### ISSUE TITLE
 Int and float different behavior with TypeError “object layout differs from”

### ISSUE THREAD

**Issue by bicofevo** [python/cpython#100037]
# Bug report
Next code:
``` python
class A(int):
    pass

class B(int):
    pass

a = A(1)
a.__class__ = B
```

Results in `TypeError: __class__ assignment: 'B' object layout differs from 'A'`
The very same code for `float` won’t throw any error:

```python
class C(float):
    pass

class D(float):
    pass

c = C(1.2)
c.__class__ = D
```

Adding `__slots__ = ()` to `A` and `B` definitions fixes the error:
``` python
class A(int):
    __slots__ = ()

class B(int):
    __slots__ = ()

a = A(1)
a.__class__ = B
```

Is it an expected difference in behavior for `int` and `float`? 

P.S. Real code is in the autoreload extension for jupyter, where it tries to reload the changed class and if it’s a child of `int` it throws this error.

# Your environment

- CPython versions tested on: 3.10.8
- Operating system and architecture: Windows 10, 64bit

**Comment by sobolevn** [comment]
Looks like these lines are related: https://github.com/python/cpython/blob/4cc63e0d4e4cf3299dcc0ea81616ba072ae5589d/Objects/typeobject.c#L5188-L5236

**Comment by Eclips4** [comment]
This works fine in 3.12+ verions.
@bicofevo can you confirm this?

**Comment by bicofevo** [comment]
> This works fine in 3.12+ verions. @bicofevo can you confirm this?

Yes, I confirm it works fine in 3.12+ versions, thank you very much!
