### ISSUE TITLE
Netlify builds happen for PRs that do not change docs

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100072]
# Bug report

After https://github.com/python/cpython/pull/92852 all PRs get a notification from `netlify` about new doc builds. Example: https://github.com/python/cpython/pull/100070 (notice no `Doc/` changes made)

I don't think it is right:
1. We are wasting resources for no good reason
2. It is a noise for both contributors and core devs

But, `netlify` has `build.ignore` option that can work similarly to these lines: https://github.com/python/cpython/blob/7031275776f43c76231318c2158a7a2753bc1fba/.github/workflows/doc.yml#L23-L26
Docs: https://docs.netlify.com/configure-builds/ignore-builds/

I will send a PR to test it :)

### Linked PRs
* gh-100074

**Comment by sobolevn** [comment]
@hugovk looks like we haven't solved this. Example PR that should not have this message, but still received it: https://github.com/python/cpython/pull/100114

**Comment by hugovk** [comment]
There's two things going on here.

First, deploys are now being cancelled, as a result of PR https://github.com/python/cpython/pull/100074. 👍 

We can see that from the comment ("Deploy Preview for python-cpython-preview canceled"), the status checks ("Deploy canceled") and the [logs](https://app.netlify.com/sites/python-cpython-preview/deploys/6391e0f9116d730008ac8fb9):

```
3:05:11 PM: Detected ignore command in Netlify configuration file. Proceeding with the specified command: 'git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF . ../netlify.toml'
3:05:11 PM: User-specified ignore command returned exit code 0. Returning early from build.
3:05:11 PM: Creating deploy upload records
3:05:11 PM: Failed during stage 'checking build content for changes': Canceled build due to no content change
```

Second, the [deploy notifications](https://docs.netlify.com/site-deploys/notifications/) need to be turned off. I think this can only be done in the admin settings on Netlify, rather than [config](https://docs.netlify.com/configure-builds/file-based-configuration/), and only one person currently has access, but hopefully we'll get more soon.

**Comment by sobolevn** [comment]
Yes, looks like it: https://docs.netlify.com/site-deploys/notifications/#github-pull-request-comments

**Comment by CAM-Gerlach** [comment]
Just to note, we've gotten an substantial and increasing volume of complaints about these comments from the core developers, as it is causing a large amount of noise and annoyance. While we had a fix ready to go within hours of Neltify being initially enabled, unfortunately as mentioned the blocker here is lack of bus-factor on people with appropriate permissions on the Netlify side. If we could get @Mariatta and @hugovk added there, we can not only solve this problem, but also be able to be responsive to any future issues, while reducing excess load on critical, hardworking infrastructure staff. @ewdurbin ?

Also, for the record, this is the config we need under the Notifications settings:

![image](https://user-images.githubusercontent.com/17051931/208015737-38ce6656-d16e-4497-9d2b-160c12b84edf.png)

**Comment by ewdurbin** [comment]
Settings updated. Unfortunately it looks like netlify’s billing won’t allow me to add additional members at this time.

I’ll email their support to ask if we can get additional users on our plan.

**Comment by hugovk** [comment]
Thank you!

https://www.netlify.com/legal/open-source-policy/ says (emphasis added):

> Netlify loves open source! To show our commitment, we’ve created an Open Source plan to enable projects working on open-source-licensed software to host websites containing information directly related to the community around that software. Our Open Source plan has the same features and limits as our [Pro plan](https://www.netlify.com/pricing/#teams), _with the addition of free unlimited team members_.

**Comment by ewdurbin** [comment]
Yes, and it seems we may not be upgraded to the latest Open Source plan.

**Comment by CAM-Gerlach** [comment]
Thanks @ewdurbin , hopefully they'll respond soon so we don't have to bother you for anything like this in the future! I think we can close this particular issue now, since both parts are now solved.
