### ISSUE TITLE
Certain seeds give less than n random bits in random.getrandbits(n) 

### ISSUE THREAD

**Issue by ValliamaiRM** [python/cpython#100071]
When trying to create a 100-bit long random-bit string using the following code -

```python
random.seed(83) 
rawkey = str('{0:100b}'.format(random.getrandbits(numqubits)))
```

The output has only 99 bits and the first element is a space. 
While other seed values give out 100 bits, this seed and some others give 99 with a space in the zeroth index.,

One possible reason -

```python
random.seed(83)
a= random.getrandbits(100) 
```

this code gives 'a' the value 622476978264770105113814767400 and this in binary has only 99 digits. 

- CPython versions tested on: Python 3.9.12 (main, Apr  5, 2022, 06:56:58) 
                                                [GCC 7.5.0] :: Anaconda, Inc. on linux
- Operating system and architecture: Distributor ID:	Ubuntu
                                                           Description:	Ubuntu 20.04.4 LTS
                                                           Release:	20.04
                                                           Codename:	focal

**Comment by ronaldoussoren** [comment]
I don't think this is a bug, the first random bit is 0.  Try using ``"{0:0100b}"`` as the format string to include leading zero's in the formatted string.

**Comment by rhettinger** [comment]
As Ronald noted, there is not a bug here.  You've just got a formatting issue.  Just change the format string to `{0:0100b}` to show the leading zeros.
