### ISSUE TITLE
support emoji as identifier

### ISSUE THREAD

**Issue by liudonghua123** [python/cpython#100069]
# Feature

Currently, python support a wide range of Unicode as identifier. However, when I tried to use some emoji as identifier like variable name or function name, it is not allowed.

It would make some code more interesting and funnier if it can support emoji as identifier.

![image](https://user-images.githubusercontent.com/2276718/206135026-cc7b0cff-4cab-43ba-8149-d356fafc3db8.png)

**Comment by encukou** [comment]
This kind of suggestion should be discussed in the [ideas](https://discuss.python.org/c/ideas/6) forum first.
(I don't expect us to add emoji identifiers – but post to Ideas to get explanations why.)
