### ISSUE TITLE
test_posix fails when os.getpgrp() is missing

### ISSUE THREAD

**Issue by vstinner** [python/cpython#100046]
On "x86 Gentoo Installed with X 3.x" buildbot worker, the C function getpgrp() is not longer available: configure output ``checking for getpgrp... yes`` of [build 3488](https://buildbot.python.org/all/#builders/464/builds/3488) became ``checking for getpgrp... no`` in the next [build 3489](https://buildbot.python.org/all/#builders/464/builds/3489).

Problem: when os.getpgrp() is missing, test_posix fails with:

```
======================================================================
ERROR: test_setpgroup (test.test_posix.TestPosixSpawn.test_setpgroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/cpython/3.x.ware-gentoo-x86.installed/build/target/lib/python3.12/test/test_posix.py", line 1654, in test_setpgroup
    setpgroup=os.getpgrp()
              ^^^^^^^^^^
AttributeError: module 'os' has no attribute 'getpgrp'. Did you mean: 'setpgrp'?

======================================================================
ERROR: test_setpgroup (test.test_posix.TestPosixSpawnP.test_setpgroup)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/buildbot/buildarea/cpython/3.x.ware-gentoo-x86.installed/build/target/lib/python3.12/test/test_posix.py", line 1654, in test_setpgroup
    setpgroup=os.getpgrp()
              ^^^^^^^^^^
AttributeError: module 'os' has no attribute 'getpgrp'. Did you mean: 'setpgrp'?
```

**Comment by vstinner** [comment]
@zware: Hi. Any idea why the getpgrp() function is gone? Was it a system update between build 3488 (today, 6h20 PM) and build 3489 (today, 7h44 PM)? Sorry, I don't know the timezone used by buildbot for timestamps.

**Comment by zware** [comment]
I did in fact run updates on that machine earlier today, not sure why that function disappeared, though.  One of the updates was to glibc as well as a kernel update; I've just finished the reboot to finalize those updates and have some small hope that that will fix the issue.  If not, I can try to revert glibc tomorrow.

**Comment by vstinner** [comment]
Hum, pyconfig.h has in fact two checks:

```
/* Define if getpgrp() must be called as getpgrp(0). */
/* #undef GETPGRP_HAVE_ARG */

/* Define to 1 if you have the `getpgrp' function. */
#define HAVE_GETPGRP 1
```

HAVE_GETPGRP is to know if the function exists, and the second is if it should be called as getpgrp() or getpgrp(0). Modules/posixmodule.c uses:

```c
#ifdef GETPGRP_HAVE_ARG
    return PyLong_FromPid(getpgrp(0));
#else /* GETPGRP_HAVE_ARG */
    return PyLong_FromPid(getpgrp());
#endif /* GETPGRP_HAVE_ARG */
```

**Comment by vstinner** [comment]
"x86 Gentoo Installed with X 3.x" is back to green, I close the issue.

@zware: Thanks to fixing the worker ;-)
