### ISSUE TITLE
CNRI license statement in Python 2.5 file

### ISSUE THREAD

**Issue by stefan-hdt** [python/cpython#100079]
The file https://github.com/python/cpython/blob/2.5/Lib/re.py states the CNRI as applicable license. As far as I understand the licening of Python 2.5, the Python Software License shall be applicable for all Python code. Is that correct? In this case, does the license information in the file re.py not reflect this change of license?

Thanks for looking into this.

**Comment by zware** [comment]
Python 2.5 has been unmaintained for over 11 years now.  The licensing commentary within the `2.5` tag may well be incorrect (possibly even from when it was still maintained), but it will not be changed now.  If there are issues with licensing clarity in currently-maintained versions (3.7+ as of this writing), please open new reports for them.  Thanks!

**Comment by CAM-Gerlach** [comment]
FWIW, the license notice is still there in the current `main` version: https://github.com/python/cpython/blob/main/Lib/re/__init__.py
