### ISSUE TITLE
Error code tables in _ssl and err_name_to_codes are no longer used

### ISSUE THREAD

**Issue by davidben** [python/cpython#100062]
(Filing this for a PR I'll upload shortly.)

Prior to https://github.com/python/cpython/pull/25300, the make_ssl_data.py script used various tables, exposed in `_ssl`, to update the error list. After that PR, these are no longer used and we can trim that a bit. This gets them out of the way if, in the future, OpenSSL provides an API to do what the code here is doing directly. (https://github.com/openssl/openssl/issues/19848)

### Linked PRs
* gh-100063

**Comment by zooba** [comment]
Thanks!
