### ISSUE TITLE
Confusing docstring for `math.floor()`?

### ISSUE THREAD

**Issue by fireattack** [python/cpython#100058]
# Documentation

https://github.com/python/cpython/blob/b72014c783e5698beb18ee1249597e510b8bcb5a/Modules/clinic/mathmodule.c.h#L26

I assume it means Integer?

**Comment by AlexWaygood** [comment]
No, it means integral, as in, "a number conforming to the `Integral` interface laid out in PEP 3141, and formalised in the form of [`numbers.Integral`](https://docs.python.org/3/library/numbers.html#numbers.Integral).

`math.floor()` returns whatever `type(x).__floor__(x)` evaluates to. For most stdlib numeric types, this does indeed return an `int`. But the data model specifies that if you define `__floor__` on a custom class, it's okay for it to return a non-`int` type, as long as the returned object conforms to the `numbers.Integral` interface: https://docs.python.org/3/reference/datamodel.html#object.__floor__.

**Comment by fireattack** [comment]
Thank you for your detailed explanation!

I tried to search the whole sentence which only lands here, so I naively thought it was a typo.  I should really search "python integral" instead. 

Again, thanks for your time to kindly explain it.

**Comment by AlexWaygood** [comment]
No problem, glad I was helpful! :)

**Comment by pochmann** [comment]
If you view the [web documentation](https://docs.python.org/3/library/math.html#math.floor), you'll see `Integral` is a link to `numbers.Integral`.

For the discussion that led to the [change](https://github.com/python/cpython/commit/129fe04d4deec15f9ca0ee79776e0c4335fc12e7) to "Integral" there, see #70699.

**Comment by AlexWaygood** [comment]
Yes, I agree that it's a slightly unusual construction in the docstring here. But it is in keeping with the terse style of the other docstrings in the `math` module. I suppose we could change it to `Return the floor of x as an Integral number.\n`. But I'm not sure that the addition of the extra word would make it significantly clearer for those who aren't familiar with PEP-3141/the `numbers` module/the data model.
