### ISSUE TITLE
Make it possible to collect pystats of parts of runs

### ISSUE THREAD

**Issue by mdboom** [python/cpython#100143]
The `--enable-pystats` system has a couple of important shortcomings:

- When stats is turned off, stats aren't dumped (on quit or explicitly). Therefore, it's impossible to put `sys._stats_on`/`sys._stats_off` calls around tested code and get the results out.
- Since stats collection is on by default, it is very fiddly to exclude code for stats, especially for things that fire off subprocesses, e.g. pyperformance.

@markshannon's [suggestion](https://github.com/faster-cpython/ideas/issues/511) is to:

- Having stats off by default
- Add an `-Xstats` flag to turn it on at startup
- Always dump out stats

### Linked PRs
* gh-100144

**Comment by markshannon** [comment]
We also need to add a mechanism to always have stats on, for gathering stats for applications which cannot be modified or spawn subprocesses.

Adding an environment variable analog for `-Xstats`, e.g. `PYTHONSTATS` should be sufficient.

**Comment by hauntsaninja** [comment]
Thanks, looks like this is completed
