### ISSUE TITLE
Irritation regarding the padding of the date in the startup text for Python

### ISSUE THREAD

**Issue by PedanticHacker** [python/cpython#100153]
The startup text of Python 3.11.1 in a command-line interface produces the text like this (well, at least for me):
```
Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```
Have you spotted the issue? Well, then you're not as pedantic as you think.

HINT: There a 2 spaces (instead of just 1) lurking in that text. There's a too big of a gap between `Dec` and `6`, see? The date is not formatted properly, so the `__DATE__` macro of C has a formatting issue.

Does anyone care to fix this?

And while you're at it, there's also a missing Oxford comma in `Type "help", "copyright", "credits" or "license" for more information.`, so the text should be `Type "help", "copyright", "credits", or "license" for more information.`.

**Comment by PedanticHacker** [comment]
Additional note: This date gap issue is only present in Python 3.11.1. No prior version of Python had this. So, this came with the micro release of Python 3.11.1.

**Comment by iritkatriel** [comment]
Please use meaningfully descriptive titles when reporting issues on the bug tracker.

**Comment by eryksun** [comment]
> No prior version of Python had this. 

Actually, it appears to be a consistent formatting problem for single-digit days of the month. For example, Python 3.10.1:

```text
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 18:54:59) [MSC v.1929 32 bit (Intel)] on win32
>>>
```

It's padded for two digits.

**Comment by PedanticHacker** [comment]
Ah, then you’re even more pedantic than me. I have only spotted this today after upgrading to Python 3.11.1 and starting it up in the command-line interface.

So, how can we fix this? It looks awful!

**Comment by eryksun** [comment]
> there's also a missing Oxford comma in `Type "help", "copyright", "credits" or "license" for more information.`, so the text should be `Type "help", "copyright", "credits", or "license" for more information.`.

That's a matter of opinion and one's dialect of English. In British English, normally the [serial comma](https://www.gsbe.co.uk/grammar-commas-and-full-stops.html#commas:%20the%20serial%20comma%201) is omitted after the penultimate word or phrase in a series. The conjunction between the last two items is enough to separate them.

**Comment by eryksun** [comment]
`Py_GetBuildInfo()` uses the standard `__DATE__` macro. It's [specified](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) as follows: 

>The date of translation of the preprocessing translation unit: a character
string literal of the form `"Mmm dd yyyy"`, where the names of the
months are the same as those generated by the `asctime` function, and the
first character of `dd` is a space character if the value is less than 10. If the
date of translation is not available, an implementation-defined valid date
shall be supplied.

Personally, I don't think it's something to worry about. Anything that uses `__DATE__` will have the same formatting. It's not specific to Python.

**Comment by ericvsmith** [comment]
I agree this is not worth changing. And it may well break something that's expecting this format.

**Comment by PedanticHacker** [comment]
Well, then live with erroneous formatting. But it is obvious that this is unprofessional. When the format is such that it substitues a space for a non-existent value, that's bad formatting. It should at least prepend a `0` if it's a requirement that the value for a day in a date should include a 2-character integer. That way, no one's code would break even if they rely on a 2-character value for a day in a date.

Thoughts?

**Comment by PedanticHacker** [comment]
The specification for the `__DATE__` macro in C is such that *[...] the first character of `dd` is a space character if the value is less than 10*`, but I personally think that's bad. There should be a `0` as the padding character in the absence of the first character of `dd`. That's the standard way dates are written in formal texts. I'm not sure why C specifies it with a space.

**Comment by PedanticHacker** [comment]
We could substitute the space character with a `0`, couldn't we? The C specification is just wrong. Let's be more vigilant in Python.

**Comment by hugovk** [comment]
`__DATE__` with this behaviour was added to the [ANSI C standard](https://en.wikipedia.org/wiki/ANSI_C) in 1989, the very first C standard (aka C89).

Here's page 94 of [ISO/IEC 9899:1990 (PDF)](https://web.archive.org/web/20200909074736if_/https://www.pdf-archive.com/2014/10/02/ansi-iso-9899-1990-1/ansi-iso-9899-1990-1.pdf):

<img width="534" alt="image" src="https://user-images.githubusercontent.com/1324225/206852537-c001547b-9a1f-4e75-8e85-a6e7aed0e939.png">

This predates Python itself.

It's not worth changing, it could break anyone parsing:

```console
$ python --version --version
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]
```
```pycon
>>> sys.version
'3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]'
```

**Comment by PedanticHacker** [comment]
I totally understand the issue that we cannot disregard the C specification. I'll try to get involved with the guys that write these specifications and propose a change for the `__DATE__` macro to include a `0` instead of a space in `dd` in the absence of the first `d` character.

I think that a new specification for C is in the works right now, so there's my chance. Wish me luck.

**Comment by ericvsmith** [comment]
For an example of how it could break parsing:

```pycon
>>> sysversion = '3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]'
>>> eval(sysversion.split()[3])
6
>>> sysversion = '3.11.1 (v3.11.1:a7a450f84a, Dec 06 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)]'
>>> eval(sysversion.split()[3])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    06
    ^
SyntaxError: leading zeros in decimal integer literals are not permitted; use an 0o prefix for octal integers
```
I'm not saying that such parsing is common, but it would not surprise me at all if someone is doing basically the equivalent of this. We will not run the risk of breaking someone's code when the change is purely for cosmetic reasons.

**Comment by PedanticHacker** [comment]
Maybe we could do some formatting on the date? The C spec also says that *If the date of translation is not available, an implementation-defined valid date shall be supplied.*, so we could just skip the `__DATE__` macro and format it ourselves, maybe even locale aware.
