### ISSUE TITLE
Enum Docs does MultiplesOfThree instead of PowersOfThree

### ISSUE THREAD

**Issue by Beweeted** [python/cpython#100174]
# Documentation

Current:
The example includes a class `PowersOfThree`. Inside the function `_generate_next_value_()`, it executes `return (count + 1) * 3` (Line 5), which is multiples of three instead of powers of three.

Expected:
Line 5 should be updated to: `return 3 ** (count + 1)`, and the output on Line 9 should be updated to 9.
OR
Line 2 and Line 8 should be updated to `MultiplesOfThree`

https://docs.python.org/3/library/enum.html#enum.Enum._generate_next_value_

### Linked PRs
* gh-100178
* gh-100181

**Comment by Beweeted** [comment]
Or I guess renaming it to `ThirdPowers` would also work.

**Comment by ethanfurman** [comment]
Let's fix the math.  @Beweeted would you like to create the PR?

**Comment by ethanfurman** [comment]
Many thanks!
