### ISSUE TITLE
Too many misses in BINARY_SUBSCR_LIST_INT

### ISSUE THREAD

**Issue by sweeneyde** [python/cpython#100188]
The expression `my_list[-1]` [gets specialized](https://github.com/python/cpython/blob/70be5e42f6e288de32e0df3c77ac22a9ddf1a74b/Python/specialize.c#L1263-L1267) to `BINARY_SUBSCR_LIST_INT` every time, then it [gets deoptimized every time](https://github.com/python/cpython/blob/70be5e42f6e288de32e0df3c77ac22a9ddf1a74b/Python/bytecodes.c#L396)

~~This leads to 31%ish of `BINARY_SUBSCR_LIST_INT` executions being misses (on some programs anyway).~~ Edit: this stat was probably not accurate.

Should be an easy fix.

### Linked PRs
* gh-100189

**Comment by hauntsaninja** [comment]
Thanks for finding and fixing!
