### ISSUE TITLE
asyncio subprocess stdout occasionally lost (3.11.0 → 3.11.1 regression)

### ISSUE THREAD

**Issue by AMDmi3** [python/cpython#100133]
# Bug report

So, I've updated python from 3.11.0 to 3.11.1 and one of my utilities which runs a lot of external processes with `asyncio.create_subprocess_exec` started failing in different places in weird ways. It turned out that with some probability `asyncio.subprocess.Process.communicate()` would now return an empty stdout. Here's a repro:

```
import asyncio

async def main():
    attempt = 1
    while True:
        proc = await asyncio.create_subprocess_exec('/bin/echo', 'test', stdout=asyncio.subprocess.PIPE, stderr=asyncio.subprocess.PIPE)

        stdout, stderr = await proc.communicate()

        text = stdout.decode('utf-8').strip()

        if text != 'test':
            raise RuntimeError(f'FAIL on attempt {attempt}: output="{text}"')

        attempt += 1

asyncio.run(main())
```

You may have to wait somewhat for the problem to reproduce, but for me it fails in under 15 seconds more or less reliably. Possible output:
```
RuntimeError: FAIL on attempt 3823: output=""
```

# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: FreeBSD 13.1 amd64

### Linked PRs
* gh-100154
* gh-100398

**Comment by AMDmi3** [comment]
@kumaraditya303 FYI, there were some commits to asyncio subprocess from you recently.

**Comment by mportesdev** [comment]
I experienced this too, reported it here with some additional info:
https://discuss.python.org/t/python-3-11-1-async-subprocess-stdout-lost-when-piped/21788

**Comment by mportesdev** [comment]
For me, the following script always results with an unexpected `[b'', b'', b'baz\n']` both in Python 3.11.1 and 3.12.0a3.

```python
import asyncio


async def get_command_stdout(cmd, *args):
    proc = await asyncio.create_subprocess_exec(
        cmd, *args, stdout=asyncio.subprocess.PIPE,
    )
    stdout, _ = await proc.communicate()
    return stdout


async def main():
    return await asyncio.gather(
        get_command_stdout('echo', 'foo'),
        get_command_stdout('echo', 'bar'),
        get_command_stdout('echo', 'baz'),
    )


if __name__ == '__main__':
    print(asyncio.run(main()))
```

**Comment by gvanrossum** [comment]
Let’s bisect that repro to a specific commit.

**Comment by kumaraditya303** [comment]
Thanks for the bug report, I have a fix for this https://github.com/python/cpython/pull/100154, can you verify it that it works as you expect? Thanks @AMDmi3

**Comment by AMDmi3** [comment]
The fix works for me, thank you!
