### ISSUE TITLE
Meta issue: clean up redundant compat code

### ISSUE THREAD

**Issue by hugovk** [python/cpython#100176]
# Bug report

There's several places that have compatibility code for EOL and unsupported Python versions.

We can modernise the code by removing the obsolete bits.

I'll open separate PRs to keep the changes focused by area, and intend to use this meta issue for them all (but can also open separate issues if preferred).

### Linked PRs
* gh-100177
* gh-100190
* gh-100197
* gh-100297
* gh-101853

**Comment by sobolevn** [comment]
While looking at this, I got interested: do we even need https://github.com/python/cpython/blame/main/Tools/stringbench/stringbench.py ? It has some python2/3 compat code and the last changes to it was 10 years ago. It is clearly not up-to-date. I will raise this question on discuss.python.org

**Comment by sobolevn** [comment]
https://discuss.python.org/t/do-we-still-need-tools-io-cc-string-bench/22557

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/101853 to remove `Tools/{io,cc,string}bench`
