### ISSUE TITLE
Link in code comment no longer relevant for HTML unescaping

### ISSUE THREAD

**Issue by jcamiel** [python/cpython#100210]
# Documentation

The link in https://github.com/python/cpython/blob/0e081a089ec969c9a34f5ff25886205616ef4dd3/Lib/html/__init__.py#L28 is not longer relevant and should be replace:

- current link <http://www.w3.org/TR/html5/syntax.html#tokenizing-character-references>
- more accurate link <https://html.spec.whatwg.org/multipage/parsing.html#numeric-character-reference-end-state>

The link should explain the source of the replacements table:

```python
# see http://www.w3.org/TR/html5/syntax.html#tokenizing-character-references

_invalid_charrefs = {
    0x00: '\ufffd',  # REPLACEMENT CHARACTER
    0x0d: '\r',      # CARRIAGE RETURN
    0x80: '\u20ac',  # EURO SIGN
    0x81: '\x81',    # <control>
    0x82: '\u201a',  # SINGLE LOW-9 QUOTATION MARK
    0x83: '\u0192',  # LATIN SMALL LETTER F WITH HOOK
    0x84: '\u201e',  # DOUBLE LOW-9 QUOTATION MARK
    0x85: '\u2026',  # HORIZONTAL ELLIPSIS
    0x86: '\u2020',  # DAGGER
    0x87: '\u2021',  # DOUBLE DAGGER
    0x88: '\u02c6',  # MODIFIER LETTER CIRCUMFLEX ACCENT
    0x89: '\u2030',  # PER MILLE SIGN
    0x8a: '\u0160',  # LATIN CAPITAL LETTER S WITH CARON
 ```

### Linked PRs
* gh-100212
* gh-102044
* gh-102045

**Comment by ezio-melotti** [comment]
Fixed, thanks for the report and then PR!
