### ISSUE TITLE
New GitHub warning: `'ERROR': macro redefinition`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100213]
I think that https://github.com/python/cpython/pull/100010 is the source.

<img width="457" alt="Снимок экрана 2022-12-13 в 13 28 21" src="https://user-images.githubusercontent.com/4660275/207293591-89349d10-f531-4c95-8e4e-f2db83ce1bd8.png">

Example: https://github.com/python/cpython/commit/e4ea33b17807d99ed737f800d9b0006957c008d2 

I think we should do `#undef ERROR` beforehand.
Will send a PR!

### Linked PRs
* gh-100214

**Comment by markshannon** [comment]
OOI, do we know where `ERROR` is previously defined?

**Comment by sobolevn** [comment]
It is not in sources: 

```
» ag '#define ERROR'
Python/compile.c
59:#define ERROR -1

Python/bytecodes.c
67:#define ERROR_IF(cond, labelname) ((void)0)

Python/modsupport.c
283:#define ERROR_NEED_PY_SSIZE_T_CLEAN \

Include/internal/pycore_token.h
76:#define ERRORTOKEN      60

Modules/cjkcodecs/multibytecodec.h
120:#define ERROR_STRICT            (PyObject *)(1)
121:#define ERROR_IGNORE            (PyObject *)(2)
122:#define ERROR_REPLACE           (PyObject *)(3)
123:#define ERROR_ISCUSTOM(p)       ((p) < ERROR_STRICT || ERROR_REPLACE < (p))
124:#define ERROR_DECREF(p)                             \

```

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/100215

**Comment by eryksun** [comment]
> OOI, do we know where `ERROR` is previously defined?

The "windows.h" header includes "wingdi.h", which defines `ERROR` as a region flag with the value 0. This header gets included by "Include/internal/pycore_condvar.h": 

https://github.com/python/cpython/blob/985a71032bf055240e61259285a0b4925c925383/Include/internal/pycore_condvar.h#L39-L41

In turn, it's included by "Include/internal/pcore_gil.h", which is included by "Include/internal/pycore_runtime.h", which is included by many files.
