### ISSUE TITLE
Bare yield's behaviour undocumented

### ISSUE THREAD

**Issue by pochmann** [python/cpython#100201]
```
def g():
    yield

print(next(g()))
```
That prints `None`, but the [Yield expressions](https://docs.python.org/3/reference/expressions.html#yield-expressions) documentation doesn't say so. It only talks about *"returning the value of `expression_list` to the generator’s caller"*, but doesn't say that `None` gets returned if the optional `expression_list` isn't given.

Maybe it's stated in the PEPs referenced at the end, but I think one shouldn't have to look that far. It should be right there in the documentation.

### Linked PRs
* gh-100416
* gh-100664
* gh-100665

**Comment by ramvikrams** [comment]
`If __next__() is used (typically via either a for or the next() builtin) then the result is None`, this line is there in the doc so by it is specified when using `next()` the result will be `None`.

**Comment by pochmann** [comment]
No. That's about the value getting **into** the generator (`None` when using `__next__`, or the sent value when using `send`). I'm talking about the value getting **out** of the generator.

**Comment by ramvikrams** [comment]
> 

oh! i'll do the change then
