### ISSUE TITLE
`NameError` not raised for annotations in function scopes that reference undefined names

### ISSUE THREAD

**Issue by fenginsc** [python/cpython#100280]
If you define the following code directly outside the function:

```python
f: abcd = 3
```

You'll get an error:

```
Traceback (most recent call last):
  File "C:\Users\fenginsc\demo.py", line 1, in <module>
    f: abcd = 3
       ^^^^
NameError: name 'abcd' is not defined
```

But the same code is written within the function without any problems, and I think this a bug.

```python
def foo():
    f: abcd = 3

foo()
```

This will not cause any problems, please fix it, thanks.

**Comment by stevendaprano** [comment]
[PEP 526](https://peps.python.org/pep-0526/#runtime-effects-of-type-annotations) which introduced this feature specifies that:

"Annotations for local variables will not be evaluated ... However, if it is at a module or class level, then the type will be evaluated".

So the current behaviour is as designed.

Inside a function, there is no way to access any annotations at runtime (as local variables aren't visible to the outside), so storing the annotation is pointless. If it is pointless to store it, there is no need to evaluate it either.

Outside a function, annotations are stored in the special dunder `__annotations__`, which means they have to be evaluated at runtime.

This behaviour might change under the newly accepted PEP 649, which defers the evaluation of annotations. I'm not sure.

**Comment by JelleZijlstra** [comment]
@stevendaprano is right, and PEP 649 does not change the behavior here (https://peps.python.org/pep-0649/#annotations-on-local-variables-inside-functions).

**Comment by fenginsc** [comment]
I understand that the current design is compliant with PEP 526 or PEP 649, but I think it's necessary to evaluate type annotations for local variables inside functions, as it makes sense in the case of closures, which are uncommon but do get done.
```python
def foo1():
    x: abcd = 1
    def foo2():
        y: abcd= 2
        return x + y
    return foo2

foo1()()
```
The type annotation of variables is useful, and I think it is necessary to evaluate local variables within functions as well, thanks.

**Comment by JelleZijlstra** [comment]
If you want to change this behavior, please open a discussion on https://discuss.python.org. However, I'd currently oppose such a change:
- Type checkers already use and check local variable annotations, so the annotations are useful already in their current state.
- Evaluating local annotations will likely break some currently working and correct code that uses forward references.
- Evaluating local annotations will have some performance cost and it's not clear what the use would be. After we evaluate the annotations, where would we even put them?

**Comment by fenginsc** [comment]
@JelleZijlstra Thanks for the reply, I agree with you that the feature is really not useful at the moment, as well as there would be a lot of issues to consider if the feature were to be supported.
