### ISSUE TITLE
add to Class like Trait or Interface

### ISSUE THREAD

**Issue by AhmedBoin** [python/cpython#100267]
# Feature or enhancement

add built-in new function decorator that help to add more methods to built-in or previous projects build classes

# Pitch

I wish you add this decorator to new update to avoid rewrite it every time i start new project and would like to add new methods to existing classes in language,
Maybe you can help to make it more generic like traits that in rust 

```python
def add_to_class(Class): 
    def wrapper(obj): 
        setattr(Class, obj.__name__, obj)
     return wrapper
```

  Let’s have a quick look at how to use it. I plan to implement a class A with a method do. Instead of having code for both A and do in the same code block, I can first declare the class A and create an instance a.

```python
class A: 
    def __init__(self): 
        self.b = 1

a = A() 
```

  Next I define the method do as I normally would, but not in class A’s scope. Instead, I decorate this method by add_to_class with class A as its argument. In doing so, the method is able to access the member variables of A as I would expect if it had been defined as part of A’s definition. Let’s see what happens when I invoke it for the instance a.

```python
@add_to_class(A)
def do(self): 
    print('Class attribute "b" is', self.b)

a.do()
```

thanks alot

**Comment by AlexWaygood** [comment]
Thanks for the feature proposal! The bar for having new ideas accepted into the stdlib is quite high, however, so ideas like this need to be discussed at https://discuss.python.org/c/ideas/6 before opening an issue here. Once it's been discussed there for a while, if the idea has a reasonable level of support, we can potentially reopen this issue.
