### ISSUE TITLE
asyncio.timeout could be used as a decorator

### ISSUE THREAD

**Issue by alex-janss** [python/cpython#100283]
# Feature or enhancement

Allow `asyncio.timeout` and `asyncio.timeout_at` to also be used as decorators.

# Pitch

It would be convenient to be able to wrap coroutines with timeouts:
```
@asyncio.timeout(3)
async def foo():
    await asyncio.sleep(10)
```
This reduces nesting and makes the timeout more visible, an argument made here:  [contextlib.ContextDecorator](https://docs.python.org/3/library/contextlib.html#contextlib.ContextDecorator). Note that this functionality is included by default for any context managers created with `contextlib`, and could be easily implemented by subclassing `contextlib.AsyncContextDecorator`.

**Comment by gvanrossum** [comment]
Hm. TOOWTDI.

**Comment by alex-janss** [comment]
> Hm. TOOWTDI.

True, but `contextlib` already sets the precedent for having ContextDecorators, and the documentation there argues for the decorator functionality being preferred in certain use cases. This seems especially true in `asyncio.timeout` in cases where we simply want to wrap an entire coroutine in a timeout without doing any rescheduling.

**Comment by gvanrossum** [comment]
It’s a minor convenience at best, and we don’t have enough experience with asyncio.timeout to know whether it is needed often.

I personally find contextlib rather baroque, an prefer a sparser design. But I am repeating myself.

**Comment by kumaraditya303** [comment]
I have been using https://github.com/aio-libs/async-timeout for a long time before it was added to stdlib and never needed this. It is much better to use it as a context manager and it makes the timeout visible at call site rather than having to look at the function for its timeout. If you need this, you can create a helper decorator but it doesn't need to be in the stdlib.

**Comment by gvanrossum** [comment]
Okay, let’s pass on this.
