### ISSUE TITLE
Update test_peg_generator to not need distutils & reenable it

### ISSUE THREAD

**Issue by encukou** [python/cpython#100238]
`distutils` was removed from 3.12, as per PEP 632.
`test_peg_generator`, which uses it, was disabled. It should be updated to not need `distutils`.

See #92584

### Linked PRs
* gh-104744
* gh-104798
* gh-105135

**Comment by ramvikrams** [comment]
I'd like to work on this I looked through `test_peg_generator` but I could not find any test that importing `distuils`

**Comment by ericsnowcurrently** [comment]
@Yhg1s, this feels like a release blocker.  Thoughts?

**Comment by ericsnowcurrently** [comment]
@ramvikrams, distutils is used in Tools/peg_generator/pegen/build.py, which I'm guessing is exercised by tests under Lib/test/test_peg_generator.  See the comment in Lib/test/test_peg_generator/__init__.py.

**Comment by ramvikrams** [comment]
> @ramvikrams, distutils is used in Tools/peg_generator/pegen/build.py, which I'm guessing is exercised by tests under Lib/test/test_peg_generator.  See the comment in Lib/test/test_peg_generator/__init__.py.



Thanks I'll check it

**Comment by ericsnowcurrently** [comment]
FYI, we may want to solve this in a way that can be shared between the c-analyzer and peg_generator tools.  See https://github.com/python/cpython/issues/92584#issuecomment-1460547338.

**Comment by Yhg1s** [comment]
Yes, I consider this a release blocker for the betas (https://github.com/python/cpython/issues/92584 is left open as a release blocker for this reason).

**Comment by ramvikrams** [comment]
I read so should I replace `distutils` with `setuptools` in `Tools/peg_generator/pegen/build.py`

**Comment by lysnikolaou** [comment]
Resolved in #104798.
