### ISSUE TITLE
pprint collections with correct indentation and line breaks

### ISSUE THREAD

**Issue by BorjaEst** [python/cpython#100264]
# Feature or enhancement
pprint collections with correct indentation and line breaks.

# Pitch
It simplifies __repr__ methods in complex dataclasses.

# Previous discussion
[How to pprint custom collection](https://stackoverflow.com/questions/74801447/how-to-pprint-custom-collection)

**Comment by rhettinger** [comment]
I think the whole pprint module needs an alternate implementation built on a fresh design for easy extendibility and customization.   The current module has been pushed about as far as it can go without having to make untenable guesses about how classes want to be displayed.  ISTM there is no one size fits all solution that we can just plop in the current pprint design.

**Comment by MonadChains** [comment]
Hi @rhettinger I see there has already been a [discussion](https://discuss.python.org/t/pprint-styling-options/15947) on this issue. As a possible solution it has been proposed to add a new bool option to pprint, what do you think?
Regarding a possible new implementation of pprint, what is the process for proposing and implementing it?

**Comment by ericvsmith** [comment]
> Regarding a possible new implementation of pprint, what is the process for proposing and implementing it?

The new design should be discussed, probably on https://discuss.python.org/c/ideas/6 . Then I think a PEP would be needed.

**Comment by MonadChains** [comment]
Hi @BorjaEst,@rhettinger and @ericvsmith, I've opened a [discussion](https://discuss.python.org/t/rework-pprint-module-structure/23026) on Discuss about the reworking of pprint, feel to partecipate if you have any suggestions.

**Comment by BorjaEst** [comment]
From discussion, it seem `rich` is a nice alternative.
