### ISSUE TITLE
Adding the "bag" type

### ISSUE THREAD

**Issue by PierrickPochelu** [python/cpython#100279]
# Feature or enhancement

Bag data structure from set theory, with methods: add an element, remove an element, size of the bag, intersection, union ...

# Pitch

example:
```
A=bag(['a', 'a', 'b', 'c', 'd', 'd'])
B=bag(['c', 'd', 'd', 'e'])

print(A-B) # set theory difference
bag({'a': 2, 'b': 1, 'd': 1})

print(A.intersection(B))
bag({'c': 1, 'd': 2})

print(A.union(B))
bag({'a': 2, 'b': 1, 'c': 2, 'd': 4, 'e': 1})
```

[...]

I can push a PR (which package ? the package "collections" ?)

**Comment by sweeneyde** [comment]
Perhaps you're looking for [collections.Counter](https://docs.python.org/3/library/collections.html#collections.Counter)?

**Comment by PierrickPochelu** [comment]
Yes
