### ISSUE TITLE
Extend math.dist and math.hypot with non-Euclidian distances

### ISSUE THREAD

**Issue by alexprengere** [python/cpython#100269]
# Feature or enhancement

I think we could improve [math.dist](https://docs.python.org/3/library/math.html#math.dist) and [math.hypot](https://docs.python.org/3/library/math.html#math.dist) to handle non-Euclidian distances.

If the idea gains traction, I would be interested to implement this.

# Pitch

In many areas, non-Euclidian distances are very useful:
* when doing ["Taxicab geometry"](https://en.wikipedia.org/wiki/Taxicab_geometry), Manhattan distance is used
* when computing moves of a King on a chess board, [Chebyshev distance](https://en.wikipedia.org/wiki/Chebyshev_distance) is used
* more generally, those distances are particular cases for the [Minkowski distance](https://en.wikipedia.org/wiki/Minkowski_distance), where the distance is defined for every integer `n`:

```python
def dist(p, q, *, n):
    return sum(abs(px - qx) ** n for px, qx in zip(p, q)) ** (1 / n)

# n=2 is the Euclidian distance
dist([0, 1], [3, 2], n=2)  # 3.1622

# n=1 is the Manhattan distance
dist([0, 1], [3, 2], n=1)  # 4.0

# n -> inf converges to the Chebyshev distance
dist([0, 1], [3, 2], n=inf)  # 3.0
```

When n converges to infinity, the Minkowski distance becomes Chebyshev distance, that can be computed as:

```python
def chebyshev(p, q):
    return max(abs(px - qx) for px, qx in zip(p, q))
```

# Proposal

My proposal is to add a *keyword only* parameter to both `math.dist` and `math.hypot`. This parameter would be an `int` (> 1) or `math.inf`, and it would translate in pure Python code as:

```python
def dist(p, q, *, n=2):
    if math.isinf(n):
        return max(abs(px - qx) for px, qx in zip(p, q))    
    return sum(abs(px - qx) ** n for px, qx in zip(p, q)) ** (1 / n)

def hypot(*coordinates, n=2):
    if math.isinf(n):
        return max(abs(c) for c in coordinates)    
    return sum(abs(c) ** n for c in coordinates) ** (1 / n)
```

This would give a very handy tool:

```python
manhattan_distance = functools.partial(math.dist, n=1)
manhattan_distance([0, 1], [2, 2])  # 3

king_distance = functools.partial(math.dist, n=math.inf)
king_distance([1, 1], [8, 8])  # king moves accross the board in 7 moves
```

# Naming

Minkowski distance have their parameter usually named `p`, but `p` and `q` are already used as the parameter names for `math.dist` and `math.hypot`. I went for `n` here, but obviously another name could be used, like `dimension` or `order`.

# Previous discussion

I looked and found no other mentions of this. From the Git history, I understand that @rhettinger implemented both `math.dist` and `math.hypot`, so I guess he would be the one deciding is this is a good idea or not.

**Comment by pochmann** [comment]
`math.hypot(1e300, 1e300)` works fine, gives `1.4142135623730952e+300`.

`hypot(1e300, 1e300, n=2)` with your implementation crashes with `OverflowError: (34, 'Numerical result out of range')`.

**Comment by alexprengere** [comment]
This is not the final implementation (that would be in `Modules/mathmodule.c`), this is just a Python equivalent to discuss semantics.
In the same way, the Python docs mention:
* [`math.hypot`](https://docs.python.org/3/library/math.html#math.hypot) being equivalent to `sqrt(sum(x**2 for x in coordinates))`
* [`math.dist`](https://docs.python.org/3/library/math.html#math.dist) being equivalent to `sqrt(sum((px - qx) ** 2.0 for px, qx in zip(p, q)))`

**Comment by sweeneyde** [comment]
> In many areas

Can you explain your use cases? p-norms are certainly something that people care about theoretically, but is there a practical reason it belongs in the standard library beyond something like "it could be generalized so it should be"?

I'd tend to think that this belongs in a more specialized number-crunching library like numpy, and in fact, there's [`numpy.linalg.norm(x, ord=None, axis=None, keepdims=False)`](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html) which has everything you ask for and more.

The reason `math.hypot` and `math.dist` are useful in my mind is that they avoid the numerical pitfalls of the naive implementation of the 2-norm. The same can be achieved for 1-norms using the built-in `abs()` and `math.fsum`, and for box norms with the built-in `abs()` and `max()`. Beyond `p in {1,2,inf}`, I imagine that there is a huge dropoff in the prevalence of different p-values, particularly in practical applications.

**Comment by rhettinger** [comment]
Thank you for the suggestion, but I concur with Dennis that this is out of scope for us and is best left for specialized libraries.  

In general, something is a candidate for our math module if it is part of C's mathlib, if it appears in middle school or high school math, or is something that we need elsewhere in the standard library.   We have a similar policy for the statistics module as well.

**Comment by alexprengere** [comment]
Indeed my use cases where only for `p` in `{1, 2, inf}`, mostly centered around puzzle solving and coding problems.

I absolutely understand the need to have clear guidelines about what to include or not, and the maintenance burden of such additions. Your replies make sense. Thanks a lot for your insights!

**Comment by pochmann** [comment]
> This is not the final implementation

To be clearer: my point was that the current Euclidean one goes to some lengths to work (and be accurate) even for "tricky" inputs, and I wondered (didn't look into the details, might not understand the math) whether that can also reasonably easily be done for other ones.

https://github.com/python/cpython/blob/81f7359f67a7166d57a10a3d5366406d9c85f1de/Modules/mathmodule.c#L2483-L2489
