### ISSUE TITLE
`sysconfig.get_default_scheme` `versionadded` vs `versionchanged`

### ISSUE THREAD

**Issue by FFY00** [python/cpython#100206]
# Documentation

`get_default_scheme` used to be private and called `_get_default_scheme`, but in GH-24644, it was made public. That PR uses the `versionchanged` directive to document this, but this is confusing to users, I believe the correct directive should be `versionadded`.

### Linked PRs
* gh-100207
* gh-100216
* gh-100217

**Comment by hugovk** [comment]
Merged and backported, thank you!
