### ISSUE TITLE
Ensurepip fails ungracefully when mimetype is missing from Windows registry 

### ISSUE THREAD

**Issue by BlipRanger** [python/cpython#100256]
# Bug report

A "WinError 5 Access is denied" error occurs when ensurepip (for python 3.10 and above) is run and there are missing/inaccessible mimetypes in the Windows registry. Because ensurepip is used in the Python installer, it also fails silently there, causing pip to never be installed without alerting the user to the issue. The line in which the error occurs is here:
https://github.com/python/cpython/blob/024ac542d738f56b36bdeb3517a10e93da5acab9/Lib/mimetypes.py#L250
Bypassing that line and instead using `self._read_windows_registry(add_type)`  (which is the fallback function I believe) fixes the problem. I believe that `_mimetypes_read_windows_registry(add_type)` needs to be able to fail more gracefully when it can't find a particular mimetype in the registry. 
I found someone else describing exactly the issue [here](https://discuss.python.org/t/ensurepip-failing-with-access-is-denied-error-when-attempting-to-read-windows-registry/21482). 

# Your environment

- CPython versions tested on: 3.10, 3.11
- Operating system and architecture: Windows 10 LTSC, x64

### Linked PRs
* gh-122047
* gh-122786
* gh-122787

**Comment by huanghe2015** [comment]
Same thing happened with [me](https://discuss.python.org/t/ensurepip-failing-with-access-is-denied-error-when-attempting-to-read-windows-file/30241/11) ,[Patrick](https://discuss.python.org/t/ensurepip-failing-with-access-is-denied-error-when-attempting-to-read-windows-registry/21482) and [Stackoverflow](https://stackoverflow.com/questions/74129176/winerror-5-when-importing-openpyxl).

**Comment by LucasEsposito** [comment]
Opened a [PR](https://github.com/python/cpython/pull/122047) to address this issue

**Comment by hugovk** [comment]
Triage: Closing, PRs have been merged and backported.
