### ISSUE TITLE
add a `LIBFFI_LIBS` to `setup.py` allowing to override the autodetection

### ISSUE THREAD

**Issue by mmomtchev** [python/cpython#100236]
# Feature or enhancement

Currently the libffi autodetection supports an include override through `LIBFFI_INCLUDEDIR` but overriding the library requires patching `setup.py`

# Pitch

Typical usage would be to link vs `libffi_pic.a` when building an embeddable Python that is expected work across Linux distros

**Comment by zware** [comment]
`setup.py` has been removed in v3.12 (`main`), can you try it out and see if things work as you want there?

**Comment by mmomtchev** [comment]
I confirm that `LIBFFI_LIBS` on 3.12 alpha (`main`) does exactly what I was asking for

**Comment by zware** [comment]
Excellent, thanks for confirming!
