### ISSUE TITLE
Convert more functions in `bltinsmodule.c` to Argument Clinic

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100357]
# Feature or enhancement

There are several functions that are still not coverted to argument clinic (while they even say `AC: cannot convert yet, as needs PEP 457 group support in inspect`). I've found:
- `vars`
- `getattr`
- `dir`
- `next`
- `iter`

I will send a PR with these functions converted shortly.

### Linked PRs
* gh-100358

**Comment by abdnafees** [comment]
What's an Argument Clinic?

**Comment by sobolevn** [comment]
@abdnafees you can read about it here: https://docs.python.org/3/howto/clinic.html :)

**Comment by abdnafees** [comment]
@sobolevn Thank you.
