### ISSUE TITLE
Calling python code from c++ gives unexpected number of references

### ISSUE THREAD

**Issue by jhaggle** [python/cpython#100334]
I am running this C++ code:

```c++
#include <Python.h> 
#include <stdio.h>
#include <iostream>
#include <sstream>

int main(int argc, char** argv) {

	// 1) initialize Python
	Py_Initialize();
	PyRun_SimpleString("import sys");
	PyRun_SimpleString("sys.path.append(\".\")");
	PyRun_SimpleString("print(sys.path)");

	// 2) Import the python module
	PyObject* pName = PyUnicode_FromString("module1");
	assert(pName != NULL);
	PyObject* pModule = PyImport_Import(pName);
	assert(pModule != NULL);

	// 3) Get a reference to the python function to call
	PyObject* pDict = PyModule_GetDict(pModule);
	assert(pDict != NULL);
	PyObject* pFunc = PyDict_GetItemString(pDict, (char*)"getInteger");
	assert(pFunc != NULL);

    // 4) Call function
	PyObject* pValue = PyObject_CallObject(pFunc, NULL);

	Py_XDECREF(pValue);
	Py_XDECREF(pFunc);
	Py_XDECREF(pDict);
	Py_XDECREF(pModule);
	Py_XDECREF(pName);

	Py_Finalize();
```

The imported module is called `module1.py` and has this content:

```py
def getInteger():
    print('Python function getInteger() called')
    c = 100*50/30
    return c
```

It works fine if I comment out the `Py_XDECREF` lines. I suppose, however, that it causes memory leaks in such a case. When the `Py_XDECREF` lines are commented in, the code execution behaves unexpected. First of all, I don't understand the number of references. Why is there for example seven references to pName? Second, why do I get a negative refcount-error when using `Py_XDECREF`? As I understood `Py_XDECREF` should be safe in this respect, and the current error should only be possible if I use `Py_DECREF`? Third and most importantly: How to I change the code so that it works? 

This is how the local variables look when the code reaches the line `Py_XDECREF(pValue)` but before it executes:

[![enter image description here][1]][1]

After executing `Py_XDECREF(pValue);` it looks like this:

[![enter image description here][2]][2]

After executing `Py_XDECREF(pFunc);` it looks like this:

[![enter image description here][3]][3]

Finally when executing `Py_XDECREF(pDict);` I get the following error:

```
D:\a\1\s\Include\object.h:497: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0000018CA6726410 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized
Current thread 0x000086b0 (most recent call first):
<no Python frame>
```
[![enter image description here][5]][5]

  [1]: https://i.stack.imgur.com/OBbxm.png
  [2]: https://i.stack.imgur.com/2ozmm.png
  [3]: https://i.stack.imgur.com/r1LRj.png
  [4]: https://i.stack.imgur.com/wo8x1.png
  [5]: https://i.stack.imgur.com/oduBf.png

**Comment by JelleZijlstra** [comment]
`PyDict_GetItemString` returns a borrowed reference (https://docs.python.org/3/c-api/dict.html) so it's incorrect to DECREF its return value. This is also true for `PyModule_GetDict`. However, the other functions you call return new refs, so their return values should be DECREFed.

**Comment by jhaggle** [comment]
> 

Thanks for the answer. Could you also explain how there can be seven references to `pName` above?

**Comment by ronaldoussoren** [comment]
> Thanks for the answer. Could you also explain how there can be seven references to `pName` above when the code reaches the line Py_XDECREF(pValue)? Where do they all come from? Thanks again!

At least some of the references are from the import system, in the current implementation ``pName`` is used as the value for the ``__name__`` attribute of the imported modules (on first import) and for the key in the ``sys.modules`` dict (again on first import). That's something that you shouldn't rely on and may change in future versions.

That said, in general that's not something you should have to worry about when you follow the rules about reference counting (as described in [the manual](https://docs.python.org/3/extending/extending.html#reference-counts).
