### ISSUE TITLE
Optimize `asyncio.get_running_loop`

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#100363]
`asyncio.get_running_loop` is one of the most performance critical functions in `asyncio`. With https://github.com/python/cpython/issues/66285 the running loop can be reset  in the fork handler thereby avoiding the need for the `getpid` checks. The whole running loop holder object is unnecessary now and adds up unnecessary dependent memory loads. 

Benchmark: 
```py
import asyncio
from pyperf import Runner

async def main():
    for i in range(10000):
        asyncio.get_running_loop()


runner = Runner()
runner.bench_async_func("main", main)
```

Result: 

| Benchmark | base    | patch                 |
|-----------|:-------:|:---------------------:|
| main      | 5.03 ms | 328 us: 15.33x faster |

The numbers speak for themselves. 

### Linked PRs
* gh-100364

**Comment by gvanrossum** [comment]
> `asyncio.get_running_loop` is one of the most performance critical functions in `asyncio`.

Do you have data about this? Does it show up in profiles of real functions, or do you have call counts or whatever? Usually I imagine the call is followed by a much more expensive computation.

**Comment by kumaraditya303** [comment]
This is based upon call counts and the fact that  most functions now internally call this function as loop argument was removed from most asyncio APIs.

**Comment by gvanrossum** [comment]
Okay, makes sense.
