### ISSUE TITLE
or and and are reversed

### ISSUE THREAD

**Issue by developerDTH** [python/cpython#100362]
```python 
en=""
enlist =[]
while (en != "exit" or len(enlist) !=10):
    en = input("Englishword or exit")
    if en !="exit":
        enlist.append(en)     
for i in range(len(enlist)):
    a=""
    for b in range(10):
        a=a+enlist[i]
    print(a)
``` 
In this code, the result of using or and the result of using and are reversed. maybe it's a bug

**Comment by stevendaprano** [comment]
What makes you think that the results of `or` and `and` are reversed? Can you show an example that doesn't involve a whole lot of extra, irrelevant code?

The for-loop doesn't contain either `or` or `and`, so it is irrelevant. But for the record, that is a very inefficient and slow way to concatenate lots of substrings into one. You should use `a = ''.join(enlist)`.

**Comment by stevendaprano** [comment]
The code seems to work fine to me. The `while` loop continues so long as *either* `en` is not "exit" or the length of `enlist` is not 10. So the only way the loop can exit is if **both** `en == "exit" and len(enlist) == 10`.

That is exactly how it should be.
