### ISSUE TITLE
 `iscoroutinefunction` returns False for wrapper functions with `update_wrapper` applied

### ISSUE THREAD

**Issue by jonasBoss** [python/cpython#100317]
When decorating a `async` function with a decorator that uses `@functools.wraps` or `update_wrapper` 
`inspect.iscoroutinefunction` returns False.

The following code demonstrates this issue:
```python
import functools
import inspect

async def fn():
    pass

assert inspect.iscoroutinefunction(fn)

def decorator(fn):
    def wrapper(*args, **kwargs):
        return fn(*args, **kwargs)
    return wrapper

assert not inspect.iscoroutinefunction(decorator(fn))

def signature_preserving_decorator(fn):
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        return fn(*args, **kwargs)

    return wrapper

assert inspect.iscoroutinefunction(signature_preserving_decorator(fn))
# AssertionError
```
I would expect the last assert statement to pass

- CPython versions tested on: 3.10.8
- Operating system and architecture: Linux 5.19.17-2-MANJARO x86_64 GNU/Linux

**Comment by JosephSBoyle** [comment]
I agree that the behaviour you describe is what I would also expect.

Searching for the phrase "def is coroutine" in the source I found this link:
https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Misc/NEWS.d/3.5.0b3.rst

>" coroutines; inspect.iscoroutine no longer uses collections.abc.Coroutine... it's intended to test for pure 'async def' coroutines only;"

**Comment by gvanrossum** [comment]
Is two lines really that much boilerplate? (If you need it enough you can write a helper that does it in one. :-)

I worry there's a fundamental problem with automatically passing the "iscoroutinefunction" bit in `functools.wraps()`: what if the decorator is something that takes an async function and produces a sync version of it (e.g. by calling `asyncio.run()` on it)? I'm not a big user of `wraps()` myself, but from reading its docs (and those for `update_wrapper()`) it is far from clear that this would be an inappropriate use for those functions -- the docs mostly talk about things like preserving the function name and docstring.

For this reason I'm not a fan of _automatically_ applying `markcoroutinefunction` in `wraps()`. But maybe we could add a new keyword arg to it (and to `update_wrapper()`) that transfers the flag?

I also note that wrapping an async function in a sync wrapper may not do the right thing. E.g. a wrapper like this typical example:
```
def logcalls(func):
    def wrapper(*args, **kwds):
        print("args=", args)
        res = func(*args, **kwds)
        print("res=", res)
        return res
```
would print the "result" immediately when a wrapped async function is called, not when it returns.

**Comment by carltongibson** [comment]
Thanks @carljm. 

I have Django's various decorators in the queue for updating to support async views correctly. I think I'd expect that I'd have to write this version that you have (with the additional lines): 

```
def signature_preserving_decorator(fn):
    @functools.wraps(fn)
    def wrapper(*args, **kwargs):
        return fn(*args, **kwargs)
    if inspect.iscoroutinefunction(fn):
       wrapper = inspect.markcoroutinefunction(wrapper)
    return wrapper
```

I note that if you define `wrapper` as `async def`, the example script passes (as expected, I guess): 

```
async def fn():
    pass

def signature_preserving_decorator(fn):
    @functools.wraps(fn)
    async def wrapper(*args, **kwargs):
        return fn(*args, **kwargs)

    return wrapper

assert inspect.iscoroutinefunction(signature_preserving_decorator(fn))
```

So then we're in the exact use-case for `markcoroutinefunction`: I need (for reasons not given in this example, but Django's usage is wrapping **both** sync and async views) to have a sync `def` function that returns a coroutine object (but I can't just call it and use `isawaitable`) so you need to trust me — In that case having to apply `markcoroutinefunction` _by-hand_ seems reasonable.
