### ISSUE TITLE
Consider adding `-Werror=unguarded-availability-new` to compiler flags for Apple platforms

### ISSUE THREAD

**Issue by indygreg** [python/cpython#100384]
# Feature or enhancement

Runtime crashes like #97897 could be prevented by turning clang's `unguaded-availability-new` warning into a fatal compile error. This can be done by adding `-Werror=unguarded-availability-new` to compiler flags.

Essentially what this warning does is cross reference undefined symbols against symbols defined in the targeted Apple SDK. If it sees a symbol introduced in a newer SDK version and that symbol isn't weakly referenced/linked, you get a warning. `-Werror` upconverts it to a fatal compiler error.

If you add this flag to release builds, the compiler prevents you from shipping binaries that ship unguarded symbol usage for targeted SDK versions. i.e. it prevents run-time crashes when binaries run on older Apple OS versions.

If you enable this setting today, you may find the 3.8 branch isn't properly gating use of `mkfifoat` and `mknodat`. (Although this may be an oddity from python-build-standalone and not a CPython bug.) 

cc @ned-deily 

---

The advantages of having this additional warning is to catch regressions such as:

- https://github.com/python/cpython/issues/123797
- https://github.com/python/cpython/issues/75782

### Linked PRs
* gh-128155

**Comment by ronaldoussoren** [comment]
3.9 and later should have weak linking support in posixmodule, this was introduced while working on support for arm64 and Universal 2 binaries.   That said, newer SDKs can introduce new APIs that require changes to that.

**Comment by zanieb** [comment]
Copying over some of my commentary from #128135

Here's an initial patch https://github.com/python/cpython/commit/36c7da4fe30b616f4b8008d309ead1f7dfd6b2ba

- I'm not sure if we should be using `unguarded-availability` or `unguarded-availability-new`?
- This flag is `clang`-only, will this help prevent regressions upstream or just avoid shipping bad code downstream?
- In https://github.com/astral-sh/python-build-standalone/issues/210, users reported if this is present in the `CFLAGS` in `sysconfig` it is used to build extension modules in some packages which causes failures. Would this be a problem here too? Is there existing infrastructure to deal with this problem?

**Comment by picnixz** [comment]
What we could do is integrate this new flag as part of our CI without necessarily making it part of the `configure` script. At least it could help without affecting local configurations?

**Comment by ned-deily** [comment]
Instead of `CFLAGS`, try adding this to [`CFLAGS_NODIST`](https://docs.python.org/3/using/configure.html#envvar-CFLAGS_NODIST). "`CFLAGS_NODIST` is used for building the interpreter and stdlib C extensions. Use it when a compiler flag should not be part of `CFLAGS` once Python is installed."

**Comment by zanieb** [comment]
Ah cool, thanks @ned-deily. I was hoping there was something like that.

Do you have any other concerns before I post the patch as a pull request?

I think my most important open question is

> This flag is `clang`-only, will this help prevent regressions upstream or just avoid shipping bad code downstream?

Is `clang` being used in CI?

**Comment by indygreg** [comment]
The Xcode C toolchain is clang. There are an extremely small number of people not using clang when targeting Apple platforms. I'm pretty sure CPython's build system implicitly requires clang for Apple targets.

**Comment by picnixz** [comment]
We use clang on build bots sanitizers (UBSan, TSan and ASan) so yes we use `clang`. And for the JIT as well since this requires LLVM.

**Comment by hugovk** [comment]
> What we could do is integrate this new flag as part of our CI without necessarily making it part of the `configure` script. At least it could help without affecting local configurations? cc @hugovk

Like with this tooling?

https://devguide.python.org/development-tools/warnings/

**Comment by zanieb** [comment]
I think the concern about it affecting users is addressed by using `CFLAGS_NODIST`, is there a different concern you have that makes this better as a warning than an error?

**Comment by ned-deily** [comment]
> I'm not sure if we should be using unguarded-availability or unguarded-availability-new?

If I understand the implications correctly, I think we should stick with `unguarded-availability` until there is a demonstrated need to restrict to `unguarded-availability-new`.

Also we specifically now check and report on supported platform / compiler combinations (see `AC_MSG_CHECKING([for PEP 11 support tier])` in `configure.ac`) which for macOS is `clang` for tier 1 support. That said, we should be careful to not deliberately break `gcc` builds; presumably the `AX_CHECK_COMPILE_FLAG([-Wunguarded-availability] ...` test in the patch should take care of that.
