### ISSUE TITLE
python-3.11.1-macos11.pkg does not include Tcl/Tk (despite claims that it does)

### ISSUE THREAD

**Issue by leahymr** [python/cpython#100394]
# Bug report

I just installed python-3.11.1-macos11.pkg.  Documentation in the installer says "This package includes its own private version of Tcl/Tk 8.6.  It does not use any system-suppoied or third-party supplied versions of Tcl/Tk."

When I tried to run IDLE, IDLE says that it can't find tk/tcl.  I had to download source code and compile it myself.

# Your environment

MacOS Monterrey (12.6) on Macbook Pro (Intel)
Python 3.11.1 for Mac
Downloaded and installed Tcl/Tk 8.6.13
Command line version of XCode

**Comment by ronaldoussoren** [comment]
I checked the file contents of the installer and the archive for the subpackge "Python_Framework.pkg" (included in the installer on the website) contains ``./Versions/3.11/lib/libtk8.6.dylib`` which is the Tk library used by tkinter.

How did you start IDLE?  And if you started it from the command-line ("python3 -m idlelib") could you check if the expected copy of python is used ("which python")? You might have to create a new Terminal window before it picks up the framework version.

**Comment by ned-deily** [comment]
As Ronald notes, it's possible you would need to start a new Terminal window after installing Python for macOS from a python.org installer .pkg. The canonical path to launch those pythons is `/Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11`; if you did a default install, symlinks to that file will also be installed in `/usr/local/bin/python3.11` and `/usr/local/bin/python3` and links to IDLE at `/usr/local/bin/idle3.11` and `/usr/local/bin/idle3.11`. If you prefer to launch IDLE by double-clicking directly from the Finder, an IDLE application icon is installed by default in the `Applications` -> `Python 3.11` folder. It's possible you launched the stripped-down `python3` at `/usr/bin/python3` which is provided by Apple's Command Line Tools; it does not include `Tcl/Tk`. BTW, as noted in the installer ReadMe, the pythons from the python.org installers do not use any system-supplied or third-party supplied versions of Tcl/Tk so installing another version of Tcl/Tk has no affect. And be assured that we actually test that IDLE launches correctly before releasing every python.org macOS installer :)

**Comment by leahymr** [comment]
Ronald, Ned,

Thank you for your kind and prompt assistance.  

I typed ‘idle3’ at the command line (I could have sworn I updated the path before doing so), and clicked on the Idle application in the Applications folder.

As it is, I can’t replicate the problem now, so I agree, it must have been User Error.

Thank you, and sorry for the inconvenience,
—Michael
