### ISSUE TITLE
A New Feature

### ISSUE THREAD

**Issue by MrFa1Q** [python/cpython#100318]
Actually, it's not an issue but it is a very humble suggestion for a new feature.. i.e. **_VARIABLE DECLARATION_**
Consider this request, THANKS FOR READING..❤

**Comment by stevendaprano** [comment]
What do you mean by "variable declaration"? Can you give a clear and concise explanation of what this feature is?

Why do you want this feature? How will it make Python better?

Did you get feedback from the community on the [python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/) or the [Discuss](https://discuss.python.org/c/ideas/6)? Or anywhere else? What did other people say?

**Comment by MrFa1Q** [comment]
never mid you can leave this issue for now.. I'll let you know when I face that kind of problem again..

Thanks for replying..!
