### ISSUE TITLE
Enum with `str` or `int` Mixin Breaking Change in Python 3.11

### ISSUE THREAD

**Issue by anze3db** [python/cpython#100458]
# Bug report

Looks like there was a breaking change with the way str and int mixins work with Enums in Python 3.11:

```python
from enum import Enum


class Foo(str, Enum):
    BAR = "bar"

# Python 3.10
f"{Foo.BAR}"  # > bar

# Python 3.11
f"{Foo.BAR}"  # > Foo.BAR
```

The same goes for Enum classes with the `int` mixin.

In my project we were relying on Foo.BAR to return the enum value, so this change broke our code. We fixed it by replacing str Enum mixin with the newly added StrEnum class (thanks for that, it's exactly what we needed!).

I think reverting the breaking change would only introduce another breaking change so that's probably not the way to go. But maybe updating the whatsnew page and call out the change there could help people stumbling into this when doing the upgrade. I've found the existing point about this change in the release notes a little bit confusing and I have already opened a PR to try and clear it up a bit: https://github.com/python/cpython/pull/100387

I've also written a longer blog post about it [here](https://blog.pecar.me/python-enum), and there has been some lively discussion in [r/python](https://www.reddit.com/r/Python/comments/zt4ot4/enum_with_str_or_int_mixin_breaking_change_in/). 

# Your environment

- CPython versions tested on: 3.11.0, 3.11.1
- Operating system and architecture: MacOS, Ubuntu 22.04

### Linked PRs
* gh-100387
* gh-104060

**Comment by JosephSBoyle** [comment]
@anze3db `StrEnum` was added in 3.11, does that work as a 'slot in' replacement for your use case?

**Comment by anze3db** [comment]
@JosephSBoyle yes, we replaced the str mixin with `StrEnum` to fix this on our end. If we could let people know about this breaking change in the what's new docs it would save me a lot of head scratching, especially since the current note about this change seems wrong (see my attempt of at least making it a bit more accurate: https://github.com/python/cpython/pull/100387)

**Comment by JosephSBoyle** [comment]
Coincidentally I've also used the mixin approach you describe in professional projects, which suggests that this use is at the very least not uncommon.

As such it makes sense that the docs also suggest a way to achieve the old behaviour, like you say @anze3db. I've added a small suggestion to your PR; hopefully that will help resolve things for others in the same position!

**Comment by anze3db** [comment]
Thank you! The text that you added would have helped me a lot when I was figuring out how to fix this 👍

**Comment by jakubroztocil** [comment]
Also, `str(HTTPStatus.OK)` now returns `'200'` instead of `'HTTPStatus.OK'`. Workaround:

```python
from enum import Enum
from http import HTTPStatus

HTTPStatus.__str__ = Enum.__str__
```

**Comment by hauntsaninja** [comment]
Improving the What's New documentation was a good call, thank you! While I also found this needlessly breaking when updating my work codebase, I don't think there's anything left to be done here.
