### ISSUE TITLE
Start running SSL tests with OpenSSL 3.1.0-beta1

### ISSUE THREAD

**Issue by illia-v** [python/cpython#100454]
# Feature or enhancement

SSL tests are run with OpenSSL 1.1.1s and 3.0.7 at the moment.
https://github.com/python/cpython/blob/84bc6a4f25fcf467813ee12b74118f7b1b54e285/.github/workflows/build.yml#L238

Let's add a fresh [3.1.0-beta1](https://www.openssl.org/blog/blog/2022/12/21/OpenSSL3.1Beta/) to the matrix.

# Pitch

OpenSSL asks to build and test against this beta release.
We ran tests for alpha and beta versions of 3.0 in the past 44fb55149934d8fb095edb6fc3f8167208035b96.

### Linked PRs
* gh-100456
* gh-100486
* gh-118262
* gh-125186

**Comment by gpshead** [comment]
good idea, thanks.

**Comment by xnox** [comment]
3.10 has enabled testing with this version of openssl and higher, thus it too needs this lib64 fixup, as otherwise ld library path is wrong and tests don't run.

**Comment by encukou** [comment]
And since #101751, 3.9 also tests with 3.1.x, I think it also needs the lib64 fixup. I don't know how it passed until now; the CI logs have expired.
