### ISSUE TITLE
"configure: error: set ac_cv_file__dev_ptmx to yes/no in your CONFIG_SITE file when cross compiling" when Cross-Compiling Python 3.8.10 for armv7

### ISSUE THREAD

**Issue by locnnil** [python/cpython#100535]
# Bug report

I'm trying to cross compile python 3.8.10 to an armv7 architecture, but I'm getting the error in configuration step:

```bash
...
configure: checking for device files
checking for /dev/ptmx... not set
configure: error: set ac_cv_file__dev_ptmx to yes/no in your CONFIG_SITE file when cross compiling
```

But I already created the file `CONFIG_SITE` with `ac_cv_file_dev_ptmx=no` inside and specified in `configure` step.

## Steps to reproduce:
export INSTALL_DIR=<some_directory_to_install_architecture_independent_files>
export DIR_HOST=<some_directory_to_install_architecture_dependent_files>

wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
tar -xvf Python-3.8.10.tar.xz
cd Python-3.8.10

touch CONFIG_SITE
echo "ac_cv_file__dev_ptmx=no" > CONFIG_SITE
chmod 666 CONFIG_SITE

./configure --host=arm-linux-gnueabi \
--build=i686-pc-linux-gnu \
--prefix=$DIR_HOST \
--exec-prefix=$INSTALL_DIR \
--disable-test-modules \
--enable-optimizations \
--disable-ipv6 \
--with-config-site=./CONFIG_SITE \
CC="/usr/bin/arm-linux-gnueabi-gcc" \
CXX="/usr/bin/arm-linux-gnueabi-g++" \
LD="/usr/bin/arm-linux-gnueabi-ld" \
CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon -O2 -fexpensive-optimizations -frename-registers -fomit-frame-pointer" \
CXXFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon -O2 -fexpensive-optimizations -frename-registers -fomit-frame-pointer" \
LDFLAGS=" -Wl,-start-group -ldl -lpthread -lm -lrt -Wl,-end-group -Wl,--rpath=$INSTALL_DIR/lib/ -Wl,--dynamic-linker=$INSTALL_DIR/lib/ld-linux.so.3 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed" \
CPP="/usr/bin/arm-linux-gnueabi-gcc -E -march=armv7-a -mfloat-abi=softfp -mfpu=neon" \
CXXCPP="/usr/bin/arm-linux-gnueabi-g++ -E -march=armv7-a -mfloat-abi=softfp -mfpu=neon" \
STRIP="/usr/bin/arm-linux-gnueabi-strip" \
OBJDUMP="/usr/bin/arm-linux-gnueabi-objdump"

## Cross-Toolchain
I'm using cross tolchain: arm-linux-gnueabi-gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0

```bash
sudo apt install -y gcc-arm-linux-gnueabi
```

# Your environment

- CPython versions tested on:
Version 3.8.10:
```bash
$ wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz
```

- Operating system and architecture:
```bash
$ uname -a

Linux 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

```bash
$ cat /etc/os-release

NAME="Ubuntu"
VERSION="20.04.5 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.5 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by LOCNNIL** [comment]
While configuring, I noticed this warning:

`configure: WARNING: unrecognized options: --disable-test-modules, --with-config-site`

It appears that these options are not effective, so I looked into the script and saw the option `--site=*`. I modified my configure command from `--with-config-site=./CONFIG_SITE` to `--site=./CONFIG_SITE`, but I am still getting the same error.

**Comment by LOCNNIL** [comment]
I solved my problem by editing the CONFIG_SITE file and inserting the following lines:

```
ac_cv_file__dev_ptmx=no
ac_cv_file__dev_ptc=no
```

I then renamed the file to config.site and set it as an environment variable before running the configure script.

```bash
CONFIG_SITE=config.site  ./configure --host=arm-linux-gnueabi
--build=i686-pc-linux-gnu
--prefix=$DIR_HOST
--exec-prefix=$INSTALL_DIR
--enable-optimizations
--disable-ipv6
--with-config-site=./CONFIG_SITE
CC="/usr/bin/arm-linux-gnueabi-gcc"
CXX="/usr/bin/arm-linux-gnueabi-g++"
LD="/usr/bin/arm-linux-gnueabi-ld"
CFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon -O2 -fexpensive-optimizations -frename-registers -fomit-frame-pointer"
CXXFLAGS="-march=armv7-a -mfloat-abi=softfp -mfpu=neon -O2 -fexpensive-optimizations -frename-registers -fomit-frame-pointer"
LDFLAGS=" -Wl,-start-group -ldl -lpthread -lm -lrt -Wl,-end-group -Wl,--rpath=$INSTALL_DIR/lib/ -Wl,--dynamic-linker=$INSTALL_DIR/lib/ld-linux.so.3 -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed"
CPP="/usr/bin/arm-linux-gnueabi-gcc -E -march=armv7-a -mfloat-abi=softfp -mfpu=neon"
CXXCPP="/usr/bin/arm-linux-gnueabi-g++ -E -march=armv7-a -mfloat-abi=softfp -mfpu=neon"
STRIP="/usr/bin/arm-linux-gnueabi-strip"
OBJDUMP="/usr/bin/arm-linux-gnueabi-objdump"
```

And them It compiles fine.

### **PS: I noticed that this .tar.xz file does not contain an `INSTALL` file with instructions on the installation process and script arguments. Could it be possible to consider adding this file in this version of the Python source code?**
