### ISSUE TITLE
Lack of `INSTALL` file on Python 3.8.10

### ISSUE THREAD

**Issue by locnnil** [python/cpython#100552]
# Documentation

I downloaded the source code for Python 3.8.10 from the FTP server using the following command:

`wget https://www.python.org/ftp/python/3.8.10/Python-3.8.10.tar.xz`

However, I noticed that there was no `INSTALL` file to assist me with the cross-compilation setup. I was able to figure out how to complete the process by reading the `configure` script.

**Comment by hauntsaninja** [comment]
Python 3.8 currently only receives security patches. The documentation for cross-compilation options is here: https://docs.python.org/3/using/configure.html#cross-compiling-options
