### ISSUE TITLE
Consider converting `exceptions.c` to argument clinic

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100550]
# Feature or enhancement

I propose discussing converting several parts of `exceptions.c` to arguments clinic, because it might simplify argument parsing.

# Pitch

There are two groups of function that can be converted. But, they have some tricks to them, so this is why I am not sure about whether or not it is worth it.

So, here's the first group:
- https://github.com/python/cpython/blob/ce39aaffeef9aa8af54a8554fe7a5609a6bba471/Objects/exceptions.c#L1190-L1196
- https://github.com/python/cpython/blob/ce39aaffeef9aa8af54a8554fe7a5609a6bba471/Objects/exceptions.c#L1159-L1165

I won't duplicate the pros of AC (I hope they are quite well known), only the negative parts:
- `exceptions.c` don't have AC at all right now - there would be quite a lot of churn
- Argument parsing logic here is quite trivial: only a single argument

The second group:

- https://github.com/python/cpython/blob/ce39aaffeef9aa8af54a8554fe7a5609a6bba471/Objects/exceptions.c#L1473-L1489
- https://github.com/python/cpython/blob/ce39aaffeef9aa8af54a8554fe7a5609a6bba471/Objects/exceptions.c#L2142-L2156
- https://github.com/python/cpython/blob/ce39aaffeef9aa8af54a8554fe7a5609a6bba471/Objects/exceptions.c#L2214-L2230

Moving these functions to AC will simplify the `empty_tuple` hack, by making these arguments keyword only. But, we still need to call `BaseException_init` with existing `args` tuple. Is it even possible?

# Previous discussion

I was not able to find it.

If we decide to do it - I would like to send a PR for this :)
CC @iritkatriel as `exceptions.c` code owner.

**Comment by sobolevn** [comment]
> But, we still need to call BaseException_init with existing args tuple. Is it even possible?

Yes, looks doable. We can define `self` convert like this:

```c
/*[python input]
class PyBaseExceptionObject_converter(CConverter):
    def modify(self):
        return """
if (BaseException_init((PyBaseExceptionObject *)self, args, NULL) == -1)
    return -1;
"""
[python start generated code]*/

/*[clinic input]
ImportError_init

  self: PyBaseExceptionObject
  name: ...
  ...

Doc.
[clinic start generated code]*/
```

**Comment by iritkatriel** [comment]
This isn’t solving an actual problem right? (the exceptions don’t change very often, they are not hard to maintain, any change requires a PEP anyway). 

I think there are probably better uses for our time in the 6k open issues and 1.4k PRs waiting for review.

**Comment by iritkatriel** [comment]
As explained above, there is no reason to do this.
