### ISSUE TITLE
importlib.resources.as_file is leaving temporary file pointers open

### ISSUE THREAD

**Issue by samety** [python/cpython#100585]
# Bug report

importlib.resources.as_file is leaving temporary file pointers open after writing their contents
see `_write_contents` function in importlib/resources/_common.py

Easy to repeat, just run the test case below with `-We`
`Lib.test.test_importlib.resources.test_resource.ResourceFromZipsTest01.test_as_file_directory` 

# Your environment

- CPython versions tested on: Python 3.12.0a3+
- Operating system and architecture: Ubuntu 22.04.1 LTS

I think it just needs to use `Path.write_bytes` and keep the file pointer closed.

### Linked PRs
* gh-100586

**Comment by warsaw** [comment]
Just from a quick glance, I think you're right in that the code is relying on implicit GC to close the file, which generally isn't good practice.  @jaraco to chime in.  What I don't remember is whether its `resources` or `metadata` that @jaraco likes to fix upstream and then sync to CPython.  (I haven't looked to see if the same code exists in `importlib_resources`.)

**Comment by jaraco** [comment]
This issue is fixed in https://github.com/python/importlib_resources/pull/274, which just hasn't been merged into CPython yet. All skeleton-based projects (including importlib_metadata) now enable ResourceWarnings so these kinds of issues will get caught early.

In that fix, a context manager was used instead of relying on `write_bytes`. I do prefer this one-line approach with `write_bytes`.

**Comment by samety** [comment]
Yes I just saw the context manager fix, that's also addressing the issue indeed. I find using `write_bytes` a bit cleaner. I don't mind applying the same one line approach to the importlib_resources project if that's the preferred option. Please let me know.

**Comment by jaraco** [comment]
I cherry-picked the change into importlib_resources as python/importlib_resources@d62307884400f33777dd4430288816d417b5a332. Thanks for reporting and the fix.
