### ISSUE TITLE
urllib.Robotparser is not working

### ISSUE THREAD

**Issue by vihaanmody1** [python/cpython#100593]
Hello,

When I use the robotparser class of urllib, this error is what I get.
Please help
Thank you
![image](https://user-images.githubusercontent.com/105392905/209872390-e0bfcca0-bd10-46d4-8b98-73655e376908.png)

**Comment by hauntsaninja** [comment]
Not a bug, see https://docs.python.org/3/library/urllib.robotparser.html#urllib.robotparser.RobotFileParser.request_rate 

This isn't the right place to ask for generic help, maybe try discuss.python.org or StackOverflow
