### ISSUE TITLE
Add `strptime`/`strftime` format code examples

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#100574]
Currently the docs for [`datetime.strptime`](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) and [`datetime.strftime`](https://docs.python.org/3/library/datetime.html#datetime.date.strftime) don't include an example but have a link to the [table with the format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes), where I end up having to reconstruct the right combination every time.  At the end of each class docs there are some examples, but there are no links pointing to them, so they aren't easily discoverable.  In addition, the `.(from)isoformat` methods can often be used instead of `strftime`/`strptime`.

I therefore suggest the following changes:
1. add an example before the [table with the format codes](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes), showing some of the most common codes;
2. add links to `(date|time|datetime).isoformat` in the docs for `(date|time|datetime).strptime`;
3. add links to `datetime.fromisoformat` in the docs for `datetime.strptime` (`date` and `time` have a `.fromisoformat` method, but no `.strptime` method);

### Linked PRs
* gh-100575
* gh-103368

**Comment by hugovk** [comment]
Merged to main/3.12 and backported to 3.11. ✅
