### ISSUE TITLE
replace pydoc with pydoc3

### ISSUE THREAD

**Issue by mwermelinger** [python/cpython#100583]
# Documentation

The [3.11 docs](https://docs.python.org/3.11/library/pydoc.html) and [3.10 docs](https://docs.python.org/3.10/library/pydoc.html) state that pydoc can be invoked as a script, giving as example`pydoc sys`. However, there's no such command after installing those versions on macOS: there's only `pydoc3`.

BTW, I also have Python 3.8 installed with Anaconda and it creates symlinks pydoc and pydoc3 both pointing to pydoc3.8.

 It thus seems either the documentation should be updated to replace pydoc with pydoc3 or the 3.10 and 3.11 installers should create a pydoc symlink.

### Linked PRs
* gh-100590
* gh-100606
* gh-100607

**Comment by Fidget-Spinner** [comment]
The recommended way that is platform agnostic is probably `<python you are using> -m pydoc`. So the docs should reflect that.

**Comment by ramvikrams** [comment]
should we change it to both ways by using the platform agnostic method and pydoc3
