### ISSUE TITLE
Unable to store True and a int in a set

### ISSUE THREAD

**Issue by AksharaBhanu** [python/cpython#100527]
# Bug report
create a set with int and boolean value
example : a ={1,True}

print the value of the set
print(a)

Expected output
{1,True}

Actual Output
{1}

# Your environment
OS: MS Windows 11 64bit 
Python Version: 3.10.1

Reported By
Bhanu Prakash
javagalbhanu@gmail.com

**Comment by stevendaprano** [comment]
This is correct, because `True == 1`.

You also can't have both True and 1 or the float 1.0 or Fraction(1) or the complex number 1+0j as keys in a dict, or elements in a set.

**Comment by stevendaprano** [comment]
Unfortunately this behaviour is fundamental to how bools are designed. True and False are ints (to be precise, bool is a subclass of int) and they equal 1 and 0.

**Comment by TeamSpen210** [comment]
If you want to track both the type and value, a workaround is to instead store `(type(x), x)` tuples - `{(bool, True), (int, 1), (float, 1.0)}`.
