### ISSUE TITLE
Confusing error message when attempting to pass a newtype as a match pattern

### ISSUE THREAD

**Issue by not-my-profile** [python/cpython#100530]
```python
from typing import NewType

T = NewType('T', str)

match 'test':
    case T(): ...
```

fails with:

```
Traceback (most recent call last):
  File "/tmp/foo.py", line 6, in <module>
    case T(): ...
         ^^^
TypeError: called match pattern must be a type
```

The error message is confusing because `T` is a type. The error message should probably say `class` instead of `type`, since [as per the specification](https://peps.python.org/pep-0634/#class-patterns) it's a class pattern.

### Linked PRs
* gh-103576

**Comment by AlexWaygood** [comment]
Cc. @brandtbucher for pattern-matching

**Comment by brandtbucher** [comment]
Hm... I'm not really sure there's anything to do here. I think the main issue is Python's general overloading of the word "type" to refer to both static types (for annotations) and types of objects. It's this second group that we're checking for here:

```py
>>> import typing
>>> T = typing.NewType("T", str)
>>> isinstance(T, type)
False
```

With that said, I'm open to changing the wording of the error message from "type" to "class" if others agree that the current wording is confusing.

**Comment by sobolevn** [comment]
I agree that `class` is a much better term here than `type`. Because, here's one more example where `type` is not quite correct:

```python
>>> A = typing.Annotated[str, 'meta']
>>> match 'abc':
...    case A(): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
TypeError: called match pattern must be a type
```

`typing.Annotated[str, 'meta']` is a type. But it is not a class.
Moreover, the `ast` node is also called `MatchClass` which is another argument for the wording change.
