### ISSUE TITLE
[unittest.mock] Autospecced decorator-transformed methods

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/cpython#100596]
If a decorator transforms a method, the autospecced mock will be wrong.

e.g. Something like:

```python 
def acquire(
    func: Callable[Concatenate[_Client, Connection, _P], Awaitable[_T]]
) -> Callable[Concatenate[_Client, _P], Awaitable[_T]]:

    @functools.wraps(func)
    async def wrapper(self: _Client, *args: _P.args, **kwargs: _P.kwargs) -> _T:
        conn = await self._pool.acquire()
        return await func(self, conn, *args, **kwargs)

    return wrapper
```

Will result in the mock requiring the first connection parameter when called, but the real method will already have that parameter provided by the decorator.

I assume autospec is currently only looking at the wraps information when inspecting the signature, but maybe it could make use of the type annotations to provide a more accurate mock.

**Comment by sobolevn** [comment]
Can you please provide a minimal code sample that we can? :)

**Comment by Dreamsorcerer** [comment]
Sure, here's that example simplified:
```
import functools
from typing import *
from unittest.mock import patch

_P = ParamSpec("_P")
_T = TypeVar("_T")


def acquire(
    func: Callable[Concatenate[int, _P], Awaitable[_T]]
) -> Callable[_P, Awaitable[_T]]:

    @functools.wraps(func)
    def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> _T:
        return func(0, *args, **kwargs)

    return wrapper


@acquire
def test(foo: int) -> None:
    return


test()  # Works

with patch("__main__.test", autospec=True):
    test()  # TypeError: missing a required argument: 'foo'
```

**Comment by sobolevn** [comment]
Isn't it working as documented? https://docs.python.org/3/library/unittest.mock.html#unittest.mock.patch

> A more powerful form of spec is autospec. If you set autospec=True then the mock will be created with a spec from the object being replaced. All attributes of the mock will also have the spec of the corresponding attribute of the object being replaced. Methods and functions being mocked will have their arguments checked and will raise a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError) if they are called with the wrong signature.

Looks like I need to use
```python
with patch("__main__.test", autospec=True):
    acquire(test)()
```

**Comment by Dreamsorcerer** [comment]
Well, that's a little surprising, given that `test` refers to the wrapped function outside of the patch, so not sure why it would then patch away the wrapped function using the inner function. The behaviour is certainly surprising...

But, my real issue was with classes, this is a more representative example:
```
import functools
from typing import *
from unittest.mock import patch

_P = ParamSpec("_P")
_T = TypeVar("_T")


def acquire(
    func: Callable[Concatenate[Any, int, _P], Awaitable[_T]]
) -> Callable[Concatenate[Any, _P], Awaitable[_T]]:

    @functools.wraps(func)
    def wrapper(self, *args: _P.args, **kwargs: _P.kwargs) -> _T:
        return func(self, 0, *args, **kwargs)

    return wrapper


class A:
    @acquire
    def test(self, foo: int) -> None:
        return


a = A()
a.test()  # Works

with patch("__main__.a", autospec=True):
    a.test()  # TypeError: missing a required argument: 'foo'
```

**Comment by Dreamsorcerer** [comment]
In fact, from your quote: '...from the object being replaced'
The object it replaced was the wrapped function, but that is not what was used for the spec, it used the inner function (which I think it finds through the functools.wraps information).

**Comment by Dreamsorcerer** [comment]
It's particularly cumbersome for my use case, as a decorator is used like this on ~20 methods of the class, and I now need to replace all the methods in the mock object, so the calls work as expected.

**Comment by sobolevn** [comment]
Interesting!

I've spent some time looking into it. So, I think that the main reason for this behavior (which I still belive is correct) is that `test`'s signature is not changed.

```python
import functools
from typing import *
import inspect
from unittest.mock import patch

_P = ParamSpec("_P")
_T = TypeVar("_T")


def acquire(func: Callable[Concatenate[int, _P], Awaitable[_T]]) -> Callable[_P, Awaitable[_T]]:
    @functools.wraps(func)
    def wrapper(*args: _P.args, **kwargs: _P.kwargs) -> _T:
        return func(0, *args, **kwargs)

    return wrapper


def test(foo: int) -> None:
    return

print('before', inspect.signature(test))
test = acquire(test)
print('after', inspect.signature(test))
test()  # Works


with patch("__main__.test", autospec=True):
    test()  # TypeError: missing a required argument: 'foo'
```

Running:

```
before (foo: int) -> None
after (foo: int) -> None
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/ex.py", line 29, in <module>
    test()  # TypeError: missing a required argument: 'foo'
    ^^^^^^
  File "<string>", line 2, in test
  File "/Users/sobolev/Desktop/cpython/Lib/unittest/mock.py", line 186, in checksig
    sig.bind(*args, **kwargs)
  File "/Users/sobolev/Desktop/cpython/Lib/inspect.py", line 3229, in bind
    return self._bind(args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython/Lib/inspect.py", line 3144, in _bind
    raise TypeError(msg) from None
TypeError: missing a required argument: 'foo'
```

See? The signatures are still equal - this is not the what should happen.

But, if we actually change it in `acquire`, it will work:

```python
    sig = inspect.signature(func)
    wrapper.__signature__ = sig.replace(
        parameters=tuple(sig.parameters.values())[1:],
    )
```

Running:

```
before (foo: int) -> None
after () -> None
```

So, I think it is up to developer to define these rules, `patch("...", autospec=True)` has nothing to do with that.

**Comment by Dreamsorcerer** [comment]
Still feels like something could be improved, so the developer doesn't get this confusing behaviour.
If not the autospec itself, maybe `functools.wraps()` could update the signature or something?

**Comment by sobolevn** [comment]
> functools.wraps() could update the signature or something?

This might be an interesting idea! Can you please start a new discussion on https://discuss.python.org/ ? I think that adding a new kw to `wraps` for signatures might be useful.

But, I am going to close *this* issue for now. Thanks for the report :)

**Comment by Dreamsorcerer** [comment]
Hmm, I would do, but when I click the sign up button, I get 'Incorrect username, email or password', despite green ticks on all those fields... (The result is from the POST request to discuss.python.org/u).

**Comment by sobolevn** [comment]
You can try "Login with GitHub", it works for me

**Comment by Dreamsorcerer** [comment]
Yeah, but it locks the email address to my public Github one, which is already receiving spam and phishing attempts (I create a different email for every website). I'll try again later in the week.

**Comment by Dreamsorcerer** [comment]
OK, posted at https://discuss.python.org/t/autospeccing-decorator-transformed-methods/22734

FYI, there are several people trying to get your attention on https://github.com/wemake-services/flake8-broken-line/pull/280

**Comment by Dreamsorcerer** [comment]
No replies...
Feel free to pick up the discussion at any point, but looks like I'll have to leave it for now.

**Comment by Dreamsorcerer** [comment]
Another issue is with attributes in `__init__()` when speccing from a class. Could make use of annotations there as well:

```
class Foo:
    bar: Callable[[], str]
    def __init__(self):
        self.bar = ...

f = create_autospec(Foo, instance=True)
f.bar  # AttributeError
```
