### ISSUE TITLE
Add support to replace multiple strings at once

### ISSUE THREAD

**Issue by simon-spier0** [python/cpython#100561]
If I want to replace multiple strings, I have to write it for example like this:
```python
s = "The quick brown fox jumps over the lazy dog"
for r in (("brown", "red"), ("lazy", "quick")):
    s = s.replace(*r)
```

But I would like to write it simple just like this:
```python
s = "The quick brown fox jumps over the lazy dog"
s = s.replace(("brown", "red"), ("lazy", "quick"))
```

It would work the same for example like str.startswith() where I can put tuple of strings.

Thanks.

**Comment by stevendaprano** [comment]
Did you discuss this elsewhere, as the New Feature template asks? If so, please link to that discussion.

This has been proposed before, at least once. You should [read the rejected feature request](https://github.com/python/cpython/issues/77828).

It has also been discussed on the Python Ideas mailing list. You should [read the thread](https://mail.python.org/archives/list/python-ideas@python.org/thread/2HEN22TBODKJ5DMSH6QEW4CWOVJHZ6UC/#RNPCW422Z534UW6ZLCAM4L3LOY5IQE2P).

Doing multiple replacements at once is very tricky. Replacements have to be specified in the correct order. Just doing the replacements in a loop, one after another, may give wrong or unexpected results if any of the replacement strings are a substring of the target strings.

After reading those previous discussions, if you still think that this proposal is viable, please start by discussing it in [the "ideas" category of Discuss](https://discuss.python.org/c/ideas/6) or [the python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/). If you get positive feedback you can reopen this ticket.

**Comment by rhettinger** [comment]
FWIW, you can already write it simply:

```
s.replace('brown', 'red').replace('lazy', 'quick')
'The quick red fox jumps over the quick dog'
```

The proposed tuple version would need rules to resolve ambiguities.  Perhaps a first match rule or a first-shortest-match rule. To avoid infinite loops, overlaps could not be allowed:  `[('x', 'y'), ('y', 'x')]`
