### ISSUE TITLE
syntax error (probably)

### ISSUE THREAD

**Issue by roozetti** [python/cpython#100658]
I don't know if what I am reporting is considered a bug or not
But I wonder why such a phrase can be written. I expect Python to stop writing such an expression.
Why does Python allow such a thing to be written, and if such a thing is not useful, why is not a syntax error given for such an expression. 

```python
(x = list(dict_.keys())[0] = 'k4')


dict_ = {'k1': 1, 'k1': 2, 'k2': 3, 'k3': 4}
list(dict_.values())[0] = 8
print(dict_)                                              # {'k1': 5, 'k2': 3, 'k3': 4}
list(dict_.keys())[0] = 'k4'
print(dict_)                                              # {'k1': 5, 'k2': 3, 'k3': 4}
x = list(dict_.keys())[0] = 'k4'
print(x)                                                  # 'k4'
```

**Comment by ericvsmith** [comment]
Is your confusion the second line? You could rewrite it as:

```pycon
>>> dict_ = {'k1': 1, 'k1': 2, 'k2': 3, 'k3': 4}
>>> temp = list(dict_.values())
>>> temp[0] = 8
>>> del temp
```
You're basically creating a temporary list, setting its 0th element, then throwing away the list This isn't a bug, it's the natural consequence of how Python works.

When you're not sure of how Python works, a better place to ask questions is https://discuss.python.org/c/users/7
