### ISSUE TITLE
update_wrapper do not preserve original method signature

### ISSUE THREAD

**Issue by efibutov** [python/cpython#100694]
# Bug report

The function `update_wrapper` does not preserve the signature of decorated method of **a class** (But it works fine if an unbounded function is decorated)

```python
from functools import update_wrapper


def dispatcher(method):
    def wrapper(self, *args, **kwargs):
        kwargs['alert_type'] = method.__name__.capitalize()
        return self.post_event(*args, **kwargs)

    update_wrapper(wrapped=method, wrapper=wrapper)
    return wrapper


class Logger(object):
    def post_event(self, msg, alert_type, title):
        pass

    @dispatcher
    def info(self, msg, title=''):
        pass


Logger().info('just call to info')
```

Got an exception:

```
TypeError: Logger.post_event() missing 1 required positional argument: 'title'
```

# Your environment

- CPython versions tested on:
  - 3.10.6
- Operating system and architecture:
  - Linux Ubuntu 22.04.1 LTS x64

**Comment by FrozenBob** [comment]
Not a bug.

The `args` and `kwargs` received by `wrapper` are the actual positional and keyword arguments you passed. The `title=''` default value in `info` is not a positional or keyword argument you passed. That default value would be handled when you call the wrapped method, but your "wrapper" doesn't actually call the function it claims to wrap.

`functools.update_wrapper` is not intended to insert the wrapped function's default argument values into the arguments your wrapper receives. It cannot change your wrapper's actual signature to `def info(self, msg, title='')`, with a default value inserted, either; if it did, your wrapper would break when it tried to access `args` and `kwargs` that wouldn't exist in the new signature. All `functools.update_wrapper` does is copy some attributes over and set `__wrapped__`, so introspection tools can see the wrapped function.

**Comment by sobolevn** [comment]
+1 to @FrozenBob 

This does not look like a bug. 
Moreover, it has nothing to do with `update_wrapper`. It works the same way with and without this call.
