### ISSUE TITLE
[tutorial/classes.html] odds and ends dataclasses sample code typo dataclasses

### ISSUE THREAD

**Issue by peterjpxie** [python/cpython#100633]
# Documentation
Open https://docs.python.org/3.12/tutorial/classes.html#odds-and-ends

There is a typo in the sample code.  `import dataclasses` should be `import dataclass`.
```python 
from dataclasses import dataclasses

@dataclass
class Employee:
    name: str
    dept: str
    salary: int
```

It was introduced in this [PR](https://github.com/python/cpython/pull/100498/files#diff-cce67fcd47f7f2eb0e7c82b019417844fa21306a87e3fef7719e6fd1bd1f3774R744).

### Linked PRs
* gh-100638
* gh-100639
* gh-100640

**Comment by sobolevn** [comment]
@peterjpxie this would be a good first PR :)
Do you have time to fix it?

**Comment by peterjpxie** [comment]
@ericvsmith Thanks for fixing it.

**Comment by ericvsmith** [comment]
I didn't fix it! I just assigned it to myself. If you want to produce a pull request, I'll commit it.

**Comment by AlexWaygood** [comment]
This is now fixed on `main`, but the CLA bot seems unhappy with the backports for some reason.

**Comment by AlexWaygood** [comment]
And now successfully backported to 3.11 and 3.10. Thanks @OTheDev!
