### ISSUE TITLE
Command + v is pasting twice in IDLE if Caps lock key is on in Mac OS 

### ISSUE THREAD

**Issue by mesoumyapaul** [python/cpython#100645]

**Comment by aivarannamaa** [comment]
According to my tests, this is fixed in Tk 8.6.13 (https://github.com/thonny/thonny/issues/2753)

**Comment by ronaldoussoren** [comment]
@aivarannamaa: thanks for the updated.

I've checked that the issue is no longer present in the latest 3.12 installer which includes Tk 8.6.13 (and can be reproduced with an old 3.9 install with an older version of Tk).
