### ISSUE TITLE
Division of 8.32 by 10 yields incorrect value "0.8320000000000001"

### ISSUE THREAD

**Issue by amritabithi** [python/cpython#100679]
As the title says,

Division of 8.32 by 10 yields incorrect value "0.8320000000000001"

To reproduce:
```
x = 8.32 / 10
print(str(x))
```

**Comment by hauntsaninja** [comment]
This is how floats work, see https://stackoverflow.com/questions/588004/is-floating-point-math-broken Consider using `decimal.Decimal` instead.

**Comment by hauntsaninja** [comment]
See also https://docs.python.org/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate
