### ISSUE TITLE
"Write your first Python fix" page not work

### ISSUE THREAD

**Issue by malker97** [python/cpython#100655]
# Documentation
document is in an unreadable state
url: https://cpython-core-tutorial.readthedocs.io/en/latest/python_fix.html
doc: https://github.com/vstinner/cpython_core_tutorial/blob/main/python_fix.rst
(A clear and concise description of the issue.)

**Comment by hugovk** [comment]
Thanks for the report, but this isn't official Python documentation. Please report it instead to https://github.com/vstinner/cpython_core_tutorial

cc @vstinner

**Comment by vstinner** [comment]
I'm the author of this old guide. I archived the related GitHub project and removed the guide online. You can read the archive of the requested page at: https://github.com/vstinner/cpython_core_tutorial/blob/main/python_fix.rst

As you can see, the guide was very complete :-)
