### ISSUE TITLE
importlib.metadata fails to read version in the 'hatchling' package

### ISSUE THREAD

**Issue by yurivict** [python/cpython#100602]
# Bug report

This code fails to read version in the 'hatchling' package:
```python 
name="hatchling"
import importlib.metadata as importlib_metadata
dist = importlib_metadata.distribution(name)
print(f"dist.version={dist.version}")
```
it prints:
```python 
dist.version=None
```

# Your environment

- CPython versions tested on: 3.9.16
- py39-hatchling-1.11.0
- Operating system and architecture: FreeBSD 13.1 STABLE amd64

**Comment by ericvsmith** [comment]
I don't see this on 3.9.10 on Cygwin with hatchling 1.11.0 or 1.11.1, or with 3.10.6 on Ubuntu with hatchling 1.11.1.

I don't 3.9.16 handy, but I'll see if I can install it.

How did you install hatchling? Is this in a virtual environment? Is this a --user install?

**Comment by yurivict** [comment]
hatchling was installed from the FreeBSD package/port.
It isn't in a virtual environment and isn't a user install.

**Comment by ned-deily** [comment]
Try `pip install`-ing a version of `hatchling` directly from `pypi` using a venv as an experiment. It may be that the FreeBSD package of `hatchling` is stripping some files. If so, you should take it up with the FreeBSD project.

**Comment by ericvsmith** [comment]
I agree with @ned-deily : this is probably an issue with how the FreeBSD port installs hatchling.

**Comment by yurivict** [comment]
But what is wrong with how it is installed?
By default it uses setup.py - and the result has this problem.
I also tried to build it with build (into a wheel), and then install the wheel with 'install' - and it still has the same problem.

**Comment by ned-deily** [comment]
It could also be an issue with FreeBSD modifications to Python.  You could try bulding a vanilla Python 3.9 and installing with it. I don't have a FreeBSD installation available at the moment but your test worked ok on a Python 3.9.x on macOS.

**Comment by eli-schwartz** [comment]
Surely the simplest solution to debugging the problem is to stop theorizing about what might be wrong with how it is installed or what FreeBSD does to modify python, and simply... upload the relevant files which FreeBSD has (i.e. the contents of the `py39-hatchling-1.11.0` package). :) Then anyone can take a look at them and see what importlib.metadata doesn't like about them... :)

**Comment by yurivict** [comment]
[here](https://people.freebsd.org/~yuri/hatchling-files.tgz)

**Comment by eli-schwartz** [comment]
The only files this contains are the python files inside `usr/local/lib/python3.9/site-packages/hatchling/`. There's no metadata here.

```
$ cd /tmp/hatchling-files/usr/local/lib/python3.9/site-packages; PYTHONPATH=$PWD python3.9
Python 3.9.16 (main, Jan  1 2023, 03:08:33) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata
>>> dist = importlib.metadata.distribution('hatchling')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/importlib/metadata.py", line 542, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 196, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: hatchling
```

I don't know how you got a distribution with no version, but you "should" actually have significantly bigger errors.

**Comment by yurivict** [comment]
Sorry, that was an incomplete archive.
The complete package file is [here](https://people.freebsd.org/~yuri/py39-hatchling-1.11.0~8f3b9491eb.pkg).

**Comment by eli-schwartz** [comment]
This one does work for me:

```
$ cd /tmp/py39-hatchling-1.11.0~8f3b9491eb/usr/local/lib/python3.9/site-packages; PYTHONPATH=$PWD python3.9
Python 3.9.16 (main, Jan  1 2023, 03:08:33) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib.metadata
>>> dist = importlib.metadata.distribution('hatchling')
>>> dist.version
'1.11.0'
```

**Comment by eli-schwartz** [comment]
@yurivict https://builds.sr.ht/~eschwartz/job/914998

On a FreeBSD 13.1-RELEASE-p3 GENERIC image, I was able to successfully install python39, load your tarball and get dist.version to print 1.11.0, and then repeat the experience with `pkg install py39-hatchling`.

I'm not sure how you got the results you got, but this isn't an importlib.metadata bug and it isn't a FreeBSD bug either, and the example which fails for you, works for my reproducible FreeBSD test job after following the exact instructions you gave.

I think the problem is likely in your own local installation which has something other than a FreeBSD port installed.

**Comment by eli-schwartz** [comment]
This is probably a duplicate of #91216 and you have an additional, but broken, metadata directory for hatchling, which does NOT come from the FreeBSD port.

**Comment by yurivict** [comment]
You are right, some stray file caused this.

File:
> /usr/local/lib/python3.9/site-packages/hatchling-1.6.0-py3.9.egg-info
