### ISSUE TITLE
`itertools.product()` gives one result for empty arguments list.

### ISSUE THREAD

**Issue by yosefm** [python/cpython#100603]
# Bug report

Visible behaviour:

```pycon
>>> import itertools as it
>>> list(it.product())
[()]
```

Expected behaviour:

```pycon
>>> import itertools as it
>>> list(it.product())
[]
```

This may seem pedantic, but it actually shows up when doing `it.product(*a)` and `a` is empty, which actually happens in the wild. One expects no iteration of the iterator to happen if there is nothing to iterate on. Instead, one iteration always happens.

The behaviour is sort of documented in https://docs.python.org/3/library/itertools.html, giving an empty list instead of empty tuple as the result in this case, but It still seems like a wrong result.

# Your environment

- CPython versions tested on: 3.10.0, 3.9.12
- Operating system and architecture: Win10

# Diagnosis

`Modules/itertoolsmodule.c` line 2521, in `product_next()`
A return tuple is always created even if `npools == 0`. I think `NULL` should be returned in this case.

Fixing this should be easy, but I'm not sure about deprecation policy etc., as changing this might break existing scripts. Should this be fixed, documented, or what?

**Comment by stevendaprano** [comment]
That's interesting. The [empty cartesian product should be the null set](https://math.stackexchange.com/questions/2241536/what-is-cartesian-product-for-two-empty-sets), not a set containing the null set.

```
>>> list(product((), (), ()))
[]
>>> list(product((), ()))
[]
>>> list(product(()))
[]
>>> list(product())
[()]
```

**Comment by sobolevn** [comment]
We have a test case that ensure that the result is `[()]`: https://github.com/python/cpython/blob/f10f503b24a35a43910a632ee50c7568bedd6664/Lib/test/test_itertools.py#L1123

It exists for 15 years. Since 

Probably from:

```
  r61224 | raymond.hettinger | 2008-03-04 05:17:08 +0100 (Tue, 04 Mar 2008) | 1 line

  Beef-up docs and tests for itertools.  Fix-up end-case for product().

**Comment by pochmann** [comment]
Not a bug, it's correct. With n input iterables, you get all n-tuples with corresponding elements from the iterables. With n=0, that's all 0-tuples, i.e., the empty tuple.

@stevendaprano Your examples are like `math.prod([0, 0, 0])`, which is `0`, but the empty product `math.prod([])` is `1`.

See [Empty product](https://en.m.wikipedia.org/wiki/Empty_product), especially the "Nullary Cartesian product" section.

**Comment by yosefm** [comment]
Huh. Counterintuitive, but true. Maybe merits a line in the documentation, but not a bug.

**Comment by pochmann** [comment]
> Counterintuitive

I guess that depends on how used you are to emptiness :-)

> Maybe merits a line in the documentation

There's actually annoying precedent for that: `all(iterable)` is [documented](https://docs.python.org/3/library/functions.html#all) with:

> Return `True` if all elements of the *iterable* are true (or if the iterable is empty).

Note that the part in parenthesis is unnecessary, it's apparently just there for people who don't know [vacuous truth](https://en.m.wikipedia.org/wiki/Vacuous_truth).

(I'd prefer *that* to be *removed* instead of something similar added elsewhere, but maybe that's just me...)

**Comment by yosefm** [comment]
> > Maybe merits a line in the documentation
> 
> There's actually annoying precedent for that: `all(iterable)` is [documented](https://docs.python.org/3/library/functions.html#all) with:
> 
> > Return `True` if all elements of the _iterable_ are true (or if the iterable is empty).
> 
> Note that the part in parenthesis is unnecessary, it's apparently just there for people who don't know [vacuous truth](https://en.m.wikipedia.org/wiki/Vacuous_truth).
> 
> (I'd prefer _that_ to be _removed_ instead of something similar added elsewhere, but maybe that's just me...)

Depends if Python is for programmers of for mathematicians. Good documentation sometimes needs to state the obvious for those who wrote the code. You wouldn't even need documentation if it was only for those who already know. But I'm not going to argue this further.

**Comment by pochmann** [comment]
Yes, I acknowledge it might be useful for non-mathematicians (I studied comp-sci and some math). Although nullary Cartesian product is maybe not used by the average user, unlike `all`/`any` on empty iterables (so maybe that's not really relevant precedent).
