### ISSUE TITLE
typing.get_type_hints documentation claims it no longer includes base class type hints.

### ISSUE THREAD

**Issue by FrozenBob** [python/cpython#100673]
# Documentation

The `typing.get_type_hints` documentation currently says

> Changed in version 3.10: Calling get_type_hints() on a class no longer returns the annotations of its base classes.

This is incorrect. No such change was made in 3.10, and no such change should be made. The documentation was changed erroneously when someone mixed up the `typing.get_type_hints` behavior with an [unrelated `__annotations__` change](https://github.com/python/cpython/issues/99535).

This note should be removed from the `typing.get_type_hints` documentation.

### Linked PRs
* gh-100701
* gh-100823
* gh-100826

**Comment by hauntsaninja** [comment]
Thanks for catching, that sounds right to me. Want to open a PR to remove it?

E.g. easy to confirm that the following extension of the test added in that PR has the same `typing.get_type_hints` output on Python 3.9, 3.10.9, 3.11.1, main.
```
class A:
    attr: int
class B(A):
    pass
class C(A):
    attr: str
class D:
    attr2: int
class E(A, D):
    pass
class F(C, A):
    pass

print(A.__annotations__)
print(B.__annotations__)
print(C.__annotations__)
print(D.__annotations__)
print(E.__annotations__)
print(F.__annotations__)
print("=" * 40)

import typing
print(typing.get_type_hints(A))
print(typing.get_type_hints(B))
print(typing.get_type_hints(C))
print(typing.get_type_hints(D))
print(typing.get_type_hints(E))
print(typing.get_type_hints(F))
```

**Comment by FrozenBob** [comment]
Seems straightforward, and I've got a [commit](https://github.com/FrozenBob/cpython/commit/6091ccbf88d5182d587a0e24aaf171dcec2f19ce) I could create a pull request for, but I don't have a dev environment set up to be able to build the docs or run stuff like `patchcheck`. If I screw something up somehow, I might not notice.

**Comment by hauntsaninja** [comment]
That commit looks good to me. Open the PR and I'll take care of the rest :-)

**Comment by hauntsaninja** [comment]
Thank you!
