### ISSUE TITLE
`random.shuffle()` may raise `KeyError` for dicts including `OrderedDict`s

### ISSUE THREAD

**Issue by xxxxme** [python/cpython#100642]
```python
import random
from collections import OrderedDict
richard = OrderedDict([('parrot', 'dead'), ('rabbit', 'man-eating'), (100, 0)])
random.shuffle(richard)
```

raises a `KeyError`.

Tested on Arch Linux x64 with python 3.10.9 from official Arch repo.

**Comment by AlexWaygood** [comment]
There don't seem to be any `OrderedDict`s where `random.shuffle(<ordered_dict>)` doesn't raise a `KeyError`, as far as I can tell, though I haven't tried too hard.

**Comment by AlexWaygood** [comment]
`random.shuffle()` is [documented](https://docs.python.org/3/library/random.html) as only accepting sequences, and `OrderedDict` is not a sequence, nor is it [documented](https://docs.python.org/3/library/collections.html#collections.OrderedDict) as being a sequence. So I don't think this can be classified as a bug.

Moreover, there's been no recent behaviour change here -- I can reproduce this all the way back to Python 3.6.

**Comment by pochmann** [comment]
> There don't seem to be any `OrderedDict`s where `random.shuffle(<ordered_dict>)` doesn't raise a `KeyError`

Try with keys 0, 1, ...:
```
OrderedDict([(0, 'dead'), (1, 'man-eating'), (2, 0)])
```
[Works](https://tio.run/##TY0xDgIhEEV7TjHdQoJm1cbGzt4DGAsCg5DADJnFwtOj0Y2xfO8n77dnT0yHY5Mxcm0sHcRR4KqicAXPpaDvmWmBdb5IQMFwzr4ryT45CXD6t/qqZwtTQBcmY0Hv3lAdbdD1TPeP2luYzc2o79V2SY8YC@o1Z1STTP2HY7wA) for me in 3.8.

**Comment by AlexWaygood** [comment]
> > There don't seem to be any `OrderedDict`s where `random.shuffle(<ordered_dict>)` doesn't raise a `KeyError`
> 
> Try with keys 0, 1, ...:
> 
> ```
> OrderedDict([(0, 'dead'), (1, 'man-eating'), (2, 0)])
> ```
> 
> [Works](https://tio.run/##TY0xDgIhEEV7TjHdQoJm1cbGzt4DGAsCg5DADJnFwtOj0Y2xfO8n77dnT0yHY5Mxcm0sHcRR4KqicAXPpaDvmWmBdb5IQMFwzr4ryT45CXD6t/qqZwtTQBcmY0Hv3lAdbdD1TPeP2luYzc2o79V2SY8YC@o1Z1STTP2HY7wA) for me in 3.8.

Sure, it "works" in that it doesn't raise an Exception. But you end up with the values being associated with different keys. If `random.shuffle()` "worked" on an `OrderedDict` (or a regular `dict`, which is also ordered these days), I would expect the key/value pairs to remain the same, and merely be reordered.

**Comment by pochmann** [comment]
@AlexWaygood Yes, "works" is what I meant :-). I agree it shouldn't even be attempted since it's not a sequence. Actually `help(random.shuffle)` even tells me "Shuffle **list** x in place", btw (at least up to 3.10).

**Comment by stevendaprano** [comment]
I'm leaving this issue closed, but changing the title to better signal to future searchers that it's not just OrderedDict, but regular dicts as well, that can misbehave with `shuffle`.

*Unless* the keys are the numbers 0 through (len(d) - 1) inclusive, shuffling a mapping *may* raise KeyError. `shuffle` tries to swap two items with random indices. If both indices happen to be keys, the operation will succeed.

This issue came up before in #74496 where @rhettinger rejected either a code change or a documentation change for this. I concur with his final comment: it's just a fact of life with duck-typing. Dicts are sufficiently sequence-like for `shuffle` to sometimes work by accident, if the keys happen to match the indices used to shuffle.

**Comment by AlexWaygood** [comment]
Yes, Raymond's final remarks in #74496 are a very elegant way of putting it:

> These are just duck-typing facts of life.

**Comment by pochmann** [comment]
> `shuffle` tries to swap two items with random indices

No, only one of them is random. If both were random, you'd get bias. Indices 1 to n-1 are  *always* used, and index 0 is *probably* used.

https://github.com/python/cpython/blob/f80ba44f7d01b153b12eb7573568f9b1f33654ee/Lib/random.py#L373-L380
