### ISSUE TITLE
Docs: `IOError` not documented as a subclass of `OSError`

### ISSUE THREAD

**Issue by woodruffw** [python/cpython#100696]
# Documentation

Since at least 3.3, the `IOError` exception has been a subclass of `OSError`.

```python
>>> IOError.__mro__
(<class 'OSError'>, <class 'Exception'>, <class 'BaseException'>, <class 'object'>)
```

`pyupgrade` and `ruff` use this fact to perform automatic rewrites, simplifying exception handling statements where possible (https://github.com/asottile/pyupgrade/issues/141, https://github.com/charliermarsh/ruff/pull/1434).

However, in the current exception documentation, `IOError` is just a stub and isn't placed under the "OS exceptions" subsection: <https://docs.python.org/3/library/exceptions.html#IOError>

It also doesn't appear in the exception hierarchy rendered at the bottom of the page: <https://docs.python.org/3/library/exceptions.html#exception-hierarchy>

So, my two suggested fixes:

1. Relocate `IOError` under "OS exceptions"
2. Update the exception hierarchy render to include `IOError` under `OSError`

I'm happy to make both of these changes; just filing an issue for visibility!

xref https://github.com/charliermarsh/ruff/issues/1568

**Comment by AlexWaygood** [comment]
It's not actually a subclass of `OSError`; it's an _alias_ for `OSError`:

```pycon
>>> IOError is OSError
True
```

**Comment by AlexWaygood** [comment]
Indeed, the documentation that you link to states that `IOError` is an alias of `OSError`. You need to read the paragraph immediately above the place that you linked to:

> The following exceptions are kept for compatibility with previous versions; starting from Python 3.3, they are aliases of [OSError](https://docs.python.org/3/library/exceptions.html#OSError).
> 
> _exception_ **EnvironmentError**
> _exception_ **IOError**
> _exception_ **WindowsError**
>     Only available on Windows.

**Comment by eryksun** [comment]
See PEP3151 [coalesce exception types](https://peps.python.org/pep-3151/#step-1-coalesce-exception-types).

**Comment by woodruffw** [comment]
Not sure how I missed that. Thanks both!

**Comment by AlexWaygood** [comment]
No worries!
