### ISSUE TITLE
Improve description for `venv --upgrade-deps`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#100676]
The current description comes out as `Upgrade core dependencies: pip setuptools to the latest version in PyPI`. The lack of comma between "pip" and "setuptools" reads slightly odd to me. I think it's because `" ".join()` is used instead of `", ".join()`.

https://github.com/python/cpython/blob/edfbf56f4ca6588dfd20b53f534a4465e43c82bd/Lib/venv/__init__.py#L526

### Linked PRs
* gh-100678

**Comment by rblcoder** [comment]
Can I fix this issue?

**Comment by rblcoder** [comment]
Can the pull request me merged?
