### ISSUE TITLE
Code objects, function objects and generator object contain quite a lot of redundant information

### ISSUE THREAD

**Issue by markshannon** [python/cpython#100719]
There is a quite a lot of redundancy in code, function and generator objects.

### Intra-object redundancy

1. Code objects have four fields ,`co_nlocalsplus`, `co_nplaincellvars`, `co_nlocals`, `co_nfreevars`. Any of these fields can be computed from the other three.
2. Code objects have a qualified name and a name. The name is always the suffix of the qualified name. Changing this to qualifying prefix and name would save space and allow sharing.
3. The defaults and keyword defaults for a function are separate and the keyword defaults are a dict. They could be combined into a single array.
4. Generator objects have a `gi_code` field, which is redundant, as the frame contains a reference to the code object.

### Inter-object redundancy

1. Functions and generators have qualified name and name fields, which are almost always the same as the underlying code object. These should be lazily initialized

### Linked PRs
* gh-100721
* gh-100749

**Comment by stevendaprano** [comment]
I have no opinion on whether these changes are good or bad, but they are surely breaking changes. Code objects aren't well documented, but they're not private implementation details. How do you plan to manage these changes?

**Comment by markshannon** [comment]
The `PyCodeObject` struct is in the `Include/cpython` folder. So while it is not entirely private, we are allowed to change it.

**Comment by terryjreedy** [comment]
@stevendaprano The python-level doc for 'internal types', including code objects, https://docs.python.org/3/reference/datamodel.html#codeobject says
>Their definitions may change with future versions of the interpreter, but they are mentioned here for completeness.

'co_nplaincellvars' is not even mentioned in the 3.11 docs.

generator objects are not listed here and their internal gi_xxx methods, as opposed to `__next__`, send, and throw, are not indexed.
