### ISSUE TITLE
Shell restart due to moderately-sized matrices in GPU programming

### ISSUE THREAD

**Issue by Friedrich2** [python/cpython#100752]
# Crash report

During GPU programming with [reikna](http://reikna.publicfields.net/en/latest/) (`pip install reikna`), I made the Shell restart, which I interpret as interpreter crash. (Is this right?) I would expect to instead get a helpful error message. You can play with different matrix sizes in the second-last line of the MWE. Note that the crash may be graphic-card-dependent and only occurs for matrices being big enough.
I cannot guarantee that the error occurs always, but five test runs always yielded a restart.

Note that for really big numbers, e.g. the size [10000, 20000], an OpenCL error occurs. This is due to a graphic card out-of-memory error (completely o. k.) and may or may not hide the error.
Another dependence factor could be the matrix subdivision during the Fourier Transform (which itself depends upon the size), but nevertheless the IDLE should not crash.

Using binary search, I found that the line before `return 2` is the line which makes the Shell restart.

I do not have debugging symbols installed and can't change my installation, since the issue arose on my work computer.

# Error messages
![grafik(1)](https://user-images.githubusercontent.com/34623166/210588403-5d6dddcf-90ec-481c-a1e8-dfeacaad9b29.jpg)
 As the graphic shows, the IDLE is restarted during the execution of the program.
# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: 
![grafik](https://user-images.githubusercontent.com/34623166/210588562-77f36880-dbca-4c63-b839-49c110a9aacf.png)
![grafik](https://user-images.githubusercontent.com/34623166/210588719-55c8fc5b-27bf-4015-baae-f20bd467bc85.png)
Despite the image, I think that I have only one processor with multiple kernels. (laptop)

# Working example
EDIT: A heavily simplified version is given [below](https://github.com/python/cpython/issues/100752#issuecomment-1373722460).
```Python
import numpy
from reikna.fft import FFT, FFTShift
from reikna.core import *
import reikna.cluda
import time
import pprint
#Quelle: https://programtalk.com/vs4/python/4334/reikna/examples/demo_fftshift_transformation.py/

def personal_fftshift(arr_t, axes=None):
    """
    Returns a frequency shift transformation (1 output, 1 input) that
    works as ``output = numpy.fft.fftshift(input, axes=axes)``.

    .. warning::

        Involves repositioning of the elements, so cannot be used on inplace kernels.
    """

    if axes is None:
        axes = tuple(range(len(arr_t.shape)))
    else:
        axes = tuple(sorted(axes))

    # The code taken from the FFTShift template for odd problem sizes
    # (at the moment of the writing).
    # Note the use of ``idxs`` template parameter to get access to element indices.
    return Transformation(
        [Parameter('output', Annotation(arr_t, 'o')),
        Parameter('input', Annotation(arr_t, 'i'))],
        """
        <%
            dimensions = len(output.shape)
            new_idx_names = ['new_idx' + str(i) for i in range(dimensions)]
        %>
        %for dim in range(dimensions):
        VSIZE_T ${new_idx_names[dim]} =
            ${idxs[dim]}
            %if dim in axes:
                %if output.shape[dim] % 2 == 0:
                + (${idxs[dim]} < ${output.shape[dim] // 2} ?
                    ${output.shape[dim] // 2} :
                    ${-output.shape[dim] // 2})
                %else:
                + (${idxs[dim]} <= ${output.shape[dim] // 2} ?
                    ${output.shape[dim] // 2} :
                    ${-(output.shape[dim] // 2 + 1)})
                %endif
            %endif
            ;
        %endfor

        ${output.ctype} val = ${input.load_same};
        ${output.store_idx}(${', '.join(new_idx_names)}, val);
        """,
        connectors=['input'],
        render_kwds=dict(axes=axes))

def run_test(thr, shape, dtype, axes=None):

    data = numpy.random.normal(size=shape).astype(dtype)

    fft = FFT(data, axes=axes)
    fftc = fft.compile(thr)

    shift = FFTShift(data, axes=axes)
    shiftc = shift.compile(thr)

    # FFT + shift as two separate computations

    data_dev = thr.to_device(data)

    t_start = time.time()
    fftc(data_dev, data_dev)
    return 2

if __name__ == "__main__":
    import reikna.cluda as cluda
    api = cluda.ocl_api()
    thr = api.Thread.create()
    pprint.pprint(run_test(thr, [8000, 10000], "complex"))
    print("hallo")
```

**Comment by sobolevn** [comment]
Sorry, but this looks way too complex and unclear. 

Is it really a problem with CPython itself? Or is it a problem with some of the dependencies you are using?
Can I please ask you to replicate the same thing using just pure CPython?

Did you report this to `reikna`? What's their opinion on that matter?

**Comment by Friedrich2** [comment]
I've heavily reduced the number of dependencies by now (see below), please excuse my unnecessarily long first program. I am not good enough to replicate it in pure Python, but now we only need numpy and a class. To see the behaviour, please wait around 25 seconds.

The owner of reikna does explicitly not contribute currently, see [here](https://github.com/fjarri/reikna/issues/63#issuecomment-1364596746).
Since this type of error did not occur to me in many years of Python, particularly that no stacktrace was printed, I suppose that it may be at least interesting for CPython itself. In addition, the development here is active.

```Python
# What: Intended to show an unexpected shell restart.
# (https://github.com/python/cpython/issues/100752)
import numpy
from reikna.fft import FFT


def run_test(thr, shape, dtype, axes=None):
    
    data = numpy.random.normal(size=shape).astype(dtype)

    fft = FFT(data, axes=axes)
    fftc = fft.compile(thr)

    data_dev = thr.to_device(data)

    fftc(data_dev, data_dev)
    return 2

if __name__ == "__main__":
    import reikna.cluda as cluda
    api = cluda.ocl_api()
    thr = api.Thread.create()
    print(run_test(thr, [8000, 10000], "complex"))
    print("after the test run")
```

**Comment by hauntsaninja** [comment]
I can't run the example on my machine, I get `pyopencl._cl.LogicError: clGetPlatformIDs failed: PLATFORM_NOT_FOUND_KHR`.

There are many ways in which C extensions can crash the interpreter. I think this is unlikely to be an issue in the CPython interpreter and since I can't run the example, I will close this issue.

If you need to debug further, maybe `export PYTHONFAULTHANDLER=1` and use `gdb`. If you need further help, maybe try asking on discuss.python.org? There's also an active #c-extensions channel on the Python Discord.

**Comment by Friedrich2** [comment]
Thanks for the great suggestions! For the record: The error may come from a not-installed OpenCL driver. (c.f. [here](https://stackoverflow.com/a/52946862))
