### ISSUE TITLE
logging. In class TimedRotatingFileHandler do not work backup rotation

### ISSUE THREAD

**Issue by AndreyDukhin** [python/cpython#100790]
re expect file structure
{file}.{date}.log
fact file structure
{file}.log.{date}
fix
to delete:
dfn = self.rotation_filename(self.baseFilename + "." +
                                     time.strftime(self.suffix, timeTuple))
to insert:
dfn = self.rotation_filename(self.baseFilename[:-4] + "." +
                                     time.strftime(self.suffix , timeTuple)+ self.baseFilename[-4:])

**Comment by sobolevn** [comment]
Hi! Can you please add a bit more details about:
1. The file structure
2. The code we need to run
3. Things you expect to happen
4. Things that actually happen
5. Your OS and other important details (like filesystem, python version, etc)

Thank you!

**Comment by AndreyDukhin** [comment]
run this code and you see 3 backup "good_example" and 5 "bad_example"

import os
import logging
from logging.handlers import TimedRotatingFileHandler
import time


class TimedRotatingFileHandler2(TimedRotatingFileHandler):
    def doRollover(self):
        """
        do a rollover; in this case, a date/time stamp is appended to the filename
        when the rollover happens.  However, you want the file to be named for the
        start of the interval, not the current time.  If there is a backup count,
        then we have to get a list of matching filenames, sort them and remove
        the one with the oldest suffix.
        """
        if self.stream:
            self.stream.close()
            self.stream = None
        # get the time that this sequence started at and make it a TimeTuple
        currentTime = int(time.time())
        dstNow = time.localtime(currentTime)[-1]
        t = self.rolloverAt - self.interval
        if self.utc:
            timeTuple = time.gmtime(t)
        else:
            timeTuple = time.localtime(t)
            dstThen = timeTuple[-1]
            if dstNow != dstThen:
                if dstNow:
                    addend = 3600
                else:
                    addend = -3600
                timeTuple = time.localtime(t + addend)
        dfn = self.rotation_filename(self.baseFilename[:-4] + "." +
                                     time.strftime(self.suffix, timeTuple) + self.baseFilename[-4:])
        if os.path.exists(dfn):
            os.remove(dfn)
        self.rotate(self.baseFilename, dfn)
        if self.backupCount > 0:
            for s in self.getFilesToDelete():
                os.remove(s)
        if not self.delay:
            self.stream = self._open()
        newRolloverAt = self.computeRollover(currentTime)
        while newRolloverAt <= currentTime:
            newRolloverAt = newRolloverAt + self.interval
        #If DST changes and midnight or weekly rollover, adjust for this.
        if (self.when == 'MIDNIGHT' or self.when.startswith('W')) and not self.utc:
            dstAtRollover = time.localtime(newRolloverAt)[-1]
            if dstNow != dstAtRollover:
                if not dstNow:  # DST kicks in before next rollover, so we need to deduct an hour
                    addend = -3600
                else:           # DST bows out before next rollover, so we need to add an hour
                    addend = 3600
                newRolloverAt += addend
        self.rolloverAt = newRolloverAt


logger = logging.getLogger(name='test')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
file_handler = TimedRotatingFileHandler('bad_example.log', interval=1e8,
                                        when='S', backupCount=3, encoding='UTF8')
file_handler2 = TimedRotatingFileHandler2('good_example.log', interval=1e8,
                                        when='S', backupCount=3, encoding='UTF8')
logger.addHandler(file_handler)
logger.addHandler(file_handler)

for _ in range(5):
    logger.debug('test')
    time.sleep(2)
    file_handler.doRollover()
    file_handler2.doRollover()

**Comment by sobolevn** [comment]
You can use  ` ``` ` for formatting, see https://docs.github.com/ru/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

**Comment by AndreyDukhin** [comment]
`import os
import logging
from logging.handlers import TimedRotatingFileHandler
import time


class TimedRotatingFileHandler2(TimedRotatingFileHandler):
    def doRollover(self):
        # do a rollover; in this case, a date/time stamp is appended to the filename
        # when the rollover happens.  However, you want the file to be named for the
        # start of the interval, not the current time.  If there is a backup count,
        # then we have to get a list of matching filenames, sort them and remove
        # the one with the oldest suffix.
        if self.stream:
            self.stream.close()
            self.stream = None
        # get the time that this sequence started at and make it a TimeTuple
        currentTime = int(time.time())
        dstNow = time.localtime(currentTime)[-1]
        t = self.rolloverAt - self.interval
        if self.utc:
            timeTuple = time.gmtime(t)
        else:
            timeTuple = time.localtime(t)
            dstThen = timeTuple[-1]
            if dstNow != dstThen:
                if dstNow:
                    addend = 3600
                else:
                    addend = -3600
                timeTuple = time.localtime(t + addend)
        dfn = self.rotation_filename(self.baseFilename[:-4] + "." +
                                     time.strftime(self.suffix, timeTuple) + self.baseFilename[-4:])
        if os.path.exists(dfn):
            os.remove(dfn)
        self.rotate(self.baseFilename, dfn)
        if self.backupCount > 0:
            for s in self.getFilesToDelete():
                os.remove(s)
        if not self.delay:
            self.stream = self._open()
        newRolloverAt = self.computeRollover(currentTime)
        while newRolloverAt <= currentTime:
            newRolloverAt = newRolloverAt + self.interval
        #If DST changes and midnight or weekly rollover, adjust for this.
        if (self.when == 'MIDNIGHT' or self.when.startswith('W')) and not self.utc:
            dstAtRollover = time.localtime(newRolloverAt)[-1]
            if dstNow != dstAtRollover:
                if not dstNow:  # DST kicks in before next rollover, so we need to deduct an hour
                    addend = -3600
                else:           # DST bows out before next rollover, so we need to add an hour
                    addend = 3600
                newRolloverAt += addend
        self.rolloverAt = newRolloverAt


logger = logging.getLogger(name='test')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
file_handler = TimedRotatingFileHandler('bad_example.log', interval=1e8,
                                        when='S', backupCount=3, encoding='UTF8')
file_handler2 = TimedRotatingFileHandler2('good_example.log', interval=1e8,
                                        when='S', backupCount=3, encoding='UTF8')
logger.addHandler(file_handler)
logger.addHandler(file_handler)

for _ in range(5):
    logger.debug('test')
    time.sleep(2)
    file_handler.doRollover()
    file_handler2.doRollover()

`

**Comment by AndreyDukhin** [comment]
ok, i understand. like this, fix place
```
       dfn = self.rotation_filename(self.baseFilename[:-4] + "." +
                                     time.strftime(self.suffix, timeTuple) + self.baseFilename[-4:])

```

**Comment by akulakov** [comment]
@AndreyDukhin Why do you consider this to be a bug?

**Comment by AndreyDukhin** [comment]
re expression expect file structure
{file}.{date}.log
fact file structure
{file}.log.{date}
i wrote this in first post
its clear mistake
do you run my example? its clear

**Comment by vsajip** [comment]
This slightly modified script:
```python
import logging
from logging.handlers import TimedRotatingFileHandler
import time

logger = logging.getLogger(name='test')
logger.setLevel(logging.DEBUG)
logger.addHandler(logging.StreamHandler())
file_handler = TimedRotatingFileHandler('example.log', interval=1e8, when='S', backupCount=3, encoding='UTF8')
logger.addHandler(file_handler)

for i in range(5):
    logger.debug(f'test {i}')
    time.sleep(2)
    file_handler.doRollover()
```

When I run it:
```
$ python3.11 test.py 
test 0
test 1
test 2
test 3
test 4
$ more example.log.*
::::::::::::::
example.log.2023-01-10_10-35-56
::::::::::::::
test 2
::::::::::::::
example.log.2023-01-10_10-35-58
::::::::::::::
test 3
::::::::::::::
example.log.2023-01-10_10-36-00
::::::::::::::
test 4
```
seems to work as expected.

**Comment by AndreyDukhin** [comment]
no comment
you test backup rotation with handler "streamhandler"
just run my script and count log files

**Comment by vsajip** [comment]
> you test backup rotation with handler "streamhandler"

Sorry, what? `StreamHandler` doesn't rotate.

**Comment by AndreyDukhin** [comment]
i have 5 backup log in you example.
but backupCount=3
Backup rotation do not work
its bug

**Comment by AndreyDukhin** [comment]
i do not understand why you have 3 backup files. Look re expression, it not match with files

**Comment by AndreyDukhin** [comment]
log backups are not deleted

**Comment by vsajip** [comment]
How many backup files are there on your machine? There are 3 on my machine. What version of Python are you using?

**Comment by vsajip** [comment]
In your example code, you are adding the same handler twice:
```python
logger.addHandler(file_handler)
logger.addHandler(file_handler)
```
This is wrong - why are you doing that? Is it just a typo?

**Comment by AndreyDukhin** [comment]
>In your example code, you are adding the same handler twice:

>logger.addHandler(file_handler)
>logger.addHandler(file_handler)
>This is wrong - why are you doing that? Is it just a typo?

yes
```
logger.addHandler(file_handler)
logger.addHandler(file_handler2)

```
and yes, in python version 3.11.1 everything works, I'm confused about versions

problem only in 3.9.7

Thank you very match

**Comment by vsajip** [comment]
OK, I'll close this then. This is an old bug which has been fixed already.
