### ISSUE TITLE
[closed] generic math.root() function in python stdlib ?

### ISSUE THREAD

**Issue by ar1ja** [python/cpython#100723]
# Feature or enhancement

hello cpython devs, i think itd be nice to have a generic `math.root()` function
in the python stdlib, it can be as simple as just

```c
#include <math.h>

typedef long double ld_t;

ld_t root(ld_t n, ld_t x) {
    return pow(x, 1 / n);
}
```

where

`root(3, -10)` = cubic root -10

(note: i think it should use `powl` but its not working on my machine)

# Pitch

generic root would be nice to have in C as such operations are slow in python
and making a whole c lib for python at every project is more of a pain than a
convenience, so i think having a generic `root()` would be nice

# Previous discussion

i really dont think this is large enough change to be discussed somewhere else, its quite a small non-breaking change

(note: reason why im making this issue is that im unable to locate the math file in this project)

**Comment by eendebakpt** [comment]
There already is `math.sqrt` which works for the most common case of power 1/2. See
https://docs.python.org/3/library/math.html#math.sqrt

And for any other root you could use
```
import math

def root(a, b):
    return math.pow(a, 1./b)
```

**Comment by stevendaprano** [comment]
We should expose the standard C `cbrt()` function.

As far as a generic root function, I don't think it is worth it unless it has some functional or accuracy advantage over just writing `pow(a, 1/b)` or `a**(1/b)` directly. In the same way that C offers sqrt and cbrt because they are more accurate than calling pow, I think we should only make a root function if it is more accurate than pow.

I doubt it will be much faster than calling `pow(a, 1/b)`.

You say "such operations are slow in python" but I don't think that's true. Let's look at sqrt: there is a little bit of overhead for calling a function, but moving it into the math module doesn't remove that.

```
[steve ~]$ python3.10 -m timeit -s "x = 3.789" "x**0.5"
5000000 loops, best of 5: 82.2 nsec per loop
[steve ~]$ python3.10 -m timeit -s "x = 3.789" "pow(x, 0.5)"
2000000 loops, best of 5: 127 nsec per loop
[steve ~]$ python3.10 -m timeit -s "import math; x = 3.789" "math.pow(x, 0.5)"
2000000 loops, best of 5: 124 nsec per loop
```

If you really care about performance, using the `**` operator will be the fastest.

**Comment by TruncatedDinosour** [comment]
> We should expose the standard C `cbrt()` function.
> 
> As far as a generic root function, I don't think it is worth it unless it has some functional or accuracy advantage over just writing `pow(a, 1/b)` or `a**(1/b)` directly. In the same way that C offers sqrt and cbrt because they are more accurate than calling pow, I think we should only make a root function if it is more accurate than pow.
> 
> I doubt it will be much faster than calling `pow(a, 1/b)`.
> 
> You say "such operations are slow in python" but I don't think that's true. Let's look at sqrt: there is a little bit of overhead for calling a function, but moving it into the math module doesn't remove that.
> 
> ```
> [steve ~]$ python3.10 -m timeit -s "x = 3.789" "x**0.5"
> 5000000 loops, best of 5: 82.2 nsec per loop
> [steve ~]$ python3.10 -m timeit -s "x = 3.789" "pow(x, 0.5)"
> 2000000 loops, best of 5: 127 nsec per loop
> [steve ~]$ python3.10 -m timeit -s "import math; x = 3.789" "math.pow(x, 0.5)"
> 2000000 loops, best of 5: 124 nsec per loop
> ```
> 
> If you really care about performance, using the `**` operator will be the fastest.

ah, well, i guess ill close the issue then, thanks !

**Comment by stevendaprano** [comment]
> ah, well, i guess ill close the issue then, thanks !

Or you could suggest a more accurate algorithm for computing roots.

**Comment by stevendaprano** [comment]
> We should expose the standard C `cbrt()` function.

Ah, already done in 3.11. Excellent :-)

**Comment by vinayak19th** [comment]
Is it just me or is the pow(a,1/b) also inaccurate?  
There seems to be an issue with convergence to the exact value
>>> 125**(1/3)
4.999999999999999

**Comment by eendebakpt** [comment]
> Is it just me or is the pow(a,1/b) also inaccurate? There seems to be an issue with convergence to the exact value
> 
> > > > 125**(1/3)
> > > > 4.999999999999999
This is a result of floating point arithmetic. See https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by vinayak19th** [comment]
> > Is it just me or is the pow(a,1/b) also inaccurate? There seems to be an issue with convergence to the exact value
> > > > > 125**(1/3)
> > > > > 4.999999999999999
> 
> This is a result of floating point arithmetic. See https://docs.python.org/3/tutorial/floatingpoint.html

Yeah I figured. Just wondering if a generic function which implicitly does the rounding would be useful in mitigating careless errors this might cause

**Comment by TruncatedDinosour** [comment]
thought i forgot to close this

but anyway, floating point stuff always was weird, even addition like `0.2 + 0.1` can b stupid

anyway, ion think this will ever get added bc its so small and meaningless in most cases so idk, anyway, unrelated but my earrings r almost here, been waiting for a month :3 cant wait
