### ISSUE TITLE
Dict comprehensions are not tested at all in `test_named_expressions.py`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100746]
While working on https://github.com/python/cpython/pull/100581 I've noticed that we do not test `dict` comprehensions at all there.

I think that this needs to be improved.
I will add test case for them soon, PR is in the works.

### Linked PRs
* gh-116713
* gh-116747
* gh-116748

**Comment by hugovk** [comment]
Triage: the linked PRs are merged/closed, can this be closed?
