### ISSUE TITLE
Add inspect.ishashable

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#100875]
# A new API named `ishashable` in inspect module

# Pitch
First of all, I don't know whether this will get accepted or not but if it is then here are a few pointers

first of all, why do we need `ishashable` API in inspect
why do I need it?
I was making a lib to trace the path of a key inside a nested dict and for that, I was using ast my thought was we must have a class named Hashable in ast which could be the base class for ast.Constant and ast.Tuple may be other hashable ast nodes but that will require a lot of research for me, I don't know whether it got accepted or not 

I thought of adding a new type in the types module HashableType and then comparing in inspect like other APIs  `ismethod` , `isfunction`, and all but I need some input for this.  

# current implementation 
I am using an inbuilt function hash to check if an object in hashable 
I thought of using `__hash__` as a property of the object but the list also has `__hash__` which is not hashable 

# Previous discussion
None, but this is going to be my first PR in python so I am going to drop a mail in core mentorship list

### Linked PRs
* gh-100876

**Comment by JelleZijlstra** [comment]
We already have `isinstance(..., collections.abc.Hashable)`, although that won't catch cases where an object of a hashable type contains a non-hashable object (e.g., `([1],)`.

**Comment by Agent-Hellboy** [comment]
@JelleZijlstra i encountered this while researching, should i use this instead of hash function.

Btw,  is it possible to add a new type named HashableType in types module?

**Comment by sobolevn** [comment]
I don't think that it is really safe. We have a lot of problems with `Hashable` protocol. It is better to use something like this:

```python
def is_hashable(obj: object) -> bool:  # or typeguard if you wish
   try:
      hash(object)
   except Exception:  # or be more specific
      return False
   else:
      return True
```

This will generate correct results for any hashable / non-hashable objects.
I don't think we need an extra helper around `isinstance(..., Hashable)` 🤔

**Comment by Agent-Hellboy** [comment]
I have updated the code.

**Comment by merwok** [comment]
No, I think the `inspect` module is focused on things defined by the language (function, class, generator, etc), not all kinds of classes (which are in scope for the `abc` or `collections` module).
