### ISSUE TITLE
Possible typo in the documentation of unittest.TestLoader.testNamePatterns

### ISSUE THREAD

**Issue by busywhitespace** [python/cpython#100824]
The documentation for _TestLoader_.**testNamePatterns** in the module _unittest_ says:

> List of Unix shell-style wildcard test name patterns that test methods have to match to be included in test suites (see **-v** option).
> ...
> Note that matches are always performed using fnmatch.fnmatchcase(), so unlike patterns passed to the **-v** option, simple substring patterns will have to be converted using * wildcards.

But the option **-v** only increases verbosity, does not accept an argument, and so doesn't work with test name patterns.

In my opinion, it should be an option **-k**, because the option **-k** is used to pass a pattern as the output of `unittest --help` says:

>    -k TESTNAMEPATTERNS   Only run tests which match the given substring

Also checking the source code, **-k** is bound to _testNamePatterns_

<pre><code>parser.add_argument('-k', dest='testNamePatterns',
                    action='append', type=_convert_select_pattern,
                    help='Only run tests which match the given substring')
</code></pre>

I've created the PR in case the issue is correct.

### Linked PRs
* gh-100825
* gh-100838
* gh-100839

**Comment by hugovk** [comment]
Closing, this has been fixed in main, 3.11 and 3.10. Thanks!
