### ISSUE TITLE
Warning: "‘lo’ may be used uninitialized in this function" in `math_fsum` in `mathmodule.c`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100873]
Looks like that after https://github.com/python/cpython/commit/87d3bd0e02cddc415a42573052110eb9301d2c3d we got a new warning:
<img width="918" alt="Снимок экрана 2023-01-09 в 10 40 53" src="https://user-images.githubusercontent.com/4660275/211260435-f6ce1e4a-0e18-4065-a15f-31a53b8d7aec.png">

### Linked PRs
* gh-100881

**Comment by mdickinson** [comment]
This is a false positive; definitely not a bug, but there may be something we can do to silence the warning.

**Comment by ZeroIntensity** [comment]
if it's a false positive could casting to `void` help?

**Comment by mdickinson** [comment]
The simple and quick fix would be to initialise `lo` to `0.0`. Technically that might affect performance, but I very much doubt the effect would be measurable. The only reason I'd hesitate to just make that fix would be that if it's not clear to the compiler that `lo` isn't used uninitialized, then it's probably not clear to humans either. So there may be an opportunity to rework the code a bit to make it clearer to both humans _and_ compilers. But that opportunity also comes with a risk of inadvertently breaking something.

So I think initialising `lo` to `0.0` at the point where it's declared is the way to go; we can always look at streamlining the algorithm code in a separate PR.
