### ISSUE TITLE
Show the version of Python Launcher for Windows

### ISSUE THREAD

**Issue by oleksis** [python/cpython#100829]
# Feature or enhancement
Ability to return the version of Python Launcher for Windows running through the argument **-V** or **--version**

# Pitch
 Motivation

Starting with Python 3.11, **Python Launcher for Windows** [has been included](https://docs.python.org/3/whatsnew/3.11.html#windows-py-exe-launcher-improvements)

One way to know the version of the `py` launcher that is running is through the argument '--help' and read the first line of the help content

The following behavior is desired if the argument '--version' is added

```pwsh
➜ $env:PY_PYTHON='3.10'
 
➜ .\PCbuild\amd64\py_d.exe -V
Python Launcher for Windows Version 3.11.1+
Python 3.10.9

➜ .\PCbuild\amd64\py_d.exe --version
Python Launcher for Windows Version 3.11.1+
Python 3.10.9

➜ .\PCbuild\amd64\py_d.exe -V:3.10 -V
Python 3.10.9

➜ .\PCbuild\amd64\py_d.exe -V:3.10 --version
Python 3.10.9
```

# Previous discussion

### Linked PRs
* gh-100831
* gh-100832

**Comment by eryksun** [comment]
This will break any tool that depends on parsing the known output format of `py -V`. Maybe introduce a new "--version-launcher" option.

**Comment by oleksis** [comment]
> This will break any tool that depends on parsing the known output format of `py -V`. Maybe introduce a new "--version-launcher" option.

The  new "--version-launcher" option will show the version info and exit or pass extra arguments to the Python py launcher finded ?

**Comment by oleksis** [comment]
@eryksun thanks for the feedback i make the changes 

```pwsh
➜ $env:PY_PYTHON='3.10'
 
➜ .\PCbuild\amd64\py_d.exe -V
Python 3.10.9

➜ .\PCbuild\amd64\py_d.exe -V:3.10 --version
Python 3.10.9

➜ .\PCbuild\amd64\py_d.exe -0v
Python Launcher for Windows Version 3.12.0a3+

➜ .\PCbuild\amd64\py_d.exe --version-launcher
Python Launcher for Windows Version 3.12.0a3+
```

**Comment by eryksun** [comment]
You may be better off using `SearchPathW()` to find the path of "py.exe" and then calling `GetFileVersionInfo()`. For example, the following uses PyWin32 to inspect the version of the launcher:

```pycon
>>> py_path = win32api.SearchPath(None, 'py.exe')[0]
>>> info = win32api.GetFileVersionInfo(py_path, '\\')
>>> info['ProductVersionMS'] >> 16
3
>>> info['ProductVersionMS'] & 0xFFFF
11
>>> info['ProductVersionLS'] >> 16
1150
>>> info['ProductVersionLS'] & 0xFFFF
1013
```

The final value, 1013, is the Python API version, which isn't relevant to the launcher. The third value, 1150, is the micro version number times 1000, plus the release level times 10, plus the release serial number. In this case, the micro version number is 1 (i.e. it's version 3.11.1), the release level is 15, and the release serial is 0. The release levels are defined in Include/patchlevel.h:

https://github.com/python/cpython/blob/951303fd855838d47765dcd05471e14311dc9fdd/Include/patchlevel.h#L10-L15

**Comment by oleksis** [comment]
The launcher have the Version defined as string: `PY_VERSION`

**Comment by eryksun** [comment]
What I meant is that if you're only concerned with the py launcher on Windows, then using `GetFileVersionInfo()` will work for all versions of both the old launcher ("launcher.c") and the new launcher ("launcher2.c").

**Comment by oleksis** [comment]
I make the changes for using the new launcher ("launcher2.c") on Python 3.11+

**Comment by jaraco** [comment]
I'd recommend not to add variance with the Python launcher for Unix. Ideally these two launchers should converge. Adding changes that apply to only one because they happen to be separate implementations at the moment will only decrease the ability to converge these implementations.

Can you explain more about the motivation for the version? The current launcher already reports the version:

```
PS C:\Users\jaraco> py -V
Python 3.11.0b3
PS C:\Users\jaraco> py --version
Python 3.11.0b3
```

How is `--version-launcher` different from `--version`?

**Comment by oleksis** [comment]
How [recommended](https://github.com/python/cpython/issues/100829#issuecomment-1374633309) @eryksun adding the output to the version of the Python will break tool depending that behaviour. 

Other point is if the argument for Version action will be redirected to the same Version argument option to the Python found 

The Python Launcher for Unix until today don't have Version option for the launcher. [Here](https://github.com/brettcannon/python-launcher/discussions/259) the discussion 

Open to the ideas 💡

**Comment by brettcannon** [comment]
> How is `--version-launcher` different from `--version`?

The feature request is to know the version of the Launcher _itself_, not the version of Python that the Launcher will run on your behalf.

But one thing that isn't clear to me is what's the use case for knowing the version of the Launcher (which in the Windows case is the version of Python it was installed with)? And is the use case important enough to complicate the API for the Launcher to add another flag that's explicit to the Launcher and something it has to capture instead of launching Python?

**Comment by oleksis** [comment]
Thinking in the future, using only the Python Launcher (new version can install other Python) for integration with others tools like    Visual Studio Code, DevContainer Features, ([python-launcher  feature](https://github.com/oleksis/python-launcher/tree/main/src/python-launcher)) will easy to check what version of the Python-Launcher is available in the system

**Comment by zooba** [comment]
I'm not opposed to the change (I'd mildly prefer `--launcher-version` over `--version-launcher`), but I'm also not convinced of the use case. Feature detection would be better than checking versions, so if there are features in some versions but not others, and it matters to tools that can't just bring their own copy of the launcher with known feature set, we should add ways to detect those.

**Comment by oleksis** [comment]
I leave as a reference the fork the `Python Launcher for Windows` using `launcher2.c` from CPython and the MSI packages https://github.com/oleksis/pylauncher/releases/tag/latest

**Comment by zooba** [comment]
Repeating my concerns:
* this is not a reliable way to do feature detection. If we need feature detection, we should add that
* the PR is currently for non-programmatic use (i.e. human readable, not machine readable), so if we want machine readable (again, why?) it needs fixing
* the version is already in the help text
* nobody has provided a likely scenario for needing to read the version number by launching the file (rather than using the version APIs to read the version, or just bringing their own copy of the launcher)

**Comment by oleksis** [comment]
> * nobody has provided a likely scenario for needing to read the version number by launching the file (rather than using the version APIs to read the version, or just bringing their own copy of the launcher)

How I say before in the [comment](https://github.com/python/cpython/issues/100829#issuecomment-1374912863) , one scenario is if I want to check the version of the Python Launcher installed in the system without check the `--help` option and parse the output to find the version (`py`) of the launcher 

Other scenario for example using Devcontainer features . [Here](https://github.com/oleksis/devcontainer-features/blob/9a53d6570cb23336d1104aac935151347f58b4c7/test/python-launcher/test.sh#L33) a use case but using Python Launcher for Unix

**Comment by zooba** [comment]
You need to explain why you need to do it "without checking the `--help` option", especially since the example you posted is using the `--help` option.

**Comment by zooba** [comment]
Also, you need a scenario that isn't equally satisfied by "just run the command you want and see if it fails". Since `--help` or any new option is also going to fail if it's not installed, so you have to do this anyway.

**Comment by oleksis** [comment]
> You need to explain why you need to do it "without checking the `--help` option", especially since the example you posted is using the `--help` option.

Here was when I see  the only way to check the version I using for the setting the feature . 

Other side effects is using `--help` pass that option to the Python ( child process ) returns long  output (many lines instead just one line) to parse

**Comment by zooba** [comment]
> using `--help` pass that option to the Python ( child process ) returns long output (many lines instead just one line) to parse

For a human reading it, I agree. But for programmatically parsing the output, it's still the first line, which is much easier to read than any of the ones that come after it. We also already document the `PYLAUNCHER_DRY_RUN` environment variable, which will prevent running the child process if there's some reason you really need to do this.

I'm still not convinced we need a third way to get the version of the launcher.

**Comment by brettcannon** [comment]
I'm not convinced either, so I'm going to close this issue.
