### ISSUE TITLE
possible memory access corruption

### ISSUE THREAD

**Issue by Lagunaxx** [python/cpython#100822]
# Bug report

after calling function variable that was given as arg changes it's value.
reproduce:
load _testbug_ module from here:
[https://gitflic.ru/project/lagunax/freecad-bsplinemod](https://gitflic.ru/project/lagunax/freecad-bsplinemod)
then run next code:
```py
import testbug.Calculate.Object as CO
from testbug.Convert.Object import Vector
face1=[Vector (7.481103074617138, 1.9593129736339792, 8.972368969016198), Vector (11.66985755911539, -1.7417434358438415, 6.539787483367338), Vector (7.378754484498254, -0.7010564094778204, -2.4325814856488606), Vector (3.19, 3.0, 0.0)]
face2=[Vector (10.221859617068123, -3.7470316752740698, 12.759184350842908), Vector (5.261533933284178, -2.3789652649340307, 13.567436180290036), Vector (5.8096743162160545, 4.098066410340039, 5.968251829447128), Vector (10.77, 2.73, 5.16)]
face2projection=CO.getZProjection(face1,face2)
face1cut=CO.multiCutFacePartFromFace(face1, face2projection)
skippedNums=[]
skippedNums2=[]
nextpoint=0
crosspoint=None
usedVertex1=[]
usedVertex2=[]
startPointSearch=0
stopOnCross=False
startpointInFace1=True
inside=False
tolerance=7e-9
face1cut=CO.multiCutFacePartFromFace(face1, face2projection)
res=CO.cutFacePartFromFace(face1,face2projection,crosspoint,usedVertex1,usedVertex2,skippedNums,skippedNums2,nextpoint,None,stopOnCross,startpointInFace1,inside,tolerance)

```

next if you will look at **usedVertex1** then you will find big list value present there, but mast be [] (clean list). on next run 
```py
usedVertex1=[]
res=CO.cutFacePartFromFace(face1,face2projection,crosspoint,usedVertex1,usedVertex2,skippedNums,skippedNums2,nextpoint,None,stopOnCross,startpointInFace1,inside,tolerance)
```
**cutFacePartFromFace** works wrong, no matter that we set usedVertex1 to []. while testing i found that cutFacePartFromFace saves last usedVertex1 value and reuses it, like it makes usedVertex1 as global variable and starts to ignore what we use as arg when calling function.

same with usedVertex2

# Your environment

$ python --version
Python 3.9.2
$ uname -a
Linux producer-pc 5.10.0-20-amd64 #1 SMP Debian 5.10.158-2 (2022-12-13) x86_64 GNU/Linux

- CPython versions tested on:
- Operating system and architecture:

**Comment by ronaldoussoren** [comment]
I've quickly scanned through the code you link to, and this doesn't appear to be a bug in Python. 

Does the following code reproduce the issue you are reporting?

```python
def work_on(some_list):
     some_list.append(1)

value = []
work_on(value)
assert len(value) == 1
```

That ``value`` is changed by calling ``work_on`` is intentional in Python, a reference to the object is passed to the function and updating it in the function hence updates the value bound to the name ``value``.

**Comment by Lagunaxx** [comment]
so why when i call
```
usedVertex1=[]
usedVertex2=[]
res=CO.cutFacePartFromFace(face1,face2projection,crosspoint,usedVertex1,usedVertex2,skippedNums,skippedNums2,nextpoint,None,stopOnCross,startpointInFace1,inside,tolerance)
```
then it use old values and do not resets them to [] inside functions?

**Comment by Lagunaxx** [comment]
found my mistake. closing bug.
was missunderstood with referencing of lists
