### ISSUE TITLE
Cannot import logging module

### ISSUE THREAD

**Issue by ChangPaul** [python/cpython#100899]
Hi,

when packaging a Python gui into an executable .exe there is usually an option to run the gui without a console (e.g. using PyInstaller the option is --noconsole or --windowed).

However, if the 'logging' module is imported, this will crash the program. The first line in my program is 'import logging' and this crashes immediately. The problem is that in the 'logging' module's `__init__.py` file, the _class StreamHandler_ calls the _emit_ method, and in this case _self.stream_ will always return None.

I've tried Python3.8 and 3.10 using the latest version of PyInstaller (5.7) and the crash occurs for both.

I've currently get around this by adding
`if self.stream is None: return`
to the beginning of the emit functions. After I can import the logging module, I can handle the different logging cases as required.

**Comment by JelleZijlstra** [comment]
Could you post the stack trace for this error?

cc @vsajip for logging

**Comment by vsajip** [comment]
This might not be a `logging`-related error, perhaps just showing up as the first instance where `sys.stderr` or `sys.stdout` is accessed and found to be `None`, when that is not expected. If you are creating a windowed application, with no console, it's your responsibility to _not_ configure a `StreamHandler` using unavailable streams, but instead using other types of handler which do not depend on the missing `sys` streams - such as `FileHandler`, say.

From the evidence so far presented, it doesn't seem like a `logging` bug to me, but it may be a developer error.

**Comment by ChangPaul** [comment]
My bad, so the following does indeed work:
```
import sys
sys.stdout = open('tmp.txt', 'w')

import logging
```

Sorry, must have been coding too long into the night...
I thought I would be able to first import 'logging' and then redirect afterwards.

Thanks

**Comment by vsajip** [comment]
FWIW, I still don't see why `import logging` would fail if `sys.stderr` and/or `sys.stdout` are `None`: I see no errors.

$ python2.7 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.6 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.7 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.8 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.9 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.10 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.11 -c "import sys; sys.stderr = sys.stdout = None; import logging"
$ python3.12 -c "import sys; sys.stderr = sys.stdout = None; import logging"

**Comment by ChangPaul** [comment]
Ah ok, I did a little more digging around. You're absolutely right. `import logging` does work. The problem was this `import logging, kivy`
which mean kivy must be setting the stdout to something else when loaded.

In any case, not a bug in `logging`.
Thanks again
