### ISSUE TITLE
Update documentation for `sys.winver` to not say it's "normally the first three characters of version"

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#100894]
# Documentation

https://docs.python.org/3/library/sys.html#sys.winver says:

> The value is normally the first three characters of [version](https://docs.python.org/3/library/sys.html#sys.version).

That has not been true since Python 3.11. It should probably be updated to say something like, "The value is normally the major and minor versions of the running Python interpreter," or something along those lines.

### Linked PRs
* gh-100913
* gh-100962
* gh-100963

**Comment by eryksun** [comment]
The build architecture is also included as a suffix, except for x64.

https://github.com/python/cpython/blob/61762b93871419b34f02d83cee5ca0d94d4a2903/PCbuild/python.props#L229-L231

https://github.com/python/cpython/blob/61762b93871419b34f02d83cee5ca0d94d4a2903/PCbuild/python.props#L79-L85

For example: 

* "3.11-32"
* "3.11-arm32"
* "3.11-arm64"

There can also be a "-test" suffix (e.g. `build.bat --test-marker`), but it's not a "normal" value. For example:

* "3.11-test"
* "3.11-32-test"
* "3.11-arm32-test"
* "3.11-arm64-test"

**Comment by zooba** [comment]
> That has not been true since Python 3.11

Since 3.10 actually :)

I'm okay with only documenting it as "usually". It is actually the most useful way to find out if you're running an ARM64 version of Python, but there's no need to document it as such.
