### ISSUE TITLE
Add a new proxy node named Hashable in ast and add a new type Hashable in types module 

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#100889]
# Add a new proxy node named Hashable in ast and new type named HashableType in types module 

# Pitch
I created issue  #100875 but people do not agree with that so taking a few things from there which could be helpful 

`I was making a lib to trace the path of a key inside a nested dict and for that, I was using ast my thought was we must have a class named Hashable in ast which could be the base class for ast.Constant and ast.Tuple`

1 What do you guys think of adding a new proxy node in ast named `Hashable` which could be the proxy for ast.Constant and ast.Tuple and other hashable nodes?
2 what about adding a new type named Hashable in the types module?
# Previous discussion

**Comment by merwok** [comment]
Proposals are discussed on the ideas forums rather than github, so I’m closing this for now and you can always reopen if the discussion concludes that this is a good idea.  Thanks!

**Comment by Agent-Hellboy** [comment]
> Proposals are discussed on the ideas forums rather than github, so I’m closing this for now and you can always reopen if the discussion concludes that this is a good idea. Thanks!

Sure, let me try to implement this.
