### ISSUE TITLE
Make `copy.deepcopy` faster for `slice` objects

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100817]
## `slice`

Right now `slice` objects are deepcopied using `__reduce__` defined as:
https://github.com/python/cpython/blob/26ff43625ed7bf09542ad8f149cb6af710b41e15/Objects/sliceobject.c#L559-L563

It is one of last branches of `deepcopy` logic:
https://github.com/python/cpython/blob/26ff43625ed7bf09542ad8f149cb6af710b41e15/Lib/copy.py#L120-L157

But, since `slice` is an immutable type without nested structures, we can optimize its `deepcopy` as:

```python
d[slice] = _deepcopy_atomic
```

Before:

```
» pyperf timeit --setup 'from copy import deepcopy; s = slice(1,10,2)' 'deepcopy(s)'
.....................
Mean +- std dev: 3.46 us +- 0.18 us
```

After:

```
» pyperf timeit --setup 'from copy import deepcopy; s = slice(1,10,2)' 'deepcopy(s)'
.....................
Mean +- std dev: 277 ns +- 3 ns
```

Looks like a good speedup for just a single line!
Noticed while working on #100815 

PR is incoming.

### Linked PRs
* gh-100818

**Comment by sobolevn** [comment]
Closing, see https://github.com/python/cpython/pull/100818

**Comment by eendebakpt** [comment]
@sobolevn PR #100817 makes the `deepcopy` faster, which also has a positive effect on the speed of the `slice` deep copy:

Main: 
```
$ ./python -m pyperf timeit --setup 'from copy import deepcopy; s = slice(1,10,2)' 'deepcopy(s)'
.....................
Mean +- std dev: 2.96 us +- 0.05 us
```
PR 100817
```
 $ ./python -m pyperf timeit --setup 'from copy import deepcopy; s = slice(1,10,2)' 'deepcopy(s)'
.....................
Mean +- std dev: 2.47 us +- 0.07 us
```
