### ISSUE TITLE
Proposed Improvement to tkinter geometry manager method return values

### ISSUE THREAD

**Issue by JRiggles** [python/cpython#100891]
# Feature or enhancement

The three geometry manager methods in tkinter (`pack`, `place`, and `grid`) should return the widget on which they are called instead of returning `None`

# Pitch
It seems like an extremely common pitfall for newcomers to tkinter to do the following:
```python
my_button = tkinter.Button(text='Hello').pack()

print(my_button)
# => None
```
only to run into errors because `my_button` evaluates to `None` after being chained to a geometry manager method, i.e. `pack`

Typical practice for this reason is to declare widgets separately from adding them to a geometry manager, e.g.:
```python
my_button = tkinter.Button(text='Hello')
my_button.pack()

print(my_button)
# => .!button
```
A quick look into the [source code](https://github.com/python/cpython/blob/main/Lib/tkinter/__init__.py#L2431) for the geometry manager classes shows that it would be an extremely trivial change to return the widget on which they're called. The same line can be added to each geometry manager's respective `_configure` method:
```python
return self
```
I believe that this change would enhance the accessibility of tkinter for newcomers and provide a welcome improvement for experienced developers.

While it is *unlikely* that this proposal presents a breaking change to tkinter, it is not impossible. There is always a chance that some existing code may rely on the fact that the geometry manager methods return `None`, though this is not considered best practice.

In my estimation, the benefit of this change is obvious and the overall risk is minimal.

# Previous discussion
See this [discussion on StackOverflow](https://stackoverflow.com/questions/75060298). An example of the proposed change to the tkinter source code is included in this discussion.

**Comment by serhiy-storchaka** [comment]
Method chaining is not common in Python, and there are no enough reasons to make an exception here.

It is also potentially not future proof. If tomorrow the corresponding Tk commands will start returning something useful, we could not implement this in Tkinter if the methods already return `self`.

Propositions like this have very low chance to be accepted, so I'm closing this issue. If you find several core developers that support this idea, it can be reopened.

**Comment by terryjreedy** [comment]
I added an answer to the [SO question](https://stackoverflow.com/questions/75060298/why-do-the-tkinter-geometry-manager-methods-return-none-instead-of-returning-the/78388232#78388232url).  I am a bit tempted, but not convinced.
