### ISSUE TITLE
Discrepancy in the output of `typing.get_args` for empty tuple type annotation (`typing.Tuple[()]`/`tuple[()]`) between Python3.10 & Python3.11

### ISSUE THREAD

**Issue by lycantropos** [python/cpython#100820]
# Bug report

For `Python3.8`-`Python3.10` we have
```python
from typing import Tuple, get_args

assert get_args(Tuple) == ()
assert get_args(Tuple[()]) == ((),)
```

For `Python3.11` behavior changed
```python
from typing import Tuple, get_args

assert get_args(Tuple) == ()
assert get_args(Tuple[()]) == ()
```
which is a problem since it returns the same output for different cases: when there's no info about `tuple` elements and when there's no elements in a `tuple`.

# Your environment

- CPython versions tested on: Python3.8.16, Python3.9.16, Python3.10.9, Python3.11.1.
- Operating system and architecture: macOS 13.1 i386, but I expect it to be OS-independent, reproduces in docker for `python:3.10.9` (`sha256:b4b8149f2ff93c993d9b752dd4298493975e341a6b542a33cdfb86ce52555f36`) & `python:3.11.1` (`sha256:a46b962871434568d186ef17ae7038055e17c670833ca5320fc107435fa146d7`) images.

**Comment by lycantropos** [comment]
Looks like related to
https://github.com/python/cpython/issues/91137

**Comment by hauntsaninja** [comment]
Thanks for reporting, and yes, related to the issue you link to. This is mentioned in 3.11's What's New over here: https://docs.python.org/3/whatsnew/3.11.html#typing

@JelleZijlstra (one of the maintainers of typing.py) ran into the change in behaviour in this comment https://github.com/python/cpython/issues/91137#issuecomment-1093946369 and preferred the new behaviour, so it's highly unlikely that CPython would revert this.
