### ISSUE TITLE
Improve tests of `copy` module

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100871]
After working on https://github.com/python/cpython/issues/100817 I've noticed that there are multiple things that can be improved in terms of `copy` module tests:
1. First of all, I had submitted some broken code in https://github.com/python/cpython/pull/100818 but, our test cases were not able to detect it. Solution: add a new test case in `test_slice.py` with `copy` and `deepcopy` calls. I think it should be in `test_slice` and not in `test_copy`, because there's nothing special about it: `copy` does not change its behaviour or special case it.
2. This test ensures that after modifing `copyreg` we can now copy an object, but does not assert the result: https://github.com/python/cpython/blob/e47b13934b2eb50914e4dbae91f1dc59f8325e30/Lib/test/test_copy.py#L42-L55 Right now it can be whatever. The same happens in https://github.com/python/cpython/blob/e47b13934b2eb50914e4dbae91f1dc59f8325e30/Lib/test/test_copy.py#L302-L315 Solution: add required assertions
3. `test_deepcopy_atomic` misses several important types: `bytes`, `types.EllipsisType`, `NotImplementedType`. https://github.com/python/cpython/blob/e47b13934b2eb50914e4dbae91f1dc59f8325e30/Lib/test/test_copy.py#L350-L359

PR is incoming.

### Linked PRs
* gh-100872
* gh-100975
* gh-100976

**Comment by AlexWaygood** [comment]
Thanks @sobolevn!
