### ISSUE TITLE
Document that asyncio.wait() cancels remaining Tasks for you

### ISSUE THREAD

**Issue by sfgeorge-vl** [python/cpython#100928]
# Documentation

The following statement in the [asyncio.wait() documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) has confused folks to interpret it to mean that when once the `return_when=` condition is satisfied in a call to `done, pending await asyncio.wait(..., timeout=..., return_when=....)` , one needs to cancel remaining tasks themself:

> Unlike [wait_for()](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for), wait() does not cancel the futures when a timeout occurs.

The above statement is correct, as it only relates to the `timeout=` kwarg.  However, it is easily misunderstood to mean that, once the `return_when=` condition is met, there may be remaining tasks that one needs to explicitly cancel.

On the contrary, whenever the `return_when=` condition becomes satisfied before any `timeout=` may take effect, all of the remaining tasks are canceled for you:

`return_when=` Constant | Description
-- | --
FIRST_COMPLETED | All Tasks that did not complete are Task.cancel()-ed.
FIRST_EXCEPTION | All Tasks that did not raise the Exception are Task.cancel()-ed.
ALL_COMPLETED | By its nature, there are no remaining Tasks to cancel in this case.

I recommend that the documentation be augmented to say something like this:

> Unlike [wait_for()](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for), wait() does not cancel the futures when a timeout occurs.
> However if the return_when condition is satisfied before a timeout is reached, then all remaining tasks provided to wait() will be canceled.

**Comment by gvanrossum** [comment]
Sure, please submit a PR.

**Comment by sfgeorge-vl** [comment]
Closing this issue!  Apologies I was wrong, `asyncio.wait()` doesn't cancel tasks for you!  Sorry for the confusion.  My error in my previous testing was that I didn't attempt to _await_ the _pending_ tasks returned from `asyncio.wait()`.  As a result, my call to `asyncio.run(main())` finished with a remaining Task running, and the closing of the event loop triggered the cleanup / cancelations for me.

Toggling the following script with `go(wait=False)` vs. `go(wait=True)` shows my error.

Note to self: After calling `done, pending = asyncio.wait(...)`, the remaining _pending_ Tasks should either be await-ed or cancel()-ed, not left for something else to (maybe) clean them up.

```python
import asyncio
import time


async def rest(delay):
    try:
        await asyncio.sleep(delay)
        print(f'rest(delay={delay}) completed')
    except asyncio.CancelledError as e:
        print(f'rest(delay={delay}) was canceled')
        raise e


async def go(*, wait: bool):
    start = time.time()
    slow_delay = 10
    print(f'go(wait={wait}) Start')
    done, pending = await asyncio.wait(
        [
            asyncio.create_task(rest(1), name='Fast Task'),
            asyncio.create_task(rest(slow_delay), name='Slow Task'),
        ],
        return_when=asyncio.FIRST_COMPLETED
    )

    if wait:
        for task in pending:
            print(f'Waiting for {task.get_name()} to finish, {time.time() - start} seconds later')
            await task

    print(f'go(wait={wait}) Ended in {time.time() - start} seconds')
    print()


async def main():
    await go(wait=False)
    # await go(wait=True)

    await asyncio.sleep(1)
    print('exiting main()')


if __name__ == '__main__':
    asyncio.run(main())
    print('event loop is over')
```

**With `go(wait=False)`:**
```
go(wait=False) Start
rest(delay=1) completed
go(wait=False) Ended in 1.0017192363739014 seconds

exiting main()
rest(delay=10) was canceled
event loop is over
```

**With `go(wait=True)`:**
```
go(wait=True) Start
rest(delay=1) completed
Waiting for Slow Task to finish, 1.0047636032104492 seconds later
rest(delay=10) completed
go(wait=True) Ended in 10.032713890075684 seconds

exiting main()
event loop is over
```
