### ISSUE TITLE
Do not encourage 'if elem' comparisons where 'elem' could be None

### ISSUE THREAD

**Issue by ispsv** [python/cpython#100994]
# Documentation

Yesterday pytest issued the following warning:
`...py:43: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.`
   `if root:`

Here `root` is initialised to `None` and afterwards conditionally changed.

I later came across the following example in the documentation:

**Match Objects**
Match objects always have a boolean value of True. Since [match()](https://docs.python.org/3/library/re.html?highlight=re#re.Pattern.match) and [search()](https://docs.python.org/3/library/re.html?highlight=re#re.Pattern.search) return None when there is no match, you can test whether there was a match with a simple if statement:

```
match = re.search(pattern, string)
if match:
    process(match)
```

I suppose this is not the single occurrence of a similar outdated example in the documentation.

**Comment by ericvsmith** [comment]
What code was pytest warning about? I think `if match` is a safe pattern for `re`, and won't be broken, ever.

**Comment by ispsv** [comment]
Oh. now I notice that pytest was falsely inferring because of a loop that the type of root is a list. It also seemed weird to me that 'if None' comparison will not be supported in the future.

Thanks, I will close the issue now.
