### ISSUE TITLE
ipaddress module incorrectly identifies ipv6 link-local

### ISSUE THREAD

**Issue by rohitsodhia** [python/cpython#100995]
# Bug report
According to the [ipv6 special registry](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml) mentioned under the ipaddress is_private, link-local addresses are defined as `fe80::/10`, which expands out to `fe80:0000:0000:0000:y:y:y:y`, where `y` is any hex value from 0 to FFFF. The `is_private` property identifies any ipv6 address starting with `fe80` as private, even though link-local requires the next 3 segments to be 0.

```
>>> ip_address('fe80::1:1:1:1').is_private
True
>>> ip_address('fe80::1:1:1:1:1').is_private
True
```

The second example should not be true, as expanded it would be `fe80:0000:0000:0001:0001:0001:0001:0001`, which is not a valid link-local address.

This extends to the `is_link_local` property, which also shows true in both cases, while the second should be False

# Your environment

- CPython versions tested on: 3.8.13
- Operating system and architecture: OSX 12.6.2

**Comment by ronaldoussoren** [comment]
``fe80::/10`` is a prefix where the first 10 *bits* are fixed, and ``fd80::1:1:1:1`` is in that prefix (basically anything from ``fe80`` up to and including ``febf`` in the first segment is in this prefix.

**Comment by rohitsodhia** [comment]
My gosh, I'm sorry. Apparently this was explained to me wrong. Thanks for helping clarify.
