### ISSUE TITLE
Arbitrary code execution (python 3.8.10)

### ISSUE THREAD

**Issue by isard** [python/cpython#100971]
A student of mine accidentally has found a security issue in python 3.8.10 (at least on two different Ubuntu-derived distributions).

If you create a file called   uu.py   and any other python file in the same folder, whenever python raises a ValueError the   uu.py   is executed.

Example:

==================== uu.py ===================
```
import os
print("""
*****************************
*
* Arbitrary code execution! *
*
*****************************
""")
os.system("ls -al")
```

===== suposed-safe-file.py =====
```
number = float(input("Type a number: "))
if number > 0:
    print(number, "is positive")
```

If you type a string instead of a number when prompted, a ValueError is raised; however, uu.py is executed before.

-------------- Output ----------------
```
Type a number: a

*****************************
*
* Arbitrary code execution! *
*
*****************************

total 176
drwxrwxr-x  3 1001 1001   4096 de gen.  12 10:10 .
drwxr-xr-x 52 1001 1001 143360 de gen.  12 10:03 ..
drwxrwxr-x  2 1001 1001   4096 de gen.  12 10:10 __pycache__
-rw-rw-r--  1 1001 1001     89 de gen.  12 10:06 suposed-safe-program.py
-rw-rw-r--  1 1001 1001    139 de gen.  12 10:10 uu.py
Traceback (most recent call last):
  File "suposed-safe-program.py", line 1, in <module>
    number = float(input("Type a number: "))
ValueError: could not convert string to float: 'a'
```

**Comment by stevendaprano** [comment]
I cannot replicate this bug under Python 3.10 or 3.7 on Fedora Linux.

Have you replicated it yourself or are you just repeating what your student has told you?

How are you running the `suposed-safe-file.py` file?

If you replace the content of `suposed-safe-file.py` with a single line:

    raise ValueError('error')

does the behaviour change?

If you run under isolated mode using `python -I suposed-safe-file.py` does the behaviour change?

**Comment by eryksun** [comment]
This is the expected behavior. Normally the directory of the running script is prepended to `sys.path`, which gives priority to versions or implementations of modules and packages that are beside the script, even in place of modules in the standard library, such as [`uu`](https://docs.python.org/3.8/library/uu.html) (except for frozen modules in the interpreter binary such as `__hello__`).

For system scripts and any other collection of unrelated scripts in a directory, an [[I]solated mode](https://docs.python.org/3.8/using/cmdline.html#id2) is supported. This is an extreme measure, however, because it also ignores the user site packages and all `PYTHON*` environment variables. Starting with Python 3.11, a more surgical [safe [P]ath](https://docs.python.org/3.11/using/cmdline.html#cmdoption-P) option is supported.

**Comment by isard** [comment]
@stevendaprano 

Of course I have tested myself. :-)

I've tried what you suggested and uu.py is also executed.

```

$ cat second.py                                               12:10:32
raise ValueError("error")
$ python3 second.py                                           12:10:41

*****************************
*
* Arbitrary code execution! *
*
*****************************

total 188
drwxrwxr-x  3 1000 1000   4096 de gen.  12 12:10 .
drwxr-xr-x 52 1000 1000 143360 de gen.  12 10:03 ..
drwxrwxr-x  2 1000 1000   4096 de gen.  12 12:10 __pycache__
-rw-rw-r--  1 1000 1000     26 de gen.  12 12:09 second.py
-rw-rw-r--  1 1000 1000     87 de gen.  12 10:29 suposed-safe-program.py
-rw-rw-r--  1 1000 1000    139 de gen.  12 12:10 uu.py
Traceback (most recent call last):
  File "second.py", line 1, in <module>
    raise ValueError("error")
ValueError: error
```

If I use -I flag  uu.py  is not executed, as expected.

**Comment by isard** [comment]
@eryksun 

> This is the expected behavior.

Oh, I see.

It is a little bit inconvenient, though, because programmers should get a list of names that they should not use as filenames to avoid potencially dangerous situations; even more, everyone should make sure nobody has added a "wrong-named" file into the directory they are running a python script from.

**Comment by eryksun** [comment]
> why is uu being imported in the absense of an `import uu` statement?

It's an Ubuntu Linux thing. It sets a custom `sys.excepthook` that imports Ubuntu's `apport` package, which sets off the chain of imports `urllib.request` -> `http.client` -> `email.message` -> `uu`.

**Comment by gpshead** [comment]
There will be other module names dynamically imported that someone can squat on outside of Linux distro modified environments like Ubuntu's, but this is still Python working as intended, for better or worse.
