### ISSUE TITLE
Potential bug in heapq.heappush?

### ISSUE THREAD

**Issue by vincent-grosbois** [python/cpython#100968]
# Bug report

Hello,
it seems that the heapq module doesn't really handle exceptions well and can end up generating invalid structure in the case of exception. Consider the following code:
```
import heapq
x = []
heapq.heappush(x, 1)
print(x)
try:
    heapq.heappush(x, "a")
except:
    pass
print(x) # [1, 'a']
```

 As expected, the second call to heappush is throwing an exception. However, I notice that the second item was inserted in the array anyway. This array was supposed to always contain a heap, and now it isn't a heap anymore, and it contains data that is in an invalid state
One could assume that when being a client of he heapq module, if I manipulate heaps I will always get a heap in my program, even in the case of exception thrown on bad input.

**Shouldn't heappush method undo the insert of "a" in case it can't finish the heapify process on insertion ?**

Consider the case where you have a multi-threaded system relying on this. Assume I have some workers that are dequeueing from the heap, and some worker processes that are inserting in the heap. This means that if a worker is incorrectly inserting an invalid type, the worker will raise an excpetion as expected and potentially crash (this is OK). But it means that subsequent calls to any heap methods by the other workers will also fail as the heap will contain invalid data. Note that PriorityQueue class isn't doing specific error-handling in the case of exception either ( https://github.com/python/cpython/blob/3.11/Lib/queue.py#L236 )

Even if as a user I wanted to try/catch on every `heapq.heappush()` call, it's not even obvious how I could recover from this error and revert back to the initial state manually

# Your environment
Python 3.11

**Comment by sobolevn** [comment]
I can confirm that the same happens on `main` and `3.7` (the oldest python I have).
It happens for both C and Python implementations.

We even have a similar test case for `heapq` here: https://github.com/python/cpython/blob/d9dff4c8b5ab41c47af002ad7fb083c953e75f31/Lib/test/test_heapq.py#L394-L401

But, we don't assert what is going on with `seq` there.
But, for example this line has the same bug:

```python
for f in (self.module.heappush,):
    self.assertRaises(ZeroDivisionError, f, seq, 10)
```

`seq` becomes:

```
[<test.test_heapq.CmpErr object at 0x10bef4c40>,
 <test.test_heapq.CmpErr object at 0x10c4383d0>,
 10]
```

But, I cannot find anything in the docs that gives any guarantees about mutability of the input.

The only thing `heappush` says that is somewhat related:

> Push the value item onto the heap, maintaining the heap invariant.
> maintaining the heap invariant

So, I guess - it is supposed to main the invariant here? 

CC @rhettinger

**Comment by vincent-grosbois** [comment]
Hi, thanks for the reply

>None of the heap operations are intrinsically thread-safe. A user would need to put locks around the calls or isolate them to a single thread.
it's not really related to thread-safety. For instance if you use queue.PriorityQueue, it is thread-safe, but it still exhibits the same behavior, where an invalid call to heapq.heappush() will put the queue in an invalid state for all other threads

> There is nothing to prevent a user from altering a heap in the middle of an operation or to prevent them from breaking the heap invariant.
agreed, but here the issue is that incorrect user input that is calling a library function will break the heap invariant. So you can break the heap structure just by calling functions that are supposed to _help_ you create this heap invariant.

>if your code is run through a type checker, this kind of error can be detected in advance.
That's true for a simple example but it's possible to find more complex examples where this will occur. For instance I guess you can have a complex type where the comparison function is a user-defined function, that will end up throwing exception in some cases

>, I don't think there is anything reliable that heapq could do to handle all variations of this problem. 
Another issue I have is that if it's not handled by heapq itself, how are the users even supposed to handle this in their calling code ? It's much harder to handle for the outside of the function by looking at the raised exception, than internally in the function itself.


Overall, to me this issue just boils down to the fact that users are using heapq as a way to build heap datastructure. The usual assumption is that inserting things in a data structure, in a case of exception, will not insert any data. Here there are 2 unexpected behaviors : one is inserting data even though the insertion called failed, and the other is that the heap invariant is not true anymore.

In any case, I just wanted to raise this concern, but maybe it's not worth splitting hairs over this

**Comment by rhettinger** [comment]
If the  shared siftup or siftdown routines encounter an exception in the middle of updating the heap, how do you propose to restore the starting state short of making a copy of the stating state?

And if a program is commingling incompatible types, why shouldn't the programmer be expected to find and fix the bug during testing?  

> maybe most users are used to this behavior

Not at all.  Consider a failed dictionary update.  We don't save a copy of the starting state and restore it later:

```
>>> d = dict(a=1, b=2, c=3)
>>> d.update([('d', 4), ('e', 5), (['f'], 6), ('g', 7)])
Traceback (most recent call last):
  File "<pyshell#8>", line 1, in <module>
    d.update([('d', 4), ('e', 5), (['f'], 6), ('g', 7)])
TypeError: unhashable type: 'list'
>>> d   # The dict has mutated and that the update is only partially complete.
{'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
```

**Comment by tim-one** [comment]
> how do you propose to restore the starting state short of making a copy of the stating state?

I'm not in favor of changing anything here (it's a "garbage in, garbage out" thing to me), but in this specific case the heap sifting routines could be wrapped in `try/except` constructs to catch, and re-raise, any exceptions along the way, While sifting. append to a list of `(src, dst)` int pairs, recording the sequence of data moves via capturing the source and destination list indices of moves (ya, ya, sometimes it could be reduced - complications aren't interesting :wink:). In case of exception, use the list to reverse the moves. Since there are only `O(log(len(heap)))` pairs at most, this is practical. But overwhelmingly, according to me, a waste of time. I've run literally trillions of heap operations by now, and never gave a single thought to this before 😆.

**Comment by vincent-grosbois** [comment]
> If the shared siftup or siftdown routines encounter an exception in the middle of updating the heap, how do you propose to restore the starting state short of making a copy of the stating state?

Honestly I don't know. But maybe the fact that it's complex to solve doesn't mean it should never be implemented (assuming there is a way to do it that doesn't lower the performance in the non-error case). Also, callers who would want to handle this are in a way worse position to "undo" the changes as they can't get the full context from the stacktrace.

As it was said above, I agree it's completely a problem a "garbage in, garbage out" (and same issue with sort, etc). Maybe then it's more a question of documentation, since users can have the expectation that the system is more robust and that even "garbage" input data won't change their structure invariant (ie the `strong exception guarantee`)

**Comment by rhettinger** [comment]
Thank for the suggestion, but I will decline.   

* Extensive real world experience to date indicates that this isn't a problem in practice.  
* Commit/rollback logic isn't the norm or expectation elsewhere in Python.  
* Implementing it would be complex and likely introduce new issues of its own.
* Tim's described an O(log n) solution that records the chain of swaps for a possible "undo" recovery. However, that would add time and space overhead to the normal path for recording the swaps.  This would make everyone pay for a feature that almost no one needs.
* Even if implemented, I don't see how users would benefit — they still get an exception they need to fix and they will have to cope with a heap that is missing the data they tried to add. 

If you still think this is expected and worth the cost, I suggest posting code on the Python Package Index to see if any users actually want this functionality and are willing to pay a cost for it.

**Comment by rhettinger** [comment]
FWIW, here's a wrapper function than might meet your needs:

```
def mypush(h, x):
    copy = h[:]
    try:
        heapq.heappush(h, x)
    except TypeError:
        h[:] = copy
        raise
```
