### ISSUE TITLE
For command line examples in the documentation, use "python" rather than "python3"

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#100972]
### Linked PRs
* gh-100973

**Comment by hugovk** [comment]
Note: similar to https://github.com/python/cpython/issues/98763.

**Comment by rhettinger** [comment]
On my Mac, python no longer refers to an executable. Only python3 works. So, at least for Mac Users, the status quo is better. With the proposed substitutions, the examples won't work any more.

**Comment by erlend-aasland** [comment]
Closing this; see my https://github.com/python/cpython/pull/100973#issuecomment-1597765284 for my explanation.
