### ISSUE TITLE
"OSError not raised by Listener" in test_asyncio test_multiprocessing_* with Linux kernel 6.0.16-6.1.3 (kernel bug)

### ISSUE THREAD

**Issue by mgorny** [python/cpython#100945]
# Bug report

A few tests in CPython's test suite have suddenly started failing. I've first experienced the problem rebuilding 3.8.16 on 2023-01-11, then confirmed it on top of 3.12.0a3, 3.12.0a4 and main today. The same 3.8.16 and 3.12.0a3 versions used to pass the respective tests on 2012-12-07. I'm currently trying to investigate what have changed since but unfortunately it's hard for such a large span of time. Any ideas what to look for would be appreciated.

The failing tests are:

```
4 tests failed:
    test_asyncio test_multiprocessing_fork
    test_multiprocessing_forkserver test_multiprocessing_spawn
```

FWICS all the failures resemble this one:

```pytb
======================================================================
FAIL: test_multiple_bind (test.test_multiprocessing_spawn.WithProcessesTestListener.test_multiple_bind)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/mgorny/git/cpython/Lib/test/_test_multiprocessing.py", line 3377, in test_multiple_bind
    self.assertRaises(OSError, self.connection.Listener,
AssertionError: OSError not raised by Listener
```

I've run these tests using:
```
./python -u -W default -bb -E -E -m test -v test_asyncio test_multiprocessing_fork test_multiprocessing_forkserver test_multiprocessing_spawn
```

Full log (415k): [test.txt](https://github.com/python/cpython/files/10393849/test.txt)

# Your environment

- CPython versions tested on: 3.8.16, 3.12.0a3, 3.12.0a4, 762745a124cbc297cf2fe6f3ec9ca1840bb2e873
- Operating system and architecture: Gentoo Linux amd64, glibc 2.36-r6 p6, kernel 6.0.18-gentoo-dist

**Comment by AlexWaygood** [comment]
Looks like this might be the same issue as https://discuss.python.org/t/linux-kernel-6-0-16-6-0-18-breaking-python-tests-allows-to-bind-a-socket-twice/22701?

**Comment by gvanrossum** [comment]
Then do we need to keep this issue open?

**Comment by mgorny** [comment]
Yeah, I've just confirmed that they pass with 6.0.15 yet fail with 6.0.16.

**Comment by hhoffstaette** [comment]
The kernel regression has been [noted](https://lore.kernel.org/stable/CAFsF8vL4CGFzWMb38_XviiEgxoKX0GYup=JiUFXUOmagdk9CRg@mail.gmail.com/) and is being addressed.

**Comment by gpshead** [comment]
If a specific range of bad kernel versions can be identified, the best we can do is add unittest.skipIf decorators to impacted tests (or entire test suites if the blast radius is huge) when that kernel version is detected.

**Comment by hroncok** [comment]
For now, the estimated range is 6.0.16-6.1.3

**Comment by zware** [comment]
That sounds to me like a small enough range with a big enough problem that the most we should really do here is pin this issue for a while; considering that two separate distros have independently found the issue, I would not expect there to be widespread deployments of these versions.  If I'm wrong about that, then a conditional `expectedFailure` might be warranted.

I've edited the title since this is *not* a test regression on our part, and recommend that it be closed.

**Comment by kumaraditya303** [comment]
Pinned and closed, will unpin later.
