### ISSUE TITLE
There is no the cotangent function in the math library

### ISSUE THREAD

**Issue by DmitryMaslov1** [python/cpython#100943]
I'd like to offer you to add the cotangent function to the math library. After all, that is an essential function in mathematics.

**Comment by ajoino** [comment]
I don't think I've ever used cotangent, secant, or cosecant, they mostly seem to be used in American literature (somebody please correct me on that), so I dispute your claim that they are essential.

**Comment by stevendaprano** [comment]
@ajoino it is hard to define which trig functions are "essential" and which can be derived from others. In symbolic maths, cot is definitely just as useful as tan, but it's not clear to me how essential it is for numeric maths.

@MitreyIvanov I think an important question is whether 1/tan is accurate enough, or if there is an algorithm for cot that is more accurate. If we can't do better accuracy than 1/tan or cos/sin, then there is no real point in creating a special cot function.

@mdickinson @tim-one what do you think? Is there a case for this?

**Comment by mdickinson** [comment]
On accuracy: C doesn't provide `cot`, so we'd only be doing `1/tan` or `cos/sin` at C level anyway, which will still be good to within 1.5ulps or so. (We're not going to write our own custom implementation in `mathmodule.c` just to get an extra bit of accuracy.)

Using `1/math.tan(x)` or `math.cos(x) / math.sin(x)` as @hugovk suggested seems plenty good enough.

**Comment by mdickinson** [comment]
Sorry, I don't really see a case for this. I'm going to close here.

**Comment by ajoino** [comment]
> @ajoino it is hard to define which trig functions are "essential" and which can be derived from others. In symbolic maths, cot is definitely just as useful as tan, but it's not clear to me how essential it is for numeric maths.

Yeah it's difficult to define. Here in Sweden we never use sec, csc, or cot in favor of using 1/cos, 1/sin, and 1/tan. But some formulas do look very elegant when you use "the other three" trig functions (as if there was only 6 of them), and I guess if you're getting technical you could get away with only sin(x+\theta) and 1/sin(x+\theta)? Been a while since I did much trig so I'm probably wrong there.

**Comment by stevendaprano** [comment]
Depending on what you count, there could be 1, 3, 6 or 12 trig 
functions. Or even 0. (Use the real and imaginary parts of Euler's 
Formula e^(i x) 

https://www.johndcook.com/blog/2009/09/25/how-many-trig-functions/

https://en.wikipedia.org/wiki/Euler's_formula

**Comment by BLCXD** [comment]
> Can you use `1/math.tan(x)` or `math.cos(x)/math.sin(x)`?

Thanks
