### ISSUE TITLE
segfault in property.getter/setter/deleter if property subclass has weird __new__

### ISSUE THREAD

**Issue by cfbolz** [python/cpython#100942]
CPython crashes if run on the following code:

```python
class pro(property):
    def __new__(typ, *args, **kwargs):
        return "abcdef"
class A:
    pass

p = property.__new__(pro)
p.__set_name__(A, 1)
np = p.getter(lambda self: 1)
```

The crash happens on the last line. The problem is the [following code](https://github.com/python/cpython/blob/762745a124cbc297cf2fe6f3ec9ca1840bb2e873/Objects/descrobject.c#L1710) in `property_copy`:

```c
    new =  PyObject_CallFunctionObjArgs(type, get, set, del, doc, NULL);
    Py_DECREF(type);
    if (new == NULL)
        return NULL;

    Py_XSETREF(((propertyobject *) new)->prop_name, Py_XNewRef(pold->prop_name));
    return new;
```

In the crashing code, `new` is a string, so casting it to `propertyobject` and writing to `prop_name` is wrong.

This is synthetic code, I found the problem while porting some 3.10 features to PyPy and thinking about corner cases.

### Linked PRs
* gh-100955
* gh-100965
* gh-101008
* gh-101009

**Comment by mdboom** [comment]
Confirmed on 3.10, 3.11 and main.

**Comment by sobolevn** [comment]
`__set_name__` part is not required for the repro:

```python
class pro(property):
    def __new__(typ, *args, **kwargs):
        return "abcdef"

p = property.__new__(pro)
np = p.getter(lambda self: 1)
```

This code also crashes on 3.12

**Comment by rhettinger** [comment]
This did not fail on 3.9.   Soonish, I will hunt down the offending check in.  Off hand, I suspect the disasterous and now deprecated descriptor chaining logic.

**Comment by sobolevn** [comment]
Commit that introduced these lines: https://github.com/python/cpython/commit/c56387f80c5aabf8100ceaffe365cc004ce0d7e0

**Comment by rhettinger** [comment]
Confirmed, c56387f80c5 is the culprit.

**Comment by rhettinger** [comment]
@sobolevn Thank you for the back ports.
