### ISSUE TITLE
Improve layout of the documentation for array

### ISSUE THREAD

**Issue by ad-chaos** [python/cpython#100925]
# Documentation

Taking a look at the documentation for [`array`](https://docs.python.org/3/library/array.html) and specifically the methods and module level attributes it defines, we see the following.

<img width="847" alt="Screenshot 2023-01-11 at 12 00 02 AM" src="https://user-images.githubusercontent.com/90276965/211633089-ec6e3daf-14cc-44ca-ae20-acb8572aa15b.png">

The layout — mentioning a module level constant `array.typecodes` after the `array` class description and before the methods on the type, would suggest that `typecodes` is an attribute of the `array` type, but it is actually an attribute of the `array` module

If one reads carefully they'll notice the line that states
```
The following data items and methods are also supported:
```
But an eye that skims past that text might mistake it for being an attribute of the `array` type.

Maybe a clear demarcation between the module definitions and the functions defined by the `array` type would be more helpful.

Taking a look at another standard library datatype [`collections.Counter`](https://docs.python.org/3/library/collections.html#collections.Counter), here the class methods are shown right below its description.

The [`datetime`](https://docs.python.org/3/library/datetime.html#constants) module has a section that defines module level constants and then shows the types.

It would be nice to follow the same pattern for `array`.

### Linked PRs
* gh-101239
* gh-101485
* gh-101527
* gh-101528

**Comment by theWiseAman** [comment]
@ad-chaos Okay let me author a pull request for this.

**Comment by hauntsaninja** [comment]
Thanks, looks like this was refactored
