### ISSUE TITLE
Improve `pickle` protocols coverage in `test_slice` 

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100931]
While working on https://github.com/python/cpython/issues/100817 I've noticed that `slice` is only tested with 3 `pickle` protocols. See https://github.com/python/cpython/blob/8dd2766d99f8f51ad62dc0fde8282483590c6cd0/Lib/test/test_slice.py#L237-L243 I don't think we need to limited supported protocols. Let's test all protocols!

### Linked PRs
* gh-100932
* gh-100978
* gh-100979

**Comment by AlexWaygood** [comment]
Thanks!
