### ISSUE TITLE
Remove `check_string` and `check_mapping` from `test_xml_etree`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#100933]
Right now one test in `test_xml_etree` contains two helpers called `check_mapping` and `check_string`:

https://github.com/python/cpython/blob/8dd2766d99f8f51ad62dc0fde8282483590c6cd0/Lib/test/test_xml_etree.py#L206-L241

It originates from very old code: https://github.com/python/cpython/blob/d9a550b5e14db2748f4fe089c2637c3462ad7d8d/Lib/test/test_xml_etree.py#L140-L169

It is half-baked with lots of obvious things to be improved.

I think that it is safe just to replace them with:
- `check_string` to `assertIsInstance(str)`
- `check_mapping` to `assertIsInstance(dict)`

It is more correct, because both Python and C implementations only use `str` and `dict` for checked attributes. And in this case we can skip re-inventing tests for mapping and string.

### Linked PRs
* gh-100934
* gh-101686
* gh-101687

**Comment by hauntsaninja** [comment]
Thank you!
