### ISSUE TITLE
Specialization of some instructions does not conform to PEP 659, and prevents PEP 669

### ISSUE THREAD

**Issue by markshannon** [python/cpython#100982]
As written, PEP 659 says that individual specializations are restricted to a single instruction.
PEP 669 relies on this, as it also wants to replace instructions at runtime, and it would break if specialization occurs across multiple instructions.

Currently there are a two places where we break this design by specializing pairs of instructions together:
* `COMPARE_OP` `POP_JUMP_IF_` pairs are specialized together
* `FOR_ITER` `STORE_FAST` are specialized together

The second will go away with the register VM, and doesn't seem to be an issue in practice.
It is the `COMPARE_OP` `POP_JUMP_IF_` specialization that is problematic, as PEP 669 wants to instrument branches.
Instrumenting the `POP_JUMP_IF_` doesn't work if the `COMPARE_OP` specialization jumps over it.

The solution is to replace the `COMPARE_OP` `POP_JUMP_IF_` pair with a single `COMPARE_AND_BRANCH` instruction that can be specialized or instrumented atomically.

### Linked PRs
* gh-100983
* gh-101985
* gh-102801

**Comment by markshannon** [comment]
Superinstructions are also a problem for PEP 669, but are simpler to handle, and go away with the register VM.

**Comment by brandtbucher** [comment]
`BINARY_OP_INPLACE_ADD_UNICODE` and `CALL_NO_KW_LIST_APPEND` are two more examples of "adaptive superinstructions".

Like `FOR_ITER`, though, they don't cross a branch and will probably disappear when we get a register VM.

**Comment by markshannon** [comment]
https://github.com/python/cpython/pull/100983[)](https://github.com/python/cpython/commit/7b14c2ef194b6eed79670aa9d7e29ab8e2256a56) fixed the `COMPARE_OP` issue, so I'm retitling this issue.

**Comment by markshannon** [comment]
Although `BINARY_OP_INPLACE_ADD_UNICODE` and `CALL_NO_KW_LIST_APPEND` don't cross boundaries they may cross lines which interferes with instrumentation for `LINE` events.

**Comment by markshannon** [comment]
The instruction that is skipped in `CALL_NO_KW_LIST_APPEND` is always a `POP_TOP`.
We can fix this by making sure that the `POP_TOP` following a call has no location. It probably should anyway.

`BINARY_OP_INPLACE_ADD_UNICODE` is still a problem. It is rare, so the extra cost of de-specializing it during instrumentation and preventing that specialization if instrumentation is present would probably be OK.

Note:
This is only an issue for instrumentation of `LINE` events. `INSTRUCTION` events prevent all specialization, so there cannot be a conflict.

**Comment by markshannon** [comment]
An alternative to fixing `BINARY_OP_INPLACE_ADD_UNICODE` is to restore  the old behavior of `BINARY_ADD` to special case adding strings, and make sure that `BINARY_OP` specialization is so good that the performance of plain `BINARY_ADD` is irrelevant.

**Comment by markshannon** [comment]
Which leaves `FOR_ITER_RANGE`. I'm hoping that improvements to freelists and integer representation will make the cost of creating the temporary int tolerable.

**Comment by gvanrossum** [comment]
> * `FOR_ITER` `STORE_FAST` are specialized together
> 
> The second will go away with the register VM, and doesn't seem to be an issue in practice.

Since there is no register VM (and probably won't be one, or not for a long time), what should we do about this? Ignore it because it "doesn't seem to be an issue in practice"?

OTOH maybe this issue can be closed, since it appears we do have PEP 669 after all? @markshannon

**Comment by markshannon** [comment]
`FOR_ITER` and `STORE_FAST` are no longer specialized together (specifically for PEP 669): https://github.com/python/cpython/pull/101985

So, yes this can be closed.

**Comment by markshannon** [comment]
It looks like we never fixed up `BINARY_OP_INPLACE_ADD_UNICODE`
