### ISSUE TITLE
IndexError does not trigger on logical evaluation

### ISSUE THREAD

**Issue by PetarBoshnakov** [python/cpython#100941]
Dear,

IdexError does not trigger on below code:

```python
vals = [0, 1]
res = vals[0] > 0 and vals[2] > 1
```

IndexError is not triggered in the above code. If the wrong condition is in first place as code below - IndexError is triggered:
`res_trigger = vals[2] > 1 and vals[0] > 0`

Environment:
-- Python 3.9.10

-- Windows 10 Version	10.0.19045 Build 19045

Thanks,
Petar

**Comment by chilaxan** [comment]
That behavior is intended, python has shortcutting for logical operators (ie: `A and B` will only evaluate B if A is falsy)

**Comment by cfbolz** [comment]
It's documented here: https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not
"[and] is a short-circuit operator, so it only evaluates the second argument if the first one is true."

**Comment by AlexWaygood** [comment]
@chilaxan and @cfbolz are correct. Additionally, it would break a huge amount of code to change this.

Please direct any further questions to https://discuss.python.org/c/users/7, since this is not a bug :)

**Comment by PetarBoshnakov** [comment]
looking more into this I totally agree. this can be closed then.
