### ISSUE TITLE
Why string_at function in python3 gives different result for ubuntu linux, MacOs, Amazon Linux?

### ISSUE THREAD

**Issue by gauravjain811** [python/cpython#101075]
# Bug report
Why string_at function in python3 gives different result for ubuntu linux, MacOs, Amazon Linux?

# Your environment
python 3..8
$ uname -a
Darwin MBIN0077.local 20.6.0 Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64 x86_64

if value packed in byte obj is  0x88 0xDE it becomes 0Xe4 0X8D on MacOs, Amazon Linux but remains as  0x88 0xDE  on ubuntu linux
ex:
buf_kb = ctypes.string_at(raw_data,sizeofrawData) 

P.S.: raw_data is byte object returned from function in .so <unsigned char* in c & LP c_ubyte in python 3.8>

Kindly help to resolve the same asap.

Thank you very much.

Regards,
Gaurav Jain

**Comment by stevendaprano** [comment]
This is not a help desk for asking for help with your code. This is for reporting bugs in the Python interpreter or stdlib.

If you think this is a bug, please explain *why you think it is a bug*, e.g. what you did, what result you expected, why you expected it, and what result you got inside. You will need to show [a minimal reproducible example](https://github.com/python/cpython/issues/101075) that we can run.

**Comment by iritkatriel** [comment]
Question about python can be asked on https://discuss.python.org/c/users/7.
