### ISSUE TITLE
Detecting unused unittest.mock.patch

### ISSUE THREAD

**Issue by ikonst** [python/cpython#101004]
# Feature or enhancement

Ability to track whether a (unittest.mock) patch had any effect.

# Pitch

As large codebases are refactored, tests might pass while patching functions that are not called throughout the test's execution. To keep tests lean and maintainable, one might want to identify patches are not "in use" anymore.

It might appear that checking `m.called` would suffice, but some patches are "in use" for a negative assertion, e.g. if the input is invalid, make sure we don't write to the database.

I'd like to propose another property (temporary name - `m.used`) that'll be initialized to `False` on creation and set to `True` whenever one of the `_delegating_property`-ies is accessed. This way, it'll be set to true on
- calls (`m()`)
- `assert m.called`
- `assert m.mock_calls == []`
- `m.assert_not_called()`

etc.

When starting the patch, one could choose whether stopping the patch would assert if the patch didn't appear to be "used".

**Comment by cjw296** [comment]
I'm not aware of a compelling enough use case for this given the likely impact of the clash of introducing another 'attribute that will clash with real attributes in the wild'.

I also feel that checking for `not m.used` may be more onerous than expected.
