### ISSUE TITLE
`multiprocessing.queues.Queue.qsize` raises `NotImplementedError` on macOS

### ISSUE THREAD

**Issue by ronny-montano** [python/cpython#101094]
https://github.com/python/cpython/blob/1de4395f62bb140563761ef5cbdf46accef3c550/Lib/multiprocessing/queues.py#L124-L126

I use macos, i can't use multiprocessing for this reason

**Comment by ericvsmith** [comment]
You’d have to do some research to see if sem_getvalue is still broken on macOS. Maybe raise an issue with Apple?

**Comment by zware** [comment]
Also, as the [documentation warns](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.qsize), the value returned by `qsize` isn't reliable even on platforms that implement `sem_getvalue`, and macOS might not be the only platform that doesn't.  We have `configure` tests checking for `sem_getvalue` and whether it is "broken" for `multiprocessing`'s purposes, so I presume that macOS's is still broken.

This doesn't seem like a bug worth chasing in Python, but if you can show that `sem_getvalue` does now work as expected in macOS and can provide a patch to fix it (probably by fixing the `configure` check), we can reopen the issue.

**Comment by jm-nab** [comment]
for anyone else that finds themselves here, a possible workaround can be found here: https://github.com/keras-team/autokeras/issues/368#issuecomment-461625748
