### ISSUE TITLE
A way to generate iterator values without extra overhead if I don't care about the iterator's values.

### ISSUE THREAD

**Issue by mrolle45** [python/cpython#101095]
# Feature or enhancement

I want some cheap way of running a given iterator (or iterable) to produce all its values, without any extra overhead.

# Pitch

I have an iterator, such as `map(myfunc, mylist)`.  I want to expand the map(), which is an iterator, so that I actually call myfunc(item) for each item in mylist.

I don't know any way to run the iterator without having extra overhead, such as making a tuple, as in `tuple(map(myfunc, mylist))`.

If I create a function like `def ignore(*args): pass` and call ignore(map(myfunc, mylist)), this still creates a tuple.

If I write a loop like `for _ in map(myfunc, mylist): pass`, this incurs extra interpreter overhead.

If I try something like `any(map(myfunc, mylist))`, this has only the interpreter call to `any()`, but it depends upon all the `myfunc()` results being falsy.  Likewise, using `all()` depends upon all the `myfunc()` results being truthy.

# Previous discussion

None.  I'm starting with this issue because it's pretty simple.

# Possibilities

1. A new builtin function, like `run(iterable)`, which just calls `iter(iterable).__next__()` until reaching the end, returning None.  A "C" implementation, of course.  The name `run` can be whatever you all think is most clear.
It might be included in `itertools` rather than `builtins`.
2. A method implemented by all iterable and iterator classes which does the same thing.
3. Alternate versions of some functions, such as `map`, which create iterators.  This could be a new name, or an extra keyword argument.  For example `mapall()` or `map(..., *, all=False)`.

**Comment by JelleZijlstra** [comment]
The correct answer is `for _ in it: pass`. If that creates too much overhead, we should optimize it. I don't see a strong case for adding a new builtin or language feature.

**Comment by stevendaprano** [comment]
What is the purpose of running the iterator if you don't care about the values it produces? I suppose that there must be some side-effect, e.g `it = map(print, values)`. The fastest way to run the iterator to completion without storing any values is probably either @JelleZijlstra 's answer, or [the recipe in the itertools documentation](https://docs.python.org/3/library/itertools.html#itertools-recipes). You can do your own testing to see which is faster.

As far as worrying about the cost of the for-loop, or creating a zero-size deque, this is premature micro-optimisation. What sort of function are you passing to map that does *actual real and useful work* that nevertheless is **so fast** that the bottleneck in your code becomes the one-off cost of creating a zero-size deque, or the interpreter for loop?

I think a good question is whether this feature (run an iterator for side-effects) might be sufficiently useful to have something in `itertools` with the signature `run(func, values)`, and skip the call to `map`. (I have this function in my personal toolbox of functions, except I call it `do`.) Personally, I think it is marginal: it's useful, but maybe not useful enough to justify maintaining and documenting it forever. @rhettinger what do you think?

**Comment by rhettinger** [comment]
I would use `for _ in it: pass` which is already very fast.   If the situation called for an optimization (which it rarely does), then `deque(it, maxlen=0)` would be unbeatable.  

FWIW, the itertools recipes in the docs are mirrored in more-itertools package as `consume()`. It is just a thin wrapper around the `deque` call shown above.  Periodically run a code search on these.  The `consume()` wrapper is rarely used in practice, possibly because functional programming values tooling that is free of side-effects.
