### ISSUE TITLE
[typing: PEP 646]: `*tuple[int, int]` is improperly evaluated by `get_type_hints`

### ISSUE THREAD

**Issue by hjalmarlucius** [python/cpython#101015]
# Bug report

Unpack information of `typing.GenericAlias` is not transferred from string annotations to interpreted annotations. `typing.Unpacked` works as expected.

A fix could be to add `if getattr(t, "__unpacked__", False): return next(iter(GenericAlias(t.__origin__, ev_args)))` clause here:
https://github.com/python/cpython/blob/6492492ce7844bf1193ff748be8c09e301b12cee/Lib/typing.py#L373-L374

NOTE: This bug is in typing's internal API and I don't think there's issues in the public API (but haven't looked hard). However, this issue pops up quickly if you try to do anything wrt PEP 646 typing at runtime.

## Minimal example

```py
from typing import ForwardRef
from typing import TypeVarTuple

Ts = TypeVarTuple("Ts")
typ = ForwardRef("*Ts")._evaluate({}, {"Ts": Ts}, frozenset())
assert typ == next(iter(Ts))  # <-- PASSES AS EXPECTED

typ = ForwardRef("*tuple[int]")._evaluate({}, {}, frozenset())
assert typ == tuple[int]  # <-- PASSES BUT SHOULDN'T
assert typ == next(iter(tuple[int]))  # <-- SHOULD PASS BUT DOESN'T
```

# Your environment

Python 3.11

### Linked PRs
* gh-101031
* gh-101254

**Comment by sobolevn** [comment]
It happens because of this line: https://github.com/python/cpython/blob/ef633e5000222a3dba74473c49d6a81fca0a44ec/Lib/typing.py#L827-L831

Moreover, it is not ever tested 😒 
If I delete this line all tests pass.

Moreover, it has different semantic for `*tuple[int, str]` and `*Ts`, as you have shown.
This happens because `TypeVarTuple` automatically adds `Unpack` here: https://github.com/python/cpython/blob/ef633e5000222a3dba74473c49d6a81fca0a44ec/Lib/typing.py#L1056-L1057

I've sent a proposal with the fix, but I am not 100% happy with it. Please, share your feedback!

**Comment by AlexWaygood** [comment]
Can somebody provide an example of the bug that doesn't use private APIs such as `typing._eval_type` or `ForwardRef._evaluate`?

**Comment by sobolevn** [comment]
See my PR: 

```python
def test_get_type_hints_on_unpack_args(self):
        Ts = TypeVarTuple('Ts')

        def func2(*args: '*tuple[int, str]'): pass
        self.assertEqual(gth(func2), {'args': Unpack[tuple[int, str]]})
```

It was `{'args': tuple[int, str]}` before.

**Comment by AlexWaygood** [comment]
Thanks @sobolevn, that's very helpful! Cc. @mrahtz for interest.

**Comment by AlexWaygood** [comment]
The bug is not unique to forward references:

```pycon
>>> import typing
>>> def foo(*args: *tuple[int, int]): ...
>>> foo.__annotations__
{'args': *tuple[int, int]}
>>> typing.get_type_hints(foo)
{'args': tuple[int, int]}
```

**Comment by sobolevn** [comment]
Yes, that's a good catch. My PR does not solve the second problem. Fixing it!

**Comment by sobolevn** [comment]
Now it does. With even more hacks 😒

**Comment by hjalmarlucius** [comment]
I don't have a setup to test changes so going by intuition to simplify the change: If you try only the fix I proposed in `_eval_type` using `next(iter(...))`, are there still errors? `ForwardRef.__forward_value__` comes from `_eval_type` and if the latter returns a correctly unpacked type, it should be necessary to re-apply it and introducing `is_unpack`.

**Comment by sobolevn** [comment]
@hjalmarlucius I've managed to remove new `ForwardRef` flag. However, `next(iter(...))` seems like a very unclear hack :)

I prefer to keep my code with `__unpacked__`.

**Comment by AlexWaygood** [comment]
Thanks @hjalmarlucius for the report, and @sobolevn for the fix!
