### ISSUE TITLE
.sort(keepN=5)

### ISSUE THREAD

**Issue by etahye** [python/cpython#101022]
It's quite easy to iterate over a list and set a variable to hold the largest number, and much lighter than sorting whole list, but keeping 5 largest numbers needs a list of 5 which you append to, sort and slice, but couldn't this be done by the sort function?

**Comment by sweeneyde** [comment]
This is already implemented and lives at in [`heapq.nlargest`](https://docs.python.org/3/library/heapq.html#heapq.nlargest):

```python
>>> from heapq import nlargest
>>> nlargest(2, [1,7,3,6,4])
[7, 6]
```

No need to complicate the sort API for a less-common use-case when the behavior is already implemented elsewhere.

**Comment by etahye** [comment]
How can top 5 products be less-common use-case?

**Comment by etahye** [comment]
I guess if you want to keep 900 000 best ones you still need to sort the list.
