### ISSUE TITLE
3.11 regression: default arguments in PyEval_EvalCodeEx

### ISSUE THREAD

**Issue by MatthieuDartiailh** [python/cpython#101072]
# Bug report

3.11 Started using `_PyFunction_FromConstructor` inside PyEval_EvalCodeEx. #92173 reported that this caused issues when closures were involved because `_PyFunction_FromConstructor` discarded the closure found in `PyFrameConstructor`. This was fixed in #92175. 

It turns out the same holds true for default arguments and default kw arguments as can be seen at https://github.com/python/cpython/blob/main/Objects/funcobject.c#L90-L91 and is a regression compared to 3.10.

The fix appears fairly simple but I would love to have some guidance as to where to add a test for it.

# Your environment

- CPython versions tested on: 3.11.0
- Operating system and architecture: Windows x86-64

### Linked PRs
* gh-101127
* gh-101636

**Comment by MatthieuDartiailh** [comment]
@larryhastings This may be of interest since you authored #92175

**Comment by carljm** [comment]
The only usage of `PyEval_EvalCodeEx` within CPython is via builtin `exec`, which would never use these fields.

So the only context in which the regression matters is external use of `PyEval_EvalCodeEx` as part of the C API. So I suggest the test should go into `test_capi.py` (probably requiring a custom C test function in `Modules/_testcapimodule.c`).

**Comment by MatthieuDartiailh** [comment]
This can now be closed I believe.
