### ISSUE TITLE
`utcfromtimetuple` is mentioned in documentation, which isn't a thing. The 'from' part is erroneous

### ISSUE THREAD

**Issue by PrefixCoder** [python/cpython#101041]
# Documentation

In datetime module documentation [here](https://docs.python.org/3/library/datetime.html#datetime.datetime.utctimetuple)
in "Warning" block instead of `utctimetuple` there's `utcfromtimetuple`.

### Linked PRs
* gh-101042
* gh-101175
* gh-101176

**Comment by hauntsaninja** [comment]
Thanks all!
