### ISSUE TITLE
Potential memory leak in Objects/bytesobject.c

### ISSUE THREAD

**Issue by RuiliF** [python/cpython#101056]
# Bug report
https://github.com/python/cpython/blob/206f05a46b426eb374f724f8e7cd42f2f9643bb8/Objects/bytesobject.c#L429-L443
At line 438, object `p` won't be freed if `_PyBytesWriter_Prepare` fails (returns NULL) and thus become a memory leak.

### Linked PRs
* gh-101057
* gh-101076
* gh-101077

**Comment by sobolevn** [comment]
Good catch! @RuiliF thanks a lot!

How do you detect it? Do you use some kind of tooling? Or just by hand? :)

**Comment by RuiliF** [comment]
> Good catch! @RuiliF thanks a lot!
> 
> How do you detect it? Do you use some kind of tooling? Or just by hand? :)

Thank you for the quick response! I found it just by hand. :)

**Comment by sobolevn** [comment]
If you have others to report - you are more than welcome! 👍

**Comment by sobolevn** [comment]
Done!
