### ISSUE TITLE
Tkinter ::: Radiobutton class is not working properly based on type of value supplied to it

### ISSUE THREAD

**Issue by sangram11** [python/cpython#101005]
In Tkinter package Radiobutton is not working properly. It is showing different behavior based on different type of value selected for a given variable.

```py
from tkinter import *

root = Tk()
root.geometry("300x300")

gender = StringVar() #gender variable is set as string type
male = Radiobutton(root, text = "Male", variable = gender, value = "male")
female = Radiobutton(root, text = "Female", variable = gender, value = "female")

male.pack()
female.pack()

root.mainloop()
```

<img width="229" alt="image" src="https://user-images.githubusercontent.com/13137186/212252387-2fbb20af-d349-43b0-a598-b3154f0c823c.png">

If you run this simple piece of code, you will find all radio buttons are selected. 
This is happening because **gender variable** is set as **string type**.
A user obviously doesn't want all radio buttons to be selected.

Whereas if you run this below piece of code for integer type

```py
from tkinter import *

root = Tk()
root.geometry("300x300")

gender = IntVar() #gender variable is set as integer type
male = Radiobutton(root, text = "Male", variable = gender, value = 1)
female = Radiobutton(root, text = "Female", variable = gender, value = 2)

male.pack()
female.pack()

root.mainloop()
```

<img width="227" alt="image" src="https://user-images.githubusercontent.com/13137186/212252599-e268b77e-0128-4295-9f46-3d3965ede9ed.png">

You will find none of the option has been selected for radio buttons. This is the actual expectation for any user. They don't want all radio buttons to be selected.

Moreover, there should be an argument in Radiobutton class to select a particular radio button out of many. This is missing.

**Comment by serhiy-storchaka** [comment]
The equivalent Tcl/Tk code:
```tcl
wm geometry . 300x300
set var {}
radiobutton .rb1 -text Male -variable var -value male
radiobutton .rb2 -text Female -variable var -value female
pack .rb1 .rb2
```
and
```
wm geometry . 300x300
set var 0
radiobutton .rb1 -text Male -variable var -value 1
radiobutton .rb2 -text Female -variable var -value 2
pack .rb1 .rb2
```
has the same behavior, so this is not Python issue.

It only happens when you initialize the variable with an empty value. Note that both radiobuttons are not selected in this case, they are in third state (usually it is only possible when you use the `tristatevalue` option). It is some Tk quirk. This is not the place to discuss it.
