### ISSUE TITLE
Python have issues when the user account have accents

### ISSUE THREAD

**Issue by Plaston** [python/cpython#101059]
I have tried to run Stable diffusion but windows can't find python because it replace the ë of my user name with a Ù and give a exit 3.

Creating venv in directory G:\Furry AI\stable-diffusion-webui\venv using python 

"C:\Users\RaphaÙl\AppData\Local\Programs\Python\Python310\python.exe"

Unable to create venv in directory "G:\Furry AI\stable-diffusion-webui\venv"

exit code: 3

stderr:
Le chemin d'accès spécifié est introuvable. ( it means in french The specified path was not found. )

Launch unsuccessful. Exiting.

**Comment by ericvsmith** [comment]
Please copy and paste exactly what you typed into the shell. Was it cmd.exe? Powershell? Something else?

**Comment by eryksun** [comment]
This is a third-party bug in Stable Diffusion web UI. Its [webui.bat](https://github.com/AUTOMATIC1111/stable-diffusion-webui/blob/205991df7826429e6183fc4afbbda3d321c9fee4/webui.bat#L21-L26) batch script uses a `for /f` loop to read the output of `python -c "import sys; print(sys.executable)"`. It needs to temporarily set the console code page to UTF-8 via `chcp.com 65001`[^1]. (Also, it shouldn't use `CALL` when running "python.exe".) For example, here are a couple snippets from Python's "activate.bat" script that temporarily modify and then restore the console code page.

https://github.com/python/cpython/blob/5e9df888dd5ab0e59d1cebc30c998a17aa65a3e2/Lib/venv/scripts/nt/activate.bat#L3-L9

https://github.com/python/cpython/blob/5e9df888dd5ab0e59d1cebc30c998a17aa65a3e2/Lib/venv/scripts/nt/activate.bat#L30-L34

[^1]: The CMD shell uses the active console code page as a locale encoding when it decodes each line of a batch script or reads from a pipe such as in a `for /f` loop. This behavior is straight out of MS-DOS in the 1980s, back when the internal `CHCP` and `MODE` commands of MS-DOS were actually connected to the active locale encoding in the kernel, as well as the drivers for keyboards, displays, and printers. None of that is the case for a Windows console session, but CMD has to remain compatible with old batch scripts and old batch programmers.

**Comment by Plaston** [comment]
> 

I get the same error with pip 

C:\Users\Raphaël>pip3 install bs4
Fatal error in launcher: Unable to create process using '"C:\Users\RaphaÙl\AppData\Local\Programs\Python\Python310\python.exe"  "C:\python\Scripts\pip3.exe" install bs4': Le fichier spÚcifiÚ est introuvable.

**Comment by Plaston** [comment]
> Please copy and paste exactly what you typed into the shell. Was it cmd.exe? Powershell? Something else?

i clicked on the web ui bat file here his code;
@echo off

if not defined PYTHON (set PYTHON=python)
if not defined VENV_DIR (set VENV_DIR=%~dp0%venv)

set ERROR_REPORTING=FALSE

mkdir tmp 2>NUL

%PYTHON% -c "" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :start_venv
echo Couldn't launch python
goto :show_stdout_stderr

:start_venv
if ["%VENV_DIR%"] == ["-"] goto :skip_venv

dir "%VENV_DIR%\Scripts\Python.exe" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv

for /f "delims=" %%i in ('CALL %PYTHON% -c "import sys; print(sys.executable)"') do set PYTHON_FULLNAME="%%i"
echo Creating venv in directory %VENV_DIR% using python %PYTHON_FULLNAME%
%PYTHON_FULLNAME% -m venv "%VENV_DIR%" >tmp/stdout.txt 2>tmp/stderr.txt
if %ERRORLEVEL% == 0 goto :activate_venv
echo Unable to create venv in directory "%VENV_DIR%"
goto :show_stdout_stderr

:activate_venv
set PYTHON="%VENV_DIR%\Scripts\Python.exe"
echo venv %PYTHON%
if [%ACCELERATE%] == ["True"] goto :accelerate
goto :launch

:skip_venv

:accelerate
echo "Checking for accelerate"
set ACCELERATE="%VENV_DIR%\Scripts\accelerate.exe"
if EXIST %ACCELERATE% goto :accelerate_launch

:launch
%PYTHON% launch.py %*
pause
exit /b

:accelerate_launch
echo "Accelerating"
%ACCELERATE% launch --num_cpu_threads_per_process=6 launch.py
pause
exit /b

:show_stdout_stderr

echo.
echo exit code: %errorlevel%

for /f %%i in ("tmp\stdout.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stdout:
type tmp\stdout.txt

:show_stderr
for /f %%i in ("tmp\stderr.txt") do set size=%%~zi
if %size% equ 0 goto :show_stderr
echo.
echo stderr:
type tmp\stderr.txt

:endofscript

echo.
echo Launch unsuccessful. Exiting.
pause

**Comment by Plaston** [comment]
> 

Now ints kinda working because i installed it on c:/Python but it crash when pip is involved because it install by default on the user folder.

**Comment by zware** [comment]
As pointed out, this is not a problem with Python.  If you follow the link @eryksun posted you should be able to find the correct place to report this issue.

**Comment by eryksun** [comment]
I forgot to mention that Python also has to be forced to use UTF-8. By default, Python uses the system ANSI code page when opening a pipe file in text mode. This is likely a legacy code page such as 1252. To force standard I/O to use UTF-8, one can set the environment variable `PYTHONIOENCODING` to "UTF-8". Alternatively, starting with Python 3.7, the command-line option `-X utf8` enables UTF-8 mode as the default text I/O encoding, or set the environment variable `PYTHONUTF8` to "1".
