### ISSUE TITLE
Add os.path.splitroot() function

### ISSUE THREAD

**Issue by barneygale** [python/cpython#101000]
# Feature or enhancement

Add a function that splits a path into a `(drive, root, tail)` triad:

1. The _drive_ part has the same meaning as in `splitdrive()`
2. The _root_ part is one of: the empty string, a forward slash, a backward slash (Windows only), or two forward slashes (POSIX only)
3. The _tail_ part is everything following the root.

Similarly to `splitdrive()`, a `splitroot()` function would ensure that `drive + root + tail` is the same as the input path.

# Pitch
The extra level of detail reflects an extra step in the Windows 'current path' hierarchy -- Windows has both a 'current drive', and a 'current directory' for one or more drives, which results in several kinds of non-absolute paths, e.g. 'foo/bar',  '/foo/bar', 'X:foo/bar'

This three-part model is used successfully by pathlib, which exposes _root_ as an attribute, and combines `drive + root` as an attribute called _anchor_. The anchor has useful properties, e.g. comparing two paths anchors can tell us whether a `relative_to()` operation is possible.

Pathlib has [its own implementation of `splitroot()`](https://github.com/python/cpython/blob/08e5594cf3d42391a48e0311f6b9393ec2e00e1e/Lib/pathlib.py#L274-L285), but its performance is hamstrung by its need for OS-agnosticism. By moving the implementation into `ntpath` and `posixpath` we can take advantage of OS-specific rules to improve pathlib performance. 

# Previous discussion

- https://discuss.python.org/t/add-os-path-splitroot/22243
- https://github.com/python/cpython/pull/31691/files#r944987609
- https://github.com/python/cpython/pull/100351/files/5b67a7489e5518975d0c11033cd35bf60fad0ddf#r1065219273

### Linked PRs
* gh-101002

**Comment by AlexWaygood** [comment]
Added in #101002. Thanks @barneygale 🎉🥳

**Comment by barneygale** [comment]
Thank you very much Alex! \o/
