### ISSUE TITLE
Not great text flow

### ISSUE THREAD

**Issue by minerop5000** [python/cpython#101087]
# Text flow

[Link to File](https://github.com/python/cpython/blob/a3510c3a4e7922987e083dffc19ecd93c85d153b/Doc/library/copy.rst)

"; and" at the end of an enumeration interferes with text flow.

eg: 
```
The deepcopy() function avoids these problems by:
  -  keeping a memo dictionary of objects already copied during the current copying pass; and
  -  letting user-defined classes override the copying operation or the set of components copied.
```

### Linked PRs
* gh-101088

**Comment by slateny** [comment]
I do believe that it's properly styled right now (take a look at [this style guide](https://apastyle.apa.org/style-grammar-guidelines/lists/bulleted) under the "Items that are words or phrases" section).

**Comment by AlexWaygood** [comment]
> I do believe that it's properly styled right now (take a look at [this style guide](https://apastyle.apa.org/style-grammar-guidelines/lists/bulleted) under the "Items that are words or phrases" section).

Indeed, this is a common idiom that I've often seen elsewhere.
