### ISSUE TITLE
Typo in python random.random documentation

### ISSUE THREAD

**Issue by sherpaurgen** [python/cpython#101097]
There is a typo in documentation [here](https://docs.python.org/3/library/random.html#random.random) regarding random.random()
`the next random floating point number in the range [0.0, 1.0).` 

It can be corrected by replacing ")" with "]"

### Linked PRs
* gh-101119
* gh-101246

**Comment by hugovk** [comment]
This isn't a typo, the opening square bracket `[` means 0.0 is included.

And the closing round bracket `)` means that 1.0 is excluded.

So the random number is >= 0.0 but < 1.0.

https://stackoverflow.com/a/4396303/724176

**Comment by kumaraditya303** [comment]
It is using standard interval notation.

**Comment by rhettinger** [comment]
This has come up before.  Apparently, the interval notation is not universally known and recognized.   I will switch the `0.0 <= X < 1.0` which communicates the same information but without the notation that is cryptic to at least some readers.

**Comment by hugovk** [comment]
There's a few more we could change, at least those in docs:

```console
$ git grep "\[[0-9.]*, [0-9.]*)"
Doc/faq/library.rst:This returns a random floating point number in the range [0, 1).
Doc/howto/functional.rst:    >>> # Generate 8 random numbers between [0, 10000)
Doc/library/random.rst:generates a random float uniformly in the semi-open range [0.0, 1.0).  Python
Doc/library/random.rst:   Return the next random floating point number in the range [0.0, 1.0).
Include/bytearrayobject.h: * the bytes are mapped to ints in [0, 256).
Lib/random.py:        # When x and y are two variables from [0, 1), uniformly
Lib/random.py:        """Get the next random number in the range [0.0, 1.0)."""
Lib/test/sortperf.py:    """Return a list of n random floats in [0, 1)."""
Modules/_randommodule.c:random() -> x in the interval [0, 1).
Modules/clinic/_randommodule.c.h:"random() -> x in the interval [0, 1).");
Objects/floatobject.c:        /* Normalize f to be in the range [1.0, 2.0) */
Objects/floatobject.c:        /* Normalize f to be in the range [1.0, 2.0) */
Objects/floatobject.c:        /* Normalize f to be in the range [1.0, 2.0) */
Python/dtoa.c:     * a number in the range [0.1, 1). */
```
