### ISSUE TITLE
Jackson Style Discriminators Should allow Derived Class Deserialization with Late Binding

### ISSUE THREAD

**Issue by Maniatty** [python/cpython#101198]
# Feature or enhancement

In other languages/tool systems, (e.g. Java with the JacksonSubptype) support deserializing a base class from json, to the appropriate derived class using a type discriminator.  For interoperability with code that uses type discriminators in request/response apis, it would be convenient if that was supported, in python I have a preliminary approach that does this, with the conversion from dict->instance (i.e. BaseClass.as_dict())
# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

# Previous discussion

**Comment by rhettinger** [comment]
Please take this to python-ideas for discussion and development. Would you leverage the existing reducer methods,  `__reduce__` and `__getstate__`.  What security provisions would be provided? Is there an expectation that builtin classes would be changed or would "type discriminators" be created by users to fit a particular API.  

As written now, the the proposal is too vague to be actionable?  Please take it to a forum to be thought out and fleshed out.
