### ISSUE TITLE
New deprecation warning in some tests due to a new decorator in test.support

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#101167]
DeprecationWarning: It is deprecated to return a value that is not None from a test case (<bound method _id of <test.test_dis.DisTests testMethod=test_binary_specialize>>)

Shows up in test_dis, test_compile and test_embed, for tests that use the new @requires_specialization which was added in https://github.com/python/cpython/pull/100713.

I don't know why this decorator does this while requires_limited_api doesn't.

### Linked PRs
* gh-101171

**Comment by zware** [comment]
At https://github.com/python/cpython/blob/8a2d4f4e8eea86352de37d2ce28117e13b3dfaed/Lib/test/support/__init__.py#L1081-L1082

line 1082 should end with `(test)`.  As is, any test decorated with that decorator is disabled completely; the test is set to the `skipUnless` decorator, not the decorated test.

**Comment by iritkatriel** [comment]
Ah yes, thanks. Are you making a PR or shall I?

**Comment by zware** [comment]
All yours :)

**Comment by iritkatriel** [comment]
It's a good deprecation warning!
