### ISSUE TITLE
collections.abc.MutableSet __iand__ method does not work for some user defined classes inherited from MutableSet

### ISSUE THREAD

**Issue by TonilK** [python/cpython#101195]
# Bug report

Call for **\_\_iand\_\_** method raises an exception if user defined class that inherits from collection.abc.MutableSet has an additional arguments in its **\_\_init\_\_** function. 

## Example:
```python
  from collections.abc import MutableSet
  
  class FooSet(MutableSet):
      def __init__(self,name, values) -> None:
          self._name = name
          self._items = set([v for v in values])
  
      def __str__(self) -> str:
          return f"Foo object {self.name}. items:{self._items}"
      
      def __repr__(self) -> str:
          return f"Foo object {self.name}. items:{self._items}"
  
      def __iter__(self):
          return iter(self._items)
      
      def __contains__(self, value)->bool:
          return value in self._items
  
      def __len__(self)->int:
          return len(self._items)
      
      @property
      def name(self):
          return self._name
  
      def add(self, item):
          self._items.add(item)
      
      def discard(self, item):
          self._items.discard(item)
  
  foo_inter = FooSet('foo1',range(1,5))
  foo_union = FooSet('foo1',range(1,5))
  foo_diff  = FooSet('foo1',range(1,5))
  foo_symm_diff  = FooSet('foo1',range(1,5))
  
  foo2 = FooSet('foo2',range(3,7))
  print(foo2)
  
  print(f'Union {foo_union} and {foo2}')
  foo_union |= foo2
  print(foo_union)
  
  print(f'Intersection {foo_inter} and {foo2}')
  foo_inter &= foo2
  print(foo_inter)
  
  print(f'Diffrence {foo_diff} and {foo2}')
  foo_diff -= foo2
  print(foo_diff)
  
  print(f'Symm_diff {foo_symm_diff} and {foo2}')
  foo_symm_diff ^= foo2
  print(foo_symm_diff)
```

### Terminal output

```python
> Foo object foo2. items:{3, 4, 5, 6}
> Union Foo object foo1. items:{1, 2, 3, 4} and Foo object foo2. items:{3, 4, 5, 6}
> Foo object foo1. items:{1, 2, 3, 4, 5, 6}
> Intersection Foo object foo1. items:{1, 2, 3, 4} and Foo object foo2. items:{3, 4, 5, 6}
> Traceback (most recent call last):
>   File "footest.py", line 48, in <module>
>     foo_inter &= foo2
>   File "frozen _collections_abc", line 723, in **\_\_iand\_\_**
>   File "frozen _collections_abc", line 612, in **\_\_sub\_\_**
>   File "frozen _collections_abc", line 583, in **\_from\_iterable\_**
> TypeError: FooSet.\_\_init\_\_() missing 1 required positional argument: 'values'
```

### My environment
Windows 11, Vscode 1.74.3, Python 3.11.1 64-bit,

## The problem
Error happens in the **\_\_iand\_\_** function that unlike **\_\_ior\_\_** and others actually creates a new object inside instead of updating owner object itself. 
### problem code in **\Python311\Lib\_collections_abc.py**
At the second line (self-it) creates a new object Foo without passing all necessary arguments
```python
    def __iand__(self, it):
        for value in (self - it):
            self.discard(value)
        return self
```
### Fix suggestion
```python
    def __iand__(self, it):
        values_to_discard = set([v for v in self if v not in it])
        for value in values_to_discard:
            self.discard(value)
        return self
```

### Linked PRs
* gh-101218

**Comment by rhettinger** [comment]
See the footnote the [collections.abc docs](https://docs.python.org/3/library/collections.abc.html):

> Since some set operations create new sets, the default mixin methods need a way to create new instances from an iterable. The class constructor is assumed to have a signature in the form ClassName(iterable). That assumption is factored-out to an internal classmethod called _from_iterable() which calls cls(iterable) to produce a new set. If the Set mixin is being used in a class with a different constructor signature, you will need to override _from_iterable() with a classmethod or regular method that can construct new instances from an iterable argument.

To get your class to work correctly, add this method:

      def _from_iterable(self, it):
          return type(self)(self.name, it)

After that change, of the following operations that currently fail will succeed.

>>> p = FooSet('p', range(1, 5))
>>> q = FooSet('q', range(3, 7))
>>> p & q
Foo object p. items:{3, 4}
>>> p | q
Foo object p. items:{1, 2, 3, 4, 5, 6}
>>> p - q
Foo object p. items:{1, 2}
>>> p ^ q
Foo object p. items:{1, 2, 5, 6}
>>> p &= q
>>> p
Foo object p. items:{3, 4}

**Comment by TonilK** [comment]
Damn, for a moment I thought I was more clever than the python developers.
Thanks for the explanation. Perhaps it would help to avoid similar mistakes in the future if you could move these notes closer to the Set/Mutable Set documentation. 

Just curious, but what is the idea behind this approach? I don't really understand why not just avoid creating new objects at least in unary operators. It seems to me that it could simplify the use of collection classes and make their operators even faster without creating new objects.
