### ISSUE TITLE
asyncio.base_events.BaseEventLoop._add_callback references TimerHandle but never uses them

### ISSUE THREAD

**Issue by bdraco** [python/cpython#101143]
# Bug report

After 592ada9b4b08ad57037e365b9c462d71c96e4453 it appears this function not longer cares about `self._scheduled` or `TimerHandle` but the docstring seems to imply otherwise

# Your environment

- CPython versions tested on: 3.12.0a4
- Operating system and architecture: MacOS

I only noticed because it was unexpectedly more expensive

![unexpectedly_more_expensive](https://user-images.githubusercontent.com/663432/213334471-69b726e6-df40-4932-91f9-58582830727c.png)

I think its dead code and can be simplified to:

```diff
diff --git a/Lib/asyncio/base_events.py b/Lib/asyncio/base_events.py
index cbabb43ae0..070ea1044d 100644
--- a/Lib/asyncio/base_events.py
+++ b/Lib/asyncio/base_events.py
@@ -1857,11 +1857,9 @@ def call_exception_handler(self, context):
                                  exc_info=True)
 
     def _add_callback(self, handle):
-        """Add a Handle to _scheduled (TimerHandle) or _ready."""
+        """Add a Handle to _ready."""
         assert isinstance(handle, events.Handle), 'A Handle is required here'
-        if handle._cancelled:
-            return
-        assert not isinstance(handle, events.TimerHandle)
+        if not handle._cancelled:
             self._ready.append(handle)
 
     def _add_callback_signalsafe(self, handle):
```

### Linked PRs
* gh-101197
* gh-101216
* gh-101217

**Comment by gvanrossum** [comment]
You might as well submit a PR, we can review then.

**Comment by bdraco** [comment]
Pushed that suggested change to a few more production machines to be sure.  Still kinda surprising how much run time it has but I guess thats what happens when you call it ~10000 time a minute.

![mod](https://user-images.githubusercontent.com/663432/213800252-1e44a91d-1438-489e-a387-36624f0ad858.png)

Will send a PR soon

**Comment by bdraco** [comment]
Updated callgrind after https://github.com/python/cpython/pull/101197#discussion_r1083055587


![post_review](https://user-images.githubusercontent.com/663432/213809620-ec844be4-1f90-4363-9314-5f707276d23b.png)
