### ISSUE TITLE
`optparse` -> information about `store_const` is a bit vague

### ISSUE THREAD

**Issue by jugmac00** [python/cpython#101111]
# Documentation

For context - new `optparse` user here.

After I have seen `store_const` in our code base, I had a bit of a hard time to figure out the difference between `store`  and `store_const`.

The [Other actions](https://docs.python.org/3/library/optparse.html#other-actions) section just mentions.

> store const -> store a constant value

I would like to add a link to https://docs.python.org/3/library/optparse.html#optparse.Option.const and mention that the constant value is not provided by the user, but needs to be set beforehand.

Would a pull request with theses changes be accepted?

### Linked PRs
* gh-101121
* gh-101203
* gh-101204

**Comment by rhettinger** [comment]
> Would a pull request with theses changes be accepted?

Yes. Please assign the PR to me for review.

**Comment by jugmac00** [comment]
Thanks! I had a look around the documentation for `optparse`, and I found two more spots which would benefit by linking to `Option.const`.

**Comment by jugmac00** [comment]
> Please assign the PR to me for review.

@rhettinger: Unfortunately, it seems I do not have sufficient permissions to do this.

@hugovk We are almost in the same time zone, maybe you could assign Raymond? Thank you!

**Comment by hugovk** [comment]
Done!

**Comment by hauntsaninja** [comment]
Thank you!
