### ISSUE TITLE
pathlib.Path.is_relative_to: document behavior when passing multiple paths

### ISSUE THREAD

**Issue by vect-tmazzucotelli** [python/cpython#101130]
# Documentation

In the documentation of [`pathlib.Path.is_relative_to(*other)`](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.is_relative_to), it is not explained what happens when passing multiple `other` paths. When reading the docs, I thought passing multiple paths would return `True` if the main path is relative to **one of** the given other paths (probably because that's I wanted it to do :sweat_smile:). But it rather seems to return `True` only if it is relative to **all** given paths.

```pycon
>>> from pathlib import Path
>>> Path("/a/b").is_relative_to("/a", "/b")
False
```

I see that [passing multiple paths will be deprecated in 3.12 and removed in 3.14](https://github.com/python/cpython/commit/5a991da32961ef5780996d58b8816d5f2085f540) anyway, but in the meantime it would be nice to document the behavior :slightly_smiling_face: Not sure if docs can be backported though, so maybe that's not useful at all. In that case, feel free to close!

### Linked PRs
* gh-114034

**Comment by barneygale** [comment]
Thanks for reporting! I've added a couple of sentences to the 3.11 docs. The >=3.12 docs already mention it in the deprecation notice, and the <=3.10 docs are out of support.
