### ISSUE TITLE
Raising Exception objects from assert

### ISSUE THREAD

**Issue by novitae** [python/cpython#101133]
# Feature or enhancement
When using the function `assert`, we can only raise `AssertionError`, containing the custom string placed or not, as following:
```py
>>> assert False
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError
>>> assert False, "it's false"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AssertionError: it's false
```
The feature I am requesting is to raise a custom exception instead of an `AssertionError` one, as it could look like:
```py
>>> assert False, ValueError("must be true")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: must be true
```

# Pitch
It would be a great enhancement allowing to compact by a lot custom exception raising. In fact, some people are actually doing it like this:
```py
try:
    assert False, "A Message"
except AssertionError, e:
    raise Exception( e.args )
```
And would allow them to do it like this:
```py
assert False, Exception("A Message")
```

**Comment by ronaldoussoren** [comment]
You can use ```if not EXPR: raise Exception(...)```, which doesn't take more space and has the advantage of working in optimised mode (``python -O``). 

This has been proposed and rejected before (one example proposal is [here](https://mail.python.org/pipermail/python-ideas/2016-May/040033.html)).  Adding this feature at least requires a better pitch, please start a discussion about this on discuss.python.org to gather feedback.

**Comment by AlexWaygood** [comment]
> Adding this feature at least requires a better pitch, please start a discussion about this on discuss.python.org to gather feedback.

Agreed, a change of this magnitude definitely needs discussion on discuss.python.org before we can consider it here. If there is significant support for your proposal there, we can reconsider, but for now I'm closing this issue.
