### ISSUE TITLE
Documentation of idlelib

### ISSUE THREAD

**Issue by zachyboy12** [python/cpython#101154]
Hi,

I am trying to use idlelib for a code editor in tkinter, but I can’t becuse idlelib is under documented.
Can you please update the docs?

Thanks!

**Comment by zware** [comment]
`idlelib` is a private implementation detail of the IDLE editor.  It will not be documented and you use it at your own risk, meaning that if something changes that breaks your project, we will not consider it a bug in `idlelib` unless it also affects IDLE itself.  It is even allowed by PEP-434 to change in bugfix versions of Python.
