### ISSUE TITLE
Need a inbuilt datatype for Table 

### ISSUE THREAD

**Issue by ANVLISTENER** [python/cpython#101147]
# Feature or enhancement

In the real world, we have lot situations where we have to present data in tables and process them using objects. 

# Pitch

We request you to present a new data type where the python auto present the table. As we can't, all time depend on external packages, we really humbly request you to have support for them. 

We had PowerShell table in hashtbable object which to be parsed into the json and again taken back as hash and again present as table in console using the addn. external packages which is not advisable at all times. The same can be taken to represent a neuron/ highly complicated system like tree which needs a inbuild new data type type to be built for complicated tasks.

**Comment by ajoino** [comment]
What kind of table do you need?

A table could, e.g., be a tuple of tuples:
```python
table = (
   (1, 3.14, "foo"),
   (10, 5.4, "bar"),
)

table[0][0] # 1
table[1,2] # "bar"
```

if you want columns with labels, you can use a dict:
```python
table_column_wise = {
    label: column for label, column 
    in zip(("calls", "input", "function"), zip(*table))
}

table_column_wise["calls"][1] # 10
```

I'm sure there are other ways as well, and I would recommend you to use 3rd party libraries if you want to do more advanced tasks.

**Comment by rhettinger** [comment]
I suggest creating a new thread on python-ideas to discuss and develop the proposal.  As presented here, it is too vague and has too little buy-in to be actionable.
