### ISSUE TITLE
A small typo in Tutorial documentation

### ISSUE THREAD

**Issue by Roshan310** [python/cpython#101134]
# Documentation

(A clear and concise description of the issue.)
On topic 6.1.1 of the Tutorial page, the line reads, "If the module is imported, the code is not run". Instead, it should have been "If the module is imported, the code will not run". This might confuse some beginners as to what this line exactly means.

**Comment by ericvsmith** [comment]
I always think of the interpreter running the code, so it makes sense to me as-is.

**Comment by Roshan310** [comment]
Ok! Thank you for the review

**Comment by Roshan310** [comment]
Got it
