### ISSUE TITLE
some files in PCbuild have no newline at EOF

### ISSUE THREAD

**Issue by th1722** [python/cpython#101149]
Some files in PCbuild have no newline at EOF.

![image](https://user-images.githubusercontent.com/86101306/213910270-dec418f1-6a87-42f8-99a1-5330f9184ec4.png)

test environment: 
- CPython versions tested on: 3.7.16, 3.8.16, 3.9.16, 3.10.9, 3.11.1, 3.12a4
- Operating system and architecture: Ubuntu 22.10 kinetic (amd64)

### Linked PRs
* gh-101240

**Comment by arhadthedev** [comment]
It seems Visual Studio gives no switch to save projects with trailing newlines right away. Thus, can we expect all contributors to manually edit project files in a text editor after changing them in the IDE?

**Comment by th1722** [comment]
> It seems Visual Studio gives no switch to save projects with trailing newlines right away. Thus, can we expect all contributors to manually edit project files in a text editor after changing them in the IDE?

I created this issue to make a pull request to add a newline to EOF. so I don't expect or force contributors to do that.
I apologize for misleading you.

**Comment by th1722** [comment]
> It seems Visual Studio gives no switch to save projects with trailing newlines right away. Thus, can we expect all contributors to manually edit project files in a text editor after changing them in the IDE?

I created this issue to make a pull request to add a newline to EOF. so I don't intend to expect or force contributors to do that.
I apologize for misleading you.

**Comment by fochoao** [comment]
It is annoying but it always makes a newline at the end. It is merely Visual Studio, while I work on DjAngo projects I get this issue a lot.

**Comment by erlend-aasland** [comment]
Thanks for your interest in improving CPython, but please leave those files as they are.
