### ISSUE TITLE
Ambiguity in description of `random.choices`

### ISSUE THREAD

**Issue by treylav** [python/cpython#101128]
Hello.

There is a phrase in the [documentation for `random.choices`](https://docs.python.org/3.12/library/random.html#random.choices):

> If a weights sequence is specified, selections are made according to the relative weights. Alternatively, if a cum_weights sequence is given, the selections are made according to the cumulative weights **(perhaps computed using `itertools.accumulate()`)**. For example, the relative weights [10, 5, 30, 5] are equivalent to the cumulative weights [10, 15, 45, 50]. Internally, the relative weights are converted to cumulative weights before making selections, so supplying the cumulative weights saves work.

I assume that the original order of the phrase was intended like this:
> If a weights sequence is specified, selections are made according to the relative weights. Alternatively, if a cum_weights sequence is given **(perhaps computed using `itertools.accumulate()`)**, the selections are made according to the cumulative weights.

My assumption is based on two facts:
1. `itertools.accumulate()` can be used to calculate cumulative weights: examples of relative weights `[10, 5, 30, 5]` do convert by it to cumulative weights as `[10, 15, 45, 50]`;
2. there is no uncertainty in the process of converting the cum_weights argument, we know for sure the answer whether `itertools.accumulate()` is used or not, based on the CPython source code.

Maybe I missed something?  

Thanks in advance.

### Linked PRs
* gh-101129

**Comment by rhettinger** [comment]
The wording is correct as-is.  If a user wants to build cumulative weights outside of the function, we're suggesting that `accumulate()` is a possible way to do so.

Internally, we happen to use the same approach, but that is a irrelevant implementation detail that we don't document.
