### ISSUE TITLE
New warning on GitHub: "unused variable ‘runtime’ in `pystate.c`"

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#101181]
All PRs right now show this warning:
<img width="919" alt="Снимок экрана 2023-01-20 в 10 55 11" src="https://user-images.githubusercontent.com/4660275/213645037-f66d6b42-eca2-4b56-953f-30b514bbc5d7.png">

However, it looks like a false-positive, because `runtime` is clearly used later on:

https://github.com/python/cpython/blob/3fa8fe7177bb941aa60ecaf14d1fa1750a26f674/Python/pystate.c#L1881-L1885

Looks like it has started after https://github.com/python/cpython/commit/6036c3e856f033bf13e929536e7bf127fdd921c9

cc @ericsnowcurrently 

### Linked PRs
* gh-101188

**Comment by kumaraditya303** [comment]
The block needs to be guarded with NDEBUG, want to make a PR for it?

**Comment by sobolevn** [comment]
Working on it.

**Comment by ericsnowcurrently** [comment]
Thanks, @sobolevn!

**Comment by sobolevn** [comment]
Done!
