### ISSUE TITLE
The try statement grammar does not reflect possibility of catching a tuple of exceptions.

### ISSUE THREAD

**Issue by idkos** [python/cpython#101232]
As mentioned in the title [the try statement](https://docs.python.org/3/reference/compound_stmts.html#the-try-statement) grammar:
```
try_stmt  ::=  try1_stmt | try2_stmt | try3_stmt
try1_stmt ::=  "try" ":" suite
               ("except" [expression ["as" identifier]] ":" suite)+
               ["else" ":" suite]
               ["finally" ":" suite]
try2_stmt ::=  "try" ":" suite
               ("except" "*" expression ["as" identifier] ":" suite)+
               ["else" ":" suite]
               ["finally" ":" suite]
try3_stmt ::=  "try" ":" suite
               "finally" ":" suite
```
 does not show that the following is possible:

``` python3
try:
    # code that can throw TypeError, ValueError, MyError or OurError
except (TypeError, ValueError):
    # deal with exception
except (MyError, OurError) as e:
    # deal with exception e
```

Such possibility is mentioned in the first paragraph of the following [except clause section](https://docs.python.org/3/reference/compound_stmts.html#except-clause) and in the [tutorial](https://docs.python.org/3/tutorial/errors.html#handling-exceptions) but the grammar is not there.
Also, 'expression' in the grammar points to [conditional expressions](https://docs.python.org/3/reference/expressions.html#conditional-expressions) which is confusing and seems incorrect. This applies to other 'expression's in the grammars, at least throughout that chapter.

**Comment by thatbirdguythatuknownot** [comment]
It's correct, as `expression` contains the tuple grammar. It's exactly how it looks like in the grammar file.

**Comment by idkos** [comment]
I'm on a 3.12.0a4 version of documentation and ```expression``` takes me from ```try``` statement grammar to [conditional expressions](https://docs.python.org/3.12/reference/expressions.html#conditional-expressions) which are:
```
conditional_expression ::=  or_test ["if" or_test "else" expression]
expression             ::=  conditional_expression | lambda_expr
```
though, part of the URL 'grammar-token-python-grammar-expression' may suggests that it should point somewhere else (to the correct description). I've tried that with different browsers with the same result.

**Comment by thatbirdguythatuknownot** [comment]
> I'm on a 3.12.0a4 version of documentation and `expression` takes me from `try` statement grammar to [conditional expressions](https://docs.python.org/3.12/reference/expressions.html#conditional-expressions) which are:
> 
> ```
> conditional_expression ::=  or_test ["if" or_test "else" expression]
> expression             ::=  conditional_expression | lambda_expr
> ```
> 
> though, part of the URL 'grammar-token-python-grammar-expression' may suggests that it should point somewhere else (to the correct description). I've tried that with different browsers with the same result.

@idkos it takes me to just the part with `expression` in the block, but it *is* in the conditional expressions section.

**Comment by zware** [comment]
As pointed out, the grammar here is already correct.  Syntactically, you can put just about whatever you want in an `except` clause, and it will compile correctly.  Whether it will *behave* as expected is another matter orthogonal to the grammar, and is unknown until runtime.  The grammar doesn't know or care that `except` wants an exception type or tuple thereof, it's just an expression.  If you want confirmation that the grammar allows for tuples there, you can follow the links: `try_stmt` -> `try_stmt1` -> `expression` -> `conditional_expression` -> `or_test` -> `and_test` -> `not_test` -> `comparison` -> `or_expr` -> `xor_expr` -> `and_expr` -> `shift_expr` -> `a_expr` -> `m_expr` -> `u_expr` -> `power` -> `primary` -> `atom` -> `enclosure` -> `parenth_form` -> `starred_expression`, which is where tuple syntax is defined (basically the `(starred_item ",")*` part).

It's complicated, but that's grammar for you.
