### ISSUE TITLE
Enhance the BOLT build process

### ISSUE THREAD

**Issue by corona10** [python/cpython#101282]
From @indygreg 's https://github.com/python/cpython/pull/101093

TODO
- [x] Optional `-fno-reorder-blocks-and-partition`
- [x] Drop  `-gdwarf-4`
- [x] Run BOLT instrumented binary with `$(RUNSHARED)``
- [x] Enable BOLT optimization of libpython

### Linked PRs
* gh-101557
* gh-104493
* gh-104709
* gh-104751
* gh-104752
* gh-104821
* gh-104853

**Comment by corona10** [comment]
cc @aaupov

**Comment by indygreg** [comment]
The remaining 2 tasks in this issue are implemented by gh-104709. Unsure if we want to call this issue done after that or not.

I still have a ton of patches to overhaul the profile-related make rules (gh-104523). But those will have to wait until 3.13.

**Comment by corona10** [comment]
> The remaining 2 tasks in this issue are implemented by https://github.com/python/cpython/pull/104709.

Thanks for the work, let's ship the feature at CPython 3.12 as the experimental feature.

**Comment by erlend-aasland** [comment]
@indygreg, looks like this part can be marked completed.
