### ISSUE TITLE
Isolate the itertools extension module

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#101277]
# Feature or enhancement

Following https://github.com/ericsnowcurrently/multi-core-python/wiki/0-The-Plan we need to convert the `itertools` extension module to use module state.

There are multiple static global type objects:

https://github.com/python/cpython/blob/e244401ce508ad391295beb636e499fcc6797a2a/Tools/c-analyzer/cpython/globals-to-fix.tsv#L338-L359

We need to convert these to heap types, add module state, and implement multi-phase init.

See also PEP-687.

I've got an old PR (#24065) that I'm planning on resurrecting. I'll re-submit it as multiple PRs; this is going to be a large change.

For this particular module, it could make sense to add a module state pointer to each type context, for easy and cheap state access.

### Linked PRs
* gh-101302
* gh-101303
* gh-101304
* gh-101305

**Comment by sobolevn** [comment]
cc @rhettinger as the module owner.

**Comment by erlend-aasland** [comment]
@rhettinger, let me know if you need help understanding the various changes that are needed in order to isolate an extension module, including understanding how to create heap types using the Python C API. I'd be happy to help explaining the fundamental differences between the data structures used and the Python C API's used.
