### ISSUE TITLE
Question about abstract grammar of `Dict`

### ISSUE THREAD

**Issue by harupy** [python/cpython#101211]
# Documentation

The abstract grammar of `Dict` is defined as follows in https://docs.python.org/3/library/ast.html:

```
         | Dict(expr* keys, expr* values)
```

As `keys` contains `None` when a dict literal contains unpacking (e.g. `{"k": "v", **d}`), should this be changed to something like below to indicate `keys` is `List[Expr | None]`?

```
         | Dict(expr?* keys, expr* values)
```

## Example

```python
import ast
import sys

print(sys.version)
print(ast.dump(ast.parse("{'k': 'v', **d}"), indent=2))
```

Ouptut:

```
3.10.8 (main, Nov 24 2022, 14:13:03) [GCC 11.2.0]
Module(
  body=[
    Expr(
      value=Dict(
        keys=[
          Constant(value='k'),
          None],
          👆👆👆
        values=[
          Constant(value='v'),
          Name(id='d', ctx=Load())]))],
  type_ignores=[])
```

**Comment by harupy** [comment]
This is not a big issue https://docs.python.org/3/library/ast.html#ast.Dict explains:

```
When doing dictionary unpacking using dictionary literals the expression to be expanded goes
in the values list, with a None at the corresponding position in keys.
```

**Comment by hauntsaninja** [comment]
Hm, the ASDL you're quoting from is more meant for machines than it is for humans: https://github.com/python/cpython/blob/main/Parser/Python.asdl#L64
and I don't think it support stacking of "extra"s like this

The more human-readable documentation does mention this: https://docs.python.org/3/library/ast.html#ast.Dict

You may also be interested in the typeshed type annotations: https://github.com/python/typeshed/blob/main/stdlib/_ast.pyi#L253

**Comment by harupy** [comment]
@hauntsaninja Thanks for the quick answer!

> the ASDL you're quoting from is more meant for machines than it is for humans

Agreed :)

> You may also be interested in the typeshed type annotations: https://github.com/python/typeshed/blob/main/stdlib/_ast.pyi#L253

Thanks!
