### ISSUE TITLE
inspect.signature returns incorrect result on a @staticmethod and a @classmethod

### ISSUE THREAD

**Issue by heckad** [python/cpython#101293]
# Bug report

```python
import inspect


def test_1():
    class FooStaticmethod:
        @staticmethod
        def __call__(cls, s, l, t):
            return t

    instance = FooStaticmethod()
    instance(1, 2, 3, 4) # Success call with 4 args

    assert list(inspect.signature(instance).parameters.keys()) == ['cls', 's', 'l', 't']


def test_2():
    class FooClassmethod:
        @classmethod
        def __call__(cls, s, l, t):
            return t

    instance = FooClassmethod()
    instance(1, 2, 3) # Success call with 4 args

    assert list(inspect.signature(instance).parameters.keys()) == ['s', 'l', 't']

def test_3():
    class FooStaticmethod:
        @staticmethod
        def __call__():
            return None

    instance = FooStaticmethod()
    instance()

    assert list(inspect.signature(instance).parameters.keys()) == []
```

# Your environment

CPython versions tested on:
- Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
- Python 3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)] on win32

# Possible fix

The problem is that we are calling `_signature_from_callable` twice with `skip_bound_arg=True`. 
A simple solution is to call `_get_signature_of` with `skip_bound_arg=False` on 
https://github.com/python/cpython/blob/f02fa64bf2d03ef7a28650c164e17a5fb5d8543d/Lib/inspect.py#L2610

That fix the `test_2` but not the `test_1`. I need to think about how to do better. I will be glad to your suggestions.

Р.S I would like to submit a pull request. 

### Linked PRs
* gh-102564
* gh-115530
* gh-116197
* gh-116198

**Comment by sobolevn** [comment]
I don't think that `__call__` should ever be `@staticmethod` or `@classmethod`. It is designed to be an instance method. Do you have examples with other methods?

**Comment by heckad** [comment]
It is from pyparsing, [Here is the test suite.](https://github.com/pyparsing/pyparsing/blob/14def7d7f454bfe891589a67801854b12e0b5ed2/tests/test_unit.py#L4257) I want to do [this](https://github.com/pyparsing/pyparsing/pull/462) and  got a bug in inspect module.

Is there a way to find out which descriptor wrapped a method?

**Comment by serhiy-storchaka** [comment]
`__call__()` can be an arbitrary callable or descriptor.

Yhis is an interesting issue, and it is larger that what #102564 covers.

* It does not handle classmethod or statimethod decorated `__call__()` for types. It is more rare case, but `__call__()` can be overridden in metaclasses, and this case is supported.
* Standard `type.__call__()` calls `__new__()` and `__init__()`, which also can be not only pure Python functions.
* There are more types of callables and descriptors that can be used here: bound methods, partial(), and various builtin methods and descriptors.

#115530 is more general, and support more different cases.

It does not support all cases. There is an explicit exclusion for builtin methods and descriptors in the current code, and I keep it for now. It can be significantly weakened (allowing to support more weird cases), but this can also break some Cython generated classes, so we should be careful. More general approach would ignore signatures like `(*args, **kwargs)`, but it requires large changes.
