### ISSUE TITLE
accept numeric strings in `logging._checkLevel` (and maybe floats)

### ISSUE THREAD

**Issue by con-f-use** [python/cpython#101255]
# Enhancement

Have [`logging._checkLevel`](https://github.com/python/cpython/blob/main/Lib/logging/__init__.py#L209) accept numeric strings and maybe floating point numbers as well.

# Pitch

Currently `_checkLevel` converts logging level names (strings) or numeric values (integers) to a proper, registered logging level. Meaning it accepts the following:
 
 ```python
 logging._checkLevel(10)
 logging._checkLevel(logging.DEBUG)
 logging._checkLevel("DEBUG")
 ```
 
 and raises a `TypeError` for
 
 ```python
 logging._checkLevel("10")
 logging._checkLevel("10.0")  # maybe problematic
 logging._checkLevel(10.0)     # maybe problematic, because what would e.g. "10.8" even mean
 ```

To me, there's really no good reason, why the latter three examples should raise a `ValueError`.

# A Usecase

Aside from the academical argument, that there's really no reason for the `ValueError` as it's pretty clear and unambiguous, what `_checkLevel("10")` intends, I sometimes find myself wanting to set the log level of a Python command line application via environment variable or command line argument. Although, `_checkLevel` is not considered public API it would naturally lend itself for the conversion from strings passed this way to a proper logging level. If I want to support both the `LOG_LEVEL="10"` and  `LOG_LEVEL="DEBUG"` in the code below, this shortcoming of `_checkLevel` is a bit unexpected and inconvenient.

```python
# app.py
import logging, os

if __name__ == "__main__":
    level = os.getenv("LOG_LEVEL", logging.INFO)
    logging.basicConfig(
        level=logging._checkLevel(level),
    )
```

```shell
$ env LOG_LEVEL=10 python app.py
...
ValueError: Unknown level: '10'
```

**Comment by con-f-use** [comment]
```python
def _checkLevel(level):
    if isinstance(level, int):
        rv = level
    elif str(level) == level:
        if level not in _nameToLevel:
            try:
                rv = int(level)
            except ValueError:
                raise ValueError("Unknown level: %r" % level)
        else:
            rv = _nameToLevel[level]
    else:
        raise TypeError("Level not an integer (literal)"
                        " or a valid level name: %r" % (level,))
    return rv
```
Something like this might be a good implementation in terms of backwards-compatibility, seeing a user might have named a level like a valid integer literal, i.e. `logging.addLevelName(15, "10")`.

**Comment by rhettinger** [comment]
I vote against this change.  The risk of accidental misuse outweighs and potential benefit — that is likely why most Python APIs don't accept `"10"` when `10` is expected.  If someone is reading an environment variable, it is not hard to make an explicit integer conversion with `int(os.environ['LOGLEVEL'])`.

**Comment by con-f-use** [comment]
I understand @rhettinger, just one correction, it would at least be something like:

```
level = os.getenv('LOGLEVEL', 20)
try:
    level = int(level)
except ValueError:
    pass
level = logging._checkLevel(level)
```

for the usecase of allowing both `LOGLEVEL=DEBUG`  and `LOGLEVEL=10` and having a fallback default. Also, my main argument was, that most users would probably intuitively expect for `_checkLevel("10")` to work.

**Comment by vsajip** [comment]
I agree with what @rhettinger said, so closing this issue.
