### ISSUE TITLE
Unknown float word ordering with ./configure

### ISSUE THREAD

**Issue by elcouz** [python/cpython#101224]
I get this error on a Raspberry PI 3 compiling from source **Python3.11.1**.

In the configure output:
[...]
checking whether float word ordering is bigendian... unknown
configure: error:

**Unknown float word ordering. You need to manually preset
ax_cv_c_float_words_bigendian=no (or yes) according to your system.**

It stop there.

I use the following flags for compilation on TinyCoreLinux (Linux box 5.10.77-piCore-v7 #1 SMP Sun Nov 7 11:27:33 UTC 2021 armv7l GNU/Linux)

CPPFLAGS="-I/usr/local/include/ncursesw" CC="gcc -flto -fuse-linker-plugin -march=armv7 -mtune=arm1176jzf-s -mfpu=vfp -Os -pipe" CXX="g++ -flto -fuse-linker-plugin -march=armv7 -mtu
ne=arm1176jzf-s -mfpu=vfp -Os -pipe -fno-exceptions -fno-rtti" ./configure --prefix=/usr/local --localstatedir=/var --enable-shared --with-system-expat --with-system-ffi --with-ensurepip=yes --with-tcltk-i
ncludes='-I/usr/local/include' --with-tcltk-libs='-L/usr/local/lib -ltk8.6 -ltcl8.6'

I get the same result with the  armv6kz arch.

Thanks!

**Comment by mdickinson** [comment]
There should be a log file called `config.log`; could you post the relevant portion of that? It should show the exact test that the configure script was performing, and the manner in which it failed. Look for a line containing "checking whether float word ordering is bigendian".

**Comment by mdickinson** [comment]
There's not much we can do with this report without more information; setting to `pending`.

**Comment by mdickinson** [comment]
See also #89640. Some of the debugging steps there may help.
