### ISSUE TITLE
Optimize pathlib path construction

### ISSUE THREAD

**Issue by barneygale** [python/cpython#101362]
[Pathlib is slow](https://github.com/faster-cpython/ideas/discussions/194). One of the most obvious symptoms is that `pathlib.PurePath` objects are slow to construct. We should be able to speed construction up without making other parts of pathlib slower.

Two possible approaches:

1. Optimize the existing machinary of path construction: `__new__()`, `_from_parts()`, `_parse_parts()`, `_parse_args()`.
2. Perform less work in the constructor: defer parsing, joining and normalization until needed.

### Linked PRs
* gh-101560
* gh-101664
* gh-101665
* gh-101667
* gh-102476

**Comment by barneygale** [comment]
I'd like to land #101363 before I put the first PR up for this issue.

**Comment by zooba** [comment]
Does the PR cope with `WindowsPurePath` and `PosixPurePath` and converting between them?

**Comment by barneygale** [comment]
Could you clarify? The PRs maintain the behaviour that attempting to instantiate `pathlib.PurePath` will give you a `PureWindowsPath` or a `PurePosixPath` depending on your platform, but pathlib doesn't support _converting_ between Windows and POSIX paths as I understand it.

**Comment by zooba** [comment]
This behaviour should be preserved:

```
Python 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import *
>>> p = PureWindowsPath("a/b/c")
>>> p
PureWindowsPath('a/b/c')
>>> PurePosixPath(p)
PurePosixPath('a/b/c')
>>> PurePath(p)
PureWindowsPath('a/b/c')
>>> PosixPath(p)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.2800.0_x64__3847v3x7pw1km\lib\pathlib.py", line 962, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system
>>> WindowsPath(p)
WindowsPath('a/b/c')
>>>
```

**Comment by barneygale** [comment]
Right! That will be broken by #101667 as things stand:

```python
>>> from os import fspath
>>> from pathlib import *
>>> p = PureWindowsPath("a/b/c")
>>> p
PureWindowsPath('a/b/c')
>>> fspath(p)
'a\\b\\c'
>>> PurePosixPath(fspath(p))
PurePosixPath('a\\b\\c')
>>> PurePosixPath(p)
PurePosixPath('a\\b\\c')
```

It doesn't appear to be documented or tested behaviour, and it feels odd to me that `PurePosixPath(p)` can give a different result to `PurePosixPath(fspath(p))`. I'll try to find a good way forwards!

**Comment by barneygale** [comment]
Also doesn't really work with drives or roots:

```python
>>> PurePosixPath(PureWindowsPath('//server/share/dir'))
PurePosixPath('\\\\server\\share\\/dir')
>>> PurePosixPath(PureWindowsPath('c:/dir'))
PurePosixPath('c:\\/dir')
>>> PurePosixPath(PureWindowsPath('/dir'))
PurePosixPath('\\/dir')
```

However, using `PurePosixPath(PureWindowsPath(...).as_posix())` works everywhere:

```python
>>> PurePosixPath(PureWindowsPath('//server/share/dir').as_posix())
PurePosixPath('//server/share/dir')
>>> PurePosixPath(PureWindowsPath('c:/share/dir').as_posix())
PurePosixPath('c:/share/dir')
>>> PurePosixPath(PureWindowsPath('/share/dir').as_posix())
PurePosixPath('/share/dir')
```

So I'm tempted to conclude it's not a supported use case, and that it only happened to work in some limited circumstances. What do you reckon?

**Comment by zooba** [comment]
I think the direct conversion should either be consistent with `fspath(p)` or `p.parts`, but no strong preference which. As you say, neither makes a huge amount of sense, and the workaround (`.as_posix()`) has been there for a long time.

Might be worth adding a short note to the docs warning that the constructor can't reliably convert from different `pathlib` objects, and maybe specify whether it will `fspath` or `.parts` them.

On another perf note, is it possible that parsing the path up front isn't necessary? Obviously it'll save the most time to keep a single string literal around and parse it later, but I don't personally have a good feel for whether that's common or not. (Obviously if it's available pre-parsed then keep it.)

**Comment by barneygale** [comment]
For anyone following along, I think this ticket can be resolved if/when this PR lands:

- #102476

**Comment by barneygale** [comment]
Resolving this issue. It's now much cheaper to construct `pathlib.PurePath` and `Path` objects. Some operations like `str()` and `joinpath()` are also cheaper.

Future work:

- #102783
- #102613
- #102511
- Add C implementation of os.path.join()
