### ISSUE TITLE
Improve test_locale_calendar_formatweekday of calendar

### ISSUE THREAD

**Issue by andrehora** [python/cpython#101377]
It seems that `test_locale_calendar_formatweekday` of calendar misses some important inputs:

https://github.com/python/cpython/blob/main/Lib/test/test_calendar.py#L567-L578

Specifically, it does not cover a day under different lengths, ie, several common cases in which 1 <= length <= 10, which can change the weekday formatting.

### Linked PRs
* gh-101378
* gh-102713
* gh-102714

**Comment by hauntsaninja** [comment]
Thank you! :-)
