### ISSUE TITLE
decimal.to_eng_string gives wrong engineering notation in some cases

### ISSUE THREAD

**Issue by MichaDit** [python/cpython#101329]
E.g. `0.123` results in `0.123`, but it should result in `123E-3`.
Edit 2023-01-26:
~~Engineering notation always has 1 to 3 digits preceding the decimal point.~~
In the vast majority definitions/examples of the engineering notation there has to be 1 to 3 digits preceding the decimal point.
The only exception I am aware of is [Decimal Arithmetic Specification, version 1.7 from IBM](http://speleotrove.com/decimal/decarith.html)

Somehow related to #70411

### Linked PRs
* gh-101330

**Comment by rhettinger** [comment]
> Engineering notation **always** has 1 to 3 digits preceding the decimal point

This is not what the specification says: 

> This operation converts a number to a string, using engineering notation **if an exponent is needed**.

The determination is made following "the rules for conversion to scientific numeric string":

> The coefficient is first converted to a string in base ten using the characters 0 through 9 with no leading zeros (except if its value is zero, in which case a single 0 character is used). 
> Next, the adjusted exponent is calculated; this is the exponent, plus the number of characters in the converted coefficient, less one. That is, exponent+(clength-1), where clength is the length of the coefficient in decimal digits. 
> If the exponent is less than or equal to zero and the adjusted exponent is greater than or equal to -6, the number will be converted to a character form without using exponential notation.

For your example, that gives:

```
>>> dt = Decimal('0.123').as_tuple()
>>> dt
DecimalTuple(sign=0, digits=(1, 2, 3), exponent=-3)
>>> dt.exponent + len(dt.digits) - 1 <= 6
True
```

Accordingly, exponential notation is not used and the current output is correct:

```
>>> Decimal('0.123').to_eng_string()
'0.123'
```

Side note:  We use version `1.70` of the specification which can be found [here](http://speleotrove.com/decimal/decarith.html).

**Comment by MichaDit** [comment]
@rhettinger Points accepted, corrected 1st post.
Is it mandatory to stick to this specification?

**Comment by rhettinger** [comment]
> Is it mandatory to stick to this specification?

Yes.

**Comment by MichaDit** [comment]
Then the only point that is left, is that the IBM spec is outdated and should be updated to international standard [ISO/IEC/IEEE 60559-2020 Floating-point arithmetic](https://ieeexplore.ieee.org/document/9091348) (Superseded IEEE 754 / [IBM spec]).
With that update deprecating/removing decimal.to_eng_string seems to be the best solution, as engineering notation is not included in 60559 and there are suitable packages awailable.

**Comment by ericvsmith** [comment]
We won't be removing `decimal.to_eng_string()`.
