### ISSUE TITLE
Possible small mistake in the documentation of importlib.util.LazyLoader.factory

### ISSUE THREAD

**Issue by busywhitespace** [python/cpython#101390]
The <u>documentation</u> of _LoazyLoader_.**factory** in the module _importlib.util_ says:

> **classmethod** factory(loader)
>
> A **static method** which returns a callable that creates a lazy loader. This is meant to be used in situations where the loader is passed by class instead of by instance.

The problem is that there is a mixing of words **classmethod** and **static method**. And the [documentation](https://docs.python.org/3/reference/datamodel.html#types) defines the _static method_ as <q>... Static method objects are created by the built-in staticmethod() constructor.</q>

The source code for the method is:

```python
@classmethod
def factory(cls, loader):
    """Construct a callable which returns the eager loader made lazy."""
    cls.__check_eager_loader(loader)
    return lambda *args, **kwargs: cls(loader(*args, **kwargs))
```

So, in my opition, "a static method" in the documentation should be corrected to "a class method".

I've created the PR in case the issue is right.

### Linked PRs
* gh-101391
* gh-101813
* gh-101814

**Comment by brettcannon** [comment]
The specific code lines in question:

https://github.com/python/cpython/blob/61f2be08661949e2f6dfc94143436297e60d47de/Lib/importlib/util.py#L170-L171

So @busywhitespace is correct that the docs are wrong about calling it a static method.

**Comment by hauntsaninja** [comment]
Thanks, looks like this was fixed
