### ISSUE TITLE
Set function not returning ordered set.

### ISSUE THREAD

**Issue by 0-shubham-0** [python/cpython#101389]
`a=set()
a.add(0)
a.add(6)
a.add(6)
a.add(4)
a.add(8)`

output
{0, 8, 4, 6}

**Comment by zware** [comment]
It appears from the closing of the issue that you figured it out for yourself, but for the benefit of anyone else who comes across this: `set` is unordered, as documented in the second paragraph [about Set types](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset).
