### ISSUE TITLE
A little optimization

### ISSUE THREAD

**Issue by SatinWukerORIG** [python/cpython#101365]
# Enhancement

https://github.com/python/cpython/blob/main/Parser/token.c
line 79, 109, and 193 used int to define functions, yet the return values only need to be short int.
line 80, 110, and 194 used int to define chars, however, this leads to the overhead of memory.
# Pitch
This should be implemented or corrected because this can cause a little bit of improvement in the code performance.

**Comment by corona10** [comment]
Would you like to submit the PR? cc @gvanrossum

**Comment by SatinWuker** [comment]
i am sorry, this commit is not successful in the testing phase, thus i cannot submit. My apology.

**Comment by corona10** [comment]
@SatinWuker 

1. You have to modify the [generator](https://github.com/python/cpython/blob/e5b08ddddf1099f04bf65e63017de840bd4b5980/Tools/build/generate_token.py#L85-L90) and rerun `make regen-token` 
2. And also prove the change is worth to do it.
