### ISSUE TITLE
Remove unncessary enum._power_of_two function

### ISSUE THREAD

**Issue by corona10** [python/cpython#101341]
https://github.com/python/cpython/blob/dfad678d7024ab86d265d84ed45999e031a03691/Lib/enum.py#L1568-L1571

This function looks like be defined by mistake.

### Linked PRs
* gh-101342

**Comment by arhadthedev** [comment]
This method is introduced in 7aaeb2a3d682ecba125c33511e4b4796021d2f82. According to the parent issue (gh-82431) it was supposed to be somehow used in iterators created by `enum.__iter__()`.

@ethanfurman (an author of that commit) Can we remove `iterator._power_of_two()` or you'll develop it further?

**Comment by ethanfurman** [comment]
It can go.
