### ISSUE TITLE
Add TCP keepalive option for `asyncio.start_server()`

### ISSUE THREAD

**Issue by beavailable** [python/cpython#101336]
By default, this `asyncio.start_server()` method will create a list of socket objects usually for both IPv4 and IPv6 (if possible) and do not set keepalive option. if I want I can create a socket object by myself and set keepalive option for it, then pass it in `start_server()`, but if so, I will not be able to start a server which listens on both IPv4 and IPv6 addresses.
I hope we can add a keepalive parameter for `asyncio.start_server()` or do something else to make things easier.

### Linked PRs
* gh-112485

**Comment by axoroll7** [comment]
I don't have the same problem as you, but I understand your problem. It is a recurrent problem for me. For many projects, not only web servers, but others TCP servers too. The same problem appears with others programming languages. To alleviate this problem in Python, I thought about monkey-patching the library in question, or the socket library to use TCP keepalive. The mode being applied before `bind` and `connect`. Can TCP keepalive be applied after `bind`, `connect` or the first interaction ? In addition to this, it is difficult to access the internal sockets.

For some software prototypes, (never in production), I patched some methods of the socket object to add TCP keepalive, for most OSes :

Function signature :
```python
def tcp_keepalive(
        sock:socket.socket,
        heartbeat_s:int,
        retry_interval_s:int,
        max_retries:Optional[None] = None,
    ) -> None:
    pass
```
For linux :
```python
sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPIDLE, retry_interval_s)
sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPINTVL, heartbeat_s)
if max_retries is not None:
    sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_KEEPCNT, max_retries)
```
For BSD (macOS, FreeBSD, OpenBSD, NetBSD) :
```python
# BSD offers only one parameter
TCP_KEEPALIVE = 0x10
sock.setsockopt(socket.SOL_SOCKET, socket.SO_KEEPALIVE, 1)
sock.setsockopt(socket.IPPROTO_TCP, TCP_KEEPALIVE, heartbeat_s)
```
For Windows :
```python
# max_retries is not configurable on Windows
sock.ioctl(socket.SIO_KEEPALIVE_VALS, (1, retry_interval_s * 1000, heartbeat_s * 1000))
```
(English isn't my first language, so please excuse any mistakes.)

**Comment by beavailable** [comment]
> Can TCP keepalive be applied after `bind`, `connect` or the first interaction ?
> 
Seems that it can't.

**Comment by gvanrossum** [comment]
Please just propose a pull request that adds a keyword parameter to the right API. We will take it from there.
