### ISSUE TITLE
Bytecode interpreter generator should support composing instructions from parts.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#101369]
I.e. [this](https://github.com/python/cpython/commit/5a9af9c85c0cc9105472b435ec63acc6d4385719) should work as expected.
```
inst(BINARY_OP_ADD_FLOAT) = _BINARY_OP_ADD_FLOAT_CHECK + _BINARY_OP_ADD_FLOAT_ACTION;
```

The suggested solution of [using macro](https://github.com/faster-cpython/ideas/issues/541#issuecomment-1405242983) doesn't work.
I get the error:
```
./Python/bytecodes.c:171: Unknown instruction 'BINARY_OP_ADD_FLOAT' referenced in family 'binary_op'
./Python/bytecodes.c:171: Family 'binary_op' has unknown members: {'BINARY_OP_ADD_FLOAT'}
```

### Linked PRs
* gh-101399

**Comment by gvanrossum** [comment]
Looks like I left some technical debt in macro handling. :-(

- [ ] check_families() needs to look for family members in macros
- [ ] map_families() needs to look for PREDICT() targets in macros
- [ ] macro prelude generation needs to avoid emitting duplicate declarations when input and output variable names overlap
- [ ] add tests

**Comment by markshannon** [comment]
I would "macro" to go. Instructions defined by composing ops are instructions just as much as those defined by a blob of C code. 
`inst(FOO_AND_BAR) = FOO + BAR;`
Could you add 

- [ ] Rename `macro` as `inst`, as they are instructions.

to the end of your list?

**Comment by gvanrossum** [comment]
We’ve talked about that before, it would get a red squiggle in VS Code. Other than that it’s doable. @brandtbucher ?
