### ISSUE TITLE
PyObject_GC_Resize doesn't check preheader size

### ISSUE THREAD

**Issue by colesbury** [python/cpython#101408]
The `PyObject_GC_Resize` implementation in the main branch doesn't check if the object has a preheader:

https://github.com/python/cpython/blob/0ef92d979311ba82d4c41b22ef38e12e1b08b13d/Modules/gcmodule.c#L2357-L2358

The only internal use I see is by `_PyTuple_Resize` which doesn't have a preheader, but the [`PyObject_GC_Resize`](https://docs.python.org/3/c-api/gcsupport.html#:~:text=TYPE%20*-,PyObject_GC_Resize,-(TYPE%2C ) function is publicly documented.

### Linked PRs
* gh-101741

**Comment by corona10** [comment]
@colesbury Patch is merged, but I left the issue open for the test code.

**Comment by erlend-aasland** [comment]
@corona10: what is the status on test code? 😄

**Comment by corona10** [comment]
@erlend-aasland Nah, let's close the issue until it needs (no bandwidth to work with these days)
