### ISSUE TITLE
Add internal API for fast module access from heap type methods

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#101476]
See [topic on Discourse](https://discuss.python.org/t/a-fast-variant-of-pytype-getmodule/23377?u=erlendaasland).

For CPython internal usage, we've got `_PyModule_GetState`, which is a fast variant of `PyModule_GetState`, the module check in the latter is simply an assert in the former.

For `PyType_GetModuleState`, there are three `if`s (two of them implicitly in `PyType_GetModule`):

1. check that the given type is a heap type
2. check that the given type has an associated module
3. check that the result of `PyType_GetModule` is not `NULL`

For stdlib core extension modules, all of these conditions are always true (AFAIK). With a fast static inlined variant, for example `_PyType_GetModuleState`, with a fast variant of `PyType_GetModule` inlined, where all three conditions are `assert()`ed, we can speed up a heap type methods that need to access module state.

### Linked PRs
* gh-101477
* gh-102188

**Comment by gpshead** [comment]
relevant discuss thread: https://discuss.python.org/t/a-fast-variant-of-pytype-getmodulestate/23377

i left a question on the PR regarding the API name (ALL_CAPS or not for in the API name to be similar to other fast unchecked APIs).
