### ISSUE TITLE
_tracemalloc__get_object_traceback doesn't handle objects with pre-headers correctly

### ISSUE THREAD

**Issue by colesbury** [python/cpython#101430]
In the main branch, the function `_tracemalloc__get_object_traceback` doesn't account for objects with preheaders:

https://github.com/python/cpython/blob/ea232716d3de1675478db3a302629ba43194c967/Modules/_tracemalloc.c#L1406-L1414

This means that when running with tracemalloc some allocation tracebacks are missing:

```python
import warnings

class MyClass:
    def __del__(self):
        warnings.warn("Uh oh", ResourceWarning, source=self)

def func():
    m = MyClass()

func()
```

```
python3 -Wd -X tracemalloc=2 example.py
```

cc @markshannon 

### Linked PRs
* gh-101745

**Comment by colesbury** [comment]
Also `_PyTraceMalloc_NewReference`:

https://github.com/python/cpython/blob/28db978d7f134edf6c86f21c42e15003511e7e9b/Modules/_tracemalloc.c#L1726-L1733

**Comment by vstinner** [comment]
If someone is motivated, it would be nice to add an unit test to test_tracemalloc for this case.
