### ISSUE TITLE
From doesn't work

### ISSUE THREAD

**Issue by pschaeffer** [python/cpython#101465]
I am using Python 3.9 (sadly). I have to use 3.9 because I am also using Visual Studio 2022. VS 2022 only supports Python 3.9 (sadly). I would much prefer to use a later release of Python, but for now can't.

My problem is that 'from' statements (some of them) don't work. What I mean is that they get ignored. They should (in my case) create class objects. Of course, some (most) 'from' statements do create class objects. However, sometimes they ('from' statements) don't. What is weird is that in some source files the exact same 'from' statement works and in other source files it gets ignored.

This problem shows up in VS 2022, but also shows up when I run Python from the command line. What am I doing wrong?

**Comment by iritkatriel** [comment]
This is the python but tracker, it is for reporting bugs in python. To report a bug in "from" you would need to include a script that produces unexpected output (typically behaviour that contradicts the documentation).

For general questions about how to use python you can refer to https://discuss.python.org/c/users/7.

**Comment by pschaeffer** [comment]
Hi,
I would be glad to provide a script that reproduces the problem. However, that is not possible in this case. The problem involves multiple files. My guess is that other folks are probably having the same problem. Perhaps a search of open/closed/etc. issues might turn up something. 
Thank you
Peter Schaeffer

**Comment by pschaeffer** [comment]
Hi,

 

What does ‘not planned’ mean in this case? Python has had ‘from’ and ‘import’ statements for a long time. Sadly, I am now having problems with ‘from’ statements (in some cases). Should I create a new issue? Provide more details? Where? How?

 

Thank you

 

Peter Schaeffer

**Comment by pschaeffer** [comment]
Hi Irit Katriel,

 

I worked on this a bit further. It turns out to be a circular import problem (see below). The possible bug is that I never got an importError or any other exception. Instead, I got a runtime exception (NameError: name 'IDLmAJAX' is not defined). This problem can be easily (not really) reproduced be creating 3 (yes 3) files. 

IDLmBuild.py

 

from   IDLmAJAX       import *

from   IDLmUtility    import *

IDLmUtility.getPerceptualHash('a')

 

IDLmUtility.py

 

from   IDLmAJAX       import * 

class IDLmUtility(object):  

  @staticmethod 

  def getPerceptualHash(urlStr): 

    print(IDLmAJAX)



IDLmAJAX.py

 

from   IDLmUtility       import *

class IDLmAJAX(object):

  def runAJAX():

    pass

 

 

Note that IDLmBuild.py is the ‘main’ program where execution should start. See below.

 

C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps>py IDLmBuild.py

Traceback (most recent call last):

  File "C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps\IDLmBuild.py", line 3, in <module>

    IDLmUtility.getPerceptualHash('a')

  File "C:\Users\Peter\Documents\Visual Studio 2022\projects\PythonApps\PythonApps\IDLmUtility.py", line 5, in getPercep

    print(IDLmAJAX)

NameError: name 'IDLmAJAX' is not defined

 

Thank you

 

Peter Schaeffer

**Comment by iritkatriel** [comment]
This is in the FAQ: https://docs.python.org/3/faq/programming.html?highlight=circular#what-are-the-best-practices-for-using-import-in-a-module

**Comment by iritkatriel** [comment]
Check the documentation.

**Comment by pschaeffer** [comment]
Hi Irit Katriel,

 

I created a program that reads Python files and detects circular import problems. It even found some circular import problems that I didn’t know about. I would be glad to share the program. One problem is that the program uses a tokenizer that I created. 

 

Thank you

 

Peter Schaeffer

**Comment by iritkatriel** [comment]
You can share it from your gut hub account, or upload it as a module to PYPI.

**Comment by pschaeffer** [comment]
Hello Irit Katriel,

 

I uploaded my code to PyPI using the name detectCircularImports_pschaeffer.


Did I do this correctly?

 

I am not sure either way.

 

Thank you

 

Peter Schaeffer

**Comment by iritkatriel** [comment]
Questions of this sort are out of scope for the cpython bug tracker. You can ask on one of the many python user help forums.
