### ISSUE TITLE
Enhance aiter to support built-in sync iterables

### ISSUE THREAD

**Issue by Henkhogan** [python/cpython#101495]
# Feature or enhancement

Enhance builtin iterables like list, range with async methods like __aiter__, __anext__,...

# Pitch

It would allow to use e.g. async list comprehenions on normal lists like:

[_ async for _ in list(range(1,10))]

-> helpful if the code snipped is supposed to handle async iterables like normal iterables

# Previous discussion

https://discuss.python.org/t/enhance-builtin-iterables-like-list-range-with-async-methods-like-aiter-anext/21352/1

### Linked PRs
* gh-119278

**Comment by ofek** [comment]
I am very much in favor of this as it would remove the need to pepper the use of the following utility throughout every code base:

```python
async def aiter(iterable: Iterable):
    yield from iterable
```

**Comment by zware** [comment]
As mentioned in the discussion, sprinkling `__aiter__` implementations around the codebase is not the way to go here.  Adjusting the `aiter` builtin to automatically wrap synchronous iterators is a much more palatable option.

**Comment by brettcannon** [comment]
> Is adding `__aiter__` to `object` feasible?

Feasible, yes. Desirable, no, as that would make **every** object an asynchronous iterable.

**Comment by kumaraditya303** [comment]
I am -1 on this, to me this feels like an anti pattern and if you are using async generator for sync code then IMO it is wrong design.

**Comment by merwok** [comment]
Some motivation was provided in the thread, and the current proposal is about changing `aiter` rather than built-in objects.

**Comment by ofek** [comment]
Yes, can we change the PR title?

**Comment by Henkhogan** [comment]
New title proposal "aiter(): Implicit handling of synchronous iterable"

**Comment by Henkhogan** [comment]
Should this be extended to "async with" which seems very similar to me

**Comment by zware** [comment]
> Should this be extended to "async with" which seems very similar to me

Not in this issue, but perhaps in another.  It has different considerations and is completely unrelated to this issue.

**Comment by SimpleArt** [comment]
It is worth noting that `async-stdlib` includes this function, which can serve as a reference implementation.

This does however beg me the question: is it `aiter` that needs to be changed or the semantics of using `async for`? It sounds like we're going from `async for x in iterable` to using `async for x in aiter(iterable)` everywhere. This situation is also similar to `iter(...)` and types which implement `__getitem__` and `__len__`. Note that there's no need to do `for x in iterable` in those cases either.

**Comment by merwok** [comment]
In general, Python’s design is that keyword and operators have clear, simple behaviour (`async for` iterates over async iterables) and functions can do convenient things and conversions (`iter` is more than just calling `__iter__`, `aiter` can wrap sync iterables).

**Comment by brettcannon** [comment]
> It is worth noting that `async-stdlib` includes this function, which can serve as a reference implementation.

There are potential licensing concerns unless the person who wrote that code for `async-stdlib` also opens the PR to contribute the code to CPython.



> is it `aiter` that needs to be changed or the semantics of using `async for`?

It's `aiter`.



> It sounds like we're going from `async for x in iterable` to using `async for x in aiter(iterable)` everywhere.

That's only true if you accept any iterable, async or not, and want it to work in that loop.

**Comment by lambdaq** [comment]
> Some motivation was provided in the thread, and the current proposal is about changing `aiter` rather than built-in objects.

This sounds like a good compromise, are there any shipping plans to update the built-in `aiter()` ?
