### ISSUE TITLE
Wrong Spanish translation for math.floor

### ISSUE THREAD

**Issue by oluaces** [python/cpython#101457]
# Documentation

The Spanish translation for the math.floor (https://docs.python.org/es/3/library/math.html?highlight=math%20floor#math.floor) function says:
"...el primer número entero mayor o igual que x"
where it should be 
"...el primer número entero **menor** o igual que x"

**Comment by AlexWaygood** [comment]
Thanks! Issues with the Spanish docs need to be reported at https://github.com/python/python-docs-es, unfortunately -- please file the issue over there!
