### ISSUE TITLE
Misleading description for bisect_left function

### ISSUE THREAD

**Issue by bruisedsamurai** [python/cpython#101402]
# Documentation
https://docs.python.org/3/library/bisect.html#bisect.bisect_left
 > If x is already present in a, the insertion point will be before (to the left of) any existing entries.

This description gives the impression that `i` will be left to any occurrence of `x` but instead it points to left most occurrence of `x`.

```python
from bisect import bisect_left

arr = [1,2,3,4,5]

print(bisect_left(arr, 3))

# 2
```

**Comment by stevendaprano** [comment]
I don't understand what you think is the bug here. `a` is the list itself, so there is no "any occurrence of `a`" in the list. You probably meant `x`. The documentation is correct: the returned result (2) is to the left of the `x` (3).

```
List:    [| 1 | 2 | 3 | 4 | 5 |]
Indices:  0   1   2   3   4   5
```

**Comment by pochmann** [comment]
@stevendaprano Only of you think of indices like that, between the values. Most people probably think this way:

```
List:    [| 1 | 2 | 3 | 4 | 5 |]
Indices:    0   1   2   3   4
```

**Comment by bruisedsamurai** [comment]
@stevendaprano Yeah, fixed

@pochmann agree

It's hard to change the mental model for this specific algorithm. Because you now have to get the result and use it as regular indices. So, what value should I expect for the returned index?

**Comment by tim-one** [comment]
Well, the docs say "insertion point" instead of "index" for a reason: a list of length `N` has `N` indices, but `N+1` insertion points, and all `N+1` insertion points are possible return values of the bisect functions.  The alternative would be clumsy, like "`bisect_right()` returns one more than the index of the largest value <= the argument, even if that's an invalid index".

"Insertion points" aren't unique to this module - Python's sequence slice notation relies on the same mental model of "pointing between sequence elements". The docs should spell that out somewhere - but, for all I know, they already do somewhere.

**Comment by stevendaprano** [comment]
The best way to think about slicing is to think of the indices being 
between the values. Once you do that, it makes sense to think if 
indexing the same way.

Thinking of indices between the items just makes everything so much 
easier.

**Comment by bruisedsamurai** [comment]
Maybe then add a link to `insertion_point` explaining this 
```
Insertion point : indices being between the values
List:    [| 1 | 2 | 3 | 4 | 5 |]
Indices:  0   1   2   3   4   5
```

**Comment by ericvsmith** [comment]
I think it’s pretty clear as-is, especially because it mentions calling `list.insert()`. If you had a suggested change to the documentation, that would be helpful for this discussion.

**Comment by bruisedsamurai** [comment]
@ericvsmith hi,  I suggest some additions based on previous comments.

**Comment by rhettinger** [comment]
> "Insertion points" aren't unique to this module -

And they are covered [early in the Python tutorial](https://docs.python.org/3/tutorial/introduction.html#strings).  It is a language basic.

Also, the entire bisect module is designed around insertion points.  It is fundamental to what these functions do.  The docs are clear about this "Locate the insertion point for x in a to maintain sorted order" and "The return value is suitable for use as the first parameter to list.insert() assuming that a is already sorted.".

I concur with Eric, Steven, and Tim that there isn't a documentation bug here.  Marking this as closed.  The existing words and examples are clear.  That might not help a user who has a preexisting and conflicting mental model.  If they can't overcome that world view by reading the module docs, there are links to the source (which is short and sweet), there is StackOverflow, there are tutorial lists, and there one can easily experiment in an interactive shell.
