### ISSUE TITLE
OrderedDict dict/list representation

### ISSUE THREAD

**Issue by SimpleArt** [python/cpython#101446]
I know that for historical purposes, `OrderedDict.__repr__` displays key-value pairs in the format of `[(key, value), ...]`, since the `{key: value, ...}` representation did not respect the ordering that `OrderedDict` needs. However, this was only in the past and it has become a while since dictionaries have become ordered, so I was wondering if changing the `OrderedDict.__repr__` to display `OrderedDict({key: value, ...})` instead would be fine. The main rationale is that this is syntactically cleaner to read, often I have found the other representation to be a lot more clunky. Other than potentially breaking things like doc-tests, I don't see much issue with this. The only potential ambiguity that I see is the fact that one might not be immediately sure that the dictionary is ordered, but the fact that it is wrapped by `OrderedDict(...)` would probably dispel any doubts.

### Linked PRs
* gh-101661

**Comment by rhettinger** [comment]
I agree that the proposed new `__repr__` would be an improvement.

**Comment by rwgk** [comment]
Currently this change is mentioned only in the 3.12 [Changelog](https://docs.python.org/3.12/whatsnew/changelog.html) but not under the top-level [What’s New In Python 3.12](https://docs.python.org/3.12/whatsnew/3.12.html) page.
 
@yhg1s suggested that it should be mentioned in What’s New, too. Should I file a separate bug for this, or is this comment sufficient as a reminder?
