### ISSUE TITLE
Bug on multiprocessing.shared_memory.ShareableList

### ISSUE THREAD

**Issue by JunLeecus** [python/cpython#101416]
Hello, I meet some bug when I use `multiprocessing.shared_memory.ShareableList`.
I want to save image bytes in a ShareableList, but some bytes are dropped. My codes are simple, 
```
import numpy as np
fake_data = np.empty([720, 1280], dtype=np.uint8)
shm_list =  ShareableList([fake_data.tobytes()])
...
def process(image_bytes: bytes):
        data: np.ndarray[np.uint8] = np.frombuffer(image_bytes, np.uint8)
        image = data.reshape((720, 1280))
        shm_list[0] = image_bytes
        print(np.frombuffer(list(shm_list)[0], np.uint8).shape)
        print(np.frombuffer(image_bytes, np.uint8).shape)
...
shm_list.shm.close()
shm_list.shm.unlink()
```
this with the output
![image](https://user-images.githubusercontent.com/47651397/215416229-0b983cbc-b714-41b8-8b78-2236e6c55d0e.png)
it seems some bytes are dropped.

My env 
```
Description:    Ubuntu 20.04.4 LTS
python version : Python 3.8.10
```

This bug can be reproduce on our 2 Thinkpad X1 PC wirh arch `x86_64`, but normal on `aarch64` device.

Thanks for help!

**Comment by GarvitMehta44** [comment]
shm_link.shm.print()

**Comment by JunLeecus** [comment]
> 
`ShareableList.shm` is a `SharedMemory` instance without `print` method in python3.8.10

**Comment by JunLeecus** [comment]
I findout some of the reason. Actually, my image is an inflect of c++ Mat by pybind without copy to python. When I copy the image in python by `np.array(image)`, things will be right. But I still want to know if there is any RLE in SharedMemory?
