### ISSUE TITLE
`floor()` function definition error (only in spanish)

### ISSUE THREAD

**Issue by pablo-pnunez** [python/cpython#101456]
## Documentation

Where it says: _"el primer número entero mayor o igual que x"_
Should say: _"el primer número entero menor o igual que x"_

[https://docs.python.org/es/3.11/library/math.html](https://docs.python.org/es/3.11/library/math.html)

**Comment by AlexWaygood** [comment]
Thanks! Issues with the Spanish docs need to be reported at https://github.com/python/python-docs-es, unfortunately -- please file the issue over there!
