### ISSUE TITLE
Wrong example in more_itertools.unique_everseen

### ISSUE THREAD

**Issue by ngtrunghuan** [python/cpython#101491]
# Documentation

`unique_everseen('AAAABBBCCDAABBB') --> A B C D` is wrong. It should be `unique_everseen('AAAABBBCCDAABBBDDD') --> A B C D` or `unique_everseen('AAAABBBCCDAABBB') --> A B C`, but I think we should opt for the former to keep the result output consistent with the other example.

**Comment by ngtrunghuan** [comment]
I'm not sure this issue was necessary - was creating it for https://github.com/python/cpython/pull/101489 but I saw `Most PRs will require an issue number. Trivial changes, like fixing a typo, do not need an issue.` and thought this is indeed not required.

**Comment by hugovk** [comment]
Tip re: https://github.com/python/cpython/pull/101489: make sure to edit from the `main` branch, not `3.11`:

https://devguide.python.org/getting-started/pull-request-lifecycle/

We can backport fixes from `main` to older branches.

---

> `unique_everseen('AAAABBBCCDAABBB') --> A B C D` is wrong. 

Please could you explain how so? Running the code, I get the same output:

```pycon
>>> list(unique_everseen('AAAABBBCCDAABBB'))
['A', 'B', 'C', 'D']
```

> It should be `unique_everseen('AAAABBBCCDAABBBDDD') --> A B C D` 

Yes, I get the same output:

```pycon
>>> list(unique_everseen('AAAABBBCCDAABBBDDD'))
['A', 'B', 'C', 'D']
```

> or `unique_everseen('AAAABBBCCDAABBB') --> A B C`, 

But this outputs `['A', 'B', 'C', 'D']` (it's the first example above).

**Comment by ngtrunghuan** [comment]
yeah sorry it was a mistake
