### ISSUE TITLE
wrong type documented for xml.etree.ElementInclude.default_loader

### ISSUE THREAD

**Issue by mbel0** [python/cpython#101549]
# Documentation

In the description of xml.etree.ElementInclude in the funtion reference at [ElementInclude reference](https://docs.python.org/3.7/library/xml.etree.elementtree.html?highlight=xml#elementinclude-functions) in all versions starting with 3.7, and ending with 3.12 dev (looks like the first with XInclude suppoert, or at least with such documentation, while it is not mentioned everywhere)

1. issue with [xml.etree.ElementInclude.default_loader](https://docs.python.org/3.7/library/xml.etree.elementtree.html?highlight=xml#xml.etree.ElementTree.xml.etree.ElementInclude.default_loader)

it does not return `ElementTree`, it returns `Element`. returning `Element` causes exceptions later in the library. So suggested text is " If the parse mode is "xml", this is an Element instance."

2. issue with [xml.etree.ElementInclude.include](https://docs.python.org/3.12/library/xml.etree.elementtree.html?highlight=xml#xml.etree.ElementInclude.include)

It does not return anything, it just expands one of its parameters. Also there is a parse mode mentioned there, but it is not under control of this function. The whole phrase starting from "If the parse ..." can be just dropped as confusing. Or it can be mentioned that only xml and text files are supported for inclusion into xi:include

### Linked PRs
* gh-101550
* gh-117754

**Comment by mbel0** [comment]
the `default` loader is implemented in Lib/xml/etree/ElementInclude.py. there you can see in [default loader result for xml](https://github.com/python/cpython/blob/f4c03484da59049eb62a9bf7777b963e2267d187/Lib/xml/etree/ElementInclude.py#L90) that `.getroot()` result is returned. `getroot` is the method of `ElementTree`, but it returns `Element`

as for removing sentence about xml and text parsing from the `include` method - there are no parameters in `include` which can control this, this comes from the xml. What kind of includes are supported is explained in the beginning of the ElementInclude chapter. Also this phrase is the duplicate of the phrase in `default_loader`, where it makes sense, as inclusion type is one of the parameters, but not for the `include` method

**Comment by hugovk** [comment]
Merged and backported, thanks!
