### ISSUE TITLE
"make test" crushes raspberry pi by running tests in parallel

### ISSUE THREAD

**Issue by bwduncan** [python/cpython#101519]
# Bug report

Running "make test" after compiling Python 3.11.1 on a raspberry pi unexpectedly used all the cores. This caused it to then use all the remaining memory, and swap, and generally made a mess. I did not expect a parallel `make` without specifying `-j`.

I appreciate this is a helpful default in most cases and that it is probably difficult to replicate the nice behaviour of a python-based parallelisation with make, but in my case it just ground the raspberries into a paste and it wasn't immediately obvious without digging into the Makefile how to run the tests in serial.

# Your environment

- CPython versions tested on: CPython 3.11.1
- Operating system and architecture: Raspberry pi OS (aka Raspbian) 11 (bullseye) arm64 on a Raspberry Pi 3 model B rev 1.2

**Comment by hauntsaninja** [comment]
I'm sorry your Pi got crushed!

What is the specific change you're asking for? I think we're unlikely to change the default here; it's 2023 and parallel by default is the right thing to do since it optimises for human time. Parallelism of the build is also documented at https://devguide.python.org/getting-started/setup-building/#unix

**Comment by bwduncan** [comment]
It's ok, I didn't get in a jam :laughing: 

I'm not sure what specific change I want, but the fact that the build is explicitly parallel but the tests are implicitly parallel is surprising.

I guess there is development effort required to guess how much memory/CPU is available and limit our load to that. Probably it's much easier to rename the Makefile target test-parallel or something, so that it's explicit that's what will happen.

**Comment by bwduncan** [comment]
Oh, and it looks like the documentation you linked to doesn't mention testing the build at all, and it says that you have to ask for explicit parallelism in the build! Anyway, I don't feel strongly about this, it's just a bit unpleasant and it's obvious why it fails, and you can just skip the tests (although actually the old version of gcc on raspbian doesn't seem to work well with -march=native, I got SIGBUS running home-assistant, but I can't say for sure the tests would have spotted that and I'm sure it's fixed now anyway)

**Comment by kwsp** [comment]
@bwduncan the recommended way to run tests is `python -m test` as [documented in the dev guide](https://devguide.python.org/testing/run-write-tests/), which isn't parallel by default, and you enable more cores with the `-j` flag.
