### ISSUE TITLE
Pathlib.is_dir() handling of recursive symlinks is arguably wrong

### ISSUE THREAD

**Issue by geophile** [python/cpython#101542]
The documentation of is_dir() says:

> 
> Return True if the path points to a directory (or a symbolic link pointing to a directory), False if it points to another kind of file.
> 
> False is also returned if the path doesn’t exist or is a broken symlink; other errors (such as permission errors) are propagated.

The program below demonstrates that is_dir() applied to a circular symlink returns True, until the 41st level of recursion. Then, is_dir() returns false. This is because os.stat raises an OSError which is swallowed by is_dir(), and that error (ELOOP) is ignored.

This behavior is inconsistent with the documentation. The symlink does point to a directory, no matter how many times you go around the loop, so True is always the correct result. If too many times around the loop is indeed an error, then False should be returned, per the documented behavior.

My personal opinion is that a circular link should be handled either by raising an exception. (A return type other than boolean is a possibility, but seems non-Pythonic to me.) Perhaps, in the interest of compatibility, is_dir() could take an optional argument such as raise_exception_on_cycle, defaulting to False. Other methods (stat, for example), would seem to have the same issue.

```python
import os
import pathlib

DIR = '/tmp/r'
CIRCULAR_LINK = 'recursive'

def setup(dir):
    os.system(f'rm -rf {dir}')
    os.system(f'mkdir {dir}')
    os.system(f'ln -s . {dir}/recursive')

def recurse(path, limit, depth):
    if depth == limit:
        return
    print(f'depth {depth} {len(str(path))}:  {path.is_dir()}  {os.stat(str(path))}')
    recurse(path / CIRCULAR_LINK, limit, depth + 1)

def main():
    setup(DIR)
    recurse(pathlib.Path(DIR), 100, 0)

if __name__ == '__main__':
    main()
```

**Comment by eryksun** [comment]
An open on Linux is allowed to traverse up to 40 symlinks, no matter what they target. It doesn't actually matter whether the path is a loop. Similarly, an open on Windows is allowed 64 reparse attempts, which includes resolving the device symbolic link (e.g. "\\??\\C:" -> "\\Device\\HarddiskVolume2"). This is a simplistic way to prevent getting stuck in an infinite loop.

A path that exceeds the limit doesn't exist in the normal sense. Resolving it requires manually resolving symlinks, such as via `os.path.realpath()` or `pathlib.Path.resolve()`. I don't think it's worth the extra work to differentiate the reason that the `os.stat()` call fails with the error `ELOOP` on POSIX or `ERROR_CANT_RESOLVE_FILENAME` (1921) on Windows. Maybe the path merely exceeds the allowed number of symlinks, or maybe there's a dysfunctional symlink loop such as "recursive" -> "recursive".

**Comment by barneygale** [comment]
Closing per Eryk's comment. Thanks for the report nonetheless :)
