### ISSUE TITLE
1st line of the math.perm docstring doesn't mention a default value for k

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#101592]
Here is an example how this looks in the IDLE:
![1](https://user-images.githubusercontent.com/2155800/215657351-fae17dec-a5b2-40f3-b599-bfb606060f51.png)

While full docstring and the sphinx docs looks fine, the first line doesn't describe the function signature correctly.

_Originally posted by @skirpichev in https://github.com/python/cpython/issues/89381#issuecomment-1409708287_

**Comment by rhettinger** [comment]
I think this is unimportant.  There is only a limited amount of information that can be squeezed into the first line.   The default `k=None` is the least important case and its functionality is duplicated by `factorial`.

So, I'll mark this one as "don't worry about it".

**Comment by skirpichev** [comment]
> There is only a limited amount of information that can be squeezed into the first line.

Sure, I realize that.

> The default k=None is the least important case

The point is that it's not an obvious default value, as it was [noted](https://github.com/python/cpython/issues/81359#issuecomment-1093825749) by @serhiy-storchaka in #81359.  IMHO, even less obvious than [the log case](https://github.com/python/cpython/issues/89381#issuecomment-1407781805), where that was an issue.
