### ISSUE TITLE
Wrong example for range slice in documentation

### ISSUE THREAD

**Issue by denvov** [python/cpython#101582]
# Documentation

The second code example for Range has wrong output for slice https://docs.python.org/3/library/stdtypes.html#ranges
r = range(0, 20, 2)

Now wrong:
```
>>> r[:5]
range(0, 10, 2)
```

Should be:
```
>>> r[:5]
range(10, 20, 2)
```

**Comment by rhettinger** [comment]
Why do you expect `range(10, 20, 2)`?

I get exactly what the current docs say we should:


```
% python3.11
Python 3.11.1 (v3.11.1:a7a450f84a, Dec  6 2022, 15:24:06) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> r = range(0, 20, 2)
>>> r[:5]
range(0, 10, 2)
```

**Comment by mdickinson** [comment]
I believe it's correct as written. Here's what I get at a prompt:

```python
Python 3.10.9 (main, Dec  7 2022, 02:03:23) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> r = range(0, 20, 2)
>>> r[:5]
range(0, 10, 2)
```

Do you get something different?

**Comment by arhadthedev** [comment]
@denvov `r[:5]` means "get *first* five elements of the sequence", not *last*. You confused `r[:5]` with `r[-5:]`.

**Comment by denvov** [comment]
My bad. You are totally right. 

> @denvov `r[:5]` means "get _first_ five elements of the sequence", not _last_. You confused `r[:5]` with `r[-5:]`:
> 
> ```
> >>> range(0, 20, 2)[-5:]
> range(10, 20, 2)
> >>> range(0, 20, 2)[:5]
> range(0, 10, 2)
> ```
