### ISSUE TITLE
`_PyStaticType_Dealloc` does not invalidate type version tag

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#101696]
`_PyStaticType_Dealloc` does not invalidate the type version tag and when the interpreter is reinitialized it still points to the old index. It should be cleared after the runtime finalization to avoid a rare case where there is a cache hit from the old index. 

Found while working on https://github.com/python/cpython/actions/runs/4112993949/jobs/7098592004

### Linked PRs
* gh-101697
* gh-101722
* gh-101742

**Comment by kumaraditya303** [comment]
I'll file PR shortly. 

cc @ericsnowcurrently @erlend-aasland

**Comment by erlend-aasland** [comment]
Good job debugging that! 👏🏻👏🏻👏🏻

**Comment by markshannon** [comment]
Given that static types should be immutable and immortal, I think a better approach would be reserve low values (up to a 1000 or so) for static classes. Once allocated, a static type would keep the same version number for the lifetime of the process.

It might be handy to pre-allocate a few values for the most common types, but that's not necessary for correctness.

**Comment by kumaraditya303** [comment]
> Given that static types should be immutable and immortal, I think a better approach would be reserve low values (up to a 1000 or so) for static classes. Once allocated, a static type would keep the same version number for the lifetime of the process. It might be handy to pre-allocate a few values for the most common types, but that's not necessary for correctness.

Yeah, it makes sense and is on my todo list for a long time See https://github.com/python/cpython/issues/95795

**Comment by ericsnowcurrently** [comment]
@erlend-aasland, your patch seems correct.  I was going to ask what's the goal of your fix, since the merged fix addressed the originally described failure and gh-95795 addresses the rest.  However, I think your fix might also deal with non-builtin static types (e.g. from community extension modules), which would probably be worth fixing too (regardless of how remote the possible failure).

I have some additional feedback, but I can wait until you've made a PR.  (Feel free to request a review from me.)

**Comment by erlend-aasland** [comment]
Thanks for the comment, @ericsnowcurrently. I've alredy made a PR; I've requested your review. The PR is slightly different from my proposed patch here. I would also like to add some additional asserts, for example in `PyType_Modified` and `assign_version_tag` (naming might differ; I'm on my phone right now.)

**Comment by erlend-aasland** [comment]
As for the goal, I think Mark's reasoning is correct; making sure all immutable types have a lifelong (and immutable) valid version feels more correct than a fixup during finalise.

**Comment by kumaraditya303** [comment]
> As for the goal, I think Mark's reasoning is correct; making sure all immutable types have a lifelong (and immutable) valid version feels more correct than a fixup during finalise.

That's the ideal goal yes but your PR only achieve valid version for only one cycle [^1] of interpreter initialization, it is reset as `PyType_Ready` is called on every cycle so not quite same as valid across the whole process lifetime. One side-effect is that it will now reset the tag for extension modules too which I avoided in my PR but I don't see any issues with doing that either. 

https://github.com/python/cpython/issues/95795 is the complete solution for this, there is a lot of info about this in that thread.
[^1]: This is same as status quo with https://github.com/python/cpython/pull/101697

**Comment by erlend-aasland** [comment]
True, Kumar, my PR is not a complete solution.

**Comment by kumaraditya303** [comment]
> However, I think your fix might also deal with non-builtin static types (e.g. from community extension modules), which would probably be worth fixing too (regardless of how remote the possible failure).

Actually https://github.com/python/cpython/pull/101742 does *not* does this. The reason is that once a type is initialized via  `PyType_Ready` it is never deallocated (in the sense that the `tp_dict` and other things are never cleared) and if the interpreter is reinitialized then it uses the same old initialized type. `PyType_Ready` returns early if type is already initialized by previous interpreter.

https://github.com/python/cpython/blob/d40a23c0a11060ba7fa076d50980c18a11a13a40/Objects/typeobject.c#L6957-L6963

So because of this https://github.com/python/cpython/pull/101742 has no effect because that code is only called once and subsequent initializations are skipped entirely. This happens in core static types because they are deallocated and reinitialized on every cycle unlike extension modules.

**Comment by ericsnowcurrently** [comment]
> Actually https://github.com/python/cpython/pull/101742 does not does this.

Good point.

**Comment by kumaraditya303** [comment]
The backport is merged so closing. 

>  I could give it a go, just for fun

@erlend-aasland I'd say give it a shot, the points of implementation are written here https://github.com/python/cpython/issues/95795#issuecomment-1211037989 and we can work together on this.

**Comment by erlend-aasland** [comment]
Thanks, Kumar. I'll see if I can have something for you by the next weekend.
