### ISSUE TITLE
New warning: `conversion from 'Py_ssize_t' to 'int', possible loss of data` in `Modules/_testcapimodule.c`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#101656]
<img width="910" alt="Снимок экрана 2023-02-07 в 21 22 57" src="https://user-images.githubusercontent.com/4660275/217332496-cef2e448-0522-47fc-89b1-c87c60fab42f.png">

This happens because:
- `Py_ssize_t c_args_len = 0;`
- But, `PyEval_EvalCodeEx` expects `int`:
  ```c
   PyObject *
   PyEval_EvalCodeEx(PyObject *_co, PyObject *globals, PyObject *locals,
                  PyObject *const *args, int argcount,
                  PyObject *const *kws, int kwcount,
                  PyObject *const *defs, int defcount,
                  PyObject *kwdefs, PyObject *closure)
  ```

Looks like this is a side effect of https://github.com/python/cpython/commit/ae62bddaf81176a7e55f95f18d55621c9c46c23d

Possible solution is to use an explicit `(int)` converter. 
I don't think that we should really worry about an overflow in the test code.
I will send a PR to check if this is a proper fix.

CC @ambv as the original PR reviewer.

### Linked PRs
* gh-101657
* gh-101680

**Comment by ambv** [comment]
I think the fix is to replace the Py_ssize_t variables in the test function to `int`s as this is indeed what `PyEval_EvalCodeEx` expects.

**Comment by sobolevn** [comment]
@ambv can we do that? Because, for example, `c_defaults_len` uses this code:

https://github.com/python/cpython/blob/f87f6e23964d7a4c38b655089cda65538a24ec36/Modules/_testcapimodule.c#L3165-L3170

And `PyTuple_Size` return `Py_ssize_t` 🤔

**Comment by sobolevn** [comment]
Either way, we need to convert `Py_ssize_t` to `int` at some point. I propose to do it later on :)

**Comment by ambv** [comment]
OK, that makes sense to me, too. **Let's go!**
