### ISSUE TITLE
Grammatical error in message string for `FatalError` when calling `PyImport_AppendInittab()` after `Py_Initialize()`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#101670]
The following line should have the first instance of "be" replaced with "not":

https://github.com/python/cpython/blob/aacbdb0c650492756738b044e6ddf8b72f89a1a2/Python/import.c#L2695

### Linked PRs
* gh-101672
* gh-101723

**Comment by ericsnowcurrently** [comment]
Nice catch! :)
