### ISSUE TITLE
pdb loses local variable change after command longlist

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#101673]
# Bug report

In pdb, `ll` will clear the local variable change.

```python
def main():
    a = 1
    breakpoint()
    print(a)

main()
```

```python
-> print(a)
(Pdb) p a
1
(Pdb) !a = 2
(Pdb) p a
2
(Pdb) ll
  1     def main():
  2         a = 1
  3         breakpoint()
  4  ->     print(a)
(Pdb) p a
1
(Pdb) s
1
--Return--
```

As you can tell, `a` was changed through `!a = 2` but it was reverted after `ll`. `print(a)` also prints the unmodified value. Without `ll`, everything works fine.

The reason lies in `getsourcelines` in `pdb.py`. In that function, it tried to access `obj.f_locals`, which will refresh the dict with `PyFrame_FastToLocalsWithError` as it's a property now.

```python
if inspect.isframe(obj) and obj.f_globals is obj.f_locals:
```

As a result, the local variable changes will be erased.

The original reason to check if `obj.f_globals is obj.f_locals` is to check whether `obj` is an module frame. Now that it has side effects to pdb, we can do the check with:

```python
if inspect.isframe(obj) and obj.f_code.co_name == "<module>":
```

It might not be the most delicate way, but I can't think of a situation where this won't work.

I did this change locally and I have confirmed:

1. `./python -m test -j3` passed
2. The original bug is fixed
3. `ll` still prints the full file for module frame

I'll make a PR soon and please let me know if there are any concerns about the fix.

# Your environment

- CPython versions tested on: 3.11.1
- Operating system and architecture: Ubuntu 20.04

### Linked PRs
* gh-101674
* gh-102632
* gh-102633

**Comment by gaogaotiantian** [comment]
Hi all, it's been about a month since this issue is created. I think this issue is pretty straightforward and easy to reproduce. The fix in #101674 is easy to understand and well contained. Could someone give this issue/PR a review? Thanks.

**Comment by iritkatriel** [comment]
Any bugfix PR should include a unit test to prevent regressions.

**Comment by gaogaotiantian** [comment]
Hi @iritkatriel , thank you for the reminder! I've added the regression test for this bug - I confirmed that the test fails without the fix and passes with the fix.
