### ISSUE TITLE
Cannot import extensions linked against `python3_d.dll` debug build on Windows

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#101614]
# Bug report

Build a debug version of CPython on Windows.
Build an an extension module linked against this debug CPython's `python3_d.dll`.

This crashes at runtime with the following error:

```
ImportError: Module use of python3_d.dll conflicts with this version of Python.
```

This originates from https://github.com/python/cpython/blob/7a253103d4c64fcca4c0939a584c2028d8da6829/Python/dynload_win.c#L311-L330

It looks like this code doesn't account for the possibility of linking against `python3_d.dll` when using a debug build.

# Your environment

- CPython versions tested on: main branch, 7a253103d4
- Operating system and architecture: Windows 12 amd64

Originally reported to me in https://github.com/PyO3/pyo3/issues/2780

### Linked PRs
* gh-101615
* gh-101690
* gh-101691

**Comment by hugovk** [comment]
Thanks for the fixes!
