### ISSUE TITLE
enum.Flag: default for boundary is incorrect

### ISSUE THREAD

**Issue by huwcbjones** [python/cpython#101739]
In c9480d5ad59b052ad3d3422fcf0ac8dd5fed7f6d the default was changed from `STRICT` to `CONFORM`, but the docs were never updated to reflect this.
See https://docs.python.org/3.11/library/enum.html#enum.FlagBoundary

> STRICT
>    Out-of-range values cause a [ValueError](https://docs.python.org/3.11/library/exceptions.html#ValueError) to be raised. This is the default for [Flag](https://docs.python.org/3.11/library/enum.html#enum.Flag):

### Linked PRs
* gh-101746
* gh-102004

**Comment by hauntsaninja** [comment]
Thanks!
