### ISSUE TITLE
iter `__reduce__` can segfault if accessing `__builtins__.__dict__['iter']` mutates the iter object

### ISSUE THREAD

**Issue by ionite34** [python/cpython#101765]
# Crash report

Example from @chilaxan
```python
corrupt = iter(lambda:0, 0)

class Cstr:
    def __hash__(self):
        return hash('iter')
    def __eq__(self, other):
        [*corrupt]
        return other == 'iter'

builtins = __builtins__.__dict__ if hasattr(__builtins__, '__dict__') else __builtins__
oiter = builtins['iter']
del builtins['iter']
builtins[Cstr()] = oiter

print(corrupt.__reduce__())
```

# Expected result
This should return a valid `__reduce__` tuple of the exhausted iterator. Instead behavior is inconsistent between segmentation faults, SystemErrors, and sometimes returning the iterator without being exhausted.

# Error messages

- 3.11, windows, `PYTHONMALLOC=debug`
- 3.12.0a4, windows, `PYTHONMALLOC=debug`
```py
Windows fatal exception: access violation
> exit code -1073741819 (0xC0000005)
```

- 3.12.04a4, windows, compiled with debug mode
```py
    print(corrupt.__reduce__())
          ^^^^^^^^^^^^^^^^^^^^
SystemError: NULL object passed to Py_BuildValue
```

- 3.11, ubuntu
```py
(<built-in function iter>, (<function  at 0x7fb772c3c4a0>, 0))
> terminated by signal SIGSEGV (Address boundary error)
```
- 3.12.0a4, ubuntu
```py
(<built-in function iter>, (<function  at 0x7f3480d71f80>, 0))
```
- 3.12.0a4, ubuntu, `PYTHONMALLOC=debug`
```py
Fatal Python error: Segmentation fault
```

### Linked PRs
* gh-101769
* gh-102228
* gh-102229
* gh-102265
* gh-102268
* gh-102269
* gh-102283
* gh-102285
* gh-102286

**Comment by godlygeek** [comment]
This (horrific) reproducer provokes poorly defined behavior from this statement: https://github.com/python/cpython/blob/f1f3af7b8245e61a2e0abef03b2c6c5902ed7df8/Objects/iterobject.c#L243-L244 

The call to `_PyEval_GetBuiltin` to find the `iter` builtin is calling `Cstr.__eq__`, which exhausts the iterator, causing the `Py_CLEAR` in `calliter_iternext` to be executed, setting `it->it_callable` and `it->it_sentinel` to NULL. But the order of evaluation of arguments in a function call isn't specified, and modifying an argument by evaluating another argument is a bug.

On some platforms, `it->it_callable` and `it->it_sentinel` are being evaluated before `_PyEval_GetBuiltin`, and so `Py_BuildValue` is being passed pointers to objects that got freed inside the `_PyEval_GetBuiltin` call`
