### ISSUE TITLE
Isolate the _curses extension module

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#101714]
# Feature or enhancement

Isolate the `_curses` extension module. This means turning most global variables into module state variables.

Globals in the `_curses` extension module:

| Name | C type | Notes |
| --- | --- | --- |
| PyCursesVersion | const char[] | Hard-coded C string; can remain a global |
| PyCursesError | PyObject \*  |
| initialised\_setupterm | int | Tells whether `setupterm()` has been called to initialise `terminfo` |
| initialised | int | Tells whether `initscr()` has been called to initialise curses |
| initialisedcolors | int | Tells whether `start_color()` has been called to initialise color usage |
| screen\_encoding | int |
| PyCursesWindow_Type | PyTypeObject \* | Must convert to heap type |
| ModDict | PyObject \* |

There is also a capsule with a C API. I'm not sure if this needs special handling wrt. PEP-489, but the \_curses C API exposes three of the global variables[^1] directly. That said, those three variables are all guards for curses specific initialisation; it may make sense to keep these variables global; I don't know yet. The capsule C API also uses the \_curses exception object (`curses.error`). Altering or removing the \_curses C API is a breaking change and must follow the deprecation cycle of PEP-387.

Apart from the capsule C API issues, converting the remaining global variables to module state variables seem to be an easy task; most of them are used in either module functions or class methods. We can store the state in the `PyCursesWindow_Type` object for easy access and minimal churn.

# Pitch

This is needed in order to support a per-interpreter GIL.

# Previous discussion

https://github.com/ericsnowcurrently/multi-core-python/wiki/0-The-Plan

[^1]: `initialised_setupterm`, `initialisedcolors`, and `initialised`

### Linked PRs
* gh-104732

**Comment by chgnrdv** [comment]
@erlend-aasland, don't mind if I work on this one? :)

**Comment by erlend-aasland** [comment]
> @erlend-aasland, don't mind if I work on this one? :)

Sure, go ahead; I don't have time for this at the moment.

**Comment by erlend-aasland** [comment]
There might be a WIP PR open by me. Feel free to pick up where I left.

**Comment by chgnrdv** [comment]
@erlend-aasland, sorry, I can't find any. It's not a problem though, because I almost finished my own work and will submit a PR soon (I hope so).

**Comment by erlend-aasland** [comment]
Nice. You can ping me and `@kumaraditya303` when you're ready.

**Comment by erlend-aasland** [comment]
I'm not sure it is worth it isolating `_curses`; is there a real use case where one would run `curses` any other place than the main interpreter? See also https://github.com/python/cpython/issues/103092#issuecomment-1557521174.

I think we should consider just leaving it as it is.

cc. @ericsnowcurrently

**Comment by ericsnowcurrently** [comment]
Yeah, the status quo is: it won't get imported in isolated subinterpreters.  That should be fine.

**Comment by erlend-aasland** [comment]
Yep. Closing as wont-fix.
