### ISSUE TITLE
Document that `os.environ` forcibly upper-cases keys on case-insensitive OSs

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#101754]
# Documentation

[`os.environ` docs](https://docs.python.org/3/library/os.html?highlight=os%20environ#os.environ) don't mention that the keys get upper-cased automatically on e.g. Windows.

### Linked PRs
* gh-101840
* gh-102393
* gh-102394

**Comment by karrtikr** [comment]
Source code: https://github.com/python/cpython/blob/f1f3af7b8245e61a2e0abef03b2c6c5902ed7df8/Lib/os.py#L755

**Comment by eryksun** [comment]
Note that it wouldn't be hard to make `os.environ` case insensitive but case preserving, starting with Python 3.12 or 3.13. I discussed a possible implementation in issue #73010.
