### ISSUE TITLE
urllib.error.HTTPError: does not document constructor/all properties

### ISSUE THREAD

**Issue by ngie-eign** [python/cpython#101724]
# Documentation

The pydoc for urllib.error.HTTPError doesn't document the following properties:
- fp
- msg

Moreover, the constructor is not documented.

I only discovered what these properties were when I tried to initialize a `urllib.error.HTTPError` in standalone code to mimic py-requests.

The constructor and additional properties should be documented.

**Comment by sobolevn** [comment]
Closing as a duplicated of https://github.com/python/cpython/issues/101536
