### ISSUE TITLE
Use a range of years for copyright in LICENSE

### ISSUE THREAD

**Issue by Stevoisiak** [python/cpython#101705]
# Documentation

Most [copyright notices in cpython](https://github.com/python/cpython/commit/11f99323c2ae0ec428c370a335695e3d8d4afc1d) use a range of years.

https://github.com/python/cpython/blob/616aec1ff148ba4570aa2d4b8ea420c715c206e4/Doc/license.rst?plain=1#L103-L105

The LICENSE file is an exception.

https://github.com/python/cpython/blob/616aec1ff148ba4570aa2d4b8ea420c715c206e4/LICENSE#L86-L89

Similar to how the README was simplified in #10287, the LICENSE should use a range of years for readability and consistency.

### Linked PRs
* gh-101706

**Comment by hugovk** [comment]
Fixed in https://github.com/python/cpython/pull/113608, thanks for the report and the initial PR!

**Comment by pombredanne** [comment]
FWIW, updating copyright years every year does not make sense and is IMHO useless churn that has zero legal value and has zero technical value.
