### ISSUE TITLE
impaplib's IMAP4 last example does not use the 'host' parameter which leads to a crash

### ISSUE THREAD

**Issue by LilKS** [python/cpython#101760]
# Documentation

When using the example at the bottom of the page:
```python
import getpass, imaplib

M = imaplib.IMAP4()
M.login(getpass.getuser(), getpass.getpass())
M.select()
typ, data = M.search(None, 'ALL')
for num in data[0].split():
    typ, data = M.fetch(num, '(RFC822)')
    print('Message %s\n%s\n' % (num, data[0][1]))
M.close()
M.logout()
```

You get a crash looking like this:
```shell
Traceback (most recent call last):
  File "/Users/bob/project/main.py", line 33, in crash_example
    M = imaplib.IMAP4()
        ^^^^^^^^^^^^^^^
  File "/Users/bob/.pyenv/versions/3.11.1/lib/python3.11/imaplib.py", line 202, in __init__
    self.open(host, port, timeout)
  File "/Users/bob/.pyenv/versions/3.11.1/lib/python3.11/imaplib.py", line 312, in open
    self.sock = self._create_socket(timeout)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/.pyenv/versions/3.11.1/lib/python3.11/imaplib.py", line 302, in _create_socket
    return socket.create_connection(address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bob/.pyenv/versions/3.11.1/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/Users/bob/.pyenv/versions/3.11.1/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused
```

Which is caused by the following line that falls back to trying to connect to a localhost IMAP server which probably does not exist.
 ```python
M = imaplib.IMAP4()
```
As is mentioned at the top of the page, you should provide your server name/address unless you are using a localhost instance. However it might not be obvious at first.

Adding a fake domain like in the first example leads to the same kind of message, but it invites the developer to at least provide their server address.
Thus I would suggest to stick to what is shown in the first example as:
 ```python
M = imaplib.IMAP4('domain.org')
```

### Linked PRs
* gh-101764
* gh-117191
* gh-117192

**Comment by LilKS** [comment]
I'll quickly provide a PR for this

**Comment by vadmium** [comment]
To connect to an external domain name, wouldn’t it be better to illustrate using SSL/TLS rather than an unencrypted connection? However then you run into the default SSL behaviour being less secure than what the documentation implies; see Issue #91826.
