### ISSUE TITLE
line number of PUSH_EXC_INFO instructions is incorrect

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#101734]
The line number of `PUSH_EXC_INFO` is that of the `try:` rather than the `except:`:

```
>>> def f():
...     try:
...        a = 1
...        1/0
...        b = 2
...     except:
...        pass
... 
>>> import dis
>>> dis.dis(f)
  1           0 RESUME                   0

  2           2 NOP

  3           4 LOAD_CONST               1 (1)
              6 STORE_FAST               0 (a)

  4           8 LOAD_CONST               1 (1)
             10 LOAD_CONST               2 (0)
             12 BINARY_OP               11 (/)
             16 POP_TOP

  5          18 LOAD_CONST               3 (2)
             20 STORE_FAST               1 (b)
             22 RETURN_CONST             0 (None)

  2     >>   24 PUSH_EXC_INFO

  6          26 POP_TOP

  7          28 POP_EXCEPT
             30 RETURN_CONST             0 (None)

  2     >>   32 COPY                     3
             34 POP_EXCEPT
             36 RERAISE                  1
ExceptionTable:
  4 to 20 -> 24 [0]
  24 to 26 -> 32 [1] lasti

```

### Linked PRs
* gh-101740

**Comment by markshannon** [comment]
Should `PUSH_EXC_INFO` have a line number at all?
It seems artificial to me.

Likewise for the immediately following `POP_TOP` and `POP_EXCEPT` in the example above.

**Comment by iritkatriel** [comment]
If we don’t assign a line number then we later propagate to it the line number of the previous instruction. We don’t have anything like ‘this does not have a line number’. Only ‘it doesn’t have a line number yet’.

**Comment by markshannon** [comment]
We only do that in basic blocks (and maybe extended blocks?) though, right?
Since the `PUSH_EXC_INFO` starts a block it shouldn't get a line number from a predecessor.

**Comment by iritkatriel** [comment]
In the dis output above the PUSH_EXC_INFO appears as if it's online 2:

`2     >>   24 PUSH_EXC_INFO`

**Comment by iritkatriel** [comment]
You're right, I was confusing myself.
