### ISSUE TITLE
Weird PriorityQueue description

### ISSUE THREAD

**Issue by pochmann** [python/cpython#101777]
# Documentation

Someone asked [Does PriorityQueue call sorted every time get is called?](https://stackoverflow.com/questions/75407200/does-priorityqueue-call-sorted-every-time-get-is-called). First I laughed, how did they come up with that silly idea, but then I saw they got it from [the doc](https://docs.python.org/3/library/queue.html#queue.PriorityQueue) and it really does make it sound like that:

> The lowest valued entries are retrieved first (the lowest valued entry is the one returned by `sorted(list(entries))[0]`).

Not only `sorted` but also `list` first, and of course even if the queue didn't use a heap, it should be the straightforward `min(entries)` instead. This is so over-the-top inefficient and complicated that it looks like a weird joke.

Unless there's good reason for it, I suggest to add "as if" and use `min`:

> The lowest valued entries are retrieved first (the lowest valued entry is the one as if returned by `min(entries)`).

### Linked PRs
* gh-102026
* gh-102106
* gh-102107
* gh-102143
* gh-102154
* gh-102155

**Comment by ericvsmith** [comment]
I'm not sure it needs to be changed, but if it must be, then I'd say something like "the one that would be returned by ...".

**Comment by pochmann** [comment]
Yes, that's better.

**Comment by Dev-satish** [comment]
hey there ! 
is that okay if i work on this issue ?

**Comment by rhettinger** [comment]
+1
