### ISSUE TITLE
Incorrect / incomplete documentation of asyncio.Server

### ISSUE THREAD

**Issue by romuald** [python/cpython#101786]
# Documentation

URL: https://docs.python.org/3.7/library/asyncio-eventloop.html#asyncio.Server.sockets

The documentation states that `sockets` is a list of `socket.socket` objects

The actual type is a list of `asyncio.trsock.TransportSocket` (that is not documented)

We should add the missing documentation to the `asyncio.trsock` module, and make the proper relationship in the `Server` section

### Linked PRs
* gh-103877
* gh-103890

**Comment by gvanrossum** [comment]
I recall stumbling over this too once. I think the intention is that TransportSocket is completely transparent (in a duck-type way :-), but the docs should not lie.

**Comment by kumaraditya303** [comment]
Maybe change it to `socket-like object` if we are not documenting the whole `TransportSocket`?

**Comment by romuald** [comment]
Many thanks!

**Comment by hauntsaninja** [comment]
Thank you for the issue! :-)
