### ISSUE TITLE
Windows embedable package (ARM64) cannot load modules and does not respect PYTHONPATH

### ISSUE THREAD

**Issue by Blackhex** [python/cpython#101867]
# Steps to reproduce

1. Download any "Windows embedable package (ARM64)", e.g. the latest one https://www.python.org/ftp/python/3.12.0/python-3.12.0a5-embed-arm64.zip.
2. Unzip it on Windows Arm64 machine.
3. Set `PYTHONPATH` environment variable e.g. to `C:\Projects`
4. Run `C:\Users\radekbarton\Downloads\python-3.12.0a5-embed-arm64\python.exe -c "import sys; print(sys.path)"`

# Actual result
```
['C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64\\python312.zip', 'C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64']
```

# Expected result
```
['', 'C:\\Users\\radekbarton\\Projects', 'C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64\\python312.zip', 'C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64\\DLLs', 'C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64\\Lib', 'C:\\Program Files\\Python312-arm64', 'C:\\Users\\radekbarton\\Downloads\\python-3.12.0a5-embed-arm64\\Lib\\site-packages']
```
# Notes

This issues implies that no Python project local modules can be imported and no other Python modules can be installed e.g with `python -m pip install` even after installing pip with `get-pip.py`. The same works as expected with both "Windows installer (ARM64)"(https://www.python.org/ftp/python/3.12.0/python-3.12.0a5-arm64.exe) on Arm64 machine, or "Windows embeddable package (64-bit)" (https://www.python.org/ftp/python/3.12.0/python-3.12.0a5-embed-amd64.zip) on x64 machine. I am keen to help with the issue fix, I'd just invite some hints where to start.

**Comment by arhadthedev** [comment]
@python/windows-team

**Comment by zooba** [comment]
Please review the documentation for this distro and see whether that helps: https://docs.python.org/3/using/windows.html#windows-embeddable

If you want something that can be installed and used as part of a CI system, I suggest the Nuget packages: https://docs.python.org/3/using/windows.html#windows-nuget

**Comment by Blackhex** [comment]
@zooba Thank you for your reaction.

Hmm, it seems that I've accidentally used [https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/python-3.9.2-1-embed-amd64+pywin32.zip](https://storage.googleapis.com/webassembly/emscripten-releases-builds/deps/python-3.9.2-1-embed-amd64+pywin32.zip) package for the x64 comparison which might be somewhat modifed to include `PYTHONPATH` and local working directories to the `sys.path`. Sorry for that.

What the documentation does not cover is how is one supposed to import local modules which, I believe, is a common use case?

C:\\Projects\\test\\main.py:

```
import sys

print(sys.path)

import test

test.test("Test")
```

C:\\Projects\\test\\test.py:

```
def test(what):
    print(what)
```

C:\\Projects\\test> python-3.9.2-embed-amd64\\python.exe main.py:

```
['python-3.9.2-embed-amd64\\python39.zip', 'python-3.9.2-embed-amd64']
Traceback (most recent call last):
 File "C:\Projects\test\main.py", line 5, in <module>
   import test
ModuleNotFoundError: No module named 'test'
```

The only way how to enable this, I have found, is adding the current working dir to the `sys.path`:

```
sys.path.append('C:\\Projects\\test')
```

**Comment by zooba** [comment]
Yes, the intended approach is to add the search path to `sys.path` (most likely by modifying the `python._pth` file). I'll take a look and see if that can be made more obvious.

**Comment by Blackhex** [comment]
@eryksun Thank you. That certainly brought a light to understanding what is going on.

**Comment by zooba** [comment]
Yeah, all the pieces are definitely documented, but clearly we can make the connection more obvious. This is the second "issue" I've responded to today about the embedded distro, both with the same root cause (specifically: "I think I don't have permission to change the search path")
