### ISSUE TITLE
Incorrect SyntaxError when using nonlocal and global in if/else

### ISSUE THREAD

**Issue by thefairytalelibrary** [python/cpython#101801]
# Bug report

Python interpreter throws a SyntaxError when specifying global variable and nonlocal variable in if/else statement, stating that you can't have a variable be both nonlocal and global.  Since an if/else can only ever choose one of the options, I believe that this should not generate a SyntaxError because, through proper execution of the if statement, only either global var1 will be chosen or nonlocal var1 will be chosen, not both.

```
def func1():
	if True:
		global var1
	else:
		nonlocal var1
```

**Error:** SyntaxError: name 'var1' is nonlocal and global

# Your environment
IDLE Shell 3.9.6 using Python 3.9.6
Windows 10 Version 21H2 (OS Build 19044.2486)

**Comment by ericvsmith** [comment]
Because the compiler needs to know if a variable is global/local/nonlocal in order to generate the correct bytecode, you can't change which it is based on a runtime condition.

This is heavily "baked in" to Python, and isn't going to change.
