### ISSUE TITLE
Doc: content of availability directive lost in i18n

### ISSUE THREAD

**Issue by jeanas** [python/cpython#101845]
# Bug report

See https://git.afpy.org/AFPy/python-docs-fr/issues/28

For example, take the `os.getgid` function. https://docs.python.org/3/library/os.html#os.getgid reads

"""
os.getgid()

Return the real group id of the current process.

[Availability](https://docs.python.org/3/library/intro.html#availability): Unix.

The function is a stub on Emscripten and WASI, see [WebAssembly platforms](https://docs.python.org/3/library/intro.html#wasm-availability) for more information.
"""

However, the French translation reads

"""
os.getgid()

Renvoie l'identifiant de groupe réel du processus actuel.

[Disponibilité](https://docs.python.org/fr/3/library/intro.html#availability) : Unix.
"""

This is unexpected. When a paragraph is not translated yet, the original is normally shown. Here, it is dropped.

Not only does this lose content, but it leads to build failures when warnings are turned into errors because the translation can lose some references.

CC @tiran (commit e3b6ff19aaa318a813130ba9ad2ab0a332f27feb)

### Linked PRs
* gh-101846
* gh-101852

**Comment by hauntsaninja** [comment]
Thanks!
