### ISSUE TITLE
Duplicated st_ino calculation

### ISSUE THREAD

**Issue by juria90** [python/cpython#101810]
# Feature or enhancement
The `status->st_ino = (((uint64_t)info.nFileIndexHigh) << 32) + info.nFileIndexLow;` in function `_Py_fstat_noraise()` in file `Python/fileutils.c` is already calculated and assigned in the function `_Py_attribute_data_to_stat()` in same file.
So I'm proposing removing the duplicated code.

# Pitch
It's a duplicated code that is already done in the previous function call `_Py_attribute_data_to_stat()`.

# Previous discussion

### Linked PRs
* gh-101811

**Comment by eryksun** [comment]
This redundant calculation has been in the source for a very long time. :flushed:

In 3.1, `attribute_data_to_stat()` in "Modules/posixmodule.c" was based on a `WIN32_FILE_ATTRIBUTE_DATA` record, and `win32_fstat()` didn't use `attribute_data_to_stat()`. 

In 3.2, `attribute_data_to_stat()` was updated to use a `BY_HANDLE_FILE_INFORMATION` record, and `win32_fstat()` was updated to call `attribute_data_to_stat()`. A redundant `st_ino` calculation was left in place, however. 

In 3.5, `win32_fstat()` was moved to `_Py_fstat_noraise()` in "Python/fileutils.c", but apparently no one noticed the redundant calculation.
