### ISSUE TITLE
Windows Launcher MSI package has wrong version in 3.11.2, breaks upgrade from 3.11.0, .1

### ISSUE THREAD

**Issue by chrullrich** [python/cpython#101849]
# Bug report

The upgrade from Python 3.11.1 to 3.11.2 on Windows fails because the launcher package refuses to downgrade itself. That it believes a downgrade to be involved in the installation is surprising. The reason is that the official 3.11.1 installers (at https://www.python.org/downloads/windows/) contain a `launcher.msi` with ProductVersion 3.11.8009.0, while the 3.11.2 installers' `launcher.msi` has version 3.11.2150.0.

The same package in the 3.11.0 installers has version 3.11.7966.0.

Installation log:

    Action start 17:08:12: LaunchConditions.
    MSI (s) (50:88) [17:08:12:404]: Note: 1: 2205 2:  3: Error 
    MSI (s) (50:88) [17:08:12:404]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
    MSI (s) (50:88) [17:08:12:404]: Product: Python Launcher -- A newer version of the Python launcher is already installed.
    
    A newer version of the Python launcher is already installed.
    Action ended 17:08:12: LaunchConditions. Return value 3.
    Action ended 17:08:12: INSTALL. Return value 3.

- MSI from the 3.11.2 x64 installer:
![image](https://user-images.githubusercontent.com/4695907/218324445-3f8b8b04-0774-40f1-85a8-0c5df32b5126.png)
- MSI from the 3.11.1 x64 installer:
![image](https://user-images.githubusercontent.com/4695907/218324600-b1f68dc6-b103-4ad7-bd29-732a80955f99.png)

The situation is the same with the x86 installers.

# Ceterum censeo

This bug would have been avoided by using (a single) MSI as the distribution package format because it would have had one ProductVersion rather than somewhere between 12 and 23.

### Linked PRs
* gh-101877
* gh-101889

**Comment by arhadthedev** [comment]
@zooba (as an active committer into `Tools/msi`)
