### ISSUE TITLE
Improve Enum `__new__` error messages

### ISSUE THREAD

**Issue by SimpleArt** [python/cpython#101818]
# Documentation

Recently I stumbled upon a bug caused by a combination of `enum.Enum` and `__new__` in #101809. To summarize, in Python 3.8, using multiple inheritance with a generic and an enum such as

```python
class Bar(Foo[int], Enum):
    x = 0
```

results in the error

```
Traceback (most recent call last):
  ...
ValueError: 0 is not a valid Bar
```

This proposal is to have a clearer error message, such as

```
<function Generic.__new__ at ...> returned an 'int', not a 'Bar', perhaps you meant to use _missing_?
```

The only use case I know of for modifying `__new__` when using `Enum` are currently covered by `_missing_` (namely enum members which have multiple value aliases).

**Comment by SohamMane19** [comment]
@SimpleArt Hey i am a beginner to open source ,can you guide me through this issue?

**Comment by arhadthedev** [comment]
@SohamMane19 You can start with the contributor's manual (https://devguide.python.org/).

**Comment by Dev-satish** [comment]
@arhadthedev Mind if I give it a shot?

**Comment by arhadthedev** [comment]
@Dev-satish Uh... Sure?

**Comment by ethanfurman** [comment]
> The only use case I know of for modifying `__new__` when using `Enum` are currently covered by `_missing_` (namely enum members which have multiple value aliases).

`__new__` is used any time one wants a custom member or custom creation:
- add attributes
- automatic numbering of values (before `auto()`)
- value verification
- linking members together (think roshambo (rock, paper, scissors))
- etc.

---

I think `_missing_` is irrelevent here, but the error message could be improved.

**Comment by ethanfurman** [comment]
Actually, reviewing the sequence of events that leads to that error, I don't see a way for `Enum.__new__` to know it's being called at the wrong time (see #101809 for specifics), so making the error message appropriate for that situation is not possible.
