### ISSUE TITLE
Set: `set_richcompare` doesn't coverage case when `v` points to a non-set object

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#101834]
[Current implementation](https://github.com/python/cpython/blob/main/Objects/setobject.c#L1787) of `set_richcompare` will be failed with segfault, when `v` points to a non-set object
```c
if(!PyAnySet_Check(w))
        Py_RETURN_NOTIMPLEMENTED;
```
There's should be check for `v` object also.

### Linked PRs
* gh-101835

**Comment by chilaxan** [comment]
Is it possible to pass a non-set object into that function as `v`?

**Comment by Eclips4** [comment]
> Is it possible to pass a non-set object into that function as `v`?

Yep. `PySet_Type->tp_richcompare(non_set_obj, ...)`

**Comment by chgnrdv** [comment]
Doesn't this check in `do_richcompare`
https://github.com/python/cpython/blob/dfc2e065a2e71011017077e549cd2f9bf4944c54/Objects/object.c#L653
rules out any possibility for `v` to point to a non-set object? For `w` in `set_richcompare` guaranteed to point to `set` object the use of `PyAnySet_Check` looks redundant to me:
https://github.com/python/cpython/blob/7546914e3f8157d8bad2998677e0ea3ed4cb7939/Include/setobject.h#L30-L33
(correct me if I'm wrong :-))

**Comment by Eclips4** [comment]
Yep. You're right
