### ISSUE TITLE
Weird matching on sets

### ISSUE THREAD

**Issue by isaacl** [python/cpython#101878]
# Bug report

While attempting to use `match` to extract an element from a singleton set, I stumbled across a weird matching pattern:

```python
s = set('A')
match s:
    case set(x):
        print(x is s)  # Prints True
```

For some reason, the `x` variable gets assigned to the collection itself, instead of the contents.  Is this intended? 

cpython 3.11.1

**Comment by ronaldoussoren** [comment]
This is intentional behaviour, PEP 622 mentions:

> For the most commonly-matched built-in types (bool, bytearray, bytes, dict, float, frozenset, int, list, set, str, and tuple), a single positional sub-pattern is allowed to be passed to the call. Rather than being matched against any particular attribute on the subject, it is instead matched against the subject itself. This creates behavior that is useful and intuitive for these objects:
>

> bool(False) matches False (but not 0).
> tuple((0, 1, 2)) matches (0, 1, 2) (but not [0, 1, 2]).
> int(i) matches any int and binds it to the name i.

**Comment by isaacl** [comment]
this is weird, but OK!  ty
