### ISSUE TITLE
method-chain style list operation like polars or LINQ in C#

### ISSUE THREAD

**Issue by Dixhom** [python/cpython#101844]
# Feature or enhancement

A method-chain style list operation like polars or LINQ in C#.

# Pitch

Because a method chain is considered more readable, less error-prone and more maintainable.

## examples

```
a =  [1,2,3]
a.filter(lambda x: x > 1) # [2, 3]

a.orderby(ascending=False) # [3,2,1]

a.reverse() # [3,2,1]

b = [1, [2, 3, [4]]]
b.flatmap(lambda x: x * 2) # [2, 4, 6, 8]

a.take(1) # [1]
a.skip(2) # [3]
a.take(2).skip(1) # [2]
```

Some of the above can be achieved by list comprehension anc slicing. However, the method chain would offer more unified way of processing lists.

# Previous discussion

This is all I could find, which is irrelevant.
Support method chaining in pathlib - Ideas - Discussions on Python.org
https://discuss.python.org/t/support-method-chaining-in-pathlib/7716

**Comment by taleinat** [comment]
Suggestions like this are best proposed and discussed on the [Ideas category on the Python discourse](https://discuss.python.org/c/ideas/6) or in [the python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/).

Adding this feature to built-in Python collection types, as shown in the example, would greatly break backwards-compatibilty. I greatly doubt this would be accepted.

@Dixhom, are you familiar with [funcy-chain](https://github.com/taleinat/funcy-chain) and [pydash](https://github.com/dgilland/pydash) libraries, which support this style of programming?

**Comment by Dixhom** [comment]
@taleinat Hi, thank you for your comment. Now I realized my suggestion was not very realistic and your library funcy-chain will do the job I want. Let me close this issue.
