### ISSUE TITLE
Remove deprecated `cgi.log`

### ISSUE THREAD

**Issue by hugovk** [python/cpython#101850]
Remove `cgi.log`, deprecated in 3.10 and slated for removal in 3.12:

* https://docs.python.org/3.10/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/issues/85311
* https://github.com/python/cpython/pull/25625

Use `logging` instead.

---

[Searching the top 5k PyPI projects](https://dev.to/hugovk/how-to-search-5000-python-projects-31gk) (downloaded 2022-11-06), the only result is the pylint deprecation checker:

```console
$ python ~/github/misc/cpython/search_pypi_top.py . "cgi\.log" -q
./pylint-2.15.5.tar.gz: pylint-2.15.5/pylint/checkers/stdlib.py: "cgi.log",

Time: 0:00:16.167385
Found 1 matching lines in 1 projects
```
```console
$ python ~/github/misc/cpython/search_pypi_top.py . "from cgi import.*log" -q

Time: 0:00:15.740342
Found 0 matching lines in 0 projects
```

### Linked PRs
* gh-101851

**Comment by ethanfurman** [comment]
@hugovk Thank you for the patch; however, the entire cgi module will be removed in 3.13 so I don't see any reason to cause extra code churn in 3.12.
