### ISSUE TITLE
marshal: `r_PyLong` result can be `PyObject *` which casted to `NULL`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#101897]
https://github.com/python/cpython/blob/e5da9ab2c82c6b4e4f8ffa699a9a609ea1bea255/Python/marshal.c#L828-L829

I think, we should add a check, that `_PyLong_New(0)` didn't return `NULL`
If so, i will send a PR.

**Comment by sobolevn** [comment]
Can you please also provide a reproducer of this crash?

You can cast `NULL` to `(PyObject *)`, it won't crash (using another piece of code for a better example):

```c
static PyObject *
dict_clear(PyDictObject *mp, PyObject *Py_UNUSED(ignored))
{
    PyErr_SetString(PyExc_ValueError, "example");
    return (PyObject *)NULL;
}
```

It produces:

```python
>> {}.clear()
ValueError: example
```

And we don't perform any other actions on the returned value. So, it looks like it is safe.

**Comment by Eclips4** [comment]
I have investigated `r_object` more thoroughly, and you were totally right. Thanks!
