### ISSUE TITLE
`co_lnotab` must be removed in 3.12 according to PEP 626

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#101865]
> The co_lnotab attribute will be deprecated in 3.10 and removed in 3.12.

https://peps.python.org/pep-0626/#backwards-compatibility

It was documented as deprecated in 3.10 and to-be-removed in 3.12: https://docs.python.org/3/whatsnew/3.10.html#pep-626-precise-line-numbers-for-debugging-and-other-tools

Original issue: https://github.com/python/cpython/issues/86412

Right now CPython does not use `co_lnotab` in its source code.
But, there are two mentions of it:
1. In `gdb`: https://github.com/python/cpython/blob/6ef6915d3530e844243893f91bf4bd702dfef570/Misc/gdbinit#L60-L61 And I have no idea how it works! Some weird mix of C and some kind of a DSL / scripting language
2. In `clinic.test`: https://github.com/python/cpython/blob/6ef6915d3530e844243893f91bf4bd702dfef570/Lib/test/clinic.test#L3575 But, this is just a string-based test. So, I think it can stay there

If that's fine - I would like to do the honours.

CC @markshannon 

### Linked PRs
* gh-101866
* gh-126392
* gh-126403
* gh-126404

**Comment by markshannon** [comment]
I don't get any warning when using `co_lnotab in 3.11`, so I don't think we can remove it yet.
Don't assume everyone has read PEP 626.

We should at least warn when using it for a couple of versions, before removing it.

It isn't causing us any problems either, so there is not rush to remove it. It can wait for 3.14 or so.

**Comment by sobolevn** [comment]
Ok then, so `DeprecationWarning` it is! 👍
