### ISSUE TITLE
Add new combination of keywords: "break and continue" inside a nested loop breaks the inner and continues in the outer

### ISSUE THREAD

**Issue by ghost** [python/cpython#101935]
# Feature or enhancement

Add new combination of keywords: "break and continue" inside a nested loop breaks the inner and continues in the outer.
This could be extended to "break and break" to break inner and outer loop or even to "break and continue and continue" to break in the most inner, continue in the second most inner and continue in the outer loop"

# Pitch

We often have nested loops. Sometimes I want to continue or break the outer depending of a result of a function call in the inner. What I have to do is:

```
for index,row in tqdm(cellmesh_dataset.iterrows()):
[...]
  for gene in list_of_genes:
      tokenized_gene = tokenizer(gene)
      match_indexes = search_list_in_list(tokenized_context, tokenized_gene)
      if match_indexes == -1:
          break
        for index in match_indexes:
            for i in range(len(tokenized_gene)):
                outputs[index+i] = 1.0
  
  if match_indexes == -1:
      continue
[...]
```

What I would like to do is:
```
for index,row in tqdm(cellmesh_dataset.iterrows()):
[...]
  for gene in list_of_genes:
      tokenized_gene = tokenizer(gene)
      match_indexes = search_list_in_list(tokenized_context, tokenized_gene)
      if match_indexes == -1:
          break and continue # <--- this line now breaks the inner loop and continues in the outer
        for index in match_indexes:
            for i in range(len(tokenized_gene)):
                outputs[index+i] = 1.0
[...]
```

# Previous discussion

I have never heard of anyone discussing this.

**Comment by pochmann** [comment]
> # Previous discussion
> I have never heard of anyone discussing this.

Hmm, then why are you here? I just tried creating a feature request, and the template contained this:

> # Previous discussion
> New features to Python should first be discussed elsewhere before creating issues on GitHub,
  for example in the "ideas" category (https://discuss.python.org/c/ideas/6) of discuss.python.org,
  or the python-ideas mailing list (https://mail.python.org/mailman3/lists/python-ideas.python.org/).

**Comment by stevendaprano** [comment]
This proposed API is awful. What if you want to break out of six loops? `break and break and break and break and break and break`. I think I died a little bit inside just typing that out.

If you search for `break` on the Python-Ideas mailing list, and on Discuss, you will certainly find many previous discussions about this.

**Comment by zware** [comment]
@pochmann, @stevendaprano, please take care of your tone.  "Why are you here?" and "This proposed API is awful" are not constructive or welcoming comments.

**Comment by zware** [comment]
@r3dapple If this idea is something you want to pursue, a post to the [Ideas section of discuss.python.org](https://discuss.python.org/c/ideas/6) is the right way to get started.  Note though that there have been discussions of very similar ideas in the past that have universally been shot down; a search for "nested loops" in the Ideas section or on the python-ideas mailing list archives might be instructive.

**Comment by pochmann** [comment]
@zware I did, and you misquoted me.

**Comment by r3dapple** [comment]
> @pochmann, @stevendaprano, please take care of your tone. "Why are you here?" and "This proposed API is awful" are not constructive or welcoming comments.

I thought the same thing. After reading the responses I felt angry and sad and words like "toxic" came to mind.
I would have been enourmously discouraged in participating in the python community in the future and disappointed in the python community had it not been for your comment. Thank you.

**Comment by stevendaprano** [comment]
@zware the second line in the CoC states:

"Focusing on what is best for the community. We're respectful of the 
processes set forth in the community, and we work within them."

The processes here **clearly and obviously** include that ideas for new 
features be discussed elsewhere before creating an issue here. Do you 
think that @r3dapple completely ignoring that process is respectful?

That process exists for a good reason: to limit the number of half-baked 
ideas on the tracker, and help insulate the core devs from burn-out from 
dealing with them.

The CoC also talks about being receptive to constructive criticism. That 
goes both ways. @r3dapple why did you ignore the instructions? Perhaps 
you would find the community less "toxic" if you were a little more 
respectful towards the community.

Even if the functionality (being able to break out of multiple loops at 
once) is desirable, the proposed interface suggested here is clunky, 
difficult to use and read, and error-prone. In other words, awful. I do 
not apologise for using that word. Criticism of the API is not criticism 
of the person.

@zware you should know that quoting out of context is unfair, unkind and 
dishonest. In context, @pochmann said nothing wrong. I think that you 
owe him an apology.

**Comment by pochmann** [comment]
@zware @stevendaprano To be clear, I didn't even mean the context of me then pointing out the template text, and how to improve their code for a better example.

What I meant is that I didn't say "Why are you here?". I said "Hmm, then why are you here?". To me, the former sounds possibly angry or even yelling. While the "Hmm" rather avoids that. You don't yell "Hmm". Instead, it's setting a calm wondering tone. Wondering whether they perhaps weren't shown that text that I then cited. Might depend on the device, who knows.

I very deliberately included that "Hmm", precisely for the tone. Then to be told "take care of your tone", with that "Hmm" being removed and the "Why" capitalized to really give the impression that the "Hmm" wasn't there... that's not ok.

**Comment by leliel12** [comment]
if "awful" is not a constructive term, all of the "zen of python" must be removed.
