### ISSUE TITLE
help(list.pop) reports it takes a named parameter called index but list.pop only takes a positional parameters.

### ISSUE THREAD

**Issue by perremba** [python/cpython#101921]
# Documentation
help(list.pop) reports it takes a named parameter called index but list.pop only takes a positional parameters.
![image](https://user-images.githubusercontent.com/34656608/218883005-c01a0952-fdec-48e5-bea3-9ea936768a95.png)

**Comment by JelleZijlstra** [comment]
The `/` notation indicates that all preceding parameters are positional-only (see PEP-570). We'd appreciate suggestions for how to communicate this information better, but the signature is using standard Python syntax and there is no bug here.
