### ISSUE TITLE
test_sqlite3 failure with SQLite 3.40.1

### ISSUE THREAD

**Issue by kulikjak** [python/cpython#101947]
Since we recently updated from SQLite 3.35.5 to 3.40.1, I am seeing the following test failure:
```
======================================================================
FAIL: test_serialize_deserialize (test.test_sqlite3.test_dbapi.SerializeTests.test_serialize_deserialize)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/.../Python-3.11.0/Lib/test/test_sqlite3/test_dbapi.py", line 607, in test_serialize_deserialize
    self.assertEqual(len(data), 8192)
AssertionError: 65536 != 8192
```

It seems that the size of serialized data changed between those two SQLite versions, causing this issue; when I remove this assert, the test passes.

This is on Oracle Solaris (both SPARC and Intel); in both 3.11.0 and the latest changes cloned from GitHub (both 3.11 and main branches).

### Linked PRs
* gh-102914
* gh-102915

**Comment by erlend-aasland** [comment]
Is there a Docker image for Solaris so I can try to reproduce this?

**Comment by kulikjak** [comment]
Sadly, there isn't an Oracle Solaris docker image available.

At first, I thought that this would be an issue on all systems, but I did some testing on RHEL yesterday and cannot reproduce it there. Let me do some more digging and I'll let you know once I find something.

**Comment by erlend-aasland** [comment]
> Sadly, there isn't an Oracle Solaris docker image available.
> 
> At first, I thought that this would be an issue on all systems, but I did some testing on RHEL yesterday and cannot reproduce it there. Let me do some more digging and I'll let you know once I find something.

Thanks; without a system to reproduce this on, I'm unable to make progress here.

**Comment by kulikjak** [comment]
I think I found the issue; It's not about Solaris/Linux platform differences, it's about the way SQLite is being compiled.

We are compiling SQLite with `-DSQLITE_DEFAULT_PAGE_SIZE=32768` on Solaris, which is much higher than the default of `4096`. When I add the same define on Linux, I can see the same issue (and when I remove it on Solaris, it's gone).

**Comment by erlend-aasland** [comment]
> We are compiling SQLite with `-DSQLITE_DEFAULT_PAGE_SIZE=32768` on Solaris, which is much higher than the default of `4096`. When I add the same define on Linux, I can see the same issue (and when I remove it on Solaris, it's gone).
> 

Thanks for debugging; that makes sense! So our test is wrong. We should compare with that constant, not some arbitrary value.
