### ISSUE TITLE
Add months and years support to datetime.timedelta for consistency with datetime.datetime

### ISSUE THREAD

**Issue by ngie-eign** [python/cpython#101938]
# Feature or enhancement

Add missing field support for `datetime.timedelta` for consistency with `datetime.datetime`.

# Pitch

The `datetime.timedelta.__init__(...)` interface doesn't support all of the fields available in `datetime.datetime.__init__(...)`. In particular, one cannot adjust dates easily using months, years, etc, and instead has to use `datetime.datetime.replace(...)`, with an adjusted reference time.

Similarly, `datetime.datetime.__init__()` doesn't support microseconds, even though `datetime.timedelta.__init__(...)` supports it.

Supporting equivalent parameters would improve the interfaces and would reduce some unnecessary boilerplate, as seen below.

### Existing Form
```
now = datetime.datetime.now()
this_day_next_year = now_dt.replace(year=now.year + 1)
```

### New (Proposed) Form
```
this_day_next_year = datetime.datetime.now() + datetime.timedelta(years=1)
```

**Comment by mdickinson** [comment]
We currently have:
```
>>> datetime.timedelta(weeks=1).days
7
```

What value would `datetime.timedelta(months=1).days` give under your proposal?

**Comment by mdickinson** [comment]
A `timedelta` represents a fixed, known, time duration, but calendar months and years don't all have the same duration. So either:

- we make `datetime.timedelta(months=1)` a fixed duration (e.g., 30 days), in which case adding `timedelta(months=1)` to a given datetime will have surprising results when the month that it's being added to _doesn't_ have 30 days, or
- we somehow relax the restriction that timedeltas are always a fixed time duration, in which case we need to entirely rethink how arithmetic and comparisons of timedeltas would work, not to mention dealing with backwards compatibliity concerns.

It's not clear to me which of the above options you had in mind, but the first doesn't seem desirable and the second, if feasible at all, would need a lot of discussion to figure out the details.

Finally, I'd note that `datetime` _does_ support microseconds:

```python
>>> datetime.datetime(2001, 2, 3, microsecond=77186)
datetime.datetime(2001, 2, 3, 0, 0, 0, 77186)
```


I'll close here, but you should feel free to open a thread at https://discuss.python.org/c/ideas if you want to discuss further.

**Comment by ngie-eign** [comment]
It's kind of interesting that timedelta is seen as a strict time quanta instead of being seen as more of a conceptual time quanta... this is honestly the first time I've seen that argument, but I haven't really dug into the implementation.
The quanta of days and weeks aren't necessarily equivalent, depending on the reference point (not all weeks are weighted equally; leap seconds and leap years play a part).

I personally feel that the proposed form in the first reply seems reasonable and that timedelta should not be taken as an atomic unit of time, but as a reference point to another time. And just like the decimal, fraction, and numbers modules/objects, the value should remain conceptual in nature until it needs to be converted to a real value -- otherwise the represented value can be incorrect (thinking of floating point math).

_(FWIW, I didn't think I was going to get so philosophical about time this morning before drinking my ☕ , but I guess this week is just one of those weeks :D...)_

**Comment by mdickinson** [comment]
> timedelta is seen as a strict time quanta that relies on a reference point

I'm not sure what you mean here - a `timedelta` is simply a time duration. There's no reference point. Think of it as simply a number of seconds (though the internal representation is in terms of microseconds, seconds and days).

And that's exactly the problem: `timedelta(months=1)` would be equal to some number of seconds. But how many? Would it be equal to `timedelta(seconds=30*24*60*60)`? Or to `timedelta(seconds=31*24*60*60)`? Or something else? Either choice seems arbitrary, and neither will give you your desired behaviour of being able to add `timedelta(months=1)` to a date and get the same day of the following month.

**Comment by ngie-eign** [comment]
@mdickinson : will do on the discuss page . What I was envisioning is roughly what you described in your second bulletpoint. The change doesn’t have a philosophical change, but it does have an implementation change, since months and years are variable compared to the other quantities (sans minutes/hours/days! You can’t forget leap seconds and the fact that a minute *technically* isn’t 60 seconds!!!). Assuming that a month is counted as 30 days, instead of 28 /29 (in the case with February) or 31 seems like it would definitely break POLA.

**Comment by mdickinson** [comment]
@ngie-eign I look forward to it! To be clear, even if the change is desirable, I'm sceptical that the proposal can be made to work without significant backwards compatibility problems. There are many questions to be answered on the details, starting with the existing (still unanswered) question of what `datetime.timedelta(months=1).days` would do under your proposal, and going on to answer questions of how arithmetic would work for this extended `timedelta`, how comparisons would work (what value would `datetime.timedelta(months=1) > datetime.timedelta(days=30.5)` give?), what to do when adding 1 month to Jan 1st of a given year, and so on. The ideas page is the right place to hash out the details, and possibly to explore other ways of solving the underlying problem (whatever that might be). We can re-open an issue here if some kind of consensus is reached there.

> You can’t forget leap seconds

Well, I think the datetime module is evidence that you can. :-) From [the docs](https://docs.python.org/3/library/datetime.html#technical-detail):

> Unlike the [time](https://docs.python.org/3/library/time.html#module-time) module, the [datetime](https://docs.python.org/3/library/datetime.html#module-datetime) module does not support leap seconds.
