### ISSUE TITLE
Misinterpretation when returning lambdas capturing dictionaries from a generator

### ISSUE THREAD

**Issue by VorpalBlade** [python/cpython#101905]
# Bug report

Sorry if I'm a bit grumpy about this. I spent a few hours debugging code the other day before I figured out what was going on and was able to make the simple test case below.

The following piece of code produces unexpected results (tested on Python 3.10 and 3.11):
```python

from functools import partial


def lambda_generator():
    for i in range(1,5):
        mapping = {'a': i}
        yield lambda x: mapping[x]

def partial_generator():
    for i in range(1,5):
        mapping = {'a': i}
        yield partial(lambda v, x: v[x], mapping)


result1 = list(lambda_generator())
result2 = list(partial_generator())

print(result1)
print(result2)

# Instances of "mapping" are shared across each iteration unless we do a partial? Huh?
print([e('a') for e in result1])
print([e('a') for e in result2])
```

I get:
```
[<function lambda_generator.<locals>.<lambda> at 0x7f6c08c744a0>, <function lambda_generator.<locals>.<lambda> at 0x7f6c08cfd1c0>, <function lambda_generator.<locals>.<lambda> at 0x7f6c08cfd260>, <function lambda_generator.<locals>.<lambda> at 0x7f6c08cfd300>]
[functools.partial(<function partial_generator.<locals>.<lambda> at 0x7f6c08cfd3a0>, {'a': 1}), functools.partial(<function partial_generator.<locals>.<lambda> at 0x7f6c08cfd440>, {'a': 2}), functools.partial(<function partial_generator.<locals>.<lambda> at 0x7f6c08cfd4e0>, {'a': 3}), functools.partial(<function partial_generator.<locals>.<lambda> at 0x7f6c08cfd580>, {'a': 4})]
[4, 4, 4, 4]
[1, 2, 3, 4]
```

I find `[4, 4, 4, 4]` highly unexpected! Since the dictionary is created anew in each iteration I would *not* expect the lambdas to share dictionary instance. In addition it looks like the lambdas are separate instances too (which makes this even more confusing).

I would expect both cases to behave like with `partial`.

# Your environment

- CPython versions tested on: Python 3.10 (compiled with pyenv and system python) and Python 3.11 (compiled with pyenv)
- Operating system and architecture: Arch Linux (rolling release distro) x86-64

**Comment by stevendaprano** [comment]
This is not a bug, it is normal behaviour.

https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

You can also [google for "Python closures late binding"](https://www.startpage.com/do/search?q=Python%20closures%20late%20binding) for more information about this.

**Comment by stevendaprano** [comment]
We can take the lambda out of the equation and use a regular `def`, unroll the loop, and you will see the exact same behaviour:

```
funcs = []

# Iteration 0
mapping = {'a': 0}
def f(x): return mapping[x]

funcs.append(f)

# Iteration 1
mapping = {'a': 1}
def f(x): return mapping[x]  # Create a new function.

funcs.append(f)

# Iteration 2
mapping = {'a': 2}
def f(x): return mapping[x]  # And another.

funcs.append(f)

print([func('a') for func in funcs])
```

When you write it like that, it is obvious why the behaviour is what it is. Using lambda is no different.

The solution to get early binding is to use partial, as you have discovered, or to take advantage of the fact that parameter default values use early binding (see the FAQ).

**Comment by VorpalBlade** [comment]
A very surprising behaviour that it doesn't bind to the object, but to the name in the parent scope of the object! I don't see any good reason for the current behaviour there. I would expect that the object reference gets captured at the time of definition, just a name and a reference to the parent scope (as seems to be the case if I understand this correctly).

Why is this? While searching turned up plenty of posts and articles stating that this is the case, none explains *why* this design was chosen and why switching to a different design wouldn't be better (apart from breaking backward compatibility, though I have a hard time imaging any useful code that depends on the current behaviour).
