### ISSUE TITLE
Docs: Name of parameter should be 'def' in PyModule_FromDefAndSpec.

### ISSUE THREAD

**Issue by c2170** [python/cpython#101973]
# Documentation

In the description of **PyModule_FromDefAndSpec** and **PyModule_FromDefAndSpec2**, the definition(PyModuleDef) parameter should be _def_, not _module_.

https://docs.python.org/3/c-api/module.html

### Linked PRs
* gh-101976
* gh-101982
* gh-101983

**Comment by erlend-aasland** [comment]
Thanks @c2170 and @arhadthedev.
