### ISSUE TITLE
`Py_EnterRecursiveCall()`/`_Py_EnterRecursiveCall()` return value misused in a number of places

### ISSUE THREAD

**Issue by OTheDev** [python/cpython#101965]
Using ``grep``, I identified 3 instances in `main` where code checks if ``Py_EnterRecursiveCall(...) < 0`` (which just returns ``_Py_EnterRecursiveCall(...)``) or ``_Py_EnterRecursiveCall(...) < 0``.

1. ``Py_EnterRecursiveCall()`` [documentation](https://docs.python.org/3/c-api/exceptions.html#c.Py_EnterRecursiveCall) only guarantees that a **nonzero** value is returned in the event of an error.
2. The actual implementation can't return a negative value:

https://github.com/python/cpython/blob/76449350b3467b85bcb565f9e2bf945bd150a66e/Include/internal/pycore_ceval.h#L130-L138

### Linked PRs
* gh-101966

**Comment by erlend-aasland** [comment]
Thanks for the report, Owain! In this case, I think we can close it as obsolete bco. Irit's patch #102078. Thanks for your interest in improving CPython :)

**Comment by erlend-aasland** [comment]
> @erlend-aasland Thanks! However, Irit's patch does not fix the instances in the bisect module. Will it be addressed there?

Well observed! Check with Irit on her PR. I'm guessing it is out of scope for her PR. In that case we'll reopen this and you can update your PR to target the remaining issues.
