### ISSUE TITLE
Set: `BUILD_SET` opcode can be failed with segfault

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#101952]
https://github.com/python/cpython/blob/36b139af638cdeb671cb6b8b0315b254148688f7/Python/generated_cases.c.h#L1648-L1667
&
https://github.com/python/cpython/blob/36b139af638cdeb671cb6b8b0315b254148688f7/Python/bytecodes.c#L1303-L1316

Doesn't take in account case, when `PySet_New(NULL)` returns NULL.
We are checking that `PySet_Add` doesn't return a non-zero(-1) value.
But, `PySet_Add` has a check, that first argument is a subclass of `set`. Which fails, if we will pass `(PyObject *) NULL` as first argument. Why?
```c
#define PySet_Check(ob) \
    (Py_IS_TYPE((ob), &PySet_Type) || \
    PyType_IsSubtype(Py_TYPE(ob), &PySet_Type))
```
`PySet_Add` uses this macross. But, `Py_TYPE` will be failed with segfault when try to access `ob_type` of `(PyObject *) NULL`.

Implementation of `Py_TYPE`:

```c
static inline PyTypeObject* Py_TYPE(PyObject *ob) {
    return ob->ob_type;
}
```

```gdb
(gdb) call (PyObject *) NULL
$1 = (PyObject *) 0x0
(gdb) call $1->ob_type
Cannot access memory at address 0x8
```
So, we should add check, that value of `PySet_New` is not-null.

### Linked PRs
* gh-101958

**Comment by kumaraditya303** [comment]
cc @gvanrossum Appears to be introduced in https://github.com/python/cpython/pull/100912/

**Comment by gvanrossum** [comment]
Yeah, the original code had
```
if (set == NULL)
                goto error;
```
which somehow got lost.

How can I repro this?

**Comment by gvanrossum** [comment]
If someone could come up with a fix I'll review it, that's the quickest way.

**Comment by Eclips4** [comment]
I can fix it, but i don't know yet how to reproduce it. I was just looking through the `bytecodes.c` file =)

**Comment by gvanrossum** [comment]
It's probably hard to repro, because the only way PySet_New() can error is if it runs out of memory. I *think* restoring those two lines will do it (nothing has been popped off the stack at that point yet).

**Comment by Eclips4** [comment]
Okay, i'll soon send a PR
