### ISSUE TITLE
itertools permutation function is incredibly slow for permutations with repeating values, and contains duplicate values.

### ISSUE THREAD

**Issue by OmreeG** [python/cpython#101972]
# Bug report
When getting all the permutations for the sequence
[1,1,1,1,1,1,1,1,1,1,2] (10 1's and 1 2), using itertools permutations, my computer ran at high speed for over a minute before I stopped it, because there should only be 11 permutations, one for each position of the number 2. I realized that the permutations function works equally for repeated values and for differing values.
This can easily be tested by running permutations with only 4 values.
```
import itertools
a = itertools.permutations([1,1,1,2])
b = list(a)
print(b)
```
Now note how many duplicates b contains. There should be only 4 permutations (one for each location of 2). Instead it returns 24 values.
In order to compute just the right amount of permutations, I wrote some sample code (in python).
I'll paste the sample code below if you're interested:
```
from typing import Dict, Any,  Set, List, Tuple
from collections import Counter
import itertools
import time


def Permutations(P: Dict[ Any, int], avail:  Set[int]) -> List[Dict[int, Any]]:
    """
    The inputs are:
        P: A Counter, going from values to number of times they appear, e.g.
        [1,1,1,2,2,4] -> {1:3, 2:2, 4:1}
        avail: Available indexes, e.g. for above:
            {0,1,2,3,4,5}
        Returns List of mapping indexes to values 
    """
    if len(P) == 0:
        return []
    # If only one item, we return 
    if len(P) == 1:
        k, v = P.popitem()
        if v != len(avail):
            return []
        res = {}
        while avail:
            res[avail.pop()] = k
        return [res]

    results: List[Dict[int, Any]] = []
    # We get a random key from the counter:
    Pcopy = P.copy()
    rndm_key, count = Pcopy.popitem()
    available_indexes: List[Set[int]] = get_avail(Pcopy, avail)
    for av_ix in available_indexes:
        SecondCopy = Pcopy.copy()
        new_ps = Permutations(SecondCopy, av_ix)
        for p in new_ps:
            remaining_indexes = avail - set(p.keys())
            mini_copy = p.copy()
            mini_copy.update({x:rndm_key for x in list(remaining_indexes)})
            results.append(mini_copy)
    return results


def get_avail(P: Dict[ Any, int], avail: Set[int]) -> List[Set[int]]:
    nTotalValues = 0
    for k, v in P.items():
        nTotalValues += v
    return [set(x) for x in list(itertools.combinations(avail, nTotalValues))]

def convert_results_to_normal_version(res: List[Dict[int, Any]]) -> List[Tuple[int]]:
    if len(res) == 0:
        return []

    tuple_size = len(res[0])
    resp = [] 
    for i in range(len(res)):
        new_tup = [None]*tuple_size 
        for k in res[i]:
            new_tup[k] = res[i][k]
        resp.append(tuple(new_tup))
    return resp

def main():
    # Examples
    a = [1,1,1,1,1,1,1,2]
    b = [1,1,1,1,2,2,2,2]
    c = [1,2,3,1,2,3,1,2]
    x = [1,2,3,4,5,6,7,8]
    l = [a,b,c,x]
    for val in l:
        print("working on", val)
        time.sleep(2)
        P = Counter(val)
        avail = set(range(len(val)))
        res = Permutations(P, avail)
        res = convert_results_to_normal_version(res)
        print("final results", res)
        print("Length of final results", len(res))
        # Time to process
        time.sleep(2)

if __name__ == "__main__":
    main()
```

**Comment by carljm** [comment]
Hi! Thanks for the report. This is not a bug, however; it is documented and intended behavior. The [documentation for itertools.permutations](https://docs.python.org/3/library/itertools.html#itertools.permutations) says: "Elements are treated as unique based on their position, not on their value. So if the input elements are unique, there will be no repeated values within a permutation."

The slowness you experienced is not due to `itertools.permutation` itself being slow. The slowness is mostly because you are probably asking Python to materialize the generator into a list, and thus to build a list with around 40 million (11!) elements in it.

If you want to generate the permutations with duplicates by value removed, `set(itertools.permutations([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2])` does that just fine, and takes only a second or two on my computer.

**Comment by OmreeG** [comment]
Hi Carl, thank you for the response!
I understand the situation and documented behavior.
I just tested to find one thing, I made comparison between itertools and my hack functions.
Got some interesting time results
```
Running on  [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2]
itertools time: 3.704195022583008
new time: 0.00016999244689941406
equal? True
Running on  [1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2]
itertools time: 3.6227798461914062
new time: 0.0035338401794433594
equal? True
Running on  [1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6]
itertools time: 4.796576023101807
new time: 17.743638038635254
equal? True
Running on  [1, 2, 3, 4, 5, 6, 7, 8, 9]
itertools time: 0.25849294662475586
new time: 7.312517881393433
equal? True
```
So it looks like the original algorithm runs much faster on varying inputs, but the new one runs much faster on inputs with more repeats. Perhaps a consideration for future implementations of the algorithm.
Thanks for looking into this

**Comment by stevendaprano** [comment]
@rhettinger what do you think about adding a `permutations_with_repetition` function to itertools? It is [a standard concept](https://brilliant.org/wiki/permutations-with-repetition/) and would be useful.

**Comment by pochmann** [comment]
@stevendaprano So standard that it already exists as [`distinct_permutations`](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.distinct_permutations) in `more_itertools`.

**Comment by rhettinger** [comment]
@stevendaprano At one point I looked adding an `anagrams()` combinatoric tool, but got push back (esp from Tim Peters) that we were venturing into feature creep.  The decision was to stop with the basic combinatorics that we have now and leave the rest to third-party libraries.
