### ISSUE TITLE
Unexpected Python's (re) regular expression matching twice with the $ symbol.

### ISSUE THREAD

**Issue by perremba** [python/cpython#101930]
# Bug report

The following code (re.sub("[\r\n]*$", "\n", "Hello World\r\n")) yields a very surprising result ('Hello World\n\n')

Testing it on other strings : 
![image](https://user-images.githubusercontent.com/34656608/218973247-008e18f7-9a4b-47d8-b3ea-cc8cb965980a.png)
 led me to the conclusion that my RE matched once on the line terminations characters+end-of-line, and a second time on the end-of-line alone (since there is a * on the previous part).
 
In my understanding of regular expressions, "[\r\n]*$" should be greedy and never match more than once. Any of those : 

- `re.sub("[\r\n]*$", "\n", "Hello World\r\n")`
- `re.sub("[\r\n]*$", "\n", "Hello World")`
- `re.sub("[\r\n]*$", "\n", "Hello World\r\n\r\n\r\r\r\n\n\n")`

should yield the same result : 
`'Hello World\n'`

# Your environment

Idle Shell 3.10.8 on Windows 10

**Comment by hugovk** [comment]
I think what is going on here, is `[\r\n]*` is also matching the null case at the end of the string.

Testing with https://regex101.com/ and using `[rn]*` to simplify a bit.

For the first test, we've got a match for both `\r\n` and the empty string at the end of the line, so two substitutions:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/1324225/218981562-f77c0bf3-5af6-4c26-8855-83155b5269fa.png)


</details>

For the second, we also get a single match for the empty string: 

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/1324225/218981825-cf6de281-cef1-4137-85fb-0b452c45f106.png)


</details>

And the third is like the first, two matches:

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/1324225/218981944-fa4b23d8-63f6-49b7-9578-347d9c06d7d0.png)


</details>

What I would do is recall ["Regular Expressions: Now You Have Two Problems"](https://blog.codinghorror.com/regular-expressions-now-you-have-two-problems/) and instead use something like `str.strip()`, `str.rstrip()` or `str.rstrip("\r\n")`:

```python
>>> "Hello World\r\n".rstrip("\r\n")
'Hello World'
>>> "Hello World".rstrip("\r\n")
'Hello World'
>>> "Hello World".rstrip("\r\n\r\n\r\r\r\n\n\n")
'Hello World'
```

https://docs.python.org/3/library/stdtypes.html#str.rstrip

**Comment by pochmann** [comment]
Not a bug.

> led me to the conclusion that my RE matched once on the line terminations characters+end-of-line, and a second time on the end-of-line alone (since there is a * on the previous part).

That is correct.

> In my understanding of regular expressions, "[\r\n]*$" should be greedy and never match more than once

They don't match more than once **at the same position**. It's absolutely normal to match multiple times, at different positions. For example, `re.sub('r', 'R', 'perremba')` gives `'peRRemba'`. Would you really expect `'peRremba'` instead?

If you insist on regex, you could use `re.sub("(?<![\r\n])[\r\n]*$", "\n", "Hello World\r\n")`. I don't see something nicer. I'd go with `"Hello World\r\n".rstrip() + "\n"`.
