### ISSUE TITLE
HTTPError fp.read returns string instead of bytes 

### ISSUE THREAD

**Issue by gaborbernat** [python/cpython#101936]
Due to https://github.com/python/cpython/pull/99966/files

However, this returns a bytes stream on the live run:

```python
from http import HTTPStatus
from mailbox import Message
from urllib.error import HTTPError
from urllib.request import urlopen

try:
    urlopen("http://asadsad.sd")
except HTTPError as exception:
    content = exception.fp.read()
    print(type(content))

error = HTTPError(url="url", code=HTTPStatus.IM_A_TEAPOT, msg="msg", hdrs=Message(), fp=None)
print(type(error.fp.read()))
```
```
<class 'bytes'>
<class 'str'>
```

### Linked PRs
* gh-102100
* gh-102117
* gh-102118

**Comment by sobolevn** [comment]
cc @corona10

**Comment by corona10** [comment]
Thanks I will take a look and I will use this issue as the internal sprint issue.

**Comment by longvhdeveloper** [comment]
I'll take it

**Comment by longvhdeveloper** [comment]
@corona10 I ran code in live run the code 
`from http import HTTPStatus
from mailbox import Message
from urllib.error import HTTPError
from urllib.request import urlopen

try:
    urlopen("http://asadsad.sd")
except HTTPError as exception:
    content = exception.fp.read()
    print(type(content))

error = HTTPError(url="url", code=HTTPStatus.IM_A_TEAPOT, msg="msg", hdrs=Message(), fp=None)
print(type(error.fp.read()))`

I am checked type of fp 
`print(exception.fp)` is
<class 'http.client.HTTPResponse'>
it is not StringIO, that mean fp is not None. And if you call read() method it will return bytes
https://github.com/python/cpython/blob/dc8a86893df37e137cfe992e95e7d66cd68e9eaf/Lib/urllib/request.py#L639
[https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse.read](https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse.read)

Do I need continue with it ?

**Comment by gaborbernat** [comment]
The title is incorrect, should be read returns string instead of bytes when fp is None.

**Comment by corona10** [comment]
@longvhdeveloper 

This script might explain better.

```python
from urllib.request import urlopen
from urllib.error import HTTPError

try:
    urlopen("https://httpstat.us/500")
except HTTPError as exception:
    content = exception.fp.read()
    print(type(exception.fp))
    print(type(content))
```

> Do I change StringIO to BytesIO when fp is None ?

**Comment by corona10** [comment]
> The title is incorrect, should be read returns string instead of bytes when fp is None.


Thanks, I modified the title.

**Comment by corona10** [comment]
@longvhdeveloper Thank you for your hard work!
