### ISSUE TITLE
code.h uses MS-only C++ extensions

### ISSUE THREAD

**Issue by zooba** [python/cpython#101907]
Issue #100222 added a struct to `Include/cpython/code.h` (which is included by default by `Python.h`) that is not compliant C++:

```
typedef union {
    uint16_t cache;
    struct {
        uint8_t opcode;
        uint8_t oparg;
    };
} _Py_CODEUNIT;
```

The struct member requires a name, as only anonymous structs are currently permitted in standard C++.

(And since the original issue invokes PEP 7, I'll do the same and point out that "The public C API should be compatible with C++". The intention of this clause is that standard C++ can `#include <Python.h>`, which is currently broken.)

### Linked PRs
* gh-101909
* gh-101912

**Comment by zooba** [comment]
Do we want that to be the API then? And so we should remove the macros entirely?

If we're going to have macros, I'd rather they be the only place we have to make a change like this.

**Comment by markshannon** [comment]
Personally, I'd say get rid of the macros.

At least the uses of them. We should probably keep the declarations in case any third-party code is using them.
