### ISSUE TITLE
ArgumentParser returns wrong values when the argument name is a particular substring of the know argument 

### ISSUE THREAD

**Issue by ftesser** [python/cpython#101915]
# Bug report
Step to reproduce the bug:

1. create a  parser with just one know argument name containing an underscore (e.g: `param_a`);
2. parse a argument string that contains an unknown argument name, but that starts with the same string  (e.g: `param=wrong_value`);
3. the parser assign the value of this unknown argument to the know argument (e.g:  param_a=wrong_value: see CASE 2. in the code below).

Moreover using both the know argument and the unknown result also in a wrong assignment (see CASE 3. below).

```python
from argparse import ArgumentParser

main_parser = ArgumentParser()
# create a parser and add just one argument param_a
main_parser.add_argument('--param_a', type=str, required=False)
print('CASE 1. parse the string --param_a=correct_value -> OK')
options = main_parser.parse_known_args(['--param_a=correct_value'])[0]
print(options)
print('CASE 2. parse --param=wrong_value (argument name that starts with the same substring of the know argument name) -> KO')
options = main_parser.parse_known_args(['--param=wrong_value'])[0]
print(options)
print('CASE 3. join 1. and 2. -> KO')
options = main_parser.parse_known_args(['--param_a=correct_value', '--param=wrong_value'])[0]
print(options)
```
The output of the previous snippet of code is:
```
CASE 1. parse the string --param_a=correct_value -> OK
Namespace(param_a='correct_value')
CASE 2. parse --param=wrong_value (argument name that starts with the same substring of the know argument name) -> KO
Namespace(param_a='wrong_value')
CASE 3. join 1. and 2. -> KO
Namespace(param_a='wrong_value')
```
# Your environment

- CPython versions tested on: Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
- Operating system and architecture: Linux Ubuntu 22.04.1 LTS - x86_64 x86_64

**Comment by lucasalavapena** [comment]
Is this a bug? [The docs](https://docs.python.org/3/library/argparse.html#partial-parsing) has a warning regarding the prefix matching:
> Warning: [Prefix matching](https://docs.python.org/3/library/argparse.html#prefix-matching) rules apply to parse_known_args(). The parser may consume an option even if it’s just a prefix of one of its known options, instead of leaving it in the remaining arguments list.

**Comment by ftesser** [comment]
Hello @lucasalavapena, thanks for pointing that warning,  going into the documentation of the [Prefix matching](https://docs.python.org/3/library/argparse.html#prefix-matching) then I discover that is it possible to disable that behavior by setting [allow_abbrev](https://docs.python.org/3/library/argparse.html#allow-abbrev) to False.

Infact setting 

```python
main_parser = ArgumentParser(allow_abbrev=False)
```

The result of the previous code respect my expectation.

I have just to say that for me is unclear way `allow_abbrev=True` should help the user: the user can digit less chars but the result can be ambiguus.

**Comment by hpaulj** [comment]
This is just the default abbreviation behavior that has been present in argparse from the beginning.  Flags can be abbreviated as long as they aren't ambiguous

    In [12]: p1.parse_args('--foo=x'.split())
    usage: ipykernel_launcher.py [-h] [--foo1 FOO1] [--foo2 FOO2]
    ipykernel_launcher.py: error: ambiguous option: --foo=x could match --foo1, --foo2

The idea is that users to specify a long informative flag, that will appear in the usage and help, without having to also specify all allowed abbreviations.  

With the (newish) 'allow_abbrev' parameter you have the choice of accepting the convenient abbreviation behavior, or rejecting it because it's producing too many errors.

I think this issue should be closed.  Allowing abbreviations is a well established feature of argparse.

**Comment by arhadthedev** [comment]
@ftesser This behavior is controlled by `allow_abbrev` argument of the `argparse.ArgumentParser` constructor:

> **[class argparse.ArgumentParser([...], allow_abbrev=True, [...])](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser)**
>
> - allow_abbrev - Allows long options to be abbreviated if the abbreviation is unambiguous. (default: True)

So closing as not-a-bug.
