### ISSUE TITLE
Exception using fileinput.hook_compressed in binary mode

### ISSUE THREAD

**Issue by gmacon** [python/cpython#101961]
# Bug report

When using the [`fileinput.hook_compressed`](https://docs.python.org/3/library/fileinput.html#fileinput.hook_compressed) hook in binary mode in the case that the file is *not* compressed, an exception is raised instead of processing the file like normal.

```python
# fileinput_cat.py

import fileinput
import sys

with fileinput.input(mode='rb', openhook=fileinput.hook_compressed) as f:
    for line in f:
        sys.stdout.buffer.write(line)
```

```console
$ python3.10 fileinput_cat.py fileinput_cat.py
Traceback (most recent call last):
  File "fileinput_bug.py", line 5, in <module>
    for line in f:
  File ".../lib/python3.10/fileinput.py", line 256, in __next__
    line = self._readline()
  File ".../lib/python3.10/fileinput.py", line 385, in _readline
    self._file = self._openhook(self._filename, self._mode)
  File ".../lib/python3.10/fileinput.py", line 432, in hook_compressed
    return open(filename, mode, encoding=encoding, errors=errors)
ValueError: binary mode doesn't take an encoding argument
```

# Your environment

I tried this on Python 3.10.9 (installed from nixpkgs) on Intel macOS 11.7.3. It was working on Python 3.9.16.

### Linked PRs
* gh-102068
* gh-102098
* gh-102099

**Comment by corona10** [comment]
I will take the issue as the internal OSS sprint for the new contributors.
I will delegate the issue to my mentees.
Thanks for understanding!

**Comment by ghkim3221** [comment]
I'm looking this issue 👀

**Comment by corona10** [comment]
Thank you @ghkim3221 for the hard work!
