### ISSUE TITLE
Use _Py_EnterRecursiveCall private API in _bisectmodule.c

### ISSUE THREAD

**Issue by gdementen** [python/cpython#101903]
# Feature or enhancement

I just noticed the _bisectmodule.c is the only internal module using the Py_EnterRecursiveCall and Py_LeaveRecursiveCall public API functions instead of the private ones with underscores. For both consistency and a tiny performance enhancement, I think it would make sense to use the private API instead.

# Pitch

I have a PR ready for this, but since I have no idea of what I am doing this might be completely bogus 😉.

### Linked PRs
* gh-101931
* gh-101923

**Comment by erlend-aasland** [comment]
As noted in https://github.com/python/cpython/pull/101931#issuecomment-1432352313, this requires defining `_bisectmodule.c` as a core module, which IMO requires a broader discussion.

We deliberately make some stdlib extension modules use the public C API. As an (unrwritten) general rule, the modules in `Modules/Setup.bootstrap.in` are built using the internal C API, whereas the modules in `Modules/Setup.stdlib.in` should preferably use the public C API.

Suggesting to close this issue as _not-planned_.

**Comment by erlend-aasland** [comment]
See also Eric's comment from similar API issues: https://github.com/python/cpython/pull/31376#issuecomment-1042083465
