### ISSUE TITLE
The annotations in c_annotations.py cannot be translated

### ISSUE THREAD

**Issue by remilapeyre** [python/cpython#101986]
The c_annotations Sphinx extension at https://github.com/python/cpython/blob/main/Doc/tools/extensions/c_annotations.py adds some markup to the documentation files but those do not appear in the translation dumps, e.g. the file at https://git.afpy.org/AFPy/python-docs-fr/src/branch/3.11/c-api/refcounting.po contains no annotations of the form "Part of the Stable ABI since version 3.10.".

Because their is no translation support in c_annotations.py and the annotation are not in the translation dump either it is not possible to translate those messages at the moment.

### Linked PRs
* gh-107680
* gh-112940
* gh-112941

**Comment by hugovk** [comment]
PRs have been merged and backported, thanks for the report!
