### ISSUE TITLE
Bus error when an extension is loaded into sqlite3

### ISSUE THREAD

**Issue by jackbeagley** [python/cpython#101974]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on: 3.11.0, 3.10.9
- Operating system and architecture: MacOS 13.2.1 arm64 (Macbook Pro M1 Pro 16")

When loading the `mod_spatialite` library into `sqlite3` everything works as expected until I close the connection, at which point i get a bus error:

`50000 bus error  /opt/homebrew/Caskroom/miniforge/base/envs/main/bin/python `

I am unsure if the bug is related to spatialite or python itself but I don't get the bus error if I comment out the line `conn.load_extension(shared_lib)`. Example database from MWE: https://www.sqlitetutorial.net/wp-content/uploads/2018/03/chinook.zip

```
import sqlite3
import pandas as pd

shared_lib = '/opt/homebrew/lib/mod_spatialite.dylib'

conn = sqlite3.connect('chinook.db')

conn.enable_load_extension(True)
conn.load_extension(shared_lib)
sql = 'SELECT * FROM artists'

df = pd.read_sql(sql, conn)

conn.close()
```

**Comment by ned-deily** [comment]
It could be due to some sort of mismatch of that extension and sqlite version. Can you run the following commands in your terminal shell using the python(s) you are testing with and copy the output here?

```
python -c 'import sys;print(sys.version)'
python -c 'import _sqlite3;print(_sqlite3.__file__)'
```

**Comment by erlend-aasland** [comment]
Also, can you provide the output of this script?

```python3
>>> import sqlite3
>>> cx = sqlite3.connect(":memory:")
>>> for r in cx.execute("pragma compile_options")
>>>    print(r)
```

**Comment by jackbeagley** [comment]
Thanks for the quick responses!
So - I definitely should have mentioned that I am using conda-forge for python. Here is the output from the above commands:

```
(main)  jack@Jacks-MBP ~ python -c 'import sys;print(sys.version)'
3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:26:40) [Clang 14.0.6 ]
(main)  jack@Jacks-MBP ~ python -c 'import _sqlite3;print(_sqlite3.__file__)'
/opt/homebrew/Caskroom/miniforge/base/envs/main/lib/python3.11/lib-dynload/_sqlite3.cpython-311-darwin.so
```

And from @erlend-aasland's script:

```
('ATOMIC_INTRINSICS=1',)
('COMPILER=clang-14.0.6',)
('DEFAULT_AUTOVACUUM',)
('DEFAULT_CACHE_SIZE=-2000',)
('DEFAULT_FILE_FORMAT=4',)
('DEFAULT_JOURNAL_SIZE_LIMIT=-1',)
('DEFAULT_MMAP_SIZE=0',)
('DEFAULT_PAGE_SIZE=4096',)
('DEFAULT_PCACHE_INITSZ=20',)
('DEFAULT_RECURSIVE_TRIGGERS',)
('DEFAULT_SECTOR_SIZE=4096',)
('DEFAULT_SYNCHRONOUS=2',)
('DEFAULT_WAL_AUTOCHECKPOINT=1000',)
('DEFAULT_WAL_SYNCHRONOUS=2',)
('DEFAULT_WORKER_THREADS=0',)
('ENABLE_COLUMN_METADATA',)
('ENABLE_DBSTAT_VTAB',)
('ENABLE_FTS3',)
('ENABLE_FTS3_TOKENIZER',)
('ENABLE_FTS4',)
('ENABLE_FTS5',)
('ENABLE_GEOPOLY',)
('ENABLE_MATH_FUNCTIONS',)
('ENABLE_RTREE',)
('ENABLE_UNLOCK_NOTIFY',)
('MALLOC_SOFT_LIMIT=1024',)
('MAX_ATTACHED=10',)
('MAX_COLUMN=2000',)
('MAX_COMPOUND_SELECT=500',)
('MAX_DEFAULT_PAGE_SIZE=8192',)
('MAX_EXPR_DEPTH=10000',)
('MAX_FUNCTION_ARG=127',)
('MAX_LENGTH=1000000000',)
('MAX_LIKE_PATTERN_LENGTH=50000',)
('MAX_MMAP_SIZE=0x7fff0000',)
('MAX_PAGE_COUNT=1073741823',)
('MAX_PAGE_SIZE=65536',)
('MAX_SQL_LENGTH=1000000000',)
('MAX_TRIGGER_DEPTH=1000',)
('MAX_VARIABLE_NUMBER=250000',)
('MAX_VDBE_OP=250000000',)
('MAX_WORKER_THREADS=8',)
('MUTEX_PTHREADS',)
('SECURE_DELETE',)
('SYSTEM_MALLOC',)
('TEMP_STORE=1',)
('THREADSAFE=1',)
```

**Comment by jackbeagley** [comment]
Using `mod_spatialite` from conda instead of homebrew fixed the issue - no more bus errors! Are you happy to consider this fixed, or is the behaviour with the homebrew `mod_spatialite` still considered a bug?

**Comment by erlend-aasland** [comment]
Sounds to me that this is not an sqlite3 bug. The spatialite SQLite modules from Homebrew vs Conda may be compiled with different compilers, different compiler flags, and against different SQLite versions.

Closing as not-a-bug.
