### ISSUE TITLE
Windows Error: Multicast setsocketopt socket.IP_MULTICAST_IF not working  >3.8.12

### ISSUE THREAD

**Issue by RaubCamaioni** [python/cpython#101960]
# Bug Report: setsocketopt IP_MULTICAST_IF error on windows

Python update 3.x.13 broke setsocketopt  for multicast options on Windows 10/11. 
Minimal example works on versions <= 3.8.12, <= 3.9.12
Minimal example errors on versions >3.8.12, >3.9.12
Probably fails for any python 3 version after 3.x.12 (only tested on 3.8 and 3.9)

Minimal example fails on Windows.
Minimal example succeeds on WSL, Linux, Mac. 

Windows Error: 
```
sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_IF, socket.inet_aton(network_adapter))
OSError: [WinError 10022] An invalid argument was supplied
```

Minimal Example:
```
import socket
from contextlib import closing

address = "239.50.50.50"
port = 6000
network_adapter = "172.16.0.93"  # change to a valid network adapter ip
with closing(socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)) as sock:
	sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 2 ** 8)
	sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
	sock.bind((network_adapter, port))  # on linux the IP would be "address" NOT "network_adapter" (maybe related to why linux works)
	sock.setsockopt(socket.SOL_IP, socket.IP_MULTICAST_IF, socket.inet_aton(network_adapter))
	sock.setsockopt(socket.SOL_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(address) + socket.inet_aton(network_adapter))
```
# Windows Conda Environment
- Windows 10/11 Pro 22H2
-  OS BUILD: 19045.2486
- conda environment
- python <= 3.8.12 working
- python >= 3.9.13 failing OSError

# (Working) Minimal Example: Eryksun's Fix
Tested working on Windows/Linux

```
import socket
import platform
from contextlib import closing

address = "239.50.50.50"
port = 6000
network_adapter = "172.16.0.93"

with closing(socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)) as sock:
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_RCVBUF, 2 ** 8)
    sock.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
    
    # linux binds to multicast address, windows to interface address
    ip_bind = network_adapter if platform.system() == "Windows" else address
    sock.bind((ip_bind, port))
	
    # socket.IPPROTO_IP works on Linux and Windows
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(network_adapter))
    sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, socket.inet_aton(address) + socket.inet_aton(network_adapter))
```

**Comment by eryksun** [comment]
Previously, the socket module used the default value of 0 (i.e. [`IPPROTO_IP`](https://learn.microsoft.com/en-us/windows/win32/winsock/ipproto-ip-socket-options)) for `socket.SOL_IP`. The newer versions of the Windows SDK that are used by Python 3.9+ define `SOL_IP` as `SOL_SOCKET - 4` (0xFFFB).

```pycon
>>> sys.version_info[:2]
(3, 8)
>>> socket.SOL_IP, socket.IPPROTO_IP
(0, 0)
```
```pycon
>>> sys.version_info[:2]
(3, 9)
>>> socket.SOL_IP, socket.IPPROTO_IP
(65531, 0)
```

Winsock apparently doesn't support using this `SOL_IP` level for setting `IP_MULTICAST_IF` and `IP_ADD_MEMBERSHIP`. Your example works in 3.9+ if I use `socket.IPPROTO_IP` instead of `socket.SOL_IP`.
