### ISSUE TITLE
Infinite instance creation in finalizers

### ISSUE THREAD

**Issue by wrongnull** [python/cpython#101916]
Hi there! I think I've found corner case that hasn't been handled by cpython's memory management system yet. As the matter of fact finalizers don't track inifinite instance creation in themselves. For example:

```python
class Dummy:
   def __del__(self):
      type(self)()

d = Dummy()
del d
```

This one is reproducible in version 3.12 and on all supported platforms I guess. It is strongly related to issue #55003 
To be honest I'm not sure if this bug is worth fixing but problem is still in the interpreter. Thanks.

**Comment by terryjreedy** [comment]
@iritkatriel You closed #55003.  Is this really a bug?

**Comment by wrongnull** [comment]
> @iritkatriel You closed #55003. Is this really a bug?

At least there is an unexpected behaviour in this certain example.

**Comment by iritkatriel** [comment]
The interpreter hangs so it's a bug but I don't know if it's related to #55003.

**Comment by iritkatriel** [comment]
Actually I don't think the interpreter is handling. Try this:

```
class Dummy:
   def __init__(self):
      print('__init__', id(self))

   def __del__(self):
      print('__del__', id(self))
      type(self)()

d = Dummy()
del d
```

It's simply spinning around in user code.

**Comment by terryjreedy** [comment]
A loop in user code is not a bug.  The output is the same if the looping is done in a `def meth`.  The difference is that the latter stop with recursion error after about 1000 calls on Windows.  I know that __del__ is somehow special so the question is whether not raising with __del__ (after more than 10000 double calls) is a bug.  @ambv ?

**Comment by terryjreedy** [comment]
https://docs.python.org/3/reference/datamodel.html#object.__del__. "Due to the precarious circumstances under which [__del__()](https://docs.python.org/3/reference/datamodel.html#object.__del__) methods are invoked, exceptions that occur during their execution are ignored, and a warning is printed to sys.stderr instead."  We are discussing what to do on discord.

**Comment by terryjreedy** [comment]
Comments from njs (PythonCoreDevs, Committer topic, 2023 Feb 14) suggest that there is no sensible way to handle this.  It is somewhat equivalent to running
```
while True:
    print('Warning: ...', file=sys.stderr)
```

**Comment by wrongnull** [comment]
Awesome... Is this "legal" way to reach infinite recursion? :)

**Comment by iritkatriel** [comment]
It's not really infinite recursion. The interpreter prevents the recursion getting too deep. It's more like an infinite loop.

**Comment by wrongnull** [comment]
As I thought loops and recursion are close sematically equivallent. Doesn't matter. As I said this is a corner case.

**Comment by wrongnull** [comment]
@iritkatriel I came up with example that behaves even more weird. Will I definitely put it on an infinite loop and not on a hanging?

```python
import sys

class A:
    def __init__(self):
        print("instance created", self)
    def __del__(self):
        print("finalizer invoked", self):
        try:
            1/0
        except (ZeroDivisionError if bool(0) else type(self)()):
            pass

def custom_unraisable_hook(unraisable):
    a = A()
    del a

sys.unraisable_hook = custom_unraisable_hook
a = A()
del a
```

In your example interpreter just responds to the ```KeyboardInterrupt``` and another exceptions but not in mine

**Comment by iritkatriel** [comment]
It's constantly printing stuff to the screen, so no it's not hanging.

Deleters don't raise exceptions because they are invoked asynchronously. 
GC avoids deep recursion through the trashcan mechanism. 

You can make this go into infinite loops in all sorts of amusing ways but I don't see anything here for us to do. Have fun.
