### ISSUE TITLE
TLS version (and/or cipher suite) negotiation may cause TLS 1.3 handshakes to fail (discovered via Chromium GREASE).

### ISSUE THREAD

**Issue by cloudstrife9999** [python/cpython#101959]
**NOTE**: the following paragraphs, according to the [security policy](https://www.python.org/dev/security/) do not constitute a proper security issue (rather a bug). Therefore, I'm opening a public issue.

Python servers configured to use TLS1.3+ (see code example below), appear to perform the TLS version negotiation (and/or the cipher suite negotiation) incorrectly.

Since TLS1.3 the version negotiation has been moved to the `supported_versions` extension in ClientHello/ServerHello.

In particular, the client sends a **discrete** list of supported versions in the ClientHello, and the server selects one that it supports, echoing it back to the client in the ServerHello.

In order to detect implementation bugs, Chromium sends random reserved (see [RFC 8701](https://www.rfc-editor.org/rfc/rfc8701.html)) version codes together with the legitimate version codes in the ClientHello. This is part of the "GREASE" mechanism to detect future "intolerances" in advance.

The correct approach when receiving "GREASE" codes / extensions is to simply ignore them as unrecognised codes / extensions.

It looks like that, when at least one of the "GREASE" version codes is greater than the TLS 1.3 code (0x0304), Python aborts the TLS handshake with an alert saying that no common TLS versions / TLS cipher suites have been found.

Actually, it is possible that the error is caused by the same kind of "intolerance" in the cipher suite negotiation.
However, since "GREASE" is controlled by the browser, there is no easy way to check which of the two scenarios (version negotiation, and cipher suite negotiation) is causing the issue (or if both are).

Conversely, Mozilla Firefox does not send "GREASE" codes/extensions, and, as a result, the TLS handshake is successful.

The following code snippet can be used to trigger the issue with Chromium as the client.

```python
#!/usr/bin/env python3

from flask.app import Flask
from ssl import SSLContext, PROTOCOL_TLS_SERVER


app: Flask = Flask(__name__)

context: SSLContext = SSLContext(protocol=PROTOCOL_TLS_SERVER)

# Forcing TLS 1.3.
context.minimum_version = context.maximum_version

# Override with the actual values (this is just an example).
server_cert_path: str = "PUT_THE_CERTIFICATE_PATH_HERE"
server_private_key_path: str = "PUT_THE_PRIVATE_KEY_PATH_HERE"

context.load_cert_chain(certfile=server_cert_path, keyfile=server_private_key_path)

@ app.route("/")
def index() -> str:
    return "Hello World!"

app.run(host="127.0.0.1", port=5000, debug=False, ssl_context=context)
```

Environment:

- `debian sid`
- `Python` version: 3.11.2
- `Flask` version: 2.2.3
- `openssl` version: 3.0.8

P.s., I am aware that Flask is not intended for production. Using it was the easiest way I found to showcase the issue.
P.p.s, according to the Flask maintainer, [this bug has nothing to do with Flask or Werkzeug](https://github.com/pallets/flask/issues/4984).

**Comment by davidism** [comment]
To ensure it has the best chance of getting fixed, you'll want to modify this to be a minimal reproducible example using only `http.server` and `ssl`, not requiring the maintainers to install Flask.

**Comment by cloudstrife9999** [comment]
This following code snippet can be used to trigger the issue without having to rely on `Flask`.

```python
#!/usr/bin/env python3

from http.server import HTTPServer, SimpleHTTPRequestHandler
from ssl import SSLContext, PROTOCOL_TLS_SERVER
from multiprocessing import Process


context: SSLContext = SSLContext(protocol=PROTOCOL_TLS_SERVER)

# Forcing TLS 1.3.
context.minimum_version = context.maximum_version

# Override with the actual values (this is just an example).
server_cert_path: str = "PUT_THE_CERTIFICATE_PATH_HERE"
server_private_key_path: str = "PUT_THE_PRIVATE_KEY_PATH_HERE"

context.load_cert_chain(certfile=server_cert_path, keyfile=server_private_key_path)

with HTTPServer(("", 60000), SimpleHTTPRequestHandler) as server:
    server.socket = context.wrap_socket(sock=server.socket, server_side=True)

    p: Process = Process(target=server.serve_forever, args=())
    p.daemon = True
    p.start()
    p.join()

```

**Comment by arhadthedev** [comment]
@jackjansen, @tiran, @dstufft, @alex (as SSL module experts)

**Comment by cloudstrife9999** [comment]
Actually, it seems that the culprit is Chromium, because it does not support certain EC curves for ECDSA (namely secp521r1).
I'm closing the issue.
