### ISSUE TITLE
ceval.c: `positional_only_passed_as_keyword` can be failed with segfault

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#101967]
https://github.com/python/cpython/blob/4d8959b73ac194ca9a2f623dcb5c23680f7d8536/Python/ceval.c#L1251-L1285

This implemention doesn't take in account case when `PyList_New` returns `NULL`.
If `PyList_New(0)` returns a `NULL`, `PyList_Append` will be failed with segfault, cause of `Py_TYPE`, which will try to reach out `ob_type`. of `(PyObject *) NULL`.
This hard to reproduce, because the only way `PyList_New` can error, if it is runs out of memory, but theoretically it can happen.

### Linked PRs
* gh-101968
* gh-102016
* gh-102015
* gh-114738

**Comment by carljm** [comment]
Good find! Do you want to make a pull request to add the missing error handling?
