### ISSUE TITLE
Update required to the https://www.python.org/download/other/ with information about CPython port for UEFI environment

### ISSUE THREAD

**Issue by jpshivakavi** [python/cpython#101977]
# Documentation

The webpage - https://www.python.org/download/other/ has information about the Python ports done for other platforms from different communities. 

I am raising this ticket to get this page updated with the information about standard C Python 3.6.8 version port done for the UEFI environment. 

Where UEFI stands for Unified Extensible Firmware Interface which provides a pre-OS environment that typically used for Firmware validation, debug, board validation, diagnostics and various other use cases.  
The C-Python 3.6.8 port for UEFI provided the Advanced Python scripting capabilities on UEFI shell. This can be potentially used by a lot of device manufacturers (OEMs and ODMs), System designers, Firmware developers/validation and debug engineers for client and server systems. 

By having information about this port documented the above mentioned page, we want to bring awareness about this port to potential users. This will intern help them use and contribute back if they can.
The primary idea here is to bring to the awareness of the larger Python community about this interesting Python port for UEFI environment.

We want the following documentation details to be captured in the download/other page. 

""""""""
Python for UEFI Environment
 
Standard C-Python version 3.6.8 port for the Unified Extensible Firmware Interface (UEFI) shell environment is available through the [Tianocore](https://www.tianocore.org/) open source project.
This provides the standard C-Python scripting capabilities on UEFI environment.
Helping the UEFI based firmware and platform developer community to use it for Platform, Firmware validation, debug and etc.
Python for UEFI source code and build instructions available @ https://github.com/tianocore/edk2-libc/blob/master/AppPkg/Applications/Python/Python-3.6.8/Py368ReadMe.txt
 
Currently build support is enabled using VS2019 and GCC5 tool chains for x86 and x64 bit platforms.
"""""""""

Adding a detailed discussion thread in the Python Core Development forum for your reference.
https://discuss.python.org/t/cpython-port-for-uefi-shell/23865

**Comment by merwok** [comment]
This tracker is for CPython development, the other one that was suggested to you is the correct place: https://github.com/python/pythondotorg/issues

**Comment by jpshivakavi** [comment]
Thanks @merwok for your inputs. I shall repost it as you suggested.

**Comment by CAM-Gerlach** [comment]
> I’m not an admin who can move tickets between repos, hope you won’t mind reposting there!

You don't need to be an admin FYI, you only need the `Write` role or above on the source and destination repos. So besides org owners, any triager, core dev or anyone else with at least the `Write` role here who has `Write` or above over there could so so (though, not sure how many people do over there).
