### ISSUE TITLE
Sqlite3 driver returning error for table having more than 2000 Columns

### ISSUE THREAD

**Issue by Bishnup1995** [python/cpython#102065]
When querying a table that has more than 2000 columns an error is returned. Even though only a few columns are queried.

`[SQLITE_CORRUPT] The database disk image is malformed (malformed database schema (TableName) - too many columns on TableName)`

To Reproduce

Recompile the Sqlite Source code to support more than 2000 columns by giving the flag -DSQLITE_MAX_COLUMN=32767.
Create a table having more than 2000 Columns
Query or insert data to the created table.
The error would be returned when Querying the table with more than 2000 columns.
Expected behavior
Data should be returned

Logs
[SQLITE_CORRUPT] The database disk image is malformed (malformed database schema (TableName) - too many columns on TableName)

Environment (please complete the following information):

OS: `CentOS 7.9.2009`
CPU architecture: `x86_64`
sqlite3.sqlite_version: `'3.30.0'`

# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by terryjreedy** [comment]
Please add latest CPython version tested and minimal reproducible example.

**Comment by Bishnup1995** [comment]
Hey @terryjreedy. Thank you for your response. I am using `3.7.4` version of python. I have already added the steps to reproduce the issue. We have to create a table in sqlite3 with more than 2000 columns and then try to select some columns from the table. Please let me know if you want me to add the create table and select query.

**Comment by erlend-aasland** [comment]
Python 3.7 is not supported anymore. I would suggest you take this issue to the SQLite forum.

**Comment by erlend-aasland** [comment]
Here's some links that might come in handy:

- https://sqlite.org/howtocorrupt.html
- https://sqlite.org/forum/forum
