### ISSUE TITLE
Pointless check when creates empty tuple

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102085]
In CPython code, we have many cases like that:
```c
PyObject *obj = PyTuple_New(0);
if (obj == NULL)
    return NULL;  // or goto fail;
```
But, `PyTuple_New(0)` returns a result of `tuple_get_empty` which cannot return a `NULL` value, because empty tuple is a static object.
We can remove  all these checks from code, and write this note in `PyTuple_New`:
```c
PyObject *
PyTuple_New(Py_ssize_t size)
{
    PyTupleObject *op;
    if (size == 0) {
        // Note: Since empty tuple is statically allocated, it's cannot return NULL-value.
        return tuple_get_empty();
    }
...
```

**Comment by carljm** [comment]
It seems that a highly-predictable null check of a value that is already going to be in a register probably does not cost very much? Unless we can see visible improvement in a benchmark, I'm not sure that this change is worth the extra mental overhead. If a zero-tuple creation turns into e.g. a one-tuple creation, someone must remember to add the null check.

**Comment by sobolevn** [comment]
I agree, moreover it depends on an implementation detail that `()` is static.
Moreover, changing `0` to some other number might change the status-quo.
Let's skip this one (as the number of upvotes show the general consensus) :)

**Comment by JelleZijlstra** [comment]
If there is a real performance gain to be had here (which seems doubtful), we could add a separate internal API function that always returns an empty tuple and guarantees that it never returns NULL.
