### ISSUE TITLE
heapq module could be more efficient

### ISSUE THREAD

**Issue by msoxzw** [python/cpython#102061]
Both [Python heap implementation](https://github.com/python/cpython/blob/60bbed7f174e481d3fc69984430a4667951678b3/Lib/heapq.py#L260-L278) and [C heap implementation](https://github.com/python/cpython/blob/60bbed7f174e481d3fc69984430a4667951678b3/Modules/_heapqmodule.c#L69-L117) are roughly based on [bottom-up heapsort](https://en.wikipedia.org/wiki/Heapsort#Bottom-up_heapsort) with opposite function name. Compared to original scheme on Wikipedia, CPython implementation has unnecessary additional item swaps both in "siftup" and "siftdown" instead of only "siftup". Similarly, [GCC adopts the same approach](https://github.com/gcc-mirror/gcc/blob/b9c83e7789f7eec9871e370739baa55fd70be4cf/libstdc%2B%2B-v3/include/bits/stl_heap.h#L220-L249).

Furthermore, CPython implements partial sort based on heap, i.e. [nsmallest](https://github.com/python/cpython/blob/60bbed7f174e481d3fc69984430a4667951678b3/Lib/heapq.py#L463-L521), in [*O*(*n* log *k*) time complexity](https://en.wikipedia.org/wiki/Partial_sorting#Heap-based_solution) rather than [*O*(*n* + *k* log *n*) time complexity](https://en.wikipedia.org/wiki/Partial_sorting#Incremental_sorting), where in practice *k* is much smaller than *n*. Likewise, [GCC adopts the same approach](https://github.com/gcc-mirror/gcc/blob/b9c83e7789f7eec9871e370739baa55fd70be4cf/libstdc%2B%2B-v3/include/bits/stl_algo.h#L1902-L1912), as well.

So I am curious about why both CPython and GCC seemingly inefficiently implement heap.

**Comment by terryjreedy** [comment]
@rhettinger

**Comment by pochmann** [comment]
Both `_siftup` and `nsmallest` have extensive explanation and analysis right above where you linked to, explaining why they're done the way they are.

**Comment by rhettinger** [comment]
As Stefan Pochmann observed, the explanatory comments are in source.   

In particular, having a single *siftdown* at the end saves exit tests in the inner loop.  The comment cites testing which shows empirical evidence that this saves a substantial number of comparisons.  Also, note that in Python the object comparisons dominate the running time.

In *nsmallest* and *nlargest* algorithms are designed to run in a single pass, keeping no more than k items in memory, and giving the fewest comparisons in the common case (small k and large n).   When the data is in random order, the algorithm performs *much* better than the `O(n log k)` worst case.  For random data, the number of comparisons gets close to that for `min()`.

To explore the question further, please try StackOverflow.  This isn't the right forum for asking "I curious, why ..." questions.

**Comment by msoxzw** [comment]
Thanks a lot, and I will try StackOverflow.

By carefully reading those explanatory comments once again, CPython's _siftup_ is a variant of [bottom-up heapsort](https://en.wikipedia.org/wiki/Heapsort#Bottom-up_heapsort) with equal comparisons and more item swaps, and reiterates its advantage over [the top-down version](https://en.wikipedia.org/wiki/Heapsort#Pseudocode), if I correctly understand it.

As for _nsmallest_ and _nlargest_ algorithms, it makes perfect sense if no more than _k_ items are absolutely required to be kept in memory. By the way, *O*(*n* *log* *k*) is not only the worst case, but also the best case and average case.

**Comment by pochmann** [comment]
> By the way, _O_(_n_ _log_ _k_) is not only the worst case, but also the best case

No, you're ignoring the `if elem < top:` guard that commonly (and I the best case **always**) avoids the heap operation:

https://github.com/python/cpython/blob/60bbed7f174e481d3fc69984430a4667951678b3/Lib/heapq.py#L497-L499

**Comment by msoxzw** [comment]
> > By the way, _O_(_n_ _log_ _k_) is not only the worst case, but also the best case
> 
> No, you're ignoring the `if elem < top:` guard that commonly (and I the best case **always**) avoids the heap operation:
> 
> https://github.com/python/cpython/blob/60bbed7f174e481d3fc69984430a4667951678b3/Lib/heapq.py#L497-L499

So the best case is *O*(*k*+*n*).
