### ISSUE TITLE
`threading.RLock` must not support `*args, **kwargs` arguments

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#102029]
Right now we have an interesting problem: `_CRLock` supports `*args, **kwargs` in `__new__`, while `_PYRLock` does not.

See:
1. https://github.com/python/cpython/blob/128379b8cdb88a6d3d7fed24df082c9a654b3fb8/Lib/threading.py#L133
2. https://github.com/python/cpython/blob/128379b8cdb88a6d3d7fed24df082c9a654b3fb8/Modules/_threadmodule.c#L506 (they are unused)

I am leaving aside the problem that `_PYRLock` is not ever used (unless imported directly) for now.

Right now our docs does not say what the signature should be.
Some facts:
1. CPython's code never use `RLock` with arguments (and never say it has arguments)
2. typeshed (a source of truth for all typecheckers and several IDEs [never had a single issue](https://github.com/python/typeshed/issues?q=is%3Aissue+rlock+is%3Aclosed) about missing `*args, **kwargs` in their `RLock`'s stub: https://github.com/python/typeshed/blob/0bb7d621d39d38bee7ce32e1ee920bd5bc4f9503/stdlib/threading.pyi#L113-L119 
3. We don't have any docs about `RLock`'s signature

So, I think we can:
1. Document that `RLock` has `()` signature
2. Remove `*args, **kwargs` from C impl
4. Document this in "What's new"

Does it sound like a plan? If yes, I would like to do the honours :)

### Linked PRs
* gh-102071

**Comment by sobolevn** [comment]
Or even it migth be a good time to deprecate `_PyRLock`? 

See https://github.com/python/cpython/issues/57906
This was discussed even 11 years ago. Maybe the time has come? :)

**Comment by sobolevn** [comment]
CC @njsmith @pitrou

**Comment by hugovk** [comment]
Anything more to do here, or can we close this issue?
