### ISSUE TITLE
Reduce _idle_semaphore calls in ThreadPoolExecutor

### ISSUE THREAD

**Issue by jackcvr** [python/cpython#102024]
# Feature or enhancement

In `concurrent.futures.thread.ThredPoolExecutor` method `executor._idle_semaphore.release()` should be called if only work queue is empty

# Pitch

Currently `_idle_semaphore.release()` is called after processing every item in queue. That produces useless semaphore updates in case when queue still has items to process.
The optimization is going to increase processing speed of work queue.

### Linked PRs
* gh-102025
* gh-104959

**Comment by terryjreedy** [comment]
'IDLE' (capitalized) is the IDE that comes with CPython; it has nothing to do with inactivity ;-).

**Comment by gpshead** [comment]
thanks!
