### ISSUE TITLE
Syntax error in _delim.py

### ISSUE THREAD

**Issue by dmacks** [python/cpython#102033]
# Bug report

As part of packaging in fink, we try to byte-compile all .py using the just-built interpretter in the staging directory for installation. After compiling from the source tarball:
```
make install DESTDIR=/sw/build.build/root-python311-3.11.2-1
[...]
DYLD_LIBRARY_PATH=/sw/build.build/root-python311-3.11.2-1/sw/lib
+ /sw/build.build/root-python311-3.11.2-1/sw/bin/python3.11 -m compileall -f -o 0 -o 1 -o 2 _sysconfigdata__darwin_darwin.py Tools
[...]
Compiling 'Tools/c-analyzer/c_parser/parser/_delim.py'...
***   File "Tools/c-analyzer/c_parser/parser/_delim.py", line 37
    ''')
       ^
SyntaxError: f-string: empty expression not allowed
```

# Your environment

This is OS X 10.13, I see the same results on python-3.11.2, and 3.10.10 and 3.10.4 but not 3.9.12, which makes sense since _delim.py was introduced via PR #22841 and unchanged since that point.

### Linked PRs
* gh-102066

**Comment by hauntsaninja** [comment]
Thanks all!
