### ISSUE TITLE
`string.replace()` not working correctly in for loop

### ISSUE THREAD

**Issue by dzdz5646** [python/cpython#102147]
# Bug report

When use for loop index to replace sting, string.replace() not working.

Example: 

```py
my_string = '...(x/y)'
my_string = my_string.replace('x' , str(10))
print(my_string)

# ...(10/y)

for x in range(0 , 3 , +1):
    my_string = my_string.replace('x' , str(x))
    print(my_string)

    
# ...(10/y)
# ...(10/y)
# ...(10/y)
```

# Your environment

- CPython versions tested on: Python 3.11.2 (v3.11.2:878ead1ac1, Feb  7 2023, 10:02:41) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
- Operating system and architecture: MacOS 13.2.1 (22D68) / arm64 (Apple M1)

**Comment by chgnrdv** [comment]
Call to `s.replace(a, b)` returns `s` if `a` substring isn't present in `s`. On first iteration you assign the string with replaced `'x'` character to `my_string` variable, so on subsequent iterations
```python
my_string = my_string.replace('x', 'y')
```
won't change `my_string` because it doesn't contain `'x'` character anymore.

**Comment by chgnrdv** [comment]
Call to `s.replace(a, b)` returns `s` if `a` substring isn't present in `s`. On first iteration you assign the string with replaced `'x'` character to `my_string` variable, so on subsequent iterations
```python
my_string = my_string.replace('x', 'y')
```
won't change `my_string` because it doesn't contain `'x'` character anymore.

**Comment by AlexWaygood** [comment]
What @chgnrdv said is correct.

It looks like you may be a beginner with Python. In the future, https://discuss.python.org is a better place to get help with understanding why your code isn't running the way you'd like it to. The GitHub issue tracker is for bugs in the Python language itself (and the standard library) -- if you're a beginner, it's quite unlikely that you'll run into those :)

Good luck with your journey learning Python!
