### ISSUE TITLE
inspect has unexpected behaviour when applied to a function signature containing a bare asterisk

### ISSUE THREAD

**Issue by dmentock** [python/cpython#102144]
# Bug report

python inspect falsely recognizes a bare asterisk as part of the following parameter:

```python 
import inspect

def testfunction(a,*, c=None):
    return c

f_sig = inspect.signature(testfunction)
params = []
for param in f_sig.parameters.values():
    params.append(param)

testfunction.__signature__ = inspect.signature(testfunction).replace(parameters=[params[0]])
print(testfunction.__signature__) # (a)
testfunction.__signature__ = inspect.signature(testfunction).replace(parameters=[params[1]])
print(testfunction.__signature__) # (*, c=None) instead of (*) or (c=None)
```

# Your environment

- CPython versions tested on:
python3.8.10 
- Operating system and architecture:
WSL2 for Windows 11

**Comment by JelleZijlstra** [comment]
This is correct behavior. The asterisk isn't a parameter by itself, it's a marker that the following parameters are keyword-only.  The display of the signature correctly reflects this language behavior.

**Comment by dmentock** [comment]
@JelleZijlstra In this case why does the result of 

```
testfunction.__signature__ = inspect.signature(testfunction).replace(parameters=[params[1]])
print(testfunction.__signature__)
```
have to be `(*, c=None)` and not `(c=None)` ? How can the `*,` otherwise be separated from the parameter description?

**Comment by JelleZijlstra** [comment]
Because the `c` parameter is keyword-only. To indicate that, we put a `*` before it.

**Comment by dmentock** [comment]
But if we had a function like

 `def testfunction(a,*, c=None, d=None):`

then the result for `c` would be `(*, c=None)` and the result for `d` would again only be `(d=None)` even though `d` is the exact same as `c` in this context and their order could also be switched around. What makes `c` special that the parameter description is modified only for it?

I also tried modifying the parameter for `c` to not include the `*,` anymore for documentation purposes, but it seems very difficult to separate this string as the `inspect._ParameterKind` object is not supposed to be instantiated manually.

**Comment by JelleZijlstra** [comment]
> But if we had a function like
> 
> `def testfunction(a,*, c=None, d=None):`
> 
> then the result for `c` would be `(*, c=None)` and the result for `d` would again only be `(d=None)` even though `d` is the exact same as `c` in this context and their order could also be switched around. What makes `c` special that the parameter description is modified only for it?

I don't think that's true:

```
>>> import inspect
>>> def f(*, c, d): pass
... 
>>> sig = inspect.signature(f)
>>> sig.replace(parameters=[sig.parameters["d"]])
<Signature (*, d)>
```
