### ISSUE TITLE
Incorrect prime calculation while using generators for certain upper bounds of primes requested

### ISSUE THREAD

**Issue by anadon** [python/cpython#102166]
After some testing to confirm correct calculation of the first 10,000 primes, I have found that finding primes up to 1,000,000 but not primes up to 100,000 or 10,000,000 is producing incorrect results by omitted the later results.  Example failing code is below.

```
#!/usr/bin/env python3
"""
:description: Example file containing illustrory prime finding algorithms.
"""

from math import ceil, floor, sqrt


def naive_primality_test_generator(val: int):
    """
    :description: A time and space optimized Naive Primality Test algorithm.
    :param int: values to check through
    :returns: A generator to get the desired primes from.
    """
    if val < 2:
        return
    primes = [2]
    midpoint = ceil(sqrt(val)) + 2
    if midpoint % 2 == 0:
        midpoint = midpoint + 1
    yield 2
    for maybe_prime in range(3, midpoint, 2):
        for prime in primes:
            if sqrt(maybe_prime) < prime:
                primes.append(maybe_prime)
                yield maybe_prime
                break
            if maybe_prime % prime == 0:
                break
    for maybe_prime in range(midpoint, val + 1, 2):
        for prime in primes:
            if sqrt(maybe_prime) < prime:
                yield maybe_prime
                break
            if maybe_prime % prime == 0:
                break


for prime in naive_primality_test_generator(1000000):
    print(prime)
```

I am running Ubuntu 22.10 and have tested across 
* Python 3.9.9 (main, Jan  1 1970, 00:00:01)  [GCC 10.3.0]
* Python 3.10.7 (main, Nov 24 2022, 19:45:47) [GCC 12.2.0]
* Python 3.11.0rc2 (main, Sep 12 2022, 16:20:24) [GCC 12.2.0]

I have no idea where to go from here on this.

**Comment by anadon** [comment]
Output attached.
[results.txt](https://github.com/python/cpython/files/10810161/results.txt)

**Comment by dtrodrigues** [comment]
This isn't a Python bug, there is a bug in your code. This may be better suited for https://discuss.python.org/c/users/7

**Comment by terryjreedy** [comment]
According to results.txt, the bug is that the largest prime printed is 993997, while there are larger primes less than 1_000_000.  The bug is that for 1_000_000, the largest prime appended to primes is 997, so only primes < 997*997 = 994009 can be found.  (Only counts < 994009 have their sqrt < 997).  You need to put the first prime > midpoint into primes to assure getting them all.  Or easier, add
```
        if sqrt(maybe_prime) < midpoint:
            yield maybe_prime
```
at the end of the function, after looping thru primes the second time.

Also, only calculate sqrt(maybe_prime) just once for each value, before the inner loop.

**Comment by anadon** [comment]
Yup, that's right.  Must be burning out.

**Comment by terryjreedy** [comment]
This
