### ISSUE TITLE
Predicates in itertools and filter

### ISSUE THREAD

**Issue by pochmann** [python/cpython#102105]
# Documentation

## `filterfalse`

The [doc](https://docs.python.org/3/library/itertools.html#itertools.filterfalse) says *"Make an iterator that filters elements from iterable returning only those for which the predicate is `False`"*. That's not correct, it also returns other false elements:
```pycon
>>> list(filterfalse(lambda x: x, [False, 0, 1, '', ()]))
[False, 0, '', ()]
```

## `quantify`

This [recipe](https://docs.python.org/3/library/itertools.html#itertools-recipes) has the opposite issue:
```python
def quantify(iterable, pred=bool):
    "Count how many times the predicate is true"
    return sum(map(pred, iterable))
```
It says "true", but it only really works with `True`. Other predicates, like `re.compile(...).match` returning `re.Match` objects or `None`, don't work and `quantify` crashes. Predicates returning numbers other than 1 and 0 don't crash it but lead to wrong "counts". So `quantify` is limited. A pity and an odd outlier, since the other six tools/recipes and `filter` all support Python's general truth value concept.

The easy fix is to map `bool` over the predicate values:
```python
def quantify(iterable, pred=bool):
    "Count how many times the predicate is true"
    return sum(map(bool, map(pred, iterable)))
```
I don't see something "nicer" with the available tools/recipes. If only there was a `length` recipe, then we could do:
```python
def quantify(iterable, pred=bool):
    "Count how many times the predicate is true"
    return length(filter(pred, iterable))
```

## `filter`

The [doc](https://docs.python.org/3/library/functions.html#filter) says:

> **`filter`**(*`function`*, *`iterable`*)
> Construct an iterator from those elements of *iterable* for which *function* returns true.

The "returns true" doesn't work well. I'd say "returns a true value" or "for which *function* is true".

The last paragraph has the same issue:

> See `itertools.filterfalse()` for the complementary function that returns elements of *iterable* for which *function* returns false.

### Linked PRs
* gh-102189
* gh-102219

**Comment by picnixz** [comment]
You can patch ``quantify`` as follows if you don't care about efficiency:

```
def quantify(iterable, pred=bool):
    "Count how many times the predicate is true"
    return sum(1 for item in iterable if pred(iterable))
``` 

----
#### Remark

Formally speaking, a predicate *must* return True or False (in the sense of the language). We abusively call a function a predicate if it returns something which can be *implicitly* interpreted as a boolean value. 

I think this is not limited to this specific part of the documentation and there should probably be other locations where we write "true" instead of ``True`` or vice-versa. For instance, we could add the "predicate" term in the glossary and say that, for a predicate, returning "true" or "True" has the same meaning.

**Comment by rhettinger** [comment]
I concur that the "is False" (uppercase) in the `filterfalse()` doc is incorrect.  Interestingly, the summary at the top of the page is correct and so is the docstring.   While "predicate that returns a false value" is technically the most correct, it is more readable to say "is false" (lowercase f).

For `quantify`, just use the uppercase `True`.  The intent of the tool is to count (sum) actual True and False values which are equivalent to 1 and 0 respectively.

Please make a PR and assign to me for review.  Thanks for finding these.  It's interesting that no one noticed in the 12 years they have been published.
