### ISSUE TITLE
edit zipfile documentation for consistency

### ISSUE THREAD

**Issue by dlwrnc** [python/cpython#102190]
# Documentation

there are a few methods in zipfile where args are not explained in the method docstring for public methods. e.g., pwd arg is not explained here: https://github.com/python/cpython/blob/main/Lib/zipfile/__init__.py#L1520, but is documented in a few other public methods.

it's possible to find out what pwd is with a little bit of digging, but it would be helpful to have it defined in the method. it seems like pwd is the most consistently undefined one across zipfile, but i'd be happy to look for other ones as well.

volunteering myself to take care of this work, will open a PR shortly.

### Linked PRs
* gh-102194
* gh-102195
* gh-117408

**Comment by dlwrnc** [comment]
one-month ping on this. :)

**Comment by dlwrnc** [comment]
ping on this issue <3. I forgot about it and then got bit again by it this week.

**Comment by erlend-aasland** [comment]
Are there more actionable items left, or can we close this?

**Comment by dlwrnc** [comment]
good to close 👍 I'll probably open another issue at some point to tidy up the rest of the zipfile docstrings, but that's out of the scope of this one.
