### ISSUE TITLE
Provide dev packages for WASM builds

### ISSUE THREAD

**Issue by dbaeumer** [python/cpython#102113]
# Feature or enhancement

To compile native modules to WASM as well it would be helpful to have dev packages for the WASM builds as well (like the python-dev package for Ubuntu for example). Without these dev package headers files need to be taken from a normal Python dev install which is tricky since these dev installs come with a different `pyconfig.h` file.

Such a dev package should contain the following artifacts:

- header files including `pyconfig.h`
- library files: libpythonx.xx.a libmpdec.a  libexpat.a
- the python.o main file
- A file that describes the environment used to compile for wasm (for example the `wasi.env` file)

Such a dev package could then be used to:

- compile a native module
- link it to a new python.wasm that contains the native module code.

**Comment by brettcannon** [comment]
I am taking care of this over at https://github.com/brettcannon/cpython-wasi-build .
