### ISSUE TITLE
Unable to access same context inside asyncio.wait_for

### ISSUE THREAD

**Issue by Veritaris** [python/cpython#102123]
**platform**: `macOS-13.2-x86_64-i386-64bit`
**cpython**: `3.10.4`

Hi! Recently found an unexpected behaviour using `contextvars` and `asyncio.wait_for`  
With the following code:
```python
import asyncio
import contextvars

my_var: contextvars.ContextVar[int] = contextvars.ContextVar("MY_VAR", default=None)


async def set_var():
    await asyncio.sleep(1)
    my_var.set(10)
    print(contextvars.copy_context())
    print(f"in setter {my_var.get()}")


async def main():
    my_var.set(0)
    print("before start setter")
    await asyncio.wait_for(set_var(), 2)
    print(contextvars.copy_context())
    print(f"in main {my_var.get()}")


if __name__ == "__main__":
    asyncio.run(main())
```
we get this response with different context objects:
```shell
before start setter
<_contextvars.Context object at 0x10aff4300>
in setter 10
<_contextvars.Context object at 0x10afbfc00>
in main 0
```

But if in our `main` func we just await `set_var` we have same context:
```python
async def main():
    my_var.set(0)
    print("before start setter")
    await set_var()
    print(contextvars.copy_context())
    print(f"in main {my_var.get()}")
```

```shell
before start setter
<_contextvars.Context object at 0x10305ff80>
in setter 10
<_contextvars.Context object at 0x10305ff80>
in main 10
```
So the main point here is that we cannot pass context inside `asyncio.wait_for` and thus cannot set any contextvar inside it

**Comment by Eclips4** [comment]
Interesting. Cannot reproduce on current main.
```python
import asyncio
import contextvars

my_var: contextvars.ContextVar[int] = contextvars.ContextVar("MY_VAR", default=None)


async def set_var():
    await asyncio.sleep(1)
    my_var.set(10)
    print(contextvars.copy_context())
    print(f"in setter {my_var.get()}")


async def main():
    my_var.set(0)
    print("before start setter")
    await asyncio.wait_for(set_var(), 2)
    print(contextvars.copy_context())
    print(f"in main {my_var.get()}")


if __name__ == "__main__":
    asyncio.run(main())
```
```python
before start setter
<_contextvars.Context object at 0x7fd1e61de280>
in setter 10
<_contextvars.Context object at 0x7fd1e61de280>
in main 10
```

**Comment by asvetlov** [comment]
This behavior is intended.
Internally `wait_for()` creates a task for `set_var()` coroutine.
The task operates with a copy of the current context variables.
Thus, the copy modification doesn't affect context variables inside `main()` coroutine.

`asyncio.timeout()` (requires Python 3.11) uses another technique and doesn't create a new task internally.
Perhaps it is what are you looking for.
`async-timeout` third-party library works similar to `asyncio.timeout()` but has subtle differences in task cancellation behavior (Python 3.10 and earlier has no important API to backport `asyncio.timeout()` to previous versions with keeping 100% compatibility).

I think the issue should be closed, nothing to do with `wait_for()` code.

**Comment by gvanrossum** [comment]
Oh, maybe this changed in main (3.12)? Since @kumaraditya303’s rewrite of wait_for using timeout, it no longer creates a task.
