### ISSUE TITLE
Bug in Package Multiprocessing

### ISSUE THREAD

**Issue by PriyaKotadiya** [python/cpython#102165]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment
There is a bug in Package Multiprocessing about missed parentheses in print 'Macros:' (SyntexError) in setup.py file, line 94.

**Comment by terryjreedy** [comment]
The standard library multiprocessing directory does not have a setup.py file as it is pre-installed.  If you issue is with a 3rd party package, as on pypi.org, please close this and contact the authors of the package.

**Comment by zware** [comment]
@PriyaKotadiya  The `multiprocessing` project on PyPI is an ancient backport of the standard library `multiprocessing` package that is no longer compatible with any relevant version of Python.  You do not need to install `multiprocessing` separately to use it.
