### ISSUE TITLE
README for Tools directory out of date

### ISSUE THREAD

**Issue by stefan6419846** [python/cpython#102110]
# Documentation

Looking at the README of the *Tools* directory (https://github.com/python/cpython/blob/main/Tools/README), it seems like it is not really up-to-date with the actual directory content:

* Directories like *wasm* do not appear inside it.
* The *parser* directory is documented, but has been removed in https://github.com/python/cpython/commit/27fc3b6f3fc49a36d3f962caac5c5495696d12ed

Some subdirectories (like `Tools/scripts`) have README files which are out-of-date as well.

### Linked PRs
* gh-102550
* gh-102625
* gh-103111

**Comment by sobolevn** [comment]
@stefan6419846 this can be a great first PR! Do you want to fix it? :)

**Comment by stefan6419846** [comment]
I might have a further look at this if I find some more time to do so, although I am not really familiar with the corresponding tools directories and its content.

**Comment by PrajwalNeupane** [comment]
Hey, I am interested in trying to fix this. Please assign it to me and I will get started right away.

**Comment by arhadthedev** [comment]
@PrajwalNeupane It's an open project, no preliminary assignment is required. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

**Comment by Missoupro** [comment]
Hi, I already added a PR to fix this. Hope will be okey, if not, i still available to update it.
