### ISSUE TITLE
`\N` not properly documented in `re` module documentation

### ISSUE THREAD

**Issue by petitchou** [python/cpython#102111]
# Documentation

In the `re` module, the `\N` escape is documented in the changelog from Python 3.8 but never actually explained in the documentation proper. 

The changelog entry (which is quite helpful) says the following:

> Changed in version 3.8: The `'\N{name}'` escape sequence has been added. As in string literals, it expands to the named Unicode character (e.g. `'\N{EM DASH}'`).

While this pretty much hits all the high points of how you'd use `\N`, it still probably ought to be written out a little more formally in the documentation somewhere especially given how thoroughly and with what care the standard library tends to be documented.

### Linked PRs
* gh-106995
* gh-107096

**Comment by hugovk** [comment]
Thanks, fixed during the EuroPython 2023 sprint!

(Merged to `main` and backported to 3.12, we'll see if we need a 3.11 backport (there was a conflict), but we can close this issue now :)
