### ISSUE TITLE
"wikipedia" turtledemo example in docs is supposed to be "rosette"

### ISSUE THREAD

**Issue by SectorCorruptor** [python/cpython#102135]
The `turtle` module documentation, at [this link](https://docs.python.org/3.12/library/turtle.html) has a section on `turtledemo`. It says the demo scripts are 

1. bytedesign
2. chaos
3. clock
4. colormixer
5. forest
6. fractalcurves
7. lindenmayer
8. minimal_hanoi
9. nim
10. paint
11. peace
12. penrose
13. planet_and_moon
14. round_dance
15. sorting_animate
16. tree
17. two_canvases
18. **wikipedia**
19. yinyang

The second last example is wrong. In my Python, the `turtledemo` list shows `wikipedia` as `rosette`. Is the `rosette` title wrong, or is it the `wikipedia` title?

### Linked PRs
* gh-102137
* gh-102138
* gh-102139

**Comment by hugovk** [comment]
Using `git log --all --full-history -- Lib/turtledemo/wikipedia.py`, I see the file was renamed in https://github.com/python/cpython/issues/58325 / https://github.com/python/cpython/pull/8002 but the documentation was updated:

> The 'wikipedia' example is now 'rosette', decribing what it draws.

Would you like to create a PR to update the docs?

The file to change is https://github.com/python/cpython/blob/main/Doc/library/turtle.rst

**Comment by UndoneStudios** [comment]
I don’t know about PRs, but I have changed the file.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by UndoneStudios** [comment]
Yeah, I will

**Comment by hugovk** [comment]
Great! You can create a PR by clicking "Compare" next to the patch-1 branch at https://github.com/UndoneStudios/cpython/branches and then the green "Create pull request".

One suggestion: let's keep them in alphabetical order.

**Comment by UndoneStudios** [comment]
Isn't it already in alphabetical order?

**Comment by hugovk** [comment]
Yes, the original "two_canvases, wikipedia, yinyang" is in alphabetical order, but "two_canvases, rosette, yinyang" isn't.

**Comment by UndoneStudios** [comment]
Well, keeping it in alphabetical order is a pain. Hold on as I try to modify it...

**Comment by UndoneStudios** [comment]
Hold on, there's another issue. `sorting_animate` is missing!

**Comment by UndoneStudios** [comment]
I'm a little busy right now, so I can't make the PR request

**Comment by hugovk** [comment]
It's been broken for 11 years, so no rush :)

The thing to do would be to cut the three lines 2460-2462 and paste them at line 2447, before round_dance.

**Comment by UndoneStudios** [comment]
Thanks a lot for that tip!

**Comment by UndoneStudios** [comment]
I... don't think it went well:
https://github.com/python/cpython/pull/102137

**Comment by hugovk** [comment]
Thanks, that's looking good, I'll review it!

**Comment by hugovk** [comment]
Thanks again for reporting and fixing this 🚀

**Comment by terryjreedy** [comment]
Thanks for catching this.  I changed the name 5 years ago and did not notice the reference in the doc.
