### ISSUE TITLE
test_implied_dirs_performance is flaky

### ISSUE THREAD

**Issue by jaraco** [python/cpython#102209]
Reported [in discord](https://discord.com/channels/854719841091715092/868504620970962944/1078325012651593768), since #102018, the timing check was added to `test_implied_dirs_performance` and this check is frequently failing ([example](https://github.com/python/cpython/actions/runs/4248047744/jobs/7386765925)):

```
ERROR: test_implied_dirs_performance (test.test_zipfile.test_path.TestPath.test_implied_dirs_performance)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\contextlib.py", line 80, in inner
    with self._recreate_cm():
  File "D:\a\cpython\cpython\Lib\test\test_zipfile\_context.py", line 30, in __exit__
    raise DeadlineExceeded(duration, self.max_duration)
test.test_zipfile._context.DeadlineExceeded: (3.140999999999849, 3)
```

These failures aren't occurring on [zipp](/jaraco/zipp), where the check has been running for years without fail.

Furthermore, the check is currently not capturing the failure case because the invocation fails to consume the generator:

https://github.com/python/cpython/blob/9f3ecd1aa3566947648a053bd9716ed67dd9a718/Lib/test/test_zipfile/test_path.py#L336

That indicates that the flaky failures are due to the construction of test data:

https://github.com/python/cpython/blob/9f3ecd1aa3566947648a053bd9716ed67dd9a718/Lib/test/test_zipfile/test_path.py#L335

### Linked PRs
* gh-102225
* gh-102232

**Comment by jaraco** [comment]
Some have suggested to replace the check with something that asserts the algorithmic complexity.

I've confirmed that after addressing the correctness of the check, the tests fail if I apply this diff:

```diff
diff --git a/zipp/__init__.py b/zipp/__init__.py
index f06e9fcc..6a60fc0a 100644
--- a/zipp/__init__.py
+++ b/zipp/__init__.py
@@ -63,7 +63,7 @@ def _difference(minuend, subtrahend):
     Return items in minuend not in subtrahend, retaining order
     with O(1) lookup.
     """
-    return itertools.filterfalse(set(subtrahend).__contains__, minuend)
+    return (item for item in minuend if item not in subtrahend)


```

**Comment by zooba** [comment]
Experimentally verifying linear time is probably fine.

I suspect the reason it's failing now is because we run a lot of our CI tests against debug builds, rather than the fully optimised builds that were being used externally. So even measuring once for a small N and extrapolating a suitable timeout for a larger N is probably going to be fine - it's just the fixed 3 seconds is based on a different baseline.

**Comment by jaraco** [comment]
I've started work in https://github.com/jaraco/jaraco.test/blob/main/jaraco/test/complexity.py to attempt to test for linear time complexity of a function, but I'm finding the test is very flaky (failing 10-20%, especially in CI).

So rather than leave CPython CI in a flaky state, I've proposed #102225 to disable the flaky check for now.

**Comment by jaraco** [comment]
Turns out there already exists a sophisticated library to calculate a best-fit time complexity, [big-O](https://pypi.org/project/big-O). That library does just what's needed.

**Comment by jaraco** [comment]
Annoyingly, the fix in zipp isn't portable to CPython (because it depends on numpy), so the solution here will be just to skip the test (unless `big_o` is importable). The complexity constraint will have to be maintained in zipp.
