### ISSUE TITLE
Acceptance of bool objects by complex() is not tested

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102252]
Such operations as `complex(False) == 0j` is not covered by `test_bool.py`

### Linked PRs
* gh-102253
* gh-102257
* gh-102258

**Comment by terryjreedy** [comment]
Since `isinstance(False, int) == True` and `False == 0`, complex(False) must be complex(0) unless specifically excepted.  But looking as the other tests, the addition is reasonable.
