### ISSUE TITLE
potential nullptr dereference + use of uninitialized memory in fileutils

### ISSUE THREAD

**Issue by maxbachmann** [python/cpython#102281]
# Bug report

https://github.com/python/cpython/blob/6daf42b28e1c6d5f0c1a6350cfcc382789e11293/Python/fileutils.c#L2161-L2162 can lead to use of uninitialized memory when `join_relfile` fails.

https://github.com/python/cpython/blob/6daf42b28e1c6d5f0c1a6350cfcc382789e11293/Python/fileutils.c#L2197-L2199 in combination with https://github.com/python/cpython/blob/6daf42b28e1c6d5f0c1a6350cfcc382789e11293/Modules/getpath.c#L450

leads to a nullptr dereference.

### Linked PRs
* gh-102282
* gh-103040

**Comment by hauntsaninja** [comment]
Thanks for the fix! Looks like this could still use backports

**Comment by maxbachmann** [comment]
Thanks for the reminder

**Comment by hauntsaninja** [comment]
Thanks again :-)
