### ISSUE TITLE
polynomial_from_roots itertools recipe is exponential

### ISSUE THREAD

**Issue by pochmann** [python/cpython#102210]
# Documentation

It goes through all combinations, i.e., the whole power set, and thus takes exponential time:

https://github.com/python/cpython/blob/347f7406df62b2bbe551685d72a466f27b951f8e/Doc/library/itertools.rst?plain=1#L869-L879

It can be done in quadratic time by incorporating one root at a time. If you have the polynomial for the first few roots and want to multiply it with `(x - root)` for the next root, just multiply it with `x` (i.e., append `0` coefficient), multiply it with `root`, and subtract:

```python
def polynomial_from_roots(roots):
    coeffs = [1]
    for r in roots:
        coeffs.append(0)
        for i, c in enumerate(coeffs[:-1], 1):
            coeffs[i] -= c * r
    return coeffs
```

Runtimes for `roots = range(n)`:
```
n   current    new
20  0.219 s  4.00 μs
21  0.527 s  4.27 μs
22  1.083 s  6.09 μs
23  2.090 s  5.09 μs
24  4.234 s  5.38 μs
25  9.207 s  6.20 μs
```
Granted , the current version shows off a neat-looking combination of tools, which mine doesn't. But the recipes are also advertised as "High speed", and exponential is far from that. Not sure what to do.

**Comment by rhettinger** [comment]
Dude, this is just a demonstration recipe.  People are not actually computing large polynomials this way.

I think your zeal for speed may be causing you to "miss the forrest for the trees"

**Comment by pochmann** [comment]
I didn't say they should be as fast as possible. But like I said, the recipes are advertised as "High speed", and exponential really isn't. Exponential-vs-quadratic is also quite different from those other suboptimalities you mentioned.

Also note I didn't suggest mine should be used. I just used it to illustrate that the current one is very slow. I thought maybe a short remark about the slowness would be helpful in order to not mislead people.

The recipe also made it into `more-itertools`, also without a warning about the slowness, and you yourself said *"Users of that package just want results and typically don't look at the underlying code"*, so they might use it and not realize there's something far faster.

**Comment by rhettinger** [comment]
> But like I said, the recipes are advertised as "High speed"

Please don't become pushy and argumentative.  The "high speed" refers to using "vectorized" fast building blocks written in C versus pure python code.   It also refers to the memory (and hence speed) advantages of using iterators.

In `more-itertools`, they will happily accept convoluted and optimized code updates because their users normally use the tools instead of reading them.  Mostly though, they start with the simplest thing that could possibly work and they don't have any C implementations, because speed is not their focus.
