### ISSUE TITLE
pathlib mkdir bug on giving "other" "write" permission

### ISSUE THREAD

**Issue by artzet-s** [python/cpython#102224]
When I try to create a directory with pathlib.mkdir and specific permission. The write permission for "other" is ignored each time.

I do not have this behavior with os lib (os.mkdir + os.chmod).

I try several configuration, and verify the same results with my "ls -l" system command. 

My system

    lsb_release -a

>     No LSB modules are available.
>     Distributor ID:	Ubuntu
>     Description:	Ubuntu 20.04.5 LTS
>     Release:	20.04
>     Codename:	focal

Tested on multiple mamba environment with

* Python 3.10.9
* Python 3.7.12
* Python 3.7.16 ( mamba create -n test python=3.7)

Code to reproduce

    import os
    import pathlib
    
    for u in [0, 2, 4, 6, 7]:
        for g in [0, 2, 4, 6, 7]:
            for o in [0, 2, 4, 6, 7]:
                p = pathlib.Path(f"dir_{u}{g}{o}")
                mode = int(f"{u}{g}{o}", 8)
    
                p.mkdir(mode=mode)
                p_mkdir_with_pathlib = oct(p.stat().st_mode)
                os.rmdir(p)
    
                os.mkdir(p)
                os.chmod(p, mode=mode)
                p_mkdir_with_os = oct(p.stat().st_mode)
                os.rmdir(p)
    
                print(p, p_mkdir_with_os, p_mkdir_with_pathlib)

My output 

      

>         dir_000 0o40000 0o40000
>         dir_002 0o40002 0o40000
>         dir_004 0o40004 0o40004
>         dir_006 0o40006 0o40004
>         dir_007 0o40007 0o40005
>         dir_020 0o40020 0o40020
>         dir_022 0o40022 0o40020
>         dir_024 0o40024 0o40024
>         dir_026 0o40026 0o40024
>         dir_027 0o40027 0o40025
>         dir_040 0o40040 0o40040
>         dir_042 0o40042 0o40040
>         dir_044 0o40044 0o40044
>         dir_046 0o40046 0o40044
>         dir_047 0o40047 0o40045
>         dir_060 0o40060 0o40060
>         dir_062 0o40062 0o40060
>         dir_064 0o40064 0o40064
>         dir_066 0o40066 0o40064
>         dir_067 0o40067 0o40065
>         dir_070 0o40070 0o40070
>         dir_072 0o40072 0o40070
>         dir_074 0o40074 0o40074
>         dir_076 0o40076 0o40074
>         dir_077 0o40077 0o40075
>         dir_200 0o40200 0o40200
>         dir_202 0o40202 0o40200
>         dir_204 0o40204 0o40204
>         dir_206 0o40206 0o40204
>         dir_207 0o40207 0o40205
>         dir_220 0o40220 0o40220
>         dir_222 0o40222 0o40220
>         dir_224 0o40224 0o40224
>         dir_226 0o40226 0o40224
>         dir_227 0o40227 0o40225
>         dir_240 0o40240 0o40240
>         dir_242 0o40242 0o40240
>         dir_244 0o40244 0o40244
>         dir_246 0o40246 0o40244
>         dir_247 0o40247 0o40245
>         dir_260 0o40260 0o40260
>         dir_262 0o40262 0o40260
>         dir_264 0o40264 0o40264
>         dir_266 0o40266 0o40264
>         dir_267 0o40267 0o40265
>         dir_270 0o40270 0o40270
>         dir_272 0o40272 0o40270
>         dir_274 0o40274 0o40274
>         dir_276 0o40276 0o40274
>         dir_277 0o40277 0o40275
>         dir_400 0o40400 0o40400
>         dir_402 0o40402 0o40400
>         dir_404 0o40404 0o40404
>         dir_406 0o40406 0o40404
>         dir_407 0o40407 0o40405
>         dir_420 0o40420 0o40420
>         dir_422 0o40422 0o40420
>         dir_424 0o40424 0o40424
>         dir_426 0o40426 0o40424
>         dir_427 0o40427 0o40425
>         dir_440 0o40440 0o40440
>         dir_442 0o40442 0o40440
>         dir_444 0o40444 0o40444
>         dir_446 0o40446 0o40444
>         dir_447 0o40447 0o40445
>         dir_460 0o40460 0o40460
>         dir_462 0o40462 0o40460
>         dir_464 0o40464 0o40464
>         dir_466 0o40466 0o40464
>         dir_467 0o40467 0o40465
>         dir_470 0o40470 0o40470
>         dir_472 0o40472 0o40470
>         dir_474 0o40474 0o40474
>         dir_476 0o40476 0o40474
>         dir_477 0o40477 0o40475
>         dir_600 0o40600 0o40600
>         dir_602 0o40602 0o40600
>         dir_604 0o40604 0o40604
>         dir_606 0o40606 0o40604
>         dir_607 0o40607 0o40605
>         dir_620 0o40620 0o40620
>         dir_622 0o40622 0o40620
>         dir_624 0o40624 0o40624
>         dir_626 0o40626 0o40624
>         dir_627 0o40627 0o40625
>         dir_640 0o40640 0o40640
>         dir_642 0o40642 0o40640
>         dir_644 0o40644 0o40644
>         dir_646 0o40646 0o40644
>         dir_647 0o40647 0o40645
>         dir_660 0o40660 0o40660
>         dir_662 0o40662 0o40660
>         dir_664 0o40664 0o40664
>         dir_666 0o40666 0o40664
>         dir_667 0o40667 0o40665
>         dir_670 0o40670 0o40670
>         dir_672 0o40672 0o40670
>         dir_674 0o40674 0o40674
>         dir_676 0o40676 0o40674
>         dir_677 0o40677 0o40675
>         dir_700 0o40700 0o40700
>         dir_702 0o40702 0o40700
>         dir_704 0o40704 0o40704
>         dir_706 0o40706 0o40704
>         dir_707 0o40707 0o40705
>         dir_720 0o40720 0o40720
>         dir_722 0o40722 0o40720
>         dir_724 0o40724 0o40724
>         dir_726 0o40726 0o40724
>         dir_727 0o40727 0o40725
>         dir_740 0o40740 0o40740
>         dir_742 0o40742 0o40740
>         dir_744 0o40744 0o40744
>         dir_746 0o40746 0o40744
>         dir_747 0o40747 0o40745
>         dir_760 0o40760 0o40760
>         dir_762 0o40762 0o40760
>         dir_764 0o40764 0o40764
>         dir_766 0o40766 0o40764
>         dir_767 0o40767 0o40765
>         dir_770 0o40770 0o40770
>         dir_772 0o40772 0o40770
>         dir_774 0o40774 0o40774
>         dir_776 0o40776 0o40774
>         dir_777 0o40777 0o40775
> 
> 
>

**Comment by eryksun** [comment]
The equivalent to `p.mkdir(mode=mode)` is [`os.mkdir(p, mode)`](https://docs.python.org/3/library/os.html#os.mkdir). The resulting permissions are subject to the current umask value. For example, if `mode` is `0o777`, and the current umask is `0o002`, then the directory is created with the permissions `0o777 & ~0o002`, which is `0o775`. 

You can set the current umask to 0 via [`os.umask()`](https://docs.python.org/3/library/os.html#os.umask). However, I don't recommend doing this, especially in a multithreaded application, since the current umask value is used by all calls to `os.open()`, `os.mkdir()`, and `os.mkfifo()`.

**Comment by ronaldoussoren** [comment]
As @eryksun writes the mode passed into ``p.mkdir(...)`` is combined with the umask, as mentioned in [the documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.mkdir).

The current behaviour is therefore not a bug.

**Comment by artzet-s** [comment]
Thanks I understood my mistake, yes, it's not a bug.
