### ISSUE TITLE
Improve build support on xbox

### ISSUE THREAD

**Issue by maxbachmann** [python/cpython#102255]
# Feature or enhancement

Since there are probably more game studios using Python for their game scripting, it would be great to have better build support for CPython on the xbox. The xbox runs a windows, but does not provide all the APIs cpython is using under windows.

### Linked PRs
* gh-102256
* gh-102583

**Comment by zooba** [comment]
Thanks @maxbachmann! This was a huge effort, but I think it's worth it. Don't shy away from adjusting things we decided here if it seems important - nothing we changed should count as a public API change, so we can revert or modify if needed.
