### ISSUE TITLE
Add a public version of _AnnotatedAlias into types or typing

### ISSUE THREAD

**Issue by zmievsa** [python/cpython#102261]
# Feature or enhancement

Add a public version of _AnnotatedAlias into types or typing modules

# Pitch

If we wish to check whether something is an instance of `Annotated`, we have to use `type(Annotated[str, str])` or `from typing import _AnnotatedAlias` which is a usage of internal API. In one of my projects, I had to rebuild Annotated alias which meant that I had no standard way of getting the true type of Annotated. We have a similar problem with Union and GenericAlias, and we have their respective types defined in `types` module. Can we and should we do a similar thing for AnnotatedAlias?

I would love to implement this if anyone has any ideas and agrees with my pitch :)

**Comment by JelleZijlstra** [comment]
You should use `typing.get_origin(obj) is typing.Annotated`. Is that not enough?

**Comment by Ovsyanka83** [comment]
Hm.. it feels a bit inconsistent with other examples from types but you are right: it actually fully solves my problem. I just never thought about using get_origin for that for some reason :)

Thank you, @JelleZijlstra !
