### ISSUE TITLE
Improve on documentation for http module

### ISSUE THREAD

**Issue by rodrigomv29** [python/cpython#102200]
# Improve on documentation for http module

(A clear and concise description of your proposal.)

When I read the documentation for the htttp `__init__.py`. There is a long list of rfc codes that don't seem relevant to the http class itself. Please remove this from the file or at least add some context to the RFC codes.

I want to understand how the http library works behind the scenes and the documentation doesn't help

* RFC 7231: Hypertext Transfer Protocol (HTTP/1.1), obsoletes 2616
        * RFC 6585: Additional HTTP Status Codes
        * RFC 3229: Delta encoding in HTTP
        * RFC 4918: HTTP Extensions for WebDAV, obsoletes 2518
        * RFC 5842: Binding Extensions to WebDAV
        * RFC 7238: Permanent Redirect
        * RFC 2295: Transparent Content Negotiation in HTTP
        * RFC 2774: An HTTP Extension Framework
        * RFC 7725: An HTTP Status Code to Report Legal Obstacles
        * RFC 7540: Hypertext Transfer Protocol Version 2 (HTTP/2)
        * RFC 2324: Hyper Text Coffee Pot Control Protocol (HTCPCP/1.0)
        * RFC 8297: An HTTP Status Code for Indicating Hints
        * RFC 8470: Using Early Data in HTTP

**Comment by hugovk** [comment]
Do you mean this list?

https://github.com/python/cpython/blob/3b4f8fc83dcea1a9d0bc5bd33592e5a3da41fa71/Lib/http/__init__.py#L8-L24

The context is given, they're the RFC specs from which HTTP status codes have been implemented. 

We can see a similar list in the docs, which also lists the status codes: for each RFC:

https://docs.python.org/3/library/http.html#http-status-codes

**Comment by rodrigomv29** [comment]
Thanks for the explanation!
