### ISSUE TITLE
importlib.resources: "Deprecated functions" heading should be a subheading

### ISSUE THREAD

**Issue by yrro** [python/cpython#102215]
# Documentation

The "Deprecated functions" heading at https://github.com/python/cpython/blob/1fa38906f0b228e6b0a6baa89ab6316989b0388a/Doc/library/importlib.resources.rst#deprecated-functions, when rendered, appears alongside the "importlib.resources - Resources" heading. It probably shouldn't appear on that page at all since it's just a subsection of the "importlib.resources" page.

![image](https://user-images.githubusercontent.com/309468/221196837-5950ebb4-a9d6-46b9-9894-0513beb01ab1.png)

### Linked PRs
* gh-102217
* gh-108023
* gh-108056

**Comment by hugovk** [comment]
Thanks for the report, would you like to create a PR to fix it?

**Comment by daniel-shimon** [comment]
Hi, shouldn't this issue be closed?

**Comment by hugovk** [comment]
It should, thank you for the ping!
