### ISSUE TITLE
.HTML files won't send with ftp.storebinary

### ISSUE THREAD

**Issue by funprogrammer89** [python/cpython#102288]
# Bug report

I am unable to use ftp.storebinary to send .HTML files. HTML files are the only files I have run into so far. I can send all other files I have tried including but not limited to, .txt, .js , .jpg, .bmp ...

# Your environment

- CPython versions tested on:
- Operating system and architecture: Windows 11, Python 3.9.7

**Comment by arhadthedev** [comment]
@giampaolo (as an ftp module expert), @gpshead (as an active networking expert)

**Comment by funprogrammer89** [comment]
Thanks for labeling!

**Comment by ericvsmith** [comment]
There's not enough information here to know if this is a bug.

What code did you try, and what error did you get? What server were  you talking to?

**Comment by funprogrammer89** [comment]
I am not sure if this is a bug it just is a weird issue I am having. It is most likely not a bug but just an issue I am having. I have seen a similar issue on another forum, https://stackoverflow.com/questions/19865512/using-ftplib-to-upload-a-200kb-html-page, but nothing that addresses the exact issue I am having.

I don't seem to get an error. The code executes but the file does not transfer. If I transfer a bunch of different types of files, they seem to all transfer minus my .HTML files. 

If it helps this is the line of code I am using for sending,

ftp.storbinary('STOR ' + Temp[len(Temp) - 1], open(x, 'rb'))

I am communicating with [Infinity Free](https://www.infinityfree.net/) hosting provider FTP where I have my website files. 

My project is here, https://github.com/funprogrammer89/Git-FTP-Py/blob/main/gitFTP.py

Thanks for your help. Any other information you need to assist in the resolution of this issue I am happy to provide!

**Comment by ericvsmith** [comment]
It would be helpful if you could reduce this to a 3 or 4 line example that just tries to send the one file. It needs to be a piece of code we can run, although I realize we might need to use a different server.

**Comment by funprogrammer89** [comment]
I will write a simple program to send a single HTML file using ftplib and share the results. Stay tuned.

**Comment by funprogrammer89** [comment]
I wrote this simple app to try and send an HTML file and python executes the code with no errors but no HTML file is uploaded to the FTP server. Other file types can be uploaded with the below code but not HTML files... I am stumped.

import ftplib
ftp = ftplib.FTP("ftpupload.net")   # FTP URL
ftp.login("username", "password")  # FTP ([Username],[Password])
ftpPath = '/test/'
ftp.cwd(ftpPath)    # FTP directory

ftp.storbinary('STOR ' + 'site.txt', open(r'C:\Users\whybo\Desktop\skills.txt', 'rb'))

**Comment by ericvsmith** [comment]
Again: what error did you get?

**Comment by ericvsmith** [comment]
Also, I suggest you call `set_debuglevel(2)` to see what's going on, and post the output here. It wouldn't surprise me if the server is configured to refuse html files.

**Comment by funprogrammer89** [comment]
My FTP provider will now allow me to install .HTML files outside of the designated location.. Problem Solved! Thanks for all the help!
