### ISSUE TITLE
platform.py cannot parse cpython version string with "packaged by Anaconda, Inc."

### ISSUE THREAD

**Issue by Phynon** [python/cpython#102396]
# Bug report

platform.py cannot parse cpython version correctly.
ValueError `ValueError: failed to parse CPython sys.version: '3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'` is raised.

# Your environment

- CPython versions tested on: 3.10.9
- Operating system and architecture: Windows 11 22621.1343, amd64

**Comment by ericvsmith** [comment]
Please show the code which raises this error.

**Comment by Phynon** [comment]
> Please show the code which raises this error.


It's raised by the [log.py](https://github.com/microsoft/debugpy/blob/5601342de87e6a08d909db51a2df0d8dff8d51f7/src/debugpy/common/log.py#L59) in the debugpy module shipped with vscode-python extension, where it calls `platform.python_implementation()`.

Additionally, my miniconda version is py310_23.1.0-1, vscode version is , and vscode-python extension version is v2023.4.0.

`sys.version` gives the value `'3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]'` when I check my cpython version in interactive python console.

**Comment by corona10** [comment]
IMO, I think that you should report the issue to Anaconda, not here.
The binary is packaged by Anacona.Inc and they modified several code.

**Comment by Phynon** [comment]
Thanks I see.

> they modified several code.

I'm sorry for not noticing that.
