### ISSUE TITLE
Check documentation of PyObject_CopyData

### ISSUE THREAD

**Issue by purpleKarrot** [python/cpython#102383]
According to the documentation, `PyObject_CopyData` takes two arguments of type `Py_buffer*`:
https://github.com/python/cpython/blob/71db5dbcd714b2e1297c43538188dd69715feb9a/Doc/c-api/buffer.rst?plain=1#L502

But in the implementation, it actually takes two arguments of `PyObject*`:
https://github.com/python/cpython/blob/71db5dbcd714b2e1297c43538188dd69715feb9a/Objects/abstract.c#L613

### Linked PRs
* gh-102390
* gh-102401

**Comment by terryjreedy** [comment]
I few lines below, abstract.c has
```
    if (!PyObject_CheckBuffer(dest) ||
        !PyObject_CheckBuffer(src)) {
        PyErr_SetString(PyExc_TypeError,
                        "both destination and source must be "\
                        "bytes-like objects");
```
So the 'PyObjects' indeed have to be buffer-like.  I don't know the technical details, but I suspect that there is no real bug.

**Comment by ronaldoussoren** [comment]
> I don't know the technical details, but I suspect that there is no real bug.

There is a bug as the documentation does not match the implementation, ``Py_buffer`` is not a Python object. In this case IMHO the documentation should be fixed.

**Comment by sobolevn** [comment]
Yes, `PyObject_CheckBuffer` looks like so:

```c
int
PyObject_CheckBuffer(PyObject *obj)
{
    PyBufferProcs *tp_as_buffer = Py_TYPE(obj)->tp_as_buffer;
    return (tp_as_buffer != NULL && tp_as_buffer->bf_getbuffer != NULL);
}
```

So, there's clearly a bug in the docs. PR is sent :)
Thanks a lot for the report!
