### ISSUE TITLE
Add the default attributes to `functools.partial`

### ISSUE THREAD

**Issue by JensHeinrich** [python/cpython#102323]
# Feature or enhancement

Add `__qualname__` and `__name__` to `functools.partial`

# Pitch

Even an anonymous `lambda` function gets a `__qualname__` or rather `__name__` of `<lambda>` and `partial` should behave in the same way.

# Previous discussion

This has been previously discussed in #78656, but as `lambda`-functions are named since ~before ccd19218bcc~ 363ac7d5b6513e68b61008e2867ef23886e70619 a similiar behavior of using `<partial>` as the name should have been suggested in the last discussion already.

**Comment by sobolevn** [comment]
Why do you need this? There are other callable objects that can miss `__qualname__`:

```python
>>> class MyCallable:
...     def __call__(self, *args, **kwargs):
...         print('whatever')
... 
>>> MyCallable()()
whatever
>>> MyCallable().__qualname__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'MyCallable' object has no attribute '__qualname__'
```

What is so special about `partial`?

Isn't `getattr(obj, '__qualname__', '<default name>')` is not enough?

**Comment by JensHeinrich** [comment]
That's a valid workaround for the usecase that prompted this ticket, but I still feel it wouldn't hurt to just use `<partial>` as a `__name__` attribute

**Comment by sobolevn** [comment]
@JensHeinrich the problem with adding `__name__` and `__qualname__` attributes to `partial` is that it is not enough. There are also `__annotations__` and `__code__` attributes (and others) that people might assume all callables have. So, it is either full compatibility with the callable API or just `__call__` as it is now.

I prefer the status quo :)
And based on previous descussion I will close this ticket.

I hope my explanation helped! Thanks for the report.

**Comment by JensHeinrich** [comment]
I do get the reasoning, but I will mention the discussion in #91002 as I see those points are related. This hopefully helps future me or other people researching it.
