### ISSUE TITLE
(🐞) Column marker in error message off when line contains non ASCII character

### ISSUE THREAD

**Issue by KotlinIsland** [python/cpython#102310]
```py
b"Ā"
```
```
👉 python test.py
  File "/test.py", line 1
    b"Ā"
         ^
SyntaxError: bytes can only contain ASCII literal characters
```
Here the caret is pointing to blackspace after the code

So each non-ASCII character is adding more incorrect offset:
```
👉 $c:temp = "b'ĀĀĀĀĀĀĀĀ'"
👉 py temp
  File "C:\temp", line 1
    b'ĀĀĀĀĀĀĀĀ'
                       ^
```

## Expected
```
👉 python test.py
  File "/test.py", line 1
    b"Ā"
      ^
SyntaxError: bytes can only contain ASCII literal characters
```

### Linked PRs
* gh-103663
* gh-103703

**Comment by arhadthedev** [comment]
Can confirm on `Python 3.12.0a5+ (heads/main:bcadcde712, Feb 26 2023, 12:54:46) [MSC v.1929 64 bit (AMD64)] on win32`.

Note: `Ā` here is UTF8-encoded as `C4 80` (a single U+0100 LATIN CAPITAL LETTER A WITH MACRON). So incorrect row advancing on combined code points is totally ruled out until text normalization happens inside the parser.

**Comment by arhadthedev** [comment]
@benjaminp, @pablogsal (as parser experts)

**Comment by terryjreedy** [comment]
In IDLE, Python 3.12.0a5+ (heads/main:0f89acf6cc, Feb 27 2023, 21:33:28) says "incomplete input" for this and `"\N{a}"`, reported in #102312, and marks the closing quote, but this is effect of how codeop compiles.
In REPL, I see the above and the #102312 message.   I closed #102312 as duplicate.

**Comment by terryjreedy** [comment]
Verified bug in installed 3.10.10, 3.11.2, and 3.12.a5.

**Comment by sobolevn** [comment]
What do you think about this?

```
» ./python.exe ex.py
  File "/Users/sobolev/Desktop/cpython/ex.py", line 1
    x = b"Ā"
        ^^^^^
SyntaxError: bytes can only contain ASCII literal characters
```

This can be achieved with: 
<img width="752" alt="Снимок экрана 2023-02-28 в 14 02 29" src="https://user-images.githubusercontent.com/4660275/221835436-afff0ff4-dae7-4e8f-b621-0fe4127013f9.png">

Or do we need to highlight the symbol exactly?

**Comment by KotlinIsland** [comment]
```
👉 $c:temp.py = "b'Ā'"
👉 py temp.py
  File "C:\temp.py", line 1
    b'Ā'
         ^
SyntaxError: bytes can only contain ASCII literal characters
👉 $c:temp.py = "'\N{a}'"
👉 py temp.py
  File "C:\temp.py", line 1
    '\N{a}'
           ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 0-4: unknown Unicode character name
```

**Comment by arhadthedev** [comment]
> If my solution is fine, I can add a test case and send a PR.

@sobolevn In absence of other feedback, your solution looks better than nothing. So it's worth to create a PR and get it merged before 3.12b1.

**Comment by sobolevn** [comment]
Will do :)

**Comment by lysnikolaou** [comment]
Can this be closed?
