### ISSUE TITLE
SMTP

### ISSUE THREAD

**Issue by myk-coder** [python/cpython#102391]
Inquiries

1>Where do I get quality SMTP Servers that work?
2>Suggest one repository i can utilise the SMTP to mail in HTML form.

### Linked PRs
* gh-128309

**Comment by AlexWaygood** [comment]
Please ask questions like this at https://discuss.python.org/ rather than on the GitHub issue tracker, which is intended for tracking known bugs in CPython

**Comment by myk-coder** [comment]
thank you @AlexWaygood 

I believe this repository would work for sending html emails right?

**Comment by AlexWaygood** [comment]
I'm afraid I don't understand your question
