### ISSUE TITLE
Pool spawns way too many subprocesses in map() when cgroup cpu.shares is default or set high

### ISSUE THREAD

**Issue by mvpel** [python/cpython#102375]
I have a user running some proprietary code that is misbehaving in the multiprocessing.map() function.

In the HTCondor scheduler, each job is assigned a cpu.shares number of 100 times the number of CPUS requested for the job.

When submitting a 40-worker pool, the pstree looks very orderly when the CPU request to HTCondor is set to 1 - the main python process has 40 child processes and no more, the load average climbs to about 40 and stays there, and the job crunches its numbers and returns a result in the expected time. Each python child process' cpu.shares cgroup value is set to 100, inherited from the parent process that HTCondor launched, and each of them uses about 100% cpu time shown in "top."

When the CPU request is set to 40, however, and cpu.shares is set to 4000 as a result, pstree shows the main process, the child processes and then, unexpectedly, there are child processes of the child processes, as if each of the 40 pool workers is trying to use 40 CPUs instead of one. The load average soon spikes above 1,000, the context switching goes through the roof, and the job slows to a crawl.

The code has the expected if __name__=='__main__' statement to shelter the master process' code, and the start method is set to "spawn" with force set to True.

I'm working on gathering snapshots of the behavior, I'll post them on this issue shortly, but if anyone has any ideas in the meantime as to what might be going on, I'd appreciate the feedback.

**Comment by ericvsmith** [comment]
Without seeing the code that causes this, tracking it down will be very difficult. See if you can reproduce a small example that we can run.

**Comment by mvpel** [comment]
Here's an example of a well-behaved run, with cpu.shares set to 100:

```
(base) [pelletm@padtiphtcg04 ~]$ pstree 3138124
python─┬─python
       ├─40*[python───{python}]
       └─4*[{python}]
(base) [pelletm@padtiphtcg04 ~]$ uptime
 12:33:18 up 90 days, 23:12,  1 user,  load average: **29.33**, 31.07, 28.96
(base) [pelletm@padtiphtcg04 ~]$ 
```

Here's the cgroup cpu.shares established by HTCondor for the job:

```
$ pwd
/sys/fs/cgroup/cpu/htcondor/condor_var_lib_condor_execute_slot1_1@padtiphtcg04.and.us.ray.com
$ cat cpu.shares
100
$
```

Here's a malfunctioning run:

```
(base) [pelletm@padtiphtcx07 ~]$ pstree 364925
run_simple.sh───python─┬─python
                       ├─40*[python───32*[{python}]]
                       └─35*[{python}]
(base) [pelletm@padtiphtcx07 ~]$ uptime
 12:44:28 up 72 days,  1:03,  1 user,  load average: **941.71**, 368.50, 135.91
(base) [pelletm@padtiphtcx07 ~]$
```

Note that each of the 40 workers has 32 children. Here's the cpu.shares as established by HTCondor due to the job's request for 40 CPUs::

```
$ pwd
/sys/fs/cgroup/cpu/htcondor/condor_var_lib_condor_execute_slot1_1@padtiphtcx07.and.us.ray.com
$ cat cpu.shares
4000
$
```

The load average seems to have leveled off at about 1,100, and context switching, as you might expect, has skyrocketed.

**Comment by mvpel** [comment]
My colleague cooked up a reproducer:

[simple_mp_test.py.txt](https://github.com/python/cpython/files/10874534/simple_mp_test.py.txt)

**Comment by mvpel** [comment]
Some additional information about the environment: Centos 7, kernel 3.10.0-1160.80.1.el7.x86_64, The problem occurs on the command line as well, so the reproducer shouldn't need any other infrastructure. Here's a reproducer run with 16 workers from a shell:
```
python─┬─python
       ├─16*[python───39*[{python}]]
       └─3*[{python}]
```

**Comment by mvpel** [comment]
Okay, I found the root cause. It turns out it's originating in NumPy, not multiprocessing.

The issue isn't stemming from cgroups, but rather the fact that HTCondor sets the OMP_NUM_THREADS environment variable in the job to the number of CPUs requested by the job, while SLURM leaves it blank.

When it's blank, NumPy evidently assumes that it has leave to use every CPU on the system, and so each multiprocessing worker making NumPy calls gets threads equaling the total number of CPUs on the system, minus one for the worker. Neither I nor my colleague were aware of this behavior of NumPy, hence our puzzlement.

By adding:

`os.environ["OMP_NUM_THREADS"] = "1"`

... to the reproducer, the problem goes away and the job runs normally with the specified number of mp workers, with each using only one thread for its NumPy work.

Thanks, and sorry for the false alarm.
