### ISSUE TITLE
Segmentation fault under Python 3.9.12

### ISSUE THREAD

**Issue by YaoJiayi** [python/cpython#102329]
# Crash report
The following code snippet crashes with core dumped:
```python
import unittest
from test import support
import sys

class Tests(unittest.TestCase):
    def test_bug(self):
        modules = set()
        for name, module in sys.modules.items():
            modules.add(module)
        new_tuples = tuple(modules)
        new_set = set(new_tuples)
        print('')
        print('sys.modules:')
        print('')
        import pprint
        pprint.pprint(modules)
        print('')
        print('len(sys.modules):', len(modules))


def test_main():
    support.run_unittest(Tests)

if __name__ == '__main__':
    test_main()
```

# Error messages
```
(<object object at 0x7f0fe7b6d6a0>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>, <NULL>)
Segmentation fault (core dumped)
```
# Your environment

- CPython versions tested on: Python 3.9.12
- Operating system and architecture: Linux hx-rs4810gs 5.15.0-57-generic 63~20.04.1-Ubuntu SMP Wed Nov 30 13:40:16 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zware** [comment]
I can't reproduce this on Linux 6.0.12-76060006-generic #202212290932~1674139725~22.04~ca93ccf SMP PREEMPT_DYNAMIC Thu J x86_64 with Python 3.9.14.  Can you reproduce with any other version?

**Comment by YaoJiayi** [comment]
I've just tried Python 3.8.16. It has the same error message.

**Comment by terryjreedy** [comment]
Please reduce the code to the minimum needed to get a crash and then indicate which line it crashes on.

**Comment by YaoJiayi** [comment]
It seems that "from test import support" produces the crash.

**Comment by zware** [comment]
Is that your own `test.support` module, or the private helper from the standard library test suite?
