### ISSUE TITLE
Interpreter does not handle subtle use cases of boolean context

### ISSUE THREAD

**Issue by wrongnull** [python/cpython#102332]
According to python's data model ```NotImplemented``` should not be used in boolean context. So that user should not use it in the comparison of objects. However it happens in various places of interpreter internals. For instance:

```python
object() == None #False
object().__eq__(None) #NotImplemented
bool(NotImplemented) #DeprecationWarning
```

or

```python
class A:
    def __eq__(self, other):
        return NotImplemented

A() == 1 #False
```

It happens because of ```do_richcompare``` function which has special considerations for ```Py_NotImplemented```
Should we replace this one to something else? ```None``` would be suitable, I guess. If so, I'm ready to send a PR for this 😃

**Comment by JelleZijlstra** [comment]
What exactly is the problem you see here?

`NotImplemented` is treated specially in the return value of dunder methods; it usually means to delegate to some other object. In your examples, if for `A == B`, `A.__eq__(B)` returns `NotImplemented`, we try `B.__eq__(A)` instead.

**Comment by wrongnull** [comment]
> What exactly is the problem you see here?

quote from the docs: ```Evaluating NotImplemented in a boolean context is deprecated```. If there is no problem, documentation have to reference this special case, haven't it?

**Comment by JelleZijlstra** [comment]
That sentence refers to doing e.g. `if NotImplemented:`, not to the return value of `__eq__`.

**Comment by wrongnull** [comment]
> That sentence refers to doing e.g. `if NotImplemented:`, not to the return value of `__eq__`.

Ridiculous. User can write something like this

```python
class A:
    def __eq__(self, other):
        return NotImplemented

if A() == A():
    print(1)
else:
    print(2)
```

**Comment by JelleZijlstra** [comment]
The value of `A() == A()` in that example is `False`, not `NotImplemented`. In Python, `a == b` is *not* just semantic sugar for `a.__eq__(b)`; the semantics are more complicated.

I'm closing this issue as there is no bug here.

**Comment by AlexWaygood** [comment]
You might be interested in this blog post, which goes into detail about how Python's comparison operators work, and which discusses the semantics of returning `NotImplemented` from a comparison method: https://snarky.ca/unravelling-rich-comparison-operators/
