### ISSUE TITLE
Allow range to represent open ranges

### ISSUE THREAD

**Issue by jonasrauber** [python/cpython#102364]
Currently, range can only hold fixed-size ranges.
It would be great if `range` would accept `stop = None` to represent open ranges.

```
range(3, None)
```

This would allow checks like `5 in range(3, None)`, where the range was for example created by parsing a command line argument `'3:'`.

Slices don't work for this, see also https://github.com/python/cpython/issues/102361.

All methods of `range` would naturally generalize to this, except for `__len__`, which could raise an error if called on an open range.

**Comment by rhettinger** [comment]
Please take this to the python-ideas list.  Expect to be asked why `x in range(3, None)` would be preferable to `x > 3`.
