### ISSUE TITLE
False logic

### ISSUE THREAD

**Issue by przemgroch** [python/cpython#102369]
In this code, the if statement evaluates to true, but both parts of the conditional are false.

```python
B=2
if B<1 | B>2:
   return 0
return 1
```

**Comment by chgnrdv** [comment]
The `|`  operator (bitwise OR) has higher precedence than comparison operators, so given condition expression evaluates as
```python
B < (1 | B) > 2
```
which is equivalent to 
```python
B < (1 | B) and (1 | B) > 2
```
that is `True`.

https://docs.python.org/3/reference/expressions.html#operator-precedence
https://docs.python.org/3/reference/expressions.html#comparisons

**Comment by AlexWaygood** [comment]
Thanks @chgnrdv for the excellent explanation.

@przemgroch, it looks like you might be new to learning Python. The GitHub issue tracker is for bugs in CPython itself, and it's quite unlikely that you'll stumble upon one of those if you're just starting out. In the future, a better place to ask this kind of question would be https://discuss.python.org/c/users/7. Good luck! :)

**Comment by AlexWaygood** [comment]
As well as the docs @chgnrdv posted above, you may also find this blog post interesting: https://mathspp.com/blog/pydonts/chaining-comparison-operators#pitfalls

**Comment by przemgroch** [comment]
I'm new to python, before that i used C++ and there operator > has higher precedence than OR.
Even ChatGPT thought diffrent:
![image](https://user-images.githubusercontent.com/126773674/222419283-6f3ec7aa-3921-4540-8b95-362f3341f7f5.png)

**Comment by ericvsmith** [comment]
I think we’ve learned something about relying on ChatGPT!

**Comment by CAM-Gerlach** [comment]
> I'm new to python, before that i used C++ and there operator > has higher precedence than OR.

The same is true of Python: `>` has higher precedence than `or`. It is only bitwise or (`|` that has higher precedence than comparison. 

This is arguably somewhat suboptimal in hindsight as it makes common array-wise operations with Pandas, NumPy, etc. not behave as expected unless parenthesis are explicitly used around every comparison operation, but there's no changing it now given it would break a huge amount of existing Python code.
