### ISSUE TITLE
Interpreter generator should emit code closer to pure C

### ISSUE THREAD

**Issue by markshannon** [python/cpython#102305]
Rather than emitting macros such as `DISPATCH`, `POKE`, `TARGET` etc, it would be useful if the code generator emitted something closer to plain C. Some macros will still be needed for portability.

Doing so would make the overhead in dispatch explicit and expose redundancies that can be eliminated.
For example, not all instructions need to save `frame->prev_instr`, but all do because the assignment is hidden in a macro.

### Linked PRs
* gh-102309

**Comment by gvanrossum** [comment]
(FWIW I don't see much of a benefit in the expansion of `DISPATCH()`, but for `TARGET()` I can see the point -- in the future the generator can omit `frame->prev_instr = next_instr++` if the instruction cannot produce an error. The `Py_STATS` code should probably be a single line calling a macro though, for flexibility.)

**Comment by gvanrossum** [comment]
If we're expanding `TARGET(op)` we should also expand `PREDICTED(op)`. But `PREDICT(op)` is too complex to bother (it's almost a full copy of `DISPATCH()` -- see also https://github.com/faster-cpython/ideas/issues/496).

**Comment by markshannon** [comment]
Regarding, `TARGET` and `BRANCH`, it is only the label and goto that aren't portable,
We already have `DISPATCH_GOTO()`, so keep that. Maybe reduce `TARGET(name)` to just the label:
```C
#if USE_COMPUTED_GOTO
        #define TARGET(op) TARGET_##op:
#else
        #define TARGET(op) case op:
#endif
```
or to avoid confusion, add a new macro `LABEL(op)`?

I'd leave `PREDICT()` for now, as we might be removing it.

**Comment by gvanrossum** [comment]
A thought: should we also expand some of these macros where they occur in user code? E.g. `JUMPBY(i)` is still used frequently. Or should we just expand these in bytecodes.c?
