### ISSUE TITLE
Implement __contains__ on slice

### ISSUE THREAD

**Issue by jonasrauber** [python/cpython#102361]
`slice` should support `x in slice(start, stop, step)`

Current behavior:
```
>>> 5 in slice(3, 10)
TypeError: argument of type 'slice' is not iterable
```

Desired behavior:
```
>>> 5 in slice(3, 10)
True
```

Basically, the behavior of `x in slice(start, stop, step)` should be identical to `x in range(start, stop, step)`. The difference is that slice supports `start = None` and `stop = None`.

This should also work (and is not directly possible with `range`):
```
>>> 5 in slice(3, None)
True
```

--

My current workaround is to create a range with sufficient size and then applying the slice to it:
```
>>> x = 5
>>> x in range(x + 1)[slice(3, None)]
True
```

**Comment by terryjreedy** [comment]
I am opposed.  `item in collection` tests whether the item is in the collection.  
https://docs.python.org/3/reference/expressions.html#membership-test-operations
As the message suggests, slices are not collections.  They are implementation gimmicks for extended slicing, which selects an arithmetic subsequence of a sequence.  They objectify at runtime the extended slice syntax construct, which is precisely why Nones are allowed.  They implement blanks in the syntax.

The addition is unnecessay.  Use range as you said.  Use 0 for start = None.  Use anything big enough, such as 10**50 for stop = None.  Or n >= start for stop = None and range = 1 or None.

**Comment by jonasrauber** [comment]
> item in collection tests whether the item is in the collection
That’s not what I read in the docs you linked. Instead, they talk about a general membership operator that can also be implemented by other classes.

Slices are a public type and not some implementation detail. They do carry semantics and a membership check makes sense and is useful.

**Comment by rhettinger** [comment]
Sorry, I concur with Terry that this is not a good idea and that you've misunderstood the nature of slices.  Also, there is no need for this because range objects already support slicing and membership testing:

```
>>> list(range(10)[2:5])
[2, 3, 4]
>>> 3 in range(3, 6)
True
```

Note that slices don't support `len()` or indexing.  You cannot know anything about the contents of a slice until it has been applied to a container:

```
>>> s = slice(10, 20, 2)
>>> list(range(100)[s])
[10, 12, 14, 16, 18]
>>> list(range(15)[s])
[10, 12, 14]
>>> list(range(5)[s])
[]

```

**Comment by jonasrauber** [comment]
I get your reasoning and I’d love to use range, but ranges don’t support being open-ended.
