### ISSUE TITLE
Alternative for variable length lookbehind

### ISSUE THREAD

**Issue by dsinghsf** [python/cpython#102317]
# Crash report

Hi Team

I have list of files, each file have this format:

```
<tag1 ip1>
  <tag2 *>
      sometext 
  </tag2>
  sometext with multiple lines goes here
</tag1>

<tag1 ip2>
  sometext with multiple lines goes here
  <tag2 *>
      sometext
  </tag2>
</tag1>

<tag1 ip3>
  sometext with multiple lines goes here
  <tag2 *>
      sometext
  </tag2>
</tag1>
```

What i am trying to achieve is to replace the text inside tag2 with specific ip of tag1.
Have tried lookbehind, but it is only able to cover the tag1 with ip:

```
(?<=(<tag1 ip1>)(.|\n)*)(<tag2 \*>)(.|\n)*.*</tag2>
```
but it is also matching the text inside tag1 with the tag2 and while replacment, it is removing those text. Since the text inside tag1 is of variable length so not able to use the lookbehind as it doesnt support variable length lookbehind.

python version: 3.9.6
Mac OS

Please suggest some alternative for this or if i am missing somthing. Thanks

**Comment by AlexWaygood** [comment]
Hi, welcome to CPython!

I'm afraid the GitHub issue tracker isn't the right place to go for general programming help. The GitHub issue tracker is for tracking bugs in CPython itself, not bugs in user code. It would be better to ask your question at https://discuss.python.org/c/users/7 or StackOverflow.

**Comment by dsinghsf** [comment]
okay thanks @AlexWaygood , have created a topic on same discuss python.
