### ISSUE TITLE
Malformatted raw email with core `smtplib` module

### ISSUE THREAD

**Issue by amustaque97** [python/cpython#102373]
# Bug report

I'm using the core python smtplib module and getting a malformatted email. I'm trying to reproduce the bug but am not able to do so because of the intermittent nature. Most of the time I get a properly formatted email and other times I get an email in the raw format.

I have observed whenever I get a malformatted email it has following content

```console
From: <[example@gmail.com](mailto:example@gmail.com)>
Date: Mon, Feb 27, 2023 at 5:35 AM
Subject:
To:


ehlo [x.x.x.x]
ehlo [x.x.x.x]
ehlo [x.x.x.x]
ehlo [x.x.x.x]
ehlo [x.x.x.x]
ehlo [x.x.x.x]
ehlo [x.x.x.x]
Content-Type: multipart/mixed; boundary="===============9202455659895712280=="
MIME-Version: 1.0
From: [example@gmail.com](mailto:example@gmail.com)
Subject: <email_subject>
Date: Mon, 27 Feb 2023 00:05:05 +0000
To: [example@yahoo.com](mailto:example@yahoo.com)

--===============9202455659895712280==
Content-Type: text/html; charset="us-ascii"
MIME-Version: 1.0
Content-Transfer-Encoding: 7bit

<!DOCTYPE html>
  <html>
    <head>
    </head>
   <body>
       // some content
   </body>
</html>
```

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on: 3.6.15
- Operating system and architecture: Linux and x86_64

Screenshot for reference

<img width="611" alt="Screenshot 2023-03-02 at 7 22 07 PM" src="https://user-images.githubusercontent.com/21127788/222449557-b5b968ba-05c0-462f-ae10-59bd8d851c04.png">

**Comment by amustaque97** [comment]
Sorry sharing the exact code would be really difficult since it's a private repo of my org. I will try to submit a similar codebase soon. 

Thank you for the reply!

**Comment by hugovk** [comment]
The key word is *minimal*. 

It's good to trim down as much as possible to remove irrelevant code, ideally leaving a few lines remaining.
