### ISSUE TITLE
`inspect._signature_strip_non_python_syntax` doesn't need to strip `/`

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#102378]
`inspect._signature_strip_non_python_syntax` removes `/`, this is probably a historical thing dating before Python 3.8 made this real Python syntax.

Removing this "feature" would simplify code in `inspect`.

### Linked PRs
* gh-102379

**Comment by terryjreedy** [comment]
Can you provide an example of the difference?

**Comment by skirpichev** [comment]
@terryjreedy, there are adapted tests in the PR.

**Comment by davidhewitt** [comment]
Yes, the PR hopefully is sufficient demonstration of what I mean by simplification 😊
