### ISSUE TITLE
Didn't display Raise Exception on python 3.9.5, but can display on python 3.8.10

### ISSUE THREAD

**Issue by cicicao** [python/cpython#102453]
# Bug report

test_notebook_run.py
```python
print('Start')
raise Exception ('Test exception')
print('End')
```

On Python 3.8.10
Azure Databricks: 10.4
```python 
import os
print("DATABASE_RUNTIME_VERSION:",os.environ.get('DATABRICKS_RUNTIME_VERSION',None))
%run /dbfs/FileStore/test_notebook_run.py

DATABASE_RUNTIME_VERSION: 10.4
Start
Exception: Test exception
```

On Python 3.9.5
Azure Databricks: 11.3 LTS
```
import os
print("DATABASE_RUNTIME_VERSION:",os.environ.get('DATABRICKS_RUNTIME_VERSION',None))
%run /dbfs/FileStore/test_notebook_run.py

DATABASE_RUNTIME_VERSION: 10.4
Start
```

**Comment by cicicao** [comment]
Exception: Test exception doesn't showup on Python 3.9.5 but can show on Python 3.8.10

**Comment by ericvsmith** [comment]
This appears to be a problem in whatever environment you're running python in (Databricks?).

This is what I see from the command line:

```sh
$ cat > test_notebook_run.py <<EOF
print('Start')
raise Exception ('Test exception')
print('End')
EOF
$ python test_notebook_run.py
Start
Traceback (most recent call last):
  File "<deleted-path>/test_notebook_run.py", line 2, in <module>
    raise Exception ('Test exception')
Exception: Test exception

```
Which is as expected. You might try running this test from the command line from both versions of python.

I think whatever environment you're using is hiding the exception from you. I suggest you ask this question in https://discuss.python.org/c/users/7

**Comment by cicicao** [comment]
@ericvsmith 
Thanks for your quick reply.

May I ask what's your python version?

**Comment by ericvsmith** [comment]
I tried it with 3.9.10 and 3.12.0a1+.

**Comment by cicicao** [comment]
Yes, I found exception can display on Python 2.7.17.
I guess it's Azure databricks problem . let me confirm with them

python test_notebook_run.py
Start
Traceback (most recent call last):
  File "test_notebook_run.py", line 2, in <module>
    raise Exception ('Test exception')
Exception: Test exception

**Comment by terryjreedy** [comment]
OP's 3.8 output is just `Exception: Test exception` without the `Traceback...` part.   Databricks is catching exceptions and printing its own custom output.
