### ISSUE TITLE
Open with Idle

### ISSUE THREAD

**Issue by tellts** [python/cpython#102411]
Microsoft Windows [Version 10.0.19044.2604]

C:\Users\admin>python
Python 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
The item (Open with Idle) is missing from the context menu.

**Comment by eryksun** [comment]
If Python is associated with ".py" files, there should be an "Edit with IDLE" submenu on the context menu. If not, make sure that Python is associated with ".py" files in settings -> apps -> default apps. If the py launcher is installed, the associated application should be a "Python" app that has a rocket on its icon.

**Comment by tellts** [comment]
https://imgbox.com/iQ6iKFjf

**Comment by eryksun** [comment]
The "open with" menu shows *applications* that can open a file. Since IDLE runs via "pythonw.exe -m idlelib", even if we created a progid for IDLE, the application would be "pythonw.exe". We'd have to include an "idle.exe" executable in the installation.

**Comment by tellts** [comment]
What can be done to solve this problem?

**Comment by terryjreedy** [comment]
Install 3.x with the py launcher and associate with python (.py) files, and IDLE 3.x with appear on the Edit with IDLE submenu.  One can then run or edit and run.

**Comment by tellts** [comment]
"Install 3.x": can you please tell me which version should I install? Could it be version 2022 or 2023 or should it be released much earlier?

**Comment by eryksun** [comment]
You already have Python 3 installed. Don't waste your time installing it again. I already gave you simple instructions on how to associate ".py" files with Python to get the "Edit with IDLE" menu.

**Comment by tellts** [comment]
My Python files open in Visual Studio Code by default.

**Comment by eryksun** [comment]
> My Python files open in Visual Studio Code by default.

If you mean that you prefer for ".py" files to open by default in Visual Studio Code, then the "Edit with IDLE" menu that's defined by the "Python.File" progid won't be available to you.

If you want the "Edit with IDLE" menu to always be available, you can define it in "HKCU\\Software\\Classes\\SystemFileAssociations\\.py". Here's the contents of a REG file that configures this for 64-bit Python 3.11, based on the default all-user location of the "pyw.exe" launcher.

```text
Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py]

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py\shell]

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py\shell\editwithidle]
"MUIVerb"="&Edit with IDLE"
"subcommands"=""

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py\shell\editwithidle\shell]

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py\shell\editwithidle\shell\edit311]
"MUIVerb"="Edit with IDLE 3.11 (64-bit)"

[HKEY_CURRENT_USER\Software\Classes\SystemFileAssociations\.py\shell\editwithidle\shell\edit311\command]
@="\"C:\\Windows\\pyw.exe\" -3.11 -m idlelib \"%1\" %*"
```

If the path of "pyw.exe" is different, or if you'd rather run "pythonw.exe" directly, then simply modify the path in the default value of the "command" key. You can use this as a template to add entries for other Python versions.
