### ISSUE TITLE
Pegen improperly memoizes loop rules

### ISSUE THREAD

**Issue by abel1502** [python/cpython#102416]
# Bug report

In the following part of pegen, the memoized result is only used if `self._should_memoize(node)` is true. Since loop rules are autogenerated, they are not marked with `(memo)`, so this is always false. Despite that, in the end the result is memoized based on the different condition `if node.name`. Because of that, in the generated parser loop rules' results are always stored in the cache, but never accessed later.

https://github.com/python/cpython/blob/8de59c1bb9fdcea69ff6e6357972ef1b75b71721/Tools/peg_generator/pegen/c_generator.py#L608-L647

# Your environment

Does not matter - discovered through manual code analysis

### Linked PRs
* gh-102467
* gh-102473
* gh-102474

**Comment by sobolevn** [comment]
cc @pablogsal

**Comment by pablogsal** [comment]
Thanks for the report @abel1502 and @sobolevn for the ping!

**Comment by pablogsal** [comment]
Opened https://github.com/python/cpython/pull/102467
