### ISSUE TITLE
`iter` with two arguments is not tested by `test_builtin.py` 

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102459]
Built-in function `iter` can be used with two arguments.
This case is not tested, so, i decided to write test for it.

### Linked PRs
* gh-102460

**Comment by erlend-aasland** [comment]
This case is tested several places in the test suite. PTAL.

**Comment by Eclips4** [comment]
Oh, yes, you're right. This tested by `test_iter.py` Sorry for a noise.
