### ISSUE TITLE
Expand structural pattern matching-like syntax to assignments

### ISSUE THREAD

**Issue by blhsing** [python/cpython#102458]
With the introduction of PEP-626, we have the elegant and succinct syntax of matching a value by an instance of a class while also assigning attribute values of the instance to variables, e.g.:

```python
class Point:
    x: int
    y: int

p = Point(0, 1)
match p:
    case Point(x=0, y=y):
        print(f"Y={y} and the point is on the y-axis.")
```

Would it not be nice if we can have such a match-capture-and-assign mechansim in regular assignments as well?

Instead of:
```python
assert isinstance(p, Point)
x = p.x
y = p.y
```
we can have:
```python
Point(x, y) = p
```
or by keyword:
```python
Point(x=x, y=y) = p
```

Instead of:
```python
assert isinstance(p, Point) and p.x == 0
y = p.y
```
we can have:
```python
Point(0, y) = p
```

Instead of:
```python
assert isinstance(p, Point)
y = p.y
```
we can have:
```python
Point(_, y) = p
```

Mapping patterns can be supported too, and like structural pattern matching, extra keys can be ignored.

Instead of:
```python
p = {'x': 0, 'y': 1, 'z': 0}
x = p['x']
y = p['y']
```
we can have:
```python
p = {'x': 0, 'y': 1, 'z': 0}
{'x': x, 'y': y} = p
```

Unlike a `match-case` construct, we always have only one matching pattern on the left in an assignment, so would it not be nice if we can also perform type conversions during a match?

Instead of:
```python
for name, x, y in csv.reader(['top,0,1', 'right,1,0', 'top-right,1,1']):
    x = float(x)
    y = float(y)
    print(f'distance to {name} is {(x * x + y * y) ** .5}')
```
we can have:
```python
for name, float(x), float(y) in csv.reader(['top,0,1', 'right,1,0', 'top-right,1,1']):
    print(f'distance to {name} is {(x * x + y * y) ** .5}')
```

Unlike structural pattern matching, an assignment with just classes or literals but no variables on the left should not be allowed:

```python
Point(0, 1) = p # error
{'x': 0, 'y': 1} = p # error 
```

**Comment by hugovk** [comment]
> With the introduction of [PEP-626](https://peps.python.org/626), we have the elegant and succinct syntax of matching a value... 

Do you mean PEP-635/PEP-636?

---

New features to Python should first be discussed elsewhere before creating issues on GitHub, for example in the "ideas" category (https://discuss.python.org/c/ideas/6) of discuss.python.org. 
 
Please could open a discussion over there first?

**Comment by JelleZijlstra** [comment]
Variants of this idea were discussed on the mailing lists when pattern matching was under consideration; I would suggest reading up on the archives to understand why this idea wasn't pursued at the time.

**Comment by hugovk** [comment]
For reference, the discussion is at https://discuss.python.org/t/expand-structural-pattern-matching-like-syntax-to-assignments-generalized-unpacking/24522
