### ISSUE TITLE
Logging's msecs doesn't handle "100ms" well.

### ISSUE THREAD

**Issue by dougthor42** [python/cpython#102402]
# Bug report

`LogRecord.msecs` returns an incorrect value when timestamp (`self.ct`) value has exactly 100ms.

One liner check:

```python
assert int((1677793338.100_000_0 - int(1677793338.100_000_0)) * 1000) + 0.0 == 100.0
```

The issue is binary representation of "0.1" / floating point error:

```python
>>> # Definition of LogRecord.msecs:
>>> # https://github.com/python/cpython/blob/12011dd8bafa6867f2b4a8a9e8e54cb0fbf006e4/Lib/logging/__init__.py#L343
>>> # int((ct - int(ct)) * 1000) + 0.0
>>> ct = 1677793338.100_000_0
>>> ct
1677793338.1
>>> ct - int(ct)
0.09999990463256836
>>> _ * 1000
99.99990463256836
>>> int(_)
99
>>> _ + 0.0
99.0
```

# Your environment

- CPython versions tested on:
  - 3.10.9
  - 3.11.2
- Operating system and architecture:
  - Custom company OS based on Debian Testing
  - 64-bit

# Discussion

I think switching to [`time.time_ns`](https://docs.python.org/3/library/time.html#time.time_ns) when [setting the creation time](https://github.com/python/cpython/blob/12011dd8bafa6867f2b4a8a9e8e54cb0fbf006e4/Lib/logging/__init__.py#L303) might be one solution.

### Linked PRs
* gh-102412
* gh-117985
* gh-118062

**Comment by vacosti** [comment]
I agree with @dougthor42 about the proposed solution, since [time library itself suggests](https://docs.python.org/3/library/time.html#time.time:~:text=Use%20time_ns()%20to%20avoid%20the%20precision%20loss%20caused%20by%20the%20float%20type.) to "use time_ns() to avoid the precision loss caused by the float type".

**Comment by dougthor42** [comment]
I hope to find some time this weekend to implement a fix.
