### ISSUE TITLE
Missing max heap version of heappush

### ISSUE THREAD

**Issue by yuting-liu** [python/cpython#102430]
# Feature or enhancement
The heap push is missing for max heap. The existing `heappush` will broken the sorting order in max_heap methods.
(A clear and concise description of your proposal.)

# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

# Previous discussion

### Linked PRs
* gh-102410

**Comment by rhettinger** [comment]
There is separate work in progress for this issue.  All the max heap functions are being made public and the missing ones will be added.
