### ISSUE TITLE
documentation error for multicore

### ISSUE THREAD

**Issue by irvinren** [python/cpython#102577]
in the library of multiprocessing, there are multiple places to state this module is for multiple processors. Nowadays, multicore processors are very common, why don't we include multicore in this documents. 

[multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) is a package that supports spawning processes using an API similar to the [threading](https://docs.python.org/3/library/threading.html#module-threading) module. The [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) package offers both local and remote concurrency, effectively side-stepping the [Global Interpreter Lock](https://docs.python.org/3/glossary.html#term-global-interpreter-lock) by using subprocesses instead of threads. Due to this, the [multiprocessing](https://docs.python.org/3/library/multiprocessing.html#module-multiprocessing) module allows the programmer to fully leverage **multiple processors** on a given machine. It runs on both Unix and Windows
https://docs.python.org/3/library/multiprocessing.html

**Comment by Lincoln-developer** [comment]
Hey @irvinren , I would love to work on this, thanks.

**Comment by AA-Turner** [comment]
I'm not sure there's anything to do here, "multiple processors" is fairly well understood. I don't think we should cover the minutiae of CPU & socket architectures here.

A
