### ISSUE TITLE
Add C implementation of os.path.splitroot()

### ISSUE THREAD

**Issue by barneygale** [python/cpython#102511]
# Feature or enhancement

Speed up `os.path.splitroot()` by implementing it in C.

# Pitch

[Per](https://github.com/python/cpython/pull/102454#discussion_r1128466021) @eryksun:

> I think `splitroot()` warrants a C implementation since it's a required step in our basic path handling on Windows -- `join()`, `split()`, `relpath()`, and `commonpath()`. Speeding it up gives a little boost across the board. Also, it would be less confusing if `nt._path_splitroot()` actually implemented `ntpath.splitroot()`.
> 
> If implemented, using `_Py_splitroot()` in `_Py_normpath()` would help to ensure consistency. Currently, for example, `ntpath.normpath('//?/UNC/server/share/../..')` is correct on POSIX but wrong on Windows because `_Py_normpath()` incorrectly handles "//?/UNC/" as the root instead of "//?/UNC/server/share/".

# Previous discussion

- https://discuss.python.org/t/add-os-path-splitroot/22243
- https://github.com/python/cpython/issues/101000
- https://github.com/python/cpython/pull/102454

### Linked PRs
* gh-118089
* gh-119394
* gh-119895
* gh-119980
* gh-124097
* gh-124919

**Comment by zooba** [comment]
I'd recommend making this a `skiproot` API rather than split, and just have it return the first index (or a pointer) after the root. This is very easy to convert into a split, but it also composes better with other APIs (e.g. `_Py_normpath` _needs_ the index and not the text).

**Comment by eryksun** [comment]
Sounds good. We can use `_Py_skiproot()` in `os__path_splitroot_impl()` in "Modules/posixmodule.c". 

Note that existing use of `nt._path_splitroot()` in `importlib` will have to be updated to handle the 3-way split `(drive, root, rest)` instead of `(anchor, rest)`.

**Comment by barneygale** [comment]
I'm going to attempt to implement this, though my C is rather basic so it will take me some time.

Rough plan:

1. Make `nt._path_splitroot()` work like `ntpath.splitroot()`, i.e. return a 3-tuple. Adjust `importlib`. Use it in `ntpath` where available.
2. Add `posix._path_splitroot()`. Use it in `posixpath` where available.
3. Add `_Py_skiproot()`. Call it from `_Py_normpath()` and `_path_splitroot()`

Let me know if that doesn't sound right!

**Comment by eryksun** [comment]
Here's an overview of what I did to experiment with this idea. I started by adding a new `_Py_skiproot()` internal API function in "Python/fileutils.c":

```c
PyAPI_FUNC(wchar_t *) _Py_skiproot(wchar_t *path, Py_ssize_t size,
                                   wchar_t **root);
```

I moved the existing root-skipping implementation from `_Py_normpath()` into `_Py_skiproot()` and modified it to implement returning `rest` and `root`. I also added support for extended "UNC" paths. I updated `_Py_normpath()` to use `_Py_skiproot()`. Once `test_ntpath` and `test_posixpath` were successful, I moved on to implement `os._path_splitroot_ex` in "Modules/posixmodule.c", which I used to implement `ntpath.splitroot()` and `posixpath.splitroot()`. I again verified that `test_ntpath` and `test_posixpath` were successful.

I retained the old `os._path_splitroot` implementation that's used by `importlib`. I plan to modify `importlib` to use the new implementation, but only if benchmarking demonstrates that this idea is worthwhile. If so, I'll remove the old implementation and rename the new one to `os._path_splitroot`.

My initial comparison shows that, when splitting "//server/share/spam/eggs", the new builtin `_path_splitroot_ex()` is about 4 times faster than the fallback implementation on Windows, and it's about 1.7 times faster than the fallback implementation on POSIX.

**Comment by barneygale** [comment]
My C isn't good enough for this, so someone else please feel free to take a stab at it!

**Comment by nineteendo** [comment]
How's the status here? Do you still have the code?

**Comment by nineteendo** [comment]
@eryksun, would I have to start from scratch?

**Comment by nineteendo** [comment]
I currently have this implementation:

```c
#ifdef MS_WINDOWS
void
_Py_skiproot(wchar_t *path, Py_ssize_t size, Py_ssize_t *drvsize, Py_ssize_t *rootsize)
{
    wchar_t *pEnd = size >= 0 ? &path[size] : NULL;
#define IS_END(x) (pEnd ? (x) == pEnd : !*(x))
#define IS_SEP(x) (*(x) == SEP || *(x) == ALTSEP)
    *drvsize = 0;
    *rootsize = 0;
    if (IS_SEP(&path[0])) {
        if (IS_SEP(&path[1])) {
            // Device drives, e.g. \\.\device or \\?\device
            // UNC drives, e.g. \\server\share or \\?\UNC\server\share
            Py_ssize_t idx;
            if (path[2] == L'?' && IS_SEP(&path[3]) && (path[4] == L'U' || path[4] == L'u') &&
                (path[5] == L'N' || path[5] == L'n') && (path[6] == L'C' || path[6] == L'c') &&
                IS_SEP(&path[7])) {
                idx = 8;
            }
            else {
                idx = 2;
            }
            while (!IS_END(&path[idx]) && !IS_SEP(&path[idx])) {
                idx++;
            }
            if (IS_END(&path[idx])) {
                *drvsize = idx;
            }
            else {
                idx++;
                while (!IS_END(&path[idx]) && !IS_SEP(&path[idx])) {
                    idx++;
                }
                *drvsize = idx;
                if (IS_SEP(&path[idx])) {
                    *rootsize = 1;
                }
            }
        }
        else {
            // Relative path with root, e.g. \Windows
            *rootsize = 1;
        }
    }
    else if (!IS_END(&path[0]) && path[1] == L':')
    {
        *drvsize = 2;
        if (IS_SEP(&path[2])) {
            // Absolute drive-letter path, e.g. X:\Windows
            *rootsize = 1;
        }
    }
#undef IS_SEP
#undef IS_END
}
#endif
```

```c
#ifdef MS_WINDOWS
/*[clinic input]
os._path_splitroot_ex

    path: unicode
    /

[clinic start generated code]*/

static PyObject *
os__path_splitroot_ex_impl(PyObject *module, PyObject *path)
/*[clinic end generated code: output=de97403d3dfebc40 input=bebce42edb41f967]*/
{
    Py_ssize_t len;
    wchar_t *buffer = PyUnicode_AsWideCharString(path, &len);
    Py_ssize_t drvsize;
    Py_ssize_t rootsize;
    _Py_skiproot(buffer, len, &drvsize, &rootsize);
    wchar_t *p = buffer;
    PyObject *drv = PyUnicode_FromWideChar(p, drvsize);
    p += drvsize;
    PyObject *root = PyUnicode_FromWideChar(p, rootsize);
    p += rootsize;
    PyObject *tail = PyUnicode_FromWideChar(p, len - drvsize - rootsize);
    PyMem_Free(buffer);
    return Py_BuildValue("(OOO)", drv, root, tail);
}
#endif
```

```python
def splitroot(p):
    """Split a pathname into drive, root and tail. The drive is defined
    exactly as in splitdrive(). On Windows, the root may be a single path
    separator or an empty string. The tail contains anything after the root.
    For example:

        splitroot('//server/share/') == ('//server/share', '/', '')
        splitroot('C:/Users/Barney') == ('C:', '/', 'Users/Barney')
        splitroot('C:///spam///ham') == ('C:', '/', '//spam///ham')
        splitroot('Windows/notepad') == ('', '', 'Windows/notepad')
    """
    p = os.fspath(p)
    if isinstance(p, bytes):
        drive, root, tail = _path_splitroot_ex(os.fsdecode(p))
        return os.fsencode(drive), os.fsencode(root), os.fsencode(tail)
    return _path_splitroot_ex(p)
```

**Comment by nineteendo** [comment]
Benchmark:

```none
PS C:\Users\wanne\cpython> python -m timeit -s "import os" "os.path.splitroot('//server/share/spam/eggs')"; PCbuild\amd64\python.exe -m timeit -s "import os" "os.path.splitroot('//server/share/spam/eggs')"
500000 loops, best of 5: 940 nsec per loop # before
1000000 loops, best of 5: 346 nsec per loop # after
# -> 2.72x faster
```

**Comment by zooba** [comment]
Reopening and assigning to myself because I'm holding up the backport until we have confidence in the change. My note from the PR:

I want to hold this for a bit until we're confident in the change in later versions. Virtually every time we touch this kind of code, we introduce new failures or vulnerabilities, so let's keep it restricted to prerelease versions for now.

I'd say after 3.13.0b3 is released we'll reconsider, but that's because I'm hopeful we'll get a decent amount of people trying out those betas. If it seems like nobody is using them, we'll push this further.

**Comment by pradyunsg** [comment]
FWIW, we're seeing this affect pip's test suite starting 3.13.0b2 -- based on the changelog, https://github.com/python/cpython/issues/118263 was the thing that switched stuff over to using the C implementation, but I'm making a comment here since it seems relevant to the C implementation being adopted in general.

The specific behaviour change we're seeing is that UNC paths are normalised differently.

```
def path_to_url(path: str) -> str:
    """
    Convert a path to a file: URL.  The path will be made absolute and have
    quoted path parts.
    """
    path = os.path.normpath(os.path.abspath(path))
    url = urllib.parse.urljoin("file:", urllib.request.pathname2url(path))
    return url
```

On Windows with 3.13.0b2, we're seeing failures like the following in CI:

```
 >       assert path_to_url(r"\\unc\as\path") == "file://unc/as/path"
E       AssertionError: assert 'file:////unc/as/path' == 'file://unc/as/path'
E         
E         - file://unc/as/path
E         + file:////unc/as/path
E         ?      ++
```

This passes on 3.13.0b1, at least based on the last run yesterday (I don't have a windows dev machine handy).

**Comment by nineteendo** [comment]
This pull request wasn't back ported to 3.12, but the bug also occurs there:

```python
Python 3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from os.path import abspath, normpath
>>> from urllib.parse import urljoin
>>> from urllib.request import pathname2url
>>> path_to_url = lambda path: urljoin("file:", pathname2url(normpath(abspath(path))))
>>> path_to_url(r"\\unc\as\path")
'file:////unc/as/path'
```

**Comment by nineteendo** [comment]
@pradyunsg, it's caused by #113563:

```python
import urllib.parse
from urllib.parse import _coerce_args, urljoin, uses_netloc

def urlunsplit(components):
    scheme, netloc, url, query, fragment, _coerce_result = (_coerce_args(*components))
    if netloc or (scheme and scheme in uses_netloc and url[:2] != '//'):
        if url and url[:1] != '/': url = '/' + url
        url = '//' + (netloc or '') + url
    if scheme:
        url = scheme + ':' + url
    if query:
        url = url + '?' + query
    if fragment:
        url = url + '#' + fragment
    return _coerce_result(url)

print(urljoin("file:", "////unc/as/path")) # file:////unc/as/path
urllib.parse.urlunsplit = urlunsplit
print(urljoin("file:", "////unc/as/path")) # file://unc/as/path
```

**Comment by eryksun** [comment]
Yes, in #113563, `urllib.parse` was switched from using 2-slash UNC paths to 4-slash UNC paths. Both forms are valid. The implementation now supports a roundtrip split/unsplit correctly for both forms. For example:

```pycon
>>> r = urllib.parse.urlsplit('file:////unc/as/path')
>>> urllib.parse.urlunsplit(r)
'file:////unc/as/path'
>>> r = urllib.parse.urlsplit('file://unc/as/path')
>>> urllib.parse.urlunsplit(r)
'file://unc/as/path'
```

Previously, this didn't work correctly for 4-slash paths:

```pycon
>>> r = urllib.parse.urlsplit('file:////unc/as/path')
>>> urllib.parse.urlunsplit(r)
'file://unc/as/path'
>>> r = urllib.parse.urlsplit('file://unc/as/path')
>>> urllib.parse.urlunsplit(r)
'file://unc/as/path'
```

**Comment by nineteendo** [comment]
Eryk, is `nturl2path.pathname2url()` supposed to handle forward slashes?

```python
>>> from nturl2path import pathname2url
>>> pathname2url('//unc/as/path')
'//unc/as/path'
>>> pathname2url(r'\\unc\as\path')
'////unc/as/path'
```

**Comment by erlend-aasland** [comment]
Closing the issue as completed, as the OP feature request seems to have been implemented.

**Comment by nineteendo** [comment]
Technically there's still #119394.
