### ISSUE TITLE
`help` CLI shows a traceback when import failed

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102541]
Currently, `help` will show a traceback when we type name of something which doesn't exist:

```python
help> 123
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen _sitebuiltins>", line 103, in __call__
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 2004, in __call__
    self.interact()
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 2031, in interact
    self.help(request)
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 2057, in help
    elif request: doc(request, 'Help on %s:', output=self._output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 1781, in doc
    pager(render_doc(thing, title, forceload))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 1755, in render_doc
    object, name = resolve(thing, forceload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\pydoc.py", line 1741, in resolve
    raise ImportError('''\
ImportError: No Python documentation found for '123'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.
>>>
```
I think, this shouldn't be shown.
Is there any reason for this?
Can we show something like
`No python documentation found for '123'.`?

Reproducible on current main.

### Linked PRs
* gh-102614
* gh-105778
* gh-105830
* gh-105934
* gh-106322
* gh-106323
* gh-106340
* gh-106639
* gh-106640

**Comment by terryjreedy** [comment]
I verified above in 3.11.2 and 3.12.0a6.  3.10.10 is better -- Gives import error message without traceback.  But even better would be to give error message without `ImportError` and return to `help>` prompt.  This should possibly  be a separate PR.

**Comment by Eclips4** [comment]
How I understand, it's introduced in #89130.

**Comment by terryjreedy** [comment]
In closed duplicate #105702, I noted that there was no bug in latest release of  3.8, 3.9, or 3.10.  Patch should restore previous behavior, shown on that issue.  I just installed 32-bit 3.11.0 and it does have the bug.  Will look at PR.

**Comment by corona10** [comment]
>  CI passed because help() interaction is not adequately tested. 

Yeah, we have to add the test for interaction.

**Comment by Yhg1s** [comment]
Is the only thing left to do here improving test coverage?

**Comment by Eclips4** [comment]
> Is the only thing left to do here improving test coverage?

Sadly, but no. When I tried to write a test for this case, I founded another bug. I have already sent PR to fix.

**Comment by terryjreedy** [comment]
This issue is at least a near duplicate of issue #98374 and PR #98450, about `help('invalid')`, closed and merged. 

@Eclips4 The 2nd fix is now merged and backported.  Can you now write a test for the first one?

**Comment by Yhg1s** [comment]
Okay, so _now_ it's just about adding the last test case, right? 😅

**Comment by Eclips4** [comment]
> Okay, so _now_ it's just about adding the last test case, right? 😅

Yeah, you're right.

**Comment by terryjreedy** [comment]
I reviewed and edited and intend to merge and close this after CI passes.

**Comment by Eclips4** [comment]
Thank you very much @terryjreedy for your help!

**Comment by Eclips4** [comment]
Now, all PR's merged and backported. 
Everything that needed to be done was done.
Again, thanks Terry for his thorough help.
