### ISSUE TITLE
Possible incorrect detail in output of urlparse

### ISSUE THREAD

**Issue by jaypittman** [python/cpython#102504]
In this page: https://docs.python.org/3/library/urllib.parse.html#module-urllib.parse

In the code snippet under urllib.parse.urlparse:
urlparse("scheme://netloc/path;parameters?query#fragment")
ParseResult(scheme='scheme', netloc='netloc', path='/path;parameters', params='',
            query='query', fragment='fragment')

This shows the parameters component of the URL being placed (in the output named tuple) onto the end of .path, not into .params. Seems likely that this is an oversight. But I don't have enough experience with the code to know for sure.

**Comment by sobolevn** [comment]
Looks like the implementation is quite clear about `params` parsing. It only happens when `scheme` is in 

```python
['', 'ftp', 'hdl', 'prospero', 'http', 'imap',
 'https', 'shttp', 'rtsp', 'rtspu', 'sip', 'sips',
 'mms', 'sftp', 'tel']
```

So, this works:

```python
>>> urlparse("http://netloc/path;p?query#fragment")
ParseResult(scheme='http', netloc='netloc', path='/path', params='p', query='query', fragment='fragment')
```

But, on the other hand it was never documented.

Does it make sence to you?
