### ISSUE TITLE
tkinter.Spinbox seems to not work when 'value' parameter is set.

### ISSUE THREAD

**Issue by ThePython10110** [python/cpython#102588]
# Bug report

If the `value` parameter of a Spinbox is set, even to an `int`, the increment/decrement buttons do nothing. If this isn't the right place for this bug, sorry.
```py
from tkinter import *
root = Tk()
intvar = IntVar(root)
spinbox_with_value = Spinbox(root, from_ = 1, to = 12, value = 12, textvariable = intvar)
spinbox_with_value.pack()
# The text box is still editable, but the buttons do nothing.
```
Without the `value` parameter set, the buttons work.
```py
from tkinter import *
root = Tk()
intvar = IntVar(root)
intvar.set(12) # Workaround, since the value parameter doesn't work
spinbox_without_value = Spinbox(root, from_ = 1, to = 12, textvariable = intvar)
spinbox_without_value.pack()
# This works as intended.
```

# Your environment

- CPython versions tested on: 3.11.1, 3.9.8, 3.6.2
- Operating system and architecture: Windows 10 22H2

**Comment by terryjreedy** [comment]
You have been tripped up by tcl's 'feature' of being very forgiving on input in accepting any unambiguous prefix of an option name.  `valu` and `value` are valid abbreviations of `values`.   'values', a tuple (or list) of strings (or ints) of allowed values, or a single value that gets converted to a tuple.  So `12` is interpreted as `('12',)`.  `values` overrides `from_` and `to`.  See
https://tkdocs.com/shipman/spinbox.html
https://www.tcl.tk/man/tcl8.6/TkCmd/spinbox.html
