### ISSUE TITLE
boolif - A built-in conditional if statement, that requires the boolean type

### ISSUE THREAD

**Issue by mark-todd** [python/cpython#102557]
# Feature or enhancement

An alternative built-in keyword to `if`: `boolif`, that must act on a `bool` type or else fail. All "truthy" options such as `[]`, `None`, `0`, `1` would fail with this variant.

# Pitch

Frequently there have been bugs in code I have used and created, where a conditional statement is expected to receive a boolean, but due to mistake, it does not. A simple case I encountered earlier with Path:

```py
from pathlib import Path
path = Path('test')
if path.exists:
   print('true')
```

The mistake here is that exists is a function that should be called like so:

```py
from pathlib import Path
path = Path('test')
if path.exists():
   print('true')
```

Because if accepts truthy args, the first version does not raise an error, and the bug is not detected. You could of course add an assertion that resolves this as below:

```py
from pathlib import Path
path = Path('test')
path_does_exist = path.exists()
assert isinstance(path_does_exist, bool)
if path_does_exist:
   print('true')
```

But this is quite long, and depending on the scenario may have a runtime cost. The syntax I propose is as follows:

```py
from pathlib import Path
path = Path('test')
boolif path.exists():
   print('true')
```
This is now brief, and by making it a built-in feature, I believe there could be way for there to be no speed loss from it. This would not replace if, and simply be an additional option for those that require it.

**Comment by AlexWaygood** [comment]
Ideas for new builtin functions or new syntax should be discussed at https://discuss.python.org/c/ideas/6 before opening an issue here, as stated on the GitHub issue template.  They require a lot of buy-in from the wider community, and probably can't be implemented without a PEP being written and accepted. This hasn't been done in this instance, so I'm closing this for now.

By the way: while this is a common source of bugs, it's also one that can be easily caught early by several of Python's type checkers and linters. Running the latest version of mypy on your snippet of code, with mypy's default configuration, flags the bug (with an error message that is easy to understand): https://mypy-play.net/?mypy=latest&python=3.11&gist=9eb36ff2bb5d3609ed74ae175f2a921f

**Comment by mark-todd** [comment]
Ah apologies - I missed this on the template, I'll raise it in the discussion forum. I've used pyright/strict typing to check code with this sort of bug before and it didn't detect it, as since the value has a truthy interpretation it presumes it's valid. Perhaps mypy has a more advanced checking system for this.

**Comment by AlexWaygood** [comment]
To be fair, the `truthy-function` error code is a relatively new feature of mypy.

(It used to be part of a broader `truthy-bool` error code that was disabled by default, but the `truthy-bool` error code had too many false positives, so the `truthy-function` error code was split off from it and was enabled by default.)

If pyright doesn't have an equivalent feature, you could consider filing a feature request with pyright. They may be open to it.
