### ISSUE TITLE
Built-in `round` misbehaviour

### ISSUE THREAD

**Issue by eliegoudout** [python/cpython#102552]
Hello,

It seems like the built-in `round`function doesn't behave as expected:
```
>>> round(0.95, 1)
0.9  # Unexpected
>>> round(0.095, 2)
0.1  # Expected
>>> round(0.0095, 3)
0.009  # Unexpected
>>> round(0.00095, 4)
0.0009  # Unexpected
>>> round(0.000095, 5)
0.0001  # Expected
>>> round(0.0000095, 6)
1e-05  # Expected
>>> round(0.00000095, 7)
1e-06  # Expected
>>> round(0.000000095, 8)
1e-07  # Expected
>>> round(0.0000000095, 9)
1e-08  # Expected
>>> round(0.00000000095, 10)
1e-09  # Expected
>>> round(0.000000000095, 11)
9e-11  # Unexpected
```

[Doc](https://docs.python.org/3/library/functions.html#round) states

> `round(number, ndigits=None)`
> [...] values are rounded to the closest multiple of 10 to the power minus ndigits; if two multiples are equally close, rounding is done toward the even choice

which isn't the case here.

Is this only a problem of float encoding leading to imprecisions? I checked and [unit tests](https://github.com/python/cpython/blob/66aa78cbe604a7c5731f074b869f92174a8e3b64/Lib/test/test_builtin.py#L1503) don't cover those cases.

Cheers!

**Comment by ericvsmith** [comment]
Yes, this is a function of how floating point works. See https://docs.python.org/3/tutorial/floatingpoint.html

This might help. 0.0095's floating point value is slightly less than 0.0095:
```pycon
>>> from decimal import Decimal
>>> Decimal(0.0095)
Decimal('0.00949999999999999976407760726715423515997827053070068359375')
```
