### ISSUE TITLE
Using max() on list of numeric and non-numeric strings returns unexpected results

### ISSUE THREAD

**Issue by CalJaDav** [python/cpython#102568]
# Description
Using python 3.9.7:

Calling max on a list of stings is supposed to return the longest string. e.g.
`max(['hello', 'world!',])`
returns: `'world!'`

However when applied to a list of numeric strings it instead returns the largest number: e.g.
`max(['1.05', '2', '3'])`
returns: `'3'`

This on its own is slightly strange behavior, and a little annoying - I've gone to the effort of converting the numerics into strings, max() ought to evaluate them as strings, however it gets stranger still. Passing a list of numeric strings will always return the largest numeric value that starts with a 9. e.g.
`max(['99', '1.00324', '100','999', '9.990', '88888888'])`
returns `'999'`

This is super annoying, but it gets worse. Passing a list of numeric and non-numeric strings will always return the largest non-numeric string, even when a longer numeric string is in the list! e.g.
`max(['99', '1.00324', '100','999', '9.9990', '88888888', 'hello', 'world!'])`
returns: `'world!'`

**Comment by chgnrdv** [comment]
The results seem expected to me, since `max()` applied to a list of strings compares them lexicographically but not by their length or numerical value. This link can be useful:
https://stackoverflow.com/questions/45950646/what-is-lexicographical-order
If you want to compare strings in list by a specific attribute, you can use a `key` keyword to provide a function/constructor that will be called on each item in list, and its return value will be used for comparison:
```python
>>> max('hello', 'world!', key=len)
'world!'
>>> max(['99', '1.00324', '100','999', '9.990', '88888888'], key=float)
'88888888'
```

**Comment by sobolevn** [comment]
Yes, this works as expected. I agree with @chgnrdv 

```python
>>> max(['aa', 'b'])
'b'
>>> 'aa' > 'b'
False
>>> 'aa' < 'b'
True
>>> 'a' > 'b'
False
>>> 'a' < 'b'
True
```

**Comment by ericvsmith** [comment]
> Calling max on a list of stings is supposed to return the longest string. e.g.

Can you tell us where you saw this? I'm hoping it's not in our documentation.

**Comment by CalJaDav** [comment]
> > Calling max on a list of stings is supposed to return the longest string. e.g.
> 
> Can you tell us where you saw this? I'm hoping it's not in our documentation.

Bad info from a google search... should have just read the docs
