### ISSUE TITLE
Remove special-casing from `FORMAT_VALUE` opcode

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#102598]
Right now there's a special case in handling this opcode:

https://github.com/python/cpython/blob/5ffdaf748d98da6065158534720f1996a45a0072/Python/bytecodes.c#L3060-L3073

It comes from older version of `ceval.c`:

https://github.com/python/cpython/blob/281078794f10a42d0aa99d660e25a434fde96ec4/Python/ceval.c#L4379-L4395

But, I think that the needed optimizaion is there: https://github.com/python/cpython/blob/5ffdaf748d98da6065158534720f1996a45a0072/Objects/abstract.c#L774-L777

So, I think this can be safely removed.
I will send a PR.

### Linked PRs
* gh-102599

**Comment by hauntsaninja** [comment]
Thank you!
