### ISSUE TITLE
Multicast socket send failing on windows for loopbak adapter

### ISSUE THREAD

**Issue by teeks99** [python/cpython#102590]
# Bug report

When attempting to send multicast udp packets, most examples I could find [1](https://pymotw.com/2/socket/multicast.html), [2](https://stackoverflow.com/a/1794373/17949), indicate that you can simply call the socket's `sendto()` method with the appropriate tuple with the multicast group and port, e.g. `("224.1.1.1", 12345)`. In most cases, this works well for me on both linux and windows.

However, on windows, in the specific case where I want to send from the localhost address (`127.0.0.1`), this will cause an `OSError` exception with `[WinError 10051] A socket operation was attempted to an unreachable network`. 

For example this:
```python
import socket

MCAST_GRP = '224.1.1.6'
MCAST_PORT = 15007

LOCAL_IF = '127.0.0.1'
#LOCAL_IF = '192.168.42.42'

data = b"Multicast Data"

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)
# Not sure if this does anything
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_LOOP, 1)
# Use for sending out
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(LOCAL_IF))


sock.sendto(data, (MCAST_GRP, MCAST_PORT))
```

Causes the output:
```
>python multicast_sender_bound.py
Traceback (most recent call last):
  File "D:\code\tmp\python_multicast\multicast_sender_bound.py", line 19, in <module>
    sock.sendto(data, (MCAST_GRP, MCAST_PORT))
OSError: [WinError 10051] A socket operation was attempted to an unreachable network
```

On linux (Ubuntu 22.04) this works flawlessly, there is no error output and the data is sent as expected.

If I change the `LOCAL_IF` variable to a **non-localhost** interface on my computer, **this works correctly** and sends the example data. So this is somehow linked to the localhost address being used to send.

## Workaround 1

There is a workaround, which is to set the socket option `IP_ADD_MEMBERSHIP`. It is commonly documented that this is needed for any multicast receive socket, but I have not seen any cases of its use/necessity for sending, indeed it wasn't needed above for sending on a non-localhost interface.

With this change, everything works as expected:

```python
import socket
import struct

MCAST_GRP = '224.1.1.6'
MCAST_PORT = 15007

LOCAL_IF = '127.0.0.1'
#LOCAL_IF = '192.168.42.42'

data = b"Multicast Data"

sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, socket.IPPROTO_UDP)
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_TTL, 2)
# Not sure if this does anything
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_LOOP, 1)
# Use for sending out
sock.setsockopt(socket.IPPROTO_IP, socket.IP_MULTICAST_IF, socket.inet_aton(LOCAL_IF))

mreq = struct.pack(
    "4s4s", socket.inet_aton(MCAST_GRP),
    socket.inet_aton(LOCAL_IF))
sock.setsockopt(socket.IPPROTO_IP, socket.IP_ADD_MEMBERSHIP, mreq)

sock.sendto(data, (MCAST_GRP, MCAST_PORT))
```

An example that shows all four combinations can be found [here](https://gist.github.com/teeks99/e82b4997e3e05c569eadb2df936c1026#file-loopback_test-py).

## Workaround 2

In trying to reproduce this, I wrote [a script](https://gist.github.com/teeks99/9213d80fa61532f1d30ee6a397cd5f0a#file-combined_test-py) that included a receiver in the same process, so that I could easily see which packets were received. However, this caused the problem to go away. It seems that applying the `IP_ADD_MEMBERSHIP` option to the *receive* socket caused the problem with the send socket to go away....a somewhat concerning case of global scope? 

# Your environment

Tested with CPython 3.11.2 on Windows 10 Enterprise 21H2.

**Comment by arhadthedev** [comment]
@giampaolo, @gpshead (as networking [experts](https://devguide.python.org/core-developers/experts/))

**Comment by gpshead** [comment]
I see no Python bug here.  This sounds like something you should post on a network programming forum.
