### ISSUE TITLE
zipfile.extractall security warning in the docs, can it be removed yet?

### ISSUE THREAD

**Issue by esharf** [python/cpython#102686]
# Documentation

In the zipfile docs in the [ZipFile.extractall](https://github.com/python/cpython/blob/main/Doc/library/zipfile.rst?plain=1#L359) there is a warning.

the story of this warning is that https://github.com/python/cpython/issues/51221 was represented and fixed.
but in [this](https://github.com/python/cpython/issues/51221#issuecomment-1093481075) comment the decision was to leave this warning for people checking the latest docs even if the python version that they are using is not the latest.

but since this is already fixed on 2013 I think it's time to remove it.

**Comment by hugovk** [comment]
@gpshead @serhiy-storchaka: shall we remove this warning?

![image](https://user-images.githubusercontent.com/1324225/224956943-e4bae7ff-5ec6-455f-9423-f274a6645a37.png)

https://docs.python.org/3/library/zipfile.html#zipfile.ZipFile.extractall

**Comment by gpshead** [comment]
Lets leave it for a little while longer, I want to see an API similar to the `tarfile.extractall` https://peps.python.org/pep-0706/ security work land in zipfile and the requisite more in depth look and re-review of our implementation before we stop cautioning our users.  For consistency and just to be on the safe side.

**Comment by gpshead** [comment]
I'm going to close this issue as the docs should be updated to remove warnings when implementing mitigation style features.  There are also other semi-related reasons for warnings in the zipfile docs such as zip bombs (https://github.com/python/cpython/issues/109858) that still exist.
