### ISSUE TITLE
ipaddress.IPv6Address does not fall on invalid ipv6 string which contains "%"

### ISSUE THREAD

**Issue by Archirk** [python/cpython#102693]
# Bug report
ipaddress module validates incorrect ipv6 address string with percent "%" character
```python
import ipaddress

invalid_ipv6 = "AAAA::BBBB:CCCC:DDDD:EEE%1"

ipv6 = ipaddress.IPv6Address(invalid_ipv6) # does not rise an error
ipv6 = ipaddress.ip_address(invalid_ipv6) # does not rise an error
```

# Your environment
- CPython versions tested on: Python 3.9.13
- Operating system and architecture: Ubuntu 20.04.4 LTS x86-64

**Comment by stevendaprano** [comment]
Everything following the percent sign is a zone index.

https://superuser.com/questions/99746/why-is-there-a-percent-sign-in-the-ipv6-address

https://en.wikipedia.org/wiki/IPv6_address#Scoped_literal_IPv6_addresses_(with_zone_index)
