### ISSUE TITLE
Docs: Description of LOAD_CLOSURE in dis module should be updated

### ISSUE THREAD

**Issue by c2170** [python/cpython#102636]
# Documentation

In the description of **LOAD_CLOSURE**, I think there is no longer exists `co_fastlocalnames` attribute. It may need to be updated.

https://docs.python.org/3/library/dis.html

**Comment by hugovk** [comment]
Looks like this was added in PR https://github.com/python/cpython/pull/26388, but I also see a revert and unrevert in its issue, https://github.com/python/cpython/issues/87859...

Let's ask @ericsnowcurrently: should this reference to `co_fastlocalnames` be removed from the docs?
