### ISSUE TITLE
Function arguments error

### ISSUE THREAD

**Issue by ghost** [python/cpython#102604]
**Function arguments error**

[Crypt.txt](https://github.com/python/cpython/files/10948770/Crypt.txt)
[Terminal saved output.txt](https://github.com/python/cpython/files/10948775/Terminal.saved.output.txt)

**Comment by terryjreedy** [comment]
Please put minimal repreducible code showing problem in your message between triple backticks.
~~~
```
<code>
```
~~~
Do same for output.  Both should only be a few lines.

**Comment by stevendaprano** [comment]
You forgot to include the `self` parameters to your methods.

```
class crypt:
    def encrypt(dir, new_key_id):
    # needs to be def encrypt(self, dir, new_key_id)
```

This is for reporting bugs in the Python interpreter and standard library, not for asking for help to solve bugs in your own code. In the future, when you need help fixing your code, you can ask for help at [the Python Discuss](https://discuss.python.org/t/python-discourse-quick-start/116).

**Comment by chgnrdv** [comment]
@Elyggg, I don't see any bug here. `encrypt` is defined as method of `crypt` object, so its first argument `dir` is expected to be a `crypt` instance. But if you are calling `encrypt` method on `crypt` object with a `dir` keyword argument, it shadows positional `dir` argument already presented in method signature, so Python raises exception. Consider the following example:
```
class Foo:
    def bar(x):
         print(x)

>>> Foo().bar(x=3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Foo.bar() got multiple values for argument 'x'
>>> Foo.bar(x=3)
3
```

**Comment by Elyggg** [comment]
Thank you!
