### ISSUE TITLE
option to strip multiline strings from indentation in beginning of line

### ISSUE THREAD

**Issue by hananbeer** [python/cpython#102683]
# Feature or enhancement

when using multiline strings, you have two inconvenient options.
- indentation equal to the block depth:
```python
def foo():
    print("""this
    is
    annoying
    """)
```
which prints the first line without indentation and the rest with indentation.

- breaking the format in a horrendous way:
```python
def foo():
    print("""
this
is
ugly""")
```
which prints a newline in the beginning and also breaks the pythonic formatting.

# Proposal

introduce a new syntax:

```python
def foo():
    print(t"""
        this
        looks
        much
        better
    """)
```
(notice the `t` prefix)

which would be shorthand of:
```python
re.sub('^[\t ]*', '', string.strip(), flags=re.MULTILINE)
```

it is possibly a good idea not to remove '\r\n' that was specified explicitly at the end of the multiline string.

(I know there are modules for this, but again - very annoying)

**Comment by stevendaprano** [comment]
Quoting the new issue template: "New features to Python should first be discussed elsewhere before creating issues on GitHub". Please link to the discussion if you have done so.

Also see:

* https://github.com/python/cpython/issues/42186
* https://github.com/python/cpython/issues/62535
* https://github.com/python/cpython/issues/81087

This has been discussed many times before, so you should find it easy to find previous discussions such as these:

* https://mail.python.org/pipermail/python-ideas/2018-March/049578.html
* https://mail.python.org/pipermail/python-ideas/2019-March/056126.html

There are probably others.

**Comment by hananbeer** [comment]
great. apologies for not knowing otherwise 😅
