### ISSUE TITLE
Exception hierarchy documentation

### ISSUE THREAD

**Issue by decaz** [python/cpython#102641]
I guess `asyncio.CancelledError` should be within https://github.com/python/cpython/blob/main/Lib/test/exception_hierarchy.txt as it's the subclass of `BaseException` now according to this: https://github.com/python/cpython/blob/233e32f93614255bf5fc7c93cd98af453e58cc98/Doc/library/asyncio-exceptions.rst?plain=1#L32-L34

**Comment by Eclips4** [comment]
This file is intended to visualise only built-in exceptions, `asyncio.CancelledEror` is not one.
Please, take a look: https://github.com/python/cpython/blob/main/Doc/library/exceptions.rst#exception-hierarchy

By other hand, you can suggest add `CancelledError` to built-in exceptions (IMHO, that's not good idea).

**Comment by terryjreedy** [comment]
Built-in objects are objects defined in
```
>>> __builtins__
<module 'builtins' (built-in)>
```
which is automatically 'imported' on startup, so that it contents can be directly accessed.
```
>>> NameError
<class 'NameError'>
```
Objects defined in other modules, like asyncio, are not builtins.  Multiple models define module-specific exceptions.
