### ISSUE TITLE
Update webbrowser to use Edge as fallback instead of IE

### ISSUE THREAD

**Issue by DBJim** [python/cpython#102690]
# Feature or enhancement

[webbrowser.py](https://github.com/python/cpython/blob/54060ae91da2df44b3f6e6c698694d40284687e9/Lib/webbrowser.py#L546)  currently uses Internet Explorer as the fallback browser on Windows, if the user has no default browser, and no user-installed browsers are detected. I propose to update this code to use Microsoft Edge as the fallback instead.

# Pitch

-IE is deprecated and no longer functional on most Windows installations today.
-Any Windows installation with current Python has had Microsoft Edge installed since release.
-It seems that certain enterprise policies will block the user from directly invoking IE ([See this Github issue](https://github.com/python/cpython/issues/102520)).
-While iexplore.exe currently redirects to Edge when executed, this PR makes the fallback behavior transparent.

# Previous discussion

https://discuss.python.org/t/update-webbrowser-py-to-use-microsoft-edge-as-fallback-instead-of-ie/24791

### Linked PRs
* gh-102691

**Comment by merwok** [comment]
Thanks!
