### ISSUE TITLE
PEP3101 format string precision with type 'g' does not behave as documented

### ISSUE THREAD

**Issue by bhaible** [python/cpython#102620]
# Bug report

According to the documentation https://docs.python.org/3/library/string.html#formatstrings :
"The precision is a decimal integer indicating how many digits should be displayed after the decimal point for presentation types 'f' and 'F', or before and after the decimal point for presentation types 'g' or 'G'."

```
"The value is {0:8.5g}".format(-3.25)
```
should therefore evaluate to `'The value is  -3.2500'`. But it produces `'The value is    -3.25'`

Note that for the type 'f', it behaves as documented:
```
"The value is {0:8.5f}".format(-3.25)
```
evaluates to `'The value is -3.25000'`.

# Your environment

Python version: Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux (Ubuntu 22.04, x86_64)

**Comment by mdickinson** [comment]
This is by design: the `g` format strips trailing zeros by default. If that's not what you want, you can use the alternate form:

```python
>>> format(-3.25, '.5g')
'-3.25'
>>> format(-3.25, '#.5g')
'-3.2500'
```

**Comment by ericvsmith** [comment]
I agree with @mdickinson. The documentation also says “In both cases insignificant trailing zeros are removed from the significand, and the decimal point is also removed if there are no remaining digits following it, unless the '#' option is used.”

**Comment by bhaible** [comment]
I see. But the cited sentence looked like it is the complete documentation of the precision. How about clarifying the documentation?

"The precision is a decimal integer indicating how many digits should be displayed after the decimal point for presentation types 'f' and 'F', or before and after the decimal point for presentation types 'g' or 'G'."
->
"The precision is a decimal integer indicating how many digits should be displayed after the decimal point for presentation types 'f' and 'F', or before and after the decimal point for presentation types 'g' or 'G'. For the detailed interpretation of the precision, see below."

**Comment by ericvsmith** [comment]
@mdickinson has spent a lot of effort editing the wording for “g”. He can decide if it’s worth changing.
