### ISSUE TITLE
The shown version info of 32-bit python 3.11.2 is wrong

### ISSUE THREAD

**Issue by githubuser11123** [python/cpython#102600]
When i type in 'python' in cmd, it shows something like '[MSC v.1934 64 bit (Intel)] on win32', it tells that i have a 64-bit version. But in fact, i installed 32-bit version of python 3.11.2.
How odd, i can not reproduce this probem on my virtual machine. Can it be possible that i've made some mistakes?

**Comment by ericvsmith** [comment]
Print out sys.maxsize. If it's 9223372036854775807, you're on a 64 bit system.

**Comment by githubuser11123** [comment]
> Print out sys.maxsize. If it's 9223372036854775807, you're on a 64 bit system.

Thanks, i will try it next time if i face with the same situation. Now It only seems i had made a mistake.
