### ISSUE TITLE
Remove `None` reference from `co_consts` for lambda functions

### ISSUE THREAD

**Issue by ghost** [python/cpython#102718]
# Feature or enhancement

Don't include a reference to `None` in the `co_consts` for lambda functions (unless `None` is explicitly used).

# Pitch

The reason that `None` is included by default for normal functions is that it's much easier to just include it rather than checking all the return paths to see if the function ever implicitly returns. However, with lambda functions this is not necessary, as lambda functions cannot return implicitly. This means that holding a reference to `None` is not necessary. The benefit that not including it would have are speed and memory usage improvements. Both types of improvements would be marginal, but would still exist. I believe that implementing this change would not be *extremely* hard, though I haven't looked very much into how the parsing is handled yet so I'm not sure.

# Previous discussion

There has been no previous discussion about this¹, because this isn't technically a "new feature", more of a performance enhancement. I decided to submit the idea under this category because it's not a bug, crash, or any of the other tags that github provided, more if a small performance enhancement, and I wasn't sure how to categorise it. Because of that, I decided to put it in the "features and enhancements" category, since it's an enhancement. If I made the wrong choice, please let me know so that I can rectify it.

¹ (on official python mailing lists or forums, that is)

**Comment by Resuscitating** [comment]
This issue is incorrect. I'm going to go ahead and close it, since it's wrong.
