### ISSUE TITLE
Typo in https://docs.python.org/3/tutorial/modules.html

### ISSUE THREAD

**Issue by Mariatta** [python/cpython#102703]
# Documentation

> In “is prevents directories with a common name, such as string, unintentionally hiding valid modules that occur later on the module search path” s/ unintentionally/ from unintentionally/

Originally reported in the mailing list by Goldberg, Arthur P.

https://mail.python.org/archives/list/docs@python.org/thread/UMN53Z2TI6XIJ3BG4NDZ2X2BH3GLT4LV/

### Linked PRs
* gh-102707
* gh-102708
* gh-102709

**Comment by terryjreedy** [comment]
Looks ready to close.  Correct if wrong.
