### ISSUE TITLE
Add PyErr_DisplayException(exc) as replacement for PyErr_Display(typ, exc, tb)

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#102755]
Create a single-arg version of PyErr_Display. 

PyErr_Display is in the stable ABI but it is not documented. PyErr_DisplayException will therefore need to be in the stable ABI as well (and documented).

### Linked PRs
* gh-102756
* gh-102826
* gh-102849

**Comment by encukou** [comment]
The new function should only be available in the 3.12+ limited API, see: https://devguide.python.org/developer-workflow/c-api/#adding-a-new-definition-to-the-limited-api
Users who `#define Py_LIMITED_API` expect that their compiled extensions will work with older versions of Python.

Also, the PR removed all tests for `PyErr_Display`. Would it be possible to add at least a small smoke-test back, to ensure it continues to work?
