### ISSUE TITLE
Add sys.last_exc, deprecate sys.last_type, sys.last_value and sys.last_traceback

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#102778]
### Linked PRs
* gh-102779
* gh-102825
* gh-103314
* gh-105190
* gh-105246

**Comment by terryjreedy** [comment]
I appreciate the effort to remove the traces of string exceptions.  Is there a plan to actually stop adding the old last_xxx vars to sys and accessing them in other non-IDLE stdlib modules?

**Comment by iritkatriel** [comment]
Yes, I would like to eventually remove the old fields. 

Since they are module level variables, I don't think they can be properties. But maybe there's something we can do through intercepting getattr on the module?

**Comment by iritkatriel** [comment]
Reopening to finish idlelib.

**Comment by terryjreedy** [comment]
Followup issue for idlelib is #102832 .
