### ISSUE TITLE
Implement TODO in `test_ast.py`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102797]
In `test_ast.py` we have a old TODO:
https://github.com/python/cpython/blob/72186aa637bc88cd5f5e234803af64acab25994c/Lib/test/test_ast.py#L266-L267
How I understand, it says about code snippets in `exec_tests` and `eval_tests`.
So, I've decide to improve it.

### Linked PRs
* gh-102798

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/b8fb369193029d10059bbb5f760092071f3a9f5f.
