### ISSUE TITLE
Allow for built-in modules to be submodules

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#102768]
As discovered while trying to get [NumPy statically compiled into CPython for WASI](https://discuss.python.org/t/wasi-importing-namespaced-3rd-party-c-extensions-with-import-cycles/24606/16?u=brettcannon), the built-in importer automatically rejects any built-in module name with a `.`. But honestly I don't know if there's a need to be so strict since there technically isn't a reason why a built-in module _couldn't_ be a submodule.

**Comment by FFY00** [comment]
Closing in favor of #102700
