### ISSUE TITLE
example at https://docs.python.org/3/library/dataclasses.html fails

### ISSUE THREAD

**Issue by keithbriggs** [python/cpython#102758]
With this example in the docs:

```
@dataclass
class C:
    i: int
    j: int | None = None
```

I get:

`TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'`

This was with 
Python 3.8.10 (default, Nov 14 2022, 12:59:47) .

**Comment by JelleZijlstra** [comment]
You are using an old version of Python. Try Python 3.10 or newer.

**Comment by pochmann** [comment]
And the Python 3.8 documentation (which you can select at the top of the page) doesn't show that code.
