### ISSUE TITLE
shutil.which() is unable to utilize added paths on FreeBSD

### ISSUE THREAD

**Issue by ehthxC7x9D** [python/cpython#102741]
# Versions: 
FreeBSD 13.1-RELEASE
Python 3.9.16

# Paths
`echo $PATH`:
`/home/user/.cargo/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/user/bin`

Code:
```
python3 -c "print(__import__('shutil').which('rustc'))"
-> None
```

# Info and expectations
Running:
 `python3 -c "print(__import__('os').environ.get('PATH', None))"` 

returns: 
`/home/user/.cargo/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/user/bin`

When I use `pdb` to step through I notice that shutil.which() steps through various posix paths but never looks in the ~/.cargo/bin even though it is readily available in my shell cli.

**Comment by ericvsmith** [comment]
As long as you’re stepping through it with a debugger: which line is setting `path`, and what value it is setting it to? Is it using `PATH`, `CS_PATH`, or the fallback value `os.defpath`?

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
After playing with it more I realized `shutil.which()` was only failing to get the `~/.cargo/bin` path inside the venv.  

Outside of the venv I see the following paths, and `shutil.which()` finds it appropriately.:
` /home/user/.cargo/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/user/bin`

But when inside the venv the cargo path is overwritten with a the the venv/bin path, eg:
`/usr/home/user/pythontesting/env/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin:/home/user/bin`.

Apologies for jumping the gun with an erroneous bug report, please close.  While I have you, what am I missing that the venv isn't seeing the PATH?

**Comment by ericvsmith** [comment]
Sorry, I don't know. Maybe the "activate" script is overwriting it? I don't ever activate virtual environments, so I don't have much experience here. Maybe ask on discuss.python.org.
