### ISSUE TITLE
Releasing GIL causes crash in python 3.11 but works 3.10 and earlier

### ISSUE THREAD

**Issue by sys2065** [python/cpython#102732]
Attached example to reproduce (tested win32)

3.10.10 -> OK
3.11.2 -> Fatal Python error: init_threadstate: thread state already initialized

In case it's not a bug, could you advice how to release GIL when Py_Initialize() has it.

This causes pywin32 isapi to crash, original bug report here: https://github.com/mhammond/pywin32/issues/2025

```c
#include <Python.h>
#include <stdio.h>

int main(int argc, char **argv) {
    Py_Initialize();
    PyGILState_STATE old_state = PyGILState_UNLOCKED;
    PyGILState_Release(old_state);
    old_state = PyGILState_Ensure();
    PyGILState_Release(old_state);
    printf("OK");
    return 0;
}

```

(edit: C reproducer by @kumaraditya303)

**Comment by kumaraditya303** [comment]
I am guessing from the reproducer that you mean to release the GIL with 
```c
PyGILState_STATE old_state = PyGILState_UNLOCKED;
PyGILState_Release(old_state);
```
Is that correct? If so why don't use use `PyEval_SaveThread` for it? Can you try current main?

**Comment by sys2065** [comment]
Yes, this code is used here: https://github.com/mhammond/pywin32/blob/main/isapi/src/PythonEng.cpp
(Lines 64, 65 and 93)

PyEval_SaveThread does work.

I'm only end user of pywin32 isapi and would like see this fixed.

First needs to know, if this should be fixed in python or pywin32

**Comment by kumaraditya303** [comment]
It needs to be fixed in pywin32, it should use `PyEval_SaveThread` instead of GIL state apis.

**Comment by sys2065** [comment]
Thanks, I'll ask pywin32 to make this change.

Still interresting this has worked before and there might be others who use similar code.

**Comment by kumaraditya303** [comment]
Closing as it was a pywin32 bug and is fixed now https://github.com/mhammond/pywin32/commit/8b4eb226d693aaff092acc55ad8aa9449baede33.
