### ISSUE TITLE
Allow for built-in modules to be submodules

### ISSUE THREAD

**Issue by kesmit13** [python/cpython#102700]
# Bug report

If you statically link a namespaced extension (such as `numpy.core._multiarray_umath`) and add it to the inittab, it will not get loaded properly. In this case, the path to the extension is passed to the `BultinImporter.find_spec` method which causes it to return `None`. The path is a pointer to the namespace of the extension. 

One possible fix would be to check for a `.` in the name of the extension being loaded. If it contains that, consider it to be a fully-qualified import path and check to see if that fully-qualified name is in the builtins list before moving on to other checks.

# Your environment

- CPython 3.10 (although I believe it's the same in newer versions)
- Linux x86 and Wasm

### Linked PRs
* gh-103162
* gh-103322

**Comment by FFY00** [comment]
In GH-102768 Brett wrote:

> As discovered while trying to get [NumPy statically compiled into CPython for WASI](https://discuss.python.org/t/wasi-importing-namespaced-3rd-party-c-extensions-with-import-cycles/24606/16?u=brettcannon), the built-in importer automatically rejects any built-in module name with a `.`. But honestly I don't know if there's a need to be so strict since there technically isn't a reason why a built-in module _couldn't_ be a submodule.

**Comment by kesmit13** [comment]
Your comments about `numpy.core._multiarray_umath` are correct. The issue that I'm running into is trying to create a statically linked Python binary that includes numpy and pandas. In order to do this, I have to use `PyImport_AppendInittab` with the C extensions from those packages.

**Comment by FFY00** [comment]
Thanks, I think it makes sense to drop this limitation. I don't think there's anything else preventing built-in modules from being submodules other than the path check, so removing that check should be all that's needed.
