### ISSUE TITLE
Using multiprocessing.Value in a PR causes some unit tests to crash on Ubuntu only

### ISSUE THREAD

**Issue by YvesDup** [python/cpython#102786]
I am working on this PR:
 + https://github.com/python/cpython/pull/102499

And I have errors on unit tests on **Ubuntu** only: [See](https://github.com/python/cpython/actions/runs/4449006512/jobs/7812590271?pr=102499) 

In the multiprocessing.Queue class, I use multiprocessing.Value to share a state value beetween processes using the Queue.
All unit tests on Mac and Windows run successfully.

On Ubuntu the following  `asyncio` tests crashes:
```bash
python -m unittest -v test.test_asyncio.test_events.TestPyGetEventLoop.test_get_event_loop_new_process
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/cpython/cpython/Lib/test/test_asyncio/test_events.py", line 2779, in test_get_event_loop_new_process
    self.loop.run_until_complete(main()),
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cpython/cpython/Lib/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/ubuntu/cpython/cpython/Lib/test/test_asyncio/test_events.py", line 2771, in main
    pool = concurrent.futures.ProcessPoolExecutor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cpython/cpython/Lib/concurrent/futures/process.py", line 708, in __init__
    self._call_queue = _SafeQueue(
                       ^^^^^^^^^^^
  File "/home/ubuntu/cpython/cpython/Lib/concurrent/futures/process.py", line 170, in __init__
    super().__init__(max_size, ctx=ctx)
  File "/home/ubuntu/cpython/cpython/Lib/multiprocessing/queues.py", line 57, in __init__
    self._shutdown_state = context._default_context.Value(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/cpython/cpython/Lib/multiprocessing/context.py", line 134, in Value
    from .sharedctypes import Value
  File "/home/ubuntu/cpython/cpython/Lib/multiprocessing/sharedctypes.py", line 10, in <module>
    import ctypes
  File "/home/ubuntu/cpython/cpython/Lib/ctypes/__init__.py", line 8, in <module>
    from _ctypes import Union, Structure, Array
ModuleNotFoundError: No module named '_ctypes'
``` 
Results are identical for the following tests:

+ `compileall` tests
  +  test.test_compileall.CompileallTestsWithoutSourceEpoch.test_ddir_multiple_workers
  +  test.test_compileall.CompileallTestsWithoutSourceEpoch.test_ddir_empty_multiple_workers
  +  test.test_compileall.CompileallTestsWithSourceEpoch.test_ddir_multiple_workers
  +  test.test_compileall.CompileallTestsWithSourceEpoch.test_ddir_empty_multiple_workers
  +  test.test_compileall.CommandLineTestsWithSourceEpoch.test_workers
+ `concurrent_futures` tests
  + test.test_concurrent_futures.ProcessPoolForkserverProcessPoolExecutorTest.test_submit
  +  test.test_concurrent_futures.ProcessPoolForkserverProcessPoolExecutorTest.test_traceback
  +  test.test_concurrent_futures.ProcessPoolForkserverProcessPoolShutdownTest.test_context_manager_shutdown
  +  test.test_concurrent_futures.ProcessPoolForkserverProcessPoolShutdownTest.test_del_shutdown
  +  and more ......

Problem seems to be here, only with Ubuntu:

```bash
File "/home/ubuntu/cpython/cpython/Lib/concurrent/futures/process.py", line 708, in __init__
    self._call_queue = _SafeQueue(`
```

So what's wrong in this file about the`_ctypes` module ?
Thank you for your help

Python version: Python 3.12.0a6+

**Comment by ericvsmith** [comment]
How did you install python? It looks like it was built without `_ctypes`.

**Comment by YvesDup** [comment]
I work on Mac OSX, local unit tests are all successful. 
When I saw unit tests failed on Ubuntu cPython plateform, I installed a VM 'multipass'  Ubuntu on my Mac, built a Python with a basic 
configuration as './configure'. . from my PR and run tests again. Results are bad too.

**Comment by YvesDup** [comment]
At this time, I understand your point of view

PS: I did a full installation. There are still problems, I'm still investigating.
