### ISSUE TITLE
Improve coverage of `_collections_abc._CallableGenericAlias`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#102721]
Right now several important implementation details of this type is not covered:

1. Pickle with `ParamSpec`

<img width="1254" alt="Снимок экрана 2023-03-15 в 12 55 15" src="https://user-images.githubusercontent.com/4660275/225277373-31b4b04e-a172-49d9-bd86-5ff98a52a66d.png">

2. Invalid type argument

<img width="1247" alt="Снимок экрана 2023-03-15 в 12 55 28" src="https://user-images.githubusercontent.com/4660275/225277473-0f2c3c7c-c0ff-4625-91c5-dd03e33aa2e9.png">

Related to https://github.com/python/cpython/issues/102615 where this was originally discovered.
I will send a PR shortly.

### Linked PRs
* gh-102722
* gh-102788
* gh-102790

**Comment by AlexWaygood** [comment]
Thanks @sobolevn!
