### ISSUE TITLE
Bug in dataclass naming

### ISSUE THREAD

**Issue by joaopfg** [python/cpython#102775]
Hello, quick problem that I had with dataclasses. 

I wanted to indicate that some dataclasses of my module are private (just used as fields of the final dataclass), thus prefixing them with **__**  . Example:

```
from dataclasses import dataclass, field
@dataclass
class __C:
    c: int

@dataclass
class D:
    d: __C = field(default_factory=__C)
```
This throws a mysterious: 

`NameError: name '_D__C' is not defined`

Is this a bug ?

**Comment by Eclips4** [comment]
Cause of name mangling, during the phase of execution body of your class, `__C` transformed to `_D__C`, because it that it his own attribute
If you wanna create a "private" dataclass, name it with one leading underscore.
So, it's not a problem of dataclasses.
Reproducible example without of dataclasses:
```python
class __C:
    pass
class B:
    attr = __C
 
 Traceback (most recent call last):
  File "C:\Users\KIRILL-1\CLionProjects\cpython\example.py", line 5, in <module>
    class B:
  File "C:\Users\KIRILL-1\CLionProjects\cpython\example.py", line 6, in B
    attr = __C
           ^^^
NameError: name '_B__C' is not defined
```

**Comment by joaopfg** [comment]
@Eclips4 Thanks. Can you give more details, please ? What happens in name mangling that causes this problem ?

**Comment by Eclips4** [comment]
Did you know something about name mangling process? =)
You can read this: https://docs.python.org/3/tutorial/classes.html#private-variables

**Comment by joaopfg** [comment]
Didn't know about it. Thanks.

Wouldn't be interesting to have a mangling mechanism at module level as well (maybe with triple underscores) ?

**Comment by Eclips4** [comment]
Why is it necessary?
As I said, if you want to define a "private"(i.e prevent usage of this class in other modules), you should name your class with one leading underscore. It's common practice

**Comment by gryznar** [comment]
Is this intentional, that mangling does not work during imports? Let's suppose, that we have class `__A` in `module_a.py`, and `module_b.py`.
If we would like to import in `module_b.py` class `__A` mangling does not work and import works without error?

**Comment by Eclips4** [comment]
Name mangling works in body of classes. 
You can import class `__A` without erros, but if you try to use `__A` in body of some class which you define, it's raise a `NameError`.
```python
from test import __C


class B:
    def method(self):
        print(__C)


B().method()
>
Traceback (most recent call last):
  File "C:\Users\KIRILL-1\PycharmProjects\experiments\main.py", line 9, in <module>
    B().method()                                                                   
  File "C:\Users\KIRILL-1\PycharmProjects\experiments\main.py", line 6, in method  
    print(__C)                                                                     
NameError: name '_B__C' is not defined 
```

**Comment by joaopfg** [comment]
@Eclips4 For the same reason it's useful for classes. Isn't it useful to disallow the direct access to an attribute from disjoint scopes ? In the case of modules, it could be useful to disallow direct access to an attribute from another module.

**Comment by Eclips4** [comment]
That question isn't related to the problem of this issue.
If you want to propose some idea, you'll should discuss it on https://discuss.python.org/c/ideas/6 .

**Comment by joaopfg** [comment]
Thanks, I proposed the idea at the place you indicated: https://discuss.python.org/t/name-mangling-mechanism-at-module-level/24940?u=joaopfg

I will close the issue, since it's clear for me now.
