### ISSUE TITLE
threading.Event.wait - Improve logic

### ISSUE THREAD

**Issue by mementum** [python/cpython#102821]
# Feature or enhancement

https://github.com/python/cpython/blob/045c8a1779036172f20d60bf206649c8823bb34b/Lib/threading.py#L619-L623

Reading the code in threading.Event.wait, it would seem unnecessary and redundant to assign the internal flag and/or assign the return value of the Condition.wait, should it be called.

Hence the simplification using the power of the `or` operator which directly returns the first operand if `True`, else it will evaluate and return the second operand.

```python
        with self._cond:
            return self._flag or self._cond.wait(timeout)
```

# Pitch

Reduces the logic and makes it obvious

# Previous discussion

### Linked PRs
* gh-102822
* gh-102843

**Comment by AlexWaygood** [comment]
The proposed patch does not produce any measurable speedup relative or fix any user-visible bugs. Closing as rejected.
