### ISSUE TITLE
logging module LogRecord can accept non-str msg but it's not documented

### ISSUE THREAD

**Issue by aminalaee** [python/cpython#102873]
# Documentation

In the documentation of the logging `LogRecord` it's mentioned that it accepts msg as str argument:
https://docs.python.org/3/library/logging.html#logging.LogRecord

But just below that it explains that in `getMessage`:

> Returns the message for this [LogRecord](https://docs.python.org/3/library/logging.html#logging.LogRecord) instance after merging any user-supplied arguments with the message. If the user-supplied message argument to the logging call is not a string, [str()](https://docs.python.org/3/library/stdtypes.html#str) is called on it to convert it to a string. This allows use of user-defined classes as messages, whose __str__ method can return the actual format string to be used.

So non-str messages are allowed, and also in LogRecord attributes it's mentioned that non-str messages work and are accepted:
https://docs.python.org/3/library/logging.html#logrecord-attributes

Initially started the discussion in https://github.com/python/typeshed/pull/9914

### Linked PRs
* gh-102875
* gh-103003
* gh-103004

**Comment by arhadthedev** [comment]
@vsajip (as a logging expert)

**Comment by AlexWaygood** [comment]
Thanks @aminalaee!
