### ISSUE TITLE
Global library with an alias in importing getting replace by file in the execution folder

### ISSUE THREAD

**Issue by pO0P3R125** [python/cpython#102897]
I don't think this was intended or at least is convoluted, in the case of a library that you use in a program importing another library with an alias (in my case requests imports simple json as jsons) if in the execution folder you have another ".py" file with the name of the alias it'll prioritize the use of that file instead of the original library that it imports

**Comment by ericvsmith** [comment]
Are you saying that when requests import json, it instead imports the jsons.py that you have locally? Can you show a reproducer just using a few small .py, without requests?

**Comment by pO0P3R125** [comment]
here is the small program importing requests (they are in the zip)
![Code_kZdz0fb4h1](https://user-images.githubusercontent.com/43865463/226985223-fda2b425-4e74-4686-96ec-6587819b6046.png)
here is the fake json python library in the same folder as the file importing requests
![Code_4hmzItWoS7](https://user-images.githubusercontent.com/43865463/226990317-77fa2c93-9062-4bb0-8f71-6b05b7f2f696.png)

when I execute the file with the importing it immediatly errors out by trying to import the neccesary libraries for requests
![Code_af8tRWM9EV](https://user-images.githubusercontent.com/43865463/226988927-3f5f31a2-9f68-4c1a-954b-387b5fb634d8.png)

this is the file structure of it
![Code_S10uu4Bkia](https://user-images.githubusercontent.com/43865463/226989335-971e8480-5b98-4af0-9892-caaee81b0d6f.png)

this is the library trying to import library in a completely different folder
![Code_C39id0DFKR](https://user-images.githubusercontent.com/43865463/226989294-56ca9f56-e5c9-48c9-9346-e685d3498e46.png)

[Error.zip](https://github.com/python/cpython/files/11043072/Error.zip)

**Comment by ericvsmith** [comment]
This is different from your original report. In your original report you said if a "jsons.py" exists, there would be a problem when requests does "import simplejson as jsons".

It is expected that you cannot have a module with the same name as a stdlib module. I think that's what you're showing here.

**Comment by pO0P3R125** [comment]
Am sorry for the misunderstanding I thought they were the same ocurrence, nonetheless I seem unable to reproduce the error with a coherent set of steps
