### ISSUE TITLE
Link to wrong function in sys.getfilesystemencoding to get filesystem error handler

### ISSUE THREAD

**Issue by ogayot** [python/cpython#102899]
# Documentation

The doc of the `sys.getfilesystemencoding` function indicates:

> [...] the encoding used with the [filesystem error handler](https://docs.python.org/3/glossary.html#term-filesystem-encoding-and-error-handler) to convert between Unicode filenames and bytes filenames. The filesystem error handler is returned from [getfilesystemencoding()](https://docs.python.org/3/library/sys.html?highlight=sys#sys.getfilesystemencoding).

The filesystem error handler is actually returned by the `sys.getfilesystemencodeerrors` function.

### Linked PRs
* gh-102901
* gh-103278
* gh-103279

**Comment by itamaro** [comment]
associated PRs are merged - closing
