### ISSUE TITLE
add option for error callback of to shutil.rmtree to accept exception rather than exc_info

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#102828]
shutil.rmtree accepts as ``onerror`` a callback to should expect an exc_info tuple. To move off this, I will add a new kwarg "onexc" which should expect just an exception object. ``onerror``  will continue to work for now, but be deprecated.  

### Linked PRs
* gh-102829
* gh-102835
* gh-102850
* gh-103422

**Comment by serhiy-storchaka** [comment]
I think it is too earlier to deprecate `onerror`. It only creates inconvenience for code that should support multiple Python versions. Opened #112645 for this.

**Comment by kfsone** [comment]
What is the urgency in removing the 'onerror' parameter? A concern about shutil.rmtree performance of accepting both arguments? Or is it just part of the core-python lemming-suicide pact to drive users away by making python as consistently self-incompatible as possible?

**Comment by iritkatriel** [comment]
> What is the urgency in removing the 'onerror' parameter? 

Nobody indicated any urgency. You made that up just so you can entertain us with your witty insult.
