### ISSUE TITLE
Is the list.copy method a deep copy method?

### ISSUE THREAD

**Issue by c4-driod** [python/cpython#102867]
https://docs.python.org/3/tutorial/datastructures.html#more-on-lists
list.copy is a deep copy method.

**Comment by Eclips4** [comment]
Why is it a deep copy method?
```python
a = [1, 2, 3, [4, 5]]
b = a.copy()
b[3][0] = 5
print(a)
print(b)
> 
[1, 2, 3, [5, 5]]
[1, 2, 3, [5, 5]]
```

```python
from copy import deepcopy

a = [1, 2, 3, [4, 5]]
b = deepcopy(a)
b[3][0] = 5
print(a)
print(b)
>
[1, 2, 3, [4, 5]]
[1, 2, 3, [5, 5]]
```
So, you have misunderstand something. `list.copy` creates a shallow copy, as documented.

**Comment by c4-driod** [comment]
Sorry, I misunderstood it.
I did this because when I test code like this:
```
a = [1, 3]
b = a[:]
b[1] = 9
print(a)


```
And I got "[1, 3]" as result.
&nbsp;


晓鸉
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月21日(星期二) 下午4:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [python/cpython] Is the list.copy method a deep copy method? (Issue #102867)





 
Why is it a deep copy method?
 a = [1, 2, 3, [4, 5]] b = a.copy() b[3][0] = 5 print(a) print(b) &gt;  [1, 2, 3, [5, 5]] [1, 2, 3, [5, 5]]
 from copy import deepcopy a = [1, 2, 3, [4, 5]] b = deepcopy(a) b[3][0] = 5 print(a) print(b) &gt; [1, 2, 3, [4, 5]] [1, 2, 3, [5, 5]]
 
So, you have misunderstand something. list.copy creates a shallow copy, as documented.

**Comment by stevendaprano** [comment]
This is a bug tracker for reporting bugs and feature requests, not a help desk for learning about Python. If you want to ask questions, please ask them on [the Python Discuss](https://discuss.python.org/c/users/7).
