### ISSUE TITLE
Improve test coverage for the math module

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#102837]
Sometimes input checks are missing (e.g. L989 of math_1 or L1023 of math_1a), sometimes exceptional cases are not tested (e.g. in fsum), some code is just inaccessible (like L3519 in the perm_comb_small() helper).  See attached coverage report (for `./python -m test test_math`).

I believe, everything should be tested (except for memory errors and similar special cases).

[lcov-report.zip](https://github.com/python/cpython/files/11014453/lcov-report.zip)

### Linked PRs
* gh-102523
* gh-110000
* gh-111930
* gh-112029
* gh-112030
* gh-112041

**Comment by skirpichev** [comment]
@hauntsaninja, wait.  As I [said in the PR thread](https://github.com/python/cpython/pull/102523#issuecomment-1459641522) - there are still some uncovered lines/branches.  I think it's worth to keep this issue open until it's fixed completely.

**Comment by hauntsaninja** [comment]
Ah, missed that since it was early on. Re-opened!
