### ISSUE TITLE
Add docstrings to asyncio.Timeout

### ISSUE THREAD

**Issue by JosephSBoyle** [python/cpython#102810]
# Feature or enhancement

`asyncio.Timeout` doesn't have docstrings. (`asyncio.timeout` does though:) )

# Pitch
Adding docstrings would increase the usability of this class.

# Notes
I will open a PR for this shortly.

I envisage starting out copying from the docs: https://docs.python.org/3/library/asyncio-task.html#asyncio.Timeout
and hammering out the wording in the PR, similar to what was done for `asyncio.TaskGroup` in https://github.com/python/cpython/issues/102560.

### Linked PRs
* gh-102811
* gh-102834
* gh-102934
* gh-102958

**Comment by gvanrossum** [comment]
(Process note for the future: We don't require issues for adding docs or docstrings -- we'll set the "skip issue" label on the PR. Though we might sometimes create such issues to *solicit* contributions. Anyway, I'll review the PR this weekend.)

**Comment by JosephSBoyle** [comment]
Closing as done, thanks for the help on this!

**Comment by AlexWaygood** [comment]
> Closing as done, thanks for the help on this!

https://github.com/python/cpython/pull/102811#issuecomment-1475361441 is still to do!

**Comment by JosephSBoyle** [comment]
Aha okay, I was thinking of creating a new issue to plan the changes but I'll draft a PR sometime in the next couple of days and we can just discuss things on there:)

**Comment by AlexWaygood** [comment]
Thanks @JosephSBoyle!
