### ISSUE TITLE
PEP 701 – Syntactic formalization of f-strings

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#102856]
- [x] Changes in the C tokenizer
- [x] Categorize failing tests
- [x] Fix failing tests or modify/remove them as needed
- [x] Changes in Python tokenizer

### Linked PRs
* gh-102855
* gh-103633
* gh-103634
* gh-104006
* gh-104323
* gh-104731
* gh-104824
* gh-104847
* gh-104852
* gh-104854
* gh-104861
* gh-104865

**Comment by pablogsal** [comment]
CC: @lysnikolaou @isidentical @mgmacias95

**Comment by pablogsal** [comment]
See [this](https://github.com/we-like-parsers/cpython/issues/184) for the latest report on errors from @isidentical

**Comment by pablogsal** [comment]
Draft PR for the C tokenizer up: https://github.com/python/cpython/pull/102855

**Comment by pablogsal** [comment]
Things for the cleanup of https://github.com/python/cpython/pull/102855:

- Cleaning up the grammar and the action helpers (the names are still ridiculous and there are multiple rules commented out).
- Remove the old parsing code and check that we didn't break anything 😅 
- Clean/refactor the tokenizer struct (better names, factor stuff into its own structure as needed).
- Consider factoring out `tok_get_fstring_mode` because is a monster.
-

**Comment by pablogsal** [comment]
Ok with https://github.com/python/cpython/pull/102855 we have the following failing tests:
   
- [ ] test_ast 
-[ ] test_cmd_line_script
- [ ] test_eof 
- [ ] test_exceptions
- [ ] test_fstring
- [ ] test_tokenize 
- [ ] test_type_comments 
-[ ] test_unparse

Most of these are updating error messages, line numbers and other stuff but some may have actual bugs so we should check them. Please, mention which ones are you working on so we don't clash with one another.

**Comment by mgmacias95** [comment]
Working on `test_tokenize`

**Comment by Eclips4** [comment]
Hello, Pablo!
Can I get work on `test_ast`?
Recently I sent some PR's about this file (for example, #102797). So, I have some experience in that =)

**Comment by ramvikrams** [comment]
I can work with `test_type_comments` and `test_unparse`.

**Comment by pablogsal** [comment]
@Eclips4 @ramvikrams wonderful! Just make PRs against my fork!

Report here or ping any of us if you find something that could be a bug (don't just fix the tests blindly because there may be bugs lurking).

**Comment by pablogsal** [comment]
@lysnikolaou can you work on cleaning up the grammar + the actions?

@isidentical can you work on cleaning up some of the tokenizer layers? (This is quite a lot so we can probably work together here).

**Comment by Eclips4** [comment]
@pablogsal
About `test_ast.py`
Seems thats like there only a one test will be failed, and how I undestand, that's a bug:
https://github.com/python/cpython/blob/7f760c2fca3dc5f46a518f5b7622783039bc8b7b/Lib/test/test_ast.py#L779-L780

I think, there's two solutions:
1. Remove this test, because support of python3.7 will be ended soon.
2. Now errors raised by `tokenizer.c` instead of `string_parser.c`, so as I understand, we should change `python_gram`, is it right?

**Comment by pablogsal** [comment]
> 2\. Now errors raised by `tokenizer.c` instead of `string_parser.c`, so as I understand, we should change `python_gram`, is it right? ( We need access to `feature_version`, which in tokenizer inaccessible )

Probably we can do this but on the other hand I would prefer to not overcomplicate this so I think (1) is better

**Comment by Eclips4** [comment]
Also, I can take a look at `test_cmd_line_script`. Seems easy.

**Comment by pablogsal** [comment]
> Also, I can take a look at `test_cmd_line_script`. Seems easy.

All yours!

**Comment by ramvikrams** [comment]
@pablogsal in  `test_type_comments`  we have not used any f-strings.

**Comment by pablogsal** [comment]
> @pablogsal in `test_type_comments` we have not used any f-strings.

The one failing there is a feature version problem:

```
======================================================================
FAIL: test_fstring (test.test_type_comments.TypeCommentTests.test_fstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/test_type_comments.py", line 275, in test_fstring
    for tree in self.parse_all(fstring, minver=6):
  File "/home/runner/work/cpython/cpython-ro-srcdir/Lib/test/test_type_comments.py", line 239, in parse_all
    with self.assertRaisesRegex(SyntaxError, expected_regex,
AssertionError: SyntaxError not raised : feature_version=(3, 4)

----------------------------------------------------------------------
```

**Comment by pablogsal** [comment]
> We can just change this to 6, and this test will be pass.
> I don't research this problem, but this solution looks like the simplest.
> However... supporting syntax of python3.4 && 3.5 looks cinda strange.

I don't think that will work because we are not doing version checking anymore. See previous comments. The fix is probably to no pass `feature_version`.

**Comment by sunmy2019** [comment]
Looks like no one is analyzing `test_exceptions`. I will look into it these two days.

4 platforms seem to have met the same problem here.

**Comment by pablogsal** [comment]
@isidentical @lysnikolaou i have pushed some rules for error messages, please take a look and complete them with more if you have some spare cycles. With these the failures in `test_fstring` have decreased notably

**Comment by isidentical** [comment]
I can confirm that the total number of failures has been decrased from 88 to 63. I'll try to see what are the most high impact ones and submit a PR to clear them.

**Comment by isidentical** [comment]
If anyone intends to work on any of the remaining tasks in `test_fstring`, please double check with this PR (https://github.com/pablogsal/cpython/pull/52) since it brings down the total failures to 30 with some explanations/required decisions for the rest.

**Comment by sunmy2019** [comment]
After looking into the failure in `test_exceptions`.
```py
check(b'Python = "\xcf\xb3\xf2\xee\xed" +', 1, 18)
```

Old parser and the new parser raises the same exception (UnicodeDecodeError), but with different col_offset. This is because it was raised by the wrong token.

I would consider it a bug in the old parser. Just as this comment mentions,
https://github.com/python/cpython/blob/64cb1a4f0f0bc733a33ad7a6520e749ca1cdd43f/Parser/string_parser.c#L38-L48

the error token was not correctly set in the old parser.

Maybe we should open an issue for the old parse? But the possible fixing might be error-prone, since we might need to keep track of every possible code path.

As for the new parser, I think a change in the test case would be fine.

**Comment by sunmy2019** [comment]
The other test failure can be simplified as
```py
f"{6 0}"
```

The old parser will try to send "6 0" into the parser for f-string, thus will raise an SyntaxError like
```
    (6 0)
     ^^^
SyntaxError: f-string: invalid syntax. Perhaps you forgot a comma?
```

The new parser will (force) exccpt `}` right after `6`. Thus the error message would be

```
    f"{6 0}"
         ^
SyntaxError: expected '}'
```

The new parser cannot match the `invalue expression`, due to `p->call_invalid_rules` was not correctly set to 1.

With `p->call_invalid_rules = 1`, the new parser will output
```
    f"{6 0}"
       ^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Comment by sunmy2019** [comment]
I am working on an PR to fix `test_unparse` this weekend.

`_PyPegen_concatenate_strings` did not implement concatenating empty `Constant` with `FormattedValue`, resulting `unparse` failure.

**Comment by sunmy2019** [comment]
Hi, I got some bad news.

I have been testing against memory leaks with `./python -m test -j $(nproc) -R :`
~30% of the tests failed on this parser.

For example,
```
0:01:01 load avg: 13.77 [157/433/42] test_unittest failed (reference leak)
beginning 9 repetitions
test_unittest leaked [89, 89, 89, 89] references, sum=356
test_unittest leaked [90, 89, 89, 89] memory blocks, sum=357
.......
0:01:16 load avg: 15.00 [185/433/49] test_inspect failed (reference leak)
beginning 9 repetitions
test_inspect leaked [429, 429, 429, 429] references, sum=1716
test_inspect leaked [318, 318, 318, 317] memory blocks, sum=1271
```

These references are most likely to leak during the compilation (such as using `import`, using `compile/exec/eval`, or using `ast.parse`)

We might need to look into that.

**Comment by pablogsal** [comment]
Only 12 test left in `test_fstring` and we are ready to go!

**Comment by sunmy2019** [comment]
I think we can make it before beta 1. Formalizing fstring error messages (see https://github.com/pablogsal/cpython/pull/52#discussion_r1148587385) can be left to the end, since it is non-functional.

**Comment by pablogsal** [comment]
I pushed a commit and we are not down to 8

**Comment by pablogsal** [comment]
> I think we can make it before beta 1. Formalizing fstring error messages (see [pablogsal#52 (comment)](https://github.com/pablogsal/cpython/pull/52#discussion_r1148587385)) can be left to the end, since it is non-functional.

Yes and no: there may be some *design* consequences and I am not a fan of deactivating tests to reactivate them later.

**Comment by lysnikolaou** [comment]
There's a small discrepancy around the conversion character between our version and the string parser. The string parser does not allow spaces before *or after* the conversion character. For example:

```python3
>>> f"{'3'!r : >10s}"
  File "<stdin>", line 1
    f"{'3'!r : >10s}"
                     ^
SyntaxError: f-string: expecting '}'
```

Our version, while not allowing for spaces between `!` and the character, allows spaces after.

```python3
>>> f"{'3'!r : >10s}"
"       '3'"
```

What do you think about this? I feel okay about it, although it isn't really consistent with our decision on spaces after the `!` character.

**Comment by pablogsal** [comment]
> What do you think about this? I feel okay about it, although it isn't really consistent with our decision on spaces after the `!` character.

I feel that this is fine, and would be very difficult to disallow to be honest because these are different tokens anyway. It won't affect existing code and I don't see any reason to forbid it going foward.

**Comment by pablogsal** [comment]
7 tests to go thanks to @lysnikolaou ❤️

**Comment by lysnikolaou** [comment]
With pablogsal/cpython#65, we only have two errors to go.

```python3
======================================================================
FAIL: test_format_specifier_expressions (test.test_fstring.TestCase.test_format_specifier_expressions) (str='f\'{"s"!r{":10"}}\'')
----------------------------------------------------------------------
  File "<string>", line 1
    f'{"s"!r{":10"}}'
            ^
SyntaxError: f-string: expecting '}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lysnikolaou/repos/python/cpython/Lib/test/test_fstring.py", line 32, in assertAllRaise
    with self.assertRaisesRegex(exception_type, regex):
AssertionError: "f-string: invalid conversion character 'r{"': expected 's', 'r', or 'a'" does not match "f-string: expecting '}' (<string>, line 1)"

======================================================================
FAIL: test_format_specifier_expressions (test.test_fstring.TestCase.test_format_specifier_expressions) (str="f'{4:{/5}}'")
----------------------------------------------------------------------
  File "<string>", line 1
    f'{4:{/5}}'
          ^
SyntaxError: f-string: expecting '}'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/lysnikolaou/repos/python/cpython/Lib/test/test_fstring.py", line 32, in assertAllRaise
    with self.assertRaisesRegex(exception_type, regex):
AssertionError: "f-string: invalid syntax" does not match "f-string: expecting '}' (<string>, line 1)"
```

These are hard to handle correctly, if we have the `invalid_replacement_field` rule stay the same to catch those `expected '}'` cases. There are the following 3 options, I guess.
1. Take more time to figure out whether we can find a smart way to differentiate between these things (can't see something since yesterday)
2. Be okay with sometimes emitting a `expecting '}'` error, while there are other syntax errors within the f-string (keeping `invalid_replacement_field` as-is).
3. Be okay with sometimes emitting a `invalid syntax` error, when we could have done a better error (probably making `invalid_replacement_field` require both a conversion character and a valid format spec).

Thoughts?

**Comment by sunmy2019** [comment]
Catching all errors seems unrealistic. But I think we do have an opportunity to improve.

```
invalid_replacement_field:
    | '{' a='=' { RAISE_SYNTAX_ERROR_KNOWN_LOCATION(a, "f-string: expression required before '='") }
    | '{' a=':' { RAISE_SYNTAX_ERROR_KNOWN_LOCATION(a, "f-string: expression required before ':'") }
    | '{' a='!' { RAISE_SYNTAX_ERROR_KNOWN_LOCATION(a, "f-string: expression required before '!'") }
    | '{' a='}' { RAISE_SYNTAX_ERROR_KNOWN_LOCATION(a, "f-string: empty expression not allowed") }
    | '{' (yield_expr | star_expressions) "="? !('!' | ':' | '}') {
        PyErr_Occurred() ? NULL : RAISE_SYNTAX_ERROR("f-string: expecting '!', or ':', or '}'")
    }
    | '{' (yield_expr | star_expressions) "="? invalid_conversion_character
    | '{' (yield_expr | star_expressions) "="? ['!' NAME] !(':' | '}') {
        PyErr_Occurred() ? NULL : RAISE_SYNTAX_ERROR("f-string: expecting ':' or '}'")
    }
    | '{' (yield_expr | star_expressions) "="? [ '!' NAME ] [ ':' fstring_format_spec* ] !'}' {
        PyErr_Occurred() ? NULL : RAISE_SYNTAX_ERROR("f-string: expecting '}'")
    }
```

**Comment by sunmy2019** [comment]
With this new grammer,
```
  File "a.py", line 1
    f'{"s"!r{":10"}}'
            ^
SyntaxError: f-string: expecting ':' or '}'
```
much better I think.

**Comment by lysnikolaou** [comment]
Totally agree. Good idea! Will you open a PR?

**Comment by sunmy2019** [comment]
Sure

**Comment by sunmy2019** [comment]
Hi, there. Will anyone take a look at https://github.com/pablogsal/cpython/pull/67?

**Comment by pablogsal** [comment]
We are almost there, seems that we still have a small failure:

```
FAIL: test_random_files (test.test_tokenize.TestRoundtrip.test_random_files)
```

@isidentical this may be that we lack some changes in the untokenize function

**Comment by sunmy2019** [comment]
@pablogsal We lack changes in both the tokenize and the untokenize function. It cannot recognize the new f-string grammar. See https://github.com/pablogsal/cpython/pull/67#issuecomment-1505840208

**Comment by pablogsal** [comment]
Seems that we have a failing tests in the buildbots:

https://buildbot.python.org/all/#/builders/802/builds/760

**Comment by pablogsal** [comment]
This code is kind of wrong:

https://github.com/python/cpython/blob/6be7aee18c5b8e639103df951d0d277f4b46f902/Parser/tokenizer.c#L2513-L2517

This fails when the f-string closes in a different line due to the expression taking multiple lines:

```
>>> f"blech{
... 1
... +
... 1
... }
... "
```

Or for example, if you do

```
>>> f"123{1}
...
```

In both cases the values of `tok->cur` and `tok->line_start` are garbage.

**Comment by pablogsal** [comment]
@cmaureir its going to work on allowing comments as per the specification.

**Comment by lysnikolaou** [comment]
@mgmacias95 @pablogsal How's the work on the tokenize module going? Are we going to be able to add that until the beta? Is it going to be considered okay to add it later as well?

**Comment by flying-sheep** [comment]
Ah great! I didn't know someone would continue PEP 536. Happy that it's happening!

Shouldn't PEP 536 be mentioned in this one?

**Comment by pablogsal** [comment]
> Ah great! I didn't know someone would continue PEP 536. Happy that it's happening!
> 
> 
> 
> Shouldn't PEP 536 be mentioned in this one?

It's mentioned in the PEP:

https://peps.python.org/pep-0701/

Btw as heads up: We don't monitor normally closed issues so is very likely that people won't answer to comments when the issue is closed :)

**Comment by flying-sheep** [comment]
Thanks! Seems like I missed the mention then. Perfect!
