### ISSUE TITLE
Autodetect for RUSAGE_BOTH looks not to be working

### ISSUE THREAD

**Issue by oddjobz** [python/cpython#102857]
# Bug report

On stock distro Python (on say Ubuntu) RUSAGE_BOTH is not available. I'm testing specifically on Ubuntu 22.04 with Python 3.10 and 3.12(dev), so this is with the stock distro Python (3.10.6) and "pyenv" default builds of 3.10.7 and 3.12 dev.

```
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import resource
>>> resource.RUSAGE_SELF
0
>>> resource.RUSAGE_BOTH
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'resource' has no attribute 'RUSAGE_BOTH'. Did you mean: 'RUSAGE_SELF'?
>>> 
```

If I compile from scratch and include CFLAGS = "-DRUSAGE_BOTH", it works just fine.
```
$ env PYTHON_CFLAGS='-DRUSAGE_BOTH' pyenv install 3.10.7
Installing Python-3.10.7...
Installed Python-3.10.7 to /home/sandbox/.pyenv/versions/3.10.7
$ pyenv virtualenv 3.10.7 bugreport
$ pyenv activate bugreport
(bugreport) $ python
Python 3.10.7 (main, Mar 20 2023, 21:56:46) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import resource
>>> resource.RUSAGE_BOTH
1
>>> 
```
# Your environment
- CPython versions tested on: 3.10.6, 3.10.7, 3.12
- Operating system and architecture: Stock KUbuntu 22.04, fully updated, Linux version 5.15.0-60-generic (buildd@lcy02-amd64-054) (gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0, GNU ld (GNU Binutils for Ubuntu) 2.38) # 66-Ubuntu SMP Fri Jan 20 14:29:49 UTC 2023

**Comment by arhadthedev** [comment]
@Yhg1s (as a resource [expert](https://devguide.python.org/core-developers/experts/))

**Comment by oddjobz** [comment]
Yes, quite right .. sorry, didn't check.
I was just trying to highlight the problem rather than present a solution :-)

Anyway, my point was that the documentation seems to imply all the options should be available, yet on  the standard Ubuntu build, they're not.  Looking at the standard Debian build, 3.11.2 has SELF, CHILDREN and THREAD, but not BOTH.

In the interests of not confusing us poor application programmers, either removing BOTH from the docs, indicating it's not available by default, or amending the standard build with a -DRUSAGE_BOTH=-2 might be worth considering, unless there's some other mitigation I've missed?

(is there a reason to define all the constants except BOTH, seems unusual?)

**Comment by Yhg1s** [comment]
Python just checks if RUSAGE_BOTH is defined and exports it as-is if so, so it's not surprising that adding it to CFLAGS manually makes that happen. (In fact, that shows that the autodetect _is_ working.) It just looks like your _platform_ doesn't have it, so your Python also doesn't have it. The documentation literally says "May not be available on all systems", so I don't think there's anything to do here.
