### ISSUE TITLE
Confused traceback while `floordiv` or `mod` happens between `Fraction` and `complex` objects

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#102840]
```python
from fractions import Fraction
a = Fraction(1, 2)
b = a // 1j
>
Traceback (most recent call last):
  File "C:\Users\KIRILL-1\CLionProjects\cpython\example.py", line 5, in <module>
    b = a // 1j
        ~~^^~~~
  File "C:\Users\KIRILL-1\AppData\Local\Programs\Python\Python311\Lib\fractions.py", line 363, in forward
    return fallback_operator(complex(a), b)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unsupported operand type(s) for //: 'complex' and 'complex'
```
This traceback really confused me.
However, it's easy to fix, just need change these lines:
https://github.com/python/cpython/blob/5e6661bce968173fa45b74fa2111098645ff609c/Lib/fractions.py#L620-L621
To this:
```python
elif isinstance(b, complex):
    try:
        return fallback_operator(complex(a), b)
    except TypeError:
        raise TypeError(
            "unsupported operand type(s) for %r: %r and %r" % (
                fallback_operator.__name__,
                type(a).__qualname__,
                type(b).__qualname__)
        ) from None
```
So, after that, we have a pretty nice traceback:

```python
Traceback (most recent call last):
  File "C:\Users\KIRILL-1\CLionProjects\cpython\example.py", line 5, in <module>
    b = a // 1j
        ~~^^~~~
  File "C:\Users\KIRILL-1\CLionProjects\cpython\Lib\fractions.py", line 624, in forward
    raise TypeError(
TypeError: unsupported operand type(s) for 'floordiv': 'Fraction' and 'complex'
```

But, here a one problem - would be nice to have in traceback originally `//` instead of `floordiv`. I have no idea how to do it, without create a mapping with names. Theoretically - we can add a special attribute for it in `operator`, but it should be a another discussion.

### Linked PRs
* gh-102842

**Comment by Eclips4** [comment]
In fact, this case is also suitable for `mod`.

**Comment by Eclips4** [comment]
Thanks!
Thats looking more pythonic, and this solves the problem, btw, tests are green. I'll send a PR.

**Comment by ericvsmith** [comment]
As a rule we don't do type checking like this. Is the original traceback really that confusing?

**Comment by ericvsmith** [comment]
Yes, but the code in the traceback shows that it's converting one argument to `complex`, so that explains one of them. But maybe I overestimate what people can figure out from the traceback.

**Comment by Eclips4** [comment]
Assessment of what can be understood by humans within traceback - really hard and subjective thing, so I can't say anything at all. 
However, PR which related with this issue, doesn't break backward compatibility, just make prettier traceback, I think, we should take in account that.

**Comment by ericvsmith** [comment]
@terryjreedy: Thanks. I was trying to get across that in general we don't try to improve messages where duck typing fails.

But you're correct, in this case we are already dispatching based on the type of a parameter, so my argument is weak. I think the better solution here might be to not try to convert the numerator to a complex value, since we know that `a_complex // b_complex` isn't going to work. But that would require some surgery to make `//` a special case, different from say `a_complex * a_float`.

**Comment by serhiy-storchaka** [comment]
I would like to backport this change (the final version), but other coredevs were skeptical. Confusing error message is not a large bug.
