### ISSUE TITLE
Redundant parens in itertools.batched recipe

### ISSUE THREAD

**Issue by wimglenn** [python/cpython#102876]
# Documentation

```
def batched(iterable, n):
    # batched('ABCDEFG', 3) --> ABC DEF G
    if n < 1:
        raise ValueError('n must be at least one')
    it = iter(iterable)
    while (batch := tuple(islice(it, n))):
        yield batch
```

The parentheses around the `while` condition are superfluous and could be removed for a slight improvement in readability.

### Linked PRs
* gh-102877

**Comment by terryjreedy** [comment]
I personally view this trivial style nit a waste of developer time as an issue (as opposed to a PR review suggestion), but for itertools, it is Raymond's decision.

**Comment by wimglenn** [comment]
I don't think it is a waste of time. People will be copy-pasting this recipe from the docs all over the place until they are on 3.12+, and their linters will complain about the parens (e.g. PyCharm puts some squiggly lines there)
