### ISSUE TITLE
Document that float // float returns a float

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#102823]
PEP 238 [states clearly](https://peps.python.org/pep-0238/#semantics-of-floor-division) that the result of `x // y` is a `float`, when `x` and `y` both have type `float`.

> For floating point inputs, the result is a float. For example:
> 
>     3.5//2.0 == 1.0
> 

And indeed this is the behaviour that's been in place since Python 2.2. However, we seem to be missing a clear statement of this in the official docs. It would be good to fix that.

Motivated by the thread https://discuss.python.org/t/make-float-floordiv-and-rfloordiv-return-an-int/24959, where it's been asserted that this behaviour is an 'implementation detail'.

### Linked PRs
* gh-102824
* gh-109092
* gh-109093

**Comment by rhettinger** [comment]
+1 

Also note that `Decimal(n) // Decimal(d)` returns a float.

The docstring in `numbers.py` should also be clarified:

```
    @abstractmethod
    def __floordiv__(self, other):
        """self // other: The floor() of self/other."""
        raise NotImplementedError
```

**Comment by skirpichev** [comment]
> Also note that Decimal(n) // Decimal(d) returns a float.

IOW, a Decimal.

**Comment by hugovk** [comment]
Fixed via https://github.com/python/cpython/pull/102824 and backports to 3.11, thanks!
