### ISSUE TITLE
Path.as_posix() does not convert backslashes to slashes

### ISSUE THREAD

**Issue by adrianschlatter** [python/cpython#102959]
# Bug report

According to its docstring, the purpose of Path.as_posix() is

```
Return the string representation of the path with forward (/)
slashes.
```

However, when I run

```
from pathlib import Path

s = '\\subdir\\file.txt'
p = Path(s)
p.as_posix()
```
I get

```
'\\subdir\\file.txt'
```

I expect

```
'/subdir/file.txt'
```

# Your environment

Python 3.10.10 (main, Mar 21 2023, 18:45:11) [GCC 11.2.0] on linux

running on Linux (Ubuntu) running virtualized (WSL2) on Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz   1.99 GHz

**Comment by eryksun** [comment]
On POSIX, backslash is a regular name character. For example, on Linux:

```pycon
>>> open('spam\\eggs', 'w').close()
>>> [e for e in os.scandir('.') if '\\' in e.name]
[<DirEntry 'spam\\eggs'>]
```

If you start with a POSIX path, `as_posix()` won't replace backlashes with forward slashes. On the other hand, it will if you start with a Windows path. For example:

```pycon
>>> from pathlib import PureWindowsPath
>>> p = PureWindowsPath('\\subdir\\file.txt')
>>> print(p.as_posix())
/subdir/file.txt
```

**Comment by adrianschlatter** [comment]
I understand. So this is intended behaviour.
