### ISSUE TITLE
Improve test coverage on pdb

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#102980]
# Feature or enhancement

Add more tests on pdb module

# Pitch

The coverage on pdb module is poor - some of the commands are not tested at all. There are at least some low hanging fruits that we can do.

### Linked PRs
* gh-102981
* gh-103016
* gh-103017
* gh-111194

**Comment by arhadthedev** [comment]
Should this issue be closed as done?

**Comment by gaogaotiantian** [comment]
Please don't close it yet. There are still some missing pieces and I need to wait for #102895 to do test on `interact`. I'll do more PRs related to this issue.

**Comment by ambv** [comment]
note: #102895 is now complete.

**Comment by gaogaotiantian** [comment]
Yes, all the intended tests were added already. I'll close this one.
