### ISSUE TITLE
Update Windows and MacOS installers to SQLite 3.41.2+.

### ISSUE THREAD

**Issue by felixxm** [python/cpython#102997]
Updating Windows and MacOS installers to SQLite 3.41.2, see [release notes](https://sqlite.org/releaselog/3_41_2.html).

There is a small [bugfix](https://www.sqlite.org/src/info/76e683c5f25fe047) in the `3.41` branch, so we can wait 2-3 weeks for SQLite 3.41.3. 

### Linked PRs
* gh-102998
* gh-102999
* gh-104080
* gh-104085

**Comment by erlend-aasland** [comment]
Thanks for the heads-up, Mariusz.

> There is a small [bugfix](https://www.sqlite.org/src/info/76e683c5f25fe047) in the 3.41 branch, so we can wait 2-3 weeks for SQLite 3.41.3.

+1

I'll make sure the sources repo is ready.

**Comment by lazka** [comment]
just fyi, https://lore.kernel.org/distributions/87wn35bod7.fsf@gentoo.org/T/#u some performance regressions that will be fixed with 3.42

**Comment by felixxm** [comment]
It seems that they finally decided to release SQLite 3.42.0 and abandon 3.41.3.

I'd suggest updating the installers to SQLite 3.42.0+ in Python 3.12 as it's still in alpha stage. @erlend-aasland What do you think? (I can prepare PR.)

**Comment by erlend-aasland** [comment]
> I'd suggest updating the installers to [SQLite 3.42.0](https://sqlite.org/releaselog/3_42_0.html)+ in Python 3.12 as it's still in alpha stage. @erlend-aasland What do you think? (I can prepare PR.)

Sounds good. We'll have plenty of time in the beta period to apply the upcoming 3.42.x patch releases.
