### ISSUE TITLE
Add `mmap` support under WASI

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#102974]
Apparently the latest WASI SDK adds `mmap` support, so it may be possible to get (most of) the `mmap` module working under WASI.

**Comment by brettcannon** [comment]
https://github.com/WebAssembly/wasi-libc/blob/5d8a1409aa85acf8dbb197e13d33489ad1eac656/libc-top-half/musl/include/sys/mman.h

**Comment by assambar** [comment]
I would double-check before doing that. The wasi-libc emulation is just enough to pass the compilation and covers only a few very basic use cases.
Using that could lead to a lot of unexpected and hard to trace bugs in code that relies on mman for its full capabilities.
Take a look at the implementation - https://github.com/WebAssembly/wasi-libc/blob/659ff414560721b1660a19685110e484a081c3d4/libc-bottom-half/mman/mman.c

As an example, we had some issues with the mmap emulation while porting PHP. Took me a couple of weeks till I figured out what was the actual issue, as stuff sometimes worked and sometimes did not. A write-up of some pain points can be found here - https://github.com/vmware-labs/webassembly-language-runtimes/blob/1ae05b952385546745c326b3c6365ca9c3894597/php/php-8.1.11/README.md#mmap-support

**Comment by brettcannon** [comment]
@assambar thanks for the warning! That's enough for me to close this and not worry about it.
