### ISSUE TITLE
Add a dev container to the repository

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#102973]
Originally discussed at https://discuss.python.org/t/add-support-for-devcontainers-to-facilitate-github-codespaces-usage/21330 , the idea is to get to the point where we can have [GitHub Codespaces prebuilds](https://docs.github.com/en/codespaces/prebuilding-your-codespaces/about-github-codespaces-prebuilds). This would get people a running container in under a minute with CPython and the docs already fully built. The idea is it saves everyone time by having a preconfigured setup, making things like getting started as sprints extremely easy. It can also help in situations like with WASI where the toolchain can come pre-installed to make getting started much easier.

FYI everyone on GitHub gets 120 CPU-hours of free Codespaces, so that means a 2-core CPU instance is worth 60 hours of use. And with prebuilds, at least the initial building of `python` and the docs comes for "free" for users.

Adding this setup has already been approved by the SC.

### Linked PRs
* gh-102975
* gh-103283

**Comment by hauntsaninja** [comment]
Thanks, looks like this was merged
