### ISSUE TITLE
Regression in zipfile, read1(-1) after seek() returns empty byte string

### ISSUE THREAD

**Issue by hrnciar** [python/cpython#102956]
# Bug report

When debugging a test failure in https://pypi.org/project/fs/ I found a regression in `zipfile`, read1(-1) after seek() returns empty byte string instead of substring. I've bisected it into this commit 330f1d58282517bdf1f19577ab9317fa9810bf95. 

## Reproducer:
~~~~
import zipfile

# First, create the zip:
#   echo 'Hello, World' > hello.txt
#   zip hello.zip hello.txt

with zipfile.ZipFile('hello.zip') as myzip:
    with myzip.open('hello.txt') as myfile:
        print(myfile.read(5))
        print(myfile.seek(2, 1))
        print(myfile.read1(-1))
~~~~

## Expected output (3.11.2):
~~~~
❯ python3.11 reproduce.py
b'Hello'
7
b'World\n'
~~~~

## Actual output (3.12.0a6):
~~~~
❯ python3.12 reproduce.py
b'Hello'
7
b''
~~~~

# Your environment

- CPython versions tested on: main
- Operating system and architecture: Fedora 37, x86_64

### Linked PRs
* gh-103565
* gh-111289

**Comment by arhadthedev** [comment]
@serhiy-storchaka, @Yhg1s, @gpshead (as zipfile experts)

**Comment by mgorny** [comment]
Ping. This is still breaking `fs`, and there's a patch waiting for review since April.

**Comment by gpshead** [comment]
Thanks! 3.12.1 should include the fix.
