### ISSUE TITLE
`match` / `case` operation: `np.bool_` vs `bool`

### ISSUE THREAD

**Issue by ego-thales** [python/cpython#102905]
Hello,

Sorry, I'm not sure whether this is an intended behaviour or a bug -- couldn't find definitive answer [here](https://docs.python.org/3/whatsnew/3.10.html).
The following snippet doesn't match as I expected:
```pycon
>>> b = np.True_
>>> b == True
True
>>> match b:
...  case True:
...   print("Ha!")
...  case _:
...   print("Oh...")
... 
Oh...
```

_Tested on_ `Python 3.10.6`.

Thanks for your time.
Cheers!

**Comment by JosephSBoyle** [comment]
```python3
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> x = np.bool_(1)
>>> x
True
>>> type(x)
<class 'numpy.bool_'>
>>> isinstance(x, bool)
False
>>>
```

Could be related to the fact that `np.bool_` doesn't seem to be a subtype of `bool`.

**Comment by sobolevn** [comment]
Quoting PEP: https://peps.python.org/pep-0636/#matching-specific-values

> Literal values are compared with the == operator except for the constants True, False and None which are compared with the is operator.

So, it works as it should :)

**Comment by ego-thales** [comment]
Thanks for the reference, I couldn't find it!
Do you have any info on why these constant should behave differently? It seems a bit strange without furhter insight.

🙏

**Comment by sobolevn** [comment]
Because they are three special singletons :) 

For example, `1 == 1.0 == True`
Probably, matching `True` case with `1` value is not something users want.

**Comment by ego-thales** [comment]
Ok thanks for your answer, I guess it makes sense.

I was wondering then what would the most natural way of matching a numpy boolean array be. I think the answer is to view the array with `dtype=object`, since
```pycon
>>> np.True_.astype(object) is True
True
```

Cheers!
