### ISSUE TITLE
Improve test cases for type substitution of a list of types after initial ParamSpec substitution

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#103054]
After merging https://github.com/python/cpython/pull/102808 I realized that I've missed several important cases.

Right now substitution algorithm has these lines: https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/typing.py#L1477-L1488

It is tested. But, it is never tested for the nested arguments:

https://github.com/python/cpython/blob/2cdc5189a6bc3157fddd814662bde99ecfd77529/Lib/typing.py#L1500-L1511

I think that `Callable` is complex and important enought to be covered with as many cases as possible. Furthermore, `Callable` can be nested deeply in real types and we need to be sure that this use-case works as intended.

I will send a PR with more tests :)

Related https://github.com/python/cpython/issues/88965

### Linked PRs
* gh-103055
* gh-103105

**Comment by AlexWaygood** [comment]
Thanks Nikita!
