### ISSUE TITLE
pdb's breakpoint should check if condition is a valid expression

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#103068]
This could be either a bug report or a feature request. `pdb` has conditional breakpoint feature where you can set a condition for the breakpoint to be effective. You can also use `condition` command to change it.

The problem is - it never checks whether that condition is a valid expression. The expression will be evaluated when the breakpoint is hit and if there's a syntax error, it'll just consider it `True`. This is not an ideal behavior. We can warn the users if their input `condition` is not even a valid expression because under no circumstances that's the expected input. Also it would not be a valid command.

### Linked PRs
* gh-103069

**Comment by ambv** [comment]
Since this is an equivalent of GH-103023, let's treat this as a new feature, too.

**Comment by ambv** [comment]
Landed for 3.12, thanks! ✨ 🍰 ✨
