### ISSUE TITLE
[ctypes documentation issues] varadic typo and doctest directive mistake

### ISSUE THREAD

**Issue by peterjpxie** [python/cpython#103025]
# Documentation

Two issues on https://docs.python.org/3/library/ctypes.html

Issue 1: typo "Calling varadic functions" => should be "variadic"

Issue 2: 
![image](https://user-images.githubusercontent.com/12903395/227703681-4876b12e-d322-4cfa-9ae8-3608c3eed1ad.png)

Issue 2 has been discussed [here](https://discuss.python.org/t/ctypes-page-doctest-typo/25138) 

### Linked PRs
* gh-103026
* gh-103029
* gh-103030

**Comment by AlexWaygood** [comment]
The `.. doctest` issue doesn't exist on the 3.11 and 3.10 branches, so for the backports we're just fixing the typo.

**Comment by AlexWaygood** [comment]
Thanks @peterjpxie!
