### ISSUE TITLE
Upload .nupkg file or .zip equivalent to python.org 

### ISSUE THREAD

**Issue by solvingj** [python/cpython#103011]
# Feature or enhancement

Please add another package/publish step to upload the `.nupkg` files to python.org alongside the other precompiled package options. 

Alternatively, and preferably....

Just zip up the `tools` subdirectory of the `nuget` package separately and upload that to `python.org` named as "portable install".

# Pitch

The current build automation is just a few inches shy of addressing a much broader and more general case of CI. With one of the "relatively trivial" modifications suggested, the Python could simplify any primitive CI flows which don't use nuget package management. 

In either recommended case, nothing has to be re-built, no additional tests are needed, because it's the exact same functionality as the `nupkg`.  Just add a second capture/upload step during the stages which builds the `nupkg`, just with a different name and destination.   The hardest part is the organizational stuff: updating the website and docs to describe this new thing, etc. 

But Why?  
The `.nupkg` package is a very awesome and practical acknowledgement of the world of CI use-cases. Thanks for this. However, it's coupled to the concept/stack of nuget package management, and many CI teams in enterprise organizations can't or haven't adopted that strategy. 

Primitive CI flows (as found in many enterprise organizations) want all of their pre-compiled binary tools to follow the simple template: 
- curl to download
- zip or tar to extract
- run...

Currently, we can "hack" the `.nupkg` package to get close to this, but with a bunch of unnecessary nuance:
1. It's a `.nupkg`, so we have to rename it to .zip to unzip it with either Powershell or bsdtar
2. The files we want are in a `tools` subdirectory
3. It's hosted on nuget.org which has drawbacks:
    - Security folks don't like it, it's less official and more "scary" than python.org 
    - Scripts have to deal with different URLs, naming conventions, she verification, etc, compared to python.org

**Comment by arhadthedev** [comment]
@Yhg1s (as a release manager)

**Comment by Yhg1s** [comment]
More of a question for @zooba at this point.
