### ISSUE TITLE
If the working directory and the venv are on different disks, venv doesn't work in bash on Windows

### ISSUE THREAD

**Issue by Zabolekar** [python/cpython#103088]
**Environment**

- OS: Windows 10
- Architecture: x86_64
- Shell: bash 4.4.23, part of the git 2.37.0 install
- Python version: 3.11.1
- Output of `path/to/python -m pip list`:

```console
Package    Version
---------- -------
pip        23.0.1
setuptools 65.5.0
```

**Issue**

When I create a venv on D: and use it from C:, executables like pip or python can't be found:

```console
$ pwd
/d
$ /path/to/python -m venv myenv
$ . myenv/Scripts/activate
$ pip --version
pip 22.3.1 from D:\myenv\Lib\site-packages\pip (python 3.11)
$ cd /c
$ pip --version
bash: \myenv/Scripts/pip: No such file or directory
```

### Linked PRs
* gh-103325
* gh-103470
* gh-103500
* gh-103591

**Comment by eryksun** [comment]
A POSIX shell delimits `PATH` with ":". Thus "D:\\myenv" represents two separate pathnames "D" and "\\myenv". If a path begins with "\\", MSYS apparently resolves it against the drive path of the current working directory (e.g. "/c" or "/d").

You can work around this issue by editing "{env_dir}/Scripts/activate" to replace the value of `VIRTUAL_ENV` with the equivalent MSYS path (e.g. "D:\\myenv" -> "/d/myenv"). 

Maybe the "activate" script could detect MSYS or Cygwin and automatically translate the value of `VIRTUAL_ENV` via `export VIRTUAL_ENV=$(cygpath -u "$VIRTUAL_ENV")`.

**Comment by Zabolekar** [comment]
Thanks for the answer. My current workaround was to move venvs and code to the same disk.

Now that you mention Cygwin I've tested the script with Cygwin's version of bash as well. The script fails because it contains \r. After applying dos2unix, it works but has the same issue as MSYS bash.

Let's say I want to fix the script for everyone and not just for me. What would be the process, and what bash variants other than MSYS and Cygwin should I be aware of?

**Comment by eryksun** [comment]
> Let's say I want to fix the script for everyone and not just for me. What would be the process, and what bash variants other than MSYS and Cygwin should I be aware of?

Cygwin and MSYS2 are the common POSIX environments on Windows, other than WSL. Create a pull request that modifies the template script "Lib/venv/scripts/common/activate". 

https://github.com/python/cpython/blob/e375bff03736f809fbc234010c087ef9d7e0d384/Lib/venv/scripts/common/activate#L41-L42

Apparently MSYS and Cygwin can be [detected on bash](https://stackoverflow.com/a/8597411) using the `OSTYPE` environment variable. The following change seems to do the job. I haven't checked whether it causes a problem for an environment that's created by the MSYS2 or Cygwin versions of Python, but I don't think it should cause a problem. `cygpath -u` should only modify a Windows path such as "D:\\myenv", not a POSIX path such as "/d/myenv" or "/cygdrive/d/myenv".

```bash
if [ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ] ; then
    export VIRTUAL_ENV=$(cygpath -u "__VENV_DIR__")
else
    export VIRTUAL_ENV="__VENV_DIR__"
fi
```

The venv module replaces the `__VENV_DIR__` template parameter with the path of the created virtual environment.

**Comment by Zabolekar** [comment]
Thanks for your help. I didn't even know MSYS had cygpath, too. I've tested creating venvs in cmd and in MSYS2, then activating them in cmd, MSYS2, and cygwin, and looking at `pip --version` and `python --version`. Everything works as expected. [Here](https://github.com/python/cpython/pull/103325) is a pull request.

Two things I've noticed while doing this, not sure whether those are bugs or not:
- the script has CR LF, so Cygwin only understands it after I run dos2unix on it
- https://devguide.python.org/ advises to build on Windows with `-d` by default (set the configuration to Debug). So the resulting venvs don't contain python.exe, only python_d.exe, and calling pip directly doesn't work ("Fatal error in launcher"). If Python has been built without -d, everything works as expected.

**Comment by zooba** [comment]
> * the script has CR LF, so Cygwin only understands it after I run dos2unix on it

It may depend on your Git settings, if you've cloned and built from source. Or maybe this file gets modified when venv copies it? @vsajip any thoughts?

> * resulting venvs don't contain python.exe, only python_d.exe, and calling pip directly doesn't work

Guessing this is a script launcher limitation, or maybe they aren't being generated properly in this scenario. In any case, it's external - I believe pip still gets their launchers from distlib?

**Comment by zooba** [comment]
If that's added to `.gitattributes` then it should work fine for the installer. We don't do anything to that file.

I'd be more concerned about venv creation reading, modifying and writing the file with different line endings. If it doesn't do that, then modifying the attributes should be enough.

**Comment by vsajip** [comment]
> Or maybe this file gets modified when venv copies it?

The `activate` script in my repo on Linux has LF terminators, and the [copying code](https://github.com/python/cpython/blob/8f54302ab49a07e857843f1a551db5ddb536ce56/Lib/venv/__init__.py#L426) reads and writes the files as binary (there are some variable substitutions, but none of those should introduce CRLF line endings).

**Comment by zooba** [comment]
I've merged both fixes - any thoughts on backports? I think 3.11 is going to last long enough to be worth it, and while it won't help anyone who doesn't recreate their venvs, we'll have plenty of new users in the future.

**Comment by zooba** [comment]
Well, buildbot failures mean we won't be backporting soon. Looks like:
* some buildbots ignore `.gitattributes` (or maybe just need a clean checkout?)
* we need to change the second parameter to `assertFalse` to use `line.decode()` - it doesn't like bytes

The second issue only appears because the test is failing, so worth fixing that one first.

**Comment by db3l** [comment]
I just checked, and the `activate` script has CRLF line endings on my buildbot, so not what the `.gitattributes` file in the same tree specifies.  I certainly don't have anything on the buildbot to ignore `.gitattributes` at least not to my knowledge.  Oh, and yes, it's that way in all the existing checkouts for other branches as well.

A quick test with a manual fresh checkout does end up with LF, so the buildbot tree is perhaps just git not adjusting an already checked out file.  Once the parameter fix is addressed, I could manually flush the buildbot's 3.x tree to verify with a test run if it would help.

**Comment by Zabolekar** [comment]
> we need to change the second parameter to assertFalse to use line.decode() - it doesn't like bytes

I've checked again how it looks decoded vs. undecoded, found neither helpful and decided to remove the line itself from the error message and use the line number instead. See PR.

**Comment by Zabolekar** [comment]
This might be why the tests fail: https://github.com/python/cpython/pull/103500#issuecomment-1506700154

**Comment by zooba** [comment]
> A quick test with a manual fresh checkout does end up with LF, so the buildbot tree is perhaps just git not adjusting an already checked out file. Once the parameter fix is addressed, I could manually flush the buildbot's 3.x tree to verify with a test run if it would help.

You can flush it anyway, the test fix looks good, and the test will pass once the checkout is clean. Thanks @db3l!

**Comment by zooba** [comment]
Hopefully this approach to cleaning up all the buildbots will work. Would be nice to have something a bit narrower/faster, but this will do.

**Comment by db3l** [comment]
Isn't that just using the PR branch directory on the buildbots and not any of the actual branch trees?

Sort of a kludge, but perhaps actually touching the `activate` file in some innocuous way to ensure it will have to be updated simultaneous with or subsequent to the `.gitattributes` change?

Or, any thought to just not going down this road, and expecting Cygwin users to use the igncr shell option?  It's been a while since my Cygwin days but having to deal with CRLF scripts wasn't that uncommon.  Separately, as it is, this change only fixes use under Cygwin with sh/bash (e.g., the csh script is still CRLF).

**Comment by db3l** [comment]
I just happened to notice the `activate.csh` and `activate.fish` versions in the posix folder, which are also CRLF on Windows.  It seemed plausible that changes for `activate` would hold for those too.  Then again, the venn diagram overlap of Cygwin users using those shells with Python testing may be null...

**Comment by Zabolekar** [comment]
> Cygwin (specifically Git Bash)

But git bash is not Cygwin.

**Comment by GalaxySnail** [comment]
> > Cygwin (specifically Git Bash)
> 
> But git bash is not Cygwin.

Git-bash is based on msys2 [1], which is based on Cygwin [2].

[1] https://github.com/git-for-windows/git/wiki#about
[2] https://github.com/msys2/msys2-runtime
