### ISSUE TITLE
Outdated `dataclass.make_dataclass` docstring

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#103027]
This docstring line in `make_dataclass` is outdated:

https://github.com/python/cpython/blob/1fd603fad20187496619930e5b74aa7690425926/Lib/dataclasses.py#L1424-L1425

There are new parameters: `kw_only`, `slots`, `weakref_slot` that are not mentioned.
I will send a PR.

### Linked PRs
* gh-103028

**Comment by ericvsmith** [comment]
Thanks!
