### ISSUE TITLE
gc.freeze documentation is unclear

### ISSUE THREAD

**Issue by raylu** [python/cpython#103059]
# Documentation

The [current advice](https://docs.python.org/3/library/gc#gc.freeze) seems to mean you should `gc.disable()` and `gc.freeze()` right before `os.fork()`, which doesn't do anything.

Łukasz explained the advice in https://bugs.python.org/issue31558#msg302780.

I'm proposing a fix in PR #103058.

### Linked PRs
* gh-103058
* gh-103416

**Comment by arhadthedev** [comment]
@pitrou, @pablogsal (as gc experts)
