### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by Rigavinil201** [python/cpython#103087]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by terryjreedy** [comment]
If this is intentional spam, go away.  If this is an accident, click `...` and fill in the info needed and we will re-triage.

**Comment by CAM-Gerlach** [comment]
@python/organization-owners please block as presumed spam, it fits the pattern of previous spammers and the user has blocked others viewing their history which makes it harder to confirm they are a spammer, which I've never seen any non-spam user do (let alone user new to GitHub who might plausibly do this by accident). I've also reported it to GitHub so they can investigate. Thanks!

**Comment by ambv** [comment]
Done.
