### ISSUE TITLE
Quotation Markers in Formatted String Variables

### ISSUE THREAD

**Issue by sambo22** [python/cpython#103018]
# Feature or enhancement

I have the following:
```
print(f"bla bla this {dictionary["aKey"]} value means something")
```
The double-quotes surrounding the "aKey" are associated with the f-string's double quotes, requiring me to use single quotes around my 'aKey'.

# Pitch
The "aKey" quotations pattern, and any other quote(s), could be independent from the set(s) used in the f-string using the {...} for context.

**Comment by ericvsmith** [comment]
This will be fixed when PEP-701 is fully implemented, which is happening now and should be in Python 3.12.
