### ISSUE TITLE
tempfile.TemporaryFile() emits a ResourceWarning that does not trace back to user code

### ISSUE THREAD

**Issue by mmerickel** [python/cpython#103070]
# Feature or enhancement

When using `tempfile.TemporaryFile` a `ResourceWarning` should be emitted with the source tracing back to user code. Instead it currently traces back to the `_io.open` invocation inside the `tempfile` module and is useless for tracking down the code that created the tempfile.

# Pitch

Take the following `foo.py`:

```python
import tempfile


def main():
    fp = tempfile.TemporaryFile()


if __name__ == '__main__':
    main()
```

I would expect the `ResourceWarning` to point to the line `fp = tempfile.TemporaryFile()`. Instead I see the following:

```
❯ PYTHONTRACEMALLOC=1 PYTHONWARNINGS=default python3 -m foo
/Users/michael/work/foo.py:9: ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  main()
Object allocated at (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/tempfile.py", lineno 657
    file = _io.open(dir, mode, buffering=buffering,
```

Note that it's pointing at the tempfile module itself which is worthless other than to tell me it's a tempfile that's causing the issue - however for me it's in library code and I have no idea which library!

Please modify `tempfile` to properly track the source and emit a better warning.

**Comment by tomasr8** [comment]
The  [documentation](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONTRACEMALLOC) says that  you can pass a number to `PYTHONTRACEMALLOC` which is the maximum number of frames it stores. Using `PYTHONTRACEMALLOC=1` stores just 1 frame.

With `PYTHONTRACEMALLOC=3` (or higher), you should see the full trace:
```python
foo.py:9: ResourceWarning: unclosed file <_io.BufferedRandom name=3>
  main()
Object allocated at (most recent call last):
  File "foo.py", lineno 9
    main()
  File "foo.py", lineno 5
    fp = tempfile.TemporaryFile()
  File "/home/tomas/.pyenv/versions/3.11.2/lib/python3.11/tempfile.py", lineno 622
    file = _io.open(dir, mode, buffering=buffering,

```

**Comment by mmerickel** [comment]
Confirmed this is working for me to track down those leaks - I had no idea that this was possible with the tracemalloc config. I'm going to close this issue. Thank you @tomasr8!
