### ISSUE TITLE
Add SyntaxError check for pdb's command `display`

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#103023]
# Feature or enhancement

Check `SyntaxError` when doing `display` in `pdb`.

# Pitch

`display` adds an expression to watch list. However, if there's a syntax error, then the command is meaningless. Currently, `display` still adds this invalid expression into the watch list, which does not make sense in almost all cases. Adding a syntax error check could prevent the users from accidentally adding wrong expressions then having to remove it with `undisplay`.

### Linked PRs
* gh-103024

**Comment by ambv** [comment]
That's a reasonable improvement, thanks for taking the time to report and implement this!
