### ISSUE TITLE
[`dataclasses`] Asymmetric handling of field defaults

### ISSUE THREAD

**Issue by ASEM000** [python/cpython#103080]
Currently, default and default factory are handled differently if not being initialized by user-defined init

```python

import dataclasses as dc 

@dc.dataclass
class Test:
    a:int = dc.field(default=1)
    def __init__(self) -> None:
        pass

Test() # Test(a=1) # -> a is class variable

```

However, this code will through an error.

```python

@dc.dataclass
class Test:
    a:int = dc.field(default_factory=lambda: 1)
    def __init__(self) -> None:
        pass

Test() # AttributeError

```

**Comment by ericvsmith** [comment]
It's the user's responsibility to initialize self.a, since it's used in the repr. In the first case (as you say), Test.a is being used. But witha  default_factory, there's no reasonable value to initialize Test.a with.

**Comment by ericvsmith** [comment]
We could probably document this better. I’m open to suggestions.
