### ISSUE TITLE
Add a C API to assign a new version to a PyTypeObject

### ISSUE THREAD

**Issue by swtaarrs** [python/cpython#103091]
# Feature or enhancement

I would like to add an API function like this:
```
/* Attempt to assign a version tag to the given type.
 *
 * Returns 1 if the type already had a valid version tag or a new one was
 * assigned, or 0 if a new tag could not be assigned.
 */
PyAPI_FUNC(int) _PyType_AssignVersionTag(PyTypeObject* type);
```

It would be a thin wrapper around the existing [`assign_version_tag`](https://github.com/python/cpython/blob/main/Objects/typeobject.c#L568-L599) function, and is modeled after a similar function we added to Cinder as part of https://github.com/facebookincubator/cinder/commit/43c4e2dfe0e4a967251a72468adfc6602011dbda.

# Pitch

Cinder (and possibly other JITs or optimizing interpreters) would benefit from being able to ensure that type has a valid version tag without having to call `_PyType_Lookup()` just for the version-assigning side-effect. We rely on notifications from `PyType_Modified()` to invalidate code in our JIT when types change, and this only works when the types in question have valid version tags.

# Previous discussion

There's no written discussion I'm aware of, but @carljm and @markshannon have discussed this offline.

### Linked PRs
* gh-103095

**Comment by encukou** [comment]
AFAIK, version tags are an implementation detail. For anything except JITs/optimizers, `PyType_Modified()` should be enough API.
IMO it would make sense to put this function in the [unstable API](https://peps.python.org/pep-0689/#specification). Name the function `PyUnstable_Type_AssignVersionTag` to do that.

**Comment by carljm** [comment]
I suspect it would also make more sense for the declaration to live in `Include/cpython/object.h` rather than `Include/object.h`, though I guess this isn't strictly required?

**Comment by swtaarrs** [comment]
https://github.com/python/cpython/pull/103095 is merged. Thanks @encukou and @carljm!

**Comment by brandtbucher** [comment]
I was just bit by this API's somewhat odd return value. Typically we return 0 on success and -1 on failure, but this returns 1 on success and 0 on failure.

Perhaps it should be changed?

**Comment by carljm** [comment]
I'm glad you're finding uses for this API :)

The PR to expose this function outside `typeobject.c` just passed through the existing return value convention from the pre-existing static`assign_version_tag` function, which has been there for a long time; I don't think changing it was ever considered.

I'm not sure how consistent the convention is; e.g. the compiler always returns 0 on failure and 1 on success. Also, `-1` often signifies "exception is set," but this API never sets an exception, it's just indicating whether a version tag was successfully set.

No strong feelings here.

**Comment by erlend-aasland** [comment]
> Also, -1 often signifies "exception is set," but this API never sets an exception, it's just indicating whether a version tag was successfully set.

What if we need to change the implementation in the future (because of runtime changes or whatever) and we end up having to use an internal API that can set an exception? If we design this API to always succeed, we have two options: swallow the exception before returning, or add a new API that can return with an exception set. See also the issue about infallible APIs in the C API workgroup repo.

**Comment by encukou** [comment]
There's some discussion general guidelines starting over at https://github.com/python/cpython/issues/105201#issuecomment-1578342058

IMO, 0 and 1 is consistent with the direction of that discussion:

* -1 would means error, with an exception set
* 0 means "lesser result" (like "no" or "missing value")
* 1 means "greater result" (like "yes" or "valid value")

> What if we need to change the implementation in the future (because of runtime changes or whatever) and we end up having to use an internal API that can set an exception? If we design this API to always succeed, we have two options: swallow the exception before returning, or add a new API that can return with an exception set. See also the issue about infallible APIs in the C API workgroup repo.

That's a valid concern -- adding an error case to an existing function, while trying to keep API compatibility, is very messy.
On the one hand this is unstable API, where we can just remove the function & replace it with a new one.

On the other hand, it's not that hard to do: *put a note in the docs* that it "returns -1 with an exception set" on error, and require that callers do error checking -- even though the exception currently never happens.

**Comment by carljm** [comment]
This makes sense in general, but I wonder if there is still room, particularly for an explicitly unstable API, for deeming the likelihood that an API will ever need to raise an exception so low that the practical cost-benefit analysis does not favor making every caller add an extra case for handling something that is currently impossible and probably will never happen in the future, either. Of course anything is possible, but for an unstable API in the unlikely scenario we have the option of just replacing the API.

Assigning a version tag to a type is a low-level internal operation (the target audience for its exposure is really only implementers of third-party runtime optimizers / JITs), and a relatively simple one, and I think we would go to some lengths to ensure that it remains simple and doesn't set exceptions in the future.

**Comment by encukou** [comment]
> I wonder if there is still room

Yup, it's totally fine for unstable API, where you can just yank the function. But it should be an informed decision.

**Comment by markshannon** [comment]
This should never set an exception.

Since it can fail (returning 0) and failure doesn't indicate an error, we can just avoid code paths that can raise.
