### ISSUE TITLE
When PEP: 505 get implemented? Or should I open a new Proposal? I'm not sure if my thinking is original.

### ISSUE THREAD

**Issue by yingshaoxo** [python/cpython#103128]
It seems like nowadays, typescript, flutter, kotlin already supports `?` and `??` operator very well.

___

By using `?` operator:
```
a_class = None
a_class?.function()

> this function won't get called since "a_class_instance == None"
```

___

By using `??` operator:
```
response = {}
response.a_variable = None

new_variable = response.a_variable?? True

> new_variable would be equal to True since "response.a_variable == None"
```

___

https://peps.python.org/pep-0505/#boolean-aware-operators

**Comment by hugovk** [comment]
Yes, instructions are in the developer's guide: https://devguide.python.org/

**Comment by terryjreedy** [comment]
On a 10+ year old Windows machine, rebuilding CPython takes maybe 2 min.
