### ISSUE TITLE
using @typechecked on a @property causes a weak ref error on the property object

### ISSUE THREAD

**Issue by DanZee** [python/cpython#103129]
# Bug report

The code below fails at the print statement with a "cannot create weak reference to 'property' object" error.

```
from typeguard import typechecked

@typechecked
class A:
  @property
  def p(self) -> int:
    return 1

a = A()
print(a.p)
```

```
Error details:
Exception has occurred: TypeError
cannot create weak reference to 'property' object
  File "C:\Code\ExploreSims\scratch.py", line 9, in p
    def p(self) -> int:
  File "C:\Code\ExploreSims\scratch.py", line 13, in <module>
    print(a.p)
          ^^^
TypeError: cannot create weak reference to 'property' object
```

# Your environment

- Python 3.11.2

**Comment by sobolevn** [comment]
Why do you think that this is a CPython's bug and not `typeguard`'s bug?
Can you reproduce this problem without any dependencies and show us what do you expect to happen?

Thanks!

**Comment by DanZee** [comment]
You're 100% correct. It already has been filed in the typeguard project.
