### ISSUE TITLE
Improve precision of floating-point operations

### ISSUE THREAD

**Issue by haja-fgabriel** [python/cpython#103148]
# Bug report

A simple addition, like

```python
>>> x = 19961011.8
>>> y = -19538908.2
>>> x + y
422103.6000000015
```

will return an imprecise answer. 
The correct answer of the addition is `422,103.6`

Tested on

CPython 3.8.10 (on both Windows 10 amd64 and Ubuntu MATE 20.04 amd64)
CPython 3.12.0a5 (Windows 10 amd64)
CPython 3.9.5 (on Ubuntu 21.04 amd64)

**Comment by zware** [comment]
Please see https://docs.python.org/3/tutorial/floatingpoint.html, this is a universal limitation of binary floating point operations.  If you need higher base-10 precision, take a look at the [decimal](https://docs.python.org/3/library/decimal.html) module, but note that this is the same phenomenon as `2/3 != 0.666666667`, no matter how many additional `6`s you include there.

**Comment by haja-fgabriel** [comment]
I'm sorry, it's my fault. I have later tested the same behavior on other languages. Turns out to be an issue of 64-bit floats actually and not of CPython 😁
Thank you for the suggestion wth the decimal module! I should read the documentation better 😂
