### ISSUE TITLE
Fatal Python error: init_import_site: Failed to import the site module Python runtime state: initialized

### ISSUE THREAD

**Issue by sonyakun** [python/cpython#103161]
# Bug report
When executing the command "python", the following error occurs and nothing can be executed
(Commands such as pip also generate the same error.)
```shell
Fatal Python error: init_import_site: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site.py", line 617, in <module>
    main()
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site.py", line 604, in main
    known_paths = addsitepackages(known_paths)
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site.py", line 387, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site.py", line 226, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "C:\Users\hm74c\AppData\Local\Programs\Python\Python310\lib\site.py", line 179, in addpackage
    for n, line in enumerate(f):
UnicodeDecodeError: 'cp932' codec can't decode byte 0x88 in position 41: illegal multibyte sequence
```
(Reinstallation is considered as a last resort due to the large number of installed libraries and the time it takes to check them.)
## reproduction method
Probably very difficult to reproduce.

# Your environment

- CPython Version:(Python version is) 3.10.8
- Operating system and architecture:Windows11 x64 (Language is Japanese.)

**Comment by arhadthedev** [comment]
@corona10 (as the one who worked recently with encodings)

**Comment by sunmy2019** [comment]
Looks like some of your .pth files within the site-packages directory have the wrong encodings.

Try to do the following things, invoke python with `-v` verbose mode:
`python -v`

and focus on the (last) lines that look like

```
Processing .pth file: ...
```

Looks like one of these `.pth` did not use your local encoding, but it should

**Comment by sonyakun** [comment]
Thank you very much. I can now run python by setting the encoding to ANSI (cp932).

**Comment by arhadthedev** [comment]
Closing as solved then.

**Comment by Jgg5252** [comment]
请问具体如何解决的呢

**Comment by HateHX** [comment]
> 请问具体如何解决的呢

可以看一下工作目录是不是设置错了，我就是往python目录写了个文件报错，删了就好

**Comment by litao09h** [comment]
用centos8就好了，估计是gcc版本太低的原因。
