### ISSUE TITLE
Enum states Boundaries incorrectly (In docs and source code)

### ISSUE THREAD

**Issue by 3SheepInATrenchcoat** [python/cpython#103115]
Regarding [howto/enum](https://docs.python.org/3/howto/enum.html#combining-members-of-flag).
The documentation incorrectly states that `The default for Flag is STRICT, the default for IntFlag is EJECT, and the default for _convert_ is KEEP (see ssl.Options for an example of when KEEP is needed).`. This is not the case, as `Flag` uses `CONFORM` and `IntFlag` uses `KEEP`.
This was changed by commits #96865 and #93250 respectively. 
Additionally to the Documentation, the docstring for `FlagBoundary` states this incorrectly as well.

**Comment by sunmy2019** [comment]
You can make a PR to change [`Doc/howto/enum.rst`](https://github.com/python/cpython/blob/main/Doc/howto/enum.rst) if it is convenient for you.

**Comment by ethanfurman** [comment]
Fixed in #103163 and #103227.
