### ISSUE TITLE
An error message in python with bs4

### ISSUE THREAD

**Issue by JokerDemonKing-bin** [python/cpython#103166]
```python
import bs4


html = '''
<title>小丑之家</title>
<div class="info" float="left">Welcome to Joker's home</div>
<div class='info' float='right'>
    <span>Good Good Study, Day Day Up</span>
    <a href='https://www.bilibili.com></a>
    <strong><!--无效--></strong>
</div>
'''

print("-------------获取内容-----------------")
print(soup.span.string)
print(soup.strong.string)
print(soup.strong.text)    # 用text无法获取注释信息

```

This is running in a general Python environment. The problem with the code above is that when `<a href='https://www.bilibili.com'></a>` is missing a single quote, running the Python code prompts an error that says `print(soup.strong.string) 'NoneType' object has no attribute 'string'`, but completing the single quote does not result in this error. There is something wrong with the error here, I hope it can be corrected.
![1](https://user-images.githubusercontent.com/126929742/229273741-1295379c-8add-46eb-b2b8-cb1f29df467c.PNG)
![2](https://user-images.githubusercontent.com/126929742/229273745-fe217fa8-3f27-484a-9fe2-3a9da5b7fa28.PNG)

**Comment by hugovk** [comment]
I can't tell because you've not shown where `soup` is set (I get `NameError: name 'soup' is not defined` with the above), so that could be the problem.

Anyway, this is the issue tracker for the Python language itself and your problem looks like an issue with your code. 

Consider posting instead on https://stackoverflow.com/ or https://discuss.python.org/c/users/7 and first follow the advice at https://stackoverflow.com/help/minimal-reproducible-example to create a runnable example.

**Comment by JokerDemonKing-bin** [comment]
![1](https://user-images.githubusercontent.com/126929742/229273443-b6a85fde-dbca-421f-8736-34bb90c45311.PNG)
![2](https://user-images.githubusercontent.com/126929742/229273449-ffcf1964-6864-4eba-b3b0-7882b9cfa730.PNG)

**Comment by JokerDemonKing-bin** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "python/cpython"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月1日(星期六) 下午3:19
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [python/cpython] An error message in python with bs4 (Issue #103166)





 
I can't tell because you've not shown where soup is set (I get NameError: name 'soup' is not defined with the above), so that could be the problem.
 
Anyway, this is the issue tracker for the Python language itself and your problem looks like an issue with your code.
 
Consider posting instead on https://stackoverflow.com/ or https://discuss.python.org/c/users/7 and first follow the advice at https://stackoverflow.com/help/minimal-reproducible-example to create a runnable example.
