### ISSUE TITLE
An inconsistent behaviours in ``__repr__`` functions for subclasses of built-in simple data structures (dict, set, list, tuple, str) 

### ISSUE THREAD

**Issue by gresm** [python/cpython#103117]
# Bug report

MRE:
```py
class D(dict):
  pass

class S(set):
  pass

class L(list):
  pass

class T(tuple):
  pass

class S_(str):
  pass

print(repr(dict({"a": 1})))
print(repr(D({"a": 1})))
print(repr(set([1, 2])))
print(repr(S([1, 2])))
print(repr(list([1, 2])))
print(repr(L([1, 2])))
print(repr(tuple([1, 2])))
print(repr(T([1, 2])))
print(repr(str([1, 2])))
print(repr(S_([1, 2])))
```

Output:
```py
{'a': 1}
{'a': 1}
{1, 2}
S({1, 2})
[1, 2]
[1, 2]
(1, 2)
(1, 2)
'[1, 2]'
'[1, 2]'
```

# Your environment

- CPython versions tested on: 3.10.6, 3.11.2

**Comment by sobolevn** [comment]
I guess that the main motivation for `set` to behave this way is:

```python
>>> repr(frozenset((1, 2)))
'frozenset({1, 2})'
```

**Comment by stevendaprano** [comment]
Unless there is documentation stating that the repr is supposed to differ from what you see, there is no bug here.

Good or bad, the behaviour you see goes back for decades.

**Comment by gresm** [comment]
What I meant here was rather that
```py
class MyDict(dict):
    pass

a = MyDict()
print(repr(a))
```
Should print:
```py
MyDict({})
```
Not the other way around. And indeed, naming it a "bug" is a stretch, but github is weird with label customization and doesn't allow me using a different one. Probably it is somewhere between a bug and an enhancement...

**Comment by stevendaprano** [comment]
Unless there is documentation stating that the repr of a subclass of dict must be 'MyDict({}', then the fact that it isn't is not a bug. The inconsistency between the reprs of dict and set subclasses is not a bug either, unless there is documentation that they must behave the same. Nothing in the Python language definition prohibits classes from having distinct reprs.

I personally agree with you that it would be better if all of the classes shown behaved like set, but they don't, and changing that behaviour is surely going to be prohibitive.

**Comment by gresm** [comment]
I reason that the area of breaking impact by the change would be close to zero, as it would change the behavior of an built-in object subclass (rare usage) for a default and overridable behavior of ``repr``, where the likelihood of unchanged behavior in the impactful code is even less likely. Even then, in what sort of situations would the code break after the change?

And the less important part about it not being a bug: from my understanding function ``repr()`` should return a string that copied and pasted would allowed creating same/similar object that was put inside the ``repr()`` function (with the exception of the string that is enclosed in <>, as it symbolizes the inability of creating such an object by instancing the class). So, I conclude that the current behavior of these types contradict with the principle/ideology behind the ``repr()`` function, so it somewhat fits in the ``bug`` category.

**Comment by terryjreedy** [comment]
You correctly paraphrased the second sentence of the [repr doc](https://docs.python.org/3/library/functions.html#repr).  The built-in class instances do have representations that evaluate to an instance equal to the instance, including for frozensets.  The third sentence says "A class can control what this function returns for its instances by defining a __repr__() method." If *your* subclass representations function 'incorrectly', the bug is in your code for omitting the needed `.__repr__`.  The doc is not intended to imply that python writes one for you.
