### ISSUE TITLE
Improve the documentation for `ignore_warnings`

### ISSUE THREAD

**Issue by CharlieZhao95** [python/cpython#103109]
# Documentation

Recently, I found that using `ignore_warnings(*, category)`, a simple decorator in `test.support.warning_helper`, is sometimes a concise way to suppress warnings in test cases. For example:

```python
# use `with` statement
def test_suppress_warning():
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=SyntaxWarning)
        # do something

# use decorator
@warning_helper.ignore_warnings(category=SyntaxWarning)
def test_suppress_warning():
    # do something
```

**What I want to improve:**

1. The [comment](https://github.com/python/cpython/blob/e375bff03736f809fbc234010c087ef9d7e0d384/Lib/test/support/warnings_helper.py#L47) of function `ignore_warnings` , it writes

> Decorator to suppress deprecation warnings

 But in fact this can become a more general warning suppression decorator, not just deprecation warnings, we can improve this comment. 

2. The document of [test.support.warnings_helper](https://docs.python.org/3.12/library/test.html?highlight=warnings_helper#module-test.support.warnings_helper), it is missing information about the function `ignore_warnings`.
3. Perhaps we can also add a default value to it, just like `ignore_warnings(*, category=Warning)`, so that the behavior of this decorator is consistent with `warnings.simplefilter`.

### Linked PRs
* gh-103110
* gh-103198
* gh-103199

**Comment by erlend-aasland** [comment]
Fixing the docstring and adding documentation seems enough for now. AFAIK, there is no need for adding a default value (consistency with `warnings.simplefilter` is not reason enough IMO). Marking this as closed.
