### ISSUE TITLE
Pypi source changing error

### ISSUE THREAD

**Issue by JasonMo1** [python/cpython#103189]
I've installed python from Microsoft Store. When I want to change my pypi source with command 'pip install -i https://mirrors.ustc.edu.cn/pypi/web/simple pip -U' and 'pip config set global.index-url https://mirrors.ustc.edu.cn/pypi/web/simple'. But I got an error:
![mmexport1680427938365](https://user-images.githubusercontent.com/111677135/229344813-bc0fb9c6-eda6-41a9-a606-4239636423b4.png)
![mmexport1680427961350](https://user-images.githubusercontent.com/111677135/229344814-39bbdbcd-8c1a-41a2-b40f-aad8a3c4ee52.png)
After reading the message, I realize that it because of 'WindowsApps'(Microsoft Store installation path) need to access as SYSTEM permission. Although I try to run this command as Administrator, it still doesn't work. I think we should move pip.ini into another place where can access with user permission.

**Comment by ericvsmith** [comment]
This looks like a pip issue. Please report it at https://github.com/pypa/pip/issues

Also, please don't post images, We can't copy and paste from them, and they're hostile to people who use screen readers.

I'm going to close this. If the pip issue decides this is a CPython bug, then we can re-open this.
