### ISSUE TITLE
Doc: |today| format does not honor language's time format

### ISSUE THREAD

**Issue by rffontenelle** [python/cpython#103122]
The Sphinx `|today|` variable in Python Docs is rendered in the English time format "month day, year" even when browsing in other languages. This is mostly (or only?) noticeable in What's New in Python, e.g. [3.11](https://docs.python.org/3.11/whatsnew/3.11.html).

I'd expect the date to honor the language's time format as translated in Sphinx. Taking version 4.5.0 which is used to build Python Docs 3.11, [pt_BR](https://github.com/sphinx-doc/sphinx/blob/c470402cfbeb14cf1c85b27437f7649ef0da61e5/sphinx/locale/pt_BR/LC_MESSAGES/sphinx.po#L927) and [fr](https://github.com/sphinx-doc/sphinx/blob/c470402cfbeb14cf1c85b27437f7649ef0da61e5/sphinx/locale/fr/LC_MESSAGES/sphinx.po#L947) are translated to show "day month, year".

The source of this issue seems to be in [Doc/conf.py](https://github.com/python/cpython/blob/7d1d66341838d7d1963c9ee7ffca2950d3a751fd/Doc/conf.py#L59) which sets [today_fmt](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-today)'s value, hence overriding Sphinx default value and its translations.

Steps to reproduce:
- Browse original [What's New in Python 3.11](https://docs.python.org/3.11/whatsnew/3.11.html) and see `Date: March 29, 2023`
- In the language drop-down menu, select Brazilian Portuguese and see `Date: março 29, 2023` where should be 29 março, 2023
- Now select French, see `Date: mars 29, 2023` where should be 29 mars, 2023

**Comment by hugovk** [comment]
The `|today|` variable has been removed from the What's New pages, for example see:

* https://github.com/python/cpython/issues/100700
* https://github.com/python/cpython/pull/106999

And we can see it's been removed from the pages:

* https://docs.python.org/3.11/whatsnew/3.11.html
* https://docs.python.org/fr/3.11/whatsnew/3.11.html

Therefore we can close this. Thanks for reporting!
