### ISSUE TITLE
Add a timeout to CI builds

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#103180]
The joke PR #103178 included some very slow code that runs at import time, and CI took >3 hours before I canceled it. This wastes resources and is a possible abuse vector; a malicious actor could use it to eat up our CI resource quota. We should have some reasonable timeout (1 hour?) for all CI builds.

### Linked PRs
* gh-103437
* gh-103543
* gh-130375
* gh-130431
* gh-130432

**Comment by kylehofmann** [comment]
I would like to publicly apologize for the PR. It didn't turn out the way I had intended.

**Comment by JelleZijlstra** [comment]
No apology necessary, it's better that we find out about this problem through a well-intentioned joke.

I was actually surprised when I saw the PR that it showed you as a first-time contributor here. Based on the level of your contributions on the Python Discord, I'm sure there's lots of useful work you could do on CPython if you are so inclined. Perhaps your next PR will be less quadratic. (And if you're not interested or don't have time, that's perfectly fine too, of course.)

**Comment by arhadthedev** [comment]
Related issue (for the build step only): gh-90361.

**Comment by sobolevn** [comment]
I had some time to look at this. I think that we need to base timeouts:
1. For short actions, like `stale` and `labels`
2. For build / test actions

## Short timeout

`stale` takes ~1m average to finish:
<img width="886" alt="Снимок экрана 2023-04-11 в 12 10 11" src="https://user-images.githubusercontent.com/4660275/231113176-fc58f21c-1f04-4671-854a-96801e84f5ae.png">

`new-bugs-notifier` takes several seconds:
<img width="891" alt="Снимок экрана 2023-04-11 в 12 11 46" src="https://user-images.githubusercontent.com/4660275/231113355-e444f236-3df3-46dc-82cb-069a3e35f5c3.png">

`check-labels` also takes several seconds:
<img width="881" alt="Снимок экрана 2023-04-11 в 12 12 27" src="https://user-images.githubusercontent.com/4660275/231113506-7fbfc8e0-4804-4897-8833-eb8a37ecc418.png">

`verify-ensurepip-wheels` takes several seconds:
<img width="886" alt="Снимок экрана 2023-04-11 в 12 13 34" src="https://user-images.githubusercontent.com/4660275/231113809-5ab6f621-d42d-41c9-ad8c-7d9bb25fd211.png">

`project-updater` takes several seconds as well:
<img width="889" alt="Снимок экрана 2023-04-11 в 12 15 02" src="https://user-images.githubusercontent.com/4660275/231114067-c3416513-e026-4894-8f76-92620ae0642e.png">

I think that **10 minutes** as a timeout is a reasonable number for this group.
It will allow quite some performance degradation, but still keep our resources under controll. 

## Slow actions

`docs` can work from 10m up to 20m:
<img width="885" alt="Снимок экрана 2023-04-11 в 12 17 05" src="https://user-images.githubusercontent.com/4660275/231114612-b2eb1454-e599-4e0e-b216-09fb3a0fcfca.png">

`testsmsi` can take from several minutes up to 20m:
<img width="879" alt="Снимок экрана 2023-04-11 в 12 18 26" src="https://user-images.githubusercontent.com/4660275/231114940-ffab2bea-fa95-4a3f-8ad9-ccca1aba1379.png">

`build` takes around 30m:
<img width="889" alt="Снимок экрана 2023-04-11 в 12 19 24" src="https://user-images.githubusercontent.com/4660275/231115144-ec8c4a29-4227-4072-9c1d-3052a8ecc7a4.png">

So, using **1h** is a resonable timeout. 

I will send a PR with these timeouts in a moment.
Plus, I will change per-step timeouts from https://github.com/python/cpython/issues/90361 to be job-level (and increase them).

**Comment by hauntsaninja** [comment]
Looks like this was completed, thanks all!
