### ISSUE TITLE
Add π to the `math` module

### ISSUE THREAD

**Issue by JosephSBoyle** [python/cpython#103172]
Currently, the math module in CPython uses the identifier math.pi to represent the mathematical constant π. This breaks user expectations and violates the principle of least surprise.

To improve consistency and readability, I propose changing  math.pi to math.π symbol throughout the module. The reasoning for this is threefold:

1. This change will make the code more intuitive for mathematicians and scientists (at least 99%+ of python users) who are more used to seeing the π symbol, thus reducing cognitive load and allowing them to build more complicated research code. 

2. Python supports unicode characters such as π and we don't take advantage of this enough. We can use π, therefore we should.

3. Nobody currently knows how to type π, if we make this change users will have to open the math module and copy and paste the variable name - which is a great way to increase the visibility of important module internals that users need to read. 

Some would be tempted to create a math.pi alias to maintain backwards compatibility, but I think that would only encourage people to continue using the non-symbolic variable (bad), so I propose simply deleting math.pi entirely (users will get the hint!). 

This is a pretty small change so I don't think a news entry is necessary, in fact I think not having a news entry would make this change a sort of cool Easter Egg that users can discover and enjoy!

Kind regards and happy April 1st,
Joe

### Linked PRs
* gh-103178

**Comment by sobolevn** [comment]
I think that 🥧 is a much better name! It looks *tasty*!

**Comment by kumaraditya303** [comment]
Worth backporting to 2.7!

**Comment by rasputyashka** [comment]
Yea, I was really surprised when realized that my keyboard has only π, but not "p" and "i". That's why i still don't use python when i to do some rocket science.

**Comment by efahl** [comment]
> Python supports unicode characters such as π and we don't take advantage of this enough. We can use π, therefore we should.

I concur wholeheartedly with this.  We should look for other opportunities to ~~impose our will upon~~ make life easier for all users, so suggest we use  Σ  to replace the 'sum' builtin.

**Comment by jschwar313** [comment]
Sounds pretty irrational to me.

**Comment by flowerbug** [comment]
Everyone should write in the margins that using such a symbol is not reflecting the reality of the situation.  As you are writing a finite symbol, but when you read and evaluate such a symbol your brain should never return.  This is true of many such symbols where we fudge maths, e, 1/3, inf, etc.

**Comment by mrabarnett** [comment]
And λ to replace 'lambda', of course.

Plus &#128013; instead of 'Python'.

**Comment by rasputyashka** [comment]
> And λ to replace 'lambda', of course.
> 
> Plus &#128013; instead of 'Python'.

but we don't use "python" anywhere in the code. It's neither builtin or keyword.

**Comment by gvanrossum** [comment]
Where’s the PR?

**Comment by sfermigier** [comment]
On a more serious tone, the "empty set" character (“∅”, U+2205) should be usable to represent an empty set in Python. It currently is not allowed:

```
Python 3.11.2 (main, Feb 16 2023, 02:51:42)
>>> ∅ = set()
  File "<stdin>", line 1
    ∅ = set()
    ^
SyntaxError: invalid character '∅' (U+2205)
```

**Comment by sfermigier** [comment]
> > Python supports unicode characters such as π and we don't take advantage of this enough. We can use π, therefore we should.
> 
> I concur wholeheartedly with this. We should look for other opportunities to ~impose our will upon~ make life easier for all users, so suggest we use Σ to replace the 'sum' builtin.

(Seriously) Note that currently the '∑' (U+2211) character is not allowed as an identifier in Python, so it isn't even doable (assuming it's a good idea):

```
>>> ∑ = sum
  File "<stdin>", line 1
    ∑ = sum
    ^
SyntaxError: invalid character '∑' (U+2211)
```

**Comment by AlexWaygood** [comment]
Alas! For it is no longer April 1, and what had yesterday seemed like a revelatory idea, now seems, uh, foolish.

Thanks for the excellent April Fool's, @JosephSBoyle, it brightened my day :)

**Comment by efahl** [comment]
> (Seriously) Note that currently the '∑' (U+2211) character is not allowed as an identifier in Python, so it isn't even doable (assuming it's a good idea):

I didn't use 2211, I used Σ \u03a3, which is indeed valid as an identifier.  Choose your homographs carefully.

**Comment by holdenweb** [comment]
Those who want it can simply type

    π = math.pi

so I'd suggest this frivolity end immediately. Beware the ∏thon Secret Underground, who have spies out watching for this sort of @*^&E$*^^RVO^RVOP*&%^
