### ISSUE TITLE
detect infinite list extend/append

### ISSUE THREAD

**Issue by fpom** [python/cpython#103284]
When the size of a `dict` changes while it is iterated over, we get a `RuntimeError`. But this is not the case on lists. For instance, the following code will loop until it exhausts memory:

```python
seq = list(range(10))
for s in seq:
    seq.append(s)
```

Same situation with this code:

```python
seq = list(range(10))
seq.extend(s for s in seq)
```

I would have expected such a corner case to be detected.

**Comment by ericvsmith** [comment]
The trick is doing this without breaking currently running code. For example, this:
```python
seq = list(range(10))
for s in seq:
    if len(seq) < 20:
        seq.append(s)
```
currently works, and we wouldn't want to make it an error. This example is admittedly contrived, but it's just indicative of the kind of code that we can't break.

**Comment by rhettinger** [comment]
As Eric points out, this is valid code, so we can't change it.

Also, infinite loop errors are just a special case of larger-than-convenient errors.  In general, we don't really have a straightforward way to determine the actual programmer intent:

```
# Finite and unusably large number of appends
seq = []
for i in range(1_000_000_000_000_000_000): 
     seq.append(i)
```
