### ISSUE TITLE
distutils.dir_util: copy_tree does not recreate folder structures in the same session if deleted in between

### ISSUE THREAD

**Issue by chfo** [python/cpython#103210]
# Bug report

copy_tree has the options to recreate the full folder path.
For example: if the destination is D:\\target\\subdir\\target_folder and subdir does not exists, copy_tree creates the folder subdir.

This works fine for the first call. If you delete the folder subdir and recall copy tree again. It crashes because the folder subdir does not exist any more. This leads to my assumption that copy_tree does not recheck if the folder structure exists (would guess cache reuse).

Example:

```
from distutils.dir_util import copy_tree
import shutil
import os

# Vars
src_folder = "source"
src_file = "src_file"
destination1 = os.path.join("destination", "subdir", "Target1")
destination2 = os.path.join("destination", "subdir", "Target2")

# Prepare Source Files
if not os.path.exists(src_folder):
    os.makedirs(src_folder)
    src_path = os.path.join(src_folder, src_file)
    with open(src_path, 'w') as fp:
        pass

shutil.rmtree(os.path.join("destination"))

# Valid copy commands
copy_tree(src_folder, destination1)
copy_tree(src_folder, destination2)

# Visual proof
for f in os.listdir(destination1):
    print("Destination 1 " + f)

for f in os.listdir(destination2):
    print("Destination 2 " + f)

shutil.rmtree(os.path.join("destination", "subdir"))

# failed copy command
try:
    copy_tree(src_folder, destination1)
except:
    print("copy command failed")
```

# Your environment

- CPython versions tested on: 3.11.2 64bit
- Operating system and architecture: Windows 10

**Comment by AlexWaygood** [comment]
distutils is deprecated in 3.11, and has been removed from CPython entirely on our `main` branch in preparation for 3.12, so we won't be fixing any bugs in distutils, I'm afraid.

Importing distutils on 3.12+ will continue to work if you have setuptools installed (and if you have setuptools installed on 3.11, you're likely already using setuptools's vendored version of distutils without knowing it). But bugs in setuptools's vendored version of distutils should be reported on the setuptools issue tracker: https://github.com/pypa/setuptools/issues
