### ISSUE TITLE
Two apparent unnecessary expressions in `Enum.py::EnumType::_find_new_()`

### ISSUE THREAD

**Issue by sadra-barikbin** [python/cpython#103260]
In the statement below, based on past statements, neiter `first_enum` is `None`, nor `__new__` could reallistically be `Enum.__new__`. 
https://github.com/python/cpython/blob/6abd0486bbb30b9d2c99b00412d5641f9c778b88/Lib/enum.py#L1045-L1046
`first_enum` is not `None` because this has been made sure in `_get_mixins_`:
https://github.com/python/cpython/blob/6abd0486bbb30b9d2c99b00412d5641f9c778b88/Lib/enum.py#L950-L951
Also `__new__` couldn't be `Enum.__new__`  because the earlier statements do not allow this. The only exception is in this unrealistic scenario:

```python
class AnEnum(Enum):
    __new__ = Enum.__new__
```
Is this has been the reason that this term is added to the `if` statement?

By the way in Python3.8 this two expressions don't exist:
https://github.com/python/cpython/blob/3205d1fbbbfcf613b74d236be9db7a8225f452ea/Lib/enum.py#L618-L619

**Comment by ethanfurman** [comment]
When `Enum` itself is being defined, the name `Enum` is [assigned to `None`](https://github.com/python/cpython/blob/6abd0486bbb30b9d2c99b00412d5641f9c778b88/Lib/enum.py#L18-L21).

I temporarily made the change you suggest, and three of the enum tests failed:
- test_convert_complex
- test_convert_uncomparable
- test_test_simple_enum

You can look at those to see why the changes were needed.

**Comment by sadra-barikbin** [comment]
@ethanfurman You're right. As a result of this:
https://github.com/python/cpython/blob/6abd0486bbb30b9d2c99b00412d5641f9c778b88/Lib/enum.py#L21
`Enum` below is `None`
https://github.com/python/cpython/blob/6abd0486bbb30b9d2c99b00412d5641f9c778b88/Lib/enum.py#L950-L951

Thank you for quick response!

**Comment by sadra-barikbin** [comment]
@ethanfurman, I had a question regarding changes in subclassing `Enum` in 3.11. As of 3.11, if enum class has a mixin parent apart from `Enum` which has defined `__init__` or `__new__`, `member._value_` is set to be another instance of the mixin class 
 unless user defines `__new__` in the enum class and set `_value_`. However user naturally expects `_value_` to be the value assigned to the member in class definition. In the example below
```python
class mixin:
  def __init__(self):
    pass

class CustomEnum(mixin, Enum):
  MEMBER = "member"
```
`CustomEnum.MEMBER` is an instance of `mixin` and `CustomEnum.MEMBER.value` is another instance of it(with different id), while it was expected that `CustomEnum.MEMBER.value` would be `"member"`. Could you please explain what has been the rationale for this change?

By the way, this change is not noted in python docs enumeration page.
