### ISSUE TITLE
disabledwidth in canvas.create_rectangle is ignored, needs to be set with canvas.itemconfig

### ISSUE THREAD

**Issue by brockbrownwork** [python/cpython#103216]
# Bug report

I want the outline of a rectangle in a canvas to get a bigger width, when the rectangle is in state "disabled". Therefore I use the parameter "disabledwidth=4". But when the rectangle is in state "disabled", the outline has still a width of 1 instead of 4.

This is my code, which shows the problem:
```python
import tkinter as tk
def disabled():
    canvas.itemconfig(rect, state="disabled")
def normal():
    canvas.itemconfig(rect, state="normal")
root    = tk.Tk()
canvas  = tk.Canvas(root, height=250, width=250)
button1 = tk.Button(root, text="change rectangle to state disabled", command=disabled)
button2 = tk.Button(root, text="change rectangle to state normal"  , command=normal  )
rect = canvas.create_rectangle(40, 40, 180, 180,
                fill           = "red",
                activefill     = "green2",
                activeoutline  = "green3",
                activewidth    = 4,
                disabledfill   = "grey",
                disabledoutline= "grey2",
                disabledwidth  = 4
                )
canvas.grid()
button1.grid()
button2.grid()
root.mainloop()
```
When I move the mouse over the rectangle, the state of the rectangle changes to "active", everything works as expected, especially the outlinewidth changes to 4. But when I change the state to "disabled" by clicking on the button the outline stays at width 1. Here's where it says that this option should exist: [https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/create_rectangle.html](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/create_rectangle.html)

This is the workaround code:
```python
import tkinter as tk

def disabled():
    canvas.itemconfig(rect, state="disabled", width=4)

def normal():
    canvas.itemconfig(rect, state="normal", width=1)

root    = tk.Tk()
canvas  = tk.Canvas(root, height=250, width=250)
button1 = tk.Button(root, text="change rectangle to state disabled", command=disabled)
button2 = tk.Button(root, text="change rectangle to state normal"  , command=normal  )
rect = canvas.create_rectangle(40, 40, 180, 180,
                fill           = "red",
                activefill     = "green2",
                activeoutline  = "green3",
                activewidth    = 4,
                disabledfill   = "grey",
                disabledoutline= "grey2",
                width          = 1
                )
canvas.grid()
button1.grid()
button2.grid()
root.mainloop()
```

# Your environment

- CPython versions tested on:
 3.10.4
- Operating system and architecture:
Windows 10

**Comment by terryjreedy** [comment]
Win 10, 3.12.0a6: create_oval has same bug, create_arc works fine.  All 3 methods make the same tk call except for passing 'arc', 'oval', or 'rectangle'.  I strongly suspect that the bug is in tk.

**Comment by chrstphrchvz** [comment]
I have confirmed that this is a (very old) Tcl/Tk bug, and have submitted a fix for it: https://core.tcl-lang.org/tk/info/f4d9d74df628

**Comment by terryjreedy** [comment]
We'll look forward to getting the fix in a future tk release.  Thank you.
