### ISSUE TITLE
Polish documentation of pdb

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#103237]
# Documentation

pdb's documentation has not been polished for a while and there are a couple of issues with it.

First of all, the introductive part was pretty awkward. It starts with `pdb.run()`, which no one is using for actual debugging. I've never see a 3rd-party tutorial for pdb starting with this usage, or even mentioning it. The example also uses a secluded module `mymodule` in which users have no idea what's going on.

Starting with the most unusual (and arguably most useless) usage of `pdb` is not friendly to the users and could push users away.

Then, `pdb.py` is used multiple times in the documentation which is very unusual. The users would never need to know `pdb.py`. For none of the other documentations, the `-m` usage would refer the module as `XX.py`. Most of the modules that can be invoked with `-m` in the command line use the word "command line" in the usage explanation([zipfile](https://docs.python.org/3/library/zipfile.html#command-line-interface), [unittest](https://docs.python.org/3/library/unittest.html#command-line-interface), [webbrowser](https://docs.python.org/3/library/webbrowser.html)) so I modified that a bit.

Moreover, the example we were giving was not reproducible as it uses a hidden module. We should give users an example that is easy to understand and reproduce.

A couple of the debugger commands also need some polish.
* `where` - we should show the arrow (`>`) because there's also `->` in the output of `where` command and it could also be referred to as an "arrow".
* `args` - we should clarify that we are listing the **current** value of the arguments, because the arguments could be changed since they were passed into the function.
* `display` - added a detailed explanation of expressions of mutable result, which was discussed in https://github.com/python/cpython/issues/102886
* `retval` - clarified the ambiguous usage "a function" to "the current function" as all the other commands use.

### Linked PRs
* gh-103238
* gh-103466

**Comment by hauntsaninja** [comment]
Thanks again for this improvement! :-)
