### ISSUE TITLE
Partial "Introduction" text whiteout when attempting to install the latest MacOS 3.11.3 or 3.10.11 pkgs

### ISSUE THREAD

**Issue by HNichols253** [python/cpython#103290]
Part of the "Introduction" section of the notice to "MacOS 13 Ventura users" whites out when attempting to install download pkgs "python-3.11.3-macos11" or "python-3.10.11-macos11". 

MacBookAir10,1 13.3", M1, Model: MGND3LL/A, Firmware: 8422.100.650, MacOS Ventura 13.3, SSD 256GB, Firewall: On

<img width="645" alt="Screenshot 2023-04-05 at 1 21 25 PM" src="https://user-images.githubusercontent.com/79293579/230201576-62f3d9b4-039a-48a9-8336-c4fd2b6c1ccd.png">
<img width="645" alt="Screenshot 2023-04-05 at 1 20 59 PM" src="https://user-images.githubusercontent.com/79293579/230201591-efcfde4b-0d85-49fc-b7cd-00421f660008.png">

**Comment by ned-deily** [comment]
Thanks for the report. I assume this is only an issue if the system is in dark mode? I did not think to test that. It should render correctly in traditional light mode. If so, I should be able to replace the installer files with just updated Welcome screens.

**Comment by HNichols253** [comment]
Ned, looks like your assumption was correct. When changed to light mode, the text appears just fine.

**Comment by ned-deily** [comment]
I have repackaged all three affected python.org macOS installers (3.12.0a7, 3.11.3, and 3.10.11 with updated Welcome screens that should render correctly in both light and dark modes; otherwise, the installed contents are the same. As of this moment, the updated 3.12.0a7 installer has replaced the original one and the release page has been updated with a note.  I expect that the 3.11.3 and 3.10.11 will be similarly updated in the very near future.

**Comment by hugovk** [comment]
Confirmed the 3.12.0a7 installer looks good now, thank you!

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1324225/230612739-149e4fff-4e01-4691-9644-3e7ffb8b7bc1.png">

<img width="732" alt="image" src="https://user-images.githubusercontent.com/1324225/230612782-84e433f5-3b2f-4b66-b382-7d7cd8d2ca6b.png">

**Comment by hugovk** [comment]
And confirmed fixed with 3.11.4 (macOS Ventura 13.4). Thanks!

![image](https://github.com/python/cpython/assets/1324225/50b67ba9-68f1-4762-bddd-c7eeed5bb373)

![image](https://github.com/python/cpython/assets/1324225/65e14fab-2754-4bff-833c-1884a9883006)
