### ISSUE TITLE
Misspelling Speilberg vs. Spielberg in example code for bisect() function

### ISSUE THREAD

**Issue by PedanticHacker** [python/cpython#103266]
The Python documentation has an example code for the `bisect` function [HERE](https://docs.python.org/3/library/bisect.html#examples). In the second example code there's the surname of the movie director Steven Spielberg written incorrectly as *Speilberg* in every occurence. His surname should be corrected from *Speilberg* to the correct spelling *Spielberg*.

Perhaps his Wikipedia article should be enough to prove my point: [Steven Spielberg Wikipedia article](https://en.wikipedia.org/wiki/Steven_Spielberg)

I am politely asking to fix this misspelling in the example code for every such occurence. Thank you.

### Linked PRs
* gh-103267
* gh-103327

**Comment by sobolevn** [comment]
Very cool bug, thanks 🎦

**Comment by hugovk** [comment]
Thanks, fixed and backported to 3.11.
