### ISSUE TITLE
`pathlib.Path.owner()` and `.group()` should accept a `follow_symlinks` argument

### ISSUE THREAD

**Issue by markrwilliams** [python/cpython#103363]
# Feature or enhancement

`pathlib.Path.owner()` and `pathlib.Path.group()` always follow symbolic links.  They should gain a new argument, `follow_symlinks`, that defaults to `True`. This will align their API with that of `pathlib.Path.stat()` and `pathlib.Path.chmod()`

# Pitch

Most `pathlib.Path` methods follow symbolic links, so it's natural for these ownership methods to do the same.
However, doing so unconditionally results in a surprising error when you'd actually like them to look at a link's ownership - for example, to work with a system that uses dangling symbolic links as lock files - and there's no convenient API to call instead.

# Previous discussion

#65521 brought up the same issue but proposed fixing it by changing the system call from `stat` to `lstat`, which was deemed too disruptive.
#18864 added `follow_symlinks` to `pathlib.Path.stat` and `pathlib.Path.chmod`. [A commenter](https://github.com/python/cpython/pull/18864#issuecomment-645263576) asked about adding this argument to other methods, namely `is_file()` and `is_dir()`.

I'm happy to contribute the code if this seems worth doing.

### Linked PRs
* gh-107962

**Comment by barneygale** [comment]
Sounds reasonable to me!

**Comment by ganesh-k13** [comment]
@markrwilliams are you working on this issue? I'd be happy to add it if you are not.

**Comment by kamilturek** [comment]
Given no action for several months on this issue, I decided to open a PR.

**Comment by barneygale** [comment]
Implemented by @kamilturek in #107962, merged into 3.13 as [a1551b4](https://github.com/python/cpython/commit/a1551b48eebb4a68fda031b5ee9e5cbde8d924dd) :tada:

**Comment by jb2170** [comment]
Nice
