### ISSUE TITLE
Get the "Current" Thread State from a Thread-local

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#103323]
(This is a revival of gh-84702, which @vstinner worked on several years ago.)

For a per-interpreter GIL (PEP 684) we need to start storing the "current" thread state in a thread-local variable, rather than `_PyRuntime.tstate_current`.  There may be other benefits to the approach if we can take advantage of native compiler support (e.g. C11's `__thread_local`).

Also see https://discuss.python.org/t/how-to-get-the-current-thread-state/22655.

### Linked PRs
* gh-103324
* gh-104171
* gh-114593

**Comment by ericsnowcurrently** [comment]
CC @markshannon

**Comment by hauntsaninja** [comment]
Looks like this was completed, thanks!
