### ISSUE TITLE
enum.CONFORM behavior breaks backwards compatibility

### ISSUE THREAD

**Issue by benburrill** [python/cpython#103365]
Encountered yet another breaking change for enums.  There are two problems here:

* CONFORM doesn't "conform" to members that are partially unsupported
* CONFORM does not match the previous behavior for Flag.  It used to be more similar to STRICT, but STRICT also doesn't allow partially unsupported members, while Flag in 3.10 did.

Example to reproduce:

```python
import enum
class SkipFlag(enum.Flag):
    A = 1
    B = 2
    C = 4 | B

print(SkipFlag.C in (SkipFlag.A|SkipFlag.C))

class SkipIntFlag(enum.IntFlag):
    A = 1
    B = 2
    C = 4 | B

print(SkipIntFlag.C in (SkipIntFlag.A|SkipIntFlag.C))

print(SkipIntFlag(42).value)
print(SkipFlag(42).value)
```

In Python 3.10.6, this code outputs:

```
True
True
42
Traceback (most recent call last):
...
ValueError: 42 is not a valid SkipFlag
````

In Python 3.11.2:
```
False
True
42
2
```

Having such members as C is useful to create a flags that are distinct from B but always implies B.

In a previous comment bug report it was stated that the previous behavior of Flag was CONFORM:

> Actually, won't need a deprecation period, since the proper default for `Flag` is `CONFORM` as that matches previous behavior.

_Originally posted by @ethanfurman in https://github.com/python/cpython/issues/96865#issuecomment-1251372597_

Clearly this is incorrect.  The previous behavior was more similar to STRICT, but there appears to be no precise equivalent in Python 3.11 to the old behavior.  Using STRICT in Python 3.11, `SkipFlag.A | SkipFlag.C` would fail to be created completely.

### Linked PRs
* gh-103494
* gh-103513

**Comment by sunmy2019** [comment]
With https://github.com/python/cpython/pull/24215, only single-bit values will be considered in `Flag`. multi-bit values are only considered an alias.

Thus `SkipIntFlag.A | SkipIntFlag.C` is actually `SkipIntFlag.A | SkipIntFlag.B`, since the `0b100` bit is discarded.

You will need an element with value 4 inside of `SkipFlag`.

This answers "why it behaves like this".

**Comment by sunmy2019** [comment]
> Only single-bit values will be considered in Flag

This is documented with an inconspicuous line.

https://docs.python.org/3.10/library/enum.html#combining-members-of-flag
https://docs.python.org/3.11/howto/enum.html#flag-and-intflag-minutia

I think this should be added to the API reference here:
https://docs.python.org/3/library/enum.html#enum.Flag

**Comment by benburrill** [comment]
> https://docs.python.org/3.11/howto/enum.html#flag-and-intflag-minutia

It's also documented there that the default for Flag in Python 3.11 is STRICT, but it's really CONFORM

**Comment by ethanfurman** [comment]
@benburrill Thank you for the bug report.  `STRICT` has been restored as the default for `Flag`, and the underlying issues fixed.
