### ISSUE TITLE
Improve `typing._GenericAlias.__dir__` coverage

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#103395]
Right now the only test we have for `dir()` on `_GenericAlias` is 

```python
    def test_genericalias_dir(self):
        class Foo(Generic[T]):
            def bar(self):
                pass
            baz = 3
        # The class attributes of the original class should be visible even
        # in dir() of the GenericAlias. See bpo-45755.
        self.assertIn('bar', dir(Foo[int]))
        self.assertIn('baz', dir(Foo[int]))
```

And here's how it is defined:

https://github.com/python/cpython/blob/c330b4a3e7b34308ad97d51de9ab8f4e51a0805c/Lib/typing.py#L1323-L1325

We clearly need more tests:
1. That dunder methods are not included
2. What `_GenericAlias` API we expose (at least parts that we consider user-visible, like `__args__` and `__parameters__` and `__origin__`)
3. `_GenericAlias` has subclasses, they are also not tested

I will send a PR for this :)

### Linked PRs
* gh-103396
* gh-103410

**Comment by sobolevn** [comment]
Oh, looks like this test revealed a bug (or at least an inconsistency):

```python
>>> typing.Callable[..., int].copy_with(([int, str], bool))
typing.Callable[[<class 'int'>, <class 'str'>], bool]
>>> collections.abc.Callable.copy_with
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Callable' has no attribute 'copy_with'
```

**Comment by sobolevn** [comment]
I can open a new issue for it, if this is an issue indeed.

**Comment by AlexWaygood** [comment]
> Oh, looks like this test revealed a bug (or at least an inconsistency):
> 
> ```python
> >>> typing.Callable[..., int].copy_with(([int, str], bool))
> typing.Callable[[<class 'int'>, <class 'str'>], bool]
> >>> collections.abc.Callable[..., int].copy_with
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> AttributeError: type object 'Callable' has no attribute 'copy_with'
> ```

I don't _think_ the `copy_with` method is meant to be public-API. We document several public attributes of `GenericAlias` objects here, and `copy_with` is not one of the ones documented: https://docs.python.org/3/library/stdtypes.html#special-attributes-of-genericalias-objects.

_However_, the `copy_with` method is used by several internal functions of the `typing` module, e.g.:

https://github.com/python/cpython/blob/8317d51996e68d8bb205385c1d47a9edcd128e7b/Lib/typing.py#L401

So it's possible that this method being absent on instances of `collections.abc._CallableGenericAlias` means there's a difference in behaviour that's exposed to users. If so, then we have got a bug on our hands.

**Comment by AlexWaygood** [comment]
> So it's possible that this method being absent on instances of `collections.abc._CallableGenericAlias` means there's a difference in behaviour that's exposed to users. If so, then we have got a bug on our hands.

I don't think there is a user-visible bug here due to `collections.abc.Callable[..., int]` not having a `.copy_with` method. All places in the `typing` module where the `.copy_with` method is accessed are unreachable for objects that are instances of `types.GenericAlias` (and `collections.abc._CallableGenericAlias` is a subclass of `types.GenericAlias`). Moreover, this is just the same behaviour as we get with all `GenericAlias` objects -- `Tuple[int, int]` has a `copy_with` method, but `tuple[int, int]` does not:

```pycon
>>> import typing
>>> typing.Tuple[int, int].copy_with
<bound method _GenericAlias.copy_with of typing.Tuple[int, int]>
>>> tuple[int, int].copy_with
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'tuple' has no attribute 'copy_with'
```

**Comment by sobolevn** [comment]
Yes, looks like we special case all `types.GenericAlias` usages before `.copy_with` call happens. Some examples:

```python
        if isinstance(t, GenericAlias):
            return GenericAlias(t.__origin__, ev_args)
        if isinstance(t, types.UnionType):
            return functools.reduce(operator.or_, ev_args)
        else:
            return t.copy_with(ev_args)
```

and

```python
    if isinstance(t, _GenericAlias):
        stripped_args = tuple(_strip_annotations(a) for a in t.__args__)
        if stripped_args == t.__args__:
            return t
        return t.copy_with(stripped_args)
    if isinstance(t, GenericAlias):
        stripped_args = tuple(_strip_annotations(a) for a in t.__args__)
        if stripped_args == t.__args__:
            return t
        return GenericAlias(t.__origin__, stripped_args)
```

I agree that this is not a bug, but it looks like a bad API :)
Ideally, `types.GenericAlias` should have the same API here, but since it already has some different ways of doing things, let's leave it as-is.
