### ISSUE TITLE
String escape sequences should be listed in the stdtypes page

### ISSUE THREAD

**Issue by egtwobits** [python/cpython#103360]
# Documentation

Since string escape sequences are FREQUENTLY used and referred to, they should be listed on the [Built In Types](https://docs.python.org/3/library/stdtypes.html) page, not tucked away in an obscure [lexical analysis](https://docs.python.org/3/reference/lexical_analysis.html) page :( Finding it from a search engine is just HORRIBLE.

### Linked PRs
* gh-103638
* gh-114907
* gh-114908

**Comment by terryjreedy** [comment]
The reference for [string/bytes literals](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) belongs where it is, the Literals section of the reference manual.  The [string and bytes](https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str) doc already has a cross-reference to that section.  

We might consider making "escape sequences" in that sentence link to the table.

**Comment by zormit** [comment]
I think this is solved by the PR, but the PR got stale somehow (CI results are outdated by now).
