### ISSUE TITLE
Replace Py_NewRef(Py_NotImplemented) usage with Py_RETURN_NOTIMPLEMENTED

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#103354]
I believe that using ```Py_RETURN_NOTIMPLEMENTED``` instead of ```Py_NewRef(Py_NotImplemented)``` makes the code easier to read and understand.

### Linked PRs
* gh-103355

**Comment by sobolevn** [comment]
See my comment on the PR on why it was rejected.
