### ISSUE TITLE
Visual Studio Community 2017 is kind of old.

### ISSUE THREAD

**Issue by tasty0tomato** [python/cpython#103340]
https://github.com/python/cpython/blob/main/PCbuild/readme.txt
https://learn.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes

> Visual Studio 2017 version 15.9 is the final supported servicing baseline for Visual Studio 2017 and has entered the extended support period

Maybe time to use Visual Studio 2022 or at least 2019?

**Comment by 2010person** [comment]
Some people might not be able to upgrade, but I guess you could always use a later version if you wish?

**Comment by terryjreedy** [comment]
VC2017 is the minimum.  The Visual Studio link in the [devguide](https://devguide.python.org/getting-started/setup-building/#windows-compiling) actually installs VC2022, at least by default.

The readme otherwise needs updating as 64 bit builds have been the default for a few releases.

**Comment by arhadthedev** [comment]
Сlosing because VS 2019 and 2022 open and save VS 2017 project files without conversion. As for features, C11 is supported by all three versions in the same way.
