### ISSUE TITLE
C-API header files break compilation

### ISSUE THREAD

**Issue by Jon-Croz** [python/cpython#103317]
# Bug report

I am extending a currently-functional C program with a new module that contains embedded python. As such, I set my environment variables, LDFLAGS / CFLAGS, PYTHONHOME, load the intel modules I need, and everything compiles _except_ the references to Python.h's related files. There is nothing wrong with Python.h (as far as I'm concerned), but rather the libraries it calls (specifically: object.h, pytime.h, objimpl.h, bytesobject.h and unicodeobject.h. 

I've tested the compilation for Python2.7, and it works fine. Python3.9's libraries are giving me problems. 

# Your environment

CentOS Linux 7, intel64/2019/mpiicc, Python3.9

[2023-4-6_Python-C-API.txt](https://github.com/python/cpython/files/11173203/2023-4-6_Python-C-API.txt)

**Comment by CrozierJonathan** [comment]
And attached are the troublesome header files:

[2023-4-6_Python-headers.zip](https://github.com/python/cpython/files/11174195/2023-4-6_Python-headers.zip)

**Comment by CrozierJonathan** [comment]
Does anyone on the python-dev team or another user have insight into the nature of this problem?

**Comment by YanniCrozr** [comment]
Update for all those who are interested in this problem: the solution is as follows:

- define Py_LIMITED_API, manually edit object.h's syntax problems (which stem from C90/C99 conflicts), update and source the correct mpicc library / load modules, activate the conda environment, and load associated ldflags and cflags to point to the correct Python.h at compilation time.

Voila.
