### ISSUE TITLE
Running and importing a file creates a duplicate copies of the module.

### ISSUE THREAD

**Issue by st-pasha** [python/cpython#103390]
# Bug report

Consider a minimal `example` module with two files:

**bar.py**
```python
def get_foo():
    from .foo import Foo
    return Foo()
```
**foo.py**
```python
class Foo: pass

def main():
    from .bar import get_foo
    foo = get_foo()
    print(f"foo is an instance of Foo: {isinstance(foo, Foo)}")

if __name__ == "__main__":
    main()
```

In this case running `python -m example.foo` will print
```
foo is an instance of Foo: False
```

Essentially, the class `Foo` visible from `bar.py`, and the one in the `foo.py` are two different objects! When I print their fully qualified names, they turn out to be:
```
example.foo.Foo
__main__.Foo
```
So I kinda understand how this problem comes out to be, but I still think it's a bug, because if I run `foo.main()` from a different file (say `__main__.py`), then the answer will be different.

# Your environment

I've tested this MVE on python 3.8.16 and on 3.11.2, macOS and Linux.

**Comment by sunmy2019** [comment]
You can try

```py
if __name__ == "__main__":
    from .foo import Foo 
    main()
```

**Comment by terryjreedy** [comment]
When you run a file as main and import it from another modules, you get duplicate copies of the *module*, and hence everything in it.  This is a known gotcha.  The standard solution is to define nothing in the startup module except for a `main` function that is never imported by any other module in the package or application. Another is a solution I used in IDLE is the following code at the top of pyshell.py.  Running pyshell.py was once the documented main entry point to start IDLE and might still be used as such by people who have not switched to idle.py.
```python
if __name__ == "__main__":
    sys.modules['idlelib.pyshell'] = sys.modules['__main__']
```
After this, the two entries in sys.modules point to the same module created from pyshell.py.  Other modules that import pyshell will use the idlelib.pyshell key.
