### ISSUE TITLE
A new issue is not needed for something like this.  A PR attached to the original issue is better (even if issue is 'closed') as can see fix on original issue.  Re-pointed PR to original issue.

### ISSUE THREAD

**Issue by Security2965** [python/cpython#103346]
A new issue is not needed for something like this.  A PR attached to the original issue is better (even if issue is 'closed') as can see fix on original issue.  Re-pointed PR to original issue.

_Originally posted by @terryjreedy in https://github.com/python/cpython/issues/103145#issuecomment-1491950904_

**Comment by terryjreedy** [comment]
I also reported to GH.
