### ISSUE TITLE
ResourceWarning due to unclosed response in http.client.HTTPConnection._tunnel

### ISSUE THREAD

**Issue by graingert** [python/cpython#103472]
# Bug report

calling `http.client.HTTPConnection._tunnel()` may result in a `ResourceWarning` because the response is not closed

this results in an intermittent failure on the urllib3 test `test/with_dummyserver/test_proxy_poolmanager.py::TestHTTPProxyManager::test_tunneling_proxy_request_timeout[https-https]` with ResourceWarnings enabled, see https://github.com/urllib3/urllib3/actions/runs/4638944124/jobs/8209257011#step:6:2471 and https://github.com/urllib3/urllib3/blob/4d425a2d767ce2e0c988fff4385046ea57458c49/test/with_dummyserver/test_proxy_poolmanager.py#L480-L498

# Your environment

- CPython versions tested on: 3.8-3.11

### Linked PRs
* gh-103473
* gh-104077

**Comment by hauntsaninja** [comment]
Looks like this was fixed, thanks all!
