### ISSUE TITLE
Deprecate `pathlib.Path.lstat()` and `lchmod()`

### ISSUE THREAD

**Issue by barneygale** [python/cpython#103476]
These methods have non-obvious names, unless you already know that "l" stands for "link". They can be readily replaced with `stat(follow_symlinks=False)` and `chmod(follow_symlinks=False)`, which are more explicit and conform better to pathlib's other APIs.

IMHO the pathlib interface would be better off without them. How would we feel about deprecating + removing them?

**Comment by ramvikrams** [comment]
Should I go on with  depricating it ?

**Comment by barneygale** [comment]
I should have started a discussion thread before logging this issue. It's here now:

https://discuss.python.org/t/deprecate-pathlib-path-lstat-and-lchmod/26036

**Comment by barneygale** [comment]
Won't do. Too much churn for too little gain.
