### ISSUE TITLE
Embedded python doesn't recognize exit()

### ISSUE THREAD

**Issue by jschwar313** [python/cpython#103411]
# Documentation

I had the same issue with embedded python as this issue:  https://github.com/python/cpython/issues/90007

This was my error:

C:\Program Files\Jim Schwartz\AWS PC Backup>aws_pc_backup.exe -m:lb
Traceback (most recent call last):
  File "aws_pc_backup_main.py", line 1, in init python.aws_pc_backup_main
NameError: name 'exit' is not defined

I found out the problem.  It's not an issue with coding.  It's an issue with the directory structure of the python embedded code and that directory structure is not documented.  

You need to put in the documentation that the following directory structure should be followed when packaging your embedded code:

In the root, put the following code:
python.exe
python3.dll
python311.dll
pythonw.exe
vcruntime140.dll
vcruntime140_1.dll

Then create a directory called DLLs and put the contents of the rest of the zip file's root code

Then create a directory called Lib in the application root and put the contents of the zip file called  python311.zip that included in the zip file.

Then in the Lib directory, there's a site-packages directory.  Paste your packages in there from your application code that your application uses.

I hope this helps someone else and I hope you change the documentation to include this information.  Please tag the people on that issue I posted in this issue.

**Comment by eryksun** [comment]
The embeddable distribution requires no extra directory structure to be created. You can just unzip it in the destination directory. Note, however, that it contains a [".\_pth" file](https://docs.python.org/3/library/sys_path_init.html#pth-files) (e.g. "python311.\_pth"). This file assigns the initial `sys.path`, and its presence also ensures that Python runs in isolated mode. Each path in a ".\_pth" file can be either absolute or relative to the location of the file. By default it includes a "." entry, which refers to the directory that contains the "._pth" file, and an entry for the zipped standard library (e.g. "python311.zip"). When a ".\_pth" file is used, the [`site` module](https://docs.python.org/3/library/site.html) will not be imported automatically at startup, unless the ".\_pth" file includes the directive `import site`.

By default, `builtins.exit` is assigned by the `site` module. You can manually alias `sys.exit` as `builtins.exit` if you have no other reason to import the `site` module.

**Comment by jschwar313** [comment]
I checked out my application directory.  I found one *._pth file:

C:\Program Files\Jim Schwartz\AWS PC Backup>dir /s *._pth
 Volume in drive C is OS
 Volume Serial Number is 7EC9-D353

 Directory of C:\Program Files\Jim Schwartz\AWS PC Backup\DLLs

04/10/2023  07:58 AM                80 python311._pth
               1 File(s)             80 bytes

     Total Files Listed:
               1 File(s)             80 bytes
               0 Dir(s)  687,939,502,080 bytes free

C:\Program Files\Jim Schwartz\AWS PC Backup>type C:\Program Files\Jim Schwartz\AWS PC Backup\DLLs\python311._pth
The system cannot find the file specified.
Error occurred while processing: C:\Program.
The system cannot find the path specified.

C:\Program Files\Jim Schwartz\AWS PC Backup>type "C:\Program Files\Jim Schwartz\AWS PC Backup\DLLs\python311._pth"
python311.zip
.

# Uncomment to run site.main() automatically
#import site

I then renamed it to python311._pth.old and my app still worked.  I do have python on my path.  I'll try my dual boot where python is not on my path later.

**Comment by jschwar313** [comment]
By the way, my application, which is written in python, are generated and compiled like this.  Would that affect the embedded python directory structure in any way?

cython -3 --embed -o aws_pc_backup.c   ..\..\src\python\aws_pc_backup_main.py

cl /O2 /I"C:\\Users\\(userid)\\AppData\\Local\\Programs\\Python\\Python3112\\include\\" aws_pc_backup.c /link C:\\Users\\(userid)\\AppData\\Local\\Programs\\Python\\Python3112\\libs\\python311.lib

**Comment by jschwar313** [comment]
I did what you said and I got this when running my app:

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>aws_pc_backup.exe -m:lb
Traceback (most recent call last):
  File "aws_pc_backup_main.py", line 1, in init python.aws_pc_backup_main
NameError: name 'exit' is not defined

I put the site-packages directory under Lib in my application directory.  Is that correct?  How should I change it if it's not.  Again, this is not documented from what I can see.  If I'm wrong, please tell me.  This same command works in my other directory that I set up like I previously described.  By the way, I call sys.exit(0) in my python code.  I import sys.

**Comment by jschwar313** [comment]
One more update.  I have an easy way to reproduce issues with python as an embedded distribution.  I wrote a simple python program to get my public ip address.  I ran it in the embedded distribution directory set up like you said but I put the site-packages directory under Lib and I also tried it with site-packages in the root.  I received the same error both times.  Here's what happened and I've attached my program.  Are we supposed to unzip that python zip file and paste the packages in the site-packages directory and zip it up again?  That's not documented if we are supposed to do that.

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>python get_public_ip_address.py
Traceback (most recent call last):
  File "C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck\get_public_ip_address.py", line 2, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

[get_public_ip_address.py.txt](https://github.com/python/cpython/files/11194650/get_public_ip_address.py.txt)

**Comment by eryksun** [comment]
The "python311._pth" file that's beside "python311.dll" and "python311.zip" is the ideal way to have complete control over `sys.path` in a Python-based application. It overrides the default strategies for creating `sys.path`, which is really what you want in the embedding context. It's also important that it enables isolated mode, so your application won't be affected by registry settings or any of the `PYTHON*` environment variables, which are intended for system scripting and development, not for applications.

The following works fine for me.

app.py (compiled to "app.exe" using Cython and VC++):

```python
import sys
import requests

exit = sys.exit

def main(argv):
    print('sys.flags.isolated:', sys.flags.isolated)
    print('sys.executable:', sys.executable)
    print('sys.prefix:', sys.prefix)
    print('sys.exec_prefix:', sys.exec_prefix) 
    print('sys.path:', sys.path, sep='\n')
    my_public_ip = requests.get('https://checkip.amazonaws.com').text.strip()
    print('My Public ip is', my_public_ip)
    return 0

if __name__ == '__main__':
    exit(main(sys.argv))
```

python311.\_pth:

```text
python311.zip
.
packages
```

"packages" subdirectory (vendored packages):

* requests
* certifi
* charset\_normalizer
* idna
* urllib3

Output:

```text
C:\Temp\test>embed\app.exe
sys.flags.isolated: 1
sys.executable: C:\Temp\test\embed\app.exe
sys.prefix: C:\Temp\test\embed
sys.exec_prefix: C:\Temp\test\embed
sys.path:
['C:\\Temp\\test\\embed', 'C:\\Temp\\test\\embed\\python311.zip', 'C:\\Temp\\test\\embed', 'C:\\Temp\\test\\embed\\packages']
My Public ip is ******
```

**Comment by jschwar313** [comment]
I updated the zip file to have the site-packages in the zip file that I need.  I deleted the site-packages directory that I had there.  I then ran the following:

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>python get_public_ip_address.py
Python path configuration:
  PYTHONHOME = 'C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck'
  PYTHONPATH = (not set)
  program name = 'python.exe'
  isolated = 1
  environment = 0
  user site = 1
  safe_path = 1
  import site = 0
  is in build tree = 0
  stdlib dir = 'C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck\Lib'
  sys._base_executable = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck\\python.exe'
  sys.base_prefix = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck'
  sys.base_exec_prefix = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck'
  sys.platlibdir = 'DLLs'
  sys.executable = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck\\python.exe'
  sys.prefix = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck'
  sys.exec_prefix = 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck'
  sys.path = [
    'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck\\python311.zip',
    'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x000094d4 (most recent call first):
  <no Python frame>

**Comment by jschwar313** [comment]
I'm still having issues and I don't know why.  I re-extracted the embedded zip file, I updated the *._pth file, I put my packages in a new directory called packages, which is listed in the *._pth file.  Here are my results.  I created an app.py file from your code, too.

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>type *._pth

python311._pth


python311.zip
.
packages

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>python --version
Python 3.11.2

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>pip list
'pip' is not recognized as an internal or external command,
operable program or batch file.

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>python app.py
sys.flags.isolated: 1
sys.executable: C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck\python.exe
sys.prefix: C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck
sys.exec_prefix: C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck
sys.path:
['C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck\\python311.zip', 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck', 'C:\\Program Files\\Jim Schwartz\\AWS PC BACKUP Embedded Eryck\\packages']
My Public ip is <snip>

C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>aws_pc_backup.exe -m:lb
Traceback (most recent call last):
  File "aws_pc_backup_main.py", line 1, in init python.aws_pc_backup_main
NameError: name 'exit' is not defined

**Comment by jschwar313** [comment]
By the way, I was told to use cython version 3.0.0b1 to get rid of the warnings in the regular package.  Not sure if that's contributing to some of these issues or not.

**Comment by eryksun** [comment]
>   File "aws_pc_backup_main.py", line 1, in init python.aws_pc_backup_main
NameError: name 'exit' is not defined

As already discussed, there is no `exit()` function in `builtins` if the `site` module isn't imported. That said, I advise against using the `import site` directive in "python311.\_pth". Doing so will add the per-user site packages directory to `sys.path` if that directory exists. This could interfere with your application -- e.g. an optional dependency that you don't include in your application could get sourced from a `--user` install.

Note that the `exit()` function isn't intended to be reliably available. It's a convenience for interactive use in the REPL shell. See the list of [builtin functions](https://docs.python.org/3/library/functions.html) and the [constants added by the site module](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module):

>> The [site](https://docs.python.org/3/library/site.html#module-site) module (which is imported automatically during startup, except if the [-S](https://docs.python.org/3/using/cmdline.html#cmdoption-S) command-line option is given) adds several constants to the built-in namespace. They are useful for the interactive interpreter shell and *should not be used in programs* [emphasis added].

Notice that in "app.py", I aliased `exit = sys.exit`. My previous suggestion to set `builtins.exit = sys.exit` turns out to be tricky to implement with a Cython-ized script because the Cython compiler uses early binding of names that aren't defined globally. Thus it will try to bind `exit` (and possibly fail) before the script has a chance to set `builtins.exit`. 

I suggest that you just use `sys.exit()`, and forget about using `exit()`, which is what the documentation advises for scripts and applications.

> C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>pip list
'pip' is not recognized as an internal or external command,
operable program or batch file.

I suggest using a virtual environment that only has the required packages installed. If the virtual environment has pip installed (default), then activating the environment ensures that the "pip" command works and operates on the right environment. with a virtual environment that's created specifically for developing the application, just copy its site packages directory to "packages". Additionally, you could replace all ".py" files in the required packages with compiled ".pyc" files, which is how the standard library is distributed in "python311.zip".

**Comment by jschwar313** [comment]
First, I don't use exit().  I use sys.exit() with an integer return code in the parens.  Sorry, I should have told you that previously.

Second, I do use a virtual environment for testing, but I want to get the embedded distribution working like it should work.  I don't know how to do that.  I have a working environment, but it's set up like a python install but with no environment variables.  It's much larger than the embedded environment, too.  That works fine, although I need to test it on my dual boot environment yet.  I can't seem to get the embedded environment working like the documentation says it should.

**Comment by eryksun** [comment]
> First, I don't use exit().

Something in `python.aws_pc_backup_main` is calling `exit()` without a global (per module) binding of `exit`. This fails, as expected since Cython implements early binding. This is the kind of error that I experience with a Cython-ized script that called `exit()` when "python311.\_pth" didn't include the `import site` directive (a setting that you should not use):

>> C:\Program Files\Jim Schwartz\AWS PC BACKUP Embedded Eryck>aws_pc_backup.exe -m:lb
Traceback (most recent call last):
  File "aws_pc_backup_main.py", line 1, in init python.aws_pc_backup_main
NameError: name 'exit' is not defined

**Comment by jschwar313** [comment]
I have your email address from other posts.  I'll email you the python code and the generated c code that I'm using.  You won't be able to run the program without an AWS account, though, but this will give you an idea.  Not sure if this will help or not.

**Comment by erlend-aasland** [comment]
> OMG. I did have exit in my code. I'm so sorry. I'll change that now. I apologize. Now my executable works, but pip list doesn't. Why is that?

I'm not sure how to interpret your post; is this still an issue? Can we close this? Does the issue title still reflect the issue you are/were seeing?

**Comment by jschwar313** [comment]
Yes. You can close this now. Sorry for the misunderstanding. Sent from my iPhoneOn Jun 19, 2023, at 3:46 PM, Erlend E. Aasland ***@***.***> wrote:﻿

OMG. I did have exit in my code. I'm so sorry. I'll change that now. I apologize. Now my executable works, but pip list doesn't. Why is that?

I'm not sure how to interpret your post; is this still an issue? Can we close this? Does the issue title still reflect the issue you are/were seeing?
