### ISSUE TITLE
sched.scheduler docs improvement

### ISSUE THREAD

**Issue by nburns** [python/cpython#103417]
# Documentation
The docs for `sched.scheduler` have an example that uses `time.time` as the `timefunc` https://docs.python.org/3/library/sched.html#sched.scheduler

Using `time.time` instead of `time.monotonic` (the default value of `sched.scheduler`) creates the potential for "strange things" to happen when seasonal time shifts make the system clock go backwards, resulting in bugs in user's code.

It seems like it would be better to use `time.monononic` so as to introduce better practices to people learning the language.

### Linked PRs
* gh-103418
* gh-103468
* gh-111497
* gh-115908
* gh-115909

**Comment by hauntsaninja** [comment]
Thank you!

**Comment by serhiy-storchaka** [comment]
It broken the example which expects that the result of `timefunc()` is larger than 1_650_000_000 (~ 2022-Apr-15). It is not so for `time.monotonix()`, unless your system has more than 50 years uptime. See #111497.
