### ISSUE TITLE
Clarify SyntaxWarning with literal comparison

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#103492]
I had a coworker slightly confused about the following warning, since None is a literal and `is not None` is idiomatic:
```
>>> 'a' is not None
<stdin>:1: SyntaxWarning: "is not" with a literal. Did you mean "!="?
True
```
I think this would be better as:
```
>>> 'a' is not None
<stdin>:1: SyntaxWarning: "is not" with str literal. Did you mean "!="?
True
```

### Linked PRs
* gh-103493

**Comment by terryjreedy** [comment]
https://docs.python.org/3/reference/lexical_analysis.html#literals 
> Literals are notations for constant values of some built-in types.
In particular bytes, strings, and numbers are discussed in the following.
https://docs.python.org/3/reference/expressions.html#literals is more specific.
> Python supports string and bytes literals and various numeric literals:
> Evaluation of a literal yields an object of the given type (string, bytes, integer, floating point number, complex number) with the given value.

None is a constant, but not a 'literal' as defined in the sections above.  This is only to say that the current message is not really ambiguous.  Still, the added detail may help some.

https://docs.python.org/3/reference/expressions.html#parenthesized-forms
A tuple is a 'parenthesized form' that is either empty or has at least 1 comma.   A constant tuple is not really a literal, but testing  I see that one is already called a 'literal'.

The test changes look good; can't review the c code.
