### ISSUE TITLE
Brazilian Portuguese translation for "3.3.9. With Statement Context Managers"

### ISSUE THREAD

**Issue by pauloc** [python/cpython#103419]
# Documentation

The Brazilian Portuguese translation for "3.3.9. With Statement Context Managers" (https://docs.python.org/3/reference/datamodel.html#with-statement-context-managers) in "3. Data Model" is wrong.

It reads "Com gerenciadores de contexto de instruções", which makes no sense whatsoever.

The correct translation for the original English title("With Statement Context Managers") is "Gerenciadores de Contexto da Instrução with"

**Comment by sobolevn** [comment]
I think that this should be moved to https://github.com/python/python-docs-pt-br

**Comment by AlexWaygood** [comment]
> I think that this should be moved to https://github.com/python/python-docs-pt-br

Yes, please open an issue there instead!
