### ISSUE TITLE
Grammatical Error

### ISSUE THREAD

**Issue by Aditya-Naresh** [python/cpython#103446]
# Documentation
I was learning the language using the official documentation and came across a small grammatical error on the page https://docs.python.org/3/tutorial/modules.html . 
![image](https://user-images.githubusercontent.com/64772267/231244038-7c13d7b4-59bc-45a4-af98-84ed94475273.png)

**Comment by Aditya-Naresh** [comment]
@Eclips4

**Comment by wookie184** [comment]
Hi,

What is the grammatical error that you are referring to?

**Comment by Eclips4** [comment]
Hello again =)
Please, read the code of conduct and devguide before making a PR.
Such changes doesn't need a issue.
However, your PR which you wanna merge to 3.11 branch, cannot be merged. Please re-create your PR and choose main branch.

**Comment by zware** [comment]
See #103444.  I don't agree that there's a grammatical error here, and am thus closing the issue.

**Comment by terryjreedy** [comment]
The ambiguity in the challenged sentence, leading to the OP's claim,  is that 'run' can be either active present tense ('does not') or passive past participle ('is not')*.  Both are grammatical and both can work in this context.  The effective meaning is the same, so status quo wins.

*Compare, for instance, 'If one pushes an open door and there is a 100-pound rock in the doorway, the door' ... 'does not close.' versus 'is not closed.'  If one were writing a novel, the subtle difference of emphasis on the action versus result and view time (during versus after) could likely be relevant.  But not here.
