### ISSUE TITLE
Make `float.__floordiv__` return an int

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#103445]
# Feature or enhancement

`int.__floordiv__` and `float.__floordiv__` are the only two builtin implementations of the `//` operator.
This is to make `float.__floordiv__` return an int, so that the `//` operator always returns an int when used on builtin types.

# Pitch

Opens the result of a floor-division involving float to the int API, which includes all the int methods on the one part, and the ability to be used in range, slices, list/tuple multiplication... on another part.
Floor division was first described as a true division followed by a call to `math.floor`, which got broken in PEP 3141 which changed math.floor's return type but seemingly forgot to change `float.__floordiv__`'s as well. This puts them back together.
Read the [PEP draft](https://demo.hedgedoc.org/ooJT0_iwQ9e0syCZ0xCiJA) - though this may not require a PEP - for a more fuller and detailed rationale.

# Previous discussion

[Make `float.__(i/r)floordiv__` return an int](https://discuss.python.org/t/make-float-i-r-floordiv-return-an-int/24959) on Ideas.

**Comment by JelleZijlstra** [comment]
Several core developers on the linked Discourse thread were skeptical about this proposal for various technical reasons. We shouldn't make this change without carefully considering these objections, and that will probably need a PEP.

**Comment by Gouvernathor** [comment]
I don't think this requires any compatibility mechanism bigger than the non-togglable one I outlined in the document.

When the random.seed function restricted the types it takes, and random.sample started rejecting sets and dicts, there was some transition period but no toggle between the old and the new behavior was introduced. It was the former one, right up until it was the new one. This is the most evident changes I could cite from my perspective, but there are surely dozens of other examples in various other parts of python.

I seriously doubt this change would break any more code than these changes to the random module did. Not to mention the deafening lack of documentation about this : nowhere in the doc is there any mention that `float.__floordiv__` does return a float, there are vague warnings at best. There is even a mistaken (or at least ambiguous) phrasing in the [divmod doc](https://docs.python.org/3/library/functions.html#divmod) implying that the first element, which is the same as the floordiv result, is "usually `math.floor(a / b)`", a.k.a an int ever since PEP 3141 was passed, and another equally dubious phrasing in 3141 itself (see the Discourse thread for more details).

Why would an undocumented behavior require such an extensive adaptative mechanism ?
If developers want to transition step by step, they can get the former and new behaviors by casting the calculation in the `int` or `float` callables, respectively. Yes, that would lose some execution time, but I guess that's the price to pay for relying on those. And these two recipes have the merit of existing and being very simple, as opposed to most if not all `__future__` toggles.

**Comment by mdickinson** [comment]
> the non-togglable one I outlined in the document [...]

I'm afraid that that section of the document is rather unclear to me. Could you please outline (here, not in the document) precisely which code (and under what conditions) would be expected to issue a `DeprecationWarning` during the proposed transition period?

**Comment by Gouvernathor** [comment]
It would be right about [here](https://github.com/python/cpython/blob/4307feaddc76b9e93cd38e325a1f0ee59d593093/Objects/floatobject.c#L731) (and the same in the float_divmod function, but let's keep that one on the side while we work the floordiv case).
After the `floordiv` result is computed, we do something similar to [this code](https://github.com/python/cpython/blob/main/Objects/longobject.c#L404-L411), by testing for infinity and nan-ness of the value and emit warnings if so.
That is for the period of time before any actual change is done to the values returned by the function.

In a second period of time, if we want to be extra-careful, we can have those ifs emit the warning and return the float-converted value, while the else (the normal behavior for non-infinity values of the `floordiv` variable) returns an int. That would make the operator still raise no exception but it would become mixed-types, so there are pros and cons about that.
But the main place where I would put deprecation warnings would be as said above, to warn about the non-int values.

**Comment by mdickinson** [comment]
Sorry, I meant which *Python* code. I'm asking about the user-visible behaviour change, not the implementation. That is, under what conditions should a Python _user_ expect a `DeprecationWarning` to be issued during the transition period? E.g., would every `x // y` operation in which both `x` and `y` are instances of float issue a warning?

> [...] other possible breaking points [...]

Indeed it's the type change that primarily concerns me much more than the behaviour of NaNs or infinities. The ramifications of that type change aren't limited to direct type checking in user code. As a random example, consider this NumPy-using session:

```python
Python 3.10.10 (main, Feb 10 2023, 08:56:54) [Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> (np.arange(1000000) * (1e40 // 1e10)).dtype
dtype('float64')
>>> (np.arange(1000000) * int(1e40 // 1e10)).dtype
dtype('O')
```

The second result is the result that we'd get under your proposal after the type change. And that's a _big_ difference: an efficient array of 1 million packed floats has become an inefficient array of pointers to unboxed integers. That's the sort of change which should not occur silently.

**Comment by Gouvernathor** [comment]
> an efficient array of 1 million packed floats has become an inefficient array of pointers to unboxed integers
Yes, but in other words, an array of imprecise values has become more precise. If developers (or modules, Numpy in this case) want to ignore that precision they should do so, Python shouldn't crop things in their place. For me that's a feature, not a bug - and I'll note it only degrades performance and does not yield errors.

> Note that last value in the result - in one case it's 2.; in the other it's something tiny.
I'm afraid I don't understand precisely how the problem happens. It's very weird that a calculation involving less floats and more ints makes it less accurate. It seems to be in the conversion of `y` back to a float before the multiplications occur ? And that the conversion doesn't yield a float equal to `x` ?
If so, the bug is there, either in the Python C implementation or in Numpy's, and in that case it's covered by the broad "float maths are inaccurate" blanket.
If the code as you wrote it, which means without using the `//` operator (but I understand your point of course), shows that weird inaccuracy, then it seems it could happen anytime anyway, so we shouldn't take it into account right here and now.

But of course if I misunderstood the second behavior it may be another bag of beans altogether.

**Comment by mdickinson** [comment]
> Yes, but in other words, an array of imprecise values has become more precise.

Okay, I give up. There are real issues here, but you see to want to wave them away rather than engage and try to solve them.

I recommend closing this issue.

**Comment by jamadagni** [comment]
Wow so much discussion has already happened! I'm just a Python end user who would like to reiterate the request for `float.__floordiv__` to return an `int` (and so that `divmod` also does so for the quotient component). 

My use case for wanting it as an `int` is mainly indexing using the quotient. I cannot claim widespread programming experience but I do not see any use for retaining it as a `float`. (I do not know about any other possible technical issues involved.)

**My use case**:

I am replicating old Indian methods of computing astronomical positions involving mathematical algorithms which use sexagesimal (and other non-decimal place) values. I implemented those values using my custom class internally using `float`, and procedures involve dividing one sexagesimal by another, noting the quotient (integer), dividing the remainder sexagesimal by yet another sexagesimal and so on, and taking the last quotient for indexing another table.

I attach an except from [the book](https://archive.org/details/vakyakaranawithlaghuparkasikasudararajaed.kuppannasastrit.s.sarmak.v._865_t/page/259/mode/1up) to illustrate the requirement:

![vakya-floordiv](https://github.com/user-attachments/assets/6f810751-bf5d-4873-8b55-c81869f17a5b)

Note the last line given which says to compute for the 12th cycle which means indexing from a list of tables.

I hope this gets resolved soon. Thanks!
