### ISSUE TITLE
Remove unused TKINTER_PROTECT_LOADTK code

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#103532]
The `TKINTER_PROTECT_LOADTK` macro and relevant code (originally for #49372) are only defined for Tk 8.4.13 and earlier, but Tkinter already requires at least 8.5.12. Is there a reason to keep this code around, or can it be removed?

### Linked PRs
* gh-103535
* gh-103542
* gh-103544

**Comment by zware** [comment]
Thanks for the report and patch!
