### ISSUE TITLE
Incorrect deduplication of Enum values in `Union[Literal[1], Literal[SomeEnum.one]]`

### ISSUE THREAD

**Issue by adriangb** [python/cpython#103592]
This was fixed on 3.9 (by https://github.com/python/cpython/pull/23294 or followups). Here's a test / example:

```python
from enum import Enum
from typing import Literal, Union, get_args


class MyEnum(int, Enum):
    foo = 1

tp = Union[Literal[MyEnum.foo], Literal[1]]
assert len(get_args(tp)) == 2, get_args(tp)

tp = Union[Literal[1], Literal[MyEnum.foo]]
assert len(get_args(tp)) == 2, get_args(tp)
```

These assertions fail on 3.8 since `Union` deduplicates both `Literal`s into the same thing. The reason you need `Literal` here is because enum values are values not types so they can only appear in a Union if they're also within a Literal.

As per https://github.com/python/cpython/pull/23294#issuecomment-728659310 maybe the answer here is to not do anything. And in fact I looked into back porting and it was too big of a change to be called a back port. But I didn't see *this specific* issue w/ Enum and Union reported, so I at least wanted to report it and confirm that it is a bug.

### Linked PRs
* gh-103706
* gh-103720

**Comment by JelleZijlstra** [comment]
3.8 is in security fix-only mode, so it's too late to fix this.

**Comment by adriangb** [comment]
Makes sense. I'll just close the issue then.

**Comment by adriangb** [comment]
Do you think we can change https://github.com/python/typing_extensions/blob/501a00e4701185ec93220155a0caa3da71d327e8/src/typing_extensions.py#L264-L268 to use the `typing-extensions` implementation for 3.8 as well?

**Comment by JelleZijlstra** [comment]
Yes, that makes sense to do.

**Comment by sobolevn** [comment]
`test_typing.py` police is here 🚨

This is not tested right now, in fact, `Literal` with `enum` is never tested at all.
Moreover, we don't have a single `Union[Literal, Literal, ...]` test at all.

Thanks a lot @adriangb for raising this.
PR with the fix is ready :)
