### ISSUE TITLE
TypeError: <lambda>() takes 1 positional argument but X were given

### ISSUE THREAD

**Issue by milahu** [python/cpython#103505]
# Bug report

wrapping and reassigning a function with lambda does not work as expected

somehow the right side of the assignment `lambda x: f(x, 0)` is using `f` from the left side of the assignment, effectively creating an infinite recursion in the assignment: the lambda function is trying to call itself

this looks like a wrong lazy-evaluation/late-binding/inlining of the lambda function (in the wrong scope). or, it is a limitation of lambda, because lambda does not create its own scope (function body) (compared to regular `def` functions)

```py
def f(a, b):
  return a + b

# wrap f with lambda, reassign to f
f = lambda x: f(x, 0)
f(0) # breaks: TypeError: <lambda>() takes 1 positional argument but 2 were given
# note: this only breaks when calling f

# workaround: rename the inner function
# this is also the expected behavior: lambda should store a private copy of f
_f = f; f = lambda x: _f(x, 0)
f(0) # works
```

regarding this error, there are some [posts on stackoverflow.com](https://stackoverflow.com/search?q=python+TypeError%3A+%3Clambda%3E%28%29+takes+positional+argument+but+were+given)

keywords: shadowing, replacing, same name

# Your environment

- CPython versions tested on: Python 3.10.9
- Operating system and architecture: x86_64 GNU/Linux

**Comment by ronaldoussoren** [comment]
This is not a bug, but expected behaviour.   ``lambda x: f(x, 0)`` does not bind ``f`` to the lambda object, but the name gets resolved when the lambda is called.

This is not different from:

```python3

def f(a, b):
   return a + b

def f(a):
    return f(a, 0)
```

The [FAQ entry about using lambda's in a for loop](https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result) gives some more background on the general behaviour and possible workarounds.

**Comment by milahu** [comment]
so lambda is actually a "lambda macro" (not a "lambda function")

so `f(0)` would expand to

```py
def f(a, b):
  return a + b
f = (lambda x: f(x, 0))

f(0)

(lambda x: f(x, 0))(0)
# 0

(lambda x: (lambda x: f(x, 0))(x, 0))(0)
# TypeError: <lambda>.<locals>.<lambda>() takes 1 positional argument but 2 were given

(lambda x: (lambda x: (lambda x: f(x, 0))(x, 0))(x, 0))(0)
# TypeError: <lambda>.<locals>.<lambda>() takes 1 positional argument but 2 were given

# ... infinite recursion via f
```

this also breaks with javascript arrow functions
with javascript's typical "infinite recursion" error, because extra arguments are ignored

```js
var f = (a, b) => a + b;
var f = (x) => f(x, 0);
f(0);
// Uncaught RangeError: Maximum call stack size exceeded
```

nothing to do here, i guess (closing)
