### ISSUE TITLE
Dangling references to argparse.REMAINDER

### ISSUE THREAD

**Issue by dansebcar** [python/cpython#103582]
# Documentation

In #61252, `argparse.REMAINDER` was removed from [the nargs documentation](https://docs.python.org/3.12/library/argparse.html#nargs) but there are still two references to the feature, one in [the table at the top](https://docs.python.org/3.12/library/argparse.html#quick-links-for-add-argument) and one in [the intermixed parsing section](https://docs.python.org/3.12/library/argparse.html#intermixed-parsing). I think they should also be removed to fully un-document the feature.

This also confused [some Reddit users](https://www.reddit.com/r/learnpython/comments/trhpow/undocumented_features_eg_argparseremainder/).

### Linked PRs
* gh-103586
* gh-103620

**Comment by terryjreedy** [comment]
@sobolevn

**Comment by sobolevn** [comment]
Thanks, I will take a look tomorrow.
