### ISSUE TITLE
The return type hint of __exit__ should be Optional[bool] instead of None

### ISSUE THREAD

**Issue by hansonchar** [python/cpython#103573]
# Bug report

Per [typecontextmanager](https://docs.python.org/3/library/stdtypes.html#typecontextmanager)
>Exit the runtime context and return a Boolean flag indicating if any exception that occurred should be suppressed.

In fact by empirical observation `__exit__` can return `None`, `False` and `True`.  However, [typing.py](https://github.com/python/cpython/blob/main/Lib/typing.py#L3314) shows that the return type hint is current specified as `None`, which contradicts the documentation and actual behavior.

# Your environment

- CPython versions tested on: Python 3.11.3
- Operating system and architecture: 
Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

**Comment by JelleZijlstra** [comment]
The annotation you point to is for `IO.__exit__`, and it is appropriate there to always return None. It would be highly unexpected if an IO class returned `True` in its `__exit__` method.

**Comment by hansonchar** [comment]
I encountered this issue when I was [coding](https://exercism.org/tracks/python/exercises/paasio/solutions/someknowit) against `io.BufferedRandom` and `socket`.  In both instances, I observed the `__exit__` method returned all three values under different conditions.

Seems this is a general typing issue of that method as currently defined at [typing.py](https://github.com/python/cpython/blob/main/Lib/typing.py#L3314)

**Comment by JelleZijlstra** [comment]
`socket.socket.__exit__` is defined at https://github.com/python/cpython/blob/main/Lib/socket.py#L240 and always returns None.

`BufferedRandom.__exit__` I believe is `iobase_exit` at https://github.com/python/cpython/blob/4fe1c4b97e39429abbb9c2117fe40f585de00887/Modules/_io/iobase.c#L469. It returns whatever close() returns, which also tends to be None (https://github.com/python/cpython/blob/4fe1c4b97e39429abbb9c2117fe40f585de00887/Modules/_io/iobase.c#L220).

**Comment by hansonchar** [comment]
Isn't it that the `__exit__` method can be wrapped/decorated by a wrapper class, and that wrapper class can choose to return `True`/`False` instead of `None`? 

My understanding is that this is the type of a general method, representing an interface/contract which the [doc](https://docs.python.org/3/library/stdtypes.html#typecontextmanager) indicates that it can return a boolean value.   The fact that specific implementation may always return `None` shouldn't result in altering the general interface/contract.

Arguably though if the general interface is defined at `Optional[boo]`, specific implementation should be able to override the method to return a co-variant type of, say, `None`.   But not vice-versa.

**Comment by JelleZijlstra** [comment]
Wrapper classes can return something else, but they'd break the contract of the `IO` class. Similarly, subclasses of `IO` could return something other than `IO[AnyStr]` from the `__enter__` method, but they'd break the contract of the class. That's what the type annotations mean.

**Comment by hansonchar** [comment]
As it stands, currently no new classes or implementation can return anything other than `None` with explicit type hint.  Otherwise, it would fail the static type check (e.g. `mypy`).

**Comment by JelleZijlstra** [comment]
That's only true for classes that inherit from `IO`. For general context managers, you can return whatever you want and mypy will be fine with it.

**Comment by hansonchar** [comment]
I see.  Interesting.  But the mocking tests used at [exercism](https://exercism.org/tracks/python/exercises/paasio/solutions/someknowit) does return `True`/`False` in the mocked IO classes; but what you are saying is that those test cases should never occur in the first place!

**Comment by hansonchar** [comment]
Thanks for the explanation.
