### ISSUE TITLE
Isolate _multibytecodec

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#103583]
### Linked PRs
* gh-103540
* gh-103588
* gh-103589
* gh-103868
* gh-103869
* gh-103870

**Comment by erlend-aasland** [comment]
In gh-103540 I've isolated \_multibytecodec. However, more steps are needed to isolate the \_codec\_\* (sub-ish) modules. I've identified some issues that IMO should be solved first, preferably in separate PRs:

- There is no reference dependency between the \_multibytecodec and the \_codecs\_\* modules. This is a problem, because the MultibyteCodecObject type (of the \_multibytecodec module) stores pointers to codec structs whose memory is owned by the \_codecs\_\* modules. IMO, this needs to be done anyway, so we can start here.
- We need a way to store global pointers to codecs and maps; one possibility is to expand the `MultibyteCodec` struct and pass that to the various mb handlers. Another possibility is to store these in \_codecs\_\* module state, store that state, for example in `MultibyteCodecObject`, and pass state to the mb handlers. Yet another possibility is to use the `config` member of `MultibyteCodec` for this, and change the semantics of that struct field.

Also, some low-hanging fruit that IMO can be done right now:

- We've got both `MultibyteCodec_State` and `_multibytecodec_state`. IMO, we should rename one of those; the current naming is too similar and confusing.
- `MultibyteCodec` pointers should be passed as `const`

**Comment by erlend-aasland** [comment]
cc. @corona10

**Comment by erlend-aasland** [comment]
> In [gh-103540](https://github.com/python/cpython/pull/103540) I've isolated _multibytecodec.

No, I haven't; I've only put the codec and map arrays into the \_codecs\* module state.

**Comment by erlend-aasland** [comment]
@corona10, I made three competing PRs for how to implement custom module state for the CJK modules. IMO, alternative 2 is the best approach. Alt 3 is way too complex (and currently, it does not even work). Alt 1 is too hacky.

cc. @kumaraditya303

**Comment by corona10** [comment]
@erlend-aasland I will take a look by tomorrow. ;)
