### ISSUE TITLE
Rewarded personal attacks and spurious issue closing

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#103521]
> Okay, I give up. There are real issues here, but you seem to want to wave them away rather than engage and try to solve them.
> 
> I recommend closing this issue.

_Originally posted by @mdickinson in https://github.com/python/cpython/issues/103445#issuecomment-1507229991_

This is a baseless, rude and derogatory attack on my character and motivations that in no way reflect the time and care I took to explain my views and discuss the problem at hand.
The issue was closed with no other base than these insults and in a way that's preventing me to answer and defend myself there.

The issue should be reopened without allowing such petty personal attacks to happen. This is a terrible climate to set on a collaboration-based project, that shuts good-faith contributions and propositions out and enable these abusive and authoritative behaviors. This demands a reaction. This kind of behavior should especially not be rewarded by submitting to the demands of the bullies - closing the issue, in this instance.

**Comment by JelleZijlstra** [comment]
The issue closure was appropriate and Mark's message focused on technical issues, not personal attacks.

**Comment by ethanfurman** [comment]
Here are instructions for [reporting a CoC violation](https://www.python.org/psf/conduct/reporting/).

As for the original PR, I suggest you go the PEP route.

**Comment by Gouvernathor** [comment]
> you seem to want to wave them away rather than engage and try to solve them

How is that related to a technical issue ? How is that not a personal attack, on my motivations and character ?

**Comment by mdickinson** [comment]
@Gouvernathor Yes, you're right. I lost patience, and responded when I should have sat on my hands. I apologise, and I withdraw the comment. I'll delete the comment from the issue.
