### ISSUE TITLE
debug f-strings (=) padding is erroneous

### ISSUE THREAD

**Issue by JohnnyNajera** [python/cpython#103522]
# Bug report
The developer pad all the strings to be of the same length for a nice view. However
```
>>> print(f'{people_in_the_room =:20}\n{furnitures_in_the_room =:20}\n{total =:20}')
people_in_the_room =                 123
furnitures_in_the_room =                  45
total =                 168
```

The varible names' lengths are not counted in the padding size. From a pure end-user perspective this is extremely weird. As in "why even supporting padding if it just doesn't work as expected?"

# Your environment
All supported versions.

# Solution

I suggest this syntax will generate an ExpressionValue object, which holds both the expression itself and its value. The formatter of the object will firstly receive specification regarding the debug print (padding, alignment, possibly in the future "table mode", etc.), and after that it will receive the internal format_spec for the internal object.
```python
result = f'{  my_number * 2.5 = :40:.2f}'
```
This should be equivalent to:
```python
temp_object = ExpressionValue(" my_number * 2.5", my_number * 2.5)
result = temp_object.format("40:.2f")
```
ExpressionValue is implemented as follows:
```python
class ExpressoinValue:

  def __init__(self, expression, value):
      self.expression = expression
      self.value = value

  def _format_internal(expression, value_formatted, format_spec):
      # .... 

  def __format__(self, format_spec):
     debug_expression_format, inner_value_format = format_spec.split(':', 1)
     value_formatted = self.value.format(inner_value_format)
     return _format_internal(self.expression, value_formatted, debug_expression_format)
```

This breaks compatibility with current formatted debug f-strings. But as these are only debug prints, I don't think it is too bad.

**Comment by pochmann** [comment]
> these are only debug prints

What makes you think that?

**Comment by JohnnyNajera** [comment]
> What makes you think that?

The formal specification refer to this as a [debug-expressions](https://peps.python.org/pep-0701/#handling-of-f-string-debug-expressions). But indeed there are backward compatibility issue here. If it is believed the suggestion breaks too much then it definitely it should not be implemented.

**Comment by sunmy2019** [comment]
Strong negative.

Implementing this is impossible in most cases.

* many values don't accept length in format spec.

e.g.
1. class that only implemented `__repr__`, but not `__format__`
2. with a customized `__format__`.

* it increases the complexity of the interpreter, which means it needs to find a way to tell the length to the format function.
It means the `__format__` is context-aware. This would break much compatibility.

**Comment by ericvsmith** [comment]
It's also the case that the format spec might not apply to strings at all. For example:

```pycon
>>> from datetime import *
>>> f'{datetime.now() = :%Y-%m-%d}'
'datetime.now() = 2023-04-13'
```

My point is that you can't just say "concatenate the expression text and the result, then apply the format spec to the result of that".

**Comment by JohnnyNajera** [comment]
@ericvsmith @sunmy2019 there is an inner format_spec, which is addressed to the inner object, and there is an outter format_spec, which applies to the ExpressionValue itself. The last example would be:
```
>>> f'{datetime.now() = :30:%Y-%m-%d}'
'datetime.now() =           2023-04-13'
```

**Comment by ericvsmith** [comment]
Ah, I see. I didn't realize you were proposing a new feature, I thought you were saying the current behavior is broken. I apologize for not reading so clearly.

You should probably bring this up on https://discuss.python.org/c/ideas/6 for more feedback.

A problem with reusing the colon is that's part of the format spec, and the formatting machinery passes it to the object's `__format__`. Your example is currently valid code:
```pycon
>>> f'{datetime.now() = :30:%Y-%m-%d}'
'datetime.now() = 30:2023-04-13'
```
That example is contrived, but how about:
```pycon
>>> f'{datetime.now() = :%Y-%m-%d %H:%M:%S}'
'datetime.now() = 2023-04-13 17:17:41'
```
There aren't really any characters we could hijack here in order to create the outer format spec.

**Comment by JohnnyNajera** [comment]
Thank you for the suggestion :) I will do that.

I think the colon is not a problem because I only split with maxsplit=1, and take the entire right-hand part into the internal formatter, completely untouched. The last example would be:
```
>>> f'{datetime.now() = :40:%Y-%m-%d %H:%M:%S}'
'datetime.now() =                         2023-04-13 17:17:41'
```

**Comment by ericvsmith** [comment]
But how do you know `%Y-%m-%d %H:%M:%S` isn't inner `%Y-%m-%d %H` and outer `%M:%S`? (Or maybe I have the terminology backward).

**Comment by JohnnyNajera** [comment]
@ericvsmith because the outter format_spec is the format of my ExpressionValue. I can decide it has no colons in it, other than the one which marks the beginning of the inner format_spec. 

(Of course this is just one possible example of such encoding.)

**Comment by ericvsmith** [comment]
Breaking compatibility is a non-starter.

**Comment by JohnnyNajera** [comment]
@ericvsmith so finding a new syntax for this? maybe even a syntax for printing a few expressions at once?

or do you have some other completely different idea?

**Comment by hauntsaninja** [comment]
Like Eric said, https://discuss.python.org/c/ideas/6 is a better place for brainstorming new syntax or features
