### ISSUE TITLE
perf maps address format

### ISSUE THREAD

**Issue by art049** [python/cpython#103650]
# Bug report

As implemented by @pablogsal in #96123 we can now generate perf maps(which is awesome BTW).
Currently, perf maps are formatted this way:
```
0x58c5882 b py::<module>:/home/arthur/Projects/python-playground/dummy_script.py
0x58c588d b py::baz:/home/arthur/Projects/python-playground/dummy_script.py
0x58c5898 b py::bar:/home/arthur/Projects/python-playground/dummy_script.py
0x58c58a3 b py::foo:/home/arthur/Projects/python-playground/dummy_script.py
```

However, as per the [perf maps interface specification](https://github.com/torvalds/linux/blob/master/tools/perf/Documentation/jit-interface.txt) it seems the address should not include the leading `0x`. 

Thus the perf map should look like this:
```
58c5882 b py::<module>:/home/arthur/Projects/python-playground/dummy_script.py
58c588d b py::baz:/home/arthur/Projects/python-playground/dummy_script.py
58c5898 b py::bar:/home/arthur/Projects/python-playground/dummy_script.py
58c58a3 b py::foo:/home/arthur/Projects/python-playground/dummy_script.py
```
 
Still, it works fine with `perf` but might not with other tools not handling this leading `0x`.

# Your environment

- CPython versions tested on: 3.12.0a7
- Operating system and architecture: Manjaro 22.1.0 x86_64

### Linked PRs
* gh-103651

**Comment by terryjreedy** [comment]
@pablogsal The perf doc says that perf map start addresses (as well as sizes) are hex numbers without '0x'.  The implementation prints them with '0x'.  Which is wrong?  There is a PR to change the implementation.

**Comment by hauntsaninja** [comment]
Closing since #103651 was merged
