### ISSUE TITLE
Help finding replacement for MessageSource

### ISSUE THREAD

**Issue by juniartisu** [python/cpython#103603]
Hi,
Looks like MessageSource is being deleted in this issue https://hg.python.org/jython/rev/ec1b1e701776
Is there a replacement to it? 
Thanks for your help in advance.

**Comment by hugovk** [comment]
Hi, that's a commit in the Jython code and this is the issue tracker for the CPython project.

I suggest you ask at the Jython issue tracker: https://github.com/jython/jython/issues/
