### ISSUE TITLE
IDLE - Update code with pyupgrade

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#103668]
Item 7 for #87179.  In https://github.com/python/cpython/issues/87179#issuecomment-1093900180, Anthony Sottile suggestted running his program [pyupgrade](https://pypi.org/project/pyupgrade/), which automates code updates.  It would have done some of the things already done and will do some more.  In response to my query, he said on another comment that it has been well tested on multiple packages to only do valid changes.  His comment includes a bash command:
`git ls-files -- Lib/idlelib | grep '\\.py$' | xargs pyupgrade --py36-plus`
 On Windows, use pyupgrade-directories or try above with git bash on idlelib and idle_test.

### Linked PRs
* gh-103671
* gh-103730

**Comment by sobolevn** [comment]
Two notes:
1. `--py36-plus` -> `--py311-plus`
2. It is a good practice to run `pyugrade` multiple times (until there are no new changes produced, because it might upgrade stuff several times: `%` -> `.format` -> `f''`)

I've sent a demo PR (feel free to close if the diff is too large / not useful).
