### ISSUE TITLE
Implement PEP 692

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#103629]
PEP-692 was accepted, but without the syntax change. That means there's very little to do in CPython, but a few changes should be made:

- https://docs.python.org/3.12/library/typing.html#typing.Unpack should mention this new use for Unpack
- https://docs.python.org/3.12/whatsnew/3.12.html should mention the PEP
- Maybe some aspects of `typing.py` assume Unpack is only used for PEP 646 and should be updated

And maybe something else I'm forgetting.

cc @franekmagiera

### Linked PRs
* gh-103894
* gh-104048

**Comment by franekmagiera** [comment]
Thanks Jelle! I will try to find time to pick some of this up after the weekend.

**Comment by franekmagiera** [comment]
When it comes to `typing.py` - the `repr` for `Unpack` needs to be updated - I will try to do that and also add an entry in `whatsnew` later this week (in separate PRs).

**Comment by franekmagiera** [comment]
[typing rtd](https://typing.readthedocs.io/en/latest/) already mentions PEP 692, also added a PR to update [mypy's cheatsheet](https://github.com/python/mypy/pull/15163)

**Comment by AlexWaygood** [comment]
I think we're done here! Easiest typing PEP to implement that I've been involved with 😄
