### ISSUE TITLE
Inconsistent `AttributeError` messages for private names

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#103623]
I am not sure if this is a bug or not, and since I was not able to find existing duplicates I will report it anyway.

When you try to access a private attribute outside of the class body, you get a correct error message:

```python
>>> class A: ...
... 
>>> print(A().__a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'A' object has no attribute '__a'
```

But, inisde the class body the error message changes:

```python
>>> class B:
...    def __init__(self):
...        print(self.__a)
... 
>>> B()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
AttributeError: 'B' object has no attribute '_B__a'
```

I don't think that showing a mangled name here is the best idea.
In my opinion `AttributeError: 'B' object has no attribute '__a'` would be better here.

But, there are probably reasons why this behavior exists.

I would like to hear other opinions :)

If this is indeed should be improved, I would like to work on it.

**Comment by corona10** [comment]
@pablogsal is the expert for this kinds of developer experience issues

**Comment by sunmy2019** [comment]
Private name mangling happens during compile time, especially during AST -> byte code.

Showing the mangle here indicates what the Interpreter is trying to do. For example,

```py
__a = 1
class A:
    def __init__(self):
        print(__a)
```
```
NameError: name '_A__a' is not defined
```

**Comment by terryjreedy** [comment]
I agree.  A class should be tested before being released to other users, and that testing should cover the use of private names.
