### ISSUE TITLE
Memory error in calendar.isleap

### ISSUE THREAD

**Issue by baltsers** [python/cpython#103687]
# Bug report

We did a fuzzing test on Python3.9.15, a memory error happened.

```
from calendar import *
import calendar
import argparse

class demoCls():

    def __init__(self):
        pass

    def demoFunc(self, arg):
        try:
            ret = calendar.isleap(arg)
        except (AssertionError, AttributeError, LookupError, OSError, TypeError, ValueError, argparse.ArgumentError, argparse.ArgumentTypeError, calendar.IllegalMonthError, calendar.IllegalWeekdayError) as e:
            pass

year = b'%444444444444reduce_depth44444444444444444444444F'
dc = demoCls()
dc.demoFunc(year)
```
[details](https://github.com/baltsers/fuzzVuls/tree/master/Python3.9.15/calendar.isleap)

## Bug info
```
    #1 0x499621 in PyMem_RawMalloc /root/CpyFuzz/experiments/Python-3.9.15/Objects/obmalloc.c:572:12
    #2 0x499621 in _PyObject_Malloc /root/CpyFuzz/experiments/Python-3.9.15/Objects/obmalloc.c:1645:11
    #3 0x41f83e in _PyBytes_FromSize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:81:31
    #4 0x41f83e in PyBytes_FromStringAndSize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:112:27
    #5 0x428506 in _PyBytesWriter_Resize /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:3348:30
    #6 0x422faa in _PyBytesWriter_Prepare /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:3401:15
    #7 0x422faa in _PyBytes_FormatEx /root/CpyFuzz/experiments/Python-3.9.15/Objects/bytesobject.c:962:23
    #8 0x6be614 in binary_op1 /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:869:13
    #9 0x6bec07 in binary_op /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:898:24
    #10 0x6bec07 in PyNumber_Remainder /root/CpyFuzz/experiments/Python-3.9.15/Objects/abstract.c:1086:12
    #11 0x55606a in _PyEval_EvalFrameDefault /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:1676:21
    #12 0x43336f in _PyEval_EvalFrame /root/CpyFuzz/experiments/Python-3.9.15/./Include/internal/pycore_ceval.h:40:12
    #13 0x43336f in function_code_fastcall /root/CpyFuzz/experiments/Python-3.9.15/Objects/call.c:330:24
    #14 0x5635fd in _PyObject_VectorcallTstate /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:118:11
    #15 0x5635fd in PyObject_Vectorcall /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:127:12
    #16 0x5635fd in call_function /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:5077:13
    #17 0x55d8bf in _PyEval_EvalFrameDefault /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:3489:23
    #18 0x43336f in _PyEval_EvalFrame /root/CpyFuzz/experiments/Python-3.9.15/./Include/internal/pycore_ceval.h:40:12
    #19 0x43336f in function_code_fastcall /root/CpyFuzz/experiments/Python-3.9.15/Objects/call.c:330:24
    #20 0x5635fd in _PyObject_VectorcallTstate /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:118:11
    #21 0x5635fd in PyObject_Vectorcall /root/CpyFuzz/experiments/Python-3.9.15/./Include/cpython/abstract.h:127:12
    #22 0x5635fd in call_function /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:5077:13
    #23 0x55d897 in _PyEval_EvalFrameDefault /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:3506:23
    #24 0x565264 in _PyEval_EvalFrame /root/CpyFuzz/experiments/Python-3.9.15/./Include/internal/pycore_ceval.h:40:12
    #25 0x565264 in _PyEval_EvalCode /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4329:14
    #26 0x554061 in _PyEval_EvalCodeWithName /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4361:12
    #27 0x554061 in PyEval_EvalCodeEx /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:4377:12
    #28 0x554061 in PyEval_EvalCode /root/CpyFuzz/experiments/Python-3.9.15/Python/ceval.c:828:12
    #29 0x5d2367 in run_eval_code_obj /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1221:9
    #30 0x5d2367 in run_mod /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1242:19
    #31 0x5d2367 in pyrun_file /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:1140:15
    #32 0x5cedc6 in pyrun_simple_file /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:450:13
    #33 0x5cedc6 in PyRun_SimpleFileExFlags /root/CpyFuzz/experiments/Python-3.9.15/Python/pythonrun.c:483:15
    #34 0x41e1fd in pymain_run_file /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:373:15
    #35 0x41e1fd in pymain_run_python /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:598:21
    #36 0x41e1fd in Py_RunMain /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:677:5
    #37 0x41ea66 in pymain_main /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:707:12
    #38 0x41ead2 in Py_BytesMain /root/CpyFuzz/experiments/Python-3.9.15/Modules/main.c:731:12
    #39 0x7fa91a5bac86 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21c86)
```

# My environment

CPython: 3.9.15
Ubuntu: 18.0.4 (x86 64)

**Comment by ronaldoussoren** [comment]
I can reproduce the crash with python3.11 on macOS, but haven't tried to debug.

**Comment by sunmy2019** [comment]
If the year has type `bytes`, `year % 4` is a format string then.

Your format string has a `%444444444444r`. This causes a memory error. (string too long)

**Comment by sunmy2019** [comment]
Either `'%444444444444r' % 4` or `f"{4:444444444444}"` will cause the same memory error.

Maybe a type check of `year` can be added here.

**Comment by ronaldoussoren** [comment]
The following seems to be a minimal reproducer:

```python3

b'%444444444444r' % 4
```

This gives the same backtrace for me, and is based on the code that's executing in the OP's example. For me the crash happens in ``_PyBytes_FormatEx``, likely due to the large field width.

**Comment by sunmy2019** [comment]
> likely due to the large field width.

It requires 414GB memory.

**Comment by ronaldoussoren** [comment]
> Either `'%444444444444r' % 4` or `f"{4:444444444444}"` will cause the same memory error.
> 
> Maybe a type check of `year` can be added here.

At least on macOS this is a C-level crash, and should be fixed. Adding a type check to ``calendar.isleap`` would just hide the problem.

**Comment by sunmy2019** [comment]
> At least on macOS this is a C-level crash, and should be fixed.

Oh, on Linux, a null pointer will be returned by the malloc. It exits gracefully.

It is possible that macOS malloc lib did not handle it properly. It sounds like a check is required before calling malloc.

Shouldn't there be similar issues with large memory requests on macOS?

**Comment by ronaldoussoren** [comment]
> > At least on macOS this is a C-level crash, and should be fixed.
> 
> Oh, on Linux, a null pointer will be returned by the malloc. It exits gracefully.

Interesting, is there a limit on the amount of memory a proces may allocate on. your system? I'd expect malloc to work fine for this on a 64-bit system, but running into problems when actually trying to use the memory unless the system has a huge amount of RAM or swap.


> 
> It is possible that macOS malloc lib did not handle it properly. It sounds like a check is required before calling malloc.
> 
> Shouldn't there be similar issues with large memory requests on macOS?

Looking someone deeper, this appears to be related to an OOM killer on macOS, I get the following in system logging when trying to allocate a large amount of memory:

```
low swap: killing largest compressed process with pid 48169 (Python) and size 70404 MB
```

I get a MemoryError when doing the same while limiting the amount of memory that can be used using ``ulimit -v``.

Which brings this into "don't do that then" territory.

**Comment by terryjreedy** [comment]
Module calendar has undocumented IllegalMonthError and IllegalWeekdayError (for bad int values).  They should be documented.  

Given that the mod bug has been twice reported on other issues, I think this issue should be to add a type check it isyear.
```
c.isleap('%4r')
False
```
should raise `TypeError: year must be int, not type(year)` instead of returning.

Also check other calendar functions that use `argument % int` expressions.

**Comment by ronaldoussoren** [comment]
@baltsers : All issues you are filing are basically the same: your script tries to allocate a very large amount of memory and fails because of that, either with a MemoryError if the process is constrained or by being killed by the OOM killer when it is not constrained.

This is not something the Python interpreter can guard against, memory allocations functions (e.g. malloc(3)) will succeed if there's free address space and the proces will crash later on when trying to use that address space when there's not enough available RAM and swap space.

**Comment by sunmy2019** [comment]
> Interesting, is there a limit on the amount of memory a proces may allocate on. your system?

I think there would be one. On my mac
```py
"%111111111111111r" % 1    # memory error
"%11111111111111r" % 1     # killed by OOM killer
```
