### ISSUE TITLE
Allow separators in `attrgetter`

### ISSUE THREAD

**Issue by ruddra** [python/cpython#103622]
# Enhancement

__I propose an enhancement based on this issue [#46151](https://github.com/python/cpython/issues/46151).__

Currently `attrgetter` accepts dotted path while getting attributes from an object. I propose it should not only accept dotted paths, but other separators as well. Like this:

```python
operator.attrgetter(obj, "a.b")  # default behavior
operator.attrgetter(obj, "a__b", separator='__')  # enhanced behavior
```

# Pitch

Allowing different types of separators in `attrgetter` will help users by a nested attribute path which is not dotted (could be something else such as underscore, or slash).

# Previous discussion

https://discuss.python.org/t/allow-separators-in-attrgetter/25992/1

**Comment by sobolevn** [comment]
Is there any benefit in having this over `operator.attrgetter(obj, "a__b".replace("__", "."))`?

**Comment by ruddra** [comment]
Of course, I do not have to run additional operation before passing the argument to the function. It yields maybe a very little performance improvement (negligible) but it makes the implementation of the function much simpler. For, if I have multiple arguments, I have to make the replace operation multiple times. 

```
a = attrgetter('a__b'.replace("__", '.'), 'a__c'.replace('__', '.'), 'a__d'.replace('__', '.'), 'a__e'.replace('__', '.'))
```

Of course that can be fixed with a map function but its still additional operations. Aside from that, from the source code, the change would be pretty simple:

class attrgetter:
   ...
    __slots__ = ('_attrs', '_call')

    def __init__(self, attr, *attrs, sep="."):
       ...
      names = attr.split(sep)
```

About the discussion link, it seems Akismet has blocked it because I tried to edit the post right after I posted it in the discussion. It is saying the post will be online as soon as someone reviews it.

**Comment by terryjreedy** [comment]
I don't really get why you would want to type 'a___b' (triple underscore?) instead of 'a.b'.  Seems like a needless complication.

**Comment by sobolevn** [comment]
This is quite common in Django, because this is how queries are defined.

But, I still think that converting `__` to `.` is simple enough in user-space and no new parameters are required here.

**Comment by terryjreedy** [comment]
I am closing this at least for now because opening this issue an hour after the same proposal was posted to discuss is premature.  The point of asking people to post to discuss instead is to develop them and get support before putting them on our work list.

**Comment by terryjreedy** [comment]
I posted some of my objections on the discussion and pointed out there that `.replace('__', '.'), if needed more than once, can be put in a function with a short name.
