### ISSUE TITLE
Unhelpful error message from logging.config.FileConfig can be improved

### ISSUE THREAD

**Issue by vsajip** [python/cpython#103606]
# Feature or enhancement

If a configuration file does not exist, the error raised by `logging.config.fileConfig` doesn't say that the file doesn't exist, instead suggesting that the file has an invalid format. This should be improved so that the correct error message is provided. 

# Pitch

The improved error message will guide a user to an error such as a typo in the filename more quickly. See for example [this question](https://stackoverflow.com/questions/76026274).

### Linked PRs
* gh-103628
* gh-104687
* gh-104701

**Comment by Agent-Hellboy** [comment]
Hi, @vsajip can I try to fix this?

**Comment by arhadthedev** [comment]
@Agent-Hellboy It's an open project, no preliminary assignment is required. The only thing you need is to follow the contributor's manual at https://devguide.python.org/ where conventions and processes are described.

**Comment by Agent-Hellboy** [comment]
okay, sure

**Comment by Agent-Hellboy** [comment]
Hi @arhadthedev 
my approach would be to check the return value of `cp.read(fname, encoding=encoding)` 
https://github.com/python/cpython/blob/d1e4917e06d5638f1a7fa189d6d63ec9c2a27753/Lib/logging/config.py#L71
It uses `configparser` to parse the configuration files which suppresses the OSError but it returns an empty list if the file is not present
https://github.com/python/cpython/blob/d1e4917e06d5638f1a7fa189d6d63ec9c2a27753/Lib/configparser.py#L665
I will raise and PR which will raise ValueError that the file is not present and will try to include a test for the same

**Comment by vsajip** [comment]
Wouldn't it be simpler to use e.g. `os.path.exists()` and then throw a `FileNotFoundError` if the file doesn't exist? That would be the approach I would have taken.

**Comment by arhadthedev** [comment]
Because of the *easier to ask for forgiveness than permission* principle [with the very `os.path.exists()` as an example](https://docs.quantifiedcode.com/python-anti-patterns/readability/asking_for_permission_instead_of_forgiveness_when_working_with_files.html):

```python
import os

# violates EAFP coding style
if os.path.exists("file.txt"):
    os.unlink("file.txt")
```

**Comment by vsajip** [comment]
Yes, but the "file not found" message/`FileNotFound` exception are more informative than a generic "invalid file" when the file doesn't exist. It's a small point, I suppose; it's easier to ask for forgiveness, but that doesn't mean it's a cast-iron rule.

**Comment by Agent-Hellboy** [comment]
okay, I will raise FileNotFound before giving the file to the config parser 
https://github.com/python/cpython/blob/6be7aee18c5b8e639103df951d0d277f4b46f902/Lib/logging/config.py#L63
`why should I try to parse a file which is not present`

**Comment by gpshead** [comment]
I left some comments on the merged PR... ValueError isn't the right exception to use for things external to the process not related to the variable value itself.  I suggest RuntimeError if you don't have your own Error exception class.

**Comment by Agent-Hellboy** [comment]
sure @gpshead, I will raise a PR

**Comment by gpshead** [comment]
thanks!
