### ISSUE TITLE
Tk 8.7: TIP 577 breaks tkinter.Menu.index()

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#103685]
# Bug report

One effect of [TIP 577](https://core.tcl-lang.org/tips/doc/trunk/tip/577.md) is that as of Tk 8.7, the `index` command for menus will now return an empty string instead of `none`, leading to an error in `tkinter.Menu.index()`:

```
>>> m.index('none')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/git/cpython/Lib/tkinter/__init__.py", line 3434, in index
    return self.tk.getint(i)
           ^^^^^^^^^^^^^^^^^
_tkinter.TclError: expected integer but got ""
```

It should be easy to accommodate both the new and old behavior.

### Linked PRs
* gh-103686
* gh-103734

**Comment by terryjreedy** [comment]
Thanks for making a start on preparing for 8.7+ & 9.0+
