### ISSUE TITLE
Invalid arument error for datetime.timestamp() method in windows

### ISSUE THREAD

**Issue by subindevs** [python/cpython#103648]
# Bug report

In Windows 10 for  a datetime.datetime class if the year value is greater than 3001, then the timestamp() method returns  invalid argument error.
```
File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
```
## Reproducible example
```python
>>> from datetime import datetime
>>> max_time = datetime(year=9000,month=1,day=1,hour=0,minute=0,second=0)
>>> max_time.timestamp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 22] Invalid argument
>>>
```

# Your environment

- CPython versions tested on: Python 3.11.3
- Operating system and architecture: Windows 10, 64bit
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32

### Linked PRs
* gh-103653

**Comment by pochmann** [comment]
I think you'd better point out the bug more clearly (that it raises `OSError` instead of the [documented](https://docs.python.org/3/library/datetime.html#datetime.datetime.timestamp) `OverflowError`).

**Comment by gaogaotiantian** [comment]
Basically on Windows we simply raises `OSError` when `localtime_s()` fails. I fixed it in #103653 and waiting for the review now.

**Comment by akulakov** [comment]
From microsoft docs, for reference:
https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/localtime-localtime32-localtime64?view=msvc-170

[returns NULL, causing OSError currently]

> After 23:59:59, December 31, 3000, UTC (using _time64 and __time64_t).

**Comment by vstinner** [comment]
I close the issue: see https://github.com/python/cpython/pull/103653#issuecomment-1773722601
