### ISSUE TITLE
Implement and document PEP 713

### ISSUE THREAD

**Issue by amyreese** [python/cpython#103741]
# Feature or enhancement

- [PEP 713: Callable Modules](https://peps.python.org/pep-0713/)
- [Discussion](https://peps.python.org/pep-0713/)

- [ ] Implement method for calling modules' `__call__` objects if they exist
- [ ] Add test cases covering callable and non-callable modules
- [ ] Document new interfaces and changes as described in the PEP

### Linked PRs
* gh-103742

**Comment by hugovk** [comment]
We can close this issue now as the PEP was rejected in the end. But thank you anyway!
