### ISSUE TITLE
Python appears to degrade Windows 10 functionality, eventually requiring reboot

### ISSUE THREAD

**Issue by DManowitz** [python/cpython#103738]
# Bug report

Python (or some commonly used python library or possibly something else, but definitely tied to Python usage) appears to cause degradation of Windows features.  As python is run more times, various Windows features will stop working, and eventually I'll need to reboot, at which point all Windows features work again.  Some of the issues I've seen are the following:

* Windows clipboard does not function correctly, especially in Firefox, although eventually Excel may report not being able to correctly use the clipboard.   Other programs can access the Windows clipboard correctly, though (especially those that only copy/paste plain text).
* Trying to launching a processes or open a file via double-clicking a file in Explorer does not launch the appropriate program or open the specified file.
* Programs will not launch from the Start Menu.
* Programs will not be able to open new windows.
* The speaker/headphones indicator icon in the taskbar indicates no available audio device, even though at least one is available, and can be used via appropriate programs already open (e.g., iTunes, Spotify)
* The screen blanks out and does not show anything, except an arrow with hourglass pointer (which will move in response to the mouse) for an extended period.  I don't know if it would ever recover from this; I always end up rebooting if this happens.

I first experienced these issues while setting up environments using the [Mamba package installer](https://mamba.readthedocs.io/en/latest/), so I initially thought this was a Mamba issue.  However, I then started to see the same issues when using Conda, and then when just using a plain Python interpreter.

I mostly use a base conda environment set up with Python 3.9, and I've created environments with Python 3.7 & 3.8 and experienced these issues using any of them, so at least any combination of these Python versions seem to be able to cause these problems.

I haven't seen any other reports of such issues or experienced them on any other machine that I've used python on previously, but I can consistently reproduce them on my current personal laptop, and only when I run python or python-based programs.  Thus, there may be some interplay between python and some other program(s) I have running, or this may even be a Windows bug, but I'm not sure how to potentially diagnose which other program(s) might be the culprit, so I'm hoping someone might have some ideas here.

# Your environment

- CPython versions tested on: 3.7, 3.8, 3.9
- Operating system and architecture: Windows 10 x86_64, versions 21H2 and 22H2.

**Comment by terryjreedy** [comment]
I use python.org CPython and IDLE for days without reboot and have not seen much of what you claim.  Possibly a bug in something you use leaves zombie python processes.  There have been patches to fix such when traced to something specific.  Use Task Manager to check.

**Comment by gpshead** [comment]
I suggest taking this up on a Python users forum. This is someone asking for help, there's nothing actionable in this report.
