### ISSUE TITLE
Remove `🤖 automerge`

### ISSUE THREAD

**Issue by arhadthedev** [python/cpython#103739]
According to https://github.com/python/core-workflow/issues/498#issuecomment-1502516107, the following steps must be done:

1. https://github.com/python/cpython/pull/103337
1. Enable "Allow automerge" repo option on `cpython`, `devguide`, `peps` and `core-workflow`
1. https://github.com/python/devguide/pull/1082, https://github.com/python/devguide/issues/1079
1. *This PR is here*
1. https://github.com/python/miss-islington/pull/610

Since step 5 was implemented before step 3 (and, probably, step 2), we cannot postpone removal of the https://github.com/python/cpython/labels/%3Arobot%3A%20automerge. Otherwise, [core developers will continue to apply no longer working label](https://github.com/python/miss-islington/issues/458#issuecomment-1518941527).

**Comment by sobolevn** [comment]
сс @ezio-melotti

**Comment by hugovk** [comment]
> Since step 5 was implemented before step 3 (and, probably, step 2),

Step 5 was merged on Thursday and step 2 was enabled on Wednesday. Sorry we didn't post about it in the issue.

Anyway, yes, let's remove the label now.

**Comment by hugovk** [comment]
And I have permissions to delete labels, so have deleted it. 🗑️

**Comment by arhadthedev** [comment]
For backup purposes: the label looked like this:

![](https://user-images.githubusercontent.com/4881073/234081509-4b8646c2-f944-42ea-b52b-987f77e9d60d.png)

Because after I closed the tab, it's gone.
