### ISSUE TITLE
ast.unparse not working. Throwing error like AttributeError: 'assign' object has no attribute 'lineno'.

### ISSUE THREAD

**Issue by ankit-gautam23** [python/cpython#103768]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by yujiecong** [comment]
```
import ast


func_call = ast.Expr(value=ast.Assign(
    targets=[ast.Name(id='r', ctx=ast.Store())],
    value=ast.Call(
        func=ast.Name(id='func', ctx=ast.Load())
        args=[
            ast.Name(id='a', ctx=ast.Load()), 
            ast.Name(id='b', ctx=ast.Load()), 
            ast.Name(id='c', ctx=ast.Load()), 
        ],
        keywords=[]))
)

```

func_call_code = ast.unparse(func_call)

print(func_call_code)

**The above code will raise an error in both Python 3.9.13 and 3.11.3. The call stack is as follows.**

```

3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Traceback (most recent call last):
  File "D:\learning\pyviz\test\test-ast.py", line 64, in <module>
    func_call_code = ast.unparse(func_call)
                     ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 1708, in unparse
    return unparser.visit(ast_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 818, in visit
    self.traverse(node)
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 809, in traverse
    super().visit(node)
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 848, in visit_Expr
    self.traverse(node.value)
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 809, in traverse
    super().visit(node)
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 418, in visit
    return visitor(node)
           ^^^^^^^^^^^^^
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 876, in visit_Assign
    if type_comment := self.get_type_comment(node):
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 800, in get_type_comment
    comment = self._type_ignores.get(node.lineno) or node.type_comment
                                     ^^^^^^^^^^^
AttributeError: 'Assign' object has no attribute 'lineno'
```

hope i can help you

**Comment by yujiecong** [comment]
> ```
> import ast
> 
> 
> func_call = ast.Expr(value=ast.Assign(
>     targets=[ast.Name(id='r', ctx=ast.Store())],
>     value=ast.Call(
>         func=ast.Name(id='func', ctx=ast.Load())
>         args=[
>             ast.Name(id='a', ctx=ast.Load()), 
>             ast.Name(id='b', ctx=ast.Load()), 
>             ast.Name(id='c', ctx=ast.Load()), 
>         ],
>         keywords=[]))
> )
> 
> func_call_code = ast.unparse(func_call)
> 
> print(func_call_code)
> ```
> 
> **The above code will raise an error in both Python 3.9.13 and 3.11.3. The call stack is as follows.**
> 
> ```
> 
> 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
> Traceback (most recent call last):
>   File "D:\learning\pyviz\test\test-ast.py", line 64, in <module>
>     func_call_code = ast.unparse(func_call)
>                      ^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 1708, in unparse
>     return unparser.visit(ast_obj)
>            ^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 818, in visit
>     self.traverse(node)
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 809, in traverse
>     super().visit(node)
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 418, in visit
>     return visitor(node)
>            ^^^^^^^^^^^^^
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 848, in visit_Expr
>     self.traverse(node.value)
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 809, in traverse
>     super().visit(node)
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 418, in visit
>     return visitor(node)
>            ^^^^^^^^^^^^^
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 876, in visit_Assign
>     if type_comment := self.get_type_comment(node):
>                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "C:\Users\yjc\AppData\Local\Programs\Python\Python311\Lib\ast.py", line 800, in get_type_comment
>     comment = self._type_ignores.get(node.lineno) or node.type_comment
>                                      ^^^^^^^^^^^
> AttributeError: 'Assign' object has no attribute 'lineno'
> ```
> 
> hope i can help you
> 
> By the way, this code is generated by ChatGPT, but it clearly wouldn't fix such an error, funny.

and finally i found how to do

just .

```
func_call_code = ast.unparse(ast.fix_missing_locations(func_call))

print(func_call_code)

```
it's done

**Comment by iritkatriel** [comment]
Yeah, ChatGPT is not a very good programmer.
