### ISSUE TITLE
Python3 erroneously calls r'\' a syntax error

### ISSUE THREAD

**Issue by greg1lutz** [python/cpython#103704]
The Python 3.11.3 interpreter, upon seeing the expression
r'\\'
emits the message
SyntaxError: unterminated string literal

**Comment by hauntsaninja** [comment]
Thanks, but this isn't a bug.

This is documented at this FAQ: https://docs.python.org/3/faq/programming.html#can-i-end-a-raw-string-with-an-odd-number-of-backslashes

It's also mentioned at https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

**Comment by terryjreedy** [comment]
@greg1lutz Please ask whether behaviors are bugs on the [discuss](https://discuss.python.org) help channel.

**Comment by hauntsaninja** [comment]
Oh one more note is that I'd opened #100446 to explore ways to improve the error message, although that PR is in limbo because it will likely conflict with PEP 701 changes
