### ISSUE TITLE
Empty unclosed f-string does not directly raise a SyntaxError in the REPL

### ISSUE THREAD

**Issue by lysnikolaou** [python/cpython#103727]
# Bug report

This is another bug introduced in https://github.com/python/cpython/commit/1ef61cf71a218c71860ff6aecf0fd51edb8b65dc. When typing an empty single-quoted unclosed f-string in the REPL, another line is added and input is expected, before a `SyntaxError` is raised.

Before https://github.com/python/cpython/commit/1ef61cf71a218c71860ff6aecf0fd51edb8b65dc:
```python3
❯ ./python.exe 
Python 3.12.0a7+ (tags/v3.12.0a7-153-ga6b07b5a34:a6b07b5a34, Apr 23 2023, 13:18:40) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f'
  File "<stdin>", line 1
    f'
    ^
SyntaxError: unterminated string literal (detected at line 1)
```

Current main:
```python3
❯ ./python.exe 
Python 3.12.0a7+ (heads/main:05b3ce7339, Apr 23 2023, 13:26:24) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> f"
... 
  File "<stdin>", line 1
    f"
    ^
SyntaxError: unterminated f-string literal (detected at line 2)
>>> f"
... asdnc
  File "<stdin>", line 1
    f"
    ^
SyntaxError: unterminated f-string literal (detected at line 2)
>>> f"
... asdasd"
  File "<stdin>", line 1
    f"
    ^
SyntaxError: unterminated f-string literal (detected at line 2)
```

### Linked PRs
* gh-103775

**Comment by terryjreedy** [comment]
In IDLE, which uses code.interactive_interpreter, which ultimately uses codeop._maybe_compile,  I get 'SyntaxError: incomplete input' in installed 3.12.0a7 and the new message *at line 1* in fresh repository 3.12.0a7+.

**Comment by lysnikolaou** [comment]
`codeop._maybe_compile` uses `compile`, which doesn't encounter the problem mentioned here.

It's got to do with the interactive mode, where we advance the tokenizer far enough (to backup again afterwards) that a newline character is not enough for the syntax error to be emitted.
