### ISSUE TITLE
Remove recognition of "procbody" Tcl value type

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#103735]
Ever since #36111, Tkinter has checked for Tcl values with the "procbody" type, presumably because it was (and still is) one of the registered types or listed in tclInt.h. But this type is not interesting to Tkinter: any values of this type are wrapped with `_tkinter.Tcl_Obj` just as if they were of an unrecognized type. I suggest that Tkinter not cache this type or check for values using it.

### Linked PRs
* gh-103736

**Comment by serhiy-storchaka** [comment]
Agree. It was never used, and I do not even see how it can be used.
