### ISSUE TITLE
Implement PEP 695

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#103763]
We should implement PEP-695. Some discussion of the implementation is at https://github.com/erictraut/cpython/issues. I will open a draft PR momentarily.

TODO:
- [ ] Evaluate TypeAlias values
- [ ] Lazy evaluation for TypeVar bounds
- [ ] More tests
- [ ] Fix remaining tests in test_typing.py

### Linked PRs
* gh-103764

**Comment by sunmy2019** [comment]
Wow. This syntax looks so cool. It reminds me of many generic expressions in other languages, such as C++ and Rust. (while the increases the learning curve of Python)

I'll see what I can help here.

**Comment by preveen-stack** [comment]
I feel we should defend the intuitive readability of python irrespective of what.

**Comment by JelleZijlstra** [comment]
The implementation is done. The next step is #103921, the documentation.

**Comment by JelleZijlstra** [comment]
I don't expect more major changes, no. There are currently no open PEP 695-related bugs; if anything else changes it would be as a result of new feedback we receive during the beta phase.
