### ISSUE TITLE
ASAN false positives due to vfork() with GCC 9

### ISSUE THREAD

**Issue by colesbury** [python/cpython#103726]
Older versions of ASAN don't properly support `vfork()`. Python uses `vfork()` when available in `_posixsubprocess.c`. This can lead to false positive reports from ASAN.  I believe this issue exists with GCC 9 (and older), but not GCC 10 (and newer). The CPython GitHub actions ASAN runner currently uses GCC 9.4.0, so it does not properly handle vfork().

I've seen these false positives in my nogil-3.12 fork. I'm unsure if you've run into them upstream.

See https://github.com/google/sanitizers/issues/925

https://github.com/python/cpython/blob/5041c2ba6e9c992d1c54834481c9be64581c0235/Modules/_posixsubprocess.c#L43-L49

### Linked PRs
* gh-103728
* gh-104794

**Comment by corona10** [comment]
@colesbury Can I take a look at it?

**Comment by gpshead** [comment]
bonus points if this can be done only under compiler versions known too old to ASAN the vfork code path so that we retain coverage of what actually gets used when possible.

**Comment by corona10** [comment]
> The CPython GitHub actions ASAN runner currently uses GCC 9.4.0, so it does not properly handle vfork().

But if I understand the issue correctly, what about just upgrading the GCC version by using the apt command for the ASAN tests.

**Comment by corona10** [comment]
Ah okay, now I understood what the title meant `Disable vfork() when running under ASAN`.
It will be great if we can only disable vfork() under ASAN for old gcc versions.

**Comment by colesbury** [comment]
> Can I take a look at it?

@corona10 - that would be great.

> bonus points if this can be done only under compiler versions known too old to ASAN the vfork code path

We might also want to check the Clang version. I believe that [Clang 9.0](https://github.com/llvm/llvm-project/blob/llvmorg-9.0.1/compiler-rt/include/sanitizer/hwasan_interface.h#L53-L55) and newer support vfork() properly:

> But if I understand the issue correctly, what about just upgrading the GCC version by using the apt command for the ASAN tests?

That should work, but that means that if someone is running ASAN with an older compiler locally they may run into false positives. (That might be OK -- we could instruct people to use a newer compiler). I'm not sure which approach is better.

**Comment by gpshead** [comment]
i'm not too worried about people using old toolchains for modern features such as ASAN. Our advice can simply be "upgrade". In my potentially biased experience people who understand what sanitizers are want the recent features and fixes for those to get more accurate results. So if just upgrading our CI and bot configs to use a more recent version is all it takes, sounds good to me.

**Comment by corona10** [comment]
>  So if just upgrading our CI and bot configs to use a more recent version is all it takes, sounds good to me.

+1, I will submit the PR for it

**Comment by corona10** [comment]
@arhadthedev I think that this is highly related to build rather than extension modules.

**Comment by colesbury** [comment]
I edited the issue title - I hope this is more clear (and doesn't confuse things).

**Comment by corona10** [comment]
Close the issue. Thanks for the report @colesbury
