### ISSUE TITLE
sprintf deprecation warning on macOS for datetimemodule

### ISSUE THREAD

**Issue by corona10** [python/cpython#103733]
## How to reproduce
````
./configure --with-address-sanitizer && make
`````

## Deprecation warning
````
./Modules/_datetimemodule.c:1566:9: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
        sprintf(freplacement, "%06d", 0);
````

**Comment by corona10** [comment]
cc @ned-deily @pganssle

**Comment by corona10** [comment]
I expect that the solution will not be hard, so I label the issue as `easy`

**Comment by pganssle** [comment]
Seems like a good sprint issue? Assuming we can detect this in the tests easily or otherwise verify the fix.

**Comment by arhadthedev** [comment]
Can `PyOS_snprintf()` be a drop-in replacement here?

**Comment by corona10** [comment]
> Seems like a good sprint issue? Assuming we can detect this in the tests easily or otherwise verify the fix.

I will happy that it can be used for the sprint issue.

**Comment by arhadthedev** [comment]
A parent issue: gh-101703.
