### ISSUE TITLE
Python removes negative ranges from dictionaries

### ISSUE THREAD

**Issue by wnakhleh** [python/cpython#103750]
# Bug report

Python removes negative ranges from dictionaries

Example to reproduce:
```Python
print({range(16, 1): 0.5, range(32, 16): 0.5})
```

The expected output:
 > {range(16, 1): 0.5, range(32, 16): 0.5}

The actual output:
>  {range(16, 1): 0.5}

# Your environment

- CPython versions tested on: 3.10, 3.7.6
- Operating system and architecture: WIN11+linux

**Comment by Eclips4** [comment]
However, this seems interesting:
```python
>>> a = {range(16, 1): 1}
>>> a[range(32, 16)] = 2
>>> a
{range(16, 1): 2}
```

**Comment by Eclips4** [comment]
> Python removes negative ranges from dictionaries

You misunderstood something. Python doesn't remove anything from dictionary. 
```python
hash(range(32, 16)) == hash(range(16, 1))
> True
# And there's need a check for objects equality 
range(32, 16) == range(16, 1)
> True
```
So, after this checks, Python decides to change the value of key.
