### ISSUE TITLE
Remove `#ifdef TCL_WIDE_INT_TYPE` usage

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#103731]
In Tcl 8.4 and later, tcl.h has always provided `TCL_WIDE_INT_TYPE`, `Tcl_WideInt`, and `Tcl_WideUInt`. Since Tkinter requires 8.5.12, it is okay for `AsObj()` to use `Tcl_WideInt` without checking if `TCL_WIDE_INT_TYPE` is defined. `Tcl_WideInt` is already used without similar `#ifdef`s in `fromWideIntObj()`.

### Linked PRs
* gh-103732

**Comment by serhiy-storchaka** [comment]
You are right. TCL_WIDE_INT_TYPE is defined and undefined several times in tcl.h, but finally it is always defined.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @chrstphrchvz.
