### ISSUE TITLE
Let's be explicit: is asyncio.Task.cancel() thread-safe?

### ISSUE THREAD

**Issue by dimaqq** [python/cpython#103819]
# Documentation

Is `asyncio.Task.cancel()` thread-safe or not?

The class is marked as not thread-safe, so maybe not?

Yet, the example in "Scheduling from Other Threads" seems to call `future.cancel()` from another thread?

Digging a bit deeper, `.cancel()` only schedules task for cancellation, so maybe it's OK?

The internet search yields inconclusive results. The ChtaGtp claims thread safety, but I wouldn't trust it.

Specifically, if code in another thread needs to cancel some task, is that code supposed to call `asyncio.run_coroutine_threadsafe(some_task.cancel)`?

**Comment by gvanrossum** [comment]
Nothing in asyncio is threadsafe unless explicitly documented as being threadsafe.

**Comment by dimaqq** [comment]
Thank you for the concise answer.

I feel that documentation could be improved still. 🙏🏻 

It was quite confusing for me, it's bound to be moreso for new Python users.
