### ISSUE TITLE
Improve `builtins.__doc__`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#103886]
```pycon
>>> import builtins
>>> print(builtins.__doc__)
Built-in functions, exceptions, and other objects.

Noteworthy: None is the `nil' object; Ellipsis represents `...' in slices.
>>> 
```

A few possible improvements:
- `None` is not actually in the builtins module, as it's a keyword
- `Ellipsis` has more uses than just slices
- The docstring doesn't explain what "builtins" means. It should say that this module is special in that its namespace is always available, or something along those lines.

### Linked PRs
* gh-104179
* gh-104257

**Comment by tomasr8** [comment]
I guess we could reuse (to some degree) the [builtins documentation](https://docs.python.org/3/library/builtins.html)?

**Comment by JelleZijlstra** [comment]
Much better now, thanks @tomasr8!

**Comment by tomasr8** [comment]
Thanks for the review!
