### ISSUE TITLE
Return newly added Enum constants for month and days in calendar module 

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#103822]
# Pitch
As discussed with @ethanfurman in one of my PR, I am going to create a PR to change the return type of functions and methods which currently return ints from 0-7 and 1-12 to represent days and months to newly added enum attributes 

# Previous discussion
the previous discussion can be tracked from the last comment on #103642

### Linked PRs
* gh-103827

**Comment by hauntsaninja** [comment]
Thanks!
