### ISSUE TITLE
Issues when showing broken `Exception.__notes__`

### ISSUE THREAD

**Issue by pR0Ps** [python/cpython#103895]
# Bug report

When [notes on an exception](https://docs.python.org/3/library/exceptions.html#BaseException.__notes__) cannot be shown because the `repr` and `str` raise exceptions, a `<note str() failed>` message is shown instead. In the case where `exception.__notes__` is not a sequence and cannot be shown, a `<__notes__ repr() failed>` is shown. In the second case, the message does not include a trailing newline.

`__notes__` is a list containing a broken "note" - output includes a newline:
```python
class A:
    def __repr__(self):
        raise Exception()

e = Exception()
e.__notes__ = [A()]  # !!!
raise e
```
```
user@host $ ./repro.py
Traceback (most recent call last):
  File "./repro.py", line 8, in <module>
    raise e
Exception
<note str() failed>
user@host $ 
```

`__notes__` is just a single broken "note" - output does not include a newline:
```python
class A:
    def __repr__(self):
        raise Exception()

e = Exception()
e.__notes__ = A()  # !!!
raise e
```
```
user@host $ ./repro.py
Traceback (most recent call last):
  File "./repro.py", line 8, in <module>
    raise e
Exception
<__notes__ repr() failed>user@host $ 
```

Additionally, when `__notes__` is a string/bytes, the contents are expoded over multiple lines because of an `isinstance(__notes__, Sequence)` check.

String:
```python
e = Exception()
e.__notes__ = "a note"
raise e
```
```
user@host $ ./repro.py
Traceback (most recent call last):
  File "./repro.py", line 8, in <module>
    raise e
Exception
a

n
o
t
e
user@host $ 
```

Bytes:
```python
e = Exception()
e.__notes__ = b"a note"
raise e
```
```
user@host $ ./repro.py
Traceback (most recent call last):
  File "./repro.py", line 8, in <module>
    raise e
Exception
97
32
110
111
116
101
user@host $ 
```

Even though the above are all edge cases, since there are some checks that handle these cases already, it makes sense to handle them more gracefully.

# Your environment

- CPython versions tested on: 3.12.0a7+
- Operating system and architecture: macOS Mojave (x86)

### Linked PRs
* gh-103897

**Comment by gaogaotiantian** [comment]
Is ``Exception.__notes__`` supposed to be directly written? ``add_note()`` is definitely the recommended interface to use the feature. The docs mentioned ``__notes__`` as a "list of the notes", and is breaking that a "corner case", or simply the wrong way to use it?

**Comment by pR0Ps** [comment]
It is not supposed to be directly written (as far as I can tell), but while I was experimenting with some unrelated exception handling I was digging into this and noticed the inconsistency with the newlines so I figured I'd make a quick patch.

The only reason I bothered at all is because there's already some amount of handling of invalid notes so it seems it's at least been considered that someone may write `Exception.__notes__` directly.

**Comment by iritkatriel** [comment]
Merged into 3.12. Leaving open pending decision about backporting to 3.11.

**Comment by iritkatriel** [comment]
Assigned to @ambv for a backport decision.

**Comment by hugovk** [comment]
@ambv Shall we backport or close this issue?
