### ISSUE TITLE
Python/C API "PyUnicode_FromObject" is listed in the "Deprecated " section

### ISSUE THREAD

**Issue by Hizuru3** [python/cpython#103883]
In the documentation of Python 3.11 (or earlier), the Python/C API "PyUnicode_FromObject" is listed in the "Deprecated Py_UNICODE APIs" section, which is marked to be removed in version 3.12:

https://docs.python.org/3.11/c-api/unicode.html#deprecated-py-unicode-apis

However, the API seems not to get removed from neither of the actual implementation nor the documentation in Python 3.12. PEP 623 (https://peps.python.org/pep-0623/) doesn't even mention "PyUnicode_FromObject" as deprecated.

I suspect it is an error of the documentation, or did I miss something else?

### Linked PRs
* gh-103913
* gh-103915

**Comment by sunmy2019** [comment]
It's more like nobody remembers this or cares about this.

**Comment by arhadthedev** [comment]
> It's more like nobody remembers this or cares about this.

Linux/BSD end users will be confused after CPython 3.12.0 is out.

**Comment by arhadthedev** [comment]
@methane (as an author and implementer of pep-0623).

**Comment by methane** [comment]
pep 623 doesn't affect to PyUnicode_FromObject.

**Comment by methane** [comment]
OK, this is 12 year old bug, since PEP 393.
https://github.com/python/cpython/commit/db6c7f5c33ba4808907f227d5996ca70a67e21c6

**Comment by methane** [comment]
Even though this issue is disappeared in main branch, it is better to move this API to other "creating Unicode object" APIs.
