### ISSUE TITLE
`logging`: use `snake_case` naming style and use `camelCase` only as deprecated aliases

### ISSUE THREAD

**Issue by PedanticHacker** [python/cpython#103834]
# Feature or enhancement

The `logging` module does not follow Python's `snake_case` naming style for functions/methods, as recommended by PEP 8. For example, `logging` has a `setLevel()` method as oppose to having a `set_level()` method.

For example, the `threading` module has adopted the `snake_case` naming style, but is preserving the old `camelCase` names as deprecated aliases.

# Pitch

In the same manner, I think `logging` should follow suit. The `logging` module should have `snake_case` method names, as per PEP 8, and should preserve the `camelCase` method names as deprecated aliases.

**Comment by JelleZijlstra** [comment]
This would be a huge disruptive change and we're unlikely to make the change at this point. If you feel strongly about this, open a discussion on https://discuss.python.org, but it's very unlikely this will be accepted.

**Comment by terryjreedy** [comment]
`threading.stack_size` was added in 2.5 instead of `stackSize`.  Looking ahead to 3.0, snake_case versions of camelCase names were added in 2.6.  The latter were deprecated but left in 3.0 itself.  That transition was a special case.
