### ISSUE TITLE
Just a quick question

### ISSUE THREAD

**Issue by ChillVibesMushroom** [python/cpython#103854]
I'm running python3 in a virtual environment where I have to install certain packages but I have to run the tool as a super user with sudo because some operations are not permitted I can install the packages required as super user or root user and that wouldn't inpact anything outside my python3 venv right .

**Comment by zitterbewegung** [comment]
@ChillVibesMushroom hi this is for raising issues about the development of python and not on how to use it. You are welcome to ask this on https://www.pythondiscord.com
