### ISSUE TITLE
ipadx/ipady Only Pad right/bottom on tkinter Frame with Grid Layout Manager

### ISSUE THREAD

**Issue by Rybec** [python/cpython#103862]
# Bug report

Using the Grid layout manager to place a Frame, the ipadx and ipady options only produce padding on the bottom and right sides.

As you can see in the following code, I'm not adding padding anywhere else.  Widgets are stuck to sides (and bottom, in one case) for alignment.  When executed, this only adds the specified padding to the right and bottom inside edges of the Frame.

This bug has been reproduced by at least three others as well, as early as Feb. 2019.  Two of these were with Frames, but one also happened with a ListBox, so it seems Frames aren't the only place this happens:

[https://python-forum.io/thread-16243.html](https://python-forum.io/thread-16243.html)
[https://stackoverflow.com/questions/68406658/bug-in-tkinter-inner-padding-ipadx-ipady-only-works-on-right-side-and-botto](https://stackoverflow.com/questions/68406658/bug-in-tkinter-inner-padding-ipadx-ipady-only-works-on-right-side-and-botto)
[https://stackoverflow.com/questions/72848582/python-tkinter-ipad-on-grid-only-pads-the-right-and-bottom-side](https://stackoverflow.com/questions/72848582/python-tkinter-ipad-on-grid-only-pads-the-right-and-bottom-side)

This is my code that produces the error (however the bug also occurs if the frame is placed via the Grid manager directly after it is created, but before any elements are added):

```
import tkinter as tk


window = tk.Tk()


frame = tk.Frame(master=window,
                 relief=tk.GROOVE,
                 borderwidth=3)

label = tk.Label(text="Text should go in here:", master=frame)

entry = tk.Entry(width=20, master=frame)

button = tk.Button(text="This button",
                   background="#000000",
                   foreground="#FFFFFF",
                   height=0,
                   width=0,
                   master=frame)

label.grid(row=0, column=0, sticky="w")
entry.grid(row=1, column=0, sticky="w")
button.grid(row=2, column=0, sticky="se")

frame.grid(row=0, column=0, ipadx=5, ipady=5)  # !!! Padding added here !!!


window.mainloop()
```

# Your environment

- CPython versions tested on: 3.9.2
- Operating system and architecture: Debian GNU/Linux 11 (bullseye), x86-64 (Intel)
- Window Manager/Desktop: LXDE

I was able to work around this bug by padding the internal elements, on the relevant sides only, however this is tedious and error prone, especially if I need to add additional elements (which I will, because this is just the initial testing/learning phase).

(On a side note, I'm curious why padx and pady can take two-tuples to specify different padding for each side, but ipadx and ipaxy can't.  That seems like a massive oversight.  Is this just a limit of Tk itself (in which case I'm being curious in the wrong place...)?)

**Comment by terryjreedy** [comment]
Please edit your code to the simplest possible that dependably exhibits the issue.  To determine whether this is a tk issue or a tkinter issue, someone would have to translate it to tcl/tk and run with tcl/tk.  My guess is that it is a tk issue.  Someone could also check tk bug reports.

**Comment by Rybec** [comment]
I think this is about as simple as it can get.  The window is tiny, but it's even more obvious that there's padding on the bottom and right sides but not the left or top.  (I also just tested this with the pack layout manager.  The bug apparently manifests with both grid and pack layout managers.  I attempted to test the "place" manager, but it doesn't have the ipad_ arguments, it threw an exception.)

I hope this helps!


```
import tkinter as tk

window = tk.Tk()
frame = tk.Frame(master=window)
label = tk.Label(text="label", master=frame)

label.grid(row=0, column=0)
frame.grid(row=0, column=0, ipadx=5, ipady=5)  # Same bug with frame.pack(ipadx=5, ipady=5) 

window.mainloop()
```

**Comment by oehhar** [comment]
It might be good to follow the discussion on the Tk side here:
[Tk ticket 58cdb943](https://core.tcl-lang.org/tk/info/58cdb943bed892a6)

**Comment by terryjreedy** [comment]
Harold, thank you for submitting the tk tickets.  Nothing for us to do here.

**Comment by oehhar** [comment]
Tk Wizard Francois gave the following comment:

I don't think there is a bug. Difference between -padx and -ipadx is subtle, as explained in [TkDocs](https://tkdocs.com/tutorial/grid.html). Please read this page, it provides a lot of valuable insights.

You seem to expect to see Button2 to be centered inside .frame2 but this is not what you specify using -ipadx/y. I readily admit it's not easy to grasp.

My personal way to solve the task would be to give padx/y to the button, so always use extenal padding.

Proposals to improve the documentation are welcome.

Thank you all,
Harald

**Comment by oehhar** [comment]
Another topic. I tried to motivate some TkInter user for the [OpenACS/TCL/Tk](https://openacs.org/conf2023/info/) user meeting in Vienna, without any feed-back. Eventually, some people may consider to participate at the Tk pannel on Friday remotely, what will be possible for free.

Feel free to delete this advertisment. It is a desperate try anyway.

**Comment by serhiy-storchaka** [comment]
In any case this is not a Python issue. It is not something caused by wrong translation from Python to Tcl/Tk, and we cannot change this from our side.
