### ISSUE TITLE
Running the Docs workflow via workflow_dispatch always fails

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#103884]
Our Docs workflow file allows people to manually trigger the workflow on arbitrary branches in their GitHub fork of CPython:

https://github.com/python/cpython/blob/6c4124d11ab731f3774e3454ded33df089bd317e/.github/workflows/doc.yml#L1-L4

This is a useful feature that I like to use in order to test possible changes prior to filing a PR. However, on latest `main`, while it is still _possible_ to run the Docs workflow via the `workflow_dispatch`, it now always fails if you try to do so. Example failing run on my GitHub fork: https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105.

The error occurs in the "Get list of changed files" step here (added to the workflow in #102513):

https://github.com/python/cpython/blob/6c4124d11ab731f3774e3454ded33df089bd317e/.github/workflows/doc.yml#L57-L62

The error message is:

```
Run Ana06/get-changed-files@v[2](https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105#step:8:2).2.0
  with:
    filter: Doc/**
    token: ***
    format: space-delimited
  env:
    pythonLocation: /opt/hostedtoolcache/Python/[3](https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105#step:8:3).11.3/x6[4](https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105#step:8:4)
    PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.3/x[6](https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105#step:8:6)4/lib/pkgconfig
    Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.[11](https://github.com/AlexWaygood/cpython/actions/runs/4803232831/jobs/8547528105#step:8:11).3/x64
    Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.3/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
Error: This action only supports pull requests and pushes, workflow_dispatch events are not supported. Please submit an issue on this action's GitHub repo if you believe this in correct.
Base commit: undefined
Head commit: undefined
Error: The base and head commits are missing from the payload for this workflow_dispatch event. Please submit an issue on this action's GitHub repo.
Error: Not Found
```

While this isn't a _huge_ problem, it would be nice if we could continue to be able to run the Docs workflow via the `workflow_dispatch` trigger without it failing.

Cc. @hugovk, @ezio-melotti, @CAM-Gerlach

### Linked PRs
* gh-103889

**Comment by hugovk** [comment]
Yep, we can't get the list of files changed in a PR, when _not_ running as a PR :)

Let's add some logic to skip this bit for non-PRs:

https://github.com/python/cpython/blob/d45225bd66a8123e4a30314c627f2586293ba532/.github/workflows/doc.yml#L57-L70

**Comment by hugovk** [comment]
Fixed in https://github.com/python/cpython/pull/103889, thanks for the report!

**Comment by AlexWaygood** [comment]
Thanks for the lightning-quick fix!
