### ISSUE TITLE
Add missing tests to the dis module

### ISSUE THREAD

**Issue by jkchandalia** [python/cpython#103804]
Improve test coverage for the dis module i.e `cpython/lib/dis.py`, tests are in `cpython/Lib/tests/test_dis.py`. Missing tests include:

- `dis.disco`
- `dis.findlinestarts`

### Linked PRs
* gh-103806
* gh-103901

**Comment by nanjekyejoannah** [comment]
@jkchandalia can you discuss your motivation for `dis.disco` being covered before we close this? I didnt follow your email very well.

**Comment by jkchandalia** [comment]
@nanjekyejoannah I had a look at `dis.disco` which is the other function we mentioned in the issue. It looks like `disco = disassemble` and only exists only for backward compatibility which is what I see here: https://github.com/python/cpython/blob/b934f97850b7b2db30fa2b26720d58aac4783149/Lib/dis.py#L608

Because `dis.disassemble` appears to be thoroughly tested, I was wondering if we don't need to write tests for disco explicitly?

**Comment by iritkatriel** [comment]
disco is documented: https://docs.python.org/3/library/dis.html#dis.disco
so strictly speaking it should be tested. 

Perhaps it should also be deprecated, I don't know the history.

**Comment by jkchandalia** [comment]
@iritkatriel @nanjekyejoannah it looks like dis.disco was introduced in the initial python commit in 1990 by Guido: https://github.com/python/cpython/commit/217a5fa3c33ae58c1fe420f94eeb7e806961c3c1

I'm assuming it's been kept around for backwards compatibility and may not yet be a good idea to deprecate but I defer to your judgement. I've opened a PR with a test for `dis.disco` assuming we want to keep this around.
