### ISSUE TITLE
Broken test in test_genericalias

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#103880]
The test at https://github.com/python/cpython/blob/1c0a9c5a1c84bc334f2bde9d45676f19d9632823/Lib/test/test_genericalias.py#L315 has multiple statements in one `with self.assertRaises` block. This is bad, because the test will pass if only one of them raises. Presumably, we want a separate `with` for every statement.

At work, I implemented a lint rule that enforces that for our equivalent of `assertRaises`, there is only one statement within the `with` block. We could use the same pattern to look for other instances of this problem in our codebase.

cc @sobolevn as this may be of interest to you 

### Linked PRs
* gh-103916
* gh-103917

**Comment by sobolevn** [comment]
I can also change pure `assert` to be `self.assert*`

**Comment by sobolevn** [comment]
There are none raw `assert` statements in `test_genericalias`, but there are multiple in `test_types`, this will wait for the next time.
