### ISSUE TITLE
strip function bug

### ISSUE THREAD

**Issue by mirrornight** [python/cpython#103830]
# Bug report
example 
```
Python 3.9.13 (main, Aug 11 2022, 13:40:36) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> print('Baar ayJ0eXAiOiJKV1QiLCJ2ZXIiO'.strip('Baar '))
yJ0eXAiOiJKV1QiLCJ2ZXIiO
```
string missing character "a"

**Comment by rhettinger** [comment]
This isn't a bug.  The `strip()` method removes all contiguous occurences of the set of characters in the argument.  I think you want the `removeprefix` method instead.
