### ISSUE TITLE
Test documentation with the oldest supported Sphinx version

### ISSUE THREAD

**Issue by AA-Turner** [python/cpython#103903]
As we've discussed at various points recently, it would be of some use to have an automatic test that the minimum Sphinx version that we advertise in ``Doc/conf.py`` actually works. See PR for a new GitHub Actions job to test this on all documentation changes.

A

### Linked PRs
* gh-103904
* gh-103948

**Comment by AlexWaygood** [comment]
Thanks @AA-Turner!
