### ISSUE TITLE
Window width can be manipulated in a way that should not happen when resizing is partially restricted

### ISSUE THREAD

**Issue by AirplaneA220** [python/cpython#103938]
**Code:**
`1 import tkinter as tk              `
`2                                   `
`3 main_window = tk.Tk()             `
`4                                   `
`5 main_window.title('Title')        `
`6 main_window.geometry('250x100')   `
`7 main_window.resizable(False, True)`
`8                                   `
`9 main_window.mainloop()            `

**How to replicate:**
1) Run the code above on Windows 10/11
2) When the window opens spam `Win + Right Arrow`
3) You should see the window size expand horizontally

**Expected Behaviour:**
The window should not be able to be resized horizontally, only vertically

**Observed Behaviour:**
The window is able to expand horizontally

**Comment by terryjreedy** [comment]
Win key + other key behavior is defined by Microsoft and likely handled directly by Windows and not by tk, let alone tkinter.  Other app windows behave the same as a tkinter window.
