### ISSUE TITLE
Unexpected TypeError using matching (PEP 622, 634)

### ISSUE THREAD

**Issue by mfsjr** [python/cpython#103930]
# Bug report
I'm matching a str to a str and getting "TypeError('called match pattern must be a type')".   This seems to be what PEP 634 describes as a literal matching pattern, but let me apologize in advance if I'm missing something stupid.  I wasn't expecting an error, and even then, I don't understand what the TypeError is saying.

I have a simplified code sample below...

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

    admin_groups: dict[str, str] = {'dev': 'is_admin', 'test': 'is_admin_test'}
    groups: list[str] = ['is_admin']
    roles: list[str] = []
    
    for group in groups:
        if group == admin_groups.get('dev'):
            roles.append(group)
    print(f"using if: {str(roles)}")  # using if: ['is_admin']
    
    for group in groups:
        match group:
            case admin_groups.get('dev'):  # TypeError('called match pattern must be a type')
                roles.append(group)
    print(f"using match: {str(roles)}")

# Your environment

- CPython versions tested on:  Python v3.11.2
- Operating system and architecture:  OSX Big Sur v11.6.8 (Intel)

Running locally:

    $ python ./test/temp.py
    using if: ['is_admin']
    Traceback (most recent call last):
      File "/Users/mfsjr/PycharmProjects/update/update_ws/./test/temp.py", line 17, in <module>
        case admin_groups.get('dev'):  # TypeError('called match pattern must be a type')
             ^^^^^^^^^^^^^^^^^^^^^^^
    TypeError: called match pattern must be a type

**Comment by Ksmal37** [comment]
I don't think you can use functions in a match pattern

**Comment by mfsjr** [comment]
If that's the explanation then I can go with it, but the docs are actually using classes though:

class Point:
    x: int
    y: int

def location(point):
    match point:
        case Point(x=0, y=0):
            print("Origin is the point's location.")
        case Point(x=0, y=y):
            print(f"Y={y} and the point is on the y-axis.")
        case Point(x=x, y=0):
            print(f"X={x} and the point is on the x-axis.")
        case Point():
            print("The point is located somewhere else on the plane.")
        case _:
            print("Not a point")

**Comment by Ksmal37** [comment]
As far as i know the classes in match case dont create instances, the class type is compared against the match and its attributes

**Comment by sobolevn** [comment]
`TypeError: called match pattern must be a type` is exactly the error you should get here.

You cannot use a function call in a match pattern.

**Comment by mfsjr** [comment]
Ok, thank you
