### ISSUE TITLE
Revert/improve the restriction on using non-ThreadPoolExecutor

### ISSUE THREAD

**Issue by antoscha** [python/cpython#103920]
# Feature or enhancement

Allow custom pool executors to be passed in `loop.set_default_executor`.

# Pitch

As an example, I can give an executor provided by `mpi4py` project allowing to utilize all CPUs without GIL limitations and across all nodes in a cluster. The change accepted in https://github.com/python/cpython/issues/87400 breaks the feature, so I'd like to suggest to improve the prohibition.  
`MPIPoolExecutor` works for me without any issues in Python<3.11: https://github.com/mpi4py/mpi4py/issues/350

**Comment by gvanrossum** [comment]
So the problem with using a process pool executor as the *default* executor is that the asyncio event loop occasionally uses that for things like DNS lookup.

It is also likely that other libraries built on top of asyncio might use the default executor in a way that would be broken by using a process pool executor.

Instead, you can explicitly pass the process pool executor of your choice to [`run_in_executor`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor`). If you do this all the time, write a helper function.

Setting the default executor is mostly useful to be able to configure the number of threads in the pool. The semantics of process pool executors are sufficiently different that I don't believe "works for me" is a high enough bar.
