### ISSUE TITLE
array slices negative weirdness

### ISSUE THREAD

**Issue by kelvinwop** [python/cpython#103964]
# Bug report

![image](https://user-images.githubusercontent.com/30770221/235062416-97bae659-eb16-4d86-9d43-94e2023ca8ee.png)

# Your environment

Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by sobolevn** [comment]
I looks correct to me.

Maybe this example will show you whats happening:

```python
>>> a = [0, 1, 2, 3, 4]
>>> # Direct index:
>>> #     0  1  2  3  4
>>> # Backward index:
>>> #    -5 -4 -3 -2 -1
```

So, now let's analyze some cases:

```python
>>> a[2:-5:-1]
[2, 1]
```

So, we start at `[2]` and move to `[-5]` (not including) which are: `2` and `0` respectively.
To include the last index:

```python
>>> a[2:-6:-1]
[2, 1, 0]
```

But, when moving from `[1]` to `[-2]` there are no values:

```python
>>> # Direct index:
>>> #     0  1  2  3  4
>>> # Backward index:
>>> #    -5 -4 -3 -2 -1
>>> a[1:-2:-1]
[]
```

I hope that this helps :)
If you agree, please feel free to close this issue.

**Comment by hugovk** [comment]
I'd already typed this when @sobolevn replied, so hopefully this helps as another angle :)

---

`s[i:j:k]` means "slice of _s_ from _i_ to _j_ with step _k_"

And:

> If _i_ or _j_ is negative, the index is relative to the end of sequence _s_: `len(s) + i` or `len(s) + j` is substituted.

https://docs.python.org/3/library/stdtypes.html#common-sequence-operations

So `a[5:-11:-1]` is a slice from position 5 to 100-11 = 89, with step -1, or going backwards.

But we can never get from 5 to 89 by stepping backwards, we need to step forwards, so we get an empty list `[]`.

---

Next, `a[5:-100:-1]` means slice from 5 to 100-100 = 0, stepping backwards by 1. We stop just before getting to the end point, so don't include the item from position 0 and get `[5, 4, 3, 2, 1]`.

---

Finally, `a[5:-101:-1]` is like the previous one, but the stopping point is one further, so we now get the item at position 0: `[5, 4, 3, 2, 1, 0]`.

**Comment by terryjreedy** [comment]
I believe that the confusion comes from thinking that negative start/stop slice *indexes* have anything to do with negative range values.  They don't because -n range values count down from 0 while indexes are relative to end of sequence.
