### ISSUE TITLE
Unexpected interpreter crash

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104086]
Originally taken from [104057](https://github.com/python/cpython/issues/104057#issuecomment-1530242980)
Minimal reproducible example:
```python3
import os


def make_bad_fd():
    file = open("test_file.txt", "wb")
    try:
        return file.fileno()
    finally:
        file.close()



fd = make_bad_fd()
os.write(fd, b"foo")
```
Error:
```
"Debug assertion Failed."
File minkernel/ctrs/ucrt/src/appcrt/lowio/write.cpp line 50, expression (_osfile(fh) & FOPEN)
```
Reproducible only on Windows and debug build of interpreter.
Is it a bug?

**Comment by eryksun** [comment]
It's not a bug. See my [comment](https://github.com/python/cpython/issues/104057#issuecomment-1531503593) on issue #104057.
