### ISSUE TITLE
classes.html..C++ terminology referenced default scope as public and member functions as virtual which is not correct

### ISSUE THREAD

**Issue by gbrao018** [python/cpython#104053]
# Documentation

In classes.html, it was mentioned as 

"In C++ terminology, normally class members (including the data members) are public (except see below [Private Variables](https://docs.python.org/3/tutorial/classes.html#tut-private)), and all member functions are virtual."

There is a bug in the above description. In C++, default scope is private not public.  And all member functions are NOT virtual by default. Hope you please correct this.

Thanks,
Ganji.

**Comment by JelleZijlstra** [comment]
I think that's intended to mean that *Python* data members are public and methods are virtual if you think of them in C++ terminology. That's correct, but perhaps it could be worded better.

**Comment by ericvsmith** [comment]
In context, I think it’s pretty clear that it’s describing python classes using C++ terminology.
