### ISSUE TITLE
Add a `CookieJar.get_cookie` method

### ISSUE THREAD

**Issue by alexei** [python/cpython#104019]
# Feature or enhancement

Add a `CookieJar.get_cookie(domain: str, path: str, name: str)` method.

# Pitch

The cookie jar offers methods for writing (`set_cookie`, `clear`), but there’s no high level way to reading any of it i.e. no `get_cookie`. This is to propose to add such a method as the counterpart of `set_cookie`.

# Discussion

https://discuss.python.org/t/add-a-cookiejar-get-cookie-method/26368

**Comment by hugovk** [comment]
# Previous discussion

  New features to Python should first be discussed elsewhere before creating issues on GitHub, for example in the "ideas" category (https://discuss.python.org/c/ideas/6) of discuss.python.org, or the python-ideas mailing list (https://mail.python.org/mailman3/lists/python-ideas.python.org/).

Please could you open such a discussion and add the link here?

**Comment by alexei** [comment]
@hugovk I opened the topic and edited the description

**Comment by AA-Turner** [comment]
Closing in favour of the Discourse topic.

A
