### ISSUE TITLE
typing: Document get_origin and get_args separately

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104010]
Currently `get_args` and `get_origin` share the same documentation paragraph:

<img width="904" alt="Screen Shot 2023-04-30 at 6 58 36 AM" src="https://user-images.githubusercontent.com/906600/235356943-27853a8c-384b-4585-8047-1b6487effac3.png">

This makes it look like `get_args` is undocumented. I think the two functions are different enough that it makes sense to give each its own paragraph of documentation.

### Linked PRs
* gh-104013
* gh-104359

**Comment by chgnrdv** [comment]
Don't mind if I'll work on it? :)

**Comment by JelleZijlstra** [comment]
Go ahead!
