### ISSUE TITLE
Accessing Files on same root directory

### ISSUE THREAD

**Issue by ankit-gautam23** [python/cpython#104087]
I am trying to access one function which is there in another file. I tried accessing that in local it worked but it didn't work on server where I hosted it. Any fixes for this. I tried import under try except.

**Comment by Eclips4** [comment]
Hello!
Please, provide an minimal reproducible example of your problem.
Also, your question seems like not a related to this repo, you can ask for help here: https://discuss.python.org/c/users/7

**Comment by sobolevn** [comment]
Please, ask user-support questions in https://discuss.python.org/c/users/7

This is a place for bugs in CPython :)
