### ISSUE TITLE
Add type annotations to clinic.py

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#104050]
# Feature or enhancement

Gradually add type hints to clinic.py.

# Pitch

Adding type hints to clinic.py will make it easier to debug, fix bugs, do code review, add new features, and triage. IMO, the churn is worth the effort in the long run.

# Previous discussion

Since adding typing to the CPython code base has been a slightly controversial topic (obviously controversial for `Lib/`), I created a [topic on Discourse](https://discuss.python.org/t/consider-adding-type-hints-to-clinic-py/26320?u=erlendaasland) and asked for feedback. So far, I have not received any discouragements :)

### Linked PRs
* gh-104421
* gh-104538
* gh-104543
* gh-104544
* gh-104547
* gh-104588
* gh-104589
* gh-104626
* gh-104628
* gh-104631
* gh-104648
* gh-104704
* gh-104705
* gh-104706
* gh-106343
* gh-106354
* gh-106357
* gh-106376
* gh-106431
* gh-106435
* gh-106437
* gh-106519
* gh-106655
* gh-106699
* gh-106732
* gh-106750
* gh-106760
* gh-106810
* gh-106929
* gh-106932
* gh-106934
* gh-106935
* gh-107074
* gh-107192
* gh-107200
* gh-107206
* gh-107207
* gh-107209
* gh-107210
* gh-107225
* gh-107264
* gh-107288
* gh-107293
* gh-107294
* gh-107399
* gh-107405

**Comment by erlend-aasland** [comment]
Since I've been ignorant to typing until now, I'd like to give this a shot myself; it'll be a nice opportunity to learn some new tricks.

**Comment by sobolevn** [comment]
@erlend-aasland feel free to ask for help/reviews :)

**Comment by hauntsaninja** [comment]
A good place to start is by switching the instance fields in `CConverter` to use variable annotations. This is the cause of most of the existing mypy complaints.

As you add types, the type checker will become more useful. Once you've gotten a number of types in, I recommend upgrading to `mypy --check-untyped-defs`, and then possibly `mypy --strict`.

I'm biased, but I think mypy docs are a generally useful reference: https://mypy.readthedocs.io/en/latest/cheat_sheet_py3.html

**Comment by erlend-aasland** [comment]
As recommended by @AlexWaygood, we should probably start by adding a minimal type check to the CI. (We really don't want to increase CI minutes too much.) In the beginning, perhaps an allow-list is the most manageable path forward. When that list starts to grow, we can consider switching to using a deny-list instead. Thoughts? PRs welcome :)

**Comment by AlexWaygood** [comment]
Here's a PR to add a mypy check in CI, checking only the `Tools/clinic` directory: https://github.com/python/cpython/pull/104421. It ran in 20 seconds (and will only run on PRs that touch files in `Tools/clinic/`), so I doubt it will increase our use of CI minutes too much!

**Comment by erlend-aasland** [comment]
> Since I've been ignorant to typing until now, I'd like to give this a shot myself; it'll be a nice opportunity to learn some new tricks.

Don't take this too serious; I don't want to block anybody from contributing. Please fire up PRs if you want (I appreciate if you tag me, though!)

**Comment by erlend-aasland** [comment]
I amended my https://github.com/python/cpython/issues/104050#issuecomment-1530006444; as stated in the edited text: I don't want to block anyone; please create PRs if you feel the urge :)

**Comment by AlexWaygood** [comment]
44 merged PRs later, and clinic is now 100% fully typed! 🚀

**Comment by erlend-aasland** [comment]
A big thanks to everyone involved! 🎉❤️
