### ISSUE TITLE
Performance of PyObject_HasAttrString

### ISSUE THREAD

**Issue by itamaro** [python/cpython#104078]
# Feature or enhancement

`PyObject_HasAttrString` is implemented in terms of `PyObject_GetAttrString` / `PyErr_Clear`.
for non-existing attributes, there's significant overhead from creating an error only to clear it later.
this can be optimized by implementing it in terms of `PyObject_HasAttr`.

## microbenchmark

```
python -m pyperf timeit -s '
import _testcapi
hasattr_string = _testcapi.hasattr_string

class A:
  def __init__(self):
    self.attr = 1

a = A()' 'hasattr_string(a, "noattr")'
.....................
Mean +- std dev: 487 ns +- 7 ns
```

### Linked PRs
* gh-104079

**Comment by ericvsmith** [comment]
What are the before and after timings? Have you tested the impact on something other than a micro benchmark?

**Comment by JelleZijlstra** [comment]
There appear to be no calls to `PyObject_HasAttrString`  in CPython itself, other than internal extension modules. So it's unlikely there will be an effect on CPython's own performance. However, the function is part of the public API, so speeding it up may help some third-party extensions.

**Comment by itamaro** [comment]
> What are the before and after timings?

the before and after numbers are quoted in the PR description (the optimization is about 3.3X speedup).

> Have you tested the impact on something other than a micro benchmark?

as @JelleZijlstra pointed out, this doesn't really show up within cpython itself. it showed up in Instagram profiling data due to internal and/or third-party usage (I don't have the data available to pinpoint it).
based on code search I see usage of this API in BoostPython & Cython for example.
