### ISSUE TITLE
`test_calendar` fails on Azure Pipelines

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#104012]
The newly added test `test_calendar.CalendarTestCase.test_deprecation_warning` (added in https://github.com/python/cpython/commit/84e7d0f0c7f9a44d81be2d705ed4d401a6505356) has been consistently failing on Azure Pipelines over the past day. Example: https://dev.azure.com/Python/cpython/_build/results?buildId=126290&view=logs&j=0fcf9c9b-89fc-526f-8708-363e467e119e&t=fa5ef4ee-3911-591e-4444-19482ab189b7&l=463. I'm not sure why there's a difference between Azure Pipelines and GitHub Actions here, but it does also fail for me locally on Windows.

Cc. @Agent-Hellboy / @hugovk

The fix seems simple; I have a PR ready.

### Linked PRs
* gh-104014

**Comment by Agent-Hellboy** [comment]
Thanks @AlexWaygood
