### ISSUE TITLE
Frozen dataclasses with slots cannot override __getstate__ or __setstate__

### ISSUE THREAD

**Issue by drhagen** [python/cpython#104035]
You are supposed to be able to override how `pickle` pickles an object with `__getstate__` and `__setstate__`. However, these methods [are ignored](https://stackoverflow.com/questions/76143398/pickle-ignores-getstate-on-frozen-dataclasses-with-slots) in a dataclass when specifying both `frozen=True` and `slots=True`.

See this example:

```python
import pickle
from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class Foo:
    bar: int

    def __getstate__(self):
        print("getstate")
        return {"bar": self.bar}

    def __setstate__(self, state):
        print("setstate")
        object.__setattr__(self, "bar", state["bar"])

b = pickle.dumps(Foo(1))
foo = pickle.loads(b)
```

The expected "getstate" and "setstate" lines are never printed because the supplied methods are never called. If either `frozen` or `slots` is removed, the expected lines are printed.

From [the source code](https://github.com/python/cpython/blob/main/Lib/dataclasses.py#L1228-L1231), it is pretty clear why this is happening. If `frozen` and `slots` are both `True`, then special versions of `__getstate__` and `__setstate__` are unconditionally attached to the dataclass. The dataclass decorator should probably treat this way that it does other methods—only add a method if it is not already present.

### Linked PRs
* gh-104041
* gh-104044

**Comment by ericvsmith** [comment]
It does seem reasonable to ignore `__getstate__` and `__setstate__` if they're already set. Have you tested this? And in particular, does it break any existing tests?

**Comment by sobolevn** [comment]
Oh, I just went for fixing this in https://github.com/python/cpython/pull/104041 :) 

New logic will allow users to customize `__getstate__` and `__setstate__` method.
Thanks a lot, @drhagen for finding this :)

It is funny that I've spent the whole day optimizing these two in https://github.com/python/cpython/issues/103032, but I haven't seen this! 👍
