### ISSUE TITLE
Remove dead code from clinic.py

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#104146]
There's a bit of unused code in clinic.py. For example, the code that manipulated `second_pass_replacements` was removed in 2015 (commit 0759f84d6260bad1234b802212e73fdc5873d261, gh-67688 (bpo-23500)), but the variable and a branch depending on it still persists.

Suggesting to remove all unused code in order to make clinic more readable and maintainable.

### Linked PRs
* gh-104147
* gh-104214
* gh-104627
* gh-104680
* gh-106358
* gh-107555
* gh-107608
* gh-107627
* gh-107632
* gh-119162

**Comment by erlend-aasland** [comment]
Encountered more unused vars in `DSLParser.directive_class`; reopening.

**Comment by AlexWaygood** [comment]
Running `pyflakes` on `Tools/clinic` finds a few more yet:

```
Tools/clinic/clinic.py:551:5: local variable 'result' is assigned to but never used
Tools/clinic/clinic.py:1341:9: local variable 'groups' is assigned to but never used
Tools/clinic/clinic.py:1431:9: local variable 'default_return_converter' is assigned to but never used
Tools/clinic/clinic.py:1529:9: local variable 'ignore_self' is assigned to but never used
Tools/clinic/clinic.py:1809:21: local variable 'input_checksum' is assigned to but never used
Tools/clinic/clinic.py:4224:9: local variable 'new' is assigned to but never used
```

All except maybe the last one look as though they're true positives to me, from skimming the code.

**Comment by erlend-aasland** [comment]
> Running `pyflakes` on `Tools/clinic` finds a few more yet:

Let's leave this open, but I suggest we remove them when we encounter issues with them. For example, in gh-104627 I removed variables that created havoc when I added type annotations for the surrounding code.

**Comment by erlend-aasland** [comment]
OTOH, there's no harm in removing them right away. After all, the grand plan is to improve the readability and maintainability of Argument Clinic. Unused code is clutter, and it makes it harder to understand what's happening.
