### ISSUE TITLE
bdb.BdbQuit is found when trying to using pdb to debug ansible 2.9.20

### ISSUE THREAD

**Issue by haojue** [python/cpython#104194]
# Bug report
not sure if it is the right place to file this bug, if not please help redirect me to other suitable places, thank you!

when trying to debug ansible `ansible-2.9.20-1.el8ae.noarch`, 

```plain
python -m pdb /usr/bin/ansible-playbook  -i /somepath/inventory/3242/hosts /root/testplay2.yml -v

b /usr/lib/python3.6/site-packages/ansible/executor/task_executor.py:368

(Pdb)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: bdb.BdbQuit
fatal: [172.26.3.242]: FAILED! => {"msg": "Unexpected failure during module execution.", "stdout": ""}
```

# Your environment

```plain
python -V
Python 3.6.8
```

**Comment by arhadthedev** [comment]
@iritkatriel, @gaogaotiantian (as the most often committers into `Lib/pdb.py`)

**Comment by sunmy2019** [comment]
Can You provide full steps or minimal steps to reproduce it?

Python3.6 is no longer in maintenance, would you try a newer version (namely 3.10, 3.11) to check if this issue persists?

**Comment by gaogaotiantian** [comment]
Hi @haojue , without a reproducible example we can't reproduce this problem. Also what command did you use? Did you bring up `pdb` successfully and set a breakpoint? I asked because there's no prompt(`(Pdb) `) before your break command so it might not be directly copied from your terminal.

More importantly, did you quit `pdb`? Like using `Ctrl+D` or `quit`. The current mechanism for quitting `pdb` is to raise a `BdbQuit` exception, but in `ansible` [code](https://github.com/ansible/ansible/blob/932abc0711f05b6f91af1dfce0061c848e4165a0/lib/ansible/executor/task_executor.py#L200), they tried to catch all the exceptions and do something with it. Which means, if you tried to exit `pdb` when debugging `ansible`, the "exit" signal would be caught by `ansible` and that's probably what you saw.

**Comment by haojue** [comment]
Hi @gaogaotiantian @sunmy2019 , 
Thank you for your quick response! To answer your queries:
1. I know Python3.6 is no longer in maintenance, just raising the issue to see if it is a common issue for all versions^_^ I do not have a python 3.10, 3.11 yet, but in our next release, we might use python 3.9.
2. I have set pdb breakpoint successfully and I did not run any `Ctrl+D` or `quit` to quit pdb manually.
3. command I was using: `python -m pdb /usr/bin/ansible-playbook  -i /somepath/inventory/3242/hosts /root/testplay2.yml -v`

The steps to reproduce:
1. create testplay2.yml
```
---
- hosts: controller
  tasks:
   - name: "ssh server config change to send an alive message to the ssh connected client"
     ansible.builtin.command: "{{ item }}"
     args:
       warn: false
     with_items:
      - 'sed -i "/ClientAliveInterval/d" /etc/ssh/sshd_config'
      - 'sed -i "/ClientAliveCountMax/d" /etc/ssh/sshd_config'
      - 'sed -i "$a ClientAliveInterval 90"  /etc/ssh/sshd_config'
      - 'sed -i "$a ClientAliveCountMax 3"  /etc/ssh/sshd_config'
      - 'rm -rf /tmp/.ansible/cp'
      - 'mkdir -p /tmp/.ansible/cp'
     ignore_errors: yes

   - name: ensures sshd service is restarted
     service:
       name: "sshd"
       state: restarted
       enabled: yes
     register: sshd_restart
     until: sshd_restart is success
     retries: 10
     delay: 5
```
2.  inventory file is created `/somepath/inventory/3242/hosts`
```
all:
  children:
    controller:
      hosts:
        1.1.1.1:             <==== actually we are using another valid ip address instead of 1.1.1.1      
```
3. run `python -m pdb /usr/bin/ansible-playbook  -i /somepath/inventory/3242/hosts /root/testplay2.yml -v`
4. `b /usr/lib/python3.6/site-packages/ansible/executor/task_executor.py:368` 
5. `c` to continue
6. the errors in the description happens

please let me know if these info is enough.

**Comment by gaogaotiantian** [comment]
Unfortunately, I can't reproduce this on 3.11.

```

PLAY [controller] ****************************************************************************

TASK [Gathering Facts] ***********************************************************************
fatal: [1.1.1.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 1.1.1.1 port 22: Connection timed out", "unreachable": true}

PLAY RECAP ***********************************************************************************
1.1.1.1                    : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

The program exited via sys.exit(). Exit status: 4
> /home/gaogaotiantian/programs/bilibili_video/venv3.11/bin/ansible-playbook(3)<module>()
-> import re
```

Not sure if the invalid IP intercepted the bug. Since python3.6 is EOL now, we won't spend more time to try to reproduce this on 3.6. If you can reproduce this on 3.10 or 3.11, let us know and we'll have another look at it.

**Comment by haojue** [comment]
@gaogaotiantian , 

Thank you! if I can reproduce it on 3.9, is that ok for you to take another look at it? I will switch to python39 in one or two months.

**Comment by haojue** [comment]
Besides, seems you are on a different route as this error is found ^_^
```
TASK [Gathering Facts] ***********************************************************************
fatal: [127.0.0.1]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: ssh: connect to host 127.0.0.1 port 22: Connection refused", "unreachable": true}
```

**Comment by gaogaotiantian** [comment]
Then you need to provide a minimum **reproducible** example - meaning we need to be able to reproduce your error without any background knowledge of the 3rd party libraries. For example, your host file is obviously invalid so I may not be able to reproduce the error.

I would suggest you to narrow it down as much as possible, and provide steps that can reliably reproduce this error on ANY computer.

**Comment by haojue** [comment]
My apology for late response, thank you @gaogaotiantian and all involved in this issue! I'll definitely revisit this issue when I switch over to python39.
