### ISSUE TITLE
Support detecting SOCKS proxy configuration on macOS

### ISSUE THREAD

**Issue by samschott** [python/cpython#104180]
# Feature or enhancement

Allow `urllib.request.getproies()` to detect SOCKS proxies configured in macOS system settings.

# Pitch

`urllib.request.getproies()` is widely used, for example by `requests`, to detect proxy configurations from environment variables, macOS System Settings or the Windows Systems Registry. On macOS, however, it does not support reading SOCKS proxy configurations. This is supported on Windows, see #26307.

I'm not sure if this is intentional or just an oversight, but the difference is certainly not documented in https://docs.python.org/3/library/urllib.request.html#urllib.request.getproxies. It would be nice to have feature parity here.

### Linked PRs
* gh-104181

**Comment by ronaldoussoren** [comment]
Not having SOCKS support is an oversight. At the time I didn't know urllib supported SOCKS, and my use-case when adding this was an environment with a regular HTTP proxy.

**Comment by ronaldoussoren** [comment]
@samschott : Thanks for the PR. 

Closing the issue as the PR is merged and this is a feature change that cannot be back ported.
