### ISSUE TITLE
Prefix Matching in importlib

### ISSUE THREAD

**Issue by ShadowUnicorn90** [python/cpython#104165]
Python 3.9.6 running in pyenv and poetry virtualenv.  Had multiple versions of a directory with Python files to import, decided it would be best “import dir1  as dir”, “import dir2 as dir”, etc. and comment out all lines but the import statement I wanted at the time.  One of the directories was named gym_zelda_1 and another was named gym_zelda_1_expert_control.  Very bizarre behavior ensued.  Concluded Python was importing gym_zelda_1 when asked to import gym_zelda_1_expert_control.  Issue was solved by deleting all but one directory and resorting to copying files back and forth when changes were needed.  Prefix matching?  Seems unintended behavior.  To thought I would try to be helpful and report it.

**Comment by sobolevn** [comment]
Please, provide a minimal sample to reproduce this issue.

**Comment by itamaro** [comment]
could not repro (on MacOS) based on my understanding of the issue as described

```
test/
├── foo
│   └── __init__.py
├── foo_bar
│   └── __init__.py
└── hello.py
```

```py
# hello.py

# import foo as m
import foo_bar as m

print("hello from", m)
```

```bash
./python.exe test/hello.py
hello from <module 'foo_bar' from '/Users/itamaro/work/pyexe/main-dbg/test/foo_bar/__init__.py'>
```

**Comment by ericvsmith** [comment]
I'm going to close this. If the original poster has more information that allows us to reproduce the issue, we can reopen it.
