### ISSUE TITLE
Improve tokenize error handling

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#104169]
There has been quite a lot of instances were poor error handling in the tokenizer leads to crashes or errors being overwritten. We should not rely on continuous patches to every single individual issue but we should improve the situation with more robust infrastructure.

### Linked PRs
* gh-104170
* gh-110684
* gh-110727

**Comment by pablogsal** [comment]
CC: @lysnikolaou

**Comment by hugovk** [comment]
Ready to close? Thanks!
