### ISSUE TITLE
Dicts' item views support set-like operations even when the items are not hashable

### ISSUE THREAD

**Issue by UltimateLobster** [python/cpython#104229]
# Bug report
From the documentation of dict views:

> If all values are hashable, so that (key, value) pairs are unique and hashable, then the items view is also set-like. 
> ...
> For set-like views, all of the operations defined for the abstract base class collections.abc.Set are available (for 
example, ==, <, or ^).

However, the following operation works with no error even when the value is non-hashable:
```python
d1 = {"key": []}
d2 = {"key": []}

# Prints False.
print(d1.items() > d2.items())
```

Is this a bug or an outdated documentation?

# Your environment

- CPython versions tested on: 3.11.3
- Operating system and architecture: Windows 11 64 bit.

**Comment by sunmy2019** [comment]
Docs are here:
https://github.com/python/cpython/blob/f5088006ca8e9654fbc3de119462f0ab764e408b/Doc/library/stdtypes.rst#L4751-L4758

**Comment by sunmy2019** [comment]
No words indicate that "when the value is non-hashable, comparing dict views will lead to an error".


Comparing 2 dict.items() is implemented here

https://github.com/python/cpython/blob/f5088006ca8e9654fbc3de119462f0ab764e408b/Objects/dictobject.c#L4623-L4680

I think this issue is invalid, but we do have a chance to improve the doc.

**Comment by UltimateLobster** [comment]
> Comparing 2 dict.items() is implemented here
> 
> https://github.com/python/cpython/blob/f5088006ca8e9654fbc3de119462f0ab764e408b/Objects/dictobject.c#L4623-L4680
> 
> No words in the doc indicate that "when the value is non-hashable, comparing dict views will lead to an error". The doc only indicates "when the value is hashable, comparing dict views will not lead to an error".
> 
> I think this issue is invalid, but we do have a chance to improve the doc.

While not explicitly stating that it should raise an error, it goes out of its way to specifiy the potential hashability of the items. The implication is that views with non-hashable items should behave somewhat differently to views with hashable items (because otherwise, why bring the subject of hashability at all?).

I just wanted to make sure this is indeed a case of a documentation issue and not a case of an implementation detail we should not rely on.

**Comment by rhettinger** [comment]
> I just wanted to make sure this is indeed a case of a documentation issue and not a case of an implementation detail we should not rely on.

This is an implementation detail – the algorithm could have been written without an early out for a size check. 

With respect to the docs, we don't normally document implementation details like this. It risks over-specification and it makes the docs harder to reader.  Also, the norm in Python is that TypeErrors do not get raised unless the data is actually being used on some code path. For example, with an array of ints that contains a `None`, bisect only reports a TypeError if the `None` happens to be in the chain of bisections.
