### ISSUE TITLE
`lzma._decode_filter_properties` crashes with BCJ filter and buffer of zero length

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#104282]
Example:

```python
>>> import lzma
>>> lzma._decode_filter_properties(lzma.FILTER_X86, b"")
Segmentation fault (core dumped)
```
In `_lzma__decode_filter_properties_impl` call to `lzma_properties_decode` returns `LZMA_OK` and leaves `filter.options` intact (that is uninitialized) if `filter.id` is id of a BCJ filter (FILTER_X86, FILTER_POWERPC, FILTER_IA64, FILTER_ARM, FILTER_ARMTHUMB, FILTER_SPARC) and `encoded_props->len` is equal to zero.

https://github.com/python/cpython/blob/01cc9c1ff79bf18fe34c05c6cd573e79ff9487c3/Modules/_lzmamodule.c#L1487-L1495

Then, in `build_filter_spec`, access to `f->options->start_offset` leads to segmentation fault:

https://github.com/python/cpython/blob/01cc9c1ff79bf18fe34c05c6cd573e79ff9487c3/Modules/_lzmamodule.c#L489-L499

The PR is on the way.
3.9-3.12 are affected for sure.

### Linked PRs
* gh-104283
* gh-114181
* gh-114182

**Comment by vortex996** [comment]
same

**Comment by serhiy-storchaka** [comment]
The PR uses a solution that differs from your report. It tests that `options` is not NULL. And I tested that it is set to NULL if the memory was initialized by non-null values. So this is not a use of uninitialized value, but a null pointer dereference.

`lzma._decode_filter_properties()` is not used with BCJ filter in the stdlib, and it is a private function, so this crash does not affect common users. But for third-party projects it may be a security issue.
