### ISSUE TITLE
Lib/tarfile.py: Inconsistent name with trailing slash

### ISSUE THREAD

**Issue by thibault-p** [python/cpython#104201]
# Bug report
The trailing slash is trimmed from name if name is too large to fit in header and it is stored in pax headers.  In the case name fits in header, trailing slash is removed only if entry is flaged as directory.

```python
import tarfile

# Create tar
with tarfile.open("foo.tar", "w") as tar:
    tar_info = tarfile.TarInfo()
    tar_info.name = "this_name_is_short/"
    tar.addfile(tar_info)

    tar_info = tarfile.TarInfo()
    tar_info.name = "this_name_is_supercalifragilisticexpialidociously_long_and_it_will_ends_in_the_pax_headers_section_instead_of_the_regular_header/"
    tar.addfile(tar_info)

# Read tar
with tarfile.open("foo.tar", "r") as tar:
    tar_info = tar.next()
    print(tar_info.name)
    tar_info = tar.next()
    print(tar_info.name)
```
### Output

```shell                                      
this_name_is_short/
this_name_is_supercalifragilisticexpialidociously_long_and_it_will_ends_in_the_pax_headers_section_instead_of_the_regular_header
```
The trailing `/` is missing for the long name but it is present for the short one.

### Expected output
```shell                                      
this_name_is_short/
this_name_is_supercalifragilisticexpialidociously_long_and_it_will_ends_in_the_pax_headers_section_instead_of_the_regular_header/
```
Both name have their trailing `/`.

# Your environment

```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.6 LTS
Release:        20.04
Codename:       focal
Python 3.8.10
```

**Comment by terryjreedy** [comment]
In the code you posted, the long name did not have a trailing slash.  After I added it, I verified that it is indeed deleted.  I also tried all other ascii symbols (except backslash) and none of them were removed.

**Comment by sunmy2019** [comment]
"/" was removed here:
https://github.com/python/cpython/blob/45a9e3834a6ed20ee250e2e5a8583dffcef0eb73/Lib/tarfile.py#L1542-L1543

**Comment by terryjreedy** [comment]
See edited comment.

**Comment by thibault-p** [comment]
@sunmy2019  Thank you for pointing out the code snippet.

@terryjreedy Removing the trailing slash without further check could be problematic. A conservative approach could be 
 ```python
 if keyword == "path" and self.isdir(): 
     value = value.rstrip("/") 
```
This will match the short name behaviour.

https://github.com/python/cpython/blob/45a9e3834a6ed20ee250e2e5a8583dffcef0eb73/Lib/tarfile.py#L1273-L1274

**Comment by thibault-p** [comment]
The `Tarfile` behaviour differs from `gnu tar`(version 1.30) as you can see. 

```shell
$ python -m tarfile -l foo.tar      
this_name_is_short/ 
this_name_is_supercalifragilisticexpialidociously_long_and_it_will_ends_in_the_pax_headers_section_instead_of_the_regular_header 
```
### Gnu tar

```shell
$ tar tvf foo.tar
drw-r--r-- 0/0               0 1970-01-01 01:00 this_name_is_short/
drw-r--r-- 0/0               0 1970-01-01 01:00 this_name_is_supercalifragilisticexpialidociously_long_and_it_will_ends_in_the_pax_headers_section_instead_of_the_regular_header/
```
