### ISSUE TITLE
`__iadd__` updates value only once when called in the loop from the outer function 

### ISSUE THREAD

**Issue by enkidulan** [python/cpython#104222]
# Bug report

Consider the example:

```py3
class Counter:
    def __init__(self, c=0):
        self.c = c

def count_iadd(counter):
    counter.c =+ 1

def count_to_3():
    counter = Counter()
    for _ in range(3):
        count_iadd(counter)
    return counter.c

result = count_to_3()
assert result == 3, result

```

If to run this code, it will fail because `count_to_3` call returns `1` instead of `3`:
```
Traceback (most recent call last):
  File "...", line 16, in <module>
    assert result == 3, result
           ^^^^^^^^^^^
AssertionError: 1
``` 

The issue seems to be with `counter.c =+ 1`, if to replace it with `counter.c = counter.c + 1` the example works as expected.

However, the most confusing part is that it returns `1` and not `0`, which means that `counter.c =+ 1` works correctly on the first iteration, but fails on all following iterations. Printing the id of the `counter.c` after each `+=` operation shows that its value is updated only once:

```
139965533934984
139965533935016
139965533935016
```

Here is a simple test case to confirm the behavior:

```py3
import unittest

class Counter:
    def __init__(self, c=0):
        self.c = c

def count_to_ten(count_function):
    counter = Counter()
    for _ in range(10):
        count_function(counter)
    return counter.c

class TestStringMethods(unittest.TestCase):

    def test_iadd(self):
        def count_iadd(counter):
            counter.c =+ 1
        assert count_to_ten(count_iadd) == 10

    def test_assign(self):
        def count_assign(counter):
            counter.c = counter.c + 1
        assert count_to_ten(count_assign) == 10

if __name__ == '__main__':
    unittest.main()
```

# Your environment

- CPython versions tested on: 3.11.3, 3.9, and 2.7
- Operating system and architecture: Linux x64

**Comment by carljm** [comment]
Hi! The in-place addition operator is spelled `+=`, not `=+`. Correct this in your example and it works as expected.

Spacing is not required around operators, so `counter.c =+ 1` is interpreted as `counter.c = +1`, which is equivalent to `counter.c = 1` (unary plus is a no-op), which also explains why you see `1` and not `0`.

**Comment by enkidulan** [comment]
:man_facepalming:
 thanks!

**Comment by terryjreedy** [comment]
One can ask about such puzzling results on the help channel of https://discuss.python.org/.
