### ISSUE TITLE
`test_pathlib` can fail on Windows if a `/dev/null` folder exists

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#104242]
# Bug report

`pathlib._Base_PathTest.test_is_char_device_true` is skipped unless `Path("/dev/null").exists()` evaluates to `True`:

https://github.com/python/cpython/blob/376137f6ec73e0800e49cec6100e401f6154b693/Lib/test/test_pathlib.py#L2591-L2600

I think the assumption is that if that filepath exists, the test must be running on a Posix machine (`/dev/null` isn't a special path in any way on Windows). However, this isn't necessarily true! On my Windows machine (to my surprise), I _do_ have a `/dev/null` directory:

```pycon
>>> import pathlib
>>> P = pathlib.Path("/dev/null")
>>> P.exists()
True
>>> P.absolute()
WindowsPath('C:/dev/null')
```

Why do I have a `/dev/null` path on my machine? I'm not sure, but I suspect I probably ran some script at some point that didn't have proper support for Windows, and it created a `/dev/null` folder for me instead of erroring out when it found that my machine didn't have one. Looks like I've got some weird mypy caches in there or something.

Anyway, the test should be more resilient to weird edge cases like this; it currently fails on my machine:

<details>
<summary>Results of running `python -m test test_pathlib` on my machine</summary>

```pytb
======================================================================
FAIL: test_is_char_device_true (test.test_pathlib.PathSubclassTest.test_is_char_device_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_pathlib.py", line 2596, in test_is_char_device_true
    self.assertTrue(P.is_char_device())
AssertionError: False is not true

======================================================================
FAIL: test_is_char_device_true (test.test_pathlib.PathTest.test_is_char_device_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_pathlib.py", line 2596, in test_is_char_device_true
    self.assertTrue(P.is_char_device())
AssertionError: False is not true

======================================================================
FAIL: test_is_char_device_true (test.test_pathlib.WindowsPathTest.test_is_char_device_true)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_pathlib.py", line 2596, in test_is_char_device_true
    self.assertTrue(P.is_char_device())
AssertionError: False is not true

----------------------------------------------------------------------
Ran 595 tests in 2.706s

FAILED (failures=3, skipped=191)
test test_pathlib failed
test_pathlib failed (3 failures)

== Tests result: FAILURE ==
```

</details>

Maybe the test should just be skipped on Windows?

# Your environment

- CPython versions tested on:
  - `main` @ 263abd333d18b8825cf6d68a5051818826dbffce
  - 3.11
- Operating system and architecture: 64-bit Windows (AMD64)

### Linked PRs
* gh-116904
* gh-116983
* gh-117277
* gh-117280

**Comment by terryjreedy** [comment]
The test seems to be testing that the system meets certain assumptions rather than the behavior of pathlib.  It even says that /dev/null *usually* is a char device, but fails if, unusually, it is not.  On Windows, /dev/null is usually absent, unless it is not.

**Comment by CAM-Gerlach** [comment]
Instead of skipping a test on a specific platform, it seems it might be more robust to instead skip if the platform _isn't_ POSIX, i.e. if `os.name` is not `posix`?
