### ISSUE TITLE
argparse: remove redundant len()

### ISSUE THREAD

**Issue by buraksaler** [python/cpython#104273]
# Feature or enhancement

I decreased calling of redundant len() function.

# Pitch

(Explain why this feature or enhancement should be implemented and how it would be used.
 Add examples, if applicable.)

# Previous discussion

### Linked PRs
* gh-104274

**Comment by itamaro** [comment]
hello @buraksaler!

it is not clear from this issue when `len()` calls you are referring to and why they are redundant.

looking at the linked PR, I'm inferring you refer to the argparse module, where you suggest replacing 3 `len()` calls with one.
while the change looks functionally correct to me, any change has inherent risks, so making such a change should be justifiable.
can you explain the benefits of making this change? it looks like the intention could have been improving performance by caching the result of a function call, in which case, you should provide benchmarking results (micro or macro) or profiling data showing the improvement from making this change.

**Comment by terryjreedy** [comment]
Justification: `indent` is a parameter of the helper function get_lines.  It is not rebound within the function.  Its length is therefore a constant within the function.  Hence `len(indent)` is only needed once.  

Calculating common subexpressions just once is a common optimization.  I don't think benchmarking is needed.

**Comment by hauntsaninja** [comment]
I'm okay with the specific PR, but in general we discourage microoptimisations in cold code, especially if done without any kind of benchmarking. These cost reviewer time, can hurt readability and if poorly done run the risk of regressions. I certainly wouldn't welcome PRs doing CSE for all calls to len in the standard library.
