### ISSUE TITLE
Tools/peg_generator/pegen produces invalid python in parse.py

### ISSUE THREAD

**Issue by noahbkim** [python/cpython#104366]
# Bug report

Following the [https://devguide.python.org/internals/parser/#making-experiments](CPython devguide) to create a Python grammar parser (`parse.py`) produces invalid Python:

```
$ make -j
$ cd Tools/peg_generator
$ ../../python -m pegen -v python ../../Grammar/python.gram
  File "/usr/scratch/noah/python/Tools/peg_generator/./parse.py", line 34
    return _PyAST_Interactive ( a , p -> arena )
                                      ^^
SyntaxError: invalid syntax
```

Notably, the trailer gets copied in wholesale (definitely not gonna run):

```
void *
_PyPegen_parse(Parser *p)
{
    // Initialize keywords
    p->keywords = reserved_keywords;
    p->n_keyword_lists = n_keyword_lists;
    p->soft_keywords = soft_keywords;
    ...
```

# Your environment

This appears to be environment agnostic.

**Comment by noahbkim** [comment]
cc @lysnikolaou

**Comment by Eclips4** [comment]
Cannot reproduce on current main.
On which version of CPython did you try this?

**Comment by sunmy2019** [comment]
> Cannot reproduce on current main.

You need one more step: 
```
../../python parser.py
```





> produces invalid Python

That grammar file is intended for C.

Impossible to support both C and Python versions in one grammar file.

For a Python version, check this repository: https://github.com/we-like-parsers/pegen/tree/main
and here https://github.com/we-like-parsers/pegen/blob/main/data/python.gram

Note that the Python version is not up to date. The C version is the reference.

**Comment by noahbkim** [comment]
Thanks! Sorry, maybe it would be worth updating the devguide to be explicit here, but this can be closed.
