### ISSUE TITLE
Add importlib.util.allowing_all_extensions()

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#104310]
Per [PEP 684](https://peps.python.org/pep-0684/#restricting-extension-modules), we are providing `importlib.util.allowing_all_extensions()` as a context manager users may use to disable the strict compatablility checks.

I'll be added docs for this separately from the code.

### Linked PRs
* gh-104311
* gh-105255
* gh-105518

**Comment by hauntsaninja** [comment]
Thanks!

**Comment by ericsnowcurrently** [comment]
@brettcannon asked for a different name for the context manager:  https://github.com/python/cpython/pull/104311#issuecomment-1540922574.
