### ISSUE TITLE
Add link to Download page on documentation index

### ISSUE THREAD

**Issue by adorilson** [python/cpython#104395]
# Documentation

In docs.python.org, there is no a obvious link to [download page](https://docs.python.org/3/download.html). I found one just in a question on FAQ section.

So, I suggestion add a link on documentation index. I think a new entry on Meta Information section a good place for this. 

### Linked PRs
* gh-104443
* gh-109345
* gh-109346

**Comment by terryjreedy** [comment]
Adding a link to x.y.z download page to the x.y.z doc seems like a good idea.  There could be objection that the docs are for python and the download page only has CPython, but a) there is no other current x.y.z implementation that I know of and b) either the doc or the download page could have other links.

**Comment by rffontenelle** [comment]
@terryjreedy I'm not sure I understand your message.

The download page listed by Adorilson is for a specific CPython version, so https://docs.python.org/3.11/download.html has links to 3.11 version. This thanks to the [download.html template](https://github.com/python/cpython/blob/3.11/Doc/tools/templates/download.html)

**Comment by adorilson** [comment]
@terryjreedy I mean the downloading the documentation itself, not a Python implementation.

Btw, using "Getting Documentation" seems more clear than  "Download".

**Comment by terryjreedy** [comment]
What does 'downloading the documentation' mean?  It comprises 100s of interlinked web pages.

**Comment by rffontenelle** [comment]
The "download page" in the original message links to downloading CPython's documentation in formats like PFF, HTML, etc.

![Screenshot_20230512-194138_Firefox.jpg](https://github.com/python/cpython/assets/1571783/3e0049e9-e2a1-4738-8936-ba38fc993ed7)

**Comment by terryjreedy** [comment]
Sorry I missed this.  I agree that this should not be kept a near secret.  I opened a new [discuss topic](https://discuss.python.org/t/list-doc-download-page-on-initial-doc-page/26728) for more opinions and information.

**Comment by terryjreedy** [comment]
2 or 3 people on the discuss topic (link) above pointed out that there is already a link in the left-hand column.
@adorilson  I am sure that you can read the discuss page even without an account.

@JulienPalard  Please decide about Adam's PR and this issue.

**Comment by adorilson** [comment]
> 2 or 3 people on the discuss topic (link) above pointed out that there is already a link in the left-hand column.

Really, I didn't realized this before.

> @adorilson I am sure that you can read the discuss page even without an account.

Yes, I saw the discuss. Thank you.

I saw the PR too and I will do a suggestion there.

**Comment by hugovk** [comment]
This should be better now. Thanks for the report!
