### ISSUE TITLE
Comprehension inlining: Bug if comprehension contains a lambda

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104357]
Code sample:

```python
def outer(x):
    return [lambda: x for x in range(x)]

print([f() for f in outer(2)])
```

On 3.11, this produces `[1, 1]` as expected.

But on current main, I get:

```
>>> [f() for f in outer(2)]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in outer
TypeError: 'cell' object cannot be interpreted as an integer
```

Almost certainly due to PEP 709 / #101441, cc @carljm.

### Linked PRs
* gh-104368

**Comment by carljm** [comment]
Thanks for finding this case! I had tests for similar cases with lambda inside the comprehension using the same name as non-cell outside the comprehension, but they were all of the form:

```
def outer():
    x = 2
    return [lambda: x for x in range(x)]
```

The key factor in your example is that there is no store to `x` in the outer scope.
