### ISSUE TITLE
gammavariate uses misleading parameter names.

### ISSUE THREAD

**Issue by drj11** [python/cpython#104337]
# Documentation for gammavariate

The parameters of the `gammavariate` function (in `random` module) are `alpha`, `beta`.

We can see, from the mathematical description given, that these correspond to _shape_ and _scale_. [Wikipedia conventionally describes these using the symbols `k` and `theta`](https://en.wikipedia.org/wiki/Gamma_distribution). Wikipedia uses `beta` for _rate_, which is the reciprocal of _scale_: _beta_ = 1/_theta_

This is a proposal to:

- explain that `alpha` and `beta` are also known as _shape_ and _scale_;
- reinforce that by adding that μ is proportional to _scale_;
- add a warning that these are not the conventional names.

or, more controversially, scrap all that and rename the parameters _k_ and _theta_. I understand that the parameter names leak into the API, so maybe not this option.

Side note: there is some variability in naming convention. The only textbook i have to hand is Grimmett and Stirzaker "Probability and Random Process" (OUP, 1982). That uses Γ(λ, t) where _lambda_ is rate and _t_ is shape.

(A clear and concise description of the issue.)

### Linked PRs
* gh-104410
* gh-104481

**Comment by mdickinson** [comment]
> * add a warning that these are not the conventional names.

I'm curious: what's the algorithm for determining what the conventional names are? The first textbook I checked was DeGroot's "Probability and Statistics" (2nd edn), which uses α and β for the parameter names. The C++ std. lib. uses `alpha` and `beta` ([ref](https://en.cppreference.com/w/cpp/numeric/random/gamma_distribution)). The first hit I got in an arXiv search was [this paper](https://arxiv.org/abs/2303.17487), which uses α and β.

**Comment by mdickinson** [comment]
Hmm, sorry; I see - there's variation in whether β represents the scale or the inverse scale. Of the three references mentioned above, DeGroot has β being the inverse of the scale, while the C++ std. lib. and the paper referenced have β as the scale parameter. A Google Books search pulled up [this book](https://www.google.co.uk/books/edition/Gamma_and_Related_Distributions/eMAfAwAAQBAJ?hl=en&gbpv=1&dq=gamma+distribution&printsec=frontcover) as the first hit, which also uses β as the scale.

So indeed there's variation, but Python's choice doesn't seem to be particular unusual here. A note following your first suggestion ("explain that alpha and beta are also known as shape and scale") doesn't seem unreasonable, but I'm not seeing a case for the suggested warnings (and still less for renaming).

**Comment by mdickinson** [comment]
> A Google Books search pulled up [this book](https://www.google.co.uk/books/edition/Gamma_and_Related_Distributions/eMAfAwAAQBAJ?hl=en&gbpv=1&dq=gamma+distribution&printsec=frontcover) as the first hit, which also uses β as the scale.

Hmm. Forget the book - that doesn't seem to be a good reference. It hedges its bets weirdly by presenting pdfs using β both as a scale parameter _and_ an inverse scale parameter, and seems to interchange between the two inconsistently (e.g., in Ch III, the variance is computed as ɑβ²).

**Comment by mdickinson** [comment]
One more data point: here's Wolfram Alpha:
<img width="876" alt="Screenshot 2023-05-09 at 20 54 30" src="https://github.com/python/cpython/assets/662003/9c4deafa-33eb-494f-8715-9fb1c9f4ad0b">

**Comment by drj11** [comment]
You seem to have resolved most issues whilst i was asleep.

Agreed that this use of `alpha` and `beta` fall within existing accepted use, and therefore on not changing the names. Agreed (obviously) that adding a note relating to _shape_ and _scale_ would be useful.

As for convention, i didn't claim any particular convention, i just deferred to Wikipedia (which of course, you are welcome to edit). Although i _do_ claim that i was mislead.

**Comment by terryjreedy** [comment]
I propose that in https://github.com/python/cpython/blob/main/Doc/library/random.rst we replace
>  Conditions on the parameters are ``alpha`` > 0 and ``beta`` > 0.

with
> The shape and scale parameters ``alpha`` and ``beta``, must get positive values.  (Confusingly, 'beta' is sometimes used instead for the rate parameter 1 / scale.)

@rhettinger ?

**Comment by rhettinger** [comment]
One other source for comparison:  https://support.microsoft.com/en-us/office/gamma-dist-function-9b6f1538-d11c-4d5f-8966-21f6a2201def  The MS Excel docs are precise because they show the underlying probability density functions.

The suggested edit looks fine to me though I might have chosen different wording:

```
- The shape and scale parameters alpha and beta, must get positive values.
+ The shape and scale parameters, alpha and beta, must have positive values.
- (Confusingly, 'beta' is sometimes used instead for the rate parameter 1 / scale.)
+ (Calling conventions vary and some sources define 'beta' as the inverse of the scale).
```

**Comment by terryjreedy** [comment]
PR with Raymond's improvements upon my draft.
