### ISSUE TITLE
Newline string breaks doctest in four different contexts

### ISSUE THREAD

**Issue by pdq-self** [python/cpython#104303]
# Crash report
Four separate small code samples break doctest because a newline is misinterpreted.
In all four code samples, the failure follows the newline string, "\n", whether it appears
as a string literal or is assigned to a variable.

## CONTEXT 1
- A newline character in a literal string:  "\n",
- in an `__init__()`,
- in a class,
- that is in a docstring,
- that is inside an outermost class

### CAUSES doctest.testmod() to
1. raise a ValueError exception,
2. diagnose that line 10 of the docstring has inconsistent leading whitespace: '",' -- when there is no inconsistent leading whitespace in the file --
3. display a Traceback stack,
4. return to the shell prompt with status code 1.

### TRACEBACK, context 1
Runable code sample 1 contains a traceback.

### Error messages, context 1
- ValueError: line 10 of the docstring for __main__.F has inconsistent leading whitespace: '",'
- returned to shell prompt with status code 1.

## CONTEXT 2
- Assigning a newline character in a literal string to a variable
- in an `__init__()`,
- in a class,
- that is in a docstring,
- that is inside an outermost class

### CAUSES doctest.testmod() to
1. raise a ValueError exception,
2. -- NOTE THE LINE NUMBER CHANGE FROM CONTEXT 1--
3. diagnose that line 5 of the docstring has inconsistent leading whitespace: '",' -- when there is no inconsistent leading whitespace in the file --
4. display a Traceback stack,
5. return to the shell prompt with status code 1.

### TRACEBACK, context 2
Runable code sample 2 contains a traceback.

### Error messages, context 2
- ValueError: line 5 of the docstring for __main__.F has inconsistent leading whitespace: '"'
- returned to shell prompt with status code 1.

## CONTEXT 3
- A newline character in a literal string ("\n"),
- in a function,
- that is in a docstring

### CAUSES doctest.testmod() to
1. incorrectly interpret string literal "\n" as a line break,
2. try a test that was not requested,
3. incorrectly expect the test to produce the bottom of function in_it(),
4. raise a SyntaxError exception,
5. incorrectly detect that line 9 of the docstring has an unterminated string literal -- although there are no unterminated string literals in the file --
6. display a Traceback stack,
7. return to the shell prompt with status code 0, as if nothing bad happened.

### TRACEBACK, context 3
Runable code sample 3 contains both the try/expecting pair and the traceback.

### Error messages, context 3
- SyntaxError: unterminated string literal (detected at line 9)
- returned to shell prompt with status code 0.

## CONTEXT 4
- Assigning a newline character in a literal string to a variable
- in a function,
- that is in a docstring

### CAUSES doctest.testmod() to
1. incorrectly interpret string literal "\n" as a line break,
2. try a test that was not requested,
3. incorrectly expect the test to produce the bottom of function in_it(),
4. raise a SyntaxError exception,
5. -- NOTE THE LINE NUMBER CHANGE FROM CONTEXT 3--
6. incorrectly detect that line 4 of the docstring has an unterminated string literal -- although there are no unterminated string literals in the file --
7. display a Traceback stack,
8. return to the shell prompt with status code 0, as if nothing bad happened.

### TRACEBACK, context 4
Runable code sample 4 contains both the try/expecting pair and the traceback.

### Error messages, context 4
- SyntaxError: unterminated string literal (detected at line 4)
- returned to shell prompt with status code 0.

# My environment
- CPython versions tested on:  Python 3.11.2 (main, Mar 24 2023, 00:28:48) [Clang 14.0.0 (clang-1400.0.29.202)]
- Operating system and architecture:  macOS 12.6.5, Intel Core i9

[codesample1.tgz](https://github.com/python/cpython/files/11423788/codesample1.tgz)
[codesample2.tgz](https://github.com/python/cpython/files/11423932/codesample2.tgz)
[codesample3.tgz](https://github.com/python/cpython/files/11424420/codesample3.tgz)
[codesample4.tgz](https://github.com/python/cpython/files/11424421/codesample4.tgz)

**Comment by gaogaotiantian** [comment]
I only took a look at the first case. (For future issues, I'd recommend to copy/paste your example to the issue directly, it would faster for us to reproduce).

I think all of your problems are from the same root - the `\n` you put in a string is a new line, not the literal `\n`.

```python
s = "a\nb"
```

is equivalent to

```python
s = """a
b"""
```

Converting your code in this format, you'll understand why it reported error(not crash in this case, we normally do not consider an exception a crash).

To keep `\n` you should escape `\`, so `"\\n"` will give you what you actually needed. Another possibility is to use

```python
r"""
"\n"
"""

A minimum example would be

```python
exec("s = '\n')")
```

which will generate similar error as your code - because `\n` is treated as a newline character.

**Comment by pdq-self** [comment]
Hello Ms Gao,

Thank you, your explanation was excellent and clear.  Your analysis is much better than mine.

Originally, I took working code that Python runs flawlessly.  The fragment that you see below is a small piece of a larger program, but it is the part that broke doctest.  Note the annotation beside the "\n":

            # Found //
            finite_state_machine[2] = fsm.State(
                2,
                [
                    # Pass the end of line character to the output.
                    fsm.Arc(
                        "\n",  # here len("\n") is 1
                        [
                            fsm.Output(self.write),
                            fsm.Output(self.discard)
                        ],
                        0
                    ),

                    # Ingest all that follows //
                    fsm.Arc(fsm.Arc.ANY_CHAR, [fsm.Output(self.buffer)], 2)
                ]
            )

Escaping the backslash to protect doctest, breaks my code because the FSM is a filter that inspects data one character at a time, one character from the input is compared against one character from each arc or state transition that are paths that direct control to other states.

            # Found //
            finite_state_machine[2] = fsm.State(
                2,
                [
                    # Pass the end of line character to the output.
                    fsm.Arc(
                        "\\n",  # after translation, len("\\n") is 2
                        [
                            fsm.Output(self.write),
                            fsm.Output(self.discard)
                        ],
                        0
                    ),

                    # Ingest all that follows //
                    fsm.Arc(fsm.Arc.ANY_CHAR, [fsm.Output(self.buffer)], 2)
                ]
            )

Given that Python compiles and runs the original code flawlessly, but doctest requires escaping the newline's backslash.  Python parses my code without interpreting that newline as a line break, but doctest also parses my code and mistakes that same newline for a line break.  Something is awry in doctest.

Again, thank you for analyzing the problem and suggesting possible ways to avoid the problem.

Cheers,

Bill del Solar (pdq-self)

**Comment by gaogaotiantian** [comment]
You needed to escape the `\n` in your doctest because you are using it in a string literal.

Like I said above, if you write `s = '\n'` in your Python file, it works. But if you do `exec("s = '\n'")`, it won't work. That's how Python treats string literals.

The intention of doctest is to be able to copy and paste your code and output directly, but there are limits to it because you are writing it as a string, not a Python script. `\n` would be one of the limits.

Imagine you have a Python script like

```python
a = """
test
"""
print(a)
```

You can't simply copy and paste it in doctest, because it uses `"""` in the script and that will mess up the docstring.

I think the misunderstanding here is that "I can always copy and paste my code in doctest and it'll just work", that's not the case and it is not a bug in doctest. It's simply a limitation for Python libraries and you have had a corner case - a corner case that's expected and not fixable.

**Comment by pochmann** [comment]
> But if you do `exec("s = '\n'")`, it won't work.

So use a raw string: `exec(r"s = '\n'")`.

The [doctest doc](https://docs.python.org/3/library/doctest.html#which-docstrings-are-examined) also says:

> If you [...] use a backslash, you should use a raw docstring

I'd test with @pdq-self's examples, but they hid them in external tgz files, making it enormously difficult...

**Comment by gaogaotiantian** [comment]
Yes, using raw string also works.
