### ISSUE TITLE
AttributeError when calling ._target on Process objects (multiprocessing) after starting Process

### ISSUE THREAD

**Issue by Carson-Bay** [python/cpython#104356]
# Bug report

The process object just after creation has an Attribute _target that returns the function object that was passed into the initialization. After calling start() this Attribute seems to disappear and is not longer available resulting in AttirbuteError. 

# Your environment

- CPython versions tested on: Python 3.8.10 and 3.12.0a7
- Operating system and architecture: 5.10.16.3-microsoft-standard-WSL2 Ubuntu and Windows 10

**Comment by Carson-Bay** [comment]
If this is a full issue I would love to use this as an opportunity to learn how to contribute to python if possible!

**Comment by Carson-Bay** [comment]
Code to reproduce:

```python
import time
import multiprocessing

def foo():
    """Test Worker Function"""
    time.sleep(5)

p = multiprocessing.Process(target=foo)

"""Prints the function pointer"""
print(p._target)

p.start()

"""AttributeError"""
print(p._target)
```

**Comment by Tunglies** [comment]
Based on Process class works, when you start the process and it will delete self._target.
` def start(self):
        '''
        Start child process
        '''
        self._check_closed()
        assert self._popen is None, 'cannot start a process twice'
        assert self._parent_pid == os.getpid(), \
               'can only start a process object created by current process'
        assert not _current_process._config.get('daemon'), \
               'daemonic processes are not allowed to have children'
        _cleanup()
        self._popen = self._Popen(self)
        self._sentinel = self._popen.sentinel
        # Avoid a refcycle if the target function holds an indirect
        # reference to the process object (see bpo-30775)
        del self._target, self._args, self._kwargs
        _children.add(self)`

**Comment by Carson-Bay** [comment]
Seems like a weird system, couldn't find documentation about this behaviour online. Why can't the class keep self._target

**Comment by Tunglies** [comment]
> See code in [process.py](https://github.com/python/cpython/blob/main/Lib/multiprocessing/process.py) line: 110 to line: 126. Where line 125 del self._target.

**Comment by Carson-Bay** [comment]
So its done on purpose, but why?

**Comment by hugovk** [comment]
It's commented:

https://github.com/python/cpython/blob/2dcb289ed08980c8f97d538060b4ad8d5e82b56a/Lib/multiprocessing/process.py#L123-L125

The bpo reference is this issue: https://github.com/python/cpython/issues/74958

**Comment by Carson-Bay** [comment]
As someone new here I would love an explanation. Something something memory leaks when these attributes aren't deleted?

**Comment by Carson-Bay** [comment]
@gaogaotiantian I only found `._target` from ChatGPT. Of course it was used incorrectly causing this issue.

**Comment by gaogaotiantian** [comment]
> @gaogaotiantian I only found `._target` from ChatGPT. Of course it was used incorrectly causing this issue.

For future reference, I'd recommend checking the official documentation of Python first before raising an issue. Make sure that the behavior is different than what the documentation claims, that's normally a good definition of a bug. ChatGPT is not the authority for Python :)

**Comment by Carson-Bay** [comment]
Ofc, I should of realized the lack of info on _target was a sign that it doesn't have consistent behaviour. I will know for the future.
