### ISSUE TITLE
Segfault protocol.cpython

### ISSUE THREAD

**Issue by vitassuper** [python/cpython#104321]
# Crash report

Uvicorn server twice was reloaded

# Error messages

In logs on my server I got only 
```
May  9 09:50:56 vdska kernel: [586745.282012] python3[2695]: segfault at 0 ip 00007ff211e8be35 sp 00007ffdb02aa3e0 error 6 in protocol.cpython-311-x86_64-linux-gnu.so[7ff211e65000+9f000]
May  9 09:51:16 vdska kernel: [586764.689741] python3[20627]: segfault at 0 ip 00007f1d3a3b4e35 sp 00007f1d3889c1c0 error 6 in protocol.cpython-311-x86_64-linux-gnu.so[7f1d3a38e000+9f000]
```

# Your environment

- CPython versions tested on:
Python 3.11.2 (main, Mar 17 2023, 02:19:18) [GCC 10.2.1 20210110] on linux
- Operating system and architecture:
Linux 0aa90c609aa2 4.15.0-210-generic # 221-Ubuntu SMP Tue Apr 18 08:32:52 UTC 2023 x86_64 GNU/Linux

**Comment by Eclips4** [comment]
Hello!
Uvicorn is a python third-party package. Did you sure that problem in CPython?

**Comment by chgnrdv** [comment]
Error message that you provided shows that segfault occurred in shared library `protocol.cpython-311-x86_64-linux-gnu.so` that is not a part of Python standard library, but possibly a part of some third-party framework you are using.

**Comment by vitassuper** [comment]
[requirements.txt](https://github.com/python/cpython/files/11430766/requirements.txt)
Cant fetch traceback because I can reproduce this issue, It happens sometime

**Comment by sunmy2019** [comment]
> Hello, this message indicates that problem was with CPython

This is not true.

> protocol.cpython-311-x86_64-linux-gnu.so[7ff211e65000+9f000]

`protocol.cpython-311-x86_64-linux-gnu.so` is the name of a shared library, `cpython-311-x86_64-linux-gnu` only indicates its Python version.

**Comment by chgnrdv** [comment]
@vitassuper, `asyncpg` library has `protocol.cpython-311-x86_64-linux-gnu.so` component in it, although I'm not 100% sure about other libraries you are using. Maybe it makes sense to ask `asyncpg` maintainers:
https://github.com/MagicStack/asyncpg

**Comment by vitassuper** [comment]
@chgnrdv, thank you, I will check this repo

**Comment by sobolevn** [comment]
Please, reopen if you find the source of this bug in CPython itself :)
