### ISSUE TITLE
PYTHON_FOR_REGEN only works with Python 3.10 or newer

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#104487]
On current `main`, `PYTHON_FOR_REGEN` only works with Python 3.10 or newer.

Previously, we've tried to maintain backwards compatibility with older Python versions in our build system. Last time we adjusted `PYTHON_FOR_REGEN` (gh-98988), we deliberately did not bump the minimal version requirements; our `configure` checks for Python 3.11 through Python 3.6.

While working on gh-104050, a discussion about version requirements came up, and we found out that on `main`, `make clinic` only works when `PYTHON_FOR_REGEN` is Python 3.10 or newer. Also, the newly introduced "generate cases script" uses pattern matching and uses newly introduced typing features. Per now, `PYTHON_FOR_REGEN` must be 3.10 or newer.

There are two solution to this:

1. bump the `PYTHON_FOR_REGEN` version requirements to 3.10 in `configure`
2. amend the problematic build scripts, so older Python versions are still supported

Personally, I think I'm leaning towards the former. Apparently no core dev, triager or other contributor has noticed this issue until now. No buildbot has failed (we don't test the minimum required version; perhaps we should). OTOH, I understand that it makes stuff like bootstrapping slightly more cumbersome.

Anyway, we should probably at least bump the version requirement from Python 3.6 to 3.8.

### Linked PRs
* gh-104488

**Comment by erlend-aasland** [comment]
cc. @AlexWaygood, @JelleZijlstra, @hugovk

**Comment by AlexWaygood** [comment]
(FWIW, this issue was originally highlighted by running mypy on `Tools/clinic` with `--python-version=3.8`, which pointed out that `clinic.py` currently makes regular use of `types.NoneType`, a symbol that's new in Python 3.10.)

**Comment by erlend-aasland** [comment]
cc. @gvanrossum and @iritkatriel for `Tools/cases_generator/`

**Comment by erlend-aasland** [comment]
Related:

- gh-99016
- gh-99017

**Comment by gvanrossum** [comment]
I’m reluctant to have to dumb down the cases generator to 3.8. Can we please just bump the required version to 3.10? As you say there isn’t much need for earlier versions, apparently.

**Comment by erlend-aasland** [comment]
I've updated my PR with Python 3.10 as the minimum version, and I also included Python 3.12 in the list.

**Comment by sobolevn** [comment]
I also agree with bumping minimal version to 3.10 (as I said in the original issue).
I cannot imagine real-life use-cases when you need to compile the most recent Python version from source, but at the same time you don't have an access to at least 3.10

Plus, this makes writting code much more pleasant due to new typing + syntax features.

@erlend-aasland thanks for raising this! 👍

**Comment by erlend-aasland** [comment]
> I cannot imagine real-life use-cases when you need to compile the most recent Python version from source, but at the same time you don't have an access to at least 3.10

Bootstrapping Python on a new platform.

**Comment by erlend-aasland** [comment]
Resolved with:

- gh-104488
