### ISSUE TITLE
BrokenPipeError: [Errno 32] Broken pipe

### ISSUE THREAD

**Issue by NoteDance** [python/cpython#104420]
# Bug report

https://colab.research.google.com/drive/1yTfJ-fcHMdwQxxoylyUFq5cFqloTKFYi?usp=sharing:

```python
import kernel as k   #import kernel
import tensorflow as tf
import nn as n                          #import neural network
from multiprocessing import Process,Lock
mnist=tf.keras.datasets.mnist
(x_train,y_train),(x_test,y_test)=mnist.load_data()
x_train,x_test =x_train/255.0,x_test/255.0
nn=n.nn()                                #create neural network object
kernel=k.kernel(nn)   #start kernel
kernel.process_thread=7                        #thread count,use 7 processes to train
kernel.epoch_=6                #epoch:6
kernel.data(x_train,y_train)   #input you data
kernel.lock=[Lock(),Lock(),Lock()]
for _ in range(7):
	p=Process(target=kernel.train,args=(32,)) #batch size:32
	p.start()
for _ in range(7):
	p.join()
```

# Your environment

- CPython versions tested on:3.7.16
- Operating system and architecture:Windows11

When I run the program I get BrokenPipeError: [Errno 32] Broken pipe.

**Comment by sunmy2019** [comment]
1. Can you provide a full backtrace?
2. How can you tell the problem is from CPython?
3. Python 3.7.16 is no longer maintained. The minimum maintained version is 3.11 now.
4. The environment you provided did not indicate the versions of 3rd-party packages.

**Comment by NoteDancing** [comment]
@sunmy2019 
  File "C:\Users\NoteDancing\AppData\Local\Temp\ipykernel_2132\2049245860.py", line 16, in <module>
    p.start()

  File "E:\AI\anaconda3\envs\python37\lib\multiprocessing\process.py", line 112, in start
    self._popen = self._Popen(self)

  File "E:\AI\anaconda3\envs\python37\lib\multiprocessing\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File "E:\AI\anaconda3\envs\python37\lib\multiprocessing\context.py", line 322, in _Popen
    return Popen(process_obj)

  File "E:\AI\anaconda3\envs\python37\lib\multiprocessing\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)

  File "E:\AI\anaconda3\envs\python37\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)

BrokenPipeError: [Errno 32] Broken pipe
1. This is full backtrace.
2.I'm not sure if the problem is from CPython.
4.TensorFlow's version is 2.11.0.

**Comment by sunmy2019** [comment]
Can you try adding `if __name__ == "__main__":` before doing the real job?
Can you try running it on Linux?

This looks like a Windows-specific issue.

**Comment by NoteDancing** [comment]
@sunmy2019 I tried adding if __name__ == "__main__": and got the same error.I haven't a computer with Linux.

**Comment by NoteDancing** [comment]
KeyboardInterrupt                         Traceback (most recent call last)
[<ipython-input-2-56da10274574>](https://localhost:8080/#) in <cell line: 14>()
     17     p.start()
     18   for _ in range(7):
---> 19     p.join()

[/usr/lib/python3.10/multiprocessing/process.py](https://localhost:8080/#) in join(self, timeout)
    147         assert self._parent_pid == os.getpid(), 'can only join a child process'
    148         assert self._popen is not None, 'can only join a started process'
--> 149         res = self._popen.wait(timeout)
    150         if res is not None:
    151             _children.discard(self)

[/usr/lib/python3.10/multiprocessing/popen_fork.py](https://localhost:8080/#) in wait(self, timeout)
     41                     return None
     42             # This shouldn't block if wait() returned successfully.
---> 43             return self.poll(os.WNOHANG if timeout == 0.0 else 0)
     44         return self.returncode
     45 

[/usr/lib/python3.10/multiprocessing/popen_fork.py](https://localhost:8080/#) in poll(self, flag)
     25         if self.returncode is None:
     26             try:
---> 27                 pid, sts = os.waitpid(self.pid, flag)
     28             except OSError:
     29                 # Child process not yet created. See #1731717

KeyboardInterrupt:

@sunmy2019 This is the error when running on Google Colab.

**Comment by NoteDancing** [comment]
Traceback (most recent call last):

  Cell In[3], line 4
    p.start()

  File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\process.py:121 in start
    self._popen = self._Popen(self)

  File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\context.py:224 in _Popen
    return _default_context.get_context().Process._Popen(process_obj)

  File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\context.py:336 in _Popen
    return Popen(process_obj)

  File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\popen_spawn_win32.py:94 in __init__
    reduction.dump(process_obj, to_child)

  File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\reduction.py:60 in dump
    ForkingPickler(file, protocol).dump(obj)

TypeError: cannot pickle 'weakref.ReferenceType' object

@sunmy2019 I just got this error using python3.11.3 on Windows11.

**Comment by eryksun** [comment]
What is `nn` that has an `nn.nn()` callable? The neural network package for TensorFlow has no such callable.

Also, the following snippet makes no sense. It tries to `join()` the same process 7 times.

```python
for _ in range(7):
	p=Process(target=kernel.train,args=(32,)) #batch size:32
	p.start()
for _ in range(7):
	p.join()
```

The process objects should be added to a list. Then iterate the list to `join()` each of them.

**Comment by liguo-ri** [comment]
+1

**Comment by gaogaotiantian** [comment]
> Traceback (most recent call last):
> 
> Cell In[3], line 4 p.start()
> 
> File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\process.py:121 in start self._popen = self._Popen(self)
> 
> File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\context.py:224 in _Popen return _default_context.get_context().Process._Popen(process_obj)
> 
> File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\context.py:336 in _Popen return Popen(process_obj)
> 
> File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\popen_spawn_win32.py:94 in **init** reduction.dump(process_obj, to_child)
> 
> File E:\AI\anaconda3\envs\python311\Lib\multiprocessing\reduction.py:60 in dump ForkingPickler(file, protocol).dump(obj)
> 
> TypeError: cannot pickle 'weakref.ReferenceType' object
> 
> @sunmy2019 I just got this error using python3.11.3 on Windows11.

On Windows, you have to make sure your target function is pickleable - because it uses `spawn`. I don't know what your `kernel` is, but I doubt it could be pickled. When you do `Process(target=kernel.train,args=(32,))`, `multiprocessing` tries to pass `kernel.train` by pickling. You can try to reproduce this issue by `pickle.dumps(kernel.train)`. May have the same error.

**Comment by NoteDancing** [comment]
@sunmy2019 @gaogaotiantian @eryksun Thank you for your answers.
