### ISSUE TITLE
Some instructions and specializations ignore PEP 523

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#104405]
Four instructions ignore PEP 523 when executing:

- `BINARY_SUBSCR_GETITEM`
- `FOR_ITER_GEN`
- `SEND`
- `SEND_GEN`

Five instructions ignore it when specializing:

- `BINARY_SUBSCR_GETITEM`
- `FOR_ITER_GEN`
- `LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN`
- `LOAD_ATTR_PROPERTY`
- `SEND_GEN`

I'll have a PR up soon.

### Linked PRs
* gh-104406
* gh-104441

**Comment by terryjreedy** [comment]
https://peps.python.org/pep-0523/
