### ISSUE TITLE
Consider adding test_asyncio for PGO test

### ISSUE THREAD

**Issue by corona10** [python/cpython#104426]
From @carljm, I can hear the effect of adding the test_asyncio for the test suite that contributes to their CPU workload.
When I added the test_asyncio to the PGO test suite, it didn't degrade the overall Python performance workload.
And I also got a positive result from asyncio test group.
see: https://gist.github.com/corona10/985c03c34cf0441d2294148fff08f97f

So I would like to suggest adding the test_asyncio as the PGO test suite group.
(one line patch is already prepared).

### Linked PRs
* gh-104429

**Comment by gvanrossum** [comment]
Oh, okay. The PGO workload is a black art anyway…

**Comment by gpshead** [comment]
Thanks for trying this, it's always good to check if we're missing out.  See the comment thread on the PR though.  Adding this didn't appear to make a meaningful performance change.

We used to run most of the entire test suite which wasn't adding meaningful value vs what we run today.  See https://github.com/python/cpython/issues/80225 for that change.

https://github.com/faster-cpython/ideas/issues/547 and its linked to 99 also sort of cover this topic.

**Comment by corona10** [comment]
> Thanks for trying this, it's always good to check if we're missing out. See the comment thread on the PR though. Adding this didn't appear to make a meaningful performance change.

**Comment by gpshead** [comment]
The test_asyncio suite is huge and slow. Surely just running some tiny (non-slow) subset of it will provide plenty of PGO data for that kind of targeted improvement. If we're going to add anything, find such a fast subset and figure out how to only have that added to the run.

Reread https://github.com/python/cpython/issues/80225 for why we don't just run the entire test suite and our slow tests in PGO builds anymore.

**Comment by corona10** [comment]
Close the issue until it's actually needed.
