### ISSUE TITLE
Py_FileSystemDefaultEncoding stable limited API and deprecated?

### ISSUE THREAD

**Issue by illume** [python/cpython#104477]
Hi,

Py_FileSystemDefaultEncoding is both documented as the stable limited API and as deprecated.

- Probably the docs on https://docs.python.org/3.12/c-api/stable.html need updating?
- What's the replacement for getting it inside an extension? That's not clear to me.

all the best,

**Comment by sunmy2019** [comment]
Check this commit: https://github.com/python/cpython/commit/0ff626f210c69643d0d5afad1e6ec6511272b3ce

**Comment by sunmy2019** [comment]
https://docs.python.org/3.12/whatsnew/3.12.html#id4

**Comment by illume** [comment]
Hi.

Thanks!

The two things I was interested in:

- There is no replacement documented I could find. Seems there isn't, not just that I couldn't find it.
- It is documented as both stable and deprecated at the same time. That is contradictory. It's potentially a problem for those who tried to use what is labeled as the limited / stable thingo.

I had already seen the release notes and the commit.

Anyway... moving on. Thanks for your time.

cheers!

**Comment by sunmy2019** [comment]
> both stable and deprecated at the same time.

Stable API deprecation will go through several minor versions, and people will get this information foreahead.

Unstable APIs can be deprecated without notice.

Stable != Forever

**Comment by illume** [comment]
Thanks. I don’t need further explanation. Good day to you.
