### ISSUE TITLE
datetime.datetime.fromisoformat throws error for a valid ISO string

### ISSUE THREAD

**Issue by jain-divy** [python/cpython#104434]

**Comment by AlexWaygood** [comment]
Please don't upload images of code. Just copy and paste the code that you ran. For why uploading images of code is a bad idea, please see https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors

**Comment by sunmy2019** [comment]
This is fixed on 3.11. https://godbolt.org/z/4afKfo3xn

3.9 and 3.10 is security-fix-only.
