### ISSUE TITLE
Tkinter: Tk 8.7 alphabetizes options in certain error messages

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#104497]
As done by e.g. https://core.tcl-lang.org/tk/info/b7db31b3a38b and causing this Tkinter test to fail:

```
======================================================================
FAIL: test_configure_type (test.test_tkinter.test_widgets.MenuTest.test_configure_type)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/git/cpython/Lib/test/test_tkinter/test_widgets.py", line 1403, in test_configure_type
    self.checkEnumParam(
  File "/Users/user/git/cpython/Lib/test/test_tkinter/widget_tests.py", line 134, in checkEnumParam
    self.checkInvalidParam(widget, name, 'spam', errmsg=errmsg)
  File "/Users/user/git/cpython/Lib/test/test_tkinter/widget_tests.py", line 63, in checkInvalidParam
    self.assertEqual(str(cm.exception), errmsg)
AssertionError: 'bad type "spam": must be menubar, normal, or tearoff' != 'bad type "spam": must be normal, tearoff, or menubar'
- bad type "spam": must be menubar, normal, or tearoff
+ bad type "spam": must be normal, tearoff, or menubar
```

### Linked PRs
* gh-104789
* gh-105028
* gh-105029

**Comment by sunmy2019** [comment]
And if you want a little more, you can use
```py
>>> from collections import Counter
>>> Counter("1234") == Counter("3412")
True
```

**Comment by terryjreedy** [comment]
@sunmy2019  As near as I can tell from from searching _tkinter.c and tkinter/__init__.py, the actual error message is from tcl/tk.  If so, all that needs testing is that as error is raised with 'spam' in the message.  The options in the expected message come from the test itself, so a mismatch would indicate an error in tcl/tk, which we are not trying to test, or in the test, from being overy specific.

@chrstphrchvz The title and linked tcl issue suggest that multiple messages have been revised.  If so, a special case fix for one test would be insufficient.

**Comment by chrstphrchvz** [comment]
> @chrstphrchvz The title and linked tcl issue suggest that multiple messages have been revised. If so, a special case fix for one test would be insufficient.

Understood, however this is currently the only test I have found to be affected by alphabetizing changes.

**Comment by terryjreedy** [comment]
Then I will make a PR to fix just that test.
