### ISSUE TITLE
Some unicode variables can't be accessed with `getattr`

### ISSUE THREAD

**Issue by deoktr** [python/cpython#104458]
# Bug report

Some unicode variables names can't be accessed with `getattr` and are changed.

```python
>>> class a:
...     ʷ=1
...     Ẩ=2
...     b=3
...
>>> a.ʷ
1
>>> a.Ẩ
2
>>> a.b
3
>>> getattr(a, "b")
3
>>> getattr(a, "Ẩ")
2
>>> getattr(a, "ʷ")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'a' has no attribute 'ʷ'
>>> getattr(a, "\u02b7")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'a' has no attribute 'ʷ'
>>> a.__dict__
mappingproxy({'__module__': '__main__', 'w': 1, 'Ẩ': 2, 'b': 3, '__dict__': <attribute '__dict__' of 'a' objects>, '__weakref__': <attribute '__weakref__' of 'a' objects>, '__doc__': None})
>>> a.w
1
>>> getattr(a, "w")
1
>>> a.__dict__["w"]
1
>>> a.__dict__["ʷ"]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'ʷ'
```

In the dict we can see that the symbol `w` is not the same as `ʷ` (`\u02b7` "Modifier Letter Small W").

Looks like unicode using [Spacing Modifier Letters](https://en.wikipedia.org/wiki/Spacing_Modifier_Letters) are all affected, there is maybe more.

Here is a quick and dirty code to list problematic unicodes:

```python
count = 0
for unicode_code in range(0, 0xFFFFF):
    char = chr(unicode_code)
    code = f"class a:\n {char}=None"
    try:
        exec(code)
    except:
        pass
    else:
        code = f"class a:\n {char}=None\ngetattr(a, {repr(char)})"
        try:
            exec(code)
        except AttributeError:
            print(f"\\u{unicode_code} ({char})")
            count += 1
print(count)
```

I found that 3411 unicodes are having this issue.

# Your environment

- CPython versions tested on: Python 3.10.10 (main, Mar  5 2023, 22:26:53) [GCC 12.2.1 20230201] on linux
- Operating system and architecture: linux x86_64

**Comment by gaogaotiantian** [comment]
This is probably intentional. In `_PyPegen_new_identifier`, the `id` is normalized by `unicodedata.normalize("NFKC", id)` ([docs](https://docs.python.org/3/library/unicodedata.html?highlight=unicodedata#unicodedata.normalize)). So `"ʷ"` is intentially converted to `"w"` as an identifier. If there's explicit code in the parser, this may not be a bug.

**Comment by terryjreedy** [comment]
Same on main on Win10.
Tian is correct:  https://docs.python.org/3/reference/lexical_analysis.html#identifiers says
> All identifiers are converted into the normal form NFKC while parsing; comparison of identifiers is based on NFKC.

**Comment by sunmy2019** [comment]
> This is probably intentional.

This is added here:
https://github.com/we-like-parsers/cpython/pull/108

I am not an expert on Unicode. Probably, the conversion here helped solve some technical issues.

@pablogsal as the original committer

**Comment by ericvsmith** [comment]
Since this is documented, I'm closing the issue.
