### ISSUE TITLE
Spelling error? On tkinter — Python interface to Tcl/Tk page 

### ISSUE THREAD

**Issue by Alakazella** [python/cpython#104489]
Not sure if this is a spelling error or should be this way.  On the Tkinter Python interface to Tcl/Tk page. There is the use of "MAN" page.  I think this should be main. Or am I wrong? 

[https://docs.python.org/3/library/tkinter.html#navigating-the-tcl-tk-reference-manual](url)

Navigating the Tcl/Tk Reference Manual
As noted, the official [Tk commands](https://www.tcl.tk/man/tcl8.6/TkCmd/contents.htm) reference manual (**man** pages) is often the most

In the official Tcl/Tk reference documentation, you’ll find most operations that look like method calls on the man page for a specific widget (e.g., you’ll find the invoke() method on the [ttk::button](https://www.tcl.tk/man/tcl8.6/TkCmd/ttk_button.htm) **man** page), while functions that take a widget as a parameter often have their own **man** page (e.g., [grid](https://www.tcl.tk/man/tcl8.6/TkCmd/grid.htm)).

You’ll find many common options and methods in the [options](https://www.tcl.tk/man/tcl8.6/TkCmd/options.htm) or [ttk::widget](https://www.tcl.tk/man/tcl8.6/TkCmd/ttk_widget.htm) **man** pages, while others are found in the **man** page for a specific widget class.

You’ll also find that many Tkinter methods have compound names, e.g., winfo_x(), winfo_height(), winfo_viewable(). You’d find documentation for all of these in the [winfo](https://www.tcl.tk/man/tcl8.6/TkCmd/winfo.htm) **man** page.

**Comment by ned-deily** [comment]
Thanks for your report but the references to `man` pages are indeed correct.  See [here](https://en.m.wikipedia.org/wiki/Man_page) for an explanation.
