### ISSUE TITLE
Tkinter: test_getint incompatible with Tcl 9.0

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#104411]
[TIP 114](https://core.tcl-lang.org/tips/doc/trunk/tip/114.md) means that as of Tcl 9.0, integers are only treated as octal when the `0o` prefix is specified; a leading 0 by itself is no longer sufficient. This change partially breaks test_getint:

```
======================================================================
FAIL: test_getint (test.test_tcl.TclTest.test_getint)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/git/cpython/Lib/test/test_tcl.py", line 145, in test_getint
    self.assertEqual(tcl.getint((' %#o ' % i).replace('o', '')), i)
AssertionError: 17777777777 != 2147483647
```

### Linked PRs
* gh-104412
* gh-105356
* gh-105357

**Comment by terryjreedy** [comment]
Please add the topic-tkinter label to these tkinter posts so they do not get lost.
