### ISSUE TITLE
test_exceptions are leaked

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104454]
Tried on [last commit](https://github.com/python/cpython/commit/46f1c78eebe08e96ed29d364b1804dd37364831d)
```python
PS C:\Users\KIRILL-1\CLionProjects\cpython> ./python -m test -R 3:3 test_exceptions
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_exceptions
beginning 6 repetitions
123456
......
test_exceptions leaked [18, 18, 18] references, sum=54
test_exceptions leaked [12, 12, 12] memory blocks, sum=36
test_exceptions failed (reference leak) in 38.1 sec

== Tests result: FAILURE ==

1 test failed:
    test_exceptions

Total duration: 38.2 sec
Tests result: FAILURE
```
OS: Windows 10

### Linked PRs
* gh-104455

**Comment by iritkatriel** [comment]
More specifically:

```
% ./python.exe -m test -R3:3 test_exceptions -m testAttributes 
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 3.46 Run tests sequentially
0:00:00 load avg: 3.46 [1/1] test_exceptions
beginning 6 repetitions
123456
......
test_exceptions leaked [18, 18, 18] references, sum=54
test_exceptions leaked [12, 12, 12] memory blocks, sum=36
test_exceptions failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_exceptions

Total duration: 256 ms
Tests result: FAILURE

```

**Comment by csm10495** [comment]
PR opened to fix. Thanks folks. For my benefit: Why doesn't this test run on PRs?

**Comment by AlexWaygood** [comment]
> PR opened to fix. Thanks folks. For my benefit: Why doesn't this test run on PRs?

Running the refleak tests generally takes a while, and isn't necessary for most PRs to CPython. We have a label we can add to PRs to trigger the test being run; in this case, looks like we just forgot to add that label to this PR. It's not a big issue; happens quite often around here :-)

**Comment by gpshead** [comment]
thanks for the fix. I missed this leak in review (easy for anyone to miss - our C API is full of sharp edges) and didn't think to trigger the refleaks buildbots on the original PR. it happens, no worries.
