### ISSUE TITLE
 itertools.combinations cause memory overflow and crash

### ISSUE THREAD

**Issue by xaoyaoo** [python/cpython#104419]
# Crash report

```python
import itertools

lst = list(range(1, 76))  # [1, 2, 3, ..., 74, 75]

comb = itertools.combinations(lst,60) 
comb_lst = list(comb)

print(len(comb_lst))
print(comb_lst[:5])`
```

Running this code will result in a memory overflow, causing the computer to crash.

# Error messages

no error message.

# Your environment

Windows 11 operating system and Python version 3.10.

**Comment by xaoyaoo** [comment]
Of course not, but I think Python should evaluate the machine's performance and raise an error if the code is likely to cause a crash.

**Comment by sunmy2019** [comment]
On Windows you will always get memory requests fulfilled, the system just tries very hard to swap out.

It's up to the OS how much memory is left. It should not be guarded from the Python side.

**Comment by xaoyaoo** [comment]
Okay, you've convinced me.

**Comment by terryjreedy** [comment]
The interpreter tries, but does not guarantee , to exit gracefully.  Behavior depends on OS.
https://docs.python.org/3/library/exceptions.html#MemoryError
