### ISSUE TITLE
RTSPS scheme support in urllib.parse

### ISSUE THREAD

**Issue by zentarim** [python/cpython#104554]
In accordance with
https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml

There are three valid RTSP schemes: 

URI Scheme | Description | Status | Reference 
-- | -- | -- | -- 
rtsp | Real-Time Streaming Protocol (RTSP) | Permanent | [RFC2326][RFC7826] 
rtsps | Real-Time Streaming Protocol (RTSP) over TLS | Permanent | [RFC2326][RFC7826] 
rtspu | Real-Time Streaming Protocol (RTSP) over unreliable datagram transport | Permanent | [RFC2326]

But in `urllib/parse.py` only two of them are defined:
- rtsp
- rtspu

What make impossible to use functions like `urllib.parse.urljoin()` upon `rtsps://*` URLs:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urljoin
>>> urljoin('rtsps://127.0.0.1/foo/bar', 'trackID=1')
'trackID=1'
```
Expected result is:
```
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import urljoin
>>> urljoin('rtsps://127.0.0.1/foo/bar', 'trackID=1')
'rtsps://127.0.0.1/foo/trackID=1'
>>> 
```

I was able to get the expected behavior by patching `urllib/parsing.py`:
```
--- parse.py.bak        2023-05-16 16:16:01.910634526 +0000
+++ parse.py    2023-05-16 16:17:35.793154580 +0000
@@ -46,17 +46,17 @@
 
 uses_relative = ['', 'ftp', 'http', 'gopher', 'nntp', 'imap',
                  'wais', 'file', 'https', 'shttp', 'mms',
-                 'prospero', 'rtsp', 'rtspu', 'sftp',
+                 'prospero', 'rtsp', 'rtsps', 'rtspu', 'sftp',
                  'svn', 'svn+ssh', 'ws', 'wss']
 
 uses_netloc = ['', 'ftp', 'http', 'gopher', 'nntp', 'telnet',
                'imap', 'wais', 'file', 'mms', 'https', 'shttp',
-               'snews', 'prospero', 'rtsp', 'rtspu', 'rsync',
+               'snews', 'prospero', 'rtsp', 'rtsps', 'rtspu', 'rsync',
                'svn', 'svn+ssh', 'sftp', 'nfs', 'git', 'git+ssh',
                'ws', 'wss']
 
 uses_params = ['', 'ftp', 'hdl', 'prospero', 'http', 'imap',
-               'https', 'shttp', 'rtsp', 'rtspu', 'sip', 'sips',
+               'https', 'shttp', 'rtsp', 'rtsps', 'rtspu', 'sip', 'sips',
                'mms', 'sftp', 'tel']
 
 # These are not actually used anymore, but should stay for backwards
@@ -66,7 +66,7 @@
                     'telnet', 'wais', 'imap', 'snews', 'sip', 'sips']
 
 uses_query = ['', 'http', 'wais', 'imap', 'https', 'shttp', 'mms',
-              'gopher', 'rtsp', 'rtspu', 'sip', 'sips']
+              'gopher', 'rtsp', 'rtsps', 'rtspu', 'sip', 'sips']
 
 uses_fragment = ['', 'ftp', 'hdl', 'http', 'gopher', 'news',
                  'nntp', 'wais', 'https', 'shttp', 'snews',

```

The issue presents in Python versions:

- 3.10.6
- 3.12.0a7

### Linked PRs
* gh-104605
* gh-105759
* gh-105760

**Comment by terryjreedy** [comment]
All 3 are premanent schemes;  RTSPS is RTSP over TLS, while RTSPU is same over unreliable datagram.  Can you make a PR?
@orsenthil

**Comment by zentarim** [comment]
> All 3 are premanent schemes; RTSPS is RTSP over TLS, while RTSPU is same over unreliable datagram. Can you make a PR? @orsenthil

Sorry, but I did not get you. Who you're asking about a PR? Me or @orsenthil ?

**Comment by orsenthil** [comment]
@zentarim thanks for the report. You could submit PR, if you prefer. I guess, my mention was a cc.

**Comment by terryjreedy** [comment]
zentarim, I actually meant you.  I was not sure if Senthil was currently available.  I should have been clearer.

Senthil, since you *are* available, do you agree that this should be added?  Do the suggested additions look right?  (I would assume that RTSPS should appear wherever RTSPU does.)  New feature or bugfix?

**Comment by orsenthil** [comment]
> do you agree that this should be added? 

@terryjreedy  - yes. I agree. In previous additions similar to this, we considered this a feature and didn't backport it. I think, it is safer to consider it as feature as changes the behavior.

Although, someone who really needed rtsps protocol parsing without this change, I assume, would have patched the module locally in their code and worked around it.

**Comment by orsenthil** [comment]
> Do the suggested additions look right? (I would assume that RTSPS should appear wherever RTSPU does.) 

This looks right to me. Thinking as bug-fix seems alright here.

**Comment by hauntsaninja** [comment]
Looks like this was implemented, thanks all!
