### ISSUE TITLE
Values CANNOT be indented despite contrary statement in the docs

### ISSUE THREAD

**Issue by ullix** [python/cpython#104505]
The [docs state](https://docs.python.org/3/library/configparser.html): 
```ini
[You can use comments]
    [Sections Can Be Indented]
        can_values_be_as_well = True
```
but while sections can indeed be indented, indenting values results in an Exception.

Simple code:
```python
#! /usr/bin/env python3
# -*- coding: UTF-8 -*-

import configparser

config = configparser.ConfigParser()
with open("testconfigparser.cfg") as f:
    config.read_file(f)

print(config.get("alpha", "alpha1"))
print(config.get("alpha", "alpha2"))
print(config.get("alpha", "alpha3"))
print(config.get("alpha", "alpha4"))
```

Simple config file:
```ini
## configparsertest.cfg

    [alpha]
alpha1    = 100
alpha2    = 200
 alpha3    = 300
alpha4    = 400
```
Result of having alpha3 (inadvertently) indented by a single space is:
```pytb
$ python testconfigparser.py 
100
200
alpha3    = 300
Traceback (most recent call last):
  File "/usr/lib/python3.9/configparser.py", line 789, in get
    value = d[option]
  File "/usr/lib/python3.9/collections/__init__.py", line 941, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.9/collections/__init__.py", line 933, in __missing__
    raise KeyError(key)
KeyError: 'alpha3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ullix/geigerlog/geigerlog/misc/Bugs/testconfigparser.py", line 12, in <module>
    print(config.get("alpha", "alpha3"))
  File "/usr/lib/python3.9/configparser.py", line 792, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'alpha3' in section: 'alpha'
```

**Comment by Eclips4** [comment]
Hello!
This is a intended behavior.
Doc says:
In config parsers, values can span multiple lines as long as they are indented more than the key that holds them. By default parsers also let empty lines to be parts of values. At the same time, keys can be arbitrarily indented themselves to improve readability. In consequence, when configuration files get big and complex, it is easy for the user to lose track of the file structure. Take for instance:
```
[Section]
key = multiline
  value with a gotcha

 this = is still a part of the multiline value of 'key'
 ```

**Comment by sunmy2019** [comment]
And if you want a little more, you can use
```py
>>> from collections import Counter
>>> Counter("1234") == Counter("3412")
True
```

**Comment by ullix** [comment]
Well, this 'intended behavior' reminds me a bit of one big company famous for declaring bugs a features :-(.

Why would you even care about making sections indent-able, and so protect users from a type due to an extra space, when at the same time you are converting such a typo towards a completely different meaning?

At the very least, you'll have to rework the docs, as the current content clearly doe not do justice to what you actually do!

Apart from that, the lib is nice!

**Comment by Cherrymelon** [comment]
Doc had said it,maybe this part need more clearly ？

**Comment by AA-Turner** [comment]
This isn't a bug per Kirill.

A
