### ISSUE TITLE
Ref leaks introduced by _io isolation (gh-101948)

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104510]
Tried on current main.
```python
./python -m test -R 3:3 test_nntplib
0:00:00 load avg: 2.49 Run tests sequentially
0:00:00 load avg: 2.49 [1/1] test_nntplib
beginning 6 repetitions
123456
......
test_nntplib leaked [1222, 1220, 1222] references, sum=3664
test_nntplib leaked [828, 827, 829] memory blocks, sum=2484
test_nntplib failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_nntplib

Total duration: 640 ms
Tests result: FAILURE
```
OS: WSL Ubuntu 20.04 & Windows 10

UPD:
Leaked tests:
test_nntplib
test_gzip
test_httpservers
test_xmlrpc
test_tarfile

### Linked PRs
* gh-104516

**Comment by Eclips4** [comment]
[Commit](https://github.com/python/cpython/commit/186bf39f5c6003912e4f445430c504db51b9a743) which introduced it
@erlend-aasland

**Comment by Eclips4** [comment]
> > [Commit](https://github.com/python/cpython/commit/186bf39f5c6003912e4f445430c504db51b9a743) which introduced it
> > cc @erlend-aasland
> 
> Nice! We anticipated errors :) cc. @kumaraditya303 @vstinner

However, `nttplib` deprecated since 3.11. So, it's good that it wasn't cut out in 3.12 😄

**Comment by kumaraditya303** [comment]
On which buildbot it is failing?

**Comment by Eclips4** [comment]
test_gzip also affected by this commit:
```python
./python -m test -R 3:3 test_gzip
0:00:00 load avg: 0.00 Run tests sequentially
0:00:00 load avg: 0.00 [1/1] test_gzip
beginning 6 repetitions
123456
......
test_gzip leaked [4307, 4303, 4307] references, sum=12917
test_gzip leaked [3239, 3237, 3239] memory blocks, sum=9715
test_gzip failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_gzip

Total duration: 4.0 sec
Tests result: FAILURE
```

**Comment by Eclips4** [comment]
test_httpservers, test_xmlrpc, test_tarfilecause also cause reference leaks.

**Comment by sunmy2019** [comment]
@Eclips4 You can try doing similar things in #104457
186bf39 introduces three heap types, and none have a correct `*_clear` set.
https://github.com/python/cpython/blob/186bf39f5c6003912e4f445430c504db51b9a743/Modules/_io/_iomodule.c#L681-L687

**Comment by Eclips4** [comment]
> @Eclips4 You can try doing similar things in #104457 [186bf39](https://github.com/python/cpython/commit/186bf39f5c6003912e4f445430c504db51b9a743) introduces three heap types; none have a `*_clear` set.
> 
> https://github.com/python/cpython/blob/186bf39f5c6003912e4f445430c504db51b9a743/Modules/_io/_iomodule.c#L681-L687
> 
> But I have not carefully examined the correct value, and I am unsure whether this will fix the issue.

Sure! I can try this, and later let you know results.

**Comment by Eclips4** [comment]
Seems that implementing `Py_tp_clear` for `textiobase_spec`, `bufferediobase_spec`, `rawiobase_spec` doesn't make sense. There's no need in it. I'll check other types in `iomodule_exec`.

**Comment by erlend-aasland** [comment]
Bisected and confirmed that 186bf39f5c6003912e4f445430c504db51b9a743 is the first bad commit.

**Comment by kumaraditya303** [comment]
#104516 fixes all the leaks meantioned

**Comment by kumaraditya303** [comment]
Thanks for the report.
