### ISSUE TITLE
incorrect tb_lasti on exceptions originating from calls to outer functions

### ISSUE THREAD

**Issue by dankeyy** [python/cpython#104513]
Consider the following code where the try contents call to a function outside the try except block
```py
def g():
    [][1]

try:
    g()
except Exception as e:
    t = e.__traceback__
    print(list(t.tb_frame.f_code.co_positions())[t.tb_lasti])
```
wrongly produces
`(7, 7, 8, 23)`

this works fine though
```py
try:
    [][1]
except Exception as e:
    t = e.__traceback__
    print(list(t.tb_frame.f_code.co_positions())[t.tb_lasti])
```
`(2, 2, 4, 9)`
- CPython versions tested on: Python 3.11.3
- Operating system and architecture: nixos

dk why it added the type-bug label btw, mods should remove it

**Comment by terryjreedy** [comment]
@irit Who would know about co_positions and tb_lasti?

**Comment by iritkatriel** [comment]
cc @markshannon

**Comment by brandtbucher** [comment]
If I understand correctly, I think the issue is that `co_positions` returns one entry per code unit, while `tb_lasti` is in bytes (two per code unit).

If you change...

```py
list(t.tb_frame.f_code.co_positions())[t.tb_lasti]
```

...to...

```py
list(t.tb_frame.f_code.co_positions())[t.tb_lasti // 2]
```

...then it should give you the right positions in all cases.

**Comment by dankeyy** [comment]
> If I understand correctly, I think the issue is that `co_positions()` yields one entry per _code unit_, while `tb_lasti` is in _bytes_. There are two _bytes_ per _code unit_, so `tb_lasti` needs to be adjusted before it's used this way.
> 
> If you change...
> 
> ```python
> list(t.tb_frame.f_code.co_positions())[t.tb_lasti]
> ```
> 
> ...to...
> 
> ```python
> list(t.tb_frame.f_code.co_positions())[t.tb_lasti // 2]
> ```
> 
> ...then it should give you the right positions in all cases.

yea my bad, thanks
