### ISSUE TITLE
Error message for walrus etc. in PEP 695 contexts could be improved

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104572]
Before:

```
>>> type A[T: (x:=3)] = int
  File "<stdin>", line 1
SyntaxError: 'named expression' can not be used within a TypeVar bound
```

After:

```
>>> type A[T: (x:=3)] = int
  File "<stdin>", line 1
SyntaxError: named expression cannot be used within a TypeVar bound
```

("cannot" is one word; the quotes don't really make sense here)

### Linked PRs
* gh-104573

**Comment by JelleZijlstra** [comment]
It would also be nice if the error display had a ^ pointing to the precise location. Unfortunately that appears to be difficult, as the error is raised in symtable.c where we no longer have access to the original source. The same thing happens with other syntax errors raised in symtable.c:

```
>>> def f(a, a): pass
... 
  File "<stdin>", line 1
SyntaxError: duplicate argument 'a' in function definition
```

**Comment by terryjreedy** [comment]
The quotes might have come from thinking of 'named expression' as a grammar target, but then it would have to really be in the doc grammar and would need a hyphen.  Error messages should save quotes for quotes from the code, as with 'a' above.
