### ISSUE TITLE
Indentation issue in logging.config documentation page

### ISSUE THREAD

**Issue by jnoordsij** [python/cpython#104539]
# Documentation

The parameter block of the `logging.config.fileConfig` function has a misindented `encoding` parameter listed; this also causes the description of the previous `disable_existing_loggers` parameter to be misaligned.

For reference, this is a screenshot taken from https://docs.python.org/3/library/logging.config.html#logging-config-fileformat at 2023/05/16 around 12:45 GMT+2.
![afbeelding](https://github.com/python/cpython/assets/45041769/b34d828e-47ff-4802-9339-101a64a66966)

### Linked PRs
* gh-104540
* gh-104545
* gh-104546

**Comment by AlexWaygood** [comment]
Thanks @jnoordsij!
