### ISSUE TITLE
Generate AST for Python 2 syntax in Python 3  - AST module

### ISSUE THREAD

**Issue by KarthickRaja2002** [python/cpython#104541]
Hi,
   I need to parse Python code into AST to do analysis on top of AST. Irrelevant of the Python version, the AST should be
generated for both the Python 2 and Python 3. 

Does Python 3 AST compiler supports backward compatibility. I don't want solution like, first i should try parsing with Python 3 if it fails, fallback parser to Python 2. Instead parse all type of syntax in Python 3 AST.

```
import ast
ast_tree = ast.parse(
'''
num = 20
print(num)
print num
'''
)
```

Thanks in advance.

**Comment by sobolevn** [comment]
No, this is not possible. Python3 AST is not compatible with Python2 AST.
And I am pretty sure that no one is interested in supporting Python2 syntax anymore.

However, it can be a good project for 3rd party! You can check https://github.com/we-like-parsers/ and use it to parse Python2.

I am going to close this issue, unless no one objects :)
