### ISSUE TITLE
TypeVars created via PEP-695 mechanisms have a different repr to other TypeVars

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#104644]
There's a strange inconsistency between the repr of `TypeVar`s constructed using PEP-695 mechanisms, and `TypeVar`s created by directly calling the `typing.TypeVar` constructor. This is despite the fact that they report being the same class at runtime:

```pycon
>>> from typing import TypeVar
>>> T = TypeVar("T")
>>> T
~T
>>> class Foo[T2]: ...
...
>>> T2 = Foo.__type_params__[0]
>>> T2
T2
>>> type(T2) is type(T)
True
>>> T.__name__
'T'
>>> T2.__name__
'T2'
```

Cc. @JelleZijlstra

**Comment by sunmy2019** [comment]
At least, this is intended.

Try this:
```
>>> print(T.__infer_variance__, T2.__infer_variance__)
False True
```

```c
static PyObject *
paramspec_repr(PyObject *self)
{
    paramspecobject *ps = (paramspecobject *)self;

    if (ps->infer_variance) {
        return Py_NewRef(ps->name);
    }

    char variance = ps->covariant ? '+' : ps->contravariant ? '-' : '~';
    return PyUnicode_FromFormat("%c%U", variance, ps->name);
}
```

**Comment by AlexWaygood** [comment]
Ah, I forgot that the `~` actually had a semantic meaning behind it, and that it indicated the variance of the TypeVar!

We can maybe just close this, in that case. Though I do still think the difference in repr is somewhat confusing here. I'd guess most other people also have no idea that the `~` is meant to indicate that the TypeVar is invariant.

**Comment by JelleZijlstra** [comment]
Yes, this is how I implemented the `infer_variance` argument:

```pycon
>>> TypeVar("T", infer_variance=True)
T
>>> class Foo[T2]: pass
... 
>>> T2, = Foo.__type_params__
>>> T2
T2
```

If you have suggestions for how to improve the repr() of TypeVars I'd be interested, but I'm going to remove the bugs topic.

**Comment by AlexWaygood** [comment]
I have no concrete suggestions, no, and I guess my real gripe is with the repr of old-style TypeVars — which we can't change now, for backwards-compatibility reasons. So, we can close this for now.
