### ISSUE TITLE
Documentation for tarfile has ambigouous references for releases

### ISSUE THREAD

**Issue by JMCanning78** [python/cpython#104638]
# Documentation

The documentation for `TarFile.extraction_filter` under "New in version 3.11.4." it states:
"In Python 3.12+, leaving extraction_filter=None will emit a DeprecationWarning.

In Python 3.14+, leaving extraction_filter=None will cause extraction methods to use the [data](https://docs.python.org/3.11/library/tarfile.html?highlight=tar#tarfile.data_filter) filter by default."

Perhaps this is a forward looking comment about behavior to expect in Python releases 3.12 and 3.14, but I suspect that they should instead be something like "Python 3.11.2+" and "Python 3.11.4+" to document existing behavior.

### Linked PRs
* gh-109908

**Comment by JMCanning78** [comment]
I don't see a way to add labels to this issue, but it should have 3.11 label attached.

**Comment by JelleZijlstra** [comment]
The text as written is correct: this is the anticipated behavior in 3.12 and 3.14. cc @encukou for tarfile filters.

Do you have suggestions for how to make this clearer?

**Comment by JMCanning78** [comment]
I guess I don't have a better wording to suggest. When I saw that release 3.13 was skipped, I expected that there was some kind of mistake.

**Comment by zware** [comment]
Perhaps instead of `Python 3.12+`, make it `Python 3.12 and 3.13`?

**Comment by hugovk** [comment]
@JMCanning78 Would you like to make a PR with @zware's suggestion?

**Comment by hadrizi** [comment]
@JMCanning78 are you working on this issue? If not @hugovk can I take it?

**Comment by hugovk** [comment]
@hadrizi Sure, go for it.

**Comment by hadrizi** [comment]
I think this problem is no longer relevant after the changes in #122002

cc @hugovk @JMCanning78

**Comment by hugovk** [comment]
Thanks, https://github.com/python/cpython/pull/122002 removed this bit of text, so let's close this issue and its PR: https://github.com/python/cpython/pull/109908.
