### ISSUE TITLE
test_mmap are leaked

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104698]
Tried on current main branch.
```python
 ./python -m test -R 3:3 test_mmap
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_mmap
beginning 6 repetitions
123456
......
test_mmap leaked [13, 13, 13] references, sum=39
test_mmap failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_mmap

Total duration: 1.3 sec
Tests result: FAILURE
```
OS: Windows 10 & WSL Ubuntu 20.04

### Linked PRs
* gh-104700
* gh-104710

**Comment by Eclips4** [comment]
PR which introduce it: #103990

**Comment by AlexWaygood** [comment]
> PR which introduce it: #103990

Cc. @Agent-Hellboy / @JelleZijlstra / @sunmy2019

**Comment by chgnrdv** [comment]
It seems like `Py_buffer` in `mmap_gfind`, `mmap_write_method` and `mmap_ass_subscript` should be released if `CHECK_VALID` fails.

**Comment by Eclips4** [comment]
> It seems like `Py_buffer` in `mmap_gfind`, `mmap_write_method` and `mmap_ass_subscript` should be released if `CHECK_VALID` fails.

Yeah, you're right. I'll soon send a PR.

**Comment by sunmy2019** [comment]
> It seems like `Py_buffer` in `mmap_gfind`, `mmap_write_method` and `mmap_ass_subscript` should be released if `CHECK_VALID` fails.

Yeah, I forgot about it.



> I'll soon send a PR.

Thanks!

**Comment by JelleZijlstra** [comment]
Sorry for this, should have run the refleak buildbots before merging. Thanks @chgnrdv for the diagnosis and @Eclips4 for the PR.

**Comment by sunmy2019** [comment]
> Sorry for this, should have run the refleak buildbots before merging.

Can we make it mandatory?

**Comment by Eclips4** [comment]
> > Sorry for this, should have run the refleak buildbots before merging.
> 
> Can we make it mandatory?

I think, it's a good idea. Also, running refleak buildbots make sense in PR's which changes/adding C code. So, there need a check.
