### ISSUE TITLE
Plural vs Singular in enum documentation

### ISSUE THREAD

**Issue by twmr** [python/cpython#104659]
# Documentation

Hi! I've just seen that classname in the example in the documentation for `IntEnum` (https://docs.python.org/3/library/enum.html#enum.IntEnum) is in the plural (`Numbers`) but for all the other enum examples a classname in the singular is used.

Since a singluar  classname IMO makes more sense for all enum classes, I think `Numbers` should be changed to `Number` in the documentation.

### Linked PRs
* gh-104665
* gh-104666

**Comment by ethanfurman** [comment]
@thisch You are correct.  Do you want to create a PR?
