### ISSUE TITLE
Clinic test are skipped on Windows

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#104629]
`test_clinic` is skipped on Windows. This is a regression introduced by gh-96178.

- The `Modules/_testclinic.c` helper extension module is not included in the Windows build
- `test.support.import_helper.import_module("_testclinic")` fails and skips the whole test, since `_testclinic` is not found

### Linked PRs
* gh-104630
* gh-104632
* gh-104723
* gh-107393

**Comment by erlend-aasland** [comment]
I'll leave the Windows specific part to someone with a Windows dev environment set up; I'm not comfortable doing the needed build changes in `PCbuild/`.

**Comment by hugovk** [comment]
> I'll leave the Windows specific part to someone with a Windows dev environment set up; I'm not comfortable doing the needed build changes in `PCbuild/`.

Is everything done now? Can we close this issue? Thanks!

**Comment by AlexWaygood** [comment]
As far as I can tell, all clinic tests are now executed when I run `python -m test test_clinic -v` locally on my Windows box 🥳
