### ISSUE TITLE
PEP 695: Rename typeparams to type_params in AST

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104656]
PEP-695 introduces a few new AST attributes that are currently called `typeparams`, as specified in https://peps.python.org/pep-0695/#ast-changes. However, @AlexWaygood rightly points out (https://github.com/python/cpython/pull/104642#discussion_r1198996246) that `type_params` would be more readable and in line with most of the rest of the AST. Should we change it?

cc @erictraut for this PEP, @cdce8p who made some AST changes in this area before, @pablogsal @isidentical as AST experts.

### Linked PRs
* gh-104657

**Comment by JelleZijlstra** [comment]
The same goes for the `typeparam` type in the AST. Naming it `type_param` would be consistent with e.g. `type_ignore`.

I'm working on a draft PR.

**Comment by cdce8p** [comment]
From a users perspective either works fine. It would be more important to not change it unnecessarily after it has been released. I.e. I wouldn't recommend to go back and "fix" `finalybody`, `kwonlyargs`, etc.

**Comment by AlexWaygood** [comment]
@erictraut, I think we'd be especially interested in your thoughts on this as the author of the PEP, since the name `typeparams` is specifically specified by the PEP. Would you object to this change?

**Comment by erictraut** [comment]
I don't have a strong opinion one way or the other on the AST names. I tried to follow the patterns I could see when I implemented my prototype. If there are some other conventions or precedents that I missed, I have no objections to changing these names.

**Comment by gpshead** [comment]
I'm in favor of including the `_` becauserunonwords\_are\_less\_readable.

**Comment by JelleZijlstra** [comment]
Unless someone disagrees strongly I'll merge the change to `type_params` tonight, in time for the beta tomorrow.

**Comment by JelleZijlstra** [comment]
Wewilluseunderscores.
