### ISSUE TITLE
Syntax highlighting issue in Turtle docs

### ISSUE THREAD

**Issue by millefalcon** [python/cpython#104679]
# Documentation

A couple of function docs

- https://docs.python.org/3/library/turtle.html#turtle.setposition
- https://docs.python.org/3/library/turtle.html#turtle.pencolor
- https://docs.python.org/3/library/turtle.html#turtle.fillcolor
- https://docs.python.org/3/library/turtle.html#turtle.color
- https://docs.python.org/3/library/turtle.html#turtle.filling
- https://docs.python.org/3/library/turtle.html#turtle.shearfactor

![image](https://github.com/python/cpython/assets/16983964/af314da1-b7a8-4871-9e3e-0b0704da6cb9)

seems to not have syntax highlighting working properly. 
On inspection, I see this was due to small indentation issue.

### Linked PRs
* gh-104682
* gh-104695

**Comment by hugovk** [comment]
Thanks for the report, it also means the copy button at the top right doesn't work. 

Would you like to open a pull request to fix them?

**Comment by millefalcon** [comment]
Would love to. Thanks 👍

**Comment by millefalcon** [comment]
@hugovk Please see https://github.com/python/cpython/pull/104682
