### ISSUE TITLE
function.__type_params__ and type.__type_params__ should be writable

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104600]
The PEP-695 implementation added a new attribute `__type_params__` to functions. I made this field read-only, but I realized there is a use case for writing to it: `functools.wraps`, when wrapping a generic function, should add the `.__type_params__` to the wrapper. Making it writable is also more consistent with other fields on functions, as even the `__name__` of functions is writable.

The PEP also adds a `__type_params__` attribute to classes and type aliases. For classes it's already writable (it's just stored in the type's `__dict__`). For type aliases it's readonly, but as I don't see a use case for mutating a type alias's `__type_params__`, I'd like to keep it that way.

### Linked PRs
* gh-104601
* gh-104634

**Comment by AlexWaygood** [comment]
> For classes it's already writable (it's just stored in the type's `__dict__`).

Small correction: as noted in #104616, it's not actually writeable on class objects either at the moment:

```pycon
Running Debug|x64 interpreter...
Python 3.12.0a7+ (heads/main:cfa517d5a6, May 18 2023, 17:12:51) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo[T]: ...
...
>>> Foo.__type_params__ = ("bar",)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute '__type_params__' of 'type' objects is not writable
>>> class Bar: ...
...
>>> Bar.__type_params__ = ("bar",)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: attribute '__type_params__' of 'type' objects is not writable
```

**Comment by sobolevn** [comment]
Sorry, but now PEP is misleading: 

> A new read-only attribute called `__type_params__` is available on generic classes, functions, and type aliases. 

But, since it is now writtable (on classes as well):

```python
>>> class A[X]: ...
... 
>>> A.__type_params__
(X,)
>>> A.__type_params__ = ()
>>> A.__type_params__
()
```

Shouldn't the PEP be updated? Or do you want to make this "implementation detail" private?

**Comment by erictraut** [comment]
Sounds reasonable to me.

**Comment by JelleZijlstra** [comment]
Reopening to remind myself to do that
