### ISSUE TITLE
Enhancement Request - Relative Imports in Files Not Part of a Module

### ISSUE THREAD

**Issue by caitp** [python/cpython#104664]
**Summary:**
Python should allow relative imports in standalone files, even if they are not part of a module, to simplify code organization and improve code reuse.

**Description:**
The current behavior of relative imports in Python restricts their usage to files that are part of a module or package. This limitation creates unnecessary complexities when trying to organize code into logical units without explicitly structuring it as a package or module. Modifying sys.path or resorting to convoluted workarounds is not an ideal solution.

I'd like for the Python import mechanism to support relative imports in standalone files. By considering the directory of a file as the starting point for resolving relative import paths, developers would gain more flexibility and convenience when writing modular and reusable code, even in situations where a file is not part of a package or module.

**Expected Behavior:**
When a Python file is not associated with a module or package, the import system should allow relative imports by treating the file's directory as the reference point. This approach aligns with Python's philosophy of explicitness and simplicity, empowering developers to organize code logically without the constraints of package/module requirements.

I don't want to have to write 10 lines of unreadable code with importlib to import a relative file when `from .foo.bar.baz import Buzz` is _right there_, and the only reason it doesn't work is because the file is not within a module.
I'm sure I'm not the only person who has been frustrated by this. If Node can do it, why not?

**Comment by sunmy2019** [comment]
Hi, @caitp. New ideas are welcomed at https://discuss.python.org/c/ideas/6

We can discuss the concrete development plan here if we are unanimous there.

**Comment by gpshead** [comment]
I'm closing this as it's something that needs discussion in our forums before we'll know if we even want such a thing and what shape it should take.  Feel free to drop a link to a discuss thread here for reference if desired.
