### ISSUE TITLE
Remove locale.resetlocale() function in Python 3.13

### ISSUE THREAD

**Issue by vstinner** [python/cpython#104783]
Remove locale.getdefaultlocale() and locale.resetlocale() functions deprecated in Python 3.11: see issue #90817 for the rationale and the deprecation.

### Linked PRs
* gh-104784
* gh-105381
* gh-105401

**Comment by vstinner** [comment]
@methane asked me to keep locale.getdefaultlocale(): https://github.com/python/cpython/pull/104784#issuecomment-1558552650

**Comment by vstinner** [comment]
Ok, let's start with removing locale.resetlocale(). The locale.getdefaultlocale() function can stay a little bit longer thanks to @methane :-)

**Comment by hugovk** [comment]
> Ok, let's start with removing locale.resetlocale(). The locale.getdefaultlocale() function can stay a little bit longer thanks to @methane :-)

https://docs.python.org/3.13/library/locale.html#locale.getdefaultlocale says:

> _Deprecated since version 3.11, removed in version 3.13._

Do you have an idea how much longer it can stay? Shall we bump it a release or two? Or delete the planned removal version?

**Comment by vstinner** [comment]
You should ask @methane who was against removing it.

**Comment by methane** [comment]
My gut feeling is +2 years.
When Python 3.15 is released, Python 3.10 become EOL.

**Comment by hugovk** [comment]
3.15 sounds reasonable.

Please see issue https://github.com/python/cpython/issues/111187 and PR https://github.com/python/cpython/pull/111188 to bump removal to 3.15.
