### ISSUE TITLE
Remove kwargs-based TypedDict creation

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104786]
#90224 deprecated the creation of TypedDicts through the kwargs-based syntax (`TypedDict("TD", a=int, b=str)`). The syntax is to be removed in 3.13, so now is the time to do that. 

### Linked PRs
* gh-104891

**Comment by tomasr8** [comment]
Hi! Were you planning to submit a patch for this or is it up for grabs? I'd be happy to give it a go :)

**Comment by JelleZijlstra** [comment]
Go ahead!
