### ISSUE TITLE
Add a check on the argument type for random.normalvariate()?

### ISSUE THREAD

**Issue by lucabaldini** [python/cpython#104749]
The way real-valued distributions in the random module interact with numpy arrays is potentially confusing, e.g.

```
>>> import random
>>> import numpy
>>> x = numpy.linspace(0., 10., 11)
>>> random.normalvariate(x, 0.1)
array([-7.18104766e-03,  9.92818952e-01,  1.99281895e+00,  2.99281895e+00,
        3.99281895e+00,  4.99281895e+00,  5.99281895e+00,  6.99281895e+00,
        7.99281895e+00,  8.99281895e+00,  9.99281895e+00])
```

What it's happening here is that random.normalvariate throw a random number z normally distributed with meany mu and standard deviation sigma, and *then* adds z to the mean. If mean is a numpy array (or, really, anything supporting arithmetic addition) this can lead to unexpected/confusing results---in this case we are adding the same single random number to all the elements of the array.

I fully realize this is not a bug---everything works as advertised---and mixing numpy and the random module in the standard library isn't necessarily something that's in widespread use, but I was wondering whether it deserves an explicit check of the argument type, a mention in the docs, or a combination of the two.

I haven't looked carefully, but something similar might happen with other distributions?

**Comment by lucabaldini** [comment]
Thanks for the reply, and I am afraid I don't have real wisdom to add as to how the function should be modified (and you are probably right it should not). 

A student of mine was bitten by this today, and it did strike me as something that is potentially subtle to debug, so I thought I posted this to see if anybody got interested---but I would not be offended if this got closed immediately. You might be right this is just something intrinsic to the language.

**Comment by terryjreedy** [comment]
float.__add__ and float.__radd__ already restrictively check the type of the other argument.  It is the numpy __add__ that accepts a float and does the addition.  Someone could possibly want a result such as this, though `x + [normalvariate(0, sigma) for i in range(n)]` is more likely.  So closing.

Questions posing possible enhancements are now better posted to the Ideas channel of discuss.python.org.
