### ISSUE TITLE
test_enum tests fail because of the version bump to 3.13.0a0

### ISSUE THREAD

**Issue by Yhg1s** [python/cpython#104764]
Following the creation of the 3.12 branch and the bump of main to 3.13, test_enum started failing (https://github.com/python/cpython/actions/runs/5050528705/jobs/9061352655). This seems to be because a few tests are testing features that haven't landed in 3.13, or perhaps were rolled back. The failing tests are blocking CI.

### Linked PRs
* gh-104765
* gh-104779

**Comment by Yhg1s** [comment]
I've hotfixed the issue to get CI back to green, but either the tests or the features should be reconsidered properly.

**Comment by ethanfurman** [comment]
Working on proper fix.

**Comment by JelleZijlstra** [comment]
Seems like this was fixed in #104779.
