### ISSUE TITLE
Set the tp_getattro field to PyObject_GenericGetAttr in the few built-in types that do not already do it

### ISSUE THREAD

**Issue by geryogam** [python/cpython#104772]
# Feature or enhancement

Set the `tp_getattro` field to `PyObject_GenericGetAttr` in the few built-in types that do not already do it:
- `__loader__` (since `__loader__.__getattribute__ is object.__getattribute__`);
- `bool` (since `bool.__getattribute__ is int.__getattribute__`);
- `classmethod` (since `classmethod.__getattribute__ is object.__getattribute__`);
- `staticmethod` (since `staticmethod.__getattribute__ is object.__getattribute__`);
- subclasses of `BaseException` (since `Exception.__getattribute__ is BaseException.__getattribute__`).

# Pitch

Overriding `__getattribute__` in built-in types by setting their `tp_getattro` field is the norm, even if it is to override it with the same method (in the latter I suppose it’s for optimizing method lookup):

```python
>>> import builtins
>>> for k, v in vars(builtins).items():
...     if isinstance(v, type) and vars(v).get('__getattribute__') is not None:
...         print(k)
... 
memoryview
bytearray
bytes
complex
dict
enumerate
filter
float
frozenset
property
int
list
map
object
range
reversed
set
slice
str
super
tuple
type
zip
BaseException
```

But I noticed that only `__loader__`, `bool`, `classmethod`, `staticmethod`, and subclasses of `BaseException` do not do it:

```python
>>> for k, v in vars(builtins).items():
...     if isinstance(v, type) and vars(v).get('__getattribute__') is None:
...         print(k)
... 
__loader__
bool
classmethod
staticmethod
BaseExceptionGroup
Exception
GeneratorExit
KeyboardInterrupt
SystemExit
ArithmeticError
AssertionError
AttributeError
BufferError
EOFError
ImportError
LookupError
MemoryError
NameError
OSError
ReferenceError
RuntimeError
StopAsyncIteration
StopIteration
SyntaxError
SystemError
TypeError
ValueError
Warning
FloatingPointError
OverflowError
ZeroDivisionError
BytesWarning
DeprecationWarning
EncodingWarning
FutureWarning
ImportWarning
PendingDeprecationWarning
ResourceWarning
RuntimeWarning
SyntaxWarning
UnicodeWarning
UserWarning
BlockingIOError
ChildProcessError
ConnectionError
FileExistsError
FileNotFoundError
InterruptedError
IsADirectoryError
NotADirectoryError
PermissionError
ProcessLookupError
TimeoutError
IndentationError
IndexError
KeyError
ModuleNotFoundError
NotImplementedError
RecursionError
UnboundLocalError
UnicodeError
BrokenPipeError
ConnectionAbortedError
ConnectionRefusedError
ConnectionResetError
TabError
UnicodeDecodeError
UnicodeEncodeError
UnicodeTranslateError
ExceptionGroup
EnvironmentError
IOError
```

If it’s an oversight, I suggest we fix it.

**Comment by JelleZijlstra** [comment]
What concrete problem does this fix?

**Comment by geryogam** [comment]
It optimizes attribute lookup.

**Comment by metatoaster** [comment]
For context, this issue came to be because of [this StackOverflow thread](https://stackoverflow.com/questions/76302654/why-does-property-override-object-getattribute). Disclaimer: I did not advocate for bringing forth the suggested changes here.

**Comment by geryogam** [comment]
@benjaminp Any reason why you replaced the value `PyObject_GenericGetAttr` of `tp_getattro` with `0` for `classmethod` and the function type?

**Comment by ronaldoussoren** [comment]
@JelleZijlstra : I propose closing this issue.

The only side effect of the proposed change is adding ``__getattribute__`` to the type ``__dict__``. The ``tp_getattro`` slot will be copied from the base class in ``Objects/typeobject.c:inherit_slots``.  The types also don't override ``__getattribute__`` and hence wouldn't have that name in their dict if they were implemented in Python.
