### ISSUE TITLE
test_pickle are leaked on Windows

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#104702]
Tried on current main branch.
```python
./python -m test -R 3:3 test_pickle
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_pickle
beginning 6 repetitions
123456
......
test_pickle leaked [13, 12, 173] references, sum=198
test_pickle leaked [11, 12, 113] memory blocks, sum=136
test_pickle failed (reference leak) in 4 min 30 sec

== Tests result: FAILURE ==

1 test failed:
    test_pickle

Total duration: 4 min 30 sec
Tests result: FAILURE
```
Also, I cannot reproduce it in Linux (WSL, Ubuntu 20.04)

### Linked PRs
* gh-106207
* gh-108497
* gh-108612

**Comment by Eclips4** [comment]
I'm not sure, but some ref leaks may related to #102256

**Comment by Eclips4** [comment]
Fantastic... I can't reproduce it anymore. I just try found bad commit using git bisect...
But I've found reference leak in another way.
```python
 ./python -m test -R 3:3 test_pickle -m PyUnpicklerTests
Running Debug|x64 interpreter...
0:00:00 Run tests sequentially
0:00:00 [1/1] test_pickle
beginning 6 repetitions
123456
......
test_pickle leaked [4, 4, 4] references, sum=12
test_pickle leaked [4, 4, 4] memory blocks, sum=12
test_pickle failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_pickle

Total duration: 908 ms
Tests result: FAILURE
```

**Comment by Eclips4** [comment]
First bad commit: #94504
Also, I know about some refleaks in test_import. (#102251)
What is the relationship with this and test_import issue?
Both doesn't reproducible before #94504 PR.

**Comment by sunmy2019** [comment]
Seems all ref leaks come from `test_unpickle_module_race`

If this test is removed from `AbstractUnpickleTests`, all ref leaks are gone.
