### ISSUE TITLE
Optimize and reduce memory usage for `asyncio.Task` and others

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#104787]
Tracker issue for performance work related  to `asyncio.Task` for 3.13. 

Two things of top of my head is to use bitfields and use newer managed dict optimization in `_asyncio`. I'll add whatsnew entry once all changes land under this issue. 

### Linked PRs
* gh-104788
* gh-104795
* gh-106516

**Comment by itamaro** [comment]
Sounds great!
Are you planning to also tackle the all_tasks -> per-loop-strong-set as part of this issue?

**Comment by kumaraditya303** [comment]
> Are you planning to also tackle the all_tasks -> per-loop-strong-set as part of this issue?

Yes, but haven't thought too much about that.
