### ISSUE TITLE
Duplicated lookup on unicodekeys_lookup_unicode

### ISSUE THREAD

**Issue by corona10** [python/cpython#104717]
There are duplicated lookups on `unicodekeys_lookup_unicode`.
I am trying to understand this code as manual loop unrolling for performance. but I am not sure that it is intended.

https://github.com/python/cpython/blob/be0c106789322273f1f76d232c768c09880a14bd/Objects/dictobject.c#L932-L961

First introduced from https://github.com/python/cpython/commit/f8a95df84bcedebc0aa7132b3d1a4e8f000914bc

Please let me know this that is intended.

### Linked PRs
* gh-104716
* gh-104718

**Comment by corona10** [comment]
cc @markshannon @methane

**Comment by methane** [comment]
Yes, this is intended, manual loop unrolling.

**Comment by corona10** [comment]
Okay then I will close the issue.

> Yes, this is intended, manual loop unrolling.

**Comment by corona10** [comment]
ll
