### ISSUE TITLE
Remove the 2to3 program and the lib2to3 module

### ISSUE THREAD

**Issue by vstinner** [python/cpython#104780]
The 2to3 program is implemented with the lib2to3 module which implements a parser of the Python language. Problem: this parser is unable to parse Python 3.10 grammar :-( This issue was already known in Python 3.9 when [PEP 617 – New PEG parser for CPython](https://peps.python.org/pep-0617/) was approved.

The 2to3 program and the lib2to3 were marked as "pending" deprecated since Python 3.9, and then officially deprecated in Python 3.11 (``import lib2to3`` emits a ``DeprecationWarning``).

One of a famous user of lib2to3 was the [black project](https://github.com/psf/black) but they decided to fork lib2to3 and their fork was made compatible with Python 3.10 grammar (maybe also Python 3.11).

I propose to remove 2to3 and lib2to3 at the beginning of the Python 3.13 development cycle to give users more time to be prepared for this incompatible change before Python 3.13 final release (scheduled in October 2024).

cc @isidentical @lysnikolaou @pablogsal @ambv 

---

Example of valid Python script (``script.py``:

```py
with (open(__file__) as fp): data=fp.read()
print(len(data))
```

It works well on Python 3.11:

```
$ python3.11 script.py 
61
```

But lib2to3 is unable to parse it:

```
$ python3.11 -m lib2to3 script.py 
(...)
RefactoringTool: No files need to be modified.
RefactoringTool: There was 1 error:
RefactoringTool: Can't parse script.py: ParseError: bad input: type=1, value='as', context=(' ', (1, 21))
```

### Linked PRs
* gh-104781

**Comment by vstinner** [comment]
Done by https://github.com/python/cpython/commit/ae00b810d1d3ad7f1f7e226b02ece37c986330e7

**Comment by hugovk** [comment]
Wow!

<img width="148" alt="+26 -21,000" src="https://github.com/python/cpython/assets/1324225/4c383498-7d8c-436e-9d6b-538eec208e87">

(I think this issue can be closed, please re-open otherwise :)

**Comment by vstinner** [comment]
lib2to3 was deprecated in Python 3.11 by issue #84540.
