### ISSUE TITLE
<broadcast> and null string fail in getaddrinfo()

### ISSUE THREAD

**Issue by rlippmann** [python/cpython#104747]
# Bug report

doing socket.getaddrinfo() returns an exception when using the host strings of ```’<broadcast>’``` or the empty string. 

calling socket.gethostbyname() succeeds

I’m not sure if this is oversight or intended functionality.

The documentation seems to imply that those strings can be used anywhere an IPv4 host name can be used. 

# Your environment

- CPython versions tested on: 3.10.6
- Operating system and architecture: Ubuntu 22.04 x86_64

**Comment by sunmy2019** [comment]
The difference is because we special case `""` and `"<broadcast>"` in `socket.gethostbyname`.

**Comment by sunmy2019** [comment]
These special cases are made in the initial version back to 32 years ago. Newly implemented functions do not special case these, and old functions cannot be changed.

**Comment by rlippmann** [comment]
So, it’s intended functionality? Perhaps the docs should be changed, then. It sounds like any place you can put an IPv4 host you can use those strings.

**Comment by sunmy2019** [comment]
I found the initial commit [here](https://github.com/python/cpython/commit/2d8d4276c67d39af113c1a169c2661d7f0f86285), 21yrs old.  So I think there is no way to change the behavior.

**Comment by rlippmann** [comment]
Ok. I was asking because i was looking to add a patch to uvloop and I need to mimic the default asyncio behavior.
