### ISSUE TITLE
group pattern grammar is subset of sequence_pattern in the docs

### ISSUE THREAD

**Issue by Glyphack** [python/cpython#104715]
# Documentation

Seems like the group pattern grammar is a subset of sequence pattern grammar. Where sequence pattern starts with "(" and maybe_start_pattern is always a pattern. But this feels wrong because then the group pattern is redundant.

Picture from: https://docs.python.org/3/reference/compound_stmts.html#group-patterns

<img width="1040" alt="Screenshot 2023-05-21 at 12 00 58 PM" src="https://github.com/python/cpython/assets/20788334/f790d0b5-3bad-4d38-9677-d3ef609e687d">

I think this counts as ambiguity, from this [pep](https://peps.python.org/pep-0617/#background-on-peg-parsers) this should not happen:

> Unlike LL(1) parsers, PEG-based parsers cannot be ambiguous: if a string parses, it has exactly one valid parse tree. This means that a PEG-based parser cannot suffer from the ambiguity problems described in the previous section.

**Comment by terryjreedy** [comment]
Please reread the paragraph above the line you quote, which explains *why* PEG-based parsers cannot be ambiguous.  Trying options *in the order given* means that overlaps do not introduce ambiguity.  The same thing is true in languages like Python that guarantee that conditional expressions (guards) are evaluated in the order given.  Therefore, each condition has an implied 'and if none of the previous conditions are true' tacked on the end and there is no ambiguity  as to which alternative will be executed.  (There have been people who have advocated that alternation should be possibly ambiguous in the same way that standard context-free grammars can be.)

 In the case of [*patterns*](https://docs.python.org/3/reference/compound_stmts.html#patterns), and in particular *closed patterns*, the parser *always* tries to match *group_pattern* before it tries to match *sequence_pattern*.  So any code that could be seen as either will be seen as a group pattern.
