### ISSUE TITLE
copy.copy() is not Shallow copy

### ISSUE THREAD

**Issue by tdxs8848** [python/cpython#104734]
# Bug report

```python
import copy

class_names = ['Alice', 'Bob', 'Charlie']
class_names_shallow = copy.copy(class_names)
class_names_deep = copy.deepcopy(class_names)

class_names.append('David')

print(class_names)
print(class_names_shallow)
print(class_names_deep)

#output
# ['Alice', 'Bob', 'Charlie', 'David']
# ['Alice', 'Bob', 'Charlie']
# ['Alice', 'Bob', 'Charlie']

```

# Your environment

- win11
- python3.10

**Comment by arhadthedev** [comment]
Can confirm on `Python 3.12.0a7+ (heads/main:60993ba8b4, May 21 2023, 13:50:05) [MSC v.1929 64 bit (AMD64)] on win32`:

```plain
D:\Oleg\cpython>python gh-104734-reproducer.py
Running Release|x64 interpreter...
['Alice', 'Bob', 'Charlie', 'David']
['Alice', 'Bob', 'Charlie']
['Alice', 'Bob', 'Charlie']
```

**Comment by JelleZijlstra** [comment]
That output looks correct to me. What were you expecting?

**Comment by arhadthedev** [comment]
From https://docs.python.org/3/library/copy.html:

> copy.copy(x) 
> Return a shallow copy of x.

I suspect the output should be:

```plain
['Alice', 'Bob', 'Charlie', 'David']
['Alice', 'Bob', 'Charlie', 'David']
['Alice', 'Bob', 'Charlie']
```

**Comment by JelleZijlstra** [comment]
It's copied before the list is mutated.

**Comment by tdxs8848** [comment]
> It's copied before the list is mutated.

shallow copy should be

![image](https://github.com/python/cpython/assets/62961184/f334f549-ebba-4e0b-8081-adb4577a22cd)

**Comment by arhadthedev** [comment]
Ah, I got it. The assignment itself makes a deep copy:

```python
>>> original = ['a']
>>> copy = original
>>> copy.append('b')
>>> print(original, copy)
['a', 'b'] ['a', 'b']
```

**Comment by eryksun** [comment]
Assigning `class_names_shallow = class_names` is just another reference to the same object. It's not a copy. A shallow copy of a list is a new list that references the same items. A deep copy of a list *recursively* copies the items of the list as well.

**Comment by JelleZijlstra** [comment]
Everything I see here works as expected.

An assignment like `class_names_shallow = class_names` creates a new reference to the same list, so if you mutate the list through one reference, you'll also see the change on the other reference.

A shallow copy means creating a copy of the list itself, but not of its elements. It returns a new list, so if you mutate one copy, you won't see that mutation reflected in the other copy.

A deep copy also copies the elements of the list. In this example, that makes no difference, as the list contains strings, which are immutable. However, you can see the difference if your list contains mutable elements like other lists.

**Comment by arhadthedev** [comment]
> A shallow copy of a list is a new list that references the same items

Thank you, now I understand. Should we add this to the documentation to avoid confusion?

**Comment by tdxs8848** [comment]
Because its results are so different from direct assignment, I was very troubled when writing articles about it

**Comment by tdxs8848** [comment]
> Everything I see here works as expected.
> 
> An assignment like `class_names_shallow = class_names` creates a new reference to the same list, so if you mutate the list through one reference, you'll also see the change on the other reference.
> 
> A shallow copy means creating a copy of the list itself, but not of its elements. It returns a new list, so if you mutate one copy, you won't see that mutation reflected in the other copy.
> 
> A deep copy also copies the elements of the list. In this example, that makes no difference, as the list contains strings, which are immutable. However, you can see the difference if your list contains mutable elements like other lists.

thank you ,That doesn't sound like a strict shallow copy

**Comment by eryksun** [comment]
> That doesn't sound like a strict shallow copy

A variable in Python is just a reference to an object, so assignment has nothing to do with copying an object. If you assign `x = [[1], [2], [3]]` and `y = x`, then `x` and `y` both reference the same list object. However, if you assign `y = x[:]`, the slice of the list object creates a new list, which is a shallow copy. Adding or removing items from the copy has no effect on the original, and vice versa, because that's what it means for one thing to be a copy of another thing. It's a shallow copy, however, because it still references the same objects as the original list, which may be mutable (e.g. a list of lists). A deep copy recursively copies the items of the list.

Variable `y` as another reference to the same list:

```pycon
>>> x = [[1], [2], [3]]
>>> y = x
>>> y is x
True
>>> y.append([4])
>>> x
[[1], [2], [3], [4]]
```

Variable `y` as a shallow copy of the list:

```pycon
>>> x = [[1], [2], [3]]
>>> y = x[:]
>>> y is x
False
>>> y.append([4])
>>> x
[[1], [2], [3]]
>>> y
[[1], [2], [3], [4]]

>>> y = x[:]
>>> [a is b for a, b in zip(x, y)]
[True, True, True]
>>> x[0].insert(0, 0)
>>> x
[[0, 1], [2], [3]]
>>> y
[[0, 1], [2], [3]]
```

Variable `y` as a deep copy of the list:

```pycon
>>> x = [[1], [2], [3]]
>>> y = copy.deepcopy(x)
>>> y is x
False
>>> [a is b for a, b in zip(x, y)]
[False, False, False]
>>> x[0].insert(0, 0)
>>> x
[[0, 1], [2], [3]]
>>> y
[[1], [2], [3]]
```

Creating a deep copy can be expensive. For example, say a list contains a 100 MiB `bytearray`, then a deep copy will consume another 100 MiB of a memory.

**Comment by tdxs8848** [comment]
Thanks for your reply, I have no problem with shallow copies of direct assignments.

But copy() creates a new list object and then makes a shallow copy of the elements in the first layer.

This gives program two shallow copy results:

1.  A shallow copy of the assignment
1. Create a new object and make a shallow copy of its surface elements


```python
a_list = []
b_list = a_list
c_list = copy.copy(a_list)
print(id(a_list)) # 2402419973888
print(id(b_list)) # 2402419973888
print(id(c_list)) # 2402415946944
```

Would it be better to phrase it differently or to indicate the distinction from direct assignment?

**Comment by eryksun** [comment]
> A shallow copy of the assignment

An assignment to a variable, attribute, or index is an additional reference for an object, which increments the object's reference count that determines its lifetime. One doesn't copy an assignment. That's not an operation of the language. The right-hand expression is evaluated to an object, and a reference to that object is stored in the variable, attribute, or index.
