### ISSUE TITLE
Inconsistent format length while adding separator with underscore

### ISSUE THREAD

**Issue by Nabav** [python/cpython#104849]
# Bug report

The f-string allows different lengths and zero padding and adding `_` separators (every 3 digits for decimal and every 4 digits for binary and hexadecimal). The length of the generated string with different lengths is inconsistent.

See compiler explorer outputs: https://godbolt.org/z/dv7br5EzG

```python
x = 1
for l in [4, 5, 6, 7, 8]:
    print(f'Length: {l}')
    print(f'  bin: {x:0{l}_b}')
    print(f'  hex: {x:0{l}_x}')
    print(f'  dec: {x:0{l}_}')
```

Output:

```
Length: 4
  bin: 0001
  hex: 0001
  dec: 0_001
Length: 5
  bin: 0_0001
  hex: 0_0001
  dec: 0_001
Length: 6
  bin: 0_0001
  hex: 0_0001
  dec: 00_001
Length: 7
  bin: 00_0001
  hex: 00_0001
  dec: 000_001
Length: 8
  bin: 000_0001
  hex: 000_0001
  dec: 0_000_001
```

# Your environment

- CPython versions tested on: 3.9 and 3.11
- Operating system and architecture: Debian and compiler explorer

I would expect that the string is first padded (with zeros) to the specified length and then separator characters are inserted as much as needed. Correct me, if I am wrong.

**Comment by sunmy2019** [comment]
What is your expectation here? Is it this?
```
Length: 4
  bin: 0001
  hex: 0001
  dec: _001
Length: 5
  bin: _0001
  hex: _0001
  dec: 0_001
Length: 6
  bin: 0_0001
  hex: 0_0001
  dec: 00_001
Length: 7
  bin: 00_0001
  hex: 00_0001
  dec: 000_001
Length: 8
  bin: 000_0001
  hex: 000_0001
  dec: _000_001
```

It doesn't look good with out leading `0`.

**Comment by sunmy2019** [comment]
> the string is first padded (with zeros) to the specified length and then separator characters are inserted as much as needed.

The spec says https://docs.python.org/3/library/string.html#grammar-token-format-spec-width
>width is a decimal integer defining the minimum total field width, including any prefixes, separators, and other formatting characters. If not specified, then the field width will be determined by the content.

The spec is impossible to change since people rely on it.

**Comment by Nabav** [comment]
I understand, but it is disappointing to specify length of **9 instead of 8** to get the binary form of `0000_0001` for a simple byte (octet).

**Comment by Nabav** [comment]
Currently, the generated decimal string with the length of 4 contains 5 characters. So, it might be allowed generally to go beyond minimum length. This is not contradicting the spec.

**Comment by sunmy2019** [comment]
> In fact the total number of digits excluding separator characters should match the specified length.

This is against the spec.

**Comment by terryjreedy** [comment]
Just to note that this is about the format specification, not f-strings.  The following gives the same output.
```
x = 1
for l in [4, 5, 6, 7, 8]:
    print('Length: {}'.format(l))
    print('  bin: {:0{}_b}'.format(x, l))
    print('  hex: {:0{}_x}'.format(x, l))
    print('  dec: {:0{}_}'.format(x, l))
```
That it is harder to read is why we invented f-strings.

**Comment by ericvsmith** [comment]
Or better yet, don't even use `.format`, use the `format` builtin. That way you get rid of all `{}` parsing. Ignore that fact that I'm still using f-strings to compute the format spec, that's not the important part here.

```python
x = 1
for l in [4, 5, 6, 7, 8]:
    print(f'Length: {l}')
    print('  bin: ', format(x, f'0{l}_b'))
    print('  hex: ', format(x, f'0{l}_x'))
    print('  dec: ', format(x, f'0{l}_'))
```

Or, if you're really hard core, call `__format__` directly:
```
x = 1
for l in [4, 5, 6, 7, 8]:
    print(f'Length: {l}')
    print('  bin: ', x.__format__(f'0{l}_b'))
    print('  hex: ', x.__format__(f'0{l}_x'))
    print('  dec: ', x.__format__(f'0{l}_'))
```

My point is that in general I like to remove as much unnecessary machinery (f-strings, `.format`, etc.) when trying to see what's going on.

**Comment by ericvsmith** [comment]
> This is against the spec.

It's possible the spec needs to be updated. I'm not saying that's the case here, I haven't looked at it closely. But like everything else, it's written by humans and my have bugs.

**Comment by sunmy2019** [comment]
The grouping logic is implemented in `_PyUnicode_InsertThousandsGrouping`.

https://github.com/python/cpython/blob/c90a862cdcf55dc1753c6466e5fa4a467a13ae24/Objects/unicodeobject.c#L8933-L8967

And I believe the current behavior is following the spec, as
1. separators are counted in `min_width`.
2. the formatted result should not start with a separator.

**Comment by sunmy2019** [comment]
> separators are counted in `min_width`.

This is clearly stated since Python 3.7. https://docs.python.org/3.7/library/string.html#format-specification-mini-language

**Comment by sunmy2019** [comment]
And with `print("{:04,}".format(1))`
```
0,001
```

This behavior is dated back to Python 3.5 (I don't have Python older than 3.5)

https://godbolt.org/z/5Pe8cW9sM

I am strongly against any behavioral change here.

**Comment by Nabav** [comment]
> And with `print("{:04,}".format(1))`
> 
> ```
> 0,001
> ```
> 
> This behavior is dated back to Python 3.5 (I don't have Python older than 3.5)
> 
> https://godbolt.org/z/5Pe8cW9sM
> 
> I am strongly against any behavioral change here.

This matches exactly what I expect: total number of digits are 4 as specified and then the separator is inserted to make a string of length 5. I wish to see exactly the same behavior consistently.

**Comment by Nabav** [comment]
I agree that the formatted string should not start with a separator. It is not contradicting to what I propose.

**Comment by sunmy2019** [comment]
> This matches exactly what I expect: total number of digits are 4 as specified and then the separator is inserted to make a string of length 5.

Not at all. It matches the behavior that I am stating:

**Pad to the minimal length. Add a leading zero when necessary.**

```py
print("{:02,}".format(1))
print("{:03,}".format(1))
print("{:04,}".format(1))
print("{:05,}".format(1))
print("{:06,}".format(1))
print("{:07,}".format(1))
print("{:08,}".format(1))
print("{:09,}".format(1))
print("{:010,}".format(1))
```

on Python 3.5 and 3.11
```
01
001
0,001
0,001
00,001
000,001
0,000,001
0,000,001
00,000,001
```

**Comment by ericvsmith** [comment]
I don't think there's anything to change here. We certainly can't change resulting string. If there's a documentation change that would improve things, please propose it and we can re-open this issue.
