### ISSUE TITLE
test_venv spams our AddressSanitizer CI with 5mb of test logs

### ISSUE THREAD

**Issue by gpshead** [python/cpython#104839]
`test_venv` is spamming our AddressSanitizer CI runs with 5mb (50000 lines) of LeakSanitizer reports. Likely because it does not allow the `ASAN_OPTIONS` environment variable setting through to child Python processes it spawns.

if the test isn't useful for AddressSanitizer we should just skip it on ASAN runs.  otherwise we need to make sure the relevant environment is plumbed through.

It makes looking at AddressSanitizer logs from Github's CI interface in a browser next to impossible to use.  You have to download the logs to be able to make sense out of them.

### Linked PRs
* gh-105005
* gh-105006

**Comment by terryjreedy** [comment]
Thank you for diagnosing the test doing this.
