### ISSUE TITLE
`generate_tokens` tokenizes `$` differently with Python 3.12 than earlier

### ISSUE THREAD

**Issue by pekkaklarck** [python/cpython#104802]
I tested Python 3.12 beta 1 with [Robot Framework](https://github.com/robotframework/robotframework) and noticed that `tokenize.generate_tokens()` handles expressions containing `$` differently than earlier. Earlier `$` yielded `ERRORTOKEN` but nowadays we get `OP`: 

```python
Python 3.11.3 (main, Apr  5 2023, 14:15:06) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tokenize import generate_tokens
>>> from io import StringIO
>>> next(generate_tokens(StringIO('$x').readline))
TokenInfo(type=60 (ERRORTOKEN), string='$', start=(1, 0), end=(1, 1), line='$x')
```

```python
Python 3.12.0b1 (main, May 22 2023, 23:31:26) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from tokenize import generate_tokens
>>> from io import StringIO
>>> next(generate_tokens(StringIO('$x').readline))
TokenInfo(type=55 (OP), string='$', start=(1, 0), end=(1, 1), line='$x\n')
```

We support Python evaluation with special variables like `$var > 1` in Robot Framework data and this change breaks our [tokenizing code](https://github.com/robotframework/robotframework/blob/34257fcee84604ecf7655edc0a11e415c23dab00/src/robot/variables/evaluation.py#L86). I didn't notice anything related in the release notes and decided to report this. If the change is intentional, we can easily update our code to handle also these semantics.

Notice also that there's a small change with `TokenInfo.line` above. With Python 3.12 there's an additional `\n` even though the original string didn't contain any newlines.

**Comment by sunmy2019** [comment]
> I didn't notice anything related in the release notes

It just makes it to the deadline. I think the docs can be updated later.
https://github.com/python/cpython/pull/104323#issuecomment-1554801090

**Comment by pablogsal** [comment]
Yep, this is expected side effect of the change. Docs are being worked on here:

https://github.com/python/cpython/pull/104824

**Comment by pablogsal** [comment]
Opened https://github.com/python/cpython/issues/104825 for the new line character
