### ISSUE TITLE
pathlib is_dir gives wrong result for mounted USB flash drive

### ISSUE THREAD

**Issue by bobjalex** [python/cpython#104806]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by bobjalex** [comment]
I'm having trouble entering data into the report proper, so entering it in a comment:
CPython version 3.12b1
My environment: Windows 11 laptop 64bit

Using pathlib.is_dir for a directory on a mounted USB drive answers False, but os.path.isdir gives the correct answer: True. pathlib.is_dir works fine for the C:\ drive.

Attached is a little program that shows the problem.
[is_dir.py.txt](https://github.com/python/cpython/files/11547538/is_dir.py.txt)

**Comment by bobjalex** [comment]
Oops, I left this out:
My output from the attached program:

>python is_dir.py
using os.path: True
using pathlib: False
using os.path: True
using pathlib: True

**Comment by eryksun** [comment]
This issue should be resolved by fixing gh-104820.

**Comment by zooba** [comment]
Yep, can see this was reported first, but I've already attached the fix to #104820, so closing this as a duplicate.
