### ISSUE TITLE
Library issue, in pip list its there but still module found

### ISSUE THREAD

**Issue by georgethomas08** [python/cpython#104832]
Hi Team,

There is an issue with a library from azure, **azure-iot-device**, this library has been install in few of the systems, and was working fine, now it showing that module found. I have uninstalled and re-installed the python but still the issue there. Currently this issue been reported from both Windows and Ubuntu machine too. Please not it was Working fine. I created a venv and installed the library there it works perfectly. We need a setup without venv . Kindly help us to resolve this please find the Screenshot below

![image](https://github.com/python/cpython/assets/8665537/5cc227c9-b689-4146-bebe-d0afcc310674)

**Comment by sunmy2019** [comment]
Renaming this file `/home/ng/Documents/azure.py` should fix.

**Comment by georgethomas08** [comment]
Hi @sunmy2019,

there was file named azure.py I renamed that. Now its working,  Thank you for the information
