### ISSUE TITLE
socket.getblocking() documentation lists opposite equivalence

### ISSUE THREAD

**Issue by chrisaycock** [python/cpython#104882]
# Documentation

The [documentation](https://docs.python.org/3/library/socket.html#socket.socket.getblocking) for `socket.getblocking()` states:

> This is equivalent to checking socket.gettimeout() == 0.

But that's the opposite of what it means. According to the [source code](https://github.com/python/cpython/blob/main/Modules/socketmodule.c), `getblocking()` returns `False` if and only if `gettimeout()` returns `0.0.`

### Linked PRs
* gh-105026
* gh-105283
* gh-105284

**Comment by AlexWaygood** [comment]
Fixed, and backported to 3.12 and 3.11
