### ISSUE TITLE
Add `typing.get_protocol_members` and `typing.is_protocol`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#104873]
#103160 added an attribute `__protocol_attrs__` that holds the names of all protocol attributes:

```
>>> from typing import Protocol
>>> class X(Protocol):
...     a: int
...     def b(self) -> str: pass
... 
>>> X.__protocol_attrs__
{'b', 'a'}
```

This is useful for code that needs to extract the names included in a Protocol at runtime. Previously, this was quite difficult, as you had to look at the class's `__dict__` and `__annotations__` directly and exclude a long list of internal attributes (e.g. https://github.com/quora/pyanalyze/blob/bd7f520adc2d8b098be657dfa514d1433bea3b0c/pyanalyze/checker.py#L428).

However, currently `__protocol_attrs__` is an undocumented private attribute. I think we should either document it or add an introspection helper like `typing.get_protocol_attrs()` that exposes it.

### Linked PRs
* gh-104878

**Comment by JelleZijlstra** [comment]
Yes, I think a getter function makes sense here. I was just thinking about this while writing a patch for #104874, where I do think it makes sense to simply document the dunder attribute. The difference there is that the `NewType` class itself is simple and the attribute isn't used at runtime. Protocols, on the other hand, have to deal with complex subclassing relationships and it's plausible we'll want to make changes to the implementation in the future that change how the dunder works.

**Comment by AlexWaygood** [comment]
> Yes, I think a getter function makes sense here. I was just thinking about this while writing a patch for #104874, where I do think it makes sense to simply document the dunder attribute. The difference there is that the `NewType` class itself is simple and the attribute isn't used at runtime. Protocols, on the other hand, have to deal with complex subclassing relationships and it's plausible we'll want to make changes to the implementation in the future that change how the dunder works.

Agreed on all counts.

**Comment by AlexWaygood** [comment]
`get_protocol_members()` would probably be a better name for the function, btw. I called the attribute `__protocol_attrs__` because the attribute `__protocol_attrs__` is calculated by calling `typing._get_protocol_attrs` (which has been in typing for many years, and there's no real reason to rename). But I think `__protocol_members__` would probably have been a better name for the attribute, really.

**Comment by JelleZijlstra** [comment]
Based on PR review, going to also add `typing.is_protocol`.

**Comment by Giddius** [comment]
> Based on PR review, going to also add `typing.is_protocol`.

I know that this is most relevant for `typing` but just as comment and not actual critique: 
Almost all `is_x` functions that are not builtins are part of `inspect` and most do not use the underscore format:
- `inspect.isabstract`
- `inspect.isawaitable`
- `inspect.isdatadescriptor`
- `inspect.iscoroutine`
- …

With `asyncio.iscoroutine` being in `asyncio` and `typing.is_typeddict` in typing being the exceptions.

——
This again is meant more as a comment not a critic or request.

But

**Comment by AlexWaygood** [comment]
Oh, I think this is done now! 🎉

**Comment by NeilGirdhar** [comment]
Just out of curiosity, but does `is_protocol` differ from `issubclass(..., Protocol)`?

**Comment by AlexWaygood** [comment]
> Just out of curiosity, but does `is_protocol(x)` differ from `issubclass(x, Protocol) and x not in {typing_extensions.Protocol, typing.Protocol}`?

Yes — `x` might be a subclass of `typing_extensions.Protocol`, and `is_protocol(x)` will still hold true, due to some (awful) things we do in typing_extensions to make sure that `typing.Protocol == typing_extensions.Protocol` evaluates to `True`

**Comment by AlexWaygood** [comment]
@NeilGirdhar the relevant commit is here if you'd like to read the source code :-) https://github.com/python/cpython/commit/fc8037d84c5f886849a05ec993dd0f79a356d372

**Comment by JelleZijlstra** [comment]
The more important reason is that concrete classes can be subclasses of Protocol.

```
In [1]: from typing import Protocol

In [2]: class Proto(Protocol):
   ...:     def f(self) -> int: ...
   ...: 

In [3]: class Concrete(Proto):
   ...:     def f(self) -> int: return 0
   ...: 

In [4]: issubclass(Concrete, Protocol)
Out[4]: True
```

**Comment by NeilGirdhar** [comment]
@JelleZijlstra Makes perfect sense, thanks!
