### ISSUE TITLE
"sendIng a read()able" as error message in /Lib/http/client.py

### ISSUE THREAD

**Issue by LyingDalai** [python/cpython#104924]
# Bug report

In /Lib/http/client.py line [1027](https://github.com/python/cpython/blob/278030a17d6889731d91a55e9f70cbec0b07dee8/Lib/http/client.py#L1027) and [1057](https://github.com/python/cpython/blob/278030a17d6889731d91a55e9f70cbec0b07dee8/Lib/http/client.py#L1057), the error message is `"sendIng a read()able"` which obviously smells like an abusive string replacement.

I am conscious that this is extremely minor, but somehow it bugs me and I felt like sharing 😅

### Linked PRs
* gh-104926
* gh-104970
* gh-104971

**Comment by gjyotin305** [comment]
Hello How can i take up this issue
