### ISSUE TITLE
Consider emitting buffered DEDENT tokens on the last line

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#104976]
In Python 3.12, porting the tokenizer to use the C tokenizer underneath to support PEP 701 has now a documented change in [docs.python.org/3.12/whatsnew/3.12.html#changes-in-the-python-api](https://docs.python.org/3.12/whatsnew/3.12.html#changes-in-the-python-api):

> Some final DEDENT tokens are now emitted within the bounds of the input. This means that for a file containing 3 lines, the old version of the tokenizer returned a DEDENT token in line 4 whilst the new version returns the token in line 3.

Apparently, this affects negatively some formatting tools (see https://github.com/PyCQA/pycodestyle/issues/1142). Let's consider what options do we have and see if we can fix this without adding a lot of maintenance burden to the C tokenizer or slowing down everything.

### Linked PRs
* gh-104980
* gh-105000

**Comment by pablogsal** [comment]
We can do something like this:

```diff
diff --git a/Lib/tokenize.py b/Lib/tokenize.py
index 911f0f12f9..63dc44b0dc 100644
--- a/Lib/tokenize.py
+++ b/Lib/tokenize.py
@@ -452,7 +452,9 @@ def _tokenize(rl_gen, encoding):
         yield token
     if token is not None:
         last_line, _ = token.start
-        yield TokenInfo(ENDMARKER, '', (last_line + 1, 0), (last_line + 1, 0), '')
+        if token.type != DEDENT:
+            last_line != 1
+        yield TokenInfo(ENDMARKER, '', (last_line, 0), (last_line, 0), '')


 def generate_tokens(readline):
diff --git a/Parser/tokenizer.c b/Parser/tokenizer.c
index 1e8f785a33..376359179a 100644
--- a/Parser/tokenizer.c
+++ b/Parser/tokenizer.c
@@ -1762,12 +1762,12 @@ tok_get_normal_mode(struct tok_state *tok, tokenizer_mode* current_tok, struct t
     /* Return pending indents/dedents */
    if (tok->pendin != 0) {
         if (tok->pendin < 0) {
-            if (tok->tok_extra_tokens) {
+           if (tok->tok_extra_tokens) {
                 p_start = tok->cur;
                 p_end = tok->cur;
-            }
-            tok->pendin++;
-            return MAKE_TOKEN(DEDENT);
+           }
+           tok->pendin++;
+           return MAKE_TOKEN(DEDENT);
         }
         else {
             if (tok->tok_extra_tokens) {
diff --git a/Python/Python-tokenize.c b/Python/Python-tokenize.c
index 88087c1256..2a09dfd94a 100644
--- a/Python/Python-tokenize.c
+++ b/Python/Python-tokenize.c
@@ -214,6 +214,10 @@ tokenizeriter_next(tokenizeriterobject *it)
     }

     if (it->tok->tok_extra_tokens) {
+        if (type == DEDENT && it->tok->done == E_EOF) {
+            lineno = end_lineno = lineno + 1;
+            col_offset = end_col_offset = 0;
+        }
         // Necessary adjustments to match the original Python tokenize
         // implementation
         if (type > DEDENT && type < OP) {
```

but I think this forces us to somehow handle the ENDMARKER internally. Maybe that's a possible solution.

**Comment by pablogsal** [comment]
@lysnikolaou thoughts?

**Comment by pablogsal** [comment]
CC: @mgmacias95

**Comment by pablogsal** [comment]
Opened https://github.com/python/cpython/pull/104980 to test this idea

**Comment by lysnikolaou** [comment]
Yeah, I think that, if we want to support doing the same thing as 3.11, the only way is to special-case it `Python-tokenize.c` and not in the C tokenizer itself.

**Comment by pablogsal** [comment]
> Yeah, I think that, if we want to support doing the same thing as 3.11, the only way is to special-case it `Python-tokenize.c` and not in the C tokenizer itself.

Ok, then check if you like https://github.com/python/cpython/pull/104980
