### ISSUE TITLE
Make PY_SSIZE_T_CLEAN not mandatory again

### ISSUE THREAD

**Issue by methane** [python/cpython#104922]
# Feature or enhancement

Use ssize_t version API regardless PY_SSIZE_T_CLEAN is defined.

No change to ABI.

# Pitch

After Python 3.12 become EOL, extension developers can forget about PY_SSIZE_T_CLEAN completely.

# Previous discussion

https://mail.python.org/archives/list/python-dev@python.org/thread/KSREO43D6GQWO5LMVIU2LF7CP4IBYT2C/#FG44N6RL5CT5O3XQ6UV6LBLUCET7IF6I

### Linked PRs
* gh-104923
* gh-105051
* gh-106314
* gh-106315

**Comment by vstinner** [comment]
> After Python 3.12 become EOL, extension developers can forget about PY_SSIZE_T_CLEAN completely.

Python stdlib extensions still define the PY_SSIZE_T_CLEAN macro. Is it still useful? It's unclear to me.

Also, the official documentation also requires to define the PY_SSIZE_T_CLEAN macro: https://docs.python.org/dev/extending/extending.html

```
The first two lines of our file can be:

#define PY_SSIZE_T_CLEAN
#include <Python.h>

(...)

It is recommended to always define PY_SSIZE_T_CLEAN before including Python.h.
```

**Comment by methane** [comment]
See right after the doc. I added the link to https://docs.python.org/dev/c-api/arg.html#arg-parsing-string-and-buffers

And there is a note about it at link target.

> Note On Python 3.12 and older, the macro PY_SSIZE_T_CLEAN must be defined before including Python.h to use all # variants of formats (s#, y#, etc.) explained below. This is not necessary on Python 3.13 and later.

**Comment by vstinner** [comment]
The (extension) doc should just explain that the macro was needed on Python 3.12 and older.

**Comment by vstinner** [comment]
As a side effect, this change fixed the stable ABI: https://github.com/python/cpython/issues/71686. Thanks!
