### ISSUE TITLE
stable_abi.py --all fails on Windows

### ISSUE THREAD

**Issue by encukou** [python/cpython#105091]
The `--all` command [from the devguide](https://devguide.python.org/developer-workflow/c-api/#adding-a-new-definition-to-the-limited-api) fails on Windows.

`--all` should only enable `unixy_check` on Unixy platforms.

### Linked PRs
* gh-105092
* gh-105133

**Comment by encukou** [comment]
@AlexWaygood Could you wrap https://github.com/python/cpython/blob/bd98b65e974b7a1e086a51e7b55131582f7a0491/Tools/build/stable_abi.py#L687 in `if UNIXY:` and check if it solves the issue?

**Comment by AlexWaygood** [comment]
> @AlexWaygood Could you wrap
> 
> https://github.com/python/cpython/blob/bd98b65e974b7a1e086a51e7b55131582f7a0491/Tools/build/stable_abi.py#L687
> 
> in `if UNIXY:` and check if it solves the issue?

Yup, this fixes things on my machine!

```diff
--- a/Tools/build/stable_abi.py
+++ b/Tools/build/stable_abi.py
@@ -684,7 +684,8 @@ def main():

     if args.all:
         run_all_generators = True
-        args.unixy_check = True
+        if UNIXY:
+            args.unixy_check = True

     try:
         file = args.file.open('rb')
```
