### ISSUE TITLE
`test_tkinter` fails on refleak run due to `support` confusion

### ISSUE THREAD

**Issue by zware** [python/cpython#105077]
# Bug report

When running the refleak test runner (`-R`), `test_tkinter` fails on the second run due to `AttributeError: module 'test.test_tkinter.support' has no attribute 'load_package_tests'`.  This is because `test_tkinter` has its own `support` module, which when imported overwrites the `support` attribute set in `Lib/test/test_tkinter/__init__.py`.  That module should instead import specific symbols from `test.support` and use them directly.

# Your environment

- CPython versions tested on: `main`, `3.12`
- Operating system and architecture: Windows, Linux, any other

### Linked PRs
* gh-105078
* gh-105079

**Comment by erlend-aasland** [comment]
Resolved by:

- gh-105078
- gh-105079
