### ISSUE TITLE
RFE: Allow using setuptools and wheel wheels from a custom directory for tests

### ISSUE THREAD

**Issue by hroncok** [python/cpython#105084]
# Bug report

In Fedora, we would like to use our wheels instead of the ones bundled/vendored in Lib/test.
Ideally, we could reuse the `--with-wheel-pkg-dir` configure option for this.

# Your environment

- CPython versions tested on: 3.12.0b1
- Operating system and architecture: Fedora Linux, all architectures

This is an issue for https://github.com/python/cpython/pull/105056

### Linked PRs
* gh-105056
* gh-105424

**Comment by lysnikolaou** [comment]
Thanks @hroncok for the push on this!
