### ISSUE TITLE
minimum_version mismatch

### ISSUE THREAD

**Issue by RobBotic1** [python/cpython#105090]
# Documentation

The documentation states "The SSL context created above will only allow TLSv1.2 and later..." However, the example code sets the minimum version to TLS 1.3 (not 1.2 as stated).

I believe [this line](https://github.com/python/cpython/blob/c39500db5254c9efee9937f951f58d87ee14cf2f/Doc/library/ssl.rst?plain=1#LL2687C20-L2687C20) should be changed to:
`   >>> client_context.minimum_version = ssl.TLSVersion.TLSv1_2`

I am happy to create a pull request, if that is helpful.

### Linked PRs
* gh-105404
* gh-107038
* gh-107039
* gh-107040
* gh-107273

**Comment by sunmy2019** [comment]
> I believe [this line](https://github.com/python/cpython/blob/c39500db5254c9efee9937f951f58d87ee14cf2f/Doc/library/ssl.rst?plain=1#LL2687C20-L2687C20) should be changed to:
> ` >>> client_context.minimum_version = ssl.TLSVersion.TLSv1_2`

This part was changed in response to the deprecation of TLSv1_2. https://github.com/python/cpython/commit/2875c603b2a7691b55c2046aca54831c91efda8e

You should change the description text below instead.

https://github.com/python/cpython/blob/c39500db5254c9efee9937f951f58d87ee14cf2f/Doc/library/ssl.rst#L2691

**Comment by RobBotic1** [comment]
I believe there are still issues here (and my apologies for dropping the ball and not weighing in earlier -- the closing of the issue sent me a notification prompting me to look again).

First, I do not think it matters whether or not TLS 1.2 is deprecated. The example is simply showing how to restrict the preferred version used.

Second, the text states "and later" but the example sets a maximum_version as well as a minimum_version.

Finally, I think a useful example would actually show a range and how both minimum_version and maximum_version could be used together to restrict to that range.

For example, a minimum_version of ssl.TLSVersion.TLSv1_2 and a maximum_version of ssl.TLSVersion.TLSv1_3 would restrict to a range of TLS 1.2 and TLS 1.3, even if there are later versions in the future.

To match the current text, "The SSL context created above will only allow TLSv1.3 and later (if supported by your system)," the maximum_version would need to be left out.

**Comment by janbrasna** [comment]
> > I believe [this line](https://github.com/python/cpython/blob/c39500db5254c9efee9937f951f58d87ee14cf2f/Doc/library/ssl.rst?plain=1#LL2687C20-L2687C20) should be changed to:
> > ` >>> client_context.minimum_version = ssl.TLSVersion.TLSv1_2`
> 
> This part was changed in response to the deprecation of TLSv1_2. [2875c60](https://github.com/python/cpython/commit/2875c603b2a7691b55c2046aca54831c91efda8e)

I believe this was done mistakenly, as in reality there is no "deprecation of TLSv1.2", only some older features including how a connection is configured. Therefore:
- yes, `ssl.PROTOCOL_TLSv1_2` was deprecated;
- but no, `ssl.TLSVersion.TLSv1_2` is not deprecated and is completely fine to use.

That means there's no reason to not allow a TLSv1.2 connection as an example in the docs when connected using the current client_context, so the original wording was right.

What was also introduced in said change was a maximum_version that doesn't match the description, so it should have been either left out completely, or the description and configuration options rewritten entirely to demonstrate a different point than before with the OP flags.

**Comment by janbrasna** [comment]
The linked PR #105404 didn't resolve the mismatch as the example still doesn't match its description, so issues like #95816 remain open.

I think the best fix is reporter's proposed #107273 to show a range of TLSv1.2–v1.3 until someone rewrites the example completely to make a different point.
