### ISSUE TITLE
`datetime` documentation regarding ISO8601 reduced precision and extend representation

### ISSUE THREAD

**Issue by nhhollander** [python/cpython#105031]
# Documentation

The documentation for [date.fromisoformat()](https://github.com/python/cpython/blob/b9e2d8076981b471952355b86f90064ce3941032/Doc/library/datetime.rst?plain=1#LL527C8-L527C8), and [datetime.fromisoformat()](https://github.com/python/cpython/blob/b9e2d8076981b471952355b86f90064ce3941032/Doc/library/datetime.rst?plain=1#L993) refer to these function as as being able to accept "any valid ISO 8601 format", however there are a couple notable exceptions to this support beyond what is already mentioned in the documentation. I know that Python's date parsing code intentionally does not implement the full ISO 8601 specification for simplicity reasons, but I feel like this could be better conveyed by the current documentation.

Below is a summary of ISO 8601 date stamps that are not supported by the `datetime` module.
* Reduced Precision Date Representations (ISO8601-1:2019§5.2.2.2)
* Extended Date Representations (ISO8601-1:2019§5.2.2.3)
* Ordinal Date Representations (ISO8601-1:2019§5.2.3): This is already mentioned in the documentation
* Local Time Representations with Decimal Fraction (ISO8601-1:2019§5.3.1.4): This is already mentioned in the documentation

### Linked PRs
* gh-105049
* gh-114866
* gh-114867

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @nhhollander.
