### ISSUE TITLE
PathDistribution normalized name ignores name components after first "-"

### ISSUE THREAD

**Issue by itamaro** [python/cpython#105025]
reported this [here](https://github.com/python/importlib_metadata/issues/459) last week, not sure whether it should be filed on cpython or importlib_metadata.

I came across this issue when switching from python 3.10.5 to 3.10.9. It manifested as flake8 failure due to missing entry points when flake8-plugin-utils is also installed.

minimal repro showing the issue:

```python
# python 3.10.9
>>> from importlib.metadata import PathDistribution
>>> PathDistribution("flake8.egg-info")._normalized_name
'flake8'
>>> PathDistribution("flake8-plugin-utils.egg-info")._normalized_name
'flake8'
```

```python
# python 3.10.5
>>> from importlib.metadata import PathDistribution
>>> PathDistribution("flake8.egg-info")._normalized_name
'flake8.egg'
>>> PathDistribution("flake8-plugin-utils.egg-info")._normalized_name
'flake8'
```

the fact that both normalized names are identical in 3.10.9 makes `entry_points()` miss entry points data from flake8.

generally, based on [PyPA name normalization spec](https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization), I would expect the normalized name for `flake8-plugin-utils` to be `flake8-plugin-utils`, not `flake8`.

**Comment by jaraco** [comment]
Let's address this issue in importlib_metadata.
