### ISSUE TITLE
pytz.timezone('Asia/Shanghai') has a bug!

### ISSUE THREAD

**Issue by mikezang** [python/cpython#105015]
# Bug report

The pytz.timezone('Asia/Shanghai') is not correct with a bug!

# Your environment

Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

You will find the bug If you run this code! The pytz.timezone('Asia/Shanghai') should be +8:00 in time zone, but it return +8:06!
 

```python
from datetime import datetime, timedelta
import pytz
chinaTime = datetime(2023, 5, 27, tzinfo=pytz.timezone('Asia/Shanghai'))
print(f'China time: {chinaTime}')
utcTime = chinaTime.astimezone(pytz.UTC)
print(f' UTC time: {utcTime}')
```

```
China time: 2023-05-27 00:00:00+08:06 -> this should be 2023-05-27 00:00:00+08:00
UTC time: 2023-05-26 15:54:00+00:00 -> and this should be 2023-05-26 16:00:00+00:00
```

There is No any special setup, just install pyhton and install need packages, That will be error for all datetime calculation for China Time zone!

**Comment by chgnrdv** [comment]
`pytz` is not a part of Python standard library but a third-party package. Python has `zoneinfo` library that, I guess, serves the same purpose, and I can't reproduce your bug using it:
```python
from datetime import datetime, timedelta
import zoneinfo
chinaTime = datetime(2023, 5, 27, tzinfo=zoneinfo.ZoneInfo('Asia/Shanghai'))
print(f'China time: {chinaTime}')
utcTime = chinaTime.astimezone(zoneinfo.ZoneInfo('UTC'))
print(f'UTC time: {utcTime}')
```
```
China time: 2023-05-27 00:00:00+08:00
UTC time: 2023-05-26 16:00:00+00:00
```

**Comment by chgnrdv** [comment]
`pytz` is not a part of Python standard library but a third-party package. Python has `zoneinfo` library that, I guess, serves the same purpose and uses the same database, and I can't reproduce your bug using it:
```python
from datetime import datetime, timedelta
import zoneinfo
chinaTime = datetime(2023, 5, 27, tzinfo=zoneinfo.ZoneInfo('Asia/Shanghai'))
print(f'China time: {chinaTime}')
utcTime = chinaTime.astimezone(zoneinfo.ZoneInfo('UTC'))
print(f'UTC time: {utcTime}')
```
```
China time: 2023-05-27 00:00:00+08:00
UTC time: 2023-05-26 16:00:00+00:00
```

**Comment by mikezang** [comment]
Thanks a lot! 
I didn't know zoneinfo:(

**Comment by hugovk** [comment]
The author of https://yongweiwu.wordpress.com/2019/09/01/time-zones-in-python/ ran into the same thing:

```pycon
>>> from datetime import datetime
>>> from pytz import timezone
>>> timezone('Asia/Shanghai')
<DstTzInfo 'Asia/Shanghai' LMT+8:06:00 STD>
>>> (datetime(2017, 6, 1, tzinfo=timezone('Asia/Shanghai'))
...  - datetime(2017, 6, 1, tzinfo=timezone('UTC'))
... ).total_seconds()
-29160.0
```

> Sh*t! Was _pytz_ a joke? The time zone of Shanghai (or China) should be UTC+08:00, and I did not care a bit about its local mean time (I was, of course, expecting `-28800` on the last line). What was the author thinking about? 
> 
> ...
> 
> When [answering a StackOverflow question](https://stackoverflow.com/questions/13866926/is-there-a-list-of-pytz-timezones/48566388#48566388), I realized I misunderstood _pytz_. I still thought it had some bad design decisions; however, it would have been able to achieve everything I needed, if I had read its manual carefully (I cannot help remembering the famous acronym ‘RTFM’). It was explicitly mentioned in the manual that passing a _pytz_ time zone to the datetime constructor (as I did above) ‘“does not work” with pytz for many timezones’. One has to use the _pytz_ `localize` method or the standard `astimezone` method of `datetime`.


And indeed https://pythonhosted.org/pytz/ says:

> Note
> 
> This library differs from the documented Python API for tzinfo implementations; if you want to create local wallclock times you need to use the `localize()` method documented in this document. In addition, if you perform date arithmetic on local times that cross DST boundaries, the result may be in an incorrect timezone (ie. subtract 1 minute from 2002-10-27 1:00 EST and you get 2002-10-27 0:59 EST instead of the correct 2002-10-27 1:59 EDT). A `normalize()` method is provided to correct this. Unfortunately these issues cannot be resolved without modifying the Python datetime implementation (see PEP-431).

So to modify your code:

```diff
 from datetime import datetime, timedelta
 import pytz
-chinaTime = datetime(2023, 5, 27, tzinfo=pytz.timezone('Asia/Shanghai'))
+shanghai = pytz.timezone('Asia/Shanghai')
+chinaTime = shanghai.localize(datetime(2023, 5, 27))
 print(f'China time: {chinaTime}')
 utcTime = chinaTime.astimezone(pytz.UTC)
 print(f' UTC time: {utcTime}')
```

Gives:

```
China time: 2023-05-27 00:00:00+08:00
 UTC time: 2023-05-26 16:00:00+00:00
```
