### ISSUE TITLE
multiplication error

### ISSUE THREAD

**Issue by robertmontreuil** [python/cpython#105019]
![Screenshot from 2023-05-27 10-58-23](https://github.com/python/cpython/assets/19896434/01973432-475c-40c7-80c6-aef2f0b5fbeb)

It should be 62.4

in case the attached screen shot is not visible, using python 3.10.6, I multiply 5.2*12 and the answer is 62.400000000000006

**Comment by hugovk** [comment]
This isn't a Python bug, it's a result of how floating points are stored by computers.

It's similar in JavaScipt:

<img width="147" alt="image" src="https://github.com/python/cpython/assets/1324225/980e888f-fbba-4066-8832-7dca8ec7ec3d">


See https://docs.python.org/3/tutorial/floatingpoint.html

**Comment by hugovk** [comment]
And see https://social.jvns.ca/@b0rk/110180843060675818 for a nice explanation in a comic.

**Comment by AlexWaygood** [comment]
@robertmontreuil, please also note for the future that posting screenshots is generally discouraged when asking questions about code or filing bug reports about code. See https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors for why :)

**Comment by terryjreedy** [comment]
@robertmontreuil We encourage beginners who think they have found a bug to first post on https://discuss.python.org/c/users/7.
