### ISSUE TITLE
About the location of "sudo find / -iname 'Python.h' "

### ISSUE THREAD

**Issue by protfor** [python/cpython#105076]
Dear 

1. My environment is as follows.
 - Ubuntu 22.04lts
 -  Python 3.10.6

2. When I command "sudo find / -iname 'Python.h'" in my environment, I get the following...
  h19078@h19078:~$ sudo find / -iname 'Python.h'
  /home/h19078/.local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/python.h
  find: ‘/run/user/1000/gvfs’: no permission
  find: ‘/run/user/1000/doc’: no permission
  /usr/include/python3.10/Python.h

3. The location of python.h in above 2. is too deep,
I think it should be in a shallow place like the below.
  /usr/include/python3.10/Python.h

-> Please let me know how to solve this !

**Comment by sunmy2019** [comment]
Help requests should go here:
https://discuss.python.org/c/users/7



> 2\. /home/h19078/.local/lib/python3.10/site-packages/debugpy/_vendored/pydevd/pydevd_attach_to_process/common/python.h

This is not what you should include.



> 4\. /usr/include/python3.10/Python.h

It is. Have you installed this one? https://packages.ubuntu.com/jammy/libpython3.10-dev
https://packages.ubuntu.com/jammy/amd64/libpython3.10-dev/filelist

**Comment by protfor** [comment]
Dear sunmy2019

Thank you very much.

The information you shared allowed me to move forward with my work!
