### ISSUE TITLE
test_create_directory_with_write in test_zipfile fails in AIX

### ISSUE THREAD

**Issue by ayappanec** [python/cpython#105089]
test_create_directory_with_write in test_zipfile fails in AIX with the below message

======================================================================
FAIL: test_create_directory_with_write (test.test_zipfile.test_core.TestWithDirectory.test_create_directory_with_write)

Traceback (most recent call last):
  File "/cpython/Lib/test/test_zipfile/test_core.py", line 2879, in test_create_directory_with_write
    self.assertEqual(zinfo.external_attr, (mode << 16) | 0x10)
AssertionError: 1106051088 != 5401018384

----------------------------------------------------------------------

The reason being AIX stat call st_mode returns 240700 (in octal) for a directory with 700 mode. In linux, it returns 40700. So there is extra  “2” which seems to be related to journaled filesystem. So the logic requires that the mode should go a bitwise AND operation with 0xFFFF ,  like how it is done in **test_write_dir** in **test_core.py** to be in sync with **zinfo.external_attr**

### Linked PRs
* gh-105228
* gh-114860
* gh-114861

**Comment by hugovk** [comment]
Closing because the PRs have been merged and backported. Thanks!
