### ISSUE TITLE
Documentation of `timeit.Timer.timeit` should mention that the return value depends on the timer

### ISSUE THREAD

**Issue by tfpf** [python/cpython#105052]
# Documentation
At the moment, it is as follows.
https://github.com/python/cpython/blob/cb4615fd43e678fe44e9aeb6a486475a05b492e7/Lib/timeit.py#L164-L169

The return value may not always be a float measured in seconds. If a different `timer` function is used:
```
timeit.timeit(timer=time.perf_counter_ns)
```
then it is an integer measured in nanoseconds.

Not entirely sure how to document it unambiguously, but perhaps it can be reworded to say something like: '… as a number measured in the time unit returned by the `timer` argument of the constructor (by default: a float measured in seconds).' Or similar?

### Linked PRs
* gh-105060
* gh-108534
* gh-108535

**Comment by Cherrymelon** [comment]
Yes, the function docstring and doc page need update

**Comment by terryjreedy** [comment]
How about replacing
> a number of times, as a float measured in seconds.  The 
with
> a number of times.  The time is float seconds unless integer nanoseconds for perf_counter_ns.  The

**Comment by terryjreedy** [comment]
I suggest [timeit doc](https://docs.python.org/3/library/timeit.html#module-timeit)
```
timeit.default_timer()

    The default timer, which is always time.perf_counter().
```
be expanded to
```
timeit.default_timer()

    The default timer, which is always time.perf_counter(), returns float seconds.
    The alternative time.perf_counter_ns returns integer nanoseconds.
```

**Comment by pochmann** [comment]
It's not just seconds and nanoseconds, but really anything subtractable. For example you can do milliseconds with `timer=lambda: perf_counter() * 1e3`.

**Comment by Cherrymelon** [comment]
So,the update description:
```
timeit.default_timer()

    The default timer, which is  used time.perf_counter(), returns float seconds.
    However,other timer is permitted to substitute,like perf_counter_ns or custom function.
    Note that the time unit of retrun value  depend on the function what used.
```

Any good advice?

**Comment by tfpf** [comment]
I think a few examples are necessary to clear all bases. In addition to terryjreedy's idea:

> … returns the time it takes to execute the main statement a number of times. The return type is a float measured in seconds, unless a different timer function is used. See the examples section for more information.

And maybe just above 
https://github.com/python/cpython/blob/cb4615fd43e678fe44e9aeb6a486475a05b492e7/Doc/library/timeit.rst#L310
one could insert:
> You can specify a different timer function to measure the time in different units.
> ```
> >>> import time
> >>> import timeit
> >>> timeit.timeit('True != False')  # uses time.perf_counter be default, hence returns a float measured in seconds
> 0.020857657000306062
> >>> timeit.timeit('True != False', timer=time.perf_counter_ns)  # returns an integer measured in nanoseconds
> 20996968
> >>> timeit.timeit('True != False', timer=lambda: time.perf_counter() * 1000)  # returns a float measured in milliseconds
> 20.884455997496843
> ```

The docstring could probably just say that the return value depends on the timer specified.

**Comment by tfpf** [comment]
Is there any progress on this issue? The linked pull does not seem to have been updated.

**Comment by terryjreedy** [comment]
I plan on choosing from among the alternatives tomorrow to update.

**Comment by Cherrymelon** [comment]
I'm busy with new job recently,thx your work @terryjreedy

**Comment by tfpf** [comment]
The documentation hasn't been updated yet?

I am not proficient with reST, but would be willing to give this a shot using the suggestions here and in https://github.com/python/cpython/pull/105060.

**Comment by terryjreedy** [comment]
I have edited the PR and will merge when CI passes.
