### ISSUE TITLE
Tokenizer produces different output on Windows on py312 for ends of files

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#105017]
# Bug report

If you copy and paste the following code into a `repro.py` file and run `python -m tokenize` on it on a Windows machine, the output is different on 3.12/3.13 compared to what it was on 3.11 (the file ends with a single newline):

```py
foo = 'bar'
spam = 'eggs'
```

On Python 3.11, on Windows, the output is this:

```
> python -m tokenize cpython/repro.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,3:            NAME           'foo'
1,4-1,5:            OP             '='
1,6-1,11:           STRING         "'bar'"
1,11-1,13:          NEWLINE        '\r\n'
2,0-2,4:            NAME           'spam'
2,5-2,6:            OP             '='
2,7-2,13:           STRING         "'eggs'"
2,13-2,15:          NEWLINE        '\r\n'
3,0-3,0:            ENDMARKER      ''
```

On Python 3.13 (@ https://github.com/python/cpython/commit/6e62eb2e70a9f2a8099735989a58e8c8cfb4a2f2) on Windows, however, the output is this:

```
> python -m tokenize repro.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,3:            NAME           'foo'
1,4-1,5:            OP             '='
1,6-1,11:           STRING         "'bar'"
1,11-1,12:          NEWLINE        '\n'
2,0-2,4:            NAME           'spam'
2,5-2,6:            OP             '='
2,7-2,13:           STRING         "'eggs'"
2,13-2,14:          NEWLINE        '\n'
3,0-3,1:            NL             '\n'
4,0-4,0:            ENDMARKER      ''
```

There appear to be two changes here:
- All the NEWLINE tokens now have `\n` values, whereas on Python 3.11 they all had `\r\n` values
- There is an additional NL token at the end, immediately before the ENDMARKER token.

As discussed in https://github.com/PyCQA/pycodestyle/issues/1142, this appears to be Windows-specific, and _may_ be the cause of a large number of spurious W391 errors from the pycodestyle linting tool. (W391 dictates that there should be one, and only one, newline at the end of a file.) The pycodestyle tool is included in flake8, meaning that test failures in pycodestyle can cause test failures for other flake8 plugins. (All tests for [the flake8-pyi plugin](https://github.com/PyCQA/flake8-pyi), for example, currently fail on Python 3.13 on Windows.)

# Your environment

```
Python 3.13.0a0 (heads/main:6e62eb2e70, May 27 2023, 14:00:13) [MSC v.1932 64 bit (AMD64)] on win32
```

### Linked PRs
* gh-105022
* gh-105023
* gh-105030
* gh-105041

**Comment by pablogsal** [comment]
CC: @mgmacias95

**Comment by AlexWaygood** [comment]
#105022 fixes the issue of the additional NL token at the end of the file on Windows, but there are still differences on Windows between what the tokenizer produced on 3.11 and what it produces on #105022.

On 3.11 on Windows:

```
>python -m tokenize cpython/repro.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,3:            NAME           'foo'
1,4-1,5:            OP             '='
1,6-1,11:           STRING         "'bar'"
1,11-1,13:          NEWLINE        '\r\n'
2,0-2,4:            NAME           'spam'
2,5-2,6:            OP             '='
2,7-2,13:           STRING         "'eggs'"
2,13-2,15:          NEWLINE        '\r\n'
3,0-3,0:            ENDMARKER      ''
```

Using #105022:

```
> python -m tokenize repro.py
0,0-0,0:            ENCODING       'utf-8'
1,0-1,3:            NAME           'foo'
1,4-1,5:            OP             '='
1,6-1,11:           STRING         "'bar'"
1,11-1,12:          NEWLINE        '\n'
2,0-2,4:            NAME           'spam'
2,5-2,6:            OP             '='
2,7-2,13:           STRING         "'eggs'"
2,13-2,14:          NEWLINE        '\n'
3,0-3,0:            ENDMARKER      ''
```

Note that the same tokens are emitted now as were emitted on 3.11, but the line/column coordinates in the first column are off by one for the NEWLINE tokens.

(I'm still seeing loads of flake8-pyi test failures using #105022, and I'm presuming this is the cause.)

**Comment by pablogsal** [comment]
@AlexWaygood can you check again with the new PR?

**Comment by AlexWaygood** [comment]
> @AlexWaygood can you check again with the new PR (#105030)?

Will check either this evening or tomorrow

**Comment by AlexWaygood** [comment]
Well, I have good news and bad news.

The good news is that, on Windows, the tokenize module _appears_ to now be producing exactly the same output on `main` as it did on 3.11.

The bad news is that the spurious pycodestyle W391 errors discussed in https://github.com/PyCQA/pycodestyle/issues/1142 still haven't gone away, even using CPython `main`. These definitely bisect to https://github.com/python/cpython/commit/6715f91edcf6f379f666e18f57b8a0dcb724bf79, so something else must be going on to cause these failures :(

Regardless, the original bug reported here has definitely been fixed, so I'll close this for now, and I'll open a new issue once I've done some more investigation into what might be causing the spurious W391 errors and (hopefully) found a minimal repro that doesn't involve third-party code. Thanks @pablogsal and @mgmacias95 for all your hard work on this!

**Comment by AlexWaygood** [comment]
> I'll open a new issue once I've done some more investigation into what might be causing the spurious W391 errors and (hopefully) found a minimal repro that doesn't involve third-party code. Thanks @pablogsal and @mgmacias95 for all your hard work on this!

I've tried to investigate, but I can't immediately figure out what might be causing these W391 errors. I suspect it'll need somebody more familiar with pycodestyle's architecture and/or the tokenize module to figure out whether this is, in fact, a CPython bug at all -- and if it is, to produce a minimal repro that doesn't depend on pycodestyle.
