### ISSUE TITLE
`re.compile` is compiling a invalid regex

### ISSUE THREAD

**Issue by mrwbarg** [python/cpython#105121]
# Bug report

`re.compile` is compiling a invalid regex.

# Your environment

- CPython versions tested on: 3.11.3
- Operating system and architecture: Windows 10 x64

`re.compile` compiles the following expression: `"[0-9]++"`
which should be invalid regex.

**Comment by lukeroot** [comment]
[Possessive quantifiers](https://www.regular-expressions.info/possessive.html) were added in 3.11 https://github.com/python/cpython/issues/34627/

**Comment by terryjreedy** [comment]
See https://docs.python.org/3/library/re.html#regular-expression-syntax.  Beginners, especially, should direct questions about syntax to https://discuss.python.org/c/users/7.
