### ISSUE TITLE
Readability?

### ISSUE THREAD

**Issue by busterbeam** [python/cpython#105188]
https://github.com/python/cpython/blob/85b0b0cd947c5218260fb2bc2014c8c8de172d33/Lib/json/__init__.py#L299-L359

The doc-string can stay. But I don't think the conditional statements are quite sensible.

Why not something like

```python
def loads(string, *, **kwargs):
    if not isinstance(string, (str, bytes, bytearray)):
        raise TypeError(
            f"The JSON object must be str, bytes or bytearray, not {string.__class__.__name__}")
    if isinstance(string, (bytes, bytearray)):
        string = string.decode(detect_encoding(string), "surrogatepass")
    if string.startswith('\ufeff'):
        raise JSONDecodeError(
            "Unexpected UTF-8 BOM (decode using utf-8-sig)", string, 0)
    if not kwargs:
        return _default_decoder.decode(string)
    cls = kwargs.pop("cls", JSONDecoder)
    return cls(**kwargs).decode(string)
```
with comments in case the above doesn't make any sense
```python
def loads(string, *, **kwargs):
    # start by checking "string-like"
    if not isinstance(string, (str, bytes, bytearray)):
        raise TypeError(
            f"The JSON object must be str, bytes or bytearray, not {string.__class__.__name__}")
    # decode byte like objects
    if isinstance(string, (bytes, bytearray)):
        string = string.decode(detect_encoding(string), "surrogatepass")
    # check for magic 
    if string.startswith('\ufeff'):
        raise JSONDecodeError(
            "Unexpected UTF-8 BOM (decode using utf-8-sig)", string, 0)
    # no decoder options? just decode then
    if not kwargs:
        return _default_decoder.decode(string)
    # if there is a `cls` in key word arguments pop it out to use or just
    # use the `JSONDecoder`
    cls = kwargs.pop("cls", JSONDecoder)
    return cls(**kwargs).decode(string)
```

Most of the conditional statements before were just moving from one mapping to another, with the one exception which we can pop off of a mapping right?  I re-arranged the first if statements to reduce nesting

**Comment by sunmy2019** [comment]
Why are you removing all keyword args?

**Comment by sobolevn** [comment]
Thanks for the suggestion!

Generally we don't accept stylistic changes like that. History and correctness are more important that style (because it is subjective). 

But, if you found a bug, please explain what do you expect to happen and what happens.

If you want to contribute, please take any existing issue :)
There are some dedicated to `json` module if you are specifically interested in it.

**Comment by sunmy2019** [comment]
> But I don't think the conditional statements are quite sensible.

It clarifies what keyword args are needed. You can immediately tell from the call site.

IDE can provide more auto completions, checkers do more checks.

```
(function) def loads(
    s: str | bytes | bytearray,
    *,
    cls: Type[JSONDecoder] | None = None,
    object_hook: ((dict[Any, Any]) -> Any) | None = None,
    parse_float: ((str) -> Any) | None = None,
    parse_int: ((str) -> Any) | None = None,
    parse_constant: ((str) -> Any) | None = None,
    object_pairs_hook: ((list[tuple[Any, Any]]) -> Any) | None = None,
    **kwds: Any
) -> Any
```

Technically we can make every function has the signature
```py
def foo(*args, **kwargs): ...
```
But people won't do it. Completely dynamic isn't what you always want.

**Comment by busterbeam** [comment]
> Why are you removing all keyword args? Removing them will bring users more confusion about what kwargs are needed.

that is the purpose of the doc-string (partially).  I did not remove the keyword arguments I removed the default keyword arguments.  if your read the changes carefully you will see that most of the default keyword arguments were being passed into "kw", I'm cutting out this "middle-man", this technically could be a performance improvement, but I haven't run any tests.  We could also differ the user or modify the `loads` function at runtime to copy the `__doc__` string from `JSONDecoder.__init__` as that is where the keywords are actually being used.  

Furthermore I think the removal of "default" keyword arguments are important here as they all encode to None, if there defaults were to other "special" values it would be helpful.  furthermore "default" keyword arguments have memory between calls as far as I'm aware

> Technically we can make every function has the signature

This would be placed into the `JSONDecoder` right?  Not here? IDE's would be able to read that from being aware that its just a decoder wrapper.

**Comment by sunmy2019** [comment]
> this change shouldn't change anything in terms of compatibility as far as I'm aware

It's true.

But just like I mentioned, the IDE or the linters will not be that smart to guess what should be inside the **. You can test on yours.

**Comment by busterbeam** [comment]
@terryjreedy you make a valid point about the IDE calltip's.  And I was about to leave it there and maybe re-state the de-nesting of the type checking conditions would be appreciated, but actually we can have our cake and eat it to. Here is the best of both worlds I think

```python
def loads(string, *, cls=None, object_hook=None, parse_float=None, 
        parse_int=None, parse_constant=None, object_pairs_hook=None, **kw):
    """
    Deserialize ``s`` (a ``str``, ``bytes`` or ``bytearray`` instance
    containing a JSON document) to a Python object.
    
    To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``
    kwarg; otherwise ``JSONDecoder`` is used.
    
    The following ``JSONDecoder`` arguments are:
    """
    if not isinstance(string, (str, bytes, bytearray)):
        raise TypeError(
            f"The JSON object must be str, bytes or bytearray, not {string.__class__.__name__}")
    if isinstance(string, (bytes, bytearray)):
        string = string.decode(detect_encoding(string), "surrogatepass")
    if string.startswith('\ufeff'):
        raise JSONDecodeError(
            "Unexpected UTF-8 BOM (decode using utf-8-sig)", string, 0)
    defkw, local = loads.__kwdefaults__, locals()
    kw.update({k: local[k] for k in defkw if defkw[k] != local[k]})
    if not kw:
        return _default_decoder.decode(string)
    cls = kw.pop("cls", JSONDecoder)
    return cls(**kw).decode(string)

loads.__doc__ += JSONDecoder.__init__.__doc__
```
Another thought that came to me is the docstring.  It can stay to what it is... but I do think it could be *shortened* as it restates documentation word for word from `JSONDecoder.__init__`.  So it could all be improved by the appending a line after the function definition.
