### ISSUE TITLE
`importlib.resources.abc.TraversableResources` says it is deprecated in favour of itself

### ISSUE THREAD

**Issue by graingert** [python/cpython#105189]
# Documentation

https://docs.python.org/3.12/library/importlib.resources.abc.html#importlib.resources.abc.TraversableResources says it is deprecated in favour of itself

it should be documented here https://docs.python.org/3.12/library/importlib.html#module-importlib.abc

introduced in https://github.com/python/cpython/commit/10b12dd92ab6e29b573706dd6adb3d8eb63ae81b#r115987571

cc @jaraco @hugovk 

### Linked PRs
* gh-105232
* gh-109363

**Comment by FFY00** [comment]
Yep, the warning should be in `importlib.abc` instead of `importlib.resources.abc`.

**Comment by hugovk** [comment]
Fixed by https://github.com/python/cpython/pull/105232 and a pending backport. Thanks!
