### ISSUE TITLE
C API: Remove legacy buffer API like PyObject_AsReadBuffer()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#105186]
Would it be ok to remove the legacy "buffer" API in Python 3.13, scheduled for October 2024? I'm talking about functions:

* PyObject_AsCharBuffer()
* PyObject_CheckReadBuffer()
* PyObject_AsReadBuffer()
* PyObject_AsWriteBuffer()

This API is deprecated since Python 3.0  and is older than the new ``Py_buffer`` API. The ``Py_buffer`` API is safer: it has a PyBuffer_Release() method to notify when the consumer is done: the resource can be released. The ``Py_buffer`` API is now commonly used.

In June 2020, there was a first attempt to remove these functions in issue #85275: commit 6f8a6ee59cb7f99f68df8ee9c3e8c8cf19af3eed. It caused too many troubles and had to be reverted the following year (commit ce5e1a6809b714eb0383219190a076d9f883e008, July 2021). The removed functions were still used by at least 6 projects:

* PyQt4: **FIXED** in PyQt5 by using the safe PyObject_GetBuffer()/PyBuffer_Release() functions. PyQt4 is now legacy.
* libsolv: **FIXED**. it seems like it has been solved in https://github.com/openSUSE/libsolv/issues/410
* m2crypto: **FIXED** in m2crypto 0.37.1 by https://gitlab.com/m2crypto/m2crypto/-/commit/6bb65c27f01dd69f08c4654ce531fb283c7bcc07
* apsw: **FIXED** in 3.35.4-r1, https://github.com/rogerbinns/apsw/issues/301
* wsaccel: **FIXED** in v0.6.3: https://github.com/methane/wsaccel/issues/22 and https://github.com/methane/wsaccel/commit/b171314d883df04bf5449085e017e44dee21231f
* djvulibre: It seems like [it stills uses PyObject_AsWriteBuffer()](https://github.com/jwilk-archive/python-djvulibre/blob/181ed40594562296d74cdb5bd91fb7b964eae25b/djvu/common.pxi#L70). But https://github.com/jwilk-archive/python-djvulibre project has been archived by the owner on Oct 4, 2022 and is now read-only!

The webassets project was also mentioned, but I'm not sure that its failure is related to these removal: see https://bugzilla.redhat.com/show_bug.cgi?id=1899555 I cannot find these functions in https://github.com/Kronuz/pyScss code right now.

Sadly, the 4 functions are part of the stable ABI and have to be kept there. I'm only asking to remove them in the C API. The issue #88775 was complaining that the functions were removed wheareas they are part of the stable ABI.

**Comment by vstinner** [comment]
@methane: Would do you think? If you think that it's now ok, I can work on a PR to remove them (but keep them in the stable ABI).

**Comment by methane** [comment]
See
https://github.com/python/cpython/pull/105137

**Comment by vstinner** [comment]
Oh nice, let's discussion the discussion in issue #85275 (and PR #105137).
