### ISSUE TITLE
Python dictionary[key].append() appends passed value to all keys in the dictionary

### ISSUE THREAD

**Issue by emily-bradley** [python/cpython#105165]
In the example code below, the `dictionary[key].append()` function adds the parameter passed to `.append()` to both keys (i.e. both items) in the dictionary `value_at_each_timestep`

```
my_list = ['item1', 'item2']
current_value = dict.fromkeys(my_list, 0)
value_at_each_timestep = dict.fromkeys(my_list, [])
rounds = 3

for i in range(0, rounds):
	for item in my_list:
 		random_value = np.random.uniform(0, 1)
 		current_value[item] += random_value
 		value_at_each_timestep[item].append(current_value[item])

value_at_each_timestep
```

Output:
```
{'item1': [0.36533152548449666,
  0.5332894349809962,
  0.8286764212386598,
  0.6730809312016954,
  1.2584558921699105,
  1.1464993280925155],
 'item2': [0.36533152548449666,
  0.5332894349809962,
  0.8286764212386598,
  0.6730809312016954,
  1.2584558921699105,
  1.1464993280925155]}
  ```
  The resulting output is a two-item dictionary with list values with a length of six. The list values should have a length of 3, since for each round (of 3 rounds) we append to each item in the dictionary once.

# Your environment
* Python version tested:
    * 3.9.12
* Operating system and architecture:
    * macOS Ventura 13.3.1

**Comment by ericvsmith** [comment]
The keys all point to the same item. See https://stackoverflow.com/questions/654646/how-do-i-create-a-unique-value-for-each-key-using-dict-fromkeys for some solutions. I think `defaultdict` would be your best bet.
