### ISSUE TITLE
Documentation of `object.__eq__` is inconsistent with the behavior of it

### ISSUE THREAD

**Issue by JoHavel** [python/cpython#105198]
# Documentation

Documentation says
> By default, ``object`` implements :meth:`__eq__` by using ``is``, returning
   ``NotImplemented`` in the case of a false comparison:
   ``True if x is y else NotImplemented``. For :meth:`__ne__`, by default it
   delegates to :meth:`__eq__` and inverts the result unless it is
   ``NotImplemented``.  There are no other implied relationships among the
   comparison operators or default implementations; for example, the truth of
   ``(x<y or x==y)`` does not imply ``x<=y``. To automatically generate ordering
   operations from a single root operation, see :func:`functools.total_ordering`.

but `object() == object()` (`"1" == 1`, `str == 1`, etc.) returns `False`. It doesn't throw `NotImplemented`.

(Tested with `Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32`, `Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0]` on Ubuntu and `Python 3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110] on linux`.)

**Comment by AlexWaygood** [comment]
Building on what @ericvsmith said -- note that the `NotImplemented` singleton is a different thing to `NotImplementedError`.

https://docs.python.org/3/library/constants.html#NotImplemented

https://docs.python.org/3/library/exceptions.html#NotImplementedError

**Comment by terryjreedy** [comment]
Similarly, other operators such as `+` use the __add__ and __radd__ methods and results of the arguments as appropriate according to the operator rules.
