### ISSUE TITLE
Symbol rewriting in for-loop and lambdas

### ISSUE THREAD

**Issue by gudn** [python/cpython#105175]
# Bug report

I'm writing combinatoric parsing library and noticed one bug when using lambda in list comprehensions. I don't know what is real bug cause, but it also exists in lambda that capture loop variable.

Following code demonstrates the behavior:
```python
def constantly(x):
    return lambda _: x

def cmap(f, c):
    return lambda x: f(c(x))

data = {'a': 1, 'b': 2, 'c': 3}


print('Build list with list comprehensions')
ret = [cmap(lambda y: (k, y), constantly(x)) for k, x in data.items()]
for r in ret:
    print(r(-100))


print('Build list from plain for-loop')
ret2 = []
for k, x in data.items():
    c = cmap(lambda y: (k, y), constantly(x))
    ret2.append(c)

for r in ret2:
    print(r(-100))

print('Use function without storing')
for k, x in data.items():
    c = cmap(lambda y: (k, y), constantly(x))
    print(c(-100))
```
Results:
```
Build list with list comprehensions
('c', 1)
('c', 2)
('c', 3)
Build list from plain for-loop
('c', 1)
('c', 2)
('c', 3)
Use function without storing
('a', 1)
('b', 2)
('c', 3)
```

# Your environment

- CPython versions tested on: 3.11.3 (from docker.io/python:3.11.3)
- Operating system and architecture: Manjaro, Linux 6.1, x86_64

**Comment by JelleZijlstra** [comment]
See https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result.
