### ISSUE TITLE
Backslash in f-string format specifier gets escape

### ISSUE THREAD

**Issue by domdfcoding** [python/cpython#105194]
# Bug report

Between Python 3.12 alpha 7 and beta 1 the behaviour of format specifiers containing a backslash (e.g. `\n`, `\u2603`) in f-strings changed.

Previously, the `__format__` method would get e.g. the newline character, but it now receives a backslash and an `n` character (i.e. the string `"\n"`)

The following script demonstrates this:

```python3
# issue.py

class F:
	def __format__(self, format_spec):
		print("spec:", repr(format_spec))
		return format_spec.join(["a", "b", "c"])

print("out: ", repr((f"{F():\n}")))
print("out: ", repr((f"{F():\u2603}")))

print("out: ", repr((format(F(), "\n"))))
print("out: ", repr((format(F(), "\u2603"))))
```

```console
$ python3.11 issue.py
spec: '\n'
out:  'a\nb\nc'
spec: '☃'
out:  'a☃b☃c'
spec: '\n'
out:  'a\nb\nc'
spec: '☃'
out:  'a☃b☃c'
```

```console
$ python3.12 issue.py
spec: '\\n'
out:  'a\\nb\\nc'
spec: '\\u2603'
out:  'a\\u2603b\\u2603c'
spec: '\n'
out:  'a\nb\nc'
spec: '☃'
out:  'a☃b☃c'
```

In both cases the `format()` function works correctly - I only encounter the issue with f-strings.

I suspect this is related to the PEP 701 changes to f-strings, but I couldn't find anything in the discussion of that PEP to suggest this was a deliberate change.

# Your environment

- CPython versions tested on: Python 3.11.2, 3.12.0alpha7, 3.12.0beta1
- Operating system and architecture: Ubuntu 20.04 (AMD64)

### Linked PRs
* gh-105231
* gh-105234

**Comment by pablogsal** [comment]
@isidentical @lysnikolaou can you take this one?

**Comment by lysnikolaou** [comment]
Sure! Will probably have a look tomorrow morning.

**Comment by pablogsal** [comment]
@lysnikolaou I gave this a go and I think I have it. Can you check https://github.com/python/cpython/pull/105231 ?

**Comment by domdfcoding** [comment]
Thanks for fixing this.
