### ISSUE TITLE
stat fields wrong for files accessed over CIFS/SMB on Windows starting with 0f175766e2

### ISSUE THREAD

**Issue by jwbowen** [python/cpython#105212]
# Bug report
After upgrading Python beyond 3.12a6 on Windows (I've been playing with pathlib.Path.walk), the stat fields returned by os.stat() and pathlib.Path.stat() seem incorrect; in particular the time fields are all 0.

I'm a Unix person turned NAS admin and there's a lot of change with the Windows stat API in that commit, so I'm not qualified to venture guesses about what's going on.

If `nas` is a CIFS/SMB server, then with the following code
```python
import os
import pathlib

testfile = r'\\nas\share$\path\to\testfile.txt'

print(os.stat(testfile))
print(pathlib.Path(testfile).stat())
```

prints (with output broken up to avoid scrolling)
```
os.stat_result(st_mode=33206, st_ino=3648649231342060167, st_dev=2147484764, st_nlink=1, st_uid=0, st_gid=0,
               st_size=5236, st_atime=1682947862, st_mtime=1681251888, st_ctime=1680643578)
os.stat_result(st_mode=33206, st_ino=3648649231342060167, st_dev=2147484764, st_nlink=1, st_uid=0, st_gid=0,
               st_size=5236, st_atime=1682947862, st_mtime=1681251888, st_ctime=1680643578)

```

before commit 0f175766e2 and
```
os.stat_result(st_mode=24576, st_ino=0, st_dev=0, st_nlink=0, st_uid=0, st_gid=0,
               st_size=0, st_atime=0, st_mtime=0, st_ctime=0)
os.stat_result(st_mode=24576, st_ino=0, st_dev=0, st_nlink=0, st_uid=0, st_gid=0,
               st_size=0, st_atime=0, st_mtime=0, st_ctime=0)
```

after.

# Your environment

- **CPython versions tested on**: tagged releases 3.12a6, 3.12a7, and 3.12b1; a few commits between a6 and a7 when bisecting down to the issue. The "before/working" code above was compiled (with `PCbuild\build.bat -e -p x64`) at commit e108af6eca and the "after/broken" at commit 0f175766e2.
- **Operating system and architecture**: A Windows Server 2019 VM running on VMware 7.0U3 on an Intel Cascade Lake Xeon (x86_64). Selections from `systeminfo`
```
OS Name:                   Microsoft Windows Server 2019 Standard
OS Version:                10.0.17763 N/A Build 17763
...<snip>...
System Model:              VMware7,1
System Type:               x64-based PC
...<snip>...
BIOS Version:              VMware, Inc. VMW71.00V.17369862.B64.2012240522, 12/24/2020
```

The file share I'm accessing is on a NetApp NAS running ONTAP 9.8P18 and was accessed over SMB 3.1.

**Comment by AlexWaygood** [comment]
Cc. @zooba

**Comment by eryksun** [comment]
Note that `st_mode` is 24576 (0x6000), i.e. `S_IFBLK`. This is the same underlying problem as issue #104820. The fix will be in the next beta release.

**Comment by jwbowen** [comment]
Ah, thank you, I didn't know what to make of that value.
