### ISSUE TITLE
3.12: tokenize adds a newline when it is not there

### ISSUE THREAD

**Issue by asottile** [python/cpython#105259]
# Bug report

tokenize adds a concrete newline character when it is not present.  this breaks any sort of roundtrip source generation and pycodestyle's end-of-file checker

here's an example of a file containing a single byte (generated via `echo -n 1 > t.py`)

```console
# hd -c t.py 
00000000  31                                                |1|
0000000   1                                                            
0000001
# python3.12 -m tokenize t.py
0,0-0,0:            ENCODING       'utf-8'        
1,0-1,1:            NUMBER         '1'            
1,1-1,2:            NEWLINE        '\n'           
2,0-2,0:            ENDMARKER      ''             
# python3.11 -m tokenize t.py
0,0-0,0:            ENCODING       'utf-8'        
1,0-1,1:            NUMBER         '1'            
1,1-1,2:            NEWLINE        ''             
2,0-2,0:            ENDMARKER      '' 
```

# Your environment

- CPython versions tested on: 3.12 dbd7d7c8e1
- Operating system and architecture: ubuntu 22.04 LTS x86_64

cc @pablogsal

### Linked PRs
* gh-105364
* gh-105367

**Comment by pablogsal** [comment]
@lysnikolaou can you take a look at this? I think this is due to this line:

https://github.com/python/cpython/blob/e6373c0d8b59512aa7f0dea7f3fb162b6ed10fa4/Parser/tokenizer.c#L1268

But the real question is what is going to break if we cover that with `if (tok->extra_tokens)` and how we can fix it.

**Comment by pablogsal** [comment]
Ah wait this is because the difference is that in 3.12 the last implicit new line has a "\n" instead of an empty string?

**Comment by pablogsal** [comment]
@lysnikolaou The problem is that we are always adding a new line at the end of the line buffer so we cannot distinguish if the last one is there for real or not.

**Comment by lysnikolaou** [comment]
> The problem is that we are always adding a new line at the end of the line buffer so we cannot distinguish if the last one is there for real or not

Do we? I thought you had removed this in #104850, but apparently not. I'll have a look.

**Comment by pablogsal** [comment]
> Do we? I thought you had removed this in #104850, but I guess I misunderstood that PR. I'll have a look.

That was "reverted" because apparently that was required to keep backward compatibility IIRC

**Comment by pablogsal** [comment]
@Yhg1s can you wait until we fix this for the release?

**Comment by Yhg1s** [comment]
Yeah, I can wait.

**Comment by asottile** [comment]
yep looks fixed -- this is the only outstanding breaking change I'm encountering: #105390
