### ISSUE TITLE
PySequence_GetItem() function does not allow NULL objects in 3.10.9

### ISSUE THREAD

**Issue by roman-a-dolgov** [python/cpython#105260]
I have a python extension with objects supporting Suquence Protocol, in particular - function **sq_item()**.
According to Python documentation, it should returns sequence item if it exists for the index, or NULL otherwise. Unfrotunately, Python function PyObject * PySequence_GetItem(PyObject *s, Py_ssize_t i) (abstract.c, line 1880), which calls my implementation of sq_item() does not allow returning of NULL anymore due to the following check:
        PyObject *res = m->sq_item(s, i);
        assert(_Py_CheckSlotResult(s, "__getitem__", res != NULL));
As a result, I can no longer use debug version of my extension DLL which significantly complicates debugging process

**Comment by sunmy2019** [comment]
`NULL` is reserved for failure indication. Returning NULL needs an exception set. Breaking this invariant will leave doors open to potential bugs.

Previous behavior is buggy.

---
In what scenarios do you need to return this way? Maybe we can figure out a fix.

**Comment by roman-a-dolgov** [comment]
Okay, it looks like I need to raise the *PyExc_StopIteration *exception.

Thanks,
Roman
