### ISSUE TITLE
Link specifically to distutils migration advice in What's New

### ISSUE THREAD

**Issue by hauntsaninja** [python/cpython#105291]
I think it would be useful to link directly to https://peps.python.org/pep-0632/#migration-advice in 3.12's What's New, since that section has more specific advice.

### Linked PRs
* gh-107130
* gh-107160

**Comment by hugovk** [comment]
@hauntsaninja How does https://github.com/python/cpython/pull/107130 look?

**Comment by hauntsaninja** [comment]
Customary to leave the issue open till all backports are merged, no? Just merged it so all's good :-)

**Comment by hugovk** [comment]
Oops, thought it had been! Thanks for the merges!
