### ISSUE TITLE
Python Variables appear as hex gibberish in debugger session

### ISSUE THREAD

**Issue by mhunterP965** [python/cpython#105216]
Python variables are not presented in human-readable form during a debugging session. :(

<img width="960" alt="VSCODE_Python_Debugger_Issues" src="https://github.com/python/cpython/assets/83076462/b32fae5d-0e64-41ee-b4d0-bddadf59af7f">

Is there a config change that can fix this?

**Comment by gaogaotiantian** [comment]
This is a vscode issue, not CPython.

It also seems like the data is just what it displays - there might be some encoding issue/source issue involved but it does not seem like a bug.

**Comment by sunmy2019** [comment]
Help questions should go to
https://discuss.python.org/c/users/7

---

For your problem, explicitly add **the correct encoding** in line 10 and 40.
