### ISSUE TITLE
new throw() / athrow() syntax w/ single value is not clearly documented or noted as new in python 3.12

### ISSUE THREAD

**Issue by zzzeek** [python/cpython#105269]
# Documentation

the docs at https://github.com/python/cpython/blob/94a1eea511c53bf88dd8b1e441c8018fd9ff4a5e/Doc/reference/expressions.rst?plain=1#L755 does not note that the single arg `throw(value)` calling style appears to be new in Python 3.12; docs for 3.11 do not refer to it:  https://github.com/python/cpython/blob/8de607ab1c7605dce0efbb1a5c7148385d9176a6/Doc/reference/expressions.rst?plain=1#L743 , even though you can actually pass the "value" as the first argument to `throw()`.  It's not clear to us here if using `throw(value)` will work identically on older Python versions.     Looking at 396b58345f81d4c8c5a52546 it seems to be possibly 3.11 related, but in #96348 @gvanrossum claims "It allows passing either an exception, or a (type, value, traceback) triple where the value and traceback are optional. ", but this does not seem to be documented and is creating some confusion over here.

the [changelog](https://github.com/python/cpython/blob/94a1eea511c53bf88dd8b1e441c8018fd9ff4a5e/Doc/whatsnew/3.12.rst?plain=1#L988) as well as the deprecation warning both refer to the "single arg version" , which will "work" on older py3 versions but has different behavior (Edit: or maybe it doesn't.  we're not sure :) ).

can this document be clarified as to what differences, if any, exist between `athrow(value)` and `athrow(type, value)` and within what Python versions this new style should be accepted as an exact drop-in for the old style?  thanks

### Linked PRs
* gh-105468
* gh-105477
* gh-105478
* gh-105479
* gh-105480

**Comment by terryjreedy** [comment]
@gvanrossum @iritkatriel Questions about (doc of) athrow(v) vs. athrow(t, v) vs athrow(t,b,t) and versions.

**Comment by iritkatriel** [comment]
@zzzeek Would you like to make a patch with doc updates?

**Comment by zzzeek** [comment]
> @zzzeek Would you like to make a patch with doc updates?

if you could tell me what the docs would say?   Is there any change in behavior for `athrow(value)` vs. `athrow(type, value, tback)`?  I vaguely recall similar functions where these are in fact equivalent but my co-maintainer @caselit is not sure

**Comment by iritkatriel** [comment]
> > @zzzeek Would you like to make a patch with doc updates?
> 
> if you could tell me what the docs would say? Is there any change in behavior for `athrow(value)` vs. `athrow(type, value, tback)`? I vaguely recall similar functions where these are in fact equivalent but my co-maintainer @CaselIT is not sure

If there is then please file a bug report.

**Comment by zzzeek** [comment]
Hi - 

The bug is, "the documentation does not explain this".   I dont understand the documentation, and I dont know how to **write** the documentation because I don't understand the API.   Do I need to file a bug report under a different tag?   I had the impression that "documentation bugs" was the appropriate place to post this.

**Comment by iritkatriel** [comment]
No this issue is fine for the documentation.

**Comment by CaselIT** [comment]
> > > @zzzeek Would you like to make a patch with doc updates?
> > 
> > 
> > if you could tell me what the docs would say? Is there any change in behavior for `athrow(value)` vs. `athrow(type, value, tback)`? I vaguely recall similar functions where these are in fact equivalent but my co-maintainer @CaselIT is not sure
> 
> If there is then please file a bug report.

so the idea here is to document also for version previous to 3.12 the call signature `athrow(value)`? so copy paste the 3.12 documentation minus the deprecation?

**Comment by CaselIT** [comment]
I've created this PR https://github.com/python/cpython/pull/105468 to 3.11 branch.
Should I also create backports to other branches? Down to what version?

**Comment by iritkatriel** [comment]
Thank you @zzzeek and @CaselIT !
