### ISSUE TITLE
Ortografia Front-end

### ISSUE THREAD

**Issue by httpsdfaa** [python/cpython#105206]
# Documentation
Na versão em Português o Python falta uma letra.
SEGUE O ANEXO
![Captura de tela de 2023-06-01 18-32-10](https://github.com/python/cpython/assets/60937902/85d4cfaa-28b5-47f9-be65-ff66e5818769)

(A clear and concise description of the issue.)

**Comment by JelleZijlstra** [comment]
Thanks, reported to the Portuguese translation team at python/python-docs-pt-br#84.
