### ISSUE TITLE
Dataclass with `__module__ = "builtins"` adds `__builtins__.__builtins__`

### ISSUE THREAD

**Issue by The-Compiler** [python/cpython#105203]
# Bug report

When a dataclass with `__module__ = "builtins"` is defined (which seems somewhat common for custom exception classes), this seems to result in a `__builtins__` attribute to `__builtins__` (which recursively points to the builtins module):

```python
from dataclasses import dataclass

print(hasattr(__builtins__, "__builtins__"))

@dataclass
class Bla(Exception):

    __module__ = "builtins"

print(hasattr(__builtins__, "__builtins__"))
```

results in:

```
False
True
```

This in turn results in an `import astroid.nodes` causing an endless recursion, in the original issues due to [how schemathesis uses `dataclasses`](https://github.com/schemathesis/schemathesis/pull/1736/files#diff-c0a7dd254259e4e0371c4ba7e54bc3fda03f62e751e977f22e06879b91234aca):

Downstream reports:

- https://github.com/pylint-dev/astroid/issues/2191
- https://github.com/pytest-dev/pytest/issues/11053
- https://github.com/schemathesis/schemathesis/issues/1745

# Your environment

- CPython versions tested on: 3.7.16, 3.8.16, 3.9.16, 3.10.11, 3.11.3, 3.12.0b1
- Operating system and architecture: Archlinux 64-bit

**Comment by terryjreedy** [comment]
It is normal for modules created from Python to have attribute '__builtins__'.  I am not surprised that one is added here, so I doubt that this is a bug.

My recursive search of Lib/*.py failed to find `__module__ = "builtins"` or `__module__ = 'builtins'`.  Dataclasses might never be used in the stdlib for a custom exception.  Normal is `class CustomError(Exception): pass` or similar.

@ericvsmith Is there any point to using dataclasses for custom exceptions?

**Comment by ericvsmith** [comment]
Yes, this is because of the `exec()` behavior. I'm curious why `__module__ = "builtins"` is being used.

**Comment by The-Compiler** [comment]
From [what I can gather](https://github.com/schemathesis/schemathesis/commit/a5432405f6342477809c917e0bd1f4fcd9b7dd20), it's a hack to see `InvalidSchema` in an error message, rather than `schemathesis.exceptions.InvalidSchema`.

I have a feeling I've seen this hack used elsewhere before as well, but I can't remember where exactly.

**Comment by terryjreedy** [comment]
I see no CPython issue here.

**Comment by ericvsmith** [comment]
> From [what I can gather](https://github.com/schemathesis/schemathesis/commit/a5432405f6342477809c917e0bd1f4fcd9b7dd20), it's a hack to see `InvalidSchema` in an error message, rather than `schemathesis.exceptions.InvalidSchema`.

Irrespective of this particular issue, it seems like a bad idea to hide the type of an exception.

**Comment by Stranger6667** [comment]
@The-Compiler 

You're right about the reason it was implemented this way. I found this hack exactly in the place in `pytest` you've mentioned and used it in Schemathesis.

**Comment by ericvsmith** [comment]
I don't think there's anything to do here, so I'm going to close this.
