### ISSUE TITLE
Allow test cases to skip rerun

### ISSUE THREAD

**Issue by sunmy2019** [python/cpython#105310]
Currently, there are some tests with intentional leaks or some other tests that do not support rerun.

Adding this decorator will help to resolve this edge case.

inspired by https://github.com/python/cpython/pull/105122

### Linked PRs
* gh-105311

**Comment by Eclips4** [comment]
Interesting. Can be #105273 resolved if we decorate `test_capi/test_misc/TestOptimizerAPI.test_counter_optimizer`?

**Comment by erlend-aasland** [comment]
After thinking about this for some weeks, I'm -1 on the idea. I don't think we should make it easier to skip reruns. Unfortunately, adding machinery to `test.support` will exactly do that; hence my -1.

I'm sorry to have urged you to open this issue in the first place. However, I changed my mind.

**Comment by sunmy2019** [comment]
That's fine. I think we can leave this issue open and close the PR.
