### ISSUE TITLE
locals() in a module or class scope comprehension does not include the iteration var(s) since 3.12b1

### ISSUE THREAD

**Issue by jaraco** [python/cpython#105340]
In Python 3.11, inside a comprehension, `locals()` was bound to the scope of the comprehension:

```
 $ py -3.11 -c "print([locals() for name in 'abc'])"
[{'.0': <str_ascii_iterator object at 0x10472dc30>, 'name': 'c'}, {'.0': <str_ascii_iterator object at 0x10472dc30>, 'name': 'c'}, {'.0': <str_ascii_iterator object at 0x10472dc30>, 'name': 'c'}]
```

But since 3.12b1, `locals()` is `globals()`:

```
 $ py -3.12 -c "print([locals() for name in 'abc'])"
[{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}, {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}, {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}]
 $ py -3.11 -c "print([globals() for name in 'abc'])"
[{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}, {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}, {'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}]
 $ py -3.12 -c "print([locals() is globals() for name in 'abc'])"
[True, True, True]
```

May be related to #105256.

Discovered in [this job](https://github.com/jaraco/jaraco.clipboard/actions/runs/5107203578/jobs/9179898494), triggered by [this code](https://github.com/jaraco/jaraco.clipboard/blob/e81d86fb98c7e0d42fb160960cdd696b07b88952/conftest.py#L5-L9) (which I intend to update not to use `locals()`).

Is this change intentional?

### Linked PRs
* gh-105715
* gh-106470

**Comment by JelleZijlstra** [comment]
Yes, this is intentional and called out in PEP-709. cc @carljm

**Comment by sunmy2019** [comment]
```
>>> def foo():
...     print([locals() is globals() for name in 'abc'])
... 
>>> foo()
[False, False, False]
```

With PEP-709, list comprehensions do not have their own stack. This affects top-level sentences.

**Comment by jaraco** [comment]
Thanks for the reference. I do think the current behavior violates the PEP, which indicates that "locals() includes outer variables", suggesting that locals() would continue to include inner variables, and confirmed by the example where "under this PEP", `x` is found in locals().

In my example above, `name` does not appear in `locals()`, which is a departure from the prior behavior and of the PEP.

**Comment by sunmy2019** [comment]
The correct thing seems to be something like

```py
locals() == {**globals(), "name": ... }
```

**Comment by Yhg1s** [comment]
`name` doesn't appear in locals() at the global level because the generated bytecode uses fast locals for the name even at the global scope:
```
>>> dis.disco(compile("name = 1; [locals() for name in 'abc']", 'f', 'exec'))
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (1)
              4 STORE_NAME               0 (name)
              6 LOAD_CONST               1 ('abc')
              8 GET_ITER
             10 LOAD_FAST_AND_CLEAR      0 (name)
             12 SWAP                     2
             14 BUILD_LIST               0
             16 SWAP                     2
        >>   18 FOR_ITER                 9 (to 40)
             22 STORE_FAST               0 (name)
             24 PUSH_NULL
             26 LOAD_NAME                1 (locals)
             28 CALL                     0
             36 LIST_APPEND              2
             38 JUMP_BACKWARD           11 (to 18)
        >>   40 END_FOR
             42 SWAP                     2
             44 STORE_FAST               0 (name)
             46 POP_TOP
             48 RETURN_CONST             2 (None)

```

This seems to me to be more correct than the alternative (replacing the existing name for the duration of the list comprehension) in particular because globals are visible to outside code. Is there a practical problem with not including the loop variable in the locals() at the global level?

**Comment by JelleZijlstra** [comment]
I do agree that this is a behavior change that wasn't called out in PEP 709 and that we didn't realize would be an issue before. PEP 709 says that locals() now includes the variables from the outer frame. That's true in functions, where locals() now includes both outer and comprehension-local variables, but in module and class scopes, it now includes *only* the outer variables.

```
>>> class F:
...     print([locals() for i in range(1)])
... 
[{'__module__': '__main__', '__qualname__': 'F'}]
>>> [locals() for i in range(1)]
[{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 'F': <class '__main__.F'>}]
>>> def f(arg):
...     return [locals() for i in range(1)]
... 
>>> f(1)
[{'arg': 1, 'i': 0}]
```

And that can indeed break code like the code @jaraco linked above.

To fix it, I wonder if inside the implementation of `locals()` we can detect that we're within a class- or module-scoped comprehension, and if so, add the comprehension locals to the returned dictionary.
