### ISSUE TITLE
arch linux python 2 install test socket fail

### ISSUE THREAD

**Issue by alisacorporation** [python/cpython#105336]
# Bug report

On arch linux trying to install python 2 version, got test_socket test fail error `yay -S python2`
----------------------------------------------------------------------
Ran 54 tests in 1.098s

OK

== Tests result: FAILURE ==

369 tests OK.

**1 test failed:
    test_socket**

25 tests skipped:
    test_aepack test_al test_applesingle test_bsddb test_bsddb185
    test_bsddb3 test_cd test_cl test_dl test_gl test_imageop
    test_imgfile test_kqueue test_linuxaudiodev test_macos
    test_macostools test_msilib test_ossaudiodev test_py3kwarn
    test_scriptpackages test_startfile test_sunaudiodev test_winreg
    test_winsound test_zipfile64
2 skips unexpected on linux2:
    test_bsddb test_bsddb3

Total duration: 8 min 7 sec
Tests result: FAILURE
==> ERROR: A failure occurred in check().
    Aborting...
 -> error making: python2-exit status 4
 -> Failed to install the following packages. Manual intervention is required:
python2 - exit status 4

# Your environment

Linux fbi.gov 6.1.31-2-MANJARO #1 SMP PREEMPT_DYNAMIC Sun Jun  4 12:31:46 UTC 2023 x86_64 GNU/Linux

█████████████████  ████████   root@fbi.gov
█████████████████  ████████   -------------- 
█████████████████  ████████   OS: Manjaro Linux x86_64 
█████████████████  ████████   Host: AB350M-DS3H V2 
████████  ████████  ████████   Kernel: 6.1.31-2-MANJARO 
████████  ████████  ████████   Uptime: 5 hours, 22 mins 
████████  ████████  ████████   Packages: 2096 (pacman) 
████████  ████████  ████████   Shell: zsh 5.9 
████████  ████████  ████████   Resolution: 2560x1440, 1440x900 
████████  ████████  ████████   DE: Xfce 4.18 
████████  ████████  ████████   WM: Xfwm4 
████████  ████████  ████████   WM Theme: Mojave-dark 
████████  ████████  ████████   Theme: Mojave-dark [GTK2/3] 
████████  ████████  ████████   Icons: McMojave-circle-dark [GTK2/3] 
                               Terminal: terminator 
                               CPU: AMD Ryzen 5 1600 (12) @ 3.200GHz 
                               GPU: AMD ATI Radeon RX 470/480/570/570X/580/580X 
                               Memory: 6443MiB / 23955MiB

- CPython versions tested on: 2.7

**Comment by Eclips4** [comment]
Hello!
Sorry, but python 2 is no longer supported.

**Comment by AlexWaygood** [comment]
Indeed

**Comment by iBrabus** [comment]
Yeah, i know, but there is many apps which anyway is using python2 nowadays, i just wanted to know is this issue somekind of pytohn or arch linux, where to find more information about that. Thanks!

**Comment by ericvsmith** [comment]
You might try Stackoverflow or https://discuss.python.org/c/users/7 . We don't accept bugs for 2.7, and this isn't the place to ask general questions.
