### ISSUE TITLE
Keep deprecated functions in Python 3.13: remove this deprecation

### ISSUE THREAD

**Issue by vstinner** [python/cpython#105373]
There are multiple Python functions marked as "deprecated", usually only in the documentation, or sometimes in comments, whereas the feature is there for a long time and there is no *need* to remove them, or the rationale changed.

For example, the ``array.array('u')`` format was deprecated since it used the ``Py_UNICODE`` C type (which is deprecated), but the code was updated to use the ``wchar_t`` C type which is fine and not depreated.

Another example is passing *NULL* as *value* to ``PyObject_SetAttr(obj, name, value)`` to delete an object attribute is deprecated... but this feature exists since the birth of Python. I don't think that it's really useful to deprecate this behavior: it's fine to keep it. The ``PyObject_DelAttr()`` function is just implemented as a macro passing *NULL*:

```c
#define  PyObject_DelAttr(O, A) PyObject_SetAttr((O), (A), NULL)
```

### Linked PRs
* gh-105374
* gh-105394
* gh-105395
* gh-106537
* gh-106538
* gh-106540
* gh-106675

**Comment by hugovk** [comment]
See also https://github.com/python/cpython/issues/80480 which links to a merged PR to add `array.array('w')` and with an open PR to deprecate `array.array('u')`, cc @methane.

**Comment by arhadthedev** [comment]
> For example, the `array.array('u')` format was deprecated since it used the `Py_UNICODE` C type (which is deprecated), but the code was updated to use the `wchar_t` C type which is fine and not depreated.

- gh-95760 was merged few hours ago. Is the cited point relevant then?

**Comment by methane** [comment]
See https://github.com/python/cpython/issues/80480#issuecomment-1541327809

There are few situations where platform- or compiler-dependent `wchar_t` arrays are useful.
Many users use `array('u')` as a mutable Unicode buffer, and `array('w')` is recommended for that use.

**Comment by vstinner** [comment]
> Another example is passing NULL as value to PyObject_SetAttr(obj, name, value) to delete an object attribute is deprecated... but this feature exists since the birth of Python. I don't think that it's really useful to deprecate this behavior: it's fine to keep it. (...)

I created issue #106572: "Deprecate PyObject_SetAttr(obj, name, NULL): PyObject_DelAttr(obj, name) must be used instead".

**Comment by vstinner** [comment]
Well, I did the cleanup that I wanted to do about pending incompatible changes. I just proposed a new PR #106675 to elaborate the "Pending Removal" documentation.

I propose to open new issues if we want to adjust other pending incompatible changes: unschedule them, schedule them, or schedule them earlier.

**Comment by j4hangir** [comment]
Would be nice to have .warn() kept.

**Comment by vstinner** [comment]
> Would be nice to have .warn() kept.

The removal of logging.Logger.warn() is not planned.

**Comment by j4hangir** [comment]
> > Would be nice to have .warn() kept.
> 
> The removal of logging.Logger.warn() is not planned.

I assumed since it's deprecated it'll be eventually removed, in that case I'd agree that the deprecation is also not needed on it.

**Comment by vstinner** [comment]
Since this issue is closed, I suggest you opening a new issue if you have a strong opinion on warn() deprecation.
