### ISSUE TITLE
Incompatible function pointer types assigning to 'Function *' at readline module

### ISSUE THREAD

**Issue by corona10** [python/cpython#105323]
At macOS 12.5.1 with Apple clang version 14.0.0 (clang-1400.0.29.202)

````

./Modules/readline.c:1252:21: warning: incompatible function pointer types assigning to 'Function *' (aka 'int (*)(const char *, int)') from 'int (void)' [-Wincompatible-function-pointer-types]
    rl_startup_hook = on_startup_hook;
                    ^ ~~~~~~~~~~~~~~~
./Modules/readline.c:1254:23: warning: incompatible function pointer types assigning to 'Function *' (aka 'int (*)(const char *, int)') from 'int (void)' [-Wincompatible-function-pointer-types]
    rl_pre_input_hook = on_pre_input_hook;
````

### Linked PRs
* gh-106284
* gh-108633
* gh-108665
* gh-112513

**Comment by corona10** [comment]
Header from apple Xcode.

````c

/* typedefs */
typedef int	  Function(const char *, int);
typedef void	  VFunction(void);
typedef void	  VCPFunction(char *);
typedef char	 *CPFunction(const char *, int);
typedef char	**CPPFunction(const char *, int, int);
typedef char     *rl_compentry_func_t(const char *, int);
typedef int	  rl_command_func_t(int, int);
````

**Comment by erlend-aasland** [comment]
@corona10, did you get any further with this? I'm getting annoyed at these warnings, myself :)

**Comment by corona10** [comment]
@erlend-aasland I will try to solve this issue at this weekend ;)

**Comment by corona10** [comment]
@ned-deily cc @erlend-aasland 

Hi Ned,
AFAIK, Apple uses a different readline implementation from GNU and I checked API signatures were the same across versions.
https://github.com/phracker/MacOSX-SDKs
So we can easily solve this issue by using a conditional compile approach.

But if we have to care about linking with the GNU version on the macOS, the problem will be more difficult.
So we need to know that we should care or not.
https://stackoverflow.com/questions/7214374/how-do-i-link-against-the-gnu-readline-library-rather-than-libedit-in-macosx

**Comment by erlend-aasland** [comment]
> But if we have to care about linking with the GNU version on the macOS, the problem will be more difficult.

You can use the preprocessor define `WITH_EDITLINE` to check if we're compiling with editline or readline.

**Comment by corona10** [comment]
> You can use the preprocessor define WITH_EDITLINE to check if we're compiling with editline or readline.

Wow, That's good! I will prepare the patch by this weekend :)

**Comment by erlend-aasland** [comment]
If you grep for `READLINE` in `configure.ac`, you'll find that the dependency resolver for `readline` is more complex than that for other extension modules with third party dependencies. See also the `WITH_EDITLINE` conditional at the top of `Modules/readline.c` :)

**Comment by erlend-aasland** [comment]
See discussion on #108588

**Comment by corona10** [comment]
For reference what I investigated

| Backend 	| configure 	| header 	| Real verison 	| Macro Version (RL_READLINE_VERSION) 	| Install 	| Source 	| rl_startup_hook 	| rl_pre_input_hook 	| User 	|
|---	|---	|---	|---	|---	|---	|---	|---	|---	|---	|
| readline 	| --with-readline=readline 	| readline/readline.h 	| 8.2.1 	| 0x0802 	| brew / MacPorts 	| https://ftp.gnu.org/gnu/readline/ 	| typedef int rl_hook_func_t (void); 	| typedef int rl_hook_func_t (void); 	| Linux/BSD/ macOS/... 	|
| libedit w/readline wrapper 	| --with-readline=editline 	| editline/readline.h 	| 20221030-3.1 	| 0x0402 	| brew / MacPorts 	| https://www.thrysoee.dk/editline/ 	| rl_hook_func_t(void); 	| rl_hook_func_t(void); 	| Linux/BSD/ macOS/... 	|
| libedit 	| --with-readline=editline 	| editline/editline.h 	| 1.17.1 	| n/a 	| https://github.com/troglobit/editline 	| https://github.com/troglobit/editline 	| n/a 	| n/a 	| Linux/BSD/ macOS/... 	|
| Apple editline 	| --with-readline=apple 	| readline/readline.h editline/readline.h 	| libedit-57 	| 0x0402 	| XCode SDK 	| https://github.com/apple-oss-distributions/libedit/ 	| typedef int 	  Function(const char *, int); 	| typedef int 	  Function(const char *, int); 	| macOS 	|

**Comment by erlend-aasland** [comment]
BTW, we have some really outdated readline checks in configure.ac. Any check for functionality introduced in readline versions before 4.2 could probably be tossed out.

**Comment by gaogaotiantian** [comment]
I think this issue impacts more than than MacOS.

I tried to link libedit on Ubuntu and it has the same issue.

```
sudo apt install libedit-dev
./configure --with-readline=editline
make
```

We only use two headers, `<editline/readline.h>` if `with-readline==editline` and `<readline/readline.h>` if `with-readline==readline` (default). I think `<editline/readline.h>` always uses the "old" declaration with `typedef int Function(const char *, int);`.

I was wondering if we need `WITH_APPLE_EDITLINE`. `_RL_FUNCTION_TYPEDEF` seems to be the macro to indicate that the rl_* functions have the new style declarations, and the corresponding "old style" is the one with `Function`.

I think we should do something like 

```c
static int
#if defined(_RL_FUNCTION_TYPEDEF)
on_startup_hook(void)
#else
on_startup_hook(const char *Py_UNUSED(text), int Py_UNUSED(state))
#endif
```

**Comment by corona10** [comment]
> I was wondering if we need WITH_APPLE_EDITLINE. _RL_FUNCTION_TYPEDEF seems to be the macro to indicate that the rl_* functions have the new style declarations, and the corresponding "old style" is the one with Function.

Okay if this issue is happening outside of macOS too. We can use your suggestion for this issue.
The patch itself tried to reduce impact to outside of macOS.

**Comment by corona10** [comment]
@gaogaotiantian Do you want to submit the patch?

**Comment by gaogaotiantian** [comment]
Yeah I'll do it. As `WITH_APPLE_EDITLINE` is only used for this, should I just basically revert all the changes in #108665? The docs change to ``--with-readline`` should be kept I presume. Anything else?

**Comment by corona10** [comment]
> Yeah I'll do it. As WITH_APPLE_EDITLINE is only used for this, should I just basically revert all the changes in https://github.com/python/cpython/pull/108665?

Just remove WITH_APPLE_EDITLINE please

**Comment by corona10** [comment]
Two things are needed.
1. Remove `WITH_APPLE_EDITLINE` from configure.ac and regendeate configure file.
2. Replace `#elif defined(WITH_APPLE_EDITLINE)` to `#else`

**Comment by gaogaotiantian** [comment]
> Two things are needed.
> 
> 1. Remove `WITH_APPLE_EDITLINE` from configure.ac and regendeate configure file.
> 2. Replace `#elif defined(WITH_APPLE_EDITLINE)` to `#else`

Done in #112513

**Comment by erlend-aasland** [comment]
Can this be closed, @corona10?

**Comment by corona10** [comment]
> Can this be closed, @corona10?

Yeah sure!
