### ISSUE TITLE
asyncio.sleep(float('nan')) does not raise ValueError

### ISSUE THREAD

**Issue by jakkdl** [python/cpython#105331]
# Bug report
`time.sleep(float('nan'))` raises `ValueError`, but `asyncio.sleep(float('nan'))` is valid and sleeps for 0. This seems bad, and `asyncio.sleep` should probably also raise `ValueError`.

```python
import asyncio
import time

try:
    time.sleep(float('nan'))
except ValueError:
    print("time.sleep raised ValueError")

async def foo() -> None:
    await asyncio.sleep(float('nan'))
    print("asyncio.sleep does not raise any error")

asyncio.run(foo())
```

```bash
$ python foo.py
time.sleep raised ValueError
asyncio.sleep does not raise any error
```

`time.sleep` and `asyncio.sleep` do differ in behaviour when it comes to negative numbers and changing that behaviour was considered a breaking change without strong reason: https://github.com/python/cpython/issues/83879
`nan` feels like it should *very* rare to be passed intentionally, but the potential gain might also be small enough that this isn't worth fixing.

Related: https://github.com/python-trio/trio/issues/2493

# Your environment

- CPython versions tested on: 3.8 to 3.11 
- Operating system and architecture: `Linux 6.3.4-arch1-1`

### Linked PRs
* gh-105501
* gh-105513
* gh-105641

**Comment by sobolevn** [comment]
It is also different for negative values.

For example:

```python
>>> import asyncio
>>> async def a():
...     await asyncio.sleep(-1)
... 
>>> asyncio.run(a())
```

and

```
>>> import time
>>> time.sleep(-1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: sleep length must be non-negative
```

**Comment by jakkdl** [comment]
> It is also different for negative values.

Yes, I wrote

> `time.sleep` and `asyncio.sleep` do differ in behaviour when it comes to negative numbers and changing that behaviour was considered a breaking change without strong reason: https://github.com/python/cpython/issues/83879

**Comment by kumaraditya303** [comment]
I don't think we should change it at this point, I can accept a docs improvement for this but I'm -1 on changing the behavior.

**Comment by Zac-HD** [comment]
fwiw I'd expect it to follow whatever `time.sleep()` does with weird arguments, and think that there's a pretty strong argument in favor of consistency.

**Comment by gvanrossum** [comment]
Hm, I expect at this point there is probably plenty of working code out there that passes a negative delay to `asyncio.sleep` (perhaps the result of trying to sleep until some target time that's slightly in the past).

I don't see how NaN could be the result of such a computation, so I agree NaN is a "weird" argument (and leads to undefined behavior).

So I think I can only approve of the NaN check.
