### ISSUE TITLE
Incorrect error handling for APIs that can raise exceptions

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#105375]
For example, in the collation callback two `str` objects (`string1` and `string2`) are created using `PyUnicode_FromStringAndSize`. Error handling should happen directly after each call to `PyUnicode_FromStringAndSize`:

https://github.com/python/cpython/blob/0cb6b9b0db5df6b3f902e86eb3d4a1e504afb851/Modules/_sqlite/connection.c#L1870-L1875

Other cases where error handling is not done immediately after the API has been used:

- [x] gh-105491
- [x] gh-105494
- [x] gh-105585
- [x] gh-105590
- [x] gh-105591
- [x] gh-105592
- [x] gh-105593
- [x] gh-105594
- [x] gh-105667
- [x] gh-105475 
- [x] gh-105599
- [x] gh-105586
- [x] gh-105604
- [x] gh-105606
- [x] gh-105605
- [x] gh-105608
- [x] gh-105610
- [x] gh-105611

I might have missed some; I did not do a complete audit yet.

### Linked PRs
* gh-105412
* gh-105440
* gh-105441
* gh-105475
* gh-105491
* gh-105494
* gh-105581
* gh-105582
* gh-105583
* gh-105584
* gh-105585
* gh-105586
* gh-105590
* gh-105591
* gh-105592
* gh-105593
* gh-105594
* gh-105596
* gh-105597
* gh-105598
* gh-105599
* gh-105600
* gh-105601
* gh-105604
* gh-105605
* gh-105608
* gh-105610
* gh-105611
* gh-105612
* gh-105613
* gh-105615
* gh-105642
* gh-105643
* gh-105644
* gh-105645
* gh-105646
* gh-105647
* gh-105648
* gh-105649
* gh-105650
* gh-105651
* gh-105659
* gh-105660
* gh-105661
* gh-105662
* gh-105663
* gh-105664
* gh-105665
* gh-105666
* gh-105667
* gh-105668
* gh-105669
* gh-105686
* gh-105710
* gh-105711
* gh-105720
* gh-105721

**Comment by vstinner** [comment]
There were many "init" functions of C extensions calling all C functions without checking for exceptions, and only checking for exceptions once at the end. Most of them have been fixed with better error checking, but not all of them yet.

**Comment by vstinner** [comment]
See issue #105374 about C API being error prone: when it's unclear if passing NULL was done on purpose or by mistake

**Comment by vstinner** [comment]
See also https://github.com/capi-workgroup/problems/issues/47

**Comment by erlend-aasland** [comment]
FYI, @sobolevn: I'm working my way downwards.

**Comment by sobolevn** [comment]
Wow, it was a productive night! Great work!

**Comment by serhiy-storchaka** [comment]
Thank you, @erlend-aasland. These are minor errors, but it is nice to have the code cleaner.

Although you introduced new bugs in #105475 and #105611 related to clearing non-initialized references.

**Comment by sobolevn** [comment]
Refs https://github.com/python/cpython/issues/105673
