### ISSUE TITLE
PEP 695 is not tested to be `pickle`able

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#105433]
(or at least I cannot find these tests)

I think that testing the pickle result of functions, classes, and type aliases created with the new syntax is very important.

I propose to add these tests, PR is in the works.

### Linked PRs
* gh-105443
* gh-105845

**Comment by sunmy2019** [comment]
Sounds reasonable.

**Comment by JelleZijlstra** [comment]
Thanks Nikita!
