### ISSUE TITLE
`typing._Immutable` is not used anymore

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#105430]
`class _Immutable` https://github.com/python/cpython/blob/27c68a6d8f20090310450862c2c299bb7ba3c160/Lib/typing.py#L422-L431 after https://github.com/python/cpython/pull/103764/files#diff-ddb987fca5f5df0c9a2f5521ed687919d70bb3d64eaeb8021f98833a2a716887L969 is not used.

```
» ag _Immutable
Lib/typing.py
419:class _Immutable:
                  
```

Shall I remove it? I think that we don't provide any promises about `typing.py` internals.

### Linked PRs
* gh-105434
* gh-105451

**Comment by AlexWaygood** [comment]
> Shall I remove it?

Sounds good to me! This is undocumented, untested, not included in `__all__`, and has a name starting with a leading underscore. I don't think we can be any more explicit about the fact that it was an internal implementation detail 😆
