### ISSUE TITLE
Remove unused imports (June 2023)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#105407]
Time to time, I run ``pyflakes`` to find unused imports in the Python code base. That's the issue for June 2023 :-)

### Linked PRs
* gh-105408
* gh-105409
* gh-105410
* gh-105411
* gh-105554

**Comment by CAM-Gerlach** [comment]
Seems like all the linked PRs are merged?

**Comment by vstinner** [comment]
I close the issue. I hesitated to abuse the issue to fix other warnings found by pyflakes, but I will create other issues instead. Example: #105751 for test_ctypes.
