### ISSUE TITLE
Improve parsing speed of long strings by ipaddress.IPv4Address()

### ISSUE THREAD

**Issue by elliotwutingfeng** [python/cpython#105490]
**ipaddress.IPv4Address()** parses long strings (>15 characters) slowly, such as `"1" * int(1e2)` and `".".join("255" for _ in range(int(1e2)))`.

Since the format of IPv4 address recognized by **ipaddress.IPv4Address()** has a maximum possible length of 15 characters, we can optimize the **_ip_int_from_string()** function in class **_BaseV4** to reject the input early if it is longer than 15 characters, before running **str.split(".")** which is time expensive for long strings.

i.e.

```python
        if len(ip_str) > 15:
            raise AddressValueError('Address cannot be more than 15 characters long')
```

### Results

The proposed change reduces execution time for parsing of excessively long strings (>15 characters) to half that of valid IPv4 strings.

#### Test Environment

- CPython version tested on: 3.13.0a0, git commit 9d35a71a76cb033598ce136ea655d9e452fe3af0
- Operating system and architecture: Manjaro Linux x64, AMD Ryzen 7 5800x

```python
from timeit import timeit
from ipaddress import IPv4Address

def f(ip_str):
    try:
        IPv4Address(ip_str)
    except:
        pass

for ip_str in ["255.255.255.255", "255.255.255.2551", "1" * int(1e2), ".".join("255" for _ in range(int(1e2)))]:
    print(timeit("f(ip_str)","from __main__ import f, ip_str",number=1000_000), "seconds")
```

#### Before

```text
6.861410270998022 seconds
12.029028392000328 seconds
4.979545458998473 seconds
20.865375504999975 seconds
```

#### After

```text
7.130554482002481 seconds
3.2689362650016847 seconds
3.286588627001038 seconds
3.3457458359989687 seconds
```

### Caveats

This change results in about **4%** slower execution time for valid IPv4 addresses, and the error messages for the following invalid inputs will be different (since they are all >15 characterss long).

```python
"1000000000000000"
"0x0a.0x0a.0x0a.0x0a"
"0xa.0x0a.0x0a.0x0a"
"0000.000.000.000"
"12345.67899.-54321.-98765"
```

### Linked PRs
* gh-105492

**Comment by ericvsmith** [comment]
Is parsing too-long strings as addresses really a common operation? I'd normally be opposed to the small additional code complexity, but I'm especially opposed so since it slows down the "happy path".

What's the use case for wanting this?

**Comment by gaogaotiantian** [comment]
I think this is a biased benchmark. Improving the performance of rare cases is not worthy if it decreases the performance for normal path even for a little bit. The average cost probably will increase after the change.

**Comment by AlexWaygood** [comment]
I agree with @ericvsmith. Is the slow parsing of long strings by `ipaddress` actually a bottleneck for your application? Or is this just a theoretical issue?

Even if it is somehow a bottleneck for you, I feel like you could work around that by just doing a length check before passing the string to IPv4Address.
