### ISSUE TITLE
Documentation for 3.11.4 release missing on the "FTP"

### ISSUE THREAD

**Issue by mgorny** [python/cpython#105450]
# Documentation

The documentation for the latest 3.11.4 release seem to be missing on https://www.python.org/ftp/python/doc/.

For some reason, the directories for other new releases aren't present on the listing page but direct URIs work. However, https://www.python.org/ftp/python/doc/3.11.4/ yields 404.

**Comment by ned-deily** [comment]
> The 3.11 docs should be built on a daily cron.

That's true for the up-to-date docs but the issue here has to do with the archived set of docs produced for each release. Those are manufactured and published as part of the release process and I'm not sure why they are missing. I've pinged @pablogsal.

**Comment by ned-deily** [comment]
> # Documentation
> The documentation for the latest 3.11.4 release seem to be missing on https://www.python.org/ftp/python/doc/.
> 
> For some reason, the directories for other new releases aren't present on the listing page but direct URIs work.

The directory page appears to be up-to-date now (other than the missing 3.11.4 directory); the directory listing was probably just a stale CDN cache issue.

**Comment by pablogsal** [comment]
Not sure what happened with the docs, but I have uploaded them again and this is fixed now:

https://www.python.org/ftp/python/doc/3.11.4/
