### ISSUE TITLE
3.11: "Check if generated files are up to date" is failing due to autoconf version

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#105455]
On all 3.11 PRs that touch non-docs files (e.g. #105417), the `Check if generated files are up to date` check is currently failing on the check `grep "Generated by GNU Autoconf 2.69" configure`.

This is because d2340ef25721b6a72d45d4508c672c4be38c67d3, which created 3.11.4, updated `configure` to be generated by Autoconf 2.71. @pablogsal why was this done? Should we update the build.yml file to check for 2.71 instead of 2.69?

### Linked PRs
* gh-105467
* gh-105469

**Comment by ned-deily** [comment]
This is probably a side effect of the most recent PRs for #89886 which probably updated the VM used to do autoconf operations. @erlend-aasland

**Comment by erlend-aasland** [comment]
> This is probably a side effect of the most recent PRs for #89886 which probably updated the container used to do autoconf operations. @erlend-aasland 

We did not update the container. We just updated the CI and make to use the _271_ tagged container. The release tools should use the correct tag depending on which release it is building.

**Comment by erlend-aasland** [comment]
Either we reset `configure` using GNU Autoconf 2.69, or we backport the Autoconf 2.71 bump to 3.11. I guess the former is preferred, but the latter creates less churn. I can create PRs for both.

**Comment by erlend-aasland** [comment]
Resolved with:

- gh-105467
