### ISSUE TITLE
Document that enums with unhashable members are created non-performantly

### ISSUE THREAD

**Issue by mzhu22** [python/cpython#105535]
# Documentation

#28907 fixes enum creation taking quadratic time relative to the number of members, but _only_ for members whose values are hashable. If not fixed, ideally this would be documented somewhere as it could potentially be a big performance trap

### Linked PRs
* gh-107119
* gh-116511
* gh-116512

**Comment by nicky-eng** [comment]
I will try to create a pull request for this issue. I think it will be done by the end of the day.

**Comment by ethanfurman** [comment]
@mzhu22: Out of curiosity, do you have an actual use-case that uses many unhashable values?

**Comment by mzhu22** [comment]
@ethanfurman we were dynamically generating Enums from user data. Originally the enum member values were strings, but we switched to dataclasses to include additional metadata. For some corner cases where enums had a lot of values, this resulted in a dramatic performance hit, until we made the values immutable

**Comment by ethanfurman** [comment]
Definitely a good reason for the warning.
