### ISSUE TITLE
Emit resource warning if sqlite3 fails to close the database

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#105539]
_See https://github.com/python/cpython/issues/103837#issuecomment-1541808307 and https://github.com/python/cpython/issues/103837#issuecomment-1543936079_:

EAA:
> I still think we should consider changing the underlying API so we can emit a resource warning if close failed.

VS:
> IMO sqlite3 should be modified to emit a ResourceWarning.
>
> Currently, no ResourceWarning is emitted when a connection is not closed explicitly:

### Linked PRs
* gh-108015
* gh-108017
* gh-108360
* gh-108565

**Comment by vstinner** [comment]
What is the consequences if a database is not closed explicitly and fails to be closed at Python exit? Is there a risk of losing data?

**Comment by erlend-aasland** [comment]
> What is the consequences if a database is not closed explicitly and fails to be closed at Python exit? Is there a risk of losing data?

If `sqlite3_close()` or `sqlite3_close_v2()` fails, there is of course a risk of losing data. However, we do a pretty good job at cleaning up the connection and its debris (cursors, statements, registered callbacks, etc.), so that risk is almost non-existent :)

**Comment by vstinner** [comment]
By "fail to be closed", I was thinking about a database connection involved in a reference cycle which is impossible to break, and so close() is *never* called and the object is never destroyed.

**Comment by erlend-aasland** [comment]
> By "fail to be closed", I was thinking about a database connection involved in a reference cycle which is impossible to break, and so close() is *never* called and the object is never destroyed.

If the connection object is never destroyed (dealloc or finalize are never called), there is no way to detect that in the extension module that I know about. The proposed change involves both the finalizer and the dealloc callbacks, so I'm relying on them actually being called at some point.

**Comment by vstinner** [comment]
Congrats :-) IMO it's a nice enhancement.

**Comment by erlend-aasland** [comment]
Thanks for bringing the idea up in the first place, Victor! :)

**Comment by erlend-aasland** [comment]
Apparently, I did not cover all cases in #108017; the following now emit resource warnings:

     ./python.exe -m test -R : test_sqlite3 -m ClosedCurTests
