### ISSUE TITLE
Deprecate unusual ways of creating empty TypedDicts

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#105570]
# Feature or enhancement

I propose that we deprecate the following two ways of creating empty `TypedDict`s:

```py
from typing import TypedDict

T = TypedDict("T")
T2 = TypedDict("T2", None)
```

# Pitch

Users currently have four distinct options if they want to create an empty `TypedDict` with no fields:

```py
T = TypedDict("T")
T2 = TypedDict("T2", None)
T3 = TypedDict("T3", {})
class T4(TypedDict): ...
```

Of these four options, only `T3` and `T4` are supported by type checkers. `typing.TypedDict` has been around for a while now, so if `T1` and `T2` are still unsupported by type checkers, they probably never will be supported.

Deprecating, and eventually removing, the first two ways of constructing empty TypedDicts will allow us to simplify the code at runtime. It will also be less confusing for users. Every way in which the runtime and type checkers differ in behaviour is a potential point of confusion for users; in general, we should work to keep these points of difference to a minimum.

I also don't think these methods of constructing empty TypedDicts are particularly common.

# Previous discussion

For very similar reasons, we previously deprecated and removed the keyword-argument syntax for creating TypedDicts. This was deprecated in 3.11, and removed in 3.13:

- https://github.com/python/cpython/issues/90224
- https://github.com/python/cpython/issues/104786

In retrospect, we should really have deprecated these ways of creating empty TypedDicts at the same time. But there's no way of changing that now.

### Linked PRs
* gh-105780

**Comment by sobolevn** [comment]
I think that we should keep `T4`, because this way people might:
1. Create some base metadata object and use it for inheritance later on
2. Create literal empty dict: `class EmptyDict(TypedDict): ...`, which is a valid use-case

Others are good candidates to be deprecated, I agree.

**Comment by AlexWaygood** [comment]
> I think that we should keep `T4`

Yes, I agree. I'm proposing we deprecate T1 and T2, but keep T3 and T4.
