### ISSUE TITLE
re.search cannot find negative sign

### ISSUE THREAD

**Issue by impodog** [python/cpython#105625]
# Bug report

The regular expression I used is working wrongly.
I've made this test file, and found out that the negative sign cannot be searched.

```py
import re

pattern = r"\b(-?\d+)\b"
content = "The temperature is -3 degrees Celsius."

match = re.search(pattern, content)
if match:
    number = match.group(1)
    print("Found:", number)
else:
    print("Not found.")
```

The result is expected to be "Found: -3", but it turns out to be "Found: 3".
I believe that something is wrong with the "-" in regular expressions.

# Your environment

- CPython versions tested on: python-3.11.4-amd64
- Operating system and architecture: Win11 64-bit operating system, x64-based processor

**Comment by terryjreedy** [comment]
This is not a bug.  `\b` matches boundaries between word and non-word chars.  In this case, the 2 `\b`s match on both sides of `3`.  See the [re doc](https://docs.python.org/3/library/re.html#regular-expression-syntax), backslash sequences.

We suggest that people ask about problems with well testes modules like re on https://discuss.python.org/c/users/7 first.

**Comment by impodog** [comment]
Alright, I've figured it out by removing one of the blanks. Thanks very much anyway.
