### ISSUE TITLE
3.12: tarfile `filter` DeprecationWarning should only fire if it would matter

### ISSUE THREAD

**Issue by asottile** [python/cpython#105637]
I'm testing out the 3.12 beta and I find the warning from [PEP 706](https://peps.python.org/pep-0706/) to be unactionable for most uses

I'm ok accepting the default, and I'm ok accepting the new default in 3.14 -- but my assertion is that most people don't care about explicitly setting this and that the 3.14 default will be ok.  the DeprecationWarning as it is right now will generate a lot of (imo unnecessary) noise about the new feature

in my case I'm extracting tar files that I both completely trust and also would be extracted identically in the `filter='data'` case (which will be the default in 3.14).  I really would only care about the DeprecationWarning if I were doing exceptional things or dealing with exceptional tar files

ideally it should only fire if it would alter the output or error -- otherwise it is just noise

**Comment by zware** [comment]
IIUC, the solution is for you to set `TarFile.extraction_filter` as you like.  The point of the warning is to *be* noisy, to force you the user into acknowledging the danger of the default.

**Comment by asottile** [comment]
warnings for the sake of noise seems a bad stance to take.  it's why people ignore them and don't fix things.  warnings should be actionable

**Comment by zware** [comment]
These warnings are actionable: set `TarFile.extraction_filter`.

**Comment by asottile** [comment]
they aren't -- the default for 3.14 works fine for me and does not change behaviour.  if I do nothing the warning resolves itself.  in the interim it is forcing me to make a change for no benefit other than to silence a warning

**Comment by encukou** [comment]
I would like to do it that way, but I didn't find a reliable, cross-platform way to check whether the end result would be different without a filter.
Granted, this is mostly for changes are for details that probably wouldn't matter to you, like user and mode. But where would you draw the line?

**Comment by encukou** [comment]
With apologies for causing unnecessary alarm for well-written code, I will close this.

**Comment by asottile** [comment]
that's really unfortunate.  I hope at some point that the improved cpython deprecation policy will prevent noise like this but for now I'll just continue to get bombarded by pointless PRs and Linux distribution packagers that don't know any better
