### ISSUE TITLE
Remove unsupported flags SND_PURGE and SND_NOWAIT from winsound

### ISSUE THREAD

**Issue by DBJim** [python/cpython#105677]
The `SND_PURGE` and `SND_NOWAIT` flags defined in winsound are unsupported for many years and ignored by modern Windows.

I propose to remove them in 3.13.

Reference:
https://learn.microsoft.com/en-us/previous-versions//dd743680(v=vs.85)

### Linked PRs
* gh-105681

**Comment by zooba** [comment]
Unfortunately, they're not marked as deprecated with a planned removal in our docs. The first step should be a deprecation warning if someone passes them into our function.

But really, is this an important change to make? They don't cost anything, and they live inside their own extension module so aren't even adding memory pressure for most users.

I'd rather not remove things that could break users when it's not going to add any value. (For reference, it took me [one search](https://github.com/search?q=snd_nowait+language%3APython&ref=opensearch&type=code&l=Python) to find a number of code samples that currently work but will raise `AttributeError` after this change, so we need to be able to explain to them why this is a _good_ thing.)

**Comment by DBJim** [comment]
Thanks for your feedback @zooba 

I think there is value in cleaning up, but I'll be guided by yourself and the community whether it's worth it to remove these with a deprecation period.

**Comment by DBJim** [comment]
Thanks, good idea. I will close the issue and I'll keep an eye on the proposed soft deprecation. Appreciate the feedback.
