### ISSUE TITLE
python `hashlib` has an unstable result regarding large file on windows

### ISSUE THREAD

**Issue by zh-impact** [python/cpython#105657]
# Bug report

The cause is whisper frequently remind me to redownloading the model.

But when I checked the hash with system util `Get-FileHash` and `hashlib` (the same way with whisper does), I found the `hashlib` had an unstable result on large file no matter is `sha256`, `sha384`, or `md5` method.

<img width="913" alt="image" src="https://github.com/python/cpython/assets/4338052/a4ce7143-6321-403a-b809-d7a404f2e8d1">

```python
import hashlib
// medium.pt is from openai/whisper https://openaipublic.azureedge.net/main/whisper/models/345ae4da62f9b3d59415adc60127b97c714f32e89e936602e85993674d08dcb1/medium.pt
with open('medium.pt', 'rb') as f:
    data = f.read()
    hash = hashlib.sha256(data).hexdigest()
    print(hash)
```

Run in PowerShell
```PowerShell
for ($i=1; $i -le 10; $i++) { python .\test.py }
```

Test file: model medium.pt from [openai/whisper](https://github.com/openai/whisper) [download link](https://openaipublic.azureedge.net/main/whisper/models/345ae4da62f9b3d59415adc60127b97c714f32e89e936602e85993674d08dcb1/medium.pt)
file size: 1.42 GB, 1528008539 Bytes

# Your environment

- CPython versions tested on: 3.10.10, also tested on 3.10.11, plus 3.11.4
- Operating system and architecture: Windows 11 22H2 x64

3.11.4 looks more stable, but still have 2/10 errors:
<img width="857" alt="image" src="https://github.com/python/cpython/assets/4338052/0662c4c5-7c93-4c8f-a280-a5decb344615">

**Comment by arhadthedev** [comment]
@gpshead (as a hashlib [module expert](https://devguide.python.org/core-developers/experts/#stdlib))

**Comment by pochmann** [comment]
How large is the file? (Exactly, in bytes)

How do you know it's `hashlib` that's unstable, not the file reading?

What outputs do you get with this? (Run that ten times as before)

```python
import hashlib
with open('medium.pt', 'rb') as f:
    data = f.read()
    print(len(data), list(data[:10]), list(data[-10:]))
    for _ in range(3):
        hash = hashlib.sha256(data).hexdigest()
        print(hash)
```

**Comment by yola-0316** [comment]
@pochmann Thanks for suggestion, the previous test file is 1.42 GB, 1528008539 in Bytes [medium.pt](https://openaipublic.azureedge.net/main/whisper/models/345ae4da62f9b3d59415adc60127b97c714f32e89e936602e85993674d08dcb1/medium.pt)

And I also tested on a smaller file, it reappear the issue [small.pt](https://openaipublic.azureedge.net/main/whisper/models/9ecf779972d90ba49c06d968637d720dd632c55bbf19d441fb42bf17a411e794/small.pt). It size is 461 MB, 483617219 in Bytes

I have update the code, and find the changes is `sum(data)`.
<img width="926" alt="image" src="https://github.com/python/cpython/assets/4338052/f7103435-0024-411f-9e7d-0411fedf7a1a">

**Test results:** this time test on python 3.10.11
1. "medium.pt", the error rate is 3/10, also noticed the same `sum(data)` (i.e. 165803148631) had a different result
<img width="903" alt="image" src="https://github.com/python/cpython/assets/4338052/fa72d967-4b03-4c47-b7a2-dc862ccb5bc0">

3. "small.pt", the error rate is 1/10
<img width="926" alt="image" src="https://github.com/python/cpython/assets/4338052/f7103435-0024-411f-9e7d-0411fedf7a1a">

**Comment by sunmy2019** [comment]
`sum(data)` is different, which means `data` are different in those cases.

**Comment by gpshead** [comment]
This appears to be flaky computer hardware.

**Comment by sunmy2019** [comment]
source code of `Get-FileHash` is here
https://github.com/PowerShell/PowerShell/blob/master/src/Microsoft.PowerShell.Commands.Utility/commands/utility/GetHash.cs

It is a powershell builtin. It wraps calls to https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.sha256.hashdata?view=net-7.0#system-security-cryptography-sha256-hashdata(system-io-stream).

**Comment by sunmy2019** [comment]
https://github.com/dotnet/runtime/blob/202ccdb59afedcf2d7e86b3ba10a2b9a703c71c9/src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHashProvider.cs#L112

It indeed reads only 4096 bytes one time.

**Comment by yola-0316** [comment]
@pochmann Thanks! After change `read()` behavior to slice reading, the output result are stable.
> ```python
> import hashlib
> with open('medium.pt', 'rb') as f:
>     hasher = hashlib.sha256()
>     while data := f.read(2**12):
>         hasher.update(data)
>     print(hasher.hexdigest())
> ```

Now, I just copied the file and compare the contents, some bytes changed. 😢 
I think I need to check if it is a windows bug or my RAM had an error.
<img width="532" alt="image" src="https://github.com/python/cpython/assets/4338052/9bc65596-6657-4b52-91be-295a58f6c278">

Thanks anyway again!
