### ISSUE TITLE
`webbrowsers.Konqueror` is broken

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#105745]
`webbrowsers.Konqueror` is broken after https://github.com/python/cpython/pull/102872#issuecomment-1589958849

It looks like `def open` was not removed from `Grail` and was moved to `Konqueror`.

Originially discovered by @vstinner in https://github.com/python/cpython/pull/102872#issuecomment-1589958849

### Linked PRs
* gh-105746
* gh-105777

**Comment by vstinner** [comment]
> It looks like def open was not removed from Grail and was moved to Konqueror.

Ooops :-(
