### ISSUE TITLE
Too many `elif`s cause `MemoryError`

### ISSUE THREAD

**Issue by pbzweihander** [python/cpython#105771]
# Bug report

Save the above code as `main.py`:

```python
code = """a = 1
if a == 0:
    print(0)
"""
for i in range(1, 10000):
    code += f"""elif a == {i}:
    print({i})
"""

print(code)
```

... and run `python main.py | python` causes:

```
$ python main.py | python
MemoryError
Traceback (most recent call last):
  File "{redacted}/main.py", line 10, in <module>
    print(code)
BrokenPipeError: [Errno 32] Broken pipe
```

(`BrokenPipeError` is not relevant here)

Or, run the following code:

```python
code = """a = 1
if a == 0:
    print(0)
"""
for i in range(1, 10000):
    code += f"""elif a == {i}:
    print({i})
"""

exec(code)
```

... causes the following error:

```
Traceback (most recent call last):
  File "{redacted}/main.py", line 10, in <module>
    exec(code)
MemoryError
```

In Python 3.8.10, the error message is changed as follows:

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    exec(code)
RecursionError: maximum recursion depth exceeded during compilation
```

I think this is a bug, and the bug is due to parsing the Python code to AST causing `RecursionError`.

# Your environment

- CPython versions tested on: `Python 3.11.3`
- Operating system and architecture: Arch Linux `6.3.5-arch1-1`

**Comment by sunmy2019** [comment]
Note Python <= 3.10 is no longer maintained for bug fixes.

**Comment by corona10** [comment]
See related issue too.
* https://github.com/python/cpython/issues/60731
* https://github.com/python/cpython/issues/50015

**Comment by corona10** [comment]
> I think this is a bug, and the bug is due to parsing the Python code to AST causing RecursionError.

FYI, it is intended behavior so it is not a bug but if you think that it should be improved. Please let us know the practical usecase.

**Comment by pbzweihander** [comment]
I stepped on this bug when I using  [Amaranth](https://github.com/amaranth-lang/amaranth). Amaranth's `Memory` generates code with many `elif`s. I also think I should report this to Amaranth's issue tracker.

**Comment by terryjreedy** [comment]
The solution to a MemoryError is to get more memory.
