### ISSUE TITLE
Add experimental support for importing extension modules compiled for WASI

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#105738]
```
❯ ./run_wasi.sh -c "import importlib.machinery; print(importlib.machinery.EXTENSION_SUFFIXES)"
[]
```

See https://bytecodealliance.zulipchat.com/#narrow/stream/223391-wasm/topic/Python.20guest.20runtime.20and.20bindings/near/365948067 where this is being brought up.

**Comment by brettcannon** [comment]
This is probably blocked by upstream having the right support, else I don't see how trying to compile against `dlopen()` will succeed until it's available.

**Comment by dicej** [comment]
I have [a prototype](https://github.com/dicej/component-linking-demo/blob/main/dl.c) of `dlopen` support which I plan to add to `wasi-libc` once I've put it through some real-world tests (including Python extensions).
