### ISSUE TITLE
os.rename fails on filename with "🏴🏳️‍⚧️" in it.  (But works just fine for other unicode characters.)

### ISSUE THREAD

**Issue by ClaireCJS** [python/cpython#105779]
# Bug report

shutil has a renaming bug

What happened: I hit my first-ever failure due to shutil failure

Folder name is `Kai 🏴󠁧󠁢󠁳󠁣󠁴󠁿 🏳️‍⚧ 25% off OF (@hey)` and cannot be renamed.

```plain
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.\\Kai 🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f 🏳️\u200d⚧️ 25% off OF (@hey)' -> '.\\Kai {WAVING BLACK FLAG}{TAG LATIN SMALL LETTER G}{TAG LATIN SMALL LETTER B}{TAG LATIN SMALL LETTER S}{TAG LATIN SMALL LETTER C}t{CANCEL TAG} {WAVING WHITE FLAG}{VARIATION SELECTOR-16} {transgender_symbol}{VARIATION SELECTOR-16} 25pct off OF (@hey)'
```

This error message is wrong. The source filename is not incorrect. It exists! I'm looking at it!
And the destination filename? It's cleansed of unicode characters and is a straight-ASCII filename that most definitely is valid.

**The interesting part is that this rename works if you remove the percentage sign, and it also works if you remove the unicode characters. But it does not work if both are present!**

Note that the backstory to this is, I've written a unicode-filename cleanser that is supposed to remove all unicode from all files and folders.  I've successfully run it on hundreds of folder names with unicode in them, and hundreds of thousands of files with unicode in them.

This is the first failure in shutil.

# Your environment

- Python 3.10.9
- Windows 10 [Version 10.0.19045.3031] (64-bit)

```[tasklist]
### Tasks
```

**Comment by ClaireCJS** [comment]
It will take me a few hours for the conditions to be recreated and then I will make it happen again and do that :)

**Comment by eryksun** [comment]
If you know the path of the parent directory, you could just provide the ASCII formatted directory listing in a code block. For example:

```python
p = r'path\to\parent\directory'
print(*(ascii(x) for x in os.listdir(p) if x.startswith('Kai')), sep='\n')
```

**Comment by ClaireCJS** [comment]
It doesn't actually exist right now. It's the result of a downloading program that has a queue that can't be managed (with the error being my postprocessing program), so I have get through the queue again. Which is actually good because that will be a better reproduction than me trying to manually create the problematic filename.

**Comment by terryjreedy** [comment]
You should be able to edit you first post by putting *```* lines before and after the exception already there.

**Comment by arhadthedev** [comment]
@terryjreedy Done, on the OP's behalf.

**Comment by eryksun** [comment]
> You should be able to edit you first post by putting ``` lines before and after the exception already there.

I'm hoping that some control character was lost when the issue was created -- something that's no longer in the [raw data](https://api.github.com/repos/python/cpython/issues/105779) of the issue. If not, I'm at a loss to explain why WinAPI `MoveFileExW()` failed with `ERROR_INVALID_NAME` (123). The given name is valid.

```pycon
>>> s = '.\\Kai 🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f 🏳️\u200d⚧️ 25% off OF (@hey)'
>>> print(ascii(s))
'.\\Kai \U0001f3f4\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f \U0001f3f3\ufe0f\u200d\u26a7\ufe0f 25% off OF (@hey)'
```
I have no problem creating and accessing a directory with this name in an NTFS or exFAT filesystem. If it's some other filesystem, maybe it has a problem with the non-BMP characters, which are passed to the filesystem as UTF-16 surrogate pairs. However, that doesn't explain why it works if the percent character is removed. Percent isn't a reserved character. Also, I'm not sure what "remove the percentage sign" actually means. Can the directory be renamed in some other program? Or was a new directory created with a name that's the same except without the percent character?

**Comment by ClaireCJS** [comment]
Sorry if I was unclear. I poked around with the situation a bit before moving on (and I wish I'd made a copy first, so I don't have to wait for the conditions to happen again). 

I am indeed using a renaming program I wrote.  

So:

- the program could successfully rename the file if I removed the % from  the filename first.  (Which would make you think there are special processing issues with the % character, but no, it deals with percents just fine in every other situation, and percents are one of the characters I scrub out of filenames for being problematic sometimes)

So it seemed the program could succeed with either part that I would be inclined to think might be the cause of the problem (either the emoji, or the percent, or perhaps one of the invisible VARIATION-SELECTOR unicode characters), but not with both parts.

I'm going to try harder to reproduce the behavior when the situation comes back up again tomorrow.  Circumstances prevent its recreation until tomorrow.

**Comment by ClaireCJS** [comment]
Okay, the 3rd party downloading tool has re-created the offending foldername, and I've re-run it through my fix_unicode_filenames.py, and it has failed to rename this (while never failing with hundreds of other unicode/emoji file/foldernames).

Here is the FULLLLL output.

```
 6/15/2023  10:36         <DIR>    .
 6/15/2023  10:36         <DIR>    ..
 6/15/2023  10:36         <DIR>    Kai 🏴󠁧󠁢󠁳󠁣󠁴󠁿 🏳️‍⚧️ 25% off OF (@cutekittenkink)
                   0 bytes in 0 files and 3 dirs
     209,919,578,112 bytes free

<10:36a> <8%> C:\test>fix_unicode_filenames.py
* Processing file Kai   25% off OF (@cutekittenkink)...

***** Rename:
From: Kai   25% off OF (@cutekittenkink)
  To: Kai {WAVING BLACK FLAG}{TAG LATIN SMALL LETTER G}{TAG LATIN SMALL LETTER B}{TAG LATIN SMALL LETTER S}{TAG LATIN SMALL LETTER C}t{CANCEL TAG} {WAVING WHITE FLAG}{VARIATION SELECTOR-16}{ZERO WIDTH JOINER}{transgender_symbol}{VARIATION SELECTOR-16} 25pct off OF (@cutekittenkink)
***** Rename? [Y/n] Yes!

Traceback (most recent call last):
  File "C:\BAT\fix_unicode_filenames.py", line 1137, in <module>
    main()
  File "C:\BAT\fix_unicode_filenames.py", line 791, in main
    rename_files_in_current_directory    (mode="file",automatic_mode=mode_is_automatic)                #do current folder, which may change folder names
  File "C:\BAT\fix_unicode_filenames.py", line 581, in rename_files_in_current_directory
    process_directory(directory)
  File "C:\BAT\fix_unicode_filenames.py", line 569, in process_directory
    rename_folder_but_if_renamed_is_a_folder_that_already_exists_then_move_files_into_it_instead(old_file, new_new_file)
  File "C:\BAT\fix_unicode_filenames.py", line 591, in rename_folder_but_if_renamed_is_a_folder_that_already_exists_then_move_files_into_it_instead
    os.rename(old_name, new_name)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '.\\Kai 🏴\U000e0067\U000e0062\U000e0073\U000e0063\U000e0074\U000e007f 🏳️\u200d⚧️ 25% off OF (@cutekittenkink)' -> '.\\Kai {WAVING BLACK FLAG}{TAG LATIN SMALL LETTER G}{TAG LATIN SMALL LETTER B}{TAG LATIN SMALL LETTER S}{TAG LATIN SMALL LETTER C}t{CANCEL TAG} {WAVING WHITE FLAG}{VARIATION SELECTOR-16}{ZERO WIDTH JOINER}{transgender_symbol}{VARIATION SELECTOR-16} 25pct off OF (@cutekittenkink)'

```

And a screenshot for good measure:
![image](https://github.com/python/cpython/assets/789591/29a12f4e-dd30-49a7-927d-64d82c073a8f)

**Comment by eryksun** [comment]
A filename is invalid either because it contains reserved characters (typically `\/*?<>":|` and ordinals 1-31) or because it's too long. The maximum name length is 255 16-bit characters. The common disk filesystems on Windows (NTFS, ReFS, FAT32, and exFAT) support the upper limit. Some filesystems may have a lower limit.

On Linux, the maximum filename length is 255 8-bit characters. Given UTF-8 encoding, that's between 63 and 255 Unicode characters.

**Comment by ronaldoussoren** [comment]
> D'ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh
> 
> I guess... Could this maybe become a feature request for a more meaningful error message so that someone else in my situation doesn't embarrass themselves with a bug report? 😅

The error message is based on the system error code, in particular the "The filename, directory name, or volume label syntax is incorrect" bit.  The system error code doesn't differentiate between causes for a wrong name, that's why we cannot give a better error message, at least not without trying to reproduce the algorithm the OS uses the validate names.

To validate my reading of the issue: There is no bug here because the script tried to rename a file to a name that is not accepted by the OS (in this case a too long name). Is that correct? 

BTW. Don't feel emberrassed about filing an issue, you're not the first or last that's stumped by some issue that turns out to be easy when someone else points that out.
