### ISSUE TITLE
test added in gh-104067 has an fstring with an invalid escape sequence

### ISSUE THREAD

**Issue by mattip** [python/cpython#105784]
# Bug report

In response to #104049, a fix and a new test were added in #104067 and related PRs. The test [in test_httpserver.py](https://github.com/python/cpython/pull/104067/files#diff-5c8de474c50a44ead423e2d9ce85c1932b9c87ba9f5a3215c0b8b996c65e62b9R424) uses an fstring with an escape sequence, but does not use `r`:
```
f'listing for {self.base_url}/\?x=123'
```

I think the code (in two places) should be include an `r`: `fr'listing for ...`

On PyPy this is causing the `test___all__.py` test to fail, since it emits a warning when compiling the `*.py` to `*.pyc`. I am not sure why CPython is not seeing a similar problem. Perhaps `compileall` is run first? Or the warning filter captures the compilation as well as the import?

# Your environment

- CPython versions tested on: PyPy3.9 HEAD using stdlib 3.9.17
- Operating system and architecture: any

**Comment by terryjreedy** [comment]
@mattip CPython does not issue this warning `SyntaxWarning: invalid escape sequence '\?'` until 3.12, though only for normal strings.  What warning is PyPy3.9 emitting?  (Note: try to minimize reproducing examples, as I did below ;-)

@pablogsal In 3.12 and 3.13, f-strings are not warning about invalid escapes that get warnings in real strings.  This seems like a bug.
```
>>> f'\?'
'\\?'
>>> len(f'\?')
2
>>> '\?'
<stdin>:1: SyntaxWarning: invalid escape sequence '\?'
'\\?'

**Comment by mattip** [comment]
On python3.9.17 from Ubuntu, I get this
```
$ python3.9 -Walways -c "abc = 'abc'; print(f'listing for {abc}/\?x=123')"
<string>:1: DeprecationWarning: invalid escape sequence \?
listing for abc/\?x=123
```

**Comment by mattip** [comment]
Adding an `r` makes it run without a warning
```
$ python3.9 -Walways -c "abc = 'abc'; print(fr'listing for {abc}/\?x=123')"
listing for abc/\?x=123
```

**Comment by terryjreedy** [comment]
Security patch #104067 was backported to 3.7, which is why it affects PyPy3.9.

@ethanfurman @JelleZijlstra Do the tests added in #104067 require invalid escapes without an 'r' prefix?  Or could the escape be changed or the 'r' added?

**Comment by mattip** [comment]
Thanks. I see that was backported to 3.12. I am curious why not backport it to all versions that contain the test added in #104067 (maybe excepting ones that will no longer be released)? People running the test without precompiling pyc files will see a DeprecationWarning, no?

**Comment by mattip** [comment]
Try as I might, I cannot get CPython3.9 to emit a `DeprecationWarning` in the `test_httpservers.py` test. So I will add the `r` in the PyPy port of the stdlib tests. I am not sure why the test does not emit the warning on CPython3.9, since the f-string needs an `r` if run outside the test, but :shrug:
```
$ python3.9 -Walways -c "abc = 'abc'; print(f'listing for {abc}/\?x=123')"
<string>:1: DeprecationWarning: invalid escape sequence \?
listing for abc/\?x=123
```

**Comment by lysnikolaou** [comment]
This can be closed. @mattip An `r` prefix has been added in #105822.

**Comment by lazka** [comment]
Here it only warned when bytecompile was needed, so if there wasn't a .pyc file already for test_httpservers.
