### ISSUE TITLE
asyncio subprocess stdin/out/err can be filehandles, but this is undocumented

### ISSUE THREAD

**Issue by bewinsnw** [python/cpython#105857]
# Documentation

I was trying to write some asyncio subprocess code to pipe from one process to another, struggled until I found examples with os.pipe(). But going back to the docs I was confused because passing a filehandle isn't mentioned as an option. Looking at the underlying code, I see it definitely _is_ supported, there's a check for the parameter being an integer and the handle is used directly.

The incorrect documentation is here https://github.com/python/cpython/blob/101d5ec7d7fe122fa81a377c8ab8b562d1add9ee/Doc/library/asyncio-eventloop.rst?plain=1#L1439-L1469 

So instead of
```
   * *stdin* can be any of these:

     * a file-like object
     * the :const:`subprocess.PIPE` constant (default) which will create a new
       pipe and connect it,...
```
I'd suggest:
```
   * *stdin* can be any of these:
  
     * a file-like object
     * an existing file descriptor (a positive integer), for example those created with :meth:`os.pipe()`,
     * the :const:`subprocess.PIPE` constant (default) which will create a new
       pipe and connect it,...
```

(and similarly for stdout and stderr)

### Linked PRs
* gh-107986
* gh-108332

**Comment by gvanrossum** [comment]
I'm not sure if this is just a lack of documentation or whether it is intentional, to discourage using raw file descriptors? There might be some problems in edge cases (e.g. sockets on Windows). If you have a simple example of how you used this successfully that would also help.

**Comment by bewinsnw** [comment]
example:
```
import asyncio
import os

async def test():
    r,w = os.pipe()
    p1 = asyncio.create_subprocess_shell("seq 1 100000", stdout=w)
    p2 = asyncio.create_subprocess_shell("wc", stdin=r)
    await asyncio.gather(p1, p2)

asyncio.run(test())
```

```
$ python3 spike.py
  100000  100000  588895                                                                                                                                                                     
```
(the actual code I'm using is a fair bit more complex and takes care of closing handles etc).

I think it's just an omission, not intentional. The asyncio subprocess functions are mostly just wrappers for Popen, which is the thing handling the file handles; and it's handled in both unix and windows variants.

The non-asyncio subprocess documents that file descriptors are ok: https://docs.python.org/3/library/subprocess.html#frequently-used-arguments "stdin, stdout and stderr specify the executed program’s standard input, standard output and standard error file handles, respectively. Valid values are [PIPE](https://docs.python.org/3/library/subprocess.html#subprocess.PIPE), [DEVNULL](https://docs.python.org/3/library/subprocess.html#subprocess.DEVNULL), *an existing file descriptor (a positive integer)*, an existing file object with a valid file descriptor, and None."

In the asyncio subprocess implementation, `_UnixSubprocessTransport` passes everything but subprocess.PIPE to Popen: https://github.com/python/cpython/blob/1858db7cbdbf41aa600c954c15224307bf81a258/Lib/asyncio/unix_events.py#L821-L823 
Popen calls _get_handles: https://github.com/python/cpython/blob/1858db7cbdbf41aa600c954c15224307bf81a258/Lib/subprocess.py#L992
which handles the int filehandles case: https://github.com/python/cpython/blob/main/Lib/subprocess.py#L1704-L1705

 `_WindowsSubprocessTransport` is even simpler and passes all of the stream arguments to Popen: https://github.com/python/cpython/blob/1858db7cbdbf41aa600c954c15224307bf81a258/Lib/asyncio/windows_events.py#L873C1-L875

**Comment by gvanrossum** [comment]
Okay, makes sense. Would you like to submit a doc PR? (I wouldn't mind if the docs were refactored to avoid repeating everything three times, though maybe there are differences that make this tricky, so up to you.)

**Comment by Hels15** [comment]
I have added a pr here, extending the docs. https://github.com/python/cpython/pull/107986
