### ISSUE TITLE
Difference in behaviour of PureWindowsPath in 3.12.0b2 with multiple slashes

### ISSUE THREAD

**Issue by jnoortheen** [python/cpython#105881]
# Bug report

I was trying to add Python3.12 beta 2 to the test suit of [xonsh](https://github.com/xonsh/xonsh/pull/5156) . The tests on Windows were [failing](https://github.com/xonsh/xonsh/actions/runs/5281163680/jobs/9587052082) because of the difference in behaviour of PureWindowsPath. 

This can be reproduced like this 

in Python 3.11

```
>>> from pathlib import PurePosixPath, PureWindowsPath
>>> PurePosixPath("///tmp")
PurePosixPath('/tmp')
>>> PureWindowsPath(r"\\\tmp")
PureWindowsPath('/tmp')
```

but the same in Python 3.12.0b2 would be giving different result
```
In [1]: from pathlib import PurePosixPath, PureWindowsPath
In [2]: PurePosixPath("///tmp")
Out[2]: PurePosixPath('/tmp')
In [3]: PureWindowsPath(r"\\\tmp")
Out[3]: PureWindowsPath('///tmp')
```

I've checked the [changelog](https://docs.python.org/3.12/whatsnew/changelog.html#changelog) and this change of behaviour wasn't mentioned in it. 

# Your environment

- CPython versions tested on: 3.12.0b2
- Operating system and architecture: Windows 64bit

**Comment by arhadthedev** [comment]
`git bisect` points to 8af8f52d175959f03cf4a2786b6a81ec09e15e95 (gh-102003). @barneygale

<details><summary>How I performed the search, for reproducibility</summary>

- script

   ```bat
   git bisect start
   git bisect good v3.11.0
   git bisect bad main
   git bisect run .\gh-105881.cmd
   ```

- `gh-105881.cmd`:

   ```bat
   @echo off
   setlocal EnableDelayedExpansion

   git clean -fx -e gh-105881*
   call pcbuild\clean
   call pcbuild\build

   for /F "usebackq delims=" %%a IN (`call python.bat gh-105881.py`) do (
       if "%%a" == "PureWindowsPath('///tmp')" exit /b 1
   )
   ```

- `gh-105881.py`:

   ```python
   from pathlib import PureWindowsPath
   print(repr(PureWindowsPath(r"\\\tmp")))
   ```

</details>

**Comment by barneygale** [comment]
In Python 3.12, all Windows paths beginning `//` or `\\` are considered to be UNC paths, and so we don't remove leading slashes. In previous versions of Python the rules were more complex. More info here: https://github.com/python/cpython/issues/96290#issuecomment-1227866966

It's mentioned in the changelog (ctrl-f for "Fix handling of partial and invalid UNC drives in ntpath.splitdrive()") but the reST formatting of the entry is messed up. Will fix!

**Comment by jnoortheen** [comment]
Thanks for clarifying !
