### ISSUE TITLE
Allow eval and exec to take keyword arguments

### ISSUE THREAD

**Issue by rtpg** [python/cpython#105879]
# Feature or enhancement

Allow for `globals` and `locals` to be passed in as keyword arguments to `exec` and `eval`.

# Pitch

`exec` and `eval` both can take `globals` and `locals` as positional arguments. 
The built-in functions documentation shows the argument defaults, and _every time_ I have the documentation open and am writing these, I default to keyword arguments, and it fails because the arguments are positional-only.

For functions like this that might only be present in a handful of places, kwargs give a good way to document what parameters each argument is referring to. I don't think that in a universe in which we were introducing `eval`/`exec` now that we would explicitly disallow kwargs.

# Previous discussion

I sent [this email](https://mail.python.org/archives/list/python-ideas@python.org/thread/AD37KVC4CP4HQD4D7VUJTCWSP4LKEZYB/) to `python-ideas`

# Extra Links

[Here is an implementation](https://github.com/rtpg/cpython/commit/c4368ef213a64297954fbca4f5308d69409d6a4b), which just consists in changing the argument clinic config and rerunning. I set up some very basic kwarg tests mostly to test the case of "locals provided but globals not provided", but fortunately the existing implementations already handled this cleanly!

### Linked PRs
* gh-105885
* gh-121831
* gh-121852

**Comment by sunmy2019** [comment]
My concern is, will this hurt performance a lot?

**Comment by JelleZijlstra** [comment]
We can benchmark it, but that seems unlikely; parsing code is probably a lot slower than accepting some keyword arguments.

**Comment by rtpg** [comment]
@sunmy2019 I added a link to a commit implementing this. The short version is `eval` now has a bit more parsing code, but `exec` already has support for one kwarg, so we're still looking at the same order of magnitude of instructions or existing code IMO.

**Comment by JelleZijlstra** [comment]
Make a PR :)

**Comment by rtpg** [comment]
Created the PR, and tests seem to be passing now

**Comment by JelleZijlstra** [comment]
This will be in Python 3.13, thank you!
