### ISSUE TITLE
Clean up the `CALL` sequence

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#105848]
The bytecode sequence for calls has gotten better in 3.12, but I think it can still be improved in a couple of ways:
- First, we can start either pushing `NULL` or a tuple of `kwnames` onto the stack immediately before calls, rather than sometimes stashing `kwnames` away in a local eval loop variable via the `KW_NAMES` opcode. This *should* free up a register around calls, and it's nice to do anyways since it makes the bytecode more regular (and the stack is really where this sort of stuff belongs).
- Once that is done, we can use the low bit of the `CALL` oparg to indicate whether or not to expect `kwnames` on the stack. This should get rid of lots of new `PUSH_NULL`/`CALL` pairs.
- Separate from the above, but still sort of related: it's a bit awkward that our method call optimization either leaves `[callable, self, args...]` or `[NULL, callable, args...]` on the stack, since it means that `CALL` (and most of its specializations) have to do an awkward swap in order to load the "correct" callable. This can be simplified by always entering calls with `[callable, self_or_null, args...]` on the stack, so that the callable is always in the same position.

After this is all said and done, the `CALL` stack effect will look something like:

```c
inst(CALL, (counter/1, cache/2, callable, self_or_null, args[oparg >> 1], kwnames if (oparg & 1) -- res)) {
    // ...
}
```

### Linked PRs
* gh-105849
* gh-107788
* gh-108496
* gh-109300

**Comment by hugovk** [comment]
Anything left to do here, or can we close this issue?
