### ISSUE TITLE
singledispach and singledispachemethod from functools treat bool as int

### ISSUE THREAD

**Issue by popescu-catalin-ionut** [python/cpython#105883]
# Bug report

singledispach from functools is treat bool as an integer

# Your environment

Tested on CPython official windows arm64: 3.6.8, 3.11.3 and 3.11.4

## Singledispachmethod Example

~~~Python
from functools import singledispatchmethod


class Test:

    @singledispatchmethod
    def add(self, value):
        raise NotImplementedError('Unsupported type')


    @add.register
    def _(self, value:int):
        print("INT, First argument is of type ", type(value))



    @add.register
    def _(self, value:str):
        print("str, First argument is of type ", type(value))


if __name__ == '__main__':
    obj = Test()
    obj.add('Python')  #execute ok this line
    obj.add(1)  #execute ok this line
    obj.add(True)  #execute not ok this line because Interpreter should return NotImplemented error
~~~
This code generate following output
~~~
str, First argument is of type  <class 'str'>
INT, First argument is of type  <class 'int'>
INT, First argument is of type  <class 'bool'>
~~~

## Singledispach Example

~~~Python
from functools import singledispatch


@singledispatch
def test(arg1):
    print("default implementation of func - ")


@test.register
def test1(arg1: str):
    print("STR, First argument is of type ", type(arg1))


@test.register
def test2(arg1: int):
    print("INT, First argument is of type ", type(arg1))


test(2,)

test('string')

test(True) #execute not ok this line because Interpreter should run print("default implementation of func - ")

~~~
This code generate following output
~~~
INT, First argument is of type  <class 'int'>
STR, First argument is of type  <class 'str'>
INT, First argument is of type  <class 'bool'>
~~~

**Comment by Eclips4** [comment]
It's happens because `bool` is subclass of a `int` type. 
Documentation is bit unclear here, so, seems that this behavior is long standing, and best solution will be here just a documentation it.

**Comment by Eclips4** [comment]
сс @ethanhs as author of singledispatch

**Comment by popescu-catalin-ionut** [comment]
Personally I don't like proposed solution because in every Python book and reference Bool type is treat as a distinct type.
Typing library is treating as distinct type so if I use typing to mark an argument as certain type I expect to a certain behavior. 
This will create confusion and complexity if in typing or other libraries typing is treat bool correct and in singledispach is different

And for sure you can add an if statement to validate if type is bool or not so is doable.

**Comment by ethanhs** [comment]
Hi! I actually didn't write singledispatch, only singledispatchmethod. I agree it looks like the docs could be updated to clarify this, I *think* the sentence below is trying to express that subclasses are considered?

> Where there is no registered implementation for a specific type, its method resolution order is used to find a more generic implementation.

I'm happy to review a PR with updated wording if someone wants to write that.

**Comment by popescu-catalin-ionut** [comment]
Can you explain me, please, why singledispach or singledispachmethod should work different than a switch case where you have int and bool?

~~~Python
def test(arg):
    match type(arg):
        case str():
            print("It is a string!")
        case int():
            print("It is an integer!")
        case bool():
            print("It is a boolean!")
        case _:
            print(f"It is a {type(arg)}!")

            
test(1)
#  It is a <class 'int'>!
test(True)
#  It is a <class 'bool'>!
~~~

**Comment by sunmy2019** [comment]
> Personally I don't like proposed solution because in every Python book and reference Bool type is treat as a distinct type. Typing library is treating bool as distinct type so if I use typing to mark an argument as certain type I expect to a certain behavior. This will create confusion and complexity if in typing or other libraries annotation is treat bool correct and in singledispach is different
> 
> And for sure you can add an if statement to validate if type is bool or not so is doable.

You did not understand the question. `bool` is a subtype of `int`, and that is how it gets matched by the int.

Yes, we do look at subtypes when doing dispatches. This feature is crucial for users.

**Comment by ethanhs** [comment]
> Typing library is treating bool as distinct type

Most type checkers treat bool as a subtype of int. Also you can coerce bools into ints, `True + True == 2` after all.

**Comment by ronaldoussoren** [comment]
There is no bug here, singledispatch behaves as documented: You registered an implementation for ``int`` and none for ``bool``, the registered implementation for int. is used for boolean arguments because ``bool`` is a subclass of ``int`` (and hence ``int`` is on the MRO for ``bool``).

If you want different behaviour for boolean values you need to register an implementation for ``bool``.

**Comment by ericvsmith** [comment]
I agree there’s no bug here.

**Comment by popescu-catalin-ionut** [comment]
Sorry for not having time for re-explain the bug better... Unfortunately you already close it.

@Eclips4, @ethanhs and @ericvsmith  I was trying to say that if I register a bool is working, and every one will expect.

~~~Python
from functools import singledispatch


@singledispatch
def test(arg1):
    print("default implementation of func - ")


@test.register
def test1(arg1: int):
    print("int, First argument is of type ", type(arg1))

@test.register
def test2(arg1: bool):
    print("bool, First argument is of type ", type(arg1))

test(2) # working properly - I've registered an int and it is working properly

test(True)  # working properly - I've registered a bool and it is working properly
~~~

If I don't register bool everyone that I've spoke with and my students (because I teach Python) expect to go on default.

~~~Python
from functools import singledispatch


@singledispatch
def test(arg1):
    print("default implementation of test")


@test.register
def _ (arg1: int):
    print("INT, First argument is of type ", type(arg1))


test(2)

test(True)  # execute unexpected because Interpreter should run print("default implementation of test ")
~~~
I already know that bool is a subtype of int, but still it behaves unexpected. 

If decision is already made so be it, and thank you for your time, but still maybe you can change in next flavors to behave as expected.

**Comment by ericvsmith** [comment]
This is no more surprising than:
```python
class MyInt(int):
    pass

test(MyInt())
```
Which also prints: `int, First argument is of type  <class '__main__.MyInt'>`

This is an opportunity to teach about `isinstance` and subclasses!

**Comment by pochmann** [comment]
> maybe you can change in next flavors to behave as expected.

It already does. Your expectation is just wrong.
