### ISSUE TITLE
Proposing Type hinting for *args

### ISSUE THREAD

**Issue by moghadas76** [python/cpython#105896]
# Feature or enhancement

I was reading https://docs.python.org/3.12/whatsnew/3.12.html#new-features-related-to-type-hints  what if to define similar type for `*args` addition to **kwargs

**Comment by TeamSpen210** [comment]
This has already been done, via [PEP 646](https://peps.python.org/pep-0646/#args-as-a-type-variable-tuple)'s `TypeVarTuple`.

**Comment by JelleZijlstra** [comment]
Indeed. You can write

```
def f[*Ts](*args: *Ts) -> tuple[*Ts]: return args
```

or
```
def f(*args: *tuple[int, str]): pass
```
