### ISSUE TITLE
python inspect cannot collect annotation information from pytorch function 'GRU'

### ISSUE THREAD

**Issue by Gwihwan-Go** [python/cpython#105890]
# Bug report

The Python inspect module is unable to collect annotation information from the PyTorch function 'GRU'.
```python
import inspect 
import torch
print(inspect.signature(torch.nn.GRU))
print(torch.nn.GRU. __annotations__)
```

Output : 
```
(*args, **kwargs)
{'mode': <class 'str'>, 'input_size': <class 'int'>, 'hidden_size': <class 'int'>, 'num_layers': <class 'int'>, 'bias': <class 'bool'>, 'batch_first': <class 'bool'>, 'dropout': <class 'float'>, 'bidirectional': <class 'bool'>, 'proj_size': <class 'int'>}
```

# environment

pytorch version : 2.0.0

- CPython versions tested on: 3.9.16
- Operating system and architecture: Linux, x86_64

**Comment by sunmy2019** [comment]
The behavior of `inspect` is aligned with their doc

https://pytorch.org/docs/stable/generated/torch.nn.GRU.html#torch.nn.GRU

> CLASStorch.nn.GRU(*args, **kwargs)

And aligned with the source code: They have a customized `__init__`.
```py
    def __init__(self, *args, **kwargs):
```

**Comment by sunmy2019** [comment]
In conclusion, collecting annotations is not something `inspect.signature` should do.

Will be closed as invalid.

**Comment by terryjreedy** [comment]
The __annotations__ attribute was added long after signature introspection.  It is used for static type checking.  It does not contain the information needed by inspect.signature and is not used by inspect.signature.  For python-defined functions, It can be modified after the function is created and thereby be completely wrong for detecting the real signature.
```
>>> def f(a:int, b, /, *, c=[]): pass
... 
>>> f.__annotations__
{'a': <class 'int'>}
>>> inspect.signature(f)
<Signature (a: int, b, /, *, c=[])>
>>> f.__annotations__ = {'fake': object()}
>>> f.__annotations__
{'fake': <object object at 0x0000018A857698E0>}
```
