### ISSUE TITLE
Bump required SQLite version to 3.15.2

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#105875]
(Also [posted on Discord](https://discuss.python.org/t/bump-sqlite-minimum-version-requirement/27999?u=erlendaasland).)

In January 2021 (mid 3.10 development), Sergey Fodoseev and I raised the compile time (and runtime) SQLite version requirements for the sqlite3 standard library extension module to SQLite [3.7.15](https://sqlite.org/releaselog/3_7_15.html) (2012-12-12) or newer (commit cf0b23908cc902ac38cd83dd7ca5afdf89e1543b). That enabled us to clean up the code by getting rid of a lot of preprocessor conditionals and other version specific workarounds.

For Python 3.13 (to be released October 2024), I'll raise the version requirements to either SQLite [3.8.11.1](https://sqlite.org/releaselog/3_8_11_1.html) (2015-07-29), [3.14.2](https://sqlite.org/releaselog/3_14_2.html) (2016-09-12), or [3.15.2](https://sqlite.org/releaselog/3_15_2.html) (2016-11-28). Preferably the latter.

AFAICS on [DistroWatch](https://distrowatch.com/dwres.php?resource=package-in-distro&pkg=sqlite), we should be fine with any of those SQLite versions, for all major distros[^1].

Major clean-ups:
- For SQlite 3.8.11.1, I can remove a lot of conditional code related to CTEs and deterministic functions.
- For SQLite 3.14.2 I no longer need to implement two different variants of the trace callback.
- For SQLite 3.15.2, I can remove special handling for legacy deterministic user function behaviour.

[^1]: RHEL-7.9 ships with SQLite 3.7.17 but is EOL in June 2024.

### Linked PRs
* gh-105876
* gh-129599
* gh-129602

**Comment by corona10** [comment]
cc @ned-deily 

Will it be okay to macOS too?

**Comment by erlend-aasland** [comment]
> Will it be okay to macOS too?
> 
> (From my local environment it looks okay)

We bundle SQLite for macOS installers, so it is not a problem.

**Comment by corona10** [comment]
> We bundle SQLite for macOS installers, so it is not a problem.

Thanks!
