### ISSUE TITLE
Assertion failure in `_imp.get_frozen_object` if data object contains bad marshal data

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#105979]
Repro:
```python
import _imp
>>> _imp.get_frozen_object('x', b"6\'\xd5Cu\x12")
```
Output:
```
python: Objects/object.c:541: PyObject_Repr: Assertion `!_PyErr_Occurred(tstate)' failed.
Aborted (core dumped)
```
I'll submit a PR.

### Linked PRs
* gh-105980
* gh-106055
* gh-106100

**Comment by marceltrio** [comment]
> Repro:
> 
> ```python
> import _imp
> >>> _imp.get_frozen_object('x', b"6\'\xd5Cu\x12")
> ```
> 
> Output:
> 
> ```
> python: Objects/object.c:541: PyObject_Repr: Assertion `!_PyErr_Occurred(tstate)' failed.
> Aborted (core dumped)
> ```
> 
> I'll submit a PR.
> 
> ### Linked PRs
> * [gh-105979: Fix exception handling in `unmarshal_frozen_code` (`Python/import.c`) #105980](https://github.com/python/cpython/pull/105980)
> * [[3.12] gh-105979: Fix exception handling in `unmarshal_frozen_code` (`Python/import.c`) (GH-105980) #106055](https://github.com/python/cpython/pull/106055)
> * [[3.11] gh-105979: Fix exception handling in unmarshal_frozen_code (`Python/import.c`) (GH-105980). #106100](https://github.com/python/cpython/pull/106100)

**Comment by mattip** [comment]
When is `get_frozen_object` called with a data argument? On PyPy we do not have a data argument to the function and everything seems to work well.
