### ISSUE TITLE
Invalid IndentationError.offset in nested definitions missing an indentation block and preceding a valid line

### ISSUE THREAD

**Issue by seeM** [python/cpython#105911]
# Bug report

The [Python docs](https://docs.python.org/3.13/library/exceptions.html#SyntaxError) state that `SyntaxError.offset` is 1-indexed, however, the following edge-case involving nested definitions with a missing indentation block and a symbol on the next line returns a value of zero:

```python
def get_error_offset(source):
    try:
        compile(source, 'file.py', 'exec')
    except IndentationError as error:
        return error.offset
    raise AssertionError()

# These are fine
assert get_error_offset('def g():\n') > 0
assert get_error_offset('def g():\n0') > 0
assert get_error_offset('def f():\n    def g():\n') > 0
assert get_error_offset('class A:\n    def g():\n') > 0

# Bug with a nested definition, missing the second indentation block, with a symbol thereafter
assert get_error_offset('def f():\n    def g():\n0') == 0
assert get_error_offset('class A:\n    def g():\n0') == 0
assert get_error_offset('def f():\n    class A:\n0') == 0

# Bug for 3 and 4 layers of nesting
assert get_error_offset('def f():\n  def g():\n    def h():\n0') == 0
assert get_error_offset('def f():\n  def g():\n    def h():\n      def i():\n0') == 0
```

# Your environment

- CPython versions tested on: 3.7.16, 3.8.16, 3.9.16, 3.10.11, 3.11.3, 3.12.0b1
- Operating system and architecture: macOS 13.4 (arm64), also reproduced in the `python:3` docker image

**Comment by terryjreedy** [comment]
Same on Windows with 3.12.0b2.

**Comment by seeM** [comment]
Thanks for confirming. BTW I would love to try contribute to a fix (with some pointers to get started), but totally understand if that’s not on the table.
