### ISSUE TITLE
Use ctypes to load C library in the win11 system will crash

### ISSUE THREAD

**Issue by stgfeng** [python/cpython#105955]
# Bug report

I used ctypes to load  C library in the win11 system,  python will crash when the interface is called.  But it can be used normally in the win10 system.

Code like this
```
from ctypes import *
lib = CDLL("./SR7Link.dll")
class SR7IF_ETHERNET_CONFIG(Structure):
    _fields_ = [('abyIpAddr', c_ubyte * 4)]
ip = SR7IF_ETHERNET_CONFIG()
ip.abyIpAddr = (192,168,0,10)
lib.SR7IF_EthernetOpen(0, ip.abyIpAddr)
```

# Your environment

Windows 11 hone
22H2
22621.1702

python 3.11.4 amd64

# The C library 
[SR7Link.zip](https://github.com/python/cpython/files/11811336/SR7Link.zip)

**Comment by sunmy2019** [comment]
Why are you assuming it can also be used on Windows 11?

---

What is inside your `dll`? Letting others open your `dll` is not safe for others.

You need to provide strong evidence that this is safe.

**Comment by eryksun** [comment]
Please provide the exact definition of the `SR7IF_ETHERNET_CONFIG` structure and `SR7IF_EthernetOpen` prototype from the C API header. I searched but couldn't find it. I assume it's in a development kit that can be downloaded freely or licensed.

**Comment by stgfeng** [comment]
> Please provide the exact definition of the `SR7IF_ETHERNET_CONFIG` structure and `SR7IF_EthernetOpen` prototype from the C API header. I searched but couldn't find it. I assume it's in a development kit that can be downloaded freely or licensed.

Yes, it's a development kit. It can be downloaded freely. 
The new zip file contain  the C API header.
[SR7Link.zip](https://github.com/python/cpython/files/11814762/SR7Link.zip)

**Comment by stgfeng** [comment]
> Why are you assuming it can also be used on Windows 11?
> 
> What is inside your `dll`? Letting others open your `dll` is not safe for others.
> 
> You need to provide strong evidence that this is safe.

This is our company's development kit. 
You can download the SDK from https://www.cnsszn.com/download.html.

I'm sure it can be used on Windows 11, the SDK's VS demo or QT demo can be used normally in the win11 system.

**Comment by sunmy2019** [comment]
> Use ctypes to load C library in the win11 system will crash

Can you reproduce this without using your company's development kit?


How can you tell it is a bug of `ctypes`?
What if it's something related to the Windows library?
What if it's something is incompatible with your development kit?


---

Also, we cannot get the source code of your SDK. It is impractical for us to debug your SDK.

**Comment by sunmy2019** [comment]
If you want to let us debug `ctypes`, my advice would be to provide a reproducible example that does not involve your SDK.

Otherwise, there is not much that we can do.

**Comment by eryksun** [comment]
For everyone's reference, here are the relevant declarations and definitions from the C header "SR7Link.h":

```c
#ifdef WIN32
#define  SR7_IF_API __declspec(dllexport)
#else
#define  SR7_IF_API extern
#endif

typedef struct {
    unsigned char	abyIpAddress[4];
} SR7IF_ETHERNET_CONFIG;

SR7_IF_API int SR7IF_EthernetOpen(unsigned int lDeviceId, SR7IF_ETHERNET_CONFIG* pEthernetConfig);
```

Here's how I would translate this to Python:

```python
import ctypes

lib = ctypes.CDLL('./SR7Link.dll')

class SR7IF_ETHERNET_CONFIG(ctypes.Structure):
    __slots__ = ()
    _fields_ = (
       ('abyIpAddress', ctypes.c_ubyte * 4),
    )

lib.SR7IF_EthernetOpen.restype = ctypes.c_int
lib.SR7IF_EthernetOpen.argtypes = (
    ctypes.c_uint, # lDeviceId
    ctypes.POINTER(SR7IF_ETHERNET_CONFIG), # pEthernetConfig
)

ip = SR7IF_ETHERNET_CONFIG(abyIpAddress=(192, 168, 0, 10))
result = lib.SR7IF_EthernetOpen(0, ctypes.byref(ip))
```
That said, I don't see a serious error in your initial example. It lacks the prototype for `SR7IF_EthernetOpen`, but the default conversion of 0 works fine for an `unsigned int` parameter, and passing the ctypes array `ip.abyIpAddr` isn't effectively different from passing `ctypes.byref(ip)` in this case. They're both passed as a pointer to the same 4 bytes in memory.

If you can't provide more information on the nature of the crash that demonstrates that the Python runtime, ctypes, or libffi is at fault, then there's nothing more that I can do here. For example, provide the Windows event log for the crash that includes the exception code and faulting module (e.g. "python311.dll", "_ctypes.pyd", "libffi-8.dll"). Even better would be to run Python under a native debugger (e.g. windbg, cdb) -- or configure one for automatic, postmortem debugging -- and provide the output from the debugger command `!analyze -v` or a minidump created by the debugger command `.dump /m <filename>`.

**Comment by sunmy2019** [comment]
Isn't this debug report from Win 10?

**Comment by stgfeng** [comment]
### Test PC information
CPU	        12th Gen Intel(R) Core(TM) i7-12700H   2.30 GHz
RAM	16.0 GB
SYSTEM    Windows 11 HOME
VERSION  22H2
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
WinDbg:10.0.22621.1778 AMD64

**Comment by sunmy2019** [comment]
> STACK_TEXT:
> 00000041`107eee30 00007ffb`e97661b9 : 00007ffb`e97dcc00 00000041`10480000 00000041`10480000 00000041`10480000 : ntdll!LdrpDoDebuggerBreak+0x30
> 00000041`107eee70 00007ffb`e9759a00 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000001 : ntdll!LdrpInitializeProcess+0x1cf9
> 00000041`107ef240 00007ffb`e9703e53 : 00000041`107ef590 00007ffb`e9690000 00000041`10480050 00000041`104827ee : ntdll!_LdrpInitialize+0x55b74
> 00000041`107ef2c0 00007ffb`e9703d7e : 00000041`107ef590 00000000`00000000 00000041`107ef590 00000000`00000000 : ntdll!LdrpInitializeInternal+0x6b
> 00000041`107ef540 00000000`00000000 : 00000000`00000000 00000000`00000000 00000000`00000000 00000000`00000000 : ntdll!LdrInitializeThunk+0xe

This stack does not look related to CPython.

**Comment by AA-Turner** [comment]
Closing, no response from reporter.

A
