### ISSUE TITLE
Missing reference to issue in subprocess documentation

### ISSUE THREAD

**Issue by swaldhoer** [python/cpython#105975]
# Documentation

https://docs.python.org/3/library/subprocess.html#disabling-use-of-vfork-or-posix-spawn references

```
subprocess._USE_VFORK = False  # See CPython issue gh-NNNNNN.

subprocess._USE_POSIX_SPAWN = False  # See CPython issue gh-NNNNNN.
```

These are the only missing references I found in the whole docs.

I tried to find the correct issue number, however it was not as easy as expected:
It either is https://github.com/python/cpython/issues/80004 or https://github.com/python/cpython/issues/79718.

**Comment by hugovk** [comment]
Using git blame (https://github.com/python/cpython/blame/main/Doc/library/subprocess.rst), we can see this was added in PR https://github.com/python/cpython/pull/91490.

**Comment by ronaldoussoren** [comment]
The end of that section already states:

> Please file issues any time you have to use these private knobs with a way to reproduce the issue you were seeing. Link to that issue from a comment in your code.
