### ISSUE TITLE
asyncio.EventLoop.start_tls() returns None

### ISSUE THREAD

**Issue by Dreamsorcerer** [python/cpython#105993]
# Bug report

The documentation says the function should return a transport:
https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.start_tls

But, in some cases it actually returns None. It looks like this may happen when it receives a closing transport:
https://github.com/aio-libs/aiohttp/issues/3355#issuecomment-1597689576

I suspect this is because connection_lost() gets called during the start_tls() call, which ends up setting it to None:
https://github.com/python/cpython/blob/dba72175116373c1d15e25d84c88b516daf9f5c4/Lib/asyncio/sslproto.py#L412

Should this be allowed to return None, or should there be an exception occurring here?
A simple change could be to check for None and raise an exception, but I'm not too familiar with how this part of the code is expected to work.

### Linked PRs
* gh-105995
* gh-106188
* gh-106189
* gh-106190

**Comment by gvanrossum** [comment]
It seems reasonable to return None in this case, maybe the docs need to be updated?

**Comment by Dreamsorcerer** [comment]
OK, mainly wanted to confirm this wasn't deemed a bug before updating typeshed, but a doc update would be good too.

**Comment by Dreamsorcerer** [comment]
I would note that aiohttp seems to already expect a bunch of exceptions from this function, so I think it'd be simpler for us if there was an exception here. But, I'm not really familiar with the code, so I don't have a strong opinion. If you want to stick with the current behaviour, I've made a PR for the documentation: #105995

**Comment by kumaraditya303** [comment]
Have you investigated why aiohttp ends up passing a closing transport?

**Comment by Dreamsorcerer** [comment]
I've not figured that out, but one cause might be something to do with the TLS-in-TLS proxy code. But, I guess client disconnection can happen at any time, so maybe it's just something that we'd expect to happen on the rare occasion, even when everything is working correctly.
There's various bits of information from different users in:
https://github.com/aio-libs/aiohttp/issues/6239
https://github.com/aio-libs/aiohttp/issues/3355

**Comment by kumaraditya303** [comment]
Okay, the PR is merged now.
