### ISSUE TITLE
C API: Add PyWeakref_GetRef() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#105927]
PyWeakref_GET_OBJECT() and PyWeakref_GetObject() return a borrowed reference to the object, or a borrowed reference to None if the object has been finalized. This API is error-prone and not easy to use.

This API was discussed in 2016: https://mail.python.org/archives/list/python-dev@python.org/thread/6BIPI4MCMAZFLJNIZB4JLTBW2COCACQQ/

I propose adding a new PyWeakref_GetRef() C API function which returns a new strong reference to the object, or NULL if the object has been finalized.

### Linked PRs
* gh-105928
* gh-105929
* gh-105932
* gh-105961
* gh-105963
* gh-105964
* gh-105965
* gh-105966
* gh-105971
* gh-105992
* gh-105997
* gh-106001
* gh-106002
* gh-106006
* gh-106007
* gh-106561
* gh-117091

**Comment by erlend-aasland** [comment]
> [...] or NULL if the object has been finalized.

With an error set? If no, would you need to call `PyErr_Occurred()` to find out if an error has occurred? See also capi-workgroup/problems#1

**Comment by vstinner** [comment]
> With an error set? If no, would you need to call PyErr_Occurred() to find out if an error has occurred? See also https://github.com/capi-workgroup/problems/issues/1

No error is set. See PR #105929 for the first part of the implementation.

**Comment by erlend-aasland** [comment]
> No error is set. See PR #105929 for the first part of the implementation.

Would it be better to return None if the object has been finalized? The idiom is that APIs returning a `PyObject` pointer only will return `NULL` in case of error.

**Comment by vstinner** [comment]
> Would it be better to return None if the object has been finalized? The idiom is that APIs returning a PyObject pointer only will return NULL in case of error.

It's possible to return a strong reference to None if the reference is dead. But it makes the API harder to handle since you have to handle Py_None reference count in the "dead reference" code path.

In Python 3.12, Py_None is immortal. But I plan to add PyWeakref_GetRef() to https://pythoncapi-compat.readthedocs.io/ and on Python 3.11 and older, you have to carefully Py_DECREF(Py_None).

**Comment by encukou** [comment]
Consider making this `int PyWeakref_GetRef(PyObject *weakref, PyObject **value)`, returning -1 on error (with exception set), 0 on dead reference, and 1 for success (with `value` set).
See https://github.com/capi-workgroup/problems/issues/1 and especially https://github.com/python/cpython/issues/105201#issuecomment-1578342058 for discussion.

**Comment by vstinner** [comment]
The proposed function cannot fail. If you use it on the wrong type, it does crash instead.

**Comment by encukou** [comment]
I see. Different reasoning then.
Please don't add infallible functions to the stable ABI. There is a possiblity that it will need to fail in the future.

**Comment by erlend-aasland** [comment]
I agree with Petr; if the internals of the API changes in the future, it would be unfortunate if we also had to add a `PyWeakRef_GetRefWithError` API as well. However, we take this possibility in account, when designing new APIs.

**Comment by erlend-aasland** [comment]
See also https://github.com/capi-workgroup/problems/issues/20

**Comment by vstinner** [comment]
I'm trying to fix race conditions by avoiding borrow references. If the API is modified so it can raise an exeption, it means that all callers must be updated to handle exceptions? That sounds like a lot of work.

I don't see the point of making the API so it can raise an exeption, if there is no known case where it can happen.

I would prefer to not modify PyWeakref_GetRef() to emit a cute exception if the argument is not a weak reference. I prefer to move this responsibility to the caller. The Modules/_abc.c code is an interesting example: it handles the rare case if an object which is not a weakref landed in the container.

I would prefer to have an API simple to use when the caller controls the argument object type.

**Comment by encukou** [comment]
> I'm trying to fix race conditions by avoiding borrow references. If the API is modified so it can raise an exeption, it means that all callers must be updated to handle exceptions? That sounds like a lot of work.

Yes.

> I would prefer to have an API simple to use when the caller controls the argument object type.

Please don't add it to the stable ABI. Maintaining that for decades is also a lot of work, and avoiding the work now means we'll pay in the future.

> I would prefer to not modify PyWeakref_GetRef() to emit a cute exception if the argument is not a weak reference.

That's not necessary.
I'm asking for it to be possible to add an error case in the future. For example, on an implementation that uses tagged pointers, you could get a `MemoryError` when getting the object.

**Comment by vstinner** [comment]
Ok, Erlend and Petr convinced me, I updated my PR to use the API:

```
int PyWeakref_GetRef(PyObject *ref, PyObject **pobj)
```

**Comment by vstinner** [comment]
Should we deprecate PyWeakref_GetObject() and PyWeakref_GET_OBJECT() which return an unsafe borrowed reference?

**Comment by erlend-aasland** [comment]
> Should we deprecate PyWeakref_GetObject() and PyWeakref_GET_OBJECT() which return an unsafe borrowed reference?

I would be in favour of that.

**Comment by vstinner** [comment]
Oh, [PEP 703 – Making the Global Interpreter Lock Optional in CPython](https://peps.python.org/pep-0703/) proposes PyWeakref_FetchObject() which is more or less the PyWeakref_GetRef() function that was just added to Python 3.13.

**Comment by vstinner** [comment]
I added ``PyWeakref_GetRef()`` functions and deprecated PyWeakref_GetObject() and PyWeakref_GET_OBJECT() functions. I close the issue.
