### ISSUE TITLE
Documentation for pathlib.Path.symlink_to is incorrectly constrained

### ISSUE THREAD

**Issue by jaraco** [python/cpython#105900]
# Documentation

The docs for `symlink_to` state:

>  _target_is_directory_ must be true (default `False`) if the link’s target is a directory.

That's not precisely correct. I experimented and `symlink_to` seems to follow the same behavior as [os.symlink](https://docs.python.org/3/library/os.html#os.symlink), which provides the correct (though more complicated) guidance:

>  If the target is present, the type of the symlink will be created to match. Otherwise, the symlink will be created as a directory if _target_is_directory_ is `True` or a file symlink (the default) otherwise.

That is, both calls will infer the type of the target if it's present. The caller need not pass _target_is_directory_ if the target is an extant directory. The `symlink_to` documentation is misleading and incorrect.

### Linked PRs
* gh-114035
* gh-114464
* gh-114465

**Comment by jaraco** [comment]
As a demo:

```
 ~ $ import os, pathlib
 ~ $ os.name
'nt'

 ~ $ pathlib.Path('foo').mkdir()
 ~ $ pathlib.Path('bar').symlink_to('foo')
 ~ $ os.path.isdir('bar')
True
```

**Comment by barneygale** [comment]
Fixed!
