### ISSUE TITLE
C API: Remove PyObject_Init() return value

### ISSUE THREAD

**Issue by vstinner** [python/cpython#105944]
PyObject_Init(), PyObject_INIT(), PyObject_InitVar() and PyObject_INIT_VAR() return their argument which is technically a borrowed reference. For me, this API is really surprising. Why would someone like to rely on the return value, since the result is already known: it's the input argument?

I propose to **remove the return value** of these 4 PyObject "INIT" functions.

---

On PyPI top 5,000 projects (2023-04-13), I found 3 projects using these functions, but **none are affected by proposed change**:

* Cython (0.29.34)
* pyjson5 (1.6.2)
* boost-python copy by scipy 1.10.1

I searched for ``PyObject_INIT`` regex.

**Cython is not affected**, since it already ignores the result explicitly:

```c
code.putln("(void) PyObject_INIT(o, t);")
```

There is also boost-python (used by scipy 1.10.1) which defines PyObject_INIT() if it's not defined... for Python 1.x :-) **Python 3 is not affected**.

```c
#if !defined(PY_MAJOR_VERSION) || PY_MAJOR_VERSION < 2
# define PyObject_INIT(op, typeobj) \
        ( (op)->ob_type = (typeobj), _Py_NewReference((PyObject *)(op)), (op) )
#endif
```

pyjson5 (1.6.2) declares ``PyObject_INIT()`` and ``PyObject_InitVar()`` functions in a Cython binding... without using them. So **it's not affected neither**.

```c
cdef extern from 'Python.h':
    # ...
    object ObjectInit 'PyObject_INIT'(PyObject *obj, type cls)
    PyVarObject *ObjectInitVar 'PyObject_InitVar'(PyVarObject *obj, type cls, Py_ssize_t size)
    object PyLong_FromString(const char *str, char **pend, int base)
    # ...
```

**Comment by vstinner** [comment]
Hum, wait. It's part of the stable ABI, so we cannot just remove the return value without breaking the stable ABI :-(

**Comment by vstinner** [comment]
Another option is to deprecate this function, but Cython currently uses it to implement a freelist optimization in ``ModuleNode.generate_new_function()`` of ``Cython/Compiler/ModuleNode.py``.

**Comment by vstinner** [comment]
Existing replacement APIs:

* ``PyObject_New()`` (and ``_PyObject_New()``) calls ``PyObject_Malloc()`` and ``PyObject_Init()``.
* ``PyType_GenericAlloc()`` (and ``_PyType_AllocNoTrack()``) calls ``PyObject_Malloc()``, ``_PyObject_Init()`` or ``_PyObject_InitVar()``, and ``_PyObject_GC_TRACK()``.

**Comment by ronaldoussoren** [comment]
Isn't the borrowed reference harmless here because, as you write, the return value always is the first argument?

The return value allows you to write ``return PyObject_Init(someValue, someType);`` which can lead to slightly more compact code.

**Comment by erlend-aasland** [comment]
> The return value allows you to write `return PyObject_Init(someValue, someType);` which can lead to slightly more compact code.

As a data point, `memset`, `strcpy`, `strcat` and company all return their first argument so you can use them for call chaining.

**Comment by vstinner** [comment]
It seems quite difficult to change, deprecate, and/or remove this function. I don't think that it's worth it to change its return value, so I just close the issue. I missed the fact that it's part of the stable ABI.
