### ISSUE TITLE
random.choices fails with a mysterious bug when population is empty

### ISSUE THREAD

**Issue by pandaninjas** [python/cpython#105957]
# Bug report
random.choices fails with a mysterious bug when population is None
```sh
pandaninjas@kaptop:~$ python
Python 3.10.6 (main, Mar 10 2023, 10:55:28) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import random
>>> random.choices([])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/random.py", line 519, in choices
    return [population[floor(random() * n)] for i in _repeat(None, k)]
  File "/usr/lib/python3.10/random.py", line 519, in <listcomp>
    return [population[floor(random() * n)] for i in _repeat(None, k)]
IndexError: list index out of range
```
# Your environment

- CPython versions tested on: 3.10.6
- Operating system and architecture: Ubuntu

# Solution:
Check if list length is zero and immediately fail if it is

**Comment by arhadthedev** [comment]
@rhettinger (as a `random` module [expert](https://devguide.python.org/core-developers/experts/#stdlib))

**Comment by terryjreedy** [comment]
The 3.13 REPL is a little clearer.
```
    return [population[floor(random() * n)] for i in _repeat(None, k)]
            ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```
But if one passed a list by name, such as `mypop`, that one expected to be non-empty, this would be less clear.

**Comment by sobolevn** [comment]
> when population is None

Sorry, but it is not `None`, it is empty. These two are different :)

> random.choices fails with a mysterious bug

I think that this is a correct thing to do, please take a look at the docs here: https://docs.python.org/3/library/random.html#random.choices

It says:

> Return a k sized list of elements chosen from the population with replacement. If the population is empty, raises [IndexError](https://docs.python.org/3/library/exceptions.html#IndexError).

I think that this is not a bug.

**Comment by rhettinger** [comment]
> I think that this is not a bug.

I concur.  This is working as documented.

**Comment by alexjbest** [comment]
While I agree this is working as documented, having the same error type as `random.sample` when provided an empty list (i.e. a `ValueError` which seems more appropriate anyway) would be a convenience for the end user switching between these functions.

**Comment by terryjreedy** [comment]
If we were writing the function today, we very well might catch the IndexError and raise a ValueError with a new message.  But having documented the IndexError, we are sort of stuck with it, as a change would break code that depends on the documented exception.

**Comment by alexjbest** [comment]
> If we were writing the function today, we very well might catch the IndexError and raise a ValueError with a new message.  But having documented the IndexError, we are sort of stuck with it, as a change would break code that depends on the documented exception.

Makes sense, thanks for the explanation!
