### ISSUE TITLE
Crash in `_asyncio._swap_current_task` due to improper reference counting

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#105987]
First appeared in a474e04388c2ef6aca75c26cb70a1b6200235feb, where given function was introduced.

Repro:
```python
import _asyncio

class DummyLoop:
    pass

class DummyTask:
    pass

l = DummyLoop()
_asyncio._swap_current_task(l, DummyTask())
t = _asyncio._swap_current_task(l, None)
```
Output:
```
Modules/gcmodule.c:461: visit_decref: Assertion "!_PyObject_IsFreed(op)" failed
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x7fedad081130
object refcount : 1
object type     : 0x55f665a81fe0
object type name: dict
object repr     : Segmentation fault (core dumped)
```

I'm working on a fix.

### Linked PRs
* gh-105989
* gh-106099
* gh-139538
* gh-139539

**Comment by vstinner** [comment]
@kumaraditya303: test_issue105987() of test_asyncio.test_eager_task_factory is skipped since February, since commit 09fe550ecc392927133e3f91856c630d1310ccdb. What's the status of this test? Should it be fixed or removed?

**Comment by kumaraditya303** [comment]
> What's the status of this test? Should it be fixed or removed?

Fixed it at https://github.com/python/cpython/pull/139538, thanks @vstinner for the reminder.
