### ISSUE TITLE
match-case reports type error

### ISSUE THREAD

**Issue by yanghao** [python/cpython#105986]
Is this allowed for match-case statement:

```
c = 5

match c:
    case int('101', 2):
        print('matched')

```

This code produces below error:
```
Traceback (most recent call last):
  File "/home/yanghao/git/misc/tt.py", line 6, in <module>
    case int('101', 2):
          ^^^^^^^^^^^^^
TypeError: int() accepts 1 positional sub-pattern (2 given)
```

Of course, when replacing with "x = int('101', 2)" and then "case x:" everything is working:

```
c = 5
x = int('101', 2)
match c:
    case x:
        print('matched')

```

But this is not working as I thought how it is working. As soon as another case statement is added, it breaks again:
```
c = 5
x = int('101', 2)
match c:
    case x:
        print('matched')
    case 6:
        print('6')

```

which generates:
```

  File "/home/yanghao/git/misc/tt.py", line 4
    case x:
         ^
SyntaxError: name capture 'x' makes remaining patterns unreachable
```

It seems, I can match a constant in the "case a_constant" statement, but I cannot match a constant that is referred by a variable, e.g. using name "x" in above code. In reality, many long/complex constants (e.g. math.pi) can only be referred using a variable name. Is there any way to do constant matching through a variable?

**Comment by ronaldoussoren** [comment]
``case x`` matches all values and captures the value as ``x`` for use in the case statement. You can use a named constants as a pattern to match, but only if it is a dotted name, e.g.

```python3
match c:
   case math.pi:
      print("π!")
```

**Comment by carljm** [comment]
And an expression like `int("101", 2)` as a match pattern specifies a type and a set of attribute values to match, it does not actually call `int` to construct an int instance to match against.

I don't see anything here that isn't behaving as designed and documented. Please refer to the documentation for the match statement: https://docs.python.org/3/tutorial/controlflow.html#tut-match

**Comment by terryjreedy** [comment]
@yanghao  Questions about 'is my problem due to a CPython bug' should first be asked elsewhere, such as https://discuss.python.org/c/users/7. The Bug Report template said a bit more.

**Comment by yanghao** [comment]
> `case x` matches all values and captures the value as `x` for use in the case statement. You can use a named constants as a pattern to match, but only if it is a dotted name, e.g.
> 
> ```python
> match c:
>    case math.pi:
>       print("π!")
> ```

Thanks @ronaldoussoren . This helps. It seems the match-case in Python is more peculiar than I thought.
