### ISSUE TITLE
itertools.chain.from_iterable can exhaust the C stack

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#105960]
Reproducer:

```
import itertools

def f(xs):
    m = map(f, xs)
    return itertools.chain.from_iterable(m)

list(f("a"))
```

### Linked PRs
* gh-105962

**Comment by pablogsal** [comment]
Closing. See https://github.com/python/cpython/pull/105962#issuecomment-1601319903

**Comment by terryjreedy** [comment]
On Windows 10, the example results in the Python process, batch or interactive, closing in about 2 seconds, without an error message, but also without the Windows process error box.  (This is the usual equivalent of a *nix stackoverflow crash.)   My guess is a MemoryError that could not be displayed.  IDLE just restarts a new user execution process and '>>>' prompt.  FWIW, I pretty much agree with Raymond's comment and closing.
