### ISSUE TITLE
Behaviour change in py312 for protocols with non-callable members and custom `__subclasshook__` methods

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#105974]
# Bug report

On Python 3.11:

```pycon
>>> from typing import *
>>> @runtime_checkable
... class Foo(Protocol):
...     x = 1
...     @classmethod
...     def __subclasshook__(cls, other):
...         return hasattr(other, 'x')
...
>>> issubclass(object, Foo)
False
```

On Python 3.12:

```pycon
>>> from typing import *
>>> @runtime_checkable
... class Foo(Protocol):
...     x = 1
...     @classmethod
...     def __subclasshook__(cls, other):
...         return hsattr(cls, 'x')
...
>>> issubclass(object, Foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\typing.py", line 1829, in __subclasscheck__
    raise TypeError(
TypeError: Protocols with non-method members don't support issubclass()
```

I think I prefer the Python 3.11 behaviour here, since the whole point of allowing protocols to define custom `__subclasshook__` methods is so that users can customise how `issubclass()` works on user-defined protocols.

### Linked PRs
* gh-105976
* gh-106032

**Comment by AlexWaygood** [comment]
> I think I prefer the Python 3.11 behaviour here, since the whole point of allowing protocols to define custom `__subclasshook__` methods is so that users can customise how `issubclass()` works on user-defined protocols.

There _is_ an argument that this behaviour change should be considered a feature rather than a bug. Mypy will complain about `issubclass()` checks against protocols with non-callable members, whether or not a custom `__subclasshook__` method is defined: https://mypy-play.net/?mypy=latest&python=3.11&gist=83529c67737e01d8d837b700012e763b.

**Comment by AlexWaygood** [comment]
> There _is_ an argument that this behaviour change should be considered a feature rather than a bug.

@JelleZijlstra, thoughts on this? Is there a case that the new behaviour should be considered a feature rather than a bug?

**Comment by JelleZijlstra** [comment]
I think the new behavior is a bug; we shouldn't be clobbering people's `__subclasshook__` if they explicitly set one. It's fine if mypy rejects such classes as it's static, but the runtime can be more lenient.

**Comment by AlexWaygood** [comment]
SGTM
