### ISSUE TITLE
Support private mode in webbrowser

### ISSUE THREAD

**Issue by kr-g** [python/cpython#105983]
# Feature or enhancement

support of webbrowser incognito / private browsing 

# Pitch

modern webbrowsers offer to open an url in a data privacy protected mode.

open an url is done by calling 

> `open(url, new=0, autoraise=True)`

here giving new=3 will indicate to open the url in data privacy mode

# Previous discussion

na

### Linked PRs
* gh-105984
* gh-106069

**Comment by hugovk** [comment]
Closing as duplicate of the earlier https://github.com/python/cpython/issues/77119.
