### ISSUE TITLE
Isolate the `_decimal` extension module

### ISSUE THREAD

**Issue by CharlieZhao95** [python/cpython#106078]
This issue is used to track the PRs split from [gh-103092](https://github.com/python/cpython/pull/103381). Isolate the `_decimal` extension module by: 

* Establish a global module state and convert static types to heap types
* Move other global static variables to the global module state(possibly multiple PRs)
  - [x] DecimalException
  - [x] basic_context_template
  - [x] tls_context_key
  - [x] cached_context
  - [x] current_context_var
  - [x] default_context_template
  - [x] extended_context_template
  - [x] round_map
  - [x] Rational
  - [x] SignalTuple
  - [x] External C-API functions
* Convert the global module state to true module state
  - [x] signal_map
  - [x] cond_map
  - [x] convert global state to module state

See original issue [Isolate Stdlib Extension Modules](https://github.com/python/cpython/issues/103092)  and [PEP-687](https://peps.python.org/pep-0687/) for details.

### Linked PRs
* gh-106079
* gh-106301
* gh-106346
* gh-106395
* gh-106475
* gh-106616
* gh-106880
* gh-107287
* gh-107524

**Comment by erlend-aasland** [comment]
What is your next step, @CharlieZhao95?

**Comment by CharlieZhao95** [comment]
> What is your next step, @CharlieZhao95?

I think next we can move the remaining static global PyObject to `global_state`:

* DecimalException
* basic_context_template
* current_context_var
* default_context_template
* extended_context_template
* round_map
* Rational
* SignalTuple
* _External C-API functions_

This shouldn't be too complicated. The only question is whether we should move these _external-API functions_, which simply hold function pointers used by **numeric types**, such as `nb_multiply`, `nb_floor_divide` and so on. They will not change during the lifecycle of the program.

**Comment by erlend-aasland** [comment]
Pick the low-hanging fruit first. It is better with multiple small PRs than one big.

**Comment by CharlieZhao95** [comment]
> Pick the low-hanging fruit first. It is better with multiple small PRs than one big.

Okay! let's go step by step. I will put the objects listed above into multiple small PRs.

**Comment by CharlieZhao95** [comment]
The second stage has been completed. All documented static variables are moved to the global state. Thanks for review! @erlend-aasland @kumaraditya303 

Based on the experience of the original PR, we should also move the `signal_map` into the module state before converting the global state. This array of structures contains potentially global variables(`ex`).

```c
typedef struct {
    const char *name;   /* condition or signal name */
    const char *fqname; /* fully qualified name */
    uint32_t flag;      /* libmpdec flag */
    PyObject *ex;       /* corresponding exception */
} DecCondMap;

static DecCondMap signal_map[] = {
    ...
}
```

IMO, the next stage should be:

1. Move `signal_map` to global state
2. Convert the global module state to true module state

How about opening a draft PR (convert the global module) first? This will allow us to see failed test cases raised by `signal_map` more clearly. Or do I just start moving `signal_map` into global state?

**Comment by erlend-aasland** [comment]
> How about opening a draft PR (convert the global module) first? This will allow us to see failed test cases raised by `signal_map` more clearly. Or do I just start moving `signal_map` into global state?

FTR, I often open PRs on my own fork to check CI issues, so that I won't pollute the CPython PR list too much.

Also: I'll be away for the rest of summer, so my response time will probably be slower than usual, just so you know :)

**Comment by erlend-aasland** [comment]
Great work, @CharlieZhao95 and @kumaraditya303!
