### ISSUE TITLE
Add chdir to pathlib.Path

### ISSUE THREAD

**Issue by jb2170** [python/cpython#106094]
# Feature or enhancement

The `pathlib` module gives a nice OOP way of interacting with filesystems. The `Path` class implements methods for syscalls such as `stat`, `rmdir`, `unlink` etc which correspond to calling their counterpart in the `os` module. One missing method however is `chdir`.

# Pitch

Currently to `chdir` into a `Path` instance `p` one has to use `os.chdir(p)`, which may require an extra import of `os` in one's script just for this single function. With the proposed additions one could instead use `p.chdir()` similar to any other method such as `p.lstat()`. 

### Linked PRs
* gh-106095

**Comment by jb2170** [comment]
I was inspired by wanting to use 

```py
Path(__file__).parent.chdir()
```

at the beginning of one of my scripts so all actions are relative to a well-defined directory (symlinks aside), similar to how `make` treats targets to be relative to the `Makefile` file. I'm currently compromising with 

```py
os.chdir(Path(__file__).parent)
```

**Comment by eryksun** [comment]
A counter argument is that having to use `os.chdir(p)` makes for a useful distinction since `chdir()` affects the entire process.

**Comment by jb2170** [comment]
That's the same first response that I received discussing this in a Discord server, use of `os.chdir` having an effective lifespan longer than the `Path` instance's lifespan. I had similar thoughts about `os.chroot` too.

Thanks for the second opinion (and everyone who :+1: the comment). Now closing this issue / PR and leaving the commits for the record.

**Comment by barneygale** [comment]
Thanks for the suggestion all the same!
