### ISSUE TITLE
asyncio: Confusing TimeoutError

### ISSUE THREAD

**Issue by prabhu-yu** [python/cpython#106068]
In many example code in the URL [Coroutines and Tasks](https://docs.python.org/3.13/library/asyncio-task.html), TimeoutError exception is caught using 
```python
except TimeoutError
```
But it should be 
```python
except asyncio.TimeoutError
```
Also, not all hyperlinks to `TimeoutError` points to the
asyncio.TimeoutError, but to the standard TimeoutError

**Comment by sunmy2019** [comment]
They are the same thing.

https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.TimeoutError

**Comment by prabhu-yu** [comment]
Thank you, I was not aware of this.
Further, it says "A deprecated alias of [TimeoutError](https://docs.python.org/3/library/exceptions.html#TimeoutError)". 
So, 3.11.4 revision, I still see the many reference of asyncio.TimeoutError.
This should be simply TimeoutError as former one is deprecated.
Please let me know if I am correct.

**Comment by sunmy2019** [comment]
Yes

Docs can be updated if any one is willing to make a PR.

**Comment by hugovk** [comment]
Thanks for the report.

Docs fixed in https://github.com/python/cpython/pull/106136 and backported in https://github.com/python/cpython/pull/106179 and https://github.com/python/cpython/pull/106180.

**Comment by pullagad** [comment]
> Thanks for the report.
> 
> Docs fixed in #106136 and backported in #106179 and #106180.

You are welcome.
