### ISSUE TITLE
PyDict_GetItem and PyObject_HasAttr should not be used

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#106033]
These functions are broken by design, because they discard any exceptions raised inside, including MemoryError and KeyboardInterrupt. There were several rounds of getting rid of them in past (for example 567eba1852ed89e5cf93dbce33f7e2ca73e8f05d, #11112, #75753), but they occur in new code.

### Linked PRs
* gh-106034
* gh-106040
* gh-106041
* gh-106044
* gh-106047
* gh-106070
* gh-106071
* gh-106228

**Comment by iritkatriel** [comment]
See also https://github.com/python/cpython/issues/86172.

**Comment by vstinner** [comment]
See also the issue #106004: I propose adding PyDict_GetItemRef() function which doesn't have these flaws.

**Comment by erlend-aasland** [comment]
Can this be closed, or do you expect more work here, @serhiy-storchaka?
