### ISSUE TITLE
Wrong type annotation skipping code execution

### ISSUE THREAD

**Issue by mahirchavda** [python/cpython#106015]
# Bug report
Because of the wrong type annotation, python is not executing the code line.

This program generates `KeyError: 'hello'`
```python
data = {}
data['hello']
print(data)
```
If I add wrong type annotation, It is skipping the second code line. Program runs without any error.
```python
data = {}
data['hello']:int
print(data)
```

My understanding is that type safety is not a real thing in python. It's just to make code more readable and detect bugs at early stage. Based on that understanding, python should not skip code just because I mentioned wrong type in the code. Feel free to correct me.

###  Conversation on Slack for reference
Link: https://pythondev.slack.com/archives/C07EFMZ1N/p1687502170353849
![image](https://github.com/python/cpython/assets/123979186/2d5fc38f-c83f-4cd1-86da-ce95150bd0f7)

# Your environment

- CPython versions tested on: **Python 3.9.16**
- Operating system and architecture: **Amazon Linux (x86_64)**

**Comment by sku2000** [comment]
It's allowed in [pep 526](https://peps.python.org/pep-0526/#annotating-expressions).
```python
d = {}
d['a']: int = 0  # Annotates d['a'] with int.
d['b']: int      # Annotates d['b'] with int.
```

**Comment by shahid-0** [comment]
> It's allowed in [pep 526](https://peps.python.org/pep-0526/#annotating-expressions).
> 
> ```python
> d = {}
> d['a']: int = 0  # Annotates d['a'] with int.
> d['b']: int      # Annotates d['b'] with int.
> ```

But it's not doing its job well I think, I've tried type hinting but not working as we want. @sku2000 
![image](https://github.com/python/cpython/assets/81429750/f492d64d-fe19-4377-8c6f-ba9b07bed7e4)

**Comment by ericvsmith** [comment]
Without an assignment, this line with the annotation is “mostly” ignored at runtime. See the last item in https://peps.python.org/pep-0526/#rejected-postponed-proposals for an indirect reference to this. 

I couldn’t find where this is documented, but I recall a previous discussion about it.

**Comment by sobolevn** [comment]
It is explicitly listed as an example in https://peps.python.org/pep-0526/#annotating-expressions

It is required to annotate things that might not be there.

**Comment by ericvsmith** [comment]
@sobolevn thanks for finding that.

This should be in the Python documentation somewhere, not just in the PEP. Also, the proposed documentation should be clear that it's annotating a value that doesn't yet exist, and that annotating something that doesn't yet exist isn't an error. I realize the example implies that the code works, but the intent should be explicit.

Hopefully someone will find where it does already exist in the docs, and we can close this issue.

**Comment by sobolevn** [comment]
That's @sku2000's message I implicilty quote :)

Yes, docs change is a good idea! 👍

**Comment by mahirchavda** [comment]
Thanks for looking into the issue. After reading the pep doc and going through examples. It's clear and makes sense. `d['xyz']: int` is just an annotation unless you assign the value like `d['xyz']: int = 1`
