### ISSUE TITLE
Make implicit boolean conversions explicit

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#106008]
...as discussed in https://github.com/faster-cpython/ideas/issues/568.

By adding a dedicated instruction for converting values to bool, we can easily specialize the conditions of all remaining branches in the bytecode while keeping the branches themselves as "dumb" and simple as possible.

This is one of the few remaining common cases where a little specilization will give us a lot of useful information (such as "this branch won't execute arbitrary code") for higher tiers of optimization. Plus, the most common specializations (such as for `bool` or `None`) will be effectively no-ops.

### Linked PRs
* gh-106003
* gh-106367

**Comment by pablogsal** [comment]
@brandtbucher Apparently this PR introduced a refleak in test_grammar:

```
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 14.52 Run tests sequentially
0:00:00 load avg: 14.52 [1/1] test_grammar
beginning 9 repetitions
123456789
.........
test_grammar leaked [2, 2, 2, 2] references, sum=8
test_grammar leaked [2, 2, 2, 2] memory blocks, sum=8
test_grammar failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_grammar

Total duration: 349 ms
Tests result: FAILURE
```

**Comment by brandtbucher** [comment]
Huh. Yeah, I'll take a look.

**Comment by brandtbucher** [comment]
Ah, I think I found it.
