### ISSUE TITLE
 Class 'Category' has no 'objects' memberPylintE1101:no-member

### ISSUE THREAD

**Issue by zainyousaf099** [python/cpython#106056]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

@alex 
I'm playing with Python Django in 3.11.3 and the code from .models import Category

def menu_links(request):
    links = Category.objects.all()
    return dict(links=links)
 is showing error

-->Class 'Category' has no 'objects' memberPylint[E1101:no-member](https://pylint.readthedocs.io/en/latest/user_guide/messages/error/no-member.html) 

but in 3.9.11 I have for some project the code shows no error 

but there is one more thing the code show error in 3.11.3 but code is running correctly also in it but showing an error for no code  exit

**Comment by Eclips4** [comment]
Hello!
How it is related to CPython?

**Comment by lightdrk** [comment]
need more details , for above

**Comment by ronaldoussoren** [comment]
This appears to be an issue with using Django. Please ask about this on the Django forums (https://forum.djangoproject.com/).
