### ISSUE TITLE
fsencode and fsdecode() ignore `sys._enablelegacywindowsfsencoding()`

### ISSUE THREAD

**Issue by methane** [python/cpython#106042]
`sys._enablelegacywindowsfsencoding()` changes fsencoding from "utf-8" to "mbcs".

But `os.fsencode()` and `os.fsdecode()` caches the output of `sys.getfilesystemencoding()` and `sys.getfilesystemencodeerrors()`. See here:

https://github.com/python/cpython/blob/1d33d5378058671bfabb6f4d4b5bfd4726973ff9/Lib/os.py#L808-L839

User need to call `sys._enablelegacywindowsfsencoding()` before importing os module. It is too difficult.

Interestingly, Mercurial import os before calling it. And they use fsencode/fsdecode. So I think they have a bug since they start Python 3 support. I hope I am wrong.

https://repo.mercurial-scm.org/hg/file/tip/mercurial/pycompat.py#l118

AFAIK, Mercurial is the only user of `sys._enablelegacywindowsfsencoding()`.
If they can enable legacy fs encoding with envvar or C API, I think we should deprecate the `sys._enablelegacywindowsfsencoding()`.

**Comment by methane** [comment]
Mercurial uses the `PYTHONLEGACYWINDOWSSTDIO` envvar.
I hope they can use `PYTHONLEGACYWINDOWSFSENCODING` instead of `sys._enablelegacywindowsfsencoding` too.

```
Mercurial-42f761e97dec> rg PYTHONLEGACYWINDOWS
mercurial/exewrapper.c
51:	_wputenv(L"PYTHONLEGACYWINDOWSSTDIO=1");

contrib/win32/hg.bat
7:set PYTHONLEGACYWINDOWSSTDIO=1

tests/run-tests.py
1456:            env['PYTHONLEGACYWINDOWSSTDIO'] = '1'
```

**Comment by methane** [comment]
@indygreg fixed this bug in Mercurial by replacing `os.fsencode()` with `a.encode("mbcs", "ignore")`.

https://repo.mercurial-scm.org/hg/rev/00e0c5c06ed5

**Comment by methane** [comment]
Mercurial uses `os.fsencode()` a lot.
If we *fix* the `os.fsencode()` to reflect `sys._enablelegacywindowsfsencoding()`, it may *break* Mercurial.

I think we should document and deprecate `sys._enablelegacywindowsfsencoding()` instead of fixing it.

**Comment by MonadChains** [comment]
According to [vstinner's](https://github.com/vstinner) [search_pypi_top.py](https://github.com/vstinner/misc/blob/main/cpython/search_pypi_top.py), there are only 4 reference `_enablelegacywindowsfsencoding` in the top 5000 mypy packages with 3 simple placeholder functions:
```python
def _enablelegacywindowsfsencoding() -> None:
    ...

I believe that the function can be deprecate without major breaking problems

**Comment by methane** [comment]
This bug is duplicate of #73427.
