### ISSUE TITLE
C API: Add PyDict_GetItemRef() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106004]
The PyDict C API has a bad history. PyDict_GetItem() ignores all exception: error on hash(), error on "key == key2", KeyboardInterrupt, etc. PyDict_GetItemWithError() was added to fix this design. Moreover, Python 3.9 and older allowed to call PyDict_GetItem() with the GIL released.

PyDict_GetItem() returns a borrowed reference which is usually safe since the dictionary still contains a strong reference to the request value. But in general, borrowed references are error prone and can likely lead to complex race conditions causing crashes:

* "Functions must not return borrowed references" says https://devguide.python.org/developer-workflow/c-api/index.html
* https://github.com/capi-workgroup/problems/issues/5

While ``PyDict_GetItem()`` calls can be quite easily replaced with ``PyObject_GetItem()`` which has a better API (return a new stong reference), developers usually prefer to still use the specialized PyDict API for best performance: avoid the minor overhead of type dispatching, ``Py_TYPE(obj)->tp_as_mapping->mp_subscript``.

I propose adding ``PyDict_GetItemRef()`` and ``PyDict_GetItemStringRef()`` functions to the limited C API (version 3.13): replacements for ``PyDict_GetItem()``, ``PyDict_GetItemWithError()`` and ``PyDict_GetItemString()``.

API:

```
int PyDict_GetItemRef(PyObject *mp, PyObject *key, PyObject **pvalue);
int PyDict_GetItemStringRef(PyObject *mp, const char *key, PyObject **pvalue);
```

``PyDict_GetItemWithError()`` has another API issue: when it returns NULL, it can mean two things. It returns NULL if the key is missing, but it also returns NULL on error. The caller has to check ``PyErr_Occurred()`` to distinguish the two cases (to write correct code). See https://github.com/capi-workgroup/problems/issues/1 Proposed API avoids this by returning an ``int``: return -1 on error, or return 0 otherwise (present or missing key). Checking ``PyErr_Occurred()`` is no longer needed.

By the way, the public C API has no PyDict_GetItem**String**WithError() function: using ``PyDict_GetItemWithError()`` with a ``char*`` key is not convenient. The ``_PyDict_GetItemStringWithError()`` function exists but it's a private C API.

### Linked PRs
* gh-106005
* gh-107229

**Comment by vstinner** [comment]
Example of ``PyDict_GetItemRef()`` usage of the function, replacing ``PyDict_GetItemWithError()``:

```diff
@@ -5146,13 +5191,12 @@ dictitems_contains(_PyDictViewObject *dv, PyObject *obj)
         return 0;
     key = PyTuple_GET_ITEM(obj, 0);
     value = PyTuple_GET_ITEM(obj, 1);
-    found = PyDict_GetItemWithError((PyObject *)dv->dv_dict, key);
+    if (PyDict_GetItemRef((PyObject *)dv->dv_dict, key, &found) < 0) {
+        return -1;
+    }
     if (found == NULL) {
-        if (PyErr_Occurred())
-            return -1;
         return 0;
     }
-    Py_INCREF(found);
     result = PyObject_RichCompareBool(found, value, Py_EQ);
     Py_DECREF(found);
     return result;
```

``PyErr_Occurred()`` and ``Py_INCREF()`` calls can be removed.

**Comment by vstinner** [comment]
See also my previous attempt in 2020: issue #86460 "Add new C functions with more regular reference counting like PyTuple_GetItemRef()".

**Comment by vstinner** [comment]
> There is no foreseeable future in which we'd go the other way towards all-borrowing-only APIs.

FYI I'm tracking the list of C API functions returning borrowed references at: https://pythoncapi.readthedocs.io/bad_api.html#functions

I'm trying to provide a replacement for each function, and if possible an efficient replacement. For example, PyDict_GetItem() can be replaced with PyObject_GetItem(), but it's less efficient (that's what I explained in my first message).

**Comment by serhiy-storchaka** [comment]
The only problem is that functions with so similar names have completely different interface. It is pretty confusing. Would not be better to name it `PyDict_LookupItem` or like? It may be worth to add also `PyMapping_LookupItem` for convenience. BTW, I think it is time to make `_PyObject_LookupAttr` public (if we agree about the name).

**Comment by vstinner** [comment]
I replied on the PR, since the discussion is ongoing there.

**Comment by serhiy-storchaka** [comment]
Tests will be added in #107179.
