### ISSUE TITLE
Type hinting not working on dictionary key value pair

### ISSUE THREAD

**Issue by shahid-0** [python/cpython#106018]
# Bug report

I see bug #106015 so I've tried to search about this bug to resolve this, then someone replied and mention this is allowed in [pep 256](https://peps.python.org/pep-0526/#annotating-expressions)
[link to the reply](https://github.com/python/cpython/issues/106015#issuecomment-1604043926)

After that, I tried by myself that type hinting, in pep 256 documentation if we write `d['a']: int = 0` then then `d['a']` will annotate with int, but it's not working as they mention in the docs.

I tried the below code:
```data = {}
>>> data['hello']: int = 'hello world'
>>> data
{'hello': 'hello world'}
>>> type(data['hello'])
<class 'str'>
>>> data['str_key']: str = 10
>>> data
{'hello': 'hello world', 'str_key': 10}
>>> type(data['str_key'])
<class 'int'>
```
As you can see I've selected the `int` type for `data['hello']: int` but assigned string and it did not arise any error.

# environment

- Python version: 3.11.3
- Operating system and architecture: Windows 11

**Comment by ericvsmith** [comment]
Type hints are not enforced at runtime, so this is not a bug. You need to run your code through a type checker, such as mypy, to catch this error.
