### ISSUE TITLE
test_basic_multiple_interpreters_deleted_no_reset() of test_imp/test_import leaks references

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106000]
The test_basic_multiple_interpreters_deleted_no_reset() test of test_import (previously in test_imp) leaks references but only when test_import is run with -jN option:

The test leaks since it was added by the commit bb0cf8fd60e71581a90179af63e60e8704c3814b at Feb 27.

Leak with ``-j1`` option:

```
$ ./python -m test -j1 -R 3:3 test_import -m test_basic_multiple_interpreters_deleted_no_reset 
test_import leaked [10, 10, 10] references, sum=30
```

No leak without the ``-j1`` option, magic!

```
$ ./python -m test -R 3:3 test_import -m test_basic_multiple_interpreters_deleted_no_reset 
(...)
Tests result: SUCCESS
```

cc @ericsnowcurrently

**Comment by sunmy2019** [comment]
It is to be fixed by https://github.com/python/cpython/pull/104796

> when run with -jN option

He let tests skipped if `-j` is in sys.args. You can see my PR for details and ongoing discussions.
