### ISSUE TITLE
Fatal error on SSL protocol - deque index out of range

### ISSUE THREAD

**Issue by mishunn** [python/cpython#106028]
Hello.
I am running a http/2 server using the 'h2' library (asyncio.Protocol via SSL) Python3.11.3 on Debian 11.6 (Also reprodice on Windows).

I have two streams open in one connection. In the first client sends audio to the server, in the second server sends service information to the client at the same time.

Everything works fine up to a certain point.
Sometimes there are moments when I send data to the client ( _SSLProtocolTransport.write), which starts 'SSLProtocol._do_write' and at the same moment 'buffer_updated' method is called, which calls 'SSLProtocol._do_write' via 'SSLProtocol._do_read'. Thus two 'SSLProtocol._do_write' are called at the same time. There is a simultaneous sending of data to the transport and an exception occurs during the removal of the '0' element from the deque 'self._write_backlog' (del self._write_backlog[0]). An exception is thrown - IndexError('deque index out of range').
Methods pause_reading and resume_reading do not help fix the error. 'SSLProtocol._do_write' called twice sometimes.

Is it possible to add some sort of synchronizer (lock for example) to 'SSLProtocol._do_write' (asyncio/sslproto.py) so that the deque is parsed sequentially?

**Comment by kumaraditya303** [comment]
You need to provide a reproducer for this preferably without third party dependencies.
