### ISSUE TITLE
`test_traceback` does not run one set of `CPythonTracebackErrorCaretTests`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106185]
Based on @hugovk work in https://github.com/python/core-workflow/issues/505 I found that we have two duplicated class `CPythonTracebackErrorCaretTests` here: https://github.com/python/cpython/blob/a3dd8cce58fe2b27eea4eed572d086dc8a7e1bb8/Lib/test/test_traceback.py#L908-L928

So, first tests are not executed.
We need to rename on of them.

Before: `Ran 236 tests in 2.453s`
After: `Ran 259 tests in 2.481s`

### Linked PRs
* gh-106187
* gh-107268

**Comment by hauntsaninja** [comment]
Nice spot, thank you!
