### ISSUE TITLE
Why do we need to change the permission of the `uu.py` file?

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#106132]
https://github.com/python/cpython/commit/3d5dd1eee265ec43dd96d89656c2a1c207dd5815 In this patch, the file permission of the uu.py file is changed. 

The permission on the `uu.py` file is changed from 755 to 644. Is this a misoperation? Why change this permission?

**Comment by sunmy2019** [comment]
@samcarroll42 as the original committer

**Comment by ronaldoussoren** [comment]
@alittlesir, do you have a use case for the file being executable?

**Comment by ronaldoussoren** [comment]
Executing the module can be done with "python3 -m uu" instead of "python3 /path/to/uu.py".  The former has been the best way to do this for a long while.
