### ISSUE TITLE
AST nodes for PEP 695 type param syntax do not require `end_lineno` nor `end_col_offset`

### ISSUE THREAD

**Issue by jacobtylerwalls** [python/cpython#106145]
# Bug report
Unlike AST nodes for 3.10 match syntax, AST nodes for 3.12 type param syntax (PEP 695) do not require `end_lineno` nor `end_col_offset`.

For 3.10 match syntax, this question was discussed [here](https://github.com/python/cpython/issues/88058#issuecomment-1093911564), and it was decided to require them.

Context: see end_lineno and end_col_offset creation in 3.8 by #11605. 

https://github.com/python/cpython/blob/bb578a0c304dffe43bb28b36b2b1c9153c78b659/Parser/Python.asdl#L148-L151

# Your environment
Python 3.12.0b3

### Linked PRs
* gh-106224
* gh-106295

**Comment by JelleZijlstra** [comment]
Good catch, I think we should fix this. Feel free to submit a PR; otherwise I should get to it in the next few days.

**Comment by sobolevn** [comment]
Sorry for sliding in, but I was experementing with `type_params` support for my linter and found this related issue :)

**Comment by jacobtylerwalls** [comment]
Fixed in #106224. Thanks all!
