### ISSUE TITLE
venv should check if directory exists while activating a virtual environment 

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#106151]
# Bug report

let's suppose some beginner shares the venv folder over the network or email and thinks that it will work on another machine like a container as it is bluffing the user by adding `venv`   `PS1="(venv) ${PS1:-}"` after checking `sys.prefix` we got to know it is same as a base prefix but it should check if `VIRTUAL_ENV="/home/proshan/venv"` directory is present or not before, and maybe it should throw an error  

content of `venv/bin/activate` 

```bash
VIRTUAL_ENV="/home/proshan/venv"
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH

# unset PYTHONHOME if set
# this will fail if PYTHONHOME is set to the empty string (which is bad anyway)
# could use `if (set -u; : $PYTHONHOME) ;` in bash
if [ -n "${PYTHONHOME:-}" ] ; then
    _OLD_VIRTUAL_PYTHONHOME="${PYTHONHOME:-}"
    unset PYTHONHOME
fi

if [ -z "${VIRTUAL_ENV_DISABLE_PROMPT:-}" ] ; then
    _OLD_VIRTUAL_PS1="${PS1:-}"
    PS1="(venv) ${PS1:-}"
    export PS1
    VIRTUAL_ENV_PROMPT="(venv) "
    export VIRTUAL_ENV_PROMPT
fi

# This should detect bash and zsh, which have a hash command that must
# be called to get it to forget past commands.  Without forgetting
# past commands the $PATH changes we made may not be respected
if [ -n "${BASH:-}" -o -n "${ZSH_VERSION:-}" ] ; then
    hash -r 2> /dev/null
fi
```

# Your environment

- CPython versions tested on: 3.11 
- Operating system and architecture: Linux-5.14.0-1059-oem-x86_64-with-glibc2.31

I will try to raise a PR if this is an issue and should be fixed

**Comment by vsajip** [comment]
Do you mean creating, or activating? And is this really an issue? I mean, you can't catch everything. What if a folder were shared to the exact same location on a different machine, but that other machine used a different processor architecture? Any libraries using C extensions would fail. What it the venv used symlinks which are only available on the machine where the venv was created?

This feels like a solution in search of a problem. I suggest posting on Discourse to see if any other Python core developers think this is an idea worth pursuing.

**Comment by Agent-Hellboy** [comment]
> What if a folder were shared to the exact same location on a different machine

This is possible but it is very rare as dirs on posix starts with  home/<username>

>other machine used a different processor architecture

I have no idea how venv depends on the architecture, I guess you mean an extension module can fail as its linker will try to link for python lib on the user machine to compile but the compiled module will be there in venv in virtual env of site-packages it is not going to compile again right?

all I am saying is adding a check for VIRTUAL_ENV 
https://github.com/python/cpython/blob/1f74b9e933d546a015e8497e3b8728357196acc8/Lib/venv/scripts/common/activate#L52
```
_OLD_VIRTUAL_PATH="$PATH"
if [ -d "$VIRTUAL_ENV" ]; then
    PATH="$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH"
else
    echo "Error: Path '$VIRTUAL_ENV' does not exist."
    exit 1
fi
export PATH
```

why I am saying to fix this 

As you can see in zsh as well as in bash both it is not activating the environment but it is bluffing the user that the environment is activated by adding venv in bash and adding an extra proshan on the right side panel on zsh , it should throw an error that virtual env is not created there is a failure 

![Screenshot from 2023-06-28 09-49-52](https://github.com/python/cpython/assets/31388347/f32da6db-d368-4d8d-8bec-61bad86730bb)
![Screenshot from 2023-06-28 09-55-56](https://github.com/python/cpython/assets/31388347/b0e43d0c-7b4e-4cea-9e71-277288dd8461)

> What it the venv used symlinks which are only available on the machine where the venv was created?

you can see he has 3.10 but still it added (venv) bluffed the user that the environment is activated 

![Screenshot from 2023-06-28 09-50-48](https://github.com/python/cpython/assets/31388347/9db4eeec-9f4c-46e2-a12c-d0eaa8e2ffd7)

the documentation says that we should do the below check but we should throw an error if the virtual environment doesn't get activated 

`When a Python interpreter is running from a virtual environment, [sys.prefix](https://docs.python.org/3/library/sys.html#sys.prefix) and [sys.exec_prefix](https://docs.python.org/3/library/sys.html#sys.exec_prefix) point to the directories of the virtual environment, whereas [sys.base_prefix](https://docs.python.org/3/library/sys.html#sys.base_prefix) and [sys.base_exec_prefix](https://docs.python.org/3/library/sys.html#sys.base_exec_prefix) point to those of the base Python used to create the environment. It is sufficient to check sys.prefix != sys.base_prefix to determine if the current interpreter is running from a virtual environment.`

>This feels like a solution in search of a problem
kind of :) 

> I suggest posting on Discourse to see if any other Python core developers think this is an idea worth pursuing.
sure

**Comment by vsajip** [comment]
Can I just point out that you keep saying "created", e.g.

> it should throw an error that virtual env is not created

But it has _already_ been created, and what you are talking about is _activating_ it. You use the same terminology in the Discourse topic, so I'd advise changing it so that everyone's clear on what you actually mean. Also it's not "bluffing the user" - bluffing is a deception one does intentionally.

Also, how exactly did you transfer the venv? Just for clarity.

**Comment by Agent-Hellboy** [comment]
> Can I just point out that you keep saying "created", e.g.

edited 

>Also, how exactly did you transfer the venv? Just for clarity.

I hosted it on the local wifi network.

**Comment by Agent-Hellboy** [comment]
Closing it as documentation clearly suggests we should not more the folder after it creation,and we should always create a new one.

**Comment by falstjit** [comment]
The issue that one of my users was facing was that he renamed the parent directory in the path. I understand that it is not expected to work, but the appearance of it working when it's not, is hard to explain to someone who isn't as savvy. In their view, nothing moved, it was just a rename higher in the hierarchy, everything in the project remained identical. The virtual env was created through vscode, and vscode happily executes things with the seemingly activated virtual environment. I don't think anyone's asking for this to be fixed in the sense that it should magically work, but rather in the sense that it should fail properly to save someone the headache. It's a minor check to see if the path being added to PATH actually exists, and fail if it doesn't - agreed it doesn't cover every case, but the return on investment seems pretty good in my view.
