### ISSUE TITLE
Add more cases to `test_patma`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106135]
While anwsering https://github.com/python/cpython/issues/106133 I've noticed that `test_patma` does not have tests for some corner-cases:
1. Case `case [x] | x: ...` is mentined in https://peps.python.org/pep-0634/#capture-patterns but is never tested, the closest we have to it is `case [z] | [1, (0 | 1 as z)] | [z]:`, which is not the same
2. Guards can have side effects according to https://peps.python.org/pep-0634/#guards but it is never tested
3. Guards are never tested with: mapping patterns, dotted value patterns
4. In [`ClassPattern` section](https://peps.python.org/pep-0634/#class-patterns) PEP says: `If name_or_attr is not an instance of the builtin type, TypeError is raised.` It is never tested in `TestTypeErrors`
5. [`LiteralPattern`](https://peps.python.org/pep-0634/#literal-patterns) might have some more expected `SyntaxError` cases, like using `*` and `/`, using three numbers like `0 + 0j + 0`
6. `LiteralPattern` says: `The singleton literals None, True and False are compared using the is operator.`, but only `None` is checked

I would like to send a PR with the new test cases.

### Linked PRs
* gh-106271

**Comment by terryjreedy** [comment]
Seems like a good idea.  Question: `case x, x: pass` evokes `SyntaxError: incomplete input` for any statement.  Does this seem right or should I open an issue?

**Comment by sobolevn** [comment]
@terryjreedy yes, this is not allowed: https://peps.python.org/pep-0634/#capture-patterns

> This disallows for example `case x, x: ...`

**Comment by brandtbucher** [comment]
Thanks for taking this on, it's definitely appreciated! Please ping me for review once it's ready. :)
