### ISSUE TITLE
3.12.0b3 build issue: 'O_CLOEXEC' undeclared in sysmodule.c

### ISSUE THREAD

**Issue by lmunch** [python/cpython#106118]
I am building Python 3.12.0b3 (3.11.X builds fine) on CentOS 5 using glibc-2.5 and gcc-4.8.5 and I encounter this build error:

gcc-4.8 -std=gnu11 -pthread -c -fno-strict-overflow -Wsign-compare -DNDEBUG -g -O3 -Wall -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -DPy_BUILD_CORE \
		-DABIFLAGS='""' \
		-DMULTIARCH=\"x86_64-linux-gnu\" \
		-o Python/sysmodule.o ./Python/sysmodule.c
./Python/sysmodule.c: In function 'PyUnstable_PerfMapState_Init':
./Python/sysmodule.c:2280:62: error: 'O_CLOEXEC' undeclared (first use in this function)
     int flags = O_WRONLY | O_CREAT | O_APPEND | O_NOFOLLOW | O_CLOEXEC;
                                                              ^
./Python/sysmodule.c:2280:62: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Python/sysmodule.o] Error 1

Perhaps there is a missing #ifdef O_CLOEXEC in ./Python/sysmodule.c?

Thanks

### Linked PRs
* gh-106120
* gh-106199

**Comment by erlend-aasland** [comment]
It looks like the other usages of `O_CLOEXEC` are guarded by preprocessor conditionals. AFAICS, we should do the same here.
