### ISSUE TITLE
Add SoftDeprecationWarning warning category

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106137]
Implementation of my proposed PEP 387 "Soft Deprecation" policy: https://github.com/python/peps/pull/3182

* Add SoftDeprecationWarning warning category
* Ignore these warnings by default, except in the ``__main__`` module  (similar to [PEP 565: Show DeprecationWarning in __main__](https://peps.python.org/pep-0565/))

As an example, I propose to soft deprecate the getopt module: PR #105735 (currently, the PR uses a regular "hard" deprecation).

### Linked PRs
* gh-106142

**Comment by terryjreedy** [comment]
This seems like a new feature.  Is there any discussion that you can link to?  Such as about the PEP?

**Comment by hugovk** [comment]
Discussion is ongoing at https://discuss.python.org/t/formalize-the-concept-of-soft-deprecation-dont-schedule-removal-in-pep-387-backwards-compatibility-policy/27957

**Comment by vstinner** [comment]
>This seems like a new feature. Is there any discussion that you can link to? Such as about the PEP?

Yes, see the first link in the issue :-)

> Implementation of my proposed PEP 387 "Soft Deprecation" policy: https://github.com/python/peps/pull/3182

=> https://github.com/python/peps/pull/3182

Also, @hugovk gave the link to the discussion.

**Comment by vstinner** [comment]
The idea of issuing a warning for soft deprecations is not liked, so I abandon my idea: https://discuss.python.org/t/formalize-the-concept-of-soft-deprecation-dont-schedule-removal-in-pep-387-backwards-compatibility-policy/27957
