### ISSUE TITLE
profile and cProfile are different even though docs say they are the same

### ISSUE THREAD

**Issue by jonathan-s** [python/cpython#106195]
# Bug report
```
import profile
import cProfile

c_profiler = cProfile.Profile()
c_profiler.enable()

p_profile = profile.Profile()
p_profile.enable() # raises AttributeError!
```

both cProfile and profile should have the same methods as stated in the documentation, but they do not. `profile` seems to be missing the methods enable and disable

# Your environment

- CPython versions tested on: Python 3.8.16 # though I think this bug occurs in much older versions as well. 
- Operating system and architecture: MacOS 13.1 (22C65)

**Comment by ronaldoussoren** [comment]
Both ``enable`` and ``disable`` are documented as being available with cProfile only (see https://docs.python.org/3/library/profile.html#profile.Profile.enable). 

```
enable()
   Start collecting profiling data. Only in cProfile.
disable()
   Stop collecting profiling data. Only in cProfile.
```

**Comment by jonathan-s** [comment]
My bad!
