### ISSUE TITLE
Fix `test_opcache` to skip threaded tests on WebAssembly platforms

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#106214]
https://buildbot.python.org/all/#/builders/1056/builds/2355
https://buildbot.python.org/all/#/builders/1046/builds/2338

/cc @brandtbucher 

### Linked PRs
* gh-106166

**Comment by hoodmane** [comment]
Should be fixed by https://github.com/python/cpython/pull/106166

**Comment by brandtbucher** [comment]
Thanks for the quick fix!
