### ISSUE TITLE
timeit basic examples are not compatible for Windows (CMD/ PowerShell)

### ISSUE THREAD

**Issue by arye321** [python/cpython#106232]
# Documentation
on this page
https://docs.python.org/3/library/timeit.html

the example 

`python3 -m timeit '"-".join(str(n) for n in range(100))'`

should be

`python3 -m timeit "'-'.join(str(n) for n in range(100))"`

because CMD and PowerShell do not support the first format

### Linked PRs
* gh-106296
* gh-106298

**Comment by tpackard1** [comment]
both the examples worked for me in PowerShell 7.3.4. What version of PowerShell did you try it with?

**Comment by arye321** [comment]
PS Version     5.1.19041.3031
When running `python3 -m timeit '"-".join(str(n) for n in range(100))'`
I'm getting
```
option -. not recognized
use -h/--help for command line help
```

**Comment by arye321** [comment]
Yes I just tested it on another machine, on v5.1 its not working but works on 7.3

**Comment by eryksun** [comment]
Newer versions of PowerShell rewrite a command line that contains a single-quoted string to instead use double quotes, with literal double quote characters backslash escaped as needed. For example, `'"-".join(str(n) for n in range(100))'` -\> `"\"-\".join(str(n) for n in range(100))"`. This allows the C runtime in the Windows version of Python to parse the double-quoted string as a single command-line argument that contains literal double quote characters.

In contrast, the CMD shell has no special handling of single quote characters in this context. It passes the command line exactly as written to the spawned process. The C runtime in the spawned Python process has no special handling of single quote characters when parsing a command line into an argument array. For example, `'"-".join(str(n) for n in range(100))'` is parsed as an array of 5 arguments, `["'-.join(str(n)", 'for', 'n', 'in', "range(100))'"]`, which obviously won't work.

Also, most Python installations on Windows have no "python3" command. The exception, at least for official PSF releases, is the app distribution in the Microsoft Store, which enables a "python3.exe" appexec alias by default.

**Comment by terryjreedy** [comment]
Examples should use the generic 'python' and work on Windows Command Prompt.  People should substitute 'python' with 'python3', 'python3.y', 'py', 'py -3', 'py -3.y'.  I presume " outside ' works on *nix.  Working on PR.

**Comment by terryjreedy** [comment]
Main already has 'python', not 'python3'.  However, 'python' was 'python3' in 3.11, changed in 3.12.  Hence a backport would require redoing the patch.
