### ISSUE TITLE
Mixed Type ChainMap Order Dependency

### ISSUE THREAD

**Issue by joegeisbauer-ce** [python/cpython#106261]
# Bug report

A ChainMap will allow for mixed types without throwing an error; however, accessing values from the ChainMap via keys fails once it hits a list, if the desired key follows the list. In the example below, `c` will throw a TypeError with the following message: "TypeError: list indices must be integers or slices, not str," while `d` will return the correct value.

```
from collections import ChainMap

a = [0,1,2,3]
b = {'animal': 'dog', 'color': 'black'}
c = ChainMap(a,b)
d = ChainMap(b,a)
c['animal'] (throws error)
d['animal'] (outputs 'dog')
```

# Your environment

- CPython versions tested on: 3.10.6 and master repo branch
- Operating system and architecture: Ubuntu 22.04 x86_64

### Linked PRs
* gh-106262

**Comment by joegeisbauer** [comment]
I have a fix for this already, and will have a PR up shortly.

**Comment by sunmy2019** [comment]
> A ChainMap will allow for mixed types without throwing an error

IMO `ChainMap` should only accept map-like objects, not `list`.

**Comment by joegeisbauer** [comment]
I am happy to go either way here. I think it should either error out on creation, or we should implement the TypeError fix though. Otherwise, the behavior is confusing. I was simply assuming that the desired behavior was that lists would work since it did not error on creation when I tested a list with a dictionary.

**Comment by sunmy2019** [comment]
> error out on creation

This is technically not feasible.

> I was simply assuming that the desired behavior was that lists would work since it did not error on creation when I tested a list with a dictionary.

You should not assume that.

For example,
```py
from collections import ChainMap, defaultdict
a = ChainMap(defaultdict(int), 123, object, "anything you want..." )

a[0] # always works
```

**Comment by hauntsaninja** [comment]
Python is a dynamically typed language. It allows you to pass whatever you want and it's typically your responsibility as a programmer to make sure whatever you're passing in is something that makes sense.

If you'd like to see errors for this kind of thing sooner, I recommend using a static type checker. These will warn you about this even before you run your code: https://mypy-play.net/?mypy=latest&python=3.11&gist=230eece82e9f0b307faffb860be5afeb

**Comment by joegeisbauer** [comment]
Okay. Thank you for your time, consideration, and explanation.
