### ISSUE TITLE
`_DummyThread`s can be joined in `-OO` mode

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106236]
Right now `_DummyThread` claims to not allow `join`: https://github.com/python/cpython/blob/fb0d9b9ac1ec3ea13fae8b8ef6a4f0a5a80482b3/Lib/threading.py#L1453-L1458

But, it can be easily changed with `python -OO` mode, which strips `assert` statements.

The easiest way to check this is:

```python
# ex.py
import threading, _thread

def f(mutex):
    threading.current_thread()
    mutex.release()

mutex = threading.Lock()
mutex.acquire()

tid = _thread.start_new_thread(f, (mutex,))
mutex.acquire()
threading._active[tid].join()
print('done')
```

`python ex.py` results in:

```
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/ex.py", line 12, in <module>
    threading._active[tid].join()
  File "/Users/sobolev/Desktop/cpython/Lib/threading.py", line 1458, in join
    assert False, "cannot join a dummy thread"
AssertionError: cannot join a dummy thread
```

But, `python -OO ex.py` results in:

```
done
```

This looks like an important behavior change. I propose to use explicit `AssertionError` / `RuntimeError` instead.

I have a PR ready.

### Linked PRs
* gh-106237

**Comment by gpshead** [comment]
fixed in main, thanks for the PR.  I don't personally think this is important enough to put in a bugfix release, if someone finds a practical reason to do so, feel free to hit the backport buttons.
