### ISSUE TITLE
Add stdlib_deprecations module

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106240]
Following [Formalize the concept of “soft deprecation” (don’t schedule removal) in PEP 387 “Backwards Compatibility Policy”](https://discuss.python.org/t/formalize-the-concept-of-soft-deprecation-dont-schedule-removal-in-pep-387-backwards-compatibility-policy/27957) discussion and my PEP PR [PEP 387: Add Soft Deprecation section](https://github.com/python/peps/pull/3182), I propose to add a new ``stdlib_deprecations`` module which provides an API for linters to check if an API is deprecated or not.

### Linked PRs
* gh-106241

**Comment by JelleZijlstra** [comment]
Note that any new stdlib module requires a PEP: https://peps.python.org/pep-0002/#acceptance-procedure

**Comment by vstinner** [comment]
Closed: see https://github.com/python/cpython/pull/106241#issuecomment-1619259964
