### ISSUE TITLE
[match-case] allow matching Literal `Ellipsis` and `NotImplemented`.

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#106249]
# Feature or enhancement

It seems inconsistent that the [builtin singleton constant](https://docs.python.org/3/library/constants.html) `None` is allowed to be literal in a match-case statement (as opposed to using `types.NoneType()`), but `Ellipsis` and `NotImplemented` are not:

```python
from types import NoneType, EllipsisType, NotImplementedType

x = None

match x:
    case NoneType():  # ✔
        print(x)
    case EllipsisType():  # ✔
        print(x)
    case NotImplementedType():  # ✔
        print(x)
    case _:
        print("Not Matched!")
            
match x:
    case None:
        print(x)
    case Ellipsis:  # ✘ SyntaxError
        print(x)
    case NotImplemented:  # ✘ SyntaxError
        print(x)
    case _:
        print("Not Matched!")
```

# Pitch

Put the builtin singleton constants on equal footing and give `NotImplemented` and `Ellipsis` the same privileged literal special-casing as `None`. Having to import `EllipsisType` and `NotImplementedType` is rather annoying.

**Comment by brandtbucher** [comment]
The reason it's designed this way is because `None`, `True`, and `False` are syntax, while `Ellipsis` and `NotImplemented` are just normal names that happen to be defined in the builtins.

We *could* allow singleton matches on `...` (another spelling for `Ellipsis`), but honestly that seems close to useless, and could cause confusion with `*` patterns in the context of things like sequence patterns:

```py
match whatever:
    # Matches a three-element sequence with `Ellipsis` as the second element:
    case [first, ..., last]:
        pass
    # Matches any two-or-more-element sequence:
    case [first, *_, last]:
        pass
```

**Comment by randolf-scholz** [comment]
@brandtbucher One thing that still kind of confuses me: Why am I allowed to match `builtins.NotImplemented`, and why does it matter how it is imported?

```python
x = NotImplemented

import builtins
from builtins import NotImplemented as NotImpl

assert NotImplemented is builtins.NotImplemented
assert NotImplemented is NotImpl

match x:
    case builtins.NotImplemented:  # ✔ no syntax error
        print("It's NotImplemented")
    case _:
        print("It's not NotImplemented")

match x:
    case NotImpl:  # ✘ SyntaxError
        print("It's NotImplemented")
    case _:
        print("It's not NotImplemented")
```

Why does `SyntaxError` get raised for the second but not the first match-case?
