### ISSUE TITLE
math.log10(10**443) != 443.0

### ISSUE THREAD

**Issue by clairvoyante** [python/cpython#106221]
```
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from math import log10
>>> log10(10**443)
443.00000000000006
>>>
```
443.00000000000006 is very small error(1ULP), So, "Won't fix this issue" is acceptable, IMHO.

**Comment by TheCalculus** [comment]
@clairvoyante floating point errors aren't bugs. they are by design meant to be approximations of real numbers and the relative error is normally acceptable.
see [this](https://stackoverflow.com/questions/588004/is-floating-point-math-broken) for more information about them

**Comment by tpackard1** [comment]
Or tldr: "Python only prints a decimal approximation to the true decimal value of the binary approximation stored by the machine." For example 0.1 is not stored in the machine as simply 0.1 but
```
>>> format(0.1, '.50g')
'0.1000000000000000055511151231257827021181583404541'
```
if you really wanted to just get 443.0 back you could do something like the following:
```
>>> print(f'{math.log10(10**443): .1f}')
 443.0
```

**Comment by terryjreedy** [comment]
@TheCalculus @tpackard1 Thanks for explaining so I or another coredev does not have to.

@clairvoyante We would prefer that people post issues like this to question/answer forums, such as https://discuss.python.org/c/users/7.

**Comment by pochmann** [comment]
> ```
> >>> format(0.1, '.50g')
> '0.1000000000000000055511151231257827021181583404541'
> ```

So close. With 56, you'd see the exact value (0.1000000000000000055511151231257827021181583404541015625).
