### ISSUE TITLE
Provide a way for operators on subclasses of native types to return instances of the subclass

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#106222]
# Feature or enhancement

A simple way to make `tuple_subclass(...)[:]` an instance of tuple_subclass instead of tuple, same for `-float_subclass(...)`.

# Pitch

When subclassing native types such as float or dict, or stdlib types such as Counter, it’s often surprising or frustrating for new users that Subclass() + Subclass() is an instance of the native type rather than the subclass.
It is so for performance reasons I assume, so I’m not proposing we change that. Instead, I'm proposing a way to easily but specifically direct subclasses to work that way.

Mitigating that behavior is often tedious and leads to long, repetitive and error-prone code, here is my favorite one (written by yours truly) but which is still a chore :
https://github.com/renpy/renpy/blob/master/renpy/display/core.py#L193-L276
Doing this kind of operation is very unhandy for beginners and amateurs alike, as [this thread](https://discuss.python.org/t/how-to-extend-built-in-decimal-class/28547) shows for example.

My idea is to make a [`functools.total_ordering`](https://docs.python.org/3/library/functools.html#functools.total_ordering)-like class decorator, which I explain in more details in the Discuss thread, in the docstring of the implem and possibly in the pull request.
[Testable implementation](https://colab.research.google.com/drive/1WRI8CrVnkZdcLgp1wl3DQQEBURfQ6x2C?usp=sharing), also proposed as a pull request to the functools module.

# Previous discussion

https://discuss.python.org/t/re-type-operator-overloads-when-subclassing-a-builtin-or-stdlib-type/28378/2

### Linked PRs
* gh-106223

**Comment by iritkatriel** [comment]
-1 for including this in the stdlib.

Your proposed solution is quite limited - it only works when the subclass constructor has the same signature as the base class. This will lead to just as much confusion as the current state. You can create a module on PYPI with this, but I don't think it's generic enough to be in the stdlib.

**Comment by Gouvernathor** [comment]
@iritkatriel The signature thing is a fair point I overlooked. But it's only against the implementation, not the feature idea itself.

Is your point about being generic enough to be in the stdlib, linked to that question, or not ? I.e, if I find a way to make it work even for subclasses with different signatures, would you still consider it's not generic enough ?

**Comment by iritkatriel** [comment]
>  I.e, if I find a way to make it work even for subclasses with different signatures, would you still consider it's not generic enough ?

If you make it generic then I won't consider it to not be generic, but that doesn't automatically mean it will be included in the stdlib.  If it's complicated, and not considered to solve an important enough problem, then it probably won't be included. PYPI exists for a reason. There are many useful things there that will never be in the stdlib.
