### ISSUE TITLE
Python/ceval.c -Wunreachable-code warn from apple-clang

### ISSUE THREAD

**Issue by corona10** [python/cpython#106280]
````

Python/ceval.c:2849:17: warning: code will never be executed [-Wunreachable-code]
                for (;;) {}
                ^~~~~~~~~~~
Python/ceval.c:2848:17: warning: code will never be executed [-Wunreachable-code]
                abort();  // Unreachable
````

The code was first introduced from https://github.com/python/cpython/commit/51fc72511733353de15bc633a3d7b6da366842e4
@gvanrossum is it really needed?

### Linked PRs
* gh-106285

**Comment by gvanrossum** [comment]
I was being silly. Just delete those two lines. I didn't realize that clang understands that `Py_FatalError()` never returns...
