### ISSUE TITLE
startup-failure in the python idle

### ISSUE THREAD

**Issue by pranav-dhinoja** [python/cpython#106333]
# Crash report

Tell us what happened, ideally including a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example).

# Error messages

Enter any relevant error message caused by the crash, including a core dump if there is one.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by ericvsmith** [comment]
Please ask for help on a python forum, such as https://discuss.python.org/c/users/7

**Comment by terryjreedy** [comment]
Duplicate of #016632.  Please do not open duplicate reports.
