### ISSUE TITLE
Argument Clinic: DSLParser.parse_converter() can return an incorrect kwargs dict

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#106359]
_Originally posted by @AlexWaygood in https://github.com/python/cpython/issues/106354#issuecomment-1617797726_:

```
Tools/clinic/clinic.py:5039: error: Incompatible return value type (got
"tuple[str, bool, dict[str | None, Any]]", expected
"tuple[str, bool, dict[str, Any]]")  [return-value]
                    return name, False, kwargs
                           ^~~~~~~~~~~~~~~~~~~
```

I think mypy is flagging a real bug in the code here. The issue is this block of code here:

https://github.com/python/cpython/blob/d694f043ae25308dda607fad4ea1d8d85d79982f/Tools/clinic/clinic.py#L5033-L5039

The function is annotated as return `tuple[str, bool, KwargDict]`, and `KwargDict` is a type alias for `dict[str, Any]`. It's important that the dictionary that's the third element of the tuple only has strings as keys. If it doesn't, then this will fail:

https://github.com/python/cpython/blob/d694f043ae25308dda607fad4ea1d8d85d79982f/Tools/clinic/clinic.py#L4617

The code as written, however, doesn't guarantee that all the keys in the `kwargs` dictionary will be strings. In the dictionary comprehension, we can see that `annotation` is an `ast.Call` instance. That means that `annotation.keywords` is of type `list[ast.keyword]` -- we can see this from typeshed's stubs for the `ast` module (which are an invaluable reference if you're working with ASTs in Python!): https://github.com/python/typeshed/blob/18d45d62aabe68fce78965c4920cbdeddb4b54db/stdlib/_ast.pyi#L324-L329. If `annotation.keywords` is of type `list[ast.keyword]`, that means that the `node` variable in the dictionary comprehension is of type `keyword`, which means (again using typeshed's `ast` stubs), that `node.arg` is of type `str | None`: https://github.com/python/typeshed/blob/18d45d62aabe68fce78965c4920cbdeddb4b54db/stdlib/_ast.pyi#L516-L520. AKA, the keys in this dictionary are not always guaranteed to be strings -- there's a latent bug in this code!

### Linked PRs
* gh-106361
* gh-106364

**Comment by erlend-aasland** [comment]
Suggested fixes by Alex: https://github.com/python/cpython/pull/106354#issuecomment-1617832899

**Comment by erlend-aasland** [comment]
In the spirit of Argument Clinic, I would think it would be best to catch the error and bail; so a modified variant of the second suggestion, @AlexWaygood

**Comment by AlexWaygood** [comment]
Here's a minimal repro of the situation where the `arg` attribute of an `ast.keyword` node could be `None`:

```pycon
>>> module = ast.parse('foo(**kwargs)')
>>> call = module.body[0].value
>>> assert isinstance(call, ast.Call)
>>> keyword = call.keywords[0]
>>> assert isinstance(keyword, ast.keyword)
>>> keyword.arg is None
True
```

**Comment by erlend-aasland** [comment]
Actually, `parse_converter` cannot be called unless the param declaration is valid, which means it's guaranteed to be a `str`. Adding an `assert` should be sufficient.

**Comment by AlexWaygood** [comment]
And here's a failing test case:

```diff
--- a/Lib/test/test_clinic.py
+++ b/Lib/test/test_clinic.py
@@ -327,6 +327,9 @@ def test_param_default_expression(self):
         s = self.parse_function_should_fail("module os\nos.access\n    follow_symlinks: int = sys.maxsize")
         self.assertEqual(s, "Error on line 0:\nWhen you specify a named constant ('sys.maxsize') as your default value,\nyou MUST specify a valid c_default.\n")

+    def test_kwarg_splat(self):
+        self.parse_function("module os\nos.access\n    follow_symlinks: int(**{'c_default': 'MAXSIZE'})")
+
```

Add this test, and this is the result if you run `python -m test test_clinic`:

```pytb
test test_clinic failed -- Traceback (most recent call last):
  File "C:\Users\alexw\coding\cpython\Lib\test\test_clinic.py", line 331, in test_kwarg_splat
    self.parse_function("module os\nos.access\n    follow_symlinks: int(**{'c_default': 'MAXSIZE'})")
  File "C:\Users\alexw\coding\cpython\Lib\test\test_clinic.py", line 865, in parse_function
    block = self.parse(text)
            ^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\test\test_clinic.py", line 861, in parse
    parser.parse(block)
  File "C:\Users\alexw\coding\cpython\Tools\clinic\clinic.py", line 4481, in parse
    self.state(line)
  File "C:\Users\alexw\coding\cpython\Tools\clinic\clinic.py", line 4751, in state_parameters_start
    return self.next(self.state_parameter, line)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Tools\clinic\clinic.py", line 4521, in next
    self.state(line)
  File "C:\Users\alexw\coding\cpython\Tools\clinic\clinic.py", line 4989, in state_parameter
    converter = dict[name](c_name or parameter_name, parameter_name, self.function, value, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: keywords must be strings

test_clinic failed (1 error)

== Tests result: FAILURE ==
```

`clinic` _should_ fail if you do a kwarg-splat in a function call as an annotation -- but it should fail gracefully using the `fail()` function, rather than crashing with a `TypeError`

**Comment by erlend-aasland** [comment]
> Here's a minimal repro of the situation where the `arg` attribute of an `ast.keyword` node could be `None`:

I've failed to reproduce it in clinic, though.

**Comment by AlexWaygood** [comment]
> > Here's a minimal repro of the situation where the `arg` attribute of an `ast.keyword` node could be `None`:
> 
> I've failed to reproduce it in clinic, though.

I just did; see https://github.com/python/cpython/issues/106359#issuecomment-1618040738

**Comment by erlend-aasland** [comment]
Yeah, I managed to do a similar repro; PR up.

**Comment by AlexWaygood** [comment]
> Yeah, I managed to do a similar repro; PR up.

Dang, you beat me to it; I was also working on a PR :D

**Comment by erlend-aasland** [comment]
Sorry! :) Oh, well you kinda wrote the entire patch. I just filled in a tiny blank!
