### ISSUE TITLE
Increase Argument Clinic test coverage

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#106368]
The Argument Clinic test suite consists of three parts:

- Lib/test/test_clinic.py: mostly parser tests
- Lib/test/clinic.test: generated code, checked by test_clinic.py (`ClinicExternalTest`)
- Modules/_testclinic.c: mostly converter tests (thanks, @colorfulappl!)

Test coverage is currently just above 80%, which is too low. I'd say we try to reach 90-something percent coverage.

Reminder: PRs for increased test coverage should be backported to all bugfix branches.

### Linked PRs
* gh-106369
* gh-106370
* gh-106373
* gh-106374
* gh-106379
* gh-106381
* gh-106384
* gh-106387
* gh-106388
* gh-106389
* gh-106390
* gh-106391
* gh-106407
* gh-106409
* gh-106410
* gh-106415
* gh-106438
* gh-106439
* gh-106728
* gh-106730
* gh-106731
* gh-106759
* gh-106769
* gh-106770
* gh-106813
* gh-106833
* gh-106838
* gh-106839
* gh-106933
* gh-106943
* gh-106944
* gh-106979
* gh-106994
* gh-107002
* gh-107156
* gh-107189
* gh-107190
* gh-107277
* gh-107282
* gh-107326
* gh-107364
* gh-107365
* gh-107366
* gh-107387
* gh-107496
* gh-107499
* gh-107500
* gh-107514
* gh-107582
* gh-107606
* gh-107611
* gh-107641
* gh-107693
* gh-107731
* gh-107977
* gh-107985

**Comment by erlend-aasland** [comment]
Also: a side effect of good coverage, is that it can help identify unreachable paths in the code.

**Comment by erlend-aasland** [comment]
cc. @sobolevn, who I know enjoys increasing test coverage 📈

**Comment by erlend-aasland** [comment]
FTR, we're up in 86% coverage now.

**Comment by littlebutt** [comment]
> FTR, we're up in 86% coverage now.

A question, where can I find the test coverage? Thank you.

**Comment by erlend-aasland** [comment]
> A question, where can I find the test coverage? Thank you.

There is no published coverage, or coverage measurement in CI. You'll have to measure it yourself, for now.

**Comment by erlend-aasland** [comment]
FTR, I got my coverage setup up and running again; coverage is at ~87% as of HEAD at 70dc00946938027d5a79bcb7b65038319040144e.

**Comment by erlend-aasland** [comment]
Reopening to increase coverage for the DSL parser state machine and the docstring formatter.

**Comment by erlend-aasland** [comment]
We're now at 93% coverage.
