### ISSUE TITLE
datetime UTC deprecation warnings use the name "datetime" inconsistently

### ISSUE THREAD

**Issue by wjandrea** [python/cpython#106392]
## Bug report

The UTC deprecation warnings (added in #103858) use the name `datetime` to refer to both the object and the module, which is confusing. Like, if I copy-paste the code from the warnings, it doesn't work:

```python
>>> import datetime
>>> datetime.datetime.utcnow()
<stdin>:1: DeprecationWarning: datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.now(datetime.UTC).
datetime.datetime(2023, 7, 3, 23, 35, 25, 850070)
>>> datetime.now(datetime.UTC)  # <-- Copy-pasted but doesn't work
  ...
AttributeError: module 'datetime' has no attribute 'now'
>>> datetime.datetime.now(datetime.UTC)  # Fixed
datetime.datetime(2023, 7, 3, 23, 35, 32, 898186, tzinfo=datetime.timezone.utc)
>>> 
>>> timestamp = 0
>>> datetime.datetime.utcfromtimestamp(timestamp)
<stdin>:1: DeprecationWarning: datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.fromtimestamp(timestamp, datetime.UTC).
datetime.datetime(1970, 1, 1, 0, 0)
>>> datetime.fromtimestamp(timestamp, datetime.UTC)  # <-- Copy-pasted but doesn't work
  ...
AttributeError: module 'datetime' has no attribute 'fromtimestamp'
>>> datetime.datetime.fromtimestamp(timestamp, datetime.UTC)  # Fixed
datetime.datetime(1970, 1, 1, 0, 0, tzinfo=datetime.timezone.utc)
```

To fix it, I'd just put `datetime.datetime` where necessary. LMK if you want me to submit a PR.

### By the way

#104542 brought up the same thing about the deprecated names, but I think it's fine personally:

> It's really `datetime.datetime.utcnow()` and `datetime.datetime.utcfromtimestamp()`, and not `datetime.utcnow()` and `datetime.utcfromtimestamp()`.

#105544 might also be relevant, I'm not sure.

## Your environment

- CPython versions tested on: 3.12.0b3
- Operating system and architecture: Ubuntu 20.04 x64

### Linked PRs
* gh-106405
* gh-106436
* gh-108792
* gh-114761
* gh-114764
* gh-114767

**Comment by terryjreedy** [comment]
The specific inconsistency is that `datetime.now(datetime.UTC)` uses `datetime` with two different meanings, first class then module.  So the expression can never be correct regardless of the import.  I agree with expanding the first `datetime` to what works with `import datetime`.  This is what @hugovk did with the What'sNew entry.  Users should then be able to figure out that the alternative is `datetime.now(UTC)`, with the module label stripped off in both places after *both* objects are imported from the module.

**Comment by hugovk** [comment]
@wjandrea Thanks for the report, would you like to create a PR to update the deprecation warning text?

**Comment by serhiy-storchaka** [comment]
The C implementation was fixed in GH-108073. GH-106436 fixed the Python implementation incompletely, it left inconsistent references to methods at the beginning of warning messages.

**Comment by hauntsaninja** [comment]
Ah sorry, I was mainly looking at the consistency between `datetime.fromtimestamp` and `datetime.UTC` needed to make that expression work
