### ISSUE TITLE
typing.get_type_hints fails when attempting to import a union type from another module

### ISSUE THREAD

**Issue by s-vitaliy** [python/cpython#106334]
While investigating the bug in lidatong/dataclasses-json#429, I discovered that the "get_type_hints" function can potentially fail when invoked on a type from another module that includes a forward declaration which hasn't been imported.

Steps to reproduce:

1. Create a project with the following structure:
```
src/test_case.py
src/fail.py
src/success.py
```
And with the following contents in the files:
**fail.py**:
```python
import dataclasses as dataclasses
from typing import get_type_hints, Optional

import test_case


@dataclasses.dataclass
class SelfTestCase:
    policy_arn: Optional[test_case.Input[str]]


if __name__ == '__main__':
    result = get_type_hints(type(SelfTestCase(None)))
```

**test_case.py**:
```python
from typing import TypeVar, Union, Awaitable, Generic

T = TypeVar("T")
Input = Union[T, Awaitable[T], "Output[T]"]


class Output(Generic[T]):
    pass
```
**success.py**
```python
import dataclasses as dataclasses
from typing import get_type_hints, Optional

from typing import TypeVar, Union, Awaitable, Generic

T = TypeVar("T")
Input = Union[T, Awaitable[T], "Output[T]"]


class Output(Generic[T]):
    pass


@dataclasses.dataclass
class SelfTestCase:
    policy_arn: Optional[Input[str]]


if __name__ == '__main__':
    result = get_type_hints(type(SelfTestCase(None)))
```

When I'm running the `fail.py` file, I'm getting the following error:
```
Traceback (most recent call last):
  File "C:\Users\savit\PycharmProjects\bug_in_typing\src\fail.py", line 11, in <module>
    result = get_type_hints(type(SelfTestCase()))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\typing.py", line 1833, in get_type_hints
    value = _eval_type(value, base_globals, base_locals)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\typing.py", line 329, in _eval_type
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\typing.py", line 329, in <genexpr>
    ev_args = tuple(_eval_type(a, globalns, localns, recursive_guard) for a in t.__args__)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Output' is not defined
```

When I run `success.py` (without any imports), there are no errors. It appears that the error occurs when the `Output` class is not defined in the same scope where the union type Input is imported.

The original code that causes the error was in the [pulumi library](https://github.com/pulumi/pulumi/blob/947aac380628fe028d3defee2734ef96d9e584d4/sdk/python/lib/pulumi/output.py#L52C5-L52C5).

**Comment by AlexWaygood** [comment]
@s-vitaliy, could you let us know which versions of Python you were testing on?

**Comment by s-vitaliy** [comment]
@AlexWaygood, I'm testing on python 3.10 and 3.11
```
> .\venv311\Scripts\python.exe --version
Python 3.11.4
> .\venv\Scripts\python.exe --version
Python 3.10.11
```

**Comment by sunmy2019** [comment]
Solving this may be difficult or nearly impossible.

It is also documented.
> Note [get_type_hints()](https://docs.python.org/3/library/typing.html#typing.get_type_hints) does not work with imported [type aliases](https://docs.python.org/3/library/typing.html#type-aliases) that include forward references. Enabling postponed evaluation of annotations ([PEP 563](https://peps.python.org/pep-0563/)) may remove the need for most forward references.

https://docs.python.org/3/library/typing.html#typing.get_type_hints

**Comment by sunmy2019** [comment]
I don't think we should fix this.

See also #89089

**Comment by AlexWaygood** [comment]
Thanks @sunmy2019! I think you're right that this was comprehensively discussed in #89089, and that it would be hard-if-not-impossible to fix in a principled way.

Long-term, the best solution is probably for to migrate towards PEP-695-style type aliases where possible.
