### ISSUE TITLE
getting error installing scipy: Failed building wheel for numpy (Numpy is already installed)

### ISSUE THREAD

**Issue by aakanshapandey1203** [python/cpython#106397]
# Bug report
Getting error installing scipy: Failed building wheel for numpy (Numpy is already installed)
Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment
Zlinux(s390x)

- CPython versions tested on:
- Operating system and architecture:

**Comment by hugovk** [comment]
This is the issue tracker for CPython itself.

Please report SciPy/NumPy installation issues to the SciPy or NumPy projects. You'll need to give them the full error trackback.
