### ISSUE TITLE
Why tkinter in python 3.9.0 removed _get_default_root?

### ISSUE THREAD

**Issue by littlewhitecloud** [python/cpython#106327]
https://github.com/python/cpython/blob/v3.9.0/Lib/tkinter/__init__.py

**Comment by littlewhitecloud** [comment]
![image](https://github.com/python/cpython/assets/71159641/7c9c0c58-9d9d-4740-bf8b-6977d7ddabe3)

**Comment by terryjreedy** [comment]
This issue tracker is for patching future CPython releases.  Please ask questions on help forums, such as https://discuss.python.org/c/users/7.   But don't ask this one as tkinter._get_default_root still exists in 3.11+.
