### ISSUE TITLE
IDLE is having startup failure

### ISSUE THREAD

**Issue by pranav-dhinoja** [python/cpython#106332]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by pranav-dhinoja** [comment]
the idle of python is having the startup-failure

**Comment by ericvsmith** [comment]
Please ask for help on a python forum, such as https://discuss.python.org/c/users/7

**Comment by terryjreedy** [comment]
If you ask elsewhere, give your operating system, python version, exact what you did, and exactly what happened that you call a 'failure'.
