### ISSUE TITLE
Suspicion with Python reliability when checking for a string within a string. 

### ISSUE THREAD

**Issue by NSC9** [python/cpython#106440]
Environment: Jupyter Notebook
CPython versions tested on: 3.10.6
Operating system and architecture: https://termbin.com/63rc
Link to code: [link](https://github.com/NSC9/Sample_of_Work/blob/Main/mathematics.ipynb)

I have a suspicion there is something wrong with how Python checks to see if a string is within a string. 
At line 15: `kw3 = {"I","*I","I/2","*I/2","*I:","I:"}`, I had to sequentially add more and more checks when just "I" should work. 
My suspicion is that the colon may be breaking the way Python searches a string. 

Line 113: `if not any(kw in str(eq55) for kw in kw3):` where `str(eq55)` is some string representing a generated equation that may or may not include the string `I`. 

`kw3 = {"I"}` should be enough, but I had to add a lot more to it to stop getting blown up and ugly equations that include `I` for a complex number inside them. 

`str(eq55)` type is `<class 'sympy.core.relational.Equality'>`
`Eq(lambda_i, {-12: 1, 3 - 2*sqrt(2)*I: 1, 3 + 2*sqrt(2)*I: 1})` is an example of what `eq55` could be.

So far the code works the way I want it to, but I do not understand why I needed to add more than 1 element in `kw3`.

**Comment by ericvsmith** [comment]
Please simplify your example to a few lines of code.

It's very unlikely that this is a bug in Python. I suggest you ask for help in https://discuss.python.org/c/users/7

**Comment by ericvsmith** [comment]
Also, please provide an example that doesn't use any third party libraries. If this is in fact a bug in Python, you should be able to demonstrate it without using sympy.

**Comment by ronaldoussoren** [comment]
I'm closing this issue, there is no clear description of what's going wrong and it unlikely to be a bug in Python itself.
