### ISSUE TITLE
re.sub backreferences interaction with unicode literals

### ISSUE THREAD

**Issue by yairflists** [python/cpython#106419]
# Bug report

When using unicode literals in "String" argument of re.sub only \g backtraces are producing the correct results 'CB':
Minimal steps to reproduce:

```
Python 3.12.0b3 (tags/v3.12.0b3:f992a60, Jun 20 2023, 12:25:40) [MSC v.1936 64 bit (AMD64)] on win32
>>> import re
>>> from sys import version_info
>>> print(version_info)
sys.version_info(major=3, minor=12, micro=0, releaselevel='beta', serial=3)

>>> A = '\N{LATIN CAPITAL LETTER A}'
>>> B = '\N{LATIN CAPITAL LETTER B}'
>>> C = '\N{LATIN CAPITAL LETTER C}'
>>> rex =            ('([' + A     + B     + '])' )
>>> res3 = re.sub(rex            + C,      C      + '\g<1>' , 'BC')
<stdin>:1: SyntaxWarning: invalid escape sequence '\g'
>>> res4 = re.sub(rex            + C,      C      + '\1' , 'BC')
>>> print(repr(res3))
'CB'
>>> print(repr(res4))
'C\x01'
```
```

**Comment by terryjreedy** [comment]
No bug here.  `'\1'` is `'\x01'`.  `'\1'` is seen as a 1-digit [octal escape.](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals).  Also see this part of the [re doc](https://docs.python.org/3.12/library/re.html#regular-expression-syntax):
>If you’re not using a raw string to express the pattern, remember that Python also uses the backslash as an escape sequence in string literals; if the escape sequence isn’t recognized by Python’s parser, the backslash and subsequent character are included in the resulting string. However, if Python would recognize the resulting sequence, the backslash should be repeated twice. This is complicated and hard to understand, so it’s highly recommended that you use raw strings for all but the simplest expressions.

You need either `'\\1'` or `r'\1'` for `re` to see the 2 character string '\1'.  I  would always use the raw string with 'r' prefix unless I wanted some backslashes within a string to be immediately processed, as for unicode \u#### escapes, and others left to be processed by re.

The doc is slightly obsolete.  `\g'` is not recognized.  In 3.12, it generates SyntaxWarning, which you copied.  I believe in 3.14 it will be a SyntaxError.  You should enter either `'\\g<1>'` or `'r\g<1>'`. 

We suggest that beginners ask questions about possible bugs on help forums such as https://discuss.python.org/c/users/7.
