### ISSUE TITLE
Open with Idle

### ISSUE THREAD

**Issue by honis56** [python/cpython#106421]
Windows 10 Pro Version 10.0.19045 Build 19045

Python 3.11 (64-bit)

Install Python from website, make standard app .py, but there is still no "Edit with Idle" in context menu as mentioned in closed Bug Report #102411

**Comment by terryjreedy** [comment]
When I right-click on a .py file, the second line is 'Open with IDLE'.  Hovering the mouse pointer over that shows a submenu with 'Open with IDLE 3.11 (64-bit)' and same for 3.12.  To determine is there is a bug in the installation, you will have to report what you did in more excruciating detail than you have ;-).

**Comment by honis56** [comment]
After reinstalling windows and python on my laptop, the bug disappeared. Hopefully it will also disappear on my other computer when I renew the entire installation in a few days. Thank you for answering. ;-)

**Comment by honis56** [comment]
After reinstalling windows and python on my PC, the bug disappeared as well.
Sorry for my announcement.

**Comment by terryjreedy** [comment]
A non-bug resolution is common, and why the bug report template suggests first posting elsewhere, such as https://discuss.python.org/c/users/7.  (I look at those too.)
