### ISSUE TITLE
can access variable from for loop outside the scope.

### ISSUE THREAD

**Issue by jaeeewon** [python/cpython#106472]
# Bug report

```
z = [1, 2, 3];

for i in z :
    print('for', i);

print('out of scope', i);

print(locals());

```

returns under

```
for 1
for 2
for 3
out of scope 3
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': 'path-to-directory\\test_0706.py', 'z': [1, 2, 3], 'i': 3}
```

in other case, such as c and javascript, cannot access to variable "i" in common.
does it intentional issue? cannot understand why this occurs and seems bug.

# Your environment

- CPython versions tested on: 3.11.3
- Operating system and architecture: Win10 x64 22H2

**Comment by sunmy2019** [comment]
It is intentional.

**Comment by sunmy2019** [comment]
In short, "for loops" do not have their own scope.
https://docs.python.org/3/tutorial/classes.html#python-scopes-and-namespaces

https://stackoverflow.com/q/3611760/14406396
