### ISSUE TITLE
New warning: "'_Py_IsInterpreterFinalizing' undefined; assuming extern returning in"

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106406]
<img width="993" alt="Снимок экрана 2023-07-04 в 13 49 29" src="https://github.com/python/cpython/assets/4660275/72849196-4368-4368-a77b-d8584c8444db">

Looks like the reason for this is https://github.com/python/cpython/commit/bc7eb1708452da59c22782c487ae7f05f1788970#diff-42415407f8d0ef2d42e29d13d979f633e3543770e62c3871e1101ad532d336a8

I am working on a fix. PR is comming :)
CC @vstinner 

### Linked PRs
* gh-106408

**Comment by vstinner** [comment]
Oops right. I merged your PR.

Fixed by commit https://github.com/python/cpython/commit/80f1c6c49b4cd2bf698eb2bc3d2f3da904880dd2
