### ISSUE TITLE
random.randint make string

### ISSUE THREAD

**Issue by ghost** [python/cpython#106427]
Dear Python Development Team,

I hope this message finds you well. I am writing to report a bug that I have encountered in the random module of Python. Specifically, I believe there is an issue with the random.randint(a, b) function.

**Description:**
When utilizing the random.randint(a, b) function with the parameters set to (1, 10), I have noticed that the returned value is occasionally a string instead of an integer. This behavior contradicts the expected functionality of the function, as it is intended to generate a random integer between the specified bounds.

**Steps to Reproduce:**
Import the random module in Python.
Execute the code: random.randint(1, 10).

**Expected Result:**
The code should consistently return an integer between 1 and 10, inclusive.

**Actual Result:**
Occasionally, instead of returning an integer, the function produces a string as the output.

**Example of Incorrect Output:**
Returned value: "A"

**Environment Details:**
Python version 3.11.3
Operating system: Ventura 13.4 mac os

**Additional Information:**
I have tested this issue on multiple machines running different operating systems, and the problem persists. It occurs sporadically, and I have not been able to identify any specific patterns or triggers for this behavior.

I have also reviewed the Python documentation for the random.randint(a, b) function, and there is no mention of any potential issues or limitations that could lead to this unexpected outcome.

Please let me know if you require any further information or if there are any steps I can take to help diagnose and resolve this bug. I am eager to assist in any way I can to ensure the stability and reliability of Python.

Thank you for your attention to this matter, and I look forward to your response.

**Comment by methane** [comment]
Please provide smallest but complete code to reproduce.

**Comment by methane** [comment]
I can not reproduce it with this code.

```py
import random

def main():
    for i in range(100):
        for _ in range(1000000):
            j = random.randint(1,10)
            if type(j) != int:
                print(f"{j=!r} ({type(j)})")
                break
        #print(f"{i=!r}")

main()
```

I think bug is very likely in your code, not random.randint.
That's why providing reproducible code is very important when reporting issue.

**Comment by terryjreedy** [comment]
I ran the following on Windows with no problems.
```
for i in range(100_100_000):
    if type(j:=ri(1, 10)) is not int:
        print(i, j, type(j))
    if not i % 10_000_000:
        print(i)
```
Ditto in Macbook Air with Catalina for 10_000_000.

Note: randint(min, max) = Random().randint = Random().randrange(min, max+1, 1)
= min + Random()._randbelow(max+1 - min) = (for min=1) 1 + Random().randbelow(max).
`self._randbelow(n)` compares possible return values to n before returning them, so it cannot
return anything that does not compare to `n (max)`, and strings are not comparable to ints.

**Comment by chgnrdv** [comment]
Is code being ran in interactive interpreter? Is return value exactly a string literal `'A'` or just A letter without any quotes? Is some exotic `sys.displayhook` was set before code being run, like in this example?
```python
>>> import sys
>>> def my_displayhook(o):
...     if isinstance(o, int):
...         print(hex(o)[2:].upper())
...     else:
...         print(repr(o))
... 
>>> sys.displayhook = my_displayhook
>>> import random
>>> random.randint(1, 10)
3
>>> random.randint(1, 10)
A
```
Could it be some weird encoding/terminal issue that forces one of digit characters to be printed as A character?

**Comment by hugovk** [comment]
You're getting a string because you're converting to a string:

You're converting a digit to hexadecimal and removing the "0x" prefix:

```python
print(hex(o)[2:].upper())
```

https://docs.python.org/3/library/functions.html#hex

https://simple.m.wikipedia.org/wiki/Hexadecimal

https://docs.python.org/3/library/sys.html#sys.displayhook

Please remember to include a minimal code sample next time.

**Comment by amirshnll** [comment]
```
def generate_verify_code(length=6):
    """Generate a verification code of specified length using randint."""
    min_value = 10 ** (length - 1)
    max_value = (10**length) - 1
    return random.randint(min_value, max_value)
```

**Comment by methane** [comment]
@amirshnll It produce integer always.

**Comment by amirshnll** [comment]
Hey @methane , I checked this function in a loop 10 million times, and on two occasions, it produced non-numeric characters.

![photo_2023-07-05_15-42-29](https://github.com/python/cpython/assets/30009591/4b47d816-a342-4edb-b964-54fe95b939e5)
![photo_2023-07-05_15-42-34](https://github.com/python/cpython/assets/30009591/ece58e66-dc77-4981-954c-f3f08fcb9284)

**Comment by methane** [comment]
Your code isn't complete.
There can be a bug between your function and your screenshot.

**Comment by chgnrdv** [comment]
@amirshnll, what is this UI element in which the verification code is displayed? Where and how the return value of `generate_verify_code` function is used?
As mentioned above, `random.randrange` cannot return non-integer value under any circumstances, so there is probably a bug in your own code, namely in the one that represents verification code value as a string.

Since there is no bug in Python itself, it is beyond of scope of issue tracker. If you need help with your Python code, you can create a topic at [discuss forum](https://discuss.python.org/c/users/7).
