### ISSUE TITLE
Can't build python service on server

### ISSUE THREAD

**Issue by josephsachdeva** [python/cpython#106413]
# Crash report

We have a docker version 20.10.7 and from today morning, whenever we are trying to re-build the service it is going into restart mode.

# Error messages
```
  File "/usr/local/lib/python3.8/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

# Your environment
Ubuntu VERSION="18.04.6 LTS (Bionic Beaver)"
Docker Version: 20.10.7

Someone updated the python:3.8 base images, and we have tried this on multiple servers, the issue remains the same. So it looks like there's an error with the docker updates

**Comment by ericvsmith** [comment]
Where did you get the docker image?

**Comment by sunmy2019** [comment]
Potentially related https://github.com/python/cpython/issues/106038

**Comment by sunmy2019** [comment]
What's your base OS?

**Comment by iritkatriel** [comment]
Closing as the OP is not responding to followup questions, and we have another issue for (probably) the same problem.
