### ISSUE TITLE
Missing Deprecation Notice for typing.Callable Alias in the Deprecated Aliases section

### ISSUE THREAD

**Issue by ColemanDunn** [python/cpython#106461]
# Documentation

typing.Callable is not listed as a deprecated alias under https://docs.python.org/3/library/typing.html#deprecated-aliases. 

However, it IS listed here: https://docs.python.org/3/library/typing.html#typing.Callable and states "Deprecated alias to [collections.abc.Callable](https://docs.python.org/3/library/collections.abc.html#collections.abc.Callable)". But not having it anywhere in the [Depricated Aliases section](https://docs.python.org/3/library/typing.html#deprecated-aliases) of the docs is confusing as the only depreciation notice lies outside of this section. 

It seems like it could fit under this section: https://docs.python.org/3/library/typing.html#aliases-to-container-abcs-in-collections-abc as the language used in this section ("Deprecated alias to collections.abc.[...]") closely matches the language used callable depreciation notice, but I am not entirely sure it if fits the "container" description.

I suggest adding the deprecation notice to the [Depricated Aliases section](https://docs.python.org/3/library/typing.html#deprecated-aliases).

That is all! Thanks!

### Linked PRs
* gh-106462
* gh-106574
* gh-106575

**Comment by AlexWaygood** [comment]
Luckily for you, I had already been working on this, just hadn't got round to making a PR yet :)

Please see https://github.com/python/cpython/pull/106462.

**Comment by AlexWaygood** [comment]
Fixed and backported. The updates should appear in the online docs in the next day or so.

Thanks for the report @ColemanDunn!
