### ISSUE TITLE
Reduce the number of materialized instance `__dict__`s

### ISSUE THREAD

**Issue by markshannon** [python/cpython#106485]
Accessing the `__dict__` attribute of an object causes the dictionary to be materialized.
This has a negative impact on performance.
We should provide means to access the `__dict__` without forcing materialization, which can be used in copy, pickle and any third party code that chooses to.

I propose two new methods on `object`:
* `__dict_copy__(self)`, which will be equivalent to `self.__dict__.copy()`, but without materializing the dictionary of objects with virtual dictionaries.
* `__dict_update__(self, arg)`, which will be equivalent to `self.__dict__.update(arg)`, but without materializing the dictionary of objects with virtual dictionaries.

### Linked PRs
* gh-106496
* gh-106539
* gh-107837
* gh-107843

**Comment by brandtbucher** [comment]
I opened a draft PR for an alternate approach, which aggressively "un-materializes" `__dict__`s in `LOAD_ATTR_WITH_HINT`.

**Comment by kumaraditya303** [comment]
This change seems to be causing crashes on buildbots. See https://buildbot.python.org/all/#/builders/123/builds/813 as example.

**Comment by markshannon** [comment]
Two more things to fix:
* Instances created by `copy.deepcopy` do not get their `__dict__`s dematerialized.
* We shouldn't be creating dictionaries in `_PyObjectDict_SetItem` for objects with managed `__dict__`s if the key is in the shared keys.

**Comment by hugovk** [comment]
Is there more to do here, or can we close this issue?
