### ISSUE TITLE
Double-click the resulting window in the upper left corner to exit | 双击创建的窗口左上角莫名会退出

### ISSUE THREAD

**Issue by 80zhangyan** [python/cpython#106578]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:
![image](https://github.com/python/cpython/assets/124112295/c8d9d24f-f851-4956-b888-f4cb138ca5e2)

**Comment by 80zhangyan** [comment]
I think this may be a BUG

**Comment by gaogaotiantian** [comment]
This is a Windows feature and not related to CPython. You can try it out on file explorer, it behaves the same.

**Comment by 80zhangyan** [comment]
> 这是 Windows 功能，与 CPython 无关。你可以在文件资源管理器上尝试一下，它的行为是一样的。

Thank you for your answer

**Comment by terryjreedy** [comment]
To be clear, on Windows, double clicking the window icon, in this case the tk feather, closes the window.  Double clicking the window title, in this case 'tk', maximizes or restores.  LOL, I never knew this.  I verified on Command Prompt window.

@80zhangyan Please ask about possible bugs on https://discuss.python.org/c/users/7 or other user help forums.
