### ISSUE TITLE
 Incorrect Behavior when Updating Individual Elements in a Python Array

### ISSUE THREAD

**Issue by mohanprasat-h** [python/cpython#106562]
I encountered a particular issue while trying to update individual elements within a 2D array in Python3.11.4. Here are the details of the problem:

Issue:
I initialized a 4x4 array using the following code:
```
array = [[0]*4]*4
print(array)
```

Expected Result:
I anticipated the output to be:
```
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
```

However, the actual result was as expected. So far, everything seemed fine. However, when I tried to update a specific element, specifically `array[0][0]`, to the value of 1 using the following code:
```
array[0][0] = 1
```

Expected Result:
I anticipated that the array would be updated as follows:
```
[[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
```

Actual Result:
Unfortunately, the actual result differed from my expectations. Instead of only updating array[0][0], the change was propagated to every element in the first column, resulting in the entire column being modified:
```
[[1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0], [1, 0, 0, 0]]
```

This behavior is unexpected and does not align with my intention to update only a single element within the array. It seems that modifying one element affects the entire column.

Please forgive me if the question was stupid.

**Comment by hugovk** [comment]
This isn't a Python bug nor a stupid question, it's not obvious at first glance what's going on.

When you do `[[0]*4]*4`, you're creating and re-using that inner `[0]*4` list object four times in the outer list.

Instead, do something like this:

```pycon
>>> array2 = [[0 for x in range(4)] for y in range(4)]
>>> array2
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
>>> array2[0][0] = 1
>>> array2
[[1, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
```

See https://stackoverflow.com/a/240205/724176 for more.
