### ISSUE TITLE
Add a collection of offsets to facilitate the work of out-of-process debuggers

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#106597]
Some of the relevant fields in the interpreter state and the frame state in 3.12 are very challenging to fetch from out-of-process tools because they are in offsets that depend on compilation or platform variables that are different in different platforms. Not only that but they require the tools to copy a huge amount of intermediate structures making the whole thing very verbose.

To allow out-of-process tools to get these offsets without having to copy the headers (which also doesn't really work as some of these fields may depend on compilation flags and other parameters), add a debugging struct to the runtime state (which is the entry point many of these tools need anyway) that contain a list of the offsets that are relevant for out-of-process tools.

This list will not be backward compatible between minor versions but is expected to reflect the relevant fields for all the life of a minor version.

We can add more fields to the struct in the future at our leisure. 

See https://github.com/python/cpython/issues/106140 and https://github.com/python/cpython/issues/100987 and https://github.com/python/cpython/pull/105271 for more information.

### Linked PRs
* gh-106598
* gh-121311
* gh-121312
* gh-121369
* gh-121370

**Comment by hugovk** [comment]
Is there more to do here, or can we close this issue?

**Comment by pablogsal** [comment]
We can close it for now 👍
