### ISSUE TITLE
```os.system("cd path")``` can not change the dir

### ISSUE THREAD

**Issue by littlewhitecloud** [python/cpython#106582]
# Bug report
```python
from os import system, getcwd

system(r'cd C:\ ') # Change the dir to the C:\
print(getcwd()) # Still the old dir nothing changed
```
Use this line cannot change the dir.

# Environment
- CPython versions tested on: 3.9.0
- Operating system and architecture: Windows 10 22H2 19045.3031

**Comment by JelleZijlstra** [comment]
That's because `os.system` invokes a separate shell process, and the `cd` only changes that shell's working directory.

Use `os.chdir` instead.
