### ISSUE TITLE
Deprecate PyObject_SetAttr(obj, name, NULL): PyObject_DelAttr(obj, name) must be used instead

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106572]
When ``PyObject_SetAttr()`` is called with a ``NULL`` value, it's unclear if the caller wants to remove the attribute on purpose, or if the value is ``NULL`` because of an error. Such API is error prone and should be avoided.

In 2005, this feature was already deprecated in the documentation in issue #69887 by commit 45be8d67be0083c923ca31e4803de861177a2383.

I propose to now emit a DeprecationWarning and schedule the removal of this feature in Python 3.15. If too many C extensions rely on this current behavior, we can consider removing the feature later.

### Linked PRs
* gh-106573
* gh-106611

**Comment by vstinner** [comment]
python-dev discussion in 2015: https://mail.python.org/archives/list/python-dev@python.org/thread/OSKS23WDHU67NQCANPNSAPHATZ2J3W7T/

**Comment by vstinner** [comment]
I wrote issue #105373 to remove the deprecation in the documentation, but @serhiy-storchaka wrote that the deprecation should stay: https://github.com/python/cpython/pull/105374#issuecomment-1579207740

Copy of his message:

---
The Gmane link no longer work, the working links to the discussion (it was split on several threads) are
https://mail.python.org/archives/list/python-dev@python.org/thread/OSKS23WDHU67NQCANPNSAPHATZ2J3W7T/
https://mail.python.org/archives/list/python-dev@python.org/thread/UJI3KJQVOY7VELTDJOBTBWM3TYDHEYGD/

The problems with the current behavior:
1. It looks confusing that some of `*Set*` functions do removing, while other raise SystemError or crash. Ideally, all such functions should either support deletion by specifying NULL, or raise SystemError. A crash is acceptable too, for performance.
2. It is a bug magnet. It is easy to get the NULL pointer instead of a pointer to object (just forgot to check for error) and delete instead of set.

Changing the current behavior is a long process. M.-A. Lemburg specified the required procedure. It is interesting, that if we started it in 3.6, it would already be finished.

**Comment by vstinner** [comment]
I reported this error prone API as https://github.com/capi-workgroup/problems/issues/47

**Comment by vstinner** [comment]
We should consider deprecating similar APIs used to delete an item/attribute:

* ``PyObject_SetItem(obj, key, NULL)``: use ``PyObject_DelItem(obj, key)`` instead
* ``PyMapping_SetItemString(obj, key, NULL)``: use ``PyMapping_DelItemString(obj, key)`` instead
* ``PySequence_SetItem(obj, index, NULL)``: use ``PySequence_DelItem(obj, index)`` instead
* ``PySequence_SetSlice(obj, i1, i2, NULL)``: use ``PySequence_DelSlice(obj, i1, i2)`` instead

**Comment by serhiy-storchaka** [comment]
Unfortunately, adding a warning will break binary compatibility. Code compiled with older Python version which uses `PyObject_DelAttr()` calls `PyObject_SetAttr()`, because `PyObject_DelAttr()` was implemented as a macro.

We should first implement `PyObject_DelAttr()` as a separate function, then in some distant future we decide to break binary compatibility with Python older than 3.13 and add a warning, then error, in `PyObject_SetAttr()`.

**Comment by vstinner** [comment]
I close the issue: see https://github.com/python/cpython/pull/106573#issuecomment-1649701820
