### ISSUE TITLE
C API: Add PyObject_GetOptionalAttr() function

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#106521]
It is a new name of former `_PyObject_LookupAttr()` added in #76752.

```c
int PyObject_GetOptionalAttr(PyObject *obj, PyObject *attr_name, PyObject **result);
```

Discussion about making it public and naming: https://discuss.python.org/t/make-pyobject-lookupattr-public/29104.

See also other new functions with similar interface in #106307 and #106004.

### Linked PRs
* gh-106522
* gh-106642

**Comment by vstinner** [comment]
I added PyObject_GetOptionalAttr() and PyObject_GetOptionalAttrString() to pythoncapi-compat: https://github.com/python/pythoncapi-compat/commit/157d6d432831c739fe601f70ec7623b0b71febba

**Comment by carljm** [comment]
PRs are merged, this looks done.
