### ISSUE TITLE
Document PEP 387 Soft Deprecation

### ISSUE THREAD

**Issue by vstinner** [python/cpython#106535]
# Documentation

Document https://peps.python.org/pep-0387/#soft-deprecation

### Linked PRs
* gh-106536
* gh-105735
* gh-106859

**Comment by ncoghlan** [comment]
Note that PEP 389 specifically stated that `getopt` was *not* deprecated: https://peps.python.org/pep-0389/#updates-to-getopt-documentation

Follow-up on this in #126225
