### ISSUE TITLE
dict can have the same key twice

### ISSUE THREAD

**Issue by AliRn76** [python/cpython#106507]
# Bug report
I have a `dict` named `self.content` which can have the `same key` twice
Here is the screenshot of the problem:
![Screenshot from 2023-07-07 13-26-10](https://github.com/python/cpython/assets/40032682/eb29593e-e5a5-42c8-87dd-34f6df2819dc)

**You can see the problem yourself by running [PantherDB](https://github.com/AliRn76/pantherdb) tests with `python3.12`**

# Your environment
- **CPython Version:** 3.12.0~b3-1+jammy1
- **Depends:** python3.12-minimal (= 3.12.0\~b3-1+jammy1), libpython3.12-stdlib (= 3.12.0\~b3-1+jammy1), mime-support

- **OS:** Ubuntu 22.04.2 LTS x86_64
- **Kernel:** 5.19.0-45-generic
- **CPU:** Intel i5-7200U (4) @ 3.100GHz

**Comment by hugovk** [comment]
Please can you provide a minimal, runnable, self-contained code snippet that reproduces the problem, and post it as plaintext rather than a screenshot?

**Comment by AliRn76** [comment]
> Please can you provide a minimal, runnable, self-contained code snippet that reproduces the problem, and post it as plaintext rather than a screenshot?

This problem does not happen in simple scenarios, and that's why I put the screenshot & The source code that made this issue _(line below the screenshot)_

**Comment by pochmann** [comment]
I'd have something to try, but I can't copy&paste text from a screenshot :-(

**Comment by hugovk** [comment]
> > Please can you provide a minimal, runnable, self-contained code snippet that reproduces the problem, and post it as plaintext rather than a screenshot?
> 
> This problem does not happen in simple scenarios, and that's why I put the screenshot & The source code that made this issue _(line below the screenshot)_

Please see https://stackoverflow.com/help/minimal-reproducible-example -- reducing your code as much as possible to the smallest bit that reproduces the problem _really_ helps us investigate, and it might help you find problems on your side in the process.

Cloning your repo and installing all its dependencies and so on, adds many more (thousands?) of lines of code to investigate. Plus we need to figure out all those steps, which takes more time away from investigating this, and working on other things. And as mentioned, we can't copy and paste from screenshots, so if including screenshots, please also include plaintext.

Thank you!

**Comment by AliRn76** [comment]
Here is the code:
It only required `orjson` (I found out it is ok with `json`) and require to working with file
_This code works well in other python versions_

I put some print for you on line ~= 60 

```python
from __future__ import annotations
import os
import os.path
import orjson as json
from unittest import TestCase


class PantherDB:
    db_name: str = 'database2.pdb'
    __content: dict = {}

    def __init__(self, db_name: str):
        self.__content = {}
        self.db_name = db_name

        if not os.path.exists(self.db_name):
            open(self.db_name, 'w').close()

    @property
    def content(self) -> dict:
        return self.__content

    def _write(self) -> None:
        content = json.dumps(self.__content)
        with open(self.db_name, 'bw') as file:
            file.write(content)

    def _refresh(self) -> None:
        with open(self.db_name, 'rb') as file:
            data = file.read()
            if data == b'':
                self.__content = {}
            else:
                self.__content = json.loads(data)

    def collection(self, collection_name: str) -> PantherCollection:
        return PantherCollection(
            db_name=self.db_name,
            collection_name=collection_name
        )


class PantherCollection(PantherDB):
    collection_name: str

    def __init__(self, db_name: str, collection_name: str):
        super().__init__(db_name=db_name)
        self.collection_name = collection_name

    def _write_collection(self, documents: list) -> None:

        print(f'Keys Before:\t{self.content.keys()}')  # For Debugging

        self.content[self.collection_name] = documents

        # # # # For Debugging
        print(f'New Key:\t{self.collection_name}')
        print(f'Keys After:\t{self.content.keys()}')
        if len(self.content.keys()) == 2:
            print(f'First Key:\t{[*self.content.keys()][0]}')
            print(f'Second Key:\t{[*self.content.keys()][1]}')
            print([*self.content.keys()][0] == [*self.content.keys()][1])
        print()
        # # #

        self._write()

    def _get_collection(self) -> list[dict]:
        """return documents"""
        self._refresh()
        return self.content.get(self.collection_name, [])

    def insert_one(self, **kwargs) -> dict:
        documents = self._get_collection()
        kwargs['_id'] = len(documents) + 1
        documents.append(kwargs)
        self._write_collection(documents)
        return kwargs


if __name__ == '__main__':
        db = PantherDB('database2.pdb')

        collection = db.collection('CollectionName')
        obj1 = collection.insert_one(first_name='FirstName1', last_name='LastName1')
        obj2 = collection.insert_one(first_name='FirstName2', last_name='LastName2')

        # assert obj2['_id'] == 2

        os.remove('database2.pdb')

```

**Comment by hugovk** [comment]
It sounds like an orjson issue. I don't have a Rust compiler to install orjson for Python 3.12.

Thanks for the self-contained, runnable code snippet! The next step is to aim for _minimal_.

> Minimal: Use as little code as possible that still produces the same problem

Tips:

> **Minimal**
> The more code there is to go through, the less likely people can find your problem. Streamline your example in one of two ways:
> 
> 1. **Restart from scratch.** Create a new program, adding in only what is needed to see the problem. > Use simple, descriptive names for functions and variables – don’t copy the names you’re using in your existing code.
> 2. **Divide and conquer.** If you’re not sure what the source of the problem is, start removing code a bit at a time until the problem disappears – then add the last part back.

Please could you try removing irrelevant bits of code to make it as small as possible?

**Comment by ronaldoussoren** [comment]
This might be a bug in orjson, it uses private APIs like ``_PyDict_SetItem_KnownHash`` which can result in duplicate keys when the caller provides the wrong hash value for a key.

**Comment by AliRn76** [comment]
@hugovk Thank you for your time and help

Here is the minimal code with some `print`, which we can create `content` dict with 2 identical `key`

```python
import os.path
import orjson as json


file_name = 'database.pdb'


def read_file() -> dict:
    with open(file_name, 'rb') as file:
        return json.loads(file.read())


def write_file(content) -> None:
    with open(file_name, 'wb') as file:
        file.write(json.dumps(content))


def insert_to_file():
    content = read_file()

    content['key'] = 'value'

    print(content.keys())  # dict_keys(['key', 'key'])
    if len(content.keys()) > 1:
        print([*content.keys()][0] == [*content.keys()][1])  # True
        print(*[*content.keys()][0].encode())  # 107 101 121
        print(*[*content.keys()][1].encode())  # 107 101 121

    write_file(content)


if __name__ == '__main__':
    write_file({})

    insert_to_file()
    insert_to_file()

    os.remove(file_name)
```

**Comment by sunmy2019** [comment]
> Here is the minimal code

not minimal enough

**Comment by sunmy2019** [comment]
Two keys have different hash value.

```py
import orjson


content = orjson.loads(b'{"key":"value"}')

content['key'] = 'value'
print(content.keys())

print(hash([*content.keys()][0]), hash([*content.keys()][1]))  # True

print(hash("key"))
```

on 3.12

```py
dict_keys(['key', 'key'])
-7981711143384484130 -2493793918196975134
-2493793918196975134
```

**Comment by bityob** [comment]
On Windows it works fine 

```python
import orjson

content = orjson.loads(b'{"key":"value"}')

content['key'] = 'value'
print(content.keys())
```

Output -
```
dict_keys(['key'])
```

Version -
```
>>> sys.version
'3.12.0a5 (tags/v3.12.0a5:3c67ec3, Feb  7 2023, 16:36:51) [MSC v.1934 64 bit (AMD64)]'
>>> orjson.__version__
'3.9.1'
```

**Comment by sunmy2019** [comment]
> On Windows it works fine

Can you try this:

```py
import orjson

content = orjson.loads(b'{"key":"value"}')

print(hash([*content.keys()][0]), hash("key"))
```

**Comment by sunmy2019** [comment]
This is definitely related to `orjson`. You should report there.

**Comment by bityob** [comment]
> ```python
> import orjson
> 
> content = orjson.loads(b'{"key":"value"}')
> 
> print(hash([*content.keys()][0]), hash("key")) # expect the same
> ```

Output on Windows -
```
-3893045467968269981 -3893045467968269981
```

Same

**Comment by ronaldoussoren** [comment]
> Two keys have different hash value.
> 
The same code does work correctly on Python 3.11.   That doesn't mean there's a bug in Python itself though, there's a lot of moving parts in orjson and the libraries it uses. I've quickly scanned through parts of the orjson code and it appears to construct string objects manually (see https://github.com/ijl/orjson/blob/master/src/str/create.rs#L27) instead of using public APIs.

@AliRn76: please check with the orjson project.

**Comment by sunmy2019** [comment]
bisected to ea2c0016502472aa8baa3149050ada776d17a009 which changes `str` layout.

`orjson` is using internal APIs relying on the old layout.
https://github.com/ijl/orjson/blob/8686b2255f1adfec844e4507ef74de3dc58039a9/src/str/ffi.rs#L9-L24

Not CPython's fault.

> '3.12.0a5 (tags/v3.12.0a5:3c67ec3, Feb  7 2023, 16:36:51) [MSC v.1934 64 bit (AMD64)]'

bisect result shows it affects >= 3.12b1.

**Comment by AliRn76** [comment]
Response of orjson owner:
> I don't see this reproducing with orjson 3.9.2 and Python 3.12.0b3. In any case the most important thing to mention was that this is apparently happening with a prerelease version of Python.

_Originally posted by @ijl in https://github.com/ijl/orjson/issues/404#issuecomment-1626188267_
