### ISSUE TITLE
`_sre.template` crashes in case of negative or non-integer group index

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#106524]
`_sre.template` crashes if `template` argument contains group index that is negative or not an `int` instance.
Examples:
```python3
>>> import _sre
>>> _sre.template("", ["", -1, ""])
Segmentation fault (core dumped)
```
```python3
>>> _sre.template("", ["", (), ""])
Segmentation fault (core dumped)
```
In `_sre_template_impl` part of `self->items` remains uninitialized if call to `PyLong_AsSsize_t` returns negative value or fails with exception. Then attempt to clear `self->items[i].literal` in `template_clear` leads to dereferencing of uninitialized pointer.

Not sure if this worth fixing, since `_sre.template` is an internal implementation detail that is used only in `_compile_template` function, where it accepts only (I guess) correct templates created in `_parser.parse_template` function, and additional checks/initialization can affect its performance. But I'll submit a PR anyway.

### Linked PRs
* gh-106525
* gh-106544

**Comment by terryjreedy** [comment]
In Windows with 3.12.0b3 installed, I just get 'TypeError: invalid template'

**Comment by chgnrdv** [comment]
@terryjreedy, sorry, I should have mentioned that Python needs to be build in debug mode, or with ASAN enabled.
