### ISSUE TITLE
Color method for str object

### ISSUE THREAD

**Issue by sbOogway** [python/cpython#106658]
EXAMPLE 
```python
"hello".color('green')
```
```
\033[91mHello, World!\033[0m // in bash would appear green
```

the method wraps the string with ansi escape code and returns it colored for display in terminal window.

**Comment by carljm** [comment]
Python strings are used for many different purposes and in many different contexts. `"hello".color('green')` won't do what it claims to do if the resulting string is displayed on a web page, for example.

IMO this feature belongs in a terminal display library (of which there are many to choose from in Python), not as a method on the core `str` type.

If you want to push for this feature, please bring it up on https://discuss.python.org/c/ideas/6 first, as requested by the new-issue template. Only open an issue here if there is significant support in a Discuss thread in favor of the feature (and link to the Discuss thread in your issue, again as requested in the new-issue template.)
