### ISSUE TITLE
removing "& key.events" part from selectors.py module.

### ISSUE THREAD

**Issue by amirsoroush** [python/cpython#106686]
I was wondering why we have `& key.events` part here: 

https://github.com/python/cpython/blob/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L337

After the line 333, `events` is either `1`, `2` or `3`. Can't we just use `events` instead of `events & key.events` ?

file descriptors are already checked and added to the relevant `set` in `.register()` method:

https://github.com/python/cpython/blob/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L300-L303

I doubt that `events` and `events & key.events` can be different.

This pattern is repeated [here](https://github.com/python/cpython/blob/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L427), [here](https://github.com/python/cpython/blob/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L480), and [here](https://github.com/python/cpython/blob/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L575)

Thanks.

**Comment by sunmy2019** [comment]
You can use git blame for the history, and find out who wrote that piece of code in the first place.

https://github.com/python/cpython/blame/7f55f58b6c97306da350f5b441d26f859e9d8f16/Lib/selectors.py#L300-L303

**Comment by sunmy2019** [comment]
Usually, we won't change a legacy code unless we have a good reason and after thorough consideration.
