### ISSUE TITLE
Minor documentation issues in asyncio BaseEventLoop

### ISSUE THREAD

**Issue by Spycho** [python/cpython#106634]
Firstly:

https://github.com/python/cpython/blob/a2d54d4e8ab12f967a220be88bde8ac8227c5ab3/Lib/asyncio/events.py#L620

I think the `AbstractEventLoopPolicy`'s `get_event_loop` function should not say:

> Returns an event loop object implementing the BaseEventLoop interface

But rather:

> Returns an event loop object implementing the **AbstractEventLoop** interface

`AbstractEventLoop` is more of a representation of the interface than `BaseEventLoop`, and `AbstractEventLoop` is the class that the docs instruct people to extend if they want to have a custom event loop, and specifically say to not extend `BaseEventLoop`. It's also easier to look at the interface via `AbstractEventLoop`, without all the implementation details getting in the way.

Secondly:

https://github.com/python/cpython/blob/64c0890b697783db9b3f67e3bb4dcee1165a0b9b/Lib/asyncio/base_events.py#L730

Grammar error:
> If two callbacks are scheduled for exactly the same time, it undefined which will be called first.

should read:
> If two callbacks are scheduled for exactly the same time, it **is** undefined which will be called first.

### Linked PRs
* gh-106671
* gh-106711
* gh-106712

**Comment by gvanrossum** [comment]
Go ahead and create a PR. The Abstract/Base issue is worthy of fixing, the other can be fixed while you're at it.
