### ISSUE TITLE
PEP 669 is not documented in 3.12 docs

### ISSUE THREAD

**Issue by jpe** [python/cpython#106692]
# Documentation

Unless I'm missing something, the inclusion of PEP 669 doesn't seem to be documented in the Python 3.12 docs -- I can't find mention of it in what's new (I searched for 669 and didn't find anything) and monitoring isn't in the docs for the sys module.

**Comment by hugovk** [comment]
Thanks for the report, we have https://github.com/python/cpython/issues/103082 to track documenting the PEP. 

Let's close this as a duplicate.
