### ISSUE TITLE
New warning in `ssl.c`: conversion from 'uint64_t' to 'long', possible loss of data

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106687]
See https://github.com/python/cpython/pull/106678/files#diff-89879be484d86da4e77c90d5408b2e10190ee27cc86337cd0f8efc3520d60621

<img width="1064" alt="Снимок экрана 2023-07-12 в 21 12 39" src="https://github.com/python/cpython/assets/4660275/108ee61c-1352-465b-98a2-c429d9cc5834">

### Linked PRs
* gh-106700
* gh-106827
* gh-116665

**Comment by vstinner** [comment]
I wrote PR #106700 to fix the compiler warning.

**Comment by sobolevn** [comment]
Thank you, @vstinner!
