### ISSUE TITLE
Make uop executor objects variable length

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#106608]
Currently `_PyUOpExecutorObject` contains a fixed-length (`_Py_UOP_MAX_TRACE_LENGTH`, 32) array of micro instructions. We should switch to the usual variable-length array (making it a `PyVarObject`) so that we can make the largest superblock larger without paying the memory overhead cost for the full array.

### Linked PRs
* gh-107411
* gh-107531

**Comment by gvanrossum** [comment]
This should be easy for someone with C experience. There are many examples in the CPython code base that do a similar thing. Basically the struct should be declared to end with `_PyUOpInstruction trace[1];` and be given a size field, and various uses of the struct should be updated. I do expect a contributor taking this up to do their own research on how to build CPython, etc.

**Comment by dalalvarun** [comment]
I want to give it a try @gvanrossum

**Comment by gvanrossum** [comment]
@dalalvarun Go for it. Let me know if you get stuck.

**Comment by kgdiem** [comment]
Based on your description above I started off trying to base the implementation of `trace` off of a `PyListObject` /  `PySetObject`;

From your description though,`PyExecutorArray` seemed to fit your description of the implementation better:
> Basically the struct should be declared to end with _PyUOpInstruction trace[1]; and be given a size field

```
typedef struct {
    int size;
    int capacity;
    struct _PyExecutorObject *executors[1];
} _PyExecutorArray;
```

But this seems to be in conflict with the aim of avoiding having to copy everything into a new, larger array.

My questions:
1. Is something similar to a `PyListObject` but without all the casts the aim? 
 2. Should there be a new `_Py_UOP_MAX_TRACE_LENGTH` or should the size of the trace be `SSIZE_MAX`?

**Comment by gvanrossum** [comment]
@kgdiem Good questions. What I had in mind is not like `PyListObject` (which merely has a pointer to a separately malloc'ed array). It's more like a `PyTupleObject`. The struct you show is closer to what I have in mind, but we don't need a `capacity` field, and it should be an object. The idea is that the trace is initially written to a temporary buffer (`_PyUOpInstruction trace[_Py_UOP_MAX_TRACE_LENGTH]` in `uop_optimize`), and then a `_PyUOpExecutorObject` is allocated of the right size, into which the trace is copied. The role of `_Py_UOP_MAX_TRACE_LENGTH` will be reduced to the size of the temporary buffer.

**Comment by gvanrossum** [comment]
Looks like @rdrf2838 won the race.
