### ISSUE TITLE
__annotations__ on NamedTuple do not work

### ISSUE THREAD

**Issue by jc211** [python/cpython#106668]
NamedTuple does not have `__annotations__` set. 

In our usecase,  we were testing these NamedTuples: https://github.com/TimSchneider42/python-natnet-client/blob/8b321077d68c27b9566f48298eaf65879dc8823c/natnet_client/data_frame.py#L10C1-L11C1 

# Your environment

Windows 11
Python 3.11

**Comment by AlexWaygood** [comment]
To be clear, `__annotations__` are set on NamedTuple classes created via the class-based syntax or the call-based syntax. However, subclasses of NamedTuple classes do not inherit `__annotations__` from the NamedTuple class they inherit from:

```pycon
>>> from typing import NamedTuple
>>> class Foo(NamedTuple):
...   x: int
...   
>>> Foo.__annotations__
{'x': <class 'int'>}
>>> Bar = NamedTuple('Bar', [('x', int)])
>>> Bar.__annotations__
{'x': <class 'int'>}
>>> class Baz(NamedTuple('Eggs', [('x', int)])): ...
... 
>>> Baz.__annotations__
{}
```

`Baz` is not a NamedTuple class; it's a subclass of a NamedTuple class. Observe how `Bar` and `Baz` have different mros:

```pycon
>>> Bar.__mro__
(<class '__main__.Bar'>, <class 'tuple'>, <class 'object'>)
>>> Baz.__mro__
(<class '__main__.Baz'>, <class '__main__.Eggs'>, <class 'tuple'>, <class 'object'>)
```

The current behaviour with `__annotations__` seems to me to be the correct behaviour, as it matches what you get with any other subclass when it comes to `__annotations__`:

```pycon
>>> class Spam:
...   x: int
...   
>>> Spam.__annotations__
{'x': <class 'int'>}
>>> class Ham(Spam): pass
... 
>>> Ham.__annotations__
{}
```

If what you want is to merge the `__annotations__` dictionary of a given class and all of its superclasses, `typing.get_type_hints()` can do that for you:

```pycon
>>> import typing
>>> typing.get_type_hints(Baz)
{'x': <class 'int'>}
>>> typing.get_type_hints(Ham)
{'x': <class 'int'>}
```

**Comment by jc211** [comment]
Thanks for the clarification Alex. In my tests in python 3.8, the annotations were indeed inherited. Something must have changed in later versions. The library I linked relied heavily on this behavior. I think noting this change here might be valuable for others if the come looking.

**Comment by AlexWaygood** [comment]
Interesting. Have you tested using Python 3.10 and 3.9?

A lot changed in Python 3.10 with regard to  how `__annotations__` were handled; my guess would be that the behaviour change here came about as a result of those changes.

**Comment by AlexWaygood** [comment]
Indeed, https://docs.python.org/3/howto/annotations.html#annotations-howto mentions that all subclasses prior to Python 3.10 used to inherit their superclass's `__annotations__` dictionary.

The behaviour change is extensively documented in that article, the article is linked to from "What's new in Python 3.10", and nothing about the behaviour change in Python 3.10 is specific to NamedTuples. So I don't think we should add anything to the documentation for NamedTuples about this.
