### ISSUE TITLE
CompletedProcess: extraneous "\n" on stdout

### ISSUE THREAD

**Issue by david-thrower** [python/cpython#106604]
# Description:

When a script calls a subproces, for example, via subprocess.run(shell=True,capture_output=True), the implicit "\n" explicitly appears at the end of the content returned by CompletedProcess.stdout.decode("utf8"), where the trailing "\n" was not included in the intended output of the process. This can create inconsistencies when code or numerical parameters are being parsed by a subprocess.

Minimal reproducible example:

# Environment any recent Python distribution (3.8+)

## Worker job
worker.py
```python3
from fire import Fire

def foo(bar: int, baz: float)
    return bar * baz

if __name__ == "__main__":
    Fire(foo)
```

## Main script
orchestrator.py
```python3
from subprocess import run

completed = run('worker.py -foo 1 -bar 1.25', shell=True, capture_output=True)
if complete.returncode < 1:
    bundy = completed.stdout.decode("utf8")
else:
    some_log_function(completed.stderr.decode("utf8"))
    raise SomeException("Lorem ipsum") 
print(bundy)
```

Run this:
`python3 orchestrator.py`

You get:

```
"""1.25
"""
```

... where this was intended:

```
"1.25"
```

## This can break some functions that cast string representations of numbers to a numeric type or create inconsistencies in text or parsed dynamic code extracted from a subprocess. 

- CPython versions tested on: 3.10.6,  3.8.10,  3.11.1

- Operating system and architecture: Ubuntu 22.04; debian bullseye; x86

**Comment by terryjreedy** [comment]
In the example, `print(bundy)` adds '\n'.  If fire also did so

**Comment by sunmy2019** [comment]
This `\n` is added by this print call.
https://github.com/google/python-fire/blob/6e485c971f4998175b841c775edcd980f2fb55ea/fire/core.py#L276

You can use `rstrip` to deal with it as mentioned.
