### ISSUE TITLE
Tests / Docs / Docs fails on old PRs with blurb

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#106689]
The tests for PR #8150 were all green.  When I added a blurb for #8150, Tests / Docs / Docs failed because of the 4-digit number.
https://github.com/python/cpython/actions/runs/5534988528/jobs/10100701118?pr=8150
>Error: ../build/NEWS:751: ERROR: The GitHub ID '8150' seems too low"

The error occurred during the sphinx html build, but I have no idea where the misinformation is stored or what tracker this properly belongs on.

**Comment by hugovk** [comment]
The full message:

> Error: ../build/NEWS:751: ERROR: The GitHub ID '8150' seems too low -- use :issue:`...` for BPO IDs

It doesn't work with _PR_ numbers.

It's expecting either a GitHub _issue_ number, the lowest such began at 32426, from when we transferred issues over from https://bugs.python.org/

Or use the other format to specify a BPO ID.

I think the easiest thing is to create a new issue for the PR, and use that issue number.

**Comment by hugovk** [comment]
And here's where the error message comes from:

https://github.com/python/cpython/blob/e4b88c1e4ac129b36f99a534387d64f7b8cda8ef/Doc/tools/extensions/pyspecific.py#L69-L80

**Comment by terryjreedy** [comment]
There was no bpo issue: in the initial message, Ammar said "(Can be marked with skip issue and skip news as it pertains to the build process)" but I decided that a visible addition possibly used by non-core devs (to run coverage) should be mentioned.  I opened  #106690.
