### ISSUE TITLE
sysconfig imports pprint which imports the world

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#106789]
sysconfig imports pprint in order to print the config dict to a file. But this dict contains only strings and ints, so pprint is overkill.

The problem with importing pprint is that it imports dataclasses, which imports inspect, which imports dis which imports opcode which tries to import _opcode which does not exist in early stages of the build when sysconfig is used. So opcode imports _opcode in a try-except and ignores import errors. Since sysconfig doesn't need anything from _opcode, the partially constructed opcode module suffices. But this is flaky and hard to reason about (it works because it works).   It would be better if sysconfig didn't import so much.

### Linked PRs
* gh-106790

**Comment by gvanrossum** [comment]
Honestly I think that dataclasses shouldn't import inspect, and inspect shouldn't import dis. But if this is the easiest way to fix the issue at hand, let's do it.

**Comment by iritkatriel** [comment]
I'll look into that. Let's hold off merging this.

**Comment by FFY00** [comment]
Regardless of other possible solutions, I think removing the `sysconfig` dependency on `pprint` is a valuable contribution on its own, so I am happy with it being merged.
