### ISSUE TITLE
Add __length_hint__ to dict and to dict views

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#106764]
This will improve the performance of `list(d.values())` for example.

**Comment by terryjreedy** [comment]
Someone asked whether [this would really help](https://discuss.python.org/t/how-would-list-d-values-benefit-from-length-hint/29713) given that dicts have a `.__len__`.

**Comment by rhettinger** [comment]
@sunmy2019 This is an optimization, not a feature.

**Comment by rhettinger** [comment]
Yes, I think that would suffice.

**Comment by erlend-aasland** [comment]
> Yes, I think that would suffice.

It is unclear to me what the resolution of this issue was. It looks to me like this was abandoned. If not, was it implemented without a reference to the issue in the PR/commit title?

**Comment by sunmy2019** [comment]
> It looks to me like this was abandoned.

Same to me.
