### ISSUE TITLE
Streamline family syntax in Tools/cases_generator

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#106706]
The syntax to designate a family currently looks like this:
```
        family(store_subscr, INLINE_CACHE_ENTRIES_STORE_SUBSCR) = {
            STORE_SUBSCR,
            STORE_SUBSCR_DICT,
            STORE_SUBSCR_LIST_INT,
        };
```
Here the `store_subscr` "family name" is redundant (and in fact we even had [one case](https://github.com/python/cpython/pull/104268) where it was incorrect).

I propose to change it to be more similar to the `pseudo` syntax, so it will become
```
        family(STORE_SUBSCR, INLINE_CACHE_ENTRIES_STORE_SUBSCR) = {
            STORE_SUBSCR_DICT,
            STORE_SUBSCR_LIST_INT,
        };
```
This should be a straightforward change to the parser and code generator in Tools/cases_generator.

### Linked PRs
* gh-106716

**Comment by danik292** [comment]
Where I find thet code?

**Comment by gvanrossum** [comment]
In Tools/cases_generator/. The example is in Python/bytecodes.c.

**Comment by kgdiem** [comment]
I started working on this here: https://github.com/kgdiem/cpython/tree/streamline-family-syntax/Tools/cases_generator

It doesn't seem like the right thing to do is add the family name to the list of members in `parser.py`[1]. 

I think the correct course of action to change the validations `check_families`[2] (decrement member length requirement, ensure name is in the macro instructions) and make some simple updates to `write_metadata`[3] in`generate_cases.py`. 

Is that correct? 

[1] https://github.com/python/cpython/blob/main/Tools/cases_generator/parser.py
[2] https://github.com/python/cpython/blob/main/Tools/cases_generator/generate_cases.py#L809
[3] https://github.com/python/cpython/blob/main/Tools/cases_generator/generate_cases.py#L1171

WIP branch https://github.com/kgdiem/cpython/tree/streamline-family-syntax

**Comment by gvanrossum** [comment]
@kgdiem You got it!

**Comment by kgdiem** [comment]
> @kgdiem You got it!

Awesome! I had one question about changing one of the tests in my PR but I saw you opened another issue wrt them being broken ... 

https://github.com/python/cpython/issues/105540

**Comment by gvanrossum** [comment]
If you are ready for a review of your code, just make a PR and CC me.

**Comment by gvanrossum** [comment]
@kgdiem Thanks for your contribution! You're welcome to help out more any time.

**Comment by kgdiem** [comment]
> @kgdiem Thanks for your contribution! You're welcome to help out more any time.

Thanks! I'm interested in spending 5-10 hours/week working on Python/Python ecosystem but having some trouble finding another issue I can pick up.

**Comment by gvanrossum** [comment]
> Thanks! I'm interested in spending 5-10 hours/week working on Python/Python ecosystem but having some trouble finding another issue I can pick up.

Cool. May I inquire what motivates you to do this? And what kind of issues are you looking for? Can they involve C code?

**Comment by kgdiem** [comment]
> May I inquire what motivates you to do this? 
I enjoy it! I code as a hobby (and professionally) and want to do something beyond web development; high perf, systems programming, applied CS, etc 

> And what kind of issues are you looking for? Can they involve C code?
Ya. I started looking at the last issue you'd opened (106608) but was a bit intimidated and was trying to find something "easier" / more in my traditional wheelhouse.

In thinking about my reply here, re-reviewing the issue & related the code, I'm pretty confident and am going to give it a shot. I'll reach out over there if I need any help. 

Thanks again.

**Comment by gvanrossum** [comment]
Cool, see you at that issue. Be sure not to bang your head against the wall for too long -- ask for help before it starts bleeding! :-)
