### ISSUE TITLE
Mistake on docs of dis library of Python 3.8

### ISSUE THREAD

**Issue by TiZCrocodile** [python/cpython#106725]
# Documentation

In the documentation of Python 3.8, library dis, it says the opcode ROT_FOUR
is new in version 3.8, but its actually in version 3.0, also.
I read the description of the opcode and its also exactly the same description.

3.0 [ROT_FOUR](https://docs.python.org/release/3.0/library/dis.html#opcode-ROT_FOUR)
Lifts second, third and forth stack item one position up, moves top down to position four.
3.8 [ROT_FOUR](https://docs.python.org/release/3.8.17/library/dis.html#opcode-ROT_FOUR)
Lifts second, third and fourth stack items one position up, moves top down to position four.

**New in version 3.8.**

**Comment by TiZCrocodile** [comment]
> Seems like it was removed at some point in between and re-added in 3.8; I don't see it in 3.7.0. In any case, the opcode is gone again in 3.11 and 3.10 and lower only receive security fixes, so we're not going to change the docs here.

ok, thanks for the reply

**Comment by TiZCrocodile** [comment]
@JelleZijlstra wait but dont you think its better to write something like "returned in version 3.8" or something similar so it will not confuse or mislead someone?

**Comment by JelleZijlstra** [comment]
Could be worth considering, but as I said we're only making security fixes to 3.8/3.9/3.10 at this point, and this definitely isn't a security fix.
