### ISSUE TITLE
[3.12] `EnumMeta.__getattr__` removed without deprecation

### ISSUE THREAD

**Issue by jacobtylerwalls** [python/cpython#106762]
# Bug report
```python
>>> from enum import Enum
>>> class Color(Enum):
...     RED = "red"
... 
```
**3.11**
```python
>>> Color.__getattr__("RED")
<Color.RED: 'red'>
```

**3.12b4**
```py
>>> Color.__getattr__("RED")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'Color' has no attribute '__getattr__'. Did you mean: '__getitem__'?
```

***
I see that `__getattr__` is [documented](https://docs.python.org/3.11/library/enum.html#enum.EnumType.__getattr__), so I would have expected either a deprecation notice or an entry in What's New for Python 3.12.

### Linked PRs
* gh-107466
* gh-107509

**Comment by ethanfurman** [comment]
It's actually `EnumMeta.__getattr__`, but yes, it needs to be removed from the documentation as well as having a news entry.

**Comment by jacobtylerwalls** [comment]
Do you remember what the rationale was for removing `__getattr__` in 4e704d7847f2333f581f87e31b42e44a471df93a? Most of that commit was reverted in #103236 but not the removal of `__getattr__`.

The docs reference to `__getattr__` was already removed in 6a980de.

**Comment by ethanfurman** [comment]
It was the original method of looking up enum members, but it was quite slow; a more performant method is being used now.

Do you have a situation where `__getattr__` was being directly called?

**Comment by jacobtylerwalls** [comment]
Yes, I found it when trying to pass the pylint test suite against Python 3.12. Apparently the presence of a `__getattr__` attribute is [used as a heuristic](https://github.com/pylint-dev/pylint/blob/644f22427001571ba4a25afe2eceae525a8b5be0/pylint/checkers/typecheck.py#L481) for whether dot-access syntax is permitted, so pylint's linting of enums will have false negatives without a patch.

> Do you have a situation where __getattr__ was being directly called?

So, not called directly, but more like `if getattr(EnumClass, "__getattr__"):`

A deprecation period would give just a little more runway to deal with that, but the patch probably isn't particularly involved.

**Comment by jacobtylerwalls** [comment]
What about just keeping `__getattr__` as a shim for `__getitem__`?

**Comment by ethanfurman** [comment]
Where is `has_dynamic_getattr` defined?  Is it just looking for presence, or something more?

**Comment by jacobtylerwalls** [comment]
It's in an upstream dependency `astroid`. [Here's](https://github.com/pylint-dev/astroid/blob/93b1ee300445d9027afa44683a5c4e5733407329/astroid/nodes/scoped_nodes/scoped_nodes.py#L2570) `has_dynamic_getattr`: I'm fairly certain it just checks for presence. (When it calls `self.getattr`, it's checking for the [presence of an entry](https://github.com/pylint-dev/astroid/blob/93b1ee300445d9027afa44683a5c4e5733407329/astroid/nodes/scoped_nodes/scoped_nodes.py#L2454) in `self.locals`, where self is astroid's[0] version of the ast node for the class, and locals is the set of names defined on the class, like this):

```py
(Pdb) self
<ClassDef.Color l.2 at 0x106fb0910>
(Pdb) self.metaclass()
<ClassDef.EnumType l.468 at 0x1072c9450>
(Pdb) '__getattr__' in self.metaclass().locals
True
```

**Comment by jacobtylerwalls** [comment]
cc/ @Yhg1s to put on your radar for rc1.
