### ISSUE TITLE
[3.11] [3.12] Building python 3.11.4 installer FAILS, launcher.wixproj cannot detect v143 buildtools

### ISSUE THREAD

**Issue by ashish-2022** [python/cpython#106765]
# Bug report

I tried to build Python 3.11.4 with Visual Studio 2022 (v143) and I get following error at the end of compilation.
Rest of the project binaries are built using v143 successfully.

```
Project "D:\build\DE-Python\Python\Tools\msi\launcher\launcher.wixproj" (1) is building "D:\build\DE-Python\Python\PCbuild\pyshellext.vcxproj" (2) on node 1 (default targets).
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5): error MSB8020: The build tools for v143 (Platform Toolset = 'v143') cannot be found. To build using the v143 bui
ld tools, please install v143 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Retarget solution". [D:\build\DE-Python\Python\
PCbuild\pyshellext.vcxproj]
```

I used following command to build: **Python\Tools\msi\build.bat -x64 --pack**

Note: This command successfully creates installer for Python 3.10.12 on same setup.

**Build steps from: https://github.com/python/cpython/blob/main/Tools/msi/README.txt no longer work for 3.11.x and 3.12.x series for python users**

# My environment

VCIDEInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\VC\
VCINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\
VCToolsInstallDir=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.36.32532\
VCToolsRedistDir=C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Redist\MSVC\14.36.32532\
VCToolsVersion=14.36.32532
VisualStudioVersion=17.0
VS170COMNTOOLS=C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\Tools\
VS2022INSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Professional
VSINSTALLDIR=C:\Program Files\Microsoft Visual Studio\2022\Professional\

- CPython versions tested on: Python 3.11.4

- Operating system and architecture: 
Edition	Windows 10 Enterprise
Version	22H2
Installed on	‎7/‎14/‎2023
OS build	19045.3031
Experience	Windows Feature Experience Pack 1000.19041.1000.0

# Steps to reproduce 
1. Enable .Net Framework 3.5 on Windows 10
2. Install Visual Studio 2022(v143 toolset) on Windows 10 Enterprise (or any other flavor)
2. Install PythonDevelopment tools (with Python native development tools)
3. Download source code zip for python 3.11.4
4. Execute: Tools\msi\build.bat -x64 --pack
5. Expected result: Installer should be created 

### Linked PRs
* gh-110566

**Comment by ashish-2022** [comment]
I tried to build **Python 3.10.12** code on same setup and it builds fine and creates local installer under D:\Python_3_10_12\Python-3.10.12\PCbuild\amd64\en-us on my setup

This issue I can see on 3.11.1 also, what is changed in 3.11.x series?

**Comment by terryjreedy** [comment]
The message says that you *do not have* the v143 buildtools, whatever that is.  Do you follow the instructions to install them?

The devguide [Windows build section](https://devguide.python.org/getting-started/setup-building/#windows) says
>When installing [VS], select the Python development workload and the optional Python native development tools component to obtain all of the necessary build tools.

Did you do that?  When compiling 3.11 stopped working for me, I verified that this is necessary by initial not doing so.  I somehow found the option to add the needed Python tools.

**Comment by ashish-2022** [comment]
> The message says that you _do not have_ the v143 buildtools, whatever that is. Do you follow the instructions to install them?
> 
> The devguide [Windows build section](https://devguide.python.org/getting-started/setup-building/#windows) says
> 
> > When installing [VS], select the Python development workload and the optional Python native development tools component
> > to obtain all of the necessary build tools.
> 
> Did you do that? When compiling 3.11 stopped working for me, I verified that this is necessary by initial not doing so. I somehow found the option to add the needed Python tools.
> 
> You have not yet demonstrated a bug in the CPython distribution. You could have first posted to https://discuss.python.org/c/users/7 for help.

I have installed all Python tools and verified it with Python 3.10.12 build.

This issue is only there in 3.11.x series
Please try using command: Tools\msi\build.bat -x64 --pack to build and create installer. (--pack there is issue)

I have posted this on discuss.python.org as suggested by you, thanks.

**Comment by ashish-2022** [comment]
Issue also reproduced on clean Windows11 with Visual Studio Community version.

**Comment by tpendse** [comment]
@zooba This trivial only if I already have toolset `140` or `142` installed.

**Comment by hipitt** [comment]
> @zooba This trivial only if I already have toolset `140` or `142` installed.

My situation is that both v140 and v142 are installed ...

**Comment by ashish-2022** [comment]
Hi @kumaraditya303, can you help me on this. Should I set any additional environment variables to compile python3.11.x?

**Comment by ashish-2022** [comment]
**Found the solution:**
For Python 3.11.x and above since Wix is upgraded to Wix-3.14 we have to enable "Microsoft .NET Framework 4.8 Advanced Services" instead of "Microsoft .NET Framework Version 3.5" 

@zooba Please update this somewhere in the documentation. Everywhere in Python documentation it still says enable "Microsoft .NET Framework Version 3.5" , See: https://github.com/python/cpython/blob/main/Tools/msi/README.txt
and https://devguide.python.org/getting-started/setup-building/

**Comment by DirectX-Box** [comment]
I have the same issue but installing the **"Microsoft .NET Framework 4.8 Advanced Services"** did not fix it for me.

<details>
    <summary>Click to expand log</summary>

```
"C:\Python-3.12.0\Tools\msi\launcher\launcher.wixproj" (cible par défaut) (1) ->
"C:\Python-3.12.0\PCbuild\pyshellext.vcxproj" (Build cible) (4:2) ->
(PrepareForBuild cible) ->
  C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(456,5
): error MSB8020: Les outils de génération pour v143 (ensemble d'outils de plateforme = 'v143') sont introuvables. Pour
 générer à l'aide des outils de génération v143, installez les outils de génération v143. Vous avez également la possib
ilité de mettre à niveau les outils Visual Studio actuels en sélectionnant le menu Projet ou en cliquant avec le bouton
 droit sur la solution, puis en sélectionnant "Recibler la solution". [C:\Python-3.12.0\PCbuild\pyshellext.vcxproj]
```
</details>

I have Visual Studio 2022 Professional 17.7.4 installed with the following configuration:

<details>
    <summary>Expand to see exported configuration</summary>

```
{
  "version": "1.0",
  "components": [
    "Microsoft.VisualStudio.Component.CoreEditor",
    "Microsoft.VisualStudio.Workload.CoreEditor",
    "Microsoft.Net.Component.4.8.SDK",
    "Microsoft.Net.Component.4.7.2.TargetingPack",
    "Microsoft.VisualStudio.Component.TypeScript.TSServer",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions",
    "Microsoft.VisualStudio.Component.JavaScript.TypeScript",
    "Microsoft.VisualStudio.Component.Roslyn.Compiler",
    "Microsoft.Component.MSBuild",
    "Microsoft.VisualStudio.Component.Roslyn.LanguageServices",
    "Microsoft.VisualStudio.Component.TextTemplating",
    "Microsoft.VisualStudio.Component.NuGet",
    "Microsoft.VisualStudio.Component.Debugger.JustInTime",
    "Component.Microsoft.VisualStudio.LiveShare.2022",
    "Microsoft.VisualStudio.Component.IntelliCode",
    "Microsoft.Component.PythonTools",
    "Microsoft.VisualStudio.Component.VC.CoreIde",
    "Microsoft.VisualStudio.Component.Windows10SDK",
    "Microsoft.VisualStudio.Component.VC.Tools.x86.x64",
    "Microsoft.VisualStudio.Component.Graphics.Tools",
    "Microsoft.VisualStudio.Component.VC.DiagnosticTools",
    "Microsoft.VisualStudio.Component.Windows11SDK.22621",
    "Microsoft.ComponentGroup.PythonTools.NativeDevelopment",
    "Microsoft.VisualStudio.Workload.Python",
    "Microsoft.VisualStudio.Component.VC.ATL",
    "Microsoft.VisualStudio.Component.VC.ATLMFC",
    "Microsoft.VisualStudio.Component.VC.Modules.x86.x64",
    "Microsoft.VisualStudio.Component.SecurityIssueAnalysis",
    "Microsoft.VisualStudio.Component.VC.Redist.14.Latest",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Core",
    "Microsoft.VisualStudio.Component.Windows11Sdk.WindowsPerformanceToolkit",
    "Microsoft.VisualStudio.Component.CppBuildInsights",
    "Microsoft.VisualStudio.ComponentGroup.WebToolsExtensions.CMake",
    "Microsoft.VisualStudio.Component.VC.CMake.Project",
    "Microsoft.VisualStudio.Component.VC.TestAdapterForBoostTest",
    "Microsoft.VisualStudio.Component.VC.TestAdapterForGoogleTest",
    "Microsoft.VisualStudio.Component.VC.CLI.Support",
    "Microsoft.VisualStudio.Component.VC.ASAN",
    "Microsoft.VisualStudio.Component.VC.Llvm.ClangToolset",
    "Microsoft.VisualStudio.Component.VC.Llvm.Clang",
    "Microsoft.VisualStudio.ComponentGroup.NativeDesktop.Llvm.Clang",
    "Microsoft.Component.VC.Runtime.UCRTSDK",
    "Microsoft.VisualStudio.Component.VC.140",
    "Microsoft.VisualStudio.Component.Vcpkg",
    "Microsoft.VisualStudio.Workload.NativeDesktop"
  ]
}
```
</details>

I have both .NET 3.5 and 4.8 Advanced Services installed:

![image](https://github.com/python/cpython/assets/61107724/7052813d-3f95-4840-9240-5c8d480b3243)

I have tried repairing the Visual Studio install to no avail.

**Comment by ashish-2022** [comment]
> I have the same issue on 3.12.0 but installing the **"Microsoft .NET Framework 4.8 Advanced Services"** did not fix it for me.
> 
> Command: `buildrelease.bat -x64 -D --skip-msi --skip-nuget` (working directory: `Tools\msi`)
> 
> Click to expand log
> I have Visual Studio 2022 Professional 17.7.4 installed with the following configuration:
> 
> Expand to see exported configuration
> I have both .NET 3.5 and 4.8 Advanced Services installed:
> 
> ![image](https://user-images.githubusercontent.com/61107724/273548156-7052813d-3f95-4840-9240-5c8d480b3243.png)
> 
> I have tried repairing the Visual Studio install to no avail.
> 
> EDIT: I also tried the DISM command. It completed successfully but my situation remains unchanged.

And I had to also select MSVC v143 -VS 2022 C++ ARM64 build tools even though I'm just building for x64.

**Comment by zooba** [comment]
Pull requests are welcome.

This is a community project. You are clearly capable of making the changes, so feel free to follow https://devguide.python.org/ to submit a PR, put `gh-106765` in the title so it links to this issue, and we can merge it.

Actively commenting on the tracker and pinging other contributors does not help your cause.

**Comment by DirectX-Box** [comment]
> > I have the same issue on 3.12.0 but installing the **"Microsoft .NET Framework 4.8 Advanced Services"** did not fix it for me.
> > Command: `buildrelease.bat -x64 -D --skip-msi --skip-nuget` (working directory: `Tools\msi`)
> > Click to expand log
> > I have Visual Studio 2022 Professional 17.7.4 installed with the following configuration:
> > Expand to see exported configuration
> > I have both .NET 3.5 and 4.8 Advanced Services installed:
> > ![image](https://user-images.githubusercontent.com/61107724/273548156-7052813d-3f95-4840-9240-5c8d480b3243.png)
> > I have tried repairing the Visual Studio install to no avail.
> > EDIT: I also tried the DISM command. It completed successfully but my situation remains unchanged.
> 
> And I had to also select MSVC v143 -VS 2022 C++ ARM64 build tools even though I'm just building for x64. Also please un-select .NET Framework 3.5

I didn't notice this but yeah, installing **"MSVC v143 -VS 2022C++ ARM64/ARM64EC (v14.36-17.7)** fixed it without any need to uninstall .NET Framework 3.5.

> Pull requests are welcome.
> 
> This is a community project. You are clearly capable of making the changes, so feel free to follow https://devguide.python.org/ to submit a PR, put `gh-106765` in the title so it links to this issue, and we can merge it.
> 
> Actively commenting on the tracker and pinging other contributors does not help your cause.

I don't think you were talking to me since I didn't ping anyone (dirctly) but I tried to find the culprit based on the commit and the findings by this issue's author but haven't managed to solve it (yet?). Should I find a fix I guess I'll make a PR but my current work schedule doesn't allow me to spend time on this, I apologize.

**Comment by zooba** [comment]
That's the readme updated. As we only generate a single launcher installer for all platforms, there isn't really a nice way to omit the ARM64 tooling requirement, but if someone wants to have a go at improving the error message (probably by adding more output in `launcher.wixproj` where the build is triggered) please feel free to reopen this.

**Comment by vladimir-andreevich** [comment]
According to the blog posts for WiX 3.14.0 and WiX 3.14.1, these are the security updates which do not add anything new to the toolkit, including support for Windows ARM64 devices. The need to install C++ ARM build tools is not introduced by the Windows Installer XML Toolset itself, but rather by [this change](https://github.com/vladimir-andreevich/cpython/commit/45faf151c693b6f13f78926761caea6df7242024) which comes with the upgrade of the Windows Installer XML Toolset to version 3.14.

[Windows Installer XML Toolset 3.14 blog post](https://www.firegiant.com/blog/2024/2/6/wix-security-releases-available/)
[Windows Installer XML Toolset 3.14.1 blog post](https://www.firegiant.com/blog/2024/3/22/wix-security-releases-available-redux/)
