### ISSUE TITLE
May not parse correctly due to left-factoring

### ISSUE THREAD

**Issue by matsubara-kanta** [python/cpython#106715]
# Bug report
Left-factoring for CPython grammar may result in incorrect parsing.
For example, if we change

if_stmt:
    | 'if' named_expression ':' block elif_stmt 
    | 'if' named_expression ':' block [else_block]

to

if_stmt: 
    | 'if' named_expression ':' block (elif_stmt | [else_block])

, the parse will fail for CPython library files.

Looking at the differences in the generated parsers, it seems that if the entire Group class is a parsing expression that never fails (i.e., nullable), it will not be parsed correctly.

# Your environment

- CPython versions tested on: 3.11
- Operating system and architecture: macOS Ventura 13.4.1

**Comment by sunmy2019** [comment]
Then do not use left-factoring for CPython grammar.

Are there other questions?

**Comment by matsubara-kanta** [comment]
If you really think that's the way to handle it, I won't say anything.

**Comment by ericvsmith** [comment]
It appears it’s just not designed to be used this way, rather than a bug. If you want to change the behavior, you should raise it on https://discuss.python.org/c/ideas/6
