### ISSUE TITLE
Move Tier 2 interpreter (`_PyUopExecute`) to a new file

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#106701]
It currently lives in ceval.c, but I'm noticing serious increases in compile time, possibly because the file is so large. Splitting it up should make this more bearable (esp. when using `make -j`).

It's not completely trivial, since there are a number of static functions (and some macros?) that are shared between the Tier 1 an Tier 2 interpreter. But those should be turned into private functions (`_Py` prefix, no `PyAPI_FUNC` macro). That will help the copy-and-patch tooling as well. (CC @brandtbucher)

### Linked PRs
* gh-106702
* gh-106924

**Comment by brandtbucher** [comment]
FWIW, copy-and-patch still needs symbols, but they can be hidden behind `Py_BUILD_CORE`. So marking them as `PyAPI_FUNC` in `Include/internal/pycore_ceval.h` is fine (not something that needs to happen now, though.
