### ISSUE TITLE
Is GC retracking necessary for permuted tuples?

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#106785]
@brandtbucher There is tuple retracking logic in iterators that reuse the same output tuple.  That makes sense to me for iterators that put new objects in the tuple — `zip()` and `enumerate()` for example.   But is it ever needed for an iterator like `itertools.product()` that simply rearranges existing objects in the tuple? 

        // bpo-42536: The GC may have untracked this result tuple. Since we're
        // recycling it, make sure it's tracked again:
        else if (!_PyObject_GC_IS_TRACKED(result)) {
            _PyObject_GC_TRACK(result);
        }

**Comment by brandtbucher** [comment]
Hm, not sure what you mean by “rearranges existing objects in the tuple”. Code like `itertools.product([untracked, tracked], [untracked])` relies on the fix to guarantee that the second result is tracked, right?

**Comment by brandtbucher** [comment]
(I think even `itertools.permutations` needs it, since `r` may be less than the total number of elements, so some will be swapped in and out on each iteration.)

**Comment by rhettinger** [comment]
I speculated that if the source pools themselves become untracked, then the result tuple could be left untracked as well (since the result tuple elements are a subset of the source elements).
