### ISSUE TITLE
error with list index

### ISSUE THREAD

**Issue by akbzam** [python/cpython#106717]
# Bug report

Include a minimal, reproducible example (https://stackoverflow.com/help/minimal-reproducible-example), if possible.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by AlexWaygood** [comment]
you have not given any details about what the error is

**Comment by akbzam** [comment]
hi
i typed few minutes ago but i can not see what i typed. i am not familiar with this environment, but the bug is( plz type in idle):
t=('s','b','c','a','s','b')
t,index('b',1)
t,index('b',2)
t,index('b',3)
t,index('b',4)
t,index('b',5)
t,index('b',6)

in all except last the idle will show 5 and in last, it shows an error message.
i hope this comment does not been lost. i typed the bug error several times.

**Comment by AlexWaygood** [comment]
Thanks! That all looks like correct behaviour to me :)

If you're new to Python and you're struggling with how indexing works, https://discuss.python.org/c/users/7 is a better place to ask for help.

(By the way, note that `t=('s','b','c','a','s','b')` creates a tuple, not a list :)

**Comment by akbzam** [comment]
i am sorry
between t and index there is a '.' not','
namely:
t.index('b',1)

**Comment by AlexWaygood** [comment]
Yes, I guessed that that was the case. My previous comment still stands.

**Comment by pochmann** [comment]
So you're claiming that `t.index('b',1)` returns `5` instead of `1`?

**Comment by AlexWaygood** [comment]
@pochmann, @akbzam is new to programming. If you'd like to help them understand what this method does, please comment on the Discourse thread they opened: https://discuss.python.org/t/a-bug-in-python-with-tuple-index/29589/1
