### ISSUE TITLE
Incomprehensible behavior of imports

### ISSUE THREAD

**Issue by klaydev** [python/cpython#106744]
Sample code below. This behavior manifests itself only in one project and only on the Linux system, everything is OK on Windows. Using Python 3.11.4
```py
#main.py
sio = socketio.AsyncServer()
. . .
    logger.info(id(sio)) -> 140026598352912
. . .
```
```py
#auth_handler.py
from main import sio
. . .
    logger.info(id(sio)) -> 140026598649744
. . .
```

**Comment by terryjreedy** [comment]
If you have questions or need help about using Python, please post to appropriate help forums, such as stackoverflow.com or https://discuss.python.org/c/users/7.  The CPython issue tracker is for tracking well-defined issues that require a patch to the CPython distribution of code and documentation.
