### ISSUE TITLE
frame_getlocals may return NULL

### ISSUE THREAD

**Issue by P403n1x87** [python/cpython#106886]
# Crash report

We've had reports of SIGSEGV from users of the Datadog Python profiler pointing to this line

https://github.com/DataDog/dd-trace-py/blob/3b8457e03ab0ff99f4603c4e41c6f031049378aa/ddtrace/profiling/collector/_traceback.pyx#L19

Looking at the implementation of `frame_getlocals` I have noticed that there might be a chance that it might return `NULL`, since the value is coming from the `_PyInterpreterFrame->f_locals` field, which is documented to potentially hold the value `NULL`. I believe in this case the function should return, at the very least, `None` (in fact, because of typing, this should probably be an empty collection).

# Error messages

We don't have a core dump yet, and we cannot reproduce the problem yet. The pointer we've got so far is

```
 754 "2023-07-17T20:59:43.455Z","File ""ddtrace/profiling/collector/_traceback.pyx"", line 19, in ddtrace.profiling.collector._traceback._extract_class_name"
```

# Your environment

CPython 3.11.4

### Linked PRs
* gh-106885

**Comment by P403n1x87** [comment]
We are using the Python API to unwind the stack in Cython, and in particular we get the `f_locals` attribute from `frame` objects. We do not call the C API directly, so we don't expect us to be the cause of a segfault. Besides, the information that we got seems to indicate that the segfault happens within the CPython internals rather than in our Cython extension.

**Comment by markshannon** [comment]
> we get the f_locals attribute from frame objects
In Python?

> We do not call the C API directly
What do you do, then?

**Comment by P403n1x87** [comment]
This is the unwinding logic that we currently use, implemented in Cython, but with essentially pure-Python code

https://github.com/DataDog/dd-trace-py/blob/1.x/ddtrace/profiling/collector/_traceback.pyx

The pre-processor statements like https://github.com/DataDog/dd-trace-py/blob/15b43d93f4d9d0da94de1acde8d51d1d7dc70916/ddtrace/profiling/collector/_traceback.pyx#L78 are there because we've had reports in the past of non `FrameType` objects making their way into these helper functions. The place where we collect the leaf frame from the threads is here

https://github.com/DataDog/dd-trace-py/blob/15b43d93f4d9d0da94de1acde8d51d1d7dc70916/ddtrace/profiling/collector/stack.pyx#L232-L305

and in particular this is how we grab the leaf frame in Python 3.11

https://github.com/DataDog/dd-trace-py/blob/15b43d93f4d9d0da94de1acde8d51d1d7dc70916/ddtrace/profiling/collector/stack.pyx#L258C31-L271
