### ISSUE TITLE
Python unittest.mock objects leak new objects when calling sys.getsizeof calls on them

### ISSUE THREAD

**Issue by robambalu** [python/cpython#106823]
# Bug report
When calling sys.getsizeof on mock objects it looks like mock ends up leaking some new objects.  Its very easy to reproduce, this loop will leak indefinitely:

```python
import unittest.mock
import sys
Literal = unittest.mock.MagicMock(name='Literal')
c = 0
while True:
    c += sys.getsizeof(Literal)

```
# Your environment
This was tested on Python 3.8 on Linux CentOS 7

**Comment by ronaldoussoren** [comment]
``Literal.mock_calls`` shows what's going on: ``sys.getsizeof`` calls a special method (``__sizeof__``) and those calls are recorded by the mock.

**Comment by robambalu** [comment]
Interesting, I didn't realize it does that ( is this documented anywhere? ).  I confirmed that if literal is created within the loop then there is no leak.
The issue I was hitting is that I was occasionally iterating over all GC objects and calling getsizeof() to get rough memory usage of my application.  This ended up leaking on some mock object that existed somewhere.
Is there some way to turn off this behavior?

**Comment by ronaldoussoren** [comment]
AFAIK this cannot be turned off, other than explicitly by checking if objects are instances of MagicMock.

Documentation for ``sys.getsizeof`` mentions the special method: https://docs.python.org/3/library/sys.html#sys.getsizeof.

Documentation for ``MagicMock`` mentions that it has a default implementation of "most" magic method: https://docs.python.org/3/library/unittest.mock.html#unittest.mock.MagicMock

**Comment by robambalu** [comment]
I'm aware of the special method, and I saw the small mention of __sizeof__ in the magicmock docs, but nowhere does it mention that it accumulates all the calls ( and for what purpose? how is it accessed / used? )

**Comment by robambalu** [comment]
Thanks, thats good to know.  Thanks for the help here
