### ISSUE TITLE
Unreachable code in `Modules/_ssl.c`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#106831]
Looks like code in this check cannot ever be reached:

https://github.com/python/cpython/blob/2b94a05a0e45e4aae030a28b716a038ef529f8ef/Modules/_ssl.c#L2824-L2827

At this point `session` cannot be `NULL`, because it is checked right above: https://github.com/python/cpython/blob/2b94a05a0e45e4aae030a28b716a038ef529f8ef/Modules/_ssl.c#L2803-L2806

I guess that it was intended to check `newsession` variable instead.

Docs say: https://www.openssl.org/docs/man1.0.2/man3/d2i_SSL_SESSION.html

> d2i_SSL_SESSION() returns a pointer to the newly allocated SSL_SESSION object. In case of failure the NULL-pointer is returned and the error message can be retrieved from the error stack.

One more thing that bothers me here is that error is not set. We just return `NULL` which can theoretically crash the interpeter.

So, my plan is to:
1. Check `newsession` instead
2. Add a `ValueError` there

Originally introduced in https://github.com/python/cpython/commit/99a6570295de5684bfac767b4d35c72f8f36612d

PR is on its way.

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.

Author A. Voronin.

### Linked PRs
* gh-106832
* gh-106835
* gh-106836

**Comment by vstinner** [comment]
I merged your fix, thanks. The backport will land automatically soon.
