### ISSUE TITLE
Unix-only pages should each say "Availability: Unix"

### ISSUE THREAD

**Issue by nedbat** [python/cpython#106861]
# Documentation

This section of the docs has a number of pages: https://docs.python.org/3/library/unix.html .  Each is only available on Unix, but the pages themselves don't say this.  For example, if you search for the `resource` module, you get to here: https://docs.python.org/3/library/resource.html, and nothing on that page says it's not available on Windows.

It would be a small change to add "Availability: Unix" to each of these pages to make them more self-contained and quicker to reference.

### Linked PRs
* gh-108975
* gh-111553
* gh-111554

**Comment by CAM-Gerlach** [comment]
Additionally, some of them actually already _have_ an `availability` directive (via the `wasm_notavail.rst` include) that only lists as its contents `not Emscripten, not WASI` that implies it _is_ available on other platforms.

Unfortunately, the rather crude nature of that currently being done as an include makes it not possible to add any other qualifiers to the `availability` directive. A much better approach that allows this and avoids the include altogether would be to add the appropriate logic to the directive itself (as its already a custom directive) to insert the appropriate descriptive content if `not Emscripten, not WASI` are listed as `platforms`. To avoid further overloading the directive itself with bespoke content and special-casing, and make this easy to configure in the future, this would be stored in the `conf.py`, along with the known platform names, as a mapping from platform names to standard description content to inject.

**Comment by CAM-Gerlach** [comment]
I opened #106867 to cover the directive improvements discussed above that are required by this issue.

**Comment by hugovk** [comment]
https://github.com/python/cpython/pull/108975 has been merged and backports will be soon. Thanks!
