### ISSUE TITLE
Support Checking Abstract Base Classes in `numbers` when binding sqlite3 parameters

### ISSUE THREAD

**Issue by afbarnard** [python/cpython#106878]
# Bug report

After storing small integers in a NumPy array, inserting those integers into a table with SQLite results in SQLite storing bytes instead of integers.

Here's a Python script to demonstrate the problem:
```python
import sqlite3
import numpy
from pprint import pprint

vals = list(range(129)) # Bug also with 257
vals = numpy.array(vals) # Bug goes away when this is disabled
#vals = list(vals) # Bug exists even when this is enabled
tups = zip(vals)

db = sqlite3.connect('sqlite_numpy_bug.sqlite')
db.execute('create table tbl (col)')
db.executemany('insert into tbl (col) values (?)', tups)
db.commit()
pprint(list(db.execute('select * from tbl').fetchall()))
db.close()
```

One would expect the above script to output something like:
```python
[(0,),
 (1,),
 (2,),
 (3,),
 (4,),
...
```
However, the actual output is:
```python
[(b'\x00\x00\x00\x00\x00\x00\x00\x00',),
 (b'\x01\x00\x00\x00\x00\x00\x00\x00',),
 (b'\x02\x00\x00\x00\x00\x00\x00\x00',),
 (b'\x03\x00\x00\x00\x00\x00\x00\x00',),
 (b'\x04\x00\x00\x00\x00\x00\x00\x00',),
...
```

In contrast, SQLite itself only outputs single bytes, not the 8-byte chunks above:
```bash
$ rm sqlite_numpy_bug.sqlite; python3 sqlite_numpy_bug.py
$ sqlite3 sqlite_numpy_bug.sqlite
sqlite> .output query.out
sqlite> select * from tbl;
sqlite> .q
$ hexdump -C query.out | less
```
The output in `query.out` is bytes 0x00-0x80, each followed by 0x0a (newline), except the initial 0x00 byte is missing (probably due to C string handling).  (That's 129 * 2 - 1 = 257 bytes.)

# Versions / Environment

I tested this with the latest Python, NumPy, and SQLite (as available to Conda -- NumPy is a micro version behind) by creating and activating a Conda environment and iterating the above commands.
```bash
$ conda create --name test --channel defaults python=3.11 numpy sqlite
$ conda activate test
$ # python3, sqlite3, hexdump, etc.
```
These are the versions in the above environment:
```
$ python3
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
>>> import numpy, sqlite3
>>> numpy.__version__
'1.25.0'
>>> sqlite3.version
'2.6.0'
>>> sqlite3.sqlite_version
'3.41.2'
$ sqlite3 --version
3.41.2 2023-03-22 11:56:21 0d1fc92f94cb6b76bffe3ec34d69cffde2924203304e8ffc4155597af0c191da
$ uname -a
Linux <host> 6.2.15-100.fc36.x86_64 #1 SMP PREEMPT_DYNAMIC Thu May 11 16:51:53 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
```

# Comments

I am reporting this bug here because I'm guessing the problem lies in the `sqlite3` module of Python's standard library.  But there's lots of C going on here, so the problem could very well be with NumPy, especially if NumPy is backing the array with 8-bit integers.  In any case, the problem is that the two modules aren't cooperating.

I'm fine with working on diagnosing and fixing this bug, but I might not be the most efficient person as I have no knowledge of the internals of either SQLite or NumPy (although I have done a little superficial work interfacing CPython with some C++ code a long time ago).  However, as a start, I would quite appreciate it if someone could give me some pointers to info on how to debug this sort of binary-level stuff in Python.  (Or does one just go straight to `gdb`?)

**Comment by sunmy2019** [comment]
> does one just go straight to `gdb`?

Yes, and with a debug version of CPython.

---

The type of elements is changed.

```py
>>> a = list(numpy.array(list(range(127))))
>>> type(a[0])
<class 'numpy.int64'>
```

and `b'\x01\x00\x00\x00\x00\x00\x00\x00',` is just a byte representation of little-endian int64 type.

**Comment by sunmy2019** [comment]
I suspect you need to add a conversion to Python types to achieve your expected behavior. (convert it to Python int)

**Comment by sunmy2019** [comment]
```py
[int(x) for x in np.array(...)]
```

**Comment by sunmy2019** [comment]
The real binding happens here.
https://github.com/python/cpython/blob/7513e2e7e48f6c004ed9bce55f2dcc6b388e02cd/Modules/_sqlite/cursor.c#L531-L561
and `numpy.int64` implements buffer protocol, so it goes to the `TYPE_BUFFER` branch.

**Comment by afbarnard** [comment]
Thanks for figuring out all that so quickly!  Based on what you found, I completely understand now what is going on.  I had just assumed that since `issubclass(numpy.int64, numbers.Integral)` is true that SQLite would treat it as an integer.  Then I guess the question is whether this is the desired behavior or not.

(In any case, the SQLite client could print out its blobs better than just as C strings.  That led me astray.)

**Comment by sunmy2019** [comment]
I think it's quite natural. I figured out the behavior very soon.

You can refer to the document for type conversation. 

https://docs.python.org/3/library/sqlite3.html#sqlite3-types

Also note that you can work with customized type by adding your adapters. 

https://docs.python.org/3/library/sqlite3.html#sqlite3-adapters

I tend to close this issue as invalid.

**Comment by sunmy2019** [comment]
This feature request is technically feasible.

But I am not keen on it for obvious compatibility reasons. 

Also note that checking subclasses hurts the performance for users who don't need this feature.


I will let others decide.

**Comment by erlend-aasland** [comment]
After quickly reading through this, it seems to me this can be solved by implementing a custom adapter/converter pair. The C code Steven references is already complex enough; I don't think the added complexity is worth it, especially considering this can be solved with custom converters/adapters (which is why they're there in the first place).

Sorry, but I'm going to close this as not-planned.

Note: if you find the converter/adapter part of the sqlite3 docs difficult to understand, _that_ is definitely a (docs) bug; in that case, let us know by filing a docs issue :)
