### ISSUE TITLE
Include of `linux/limits.h` breaks build on Linux <5.1

### ISSUE THREAD

**Issue by indygreg** [python/cpython#106881]
# Bug report

#101857 / #101858 added an `#include <linux/limits.h>` on Linux in `Modules/posixmodule.c`.

If my Linux Git history sleuthing is accurate (`git log -- include/linux/limits.h`), `linux/limits.h` only exists in Linux <3.10 and >5.1. (Yes, the file was removed then re-added.) Attempting to compile CPython against Linux headers 3.10-5.0 fails due to the missing file.

cc @thesamesam (commit author) @gpshead (reviewer)

### Linked PRs
* gh-107397
* gh-107414
* gh-107415

**Comment by gpshead** [comment]
the joys of headers. I suppose an additional configure.ac check can handle this.

**Comment by thesamesam** [comment]
Typical! Happy to look if you don't get a chance.

**Comment by justdan6** [comment]
This looked like an easy first issue for me so I hope you don't mind that I grabbed it.
