### ISSUE TITLE
Use roles :data: and :const: for module-level variables and constants

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#106892]
Role `:data:` is purposed for marking a module-level variable. [1]  But role `:attr:` is often used instead in cases like `sys.modules`. While technically any module-level variable is accessible as an attribute, I think that it would be better to use more special role `:data:`.

[1] https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#role-py-data

### Linked PRs
* gh-106894
* gh-106954
* gh-106955

**Comment by erlend-aasland** [comment]
I agree that `data` is better than `attr`. Why not `:py:data:`?

**Comment by serhiy-storchaka** [comment]
Because it is the default domain. It can make some sense in the C API documentation to distinguish with the C domain (which is not default), but in the rest of documentation we do not add the `py:` prefix.

**Comment by erlend-aasland** [comment]
Yes, I know that this was the general guideline before, and I'm fine with using the default (py) domain. I saw some discussion about this recently, but I cannot find it. Perhaps @CAM-Gerlach or @hugovk remembers?

**Comment by hugovk** [comment]
Nope, I don't recall...
