### ISSUE TITLE
No sys.monitoring RAISE event emitted when exception is re-raised (3.12b4)

### ISSUE THREAD

**Issue by jpe** [python/cpython#106897]
It looks like no RAISE event is emitted for a bare raise in an except: clause or at the end of a finally: clause that implicitly reraises an exception. I don't know whether this a problem with the implementation or it should simply be documented that this is to be expected.

I mentioned this in https://github.com/python/cpython/issues/103082 but was encouraged to create a separate bug for it.

### Linked PRs
* gh-107291
* gh-107346

**Comment by markshannon** [comment]
We should emit an event for these cases, as the "exception raised" events, and " exception handled" events should balance.
There are quite a lot of exception events during unwinding however, so this could be quite noisy.

For example:
```Python
def func():
    try:
        try:
            1/0
        except:
            raise
    except:
        pass
```
generates 3 raise/handled pairs. The obvious 2, plus another for cleanup, which is highly implementation dependent.
If we generate normal `RAISE` events, this will break `sys.settrace`, so we need to emit a different event.
`RERAISE` is the obvious name.
