### ISSUE TITLE
Add mechanism for getting active exception in a sys.monitoring PY_UNWIND callback (3.12)

### ISSUE THREAD

**Issue by jpe** [python/cpython#106898]
I couldn't figure out a way get the active exception from a PY_UNWIND event callback -- I was hoping the exception would be passed to the callback but it isn't. This was an issue with the old tracer function debugger / profiler support so it's not really a regression, but I was hoping to avoid the work arounds that we used with it.

I mentioned this in https://github.com/python/cpython/issues/103082 but was encouraged to create a separate bug for it.

### Linked PRs
* gh-107347
* gh-107382

**Comment by gaogaotiantian** [comment]
This should be doable by simply getting the exceptions from `tstate`. The question is whether to add it - it would change the interface of the monitoring callbacks and is not backward compatible (of course it won't break a lot of code as there aren't a lot yet). I'll leave the decision to @markshannon and if he's lazy to implement that, I can do it.

**Comment by jpe** [comment]
Before the callback is called, the current_exception is saved & set to NULL and then it is restored afterwards. It might be in one of the other tstate fields, but using sys.exc_info() doesn't retrieve it.

**Comment by gaogaotiantian** [comment]
Yes the current exception is saved. I meant we can do it otherwise in the instrumentation code to pass it down, it's not rocket science. This would be a design decision and Mark may have other concerns when he implemented this. That's why I said we should wait for his decision.

**Comment by markshannon** [comment]
It makes sense to pass the exception to the event handler.
We pass the exception for the `RAISE` event, so it would make sense to do so for `PY_UNWIND`.

Should `C_RAISE` event handlers also get the exception?

**Comment by jpe** [comment]
I think C_RAISE handlers should get the exception as an argument for consistency sake, if nothing else

**Comment by gaogaotiantian** [comment]
So we need to change the callback signatures. The feature is not even documented though (except for the PEP). That's probably a separate question but - we should have the official documentation for `sys.monitoring` right?

I can work on adding the exception to the callback if no one volunteers.
