### ISSUE TITLE
Changed behaviour of str.translate()

### ISSUE THREAD

**Issue by janskarvall** [python/cpython#106889]
# Bug report

Using Ubuntu 20.04 I did not have this problem. Possibly I run Python 3.8.2, too late to find out.
Now I changed over to Debian 11. When I open a terminal and run:
```bash
janne@ubuntu:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
janne@ubuntu:~$ python3 --version
Python 3.9.2
janne@ubuntu:~$ python3
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'a#b'.translate(str.maketrans({'#': r'\#'}))
'a\\#b'
>>> 
janne@ubuntu:~$
```
I expected a single backslash. With Python 3.9.2 I got two backslashes.

**Comment by terryjreedy** [comment]
'\#' is not a legal escape sequence.  Using such in a string literal without an 'r' prefix used to be allowed.  It is now in 3.13 a SyntaxWarning and will eventually become a   SyntaxError.  You have a single backslash in the 4 character string.  It is doubled for display.  In 3.12, `'a\#b' == 'a\\#b'` is true.  In 3.13, the same expression raises a warning.  Try `len('a#b'.translate(str.maketrans({'#': r'\#'}))` to be sure that you have 4 chars.  Try `for c in 'a#b'.translate(str.maketrans({'#': r'\#'})): print(c)` to be doubly sure of what they are.

**Comment by ericvsmith** [comment]
In addition to what @terryjreedy says, in the interactive interpreter you're seeing the backslashes (among other characters) escaped with a backslash. The simplest way to see this is:
```
>>> r'a\#b'
'a\\#b'
```
Since this isn't a bug, I'm closing the issue.

**Comment by janskarvall** [comment]
Sorry! I don't understand how to translate the str r'a#b' to r'a\#b'.

**Comment by janskarvall** [comment]
Sorry, I meant how to translate the str r'a#b' to r'a\#b'.

**Comment by janskarvall** [comment]
Ahh, the single backslash in the result is somehow removed in my comments. I meant how to translate the str r'a#b' to r'a\\#b'.

**Comment by ericvsmith** [comment]
Please ask this question on https://discuss.python.org/c/users/7.
