### ISSUE TITLE
[Py 3.11.4]Dict variables may be incorrectly declared

### ISSUE THREAD

**Issue by fu050409** [python/cpython#106821]
# Bug report
I'm working on a TRPG robot that requires me to save both the number of dice a player has and the outcome of their roll.

Here is a portion of the code:
```python
import ranom
from dicer import Dice

prop = {
            "str": 1,
            "hth": 1,
            "per": 1,
            "dex": 1,
            "fte": 1,
            "chr": 1,
            "int": 1,
            "wil": 1
        }
attr = prop
total = 20 - len(prop)
for _ in range(total):
    name = random.choice(list(prop.keys()))
    prop[name] += 1

for p in prop.keys():
    num = prop[p]
    dice = Dice(f"{num}d8", explode=True)
    dice.roll()
    prop[p] = dice.total
    attr[p] = dice.dices

print(attr)
print(prop)
```

There is no doubt that the parameter "attr" and the parameter "prop" should be the same in the beginning.

It's worth mentioning that "Dice" is a class I made up that returns itself after completing "Dice().roll()". It itself contains two parameters "total" and "dices" after completing "roll". Where, "total" is a variable of type int, and "dices" is a variable of type list. I've checked it elsewhere, and my Dice class works fine, and the types of values it stores are as expected.

But in fact, after the above code is executed, the print function gives the same arguments as "prop" and "attr", and all its key values are provided by "Dice.dices", which should only be assigned to "attr". Of course, if this is not a BUG from Python, but a mistake from me, I hope you will not hesitate to advise

However, if I delete the line "attr[p] = dice.dices", the values in "prop" are as expected. Similarly, if I just replace "attr=prop" with
```
{
            "str": 1,
            "hth": 1,
            "per": 1,
            "dex": 1,
            "fte": 1,
            "chr": 1,
            "int": 1,
            "wil": 1
}
```
and I didn't change anything else, the results of the code are also as expected.

I don't know if this is a BUG of python, if it is, I like, I publish it in an issue that might improve Python, which is a programming language I really like.

# My environment
Here is my Python details:
`Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32`

I use VSCode as my Python editor.

**Comment by ronaldoussoren** [comment]
The line ``attr = prop`` does not copy the value of ``prop``, but creates a second reference to the dictionary.  Because of that at the end ``print(attr)`` and ``print(prop)`` will print the same value.

That's not a bug in Python, but expected behaviour.

Please ask questions about using Python on https://discuss.python.org/ .
