### ISSUE TITLE
The table of sys.flags doesn't have warn_default_encoding attribute.

### ISSUE THREAD

**Issue by qqwqqw689** [python/cpython#106847]
https://docs.python.org/3/library/sys.html?highlight=sys%20flags#sys.flags

PEP 597 – Add optional EncodingWarning https://peps.python.org/pep-0597/

![image](https://github.com/python/cpython/assets/114795525/1d8c8b8c-88bd-4809-b71c-f3f2e4ec4709)

### Linked PRs
* gh-106854
* gh-106958
* gh-107054

**Comment by sobolevn** [comment]
@qqwqqw689 indeed! Would you like to submit a PR with the fix? :)

`-X warn_default_encoding` should be fine, I think.

**Comment by qqwqqw689** [comment]
@sobolevn OK

**Comment by vstinner** [comment]
cc @methane

**Comment by methane** [comment]
thank you.
