### ISSUE TITLE
Use role :const: for referencing module constants

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#106909]
While technically Python modules are mutable and every name can be overridden, some names are not intended to be changed.  Sphinx has a special directive for this: `:const:`. I think that it is better to use semantically more specific `:const:` instead of general `:data:` in these cases.

First of all it is all-uppercase names, but there are exceptions: `curses.LINES` and `curses.COLS` are changed after terminal changes size. But some lowercase names like `os.sep` and `string.ascii_letters` are also clearly constants.

### Linked PRs
* gh-106910
* gh-106956
* gh-106957

**Comment by erlend-aasland** [comment]
Why not replace them with `:py:const:`?
