### ISSUE TITLE
Docs: alphabetise bullets by module name

### ISSUE THREAD

**Issue by hugovk** [python/cpython#106976]
# Documentation

Re: https://github.com/python/cpython/pull/106540#discussion_r1259964874

Look at:
* https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-python-3-14
* https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-python-3-15
* https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-python-3-16
* https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-future-versions

Each bullet point begins with the relevant module name, and the bullets are alphabetised.

Let's do the same for:

* [x] https://docs.python.org/3.13/whatsnew/3.13.html#deprecated
* [x] https://docs.python.org/3.13/whatsnew/3.12.html#deprecated
* [x] https://docs.python.org/3.13/whatsnew/3.12.html#pending-removal-in-python-3-14
* [x] https://docs.python.org/3.13/whatsnew/3.12.html#removed

### Linked PRs
* gh-106982
* gh-107005
* gh-107106

**Comment by littlebutt** [comment]
I made some changes on the page [What’s New In Python 3.13-Deprecated](https://docs.python.org/3.13/whatsnew/3.13.html#deprecated). Is it the way we want? If it is OK, I am glad to modify the other pages

**Comment by littlebutt** [comment]
I found some changes cannot be classified into spesific modules so I just left them alone.

**Comment by littlebutt** [comment]
Actually this issue can be closed since the task 4 is included in the last commit. I forgot to change the commit message. Sorry and this is [The preview page](https://cpython-previews--107106.org.readthedocs.build/en/107106/whatsnew/3.12.html#removed).

**Comment by hugovk** [comment]
Good stuff, thank you for your contributions!
