### ISSUE TITLE
asyncio.sleep doesn't elapse while in suspend on Linux

### ISSUE THREAD

**Issue by endrift** [python/cpython#106940]
# Bug report

When using asyncio.sleep() on Linux, if the computer goes into suspend while the sleep is being awaited, this time is not factored into the asyncio.sleep time due to CLOCK_MONOTONIC halting.

For example, if you await asyncio.sleep(120), then after 30 seconds enter suspend, wait 60 seconds, then wake up the computer, you will have to wait 90 seconds for the sleep to finish instead of 30.

# Your environment

- CPython versions tested on: 3.11.3
- Operating system and architecture: SteamOS 3.5 "main" branch (Arch Linux fork), x86_64

I'm not sure if this affects all Linux setups. It seems on my laptop, CLOCK_MONOTONIC keeps ticking while asleep, but on my Steam Deck it doesn't. The fact that it doesn't keep ticking is the root cause of this issue, and using CLOCK_BOOTTIME (which has been around since 2.6.39, according to Python's own docs) instead would probably fix this.

**Comment by endrift** [comment]
The fact that there's no way to schedule an absolute task kind of compounds the issue. I'd like to execute a task roughly every hour, but if the computer is asleep for some time, I'd like it to wake up sooner. It seems that the usual approach of using asyncio.sleep here doesn't work.

**Comment by gvanrossum** [comment]
I don't see this as a bug. Please ask on a user forum for how to work around it.
