### ISSUE TITLE
Forgot to add error check?

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#106916]
#106411 adds  the  `_PyCompile_CleanDoc` function.
there's a call to `PyMem_Malloc`, but we don't check if it returns `NULL` value:
https://github.com/python/cpython/blob/009e8f084c4cbb1f43d40b24b7f71fb189bbe36b/Python/compile.c#L8055-L8063

Is there a need to check for a `NULL` value?
If so, I can send a PR.

### Linked PRs
* gh-106921

**Comment by Eclips4** [comment]
cc @methane

**Comment by methane** [comment]
Yes, I forgot. Thank you.
Would you create a pull request, or may I?

**Comment by Eclips4** [comment]
I'll soon send a pull request =)
