### ISSUE TITLE
Argument Clinic 'destination <name> clear' is broken

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#106970]
The `destination <name> clear` command is documented like this:

> It removes all the accumulated text up to this point in the destination. (I don’t know what you’d need this for, but I thought maybe it’d be useful while someone’s experimenting.)

Clearly, the last sentence is correct, because this command contains two bugs, and nobody has ever complained:

1. It accesses [the wrong attribute](https://github.com/python/cpython/blob/0ba07b2108d4763273f3fb85544dde34c5acd40a/Tools/clinic/clinic.py#L1984-L1986) when clearing the accumulators
2. The directive parser [does not return immediately](https://github.com/python/cpython/blob/0ba07b2108d4763273f3fb85544dde34c5acd40a/Tools/clinic/clinic.py#L4494C3-L4496) after executing the `clear` command, so it jumps straight into "fail because we got an unknown command"

The fixes are easy, so I suggest we apply the fixes and add regressions tests. An alternative could be to remove the `clear` command, but I don't think we should tear out features lightly, no matter how obscure they are.

Found while working on #106935.

### Linked PRs
* gh-106972
* gh-106983
* gh-107059

**Comment by AlexWaygood** [comment]
Is this fixed now?
