### ISSUE TITLE
Use proper markup for the C "constants"

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#106919]
Many of the C "constants" (actually macros without parameters) are declared in the documentation using the `data` directive and referred using `:data:` and `:const:` roles. It is incorrect, because these directive and roles are defined in the Python domain and purposed to use with Python module level variables. I think that it is better to document them as they are, the C macros.

One of the differences is that the HTML anchors contains the `c.` prefix, e.g. `c.METH_VARARGS`. There may also be the difference in visual representation.

Other issues in the current markup:

* In the index they are marked as "(built-in variable)".
* There are no index entries for `METH_KEYWORDS` and `METH_METHOD` and they cannot be referred.
* There are two definitions of `Py_TPFLAGS_HAVE_GC`. They does not conflict only because they are in different namespaces.

### Linked PRs
* gh-106920
* gh-106951
* gh-106952

**Comment by encukou** [comment]
Are you aware of the discussion in https://github.com/python/cpython/issues/96996?
