### ISSUE TITLE
What's new in 3.12: fix typo: non-integral -> non-integer

### ISSUE THREAD

**Issue by hugovk** [python/cpython#106973]
# Documentation

https://docs.python.org/3.12/whatsnew/3.12.html#changes-in-the-python-api says:

> * Removed randrange() functionality deprecated since Python 3.10. Formerly, randrange(10.0) losslessly converted to randrange(10). Now, it raises a [TypeError](https://docs.python.org/3.12/library/exceptions.html#TypeError). Also, the exception raised for non-integral values such as randrange(10.5) or randrange('10') has been changed from [ValueError](https://docs.python.org/3.12/library/exceptions.html#ValueError) to [TypeError](https://docs.python.org/3.12/library/exceptions.html#TypeError). This also prevents bugs where randrange(1e25) would silently select from a larger range than randrange(10**25). (Originally suggested by Serhiy Storchaka [gh-86388](https://github.com/python/cpython/issues/86388).)

"non-integral" should be "non-integer"

### Linked PRs
* gh-106984
* gh-106986

**Comment by pochmann** [comment]
What's wrong with "non-integral"?

**Comment by hugovk** [comment]
Referring to the original issue https://github.com/python/cpython/issues/86388 and its PRs, it's about the handling of things that are not integers such as floats and strings.

And we just used "non-integer" for this in the previous note at https://docs.python.org/3.11/library/random.html#random.randrange:

<img width="779" alt="image" src="https://github.com/python/cpython/assets/1324225/caeda929-bdc4-4614-8c2e-85c574a6fe9d">

**Comment by pochmann** [comment]
> And we just used "non-integer" for this in the previous note

For types. It said "non-integer types" and "non-integral values". Looks alright and intentional to me, not like a typo. But I guess integer works for both and seems more popular...

**Comment by LauraLangdon** [comment]
> > And we just used "non-integer" for this in the previous note
> 
> For types. It said "non-integer types" and "non-integral values". Looks alright and intentional to me, not like a typo. But I guess integer works for both and seems more popular...

I think you're correct and this wasn't a typo, but since "integral" has multiple meanings in English and "integer" doesn't, "integer" seems like a solid choice.

If folks agree, I'd love to make fixing this my first contribution!
