### ISSUE TITLE
Minor: Logging module debugging improvement

### ISSUE THREAD

**Issue by baolsen** [python/cpython#106947]
# Bug report

When the logging module attaches a default StreamHandler to the root logger, I suggest that it also emits a DEBUG log message indicating that this has happened.

Currently it is difficult to identify the root cause of where handlers originate coming from, when removing logging handlers and adding your own in some complex scenarios (see below).

# A minimal reproducible example

```
import logging
logger = logging.getLogger()
logger.setLevel(logging.DEBUG)
logging.debug("test1")

logger.handlers = []
logging.debug("test2")
```

Output:
```
DEBUG:root:test1
DEBUG:root:test2
```

Proposed output:
```
DEBUG:root:test1
DEBUG: No handlers were attached to the root logger, attaching a new StreamHandler to it.
DEBUG:root:test2
```

# Discussion

https://discuss.python.org/t/minor-logging-module-debugging-improvement/28228

# Scenario / use case

I have a complex use case where I need to manipulate multiple loggers, specifically I have application-specific loggers configured with their handlers and then at another step in my application I need to reconfigure which logger and handlers are being used.

To achieve this I remove and reattach various log handlers, to various loggers, at run time.

To further complicate things, I have some log handlers that emit messages to the user’s terminal (appearing like the output of a StreamHandler) with some additional formatting going on. Some of these loggers come from imported libraries so I can’t easily change how they work.

However, due to a bug in my application, at one point my code was not attaching any handlers to the loggers.

I believe this caused Python logging to fallback and emit logs via the root logger and automatically attach a StreamHandler to emit those logs. Remember that I had explicitly removed all handlers at the beginning of my process, because I need my customised logging instead.

This produced (in my case) undesirable output to the stream. It was difficult for me to debug the source of these messages.

I first thought that one of my logging handlers was emitting the logs to my terminal. It took some time to step through the code and debug the logging configurations, handlers etc and come to the conclusion that all of my logging handlers were actually correct - just that in some scenarios they were not being attached and this caused messages to be emitted by some handler I had not attached directly by myself.

I realise the default behaviour is intended, and helpful to the vast majority of users:

Without any handlers, logging would be mostly useless as nothing would be emitted
With a stream handler being automatically attached there is hopefully direct feedback to the user that logging is happening
Many existing applications probably rely on this and other nuanced functionality today due to Python logging being a core functionality. I don’t think a WARNING should be emitted if there are no handlers attached as it may be too noisy.
My use case is overcomplicated compared to the average user requirements and the root cause of my issue is a bug in my code rather than in the logging module.
I therefore don’t want to propose material changes to the existing behavior (emit to stream when there are no handlers for the root logger).

Instead, I propose that a DEBUG message is emitted when no handlers were configured to indicate where the logging is coming from.

# Your environment

This has been standard functionality so probably reproducible in "any" environment.

- CPython versions tested on: 3.10.8, 3.11.4 (latest)
- Operating system and architecture: Apple Mac M1 running Ventura 13.4.1 (latest)
(Darwin Kernel Version 22.5.0: Thu Jun  8 22:22:19 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T8103)

### Linked PRs
* gh-106950

**Comment by baolsen** [comment]
Proposed solution added as a PR to clarify.

**Comment by vsajip** [comment]
By all means open a discussion, but please wait to get an actual discussion *before* raising an issue and a PR! I don't think this change is necessary (and also may break code for some users out there because it's a behaviour change). I think the documentation on how to configure logging is in a reasonable state, but if you want to propose documentation changes because you think it's not clear in some way, I'll look at PRs for that.

**Comment by baolsen** [comment]
Thanks for the feedback, I'll close this issue and revisit the docs :)
