### ISSUE TITLE
Global String Objects are Interned Only in the First Interpreter

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#106931]
When a string object is interned via `_PyUnicode_InternInPlace()`, its "state.interned" field is set.  Afterward, subsequent calls to `_PyUnicode_InternInPlace()` will skip that string.  The problem is that some strings may be used in multiple interpreters, which each have their own interned dict.  The string is shared between the interpreters, along with its "state.interned" field.  That means the string will only be interned in the first interpreter where `_PyUnicode_InternInPlace()` is called (ignoring races in the function, e.g. gh-106930).

We need to fix it so one of the following is true:

* there should be one global interned "dict" shared by all interpreters (we tried this already and it is very tricky)
* strings are always interned in every interpreter, regardless of the "state.interned" value

### Linked PRs
* gh-107272
* gh-107358
* gh-107362
* gh-110713

**Comment by ericsnowcurrently** [comment]
CC @kumaraditya303

**Comment by kumaraditya303** [comment]
I prefer option 1 and would like to try make it work after I am in better health.

**Comment by ericsnowcurrently** [comment]
I likewise prefer the first option, though with some other data structure than a dict.

**Comment by ericsnowcurrently** [comment]
Solutions I've considered:

1. use a global `_Py_hashtable` for statically allocated strings and keep the per-interpreter dict for strings allocated by each interpreter
2. keep all per-interpreter dicts in sync, making a copy of the string in each one (or no copy if statically allocated)
3. use a global `_Py_hashtable` for all strings; store only main-interpreter-owned strings (i.e. copy if needed)

**Comment by ericsnowcurrently** [comment]
This is done.

FYI, I didn't backport the fix to 3.12, given how late in the release cycle we are and the reservations of the release manager.
