### ISSUE TITLE
cProfile with list comprehension is less obvious with Python 3.12

### ISSUE THREAD

**Issue by tim-schilling** [python/cpython#107088]
# Bug report

I believe that the cProfiler is less helpful now in python 3.12 when attempting to point a developer to a list comprehension as the bottleneck. With python 3.11, it points out that there is a `listcomp` that is responsible for the bulk of the duration. In 3.12, that line is missing.

**Python 3.11.4**

```python
>>> import cProfile
>>> cProfile.run('[i for i in range(50000) if i % 2 == 0]')
         4 function calls in 0.009 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.009    0.009    0.009    0.009 <string>:1(<listcomp>)
        1    0.000    0.000    0.009    0.009 <string>:1(<module>)
        1    0.000    0.000    0.009    0.009 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

**Python 3.12.0b4**

```python
>>> cProfile.run('[i for i in range(50000) if i % 2 == 0]')
         3 function calls in 0.006 seconds

   Ordered by: standard name

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.006    0.006    0.006    0.006 <string>:1(<module>)
        1    0.000    0.000    0.006    0.006 {built-in method builtins.exec}
        1    0.000    0.000    0.000    0.000 {method 'disable' of '_lsprof.Profiler' objects}
```

# Your environment

- CPython versions tested on: 3.12.0b4
- Operating system and architecture: Ubuntu 22.04.2 LTS

**Comment by AlexWaygood** [comment]
At a guess, probably a result of PEP-709? (Cc. @carljm)

**Comment by tim-schilling** [comment]
I'm sorry, I didn't catch this. https://peps.python.org/pep-0709/#tracing-profiling-will-no-longer-show-a-call-return-for-the-comprehension

> [Tracing/profiling will no longer show a call/return for the comprehension](https://peps.python.org/pep-0709/#tracing-profiling-will-no-longer-show-a-call-return-for-the-comprehension)
> 
> Naturally, since list/dict/set comprehensions will no longer be implemented as a call to a nested function, tracing/profiling using sys.settrace or sys.setprofile will also no longer reflect that a call and return have occurred.

**Comment by AlexWaygood** [comment]
> I'm sorry, I didn't catch this.

Don't be sorry — it's our job to call out backwards-incompatible changes in the docs!

@carljm, do you think the impact on tracing/profiling from PEP-709 maybe deserves a bullet point in https://docs.python.org/3.12/whatsnew/3.12.html#pep-709-comprehension-inlining?

**Comment by AlexWaygood** [comment]
Since this is already called out in PEP-709, and in "What's New in Python 3.12", I don't think there's any way we can further improve the docs here :/

> when attempting to point a developer to a list comprehension as the bottleneck.

On the plus side, List comprehensions should also be much faster in Python 3.12 as a result of this change :-)

**Comment by tim-schilling** [comment]
Yup, yup. This makes sense. I was looking for a change in cProfile in 3.12, not with the comprehensions. Thank you @AlexWaygood!
