### ISSUE TITLE
`builtins.set` __sizeof__ changes after copying

### ISSUE THREAD

**Issue by KristinnVikar** [python/cpython#107175]
# Bug report
At some lengths, calling `__sizeof__()` on a set gives a different value after copying said set.
The inconsistency shows up as both an increase or a decrease in reported size.
Any copying of the set results in this behavior, but modifying the set itself does not. 

I've tested looking at the memory usage of a python process with regard to the created set, and it looks like the **copied set** has the correct `__sizeof__` value.

Simple repro:
```py
import sys

a = set(range(10_000_000))
b = a.copy()
c = set(a)
d = a.union({1})

print(a == b == c)  # -> True

print(sys.getsizeof(a))  # -> 268435672
print(sys.getsizeof(b))  # -> 536871128
print(sys.getsizeof(c))  # -> 536871128
print(sys.getsizeof(d))  # -> 536871128

print(a.__sizeof__())  # -> 268435656
print(b.__sizeof__())  # -> 536871112
print(c.__sizeof__())  # -> 536871112
print(d.__sizeof__())  # -> 536871112

```

But at other lengths, the reported size is the same.
```py
import sys

a = set(range(10_000))
b = a.copy()
c = set(a)

print(a == b == c)  # -> True

print(sys.getsizeof(a))  # -> 524504
print(sys.getsizeof(b))  # -> 524504
print(sys.getsizeof(c))  # -> 524504

print(a.__sizeof__())  # -> 524488
print(b.__sizeof__())  # -> 524488
print(c.__sizeof__())  # -> 524488
```

I made a quick script to find the sizes this inconsistency applies to. And testing seems to show that 43.7% of all lengths below 50,000 have this issue.

```py
for i in range(500):
    a = set(range(i))
    b = a.copy()
    assert a == b

    if a.__sizeof__() != b.__sizeof__():
        print(f"{i}: True")
    else:
        print(f"{i}: False")
```

My expectation is that the reported size would not change from copying a set.

# Your environment

Tested on both Ubuntu and Debian with same results

- CPython versions tested on:
  - 3.11.0
  - 3.11.2
- Operating system and architecture:
  - Ubuntu 22.04.2 LTS
  - Debian GNU/Linux 12

**Comment by AlexWaygood** [comment]
Your issue title references `collections.abc.Set`, but your code examples all use `builtins.set` — is this deliberate?

**Comment by KristinnVikar** [comment]
Ah sorry! I meant to reference `builtins.set`!

**Comment by ronaldoussoren** [comment]
Sets internally use a hash table that grows in fairly large steps to avoid the cost of memory allocation when growing the set by adding multiple items. For smallish sets the amount of backing storage is quadrupled when adding items, and for larger sets the amount of backing storage is doubled.

When creating a set from another set the amount of backing storage always is set to double the amount of items in the source set. 

Because of this the size of a smallish copied set will be slightly smaller than that of a larger copied set.

See Python/setobject.c for details.

IMHO this is not a bug, but an implementation detail of how the memory for a set is managed by the implementation.

**Comment by ericvsmith** [comment]
I agree with @ronaldoussoren that this isn't a bug.

@KristinnVikar : is this causing some practical problem?

**Comment by gaogaotiantian** [comment]
I don't think we ever promise to keep the allocated memory of the copied object the same as the original one.

```python
>>> import sys
>>> a = [1, 2, 3]
>>> sys.getsizeof(a)
88
>>> b = a.copy()
>>> sys.getsizeof(b)
80
>>> 
```

This is just how the data structure is implemented, and could be changed in the future. I don't think this is a bug.

**Comment by KristinnVikar** [comment]
Yeah, I agree that that it's not a bug. Just an undocumented side-effect of copying collections. 

It's just much more noticable with `set` objects. Where the difference is double or half, compared to a list where the difference is `8` bytes.

**Comment by JelleZijlstra** [comment]
As explained, `__sizeof__` is correct here and it's not unexpected that the in-memory size of the set depends on exactly how it is created.

If there is a concrete proposal for how to improve memory usage for sets, please open a new issue.
