### ISSUE TITLE
Don't run plausible analytics out of docs.python.org

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#107136]
# Documentation

Since e8ab0096a583184fe24dfbc39eff70d270c8e6f4, an HTTP request to plausible.io is triggered even for local builds.

So I just triggered the tracker with a local build just to check a PR (this is how I discovered it, by seeing uBlock Origin telling me it blocked it).

I don't feel that's OK as it means that Linux packages containing the Python doc, like [python3-doc](https://packages.debian.org/trixie/python3-doc) will embed the tracker too (or every distrib will take the pain to remove it...).

I think e8ab0096a583184fe24dfbc39eff70d270c8e6f4 should be reverted and maybe implemented on docsbuild-scripts, or at least be made optional (using an environment flag?) and disabled by default so we could enable it in docsbuild-script.

### Linked PRs
* gh-107856
* gh-108334
* gh-108335

**Comment by hugovk** [comment]
Thanks for raising this, I suggest we let the trial run to its end (there are 8 days left), revert, and then look into those options if we continue using it.

**Comment by hugovk** [comment]
PRs were merged, let's close this now. Thanks!
