### ISSUE TITLE
Remove unused _PyArg_VaParseTupleAndKeywordsFast()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#107196]
It seems like the ``_PyArg_VaParseTupleAndKeywordsFast()`` function is no longer used in the Python code base.

Moreover, Argument Clinic (``Tools/clinic/clinic.py``) can produce code calling the ``_PyArg_ParseTupleAndKeywordsFast()`` function, but it is not the case currently: ``_PyArg_ParseStackAndKeywords()`` is used instead.

What's the status of these two functions, ``_PyArg_ParseStackAndKeywords()`` and ``_PyArg_VaParseTupleAndKeywordsFast()``?

cc @erlend-aasland @serhiy-storchaka 

### Linked PRs
* gh-107197

**Comment by vstinner** [comment]
PR #107197 is the easy part: remove the unused private ``_PyArg_VaParseTupleAndKeywordsFast()`` function.

**Comment by serhiy-storchaka** [comment]
Argument Clinic currently unrolls parsing functions, generating a sequence of converter calls for individual parameters. But it does not support all cases, and when it fail to generate parsing code for all parameters, it falls back to traditional method, calling `_PyArg_ParseTupleAndKeywordsFast` or `_PyArg_ParseStackAndKeywords`. The former is used for `__new__` and __init__`, the latter for other methods.

So it happened that `_PyArg_ParseTupleAndKeywordsFast` is not used in currently generated code. But it will be used if we convert to Argument Clinic some classes with constructors which need it.

`_PyArg_VaParseTupleAndKeywordsFast` is not used and AFAIK never was used. It was added for symmetry, for the case if we make this interface public.

You can remove `_PyArg_VaParseTupleAndKeywordsFast`, but itself it will not save much code. You can defer this until we remove also `_PyArg_ParseTupleAndKeywordsFast` (and possible `_PyArg_ParseStackAndKeywords`) by  ensuring that Argument Clinic no longer needs such fallback. Or until we add them (reworked) to the public API, so they could be used without Argument Clinic.

**Comment by vstinner** [comment]
Let's keep _PyArg_ParseStackAndKeywords() for now. PR #110966 moves it to the internal C API, so it will be easier to remove it later if needed.
