### ISSUE TITLE
Modification of builtin types using classes

### ISSUE THREAD

**Issue by PlaceReporter99** [python/cpython#107141]
# Feature or enhancement

I would like it so that when I do something like `class str(builtin=True)`, any functions and other things defined in the class apply to the built-in class, and therefore literals.

# Pitch

With a built-in type, you may decide to not implement a few class methods for that type. Adding this would allow users who want those class methods to implement them.

# Previous discussion

https://discuss.python.org/t/ability-to-modify-python-types-by-simple-class-declaration/30150

**Comment by ericvsmith** [comment]
I'm going to close this unless and until a consensus comes out of the discussion on discuss.python.org. This will also need a PEP, so an issue isn't much use yet.

If we get as far as implementing this, we can re-open this issue.

**Comment by PlaceReporter99** [comment]
@ericvsmith ok
