### ISSUE TITLE
`help()` output of `lambda` with manually set `__annotations__` is one char off

### ISSUE THREAD

**Issue by Dutcho** [python/cpython#107155]
# Bug report

`help()` output of `lambda` with manually set `__annotations__` is slightly scrambled.
```
f = lambda a, b, c: 0              # lambdas cannot have annotations
f.__annotations__['return'] = int  # but you can set them manually

help(f)                            # superfluous ")" and missed last char
# <lambda> lambda a, b, c) -> in

import inspect
print(inspect.signature(f))        # correctly displays
# (a, b, c) -> int
```

## Note
This is a minor glitch for an atypical (perhaps even unsupported) use of annotations.

## Hypothesis
Perhaps `help()` uses (the same logic as) `inspect.signature()` and (to reflect `lambda` syntax) wants to drop the brackets "(...)", but then has a *one-off* error for its text slice (picking `") -> in"` instead of `" -> int"`)

# Environment
- CPython versions tested on: 3.6.8 - 3.11.4, 3.12.0b4
- Operating system and architecture: Windows 11

### Linked PRs
* gh-107401
* gh-115612
* gh-115613

**Comment by Eclips4** [comment]
Looks like a known issue :)
https://github.com/python/cpython/blob/f443b54a2f14e386a91fe4b09f41a265445008b8/Lib/pydoc.py#L1503-L1506

**Comment by Eclips4** [comment]
Probably, we can just replace boundaries, `argspec.replace("(", "").replace(")", "")`. Can there be any boundaries in signature of lambda?

**Comment by AA-Turner** [comment]
```python
f = lambda a, b: (a, b)
f.__annotations__['return'] = (int, int)
help(f)
# Help on function <lambda> in module __main__:
#
# <lambda> lambda a, b) -> (<class 'int'>, <class 'int'>
```

This isn't currently a legal type annotation, but using tuple literals was proposed in PEP-677 and something similar could come up again -- a cleaner fix could be to handle the string conversion manually. I've suggested something on the PR.

A

**Comment by serhiy-storchaka** [comment]
The parentheses were removed because `lambda (a, b, c)` is not a valid Python syntax. But neither `lambda a, b, c -> int` is. So why simply not keep parentheses if there are annotations? `lambda (a, b, c) -> int`. It will also be less ambiguous if parameters are annotated: `lambda (a: int, b: int, c: int) -> int`.
