### ISSUE TITLE
xls2xlsx is not working as designed

### ISSUE THREAD

**Issue by duvvurna** [python/cpython#107165]
# Bug report

xls2xlsx package is not working as per documentation. I have tried all the best possible ways and don't see this working.Acutal issues looks like failing in conversion

# Your environment

I have tested in various scenarios and that failed a lot of time.
pls help me fix this issue.

**Comment by hugovk** [comment]
This is the issue tracker for the Python progamming language. Please report youe issue to https://github.com/snoopyjc/xls2xlsx, and you'll need to include a lot more detail, see https://stackoverflow.com/help/minimal-reproducible-example for advice.
