### ISSUE TITLE
Poor performance of `_io.BufferedReader.tell`

### ISSUE THREAD

**Issue by Mysteryem** [python/cpython#107158]
# Bug report
I've noticed unexpectedly poor performance of calling `_io.BufferedReader.tell()` in a Python script I've been working on, when compared to calling `_io.BytesIO.tell()`. From looking at the source in https://github.com/python/cpython/blob/main/Modules/_io/bufferedio.c it looks to me like `_io.BufferedReader.tell()` may be slow because it ignores the cached stream position, instead re-getting the position from the raw stream on every call:

[`cpython/Modules/_io/bufferedio.c/#_io__Buffered_tell_impl`](https://github.com/python/cpython/blob/7d41ead9191a18bc473534f6f8bd1095f2232cc2/Modules/_io/bufferedio.c#L1271) appears to always get the position by calling `_buffered_raw_tell()`. The [implementation notes](https://github.com/python/cpython/blob/7d41ead9191a18bc473534f6f8bd1095f2232cc2/Modules/_io/bufferedio.c#L272) specify that the absolute position of the raw stream is cached if possible, so I'm suspecting that `_io__Buffered_tell_impl` should be using the [`RAW_TELL`](https://github.com/python/cpython/blob/7d41ead9191a18bc473534f6f8bd1095f2232cc2/Modules/_io/bufferedio.c#L391) macro instead of `_buffered_raw_tell` so that it uses the cached value when available.

It may be that the cached value cannot be relied upon in `_io__Buffered_tell_impl`, and that calling `_buffered_raw_tell()` is necessary here, but I couldn't tell if that was the case from a quick look at the source and git blame, so I have made this bug report.

The script below does some simple timing of the `_io.BufferedReader.tell()` and `_io.BytesIO.tell()` functions.
Example output from the script:
```
BufferedReader.tell() time:
        0.5720981000049505s
BytesIO.tell() time:
        0.050327699980698526s
```
I would have expected both functions to be within the same order of magnitude.
```py
import timeit
from io import BytesIO
import _io
import tempfile
import os

timing_count = 1_000_000

print()
print()

temp_file_path = None
try:
    handle, temp_file_path = tempfile.mkstemp()
    # Use `open` so we get an _io.BufferedReader
    with open(handle, 'rb') as f:
        assert isinstance(f, _io.BufferedReader)
        tell = f.tell
        t = timeit.timeit("tell()", globals=globals(), number=timing_count)
        # About 0.6s on my system.
        print(f"BufferedReader.tell() time:\n\t{t}s")
finally:
    # Remove the temporary file
    if temp_file_path is not None:
        os.remove(temp_file_path)

# I would expect _io_BufferedReader.tell() to have similar performance to BytesIO.tell(),
# but it takes about 10 times the duration compared to BytesIO.tell().
with BytesIO(b"") as f:
    assert isinstance(f, _io.BytesIO)
    tell = f.tell
    t = timeit.timeit("tell()", globals=globals(), number=timing_count)
    # About 0.05s on my system.
    print(f"BytesIO.tell() time:\n\t{t}s")
```

# Your environment

I am working on an addon script for Blender 4.0 alpha with its bundled Python version, which reports the Python version as `3.10.11 (main, May  9 2023, 12:29:22) [MSC v.1928 64 bit (AMD64)]`

- CPython versions tested on: 3.10.11
- Operating system and architecture: Windows-10-10.0.19045-SP0

**Comment by corona10** [comment]
@Mysteryem Looks reasonable, do you want to submit the patch?

**Comment by Mysteryem** [comment]
I set up a build environment and tried out replacing the `_io__Buffered_tell_impl` call with `RAW_TELL`. The performance then becomes comparable to `BytesIO.tell`, but a number of the tests then fail, so it looks like the state of `abs_pos` cannot be assumed to be accurate when `_io__Buffered_tell_impl` is called.

Always initialising `abs_pos` to `-1`, so that the first `RAW_TELL` call will get the position from the raw stream, gets a number of the test to pass again, but some still fail, so I'm guessing there are parts of the code that read from or seek the raw stream without updating `abs_pos` (either to a known value or to `-1` to signify it is now unknown).

Now that I've got an environment set up, I'll investigate some more to see if this change will be possible.

**Comment by corona10** [comment]
>  I'm guessing there are parts of the code that read from or seek the raw stream without updating abs_pos (either to a known value or to -1 to signify it is now unknown).

Yeah, I worried about the same point, if there is a way to guarantee the cached value, it will be great!

**Comment by Mysteryem** [comment]
Unfortunately, I don't think this is possible because a file descriptor can be shared by multiple `_io.FileIO` instances (possibly wrapped by `_io.BufferedReader` or similar) and any one instance can seek/read/write to change the stream position. If each instance were to have their own cached position, seeking with one instance would have to invalidate the cached position of every other instance with the same file descriptor. Therefore, `_io.FileIO.tell()` must get the stream position from the OS on every call.

The only idea that comes to mind is if there was a separate 'fast tell' function that uses a cached position, but would only be guaranteed to be accurate when the file descriptor has not been shared, but that sounds rather niche.

At least I got to the bottom of why there's the performance difference between `BytesIO.tell()` and `BufferedReader.tell()`.

I'll close this issue since I don't think there's anything to do here.

Example of sharing the file descriptor (`handle`):
```py

import tempfile
import os

print()
print()

temp_file_path = None
try:
    handle, temp_file_path = tempfile.mkstemp()
    with open(handle, 'r+b') as f1:
        with open(handle, 'r+b', closefd=False) as f2:
            orig_pos1 = f1.tell()
            orig_pos2 = f2.tell()
            assert orig_pos1 == orig_pos2
            
            f1.seek(1)

            updated_pos1 = f1.tell()
            updated_pos2 = f2.tell()
            assert updated_pos1 == (orig_pos1 + 1)
            # Only f1 was seeked, but f2 has also been
            # seeked because it has the same file descriptor
            assert updated_pos1 == updated_pos2
            # f1 and f2 are separate instances, so would have
            # their own fields, but each instance cannot
            # independently maintain a cached position.
            assert f1 != f2
            assert f1.raw != f2.raw           
finally:
    # Remove the temporary file
    if temp_file_path is not None:
        os.remove(temp_file_path)
```
