### ISSUE TITLE
C API: Rename _PyUnstable_GetUnaryIntrinsicName() to PyUnstable_GetUnaryIntrinsicName()?

### ISSUE THREAD

**Issue by vstinner** [python/cpython#107149]
Python 3.13 added ``_PyUnstable_GetUnaryIntrinsicName()`` and ``_PyUnstable_GetBinaryIntrinsicName()`` to the C API. I don't get the ``_PyUnstable`` prefix: [PEP 689 – Unstable C API tier](https://peps.python.org/pep-0689/) uses ``PyUnstable_`` prefix.

Is it just a typo, or is the API private on purpose? If it's private, why does its name look like as if it's part of the Unstable C API?

cc @brandtbucher @iritkatriel @encukou 

### Linked PRs
* gh-108440
* gh-108441
* gh-108651
* gh-112042

**Comment by iritkatriel** [comment]
I doubt there was a reason for the _. Probably just a habit.

**Comment by vstinner** [comment]
At the end, all APIs discussed here are public and exposed with the ``PyUnstable`` prefix in the public C API (in ``Include/cpython/``).

**Comment by encukou** [comment]
Unstable API needs documentation and tests.

**Comment by erlend-aasland** [comment]
> Unstable API needs documentation and tests.

Perhaps #105481 (which added the APIs in question) should be reopened instead.

**Comment by vstinner** [comment]
@erlend-aasland:
> Perhaps https://github.com/python/cpython/issues/105481 (which added the APIs in question) should be reopened instead.

Ok, I closed this issue and reopened gh-105481 instead.

**Comment by iritkatriel** [comment]
> @erlend-aasland:
> 
> > Perhaps #105481 (which added the APIs in question) should be reopened instead.
> 
> Ok, I closed this issue and reopened [gh-105481](https://github.com/python/cpython/issues/105481) instead.

It's not easy to see on that issue what you mean (which unstable APIs? That issue contained several large PRs that change many things). I think it actually works better to finish it off on this issue or create a new one than to report a large old issue.

**Comment by iritkatriel** [comment]
Also, PyUnstable_ExecutableKinds was not added in  https://github.com/python/cpython/issues/105481.

**Comment by iritkatriel** [comment]
Reopening. See https://github.com/python/cpython/issues/105481#issuecomment-1807836928.

**Comment by vstinner** [comment]
> Reopening. See https://github.com/python/cpython/issues/105481#issuecomment-1807836928.

Change implemented by https://github.com/python/cpython/commit/36aab34fab3d05f254fe80ca542c38c5f9ae11fe. I close again the issue.
