### ISSUE TITLE
datetime: negative time difference off by two days

### ISSUE THREAD

**Issue by schmidi314** [python/cpython#107240]
# Bug report

Time differences behave strangely:
```py
import datetime
ts1 = datetime.datetime(2000, 1, 1, 1)
ts2 = datetime.datetime(2000, 1, 1, 2)
print(ts1)
print(ts2)
delta1 = ts1 - ts2
delta2 = ts2 - ts1
print(delta1)
print(delta2)
```
Result:
```
2000-01-01 01:00:00
2000-01-01 02:00:00
-1 day, 23:00:00
1:00:00
```

# Your environment

CPython versions tested on:
- 3.11.3 on linux
- 3.10.9 on windows
- 3.11.0 on linux

**Comment by hugovk** [comment]
Hmm, well `-1 day, 23:00:00` is -24 hours + 23 hours = -1 hour.

It's a little clearer without `print`:
```pycon
>>> delta1
datetime.timedelta(days=-1, seconds=82800)
>>> delta2
datetime.timedelta(seconds=3600)
```

82800 seconds is 23 hours, so again -1 day + 23 hours = 1 hour.

---

https://stackoverflow.com/a/51917004/724176 says:

> Because of the way timedeltas are stored internally, **only the `days` attribute can take on negative values**. This can be surprising when the timedelta is printed back. An [illuminating example from the docs][1],
>
```pycon
>>> d = timedelta(microseconds=-1)
>>> (d.days, d.seconds, d.microseconds)
(-1, 86399, 999999)
```
>
> ie. -1d + 86399s + 999999µs = -1µs

  [1]: https://docs.python.org/2.4/lib/datetime-timedelta.html

---

With a modern version of the docs, go to https://docs.python.org/3/library/datetime.html#timedelta-objects and scroll down to the table:

> Supported operations:

| Operation | Result |
| - | - |
| `str(t)` | Returns a string in the form `[D day[s], ][H]H:MM:SS[.UUUUUU]`, where D is negative for negative `t`. (5) |

> ...
> 
> Notes:
> 
> ...
> 
> 5. String representations of [`timedelta`](https://docs.python.org/3/library/datetime.html#datetime.timedelta) objects are normalized similarly to their internal representation. This leads to somewhat unusual results for negative timedeltas. For example:
> 
```pycon
>>> timedelta(hours=-5)
datetime.timedelta(days=-1, seconds=68400)
>>> print(_)
-1 day, 19:00:00
```

So this is an expected result!

**Comment by hugovk** [comment]
See also:
* https://github.com/python/cpython/issues/44071
* https://github.com/python/cpython/issues/53676
* https://github.com/python/cpython/issues/82882

**Comment by schmidi314** [comment]
Thanks @hugovk for the clarification. My bad. But since this behaviour seems to cause confusion, wouldn't it be an option to do something like this?

```
def __str__(self):

    if self.total_seconds() < 0:
        return f'-{(-self).__str__()}'
        
    # continue original code
```

I bet workarounds like these have been coded a lot.
