### ISSUE TITLE
tkinter's Entry widget allows navigating by word in masked password field

### ISSUE THREAD

**Issue by pv2b** [python/cpython#107286]
# Bug report

There’s an issue with the Entry widget (See: https://tkdocs.com/shipman/entry.html) where, when using it to prompt for passwords using show=’*’, the characters are properly masked, but you can still (at least on Windows, where I have tested this) navigate through the password using Ctrl+Left and Ctrl+Right to discover word boundaries, if you use a password that for example contains spaces, or other characters that can be considered word boundaries for the purpose of navigation.

An easy way to reproduce it is by using the tkinter.simpledialog module as per the minimal example program below:

```
from tkinter.simpledialog import askstring
askstring("Password", "Please enter your password", show='*')
```

When you run the program, a window with a password prompt will pop up. In the window that pops up, enter a string containing spaces, for example “this is a test”. Notice however that the string appears masked.

But, press Ctrl+Left and notice how you can navigate between the different words, thereby, even though the password is masked, can discover the structure of a password containing spaces, leading to partial password disclosure.

I've not tested on anything else than Windows, so it's quite possible this is platform-specific.

# Your environment

- CPython versions tested on: 3.10.11, 3.12.0b4
- Operating system and architecture: Windows 11 x64

**Comment by serhiy-storchaka** [comment]
Tkinter is a relatively thin wrapper around [Tcl/Tk](https://www.tcl.tk/). It does not interfere in the behavior of the Tk `entry` widget. Please use the Tk bug tracker to report this issue.

**Comment by pv2b** [comment]
I have submitted this on the Tk bug tracker as per your suggestion. Thank you.
https://core.tcl-lang.org/tk/tktview/2a32225cd1d895f1651cb527e29e17d0ff5fad1f
