### ISSUE TITLE
Itertools Recipes - iter_index() silently suppresses ValueError

### ISSUE THREAD

**Issue by vbrozik** [python/cpython#107208]
# Documentation

In Itertools Recipes there is a bug in the [`iter_index()`](https://github.com/pochmann/cpython/blob/ecd95bb943256ecb3afeb70540387475a73e6dd7/Doc/library/itertools.rst?plain=1#L893) function. The function silently suppresses `ValueError` exception raised by a generator given to the argument `iterable`.

The bug was introduced by this pull request: gh-102088 Optimize iter_index itertools recipe #102360
Commit: https://github.com/python/cpython/pull/102360/commits/148bde644195408ec68cd145b779f42a214bfbb1

Code to reproduce the bug:

``` python
def assert_no_value(iterable, forbidden_value):
    """Pass the iterable but raise ValueError if forbidden_value is found."""
    for item in iterable:
        if item == forbidden_value:
            raise ValueError(f'Value {forbidden_value!r} is not allowed.')
        yield item

# Here we should get ValueError exception
# but it is being silently suppressed by iter_index()
list(iter_index(assert_no_value('AABCADEAF', 'B'), 'A'))
```

Complete notebook reproducing the bug:
https://github.com/vbrozik/python-ntb/blob/main/problems_from_forums/2023-07-24_iter_index.ipynb

Possible solutions which come to my mind:
* revert the commit https://github.com/python/cpython/pull/102360/commits/148bde644195408ec68cd145b779f42a214bfbb1
* check the value of `ValueError` inside the `iter_index()` function
* open discussion to determine whether `operator.indexOf()` should use `ValueError`

Note: I already mentioned the bug in the package `more-itertools` which inherited it:
Update recipes.iter_index to match CPython PR 102360 [#690](https://github.com/more-itertools/more-itertools/pull/690)

### Linked PRs
* gh-108835
* gh-108837

**Comment by AlexWaygood** [comment]
Cc. @pochmann

**Comment by pochmann** [comment]
The "Fast path for sequences" btw has the same issue(?), as can be seen with this sequence version of your example:

```python
from collections.abc import Sequence

class AssertNoValue(Sequence):
    def __init__(self, iterable, forbidden_value):
        self.iterable = iterable
        self.forbidden_value = forbidden_value

    def __getitem__(self, index):
        item = self.iterable[index]
        if item == self.forbidden_value:
            raise ValueError(f'Value {self.forbidden_value!r} is not allowed.')
        return item

    def __len__(self):
        return len(self.iterable)

# Here we should get ValueError exception
# but it is being silently suppressed by iter_index()
list(iter_index(AssertNoValue('AABCADEAF', 'B'), 'A'))
```

[Attempt This Online!](https://ato.pxeger.com/run?1=tVTNbtNAEJbgZl5iSA621SRqJCRQpSC50IpTkSjiglDkn3Gy0nbX7I5JI9Qn4dILPFSfhvHasddpLxzYi5OZb_6--fn1p9rTVqv7h-cvxE2lDYGu0KSkTVAafQOC0JDW0kKnFlaKHIOgwNIp10IVeBs1P9NM4gx-pLLmj6XU0Oo0PguA3-QTUm0UMJitLey2aBDSFgw6z2vDERRLLH6vUeUsNHBwupg4J1M_YJgk5--S9xfJZTiDMAljmM_fwiks4RW8dnAy-zZ489htawirwa0TOAje5lgRJERGZDXhhTHaDNaVEYqiybXUO6hS2k7iXjWFXgol57xBxd5lH8T2SEFNbEefR5fjaQZXWuHgVDDSKWAOy146Kqh5u62QCJ9NjWN58_YCZQGRgDMOCid9W9uiP5acQtermLXLIXZHxZdGdUSDoyK1bUkoLT5i6DK19JihXuoYOnTY_q9y-15H3SyKk2X8TwX-rqmcv3l4Rm4Hci0l5iS0sos0yw-bcN3VEQS5ZBtIrOVdudLOcXTQdgvQrMuasxK0XkcWZTmDYQaYlUwUBap12xB_bGW5OAC90R0DjuwZdyQJvBw2SOzlZkijYcoL2SibfviRvzrQtwFTdrDVkwmMCTWpsOjRHZWh-wM_n7J9ae54SUBpglTyZmGxCIfeme6McHC_JsnWbT1eIR2WddGomDgIpvChuT87BLvVNQ8Ok-Jl2I0IN5yRfA6a1eWcMhRqA5aHUJHcg62ryiA3vYBs75-mOGi3QQpLkScfD8j4gJ2HcXvG4rgdvvvu033_Ag)

Granted, that's perhaps more artificial/unrealistic than an *iterator* raising a `ValueError`.

**Comment by rhettinger** [comment]
Interestingly, `indexOf('AABCADEAF', 'X')` and `indexOf(assert_no_value('AABCADEAF', 'B'), 'X')` both raise a `ValueError`. It seems that the two cases can only be distinguished by examining the exception message.

**Comment by rhettinger** [comment]
The [proposal](https://discuss.python.org/t/valuenotfounderror/30442) to add `ValueNotFoundError` did not go well.  This is unfortunate because putting in a new exception is a big step that requires a consensus. 

Unless someone with more social capital steps forward to champion `ValueNotFoundError`, it looks like `operator.indexOf` will remain broken in perpetuity and we will need to roll back @pochmann 's optimization.
