### ISSUE TITLE
C API: No longer export internal C API functions

### ISSUE THREAD

**Issue by vstinner** [python/cpython#107211]
Many internal C API functions are exported with PyAPI_FUNC() and internal variables are exported with PyAPI_DATA(), whereas these APIs should not be used outside Python internals.

I propose to replace PyAPI_FUNC() and PyAPI_DATA() with extern on symbols which are not used by stdlib shared extensions.

The exception should be to export, not the default. For example, the ``_PyObject_DebugMallocStats()`` function is exported by the 3rd party guppy3 project.

See also issue #106320: C API: Remove private C API functions (move them to the internal C API).

### Linked PRs
* gh-107212
* gh-107213
* gh-107214
* gh-107215
* gh-107217
* gh-107218
* gh-108012
* gh-108229
* gh-108422
* gh-108423
* gh-108424
* gh-108425
* gh-108435
* gh-109037

**Comment by vstinner** [comment]
I went through the list of functions and variables exported by the internal C API. I prefer to stop here and see how third party projects are affected.

**Comment by kulikjak** [comment]
Hi, since last week we are hitting the following issue during build:
```
[ERROR] select failed to import: ld.so.1: python: relocation error: file ..../build/sparcv9/build/lib.solaris-2.11-sun4v.64bit-3.13/select.cpython-313.so: symbol _Py_open: referenced symbol not found
```
I presume this happens because the devpoll selector (specific to Solaris) uses `_Py_open` that is no longer visible after this change?

**Comment by encukou** [comment]
Victor, could you fix `select.devpoll()`?

**Comment by vstinner** [comment]
> Is there more work to be done here?

Oh, I forgot this issue :-) I wrote 4 more PRs. When these ones will be merged, it should be good.

**Comment by vstinner** [comment]
Ok, now we should be good.
