### ISSUE TITLE
Tkinter: test failure due to Tk 8.6.14 listbox bugfix

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#107262]
The current output of the `itemconfigure` command for listbox widgets falsely suggests that the configuration of listbox items is influenced by the options database (if I understand correctly). This will be fixed in Tk 8.6.14: see https://core.tcl-lang.org/tk/info/ed8eae599d76 and https://core.tcl-lang.org/tk/vdiff?from=edf00be1&to=025022a4

Although `tkinter.Listbox.itemconfigure()` will still work properly, test.test_tkinter.test_widgets.ListboxTest.test_itemconfigure will fail since it expects the erroneous output:

```
======================================================================
FAIL: test_itemconfigure (test.test_tkinter.test_widgets.ListboxTest.test_itemconfigure)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/user/git/cpython/Lib/test/test_tkinter/test_widgets.py", line 1002, in test_itemconfigure
    self.assertEqual(widget.itemconfigure(0, 'background'),
AssertionError: Tuples differ: ('background', '', '', '', 'red') != ('background', 'background', 'Background', '', 'red')

First differing element 1:
''
'background'

- ('background', '', '', '', 'red')
+ ('background', 'background', 'Background', '', 'red')
```

### Linked PRs
* gh-119322
* gh-119806
* gh-119807
* gh-130274
* gh-130275
* gh-130276

**Comment by terryjreedy** [comment]
I have no experience with the options database.  Are we currently testing for buggy behavior?

**Comment by serhiy-storchaka** [comment]
We are currently testing for the current behavior. They change Tk tests, so we should also change corresponding Tkinter tests. Either make them more lenient, so they will pass on all version (we can use mock.ANY for this), or expect different result depending on the Tk patch level, or only test this assertion on the fixed Tk with the correct result. The exact value is not so important as its "form" -- we test that `itemconfigure()` can take two arguments and return a 5-tuple, its first item is the option name and its last item is the current value.

Do you want to create a PR @chrstphrchvz?

**Comment by hugovk** [comment]
We need to backport this to 3.9, because it's still using `ubuntu-20.04` which is deprecated and will be fully unsupported in April: https://github.com/actions/runner-images/issues/11101.

And the upgrade to newer Ubuntu also upgrades Tk.
