### ISSUE TITLE
Any of listcomp optimization

### ISSUE THREAD

**Issue by kirillyat** [python/cpython#107241]
# Feature or enhancement

Any of listcomp optimization

Do not count all items of listcomp in case of any construction

# Pitch

`any([check(row) for row in rows])`

```
for row in rows:
    if check(row):
        return True
    return False
```

# Previous discussion

for loop via break

currently all items would be checked

**Comment by terryjreedy** [comment]
Please post questions and ideas on other forums, such as discuss.python.org, before opening issues.
