### ISSUE TITLE
importing new module with location

### ISSUE THREAD

**Issue by guyko81** [python/cpython#107228]
# Feature or enhancement

Importing new modules in Python is a pain, and far from straightforward. The trivial way to import a new module would be to give the full path of the file containing the required code - which could be a python __init__ module itself, setting up a fully functional module.

# Pitch

The import behaviour could change such a way that every beginner would feel involved, and we wouldn't have long discussions about importing modules.
The new behaviour - added to existing - would look like:

```python
import 'path/to/module/module_name.py'
```
OR
```python
import 'path/to/module/module_name.py' as module_name
```

The first one would use the filename as the module_name by default. 

I'm aware that this behaviour is already solved if the path of the file is in the python path, however it only works if python starts AFTER the python path is defined AND the file is there already in the path. Which makes it very confusing using the import functionality from an ipynb notebook.

# Solution proposal
```python
import sys
import types
import importlib.machinery
```
### define the name and path of your module
```python
module_name = 'new_module'
module_path = '/path/to/new_module.py'
```

### create a loader for the module
```python
loader = importlib.machinery.SourceFileLoader(module_name, module_path)
```

### load the source code from the .py file
```python
code = loader.get_code(module_name)
```

### create a new module object
```python
new_module = types.ModuleType(loader.name)
```

### add the source code to the module object
```python
exec(code, new_module.__dict__)
```

### add the module to the cache
```python
sys.modules[loader.name] = new_module
```

**Comment by hugovk** [comment]
# Previous discussion

New features to Python should first be discussed elsewhere before creating issues on GitHub, for example in the ["ideas" category](https://discuss.python.org/c/ideas/6) of discuss.python.org, or the [python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/).

Please can you first open a discussion at one of those places?

**Comment by hugovk** [comment]
For reference: https://discuss.python.org/t/import-files-directly-from-file-location/30244?u=hugovk

**Comment by sunmy2019** [comment]
Closed as the discussion in the https://discuss.python.org/t/import-files-directly-from-file-location/30244 is closed.

**Comment by guyko81** [comment]
https://github.com/guyko81/modgen

**Comment by guyko81** [comment]
```
pip install modgen
```
```
import modgen
module_name = 'my_selected_module_name'
module_location = 'path/to/my/module/file.py'
modgen.create(module_name, module_location)
```
```
import my_selected_module_name
```

**Comment by AlexWaygood** [comment]
@guyko81, the GitHub issue tracker is not an appropriate place to advertise your project. Consider posting on reddit or emailing https://mail.python.org/mailman3/lists/python-announce-list.python.org/.
