### ISSUE TITLE
get correct answer except 1

### ISSUE THREAD

**Issue by cyberlog101238** [python/cpython#107349]
```
def inp():
    numbers = input("")
    number = numbers.split()
    return number

number = inp()

if number.__len__() != 3:
    inp()

n_1 = number[0]
n_2 = number[1]
n_3 = number[2]

print(min(number))
```

it gives the wrong answer in inputting 40 60 8

**Comment by hugovk** [comment]
You're checking for the smallest string, sorted alphanumerically:

```pycon
>>> min("40", "60", "8")
'40'
>>> min(40, 60, 8)
8
```

Anyway, this issue tracker is for problems in the Python programming language itself. 

For help with your own programs, please ask at https://discuss.python.org/c/users/7 or https://stackoverflow.com/.
