### ISSUE TITLE
Optimize textwrap.indent()

### ISSUE THREAD

**Issue by methane** [python/cpython#107369]
Current code:

```py
def indent(text, prefix, predicate=None):
    """Adds 'prefix' to the beginning of selected lines in 'text'.

    If 'predicate' is provided, 'prefix' will only be added to the lines
    where 'predicate(line)' is True. If 'predicate' is not provided,
    it will default to adding 'prefix' to all non-empty lines that do not
    consist solely of whitespace characters.
    """
    if predicate is None:
        def predicate(line):
            return line.strip()

    def prefixed_lines():
        for line in text.splitlines(True):
            yield (prefix + line if predicate(line) else line)
    return ''.join(prefixed_lines())
```

* `predicate = str.strip` is faster than `def predicate(line)`
* `''.join(x)` converts input iterable to sequence. Using generator just makes overhead.
* creating temporary `prefix + line` is avoidable.

### Linked PRs
* gh-107374
* gh-131923

**Comment by methane** [comment]
```py
import timeit
import textwrap

with open("Objects/unicodeobject.c") as f:
    text = f.read()

it = timeit.Timer(lambda: textwrap.indent(text, " "*4))
result = it.repeat(number=1000)
result.sort()
print(f"indent {len(text.splitlines())} lines.")
print(f"{result[0]:.4f}msec")
```

before: 2.8msec
after:  2.1msec (-25%)

**Comment by hroncok** [comment]
This changes the exception type when bad type is passed:

Before:

```pycon
>>> import textwrap
>>> textwrap.dedent(5)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    textwrap.dedent(5)
    ~~~~~~~~~~~~~~~^^^
  File "/usr/lib64/python3.14/textwrap.py", line 435, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or bytes-like object, got 'int'
```

After:

```pycon
>>> import textwrap
>>> textwrap.dedent(5)
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    textwrap.dedent(5)
    ~~~~~~~~~~~~~~~^^^
  File "/usr/lib64/python3.14/textwrap.py", line 432, in dedent
    lines = text.split('\n')
            ^^^^^^^^^^
AttributeError: 'int' object has no attribute 'split'
```

The exception context itself could be better in both cases, but arguably, TypeError is better here. This breaks tests assumption in https://github.com/laurent-laporte-pro/deprecated/blob/3f67ca71143479ef7ce71786538b2bc0ef9ee4b4/tests/test_deprecated.py#L201

**Comment by methane** [comment]
@hroncok This issue is about indent, not dedent.

See https://github.com/python/cpython/pull/131919 instead.

**Comment by hroncok** [comment]
https://github.com/python/cpython/pull/131919 references this issue.

**Comment by hroncok** [comment]
Moved to https://github.com/python/cpython/pull/131919#issuecomment-2804930218

**Comment by methane** [comment]
> [#131919](https://github.com/python/cpython/pull/131919) references this issue.

It references https://github.com/python/cpython/issues/130167, not this issue.

https://github.com/python/cpython/pull/131923 references this issue because it makes textwrap.indent faster again. It is unrelated to textwrap.dedent.

**Comment by hroncok** [comment]
Sorry for my confusion.
