### ISSUE TITLE
`keys` is de facto a reserved method

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#107394]
# Documentation

As discussed [here](https://discuss.python.org/t/keys-as-a-reserved-method-name-and-part-of-the-data-model).

In summary, the `keys` method is used on arbitrary objects by the python interpreter to duck-type these objects as mappings or not. In particular, it is used for the implementation of the `**` ~~unary operator~~ syntax in function calls, and as part of the `dict.update` method's implementation. That makes it just as [reserved](https://docs.python.org/3/reference/lexical_analysis.html#reserved-classes-of-identifiers) as the other methods listed in the [data model page](https://docs.python.org/3/reference/datamodel.html). That (apparently) long-standing behavior should be made to appear clearly in the documentation.

Some existing code, of which examples are listed in the Discuss thread, implements `keys` as a method to do anything other than what the data model recognizes it to be, or even as a property returning a non-callable thing ; it is a mistake to do that, just as it would be a mistake to have `__len__` take the name of a city, print its neighbors and return None, something which would be perfectly acceptable for a method named `append`. But the documentation doesn't warn about that in the case of `keys`.

If the behavior as described, and as I will document it in a coming PR, is not satisfactory, then my original thread contains a proposition to change it but it's not the purpose of this issue. If people are tempted to change the behavior, I suggest updating the doc first for security and then make the change (which will necessarily take ages before being definitively enacted).

### Linked PRs
* gh-107395

**Comment by terryjreedy** [comment]
I think that this should be closed as not planned for the same reasons I gave in the discussion. The only reserved words in Python are the syntax keywords and reserved identifiers/names, which all begin with '_'.  The only use of 'reserved' in the data model section is "Other bits in co_flags are reserved for internal use."

Because OP thinks 'keys' is reserved, OP claims that 'is it a mistake' to use 'keys' with meanings other than the one intended for mappings.  Not in python.  It is routine to reuse builtin names and and attribute names. This is done in the stdlib.  That is why these names are not reserved.

OP claims that users uniquely need protection from such mistakes involving 'keys'.  The needs evidence that people uniquely have a bug problem with 'keys'.

**Comment by Gouvernathor** [comment]
The discussion continues more expansively in Discourse, but in a nutshell, `__iter__` is to `*expression` what `keys` is to `**expression`. `__iter__` is reserved, `keys` should be too.

**Comment by erlend-aasland** [comment]
AFAICS, this idea does not get much support in the linked Discourse topic, which suggests to me this issue and the linked PR were created prematurely.

**Comment by Gouvernathor** [comment]
I opened this after almost two weeks of silence on the thread and no real apparent opposition at the time.
And now we have a viable doc addition to consider, we can see what it looks like when considering it.

**Comment by merwok** [comment]
«not much support» and «weeks of silence» are not in contradiction!

**Comment by Gouvernathor** [comment]
Well the expressed opposition was (majorly) against changing the implementation of the `**` unpacking. And the last messages in the thread were me answering that in that case if the behavior was fine and didn't need changing, we should document it - a message liked by 2 people. That's not crowds-moving support, sure, but it was more support than opposition and for a doc change I wouldn't place the bar much higher than that, intuitively.

**Comment by erlend-aasland** [comment]
Changing the _reference text_ should IMO not be taken lightly on. If you get opposition from a core dev, that's a very good indicator _not_ to continue with an issue and a PR; instead, try and understand why there is opposition; listen carefully to arguments, concerns and objections made by others. Keeping on pushing is IMO not the way to make such important changes.

**Comment by Gouvernathor** [comment]
Well, sure, that's why I'm asking the reason for treating the method used for implementing `*expression` differently than the method used for implementing `**expression`.
See my message at the top : I rectified calling `**` a unary operator after Terry showed in Discourse how it wasn't actually one.

**Comment by rhettinger** [comment]
> I think that this should be closed as not planned for the same reasons I gave in the discussion. 

I concur.

**Comment by erlend-aasland** [comment]
@Gouvernathor; it seems this change has little support which the core dev team. Hereby closing it.

**Comment by Gouvernathor** [comment]
Well I encourage @terryjreedy and @rhettinger to give their reasons on Discourse as to why `*expression` should be done by a reserved method and `**expression` not, regarding what I wrote there some days ago.
