### ISSUE TITLE
Confused deprecation in importlib.resources.abc

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#107352]
In https://docs.python.org/3.12/library/importlib.resources.abc.html:

The documentation for `importlib.resources.abc.Traversable` says: "Deprecated since version 3.12, will be removed in version 3.14: Use `importlib.resources.abc.Traversable` instead."

The documentation for `importlib.resources.abc.TraversableResources` says: "Deprecated since version 3.12, will be removed in version 3.14: Use `importlib.resources.abc.TraversableResources` instead."

Why does it recommend to use the same deprecated class?

**Comment by AlexWaygood** [comment]
Duplicate of #105189

**Comment by serhiy-storchaka** [comment]
> It doesn't seem worth fully documenting them, shall we add brief entries? The class title, and the deprecation note?

Yes, I think it would be fine.
