### ISSUE TITLE
tarfiles: `AttributeError: '_Stream' object has no attribute 'exception'` while trying to open tgz file

### ISSUE THREAD

**Issue by balmeida-nokia** [python/cpython#107396]
# Bug report

If a tar file appears to be a `tar.gz` file, it can fail in this block of `tarfile.py`

```
        while c < size:
            # Skip underlying buffer to avoid unaligned double buffering.
            if self.buf:
                buf = self.buf
                self.buf = b""
            else:
                buf = self.fileobj.read(self.bufsize)
                if not buf:
                    break
            try:
                buf = self.cmp.decompress(buf)
            except self.exception as e:
                raise ReadError("invalid compressed data") from e
            t.append(buf)
            c += len(buf)
```
at:
```
buf = self.cmp.decompress(buf)
```
before `self.exception` is set.
Because around:

```
            if comptype == "gz":
                try:
                    import zlib
                except ImportError:
                    raise CompressionError("zlib module is not available") from None
                self.zlib = zlib
                self.crc = zlib.crc32(b"")
                if mode == "r":
                    self._init_read_gz()
                    self.exception = zlib.error
                else:
                    self._init_write_gz()
```
This: `self._init_read_gz()`
is called before `self.exception = zlib.error`

Stack trace:
```
_read, tarfile.py:548
read, tarfile.py:526
_init_read_gz, tarfile.py:491
__init__, tarfile.py:375
open, tarfile.py:1827
<module>, test.py:2
```

In my case, `buf = self.cmp.decompress(buf)` failed to execute but that's a separate issue that may or may not be a bug

# Your environment

- CPython versions tested on: 3.11.4
- Operating system and architecture: Windows 10 21H2

### Linked PRs
* gh-107485
* gh-108207
* gh-108208

**Comment by sunmy2019** [comment]
Looks reasonable. Will you open an PR?

**Comment by balmeida-nokia** [comment]
Sure

**Comment by encukou** [comment]
Hello,
How does this issue manifest? `exception` appears like an write-only attribute of an internal class.
I'd like to add a test for the PR, but can't think of a reasonable one. Do you have a use case we currently don't have tests for?

**Comment by balmeida-nokia** [comment]
@encukou Please see: https://github.com/python/cpython/issues/107398

Maybe that one will explain better the sequence where this failure can happen.

My interpretation is that gzip supports backwards skipping and it appears to be rarely used. If I open a tgz with `r|*` (which, by design, doesn't support backwards skipping) and the gzip stream requests a backwards skip, an exception is raised. At the `except` statement it has `except self.exception` which is were the attribute is read, which means the attribute is actually read-write.

**Comment by encukou** [comment]
Oh, I see!
Here's a reproducer:
```python
with open('hm.tar.gz', 'rb') as f:
    f = io.BytesIO(
        b'\x1f\x8b'  # header
        + b'\x08'  # compression method
        + b'\x04'  # flags
        + b'\0\0\0\0\0\0'  # padding?
        + b'\0\x01'  # size
        + bytes(5)  # corrupt data (zeros)
    )
    tarfile.open(fileobj=f, mode='r|gz')
```
If you can add it as a test using `with self.assertRaises(tarfile.ReadError):` to `Lib/test/test_tarfile.py`, it'd speed things up. If not I'll get to it later.

**Comment by balmeida-nokia** [comment]
OK. I will.

**Comment by balmeida-nokia** [comment]
@encukou Made a commit with the tests. I'm unsure if I placed the new class in the correct placement but it seemed to be one of the best places to place it. I tried to figure out if a new class should be done and seemed to be a reasonable choice.
https://github.com/python/cpython/pull/107485
