### ISSUE TITLE
It seems that `platform.platform` can't detect windows 11?

### ISSUE THREAD

**Issue by littlewhitecloud** [python/cpython#107338]
![image](https://github.com/python/cpython/assets/71159641/f770a4c6-6a00-43b4-b34a-677b712fbe0e)
![image](https://github.com/python/cpython/assets/71159641/ed06ca6a-648c-4aad-ad00-a0cf3dc11074)

**Comment by hugovk** [comment]
This terminal version:

![image](https://github.com/python/cpython/assets/1324225/5c6d203f-b7da-4db0-89ca-ea7f106c506d)

Matches the version Python gets:

![image](https://github.com/python/cpython/assets/1324225/fd80825d-5c04-4779-b32e-622e727d55d3)

So this doesn't look like a Python problem.

**Comment by hugovk** [comment]
And looking at https://en.wikipedia.org/wiki/Windows_11 it shows the latest version is 22H2 10.0.22621.2070.

https://en.wikipedia.org/wiki/Windows_NT#Releases makes it clear: _Windows NT_ version 10.0 has marketed under several names:

* Windows 10
* Windows Server 2016
* Windows Server 2019
* Windows Server 2022
* Windows 11

**Comment by eryksun** [comment]
This has been fixed in Python 3.12 by using a new `_wmi` module to query the system's "Win32_OperatingSystem" information. There were ways discussed to fix it without using WMI in Python 3.10 and 3.11, but nothing was ever implemented.
