### ISSUE TITLE
``errno`` documentation missing several constants

### ISSUE THREAD

**Issue by qqwqqw689** [python/cpython#107453]
The [``errno`` documentation](https://docs.python.org/3/library/errno.html) doesn't have:

* errno.ECANCELED
* errno.EOWNERDEAD
* errno.ENOTRECOVERABLE
* errno.ENOTSUP

Reference: [errno(3) man page](https://linux.die.net/man/3/errno)

### Linked PRs
* gh-107486
* gh-108365
* gh-108529
* gh-108530

**Comment by sunmy2019** [comment]
Yes. Other signals added in this commit are also undocumented.

b85e165635889d9d736b7082c0e486217f2ca821

A PR is welcome.

**Comment by qqwqqw689** [comment]
{19: 'ENODEV',
 10065: 'WSAEHOSTUNREACH',
 122: 'ENOMSG',
 120: 'ENODATA',
 40: 'ENOSYS',
 32: 'EPIPE',
 22: 'EINVAL',
 132: 'EOVERFLOW',
 4: 'EINTR',
 10068: 'WSAEUSERS',
 41: 'ENOTEMPTY',
 10055: 'WSAENOBUFS',
 134: 'EPROTO',
 10071: 'WSAEREMOTE',
 10: 'ECHILD',
 10062: 'WSAELOOP',
 18: 'EXDEV',
 7: 'E2BIG',
 3: 'ESRCH',
 10040: 'WSAEMSGSIZE',
 10047: 'WSAEAFNOSUPPORT',
 10064: 'WSAEHOSTDOWN',
 10046: 'WSAEPFNOSUPPORT',
 10042: 'WSAENOPROTOOPT',
 16: 'EBUSY',
 10035: 'WSAEWOULDBLOCK',
 10056: 'WSAEISCONN',
 10058: 'WSAESHUTDOWN',
 9: 'EBADF',
 5: 'EIO',
 10041: 'WSAEPROTOTYPE',
 28: 'ENOSPC',
 8: 'ENOEXEC',
 10037: 'WSAEALREADY',
 10050: 'WSAENETDOWN',
 13: 'EACCES',
 42: 'EILSEQ',
 20: 'ENOTDIR',
 1: 'EPERM',
 33: 'EDOM',
 10061: 'WSAECONNREFUSED',
 21: 'EISDIR',
 10043: 'WSAEPROTONOSUPPORT',
 30: 'EROFS',
 10049: 'WSAEADDRNOTAVAIL',
 111: 'EIDRM',
 104: 'EBADMSG',
 23: 'ENFILE',
 29: 'ESPIPE',
 121: 'ENOLINK',
 10052: 'WSAENETRESET',
 10060: 'WSAETIMEDOUT',
 2: 'ENOENT',
 17: 'EEXIST',
 10069: 'WSAEDQUOT',
 125: 'ENOSTR',
 14: 'EFAULT',
 27: 'EFBIG',
 36: 'EDEADLOCK',
 10057: 'WSAENOTCONN',
 10039: 'WSAEDESTADDRREQ',
 39: 'ENOLCK',
 10053: 'WSAECONNABORTED',
 10051: 'WSAENETUNREACH',
 10070: 'WSAESTALE',
 124: 'ENOSR',
 12: 'ENOMEM',
 10038: 'WSAENOTSOCK',
 31: 'EMLINK',
 34: 'ERANGE',
 10054: 'WSAECONNRESET',
 10048: 'WSAEADDRINUSE',
 10045: 'WSAEOPNOTSUPP',
 11: 'EAGAIN',
 38: 'ENAMETOOLONG',
 25: 'ENOTTY',
 10044: 'WSAESOCKTNOSUPPORT',
 137: 'ETIME',
 10059: 'WSAETOOMANYREFS',
 24: 'EMFILE',
 139: 'ETXTBSY',
 10036: 'WSAEINPROGRESS',
 6: 'ENXIO',
 10024: 'WSAEMFILE',
 10092: 'WSAVERNOTSUPPORTED',
 10067: 'WSAEPROCLIM',
 10014: 'WSAEFAULT',
 10093: 'WSANOTINITIALISED',
 10063: 'WSAENAMETOOLONG',
 10066: 'WSAENOTEMPTY',
 10013: 'WSAEACCES',
 10000: 'WSABASEERR',
 10009: 'WSAEBADF',
 10101: 'WSAEDISCON',
 10004: 'WSAEINTR',
 10091: 'WSASYSNOTREADY',
 10022: 'WSAEINVAL',
 105: 'ECANCELED',
 133: 'EOWNERDEAD',
 127: 'ENOTRECOVERABLE',
 129: 'ENOTSUP'}

all errnos.
![image](https://github.com/python/cpython/assets/114795525/680e6d65-9fa9-487d-a5fc-f78ce85d5e4b)
(windows)

I will check them one by one.

**Comment by qqwqqw689** [comment]
That's all.

ECANCELED

<img width="257" alt="0aedcce53a0721b1d1c20ea3e48bcee" src="https://github.com/python/cpython/assets/114795525/d4bc3809-6444-4fe7-9b2a-4604e471490e">

EOWNERDEAD

<img width="237" alt="e2c87f5e3be7269ab518e4a4af0e469" src="https://github.com/python/cpython/assets/114795525/2b002c68-61cd-4d1b-9979-7a780a12e699">

ENOTRECOVERABLE

<img width="299" alt="8ca0d6f78e2b9736dba71169bb9bebe" src="https://github.com/python/cpython/assets/114795525/c1d0c418-64c9-4ca5-a52b-0908cebba155">

ENOTSUP

<img width="238" alt="f1806a6a5a5c18b41dbfb9fd328aebd" src="https://github.com/python/cpython/assets/114795525/bc493bc5-1ab0-4c76-837c-24eb5065d734">

10041: 'WSAEPROTOTYPE',
10037: 'WSAEALREADY',
10050: 'WSAENETDOWN',
10061: 'WSAECONNREFUSED',
10043: 'WSAEPROTONOSUPPORT',
10049: 'WSAEADDRNOTAVAIL',
10052: 'WSAENETRESET',
10060: 'WSAETIMEDOUT',
10069: 'WSAEDQUOT',
10057: 'WSAENOTCONN',
10039: 'WSAEDESTADDRREQ',
10053: 'WSAECONNABORTED',
10051: 'WSAENETUNREACH',
10070: 'WSAESTALE',
10038: 'WSAENOTSOCK',
10054: 'WSAECONNRESET',
10048: 'WSAEADDRINUSE',
10045: 'WSAEOPNOTSUPP',
10044: 'WSAESOCKTNOSUPPORT',
10059: 'WSAETOOMANYREFS',
10036: 'WSAEINPROGRESS',
10024: 'WSAEMFILE',
10092: 'WSAVERNOTSUPPORTED',
10067: 'WSAEPROCLIM',
10014: 'WSAEFAULT',
10093: 'WSANOTINITIALISED',
10063: 'WSAENAMETOOLONG',
10066: 'WSAENOTEMPTY',
10013: 'WSAEACCES',
10000: 'WSABASEERR',
10009: 'WSAEBADF',
10101: 'WSAEDISCON',
10004: 'WSAEINTR',
10091: 'WSASYSNOTREADY',
10022: 'WSAEINVAL',
10040: 'WSAEMSGSIZE',
10047: 'WSAEAFNOSUPPORT',
10064: 'WSAEHOSTDOWN',
10046: 'WSAEPFNOSUPPORT',
10042: 'WSAENOPROTOOPT',
10035: 'WSAEWOULDBLOCK',
10056: 'WSAEISCONN',
10058: 'WSAESHUTDOWN',
WSAEHOSTUNREACH
WSAEUSERS
WSAENOBUFS
WSAELOOP

**Comment by vercetti322** [comment]
Hi!
Its my first time  contributing. Can I work on this issue?

**Comment by qqwqqw689** [comment]
@vercetti322 everyone is welcomed.

**Comment by vercetti322** [comment]
I have submitted my pull request. Please ignore the 'gh-107453' commit, was done by mistake.

**Comment by hugovk** [comment]
> Yes, everyone is welcome.

@qqwqqw689 True, although may I suggest next time you mention if you already have a PR open, so others can better spend time on other issues?

Thanks both.

**Comment by qqwqqw689** [comment]
@hugovk  OK.
