### ISSUE TITLE
ctypes: Improve error messages when converting to an incompatible type

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#107455]
This code produces an error with a somewhat unhelpful message:

```python
from ctypes import *

printf = CDLL('libc.so.6').printf
printf.argtypes = [c_char_p, c_char_p]
printf(b"Value %s\n", 10)  # call with an incompatible argument
```
```python
Traceback (most recent call last):
  File "/home/tomas/dev/cpython/error.py", line 5, in <module>
    printf(b"Value: %s\n", 10)
ctypes.ArgumentError: argument 2: TypeError: wrong type
```
The source code itself suggests providing a better message:
https://github.com/python/cpython/blob/3979150a0d406707f6d253d7c15fb32c1e005a77/Modules/_ctypes/_ctypes.c#L1795-L1797

I suggest making the message more helpful by including the expected argument type and the type that was actually provided e.g.
```diff
- TypeError: wrong type
+ TypeError: 'int' object cannot be interpreted as ctypes.c_char_p
 ```
The same improvement can be applied to `c_wchar_p` and `c_void_p`.

### Linked PRs
* gh-107456

**Comment by kumaraditya303** [comment]
Thanks!
