### ISSUE TITLE
asyncio nonresponsive port blocks entire loop

### ISSUE THREAD

**Issue by xloem** [python/cpython#107470]
# Bug report

## Checklist

- [x] I am confident this is a bug in CPython,
      not a bug in a third-party project
- [x] I have searched the CPython issue tracker,
      and am confident this bug has not been reported before

## A clear and concise description of the bug

While waiting for a reply, asyncio socket connections halt the entire selector loop. The hang is on this line: https://github.com/python/cpython/blob/a24e25d74bb5d30775a61853d34e0bb5a7e12c64/Lib/asyncio/selector_events.py#L649 . This is most visible when a single server is down during many parallel connections.

The below script causes this issue for me. It should output a tuple for the successful connection, but instead hangs until another connection fails.
```py
import asyncio

async def atest():
    for next_completed in asyncio.as_completed([
        asyncio.open_connection('1.0.0.0', 65535),
        asyncio.open_connection('www.yahoo.com', 65535),
        asyncio.open_connection('www.yahoo.com', 443),
    ]):
        print(await next_completed)

asyncio.run(atest())
```

The issue is resolved for me with this workaround:
```py
orig_sock_connect = loop._sock_connect
def background_sock_connect(fut, sock, address):
    fut.__task = asyncio.Task(asyncio.to_thread(orig_sock_connect, fut, sock, address))
loop._sock_connect = background_sock_connect
```

# Your environment

- CPython versions tested on: 3.10.11
- Operating system and architecture: Linux RHEL7
- NOTE: I am using [proxychains4](https://github.com/rofl0r/proxychains-ng) to connect via an HTTP proxy, which hooks the socket connection system calls python is using.

**Comment by gvanrossum** [comment]
Hm... There is code in `BaseEventLoop._connect_sock` to set the socket in nonblocking mode, so this shouldn't happen. Can you repro this without using proxychains? If not, I would suspect that maybe proxychains, when it hooks `connect()`, doesn't respect the non-blocking setting. (Note: I don't know the first thing about proxychains, I'm just going by your description.)

**Comment by xloem** [comment]
Yeah, it sounds like this is a bug in proxychains ignoring the non-blocking setting. I found direct internet and the behavior did not reproduce via it. Sneaky way the quirk manifests.
