### ISSUE TITLE
No module named "encodings" when making

### ISSUE THREAD

**Issue by Kaki-In** [python/cpython#107420]
# Crash report

Following the building instructions, after having ran "./configure", "make" fails

# Error messages

```
$ make
./_bootstrap_python ./Programs/_freeze_module.py abc ./Lib/abc.py Python/frozen_modules/abc.h   Exception ignored error evaluating path:
Traceback (most recent call last):                                                                File "<frozen getpath>", line 349, in <module>
ModuleNotFoundError: No module named 'encodings'
Fatal Python error: error evaluating path
Python runtime state: core initialized

Current thread 0x00007f3b76896140 (most recent call first):
  <no Python frame>
make: *** [Makefile:1213: Python/frozen_modules/abc.h] Error 1
```

# Your environment

- CPython versions tested on: python3.11
- Operating system and architecture: Linux X86_64 Debian 10.13

**Comment by sunmy2019** [comment]
Can you try a clean build?
What branch/commit are you on?
Do you have this file? `Lib/encodings/__init__.py`

**Comment by Kaki-In** [comment]
I downloaded the .tar.xz file from the python.org website

The Lib/encodings/__init__.py is present as expectes

**Comment by sunmy2019** [comment]
What's line 349 of your file `Modules/getpath.py`.

Can you provide that line and related lines?

**Comment by Kaki-In** [comment]
Around this line : 
```python
   337	# ******************************************************************************
   338	# READ pyvenv.cfg
   339	# ******************************************************************************
   340	
   341	venv_prefix = None
   342	
   343	# Calling Py_SetPythonHome(), Py_SetPath() or
   344	# setting $PYTHONHOME will override venv detection.
   345	if not home and not py_setpath:
   346	    try:
   347	        # prefix2 is just to avoid calculating dirname again later,
   348	        # as the path in venv_prefix is the more common case.
   349	        venv_prefix2 = executable_dir or dirname(executable)
   350	        venv_prefix = dirname(venv_prefix2)
   351	        try:
   352	            # Read pyvenv.cfg from one level above executable
   353	            pyvenvcfg = readlines(joinpath(venv_prefix, VENV_LANDMARK))
   354	        except FileNotFoundError:
   355	            # Try the same directory as executable
   356	            pyvenvcfg = readlines(joinpath(venv_prefix2, VENV_LANDMARK))
   357	            venv_prefix = venv_prefix2
   358	    except FileNotFoundError:
   359	        venv_prefix = None
   360	        pyvenvcfg = []
   361	
   362	    for line in pyvenvcfg:
   363	        key, had_equ, value = line.partition('=')
   364	        if had_equ and key.strip().lower() == 'home':
   365	            executable_dir = real_executable_dir = value.strip()
   366	            if not base_executable:
   367	                # First try to resolve symlinked executables, since that may be
   368	                # more accurate than assuming the executable in 'home'.
   369	                try:
   370	                    base_executable = realpath(executable)
   371	                    if base_executable == executable:
   372	                        # No change, so probably not a link. Clear it and fall back
   373	                        base_executable = ''
   374	                except OSError:
   375	                    pass
   376	                if not base_executable:
   377	                    base_executable = joinpath(executable_dir, basename(executable))
   378	            break
   379	    else:
   380	        venv_prefix = None
   381	
   382	
```

**Comment by sunmy2019** [comment]
Can you split line 349 into
```diff
-        venv_prefix2 = executable_dir or dirname(executable)
+        venv_prefix2 = executable_dir or \
+                                  dirname(executable)
```

then make a clean build to check if the `dirname` causes the problem.


Also, what is your working directory?

---

@zooba Can you take a look?

**Comment by Kaki-In** [comment]
My working directory : `~/Téléchargements/Python-3.11.0`

I unzipped the tarxf file, modified the file, and finally made it. Still the same result, nothing about getpath.py

**Comment by sunmy2019** [comment]
> My working directory : `~/Téléchargements/Python-3.11.0`

Can you try a directory with full ascii?


> I unzipped the tarxf file, modified the file, and finally made it. Still the same result, nothing about getpath.py

Did this line

`Traceback (most recent call last): File "<frozen getpath>", line 349, in <module>`

Changes to

`Traceback (most recent call last): File "<frozen getpath>", line 350, in <module>`

?

**Comment by Kaki-In** [comment]
> Did this line
> ```Traceback (most recent call last): File "<frozen getpath>", line 349, in <module>```
> Changes to
> ```Traceback (most recent call last): File "<frozen getpath>", line 350, in <module>```
> ?

Oh i didn't see but yes it did.

> Can you try a directory with full ascii? 

It seems to be this because I could install Python3.10 in my `~` directory. I think you fixed my problem, thanks a lot!

**Comment by Kaki-In** [comment]
Since I moved the directory to `~` it works now. Thanks again!

**Comment by Kaki-In** [comment]
> You don't need to open it to post

Sorry, it was a missclick
