### ISSUE TITLE
Restructure Argument Clinic CLI

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#107467]
Suggesting to ...:

- [x] make the clinic tool a well-behaved command-line citizen; write to `stderr`, not `stdout`, on error (partly depends on #107468)
- [x] put the whole CLI in `main`, making it easier to mock the tool in the test suite (currently we use subprocesses, which is slow, and requires several lines of boiler-plate test setup code)
- [x] ~~Introduce CLIError and use it for usage errors~~ Used `ArgumentParser.error` instead.

### Linked PRs
* gh-107469

**Comment by AA-Turner** [comment]
@erlend-aasland is there anything left to do in this issue? Looks like #107469 captured all of this (maybe save stderr/stdout?)

A

**Comment by erlend-aasland** [comment]
Thanks for the heads-up! Yes, this can be closed.
