### ISSUE TITLE
ctypes `_as_parameter_` does not mention all possible types

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#107442]
# Documentation

The `_as_parameter_` attribute can be used when one wants to pass a custom object a `ctypes` function.
The [documentation](https://docs.python.org/3/library/ctypes.html?highlight=ctypes#calling-functions-with-your-own-custom-data-types) says:

> it must be one of integer, string, or bytes

However, one can also use a `ctypes` instance or another object which itself has the `_as_parameter_` attribute.
The documentation should be updated to include these two additional possibilities.

### Linked PRs
* gh-107443
* gh-107707
* gh-107718

**Comment by hugovk** [comment]
Thanks for the fix!
