### ISSUE TITLE
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'

### ISSUE THREAD

**Issue by rsawavesemi** [python/cpython#107493]
Hi,

We got an error while importing xls2xlsx module "**ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.0.2k-fips  26 Jan 2017'**" , we tried a couple of solutions. None of them worked.....,
robust solution will be very much appreciated.

Thank you

**Comment by AraHaan** [comment]
What version of python is used?

**Comment by ronaldoussoren** [comment]
Your report misses a lot of information that's needed to traige:

- What OS are you using?
- What version of Python do you use?
- How was Python installed?

The error message indicates that you use a version of Python that was built using an ancient version of OpenSSL, which is no longer supported by the third-party urllib3 library.  Unless you're using one of our builds of Python (for Windows or macOS) there's nothing the CPython project can do to fix this issue.

**Comment by debajitopenfivedutta** [comment]
Hi @ronaldoussoren ,

Below is the information:-

1. What OS are you using?
We are using CentOS Linux release 7.9.2009 (Core)

2. What version of Python do you use?
This is an issue we are experiencing for Python 3.9.0

3. How was Python installed?
We installed the python from the source, i.e. downloading the tar file and then ./config followed by the make and make install commands.

**Comment by ronaldoussoren** [comment]
Apparently EPEL has OpenSSL 1.1 available, see https://centosfaq.org/centos/install-openssl-111-on-centos-linux-release-792009-core/

After installing that you have to rebuild Python, and make sure it picks up the headers and library from the newer version of OpenSSL.

**Comment by zware** [comment]
This is not an issue with currently-supported Python versions on any platform; closing.

**Comment by AraHaan** [comment]
@debajitopenfivedutta You might want to start using 3.11+ which *should* work out of the box for you, 3.12 if you can run release candidate builds, or even main if you want to live on 3.13 (dev) version. Although C extensions would need to be compiled on your machine and depending on your dependencies might not build correctly.
