### ISSUE TITLE
fractions standard library uses infinite integer precision

### ISSUE THREAD

**Issue by carlos-adir** [python/cpython#107425]
# Feature or enhancement

Python already has the standard library [fractions](https://docs.python.org/3/library/fractions.html) which allows operations using fractions (pair of integers).

Today there's the method ```limit_denominator``` which allows to modify the "precision". 
The enchancement is to remove the integer limit of the fraction by passing ```None``` as argument

**Comment by hugovk** [comment]
# Previous discussion

New features to Python should first be discussed elsewhere before creating issues on GitHub, for example in the ["ideas" category](https://discuss.python.org/c/ideas/6) of discuss.python.org, or the [python-ideas mailing list](https://mail.python.org/mailman3/lists/python-ideas.python.org/).

Please will you open a discussion in one of those places?

**Comment by terryjreedy** [comment]
Carlos, I believe you are asking for the status quo, in that there is no limit until one requests one, and hence nothing to discuss.
```
>>> from fractions import Fraction
>>> f=Fraction('3.1415926535897932'); f
Fraction(7853981633974483, 2500000000000000)
>>> f*f
Fraction(61685027506808489857291095117289, 6250000000000000000000000000000)
```
If I am wrong and you want to pursue your idea, do post as suggested.

**Comment by carlos-adir** [comment]
Indeed, my bad. I made a code to invert fractional matrix ([you can find it here](https://gist.github.com/carlos-adir/5360223c42cebbd3b740f7dc8ee9c798)) by gaussian elimination and I encoutered ```RuntimeWarning: overflow``` warning which gave wrong results for inverted matrix (even for small matrix, with ```max_denominator=100``` and ```size = 10```).

My steps were:
1. Convert to a integer matrix
2. Invert integer matrix
3. Set-up the values as fractions

I was using ```__truediv__``` between two integers in ```invert_integer_matrix``` and returning a ```float``` matrix. Calling ```Fraction(float)/integer```` gave overflow.

I switched the division to ```__floordiv__``` since I know the division result is an integer and it works perfectly.


```
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:457: RuntimeWarning: overflow encountered in scalar multiply
  return Fraction(na * db + da * nb, da * db, _normalize=False)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:459: RuntimeWarning: overflow encountered in scalar multiply
  t = na * (db // g) + nb * s
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:459: RuntimeWarning: overflow encountered in scalar add
  t = na * (db // g) + nb * s
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:462: RuntimeWarning: overflow encountered in scalar multiply
  return Fraction(t, s * db, _normalize=False)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:463: RuntimeWarning: overflow encountered in scalar multiply
  return Fraction(t // g2, s * (db // g2), _normalize=False)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:457: RuntimeWarning: overflow encountered in scalar add
  return Fraction(na * db + da * nb, da * db, _normalize=False)
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\fractions.py:495: RuntimeWarning: overflow encountered in scalar multiply
  return Fraction(na * nb, db * da, _normalize=False)
```
