### ISSUE TITLE
multiprocessing manager classes DictProxy and ListProxy don't support typing in 3.11.4

### ISSUE THREAD

**Issue by TheMythologist** [python/cpython#107431]
# Bug report
`DictProxy` and `ListProxy` classes from `multiprocessing.managers` do not support generic annotations.

Minimal reproducible example for `DictProxy`:
```py
from multiprocessing.managers import DictProxy
from multiprocessing import Manager

d: DictProxy[str, float] = Manager().dict()
```

Error:
```error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: type 'DictProxy' is not subscriptable
```

Similar for `ListProxy`

Side note: https://github.com/python/cpython/issues/99509 appears to still be an issue as well

# Your environment
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32

### Linked PRs
* gh-107433

**Comment by sobolevn** [comment]
For older versions you can use `'DictProxy[A, B]'`, it will work, because these classes are generic in `typeshed` :)
