### ISSUE TITLE
Incorrect documentation in nltk.stem.lancaster.LancasterStemmer class

### ISSUE THREAD

**Issue by Smeetp1234** [python/cpython#107494]
In examples given in [`nltk.stem.lancaster.LancasterStemmer`](https://www.nltk.org/api/nltk.stem.lancaster.html) class, there is an example given as: 
`from nltk.stem.lancaster import LancasterStemmer`
`st = LancasterStemmer()`
`st.stem('cement')      # ditto`
where # ditto is specifying that word is not changed and kept same after appying stemming. 
But as per given output there, 'ent' got removed from word 'cement', contradictory to stated comment.
I will request to correct this problem in the documentation as it is misleading as compared to actual output.

**Comment by ronaldoussoren** [comment]
NLTK is a 3th-party library and not part of the CPython standard library.

Please file an issue with that project (https://www.nltk.org)
