### ISSUE TITLE
Outdated example code of typing.TypedDict

### ISSUE THREAD

**Issue by wanglc02** [python/cpython#107422]
# Documentation

https://docs.python.org/3.12/library/typing.html#typing.TypedDict

Changed in version 3.11: Added support for generic TypedDicts.

The text description has already changed, too:
A TypedDict cannot inherit from a non-TypedDict class, except for Generic. For example:
```python
class X(TypedDict):
    x: int

class Y(TypedDict):
    y: int

class Z(object): pass  # A non-TypedDict class

class XY(X, Y): pass  # OK

class XZ(X, Z): pass  # raises TypeError

T = TypeVar('T')
class XT(X, Generic[T]): pass  # raises TypeError
```

On the last line of the above code, `# raises TypeError` should be `# OK`. I have tested this in version 3.12. It is OK.

### Linked PRs
* gh-107423
* gh-107436
* gh-107437
* gh-107438

**Comment by AlexWaygood** [comment]
This has now been fixed, and backported to 3.12 and 3.11. Thanks @wanglc02 for opening the issue, and thanks @ghubrakesh for the PR fixing it!
