### ISSUE TITLE
creating an instance in a loop but having the same object address

### ISSUE THREAD

**Issue by vonsago** [python/cpython#107579]
# Bug report
Why does the call with the same meaning but produce so many different object address results?
Why the second results is the same object at 0x10ae4dd10?
Why the third results is  0x10ae4dd10 and 0x10ae4dd50?
Why the above results is not like the first results which have the different object address?
```
>>> class A:
...     ...
>>> for i in range(10):
...     x.append(A())
... 
>>> 
>>> x
[<__main__.A object at 0x10ae4da10>, <__main__.A object at 0x10ae4dad0>, <__main__.A object at 0x10ae4db10>, <__main__.A object at 0x10ae4db50>, <__main__.A object at 0x10ae4db90>, <__main__.A object at 0x10ae4dc10>, <__main__.A object at 0x10ae4dc50>, <__main__.A object at 0x10ae4dc90>, <__main__.A object at 0x10ae4dcd0>, <__main__.A object at 0x10ae4dbd0>]
>>> 
>>> for i in range(10):
...     print(A())
... 
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd10>
>>> for i in range(10):
...     x=A()
...     print(x)
... 
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd50>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd50>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd50>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd50>
<__main__.A object at 0x10ae4dd10>
<__main__.A object at 0x10ae4dd50>
>>> quit()
```
## Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug

# Your environment

- CPython versions tested on: Python 3.11.3 (v3.11.3:f3909b8bc8, Apr  4 2023, 20:12:10) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin and Python 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) 
- Operating system and architecture: 10.15.3 mac and linux ubuntu

**Comment by ronaldoussoren** [comment]
This is not a bug, but a question about basic Python functionality. Please ask questions like this on the discussion forum at https://discuss.python.org/c/users/7.

In this case the object id happens to stay the same when you create objects in a loop because the object you're just created is garbage collected immediately and memory is reused.
