### ISSUE TITLE
Docs for `__future__.annotations` don't mention PEP585

### ISSUE THREAD

**Issue by pfaion** [python/cpython#107530]
# Documentation

Hi everyone, I'm not 100% if this is a documentation issue. On the [page for the `__future__` module](https://docs.python.org/3/library/__future__.html#module-__future__), the feature table at the bottom lists the following as the "effect" of using ` from __future__ import annotations`:

> [PEP 563](https://peps.python.org/pep-0563/): Postponed evaluation of annotations

However, after some research I think that this does also enable _[PEP 585](https://peps.python.org/pep-0585/): Type Hinting Generics In Standard Collections_. This is also stated in [PEP 585, section "Implementation"](https://peps.python.org/pep-0585/#implementation):
> Starting with Python 3.7, when from __future__ import annotations is used, function and variable annotations can parameterize standard collections directly.

I'm not entirely sure how the "effect" of a future import is defined. Are there PEPs that specifically describe what `from __future__ import annotations` is supposed to do, or can any PEP basically "register" itself into a future feature?

I think the "effect" column on the feature table for the `__future__` module should probably be updated to include PEP 585? But I want to confirm that I understood this correctly.

**Comment by hauntsaninja** [comment]
PEP 563 is interesting in that it allows code that would produce errors to be valid annotations:
```
λ cat x.py
# from __future__ import annotations
def f(x: 1/0): ...
print("completed!")
λ python x.py
Traceback (most recent call last):
  File "/Users/shantanu/devoai/openai/x.py", line 2, in <module>
    def f(x: 1/0): ...
ZeroDivisionError: division by zero
λ vim x.py
λ cat x.py
from __future__ import annotations
def f(x: 1/0): ...
print("completed!")
λ python x.py
completed!
```

Sometimes it so happens that code that would produce an error in one version of Python, no longer produces an error in another version of Python:
```
λ python3.7
Python 3.7.13 (default, Aug  7 2022, 02:33:47) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> list[int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
>>> 

λ python3.9
Python 3.9.9 (main, Aug  7 2022, 02:25:38) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> list[int]
list[int]
```

Finally, type checkers can interpret source code however they like, and all type checkers I'm aware of choose to understand `list[int]` when combined with `from __future__ import annotations` as behaving like Python 3.9 code.

These facts combined mean that PEP 563 can be a way to "backport" PEP 585 or PEP 604 like semantics in common cases. But there is no interaction with the underlying Python runtime, and indeed, any use of annotations at runtime will blow up:
```
λ python3.7
Python 3.7.13 (default, Aug  7 2022, 02:33:47) 
[Clang 13.1.6 (clang-1316.0.21.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> def foo(x: list[int]): ...
... 
>>> import typing
>>> typing.get_type_hints(foo)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shantanu/.pyenv/versions/3.7.13/lib/python3.7/typing.py", line 1013, in get_type_hints
    value = _eval_type(value, globalns, localns)
  File "/Users/shantanu/.pyenv/versions/3.7.13/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/Users/shantanu/.pyenv/versions/3.7.13/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

See also https://mypy.readthedocs.io/en/stable/runtime_troubles.html

**Comment by pfaion** [comment]
Thank you for the quick response!

So do I understand you correctly, that whether or not using PEP 585 annotations are valid syntax is depending on the interpreter?

I would have understood the ["Implementation" section of PEP 585]()https://peps.python.org/pep-0585/#implementation) as if using `from __future__ import annotations` should always make PEP 585 annotations valid syntax:

>Starting with Python 3.7, when from __future__ import annotations is used, function and variable annotations can parameterize standard collections directly. Example:
> ```python
>from __future__ import annotations
>
>def find(haystack: dict[str, list[int]]) -> int:
>    ...
>```

I don't have a Python 3.7 interpreter at hand right now, but in my 3.8 interpreter this is indeed the case, i.e. the future import _makes this valid syntax_. Compare here without the future import:
```
Python 3.8.13 (default, Aug 16 2022, 12:16:29)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> def foo(x: list[int]): ...
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```
And here with the import:
```
Python 3.8.13 (default, Aug 16 2022, 12:16:29)
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import annotations
>>> def foo(x: list[int]): ...
...
>>>
```

**Comment by pfaion** [comment]
Some of the existing tooling around Python also seems to assume that the future import should always make PEP 585 annotations valid. But this could also be incorrectly implemented behavior in those tools!

- [pyupgrade](https://github.com/asottile/pyupgrade#pep-585-typing-rewrites) will rewrite `List[int]` to `list[int]` when the future import exists
- there is a [flake8 extension](https://github.com/tyleryep/flake8-future-annotations) that warns about not using `list[int]` when the future import exists (although they call that "PEP 563 rewrite", which in itself is inconsistent)
- the ruff linter [reimplements the mentioned flake8 warning](https://beta.ruff.rs/docs/rules/future-rewritable-type-annotation/)

As stated above, I'm aware that those tools could be wrong, so I am trying to understand how this is supposed to work.

**Comment by AlexWaygood** [comment]
> I would have understood the ["Implementation" section of PEP 585](https://peps.python.org/pep-0585/#implementation) as if using `from __future__ import annotations` should always make PEP 585 annotations valid syntax:

It's not really the case that `__future__.annotations` makes anything "valid syntax". Rather, the effect is that `__future__.annotations` causes the Python interpreter _not to interpret anything in annotations as syntax at all_. The `__future__` import changes the way Python compiles your program so that all syntax in annotations is stringified, and never in fact executed:

```pycon
Python 3.8.16 (default, Mar  2 2023, 03:18:16) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> x: int
>>> __annotations__
{'x': <class 'int'>}
>>> from __future__ import annotations
>>> y: int
>>> # Due to the __future__ import,
>>> # the annotation for "y" is the literal string "int",
>>> # rather than the class `int` itself:
>>> __annotations__
{'x': <class 'int'>, 'y': 'int'}
>>> z: list[int]
>>> __annotations__
{'x': <class 'int'>, 'y': 'int', 'z': 'list[int]'}
>>> # runtime use of PEP-585 syntax still breaks on Python <3.9,
>>> # even with __future__.annotations
>>> z = list[int]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'type' object is not subscriptable
```

> Some of the existing tooling around Python also seems to assume that the future import should always make PEP 585 annotations valid. But this could also be incorrectly implemented behavior in those tools!

If any of these tools are upgrading to PEP-585 syntax _in runtime contexts_, then yes, that would count as incorrect behaviour in these tools (though I doubt any of them are). But as @hauntsaninja mentioned above:

> PEP 563 can be used as a vehicle to "backport" PEP 585 or PEP 604 like semantics when type checking code in common cases.

And that's what all of these tools are choosing to do: they are taking advantage of the fact that code in annotation contexts will never be evaluated by the interpreter at runtime if `__future__.annotations` is enabled, and using that to upgrade your code to use PEP-585 syntax in those specific contexts.

**Comment by pfaion** [comment]
Ok, got it! That makes a lot of sense. Thanks for the detailed explanations!
