### ISSUE TITLE
run_in_executor not stopping thread after task cancellation in asyncio (Python 3.11)

### ISSUE THREAD

**Issue by dvir3211** [python/cpython#107505]
# Bug report

## A clear and concise description of the bug
The `run_in_executor` function in asyncio does not stop the thread after task cancellation.

## Steps to Reproduce
```python
import asyncio
import time

def runner():
    while True:
        print('Running.')
        time.sleep(1)

async def test():
    task = asyncio.get_event_loop().run_in_executor(None, runner)
    task.cancel()
    await task

asyncio.get_event_loop().run_until_complete(test()) 
```

## Expected Behavior
The `run_in_executor` function should stop the thread and terminate the task when it is canceled.

## Actual Behavior
The `run_in_executor` function does not stop the thread and the task continues to run even after it is canceled.

## Your environment
- CPython versions tested on: python3.11
- Operating system and architecture: macOS M1

**Comment by dvir3211** [comment]
?

**Comment by sunmy2019** [comment]
https://docs.python.org/3/library/asyncio-task.html#task-cancellation

> Tasks can easily and safely be cancelled. When a task is cancelled, [asyncio.CancelledError](https://docs.python.org/3/library/asyncio-exceptions.html#asyncio.CancelledError) will be raised in the task at the next opportunity.

Doc says **at the next opportunity**. This is usually an await point/get the result point of the future.

It means the exception is raised at
```py
    await task # <----- here
```
But your task is running on another thread, it has **no opportunity** to find this `asyncio.CancelledError`.

**Comment by sunmy2019** [comment]
Let's just say, can you find any line in
```py
def runner():
    while True:
        print('Running.')
        time.sleep(1)
```
that can raise an `asyncio.CancelledError` exception?


```py
    await task # <----- here
```
Only this line is able to raise an `asyncio.CancelledError`

**Comment by gvanrossum** [comment]
Yeah, you cannot cancel a task that never calls `await`.

It's the same without `asyncio`:
```
import concurrent.futures
f = concurrent.futures.ThreadPoolExecutor(runner)
f.cancel()
```
doesn't interrupt that `runner` function either.
