### ISSUE TITLE
difflib.sequencematcher.find_longest_match Long strings have low efficiency

### ISSUE THREAD

**Issue by yysirs** [python/cpython#107578]
# Documentation

Two strings with a length of 10w+, **find_longest_match** The efficiency of the match function is very low. Is there any way to optimize it

**Comment by ericvsmith** [comment]
What is "10w+"?

Please share any measurements or comparisons you've taken. There's not enough information here to know what exactly the issue is.

**Comment by gaogaotiantian** [comment]
I believe it was briefly discussed in https://github.com/python/cpython/issues/106865.

`find_longest_match` is **supposed** to be slow for two arbitrary strings 100k+ characters. May I ask the usage for it? I believe the correct way (or the expected way) to compare two "articles" is to do them line by line, instead of character by character.

**Comment by yysirs** [comment]
> I believe it was briefly discussed in #106865.
> 
> `find_longest_match` is **supposed** to be slow for two arbitrary strings 100k+ characters. May I ask the usage for it? I believe the correct way (or the expected way) to compare two "articles" is to do them line by line, instead of character by character.

Used to search for operations such as insert, replace, and delete in two articles.

**Comment by yysirs** [comment]
> What is "10w+"?
> 
> Please share any measurements or comparisons you've taken. There's not enough information here to know what exactly the issue is.

Sorry, the meaning of the expression is 100k+ characters.

**Comment by gaogaotiantian** [comment]
> Used to search for operations such as insert, replace, and delete in two articles and highlight the differences in content.

For articles, do not use the full string to build `SequenceMatcher`, instead, use list of lines.

```python
s1 = f1.read()
s2 = f2.read()

# DO NOT DO THIS!!
m = difflib.SequenceMatcher(a=s1, b=s2)

# Do this, or do `readlines()` when you read from the file
m = difflib.SequenceMatcher(a=s1.splitlines(), b=s2.splitlines())
```

Comparing by lines would make your program much efficient, and it normally makes sense.
