### ISSUE TITLE
Argument Clinic: param docstrings are not checked for non-ascii chars

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#107559]
Also, the warning message is a little bit strange: _"Non-ascii character appear in docstring"_

Suggesting to change the warning message to _"Non-ascii characters are not allowed in docstrings: {offending char!r}"_, and move the check from `docstring_for_c_string()` to `docstring_append()`. The former is only called for function docstrings; the latter is called both for function and parameter docstrings.

### Linked PRs
* gh-107560

**Comment by erlend-aasland** [comment]
Resolved with:

- gh-107560

**Comment by terryjreedy** [comment]
Normal docstrings do not have such a limitation.  I am curious where parameter doctrings and this limitation are documented.  Or is this specific to Arg Clinic?  The glossary 'docstring' entry makes no mentions of parameter docstrings and I cannot find anything in the index.

**Comment by erlend-aasland** [comment]
This limitation was introduced quite recently with issue gh-80282 and PR gh-12018. However, no rationale or motivation was given. There is no discussion on the issue, nor on the PR. I find this peculiar.
