### ISSUE TITLE
Typo in threading docs?

### ISSUE THREAD

**Issue by qqwqqw689** [python/cpython#107529]
https://docs.python.org/3/library/threading.html#threading.Lock.acquire

> acquire(blocking=True, timeout=- 1)
> Acquire a lock, blocking or non-blocking.
> 
> When invoked with the blocking argument set to True (the default), block until the lock is unlocked, then set it to locked and return True.
> 
> When invoked with the blocking argument set to False, do not block. If a call with blocking set to True would block, return False immediately; otherwise, set the lock to locked and return True.

Maybe True -> False.( If a call with blocking set to True would block, return False immediately; )

**Comment by AlexWaygood** [comment]
Please don't use screenshots when creating issues on GitHub. They're bad for accessibility and searchability. https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors goes into the various reasons why it's bad in greater detail.

**Comment by qqwqqw689** [comment]
@AlexWaygood OK, I have edited it.

**Comment by hauntsaninja** [comment]
The documentation is correct as far as I can tell:
```
>>> import threading
>>> l = threading.Lock()
>>> l.acquire(False)
True
>>> l.acquire(False)
False
```

**Comment by qqwqqw689** [comment]
@hauntsaninja
@AlexWaygood 
I have tried it.

This code 

`import threading`
`l = threading.Lock()`
`l.acquire(False)`

`l.acquire(True)`

blocked.

this 

`import threading`
`l = threading.Lock()`
`l.acquire(False)`

`l.acquire(False)`

didn't.

So I think " If a call with blocking set to True would block, return False immediately; " should be "" If a call with blocking set to False would block, return False immediately;

**Comment by zware** [comment]
This isn't a typo; the docs are correct as written.  It's a tricky situation to accurately describe succinctly in English, though.  It's basically "If a call with `blocking=False` had been made with `blocking=True` instead and would have blocked, return False immediately." but I'm not sure if that's actually clearer or not (or if I have all of the tenses straight :)).

**Comment by qqwqqw689** [comment]
OK, thanks :).
