### ISSUE TITLE
Move the Argument Clinic docs to the devguide

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#107518]
See [topic on Discourse](https://discuss.python.org/t/where-should-the-argument-clinic-docs-live/30160?u=erlendaasland) and python/devguide#1148

Quoting from the linked topic:

> Currently, the Argument Clinic docs live in the How-To section of docs.python.org:
>
> https://docs.python.org/3/howto/clinic.html.
>
> The devguide does not mention Argument Clinic at all (except in the experts section).
>
> The clinic docs's primary audience are core developers and contributors, which is also the primary audience of the devguide. I'd like to suggest we move the clinic docs from docs.python.org to devguide.python.org.

So far, I've only received encouraging reactions, both on Discourse and on the core dev Discord.

TODO:

- [x] Filter out Doc/howto/clinic.rst
- [x] Add the filtered out branch to the devguide: python/devguide#1160
- [x] Replace the clinic.rst contents with a link to the devguide and a short text about why the change was made

### Linked PRs
* gh-109900
* gh-110760
* gh-110761

**Comment by erlend-aasland** [comment]
Filtered out branch: https://github.com/erlend-aasland/devguide/tree/migrate-clinic-docs

**Comment by erlend-aasland** [comment]
Thanks to @AA-Turner, python/devguide#1160 has now landed!

**Comment by AA-Turner** [comment]
And now [rendered](https://devguide.python.org/development-tools/clinic/)!

A

**Comment by erlend-aasland** [comment]
> And now [rendered](https://devguide.python.org/development-tools/clinic/)!

Wow, that was fast :) Next, we need to redirect the old docs to the devguide (if possible!).

**Comment by rhettinger** [comment]
+1 for moving to the devguide.

**Comment by erlend-aasland** [comment]
Backports to 3.12 and 3.11 are queued for automerging. Marking this as resolved. Thanks to everyone who has helped with this effort; highly appreciated.
