### ISSUE TITLE
Update CI, Windows, and macOS installer builds to OpenSSL 3.0.10

### ISSUE THREAD

**Issue by ned-deily** [python/cpython#107565]
3.0.10 released 2023-08-01. None of the changes *appear* to be critical to Python usage but ...

### Linked PRs
* gh-107896
* gh-107897
* gh-108118
* gh-108119
* gh-108120
* gh-108121
* gh-108122
* gh-108123
* gh-108124
* gh-108928
* gh-108930
* gh-108932

**Comment by webknjaz** [comment]
@ned-deily all the linked PRs are merged. Should this be closed?

**Comment by ned-deily** [comment]
> Should this be closed?

Not yet: the Windows builds have not yet been updated. @zooba?

**Comment by zooba** [comment]
I just pushed the builds to our repo, so someone can update the references to use 3.0.10 now (I won't have time today, but maybe later this week)

**Comment by zware** [comment]
Done in all current branches.
