### ISSUE TITLE
Specialize `str[int]`

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#107596]
According to our [stats](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230729-3.13.0a0-5113ed7/bm-20230729-azure-x86_64-python-main-3.13.0a0-5113ed7-pystats.md), `BINARY_SUBSCR` has a 90% failure rate, and over half of those are due to `str[int]`.

This seems like an easy one to specialize.

### Linked PRs
* gh-107597

**Comment by hauntsaninja** [comment]
Nice, thank you!
