### ISSUE TITLE
Refleak tests on main with Windows 11 fails with `test_capi`

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#107628]
# Bug report

## Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project

## A clear and concise description of the bug

  ```sh
PS D:\Ken\Documents\GitHub\cpython> .\PCbuild\amd64\python_d.exe -m test test_capi -R 3:3
0:00:00 Run tests sequentially
0:00:00 [1/1] test_capi
beginning 6 repetitions
123456
.test test_capi failed -- Traceback (most recent call last):
  File "D:\Ken\Documents\GitHub\cpython\Lib\test\test_capi\test_misc.py", line 2501, in test_extended_arg
    self.assertIsNone(ex)
AssertionError: <uop_executor object at 0x000001ADE4BB9BA0> is not None

test_capi failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_capi

Total duration: 14.9 sec
Tests result: FAILURE
  ```

NOTE: the test does not fail on a normal single run of `test_capi`. It only fails with the repeated runs induced by the refleak hunter!

# Your environment

- CPython versions tested on: `main`
- Operating system and architecture: Windows 11 64-bit

**Comment by Fidget-Spinner** [comment]
This isn't something that needs to be fixed, but it's blocking the refleak buildbots which is indirectly blocking the release.

**Comment by Fidget-Spinner** [comment]
CC @markshannon

**Comment by gvanrossum** [comment]
Does #107566 not fix this?

**Comment by Fidget-Spinner** [comment]
It does. Sorry for the noise Guido. It seems I was running `main` that was 3 days old.
