### ISSUE TITLE
Replace HttpStatus by more explicit names

### ISSUE THREAD

**Issue by sylvainmouquet** [python/cpython#107668]
# Feature or enhancement

The proposal is to use a more explicit names for HttpStatus with adding the http status code in the name of the variable.

# Pitch

currently we have HttpStatus.OK when the http status code is 200
```py
HttpStatus.OK
```

The proposal is to use the same env variables used by the project starlette : 
https://github.com/encode/starlette/blob/a8b8856ce393a82ab4a714131085dbc4d658e34d/starlette/status.py#L92

```py
HttpStatus.HTTP_200_OK
```

# Previous discussion

**Comment by ethanfurman** [comment]
That would be moving backwards.  Starlette should (IMO) move to enums instead of using global variables (in which case they could use, for example, `OK` as the name and `HTTP_200_OK` as an alias so current code continues working).

**Comment by sylvainmouquet** [comment]
We could add the alias in the official HttpStatus it adds better code readability

**Comment by ethanfurman** [comment]
Better code readability is debatable.  I find reading `http` twice to be irritating; and anyone who knows `200` means OK doesn't need to read the `200`, and anyone who doesn't probably doesn't need to (and can get the value easily enough if they do).

**Comment by iritkatriel** [comment]
There isn't consensus on this issue, so I think this won't go forward without wider discussion. If you want to proceed, please start a discussion on https://discuss.python.org/c/ideas/6 and once there is agreement, create a new issue.
