### ISSUE TITLE
anext is after any

### ISSUE THREAD

**Issue by zeritonius** [python/cpython#107662]
# Documentation

In the list of builtin functions:
https://docs.python.org/3/library/functions.html
"anext" is after "any", yet in the documentation itself, on the same page, "anext" is before "any", in the correct alphabetical order.

Is this just a typo or there is a reason for it?
Thank you.

![anext](https://github.com/python/cpython/assets/89370810/9d27bad8-e83f-4bba-884c-1ec8544acced)

### Linked PRs
* gh-107663
* gh-107664
* gh-107665

**Comment by terryjreedy** [comment]
Same in 3.12 and main.  Thanks for reporting.  Prepared PR.

**Comment by terryjreedy** [comment]
Close when 3.12 is unblocked and 3.12 backport is merged.
