### ISSUE TITLE
Switch Statment for python

### ISSUE THREAD

**Issue by gauthamarcot** [python/cpython#107604]
# Feature Proposal: Addition of a `switch` Statement to Python

## Proposal Description

This proposal suggests the addition of a `switch` statement to the Python programming language. A `switch` statement allows for cleaner and more concise handling of multiple branching conditions, enhancing readability and reducing the need for lengthy `if`-`elif` chains.

## Motivation

The current lack of a `switch` statement in Python can lead to less readable and more verbose code when dealing with multiple cases. The proposed `switch` statement would address this by providing a more natural and compact way to handle branching logic.

## Syntax and Usage

The proposed `switch` statement would have the following syntax:

```python
switch expression:
    case value1:
        # code for value1
    case value2:
        # code for value2
    # ...
    default:
        # code for default case
# Example block of code of usage 
`def process_data(data, operation):
    switch operation:
        case 'add':
            result = perform_addition(data)
        case 'subtract':
            result = perform_subtraction(data)
        case 'multiply':
            result = perform_multiplication(data)
        default:
            result = handle_invalid_operation(data)

    return result
`

**Comment by JelleZijlstra** [comment]
You might be interested in the `match` statement from PEP-634; I doubt we'll add another similar construct. In any case, a change of this magnitude will need discussion on discuss.python.org and a PEP first.

**Comment by gauthamarcot** [comment]
sure @JelleZijlstra sorry my bad for raising the request
