### ISSUE TITLE
ctypes: Add docstring for `ctypes.Array`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#107689]
# Documentation

The [`Array` class](https://docs.python.org/3.13/library/ctypes.html#ctypes.Array) from the `ctypes` module doesn't have a proper docstring:

```python
from ctypes import Array
help(Array)

>>> Help on class Array in module _ctypes:
>>>
>>> class Array(_CData)
>>>  |  XXX to be provided   # !!
>>>  |
```

Though the class is documented in the [docs](https://docs.python.org/3.13/library/ctypes.html#ctypes.Array) so we could just reuse that description.

Feel free to pick up this issue :) If you're new to the C internals, here's a small guide to help you get started:

`ctypes.Array` is a class implemented in C defined in `Modules/_ctypes/_ctypes.c`. Here is the current docstring definition:

https://github.com/python/cpython/blob/71a7c96ffeb0d7fef06be3e57468896e030967a5/Modules/_ctypes/_ctypes.c#L4816-L4818

To update the docstring, we could simply change the argument of `PyDoc_STR(...)` but if the docstring is longer it's better to use [PyDoc_STRVAR](https://docs.python.org/3/c-api/intro.html#c.PyDoc_STRVAR) to create a separate variable with the new docstring:

```c
PyDoc_STRVAR(array_doc,
"Abstract base class for arrays.\n"
"\n"
"The recommended way to create ...");
```
then you substitute it back instead of `PyDoc_STR`:
```diff
Py_TPFLAGS_DEFAULT | Py_TPFLAGS_BASETYPE, /* tp_flags */ 
- PyDoc_STR("XXX to be provided"),        /* tp_doc */ 
+ array_doc,                              /* tp_doc */ 
(traverseproc)PyCData_traverse, 
```

To test that it worked, rebuild python and check the docstring ;)

### Linked PRs
* gh-107697
* gh-108882

**Comment by kostyafarber** [comment]
Can I work on this?

**Comment by tomasr8** [comment]
> Can I work on this?

Go ahead!

**Comment by kostyafarber** [comment]
@tomasr8 we can close this now as it's been merged. Thanks!

**Comment by tomasr8** [comment]
No idea what the general policy is, but searching for merged docstring PRs, I found a couple which did get backported (e.g. #103113)

**Comment by HarshKakran** [comment]
Hey! Is this issue still open?

**Comment by tomasr8** [comment]
> Hey! Is this issue still open?

The PR was `ctypes.Array` has already been merged, but  if you look through the ctypes module, there are more objects with missing docstrings (e.g. `_CData`). You might wanna have a look at those ;)
