### ISSUE TITLE
Email Content-Transfer-Encodings 7bit, 8bit and binary are not considered in Message.get_payload method

### ISSUE THREAD

**Issue by wahlflo** [python/cpython#107645]
# Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [x] I have searched the CPython issue tracker, and am confident this bug has not been reported before

# A clear and concise description of the bug

## Background
There are several possible values for the "Content-Transfer-Encoding" field in an email, indicating how the content of the email has been encoded to represent non-ASCII characters or binary data. Here are some of the commonly used values:

- ``quoted-printable``: In this encoding, non-ASCII characters and binary data are converted into a printable form by replacing them with their hexadecimal values. This encoding is suitable for texts that contain many non-ASCII characters.
- ``base64``: The content is converted into binary form and then encoded into a base-64 character string. Base64 is commonly used for encoding binary data such as images or attachments.
- ``7bit``: This value means that the email's content contains only 7-bit ASCII characters and no special encoding is required. It does not expect any non-ASCII characters or binary data.
- ``8bit``: As mentioned earlier, this value means that the content consists of 8-bit characters, including non-ASCII characters, and no special encoding is required.
- ``binary``: This value is used to indicate that the content is binary and does not require any special encoding. It expects the content to consist of 8-bit characters, including non-ASCII characters and binary data.

``quoted-printable`` and ``base64`` are considered in the method ``Message.get_payload``:

https://github.com/python/cpython/blob/407d7fda94268d70b92e2e685ca9891ec3641e78/Lib/email/message.py#L243-L328

## Problem

When the ``debug`` flag is set to ``true`` and the ``Content-Transfer-Encoding`` is one of ``7bit``, ``8bit`` or ``binary`` it is still tried to deocde the content ending up in a corrupt payload. 

## Possible Fix
Check if the ``Content-Transfer-Encoding`` is one of ``7bit``, ``8bit`` or ``binary`` and if this is case return directly the payload without any additional decoding attempts:

```python3
payload = self._payload
cte = str(self.get('content-transfer-encoding', '')).lower()
if cte in {'7bit', '8bit', 'binary'}:
    return payload 
...
```

### Linked PRs
* gh-107647

**Comment by bitdancer** [comment]
What you propose changes the documented behavior of the method, and thus cannot be done for backward compatibility reasons, even though it would certainly be nice to do it for convenience reasons.  However, this is the old API, so we aren't going to put any extra effort in to improving it.  (We really just need to make the new API the default API, but no one has stepped up to do that.  I'm hoping I'll be able to start dealing with it next year.)

If you want a better interface for getting the (properly decoded) payload, use the new API (policy=policy.default, etc) and the get_content method of message.emailMessage.
