### ISSUE TITLE
NamedTemporaryFile behaves differently based on the size of the data written to it

### ISSUE THREAD

**Issue by hedonhermdev** [python/cpython#107636]
# Bug report

## Checklist

- [x ] I am confident this is a bug in CPython, not a bug in a third-party project
- [ x] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug
When copying a `NamedTemporaryFile` to another file, the behavior is different based on the size of that file. 

In the snippet given below, the `small_file_copy` has a size of 0 while the `big_file_copy` has a size of `50000`. I don't know if this is the expected behavior or if it's because of some UNIX behavior but the docs do not go over this. 

  ```py
from tempfile import NamedTemporaryFile
import shutil

f_small = NamedTemporaryFile()
f_big = NamedTemporaryFile()

f_small.write(b'apple' * 100)
f_big.write(b'apple' * 10000)

print("small_name:", f_small.name)
print("big_name:", f_big.name)

shutil.copy(f_small.name, 'f_small_copy')
shutil.copy(f_big.name, 'f_big_copy')

with open('f_small_copy', 'r') as f:
    print('small size: ', len(f.read()))


with open('f_big_copy', 'r') as f:
    print('big size: ', len(f.read()))
  ```

Output:
```
small_name: /var/folders/p0/g9vb37tx16d0l8j95yw3s59c0000gn/T/tmp_uvfjjqa
big_name: /var/folders/p0/g9vb37tx16d0l8j95yw3s59c0000gn/T/tmp0eskqnwk
small size:  0
big size:  50000
```

# Your environment
- CPython versions tested on: Python 3.10.12
- Operating system and architecture: MacOS 13.4.1 (arm64)

**Comment by ericvsmith** [comment]
This is no doubt buffering: the contents of the file don't need to be written to disk until you close or flush the file. If you add `.flush()` calls to each file after you write the data, you'll see all of the data on disk.

**Comment by hedonhermdev** [comment]
Ah shit. Sorry.
