### ISSUE TITLE
ctypes docs: Update `ArgumentError` error messages

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#107600]
# Documentation

Now that #107456 has been merged, we should also update the examples in the docs
which still show the old message:

https://github.com/python/cpython/blob/58ef74186795c56e3ec86e8c8f351a1d7826638a/Doc/library/ctypes.rst?plain=1#L445-L447

### Linked PRs
* gh-107601

**Comment by erlend-aasland** [comment]
Resolved with:

- 107601
