### ISSUE TITLE
EnumType is not documented as new in 3.11

### ISSUE THREAD

**Issue by tim-mitchell** [python/cpython#107700]
# Documentation

In python 3.10 and earlier Enum's metaclass was called `EnumMeta`. https://docs.python.org/3.10/library/enum.html#enum-classes
In python 3.11 this was renamed EnumType (https://docs.python.org/3.11/whatsnew/3.11.html#enum).
However the fact that `EnumType` was introduced in Python 3.11 is not mentioned. https://docs.python.org/3.10/library/enum.html#enum-classes
Nor is the fact that `EnumMeta `still exists as an alias.

This would be useful to document.

### Linked PRs
* gh-108260
* gh-108300
* gh-108301

**Comment by sobolevn** [comment]
Looks like `EnumType` is documented: https://docs.python.org/3.11/library/enum.html#enum.EnumType

**Comment by AA-Turner** [comment]
@sobolevn -- I think the point is more that a ``.. versionadded:: 3.11`` directive is missing.

A

**Comment by hugovk** [comment]
Thank you!
