### ISSUE TITLE
test_tkinter leaks files in the C locale

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#107705]
```
$ LC_ALL=C ./python -m test -vuall test_tkinter -m 'test_write'
...
Warning -- files was modified by test_tkinter
Warning --   Before: []
Warning --   After:  ['@test_1061191_tmp\udce6'] 
Warning -- files was modified by test_tkinter
Warning --   Before: []
Warning --   After:  ['@test_1061191_tmp\udce6'] 
test_tkinter failed (env changed)
...
```

Since it is only a warning and occurs only in the C locale, it was unnoticed.

In the C locale Tcl uses Latin1 to encode filenames, while Python uses UTF-8.

### Linked PRs
* gh-110507
* gh-110857
* gh-110858

**Comment by terryjreedy** [comment]
Also seems to be *nix specific.  On Windows, that test invocation, with `-m 'test_write'`, runs no tests.

**Comment by serhiy-storchaka** [comment]
On Windows you should not use single quotes (actually they are not needed here on Posix too, it is a remnant of other filters).

**Comment by terryjreedy** [comment]
Duh.  With double quotes or none, test_write runs and passes without warning.  But the debug build says it is running with "locale=cp1252".  It seems that the LC_ALL setting is ignored.

**Comment by vstinner** [comment]
AsObj() has 3 code paths to encode a Python str object to Tcl/Tk:

```c
#if USE_TCL_UNICODE
        if (sizeof(Tcl_UniChar) == 2)
            encoded = _PyUnicode_EncodeUTF16(value,
                    "surrogatepass", NATIVE_BYTEORDER);
        else if (sizeof(Tcl_UniChar) == 4)
            encoded = _PyUnicode_EncodeUTF32(value,
                    "surrogatepass", NATIVE_BYTEORDER);
        else
            Py_UNREACHABLE();
#else
        encoded = _PyUnicode_AsUTF8String(value, "surrogateescape");
#endif
```

From Python, I don't see any way to detect how to know which code path is taken: ``USE_TCL_UNICODE`` and ``sizeof(Tcl_UniChar)`` are not exposed in the Python API. Not even logged by ``test.pythoninfo``. Well, ``USE_TCL_UNICODE`` is not hard to guess :-)

```c
#ifdef MS_WINDOWS
#define USE_TCL_UNICODE 1
#else
#define USE_TCL_UNICODE 0
#endif
```

Maybe ``sizeof(Tcl_UniChar)`` should be exposed in the ``_tkinter`` extension.

---

TESTFN is ``'@test_452347_tmpæ'`` string in my case. This string can be encoded to UTF-8:

```
>>> '@test_452347_tmpæ'.encode('utf8')
b'@test_452347_tmp\xc3\xa6'
```

I checked that FromObj(AsObj()) gives back the same string.

No, the problem is that the Tcl/Tk calls ``('::img::test', 'write', '@test_452819_tmpæ')`` doesn't handle non-ASCII characters and escapes them using surrogateescape for an unknown reason :-(

**For now, honestly, I would suggest to simply use an ASCII filename.**

**Comment by serhiy-storchaka** [comment]
No, it has no relation to how Tkinter convert strings between Python and Tcl.

Tcl uses Latin1 encoding for the C locale, while Python uses UTF-8. Tcl command
```tcl
open \u00e6 w
```
creates file with name consisting of one byte 0xe6 in the C locale.

It would be better to document this, but there is currently no place in the documentation where it would be appropriate.

And we need to add a workaround in the test.

**Comment by vstinner** [comment]
> It would be better to document this, but there is currently no place in the documentation where it would be appropriate.

Would it be possible to update the Python tkinter module to use the expected encoding, rather than documentation an issue?

**Comment by serhiy-storchaka** [comment]
Possible -- maybe, but with a great difficulty. You need to add a list of Tcl command that takes or returns a path, a list of options that correspond to a path, a list of variables that store paths, and on every conversion between Python and Tcl look up in these tables and re-code string from UTF-8 to Latin1 and back. It may be even more difficult if there are other conditions of if the required information is not available at the point of conversion.

**Comment by vstinner** [comment]
Can we configure Tcl to use another encoding than Latin1?

**Comment by serhiy-storchaka** [comment]
Setting locale to C.UTF-8 helps.

But this is application-level change.

**Comment by vstinner** [comment]
Thanks for the fix.
