### ISSUE TITLE
The callback signature for `PY_THROW` is inconsistent with the other exception handling callbacks

### ISSUE THREAD

**Issue by markshannon** [python/cpython#107724]
The callbacks for `RAISE`, `RERAISE`, `EXCEPTION_HANDLED`, `PY_UNWIND` and `STOP_ITERATION` all take the exception as their third argument.
`PY_THROW` is the odd one out, but it should be consistent with the others.
`PY_THROW` is a rare event, so this got overlooked. We should fix it before the next release of 3.12.

Fortunately it is very easy to fix.

### Linked PRs
* gh-107725
* gh-107802

**Comment by kumaraditya303** [comment]
Closed as backport is merged.
