### ISSUE TITLE
Appending items to empty list attribute of current object appends elements to previous object.

### ISSUE THREAD

**Issue by s4hms** [python/cpython#107720]
I have a class defined like :
```
class Test:

    def __init__(self,list1=[]):
        self.list1 = list1
```

The list1 attribute is empty by default if no corresponding value passed during initiating objects.

I've created objects of the class with no value passed for attribute list1 like: 
```
test1 = Test()
test2 = Test()
```

I have a function defined which adds values to attribute list1 for both objects test1 and test2 like:
```
def my_func(obj):
    for i in range(5):
        obj.list1.append(i)
```

I created a list which holds both objects like:
```
objects_list = [test1,test2]
```

Now I iterate over the list and pass the objects to my_function like:
```
for obj in objects_list:
    my_func(obj)
```

If I print the values for test1.list1 and test2.list1 like:
```
print(test1.list1)
print(test2.list1)
```

the expected result should look like:
```
[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4]
```

but i got:
```
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 0, 1, 2, 3, 4]
```

Python is not only appending values to attribute list1 of the current object but also to other objects in the list.

**Comment by AlexWaygood** [comment]
Hi! This isn't a bug in Python, I'm afraid, but expected behaviour. Please see:
- https://docs.python-guide.org/writing/gotchas/
- https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument
- (and many other articles)
