### ISSUE TITLE
Argument Clinic: add support for deprecating keyword use of parameters

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#107704]
See https://github.com/python/cpython/issues/95065#issuecomment-1193187512 by Serhiy. Quoting:

> Turn positional-or-keyword parameters into positional-only parameters. A directive which means "the preceding positional-or-keyword parameters will be positional-only parameters in future".

In #95151, Argument Clinic learned how to deprecate positional use of parameters. In this issue, we propose to teach Argument Clinic how to deprecate keyword use of parameters.

Suggesting to use a similar syntax as the one introduced in #95151 

```
func
   a: object
   / [from X.Y]
```

Meaning `a` will be positional-only from Python version X.Y. We can reuse parts of the code introduced in #95151 to implement this feature.

### Linked PRs
* gh-107984

**Comment by erlend-aasland** [comment]
cc. @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
I am working on this.

**Comment by erlend-aasland** [comment]
Thanks for doing this, Serhiy.
