### ISSUE TITLE
DocTestFinder.find fails if module contains class objects with special characters

### ISSUE THREAD

**Issue by gertjanvanzwieten** [python/cpython#107715]
# Bug report

## Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug

Doctests initialization may fail with `re.error` in case a module contains (dynamically generated) class objects with special characters in their name. This is caused by the regular expression compiled in `doctest.DocTestFinder._find_lineno` failing to escape the class name before embedding it. If compilation does succeed, then invalid matches may result from interpreting the class name as a search pattern.

# Your environment

- CPython versions tested on: 3.9.2
- Operating system and architecture: Debian linux amd64

### Linked PRs
* gh-107716
* gh-107726
* gh-107727

**Comment by gertjanvanzwieten** [comment]
I ran into this for our physical units framework, in which dimensions are represented by classes and quantities by instances thereof, and operations on the quantities result in dynamically created classes representing the resulting dimension. The special characters in the automatically generated names represent the operation: e.g. L*M/T2 for force. While we could use any other naming scheme to avoid triggering this issue, we prefer to keep the current one for readability during live inspection.

It is true that the line number will not be found. This is fine, we just need to get rid of the exception. Avoiding the search altogether would be equally fine if there is a way to identify dynamically created classes. However, we though that embedding an unescaped string in a regular expression is considered bad practice in general, which would suggest that the proposed fix is an improvement regardless. I see the issue with `__name__` potentially being not a string, but I am not aware of a mechanism for creating this situation while still testing true for `inspect.isclass`.

**Comment by serhiy-storchaka** [comment]
I agree that  embedding an unescaped and not validated string in a regular expression is not a good practice. It could be validated with `str.isidentifier()`, but more complex code would need tests. Also the surrounding code cries for refactoring. I cannot require it from you.

Thank you for your contribution @gertjanvanzwieten.

**Comment by gertjanvanzwieten** [comment]
Thanks for merging!

**Comment by terryjreedy** [comment]
The danger of closing before the backports are merged is that the backports may fail for weird reasons.  The CLA bot failed again on both backports.  Gertjan, try reclicking as you did before.  I added a note about the flakey bot to the coredev discord.

**Comment by gertjanvanzwieten** [comment]
Done!

**Comment by hugovk** [comment]
Thanks!
