### ISSUE TITLE
importlib.resources.as_file docs should mention it can provide whole directories

### ISSUE THREAD

**Issue by smheidrich** [python/cpython#107732]
# Documentation

As [pointed](https://discuss.python.org/t/importlib-resources-access-whole-directories-as-resources/15618/3?u=smheidrich) [out](https://discuss.python.org/t/importlib-resources-access-whole-directories-as-resources/15618/5?u=smheidrich) in a thread on the Ideas forum, `importlib.resources` gained support for extracting/returning whole directories as resources via its `as_file()` function in Python 3.12.

But [the docs](https://docs.python.org/3.13/library/importlib.resources.html#importlib.resources.as_file) make no mention of this and in fact heavily suggest the opposite (emphasis mine):

> `importlib.resources.as_file(traversable)`
>Given a [Traversable](https://docs.python.org/3.13/library/importlib.resources.abc.html#importlib.resources.abc.Traversable) object representing **a file**, typically from [importlib.resources.files()](https://docs.python.org/3.13/library/importlib.resources.html#importlib.resources.files), return a context manager for use in a [with](https://docs.python.org/3.13/reference/compound_stmts.html#with) statement. [...]
>
>Exiting the context manager cleans up any temporary **file** created when the resource was extracted from e.g. a zip file.
>
>Use as_file when the Traversable methods (read_text, etc) are insufficient and **an actual file** on the file system is required.

This should probably be changed to reflect the fact that it can now handle directories as well, not just individual files.

Especially important because being able to extract/return whole directories was a feature that `importlib.resources` lacked for quite a while compared to its now-deprecated predecessor [`pkg_resources`](https://setuptools.pypa.io/en/latest/pkg_resources.html#resource-extraction), so not pointing out that this works now can make people remain hesitant to make the switch.

PR incoming.

### Linked PRs
* gh-107734
* gh-109058

**Comment by hugovk** [comment]
Thanks, merged to main with a backport open for 3.12.
