### ISSUE TITLE
The table on ``logging`` debug levels is unclear

### ISSUE THREAD

**Issue by far-authentise** [python/cpython#107877]
## Existing Table 

Many readers need a quick discussion to interpert [the current table](https://docs.python.org/3.12/library/logging.html#logging-levels):

Level | Numeric value
-- | --
logging.CRITICAL | 50
logging.ERROR | 40
logging.WARNING | 30
logging.INFO | 20
logging.DEBUG | 10
logging.NOTSET | 0

## Suggested Table 

Level | Numeric value | Info 
-- | -- | -- 
logging.CRITICAL | 50 | Only crashing bugs | Fewest Messages 
logging.ERROR | 40 | The above, & major errors 
logging.WARNING | 30 | The above, & minor errors
logging.INFO | 20 | The above, & detailed info 
logging.DEBUG | 10 | The above, & 'helpful' messages
logging.NOTSET | 0 | No error logging | 

The number of times I've had a bug in code due to the misunderstanding, or the number of times I've needed a whiteboard and 5 minutes to explain this concept is astounding. For some reason, it's just not intuitive for like 1/3 of people I have trained or worked with. 

### Linked PRs
* gh-107894
* gh-107921
* gh-107922

**Comment by tyler-authentise** [comment]
Great Idea 👍

**Comment by AA-Turner** [comment]
cc: @vsajip

**Comment by AA-Turner** [comment]
Perhaps this table should link to the [table in the HOWTO](https://docs.python.org/3.12/howto/logging.html#when-to-use-logging), which does give descriptive overviews? It may be that those descriptions aren't discoverable enough. 

That table might also include [information on ``NOTSET``](https://docs.python.org/3.12/howto/logging.html#when-to-use-logging), as it does not mean "No error logging", but rather one of two things dependent on status as the root logger.

A
