### ISSUE TITLE
Standarize LogRecord attributes

### ISSUE THREAD

**Issue by Saphyel** [python/cpython#107881]
# Improve LogRecord class

I'm looking for standardise the attributes of the LogRecord class

At the moment this class has things like "funcName", "levelname" and "exc_info" so I think will be best to agree to have only one way to format it, this will improve the DX, because you don't have to double check things or when you want to filter the logs you know what to expect

**Comment by vsajip** [comment]
This issue comes up continually, I don't think it's possible to change the names (due to backward compatibility constraints) and I don't think it is worth the trouble to maintain aliases. Anyway, this is not specifically a logging issue - it affects numerous modules in the stdlib.
