### ISSUE TITLE
tarfile.data_filter wrongly rejects some tarballs with symlinks

### ISSUE THREAD

**Issue by encukou** [python/cpython#107845]
My implementation of PEP-706 has a bug: it wrongly determines the target of symlinks, and thus wrongly raises `LinkOutsideDestinationError` on some valid tarballs.
 
I didn't pay enough attention to this quirk of the format (which I'd like to add to [TarInfolinkname](https://docs.python.org/3/library/tarfile.html#tarfile.TarInfo.linkname) docs):

>   For symbolic links (``SYMTYPE``), the linkname is relative to the directory that contains the link.
>   For hard links (``LNKTYPE``), the linkname is relative to the root of the archive.

So, in a tarball that contains the following, the links point to `dir/target`:

- `dir/target`
- `other_dir/symlink` -> `../dir/target`
- `other_dir/hardlink` -> `dir/target`

But `data_filter` thinks that `other_dir/symlink` will point to `../dir target` outside the destination directory.

I have a fix but would like to test it more next week, before merging.
Sorry for the extra work this'll cause for a lot of people :(

### Linked PRs
* gh-107846
* gh-108209
* gh-108210
* gh-108211
* gh-108274
* gh-108279

**Comment by encukou** [comment]
3.13 PR is merged.
3.12 PR is merged (thanks Thomas)!
Buildbots are running on the 3.11 PR: https://github.com/python/cpython/pull/108209
If the bots don't find any issues I'll continue with the older releases (3.10 needs adjusting tests, 3.9-3.8 doesn't apply cleanly in Git).

**Comment by hugovk** [comment]
Ready to close this issue?

**Comment by encukou** [comment]
Yes, thank you for the ping.
For reference, the affected versions, which can raise unwanted `tarfile.LinkOutsideDestinationError` on valid input, are:

```python
sys.version_info[:3] in {(3, 8, 17), (3, 9, 17), (3, 10, 12), (3, 11, 4)}
```
