### ISSUE TITLE
Extend netlink support to FreeBSD

### ISSUE THREAD

**Issue by igalic** [python/cpython#107812]
# Feature or enhancement

Extend [`socket`](https://docs.python.org/3/library/socket.html)'s `AF_NETLINK` support to FreeBSD.

# Pitch

FreeBSD 13.2-RELEASE was the first FreeBSD release with a solid support of netlink.
Previously this was Linux only technology, but has established itself as a standard: https://www.rfc-editor.org/rfc/rfc3549

# Previous discussion

This is all pretty new, so I am unaware of previous discussions.

### Linked PRs
* gh-107813

**Comment by igalic** [comment]
is there any way to get this packported to 3.12 at least, so FreeBSD ports won't have to carry this patch for the next couple years?

**Comment by Eclips4** [comment]
> is there any way to get this packported to 3.12 at least, so FreeBSD ports won't have to carry this patch for the next couple years?
> 
> the python team is preparing a bump to 3.10 right now, which is marked as security release https://www.python.org/downloads/ and since this isn't a bug fix, it can't go into 3.11
> 
> but 3.12 isn't out _yet_ do I'm hoping we can backport it there at least

Perhaps it's a good idea, but 3.12 currently in the stage of "feature freeze", so 3.12 branch accepts only bug fixes.
cc @Yhg1s

**Comment by erlend-aasland** [comment]
> [...] but 3.12 currently in the stage of "feature freeze", so 3.12 branch accepts only bug fixes and some other stuff with approve of release manager.

3.12 has entered the Release Candidate phase; nothing goes into 3.12 without RM approval. IMO this is out of the question for 3.12; the FreeBSD ports will have to maintain their patches for another release. (That should not be too hard for them; there has been no requests for it so far, so I find it hard to see that this is a major pain point.)

**Comment by Yhg1s** [comment]
Yes, it's too late for 3.12. Feature freeze was back in May, and although I might have let in a change like this one in one of the early betas, it's much too late to include now.
