### ISSUE TITLE
Double linked list implementation for asyncio tasks

### ISSUE THREAD

**Issue by kumaraditya303** [python/cpython#107803]
Currently `asyncio` tasks are stored in a `Weakset`, this is inefficient and in some cases causes bugs because of thread safety (https://github.com/python/cpython/issues/80788). In terms of memory usage it requires maintaining a full set and their corresponding weakref callback to cleanup objects when deallocated and finalized by the gc. In applications where tasks are created at fast pace this becomes a bottle neck, to mitigate this now `asyncio` tasks will now be stored in a global double linked of tasks for cases where Task is a subclass of `_asyncio.Task` in other cases we still rely on the weakset. This reduces the work done by the gc speedups the execution and reduces memory usage. In some of my own benchmarks I have seen 15- 20% improvement and pyperformance benchmarks reflect roughly the same.

https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20230805-3.13.0a0-1d32835/bm-20230805-linux-x86_64-kumaraditya303-linked_list-3.13.0a0-1d32835-vs-base.md

Updated: https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20240622-3.14.0a0-4717aaa#vs-base

### Linked PRs
* gh-107804
* gh-120995
* gh-121007
* gh-126577

**Comment by colesbury** [comment]
I think there are some thread-safety issues with the linked list implementation:

* It's not going to be thread-safe in the free-threaded build. We can probably add a lock or a critical section.
* Even with the GIL, the linked list of tasks may be modified while it's being looped over because the GIL can be released in `add_one_task`.

**Comment by willingc** [comment]
Thanks @colesbury for flagging this.

**Comment by kumaraditya303** [comment]
I am closing this, will track free threaded issues in https://github.com/python/cpython/issues/120974

**Comment by colesbury** [comment]
@kumaraditya303, can you fix the thread-safety/reentrancy issue that affects the default build (with the GIL)? `head` can be deallocated while it's being used. It needs to be protected by a `Py_INCREF()`. This is not specific to the free-threading build.

https://github.com/python/cpython/blob/2d3187bf205ae826bab3d5cf67c0c673e8af2a88/Modules/_asynciomodule.c#L3711-L3721
