### ISSUE TITLE
ssl.PROTOCOL_TLS is deprecated   ssl_context = ssl.SSLContext(ssl.PROTOCOL_TLS)

### ISSUE THREAD

**Issue by anirbanchakrabarty** [python/cpython#107890]
# Crash report

# Error messages

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by ronaldoussoren** [comment]
Please add more a more descriptive message and just a short summary that describes document behaviour.

In particular the SSL module documentation documents that the constant is deprecated and why:

> Deprecated since version 3.10: TLS clients and servers require different default settings for secure communication. The generic TLS protocol constant is deprecated in favor of [PROTOCOL_TLS_CLIENT](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_CLIENT) and [PROTOCOL_TLS_SERVER](https://docs.python.org/3/library/ssl.html#ssl.PROTOCOL_TLS_SERVER).
