### ISSUE TITLE
`turtle.teleport` has incorrect-ish signature

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#107805]
# Bug report

`turtle.teleport` added in https://github.com/python/cpython/pull/103974 seems not quite correct.

Why?
1. It is produced automagically from `Turtle.teleport` instance method. It has this signature: `def teleport(self, x=None, y=None, *, fill_gap: bool = False) -> None:`
2. The result function `turtle.teleport` has this signature: `def teleport(x, y=None, fill_gap=None)`

Notice that it is missing `x=None` default and for some reason `fill_gap` is not a kw-only anymore.

The second problem happens because inside it uses `inspect.getargs`: https://github.com/python/cpython/blob/52fbcf61b5a70993c2d32332ff0ad9f369d968d3/Lib/turtle.py#L3927 which translates kw-only to positional-or-keyword params.

So, when I try to run `turtle.teleport` I get:

```python
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/ex.py", line 60, in <module>
    print(teleport())
          ^^^^^^^^^^
TypeError: teleport() missing 1 required positional argument: 'x'
                     
```

And with just one arg:

```python
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/ex.py", line 60, in <module>
    print(teleport(1))
          ^^^^^^^^^^^
  File "<string>", line 4, in teleport
TypeError: Turtle.teleport() takes from 1 to 3 positional arguments but 4 were given
                        
```

Annotations are also missing. It is not a big problem, but it is inconvenient.

I propose using `inspect.signature` instead. It will allow us using pos-only and keyword-only params with ease.

I have a PR ready.

Found while working on https://github.com/python/typeshed/pull/10548
CC @AlexWaygood and @terryjreedy 

### Linked PRs
* gh-107807
* gh-108749

**Comment by gpshead** [comment]
FWIW the bug in the PR adding teleport was added by me as I decided fill_gap should be keyword only for a more readable API feel, without realizing that such gross hacks existed elsewhere within turtle that relied on `inspect` in this manner. yuck! good find.
