### ISSUE TITLE
``map`` and ``filter`` are documented as taking functions, not callables

### ISSUE THREAD

**Issue by odigosdev** [python/cpython#107867]
# Documentation

Signatures of `map` and `filter` are incorrect, they designated as "as first parameter we accept an function", but in fact, they accepts a`callable` object. 

# Links
https://docs.python.org/3/library/functions.html#filter
https://docs.python.org/3/library/functions.html#map

**Comment by AA-Turner** [comment]
I'm not sure we need to change this, as in many places we use *function* and *callable* interchangeably.

A

**Comment by Geekverma** [comment]
@implAikawa can you mention on which file & line number it is?

**Comment by implAikawa** [comment]
@Geekverma If you mean PyDoc_STRVAR. That's it:
Map: https://github.com/python/cpython/blob/main/Python/bltinmodule.c#L1434
Filter: https://github.com/python/cpython/blob/main/Python/bltinmodule.c#L623

**Comment by Geekverma** [comment]
Yes

**Comment by Geekverma** [comment]
so you just to be signatures as per doc?

**Comment by implAikawa** [comment]
@AA-Turner Hmm...Yeah, I just haven't heard about it anywhere. I just think that a function is a member of the callable set. That's why I didn't think about you using them as synonyms.

**Comment by implAikawa** [comment]
@AA-Turner It's just that some beginners take it literally (like me) and think that only a function can be used in the first parameter, some even believe in it.
As far as I understand, this is too voluminous work and hardly anyone will undertake it. If yes, then I'll close the issue.

**Comment by terryjreedy** [comment]
The parameter names in a signature are just that -- a name used to refer to the parameter.  We could have given the signature as "filter(foo, bar)" but we try to use more descriptive names that hint at the type.  In the mathematical sense, all callables can be viewed as functions.  But I won't deny that 'function' in our docs is sometimes a bit of a slippery term.
