### ISSUE TITLE
Typo "consecuence" in 3.12 whatsnew

### ISSUE THREAD

**Issue by wookie184** [python/cpython#107891]
Typo is here, "consecuence" should be "consequence":
https://github.com/python/cpython/blob/2e27da18952c6561f48dab706b5911135cedd7cf/Doc/whatsnew/3.12.rst?plain=1#L1579

I'll open a PR.

## Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [x] I have searched the CPython issue tracker, and am confident this bug has not been reported before

### Linked PRs
* gh-107892
* gh-107893

**Comment by AlexWaygood** [comment]
Thanks, PR welcome!
