### ISSUE TITLE
`typing.TypeAliasType` doesn't implement `__instancecheck__`

### ISSUE THREAD

**Issue by tushar-deepsource** [python/cpython#107819]
# Bug report

## Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [x] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug

The new `type` syntax in 3.12 creates `typing.TypeAliasType` objects, but the types created by this type are not checkable via `isinstance()`.

This seems inconsistent, because other similar types introduced by new syntax (such as `typing.UnionType`) work just fine with `isinstance()`.

```python
>>> T = int | str
>>> type(T)
<class 'types.UnionType'>
>>> # isinstance works here
>>> isinstance(5, T)
True

>>> type U = int
>>> type(U)
<class 'typing.TypeAliasType'>
>>> # isinstance DOESN'T work here
>>> isinstance(5, U)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

This severely limits the usability of the `type` syntax for any runtime usage.

# Your environment

- CPython versions tested on: `3.12.0rc1`
- Operating system and architecture: Docker image `python:3.12-rc-alpine`, running on MacOS Ventura

**Comment by JelleZijlstra** [comment]
This is correct and intended behavior. PEP 695 type aliases can contain arbitrarily complex types, many of which will not work with `isinstance()` (e.g., `type L = list[int]`). If you want to change this behavior, please open a discussion on discuss.python.org first.

**Comment by tusharsadhwani** [comment]
For this usecase the `isassignable()` function from [trycast](https://pypi.org/p/trycast) seems more reasonable.
