### ISSUE TITLE
some of the generated build files use the default system line ending

### ISSUE THREAD

**Issue by maxbachmann** [python/cpython#107816]
# Bug report

Some of the generated files use the default system line ending. This leads to changes of the line endings when generating on different systems (e.g. Linux vs Windows). Since they are currently checked in using lf as line ending, this is probably what should be used when generating them on every system.

### Linked PRs
* gh-107817

**Comment by maxbachmann** [comment]
At least in our case we store vendor repositories as part of our own monorepo. We could probably tell our version control system to store them using a specific line ending. However I feel like they should just generate the same files on different operating systems instead of relying on the version control system to fix up the files. Especially given how simple it is to generate these files with the appropriate line endings.

**Comment by encukou** [comment]
But if this is changed, all tools that work with the files on disk will need to recognize `\n` as a line ending. I don't know if that's the case.
And given I work on a system that uses `\n`, I don't feel qualified to decide.

**Comment by maxbachmann** [comment]
These specific files are `.py`, `.h` and `.c` files. Which are only used by the specific interpreter/compiler. We expect them to handle `\n` as line ending, since that is the line ending we use for all code files that are not generated.

**Comment by gvanrossum** [comment]
> We expect them to handle `\n` as line ending, since that is the line ending we use for all code files that are not generated.

Really? That's what we have in Git and GitHub, yes, but what I see in my working directories on my Windows laptop uses system line ends. So with this PR (gh-107817) the generated files would actually become the odd ones out. That feels wrong to me. The `newlines=...` option to `open()` feels esoteric, and I don't like having to use it.

**Comment by encukou** [comment]
Indeed. The PR would change behaviour for anyone who *does* use the recommended repo setting on Windows. Note that this setting is also default for Git on Windows.
This is something you should handle in your monorepo system.

**Comment by maxbachmann** [comment]
>  The PR would change behaviour for anyone who does use the recommended repo setting on Windows. Note that this setting is also default for Git on Windows.

Recommended as in recommended by cpython or git? I couldn't find anything related to this in https://github.com/python/cpython/blob/main/PCbuild/readme.txt.

Overall this is not really an issue for me. I can absolutely handle this in our monorepo system. I mainly opened this issue thinking this was a bug, so if it's not I am happy with closing the issue + PR.

**Comment by encukou** [comment]
CPython's devguide recommends it: https://devguide.python.org/getting-started/git-boot-camp/#enabling-autocrlf-on-windows
Git man pages don't make recommendations (and Git rarely changes its defaults), but adjacent projects recommend it:
* the Git book: https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_core_autocrlf -- “If you’re on a Windows machine, set it to true”
* GitHub: https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings?platform=windows#global-settings-for-line-endings
* the Git for Windows GUI installer has `true` selected by default:
   
   ![image](https://github.com/python/cpython/assets/302922/4062fd92-bb19-4753-a6e8-95dc8a15b6a6)


> Overall this is not really an issue for me. I can absolutely handle this in our monorepo system. I mainly opened this issue thinking this was a bug, so if it's not I am happy with closing the issue + PR.

Let's go with that.
Thanks for bringing it up!

**Comment by maxbachmann** [comment]
Thanks for the reference to the development guide :+1:
