### ISSUE TITLE
Add lzo1z decompression

### ISSUE THREAD

**Issue by gupta-ekansh** [python/cpython#107806]
# Feature or enhancement

# Pitch

# Previous discussion

**Comment by ronaldoussoren** [comment]
There's at least one project on PyPI that claims to support LZO compression and decompression (https://pypi.org/project/python-lzo/).

If you mean to ask if LZO compression can be supported in the standard library: you'll have to defend why supporting this in a package on PyPI is not good enough.

**Comment by terryjreedy** [comment]
To ask questions, such as 'how can I do lzo decomplession in Python?', please post to https://discuss.python.org/c/users/7 .  To propose a new feature, with suporting arguments as requested above, post to https://discuss.python.org/c/ideas/6.
