### ISSUE TITLE
find_python.bat is not properly silenced

### ISSUE THREAD

**Issue by maxbachmann** [python/cpython#107814]
# Bug report

When `find_python.bat` is run without a Python interpreter present on the system it installs an interpreter via nuget. However in this case it does not properly silence output to stdout when `-q` is passed. This leads to issues when the user relies on only the interpreter path to be printed, which is the case when it is used inside visual studio.

### Linked PRs
* gh-107815
* gh-107823
* gh-107824

**Comment by zooba** [comment]
Thanks! The backports should get merged sometime soon, but I'll close the issue now.
