### ISSUE TITLE
Setuptools - Global range ([0-9]) not working

### ISSUE THREAD

**Issue by deragon** [python/cpython#107949]
# Description

When `MANIFEST.in` contains `global-exclude *202*`, any file with this string is being excluded such as `file3_20230814T111336.py` (WORKS AS INTENDED).

However, when  `MANIFEST.in` contains `global-exclude *202[0-9]*`, any file with a string that follows that glob-style pattern gets included, such as one named `file3_20230814T111336.py`.  **That is the BUG.**

Note that I tested the glob-style pattern an it is valid:

```
$ find . -name '*202[0-9]*'
./src/file3_20230814T111336.py
```

Last note, when  `MANIFEST.in` contains `global-exclude *202[23]*`, that does work and `file3_20230814T111336.py` gets excluded.  The [] syntax seams to work partially, but its "range" functionality does not.

Setuptools is not following what its documentation is referring to at [Controlling files in the distribution](https://setuptools.pypa.io/en/latest/userguide/miscellaneous.htm) which points to [PyPA’s Packaging User Guide](https://packaging.python.org/en/latest/guides/using-manifest-in/).  In this last page, we do find:

> matches any one of the characters between the square brackets (which may contain character ranges, e.g., [a-z] or [a-fA-F0-9]). 

# Environment

```
$ python --version
Python 3.10.12

$ pip freeze
build==0.10.0
packaging==23.1
pyproject_hooks==1.0.0
# Editable install with no version control (setuptools-tests==1.0)
-e <somedir>/setuptools-test
tomli==2.0.1
```

# Setup to reproduce the problem

[setuptools-globstyle-bug.zip](https://github.com/python/cpython/files/12338110/setuptools-globstyle-bug.zip)

**Comment by hugovk** [comment]
This is the tracker for CPython not setuptools. Please report setuptools issues to their tracker at https://github.com/pypa/setuptools.
