### ISSUE TITLE
`class My[X](object):` raises `TypeError: Cannot create a consistent method resolution order`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#107909]
```python
>>> class My[X](object): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <generic parameters of My>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic
```

It looks like a correct error: 

```python
>>> from typing import Generic
>>> from typing import TypeVar
>>> T = TypeVar('T')
>>> class A(object, Generic[T]): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic

>>> class A(Generic[T], object): ...
... 
>>> 
```

But it is not tested. I think that `object` is quite an important corner-case to test it explicitly.

`class My[X]():` is tested.

### Linked PRs
* gh-108001
* gh-108022

**Comment by brandonardenwalli** [comment]
Hi! I am to try to follow along, but I am not able to get the same error from the first example you give:

`class My[X](object): ...`

gives me `File "<stdin>", line 1
    class My[X](object): ...
            ^
SyntaxError: invalid syntax`

the second example works for me though:
`class A(object, Generic[T]): ...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic`

Am I doing something wrong? How to fix to reproduce the same error as you?

P.S. how to make code formatting look like your examples? I use the "Add code" button but my code looks different from yours in the preview.

**Comment by brandonardenwalli** [comment]
Okay, I run again after great suggestion from JelleZijlstra in other conversation. I can now reproduce:
`class My[X](object): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <generic parameters of My>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic
>>> from typing import Generic
>>> from typing import TypeVar
>>> T = TypeVar('T')
>>> class A(object, Generic[T]): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic
>>> class A(Generic[T], object): ...
...
`


For anyone also stuck with same problem as me above, try to do https://github.com/python/cpython/issues/107905#issuecomment-1678277984/

**Comment by AlexWaygood** [comment]
@brandonardenwalli, please use triple backticks to format multiline code blocks, i.e.:

````
```
Your code here 
```
````
