### ISSUE TITLE
`TypeError: Cannot create a consistent method resolution order`, why the newline?

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#107910]
Repro:

```
>>> class My[X](object): ...
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <generic parameters of My>
TypeError: Cannot create a consistent method resolution
order (MRO) for bases object, Generic
```

Notice that there's a `\n` between "resolution" and "order".

This code exists for 21 years now: https://github.com/python/cpython/blame/main/Objects/typeobject.c#L2447
And it does not look anyone else is bothered :)

For me, `TypeError: Cannot create a consistent method resolution order (MRO) for bases object, Generic` would be a much better error message.

Opinions?

### Linked PRs
* gh-107928

**Comment by sunmy2019** [comment]
That error message could be too long for long type names.
I'd like the first line within 80 characters.

```
TypeError: Cannot create a consistent method resolution order (MRO) for
bases object, Generic
```

**Comment by ericvsmith** [comment]
Is there anywhere else where error messages contain newlines?

If this is the only place, then I suggest removing it. If it's a common pattern, figure out what the rule is ("first line < 78 chars", or whatever), document it and apply the rule here.

**Comment by xncbf** [comment]
I made a PR by fixing the doc message not requiring a newline, including the error message.

**Comment by serhiy-storchaka** [comment]
Initially it was much longer error message:
```c
       off = PyOS_snprintf(buf, sizeof(buf), "Cannot create class.\
The superclasses have conflicting\n\
inheritance trees which leave the method resolution order (MRO)\n\
undefined for bases");
```
But I do not think it still needs to be multi-line and be split at random point. It does not make it more readable, taking into account that it is only a part of the error message, and the full error message, including the list of type names, can be up to 1000 characters long.
