### ISSUE TITLE
clarify documentation on when `os.lchmod()` is missing

### ISSUE THREAD

**Issue by calestyo** [python/cpython#107959]
# Documentation

`lchmod()` is not part of POSIX, see 
https://pubs.opengroup.org/onlinepubs/9699919799/functions/chmod.html but only mentioned there for systems which support changing the file permission bits of symbolic links:
> Some implementations might allow changing the mode of symbolic links. This is not supported by the interfaces in the POSIX specification. Systems with such support provide an interface named lchmod(). To support such implementations fchmodat() has a flag parameter.

Therefore, `lchmod()` isn't available on any Unixes, which don't do so.
According to  https://unix.stackexchange.com/questions/224979/why-do-linux-posix-have-lchown-but-not-lchmod this might be a majority.<br> In any case, Linux, which nowadays is undoubtedly the most important POSIX/Unix-like system, doesn't do so.

I shall provide a MR, which adds some clarification to the documentation about this.

Cheers,
Chris.

### Linked PRs
* gh-107960
* gh-113066
* gh-113067

**Comment by serhiy-storchaka** [comment]
Thank you @calestyo. I just created a PR for `lchmod()` on Windows and figured out that it is weird to write that it is available on both Unix and Windows when it is not available on Linux.

**Comment by calestyo** [comment]
Thanks for merging. I do have a number of other issues open with resect to `os`, `stat` and the likes. Especially the issue with `os.path.ismount()` being buggy and the PR for `stat` would be great if they could get some attention by some Python devs.
