### ISSUE TITLE
pydev debugger: This version of python seems to be incorrectly compiled

### ISSUE THREAD

**Issue by BareonZahar** [python/cpython#107917]
# Bug report

## Checklist

- [ ] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the CPython issue tracker, and am confident this bug has not been reported before

## A clear and concise description of the bug

pydev debugger: CRITICAL WARNING: This version of python seems to be incorrectly compiled (internal generated filenames are not absolute) pydev debugger: The debugger may still function, but it will work slower and may miss breakpoints.

# Your environment

- CPython versions tested on:
- Operating system and architecture:

**Comment by hugovk** [comment]
Please give more detail as requested in the template, also let us know where you got your Python from and how you installed it.

Let's close this issue in the meantime.

**Comment by BareonZahar** [comment]
Здравствуйте я хотел чтоб вы мне подсказали как устранить эту проблему
