### ISSUE TITLE
Unnecessary comment about increasing the reference count in usage of ``Py_None`` 

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#107955]
After merging of #19474 this comment looks unnecessary:
https://github.com/python/cpython/blob/8d3cb1bc4b5de091d7b5fcc5ce7378151a8f4f45/Include/object.h#L849

### Linked PRs
* gh-107993

**Comment by Eclips4** [comment]
cc @eduardo-elizondo

**Comment by corona10** [comment]
Do you want to send a PR to update the comment?

**Comment by brandonardenwalli** [comment]
If possible, I can do the change too? This looks to be fairly simple and I think I should be able to do.

**Comment by Eclips4** [comment]
> If possible, I can do the change too? This looks to be fairly simple and I think I should be able to do.

Go ahead =)

**Comment by brandonardenwalli** [comment]
Great, I will make fix soon!

**Comment by eduardo-elizondo** [comment]
Good catch, and yeah, as @corona10 mentioned, feel free to create a PR to clean it up 🙂
