### ISSUE TITLE
``asyncio.{timeout_at,timeout}`` are incorrectly documented as ``coroutine``

### ISSUE THREAD

**Issue by graingert** [python/cpython#107980]
# Documentation

[``asyncio.timeout_at``](https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout_at) and [``asyncio.timeout``](https://docs.python.org/3/library/asyncio-task.html#asyncio.timeout) are documented as ``coroutine`` but they are synchronous functions that return async context managers.

### Linked PRs
* gh-108126
* gh-108152
* gh-108153

**Comment by gvanrossum** [comment]
@Tinche I think you wrote those docs originally -- maybe you can help fix them too?

**Comment by Tinche** [comment]
Sure, I can take this.

I must've stuck on the `coroutinefunction` role on there as closest that sounded right. But you're right, these aren't coroutine functions, they're really async context managers, or technically async context manager factories I guess.

I can just convert these to `function`s, or would adding a new role for async context managers be a better play? I see these roles are defined in https://github.com/python/cpython/blob/main/Doc/tools/extensions/pyspecific.py, might not be too hard adding a new one. As far as I can tell, there are only a few async context managers in the stdlib currently: TaskGroup and Timeout, AsyncExitStack and aclosing. Maybe they'd benefit from a documentation prefix similar to the current `coroutine`.

**Comment by graingert** [comment]
> Perhaps the analogous position would be mark timeout as an [async function](https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-option-py-function-async)?

`timeout` is not an async function, it's a synchronous function that returns an instance of `asyncio.Timeout`
