### ISSUE TITLE
test_tarfile fails on file modes

### ISSUE THREAD

**Issue by furkanonder** [python/cpython#107902]
## Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the CPython issue tracker, and am confident this bug has not been reported before

#
```bash
[ted@rasp4 cpython]$ ./python -m test test_tarfile
0:00:00 load avg: 0.27 Run tests sequentially
0:00:00 load avg: 0.27 [1/1] test_tarfile
test test_tarfile failed -- Traceback (most recent call last):
  File "/home/ted/cpython/Lib/test/test_tarfile.py", line 3679, in test_modes
    self.expect_file('all_bits', mode='?rwsrwsrwt')
  File "/home/ted/cpython/Lib/test/test_tarfile.py", line 3429, in expect_file
    self.assertEqual(got, mode)
AssertionError: '?rwsrwxrwt' != '?rwsrwsrwt'
- ?rwsrwxrwt
?       ^
+ ?rwsrwsrwt
?       ^
```

# Your environment

- CPython versions tested on: Python 3.13.0a0
- Operating system and architecture:  Manjaro ARM Linux aarch64 | Raspberry Pi 4 Model B Rev 1.5
- Configuration of CPython: ./configure --with-pydebug

### Linked PRs
* gh-108368
* gh-125255
* gh-125576
* gh-125835

**Comment by encukou** [comment]
Thanks for the report!
The test fix was merged in main. Let me know if you need a backport -- I won't make one by default since this is only a test issue for a platform without buildbots. I assume you can patch/skip the test on your build.
