### ISSUE TITLE
underscore after Z or before a

### ISSUE THREAD

**Issue by zeritonius** [python/cpython#107950]
# Documentation

On the list of modules,
https://docs.python.org/3/py-modindex.html
_ is before a.

However, on the list of functions,
https://docs.python.org/3/library/functions.html
_ is after Z.

1. I was wondering if _ is best before A on the list functions as well.

2. I also noticed that small letters (a, b, ...) are used for module index, while capital letters (A, B, ...) are used for functions index. Would small letters be best on list functions as well, considering that the functions' names start with small letters?

Thank you.

![underscore2](https://github.com/python/cpython/assets/89370810/03021915-fb67-45ca-a88d-42d3581d6571)

**Comment by brandonardenwalli** [comment]
Hello, I am still learning and want to calrify for my understanding: what way is best to sort when making documentation? Is there a guideline for this, or based on majority opinion?
