### ISSUE TITLE
Unused `maxsize` argument in `_init` method of `queue.Queue`

### ISSUE THREAD

**Issue by shailshouryya** [python/cpython#107906]
# Feature or enhancement

Note: this is less of a feature or enhancement, and more of a technical debt refactor - however, I don't see an Issue option for "Refactoring," so this is the closest label.

The `__init__` method of `queue.Queue` passes in the `maxsize` argument to the `_init` method:
https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/queue.py#L34-L36

but the `_init` method does not actually use the `maxsize` argument at all:
https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/queue.py#L205-L209

# Pitch

Remove this unused `maxsize` argument.

### Linked PRs
* gh-107907

**Comment by shailshouryya** [comment]
Also, it looks like `asyncio.queues.Queue` has some similar leftovers (https://github.com/python/cpython/pull/107907#issuecomment-1676265948):
https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/asyncio/queues.py#L33-L50

https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/asyncio/queues.py#L224-L227

https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/asyncio/queues.py#L237-L240

**Comment by sweeneyde** [comment]
Since the Queue class is designed to be inherited from with `_init` overridden, I would suggest not to change this, especially when there is no tangible benefit beyond refactoring.

We wouldn't want to break user code that has its own `_init` implementation that expects `maxsize`, such as if someone has code like in https://github.com/python/cpython/issues/51586 that has been working for a decade.

**Comment by sunmy2019** [comment]
That `maxsize` argument left unused for 10 years is also for compatibility reasons.

**Comment by shailshouryya** [comment]
Interesting, I thought variables prefixed with a `_` (underscore) indicated that a variable/function/method is an "internal" implementation detail. Is that not the case for core modules? Or is that only for C source files for the core dependencies?

In that case, might it be useful to add a comment providing this context?

**Comment by rhettinger** [comment]
As noted by others, this would be a breaking change.  The code specifically advises users to override those methods in subclasses.  If you change the call signature, it breaks every one of those user customizations.  Also, some of the those may actually need the `maxsize` argument which is likely why Guido included it in the API.

There is also a principle of "Chesterson's fence" and an assumption that the people who came before you (the original author and all of the subsequent maintainers) knew what they were doing.

**Comment by shailshouryya** [comment]
Got it, that makes sense - I know the `__init__` method is usually overridden in subclasses, but didn't see that the `_init` method here was supposed to be overridden in subclasses, and didn't see it in the [docs page either](https://docs.python.org/3/library/queue.html). Where is that written? (I understand this is a breaking change and won't go in, I'm just curious where this info was since I missed it)

**Comment by brandonardenwalli** [comment]
Hello, I am looking through recent issues and trying to follow along, and this to me looks to be a simple issue but I do not understand why this pitch is no good. According to what I learn so far, to me I understand code with the _ (underscore) should be thought to be "private" and no depend on it, and above in this conversation also mention this. But anyways, it looks like _init do not use maxsize anymore now, so even the code itself changed?

Also, for the code to specifically advises users to override those methods in subclasses, where is this? I no find this where I look. I look at https://github.com/python/cpython/blob/ee40b3e20d9b8d62a9b36b777dff42db1e9049d5/Lib/queue.py and at https://docs.python.org/3/library/queue.html but both of them do not say to keep _init?

Also, https://github.com/python/cpython/issues/51586 look to me like it was a suggest that was never add to here, no? For example, it says

> Using current queue module classes this is not practical, because there
is a choice between unbounded memory consumption or blocking. I propose
adding a 'LossyQueue' class in the queue module which would allow
bounded memory consumption without blocking on put.

But at bottom it look like this suggest did not become used? Or maybe I not understand "Right now, it is not at all clear that this is the right thing to do" correctly?
