### ISSUE TITLE
`enum` docs display incorrect output for `dir`

### ISSUE THREAD

**Issue by ujan-r** [python/cpython#107957]
The `__dir__` methods for `EnumType`/`EnumMeta` and `Enum` were changed in Python 3.11, but the documentation hasn't been updated. For example:

https://github.com/python/cpython/blob/a2a4b9f1ec86b9762a5d35895ac5b528e03d5b98/Doc/howto/enum.rst?plain=1#L1053-L1056

The actual output (for Python 3.11+) is:
```py
>>> dir(Planet)
['EARTH', 'JUPITER', 'MARS', 'MERCURY', 'NEPTUNE', 'SATURN', 'URANUS', 'VENUS', '__class__', '__contains__', '__doc__', '__getitem__', '__init_subclass__', '__iter__', '__len__', '__members__', '__module__', '__name__', '__qualname__']
>>> dir(Planet.EARTH)
['EARTH', 'JUPITER', 'MARS', 'MERCURY', 'NEPTUNE', 'SATURN', 'URANUS', 'VENUS', '__class__', '__doc__', '__eq__', '__hash__', '__module__', 'mass', 'name', 'radius', 'surface_gravity', 'value']
```

There are other examples with incorrect outputs in [Doc/library/enum.rst](https://github.com/python/cpython/blob/8d3cb1bc4b5de091d7b5fcc5ce7378151a8f4f45/Doc/library/enum.rst).

### Linked PRs
* gh-107958

**Comment by ethanfurman** [comment]
Code has been updated to match the docs.
