### ISSUE TITLE
os.sendfile() flags improperly ordered in documentation

### ISSUE THREAD

**Issue by calestyo** [python/cpython#107924]
# Bug report

There are some minor issues in the documentation for which I'm about to submit MRs:

1. There's some bad ordering around ``os.sendfile()``, it seems to make no sense that the `os.set_blocking()` function comes in-between the `os.sendfile()` function and its flags.
2. Also, the flags could possibly be joined into one section

https://github.com/python/cpython/blob/cc2cf85d03cf29994a707aae5cc9a349a4165b84/Doc/library/os.rst?plain=1#L1542-L1618

## Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the CPython issue tracker, and am confident this bug has not been reported before

### Linked PRs
* gh-107926
* gh-109099
* gh-109178

**Comment by AA-Turner** [comment]
@Eclips4 note that you can have a ['docs bug'](https://github.com/python/cpython/issues?q=label%3Adocs+label%3Atype-bug). The four ``type-`` labels act orthoganally to the "area" labels (docs, stdlib, interpreter-core, tests, extension-modules). See https://devguide.python.org/triage/labels/.

A

**Comment by AA-Turner** [comment]
@calestyo please could you split your PR into two parts, one for each distinct issue?

A

**Comment by calestyo** [comment]
@AA-Turner split out the stuff regarding `mknod()` in a separate issue and made this issue only about the ordering of `sendfile()` and its flags.

So I'd guess the MR for this one could be merged.
