### ISSUE TITLE
Improve error message for function calls with bad keyword arguments

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#107944]
Current traceback message:

```
>>> pow(bass=5, exp=2)
Traceback (most recent call last):
  ...
TypeError: pow() missing required argument 'base' (pos 1)
```

Proposed:

```
>>> pow(bass=5, exp=2)
Traceback (most recent call last):
  ...
TypeError: pow() Keyword argument 'bass' not defined. Did you mean "base"?
```

### Linked PRs
* gh-107969
* gh-114792

**Comment by pablogsal** [comment]
Ah, fantastic proposal! I will work on this this week

**Comment by pablogsal** [comment]
Will close after I add a what's new entry

**Comment by hugovk** [comment]
(@pablogsal Reminder for the what's new entry)

**Comment by pablogsal** [comment]
> (@pablogsal Reminder for the what's new entry)

Thanks for the ping. In general I collect all of this in one PR but I will do this separately so I don't forget
