### ISSUE TITLE
Stdev should return zero for a single datapoint

### ISSUE THREAD

**Issue by abatea** [python/cpython#107900]
# Feature or enhancement

I really want to call this a bug. Standard deviation is defined to be zero for a single input value, same as if all datapoints have the same value. However, python's implementation arbitrarily and incorrectly requires two datapoints.

# Pitch

Right now, `stdev` is the oddball raising StatisticsError while `mean` and friends will return for a single input. Fixing this allows the same iterable to be passed to these statistics functions, and it will either succeed for all or raise an error from all.

# Previous discussion

**Comment by sweeneyde** [comment]
There are two different functions here: `statistics.stdev` (to apply to samples), and `statistics.pstdev` (to apply to the entire population, if you somehow have access to that).

* `pstdev(arr)` is `sqrt(sum((x-mean)**2 for x in arr) / len(arr))`, while
* `stdev(arr)` is `sqrt(sum((x-mean)**2 for x in arr) / (len(arr) - 1))`.

This difference is known as [Bessel's correction](https://en.wikipedia.org/wiki/Bessel%27s_correction). This is mentioned in the [module docs](https://docs.python.org/3/library/statistics.html).

If you just have one sample of some random process, there is no information being conveyed about the dispersion of the random process. If you tried to divide by `len(arr) - 1`, you would divide by zero. Accordingly, no value can be produced.

On the other hand, if you can somehow guarantee that the random process *always* outputs the same value, *then* you can conclude that the standard deviation of the process is zero. This is what `pstdev` does.
