### ISSUE TITLE
isinstance discrepancies between 3.8 and 3.11

### ISSUE THREAD

**Issue by keren-orca** [python/cpython#108052]
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.8, 3.11

### Operating systems tested on:

macOS

### A clear and concise description of the bug:

```python
from typing import Any

print(isinstance(Any, type))
```

On 3.8 this prints `False`, while on 3.11 it prints `True`. I've went over the change logs of 3.9, 3.10, 3.11 but haven't found any indication of this change.

Can you please assist? 

Thanks.

**Comment by JelleZijlstra** [comment]
This is related to the Python 3.11 change to allow subclassing Any at runtime.

The exact runtime representation of Any is an implementation detail and should not be relied upon.
