### ISSUE TITLE
_Py_IsFinalizing has been removed, meaning C/C++ threads cannot avoid termination during shutdown

### ISSUE THREAD

**Issue by dgrisby** [python/cpython#108014]
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.13.0a0 (main, Jul 29 2023, 00:25:05) [GCC 13.1.1 20230614 (Red Hat 13.1.1-4)]

### A clear and concise description of the bug:

Threads that call PyEval_RestoreThread while the runtime is finalizing are terminated. The documented way to avoid this is to call _Py_IsFinalizing() to check. https://docs.python.org/3.13/c-api/init.html#c.PyEval_RestoreThread

_Py_IsFinalizing() has been removed from Python 3.13. Please provide a public API function that has the equivalent behavior, or some other way for a non-Python thread to safely attempt to call into Python code when the interpreter may be finalizing.

Rather than the calling code checking for finalization, an alternative solution would be to provide a variant of PyEval_RestoreThread that returns success or failure, so the calling code can know that it was unable to acquire the GIL, and react accordingly.

### Linked PRs
* gh-108032

**Comment by ericsnowcurrently** [comment]
FYI, there is some work to hang remaining threads rather than killing them: gh-105805.  I expect that would land in 3.13. 
 Presumably a `Py_IsFinalizing()` would still be helpful though.

**Comment by erlend-aasland** [comment]
I think it would make sense to also make `_Py_IsInterpreterFinalizing` public.

**Comment by vstinner** [comment]
Function added by commit https://github.com/python/cpython/commit/3ff5ef2ad3d89c3ccf4e07ac8fdd798267ae6c61.

**Comment by vstinner** [comment]
Function added to pythoncapi-compat by commit https://github.com/python/pythoncapi-compat/commit/1bb4e168b5931f88d9d49fe29d36cc0721ca14ff.

**Comment by vstinner** [comment]
I proposed adding PythonFinalizationError exception in PR gh-109809.

**Comment by vstinner** [comment]
Follow-up: @wjakob asked to add this new function to the limited C API version 3.13.
