### ISSUE TITLE
sqlite3: some code paths ignore exceptions

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#108083]
_Originally posted by @vstinner in https://github.com/python/cpython/pull/108015#discussion_r1297029863_:

> Ignoring the exception here is a bug.
>
> connection_finalize() clears any exception with PyErr_SetRaisedException(), but pysqlite_connection_close_impl() must not ignore silently error, since here we are talking about a raised Python exception! The function must report if an exception was raised. Then the caller is free to ignore it or not.
>
> I suggest to continue ignoring it in finalize, but then write a separated PR to *log* the "unraisable exception".

### Linked PRs
* gh-108084
* gh-108141

**Comment by serhiy-storchaka** [comment]
I have not found a test for failing `Connection.close()`. Would it be possible to write one? Maybe in a separate issue.

**Comment by erlend-aasland** [comment]
> I have not found a test for failing `Connection.close()`. Would it be possible to write one? Maybe in a separate issue.

It should be possible to force the implicit ROLLBACK in `.close()` to fail using some kind of database lock trick. Perhaps we could use a similar trick as in `test_ctx_mgr_rollback_if_commit_failed`.

**Comment by erlend-aasland** [comment]
Keeping this open until tests are added.

**Comment by serhiy-storchaka** [comment]
`sqlite3_close()` can be made failing in many ways, but `sqlite3_close_v2()` tries hard to return SQLITE_OK, so it may be not so easy to provoke a failure.

https://www.sqlite.org/c3ref/close.html

**Comment by erlend-aasland** [comment]
Yes, `sqlite3_close_v2()` returns `SQLITE_OK` if it is given a valid database handle.
`sqlite3_close` _can_ return an error, but it is hard to see how to be able to trigger that from the constructor; I'm not sure it is possible. We could just as well use `sqlite3_close_v2()` in the constructor.

**Comment by erlend-aasland** [comment]
> If there is no easy way to trigger an error at exit or to report it, I suggest to just give up and close the issue.

I don't think there is; the case is the constructor, between the `sqlite3_open_v2` call and the following four `goto error` jumps. I don't see how we can provoke an error there.

Closing this as resolved.

**Comment by vstinner** [comment]
Thanks, nice sqlite3 enhancement! Ignoring exceptions silently is never a good idea.
