### ISSUE TITLE
importlib.metadata documentation references the original module

### ISSUE THREAD

**Issue by romuald** [python/cpython#108013]
# Documentation

URL: https://docs.python.org/3/library/importlib.metadata.html

I'm not sure if this is an actual issue, but it seems that this documentation references the original module name (`importlib_metadata`), instead of the one that is actually present in the python library (`importlib.metadata`)

I'll try to come up with a PR since this seems to be a pretty small change

**Comment by hugovk** [comment]
I expect this is because it's a largely copy/paste of the backport library's docs (or the other way round).

Compare with:

* https://importlib-metadata.readthedocs.io/en/latest/using.html#using-importlib-metadata

cc @jaraco.

**Comment by romuald** [comment]
Actually this is fixed in _main_ by 4cd95dce (cf https://docs.python.org/3.13/library/importlib.metadata.html)
Maybe it could be backported?

**Comment by AA-Turner** [comment]
xref #102217

**Comment by jaraco** [comment]
Thanks AA-Turner for addressing this issue!
