### ISSUE TITLE
Adding the possibility of sequence operations to str.

### ISSUE THREAD

**Issue by CaixyPromise** [python/cpython#108008]
### Has this already been discussed elsewhere?

- [ ] I have already discussed this feature proposal on Discourse
- [x] This is a minor feature, which does not need previous discussion elsewhere

### Summary of proposal:

Adding the possibility of sequence operations to str.

### Pitch:

I think we need some simple upgrades to str. Such as, we should be allowed to manipulate our strings using the corresponding sequence, just like we can manipulate our strings and update them using subscripts, rather than truncating a str and then creating a new str splice. I look forward to seeing my suggestion, and if I can, I'll try to go ahead and come up with my solution.

```python
  s1 = 'I 1ove Python!!1'
  # If it's now, if we want to change the 1 in 1ove to L, Nomally, here's maybe what we need to do.
  new_str1 = s1[:2] + 'L' + s1[3:]
  print(new_str1)
  # The following code is not allowed.
  s1[2] = 'L' # TypeError: 'str' object does not support item assignment
  # So we want to realise our new possibilities.
  # Or, we can do some upgrading of the replace method. 
  # The replace method sounds pretty good.
  # For example, if the first parameter passed in by replace is an int, we can modify it based on the position passed in.
```

**Comment by AlexWaygood** [comment]
> This is a minor feature, which does not need previous discussion elsewhere

Any feature proposal that involves modifying a builtin type in Python is a major feature, that definitely requires previous discussion elsewhere before opening an issue on GitHub, I'm afraid :)

Changes like this have far-reaching consequences, so the bar is high for such proposals.

**Comment by terryjreedy** [comment]
Python requires that strings remain immutable so that they can be used as dictionary keys.  Some of the hits for https://stackoverflow.com/search?q=%5Bpython%5D+why+are+strings+immutable&s=975e694b-760c-4af3-91c3-80fbbb3d2c9b might help you understand better.
