### ISSUE TITLE
const char* to str changes the python string data

### ISSUE THREAD

**Issue by HYPER-00** [python/cpython#108046]
### Checklist

- [ ] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]

### A clear and concise description of the bug:

Im using Raknet network as a dll.

I called a C function that returns a struct with `char*` value as full packet content. I compared the value that received from python function with the value has been passed from C dll. **the two values are not equal.**
![image](https://github.com/python/cpython/assets/132200124/904e1f86-579b-48e1-ad66-d7b1ce871814)

**Summary: When returning `char *` from C/C++ dll to a Python script, the both values are not equal.**
**NOTE: Im using raknet network so the packet could be compressed + I tested the C function with C Api and ctypes**

**Comment by ericvsmith** [comment]
Please provide an example we can run. Ideally the example would just use the standard library, and no third party code.

**Comment by ronaldoussoren** [comment]
This issue does have enough information to reproduce the issue or to determine if there is a CPython issue at all.
