### ISSUE TITLE
Missing `__annotations__` from namespace parameter when using the `make_dataclass` function.

### ISSUE THREAD

**Issue by remimd** [python/cpython#108088]
### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

Python 3.11.4 (main, Jul 10 2023, 21:13:24) [Clang 14.0.3 (clang-1403.0.22.14.1)]

### A clear and concise description of the bug:

When a namespace is passed as a parameter to the `make_dataclass` function and namespace has `__annotations__` field, the field is completely ignored when the class is created. Current code replaces the namespace annotations with those generated with the fields. I think it would be wiser to make an update.

Bug is here : https://github.com/python/cpython/blob/2da67a5789a9247ae6611185bf786b697aa04fbe/Lib/dataclasses.py#L1509

**Comment by ericvsmith** [comment]
This is a feature request, and should be discussed first on discuss.python.org. In that discussion, you should point out why this is an improvement over the current behavior.

**Comment by remimd** [comment]
Ok, I thought it was a bug as I didn't see anything in the documentation that said namespace annotations were ignored. I don't think it's worth opening a topic for such a small improvement. 
So I'll close the issue.

**Comment by remimd** [comment]
It's not really a bug.

**Comment by ericvsmith** [comment]
I suppose it wouldn't hurt to mention this behavior in the documentation. Let me know you have suggested wording.
