### ISSUE TITLE
Document 'manager' and '_log' attrs of Logging

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#108198]
_Originally posted by @serhiy-storchaka in https://github.com/python/cpython/pull/108145#discussion_r1299794270_
            

### Linked PRs
* gh-114248

**Comment by erlend-aasland** [comment]
See gh-75638 for the original issue.

**Comment by erlend-aasland** [comment]
> Actually, 'manager' and '_log' attrs of LoggingAdapter are documented. But 'manager' and '_log' attrs of Logger are not.

Thanks for pointing that out.

**Comment by ebel** [comment]
I'll give this a go. First cpython issue fwiw.
