### ISSUE TITLE
September 1752 includes 11 days which shouldn't be present

### ISSUE THREAD

**Issue by FOSSBOSS** [python/cpython#108151]
### Checklist

- [x] I am confident this is a bug in CPython, not a bug in a third-party project
- [x] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

python3.10

### A clear and concise description of the bug:

This is a bug related to historical events in the Gregorian calendar:
in September 1752, from 9/2/1752 to 9/14/1752, 11 days were skipped to compensate for a time shift which had developed in the past millennium.
A discrepancy between a solar year and the Julian Calendar had grown by an additional day, so that the calendar used in England and its colonies was 11 days out-of-sync with the Gregorian Calendar used in Europe.
This was fixed by skipping 11 days in September 1752.
 
Example:

```py
import calendar
print(calendar.month(1752,9))
```

![y1752](https://github.com/python/cpython/assets/12141764/f128e6e7-cabb-4d63-8f03-ccb523fa3205)

should read:
![should](https://github.com/python/cpython/assets/12141764/8c1d846b-b390-4371-81df-1bc2eef501ae)

**Comment by mdickinson** [comment]
I believe this is intentional. From the [docs](https://docs.python.org/3/library/calendar.html):

> The functions and classes defined in this module use an idealized calendar, the current Gregorian calendar extended indefinitely in both directions. [...]

**Comment by mdickinson** [comment]
> This was fixed by skipping 11 days in September 1752.

Isn't this particular correction specific to Great Britain? As I understand it, the switch to the Gregorian calendar happened at different times in different countries. Getting the `calendar` module to do the "right thing" in all cases would be a rather messy business.

**Comment by FOSSBOSS** [comment]
Sure, the Gergorian calender is the one in question here. Applicable only to places utilizing the gregorian calendar, including Europe, and the Ameraicas, but not applicable to nations, or cultures utilizing other calendars.

**Comment by pochmann** [comment]
But the Gregorian calendar did have those days, no?

**Comment by ericvsmith** [comment]
I agree that the current behavior works as documented, and can't be changed. And as @mdickinson says, to get this "right" is very difficult. https://en.wikipedia.org/wiki/Adoption_of_the_Gregorian_calendar points out that different areas (I hesitate to say "countries") adopted it at different times.

I'm going to close this. I haven't check PyPI, but it seems like the best place for a module with the functionality described.
