### ISSUE TITLE
Time incorrect in Windows docker desktop container, if i use any version higher than 3.11.2(3.11.3 and 3.11.4)

### ISSUE THREAD

**Issue by bearsdj** [python/cpython#108169]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.11.2 (main, Mar 23 2023, 17:12:29) [GCC 10.2.1 20210110]

### A clear and concise description of the bug:

```python
# Add a code block here, if required
I used this docker file
FROM python:3.11.2-bullseye
# FROM python:latest
WORKDIR /app
COPY . /app

ENV TZ="Africa/Cairo"
# CMD ["python", "date.py"]

```
When i create a container with any python greater than 3.11.2(these ones - 3.11.3 and 3.11.4), when i go into the terminal ,and type date, the time is an hour forward. My scripts need to run at the correct local time and do not.
I hope this will help you.
I had to revert back to 3.11.2 to get the time correct.
![3112](https://github.com/python/cpython/assets/52139681/ae9c1ac3-f8ad-49f5-adc9-f74f80c4dd66)
![3114](https://github.com/python/cpython/assets/52139681/cbaa5eb6-2172-45cd-afe7-876e71f9172b)
![3113](https://github.com/python/cpython/assets/52139681/10f77d11-0553-4092-8c0c-85644aad5236)

regards
Michael

**Comment by bearsdj** [comment]
I have the latest windows Docker Desktop Version

**Comment by Eclips4** [comment]
Hello!
How it's related to CPython?

**Comment by bearsdj** [comment]
HI
I do not know if it is related.
I am new to this.
If you say is not i will close this.

**Comment by Eclips4** [comment]
> HI I do not know if it is related. I am new to this. If you say is not i will close this.

It's doesn't related to CPython repository, it's seems like a docker issue. Please, open issue in  docker repository.

**Comment by bearsdj** [comment]
i am not sure where to log it, can you assist?

**Comment by Eclips4** [comment]
> i am not sure where to log it, can you assist?

https://github.com/docker/for-win

**Comment by bearsdj** [comment]
Thank you
