### ISSUE TITLE
pprint splits string in a dictionary, formatting is broken

### ISSUE THREAD

**Issue by tsyg** [python/cpython#108292]
# Bug report

### Checklist

- [ ] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

### A clear and concise description of the bug:

```python
from pprint import pprint

d = {
    'paths': {
        '/mymethod': {
            'get': {
                'responses': {
                    200: {'description': 'Successful operation'},
                    400: {'description': 'Application error'}
                }
            }
        }
    }
}

pprint(d["paths"])
```

**Actual** result:
<pre>
{'/mymethod': {'get': {'responses': {200: {'description': 'Successful '
                                                          'operation'},
                                     400: {'description': 'Application '
                                                          'error'}}}}}

</pre>

NB: The description above is broken, causing invalid JSON

**Expected** result:
<pre>
{
    '/mymethod': {
        'get': {
            'responses': {
                200: {
                    'description': 'Successful operation'
                },
                400: {
                    'description': 'Application error'
                }
            }
        }
    }
}
</pre>

**Comment by hugovk** [comment]
`pprint.pprint` doesn't claim to output valid JSON:

https://docs.python.org/3/library/pprint.html

To output nicely-formatted JSON, use something like `json.dumps` with an `indent`:

```python
import json

d = {
    'paths': {
        '/mymethod': {
            'get': {
                'responses': {
                    200: {'description': 'Successful operation'},
                    400: {'description': 'Application error'}
                }
            }
        }
    }
}

print(json.dumps(d["paths"], indent=2))
```
```json
{
  "/mymethod": {
    "get": {
      "responses": {
        "200": {
          "description": "Successful operation"
        },
        "400": {
          "description": "Application error"
        }
      }
    }
  }
}
```


https://docs.python.org/3/library/json.html

**Comment by terryjreedy** [comment]
Please consider using https://discuss.python.org/c/users/7 to ask about possible bugs.
