### ISSUE TITLE
elif raises SyntaxError when preceded by a string statement

### ISSUE THREAD

**Issue by Stock-Owl** [python/cpython#108272]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

### A clear and concise description of the bug:

Minor bug
The following piece of code produces a syntax error. PyLance says it's an unexpected indetnation at the `elif` clause.

```python
# please note that this example has been taken out of context,
# but still poses the same problem as the implementation
from multiprocessing import Value

shared_break = Value('b', True)

print("started")

"""
IF the shared value is false, then set it to true while breaking
And wait until it is false again. then continue
"""
if shared_break.value == False:
    shared_break.value = True
    while True:
        if shared_break.value == False:
            break
        pass
                            
"""
IF the shared value is true, then wait for
an input from the user then continue
"""
elif shared_break.value == True:
    print(input("Waiting for input"))

print("ended")
```

Moving the multiline-comment (`IF shared values it true...`) seems to fix the problem:

```python
# please note that this example has been taken out of context,
# but still poses the same problem as the implementation
from multiprocessing import Value

shared_break = Value('b', True)

print("started")

"""
IF the shared value is false, then set it to true while breaking
And wait until it is false again. then continue
"""
if shared_break.value == False:
    shared_break.value = True
    while True:
        if shared_break.value == False:
            break
        pass
                            
elif shared_break.value == True:
    print(input("Waiting for input"))

print("ended")
"""
IF the shared value is true, then wait for
an input from the user then continue
"""
```

Also, the problem doesn't arise when multiple `#` comments are used:

```python
# please note that this example has been taken out of context,
# but still poses the same problem as the implementation
from multiprocessing import Value

shared_break = Value('b', True)

print("started")

"""
IF the shared value is false, then set it to true while breaking
And wait until it is false again. then continue
"""
if shared_break.value == False:
    shared_break.value = True
    while True:
        if shared_break.value == False:
            break
        pass
                            
# IF the shared value is true, then wait for
# an input from the user then continue
elif shared_break.value == True:
    print(input("Waiting for input"))

print("ended")
```
PEP8 says "Block comments generally apply to some (or all) code that follows them, and are indented to the same level as that code. Each line of a block comment starts with a # and a single space (unless it is indented text inside the comment)."

However the comment is indented at the same level as the following code.

[Same issue from 8 years ago](https://stackoverflow.com/questions/28212280/python-programming-multiline-comments-before-an-else-statement)

**Comment by ericvsmith** [comment]
Your code is basically:
```
if something:
    pass
'a string'
elif something_else:
    pass
```
You have an un-indented string at the same level as the `if`` so the if statement is ended. This is not a bug. The same thing is explained in the StackOverflow link you included.
