### ISSUE TITLE
Minor mistake in dataclasses documentation update

### ISSUE THREAD

**Issue by FrozenBob** [python/cpython#108267]
An [update](https://github.com/python/cpython/commit/0f23eda4b996dacd19dbe91bd47a30433bf236d2) to the dataclasses docs, intended to make magic method names link to the relevant data model documentation, accidentally changed a line that shouldn't have been changed.

The docs used to say

> There is a tiny performance penalty when using `frozen=True`: `__init__()` cannot use simple assignment to initialize fields, and must use `object.__setattr__()`.

The documentation update accidentally changed `object.__setattr__` to just `__setattr__` here, so now it reads

> There is a tiny performance penalty when using `frozen=True`: `__init__()` cannot use simple assignment to initialize fields, and must use `__setattr__()`.

This line was specifically meant to refer to `object.__setattr__`, the `__setattr__` method of the base `object` class, as simple attribute assignment would hit the frozen dataclass's `__setattr__` override.

This part of the documentation should be reverted. I think it should just take a 1-character change, simply removing a tilde.

### Linked PRs
* gh-108355
* gh-108357
* gh-108358
* gh-119082
* gh-119097
* gh-119098
* gh-119277
* gh-119279
* gh-119280

**Comment by ericvsmith** [comment]
I'm no sphinx expert. Would removing a tilde restore the output text to be `object.__setattr__`? That's what I think should be displayed.

**Comment by hugovk** [comment]
Yes, removing the tilde gives `object.__setattr__()`:

![image](https://github.com/python/cpython/assets/1324225/a7169711-478e-4ed8-90cd-2500f8bcf5cc)

@FrozenBob Thanks for the report, would you like to create a PR to fix this?

**Comment by ericvsmith** [comment]
> Yes, removing the tilde gives `object.__setattr__()`:

How on earth is someone supposed to know that? Seriously: where could I find out more info? I'd like to get better at this.

**Comment by AlexWaygood** [comment]
@ericvsmith there's some useful info on the markup in the devguide here (in particular, see the "quick reference" section at the top of the page): https://devguide.python.org/documentation/markup/

**Comment by AlexWaygood** [comment]
If we just remove the tilde, the link will take people to the entry for the `__setattr__` magic method in the data model documentation, rather than the docs for `object.__setattr__` itself (we have no docs for `object.__setattr__` itself). Maybe it would be better in this case to suppress the link entirely?

```rst
:meth:`!object.__setattr__`
```

That will render as `object.__setattr__()` in the HTML documentation, but won't add a link.

**Comment by FrozenBob** [comment]
Suppressing the link sounds reasonable to me.

**Comment by AlexWaygood** [comment]
Thanks @FrozenBob!

**Comment by FrozenBob** [comment]
This error appears to have been reintroduced during an [overhaul](https://github.com/python/cpython/pull/117005) of the `dataclasses` docs' links. Looks like it needs to be re-fixed.

**Comment by hauntsaninja** [comment]
Thank you for your vigilance!

**Comment by AlexWaygood** [comment]
Thanks @FrozenBob! We've fixed this on `main` (again!), and automerge has been scheduled for the backport PRs.

**Comment by FrozenBob** [comment]
I think you might need an extra blank line before the comment or something - it's rendering in the generated documentation.

**Comment by FrozenBob** [comment]
I see a confused emoji. In case it wasn't clear, this is what's showing up in the docs now:

> There is a tiny performance penalty when using `frozen=True`: [`__init__()`](https://docs.python.org/3/reference/datamodel.html#object.__init__) cannot use simple assignment to initialize fields, and must use `object.__setattr__()`. .. Make sure to not remove “object” from “object.\_\_setattr\_\_” in the above markup

The part starting with the ".." looks like it was supposed to be a reStructuredText comment, but it's showing up in the actual documentation. I think this may be because it needs a blank line above it.

**Comment by AlexWaygood** [comment]
I understood the problem — sorry for the ambiguous reaction emoji I applied! I suppose I intended to convey that I was frustrated at myself for not checking the docs preview before merging, but sadly there's no reaction emoji for that exact sentiment ;-)
