### ISSUE TITLE
Add --disable-gil option to configure

### ISSUE THREAD

**Issue by colesbury** [python/cpython#108223]
# Feature or enhancement

@itamaro is working on setting up additional buildbots for PEP 703 builds. To support this, we'll add an optional `--disable-gil` flag to the configure. For now, this flag won't do anything other than define the `Py_NOGIL` macro, but once the buildbots are setup, any future code behind this flag will be tested in the CI.

### Linked PRs
* gh-108227
* gh-108236
* gh-108238
* gh-108239
* gh-111060
* gh-112780

**Comment by vstinner** [comment]
@colesbury: Would you mind to document the new option in https://docs.python.org/dev/using/configure.html documentation? You will need a ``.. versionadded:: 3.13``.

**Comment by terryjreedy** [comment]
Will no-gil initially be *nix only or will no-gil builds for Windows be possible?

**Comment by itamaro** [comment]
> Will no-gil initially be *nix only or will no-gil builds for Windows be possible?

ideally we should have it for all platforms as early as possible
