### ISSUE TITLE
[C API] Add PyDict_ContainsString() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108314]
# Feature or enhancement

### Has this already been discussed elsewhere?

No response given

### Proposal:

Most, if not all, PyDict C APIs have a "String" flavor where the key argument is expressed as a UTF-8 encoded bytes string. But the ``PyDict_Contains()`` API is missing such variant.

I suppose that it was not proposed before since ``PyDict_GetItemString(dict, key) != NULL`` can already be used. My problem is that ``PyDict_GetItemString()`` **ignores errors**: I would like to report errors.

The newly added ``PyDict_GetItemStringRef()`` can be used to check if a dictionary has a key and report errors, but it requires calling ``Py_DECREF()`` which is not convenient. Example:

```
PyObject *value;
if (PyDict_GetItemStringRef(dict, key, &value) < 0) {
    // ... handle error ...
}
int has_value = (value != NULL);
Py_XDECREF(value);
// ... use has_value ...
```

I would like to be able to replace this code with:

```
int has_value = PyDict_ContainsString(dict, key);
if (has_value < 0) {    
    // ... handle error ...
}
// ... use has_value ...
```

There is no need to INCREF/DECREF just to check if a dictionary has a key.

### Linked PRs
* gh-108323
* gh-108448
* gh-108489

**Comment by vstinner** [comment]
There is already an abstract PyMapping_HasKeyString() function. Sadly, on error, this function clears the exception and returns 0 :-(

**Comment by corona10** [comment]
> Has this already been discussed elsewhere?

FYI, there was the discussion with adding this API.
https://github.com/capi-workgroup/problems/issues/23

**Comment by encukou** [comment]
And here: https://github.com/python/cpython/issues/100100

**Comment by vstinner** [comment]
I added the function to pythoncapi-compat: https://github.com/python/pythoncapi-compat/commit/4734c8ec3a4111d1fb6ded87db135ed3345d1867
