### ISSUE TITLE
Move test files into test subdirectories

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108303]
# Feature or enhancement

### Proposal:

The Python test suite has around 166 files and sub-directories where the name is not clearly associated to a test. For example, it's not obvious to me which test uses ``talos-2019-0758.pem`` or ``coding20731.py``.

When possible, I propose to move these files into sub-directories related to their test. Example:

* create ``Lib/test/test_module/`` sub-directory
* move ``Lib/test/test_module.py`` to ``Lib/test/test_module/__init__.py``
* move ``good_getattr.py`` and ``bad_getattr*.py`` scripts to ``Lib/test/test_module/``

Well, I created PR #108293 for this specific example.

### Linked PRs
* gh-108305
* gh-108325
* gh-108328
* gh-108336
* gh-108354
* gh-108978
* gh-108979
* gh-109265
* gh-109314
* gh-109368
* gh-109489
* gh-109512
* gh-109513
* gh-109607
* gh-109670
* gh-109671
* gh-109672
* gh-109673
* gh-109674
* gh-109675
* gh-109677
* gh-109678
* gh-109679
* gh-109680
* gh-109682
* gh-109683
* gh-109686
* gh-109724
* gh-110646
* gh-110732
* gh-111543
* gh-111549
* gh-111825
* gh-111859
* gh-111860
* gh-111879
* gh-111880
* gh-111882
* gh-111883
* gh-111891
* gh-111892
* gh-111899
* gh-111945
* gh-111946
* gh-112108
* gh-112109
* gh-112110
* gh-112114
* gh-112976
* gh-112977
* gh-114254
* gh-114313
* gh-114343
* gh-114344
* gh-114356
* gh-114368
* gh-114372
* gh-114427
* gh-114433
* gh-114488
* gh-114506
* gh-114687
* gh-115501
* gh-115502
* gh-115625
* gh-115626
* gh-130540

**Comment by vstinner** [comment]
The alternative is to have a "data" directory, so a different directory name:

* audiodata/
* decimaltestdata/
* dtracedata/
* subprocessdata/
* tkinterdata/
* typinganndata/
* xmltestdata/
* ziptestdata/

**Comment by terryjreedy** [comment]
I have also noticed and wondered about the melange of misc files.  I like packaging the test code and data together in one directory, as in your 'module' example, especially given that we already have test_xyz directories.

**Comment by vstinner** [comment]
I created PR #108299 for test_crashers.

**Comment by serhiy-storchaka** [comment]
What with data files used in several different tests?

**Comment by vstinner** [comment]
> What with data files used in several different tests?

For this case, I suggest to keep the current trend of having a "data/" directory, such as ``audiodata/``. I don't think that duplicating files to "isolate" tests is worth it.

The problem with these "data" directories is that when a test file is no longer needed, it's more likely to  be forgotten.

**Comment by vstinner** [comment]
I made a test after PR #108978 (Create Lib/test/test_dataclasses/ directory): if I change ``Lib/test/test_dataclasses/__init__.py`` in the main branch, ``git cherry-pick -x`` is able to backport the change to the 3.12 branch smoothly (automated, no merge conflict). Nice!

**Comment by hugovk** [comment]
Python 3.11 gets bug fixes until April 2024 and security fixes until October 2027.

Only one of these PRs was backported to 3.11.

The other eight have not been, and the two opens ones aren't labelled for backport. 

This means 

* future bug fixes will be harder to maintain, 
* things are out of sync, 
* it's harder to reason what belongs where, 
* and it's more prone to merge conflicts, especially when moving files. 


Shall we backport the others?

**Comment by vstinner** [comment]
> future bug fixes will be harder to maintain

I would prefer to not backport these changes to limit changes in stable branches. Which change was backported?

See my previous comment, git cherry-pick understands that files are renamed/moved, and it goes smoothly.

I don't have a strong opinion on this topic.

@ambv: recently, you asked me to backport other test refactoring changes to stable branches to ease maintenance. What's your opinion on this issue?

**Comment by ambv** [comment]
Why should we limit changes to test files in stable branches? AFAICT it doesn't hurt maintenance but it does help with conflicts. Git follows some renames but not others, I wouldn't trust it to consistently figure out what you refactored.

+1 to backporting testing changes as far as they will go.

**Comment by vstinner** [comment]
Ok, let's backport all of these changes in this case.

**Comment by serhiy-storchaka** [comment]
I almost always backport tests and doc changes as far as it is reasonably possible. In the Mercurial era it included branches in security-only fix mode.

**Comment by vstinner** [comment]
> Why should we limit changes to test files in stable branches?

In general, "stable" for me means "does not change". The fewer changes we make, the lower risk of regression there is.

But people want to backport all doc changes, and apparently also all test changes. I'm fine with it, if it's something like a guideline. Maybe it should be put in the devguide, so i would stop ranting each time 🤣

These days, what makes backporting more complicated is that 3.12 is blocked, the release manager has to manually go through all backports. It makes it harder to a have a queue of pending inter-dependent backports.

**Comment by ambv** [comment]
Yes, we should put it in the devguide that test and doc changes should be backported to bugfix branches. Docs have immediate value to users and tests help with maintenance. Neither cause user-visible regressions.

**Comment by vstinner** [comment]
So. I created many backport PRs. I hope that it will not be a nightmare to merge them in the "right order"!

Backporting PR #109513 "badsyntax_pep3120.py" needs to wait until PR #109314 is backported to 3.11 (PR #109678) and 3.12 (PR #109677).

Merging PR #109512 "mathdata" broke all CIs since the PR wasn't updated after PR #109548 got merged, oops. I wrote PR #109686 to fix it. I didn't backport it yet until things are more stable.

**Comment by vstinner** [comment]
@ambv:
> Yes, we should put it in the devguide that test and doc changes should be backported to bugfix branches. Docs have immediate value to users and tests help with maintenance. Neither cause user-visible regressions.

I created https://github.com/python/devguide/issues/1168 to not forget :-)

**Comment by vstinner** [comment]
I close the issue. While it's not 100% done, remaining files can reuse this closed issue, or another issue can be created. This issue already has a long list of pull requests and a long history.

Thanks to everybody who helped cleaning Lib/test/, reviewers, and especially @sobolevn who wrote many changes!
