### ISSUE TITLE
<br> not accepted in Expat

### ISSUE THREAD

**Issue by Harvey13** [python/cpython#108302]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [ ] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]

### A clear and concise description of the bug:

Hello
I test this code on Google Colab 
```
from xml.dom import minidom
http_string_ok = "<div>Hello <br />Welcome to <br />the blog<br /></div>"
http_string_bad = "<div>Hello <br>Welcome to <br>the blog<br></div>"
dom = minidom.parseString(http_string_ok)
dom = minidom.parseString(http_string_bad)
```
The second line throws an error **ExpatError: mismatched tag: line 1, column 44**
but **< br >** is valid ...

**Comment by zware** [comment]
`<br>` is not actually valid XML: it's an opening tag without a close, which is required in XML.  It should be the self-closing `<br />` instead.

**Comment by Harvey13** [comment]
@zware Hello , refering to `https://html.spec.whatwg.org/#the-br-element` < br > is valid ...

**Comment by zware** [comment]
HTML is closely related to XML, but to parse HTML correctly you will need an HTML parser, not an XML parser.

**Comment by terryjreedy** [comment]
Try the `html.parser` module.
