### ISSUE TITLE
tkinter file dialog box run through Plotly Dash/Google Chrome

### ISSUE THREAD

**Issue by matt-sd-watson** [python/cpython#108376]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.9.16 (main, Mar  8 2023, 14:00:05)  [GCC 11.2.0]

### A clear and concise description of the bug:

I am producing a `tkinter` file dialog box through a Plotly dash app callback used in Google Chrome. When the file dialog box shows up, it looks ridiculously small, similar to the screenshot below:

![5S2iJ](https://github.com/python/cpython/assets/40243147/d0abbd23-4951-468c-bb7f-691167926c8e)

I have not been able to find any documentation where the default size of the dialog box can be increased.

**Comment by chrstphrchvz** [comment]
The reporter does not specify which Linux distribution/desktop environment they are using, but from the screenshot, it looks like GNOME on recent Ubuntu, with >100% scaling set.

It is known that Tcl/Tk 8.6 has limited usability on hi-DPI devices. To my knowledge, there is not much Tkinter can do to improve this (although IDLE does try to adjust a few things). Tcl/Tk 8.7 plans to improve DPI scaling considerably, but it may still be a while before it is released.

Until then, I would probably instead try GTK (e.g. using Zenity dialogs) or Qt or some other toolkit which already works well on hi-DPI.

**Comment by chrstphrchvz** [comment]
> I have not been able to find any documentation where the default size of the dialog box can be increased.

The Tkinter file dialogs are provided by Tcl/Tk, and most aspects of their appearance (such as the sizes of fonts and UI elements) are seemingly not meant to be customizable. I am not sure they can be customized without relying on knowledge of their implementation details.

**Comment by serhiy-storchaka** [comment]
Closed as not a Tkinter issue.
