### ISSUE TITLE
Split long running test suites up into smaller sub suites to reduce our regrtest long tail on multi-core systems.

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108388]
The slowest tests of the Python test suite are:

* test_concurrent_futures
* test_multiprocessing_spawn
* test_peg_generator
* test_tools.test_freeze tests

They each tend take multiple minutes to run.  The bulk of our others take <10 seconds.  They occupy a lot of wall time as a long tail in a normal make test or regrtest run on a typical parallel run multi-core systems.

This bug originally proposed to skip them unless the "cpu" resource is enabled (it's disabled by default). That was deemed appropriate for `test_peg_generator` and `test_tools.test_freeze` which are either not platform specific or rarely needed in CI.  (PR #108386) - This PR reduced the total test duration between **3** and **5** minutes.

### Linked PRs
* gh-108389
* gh-108391
* gh-108393
* gh-108396
* gh-108397
* gh-108401
* gh-108442
* gh-108443
* gh-109688
* gh-109704

**Comment by terryjreedy** [comment]
I have previously requested that the slowest tests not restricted to  -cpu be split into pieces that can run in parallel when -j is used.  Thank you for doing this.

**Comment by hugovk** [comment]
> The slowest tests of the Python test suite are:
> 
> * test_concurrent_futures
> * test_multiprocessing_spawn
> * test_peg_generator
> * test_tools.test_freeze tests

How long do they usually take?

**Comment by gpshead** [comment]
I edited the title and updated the initial comment since this and the related PRs shifted from the original opening statement. :)

**Comment by sobolevn** [comment]
I experience new failures of `test_concurrent_futures` on Windows on my unrelated PR: https://github.com/python/cpython/actions/runs/5972558288/job/16203298171?pr=108456

Failing tests:
```
     test.test_concurrent_futures.test_deadlock
     test.test_concurrent_futures.test_shutdown
```

**Comment by vstinner** [comment]
> I experience new failures of test_concurrent_futures on Windows on my unrelated PR

Sadly, the issue is known for at least one month: see issue #107219.

Logs:

```
  File "D:\a\cpython\cpython\Lib\test\test_concurrent_futures\test_deadlock.py", line 236 in test_crash_big_data
```

It's this test which hangs sometimes on Windows.

**Comment by vstinner** [comment]
This feature has been implemented in the main branch, and backported to the 3.12 branch. I don't think that it's worth it to backport it to the 3.11 branch.

I splitted these test packages:

* test_concurrent_futures
* test_multiprocessing_fork
* test_multiprocessing_forkserver
* test.test_multiprocessing_spawn

Example:

```
$ ./python -m test test_concurrent_futures --list-tests
test_concurrent_futures.test_as_completed
test_concurrent_futures.test_deadlock
test_concurrent_futures.test_future
test_concurrent_futures.test_init
test_concurrent_futures.test_process_pool
test_concurrent_futures.test_shutdown
test_concurrent_futures.test_thread_pool
test_concurrent_futures.test_wait
```

I close my issue.
