### ISSUE TITLE
Add platform triplets for x86_64 GNU/Hurd

### ISSUE THREAD

**Issue by sthibaul** [python/cpython#108447]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Output from running 'python -VV' on the command line:

N/A

### A clear and concise description of the bug:

Building on x86_64 GNU/Hurd fails with 

```
Misc/platform_triplet.c:260 error: #error unknown platform triplet
```

Trivial patch posted to https://github.com/python/cpython/pull/108045

### Linked PRs
* gh-108045
* gh-111987
* gh-111988

**Comment by erlend-aasland** [comment]
Restyled as a feature.
