### ISSUE TITLE
`sys.monitoring.set_local_events()` allows "non local" events like `RAISE`, in contradiction to PEP 669.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#108470]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.12

### A clear and concise description of the bug:

`sys.monitoring.set_local_events(TOOL, code, sys.monitoring.events.RAISE)` should raise an exception, but succeeds.

This was discovered when investigating https://github.com/python/cpython/issues/108390.
Fixed by https://github.com/python/cpython/pull/108420

**Comment by Yhg1s** [comment]
rc2 is scheduled for today. How close is this to getting fixed? I'll probably push the release to tomorrow regardless, but let me know if it needs more time.

**Comment by markshannon** [comment]
Fixed in main
https://github.com/python/cpython/pull/108899 is the backport to 3.12
