### ISSUE TITLE
Add option to iterate over dataclass fields

### ISSUE THREAD

**Issue by nadav1603** [python/cpython#108450]
# Feature or enhancement

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Proposal:

This is something I have been needing for a while, and I've seen more than a few questions about it.
I think the implementation is going to be quite simple, and I think it could make ours life a bit better.

Example:
```python
from datacalsses import dataclass

@dataclass(iterable=True)
class MyDataclass:
    a: int
    b: str
    c: bool

d = MyDataclass(1, "2", False)
for field_name, field_value in d:
    ...
```

**Comment by ericvsmith** [comment]
Or write a wrapper:
``` pycon
>>> import dataclasses
>>> def iterate_items(d):
...     for field in dataclasses.fields(d):
...         yield field.name, getattr(d, field.name)
...
>>> list(iterate_items(d))
[('a', 1), ('b', '2'), ('c', False)]
```
And `iterate_keys` and `iterate_values`, if you want.

If we added `iterable=True` (which I'm generally opposed to), it's not clear to me if we'd want to return keys, values, or items (to use `dict` terminology).

Does attrs provide any similar functionality?

**Comment by ericvsmith** [comment]
Since this is an enhancement request, it should be discussed on discuss.python.org first. @nadav1603 : I suggest you open a discussion over there (in ideas) if you want to gather support for the proposal. I'm going to close this, but it can be re-opened if the decision there is to move forward.
