### ISSUE TITLE
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?

### ISSUE THREAD

**Issue by BarkingDeer** [python/cpython#108541]
# Bug report

### Checklist

- [ ] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### A clear and concise description of the bug:

I suppose this is a bug in Python 3.12. The problem occurs when I try to install  a package (pytest) or when I activate the AI assistant in PyCharm. The problem is resolved when I accept the suggestion.

```pytb
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\packaging_tool.py", line 108, in main
    do_list()
  File "C:\Program Files\JetBrains\PyCharm 2022.1.3\plugins\python\helpers\packaging_tool.py", line 45, in do_list
    import pkg_resources
  File "D:\Python\Docs\euler\Lib\site-packages\pkg_resources\__init__.py", line 2191, in <module>
    register_finder(pkgutil.ImpImporter, find_on_path)
                    ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
```

**Comment by Eclips4** [comment]
Hello!
This bug doesn't related to CPython. Seems that your plugin uses old version of `setuptools`. Try to update your plugin, and update `setuptools` to 68.0.0+ version in your virtual environment.

**Comment by BarkingDeer** [comment]
Many thanks. Sorry for the reporting of a false bug.
