### ISSUE TITLE
Add explicit test for sqlite3.Row.keys()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#108558]
### Has this already been discussed elsewhere?

No response given

### Proposal:

Seems, there are no tests for `sqlite3.Row.keys()`.

### Linked PRs
* gh-108578
* gh-108615
* gh-108616
* gh-108628

**Comment by EddInSverige** [comment]
Hey @erlend-aasland / @serhiy-storchaka - I'm a test engineer and would love to contribute to Python. Been using it for 9+ years. Any chance of taking a look at this issue?

**Comment by erlend-aasland** [comment]
Great, have a go at it! :) I'll get a ping when you create the PR.

**Comment by erlend-aasland** [comment]
> Edit: I guess master is not what we merge into lol, what's the working branch to merge into? Pulled master for this work

The development branch is called `main` (currently 3.13 development). Apart from that, we've got release branches (`3.12`, `3.11`, etc.). You're free to choose your own branching scheme when developing. I used to name bug/feature branches using the issue number, but nowadays I group them using a simple naming scheme instead: `sqlite/*` for sqlite3 stuff, `clinic/*` for Argument Clinic stuff, `docs/*` for random documentation stuff, and for everything else, I just make up a name there and then :)

**Comment by EddInSverige** [comment]
Okay great! So I guess my PR is all good then? 

If so I'll dig out some more test issues and have a go at them :)

**Comment by erlend-aasland** [comment]
> Okay great! So I guess my PR is all good then?

Indeed it is :)

> If so I'll dig out some more test issues and have a go at them :)

Great!


BTW; `test_sqlite_row_as_dict` implicitly already tested `keys()`, so there is no increase in test coverage post this change.

**Comment by EddInSverige** [comment]
> BTW; `test_sqlite_row_as_dict` implicitly already tested `keys()`, so there is no increase in test coverage post this change.

I added a second PR to cover the edge case that the SQL query didn't return any results and a few other behaviours
