### ISSUE TITLE
PDB: Vagueness in comments and names, and Grammtical Mistakes in Information.

### ISSUE THREAD

**Issue by SatinWukerORIG** [python/cpython#108554]
# Feature or enhancement

### Has this already been discussed elsewhere?

No response given

### Proposal:

```python
def find_function(funcname, filename):
    cre = re.compile(r'def\s+%s\s*[(]' % re.escape(funcname))
    try:
        fp = tokenize.open(filename)
    except OSError:
        return None
    # consumer of this info expects the first line to be 1
    with fp:
        for lineno, line in enumerate(fp, start=1):
            if cre.match(line):
                return funcname, filename, lineno
    return None
```
In this piece of code, there are three improperly-named variables that caused a bit of confusion when I was reading: `fp`, which stands for file_pointer, 'cre', which stands for compiled regular expression, and lineno, meaning line number.
There were also some grammatical mistakes in the comments and the introduction "paragraph" at the beginning of the file.
PDB is one of the major standard lib in Python, I hope people who read this code will not get confused like me.
Thank you guys so much for making Python a great language so far.

### Linked PRs
* gh-108555

**Comment by AlexWaygood** [comment]
Thanks for the suggestion! Unfortunately, CPython generally doesn't accept PRs making purely stylistic to its code. If we did, there would be no stopping the tide of PRs attempting to clean up decades-old code, and the churn would be immense :)

Closing for these reasons, and the reasons explained on the PR thread

**Comment by SatinWukerORIG** [comment]
> Thanks for the suggestion! Unfortunately, CPython generally doesn't accept PRs making purely stylistic to its code. If we did, there would be no stopping the tide of PRs attempting to clean up decades-old code, and the churn would be immense :)
> 
> Closing for these reasons, and the reasons explained on the PR thread

My apology here.
