### ISSUE TITLE
3.11.5 test_httpservers fails on unhandled DeprecationWarning ("invalid escape sequence '\\?'")

### ISSUE THREAD

**Issue by dvzrv** [python/cpython#108569]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]

### A clear and concise description of the bug:

Hi! When attempting to upgrade the python package for Arch Linux to 3.11.5 I ran into the following test issue:

```
[..]
test.test_httpservers
FAIL

======================================================================
FAIL: test_all (test.test___all__.AllTest.test_all)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python/src/Python-3.11.5/Lib/test/test___all__.py", line 129, in test_all
    self.check_all(modname)
  File "/build/python/src/Python-3.11.5/Lib/test/test___all__.py", line 43, in check_all
    with warnings_helper.check_warnings(
  File "/build/python/src/Python-3.11.5/Lib/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/build/python/src/Python-3.11.5/Lib/test/support/warnings_helper.py", line 185, in _filterwarnings
    raise AssertionError("unhandled warning %s" % reraise[0])
AssertionError: unhandled warning {message : DeprecationWarning("invalid escape sequence '\\?'"), category : 'DeprecationWarning', filename : '/build/python/src/Python-3.11.5/Lib/test/test_httpservers.py', lineno : 445, line : None}

----------------------------------------------------------------------
Ran 1 test in 0.621s

FAILED (failures=1)
test test___all__ failed
0:00:05 load avg: 3.34 [ 12/432/1] test___future__ -- test___all__ failed (1 failure)
test_attributes (test.test___future__.FutureTest.test_attributes) ... ok
test_names (test.test___future__.FutureTest.test_names) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.000s
[..]
```

Full build and check logs:
[python-3.11.5-1-x86_64-build.log](https://github.com/python/cpython/files/12455747/python-3.11.5-1-x86_64-build.log)
[python-3.11.5-1-x86_64-check.log](https://github.com/python/cpython/files/12455746/python-3.11.5-1-x86_64-check.log)

Build script for the package: https://gitlab.archlinux.org/archlinux/packaging/packages/python/-/blob/main/PKGBUILD

cc @felixonmars

**Comment by hugovk** [comment]
The f-string was turned into a raw f-string for `main` and 3.12, but not 3.11: 

* https://github.com/python/cpython/issues/105821
* https://github.com/python/cpython/pull/105822
* https://github.com/python/cpython/pull/105824

@pablogsal @AlexWaygood Shall we backport it to 3.11?

**Comment by AlexWaygood** [comment]
> @pablogsal @AlexWaygood Shall we backport it to 3.11?

That makes sense to me; the change is very low-risk 👍

@dvzrv, are you running your tests with `-W`/`-Werror`? (I'm curious why we're not seeing the same CI failures in CI over at CPython!)

**Comment by dvzrv** [comment]
> @dvzrv, are you running your tests with `-W`/`-Werror`? (I'm curious why we're not seeing the same test failures in CI over at CPython!)

Not that I am aware of (definitely not explicitly).

Rebuilding with the patch applied now to see where this leads and will report back. Thanks for the super quick responses here!

**Comment by dvzrv** [comment]
Building with https://github.com/python/cpython/pull/108576 applied on top of 3.11.5 fixes the issue for us. Thank you! :)
