### ISSUE TITLE
Duplicate entry in 3.11.5 changelog - pickle module

### ISSUE THREAD

**Issue by salty-horse** [python/cpython#108542]
# Documentation

The [3.11.5 changelog](https://docs.python.org/3/whatsnew/changelog.html#python-3-11-5-final) has an entry that appears twice:
> [gh-105375](https://github.com/python/cpython/issues/105375): Fix bugs in [pickle](https://docs.python.org/3/library/pickle.html#module-pickle) where exceptions could be overwritten.
> [gh-105497](https://github.com/python/cpython/issues/105497): Fix flag inversion when alias/mask members exist.
> [gh-105375](https://github.com/python/cpython/issues/105375): Fix bugs in [pickle](https://docs.python.org/3/library/pickle.html#module-pickle) where exceptions could be overwritten.

The relevant files with identical contents:
[Misc/NEWS.d/next/Library/2023-06-08-08-58-36.gh-issue-105375.bTcqS9.rst](https://github.com/python/cpython/blob/HEAD/Misc/NEWS.d/next/Library/2023-06-08-08-58-36.gh-issue-105375.bTcqS9.rst)
[Misc/NEWS.d/next/Library/2023-06-09-21-04-39.gh-issue-105375.bTcqS9.rst](https://github.com/python/cpython/blob/HEAD/Misc/NEWS.d/next/Library/2023-06-09-21-04-39.gh-issue-105375.bTcqS9.rst)

### Linked PRs
* gh-108543
* gh-108544
* gh-108545

**Comment by Eclips4** [comment]
Yeah, [Misc/NEWS.d/next/Library/2023-06-09-21-04-39.gh-issue-105375.bTcqS9.rst](https://github.com/python/cpython/blob/HEAD/Misc/NEWS.d/next/Library/2023-06-09-21-04-39.gh-issue-105375.bTcqS9.rst) has incorrect information. There's should be "Fix bugs in errno where exceptions could be overwritten."

Would you like to send a PR?

**Comment by erlend-aasland** [comment]
FTR, the NEWS entry comes from eede1d2f48b4fe7f7918952d9ebeb744b58668c1, PR gh-105590, issue gh-105375. The NEWS entry is present in `main`, 3.12, and 3.11.
