### ISSUE TITLE
windows: pythonw cannot spawn multiprocessing.Process

### ISSUE THREAD

**Issue by sam-s** [python/cpython#108587]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

Python 3.11.4 | packaged by Anaconda, Inc. | (main, Jul  5 2023, 13:38:37) [MSC v.1916 64 bit (AMD64 )]

### A clear and concise description of the bug:

The following [script](https://docs.python.org/3/library/multiprocessing.html) runs as expected under `python.exe` but **not** under `pythonw.exe`:
```python
from multiprocessing import Process
import os

def info(title):
    with open(f"{__name__}-{os.getppid()}-{os.getpid()}","a") as fd:
        fd.write(f"{title}\n")

class P(Process):
    def __init__(self, x):
        self.x = x
        super().__init__(name=str(os.getpid()))
        info(f"init {self}")
        self.start()
    def run(self):
        info(f"running {self}")

if __name__ == '__main__':
    info('main line')
    pl = [P(x) for x in range(2)]
    info(f"started {pl}")
    for p in pl:
        p.join()
        info(f"joined {p}")
```

# `python.exe`

2 sub-processes are started and 3 files are created, exactly as expected/documented:

### `==> __main__-36968-52232 <==`
```
main line
init <P name='52232' parent=52232 initial>
init <P name='52232' parent=52232 initial>
started [<P name='52232' pid=21116 parent=52232 started>, <P name='52232' pid=43464 parent=52232 started>]
joined <P name='52232' pid=21116 parent=52232 stopped exitcode=0>
joined <P name='52232' pid=43464 parent=52232 stopped exitcode=0>
```
### `==> __mp_main__-52232-21116 <==`
```
running <P name='52232' parent=52232 started>
```
###  `==> __mp_main__-52232-43464 <==`
```
running <P name='52232' parent=52232 started>
```

# `pythonw.exe`

No subprocesses are started and only 1 file is created:

###  `__main__-20572-33044`
```
main line
init <P name='33044' parent=33044 initial>
init <P name='33044' parent=33044 initial>
started [<P name='33044' pid=35276 parent=33044 started>, <P name='33044' pid=41872 parent=33044 started>]
joined <P name='33044' pid=35276 parent=33044 stopped exitcode=1>
joined <P name='33044' pid=41872 parent=33044 stopped exitcode=1>
```

**Comment by zooba** [comment]
I can't reproduce this, we're going to need some more information about your setup.

Since you're an Anaconda user, you should report it to them first. They're responsible for supporting their own builds. If they (or you) find that it also occurs in unmodified CPython builds, we can investigate further.

**Comment by terryjreedy** [comment]
Ran fine for me with installed 3.11.4, 3.11.5, and 3.12.0rc1.

**Comment by sam-s** [comment]
indeed, I switched to the normal python 3.11 and the problem is now gone.
thank you, sorry about the noise
