### ISSUE TITLE
test_import leaks references

### ISSUE THREAD

**Issue by carljm** [python/cpython#108696]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.13.0a0 (bisect/good-edb569e8e1f469ac5ce629cc647ab169d895de41-1-gfeb9a49c9c-dirty:feb9a49) [GCC 8.5.0 20210514 (Red Hat 8.5.0-20)]

### A clear and concise description of the bug:

Reproduce with `./python -m test -R: -v test_import`.

### Linked PRs
* gh-108698

**Comment by carljm** [comment]
Bisection shows this leak was introduced by https://github.com/python/cpython/pull/104186

cc @FFY00

**Comment by sunmy2019** [comment]
Checks passed
