### ISSUE TITLE
Remove `TIER_ONE` and `TIER_TWO` from bytecodes.c

### ISSUE THREAD

**Issue by markshannon** [python/cpython#108614]
The `TIER_ONE` and `TIER_TWO` macros cause a few problems:

Their presence in the bytecode definitions means that anyone maintaining the interpreter or adding new instructions needs to understand the internals of the multiple execution layers and how they differ.
This makes the entry barrier for contribution, which is already high for these components, even higher.

It makes reasoning about the correctness of optimizations harder.

It prevents the addition of new execution tiers, or changing the design of the current tiers much harder.

We can remove the `TIER_ONE` and `TIER_TWO` macros by making modifications to internal execution engine state explicit, without describing how that state is implemented.
For example, rather than modifying `next_instr` in the tier 1 interpreter, we can use `JUMP_BY` or `SAVE_IP` macros.
See https://github.com/faster-cpython/ideas/issues/618

### Linked PRs
* gh-108630
* gh-108685
* gh-108725
* gh-109132
* gh-109247

**Comment by hugovk** [comment]
Looks like everything is done for this one. Thanks!
