### ISSUE TITLE
Datetime wrong format (error in zero padding day) doesn't raise exception

### ISSUE THREAD

**Issue by yagohdezg** [python/cpython#108619]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux, Windows

### A clear and concise description of the bug:

```python
from datetime import datetime
datetime.strptime("2023013", "%Y%m%d")
```
The above piece of code should throw and exception, but it doesn't and the resulting date is "2023-01-03".
Using the "%d" formatter should only allow zero-padding days to be allowed, the date is ambiguous and should throw an Exception.

**Comment by tirkarthi** [comment]
Similar report : https://github.com/python/cpython/issues/79084

**Comment by ericvsmith** [comment]
@yagohdezg: Could you point to the documentation that says that's how it should work? From a quick read of #79084 it seems that leading zeros aren't required in strptime.

**Comment by yagohdezg** [comment]
I was referencing this piece of documentation: https://docs.python.org/3/library/datetime.html#format-codes that said dates must have zero-padding (exact phrasing: **%d Day of the month as a zero-padded decimal number.**) but now reading through #79084 i see its the same Issue as mine. If #79084 is correct then I guess a change to the docs is required.
