### ISSUE TITLE
Extend sqlite3 CLI tests

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#108617]
# Bug report

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Proposal:

The interactive sqlite3 CLI tests are suboptimal; Serhiy easily proved they can be silently broken in a number of ways.

### Linked PRs
* gh-108556
* gh-108626

**Comment by EddInSverige** [comment]
@erlend-aasland Happy to take a look at this, unless Serhiy was planning to do something already, but might need some direction with what would be good test cases?

**Comment by erlend-aasland** [comment]
Serhiy already has a PR up. If you want to look for test coverage holes, you should set up C coverage measurement in your development environment.
