### ISSUE TITLE
types.MemberDescriptorType docs should mention it is used for __slots__

### ISSUE THREAD

**Issue by plokmijnuhby** [python/cpython#108731]
The documentation for types.MemberDescriptorType in the types module indicate that it is used in extension modules. This is true, but fails to mention the other common use of the class, as the type of a slot.
For those who aren't aware, if we define a class like so:
```
class Foo:
    __slots__ = ('bar',)
```
then it will create an attribute `bar` on the class. Calling `type(Foo.bar)` will return types.MemberDescriptorType.

### Linked PRs
* gh-108745
* gh-114536
* gh-114537

**Comment by AA-Turner** [comment]
PR welcome!

A

**Comment by ApoorvShah111** [comment]
Hi, a newbie here is this issue open for taking up?
If so any related documentation would be greatly appreciated!

**Comment by Vidhyavinu** [comment]
Can I work on this issue?

**Comment by hugovk** [comment]
@Vidhyavinu Thanks, but we already have a PR for this: https://github.com/python/cpython/pull/108745

**Comment by Vidhyavinu** [comment]
@hugovk  ok. Thanks for the update.
