### ISSUE TITLE
C++ include behavior instead of "from"and"import"

### ISSUE THREAD

**Issue by Suletta-Majo** [python/cpython#108706]
# Feature or enhancement

### Has this already been discussed elsewhere?

No response given

### Proposal:

```python
include subcodefile
or
from subcodefile include ***#function or section?
```
I'm a beginner who has been programming in Python for 1 month  
The main program file that has become too long If you try to separate files (modules) by approximate By role
It does not seem to be very suitable for such applications, and the “scope” is complicated. i confused
like below case. (those are 13years ago :0)
https://stackoverflow.com/questions/3400525/global-variable-from-a-different-file-python
https://stackoverflow.com/questions/8814316/make-variable-global-to-multiple-files-in-python

so i'am suggest this
command combines files. Just like C++ "include" is "as far as I know" such behavior
13years ago this stackoverflow question by someone. 
so I'm sorry if a simple solution or way of doing things has been added to Python as it is now, I didn't find it

**Comment by AlexWaygood** [comment]
The feature-request issue form states:

> Proposing a feature to CPython?
> 
> You'll need to demonstrate widespread support for your idea among the community.
> 
> Major feature proposals should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue. Wait until it's clear that most people support your idea before filling in this form.

This would definitely constitute a major feature proposal, given that it's a proposal for new syntax. Please open a thread on Discourse to discuss your idea :)

**Comment by Suletta-Majo** [comment]
oh. ok understand thanks
