### ISSUE TITLE
doctest: count the number of skipped tests

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108794]
# Feature or enhancement

### Has this already been discussed elsewhere?

No response given

### Proposal:

Currently, doctest only counts the number of failured and attempted tests, not the number of skipped tests.

### Linked PRs
* gh-108795

**Comment by serhiy-storchaka** [comment]
See also #108885.

Different examples in a doctest are not like separate test cases. They are not independent, they run in the specific order, and they cannot be conditionally skipped by CLI options. They are more like sub-tests.

**Comment by vstinner** [comment]
The feature was implemented in https://github.com/python/cpython/commit/4f9b706c6f5d4422a398146bfd011daedaef1851. I close the issue.

> See also https://github.com/python/cpython/issues/108885. Different examples in a doctest are not like separate test cases. They are not independent, they run in the specific order, and they cannot be conditionally skipped by CLI options. They are more like sub-tests.

Ok, I will have a look.
