### ISSUE TITLE
The warning about handle_list and close_fds may have bug

### ISSUE THREAD

**Issue by qqwqqw689** [python/cpython#108796]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### A clear and concise description of the bug:

The code in subprocess.py.
```python
if handle_list:
  if not close_fds:
      warnings.warn("startupinfo.lpAttributeList['handle_list'] "
                    "overriding close_fds", RuntimeWarning)
      
  # When using the handle_list we always request to inherit
  # handles but the only handles that will be inherited are
  # the ones in the handle_list
  close_fds = False
```
If the close_fds is True, we will never get into the second if block.
But in document subprocess, it says that

handle_list
Sequence of handles that will be inherited. close_fds must be true if non-empty.

**Comment by sobolevn** [comment]
> Sequence of handles that will be inherited. close_fds must be true if non-empty.

So, `if len(handle_list) > 0 and not closed_fds: warn()`
This is exactly what we have in the code, isn't it?

**Comment by qqwqqw689** [comment]
If the list is empty, if will be false.

This code:
```python
test = [] 

if test:
    print(1)
```

According to the document:

handle_list
Sequence of handles that will be inherited. close_fds must be true if non-empty.

On Windows, if close_fds is true then no handles will be inherited by the child process unless explicitly passed in the handle_list element of STARTUPINFO.lpAttributeList, or by standard handle redirection.

I think the code should be:
```python
if handle_list:
  if not close_fds:
      warnings.warn("startupinfo.lpAttributeList['handle_list'] "
                    "overriding close_fds", RuntimeWarning)
      
  # When using the handle_list we always request to inherit
  # handles but the only handles that will be inherited are
  # the ones in the handle_list
  close_fds = True
```

Maybe? To the honest, I'm not sure.

**Comment by iritkatriel** [comment]
I'm closing because the code seems to match the documentation.

The usual way to report a bug is by providing a script that produces output which contradicts the documentation.
