### ISSUE TITLE
getrefcount() function return value issue in 3.11.x version

### ISSUE THREAD

**Issue by tausa86** [python/cpython#108705]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Windows

### A clear and concise description of the bug:

```python
# Add a code block here, if required
```
n=10
getrefcount(n)
![Python_3 11 x_version_issue](https://github.com/python/cpython/assets/143679925/7275c730-57f4-417e-8ee5-51bf0c5b78a2)

**Comment by sobolevn** [comment]
Repro from image:

```python
>>> from sys import getrefcount
>>> getrefcount(10)
1000000022
```

But, why do you think that this is a bug?

**Comment by tausa86** [comment]
The 100000 is extra as compared to the previous version.

Also, the concept of reference count is that it represents the number of
variables referring to the object. I don't think for all variables there is
always 1 crore and above reference count or variables are pointing on a
given system.

Thanx and Regards,
Md Taufik

**Comment by tausa86** [comment]
Hello Adam,

Please compare results between 3.10.x and 3.11.4

It's real issue one more issue I have encountered is infinite loop in
3.10.x terminates automatically while in 3.11.4 it hangs IDLE (no response)
we need to close the window and reopen.

All these issues I encountered in Windows OS
Thanks and Regards,
Taufik
