### ISSUE TITLE
Split up _testinternalcapi.c

### ISSUE THREAD

**Issue by colesbury** [python/cpython#108777]
https://github.com/python/cpython/issues/93649 and associated PRs split up `_testcapimodule.c` because the file is large and hard to maintain. I'm proposing splitting the tests for the internal C API (`Modules/_testinternalcapi.c`) in the same manner for the same reasons. Additionally, I expect the PRs related to PEP 703 to require additional internal C API tests, and I'd like to avoid further cluttering `_testinternalcapi.c`.

cc @encukou @vstinner 

### Linked PRs
* gh-108787

**Comment by rhettinger** [comment]
I don't think this is worthwhile. In some ways, having lots of smaller files is its own bit of hassle.  Our editors are powerful enough to make it easy to work with a single large file.

**Comment by colesbury** [comment]
To be clear, I am not proposing breaking up `_testinternalcapi.c` entirely, only where there's enough related tests to make it worthwhile. I'm not proposing **lots** of smaller files. I'm proposing a **few** smaller files that contain test code for related bits of the internal C API, such as for testing the locks and other synchronization primitives in https://github.com/python/cpython/issues/108724.

**Comment by erlend-aasland** [comment]
> https://github.com/python/cpython/issues/93649 and associated PRs split up `_testcapimodule.c` because the file is large and hard to maintain. I'm proposing splitting the tests for the internal C API (`Modules/_testinternalcapi.c`) in the same manner for the same reasons. Additionally, I expect the PRs related to PEP 703 to require additional internal C API tests, and I'd like to avoid further cluttering `_testinternalcapi.c`.

Sounds reasonable to me; there's been various efforts the last years that have split up large and unmaintainable files (both .py and .c files) into maintainable chunks.

**Comment by vstinner** [comment]
Can you give a prototype of how you would like to split this C extension? Does it change the Python test_capi test package?

**Comment by erlend-aasland** [comment]
> For now, I'd just move the 12 `_PyTime` tests to their own file.

Do you want to keep this open?

**Comment by colesbury** [comment]
I think we can close this.
