### ISSUE TITLE
Markup missing in docs for `inspect.Signature.replace()`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#108857]
# Documentation

The word "replace" in the docs for `inspect.Signature.replace()` is missing appropriate markup to make it not appear as just the word "replace":

https://github.com/python/cpython/blob/44fc378b598eb675a847d1b7c46c8f6e81313c04/Doc/library/inspect.rst?plain=1#L733

Probably needs a `:meth:`, but at least some code literal markup.

### Linked PRs
* gh-108862
* gh-108970
* gh-108971

**Comment by nabin2004** [comment]
@brettcannon, I think I've wrapped up the task. This is my first time contributing to open source, so I apologize if I made any mistakes.
