### ISSUE TITLE
html.unescape() doesn't properly handle utf-8 sequences

### ISSUE THREAD

**Issue by sharkusk** [python/cpython#108802]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.11

### Output from running 'python -VV' on the command line:

Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]

### A clear and concise description of the bug:

A server is returning XML containing text with non-ascii characters provided as html utf-8 escape sequences.  html.unescape() mis-interprets these sequences as individual unicode characters causing incorrect output.
  
```python
from html import unescape

test_in = "&#232;&#128;&#129;&#229;&#184;&#171;&#230;&#149;&#172;&#230;&#156;&#141;" # e8 80 81 e5 b8 ab e6 95 ac e6 9c 8d
expected = "老師敬服"
result = unescape(test_in)
# result from unescape will be: "è€\x81å¸«æ•¬æœ\x8d"
print(expected == result)
```

**Comment by ronaldoussoren** [comment]
The [wikipedia page on character encodings](https://en.wikipedia.org/wiki/Character_encodings_in_HTML) documents that a numeric entity refers to a unicode character, which makes the behaviour of Python correct.

Python's behaviour also matches that of Safari given the following HTML fragment:

```html

<head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>

<body>
        <p>&#232;&#128;&#129;&#229;&#184;&#171;&#230;&#149;&#172;&#230;&#156;&#141;</p>
</body>
```

Because of this I'd say this isn't a bug in Python.

**Comment by sunmy2019** [comment]
I agree with @ronaldoussoren. See also https://en.wikipedia.org/wiki/List_of_XML_and_HTML_character_entity_references

```py
>>> "".join(chr(x) for x in [232, 128, 129, 229, 184, 171, 230, 149, 172, 230, 156, 141])
'è\x80\x81å¸«æ\x95¬æ\x9c\x8d'
```
