### ISSUE TITLE
<off topic>

### ISSUE THREAD

**Issue by sjy78** [python/cpython#108842]
怎么mu（3.8）里用open打不开一个.mp3的文件？？？
[.zip link removed]

**Comment by sunmy2019** [comment]
Please provide a concise description of the bug. Clarify what's in that zip file.

**Comment by sunmy2019** [comment]
It may be considered as spam under current status.

**Comment by ericvsmith** [comment]
According to Google Translate, this appears to be a usage question, not a bug report. Please ask your question on https://discuss.python.org/c/users/7, but I don't think there are many Chinese speakers there.

Also, posting a zip file with no explanation as to what's in it is unfriendly. Most people will not download and open a random zip file.
