### ISSUE TITLE
csv module documentation: some redundant statement

### ISSUE THREAD

**Issue by alextretyak** [python/cpython#108838]
From [here](https://github.com/python/cpython/blob/a52213bf830226fd969dc2a2ef8006c89edecc35/Doc/library/csv.rst?plain=1#L61-L62):
> If *csvfile* is a file object, it should be opened with ``newline=''``.

It looks like this statement is useless/redundant for **csv.reader** (i.e. it is useful only for **csv.writer**), as `newline=None` [by default] works fine on any platform.

### Linked PRs
* gh-108850
* gh-110256

**Comment by serhiy-storchaka** [comment]
It is not useless, because with `newline=None` and `newline=''` you can get different results if the input contains multiline quoted field. For example:
```csv
"a
b"
```

**Comment by alextretyak** [comment]
Can you give some working example?
I've checked the case with multiline quoted fields on both Windows and on Linux, and I haven't seen any different results between `newline=None` and `newline=''`.

When *newline* is `None`, universal newlines mode is enabled at file level, but it does not bother with the csv module own (universal) newline handling.

**Comment by alextretyak** [comment]
If the csv file contains:
```
"a
b"
```
I always get
```
['a\nb']
```

**Comment by serhiy-storchaka** [comment]
```pycon
>>> import csv, io
>>> next(csv.reader(io.TextIOWrapper(io.BytesIO(b'"a\r\nb"'), newline='')))
['a\r\nb']
>>> next(csv.reader(io.TextIOWrapper(io.BytesIO(b'"a\r\nb"'), newline=None)))
['a\nb']
```

**Comment by alextretyak** [comment]
```python
>>> next(csv.reader(io.TextIOWrapper(io.BytesIO(b'"a\r\nb"'), newline='')))
['a\r\nb']
```
This is not correct behaviour, I think. As `\r` character is not expected inside a string in any practical program. How should it [`\r`] be handled?
The sole purpose of the *newline* argument is to get rid of all `\r` characters correctly.

And to read csv from a string, code like this will be used:
```python
next(csv.reader(io.StringIO('"a\nb"')))
```

**Comment by serhiy-storchaka** [comment]
[RFC 4180](https://datatracker.ietf.org/doc/html/rfc4180#section-2),  section 2.6:
```
   6.  Fields containing line breaks (CRLF), double quotes, and commas
       should be enclosed in double-quotes.  For example:

       "aaa","b CRLF
       bb","ccc" CRLF
       zzz,yyy,xxx
```

So `\r\n` is expected in a quoted field.

In any case, this issue is about the documentation. And the documentation is correct, requiring to open input files with `newline=''`.

**Comment by alextretyak** [comment]
> RFC 4180

Please, do not confuse how data is *transferred* over the network with how it is *stored* in `str` variables in the programs.

For example, CRLF's are used in HTTP headers, but they never appear in strings:

```python
from urllib import request
with request.urlopen('https://google.com') as f:
    print(repr(str(f.info()))) # print all HTTP headers (printed headers are delimited with LF, not CRLF!)
```

> And the documentation is correct, requiring to open input files with `newline=''`.

No, it is not. If you open the input file **via `open()`** (as given in the usage example [here](https://github.com/python/cpython/blob/a52213bf830226fd969dc2a2ef8006c89edecc35/Doc/library/csv.rst?plain=1#L78)), then there is no difference between `newline=None` and `newline=''`.

**Comment by serhiy-storchaka** [comment]
There is a difference. `open()` in text mode returns `TextIOWrapper` which handles newline translations. I used `TextIOWrapper` and `BytesIO` for simplicity, but here is an example with `open()`:
```pycon
>>> import csv
>>> with open('test.csv', 'w', newline='') as f:
...     csv.writer(f).writerow(['a\r\nb', 'a\nb', 'a\rb'])
... 
20
>>> with open('test.csv', 'r', newline='') as f:
...     print(next(csv.reader(f)))
... 
['a\r\nb', 'a\nb', 'a\rb']
>>> with open('test.csv', 'r', newline=None) as f:
...     print(next(csv.reader(f)))
... 
['a\nb', 'a\nb', 'a\nb']
```

**Comment by alextretyak** [comment]
Hm. It looks like I mistested this case.
But then it's even worse: the csv reader leaves CR's inside the strings for csv files with multiline records stored with Windows-style line endings. Although this is a subject for another issue...
