### ISSUE TITLE
<off topic>

### ISSUE THREAD

**Issue by sjy78** [python/cpython#108846]
请问，怎么用不了open打开一个音频？
（在这个文件里）
[.zip link removed]
（源代码是编写在编译器里的东西，错误码是抛出的错误）

**Comment by wangyi041228** [comment]
如果你是真人，应该是 Python 新用户。建议你通过书籍、视频或其他渠道入门 Python 和各库，你遇到的基础问题在这里无法得到有效解答。具体到你提供的代码，tftp(socket(AF_INET,SOCK_DGRAM), '002.mp3')已经实现功能，前面的a =和下一行的open纯粹画蛇添足。
