### ISSUE TITLE
Support nushell in venv

### ISSUE THREAD

**Issue by detrin** [python/cpython#108852]
# Feature or enhancement

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

I am not aware of any.

### Proposal:

Similar to https://github.com/python/cpython/tree/03c4080c71f49df9c219354b7b38b738917fd2ed/Lib/venv/scripts/common

I would be nice to include support for [nushell](https://github.com/nushell/nushell) 

For example virtualenv has it already https://github.com/pypa/virtualenv/blob/6d22da631fd289f89f921a4010047ad969b7bfa7/src/virtualenv/activation/nushell/activate.nu#L2

### Linked PRs
* gh-114042
* gh-114043

**Comment by HarshKakran** [comment]
Hey! Is anyone working on this?

**Comment by detrin** [comment]
> Hey! Is anyone working on this?

I doubt it as it is not assigned to anyone? Are you interested in status of this issue or in making PR?

**Comment by sobolevn** [comment]
From https://github.com/nushell/nushell/issues/852 I can tell that `nu` still changes quite often. Python's release model is quite slow, users won't be able to just run `pip install -U virtualenv` to update to the fix version of `activate.nu`.

Plus, how would we test that the script is correct? 

Who would support `activate.nu` in CPython's repo? It seems like a very niche technology, not many people are familiar with it (yet!)

**Comment by sobolevn** [comment]
Here's how `nu` looks: https://github.com/pypa/virtualenv/blob/6d22da631fd289f89f921a4010047ad969b7bfa7/src/virtualenv/activation/nushell/activate.nu#L2

**Comment by detrin** [comment]
> From [nushell/nushell#852](https://github.com/nushell/nushell/issues/852) I can tell that `nu` still changes quite often. Python's release model is quite slow, users won't be able to just run `pip install -U virtualenv` to update to the fix version of `activate.nu`.

Right, but I think this may change in future. At the moment there is no stable major release of nushell.

> Plus, how would we test that the script is correct?

I don't understand where is here an issue. The same way as are envs set in shell we could do it in nushell and then check them as sort of unit test and their behavior with using python. 

> Who would support `activate.nu` in CPython's repo? It seems like a very niche technology, not many people are familiar with it (yet!)

Well, I am here and I believe many ppl who use nushell + python will join in future as nushell is more and more popular.

**Comment by brettcannon** [comment]
> Right, but I think this may change in future. At the moment there is no stable major release of nushell.

And since we don't want to burden ourselves with supporting a moving target, I think we would prefer to consider adding support once a stable release is out.
