### ISSUE TITLE
TypeError when use `type` as the enum value

### ISSUE THREAD

**Issue by Atry** [python/cpython#108883]
# Bug report

### Checklist

- [X] I am confident this is a bug in CPython, not a bug in a third-party project
- [X] I have searched the [CPython issue tracker](https://github.com/python/cpython/issues?q=is%3Aissue+sort%3Acreated-desc),
and am confident this bug has not been reported before

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

Python 3.10.12 (main, Jun 23 2023, 11:49:23) [Clang 11.1.0 ]

### A clear and concise description of the bug:

```python
from enum import Enum


class MyTypeEnum(type, Enum):
    A = object
    B = str
```
When defining an enum whose values are types, I got the `TypeError`
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[4], line 4
      1 from enum import Enum
----> 4 class MyTypeEnum(type, Enum):
      5     A = object
      6     B = str

File [/nix/store/2rrfpkq6cr8ppip9szl0z1qfdlskdinq-python3-3.10.12/lib/python3.10/enum.py:223](https://file+.vscode-resource.vscode-cdn.net/nix/store/2rrfpkq6cr8ppip9szl0z1qfdlskdinq-python3-3.10.12/lib/python3.10/enum.py:223), in EnumMeta.__new__(metacls, cls, bases, classdict, **kwds)
    218 enum_class._member_type_ = member_type
    220 # save DynamicClassAttribute attributes from super classes so we know
    221 # if we can take the shortcut of storing members in the class dict
    222 dynamic_attributes = {
--> 223         k for c in enum_class.mro()
    224         for k, v in c.__dict__.items()
    225         if isinstance(v, DynamicClassAttribute)
    226         }
    228 # Reverse value->name map for hashable values.
    229 enum_class._value2member_map_ = {}

TypeError: unbound method type.mro() needs an argument
```

### Linked PRs
* gh-108884

**Comment by terryjreedy** [comment]
I confirmed the behavior on 3.12.0rc1.  Without reading the enum doc, I am not sure whether this is a bug report or feature request.  In either case, the main branch patched first unless a patch does not apply there.  I recommend that you wait for a response from @ethanfurman or other core dev knowledgeable about enum before submitting a new patch, for the main branch.

**Comment by Atry** [comment]
The doc did not mention that type cannot be an enum value

**Comment by AlexWaygood** [comment]
Python 3.10 is now only accepting security fixes, so let's look at the behaviour here on Python 3.11-3.13. On Python 3.11, we get this behaviour:

```pycon
>>> import enum
>>> class Foo(type, enum.Enum):
...     X = range
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 560, in __new__
    raise exc
  File "C:\Users\alexw\AppData\Local\Programs\Python\Python311\Lib\enum.py", line 259, in __set_name__
    enum_member = enum_class._new_member_(enum_class, *args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() takes exactly 3 arguments (1 given)
```

And on the CPython `main` branch, we get this behaviour:

```pycon
>>> import enum
>>> class Foo(type, enum.Enum):
...     X = range
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\alexw\coding\cpython\Lib\enum.py", line 574, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\alexw\coding\cpython\Lib\enum.py", line 266, in __set_name__
    enum_member = enum_class._new_member_(enum_class, *args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: type.__new__() takes exactly 3 arguments (1 given)
Error calling __set_name__ on '_proto_member' instance 'X' in 'Foo'
```

I haven't checked on Python 3.12, but I imagine it'll be much the same as either Python 3.11 or Python 3.13.

Neither of these behaviours looks like a bug to me. This behaviour is covered by the docs here (though I admit it took me a little while to find the explanation in the docs): https://docs.python.org/3/howto/enum.html#creating-members-that-are-mixed-with-other-data-types

> When subclassing other data types, such as [int](https://docs.python.org/3/library/functions.html#int) or [str](https://docs.python.org/3/library/stdtypes.html#str), with an [Enum](https://docs.python.org/3/library/enum.html#enum.Enum), all values after the `=` are passed to that data type’s constructor. For example:
>
> ```pycon
> >>> class MyEnum(IntEnum):      # help(int) -> int(x, base=10) -> integer
> ...     example = '11', 16      # so x='11' and base=16
> ...
> >>> MyEnum.example.value        # and hex(11) is...
> 17
> ```

`type.__new__` has to be called with three arguments, so it makes sense that the snippet in your issue report doesn't work.

There does seem to have been a _small_ regression in the error message between Python 3.11 and Python 3.13, but it doesn't seem too severe. I'll let @ethanfurman decide on whether this should be closed, though, as he's the `enum` maintainer.
