### ISSUE TITLE
`global x: int` is not tested

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#108983]
While reading https://peps.python.org/pep-0526/#where-annotations-aren-t-allowed I've noticed that not all corner-cases are covered: https://github.com/python/cpython/blob/6f8411cfd68134ccae01b0b4cb332578008a69e3/Lib/test/test_grammar.py#L347-L365

For example, explicit PEP's example:

```python
def f():
    global x: int  # SyntaxError

def g():
    x: int  # Also a SyntaxError
    global x
```

Two problems:
1. `global x: int` is not tested, only `nonlocal x: int` is
2. `x: int; nonlocal x` is not tested

There's also an interesting corner-case from the rejected ideas:

```python
x: int = y = 1
z = w: int = 1
```

Since, we have this test `check_syntax_error(self, "def f: int")`, I assume that we also test rejected ideas here. So, let's add this one as well.

I propose adding these three cases.

### Linked PRs
* gh-108984
* gh-109000
* gh-109001

**Comment by hugovk** [comment]
Thank you!
