### ISSUE TITLE
Adding collections.Counter - int

### ISSUE THREAD

**Issue by jonashaag** [python/cpython#108994]
# Feature or enhancement

### Proposal:

Add support for `some_counter - some_int` as an easy way to remove all elements with a count `<= some_int`.

```python
print(MyCounter("aaabb") - 2)
# => Counter({'a': 1})


# Example implementation:

from collections import Counter

class MyCounter(Counter):
    def __sub__(self, other):
        if isinstance(other, int):
            result = Counter()
            for elem, count in self.items():
                newcount = count - other
                if newcount > 0:
                    result[elem] = newcount
            return result
        else:
            return super().__sub__(other)
```

### Links to previous discussion of this feature:

https://discuss.python.org/t/adding-collections-counter-int/33114/1

**Comment by hugovk** [comment]
When I look at `MyCounter("aaabb") - 2` it's not immediately clear it does what you're proposing, so this will benefit from a wider discussion first.

Please will you open a topic at https://discuss.python.org/c/ideas/6?

**Comment by AlexWaygood** [comment]
Closing until the discussion on discuss.python.org has reached consensus; we can reopen if there is support for the proposal
