### ISSUE TITLE
Disallow frame_setlineno on yield events

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#108933]
It's a difficult case to support, and it's not at all clear that there is a use case for it. 

### Linked PRs
* gh-108947

**Comment by markshannon** [comment]
While setting the line number on yield events seems like a weird thing to do, and hard to do from a debugger, perhaps there is a use case.
I feel a bit nervous removing this without some evidence that isn't used.
Maybe ask on discuss.python.org if anyone knows of a use?

**Comment by markshannon** [comment]
OOI, what specifically is hard to support?

**Comment by iritkatriel** [comment]
https://discuss.python.org/t/does-anyone-have-a-use-case-for-setting-f-lineno-from-a-return-event-of-a-yield/33110

**Comment by iritkatriel** [comment]
> Maybe ask on discuss.python.org if anyone knows of a use?

My post has been up for about 3 weeks now and nobody came up with anything.

**Comment by markshannon** [comment]
That might just mean that no one saw it, of course, but I think it we can go ahead.

**Comment by markshannon** [comment]
Is the yield event the problem or is it jumping in a suspended generator?

What happens if I change the line number of a suspended generator? `gen.gi_frame.f_lineno = ...` in an unrelated line event?
