### ISSUE TITLE
test_asyncio: test_subprocess_consistent_callbacks() fails randomly

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108973]
The following test_asyncio test is unstable and fails randomly on buildbots. I saw failures on Linux and FreeBSD.

```
FAIL: test_subprocess_consistent_callbacks (test.test_asyncio.test_subprocess.SubprocessThreadedWatcherTests.test_subprocess_consistent_callbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel8-z.lto-pgo/build/Lib/test/test_asyncio/test_subprocess.py", line 788, in test_subprocess_consistent_callbacks
    self.loop.run_until_complete(main())
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel8-z.lto-pgo/build/Lib/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/dje/cpython-buildarea/3.x.edelsohn-rhel8-z.lto-pgo/build/Lib/test/test_asyncio/test_subprocess.py", line 780, in main
    self.assertEqual(events, [
AssertionError: Lists differ: ['process_exited', ('pipe_data_received', 1, b'stdout')] != [('pipe_data_received', 1, b'stdout'), ('p[95 chars]ted']

First differing element 0:
'process_exited'
('pipe_data_received', 1, b'stdout')

Second list contains 3 additional elements.
First extra element 2:
'pipe_connection_lost'

- ['process_exited', ('pipe_data_received', 1, b'stdout')]
?  ------------------                                    ^

+ [('pipe_data_received', 1, b'stdout'),
?                                      ^

+  ('pipe_data_received', 2, b'stderr'),
+  'pipe_connection_lost',
+  'pipe_connection_lost',
+  'process_exited']
```

build: https://buildbot.python.org/all/#/builders/442/builds/4900

### Linked PRs
* gh-109431
* gh-109609
* gh-109610

**Comment by gvanrossum** [comment]
Agreed. Feel free to suggest a PR that fixes this.

**Comment by vstinner** [comment]
@kumaraditya303: It looks wrong that the "process_exited" event is reported **after** "pipe_data_received" event. Any idea on how to make sure that events are delivered in the right order?

First, I wanted to just tolerate events in any order in the test. But then I realized that maybe something is wrong here.

**Comment by kumaraditya303** [comment]
"process_exited" should be the last event, also I am unable to reproduce it on any of my own testing, I guess something is special about freebsd but I don't have bandwidth to investigate for such platforms.

**Comment by vstinner** [comment]
> I saw failures on Linux and FreeBSD.

So far, I didn't manage to design a reliable way to trigger the bug. I will have a look at it later. I wanted to open an issue to keep track of it. There are many unstable tests these days in Python, and it annoys me to have flaky CI.

**Comment by vstinner** [comment]
@kumaraditya303:
> "process_exited" should be the last event, also I am unable to reproduce it on any of my own testing, I guess something is special about freebsd but I don't have bandwidth to investigate for such platforms.

Oh sure, it's perfectly fine if you don't have the bandwidth for that.

**Comment by kumaraditya303** [comment]
> Oh sure, it's perfectly fine if you don't have the bandwidth for that.

If you get a reliable way to trigger it on Linux then I will surely look into it.

**Comment by vstinner** [comment]
Variant on FreeBSD:

```
FAIL: test_subprocess_consistent_callbacks (test.test_asyncio.test_subprocess.SubprocessThreadedWatcherTests.test_subprocess_consistent_callbacks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/Lib/test/test_asyncio/test_subprocess.py", line 788, in test_subprocess_consistent_callbacks
    self.loop.run_until_complete(main())
  File "/tmp/cirrus-ci-build/Lib/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/tmp/cirrus-ci-build/Lib/test/test_asyncio/test_subprocess.py", line 780, in main
    self.assertEqual(events, [
AssertionError: Lists differ: [('pi[29 chars]t'), 'pipe_connection_lost', ('pipe_data_recei[57 chars]ted'] != [('pi[29 chars]t'), ('pipe_data_received', 2, b'stderr'), 'pi[57 chars]ted']
First differing element 1:
'pipe_connection_lost'
('pipe_data_received', 2, b'stderr')
  [('pipe_data_received', 1, b'stdout'),
-  'pipe_connection_lost',
   ('pipe_data_received', 2, b'stderr'),
   'pipe_connection_lost',
+  'pipe_connection_lost',
   'process_exited']
```

build: https://cirrus-ci.com/task/6142659970990080?logs=test#L878

**Comment by vstinner** [comment]
Issue seen on s390x RHEL7 LTO 3.x: https://buildbot.python.org/all/#/builders/402/builds/5394

**Comment by vstinner** [comment]
Also seen on:

* s390x SLES 3.x: https://buildbot.python.org/all/#/builders/540/builds/6542
* s390x RHEL8 3.x: https://buildbot.python.org/all/#/builders/509/builds/4914

**Comment by vstinner** [comment]
I started to write a fix to ensure that events are always delivered in a specific order. For example, create 4 queues of callbacks:
* priority 0 - pipe_data_received (highest)
* priority 1 - pipe_connection_lost
* priority 2 - process_exited
* priority 3 - others (lowest)

The problem is that asynchronous programming is hard, system programming is hard, and as @sorcio wrote, multi-core CPUs, multithreading, and different event loop implementation make everything less deterministic.

My worry is if that for some reasons one of these events is not delivered, the other ones are queue... maybe forever :-(

When a process completes, I want to know it as soon as possible. Getting its pipe output is honestly secondary. Maybe the process was killed by a signal. Maybe something bad happens, who knows?

@sorcio:
> I'm unsure what asyncio wants to promise here.

While it's technically possible to ensure that events are delivered in a determistic way... I'm not sure that it's worth it :-( The drawbacks seem to be expensive and risky to me.

Thanks @sorcio to digging deep into the issue and for your long analysis!

I'm now more confident that the test... should just endorse that async programming make such events less determistic and tolerate that these events can be delivery in any order. I wrote PR #109431 for that.

**Comment by gvanrossum** [comment]
Is everyone here aware that "process exited" and "pipe closed" are orthogonal events? The process that exits may have shared the file descriptor with a child process that continues to exist. Or the process could close the file descriptor without exiting. I don't think we should enforce or require an order between such events.

**Comment by vstinner** [comment]
@gvanrossum:
> Is everyone here aware that "process exited" and "pipe closed" are orthogonal events? The process that exits may have shared the file descriptor with a child process that continues to exist. Or the process could close the file descriptor without exiting.

It just kills my idea of **ordering events**.

> I don't think we should enforce or require an order between such events.

Ok, so we are on the same page: my PR #109431 fix the test by accepting that events are not ordered. With my change, the only thing which is tested is that we get all events, in any order.

**Comment by vstinner** [comment]
> It could be worth mentioning in the docs, if it's probable cause for confusion.

Done in my (updated) PR.

> The original issue also points to the [example in the docs](https://github.com/python/cpython/blob/82505dc351b2f7e37aa395218709b432d83292cd/Doc/library/asyncio-protocol.rst?plain=1#L991) which is not correct because it makes the same wrong assumption.

Example fixed in my (updated) PR.
