### ISSUE TITLE
Make functools.cache accepting a cached function id / custom cache dict

### ISSUE THREAD

**Issue by vadimkantorov** [python/cpython#108990]
# Feature or enhancement

### Proposal:

Sometimes it would be nice to be able to tell `functools.cache` that `g()` calls should be cached between `f()` calls. For that, I propose to allow an argument which would override the identity of the cached function (`id=` or `function_key=` or other name).

A second idea is to allow `functools.cache` to accept an underlying dict as an argument. This would then allow to manage it as user wishes (e.g. clear this dict manually when need to reduce memory pressure; or have multiple dicts with different cache policies)

```python
import functools

def f():
    @functools.lru_cache
    def g():
        print(2)
        return 1
    print(g())

if __name__ == '__main__':
    f()
    f()
```

On my Python 3.8 it prints
```
2
1
2
1
```

If we could instead say sth like:
```python
my_large_llm_model_objects = {}

def f():
    @functools.lru_cache(id = "g", dict = my_large_llm_model_objects)
    def g():
        ...
if __name__ == '__main__':
    f()
    f()
    my_large_model_objects.clear()
    f()
    f()
```

Then, it 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by serhiy-storchaka** [comment]
The title mentions `functools.cache`, but all examples in the body use `functools.lru_cache`. What exactly do you mean?

If you want to clear a cache, use the `cache_clear()` method of the cached function.

If you want to have multiple caches with different cache policies, create several cached functions from the same original:
```
g1 = functools.lru_cache(maxsize=100)(g)
g2 = functools.lru_cache(maxsize=2000)(g)
```

cc @rhettinger

**Comment by vadimkantorov** [comment]
> What exactly do you mean?

I'm using old Python 3.8.10 which doesn't have `@functools.cache`, but I think the ideas (allow passing explicit function id and arena dict) are useful for both `@functools.cache` and `@functools.lru_cache`

Thanks for hinting that every `@functools.cache` call creates its own cache, I didn't know that. So maybe my ideas are not very applicable then (my ideas would in reverse enable some more persistent / global underlying cache dicts). But curious to learn what others think

**Comment by rhettinger** [comment]
Thank you for the suggestion but I think we should decline.  In my experience, it would cause more problems and create more confusion than it would solve.  FWIW, there are many cache variants on PyPI so you could try one of those.  Also, it is easy to write your own variants following the examples in the `OrderedDict` docs.
