### ISSUE TITLE
tarfile doesn't set file modes correctly on FreeBSD: test_tarfile.test_modes() fails on FreeBSD

### ISSUE THREAD

**Issue by sorcio** [python/cpython#108948]
# Bug report

### Bug description:

The best example for this is given in the regression test suite. `TestExtractionFilters.test_modes` in `test_tarfiles` fails with `OSError: [Errno 79] Inappropriate file type or format` on FreeBSD.

The reason is that [chmod](https://man.freebsd.org/cgi/man.cgi?query=chmod&sektion=2&manpath=FreeBSD+14.0-STABLE) fails with EFTYPE (errno 79) when attempting to set the sticky bit (S_ISVTX) on a file when the effective user is not root. Most other platforms will just ignore the bit in chmod calls.

Tested on FreeBSD 13.2 but documentation suggests this is not a new behavior.

(Note that FreeBSD buildbots haven't been running for a while. This is probably why this issue, although it causes a test failure, hadn't been caught before)

### CPython versions tested on:

3.12

### Operating systems tested on:

Other

### Linked PRs
* gh-108950
* gh-109697
* gh-109698
* gh-109699

**Comment by vstinner** [comment]
Fixed by skipping the test if chmod() cannot set the sticky bit.

See https://github.com/python/cpython/pull/108950#issuecomment-1731523355 for the longer rationale.
