### ISSUE TITLE
test_sys.test_intern() fails if run more than once in the same process

### ISSUE THREAD

**Issue by vstinner** [python/cpython#108963]
# Bug report

Example:

```
$ ./python -m test test_sys test_sys -m test_intern -v
(...)
0:00:00 load avg: 1.60 Run tests sequentially
0:00:00 load avg: 1.60 [1/2] test_sys
test_intern (test.test_sys.SysModuleTest.test_intern) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.001s

OK
0:00:00 load avg: 1.60 [2/2] test_sys
test_intern (test.test_sys.SysModuleTest.test_intern) ... FAIL

======================================================================
FAIL: test_intern (test.test_sys.SysModuleTest.test_intern)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vstinner/python/3.12/Lib/test/test_sys.py", line 687, in test_intern
    self.assertTrue(sys.intern(s) is s)
AssertionError: False is not true

----------------------------------------------------------------------
(...)

Result: FAILURE
```

### Linked PRs
* gh-109491
* gh-110216

**Comment by serhiy-storchaka** [comment]
For reference, the module level counter was added in aee3486b318d11c10520b533735d98ade48776a5 to prevent test_intern failing when it is rerun in verbose mode. But if the module is reloaded, the counter is reset.

One of solutions is to use the random module. Possibility of collisions in negligible.

Other solution -- use timer in the hope that the computer is not fast enough to finish the whole test several times in the time resolution unit.

We can also try to use `id()`s of some objects (`self`, `globals()`, `locals()`), but there is greater chance that all of them are allocated at exactly same address after reloading the module.

`test_subinterp_intern_dynamically_allocated` fails for the same reason.
