### ISSUE TITLE
duplicate backslashes in str.split docstring

### ISSUE THREAD

**Issue by jwilk** [python/cpython#108915]
```console
$ pydoc3 str.split | grep -F '\\'
        character (including \\n \\r \\t \\f and spaces) and will discard
```
These should be single backslashes.

### Linked PRs
* gh-109044
* gh-109061
* gh-109062

**Comment by sobolevn** [comment]
This looks much better, I agree:
<img width="788" alt="Снимок экрана 2023-09-05 в 17 03 18" src="https://github.com/python/cpython/assets/4660275/14185514-098e-457e-8e94-9ad8318499f5">

Would you like to send your first a PR? :)

**Comment by terryjreedy** [comment]
str.split.__doc__ has 4 backslashes for each char, whereas it should only have 2 so that 1 is left in the string instead of 2.
