### ISSUE TITLE
Add tests for msvcrt module

### ISSUE THREAD

**Issue by aisk** [python/cpython#108996]
# Bug report

### Bug description:

[msvcrt](https://docs.python.org/3/library/msvcrt.html) is a public module, but it has no tests.

### Linked PRs
* gh-109004
* gh-109169
* gh-109226

**Comment by terryjreedy** [comment]
Thanks for the submission.  I reviewed the PR but would like someone else to look at the file op class.

**Comment by vstinner** [comment]
I close the issue, thanks @aisk.

**Comment by vstinner** [comment]
test_msvcrt: test_getwche() failed with timeout (10 min) on GHA Windows x64: see issue gh-110147.
