### ISSUE TITLE
test_xxtestfuzz emits DeprecationWarning

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#109098]
test_xxtestfuzz emits deprecation warnings about modules sre_compile and sre_constants which always were internal. It should use public non-deprecated API.

```
$ ./python -Wa -m test -v test_xxtestfuzz
...
test_sample_input_smoke_test (test.test_xxtestfuzz.TestFuzzer.test_sample_input_smoke_test)
This is only a regression test: Check that it doesn't crash. ... /home/serhiy/py/cpython/Lib/test/test_xxtestfuzz.py:13: DeprecationWarning: module 'sre_compile' is deprecated
  _xxtestfuzz.run(b"")
/home/serhiy/py/cpython/Lib/test/test_xxtestfuzz.py:13: DeprecationWarning: module 'sre_constants' is deprecated
  _xxtestfuzz.run(b"")
ok
...
```

cc @ssbr, @ammaraskar

### Linked PRs
* gh-109911
* gh-109932
* gh-109933

**Comment by serhiy-storchaka** [comment]
cc @ammaraskar

These tests should be either removed or rewritten using the public API.

**Comment by gpshead** [comment]
I believe that PR should fix this. if not, please feel free to reopen. thanks for the PR and reviews!

**Comment by serhiy-storchaka** [comment]
Do not miss merging in 3.12 branch.

**Comment by serhiy-storchaka** [comment]
@gpshead Please do no forgot to edit commit message. It contains a duplicate of the subject and intermediate commit messages.
