### ISSUE TITLE
ARM Raspbian 3.x fails to build _testcapi extension: undefined symbol: __atomic_fetch_or_8

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109054]
I supposed that the build error is related to ``Modules/_testcapi/pyatomic.c`` and ``Include/cpython/pyatomic.h``.

"Raspbian is a free operating system based on Debian optimized for the Raspberry Pi hardware."

Buildbot worker says: "Raspberry Pi 4 B running Raspbian (Bullseye 11.x)."

test.pythoninfo:

* CC.version: gcc (Raspbian 10.2.1-6+rpi1) 10.2.1 20210110
* platform.architecture: 32bit ELF
* platform.libc_ver: glibc 2.31
* platform.platform: Linux-6.1.21-v8+-aarch64-with-glibc2.31
* sysconfig[PY_CFLAGS]: ``-fno-strict-overflow -DNDEBUG -g -O3 -Wall -UNDEBUG``
* sysconfig[PY_CFLAGS_NODIST]: ``-std=c11 -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal``
* sysconfig[PY_STDMODULE_CFLAGS]: ``-fno-strict-overflow -DNDEBUG -g -O3 -Wall -UNDEBUG -std=c11 -Werror=implicit-function-declaration -fvisibility=hidden -I./Include/internal -I. -I./Include``

Logs:

```
gcc -pthread -shared      Modules/_testcapimodule.o Modules/_testcapi/vectorcall.o Modules/_testcapi/vectorcall_limited.o Modules/_testcapi/heaptype.o Modules/_testcapi/abstract.o Modules/_testcapi/unicode.o Modules/_testcapi/dict.o Modules/_testcapi/getargs.o Modules/_testcapi/datetime.o Modules/_testcapi/docstring.o Modules/_testcapi/mem.o Modules/_testcapi/watchers.o Modules/_testcapi/long.o Modules/_testcapi/float.o Modules/_testcapi/structmember.o Modules/_testcapi/exceptions.o Modules/_testcapi/code.o Modules/_testcapi/buffer.o Modules/_testcapi/pyatomic.o Modules/_testcapi/pyos.o Modules/_testcapi/immortal.o Modules/_testcapi/heaptype_relative.o Modules/_testcapi/gc.o   -o Modules/_testcapi.cpython-313-arm-linux-gnueabihf.so
[ERROR] _testcapi failed to import: /var/lib/buildbot/workers/3.x.gps-raspbian.nondebug/build/build/lib.linux-aarch64-3.13/_testcapi.cpython-313-arm-linux-gnueabihf.so: undefined symbol: __atomic_fetch_or_8
The necessary bits to build these optional modules were not found:
_tkinter              _uuid                                    
To find the necessary bits, look in configure.ac and config.log.

Following modules built successfully but were removed because they could not be imported:
_testcapi                                                      

Checked 107 modules (31 built-in, 72 shared, 1 n/a on linux-aarch64, 0 disabled, 2 missing, 1 failed on import)
```

logs: https://buildbot.python.org/all/#/builders/424/builds/4849

cc @colesbury @gpshead 

### Linked PRs
* gh-109101
* gh-109211
* gh-109224

**Comment by vstinner** [comment]
Maybe Python should be linked to ``-latomic``. Old GCC discussions:

* https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81358
* "I think we should generally link libatomic with --as-needed by default: https://gcc.gnu.org/legacy-ml/gcc-patches/2013-11/msg02605.html

**Comment by vstinner** [comment]
Another example:

* https://github.com/grpc/grpc/pull/20514/commits/b912fc7d8d401bb65b3147ee77d03beaa3d46038
* https://stackoverflow.com/questions/70084134/undefined-symbol-atomic-exchange-8

**Comment by vstinner** [comment]
* Build 4788: 39 tests failed: https://buildbot.python.org/all/#/builders/424/builds/4788 -- this one added pyatomic.h and related _testcapi tests
* Build 4787: test_concurrent_futures.test_shutdown failed: https://buildbot.python.org/all/#/builders/424/builds/4787

I confirm that this regression comes from the commit 2bd960b57944107fbfbd8ff005b4223e1ea6555f.

**Comment by colesbury** [comment]
I'm on vacation this week, but I'll have some time to look at this this evening.

**Comment by vstinner** [comment]
I never heard about Raspbian before. I was curious about it, so I added ``platform.freedesktop_os_release()`` to ``test.pythoninfo`` :-)

```
platform.freedesktop_os_release[ID]: raspbian
platform.freedesktop_os_release[NAME]: Raspbian GNU/Linux
platform.freedesktop_os_release[VERSION]: 11 (bullseye)
platform.freedesktop_os_release[VERSION_CODENAME]: bullseye
platform.freedesktop_os_release[VERSION_ID]: 11
```

**Comment by colesbury** [comment]
From @vstinner's comments and playing with https://gcc.godbolt.org/, it looks like the 8 byte (64-bit) use library support with the default compiler options on this platform. GCC doesn't need the library support if you target `-march=armv7-a` (the ARMv7-A and ARMv7-R profiles support the `ldrexd` "double-word" exclusive load).

Some random other things that I learned, but are probably not important:
* Raspbian is now called Raspberry Pi OS
* The Raspberry Pi Model B's have used a 64-bit CPUs (armv8-a) since ~2016, but the Raspbian/Raspberry Pi OS was 32-bit only until 2022 and it seems like 32-bit OS is still the most commonly used

**Comment by vstinner** [comment]
> From @vstinner's comments and playing with https://gcc.godbolt.org/, it looks like the 8 byte (64-bit) use library support with the default compiler options on this platform. GCC doesn't need the library support if you target -march=armv7-a (the ARMv7-A and ARMv7-R profiles support the ldrexd "double-word" exclusive load).

It's nice if libatomic can be omitted depending on the compiler and compiler flags, but I would like to cover all cases :-) We should detect and add ``-latomic`` when needed.

**Comment by ayappanec** [comment]
**AIX** also fails to build because of this problem.
Modules/ld_so_aix gcc -pthread -bI:Modules/python.exp      Modules/_testcapimodule.o Modules/_testcapi/vectorcall.o Modules/_testcapi/vectorcall_limited.o Modules/_testcapi/heaptype.o Modules/_testcapi/abstract.o Modules/_testcapi/unicode.o Modules/_testcapi/dict.o Modules/_testcapi/getargs.o Modules/_testcapi/datetime.o Modules/_testcapi/docstring.o Modules/_testcapi/mem.o Modules/_testcapi/watchers.o Modules/_testcapi/long.o Modules/_testcapi/float.o Modules/_testcapi/structmember.o Modules/_testcapi/exceptions.o Modules/_testcapi/code.o Modules/_testcapi/buffer.o Modules/_testcapi/pyatomic.o Modules/_testcapi/pyos.o Modules/_testcapi/immortal.o Modules/_testcapi/heaptype_relative.o Modules/_testcapi/gc.o   -o Modules/_testcapi.cpython-313.so
ld: 0711-327 WARNING: Entry point not found: PyInit__testcapi.cpython-313
ld: 0711-317 ERROR: Undefined symbol: .__atomic_fetch_or_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_fetch_and_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_load_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_store_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_exchange_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_compare_exchange_8
ld: 0711-317 ERROR: Undefined symbol: .__atomic_fetch_add_8

Need -latomic to be passed. I see MODULE__TESTCAPI_LDFLAGS variable in the generated Makefile but not populated with anything

**Comment by vstinner** [comment]
> AIX also fails to build because of this problem.

Can you try my PR? Does it fix your issue?

**Comment by ayappanec** [comment]
> > AIX also fails to build because of this problem.
> 
> Can you try my PR? Does it fix your issue?

https://github.com/vstinner/cpython/tree/configure_libatomic
It still failed with the same error

**Comment by ayappanec** [comment]
> > > AIX also fails to build because of this problem.
> > 
> > 
> > Can you try my PR? Does it fix your issue?
> 
> https://github.com/vstinner/cpython/tree/configure_libatomic It still failed with the same error
> 
> The config.log has this
> 
> configure:27770: checking whether libatomic is needed by <pyatomic.h> configure:27815: gcc -pthread -o conftest -I. -I./Include conftest.c -lintl -ldl >&5 conftest.c:422: warning: "PY_BUILTIN_HASHLIB_HASHES" redefined 422 | #define PY_BUILTIN_HASHLIB_HASHES "md5,sha1,sha2,sha3,blake2" | conftest.c:421: note: this is the location of the previous definition 421 | #define PY_BUILTIN_HASHLIB_HASHES /**/ | ld: 0711-317 ERROR: Undefined symbol: .__atomic_fetch_or_8 ld: 0711-317 ERROR: Undefined symbol: .__atomic_load_8 ld: 0711-317 ERROR: Undefined symbol: .__atomic_store_8 ld: 0711-345 Use the -bloadmap or -bnoquiet option to obtain more information. collect2: error: ld returned 8 exit status configure:27815: $? = 1 configure: program exited with status 1

This is a 32bit build. 64bit build passes though

**Comment by ayappanec** [comment]
In AIX, only the 32bit build fails. 64bit build doesn't require -latomic looks like.

**Comment by vstinner** [comment]
> The config.log has this

What does the configure say? Does it say ``checking whether libatomic is needed by <pyatomic.h>... yes``?

Also, check if ``make`` links _testcapi with ``-latomic``. Or check ``grep '_TESTCAPI_.*=' Makefile`` command to see if you have ``-latomic`` in ``MODULE__TESTCAPI_LDFLAGS``.

**Comment by ayappanec** [comment]
https://github.com/vstinner/cpython/blob/configure_libatomic/configure#L27834
This line has some typo error I guess.

**Comment by ayappanec** [comment]
LIBATOMIC=${LIBATOMIC-"-latomic"}

**Comment by ayappanec** [comment]
> > The config.log has this
> 
> What does the configure say? Does it say `checking whether libatomic is needed by <pyatomic.h>... yes`?
> 
> Also, check if `make` links _testcapi with `-latomic`. Or check `grep '_TESTCAPI_.*=' Makefile` command to see if you have `-latomic` in `MODULE__TESTCAPI_LDFLAGS`.

MODULE__TESTCAPI_LDFLAGS is never populated with $LIBATOMIC, even though "MODULE__TESTCAPI_STATE=yes"

**Comment by vstinner** [comment]
> This line has some typo error I guess.

``LIBATOMIC=${LIBATOMIC-"-latomic"}`` is a dark spell of @erlend-aasland.

Sorry but I don't understand you test. Please:

* Apply my latest PR (I just updated it)
* Run ./configure
* Check ``checking whether libatomic is needed by <pyatomic.h>`` line in configure output. Is it yes or not?
* Check MODULE__TESTCAPI_LDFLAGS in Makefile: what is the variable value?

It's not clear to me if you ran your test on 32-bit or 64-bit AIX.

**Comment by ayappanec** [comment]
> > This line has some typo error I guess.
> 
> `LIBATOMIC=${LIBATOMIC-"-latomic"}` is a dark spell of @erlend-aasland.
> 
> Sorry but I don't understand you test. Please:
> 
> * Apply my latest PR (I just updated it)
> * Run ./configure
> * Check `checking whether libatomic is needed by <pyatomic.h>` line in configure output. Is it yes or not?
> * Check MODULE__TESTCAPI_LDFLAGS in Makefile: what is the variable value?
> 
> It's not clear to me if you ran your test on 32-bit or 64-bit AIX.

I did a fresh 
git clone https://github.com/vstinner/cpython
cd cpython
git checkout configure_libatomic
./configure 

checking whether libatomic is needed by <pyatomic.h>, the result is yes 
But "MODULE__TESTCAPI_LDFLAGS= " is still empty in Makefile.

It's a 32bit build. In AIX ,the default build environment is 32bit. 

64bit build in AIX works as it doesn't require -latomic .

**Comment by ayappanec** [comment]
LIBATOMIC=""
LIBATOMIC=${LIBATOMIC-"-latomic"}
echo $LIBATOMIC

This scenario never works

**Comment by ayappanec** [comment]
LIBATOMIC=${LIBATOMIC:-"-latomic"} will work instead.

**Comment by vstinner** [comment]
I fixed (again ;-)) my PR. Please test it.

The problem is that ``LIBATOMIC=${LIBATOMIC-"-latomic"}`` does nothing if the LIBATOMIC variable is already defined. And I defined it to an empty string with ``LIBATOMIC=""``.

**Comment by ayappanec** [comment]
> I fixed (again ;-)) my PR. Please test it.
> 
> The problem is that `LIBATOMIC=${LIBATOMIC-"-latomic"}` does nothing if the LIBATOMIC variable is already defined. And I defined it to an empty string with `LIBATOMIC=""`.

It works now.

**Comment by vstinner** [comment]
> It works now.

Thanks for testing it!

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/1f7e42131d2800f0fbb89bfd91fafa8a073e066d
