### ISSUE TITLE
test_asyncio, test_imaplib and test_socket fail with FreeBSD TCP blackhole

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109015]
test_asyncio, test_imaplib and test_socket fail with FreeBSD TCP blackhole. When a FreeBSD machine is configured with:

```
sudo sysctl net.inet.tcp.blackhole=2
sudo sysctl net.inet.udp.blackhole=1
```

That's the case by default in FreeBSD GCP image:

* https://github.com/cirruslabs/cirrus-ci-docs/issues/483
* https://reviews.freebsd.org/D41751

I'm working on a PR to skip affected tests with such special configuration.

### Linked PRs
* gh-109016
* gh-109041
* gh-109042

**Comment by emaste** [comment]
I seem to have left my comment in the wrong spot -- sysctl provides a `-n` arg to suppress the name:

```
$ sysctl -n net.inet.tcp.blackhole
0
```
