### ISSUE TITLE
Tests: remove C API tests using @requires_legacy_unicode_capi()?

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109050]
The ``@test.support.requires_legacy_unicode_capi()`` decorators uses ``from _testcapi import unicode_legacy_string``, but this module attribute has been remove since Python 3.12 by commit f9c9354a7a173eaca2aa19e667b5cf12167b7fed, and so all tests using the decorator are now always skipped.

Should we now remove tests using ``@requires_legacy_unicode_capi()`` decorator? Or are these tests kept on purpose?

For example, this test is now always skipped:

```
$ ./python -m test test_capi -m test.test_capi.test_getargs.String_TestCase.test_Z -v

test_Z (test.test_capi.test_getargs.String_TestCase.test_Z) ... skipped 'requires legacy Unicode C API'
```

See also issue #92536 and [PEP 623: Remove wstr from Unicode](https://peps.python.org/pep-0623/).

cc @methane @serhiy-storchaka 

### Linked PRs
* gh-109068

**Comment by serhiy-storchaka** [comment]
I have examined them all, and they do not contain anything that could be tested. The fact that particular format units are errors is already tested in other tests.
