### ISSUE TITLE
Use Kyiv instead of Kiev in test_email

### ISSUE THREAD

**Issue by jspricke** [python/cpython#109017]
# Bug report

### Bug description:

As proposed in #108533 the time zone was renamed but we can't simply rename it in the test cause it fails on old(?) MacOS systems.  I would propose to prepend it with:

```python
@unittest.skipUnless(os.path.exists('/usr/share/zoneinfo/Europe/Kyiv') or
                         os.path.exists('/usr/lib/zoneinfo/Europe/Kyiv'),
                         "Can't find the Olson's TZ database")
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-109251
* gh-111279
* gh-111280

**Comment by corona10** [comment]
@serhiy-storchaka Would you like to take a look since you are the Ukranian?

**Comment by serhiy-storchaka** [comment]
I do not like relying on the particular location of the database. Although it was already here in the existing code, the comment notes that it is not a robust way. Now we have `zoneinfo` in the stdlib, so perhaps it could be used.

**Comment by jspricke** [comment]
@serhiy-storchaka thanks for the proposal, I've updated my PR.
