### ISSUE TITLE
Instantiation of an empty Enum with any value no longer throws `ValueError`

### ISSUE THREAD

**Issue by Fatal1ty** [python/cpython#109022]
# Bug report

### Bug description:

On Python < 3.12 instantiation of an empty `Enum` with any value resulted in `ValueError`, but on 3.12.0rc2 it returns `<enum 'bar'>` without errors. On 3.12.0rc1 it resulted in `TypeError: 'NoneType' object is not iterable` that was addressed in this issue:
* https://github.com/python/cpython/issues/106928

I'm not sure if it's intended or not but just in case, I'll write about it, so that if it's unintended behaviour it could be fixed before the final release. For me `ValueError` was more consistent but I don't see a practical reason to use empty enums anyway and I'm fine if this issue is going to be closed.
```python
class Foo(Enum):
    pass

print(Foo('bar'))
# 3.11: ValueError: 'bar' is not a valid Foo
# 3.12.0rc1: TypeError: 'NoneType' object is not iterable
# 3.12.0rc2: <enum 'bar'>
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-109048
* gh-109122

**Comment by ethanfurman** [comment]
In Python 3.10- the code would check the number of arguments to determine if a member lookup or a functional enum creation was intended.

In Python 3.11+ it decides which path to take based on the presence of members:
- no members defined, must be a functional creation
- members defined, must be a member lookup

We then ended up with the `None is not iterable` in those cases where the functional method was being used to make a new enum class with behavioral changes (i.e. methods), but no new members.

The last bug-fix resolves that issue, but now we have the current issue of creating a new enum class with what looks like a member lookup.

That didn't work before 3.12, so we could certainly go back to making that an error (and perhaps getting better error messages).

**Comment by hugovk** [comment]
Thanks!
