### ISSUE TITLE
Can't access my variable to update it

### ISSUE THREAD

**Issue by Geneticwol97** [python/cpython#109028]
# Bug report

### Bug description:

![Screenshot 2023-09-06 132821](https://github.com/python/cpython/assets/144282338/01162458-e369-461c-a8fa-a91c80684145)

My code:

```py
import pgzrun
cookie = Actor("cookie")
def draw():
    screen.clear()
    cookie.draw()
def placecookie():
    cookie.x = 300
    cookie.y = 200
placecookie()
clix = 0
def on_mouse_down(pos):
    if cookie.collidepoint(pos):
---->clix += 1
        print(clix)
        print("Clicks! Wow!")
        placecookie()
pgzrun.go()
```

Python can't access my variable, I think it's a bug. I installed pgzero and tested it, and it worked fine with clicks = clix += 1.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
Hi! This isn't a bug in Python; this is just how scoping in Python works. Your `on_mouse_down()` function is trying to be both a local variable and a global variable at the same time. If you'd like more help understanding this topic, I recommend you read a tutorial on scoping in Python, or ask on discuss.python.org; the GitHub issue tracker is not a help forum.
