### ISSUE TITLE
test_asyncgen fails randomly on Windows

### ISSUE THREAD

**Issue by vstinner** [python/cpython#109067]
```
FAIL: test_async_gen_asyncio_gc_aclose_09 (test.test_asyncgen.AsyncGenAsyncioTest.test_async_gen_asyncio_gc_aclose_09)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncgen.py", line 1075, in test_async_gen_asyncio_gc_aclose_09
    self.assertEqual(DONE, 1)
AssertionError: 0 != 1
```

and then:

```
Re-running test_asyncgen in verbose mode (matching: test_async_gen_asyncio_gc_aclose_09)
test_async_gen_asyncio_gc_aclose_09 (test.test_asyncgen.AsyncGenAsyncioTest.test_async_gen_asyncio_gc_aclose_09) ... FAIL
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<<async_generator_athrow without __name__>()> wait_for=<Future finished result=None>>

======================================================================
FAIL: test_async_gen_asyncio_gc_aclose_09 (test.test_asyncgen.AsyncGenAsyncioTest.test_async_gen_asyncio_gc_aclose_09)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "D:\a\cpython\cpython\Lib\test\test_asyncgen.py", line 1075, in test_async_gen_asyncio_gc_aclose_09
    self.assertEqual(DONE, 1)
AssertionError: 0 != 1

----------------------------------------------------------------------
Ran 1 test in 0.206s

FAILED (failures=1)
test test_asyncgen failed
```

build: https://github.com/python/cpython/actions/runs/6105856789/job/16569987356?pr=109060

### Linked PRs
* gh-109142
* gh-109149
* gh-109150

**Comment by vstinner** [comment]
This bug is failing randomly since at least 2019:

* https://github.com/python/cpython/issues/76827
* https://github.com/python/cpython/issues/79941
* https://github.com/python/cpython/issues/80297

Time to time, a new ticket is opened, and then closed by the lack of time to dig into it. Since the bug failure rate is low, people tend to ignore it, until it comes back :-)

**Comment by kumaraditya303** [comment]
Should be fixed by https://github.com/python/cpython/pull/109142

**Comment by vstinner** [comment]
Thanks a lot for the fix @kumaraditya303.

**Comment by kumaraditya303** [comment]
> Thanks a lot for the fix

Yeah, seems I fixed 5 year old bug in 5 minutes ;)

**Comment by vstinner** [comment]
> Yeah, seems I fixed 5 year old bug in 5 minutes ;)

That's being called "being efficient"! And with ``asyncio.sleep(0)``!

Note: [never use time as a synchronization primitive](https://pythondev.readthedocs.io/unstable_tests.html#don-t-use-sleep-as-synchronization), it only leads to unstable tests. I'm talking about the test before your fix. But apparently, ``asyncio.sleep(0)`` is reliable for asyncio unit tests. ``asyncio.sleep(0)`` is special, it doesn't rely on a clock, just on event scheduling in asyncio.
