### ISSUE TITLE
Ensure only one wheel for each vendored package in `verify_ensurepip_wheels.py`

### ISSUE THREAD

**Issue by ambv** [python/cpython#109002]
We've had two cases of old wheels not being removed while a new one is added. This lead to CI failures on the affected branches, which required a fix afterwards like gh-108998.

Let's fix it by making the tool complain if there's more than one wheel present.

Reported by @edmorley.

### Linked PRs
* gh-109003
* gh-109005
* gh-109006
* gh-109007
* gh-109008
* gh-109009

**Comment by webknjaz** [comment]
Related: https://github.com/python/cpython/pull/109245

**Comment by hugovk** [comment]
That's a lot of backports! Thanks!
