### ISSUE TITLE
Limited API tests are now incorrectly skipped unconditionally

### ISSUE THREAD

**Issue by andersk** [python/cpython#109045]
Commit 13a00078b81776b23b0b6add69b848382240d1f2 (#108663, cc @vstinner) made all Python builds compatible with the Limited API, and removed the `LIMITED_API_AVAILABLE` flag. However, some tests are still checking for that flag, so they are now being incorrectly skipped.

https://github.com/python/cpython/blob/3bfa24e29f286cbc1f42bdb4d2b1c0c9d643c8d6/Modules/_testcapimodule.c#L4000-L4010

https://github.com/python/cpython/blob/3bfa24e29f286cbc1f42bdb4d2b1c0c9d643c8d6/Lib/test/support/__init__.py#L1088-L1094

### Linked PRs
* gh-109046

**Comment by vstinner** [comment]
I'm now curious. How did you notice that some tests were always skipped?

**Comment by vstinner** [comment]
Before:

```
./python -m test test_capi 
(...)
Total tests: run=668 skipped=13
Total test files: run=1/1
Result: SUCCESS
```

After:

```
./python -m test test_capi 
(...)
Total tests: run=669 skipped=6
Total test files: run=1/1
Result: SUCCESS
```

I can see that there are less skipped tests :-) By the way, remaining skips:

```
$ ./python -m test test_capi -v|grep 'skipped '
test_Z (test.test_capi.test_getargs.String_TestCase.test_Z) ... skipped 'requires legacy Unicode C API'
test_Z_hash (test.test_capi.test_getargs.String_TestCase.test_Z_hash) ... skipped 'requires legacy Unicode C API'
test_u (test.test_capi.test_getargs.String_TestCase.test_u) ... skipped 'requires legacy Unicode C API'
test_u_hash (test.test_capi.test_getargs.String_TestCase.test_u_hash) ... skipped 'requires legacy Unicode C API'
test_trashcan_python_class1 (test.test_capi.test_misc.CAPITest.test_trashcan_python_class1) ... skipped "resource 'cpu' is not enabled"
test_trashcan_python_class2 (test.test_capi.test_misc.CAPITest.test_trashcan_python_class2) ... skipped "resource 'cpu' is not enabled"
```

**Comment by vstinner** [comment]
I created issue #109050 for ``skipped 'requires legacy Unicode C API'`` tests.

**Comment by andersk** [comment]
> I'm now curious. How did you notice that some tests were always skipped?

I actually found this from the source—during an unrelated investigation I noticed that changes to `heaptype_relative.c` and `vectorcall_limited.c` had no effect even when introducing deliberate compile errors.

(The unrelated investigation is into the feasibility of `const`-marking fields like `tp_methods`, `tp_members`, `tp_getset`, `m_ml`, `m_methods`, `m_slots` so that we can conveniently move a bunch of structs with function pointers to read-only memory for slightly improved [security hardening](https://lkml.org/lkml/2010/11/7/113).)

**Comment by vstinner** [comment]
> had no effect even when introducing deliberate compile errors

It's always good to test the tests by injecting errors on purpose and making sure that... they fail :-) Especially during development!
