### ISSUE TITLE
Data classes - nonequivalence in case of adding a default value (creating a class with __init__() vs creating a dataclass)

### ISSUE THREAD

**Issue by and0sha** [python/cpython#109185]
# Bug report

### Bug description:

https://github.com/python/cpython/blob/main/Lib/dataclasses.py
https://docs.python.org/3.11/library/dataclasses.html

```python
from dataclasses import dataclass

@dataclass
class InventoryItem:
    name: str
    unit_price: float
    quantity_on_hand: int = 0


apple = InventoryItem(name='apple', unit_price=5, quantity_on_hand=2)
assert apple.name == 'apple'
assert apple.quantity_on_hand == 2
assert InventoryItem.quantity_on_hand == 0 
```
- Did the developers plan this behavior?
- The class has an attribute (due to the default value in the dataclass).
- This is not equivalent to creating a class with `__init__()`
- InventoryItem.quantity_on_hand must throw AttributeError (like InventoryItem.name - AttributeError)

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux, Windows

**Comment by sobolevn** [comment]
Yes, it is expected :)
