### ISSUE TITLE
incorrect SyntaxError

### ISSUE THREAD

**Issue by mqyhlkahu** [python/cpython#109120]
# Bug report

### Bug description:

The following input will cause a `SyntaxError`.  That's all well and good, but the message for the `SyntaxError` is incorrect.
```python
f(A,*)
```
```python
SyntaxError: iterable argument unpacking follows keyword argument unpacking
```
This is not correct.  That error message is intended for cases like this `f(**kwargs, *args)`.
This bug is present on `3.9`, `3.10`, and `3.11`.  I haven't tested `3.12`, but I suspect that it is present there as well.  The bug is not present on `3.8`.

### CPython versions tested on:

3.8 3.9, 3.10, 3.11

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-117444
* gh-117464
* gh-117465

**Comment by ambv** [comment]
Yeah, no changes in 3.12 and `main` for the error message.

**Comment by sobolevn** [comment]
On 3.8 it used to be just:

```
  File "main.py", line 2

    f(A,*)

         ^

SyntaxError: invalid syntax

```

**Comment by terryjreedy** [comment]
Should the backports be merged?
