### ISSUE TITLE
Missed keyword in keyword  module

### ISSUE THREAD

**Issue by MehdiGhahremani** [python/cpython#109145]
# Bug report

### Bug description:

```python
import keyword as k
k.iskeyword("range")
False
```
Please add "range" keyword to kwlist in keyword module 
I fixed it in my computer :)
Thanks

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
``range`` is not a keyword but a built-in function.

**Comment by terryjreedy** [comment]
Please ask about possible bugs somewhere else, such as https://discuss.python.org/c/users/7.
