### ISSUE TITLE
Replace _PyFrame_OpAlreadyRan by a check for incomplete frame

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#109176]
The ``_PyFrame_OpAlreadyRan`` function in frameobject.c is not covered by any tests.

For details see https://github.com/faster-cpython/ideas/issues/623.

### Linked PRs
* gh-119234

**Comment by ericsnowcurrently** [comment]
Here's a demonstration of the (unlikely?) case for which `_PyFrame_OpAlreadyRan()` was added:

```python
def spam(a, b, c):
    def eggs():
        return a, b, c
    return eggs

args = (1, 2, 3)
eggs1 = spam(*args)
print(eggs1.__closure__)
assert all(v is c.cell_contents for v, c in zip(args, eggs1.__closure__))

args = eggs1.__closure__
eggs2 = spam(*args)
print(eggs2.__closure__)
assert all(c not in eggs2.__closure__ for c in args)
assert all(v is c.cell_contents for v, c in zip(args, eggs2.__closure__))
```

However, this only needs `_PyFrame_OpAlreadyRan()` if it's possible to interrupt the eval loop *before* all `MAKE_CELL` instructions have executed.  Per https://github.com/faster-cpython/ideas/issues/623#issuecomment-1715658784, it sounds like such a case is not possible.  Thus, we might not have any way to add a test where `_PyFrame_OpAlreadyRan()` ever returns false.  (We may end up removing `_PyFrame_OpAlreadyRan()` instead.)

@markshannon, could you verify that the eval loop can't be interrupted before all `MAKE_CELL` instructions have executed?

**Comment by ericsnowcurrently** [comment]
Regardless, it *would* make sense to add a test that does something like the code I posted above.

**Comment by iritkatriel** [comment]
There could perhaps also be a pure C example.

**Comment by iritkatriel** [comment]
Changed the title to reflect the decision in the discussion beginning with https://github.com/faster-cpython/ideas/issues/623#issuecomment-1717915148.

**Comment by iritkatriel** [comment]
@markshannon points out that this frame cannot be incomplete because it comes from a PyFrameObject (in PyFrame_GetVar). So we will just replace the check by an assertion.
