### ISSUE TITLE
Why did the developers add deepcopy to asdict, but did not add it to _field_init (for safer creation of default values via default_factory)?

### ISSUE THREAD

**Issue by and0sha** [python/cpython#109193]
# Bug report

### Bug description:

Why did the developers add deepcopy to asdict, but did not add it to _field_init (for safer creation of default values via default_factory)?

```python
from typing import List
from dataclasses import dataclass, field, asdict


@dataclass
class Viewer:
    Name: str


Default_users = [Viewer('Admin')]


@dataclass
class Films:
    Title: str
    Viewers: List[Viewer] = field(default_factory=lambda: Default_users)


film_1 = Films('Satan-tango')
film_2 = Films('Mirror')
film_1_dict = asdict(film_1)
film_2_dict = asdict(film_2)
film_1.Viewers.append(Viewer('Andrey'))
film_1_dict['Viewers'].append(Viewer('Guido'))
assert film_1 == Films(Title='Satan-tango', Viewers=[Viewer(Name='Admin'), Viewer(Name='Andrey')])
assert film_2 == Films(Title='Mirror', Viewers=[Viewer(Name='Admin'), Viewer(Name='Andrey')])
assert film_1_dict == {'Title': 'Satan-tango', 'Viewers': [{'Name': 'Admin'}, Viewer(Name='Guido')]}
assert film_2_dict == {'Title': 'Mirror', 'Viewers': [{'Name': 'Admin'}]}
```
The viewer Andrey is added to two films. Everything is correct in the dict version.
https://github.com/python/cpython/blob/75cd86599bad05cb372aed9fccc3ff884cd38b70/Lib/dataclasses.py#L498
If this line is replaced with this - `globals[default_name]` = lambda: `copy.deepcopy(f.default_factory()),` then everything will be correct

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux, Windows

**Comment by ronaldoussoren** [comment]
This is not the right place to ask questions like this, please use the [python forum](https://discuss.python.org/c/users/7) for that.

The current behaviour is as documented and is intentional.

**Comment by Zlmrfi** [comment]
@ronaldoussoren Thank you for advice. https://discuss.python.org/t/why-did-the-developers-add-deepcopy-to-asdict-but-did-not-add-it-to-field-init-for-safer-creation-of-default-values-via-default-factory/33475
