### ISSUE TITLE
Run mypy on `Tools/wasm`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109125]
# Feature or enhancement

Right now we already have 3 fully typed and checked tools:
- https://github.com/python/cpython/issues/104050
- https://github.com/python/cpython/issues/108455
- https://github.com/python/cpython/issues/104504

I think we can also add `Tools/wasm` quite easily to this list.
`Tools/wasm` already has most of the type annotations, but there are some mypy errors to fix.

### Linked PRs
* gh-109126
* gh-109561

**Comment by brettcannon** [comment]
I'm not sure if it's worth keeping a couple of scripts typed, especially based on the restrictions of typing in the repo (e.g., older versions of Python w/o `typing_extensions` access, etc.). I honestly would be fine stripping out the types in the scripts in that directory rather than try to keep the types working.

**Comment by corona10** [comment]
We may need to define the scope of what scripts would be worth adding typing, and applying mypy pipeline.

cc @AlexWaygood @erlend-aasland @vstinner

**Comment by AlexWaygood** [comment]
> We may need to define the scope of what scripts would be worth adding typing, and applying mypy pipeline.

I'm not sure this needs to be formalised much. I think we should add mypy to CI for self-contained CPython projects where the maintainers of those projects say they'd find it useful. We should avoid doing so for projects where the maintainers of those projects say it wouldn't be useful.

**Comment by vstinner** [comment]
Once I will be done with refactoring libregrtest https://github.com/python/cpython/issues/109162 I will need help to add type hints there ;-) IMO it would be a more interesting target than Tools/wasm/ scripts.

**Comment by hugovk** [comment]
Done via https://github.com/python/cpython/pull/109126, thanks!
