### ISSUE TITLE
`ssl.SSLObject` and `ssl.SSLSocket` should expose method to get certificate chain

### ISSUE THREAD

**Issue by matiuszka** [python/cpython#109109]
# Feature or enhancement

### Proposal:

Being able to get a certificate chain is needed to perform OCSP revocation checks.
Starting from `py3.10` we can at least call C-level API directly, but I guess such a crucial functionality should be documented and exposed in Python API:
```python
ssl_socket._sslobj.get_unverified_chain()
```

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-109113

**Comment by gpshead** [comment]
Thanks for the contribution!
