### ISSUE TITLE
misleading SyntaxError (f-string and type alias related)

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#109114]
# Bug report

### Bug description:

The following code produces a misleading syntax error.

```python
lambda name_3=f'{name_4}': {name_3}

type {}[name_4] = {}

```

output (Python 3.12.0rc2+):
```python
  File "/home/frank/projects/pysource-codegen/bug.py", line 1
    lambda name_3=f'{name_4}': {name_3}
    ^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: f-string: lambda expressions are not allowed without parentheses
```
The first line should be valid python syntax and I would expect to get an syntax error for the wrong type alias name.

side note:
This is generated code. I found this issue during my work for the python 3.12 support for pysource-codegen.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109121
* gh-109155

**Comment by AlexWaygood** [comment]
> The first line should be valid python syntax

Cc. @pablogsal

> and I would expect to get an syntax error for the wrong type alias name.

Cc. @JelleZijlstra

**Comment by JelleZijlstra** [comment]
The wrong type alias does produce a syntax error when you put it by itself:

```
>>> type {}[name_4] = {}
  File "<stdin>", line 1
    type {}[name_4] = {}
         ^
SyntaxError: invalid syntax
```

I suspect there's some wrong heuristic in the parser where it simply shows the SyntaxError in the wrong place. That's outside my area of expertise though, so I'll leave this to Pablo.

**Comment by pablogsal** [comment]
The problem is that the parser finds the issue in the error pass with the lambda first, even if is correct
