### ISSUE TITLE
Replace the old `getopt` with `argparse` in pdb CLI

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#109164]
# Feature or enhancement

### Proposal:

`pdb` is using `getopt` for argument parsing. `getopt` is pretty old and not well maintained. Some issue in #108791 could be avoided with the modern `argparse` module. We should replace `getopt` with `argparse` when it's easy to do so. This might ease the load in the future when more arguments are added to the CLI.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-109165

**Comment by serhiy-storchaka** [comment]
Actually, `getopt` is stable and `argparse` has many bugs (some of them are design flaws).

**Comment by ericvsmith** [comment]
I agree that `argparse` has many problems and isn't the best choice. And this is coming from someone who was pushing to get it in the stdlib.

**Comment by gaogaotiantian** [comment]
`getopt` is soft deprecated since 3.13. It doesn't mean that we can't use it, it's just we should try to use actively maintained stdlib. Also the CLI for `pdb` is not that complicated. I agree there are issues with `argparse`, but there are issues with `getopt` as well (see the linked issue). I believe CPython will always have a CLI parser in its stdlib. It's `argparse` now but maybe in the future there will be a better designed alternative, we can switch to that then.
