### ISSUE TITLE
Notes added to "SyntaxError" (and subclasses) are not displayed

### ISSUE THREAD

**Issue by Delgan** [python/cpython#109179]
# Bug report

### Bug description:

Hi.

I noticed that using [`add_note()`](https://docs.python.org/3/library/exceptions.html#BaseException.add_note) with an error of type `SyntaxError` (or its derived such as `IndentationError` and `TabError`) produces a traceback without the expected notes.

Here is a minimal reproducible example:
```python
try:
    exec("a = 7 *")
except SyntaxError as e:
    e.add_note("Note")
    raise
```
Or alternatively:

```python
e = SyntaxError("invalid syntax", ("<string>", 1, 8, "a = 7 *\n", 1, 8))
e.add_note("Note")
raise e
```

The output of these examples is:

```python
Traceback (most recent call last):
  File "/home/delgan/test.py", line 2, in <module>
    exec("a = 7 *")
  File "<string>", line 1
    a = 7 *
           ^
SyntaxError: invalid syntax
```

The expected `"Note"` is missing.

Since neither PEP 678 nor the documentation mention that `SyntaxError` is not fully compatible with notes, I assume that this is probably a bug.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109197
* gh-109280
* gh-109283

**Comment by terryjreedy** [comment]
Test code above works with IndexError, for instance.  The `.__notes__` attribute is added but not used.
@iritkatriel You added this and its doc.

**Comment by iritkatriel** [comment]
Thanks, this is a bug. SyntaxError is handled differently and it drops the notes. Fixed in https://github.com/python/cpython/pull/109197.
