### ISSUE TITLE
Remove INSTRUCTION event monitoring will remove LINE events as well

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#109156]
# Bug report

### Bug description:

The current de-instrumentation code for instructions incorrectly de-instruments line too. So if INSTRUCTION events are removed, event if the LINE events are still there, it won't trigger the event.

```python
import sys
E = sys.monitoring.events

def line(*args):
    print("Line event: ", args)

def inst(*args):
    print("Instruction event: ", args)

sys.monitoring.use_tool_id(0, "test")
sys.monitoring.set_events(0, 0)
sys.monitoring.register_callback(0, E.LINE, line)
sys.monitoring.register_callback(0, E.INSTRUCTION, inst)
sys.monitoring.set_events(0, E.LINE | E.INSTRUCTION)
sys.monitoring.set_events(0, E.LINE)
a = 1
sys.monitoring.set_events(0, 0)
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-109157
* gh-109384

**Comment by markshannon** [comment]
https://github.com/python/cpython/pull/109131 fixes this.
We should add the test in #109157 though.

**Comment by gaogaotiantian** [comment]
> #109131 fixes this. We should add the test in #109157 though.

Do you want me to only keep the test in the PR? I can rename the PR to "add tests" and maybe skip the news?

**Comment by markshannon** [comment]
Fixed
