### ISSUE TITLE
The docs of "traceback.format_exception_only" is incorrect when the Exception has notes

### ISSUE THREAD

**Issue by Delgan** [python/cpython#109184]
# Documentation

The documentation of [`traceback.format_exception_only`](https://docs.python.org/3.11/library/traceback.html#traceback.format_exception_only) states the following (emphasis mine):

> Format the exception part of a traceback using an exception value such as given by `sys.last_value`. The return value is a list of strings, each ending in a newline. Normally, the list contains a single string; however, for [SyntaxError](https://docs.python.org/3.11/library/exceptions.html#SyntaxError) exceptions, it contains several lines that (when printed) display detailed information about where the syntax error occurred. **The message indicating which exception occurred is the always last string in the list.**

The last string isn't always the formatted `Exception` instance. Actually, the last string can be any arbitrary string if notes are added to the `Exception`, as demonstrated by the following example:

```python
import traceback


e = ValueError("The error")
e.add_note("Notes:\n1. Part 1\n2. Part 2")

output = traceback.format_exception_only(e)
print(output)
```

The `output` is actually a list of 4 elements, with the message representing the raised `Exception` being in first position:

```python
['ValueError: The error\n', 'Notes:\n', '1. Part 1\n', '2. Part 2\n']
```

This also applies to the documentation of [`TracebackException.format_exception_only`](https://docs.python.org/3.11/library/traceback.html#traceback.TracebackException.format_exception_only).

### Linked PRs
* gh-109201
* gh-109334
* gh-109336

**Comment by terryjreedy** [comment]
@iritkatriel

**Comment by iritkatriel** [comment]
Thank you. "Normally, the list contains a single string" is also no longer true.

**Comment by iritkatriel** [comment]
Is this better? https://github.com/python/cpython/pull/109201

**Comment by Delgan** [comment]
> Is this better? #109201

Looks good and accurate! Thanks for the update. :+1:
