### ISSUE TITLE
Invalid "equivalents" of the complex type constructor in docs

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#109218]
The sphinx docs says:
```
class complex(real=0, imag=0)
[...]
Return a complex number with the value real + imag*1j or convert a string or number to a complex number.
[...]
```
The docstring (btw it doesn't mention a string as an argument):
```
>>> print(complex.__doc__)
Create a complex number from a real part and an optional imaginary part.

This is equivalent to (real + imag*1j) where imag defaults to 0.
```

That wrong, e.g.:
```pycon
>>> complex(0.0, -0.0)
-0j
>>> 0.0 + (-0.0)*1j
0j
>>> complex(-0.0, -0.0)
(-0-0j)
>>> -0.0 + (-0.0)*1j
(-0+0j)
>>> complex(-0.0, 0.0)
(-0+0j)
>>> -0.0 + 0.0*1j
0j
```

<details>
<summary>Here is an attempt (patch) to solve, let me know if this is worth a PR:</summary>

```diff
diff --git a/Doc/library/functions.rst b/Doc/library/functions.rst
index d9974c6350..78b85658ef 100644
--- a/Doc/library/functions.rst
+++ b/Doc/library/functions.rst
@@ -373,8 +373,8 @@ are always available.  They are listed here in alphabetical order.
 .. class:: complex(real=0, imag=0)
            complex(string)

-   Return a complex number with the value *real* + *imag*\*1j or convert a string
-   or number to a complex number.  If the first parameter is a string, it will
+   Create a complex number from a real part and an optional imaginary part
+   or convert a string to a complex number.  If the first parameter is a string, it will
    be interpreted as a complex number and the function must be called without a
    second parameter.  The second parameter can never be a string. Each argument
    may be any numeric type (including complex).  If *imag* is omitted, it
diff --git a/Objects/complexobject.c b/Objects/complexobject.c
index 0e96f54584..336b703233 100644
--- a/Objects/complexobject.c
+++ b/Objects/complexobject.c
@@ -886,9 +886,8 @@ complex.__new__ as complex_new
     real as r: object(c_default="NULL") = 0
     imag as i: object(c_default="NULL") = 0

-Create a complex number from a real part and an optional imaginary part.
-
-This is equivalent to (real + imag*1j) where imag defaults to 0.
+Create a complex number from a real part and an optional imaginary part
+or convert a string to a complex number.
 [clinic start generated code]*/

 static PyObject *
```
</details>

**Edit**:
Another instance of this issue is in the [cmath docs](https://docs.python.org/3/library/cmath.html#conversions-to-and-from-polar-coordinates):
```rst
A Python complex number ``z`` is stored internally using *rectangular*
or *Cartesian* coordinates.  It is completely determined by its *real
part* ``z.real`` and its *imaginary part* ``z.imag``.  In other
words::

   z == z.real + z.imag*1j
```
E.g.:
```pycon
>>> from cmath import inf
>>> complex(0.0, inf)
infj
>>> 0.0 + inf*1j
(nan+infj)
```

### Linked PRs
* gh-119620
* gh-119635
* gh-119687
* gh-119795
* gh-119796
* gh-119803
* gh-119805

**Comment by pochmann** [comment]
> The sphinx docs says:
> 
> ```
> class complex(real=0, imag=0)
> [...]
> Return a complex number with the value real + imag*1j or convert a string or number to a complex number.
> [...]
> ```

It's not actually styled like that but like this:

> Return a complex number with the value *real* + *imag*\*1j or [...]

Not like this:

> Return a complex number with the value `real + imag*1j` or [...]

So at least to me, that looks like math, not like code, and then it's correct (because in math, typically ["−0, +0 and 0 are identical"](https://en.wikipedia.org/wiki/Signed_zero?wprov=sfla1)). Similar to how `0.1` isn't 0.1 (but 0.1000000000000000055511151231257827021181583404541015625). Style tells how to interpret things.

The docstring is ambiguous, though, as I think it's raw style-less text so doesn't even have the capacity to style as code, so it can be interpreted as such. And then it could be wrong, depending on the interpretation of the word "equivalent" there, which doesn't necessarily mean it needs to do the 100% exact same thing. For example [`enumerate`](https://docs.python.org/3/library/functions.html#enumerate) is also documented to be "equivalent" to some Python code shown there, even though that doesn't even return the same *type* (not an `enumerate object` but a `generator object`).

**Comment by AA-Turner** [comment]
See also https://discuss.python.org/t/33433/

A

**Comment by mdickinson** [comment]
Note that the two arguments to `complex` can themselves be complex numbers, so describing them as the real and imaginary part isn't always accurate:

```
>>> complex(1+2j, 1-2j)
(3+3j)
```

**Comment by skirpichev** [comment]
> two arguments to ``complex`` can themselves be complex numbers

Indeed, but in this form the "equivalency" ``complex(r, i) == r + i*1j`` is also broken:
```pycon
>>> complex(r := nan-infj, i := -inf+infj)
(nan-infj)
>>> r + i*1j
(nan+nanj)
>>> complex(r := -0.0-0j, i := 1+0j)
(-0+1j)
>>> r + i*1j
1j
```
Under the hood, instead, we have:
```pycon
>>> complex(r.real - i.imag, i.real + r.imag)
(-0+1j)
```

> describing them as the real and imaginary part isn't always accurate

It's used in the current docstring, anyway.

Lets decide, however, whether this is a bug, regardless from the outcome in the mentioned discussion.  Or not (as for ``complex`` vs ``eval(repr(complex))``).

**Comment by skirpichev** [comment]
@mdickinson, does this looks as an issue for you or we should accept imprecise docs?  I don't see good ways to reword docs, while keeping them short and expressive.

Not sure, if this is a good idea to revival the d.p.o thread.  On another hand, mentioned in the d.p.o variant with the imaginary type isn't explored well.  Here is an implementation of the imaginary type & mixed-mode arithmetic rules: https://github.com/skirpichev/cpython/pull/1  Among others, that should address current issue.
@serhiy-storchaka, do you think that it worth to discuss this proposal as a PEP?

So far major arguments against were:
- (a) it’s a fairly large and involved change in comparison to the size of the problem it’s solving
- (b) adoption of the C99 imaginary types has been disappointing

I think that above implementation is more or less complete to estimate (a): so far most changes limited to arithmetic methods.  (b) - this looks to be a strong one.  On another hand, this feature of the C99+ standards is optional - that might be an explanation of partial adoption, while in the Python - complex arithmetic is a part of the language.  For numeric C libraries, the GSL, for example, has own routines to do mixed-mode arithmetic...

**Comment by serhiy-storchaka** [comment]
Currently the signature of complex is:
```
complex(real=0, imag=0)
```
Both `real` and `imag` are positional-or-keyword parameters. This allows absurd calls like `complex(real="1j")`.

I think that it should support several more limited signatures:
* `complex(number=0, /)`
* `complex(string, /)`
* `complex(real=0, imag=0)`

A string and complex number arguments should only be passed as a positional argument. `real` and `imag` should only be real numbers.

**Comment by skirpichev** [comment]
@serhiy-storchaka, yes I think this could solve the current issue like proposed in it's description.  (I.e. we should remove all mentions of broken identities.)

At price of breaking compatibility.  It seems, support for imaginary arguments exists since v2.2 (6d6c1a35e08).  Not sure on what ground it was added, I doubt it's practically used.

> This allows absurd calls like complex(real="1j").

... on another hand it might be viewed as a bug.

Shall I open a separate issue or it would be better to discuss this first on d.p.o?

**Comment by mdickinson** [comment]
> I think that it should support several more limited signatures:

+1. I'd particularly like to see the form `complex(1 + 1j, 3 - 4j)` deprecated, and eventually dropped.

**Comment by serhiy-storchaka** [comment]
I think this is the right issue, and no need to open another issue. My plan:

* Document the current behavior more accurately (without focusing on passing a string as the "real" keyword argument). The docstring may be more brief and do not include weird cases. This change should be backported.
* Make passing a string as the "real" keyword argument an error. I do not think any deprecation is needed here. It looks like just an implementation artifact.
* Deprecate accepting complex numbers as "real" and "image" arguments. This is the old behavior, since introduction of the `complex()` builtin in 1.4 (8a5c5d277eba096c4f12fdcdf5b3550d63f6bc56), but I do not think there is a use case for this. Accepting a complex number as the "real" argument could be an implementation artifact, but I have no explanation for accepting a complex number as the "imag" argument.

 #119620 implements the last two items.

**Comment by serhiy-storchaka** [comment]
The tests for the `complex()` constructor currently are a mess, they were not cleaned up after Python 2, and some interesting cases are not covered. I refactor them in #119635, it is better to merge it before #119620.

**Comment by serhiy-storchaka** [comment]
And #119687 is the documentation part. It adds more details and avoids using the `real+imag*1j` expression, which can be incorrect in corner cases. It uses a vague wording for parts which are planned for deprecation.

**Comment by serhiy-storchaka** [comment]
Thank you for your reviews @skirpichev and @mdickinson.
