### ISSUE TITLE
Way to hibernate code/resume code

### ISSUE THREAD

**Issue by x-0D** [python/cpython#109220]
Is there proper way to save current call stack and globals/locals for each frame, so it can be restored further from the line where program stopped?

I'm trying to implement execution checkpoints (snapshots/time_travel) with save_state() and load_state() funcs. There are pickle and dill to save globals and locals, but I don't see the way to save/resume execution frames stack.

(Maybe inspection.get_currentframe() will help to save line_no and code filename recursive until f_back is None, but I don't know how to restore saved data in right way.)

Please, mark it as feature request or give a hint how to implement (theoretically) this functionaliny.

**Comment by AA-Turner** [comment]
Consider opening a discussion on https://discuss.python.org/

A

**Comment by terryjreedy** [comment]
This is not a place to ask for help and new feature need prior discussion to refine to something specific.
https://discuss.python.org/c/users/7 or other fora such as stackoverflow to ask for help, hints, etc.
https://discuss.python.org/c/ideas/6 to discuss new feature ideas.
I am pretty sure that there has been previous discussion of this topic.
