### ISSUE TITLE
Enhance `sqlite3` connection context management documentation with `contextlib.closing`

### ISSUE THREAD

**Issue by d33bs** [python/cpython#109234]
This issue covers an opportunity to enhance the existing [`sqlite3` docs on context management](https://docs.python.org/3/library/sqlite3.html#sqlite3-connection-context-manager) by adding a mention of [`contextlib.closing`](https://docs.python.org/3/library/contextlib.html#contextlib.closing) to help guide developers when performing singular transactions. Adding this section to the documentation would help guide developers in use cases where they'd like to close the `sqlite3` connection without an additional `sqlite.connect().close()` after a context manager closes.

For default `sqlite3` context management cases which don't use `contextlib.closing` we could outline or strengthen existing mention that the intention is to perform multiple transactions without fully closing the connection. This might help distinguish development options / decision-making for Python developers reading through the documentation.

A `contextlib.closing` example we could include:

```python
import sqlite3
from contextlib import closing

with closing(sqlite3.connect("workfile.sqlite")) as cx:
    with cx:
        cx.execute("CREATE TABLE lang(id INTEGER PRIMARY KEY, name VARCHAR UNIQUE)")
        cx.execute("INSERT INTO lang(name) VALUES(?)", ("Python",))

# no need to close the connection as contextlib.closing closed it for us
``` 

Related to [a discussion from discuss.python.org](https://discuss.python.org/t/implicitly-close-sqlite3-connections-with-context-managers/33320). Many thanks to @erlend-aasland for suggesting the `contextlib.closing` approach and the others in the discussion thread for their help in discussing this topic.

### Linked PRs
* gh-109322
* gh-110293
* gh-110294

**Comment by Lincoln-developer** [comment]
Hey, greetings !
well, I am requesting to take on this issue though still a newbie.

**Comment by merwok** [comment]
Please do!  You can read https://devguide.python.org/ for instructions and use the core-mentorship group to get help.

**Comment by nanjekyejoannah** [comment]
The closing bit was added, please reopen if the PR didn't address everything.

**Comment by AA-Turner** [comment]
Should the PR be backported?

A

**Comment by nanjekyejoannah** [comment]
@erlend-aasland  has handled the backport

**Comment by edcsnt** [comment]
Too bad that no example is provided in the documentation. I had to use a search engine to find the original thread and this issue to read an example.
