### ISSUE TITLE
Broken sys.getrefcount

### ISSUE THREAD

**Issue by timofej673** [python/cpython#109221]
# Bug report

### Bug description:

```python
>>> a = "some string"
>>> sys.getrefcount(a)
4294967295
must be: 2 (on python 3.11.2)
on heads/main:75cd86599b: always 4294967295
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by pochmann** [comment]
Not a bug, clearly explained by the [documentation](https://docs.python.org/3.13/library/sys.html#sys.getrefcount).

**Comment by timofej673** [comment]
> Not a bug, see the [documentation](https://docs.python.org/3.13/library/sys.html#sys.getrefcount).

Sorry

**Comment by ravetisy** [comment]
but why would some random string still have a lot of refcount?
