### ISSUE TITLE
document of msvcrt.kbhit's return value is incorrect

### ISSUE THREAD

**Issue by aisk** [python/cpython#109266]
`msvcrt.kbhit`'s [document](https://docs.python.org/3.11/library/msvcrt.html#msvcrt.kbhit) said:

>     Return True if a keypress is waiting to be read.

But according to it's [clinic function signature](https://github.com/python/cpython/blob/60b8341d07649194aa73108369a1e04ed1848794/PC/msvcrtmodule.c#L221), it should be a type of long. And as the [Microsoft's document](https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/kbhit?view=msvc-170) said it would be a nonzero value if  a key has been pressed.

### Linked PRs
* gh-109267

**Comment by AA-Turner** [comment]
Would it make more sense here to change the return type to ``bool``, if the only valid return values are 0 and 1?

A

**Comment by aisk** [comment]
> Would it make more sense here to change the return type to `bool`, if the only valid return values are 0 and 1?
> 
> xref: https://learn.microsoft.com/en-us/cpp/c-runtime-library/reference/kbhit?view=msvc-170
> 
> A

I just inspect it would only return 0 or 1, but the document said it would returns 0 or any other nonzero values.
