### ISSUE TITLE
SystemError when printing symbol table entry

### ISSUE THREAD

**Issue by yunline** [python/cpython#109207]
# Bug report

### Bug description:

Platform: Windows10
Tested version: 3.10, 3.11, 3.12rc2

```python
import symtable

script = "a=0"

symt = symtable.symtable(script, "test.py", "exec")
print(symt._table)
```

```
<symtable entry top(-1), line 0>OverflowError: Python int too large to convert to C long

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "x:\python\oneliner\__develop\symt.py", line 8, in <module>
    print(symt._table)
SystemError: <built-in method write of _io.TextIOWrapper object at 0x000001508B5559A0> returned a result with an exception set
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-109225
* gh-109227
* gh-109228

**Comment by serhiy-storchaka** [comment]
I can see what the problem can be.

The repr first converts the table id  to C long using `PyLong_AS_LONG()`. But the table id is just the `id()` of the corresponding AST node, and in Python it is an integer representation of pointer. Pointers are 64-bit on 64-bit platform, but C long is 32-bit on Windows. So we get an exception on 64-bit Windows.

Marking this as easy issue, as what you only need is simply remove `PyLong_AS_LONG()`, replace the `%ld` format code with `%S` or `%R`, and add a test and a NEWS entry. Welcome!
