### ISSUE TITLE
Unexpected result when swap elements in list

### ISSUE THREAD

**Issue by cola0405** [python/cpython#109249]
# Bug report

### Bug description:

```python
nums = [1,2,3,4]

# try to swap 2 and 3
nums[1], nums[nums[1]] = nums[nums[1]], nums[1]

print(nums)   # but  the result is [1, 3, 3, 2]
```

I have checked the bytecode and know what's going on, but I think the expression will confuse people.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by pochmann** [comment]
No bug, works as documented. If you think it will confuse people, then don't use it.

**Comment by terryjreedy** [comment]
`nums[nums[1]], nums[1]` is `nums[2], 21` is `3,2`.  Assignment is done left to right.  So `nums[1]` replaces 2 with 3 and `nums[nums[1]]` is `nums[3]` and that gets replaced with 2.  In all, 2 is replaced with 3 and 4 is replaced with 2.

Please ask about possible bugs elsewhere, such as https://discuss.python.org/c/users/7.

**Comment by cola0405** [comment]
emm... well, I just thinking about whether it is necessary to fix this, because it is a well knowed pythonic way to swap variables, then I think this operation should not perform like this.

**Comment by sunmy2019** [comment]
> because it is a well-known pythonic way to swap variables

No, it's not. You should generally avoid using `num[num[1]]` when modifying `num[1]`.

**Comment by sunmy2019** [comment]
You can think of this code

```py
nums = [1, 2, 3, 4]

tmp = (nums[nums[1]], nums[1]) # a tuple

# assert tmp == (3, 2)

nums[1] = tmp[0]
nums[nums[1]] = tmp[1]
```
