### ISSUE TITLE
Segfault with ctypes c_void_p created from casting a CFUNCTYPE

### ISSUE THREAD

**Issue by sklam** [python/cpython#109372]
# Crash report

### What happened?

Running the following script results in `illegal hardware instruction`, `segmentation fault`, or `rosetta error: unsupported privilege level: 1` with python 3.12rc2 on OSX x86 via rosetta on M1.  The same script works fine in py3.11 and py3.9.

Reproducer:

```python
from ctypes import CFUNCTYPE, cast, c_void_p


@CFUNCTYPE(None, c_void_p)
def use_callback(ptr):
    print(ptr)


@CFUNCTYPE(None)
def callback():
    print("The callback was called!")


ptr = cast(callback, c_void_p)
use_callback(ptr)
```

Another reproducer shows that the problem may lie within the handling of `c_void_p` argument to a CFUNCTYPE:

```python
from ctypes import CFUNCTYPE, cast, c_void_p


@CFUNCTYPE(None, c_void_p)
def use_callback(ptr):
    print(ptr)


if True:   # Setting this branch to False "fixes" the problem
    @CFUNCTYPE(None)
    def callback():
        print("The callback was called!")

ptr = c_void_p(32901)
print(ptr)
use_callback(ptr)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Output from running 'python -VV' on the command line:

Python 3.12.0rc2 | packaged by Anaconda, Inc. | (main, Sep  7 2023, 09:13:05) [Clang 14.0.6 ]

**Comment by ronaldoussoren** [comment]
Both scripts works fine for me on an M1 (macOS 13.5.2), Python 3.12rc2 installed using the python.org. Tested with x86_64 and arm64.

Output for the second script:

```
% arch -x86_64 python3.12 repro.py
c_void_p(32901)
32901
```

Behaviour is the same with python3.11 (also installed using the python.org installer)

**Comment by sunmy2019** [comment]
There's also a possibility that something's broken in rosetta.

**Comment by sklam** [comment]
The problem has been resolved. It is a build program related to `-DUSING_APPLE_OS_LIBFFI`.
