### ISSUE TITLE
Logging __init__.py error method does not support extra parameters

### ISSUE THREAD

**Issue by Dubey-Aryaman** [python/cpython#109398]
# Bug report

### Bug description:

```python
logger.error(“some message”, flush=True)
```

On line 1475, 

```python
self._log(ERROR, msg, args, **kwargs)
```

args is missing a "*" 

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by Dubey-Aryaman** [comment]
@ronaldoussoren The python documentation for 3.8 (https://docs.python.org/3.8/library/logging.html) indicates to me the definition for error should include both *args and **kwargs, allowing for a variable num of arguments to the function - but i'm unable to pass extra params to logger.error(), seems to be due to the missing * in front of args

apologies if I am misunderstanding.

**Comment by ronaldoussoren** [comment]
The public APIs (``def error(...)``, ...) accept variable number of arguments through ``*args``, the internal API passes the tuple with variable arguments around.

Is there a reproducer where you cannot pass a variable number of positional arguments to a public API that's documented to accept them?

**Comment by Dubey-Aryaman** [comment]
@ronaldoussoren I'm afraid I don't quite understand the distinction here - I thought I was passing the arguments to the public API by using logger.error(msg, arg1, arg2, ...) 

could you provide an example for passing a variable number of positional arguments to the public API?

**Comment by ronaldoussoren** [comment]
> @ronaldoussoren I'm afraid I don't quite understand the distinction here - I thought I was passing the arguments to the public API by using logger.error(msg, arg1, arg2, ...)
> 
> could you provide an example for passing a variable number of positional arguments to the public API?

``logger.error(msg, arg1, arg2, ...)`` is an example of passing a variable number of positional arguments. Does this not work for you? And if so, what error do you get? 

As @ericvsmith noted ``flush=True`` is not a valid keyword argument for ``logging.error`` only the keyword arguments mentioned in https://docs.python.org/3.8/library/logging.html#logging.debug are valid.

**Comment by Dubey-Aryaman** [comment]
@ericvsmith @ronaldoussoren Thanks for clearing this up for me, I didn't notice flush was not a supported kwarg. Closing the issue.
