### ISSUE TITLE
line tracing depends on prev_instr

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#109333]
Is this is a bug or intended behaviour?

```
def f():
   return 1

def func():
   x = f() + 2
   return x
```

The trace for calling ``func`` looks like this:

```
[(4, 'call'),
 (5, 'line'),
 (1, 'call'),
 (2, 'line'),
 (2, 'return'),
 (6, 'line'),
 (6, 'return')]
```

Note that after returning from f(), there is code executed on line 5 but we don't have a line event because (I think) the prev_instr of the line on func's frame is also 5.  Shouldn't there be another event for line 5 though, since the dynamic previous instruction is different?

**Comment by iritkatriel** [comment]
I'm repurposing this to resolve how we can remove `prev_instr` from line tracing. When we return from a function we need to know which was the last line that was traced in the current frame. If we only have `instr_ptr` which points at the next instruction, we don't know which instruction's line number to look up for comparison with the current line, so we don't know whether we are on a new line.

We need `INSTRUMENTED_LINE` to store the line number somewhere, so that it can compare it with the line number next time it's called. This could be either on the frame, or in the instrumentation data structure (where it would need a map from frame to last_traced_line).  The former is simpler, the latter keeps this within the instrumentation system.

(Once this is done, `INSTRUMENTED_LINE` can move to bytecodes.c.)

**Comment by markshannon** [comment]
`instr_ptr` should point to the currently executing instruction. It can be set at the beginning of each instruction, immediately after dispatch.
```C
frame->instr_ptr = next_instr;
```
`INSTRUMENTED_LINE` needs to know the previously executed instruction.
To do this, we just need to change the prefix to
```C
_Py_CODEUNIT *prev = frame->instr_ptr;
frame->instr_ptr = next_instr;
```
Whether we special case it in `ceval.c`, or let the code generator special case it, seems unimportant.

I see no need to add an extra field to the frame.

**Comment by iritkatriel** [comment]
I see, so instr_ptr should point at the CALL at this point. I think I over-engineered this.
