### ISSUE TITLE
Tier 2 loop detection confused by `except`

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#109378]
I found that the Tier 2 translation gets triggered by a `JUMP_BACKWARD` that doesn't represent a loop. This is from Lib/importlib/_bootstrap.py, function `_get_module_lock()`:
```py
        try:
            lock = _module_locks[name]()
        except KeyError:
            lock = None

        if lock is None:
            ...
```
Because the `except` block is moved to the end of the function, it ends in a `JUMP_BACKWARD` to the `if`. If the function is called enough times and `KeyError` is raised enough times, the optimizer is called and replaces the `JUMP_BACKWARD` with `ENTER_EXECUTOR`. So the rest of the function is executed in Tier 2, but only when `KeyError` is caught.

CC: @markshannon @iritkatriel

**Comment by markshannon** [comment]
I don't really see a problem here.
If the exception handler is hot enough, it should get optimized.
