### ISSUE TITLE
muslinux: Library loaded with `ctypes.cdll.LoadLibrary` does not load symbols for python binding module

### ISSUE THREAD

**Issue by LecrisUT** [python/cpython#109332]
# Bug report

### Bug description:

I am not sure if this was intended to work like that in the first place, but the following works on most linux OS (manylinux I suppose), macos and windows:
```python
import ctypes

ctypes.cdll.LoadLibrary(Path(bundled_lib))           
import _python_binding
```
where the `_python_binding` module is built with `link_libraries` to the one in `bundled_lib`.

Manually setting `rpath` makes it work, so I don't think it's an issue with the symbols themselves, but some issue with how `ctypes.cdll.LoadLibrary` and how the python binding module share the symbols. I have tried to set `ctypes.DEFAULT_MODE` to either ` ctypes.RTLD_GLOBAL` or ` ctypes.RTLD_LOCAL`, but that doesn't seem to change the behaviour.

An example docker container to replicate this issue is:
```dockerfile
FROM python:alpine

RUN apk update
RUN apk add musl-dev gcc linux-headers cmake neovim bash
RUN pip install spglib
```
with the relevant code in `spglib.spglib#58`:
```console
$ python -c "import spglib"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/spglib/__init__.py", line 37, in <module>
    from .spglib import (  # noqa: F401
  File "/usr/local/lib/python3.11/site-packages/spglib/spglib.py", line 67, in <module>
    from spglib import _spglib as spg
ImportError: Error loading shared library libsymspg.so.2: No such file or directory (needed by /usr/local/lib/python3.11/site-packages/spglib/_spglib.cpython-311-x86_64-linux-musl.so)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Other

**Comment by encukou** [comment]
musl is unsupported per PEP-11. (It would be nice to support it, but, people interested in doing the work somehow don't show up around this repo.)

I'll close the bug. Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or work to make it officially supported.
I encourage such people to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping.
