### ISSUE TITLE
Inconsistent behavior when calling or on None and False

### ISSUE THREAD

**Issue by elliotfayman** [python/cpython#109388]
# Bug report

### Bug description:

# Summery
The ```or``` operator in Python displays inconsistent behavior when used with ```None``` and ```False```.

# Steps to Reproduce
1. Evaluate the expression ```None or False```: Returns ```False```
1. Evaluate the expression ```False or None```: Returns ```NoneType```
1. Test more complex expressions like ```None or None or False```: Returns ```False```

# Expected Behavior
The behavior of the ```or``` operator, when combined with ```None``` and ```False```, should always return ```False``` because both ```None``` and ```False``` are Falsey.

# Observed Behavior
In general, appending ```or False``` tends to result in the return value being ```False```. Otherwise, the return type is more often NoneType.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by carljm** [comment]
This is not a bug, it is expected, designed, and desirable behavior. Please look up "short-circuiting" in Python. Boolean operators do not evaluate to `True` or `False`, they evaluate to the actual value of the last-evaluated operand necessary to determine the truthiness of the expression.

**Comment by TeamSpen210** [comment]
`and` / `or` are not directly boolean operations. They are defined closer to the following:
```py
def and(a, b):
    if a:
        return b
    else:
        return a

def or(a, b):
    if a:
        return a
    else:
        return b
```

Except they only evaluate `a` once, and only evaluate `b` if they need to. If you coerce the result to boolean (with `bool()`), it has the same behaviour as what you expect, but this gives them additional use cases. For example, you can do `some_string or 'empty'` to return `"empty"` instead if the string is either empty or `None`. The short circuiting behaviour is often used by doing things like `if value is not None and value.some_method():` - if the value is `None` we don't try to evaluate the method call.

This is [documented behaviour](https://docs.python.org/3/reference/expressions.html#boolean-operations) and isn't going to change.

**Comment by terryjreedy** [comment]
@elliotfayman Please ask questions about behavior you do not understand on https://discuss.python.org/c/users/7 or other help forums.
