### ISSUE TITLE
*.pth file in site-packages not initialize in embedded python

### ISSUE THREAD

**Issue by pokq** [python/cpython#109309]
# Bug report

### Bug description:

see the picture
<img width="1117" alt="2023-09-12 095131" src="https://github.com/python/cpython/assets/115908818/f2a3e922-a738-4fe6-b890-83f94a6dc7fa">

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by aedbce** [comment]
I forget to uncommnet.
