### ISSUE TITLE
Spring cleaning CI workflow logs

### ISSUE THREAD

**Issue by hugovk** [python/cpython#109399]
https://github.com/python/cpython/actions lists the GitHub Actions workflows that have run on the repo:

1. Add issue header
2. [_Bots_](https://github.com/python/cpython/actions/workflows/trigger-bots.yml)
3. Check labels
4. Codespaces Prebuilds
5. Coverage
6. Docs
7. [_Docs_](https://github.com/python/cpython/actions/workflows/reusable-docs.yml)
8. Lint
9. [_Look for missing information_](https://github.com/python/cpython/actions/workflows/call-bedevere.yml)
10. Mark stale pull requests
11. mypy
12. new-bugs-announce notifier
13. Read the Docs PR preview
14. [_Run mypy on Tools/clinic_](https://github.com/python/cpython/actions/workflows/mypy-clinic.yml)
15. Tests
16. TestsMSI
17. Update GH projects
18. [_Verify bundled libexpat_](https://github.com/python/cpython/actions/workflows/verify-expat.yml)
19. Verify bundled wheels

The five in italics are leftovers from PRs and only had between 2-4 runs each before being renamed or removed.

I propose to delete the old logs from those workflows so they're removed from the sidebar, making it easier to navigate to the active ones.

Any objections?

Checklist for removal, and pinging those involved in those old workflow:

- [x] 2. [_Bots_](https://github.com/python/cpython/actions/workflows/trigger-bots.yml) - @waylan @serhiy-storchaka @fbidu
- [x] 7. [_Docs_](https://github.com/python/cpython/actions/workflows/reusable-docs.yml) - @CAM-Gerlach 
- [x] 9. [_Look for missing information_](https://github.com/python/cpython/actions/workflows/call-bedevere.yml) - @arhadthedev 
- [x] 14. [_Run mypy on Tools/clinic_](https://github.com/python/cpython/actions/workflows/mypy-clinic.yml) - @AlexWaygood 
- [x] 18. [_Verify bundled libexpat_](https://github.com/python/cpython/actions/workflows/verify-expat.yml) - @illia-v

**Comment by AlexWaygood** [comment]
> * [ ]  14. [_Run mypy on Tools/clinic_](https://github.com/python/cpython/actions/workflows/mypy-clinic.yml) - @AlexWaygood

Seems like a good idea in general, and no objections from me on this one specifically! I think those are just the runs from the first few commits on the PR that originally introduced the mypy check to CI — but the workflow was renamed before the PR was merged, IIRC!

**Comment by hugovk** [comment]
No objections in a week for the others, let's remove those too.

**Comment by hugovk** [comment]
Removed!

**Comment by fbidu** [comment]
thanks for the ping, folks, but I particularly don't remember being involved in the bots file. No objections from me!
