### ISSUE TITLE
Add a note to the `venv` documentation that users should **not** put their code _inside_ the virtual environment

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#109414]
# Documentation

The `venv` docs don't explicitly call out that the virtual environment directory should be viewed as self-contained unit and not as a directory to place one's own code.

### Linked PRs
* gh-109440
* gh-109480
* gh-109481

**Comment by vsajip** [comment]
There is [an admonition](https://docs.python.org/3/library/venv.html#how-venvs-work):

> Because of this, environments are inherently non-portable, in the general case. You should always have a simple means of recreating an environment (for example, if you have a requirements file requirements.txt, you can invoke pip install -r requirements.txt using the environment’s pip to install all of the packages needed by the environment).

I don't object to adding more information, but doesn't this

> virtual environment directory  ... and not as a directory to place one's own code.

come under the "bleedin' obvious" category?

**Comment by brettcannon** [comment]
> doesn't this
> 
> > virtual environment directory  ... and not as a directory to place one's own code.
> 
> come under the "bleedin' obvious" category?

That's what I thought, but based on https://mastodon.social/@fschulze/111053590685791015 and the amount of people we are running into with VS Code who are getting upset we don't format code we find in a virtual environment because we treat it as outside of a user's domain, it apparently isn't getting out enough into the general community.
