### ISSUE TITLE
`str.strip` with hexadecimal-like strings

### ISSUE THREAD

**Issue by dmkulazhenko** [python/cpython#109455]
# Bug report

### Bug description:

`str.strip`, `str.lstrip`, `str.rstrip` work in a strange way with hexademical-like strings.

```python
>>> '0x0'.lstrip('0x')
''  # expected: '0'
>>> '0x0123'.lstrip('0x')
'123'  # expected: '0123'
>>> '0x0'.strip('0x')
''  # expected: '0'
>>> '0x0'.rstrip('0x')
''  # expected: '0x0'
>>> '0x0'.rstrip('x0')
''  # expected '0'
```

--------
upd: Seems to be issues touches not only hexadecmial like strings, but anything:
```python
>>> 'zxz'.lstrip('zx')
''  # expected: 'z'
```

### CPython versions tested on:

3.9, 3.10, 3.11

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
`.strip()` does not take a string to be stripped off, but a set of characters. See the examples in https://docs.python.org/3.10/library/stdtypes.html#str.strip. You may want to use `.removeprefix` or `.removesuffix` instead.
