### ISSUE TITLE
struct.unpack expecting wrong datasize with header dhhbhh (or bh)

### ISSUE THREAD

**Issue by Source61** [python/cpython#109476]
# Bug report

### Bug description:

```python
import struct

data = b"\xff"*17
struct.unpack('dhhbhh', data) # expecting size 18
```

This issue seems to be caused by the '[bB?x]' header/format preceding any(?) other format letter, e.g. 'bh' expects size 4.

Couldn't find anything about this in the documentation, so assumed this is a bug.

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
This is not a bug, ``struct.calcsize('bh')`` is 4 because the struct module adds padding to get native alignment, as described by the start of "[Byte Order, Size and Alignment](https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment)" in the documentation.
