### ISSUE TITLE
argparse fails to get value of argument if the value is `--`

### ISSUE THREAD

**Issue by kushal-kumaran** [python/cpython#109475]
# Bug report

### Bug description:

This code:

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--broken")
parser.add_argument("--working")

args = parser.parse_args(["--broken=--", "--working=asdf"])
print(args)
```

prints:
```
$ podman run -v $(pwd):/src python:3.11.5-bookworm python /src/delim.py 
Namespace(broken=[], working='asdf')
```

The value of the `--broken` argument is not parsed, presumably because it is the standard end-of-argument-list value. But this does not seem expected when the value is introduced with `=`. Besides, in this case, the parsing does continue for subsequent args, so it was not actually treated as end of arguments.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-110959
* gh-114814
* gh-115036
* gh-115037

**Comment by sobolevn** [comment]
`--` means a very specific thing in argument parsing, I don't think that it should be a value of any other argument. If you need this value somewhere in your program, you can use some alias: like `--flag=doubledash`

**Comment by SouSingh** [comment]
Hello @kushal-kumaran I try to run it on my device I get some output I hope that will help
![Screenshot (106)](https://github.com/python/cpython/assets/96938361/e687898c-79fd-42ee-9395-aedeb049936a)

**Comment by ericvsmith** [comment]
> `--` means a very specific thing in argument parsing, I don't think that it should be a value of any other argument. If you need this value somewhere in your program, you can use some alias: like `--flag=doubledash`

I completely disagree with this. Imagine if you were reading the documentation of a command line utility, and it said "If you want the output file to be named '--', then use 'doubledash' instead, and this will be translated to '--' internally. It is not possible to specify an output name of 'doubledash'."

I think this is a completely valid bug report. I'm not sure it's fixable, given all of the issues with argparse and how it scans arguments. I am surprised that using `=--` doesn't work. See https://github.com/python/cpython/issues/53580 for a case where using `=` was suggested as a partial workaround.
