### ISSUE TITLE
types issue

### ISSUE THREAD

**Issue by Gabriel-Vergely** [python/cpython#109463]
# Bug report

### Bug description:

```python
tup: tuple[str,str,int] = ("a","b","c")
print(tup)
# > ('a', 'b', "c")
tup: tuple((str,str,str)) = ("a","b",1)
print(tup)
# > ('a', 'b', "c")
```
the type inside the tuples seems irrelevant.

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Indeed, please see the note at the top of the `typing` module documentation:

> **Note**: The Python runtime does not enforce function and variable type annotations. They can be used by third party tools such as type checkers, IDEs, linters, etc.

https://docs.python.org/3/library/typing.html

Please ask any further questions at https://discuss.python.org/c/users/7; the GitHub issue tracker isn't the right place to ask for help :-)
