### ISSUE TITLE
unexisting `con.json` file: misreport the exists, and fail writing

### ISSUE THREAD

**Issue by yantaozhao** [python/cpython#109458]
# Bug report

### Bug description:

For name `'con.json'`, (indeed the suffix doesn't matter. for all matching pattern of `con.*` like `con.txt`, `con.qwert`, etc):
- Python will always return `True` when run `exists()` check on name `'con.json'`, even though file not exists actually!
- Writing content to the `'con.json'` file will fail, and content is redirected to console.

![image](https://github.com/python/cpython/assets/9587405/bc87dd57-b0fe-4029-8876-5cee23417767)

### CPython versions tested on:

3.9, 3.10, 3.11 ,release by [conda](https://docs.conda.io/projects/miniconda/en/latest/index.html)

### Operating systems tested on:

Windows 10

**Comment by SouSingh** [comment]
hello @yantaozhao con.json I tried to run it on my device it says it doesn't exist 
![Screenshot (105)](https://github.com/python/cpython/assets/96938361/28ff4e05-fbb5-4e79-b54a-5e2409ec133d)

**Comment by yantaozhao** [comment]
> hello @yantaozhao con.json I tried to run it on my device it says it doesn't exist ![Screenshot (105)](https://user-images.githubusercontent.com/96938361/268346554-28ff4e05-fbb5-4e79-b54a-5e2409ec133d.png)

Hi @SouSingh , thanks for your work.

From the snapshot, it looks like your *python* release is from [*python.org*](https://www.python.org/), is it?
Could you test again with *python* from [*conda*](https://docs.conda.io/projects/miniconda/en/latest/), if that's convenient?

My environment: Windows10 64bit + Python from conda.

**Comment by SouSingh** [comment]
Hi @yantaozhao I using Python 3.10.2 and the Device is Windows 11

**Comment by yantaozhao** [comment]
it seems that the bug exists on Windows10

**Comment by aisk** [comment]
I can't reproduce the issue on Windows 11 with `con.json`, but with the filename `con` I've got your problem. However, `con` is a reserved name in Windows, even if it have any prefixes. The MS's [document](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) said:

> CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).

I doubt this is not a Python related issue but a Windows issue, and in any case, I think you should not use the reserved file name on Windows.

**Comment by yantaozhao** [comment]
> I can't reproduce the issue on Windows 11 with `con.json`, but with the filename `con` I've got your problem. However, `con` is a reserved name in Windows, even if it have any prefixes. The MS's [document](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file) said:
> 
> > Do not use the following reserved names for the name of a file:
> > CON, PRN, AUX, NUL, COM0, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT0, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt and NUL.tar.gz are both equivalent to NUL. For more information, see [Namespaces](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#win32-file-namespaces).
> 
> I doubt this is not a Python related issue but a Windows issue, and in any case, I think you should not use the reserved file name on Windows.

correct answer.
