### ISSUE TITLE
Inconsistent document about poll in select module

### ISSUE THREAD

**Issue by aisk** [python/cpython#109450]
The summary of select module said poll is available in most operating systems: https://github.com/python/cpython/blob/main/Doc/library/select.rst?plain=1#L9-L10

But the function document of poll said it's not supported by all operating systems. https://github.com/python/cpython/blob/main/Doc/library/select.rst?plain=1#L95

I think the summary is more right, except it's not supported on Windows.

**Comment by JelleZijlstra** [comment]
I'm not sure I see the inconsistency between "supported on most" and "not supported on all". However, it would be good to be more concrete about which OSes are and are not supported.

**Comment by aisk** [comment]
Ah, I had misunderstood the "not supported on all", I missed it with "all platform is not supported"
