### ISSUE TITLE
frozen dataclass inheritance is not strictly checked in multiple inheritance

### ISSUE THREAD

**Issue by Batman-q96** [python/cpython#109409]
# Bug report

### Bug description:

```python
import dataclasses

@dataclasses.dataclass
class NotFrozen:
    pass

@dataclasses.dataclass(frozen=True)
class Frozen:
    pass

@dataclasses.dataclass(frozen=True)
class Child(NotFrozen, Frozen):
    pass
```
The dataclass inheritance hierarchy is supposed to require all classes to be either frozen or non frozen, this works properly for checking that an unfrozen class does not inherit from any frozen classes, but it allows frozen classes to inherit from unfrozen ones as long as there's at least one frozen class in the MI

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

### Linked PRs
* gh-109437

**Comment by Batman-q96** [comment]
```python
import dataclasses

@dataclasses.dataclass
class NotFrozen:
    pass

@dataclasses.dataclass(frozen=True)
class Frozen:
    pass

# this class fails to create with
# TypeError: cannot inherit non-frozen dataclass from a frozen one
@dataclasses.dataclass
class NotFrozenChild(NotFrozen, Frozen):
    pass

# this class has no issue with creation
@dataclasses.dataclass(frozen=True)
class FrozenChild(NotFrozen, Frozen):
    pass
```

The expected behavior would be that FrozenChild should fail to create with a TypeError: cannont inherit frozen dataclass from a non-frozen one

**Comment by sobolevn** [comment]
Yes, I also belive that this is a bug, here's how users can face it:

```python
def mutate_not_frozen(instance: NotFrozen) -> None:
    x.some_field = 1

mutate_not_frozen(NotFrozen())  # ok
mutate_not_frozen(FrozenChild())  # type-checkers will allow it, but will fail in runtime
```

Interesting, it should fail here:

```python
        # Raise an exception if we're frozen, but none of our bases are.
        if not any_frozen_base and frozen:
            raise TypeError('cannot inherit frozen dataclass from a '
                            'non-frozen one')
```

and it fails correctly with just a single parent, but multiple parents should be checked with `all`, not `any`.

**Comment by ericvsmith** [comment]
Since this is a change in behavior, I'm inclined to call it a feature request and not backport it.

**Comment by ericvsmith** [comment]
Thanks, @sobolevn !
