### ISSUE TITLE
why visual studio is required to get something working for msys2/mingw32?

### ISSUE THREAD

**Issue by goofyseeker311** [python/cpython#109493]
# Bug report

### Bug description:

when doing mingw32 stuff, installing visual studio should not be a requirement, not even a friendly one.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by aisk** [comment]
Actually, only the Windows SDK is needed, you can build Python without Visual Studio.

**Comment by zware** [comment]
Closing for now, but if you can point to some incorrect documentation that ought to be fixed we can reopen.
