### ISSUE TITLE
json.dumps crash on deep nested dicts

### ISSUE THREAD

**Issue by charles-paperman** [python/cpython#109456]
# Crash report

### What happened?

The following code crash with a segmentation fault

```python
import json, sys
def d(a):
    if a == 0: 
        return dict(b=3)
    return dict(a=d(a-1))
sys.setrecursionlimit(50000000)
document = d(87268)
x = json.dumps(d)
```

The content of x is not big (less 1M chars) so it is not related to the size of the output. The setrecursionlimit needs to be big for the d function to work but also for the json.dumps that otherwise raise a RecursionError.  The value (87268) is minimal for the bug to occurs.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Duplicate of #109261
