### ISSUE TITLE
Pandas DataFrame - Default index for all scalar values

### ISSUE THREAD

**Issue by madarasw** [python/cpython#109525]
# Feature or enhancement

### Proposal:

```
# Scenario 1
age_dict = {'Cat': [3], 'Dog': [4], 'Bird': [7], 'Fish': [8]}
age_dataframe = pandas.DataFrame(age_dict)

# Scenario 2
age_dict = {'Cat': 3, 'Dog': [4], 'Bird': 7, 'Fish': 8}
age_dataframe = pandas.DataFrame(age_dict)

# Scenario 3
age_dict = {'Cat': 3, 'Dog': 4, 'Bird': 7, 'Fish': 8}
age_dataframe = pandas.DataFrame(age_dict)
```

Considering above three scenarios, 
The first scenario works.
The second scenario works when there is at least one list type value in the dictionary, which gives the impression that the third scenario would work.

However, the third scenario gives an error as below;
**ValueError: If using all scalar values, you must pass an index**

It would be better if the third scenario does not give an error and work with the default index 0.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by AlexWaygood** [comment]
Hi, thanks for the feature request! Unfortunately, however, this looks like it needs to be filed with the pandas project rather than CPython, as it doesn't have anything to do with CPython :-)

Please file an issue at https://github.com/pandas-dev/pandas/issues instead
