### ISSUE TITLE
Python 3 -m Build Unable to Parse PowerShell Generated pyproject.toml Using Out-File on Windows

### ISSUE THREAD

**Issue by hollowaykeanho** [python/cpython#109588]
# Bug report

### Bug description:

This ticket is for tracking purposes in case anyone bump into the same issue. Please conclude it in accordingly (whether it's a bug or close it immediately). 

For unknown reason, `pyproject.toml` generated by PowerShell using `UTF8` encoder (`$__content | Out-File -FilePath "pyproject.toml" -Encoding UTF8`) is not parse-able by Python build command `python -m build --sdist --whell .`. On Windows OS, it consistently throws this error despite being a healthy file (see `pyproject.windows` in the uploaded artifact:

```
* Creating venv isolated environment...
ERROR Failed to parse D:\a\AutomataCI\AutomataCI\tmp\pypi_automataci-src_1.5.0_windows-amd64\.\pyproject.toml: Invalid statement (at line 1, column 1) 
```

This problem is not seen on UNIX system like Ubuntu and MacOS (as in using their native `printf "..." >  "pyproject.toml"` method).

This problem is also not seen when `Set-Content -Path "pyproject.toml" -Value $__content` in PowerShell file generation. Hence, please use `Set-Content` to workaround the matter.

## How to reproduce

1. Unpack this CI workspace artifact. [sample.tar.gz](https://github.com/python/cpython/files/12667313/sample.tar.gz)
2. Rename/copy either one of the `pyproject` and set to `pyproject.toml`
3. Change directory and run `python -m build --sdist --whell .` across 3 different OSes.
4. Observe. Only Windows' version will throw an error.

### GitHub Actions OS matrices run (Observe PACKAGE step)

1. https://github.com/corygalyna/AutomataCI/actions/runs/6241976144
2. https://github.com/corygalyna/AutomataCI/actions/runs/6242157791
3. https://github.com/corygalyna/AutomataCI/actions/runs/6241903843/job/16944903291
4. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.utility/out-file
5. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.management/set-content

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS, Windows

**Comment by hugovk** [comment]
This is the tracker for bugs in CPython itself. It doesn't sound like a CPython bug, it's possibly one in https://github.com/pypa/build but maybe you need to save the file as UTF-8 without a BOM (byte order mark).

By the way, it's  `--whell` not ` --wheel`.

**Comment by hollowaykeanho** [comment]
> save the file as UTF-8 without a BOM (byte order mark)

Tried all the Encoding methods for UTF-8. The one without BOM will yield another kind of error:

```
* Creating venv isolated environment...

Traceback (most recent call last):
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__main__.py", line 388, in main
    built = build_call(
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__main__.py", line 210, in build_package
    out = _build(isolation, srcdir, outdir, distribution, config_settings, skip_dependency_check)
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__main__.py", line 147, in _build
    return _build_in_isolated_env(srcdir, outdir, distribution, config_settings)
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__main__.py", line 111, in _build_in_isolated_env
    builder = _ProjectBuilder.from_isolated_env(env, srcdir)
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__init__.py", line 199, in from_isolated_env
    return cls(
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__init__.py", line 180, in __init__
    self._build_system = _parse_build_system_table(_read_pyproject_toml(pyproject_toml_path))
  File "D:\a\AutomataCI\AutomataCI\tools\python-engine\lib\site-packages\build\__init__.py", line 83, in _read_pyproject_toml
    return tomllib.loads(f.read().decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

ERROR 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

https://github.com/corygalyna/AutomataCI/actions/runs/6241903843/job/16944903291


> it's possibly one in https://github.com/pypa/build

Noted. I will transfer the ticket there shorty. Thanks for the pointer.
