### ISSUE TITLE
Make PyComplex_RealAsDouble/ImagAsDouble use __complex__

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#109598]
The C-API docs says: "Return the real/imag part of op as a C double."  But the real code looks like:
```c
PyComplex_RealAsDouble(PyObject *op)
{
    if (PyComplex_Check(op)) {
        return ((PyComplexObject *)op)->cval.real;
    }
    else {
        return PyFloat_AsDouble(op);
    }
}
```
So, we assume instead that the ``op`` is a float-like class (a subtype of or something with a ``__float__`` dunder method).  Instead, we should look on the ``__complex__`` method in the ``else`` branch.  This is an issue like #44670, I think.

Minor issue: these functions aren't tested, only indirectly with ``format()`` (that will not trigger all possible cases).

Edit:
The current ``PyComplex_ImagAsDouble()`` silently returns ``0.0`` for all non-PyComplexObject objects (or subtypes of).  I think it's a bug and we should return ``-1.0`` instead and set the error indicator.

### Linked PRs
* gh-109647

**Comment by skirpichev** [comment]
PR is ready for review: https://github.com/python/cpython/pull/109647

**Comment by encukou** [comment]
Thanks for the PR!

I don't think this is bugfix-y enough to need backporting.
