### ISSUE TITLE
Brazilian Portuguese translation typo

### ISSUE THREAD

**Issue by Cristian-Erick** [python/cpython#109577]
There's a typo on the math page, URL: https://docs.python.org/pt-br/3/library/math.html?#math

math.floor(x)
Retorna o limite mínimo de x, o maior inteiro menor ou igual a x. Se x não é um ponto flutuante, delega para [x.__floor__](https://docs.python.org/pt-br/3/reference/datamodel.html#object.__floor__), cujo qual deve retornar um 𝘃𝗮𝗹𝗽𝗿 𝗱𝗽 tipo [Integral](https://docs.python.org/pt-br/3/library/numbers.html#numbers.Integral)

**Comment by hugovk** [comment]
cc @rffontenelle from the Brazilian Portuguese translation team.

**Comment by AlexWaygood** [comment]
Please open an issue at https://github.com/python/python-docs-pt-br/issues, which is where the source code for the Brazilian Portuguese translation is maintained :)
