### ISSUE TITLE
Based on the grammar in the docs, it looks like it's possible to have type annotations in lambda expressions

### ISSUE THREAD

**Issue by Glyphack** [python/cpython#109553]
# Documentation

Based on the grammar seems like it's possible to have type annotations there:
https://docs.python.org/3/reference/expressions.html#lambda

lambda has a parameter_list, parameter_list can have a defparameter and defparameter is a parameter. This is the valid grammar for parameter:

```
parameter                 ::=  identifier [":" expression]
```

I checked the full grammar page and the grammar there is stated different than the previous page: https://docs.python.org/3/reference/grammar.html

I think we can update the docs to refer the page below for the grammar of labmda expressions.

### Linked PRs
* gh-109552

**Comment by sobolevn** [comment]
Yes, good catch. `lambda` in real grammar has specialiazed rules: https://github.com/python/cpython/blob/f65497fd252a4a4df960da04d68e8316b58624c0/Grammar/python.gram#L858

It is called `lambda_param`, it cannot have annotations.

**Comment by Glyphack** [comment]
@sobolevn what do you think is the way to make this more clear in the docs?

1. Copy the lambda_param grammar to this page
2. Remove the link to parameter_list in the lambda paragraph so reader won't follow the wrong grammar

**Comment by Glyphack** [comment]
I'm closing this one, after the discussion in the PR I agree that this is stated in the documentation and it's okay to not have it in the grammar.
