### ISSUE TITLE
The text introduction in the tutorial has a mistake in indexing

### ISSUE THREAD

**Issue by QB3-11** [python/cpython#109502]
In the text section of the third chapter of the documentation, in the string indexing part, -0 is written in the place of -6.

"Note that since -0 is the same as 0, negative indices start from -1"

**Comment by AA-Turner** [comment]
Fairly sure the reference to 3.1.2 means: https://docs.python.org/3/tutorial/introduction.html#text

**Comment by AA-Turner** [comment]
There isn't an error here, the relevant part is describing how negative indicies work.

![image](https://github.com/python/cpython/assets/9087854/8b528b7f-8dfa-4667-ba31-0245c441654d)

A
