### ISSUE TITLE
An error in Mapping Protocol

### ISSUE THREAD

**Issue by qqwqqw689** [python/cpython#109563]
[doc](https://docs.python.org/3/c-api/mapping.html) 

It says:

int PyMapping_Check(PyObject *o)

Return 1 if the object provides the mapping protocol or supports slicing, and 0 otherwise. 

I think or is wrong.Because in cpython/Objects/abstract.c.We have:
```
int
PyMapping_Check(PyObject *o)
{
    return o && Py_TYPE(o)->tp_as_mapping &&
        Py_TYPE(o)->tp_as_mapping->mp_subscript;
}
```
Maybe or should be and.

**Comment by AA-Turner** [comment]
Please open a discussion on Discourse.

A

**Comment by qqwqqw689** [comment]
@AA-Turner 
I think "Return 1 if the object provides the mapping protocol or supports slicing, and 0 otherwise."  should be
"Return 1 if the object provides the mapping protocol and supports slicing, and 0 otherwise."
