### ISSUE TITLE
Doctest - No clear guidance on how to use the "Option Flag"  and and the explanation of "Which Docstrings Are Examined" is ambiguos.

### ISSUE THREAD

**Issue by Unique-Usman** [python/cpython#109510]
# Documentation

Which Docstrings Are Examined :- The issue with the provided documentation lacks clarity and precision. It doesn’t clearly specify what “is true” means in the context of M.test, and it uses unclear language when describing how strings are treated. Additionally, it doesn’t explain why this information is relevant or how it’s practically used.

Option flag :- The documentation provides detailed information about various option flags in doctest, but it lacks real-world examples or scenarios where these flags might be used. Without practical examples, users may find it challenging to understand when and how to apply these flags effectively in their code or documentation testing processes. Providing concrete examples and use cases would greatly enhance the usability of this documentation.

### Linked PRs
* gh-109696
* gh-111077
* gh-111078

**Comment by Unique-Usman** [comment]
I am currently working on fixing this.

**Comment by hugovk** [comment]
Thank you for the fixes!
