### ISSUE TITLE
`socket` Manually set the connection state for SOCK_RAW (AF_INET+IPPROTO_TCP)

### ISSUE THREAD

**Issue by hyperion-cs** [python/cpython#109514]
# Feature or enhancement

### Proposal:

Imagine we have created a _SOCK_RAW (AF_INET+IPPROTO_TCP)_ socket, manually established a connection to the remote server (using manual sending and receiving/processing of packets for a three-way handshake like "`=> SYN <= SYN, ACK => ACK`"), i.e. NOT using the `.connect()` function. Now, we want to switch to a higher-level socket of the form _SOCK_STREAM (AF_INET+IPPROTO_TCP)_. We can do it like this:
```python
import socket

raw_socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_TCP)

...
* Establishing a TCP connection via manual three-way handshake here *
...

stream_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP, fileno = raw_socket.detach())
```

However, now if we try to accept data (e.g. `4096` bytes):
```python
data = stream_socket.recv(4096)
```

We will get an error like `OSError: [Errno 57] Socket is not connected`. This makes sense, because now `laddr` and `laddr` for stream_socket do not exist (and did not exist in _SOCK_RAW_). Fortunately, we can set `laddr` using the `.bind()` function in _SOCK_RAW_:
```python
import socket

raw_socket = socket.socket(socket.AF_INET, socket.SOCK_RAW, socket.IPPROTO_TCP)
raw_socket.bind((src_ip, src_port))

...
* Establishing a TCP connection via manual three-way handshake here (using `src_ip` in the IP header, and `src_port` in the TCP packet header) *
...

stream_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP, fileno = raw_socket.detach())

data = stream_socket.recv(4096)

```

Now `laddr` in `stream_socket` will be set, however, `raddr` still does not exist. It can only be set by using `.connect()` (in both _SOCK_RAW_ and _SOCK_STREAM_). However, calling this function will attempt to establish a new connection, which is **already** established in `SOCK_RAW`.

Thus, I propose to allow _SOCK_RAW_ to set its own state for `raddr`, so that when a _SOCK_STREAM_ is created from _SOCK_RAW_ (by reusing its socket discriptor), the resulting _SOCK_STREAM_ has an established connection state without `.connect()` (i.e. `laddr` and `raddr` must exist, and `.recv()` function is immediately available without returning an error like `OSError: [Errno 57] Socket is not connected`). Perhaps one option is to make `setsockname()` (set `laddr`) and `setspeername()` (set `raddr`) functions in addition to `getsockname()` and `getspeername()` functions. Also, these methods will probably need to manually specify things like `seq`/`ask` num etc.

You may be asking, "why is this necessary?". The answer is simple. Sometimes a low level connection needs to be established (e.g. sending a special `SYN` packet, with a special `seq num`, etc.). However, already after the connection is established, there is no need to operate at a low level, and a normal _SOCK_STREAM_ is required.
Ideally, this should be switching from _SOCK_RAW_ to _SOCK_STREAM_ or vice versa at **any** time. But, for starters, manually setting `raddr` (and anything else that can tell _SOCK_STREAM_ that the connection is already established) will suffice. And it's somewhat surprising that there is a _SOCK_RAW_ where you can specify `laddr` but can't `raddr`, isn't it?

On the other hand, I realize that _SOCK_RAW_ in general should not operate on things like `laddr` and `raddr` at all, because it operates at a lower level and these things are only valid for _IPPROTO_TCP_. Thus, it should only be possible to set these parameters if _SOCK_RAW_ is created in IPPROTO_TCP (and for UDP, maybe.) mode.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ronaldoussoren** [comment]
The Python socket APIs are a fairly thin wrapper around the system socket APIs. How would you accomplish the requested feature using the C socket APIs?

**Comment by hyperion-cs** [comment]
@ronaldoussoren, I see your point. Using only C socket APIs, it is probably impossible to do this. Because the only thing that sets the `raddr` there is the `connect()` function (similar to the "thin wrapper" in Python). Thus, it seems that we are limited by the available APIs. Well, in that case, we can close the issue.
