### ISSUE TITLE
Rule name conflict and token marking mistakes in the 3.12.0rc grammar

### ISSUE THREAD

**Issue by RobEin** [python/cpython#109596]
# Bug report

### Bug description:

This report was originally launched [here](https://discuss.python.org/t/rule-name-conflict-and-token-reference-mistakes-in-the-3-12-0rc-grammar/34151/3).

[grammars](https://github.com/python/cpython/blob/main/Grammar/python.gram):
3.12.0rc3
3.13.0 alpha 0

Rule name conflict with the follwing two grammar rules:
```
fstring: star_expressions
```
and
```
fstring:
    | FSTRING_START fstring_middle* FSTRING_END
```

The colon sign is not a soft keyword (":"), it is a token (':') in these rules:
```
type_param:
    | NAME [type_param_bound] 
    | '*' NAME ":" expression 
    | '*' NAME 
    | '**' NAME ":" expression 
    | '**' NAME

type_param_bound: ":" expression
```

The equal sign is not a soft keyword ("="), it is a token ('=') in the following rule:
```
fstring_replacement_field:
    | '{' (yield_expr | star_expressions) "="? [fstring_conversion] [fstring_full_format_spec] '}'
```

These are more just notation problems in the previous two cases.
In general, this is a problem from that point of view that comparing two texts is slower than comparing two integers.

### CPython versions tested on:

3.12

### Linked PRs
* gh-109606
* gh-109752

**Comment by pablogsal** [comment]
I created a PR to fix it, but notice is not really a problem as the parser does not generate soft keywords for these tokens. For example:

https://github.com/python/cpython/blob/850cc8d0b1db0a912a6e458720e265e6a6e5c1ba/Parser/parser.c#L15973
