### ISSUE TITLE
Clean-up pyatomic headers

### ISSUE THREAD

**Issue by colesbury** [python/cpython#109693]
# Feature or enhancement

Now that https://github.com/python/cpython/issues/108337 is done, we have three atomic headers. We should be able to remove `pycore_atomic.h` and `pycore_atomic_funcs.h` and replace their usages with calls to `pyatomic.h`.

cc @vstinner 

### Linked PRs
* gh-109694
* gh-110477
* gh-110480
* gh-110604
* gh-110605
* gh-110836
* gh-110837
* gh-110992

**Comment by colesbury** [comment]
@vstinner, For `pycore_atomic.h`, I'm not sure whether to keep `_Py_atomic_address` and `_Py_atomic_int` or not.

**Comment by vstinner** [comment]
I was fine to remove pycore_atomic_funcs.h at once since it's only used by _PyUnicode_FromId() which is... no longer used by Python itself!

To remove pycore_atomic.h, I would prefer to make baby steps: convert usage one by one. For example, you can start by converting signal handlers: get_handler() and set_handler() in Modules/signalmodule.c, and also the two "tripped" variables.

If someone goes wrong, it would be easier to revert changes if they have limited scope. Also, smaller PRs are easier to review :-)

**Comment by corona10** [comment]
I am working on the following fields.

https://github.com/python/cpython/blob/67e8d416cc5e14c181e4f883ffb4d87f2a647ae1/Include/internal/pycore_gil.h#L28-L31

**Comment by vstinner** [comment]
The last part seems to be about annotations:

```
vstinner@mona$ git grep pycore_atomic.h

Makefile.pre.in:                $(srcdir)/Include/internal/pycore_atomic.h \
PCbuild/pythoncore.vcxproj:    <ClInclude Include="..\Include\internal\pycore_atomic.h" />
PCbuild/pythoncore.vcxproj.filters:    <ClInclude Include="..\Include\internal\pycore_atomic.h">

Python/ceval_gil.c:#include "pycore_atomic.h"        // _Py_ANNOTATE_RWLOCK_CREATE
Python/thread_pthread.h:#include "pycore_atomic.h"        // _Py_ANNOTATE_PURE_HAPPENS_BEFORE_MUTEX
```

**Comment by vstinner** [comment]
```
Python/ceval_gil.c:#include "pycore_atomic.h"        // _Py_ANNOTATE_RWLOCK_CREATE
Python/thread_pthread.h:#include "pycore_atomic.h"        // _Py_ANNOTATE_PURE_HAPPENS_BEFORE_MUTEX
```

Hum, in fact, these symbols come from dynamic_annotations.h. It seems like pycore_pyatomic.h is no longer needed.

@corona10: Do you want to prepare a PR to remove it?

**Comment by corona10** [comment]
@colesbury @vstinner I think that now we can close this issue.
Please let me know if you want to reopen this issue :)

**Comment by colesbury** [comment]
Thanks @corona10!

**Comment by vstinner** [comment]
Well done. One less legacy API in Python C API :-)
