### ISSUE TITLE
python venv Access denied issue

### ISSUE THREAD

**Issue by gautamsagar99** [python/cpython#109676]
# Bug report

### Description

I have created environment using python -m venv ENV_NAME
now I am facing a issue where after activating the environment and installing any libraries then it is prompting like: 

``` 
Program 'pip.exe' failed to run: Access is deniedAt line:1 char:1
+ pip --version
+ ~~~~~~~~~~~~~.
At line:1 char:1
+ pip --version
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed 
```
    
It is saying like access denied I have tried it in multiple systems with Full access control for the user.

### How to Reproduce this error:

1. create environment using 
   python -m venv ENV_NAME
 2. activate the environment 
 3. run the below command
    pip --version
    
   after performing above steps  I got this error :
   
 ``` 
Program 'pip.exe' failed to run: Access is deniedAt line:1 char:1
+ pip --version
+ ~~~~~~~~~~~~~.
At line:1 char:1
+ pip --version
+ ~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```

### CPython versions tested on:

3.9, 3.11

### Operating systems tested on:

Windows

**Comment by hauntsaninja** [comment]
This is unlikely to be a bug in CPython, and much more likely to be a permissions issue specific to the system you're running on. Consider asking for help at https://discuss.python.org/c/users/7 or on https://stackoverflow.com/
