### ISSUE TITLE
Python3.12 bitwise_and_raw Excessive Memory Consumption or memory leak when migrate from 3.9 to 3.12

### ISSUE THREAD

**Issue by Nhatdealin** [python/cpython#109645]
# Crash report

### What happened?

We are migrating python 3.9 to python 3.12 and had an issue:

After installing new python (we tried 3.12.0rc1, rc2, and rc3), my Subcommand returned non zero status 137 when run command `python ... ` or create virtualenv `virtualenv ...`. On my system, it consumed approximately 16 GBs of memory before being killed. It looks like have leak memory or high consumption memory in this case when go throw bitwise_and_raw in parser.c - shift_expr_rule() inside bitwise_and_raw() [Link here](https://github.com/python/cpython/blob/3.12/Parser/parser.c#L13164C5-L13182C6): 

**Error messages**

OOM killing produced no output, save for Killed.

We ran Valgrind to check and this is a peak (of course it looped many times - other snapshots before killed my process)

```
snapshot=24
#-----------
time=742357481
mem_heap_B=6322655
mem_heap_extra_B=15641
mem_stacks_B=0
heap_tree=peak
n4: 6322655 (heap allocation functions) malloc/new/new[], --alloc-fns, etc.
n1: 4986158 0x4A3AB3F: _PyMem_RawMalloc (obmalloc.c:45)
  n2: 4986158 0x4A3AB18: _PyMem_DebugRawAlloc (obmalloc.c:2096)
   n1: 4985366 0x4A3A86D: _PyMem_DebugRawMalloc (obmalloc.c:2129)
    n2: 4985366 0x4A3A84D: PyMem_RawMalloc (obmalloc.c:662)
     n2: 4978378 0x4A3B896: _PyObject_Malloc (obmalloc.c:1569)
      n1: 4978378 0x4A3AA31: _PyMem_DebugRawAlloc (obmalloc.c:2096)
       n1: 4978378 0x4A3A86D: _PyMem_DebugRawMalloc (obmalloc.c:2129)
        n2: 4978378 0x4A3B824: _PyMem_DebugMalloc (obmalloc.c:2281)
         n2: 4290576 0x4A3CAE2: PyMem_Malloc (obmalloc.c:703)
          n2: 4235264 0x4B433B7: block_new (pyarena.c:81)
           n1: 4226992 0x4B43549: block_alloc (pyarena.c:112)
            n7: 4226992 0x4B43475: _PyArena_Malloc (pyarena.c:183)
             n11: 2655312 0x494E22E: _PyPegen_insert_memo (pegen.c:47)
              n9: 1340064 0x494E1CB: _PyPegen_update_memo (pegen.c:72)
               n1: 223344 0x496151C: shift_expr_rule (parser.c:13208)
                n1: 223344 0x496115C: bitwise_and_raw (parser.c:13174)
                 n1: 223344 0x4961040: bitwise_and_rule (parser.c:13092)
                  n1: 223344 0x4960C70: bitwise_xor_raw (parser.c:13052)
                   n1: 223344 0x4960B54: bitwise_xor_rule (parser.c:12970)
                    n1: 223344 0x4960784: bitwise_or_raw (parser.c:12930)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by iritkatriel** [comment]
Are you able to provide more information about what your subcommand is doing? Can you give us code to run which can reproduce this?

**Comment by iritkatriel** [comment]
Have you tried the same with 3.11?

**Comment by Nhatdealin** [comment]
Hi, We are build ourself python, first of all we download gzip file and install it. our script is run :
`source script to run python in **debug** mode && virtualenv <new venv name>`
I have not tried with 3.11.

**Comment by iritkatriel** [comment]
> Hi, We are building our own python, first of all, we download gzip file and install it. our script is run : `source script to run python in **debug** mode && virtualenv <new venv name>`
> 

What does your script contain?

**Comment by Nhatdealin** [comment]
> > Hi, We are building our own python, first of all, we download gzip file and install it. our script is run : `source script to run python in **debug** mode && virtualenv <new venv name>`
> 
> What does your script contain?

My script is just to setup for environment variables: CXXFLAGS, CFLAGS, LDFLAGS

**Comment by iritkatriel** [comment]
Can you post you full script here?

We are not seeing other people reporting that just creating a venv with 3.12 blows up memory, so there is something in your setup/environment that is triggering the problem. We won't be able to do anything about it without precise instructions how to reproduce what you are seeing.

**Comment by gvanrossum** [comment]
The specifics of bitwise and are probably a red herring. We need to know exactly what it is parsing (generated code?). IIRC the parser may use more memory when built in debug mode.
