### ISSUE TITLE
`test_enum` has duplicate test cases: function vs class based enum definitions

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109774]
# Bug report

https://github.com/python/cpython/blob/5e7ea95d9d5c3b80a67ffbeebd76ce4fc327dd8e/Lib/test/test_enum.py#L1034-L1047

Looks like some cases here are just duplicates: because in some cases `Function` and `Class` tests have different `enum_type` definitions: https://github.com/python/cpython/blob/5e7ea95d9d5c3b80a67ffbeebd76ce4fc327dd8e/Lib/test/test_enum.py#L1104-L1109

But, some have identical. I propose to delete cases where `enum_type` is a duplicate.
I have a PR ready.

It was introduced in https://github.com/python/cpython/pull/108704
CC @ethanfurman 

### Linked PRs
* gh-109775

**Comment by ethanfurman** [comment]
Those duplicates are intentional -- the functional creation tests excercise different code than the class creation tests.
