### ISSUE TITLE
Split up `_GUARD_BOTH_INT` and `_GUARD_BOTH_FLOAT`

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#109736]
# Feature or enhancement

### Proposal:

We should split up `_GUARD_BOTH_INT` into `_CHECK_INT 0` `_CHECK_INT 1`, likewise for `_GUARD_BOTH_FLOAT`. The problem is that these are effectively superinstructions, and they complicate optimizations.

They are easier optimize, because it's 1 input mapping to 1 output, and we can easily eliminate repeated checks by treating it as a common subexpression. The second is that this makes the opcode reusable for `TO_BOOL_INT` which also checks for `PyLong`.

### Has this already been discussed elsewhere?

No response given

**Comment by brandtbucher** [comment]
Sounds like a good idea. Does it make more sense to give them opargs/operands indicating a stack level, or to have two variants (`_CHECK_INT_1` and `_CHECK_INT_2`). Our handling of opargs is still a bit ad-hoc... and I'm not sure if we'll ever want to look deeper than the top two items? It seems like that may simplify the translation, at the expense of a little code duplication.

**Comment by Fidget-Spinner** [comment]
I was thinking `CHECK_INT_1` and `CHECK_INT_2`. Giving them opargs means we can't compose them for the tier 1 instruction :(.

**Comment by gvanrossum** [comment]
Sounds good; looking forward to the PR.

**Comment by Fidget-Spinner** [comment]
> Sounds good; looking forward to the PR.

I hope to work on this at the sprint.

**Comment by Fidget-Spinner** [comment]
I've decided not to pursue this, as I have other plans.

**Comment by brandtbucher** [comment]
Probably still worth leaving open though? Presumably any optimizer we eventually have will benefit from removing one of the guards if possible?

Or do you have something more clever in mind? :)

**Comment by Fidget-Spinner** [comment]
Guards only matter insofar that we have a corresponding action to take. So we don't have to split them up: there won't be any improvement in information gain (with our current plans, at least).

**Comment by brandtbucher** [comment]
Hm, maybe I’m misunderstanding your plans. If I have an expression like `42 * x`, surely we could benefit from removing the guard for the LHS?

**Comment by Fidget-Spinner** [comment]
> Hm, maybe I’m misunderstanding your plans. If I have an expression like `42 * x`, surely we could benefit from removing the guard for the LHS?

I think we would, but the small overhead saved from that, versus having to do two checks on every binary op now, is probably not worth it IMO.
