### ISSUE TITLE
Include "t" in ABI tag for `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#109740]
# Feature or enhancement

Context: 
* [PEP 703 (Build Configuration Changes)](https://peps.python.org/pep-0703/#build-configuration-changes) 
* [PEP 3149 – ABI version tagged .so files](https://peps.python.org/pep-3149/#proposal)

The `--disable-gil` builds will have a different *version specific* ABI from the default CPython 3.13 builds due to reference counting differences and other changes. This should be indicated by a "t" (for "threading") in the ABI tag.

On POSIX, this is achieved by setting the `ABIFLAGS` variable, which feeds into the sysconfig `EXT_SUFFIX` and `SOABI` variables. The version specific shared libraries would look like:

* `package.cpython-313t-darwin.so`

On Windows, this is achieved by setting [`PYD_TAGGED_SUFFIX`](https://github.com/python/cpython/blob/c32abf1f21c4bd32abcefe4d601611b152568961/Python/dynload_win.c#L18-L22), which feeds into the sysconfig `EXT_SUFFIX`. The shared libraries using the version specific ABI would look like:

* `_package.cp313t-win_amd64.pyd`

Note that this does not address and is independent of the stable ABI. There's ongoing [discussion](https://discuss.python.org/t/python-abis-and-pep-703/34018) about how best to support the stable ABI in `--disable-gil` builds.

cc @gpshead @brettcannon @vstinner 

### Linked PRs
* gh-109922

**Comment by vstinner** [comment]
Yep, I'm fine with "t" tag. Try to write a test to ensure that if Python is built with NoGIL, the tag is present. Maybe added it in test_sys which can check sys.abiflags.

**Comment by colesbury** [comment]
This is implemented, although there are still some follow-up tasks.
