### ISSUE TITLE
Re-entering pairwise.__next__() leaks references

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#109786]
Re-entering the `__next__()` method of itertools.pairwise leaks references, because *old* hold a borrowed reference when the `__next__()` method of the underlying iterator is called. It may potentially lead to the use of a freed memory and a crash, but I only have reproducer for leaks.

Even if the re-entrant call is not very meaningful, it should correctly count references. There are several ways to fix this issue. I choose the simplest one which matches the current results (only without leaks) in most of simple tests, even if there is no other reasons to prefer these results.

cc @rhettinger

### Linked PRs
* gh-109788
* gh-112699
* gh-112700

**Comment by rhettinger** [comment]
Let's get the other issue fixed first.  This one is somewhat exotic and the PR makes a mess of the code.

**Comment by pochmann** [comment]
I don't see your leak reproducer, wrote one based on your test:

<details><summary>Leak reproducer</summary>

[Whole code at Attempt This Online!](https://ato.pxeger.com/run?1=hVNLTsMwEF2w8ylGQih2Kf0ICaFK3XRXCbgAoMhNx21oYke2K5KzsOkGDsVpsOOkTVELXtnzPO-9mbE_vorKrpXc7T63Vtzcf19cCa1ySC1qq1RmIM0LpS0UPNXvqUHSnE1l2u0qaXdW8wRznmUqIWSJAlKZaBS0ZBMCbiUZNwbm4VAH1FZamMJoH_FZcezl45gazAQ73PZLo91qCR75lSOxtKdzfGgQpK6nMD7CUtGFpw4-zu1oegHq-2DY3xS3ZynKU7U8KYl1vOZ23Wh7TeeUBamuNLmEuW8rNwhcglq8YWKNIxPBwKKC8cgtUjqqgFJGCp1KS0V0uIZCaZxEfT_KwQpti7hpMeIwiN34QHO5QloTNl3dz5SsEldzlnUFDvxcuBmeo3c1PCDfBKP7EpRwAdjMAHmyJp3HNDCWay_yv61FZdE0wGmHLzJz0riEHHOlK2-xK-WsxvV5GYcLlD2PXmE4dN56vbs-RI-ziIXf0nya9vP8AA)

`incref(x)` artificially increases the refcount of `x`:

```python
def incref(x):
    class I:
        count = 0
        def __iter__(self):
            return self
        def __next__(self):
            self.count += 1
            if self.count == 1:
                return next(pairs)
            if self.count == 3:
                return x
            return None
    pairs = pairwise(I())
    next(pairs)
```

Demo increasing an object's refcount by 10000:
```python
x = object()
print(f'refcount before:', sys.getrefcount(x))
for _ in range(10000):
    incref(x)
gc.collect()
print('refcount after:', sys.getrefcount(x))
```

Output:
```
refcount before: 2
refcount after: 10002
```

Demo leaking 10000 objects of 10 kB each:
```python
tracemalloc.start()
for _ in range(10000):
    incref(bytes(10000))
gc.collect()
print('\nleaked memory:', tracemalloc.get_traced_memory()[0] // 10**6, 'MB')
```

Output:
```
leaked memory: 100 MB
```

</details>

**Comment by serhiy-storchaka** [comment]
I added them as tests. You can run tests with the `-R` option to see leaks.
