### ISSUE TITLE
Windows os.path.isdir has different signature

### ISSUE THREAD

**Issue by aminalaee** [python/cpython#109782]
# Bug report

### Bug description:

In this PR #101324 and issue #101196 the optimized methods of `isdir` and `isfile` were added for windows. If not available they will fall back to `genericpath` implementations.

The issue with `isdir` is that this introduced a different signature compared to `genericpath`:
```py
# in genericpath.py
def isdir(s) -> bool: ...

# in optimized nt module
def isdir(path) -> bool: ...
```

I'm not sure if this was intentional to have different signatures depending on the platform, and there's any possibility to fix this now. Ref: https://github.com/python/typeshed/pull/10751

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109790
* gh-110233

**Comment by sobolevn** [comment]
CC @zooba and @mdboom

**Comment by zooba** [comment]
Pretend the optimised one doesn't exist and type it like it shows up in Python code.

We can chonge
