### ISSUE TITLE
basicblock_addop Assertion: while-else-loop with try

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#109719]
# Bug report

### Bug description:

```python
while name_5:
    try:
        break
    except:
        pass
else:
    1 if 1 else 1

```

output (Python 3.12.0rc3+):
```python
python: Python/flowgraph.c:114: basicblock_addop: Assertion `0 <= oparg && oparg < (1 << 30)' failed.
```

@iritkatriel I think this looks similar to https://github.com/python/cpython/issues/109627

I tested this bug with faa8003 and the fix does not solve this issue.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-109734
* gh-109749

**Comment by sobolevn** [comment]
CC @iritkatriel who fixed a similar problem before

**Comment by iritkatriel** [comment]
Thank you, it's the same bug in another place in the compiler. Keep them coming. How are you doing this? With a fuzzer?

**Comment by iritkatriel** [comment]
Thank you, it's the same bug in another place in the compiler. Keep them coming. How are you doing this? With a fuzzer?

**Comment by 15r10nk** [comment]
Yes, I wrote [pysource-codegen](https://github.com/15r10nk/pysource-codegen) which generates random python code.
 
I am currently adding 3.12 support and find these bugs more or less on the way.
My current setup is here [pysource-playground](https://github.com/15r10nk/pysource-playground) which combines pysource-codegen and pysource-minimize.

**Comment by iritkatriel** [comment]
That's truly awesome. Thank you.

**Comment by gpshead** [comment]
connecting some dots here as an FYI - https://github.com/Zac-HD/hypothesmith is another python code generator.

It's be neat to have code generation as you've been doing perhaps setup within our oss-fuzz runs.

**Comment by 15r10nk** [comment]
hi @gpshead, thank you for the connection. 
I already know about hypothesmith. I think that both tools have their own strength. 
* pysource-codegen is limited to the possible output of ast.unparse but can generate larger source files.
* hypothesmith uses libCST which provides more variation in the generated code, but is limited by the randomness of hypothesis and can not generate larger source files.

oss-fuss is actually new for me. I will look into it. Thank you.
