### ISSUE TITLE
`_testinternalcapi` is imported without guards in some test modules

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109721]
# Bug report

I found at least three cases where `_testinternalcapi` is just imported, we cannot do that, because other python implementation which reuse our test cases will fail on this.

1. https://github.com/python/cpython/blob/34ddcc3fa118168901fa0d3a69b3b5444fc2f943/Lib/test/test_cmd_line.py#L785-L826

2. https://github.com/python/cpython/blob/34ddcc3fa118168901fa0d3a69b3b5444fc2f943/Lib/test/test_import/__init__.py#L25
3. https://github.com/python/cpython/blob/34ddcc3fa118168901fa0d3a69b3b5444fc2f943/Lib/test/test_opcache.py#L8

There can be several options to solve this:
1. Use `import _testinternalcapi` with `except ImportError`, when some places might need it
2. Use `import_helper.import_module` to skip some tests where this module is required
3. Use `@cpython_only` decorator

### Linked PRs
* gh-109722

**Comment by serhiy-storchaka** [comment]
Is it already fixed?
