### ISSUE TITLE
Combine dataclass exec calls

### ISSUE THREAD

**Issue by ssweber** [python/cpython#109870]
# Feature or enhancement

### Proposal:

[As mentioned here](https://discuss.python.org/t/improving-dataclasses-startup-performance/15442/18), dataclass definition can possibly be sped up by combining the multiple `exec` calls into one.

I have two versions, and I found that this results in either a 1.1-1.22 ~~1.26, or 1.37 speedup versus main~~ (old time / new time)

~~[version 1](https://github.com/python/cpython/commit/e7c42bd21cf0f12ebfd88744dfde70b78877b1ac) combines the exec calls by passing a list of name/txt/locals from each function definition.
[version 2](https://github.com/python/cpython/commit/10a72b7621b4a6580db1b29d15f259109a701c08) simplifies the final exec call to avoid `__create_fn__`, but I'm not experienced to know if that is safe.~~ (see below for open pr)

@ericvsmith Let me know if this is a suitable change, and if so, which version we should open a pr based on.

Thank you!

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

https://discuss.python.org/t/improving-dataclasses-startup-performance/15442/18

### Linked PRs
* gh-110186
* gh-110851

**Comment by ssweber** [comment]
I measured the difference [with this benchmark](https://gist.github.com/ssweber/34222fd2e770a72147903ab2706f98d7) which includes order=True. 

Since we are combining exec calls, the speed up over main will be less if order=False

**Comment by ssweber** [comment]
This is not as performant as [Caching dataclass](https://github.com/python/cpython/issues/100930), but I wanted a counter-point available where memory use shouldn’t be a potential concern.

**Comment by ericvsmith** [comment]
@ssweber : As I said elsewhere, I think this is a good idea. Thanks for the work on it! I plan on looking at this during the core dev sprint next week.

**Comment by ssweber** [comment]
Glad I can help in some way! I cleaned up and created a pull request. I tried to not change to much, mainly just to prove the modest speedup.

**Comment by ericvsmith** [comment]
I have a PR that's almost ready for this. I got about a 15% speedup for creating the most basic of dataclasses, which adds 3 methods: `__init__`, `__repr__`, and `__eq__`. I expect the speedup to be faster if adding comparison functions, etc.

**Comment by ssweber** [comment]
It's like 1.22 when you include order/frozen! 😄 love the new `FuncBuilder` class.
