### ISSUE TITLE
`reprlib.recursive_repr` does not copy `__type_params__`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109818]
# Bug report

Repro:

```python
>>> from reprlib import recursive_repr
>>> 
>>> class My:
...    @recursive_repr()
...    def __repr__[T](self, converter: T | None = None): ...
... 
>>> My().__repr__.__type_params__
()
```

This happens because `recursive_repr` does not use `@wraps`, but reinvents it: https://github.com/python/cpython/blob/f2eaa92b0cc5a37a9e6010c7c6f5ad1a230ea49b/Lib/reprlib.py#L26-L33

And `__type_params__` was added in https://github.com/python/cpython/issues/104600

### Linked PRs
* gh-109819
* gh-109999

**Comment by hugovk** [comment]
Thanks for the issue and PRs!

Little reminder to close issues when the PRs are merged :)
