### ISSUE TITLE
Behaviour of None in slices used for indexing

### ISSUE THREAD

**Issue by ByteEater-pl** [python/cpython#109997]
It's useful to conditionally slice a collection until the end. It's possible by putting the result of `len` on the collection in the second position in the slice (`-1` is no good, it skips the last element), but it's less performant and more verbose, especially if the collection is expressed by a complex expression.

There seems to be a working solution: use `None`. But it's an undocumented feature. Here's the current wording:
> Sequences also support slicing: a[i:j] selects all items with index k such that i <= k < j. When used as an expression, a slice is a sequence of the same type. This implies that the index set is renumbered so that it starts at 0.
>
> Some sequences also support “extended slicing” with a third “step” parameter: a[i:j:k] selects all items of a with index x where x = i + n*k, n >= 0 and i <= x < j.

It should raise an exception (unless the programme has redefined comparison) with `3:None`, like evaluating `3 < None`. But instead it works in the useful way described above.

Please change the documentation so that it matches the implementation and legalizes this useful feature.

**Comment by TeamSpen210** [comment]
That bit of the docs is a summary, it doesn't go into the details. In the more specific sections, it is documented that `None` must mean the same as omitting values. In the section about sequence operations, [note 5](https://docs.python.org/3/library/stdtypes.html#common-sequence-operations) specifies that they must accept `None`. And in the section defining the [slicing syntax](https://docs.python.org/3/reference/expressions.html#slicings), it specifies that a slice object is created with attributes set to `None` if values are omitted. That means it's impossible for an object to tell the difference between `None` and an omitted value.

**Comment by ByteEater-pl** [comment]
Thanks for explaining it, @TeamSpen210. The issue can be closed.

Although I think it still doesn't require that `__getitem__` for the indices forming an arithmetic sequence defined by a slice be called in any particular order. Which may lead to observable differences if `__getitem__` is impure. It isn't even stated that for each value there's exactly one call (if they don't raise an exception or modify the primary or mutable attributes of any of the indexing slices, presumably).

And it isn't clear to me how many times `__getitem__` is called with tuples if there's more than one slice in the slice list. For example, in `x[1:3, 'a', :2]` are there just two calls (`x.__getitem__((1, 'a', 0))` and `x.__getitem__((2, 'a', 1))`), or four, or some other number? (As noted above, their order is unspecified.)

So, two separate issues for the above before closing?

**Comment by TeamSpen210** [comment]
The interpreter doesn't call `__getitem__` multiple times, ever. The meaning of the indexes is all entirely up to the target object. In your example, it'll result in the call `x.__getitem__((slice(1, 3, None), 'a', slice(None, 2, None)))`. The sequence types section describes how the builtin objects all behaves, but you don't have to follow those rules. For instance, you could do cheeky things like `someobj[5, "default": None]`.

Actually, a better link for the functionality is a note in the [definition for `__getitem__`/`__setitem__`](https://docs.python.org/3/reference/datamodel.html#emulating-container-types), which explicitly states a slice is passed in.

**Comment by ByteEater-pl** [comment]
Thanks, now I understand it, having connected the dots you pointed me to. It appears there to be nothing to correct after all, so closing.
