### ISSUE TITLE
Unexpected `__isabstractmethod__` attribute on `staticmethod` object accessed via `__dict__`

### ISSUE THREAD

**Issue by Joshuaalbert** [python/cpython#109965]
# Bug report

## Description
When accessing a `staticmethod` object directly through a class's `__dict__`, the `staticmethod` object seems to have the `__isabstractmethod__` attribute set, even when the method isn't declared abstract using the `@abstractmethod` decorator.

## Steps to Reproduce
Here's a minimal example to reproduce the behavior:

```python
class A:

    @staticmethod
    def static_method():
        return

if __name__ == '__main__':
    a = A()   
    assert not hasattr(a.static_method, '__isabstractmethod__')  # Success
    assert not hasattr(A.static_method, '__isabstractmethod__')  # Success
    unwrapped_function = A.__dict__["static_method"].__func__
    assert not hasattr(unwrapped_function, '__isabstractmethod__')  # Success
    
    assert not hasattr(A.__dict__["static_method"], '__isabstractmethod__')  # <--- This assertion fails
```

### CPython versions tested on:

3.10
3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
This is because of how descriptors work:

- Accessing `A.static_method` at runtime triggers the call `A.__dict__['static_method'].__get__(A)`, which is returns the same object as `A.__dict__['static_method'].__func__`. I.e., when you access `A.__dict__['static_method']`, you get an object of type `builtins.staticmethod`, but when you access `A.static_method`, you get an object of type `types.FunctionType`.
- `staticmethod` objects have an `__isabstractmethod__` descriptor, while `types.FunctionType` objects do not.

```pycon
>>> class Foo:
...     @staticmethod
...     def bar(): ...
...
>>> type(Foo.bar)
<class 'function'>
>>> type(Foo.__dict__['bar'])
<class 'staticmethod'>
>>> Foo.__dict__['bar'].__func__
<function Foo.bar at 0x000001A7F4DEC900>
>>> type(Foo.__dict__['bar'].__get__(Foo))
<class 'function'>
>>> Foo.__dict__['bar'].__get__(Foo) is Foo.bar is Foo.__dict__['bar'].__func__
True
>>> staticmethod.__dict__['__isabstractmethod__'].__get__(Foo.__dict__['bar'])
False
>>> staticmethod.__dict__['__isabstractmethod__']
<attribute '__isabstractmethod__' of 'staticmethod' objects>
>>> type(_)
<class 'getset_descriptor'>
>>> staticmethod.__dict__['__isabstractmethod__'].__get__(Foo.bar)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: descriptor '__isabstractmethod__' for 'staticmethod' objects doesn't apply to a 'function' object
```

I agree with @sobolevn: this doesn't seem like a bug to me

**Comment by Joshuaalbert** [comment]
I see, it was this fact that I was unaware of:
> when you access A.__dict__['static_method'], you get an object of type builtins.staticmethod, but when you access A.static_method, you get an object of type types.FunctionType

I expected they return the same type.

**Comment by AlexWaygood** [comment]
> I expected they return the same type.

No. You may be interested in the pure-Python equivalent of `builtins.staticmethod` given in the Descriptor HOWTO: https://docs.python.org/3/howto/descriptor.html#static-methods :-)
