### ISSUE TITLE
Also test `typing.NamedTuple` with `copy.replace`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#109956]
# Bug report

Right now only `collections.namedtuple` is tested: https://github.com/python/cpython/blob/b1aebf1e6576680d606068d17e2208259573e061/Lib/test/test_copy.py#L937-L946

@serhiy-storchaka noted in https://github.com/python/cpython/pull/108752#discussion_r1313369490 that only named tuples created by `collections.namedtuple()` are supported. But, since `typing.NamedTuple` uses `collections.namedtuple` inside: https://github.com/python/cpython/blob/b1aebf1e6576680d606068d17e2208259573e061/Lib/typing.py#L2695-L2696 it is also supported:

```python
>>> import typing
>>> 
>>> class N(typing.NamedTuple):
...    x: int
...    y: int
... 
>>> N.__replace__
<function N._replace at 0x10580a210>
>>> import copy
>>> copy.replace(N(1, 2), x=3)
N(x=3, y=2)
```

I have a PR ready with extra tests.

Refs https://github.com/python/cpython/issues/108751
Refs https://github.com/python/cpython/pull/108752

### Linked PRs
* gh-109957

**Comment by serhiy-storchaka** [comment]
"Named tuple" is more general term (https://docs.python.org/3/glossary.html#term-named-tuple).  Not all named tuples in wide meaning are supported (for example named tuples created by the PyStructSequence C API are not supported yet). `typing.NamedTyple` is a funny way to call `collections.namedtuple()`, so this note covers it too. If you want to test them, would not be better to add new tests to other `typing.NamedTyple` tests?
