### ISSUE TITLE
Survey: Open-Source Documentation for Newcomers

### ISSUE THREAD

**Issue by nursenakrbs** [python/cpython#110046]
Hello Python Community!

We are researchers from George Mason University in the United States, looking for open-source contributors to participate in our survey on open-source software (OSS) project documentation use when onboarding. If you are 18 or older and contributed to an OSS project in the last one year, you can help!

The objective of our research is to better understand what type of documentation in OSS projects is more helpful for project newcomers. The survey will take approximately 10 minutes, and upon successful completion of the survey, you will be able to participate in a draw for a chance to win one of four Amazon.com gift cards worth $50 via email.

The link to survey: https://go.gmu.edu/Onboarding_Study

We would be greatly appreciative if you would be willing to participate in this study and help us improve the effectiveness of the onboarding to software projects.

If this message would best be directed or reposted somewhere, please let us know, and we will be happy to modify/repost it.

Thank you for considering participating in our research study!

Research Team: Nursena Kurubas, Dr. Kevin Moran and Dr. Brittany Johnson

IRBNet #: ``2029296-1``

**Comment by AA-Turner** [comment]
Hi,

You'd likely better get a better response on the [Python Discourse](https://discuss.python.org/) forum. There's also a [Discord forum](https://discord.gg/sMWqvzXvde) for Python's documentation which you could likely ask the same question at, though note that the latter is a private forum and the former is public (and far more widely read).

Thanks,
Adam

**Comment by AA-Turner** [comment]
Please also provide some context for what the "IRBNet" number means, as at present you've presented it without context!

A

**Comment by nursenakrbs** [comment]
Hi,

Thank you so much Adam, it helped a lot! 

-Nursena
