### ISSUE TITLE
test_threading failed: test_reinit_tls_after_fork() failed with "env changed" on GHA Address Sanitizer: process 19857 is still running after 300.4 seconds

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110031]
GHA Address Sanitizer:

```
test_reinit_tls_after_fork (test.test_threading.ThreadJoinOnShutdown.test_reinit_tls_after_fork) ... Warning -- Uncaught thread exception: AssertionError
Exception in thread Thread-35 (do_fork_and_wait):
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Lib/threading.py", line 1066, in _bootstrap_inner
    self.run()
  File "/home/runner/work/cpython/cpython/Lib/threading.py", line 1003, in run
    self._target(*self._args, **self._kwargs)
  File "/home/runner/work/cpython/cpython/Lib/test/test_threading.py", line 1185, in do_fork_and_wait
    support.wait_process(pid, exitcode=50)
  File "/home/runner/work/cpython/cpython/Lib/test/support/__init__.py", line 2202, in wait_process
    raise AssertionError(f"process {pid} is still running "
AssertionError: process 19857 is still running after 300.4 seconds
ok
```

build: https://github.com/python/cpython/actions/runs/6340021936/job/17220524327?pr=110026

### Linked PRs
* gh-110100
* gh-110103
* gh-110104

**Comment by vstinner** [comment]
See also issue gh-110052 which looks similar.

**Comment by ericsnowcurrently** [comment]
I'm not sure this is related.  `test_reinit_tls_after_fork()` does not involve any daemon threads or subinterpreters.  It actually reminds me of errors on gh-109846: https://github.com/python/cpython/actions/runs/6312835754/job/17139691845.

**Comment by vstinner** [comment]
@ericsnowcurrently:
> I'm not sure this is related. test_reinit_tls_after_fork() does not involve any daemon threads or subinterpreters.

Oh, I was wrong: it's a ASAN build. I wrote PR #110100 to skip the test if Python is built with ASAN, as I already did for another test_threading test.
