### ISSUE TITLE
The TypeError message from random.seed call has a seemingly unintentional newline in the middle

### ISSUE THREAD

**Issue by yilei** [python/cpython#110050]
# Bug report

### Bug description:

```python
>>> import random
>>> random.seed(random)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...lib/python3.12/random.py", line 167, in seed
    raise TypeError('The only supported seed types are: None,\n'
TypeError: The only supported seed types are: None,
int, float, str, bytes, and bytearray.
```

It appears that the newline in the middle added in https://github.com/python/cpython/pull/25874 isn't intentional.

I'll send a PR.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-110051
* gh-110625

**Comment by encukou** [comment]
Thank you for the fix!
It won't appear in 3.12 as it could break code that relies on the old wording, but it did get into 3.13.
