### ISSUE TITLE
Refactor to reduce code duplication in `Tools/scripts/summarize_stats.py`

### ISSUE THREAD

**Issue by mdboom** [python/cpython#110019]
# Feature or enhancement

### Proposal:

The `summarize_stats.py` script operates in two modes: single and comparison.  It grew these two modes somewhat organically, and there is a lot of code duplication and opportunity for these two modes to diverge.  By refactoring to have each of the tables know how to present themselves in both modes, we should reduce the overall amount of code and these kinds of bugs.  This refactor should be helpful in advance of the many [new stats we plan to add for the Tier 2 interpreter](https://github.com/python/cpython/issues/109329).

Cc: @brandtbucher, @markshannon 

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

Related: https://github.com/python/cpython/issues/109329

### Linked PRs
* gh-110398

**Comment by hugovk** [comment]
Thanks!
