### ISSUE TITLE
copy and deepcopy fail to copy ipaddress scope_id

### ISSUE THREAD

**Issue by becarpenter** [python/cpython#110196]
# Bug report

### Bug description:

copy and deepcopy fail to copy ipaddress scope_id
```python3
import ipaddress, copy
a = ipaddress.IPv6Address('fe80::abc%def')
a.scope_id  #shows 'def'
c = copy.copy(a)
c.scope_id  #shows null, should show 'def'
d = copy.deepcopy(a)
d.scope_id  #shows null, should show 'def'
```

### CPython versions tested on:

3.9, 3.11

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-110198
* gh-111190
* gh-111191

**Comment by gaogaotiantian** [comment]
`IPv6Address` now inherits `__reduce__` from `_BaseAddress` which will only keep the ip info (so `scope_id` is discarded). I just added a new `__reduce__` method for it to solve this.

**Comment by becarpenter** [comment]
Thanks for quick response.
