### ISSUE TITLE
Unexpected performance between (seemingly) pointless CONTAINS_OP compared to COMPARE_OP

### ISSUE THREAD

**Issue by ndren** [python/cpython#110192]
Try the following:
```bash
# Python 3.11.5 (main, Sep  2 2023, 14:16:33) [GCC 13.2.1 20230801] on linux [archlinux, python 3.11.5-2]
python -m timeit -s 'x=2**32' 'x==2**32'
# 10000000 loops, best of 5: 21.4 nsec per loop
python -m timeit -s 'x=2**32' 'x in (2**32,)'
# 20000000 loops, best of 5: 18.8 nsec per loop
python -m timeit -s 'x=2**32' 'x in [2**32]'
# 20000000 loops, best of 5: 18.9 nsec per loop
```
Unless I misunderstood something about how the comparison operator works (some identically equal shenanigans?), this does not seem like the right result. It is expected that the results are either equal or the other way around, but this is reproducible consistently. I could not test previous Python versions though.

**Comment by JelleZijlstra** [comment]
Interesting find! I think this is what's going on:

The 2**32 gets compiled into a constant
```
In [2]: dis.dis("2**32")
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (4294967296)
              4 RETURN_VALUE
```

When you do the `in` check, the algorithm looks something like this:
```
def tuple_contains(tpl, x):
    for elt in tpl:
        if elt is x: return True
        if elt == x: return True
    return False
```

That is, we first check for identity, and only then for equality. And in your example, the 2**32 constants get unified so that they refer to the same object. You can check that by running `python -m timeit -s 'x=2**32' 'print(x is 2**32)'` (warning, it will print a lot). And apparently that fast path for container membership is faster than actually comparing the two ints for equality.

You can check this by doing `x=int(float(2**32))` instead, which returns the same number but a different object:

```
% python -m timeit -s 'x=int(float(2**32))' 'x==2**32'
20000000 loops, best of 5: 11 nsec per loop
% python -m timeit -s 'x=int(float(2**32))' 'x in [2**32]'
20000000 loops, best of 5: 13.9 nsec per loop
% python -m timeit -s 'x=int(float(2**32))' 'x in (2**32,)'
20000000 loops, best of 5: 13.9 nsec per loop
```

And then equality is indeed slightly faster, as expected.

Is there anything actionable here? Possibly it's worth it to add a fast path to the int equality check, so that it returns immediately if self is the same object as the other object. Not sure if that's worth the overhead though (an extra pointer equality check for all integer equality comparisons).

**Comment by ndren** [comment]
Very interesting! That makes a lot of sense.

I am not in a position to decide if the change would be useful, but from what I've read it seems that previous decisions have been made with the assumption that small integers are common, and I think those are always the same object. So maybe this would make sense to do.

Also, it could only include the check for constants that are known to always point to the same object (like x==3), though that may be too much complexity. Though it would at least alleviate the "SyntaxWarning: "is" with a literal." warning without losing the upsides.

Feel free to close if not actionable though.

**Comment by pochmann** [comment]
If I'm not mistaken, int comparisons already have a fast path checking identity:

https://github.com/python/cpython/blob/6139bf5e0c755ed22bdfb027a5299493f0c71be9/Objects/longobject.c#L3265

**Comment by eendebakpt** [comment]
Does the specializing adaptive interpreter work when running with `timeit`? If not, then the `==` is mapped to a `COMPARE_TO` bytecode which executes `PyObject_RichCompare` (https://github.com/python/cpython/blob/main/Objects/object.c#L818)

**Comment by ndren** [comment]
@eendebakpt I don't know the details, but does output of `python -m timeit -s 'x=2**32' 'import dis; dis.dis(lambda:x==2**32)'` answer your question? (The performance difference is also reproducible inside lambdas, so it should be fine in principle.)

**Comment by eendebakpt** [comment]
@ndren You need to do `dis.dis(..., adaptive=True)` to see the adaptive bytecodes.

But also you need to make sure the statement `x==2**32` is interpreted often enough to trigger the specialization. If I create a file `cc.py` with
```
import dis

def g(x):
    for ii in range(12_000): # large enough to trigger the adaptive bytecode
        x==2**5
        x+3
```
and then run `python -m timeit -s  "from cc import g; import dis" "g(4); dis.dis(g, adaptive=True)"` (with Python 3.12!) I get the output
```
  3           0 RESUME                   0

  4           2 LOAD_GLOBAL_BUILTIN      1 (NULL + range)
             12 LOAD_CONST               1 (12000)
             14 CALL_BUILTIN_CLASS       1
             22 GET_ITER
        >>   24 FOR_ITER_RANGE          12 (to 52)
             28 STORE_FAST__LOAD_FAST     1 (ii)

  5          30 LOAD_FAST__LOAD_CONST     0 (x)
             32 LOAD_CONST               2 (32)
             34 COMPARE_OP_INT          40 (==)
             38 POP_TOP

  6          40 LOAD_FAST__LOAD_CONST     0 (x)
             42 LOAD_CONST               3 (3)
             44 BINARY_OP_ADD_INT        0 (+)
             48 POP_TOP
             50 JUMP_BACKWARD           14 (to 24)

  4     >>   52 END_FOR
             54 RETURN_CONST             0 (None)
```
The `COMPARE_OP` is specialized to`COMPARE_OP_INT `

On your system (python 3.11.5) you will probably see the specialization of `BINARY_OP_ADD_INT`, but not `COMPARE_OP_INT` (that was added later).

Could you re-run your benchmarks, but with the statement wrapped in in function so that the adaptive interpreter is used?

**Comment by ndren** [comment]
> Could you re-run your benchmarks on 3.12, but with the statement wrapped in a function so that the adaptive interpreter is used?

@eendebakpt I will do that once 3.12 is released in Arch. (Though as far as I can tell it happens on other systems.) What should I measure exactly?

What I had in mind was measuring `g(4)` then measuring `g_with_in_list(4)` then measuring `g_with_in_tuple(4)`, would that work?

**Comment by ndren** [comment]
It behaves the same on a cold interpreter on 3.12:
```
$ python -m timeit -s 'x=2**32' 'x==2**32'
10000000 loops, best of 5: 26.2 nsec per loop
$ python -m timeit -s 'x=2**32' 'x in [2**32]'
20000000 loops, best of 5: 19.9 nsec per loop
$ python -m timeit -s 'x=2**32' 'x in (2**32,)'
20000000 loops, best of 5: 19.7 nsec per loop
```

But, more importantly, it behaves as expected in 3.12 with a hot interpreter (thanks for showing how to check the bytecodes!):
```bash
# Python 3.12.3 (main, Apr 23 2024, 09:16:07) [GCC 13.2.1 20240417] on linux (archlinux, python 3.12.3-1)

# With comparison to 2**5
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g(4)"
500 loops, best of 5: 505 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_list(4)"
500 loops, best of 5: 638 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_tuple(4)"
500 loops, best of 5: 644 usec per loop

$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g(2**5)"
500 loops, best of 5: 513 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_list(2**5)"
500 loops, best of 5: 535 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_tuple(2**5)"
500 loops, best of 5: 536 usec per loop


# With comparison to 2**32
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g(4)"
500 loops, best of 5: 603 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_list(4)"
500 loops, best of 5: 642 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_tuple(4)"
500 loops, best of 5: 650 usec per loop

$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g(2**32)"
500 loops, best of 5: 912 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_list(2**32)"
500 loops, best of 5: 925 usec per loop
$ python -m timeit -s "from cc import g,g_with_in_list,g_with_in_tuple; import dis" "g_with_in_tuple(2**32)"
500 loops, best of 5: 956 usec per loop
```

For reproduction, test and also replace 2**32 with 2**5 as needed:
```py
import dis

def g(x):
    for ii in range(12_000): # large enough to trigger the adaptive bytecode
        x==2**32
        x+3
def g_with_in_list(x):
    for ii in range(12_000): # large enough to trigger the adaptive bytecode
        x in [2**32]
        x+3
def g_with_in_tuple(x):
    for ii in range(12_000): # large enough to trigger the adaptive bytecode
        x in (2**32,)
        x+3
```
Closing, thanks!
