### ISSUE TITLE
if SOURCE_DATE_EPOCH is set, don't randomize the testsuite

### ISSUE THREAD

**Issue by asottile** [python/cpython#110164]
# Feature or enhancement

### Proposal:

cc @vstinner  from https://github.com/python/cpython/pull/109570#discussion_r1342002862

cc @doko42 @stefanor  from debian -- this would allow debian to remove this patch I believe https://salsa.debian.org/cpython-team/python3/-/blob/master/debian/patches/test-no-random-order.diff

if `SOURCE_DATE_EPOCH` is set test randomization should be disabled

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://github.com/python/cpython/pull/109570#discussion_r1342002862

### Linked PRs
* gh-110168

**Comment by vstinner** [comment]
Would you be able to test if my PR gh-110168 fix your issue?

**Comment by vstinner** [comment]
My PR doesn't check SOURCE_DATE_EPOCH value. It only checks if the variable is defined.

**Comment by asottile** [comment]
@vstinner works great -- thanks!

**Comment by vstinner** [comment]
Merged, thanks for the test @asottile.

**Comment by encukou** [comment]
The feature breaks tests, see: https://github.com/python/cpython/issues/110932
If we are to maintain this case, it should probably have a buildbot.

**Comment by vstinner** [comment]
> If we are to maintain this case, it should probably have a buildbot.

I don't think that a whole buildbot is needed. Just additional tests.
