### ISSUE TITLE
Instructions to create RPM for install python3.9 and higher

### ISSUE THREAD

**Issue by Konstantin74R** [python/cpython#110101]
# Documentation

How can I get instructions or spec file for rightly creating rpm file with python3.9.17 installer(not modules) for Centos 7?
In now rpm with python installer packages don't release for Centos 7, but i need build it rightly - in install python3.9 will updates python3.6(example) and all need dependeces.
Where can I find official spec file ?

**Comment by AA-Turner** [comment]
There's no official RPM spec file, please ask your distributor (e.g. Fedora, RHEL).

A
