### ISSUE TITLE
`--disable-gil` test failures due to ABI flag

### ISSUE THREAD

**Issue by colesbury** [python/cpython#110119]
# Bug report

On Linux and macOS, `test_cppext` fails due to:

```
AssertionError: would build wheel with unsupported tag ('cp313', 'cp313td', 'linux_x86_64')
```

Example build: https://buildbot.python.org/all/#/builders/1217/builds/286

Resolving this failure will require updating `pip` and our bundled pip version. In the meantime, I will skip this test on `--disable-gil` builds.

On Windows, there are additional build failures (`test_importlib`,  `test_peg_generator`)

```
AssertionError: '_d.cp313-win32.pyd' not found in ['_d.cp313t-win_amd64.pyd', '_d.pyd']
```

```
LINK : fatal error LNK1181: cannot open input file 'python313_d.lib'
```

Example build: https://buildbot.python.org/all/#/builders/1241/builds/18

Resolving the Windows test failures require https://github.com/python/cpython/pull/110049 so that we have a standard way of determining `--disable-gil` builds from Python code.

### Linked PRs
* gh-110123
* gh-110422
* gh-116964

**Comment by colesbury** [comment]
These are fixed now. The Windows buildbot needed to *not* be run from the "Developer Command Prompt for VS 2022".

**Comment by colesbury** [comment]
Oops I was looking at the wrong green icon.

**Comment by vstinner** [comment]
> [test_cppext] Resolving this failure will require updating pip and our bundled pip version. In the meantime, I will skip this test on --disable-gil builds.

If pip is fixed, can the test upgrade pip if running NoGIL Python, as a temporary workaround?

**Comment by colesbury** [comment]
Pip's not fixed yet, but that might be possible once it's fixed. I just put up a PR https://github.com/pypa/packaging/pull/728 to update packaging.tags and then that would need to be pulled into pip's [vendored copy](https://github.com/pypa/pip/tree/main/src/pip/_vendor/packaging) of packaging.

**Comment by vstinner** [comment]
Until pip is fixed, sure, you can skip test_cppext on NoGIL build.

**Comment by colesbury** [comment]
The Windows test looks like it's passing now.
