### ISSUE TITLE
Multiline expression brackets with format specifiers don't work in f-strings

### ISSUE THREAD

**Issue by tusharsadhwani** [python/cpython#110259]
# Bug report

### Bug description:

In accordance with [PEP 701](https://peps.python.org/pep-0701/), the following code works:

```pycon
>>> x = 1
>>> f"___{
...     x
... }___"
'___1___'

>>> f"___{(
...     x
... )}___"
'___1___'
```

But the following fails:

```python
f"__{
    x:d
}__"
```

This gives:
```
  File "<stdin>", line 1
    x:d
SyntaxError: unterminated f-string literal (detected at line 2)
```

Is this intended behaviour? This is not clarified in the PEP.

---

Similarly,

```python
f"""__{
    x:d
}__"""
```

Gives:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format specifier 'd
' for object of type 'int'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-110271
* gh-110396

**Comment by pablogsal** [comment]
Thanks for the report! I have opened https://github.com/python/cpython/pull/110271 to fix it

**Comment by ericvsmith** [comment]
I'd be careful on that last one. If `x` is a `datetime.datetime`, it's a valid format spec.

``pycon
>>> x=datetime.datetime.now()
>>> f"""__{
...    x:d
... }__"""
'__d\n__'
```

**Comment by ericvsmith** [comment]
In case that's not clear: format specs for `datetime.datetime` can contain any characters, and are passed on to `strftime`. Perhaps more usefully:
```pycon
>>> f"""__{
...     x:%Y
... %m
... %d
... }__"""
'__2023\n10\n03\n__'
```

**Comment by pablogsal** [comment]
Hummmm, then what you are saying is that we should not include the newline in the single quoted case but we should do it in the triple quoted case?

**Comment by pablogsal** [comment]
Ah, indeed, this is the case because the triple quote case works like that in 3.11:

```
Python 3.11.1 (main, Jan  3 2023, 20:00:19) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> f"""__{
...    datetime.datetime.now():%Y
...    %m
...    %d
... }__"""
'__2023\n   10\n   04\n__'
```

**Comment by lysnikolaou** [comment]
> Hummmm, then what you are saying is that we should not include the newline in the single quoted case but we should do it in the triple quoted case?

I don't understand why this is the case. Shouldn't these both lead to the same AST?

Multi-line f-string:
```python3
f"""__{
    x:%Y
%m
%d
}__"""
```

Single-quoted f-string:
```python3
f"__{
    x:%Y
%m
%d
}__"
```

**Comment by ericvsmith** [comment]
I don't think it's necessarily an issue. I was just pointing out that the error shown in the original report
```python
f"""__{
    x:d
}__"""
```
(a ValueError from the bad format spec "d\n" for int) is different from the error in 
```python
f"__{
    x:d
}__"
```
(a SyntaxError). In any event, the format spec should be allowed to have newlines, including trailing newlines.

**Comment by tusharsadhwani** [comment]
@ericvsmith the triple quoted issue is indeed different from the single quoted case.

But, is that a bug?

```python
f"""{
  5:.2f
}"""
```

doesn't work on 3.11 and below as well, but I feel like it should.

**Comment by tusharsadhwani** [comment]
Agreed.

The change for single quotes should still go through IMO, because the AST should be identical for the formatted brackets even if the fstring gets split on multiple lines. For triple quotes the ASTs must be different because of backwards compatibility reasons.

**Comment by pablogsal** [comment]
There is still ambiguity on how to treat the single quote case. The most natural way **for the tokenizer** is to stop the format string on the first `\n` because the string chunks of single quote f-strings cannot spawn more than one line. So this means that this is valid:

```
>>> f"__{
... 1
... +
... 1:d
...
...
... }__"
```

but this is not:

```
>>> f"__{
... 1
... +
... 1:a
... b
...
... }__"
```

The other option is allowing multi-line format specs but that may be a bit more annoying to implement. @ericvsmith @lysnikolaou what do you think?

**Comment by tusharsadhwani** [comment]
It seems like an arbitrary limitation on code formatters: splitting any f-string on the expression brackets will be valid, unless it's the specific case of a single quoted fstring with a format specifier.

**Comment by pablogsal** [comment]
Not really, you can still be able to split the f-string in the brackets, but not the format specifier. This is fine because if you split the format specifier you are changing the f-string anyway.

To clarify, you can change:

```
f"__{1+1:xxx}__"
```

to 

```
f"__{
1
+
1:xxx


}__"
```

if you want, but you cannot split the `xxx`

**Comment by tusharsadhwani** [comment]
Makes sense, the linked PR seems good to me

**Comment by pablogsal** [comment]
So basically, in other words, if **single quoted f-strings** format specifiers cannot spawn multiple lines themselves.

**Comment by ericvsmith** [comment]
@pablogsal So I think you're saying that for single quoted f-strings, there can't be a newline in the format spec. Although it looks like that's a change, I think it's okay.

**Comment by lysnikolaou** [comment]
I think that's okay as well. Tokenizing multi-line format specifiers in single-quoted f-strings would be a bit cumbersome, so let's go with that.

**Comment by pablogsal** [comment]
> ETA: Our messages crossed. I think we're in agreement.

Sorry, I am also on a plane, so the timing of my messages may be a bit inconsistent :P

**Comment by pablogsal** [comment]
Update: i tried to check how annoying would be to support the other option (support multi-line format specifiers) and turns out that is quite easy to support thanks to how we have structured this (yay!). So **only if we want** we can support that. 

It would look like this, for clarification:

```

code = """\
f"__{
1
+
1:a
b
c

}__"
"""

print(ast.dump(ast.parse(code), indent=4))
```

which prints:

```
Module(
    body=[
        Expr(
            value=JoinedStr(
                values=[
                    Constant(value='__'),
                    FormattedValue(
                        value=BinOp(
                            left=Constant(value=1),
                            op=Add(),
                            right=Constant(value=1)),
                        conversion=-1,
                        format_spec=JoinedStr(
                            values=[
                                Constant(value='a\nb\nc\n\n')])),
                    Constant(value='__')]))],
    type_ignores=[])
```

Sorry for the back and forth @lysnikolaou @ericvsmith. I think we are free to choose whatever we prefer.

**Comment by pablogsal** [comment]
Notice that this has an important difference that I think it makes is less appealing: extra trailing newlines are included in the format specifier, which I think it will make formatters unhappy (@tusharsadhwani, please confirm)

**Comment by tusharsadhwani** [comment]
Can confirm, second option will restrict code formatting, pretty much making fstrings with format specs unformattable

**Comment by ericvsmith** [comment]
@tusharsadhwani black can't reformat the format specs without breaking datetime.datetime (for example).

@pablogsal I don't think it matters all that much. I can't imagine that there are many single quote multi-line format specs, although they no doubt exist.

**Comment by tusharsadhwani** [comment]
@ericvsmith wasn't single quote multiline format spec invalid syntax until now?

**Comment by ericvsmith** [comment]
@tusharsadhwani : I thought somewhere on this thread someone said it worked in 3.11, but I guess I misread that.
