### ISSUE TITLE
Docs: The recommended token length in 'secrets' has not been updated since 2015

### ISSUE THREAD

**Issue by JonBendtsen** [python/cpython#110229]
# Documentation

token length has not been updated since 2015, it would be nice with an update.

[How many bytes should tokens use?](https://docs.python.org/dev/library/secrets.html#how-many-bytes-should-tokens-use)

> To be secure against [brute-force attacks](https://en.wikipedia.org/wiki/Brute-force_attack), tokens need to have sufficient randomness. Unfortunately, what is considered sufficient will necessarily increase as computers get more powerful and able to make more guesses in a shorter period. As of 2015, it is believed that 32 bytes (256 bits) of randomness is sufficient for the typical use-case expected for the [secrets](https://docs.python.org/3.13/library/secrets.html#module-secrets) module.

**Comment by sunmy2019** [comment]
Makes sense. PR is welcome.

**Comment by JonBendtsen** [comment]
@sunmy2019  thanks, but I am not enough of a security expect to be able to set a sensible lenth

**Comment by AA-Turner** [comment]
@JonBendtsen -- a note for future issues, including a little more context (e.g. a link to the documentation in question or the module name) is very useful for readers.

A

**Comment by JonBendtsen** [comment]
@rhettinger I have no source, not even heresay from some guy on twitter :-D

If 32 byte is fully adequate, then I think that the text should be updated to postulate that 32 bytes are fully adequate, and for decades to come.
