### ISSUE TITLE
Unexpected PEP 8 Warning After Upgrading to Python 3.12

### ISSUE THREAD

**Issue by rly0nheart** [python/cpython#110296]
# Bug report

### Bug description:

After upgrading from Python 3.11 to Python 3.12, I started receiving a PEP 8 warning ("E231 missing whitespace after ':'") for the following line of code:
```python
def add_http_to_link(link: str) -> str:
    """
    Adds 'http://' to the URL if it doesn't already start with 'http://' or 'https://'.

    :param link: The link to modify.
    :return: The modified URL.
    """
    if not link.startswith(("http://", "https://")):
        return f"http://{link}"  # <- E231 missing whitespace after ':'
    return link
```
In Python 3.11, this line did not trigger any PEP 8 warnings. I believe this might be a false positive, as the colon is not a binary operator but part of the string format.

## Additional Information:
* PyCharm version: 2023.2.1

## Screennshot
![2023-10-03_17-06](https://github.com/python/cpython/assets/74001397/4ed50c06-dab4-45ae-b5fc-a4b6fa0b9411)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
Hi! This warning isn't emitted by CPython. It's emitted by a third-party linting tool (probably [pycodestyle](https://github.com/PyCQA/pycodestyle)).

Your best bet is to:
1. Make sure you're using the most recent version of that linting tool, and;
2. If the error still occurs with the most recent version, file a bug with that tool.

Unfortunately this has nothing to do with CPython, so I'm going to close this issue for now, as this tracker is for bugs in the Python programming language itself, not third-party tools written in Python. For general help and assistance with Python, https://discuss.python.org/c/users/7 is a good place to ask questions :-)

**Comment by hugovk** [comment]
This is a bug in PyCharm, I've seen it for Python 3.11 too.

Here's the PyCharm bug report:

https://youtrack.jetbrains.com/issue/PY-63374/E231-false-positive-in-f-strings-after-PEP-701-support

**Comment by rly0nheart** [comment]
> This is a bug in PyCharm, I've seen it for Python 3.11 too.
> 
> Here's the PyCharm bug report:
> 
> https://youtrack.jetbrains.com/issue/PY-63374/E231-false-positive-in-f-strings-after-PEP-701-support

Ah thanks for this!

It doesn't even seem to have been resolved.
