### ISSUE TITLE
Unhandled error of `PyList_Reverse` in `posixmodule`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110264]
# Bug report

https://github.com/python/cpython/blob/8c071373f12f325c54591fe990ec026184e48f8f/Modules/posixmodule.c#L574-L585

Here we should decref `cpy` and early return if `reverse` fails.

### Linked PRs
* gh-110265

**Comment by serhiy-storchaka** [comment]
It never returns an error here.

**Comment by sobolevn** [comment]
Thanks! I've missed that.
