### ISSUE TITLE
Unix mmap: Bus error on access of anonymous memory mapping after resize > pagesize 

### ISSUE THREAD

**Issue by drewja** [python/cpython#110243]
# Crash report

### What happened?

```python
import mmap
mem = mmap.mmap(-1, mmap.PAGESIZE)
mem.resize(mmap.PAGESIZE * 2)
#                   ^ no error
print(mem[mmap.PAGESIZE-1])
#                  ^ still ok
print(mem[mmap.PAGESIZE])
# Bus error (core dumped)
```
Allocations (and access) of memory greater the pagesize work as expected (e.g. mmap(-1, mmap.PAGESIZE + n)  ).
This crash is specific to an access of memory where index >= PAGESIZE, after resizing.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.5 (main, Aug 28 2023, 20:02:58) [GCC 13.2.1 20230801]

**Comment by drewja** [comment]
I have not attempted to debug the core yet but will do later on when I have time.  Here is a link to the source code for resize method: https://github.com/python/cpython/blob/fc2cb86d210555d509debaeefd370d5331cd9d93/Modules/mmapmodule.c#L512

**Comment by Mazogedoo** [comment]
import mmap
mem = mmap.mmap(-1, mmap.PAGESIZE)
mem.resize(mmap.PAGESIZE * N)
#                   ^ no error
print(mem[mmap.PAGESIZE-1])
#                  ^ still ok
print(mem[mmap.PAGESIZE])
# Bus error (core dumped)

**Comment by sunmy2019** [comment]
It's an upstream bug: https://bugzilla.kernel.org/show_bug.cgi?id=8691

```
import mmap
mem = mmap.mmap(-1, mmap.PAGESIZE, flags=mmap.MAP_PRIVATE)
mem.resize(mmap.PAGESIZE * 2)
print(mem[mmap.PAGESIZE]) # this works
```

https://stackoverflow.com/questions/61949694/linux-mremap2-map-anonymousmap-shared-cant-access-new-area
