### ISSUE TITLE
`test_unicode` always fails during a PGO-optimised build (because it does not exist)

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#110276]
# Bug report

### Bug description:

As part of a PGO-optimised build, a selection of tests are run in order for the PGO build to take place (if I understand correctly, these tests are used to gather data on which functions in Python are performance-critical and should be optimised). Exactly which tests are run is hardcoded here:

https://github.com/python/cpython/blob/bb2e96f6f4d6c397c4eb5775a09262a207675577/Lib/test/libregrtest/pgo.py#L1-L51

`test_unicode` is specified as one of the tests to be run as part of this selection. However, `test_unicode` always fails during a PGO build. Why? Because it was renamed as `test_str` in #13172 (by @asqui). This hasn't been noticed until now because the PGO build is still marked as a "success" even if some tests fail during the analysis phase.

The fix for the immediate issue is simple: don't try to run `test_unicode` as part of the PGO-optimised build (it doesn't exist anymore); run `test_str` instead. Longer term, though, we might want to look at making the PGO build fail if it tries to run nonexistent tests. It's probably correct for the build to continue even if some tests fail during the analysis phase, but perhaps we could make an exception for this _specific kind_ of failure (attempting to run nonexistent tests).

Cc. @hugovk as the primary reviewer for #13172, and @vstinner as a libregrtest expert.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-110277
* gh-110295
* gh-111950

**Comment by AlexWaygood** [comment]
The failure wasn't "just on my machine": you can see the "test_unicode failed (uncaught exception)" message in the logs for our PGO buildbots too. Example: https://buildbot.python.org/all/#/builders/249/builds/6518/steps/3/logs/stdio.



> Maybe the problem is that Makefile.pre.in ignores failures :-(

Hmm, I'm on Windows, and the test failure doesn't cause a PGO build (which doesn't use the Makefile on Windows) to fail on my machine either. The test fails as part of the build, the failure is reported and logged to the terminal, but the build then continues and is marked as a success.

**Comment by vstinner** [comment]
> FWIW, the failure wasn't "just on my machine": you can see the "test_unicode failed (uncaught exception)" message in the logs for our PGO buildbots too.

A log is not really what I expect when I say "failure". I expected a red buildbot :-) Otherwise, it's too easy to miss.

**Comment by vstinner** [comment]
I wrote PR #110295 to no longer ignore PROFILE_TASK failure silently.

**Comment by vstinner** [comment]
My commit https://github.com/python/cpython/commit/6ab6040054e5ca2d3eb7833dc8bf4eb0bbaa0aac no longer ignores PROFILE_TASK failure silently.

**Comment by AlexWaygood** [comment]
> My commit [6ab6040](https://github.com/python/cpython/commit/6ab6040054e5ca2d3eb7833dc8bf4eb0bbaa0aac) no longer ignores PROFILE_TASK failure silently.

It sounds like there is little appetite among the core devs who maintain the Windows build for an equivalent `PCBuild` fix, so I'll close this out now. Thanks @vstinner!

**Comment by vstinner** [comment]
PGO builds are tested daily on Unix by buildbots. So now we should get any similar issue get reported way earlier.
