### ISSUE TITLE
Build warnings - October 2023

### ISSUE THREAD

**Issue by TabLand** [python/cpython#110266]
# Bug report

### Bug description:

Building python from source returns the following warnings:
```
./Include/internal/pycore_call.h:185:16: warning: ‘small_stack’ may be used uninitialized [-Wmaybe-uninitialized]
./Include/internal/pycore_call.h:187:11: warning: ‘small_stack’ may be used uninitialized [-Wmaybe-uninitialized]
./Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time
./Modules/_decimal/libmpdec/io.c:348:40: warning: writing 1 byte into a region of size 0 [-Wstringop-overflow=]
./Modules/_xxinterpchannelsmodule.c:104:1: warning: ‘get_module_from_owned_type’ defined but not used [-Wunused-function]
```

commit 8c071373f12f325c54591fe990ec026184e48f8f (HEAD -> main, origin/main, origin/HEAD)
Date:   Tue Oct 3 08:10:16 2023 +0200

Logs attached: [build.log](https://github.com/python/cpython/files/12790164/build.log)

I will aim to investigate these one by one this week

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-110269

**Comment by AlexWaygood** [comment]
> ./Modules/_decimal/libmpdec/context.c:56: warning: mpd_setminalloc: ignoring request to set MPD_MINALLOC a second time

This one dates from #107287: see https://github.com/python/cpython/pull/107287#issuecomment-1656040379

**Comment by TabLand** [comment]
Relates to #103186

**Comment by sobolevn** [comment]
This is strange: 

```
» ag get_module_from_owned_type   
Modules/_xxinterpchannelsmodule.c
104:get_module_from_owned_type(PyTypeObject *cls)
2349:    PyObject *mod = get_module_from_owned_type(cls);
                                      
```

**Comment by TabLand** [comment]
Hi @iritkatriel,

Apologies for the radio silence...
I can no longer see these warnings in recent build logs.

Many thanks everyone!
