### ISSUE TITLE
`test_zlib` uses some very old `random` API

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110332]
# Bug report

Here's the problematic code: https://github.com/python/cpython/blob/1465386720cd532a378a5cc1e6de9d96dd8fcc81/Lib/test/test_zlib.py#L513-L525

It always fails with `AttributeError`, because `random.WichmannHill()` does not exist.

This is some old compatibility class that was removed a long time ago:

```
The attributes random.whseed and random.__whseed have no meaning for
  the new generator.  Code using these attributes should switch to a
  new class, random.WichmannHill which is provided for backward
  compatibility and to make an alternate generator available.
```

So, I propose to simplify this test.

### Linked PRs
* gh-110334
* gh-110348
* gh-110349

**Comment by AlexWaygood** [comment]
Thanks!
