### ISSUE TITLE
Import Error for Site Packages

### ISSUE THREAD

**Issue by JemmaFromJupiter** [python/cpython#110370]
# Bug report

### Bug description:

``` python
from __future__ import annotations

import numpy as np
```

This small block of code is returning the Error:

``` powershell
Traceback (most recent call last):
  File "c:\Users\stare\Saved Games\OneDrive\Desktop\Programs\Tests\practice\genericTyping.py", line 3, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
```

I have tried uninstalling and reinstalling the packages, I have checked that it is installed in the right place. No Idea why this might be happening.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
You don't have numpy installed. It is a third-party package, not part of Python itself. Try `pip install numpy`, `python -m pip install numpy`, or a similar command.

**Comment by JemmaFromJupiter** [comment]
> You don't have numpy installed. It is a third-party package, not part of Python itself. Try `pip install numpy`, `python -m pip install numpy`, or a similar command.

I do have numpy installed, I checked the packages, I uninstalled and reinstalled numpy.

**Comment by JemmaFromJupiter** [comment]
I figured it out on my own, I had to uninstall the previous version of python as pip was still installing for my python 3.11 installation.
