### ISSUE TITLE
test__xxinterpchannels leaks [21, 21, 21] references

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110300]
```
./python -m test test__xxinterpchannels -R 3:3
(...)
test__xxinterpchannels leaked [21, 21, 21] references, sum=63
```

Regression introduced by: commit a8f5dab58daca9f01ec3c6f8c85e53329251b05d

```
commit a8f5dab58daca9f01ec3c6f8c85e53329251b05d
Author: Eric Snow <ericsnowcurrently@gmail.com>
Date:   Mon Oct 2 14:47:41 2023 -0600

    gh-76785: Module-level Fixes for test.support.interpreters (gh-110236)
    
    * add RecvChannel.close() and SendChannel.close()
    * make RecvChannel and SendChannel shareable
    * expose ChannelEmptyError and ChannelNotEmptyError

 Lib/test/support/interpreters.py  |  30 +++++--
 Lib/test/test_interpreters.py     |  16 ++++
 Modules/_xxinterpchannelsmodule.c | 185 +++++++++++++++++++++++++++++++++-----
 3 files changed, 206 insertions(+), 25 deletions(-)
```

Example of build: https://buildbot.python.org/all/#/builders/320/builds/855

cc @ericsnowcurrently 

### Linked PRs
* gh-110318

**Comment by ericsnowcurrently** [comment]
FWIW, test_interpreters has much worst leaks.  They are due to `_xxinterpchannels._register_end_types()`.  I'm going to temporarily drop that call and circle back to what's causing the leaks there.

**Comment by ericsnowcurrently** [comment]
I've merged a temporary fix, but I still need to resolve the underlying issue.

**Comment by vstinner** [comment]
``./python -m test test__xxinterpchannels -R 3:3`` no longer leaks, I close the issue.

**Comment by ericsnowcurrently** [comment]
FTR, I followed up on gh-110607.
