### ISSUE TITLE
In _GUARD_TYPE_VERSION, can type_version be 0?

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#110319]
Currently `_GUARD_TYPE_VERSION` looks like this in Python/bytecodes.c:
```
        op(_GUARD_TYPE_VERSION, (type_version/2, owner -- owner)) {
            PyTypeObject *tp = Py_TYPE(owner);
            assert(type_version != 0);
            DEOPT_IF(tp->tp_version_tag != type_version);
        }
```
My question is about that `assert`. As I split more opcodes into uops, I find some variations of this -- a few opcodes didn't have such an `assert`, a few others have it *after* the `DEOPT_IF` call. Are there really places where the cache can contain a `type_version` field that is zero? And if so, should those match a zero `tp_version_tag` in the type?

@markshannon @brandtbucher 

### Linked PRs
* gh-112226

**Comment by brandtbucher** [comment]
`type_version` must not be zero. A zero `tp_version_tag` means either one has not been assigned yet, or we have run out of new versions.

When we specialize anything requiring a type version, we *must* fail to specialize if we request a type version (usually via a call to `_PyType_Lookup` and it's `0`. So the invariant `assert(type_version != 0)` must hold for every type (and dictionary keys, and function) version we use.

**Comment by gvanrossum** [comment]
Examples where the `assert` comes last:

- `LOAD_ATTR_PROPERTY`
- `LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN`
- `LOAD_ATTR_CLASS` has code *similar* to this (it's different because the type is on the stack instead of the instance) with the `assert` last

Example without `assert`:
- `LOAD_ATTR_METHOD_LAZY_DICT`

Is this all just random differences, or is there a reason? Would it make sense to move the `assert` after the `DEOPT_IF` and be done with it?

**Comment by brandtbucher** [comment]
Lets assert it before the `DEOPT_IF`, to make it clear that it should *never* be zero.
