### ISSUE TITLE
`test_contextlib_async` produces several `RuntimeWarning`s

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110378]
# Bug report

```
» ./python.exe -m test test_contextlib_async
Using random seed 908291980
0:00:00 load avg: 4.08 Run 1 test sequentially
0:00:00 load avg: 4.08 [1/1] test_contextlib_async
/Users/sobolev/Desktop/cpython/Lib/contextlib.py:701: RuntimeWarning: coroutine method 'aclose' of 'AsyncContextManagerTestCase.test_contextmanager_trap_second_yield.<locals>.whoo' was never awaited
  async def __aenter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/Users/sobolev/Desktop/cpython/Lib/contextlib.py:701: RuntimeWarning: coroutine method 'aclose' of 'AsyncContextManagerTestCase.test_contextmanager_trap_yield_after_throw.<locals>.whoo' was never awaited
  async def __aenter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/Users/sobolev/Desktop/cpython/Lib/contextlib.py:701: RuntimeWarning: coroutine method 'aclose' of 'TestAbstractAsyncContextManager.test_async_gen_propagates_generator_exit.<locals>.gen' was never awaited
  async def __aenter__(self):
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

== Tests result: SUCCESS ==

1 test OK.

Total duration: 121 ms
Total tests: run=58
Total test files: run=1/1
Result: SUCCESS
```

This can be fixed by moving away from legacy `@_async_test` and by using stabel `IsolatedAsyncioTestCase`.

https://github.com/python/cpython/blob/6592976061a6580fee2ade3564f6497eb685ab67/Lib/test/test_contextlib_async.py#L14-L20

### Linked PRs
* gh-110379
* gh-110499
* gh-110500
* gh-110588
* gh-110589
* gh-110610
* gh-110611

**Comment by serhiy-storchaka** [comment]
There are two issues here.

1. `test_async_gen_propagates_generator_exit` (added in bpo-33786/#77967, PR #7467) creates an asynchronous generator, but do not iterate it to the end (it would close it implicitly) and do not close it explicitly. Actually, this test does not work at all. It is passed with unpatched code, it only prints a traceback from implicitly called destructor. It also contains code not related to the issue. This test should be rewritten.
2. `test_contextmanager_trap_yield_after_throw` and `test_contextmanager_trap_second_yield` test `asynccontextmanager` with an asynchronous generator with second `yield`. `asynccontextmanager` raises RuntimeError, but leaves the underlying asynchronous generator object not closed. Such generator is a programming error, and we don't have to clean up after this, but the "gen" attribute of `asynccontextmanager` object is an implementation detail, so it is better to not leave it to user and do clean up. The `__exit__` method should close the underlying asynchronous generator object.

Moving to IsolatedAsyncioTestCase looks like a good thing, but only after fixing the deeper issues.

**Comment by ambv** [comment]
This is solved, thanks! ✨ 🍰 ✨

**Comment by serhiy-storchaka** [comment]
Thank you for your reviews @ambv.
