### ISSUE TITLE
Tkinter demo: show Tcl/Tk patchlevel instead of version

### ISSUE THREAD

**Issue by chrstphrchvz** [python/cpython#110345]
# Feature or enhancement

### Proposal:

When dealing with issue reports involving Tcl/Tk, it is often much more helpful to know what Tcl/Tk calls the “patchlevel” (e.g. 8.6.13) than what Tcl/Tk calls the “version” (e.g. 8.6), because only the former usually corresponds to individual Tcl/Tk releases (and bugs tend to be fixed between these releases).

The test program in `tkinter._test()` (as invoked by `python3.y -m tkinter`) currently shows the Tcl/Tk “version”. So if Tkinter users are consulting this demo to know what Tcl/Tk is on their system when reporting issues, then I believe it would be better for this demo to show the “patchlevel” instead.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-110350
* gh-114252
* gh-114253

**Comment by serhiy-storchaka** [comment]
Backported because it rather has relation to testing and troubleshooting.
