### ISSUE TITLE
Better communicate that `IOError` and `WindowsError` are just aliases of `OSError` now

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110497]
# Bug report

While working on some Windows-related typeshed PRs, I've noticed that some places in docs are very clear about this change. For example:

```rst
.. versionchanged:: 3.3
   :exc:`IOError` used to be raised; it is now an alias of :exc:`OSError`.
```

It is clear that `OSError` is the same as `IOError` now.

But, there are several places where it is not clear. Example:

https://github.com/python/cpython/blob/92ca90b7629c070ebc3b08e6f03db0bb552634e3/Doc/library/gettext.rst#L165-L170

It might be confusing: people might think that right now `OSError` and `IOError` are different. 
Let's add notes about explicit alias to several places that miss it.

### Linked PRs
* gh-110498
* gh-110545
* gh-110546

**Comment by nanjekyejoannah** [comment]
Closing because PR is merged.
