### ISSUE TITLE
ipaddress constructor allows bool argument

### ISSUE THREAD

**Issue by nesle** [python/cpython#110466]
# Bug report

### Bug description:

```python
>>> ipaddress.ip_address(True)
IPv4Address('0.0.0.1')
>>> ipaddress.ip_address(False)
IPv4Address('0.0.0.0')
```
I'm thinking this is unintentional and would be better off as a ValueError.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
This is just because `bool` is a subclass of `int`. Disallowing `bool` would be an arbitrary violation of LSP. I don't see any reason to make this change.

**Comment by AA-Turner** [comment]
I agree with Alex, note also ``True == 1`` and ``False == 0``

A
