### ISSUE TITLE
Nested F-string with same quotes fail; Why does Python interpret it as new Dictionary initialization in same line?

### ISSUE THREAD

**Issue by AhnafCodes** [python/cpython#110426]
# Bug report

### Bug description:

```python
Python 3.12.0 (v3.12.0:0fb18b02c8, Oct  2 2023, 09:45:56) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin

>>> fruit = {'name': 'Apple', 'price': 10}
>>> f'<li class="item"> { fruit["name"] } </li>'
'<li class="item"> Apple </li>'
>>> f"<li class="item"> { fruit["name"] } </li>"
  File "<stdin>", line 1
    f"<li class="item"> { fruit["name"] } </li>"
                 ^^^^
SyntaxError: invalid syntax
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by Earth-And-Moon** [comment]
The error happens because you are using quotes inside the string. You need to edit it like this:
```
f'<li class="item"> { fruit["name"] } </li>'
```
or
```
    f"<li class=\"item\"> { fruit["name"] } </li>"
```
Using " inside a string opened and closed by " is not allowed, so you need to escape the inner quotes with \" or use other quotes.

**Comment by JelleZijlstra** [comment]
These quotes are in the string part of the f-string, not the interpolated bits. Python 3.12 doesn't change anything there.

I would recommend asking for help in https://discuss.python.org/c/users/7 first before opening an issue.

**Comment by AhnafCodes** [comment]
Reason give Python interprets it as parts as per https://github.com/python/cpython/issues/110369


> 
> ```
> f"FRUIT"     {fruit['name']}   ""
> ---------     ---------------   --
>   fstring           set       string
> ```
> 
> It's interpreted as 3 parts.
> ...
> ```

Why does Python interpret it as new Set/Dictionary initialization in/on the same line? as string and with no "variable name" or "assignment operator"(=) present. Instead of trying the next assumption that the fstring is nested  error
