### ISSUE TITLE
Implement biased reference counting in `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#110481]
# Feature or enhancement

CPython's current reference counting implementation would not be thread-safe without the GIL. In `--disable-gil` builds, we should implement biased reference counting, which is thread-safe and has lower execution overhead compared to plain atomic reference counting. The design is described in the ["Biased Reference Counting"](https://peps.python.org/pep-0703/#biased-reference-counting) section of PEP 703.

This will require changing the `PyObject` struct in `--disable-gil` builds. I expect the `--disable-gil` struct to look like:

```c
struct _object {
  uintptr_t ob_tid;
  uint16_t _padding;
  uint8_t ob_mutex;
  uint8_t ob_gc_bits;
  uint32_t ob_ref_local;
  Py_ssize_t ob_ref_shared;
  PyTypeObject *ob_type;
};
```

Not all the fields will be used immediately, but it will be easier to include them as part of implementing this change.

I intend to split the implementation across (at least) two PRs to make it easier to review.
1. The first PR will add the new `PyObject` fields and implement the core biased reference counting operations, but not the [inter-thread queue](https://github.com/colesbury/nogil-3.12/blob/nogil-3.12/Python/pyrefcnt.c) to reduce the initial complexity. (done)
2. A later PR will implement the inter-thread queue. (not yet implemented)

The inter-thread queue is needed eventually (before *actually* disabling the GIL), but since the `--disable-gil` builds still currently require the GIL, it doesn't have to be in the initial PR.

### Linked PRs
* gh-110764
* gh-111503
* gh-111505
* gh-111560
* gh-111974
* gh-112174
* gh-112180
* gh-112595
* gh-114824
* gh-117271

**Comment by vstinner** [comment]
@colesbury @corona10: Is there anything left? Or can we close the issue?

**Comment by encukou** [comment]
Since #117271 was merged, `test_multiprocessing` tests are consistently failing on noGIL Refleaks buildbots. For example: https://buildbot.python.org/all/#/builders/1368/builds/606

**Comment by colesbury** [comment]
I put up https://github.com/python/cpython/pull/117370, which fixes the refleaks.
