### ISSUE TITLE
glob module docs in wrong order

### ISSUE THREAD

**Issue by barneygale** [python/cpython#110417]
The documentation of the `glob` module is in a slightly odd order:

1. A description of the globbing language (wildcards etc)
2. A "see also: pathlib" block
3. Function documentation:
   a. `glob()`
   b. `iglob()`
   c. `escape()`
4. Two examples of using `glob()`
5. A "see also: fnmatch" block

In particular, the description of `glob()` and the examples of its usage are interrupted by descriptions of `iglob()` and `escape()`.

I think this might be better:

1. A description of the globbing language (wildcards etc)
5. A "see also: fnmatch" block
2. A "see also: pathlib" block
3. Function documentation:
   a. `glob()`, including two examples of its usage
   b. `iglob()`
   c. `escape()`

### Linked PRs
* gh-110418

**Comment by terryjreedy** [comment]
Why not backport?  Conflicts from changes?
