### ISSUE TITLE
I have problems with pip

### ISSUE THREAD

**Issue by ghost** [python/cpython#110432]
# Bug report

### Bug description:

hi, I´m using python 3.12.0 have problems when I want to install a library with pip. for example: I want to install the cx_freeze library and it gives me an error (and it doesn't install it). cmd returns me this when I try to install the library cx_Freeze:

Collecting cx-Freeze
  Using cached cx_Freeze-6.15.9.tar.gz (1.7 MB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [40 lines of output]
      Collecting setuptools<69,>=62.6
        Obtaining dependency information for setuptools<69,>=62.6 from https://files.pythonhosted.org/packages/bb/26/7945080113158354380a12ce26873dd6c1ebd88d47f5bc24e2c5bb38c16a/setuptools-68.2.2-py3-none-any.whl.metadata
        Using cached setuptools-68.2.2-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel>=0.38.4
        Obtaining dependency information for wheel>=0.38.4 from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting cx_Logging>=3.1
        Using cached cx_Logging-3.1.0.tar.gz (27 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Installing backend dependencies: started
        Installing backend dependencies: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Using cached setuptools-68.2.2-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Building wheels for collected packages: cx_Logging
        Building wheel for cx_Logging (pyproject.toml): started
        Building wheel for cx_Logging (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        Building wheel for cx_Logging (pyproject.toml) did not run successfully.
        exit code: 1

        [7 lines of output]
        running bdist_wheel
        running build
        running build_ext
        creating build
        creating build\implib.win-amd64-cpython-312
        building 'cx_Logging' extension
        error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
        [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cx_Logging
      Failed to build cx_Logging
      ERROR: Could not build wheels for cx_Logging, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Could they fix it in the next update?

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!

As it is written in the error, you need to install Microsoft Visual C++ 14.0 or greater.
However, this repository intended as bug tracker for CPython, this issue doesn't looks like a bug related to CPython.

I would recommend asking for help in https://discuss.python.org/c/users/7.

**Comment by gaogaotiantian** [comment]
The actual issue here is that `cx_Freeze` does not support 3.12 yet. That means they do not have a wheel(`.whl` file) with 3.12, so you had to install from source. You don't have all the requirements to build from source (build tool missing according to your error message).

So, you should submit an issue in `cx_Freeze` to ask them to support 3.12 :)
