### ISSUE TITLE
modifying installation via Windows settings prompts to save "12.0-amd64.exe" in system32

### ISSUE THREAD

**Issue by landfillbaby** [python/cpython#110469]
# Bug report

### Bug description:

when trying to modify installation via either Windows 10 settings -> Apps & features -> Modify, or Control Panel -> Programs and Features, the installer prompts me to save "12.0-amd64.exe" in system32, several times. whether i save or cancel it does not show any errors. the file is actually just the installer from https://www.python.org/ftp/python/3.12.0/python-3.12.0-amd64.exe again.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by landfillbaby** [comment]
oh nevermind. this is a bug with Ninite actually

**Comment by landfillbaby** [comment]
although there should maybe be safeguards against this problem just in case

**Comment by AA-Turner** [comment]
Please report to Ninite first, given the initial bug is with them.

A
