### ISSUE TITLE
a reference to python-3.5 in Tutorial appendix

### ISSUE THREAD

**Issue by partev** [python/cpython#110531]
# Documentation

Tutorial appendix refers to python3.5 twice here: https://docs.python.org/3.13/tutorial/appendix.html
in section 16.1.2:

![image](https://github.com/python/cpython/assets/23830955/4f21d5c8-d300-439b-9285-7384ad2d4cf1)
and in section 16.1.4:

![image](https://github.com/python/cpython/assets/23830955/1ddb0c5d-2e3d-496d-997c-0f64e6ae2ec1)

Should these be changed to **python3.13** or **python3** or is it not worth fixing it at all?

**Comment by nanjekyejoannah** [comment]
I don't think the change is necessary,  may have been just an example, if you toggle between versions you will see its the same py3.5 reference in the context of an example I guess.

**Comment by nanjekyejoannah** [comment]
You can reopen the issue if you insist.
