### ISSUE TITLE
fix a URL redirect to wikipedia article on Fibonacci numbers

### ISSUE THREAD

**Issue by partev** [python/cpython#110534]
# Documentation

Section 3.2 of the tutorial: https://docs.python.org/3.13/tutorial/introduction.html#first-steps-towards-programming
links to https://en.wikipedia.org/w/index.php?title=Fibonacci_number which redirects to https://en.wikipedia.org/wiki/Fibonacci_sequence

### Linked PRs
* gh-110535
* gh-110536
* gh-110537

**Comment by terryjreedy** [comment]
I confirmed the correction.
