### ISSUE TITLE
`test_*_code` functions in `_testcapi/getargs.c` have memory leaks

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110572]
# Bug report

I don't think it is *very* important, since this is just a test, but why have it when it is spotted?

1. `test_k_code`: https://github.com/python/cpython/blob/326c6c4e07137b43c49b74bd5528619360080469/Modules/_testcapi/getargs.c#L331-L398 

On errors `tuple` is not decrefed.
Also, note these lines: https://github.com/python/cpython/blob/326c6c4e07137b43c49b74bd5528619360080469/Modules/_testcapi/getargs.c#L358-L374

Here' we leave a `tuple` is a semi-broken state. Its 0'th item has a reference count of 0.
We should also recreate a `tuple` here with the new items. `test_L_code` also has this problem.

2. https://github.com/python/cpython/blob/326c6c4e07137b43c49b74bd5528619360080469/Modules/_testcapi/getargs.c#L684-L732

On errors `tuple` is not decrefed. And `num` is re-assigned without `tuple` cleanup.

3. https://github.com/python/cpython/blob/326c6c4e07137b43c49b74bd5528619360080469/Modules/_testcapi/getargs.c#L734-L767

As well, `tuple` is leaked on errors.

I have a PR ready.

### Linked PRs
* gh-110573
* gh-111161
* gh-111214

**Comment by serhiy-storchaka** [comment]
Are these tests still needed?

**Comment by sobolevn** [comment]
`'s'`, `'L'`, and `'k'` are still mentioned in https://docs.python.org/3.12/howto/clinic.html#how-to-use-real-argument-clinic-converters-instead-of-legacy-converters

So, I guess we still need to make sure that they are supported and work correctly.
They are even not deprecated, just called "legacy".

**Comment by serhiy-storchaka** [comment]
I mean that they are tested in `Lib/test/test_capi/test_getargs.py` using wrappers like `getargs_k()`. And #110628 adds tests for functions like `PyLong_AsUnsignedLongMask()`.

**Comment by sobolevn** [comment]
In this case, yes. We can some logic from these tests to `test_long.py`.

Things that right now are not tested in `test_long` (this list might be not full):
- `test_k_code`: `PyLong_FromString("FFFFFFFFFFFFFFFFFFFFFFFF", NULL, 16)`
- `test_k_code`: `PyLong_FromString("-FFFFFFFF000000000000000042", NULL, 16)`
- `test_s_code`: `getargs_s('t\xeate')` (however, `'abc\xe9'` is tested)
- `test_s_code`: `getargs_z('t\xeate')` (however, `'abc\xe9'` is tested)

So, do you agree on this plan?
1. I convert this PR to delete these tests, it will be in a draft state for now
2. We ensure that all checks from `test_*_code` are in either `test_long.py` or in `test_getargs.py`
3. We merge your PR with `test_long.py` and possible PRs to `test_getargs.py`
4. We merge my PR from `1.` with these tests removed

**Comment by serhiy-storchaka** [comment]
I merged your PR, and it will be backported to 3.12. In main we should consider removing this tests.

`PyLong_FromString("FFFFFFFFFFFFFFFFFFFFFFFF", NULL, 16)` is just a way to create a long int for the following test of `PyLong_AsUnsignedLongMask()`. There are already tests for `PyLong_AsUnsignedLongMask()` for argument outside of 0..ULONG_MAX. There are also similar tests for the "k" format unit. I think that all this can be deleted.

**Comment by hugovk** [comment]
Thanks for the PRs.
