### ISSUE TITLE
Tkinter, window lose its focus after some codes

### ISSUE THREAD

**Issue by githubuser11123** [python/cpython#110521]
# Bug report

### Bug description:

```python
import tkinter
from tkinter import ttk 

root = tkinter.Tk()

entry = ttk.Entry(root)
entry.grid()
entry.focus_set()

root.state('withdrawn')
root.update()

root.resizable(True, True)
root.resizable(True, True)  # if delete this line, entry will get focus at first time after running script

root.state('normal')

root.mainloop()
```

Running the above script in IDLE, the newly created window will not get focus. But after deleting the commented line, the newly created window and entry widget will get focus. There is no reason for the difference, so I suppose it's a bug.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ParamThakkar123** [comment]
The behavior you're observing in your code is not necessarily a bug, but rather a result of the way you are managing the focus and window states in your tkinter application.

In your code, you are using the root.state('withdrawn') method to initially hide the window and then root.state('normal') to show it again. When you hide the window using withdrawn, it does not get focus automatically when you show it again with normal.

However, when you delete the line root.resizable(True, True), it seems to trigger some internal behavior in the tkinter library that results in the window getting focus when it's shown again.

To make the window get focus consistently after showing it, you can explicitly call the focus_force() method on the root window after setting its state to 'normal'. Here's an updated version of your code:
"""
import tkinter
from tkinter import ttk

root = tkinter.Tk()

entry = ttk.Entry(root)
entry.grid()
entry.focus_set()

root.state('withdrawn')
root.update()

root.resizable(True, True)

# Show the window and give it focus
root.state('normal')
root.focus_force()

root.mainloop()
"""

**Comment by ParamThakkar123** [comment]
The behavior you're observing in your code is not necessarily a bug, but rather a result of the way you are managing the focus and window states in your tkinter application.

In your code, you are using the root.state('withdrawn') method to initially hide the window and then root.state('normal') to show it again. When you hide the window using withdrawn, it does not get focus automatically when you show it again with normal.

However, when you delete the line root.resizable(True, True), it seems to trigger some internal behavior in the tkinter library that results in the window getting focus when it's shown again.

To make the window get focus consistently after showing it, you can explicitly call the focus_force() method on the root window after setting its state to 'normal'. Here's an updated version of your code:

```
import tkinter
from tkinter import ttk

root = tkinter.Tk()

entry = ttk.Entry(root)
entry.grid()
entry.focus_set()

root.state('withdrawn')
root.update()

root.resizable(True, True)

# Show the window and give it focus
root.state('normal')
root.focus_force()

root.mainloop()
```

**Comment by githubuser11123** [comment]
> The behavior you're observing in your code is not necessarily a bug, but rather a result of the way you are managing the focus and window states in your tkinter application.
> 
> In your code, you are using the root.state('withdrawn') method to initially hide the window and then root.state('normal') to show it again. When you hide the window using withdrawn, it does not get focus automatically when you show it again with normal.
> 
> However, when you delete the line root.resizable(True, True), it seems to trigger some internal behavior in the tkinter library that results in the window getting focus when it's shown again.
> 
> To make the window get focus consistently after showing it, you can explicitly call the focus_force() method on the root window after setting its state to 'normal'. Here's an updated version of your code:
> 
> ```
> import tkinter
> from tkinter import ttk
> 
> root = tkinter.Tk()
> 
> entry = ttk.Entry(root)
> entry.grid()
> entry.focus_set()
> 
> root.state('withdrawn')
> root.update()
> 
> root.resizable(True, True)
> 
> # Show the window and give it focus
> root.state('normal')
> root.focus_force()
> 
> root.mainloop()
> ```

Thanks for reply. However, your code doesn't work, I try it but the window still can't get focus automatically. And may I state it more clearly, it's not a problem about whether the sentence "root.resizable(True, True)" exists or not, it's about one or two sentences "root.resizable(True, True)", they make difference! In my real project, I happen to have to use those two duplicate sentences, and get a unwilling result.

**Comment by githubuser11123** [comment]
> The behavior you're observing in your code is not necessarily a bug, but rather a result of the way you are managing the focus and window states in your tkinter application.
> 
> In your code, you are using the root.state('withdrawn') method to initially hide the window and then root.state('normal') to show it again. When you hide the window using withdrawn, it does not get focus automatically when you show it again with normal.
> 
> However, when you delete the line root.resizable(True, True), it seems to trigger some internal behavior in the tkinter library that results in the window getting focus when it's shown again.
> 
> To make the window get focus consistently after showing it, you can explicitly call the focus_force() method on the root window after setting its state to 'normal'. Here's an updated version of your code:
> 
> ```
> import tkinter
> from tkinter import ttk
> 
> root = tkinter.Tk()
> 
> entry = ttk.Entry(root)
> entry.grid()
> entry.focus_set()
> 
> root.state('withdrawn')
> root.update()
> 
> root.resizable(True, True)
> 
> # Show the window and give it focus
> root.state('normal')
> root.focus_force()
> 
> root.mainloop()
> ```

It 's not a problem about whether this sentence "root.resizable(True, True)" exits or not, it's a problem about one or two sentences "root.resizable(True, True)". In my real project, I happen to have to use those two duplicate sentences consecutively, and get an unwilling result.
Anyway, I learn from your code to use "entry.focus_force" and it solve my problem. Thank you for reply. 
Still, it makes one confused why one and two same sentence make a difference. I hope it's an insignificant matter, and I'll close this issure afterwhile.
