### ISSUE TITLE
No distutils folder

### ISSUE THREAD

**Issue by posi-olomo** [python/cpython#110583]
# Bug report

### Bug description:

There is no distutils folder in the Lib folder. That's all. I just thought I should let y'all know.

Well, bye and have a good day.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
It's not a bug but a feature. See PEP-632.

**Comment by posi-olomo** [comment]
Thank you!!!!
