### ISSUE TITLE
Possible documentation issue(if its by design) or an issue with method itself in title method of str object 

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#110538]
# Bug report

I encountered this while contributing to an alternate implementation of CPython.

### Bug description:

https://docs.python.org/3.13/library/stdtypes.html#str.title
Please read this 
`Return a title-cased version of the string where words start with an uppercase character and the remaining characters are lowercase.` 
what do you think would be the output of `"{Hel1o}world".title()`?

```py
➜  cpython git:(main) ./python.exe
Python 3.13.0a0 (heads/main:0df772f555, Oct  9 2023, 11:43:29) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> l="{Hel1o}world"
>>> l.title()
'{Hel1O}World'
```

shouldn't we add `isalpha` with `islower` and `isupper` checks in here?https://github.com/python/cpython/blob/0df772f555d44f2e78a252e62b1d83b601ace96b/Objects/bytes_methods.c#L335

`php` has `ucwords` , and it doesn't capitalize w after } and o after 1.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by terryjreedy** [comment]
Please read the entire entry, which continues with "The algorithm uses a simple language-independent definition of a word as groups of consecutive letters. "  How is that not clear.  In any case, we will not change it.

  It go on to say that this may not be what one wants and suggests str.capwords or `re` as alternatives.

**Comment by Agent-Hellboy** [comment]
okay, sure, no problem, what about adding `we are treating non-alpha char from ASCII as separator` in the doc?

**Comment by Agent-Hellboy** [comment]
> Ascii or not is irrelevant for the title method. There is nothing special about ascii versus non-ascii for either letter or non-letter chars.

yes, it's taking `unsigned char`, I will close the issue.
