### ISSUE TITLE
tkinter reference counting bug

### ISSUE THREAD

**Issue by Volker-Weissmann** [python/cpython#110523]
# Bug report

### Bug description:

This code here:
```python
import tkinter as tk
from PIL import Image, ImageTk

class Root(tk.Tk):
    def __init__(self):
        super().__init__()

        self.frame = tk.Frame()
        self.frame.pack(expand=True)

        self.ref_count_hack = []

        for i in range(2):
            img = Image.open(open("/home/volker/Downloads/Python-logo-notext.svg.png", "rb"))
            img_width, img_height = img.size
            scale = min(300 / img_width, 300 / img_height)
            img = img.resize((round(img_width * scale), round(img_height * scale)))
            img = ImageTk.PhotoImage(img)
            if True:
                self.ref_count_hack.append(img)
            label = tk.Label(
                self.frame,
                highlightthickness=1,
                image = img
            )
            r, c = divmod(i, 2)
            label.grid(row=r, column=c)

root = Root()
root.mainloop()
```
works fine. It creates a window that looks like this:
![image](https://github.com/python/cpython/assets/39418860/e648debb-0561-49fa-ae18-cb4eb7d4e414)

But once I replace `if True:` with `if i == 1:`, the windows looks like this:
![image](https://github.com/python/cpython/assets/39418860/0c45b19a-3e70-4635-b8e0-893fbe8eeb22)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Confirmed on 3.11.
Can you provide example with same bug without using `PIL`?

**Comment by haiderk0987** [comment]
Can you provide more details about the bug?
Looking at the code, it seems like replacing ```if True``` with ```if i == 1``` should be inserting image only once at the second iteration of loop, which seems to be fine. What's your expected result?

**Comment by Eclips4** [comment]
> Can you provide more details about the bug? Looking at the code, it seems like replacing `if True` with `if i == 1` should be inserting image only once at the second iteration of loop, which seems to be fine. What's your expected result?

It's just appended object to the list, nothing more. If you remove line with `if True` or `if i == 1`, there will be no image at all. Probably is there somewhere weakref?

**Comment by serhiy-storchaka** [comment]
It is because PIL.ImageTk.PhotoImage destroys the Tk image in its destructor which happens when the last reference to it disappears. It happens when you store a reference to new image in the `img` variable. tkinter.Label do not store reference to the Python wrapper around image, you need to do it yourself.

**Comment by Volker-Weissmann** [comment]
> Confirmed on 3.11. Can you please provide an example with the same bug without using `PIL`?

I don't have an example without `PIL`.

**Comment by serhiy-storchaka** [comment]
Here is a similar example without using PIL:
```py
from tkinter import *
root = Tk()
imgpath = 'Lib/idlelib/Icons/idle_256.png'
img = PhotoImage(master=root, file=imgpath)
lbl = Label(root, image=img)
lbl.pack()
img2 = PhotoImage(master=root, file=imgpath)
# del img
lbl2 = Label(root, image=img2)
lbl2.pack()
root.mainloop()
```
If you uncomment `del img`, the upper image will disappear.

This is not a bug, this is how Tkinter works. I do not think that this can be changed. Keeping an image after destroying the Python object will lead to resource leaks.
