### ISSUE TITLE
Use nested f-string for f-string's format specifier

### ISSUE THREAD

**Issue by yoonghm** [python/cpython#110671]
# Feature or enhancement

### Proposal:

```python
x = 123.456
print(f'{x}')
print(f'{x:.2f}')
```

```Output None
123.456
123.46
```

```Python
ff='.2f'
print(f'{x:f'{ff}'}')
```

```Output None
  File "<stdin>", line 1
    print(f'{x:f'{ff}'}')
                ^
SyntaxError: f-string: expecting '}', or format specs
```

Could the improved f-string in Python 3.12 support embedded or nested f-string for its format specifier?

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
This has worked since 3.6 (although I only tested with 3.7): `print(f'{x:{ff}}')`.
```
>>> x = 123.456
>>> ff='.2f'
>>> print(f'{x:{ff}}')
123.46
```
