### ISSUE TITLE
Version of Python fetched via nuGet should be set

### ISSUE THREAD

**Issue by Yalefeuv** [python/cpython#110612]
https://github.com/python/cpython/blob/edf701c4d83f399bff8612c34fef95da7663945e/PCbuild/find_python.bat#L60

Version of Python fetched via nuGet should be set
Currently, if you try to build Python 3.8 on Windows 7, it will fail because the version fetched is unsupported on Win 7.
Here is a possible fix in this case
@"%_Py_NUGET%" install pythonx86 -ExcludeVersion **-Version 3.8.10** -OutputDirectory "%_Py_EXTERNALS_DIR%"

**Comment by zooba** [comment]
Unfortunately, we're not accepting fixes for 3.8 anymore.

The best option if you're still building 3.8 is to install your own copy of Python and set the `PYTHON` or `HOST_PYTHON` environment variable to point at it before building. There's no need to rely on the automatic download.
