### ISSUE TITLE
The pre-commit hooks do not work on macOS

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#110652]
```console
$ grep "entry.*python" .pre-commit-config.yaml
        entry: 'python Tools/patchcheck/reindent.py --nobackup --newline LF'
        entry: "python Tools/patchcheck/untabify.py"
```

Unfortunately, there is no `python` on macOS; only `python3`. Can we change these to `python3`?

### Linked PRs
* gh-110653

**Comment by erlend-aasland** [comment]
Simply executing these scripts directly would also do:

```console
$ head -n1 Tools/patchcheck/*.py
==> Tools/patchcheck/patchcheck.py <==
#!/usr/bin/env python3

==> Tools/patchcheck/reindent.py <==
#! /usr/bin/env python3

==> Tools/patchcheck/untabify.py <==
#! /usr/bin/env python3
```

**Comment by hugovk** [comment]
Yep, see also comments at https://github.com/python/cpython/pull/109891#issuecomment-1755709823.

We can't use `python3` because that won't work on Windows...

Let's check if direct execution works on Windows.

**Comment by AlexWaygood** [comment]
> We can't use `python3` because that won't work on Windows...
> 
> Let's check if direct execution works on Windows.

Unfortunately neither approach works on Windows: see https://github.com/python/cpython/pull/110653#issuecomment-1756444122 ://

**Comment by AlexWaygood** [comment]
I think we should revert these commits until we figure out how to fix this properly (if it can be "fixed properly"):

- https://github.com/python/cpython/commit/f5edb56328b46f262b74a53343b8098a3934f761
- https://github.com/python/cpython/commit/08ec4a1dbf66383303de9ce5cb55b2b437ef92c0

**Comment by hugovk** [comment]
Agree to revert.

I'd prefer to replace `Tools/patchcheck/reindent.py` and `Tools/patchcheck/untabify.py` with other pre-commit hooks.

**Comment by erlend-aasland** [comment]
> I'd prefer to replace `Tools/patchcheck/reindent.py` and `Tools/patchcheck/untabify.py` with other pre-commit hooks.

Surely there must be existing hooks we can use.

If we need CPython specific hooks, we can create a repo for them under the GitHub `python` org. (for example `python/pre-commit`)
