### ISSUE TITLE
Incorrect syntax error message for incorrect argument unpacking

### ISSUE THREAD

**Issue by thatbirdguythatuknownot** [python/cpython#110696]
# Bug report

### Bug description:

I don't think `SyntaxError: iterable argument unpacking follows keyword argument unpacking` should be present in a case like this (minimal reproducible example):
```python
>>> func(t, *:)
  File "<stdin>", line 1
    func(t, *:)
         ^
SyntaxError: iterable argument unpacking follows keyword argument unpacking
```
So it seems like if `*` is followed by code that triggers a generic `SyntaxError: invalid syntax` error, the former error triggers and overshadows the generic error. This has somewhat made checking the error in the expression following that `*` a bit harder.
I have another question. `func(a=5, *b)` is apparently allowed but from the error `func(**{'a': 7}, *b)` isn't? I don't know what the PEP is for this so I'll try to search it up later.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-110706
* gh-110765
* gh-110766

**Comment by Eclips4** [comment]
cc @pablogsal

**Comment by thatbirdguythatuknownot** [comment]
As for my question, it seems that `func(a=5, *b)` shouldn't be valid? All the other alternative ways to write it are invalid syntax.
```python
# not allowed
func(a=5, 1, 2)
func(**{'a': 5}, 1, 2)
func(**{'a': 5}, *(1, 2))
# allowed
func(a=7, *(1, 2))
```

**Comment by pablogsal** [comment]
> As for my question, it seems that `func(a=5, *b)` shouldn't be valid? All the other alternative ways to write it are invalid syntax.

It was valid before (3.9 and older) so we cannot just make invalid now
