### ISSUE TITLE
Add -Xcpu_count=process cmdline mode to redirect os.cpu_count as os.process_cpu_count

### ISSUE THREAD

**Issue by corona10** [python/cpython#110649]
Since we add the os. process_cpu_count from https://github.com/python/cpython/issues/109649 and -Xcpu_count=<n> command from https://github.com/python/cpython/issues/109595, we can easily redirect os.cpu_count to os. process_cpu_count as we discussed at https://github.com/python/cpython/issues/109595#issuecomment-1741054217

### Linked PRs
* gh-110639

**Comment by vstinner** [comment]
What's the use case of this option? Would you mind to elaborate?

Why not modifying code to replace os.cpu_count() with os.process_cpu_count()?

I have doubts that this function is really needed.

cc @gpshead

**Comment by corona10** [comment]
> Why not modifying code to replace os.cpu_count() with os.process_cpu_count()?

Well, I consider the case that if people want to replace it without modifying source code(3rd party library) from os.cpu_count() and use it os.process_cpu_count() by default mode.

**Comment by vstinner** [comment]
You can use ``export PYTHON_CPU_COUNT=$(python -c "import os; print(os.process_cpu_count())")`` which does the same, no?

**Comment by corona10** [comment]
Same! Then let's close it
