### ISSUE TITLE
Pattern matching is not tested with `@runtime_checkable` protocols

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110686]
# Bug report

There are different simple and corner cases that we need to tests.
Why is that important? Because `runtime_checkable` `Protocol` has its own `__instancecheck__` magic that must work correctly with `match` machinery.

```python
>>> import typing, dataclasses
>>> @typing.runtime_checkable
... class P(typing.Protocol):
...    a: int
... 
>>> @dataclasses.dataclass
... class D:
...    a: int
... 
>>> match D(1):
...    case P() as p:
...        print(p)
... 
D(a=1)
```

```python
>>> @typing.runtime_checkable
... class P(typing.Protocol):
...    a: int
...    b: int
... 
>>> @dataclasses.dataclass
... class D:
...     a: int
...     b: int
... 
>>> match D(1, 2):
...     case P(b=b1):
...         print(b1)
... 
2
```

I have a PR ready.

CC @AlexWaygood for `runtime_checkable` and @brandtbucher for `match`

Requires https://github.com/python/cpython/issues/110682 to test multiple cases with `Protocol` and `__match_args__`.

### Linked PRs
* gh-110687

**Comment by hugovk** [comment]
@sobolevn Ready to close this issue?
