### ISSUE TITLE
(VS 2019) Can't build main on Windows via build.bat: "cannot locate MSBuild.exe"

### ISSUE THREAD

**Issue by tim-one** [python/cpython#110795]
# Bug report

### Bug description:

This started about a week ago.

```none
C:\Code\Python>git checkout main
Already on 'main'
Your branch is up to date with 'upstream/main'.

C:\Code\Python>cd PCbuild

\Code\Python\PCbuild>build
Using "C:\Code\Python\PCbuild\\..\externals\pythonx86\tools\python.exe" (found in externals directory)
Fetching external libraries...
bzip2-1.0.8 already exists, skipping.
sqlite-3.43.1.0 already exists, skipping.
xz-5.2.5 already exists, skipping.
zlib-1.2.13 already exists, skipping.
Fetching external binaries...
libffi-3.4.4 already exists, skipping.
openssl-bin-3.0.11 already exists, skipping.
tcltk-8.6.13.0 already exists, skipping.
Finished.
Cannot locate MSBuild.exe on PATH or as MSBUILD variable
```

Fiddling PATH gets beyond that, but then dies with an even weirder error:

```none
C:\Code\Python\PCbuild>set PATH=%PATH%;C:\Windows\Microsoft.NET\Framework64\v4.0.30319\

C:\Code\Python\PCbuild>build
Using "C:\Code\Python\PCbuild\\..\externals\pythonx86\tools\python.exe" (found in externals directory)
Fetching external libraries...
bzip2-1.0.8 already exists, skipping.
sqlite-3.43.1.0 already exists, skipping.
xz-5.2.5 already exists, skipping.
zlib-1.2.13 already exists, skipping.
Fetching external binaries...
libffi-3.4.4 already exists, skipping.
openssl-bin-3.0.11 already exists, skipping.
tcltk-8.6.13.0 already exists, skipping.
Finished.
Using "C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"  (found in the PATH)
Using "C:\Code\Python\PCbuild\\..\externals\pythonx86\tools\python.exe" (found in externals directory)

C:\Code\Python\PCbuild>"C:\Windows\Microsoft.NET\Framework64\v4.0.30319\MSBuild.exe"  "C:\Code\Python\PCbuild\pcbuild.proj" /t:Build /m /nologo /v:m /clp:summary /p:Configuration=Release /p:Platform=x64 /p:IncludeExternals=true /p:IncludeCTypes=true /p:IncludeSSL=true /p:IncludeTkinter=true /p:DisableGil= /p:UseTestMarker= /p:GIT="C:\Users\Tim\AppData\Local\Programs\Git\cmd\git.exe"
C:\Code\Python\PCbuild\pcbuild.proj(3,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

C:\Code\Python\PCbuild\pcbuild.proj(3,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props
" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
```

This seems specific to the command line. Building from within the GUI (Visual Studio 2019 16.11.31) still appears to work.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
I have not built python since September, so I just tried `> PCBuild\build.bat -d` and it worked as normal.  It follows `Finished` after tcl/tk with the msbuild call: `"F:\VS2022\Community\MSBuild\Current\Bin\msbuild.exe" ... <about 10 arguments on 4 lines>`   I have not touched PATH myself and the msbuild.exe directory is not in it.   Must get it from the registery.

I would check that the directory you gave is readable, contains msbuild.exe, and the latter will execute and give some message called without args.

**Comment by tim-one** [comment]
Ya, nothing obviously wrong with any of that:

```none
C:\Code\Python\PCbuild>cd \Windows\Microsoft.NET\Framework64\v4.0.30319\

C:\Windows\Microsoft.NET\Framework64\v4.0.30319>dir MSBuild.exe
 Volume in drive C is OS
 Volume Serial Number is 54BD-629A

 Directory of C:\Windows\Microsoft.NET\Framework64\v4.0.30319

06/24/2022  09:16 PM           252,312 MSBuild.exe
               1 File(s)        252,312 bytes
               0 Dir(s)  3,797,825,142,784 bytes free

C:\Windows\Microsoft.NET\Framework64\v4.0.30319>msbuild
Microsoft (R) Build Engine version 4.8.9037.0
[Microsoft .NET Framework, version 4.0.30319.42000]
Copyright (C) Microsoft Corporation. All rights reserved.

MSBUILD : error MSB1003: Specify a project or solution file. The current working directory does not contain a project or solution file.

C:\Windows\Microsoft.NET\Framework64\v4.0.30319>
```

Since the last time this worked (about a week ago), there have been updates to (at least) CPython's main branch, Visual Studio, git for Windows, and Windows 10 Pro. They're all as "up to date" as is possible to get.

**Comment by terryjreedy** [comment]
I have only updated Python main and Windows 10.

**Comment by tim-one** [comment]
Possibly related, although I can't follow what happened here, or how it was resolved:

https://github.com/python/cpython/issues/77856

**Comment by terryjreedy** [comment]
@python/windows-team Anyone have any idea why Tim cannot compile?

**Comment by tim-one** [comment]
Thanks, Terry. I'll add that I since used the GUI to clean out everything, and wholly deleted the `amdt4` and `obj` subdirectories of `PCbuild`, just in case some old stale file was confusing things. But, it made no difference to any behavior reported here ☹️

**Comment by jkloth** [comment]
Notice that the path for msbuild.exe is coming from the .NET Framework, not Visual Studio.  It would seem that a recent update to the .NET Framework adds itself to the PATH thus causing its msbuild.exe to be found by `find_python.bat` prior to searching the Visual Studio installations.

**Comment by tim-one** [comment]
No, `msbuild.exe` isn't on the PATH at all - that's why the original error message here is "Cannot locate MSBuild.exe on PATH or as MSBUILD variable".

```
C:\Code\Python\PCbuild>where msbuild
INFO: Could not find files for the given pattern(s).
```
 _I_ later manually added .NET to the PATH because some random web page said that's the way to fix this kind of error. Then the CPython build process makes a tiny bit of additional progress before dying in a different way (but I already spelled that all out in the first msg here).

I find nothing named `ms*.*` anywhere in the Visual Studio directories.

**Comment by tim-one** [comment]
Staring at `PCbuild\find_msbuild.bat`, perhaps this is relevant:

```
@rem VS 2017 and later provide vswhere.exe, which can be used
@if not exist "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe" goto :skip_vswhere
```

The comment seems to imply it _expects_ `vswhere.exe` to exist in a current Visual Studio installation - but there is no such file  in my (recently updated_ installation ((Visual Studio 2019 16.11.31).

**Comment by jkloth** [comment]
(Apologies for missing the error in the first block.)  So as to `vswhere.exe`, quoting from [vswhere wiki](https://github.com/Microsoft/vswhere/wiki/Installing):

> Starting with Visual Studio 15.2 (26418.1 Preview) vswhere.exe is installed in _%ProgramFiles(x86)%\Microsoft Visual Studio\Installer_ (use _%ProgramFiles%_ in a 32-bit program prior to Windows 10). This is a fixed location that will be maintained.

So, if it is missing, I would suggest repairing the Visual Studio installation.

**Comment by tim-one** [comment]
I have no reason to believe my VS installation is damaged - or, if it is, how it _could_ be repaired.

Trying to install `vswhere.exe` from various methods on the wiki you linked to is just leading to another bottomless pit of mysteries; e.g.,

```none
C:\Code\Python\PCbuild>winget install Microsoft.VisualStudio.Locator
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing

No packages were found among the working sources.
```

And I'm not inclined to spend more time on that: even if `vswhere` worked, `msbuild.exe` is not on the PATH anyway, nor does it exist in any of the VS directories.

But this "should" all be shallow to _someone_ here :wink:.

**Comment by terryjreedy** [comment]
I have VS22 from June 22, with the options specified in the devguide.  I don't know if VS19 upgraded is the same or not.

**Comment by tim-one** [comment]
Terry, that's a clue I can use :smile:! I didn't even know 2022 existed - I'm using 2019 because that's the most recent one I ever heard of. I'm installing 2022 now and will report on how it works out tomorrow (it's getting late here, and the installation is taking a very long time).

**Comment by tim-one** [comment]
Installing VS 2022 (17.7.5) cleared up all the symptoms reported here, so I'm closing this. I assume - but don't know - that the most up-to-date version of VS 2019 (16.11.3) will fail the same way for others.

**Comment by jkloth** [comment]
Although resolved, I'll just note that my update-to-date (16.11.31) VS2019 works as intended, so this is hopefully an isolated problem.

**Comment by tim-one** [comment]
Ya, it will remain a mystery, There were no other oddities on the machine, Event Viewer didn't show any problems, and chkdsk, dism, and sfc found no complaints either. Strange! vswhere and msbuild were both conspicuous by absence in my VS2019 folders, but easy to find for in VS2022's.

**Comment by zooba** [comment]
vswhere.exe has been part of the Visual Studio installer since VS 2017. It certainly hasn't moved anywhere.

I'm not sure why it disappeared from your VS Installer directory (note that it's not part of VS proper, but the installer), but that's the problem.

Most likely updating the installer restored the file. I don't think there's a way to repair just the installer though, and it's possible that the VS 2019 installer refused to take an automatic update.

**Comment by tim-one** [comment]
Could be - but msbuild.exe was also missing (which appears to be part of VS proper, not of the installer). In any case, it's still working today under VS 2022 😄 .

**Comment by zooba** [comment]
Technically, you can have a valid install of VS these days that doesn't include MSBuild. I think as soon as you add any language support at all, you'll get it, but it's not strictly required.

Still, if you had the VC tools installed, it should've been there. A corrupt install for some reason seems likely.

**Comment by tim-one** [comment]
Back when msbuild.exe was missing too, under VS 2019, as noted before it was still possible to build Python using the GUI. It's only the `pcbuild.bat` way that was dead in the water.

**Comment by BerendKemper** [comment]
```
PS C:\Users\Berend\Documents\cpython> PCbuild\build.bat -c Debug
Using "C:\Users\Berend\Documents\cpython\PCbuild\\..\externals\pythonx86\tools\python.exe" (found in externals directory)
Fetching external libraries...
bzip2-1.0.8 already exists, skipping.    
sqlite-3.45.1.0 already exists, skipping.
xz-5.2.5 already exists, skipping.       
zlib-1.3.1 already exists, skipping.
Fetching external binaries...
libffi-3.4.4 already exists, skipping.
openssl-bin-3.0.13 already exists, skipping.
tcltk-8.6.13.1 already exists, skipping.
Finished.
Cannot locate MSBuild.exe on PATH or as MSBUILD variable
```
Can cpython also be installed without visual studio? (i'm using visual studio code)
