### ISSUE TITLE
Intermittent failure in ` test_sys.SysModuleTest.test_current_exceptions`

### ISSUE THREAD

**Issue by FFY00** [python/cpython#110796]
# Bug report

### Bug description:

Example: https://github.com/python/cpython/actions/runs/6502915514/job/17662666558?pr=110794

The code in question:

https://github.com/python/cpython/blob/b883cad06b12443014d57dcebd42d55f559b18f4/Lib/test/test_sys.py#L507-L572

Originally added in 64366fa9b3ba71b8a503a8719eff433f4ea49eb9

I believe the failure is due to `sys._current_exceptions` being run before the exception is raised.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-110797

**Comment by hugovk** [comment]
Thanks for the fix!
