### ISSUE TITLE
'+'.zfill(2) and '-'.zfill(2) return '+0' and '-0'

### ISSUE THREAD

**Issue by Bokotyk** [python/cpython#110716]
# Bug report

### Bug description:

```python
'-'.zfill(2)
'-0'
'+'.zfill(2)
'+0'
'%'.zfill(2)
'0%'
'-'.zfill(7)
'-000000'
```

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by bcail** [comment]
Looks like this is [documented behavior](https://docs.python.org/3/library/stdtypes.html#str.zfill).

**Comment by terryjreedy** [comment]
@Bokotyk Please ask about bugs on a help forum, such as https://discuss.python.org/c/users/7.  When you do, please check the appropriate doc entry first and test on a more recent Python version, as we fix a few hundred in each.

@bcail Thanks for the report.
