### ISSUE TITLE
name error in zipfile.ZipInfo._decodeExtra()

### ISSUE THREAD

**Issue by jwilk** [python/cpython#110715]
https://github.com/python/cpython/blob/f27b83090701b9c215e0d65f1f924fb9330cb649/Lib/zipfile/__init__.py#L548 uses the `warnings` module, but AFAICS it's never imported.

### Linked PRs
* gh-110822
* gh-110861

**Comment by Eclips4** [comment]
> > Would you like to send a PR?
> 
> No, sorry. CLA is a deal breaker for me.

Ok, then I send pull request tomorrow (or someone take it, feel free to do it).
Thanks for report!
