### ISSUE TITLE
[Regression] TypeVar crashes when name is specified via keyword parameters

### ISSUE THREAD

**Issue by mxschmitt** [python/cpython#110782]
# Crash report

### What happened?

```python
from typing import TypeVar
TypeVar(name="Handler")
```

Good: 3.11.X
Bad: 3.12.0

Downstream issue: https://github.com/jfhbrook/pyee/issues/134

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS

### Output from running 'python -VV' on the command line:

Python 3.12.0 (main, Oct 12 2023, 00:42:11) [GCC 12.2.0]

### Linked PRs
* gh-110784
* gh-110787

**Comment by mxschmitt** [comment]
Investigation: Changing `TypeVar(name="Handler")` to `TypeVar("Handler")` fixes it for me.

**Comment by JelleZijlstra** [comment]
This is possibly a bug in Argument Clinic (see https://github.com/python/cpython/blob/e7331365b488382d906ce6733ab1349ded49c928/Objects/typevarobject.c#L326): if `name` is passed as a positional argument and there are no constraints, `constraints` is an empty tuple, but if it's a keyword argument, `constraints` is NULL.

I'll send a PR in a moment with a workaround in typevarobject.c.

**Comment by JelleZijlstra** [comment]
Fix is merged, and will be in 3.12 soon; 3.12.1 should include the fix.

I'll note that using a keyword argument for the name of a TypeVar is not an officially supported part of the type system, so to make your code portable across type checkers and Python versions, you should use a positional argument for the name. It appears that pyright supports the keyword argument form, but mypy does not. We'll continue to support the keyword argument form at runtime for backwards compatibility.

**Comment by sobolevn** [comment]
Thanks! 

@JelleZijlstra would you accept 

https://github.com/python/cpython/blob/e7331365b488382d906ce6733ab1349ded49c928/Objects/typevarobject.c#L329-L330

change to just

```
*constraints
```
?

Because this seems like a fortunate event that this notation works. I was not able to find that this is a documented approach.

If so, I would send a PR :)

**Comment by AlexWaygood** [comment]
> Because this seems like a fortunate event that this notation works. I was not able to find that this is a documented approach.

We should try to make sure AC raises an error if it encounters syntax like this which isn't supported! Cc. @erlend-aasland

**Comment by sobolevn** [comment]
Ok, will do after https://github.com/python/cpython/issues/110864

**Comment by JelleZijlstra** [comment]
Thanks @sobolevn for investigating further!

I'm fine with whatever syntax works here, but ideally AC should support annotations on `*args` (e.g., I should be able to write `*args: bool` to get any number of bool args), and as Alex says it should error on unsupported constructs.
