### ISSUE TITLE
Improve markup in `Doc/library/tkinter.ttk.rst`

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#110746]
# Documentation
In the `tkinter` docs there are a few methods that include sequences of valid options/values, e.g. https://docs.python.org/3/library/tkinter.ttk.html#tkinter.ttk.Treeview.column

These should use appropriate markup (like ` ``...`` ` or `*...*`).

### Linked PRs
* gh-111236
* gh-113193
* gh-113194

**Comment by isacben** [comment]
Hello,

I would like to contribute with this issue. 
Please let me know.

Thank you!

**Comment by varundeepsaini** [comment]
Heyy
Is this Issue Still Open ??
If Yes Then Can you please assign it to me

**Comment by hugovk** [comment]
The issue is still open but there's already a PR: https://github.com/python/cpython/pull/111236

**Comment by akshatgokul** [comment]
Thank you @hugovk, @ezio-melotti, and @serhiy-storchaka for the merge. I think the issue can be marked as closed now.

**Comment by ezio-melotti** [comment]
Thanks to you for the PR!
