### ISSUE TITLE
test_signal fails with interpreter crash

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#110772]
# Bug report

### Bug description:

`./python.exe -m test -v test_signal`

Traceback:
```python
...many lines
test_stress_modifying_handlers (test.test_signal.StressTest.test_stress_modifying_handlers) ... Fatal Python error: Bus error

Current thread 0x000000016e333000 (most recent call first):
  File "/Users/admin/Projects/cpython/Lib/test/test_signal.py", line 1338 in set_interrupts
  File "/Users/admin/Projects/cpython/Lib/threading.py", line 1004 in run
  File "/Users/admin/Projects/cpython/Lib/threading.py", line 1067 in _bootstrap_inner
  File "/Users/admin/Projects/cpython/Lib/threading.py", line 1024 in _bootstrap

Thread 0x00000001e7601300 (most recent call first):
  File "/Users/admin/Projects/cpython/Lib/enum.py", line 1155 in __new__
  File "/Users/admin/Projects/cpython/Lib/enum.py", line 729 in __call__
Assertion failed: (PyCode_Check(f->f_executable)), function _PyFrame_GetCode, file pycore_frame.h, line 83.
Fatal Python error: Aborted

```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Bisected to  1e3460d9faaffb35b3c6175c666b1f45aea2c1d8

cc @gaogaotiantian @markshannon

**Comment by gaogaotiantian** [comment]
Can you reliably reproduce this on Mac? I can't repro it on Linux(WSL).

**Comment by gaogaotiantian** [comment]
From the buildbot, this seems to be a Mac specific issue. I don't have a Mac by hand.

**Comment by Eclips4** [comment]
Interesting. I no longer can reproduce it :(

**Comment by gaogaotiantian** [comment]
I don't think `test_stress_modifying_handlers` could trigger the issue as the newly added code should not matter. It's possible that there's some dependency on other tests somehow clearing the interpreter states. I don't have any theories yet for what could happen (or if this is a real issue caused by this specific commit).

**Comment by gaogaotiantian** [comment]
Okay let me see if I could repro on Linux.

**Comment by gaogaotiantian** [comment]
I am able to repro this on my Mac on the commit before https://github.com/python/cpython/commit/1e3460d9faaffb35b3c6175c666b1f45aea2c1d8. So this is not introduced by the commit mentioned. (which makes sense because the only line of code committed is not executed during the test).

**Comment by chgnrdv** [comment]
See also #110017 110083

**Comment by chgnrdv** [comment]
See also #110017 #110083

**Comment by Eclips4** [comment]
> I am able to repro this on my Mac on the commit before [1e3460d](https://github.com/python/cpython/commit/1e3460d9faaffb35b3c6175c666b1f45aea2c1d8). So this is not introduced by the commit mentioned. (which makes sense because the only line of code committed is not executed during the test).

Yes, after some investigation I came to the same conclusions. Sorry for the false *accusation*.



> See also #110017 #110083

Thanks! That's looks like duplicate of #110017.
