### ISSUE TITLE
The exclamation symbol is not a soft keyword or no token is needed for it

### ISSUE THREAD

**Issue by RobEin** [python/cpython#110798]
# Bug report

### Bug description:

If the ```"!"``` [expression](https://github.com/python/cpython/blob/27d5ea291c16bcdfaad25e2e371c2ba3d591ed37/Grammar/python.gram#L919) is a soft keyword, then I think the [EXCLAMATION token](https://github.com/python/cpython/blob/27d5ea291c16bcdfaad25e2e371c2ba3d591ed37/Grammar/Tokens#L56) is unnecessary.
Or if it's necessary, then the ```'!'``` expression would be an appropriate reference to the EXCLAMATION token.

### CPython versions tested on:

3.12

**Comment by terryjreedy** [comment]
'!' is neither a keyword, nor soft keyword, nor expression.  It is "incomplete input" as its only use in Python syntax is in the `!=` comparison operator.  Other uses are given at the top of https://docs.python.org/3/genindex-Symbols.html.  I see no indication of any bug and hence currently believe that this should be closed.

**Comment by RobEin** [comment]
It's really not a bug right now.
But in later versions, a problem may arise from the combined use of the soft keyword (soft symbol) EXCLAMATION token and the dedicated EXCLAMATION token.

The '!=' operator has a separate token, it does not use the EXCLAMATION token.
What's the point of a token anyway?

**Comment by RobEin** [comment]
In my opinion, once [fstring mini language](https://docs.python.org/3.12/library/string.html#formatspec) has become an integral part of the Python grammar, the exclamation mark deserves a dedicated token '!', as it exists but is not used.
The exclamation mark as a soft keyword "!" I don't think it makes sense.
The exclamation mark is not included in the [soft keyword list](https://docs.python.org/3.12/reference/lexical_analysis.html#soft-keywords) either.
I think it could be a typo and rather they wanted to write an '!' grammar [expression](https://peps.python.org/pep-0617/#syntax).

**Comment by terryjreedy** [comment]
The parser parses the string of tokens produced by the tokenizer.  The theory behind this split is explained in multiple places.  When the language changes, the tokenizer, parser, compiler, and for CPython, the target bytecode may all change, but in such a way that the combined effect is to execute Python code as specified.  AFAIK, there are no bugs related to tokenization involving '!', and hence no need to do anything.
