### ISSUE TITLE
Backport test_capi enhancements from Python 3.12 to Python 3.11

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110835]
I propose to copy Modules/_testcapi/ and Lib/test/test_capi/ from Python 3.12 to Python 3.11 to increase the test coverage in Python 3.11 and allow backporting test changes, since test changes should be backported to stable versions: Python 3.11 and 3.12.

**Comment by vstinner** [comment]
Example of test which would be nice to backport to Python 3.11: https://github.com/python/cpython/pull/110547#issuecomment-1757671391

**Comment by serhiy-storchaka** [comment]
```
$ git log --oneline Modules/_testcapi/ Lib/test/test_capi/ | wc -l
183
```

**Comment by vstinner** [comment]
While it would be nice, I failed to find time to do that. So let's leave the code as it is. I just close the issue.
