### ISSUE TITLE
List Comprehension with if else condition

### ISSUE THREAD

**Issue by pallavchat** [python/cpython#110831]
# Feature or enhancement

### Proposal:

When using list comprehension and using only if condition it goes after for statement whereas when if and else both is used it goes before for statement. This defeats the purpose of Python to make it easy to understand and implement.
It will be better if both can either be before or after the for statement 
# Add a code block here, if required

```python
old_list = [8, 13, -7, 4, -9, 2, 10]
new_list = [num if num >= 0 else 0 for num in old_list]
print(new_list) 
new_list_1 = [num*num for num in old_list if num >= 0]
print(new_list_1)
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by sobolevn** [comment]
Hi! Welcome to the bugtracker :)

I don't quite understand what exactly you are proposing :) 
If you want to use ternary expressions in comprehensions - it is totally possible.
Example:

```python
>>> [x if x % 2 == 0 else -x for x in range(10)]
[0, -1, 2, -3, 4, -5, 6, -7, 8, -9]
```

If you want to use `else` part in `for ... if`, then I don't think that it is possible, because this `if` is like filter. It replicates this behaviour:

```python
>>> [x for x in range(10) if x % 2 == 0]
[0, 2, 4, 6, 8]
```

```python
>>> result = []
... for x in range(10):
...     if x % 2 == 0:
...         results.append(x)
...
>>> result
[0, 2, 4, 6, 8]
```

**Comment by AlexWaygood** [comment]
I agree with @sobolevn; it's not clear what exactly you're proposing here. But if you're proposing new syntax here, then that's definitely a major change that would require discussion elsewhere before opening an issue on GitHub :)

Please open an issue at https://discuss.python.org/c/users/7 with your suggestions :)
