### ISSUE TITLE
PyArg_ParseTupleAndKeywords() and non-ASCII keyword names

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#110815]
Most of C strings in the C API are implied to be UTF-8 encoded. PyArg_ParseTupleAndKeywords() mostly works with non-ASCII keyword names as they are UTF-8 encoded. Except one case, when you pass argument by keyword with invalid non-ASCII name  to a function that has optional parameter with non-ASCII UTF-8 encoded name. In this case you get a crash in the debug build.

It was caused by combination of f4934ea77da38516731a75fbf9458b248d26dd81 and a83a6a3275f7dc748db3a237bbf4b05fcf76a85f (bpo-28701, #72887). Before these changes you simply got inaccurate or even wrong error message.

Examples:

1.
   Parameters: "ä"
   Keyword arguments: "ë"
   Old behavior: TypeError "'ë' is an invalid keyword argument for this function"
   Current behavior: crash
   Expected behavior: TypeError "'ë' is an invalid keyword argument for this function"

2.
   Parameters: "ä"
   Keyword arguments: "Ã¤"
   Old behavior: TypeError "invalid keyword argument for this function"
   Current behavior: crash
   Expected behavior: TypeError "'Ã¤' is an invalid keyword argument for this function"

3.
   Parameters: "ä", "ë"
   Keyword arguments: "Ã¤", "ë"
   Old behavior: TypeError "'ë' is an invalid keyword argument for this function"
   Current behavior: crash
   Expected behavior: TypeError "'Ã¤' is an invalid keyword argument for this function"

In case 1 the pre-bpo-28701 behavior was correct, in case 2 it was correct but not precise (it failed to find the name of invalid keyword argument), in case 3 it was wrong (it found wrong name). In all cases there is a crash currently.

### Linked PRs
* gh-110816
* gh-110817
* gh-110825

**Comment by serhiy-storchaka** [comment]
I am not sure how to classify this issue: as a bug or a new feature. On one hand, it was a regression in 3.7, crash is worse than wrong error message. On other hand, it was not explicitly documented that non-ASCII names are supported, there were no tests, and if it worked, it was only by accident. And it was a long time ago. So, official support of non-ASCII names can be a new feature.

**Comment by terryjreedy** [comment]
Is the issue visible from Python code:
```
def f(ä=''): pass

f(ä="ë")
f(ä="Ã¤")
```
works.  If something like this were to crash, I would say definitely a bugfix to be backported.

**Comment by serhiy-storchaka** [comment]
It is an issue with `PyArg_ParseTupleAndKeywords()`, a C API used for parsing keyword arguments in extension functions. Python defined functions do not use it. Also, it is an issue with argument names, not values. Non-ASCII argument names are forbidden in the core interpreter and the stdlib, but third parties may have reasons to use them.

**Comment by terryjreedy** [comment]
Thanks.  Makes sense now.
