### ISSUE TITLE
Legacy tracing & PY_UNWIND: arg of legacy tracer call should be NULL

### ISSUE THREAD

**Issue by jpe** [python/cpython#110892]
# Bug report

### Bug description:

When using a legacy tracer with `PyEval_SetTrace` and a function exits with an exception, the arg of the tracer event `PyTrace_RETURN` should be NULL [docs](https://docs.python.org/3/c-api/init.html#c.PyTrace_RETURN). Currently in 3.12 (& 3.13), the arg is set to the exception value because the PY_UNWIND handler is forwarding its arg to the legacy tracer function.

### CPython versions tested on:

3.12

### Linked PRs
* gh-110909

**Comment by gaogaotiantian** [comment]
I'm confused. Why do you think the exception is passed to the legacy tracer? Could you share an example code?

In `_PyEval_SetTrace`, the callback of `PY_MONITORING_EVENT_PY_UNWIND` is `sys_trace_func3` which unconditionally passes `Py_None` as the arg to the trace function. That is the case for both 3.12 and 3.13.

**Comment by jpe** [comment]
The arg needs to be NULL and not Py_None when there's an exception. For the legacy tracer 'r' event, the arg is the value returned so arg=Py_None indicates None is returned without an exception.

I found this while debugging Wing's debugger which uses a C implemented trace function and I saw the arg was not NULL and didn't look at what the value was or look closely up the stack; sorry. It may be that the trampoline that called a Python implemented trace function passed Py_None when arg was NULL, but it's been years since I worked with a Python implemented trace function.

**Comment by gaogaotiantian** [comment]
Okay I think I understood what you were talking about.

**Comment by gaogaotiantian** [comment]
PR is made to fix this.

**Comment by jpe** [comment]
I've verified that the trace function gets a NULL on an UNWIND event with the PR. Thanks!

Shouldn't the profile function also get a NULL on an UNWIND event?

**Comment by gaogaotiantian** [comment]
> I've verified that the trace function gets a NULL on an UNWIND event with the PR. Thanks!
> 
> Shouldn't the profile function also get a NULL on an UNWIND event?

Yes, `sys_profile_unwind` is changed to return NULL in the same PR.

**Comment by jpe** [comment]
I see the profile change now; LGTM.
