### ISSUE TITLE
problem with print("f{}")

### ISSUE THREAD

**Issue by HernandezAvilesRaul** [python/cpython#110802]
# Bug report

### Bug description:

in pycharm if you tried to interact with the {} like adding a [] or "" it will automaticly create an error that unable any functionality inside the IDE you can´t type or erase anything
```python
stock = {
    "sandia": {"precio": 10, "cantidad": 10},
    "coco": {"precio": 15, "cantidad": 10},
    "fresa": {"precio": 35, "cantidad": 10},
    "manzana": {"precio": 45, "cantidad": 10},
    "naranja": {"precio": 30, "cantidad": 10},
    "guayaba": {"precio": 20, "cantidad": 10},
    }

for fruto, valores in stock.items():
    print(f"{fruto}, {valores}")
```
### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
This repository is intended as CPython bug tracker, and your question doesn't look as related to CPython.
Please, ask for help on the [discuss](https://discuss.python.org/c/users/7).
