### ISSUE TITLE
pathlib's PosixPath does not have an attribute "walk"

### ISSUE THREAD

**Issue by ioah86** [python/cpython#110838]
# Bug report

### Bug description:

```python
from pathlib import Path

pth = Path(".")
for (root_dir, dir_names, file_names) in pth.walk():
    print(root_dir)
    print(dir_names)
    print(file_names)
```

According to the [documentation](https://docs.python.org/3/library/pathlib.html#pathlib.Path.iterdir), `PosixPath` inherits from `Path`, and hence should have the `walk` feature. But I am getting the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[3], line 1
----> 1 for (root_dir, dir_names, file_names) in pth.walk():
      2     print(root_dir)
      3     print(dir_names)

AttributeError: 'PosixPath' object has no attribute 'walk'
```

I do not think that this is intended.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
The documentation states that the `walk()` method was added in Python 3.12. You are using Python 3.11.

**Comment by ioah86** [comment]
Dangit... Moment of rtfm... Thank you for your triaging.
