### ISSUE TITLE
ord() is not always right

### ISSUE THREAD

**Issue by BDKey** [python/cpython#110999]
# Bug report

### Bug description:

```python
from random import randint as rnd

def encrypt(text):
    splitted = []
    for i in text:
        splitted.append(str(1000+ord(i))[1::])
    print(splitted)
    keys = []
    trash = []
    for i in range(0,len(text)+rnd(0,1)):
        keys.append(rnd(1,9))
        trash.append(rnd(10**(keys[i]-1),10**keys[i]))
    key = ""
    for i in keys:
        key += str(i)
    res = ""
    for i in range(len(splitted)):
        res+=str(trash[i])+str(splitted[i])
    if len(splitted) < len(trash):
        res+=str(trash[len(trash)-1])
    return key, res

def decrypt(allInOne):
    key = allInOne[0]
    text = allInOne[1]
    keys = []
    for i in key:
        keys.append(int(i))
    if (sum(keys)+len(keys)*3)!=len(text):
        text = text[:-(keys[len(keys)-1])]
        keys.pop(len(keys)-1)
    pen = 0
    keypen = 0
    parts = []
    while keypen < len(keys):
        pen+=keys[keypen]
        keypen+=1
        sym = ""
        for i in range(0,3):
            sym+=text[pen+i]
        parts.append(chr(int(sym)))
        pen+=3
    res = ""
    print(parts)
    for i in parts:
        res+=i
    return res

intake = input("?>")
AllOK = True
for i in range(0,1000):
    print("TEST")
    enc = encrypt(intake)
    dec = decrypt(enc)
    if dec != intake:
        AllOK = False
        print(intake, dec)
        break

if AllOK: print("Test OK")
else: print("Test error")
```
Sorry, i'm a Russian, and my English isn't very good
So, i am programming an encryptor and a decryptor for my project. And sometimes, function ord() is returning not correct symbol (i've already checked in ascii table). To test that, i've wrote a unit test and figured out that i was right. I am using Windows 10 x64, so i think that's not hardware problem. To test it yourself you need to:
1) Lauch code
2)Enter random text to test it (only English letters)
3)Look at output, it contains:
TEST <-- begining of test
[some numbers] <-- every letter of your text converted to ascii
[some letters] <-- encrypted letters
4) If text that you've entered is not the same with encrypted text
text text <-- comparation of text that you've entered and encrypted
Test error <-- just a message

That's (i think) is everything that you should know.
I already tested this with a bunch of online python interpriters and they have the same issue.
I know that this is problem with ord()

I HAVE A MISTAKE
I MEAN NOT A ord(), BUT A chr() error

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
If there is a problem with ``ord()`` you should be able to show the issue with a much smaller script.

**Comment by BDKey** [comment]
okay, i'll do it

**Comment by BDKey** [comment]
so, this is working fine
`
#ord() test
word = input("?>")[0]
for i in range(0,10000):
    code = ord(word)
    dec = chr(code)
    if dec != word:
        print("ERR")
`

**Comment by BDKey** [comment]
missclick

**Comment by BDKey** [comment]
my bad, i should fix that problem

**Comment by terryjreedy** [comment]
@BDKey Please ask first about possible bugs on the Python discourse help channel: https://discuss.python.org/c/users/7.
