### ISSUE TITLE
Regression in `MemoryError` displaying (`_PyErr_Display` fallback to C impl of `print_exception`)

### ISSUE THREAD

**Issue by chgnrdv** [python/cpython#110912]
# Bug report

### Bug description:

After e7331365b488382d906ce6733ab1349ded49c928:
```python
>>> raise MemoryError()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
object address  : 0x7fd3b6037540
object refcount : 3
object type     : 0x556d6e04cf40
object type name: MemoryError
object repr     : MemoryError()
lost sys.stderr
```

cc @pablogsal 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-110921

**Comment by serhiy-storchaka** [comment]
Seen this with real MemoryError, but I thought it was because the error handler couldn't run when out of memory. But if it produces this for an artificial MemoryError, something is very wrong.

**Comment by pablogsal** [comment]
> Seen this with real MemoryError, but I thought it was because the error handler couldn't run when out of memory. But if it produces this for an artificial MemoryError, something is very wrong.

This was caused by an (incorrect) forceful fallback to the C implementation of the traceback machinery after we switched to use the Python `traceback` module as the main mechanism.
