### ISSUE TITLE
Should reference to old books be retained?

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#110930]
# Documentation

A [question on the help channel](https://discuss.python.org/t/offical-documentation/36356) asked about a reference to a "twenty year old book," but didn't specify it. I assume the poster was referring to Mark Lutz's book. I realize that book has a place in Python history as perhaps the first widely read book on Python, but should it still be afforded more-or-less first class status as Python reference material? I don't know when it was last updated, so maybe it's up-to-date and the link just needs to be corrected, but if not, perhaps we should continue ourselves to more recent, online, sources which better match the current language.

### Linked PRs
* gh-112490
* gh-112523
* gh-112524

**Comment by dKosarevsky** [comment]
Water, but legend

**Comment by smontanaro** [comment]
> Water, but legend

?

**Comment by hugovk** [comment]
The poster confirmed they meant the 23-year-old "Python and Tkinter Programming" and provided a [Amazon link](https://www.amazon.com/Python-Tkinter-Programming-John-Grayson/dp/1884777813/) to the 2000 book by John Grayson.

However, the book by that title mentioned at https://docs.python.org/3/library/tkinter.html is:

> [Python and Tkinter Programming](https://www.packtpub.com/product/python-gui-programming-with-tkinter/9781788835886)
By Alan Moore. (ISBN 978-1788835886) 

Published May 2018.

So this is a misunderstanding.

---

Whilst we're here, let's consider the Lutz book. Its [website](https://learning-python.com/README-PP4E-PY33-PY35.html) says:

> release 1.4 of the book's examples package works with Pythons 3.0 through 3.10, and likely later [...] .Also note that most book examples will run unchanged under 3.3 through 3.10;

And provides a list of some changes that may be needed. So sounds like this book can still has value.

---

I don't think there's anything to do here, but thanks for raising!

**Comment by hugovk** [comment]
Or rather, there is a problem here:

> However, the book by that title mentioned at [docs.python.org/3/library/tkinter.html](https://docs.python.org/3/library/tkinter.html) is:
> 
> > [Python and Tkinter Programming](https://www.packtpub.com/product/python-gui-programming-with-tkinter/9781788835886)
> > By Alan Moore. (ISBN 978-1788835886)

This links to _Python GUI programming with Tkinter_ by Alan D. Moore.

So the link and author is good, but the title is wrong. The books section was updated in 2021 in  https://github.com/python/cpython/pull/27838 and looks like there was a mixup. So let's re-open this to fix it, and review the others.

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/112490 to fix it. The other titles and ISBNs are correct.
