### ISSUE TITLE
Unable to pip install mysqlclient in 3.12

### ISSUE THREAD

**Issue by AdarshSavalagi** [python/cpython#110996]
![IMG-20231007-WA0025](https://github.com/python/cpython/assets/120472249/cd98acbd-2982-46d9-ada6-aa4f9a27ba89)
# Crash report

### What happened?

```python
pip install mysqlclient 
```
As I try to install mysqlclient in latest version 3.12 it is showing me some error but as I rolled back to 3.11 it works perfectly fine 

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
This is almost certainly a result of `mysqlclient`, or a dependency of `mysqlclient`, not yet being compatible with Python 3.12. It's impossible to say for sure, however, without you showing us the error message that pip gave you.

**Comment by AdarshSavalagi** [comment]
> This is almost certainly a result of `mysqlclient`, or a dependency of `mysqlclient`, not yet being compatible with Python 3.12. It's impossible to say for sure, however, without you showing us the error message that pip gave you.

![Uploading IMG-20231007-WA0025.jpg…]()

**Comment by zware** [comment]
@AdarshSavalagi: It looks like you submitted your comment before the image finished uploading (which seems like a GitHub bug, but also beside the point :)).

Images are *not* the best way to share code or error messages, though.  Instead, copy it and paste it in a [code block](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#quoting-code).

That said: as already mentioned, this is not a cpython bug.  You'll have better luck reporting to the mysqlclient project.

**Comment by deepanshuchaudhary007** [comment]
Hii @AdarshSavalagi please try this "python -m pip install django-mysql" first in you are working on Django
then add "django_mysql" this into your INSTALLED_APPS in setting.py. I hope its working for you.
