### ISSUE TITLE
Make pdb completion work with alias, convenience variables etc.

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#110944]
# Feature or enhancement

### Proposal:

The current pdb completion could be improved for the following scenarios:
1. It should support alias if there is any
2. Convenience variables (starting with the `$`) should be supported as an expression
3. For the "command" completion, if there's no command matches, then the user is probably typing an expression to display and we should just complete as expression.

```
# The user probably wants $_frame
(pdb) $<tab>
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-110945
* gh-111826
* gh-112024
* gh-112025

**Comment by encukou** [comment]
All the PRs are merged! Thank you!
It looks like there's nothing more to do in this issue, so I'll close it.
