### ISSUE TITLE
50% of tests in `test__opcode` are not run

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#110923]
# Bug report

### Bug description:

Following https://github.com/python/cpython/commit/40f3f11a773b854c6d94746aa3b1881c8ac71b0f, `test__opcode.py` has two subclasses of `unittest.TestCase` in the global namespace that are both called `OpListTests`. This means that all tests in the first class are silently skipped in CI, as the whole class definition is overridden by the second class at import time, before unittest even tries to load the tests inside the class.

If the `TestCase` subclasses are given different names, the tests in the first class fail, as they rely on a helper method that was removed in https://github.com/python/cpython/commit/40f3f11a773b854c6d94746aa3b1881c8ac71b0f.

Cc. @iritkatriel as author of https://github.com/python/cpython/commit/40f3f11a773b854c6d94746aa3b1881c8ac71b0f

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-110926

**Comment by iritkatriel** [comment]
Yes. You assigned to yourself because you are working on a fix?

I'd rename the second class to StackEffectTests. Then fix the first one.

**Comment by AlexWaygood** [comment]
> Yes. You assigned to yourself because you are working on a fix?

I already file one, four minutes ago ;)

- #110926
