### ISSUE TITLE
[Enum] minor fixes and cleanup

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#110905]
# Bug report

### Bug description:

The `_is_private` method has incorrect results on attributes starting with a triple underscore. Example:

```python
import enum
enum._is_private('X', '_X___test') # returns True
```
The relevant code is:
```
def _is_private(cls_name, name):
    pattern = '_%s__' % (cls_name, )
    pat_len = len(pattern)
    if (
            len(name) > pat_len
            and name.startswith(pattern)
            and name[pat_len:pat_len+1] != ['_']
            and (name[-1] != '_' or name[-2] != '_')
        ):
        return True
    else:
        return False
```
The check `name[pat_len:pat_len+1] != ['_']` is always `False`, since `name[pat_len:pat_len+1]` is a `str` and `['_']` a list.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-110906
* gh-111042
* gh-111043

**Comment by sunmy2019** [comment]
> ```python
> import enum
> enum._is_private('X', '_X___test') # returns True
> ```

I don't see a problem with your example.

```py
>>> class X:
...   ___x = 1
...
>>> X._X___x
1
```

**Comment by sunmy2019** [comment]
The comparison of str and list is indeed buggy.

**Comment by ethanfurman** [comment]
Indeed - a self-cancelling bug!  Or a bug and an anti-bug... hmm.

Anyway, the correct fix is just to remove that line.

**Comment by ethanfurman** [comment]
The docs about [private variables](https://github.com/python/cpython/pull/110906#event-10658256229).

**Comment by eendebakpt** [comment]
Documentation: https://docs.python.org/3/tutorial/classes.html?highlight=private%20variable#private-variables:

Any identifier of the form `__spam` (at least two leading underscores, at most one trailing underscore) is textually
replaced with `_classname__spam`, where `classname` is the current class name with leading underscore(s) stripped.

**Comment by eendebakpt** [comment]
Closing the issue as the problem is resolved on the main branch. There are open PRs with backports to 3.11 and 3.12, but those are nice-to-have (can be closed afaic).

**Comment by sunmy2019** [comment]
@ethanfurman Will you merge the backport PR?

**Comment by ethanfurman** [comment]
Still considering.

**Comment by ethanfurman** [comment]
Closed the backports without merging.
