### ISSUE TITLE
invalid_def_raw and invalid_class_def_raw rules do not account for type parameters

### ISSUE THREAD

**Issue by MatthieuDartiailh** [python/cpython#110938]
# Bug report

### Bug description:

The rules which are affected are here: https://github.com/python/cpython/blob/6a4528d70c8435d4403e09937068a446f35a78ac/Grammar/python.gram#L1371

Typically I believe they should read
```
invalid_def_raw:
    | ['async'] a='def' NAME [type_params] '(' [params] ')' ['->' expression] ':' NEWLINE !INDENT {
        RAISE_INDENTATION_ERROR("expected an indented block after function definition on line %d", a->lineno) }
invalid_class_def_raw:
    | 'class' NAME [type_params] ['(' [arguments] ')'] NEWLINE { RAISE_SYNTAX_ERROR("expected ':'") }
    | a='class' NAME [type_params] ['(' [arguments] ')'] ':' NEWLINE !INDENT {
        RAISE_INDENTATION_ERROR("expected an indented block after class definition on line %d", a->lineno) }
```
to allow proper error reporting if the definition uses type parameters.

### CPython versions tested on:

3.12

### Linked PRs
* gh-110973
* gh-110986
* gh-110990
* gh-111023

**Comment by Eclips4** [comment]
cc @pablogsal @lysnikolaou and @JelleZijlstra as author of implementation of PEP 695

**Comment by pablogsal** [comment]
Will make a pr today

**Comment by sobolevn** [comment]
Sorry for being late with the review, but there are several test cases that are missing from @pablogsal's PR. I've opened a new one to address this case:

- before:
```python
>>> class A[T]
  File "<stdin>", line 1
    class A[T]
              ^
SyntaxError: invalid syntax
>>> class A[T]()
  File "<stdin>", line 1
    class A[T]()
                ^
SyntaxError: invalid syntax
```

- after:
```python
>>> class A[T]
  File "<stdin>", line 1
    class A[T]
              ^
SyntaxError: expected ':'
>>> class A[T]()
  File "<stdin>", line 1
    class A[T]()
                ^
SyntaxError: expected ':'
```

It is fixed, but not tested 👍
