### ISSUE TITLE
Windows: WindowsConsoleIO produces mojibake replacement characters

### ISSUE THREAD

**Issue by sorgloomer** [python/cpython#110913]
# Bug report

### Bug description:

Hi! The following code reliably produces some unicode [replacement characters �](https://www.compart.com/en/unicode/U+FFFD), on Windows, always in the same location. Works fine on Linux.

This report is a follow-up to this other one: https://github.com/python/cpython/issues/82052

[A fix was already attempted](https://github.com/python/cpython/pull/101103/files#diff-463599eb2f67c89107a6fc2431d387fef7fdbb8c860b2c424477ca9b9794282cR999), but as you can see, there are still some cases uncovered.

### Example 1

```python
print('é'*20001)
```
![image](https://github.com/python/cpython/assets/5985835/b1059ca2-0dee-48d4-9cbd-669b54967fcb)

### Example 2

This is an attempt at making a shorter example, and a bit of a stretch goal.

```sh
python -c "import sys;[sys.stdout.buffer.raw.write(b) for b in [b'\xc3', b'\xa9',b'\xc3\xa9']]"
```
![image](https://github.com/python/cpython/assets/5985835/8788d57c-9c49-41f9-9020-c4075c2dd551)

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-111007
* gh-111108
* gh-111109

**Comment by zooba** [comment]
Example 2 demonstrates the issue, but isn't relevant to our bugfix. It's bypassing our buffer, which is the only point we'd buffer a character and wait for the next one to be written.

I have no idea why example 1 works/fails though, unless it's a straightforward logic error in the code that's supposed to walk back at the end of the buffer.

**Comment by sorgloomer** [comment]
I think it is just that, a straightforward logic error. There was this comment in the original ticket:

> One thing this doesn't handle is if there isn't a UTF-8 final byte in the part of the buffer we are planning on converting, so len goes to 0. I can't imagine how that would happen, but I haven't checked if that's a possibility. And if it is, I don't know what else we can do about it...

The assessment here is incorrect, as "example 1" demonstrates, it can happen in a valid scenario. I think the problem is that the walkback does not properly analyze the utf8 encoding, it is essentially not searching for the previous complete utf8 character, it is looking for the last single-byte character, which is an important difference in this case.

An improved code could look for the last utf-8 start byte, and check if the codepoint is complete. Something like this:

```
static PyObject *
_io__WindowsConsoleIO_write_impl(winconsoleio *self, PyTypeObject *cls,
                                 Py_buffer *b)
{
    //...
    DWORD len, wlen, orig_len, last_char_start_idx, n = 0;
    char current_byte;
    // ...
        while (wlen > 32766 / sizeof(wchar_t)) {
            len /= 2;
            orig_len = len;
    
            len = _find_last_complete_char_end((char *)b->buf, len);
            if (len == 0) {
                // found an encoding error, the last character starts at index 0, or the buffer was empty: fall back
                len = orig_len;
            }
            wlen = MultiByteToWideChar(CP_UTF8, 0, b->buf, len, NULL, 0);
        }
    // ...
}

DWORD _find_last_complete_char_end(char* buf, DWORD len) {
    DWORD i, byte_count;
    char b;
    if (len == 0) {
        // error, empty buffer
        return 0;
    }
    i = len - 1;
    if ((buf[i] & 0x80) == 0) {
        // ok, last byte is a 1-byte character
        return len;
    }
    // last byte is part of a multibyte character, we have to search the start of the character to see if it is complete
    byte_count = 0;
    for (;;) {
        if ((buf[i] & 0xc0) != 0x80) {
            // not a continuation byte, conclude search
            break;
        }
        if (i == 0) {
            // error, only continuation characters found
            return 0;
        }
        i--;
        byte_count++;
        if (byte_count >= 4) {
            // error, did not find a character boundary in 4 bytes
            return 0;
        }
    }
    byte_count = _get_utf8_byte_count(buf[i]);
    if (byte_count == 0) {
        // error, invalid start byte
        return 0;
    }
    if (i + byte_count < i) {
        // error, overflow
        return 0;
    }
    if (i + byte_count > len) {
        // ok, last character is incomplete, return its start index
        return i;
    }
    if (i + byte_count < len) {
        // error, there was an excess of continuation characters
        return 0;
    }
    // ok, character was actually complete, last byte coincides with buffer end
    return len;
}

DWORD _get_utf8_byte_count(char first_byte) {
    if ((first_byte & 0x80) == 0x00)
        return 1;
    if ((first_byte & 0xe0) == 0xc0)
        return 2;
    if ((first_byte & 0xf0) == 0xe0)
        return 3;
    if ((first_byte & 0xf8) == 0xf0)
        return 4;
    return 0;
}
```

**Comment by zooba** [comment]
Ah, I see, the end byte doesn't necessarily have to have `0x80` unset, but it does have to match the byte count.

Could we use some logic instead where we back up by 4 bytes, read the value there, and move forward by up to 4 bytes based on the character? That should avoid any bad loops, and we know we have at least 4 bytes there already. Basically:

```
while (wlen > 32766 / sizeof(wchar_t)) {
    len = len / 2;
    if (len > 4) {
        len += _get_utf8_byte_count(((char *)b->buf)[len - 4]) - 4;
    }
    wlen = MultiByteToWideChar(CP_UTF8, 0, b->buf, len, NULL, 0);
}
```

**Comment by sorgloomer** [comment]
I am afraid we can't avoid a loop here. By backing up exactly 4 bytes we might find ourselves in the middle of another utf8 sequence.

**Comment by zooba** [comment]
I must be confusing encoding schemes in my (fever-riddled, right now) head, there's at least one out there where you can detect how many bytes are left in a sequence from anywhere in a sequence.

Is it better to back up and scan forward a small amount? Or cap the scan backwards? We ought to be able to get away with checking no more than the longest valid sequence, right?

**Comment by ChrisDenton** [comment]
To be clear, UTF-8 has the follow encoding (in binary) for one to four bytes:

```plain
0xxxxxxx
110xxxxx 10xxxxxx
1110xxxx 10xxxxxx 10xxxxxx
11110xxx 10xxxxxx 10xxxxxx 10xxxxxx
```

If on a continuation byte (high bits are `10`) then we only need to scan backwards until we find a byte whose high bits are `11`. Which will be in the previous 1 to 3 bytes, assuming valid UTF-8.

**Comment by sorgloomer** [comment]
> We ought to be able to get away with checking no more than the longest valid sequence, right?

Indeed. As long as the encoding is correct, we will only need to back up at most 4 bytes. No more than 3 continuation bytes ( 0b10xxxxxx ) appear in a sequence in a valid utf-8 encoded text, so capping it should not affect legit usecases.
![image](https://github.com/python/cpython/assets/5985835/29a754c7-6bd6-4d9d-987a-3bbea5acf425)

**Comment by sorgloomer** [comment]
How about

```
DWORD _find_last_utf8_boundary(char *buf, DWORD len) {
    /* This function never returns 0, returns the original len instead */
    DWORD count = 1;
    if (len == 0 || (buf[len - 1] & 0x80) == 0)
        return len;
    for (;; count++) {
        if (count > 3 || count >= len)
            return len;
        if ((buf[len - count] & 0xc0) != 0x80)
            return len - count;
    }
}

...

while (wlen > 32766 / sizeof(wchar_t)) {
    len /= 2;
    /* Fix for github issues gh-110913 and gh-82052. */
    len = _find_last_utf8_boundary(b->buf, len);
    wlen = MultiByteToWideChar(CP_UTF8, 0, b->buf, len, NULL, 0);
}
```

**Comment by hugovk** [comment]
Thank you for the report and fix!
