### ISSUE TITLE
asyncio.wait function docstring misleading

### ISSUE THREAD

**Issue by bharel** [python/cpython#110961]
# Documentation
According to [docstring](https://github.com/python/cpython/blob/99b7e1c1d7b02adaf98f24bfb843cc57b677f9d6/Lib/asyncio/tasks.py#L440) "Coroutines will be wrapped in Tasks.".
This was [deprecated](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait) starting at 3.11.
I can push out a fix sometime soon.

### Linked PRs
* gh-111017

**Comment by gvanrossum** [comment]
Sure, go ahead with the fix.
