### ISSUE TITLE
`test_zoneinfo` tests are silently skipped

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#110974]
# Bug report

This is how `test_zoneinfo` defines its package:

https://github.com/python/cpython/blob/b75b1f389f083db8568bff573c33ab4ecf29655a/Lib/test/test_zoneinfo/__init__.py

This is problematic, because there are clashin test-classes names in these files. For example:
- https://github.com/python/cpython/blob/b75b1f389f083db8568bff573c33ab4ecf29655a/Lib/test/test_zoneinfo/test_zoneinfo.py#L119
- https://github.com/python/cpython/blob/b75b1f389f083db8568bff573c33ab4ecf29655a/Lib/test/test_zoneinfo/test_zoneinfo.py#L404

And:
- https://github.com/python/cpython/blob/b75b1f389f083db8568bff573c33ab4ecf29655a/Lib/test/test_zoneinfo/test_zoneinfo_property.py#L94
- https://github.com/python/cpython/blob/b75b1f389f083db8568bff573c33ab4ecf29655a/Lib/test/test_zoneinfo/test_zoneinfo_property.py#L131

So, when running `./python.exe -m test test_zoneinfo`, some tests are not executed because of this clash. Proof:

- Before:
```
Total duration: 677 ms
Total tests: run=159 skipped=26
Total test files: run=1/1
Result: SUCCESS
```

- After:

```
Total duration: 567 ms
Total tests: run=211 skipped=26
Total test files: run=1/1
Result: SUCCESS
```

I have a patch ready.

### Linked PRs
* gh-110975

**Comment by hugovk** [comment]
Thanks for the fix!
