### ISSUE TITLE
[C API] Py_MOD_PER_INTERPRETER_GIL_SUPPORTED added to limited C API without versionning

### ISSUE THREAD

**Issue by vstinner** [python/cpython#110968]
Three constants for PyModuleDef_Slot were added to the limited C API in Python 3.13:

* Py_MOD_MULTIPLE_INTERPRETERS_NOT_SUPPORTED
* Py_MOD_MULTIPLE_INTERPRETERS_SUPPORTED
* Py_MOD_PER_INTERPRETER_GIL_SUPPORTED

Problem: there are added without version, as if they are available on Python 3.12 and older, whereas it's not the case.

cc @encukou @ericsnowcurrently 

### Linked PRs
* gh-110969
* gh-111584
* gh-111588

**Comment by ericsnowcurrently** [comment]
Yeah, it was definitely unintentional to expose any of these in the wrong place.

Also, they were added to 3.12 (1c420e138fd), right before feature freeze.  Would we be okay to add the version ifdefs in 3.12.1?  (I'd think so, but I sometimes get this subtle sort of compatibility concern wrong.)

> The bigger problem here is the slot ID, `Py_mod_multiple_interpreters`. It'll make the extension fail to load if used with an older version. That should definitely be in an `#ifdef`.

Agreed.  gh-110969 missed fixing it.

**Comment by vstinner** [comment]
> Also, they were added to 3.12 (https://github.com/python/cpython/commit/1c420e138fd828895b6bd3c44ef99156e8796095), right before feature freeze. Would we be okay to add the version ifdefs in 3.12.1?

Oh, I missed that. I wrote PR #111584 to fix the version check in the main branch, and then I will backport the change to the 3.12 branch.

**Comment by ericsnowcurrently** [comment]
Thanks for taking care of this, @vstinner!
