### ISSUE TITLE
Align Expected and Actual titles in assert_has_calls/assert_called_with for greater readability

### ISSUE THREAD

**Issue by morisja** [python/cpython#111019]
# Feature or enhancement

### Proposal:

The current output for `assert_called_with` and `assert_has_calls` has different spacing making visual identification of simple issues challenging. 

Example:
```pytb
  File "/usr/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: mock('foo', 'bar')
Actual: mock('foo', 'foo')     <-- moving this two chars to the right would be easier to see foo != bar

  File "/usr/lib/python3.10/unittest/mock.py", line 966, in assert_has_calls
    raise AssertionError(
AssertionError: Calls not found.
Expected: [call('foo', 'bar')]
Actual: [call('foo', 'foo')]   <-- moving this two chars to the right would be easier to see foo != bar
```
I propose whitespace is added preceding `Actual:` to align as follows:

```pytb
  File "/usr/lib/python3.10/unittest/mock.py", line 929, in assert_called_with
    raise AssertionError(_error_message()) from cause
AssertionError: expected call not found.
Expected: mock('foo', 'bar')
  Actual: mock('foo', 'foo')

  File "/usr/lib/python3.10/unittest/mock.py", line 966, in assert_has_calls
    raise AssertionError(
AssertionError: Calls not found.
Expected: [call('foo', 'bar')]
  Actual: [call('foo', 'foo')]
```

I chose preceding to minimize any potential parsing (e.g `Actual  :`  would make two fields if split by whitespace)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

I found similar, but not exact discussion here
https://github.com/python/cpython/issues/79681

### Linked PRs
* gh-111020
* gh-111024
* gh-111025

**Comment by terryjreedy** [comment]
An alternative would have been to click 'Expected' to 'Actual', but verb-adjective is a bit jarring.  Indent is fine and alignment will help.
