### ISSUE TITLE
pdb should check if the executing file is modified and warn users

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#111051]
# Feature or enhancement

### Proposal:

It's possible that the file is modified during debugging, which would definitely confuse users - the source will not match the execution anymore.

There's no perfect solution under such circunstances, but we should at least warn users that this is happening.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-111052
* gh-121959
* gh-122114

**Comment by ambv** [comment]
I often have an issue with the test for this when running on a RAM disk formatted with HFS+. That file system only has 1-second mtime resolution, so the test often doesn't register an mtime change and intermittently fails. Fix incoming.

**Comment by gaogaotiantian** [comment]
Hi @ambv , is this fixed now? Can we close this?
