### ISSUE TITLE
Python 3.12 inspecting a coroutine using `getcoroutinestate` returns the wrong state.

### ISSUE THREAD

**Issue by gottadiveintopython** [python/cpython#111058]
# Bug report

### Bug description:

Prior to Python 3.12, we can close a just created coroutine, thus, the following test passes:

```python
from inspect import getcoroutinestate, CORO_CLOSED


async def do_nothing():
    pass


def test_immediate_close():
    coro = do_nothing()
    coro.close()
    assert getcoroutinestate(coro) == CORO_CLOSED
```

But in Python 3.12, the assertion fails and `getcoroutinestate(coro)` still is `CORO_CREATED` after the `coro.close()`. You can confirm it from https://github.com/gottadiveintopython/py312/actions/runs/6571303025/job/17850194150.

I don't know if this is an intensional change or not, but I just wanted to tell you.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-112428
* gh-112589

**Comment by terryjreedy** [comment]
Same change on Windows. 3.13 like 3.12.

**Comment by Eclips4** [comment]
Bisected to f02fa64bf2d03ef7a28650c164e17a5fb5d8543d
cc @markshannon

**Comment by gottadiveintopython** [comment]
@Eclips4  Looks like it's a bug. Thank you for your investigation.

**Comment by markshannon** [comment]
The coroutine is closed, as `coro.send(None)` fails. It is just that `getcoroutinestate` returns the wrong value.
I've updated the title accordingly.

**Comment by iritkatriel** [comment]
`getcoroutinestate` does this:

```
    if coroutine.cr_running:
        return CORO_RUNNING
    if coroutine.cr_suspended:
        return CORO_SUSPENDED
    if coroutine.cr_frame is None:
        return CORO_CLOSED
    return CORO_CREATED
```


`coroutine.cr_frame` returns ``None`` for frames which have state `FRAME_CLEARED`, but not for `FRAME_COMPLETED`.

We can change `coroutine.cr_frame` to return ``None`` for completed frames too, or (if there is a backwards compatibility issue) we would need to add bool ``cr_completed`` to the coroutine API.

**Comment by Eclips4** [comment]
Thanks @gottadiveintopython for the report and Irit for fixing it!
