### ISSUE TITLE
3.13: PyFrame_GetCode(f)->co_firstlineno can be wrong

### ISSUE THREAD

**Issue by nedbat** [python/cpython#111081]
# Bug report

### Bug description:

I am stuck, and could use some help. This could be a coverage.py bug, or a CPython bug.  Using Python 3.13, I am getting incorrect data from `co_firstlineno`, but I don't know if there's a CPython bug, or if I am doing something wrong.

To reproduce: 

```bash
git clone https://github.com/nedbat/coveragepy
cd coveragepy
git checkout 5915e043e9bc911641eecbe13624f08af1f68ae7
pip install tox

COVERAGE_DEBUG=dataop,dataop2 COVERAGE_DEBUG_FILE=/tmp/debug.out tox -e py313 -- -n 0 -k test_report_skip_covered_branches_with_totals
```

When I run this, my debug.out looks like this (tmp filenames shortened):

```
Setting coverage context: None
Adding arcs: 3 files, 14 arcs total
  /tmp/t0/also_not_run.py: [(-1, 2), (2, -1)]
  /tmp/t0/main.py: [(-1, 2), (2, -1343), (-5, 6), (6, 7), (7, -5), (6, -5)]
  /tmp/t0/not_covered.py: [(-1, 2), (2, 5), (3, 4), (-2, 3), (4, -2), (5, -1)]
Adding file tracers: 0 files
```

"Arcs" are (from, to) pairs of line numbers that execution traversed.  A negative "from" number like in (-5, 6) means execution entered the code object that starts at line 5, and started at line 6.  A negative "to" number line in (6, -5) means that exection jumped from line 6 to exit the code object that starts at line 5.

The debug output shows that we tried to add pair (2, -1343) for main.py.  This means we think execution jumped from line 2 to exit from the code object that starts at line 1343. Except main.py is only 9 lines long (https://github.com/nedbat/coveragepy/blob/5915e043e9bc911641eecbe13624f08af1f68ae7/tests/test_report.py#L417-L437), so something is wrong.

The problem isn't particular to this one test, I've just selected one to provide a focused example.

I'm available on IRC or Discord if a live chat would help. I know this is far from a minimal reproduction.

### CPython versions tested on:

3.13.0a1

### Operating systems tested on:

macOS

**Comment by nedbat** [comment]
@mhammond @iritkatriel have I misunderstood something here?

**Comment by iritkatriel** [comment]
I think you meant to ping @markshannon

**Comment by nedbat** [comment]
Indeed... :(

**Comment by markshannon** [comment]
A few questions

* What is `f`? Is it a normal function or the temporary function we create for module level code?
* Are you sure that it is `co_firstlineno` that is wrong, not the offset. A correct `co_firstlineno` plus a large negative offset would have a similar effect
* Is this an issue in 3.12?
* Is there a smaller reproducer (in Python, C or a mix) that shows a negative `co_firstlineno` field, or some other anomaly?

**Comment by nedbat** [comment]
> What is `f`?

It's a frame object.  The line of code is [here](https://github.com/nedbat/coveragepy/blob/5915e043e9bc911641eecbe13624f08af1f68ae7/coverage/ctracer/tracer.c#L539).  `MyFrame_GetCode` is just a macro for `PyFrame_GetCode` [here](https://github.com/nedbat/coveragepy/blob/5915e043e9bc911641eecbe13624f08af1f68ae7/coverage/ctracer/util.h#L45-L46).  `frame` is a `PyFrameObject *` passed to the C trace function.

> Are you sure that it is `co_firstlineno` that is wrong, not the offset. A correct `co_firstlineno` plus a large negative offset would have a similar effect

I'm accessing the `co_firstlineno` member of the struct, then using it as a line number.  I don't see where I'm applying an offset, though I could be missing something.

> Is this an issue in 3.12?

No.

> Is there a smaller reproducer (in Python, C or a mix) that shows a negative `co_firstlineno` field, or some other anomaly?

I wish I had a smaller reproducer. I know it isn't fair to dump all this into a bug report.  I don't have a smaller one, though I have tried.

**Comment by markshannon** [comment]
If `PyFrame_GetCode(f)->co_firstlineno` is incorrect, that means one of two things: either
* `PyFrame_GetCode(f)` not a code object, or
* there a code object with an incorrect `co_firstlineno` 

Can you tell which is it?
It might help to print out `f` in a debugger like gdb.

**Comment by nedbat** [comment]
I cannot reproduce this.  The coverage.py commit I mentioned at the top no longer exists.  I tried a commit from that time on 3.13.0a3, and the problem is not happening.
