### ISSUE TITLE
BUG when using dict.fromkeys() and bisect.insort()

### ISSUE THREAD

**Issue by Ray-Lei-93** [python/cpython#111029]
### Bug description:

```python
import bisect
a=dict.fromkeys(range(3),[])
bisect.insort(a[2], 3)
```
The expected behavior of the above code is that only insert element 3 in a[2], so the dict a should look like this:
```python
{0: [], 1: [], 2: [3]}
```
However, it looks like this:
```python
{0: [3], 1: [3], 2: [3]}
```
It seems the origin dict has not "really" allocated the list to the dict. And I find that if you append an element before `bisect.insort`, that list won't be affected. And after `bisect.insort`, the origin `append` function for list will affect other lists.

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
This is not a bug in Python: ``dict.fromkeys(keys, value)`` sets ``value`` as the value for every key from ``keys``.

In your code ``a[0]``, ``a[1]`` and ``a[2]`` refer to the same list object, e.g. ``a[0] is a[2]``. 

Pleas ask questions about using Python on discord: https://discuss.python.org/c/users/7
