### ISSUE TITLE
 error: call to undeclared function 'sendfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]

### ISSUE THREAD

**Issue by tommyyama2020** [python/cpython#111033]
# Bug report

I am unsure that this is a bug. 
### Bug description:

When running `pyenv install 3.8.0` on my Mac, this error occurred and the installation failed. 

 `error: call to undeclared function 'sendfile'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]`

OS ver:  Sonoma ver 14.0

### CPython versions tested on:

3.8

### Operating systems tested on:

macOS

**Comment by ericvsmith** [comment]
A couple of things:
- 3.8 is a very old version, which now only gets security fixes, so no one here is likely to try and debug this.
- This looks like a problem with pyenv, not with python.
- You've not shown the entire error message, so there's not a lot to go on here.

I suggest asking for help on a pyenv forum, where you're more likely to find people familiar with this problem.

**Comment by ned-deily** [comment]
Not only is Python 3.8 very old and nearling end-of-life but you have specified Python 3.8.0, which was the first release of 3.8. The current release of 3.8 is 3.8.18 and with that version the error does not occur.

**Comment by tommyyama2020** [comment]
@ned-deily thanks
