### ISSUE TITLE
The tutorial https://packaging.python.org/en/latest/tutorials/packaging-projects/ does not work with hatch

### ISSUE THREAD

**Issue by LLyaudet** [python/cpython#111009]
# Documentation
Hello,

This tutorial
https://packaging.python.org/en/latest/tutorials/packaging-projects/
says:
"this tutorial uses [Hatchling](https://packaging.python.org/en/latest/key_projects/#hatch) by default, but it will work identically with [setuptools](https://packaging.python.org/en/latest/key_projects/#setuptools), [Flit](https://packaging.python.org/en/latest/key_projects/#flit), [PDM](https://packaging.python.org/en/latest/key_projects/#pdm), and others that support the [project] table for [metadata](https://packaging.python.org/en/latest/tutorials/packaging-projects/#configuring-metadata)."

But it seems it was converted from a tutorial with setuptools.
Hatchling does not seem to work well when the source of the package is in a src/ folder.
My repository here
https://github.com/LLyaudet/django-monkey-patches
demonstrates the problem.
I had to switch from hatch to setuptools to have a wheel that is correct.

Best regards,
    Laurent Lyaudet

**Comment by terryjreedy** [comment]
This is not the repository for the packaging docs.  This issue should be reopened in the appropriate repository.
The tutorial link above, at the bottom right corner, has a weblink button [`Found a bug?`.](https://github.com/pypa/packaging.python.org/issues)

**Comment by LLyaudet** [comment]
Thanks @terryjreedy :) I just did that : https://github.com/pypa/packaging.python.org/issues/1316
