### ISSUE TITLE
Add GitHub Action for checking free-threaded build

### ISSUE THREAD

**Issue by corona10** [python/cpython#111062]
Currently, nogil build has been added to buildbot, but it is inconvenient to check whether it is working properly in the PR stage.
So I would like to suggest: Putting a CI that checks nogil builds in Github Action.

This will satisfy the following conditions:
* It will only run against the main branch
* It will check only the build itself and does not run unittests
* (Optional) Even if it fails, it does not fail and does not interfere with other PRs.
(e.g https://github.com/python/pyperformance/pull/274)

If this happens, it will be very helpful in reviewing nogil-related PRs.

### Linked PRs
* gh-111060
* gh-111437
* gh-111440
* gh-111444
* gh-111446
* gh-111449
* gh-111452
* gh-111493
* gh-111494
* gh-111521
* gh-111552
* gh-111568
* gh-111570

**Comment by corona10** [comment]
As I shared on the discord, I will proceed this issue during the PyCon APAC sprint :)

**Comment by corona10** [comment]
We are going to set up the CI based on the reusable workflow that @hugovk suggested.
And CIs will be triggered only if the `topic-nogil` is attached.
I will separate it into multiple tasks that more people can participate on this issue.

- [x] Add `topic-nogil` label
- [ ] Add Linux CI based on reusable workflow: @corona10 
- [ ] Add macOS CI based on reusable workflow
- [ ] Add Windows(x86) CI based on reusable workflow
- [ ]  Add Windows(arm64) CI based on reusable workflow

**Comment by hugovk** [comment]
Please also open an issue about creating a new label: https://github.com/python/core-workflow/issues/new/choose

And see the end of the SC announcement:

> We want to avoid negatives in terms and flags and such, so we won’t get into double-negative terrain (like we do when we talk about ‘non no-GIL’). We’d like a positive, clear term to talk about the no-GIL build, and we’re suggesting ‘free-threaded’. (Relatedly, that’s why the build mode/ABI letter is ‘t’ and not ‘n’; that change was already made.) 

https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-in-cpython-acceptance/37075?u=hugovk

So perhaps `topic-free-threaded` is more appropriate.

**Comment by dimaqq** [comment]
Taking Linux

**Comment by NCLI** [comment]
**_I_** am taking Linux :-D

**Comment by corona10** [comment]
Good example: https://github.com/python/cpython/pull/110794#issuecomment-1763470794

**Comment by corona10** [comment]
@hugovk I will leave the name of reusable workflow to you since I am not sure which convention will be better.

**Comment by corona10** [comment]
Now macOS CIs supports both default and free-threaded mode (just for topic-free-threaded label).

**Comment by hugovk** [comment]
> @hugovk I will leave the name of reusable workflow to you since I am not sure which convention will be better.

We already had `reusable-docs.yml` used from `build.yml`, so `reusuable-[X].yml` is a good pattern.

And https://github.com/python/cpython/pull/111444 added `reusable-build-macos.yml`, also used from `build.yml`.

Shall we skip `-build-` in the middle, or do you think it's useful?

**Comment by corona10** [comment]
> Shall we skip -build- in the middle, or do you think it's useful?

I don't have any opinion for the convention, if you want you can change it as a separate PR :)

**Comment by encukou** [comment]
AFAICS, all the build need to be added to `allowed-skips`, otherwise docs-only pull requests are blocked -- see https://github.com/python/cpython/pull/111504

**Comment by corona10** [comment]
> AFAICS, all the build need to be added to allowed-skips, otherwise docs-only pull requests are blocked -- see https://github.com/python/cpython/pull/111504

@hugovk Can you follow up on this issue too? In my time zone, it's too late now. But some people may want to solve this issue ASAP.. I will also take a look at it tomorrow, from my timezone.

**Comment by hugovk** [comment]
Yes, I'll take a look this evening.

**Comment by hugovk** [comment]
Hi @webknjaz! We just added some more reusable workflows, but need to add some more config so they don't block docs builds. The new ones should be allowed to fail/skip. What are we missing?

**Comment by webknjaz** [comment]
*/me looks*

**Comment by webknjaz** [comment]
> We already had reusable-docs.yml used from build.yml, so reusuable-[X].yml is a good pattern.

FTR This is the pattern I decided to promote in my other projects, having seen how well it worked here and in a few other projects..

**Comment by hugovk** [comment]
btw I'm just about to open this as a PR: https://github.com/python/cpython/compare/main...hugovk:cpython:ci-update-skip-lists?expand=1

**Comment by webknjaz** [comment]
@hugovk do you have specific PRs for me to review? In general, it sounds about right. But there may be quirks related to conditionals and matrixes.

> We just added some more reusable workflows, but need to add some more config so they don't block docs builds. The new ones should be allowed to fail/skip. What are we missing?

**Comment by hugovk** [comment]
Please could you review https://github.com/python/cpython/pull/111521?

**Comment by webknjaz** [comment]
> AFAICS, all the builds need to be added to `allowed-skips`, otherwise docs-only pull requests are blocked -- see https://github.com/python/cpython/pull/111504

It seems like the skipped `build_windows` is at fault here. Perhaps, moving jobs to reusable workflows didn't take this into account correctly. Haven't looked into the changes from computer yet.

![Screenshot_2023-10-30-21-30-09-10_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/python/cpython/assets/578543/6dab4f4e-287d-4ff1-8885-8b62ab792ef8)

**Comment by webknjaz** [comment]
Yep. That's it:
![Screenshot_2023-10-30-21-35-01-15_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/python/cpython/assets/578543/7f32c82b-0d24-4cc8-8a46-004cda570f73)

![Screenshot_2023-10-30-21-35-12-63_320a9a695de7cdce83ed5281148d6f19.jpg](https://github.com/python/cpython/assets/578543/4eddaf44-9a54-4bb3-ae5c-8dc8d38899ee)

The `needs` context doesn't have those job names anymore. The action only sees the new job name.

**Comment by webknjaz** [comment]
> It will only run against the main branch
> It will check only the build itself and does not run unittests

I wonder if using merge queues would be helpful in this context..

**Comment by encukou** [comment]
Thank you for following up!

**Comment by webknjaz** [comment]
No problem! Tag me if you'll need instructions for skipping individual jobs inside those reusable workflows. That's possible, but rather tricky.

**Comment by corona10** [comment]
Now, I close the issue since we set up the basic workflows!
Thank you @hugovk

**Comment by hugovk** [comment]
Let's also backport to the 3.12 and 3.11 branches.

Obviously the free-threading bits won't be backported, but it will help to have the rest of the structure matching to make it easier to backport other changes.
