### ISSUE TITLE
"is" operator evaluation bug

### ISSUE THREAD

**Issue by TanixLu** [python/cpython#111028]
# Bug report

### Bug description:

```python
a = 10

a is a < 5       # False
a is a < 15      # True

# The expressions above should be interpreted by the interpreter as follows, 
# because the less-than operator (<) has higher precedence than 'is':
a is (a < 5)     # False
a is (a < 15)    # False

(a is a) < 5     # True
(a is a) < 15    # False
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
The code

```python3

a is a < 5
a is a < 15
```
is more or less equivalent to 

```python3

a is a and a < 5   # True and False -> False
a is a and a < 15. # True and True -> True
```

See https://docs.python.org/3/reference/expressions.html#comparisons

**Comment by AlexWaygood** [comment]
Yes, this isn't a bug; this is documented behaviour. If you have further questions on this topic, please ask them at https://discuss.python.org/c/users/7. The GitHub issue tracker is for bugs in CPython :)

**Comment by TanixLu** [comment]
Thank you for your prompt response. This completely answers my question.
