### ISSUE TITLE
Unnecessary `PyFrozenSet_Check` calls in `ast_opt.c`?

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#111133]
This code looks strange:
https://github.com/python/cpython/blob/37e4e20eaa8f27ada926d49e5971fecf0477ad26/Python/ast_opt.c#L177-L178
Function above intended as *safe mutiply*, but set (and frozenset) doesn't have `tp_as_number->nb_multiply` field, so it cannot be used with `*` operator.

### Linked PRs
* gh-111137

**Comment by Eclips4** [comment]
cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
You are right.

**Comment by Eclips4** [comment]
> You are right.

I'll send a PR ;)

**Comment by serhiy-storchaka** [comment]
Thank you Kirill.
