### ISSUE TITLE
Convert unsemantic monospaced directives to :ref:

### ISSUE THREAD

**Issue by InSyncWithFoo** [python/cpython#111151]
Directives like `:class:`, `:func:`, etc. auto-apply a monospaced font to the displayed text, which doesn't look very nice if used unsemantically. `:ref:` directives are the way to go when it comes to internal links with non-code text, and most of other internal links already follow this.

For example, this line in _Doc/library/typing.rst_:

https://github.com/python/cpython/blob/b07f23259d30e61fd7cc975b8b0e3b2e846fed8f/Doc/library/typing.rst#L307

...should be changed to:

```rst
variadic number of arguments, :ref:`overloaded functions <overload>`
```

And this line:

https://github.com/python/cpython/blob/b07f23259d30e61fd7cc975b8b0e3b2e846fed8f/Doc/library/typing.rst#L2775

...needs an _[explicit target](https://docs.readthedocs.io/en/stable/guides/cross-referencing-with-sphinx.html#explicit-targets)_:

```rst
.. _overload:

.. decorator:: overload
```

### Linked PRs
* gh-111152
* gh-111269
* gh-111270

**Comment by hugovk** [comment]
If we were talking about `overload` directly, monospace is good there.

But if we're essentially overriding it with other text, normal font seems more sensible.

* ``` :func:`overload` ``` in monospace -> "`overload`"
* ``` :func:`overloaded functions <overload>` ``` in normal font -> "overloaded functions"

I wonder if this is something Sphinx should be doing? But maybe the override text is actually another function name in some cases, and it's not safe for a blanket assumption.

cc @AA-Turner

**Comment by hugovk** [comment]
No need to apologise, I got the idea and your PR looks good from a quick check. 


To nitpick, an alternative to:

```rst
:meth:`baz_qux <foo.Bar.baz_qux>` 
```

Is something like:

```rst
:meth:`~foo.Bar.baz_qux`
```

But for another example, maybe we want to display only `Bar.baz_qux` so would use something like:

```rst
:meth:`Bar.baz_qux <foo.Bar.baz_qux>`
```

Which answers my question that we can't have a generic Sphinx solution for this, and specific fix like your PR is what we need. Thanks, I'll review the PR later.
