### ISSUE TITLE
`test_bad_new` in `test_descr` is silently skipped

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111128]
Code: https://github.com/python/cpython/blob/d8f32be5b6a736dc2fc9dca3f1bf176c82fc9b44/Lib/test/test_descr.py#L1791-L1802

Right now (if you remove `@unittest.expectedFailure`) it fails with:

```
======================================================================
FAIL: test_bad_new (test.test_descr.ClassPropertiesAndMethods.test_bad_new)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_descr.py", line 1798, in test_bad_new
    self.assertRaises(TypeError, C)
AssertionError: TypeError not raised by C

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (failures=1)
test test_descr failed
test_descr failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_descr

Total duration: 100 ms
Total tests: run=1 (filtered) failures=1
Total test files: run=1/1 (filtered) failed=1
Result: FAILURE
```

I propose to rewrite this test to pass. Because it looks like there's no similar test.
Or we can remove it if this test is not needed.

Refs https://github.com/python/cpython/issues/111101

### Linked PRs
* gh-111129

**Comment by serhiy-storchaka** [comment]
There is a bug in `__new__` method inheritance. See #49572. The test tests the expected behavior. `@expectedFailure` will be removed after fixing this bug.
