### ISSUE TITLE
C API: Consider adding a public PyList_Extend() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#111138]
# Feature or enhancement

The private `_PyList_Extend()` function has been removed in Python 3.13: see PR #108451.

@scoder [asked](https://github.com/python/cpython/pull/108451#issuecomment-1772792843) what is the replacement for this removed function.

The obvious replacement is ``PyObject_CallMethod(list, "extend", "O", arg)``: call the `list.extend()` method. But it's slower, `PyObject_CallMethod()` has to get the method and decode the "O" format string.

Another replacement is ``PyList_SetSlice(L, PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, arg)`` which is less straightforward, but it's efficient.

I propose adding a public PyList_Extend() function. The list type is commonly used in C extensions, it's a convenient API to create a collection when the length is not known is advance.

I don't think that performance is really the problem here since ``PyList_SetSlice(L, PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, arg)`` is available. The problem is more to more the function easier to discover and make the API easier to use. Also, it should help people to migrate away from the removed function.

There is already a public **PyDict_Update()** API for the dict type, it is part of the limited C API.

If we add a function for the list type, should we also add **PySet_Update()** "for completeness"? The private `_PySet_Update()` was removed in Python 3.13.

cc @serhiy-storchaka @encukou 

---

A code search on ``_PyList_Extend`` in PyPI top 5,000 projects (2023-07-04) found 4 projects using this function:

* Cython (0.29.36)
* catboost (1.2)
* mypy (1.4.1)
* pyrsistent (0.19.3)

Logs:

<details>

```
PYPI-2023-07-04/catboost-1.2.tar.gz: catboost-1.2/catboost_all_src/contrib/tools/cython/Cython/Compiler/Builtin.py: BuiltinMethod("extend",  "TO",   "r", "__Pyx_PyList_Extend",
PYPI-2023-07-04/catboost-1.2.tar.gz: catboost-1.2/catboost_all_src/contrib/tools/cython/Cython/Compiler/ExprNodes.py: extend_func = "__Pyx_PyList_Extend"
PYPI-2023-07-04/catboost-1.2.tar.gz: catboost-1.2/catboost_all_src/contrib/tools/cython/Cython/Utility/Optimize.c: static CYTHON_INLINE int __Pyx_PyList_Extend(PyObject* L, PyObject* v) {
PYPI-2023-07-04/catboost-1.2.tar.gz: catboost-1.2/catboost_all_src/contrib/tools/cython/Cython/Utility/Optimize.c: PyObject* none = _PyList_Extend((PyListObject*)L, v);

PYPI-2023-07-04/Cython-0.29.36.tar.gz: Cython-0.29.36/Cython/Compiler/Builtin.py: BuiltinMethod("extend",  "TO",   "r", "__Pyx_PyList_Extend",
PYPI-2023-07-04/Cython-0.29.36.tar.gz: Cython-0.29.36/Cython/Compiler/ExprNodes.py: extend_func = "__Pyx_PyList_Extend"
PYPI-2023-07-04/Cython-0.29.36.tar.gz: Cython-0.29.36/Cython/Utility/Optimize.c: static CYTHON_INLINE int __Pyx_PyList_Extend(PyObject* L, PyObject* v) {
PYPI-2023-07-04/Cython-0.29.36.tar.gz: Cython-0.29.36/Cython/Utility/Optimize.c: PyObject* none = _PyList_Extend((PyListObject*)L, v);

PYPI-2023-07-04/mypy-1.4.1.tar.gz: mypy-1.4.1/mypyc/lib-rt/dict_ops.c: PyObject *res = _PyList_Extend((PyListObject *)list, view);
PYPI-2023-07-04/mypy-1.4.1.tar.gz: mypy-1.4.1/mypyc/lib-rt/dict_ops.c: PyObject *res = _PyList_Extend((PyListObject *)list, view);
PYPI-2023-07-04/mypy-1.4.1.tar.gz: mypy-1.4.1/mypyc/lib-rt/dict_ops.c: PyObject *res = _PyList_Extend((PyListObject *)list, view);
PYPI-2023-07-04/mypy-1.4.1.tar.gz: mypy-1.4.1/mypyc/lib-rt/list_ops.c: return _PyList_Extend((PyListObject *)o1, o2);

PYPI-2023-07-04/pyrsistent-0.19.3.tar.gz: pyrsistent-0.19.3/pvectorcmodule.c: PyObject *retVal = _PyList_Extend((PyListObject *)self->appendList, args);
```

</details>

Cython uses the function to implement its own __Pyx_PyList_Extend() API:

```c
static CYTHON_INLINE int __Pyx_PyList_Extend(PyObject* L, PyObject* v) {
#if CYTHON_COMPILING_IN_CPYTHON
    PyObject* none = _PyList_Extend((PyListObject*)L, v);
    if (unlikely(!none))
        return -1;
    Py_DECREF(none);
    return 0;
#else
    return PyList_SetSlice(L, PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, v);
#endif
}
```

### Linked PRs
* gh-111582
* gh-111862

**Comment by serhiy-storchaka** [comment]
`PyDict_Update()` is not trivial. `PyList_Extend()` is trivial, literally one-liner.
```c
#define PyList_Extend(list, arg) PyList_SetSlice((list), PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, (arg))
```
I don't mind adding it as a macro. Together with `PyList_Clear()`.
```c
#define PyList_Clear(list) PyList_SetSlice((list), 0, PY_SSIZE_T_MAX, NULL)
```

**Comment by musicinmybrain** [comment]
Just noting that the proposed `PyList_Extend` macro is not an exact drop-in replacement for the removed `_PyList_Extend()` function, since the necessary error-checking is a bit different: `_PyList_Extend()` returns `PyObject *`, but `PyList_SetSlice()` returns `int`.

**Comment by vstinner** [comment]
> #define PyList_Extend(list, arg) ...

I dislike macros: they cannot be used in programming languages other than C, and in projects which only load libpython symbols (ex: vim text editor). See for example [PEP 670 – Convert macros to functions in the Python C API](https://peps.python.org/pep-0670/).

**Comment by musicinmybrain** [comment]
> For a method used in Python, it makes sense. For a C API, it looks inefficient to return None on success.

I agree, and I think returning `int` is the correct signature for a C API.

It’s just worth pointing out that extension authors porting to Python 3.13 will need to be aware that they cannot simply search-and-replace `_PyList_Extend` with the proposed `PyList_Extend`, despite the similar names. https://github.com/tobgu/pyrsistent/pull/284 is a good example.

**Comment by vstinner** [comment]
First step: I wrote PR #111582 to test the existing public PyList C API.

**Comment by vstinner** [comment]
PR gh-111562 added tests on the PyList C API.

I wrote PR gh-111862 to add PyList_Extend() and PyList_Clear() to the public C API.

**Comment by vstinner** [comment]
I close the issue.

Commit https://github.com/python/cpython/commit/babb787047e0f7807c8238d3b1a3128dac30bd5c adds PyList_Extend() and PyList_Clear(). I wrote https://github.com/python/pythoncapi-compat/pull/80 to add these functions to pythoncapi-compat.

@serhiy-storchaka's macros can also be used on Python 3.12 and older:

```c
#define PyList_Extend(list, arg) PyList_SetSlice((list), PY_SSIZE_T_MAX, PY_SSIZE_T_MAX, (arg))
#define PyList_Clear(list) PyList_SetSlice((list), 0, PY_SSIZE_T_MAX, NULL)
```

> If we add a function for the list type, should we also add PySet_Update() "for completeness"? The private _PySet_Update() was removed in Python 3.13.

I didn't add this function.
