### ISSUE TITLE
`test_set_of_sets_reprs` of `test_pprint` is silently ignored

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111147]
# Bug report

Right now this test is marked as `expectedFailure` with a big comment about why:
https://github.com/python/cpython/blob/b07f23259d30e61fd7cc975b8b0e3b2e846fed8f/Lib/test/test_pprint.py#L622-L646

With `self.maxDiff = None`:

```
» ./python.exe -m test test_pprint -m test_set_of_sets_reprs
Using random seed 3151060862
0:00:00 load avg: 1.34 Run 1 test sequentially
0:00:00 load avg: 1.34 [1/1] test_pprint
test test_pprint failed -- Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython/Lib/test/test_pprint.py", line 672, in test_set_of_sets_reprs
    self.assertEqual(pprint.pformat(cube), cube_repr_tgt)
AssertionError: '{fro[43 chars]set({1}), frozenset({0})}),\n frozenset({0}): [843 chars])})}' != '{fro[43 chars]set({0}), frozenset({1})}),\n frozenset({0}): [1017 chars])})}'
- {frozenset(): frozenset({frozenset({2}), frozenset({1}), frozenset({0})}),
-  frozenset({0}): frozenset({frozenset(), frozenset({0, 1}), frozenset({0, 2})}),
-  frozenset({1}): frozenset({frozenset(), frozenset({0, 1}), frozenset({1, 2})}),
? ^          ---                                       ---                ---
+ {frozenset(): frozenset({frozenset({2}), frozenset({0}), frozenset({1})}),
? ^                                  +++
+  frozenset({0}): frozenset({frozenset(),
+                             frozenset({0, 2}),
+                             frozenset({0, 1})}),
+  frozenset({1}): frozenset({frozenset(),
+                             frozenset({1, 2}),
+                             frozenset({0, 1})}),
+  frozenset({2}): frozenset({frozenset(),
+                             frozenset({1, 2}),
+                             frozenset({0, 2})}),
-  frozenset({0, 1}): frozenset({frozenset({1}),
?             ^  ^                          ^
+  frozenset({1, 2}): frozenset({frozenset({2}),
?             ^  ^                          ^
-                                frozenset({0}),
?                                           ^
+                                frozenset({1}),
?                                           ^
                                 frozenset({0, 1, 2})}),
-  frozenset({2}): frozenset({frozenset(), frozenset({0, 2}), frozenset({1, 2})}),
   frozenset({0, 2}): frozenset({frozenset({2}),
                                 frozenset({0}),
                                 frozenset({0, 1, 2})}),
-  frozenset({1, 2}): frozenset({frozenset({2}),
?              ---                          ^
+  frozenset({0, 1}): frozenset({frozenset({0}),
?             +++                           ^
                                 frozenset({1}),
                                 frozenset({0, 1, 2})}),
-  frozenset({0, 1, 2}): frozenset({frozenset({0, 1}),
?                                              ^  ^
+  frozenset({0, 1, 2}): frozenset({frozenset({1, 2}),
?                                              ^  ^
                                    frozenset({0, 2}),
-                                   frozenset({1, 2})})}
?                                               ---
+                                   frozenset({0, 1})})}
?                                              +++


test_pprint failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test_pprint

Total duration: 38 ms
Total tests: run=1 (filtered) failures=1
Total test files: run=1/1 (filtered) failed=1
Result: FAILURE
```

There are several problems with this test:
1. It creates an explicit relation with `test_set` because of an import: https://github.com/python/cpython/blob/b07f23259d30e61fd7cc975b8b0e3b2e846fed8f/Lib/test/test_pprint.py#L11 We try to revome such dependencies
2. It does not work :)
3. It is not very readable:

<img width="1352" alt="Снимок экрана 2023-10-21 в 08 49 09" src="https://github.com/python/cpython/assets/4660275/bbf78fe6-f881-494c-b84e-2581aec4b199">

Why is this test unstable? Because `frozenset({0}) < frozenset({1}) is False` and `frozenset({1}) < frozenset({0}) is False`. However, we can refator this test to use `frozenset()`, it is always ordered: `frozenset() < frozenset({1, 2}) is True`, `frozenset() > frozenset({1, 2}) is False`

So, my idea is to:
- Refactor this test to still do pretty much the same
- But reliably 
- With more readability
- Without `test_set` dependency

Refs:
- https://github.com/python/cpython/commit/969fe57baa0eb80332990f9cda936a33e13fabef
- https://bugs.python.org/issue13907

### Linked PRs
* gh-111148

**Comment by serhiy-storchaka** [comment]
The test was originally added in Python 2.6 in 5310b6941965afa3a40e61e8315590c931dc47e6 (logs for main do not show this). Then marked as CPython-only with adding a large comment in bpo-9131 (#53377). Then marked as expected failure in bpo-13903 (#58111). Stable part of the test was moved to other test method.

See also related issue bpo-27495 (#71682).

I think that @rhettinger as the original author of tests and the maintainer of these classes should decide what to do with this test. Should it be rewritten for non-deterministic order or removed?
