### ISSUE TITLE
Syntax: Mismatching order of conditional expression evaluation

### ISSUE THREAD

**Issue by awwright** [python/cpython#111135]
# Bug report

### Bug description:

The syntax for a conditional expression changes depending on the context the logic is found in: If in a [conditional expression](https://mail.python.org/pipermail/python-dev/2005-September/056846.html), or if in a [statement](https://docs.python.org/3/reference/compound_stmts.html#if).

This can be verified by checking the full grammar specification, which uses an `if` symbol in two distinct places, once in the "if_stmt" production (itself referenced as an alternative in the "compound_stmt" production) and again as one of a few alternatives for the "expression" production. This would ordinarily be an acceptable way to factor the grammar, if not for the fact that the order of evaluation is inconsistent: the "if_stmt" production accepts expressions in "test, then, else" order and the "expression" production accepts statements in the "then, test, else" order. Unsurprisingly, this is confusing.

And this also violates a long-standing expectation that evaluation happens in a defined order; if I have any two expressions _a_ and _b_, in that order in a file, the result of _b_ should never impact the evaluation of _a_, unless _a_ could sometimes impact _b_ (in which case the rule is _ambiguous_).

Here, when reading the `expression` production `disjunction 'if' disjunction 'else' expression`, that ordering suggests that the first "disjunction" would be evaluated first, and the value will affect the execution of the second disjunction.

But in the actual execution, this is not the case:

```python3
def x(n):
        print(n);
        return n;
x(x(1) if x(2) else x(3));
```

In this file, I should expect to see `1` be the first line of output, but surprisingly it's `2`: It's skipping over the evaluation of x(1), running x(2), then deciding based on the return value to evaluate x(1).

This mistake appears to have been introduced in https://mail.python.org/pipermail/python-dev/2005-September/056846.html then formalized in https://peps.python.org/pep-0308/

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
The design of conditional expressions has been in Python for a long time now and it is unlikely to be changed.

If you want this changed, you'll have to write and champion a PEP, but it's highly unlikely that such a proposal would be accepted.

**Comment by ericvsmith** [comment]
The PEP discusses this short-circuit evaluation in a number of places. For example, see https://peps.python.org/pep-0308/#short-circuit-behavior. This isn't going to change.

**Comment by terryjreedy** [comment]
For the purpose of this tracker, a bug is a discrepancy between doc and implementation.  The [doc](https://docs.python.org/3/reference/expressions.html#conditional-expressions) clearly states the observed behavior: "The expression x if C else y first evaluates the condition, C rather than x."  AFAIK, the last time we made syntax changes that broke working Python code was for 3.0.  We currently have no plans to do so again.
