### ISSUE TITLE
Move test running code from test.support to libregrtest

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111165]
`test.support.run_unittest()` was used to run unit tests, but now all tests are collected using standard unittest mechanism. Currently it is only used in libregrtest, and its code can be moved there.

`test.support.run_doctest()` was used to run doctests, but now they are integrated in unit tests using `DocTestSuite` and `DocFileSuite`. It is no longer used, and can be removed.

### Linked PRs
* gh-111166
* gh-111316
* gh-111318
* gh-111327
* gh-111328
* gh-111329
* gh-111467
* gh-111471
* gh-111472

**Comment by serhiy-storchaka** [comment]
cc @vstinner

**Comment by vstinner** [comment]
Can this issue be closed?
