### ISSUE TITLE
Types `f` and `e` in format spec does not remove trailing zeros for floats if precision is not specified

### ISSUE THREAD

**Issue by Prometheus3375** [python/cpython#111125]
# Bug report

### Bug description:

I will report this as a bug, however, this can be an issue with documentation.

By the docs of [format specification mini-language](https://docs.python.org/3/library/string.html#format-specification-mini-language):

> `'f'` -- Fixed-point notation. For a given precision p, formats the number as a decimal number with exactly p digits following the decimal point. With no precision given, uses a precision of 6 digits after the decimal point for [float](https://docs.python.org/3/library/functions.html#float), and uses a precision large enough to show all coefficient digits for [Decimal](https://docs.python.org/3/library/decimal.html#decimal.Decimal). **If no digits follow the decimal point, the decimal point is also removed unless the # option is used.**

I am focusing on the bold part. Let's test it.

Integers, floats and complex numbers:
```python
>>> f'{1:f}'
'1.000000'
>>> f'{1.:f}'
'1.000000'
>>> f'{1+1j:f}'
'1.000000+1.000000j'
>>> f'{.1:f}'
'0.100000'
```

Decimals:
```python
>>> from decimal import Decimal
>>> f'{Decimal(1):f}'
'1'
>>> f'{Decimal(1.):f}'
'1'
>>> f'{Decimal(.1):f}'
'0.1000000000000000055511151231257827021181583404541015625'
```

> If no digits follow the decimal point, the decimal point is also removed unless the # option is used.

The sentence goes after mentioning Decimal. So maybe the sentence speaks only about them? If so, then note about `#` must work.

```python
>>> from decimal import Decimal
>>> d = Decimal(1)
>>> f'{d:#f}'
ValueError: invalid format string
```

As intended, because per `#` documentation:

> The '#' option causes the “alternate form” to be used for the conversion. The alternate form is defined differently for different types. **This option is only valid for integer, float and complex types**

The further docs of `#` also suggest that `f` must remove trailing zeros:

> For float and complex the alternate form causes the result of the conversion to always contain a decimal-point character, even if no digits follow it. **Normally, a decimal-point character appears in the result of these conversions only if a digit follows it.** In addition, for 'g' and 'G' conversions, trailing zeros are not removed from the result.

The same issue is true for format types `e`, `F` and `E`.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
The behavior corresponds to the documentation. Where do you see the bug?

**Comment by Prometheus3375** [comment]
The documentation says:

> If no digits follow the decimal point, the decimal point is also removed unless the # option is used.

An integer does not have digits after the decimal point, but `f{1:f}` returns `1.000000`.

**Comment by serhiy-storchaka** [comment]
Other examples:
```
>>> f'{1:.0f}'
'1'
>>> f'{1.0:.0f}'
'1'
>>> f'{1+1j:.0f}'
'1+1j'
```
:point_up: "If no digits follow the decimal point, the decimal point is also removed..."
```
>>> f'{1:#.0f}'
'1.'
>>> f'{1.0:#.0f}'
'1.'
>>> f'{1+1j:#.0f}'
'1.+1.j'
```
:point_up: "... unless the # option is used."

**Comment by serhiy-storchaka** [comment]
`f{1:f}` returns `1.000000` which has digits after the decimal point.

**Comment by Prometheus3375** [comment]
Oh, I see. Thank you for the answer! I got a bit confused with docs which places comment about no digits after mentioning the case with no precision given.
