### ISSUE TITLE
To be noticed

### ISSUE THREAD

**Issue by RohitMugalya** [python/cpython#111117]
# Bug report

### Bug description:

```python
class MyClass:
    def __init__(self, var1, var2):
        self.var1 = var1
        self.var2 = var2
        setattr(self, '|my-pvt-var|', 'pvt-val')    #    To Be Noticed

mc = MyClass()
```

Actually this doesn't raise any error but is this a error prone what I mean is will this cause any side effects?
anyway we can't access this by saying `mc.|my-pvt-var|` only by `getattr()` though my only doubt *"IS THIS SAFE?"*  still I tried `mc.__dict__` it is there in the mappingproxy.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
It's intended behaviour.
From [docs](https://docs.python.org/3/library/functions.html?highlight=setattr#setattr):

> This is the counterpart of [getattr()](https://docs.python.org/3/library/functions.html?highlight=setattr#getattr). The arguments are an object, a string, and an arbitrary value. The string may name an existing attribute or a new attribute. The function assigns the value to the attribute, provided the object allows it. For example, setattr(x, 'foobar', 123) is equivalent to x.foobar = 123.
name need not be a Python identifier as defined in [Identifiers and keywords](https://docs.python.org/3/reference/lexical_analysis.html#identifiers) unless the object chooses to enforce that, for example in a custom [__getattribute__()](https://docs.python.org/3/reference/datamodel.html#object.__getattribute__) or via [__slots__](https://docs.python.org/3/reference/datamodel.html#object.__slots__). An attribute whose name is not an identifier will not be accessible using the dot notation, but is accessible through [getattr()](https://docs.python.org/3/library/functions.html?highlight=setattr#getattr) etc..
