### ISSUE TITLE
broken optimization in gen_close()

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#111107]
There is an optimization in gen_close which attempts to shortcut the case where a sub-generator is being closed, and it is wrapped in only one try block (which is presumed to be for the ``StopIteration`` so can be ignored). 

However, there is a bug there where the exception depth is taken from ``frame->prev_instr[0].op.code``, where it should be ``frame->prev_instr[0].op.arg``. 

At the moment this optimization is not doing anything because `exception_handler_depth` is never 1, it is either 118 (opcode of `YIELD_VALUE`) or 241 (opcode of `INSTRUMENTED_YIELD_VALUE`).   If one of those opcodes will happen to be mapped to 1, then this code will have some impact but obviously not the intended one.

CC @markshannon

**Comment by iritkatriel** [comment]
If I try to fix the typo and use `op.arg` instead of `op.code`, some tests fail: https://github.com/python/cpython/pull/111069

**Comment by iritkatriel** [comment]
The failure in testcontextlib is fixed by setting the frame state in case we return early:

         if (exception_handler_depth == 1) {
+            gen->gi_frame_state = FRAME_COMPLETED;
             Py_RETURN_NONE;
         }

**Comment by Eclips4** [comment]
Probably related: #111058

**Comment by Eclips4** [comment]
Probably related: #111058

**Comment by iritkatriel** [comment]
Perf measurement for https://github.com/python/cpython/pull/111069:

https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20231020-3.13.0a1%2B-90d6409/bm-20231020-linux-x86_64-iritkatriel-refleak-3.13.0a1%2B-90d6409-vs-base.md
