### ISSUE TITLE
Crash of interpreter due to assign before global declaration

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#111132]
# Crash report

### What happened?

```python
def bar():
    x = 11
    global x
    return x

bar()
```

Traceback:
```python
File "/Users/admin/Projects/cpython/example.py", line 3
    global x
    ^^^^^^^^
SyntaxError: name 'x' is assigned to before global declaration
Assertion failed: ((gc->_gc_next & NEXT_MASK_UNREACHABLE) == next_value), function validate_list, file gcmodule.c, line 403.
zsh: abort      ./python.exe example.py
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-111136

**Comment by Eclips4** [comment]
Bisected to e1d8c65e1df990ef8d61b8912742e1a021395e78
cc @pablogsal

**Comment by chgnrdv** [comment]
FYI, these are examples of code that hit the same assertion:
```python
def f(x):
    global x
```
```python
def f():
    global x
    nonlocal x
```
```python
x = 0
def f():
    nonlocal x
```

**Comment by chgnrdv** [comment]
Commenting out this decref made issue go away.
https://github.com/python/cpython/blob/37e4e20eaa8f27ada926d49e5971fecf0477ad26/Python/pythonrun.c#L1279-L1281

**Comment by pablogsal** [comment]
Thanks a lot @sobolevn for the fix and @Eclips4 for the report!
