### ISSUE TITLE
`test_restored_object_new` in `test_descr` is silently ignored

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111101]
# Bug report

It is marked as `expectedFailure`: https://github.com/python/cpython/blame/c42c68aa7bd19b0de7f2132ed468bc4ce83d8aa9/Lib/test/test_descr.py#L1838-L1860

So, in other words: it can fail for whatever reason and nobody will know that.
I have an alternative solution ready.

### Linked PRs
* gh-111102

**Comment by serhiy-storchaka** [comment]
Python has a bug. `@expectedFailure` will be removed if that bug be fixed.
