### ISSUE TITLE
Objects/typeobject.c: No such file or directory.

### ISSUE THREAD

**Issue by LinanV** [python/cpython#111203]
# Crash report

### What happened?

hi, team:
    my python version is 3.7.9; os:  CentOS 7.3 Linux localhost.localdomain 3.10.0-514.el7.x86_64;
    I got a Segmentation fault as flow:
Program terminated with signal 11, Segmentation fault.
#0  0x00000000004ae966 in add_tp_new_wrapper (type=0x7f487bc06a70) at Objects/typeobject.c:5966
5966    Objects/typeobject.c: No such file or directory.
(gdb) bt
#0  0x00000000004ae966 in add_tp_new_wrapper (type=0x7f487bc06a70) at Objects/typeobject.c:5966
#1  add_operators (type=0x7f487bc06a70) at Objects/typeobject.c:7462
#2  PyType_Ready (type=0x7f487bc06a70) at Objects/typeobject.c:5214
#3  0x00000000004af58e in find_name_in_mro (type=<optimized out>, name=0x18600c0, error=0x7f4889fa9660) at Objects/typeobject.c:3078
#4  0x00007f4863b3af48 in ?? ()
#5  0x00007f4863b3add0 in ?? ()
#6  0x00007f48631652d0 in ?? ()
#7  0x00007f4863185a10 in ?? ()
#8  0x00000000004f4209 in _PyEval_EvalFrameDefault (f=0x49bb9e <_PyObject_LookupAttr+94>, throwflag=2076207728) at Python/ceval.c:878
#9  0x0000000000461e9a in _PyBytes_DecodeEscape (s=0x7ffcb517e360 "\320R\026cH\177", len=139949258015200, errors=<optimized out>, unicode=<optimized out>,
    recode_encoding=<optimized out>, first_invalid_escape=<optimized out>) at Objects/bytesobject.c:1195
#10 0x00000000004905e3 in clone_combined_dict (orig=0x7f4889fd3770) at Objects/dictobject.c:645
#11 PyDict_Copy (o=0x7f4889fd3770) at Objects/dictobject.c:2590
#12 0x00007ffcb517e6b0 in ?? ()
#13 0x00007f4866d06d70 in ?? ()
#14 0x000000000048b256 in lookdict_unicode_nodummy (mp=<optimized out>, key=0x7f488a029910, hash=139948940347424, value_addr=<optimized out>)
    at Objects/dictobject.c:863
#15 0x0000000000088428 in ?? ()
#16 0x00007f48809664d0 in ?? ()
#17 0x00007f4866d1d4d0 in ?? ()
#18 0x00007f48631980b0 in ?? ()
#19 0x00007f488a002950 in ?? ()
#20 0x00007f487c7138d4 in ?? ()
#21 0x00007f4866e0e1e0 in ?? ()
#22 0x000000000046dee4 in frame_tp_clear (f=0x7f488a029910) at Objects/frameobject.c:547
#23 0x0000000000000001 in ?? ()
#24 0x0000000002442f28 in ?? ()
#25 0x0000000000000001 in ?? ()
#26 0x000000000100e8f0 in ?? ()
#27 0x0000000000461e9a in _PyBytes_DecodeEscape (s=0x100e8f0 "\200\377/\001", len=4764246, errors=<optimized out>, unicode=<optimized out>,
    recode_encoding=<optimized out>, first_invalid_escape=<optimized out>) at Objects/bytesobject.c:1195
#28 0x00007ffcb517e9d0 in ?? ()
#29 0x00007ffcb517e910 in ?? ()
#30 0x00007f487b5f79c0 in ?? ()
#31 0x00007f4866d1c450 in ?? ()
#32 0x00007f4863185a10 in ?? ()
#33 0x0000000002192fa0 in ?? ()
#34 0x00007f487b5f7990 in ?? ()
#35 0x00007ffcb517ea30 in ?? ()
#36 0x0000000000000030 in ?? ()
#37 0x00007f4889feb430 in ?? ()
#38 0x0000000001340330 in ?? ()
#39 0x00007f4866d1c450 in ?? ()
#40 0x00007f4863185a10 in ?? ()
#41 0x0000000002192fa0 in ?? ()
#42 0x0000000000464ecc in _PyObject_FastCallDict (kwargs=0x0, nargs=<optimized out>, args=0x7f487c7137b0, callable=0x7f4889feb430) at Objects/call.c:128
#43 object_vacall (callable=0x7f4889feb430, vargs=<optimized out>) at Objects/call.c:1200
#44 0x00000000004af77b in find_name_in_mro (type=0x7f48822d97f0, name=0x48b256 <lookdict_unicode_nodummy+278>, error=0x7f4866d1c450) at Objects/typeobject.c:3048
#45 0x000000000049b278 in _PyObject_GenericGetAttrWithDict (suppress=0, dict=0x0, name=0x7f48822d97f0, obj=0x7f4863185a10) at Objects/object.c:1237
#46 PyObject_GenericGetAttr (name=0x7f48822d97f0, obj=0x7f4863185a10) at Objects/object.c:1309
#47 PyObject_GetAttr (name=0x7f48822d97f0, v=0x7f4863185a10) at Objects/object.c:913
#48 _PyObject_GetAttrId (v=0x7f4863185a10, name=<optimized out>) at Objects/object.c:875
#49 0x00000000004f3929 in builtin_exec_impl (module=<optimized out>, locals=0x7f4866e0d5f6, globals=0x245ac48, source=<optimized out>) at Python/bltinmodule.c:1095
#50 builtin_exec (module=<optimized out>, args=<optimized out>, nargs=<optimized out>) at Python/clinic/bltinmodule.c.h:283
---Type <return> to continue, or q <return> to quit---
#51 0x00007f4889feb050 in ?? ()
#52 0x00007f4862c73dd0 in ?? ()
#53 0x00000000004ae8be in add_methods (meth=0x0, type=0x0) at Objects/typeobject.c:4829
#54 PyType_Ready (type=0x0) at Objects/typeobject.c:5217
#55 0x00000000004af5b7 in find_name_in_mro (type=<optimized out>, name=0x7f4866d1d560, error=0x7f4866e0d6c0) at Objects/typeobject.c:3083
#56 0x00000000005646c1 in _PyCode_ConstantKey (op=0x245aad0) at Objects/codeobject.c:514
#57 0x00007f4866e0ea50 in ?? ()
#58 0x00000000032fc620 in ?? ()
#59 0x0000000066e09510 in ?? ()
#60 0xffffffffffffffff in ?? ()
#61 0x00007f4864423fa0 in ?? ()
#62 0x00007f4866e094e0 in ?? ()
#63 0xf1f800ec5aa700e0 in ?? ()
#64 0x0000000000000006 in ?? ()
#65 0x0000000000000001 in ?? ()
#66 0x0000000000000000 in ?? ()

Could U tell me how to deal with this problem.

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.7.9 (default, Oct 13 2023, 00:08:33) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

**Comment by ronaldoussoren** [comment]
First of all Python 3.7 has reached the end of its support window for us.

But more importantly, without a way to reproduce the issue there's not enough information in the issue to tell what the problem might be.

**Comment by LinanV** [comment]
thanks, then I can only try to upgrade to a higher version.

**Comment by ronaldoussoren** [comment]
RedHat and through that indirectly Centos still supports Python 3.7, but the core developers do not.

Finding the issue starts by having a way to reproduce the issue, otherwise it will be very hard to debug the issue regardless of the Python version. 

Anyway, good luck in trying to resolve the problem!
