### ISSUE TITLE
Error in example of `tempfile` module

### ISSUE THREAD

**Issue by kkarbowiak** [python/cpython#111282]
# Documentation

The third example in [Examples](https://docs.python.org/3.13/library/tempfile.html#examples) section of `tempfile` module shows creating `TemporaryFile` with `delete_on_close` parameter, however the parameter is present only in `NamedTemporaryFile` class. Also, a colon is missing several lines below.

The [Examples](https://docs.python.org/3.12/library/tempfile.html) in 3.12 version is the same, so both 3.13 and 3.12 versions are affected.

### Linked PRs
* gh-111283
* gh-111579

**Comment by DavidCoy77** [comment]
Hello, I'm an undergraduate computer science student and I'm eager to make a first contribution to GitHub. Would you be willing to offer some guidance to help me through this issue? Thanks!

**Comment by DavidCoy77** [comment]
Oops! Sorry, that's my fault for not noticing.

**Comment by zware** [comment]
Thanks for the report and patch, @kkarbowiak!
