### ISSUE TITLE
`socketmodule.c` does not handle errors on module creation extension-modules 

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111253]
# Bug report

It handles most with a specialized macro:
https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/socketmodule.c#L7716-L7722

but not these ones:

https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/socketmodule.c#L7724-L7731

Introduced in https://github.com/python/cpython/pull/96536

### Linked PRs
* gh-111254
* gh-111299

**Comment by vstinner** [comment]
Fixed in 3.12 and main branches.
