### ISSUE TITLE
`_selectmodule.c` does not handle errors when creating a module

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111233]
# Bug report

It is documented that `PyModule_AddIntMacro` can raise an error (and it can in fact):

```rst
.. c:macro:: PyModule_AddIntMacro(module, macro)

   Return ``-1`` on error, ``0`` on success.
```

But, some calls are not checked for errors:

https://github.com/python/cpython/blob/96cbd1e1db3447a33e5cc5cc2886ce79b61cc6eb/Modules/selectmodule.c#L2471-L2476

### Linked PRs
* gh-111234

**Comment by hugovk** [comment]
Thanks!
