### ISSUE TITLE
`timemodule.c` does not handle errors on module creation

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111295]
# Bug report

Here are the problematic lines: https://github.com/python/cpython/blob/8b44f3c54bb4f99445c108bc0240c458adae9c6f/Modules/timemodule.c#L1766-L1772

https://github.com/python/cpython/blob/8b44f3c54bb4f99445c108bc0240c458adae9c6f/Modules/timemodule.c#L1831-L1833

https://github.com/python/cpython/blob/8b44f3c54bb4f99445c108bc0240c458adae9c6f/Modules/timemodule.c#L1836-L1838

However, in some cases it uses the correct approach: https://github.com/python/cpython/blob/8b44f3c54bb4f99445c108bc0240c458adae9c6f/Modules/timemodule.c#L1985-L1987

### Linked PRs
* gh-111296
* gh-111300

**Comment by vstinner** [comment]
Fixed in 3.12 and main branches.
