### ISSUE TITLE
LC_CTYPE incorrectly references case sensitivity of "the functions of module `string`"

### ISSUE THREAD

**Issue by glyph** [python/cpython#111276]
# Documentation

https://docs.python.org/3.12/library/locale.html#locale.LC_CTYPE says:

> Locale category for the character type functions. Depending on the settings of this category, the functions of module [string](https://docs.python.org/3.12/library/string.html#module-string) dealing with case change their behaviour.

I believe this is referring to Python 2.7's ['`string.lower`](https://docs.python.org/2.7/library/string.html?highlight=string#string.lower) et. al., which have been gone for quite some time.  I think since Python 3.3 unicode case-conversion functions have quite intentionally been locale-independent.

Confusion about this issue seems pervasive, even in CPython itself; consider this bit of code with a somewhat misleading comment: https://github.com/python/cpython/blob/b180120468c100e8c77696ed90b892db59c699c7/Lib/logging/handlers.py#L836-L847

So it would be good to clean up the docs.  Earlier in the same document it does say:

> There is no way to perform case conversions and character classifications according to the locale. For (Unicode) text strings these are done according to the character value only, while for byte strings, the conversions and classifications are done according to the ASCII value of the byte, and bytes whose high bit is set (i.e., non-ASCII bytes) are never converted or considered part of a character class such as letter or whitespace.

### Linked PRs
* gh-111319
* gh-111391
* gh-111392

**Comment by glyph** [comment]
Thanks a ton @ambv ! Glad to see this obscure little corner get cleaned up.

**Comment by hugovk** [comment]
Closing because the PRs have been merged. Thanks for the report!
