### ISSUE TITLE
Documentation of `pow` is incorrect regarding `**`

### ISSUE THREAD

**Issue by RunDevelopment** [python/cpython#111228]
# Documentation

The documentation of [the `pow` function](https://docs.python.org/3/library/functions.html#pow) currently states:

> The two-argument form `pow(base, exp)` is equivalent to using the power operator: `base**exp`.

This is incorrect for negative `base` with exponents between 0 and 1 (both exclusive). E.g.:

```py
>>> pow(-9, 0.5)
(1.8369701987210297e-16+3j)
>>> -9 ** 0.5
-3.0
```

(Tested for Python 3.8.2 and 3.10.6.)

While `pow` returns a complex value, `**` simply returns the negative square root of the absolute value of `base`.

Note that this is only the difference in behavior that I observed so far. Issue https://github.com/python/cpython/issues/60200 suggests there might be more.

**Comment by Eclips4** [comment]
Hello!
There's no bug. `**` has a higher precedence than the negation operator `-`.
So, your expression calculates as `-(9 ** 0.5)`.
FYI: https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by RunDevelopment** [comment]
I see. Thank you!

Maybe in Python 4, this could be invalid syntax to protect against this footgun. I mean, JS made this invalid syntax. 
```js
> -9 ** 0.5
-9 ** 0.5
^^^^^

Uncaught:
SyntaxError: Unary operator used immediately before exponentiation expression. Parenthesis must be used to disambiguate operator precedence
```
