### ISSUE TITLE
Missing `,` in readme.rst

### ISSUE THREAD

**Issue by innovinitylabs** [python/cpython#111240]
# Documentation

(A clear and concise description of the issue.)

in the last line of readme,

"There are interfaces to some GNU code but these are entirely optional." should be "There are interfaces to some GNU code, but these are entirely optional."

### Linked PRs
* gh-111241

**Comment by gaogaotiantian** [comment]
I don't believe CPython takes pure typo PR now. Also, I also don't believe that comma is required.

**Comment by hugovk** [comment]
There could be a comma here but I don't think it's essential. Thanks anyway for the PR.
