### ISSUE TITLE
Styling the docs

### ISSUE THREAD

**Issue by ShubhamJagtap2000** [python/cpython#111231]
# Documentation

(A clear and concise description of the issue.)
## Existing docs
![image](https://github.com/python/cpython/assets/63872951/94fec0e1-025f-4461-8627-da8390a3c138)

## Changes made
![image](https://github.com/python/cpython/assets/63872951/ba3e4be1-aca3-42f1-abc7-59720ef7cceb)

Please review and suggest if I can raise a PR. 

Thank you.

**Comment by hugovk** [comment]
Thanks, but I don't think there's anything to do here.

You're viewing the docs via the GitHub UI:

https://github.com/python/cpython/blob/main/Doc/tutorial/appendix.rst#the-interactive-startup-file

Instead, you should be viewing them when built by Sphinx, where the code blocks have syntax highlighting. Also the `sitecustomize` and `usercustomize` text is properly rendered:

https://docs.python.org/3/tutorial/appendix.html#the-interactive-startup-file

<img width="821" alt="image" src="https://github.com/python/cpython/assets/1324225/706ead00-a142-4b2f-9046-13e777c74142">
