### ISSUE TITLE
Mention configparser in tomllib

### ISSUE THREAD

**Issue by opk12** [python/cpython#111267]
# Documentation

1. I made a simple app free of the external dependencies hell.
2. I searched for a built-in INI parser.
3. I found tomllib, but it does not support writing. [The doc](https://docs.python.org/3/library/tomllib.html) points to 3rd-party libs with write support.
4. I searched again and found configparser, which can write to the config file and is in the standard library.

What about mentioning configparser in the tomllib documentation, until tomllib supports writing?

**Comment by sobolevn** [comment]
Sorry, I am confused:

> I searched for a built-in INI parser.
> I found tomllib

But, `tomllib` is not about `ini` parsing. These are two different things: `ini` and `toml`
If you want `toml` library with writting use `tomlkit`

**Comment by ronaldoussoren** [comment]
I agree with @sobolevn, tomllib is not a .INI parser and therefore mentioning configparser in the tomllib documentation is not useful.
