### ISSUE TITLE
`blake2module.c` does not handle errors on module creation 

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111251]
# Bug report

It does it in some parts:
- https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/_blake2/blake2module.c#L88-L90
- https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/_blake2/blake2module.c#L66-L75

But, not in others:

- https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/_blake2/blake2module.c#L98-L101
- https://github.com/python/cpython/blob/81eba7645082a192c027e739b8eb99a94b4c0eec/Modules/_blake2/blake2module.c#L120-L123

This is similar to:
- https://github.com/python/cpython/issues/111233
- https://github.com/python/cpython/issues/111230

### Linked PRs
* gh-111252
* gh-111297
* gh-111298

**Comment by hugovk** [comment]
Backport PRs now merged, thanks!
