### ISSUE TITLE
Crashes and errors in test_embed with PYTHONUOPS=1

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#111339]
For a detailed report see https://github.com/python/cpython/pull/110384#issuecomment-1777657115 (a comment by @brandtbucher on a merged PR by @markshannon ).

I am keeping notes about what I'm learning about this (though Mark said it's his).

---

The issue seems intermittent. I can repro it by running this command repeatedly on my Mac:
```
PYTHONUOPS=1 ./Programs/_testembed test_run_main_loop
```
Usually it passes (printing 5 lines of output); occasionally I get this error:
```
Py_RunMain(): sys.argv=['-c', 'arg2']
Assertion failed: (PyUnicode_CheckExact(ep->me_key)), function unicodekeys_lookup_unicode, file dictobject.c, line 938.
Abort trap: 6
```

---

~I can only repro this with PYTHONUOPS=1, but it never prints any uops debug output. Could it be that the issue is in the code for checking the env var?~

### Linked PRs
* gh-111350
* gh-111430

**Comment by brandtbucher** [comment]
It's intermittent, and it *seems* like it's manifesting itself as refleaks and prematurely freed interned. My hunch is that the linked list is broken somehow, but I've combed through it a bunch of times and haven't found anything wrong.

Weirdly, I've found that I can't reproduce anymore after commenting out the `PyMemberDef` for the `valid` member of `_PyUOpExecutorObject`. Seems like a red herring... maybe it changes the order of allocations or GC traversals somehow (or the bug is unrelated to this PR, and just triggered by the allocation patterns it creates)?

**Comment by brandtbucher** [comment]
If you look at the `ob_type` member of that key, it's a freed byte pattern (`0xDDDDDDDDDDDDDDDD`).

**Comment by gvanrossum** [comment]
Using the VS Code C debugger on macOS to run `_testembed`, I got a traceback. The failing dict lookup is called (indirectly) from `PyUnstable_Optimizer_NewUOpOptimizer()`, via `PyType_Ready()` and `_PyType_CheckConsistency()` and `PyDict_Contains()`.

**Comment by brandtbucher** [comment]
It also goes away for me if I replace `PyUnicode_InternFromString` with `PyUnicode_FromString` in `descr_new` (which is called for each member in the type struct).

**Comment by gvanrossum** [comment]
> It also goes away for me if I replace `PyUnicode_InternFromString` with `PyUnicode_FromString` in `descr_new` (which is called for each member in the `tp_members` array during `PyType_Ready`).

Oh, that points to a new idea. The `valid` key is a "normal" interned string, which presumably is deleted when the interpreter is finalized. The other keys are all standard dunders which are constructed using `_Py_ID()` (e.g. `&_Py_ID(__new__)` in the failing line).

Clearly something ought to clear the `tp_dict` field on finalization, but doesn't, so it survives finalization in this static type. Maybe @ericsnowcurrently has some insight?

**Comment by ericsnowcurrently** [comment]
From gh-111350 (which fixes the crash in this specific case):

> Builtin methods seem more robust than builtin properties.
> This is clearly a workaround, rather than a proper fix, but a proper fix will be a lot of work.

@markshannon, it sounds like you may have insight into the underlying problem.  More info would be valuable.

**Comment by gvanrossum** [comment]
I don't know about the true underlying problem, but I have a hunch that it's easy to repro (e.g. in `_testcapi`):
- Define a very simple static type
- Give it one `PyMemberDef`
- Do the following a few times:
```
Py_Initialize();
PyType_Ready(<our type>);
// Possibly instantiate our type
Py_Finalize();
```
(Function names may differ from actual API, I've not looked it up.)

The problem appears that the static type's `tp_dict` survives the finalization but one of the keys (the name of the `PyMemberDef`) is an interned string and has somehow been invalidated by finalization.

It's quite possible that something needs to clear the `tp_dict` as part of finalization, but that part of the lifecycle code is rather complicated. :-(

**Comment by brandtbucher** [comment]
@markshannon and I think we found the issue this morning.

It looks like we need to add our types to `static_types` in `object.c`. This arranges for calling `_PyStaticType_InitBuiltin` and `_PyStaticType_Dealloc` on them at the right time, which do some "special things" like arranging for `tp_dict` to be stashed on the interpreter, etc. Hopefully there aren't too many other types that we've forgotten to add here... :(

I'm working on a PR now.

**Comment by gvanrossum** [comment]
Great sleuthing (as they say). I figured there was something like that, but I couldn't find it -- that's why I asked for Eric's help.

**Comment by brandtbucher** [comment]
@savannahostrowski is going to work on fixing this. If anybody's blocked on this, please let me know.

**Comment by jiridanek** [comment]
I think I hit this while wanting to use Fedora's `python3-debug` Python binary. I want to use this debug build of Python because it works well with leak sanitizer (does not cause its own leaks, when I use it with `PYTHONMALLOC=malloc_debug PYTHONDEVMODE=1`, so I can be fairly certain that any leaks that do appear are caused by me (in an application that embeds Python interpreter.

```
c_unittests: /builddir/build/BUILD/Python-3.12.0/Objects/dictobject.c:936: unicodekeys_lookup_unicode: Assertion `PyUnicode_CheckExact(ep->me_key)' failed.
Signal: SIGABRT (Aborted)
Fatal Python error: Aborted

Current thread 0x00007ffff05926c0 (most recent call first):
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 1288 in create_module
  File "<frozen importlib._bootstrap>", line 813 in module_from_spec
  File "<frozen importlib._bootstrap>", line 915 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1325 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1354 in _find_and_load
  File "/usr/lib64/python3.12/ctypes/__init__.py", line 8 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 994 in exec_module
  File "<frozen importlib._bootstrap>", line 929 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1325 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1354 in _find_and_load
  File "/home/jdanek/repos/skupper-router/python/skupper_router_internal/dispatch.py", line 40 in <module>
  File "<frozen importlib._bootstrap>", line 488 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 994 in exec_module
  File "<frozen importlib._bootstrap>", line 929 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1325 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1354 in _find_and_load
Signal: SIGABRT (Aborted)
```

Is there a useable workaround to avoid the assert (while still using a debug build of Python3.12) or do I have to wait for Python3.13 with the fixes?

**Comment by jiridanek** [comment]
I did one more check, it really looks like this issue (https://github.com/python/cpython/issues/111339#issuecomment-1780112389)

```
(gdb) p ep->me_key.ob_type
$2 = (PyTypeObject *) 0xdddddddddddddddd
```

While trying to understand this further, I realized there is probably no way to avoid the assert, baring some crazy LD_PRELOAD tricks, possibly. Looks like I'd need a debug build of Python (to get clean asan bill) with asserts disabled (so as not to crash on this).
