### ISSUE TITLE
[Per-Interpreter GIL] Unable to import module _datetime into subinterpreters in 3.12

### ISSUE THREAD

**Issue by jackyk02** [python/cpython#111378]
# Bug report

### Bug description:

Code Example:
```
import _xxsubinterpreters
from _datetime import *
id = _xxsubinterpreters.create()
number = 1000
input_string = f'''import _datetime
print(dt.datetime_CAPI)
'''
_xxsubinterpreters.run_string(id, input_string)
```

Output from `python3.12 example.py`:
```
Traceback (most recent call last):
  File "/mnt/c/Users/jacky/Desktop/simple_multi/src-gen/workers2_compiledwith12/test_custom.py", line 13, in <module>
    _xxsubinterpreters.run_string(id, input_string)
_xxsubinterpreters.RunFailedError: <class 'ImportError'>: module _datetime does not support loading in subinterpreters
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

@ericsnowcurrently @ericvsmith Any help would be much appreciated :)

**Comment by gaogaotiantian** [comment]
I believe `_datetime` is not isolated yet so it's not available in subinterpreters. This might be a dup of #110415 and the previous discusson #71587

**Comment by ericsnowcurrently** [comment]
> I believe `_datetime` is not isolated yet so it's not available in subinterpreters. This might be a dup of #110415 and the previous discusson #71587

Correct.

@jackyk02, if you agree this is a duplicate then please close this issue.  If it is a different problem then please elaborate.  Thanks!

**Comment by erlend-aasland** [comment]
Closing as a duplicate.
