### ISSUE TITLE
`get_type_hints(include_extras=True)` returns double `Union` with `Annotated` 

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111308]
# Bug report

Repro:

```python
>>> def annotated(p: Annotated[Optional[str], ...] = None) -> None: ...
...

>>> get_type_hints(annotated)
{'p': typing.Union[typing.Union[str, NoneType], NoneType], 'return': <class 'NoneType'>}

>>> get_type_hints(annotated, include_extras=True)
{'p': typing.Union[typing_extensions.Annotated[typing.Union[str, NoneType], Ellipsis], NoneType], 'return': <class 'NoneType'>}
```

The first case is finish-ish, the union is not flattened, but it is semantically the same.
We can change it, however.

In the second case, I would expect `p` to be equal to `typing_extensions.Annotated[typing.Union[str, NoneType], Ellipsis]` without the outer `Union`. It complicates things for runtime tools: see https://github.com/litestar-org/litestar/pull/2516

Originally posted by @peterschutt, thank you so much for the report!

What do other think? If you agree that this is a bug, I can solve this :)
CC @AlexWaygood @JelleZijlstra @hauntsaninja

**Comment by JelleZijlstra** [comment]
What version are you testing on? I think we already fixed this some time ago. Here is main:

```
>>> from typing import *
>>> def annotated(p: Annotated[Optional[str], ...] = None) -> None: ...
... 
>>> get_type_hints(annotated)
{'p': typing.Optional[str], 'return': <class 'NoneType'>}
>>> 
>>> get_type_hints(annotated, include_extras=True)
{'p': typing.Annotated[typing.Optional[str], Ellipsis], 'return': <class 'NoneType'>}
```
