### ISSUE TITLE
Raw string literal with backslash at end of string is invalid

### ISSUE THREAD

**Issue by SeTcbPrivilege** [python/cpython#111399]
# Bug report

### Bug description:

It is not possible to specify a raw string literal ending with a backslash. Example:
```python
test = r'\'
```
This results in the following SyntaxError when typed into the interactive console or saved to a file and executed:

```
  File "C:\Users\kristian\Downloads\python-3.12.0-embed-amd64\test_raw_string.py", line 1
    test = r'\'
           ^
SyntaxError: unterminated string literal (detected at line 1)
```

The same error also occurs for double-quoted literals or literals that contain text before the backslash. This affects Windows paths with a trailing backslash, like `r'C:\Windows\'`

When I put two backslashes at the end and try to print the string, it prints both backslashes. The string `r'\''` also works and is evaluated as expected (a single backslash followed by a single quote.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
Not a bug; please see the FAQ on this subject: https://docs.python.org/3/faq/design.html#why-can-t-raw-strings-r-strings-end-with-a-backslash

**Comment by ericvsmith** [comment]
See https://docs.python.org/3/faq/design.html#why-can-t-raw-strings-r-strings-end-with-a-backslash
