### ISSUE TITLE
Typo in math_sumprod_impl()

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#111342]
https://github.com/python/cpython/blob/3f84a19e6291db682fc9a570e7612e80e2ffbbb5/Modules/mathmodule.c#L2835
Obviously, should be ``p_i`` in the last OR operand, c.f. [L2824](https://github.com/python/cpython/blob/3f84a19e6291db682fc9a570e7612e80e2ffbbb5/Modules/mathmodule.c#L2824).

Factored out from #110000.  I think this should be fixed regardless on the fate of that pr.  052d7de867 has also simple test for this if.

### Linked PRs
* gh-111416
* gh-111419

**Comment by rhettinger** [comment]
@skirpichev Care to make a PR with test for this?

**Comment by skirpichev** [comment]
Yep.  #111416
