### ISSUE TITLE
TimeoutError isn't raised async with asyncio.timeout(X)

### ISSUE THREAD

**Issue by maxsimov** [python/cpython#111379]
# Bug report

### Bug description:

```python
import asyncio

async def bar():
    print("In the bar()!")
    try:
        while True:
            await asyncio.sleep(10)
    except asyncio.exceptions.CancelledError:
        print("bar() cancelled!")

async def foo():
    print("In the foo()!")
    task = asyncio.create_task(bar())
    try:
        async with asyncio.timeout(2):
            await task
    except asyncio.exceptions.TimeoutError:
        print("foo() timeout!")

    print("foo() end")
```
Expected:
In the foo()!
In the bar()!
bar() cancelled!
foo() timeout!   <--- never occur

Actual:
In the foo()!
In the bar()!
bar() cancelled!

From what I see that TimeoutError was never raised.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux

**Comment by itamaro** [comment]
Is this behaving differently in 3.12 / 3.11 / 3.10?

According to the docs (https://docs.python.org/3/library/asyncio-task.html#task-cancellation)

> The asyncio components that enable structured concurrency, like asyncio.TaskGroup and asyncio.timeout(), are implemented using cancellation internally and might misbehave if a coroutine swallows asyncio.CancelledError.

**Comment by gvanrossum** [comment]
This is as designed. If you swallow CancelledError you interfere with the timeout handling.
