### ISSUE TITLE
`secrets.choice` function produces too many repeating characters

### ISSUE THREAD

**Issue by TheRealBecks** [python/cpython#111337]
# Bug report

### Bug description:

I want to create secure passwords and I use the `secrets.choice` function with 80 different characters:
`abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:,;+-=*#_<>()[]§~`

I saw that 20-30 % of all passwords with a length of 30 characters have repeating characters what statistically makes no sense: When using 80 characters there's a probability of 1/6400 having two same characters in a row (80^2). When I generate 20 passwords with a length of 10 there will be 200 characters in total, but about 2 or 3 repetitions - that's about factor 60+ higher than expected.

You can define the length of the passwords (like `10`) and the number of passwords (like `20`) as follows for my script:
```
python repetition.py 10 20
```

`repetition.py`:
```python
"""Check for character repetition in secure password generator."""
import secrets
import sys
from functools import reduce


class Password:
    """Define a password."""

    def __init__(self: "Password", length: int) -> None:
        """Initialize Password."""
        self.length: int = length
        selected_symbols: str = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789.:,;+-=*#_<>()[]§~"

        while True:
            self.key: str = "".join(secrets.choice(selected_symbols) for i in range(self.length))
            # Check for duplicate symbols in a row
            if not bool(reduce(lambda x, y: (x is not y) and x and y, self.key)):
                # The password is bad
                print("Repetition:", self.key)
                continue
            # The password is good
            break

    def __str__(self: "Password") -> str:
        """Return Key as str."""
        return f"{self.key}"


if __name__ == "__main__":
    length: int = int(sys.argv[1])
    number_of_keys: int = int(sys.argv[2])

    for _ in range(int(number_of_keys)):
        print(Password(length=length))
    sys.exit(0)
```

Example output:
```
+0#Th,0K;j
4kr:Axvr:i
Ex:WhH:(TH
G:§4KdFRdW
m.GSl#DT=_
tZr4~.u9[Q
1c;d*IsmNz
Repetition: F.=n<)==)T
L0#wYtmLDr
aCHUd=4kI;
=,ry6x:6hw
LS0,X;r2;v
yS)ItUBXPv
+xfYUh:fIQ
9(gHvTQvI0
4N)5~,hcW9
+ezg>:k3e=
Repetition: B§g*B:LA**
hc~uz>g=Qy
YUmxV8PERy
Repetition: e7)#9;vvIR
S)348>F#.A
O(*7Falb(3
```

You can clearly see that 3 out of 20 passwords have repeating characters. I tested different lengths up to 30 characters and it doesn't really change the percentage of 'bad passwords'. With more than 30+ characters there is an increase of repetition, but that's to be expected.

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux

**Comment by decorator-factory** [comment]
> When using 80 characters there's a probability of 1/6400 having two same characters in a row

No, the probability of that is `1/80`. Whatever character you pick first, there's a `1/80` probability the second one will be the same.

The probability that in a 30-character string there will be a repeated characters one after another is `1 - (79/80)**29`, which is approximately 30.5%

**Comment by gaogaotiantian** [comment]
The probability for 10-character is `1 - (79/80) ** 9` which is `10.7%`. So 3 repetition in 20 passwords seems correct. Math is fun isn't it!

**Comment by TheRealBecks** [comment]
Thanks for pointing that out! :smile:
