### ISSUE TITLE
Consider restoring _PyHASH_INF/BITS/MODULUS/IMAG as public

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#111389]
This is used to implement CPython-like hashing of numeric types e.g. [in Sage](https://github.com/sagemath/sage/blob/07a2afd65fb4b0a1c9cbc43ede7d4a18c921a000/src/sage/libs/gmp/pylong.pyx#L35-L52) or [in gmpy2](https://github.com/aleaxit/gmpy/blob/master/src/gmpy2_hash.c).  Actually, the same info is available via ``sys.hash_info``, so I don't see reasons to hide this in Python.h.

See #106320 and #107026.

### Linked PRs
* gh-111418
* gh-119214
* gh-119334
* gh-141236

**Comment by sobolevn** [comment]
CC @vstinner

**Comment by vstinner** [comment]
Python 3.12 has 5 constants implemented as macros:

* `_PyHASH_BITS`
* `_PyHASH_IMAG`
* `_PyHASH_INF`
* `_PyHASH_MODULUS`
* `_PyHASH_MULTIPLIER`

Significant commits related to these constants:

* commit 985ecdcfc29adfc36ce2339acf03f819ad414869: new `Include/pyhash.h` header file
* commit 27cbcd6241d787b5e99c6ed05ec8377051f397aa: in `Include/pyport.h`, use unsigned integer, replace Py_hash_t with Py_uhash_t
* commit 63e6c3222f563cfb156de6e92199e9e35ad5d832: add `_PyHASH_MULTIPLIER` constant
* commit 8035bc5c048ff08f652649754eb8ea769337afa0: add `Py_uhash_t` type, replace `unsigned long` with `size_t`
* commit dc787d2055a7b562b64ca91b8f1af6d49fa39f1c: add `_PyHASH_BITS`, `_PyHASH_IMAG`, `_PyHASH_INF` and `_PyHASH_MODULUS` constants

> the same info is available via sys.hash_info, so I don't see reasons to hide this in Python.h.

Right, it makes sense to make them public. I'm not sure why it was private before.

We can keep them as macros, but maybe we should consider declaring them as variables (using with `dlsym` for example) to make them usable in programming languages and use cases which cannot use macros.

**Comment by vstinner** [comment]
> We can keep them as macros, but maybe we should consider declaring them as variables (using with dlsym for example) to make them usable in programming languages and use cases which cannot use macros.

I created https://github.com/capi-workgroup/api-evolution/issues/37 to discuss that.

**Comment by skirpichev** [comment]
@vstinner, I did a quick reversion in #111418

**Comment by vstinner** [comment]
Should we also add some functions like Py_HashPointer()?

**Comment by vstinner** [comment]
@skirpichev:
> are you about documenting these macroses somewhere (I propose https://docs.python.org/3/library/sys.html#sys.hash_info, where we could mention them in descriptions for different fields) AND about renaming them too (add PyUnstable_ aliases)?

If constants are made public, yes, they must be documented.

I don't know that PyUnstable prefix is needed, these constants seem stable.

**Comment by skirpichev** [comment]
> Should we also add some functions like Py_HashPointer()?

Maybe others (I don't know examples), but not this function.  It's [used](https://github.com/aleaxit/gmpy/blob/125310619ffc3cbf2a88a3b9121ea74b8e295ec3/src/gmpy2_hash.c#L120) currently in the gmpy2, but this could be replaced by ``PyBaseObject_Type.tp_hash``.   And this is a documented replacement:
https://github.com/python/cpython/blob/63acf78d710461919b285213fadc817108fb754e/Doc/library/stdtypes.rst?plain=1#L789-L790

> If constants are made public, yes, they must be documented.

Ok, I'll go with suggested above ``sys.hash_info``.  Let me know if you have in mind a better place to put the docs.

> these constants seem stable

Yep.  But can be removed in any minor release, as ``_PyHASH_NAN``.

**Comment by vstinner** [comment]
https://docs.python.org/dev/library/sys.html is the Python API.

For the C API, I would prefer to create a new page under https://docs.python.org/dev/c-api/ category.

**Comment by skirpichev** [comment]
> Should we also add some functions like Py_HashPointer()?

UPD:

The one drawback with the ``PyBaseObject_Type.tp_hash`` solution above is that there is no guarantee that this function does accept an arbitrary pointer (not only a pointer to some PyObject subclass).  (In gmpy2 we pass mpfr_t: https://github.com/aleaxit/gmpy/blob/e002e2c28994f6c9edd411c1f1e09d0bbbbfca9b/src/gmpy2_hash.c#L122)

On one hand, this is unlikely to be changed.  On another hand, this situation is not documented.  Maybe it should?

**Comment by vstinner** [comment]
I restored _PyHASH constants with PR https://github.com/python/cpython/pull/112115.

**Comment by vstinner** [comment]
> Should we also add some functions like Py_HashPointer()?

I proposed PR https://github.com/python/cpython/pull/112096 to add Py_HashPointer() function.

**Comment by vstinner** [comment]
@skirpichev: Once a public `Py_HashDouble()` function will be added, I will look into this issue: https://github.com/python/cpython/issues/111545

**Comment by vstinner** [comment]
> This is used to implement CPython-like hashing of numeric types e.g. in Sage or in gmpy2.

You can now propose changes for these projects to use the public names :-) I added the constants to pythoncapi-compat: https://github.com/python/pythoncapi-compat/commit/7539c7f82c0eda744ac455f0a15bf41432f2b02c
