### ISSUE TITLE
`itertools.rst` says that `start` is a required argument for `count`, while it is not

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111343]
# Bug report

<img width="810" alt="Снимок экрана 2023-10-26 в 10 04 40" src="https://github.com/python/cpython/assets/4660275/ae236f93-f637-4861-8ac0-630471097b84">

However,

```python
>>> import itertools
>>> itertools.count()
count(0)
>>> next(itertools.count())
0
```

I propose that we use `[start, step]` instead.

### Linked PRs
* gh-111344
* gh-111385

**Comment by sobolevn** [comment]
`[start, step]` might also look like a list for some users 🤔

**Comment by pochmann** [comment]
Doesn't `[start, step]` mean you must provide neither or both but not only one? For example [`bytes`](https://docs.python.org/3.10/library/functions.html#func-bytes) used to be documented as `class bytes([source[, encoding[, errors]]])` to allow providing only some of them.

**Comment by zware** [comment]
`[start[, step]]` implies that `step` can only be specified in conjunction with `start`, which also isn't true.

**Comment by pochmann** [comment]
> `[start[, step]]` implies that `step` can only be specified in conjunction with `start`, which also isn't true.

@sobolevn Is that wrong?

**Comment by zware** [comment]
@rhettinger, I don't think this is complete:

1) Behavior is the same between 3.12 and 3.11, any documentation change here should be backported to at least 3.11
2) As stated above, `[start[, step]]` implies that `step` can only be specified in conjunction with `start`, which also isn't true.  If you really want to stick with brackets you could try something like `[start[, ]][step]`, but really that's just getting ridiculous.  `start=0, step=1` is accurate and unambiguous.

**Comment by rhettinger** [comment]
My personal opinion is that this is over nitpicking what is supposed to be an overview table with a hotlink to more details.  No actual user has ever been confused by this.  I accepted the PR mainly to satisty sobolevn and this isn't worth backporting or further mangling the table,
