### ISSUE TITLE
Support configuring -X frozen_modules=on|off using an environment variable.

### ISSUE THREAD

**Issue by yilei** [python/cpython#111374]
# Feature or enhancement

### Proposal:

Most of the `-X` options (https://docs.python.org/3/using/cmdline.html#cmdoption-X) can be configured via an environment variable, but not `-X frozen_modules`.

This makes it harder for environments that you don't have the control over the flags passed to the Python interpreter.

https://github.com/python/cpython/issues/98697 also includes a use case for [crossenv](https://github.com/benfogle/crossenv), but the issue was closed because it was not in time for Python 3.11.

I'm proposing a ~~`PYTHONFROZENMODULES`~~ `PYTHON_FROZEN_MODULES` environment variable to be added for Python 3.13, which has the equivalent meaning of using `-X frozen_modules`.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://github.com/python/cpython/issues/98697 is the same request, but closed due to not in time for Python 3.11.

### Linked PRs
* gh-111411

**Comment by yilei** [comment]
Btw, I'll also send a PR, assuming this will be accepted.

**Comment by hugovk** [comment]
> I'm proposing a `PYTHONFROZENMODULES` environment variable to be added for Python 3.13, which has the equivalent meaning of using `-X frozen_modules`.

I'll let others review the PR, but if we do this, let's add underscores to the name:

* `PYTHON_FROZEN_MODULES` 

See https://discuss.python.org/t/change-environment-variable-style/35180?u=hugovk

**Comment by hugovk** [comment]
Thank you for your contribution!
