### ISSUE TITLE
remove hacks in genobject.c

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#111354]
Refactor Objects/genobject.c to get rid of these hacks/issues:

- ~~`gen_close` accesses `instr_ptr - 1`~~
- `_PyGen_yf` peeks into the execution stack
- Comparisons with enum values
- ``result`` arg reused in ``gen_send_ex2`` for two different purposes (one of which is not the result)

### Linked PRs
* gh-111365
* gh-111368
* gh-111459
* gh-111648
* gh-111708

**Comment by hugovk** [comment]
Closing as it looks like the relevant PRs have been merged, please re-open if still needed.
