### ISSUE TITLE
np.nan != float("nan), datatype drifts with pickle

### ISSUE THREAD

**Issue by gatorwatt** [python/cpython#111333]
# Bug report

### Bug description:

Just made note of this issue to a IEEE 754 committee member, wanted to call to you attention:

Have noticed a distinction in NaN representations in python that might be a good idea for alignment. Right now the generic version of python floats has both (float("nan") == float("nan")) == False and (float("nan") is float("nan")) == False, while the numpy version of np.nan is different such that (np.nan == np.nan) == False and (np.nan is np.nan) == True. The distinction is material because it allows np.nan to be used as a regular expression in settings like serving as a dictionary key which when attempted with float("nan") leaves a dictionary value inaccessible by address. The issue becomes more important when you consider that for serializing libraries like pickle a dumped np.nan entry when loaded will experience datatype drift to float("nan") which could lead to hard to spot bugs in all kinds of scenarios I expect.

### CPython versions tested on:

3.8

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
I'm not sure what the bug is that you are reporting. It's true that `pickle.loads(pickle.dumps(numpy.nan)) is not numpy.nan`, but numpy is a third-party project, not something that CPython controls.

**Comment by pochmann** [comment]
What do you mean with "datatype drift"? `numpy.nan` is an ordinary Python `float` and pickle doesn't change that. It's just like Python's own `math.nan`.

**Comment by gatorwatt** [comment]
This might be an issue for numpy instead of python, but it had a lot of parts and as pickle is released through python distribution at a minimum I thought you guys should be made aware.

**Comment by gatorwatt** [comment]
> What do you mean with "datatype drift"? `numpy.nan` is an ordinary Python `float` and pickle doesn't change that. It's just like Python's own `math.nan`.

I am referring to how prior to using pickle an entry of type x=np.nan has the property x is x == True and after using pickle it drifts to having the property x is X == False.

**Comment by gaogaotiantian** [comment]
First of all, `numpy.nan` is `float`, not a special type.

```python
>>> type(numpy.nan)
<class 'float'>
```

`x is x` will always be `True`. `float("nan") is float("nan")` is not `x is x`. If you do `x = float("nan")`, you'll find `x is x == True`.

I think you just have a misunderstanding of Python objects. When you do `float("nan")`, you create a new float object, and the two newly created objects are two distinct objects.

When you pickle & unpickle, you'll also create new objects - you have no gurantee `x is unpickle(pickle(x))`, or `unpickle(pickle(x)) is unpickle(pickle(x))`. It has nothing to do with `numpy.nan` or `math.nan`.

However, if you do `y is unpickle(pickle(x))`, `y is y` will always hold. In your case, if you do `x = unpickle(pickle(numpy.nan))`, `x is x` will be `True`.

**Comment by pochmann** [comment]
> If you do `x = float("nan")`, you'll find `x is x == True`.

I think you misspoke (`x is x == True` evaluates to `False`).

**Comment by gaogaotiantian** [comment]
> > If you do `x = float("nan")`, you'll find `x is x == True`.
> 
> I think you misspoke (`x is x == True` evaluates to `False`).

Yeah, it's not the best way to write it. I'll change it.

**Comment by terryjreedy** [comment]
There is nothing to change here in CPython.

**Comment by gatorwatt** [comment]
As a clarification, and part of the reason this is a hard to spot bug, is that [gaogaotiantian](https://github.com/gaogaotiantian)'s comment is correct, and that after assigning to a variable x = float("nan") then x is x evalutates as True. The scope where this fails is when x is used as a key in a dictionary.

```
a = float("nan")
a is a # True

import numpy as np
b = np.nan
b is b # True

a_dict = {a : "value1",
                b : "value2"}

a_dict[np.nan] # accesses "value2"

a_dict[float("nan")] # returns halt bug

# after pickle dump and load of a_dict

import pickle
with open('filename.pickle', 'wb') as handle:
  pickle.dump(a_dict, handle, protocol=pickle.HIGHEST_PROTOCOL)

# reset notebook (Esc 00)
import pickle
import numpy as np

with open('filename.pickle', 'rb') as handle:
  a_dict = pickle.load(handle)

a_dict[np.nan] # halt bug, suggesting some form of datatype drift
```

**Comment by terryjreedy** [comment]
@gatorwatt  One can ask 'Is this a bug' on help forums, such as https://discuss.python.org/c/users/7

**Comment by gaogaotiantian** [comment]
> As a clarification, and part of the reason this is a hard to spot bug, is that [gaogaotiantian](https://github.com/gaogaotiantian)'s comment is correct, and that after assigning to a variable x = float("nan") then x is x evalutates as True. The scope where this fails is when x is used as a key in a dictionary.

You should NOT use `numpy.nan` as a key to a dict, especially if you want some level of persistance.

Like I said, it has nothing to do with `numpy.nan`, this behavior is just because `__hash__` and `__eq__` functions of `nan` does not support dict. You can reproduce it with any vanilla user-defined object.

Short answer would be - don't do this. It's a bad practice to use objects that do not have good `__eq__` and `__hash__` behaviors as a dict key. This is slightly special just because `nan` has a different equal behavior than `float` - which is on purpose.

**Comment by gaogaotiantian** [comment]
> > As a clarification, and part of the reason this is a hard to spot bug, is that [gaogaotiantian](https://github.com/gaogaotiantian)'s comment is correct, and that after assigning to a variable x = float("nan") then x is x evalutates as True. The scope where this fails is when x is used as a key in a dictionary.
> 
> You should NOT use `numpy.nan` as a key to a dict, especially if you want some level of persistance.
> 
> Like I said, it has nothing to do with `numpy.nan`, this behavior is just because `__hash__` and `__eq__` functions of `nan` does not support dict. You can reproduce it with any vanilla user-defined object.
> 
> Short answer would be - don't do this. It's a bad practice to use objects that do not have good `__eq__` and `__hash__` behaviors as a dict key. This is slightly special just because `nan` has a different equal behavior than other `float` objects - which is on purpose.
