### ISSUE TITLE
The negation sign of a number is a lower-priority operation than raising to a degree (Python 3.12)

### ISSUE THREAD

**Issue by Omegon226** [python/cpython#111398]
# Bug report

### Bug description:

Recently found a mistake. If we take a number with a negative sign (e.g. -0.333) and then raise it to an even degree (2, 4, etc.), we get a negative number, while we should get a positive number!  The problem is solved if we wrap this number in brackets, which indicates a prioritisation problem.

```python
print(-0.333 ** 2)
>>> -0.11088900000000002

print(0.333 ** 2)
>>> 0.11088900000000002

print((-0.333) ** 2)
>>> 0.11088900000000002
```

If we do the calculations with variables, there is no such problem

```python
neg_num = -0.333
pos_num = 0.333

print(neg_num  ** 2)
>>> 0.11088900000000002

print(pos_num  ** 2)
>>> 0.11088900000000002

print((neg_num) ** 2)
>>> 0.11088900000000002
```

This problem has been occurring in earlier versions (3.10)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
This isn't a bug.

`**` has a higher precedence than `-`, so the first one is really doing `-(0.333 ** 2)`.

See https://docs.python.org/3/reference/expressions.html#operator-precedence
