### ISSUE TITLE
What's new in Python 3.13: move importlib.resources removals under the `Removed` section

### ISSUE THREAD

**Issue by befeleme** [python/cpython#111301]
# Documentation
There is some obsolete information in the section [Pending Removal in Future Versions](https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-future-versions) of the What's new in Python 3.13 document. 

1. There are listed:

> [importlib.resources](https://docs.python.org/3.13/library/importlib.resources.html#module-importlib.resources) deprecated methods:
>     contents()
>     is_resource()
>     open_binary()
>     open_text()
>     path()
>     read_binary()
>     read_text()

These were already removed from Python 3.13.

2. There is listed: 

> [importlib.resources](https://docs.python.org/3.13/library/importlib.resources.html#module-importlib.resources): First parameter to files is renamed to ‘anchor’.

This has already changed in Python 3.12

### Linked PRs
* gh-111509
* gh-111512
* gh-111534
* gh-111630
* gh-114187

**Comment by hugovk** [comment]
Thanks for the report!

1. 

These were indeed removed in 3.13 in PR issue https://github.com/python/cpython/issues/106531 / PR https://github.com/python/cpython/pull/106532.

Would you like to open a PR to move these out of "Pending Removal" and into the "Removed" section?

https://docs.python.org/3.13/whatsnew/3.13.html#removed

2. 

Yep, renamed in issue https://github.com/python/cpython/issues/97930 / PR https://github.com/python/cpython/pull/100598.

Would you like to open another PR to remove that bit from the 3.13 What's New and add it to the 3.12 one? We can backport this PR to 3.12.

Style note: parameters should be styled in italics (*anchor*) not quoted ("anchor"). It would be good to update those at the same time.

**Comment by befeleme** [comment]
Hi, yes, I'll send the PRs for that.

**Comment by hugovk** [comment]
Thanks, all merged!
