### ISSUE TITLE
Issues regarding German Umlaute when replacing in strings.

### ISSUE THREAD

**Issue by basti95** [python/cpython#111302]
# Bug report

### Bug description:

When replacing a value, I encountered some bug regarding the resulting encoding within files:

```python


def replace_text(value):
        value = value.replace(('Zeitschriften', 'Konferenzbände')
    return value

with open('source.txt') as file_content:
        lines = file_content.readlines}
with open(output_path, 'w+') as output:
        for line in lines:
            output.write(replace_text(line)) + '"\n')
```
Using Print, all Results are shown correctly, however, if I open the files with something like the Windows Editor

The code produces file content like:
` Wir empfehlen unseren Leser/innen, sich fÃ¼r die Benachrichtigung bei neuen Veröffentlichungen dieser Zeitschrift einzutragen. `

The expected file content would look like:
` Wir empfehlen unseren Leser/innen, sich für die Benachrichtigung bei neuen Veröffentlichungen dieser Zeitschrift einzutragen. `

The problem does not occur, if I only replace with values that does not include German Umlaute like 'ä' or 'ü'. 
It can be prevented by explicitly stating encoding='utf-8' while reading 'source.txt' (which shouldn't be necessary, since it is the default as far as I know).

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by basti95** [comment]
edited the Issue due to some own testing and fixing an error in my second iteration

**Comment by pochmann** [comment]
Your code doesn't even run at all, has four (!) syntax errors.
