### ISSUE TITLE
text_encoding() is missing from io.__all__

### ISSUE THREAD

**Issue by ntessore** [python/cpython#111356]
# Bug report

### Bug description:

The public [`io.text_encoding()`](https://docs.python.org/3/library/io.html?highlight=text_encoding#io.text_encoding) function is missing from `io.__all__`.

```python
>>> import io
>>> "text_encoding" in io.__all___
False
```

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-111370
* gh-111935
* gh-111936

**Comment by hugovk** [comment]
Fixed and backported, thanks for the issue!
