### ISSUE TITLE
Mention that unicodedata is updated for Unicode 15.1.0 in What's new in Python 3.13

### ISSUE THREAD

**Issue by befeleme** [python/cpython#111361]
# Documentation

In Python 3.13 `unicodedata` is updated for Unicode 15.1.0 (https://github.com/python/cpython/commit/def828995a35a289c9f03500903b5917df93465f).

It would be nice to have this explicitly mentioned on the [What's new in Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html) page.

### Linked PRs
* gh-112031

**Comment by Lincoln-developer** [comment]
Hey, I would love to work on this,

**Comment by hugovk** [comment]
@Lincoln-developer That would be great, thank you!
