### ISSUE TITLE
Why is the Python standard GUI (Tkinter) left in the stone age?

### ISSUE THREAD

**Issue by moefear85** [python/cpython#111394]
# Feature or enhancement

### Proposal:

Sorry for the title, it's to catch attention to the most pressing issue in 2023, because it's 2023. Is python seen as too weak such that its GUI (perhaps the most important part of any library), has to be written in another scripting language? It makes it helplessly impossible to extend or add features because one has to learn a new language to do so.

Tkinter lacks antialiasing. Even if the fonts are actually anti-aliased on modern ubuntu OSs, it doesn't look that way, and certainly not the other widgets. The canvas is definately and clearly not anti-aliased. Is this a remnant of the Linux Graphics Crisis of the last decade? I have yet to find an explanation as to what the most basic/standard hardware accelerated graphics library on linux is that enables one to draw anything/anywhere on the screen (specifically what wayland/X use to do the drawing, specifically anti-aliased text and vectors/primitives such as lines, rectangles, circles, etc), so it could become clear to me how to port Tkinter alltogether. All I find when researching the graphics architecture on linux are fat arrows pointing back on forth between various boxes labelled DRI/DRM, wayland, X, GUI, and so on. No concrete references to an API, besides references to OpenGL. I doubt wayland/X are actually coded in OpenGL, and that they draw by sending vertices to the graphics card. That's not what I understand under vector graphics.

Moreover tkinter's API is outdated. Anything modern becomes extremely bloated and slow like Kivy (which I didn't even manage to install, ie it doesn't work out of the box, which is what one expects for a standard library). Why can't python have a modern, yet simple and fast API that optionally separates the layout from the code, but retains the ability to directly instantiate objects and have them displayed and simply attach event handlers, like with guizero etc, with variables that update in realtime without having to extra instantiate ones manually? I can create wrappers for that, but that only handles some of the symptoms superficially.

I really want to improve and contribute something to tkinter, but it seems so helplessly convoluted and patched together and full of legacy, that i just don't know where to begin. The library really should be rewritten, including the API, but while providing a legacy API for backwards compatibility, in such a way that simply replacing the imported tkinter library paths would change how the rendering is done, without requiring any change to legacy tkinter code, while also exposing a modern API. There are many GUI libraries available to python, but all have one thing in common: they are each a different standard/API that one has to learn with none of them being the major winner or have any sense of being standard, while also being simple and fast, while also being fully anti-aliased, while also being fully cross-platform (mac/android/win/lin), and being maintained, and without introducing unreliable/complicated dependencies that reduce the likelihood of widespread successful/easy installing. Gtk/qt isn't straightforward to install on windows.

In python, there is a function to do everything and its dog. Yet the community seems to lack the resources to get a fundamental cornerstone library straight. I've been waiting and waiting hoping the issue would resolve itself at some point. I guess I'll have to DIM. I'll share any solution, but don't intend to jump through hoops to get it integrated into the standard library.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by terryjreedy** [comment]
This tracker is for concrete action items.  This posting does not present such.  Hence the closing.

Discussions belong on https://discuss.python.org/ (or elsewhere).  There are separate channels for questions (help) and proposals (ideas).  Before posting on either, please read the introduction section of the [tkinter doc](https://docs.python.org/3/library/tkinter.html) and the first section, Architecture.   You do not seem aware, for instance, that tkinter has nothing to do with how text and widgets are displayed.

An incompatible second interface to the tcl/tk GUI toolkit would have to be released on pypi.org.
