### ISSUE TITLE
Crash when Py_FinalizeEx() call in Python 3.11.1

### ISSUE THREAD

**Issue by ngangomsamananda** [python/cpython#111479]
# Crash report

### What happened?

We use Python on our application. when we upgraded Python from 3.9.6 to 3.11.1 and the application got occasionally crash at  Py_FinalizeEx() when we try to close the application. Can anyone help me to understand the causes of the crash? Is there a way to avoid the crash? I am out of ideas, and it's hard to reproduce the issue. The call stacks are attached:
![image](https://github.com/python/cpython/assets/134058205/f2313d4d-03a1-4aec-ab55-97bb8a6abfc1)

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by vstinner** [comment]
Without any way to reproducer, this issue cannot be fixed and is useless.

**Comment by ngangomsamananda** [comment]
@vstinner So, If we see the callstacks `_Py_FatalRefcountErrorFunc` gets call https://github.com/python/cpython/blob/230e8e924dbafe093fd1cc7b6c510dc0b9ec0caf/Python/pylifecycle.c#L3005 and it looks like it's a reference counting issue.
Then calls goes to the below lines https://github.com/python/cpython/blob/37e4e20eaa8f27ada926d49e5971fecf0477ad26/Python/pylifecycle.c#L2968
https://github.com/python/cpython/blob/37e4e20eaa8f27ada926d49e5971fecf0477ad26/Python/pylifecycle.c#L2869
https://github.com/python/cpython/blob/37e4e20eaa8f27ada926d49e5971fecf0477ad26/Python/pylifecycle.c#L2760
It goes to `abort()` and the crash occurred.
Is there a way that can handle the crash when we get a reference counting issues?

**Comment by vstinner** [comment]
It's likely a refcount bug in a C extension used by your code. Run your code with ``python -X dev myapp.py`` to get the traceback where the crash occurs and the list of 3rd party C extensions.

>  Is there a way that can handle and avoid the crash when we get a reference counting issues?

Fix bugs in your C extensions, or exit without attempting to clean anything: `os._exit(0)`.
