### ISSUE TITLE
datetime.strptime fails with circular import in calendar.py

### ISSUE THREAD

**Issue by rjeffman** [python/cpython#111425]
# Bug report

### Bug description:

When executing a source file named `calendar.py` with the content

```python
from datetime import datetime

datetime.strptime("2023", "%Y")
```

Python interpreter fails due to circular import:

```
Traceback (most recent call last):
  File "/home/rjeffman/Developer/rafaeljeffman.com/calendar.py", line 3, in <module>
    datetime.strptime("2023", "%Y")
  File "/usr/lib64/python3.11/_strptime.py", line 15, in <module>
    import calendar
  File "/home/rjeffman/Developer/rafaeljeffman.com/calendar.py", line 3, in <module>
    datetime.strptime("2023", "%Y")
AttributeError: partially initialized module '_strptime' has no attribute '_strptime_datetime' (most likely due to a circular import)
```

Internal imports should make no assumption on user's filenames.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
That's not a bug. There's no way to import internal `calendar.py`, rename your file and everything will work.
If you have an interest how imports works, you can read documentation about `importlib` and related things.
FYI: This is a CPython bug tracker, so, please, before an openning an issue, ask your question on https://discuss.python.org/c/users/7.
