### ISSUE TITLE
Restore ncurses widechar support on macOS

### ISSUE THREAD

**Issue by sorcio** [python/cpython#111460]
# Bug report

### Bug description:

Python 3.12 dropped ncurses wide char support on macOS, so for example `curses.get_wch()` is not available anymore.

I believe this was an unintended consequence of https://github.com/python/cpython/pull/94452, because the change is not documented anywhere. After that PR, HAVE_NCURSESW is never defined on Darwin. It looks like this bit of logic was not ported from setup.py to configure.ac:

https://github.com/python/cpython/blob/ec5e253556875640b1ac514e85c545346ac3f1e0/setup.py#L1121-L1124

In fact, wide char support is always available when using Apple-provided ncurses, and it used to work correctly in the 3.11 builds that I tested.

@tiran can you confirm that this was unintended?

cc @sobolevn who interpreted this as an intended change in https://github.com/python/typeshed/pull/10808. 

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-111878
* gh-112034

**Comment by ned-deily** [comment]
@erlend-aasland

**Comment by erlend-aasland** [comment]
Yes, this is probably an unintended side effect. I can look into it tomorrow.

(cc. @corona10, if you are interested)

**Comment by corona10** [comment]
Yeah I will take a look too

**Comment by erlend-aasland** [comment]
Can this be closed?

**Comment by erlend-aasland** [comment]
> @erlend-aasland if there is no need to test this, we're done here.

There's always a need for accompanying tests.

**Comment by ronaldoussoren** [comment]
@erlend-aasland : What kind of tests do you want to see here?  AFAIK we generally don't test if expected platform features are present, other than some tests I've added when working on the Universal 2 port to ensure that weak linking works as expected.

**Comment by erlend-aasland** [comment]
I did not have anything in particular in mind. If there is no particular need, let's just close this.
