### ISSUE TITLE
The code generated for the interpreter(s) is too fragile

### ISSUE THREAD

**Issue by markshannon** [python/cpython#111485]
Changing the name of an instruction, or slight changes in cache size can cause the generated code to be incorrect in odd ways.
This is a result of there being too many special cases and undocumented assumptions built in to the code generator.

This was a natural result of getting the thing working and was, until now, acceptable technical debt.
However, as we want to generate abstract interpreters, a new combiner tier-1/tier-2 interpreter and possible tail-calling interprtet/JIT compiler pair, things are too fragile.

We need to:
* Reduce the number of ad-hoc special cases in the tools to zero.
* Minimize and very clearly specify any special markers and variables we use in `bytecodes.c`
* Clarify the in-memory state and transitions of execution.
* Document the representation of that state in the various tiers and components.

 

### Linked PRs
* gh-111486
* gh-111540
* gh-111547
* gh-111561
* gh-111619
* gh-111697
* gh-111812
* gh-112299
* gh-112315
* gh-112831
* gh-112877
* gh-112968
* gh-113101
* gh-113155
* gh-113169
* gh-113252
* gh-113287
* gh-113319
* gh-113321
* gh-113324
* gh-113394

**Comment by neonene** [comment]
Maybe `INSTRUMENTED_RESUME` has an unintentional edit (mixed replacement) since d27acd4461ee603bcf6f4a81ca6afccc9fc87331?

https://github.com/python/cpython/blob/d27acd4461ee603bcf6f4a81ca6afccc9fc87331/Python/bytecodes.c#L187-L189

Previously, line 189 was `next_instr = frame->instr_ptr;`

**Comment by gvanrossum** [comment]
@markshannon ^^

**Comment by markshannon** [comment]
Indeed. That doesn't look right.

**Comment by gvanrossum** [comment]
@markshannon Can you fix this? https://github.com/python/cpython/issues/111485#issuecomment-1820941392

**Comment by gvanrossum** [comment]
@markshannon Was this part ever fixed? https://github.com/python/cpython/issues/111485#issuecomment-1820941392
