### ISSUE TITLE
time.clock_gettime_ns() is too slow

### ISSUE THREAD

**Issue by socketpair** [python/cpython#111482]
# Feature or enhancement

### Proposal:

Actually, this is a performance bug. Not a feature/enhancement.
`clock_gettime_ns()` does not use floating point operations and should be faster than old `gettimeofday()`. Unfotunately in Python it's not so. Checked in Linux X86_64 kernel 6.5.7, CPython 3.11.6

```python
In [11]: timeit time.clock_gettime_ns(0)  # CLOCK_REALTIME
55.4 ns ± 1.22 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [12]: timeit time.clock_gettime_ns(5) # CLOCK_REALTIME_COARSE
45 ns ± 0.324 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [13]: timeit time.time()
36.7 ns ± 0.953 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-111641
* gh-112170

**Comment by pochmann** [comment]
"too slow" for what?

**Comment by wrongnull** [comment]
Internally, ```clock_gettime_ns``` makes different system calls compared to the ```time.time``` function. As a result, it will have to perform more checks on the return values. I bet that's the main thing.

**Comment by socketpair** [comment]
@pochmann too slow comparing to time.time() = gettimeofday(). For example, CLOCK_REALTIME_COARSE by definition should be faster (but coarse). In fact, it's not faster in Python. I did a glimpse on the implementation. For reasons that I don't understand there are many useless wrappers around simple things.

Why not to do this: 

```C
static PyObject *
time_clock_gettime_ns(PyObject *self, PyObject *args)
{
    int clk_id;
    if (!PyArg_ParseTuple(args, "i:clock_gettime", &clk_id)) {
        return NULL;
    }

    struct timespec ts;
    if (clock_gettime((clockid_t)clk_id, &ts)) {
        PyErr_SetFromErrno(PyExc_OSError);
        return NULL;
    }

    return PyLong_FromLongLong((unsigned long long)ts.tv_sec + ((unsigned long long)ts.tv_nsec) * 1000000000ull);
}
```

I beat, it will be faster than current implementation, although I did not check yet.

**Comment by vstinner** [comment]
I'm not sure what this issue is about. If you want to propose a change, go ahead.

**Comment by socketpair** [comment]
I have checked, my optimizations give nothing, so closing the issue :(

**Comment by vstinner** [comment]
I reopen the issue: I wrote PR #111641 which makes clock_gettime() and clock_gettime_ns() up to 2x faster by using a faster calling convention (METH_VARARGS => METH_O).

**Comment by hugovk** [comment]
https://github.com/python/cpython/pull/111641 was merged. Does it need backporting? If not, let's close this issue.

**Comment by vstinner** [comment]
I dislike backporting optimizations. Better performance is not worth it compared to the risk of regression. I close the issue. Thanks @socketpair for the bug report.
