### ISSUE TITLE
Confusing `SyntaxError` message for `x for x if range(1)`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111488]
# Bug report

Today I made a typo: instead of `in` I wrote `if`.
I was quite interested to see the error message:

```python
>>> [x for x if range(1)]
  File "<stdin>", line 1
    [x for x if range(1)]
           ^^^^^^^^^^^^^
SyntaxError: expected 'else' after 'if' expression
```

I don't think that this error message is correct. Why? Because even if we follow the rabbit hole and use `else`, we won't be ever correct:

```python
>>> [x for (x if range(1) else y) in range(1)]
  File "<stdin>", line 1
    [x for (x if range(1) else y) in range(1)]
            ^^^^^^^^^^^^^^^^^^^^
SyntaxError: cannot assign to conditional expression
```

So, maybe we should change it to be something like:

```python
>>> [x for x if range(1)]
  File "<stdin>", line 1
    [x for x if range(1)]
             ^^
SyntaxError: expected 'in', got 'if'
```

Suggestions about wording are welcome :)

If others agree, I would like to work on this.

### Linked PRs
* gh-113656

**Comment by sobolevn** [comment]
cc @pablogsal @lysnikolaou

**Comment by pablogsal** [comment]
Thanks for the issue! Will take a bite at this today at night

**Comment by skirpichev** [comment]
This works for me:
```diff
diff --git a/Grammar/python.gram b/Grammar/python.gram
index ec964d6783..98270fe77f 100644
--- a/Grammar/python.gram
+++ b/Grammar/python.gram
@@ -1282,6 +1282,8 @@ invalid_with_item:
         RAISE_SYNTAX_ERROR_INVALID_TARGET(STAR_TARGETS, a) }
 
 invalid_for_target:
+    | 'async'? 'for' star_targets !'in' {
+        RAISE_SYNTAX_ERROR("'in' expected after for-loop variables") }
     | 'async'? 'for' a=star_expressions {
         RAISE_SYNTAX_ERROR_INVALID_TARGET(FOR_TARGETS, a) }
```
```pycon
Python 3.13.0a1+ (heads/main-dirty:4a929d432b, Oct 31 2023, 15:32:48) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> [x for x if range(1)]
  File "<stdin>", line 1
    [x for x if range(1)]
             ^^
SyntaxError: 'in' expected after for-loop variables
```

Let me know if this worth a PR.

**Comment by pablogsal** [comment]
This sort of works, but it breaks other error messages, for instance this one:

```
 for a, b, (c + 1, d()): pass
```

That used to be: `SyntaxError: cannot assign to expression` but now will show `'in' expected after for-loop variables` which is not correct. What is worse, adding `in` produces this:

```
>>> for a, b, (c + 1, d()) in P:
  File "<stdin>", line 1
    for a, b, (c + 1, d()) in P:
                           ^^
SyntaxError: 'in' expected after for-loop variables
```

which is obviously incorrect

**Comment by skirpichev** [comment]
Yep, wrong place, this should be restricted to comprehensions.  ``test_syntax.py`` pass with this alternative at the end of  ``for_if_clause[comprehension_ty]``.

**Comment by pablogsal** [comment]
> this should be restricted to comprehensions.

You have the same problem in list comprehensions, is just that there are no tests for that:

```
>>> [x for x() in a]
  File "<stdin>", line 1
    [x for x() in a]
               ^^
SyntaxError: 'in' expected after for-loop variables
```

this currently shows:

```
>>> [x for x() in a]
  File "<stdin>", line 1
    [x for x() in a]
           ^^^
SyntaxError: cannot assign to function call
```

**Comment by pablogsal** [comment]
@skirpichev If you want a quick PR, you can add tests that cover this case for list/set/dict comprehensions in `test_syntax`

**Comment by grigoriev-semyon** [comment]
I understood why this doesn't work: because `star_targets` crashes on the first incorrect "character" and then `!in` works, which is successful because the next token is really not `in`

But I don't know how to accurately describe the expression(which may be incorrect by star_targets view) between `for` and `in`. Can I get some hint?
