### ISSUE TITLE
Useless code block in math.trunc() ?

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#111417]
# Bug report

### Bug description:

The math.trunc function has:
https://github.com/python/cpython/blob/f013b475047b2e9d377feda9f2e16e5cdef824d7/Modules/mathmodule.c#L2073-L2076
c.f. [math.ceil](https://github.com/python/cpython/blob/f013b475047b2e9d377feda9f2e16e5cdef824d7/Modules/mathmodule.c#L1124-L1148) or [math.floor](https://github.com/python/cpython/blob/f013b475047b2e9d377feda9f2e16e5cdef824d7/Modules/mathmodule.c#L1193-L1217).

This seems to be a history artifact: the function was introduced in https://github.com/python/cpython/commit/400adb030a78c3fcb1eb458b25c990449fbf3c93 as a moved __builtins__.trunc(), while math.ceil/floor were here from the initial revision.

I think it's safe to remove mentioned block.

PS: Issue opened per @serhiy-storchaka suggestion in #110000.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-111454

**Comment by Jason-Y-Z** [comment]
Created a small PR to remove the unused code block - https://github.com/python/cpython/pull/111454

**Comment by serhiy-storchaka** [comment]
I suggested @skirpichev to open a separate issue for discussion and reference. Previously this change was hidden in a pile of unrelated changes.

Now I think that it is safe. This check is immediately followed by `_PyObject_LookupSpecial()` which calls `_PyType_Lookup()` which, after looking in the type cache, calls `find_name_in_mro()` which looks up `tp_mro`, and, if it has not yet been set, make the type ready.

I think that a similar code in the builtin `round()` can be removed as well. Other uses of `_PyType_IsReady()` and `PyType_Ready()` look more justified.

**Comment by skirpichev** [comment]
@serhiy-storchaka, in the end, it was your commit, that makes additional ``PyType_Ready()`` (since 15d3d04547) call here useless: 8ef34600c7d.

@Jason-Y-Z, I think you could reference that commit in you commit message.  And remove [similar code](https://github.com/python/cpython/blob/11e83488c5a4a6e75a4f363a2e1a45574fd53573/Python/bltinmodule.c#L2371-L2374) in ``round()``, of course.
