### ISSUE TITLE
Produces different outputs 

### ISSUE THREAD

**Issue by Nchinmayeii** [python/cpython#111401]
### Bug description:
```python
name=["chine",'shin','thippe','khushei','goggei','shiv']
new_name=[item for item in name if ('e' or 'i') in item]
print(new_name)

name=['chine','shin','thippe','khushei','goggei','shiv']
new=[]
for item in name:
    if 'e' in item :
        if 'i' in item:
            new.append(item)
print(new)
```
### CPython versions tested on:
3.11

### Operating systems tested on:

Windows

**Comment by notatallshaw** [comment]
This isn't a bug in Python, you should reach out to your peers or places on the Internet that provide help for Python such as  such as [Python Discuss help category](https://discuss.python.org/c/users/7), [/r/learnpython on reddit](https://www.reddit.com/r/learnpython), [Python Discord's #help-* channels](https://discord.gg/python), [#python on Libera.chat](https://web.libera.chat/#python) ([IRC](https://workaround.org/getting-help-on-irc/)), [python-list](https://mail.python.org/mailman/listinfo/python-list) or [python-tutor](https://mail.python.org/mailman/listinfo/tutor) mailing lists, or [StackOverflow](https://stackoverflow.com), before assuming the language interpreter itself is wrong.

FYI, here's a clue, run this in the Python REPL:

```
>> 'e' or 'i'
'e'
```

**Comment by AlexWaygood** [comment]
@notatallshaw is correct
