### ISSUE TITLE
`test_pyexpat` has strange `assertRaises` check

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111490]
# Bug report

Look at this test: https://github.com/python/cpython/blob/940ee962a8a1e87543fd36338228e526e7f35067/Lib/test/test_pyexpat.py#L531-L547

It sets up a specific error class, does all the overriding just to check that raw `Exception` is raised?

It is problematic, because some different exception type might be raised there, like `TypeError`, not `SpecificError`, I don't see a reason to keep this test so forgiving.

### Linked PRs
* gh-111491

**Comment by serhiy-storchaka** [comment]
The test was initially added in 6ffe499397acfe916202e3e46adfa868e6a307b9 (bpo-1296433/#42389). The initial version raised Exception and ignored any exception.

Then it was rewritten in d28fcbc7fb568c1ed763e57b5d5dec13ebf07bee (bpo-1690169/#44780). It was not a simply refactoring, it changed the raised exception to SpecificException, and now it expects that `parser.Parse()` will raise some exception.

Maybe @freddrake or @collinw will be able to remember why they wrote the code in this way.
