### ISSUE TITLE
Adding option `signature` to `dataclass`

### ISSUE THREAD

**Issue by nstarman** [python/cpython#111403]
### Proposal:

On normal classes it's easy to set the ``__signature__`` attribute for every class using ``__init_subclass__``.
This is nice in that ``inspect.signature()`` will never recompute the ``Signature``.

```python
import inspect

class Base:
    def __init_subclass__(cls) -> None:
        if hasattr(cls, "__signature__"):  # needed to force recomputing
            del cls.__signature__
        cls.__signature__ = inspect.signature(cls)


class Class(Base):
    def __init__(self, a, b) -> None:
        pass

>>> inspect.signature(Class), Class.__signature__
(<Signature (a, b) -> None>, <Signature (a, b) -> None>)
```

For dataclasses this is not so simple. ``dataclass`` creates the ``__init__`` method after ``__init_subclass__`` is called, so this method doesn't work and computes the signature of the parent class.

```python
@dataclass
class Class(Base):
    a: int
    b: int

>>> inspect.signature(Class), Class.__signature__
(<Signature () -> None>, <Signature () -> None>)
```

It would be great if a kwarg were added to ``dataclass`` to add the ``__signature__`` attribute

```python
@dataclass(add_signature=True)
class Class(Base):
    a: int
    b: int

>>> hasattr(Class, "__signature__"), Class.__signature__
True, <Signature (a, b) -> None>
```

Alternatively, if there were a ``__post_init_subclass__`` method or something that is a method called by dataclasses.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

I am not aware of any previous discussion.

### Linked PRs
* gh-111473

**Comment by sobolevn** [comment]
Hi, thanks for the proposal. Wouldn't this solve your issue?

```python
>>> import dataclasses
>>> import inspect
>>> def with_sig(cls):
...    cls.__signature__ = inspect.signature(cls)
...    return cls
... 
>>> @with_sig
... @dataclasses.dataclass
... class My:
...    a: int
...    b: int
... 
>>> My.__signature__
<Signature (a: int, b: int) -> None>
```

You can combine `@dataclass` and `@with_sig` decorators into one, if you wish.

**Comment by nstarman** [comment]
Thanks @sobolevn for the good suggestion. It solves the issue for me, but then requires downstream users to import and use the ``with_sig`` decorator. That's not problematic per se, but perhaps less convenient than a built-in kwarg to `dataclass`.

**Comment by hauntsaninja** [comment]
Given that this can be solved in user code and is fairly niche, I don't think it's worth the cost of adding it to dataclass proper. If you don't want downstream users to import, you could also accomplish this via a metaclass that adds a lazily computed `__signature__`.

**Comment by ericvsmith** [comment]
Since this isn't a common use case and there are ways to work around it, I'm going to close this issue. If you want to pursue it, then I suggest opening a discussion on discuss.python.org.
