### ISSUE TITLE
C Task objects cannot be mocked with multiple inhertance

### ISSUE THREAD

**Issue by kristjanvalur** [python/cpython#111542]
# Bug report

### Bug description:

When inheriting from `asyncio.Task`, which by default is a C implemented object, and also from 
a python class, mocking fails on the resulting object.   Running the following code will result in an error, on python 3.11 and all other versions I've tested:

```python
from asyncio import Task
from asyncio.tasks import _PyTask as PyTask
from unittest import mock

class Other:
    pass
class MyTask(Task, Other):
    def foo(self):
        pass

class MyPyTask(PyTask, Other):
    def foo(self):
        pass

async def func():
    pass

# this will fail with a TypeError
with mock.patch.object(MyPyTask(func()), "foo"):
    pass  # ok
with mock.patch.object(MyTask(func()), "foo"):
    pass  # this fails with TypeError
```

This results in:

```
    with mock.patch.object(MyTask(func()), "foo"):
  File "C:\Program Files\Python311\Lib\unittest\mock.py", line 1443, in __enter__
    original, local = self.get_original()
                      ^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\unittest\mock.py", line 1406, in get_original
    original = target.__dict__[name]
               ^^^^^^^^^^^^^^^
TypeError: this __dict__ descriptor does not support 'MyTask' objects
```

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Windows

**Comment by sobolevn** [comment]
This seems to be solved on `main`:

```python
» ./python.exe --version
Python 3.13.0a1+
                                                                                           
(.venv) ~/Desktop/cpython2  main ✗                                                        
» ./python.exe ex.py    
/Users/sobolev/Desktop/cpython2/ex.py:19: DeprecationWarning: There is no current event loop
  with mock.patch.object(MyPyTask(func()), "foo"):
                                          
```

**Comment by kristjanvalur** [comment]
Indeed.  Using binary search I have found the commit:
4cfc1b8568bd8bf0d44fadc42ec86696d0561d33
GH-91375: Port `_asyncio` static types to heap types and module state (#99122)

**Comment by kumaraditya303** [comment]
Yeah nothing can be done for older versions. If you really want to patch it then avoid using C implementation by 
```py
sys.modules['_asyncio'] = None
```

**Comment by kristjanvalur** [comment]
> > Did this make it into 3.12?
> 
> Unfortunately, we cannot backport these types of changes :(

What I mean was that since the commit was almost a year ago, did it make it into the 3.12 branch before it got branched off master?  I haven't been a regular core contributor for almost 10 years now and don't follow the development roadmap too closely.

However, I do take it from your reply that it didn't.

Cheers, and thanks for looking into this with me.

**Comment by sobolevn** [comment]
I think that it made into 3.12, but not into 3.11

**Comment by terryjreedy** [comment]
@kristjanvalur Main and 3.12.0 were separated in May.  With our current yearly schedule, this is predictable.
