### ISSUE TITLE
Don't require __get__ to be callable (solution seeming possible without endless recursions caused in practice)

### ISSUE THREAD

**Issue by takuom** [python/cpython#111595]
# Bug report

### Bug description:

**The Root.**  The current behaviour of `object.__getattribute__` requires the member `__get__` of a class of descriptors to always be a callable object by itself (i.e., even without being bound as a method to an instance of the class).  However, it seems to be a reasonable expectation that `__get__` could sometimes be just a descriptor (which may not itself be callable) as any other unbound method may (see "Preliminary Discussion" below for a refinement of this).  An unbound method may be an uncallable object such as an object of type `property`, `functools.partialmethod` or `staticmethod`.

**Preliminary Discussion.**  Before describing a resulting problem, let me mention that a too obvious "fix" of what has been described can cause endless recursions analogous to
```python
### Unusual code, not the interpreter's fault.

class MyCallableObject:
    pass

MyCallableObject.__call__ = staticmethod(MyCallableObject())

object_ = MyCallableObject()
assert callable(object_)
object_() # RecursionError
```
to arise too easily (or even all the time).  In a way how that could be avoided, it seems essential that ***some*** `__get__`s be called as they currently are.  However, `__get__` just being "callable" (as verifiable by the built-in function `callable`) is not necessarily what prevents an endless recursion even currently, not just because of things like the example above, but also because calling `__get__` may involve getting `__get__.__call__` from it for the relevant `__call__` *descriptor*.  For example, we currently have the following endless recursion.
```python
### Unusual code again, not the interpreter's fault

from functools import partial

class MyDescriptor:
    pass

class MyGet:
    __call__ = MyDescriptor()

    def __get__(self, instance, owner=None):
        return self if instance is None\
               else partial(self, instance)

MyDescriptor.__get__ = MyGet()
# May this be better than `MyCallableObject()`
# before?  We'll see.

class MyObject:
    attr = MyDescriptor()

object1 = MyObject()
object1.attr # RecursionError
```
Thus, `__get__` just being callable (like `MyDescriptor.__get__` in the example) may not help the recursion to end.  `__get__.__call__` is of course got without further `__get__` in the relatively rare case where `__call__` that `type(__get__)` has is not a descriptor (and `__get__.__call__` will be this call `__call__`).  However, even after we somehow get `__get__.__call__`, there may remain the need to get `__call__` of this to call it, so the situation hasn't changed essentially.  `__get__` which ends the recursion immediately is one which can be called without getting its `__call__`.  Such `__get__` does seem valuable to call.  In other cases, I'm not sure whether the end of the recursion may get closer with the getting of `__get__.__call__` than with a getting of the descriptor's `__get__`, which seems essentially as easy.  On the other hand, the latter would solve a problem, which I'm ready to describe now.  (See my next post for more details of this part.)

**The problem.**  The attribute specified by a descriptor can fail to be got because `__get__` is never used as a descriptor in the process.  For instance,
```python
def get(self, instance, owner=None):
    return self if instance is None\
           else self._get(instance)

class MyGet1:
    __get__ = get
    _get = staticmethod(get.__get__)

class D:
    # Make `__get__` a non-callable descriptor.
    __get__ = MyGet1()

    def _get(self, instance):
        return instance # say

# Let's see how well `D.__get__` may work.

# A descriptor of type `D`.
d = D()

# Use `D.__get__` as a descriptor.
get_d = d.__get__

# A class with attribute "d" given by `d`.
class O:
    d = d

# An instance of `O`.
o = O()

# Get `o`'s attribute "d" by calling `get_d`.
assert get_d(o, O) is o # Will succeed.

# Thus, `D.__get__` has worked fine as a descriptor.
# Depite this, ...

# Use `object.__getattribute__` this time.
o.d # TypeError: 'MyGet1' object is not callable
```
The "`MyGet1` object" called unsuccessfully is `D.__get__` (called on arguments `d, o, O`).  It's a severe restriction that `__get__` must be callable without being bound.  For instance, `__get__` currently can't be of type `property`, `functools.partialmethod` or `staticmethod`.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by takuom** [comment]
To supplement "Preliminary Discussion" above, the only example I'm aware of of a built-in `__get__` which can't just be a descriptor is `__get__` which the class `cls := types.WrapperDescriptorType` has.  This, `get := cls.__get__`, is such as long as `type(get)` is `cls`.  (However, `vars(cls)["__call__"]` also happens to be of type `cls`, so `get.__call__` can't be got before `get` is called anyway!)  While similar patterns are easy to produce, e.g.,
```python
class MyDescriptor1:
    pass

MyDescriptor1.__get__ = MyDescriptor1()

descriptor = MyDescriptor1()
descriptor.__get__
```
I expect things like that to be rare in practice.

**Comment by rhettinger** [comment]
> It's a severe restriction that __get__ must be callable without being bound. 

Marking a closed for the reasons listed in issue 111686.  There doesn't seem to be any compelling use case for changing the descriptor API.  The early design decisions seem to have stood the test of time.
