### ISSUE TITLE
Make `_Py_HashDouble` public again as "unstable" API

### ISSUE THREAD

**Issue by seberg** [python/cpython#111545]
In NumPy we use `_Py_HashDouble` for our floating point hashing needs and that seems like a pretty good candiate for the unstable API to me: https://github.com/python/cpython/issues/91744#issuecomment-1111990057 and https://github.com/python/cpython/issues/101101#issue-1536645235.

However, the function is currently removed rather than made unstable (to my understanding).   While it should probably be easy enough to vendor what we needed,  I would prefer the unstable API tier, it gives a better sense of having the required identical hashing.

NumPy issue: https://github.com/numpy/numpy/issues/25035

_Originally reported by @ngoldbaum in https://github.com/python/cpython/issues/111418#issuecomment-1785929387_
            

### Linked PRs
* gh-112063
* gh-112095
* gh-112096
* gh-112098
* gh-112449
* gh-112476
* gh-112647
* gh-113115

**Comment by encukou** [comment]
cc @vstinner, per the [What's New](https://docs.python.org/3.13/whatsnew/3.13.html#id10)

**Comment by vstinner** [comment]
* I proposed PR https://github.com/python/cpython/pull/112095 to add a public PyHash_Double() function.
* I proposed PR https://github.com/python/cpython/pull/112096 to add a public PyHash_Pointer() function.

**Comment by serhiy-storchaka** [comment]
I wonder whether it is worth to add the `PyObject_GenericHash()` function that implements `object.__hash__`. Using `PyHash_Pointer()` for this is a CPython implementation detail and depends on the fact that `id()` returns the address of the object. In general, Python objects and pointers can use different hash functions.

**Comment by vstinner** [comment]
It was decided to not add a public API for now: https://github.com/capi-workgroup/decisions/issues/2#issuecomment-2066091296
