### ISSUE TITLE
test_tkinter leaks references on Windows

### ISSUE THREAD

**Issue by vstinner** [python/cpython#111531]
* Latest successful build: https://buildbot.python.org/all/#/builders/920/builds/543
* First failing build: https://buildbot.python.org/all/#/builders/920/builds/549

```
test_tkinter leaked [336, 336, 337] references, sum=1009
test_tkinter leaked [151, 151, 152] memory blocks, sum=454
```

### Linked PRs
* gh-111533
* gh-111535
* gh-111536

**Comment by vstinner** [comment]
git bisect points me to PR #111202 and commit 9bb202a1a90ef0edce20c495c9426d9766df11bb:

```
9bb202a1a90ef0edce20c495c9426d9766df11bb is the first bad commit
commit 9bb202a1a90ef0edce20c495c9426d9766df11bb
Author: Serhiy Storchaka <storchaka@gmail.com>
Date:   Tue Oct 24 13:02:12 2023 +0300

    gh-75666: Tkinter: add tests for binding (GH-111202)

 Lib/test/test_tkinter/test_misc.py | 307 +++++++++++++++++++++++++++++++++++++
 1 file changed, 307 insertions(+)
```

**Comment by terryjreedy** [comment]
@serhiy-storchaka 
f:\dev\3x>python -m test -ugui -R3:3 -m BindTest test_tkinter.test_misc
...
test_tkinter.test_misc leaked [336, 336, 336] references, sum=1008
test_tkinter.test_misc leaked [151, 151, 151] memory blocks, sum=453
test_tkinter.test_misc failed (reference leak)

I am running experiments to see which individual tests leak.

**Comment by terryjreedy** [comment]
I initially commented out blocks, then changed the -m arg to a test name and checked for only 1 match.
Leaks are pretty well spread out.  Results, possibly with errors:
test_??? name(s):  references, blocks
---------------------------------------
bind, unbind, unbind2: 6, 0
rebind, bind_class: 30,16
unbind_class: 30, 8
bind_class_rebind: 46, 18
bind_all: 30, 18
bind_tags: 0, 0
bind_events: 102, 59
unbind_all: 38, 20
bind_all_rebind: 53, 20

**Comment by serhiy-storchaka** [comment]
Thank you for your report Victor. It is not only on Windows.

I knew that something may be wrong with `bind_class()` and `bind_all()`, and was going to open a new issue when found a reproducer, but I did not know that it also causes leaks.

**Comment by serhiy-storchaka** [comment]
Thank you for your tests Terry. Could you please also check if #111533 fixes leaks? I do not see leaks in `bind()` on Linux, all leaks were in `bind_class()` and `bind_all()`.
