### ISSUE TITLE
Inaccurate error message for datetime.datetime.fromtimestamp

### ISSUE THREAD

**Issue by ericli-splunk** [python/cpython#111513]
# Bug report

### Bug description:

`datetime.datetime.fromtimestamp` recognizes floating point arguments, but when I mistakenly enter a string as an argument, I get the error message "TypeError: 'str' object cannot be interpreted as an **integer**". This error message implies that `fromtimestamp` only accepts integers, which is confusing.

Expected behavior: see error message "TypeError: 'str' object cannot be interpreted as a **float**" or similar.

The same problem happens for `datetime.datetime.utcfromtimestamp`.

```python
>>> import datetime
>>> datetime.datetime.fromtimestamp('1.234')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer
>>> datetime.datetime.fromtimestamp(1.234)
datetime.datetime(1969, 12, 31, 16, 0, 1, 234000)
>>> datetime.datetime.utcfromtimestamp('1.234')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer
>>> datetime.datetime.utcfromtimestamp(1.234)
datetime.datetime(1970, 1, 1, 0, 0, 1, 234000)
>>> datetime.datetime.fromtimestamp(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'NoneType' object cannot be interpreted as an integer
>>> 
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Linked PRs
* gh-111613
* gh-124249

**Comment by Eclips4** [comment]
I don't see any bug here, it's looks like a request to improve traceback message, so I'm removing `type-bug` and adding `type-feature` label.

**Comment by vstinner** [comment]
The error message  was enhanced by the change https://github.com/python/cpython/commit/1a577729e347714eb819fa3a3a00149406c24e5e.
