### ISSUE TITLE
error: identifier "_Atomic" is undefined

### ISSUE THREAD

**Issue by AgilentGCMS** [python/cpython#111539]
# Bug report

### Bug description:

I am trying to compile python using intel C/C++ compilers on a computing cluster for speed benefits. It fails with `error: identifier "_Atomic" is undefined`. Specifically, the following compile line fails (among others):

```
$ icpc -c -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -g  -O3 -Wall -fPIC -O3 -qopenmp -parallel -fomit-frame-pointer -g -m64 -xHost -prec-div -prec-sqrt -diag-disable=10441   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -fp-model strict -prof-gen -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE -o Programs/_testembed.o ./Programs/_testembed.c
In file included from /gpfsm/dulocal15/sles15/intel/oneapi/2021/compiler/2023.2.1/linux/bin/intel64/../../compiler/include/icc/stdatomic.h(74),
                 from ./Include/internal/pycore_atomic.h(15),
                 from ./Include/internal/pycore_runtime.h(11),
                 from ./Programs/_testembed.c(11):
/usr/lib64/gcc/x86_64-suse-linux/7/include/stdatomic.h(40): error: identifier "_Atomic" is undefined
  typedef _Atomic _Bool atomic_bool;
```

which then triggers several other errors. I've found several online discussions about `_Atomic` being undefined, but I haven't found a solution. Is this fixable? I would love to compile python with intel compilers, because other code compiled with icc/icpc on this particular system is significantly faster than gcc-compiled code.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AgilentGCMS** [comment]
I configure with
```
AR=xiar LD=xild CC=icc CPP="icc -E" LIBS='-lpthread -limf -lirc' CFLAGS='-fPIC -O3 -fomit-frame-pointer -g -m64 -xHost -prec-div -prec-sqrt -diag-disable=10441' ./configure --prefix=/discover/nobackup/projects/tm5var4d/packages/python/3.11.6 --enable-optimizations --with-cxx-main=icpc --with-ensurepip=install
```

**Comment by colesbury** [comment]
What version of the Intel compiler are you using?

**Comment by AgilentGCMS** [comment]
icc/icpc version 2021.10.0 (gcc version 7.5.0 compatibility)

**Comment by colesbury** [comment]
Do you get the same errors if you use icc instead of icpc? The relevant file is C (not C++).

**Comment by AgilentGCMS** [comment]
BTW, I just tried compiling with `gcc/g++` (as a backup in case there's no solution to the `icc/icpc` issue), and that fails as well. I configure with
```
CFLAGS='-fPIC -O3 -fomit-frame-pointer -g -march=native' ./configure --prefix=/discover/nobackup/projects/tm5var4d/packages/python/3.11.6 --enable-optimizations --with-cxx-main=g++ --with-ensurepip=install
```
and `make` fails with
```
g++ -c  -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -O3 -fomit-frame-pointer -g -march=native   -fno-semantic-interposition -std=c11 -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-generate -I./Include/internal  -I. -I./Include    -DPy_BUILD_CORE -o Programs/_testembed.o ./Programs/_testembed.c
cc1plus: warning: ‘-Werror=’ argument ‘-Werror=implicit-function-declaration’ is not valid for C++
cc1plus: warning: command-line option ‘-std=c11’ is valid for C/ObjC but not for C++
In file included from ./Include/internal/pycore_runtime.h:11,
                 from ./Programs/_testembed.c:11:
./Include/internal/pycore_atomic.h:38:32: error: ‘memory_order_relaxed’ was not declared in this scope
   38 |     _Py_memory_order_relaxed = memory_order_relaxed,
      |                                ^~~~~~~~~~~~~~~~~~~~
./Include/internal/pycore_atomic.h:39:32: error: ‘memory_order_acquire’ was not declared in this scope
   39 |     _Py_memory_order_acquire = memory_order_acquire,
      |                                ^~~~~~~~~~~~~~~~~~~~
./Include/internal/pycore_atomic.h:40:32: error: ‘memory_order_release’ was not declared in this scope
   40 |     _Py_memory_order_release = memory_order_release,
      |                                ^~~~~~~~~~~~~~~~~~~~
./Include/internal/pycore_atomic.h:41:32: error: ‘memory_order_acq_rel’ was not declared in this scope
   41 |     _Py_memory_order_acq_rel = memory_order_acq_rel,
      |                                ^~~~~~~~~~~~~~~~~~~~
./Include/internal/pycore_atomic.h:42:32: error: ‘memory_order_seq_cst’ was not declared in this scope
   42 |     _Py_memory_order_seq_cst = memory_order_seq_cst
      |                                ^~~~~~~~~~~~~~~~~~~~
./Include/internal/pycore_atomic.h:46:5: error: ‘atomic_uintptr_t’ does not name a type; did you mean ‘Py_uintptr_t’?
   46 |     atomic_uintptr_t _value;
      |     ^~~~~~~~~~~~~~~~
```
and a cascade of further errors.

**Comment by colesbury** [comment]
> I do see that the file in question is a C file and not a C++ file, so I have no idea why make calls g++ on that one.

This is the cause of the compile errors and what you should debug. It is likely specific to your system/configuration and not a problem with cpython in general.

**Comment by AgilentGCMS** [comment]
> Do you get the same errors if you use icc instead of icpc? The relevant file is C (not C++).

I do not! If I substitute `icpc` with `icc` on that compile line, there are a bunch of warnings but no errors. However, the `Makefile` is generated by `./configure`, I'm not doing it manually. Any idea why the C++ compiler is being called on C code? This seems to be the case irrespective of whether I use GNU or Intel compilers.

**Comment by AgilentGCMS** [comment]
So, during configure I specified the flag `--with-cxx-main=icc`, which got rid of this error and compiled python 3.11.6 successfully. This is confusing to me, however. I've compiled earlier versions of python by specifying a C++ compiler in this option. Do I understand correctly that now I *shouldn't* supply a C++ compiler here and force it to compile with a C compiler?

**Comment by colesbury** [comment]
I'm not familiar with `--with-cxx-main`, but I saw that it's removed in the `main` branch due to  https://github.com/python/cpython/issues/93744

**Comment by AgilentGCMS** [comment]
Ah, great! I wholeheartedly agree to the removal of `--with-cxx-main`, that one has foiled my compilation attempts of at least two, perhaps more, python releases (in hindsight).
