### ISSUE TITLE
Implement Python Critical Sections from PEP 703

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111569]
# Feature or enhancement

[PEP 703](https://peps.python.org/pep-0703/) introduces the concept of ["Python Critical Sections"](https://peps.python.org/pep-0703/#python-critical-sections), which are an abstraction to help replace the GIL with finer grained locking. The key ideas is to replace the GIL with per-object locks and *implicitly* release these locks in the same places where the GIL would have been released. The mechanism is:

1) Keep track of locked mutexes in a per-thread stack
2) When the thread ["detaches"](https://peps.python.org/pep-0703/#thread-states) from the interpreter (i.e., [`_PyThreadState_Detach()`](https://github.com/python/cpython/blob/244567398370bfa62a332676762bb1db395c02fc/Include/internal/pycore_pystate.h#L143-L147)), unlock all of the thread's locked mutexes
3) When the thread  re-["attaches"](https://peps.python.org/pep-0703/#thread-states) to the interpreter, re-lock the top-most mutex or mutexes.

The "public" [^public] API consists of four macros:

```c
Py_BEGIN_CRITICAL_SECTION(object);
Py_END_CRITICAL_SECTION;
Py_BEGIN_CRITICAL_SECTION2(object1, object2);
Py_END_CRITICAL_SECTION2;
```

These will be no-ops in the default build of CPython. 

Note that if you need to operate on two objects at once, then you must use the `Py_BEGIN_CRITICAL_SECTION2` macro. Nesting two calls to `Py_BEGIN_CRITICAL_SECTION` does not guarantee that both objects are locked because the inner calls may suspend the outer critical section.

[^public]: At least at the start, even these "public" macros will still be internal-only (i.e., in `Include/internal`). I expect that we will eventually want to make them public so that C-API extensions can make use of them.

### Linked PRs
* gh-111571
* gh-111897

**Comment by brettcannon** [comment]
The latest PR related to this change broke the WebAssembly buildbots by causing them to time out: https://buildbot.python.org/all/#/builders/1046/builds/3456/steps/11/logs/stdio .
