### ISSUE TITLE
socket.htons uses unnecessary METH_VARARGS

### ISSUE THREAD

**Issue by wrongnull** [python/cpython#111662]
# Feature or enhancement

### Proposal:

By replacing calling convention to ```METH_O``` it will run faster

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-111661

**Comment by serhiy-storchaka** [comment]
`socket.ntohs()` also can be optimized.

There is a larger patch in #64373 that converts the socket module to Argument Clinic. It would automatically apply such optimization for these functions and for many other.

**Comment by wrongnull** [comment]
> `socket.ntohs()` also can be optimized.
> 
> There is a larger patch in #64373 that converts the socket module to Argument Clinic. It would automatically apply such optimization for these functions and for many other.

The main idea of this issue is replacing calling convention to METH_O when needed. I think the clinic argument is optional here

**Comment by wrongnull** [comment]
@serhiy-storchaka moreover, I don't think this patch is actual since there are now ```get_module_state``` function calls

**Comment by corona10** [comment]
> socket.ntohs() also can be optimized.
> There is a larger patch in https://github.com/python/cpython/issues/64373 that converts the socket module to Argument > Clinic. It would automatically apply such optimization for these functions and for many other.

https://github.com/python/cpython/pull/111661 updated several methods to use AC tool instead of manual parsing.
If someone want to update other things too, please open a new issue.
