### ISSUE TITLE
asyncio.Condition.wait() sometimes propagates incorrect asyncio.CancelledError

### ISSUE THREAD

**Issue by kristjanvalur** [python/cpython#111693]
# Bug report

### Bug description:

`asyncio.Condition.wait()` contains an edge case where a `CancelledError` on lock re-aquire is overwritten with a fresh `CancelledError` instance.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-111694

**Comment by gvanrossum** [comment]
Hm, this issue description is rather lacking in detail, and doesn't seem to match the intricate fix in gh-111694. Could you update the initial comment?

**Comment by kristjanvalur** [comment]
Well, that was the original issue, the other changes were sort of piggybacked.   Looking at the issue now after your review, I'm only  really 

- adding a test for Future.done() for completeness.  It is redundant in the current code
- Fixing the FIFO wakeup semantics of semaphore
- Propagating the last CancelledError out of Condition.wait()
- Removing dead code
- Cleaning and improving comments.
I'll be happy to change this once we have settled on what is going to be in the PR, if anything :)
