### ISSUE TITLE
Incorrect example of NormalDist

### ISSUE THREAD

**Issue by mdmci** [python/cpython#111616]
In https://docs.python.org/3/library/statistics.html, under the subhead "NormalDist Examples and Recipes", the result of the first example should be an integer, but the result given is 18.4. 

Also, rounding is the last computation in the example; nothing happens after that, The description would be clearer if "after rounding" were replaced with "rounded".

**Comment by mdmci** [comment]
I retract the first part of this bug report. It arose from a misunderstaning,

**Comment by terryjreedy** [comment]
To get the 'not planned' reason, one must click the down arrow.
