### ISSUE TITLE
The requirement to keep micro-ops dense while optimizing is harmful.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#111646]
The tier 2 executor creation requires optimization passes to compact the micro-ops, which is onerous and error-prone.

We should make it part of the job of creating the executor to compact the micro-ops.
We will want to modify the tier 2 instruction format, so we will need to do this anyway at some point.

### Linked PRs
* gh-111647

**Comment by mdboom** [comment]
Can you elaborate on what you mean by "compact the microops"?  Is this removing unnecessary microops and (perhaps) realloc'ing a smaller buffer and copying there?

**Comment by markshannon** [comment]
Packing them together instead of leaving gaps.
So
```
Some uop
NOP
NOP
Another uop
JUMP to exit
# Junk here 
exit:
# More uops here
```
must be compacted to:
```
Some uop
Another uop
JUMP to exit
exit:
# More uops here
```
during optimization, rather than doing it once when creating the executor.

**Comment by mdboom** [comment]
Thanks, that makes sense.
