### ISSUE TITLE
test_asyncio: test_unhandled_exceptions() fails on x86-64 macOS 3.x buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#111644]
Apparently, the test is new and was added by PR #111601.

cc @kumaraditya303 

Logs:

```
test_unhandled_exceptions (test.test_asyncio.test_streams.StreamTests.test_unhandled_exceptions) ... Warning -- threading_cleanup() failed to cleanup 1 threads (count: 1, dangling: 2)
Warning -- Dangling thread: <_MainThread(MainThread, started 4648830464)>
ok
```

build: https://buildbot.python.org/all/#/builders/366/builds/5796

### Linked PRs
* gh-111713
* gh-111714
* gh-111716
* gh-111717
* gh-111718

**Comment by vstinner** [comment]
Oh, test fails on tons of buildbots: https://github.com/python/cpython/pull/111601#issuecomment-1790226039

**Comment by kumaraditya303** [comment]
I am not able to reproduce it on my system. Also I don't understand what `Warning -- Dangling thread: <_MainThread(MainThread, started 4648830464)>` means, how can main thread be considered dangling?

**Comment by vstinner** [comment]
> I am not able to reproduce it on my system. Also I don't understand what Warning -- Dangling thread: <_MainThread(MainThread, started 4648830464)> means,

It usually means that a test spawns a thread and don't fully wait until the thread completes.

**Comment by vstinner** [comment]
I can reproduce the issue with the command:

```
./python -m test test_asyncio.test_streams -m test_unhandled_exceptions -v -j10 --fail-env-changed -F
```

**Comment by kumaraditya303** [comment]
Thanks @vstinner
