### ISSUE TITLE
DataFrame column dtype != comparison with date type fails to give correct outcome

### ISSUE THREAD

**Issue by avnishbm** [python/cpython#111636]
# Bug report

### Bug description:

```python
import pandas as pd
from datetime import date

df = pd.DataFrame(['2023-11-01','2023-01-01' '2022-01-02'] , columns=['date']) 

print (df.dtypes['date'])

print (df.dtypes['date'] != date)

print (df.dtypes['date'] is not date)
```

When we run the above code, we see that the datatype of 'date' column is object, but when compared with date type using != it returns False in place of True. But the same comparison done using "is not" returns True! Please note that that this was working in earlier versions.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by avnishbm** [comment]
This boils down to the numpy behavior:

from datetime import date
import numpy as np

dtype = np.dtype(object)

>>> dtype == date
True

**Comment by avnishbm** [comment]
The above sample code shared by @jbrockmendel in pandas issue tracker.

**Comment by sobolevn** [comment]
![изображение](https://github.com/python/cpython/assets/4660275/f8bc8110-8dea-4cb6-a728-00206ef55abb)

We need to go deeper!
Let's do the same without `numpy` or `pandas` :)

**Comment by avnishbm** [comment]
:)

Not able to reproduce it with just object and date type i.e. the following code works fine & returns True as expected :
x = object()
print (x != date)

**Comment by sobolevn** [comment]
Then - we cannot be sure that this is our bug and not numpy bug.

**Comment by avnishbm** [comment]
ok, assume this bug cannot be transferred to numpy component and i need to raise a fresh issue against numpy?

**Comment by ronaldoussoren** [comment]
This can be reproduced with

```python
import numpy as np
from datetime import date

print(np.dtype(object) == date)
```

This will print `True`.  I don't know if this is intentional behaviour from numpy (although it seems likely that it is from what I've found on Google), but this is not a bug in CPython.
