### ISSUE TITLE
In multiple threads applications, using fork results in occasional blocking rather than occasional hanging up.

### ISSUE THREAD

**Issue by 113xiaoji** [python/cpython#111635]
# Bug report

### Bug description:

# In multi-threaded applications, using fork results in blocking rather than hanging up.

We have a multi-threaded application, and in order to interact with scripts, we use a self-developed component similar to  [[pexpect](https://github.com/pexpect/pexpect)](https://github.com/pexpect/pexpect).  issue: https://github.com/pexpect/ptyprocess/issues/50, https://github.com/pexpect/pexpect/issues/369. The underlying implementation uses os.fork(). According to related issues, this can occasionally lead to unexpected deadlocks, as discussed in https://discuss.python.org/t/concerns-regarding-deprecation-of-fork-with-alive-threads/33555. However, our scenario is quite interesting. In our case, the child process gets blocked, and it doesn’t return until after a timeout of 30 seconds. Additionally, this slowness manifests suddenly and persistently from a black box perspective. Normally, it should take less than 0.1 seconds, but in problematic environments, it can persist for more than 20 seconds, and even up to 30 seconds, eventually causing the child process to be killed due to a timeout. Alternatively, the process may execve to a root process, becoming unkillable and turning into a zombie process. The code and phenomena are as follows:

Code:

Initializing an expect instance for command execution:

~~~python
def build(self, command, first_require="Username:",
                   second_require="Password:", timeout=72000):
    self.logger.info('get cmd: %s', command)
    process = expect.Spawn(command)
    try:
        idx = process.expect([first_require], 30)
        if idx == 0:
            process.send_line(self.adm_user)
        else:
            self.logger.error("excute zenithctl output: %s" % process.child_process_output)
            self.error_message = process.child_process_output
            self.close(process)
            return False
        ```
        return False
    except Exception:
        self.logger.info(traceback.format_exc())
        self.logger.info("run command failed")
        return False
    finally:
        self.close(process)
~~~

Expect implementation, the main tasks performed by the child process include: Setting the window size, setting echo, closing file descriptors, and executing execve.

```python
def _do_spawn(self):
        if not self.execute_file:
            raise ExpectException('Execute file is not selected')

        try:
            child_pid, child_fd = pty.fork()
        except OSError:
            raise ExpectException('Execute pty fork failed.')

        if child_pid == pty.CHILD:
            try:
                # Set window size
                try:
                    set_win_size_method = getattr(termios, 'TIOCSWINSZ', -2146929561)
                    windows_size = struct.pack('HHHH', 1920, 1080, 0, 0)
                    fcntl.ioctl(sys.stdin.fileno(), set_win_size_method, windows_size)
                except IOError as io_error:
                    if io_error.args[0] not in (errno.EINVAL, errno.ENOTTY):
                        raise ExpectException('Set window size exception')

                # Set echo
                try:
                    attr = termios.tcgetattr(sys.stdin.fileno())
                    attr[3] = attr[3] & ~termios.ECHO
                    termios.tcsetattr(sys.stdin.fileno(), termios.TCSANOW, attr)
                except termios.error as termi_err:
                    if termi_err.args[0] == errno.EINVAL:
                        raise IOError(termi_err.args[0], '%s: Set echo failed.' % termi_err.args[1])
                    raise ExpectException('Set echo failed.')
                except IOError as io_error:
                    if io_error.args[0] == errno.EINVAL:
                        raise IOError(io_error.args[0], '%s: Set echo failed.' % io_error.args[1])
                    raise ExpectException('Set echo failed.')

                # Close unnecessary open files
                max_file_no = resource.getrlimit(resource.RLIMIT_NOFILE)[0]
                os.closerange(3, max_file_no)
                signal.signal(signal.SIGHUP, signal.SIG_IGN)

                # Execute command line
                os.execv(self.execute_file, self.execute_command_args)
            except BaseException:
                # Exit child process in case of any exception
                sys.exit(1)
        else:
            # Handle parent process if needed
            self._process_parent_process(child_pid, child_fd)
```

The `process.expect([first_require], 30)` method utilizes selectors and epoll for implementation, waiting for the child process to produce output.

The `close` function in `expect`.

```python
def close(self):
        if self.is_child_process_closed:
            return
        
        os.close(self.child_fd)
        if self.sel:
            self.sel.close()

        time.sleep(self.close_child_process_delay)
        while True:
            # Check if the child process is still alive
            if self.child_process_terminated:
                break
            waitpid_options = 0 if self.child_process_read_eof else os.WNOHANG
            try:
                process_id, process_status = os.waitpid(self.child_pid, waitpid_options)
                if process_id == 0:
                    continue
                if os.WIFEXITED(process_status):
                    self.child_process_status = os.WEXITSTATUS(process_status)
                elif os.WIFSIGNALED(process_status):
                    self.child_process_status = os.WTERMSIG(process_status)
                elif os.WIFSTOPPED(process_status):
                    raise ExpectException('Process already been stopped.')
                self.child_process_terminated = True
                break
            except OSError as e:
                if e.errno == errno.ECHILD:
                    raise ExpectException('Process already not exist.')
                else:
                    raise
            break

        if not self.child_process_terminated:
            # Try to terminate the child process
            kill_signals = [signal.SIGHUP, signal.SIGCONT, signal.SIGINT, signal.SIGKILL]
            for _signal in kill_signals:
                try:
                    os.kill(self.child_pid, _signal)
                except OSError as e:
                    if e.errno != errno.ESRCH:
                        time.sleep(self.terminate_child_process_delay)
                        continue
                break

        self._set_closed_status()
```

command is :

```shell
/usr/bin/sudo -u xxx /bin/bash -c "xxx"
```

Phenomenon:

- The logs for the exception branch "execute zenithctl output:" and the entrance log "get cmd:" are just over 30 seconds apart.
- In the failure scenario, there is no record in the sudo logs.
- Calling build twice in a ten-second interval, but seeing the output in the sudo logs within the same second. Additionally, the call time and the time recorded in the sudo logs are all over 10 seconds, even reaching 20 or 30 seconds.
- In the sudo logs, some entries have TTY=unknown while others have TTY=pts/0.
- The script that was supposed to be executed did not run.
- The issue occurred in multiple live environments without any obvious pattern and couldn't be reproduced by us.
- Retrying in the failing environment still results in failure.
- Adjusting the execution time period still leads to failure.
- Manually executing the command is very fast.
- In the problematic scenario, system resources are normal, not exceptionally high.
- Zombie processes appeared because, after 30 seconds, when we tried to kill the process, we found that the sudo process had already been started and the user did not have the permissions to handle it.
- After restarting the service, the problem disappeared.
- The first time the service was deployed, the file descriptor limit was 65536, and after restarting, it was 4096.

Progress:

We are almost certain that the child process is blocked, not deadlocked; it's just slow, not perpetually stuck. The specific location is from after the fork in the child process to before the execve is finally executed. It’s unclear exactly where it is getting blocked. We have ruled out all system calls that could potentially block.

Points of confusion:

Using fork in a multithreading environment cannot explain why when calling build twice at a ten-second interval, the output appears in the sudo logs within the same second. Moreover, both the call time and the time recorded in the sudo logs exceed 10 seconds, sometimes even reaching 20 or 30 seconds.

Suspicions:

The process is blocked after fork, waiting for some resources, and these resources are eventually acquired. What's puzzling is what unusual scenario triggers this situation.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by 113xiaoji** [comment]
@itamarst @gpshead

**Comment by gpshead** [comment]
This sounds like a specific issue with your application that we can't help diagnose.  behavior of applications that fork when they have multiple threads is at best undefined.  deadlocks are only one possibility.

If I were debugging this kind of thing, reproducing the entire thing while running under strace might give you a better idea of what is happening in the child.  But in the end I'd still be looking to get rid of your threading+fork mix.

**Comment by 113xiaoji** [comment]
> This sounds like a specific issue with your application
Indeed, I haven't found any direct evidence related to CPython; currently, I am reviewing the code and issues of CPython regarding post-fork handling.
> behavior of applications that fork when they have multiple threads is at best undefined. deadlocks are only one possibility.
So, it's possible that in our case the process slows down but doesn't result in a deadlock.
> If I were debugging this kind of thing, reproducing the entire thing while running under strace might give you a better idea of what is happening in the child.
> I've used strace in a home environment, and I couldn't reproduce the issue; everything works normally. It seems we might have to wait until the issue occurs again in the production environment to capture it with strace.
> But in the end I'd still be looking to get rid of your threading+fork mix.
Using multi-threading with fork can lead to all sorts of strange and unpredictable issues, and it's generally advised against by the community.

**Comment by 113xiaoji** [comment]
> This sounds like a specific issue with your application that we can't help diagnose. behavior of applications that fork when they have multiple threads is at best undefined. deadlocks are only one possibility.
> 
> If I were debugging this kind of thing, reproducing the entire thing while running under strace might give you a better idea of what is happening in the child. But in the end I'd still be looking to get rid of your threading+fork mix.
1.Indeed, I haven't found any direct evidence related to CPython; currently, I am reviewing the code and issues of CPython regarding post-fork handling.
2.So, it's possible that in our case the process slows down but doesn't result in a deadlock.
3.I've used strace in a home environment, and I couldn't reproduce the issue; everything works normally. It seems we might have to wait until the issue occurs again in the production environment to capture it with strace.
4.Using multi-threading with fork can lead to all sorts of strange and unpredictable issues, and it's generally advised against by the community.
