### ISSUE TITLE
Tier 2 pystats uop counts are missing

### ISSUE THREAD

**Issue by mdboom** [python/cpython#111663]
# Bug report

### Bug description:

7e135a48d619407cd4b2a6d80a4ce204b2f5f938 inadvertently removed the uop count pystats.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-111664

**Comment by hugovk** [comment]
Closing because https://github.com/python/cpython/pull/111664 was merged, feel free to re-open if needed.
