### ISSUE TITLE
Make decimal.Decimal a subclass of numbers.Real and numbers.Complex

### ISSUE THREAD

**Issue by Prometheus3375** [python/cpython#111668]
# Bug report

### Bug description:

```python
from decimal import Decimal
from numbers import Real

print(issubclass(int, Real))  # True
print(issubclass(float, Real))  # True
print(issubclass(Decimal, Real))  # False
```

For some reason `decimal.Decimal` is not registered as a subclass of `numbers.Real`, but `decimal.Decimal` implements all `numbers.Real` abstract methods. And from common sense, any decimal is real for sure.

Since `numbers.Real` is a subclass of `numbers.Complex`, `decimal.Decimal` should also be a subclass of `numbers.Complex`.

I was thinking about `decimal.Decimal` also being a `numbers.Rational` subclass (because decimals have exact precision and can be representation as a ratio), however, `decimal.Decimal` does not implement `numerator` and `denominator` required for `numbers.Rational` subclasses.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
@rhettinger ?

**Comment by pochmann** [comment]
Previous issue: https://github.com/python/cpython/issues/87768

**Comment by Prometheus3375** [comment]
Well, I searched for such issue with query `is:issue is:closed Decimal Real`; it gave 9 pages of results, so I looked through the first page only. But #87768 was the first on the seconds page. ¯\_(ツ)_/¯
