### ISSUE TITLE
New compile warnings: `variable ‘seq’ set but not used` in `executor_cases.c.h`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#111603]
# Bug report

Introduced in https://github.com/python/cpython/pull/111600
CC @markshannon 

<img width="476" alt="Снимок экрана 2023-11-01 в 17 13 45" src="https://github.com/python/cpython/assets/4660275/2832d50d-ebf8-4988-8187-b9642e0d98eb">
<img width="519" alt="Снимок экрана 2023-11-01 в 17 13 33" src="https://github.com/python/cpython/assets/4660275/6a3ad81d-0c6c-46bf-b765-c3bb7ac14dd1">

**Comment by aisk** [comment]
I think this is already fixed by https://github.com/python/cpython/pull/111619 .

**Comment by vstinner** [comment]
> I think this is already fixed by https://github.com/python/cpython/pull/111619 .

In this case, you may need to rebase your PR to avoid the warning.
