### ISSUE TITLE
`dict` items views have set like operations even when the values are not hashable.

### ISSUE THREAD

**Issue by EvanTheB** [python/cpython#111622]
# Documentation

> Keys views are set-like since their entries are unique and [:term:`hashable`](https://github.com/python/cpython/blob/main/Doc/library/stdtypes.rst#id650). If all values are hashable, so that (key, value) pairs are unique and hashable, then the items view is also set-like. (Values views are not treated as set-like since the entries are generally not unique.) For set-like views, all of the operations defined for the abstract base class [:class:`collections.abc.Set`](https://github.com/python/cpython/blob/main/Doc/library/stdtypes.rst#id652) are available (for example, ==, <, or ^). While using set operators, set-like views accept any iterable as the other operand, unlike sets which only accept sets as the input.

```
> {1:2, 3:4}.items() >= {1:2}.items()
True
> {1:[2], 3:4}.items() >= {1:[2]}.items()
True
> set({1:[2], 3:4}.items())
TypeError: unhashable type: 'list'
```

It seems like this documentation is not accurate. `dict.items()` does have set operations even when the values are not hashable. 

See also: https://stackoverflow.com/questions/77399592/set-like-behaviour-of-dict-items-for-non-hashable-values

### Linked PRs
* gh-112051
* gh-112052

**Comment by terryjreedy** [comment]
My guess is the same as in 'Blcknight's answer: it was realized that items is read only, making hash((key,value)) = hash(key) is sufficient, making the caveat in the doc unnecessary.  To be sure, someone should check that the items for the example dict works for all of the supported operations.  And check the dict items code and the git blame history of revisions of that code.

**Comment by pochmann** [comment]
Not all set operations actually *work*, for example `{0: []}.items() | set()` fails .

**Comment by rhettinger** [comment]
Perhaps replace with second sentence with:

> Item views also have set-like operations since the (key, value) pairs are unique
> and the keys are hashable.  If the values in the items view are hashable as well,
> then the items views can interoperate with other sets.

**Comment by terryjreedy** [comment]
#112051 is mostly Raymond's suggestion.

**Comment by terryjreedy** [comment]
3.11 backport failed (conflict)
