### ISSUE TITLE
Visibility of wsgiref.util.is_hop_by_hop

### ISSUE THREAD

**Issue by stefan6419846** [python/cpython#111768]
# Documentation

`wsgiref.util.is_hop_by_hop` is available inside the official documentation (https://docs.python.org/3/library/wsgiref.html#wsgiref.util.is_hop_by_hop), but https://github.com/python/cpython/blob/ba8aa1fd3735aa3dd13a36ad8f059a422d25ff37/Lib/wsgiref/util.py#L5-L8 does not expose the method. This leads to IDE warnings when actually using it.

Is this method intended for public usage and just missing from `__all__` - or should this be considered an internal method instead?

### Linked PRs
* gh-111770

**Comment by Eclips4** [comment]
Hello!
If it's presented in docs, then it's intended as public function, so seems that someone forgot to put it in `__all__`.
Would you like to send a PR?
