### ISSUE TITLE
Set Types Described as Immutable and Mutable in Python Reference

### ISSUE THREAD

**Issue by bvarunreddy07** [python/cpython#111701]
# Documentation
Description:
Location: The inconsistent information is found in the Set Types section of the Python documentation at 3.2.6 [https://docs.python.org/3/reference/datamodel.html].
Issue: The first sentence in the Set Types section mentions that sets represent "unordered, finite sets of unique, immutable objects." However, later in the same section, it contradicts this by stating that sets are mutable and can be modified.

Expected Behavior: Can you clarify the definition of set types to avoid confusion.

**Comment by AlexWaygood** [comment]
Sets are mutable but the objects contained in them are generally immutable. The statements you quote are not in contradiction with each other.

**Comment by bvarunreddy07** [comment]
Understood.
Thank you Alex for clarifying it quickly.
