### ISSUE TITLE
Use PyDict_GetItemRef()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111789]
The following PR makes the code, that currently uses `PyDict_GetItemWithError()` which returns a borrowing reference and then call `Py_INCREF()` on the result to make a strong reference, to use `PyDict_GetItemRef()`.

cc @vstinner

### Linked PRs
* gh-111790
* gh-111827
* gh-111828
* gh-111829
* gh-111978
* gh-111979
* gh-111980
* gh-112072
* gh-112073
* gh-112074
* gh-112076
* gh-112077
* gh-112078
* gh-112079
* gh-112080
* gh-112081
* gh-112082
* gh-112083
* gh-112084

**Comment by gvanrossum** [comment]
It would perhaps be easier to review if there was one PR per file touched. That way the expert for a given file can approve (or even merge) without having to say something like "okay for foobar.c" and the PR author won't have to keep track of which files are approved.

**Comment by serhiy-storchaka** [comment]
> It would perhaps be easier to review if there was one PR per file touched.

Done.
