### ISSUE TITLE
_get_attr in nanos.py converts pd.NaT info a float, which breaks the minimization of datetimes

### ISSUE THREAD

**Issue by Tunneller** [python/cpython#111711]
# Bug report

### Bug description:

I was having wierd behaviour with pd["A"].min() if A had some pd.NaT in it, specifically python would complain that you cannot test <'' between a Timestamp and a Float.

I chased it down into nanos.py which in the example below is receiving a 2D array with values[0]0] a valid datetime and values[0][1] equal to pd.NaT.

I put in some print statements..... in _get_attr(). The rest is original code (python 3.12)

```
    try:
        print("Line 298", values[0][1], type(values[0][1]))
    except:
        pass
    
    datetimelike = False
    if values.dtype.kind in "mM":
        # changing timedelta64/datetime64 to int64 needs to happen after
        #  finding `mask` above
        values = np.asarray(values.view("i8"))
        datetimelike = True

    if skipna and (mask is not None):
        # get our fill value (in case we need to provide an alternative
        # dtype for it)
        fill_value = _get_fill_value(
            dtype, fill_value=fill_value, fill_value_typ=fill_value_typ
        )

        if fill_value is not None:
            if mask.any():
                if datetimelike or _na_ok_dtype(dtype):
                    values = values.copy()
                    np.putmask(values, mask, fill_value)
                else:
                    # np.where will promote if needed
                    values = np.where(~mask, values, fill_value)

    try:
        print("Line 329", values[0][1], type(values[0][1]))
    except:
        pass

```
The first print statement gives:
```
Line 298 NaT <class 'pandas._libs.tslibs.nattype.NaTType'>
```

The last print statement gives
```
Line 329 inf <class 'float'>
```
And from there everything goes downhill. My specific build is:

Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32

I did not see this bug already reported. Sorry in advance if it was....

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
This is not a CPython issue. You should probably take this to Pandas.

**Comment by Tunneller** [comment]
Indeed.

 

I will do so.

 

John
