### ISSUE TITLE
Support webp formats in mimetypes as standard types

### ISSUE THREAD

**Issue by Nachtalb** [python/cpython#111741]
# Feature or enhancement

### Proposal:

WEBP is not recognised as a standard type and demands the user to use `strict=False` as in `mimetypes.guess_type("foobar.webp", strict=False)` to recognise it. This is because it was previously not recognised by IANA as an official type. 

Since the introduction of `webp` support in the `mimetypes` module in #89802 it has officially been accepted to IANA and thus is not a "non-standard format" anymore. 

Refs:
- https://bugs.chromium.org/p/webp/issues/detail?id=448#c46
- https://www.iana.org/assignments/media-types/media-types.xhtml#image
- https://datatracker.ietf.org/doc/draft-zern-webp/12/

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://bugs.python.org/issue38902
https://bugs.python.org/issue45639
https://github.com/python/cpython/issues/89802

### Linked PRs
* gh-111742

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @Nachtalb.
