### ISSUE TITLE
Tkinter - iconbitmap returning empty string

### ISSUE THREAD

**Issue by fra87** [python/cpython#111759]
# Bug report

### Bug description:

According to the documentation, the `iconbitmap` function returns the bitmap if None is given.

However when I set an icon the iconbitmap function always returns an empty string.

For instance this code:

```python
from tkinter import Tk
win = Tk()
win.iconbitmap(bitmap='icon.ico')
extracted = win.iconbitmap()
print(extracted)
print(type(extracted))
sys.exit()
```

returns

```

<class 'str'>
```

(the first line is empty)

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
`win.iconbitmap()` returns `self.tk.call('wm', 'iconbitmap', self._w, None) which, according to the `tk.call` conventions and the [tk doc](https://www.tcl.tk/man/tcl8.6/TkCmd/wm.html#M45) returns "the name of the current icon bitmap associated with *window*".  Are you sure that 'icon.ico' exists, is found, and has the proper format?  Does the expected icon appear on the window?

**Comment by fra87** [comment]
Hello

Yes, I confirm.

I just tried on another PC (this one has Python Portable 3.11.1 on it). I downloaded the python.ico file (https://github.com/python/cpython/blob/main/PC/icons/python.ico), then tried reading the value at different times:

```python
from tkinter import *
win = Tk()
win.iconbitmap(bitmap='python.ico')
win.geometry("220x100")
extracted = win.iconbitmap()
print(extracted)
print(type(extracted))
strvar = StringVar()
lbl = Label(win, textvariable = strvar)
lbl.pack()
strvar.set('hi')
lbl.after(2000, lambda : strvar.set(win.iconbitmap()))

win.mainloop()

extracted = win.iconbitmap()
print(extracted)
print(type(extracted))
```

The first print shows an empty string the label's content gets erased after 2 seconds (which means win.iconbitmap returns an empty string) and the last call fails because the window was already destroyed.

The icon of the window changes from the usual blue feather to the python app icon, so the ICO file is definitely found and applied.

For the moment I only tried on windows (this PC has Win10, the other Win11) and on Python 3.11

**Comment by serhiy-storchaka** [comment]
All works on Linux (with the amendment that you should use `'@python.xbm'`).

I tested in pure Tk on Windows. You can run Wish (for example `externals\tcltk-8.6.13.1\amd64\bin\wish86t.exe`) and enter two commands in the console:
```tcl
wm iconbitmap . PC/icons/python.ico
wm iconbitmap .
```
They output nothing.

Perhaps this function does not work on Windows, or it requires some conditions. In any case it is not a Python issue.
