### ISSUE TITLE
Extend math.sumprod to handle arbitrary number of input iterables

### ISSUE THREAD

**Issue by TrangOul** [python/cpython#111840]
# Feature or enhancement

### Proposal:

"Revival" of the proposal by @rhettinger with example from @Dutcho

> 5. The MS Excel implementation generalizes `sumprod` to handle an arbitrary number of input vectors.   If there were valid use cases, we could do the same:
> 
> ```python
> def sumprod(*vecs):
>     return sum(map(math.prod, zip(*vecs, strict=True)))
> 
> >>> sumprod([10, 20, 30, 40], [2, 4, 6, 8], [1, 2, 3, 4])
> 2000
> >>> 10*2*1 + 20*4*2 + 30*6*3 + 40*8*4
> 2000
> ```

> Example use case (as variant to the motivating example at the [very top message](https://github.com/python/cpython/issues/100485#issue-1509903997) of this thread):
`sum([price * quantity * (1 - discount) * (1 + tax_rate) for price, quantity, discount, tax_rate in zip(prices, quantities, discounts, tax_rates)])`
which would then become:
`sumprod(prices, quantities, (1 - discount for discount in discounts), (1 + tax_rate for tax_rate in tax_rates))`

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

https://github.com/python/cpython/issues/100485#issuecomment-1465246451

**Comment by rhettinger** [comment]
Thanks for the suggestion, but I had previously decided against this for several reasons.  There isn't a clean way to extend the float exact-multiply step.The number of use cases is very small. It greatly complicates the code.   Another issue is that examples such as the one given above don't read very well and result in excel-like very long formulas.
