### ISSUE TITLE
Concurrently entering multiple asynchronous context managers

### ISSUE THREAD

**Issue by SuibianP** [python/cpython#111838]
# Feature or enhancement

### Proposal:

`async with` and `AsyncExitStack` alike maintain a well-defined sequential order of enter/exit. There are times where entering multiple independent asynchronous context managers concurrently is desirable. Consider,

```python
async with BLEDevice("mydevice1") as bd, RFDevice("mydevice2") as rd, WebSocket("localhost:1234") as ws:
    ...
```
the contexts of `rd` and `ws` will not start to be entered at all until `bd` finishes initialising itself and return from `__aenter__`.

I would like to propose something like `AsyncExitBag`, which should allow multiple asynchronous context managers to be entered concurrently while maintaining the same safety guarantees of no dangling contexts. My preliminary implementation is as follows (a bit like the deprecated `contextlib.nested`),

```python
import asyncio
import sys


class AsyncExitBag:
    def __init__(self, *cms):
        self.cms = cms
        self.tg = asyncio.TaskGroup()

    async def __aenter__(self):
        def task_finished(task: asyncio.Task):
            return task.done() and (not task.cancelled()) and (task.exception() is None)

        await self.tg.__aenter__()
        aenter_task_dict = {self.tg.create_task(cm.__aenter__()): cm for cm in self.cms}
        try:
            await self.tg.__aexit__(*sys.exc_info())
        except:
            # __aexit__ those successfully completed
            await asyncio.gather(
                *[cm.__aexit__(*sys.exc_info()) for task, cm in aenter_task_dict.items() if task_finished(task)])
            raise

        return (task.result() for task in aenter_task_dict.keys())

    async def __aexit__(self, *exc_details):
        await asyncio.gather(*[cm.__aexit__(*exc_details) for cm in self.cms])
```

And the usage example,

```python
class TestACM:
    def __init__(self, dur: int, throw: bool, val):
        self.dur = dur
        self.throw = throw
        self.val = val

    async def __aenter__(self):
        print("__aenter__ in")
        await asyncio.sleep(self.dur)
        print("Initial sleep over")
        if self.throw:
            raise NotImplementedError
        print("__aenter__ out, val: ", self.val)
        return self.val

    async def __aexit__(self, *exc_info):
        print("__aexit__ in")
        await asyncio.sleep(self.dur)
        print("__aexit__ out")


async def main():
    async with AsyncExitBag(TestACM(1, True, 42), TestACM(0, False, 43)) as (v1, v2):
        print("In async with body: value ", v1, v2)
    print("Out of async with")


asyncio.run(main())
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://stackoverflow.com/q/53050553/12385184

**Comment by gvanrossum** [comment]
This sounds like a fairly esoteric use case, and you have managed to solve it with a pretty simple piece of code. I'm not sure that I would like to take over maintenance of that in the stdlib though -- we already have enough things for which we can barely find maintainers. If you feel this is worth sharing, maybe you could turn it into a PyPI package? Or you could contribute it to something like [anyio](https://github.com/agronholm/anyio).

**Comment by SuibianP** [comment]
(Please do correct me if I am wrong — I am admittedly not too well versed in Python :)

From a user perspective, code is hoped to run as fast as feasible, safety guarantees prevailing of course. Async context managers are already expected to be safe to preempt at all yield points and to do proper cleanup if `__aenter__` fails half way, so running concurrently feels like a net win without drawbacks. I find the `with` sequencing, while straightforward in the sync case, valuing purity/consistency too much in the async case.

The `async with` sequencing is set in stone for Python 3, and I was thinking if such a feature, if included in the batteries, might as well be helpful for users.

**Comment by OCopping** [comment]
@SuibianP I have a use-case where I need two separate `TaskGroup`s (or similar) and this appears to be one possible solution. I wrote up my situation on [this StackOverflow post](https://stackoverflow.com/questions/77962866/python3-11-asyncio-is-it-possible-to-create-two-concurrent-taskgroups-if-so-i).
I have now tried: 
```python
async def create_task_group(
    task_group: asyncio.TaskGroup,
    tasks: List[Coroutine[Any, Any, Any]],
) -> asyncio.TaskGroup:
    for task in tasks:
        t = task_group._tasks.add(asyncio.create_task(task))
    await asyncio.sleep(0)
    return task_group

t1 = await create_task_group(self.task_group_1, tg1)
t2 = await create_task_group(self.task_group_2, tg2)

# handle exceptions
try:
    async with AsyncExitBag(t1, t2) as (_t1, _t2):
        print(_t1, _t2)
except* AbortException as err:
    print(f"{err=}")
await asyncio.sleep(0)
```
This appears to work initially, and the program appears to run fine. However, when I raise an exception in the second `TaskGroup`, the group is never cancelled. (I know that putting the `try except*` around the async with `AsyncExitBag` is a bit pointless, but thought it would be better than nothing)
I call a function to raise this exception, and I have another function that has this code below:
```python
async def _tasks_done() -> None:
    assert isinstance(self.task_group_2._tasks, set)
    while len(self.task_group_2._tasks) != 0:
        print(self.task_group_2._tasks)
        await asyncio.sleep(1)

# wait for all tasks to be "cancelled"
await asyncio.wait_for(_tasks_done(), timeout=None)
print("tasks done")
```
It never reaches the "tasks done" print statement, and just constantly prints out the task list.

I'm not sure exactly how passing a `TaskGroup` into `AsyncExitBag` is handled, but I feel like this is would be important to handle if you want to allow passing in _any_ form of asynchronous context manager.

On another note, how would you feel about providing the ability to "restart" or "recover"  a context manager within the `AsyncExitBag` if only one of all the ones passed in is cancelled? This would probably need to be in a seperate issue/PR though.

**Comment by SuibianP** [comment]
@OCopping I have not really tested, but is there any reason for using `TaskGroup._task` directly instead of the public `TaskGroup.create_task` interface? The latter [notifies the `TaskGroup` when the task is done](https://github.com/python/cpython/blob/235cacff81931a68e8c400bb3919ae6e55462fb5/Lib/asyncio/taskgroups.py#L174), the absence of which is probably the culprit.

**Comment by kumaraditya303** [comment]
I suggest to create it as a package for pypi as there is not a lot of use case of it to be in stdlib.
