### ISSUE TITLE
Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### ISSUE THREAD

**Issue by Srushhh1303** [python/cpython#111845]
# Bug report

### Bug description:

import tkinter as tk

Output :-
Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
How to resolve this error ??
Receiving this error on MacOs new update of Sonoma

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment]
Duplicate of #110950
