### ISSUE TITLE
Unify branches and deopts in the tier 2 IR.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#111848]
The basic premise of optimizing traces is that most branches are highly biased.
So we use `DEOPT_IF` to branch in the uncommon case.
However in the optimizer we may want to move work to exit branches, which needs jumps.
Unifying branches and jumps also simplifies the tier 2 interpreter *and* the JIT compiler.

So, let's merge jumps and branches, as follows:
* Convert most, if not all jumps in the tier 2 code to `DEOPT_IF`s in `bytecodes.c`
* Convert deopts into jumps internally to allow work like `SET_IP` to be sunk into exit branches.

See also https://github.com/python/cpython/issues/111610

### Linked PRs
* gh-111849
* gh-112045
* gh-112065
* gh-112274

**Comment by brandtbucher** [comment]
Yes please! :)

**Comment by gvanrossum** [comment]
Do you expect more to happen here? It looks complete. :-)
