### ISSUE TITLE
Rename `Py_NOGIL` to a positive term

### ISSUE THREAD

**Issue by hugovk** [python/cpython#111863]
From the [PEP 703 acceptance](https://discuss.python.org/t/pep-703-making-the-global-interpreter-lock-optional-in-cpython-acceptance/37075?u=hugovk):

> We want to avoid negatives in terms and flags and such, so we won’t get into double-negative terrain (like we do when we talk about ‘non no-GIL’). We’d like a positive, clear term to talk about the no-GIL build, and we’re suggesting ‘free-threaded’. (Relatedly, that’s why the build mode/ABI letter is ‘t’ and not ‘n’; that change was already made.)

`Py_NOGIL` is a user-facing macro, let's rename it to something positive.

Maybe `Py_DISABLE_GIL` or `Py_FREE_THREADED`?

cc @colesbury

### Linked PRs
* gh-111864
* gh-112300
* gh-112307

**Comment by corona10** [comment]
Maybe it will affect to https://github.com/python/cpython/pull/111571, Sam may need to make decision what should go first :)
But I agree with updating the term to follow SC's decision anyway.

**Comment by hugovk** [comment]
Yep, fully defer to Sam to merge things in whatever order he likes, including closing https://github.com/python/cpython/pull/111864 if he wants to do it another way.

**Comment by itamaro** [comment]
up to Sam of course, but perhaps invert it completely, and go with something like `Py_GIL` or `Py_WITH_GIL`?

**Comment by colesbury** [comment]
I commented on @hugovk's PR (https://github.com/python/cpython/pull/111864#issuecomment-1804090175).

Macros like `Py_GIL` or `Py_WITH_GIL` do not work well because they are not defined in older versions of Python (or pypy). That would make writing the `#if` pre-processor guards more difficult for extension code that targets multiple versions of Python.

**Comment by colesbury** [comment]
I put an issue in the steering council GitHub repo: https://github.com/python/steering-council/issues/214

**Comment by gvanrossum** [comment]
I propose "[multicore](https://github.com/python/steering-council/issues/214#issuecomment-1804321893)".

**Comment by hugovk** [comment]
The SC decision: `Py_GIL_DISABLED`

* https://github.com/python/steering-council/issues/214#issuecomment-1817942256

I've updated the PR.
