### ISSUE TITLE
Enum HOWTO doesn't render well on mobile

### ISSUE THREAD

**Issue by fipachu** [python/cpython#111895]
Specifically the purple sidebar on in section [Functional API](https://docs.python.org/3/howto/enum.html#functional-api). 
* The bar itself is hard to read. 
* Text is way wider than the rest of the site.
* Text renders in a different font size.

In Chrome devtools device mode the font size seems consistent, but the other problems still appear.

Tested in Safari on iPhone 12 mini, with docs for Python 3.12 and 3.13.

<details>
<summary>Screenshot</summary>

![zoomed_out](https://github.com/python/cpython/assets/80906036/27e2c3db-8c63-4c56-8ee8-bca5c8c12447)

</details>

### Linked PRs
* gh-111898
* gh-111908
* gh-111909

**Comment by hugovk** [comment]
It's reproducible on Chrome 119/Android 13/Samsung S22:

<details>
<summary>Mobile screenshot</summary>

![image](https://github.com/python/cpython/assets/1324225/b95bf499-de6a-4041-9e40-9cba58edd614)


</details>

It doesn't look great on desktop either (Chrome 119/macOS Ventura 13.6):

<details>
<summary>Desktop screenshot</summary>

![image](https://github.com/python/cpython/assets/1324225/1cd030f6-baea-4cb3-aa1d-e0e585e66847)

</details>

Here's the source, it's a "definition list":

https://github.com/python/cpython/blob/6f09f69b7f85962f66d10637c3325bbb2b2d9853/Doc/howto/enum.rst?plain=1#L610-L635

Any suggestions on what to replace it with? 

Perhaps a simple bulleted list?

<details>
<summary>Mobile screenshot</summary>

![image](https://github.com/python/cpython/assets/1324225/f180fb43-caef-4a5a-81fc-ae144a4fe0ef)


</details>


<details>
<summary>Desktop screenshot</summary>

![image](https://github.com/python/cpython/assets/1324225/f9da3944-b0e8-4778-8650-e85a359b648e)


</details>

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/111898.

**Comment by fipachu** [comment]
Thank you for picking it up @hugovk! And thanks for exposing me to:

<details><summary>this</summary>
<p>

and this:
https://github.com/python/cpython/blob/6f09f69b7f85962f66d10637c3325bbb2b2d9853/Doc/howto/enum.rst?plain=1#L1-L3

</p>
</details>

I have no idea what to use instead of definition list though. I'm not familiar with sphinx nor Python documentation guidelines.

**Comment by hugovk** [comment]
Let's go with https://github.com/python/cpython/pull/111898 then, thank you for reporting this!

**Comment by serhiy-storchaka** [comment]
Can we change the style of definition lists?

**Comment by hugovk** [comment]
Possibly in https://github.com/python/python-docs-theme or Sphinx?

In this case, I think part of the problem was the code block taking up a lot of extra (fixed) width, squashing the left part into a tiny space.

So I think the styling might be fine for normal definition lists? Let's revisit if we find a problem with "normal" ones.
