### ISSUE TITLE
libregrtest: Reduce number of imports at startup

### ISSUE THREAD

**Issue by vstinner** [python/cpython#111881]
Currently, when a test is run by ``./python -m test (...)``, the test starts with 170 modules already imported. The problem is that imports can have side effects and I would prefer to start tests in a "minimal environment".

Running a test with ``./python -m test (...)`` only imports 164 modules.

Example by adding ``Lib/test/test_x.py``:

```py
import sys
print(len(sys.modules))
```

Output:

```
vstinner@mona$ ./python -m test test_x
170

vstinner@mona$ ./python -m test -j1 test_x
164
```

I propose to try to make more imports lazy: only import the module the first time that it's needed, tests are rarely "performance sensitive". It may improve the "startup time".

### Linked PRs
* gh-111884
* gh-111885
* gh-111886
* gh-111887
* gh-111888
* gh-111889
* gh-111890
* gh-111893
* gh-111894
* gh-111902
* gh-112172

**Comment by arneja-arnav** [comment]
May I work on this issue? would love to take a crack at it.

**Comment by vstinner** [comment]
> May I work on this issue? would love to take a crack at it.

Yes, you can review proposed PRs and help to get them merged.

**Comment by vstinner** [comment]
I lost track of this change, so I just close it.
