### ISSUE TITLE
os.putenv() on Windows truncates value on an embedded NUL

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111841]
`os.putenv()` on Windows truncates a value containing an embedded null character.

```pycon
>>> import os
>>> os.putenv('xyz', 'abc\0def')
>>> os.system('''python.bat -c "import os; print(repr(os.environ['xyz']))"''')
Running Debug|x64 interpreter...
'abc'
0
```

`os.putenv()` and `os.unsetenv()` also truncate a name. It leads to OSError because it truncates before "=".

```pycon
>>> os.putenv('abc\0def', 'xyz')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    os.putenv('abc\0def', 'xyz')
OSError: [Errno 22] Invalid argument
>>> os.unsetenv('abc\0def')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    os.unsetenv('abc\0def')
OSError: [Errno 22] Invalid argument
```

### Linked PRs
* gh-111842
* gh-111966
* gh-111967

**Comment by vstinner** [comment]
Only the **value** is truncated if it contains embedded null character.

Python doesn't check for embedded null character in the variable name, but as you write, OSError is raised if the name is truncated. And Python rejects name which contains "=", so ``os.putenv('a=1\0', 'ignore')`` raises ValueError.
