### ISSUE TITLE
os.path.expanduser expands nonexistent users on Windows

### ISSUE THREAD

**Issue by pan324** [python/cpython#111847]
# Bug report

### Bug description:

```python
# Windows
>>> os.path.expanduser("~abcd")
'C:\\Users\\abcd'

# POSIX
>>> os.path.expanduser("~abcd")
'~abcd'
```

### CPython versions tested on:

3.11, 3.13

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
The expanduser [document](https://docs.python.org/3/library/os.path.html#os.path.expanduser) starts with
> return the argument with an initial component of ~ or ~user replaced by that user’s home directory.
It goes on to give separate details for Unix and Windows.  There is no indication that there is any check that could raise and exception, so it is returning the default directory for such a user (if there were to be one).  So I don't think that this is a bug.

**Comment by pan324** [comment]
You're absolutely right. How bizarre. I wasn't really looking for an exception but rather the original path being returned. It seems the issue is that there is no support for checking users on Windows, hence anything is treated as valid, whereas POSIX only lets through valid users. I don't think there are any use cases for expanding ~ into a nonexistent user directory regardless of OS.
