### ISSUE TITLE
SQLite3 connection hangs in infinite loop on windows with reserved filenames

### ISSUE THREAD

**Issue by stekow** [python/cpython#111851]
# Bug report

### Bug description:

There are some illegal filenames on Windows, such as 'CON', 'PRN', 'AUX', 'NUL', 'COM1', etc. If you make a sqlite3 connection with them, then there is no response or error message and you and end up in an infinite loop. 

```import sqlite3
sqlite3.connect('sqlite:///CON')
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
It is not a Python issue. The Python `sqlite3` module does not open files itself, it simply uses the Sqlite API. Please file a report on the Sqlite bug tracker.
