### ISSUE TITLE
No max_children in socketserver.ForkingMixIn documentation

### ISSUE THREAD

**Issue by AEErshov** [python/cpython#111872]
# Documentation

There is nothing about max_children attribute of socketserver.ForkingMixIn class in documentation.

### Linked PRs
* gh-118134

**Comment by aisk** [comment]
Also `timeout`, and `daemon_threads` for `ThreadingMixIn`.

And there is a `active_children` for `ForkingMixIn` asides there attributes, but this is for internal usage to store the current spawned processed. I think it should have a underscore before it's name, just like `_threads` attributes in `ThreadingMixIn`.
