### ISSUE TITLE
Wrong behavior of the groupby method

### ISSUE THREAD

**Issue by JakubZelek** [python/cpython#111985]
# Bug report

### Bug description:

```python
from itertools import groupby

x1 = ['E1', 'A', 'F', 'H']
x2 = ['F', 'E1', 'H', 'A']

f = {'E1': 'G3', 'A' : 'G1', 'H': 'G1', 'F': 'G2'}

def issue_map(lst):
    out_nodes_grouped_by_blob = {key: list(value) for key, value in groupby(lst, lambda n: f[n])}
    print(f'for {lst=} - {out_nodes_grouped_by_blob}')

issue_map(x1)
issue_map(x2)

print(f"set equality: {set(x1) == set(x2)}")

```

The result of the comparition:
![image](https://github.com/python/cpython/assets/72871011/b56a1139-251d-4a80-9c2c-a312623e142f)

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by gaogaotiantian** [comment]
According to the docs:

> Generally, the iterable needs to already be sorted on the same key function.

> The operation of [groupby()](https://docs.python.org/3/library/itertools.html#itertools.groupby) is similar to the uniq filter in Unix. It generates a break or new group every time the value of the key function changes (which is why it is usually necessary to have sorted the data using the same key function). That behavior differs from SQL’s GROUP BY which aggregates common elements regardless of their input order.

You need to sort the data based on the key function before using `groupby()`.

**Comment by Zeleczek-kodowniczek** [comment]
Sure, thank you for fast answer!
