### ISSUE TITLE
TextIOWrapper.reconfigure() crashes if encoding is not string or None

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111942]
# Crash report

### What happened?

Unlike to `TextIOWrapper` constructor, `TextIOWrapper.reconfigure()` does not check that the encoding argument is actually None or string. If it is not None, it calls `_PyUnicode_EqualToASCIIString` that only works with strings and crashes in debug build. There may be other similar errors in other arguments.

```pycon
>>> import sys
>>> sys.stdout.reconfigure(encoding=42)
Objects/unicodeobject.c:552: _PyUnicode_CheckConsistency: Assertion failed: PyType_HasFeature((Py_TYPE(((PyObject*)((op))))), ((1UL << 28)))
Enable tracemalloc to get the memory block allocation traceback

object address  : 0x55a2e3147ca8
object refcount : 4294967295
object type     : 0x55a2e3119f00
object type name: int
object repr     : 42

Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x00007fc99ee43740 (most recent call first):
  File "<stdin>-1", line 1 in <module>
Aborted (core dumped)
```

### CPython versions tested on:

3.10, 3.11, 3.12

### Linked PRs
* gh-111976
* gh-112058
* gh-112059
* gh-112061
* gh-112067
* gh-112085
* gh-112089
* gh-126542

**Comment by serhiy-storchaka** [comment]
Weird. The address sanitizer tests were passed in main and 3.12, but failed in 3.11. And I now can reproduce the failure locally in main.

The newly added tests exposed a bug in the `TextIOWrapper` constructor when pass a non-encodable "errors" argument.

**Comment by vstinner** [comment]
Nice thanks, thanks.

**Comment by encukou** [comment]
There's an issue with the 3.11 backport, in `textiowrapper_change_encoding`. Main had:

```diff
+    Py_INCREF(errors);
 ...
     Py_SETREF(self->encoding, encoding);
-    Py_SETREF(self->errors, Py_NewRef(errors));
+    Py_SETREF(self->errors, errors);
```

but in 3.11 this is:

```diff
+    Py_INCREF(errors);
...
     Py_INCREF(errors);
     Py_SETREF(self->encoding, encoding);
     Py_SETREF(self->errors, errors);
```
i.e. there's an extra incref, but it looks -- at least to Git -- like the change that removes `Py_NewRef` was already applied.

This was not caught because [`test_io` *refleaks* tests were ineffective on 3.11](https://github.com/python/cpython/pull/126478#issuecomment-2462070264).

I'm preparing a fix.
