### ISSUE TITLE
Argument Clinic: Add support for PEP 703's critical sections (`Py_BEGIN_CRITICAL_SECTION()`)

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111903]
# Feature or enhancement

PEP 703 in large part relies on replacing the GIL with fine grained per-object locks. The primary way to acquire and release these locks is through the critical section API (https://github.com/python/cpython/issues/111569). It would be helpful if argument clinic could auto generate the API calls in the binding code when specified.

For example, the [`bufferedio.c`](https://github.com/python/cpython/blob/6f09f69b7f85962f66d10637c3325bbb2b2d9853/Modules/_io/bufferedio.c) will require per-object locking around most calls for thread-safety in `--disable-gil` builds.

As an example, the `_io._Buffered.close` function is written as:

https://github.com/python/cpython/blob/6f09f69b7f85962f66d10637c3325bbb2b2d9853/Modules/_io/bufferedio.c#L523-L529

We might add a `@critical_section` directive to designate that argument clinic should generate `Py_BEGIN_CRITICAL_SECTION()` and `Py_END_CRITICAL_SECTION()` in the binding code before calling `_io__Buffered_close_impl`.

```c
/*[clinic input]
@critical_section
_io._Buffered.close
[clinic start generated code]*/

static PyObject *
_io__Buffered_close_impl(buffered *self)
/*[clinic end generated code: output=7280b7b42033be0c input=d20b83d1ddd7d805]*/
```

The generated binding code in `bufferedio.c.h` would then look like:

```c
static PyObject *
_io__Buffered_close(buffered *self, PyObject *Py_UNUSED(ignored))
{
    PyObject *return_value = NULL;

    Py_BEGIN_CRITICAL_SECTION(self);
    return_value = _io__Buffered_close_impl(self);
    Py_END_CRITICAL_SECTION();

    return return_value;
}
```

Note that `Py_BEGIN/END_CRITICAL_SECTION()` are no-ops in the default build.

### Linked PRs
* gh-111904
* gh-112251

**Comment by corona10** [comment]
cc @erlend-aasland

**Comment by colesbury** [comment]
I've updated the issue to use AC's existing "directive" feature and syntax.
