### ISSUE TITLE
socket module does not include all getnameinfo flags

### ISSUE THREAD

**Issue by adder32** [python/cpython#111995]
The `socket` module does not include `NI_IDN` `getnameinfo` flag.

See: https://man7.org/linux/man-pages/man3/getnameinfo.3.html

### Linked PRs
* gh-111994

**Comment by sambhavnoobcoder** [comment]
hi respected @moderators . I am a beginner here and am looking to make some open source contributions . it would be great if you could point me to the right direction to a good issue to make my first open source contribution to this repo . thanks

**Comment by gpshead** [comment]
@sambhavnoobcoder I suggest starting with https://www.python.org/dev/core-mentorship/ if you haven't already.
