### ISSUE TITLE
unicode: make ucnhash_capi initialization thread-safe in `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111972]
# Feature or enhancement

The `_PyUnicode_Name_CAPI` provides functions to get the name for a given Unicode character code and vice versa. It is lazily initialized and stored in the per-interpreter `_Py_unicode_state`:

https://github.com/python/cpython/blob/3932b0f7b1566374427daa8bc47203032015e350/Include/internal/pycore_unicodeobject.h#L425-L432

The initialization of the `ucnhash_capi` isn't thread-safe without the GIL. (There can be a data race on reading and writing `ucnhash_capi`).

Mostly for my own reference, here are the similar modifications in the `nogil-3.12` fork: https://github.com/colesbury/nogil-3.12/commit/5d006db9fa

### Linked PRs
* gh-112249

**Comment by Eclips4** [comment]
This seems quite easy 😄 
Please, take a look at the #112249.

**Comment by erlend-aasland** [comment]
Resolved by #112249
