### ISSUE TITLE
asyncio task tests misbehave if _asyncio C module is missing

### ISSUE THREAD

**Issue by CendioOssman** [python/cpython#111959]
# Bug report

### Bug description:

Remove the built _asyncio C module, then run the asyncio task tests:

```console
$ build/python -m test -v test.test_asyncio.test_tasks
```

You'll get flooded with a bunch of:

```console
Warning -- Unraisable exception
Exception ignored in: <function BaseTaskTests.test_task_del_collect.<locals>.Evil.__del__ at 0x7fe44d00dee0>
Traceback (most recent call last):
  File "/local/home/ossman/cpython/Lib/test/test_asyncio/test_tasks.py", line 138, in __del__
AttributeError: 'NoneType' object has no attribute 'collect'
```

The issue seems to be that this destructor is being run doing interpreter shutdown, so the imported `gc` is now gone (`None`).

A workaround is:

```diff
diff --git a/Lib/test/test_asyncio/test_tasks.py b/Lib/test/test_asyncio/test_tasks.py
index 4dfaff847e..5e333b545f 100644
--- a/Lib/test/test_asyncio/test_tasks.py
+++ b/Lib/test/test_asyncio/test_tasks.py
@@ -134,7 +134,8 @@ async def coro():
     def test_task_del_collect(self):
         class Evil:
             def __del__(self):
-                gc.collect()
+                if gc is not None:
+                    gc.collect()
 
         async def run():
             return Evil()
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by gvanrossum** [comment]
I wouldn't call that a crash. I don't have access to Linux; on my macOS I just get this:
```
~/cpython$ ./python.exe -m test test.test_asyncio.test_tasks
Using random seed: 532536042
0:00:00 load avg: 4.47 Run 1 test sequentially
0:00:00 load avg: 4.47 [1/1] test.test_asyncio.test_tasks
test test.test_asyncio.test_tasks failed -- Traceback (most recent call last):
  File "/Users/guido/cpython/Lib/test/test_asyncio/test_tasks.py", line 2933, in test_asyncio_module_compiled
    import _asyncio
ModuleNotFoundError: No module named '_asyncio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/guido/cpython/Lib/test/test_asyncio/test_tasks.py", line 2935, in test_asyncio_module_compiled
    self.fail('_asyncio module is missing')
AssertionError: _asyncio module is missing

test.test_asyncio.test_tasks failed (1 failure)

== Tests result: FAILURE ==

1 test failed:
    test.test_asyncio.test_tasks

Total duration: 7.3 sec
Total tests: run=269 failures=1 skipped=684
Total test files: run=1/1 failed=1
Result: FAILURE
```
which seems not unreasonable (we'd like the tests to fail if `_asyncio` is accidentally not built).

**Comment by CendioOssman** [comment]
I was trying to check my modifications to the pure Python version of `asyncio/tasks.py` (which seem to get overridden by the C version normally), but it was very difficult to see the actual test results as I got pages upon pages of those warnings/errors.

So this issue made development rather difficult for me at least. :/

**Comment by gvanrossum** [comment]
Can you just submit your fix as a PR?

**Comment by CendioOssman** [comment]
Sure. But I'm very uncertain if that's really a fix and not just papering over something more serious. Is there anyone more familiar with that code who could have a look?

**Comment by gvanrossum** [comment]
> Is there anyone more familiar with that code who could have a look?

Asyncio seems forever without enough maintainers. This seems an odd use case (why delete `_asyncio`?) so I prefer to spend what little time I have for asyncio on more important issues.

**Comment by ordinary-jamie** [comment]
Hi @CendioOssman -- disclaimer: I'm a newbie with `asyncio` looking to learn how to contribute :) 

Like Guido said, it's an odd use case since changes must be done to `_asyncio` anyways... but if you really need to do it, I can offer you an import hack:

```py
# run_asyncio_test_without_c_ext.py
import sys
import importlib.abc

class ImportInterceptor(importlib.abc.MetaPathFinder):
    def __init__(self, modules):
        self._modules = modules

    def find_spec(self, fullname, path, target=None):
        if fullname in self._modules:
            raise ImportError


# Must be set before importing asyncio.
# Comment out if you wish to use the real asyncio.
sys.meta_path = [ImportInterceptor(['_asyncio'])] +  sys.meta_path

import asyncio

# Check that we're using the Python asyncio, not the _asyncio module.
assert asyncio.futures.Future.__module__ == "asyncio.futures"

# Comment out `sys.meta_path = ...` and this assertion will be True
# assert asyncio.futures.Future.__module__ == "_asyncio"

# Run the tests...
import unittest

loader = unittest.TestLoader()
asyncio_tests = loader.discover('Lib/test/test_asyncio')
unittest.TextTestRunner().run(asyncio_tests)
```

Then, simply running the script from the TLD:

```bash
cd cpython/
./python.exe run_asyncio_test_without_c_ext.py
```

You'll notice a lot more skips since a lot of test cases only run if the C extension module is loaded via:

```py
@unittest.skipUnless(hasattr(tasks, '_CTask'),
                       'requires the C _asyncio module')
```

How it works: You can see that [`tasks.py`](https://github.com/python/cpython/blob/cde1335485b7bffb12c378d230ae48ad77d76ab1/Lib/asyncio/tasks.py#L390-L396), `futures.py`, etc. all try to import the C extension module; if an `ImportError` is raised the overriding of the python definition doesn't happen.

Hope this helps :)

**Comment by kumaraditya303** [comment]
> Sure. But I'm very uncertain if that's really a fix and not just papering over something more serious. Is there anyone more familiar with that code who could have a look?

if you want to test pure python code then `sys.modules['_asyncio']=None` trick works, you can use it. I don't think we need to fix anything here as without c acdelerator the tests would fail.
