### ISSUE TITLE
Use critical sections to protect I/O objects (in `--disable-gil` builds)

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111965]
# Feature or enhancement

The I/O objects, like [`io.BufferedIOBase`](https://docs.python.org/3/library/io.html#io.BufferedIOBase), [`io.TextIOWrapper`](https://docs.python.org/3/library/io.html#io.TextIOWrapper), and [`io.StringIO`](https://docs.python.org/3/library/io.html#io.StringIO) have internal state that would not be thread-safe without the GIL.

We should be able to mostly use Argument Clinic's (AC) support for "critical sections" to guard methods on these objects. For operations that don't use AC, we can either convert them to use AC or write the `Py_BEGIN_CRITICAL_SECTION`/`Py_END_CRITICAL_SECTION` manually.

For context, here are the similar modifications in the `nogil-3.12` fork, but the implementation in CPython 3.13 will be a bit different (no need for extra locks, use the syntax from #111903):
* https://github.com/colesbury/nogil-3.12/commit/ffade9d6f6 (PR by @Mayuresh16)
* https://github.com/colesbury/nogil-3.12/commit/5b83c16dcd (PR by @aisk)
* https://github.com/colesbury/nogil-3.12/commit/6323ca60f9 (PR by @aisk)

### Linked PRs
* gh-112116
* gh-112193
* gh-112298

**Comment by colesbury** [comment]
Yes, thanks, it should say `TextIOWrapper`. I've edited the issue.

**Comment by sobolevn** [comment]
Sorry, what about `_pyio`?

**Comment by colesbury** [comment]
@sobolevn, any specific concerns? I didn't see anything that looked like it required locking, but I may have missed something.

**Comment by sobolevn** [comment]
No, no specific questions :)
I hoe that our new tests for threaded IO will catch any potential differences between two implementations 👍

**Comment by Mayuresh16** [comment]
@colesbury Hi, I would like to give it a try for `io.BufferedXXX` implementation and will be happy to start my first open-source contribution with CPython based on my knowledge and understanding of the tools. 😅

**Comment by sobolevn** [comment]
Looks like it is done! 🎉
