### ISSUE TITLE
Document better assignment expression parentheses requirements

### ISSUE THREAD

**Issue by lysnikolaou** [python/cpython#111944]
# Feature or enhancement

### Proposal:

Should we maybe thinks about allowing unparenthesized top-level assignment expressions. It came up on ipython/ipython#14214 that people would like to have something like that, especially in REPLs, in order to be able to assign a value to a variable and have it be displayed afterwards. I played around with the parser a bit and the change to allow this is very straight-forward.

We could also discuss adding it behind a flag or only enable it on the REPL.

Behavior on main:
```python
❯ ./python.exe
Python 3.13.0a1+ (heads/main:baeb7718f8, Nov 10 2023, 12:05:38) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a := 3
  File "<stdin>", line 1
    a := 3
      ^^
SyntaxError: invalid syntax
```

New behavior:
```python
❯ ./python.exe
Python 3.13.0a1+ (heads/main-dirty:baeb7718f8, Nov 10 2023, 12:20:20) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a := 3
3
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-111977
* gh-112010
* gh-112011

**Comment by lysnikolaou** [comment]
@terryjreedy I don't think the `type-bug` label applies here. The current behavior is correct according to the specification in PEP 572.

**Comment by terryjreedy** [comment]
Top level assignment expressions work when parenthesized.
```
>>> (a := 3)
3
>>> a
3
```
According to the [expression doc](https://docs.python.org/3/reference/expressions.html#assignment-expressions)
this should not be needed.  The discrepancy would usually be seen as a bug.

According to the [PEP](https://peps.python.org/pep-0572/), the behavior is intended, with the parenthesized form discouraged.  See the first example under exceptional cases.  So it seems that the doc should be fixed unless it is intended that the discouraged form not be documented.  But I believe this would be unusual.

To support a feature addition, argue against the PEP's prohibition rationale.

@gvanrossum

**Comment by lysnikolaou** [comment]
I'm sorry, I might not have made myself clear.

I understand all that. I agree that the doc should be improved to include that top-level walruses need parentheses. But that should probably be a different issue. What I would like to do with this one, is start a discussion on whether we should lift that restriction.

The PEP says:
> Unparenthesized assignment expressions are prohibited at the top level of an expression statement. [...] This rule is included to simplify the choice for the user between an assignment statement and an assignment expression – there is no syntactic position where both are valid.

I agree with the concept of "There should be one way to do it", but I would think that, in the context of a REPL, assignment statements and assignment expressions do two slightly different things. And I'm asking whether others agree so that this can be lifted, since it's also a very easy change to implement on the parser side.

**Comment by gvanrossum** [comment]
I am not in favor of lifting the restriction. I don’t want there to be two top level forms of assignment.

**Comment by lysnikolaou** [comment]
> I am not in favor of lifting the restriction. I don’t want there to be two top level forms of assignment.

What if it could only be enabled with an `ast.PyCF_ALLOW_TOP_LEVEL_WALRUS` kind of flag in `ast.parse`/`compile` in `single` mode? Would that make a difference?

**Comment by gvanrossum** [comment]
That would only confuse users — what’s valid in one context wouldn’t be valid in another context.

**Comment by AlexWaygood** [comment]
> That would only confuse users — what’s valid in one context wouldn’t be valid in another context.

I agree -- I think we should keep the REPL consistent with Python in other contexts, wherever possible

**Comment by ericvsmith** [comment]
I don't think there's much chance of this succeeding, but if you want to pursue it you should open up a discussion on https://discuss.python.org/c/ideas/6

**Comment by terryjreedy** [comment]
I labelled as I did because the code and doc issues are not independent.  If we change 'main' to allow `>>> a:=3`, then the doc becomes correct in 'main' and should not be changed there.  If status quo continues, as I currently support and also expect, then the doc should be changed in main as well as in maintenance versions.  PR submitted.

**Comment by terryjreedy** [comment]
There are two separately mentioned parenthesis requirements in the PEP missing from the Reference manual: `(a := 1)` instead of `a := 1` for an expression statement, and `b = (a := 1)` instead of `a = b: = 1` for an assignment expression as the right-hand side of an assignment statement.  Eliminating the latter has not been requested and IMO definitely should not be.  My PR adds both requirements.  I plan to merge it within a day, and if the former restriction were to be dropped sometime, the doc could be revised again along with the code revision.  (And that would only be a feature change for 'main'.)

**Comment by lysnikolaou** [comment]
> I don't think there's much chance of this succeeding, but if you want to pursue it you should open up a discussion on https://discuss.python.org/c/ideas/6

Since there's consensus that this isn't something we want to support, I won't pursue this further.

Thanks folks for your input and @terryjreedy for fixing the docs issue.
