### ISSUE TITLE
Installation of Python3.12 failed in FreeBSD environement

### ISSUE THREAD

**Issue by Soujanya459** [python/cpython#111941]
# Bug report

### Bug description:

I was able to install python versions till python3.11.5 .. BUt now I'm trying to install python3.12 in FreeBSD environment, it is getting failed with below error..  

```python

cc -pthread -DUSE_ZLIB_CRC32 -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/inclush/ese/usr/local/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-functn -fvisibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/binascii.c -o Modules/binascii.o
cc -pthread -shared -Wl,-rpath=/var/crash/ese/usr/local/lib -L/var/crash/ese/usr/local/lib    Modules/binascii.o -lz  -o Modules/binascii.c
cc -pthread  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/include -I//var/crash/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration idden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/_bz2module.c -o Modules/_bz2module.o
cc -pthread -shared -Wl,-rpath=/var/crash/ese/usr/local/lib -L/var/crash/ese/usr/local/lib    Modules/_bz2module.o -lbz2  -o Modules/_bz2.c
cc -pthread  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/include -I//var/crash/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration idden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/_lzmamodule.c -o Modules/_lzmamodule.o
cc -pthread -shared -Wl,-rpath=/var/crash/ese/usr/local/lib -L/var/crash/ese/usr/local/lib    Modules/_lzmamodule.o -llzma  -o Modules/_lzmso
cc -pthread  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/include -I//var/crash/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration idden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/zlibmodule.c -o Modules/zlibmodule.o
cc -pthread -shared -Wl,-rpath=/var/crash/ese/usr/local/lib -L/var/crash/ese/usr/local/lib    Modules/zlibmodule.o -lz  -o Modules/zlib.cpy
cc -pthread -DUSE_NDBM -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/include -I//usr/local/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-desibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/_dbmmodule.c -o Modules/_dbmmodule.o
cc -pthread -shared -Wl,-rpath=/var/crash/ese/usr/local/lib -L/var/crash/ese/usr/local/lib    Modules/_dbmmodule.o   -o Modules/_dbm.cpytho
cc -pthread -I/usr/local/include/readline -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/use -I//var/crash/ese/usr/local/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=ion-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/readline.c -o Modules/readline.o
./Modules/readline.c:39:12: fatal error: 'readline/readline.h' file not found
#  include <readline/readline.h>
           ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /var/crash/ese/work/python/Python-3.12.0
onefs-soujanya-50-1# 

```

### CPython versions tested on:

3.12

### Operating systems tested on:

Other

**Comment by Soujanya459** [comment]
[Python3_12Installation.txt](https://github.com/python/cpython/files/13318018/Python3_12Installation.txt)

Please find installation log in the attached file

**Comment by Soujanya459** [comment]
As installation itself is failing. we are yet to build our python project on this OS.. 
Please  look into this issue asap

**Comment by furkanonder** [comment]
@Soujanya459 Which version of FreeBSD are you trying to install Python on? I tried your configuration command, but it seems invalid.
```sh
freebsd@generic:~/Python-3.12.0 % ./configure --prefix=/var/crash/ese/usr/local --with-openssl=/var/crash/ese/usr/local --with-ensurepip=install --enablGS="-Wl,-rpath=/var/crash/ese/usr/local/lib"
configure: error: unrecognized option: `--enablGS=-Wl,-rpath=/var/crash/ese/usr/local/lib'
Try `./configure --help' for more information
```
My environment;
```sh
freebsd@generic:~/Python-3.12.0 % uname -a
FreeBSD generic 13.2-RELEASE FreeBSD 13.2-RELEASE releng/13.2-n254617-525ecfdad597 GENERIC arm64
freebsd@generic:~/Python-3.12.0 % 
```

**Comment by Soujanya459** [comment]
I ran the command... Still the issue is same 
FreeBSD onefs-soujanya-50-1 12.0-CURRENT FreeBSD 12.0-CURRENT amd64

```
# ./configure --prefix=/var/crash/ese/usr/local --with-openssl=/var/crash/ese/usr/local --with-ensurepip=install --enable-shared LDFLAGS="-Wl,-rpath=/var/crash/ese/usr/local/lib"
checking build system type... **x86_64-unknown-freebsd12.0**
checking host system type... x86_64-unknown-freebsd12.0

--
cc -pthread -I/usr/local/include/readline -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall -I//var/crash/ese/usr/local/includ
e -I//var/crash/ese/usr/local/include  -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-functi
on-declaration -fvisibility=hidden  -I./Include/internal  -I. -I./Include   -fPIC -fPIC -c ./Modules/readline.c -o Modules/readline.o
./Modules/readline.c:39:12: fatal error: 'readline/readline.h' file not found
#  include <readline/readline.h>
           ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1
```

**Comment by ngie-eign** [comment]
@Soujanya459 : the lang/python312 port does not exist upstream FreeBSD yet.

Could you please raise this issue through bugs.freebsd.org instead / reach out to freebsd-python@FreeBSD.org ?

FreeBSD does not ship with GNU readline by default due to licensing restrictions (it's an optional port). It ships with [editline](https://github.com/troglobit/editline). I opened up an issue a while back to add editline support and it's been iterated on by various people, but libeditline support still does not exist upstream. Given that Apple also doesn't ship readline, some configure arguments being passed are likely incorrect.

Why isn't this being installed via a port and instead being installed via a source tarball?

**Comment by ngie-eign** [comment]
I stand corrected -- libedit/editline support does seem to be present in cpython as of the last few releases: https://github.com/python/cpython/issues/57710 .
The configure arguments might need adjusting or autoconf detection might need adjusting.

**Comment by Soujanya459** [comment]
Here I'm trying to install Python in custom location.. and I have installed openssl, zlib, sqlite  in custom location /var/crash/ese/usr/local .. 
I want them to be picked up during python installation so I'm trying to Install Python via source code.. 
but anyway i don't want this readline feature in my application.. 
usually I do delete readline.cpython-311.so file after Python installation...


"The configure arguments might need adjusting or autoconf detection might need adjusting. " - So can you please suggest me what shall I give as options to get rid of this error  ?

**Comment by erlend-aasland** [comment]
cc. @corona10

**Comment by Soujanya459** [comment]
Please check this issue asap.. I'm blocked to build my application

**Comment by Soujanya459** [comment]
I'm uploading the python3.11.5 installation log.. where it installed fine..

[Python3_11_5Installation Steps.txt](https://github.com/python/cpython/files/13392034/Python3_11_5Installation.Steps.txt)

I see there is difference while checking for libreadline,  Can you check and let me know is there any option I can provide during configure command to fix this error.. 

![image](https://github.com/python/cpython/assets/84155017/4cb91375-094e-47a5-9843-b9c8beebaa1f)

**Comment by ngie-eign** [comment]
@Soujanya459 Please reach out to your internal support team for more assistance.
You aren’t running a release version of FreeBSD and I don’t think folks in this group (cpython) can effectively assist you with your support queries since they will not likely be able to reproduce your build environment without disclosing more information which might be protected from release to anonymous third-parties.

**Comment by Soujanya459** [comment]
Actualy in our custom OS missing header file exist in /usr/local/include. I will check with them what is causing this.. 

Now going ahead with workaround,  like building python by providing option `--without-readline'.
 Python3.12 installed successfully
