### ISSUE TITLE
Add signatures for some builtins

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111999]
# Feature or enhancement

Signature can be manually added for some builtin functions and classes that do not use Argument Clinic.

### Linked PRs
* gh-112000
* gh-119540
* gh-119543

**Comment by serhiy-storchaka** [comment]
This change exposed a bug in a test: #112001.

**Comment by JelleZijlstra** [comment]
The signature for `.format_map()` is now incorrect:

```
>>> str.format_map.__text_signature__
'($self, /, mapping)'
>>> "x".format_map(mapping={})
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    "x".format_map(mapping={})
    ~~~~~~~~~~~~~~^^^^^^^^^^^^
TypeError: str.format_map() takes no keyword arguments
```

**Comment by serhiy-storchaka** [comment]
Thank you for catching this @JelleZijlstra.

**Comment by encukou** [comment]
Is there more to do here?

**Comment by JelleZijlstra** [comment]
Thanks @serhiy-storchaka for the quick fix!
