### ISSUE TITLE
Use per-thread freelists in `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111968]
# Feature or enhancement

CPython uses freelists for frequently allocated Python objects, like `dict`, `list`, and `slice`. There freelists are generally stored in the per-interpreter state, which is not thread-safe without the GIL. In `--disable-gil` builds, the freelists should be stored in the per-thread state (i.e., `PyThreadState`). I think we probably want to keep the freelists in the interpreter state for the default build. This will probably require some refactoring.

Freelists:
* `float`
* `slice` (`slice_cache`)
* `tuple`
* `list` 
* `dict` (`PyDictKeysObject` and `PyDictObject`)
* `generator` (`value_freelist` and `asend_freelist`)
* `PyContext`

For context, here are similar changes in the `nogil-3.12` fork, but I expect the changes in CPython 3.13 to be a bit different:
* https://github.com/colesbury/nogil-3.12/commit/07f5f8c318
* https://github.com/colesbury/nogil-3.12/commit/2a4c17e896

### Linked PRs
* gh-113584
* gh-113886
* gh-113919
* gh-113921
* gh-113929
* gh-113972
* gh-114122
* gh-114189
* gh-114270
* gh-114323
* gh-114581
* gh-114899
* gh-115329
* gh-115505
* gh-115546
* gh-136673

**Comment by Yaro1** [comment]
Hi!
I'm new here, but if you don't mind I would like to take that issue

**Comment by colesbury** [comment]
Hi @Yaro1, thanks for volunteering. You are welcome to take this on, but I don't think it's a great first issue. There are some subtleties and it also depends on https://github.com/python/cpython/pull/112776.

**Comment by Yaro1** [comment]
Got it, thanks.
Can I take please in that case some of the issues from https://github.com/python/cpython/issues/108219 ?

**Comment by colesbury** [comment]
I don't think there are any good issues right now that are scoped out and not blocked on other work.

**Comment by Yaro1** [comment]
Okay, got it. Thank you

**Comment by corona10** [comment]
@colesbury I would like to take a look at this issue, Is there any pending issues that are related to this issue?

**Comment by colesbury** [comment]
@corona10, thanks! I think the issues were fixed (problems with `PyThreadState_Clear()` being called by the wrong interpreter)

**Comment by corona10** [comment]
https://github.com/python/cpython/pull/113584 will introduce seamless management of freelists that runtimes do not need to care about the implementation detail :)

```mermaid
graph TD;
    PerThread --> FreeList;
    PerInterpreter --> FreeList;
    GC --> PerThread;
    GC --> PerInterpreter;
    _PyFreeListState --> PerThread;
    _PyFreeListState --> PerInterpreter;
    Runtime --> _PyFreeListState;
    list --> Runtime
    tuple --> Runtime
    slice --> Runtime
    float --> Runtime
    dict --> Runtime
    generator --> Runtime
    PyContext --> Runtime
```

**Comment by corona10** [comment]
I should clean up some headers even if all free-lists are migrated.

**Comment by corona10** [comment]
TODO: https://github.com/python/cpython/pull/114323#pullrequestreview-1846171825
cc @ericsnowcurrently

**Comment by ericsnowcurrently** [comment]
As noted in review comments in gh-114323, I think the following should be adjusted:

* [ ] change the various type-specific `_PyXXX_Fini()` signatures back to taking a single `PyInterpreterState *` argument
* [ ] change the type-specific struct names, e.g. `struct _Py_float_state`, to something more specific, e.g. `struct _Py_float_freelist`
* [ ] change the struct name `_Py_freelist_state` to `_Py_freelists` or, better, `_PyObject_freelists`
* [ ] change `PyInterpreterState.freelist_state` to `PyInterpreterState.freelists` or, even better, to `PyInterpreterState.object_state.freelists`
* [ ] split `struct _Py_dictkeys_freelist` out of `struct _Py_dict_freelist`

**Comment by colesbury** [comment]
Regarding `_PyXXX_Fini`, I think we should have one top-level function to clear free-lists (`_Py_ClearFreeLists()`) instead of routing some calls via `_PyXXX_Fini`. Right now these two code paths do the same thing: [`_Py_ClearFreeLists`](https://github.com/python/cpython/blob/587d4802034749e2aace9c00b00bd73eccdae1e7/Python/pystate.c#L1464-L1469) and in [`finalize_interp_types`](https://github.com/python/cpython/blob/587d4802034749e2aace9c00b00bd73eccdae1e7/Python/pylifecycle.c#L1788-L1794), which makes it prone to bugs when adding new freelists. I think that will leave a bunch of the `_PyXXX_Fini` functions empty.

**Comment by ericsnowcurrently** [comment]
I'd support calling `_Py_ClearFreeLists()` in `finalize_interp_types()` (at the end).  If some `_PyXXX_Fini()` is consequently empty then we should drop the function.

FWIW, I also think we should change that name to `_PyObject_ClearFreeLists()` (or maybe `_PyObject_ClearFreelists()`), to make it clear they are object-specific freelists.

**Comment by corona10** [comment]
Final diagram:

```mermaid
graph TD;
    PerThread --> FreeList;
    PerInterpreter --> FreeList;
    GC -- if free-threaded --> gc_freethreading;
    GC -- if default build --> gc_gil;
    gc_freethreading --> PerThread;
    gc_gil --> PerInterpreter;
    _Py_object_freelists -- if free-threaded --> PerThread;
    _Py_object_freelists -- if default build --> PerInterpreter;
    Runtime -- _Py_object_freelists_GET --> _Py_object_freelists;
    list --> Runtime;
    tuple --> Runtime;
    slice --> Runtime;
    float --> Runtime;
    dict --> Runtime;
    dictkey --> Runtime;
    async_gen --> Runtime;
    _PyContext --> Runtime;
   object_stack --> Runtime;
```

**Comment by corona10** [comment]
@ericsnowcurrently @colesbury 
Thanks for all the feedback on this issue!
