### ISSUE TITLE
json: make "memo" dict local to scan_once call

### ISSUE THREAD

**Issue by colesbury** [python/cpython#111928]
# Feature or enhancement

The `Modules/_json.c` parser is mostly stateless (or the state is immutable). The one exception is the "memo" dictionary, which is used to avoid duplicate `PyUnicodeObject` instances for the same JSON C strings.

https://github.com/python/cpython/blob/289af8612283508b67d7969d7182070381b4349b/Modules/_json.c#L696-L700

The `memo` dictionary is already cleared after each call `scan_once`:

https://github.com/python/cpython/blob/289af8612283508b67d7969d7182070381b4349b/Modules/_json.c#L1118

We should move the creation and destruction of the `memo` dict to the invocation of `scan_once` instead of having it as part of the module state. This will avoid contention on the dictionary locks in `--disable-gil` builds if multiple threads are concurrently parsing JSON strings.

For an example modification, see https://github.com/colesbury/nogil-3.12/commit/964bb33962.

### Linked PRs
* gh-112005

**Comment by aisk** [comment]
I just took a look at the example modification, and run the test on it locally and it succeded. I think there is no more works to do, so just cherry-picked it and made a PR.

If anyone think there need improves, I want to investigate on it.

**Comment by colesbury** [comment]
Thanks @aisk!
