### ISSUE TITLE
Run test_posix on Windows

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#111912]
When I searched for a place for tests for gh-111841, I have found that they already exist, but in `test_posix` which is skipped on Windows.

The simplest way is to make `test_posix` running on Windows. It turned out that most tests are already compatible with Windows, except this test and yet one test that tests for Posix-specific constants.

### Linked PRs
* gh-111913
* gh-111953
* gh-111954

**Comment by hugovk** [comment]
Fixed and backported, looks like we can close this. Thanks!
