### ISSUE TITLE
Contradicting statement in c-api/stable.rst

### ISSUE THREAD

**Issue by DerSchinken** [python/cpython#112092]
# Documentation
> So, code compiled for Python 3.10.0 will work on 3.10.8 and vice versa, but will need to be compiled separately for 3.9.x and 3.10.x.
> \- [https://docs.python.org/3/c-api/stable.html](https://docs.python.org/3/c-api/stable.html#stable:~:text=So%2C%20code%20compiled%20for%20Python%203.10.0%20will%20work%20on%203.10.8%20and%20vice%20versa%2C%20but%20will%20need%20to%20be%20compiled%20separately%20for%203.9.x%20and%203.10.x.)

This contradicts itself, tho it could be that the `Unless documented otherwise` case is meant with it.     
But if so it would need a better clarification 

### Linked PRs
* gh-112093
* gh-114260
* gh-114261

**Comment by hugovk** [comment]
"Unless documented otherwise" does not add much clarity, and I don't think there's a contradiction here. 

What it's saying is:

* If you only want to support 3.10.x versions, like 3.10.0, 3.10.1, and 3.10.8, then you only need to compile for one of them, and it will work for all. 

* If you want to support 3.9.x and 3.10.x, like 3.9.0, 3.9.1, 3.9.5, 3.10.0, 3.10.1, and 3.10.8, then you need to compile twice: once for 3.9.x and once for 3.10.x.

Does that help explain it?

**Comment by DerSchinken** [comment]
I get what this is trying to say. But how I read it, and others that I've asked if I overlooked something, is "Code compiled for Python 3.10.0 will work across all versions of that minor release (3.10), but will need to be compiled seperately on 3.10.x" which is contradicting itself.

WIth "Unless documented otherwise" I meant `Unless documented otherwise, Python’s C API is covered by the Backwards Compatibility Policy`, which is redundant so I guess I'll just remove it

**Comment by ronaldoussoren** [comment]
> I get what this is trying to say. But how I read it, and others that I've asked if I overlooked something, is "Code compiled for Python 3.10.0 will work across all versions of that minor release (3.10), but will need to be compiled seperately for 3.10.x" which is contradicting itself.

But that's not what the documentation says, you're leaving out some words and that introduces the contradiction. That said, I might be possible to rephrase this for more clarity, for example (with changes in bold):

> So, code compiled for Python 3.10.0 will work on 3.10.8 and vice versa, but will need to be **re**compiled **~~separately~~** for 3.9.x and **3.11.x**.

**Comment by DerSchinken** [comment]
> [...] you're leaving out some words and that introduces the contradiction.

Ok so let's not leave any words out:
> So, code compiled for Python 3.10.0 will work on 3.10.8 and vice versa, but will need to be compiled separately for 3.9.x and 3.10.x.

Why then do I need to compile my 3.10.0 code for 3.10.x separately if `CPython’s Application Binary Interface (ABI) is forward- and backwards-compatible across a minor release` is true?

I'm getting the feeling that my understanding of English isn't good enough, so it may not be contradicting, but I think changing that last part from `[...] compiled separately for 3.9.x and 3.10.x.` to `[...] compiled separately for any other minor version.` would avoid any of that wrong thinking that I and others apparently have here
