### ISSUE TITLE
`signal` page claims its classes are new in version 3.5 when they are new in 3.11

### ISSUE THREAD

**Issue by Spiffyk** [python/cpython#112036]
# Documentation

The `signal` documentation at <https://docs.python.org/3.11/library/signal.html#signal.Signals> claims that the classes like `signal.Signals`, `signal.Handlers`, etc. are *New in version 3.5*, but in fact they were introduced in 3.11; older versions do not have these (see e.g. <https://docs.python.org/3.10/library/signal.html#signal.Signals>).

**Comment by hugovk** [comment]
For reference, the "New in version 3.5" documentation was added in issue https://github.com/python/cpython/issues/72393 / PR https://github.com/python/cpython/pull/28628, which happened in the 3.11 docs and wasn't backported to older versions of the docs.

However, the constants were converted to `IntEnum`s in commit https://github.com/python/cpython/commit/24e837f23126eab7486a77f3cb51b982226adb70 which was in Python 3.5.

So the 3.11 (and later) documentation is correct; it's just that 3.10 and older versions of the docs are missing this info, and those branches are only accepting security fixes (https://devguide.python.org/versions/) so we can't update them any more.
