### ISSUE TITLE
datetime.isoformat() produces non-standards compliant offsets

### ISSUE THREAD

**Issue by antonagestam** [python/cpython#112057]
# Bug report

### Bug description:

Some examples:

```pycon
>>> import datetime, zoneinfo
>>> datetime.datetime(1734, 3, 7, 12, 19, 34, 394447, fold=1, tzinfo=zoneinfo.ZoneInfo(key='Atlantic/St_Helena')).isoformat()
'1734-03-07T12:19:34.394447-00:16:08'
>>> datetime.datetime(1734, 3, 2, 12, 14, 19, 131284, tzinfo=zoneinfo.ZoneInfo(key='posix/Asia/Chungking')).isoformat()
'1734-03-02T12:14:19.131284+08:05:43'
>>> datetime.datetime(1064, 12, 3, 5, 12, 10, 77900, tzinfo=zoneinfo.ZoneInfo(key='right/Asia/Khandyga')).isoformat()
'1064-12-03T05:12:10.077900+09:02:13'
```

I believe those are not valid ISO datetime strings, due to the appended seconds to the offset. I cannot find any references to the standard that mention support for anything else than hours and minutes in that place. I believe the right formatting here would be to arithmetically apply the seconds part of the offset to the time itself.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
https://docs.python.org/3/library/datetime.html?highlight=isoformat#datetime.datetime.isoformat says:

> Return a string representing the date and time in ISO 8601 format

https://en.wikipedia.org/wiki/ISO_8601#Other_Specifications says:

> ISO 8601-2:2019 allows for general durations for time offsets. For example, more precision can be added to the time offset with the format '<time>±[hh]:[mm]:[ss].[sss]' or '<time>±[n]H[n]M[n]S' as below.

Does that help?

**Comment by antonagestam** [comment]
@hugovk Yes, that helps, thanks for pointing this out! 🙏

Do you happen to know the history, was this added in the 2019 edition?
