### ISSUE TITLE
_Py_c_sum, _Py_c_diff, etc - were removed from Python.h

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#112019]
See #106339 and #106320.  But these functions are documented as public: https://docs.python.org/3/c-api/complex.html#complex-numbers-as-c-structures

I think c38c666 should be partially reverted and ``_Py_c_abs`` - documented.

On another hand, quick github search shows very little examples of using above functions.  See also https://github.com/python/cpython/issues/106320#issuecomment-1633302147.  So, in a long term I propose to deprecate this API and related functions (PyComplex_FromCComplex/PyComplex_AsCComplex).  Who knows, maybe someday we could use ``<complex.h>``...

### Linked PRs
* gh-112021
* gh-112107

**Comment by skirpichev** [comment]
CC @vstinner

**Comment by vstinner** [comment]
If these functions are useful, I would prefer to make them public.

Previous discussion about this private API: https://github.com/python/cpython/issues/106320#issuecomment-1633302147

**Comment by vstinner** [comment]
@skirpichev: Do you use these functions? Do you know a project using these functions? A code search on PyPI top 5,000 projects only found 1 line using `_Py_c_pow()` in the numba project.

**Comment by skirpichev** [comment]
@mdickinson, should we expose these functions and details of the Py_complex struct, what do you think?

> If these functions are useful, I would prefer to make them public.

Code search shows they aren't used too much.

> @skirpichev: Do you use these functions?

Not outside of CPython itself.

PS: (I'm moving discussion from #106320)

> The C99 complex API is documented at: https://en.cppreference.com/w/c/numeric/complex

It seems, see e.g. (https://discuss.python.org/t/33433/23, https://github.com/llvm/llvm-project/issues/8904), that none of popular compilers (icc maybe an exception) support this extension correctly.

**Comment by vstinner** [comment]
> @mdickinson, should we expose these functions and details of the Py_complex struct, what do you think?

Members of the `Py_complex` structure are public since the structure was added to Python 1.4 by commit f9fca9252f64a93b4598615c504011fa385333ae in 1996. The structure was called `complex` and then was renamed to `Py_complex`.

The `Py_complex` functions are already documented but have a `_Py` prefix.

**Comment by skirpichev** [comment]
Also they take struct by value, a bit strange API.

**Comment by vstinner** [comment]
I restored removed `_Py_c` complex functions in https://github.com/python/cpython/pull/112115. The initial issue is fixed, so I close the issue.

Later, we should consider deprecating these functions and make them fully internal. I restored these functions because they are documented.

**Comment by skirpichev** [comment]
> Later, we should consider deprecating these functions and make them fully internal.

Maybe we could keep this issue for that?

**Comment by vstinner** [comment]
> Maybe we could keep this issue for that?

I prefer to wait until a migration path is decision on how to get rid of private functions (which were reverted in Python 3.13. alpha2): https://github.com/capi-workgroup/api-evolution/issues/24
