### ISSUE TITLE
Misleading docstring for `_codecs.utf_8_encode` and `_codecs.utf_8_decode`

### ISSUE THREAD

**Issue by darkfoxprime** [python/cpython#112009]
# Documentation

The docstring for `_codecs.utf_8_encode` reads:

```
>>> help(_codecs.utf_8_encode)
Help on built-in function utf_8_encode in module _codecs:

utf_8_encode(str, errors=None, /)
```

This is misleading, because `errors` is _not_ a keyword argument (as is implied by the python language syntax of that signature).

```
>>> _codecs.utf_8_encode('foo', errors='strict')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: _codecs.utf_8_encode() takes no keyword arguments
```

Similarly with `_codecs.utf_8_decode` and I assume with other codecs in that module.

**Comment by terryjreedy** [comment]
The '/' in the signature means that the preceding arguments are position only, which in this case means 'no keyword arguments.  Please ask about possible bugs elsehwhere, such as https://discuss.python.org/c/users/7.
