### ISSUE TITLE
Using sys.monitoring seems to add spurious `RERAISE` which make it hard to find actual `RERAISE` clauses.

### ISSUE THREAD

**Issue by fabioz** [python/cpython#112086]
# Bug report

### Bug description:

@markshannon The `RERAISE` which was added for the events is not specified in https://peps.python.org/pep-0669/ (from the PEP I had understood that any clause raising either a new or existing exception would give a `RAISE`), yet, in the actual implementation there's a `RERAISE` and it can appear not only on `RERAISE` statements but also spuriously, so, it's hard to know when one should stop because an exception was raised in code and when it should be ignored.

Maybe I'm misunderstanding things... what I'd like to know is how to know that an exception is raised from the `raise` statement (which is not appearing as a `RAISE` event), while not getting the spurious `RERAISE` which seem to be also generated.

i.e.:

In a case such as:

```
def method_raise():
    raise RuntimeError('err1')

def method_2():
    try:
        method_raise()
    except:
        raise RuntimeError('err2')

def method():
    try:
        method_2()
    except:
        pass

method()
```

The output would be:

```
raise method_raise 22 err1
raise method_2 16 err1
raise method_2 46 err2
reraise method_2 52 err2
raise method 16 err2
```

So, from this you can see that there are 2 raises and one reraise, which would be fair if I could just handle the `RAISE` events.

But then on:

```
def method_raise():
    raise RuntimeError('err1')

def method_2():
    try:
        method_raise()
    except:
        raise

def method():
    try:
        method_2()
    except:
        pass
```

the output is:

```
raise method_raise 22 err1
raise method_2 16 err1
reraise method_2 26 err1
reraise method_2 32 err1
raise method 16 err1
```

But now it seems I must also handle the `RERAISE` events, but I cannot differentiate the 2nd reraise which seems spurious (as there should be a way to know that there was 1 raise due to it being raised from the `method_raise` and just one more from the actual `raise` statement, yet, there's one spurious `RERAISE` which I can't differentiate from the previous `RERAISE` due to the `raise` statement).

Below is a full test case using pytest and doing the setup as needed (the file must be named `test_sys_monitoring.py` to work properly).

```python
import sys
import pytest
import threading
DEBUGGER_ID = sys.monitoring.DEBUGGER_ID
monitor = sys.monitoring

def _disable_monitoring():
    if monitor.get_tool(DEBUGGER_ID) == 'pydevd':
        sys.monitoring.set_events(sys.monitoring.DEBUGGER_ID, 0)
        monitor.register_callback(DEBUGGER_ID, monitor.events.PY_START , None)
        monitor.register_callback(DEBUGGER_ID, monitor.events.PY_RESUME, None)
        monitor.register_callback(DEBUGGER_ID, monitor.events.LINE, None)
        monitor.register_callback(DEBUGGER_ID, monitor.events.RAISE, None)
        sys.monitoring.free_tool_id(DEBUGGER_ID)


@pytest.fixture
def with_monitoring():
    monitor.use_tool_id(DEBUGGER_ID, 'pydevd')
    yield
    _disable_monitoring()


def test_exceptions(with_monitoring):
    monitor.set_events(DEBUGGER_ID, monitor.events.RAISE | monitor.events.RERAISE)

    found = []

    def _on_raise(code, instruction_offset, exc):
        if code.co_filename.endswith('test_sys_monitoring.py'):
            print('raise', code.co_name, instruction_offset, str(exc))
            found.append(('raise', code.co_name, str(exc)))

    def _on_reraise(code, instruction_offset, exc):
        if code.co_filename.endswith('test_sys_monitoring.py'):
            print('reraise', code.co_name, instruction_offset, str(exc))
            found.append(('reraise', code.co_name, str(exc)))

    monitor.register_callback(DEBUGGER_ID, monitor.events.RAISE , _on_raise)
    monitor.register_callback(DEBUGGER_ID, monitor.events.RERAISE , _on_reraise)

    def method_raise():
        raise RuntimeError('err1')

    def method_2():
        try:
            method_raise()
        except:
            raise

    def method():
        try:
            method_2()
        except:
            pass

    method()
    assert found == [
        ('raise', 'method_raise', 'err1'),
        ('raise', 'method_2', 'err1'),
        # There should be only one 'reraise' here.
        ('reraise', 'method_2', 'err1'),
        ('reraise', 'method_2', 'err1'),
        ('raise', 'method', 'err1'),
    ]
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
I believe `RERAISE` just means an existing exception is raised again, it could be triggered from an empty `raise` statement, or other places where the interpreter needs to do the exception handling, in your case, after the `except` block.

I also don't think there's a `reraise` statement.

The existance of `RERAISE` event is more than "the interpreter details", for example:

```python
def method():
    try:
        raise Exception("Some error")
    finally:
        print("Finally block")
```

It's obvious that in the `try` block, an exception is raised. However, after the `finally` block finishes, the same exception has to be raised to pass this exception to the caller. This reraise is concrete and observable.

Back to your question - do you want to just catch the raises caused by an explicit `raise` written by the user? You'll have to do source parsing anyway as the exception event will passed to the callers and trigger until it's caught right?

**Comment by fabioz** [comment]
The problem is that even when parsing, it's not possible to disambiguate the 2 `RERAISE` events because they happen at the same line.

i.e.: in the case:

```python

def _on_raise(code, instruction_offset, exc):
    if code.co_filename.endswith('sys_monitoring.py'):
        print('raise', code.co_name, instruction_offset, str(exc), sys._getframe(1).f_lineno)
        found.append(('raise', code.co_name, str(exc)))

def _on_reraise(code, instruction_offset, exc):
    if code.co_filename.endswith('sys_monitoring.py'):
        print('reraise', code.co_name, instruction_offset, str(exc), sys._getframe(1).f_lineno)
        found.append(('reraise', code.co_name, str(exc)))

monitor.register_callback(DEBUGGER_ID, monitor.events.RAISE , _on_raise)
monitor.register_callback(DEBUGGER_ID, monitor.events.RERAISE , _on_reraise)

def method_raise():
    raise RuntimeError('err1')

def method_2():
    try:
        method_raise()
    except:
        raise

def method():
    try:
        method_2()
    except:
        pass

method()
```

The output with lines is:

```
raise method_raise 22 err1 48
raise method_2 16 err1 52
reraise method_2 26 err1 54
reraise method_2 32 err1 54
raise method 16 err1 58
```

So, you can see that although the instruction is different, the line is the same -- so, parsing can help in determining if it's a handled or unhandled exception, but the exception breakpoint will effectively pause twice in that same place regardless of the case.

Maybe some internal bookkeeping can help that, but managing that state can be challenging to know when it generated something which should be reported vs when that should just be silently ignored.

**Comment by fabioz** [comment]
> Back to your question - do you want to just catch the raises caused by an explicit raise written by the user? You'll have to do source parsing anyway as the exception event will passed to the callers and trigger until it's caught right?

Not necessarily just written by the user. in the example below I'd expect `RAISES` in the following places:

```
def method_raise():
    raise RuntimeError('err1')  # RAISES

def method_2():
    try:
        method_raise()  # RAISES
    except:
        raise  # RAISES

def method():
    try:
        method_2()  # RAISES
    except:
        pass

method()
```

The problem is that on `method_2` there is just 1 `RAISES` and 2 `RERAISES` and it's not possible to easily disambiguate (in my mind it should be 2 `RAISES` for the expected cases and the `RERAISE` shouldn't even be needed, although it wouldn't hurt to have it when leaving the function/block due to the exception if someone cares about that).

**Comment by gaogaotiantian** [comment]
I believe the current behavior is to be compatible with what `sys.settrace` used to do.

If you do this:

```python
import sys

def trace_func(*args):
    print(args)
    return trace_func


def f():
    try:
        raise ValueError()
    except ValueError:
        raise

sys.settrace(trace_func)

try:
    f()
except:
    pass
```

You will only get one exception event with `raise ValueError()`, not the `raise` in `except` block. You'll only get the exception events if it's not reraised (changing `raise` to `raise ValueError()`).

So the answer would probably be - you can't do that without PEP 669 anyway. And `except: raise` is not considered a `RAISE`, it's a `RERAISE` (that will not trigger an `exception` event) and has been like that for a while.

If you do want to categorize that bare `raise` into an explicit raise event, you'll have to do it in the software logic as it's not how Python considers it.

**Comment by fabioz** [comment]
Ok, I'm closing this issue. After tinkering more with it, I think I'll be able to cover what I need with `UNWIND` and `RAISE`.
