### ISSUE TITLE
quit() and exit() don't work in interactive help

### ISSUE THREAD

**Issue by catafest** [python/cpython#112007]
# Bug report

### Bug description:

I tried to use quit and exit to return to the interactive Python shell but these not work. I need to use Ctr +Z.
```python
Python 3.13.0a1 (tags/v3.13.0a1:ad056f0, Oct 13 2023, 09:51:17) [MSC v.1935 64 bit (AMD64)] on win32
# Add a code block here, if required
help> exit()
No Python documentation found for 'exit()'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.

help> quit()
No Python documentation found for 'quit()'.
Use help() to get the interactive help utility.
Use help(str) for help on the str class.
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-112017
* gh-112047
* gh-112048

**Comment by hugovk** [comment]
Working as expected on macOS, installed using the "macOS 64-bit universal2 installer" from https://www.python.org/downloads/release/python-3130a1/

```console
❯ python3.13
Python 3.13.0a1 (v3.13.0a1:ad056f03ae, Oct 13 2023, 06:35:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

❯ python3.13
Python 3.13.0a1 (v3.13.0a1:ad056f03ae, Oct 13 2023, 06:35:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

❯ python3.13
Python 3.13.0a1 (v3.13.0a1:ad056f03ae, Oct 13 2023, 06:35:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D

❯ python3.13
Python 3.13.0a1 (v3.13.0a1:ad056f03ae, Oct 13 2023, 06:35:05) [Clang 13.0.0 (clang-1300.0.29.30)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
[1]  + 65866 suspended  python3.13
```

Also built from latest `main`:

```console
❯ ./python.exe
Python 3.13.0a1+ (heads/main:b2af50cb02, Nov 12 2023, 18:24:40) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> exit()

❯ ./python.exe
Python 3.13.0a1+ (heads/main:b2af50cb02, Nov 12 2023, 18:24:40) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> quit()

❯ ./python.exe
Python 3.13.0a1+ (heads/main:b2af50cb02, Nov 12 2023, 18:24:40) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> ^D

❯ ./python.exe
Python 3.13.0a1+ (heads/main:b2af50cb02, Nov 12 2023, 18:24:40) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>
[2]  + 65953 suspended  ./python.exe
```

**Comment by hugovk** [comment]
> ```python
> help> exit()
> No Python documentation found for 'exit()'.
> Use help() to get the interactive help utility.
> Use help(str) for help on the str class.
> ```

But this bit is interesting, have you run `help()` first to enter the interactive help?

Do you have the `PYTHONSTARTUP` env var set and pointing to a startup script?

**Comment by danik292** [comment]
It works for me.

Windows 11 Home
23H2
22631.2506

**Comment by danik292** [comment]
@catafest Exactly what Windows are you using?

**Comment by serhiy-storchaka** [comment]
The title was wrong and misleading. The correct title is "quit() and exit() don't work on interactive help".

And this is right. When you enter an interactive help, you get a long introduction message that includes: ```To quit this help utility and return to the interpreter, just type "quit".``` Not `quit()`, simply `quit`.

**Comment by zware** [comment]
This isn't version or platform specific.  As Serhiy mentioned, there's no bug here from the perspective of an understanding of the code.  However, it does strike me as being new user unfriendly, and we may want to improve it.  There's an easy fix: just add `quit()` to the `if request.lower() in ('q', 'quit'): break` line in `pydoc.Helper.interact`.  Another option would be to check for `()` in the input and either silently strip it or emit a "you probably didn't mean this here" message.

**Comment by terryjreedy** [comment]
I think that this sentence, 'To quit this help utility and return to the interpreter, just type "quit".' in [pydoc.Helper.intro](https://github.com/python/cpython/blob/main/Lib/pydoc.py#L2075) should be moved to the end after a blank line.  It is now in the middle of things to do other than quitting.  I suspect that it was once the last sentence before more was added.  I will submit a PR with this and a couple of other re-groupings.

**Comment by terryjreedy** [comment]
To me, changing this string in the pydoc module is equivalent to a doc change and should be backported.  test_pydoc still passes as is, and I don't think anyone else should depend on the exact content.  Any disagreement?

**Comment by terryjreedy** [comment]
I added 'q' as an alternative.  I had not idea that it worked until I read the code quoted above by 'zware'.

**Comment by terryjreedy** [comment]
I think that this revision should be sufficient for now.  The previously not mentioned 'q<enter>', now easy to see, is the easiest way to exit.
