### ISSUE TITLE
Make `dict` objects thread-safe in `--disable-gil` builds

### ISSUE THREAD

**Issue by colesbury** [python/cpython#112075]
We are going to need a variety of techniques to make dictionaries thread-safe in `--disable-gil` builds. I expect this to be implemented across multiple PRs.

For context, here is the change from the `nogil-3.12` fork, but things might be done a bit differently in CPython 3.13: https://github.com/colesbury/nogil-3.12/commit/d896dfc8db

1) Most operations should acquire the dictionary object lock using the critical section API.
2) Dictionary global version counter should use atomic increments 
3) `PyDictKeysObject` needs special handling (see below)
4) `PyDictOrValues` needs special handling (see below)
5) Accessing a single element should optimistically avoid locking for performance

In general, we want to avoid making changes which hurt the performance of the default build. The "critical sections" are no-ops in the default build, but we will need to take care with other changes. Some may be behind `#ifdef` guards.

### `PyDictKeysObject`

Note that `PyDictKeysObject` is *NOT* a `PyObject` subclass.

We need a mutex in `PyDictKeysObject` because multiple threads may concurrently insert keys into shared `PyDictKeysObject`. The mutex is only used for modifications to "shared" keys; non-shared keys rely on the locking for the dict object.

In `--disable-gil` builds, we want to avoid refcounting shared `PyDictKeysObject` for performance and thread-safety reasons. Instead shared keys objects should be freed during cyclic GC. (Non-shared keys don't need reference counting because they "owned" by a single dict object.) We may want to consider making this change for both the default build and `--disable-gil` builds to make maintenance easier if there is not a negative perf impact.

### `PyDictOrValues`

`PyDictOrValues` is the "managed" dict in some PyObject pre-headers. We need some locking/atomic operations to handle the transition between `PyDictValues*` and storing a `PyDictObject*`

### Optimistically Avoid Locking

See https://peps.python.org/pep-0703/#optimistically-avoiding-locking.

### Linked PRs
* gh-112247
* gh-114256
* gh-114508
* gh-114512
* gh-114543
* gh-114568
* gh-114629
* gh-114741
* gh-114742
* gh-114768
* gh-114778
* gh-114931
* gh-115108
* gh-115109
* gh-115786
* gh-115855
* gh-116087
* gh-116336
* gh-116344
* gh-116620
* gh-117528
* gh-117529
* gh-117824
* gh-118499
* gh-118676
* gh-119288
* gh-121545
* gh-129336
* gh-139737

**Comment by chgnrdv** [comment]
I'd like to work on it.

**Comment by chgnrdv** [comment]
@colesbury , I made the PR #112247 that covers the most obvious cases. Lots of methods are still to be converted, mostly the ones that access a single element and expected to optimistically avoid locking.

**Comment by DinoV** [comment]
Can you explain more what you were thinking about freeing them during cyclic GC then?  Given that Python's GC drives down reference counts I'm not 100% sure how that'd work.  The only thing I can imagine working is that we maintain a separate list of all shared keys and note which ones weren't visited during a full GC, although maybe you had something better in mind :)

**Comment by colesbury** [comment]
> The only thing I can imagine working is that we maintain a separate list of all shared keys and note which ones weren't visited during a full GC.

That's the basic idea, but the list only needs to bother with shared keys for types that were deallocated. If the type is still alive, then the shared keys must be alive too.

The strategy in `nogil-3.12` was:

1) Shared keys objects are eligible for collection only after the containing type is freed. When that happens, they get enqueued in a per-interpreter linked list of maybe-dead shared keys (called `tracked_shared_keys`):
https://github.com/colesbury/nogil-3.12/blob/nogil-3.12/Include/internal/pycore_dict_state.h#L48

2) To support this, shared keys objects have some extra state. They are actually [`PyDictSharedKeysObject`](https://github.com/colesbury/nogil-3.12/blob/cedde4f5ec3759ad723c89d44738776f362df564/Include/internal/pycore_dict.h#L113-L118), which embed a `PyDictKeysObject`.

3) During GC, we [mark any shared keys](https://github.com/colesbury/nogil-3.12/blob/cedde4f5ec3759ad723c89d44738776f362df564/Modules/gcmodule.c#L446-L455 referenced by a `dict` as live.

4) Later in the GC, we loop over the maybe-dead list (`tracked_shared_keys`), and free any shared keys that were not marked as live.

The collection is simpler than general PyObject collection because keys objects are private data structures that can only be referenced by dicts.

**Comment by DinoV** [comment]
> @DinoV is the dict work finished? Should we close this issue?

I think so, anything else that comes up would just be a bug.
