### ISSUE TITLE
`typing.py` contains two doctests that are not executed, ever

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#112155]
# Feature or enhancement

`typing.py` contains at least two doctests: https://github.com/python/cpython/blob/81ab0e8a4add53035c87b040afda6d554cace528/Lib/typing.py#L3377-L3414

But, they are not ever executed.

I propose to add a `DocTestSuite` to `test_typing` to run these tests.

Note, that this is related but not similar to https://github.com/python/cpython/pull/111682

### Linked PRs
* gh-112156
* gh-112230
* gh-112231

**Comment by AlexWaygood** [comment]
The change has been applied to `main`. `Lib/typing.py` has no doctests on the 3.12 or 3.11 branches, so there's no need to backport this.

Thanks @sobolevn!
