### ISSUE TITLE
Provide strong reference version of API for PyWeakref_GetObject

### ISSUE THREAD

**Issue by corona10** [python/cpython#112188]
PEP-703 explains the risky situation of borrowed reference API.
For working on https://github.com/python/cpython/issues/111926, I think that we should introduce a new API with strong reference that was named `PyWeakref_FetchObject` from the PEP.
But to follow the recent convention, the API name will be `PyWeakref_GetObjectRef`.

Since SC approved the PEP, there would be no issue with adding this API.
However I want to listen to opinions from a few core devs before working on the task.

@encukou @colesbury @vstinner

**Comment by colesbury** [comment]
I think @vstinner already added `PyWeakref_GetRef` that returns a strong reference.

**Comment by corona10** [comment]
> I think @vstinner already added PyWeakref_GetRef that returns a strong reference.

Oh I see, then we close the issue.

**Comment by vstinner** [comment]
> I think @vstinner already added PyWeakref_GetRef that returns a strong reference.

I'm living in the future! By the way, the beginning of my article https://vstinner.github.io/c-api-dict-getitemref.html tells about this API :-)
