### ISSUE TITLE
Apostrophe in wrong place

### ISSUE THREAD

**Issue by LyleZiegelmiller** [python/cpython#112166]
# Documentation

In [https://docs.python.org/3/tutorial/controlflow.html#positional-only-parameters](url) it states, "Looking at this in a bit more detail, it is possible to mark certain parameters as positional-only. If positional-only, the **parameters’** order matters, and the parameters cannot be passed by keyword".

The apostrophe should be between the 'r' and the 's' in the word "parameter's".

**Comment by AlexWaygood** [comment]
No, the apostrophe is in the correct place. The rule is that if it's a plural posessive, the apostrophe should come after the 's'. https://www.bbc.co.uk/bitesize/articles/zx9ydxs#zx63khv
