### ISSUE TITLE
Typo in docstring for override decorator from `typing` module.

### ISSUE THREAD

**Issue by Qua27** [python/cpython#112152]
# `typing` module documentation

## Typo description
A typo in docstring for `override` decorator. Under `Usage::` we see the following code.
```python
class Base:
    def method(self) -> None: ...
        pass

class Child(Base):
    @override
    def method(self) -> None:
        super().method()
```

Both `...` and `pass` are used in `Base`'s class method. Since `...` has already been used, `pass` statement does not relate to the method at all, causing `IndentationError`.

## Suggested solution: remove `...`
```python
class Base:
    def method(self) -> None:
        pass

class Child(Base):
    @override
    def method(self) -> None:
        super().method()
```

https://github.com/python/cpython/blob/985679f05d1b72965bfbed99d1499c22815375e4/Lib/typing.py#L3348

### Linked PRs
* gh-112158
* gh-112162

**Comment by Qua27** [comment]
@sobolevn, I'm excited to make my first contribution here, and I appreciate your understanding as I navigate through the process. If there's anything specific I should keep in mind or if you have any feedback, please feel free to let me know. Thanks for welcoming newcomers like me!

**Comment by sobolevn** [comment]
Thank *you* for your report and williness to fix the problem :)

Nothing important for this specific issue that I can think about.
For future contributions, you can read the devguide: https://devguide.python.org
