### ISSUE TITLE
Complex Number String Representation

### ISSUE THREAD

**Issue by conor-oneill-2** [python/cpython#112176]
### Bug description:

There's a minor bug in the display of how complex numbers are printed to the terminal. When displaying a complex number to the terminal, if the real part is 0, then just the imaginary number is displayed.

However, if the real part is -0, then both the real and imaginary parts are displayed, when only the imaginary part should be displayed.

Here's an easy method to reproduce the bug:
```python
>>> 1j
1j
>>> 1j*-1
(-0-1j)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
It's displaying the real part as negative zero, which has some meaning.

**Comment by conor-oneill-2** [comment]
I can't think of a use case where one would want to distinguish between the value being 0 and -0. Python in general (from what I've seen) has tried to avoid having both 0 and -0 as separate objects wherever possible, and removing this edge case where the behaviour is different would be consistent with that goal. For instance, if you tried to initialise the value of the real part manually to be -0, Python automatically converts it to 0 for you.

```python
>>>-0-1j
-1j
```

**Comment by ericvsmith** [comment]
For reals, Python does support negative zeros.
```pycon
>>> -0.0
-0.0
```
Complex numbers are built on reals.

```pycon
>>> (-0.0-1j)
(-0-1j)
```

**Comment by conor-oneill-2** [comment]
Hmmm...

OK, that was a mistake, I hadn't realised that. I'm still not sure I see a use case for having 0.0-1j and -0.0-1j display differently in the example I gave above, since they come up as equal if you test for equality, but if this way really is more consistent in the Python Standard Library, then I can close the issue.
