### ISSUE TITLE
Off-by-one index error in __main__.py doc

### ISSUE THREAD

**Issue by vanyolos** [python/cpython#112165]
Very minor issue, the '2' here should be '3' on the RHS of the comparison (given we really want to return sys.argv[2] from the ternary).

<img width="635" alt="image" src="https://github.com/python/cpython/assets/135147320/77b4c680-0c6e-48e1-9642-6e2fa55f8bae">

https://docs.python.org/3.10/library/__main__.html

### Linked PRs
* gh-112183
* gh-112184
* gh-112185

**Comment by hugovk** [comment]
If you run the example as:
```sh
python3 -m bandclass my-name
```
Then `sys.argv` contains `['/private/tmp/bandclass/__main__.py', 'my-name']`

So do we want this?

```python
student_name = sys.argv[1] if len(sys.argv) >= 2 else ''
```

**Comment by vanyolos** [comment]
yes, that should be the fix indeed.
Can you pls make the fix/PR? I have no idea how to do it, new to github and this was first time ever reading official python docs. But you gotta start somewhere

**Comment by terryjreedy** [comment]
I'm making the PR, but if you want to learn to do it, start with https://devguide.python.org/.
