### ISSUE TITLE
Tkinter - images transparency on Rocky Linux 9

### ISSUE THREAD

**Issue by angrodm** [python/cpython#112151]
# Bug report

### Bug description:

When loading images the colors have some sort of alpha or masking applied with whatever is behind the image. My test_logo.img is a blue square with white text and a red star on it. If the screen behind the resulting window is a dark color then the colors in the image are "washed" out looking. If the screen behind is white then the image just shows a white square. As you move the window around you can see the image change based on what is behind. If I have it straddle a program with a dark background and a program with a white background the colors of the image are split along the line so it is on a per pixel basis that this is occurring.

```python
import tkinter as tk
from tkinter import PhotoImage

class Window:
    
    def __init__(self, image):
        self.image = image
        self.root = tk.Tk()
        self.widgets()
        self.root.mainloop()

    def widgets(self):
        self.img = PhotoImage(file=self.image)
        label = tk.Label(self.root, image=self.img)
        label.pack()

image_path = "scratchpad/resources/images/test_logo.png"
Window(image_path)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by chrstphrchvz** [comment]
I am not certain I understand the issue being described. It sounds something which affects Tcl/Tk and not Tkinter specifically. But I am also not aware how Tcl/Tk could cause this issue; I am used to Tk windows being opaque, and so I would expect this kind of issue to affect other widgets and not just photo images.

Are you able to provide screenshots of the issue? What desktop environment, display server, and window manager are you using?

**Comment by angrodm** [comment]
I am using Python 3.11.2 (main, Sep 12 2023, 00:00:00) with tkinter 8.6.10. As far as the OS goes it is Rocky Linux 9.2 (Blue Onyx) with Gnome version 40.4.0, Windowing System X11
![tkinter_error](https://github.com/python/cpython/assets/132912656/15a8e644-368e-474a-9819-2d2adf962d35)
. Attached is a screenshot showing the issues.

You are correct in that it might not be Tkinter specifically as I am not familiar with the underpinnings of Tkinter and debugging what level the issue is at. I tested the same code on Windows and it appears to work with no issues there.

Here is a screenshot showing the issue.

**Comment by chrstphrchvz** [comment]
Thanks for the info and screenshot. Now that I think of it, I want to say I have seen a similar issue in Tcl/Tk with VcXsrv, but which I have not reported nor investigated enough to know what is likely causing it. I think it has something to do with certain X visual color depths causing strange window “stacking” behavior, so I think it could be an X server issue rather than due to Tcl/Tk or the window manager. Screenshot where an image of Earth appears behind an xterm window, except for partially bleeding though black text in xterm (similar to how the blue image background appears through filename text in other window of your screenshot):
![Screenshot 2023-08-24 141448](https://github.com/python/cpython/assets/7941193/caf2e210-f816-49d2-88f6-60702f482135)



I do not know if it this is the same issue as yours, but it might be if a similar workaround applies (specify something other than `'default'` as the `visual` option to `tkinter.Toplevel()`, such as `tkinter.Toplevel(…, visual='best')`; the list of options is described by https://www.tcl-lang.org/man/tcl/TkLib/GetVisual.htm#M5 ). Still, that would mean this is not a Tkinter issue and is possibly better discussed elsewhere.

**Comment by chrstphrchvz** [comment]
I would also be curious what is returned by `self.root.winfo_visualsavailable(includeids=True)` and `self.root.winfo_visualid()`.

**Comment by terryjreedy** [comment]
Thank you both for the images of strange image behavior on *nix.  Very likely no a tkinter issue, so closing.  My Windows answers to the questions:
```
>>> import tkinter as t
>>> r = t.Tk()
>>> r.winfo_visualsavailable(includeids=True)
[('truecolor', 32, 0)]
>>> r.winfo_visualid()
'0x0'
```
@angrodm You are welcome to post yours even after closing.

**Comment by angrodm** [comment]
I was trying to do what yall suggested and got the following results.
```python
>>> import tkinter as tk
>>> r = tk.Tk()
>>> r.winfo_visualsavailable(includeids=True)
[('truecolor', 32, 78), ('truecolor', 32, 919), ('truecolor', 32, 920), ('truecolor', 32, 921), ('truecolor', 32, 922), ('truecolor', 32, 923), ('truecolor', 32, 924), ('truecolor', 32, 925), ('truecolor', 32, 926), ('truecolor', 32, 927), ('truecolor', 32, 928), ('truecolor', 32, 929), ('truecolor', 32, 930), ('truecolor', 32, 931), ('truecolor', 32, 932), ('truecolor', 32, 933), ('truecolor', 32, 934), ('truecolor', 32, 935), ('truecolor', 32, 936), ('truecolor', 32, 937), ('truecolor', 32, 938), ('truecolor', 32, 939), ('truecolor', 32, 940), ('truecolor', 32, 941), ('truecolor', 32, 942), ('truecolor', 32, 943), ('truecolor', 32, 944), ('truecolor', 32, 945), ('truecolor', 32, 946), ('truecolor', 32, 947), ('truecolor', 32, 33), ('truecolor', 32, 34)]
>>> r.winfo_visualid()
'0x21'
```

I wasn't able to get the toplevel working with the image on it so I reworked my example to the below.

```python
import tkinter as tk
from tkinter import PhotoImage

win = tk.Tk()
win.geometry("700x500")
frame = tk.Frame(win, width=600, height=400)
frame.pack()
frame.place(anchor="center", relx=0.5, rely=0.5)
img = PhotoImage("scratchpad/resources/images/test_logo.png")
label = tk.Label(frame, image=img)
label.pack()
win.mainloop()
```
I verified I had the same issue and tried running it with the again but replacing the Frame initialization with each of the following:
```python
frame = tk.Frame(win, width=600, height=400, visual="best")  # same results
frame = tk.Frame(win, width=600, height=400, visual="directcolor")  # same results
frame = tk.Frame(win, width=600, height=400, visual="greyscale")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="grayscale")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="pseudocolor")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="staticcolor")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="staticgray")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="staticgrey")  # get an error "couldn't find an appropriate visual"
frame = tk.Frame(win, width=600, height=400, visual="truecolor")  # same results
```

At this point if it is not a python or tkinter issue do yall have any ideas on where I should post the bug report next? For now I am just avoiding using images in my python if the scripts might be used on a Rocky Linux 9 machine but that is not a long term solution and more of just ignoring the problem.

I appreciate any additional assistance.

**Comment by chrstphrchvz** [comment]
I think reporter’s issue is indeed the same as the one I encountered. It is because photo image drawing in Tcl/Tk is unaware—as was I—that pixel colors for 32-bit depth visuals may contain an alpha channel. The effect seen in the screenshots is because Tk inadvertently sets the alpha of pixels to 0, causing colors from the photo image and colors appearing behind the toplevel to be combined (adding each channel and clamping to 255, as if Tk was supposed to specify a color with premultiplied alpha). I will open an upstream ticket for this with a possible fix.

> I was trying to do what yall suggested and got the following results.
> 
> ```python
> >>> import tkinter as tk
> >>> r = tk.Tk()
> >>> r.winfo_visualsavailable(includeids=True)
> [('truecolor', 32, 78), ('truecolor', 32, 919), ('truecolor', 32, 920), ('truecolor', 32, 921), ('truecolor', 32, 922), ('truecolor', 32, 923), ('truecolor', 32, 924), ('truecolor', 32, 925), ('truecolor', 32, 926), ('truecolor', 32, 927), ('truecolor', 32, 928), ('truecolor', 32, 929), ('truecolor', 32, 930), ('truecolor', 32, 931), ('truecolor', 32, 932), ('truecolor', 32, 933), ('truecolor', 32, 934), ('truecolor', 32, 935), ('truecolor', 32, 936), ('truecolor', 32, 937), ('truecolor', 32, 938), ('truecolor', 32, 939), ('truecolor', 32, 940), ('truecolor', 32, 941), ('truecolor', 32, 942), ('truecolor', 32, 943), ('truecolor', 32, 944), ('truecolor', 32, 945), ('truecolor', 32, 946), ('truecolor', 32, 947), ('truecolor', 32, 33), ('truecolor', 32, 34)]
> >>> r.winfo_visualid()
> '0x21'
> ```

The workaround I would have suggested is to use a 24-bit depth visual, but that is only possible if `winfo_visualsavailable()` lists 24-bit visuals. In your case it only contains 32-bit visuals.

**Comment by chrstphrchvz** [comment]
> My Windows answers to the questions:
> 
> ```
> >>> import tkinter as t
> >>> r = t.Tk()
> >>> r.winfo_visualsavailable(includeids=True)
> [('truecolor', 32, 0)]
> >>> r.winfo_visualid()
> '0x0'
> ```

Tk for native Win32 and Aqua do not use real X11, and their emulation of visuals and other X11 features is sometimes only just enough to get by. So I do not expect the result of `winfo_visualsavailable()` etc. on Win32 or Aqua to be as interesting compared to X11.

**Comment by angrodm** [comment]
I appreciate the additional assistance chrstphrchvz. If there is any additional information you need from me I'll get back to this in about a week as I am on a trip for the Holiday. If possible when you get the upstream ticket created would it be okay to have a link to it in a comment here? If not no worries.

**Comment by chrstphrchvz** [comment]
> If possible when you get the upstream ticket created would it be okay to have a link to it in a comment here?

https://core.tcl-lang.org/tk/info/1d8b7124b622
