### ISSUE TITLE
Unexpected success of async test cases in unittest.TestCase

### ISSUE THREAD

**Issue by ziima** [python/cpython#112296]
# Bug report

### Bug description:

When I accidentally use `TestCase` instead of `IsolatedAsyncioTestCase` as a base class for async tests, tests are not run, but they pass with no error.

### MWE
```python
from unittest import TestCase

class MyTest(TestCase):
    async def test_fail(self):
        self.assertFalse(True)
```

When run, the result is
```sh
$ python3 -m unittest async_test.py 
/usr/lib/python3.11/unittest/case.py:579: RuntimeWarning: coroutine 'MyTest.test_fail' was never awaited
  if method() is not None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
/usr/lib/python3.11/unittest/case.py:678: DeprecationWarning: It is deprecated to return a value that is not None from a test case (<bound method MyTest.test_fail of <async_test.MyTest testMethod=test_fail>>)
  return self.run(*args, **kwds)
.
----------------------------------------------------------------------
Ran 1 test in 0.002s

OK
```
Test finishes successfully, even though no test have been run. It outputs warnings, but those could be overlooked or disabled. I'd expect the test to return errors when async test methods are defined in `TestCase`.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
Does `-W error` solve your case?

**Comment by gvanrossum** [comment]
I personally don't think it is Python's responsibility to save you from making this mistake. Though if others think this is within scope, I suppose the unittest framework could explicitly reject things named `test_blah` that are of type coroutine. (This will undoubtedly break all sorts of user code due to Hyrum's law.)

**Comment by serhiy-storchaka** [comment]
This issue was already solved, and the solution was emitting a warning. Just wait few versions until they turn into errors. Or use `-Werror` or more specific filter.

**Comment by ziima** [comment]
`-W error` doesn't really help, since larger projects are hardly warnings-free. If the warning about the test return value is intended to handle this case, then I'm OK with that.
