### ISSUE TITLE
Everytime something necessary to install, version error raised. Even in google colab now

### ISSUE THREAD

**Issue by imrnh** [python/cpython#112228]
# Bug report

### Bug description:

```python
Requirement already satisfied: tensorflow in /usr/local/lib/python3.10/dist-packages (2.14.0)
Collecting tensorflow-gpu
  Using cached tensorflow-gpu-2.12.0.tar.gz (2.6 kB)
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Please fix these issues before releasing a new version. We don't need _ seperated long numbers. We need the reliable and productive language python was. 

This issue was raised on my local machine countless amount of times (for different other libraries in different times). Downgraded the python and it worked. But why should I waste my time downgrading? Even the error sign is not giving enough information.

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
You haven't provided enough information here for us to debug this, but presumably tensorflow-gpu doesn't support the version of python you were using. There's a note on the tensorflow-gpu PyPI page that it shouldn't be used, in preference to tensorflow.

Since this isn't a Python bug, I'm going to close this. If you need help installing tensorflow, you might want to ask on a tensorflow specific email list.

**Comment by terryjreedy** [comment]
This tracker is for patches to the Python language doc and the CPython inplementation.  I do not know what 'these issues' are, but the above output does not obviously demonstrate a bug or issue with CPython, as opposed to pip or tensorflow.  3.10 only gets security fixes.
