### ISSUE TITLE
Python interpreter losing track of variables while inside a local scope and using eval()/exec()/compile functions.

### ISSUE THREAD

**Issue by AdolphoIgor** [python/cpython#112219]
# Bug report

### Bug description:

```python
def main2():

    a = eval('100*200')
    print(f'Value of a is {a}')

    # BUG? It seems that 'a' isn't a global nor a local variable
    b = exec('a = 100*700')
    print(f'Value of a is {a} b is {b}')

    print(globals())

def main():

    # The workaround is declaring a global variable here and...
    global a
    a = eval('100*200')
    print(f'Value of a is {a}')

    # ...inside the string's statement that goes to exec().
    b = exec('global a\na = 100*800')
    print(f'Value of a is {a} b is {b}')

    print(globals())

    
if __name__ == "__main__":

    a = eval('100*200')
    print(f'Value of a is {a}')

    b = exec('a = 100*900')
    print(f'Value of a is {a} b is {b}')

    print(globals())


    main2()
    main()
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
You haven't show the actual output, and how it differs from what you're expecting.

I guess the problem is you're expecting a new local variable `a` to be created? `exec` can't create local variables. This relates to the local variable optimization. So, this isn't a bug.

Instead, look at the `globals` argument to `exec`.

**Comment by Eclips4** [comment]
FYI: https://docs.python.org/3/library/functions.html?highlight=compile#exec

**Comment by AdolphoIgor** [comment]
Hi Eric. Thank you for your reply.

Brother, have you executed the code I've posted?

There is a point that an exec()/eval() should change either a global or a
local variable but it doesn't do it, the change is completely lost.
Please take a look at the code's comments and you find out what I'm talking
about.

CODE:
def main2():
# this is a 'a' local variable
a = eval('100*100')
print(f'Value of a is {a}')

# BUG:? It seems that 'a' isn't a global nor a local variable
b = exec('a = 100*700') # <--- Why 'a' variable here, which could be a
global or local variable hasn't being changed at all?
print(f'Value of a is {a} b is {b}')

print(globals())

def main():
# The workaround is declaring a global variable here and...
global a
a = eval('100*200')
print(f'Value of a is {a}')

# ...inside the string's statement that goes to exec().
b = exec('global a\na = 100*800')
print(f'Value of a is {a} b is {b}')

print(globals())

if __name__ == "__main__":
#this is a 'a' global variable...
a = eval('100*200')
print(f'Value of a is {a}')

b = exec('a = 100*900')
print(f'Value of a is {a} b is {b}')

print(globals())


main2()
main()


Respeitosamente.

Adolpho Igor Benazzi Rodrigues

**Comment by AdolphoIgor** [comment]
I beg to differ about your analysis. 

Take a look at what is happening with the same code existing in the entry point (if __name__ == "__main__":) and the "main2()" code. That doesn't make any sense at all.

def main2():
    # This is a local variable and there isn't any global variable name colliding here...
    aa = eval('100*100')
    print(f'Value of aa is {aa}')

    # BUG:
    bb = exec('aa = 100*700') # <--- Why 'aa' variable here, which is local variable but hasn't being changed at all by exec(). Why?
    print(f'Value of aa is {aa} bb is {bb}')

    print(globals())

def main():
    # The workaround is declaring a global variable here and...
    global a
    a = eval('100*200')
    print(f'Value of a is {a}')

    # ...inside the string's statement that goes to exec().
    b = exec('global a\na = 100*800')
    print(f'Value of a is {a} b is {b}')

    print(globals())

    
if __name__ == "__main__":
    #this is a global variable...
    a = eval('100*200')
    print(f'Value of a is {a}')

    b = exec('a = 100*900') # <- exec() can change the value of the variable a here...
    print(f'Value of a is {a} b is {b}')

    print(globals())

    main2()
    main()

**Comment by AdolphoIgor** [comment]
This is my output:

Value of a is 20000
Value of a is 90000 b is None
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fd80e7479d0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/adolpho/devel/laboratorio/python/testes/testes.sql/teste6.py', '__cached__': None, 'main2': <function main2 at 0x7fd80e6ec4a0>, 'main': <function main at 0x7fd80e34a7a0>, 'a': 90000, 'b': None}
Value of aa is 10000
Value of aa is 10000 bb is None
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fd80e7479d0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/adolpho/devel/laboratorio/python/testes/testes.sql/teste6.py', '__cached__': None, 'main2': <function main2 at 0x7fd80e6ec4a0>, 'main': <function main at 0x7fd80e34a7a0>, 'a': 90000, 'b': None}
Value of a is 20000
Value of a is 80000 b is None
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <_frozen_importlib_external.SourceFileLoader object at 0x7fd80e7479d0>, '__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, '__file__': '/home/adolpho/devel/laboratorio/python/testes/testes.sql/teste6.py', '__cached__': None, 'main2': <function main2 at 0x7fd80e6ec4a0>, 'main': <function main at 0x7fd80e34a7a0>, 'a': 80000, 'b': None}

**Comment by ericvsmith** [comment]
Did you read the second note in the `exec` documentation? You can't create or modify a local with `exec`. You can modify values in a dict by using the `locals` parameter to exec.

```python
def f():
    lcls = {}
    exec('a=0', lcls)
    print(f'f() {locals().get("a")=}')
    print(f'f() {lcls["a"]=}')

def g():
    a = 0
    exec('a=1')
    print(f'g() {locals()=}')
    print(f'g() {a=}')

f()
g()
```
Outputs:
```python
f() locals().get("a")=None
f() lcls["a"]=0
g() locals()={'a': 0}
g() a=0
```


Since this isn't a bug, I suggest you search Stackoverflow or ask a question on https://discuss.python.org/c/users/7

PS: Your output and code would be easier to read if you'd use backticks or triple backticks to format it correctly. The `__`s are especially confusing.

**Comment by AdolphoIgor** [comment]
That was I thought. Thank you for that.

PS: about the code format, this is my first time reporting sth... Sorry.
"Pobody is Nerfect".

But. I appreciate your help

Respeitosamente.

Adolpho Igor Benazzi Rodrigues

**Comment by ericvsmith** [comment]
No problem!

No worries on the formatting, just a helpful hint for next time.
