### ISSUE TITLE
`help()` on types has strange `(if defined)` notice for attributes that are defined

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#112266]
# Feature or enhancement

Let's say we have a regular class and we call `help()` on it:

```python
>>> class A: ...
... 
>>> help(A)
Help on class A in module __main__:

class A(builtins.object)
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
```

This leaves a strange impression: what does it mean for `__dict__`? 

> dictionary for instance variables (if defined)

It is defined. 

The same for regular `__doc__`:

```python
>>> A.__dict__['__dict__'].__doc__
'dictionary for instance variables (if defined)'
```

Let's see what happens when `__dict__` and `__weakref__` are not defined:

```python
>>> class B:
...    __slots__ = ()
... 
>>> help(B)
Help on class B in module __main__:

class B(builtins.object)

```

And:

```python
>>> B.__dict__['__dict__']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    B.__dict__['__dict__']
    ~~~~~~~~~~^^^^^^^^^^^^
KeyError: '__dict__'
```

The historical reason behind it is: https://github.com/python/cpython/commit/373c7412f297c375d84c5984f753557b441dd6f4#diff-1decebeef15f4e0b0ce106c665751ec55068d4d1d1825847925ad4f528b5b872R1356-R1377

What do others think: should we remove `(if defined)` part? 
If so, I have a PR ready.

### Linked PRs
* gh-112268
* gh-112270
* gh-112276

**Comment by AlexWaygood** [comment]
It's saying that there might not be any instance variables defined, i.e., `A().__dict__` might be empty if it has no instance variables

**Comment by AlexWaygood** [comment]
I personally find the current text clear, _but_ I'm a native English speaker. If the current text isn't clear to non-native English speakers, then I agree we should change it to something that is.

I actually quite like @sobolevn's idea of just removing the "(if defined)". I'm not sure it adds anything; if it's unclear to some people, let's just get rid of it

**Comment by sobolevn** [comment]
Context: while working on https://github.com/python/cpython/pull/112143 I've spent like 20 minutes debugging `help` and `__dict__` outputs to find out that this behaviour is expected. So, I got totally confused.

After the change:

```
>>> class A: ...
... 
>>> help(A)
Help on class A in module __main__:

class A(builtins.object)
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object

```

**Comment by terryjreedy** [comment]
I agree with the change.
