### ISSUE TITLE
Cant install request libary in windows

### ISSUE THREAD

**Issue by Goofydoggo** [python/cpython#112233]
# Bug report

### Bug description:

Trying to download request library and its showing this in powershell : 
![image](https://github.com/python/cpython/assets/145468647/31ec840f-1d9a-4725-932e-1ae5ed921ca8)
Im using python 3.12 plz help

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by arhadthedev** [comment]
Input requests starting with `>>>` tell you are inside a running Python. Enter `exit()` to return into *cmd* where both `pip` and `python` are available.

**Comment by Goofydoggo** [comment]
> Input requests starting with `>>>` tell you are inside a running Python. Enter `exit()` to return into _cmd_ where both `pip` and `python` are available.

Ty
