### ISSUE TITLE
deadlocked child process after forking on pystate.c's HEAD_LOCK

### ISSUE THREAD

**Issue by ChuBoning** [python/cpython#112275]
# Bug report

### Bug description:

A forked process (via os.fork) can inherit a locked runtime->interpreters.mutex from its parent process and will deadlock in this stack:
Child Process (deadlocked):
#0  0x0000ffffa9b2b268 in do_futex_wait.constprop () from /lib/aarch64-linux-gnu/libpthread.so.0
#1  0x0000ffffa9b2b39c in __new_sem_wait_slow.constprop.0 () from /lib/aarch64-linux-gnu/libpthread.so.0
#2  0x0000ffffa9e96eb8 in PyThread_acquire_lock_timed () from /usr/local/lib/libpython3.8.so.1.0
#3  0x0000ffffa9e865a8 in _PyThreadState_DeleteExcept () from /usr/local/lib/libpython3.8.so.1.0
#4  0x0000ffffa9eb94ac in PyOS_AfterFork_Child () from /usr/local/lib/libpython3.8.so.1.0

Similar to https://github.com/python/cpython/issues/74580 and it's solved by https://github.com/python/cpython/commit/f82c951d1c5416f3550d544e50ff5662d3836e73 on python3.6 and 3.7

However,the problem appeares again on python3.8: HEAD_LOCK is called from PyOS_AfterFork_Child->_PyEval_ReInitThreads->_PyThreadState_DeleteExcept before PyOS_AfterFork_Child->_PyRuntimeState_ReInitThreads reinit runtime->interpreters.mutex.

I notice the problem will be resolved on python3.12 from the source code,but is it still existed on python3.8 to 3.11?

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

### Linked PRs
* gh-112336
* gh-123687
* gh-123688
* gh-123713

**Comment by itamaro** [comment]
Python 3.8 is receiving only security fixes currently (so is 3.9 and 3.10).

Could you check whether this issue reproduces with 3.11 and/or 3.12 and update the issue accordingly?

**Comment by ChuBoning** [comment]
> Python 3.8 is receiving only security fixes currently (so is 3.9 and 3.10).
> 
> Could you check whether this issue reproduces with 3.11 and/or 3.12 and update the issue accordingly?

I haven't tried it on 3.11 yet.But I think this issue will reproduce on 3.11. And there is no such issue on 3.12 since _PyRuntimeState_ReInitThreads calls _PyThread_at_fork_reinit to reinit the lock at the beginning.

**Comment by ChuBoning** [comment]
> Python 3.8 is receiving only security fixes currently (so is 3.9 and 3.10).
> 
> Could you check whether this issue reproduces with 3.11 and/or 3.12 and update the issue accordingly?

Could you please take a look at this https://github.com/python/cpython/pull/112336 ? I fix it just as python3.12 does.

**Comment by ChuBoning** [comment]
Thanks a lot!

**Comment by ambv** [comment]
Thank *you* for the report and patch!
