### ISSUE TITLE
Speed up the Tier 2 interpreter

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#112287]
The Tier 2 interpreter hasn't really been optimized carefully. While the "optimizer" pass is intended to make the Tier 2 micro-code faster through things like guard elimination or constantification, we should also look into just making the Tier 2 interpreter itself faster -- possibly by changing the representation of executable traces held in the executor (the current format is identical to the IR, which is rather verbose, using 16 bytes per uop!), and possibly by just carefully tuning the interpreter. (For example, if the space of micro-opcode ordinals could overlap the space of Tier 1 bytecode ordinals, we could fit the Tier 2 opcode in one byte.)

### Linked PRs
* gh-112286

**Comment by hugovk** [comment]
Closing because the PR has been merged. Please re-open if there's more needed here.

**Comment by gvanrossum** [comment]
Thanks for the ping! Arguably the issue was wider, but we've decided to focus on JIT performance, and the Tier 2 interpreter's speed is no longer of great concern (we keep it because it's easier to debug the rest of the Tier 2 machinery this way). So let's keep it closed but mark as "not planned", which is closer to the truth.
