### ISSUE TITLE
getpass stuck on 1024+ characters (must ctrl+c)

### ISSUE THREAD

**Issue by ikamensh** [python/cpython#112338]
# Bug report

### Bug description:

In interactive mode:
```python
>>> import getpass
>>> print("a"*1025)
>>> getpass.getpass(prompt="paste output of aaaa...aaaa here")
```

Result: I get the OS error sound, a short click like when I am trying to interact with some inactive window or so. getpass() call doesn't return anymore, and doesn't accept enter key to return whatever it got. 

This is reproduced running the code above non-interactively from iTerm2. Running this script in pycharm I don't reproduce the issue, but warning and no hiding for password:
```
/usr/local/anaconda3/envs/ct311/bin/python /Users/user/clustertools/try_getpass.py 
/usr/local/anaconda3/envs/ct311/lib/python3.11/getpass.py:91: GetPassWarning: Can not control echo on the terminal.
  passwd = fallback_getpass(prompt, stream)
Warning: Password input may be echoed.
paste output of aaaa...aaaa here
```

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

macOS

**Comment by carsonRadtke** [comment]
From the [osx man page](https://man7.org/linux/man-pages/man3/termios.3.html) for `termios(4)`:

> The system imposes a limit, {MAX_INPUT}, on the number of bytes that may be stored in the input queue.

According to 'syslimits.h', MAX_INPUT is defined to be 1024 and I am able to reproduce the behavior you describe (beeping and not accepting <enter>) outside of Python with the following C program:
```c
#include <unistd.h>
#include <stdio.h>

int main()
{
  fprintf( stdout, "%s\n", getpass( "prompt: " ) );
  return 0;
}
```

**Comment by ikamensh** [comment]
Usecase: While it's unusual for a user password to be that long, I was using it for storing an API token from a website, and that was ~1250 chars long.

**Comment by ronaldoussoren** [comment]
Given that this is a limitation in the OS there's nothing we can do about this in ``getpass`` or ``termios``.

**Comment by ikamensh** [comment]
note: from my tests, the same limitation applies to `input()`.
