### ISSUE TITLE
"WARNING: Secure coding is not enabled for restorable state"

### ISSUE THREAD

**Issue by thekartikpage15** [python/cpython#112394]
# Bug report
> WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.

### Bug description:

```python
# Add a code block here, if required
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by hugovk** [comment]
Please give precise information: what did you do and what exactly happened?

**Comment by terryjreedy** [comment]
Duplicate of #110950 #111082 #111845.  Not a CPython issue.
