### ISSUE TITLE
can not unparse code with ' in format_spec

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#112364]
# Bug report

### Bug description:

The following example shows that it is not possible to unparse a f-string with a ' in the format_spec, but such code can be generated when the f-string is double-quoted.

expected behaviour:
`unparse` should use different quotes if quotes are part of the format_spec.

This is only a problem in 3.12 and worked in 3.11

```python

import ast

code="""f"{something:'}" """
print("original code:",code)

tree=ast.parse(code)
print("original tree:",ast.dump(tree,indent=2))

new_code=ast.unparse(tree)
print("unparsed code:",new_code)

ast.parse(new_code)

```

output (Python 3.12.0):
```python
original code: f"{something:'}" 
original tree: Module(
  body=[
    Expr(
      value=JoinedStr(
        values=[
          FormattedValue(
            value=Name(id='something', ctx=Load()),
            conversion=-1,
            format_spec=JoinedStr(
              values=[
                Constant(value="'")]))]))],
  type_ignores=[])
unparsed code: f'{something:'}'
Traceback (most recent call last):
  File "/home/frank/projects/pysource-playground/pysource-codegen/codi.py", line 13, in <module>
    ast.parse(new_code)
  File "/home/frank/.pyenv/versions/3.12.0/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 1
    f'{something:'}'
                   ^
SyntaxError: unterminated string literal (detected at line 1)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-115696
* gh-115782

**Comment by Eclips4** [comment]
cc  @pablogsal @lysnikolaou

**Comment by pablogsal** [comment]
Will take a look this week

**Comment by pablogsal** [comment]
I took a look at this issue and I think switching to a different set of quotes is too complex so the best way foward is that unparse scapes the quote. @isidentical @lysnikolaou WDYT?

**Comment by terryjreedy** [comment]
```python
import ast

code1="""f"{something:'}" """
code2="""f'{something:\\'}' """
print(code1)
print(code2)

tree1=ast.parse(code1)
tree2=ast.parse(code2)
print("Trees equal: ", tree1 == tree2)

dump1 = ast.dump(tree1, indent=2)
dump2 = ast.dump(tree2, indent=2)
print("Dumps equal: ", dump1 == dump2)
print("Unparses equal: ", ast.unparse(tree1) == ast.unparse(tree2))  # IE both same bug.
```
prints
```
f"{something:'}" 
f'{something:\'}' 
Trees equal:  False
Dumps equal:  True
Unparses equal:  True
```
Assuming that the tree difference is as unconsequential for compiles as it is for the dumps, the escape looks fine to me.  ast.unparse(tree2) == astunparse(

**Comment by pablogsal** [comment]
> Assuming that the tree difference is as unconsequential for compiles as it is for the dumps,

Looks like it is:

```
>>> class A:
...   def __format__(self, *args):
...      print(args)
...      return "A"
...
>>> f"{A():'}"
("'",)
'A'
>>> f"{A():\'}"
("'",)
'A'
```

**Comment by 15r10nk** [comment]
@pablogsal do you want to fix this issue? I could fix this bug if you want. That would be my first cpython Bugfix.

**Comment by pablogsal** [comment]
> @pablogsal do you want to fix this issue? I could fix this bug if you want. That would be my first cpython Bugfix.

Yes, let's fix it. Can you make a PR and CC me into it? Let's get your first CPython bug fix in 🚀
