### ISSUE TITLE
[Enum] make some private attributes public

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#112328]
# Feature or enhancement

Make `_EnumDict`, `_EnumDict._member_names`, and possibly other private names public.

This is to make subclassing `EnumType` and other advanced behavior supported, such as having multiple values per member.

### Linked PRs
* gh-112514
* gh-121720
* gh-123669
* gh-128142

**Comment by hugovk** [comment]
The PR has been merged, shall we close this, or is there more to do?

**Comment by ethanfurman** [comment]
Closing, thanks for the reminder.

**Comment by JelleZijlstra** [comment]
`EnumDict` is now public and included in `Enum.__all__`, but it is not documented at https://docs.python.org/3.13/library/enum.html or mentioned in the What's New for 3.13.

**Comment by u2rafi** [comment]
I am working on documenting this.
