### ISSUE TITLE
Reference Manual 6.3.1: wrong method mentioned

### ISSUE THREAD

**Issue by aichernig** [python/cpython#112331]
# Documentation

6.3.1. Attribute references

This section states that "This production can be customized by overriding the `__getattr__()` method."
This is wrong and should be replaced with  "This production can be customized by overriding the `__getattribute__(self, attr)` method.".

`__getattr__()` is only called when the attribute is not found.  `__getattribute__(self, attr)` is the method that is called when accessing an attribute. Here is an example code for both:

```python
class C:
    def __init__(self):
        self.a = 1
    def __getattr__(self, attr): # called when attribute not found
        print('attribute does not exist')
    def __getattribute__(self, attr): # called first
        print('attribute', attr, 'accessed')
        return object.__getattribute__(self, attr) # object is the top-level type for classes

o = C()
print(o.a) # found, calls __getattribute__
print(o.b)  # not found, calls both methods.
```

Hence, either mention both methods or only `__getattribute__`.

### Linked PRs
* gh-112375
* gh-112412
* gh-112413

**Comment by Nitin-Gahlawat** [comment]
Hello @aichernig, I'm actively addressing the current issue. If you or the community have any guidance or preferences, please let me know. Thank you.

**Comment by aichernig** [comment]
What do you mean? I explained what the problem is and how it should be resolved.

**Comment by rhettinger** [comment]
@aichernig Will this revised text suffice?

```
The primary must evaluate to an object of a type that supports attribute
references, which most objects do.  This object is then asked to produce the
attribute whose name is the identifier. The type and value produced is
determined by the object.  Multiple evaluations of the same attribute
reference may yield different objects.

This production can be customized by overriding the :meth:`__getattribute__`
method or the :meth:`__getattr__` method.  The :meth:`__getattribute__`
is called first and either returns a value or raises :exc:`AttributeError`
if the attribute is not available.

If an :exc:`AttributeError` raised and the object has a :meth:`__getattr__`
method, that method is called as a fallback.
```

**Comment by aichernig** [comment]
Yes almost perfect. I think the last sentence "If an :exc:`AttributeError` raised ... " should be "If an :exc:`AttributeError` is raised ..." or "was raised".
