### ISSUE TITLE
pdb unintentionally interpolates strings with convenience variables

### ISSUE THREAD

**Issue by salty-horse** [python/cpython#112343]
# Bug report

### Bug description:

Python 3.12 introduced $-prefixed convenience variables to pdb (#103693).

It automatically replaces $-words in strings, which is undocumented. @nedbat suggests this is unintended behavior.
```
(Pdb) p '$in'
'__pdb_convenience_variables["in"]'
```
This totally breaks MongoDB queries inside pdb, as it makes frequent use of such strings.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-112380
* gh-114202

**Comment by gaogaotiantian** [comment]
PR #112380 made to fix this. We can't easily achieve this with pure regex so I simply switched to tokenize.

**Comment by gaogaotiantian** [comment]
This is fixed in main and backported to 3.12. Close.
