### ISSUE TITLE
Add trivial improvement to list_resize() function

### ISSUE THREAD

**Issue by grayroom** [python/cpython#112369]
# Feature or enhancement

### Proposal:

While looking at the list_resize function, I found a seemingly unnecessary condition break in the code block below.

https://github.com/python/cpython/blob/e9d1360c9a1072aa23950b321491dc542c3a19b8/Objects/listobject.c#L82-L93

I checked that the `items`variable is not referenced by any line in this function. Therefore, it seems that the logic in line `88` can be replaced by the logic in line `91-92`.

The modified code block is as follows.

```c
    if (new_allocated <= (size_t)PY_SSIZE_T_MAX / sizeof(PyObject *)) {
        num_allocated_bytes = new_allocated * sizeof(PyObject *);
        items = (PyObject **)PyMem_Realloc(self->ob_item, num_allocated_bytes);
    }
    else {
        // integer overflow
        PyErr_NoMemory();
        return -1;
    }
```

There will be improvements as much as the NULL allocation in row `88` and the comparative operation in row `90` disappeared, but the effect is unlikely to be significant.

As a person aiming for a more concise code, I think it is right to improve it like this.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-112370
* gh-112371

**Comment by corona10** [comment]
As I commented: https://github.com/python/cpython/pull/112371#discussion_r1404378383
This code is intended. Can we close the issue if there is no other issue on the line?

**Comment by grayroom** [comment]
Thank you for mentioning about this
