### ISSUE TITLE
Add decorator override to argparse._AttributeHolder.__repr__

### ISSUE THREAD

**Issue by ghost** [python/cpython#112415]
# Documentation

(A clear and concise description of the issue.)

### Linked PRs
* gh-106054

**Comment by rhettinger** [comment]
I think you need to take this to a discussion group before going further with development.

In general, the argparse module is mostly closed off to future development.   Also, because import time is important for applications using argparse, we try to not import any other modules.

**Comment by AlexWaygood** [comment]
I agree with @rhettinger. Thanks for the idea, but I think we're pretty unlikely to make this change unfortunately.
