### ISSUE TITLE
`Path("").exists()` always returns True, which is a bug

### ISSUE THREAD

**Issue by yingshaoxo** [python/cpython#112484]
# Bug report

### Bug description:

```python
from pathlib import Path
print(Path("").exists())

import os
print(os.path.exists(""))
```

For empty string "", pathlib returns True, but os returns False.

Clearly, os is right, because you can't read anything from "".

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment]
Behavior verified in 3.13.0a2.

**Comment by barneygale** [comment]
This is longstanding behaviour in pathlib - `Path()`, `Path('')` and `Path('.')` all have an `__fspath__()` value of `'.'`

(Not meaning to imply this bug is invalid, just adding context)

**Comment by ronaldoussoren** [comment]
> This is longstanding behaviour in pathlib - `Path()`, `Path('')` and `Path('.')` all have an `__fspath__()` value of `'.'`
> 
> (Not meaning to imply this bug is invalid, just adding context)

That's a side effect of ``pathlib.Path`` ignoring empty segments:

```python
>>> import pathlib
>>> pathlib.Path("a", "", "", "b")
PosixPath('a/b')
>>> pathlib.Path("a////b")
PosixPath('a/b')
```

This is not documented, but is somewhat implied by "Spurious slashes and single dots are collapsed, " in the documentation. That said, it would IMHO be better to explicitly document this behaviour.

**Comment by barneygale** [comment]
pathlib models a path as three parts: `(drive, root, tail)`, where the first two elements are strings, and `tail` is a list of strings. Each element in `tail` corresponds to a real path component (no `""` or `"."`), and this is leveraged by `relative_to()` to generate the right number of `..` segments.

Right now, a path with no segments is represented as `("", "", [])`. Its `__str__()` and `__fspath__()` would be `""` according to normal joining rules, but pathlib special-cases it to `"."` instead.

I'm not sure how we'd represent both `""` and `"."` in this model. Any suggestions? Also, what would `Path("", "")` and `Path("", ".")` produce?

**Comment by ronaldoussoren** [comment]
Is there any reason to change the current behaviour? 

Treating the empty segment in ``Path("")`` differently from empty segments in multi-segment names complicates the semantics of the API with (IMHO) little to no advantage.  The current behaviour is easy to explain: all empty segments are ignored, and ``Path()`` represents the current directory (e.g. ``Path(".")``.

**Comment by barneygale** [comment]
Closing as "won't fix" - this is deliberate and longstanding behaviour, and pathlib's model of paths doesn't leave room for a distinction between `""` and `"."`.
