### ISSUE TITLE
Substantial Degradation in Performance (Roughly 58-fold) When Downloading and Storing Small Files in Parallel on Windows 11

### ISSUE THREAD

**Issue by ilotoki0804** [python/cpython#112494]
# Bug report

### Bug description:

During the development of my personal project, I noticed that the Python 3.12 multithreading on Windows 11 consumes significantly more CPU resources and operates at a noticeably slower pace compared to 3.11.

To assess the speed, I conducted [a benchmark](https://github.com/ilotoki0804/python-multithreading-performance/blob/main/performance-check.py). The results of the benchmark indicate the following:

- The `multiprocessing.pool.ThreadPool` is 1.76 times slower and consumes 33.09 times more CPU.
- The `threading.Thread` is 1.51 times slower and consumes 26.18 times more CPU.
- The `multiprocessing.pool.ThreadPool` on Windows Sandbox is 1.07 times slower and consumes 120.15 times more CPU in version 3.12 compared to version 3.11.4.

These characteristics were not observed during experimentation with WSL(Ubuntu). In fact, I was unable to obtain the final result due to the considerably slow operation of both Python 3.11 and 3.12.

I have compiled the results of the performance tests in a repository, which can be accessed via [this link](https://github.com/ilotoki0804/python-multithreading-performance).

My system: Windows 11 Pro x64 23H2, AMD 5900HX

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by neonene** [comment]
Could you check whether #95031 (or #109386) has your issue?

**Comment by ilotoki0804** [comment]
@neonene Yes. I tested it on Python 3.11.6 (OpenSSL 3 used), and the identical problem occurred. I think it shows that I have the same issue with #95031.
