### ISSUE TITLE
`sqlite3.connect(autocommit=False)` breaks `executescript("BEGIN; COMMIT")`

### ISSUE THREAD

**Issue by tom93** [python/cpython#112441]
# Bug report

### Bug description:

*Background: The autocommit parameter was added to the sqlite3 module in Python 3.12 (#83638), the default is currently LEGACY_TRANSACTION_CONTROL but it is set to change to False in a future Python release.*

When autocommit is False, it breaks code that uses [executescript()](https://docs.python.org/3.12/library/sqlite3.html#sqlite3.Cursor.executescript) with transaction control. Example:

```python
import sqlite3
con = sqlite3.connect(":memory:")
con.executescript("BEGIN TRANSACTION; CREATE TABLE t (x); INSERT INTO t VALUES(1); COMMIT;")
con.close()
```

This program works on all existing Python versions (2.7 - 3.13.0a1), but with autocommit=False it throws the following error:

```
Traceback (most recent call last):
  File "<string>", line 4, in <module>
sqlite3.OperationalError: cannot start a transaction within a transaction
```

So making autocommit=False the default in future will break backward compatibility.

---

~~One idea for fixing this is to change the behaviour of executescript() so that when autocommit is False, it will first execute an implicit COMMIT (as it already does when autocommit=LEGACY_TRANSACTION_CONTROL), and after it will execute BEGIN.~~ *Edit: This idea is unsuitable, because it is incompatible with the model where [a transaction is always open](https://github.com/python/cpython/issues/112441#issuecomment-1827607096).*

**Comment by erlend-aasland** [comment]
This is intended behaviour; `autocommit=False` implies PEP-249 compliant behaviour, meaning a transaction **is always open**. Please read the relevant docs on how `autocommit` is intended to work. See also PEP-249.

https://docs.python.org/3/library/sqlite3.html#sqlite3-transaction-control-autocommit

**Comment by erlend-aasland** [comment]
> So making autocommit=False the default in future will break backward compatibility.

No. `autocommit` was introduced in 3.12; it was not present in earlier versions. Changing the default in the future is possible with the help of documentation, changelog/What's New entries, and deprecation warnings.

**Comment by erlend-aasland** [comment]
> Can you please share your thoughts on the best way to use executescript() when the SQL string uses transaction control?

For that scenario you cannot use the implicit transaction control recommended by PEP-249. You can do that either by setting `autocommit=True` (Python 3.12 or newer) or `isolation_level=None` (Python 3.11 or older). You can for example set the `connect` keywords conditionally:

```python
kdws = {"isolation_level": None} if legacy else {"autocommit": True}
cx = sqlite3.connect(path, **kwds)
cx.executescript(sql_with_tx_ctrl_statements)
```

It's up to you how you set `legacy`; using `sys.version_info` is fine. So is `hasattr`.

> A. Use isolation_level=None. Issues: isolation_level will be deprecated(?), and there will be warnings if I don't set autocommit explicitly(?).

Currently, `isolation_level` is only soft deprecated (docs only). Perhaps that will change in the future; I can't promise anything now :(

> B. Use autocommit=True. Issues: [...] and the docs recommend autocommit=False.

I don't see how this is an issue; the docs recommend the default that PEP-249 recommends. If your application's requirements don't align with that recommendation, that's ok. It is ok to use `autocommit=True`.

**Comment by tom93** [comment]
Many thanks!
