### ISSUE TITLE
The `find_module` fallback has been removed but is still mentioned in `sys.meta_path`'s document

### ISSUE THREAD

**Issue by aisk** [python/cpython#112419]
# Documentation

The `find_module` fallback for `sys.meta_path` has been [removed](https://github.com/python/cpython/issues/98040) in Python3.12, but is still mentioned in `sys.meta_path`'s document: https://docs.python.org/3/library/sys.html#sys.meta_path.

### Linked PRs
* gh-112421
* gh-113934

**Comment by erlend-aasland** [comment]
Thanks, @aisk !
