### ISSUE TITLE
dict.get runs default arg even if key is present in dict

### ISSUE THREAD

**Issue by ankitkpandey1** [python/cpython#112443]
# Bug report

### Bug description:

```python
l={'a':1}
l.get('a', print('Running none part'))
```
Expectation: Since key 'a' is already there, it shouldn't run the default part. 
![image](https://github.com/python/cpython/assets/60101290/7b1f8079-c61a-45b6-ae7c-876831dcb54b)

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
The "default" argument for ``dict.get`` is a regular argument and hence gets evaluated before calling ``dict.get``. 

There is no bug here, this is normal behaviour.
