### ISSUE TITLE
Make `_Py_ThreadId()` work on PowerPC, IBM Z, etc.

### ISSUE THREAD

**Issue by colesbury** [python/cpython#112535]
# Feature or enhancement

Currently, [`_Py_ThreadId()`](https://github.com/python/cpython/blob/d4a6229afe10d7e5a9a59bf9472f36d7698988db/Include/object.h#L243) is only defined in `Py_GIL_DISABLED` builds and does not compile on PowerPC or IBM Z. It would be convenient to make the functionality available in general: it will be useful to implement thread-safe recursive locks. (Currently our recursive lock implementations rely on the GIL for thread-safety.)

There are two parts to this:

1) We should use `__builtin_thread_pointer()` when available
2) We should fall back to a function that returns the address of a thread-local variable if no other fast implementation is available (instead of erroring out).

The fallback (2) will be a bit slower, but it provides a portable implementation.

Note that checking if `__builtin_thread_pointer()` is available is not trivial. `__has_builtin(__builtin_thread_pointer)` is not useful (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96952). You need some combination of platform and GCC/clang version check. 

cc @vstinner @corona10 

### Linked PRs
* gh-112553
* gh-112624
* gh-112709
* gh-112746
* gh-112751
* gh-113084
* gh-113094
* gh-113185

**Comment by colesbury** [comment]
@corona10  - of course, thanks!

**Comment by vstinner** [comment]
> Note that checking if __builtin_thread_pointer() is available is not trivial. __has_builtin(__builtin_thread_pointer) is not useful (https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96952). You need some combination of platform and GCC/clang version check.

That's fine. We have many tests preprocessor checks like that, `#if ...`.

**Comment by corona10** [comment]
@colesbury Do we need to support more platforms or we can close the issue?

**Comment by colesbury** [comment]
I think we still want the cross-platform fallback that returns the address of a thread-local variable. That will probably need to be implemented in a `.c` file because accessing thread-local variables across libraries can cause issues on some platforms.

**Comment by colesbury** [comment]
Adding a fallback will ease the maintenance burden and also work with WASM. In general, I think we want portable implementations when possible even if the platforms listed in PEP 11 ought to work without them.

We can't use `_Py_ThreadId()` outside of the `--disable-gil` builds right now. That makes it harder to implement an efficient recursive lock. We still will not want to *expose* `_Py_ThreadId()` outside of `--disable-gil` builds, but it will be convenient to use it in `.c` files like `Python/lock.c`.

**Comment by corona10** [comment]
https://github.com/python/cpython/blob/7595d47722ae359e6642506646640a3f86816cef/Python/thread_pthread.h#L380-L406

Well, we already implemented for getting native thread id. Do you want to use same approach?
If yes, Which platforms do we have to care? (Linux Only? or other things too?)

**Comment by colesbury** [comment]
@corona10, no I don't think we should use `PyThread_get_thread_native_id`. I think we should do what I wrote as part (2) in the issue: "return the address of a thread-local variable"

**Comment by corona10** [comment]
Got it, I will send a PR soon.I  read TLS spec in [here](.akkadia.org/drepper/tls.pdf) and now I understand what you want to say.(maybe?)

**Comment by colesbury** [comment]
@corona10, here is an example of what I mean in mimalloc, which uses the same strategy on platforms where it doesn't implement a faster `_mi_prim_thread_id()`:
 
https://github.com/python/cpython/blob/9cdf05bc28c5cd8b000b9541a907028819b3d63e/Include/internal/mimalloc/mimalloc/prim.h#L129
https://github.com/python/cpython/blob/9cdf05bc28c5cd8b000b9541a907028819b3d63e/Include/internal/mimalloc/mimalloc/prim.h#L224-L226

My reasons for preferring this strategy instead of `PyThread_get_thread_native_id()` are:
1) It should be a lot faster than `PyThread_get_thread_native_id()` (no syscalls), although still not as fast as the platform-specific implementations currently used in `_PyThread_Id()`
2) We can make more assumptions about the format (i.e., non-zero, pointer-aligned), which I think will come in handy when implementing recursive mutexes.

**Comment by vstinner** [comment]
You may have a look at `_PyThreadState_GET()` which is implemented by reading a thread local variable. If `Py_BUILD_CORE_MODULE` macro is defined, the function is implemented with an opaque function call: implementation for libraries.

**Comment by corona10** [comment]
> Got it, I will send a PR soon.

I am going to submit the PR early next week :)

**Comment by corona10** [comment]
Okay, let's close the issue since the fallback implementation is merged.
Thank you for all your supports and contribution @colesbury, @vstinner(Awesome test codes!) and @furkanonder (RISC-V)
