### ISSUE TITLE
use cosmopolitan libc

### ISSUE THREAD

**Issue by paxcoder** [python/cpython#112596]
# Feature or enhancement

### Proposal:

use cosmopolitan libc (https://justine.lol/cosmopolitan/index.html)
benefits:
*
people packaging apps wouldn't need to worry about platforms, everything would work independently.
less space requires for storage of files
***

### Has this already been discussed elsewhere?

No response given

**Comment by ronaldoussoren** [comment]
Our current crossplatform support works satisfactory for us. Cosmopolitan Libc is effectively a new platform and adding support for that requires discussion and likely a PEP.

Please first check on https://discuss.python.org/c/ideas/6 if there's any support for this idea.
