### ISSUE TITLE
`test_sys` broken on Python 3.12 under WASI

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#112503]
# Bug report

### Bug description:

https://github.com/python/cpython/pull/110713 unconditionally imports `test.support.interpreters` which imports `_xxsubinterpreters` which fails since it isn't provided.

This doesn't fail on `main` because it has a guard against the import:

https://github.com/python/cpython/blob/48dfd74a9db9d4aa9c6f23b4a67b461e5d977173/Lib/test/test_sys.py#L19-L22

### CPython versions tested on:

3.12

### Operating systems tested on:

Other

### Linked PRs
* gh-112505

**Comment by ericsnowcurrently** [comment]
Sorry about that.  I've opened a PR to fix it.
