### ISSUE TITLE
[windows/msys2] venv doesn't create activition script for `fish` shell

### ISSUE THREAD

**Issue by tigerinus** [python/cpython#112571]
# Bug report

### Bug description:

1. Install MSYS2 for Windows
2. Install `fish` shell under MSYS2
3. Start MSYS2 environment with `fish` shell
4. Run `python -m venv venv`

Expect:

`venv\Scripts` includes `activate.fish`

Actual:

`venv\Scripts` does not include `activate.fish`

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

### Linked PRs
* gh-117169

**Comment by aisk** [comment]
Since #117169 have been merged, so I think we can close this issue now.

**Comment by tigerinus** [comment]
Will this be rolled out to next Python 10 build?

> Since #117169 have been merged, so I think we can close this issue now.

**Comment by vsajip** [comment]
> Will this be rolled out to next Python 10 build?

If you mean 3.10, then no - 3.10 and 3.11 branches are accepting security fixes only.
