### ISSUE TITLE
Helping users who mistake `.rstrip()` for `.removesuffix()`

### ISSUE THREAD

**Issue by Zac-HD** [python/cpython#112506]
This is a perennial source of confusion for new and recurring footgun for experienced users, well explained in [the rationale for PEP-616](https://peps.python.org/pep-0616/#rationale) and shown locally in e.g. https://github.com/python/cpython/issues/86479, https://github.com/python/cpython/issues/86563, https://github.com/python/cpython/issues/88679, https://github.com/python/cpython/issues/89497, https://github.com/python/cpython/issues/92315, https://github.com/python/cpython/issues/103830, and https://github.com/python/cpython/issues/109455.  

I don't think there's any way to "fix" this - the methods are clearly documented and widely used - but there are two things we could do which I think would help users learn what these methods do:

1. Emit a warning if `.strip()`, `.lstrip()`, or `.rstrip()` are passed a string containing _duplicate_ characters.  While this will have many _missed_ alarms, the _false_-alarm rate will be low because `.rstrip("suffix")` could be replaced with `.rstrip("sufix")` (or `"ifusx"`) with no change in behavior.  In Hypothesis I'd deprecate this with`FutureWarning` and intent to raise a `ValueError` later, but expect that CPython might want to be more conservative.

2. Accept `set` and `frozenset` instances for the chars-to-strip, erroring if any elements are not length-one strings.  This makes it possible to write e.g. `.rstrip(set("suffix"))`, and in general makes it immediately obvious at the call site that the thing-being-stripped is a set of characters rather than a multi-character string.  I'd expect this to have somewhat worse performance - but the pass-a-string case should remain fast, most code doesn't live in hot loops, and it would be great to show this form in classes and tutorials.

cc @iritkatriel - thoughts?

**Comment by serhiy-storchaka** [comment]
Testing whether a string contains duplicate characters will add an overhead for every use of these method. We should not punish users that use them correctly.

Testing whether a set contains only single-character strings also has a cost. Even without this check, using a set will be significantly slower than using a short string, because for every character you need to create a string object, calculate its randomized hash, and perform other complex operations. Nobody will use sets if this is worse than using strings, but the implementation of this feature will add a nontrivial amount of code in unicodeobject.c, which is already too large.

I think that it is a task for linters.

**Comment by iritkatriel** [comment]
If this is indeed a big enough problem then I think a better solution in this case is to deprecate the confusing API and introduce a better one.

**Comment by hugovk** [comment]
> I think that it is a task for linters.

This is checked by flake8-bugbear and Ruff:

* https://github.com/PyCQA/flake8-bugbear#list-of-warnings (B005)
* https://docs.astral.sh/ruff/rules/strip-with-multi-characters/ (strip-with-multi-characters B005)

And by pylint and Ruff:

* https://pylint.readthedocs.io/en/latest/user_guide/checkers/features.html#string-checker (bad-str-strip-call E1310)
* https://docs.astral.sh/ruff/rules/bad-str-strip-call/ (bad-str-strip-call PLE1310)

(They're not enabled by default by Ruff.)

**Comment by serhiy-storchaka** [comment]
Deprecating `.rstrip()` etc will create a huge problem.

**Comment by iritkatriel** [comment]
Removing it will be a big problem. Soft deprecation less so.
