### ISSUE TITLE
Add `readline.backend` for the backend `readline` uses

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#112510]
# Feature or enhancement

### Proposal:

Currently we support two backends with readline: GNU readline and editline. They work in a similar way but have some differences. Notably the way to set `<tab>` as the complete key.

The users need to distinguish the backend at run time, and currently the recommended way is:

```python
if 'libedit' in getattr(readline, '__doc__', ''):
```

We have worse checks like
```python
readline_doc = getattr(readline, '__doc__', '')
if readline_doc is not None and 'libedit' in readline_doc:
```
in `site.py`.

It would be nice to provide a more official and clean way to check the backend, instead of querying for the docstring for the module. This is also mentioned in https://github.com/python/cpython/pull/107748#discussion_r1395432432 by @encukou .

In this proposal, a new attribute `backend` is added which could be either `readline` or `editline`.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-112511

**Comment by encukou** [comment]
Thank you for adding it!

**Comment by whitequark** [comment]
Could `readline.backend` be backported to 3.12? It seems that several popular builds of Python (from what I can tell, at least Homebrew and python-build-standalone) have switched to libedit and projects using the builtin readline module functionality 
are now hitting https://github.com/python/cpython/issues/121160. It would help if the `__doc__` workaround was made unnecessary earlier.

**Comment by gaogaotiantian** [comment]
I believe Mac is using libedit by default. Unfortunately, this is considered a new feature and I don't think it would be backported to 3.12.

**Comment by whitequark** [comment]
Thanks, this is good to know at least.
