### ISSUE TITLE
Two tuples (1,) and (1,) have different IDs if in interpreter mode, and the same IDs if running .py file

### ISSUE THREAD

**Issue by Fleuvre** [python/cpython#112554]
# Bug report

### Bug description:

```python
x = (1,)
y = (1,)
print(x is y)
```

If running these Python commands one-by-one in interpreter, result is "False".
If these commands are put in test.py file, and we run "python3 test.py", result is "True".

The issue is only related to Python 3.
By the way, Python 2.7 behaves consistently: we get "False" in both interpreter mode and when running .py file.

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux, Windows

**Comment by Eclips4** [comment]
Hello! There's no bug.
In REPL this optimization simply doesn't works.
Please, compare your tuples with `==`. operator.
From docs:
> Every object has an identity, a type and a value. An object’s identity never changes once it has been created; you may think of it as the object’s address in memory. The ‘[is](https://docs.python.org/3.12/reference/expressions.html#is)’ operator compares the identity of two objects; the [id()](https://docs.python.org/3.12/library/functions.html#id) function returns an integer representing its identity.
 CPython implementation detail: For CPython, id(x) is the memory address where x is stored.
There's no guarantee from CPython that tuple with the same content will be point at the same address. For example, empty tuples can points to the same memory (because they are singletons), but it's implementation detail of CPython and other Python implementations can evaluate `() is ()` as `False`.

**Comment by Fleuvre** [comment]
OK, thanks for explanation!
So, is it expected that results obtained in interactive mode and when running .py file may differ?
Could you please give more examples of such differences?
Thanks again!

**Comment by Eclips4** [comment]
> OK, thanks for explanation! So, is it expected that results obtained in interactive mode and when running .py file may differ? 

Yes.

> Could you please give more examples of such differences?

In REPL(interactive mode):
```python
>>> a = 1000
>>> b = 1000
>>> a is b
False
```
In non-interactive mode (as python3 somefile.py)
```python
a = 1000
b = 1000
print(a is b)

python3 somefile.py
> True
```

**Comment by ethanfurman** [comment]
`==` is the proper method to check for equality.  The only time `is` returning false would be a problem is when the object is supposed to be a singleton.  For example, `None is None` should always be true.  `Enum`'s should also be true with `is`:

```python
from enum import Enum

class Color(Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

Color(1) is Color(1)
# True
```
