### ISSUE TITLE
The 'help' functions should align with PEP-484 exports when `py.typed` is used.

### ISSUE THREAD

**Issue by feluxe** [python/cpython#112521]
# Feature or enhancement

### Proposal:

I maintain a library [sty](https://github.com/feluxe/sty) and recently added type annotations and a `py.typed` file in order to comply with PEP 484.

In `__init__.py` I had to use the `import name as name` / `from foo import name as name` [export convention](https://peps.python.org/pep-0484/#stub-files) to let static type checkers know that I want to export `name` for the package.

For example in `sty.__init__.py` I want to re-export `sty.primitive.Register` and `sty.primitive.Style`, so that people can import them from the library root: `from sty import Register, Style`. I had to use the `name as name` convention to explicitly mark the imports as exports:

```python
$ cat sty/__init__.py
...
from sty.primitive import Register as Register
from sty.primitive import Style as Style
...
```
This works fine, the type checkers are happy.

Now that I have marked `Register` and `Style` explicitly as exports, I was hoping the `help()` function would recognize this as well. But when I call `help(sty)`, it doesn't print information about `Register` and `Style`. It seems like the `help()` function and the static type checkers are not on the same page regarding exports.

I think `help()` should align with static type checkers when a `py.typed` file is included in the package. This would improve Dev UX and the overall quality of Python libraries.

I now have to add `__all__ = ["Register", "Style", ...]`, which I think is unfortunate and redundant, because the type checkers already know exactly what I want to export and what not using `name as name`.

### Has this already been discussed elsewhere?

No response given

**Comment by AlexWaygood** [comment]
Note that most type checkers will understand an object is explicitly re-exported by virtue of it just being in `__all__`. The `from foo import Bar as Bar` syntax is unnecessary if you've included `Bar` in `__all__`, and, as you've discovered, defining `__all__` has several other nice effects at runtime such as being understood by `help()` etc
