### ISSUE TITLE
`string.Formatter().parse` should return a named tuple

### ISSUE THREAD

**Issue by tusharsadhwani** [python/cpython#112692]
# Feature or enhancement

### Proposal:

```python
>>> import string
>>> parts = list(string.Formatter().parse('foo {:.2f} bar'))
>>> parts
[('foo ', '', '.2f', None), (' bar', None, None, None)]
```

I think returning a named tuple here makes sense here.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by serhiy-storchaka** [comment]
This is a duplicate of #73882.
