### ISSUE TITLE
`types.FunctionType` is missing `kwdefaults` from the constructor

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#112640]
# Feature or enhancement

https://github.com/python/cpython/blob/a9574c68f04695eecd19866faaf4cdee5965bc70/Objects/funcobject.c#L800-L813

It is rather strange to have `defaults`, but not `kwdefaults`.
I propose adding `kwdefaults` as the last parameter.

### Linked PRs
* gh-112641

**Comment by Gobot1234** [comment]
Should it also have type_params?
