### ISSUE TITLE
Allow zip to be reversible if inputted iterables are reversible 

### ISSUE THREAD

**Issue by Gobot1234** [python/cpython#112627]
# Feature or enhancement

### Proposal:

```python
>>> reversed(zip((1, 2), (3, 4)))
TypeError: 'zip' object is not reversible
```
But individually 
```py
>>> zip(reversed((1, 2)), reversed((3, 4)))
<zip ((2, 4), (1, 3))>
```
works

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by gvanrossum** [comment]
> This is a minor feature, which does not need previous discussion elsewhere

I disagree -- unless this was already discussed and refined on discuss.python.org (in the Ideas topic) this does not have much of a chance of getting added.
