### ISSUE TITLE
Undeprecate the onerror argument in shutil.rmtree()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#112645]
# Bug report

A new `onexc` parameter was added in `shutil.rmtree()` in 3.12 (see #102828). At the same time passing the `onerror` argument was deprecated. It creates inconvenience for code that should run on several Python versions. It forces users to modify their working code to avoid deprecation warnings.

I think that there was nothing wrong in `onerror`. The only advantage of `onexc` over `onerror` was that it may require to write less code in some cases, but the deprecation causes an opposite effect -- it requires to write more code.

So I think that the deprecation should be reverted.

@iritkatriel

### Linked PRs
* gh-112659
* gh-112665

**Comment by hugovk** [comment]
This is still listed as pending removal in 3.14:

https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-python-3-14

Should we instead update the docs so it's listed as pending removal in an unspecified, future version?

https://docs.python.org/3.13/whatsnew/3.13.html#pending-removal-in-future-versions

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/118947.
