### ISSUE TITLE
test.test_zlib.CompressObjectTestCase.test_flushes fails to parse ZLIB_VERSION with zlib-ng

### ISSUE THREAD

**Issue by hroncok** [python/cpython#112769]
# Bug report

### Bug description:

Hello. Fedora is switching from zlib to zlib-ng. https://fedoraproject.org/wiki/Changes/ZlibNGTransition

zlib-ng defines `ZLIB_VERSION` as `"1.3.0.zlib-ng"`:

https://github.com/zlib-ng/zlib-ng/blob/f3211aba349a1d4781d0d41cb00d29fb8325af06/zlib.h.in#L61

And `test.test_zlib.CompressObjectTestCase.test_flushes` fails to parse it a sequence of dot-separated integers:

https://github.com/python/cpython/blob/11d88a178b077e42025da538b890db3151a47070/Lib/test/test_zlib.py#L476

```
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.12.0/Lib/test/test_zlib.py", line 477, in test_flushes
    ver = tuple(int(v) for v in zlib.ZLIB_RUNTIME_VERSION.split('.'))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/Python-3.12.0/Lib/test/test_zlib.py", line 477, in <genexpr>
    ver = tuple(int(v) for v in zlib.ZLIB_RUNTIME_VERSION.split('.'))
                ^^^^^^
ValueError: invalid literal for int() with base 10: 'zlib-ng'
```

Another test in this file already handles this differently via 4c7108a77144493d0aa6fc0105b67d3797e143f5:

https://github.com/python/cpython/blob/11d88a178b077e42025da538b890db3151a47070/Lib/test/test_zlib.py#L798-L804

This could be made a function, so both the tests that need to compare the version could re-use it.

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-112771
* gh-112773
* gh-112774
* gh-119565
* gh-119566
* gh-119567

**Comment by hroncok** [comment]
I'm working on a PR.

**Comment by hroncok** [comment]
> I'm working on a PR.

Here it is: https://github.com/python/cpython/pull/112771

**Comment by Eclips4** [comment]
Thanks for the report and fix @hroncok!

**Comment by ned-deily** [comment]
This issue is now affecting some older buildbots. Created backport PRs for 3.10, 3.9, and 3.8 security branches.

**Comment by vstinner** [comment]
I closed issue gh-98567 as a duplicate of this issue.
