### ISSUE TITLE
Refactor dis module to separate instructions creation from formatting

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#112720]
The dis module is not very flexible, because the formatting and instruction creation are all entangled with one another. I will refactor it so that we are able to feed an instruction sequence to a formatter, or to plug in a different formatter into dis functions.

### Linked PRs
* gh-112722
* gh-113108
* gh-115564

**Comment by terryjreedy** [comment]
Nice.  This should aid testing *and* would allow an IDE, for instance, to more easily put dis output in a GUI panel.  I might think about putting a tkinter option in dis itself.

**Comment by hugovk** [comment]
Triage: the linked PRs are merged, can this be closed?

**Comment by iritkatriel** [comment]
There will probably be more in this space, but I can reopen if so.
