### ISSUE TITLE
Behaviour of unformattable `ValueError` on `list.index` has changed in Python 3.11 (change in PyErr_Format)

### ISSUE THREAD

**Issue by da-woods** [python/cpython#112768]
# Bug report

### Bug description:

```python
lst = []

class C:
    def __repr__(self):
        raise RuntimeError("Oh no!")

try:
    lst.index(C())
except ValueError as e:
    print("This is good")
    print(repr(e))
```

On Python 3.10 this prints

```
This is good
ValueError()
```

On Python 3.11 this prints

```
Traceback (most recent call last):
  File "<path>", line 8, in <module>
    lst.index(C())
  File "<path>", line 5, in __repr__
    raise RuntimeError("Oh no!")
RuntimeError: Oh no!
```

When `PyErr_Format` fails in current versions of Python, it doesn't set the exception and instead raises the new one:

https://github.com/python/cpython/blob/11d88a178b077e42025da538b890db3151a47070/Python/errors.c#L1162-L1167

In earlier versions of Python it used to raise the requested exception unconditionally

https://github.com/python/cpython/blob/b6535ea7ecf40c51a9a13089d961c29abeaffa5e/Python/errors.c#L1059-L1064

This looks to have been a deliberate change but it can affect the behaviour of real code (https://github.com/cython/cython/issues/5894). Interestingly PyPy got there before you with this behaviour (https://foss.heptapod.net/pypy/pypy/-/issues/3978)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
cc @serhiy-storchaka

**Comment by da-woods** [comment]
> If Cython crashes because of this, it has bugs, and this change helped to expose them.

I mostly agree with this, and have a fix for the Cython issue that will be applied whatever you decide to do with this.

If I were designing this I'd probably treat the first exception as the "main error", and any exception from generating the format string as "unraisable". Just because the error message attached to the exception feels like it could be treated as optional compared to the exception itself.

However, just wanted to flag that there's a behavioural change that probably isn't too hard to hit - I don't think it's too uncommon for `__repr__` to be a bit fragile while a class is being initialized for example.

**Comment by terryjreedy** [comment]
Would it be possible to print a double traceback, as in somewhat similar situations?  (The following is not exact.)
```
Traceback ...
... <traceback lines>
ValueError()

While processing this exception, another exception occurred.
Traceback...
... <traceback lines>
RuntimeError(...)
```

**Comment by serhiy-storchaka** [comment]
No, it is unreasonable. Another exception occurred before the intended exception was created, so the intended exception cannot be raised.

Look at the following example:
```python
raise ValueError(1/0)
```
There is no way to get a ValueError instead or in addition to a ZeroDivisionError in a traceback. ValueError cannot be created, because its argument cannot be evaluated. Creation of exception with wrong argument is a bug, because the exception argument can matter. And an exception raised when calculate exception arguments (for example KeyboardInterrupt, MemoryError or RecursionError which can be raised by virtually any code) does matter and should not be silenced.
