### ISSUE TITLE
Modules/expat/xmlparse.c warning about unreachable code

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#112796]
# Bug report

### Bug description:

The code linked to below disables some code by using ``if (0 && ...)`` and that results in a compile time warning.

https://github.com/python/cpython/blob/00cce0fe495ee820cd3ca5878bdbe3dd65b1be7b/Modules/expat/xmlparse.c#L3102C19-L3118

Given that the code has been disabled single 2019 it should be safe to just remove this block, or disable the code by using ``#if 0`` with a comment when it is prudent to keep the code around.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-112841

**Comment by ronaldoussoren** [comment]
I've closed the PR because I noticed (thanks to one of the CI jobs) that ``Modules/expat`` is a vendored copy of expat.  I haven't found any documentation on updates to this vendored copy, but its probably better to just leave it as is.

**Comment by hartwork** [comment]
@ronaldoussoren this is https://github.com/libexpat/libexpat/pull/692 upstream and syncing CPython's copy of Expat to 2.6.0 will get this fixed "for free". On a side note, the idea there is to keep compiling that code which ifdef'ing it out would not do.

**Comment by hartwork** [comment]
There is dedicated issue #115399 on the upgrade to 2.6.0 now.

**Comment by ronaldoussoren** [comment]
I'm closing this issue, resolving #115399 will also fix this issue.
