### ISSUE TITLE
json.dump method case causes a memory leak 

### ISSUE THREAD

**Issue by amsenhao** [python/cpython#112707]
# Bug report

### Bug description:

```python
import gc
import json
import sys
print(sys.version)
with open('xxxx', 'w') as f:
    json.dump("{}", f)
gc.set_debug(gc.DEBUG_SAVEALL)
gc.collect()
garbage=[]
for it in gc.garbage:
    garbage.append(it)
print ("garbage is : %s " % str(garbage))
print ("garbage len is: %d" % len(str(garbage)))
```
In our code,I user json.dump method and the number of unreachable objects grows beyond all limits,i try to user f.close(),but is didn't help. python version is 3.10.6

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Python 3.10 is old enough that it is only accepting bugfixes if they relate to security issues (and I don't think this qualifies). Can this be reproduced on Python 3.11 or higher?

**Comment by amsenhao** [comment]
Can you give it a try for me? 

> Python 3.10 is old enough that it is only accepting bugfixes if they relate to security issues (and I don't think this qualifies). Can this be reproduced on Python 3.11 or higher?

I think this problem also exists in version 3.11

**Comment by amsenhao** [comment]
I try to another way:
with open('/opt/test', 'w') as f:
   f.write(json.dumps(s))
garbage will not grow

**Comment by amsenhao** [comment]
why this way:
with open('/opt/test', 'w') as f:
    f.write(json.dumps(s))
garbage will not grow

**Comment by amsenhao** [comment]
> It will not grow because you didn't set `gc.set_debug(gc.DEBUG_SAVEALL)`, so the garbage collector is collecting unneeded (unreachable) objects.
no，i  set gc.set_debug(gc.DEBUG_SAVEALL)

**Comment by encukou** [comment]
Ah, I see.
That means the code you have left doesn't create objects which need to be collected.
