### ISSUE TITLE
MemoryError when bytes a big integer

### ISSUE THREAD

**Issue by CNLiuShuhan** [python/cpython#112755]
# Bug report

### Bug description:

```python
bytes(123456789012)
```
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    bytes(123456789012)
MemoryError

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
That's expected, ``bytes(some_integer)`` creates a bytes object of that length (filled with NUL values).  You're trying to create a bytes object of over 100 GB in size.
