### ISSUE TITLE
a for in loop restarts when lot of processing done within loop

### ISSUE THREAD

**Issue by madhurabindu** [python/cpython#112799]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
I have a program where i collect github repo and pull request data for an organization
I have a for loop where I collect / process and hold data
i noticed that at somepoint this loop just restarts
I think when it goes out of memory python just restarts the loop
I am attaching screenshots of my actual program here

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
Thanks for the bug report! However, please follow the instructions given in our issue form:
- Try to create a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
- Always copy-and-paste your code; [never post screenshots](https://meta.stackoverflow.com/a/285557/13990016).
