### ISSUE TITLE
SystemError when builtins is not a dict + eval

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#112716]
# Bug report

### Bug description:

If `__builtins__` is not a dict, you can get a SystemError:
```pycon
>>> import types
>>> exec("import builtins; builtins.print(3)", {"__builtins__": types.MappingProxyType({})})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    exec("import builtins; builtins.print(3)", {"__builtins__": types.MappingProxyType({})})
  File "<string>", line 1, in <module>
SystemError: Objects/dictobject.c:1761: bad argument to internal function
```

Originally found this while playing with https://oskaerik.github.io/theevalgame/

### CPython versions tested on:

3.11, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-112770
* gh-113103
* gh-113105

**Comment by JelleZijlstra** [comment]
Simpler repro case:
```
>>> exec("import whatever", {"__builtins__": 1})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    exec("import whatever", {"__builtins__": 1})
  File "<string>", line 1, in <module>
SystemError: Objects/dictobject.c:1761: bad argument to internal function
```

**Comment by serhiy-storchaka** [comment]
There are tests (`test_exec_globals_dict_subclass`, `test_exec_globals_error_on_get`, `test_exec_globals_frozen` in `test_builtin`) that explicitly test non-dict `__builtins__`. Support of non-dicts was added in bpo-14385/#58593. @vstinner, is this feature used?

**Comment by vstinner** [comment]
> @vstinner, is this feature used?

I don't know. But for now, I would prefer to fix bugs. If we decide to remove the feature, I suppose that it should be deprecated first?

**Comment by JelleZijlstra** [comment]
Worth noting that the use case that brought me here is real (if a little silly): the game wants to enforce that you don't use any builtins, and it enforces that by setting `__builtins__` to a proxy that records access (and delegates lookups to the underlying real builtins). That seems like a reasonable thing to do, so I think we should fix rather than deprecate the feature.

**Comment by serhiy-storchaka** [comment]
It's funny that this feature was originally added when trying to build a sandbox, and now it's used in a game that requires you to escape from a sandbox.

**Comment by JelleZijlstra** [comment]
The best features are the ones that turn out to be useful in unexpected places!
