### ISSUE TITLE
`unittest` Test Discovery page says "Python 3.11 dropped the namespace packages support," which is inaccurate

### ISSUE THREAD

**Issue by rodrigodesalvobraz** [python/cpython#112890]
# Documentation

The [documentation for `unittest` Test Discovery ](https://docs.python.org/3/library/unittest.html#test-discovery) says: "Changed in version 3.11: Python 3.11 dropped the [namespace packages](https://docs.python.org/3/glossary.html#term-namespace-package) support. It has been broken since Python 3.7. Start directory and subdirectories containing tests must be regular package that have __init__.py file."

I believe the most straightforward interpretation of this statement is that Python, _as a whole_, has dropped namespace packages, which I believe is false. I think the intended interpretation is "Changed in version 3.11: _unittest_ dropped the [namespace packages](https://docs.python.org/3/glossary.html#term-namespace-package) support in Python 3.11. It has been broken since Python 3.7. Start directory and subdirectories containing tests must be regular package that have __init__.py file.

### Linked PRs
* gh-113195
* gh-113228
* gh-113229

**Comment by tpackard1** [comment]
Hi @rodrigodesalvobraz, if you are not already working on this documentation update, I would like to work on it.

**Comment by rodrigodesalvobraz** [comment]
> Hi @rodrigodesalvobraz, if you are not already working on this documentation update, I would like to work on it.

Sure, thank you!

**Comment by serhiy-storchaka** [comment]
Thank you @rodrigodesalvobraz and @tpackard1 for reporting and fixing this issue.
