### ISSUE TITLE
build fails with -DWITH_PYMALLOC_RADIX_TREE=0

### ISSUE THREAD

**Issue by doko42** [python/cpython#112867]
# Bug report

### Bug description:

bpo-37448 added a radix tree based memory map, also allowing to disable it:

  To disable the radix tree map, set a preprocessor flag as follows:
  `-DWITH_PYMALLOC_RADIX_TREE=0`.

However building with that fails:

```
In file included from ../Include/internal/pycore_interp.h:31,
                 from ../Include/internal/pycore_runtime.h:18,
                 from ../Include/internal/pycore_pystate.h:11,
                 from ../Modules/_asynciomodule.c:7:
../Include/internal/pycore_obmalloc.h:668:28: error: field 'usage' has incomplete type
  668 |     struct _obmalloc_usage usage;
      |                            ^~~~~
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-112885
* gh-113068

**Comment by doko42** [comment]
@ericsnowcurrently, this is probably not working since issue gh-81057

**Comment by doko42** [comment]
looks like guarding the usage struct member with the same preprocessor define allows the build to succeed and also pass tests

**Comment by hugovk** [comment]
The PR has been merged 👍 

Can we close this issue, or is there more to do? Do we need backports to 3.12 or 3.11?

**Comment by nascheme** [comment]
I'm wrong, needs backport to 3.12.
