### ISSUE TITLE
parking_lot.c should check for overflow in Windows `_PySemaphore_PlatformWait` code path

### ISSUE THREAD

**Issue by colesbury** [python/cpython#112804]
# Bug report

The cast in `millis = (DWORD) (timeout / 1000000);` may overflow because `DWORD` is an unsigned 32-bit integer and `timeout` is a 64-bit integer. We should clamp the result if the cast would overflow.

https://github.com/python/cpython/blob/cc7e45cc572dd818412a649970fdee579417701f/Python/parking_lot.c#L93-L105

Noticed by @vstinner in https://github.com/python/cpython/pull/112733#pullrequestreview-1766327004

### Linked PRs
* gh-124914
* gh-124991

**Comment by corona10** [comment]
@colesbury, I am closing the issue if we need to reopen it. please let me know.

**Comment by colesbury** [comment]
Thanks for fixing this!
