### ISSUE TITLE
problem with pip install mysqlclient

### ISSUE THREAD

**Issue by S7saelgh** [python/cpython#112835]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
I started a project with django and python 12.0. I'm usig visual code studio by the way.that's the message error I got:       src/MySQLdb/_mysql.c(29): fatal error C1083: Datei (Include) kann nicht ge”ffnet werden: "mysql.h": No such file or directory
      error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.38.33130\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for mysqlclient
Failed to build mysqlclient
ERROR: Could not build wheels for mysqlclient, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.

Think you in advance for the help

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
This repository is intended as CPython bug tracker, your problem looks like absence of some `mysql` headers, which doesn't related to CPython. Please ask for help on discuss: https://discuss.python.org/c/users/7 or stackoverflow: https://stackoverflow.com
