### ISSUE TITLE
format() ignores leading 0 when `_` is used

### ISSUE THREAD

**Issue by doko42** [python/cpython#112876]
# Bug report

### Bug description:

seen with 3.11 and 3.12, trunk not tested

```pycon
>>> i = int.from_bytes(b'11112345', 'little')
>>> hex(i)
'0x3534333231313131'
>>> format(i, '064b')
'0011010100110100001100110011001000110001001100010011000100110001'
>>> format(i, '064_b')
'11_0101_0011_0100_0011_0011_0011_0010_0011_0001_0011_0001_0011_0001_0011_0001'
```

Expected output for the last line:

```
'0011_0101_0011_0100_0011_0011_0011_0010_0011_0001_0011_0001_0011_0001_0011_0001'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by mdickinson** [comment]
I think it's working as designed: the `64` there is a minimum width for the output rather than a digit (or in this case bit) count, so it takes into account the underscores. For formatting a number as 64-bit binary with underscores you'd want something like `format(i, '079_b')`, so that the width takes into account the expected 15 underscores.

**Comment by terryjreedy** [comment]
Mark is [correct](https://docs.python.org/3/library/string.html#format-specification-mini-language): "*width* is a decimal integer defining the minimum total field width, including any prefixes, separators, and other formatting characters."  No bug.
```
>>> format(i, '078_b')  # 1 leading 0
'011_0101_0011_0100_0011_0011_0011_0010_0011_0001_0011_0001_0011_0001_0011_0001'
>>> format(i, '079_b')  # 2 leading 0s
'0011_0101_0011_0100_0011_0011_0011_0010_0011_0001_0011_0001_0011_0001_0011_0001'
>>> format(i, '080_b')  # leading '0_' maked 81 chars; leading '_' is not allowed
'0_0011_0101_0011_0100_0011_0011_0011_0010_0011_0001_0011_0001_0011_0001_0011_0001'
```
