### ISSUE TITLE
data = conn.recv(1024) data is bytes,  how can i know what data  it is ?

### ISSUE THREAD

**Issue by jingyuLin1999** [python/cpython#112891]
# Feature or enhancement

### Proposal:

```python
    HOST = ''  # Symbolic name meaning all available interfaces
    PORT = 50007  # Arbitrary non-privileged port
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s:
        s.bind((HOST, PORT))
        s.listen(1)
        conn, addr = s.accept()
        with conn:
            print('Connected by', addr)
            while True:
                data = conn.recv(1024)
                if not data: break
                conn.sendall(data)
```
data bytes:
b'\x9a\xe6|\xc1X\x9b,\xb5\xf2\xb7\x13r7\xb6,4y\x1a\x87\xac\xcc\xcd\xa0\xd7\xe4\xc2\'\xe0\xbc\xca\xc3,\xbe\x87\xa4#\xf1\xc8\x12*\x1fMUC\x1e)v]\xd9\xfc\xbe\xc5\x9b\x85V\xc6-F\xd0\xa1x\x18\xfe\x1bF\xe0\xaa\t8\xba\xaaTt\xb3\xf4\x8f:\xbb\xcc\xee\xf4R\x1b@\x023\x01\xa0\x9f\\\xe8\x10q\xce\xd2\xf7\xee\x7fT\xd2\x87\x91\x042\xf1\x85E\xc3\xdf\x1e\xb5\x8eW\x14^\xecI\x8a\x95\x96,\x8f\xccj4\x06\x90\xe4\xf9\xad\xc0r\xc4\x90V\xb4:o\x00\x0c"[\xf8b\x17\xe0\x1d\x91\xf5\xbb\tq(#\x969P\x18n&*\xce\xf7\x17\xafg\xf8#?\xc1\xb7\xd4\xe1\x06n`\x88\xe6\x1d\xdb\x89\x9eR\xc8(\xb8\x96\xbe\xaf=\xc4\x07\x9a\x8a-eo\x99U\x17H\x83\xbbEV\xfe\x8d?\xda9d\x13\x12Pw\xc3\xba\x89J\x81!\xaa(\xbd5k\xd0.0\xa5\xd6~b\x90h\x85e\x03\xe1J\xea\x1d\xa64\xfeAv\xfc\x1a\x12\xd2P\x17\xba\xf2\x00NH\xf9\xdab\xc8\t\x84\xa9\x8fP\xb1\xa0\xe8Mf\xd5\xd5\xea\xfb\x88w\'\xee\x17\xc3b\xec\x81k\xd3[B\xfe\xf3\x7f\xbfJ\x9c\xfeTeyr\x07\xd6\x92\xb0\xb9\x9d\xb4\x88\xbal`]\xeea^\x96t\xeeta\x95\x12 \xe6\xf4\xcc\x90\rN<\xb9\x90"\x1c\x15\xa4"TS4\xbd\x83`\xbf\xfb\x9fO\xdfR^\xca\xe4\x8d\xe3k\x93H\xd5}$\x82\xbbTb\xdb\xad;\x06\xfc!/\x83&\x98pN\x1d\xad\x91u\x99\xde"\x05\xc2Bh\xfc$\x9c:\x8b\x9f\xf3\xd2\x92\x04\x1b\x1e\x0fLmv\x8b\\\xaa\xe9\xfcF\xff\xcb\xb6S\x9f\xf0\xcc\xab\xe5\x1b}\xe5\x0ei\x1dW\x99IY\x04-\x92\x8d1\x9d\x94\x81\xd1\x80\xec\xdf\x9f\xc7\x02\xe7\xc0\'\xacb.\tI|\xab3s-Yi\xa4D\xedH\xd6o\xc59^?\x0b\x9asx[\xcd+\x7f,\xc6\x9a5\x03~D\xf3.\xdb\x04N\xbf\x9b\xf0\x94\x1eS[P?#hw\xaeh\x82768 7-\xd0\xa8\x03kuc\x19B\xfc\xc3\x1a7\xab\x05\x84\xad\xe6\xbdw\x84\xe9$\xc6n\x8a\xc2? h$\x1d\x86\xafu\x96\xcc\xda\xed\xd1\xe2\xa5\x8aI\xef\xb6\xca\xd0\xbc\xe2_\xf8i\x8d\x9c\xb5\xc3\xa3l\xab\xcf[\xef^m\x9e\xaf\xc6\xc5q\x01\xcd\xfa\x97/M\xee\xea_\xee\xf8\xb2I\x19\x15^\xb9\xd4Q\xcf\x19\x85~\x8d\xd2\x99\x8c\x1e\x9e\x0b\xb3\xfa\x1c\x9d\xf1\x10\x81\xd7\r\x86\x98\xbeu\'\x97>\xa9\x13\x14\x0cR\xc9\xb5\tk\xa6\xfbu(\xe8y"F\x08\xac\xa1\xcf\x82\x1f+\x9b,0|\xc5\xac\xda\xe79\x88\xe8\xbb\xe3K\xdc\xeb\xd8\xf0\xe3\xe4\xda\x82.\xa6\xb3\xee\x9fR\xbf\xfd\x1d\xbbJ\xbf\xc8\xc6n*\x0e\xdf=\x83\xb1J\xb6|l\xdc\xb8-&\xf2\xb5D'

<strong style="color:'red'">It is possible add http header to data ?</strong> like change  x-forwarded-for ?

**Comment by zware** [comment]
This is neither a bug nor as far as I can tell a feature request.  Please ask for help on our [Discourse](https://discuss.python.org/c/help/7) forum.
