### ISSUE TITLE
Inconsistent current line indication if the script is edited after entering `pdb`

### ISSUE THREAD

**Issue by tanloong** [python/cpython#112952]
# Bug report

### Bug description:

1. create a `for-loop.py`

```python
for i in range(10):
    breakpoint()
    print(i)
```

2. run `python for-loop.py`, entering the pdb interface

3. insert a line to `for-loop.py` after `breakpoint()`

```python
for i in range(10):
    breakpoint()
    print("This is an inserted line.")
    print(i)
```

4. run `c` in pdb and the inserted line will be shown as current line indicated by `->`, but the actual current line to be executed is `print(i)`.

5. run `c` again. The `print(i)`, instead of the inserted line, will be executed.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
See #111051. There's no perfect solution for this but we should warn user. The PR #111052 has been sitting there for a while but I have not had the chance to grab a core dev for it :)

**Comment by tanloong** [comment]
Thanks for replying! Maybe I will keep this repeated issue open to hopefully attract some core dev's attention to the PR.
