### ISSUE TITLE
Boolean tests and assignments

### ISSUE THREAD

**Issue by 11raob** [python/cpython#112935]
It is not a matter of whether the syntax is consistent with other languages.  We are discussing python.  I think it is not appropriate to close the issue, just because one person has the power to do so.  

Why not let others see the feature of the language I point out here and let people have a chance to discuss it?

Try in python 3.11 . . .
```pytb
print(1 !== 2)
Cell In[18], line 1
print(1 !== 2)
^
SyntaxError: invalid syntax

print("cat" = "dog")
Cell In[19], line 1
print("cat" = "dog")
^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```
Why is the assignment operator used for integers, but not for strings? Or, why is the correct operator used for strings, but not consistently applied for integers?

Here, one writes print("cat" == "dog") to test whether one object is equivalent to the other, and the Boolean response is False. However, the same syntax is not used when one integer is queried as to its equivalence to another integer. Here, the code is written print( 1 != 2), and the output is True, because 1 ≠ 2. However, the operator changes. = is used for assignment in python, so why is it now used as a test for equivalence for integers but not for strings??? It is illogical. It should be print(1 !== 2). Python uses '=' for assignments, like sum = a + b. That expression will take a and add b to it and place that value (assign it) to the variable sum.

**Comment by Eclips4** [comment]
Hello! This looks like a featureq request, or ... I completely doesn't understand your message.
How do you get different result for ints and strings? Seems you missed something.
If it's feature request, please, open thread on https://discuss.python.org/c/ideas/6, but honestly, there is a very low chance that this will be accepted.

**Comment by hugovk** [comment]
Also duplicate of https://github.com/python/cpython/issues/112934.

**Comment by Tishka17** [comment]
= is used for assignment 
== is used for equality testing for all types
!= is used for inequality testing for all types.
!== does not exist in python

**Comment by evle-zzz** [comment]
Perhaps, as part of efforts of making error messages more helpful, the first one could be changed to `SyntaxError: invalid syntax, perhaps you meant "!="?`

**Comment by Eclips4** [comment]
> Perhaps, as part of efforts of making error messages more helpful, the first one could be changed to `SyntaxError: invalid syntax, perhaps you meant "!="?`

I would like to hear @pablogsal opinion on that :)

**Comment by pablogsal** [comment]
> Perhaps, as part of efforts of making error messages more helpful, the first one could be changed to `SyntaxError: invalid syntax, perhaps you meant "!="?`

The most common mistake is the missing `=` as normally people forget to type the second `=`. In general, is very very rare that someone types `!` without the `=` so I think it won't cover much real cases

**Comment by 11raob** [comment]
Everyone is missing the point.   
  

  
print(1 = 1) ==>  True
  
print(1 == 1) ==>  error
  
But, not
  
print("a" = "b") ==>  error, not False
  
It has to be   
  
print("a" == "b") ==>  False   
  
to not get the error.     
  

  
One of them is == and the other one is not ==.     
  

  
But = is for assignments, not Boolean test unless it's integers in python.     
  

  

  

  
  
  
  
  
>

**Comment by pochmann3** [comment]
> print(1 = 1) ==> True
> print(1 == 1) ==> error

No, it's the other way around.
