### ISSUE TITLE
Inconsistent programming and use of operators in Boolean comparison

### ISSUE THREAD

**Issue by 11raob** [python/cpython#112934]
Try in python 3.11 . . . 

```pytb
print(1 !== 2)
Cell In[18], line 1
    print(1 !== 2)
              ^
SyntaxError: invalid syntax

print("cat" = "dog")
Cell In[19], line 1
    print("cat" = "dog")
          ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
```

Why is the assignment operator used for integers, but not for strings?  Or, why is the correct operator used for strings, but not consistently applied for integers?  

Here, one writes print("cat" == "dog") to test whether one object is equivalent to the other, and the Boolean response is False.  However, the same syntax is not used when one integer is queried as to its equivalence to another integer.  Here, the code is written print( 1 !=  2), and the output is True, because 1 ≠ 2.  However, the operator changes.  = is used for assignment in python, so why is it now used as a test for equivalence for integers but not for strings???  It is illogical.  It should be print(1 !== 2).  Python uses '=' for assignments, like sum = a + b.  That expression will take a and add b to it and place that value (assign it) to the variable sum.

**Comment by JelleZijlstra** [comment]
The equality operator is `==` and the inequality operator is `!=`. That's not going to change, and it's consistent with many other programming languages.

**Comment by 11raob** [comment]
Well, consistent with other programming languages is a different matter.  I am discussing the internal consistency of python.

**Comment by terryjreedy** [comment]
@11raob This issue tracker is for making changes to Python docs and CPython code.  To discuss existing Pythons, please use the Help and Ideas channels of https://discuss.python.org/ or other similar forums.

**Comment by 11raob** [comment]
Sure.    It's my first time posting, so I'm glad to be pointed in the right direction.     
  

  

  

  
  
  
  
  
>
