### ISSUE TITLE
Error in example of `datetime.time.fromisoformat` 

### ISSUE THREAD

**Issue by F-park** [python/cpython#112925]
# Documentation

https://github.com/python/cpython/blob/5bf7580d72259d7d64f5ee8cfc2df677de5310a4/Doc/library/datetime.rst?plain=1#L1811-L1812

I consider the correct example should be below.
```pycon
>>> time.fromisoformat('04:23:01,000384') 
datetime.time(4, 23, 1, 384) 
```

## python docs version
- 3.11
- 3.12
- 3.13

### Linked PRs
* gh-112931
* gh-113427
* gh-113428

**Comment by hugovk** [comment]
Thanks for the report. 

Looks like a copy/paste error from the previous example:

```pycon
>>> time.fromisoformat('04:23:01.000384')
datetime.time(4, 23, 1, 384)
>>> time.fromisoformat('04:23:01,000')
datetime.time(4, 23, 1, 384)
```

The actual output (Python 3.11.7 and 3.12.1):

```pycon
>>> from datetime import time
>>> time.fromisoformat('04:23:01.000384')
datetime.time(4, 23, 1, 384)
>>> time.fromisoformat('04:23:01,000')
datetime.time(4, 23, 1)
```

Would you like to open a PR to fix it?

It would also be a good idea to add the doctest marker so these examples are actually tested. 

See `.. doctest::` elsewhere in the file.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @F-park.
