### ISSUE TITLE
macOS repeatedly (sometimes) asks access permission on startup

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#112916]
# Bug report

macOS Catalina, current 3.10 - 3.13: Perhaps half the times when I start some version of IDLE from the dock, macOS says "Python would like to access files in your Documents folder  [Don't Allow]  [OK]".  I navigated to Security & Privacy dialog, Privacy pane, Files and Folders tab, and the "Allow apps below access..." box already has "Python\n [X] Documents" checked.  But still it keep asking.

As best I remember, this nuisance behavior is relatively new -- perhaps a year.  Has the install script, or idle.app been changed?

**Comment by ronaldoussoren** [comment]
I don't get this in a VM running 10.15.7 (Latest bug fix release for Catalina).  I got a popup the first time I started IDLE for 3.12 (which I hadn't used in that VM until now), and get no pop-ups when I quit & restart.

Is there any pattern in when you get the pop-up?  For example, does this happen when quickly restarting, or only when you haven't used IDLE for a while?

**Comment by ronaldoussoren** [comment]
Some other questions:

- Did you install Python using our installer or manually?
- If you did use our installer, did you strip the code signatures (needed to use lldb to debug C issues)?
- If you did use our installer and haven't stripped code signatures: Have you made changes to the installed stdlib?

**Comment by terryjreedy** [comment]
I have 10.15.7, which apparently is the final upgrade for a mid-2012 machine.
I have 3.10 to 3.13 default option installs of  python.org installers.
I have edited idlelib files to test mac-specific changes, such as some of your recent proposals.  (No development system.  No git.)
If I close and immediately reopen, I do not see the popup.  Often, about a minute later, it will appear, even if no further edits.

I downloaded the 3.13.0a2 installer again, re-installed, and I have opened IDLE several time since at intervals of a minute to a few hours.  I have not seen the popup once.  I conclude that editing idlelib files was the cause.  Thank you for the implied suggestion.

Be default, the installer suggests deletion once it finishes.  This should be appropriate for most people, but this time I kept it.

**Comment by ronaldoussoren** [comment]
> I have 10.15.7, which apparently is the final upgrade for a mid-2012 machine. I have 3.10 to 3.13 default option installs of python.org installers. I have edited idlelib files to test mac-specific changes, such as some of your recent proposals. (No development system. No git.) If I close and immediately reopen, I do not see the popup. Often, about a minute later, it will appear, even if no further edits.
> 
> I downloaded the 3.13.0a2 installer again, re-installed, and I have opened IDLE several time since at intervals of a minute to a few hours. I have not seen the popup once. I conclude that editing idlelib files was the cause. Thank you for the implied suggestion.
> 

At least some of the security controls are tied to code signatures, either directly or through add-hoc signatures from the system.

One thing you could do to avoid the pop-ups is to slightly tweak `IDLE.app/Contents/Resources/idlemain.py`. At the top of that file we change the working directory to the user's Documents folder. Changing that to the user's home directory should avoid the pop up with little effect on the user experience. 

> Be default, the installer suggests deletion once it finishes. This should be appropriate for most people, but this time I kept it.

That's not something we can change, but behaviour from the installer app itself.
