### ISSUE TITLE
DictReader not reading all fields (but does read all fieldnames)

### ISSUE THREAD

**Issue by jonathan-geoseer** [python/cpython#112958]
# Bug report

### Bug description:

Python 3.9.12 (Anaconda on Windows 10)

The following code on the attached file works perfectly:
```python
	with open(filepath, 'rt', encoding='utf-8') as f:

		reader = csv.reader(f)

		for row in reader:
			print(len(row))
		exit()
```
It correctly prints there are two rows, both with 81 records:
> 81
> 81

The same code via DictReader:
```python
	with open(filepath, 'rt', encoding='utf-8') as f:

		reader = csv.DictReader(f)
		print(len(reader.fieldnames))

		for row in reader:
			print(len(row))
		exit()
```
Prints:
> 81
> 54

For some reason, DictReader is only reading 54 records on the data row. It correctly gets all the headers, despite them being convoluted, but is losing 27 empty fields.
I've double checked and there are 81 records in the data row.

There's nothing I can see in the documentation suggesting this should happen. The closest is: 

> If a row has more fields than fieldnames, the remaining data is put in a list and stored with the fieldname specified by restkey (which defaults to None). If a non-blank row has fewer fields than fieldnames, the missing values are filled-in with the value of restval (which defaults to None).

But neither of those scenarios is the case.
[test_csv.csv](https://github.com/python/cpython/files/13635549/test_csv.csv)

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
The 'convoluted' headers have embedded newlines.  The following on 64-bit Windows 10 with 3.13
```python
import csv
filepath = "f:/dev/tem/test_csv.csv"
with open(filepath, 'rt', encoding='utf-8') as f:
    reader = csv.DictReader(f)
#    for name in reader.fieldnames:
#        print(name)
    print(len(reader.fieldnames))
    for row in reader:
        print(row)
        print(len(row))
```
prints 81, 54 as claimed.  The reason is that there are duplicate fieldnames, as can easily be seen by uncommenting the two lines I added.  Dicts, by definition, have unique keys and there must be only 54.

**Comment by jonathan-geoseer** [comment]
Yes, I'm aware there are duplicate fieldnames (part of the "convoluted"), and also that you can't have duplicate keys in Dicts. I was having a forest-for-the-trees moment in not joining those two together. Sorry about that.

That said, I believe this is still a bug, albeit in the other direction to what I originally posited:

As far as the DictReader is concerned, there are only 54 valid fieldnames in that file. So the script should return:
```
>54
>54
```

Returning a list of fieldnames that don't match the fieldnames in the data is non-sensical and highly unexpected behaviour.

If that remains "Won't fix", at the very least I'd like to suggest this is a documentation omission: it shouldn't be left to the user to infer/deduce how a function works with edge cases.
