### ISSUE TITLE
asyncio task_factory does not receive name parameter

### ISSUE THREAD

**Issue by ordinary-jamie** [python/cpython#113050]
# Bug report

### Bug description:

The `asyncio.BaseEventLoop.create_task` loop method [does not pass the `name` parameter to the task factory](https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L462-L468)

There is two issues with this:

1. [Inconsistent with the eager task factory signature](https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L462-L468)
2. Users cannot easily configure the task name through just the task factory interface 

A simple demonstration of this issue:

```python
import asyncio


def new_task(loop, coro, name=None, context=None):
    assert name is not None  # Will raise

    return asyncio.Task(coro, loop=loop, name=name, context=context)


async def main():
    loop = asyncio.get_event_loop()
    loop.set_task_factory(new_task)
    loop.create_task(asyncio.sleep(1), name="task1")


if __name__ == "__main__":
    asyncio.run(main())

```

Also see: https://github.com/python/cpython/pull/112623#issuecomment-1837405443

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-113051

**Comment by gvanrossum** [comment]
(I am not ready for a review yet, but as I see you are fond of force-pushing, can you please not do that? It makes the review cycle more complicated. It is also unnecessary since at the end we always squash-merge.)

**Comment by gvanrossum** [comment]
Hm. `set_task_factory` is [documented](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.set_task_factory) as taking a function of two positional arguments (`loop`, `coro`) and one keyword arg (`context=None`). If we start adding `name=...` to the call, we break this contract. In particular, working user code that declares a task factory as a function with exactly the suggested signature will raise an exception when called with `name=...`.

I don't think we can change this. There are similar backwards compatibility issues with other APIs outside asyncio where we have a similar constraint that prevents us to change the signature of a user-provided callback (e.g. `__exit__`), and we just live with it.

**Comment by ordinary-jamie** [comment]
>  In particular, working user code that declares a task factory as a function with exactly the suggested signature will raise an exception when called with name=....

Yup this would be a breaking change for users. I can close/park the PR and issue :) 

Is there anything we need to do around [`eager_task_factory`](https://docs.python.org/3/library/asyncio-task.html#asyncio.eager_task_factory)? The signature is misleading as it does have the `name` kwarg

> asyncio.eager_task_factory(loop, coro, *, name=None, context=None)
>   A task factory for eager task execution.
>   When using this factory (via [loop.set_task_factory(asyncio.eager_task_factory)](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.set_task_factory)),

**Comment by gvanrossum** [comment]
> Is there anything we need to do around [`eager_task_factory`](https://docs.python.org/3/library/asyncio-task.html#asyncio.eager_task_factory)? The signature is misleading as it does have the `name` kwarg

I think we should leave it alone, since 3.12 went out with this signature, and people *could* be calling it directly rather than passing it to `set_task_factory()`.

I think closing the PR is the only thing to do.
