### ISSUE TITLE
Putting "^" in if block and writing "=" gives the result of "^"

### ISSUE THREAD

**Issue by Suncode123** [python/cpython#113058]
# Bug report

### Bug description:

```python
x = int(input("Write the first number: "))
op = input("Write the operation you want to use: ")
y = int(input("Write the second number: "))
if op == "**" or "^":
     print(x**y)
else:
     print("This operation is not recognised")

a = int(input("Enter first number: "))
operation = input("Write the operation you want to use: ")
b = int(input("Enter the second number: "))
if operation == "**":
     print(a**b)
else:
     print("This operation is not recongised")
```
If we write the input for the "op" variable as "=", then python acts as if the "=" is the "^" symbol when it is not. We can confirm this by running the code above.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Expression `op == "**" or "^":` always evaluates to `True`, because `bool("^"`) is True.
You should have written `op == "**" or op == "^"`.
For the next time, please, ask for help on https://discuss.python.org/c/7
