### ISSUE TITLE
the esoteric behavior of x+=n when compared to x=x+n in iterable objects

### ISSUE THREAD

**Issue by nvnarayna** [python/cpython#113007]
# Feature or enhancement

### Proposal:

the += for lists calls a different function compared to = this is very esoteric and hinders code readability

```
l=[]
l=l+"hello"

```
which returns TypeError: can only concatenate list (not "str") to list whereas ;
```

l=[]
l+="hello"
print(l)
```
returns output ['h', 'e', 'l', 'l', 'o']

+= behaves similar to .extend here. how to go about changing this so its easier to understand ?
pythons main use cases are readability and this hinders it and is not pythonic.
i would request this to work similar to the expanded version.

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
Hello!
That's would be a big breaking change (although list concatenation is not widely used).
For this type of changes, first of all, please, open the topic on https://discuss.python.org/c/ideas/6.
Now, I'm closing this. We can reopen this later if necessary.

**Comment by terryjreedy** [comment]
The behavior observed is specified in the Operation table for [mutable sequences](https://docs.python.org/3/library/stdtypes.html#mutable-sequence-types):
> | s.extend(t) or s += t | extends s with the contents of t (for the most part the same as s[len(s):len(s)] = t) | 

where s is a mutable sequence and t is an iterable.  While feature changes should be discussed on discourse, there is essentially no chance of changing basic operations like this.
