### ISSUE TITLE
DeepChainMap

### ISSUE THREAD

**Issue by uemit61** [python/cpython#113075]
# collections

class DeepChainMap(ChainMap)...

the code of this class is not korrect.
In the Example the passed Objects are Dictionarys and not a ChainMap, if you pass
a ChainMap you will get a KeyError.

I have changed it like this...:

class DeepChainMap(ChainMap):
    
    
    
    def __setitem__(self,key,value):
        for m in self.maps:
            if key in m:
                m[key] = value 
                return 
        self.maps[0][key]=value
        
        
        
    def __delitem__(self,key):
        
        if type(self.maps[0]) is ChainMap: # otherways like in the Example it is a Dictonary
            for m in self.maps[0].maps:
                if key in m:
                    del m[key]
                    return
        else:
            for m in self.maps:
                if key in m:
                    del m[key]
                    return 
                
        raise KeyError(key)

**Comment by gaogaotiantian** [comment]
This is the same issue as #113074 so close this for dup.
