### ISSUE TITLE
Python 3.11.7 Test Suite Failure in Windows - Interpreter has more than one thread

### ISSUE THREAD

**Issue by plooploops** [python/cpython#113026]
# Bug report

### Bug description:

I was running the python `3.11.7` test suite in a windows container (e.g. with `python -m test --ignorefile C:\path\to\my\ignorefile`) and noticed the following Runtime errors when running the test suite:

```console
test test__xxsubinterpreters failed -- Traceback (most recent call last):
  File "C:\path\to\cpython\Lib\test\test__xxsubinterpreters.py", line 489, in test_main
    self.assertTrue(interpreters.is_running(main))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: interpreter has more than one thread
```

```console
test test_interpreters failed -- Traceback (most recent call last):
  File "C:\path\to\cpython\Lib\test\test_interpreters.py", line 247, in test_main
    self.assertTrue(main.is_running())
                    ^^^^^^^^^^^^^^^^^
  File "C:\path\to\cpython\Lib\test\support\interpreters.py", line 82, in is_running
    return _interpreters.is_running(self._id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: interpreter has more than one thread
```

As a workaround I can add the test cases to the ignore file, but it would be worth understanding if this is a regression.

* I was able to run `python -m test --ignorefile C:\path\to\my\ignorefile` for python `3.11.6` and I did not need to ignore these tests to complete the test suite in a windows container

### CPython versions tested on:

3.11.7

### Operating systems tested on:

Windows (windows servercore ltsc2019)

**Comment by aisk** [comment]
This has been fixed by https://github.com/python/cpython/pull/109921, and that PR was backported to the 3.12 branch. But as https://devguide.python.org/versions/ shows, 3.11 will only accept security fixes starting from two months ago, so I think we won't backport that PR to 3.11.
