### ISSUE TITLE
lstrip and rstrip altered behaviour

### ISSUE THREAD

**Issue by francescopelizza-omega** [python/cpython#113004]
# Bug report

### Bug description:

As far as I was concerned about lstrip and rstrip functionality back in 2016-2018, such method was stripping starting from left or right (respectively) the matching pattern into a string, until such pattern was broken from any character

So, wanted to remove 'foo)' pattern from 'foo)foobar' or 'foo) foobar' strings?
then: 
```
>>> a = 'foo)foobar'# or 'foo) foobar'
>>> a.lstrip('foo)')
'foobar'# or ' foobar'
```
and only the left mathcing pattern 'foo)' was cleared with or without a SPACE between 'foo)' and 'foobar' elements

NOW on, I've found that the behaviour is a bit different, lstrip and rstrip doesn't limitate to a regex walk from one side of the string until any static match is found from one side until any characters breaks up the regex matching but is much more dynamic and to me also less useful and anyway buggy, because if I want something more dynamic I would use replace method instead or jumping into regex method

In this moment lstrip or rstrip does keep walking through a string and if no spaces are found the method eats up much differently the string

So here I leave the current code that produces the bug, hope it helps to improve the method

```python
#!/usr/bin/python3

a = "foo"
b = "bar"
a_string = '%s)'%(a)
for i in range(5):
	a_string += ' %s'%(a)
a_string += ' %s'%(b)
print('Original string:', a_string)
a_string = a_string.lstrip('%s)'%(a))
print('Correctly stripped:', a_string)
print('\nNORMAL BEHAVIOUR UP TO THIS POINT\n\nThen removing the SPACE in the for loop filling up string...\n')

a_string = '%s)'%(a)
for i in range(5):
	a_string += '%s'%(a)# NO SPACE betwenn 'foo' repetitions
a_string += ' %s'%(b)
print('Original string:', a_string)
a_string = a_string.lstrip('%s)'%(a))
print('Wrongly stripped:', a_string)

##########
print('\nSWITCH to rstrip same thing...\n')

a_string = '%s'%(b)
for i in range(5):
	a_string += ' %s'%(a)
a_string += '%s)'%(a)
print('Original string:', a_string)
a_string = a_string.rstrip('%s)'%(a))
print('Correctly stripped:', a_string)
print('\nNORMAL BEHAVIOUR UP TO THIS POINT\n\nThen removin the SPACE in the for loop filling up string...\n')

a_string = '%s '%(b)
for i in range(5):
	a_string += '%s'%(a)# NO SPACE betwenn 'foo' repetitions
a_string += '%s)'%(a)
print('Original string:', a_string)
a_string = a_string.rstrip('%s)'%(a))
print('Wrongly stripped:', a_string)

```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, macOS

**Comment by ronaldoussoren** [comment]
`"foo)foobar foo".rstrip("foo")` removes characters from the right of the string that are in `"foo"`, and hence ends up with `"bar foo"` as the result. This is comparable to the following (untested) snippet:

```python

s = "foo)foobar foo"
while s and s[0] in "foo":
    s = s[1:]
```

To remove a prefix or suffix use the `removeprefix` and `removesuffix` methods

**Comment by francescopelizza-omega** [comment]
> `"foo)foobar foo".rstrip("foo")` removes characters from the right of the string that are in `"foo"`, and hence ends up with `"bar foo"` as the result. This is comparable to the following (untested) snippet:
> 
> ```python
> s = "foo)foobar foo"
> while s and s[0] in "foo":
>     s = s[1:]
> ```
> 
> To remove a prefix or suffix use the `removeprefix` and `removesuffix` methods

I do not see the benefit of this as if lstrip and rstrip works this way than the method replace is not much more helpful as lstrip and rstrip are too aggressive. Also if, you put spaces into the string, lstrip and rstrip does behave as in the old way, they stop when the regex brokens. Furthermore, also your method I tested does ignore the parenthesis as in my example, and if you try to do you're way with the pattern "foo)", it will eat up also the next 'foo', which shouldn't, unless there is a space to broke pattern match which then makes it to behave as it supposed to be.

To me is a bug

**Comment by ronaldoussoren** [comment]
I'm afraid I don't understand what you're trying to say.  In particular, the snippet in your report gives the same result in Python 3.11 and 3.9 or even 2.7.

Could you give a clearer example of what you expect that happens and what you actually see?

Something like:

```python

input_value = "..."
result = input_value.rstrip("...")
assert result == "..."
```

Obviously with the values `"..."` replaced by the actual values.

**Comment by ronaldoussoren** [comment]
The first "wrong" result according to your script is:

`'foo)foofoofoofoofoo bar'.lstrip('foo)') == " bar"`

This is entirely correct behaviour, the argument to ``lstrip``, ``rstrip`` and ``strip`` is a string with characters to remove from the left, right or both ends.  `lstrip("foo)")` will remove every character from the left of the string that is in the set `{"f", "o", "o", ")"}`.   This behaviour is exactly the same as in 2.7 (I checked).

There is no bug here.
