### ISSUE TITLE
Join abirtary joining str(int) with str(decimal)

### ISSUE THREAD

**Issue by JavaBabyX** [python/cpython#113063]
# Bug report

### Bug description:
This may actuallly be a critical vulnerability or it's using bitwise operations which...
it fails to hold numbers as string  in when getting from a list, with  operations  faster than Omega of n
```python 3.11
'34'.join('2.16')
```

### CPython versions tested on:

3.11

### Operating systems tested on:

linux: ubuntu 23.latest

**Comment by Eclips4** [comment]
Hello!
`str.join(str)` works as expected:
```python
>>> '34'.join('2.16')
'234.341346'
```
Can you please elaborate?

**Comment by zware** [comment]
Please see the [documentation for `str.join`](https://docs.python.org/3/library/stdtypes.html#str.join): for a `str` object `a`,  `a.join(b)`, the method iterates over `b` and returns a string with `a` inserted between every element of `b`.

**Comment by JavaBabyX** [comment]
> Hello! `str.join(str)` works as expected:
> 
> ```python
> >>> '34'.join('2.16')
> '234.341346'
> ```
> 
> I'm do not understand how it's related to numbers. Can you please elaborate?

Hello looks like Im not accustomed to the logic behind the join operation, I'll do some research.
I expect the result to be 342.16 as in join 34 and 2.16
I have checked and it's that '.' is a join operator so it wouldnt work with decimals unless I go Unicode or escape char
thank you for helping with this
