### ISSUE TITLE
Can't import `concurrent.futures.thread` at shutdown

### ISSUE THREAD

**Issue by pitrou** [python/cpython#113060]
# Bug report

### Bug description:

Simple reproducer (real-world [bug report](https://github.com/apache/arrow/issues/35237) is a bit more complex):
```python
import threading


def use_cf():
    import concurrent.futures.thread


def main():
    t = threading.Thread(target=use_cf)
    t.start()


if __name__ == "__main__":
    main()
```

### CPython versions tested on:

3.10, 3.11, 3.12, 3.13

**Comment by pitrou** [comment]
I don't know if we want to do anything about this, I'm just posting just in case.

@gpshead

**Comment by gpshead** [comment]
In general we consider this working as intended (from the linked bug):

```
$ python main.py 
Traceback (most recent call last):
  File "pyarrow/pandas-shim.pxi", line 100, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow/pandas-shim.pxi", line 48, in pyarrow.lib._PandasAPIShim._import_pandas
  File "/home/jleibs/pyarrow-repro/venv/lib/python3.10/site-packages/pyarrow/pandas_compat.py", line 24, in <module>
    import concurrent.futures.thread  # noqa
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 37, in <module>
    threading._register_atexit(_python_exit)
  File "/usr/lib/python3.10/threading.py", line 1504, in _register_atexit
    raise RuntimeError("can't register atexit after shutdown")
RuntimeError: can't register atexit after shutdown
```

After the main interpreter thread has exited, launching new threads isn't really supported.

This has been true since 3.9 thanks to https://github.com/python/cpython/commit/b61b818d916942aad1f8f3e33181801c4a1ed14b which resolved Issue #83993 via PR #19149.

**Comment by pitrou** [comment]
The problem isn't launching new threads here, it's simply importing the module. In other words, `c.f.thread` is imported as a side effect of the user importing another module after shutdown has started, even though the executor functionality wouldn't have been used anyway. It is of course possible to workaround by catching the `RuntimeError`, but it's a bit of a pointless annoyance.

**Comment by pitrou** [comment]
In general, I think it's a good idea for module import to be graceful, even though it can be complicated to achieve in some cases (and `concurrent.futures` is of course a complex module).

**Comment by gpshead** [comment]
It isn't reasonable to expect all non-trivial imports to work in a
finalization context.
