### ISSUE TITLE
Why not ``Type "help()", "copyright()", "credits()" or "license()" for more information.``?

### ISSUE THREAD

**Issue by linus-md** [python/cpython#113126]
# Documentation
Why does it say ``Type "help", "copyright", "credits" or "license" for more information.`` instead of 
``Type "help()", "copyright()", "credits()" or "license()" for more information.`` which would also fit in a 80 char terminal line.

It would also make this obsolete.
```
>>> license
Type license() to see the full license text
```

**Comment by hugovk** [comment]
This is a duplicate of https://github.com/python/cpython/issues/104471. I think someone is going to look into this for 3.13 🤞
