### ISSUE TITLE
`http.client.HTTPResponse.read1` does not close response after reading all data

### ISSUE THREAD

**Issue by illia-v** [python/cpython#113199]
# Bug report

### Bug description:

While trying to use `read1` in urllib3, we discovered that `read1` unlike `read` never closes the response after reading all data when the content length is known (https://github.com/urllib3/urllib3/pull/3235).

---

```python
import http.client

conn = http.client.HTTPSConnection("www.python.org")
conn.request("GET", "/")
response = conn.getresponse()
```

This runs successfully:
```python
response.read()
assert response.isclosed()
```

This fails:
```python
while response.read1():
    pass
assert response.isclosed()
```

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-113200
* gh-113259
* gh-113260

**Comment by serhiy-storchaka** [comment]
Is it a bug? The next reading operation will return an empty bytes and close the connection. So it may be just an optimization.

The `read1()` method was added in 8e5d0caf923ba027f21a2a0953a365bc6174d492 (bpo-19009/#63209), several years after adding autoclose when read all data in 7066590736bb61b5f67ade490aeee327af4bc6e2 (bpo-1580738/#44147). Why this was not added in `read1()` and `readline()`? @kristjanvalur, @pitrou, was it just an oversight or were there reasons for it?

**Comment by pitrou** [comment]
This was probably an oversight and I think this should be fixed.

**Comment by illia-v** [comment]
> Is it a bug? The next reading operation will return an empty bytes and close the connection.

Closing won't happen when the content length is known.

https://github.com/python/cpython/blob/21d52995ea490328edf9be3ba072821cd445dd30/Lib/http/client.py#L661-L665

After it has read all data, any subsequent call will reset `n` to `self.length` equal to 0 on line 662. Because of this closing will be skipped.

**Comment by kristjanvalur** [comment]
Nice necro.  Yes, probably an oversight.  The original impetus was to read from streams that didn't close.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @illia-v.

**Comment by pquentin** [comment]
Thanks everyone! Can this be closed now?

**Comment by illia-v** [comment]
@serhiy-storchaka @pitrou @kristjanvalur @pquentin thank you for your attention!
