### ISSUE TITLE
Support concatenation of Path object with strings using the + operator

### ISSUE THREAD

**Issue by songyuc** [python/cpython#113176]
# Feature or enhancement

### Proposal:

I would like to propose adding support for directly concatenating a Path object with a string using the + operator. Currently, when we want to concatenate a Path object and a string, we need to use the joinpath() method, which can make the code less intuitive and concise.

It would be great if we could simply use the + operator to concatenate a Path object and a string, similar to how we concatenate strings. This would provide a more natural and intuitive way to combine paths.

Example:
```python
from pathlib import Path

path = Path('/home/user')
result = path + 'project'
print(result)  # Expected output: /home/user/project
```

I believe that supporting the + operator for concatenation would improve the readability and simplicity of code that involves path manipulation. It would also align with the common practice of using the + operator for string concatenation in Python.

I would appreciate your feedback on this idea and whether it aligns with the goals and design principles of Pathlib. If there are any concerns or alternative suggestions, I would be happy to discuss them further.

Thank you for considering this enhancement!

### Has this already been discussed elsewhere?

No response given

**Comment by ronaldoussoren** [comment]
That's already possible using the ``/`` operator, e.g.:

```
from pathlib import Path

path = Path('/home/user')
result = path / 'project'
print(result)  # Prints: /home/user/project
```

**Comment by AlexWaygood** [comment]
Thanks for the feature request. However, I agree with @ronaldoussoren -- I don't think we need two operators doing the same thing. That would just be confusing :)
