### ISSUE TITLE
Harmonize shutil.copymode() on Windows and POSIX

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#113188]
The behavior of `shutil.copymode()` on Windows was changed by adding `os.lchmod()` in #59616. Now if *follow_symlinks* is false and both *src* and *dst* are symlinks, it copies the symlink mode (only the read-only bit). Previously it did nothing.

But there is still a difference between Windows and POSIX. If *follow_symlinks* is true and *dst* is a symlink, it sets the permission of the symlink on Windows (because `os.chmod()` still does not follow symlinks by default on Windows)  and the permission of the target on POSIX.

`shutil.copystat()` has different behavior, because it passes the *follow_symlinks* argument explicitly.

I propose to harmonize `shutil.copymode()` behavior on Windows with POSIX and with `shutil.copystat()`.

### Linked PRs
* gh-113189
* gh-113285
* gh-113426

**Comment by serhiy-storchaka** [comment]
I am not sure whether this change should be backported.

**Comment by zooba** [comment]
> I am not sure whether this change should be backported.

I left a comment on the PR pointing out the logic is too complicated for me to see exactly what changed. However, I'd suggest that as this function doesn't really do much of interest on Windows (read only property is the only mode we support, and it's not a security attribute), chances are the only people using it are using it for POSIX and just glad it works elsewhere.

If they'll be glad that their non-readonly (rare) symlink to a (rare) readonly file now correctly copies the readonly attribute, then I'd say backport. (I maybe misunderstood the scenario, but I think the logic applies no matter, so probably backport after explaining the logic clearly in the docs.)

**Comment by serhiy-storchaka** [comment]
#113285 is a solution for 3.12.

**Comment by zooba** [comment]
Is there a specific reason we should fix `copymode`/`copystat` but not `chmod` in 3.12? Or just leave them all for 3.13 only?

**Comment by serhiy-storchaka** [comment]
My main motivation is to avoid adding complicated `versionchanged` directives and What's New entry. They are not needed for bugfix.

Backporting changes in `chmod` does not help much without backporting the addition of `os.lchmod`, because some code tests its existency. And this is further in a "new feature" territory. If do not backport `os.lchmod`, the code will be of similar complexity to #113285.

**Comment by zooba** [comment]
Fair enough. Backporting the fix for the high level function seems okay to me now.
