### ISSUE TITLE
Improving error message with trailing comma in json

### ISSUE THREAD

**Issue by kno10** [python/cpython#113149]
# Bug report

### Bug description:

```python
import json
json.loads('{"a":1,}')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 8 (char 7)
```
The error is the trailing comma.

Initial pull proposal: #113047 but apparently this needs more attention than I can contribute.
The actual fix needs to be further down, possibly in line 206
https://github.com/python/cpython/blob/25061f5c98a47691fdb70f550943167bda77f6e0/Lib/json/decoder.py#L199-L208
we already know that we have seen a comma, and can insert a more helpful error message in line 206.
```python
if nextchar == '}':
    raise JSONDecodeError("No trailing commas allowed in JSON objects.", s, end - 1)
```
at this location, the previous character must have been a comma (line 201). Whitespace has been removed, so this will also catch `,\n}`

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-113227

**Comment by serhiy-storchaka** [comment]
You are welcome. Looks like it will work. Do you want to create a PR? A similar special case for a trailing comma can be added for parsing JSON array.
