### ISSUE TITLE
IDLE - Fix test_editor hang on macOS with installed Python

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#113269]
On my MacBook Air Catalina, Python 3.13.0a2, IDLE's test_editor hangs in IndentSearchTest.test_searcher.  The problem is `insert` using `update()` instead of `update_idletasks()`.  I added function in bpo-39885.  It is called earlier in IndentAnd...Test without failure.
 

### Linked PRs
* gh-113271
* gh-113272
* gh-113273

**Comment by hugovk** [comment]
I think this can be closed now, please re-open if needed.
