### ISSUE TITLE
unexpected behavior with re and strings with new-line-character '\r'

### ISSUE THREAD

**Issue by froiloc** [python/cpython#113206]
# Bug report

### Bug description:

```python
import re

print(re.findall(r'(?:^|(?<=(?:\r|x)))a*(?=x|$)', "\raaaaaaaaa"))
print(re.findall(r'(?:^|(?<=(?:\r|x)))a*(?=x|$)',  "xaaaaaaaaa"))
print(re.findall(r'(?:^|(?<=(?:\r|x)))a*(?=$)',    "xaaaaaaaaa"))
```
The idea of the pattern is to get all letter a that are either at the beginning of the string, preceded by an 'x' or by a new-line '\r'. And the string should either end with an a or an x, where the x should not be part of the match, as it is just look ahead. Similar it is with the beginning of the string, the new-line or x should not be part of the match.

If you compare the second and the third pattern, it is pretty weird that removing the option of an 'x' at the end of the string will change the result, though no x is present in the given string.

It is all very unexpected behavior. I had a "fight" with chat-GTP about this. It could not understand the behavior as well.

This kept me up all night.

I use Python 3.10.12 on Ubuntu 22.04. I have just tested it with an online python console which runs on version 3.8.5 (https://www.online-python.com/zBy8uacXGO). The behavior was the same in Python 2.7. Same with version 3.10.6 (http://tpcg.io/_OS2L2L). 

The expected output is
```
['aaaaaaaaa']
['aaaaaaaaa']
['aaaaaaaaa']
```

But I get
```
['aaaaaaaaa']
['', 'aaaaaaaaa']
['aaaaaaaaa']
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
```python3
print(re.findall(r'(?:^|(?<=(?:\r|x)))a*(?=x|$)',  "xaaaaaaaaa"))
```

You got `['', 'aaaaaaaaa']` and that looks correct to me:

First match is an empty string: start of string followed by a string of 0 `a`s and a lookahead assertion for an `x`.  After that match the first `x` is not consumed and is used for the look before assertion for the second match with a number of `a`s followed by the end of the string.

**Comment by froiloc** [comment]
```Python
import re

# here a little simplified version
print(re.findall(r'(?:^|[\rx])a*(?=x|$)', "\raaaaaaaaa"))
print(re.findall(r'(?:^|[\rx])a*(?=x|$)',  "xaaaaaaaaa"))
print(re.findall(r'(?:^|[\rx])a*(?=$)',    "\raaaaaaaaa"))
print(re.findall(r'(?:^|[\rx])a*(?=$)',    "xaaaaaaaaa"))
```
The output once again is
```
['\raaaaaaaaa']
['', 'xaaaaaaaaa']
['\raaaaaaaaa']
['xaaaaaaaaa']
```

The expected behavior is
```
['\raaaaaaaaa']
['xaaaaaaaaa']
['\raaaaaaaaa']
['xaaaaaaaaa']
```

I do not understand why the second command returns two strings, while the first and third do not. The behavior is not consistent, where I think it should be.

Playground:
https://www.online-python.com/2GJFmH0IYu

Maybe I do suffer on sleep deprivation after thinking about this for too long. But I still find this behavior unexpected and inconsistent.

**Comment by froiloc** [comment]
Alright. Sleep deprivation it is. Thank you @ronaldoussoren!

**Comment by terryjreedy** [comment]
'\r' is a return character, not a newline.  In any case, replacing \r everywhere in the initial example with \n or y or presumably any char other than 'a' results in the same behavior.  (Verified on 3.13.0a2.)  Same for 'y' substitution in simplified version.
