### ISSUE TITLE
Connection not closing when internet is switched off in between

### ISSUE THREAD

**Issue by scienmanas** [python/cpython#113215]
# Bug report

### Bug description:

```python
try : 
            connection = smtplib.SMTP("smtp.gmail.com")
            connection.starttls()
            connection.login(user=self.MailSenderAddress, password=self.Password)
            connection.sendmail(object_1["From"], [receipient], object_1.as_string())
            connection.quit()
            print(f'Email sent successfully to {Style.BRIGHT}{Fore.YELLOW}{name}{Fore.RESET}{Style.RESET_ALL}')
            return "sent"
        except Exception as e :
            print(f"{Style.BRIGHT}{Fore.RED}Email could not be sent to{Fore.RESET} {Fore.YELLOW}{name}{Fore.RESET} : {Fore.RED}{str(e)}{Fore.RESET}{Style.RESET_ALL}")
            return "failed"
```
![image](https://github.com/python/cpython/assets/99756067/3adc6da6-6ac7-403d-8481-508bbe8f4205)

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment]
The code posted will not run due to the indent of the `except` clause.  It is missing the loop statement that would cause it to be executed 3 times to send 3 mails.  I don't see the bug, as a new connection would be made each time through the loop.

**Comment by scienmanas** [comment]
the code is in a function and I am calling this function in another part of my code, So in all you can suppose this is in a loop and if the internet is switched in between when it loops its doesn't stop by itself, I have to specifically include timeout value to stop if a problem happens with internet connection

**Comment by ronaldoussoren** [comment]
That's how TCP works, sessions will stay active until something along the path tells the client that the destination is unreachable or until some internal OS timer runs out (which could be a long time). [This stackoverflow question](https://stackoverflow.com/questions/13085676/tcp-socket-no-connection-timeout) has an answer that explains this better than I could here.

You'll see the same behaviour when using tools like telnet or netcat (nc) to open the connection.

**Comment by scienmanas** [comment]
Ok, I understood its not a bug, what about adding a timeout of 2 min for smtp library, cause it just keeps on running on in such scenarios.

**Comment by ronaldoussoren** [comment]
Smtplib already supports a timeout, see [the documentation](https://docs.python.org/3/library/smtplib.html#smtplib.SMTP). I haven't checked, but the documentation suggest the timeout works for all blocking operations.

Adding a default timeout can break existing use cases, I have use cases where I loose connections to a wifi network for minutes at a time while roaming.
