### ISSUE TITLE
Simplifying of for statment

### ISSUE THREAD

**Issue by spisarau** [python/cpython#113250]
# Feature or enhancement

### Proposal:

Like any other language Python has loop statement **for**. 
Now it has following notation 
**for item in list_of_items:**
But what if we can add notation like this 
**for list_of_items:** 
and instead of using item we reserve a some word for this pusrpose, like an option we can use the name of the list just removing the last letter 's'. 
Examples :
```
for cats:
 print(reserved_value)
```

```
for dogs:
 print(dog)
```

### Has this already been discussed elsewhere?

No response given

**Comment by mattprodani** [comment]
Fixing a variable name by dropping a suffix `'s'` is quite an arbitrary decision. Similarly, reserving a keyword is not a simple solution; (How would you handle nested loops?). As far as I know functionality there is no implementation for a feature like this in any popular language (Scala has something similar with `_`, but only within lambda functions).

**Comment by Eclips4** [comment]
Hello!
Please, open a topic on discuss.python.org/6/ideas.
IMO, the chance of acceptance is very low: "Implicit better then explicit". Now I'm closing it, we can reopen it later if necessary.

**Comment by spisarau** [comment]
> Fixing a variable name by dropping a suffix 's', but in many examples people doing this stuff by themselves, so why can't we move this work to the system. 
`reserving a keyword is not a simple solution; (How would you handle nested loops?)`
maybe it is, but if get into something related with nesting we can use lists
```
for dogs:
 print(reserved_value[0])
 for dogs:
 print(reserved_value[1])
```
