### ISSUE TITLE
Add remaining TOML types to tomllib conversation table documentation

### ISSUE THREAD

**Issue by ryan-duve** [python/cpython#113234]
# Documentation

[The conversion table for Python's TOML parser](https://docs.python.org/3/library/tomllib.html#conversion-table) does not contain entries for two types listed on the TOML specification:

1. inline table (dict)
2. array of tables (list of dicts)

Adding those entries to the conversion table will make it more clear how the objects are represented in Python when using `tomllib.load`.

### Linked PRs
* gh-113236
* gh-113283
* gh-113284

**Comment by encukou** [comment]
+1. I can see that users who don't realize that *inline table* is semantically the same as *table* might be confused, and perhaps think `tomllib` doesn't implement the full spec.
There's value in matching the TOML spec, and technically-redundant entries won't hurt. (For sufficiently advanced users, all of the table falls under “common sense", anyway...)
