### ISSUE TITLE
Limit the version of the package by released time

### ISSUE THREAD

**Issue by huangliang0828** [python/cpython#113387]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
```
The win10 system, it is known that scikit-learn 0.23.2 is released in pypi in 2020. 
If I want to install other dependent packages, I hope that the release time of all dependent packages will be before 2021.In other words, the release time of the package is used to limit the version of the package installed later, including not only the package in pypi but also the package in conda-forge. How to install the package that meets the conditions by limiting the time in batches, without me personally determining the version of the package one by one.

### Has this already been discussed elsewhere?

No response given

**Comment by hauntsaninja** [comment]
This isn't an appropriate issue tracker for this question; this repository does not contain a package manager. Can I recommend the Packaging category on discuss.python.org instead? https://discuss.python.org/c/packaging/14

(I'm not aware of a tool that does this, but the PyPI API does expose upload time so you could write one. But again, better discussed in another location)

**Comment by huangliang0828** [comment]
@[hauntsaninja](https://github.com/hauntsaninja)
I 'm  sorry, thank you for the instructions, if you are convenient can be substituted for  the discuss.python.org website, at present I am not registered this website. Thanks

**Comment by terryjreedy** [comment]
Please register at discuss.python.org.  It is out current discussion site for python, cpython, and some aspects of packaging.
