### ISSUE TITLE
Outdated PyObject_HasAttr documentation (it no longer behaves like builtin `hasattr`)

### ISSUE THREAD

**Issue by perrinjerome** [python/cpython#113391]
# Documentation

The documentation says

https://github.com/python/cpython/blob/c31943af16f885c8cf5d5a690c25c366afdb2862/Doc/c-api/object.rst#L50-L52

but since https://github.com/python/cpython/issues/53875 this is no longer equivalent to ``hasattr(o, attr_name)`` but, if I understood correctly, to something like:

```py
try:
  return hasattr(o, attr_name)
except:
  return False
```

### Linked PRs
* gh-113420

**Comment by serhiy-storchaka** [comment]
Isn't the following note enough?

https://github.com/python/cpython/blob/c31943af16f885c8cf5d5a690c25c366afdb2862/Doc/c-api/object.rst?plain=1#L54-L59

**Comment by skirpichev** [comment]
> Isn't the following note enough?

I think the sentence "This is equivalent to the Python expression ``hasattr(o, attr_name)``." - must be removed.  It actually belongs to the ``PyObject_HasAttrWithError()``.

**Comment by perrinjerome** [comment]
Removing that sentence seems good, I was confused by that part because it contradicts the note below. Thank you !

**Comment by perrinjerome** [comment]
@skirpichev I saw that a pull request to fix this was merged, but the issue is still open, is it OK to close it now ? Thanks again for the fix and sorry for this question, I'm not familiar with how python uses issue tracker

**Comment by skirpichev** [comment]
Yeah, I think so.

But maybe it's stay opened intentionally.  @encukou ?

**Comment by encukou** [comment]
I want to look the docs for 3.12 (and 3.11) too, but didn't get to it yet.

**Comment by skirpichev** [comment]
On Thu, Jan 11, 2024 at 12:54:10AM -0800, Petr Viktorin wrote:
>    I want to look the docs for 3.12 (and 3.11) too, but didn't get to it yet.

Ah, does make sense.  BTW, patch could be cleanly applied to even
earlier releases.

**Comment by encukou** [comment]
Just got back to this.
On 3.12 and below, `PyObject_HasAttr` *is* the closest thing to `hasattr(o, attr_name)`. The difference from the Python function is in error handling, and the sentence just after the removed note makes things very clear.
So, I'll not backport.

Effectively, in 3.13 the “equivalent to `hasattr`” note was moved from `PyObject_HasAttr` to `PyObject_HasAttrWithError`.

Feel free to reopen/comment if you disagree.
