### ISSUE TITLE
`uuid` has a bunch of deprecated functions: let's decide what to do with them

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#113308]
# Feature or enhancement

`uuid.py` has several protected deprecated functions which are no longer in use:

https://github.com/python/cpython/blob/4afa7be32da32fac2a2bcde4b881db174e81240c/Lib/uuid.py#L591-L594

https://github.com/python/cpython/blob/4afa7be32da32fac2a2bcde4b881db174e81240c/Lib/uuid.py#L567-L575

And one unused module-level var:

https://github.com/python/cpython/blob/4afa7be32da32fac2a2bcde4b881db174e81240c/Lib/uuid.py#L583

The problem is that they were not deprecated with a warning. Only with docs.
But, right now they are deprecated since 2020.

This has a big history:
- https://github.com/python/cpython/issues/72196
- https://github.com/python/cpython/issues/84681 and https://github.com/python/cpython/pull/19948
- https://github.com/python/cpython/pull/3796

Some projects in the wild use `_load_system_functions`, despite the fact it is deprecated and was never documented and always was protected.

Examples:
- https://github.com/spulec/freezegun/blob/5e06dff53244992204706adf6907e7138ac96d39/freezegun/api.py#L71
- https://github.com/pganssle/time-machine/blob/ccc59927b4c51e35895c34578cba7aca69f28055/src/time_machine/__init__.py#L211
- https://github.com/adamchainz/time-machine/blob/39e327e18d52ebc76d3973b465ff42e139fd651d/src/time_machine/__init__.py#L223

So, what should we do?
1. Add a proper warning, schedule it for removal in two versions
2. Just remove them

I think that `1.` is safer.
I would like to work on it after the decision is made.

### Linked PRs
* gh-115934
* gh-117832

**Comment by gpshead** [comment]
I'd go with `1.`, add the warnings to start the clock.

**Comment by hugovk** [comment]
`1.` sounds good, no rush.

> Some projects in the wild use `_load_system_functions`, despite the fact it is deprecated and was never documented and always was protected.
> 
> Examples:
> 
> * [spulec/freezegun@`5e06dff`/freezegun/api.py#L71](https://github.com/spulec/freezegun/blob/5e06dff53244992204706adf6907e7138ac96d39/freezegun/api.py#L71)
> * [pganssle/time-machine@`ccc5992`/src/time_machine/__init__.py#L211](https://github.com/pganssle/time-machine/blob/ccc59927b4c51e35895c34578cba7aca69f28055/src/time_machine/__init__.py#L211)
> * [adamchainz/time-machine@`39e327e`/src/time_machine/__init__.py#L223](https://github.com/adamchainz/time-machine/blob/39e327e18d52ebc76d3973b465ff42e139fd651d/src/time_machine/__init__.py#L223)

And the second one is an inactive fork of the third, I guess just for a PR.

Searching the top 8k PyPI projects, only freezegun and time-machine use any of these four functions:

```console
❯ python3 ~/github/misc/cpython/search_pypi_top.py -q . "_load_system_functions|_ipconfig_getnode|_netbios_getnode|_has_uuid_generate_time_safe"
./freezegun-1.2.2.tar.gz: freezegun-1.2.2/freezegun/api.py: uuid._load_system_functions()
./time_machine-2.13.0.tar.gz: time_machine-2.13.0/src/time_machine/__init__.py: uuid_idempotent_load_system_functions = (
./time_machine-2.13.0.tar.gz: time_machine-2.13.0/src/time_machine/__init__.py: uuid._load_system_functions  # type: ignore[attr-defined]
./time_machine-2.13.0.tar.gz: time_machine-2.13.0/src/time_machine/__init__.py: uuid_idempotent_load_system_functions()
./uuid-1.30.tar.gz: uuid-1.30/uuid.py: def _ipconfig_getnode():
./uuid-1.30.tar.gz: uuid-1.30/uuid.py: def _netbios_getnode():
./uuid-1.30.tar.gz: uuid-1.30/uuid.py: getters = [_windll_getnode, _netbios_getnode, _ipconfig_getnode]
./ptvsd-4.3.2.zip: ptvsd-4.3.2/src/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_uuid_old.py: def _ipconfig_getnode():
./ptvsd-4.3.2.zip: ptvsd-4.3.2/src/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_uuid_old.py: def _netbios_getnode():
./ptvsd-4.3.2.zip: ptvsd-4.3.2/src/ptvsd/_vendored/pydevd/_pydev_imps/_pydev_uuid_old.py: getters = [_windll_getnode, _netbios_getnode, _ipconfig_getnode]
```

Ping @spulec and @adamchainz to give a heads-up.

**Comment by vstinner** [comment]
If you start to emit a `DeprecationWarning` right now, you respect PEP 387, and so you will be able to remove the code in 2 releases (Python 3.15) in a safe way. You can also announce the removal at: https://docs.python.org/dev/whatsnew/3.13.html#pending-removal-in-python-3-15

**Comment by sobolevn** [comment]
@serhiy-storchaka proposes to just remove these functions. I am fine with both versions, so I would like to get more votes :)

**Comment by serhiy-storchaka** [comment]
PEP 387 only applies to public APIs. We are free not only remove private functions, but change them in breaking way, for example changing the order of parameters and changing their semantic. Exceptions can be made for old and widely used private APIs, but this is not the case.

**Comment by adamchainz** [comment]
I agree, just remove them.

I’ve just made this PR to stop time-machine calling `_load_system_functions()` on Python 3.9+: https://github.com/adamchainz/time-machine/pull/425 . Thanks for the heads up.

**Comment by hugovk** [comment]
Fine by me too. 

@terryjreedy @gpshead Any objections to just removing these internal functions? They appear to be _very rarely_ used, now by only one in the top 8k.

**Comment by gpshead** [comment]
Go for it, they're private.  I sent a PR for the freezegun code (https://github.com/spulec/freezegun/pull/534), and the time-machine code is already a conditional call based on Python version.

If we encounter any issues with these during the beta period we can re-add the no-op with an actual `DeprecationWarning`.

**Comment by sobolevn** [comment]
Changing my PR, thanks everyone :)

**Comment by sobolevn** [comment]
I merged https://github.com/python/cpython/pull/115934 🎉 
Thanks everyone, I hope that this will be smooth!
