### ISSUE TITLE
Basic logging tutorial: Confusing matrix and use of word "above"

### ISSUE THREAD

**Issue by epa095** [python/cpython#113350]
# Documentation

This is about the log level table in https://docs.python.org/3/howto/logging.html#when-to-use-logging

It has "Debug" on top and "Critical" on the bottom, and underneath it it says:

> The default level is WARNING, which means that only events of this level and **above** will be tracked, unless the logging package is configured to do otherwise.

In this sentence, "above" probably relates to the numeric values of the errors, which is sorted in the opposite order than the table. Since the table is arranged as it is, the default is actually to show events of level "WARNING" and **below** in the table.

The easiest and most consistent is probably to reorder the table?

### Linked PRs
* gh-113424
* gh-113491

**Comment by hugovk** [comment]
Good spot, although I think the table reads better going in increasing order of severity.

Can we use another, more descriptive word?

Something like "only events of this level and _more severe_ will be tracked"?

Or "only events of this level and _higher severity_ will be tracked"?

**Comment by ericvsmith** [comment]
> Or "only events of this level and _higher severity_ will be tracked"?

I like this wording.

**Comment by hugovk** [comment]
@epa095 Would you like to create a PR with this wording?

**Comment by vaishnavi192** [comment]
hey @hugovk can I work on this? I am very new to open source....not able to solve issues even after searching a lot...this will give me some hope and confidence

**Comment by hugovk** [comment]
@vaishnavi192 Normally I'd give the reporter first chance, but if @epa095 is fine with it, please go ahead!

**Comment by epa095** [comment]
Fine by me!

**Comment by vaishnavi192** [comment]
Thanks a lot I will soon create a PR!😄

**Comment by vaishnavi192** [comment]
hey @hugovk I created the PR!
As a new contributor even making pull request sometimes feels overwhelming. Thanks a lot for giving me permission to solve this issue no matter how easy it was but still it boosted my confidence. I am very excited to further contribute in Python! It's been a year since I am using python. Now its time to pay back! I just love contributing to open source no matter how hard it gets! 
Also, thanks a lot @epa095 for allowing me to work on this!😁

**Comment by vaishnavi192** [comment]
I have made the requested changes; please review again
