### ISSUE TITLE
Enhance itertools.takewhile() to allow the failed transition element to captured

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#113479]
The current version of `takewhile()` has a problem.  The element that first fails the predicate condition is consumed from the iterator and there is no way to access it.  This is the premise behind the existing recipe `before_and_after()`.

I propose to extend the current API to allow that element to be captured.  This is fully backwards compatible but addresses use cases that need *all* of the data not returned by the takewhile iterator.

**Option 0:**

In pure Python, the new `takewhile()` could look like this:

```py
def takewhile(predicate, iterable, *, transition=None):
    # takewhile(lambda x: x<5, [1,4,6,4,1]) --> 1 4
    for x in iterable:
        if predicate(x):
            yield x
        else:
            if transition is not None:      # <-- This is the new part
                transition.append(x)        # <-- This is the new part
            break
```

It could be used like this:

```pycon
>>> input_it = iter([1, 4, 6 ,4, 1])
>>> transition_list = []
>>> takewhile_it = takewhile(lambda x: x<5, input_it, transition=transition_list)
>>> print('Under five:', list(takewhile_it))
[1, 4]
>>> remainder = chain(transition_list, input_it)
>>> print('Remainder:', list(remainder)) 
[6, 4, 1]
```

The API is a bit funky. While this pattern is [common in C programming](https://www.tutorialspoint.com/c_standard_library/c_function_frexp.htm), I rarely see something like it in Python.  This may be the simplest solution for accessing the last value (if any) consumed from the input.  The keyword argument `transition` accurately describes a list containing the transition element if there is one, but some other parameter name may be better.

**Option 1:**

We could have a conditional signature that returns two iterators if a flag is set:

```
true_iterator = takewhile(predicate, iterable, remainder=False)
true_iterator, remainder_iterator = takewhile(predicate, iterable, remainder=True)
```

**Option 2:**

Create a completely separate itertool by promoting the `before_and_after()` recipe to be a real itertool:

```
true_iterator, remainder_iterator = before_and_after(predicate, iterable)
```

I don't really like option 2 because it substantially duplicates `takewhile()` leaving a permanent tension between the two.

### Linked PRs
* gh-115890
* gh-115910

**Comment by AlexWaygood** [comment]
Have you considered API like this, where transition_list is set as an attribute on the exhausted iterator? It would avoid the API where `transition_list` has to be defined prior to `takewhile` being called, and is mutated by the `takewhile`  iterator — that feels pretty awkward to me.

```pycon
>>> class takewhile:
...     def __init__(self, predicate, iterable):
...         self.predicate = predicate
...         self.it = iter(iterable)
...         self.transition = None
...     def __iter__(self):
...         return self
...     def __next__(self):
...         x = next(self.it)
...         if self.predicate(x):
...             return x
...         else:
...             self.transition = [x]
...             raise StopIteration
...       
>>> input_it = iter([1, 4, 6 ,4, 1])
>>> takewhile_it = takewhile(lambda x: x<5, input_it)
>>> print('Under five:', list(takewhile_it))
Under five: [1, 4]
>>> from itertools import chain
>>> remainder = chain(takewhile_it.transition, input_it)
>>> print('Remainder:', list(remainder))
Remainder: [6, 4, 1]
```

**Comment by rhettinger** [comment]
> Have you considered an API like this, where transition_list is set as an attribute on the exhausted iterator?

Let's call that Option 3 for purposes of discussion.

**Comment by ericvsmith** [comment]
There are no awesome choices here (for good reasons), but I think I prefer Option 1. Can type checkers understand Option1 well enough?

**Comment by AlexWaygood** [comment]
> Can type checkers understand Option1 well enough?

Yes, should be easily doable with a combination of `typing.overload` and `typing.Literal` (though I still prefer Option 3, myself)

**Comment by ajoino** [comment]
Reading the description before the options were listed the solution in my head was basically Option 3 suggested, so I'd prefer that I think (though I've rarely used `takewhile`). Are there any circumstances where returning a tuple of iterators is more convenient than accessing it as an attribute? If yes, that'd be in favor of Option 1 IMO.

**Comment by christianzzz** [comment]
Seems [more-itertools.partition](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.partition) does what you need.

**Comment by ericvsmith** [comment]
> Seems [more-itertools.partition](https://more-itertools.readthedocs.io/en/stable/api.html#more_itertools.partition) does what you need.

Which is option 2, with a different name.

**Comment by encukou** [comment]
An option for Option 2 is to [“soft-deprecate”](https://peps.python.org/pep-0387/#soft-deprecation) `takewhile` -- essentially, de-emphasize it in the docs.

With Option 1, the type of the result depends on an argument. While I'm not much of a fan of static typing, one thing it taught me is that simpler typing usually indicates a better API.

Note that `before_and_after` would also substantially duplicate `dropwhile`+`consume`.

There might be inspiration in `zip_longest`. Should it have been `zip(..., fill_value=x)` instead? (Just food for thought; of course the situation here is different.)

**Comment by rhettinger** [comment]
After more thought, I think I'm just going to document the issue and provide a link to more-itertools before_and_after() as the workaround.

`takewhile()` has been around for two decades and is one of the least used and known itertools. Aside from me, no one else has ever noticed or cared about the issue.   So, it doesn't warrant any heroic effort to fix it.   If someone does care, the `before_and_after` link will suffice.
