### ISSUE TITLE
Invalid "python equivalent" in PyObject_RichCompareBool()

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#113445]
It should be ``bool(o1 op o2)`` instead.  Or (better?) the sentence "This is the equivalent of the Python expression ``o1 op o2``, where ``op`` is the operator corresponding to *opid*." could be removed, as the note below shows there is no simple equivalent python expression:
https://github.com/python/cpython/blob/fc2cb86d210555d509debaeefd370d5331cd9d93/Doc/c-api/object.rst?plain=1#L232-L234

### Linked PRs
* gh-113891
* gh-114637
* gh-114638

**Comment by Lilneo786** [comment]
```
import ctypes

# Create a Python object
obj = [1, 2, 3]

# Check if the object is equal to itself
result_eq = obj == obj
print("Equal:", result_eq)  # Output: Equal: True

# Check if the object is not equal to itself
result_ne = obj != obj
print("Not Equal:", result_ne)  # Output: Not Equal: False
```

**Comment by skirpichev** [comment]
@Lilneo786, not sure I get your point, could you elaborate, please?
