### ISSUE TITLE
JIT Compilation

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#113464]
It's probably about time to start thinking seriously about just-in-time compilation. To kick things off, here's my talk from this year's sprint about "copy-and-patch", which I think is a really promising path forward: https://youtu.be/HxSHIpEQRjs

I'll also be opening a draft PR for discussion soon.

### Linked PRs
* gh-113465
* gh-114739
* gh-114759
* gh-115800
* gh-118481
* gh-118512
* gh-118545
* gh-119466
* gh-119490
* gh-122839
* gh-133278
* gh-133486

**Comment by cosmicexplorer** [comment]
Do you have a writeup or other non-video explainer available, or is the PR itself the best reference for this technique?

**Comment by MarshalX** [comment]
> Do you have a writeup or other non-video explainer available, or is the PR itself the best reference for this technique?

Maybe this one will be helpful to you https://aha.stanford.edu/sites/g/files/sbiybj20066/files/media/file/aha_050621_xu_copy-and-patch.pdf

**Comment by brandtbucher** [comment]
> Do you have a writeup or other non-video explainer available, or is the PR itself the best reference for this technique?

There four main resources that I've been directing people towards... they each explain different things in different levels of detail:

- The [white paper](https://dl.acm.org/doi/10.1145/3485513): high-level overview of copy-and-patch.
- The [blog post](https://sillycross.github.io/2023/05/12/2023-05-12): low-level implementation details for copy-and-patch.
- The [YouTube video](https://youtu.be/HxSHIpEQRjs): high-level overview of CPython's approach to copy-and-patch.
- The [pull request](https://github.com/python/cpython/pull/113465): low-level implementation details for CPython's approach to copy-and-patch.

**Comment by brandtbucher** [comment]
Done! I'll be opening follow-up issues for further improvements to both the build process and the generated code.
