### ISSUE TITLE
'a' == 'a' in 'abc'

### ISSUE THREAD

**Issue by byubean** [python/cpython#113406]
# Bug report

### Bug description:

Consider the following expressions:

```python
>>> ('a' == 'a') in 'abc'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'in <string>' requires string as left operand, not bool

>>> 'a' == ('a' in 'abc')
False
```
- The first evaluates `('a' == 'a')` to `True`, and `True in 'abc'` rightly raises an error.
- The second evaluates ('a' in 'abc') to `True`, and then evaluates `'a' == True` to `False`. 

One would expect the following expression to follow one of the two examples above...
```python
>>> 'a' == 'a' in 'abc'  # (3)   
True
```
...but it doesn't!

Now consider the following:
```python
>>> class Foo:
...   def __contains__(self, item):
...     print('contains', item)
...     return item
... 
>>> 'a' in Foo()   # (1)
contains a
True
>>> 'a' == 'a' in Foo()   # (2)
contains a
True
>>> True == 'a' in Foo()
False
```

- Note that `'a' in Foo()` reports `True` not `'a'` (!)
- But `'a' == 'a' in Foo()` also reports `True`, as if `Foo.__contains__` is in fact returning `'a'`
  - which observation is supported by `True == 'a' in Foo()` reporting `False` (i.e. `True != 'a'`)

So, it appears that:
- under some situations (at least the interpreter), the `in` operator result is coerced to a boolean just before being displayed (1), but it is not coerced if it isn't displayed. (2) 
- something similar appears to be happening with `str.__contains__`: sometimes this function returns the substring (i.e. with `==` preceding the expression). (3)   

Additional test:
```python
>>> class Truthy:
...   def __bool__(self):
...     print('True!')
...     return True
... 
>>> class Bar:
...   def __contains__(self, item):
...     print('Contains!', item)
...     return Truthy()
... 
>>> 'a' in Bar()
Contains! a
True!
True
>>> 'a' == 'a' in Bar()
Contains! a
True!
True
>>> 'b' == 'a' in Bar()  # !?
False
```

What is going on here? Is this intentional? 

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment]
Thanks for the report! However, this is not a bug; everything is working as intended, and everything is working as it has done for several decades. Changing this behaviour would break a lot of code :)

What you've discovered is how "operator chaining" works in Python. `'a' == 'a' in 'abc'` is desugared by the interpreter to `('a' == 'a') and ('a' in 'abc')`. This is documented here: https://docs.python.org/3.12/reference/expressions.html#comparisons.

If you have further questions, please open a thread at https://discuss.python.org/c/users/7 -- the GitHub issue tracker is for bugs in CPython, and this isn't a bug :)

**Comment by byubean** [comment]
Thank you @AlexWaygood for the prompt response and helpful explanation. 

I've used `1 < x < 3` plenty, but it hadn't occurred to me that `in` was a comparison operator, and that **all** comparisons could be chained. 

I agree with the verdict: not a bug.
