### ISSUE TITLE
Mac/README.rst --enable-framework description doesn't match configure script

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#113459]
# Documentation

Trying to figure out what bits need to be deleted when cleaning a framework build, I noticed that the code in the configure script doesn't match the description of `--enable-framework` in `Mac/README.rst`. For example, the `case` stmt in `configure` has `yes`, `no` and `*` branches, while the readme file only mentions giving a directory as an argument. That suggests to me that the `yes` and `no` branches are either never really used, or are at least undocumented.

That said, I don't know if `configure` should move in the direction of `Mac/README.rst` or _vice versa_. I suspect @ronaldoussoren will have a useful opinion on the subject.

**Comment by ronaldoussoren** [comment]
AFAIK the two are consistent with each other due to the way autoconf works, e.g.:

- `configure --enable-framework`   => This is the `yes` case in configure
- `configure --enable-framework=PATH`  => This is the `*` case in configure
-  `configure` (without --enable-framework) => This is the `no` case in configure

You can also use `configure --disable-framework` for the last case, but I don't think anyone will ever do this because framework builds are disabled by default.

**Comment by smontanaro** [comment]
I'll buy that. Still, maybe the "yes" or no arg option should be mentioned with the `/Library/Frameworks` destination. I realize it's mentioned in section 4, "How do I build...", but it seems like for completeness that should be documented at the point where `--enable-framework` is described.

While it occurs to me, maybe the default should be `$HOME/Library/Frameworks`, requiring a user wishing a central install to specify it (and probably be `root`)?

**Comment by ronaldoussoren** [comment]
I don't agree with describing the "yes" and "no" alternatives in the `MAC/README.txt`, that is documentation on how to use the configure script and for that the current documentation is good. I consider the "yes" and "no" arguments as implementation details for the configure script and not something that users should ever use.

Changing the default installation location for framework builds is not something we can easily do, it is bound to break workflows.  We could more prominently document how to install a framework in your home directory.

Also note that the current default matches the defaults for a regular unix install:

| Kind               | Unix       | Framework                  |
|--------------------|------------|----------------------------|
| System location    | /usr       | /System/Library/Frameworks | 
| Local installation | /usr/local | /Library/Frameworks        | 
| Per-user           | ~/.local   | ~/Library Frameworks       |

I'm keeping the issue open for a while to check the behaviour of per-user framework installs, in particular w.r.t the installation of the various app bundles.

**Comment by ronaldoussoren** [comment]
> I'm keeping the issue open for a while to check the behaviour of per-user framework installs, in particular w.r.t the installation of the various app bundles.

Checked this, and we already document how to perform a per-user install in MAC/README.txt:

https://github.com/python/cpython/blob/e87cadc1ce194aae2c076e81298d6e8074f1bb45/Mac/README.rst?plain=1#L29-L45


My conclusion is that there is nothing to do, the README contains the details it needs to contain and also explains how to perform a per-user install.
