### ISSUE TITLE
Excess ':' symbol in datetime directive

### ISSUE THREAD

**Issue by ghost** [python/cpython#113467]
# Documentation

In additional directives table there is ':' symbol in %z directive. So it looks like %:z instead of %z.
![incorrect_directive](https://github.com/python/cpython/assets/40691934/29774d13-04f6-4a41-9158-5f833f3b6a42)

**Comment by serhiy-storchaka** [comment]
It is correct. Try `%z` and `%:z` and see the difference.

**Comment by sobolevn** [comment]
I agree:

```
>>> import datetime
>>> datetime.datetime(2020, 4, 5, 6, 7, tzinfo=datetime.timezone.utc).strftime('%:z')
'+00:00'
>>> datetime.datetime(2020, 4, 5, 6, 7, tzinfo=datetime.timezone.utc).strftime('%z')
'+0000'
```
