### ISSUE TITLE
TKinter bug?

### ISSUE THREAD

**Issue by celestinoxp** [python/cpython#113400]
# Bug report

### Bug description:

I'm working on support to scikit-learn 1.4 in pycaret with VSCode, however now i see strange errors. i dont´t know why matplotlib also appears.
traceback:
c:\Users\celes\pycaret\tests\test_check_fairness.py::test_check_fairness_multiclass_classification failed: def test_check_fairness_multiclass_classification():
        # loading dataset
        data = pycaret.datasets.get_data("iris")
    
        # initialize setup
        pycaret.classification.setup(
            data,
            target="species",
            html=False,
            n_jobs=1,
            train_size=0.8,
        )
    
        # train model
        lightgbm = pycaret.classification.create_model("lightgbm", cross_validation=False)
    
        # check fairness
>       lightgbm_fairness = pycaret.classification.check_fairness(
            lightgbm, ["sepal_length"]
        )

c:\Users\celes\pycaret\tests\test_check_fairness.py:45: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
c:\Users\celes\pycaret\pycaret\utils\generic.py:964: in wrapper
    return func(*args, **kwargs)
c:\Users\celes\pycaret\pycaret\classification\functional.py:3090: in check_fairness
    return _CURRENT_EXPERIMENT.check_fairness(
c:\Users\celes\pycaret\pycaret\internal\pycaret_experiment\supervised_experiment.py:5253: in check_fairness
    multi_metric.by_group.plot.bar(
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_core.py:1193: in bar
    return self(kind="bar", x=x, y=y, **kwargs)
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_core.py:1031: in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_matplotlib\__init__.py:71: in plot
    plot_obj.generate()
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_matplotlib\core.py:452: in generate
    self._setup_subplots()
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_matplotlib\core.py:503: in _setup_subplots
    fig, axes = create_subplots(
c:\Users\celes\pycaret\.venv\lib\site-packages\pandas\plotting\_matplotlib\tools.py:225: in create_subplots
    fig = plt.figure(**fig_kw)
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\pyplot.py:934: in figure
    manager = new_figure_manager(
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\pyplot.py:465: in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\backend_bases.py:3402: in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\backend_bases.py:3407: in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\backend_bases.py:1785: in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
c:\Users\celes\pycaret\.venv\lib\site-packages\matplotlib\backends\_backend_tk.py:486: in create_with_canvas
    window = tk.Tk(className="matplotlib")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <tkinter.Tk object .>, screenName = None, baseName = 'run_pytest_script'
className = 'matplotlib', useTk = True, sync = False, use = None

    def __init__(self, screenName=None, baseName=None, className='Tk',
                 useTk=True, sync=False, use=None):
        """Return a new top level widget on screen SCREENNAME. A new Tcl interpreter will
        be created. BASENAME will be used for the identification of the profile file (see
        readprofile).
        It is constructed from sys.argv[0] without extensions if None is given. CLASSNAME
        is the name of the widget class."""
        self.master = None
        self.children = {}
        self._tkloaded = False
        # to avoid recursions in the getattr code in case of failure, we
        # ensure that self.tk is always _something_.
        self.tk = None
        if baseName is None:
            import os
            baseName = os.path.basename(sys.argv[0])
            baseName, ext = os.path.splitext(baseName)
            if ext not in ('.py', '.pyc'):
                baseName = baseName + ext
        interactive = False
>       self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
E       _tkinter.TclError: Can't find a usable tk.tcl in the following directories: 
E           c:/Users/celes/anaconda3/Library/lib/tcl8.6/tk8.6 c:/Users/celes/anaconda3/Library/lib/tk8.6 c:/Users/celes/lib/tk8.6 c:/Users/celes/lib/tk8.6 c:/Users/lib/tk8.6 c:/Users/celes/library
E       
E       c:/Users/celes/anaconda3/Library/lib/tk8.6/tk.tcl: couldn't read file "c:/Users/celes/anaconda3/Library/lib/tk8.6/ttk/treeview.tcl": no such file or directory
E       couldn't read file "c:/Users/celes/anaconda3/Library/lib/tk8.6/ttk/treeview.tcl": no such file or directory
E           while executing
E       "source -encoding utf-8 [file join $::ttk::library treeview.tcl]"
E           (file "c:/Users/celes/anaconda3/Library/lib/tk8.6/ttk/ttk.tcl" line 110)
E           invoked from within
E       "source -encoding utf-8 c:/Users/celes/anaconda3/Library/lib/tk8.6/ttk/ttk.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel \#0 [list source -encoding utf-8 $::ttk::library/ttk.tcl]"
E           (file "c:/Users/celes/anaconda3/Library/lib/tk8.6/tk.tcl" line 706)
E           invoked from within
E       "source c:/Users/celes/anaconda3/Library/lib/tk8.6/tk.tcl"
E           ("uplevel" body line 1)
E           invoked from within
E       "uplevel #0 [list source $file]"
E       
E       
E       This probably means that tk wasn't installed properly.

c:\Users\celes\anaconda3\lib\tkinter\__init__.py:2299: TclError

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
" This probably means that tk wasn't installed properly."

Anaconda is a separate distribution from the file distrubuted on python.org.  If it does not work properly, or is not properly installed on your machine, ask on an appropriate forum.

In general, questions about possible bugs in Python as distributed on python.org should be directed to the Help channel on our Discourse: https://discuss.python.org/c/users/7
