### ISSUE TITLE
Crash of interpreter due to unclosed sub-interpreters

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#113433]
# Crash report

### Reproducer:

```python
import _xxsubinterpreters as interp

interp_id = interp.create()
```

Trace:
```
Fatal Python error: PyInterpreterState_Delete: remaining subinterpreters
Python runtime state: finalizing (tstate=0x00005576a7f343e0)

Aborted
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121060
* gh-121067

**Comment by Eclips4** [comment]
Bisected to 86a77f4e1
cc @ericsnowcurrently

**Comment by ericsnowcurrently** [comment]
Sorry for the delay.  I'll try to take a look in the next day or two.

**Comment by ericsnowcurrently** [comment]
This should be all sorted for main and 3.13.  Backporting to 3.12 isn't really an option.
