### ISSUE TITLE
UTF-8 Email parsing/serialising: Roundtrip exits with “surrogates not allowed”

### ISSUE THREAD

**Issue by bronger** [python/cpython#113594]
# Bug report

### Bug description:

In the attached Python minimal example, `email_raw_1` survives a round-trip from UTF-8 bytes string to an EmailMessage object and back to a string, while `email_raw_2` does not:

Traceback (most recent call last):   
  File "//surrogate_issue.py", line 29, in <module>
    print(message_2) 
  …
  File "/usr/local/lib/python3.12/email/_encoded_words.py", line 224, in encode
    bstring = string.encode(charset)
              ^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-2: surrogates not allowed

Funny thing is that the only difference is an additional digit in the middle of it.

The email is malformed, however, it is taken from an actual mail at <https://wilson.bronger.org/5105.txt>. Malformed or not, my other email machinery can deal with it, so I think Python should handle such real-world specimen on best-effort basis without exiting.

```python
#!/bin/python

import email, email.policy


email_raw_1 = """Content-Type: multipart/mixed; boundary="==="

--===
Content-Type: message/plain
 
 您0123456789012.3456789

--===--
""".encode()

email_raw_2 = """Content-Type: multipart/mixed; boundary="==="

--===
Content-Type: message/plain
 
 您0123456789012.34567890

--===--
""".encode()

message_1 = email.message_from_bytes(email_raw_1, policy=email.policy.SMTPUTF8)
message_2 = email.message_from_bytes(email_raw_2, policy=email.policy.SMTPUTF8)
print(message_1)
print(message_2)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-113639
* gh-113730
* gh-113907
* gh-113908

**Comment by terryjreedy** [comment]
You replaced part of the traceback with `…`.  Please replace that back with the rest of the traceback.  Then enclose the traceback in triple backticks, as you did with the file code.  The traceback as is makes no sense as printing a string should not execute the string.  Check the types of message_1 and message_2.  Maybe print the raw emails to make sure they are what they should be.

**Comment by bronger** [comment]
This is the full traceback:

```
Traceback (most recent call last):
  File "//issue.py", line 29, in <module>
    print(message_2)
  File "/usr/local/lib/python3.12/email/message.py", line 1002, in __str__
    return self.as_string(policy=self.policy.clone(utf8=True))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/message.py", line 999, in as_string
    return super().as_string(unixfrom, maxheaderlen, policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/message.py", line 188, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/local/lib/python3.12/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 180, in _write
    self._dispatch(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 217, in _dispatch
    meth(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 275, in _handle_multipart
    g.flatten(part, unixfrom=False, linesep=self._NL)
  File "/usr/local/lib/python3.12/email/generator.py", line 115, in flatten
    self._write(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 198, in _write
    self._write_headers(msg)
  File "/usr/local/lib/python3.12/email/generator.py", line 225, in _write_headers
    self.write(self.policy.fold(h, v))
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 184, in fold
    return self._fold(name, value, refold_binary=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/policy.py", line 214, in _fold
    return self.header_factory(name, ''.join(lines)).fold(policy=self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/headerregistry.py", line 253, in fold
    return header.fold(policy=policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 156, in fold
    return _refold_parse_tree(self, policy=policy)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 2823, in _refold_parse_tree
    last_ew = _fold_as_ew(tstr, lines, maxlen, last_ew,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_header_value_parser.py", line 2911, in _fold_as_ew
    encoded_word = _ew.encode(to_encode_word, charset=encode_as)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/email/_encoded_words.py", line 224, in encode
    bstring = string.encode(charset)
              ^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'utf-8' codec can't encode characters in position 0-2: surrogates not allowed
```

**Comment by terryjreedy** [comment]
If the raw strings are not encoded to bytes and "message_from_bytes" is replaces with "message_from_string", both messages are printed with whitespace (perhaps as '\r's, treated as '\n's by Github), added.  The second one, running 3.13.0a2, is
```
Content-Type: multipart/mixed; boundary="==="



--===

Content-Type: message/plain

 

 您0123456789012.34567890







--===--



```
With the original code, the encoded `email_raw_1` is printed as `b'Content-Type: multipart/mixed; boundary="==="\n\n--===\nContent-Type: message/plain\n \n \xe6\x82\xa80123456789012.3456789\n\n--===--\n'` and `...2` the same with the extra `0` and `message_1`, with blank lines removed, as
```
Content-Type: multipart/mixed; boundary="==="
--===
Content-Type: message/plain  =?unknown-8bit?q?=E6=82=A80123456789012?=.3456789
--===--
```
email._encoded words, function encode, lines 221-4 are
```
    if charset == 'unknown-8bit':
        bstring = string.encode('ascii', 'surrogateescape')
    else:
        bstring = string.encode(charset)
```
Printing `string` and `charset` prints
```
���0123456789012 unknown-8bit  # message_1
���0123456789012 unknown-8bit  # message_2
���0123456789012.34567890 utf-8  # message_2 
```
I leave it to someone else to trace back through the traceback to determine where the added digit causes the extra failing call.

**Comment by parthsdoshi** [comment]
Hi, I'm new to contributing to Python as well as the email module.

I tried to reproduce the traceback on latest master in this draft PR:
https://github.com/python/cpython/pull/113639
but I don't see any errors.

Please let me know if I'm doing something wrong, thanks!

**Comment by bronger** [comment]
> Hi, I'm new to contributing to Python as well as the email module.
> 
> I tried to reproduce the traceback on latest master in this draft PR: #113639 but I don't see any errors.
> 
> Please let me know if I'm doing something wrong, thanks!

You are missing two spaces in the string literals.  This version is more robust:

```python
import email, email.policy

email_raw_1 = \
    b'Content-Type: multipart/mixed; boundary="==="\n\n--===\n' + \
    b'Content-Type: message/plain\n \n \xe6\x82\xa80123456789012.3456789\n' + \
    b'\n--===--\n'
email_raw_2 = b'Content-Type: multipart/mixed; boundary="==="\n\n--===\n' + \
    b'Content-Type: message/plain\n \n \xe6\x82\xa80123456789012.34567890\n' + \
    b'\n--===--\n'

message_1 = email.message_from_bytes(email_raw_1, policy=email.policy.SMTPUTF8)
print(message_1)
message_2 = email.message_from_bytes(email_raw_2, policy=email.policy.SMTPUTF8)
print(message_2)
```

**Comment by parthsdoshi** [comment]
Ah that's what I get for relying on copy/paste -- will look into this later this week, thanks!

**Comment by serhiy-storchaka** [comment]
I see what is wrong here. `_fold_as_ew()` tries to decode an encoded word in the last line combine it with a new portion, and re-encode. But an encoded word was encoded with "unknown-8bit", it means that you get surrogatescape characters in the decoded string. Then it fails when the combined string is encoded with "utf-8" (because the new portions is encodable with "utf-8").

I am trying to find the best solution that is in line with the existing code.
