### ISSUE TITLE
configure prefers system install of ncurses over available pkg-config on macOS

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#113565]
# Feature or enhancement

### Proposal:

I have ncurses 6.4 installed locally with corresponding pkg-config files. I'd expect that `configure` will pick up that installation, but it seems to prefer the system installation.

I ended up running `configure` with explicit overrides for the CURSES and PANEL CFLAGS and LIBS variables:

```sh
 ../configure  ... CURSES_CFLAGS="$(pkg-config --cflags ncursesw)" CURSES_LIBS="$(pkg-config --libs ncursesw)" PANEL_CFLAGS="$(pkg-config --cflags panelw)" PANEL_LIBS="$(pkg-config --libs panelw)"
```

configure does pick up other local installs (sqlite, bz2, ...)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119816
* gh-121202
* gh-121222

**Comment by erlend-aasland** [comment]
It seems to me our configure checks are suboptimal in many cases when it comes to ncurses[w] and panel[w]. Some observations:

1. It does not make sense to not check for **ncursesw** or **npanelw** on macOS; we should remove the existing guards
2. `HAVE_NCURSESW` is automatically defined on macOS if `have_curses != no`; I'm not sure if we should keep this
3. A lot of curses feature checks do not use the pkg-config discovered CFLAGS/LIBS

I think we should rework it to first do the **ncursesw** and **panelw** checks; if not found, try **ncurses** and **panel**. Then, do the feature check with discovered CFLAGS/LIBS applied.
