### ISSUE TITLE
typings: Pass variable as final

### ISSUE THREAD

**Issue by cojmeister** [python/cpython#113654]
# Feature or enhancement

### Proposal:

The idea is to be able to pass variables as constants, mimicking c++ or rust behaviour such as. And have this be solely as part of the typings ecosystem. It's extremely helpful when reviewing code, or starting to use new codebases.
```rust
fn my_function(mut changeable: &String, unchangeable: &String) {}
```
In python I suggest the following:
```python
def my_function(changeable: str, unchangeable: Final[str])-> None:
    arguments_that_changes += "world!"
    return arguments_that_changes + argument_that_stays_constant
```

### Has this already been discussed elsewhere?

Opened issue in typing repo as well: [#1557](https://github.com/python/typing/issues/1557)

**Comment by vaishnavi192** [comment]
hey @cojmeister  I would like to work on this issue. Can you please assign me ?

**Comment by AlexWaygood** [comment]
@vaishnavi192 thanks for volunteering! Unfortunately there isn't really anything actionable here until we've come to a consensus that this is a desirable feature. The CPython repo isn't really the best place for that discussion to happen — it would be better to have that discussion in the python/typing repo or at https://discuss.python.org/c/typing/32. @cojmeister has already opened another issue in one of those forums (https://github.com/python/typing/issues/1557), so I'll close this for now
