### ISSUE TITLE
Issue with the OutputString method in controlling value assignment

### ISSUE THREAD

**Issue by iconFehu** [python/cpython#113616]
# Feature or enhancement

### Proposal:

I've encountered an issue while debugging my web scraping project. The problem lies in the method of the CookieGenerator class. This class is part of my project, and the issue becomes apparent when investigating the OutputString method of the Morsel class in cpython/Lib/http/cookies.py. The OutputString method seems to concatenate the self.coded_value by default.

https://github.com/python/cpython/blob/4036e48d59b0f9e8057e01458ab7df3dfd323a10/Lib/http/cookies.py#L397

The current implementation seems to hardcode the usage of self.coded_value when constructing the key-value pair for the Set-Cookie field. I would like to have the flexibility to control whether it uses self.coded_value or self.value based on a parameter.

I propose modifying the OutputString method to accept an additional parameter, perhaps named use_coded_value, that would allow users to choose between self.coded_value and self.value during the construction of the Set-Cookie field.

```
# Using self.coded_value
result_string = instance.OutputString(use_coded_value=True)

# Using self.value
result_string = instance.OutputString(use_coded_value=False)
```

![image](https://github.com/python/cpython/assets/46149128/eb0d08a0-9b91-4c58-ac5c-ce712508f2a1)

```python
    def OutputString(self, attrs=None):
        # Build up our result
        #
        result = []
        append = result.append

        # First, the key=value pair
        append("%s=%s" % (self.key, self.coded_value))

        # Now add any defined attributes
        if attrs is None:
            attrs = self._reserved
        items = sorted(self.items())
        for key, value in items:
            if value == "":
                continue
            if key not in attrs:
                continue
            if key == "expires" and isinstance(value, int):
                append("%s=%s" % (self._reserved[key], _getdate(value)))
            elif key == "max-age" and isinstance(value, int):
                append("%s=%d" % (self._reserved[key], value))
            elif key == "comment" and isinstance(value, str):
                append("%s=%s" % (self._reserved[key], _quote(value)))
            elif key in self._flags:
                if value:
                    append(str(self._reserved[key]))
            else:
                append("%s=%s" % (self._reserved[key], value))

        # Return the result
        return _semispacejoin(result)

    __class_getitem__ = classmethod(types.GenericAlias)
```

### Has this already been discussed elsewhere?

No response given

**Comment by serhiy-storchaka** [comment]
`value` is not safe to be used in this function. It can contain space or other special characters, that make the output ambiguous. `coded_value` contains a quoted representation of `value` which is safe to be used here. If you want some other representation, simply set different `coded_value`, and you yourself will be responsible if something goes wrong.

**Comment by iconFehu** [comment]
> `value` is not safe to be used in this function. It can contain space or other special characters, that make the output ambiguous. `coded_value` contains a quoted representation of `value` which is safe to be used here. If you want some other representation, simply set different `coded_value`, and you yourself will be responsible if something goes wrong.

Thank you for the heads up! I understand that value might have special characters, causing output ambiguity. I'll make sure to use the safe coded_value in this function. If a different representation is needed, I'll set a distinct coded_value and take responsibility if any issues arise. Thanks again for your guidance!
