### ISSUE TITLE
Security risk of hidden pth files

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#113659]
"pth files are evil." (Barry Warsaw, #78125)

There is a special kind of evilness:

1. pth files allow to execute arbitrary Python code.
2. pth files are executed automatically, unlike to normal py files which need explicit import or passing as argument to Python interpreter.
3. Some files are hidden by default (in shell and file managers). In particularly dot-files on Posix.

In sum, it increases the risk of executing malicious code. When you receive a handful of files, you, as a cautious person, check their contents before executing. If Python source files are hidden, it's okay, because you saw that nothing suspicious is imported in the files that you execute. But pth files can be executed even if you do not see them and there are no references in visible files.

This issue was first discussed in comments in #113357.

The severity of this issue is not very large, because it requires user interaction to activate. But it increases the risk. I think we should forbid processing hidden pth files.

### Linked PRs
* gh-113660
* gh-114143
* gh-114144
* gh-114145
* gh-114146
* gh-114147

**Comment by ambv** [comment]
This is now fixed. Thanks, Serhiy! ✨ 🍰 ✨

**Comment by 0xIkari** [comment]
I'm entirely unsure if this is the right place to put this, but I have designed a tool that inspects and categorizes .pth files (among other startup vectors), and I'm currently working on a feature that allows this to run as a wrapper for pip to catch it on install. This showed detection on the recent LiteLLM hack as well. Is it okay if I link the repo where my project is in case someone can get some utility out of it? 

I'm not entirely sure if this is the right place to share this.

**Comment by zware** [comment]
> I'm not entirely sure if this is the right place to share this.

This is not the place :).  Please post on [Discourse](https://discuss.python.org/) in either a new [discussion](https://discuss.python.org/c/general/7) or search for an existing relevant thread.
