### ISSUE TITLE
bisect.insort*() docs: inconsistent formatting of O() 

### ISSUE THREAD

**Issue by jwilk** [python/cpython#113664]
On https://docs.python.org/3/library/bisect.html#bisect.insort_left, "O(log n)" is typeset in monospace font, but "O(n)" is not.

### Linked PRs
* gh-113673
* gh-113695
* gh-113724
* gh-113909
* gh-113910

**Comment by jnichols0** [comment]
Created a simple PR for this: https://github.com/python/cpython/pull/113673

**Comment by serhiy-storchaka** [comment]
#113695 and #113724 are two alternate PRs. One uses italic font to make big O notation looking more like mathematic formulas, other uses :math: to render them as mathematic formulas.

The latter produces nicer looking formulas, but it may be overkill.
