### ISSUE TITLE
#find_max_num

### ISSUE THREAD

**Issue by yigitnazli** [python/cpython#113685]
#this is simply finding the maximum of random number if the user entred 0 finished the proccess
num=int(input("enter a number")) 
maximum=num #first integer assign as a max number
if (num==0):
    print("max num is 0") #if the first number is 0 just printed
    
else:
    while (num!=0): #do it till entered 0
        num=int(input("enter next number")) 
        #compare with previous number
        if(maximum>num):
            maximum
        else:
            maximum=num
            
print("max number in your range is", maximum)

**Comment by ericvsmith** [comment]
If this is a feature request, the built in `max` function will do what you want. If you're looking for help, please post to https://discuss.python.org/c/users/7
