### ISSUE TITLE
PyObject_CallOneArg and PyObject_CallNoArgs should be marked as returning a new reference

### ISSUE THREAD

**Issue by ordinary-jamie** [python/cpython#113696]
# Documentation

[`PyObject_CallOneArg` and `PyObject_CallNoArgs` should be updated in the docs](https://docs.python.org/3/c-api/call.html#c.PyObject_CallOneArg) with the reference count annotation `"Return value: New reference."` (as is the case with [`PyObject_CallFunction`](https://docs.python.org/3/c-api/call.html#c.PyObject_CallFunction) et al.)

### Linked PRs
* gh-113697
* gh-113698
* gh-113699

**Comment by erlend-aasland** [comment]
Thanks, @ordinary-jamie!
