### ISSUE TITLE
`test_logging`'s test_111615 fails under WASI

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#113692]
# Bug report

### Bug description:

https://github.com/python/cpython/pull/111638 broke WASI builds due to assuming multiprocessing was always available.

Failure can be seen at https://buildbot.python.org/all/#/builders/1046/builds/3844 .

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-113704
* gh-113844

**Comment by vsajip** [comment]
Hmm, just catching an `ImportError` on `import multiprocessing` doesn't seem to fix it. What's the easiest way to see the exact failure message?

**Comment by brettcannon** [comment]
> What's the easiest way to see the exact failure message?

https://buildbot.python.org/all/#/builders/1046/builds/3844/steps/11/logs/stdio , line 980.

This is how the multiprocessing tests handle if the module isn't built:
https://github.com/python/cpython/blob/1ae7ceba29771baf8f2e8d2d4c50a0355cb6b5c8/Lib/test/_test_multiprocessing.py#L41-L42

**Comment by vsajip** [comment]
D'oh! Can't believe I missed that line, scrolled up and down too fast, I guess  :see_no_evil:  So `multiprocessing` is built on WASI, but `_multiprocessing` isn't? I wonder what the logic there is.

**Comment by brettcannon** [comment]
> D'oh! Can't believe I missed that line, scrolled up and down too fast, I guess 🙈 So `multiprocessing` is built on WASI, but `_multiprocessing` isn't?

Sort of. Since `multiprocessing` is a `.py` file it's more that it isn't stripped out.

> I wonder what the logic there is.

I believe the original idea is enough code out there blindly assumes the module exists when importing globally, that even code that doesn't end up using the module would fail. There's also the possibility that the code just wants a constant or some code that does work (seen the former w/ ctypes).

**Comment by brettcannon** [comment]
Thanks for fixing this!
