### ISSUE TITLE
Split up Modules/gcmodule.c

### ISSUE THREAD

**Issue by colesbury** [python/cpython#113688]
# Feature or enhancement

The free-threaded builds require substantial changes to the garbage collection implementation, but we don't want to make those changes to the default build. In other parts of CPython, we have used "local" `#ifdef Py_GIL_DISABLED` guards around free-threaded specific bits, but I think doing this throughout `Modules/gcmodule.c` will make the GC harder to maintain than having separate files for the free-threaded and default builds. Additionally, I think @markshannon already suggested splitting the core GC parts from the Python "gc" module.

There's definitely an increased maintenance cost for having two GC implementations in separate files, but I think this maintenance will be less than having a single file with intermixed implementations and lots of `#ifdef Py_GIL_DISABLED` guards.

Here's a proposed split:

`Modules/gcmodule.c` - [`gc`](https://docs.python.org/3/library/gc.html) Python package interface

`Python/gc.c` - core GC functionality common to both build configurations (GIL & free-threaded)
`Python/gc_gil.c` - GIL (non-free-threaded) specific implementations
`Python/gc_free_threaded.c` - free-threaded specific implementations

At first, I'd expect most code to be in either `Modules/gcmodule.c` or `Python/gc.c`. As work on the free-threaded build continues, I would expect `Python/gc.c` to shrink as code is moved into `Python/gc_gil.c` and `Python/gc_free_threaded.c`.

@nascheme @markshannon @pablogsal @DinoV @vstinner

### Linked PRs
* gh-113715
* gh-113814

**Comment by pablogsal** [comment]
I’m fine with the splitting as well as I really don’t think we should have both versions in the same file so let’s go ahead unless someone has some strong reservations.

Refarding the performance concer a, we do have benchmarks that are checking the performance of GC runs in the pyperformance suite so we can always monitor if changes we made are significant. I am mentioning this so we are not too conservative with the changes and being worried that they are going to affect performance a lot because at the end of the day is very difficult to actually predict how these kind of alterations are going to affect performance.

So my proposal is that we do optimise for maintainability and then check performance and adapt from there.

**Comment by gpshead** [comment]
Agreed, I think this split makes sense. What y'all have already said above.

**Comment by pablogsal** [comment]
> But GC is wholly different. GC should care where objects are locate

Well, the current one doesn't care, as that was an advantage. The new one does, which is a different advantage ;)

**Comment by colesbury** [comment]
Great - it seems like there's consensus on splitting the files.

@nascheme, I was thinking that maybe `Python/gc.c` could `#include` one of `Python/gc_gil.c` or `Python/gc_free_threaded.c`. Something like:

```c
// in Python/gc.c
#ifdef Py_GIL_DISABLED
#  include "gc_free_threaded.c"
#else
#  include "gc_gil.c"
#endif
```

We already do this in a few places, with clinic generated files, in [`Modules/socketmodule.c`](https://github.com/python/cpython/blob/1ae7ceba29771baf8f2e8d2d4c50a0355cb6b5c8/Modules/socketmodule.c#L454-L459), obmalloc with mimalloc files, and a few other modules.

It's a bit icky, but it avoids both the concerns around inlining and complexity with configuring the build system to include one or the other file since that's handled at the macro pre-processor level.

**Comment by nascheme** [comment]
I'd prefer not to do that include of .c files.  It might make debugging harder, for example.  I'd include both files in the build always and then put `ifdefs` inside of them to disable code if needed.  That avoids needing extra logic when generating the makefile or whatever.

**Comment by gpshead** [comment]
This is something we should be able to adjust the _how_ of based on practical experiences if the initial approach winds up causing any issues. Debuggers know which file any given line of code came from, I'm not worried at all about that for #includes.

**Comment by colesbury** [comment]
@nascheme  - that sounds fine. I'll follow that approach.

**Comment by kulikjak** [comment]
This change broke `--with-dtrace` build on Solaris (or other systems where object files need to be modified with dtrace before linking) with error like this:
```
Undefined			first referenced
 symbol  			    in file
__dtraceenabled_python___gc__start  Python/gc.o
__dtraceenabled_python___gc__done   Python/gc.o
__dtrace_python___gc__start         Python/gc.o
__dtrace_python___gc__done          Python/gc.o
ld: fatal: symbol referencing errors
collect2: error: ld returned 1 exit status
```

#113814 fixes the issue.
