### ISSUE TITLE
[improvement] Align object addresses in the Descriptor HowTo Guide

### ISSUE THREAD

**Issue by dsardelic** [python/cpython#113625]
# Documentation
In the [Functions and methods](https://docs.python.org/3.12/howto/descriptor.html#functions-and-methods) chapter of this wonderful guide there is an inconsistency between object addresses in the provided code examples and outputs.

Current outputs for `d.f` and `d.f.__self__` are `<bound method D.f of <__main__.D object at 0x00B18C90>>` and `<__main__.D object at 0x1012e1f98>` respectively. These two addresses should in fact be identical.

### Linked PRs
* gh-113894
* gh-113922
* gh-113923

**Comment by hugovk** [comment]
Thanks for the report, this has now been fixed.
