### ISSUE TITLE
AUGMENTED OPERATORS ADDITION

### ISSUE THREAD

**Issue by raja986** [python/cpython#113670]
# Bug report

### Bug description:

```python
# Add a code block here, if required
l=[]
l+="help"#shouldn't work generally but in latest version
#its working 
#output:['h','e','l','p']
#generally we will use l+=list("help") it was given in #documention that only list can add to a list but it #differs here
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
That's not a bug. 
`l += "help"` is the same thing as `l.extend("help")`. (list method `extend` accepts an iterable).
For the next time, first of all, ask for help on https://discuss.python.org/c/7
