### ISSUE TITLE
Update autoconf to warn when building under `wasm32-unknown-emscripten`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#113632]
# Bug report

### Bug description:

Support for wasm32-unknown-emscripten was dropped in https://github.com/python/peps/pull/3612 . As [part of PEP 11](https://peps.python.org/pep-0011/#unsupporting-platforms), a `configure` error needs to be triggered when building for the platform.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-115192

**Comment by brettcannon** [comment]
This is blocked on the SC answering https://github.com/python/steering-council/issues/226 .

**Comment by brettcannon** [comment]
Another option is to have a [warning](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Diagnostic-Macros.html#Diagnostic-Macros) anytime you build on a platform that isn't supported.

**Comment by erlend-aasland** [comment]
> Another option is to have a [warning](https://www.gnu.org/software/autoconf/manual/autoconf-2.63/html_node/Diagnostic-Macros.html#Diagnostic-Macros) anytime you build on a platform that isn't supported.

We already have the following code in place:

https://github.com/python/cpython/blob/5ce193e65a7e6f239337a8c5305895cf8a4d2726/configure.ac#L961C13-L995

Removing this line...:

https://github.com/python/cpython/blob/5ce193e65a7e6f239337a8c5305895cf8a4d2726/configure.ac#L982

... _should_ end up producing a warning.
