### ISSUE TITLE
Windows installer: provide an option to install per-user without admin rights

### ISSUE THREAD

**Issue by soredake** [python/cpython#113794]
# Feature or enhancement

### Proposal:

Most per-user installers/installer switches are not requiring admin rights to install, neither should python installer.

### Has this already been discussed elsewhere?

No response given

**Comment by terryjreedy** [comment]
I am pretty sure this is already true, or is meant to be.  What *exact* installer file did you try, what *exactly* did you do, and what messages did you get?

**Comment by soredake** [comment]
> I am pretty sure this is already true

Unfortunately no.



> What _exact_ installer file did you try

`winget install --scope=user python.python.3.11`, winget manifest can be viewed here https://github.com/microsoft/winget-pkgs/blob/523add9f86fab4958b5cddcc02ad42ceb3c8c723/manifests/p/Python/Python/3/11/3.11.7/Python.Python.3.11.installer.yaml#L48-L61

**Comment by soredake** [comment]
@terryjreedy it is python installed default to install per-user but with admin rights:
![image](https://github.com/python/cpython/assets/5204968/0e351b28-a35f-477a-9340-df178cf2afba)

**Comment by soredake** [comment]
Seems `InstallLauncherAllUsers=0` should be added to python manifest in winget repository, closing.

**Comment by zooba** [comment]
FWIW, `InstallLauncherAllUsers` should already default to 0. The only time it'll change automatically is if you already have the launcher installed for all users, in which case it only makes sense for it to be enabled (or else you won't see the newer version).

**Comment by soredake** [comment]
@zooba yeah, but it's true only for >=3.12, ≤3.11 have InstallLauncherAllUsers set to 1 by default (verified in clean vm with 3.10 and 3.11 installers)

**Comment by zooba** [comment]
Ah, that was a 3.12 change. My bad (the versions blur into each other a bit, and I probably made that change over a year ago by now)
