### ISSUE TITLE
bool print -1

### ISSUE THREAD

**Issue by PreeyaSinha** [python/cpython#113778]
# Bug report

### Bug description:

```python
b = True
c = False
print ('Arthimetic Operation(c-b): ', c - b)
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by PreeyaSinha** [comment]
output :
Arthimetic Operation(c-b):  -1

**Comment by Eclips4** [comment]
Hello!
There's no bug. `bool` type is inherited from `int`. `False` represents value `0`, and `1` for `True`.
So `False - True` is equal to -1.
For the next time, first of all, ask your question on https://discuss.python.org/c/users/7, please.

**Comment by PreeyaSinha** [comment]
basic definition of bool is either TRUE or FALSE.. Is it not correct undertsanding

**Comment by PreeyaSinha** [comment]
Sure... i will follow next time before raising BUG
For the next time, first of all, ask your question on https://discuss.python.org/c/users/7, please.
