### ISSUE TITLE
`code.InteractiveInterpreter.runsource()` regression on Python 3.12+

### ISSUE THREAD

**Issue by gpotter2** [python/cpython#113703]
# Bug report

### Bug description:

`InteractiveInterpreter.runsource()` is supposed to return True when the input is incomplete, as per the doc: https://docs.python.org/3/library/code.html#code.InteractiveInterpreter.runsource. This appears to have regressed with f-strings in Python 3.12+

**Python 3.11.2:**
```python
>>> code.InteractiveInterpreter().runsource('a = f"""')
True
```

**Python 3.12.1 or Python 3.13.0a2+ (heads/main:1ae7ceba29, Jan  4 2024, 16:18:49):**
```python
>>> code.InteractiveInterpreter().runsource('a = f"""')
  File "<input>", line 1
    a = f"""
        ^
SyntaxError: unterminated triple-quoted f-string literal (detected at line 1)
False
```

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-113709
* gh-113733

**Comment by hugovk** [comment]
cc @lysnikolaou @pablogsal

**Comment by pablogsal** [comment]
Thanks a lot for the report @gpotter2. I have opened https://github.com/python/cpython/pull/113709 with a more correct fix.

**Comment by gpotter2** [comment]
Great, thanks for the very quick fix.
