### ISSUE TITLE
CSV reader inconsistent with combination of QUOTE_NONNUMERIC and escapechar

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#113785]
```pycon
>>> next(csv.reader([r'2\.5'], escapechar='\\', quoting=csv.QUOTE_NONNUMERIC))
[2.5]
>>> next(csv.reader([r'.5'], escapechar='\\', quoting=csv.QUOTE_NONNUMERIC))
[0.5]
>>> next(csv.reader([r'\.5'], escapechar='\\', quoting=csv.QUOTE_NONNUMERIC))
['.5']
```

It parses numbers with an escaped character in the middle, it parses numbers starting with a dot, but it does not parse numbers starting with an escaped character. The following variants would be more consistent:

1. Any escaped character disables parsing field as a number.
2. Allow parsing a field starting with an escaped character as a number.

### Linked PRs
* gh-122110
* gh-122258
* gh-122259

**Comment by MKuranowski** [comment]
I don't know which behavior is the expected one?

To go with the 1st option (any escapes prevent conversion), a `self->numeric_field = 1;` needs to be inserted at: https://github.com/python/cpython/blob/3efcf6673e46507e144e859fa9a33d1820380b9a/Modules/_csv.c#L724

The 2nd option requires `if (dialect->quoting == QUOTE_NONNUMERIC) numeric_field = 1;` added in here: https://github.com/python/cpython/blob/3efcf6673e46507e144e859fa9a33d1820380b9a/Modules/_csv.c#L702

**Comment by serhiy-storchaka** [comment]
I think why the escape character can be used at first place. QUOTE_NONNUMERIC does not affect escaping. If the character conflicts with one of special characters, it will be escaped, number it or not. If in future we will add support of using comma as decimal separator, there will be larger chance of conflict with field delimiter, so they should be escaped. Also, escapes can be necessary use some weird dialect with `.` or `-` as a field delimiter.

So I think that option 2 is more preferable.

**Comment by serhiy-storchaka** [comment]
@MKuranowski, do you mind to create a PR?
