### ISSUE TITLE
Compare folder A and subfolder B and show files that are in folder A but not in subfolder B

### ISSUE THREAD

**Issue by me-suzy** [python/cpython#113736]
# Bug report

### Bug description:

I think Python itself has a BIG BUG. It's a folder and subfolder problem. If they were just different folders, it would have worked fine. But there is something wrong with the combination of find files from FOLDER vs SUBFOLDER.

It is a conflict between folder and subfolder. Compare folder A and subfolder B and show files that are in folder A but not in subfolder B. And when checking, it sees the different files from both folders, but when displaying it, it can't show me only the files that are in folder A, and which are not found in subfolder B

**please see this topic:**

[https://stackoverflow.com/questions/77764496/compare-folder-a-and-subfolder-b-and-show-files-that-are-in-folder-a-but-not-in](https://stackoverflow.com/questions/77764496/compare-folder-a-and-subfolder-b-and-show-files-that-are-in-folder-a-but-not-in)

I try many combinations, 

**Another version of the code here:**

```python
import os
folder1 = r"C:\Folder-Oana\extracted"
folder2 = r"C:\Folder-Oana\extracted\translated"
# Obține lista de fișiere HTML din fiecare folder
html_files_folder1 = [f.lower() for f in os.listdir(folder1) if f.lower().endswith('.html')]
print(html_files_folder1) # daca e corect, treci mai departe
html_files_folder2 = [f.lower() for f in os.listdir(folder2) if f.lower().endswith('.html')]
print(html_files_folder2) # daca e corect, treci mai departe
# Găsește diferențele între cele două liste de fișiere
missing_files = list(set(html_files_folder1) - set(html_files_folder2))
print(missing_files) # daca da corect diferenta mergi mai departe
# Afișează fișierele care lipsesc
if missing_files:
         print("Fișierele HTML care se găsesc în folderul 1, dar nu în folderul 2, sunt:")
         for filename in missing_files:
                         print(filename)
else:
         print("Nu există fișiere HTML care se găsesc în folderul 1, dar nu în folderul 2.")
```

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by me-suzy** [comment]
Here is the structure fo folder, subfolder and files:

[https://snipboard.io/jadcTP.jpg](https://snipboard.io/jadcTP.jpg)

**Comment by sobolevn** [comment]
Right now this does not look like a bug in CPython, but looks like a bug in your code :)

Please, simplify the reproducer, show what do you expect to happen, what happens and try the latest version of python (if you are confident that this is really a bug in CPython itself).

**Comment by ericvsmith** [comment]
And when simplifying the reproducer, make sure that we can run the code, without any additional setup. Your reproducer should create whatever minimum directories and files are needed to show the problem.

**Comment by me-suzy** [comment]
it is possible that this code works on other computers. I had some older versions of Python, but I uninstalled the old one and installed the new version Python 3.12.1

```
C:\Users\Castel>python --version
Python 3.12.1
```

However, there is something strange. All tested code versions, also made with ChatGPT, have a problem with FODLER vs SUBFOLDER comparison. That is, instead of finding only the html files in FOLDER A, the code also finds the html files in SUBFOLDER B.

If the error is from me, what should I do to make it work?

**Comment by me-suzy** [comment]
WORKS. The problem was with the version of Python. Thank you!



[CODE]
import os

def find_files_only_in_folder(folder, subfolder):
    folder_files = set(os.listdir(folder))
    subfolder_files = set(os.listdir(subfolder))

    files_only_in_folder = folder_files - subfolder_files

    print(f"Files only in {folder} and not in {subfolder}:")
    for file in files_only_in_folder:
        print(f"- {file}")

if __name__ == "__main__":
    folder_path = r"c:\Folder-Oana\extracted"
    subfolder_path = r"c:\Folder-Oana\extracted\translated"

    find_files_only_in_folder(folder_path, subfolder_path)

[/CODE]

**Comment by ericvsmith** [comment]
In the future, please seek help at https://discuss.python.org/c/users/7 before opening an issue here.
