### ISSUE TITLE
Add ``int.__length__`` method

### ISSUE THREAD

**Issue by AaronShenny** [python/cpython#113855]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
num = 0
def len(int):
    while int> 0:
	int =  int//10
	num =  num+1
    return num
```
if we enter a len(num) it gives :
```python
Traceback (most recent call last):
  File "<pyshell#21>", line 1, in <module>
    len(555)
TypeError: object of type 'int' has no len()
```
It will be every helpful if we add this 

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
Hello!
This kind of feature should be widely discussed. If you really want to discuss it, you should open a new thread on https://discuss.python.org/c/ideas/6.
Honestly, there's a little chance of accepting it.
Now I'm closing it, we can reopen this later if needed.

**Comment by terryjreedy** [comment]
len is defined for iterables, and an int is not iterable.  Above you have defined the length of the base 10 representation, which is `len(str(n))`.  For the length of a hex version, `len(hex(n))` or the same `-2' to not count '0x'.  One might consider the 'true' length to be the number of bits: `int.bit_length`.
