### ISSUE TITLE
socket.getfqdn() return hostname with trailing . (dot) in WSL

### ISSUE THREAD

**Issue by gugupy** [python/cpython#113818]
# Bug report

### Bug description:

I faced this problem when I was working on `smtplib.SMTP` where `ehlo` falied with invalid domain name.

While debug the problem found WSL default adding the host entry in `/etc/hosts` as below,
```
...
127.0.0.1       gugupy.       gugupy
```
FQDN
```python
>>> import socket
>>> socket.getfqdn()
>>> gugupy.
```
So `self.local_hostname` set to `gugupy.` which actually lead to the problem. 

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, Other

**Comment by vstinner** [comment]
That's not a bug of Python, but a design choice of WSL. Trailing dot in DNS names is legal. Maybe just strip it with `name = name.removesuffix('.')`.
