### ISSUE TITLE
Missing error check in `update_symbols`

### ISSUE THREAD

**Issue by WolframAlph** [python/cpython#113842]
# Bug report

### Bug description:

There is error check missing right after a loop in https://github.com/python/cpython/blob/f3d5d4aa8f0388217aeff69e28d078bdda464b38/Python/symtable.c#L935-L982
Loop breaks when `PyIter_Next` returns `NULL` indicating that it is exhausted, but if an exception occurs, it will also return `NULL` and additionally set the exception which is not checked.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-113843
* gh-113851
* gh-113852

**Comment by serhiy-storchaka** [comment]
Thank you @WolframAlph. `symtable.c` and `compile.c` are two files that contain a large number of unchecked calls of the C API. Most of them perhaps safe and never fail, but it is difficult to prove. Someday we will add error checks for every call, but it is a large change and can make the code much more complicated. But in cases like this the check does not add much complexity.
