### ISSUE TITLE
itertools.combinations complexity enhancement

### ISSUE THREAD

**Issue by adriancretu** [python/cpython#113876]
# Feature or enhancement

### Proposal:

I have the strong belief that the C backbone implementation for itertools.combinations can be improved slightly. It is pretty fast and straight-forward as it is now, but after writing some simple C code I can strongly suggest that altering the complexity of the current algorithm can produce a performance boost, especially for the use-case of a large N.

I don't have the patience to do such a PR myself, I will just elaborate on the pseudo-code, [as it is now](https://github.com/python/cpython/blob/main/Modules/itertoolsmodule.c#L2593).

Current:
1. Initialization: creates initial indices - complexity O(n)
2. Next() - a bunch of checks if this is the first call, otherwise:
      2.1 search for the left-most value at its maximum - O(n)
      2.2 check if none found
      2.3 increment non-maximum current position
      2.4 increment all other values to the right of that
      2.5 update result tuple

Proposed enhancement:
    Most of the time, the only value that will need updating is the right-most element.
    We can obtain better speed if we only do steps 2.2, 2.3 and 2.4 in case the right-most element actually reached its max value. This may not seem much, but getting rid of several useless checks and loops that never actually execute can end up with significant performance boost.
    Also, with a little hack we can get rid of the initial indices creation. I tested this with real data for any N >= 1.
    
 Pseudo-code for next():
 ```
 last_offset = size - 1
 i = last_offset
 if indices[i] = max_for_index(i):
    if i == 0: goto empty;    // done (N = 1, reached max)
    while True:
        i--;
        if indices[i] < max_for_index(i) break;     // this position can update!
        if i == 0: goto empty;    // reached first element but can't update it

    indices[i]++.  // guaranteed it supports higher values
    // we can do-while because we know that current i cannot be the LAST index
    // this saves on a useless initial loop entry check that is always true
    do:
        i++;
        indices[i] = indices[i - 1] + 1;
    while i < last_offset
 else:
     // boom - simply increment the rightmost element, forget all the loops and checks
     indices[i]++.  // or indices[last_index]++ 
     
  // update result tuple.... (we can have some var to track from which position data changed)
 ```

I implemented in C the current algorithm used by Python vs the above pseudo-code - but obviously without the tuple creation and etc, purely to test out the complexity benefits.
Result: naive variant (Python) was around 4x slower than optimized paths taken above.

Bonus - we can get rid of the initial indices creation.

By adding a state variable - let's call it "position" or "cursor" we can force next() to produce the very first combination on the fly, not during initialization.
How, you ask?
```
// initialization - instead of looping from 1 to K, simply set the second element to its maximum value
indices[0] = 0
if k > 1:
    indices[1] = max_val_for_idx(1)
    state->cursor = 1
 else:
     state->cursor = 0.   // k = 1 

// next() - init i with state position instead of last_index
i = state->cursor
....
// set state->cursor to last_index
```

Regards!

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-113917

**Comment by Eclips4** [comment]
cc @rhettinger

**Comment by rhettinger** [comment]
> Most of the time, the only value that will need updating is the right-most element.

To my eyes, the current algorithm already focused on that case.  The search-loop starts from the right side. If only one element needs to change, there is only one iteration. So it is `O(n)`only in the worse case and closer to O(1) in the common case.

For `combinations(range(20), r=5)`, the loop counts by position are `15  135   800  3740   14688`.  The work is dominated by the two rightmost positions. Only 15 times do we run the full loop.

So, I don't think there is much fat to cut here and I am dubious that any noticeable savings can be had by trying to eliminate the search-loop.  That said, I would be delighted to be proved wrong with an actual PR that we can race against the current code.   Since I think a noticeable improvement is unlikely, the suggestion will likely sit until someone comes along that believes in it enough to devote time to work on it.

Looking a the C implementation again, I do think there is an opportunity to speed-up the case where the result tuple cannot be reused.  Instead of copying the old tuple and then updating it, the pool values can be copied in directly.  That will save a few unnecessary increfs and decrefs.  I will work on that part when I get a chance.

**Comment by adriancretu** [comment]
You are correct, overall the algorithm runs the same total number of reads and writes on the indices array for the guarantee of ordered results. I'd call this more like a micro-optimization to save a few CPU cycles, mainly because of the rest of the overhead that doesn't have to do with the actual "next combination" computation.

However if one needs major speed-up boost to generate simple integer combinations (and not as tuples) a C implementation that modifies a raw integer array buffer would indeed run a few times faster, due to this fast path to "only last index updated". Since we're working with combinations which can have indefinite (let's say tens of millions) of possible yields, the unnecessary triple loops conditionals add up a lot.

**Comment by adriancretu** [comment]
[rhettinger](https://github.com/rhettinger) I created a PR which hopefully proves my initial claims. It should be benchmarked in such a way to skip the overheads associated to tuple copying or recreation (e.g. blind iteration via dequeue).

Regards.

**Comment by adriancretu** [comment]
PR passes all validation tests. I got fooled by the fact the indices array can be 0 length. Not sure if that is intended or not (a 0-sized array is being allocated), but the code works as expected now.
