### ISSUE TITLE
For csv.DictReader, make line_num a property

### ISSUE THREAD

**Issue by sadfsdgsg** [python/cpython#113826]
### Proposal:
```python
f = pathlib.Path('myFile.csv')
my_csv = dictReader(f)

print(my_csv.line_num) # will print '0' in any case

next(my_csv # will update line_num
my_csv.fieldnames # will update line_num as well, since the property calls next()

print(my_csv.line_num) # will now print the correct line_num...



```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

[As issued](https://github.com/python/cpython/issues/46684) line_num was implemented for csv.DictReader. This attr should be a property and updated like fieldnames(through going __next()). This will make it possible to request the length of a file of a freshly created DictReader instance. If you need to know the line_num for a fresh object, you will (at the moment) call next() or ask for fieldnames(which calls next).

**Comment by vaishnavi192** [comment]
Hey @sadfsdgsg I would like to work on this issue....I am a newbie in open source so just need a bit help...we have to implement line_num as a property right....
import csv

class ModifiedDictReader(csv.DictReader):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._line_num = 0    # private variable to hold the line number
    
    @property
    def line_num(self):
        return self._line_num
    
    def __next__(self):
        row = super().__next__()
        self._line_num += 1    # increment line_num after each row
        return row
    
    def _fieldnames(self):    # internal method to access the fieldnames
        return self.fieldnames

    @property
    def fieldnames(self):
        self._line_num = 0    # reset line_num when fieldnames is accessed
        return self._fieldnames()

# Example usage
reader = ModifiedDictReader(open('data.csv', 'r'))

# Access line_num
print(reader.line_num)    # Output: 0

# Access fieldnames (automatically increments line_num)
print(reader.fieldnames)    # Output: ['name', 'age', 'city']
print(reader.line_num)    # Output: 1 

# line_num increments for each row
for row in reader:
    print(row)    # Output: {'name': 'John', 'age': '25', 'city': 'New York'}
    print(reader.line_num)    # Output: 2, 3, and so on for each row
plz tell if these changes looks fine and solve the problem and kindly assign me this issue. Thanks

**Comment by AlexWaygood** [comment]
Hi @vaishnavi192, welcome to CPython! Unfortunately I'm afraid I'm quite busy at the moment, and not really an expert on the `csv` module, so I probably won't be able to help out with this one :/ I just did a little bit of drive-by triaging here to classify the issue. I'll ask if anybody else is available to help mentor you, however :)

**Comment by vaishnavi192** [comment]
sure @AlexWaygood Thanks yeah it will be good if someone helps. I want to confirm changes and then I will open pr

**Comment by serhiy-storchaka** [comment]
I think there is some misunderstanding. `line_num` is not the length of a file. It is the number of lines read from the source iterator. At the beginning it is 0. After reading first record it is the number of lines that the first record spans (it can be more than 1). You can only get the total number of lines when you iterate all records. Requesting `line_num` should not have visible side effect.

**Comment by sadfsdgsg** [comment]
Oh wow, thank you so much for explaining!! Totally makes sense to not be a property then! Guess I will have a look to clear that up in the documentation then. I totally got that wrong...

**Comment by willingc** [comment]
@vaishnavi192 I'm happy to provide some general guidance as you work to contribute to CPython. I'm beginning to create a mentoring guide so your questions would be useful to me. Feel free to email me at willingc@python.org.

**Comment by vaishnavi192** [comment]
@willingc Thanks a lot for helping! Yes I messaged you on email. Hope to talk to you further. Thanks
