### ISSUE TITLE
Make all executors execute tier 2 instructions (micro-ops)

### ISSUE THREAD

**Issue by markshannon** [python/cpython#113860]
[Our plan](https://github.com/faster-cpython/ideas/blob/main/3.13/engine.md) proposes that we either execute all tier 2 code in the tier 2 interpreter or by [jitting the code](https://github.com/python/cpython/pull/113465)

However, our current executor interface allows calls to arbitrary function pointers.
We should remove that interface, requiring all optimizers to produce tier 2 micro-ops, which the VM is responsible for executing.

This will prevent low-level JITs like Cinder from using executors, but Cinder uses `PyFunction_SetVectorcall` to insert machine code anyway.
Higher level JITs like PyTorch dynamo, can potentially still use executors, as they provide a more powerful and flexible interface than PEP 523.

### Linked PRs
* gh-113864
* gh-113954

**Comment by erlend-aasland** [comment]
Is there more work left to do?

**Comment by markshannon** [comment]
Nope
