### ISSUE TITLE
`asyncio` `ProactorEventLoop` didn't check if the `socket` is blocking

### ISSUE THREAD

**Issue by NewUserHa** [python/cpython#113892]
# Bug report

### Bug description:

```python
import asyncio
import socket

s = socket.socket()
await asyncio.get_running_loop().sock_connect(s,('127.0.0.1',80))
```
according to https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.sock_connect and https://github.com/python/cpython/blob/5d8a3e74b51a59752f24cb869e7daa065b673f83/Lib/asyncio/selector_events.py#L617-L630
it should raise. however, `ProactorEventLoop` doesn't follow the rule

should we fix this, any thoughts

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-119519
* gh-119912
* gh-119913

**Comment by gvanrossum** [comment]
Oh, interesting. The question is, does async sending and receiving using that blocked socket work when using the `ProactorEventLoop`? Given how different IOCP is, it wouldn't surprise me if it did. Can you write a small test to check that? (There are probably tests you can adapt.)
