### ISSUE TITLE
MacOS source code build, Python 3.11, missing _tkinter support

### ISSUE THREAD

**Issue by MacDaddy1660B** [python/cpython#113880]
# Bug report

### Bug description:

I'm attempting to build Python 3.11 from source on MacOS Ventura. The build misses the ```_tkinter``` module, which I need.

I've compiled my own build of Tcl/Tk 8.6 from source, with Aqua enabled. It is installed in ```/Library/Frameworks/Tcl.framework``` and ```Tk.framework``` respectively.

I've set the ```TCLTK_CFLAGS``` and ```TCLTK_LIBS``` environment variables (show below in the configure output).

When I run the configure script, the result is missing ```_tkinter``` support. ```config.log``` shows the following

```
configure:13714: gcc -o conftest   -I/Library/Frameworks/Tcl.framework/Headers/ -I/Library/Frameworks/Tcl.framework/Headers/  conftest.c -L/Library/Frameworks/Tcl.framework/ -ltclstub8.6 -L/Library/Frameworks/Tk.framework/ -ltkstub8.6  >&5
In file included from conftest.c:120:
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/tk.h:31:3: error: Tk 8.5 must be compiled with tcl.h from Tcl 8.5
#       error Tk 8.5 must be compiled with tcl.h from Tcl 8.5
```

So the issue the configure script is looking at the Xcode CLT for some reason, and not the new source build in ```/Library/Frameworks```.

Is there a way to get the configure script to look directly at my TclTk build?

I tried building and installing Tcl and Tk 8.6 from source, and expected Python's configure script to use them through the ```TCLTK_CFLAGS``` and ```TCLTK_LIBS``` environment variables.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by ned-deily** [comment]
It looks like you might have a typo in your `TCLTK_CFLAGS` value:

` -I/Library/Frameworks/Tcl.framework/Headers/ -I/Library/Frameworks/Tcl.framework/Headers/
`

That second one should likely be `Tk.framework`.

**Comment by erlend-aasland** [comment]
The conftest shows the following command-line given to `gcc` (broken up in multiple lines by me):

> configure:13714: gcc \
>     -o conftest \
>     -I/Library/Frameworks/Tcl.framework/Headers/ \
>     -I/Library/Frameworks/Tcl.framework/Headers/ \
>     conftest.c \
>     -L/Library/Frameworks/Tcl.framework/ \
>     -ltclstub8.6 \
>     -L/Library/Frameworks/Tk.framework/ \
>     -ltkstub8.6

Perhaps the answer lies in the identical include directories?

>     -I/Library/Frameworks/Tcl.framework/Headers/ \
>     -I/Library/Frameworks/Tcl.framework/Headers/ \

Since there is no include search patch given for the Tk sources, I guess `gcc` (and not `configure`) goes looking in the system directories. Can you share your `TCLTK_CFLAGS` and `TCLTK_LIBS`? (Or just attach `config.log`)

**Comment by MacDaddy1660B** [comment]
Oh my goodness, I can't believe I missed that. Thanks for your help!

However, I have a different issue now. I'll try to figure it out. Thank you.

**Comment by MacDaddy1660B** [comment]
Resolved.
