### ISSUE TITLE
inaccurate documentation for `shutil.move` when dst is an existing directory

### ISSUE THREAD

**Issue by daiwt** [python/cpython#113803]
# Documentation

(A clear and concise description of the issue.)

In the [doc of shutil](https://github.com/python/cpython/blob/3.12/Doc/library/shutil.rst?plain=1#L360) it says:

```rst
If the destination is an existing directory, then *src* is moved inside that
directory. If the destination already exists but is not a directory, it may
be overwritten depending on :func:`os.rename` semantics.
```

However, before calling `os.rename`, it checks the existence of the destination path, and raises Error if it exists. see [shutil.py](https://github.com/python/cpython/blob/3.12/Lib/shutil.py#L883).

This behavior is not described in the documentation, and may be different from how files are overwritten in `os.rename`. For example, `os.rename('a.txt', '/b')` will silently replace `/b/a.txt` on Unix, but `shutil.move('a.txt', '/b')` will raise an Error.

In the [docstring](https://github.com/python/cpython/blob/3.12/Lib/shutil.py#L849) however, this is described much more clear:
```
If the destination is a directory or a symlink to a directory, the source
is moved inside the directory. The destination path must not already
exist.

If the destination already exists but is not a directory, it may be
overwritten depending on os.rename() semantics.
```
This should be also in the documentation, IMO.

### Linked PRs
* gh-113837
* gh-115006
* gh-115007

**Comment by serhiy-storchaka** [comment]
Agree. Do you mind to create a PR?
