### ISSUE TITLE
New warning: `‘_Py_stdlib_module_names’ defined but not used` in `Python/stdlib_module_names.h`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#113845]
# Bug report

<img width="635" alt="Снимок экрана 2024-01-09 в 11 21 27" src="https://github.com/python/cpython/assets/4660275/3079a778-973e-457c-a910-3db41a688b45">

This happens in all recent PRs, examples:
- https://github.com/python/cpython/pull/113835/files
- https://github.com/python/cpython/pull/113843/files

### Linked PRs
* gh-113949

**Comment by Eclips4** [comment]
Seems it's created for this PR: https://github.com/python/cpython/pull/113769

**Comment by serhiy-storchaka** [comment]
It was introduced by #110721. @pablogsal

**Comment by pablogsal** [comment]
As probably will be used in https://github.com/python/cpython/pull/113769 let's not remove yet.

**Comment by serhiy-storchaka** [comment]
`#113769` does not touch `Python/suggestions.c`.

**Comment by pablogsal** [comment]
Ah, sorry, this is because we are `#include "stdlib_module_names.h"  // _Py_stdlib_module_names` in `suggestions.c`. Right, I will create a PR removing the include 👍

**Comment by vstinner** [comment]
Currently, `_Py_DumpExtensionModules()` iterates on `sys.stdlib_module_names` with complicated code. Maybe it should just reuse `_Py_stdlib_module_names` list of C bytes strings.

Maybe `static const char* _Py_stdlib_module_names[] = {` should not be static, and exposed in pycore_sysmodule.h?
