### ISSUE TITLE
Walrus operator bug in the interpreter

### ISSUE THREAD

**Issue by R1senDev** [python/cpython#113898]
# Bug report

### Bug description:

```python
Python 3.11.4 (main, Sep 30 2023, 10:54:38) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> x := 1
  File "<stdin>", line 1
    x := 1
      ^^
SyntaxError: invalid syntax
>>>
```
It doesn't seem right. It is logical to assume that the value (1 in my example) should be assigned to the variable (x) and output to the terminal, however, we see SyntaxError here.
If this is not really a problem, I apologize.

**Thanks for your attention!**

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
That's intended behaviour. See https://github.com/python/cpython/issues/111944#issuecomment-1805603021 for more information.
