### ISSUE TITLE
Lack of fallback for `pthread_threadid_np` leaves Python broken on older macOS

### ISSUE THREAD

**Issue by barracuda156** [python/cpython#113889]
# Bug report

### Bug description:

Older macOS versions (10.5.8 and earlier for x86, 10.6.8 and earlier for ppc) do not have `pthread_threadid_np`, which leaves Python there unnecessarily broken. There is a simple fallback for it via `pthread_mach_thread_np`, which is used elsewhere, for instance Ruby, `i2pd`, `spdlog`.

The issue can be fixed with a minimal patch.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-113890

**Comment by ronaldoussoren** [comment]
To be honest, I doubt if it is a good idea to fix this. MacOS 10.5 and 10.6 are outside of the set of releases we generally support or even could easily test.

@ned-deily, what's you opinion on this?

**Comment by vstinner** [comment]
I suggest maintaining such patch outside Python code base. I don't think that we should support very old macOS versions and macOS on PowerPC. There is no plan to actively support such platform, nor have automated tests on it. Well, that's just my opinion ;-)

**Comment by ned-deily** [comment]
I agree with @ronaldoussoren and @vstinner here. While we don't have an official Python policy about what releases of macOS we support (something we should add to [PEP 11](https://peps.python.org/pep-0011/), the most recent bugfix release of these operating system versions was over a dozen years ago and the hardware that they run on is even older. In general, we prefer not to add something that won't be testable in our CI or buildbot environment. And there is a cost to adding seemingly benign code, especially to something as quirky as pthreads. There have to be other places in the current code base where there are problems on these old platforms and, if we accept this change, that could imply a commitment to accept other, even more complex changes. And, as a practical matter, third-party libraries, that Python and standard library modules depend on, also have problems on older systems and require unsupported patches.

I think it's admirable to try to keep old platforms running, and I know you, @barracuda156, have contributed many patches for many products on such platforms to the MacPorts project. I suggest this would be the best place for this one, too.
