### ISSUE TITLE
``test_type_cache`` fails with ``--forever`` argument

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#113937]
# Bug report

### Bug description:

Trace:

```python
./python.exe -m test -q test_type_cache --forever
Using random seed: 2064316463
0:00:00 load avg: 2.54 Run tests sequentially
test test_type_cache failed -- Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/test/test_type_cache.py", line 132, in test_class_load_attr_specialization_static_type
    self._assign_and_check_valid_version(str)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/admin/Projects/cpython/Lib/test/test_type_cache.py", line 90, in _assign_and_check_valid_version
    self.assertNotEqual(type_get_version(user_type), 0)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 == 0


== Tests result: FAILURE ==

1 test failed:
    test_type_cache

Total duration: 50 ms
Total tests: run=14 failures=1
Total test files: run=2 failed=1
Result: FAILURE

```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-113953

**Comment by Eclips4** [comment]
Seems to be introduced in #113558. This PR should be backported to 3.11 and 3.12 (but not backported yet), that's why I'm adding 3.11 & 3.12 labels.

**Comment by lazorchakp** [comment]
Sorry for this - I certainly introduced it. The first issue should be resolvable by skipping tests if we run out of version tags (like what was done in the preexisting `test_tp_version_tag_unique`). I'm not sure what could be causing the second, though. @Fidget-Spinner if you'd like another set of eyes on this, lmk

**Comment by Fidget-Spinner** [comment]
@lazorchakp if you'd like to submit a PR to fix it I would be happy to review it as well! For the second case, it's possible that the specialization has not reverted yet. In CPython, code objects are shared across functions (so every time you create a new function, it reuses the same code object, you can `dis.dis` a closure to see what I mean). So the specialization from a previous iteration could stick around for abit until it de-specializes by running the loop a few times. Because of that, I think it's fine to remove that line.

**Comment by lazorchakp** [comment]
Oh that's interesting! I should be able to get a PR open pretty quickly

**Comment by encukou** [comment]
`test_type_cache` seems to be failing for pretty much all the refleak buildbots, probably due to this fix.
Please let me know if you need help.

**Comment by Eclips4** [comment]
> `test_type_cache` seems to be failing for pretty much all the refleak buildbots, probably due to this fix. @Fidget-Spinner, please let me know if you need help.

Can you share link to the failing buildbot, please? I cannot reproduce it locally

**Comment by encukou** [comment]
Oh, I read the wrong timestamp in my buildbot triage :(
Sorry for the alarm!
