### ISSUE TITLE
Python 3.12 rstrip() has issues with certain types of string values.

### ISSUE THREAD

**Issue by manju-anandakrishnan** [python/cpython#113927]
# Bug report

### Bug description:

```python
filename = 'phosphosites.csv'
print(filename.rstrip('.csv'))
```
The code would output 'phosphosite' instead of 'phosphosites'. The same happens with stripping '.tsv' as well. However it works fine when filename is 'phosphositet.csv' or 'phosphositet.tsv'.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by zware** [comment]
Please see the [documentation for `str.rstrip()`](https://docs.python.org/3/library/stdtypes.html#str.rstrip), which will refer you to [`str.removesuffix()`](https://docs.python.org/3/library/stdtypes.html#str.removesuffix) instead for this use case.

For filenames, you may be more interested in `os.path` or `pathlib`, though.
