### ISSUE TITLE
`isinstance` support for `Union` aliases defined by `type` keyword. (PEP695)

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#113904]
# Feature or enhancement

### Proposal:

This was pointed out by Nikita Sobolev in https://github.com/python/cpython/issues/106246#issuecomment-1613336785, it seemed worthwhile to have as a separate issue.

```python
from typing import TypeAlias
# old style
Number: TypeAlias = int | float
assert isinstance(0, Number)  # ✅
# new style
type Number = int | float
assert isinstance(0, Number)  # ❌ TypeError: isinstance() arg 2 must be a type, a tuple of types, or a union
```

This prevents changing old code to the new PEP 695 syntax if type aliases define unions and are used in `isinstance` checks.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-113911

**Comment by JelleZijlstra** [comment]
This was done this way on purpose. Type aliases may contain objects that do not support `isinstance()`, and the new syntax seeks to make a clear separation between runtime and type-time uses of aliases. We can possibly change it, but we'll have to think about it carefully.

cc @erictraut

**Comment by sobolevn** [comment]
@JelleZijlstra oh, I didn't know about that. This would be a very hard concept to teach.

Let's say I have this type alias: `type MessageType = bytes | str`

And then later it can be used with, say, `pydantic`:

```python
class Payload(BaseModel):
    message: MessageType
```

What should we do here? Write a new type alias in an older form?

**Comment by hmc-cs-mdrissi** [comment]
Yeah I don’t see how new style type aliases will interact well if you commonly use bear type/cattrs/typeguard/similar libraries. I’m sure those libraries could all add extra logic to make there flavor of runtime checking work but feels like a surprise inconsistency and an easy way to have a bug.

I think if intent of bigger gap between type system vs runtime would make me lean towards if I use runtime type tools I should avoid new style aliases. In case of tools that run type asserts  at runtime that’d effectively either mean avoid new aliases almost everywhere or file tickets to those tools to support new aliases. https://typeguard.readthedocs.io/en/stable/userguide.html#using-the-pytest-plugin is one example where I’d expect most replacements of old aliases with new aliases to cause error.

**Comment by JelleZijlstra** [comment]
I now think we shouldn't do this: https://discuss.python.org/t/run-time-behaviour-of-typealiastype/43774/16

**Comment by sobolevn** [comment]
Yes, I agree:

```python
>>> type a = int | str
>>> from typing import TypeAliasType
>>> isinstance(a, TypeAliasType)
True
>>> isinstance(1, a.__value__)
True
```

**Comment by randolf-scholz** [comment]
That's a fine resolution. Although, it makes me wonder why everything is dunder on `TypeAliasType`.
