### ISSUE TITLE
[Bug] Issue with sprftime method in time

### ISSUE THREAD

**Issue by kcv-odoo** [python/cpython#113935]
# Bug report

### Bug description:

```python
import time
input_time_string = '12:30:30'
// zh_HK лагуна
lang_time_format = `%I時%M分%S秒`
formated_time = time.strptime(input_time_string, lang_time_format)
print(formated_time)
```
Result: 1900-01-01 12:30:30
Expected result: 12時30分30秒

strptime should work for given time format and also not give any random date with time
It should return only time with proper time format

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
`time.strptime()` is to "parse a string representing a time according to a format".

https://docs.python.org/3/library/time.html#time.strftime

So for example, you might do this:

```pycon
>>> import time
>>> time.strptime("12:30:30",  "%I:%M:%S")
time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=30, tm_sec=30, tm_wday=0, tm_yday=1, tm_isdst=-1)
```

If you have different characters in the input string, you might do this:


```pycon
>>> import time
>>> time.strptime("12時30分30",  "%I時%M分%S")
time.struct_time(tm_year=1900, tm_mon=1, tm_mday=1, tm_hour=0, tm_min=30, tm_sec=30, tm_wday=0, tm_yday=1, tm_isdst=-1)
```

I think what you want to do is parse a time string that uses colons, and then format it using `time.strftime()`. 

https://docs.python.org/3/library/time.html#time.strftime

For example:

```pycon
>>> import time
>>> my_time = time.strptime("12:30:30",  "%I:%M:%S")
>>> time.strftime("%I時%M分%S秒", my_time)
'12時30分30秒'
```

Anyway, this is not a bug in Python. For further questions, please ask at https://discuss.python.org/c/users/7 or https://stackoverflow.com/.

**Comment by terryjreedy** [comment]
The original posted code has 2  syntax errors and raises a ValueError when those are corrected.  When posting, please copy and paste the actual code run.
