### ISSUE TITLE
Unbounded reads by `zipfile` may cause a `MemoryError`.

### ISSUE THREAD

**Issue by insistxc** [python/cpython#113977]
# Bug report

### Bug description:

```python
def _EndRecData(fpin):
    """Return data from the "End of Central Directory" record, or None.

    The data is a list of the nine items in the ZIP "End of central dir"
    record followed by a tenth item, the file seek offset of this record."""

    # Determine file size
    fpin.seek(0, 2)
    filesize = fpin.tell()

    # Check to see if this is ZIP file with no archive comment (the
    # "end of central directory" structure should be the last item in the
    # file if this is the case).
    try:
        fpin.seek(-sizeEndCentDir, 2)
    except OSError:
        return None
    data = fpin.read()
    if (len(data) == sizeEndCentDir and
        data[0:4] == stringEndArchive and
        data[-2:] == b"\000\000"):
```
![image](https://github.com/python/cpython/assets/79511187/5fa227ce-3994-47c0-a082-40fbf1ab3058)

When checking whether a file is a zip file, MemoryError was triggered, followed by OOM. After investigation, it was found that it was a read() read exception.

Through PDB debugging, it was found that a link file was read, which points to /proc/kcore, why does the existing zip file check not determine whether it is a zip file by reading the header byte (504B0304) of the file . 

I think the existing judgment ZIP method does not limit the read reading. When reading a non -normal file, it may cause the system to collapse .

Hope to be resolved.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-122101
* gh-126347
* gh-126348

**Comment by danifus** [comment]
This implements the suggested change: https://github.com/python/cpython/pull/122101

**Comment by cmaloney** [comment]
There's a secondary thing here, that unbounded read defaults to the size at open with https://github.com/python/cpython/pull/120755. In this bug that's more than the amount of RAM remaining on the machine, hence the MemoryError / OOM. That stashed size is currently invalidated on `.truncate()` but not on `.seek()` which `zipfile` uses. I'd like to make `seek()` clear the estimated size, but that change conflicts a lot with https://github.com/python/cpython/pull/121593, so have been holding off.

#122101 I think resolves this case for `zipfile` (and makes it more predictable, safer behavior generally) but I suspect the `.seek()` case will come up more in library code, so before python 3.14 would like to get that to invalidate the cached size generally.

**Comment by picnixz** [comment]
potential) DDoS like that considered as security issues or not? @gpshead

**Comment by gpshead** [comment]
> Are (potential) DDoS like that considered as security issues or not? @gpshead

They can be, but not particularly severe. I don't think _this_ one is worth considering a security problem because the circumstances in which it can occur are extremely limited: Someone has to have opened a file that either isn't seekable or provides an egregious amount of data upon read after seeking to the end.

Just constructing that scenario in the first place is a sign of greater problems in the system.

@sethmlarson as FYI

**Comment by gpshead** [comment]
Thanks for the nice bug report and PRs.  The 3.12 and 3.13 back ports are also set to auto merge.  Indeed, avoiding unbounded read assumptions is the right coding practice.
