### ISSUE TITLE
Speed up Counter.__eq__

### ISSUE THREAD

**Issue by keithasaurus** [python/cpython#113947]
# Feature or enhancement

### Proposal:

`Counter`'s `__eq__` method could be a bit faster with trivial changes.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-113948

**Comment by hauntsaninja** [comment]
In case this is a perf bottleneck for you in real code, in the specific case where Counters are mostly equal, you can do the following for a very nice speedup:
```
for e, _ in self.items() ^ other.items():
    if self[e] != other[e]:
        return False
return True
```
(we probably can't commit it since it regresses comparisons between very different Counters, but mentioning in case useful to you!)
