### ISSUE TITLE
Document tuples and __new__

### ISSUE THREAD

**Issue by blhsing** [python/cpython#114071]
In this StackOverflow [answer](https://stackoverflow.com/a/77817668/6890912), Ethan Furman, the author of the `enum` module, demonstrated how a tuple value is [special-cased](https://github.com/python/cpython/blob/1709020e8ebaf9bf1bc9ee14d56173c860613931/Lib/enum.py#L256) so that it can be [unpacked](https://github.com/python/cpython/blob/1709020e8ebaf9bf1bc9ee14d56173c860613931/Lib/enum.py#L262) as arguments to the constructor of the mixin type, making it possible to extremely elegantly implement a member type with additional information such as a label for each member as requested by the SO question:
```python
from enum import Enum

class LabelledEnumMixin:

    labels = {}

    def __new__(cls, value, label):
        member = object.__new__(cls)
        member._value_ = value
        member.label = label
        cls.labels[value] = label
        return member

    @classmethod
    def list_labels(cls):
        return list(l for c, l in cls.labels.items())


class Test(LabelledEnumMixin, Enum):
    A = 1, "Label A"
    B = 2, "Custom B"
    C = 3, "Custom label for value C + another string"

print(list(Test))
print(Test.list_labels())
```
This outputs:
```
[<Test.A: 1>, <Test.B: 2>, <Test.C: 3>]
['Label A', 'Custom B', 'Custom label for value C + another string']
```
Such a neat behavior of a tuple value is currently undocumented in the [Supported `__dunder__` names](https://docs.python.org/3/library/enum.html#supported-dunder-names) section of the `enum`'s docs, however, making it more of an implementation detail rather than a publicly usable feature.

Please help document this feature properly so we can all benefit from the new possibilities this feature enables without fearing that we are using an undocumented implementation detail. Thanks.

### Linked PRs
* gh-114871
* gh-114993

**Comment by SultanOrazbayev** [comment]
The handling of tuples is interesting indeed. Here are two examples that seek to achieve the same thing, but one will fail because of the special handling for tuples.

Using dataclasses (works):

<details>

```python
from dataclasses import dataclass
from enum import Enum

@dataclass
class CodeLabel:
    code: int
    label: str

class LabelledEnumMixin:

    labels = {}

    def __new__(cls, codelabel: CodeLabel):
        member = object.__new__(cls)
        member._value_ = codelabel.code
        member.label = codelabel.label
        cls.labels[codelabel.code] = codelabel.label
        return member

    @classmethod
    def list_labels(cls):
        return list(l for c, l in cls.labels.items())



class Test(LabelledEnumMixin, Enum):
    A = CodeLabel(1, "Label A")
    B = CodeLabel(2, "Custom B")
    C = CodeLabel(3, "Custom label for value C + another string")

Test.list_labels()
```

</details>

Using NamedTuple (fails):

<details>

```python
from typing import NamedTuple
from enum import Enum

class CodeLabel(NamedTuple):
    code: int
    label: str

class LabelledEnumMixin:

    labels = {}

    def __new__(cls, codelabel: CodeLabel):
        member = object.__new__(cls)
        member._value_ = codelabel.code
        member.label = codelabel.label
        cls.labels[codelabel.code] = codelabel.label
        return member

    @classmethod
    def list_labels(cls):
        return list(l for c, l in cls.labels.items())



class Test(LabelledEnumMixin, Enum):
    A = CodeLabel(1, "Label A")
    B = CodeLabel(2, "Custom B")
    C = CodeLabel(3, "Custom label for value C + another string")

Test.list_labels()
```

</details>

**Comment by ethanfurman** [comment]
The `NamedTuple` problem is a different problem, and should get its own issue #.  @SultanOrazbayev, can you create a new one?
