### ISSUE TITLE
code.py not allowed, simplest possible setup [2]

### ISSUE THREAD

**Issue by elexunix** [python/cpython#114052]
# Bug report

### Bug description:

I'm sorry, this is a new version of #114028 (which was absurd, as I copied another code snippet there accidentally, that example was of course not what I wanted to demonstrate..)

I take the newest python3.12 image, and just do the following, without any external libs/soft at all:
```
$ sudo docker run -it --rm python:3.12 bash
root@717b1514f3bc:/# echo abacaba > code.py
root@717b1514f3bc:/# python3
Python 3.12.1 (main, Jan 11 2024, 09:52:34) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pdb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/pdb.py", line 77, in <module>
    import code
  File "/code.py", line 1, in <module>
    abacaba
NameError: name 'abacaba' is not defined
```

Expected behaviour: 'import pdb' completes without issues, my file code.py is of course not executed, as I didn't ask for that
Observed behaviour: Python tries to execute the unrelated file code.py in my directory

### CPython versions tested on:

3.9, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by sunmy2019** [comment]
Do not use names that might shadow the names from the standard library.

`pdb` is trying to import `code` from stdlib, but got hijacked by your `code.py`.

**Comment by hauntsaninja** [comment]
When using Python 3.11 or newer you can also use -P
