### ISSUE TITLE
fcntl: F_SEAL_FUTURE_WRITE constant

### ISSUE THREAD

**Issue by emanuele6** [python/cpython#114061]
# Feature or enhancement

### Proposal:

#13694 added `fcntl.F_ADD_SEALS`/`fcntl.F_GET_SEALS` and the `fcntl.F_SEAL_*` constants in the `fcntl` module, but the "new" `fcntl.F_SEAL_FUTURE_WRITE` constant from Linux 5.1 is missing.

Also, [the documentation of the `fcntl` module](https://docs.python.org/3/library/fcntl.html?highlight=fcntl) only mentions the constants in:
> *Changed in version 3.8*: The fcntl module now contains `F_ADD_SEALS`, `F_GET_SEALS`, and `F_SEAL_*` constants for sealing of [`os.memfd_create()`](https://docs.python.org/3/library/os.html#os.memfd_create) file descriptors

Instead of listing out "`F_SEAL_WRITE`, `F_SEAL_SHRINK`, `F_SEAL_GROW`, and `F_SEAL_SEAL`", so I was not expecting `F_SEAL_FUTURE_WRITE` to be missing.

It would be awesome if `F_SEAL_FUTURE_WRITE` (`0x10` by the way) was also defined in `fcntl`! :-)

Thank you!

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ronaldoussoren** [comment]
Do you want to provide a PR for this?

**Comment by serhiy-storchaka** [comment]
I included it in #114322.
