### ISSUE TITLE
No support for 3.11?

### ISSUE THREAD

**Issue by Lars-Albinsson** [python/cpython#114085]
# Bug report

### Bug description:

I can't install on 3.11. 
A week ago I could.

```pytho
pip install zipfile
ERROR: Could not find a version that satisfies the requirement zipfile (from versions: none)
ERROR: No matching distribution found for zipfile
```
Python version
3.11.4 (main, Jul  5 2023, 09:00:44) [Clang 14.0.6 ]

Thanx from a great library!!

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Hello!
``zipfile`` is part of Python standard library, so there's no need in downloading it via pip.

**Comment by Lars-Albinsson** [comment]
Sorry for being incompetent...
