### ISSUE TITLE
Add support for iOS as a target platform

### ISSUE THREAD

**Issue by freakboy3742** [python/cpython#114099]
# Feature or enhancement

### Proposal:

As proposed by [PEP 730](https://peps.python.org/pep-0730/), it should be possible to compile and run CPython on iOS.

This is a meta-issue for the various PRs implementing this support to reference.

For historical reference: this was previously managed as #67858 (BPO23670).

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

[PEP 730 Discussion thread](https://discuss.python.org/t/pep-730-adding-ios-as-a-supported-platform/35854)

### Linked PRs
* gh-114889
* gh-115023
* gh-115063
* gh-115120
* gh-115390
* gh-115930
* gh-116454
* gh-117052
* gh-117057
* gh-118020
* gh-118073
* gh-118378

**Comment by FFY00** [comment]
AFAICT, the iOS buildbots haven't been added yet. Is this being tracked anywhere?

**Comment by freakboy3742** [comment]
@FFY00 There's no specific ticket for adding an iOS buildbot (that I'm aware of, anyway); I'm happy to add a ticket if there should be one. 

A status update on buildbots - I'm currently wrangling Anaconda's procurement processes to get an ARM64 macOS box provisioned. This has proven a much more complex request than I originally anticipated, due to the availability of arm64 macOS cloud hardware. 

As a last resort, I have an ARM64 Mac mini that I can donate to the cause; however, I'd rather not make my home network part of critical CPython infrastructure :-)

**Comment by ned-deily** [comment]
As a placeholder reminder, we should add some info on iOS builds and testing to the [devguide](https://devguide.python.org), even if mainly links to other docs in the cpython repo.

And there eventually needs to be an entry for this in the [What’s New In Python 3.13](https://docs.python.org/dev/whatsnew/3.13.html) document.

**Comment by freakboy3742** [comment]
The devguide is [already done](https://github.com/python/devguide/pull/1296).

I'm happy to add a PR for the What's New document; I guess the question is how notable is the change on the list? Naturally, I think it's the most important change, but I imagine others may think differently :-) Any suggestions/guidance?

Lastly: still working on the buildbot - I've poked my line manager about this today, so hopefully there will be movement soon?

**Comment by freakboy3742** [comment]
A [buildbot is now live](https://buildbot.python.org/all/#/builders/1380).
