### ISSUE TITLE
code.py not allowed, simplest possible setup

### ISSUE THREAD

**Issue by elexunix** [python/cpython#114028]
# Bug report

### Bug description:

I take the newest python3.12 image, and just do the following, without any external libs/soft at all:
```
$ sudo docker run -it --rm python:3.12 bash
root@0550613fcce3:/# echo 'raise kek' > code.py
root@0550613fcce3:/# python3 code.py 
Traceback (most recent call last):
  File "//code.py", line 1, in <module>
    raise kek
          ^^^
NameError: name 'kek' is not defined```

### CPython versions tested on:

3.9, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
That error is correct. What did you expect to happen?

**Comment by terryjreedy** [comment]
Please ask questions about possible bugs on https://discuss.python.org/c/users/7 or stackoverflow.com.

**Comment by elexunix** [comment]
I'm sorry for my previous message, it's indeed not what I wanted to show, I accidentally copied something else and didn't check for sanity
