### ISSUE TITLE
__slots__ as a dict is not documented in the data model docs.

### ISSUE THREAD

**Issue by ericvsmith** [python/cpython#114044]
Starting with 3.8, `__slots__` can be a `dict`, mapping slot names to docstrings. See https://docs.python.org/3/whatsnew/3.8.html#inspect

However, https://docs.python.org/3/reference/datamodel.html does not mention this, but it should.

This came up in issue #113878 for adding docstrings to slots in dataclasses.

**Comment by AlexWaygood** [comment]
It does. It's the fourth-from-last bullet point. I added docs for it in

- #30109

**Comment by AlexWaygood** [comment]
@rhettinger, I'm somewhat confused by your comment in https://github.com/python/cpython/issues/113878#issuecomment-1890771839, since you reviewed that PR :)

**Comment by ericvsmith** [comment]
Ah, good point @AlexWaygood. I clearly didn't read far enough, and it's true that a dict with str keys is an iterable of strings.
