### ISSUE TITLE
Doc build errors in CI due to updated sphinxcontrib-applehelp

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#114021]
# Bug report

### Bug description:

Sphinxcontrib-applehelp 1.0.8 no longer has a dependency on sphinx itself and gets installed when building documentation for 3.11 and 3.12.  This causes a build problem because version 1.0.4 was the latest version of this package that supports sphinx 4 as used in those branches.

See https://github.com/python/cpython/actions/runs/7511694613/job/20451568579?pr=114019 for a failed job in CI for a back port to 3.12.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-114022
* gh-114029
* gh-114038
* gh-114039
* gh-114040

**Comment by hugovk** [comment]
cc @AA-Turner

**Comment by ronaldoussoren** [comment]
The linked PR should pin sphinxcontrib-applehelp to a version that supports Spinx 4.5.
