### ISSUE TITLE
Got `Unable to find package 'pythonx86'` Error While Compiling Python on Windows 11

### ISSUE THREAD

**Issue by YTKme** [python/cpython#114073]
# Bug report

### Bug description:

Trying to compile Python `main` branch for Windows 11 and got error for `Unable to find package 'pythonx86'`

Step To Reproduce:
1. Clone Python source
2. Execute `PCbuild\build.bat -c Debug -p x64`

Full Error:
```
Using "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\amd64\MSBuild.exe"  (found in the PATH)
Installing Python via nuget...
Feeds used:

Installing package 'pythonx86' to 'C:\Users\Aries\Desktop\Project\Repository\P\cpython\externals'.
Unable to find package 'pythonx86'
Cannot locate python.exe on PATH or as PYTHON variable
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by amkarn258** [comment]
Not able to reproduce the issue, this build succeeded for me with the latest MSBuild tools installed.

Cpython version tested on: 3.12
Operating system: Windows 11

**Comment by terryjreedy** [comment]
I have used `PCbuild\build.bat -d` for years with no problem.  Does this give the same error?  I believe you need to install some python.exe first, because it says `Using py -3.11`.  I am puzzled that it is expecting pythonx86 in externals.

**Comment by zooba** [comment]
@YTKme Do you have a nuget config file somewhere that is removing `nuget.org` from its sources? If you don't actually have access to Nuget, then you won't be able to do this.

Specify the `HOST_PYTHON` environment variable to an existing Python install (3.10 or later) and it should skip it completely.

**Comment by YTKme** [comment]
> @YTKme Do you have a nuget config file somewhere that is removing `nuget.org` from its sources? If you don't actually have access to Nuget, then you won't be able to do this.
> 
> Specify the `HOST_PYTHON` environment variable to an existing Python install (3.10 or later) and it should skip it completely.

I do not believe so because I never did any config for nuget. I just installed VS 2022 and cloned the source and fresh compile.

**Comment by YTKme** [comment]
> I have used `PCbuild\build.bat -d` for years with no problem. Does this give the same error? I believe you need to install some python.exe first, because it says `Using py -3.11`. I am puzzled that it is expecting pythonx86 in externals.

It gave same error.

I am wondering why does it need `pythonx86` to just compile python?

**Comment by zooba** [comment]
I'd check for a Nuget configuration file. Your output should show a feed here:

```
Installing Python via nuget...
Feeds used:  <--- where are the feeds???

Installing package 'pythonx86' to 'C:\Users\Aries\Desktop\Project\Repository\P\cpython\externals'.
```

Or try installing a copy of Python 3.11 first.

> I am wondering why does it need `pythonx86` to just compile python?

Because some download steps and code generation steps involve a Python script. Technically they aren't necessary if you haven't modified any of the code, but we can't detect that, and nobody has written an option for Windows to skip that part of the build entirely. Also you'd have to download 3rd party dependencies manually and set up their paths, since you wouldn't have the script to do it for you.

If you really need to work around this requirement, I suggest starting with the `get_externals.bat` file and the `regen.targets` file in PCbuild. You'll have to hack the build system a bit.

(Or you can fix your Nuget, or install a copy of Python.)

**Comment by YTKme** [comment]
> I'd check for a Nuget configuration file. Your output should show a feed here:
> 
> ```
> Installing Python via nuget...
> Feeds used:  <--- where are the feeds???
> 
> Installing package 'pythonx86' to 'C:\Users\Aries\Desktop\Project\Repository\P\cpython\externals'.
> ```
> 
> Or try installing a copy of Python 3.11 first.
> 
> > I am wondering why does it need `pythonx86` to just compile python?
> 
> Because some download steps and code generation steps involve a Python script. Technically they aren't necessary if you haven't modified any of the code, but we can't detect that, and nobody has written an option for Windows to skip that part of the build entirely. Also you'd have to download 3rd party dependencies manually and set up their paths, since you wouldn't have the script to do it for you.
> 
> If you really need to work around this requirement, I suggest starting with the `get_externals.bat` file and the `regen.targets` file in PCbuild. You'll have to hack the build system a bit.
> 
> (Or you can fix your Nuget, or install a copy of Python.)

I checked the output `externals` directory, other externals like `bzip`, `libffi`, `openssl-bin`, etc. seem to have installed fine though?

I found a `nuget.config` under `%APPDATA%\Roaming\NuGet`, but seem to be blank

```
<?xml version="1.0"?>
<configuration>
  <packageSources>
  </packageSources>
</configuration>
```

**Comment by YTKme** [comment]
> > I found a `nuget.config` under `%APPDATA%\Roaming\NuGet`, but seem to be blank
> 
> That will be the problem.
> 
> > other externals like `bzip`, `libffi`, `openssl-bin`, etc. seem to have installed fine
> 
> Looks like we have a fallback on Git in case Python isn't available. That obviously doesn't help with the other scripts, so probably we could drop the fallback and fail earlier.

Is there a documentation on what should be the correct config for nuget? This is a fresh installed system, so nuget should be default config. Same with VS 2022, it is also fresh installed.

If there's a correct configuration, I can try updating and see as well

**Comment by zooba** [comment]
The docs are https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file

But since the file is nearly empty, I'd expect deleting it to fully restore the default settings. I'm not sure how it got emptied - is this your own personal system, or a work/IT-managed system?

**Comment by YTKme** [comment]
> is this your own personal system, or a work/IT-managed system?

is a personal system that's just freshly installed

**Comment by zooba** [comment]
No idea how the file got changed then. But deleting it and re-running should get you back to default settings no problem. (A work-managed system might have done it on purpose, which could make things harder...)

**Comment by YTKme** [comment]
i've added the following "default" [configuration](https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#package-source-sections), and it seem to work fine, closing this for now...

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <packageSources>
    <add key="nuget" value="https://api.nuget.org/v3/index.json" />
  </packageSources>
</configuration>
```
