### ISSUE TITLE
Rename dataclass's __replace__ argument from "obj" to "self"?

### ISSUE THREAD

**Issue by pschanely** [python/cpython#114198]
# Bug report

### Bug description:

The first argument of the new `__replace__` method on dataclasses is conspicuously named `obj` rather than `self`. While that's not a bug, it would be kinder on introspection tools to use `self`, since it is otherwise a regular instance method.

```python
>>> import dataclasses, inspect, pprint
>>> @dataclasses.dataclass
... class Foo:
...   x: int
... 
>>> pprint.pprint({n:inspect.signature(f) for n, f in inspect.getmembers(Foo, inspect.isfunction)})
{'__eq__': <Signature (self, other)>,
 '__init__': <Signature (self, x: int) -> None>,
 '__replace__': <Signature (obj, /, **changes)>,
 '__repr__': <Signature (self)>}
```

`__replace__` was added in #108752 

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-114251

**Comment by serhiy-storchaka** [comment]
It is a trivial change. You just need to rename a parameter of function `_replace()` in `dataclasses` module.

**Comment by pschanely** [comment]
> @pschanely : Do you want to make a PR?

Oh. Well, I haven't contributed to cpython before, but I'm willing to give it a try.

**Comment by ericvsmith** [comment]
@pschanely : Reach out if you need any help!
