### ISSUE TITLE
calendar.isleap() incorrect for year 2000

### ISSUE THREAD

**Issue by David-L-Duffy** [python/cpython#114167]
>>> calendar.isleap(2000)
True

Yes, years divisible by 400 are not leap years. Might sometimes cause problems calculating Julian from Gregorian.

**Comment by sweeneyde** [comment]
Years divisible by 100 are not leap years, except those divisible by 400, which are again leap years. This agrees with the implementation:

https://github.com/python/cpython/blob/8d26db45df479a54eccd2aced7d8a5ea9fd0ffa5/Lib/calendar.py#L141-L143

February 29, 2000 was a Tuesday.

**Comment by sweeneyde** [comment]
Addressed in the [calendar module docs](https://docs.python.org/3/library/calendar.html):

> The functions and classes defined in this module use an idealized calendar, the current Gregorian calendar extended indefinitely in both directions. This matches the definition of the “proleptic Gregorian” calendar in Dershowitz and Reingold’s book “Calendrical Calculations”, where it’s the base calendar for all computations. Zero and negative years are interpreted as prescribed by the ISO 8601 standard. Year 0 is 1 BC, year -1 is 2 BC, and so on.

**Comment by David-L-Duffy** [comment]
Oops. I'm still being confused by this, 24 years later ;)

Thank you for your prompt attention. Cheers David Duffy.

Sent with [Proton Mail](https://proton.me/) secure email.
