### ISSUE TITLE
importlib.metadata test fails on Windows if symlinks aren't allowed

### ISSUE THREAD

**Issue by encukou** [python/cpython#114107]
From the AMD64 Windows11 Refleaks 3.x buildbot:
```pytb
test_packages_distributions_symlinked_top_level (test.test_importlib.test_main.PackagesDistributionsTest.test_packages_distributions_symlinked_top_level)
Distribution is resolvable from a simple top-level symlink in RECORD. ... ERROR
======================================================================
ERROR: test_packages_distributions_symlinked_top_level (test.test_importlib.test_main.PackagesDistributionsTest.test_packages_distributions_symlinked_top_level)
Distribution is resolvable from a simple top-level symlink in RECORD.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "b:\uildarea\3.x.ware-win11.refleak\build\Lib\test\test_importlib\test_main.py", line 424, in test_packages_distributions_symlinked_top_level
    fixtures.build_files(files, self.site_dir)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "b:\uildarea\3.x.ware-win11.refleak\build\Lib\test\test_importlib\_path.py", line 70, in build
    create(contents, _ensure_tree_maker(prefix) / name)
    ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "b:\uildarea\3.x.ware-win11.refleak\build\Lib\functools.py", line 911, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
  File "b:\uildarea\3.x.ware-win11.refleak\build\Lib\test\test_importlib\_path.py", line 91, in _
    path.symlink_to(content)
    ~~~~~~~~~~~~~~~^^^^^^^^^
  File "b:\uildarea\3.x.ware-win11.refleak\build\Lib\pathlib\__init__.py", line 806, in symlink_to
    os.symlink(target, self, target_is_directory)
    ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: [WinError 1314] A required privilege is not held by the client: '.symlink.target' -> 'b:\\uildworker_temp\\test_python_sby1_qjd\\tmp16dtmklg\\symlinked'
```

The test needs to be skipped when symlinks are not supported.

### Linked PRs
* gh-114108
* gh-114121
* gh-114128
* gh-114129

**Comment by encukou** [comment]
This breaks a stable buildbot of a tier 1 platform. Per PEP-11, *buildbot failures a any breakage should be fixed or reverted immediately*.

I plan to skip the test with a `test.support` helper; later we can find a fix compatible with `importlib.resources` external repo.

**Comment by vstinner** [comment]
On https://github.com/python/buildmaster-config/issues/454 I asked how to know if the Windows Developer Mode is enabled or not. I wrote https://github.com/python/cpython/pull/114121 which reads a registry value to log the state in test.pythoninfo.

**Comment by itamaro** [comment]
Is this issue good to close now?

**Comment by encukou** [comment]
@jaraco, do you have any comments?
I know `importlib_resources` is maintained as a backport repo, but I don't know the details of the workflow. As it is, the fix might cause issues in `importlib_resources`.

**Comment by vstinner** [comment]
[Build 648 of AMD64 Windows11 Refleaks 3.x](https://buildbot.python.org/all/#/builders/920/builds/648) passed. test.pythoninfo:

```
support_os_helper.can_symlink: False
windows.is_admin: 0
```

Ah, the Windows developer mode was not logged after my change. Maybe the registry key does not always exist on Windows 10.

> Is this issue good to close now?

I let @encukou and @jaraco decide. At least, I can say that test_packages_distributions_symlinked_top_level() of Lib/test/test_importlib/test_main.py only exists in the main branch and was fixed.

**Comment by jaraco** [comment]
Sorry for the delay in review. I only just today managed to stumble on the notification.

I see I've already found the change in `importlib.metadata` tests and they've been ported to `importlib_metadata`, so it's all good.

Thanks both for your help on this matter.
