### ISSUE TITLE
No error in error

### ISSUE THREAD

**Issue by Utkarshbyte** [python/cpython#114141]
# Bug report

### Bug description:

```python
#idk if this is a bug or not but
a=[1,4,2]
a=a.sort()
print(a)

#this should give an error but it gives 'None'
```

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11

### Operating systems tested on:

Linux, Windows

**Comment by ronaldoussoren** [comment]
This is not a bug.  The `list.sort` method does an in place update of the list, and returns `None`. The latter is implied by not having a documented return value, all methods without an explicit return statement (or the equivalent in extension types like `list`) will return the value `None`.
