### ISSUE TITLE
Add return types to methods in documentation

### ISSUE THREAD

**Issue by ryan-duve** [python/cpython#114277]
# Documentation

It would be good to see the return types of methods listed in a structured way in the documentation, perhaps starting with a module like sqlite3.  This is an [extension of this discussion](https://discuss.python.org/t/explicit-parameter-list-in-function-documentation/16090), except instead of documenting function parameters we are documenting return types of functions.

### Linked PRs
* gh-114278

**Comment by terryjreedy** [comment]
Most of these additions seem redundant with the existing text.  None returns are implicit if there is not `Return ...`.  If they need to be made explicit, `=> None` on the signature line would be better to me.  Excessive vertical whitespace makes docs harder to read.

**Comment by erlend-aasland** [comment]
I think this should be discussed on Discourse before starting such a huge docs change. The discussion you linked to has been stale for a very long time. Please open a new topic and link to the previous topic.

**Comment by erlend-aasland** [comment]
In the mean time, I suggest closing this, including the linked PR.
