### ISSUE TITLE
dict update method with iterable list of multi-keys dicts gets scrambled

### ISSUE THREAD

**Issue by philippedistributive** [python/cpython#114208]
# Bug report

### Bug description:

car = {"brand": "Ford","model": "Mustang","year": 1964}
car.update([{'y': 3, 'x':67}, {'z': 0, 'f':89}])
car
{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'y': 'x', 'z': 'f'}

should be

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964, 'y': '3, 'x':67, 'z': 0, 'f': 89}

### CPython versions tested on:

3.12

**Comment by gaogaotiantian** [comment]
I don't believe this is the correct way to use `dict.update()`. In the [docs](https://docs.python.org/3/library/stdtypes.html#dict.update), it says:

> [update()](https://docs.python.org/3/library/stdtypes.html#dict.update) accepts either another dictionary object or an iterable of key/value pairs (as tuples or other iterables of length two). If keyword arguments are specified, the dictionary is then updated with those key/value pairs: d.update(red=1, blue=2).

You supplied a iterable(list) of a iterable(dict) of length two. So it will be parsed as a key/value pair.

This is not a bug. If you want such feature, it would be a feature request and we should view this from a feature request perspective.

**Comment by TeamSpen210** [comment]
This is correct behaviour. `dict.update()` does not expect to be given a list of dicts. Instead it expects either a single mapping, or an iterable of `(key, value)` pairs. It just so happens that your two dicts have two items in them, so they can be unpacked successfully producing their keys.
