### ISSUE TITLE
Fix indentation in enum.rst

### ISSUE THREAD

**Issue by miyashiiii** [python/cpython#114231]
# Documentation

There is an indentation error in enum.rst (the second line of the description for "SECOND").
```rst
   * ``FIRST = auto()`` will work (auto() is replaced with ``1``);
   * ``SECOND = auto(), -2`` will work (auto is replaced with ``2``, so ``2, -2`` is
      used to create the ``SECOND`` enum member;
   * ``THREE = [auto(), -3]`` will *not* work (``<auto instance>, -3`` is used to
     create the ``THREE`` enum member)
```
https://github.com/python/cpython/blob/v3.13.0a3/Doc/library/enum.rst?plain=1#L839-L843

In reStructuredText, the space after a line break within a list item should be two spaces.

```rst
* This is a bulleted list.
* It has two items, the second
  item uses two lines.
```
https://devguide.python.org/documentation/markup/#lists-and-quotes

### Linked PRs
* gh-114232
* gh-114234
* gh-114235

**Comment by hugovk** [comment]
For reference, it's here: https://docs.python.org/3/library/enum.html#utilities-and-decorators

Thanks for the report, would you like to open a PR to fix it?

**Comment by miyashiiii** [comment]
@hugovk 
Thank you for the prompt response. Yes, I am currently in the process of creating a PR.
