### ISSUE TITLE
The as_bytes method of an email message can fold headers improperly.

### ISSUE THREAD

**Issue by msapiro** [python/cpython#114362]
# Bug report

### Bug description:

This code
```python
import email
msg = email.message_from_bytes(b"""To: user@example.com
From: "Txxxxxx Mxxxxxxx de Vxxxxxx, Fxxxxxxxx" <fxxxxxxxx.txxxxxx@subd.example.net>

body
""")
```
creates a message object which when flattened as bytes erroneously folds the long From: header following the comma inside the quoted string.
```
msg.as_bytes()
b'To: user@example.com\nFrom: "Txxxxxx Mxxxxxxx de Vxxxxxx,\n Fxxxxxxxx" <fxxxxxxxx.txxxxxx@subd.example.net>\n\nbody\n'
```

### CPython versions tested on:

3.9, 3.11

### Operating systems tested on:

Linux

**Comment by hannovonbergen** [comment]
I took a look, this behaviour is caused in the Header.encode method in Lib/email/header.py. If desired I'd like to write a PR such that split chars outside of quotes are preferred when splitting the lines.

**Comment by RanKKI** [comment]
If I understand [RFC 5322 3.2.4](https://www.rfc-editor.org/rfc/rfc5322#section-3.2.4) correctly:

> Since a quoted-string is allowed to contain FWS, folding is permitted.

Therefore, I don't think it's a bug, as it should not exceed 78 characters.

**Comment by msapiro** [comment]
I agree that the current behavior is RFC 5322 compliant and I'm closing this.
