### ISSUE TITLE
Dictionary assignment is not parsed correctly when a block comment is inserted.

### ISSUE THREAD

**Issue by interlocuteur** [python/cpython#114325]
# Bug report

### Bug description:

```
parms = {
          'k1': 1,
          '''
          'k2': 2,
          '''
          'k3': 3,
          'k4': 4,
        }
print( parms['k1'])
print()
print( parms.keys())
print()
print( parms['k3'])

```
parms['k3'] will report a KeyError and should not.
The problem is that the triple-quote has a double role. It may contain a block string or a block comment. Since a dictionary assignment expect a string as key, the comment is interpreted as a key. A solution may be to give higher precedence to comments when parsing a dictionary assignment. 

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
That is not a block comment, it is a string. Strings are not valid in arbitrary places in the Python grammar. Instead, use real comments with `#`.
