### ISSUE TITLE
'—' changed to 'â€”' when read by TextIOWrapper.read() 

### ISSUE THREAD

**Issue by DrShaimaaAli** [python/cpython#114361]
# Bug report

### Bug description:

```
f = open(filename.txt)
text = f.read()
```

**Sample text in a file**
DeSylva and Kern tell us that a heart full of joy and gladness can banish trouble and strife — and now scientists tell us that optimism may help the heart itself.

**The corresponding text in the code**
DeSylva and Kern tell us that a heart full of joy and gladness can banish trouble and strife â€” and now scientists tell us that optimism may help the heart itself.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
I think this is an encoding issue that's not related to CPython directly. The default `open()` used a different encoding than your original file, so texts got changed (because `—` is not ascii). You need to know the encoding of your txt file and use that encoding to open the file.

**Comment by ericvsmith** [comment]
@gaogaotiantian is correct, this is an encoding issue, not a bug. The correct encoding needs to be passed to `open()`, since the default of 'utf-8' is incorrect for this file. Python has no way of guessing what the encoding is.

**Comment by DrShaimaaAli** [comment]
Thank you so much for the clarification.
The default encoding is not 'utf-8' then because when I sent it as the encoding it fixed the problem

```
f = open("optimism_and_health.txt", "r", encoding="utf-8")
text = f.read()
```
