### ISSUE TITLE
cPython x_mul little optimization

### ISSUE THREAD

**Issue by woongjoonchoi** [python/cpython#114370]
# Feature or enhancement

### Proposal:

https://github.com/python/cpython/blob/b04c5005cc9bd04052075077f7b33beca5edf43d/Objects/longobject.c#L3602-L3613

In line 3603, I think we need not to add pz .  we can modify code into `carry +=  *pb++ * f;`  
pz has no value in ob_digit , Until value is assigned to pz in line 3604.  

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-114371

**Comment by Eclips4** [comment]
Hello!
That's incorrect. ``pz`` gets his own value in line 3593: ``digit *pz = z->long_value.ob_digit + i;``, so it's not unnecessary addition in line 3603.
Also, you can see that CI/CD failing on your PR on some test cases related to numbers, that's another confirmation that ``carry += *pz + *pb++ * f;`` is right code :)

**Comment by woongjoonchoi** [comment]
Thank you for your comment.  
Thanks to you, I now know more.
