### ISSUE TITLE
Awkward wording in GH-111835 whatsnew entry

### ISSUE THREAD

**Issue by technillogue** [python/cpython#114364]
# Documentation

"it requires" is a little unclear

```diff
diff --git a/Doc/whatsnew/3.13.rst b/Doc/whatsnew/3.13.rst
index 40f0cd37fe..eb00e4ad74 100644
--- a/Doc/whatsnew/3.13.rst
+++ b/Doc/whatsnew/3.13.rst
@@ -259,8 +259,8 @@ mmap
 ----

 * The :class:`mmap.mmap` class now has an :meth:`~mmap.mmap.seekable` method
-  that can be used where it requires a file-like object with seekable and
-  the :meth:`~mmap.mmap.seek` method return the new absolute position.
+  that can be used when a file-like object with seekable is required. The
+  :meth:`~mmap.mmap.seek` method now returns the new absolute position.
   (Contributed by Donghee Na and Sylvie Liberman in :gh:`111835`.)
```

I'm not sure if I should make a PR changing Doc/whatsnew/3.13.rst directly or something via Misc/NEWS.d

This refers #111852 

### Linked PRs
* gh-114374

**Comment by ericvsmith** [comment]
Wouldn't "... when a seekable file-like object is required" sound better?

I'm not sure what file you should modify.

**Comment by terryjreedy** [comment]
The What's new should be edited.  If the 3.13.a?.rst file has the same or similar verbiage, edit it also.

**Comment by technillogue** [comment]
> Wouldn't "... when a seekable file-like object is required" sound better?

maybe  "when a file-like object with a :meth:`~seekable` method is required."? they always had `seek()`
