### ISSUE TITLE
Tkinter modal window is not restored after "show desktop" (win+d) is pressed.

### ISSUE THREAD

**Issue by wopozka** [python/cpython#114422]
# Bug report

### Bug description:

It looks that this is continuation of bug #70528, where the same behaviour was observed. The issue is closed, but it seems that the case hasn't been resolved.

Way to reproduce the bug.
Run any program in windows OS (might be web browser) and later below python script. The python script will open main app windows and modal dialog over it. Then press win+d to hide all programs and show desktop. Then press browser icon to maximize if from the taskbar and after that try to do the same with python program. The python program will not show up on desktop. The only way to see it, is to open task manager, find python there, find your program and double click. Using this method you can have your python program on desktop again. It was tested in windows 10 and 11, with python 3.9.3 and 3.12. In linux os everything works as expected.

Additionally it is worth mentioning that simpledialogs do behave correctly, but I haven't been able to figure out the reason looking into sourcecode.

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import tkinter

class dialog_win(tkinter.Toplevel):
    def __init__(self, parent, *args, **kwargs):
        self.parent = parent
        tkinter.Toplevel.__init__(self, parent, *args, **kwargs)
        body = tkinter.Frame(self)
        body.pack()
        button = tkinter.Button(body, text='Testcase')
        button.pack()
        self.transient(self.parent)
        self.focus_set()
        self.grab_set()
        
        
if __name__ == "__main__":
    app = tkinter.Tk(None)
    dial = dialog_win(app)
    app.mainloop()

```

### CPython versions tested on:

3.9, 3.12

### Operating systems tested on:

Windows

**Comment by wopozka** [comment]
@terryjreedy , what do you mean about I did it working? Regarding working properly custom modals, I did not find a solution. Default dialogs seemed to work, but I've checked ask yes/now only to be fair. Regarding task manager double click it is just working, not only in my computer. Some of my friends reported the same. I am really looking forward to find a solution for this problem, as is quite annoying.

**Comment by aivarannamaa** [comment]
I have used following work-around:

```python
class MyDialog(tk.Toplevel):
    def __init__(self, master=None):
        super().__init__(master=master)
        ...
        self.bind("<FocusIn>", self._unlock_on_focus_in, True)

    def _unlock_on_focus_in(self, event):
        if not self.winfo_ismapped():
            focussed_widget = self.focus_get()
            self.deiconify()
            if focussed_widget:
                focussed_widget.focus_set()
```

**Comment by wopozka** [comment]
@aivarannamaa I was trying to bind FocusIn, but my impression was that it is not called each time I am deiconifying the app and gave up. But it works as expected, thanks for help.

**Comment by terryjreedy** [comment]
@aivarannamaa Do you know whether workaround causes problems or is harmless on other systems?

**Comment by aivarannamaa** [comment]
@terryjreedy, in my app the workaround is not constrained for Windows and so far I haven't heard of it causing problems on other platforms.

**Comment by serhiy-storchaka** [comment]
I can reproduce the behavior in pure Tcl/Tk.
```tcl
toplevel .dialog
wm transient .dialog .
grab set .dialog
```
This is not Tkinter issue. I reported a bug on the Tk bugtracker: https://core.tcl-lang.org/tk/tktview/ed6c3a787d.
