### ISSUE TITLE
`datetime.fromisoformat` Raises ValueError for Valid RFC 3339 Timestamp Without Minute in Timezone Offset

### ISSUE THREAD

**Issue by DutchGerman** [python/cpython#114471]
# Bug report

### Bug description:

**Description**:
The `datetime.fromisoformat` method in Python raises a `ValueError` when parsing a valid RFC 3339 timestamp string that omits the minutes portion in the timezone offset. According to RFC 3339, the minute part of the timezone offset is optional (`time-numoffset = ("+" / "-") time-hour [[":"] time-minute]`). However, `fromisoformat` only seems to accept the timezone offset with the minute part included.

**Steps to Reproduce**:
1. Execute the following Python code:
   ```python
   from datetime import datetime
   datetime.fromisoformat('2023-01-09T12:00:00+00')
   ```
2. Observe the `ValueError`.

**Expected Behavior**:
The `datetime.fromisoformat` method should correctly parse the timestamp `2023-01-09T12:00:00+00`, recognizing it as a valid RFC 3339 timestamp with an optional minute part in the timezone offset.

**Actual Behavior**:
The method raises a `ValueError` with the message: "Invalid isoformat string: '2023-01-09T12:00:00+00'".

**Environment**:
- Python Version: 3.11
- Operating System: Linux, Alpine 3.19.0

**Additional Information**:
- RFC 3339 Specification: https://datatracker.ietf.org/doc/html/rfc3339#appendix-A

```
   Time:

   time-hour         = 2DIGIT ; 00-24
   time-minute       = 2DIGIT ; 00-59
   time-second       = 2DIGIT ; 00-58, 00-59, 00-60 based on
                              ; leap-second rules
   time-fraction     = ("," / ".") 1*DIGIT
   time-numoffset    = ("+" / "-") time-hour [[":"] time-minute]
   time-zone         = "Z" / time-numoffset
```

This issue impacts any application relying on `datetime.fromisoformat` to parse RFC 3339 compliant timestamps that may omit the minutes in the timezone offset, for example PostgreSQL.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by sunmy2019** [comment]
Cannot reproduce on Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
```py
>>> from datetime import datetime
>>> datetime.fromisoformat('2023-01-09T12:00:00+00')
datetime.datetime(2023, 1, 9, 12, 0, tzinfo=datetime.timezone.utc)
>>>
```

**Comment by sunmy2019** [comment]
Also cannot repro on Python 3.11.5 (main, Sep 11 2023, 13:54:46) [GCC 11.2.0] on linux

```py
>>> from datetime import datetime
>>> datetime.fromisoformat('2023-01-09T12:00:00+00')
datetime.datetime(2023, 1, 9, 12, 0, tzinfo=datetime.timezone.utc)
>>>
```

**Comment by DutchGerman** [comment]
Sorry for the bloat, I just realized we made a mistake in our testing we used `from datetime import date` insted of `datetime`. 

Thanks for the quick response!
