### ISSUE TITLE
logging docstrings should use bool instead of int for exc_info

### ISSUE THREAD

**Issue by CharString** [python/cpython#114494]
The documentation passes an integer as the `exc_info` parameter:

https://github.com/python/cpython/blob/8edc8029def8040ebe1caf75d815439156dd2124/Lib/logging/__init__.py#L1496

But the annotation doesn't allow that.

https://github.com/python/typeshed/blob/2168ab5ff4e40c37505b3e5048944603b71a857d/stdlib/logging/__init__.pyi#L66-L67

### Linked PRs
* gh-114558
* gh-114624
* gh-116242

**Comment by soufrabi** [comment]
Assign me

**Comment by soufrabi** [comment]
There are 6 lines in the file that needs to be changed. Each for different level of logging.
