### ISSUE TITLE
`_threadmodule` does not check for `NULL` after `PyType_GetModuleByDef` calls

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#114414]
# Bug report

`PyType_GetModuleByDef` can return `NULL`: https://github.com/python/cpython/blob/fd49e226700e2483a452c3c92da6f15d822ae054/Objects/typeobject.c#L4640-L4645

I think that right now this is a hypothetical issue, because in practice `NULL` will never be returned for these samples. But, all other similar places do check for `NULL`. I guess that adding a check won't hurt. And in the future, if something changes - we would be safe.

Samples: 

https://github.com/python/cpython/blob/fd49e226700e2483a452c3c92da6f15d822ae054/Modules/_threadmodule.c#L903-L904

https://github.com/python/cpython/blob/fd49e226700e2483a452c3c92da6f15d822ae054/Modules/_threadmodule.c#L1044-L1045

https://github.com/python/cpython/blob/fd49e226700e2483a452c3c92da6f15d822ae054/Modules/_threadmodule.c#L1096-L1097

### Linked PRs
* gh-114415

**Comment by erlend-aasland** [comment]
For similar cases (retrieve module state in an extension module), we normally use `assert`.
