### ISSUE TITLE
argparse: make whether or not an option is required dependent on the value of another option

### ISSUE THREAD

**Issue by mulkieran** [python/cpython#114411]
# Feature or enhancement

### Proposal:

Suppose we have one option, ```--do```, and it is restricted to a set of choices, e.g., ```job1```, ```job2```.

Suppose we have another option, ```--how```, and it is only meaningful if ```--do=job1``` is selected.

It would be nice if the ```required``` entry for the ```--how``` option, instead of just receiving the values ```True``` or ```False``` would permit some way of indicating "if ```--how``` is ```job1```".

If the ```--do``` option were a required positional argument, then it would be fairly easy to handle it via a subcommand. But if it is, itself, optional, then that would not work.

This would be even nicer if it would be possible to make a group required or not required depending on the value of some other option and would work very well with the proposed mutually inclusive groups: https://github.com/python/cpython/issues/55797 enhancement.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by gaogaotiantian** [comment]
My personal opinion on this is, it seems like you should check this dynamically (using your code).

Let's ignore the implementation of it, how would you describe such relation?

```python
parser.add_argument("--how", required="do == 'job1'")
```

Something like this?

I can't think of a way to easily describe it, without inventing a new "grammar" to cover it. Maybe send it as a tuple?

```python
parser.add_argument("--how", required=("do", "job1"))
```

Reusing the `required` argument and allow it to be something more than a boolean sounds like a bad idea to me. Maybe a new argument like `required_if`? All the imaginations converge to a small piece of Python code like

```python
if args.do == "job1" and not args.how:
    raise Exception()
```

Personally, I don't think the benefit is worth the cost. `argparse` is already a very giant mess with a lot of dark corners.

**Comment by terryjreedy** [comment]
Would `required=func`, where `func` is a callable that returns a bool, work?

**Comment by mulkieran** [comment]
> Would `required=func`, where `func` is a callable that returns a bool, work?

I think it would generally not, unless you also enforced an ordering on the arguments. But if you did that, then it would.

What I'm actually looking for is the formal constraint, making the requiredness dependent on the value of some other option and having it solved in a general way by argparse. So, ```required=func``` solution is actually more general than I would like, but also has this ordering constraint.

**Comment by gaogaotiantian** [comment]
Do you have anything in mind of the actual function prototype? Imagine you have a perfect argparse, what kind of function call do you think is proper for the request you made?

**Comment by gaogaotiantian** [comment]
> Would `required=func`, where `func` is a callable that returns a bool, work?

I don't think this is helpful in any case without the proper argument. This func requires a parsed option, which creates a logic loop that may or may not be solved.

**Comment by hpaulj** [comment]
What if the user did `parser.parse_args('--how xxx --do=job1'.split()`.?  

`argparse` is designed to process `optionals` in any order.  That makes enforcing connections between `Actions` complicated.  It can be done with custom `Action` subclasses, but usually it's easier to implement such connections after parsing, when the `args` Namespace has the whole picture.

I might add that the `required` test is run near the end of parsing, when it runs through the list of `_actions` and checks if all with the `required` attribute appear in a list of `seen_actions`.  While  `parser._actions` is still available after parsing, the `seen_actions` list is not (it's a local variable).  But testing for the default `default`, `None` still works.

**Comment by mulkieran** [comment]
I think it may be that argparse has really reached its limit and it won't be possible to specify this well. Thanks for the hints. I'm going with something like https://github.com/stratis-storage/stratis-cli/pull/1073 which attaches a purpose built class to a hidden option and then extracts it from the namespace in order to do the more rigorous parsing I need. I think it will work ok.
