### ISSUE TITLE
Vulnerability in Python 3.10 (setuptools inside ensurepip folder)

### ISSUE THREAD

**Issue by bhupendra-vaishnav** [python/cpython#114446]
# Bug report

### Bug description:

We are working on Python 3.10 and found vulnerable version of setuptools package which is setuptools-65.5.0.

We did see Python 3.10 already has a fix for setuptools package and updated version of setuptools package which is setuptools-65.5.1. Though while doing analysis, we found the traces of vulnerable version inside `ensurepip` folder. We appreciate the update for `ensurepip` bundle to resolve the issue related to leftover file in `ensurepip` bundle (highlighted in below image).

Please refer absolute file paths highlighted by blue in attached screenshot :

<img width="783" alt="298218820-921dfd8f-71ac-453b-b58f-2cb474b90c28" src="https://github.com/python/cpython/assets/148317470/124adebf-0c20-4c72-9dcd-3edad23d73a0">

Vulnerability reference : https://github.com/advisories/GHSA-r9hx-vwmv-q579

CC: @samruddhikhandale, @eljog, @gauravsaini04

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by samruddhikhandale** [comment]
We opened a similar issue with https://github.com/docker-library/python/issues/901, but turns out the vulnerability comes from  Python's own stdlib.

We would appreciate a fix as this is a [high severity vulnerability](https://github.com/advisories/GHSA-r9hx-vwmv-q579), thank you!
