### ISSUE TITLE
Shebang of "/usr/bin/env/python3" prevents launcher from executing script on a fresh Windows 10 install

### ISSUE THREAD

**Issue by BookWorm0** [python/cpython#114412]
# Bug report

### Bug description:

hello.py:
```python
#!/usr/bin/env python3

print('Hello') # never runs
```

hello_noshb.py:
```python
print('Hello (no shebang)')
```
Here is a screenshot of the silent failure.
![Command](https://github.com/python/cpython/assets/46274368/87a5762f-60c4-47c9-ae91-5822370d1759)

Cause: python3.exe is a 0-byte stub file in %USERPROFILE%\AppData\Local\Microsoft\WindowsApps\, which is in PATH.  The PSF installer creates python.exe, but not python3.exe. (When python3 is typed directly into command prompt, this stub causes Store to be launched. It offers to install a Store App version of an obsolete release of python.)

Workaround: Delete the 0-byte stub so that py.exe doesn’t invoke it. 

Proposed long-term fix: For a script with a "/usr/bin/env" shebang, py.exe should check size of program found in path and act as if a 0 byte .exe doesn’t exist.

Alternate fix: Installer could create a python3.exe in the installation directory.

Screenshot of Store offering:
![ObsoleteStorePython](https://github.com/python/cpython/assets/46274368/d40e62b6-25a8-49bb-bc15-9917d17d45d0)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
This is known  ##100107 Currently, one should leave off or remove `/env` to avoid the path search that finds the stub.

**Comment by zooba** [comment]
@BookWorm0 Did you really get sent to Python 3.7 by the stub? Or did you just search that for the screenshot.

It should be taking you to 3.12 regardless of version of Windows.

**Comment by BookWorm0** [comment]
> This is known ##100107 Currently, one should leave off or remove `/env` to avoid the path search that finds the stub.

Unfortunately, macOS has an almost obsolete version of python in /usr/bin/python3, so the shebang line with /usr/bin/env is necessary for cross-platform scripts:
```
bookworm@bookworm-mbp ~ % /usr/bin/python3 -V
Python 3.9.6
bookworm@bookworm-mbp ~ % type python3
python3 is /opt/homebrew/bin/python3
```
(homebrew installs python3 on macOS.)
