### ISSUE TITLE
Context managers differ in __exit__ behaviour when implemented as classes or using contextlib.contextmanager

### ISSUE THREAD

**Issue by Sirtea** [python/cpython#114475]
# Bug report

### Bug description:

Implementing a contextmanager I discovered that the version using contextlib.contextmanager does not the "post-with" code in the event of an exception.

In the below example, the context manager implemented by a class (Lock) crashes, and __exit__() is called; that is the expected behaviour. If we implement the same contextmanager using contextlib.contextmanager (Lock2) the "post-with" code (what's below the yield keyword) never gets called on the event of an exception.

```python
from contextlib import contextmanager

class Lock:
    def __init__(self):
        pass

    def __enter__(self):
        print('enter')
        return self

    def __exit__(self, exc_type, exc_value, traceback):
        print('exit')


@contextmanager
def Lock2():
    print('enter')
    yield
    print('exit')


with Lock() as lock:
#with Lock2() as lock:
    print(1234)
    raise Exception('boom')
    print(5678)
```

### CPython versions tested on:

3.8, 3.11

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
Yes, because `print('exit')` is never executed if `yield` raises an exception. You should use try/finally block, as in all cases when you want to guarantee execution of the cleanup code. This is a bug in your code, not in CPython
```python
@contextmanager
def Lock2():
    print('enter')
    try:
        yield
    finally:
        print('exit')
```
