### ISSUE TITLE
Space between "return" and string.

### ISSUE THREAD

**Issue by chhongzh** [python/cpython#114416]
# Feature or enhancement

### Proposal:

When a function in Python returns a string, the string can be directly connected after "return". The following is an error example:

```python
def foo():
    return"Foo"
```

This way of writing is extremely irregular, but it can still be interpreted and run normally.

Perhaps this way of writing should be standardized and a grammatical error message should be added to it.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by AlexWaygood** [comment]
This would be a breaking change, that could mean that existing Python code would stop working. You'd need to put forward a strong case for why the change should be made. I think it would be best to first discuss this idea at https://discuss.python.org/. If there is strong community support for your idea there, we can reopen this issue.

**Comment by chhongzh** [comment]
Thanks, I will go back to discuss.

**Comment by sobolevn** [comment]
Please, make sure to specify why this could not be solved with a linter like `flake8` or `ruff`.
