### ISSUE TITLE
Do not allocate non-PyObjects with PyObject_Malloc()

### ISSUE THREAD

**Issue by colesbury** [python/cpython#114569]
# Feature or enhancement

The free-threaded build requires that Python objects -- and only Python objects -- be allocated through the Python object allocation APIs (like `PyObject_Malloc()` or `PyType_GenericNew()`) [^1]. 

There are a few places internally [^2] that use `PyObject_Malloc()` for non Python objects. We should switch those call sites to use `PyMem_Malloc()/Free()` instead.

Note that there is not a significant difference between using `PyObject_Malloc()` and `PyMem_Malloc()` in the default build. Both calls use obmalloc under the hood, so switching from one to the other should not matter for the default build.

<details>
<summary>Here are some examples, but this list may not be exhaustive:</summary>

https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Modules/_sre/sre_lib.h#L1125
https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Modules/_elementtree.c#L270
https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Modules/_elementtree.c#L498-L499
https://github.com/python/cpython/blob/main/Modules/mathmodule.c#L2573
https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Modules/pyexpat.c#L23-L24
https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Objects/bytearrayobject.c#L135
https://github.com/python/cpython/blob/841eacd07646e643f87d7f063106633a25315910/Parser/lexer/lexer.c#L132
</details>

[^1]: See https://peps.python.org/pep-0703/#backwards-compatibility:~:text=Non%2DPython%20objects%20must%20not%20be%20allocated%20through%20those%20APIs

[^2]: @DinoV fixed the use in `dictobject.c` in https://github.com/python/cpython/pull/114543

### Linked PRs
* gh-114574
* gh-114587
* gh-114690

**Comment by erlend-aasland** [comment]
There are some strange usage in unicodeobject.c as well; I did not look closely at it yet. Perhaps it is ok, perhaps not.

**Comment by colesbury** [comment]
Yeah, it looks like a two of those should use `PyMem` as well, but not the `struct encoding_map` one -- that's a Python object.

https://github.com/python/cpython/blob/30b7b4f73cd876732244de06d079a2caf2a7b95c/Objects/unicodeobject.c#L5206
https://github.com/python/cpython/blob/30b7b4f73cd876732244de06d079a2caf2a7b95c/Objects/unicodeobject.c#L14677

**Comment by erlend-aasland** [comment]
Did we catch all of them?

**Comment by colesbury** [comment]
Yeah, looks like it!
