### ISSUE TITLE
Rename `pathlib.PurePath.pathmod`

### ISSUE THREAD

**Issue by barneygale** [python/cpython#114575]
# Feature or enhancement

In #100502 we added a `pathmod` attribute that points to either `posixpath` or `ntpath`, and supplies low-level lexical manipulation functions used by `PurePath`.

The name "pathmod" implies the value is a module, and while that's true in `PurePath` and its subclasses, it's not necessarily true in `_abc.PurePathBase` and its subclasses. In fact, user subclasses of `PurePathBase` and `PathBase` are more likely to implement pathmod using a class, and not a module.

The ABCs are currently private, but they may be made public in future, and so I think it's worth improving the name _now_ to reduce probable future churn/grief.

Downstream issue: https://github.com/barneygale/pathlib-abc/issues/19

### Linked PRs
* gh-116513

**Comment by barneygale** [comment]
I'm currently planning to change the name to "flavour", but I'll leave this issue open for a month or so before opening a PR, in case anyone would like to object or make the case for another name.

**Comment by edgarrmondragon** [comment]
Probably not important, but could the fact that `flavour` has the alternative spelling `flavor` in "American" English be an point of contention?

**Comment by barneygale** [comment]
I've opened a PR that uses "flavour". If we're concerned about the "flavour" vs "flavor" spelling I can drop the "u" (under protest! :P), or we can find a word that isn't subject to spelling differences.

**Comment by barneygale** [comment]
My favourite alternative is "parser" - how do folks feel about that? The functionality is similar, I guess, to `urllib.parse`.

**Comment by edgarrmondragon** [comment]
I like "parser" 👍
