### ISSUE TITLE
Lib: colorsys code optimization

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#114577]
# colorsys code optimization
This is my first issue and submitting PR to Python.\
If I have any questions, please let me know. Thank you.

Lib/colorsys.py\
I made the following changes: 
## Simple Code

These modifications simplify the code logic, making it clearer. Additionally, they preserve the original functionality.

Original Code:
```python
if r < 0.0:
    r = 0.0
if g < 0.0:
    g = 0.0
if b < 0.0:
    b = 0.0
if r > 1.0:
    r = 1.0
if g > 1.0:
    g = 1.0
if b > 1.0:
    b = 1.0
return (r, g, b)
```
Modified Code:
```python
r = max(0.0, min(r, 1.0))
g = max(0.0, min(g, 1.0))
b = max(0.0, min(b, 1.0))
return r, g, b
```

## Using elif
I changed `if` to `elif` statements. Here, `hue` can only satisfy one condition at a time. Using elif can skip other if checks after a condition is met, which can improve the efficiency of the code.

Original Code:
```python
def _v(m1, m2, hue):
    hue = hue % 1.0
    if hue < ONE_SIXTH:
        return m1 + (m2-m1)*hue*6.0
    if hue < 0.5:
        return m2
    if hue < TWO_THIRD:
        return m1 + (m2-m1)*(TWO_THIRD-hue)*6.0
    return m1
```

Modified Code:
```python
def _v(m1, m2, hue):
    hue %= 1.0
    if hue < ONE_SIXTH:
        return m1 + (m2 - m1) * hue * 6.0
    elif hue < 0.5:
        return m2
    elif hue < TWO_THIRD:
        return m1 + (m2 - m1) * (TWO_THIRD - hue) * 6.0
    else:
        return m1
```

## Improve performance
The original code uses a series of **if** to determine the returned RGB values. But `i` can only satisfy one condition at a time.\
This requires checking each possible value of `i`. 

Original Code:
```python
def hsv_to_rgb(h, s, v):
    if s == 0.0:
        return v, v, v
    i = int(h*6.0) # XXX assume int() truncates!
    f = (h*6.0) - i
    p = v*(1.0 - s)
    q = v*(1.0 - s*f)
    t = v*(1.0 - s*(1.0-f))
    i = i%6
    if i == 0:
        return v, t, p
    if i == 1:
        return q, v, p
    if i == 2:
        return p, v, t
    if i == 3:
        return p, q, v
    if i == 4:
        return t, p, v
    if i == 5:
        return v, p, q
```
I changed `if` to `elif` statements. Here, `i` can only satisfy one condition at a time. Using elif can skip other if checks after a condition is met, which can improve the efficiency of the code.

Modified Code:
```python
def hsv_to_rgb(h, s, v):
    if s == 0.0:
        return v, v, v
    i = int(h*6.0) # XXX assume int() truncates!
    f = (h*6.0) - i
    p = v*(1.0 - s)
    q = v*(1.0 - s*f)
    t = v*(1.0 - s*(1.0-f))
    i = i%6
    if i == 0:
        return v, t, p
    elif i == 1:
        return q, v, p
    elif i == 2:
        return p, v, t
    elif i == 3:
        return p, q, v
    elif i == 4:
        return t, p, v
    elif i == 5:
        return v, p, q
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-114578

**Comment by hugovk** [comment]
Thanks for the issue and PR.

Did you benchmark these changes? If so, please can you share the script/command you used, and improvement from the changes?

**Comment by hugovk** [comment]
See https://github.com/python/cpython/pull/114578#issuecomment-1911609139 for some benchmarking.

**Comment by serhiy-storchaka** [comment]
It is difficult to believe that `elif` after `return` has any effect. Do you have some benchmarks?

The clipping code is likely predates introduction of `min()` and `max()`, but it can be also a microoptimization -- function calls add an overhead. Do you have some benchmarks?
