### ISSUE TITLE
Must `object.__dir__` return a sequence of `str`, or is any iterable OK?

### ISSUE THREAD

**Issue by ktbarrett** [python/cpython#114552]
According to the documentation [`__dir__` must return a `Sequence`](https://docs.python.org/3/reference/datamodel.html#object.__dir__), but e.g. typeshed's annotations currently imply that any iterable will do:

```py
class object:
    def __dir__(self) -> Iterable[str]: ...
```

https://github.com/python/typeshed/blob/26452a7c68c6ad512be00b553f7a03f869f64be9/stdlib/builtins.pyi#L125

### Linked PRs
* gh-114662
* gh-115234
* gh-115235

**Comment by sobolevn** [comment]
My 2c:
- `PySequence_List` already says: `Return a list object with the same contents as the sequence or iterable *o*`, which I guess is fine
- I've updated `__dir__` docs to mention `iterable` instead of `sequence`, because it is how runtime behaves (correctly)
