### ISSUE TITLE
Regex performance improvement.

### ISSUE THREAD

**Issue by amir-h-rassafi** [python/cpython#114586]
# Feature or enhancement

### Proposal:

I had a test that I put my script in following.
```python
import re
import time


rng = 1000000

# COMPILING IT BEFORE HAND
start = time.time()
pre_comp_pat = re.compile(r'[a-zA-Z]+')
for _ in range(rng):
    pre_comp_pat.match("gaz")
end = time.time()
print("Time (pre-compiled) ", end - start)

# COMPILING IT INSIDE THE FOR LOOP
start = time.time()
for _ in range(rng):
    pat = re.compile(r'[a-zA-Z]+')
    pat.match("gaz")
end = time.time()
print("Time (compiling each it)", end - start)

# NEVER EXPLICITLY COMPILING IT
non_comp_pat = r'[a-zA-Z]+'
start = time.time()
for _ in range(rng):
    re.match(non_comp_pat, "gaz")
end = time.time()
print("Time (not compiling)", end - start)
```
and the result is:
```
Time (pre-compiled)  0.19112229347229004
Time (compiling each it) 0.5717971324920654
Time (not compiling) 0.5644176006317139
```
I jumped to implementation https://github.com/python/cpython/blob/456e274578dc9863f42ab24d62adc0d8c511b50f/Lib/re/__init__.py#L339-L341 and then I find out there is cache on this then the result is really unexpected(as it slower 3 times!).

### Has this already been discussed elsewhere?

No response given

**Comment by serhiy-storchaka** [comment]
What is your proposal?

**Comment by gaogaotiantian** [comment]
It's not that unexpected.

`re.compile` itself has a cost that is non-zero, even with the cache mechanism. Your string to match + matching patter is too simple so the cost of `re.compile` with cache is comparable to `re.match`. Cache does not bring overhead to zero.

In fact, without the cache, your code would be about 100x slower, and cache brought it to 3x.

I don't see any issue to fix here.
