### ISSUE TITLE
ssl: Fix locking in cert_store_stats and get_ca_certs

### ISSUE THREAD

**Issue by davidben** [python/cpython#114572]
# Bug report

### Bug description:

Filing this to attach a PR to.

cert_store_stats and get_ca_certs query the SSLContext's X509_STORE with X509_STORE_get0_objects, but reading the result requires a lock. See https://github.com/openssl/openssl/pull/23224 for details.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-114573
* gh-115547
* gh-115548
* gh-115549
* gh-118109
* gh-118442

**Comment by hugovk** [comment]
Closing as the PR has been merged and backported. Thanks!
