### ISSUE TITLE
Where is asciilib_find_slice?? 

### ISSUE THREAD

**Issue by woongjoonchoi** [python/cpython#114523]
https://github.com/python/cpython/blob/1e4f00ebd8db44a031b61eed0803b4c3d731aed7/Objects/unicodeobject.c#L8959-L8994

I want to know internal implementation of "asciilib_find_slice" , "ucs1lib_find_slice", ... In other words " *_find_slice " .

But ,  i cannot find where it is in this repo.

Can you tell me where it is?

**Comment by Eclips4** [comment]
Hello!
It's placed here:
https://github.com/python/cpython/blob/1e4f00ebd8db44a031b61eed0803b4c3d731aed7/Objects/stringlib/find.h#L45-L51
Acessing this function via ``asciilib`` / ``ucs1lib`` is achieved by *some magic* of C-macrosses.

Also, this repository is intended as CPython bug tracker. For the next time, if you have some question about CPython internals, ask about it here: https://discuss.python.org/c/users/7

**Comment by woongjoonchoi** [comment]
I was wondering where to ask the question, but thanks to you, I found out.
