### ISSUE TITLE
Incorrect deprecation warning for 'N' specifier

### ISSUE THREAD

**Issue by skrah** [python/cpython#114678]
# Bug report

### Bug description:

In the main branch, the following warning is issued whenever a fill character (possibly utf-8) either is 'N' or contains 'N':

```
>>> from _decimal import *
>>> Decimal("0").__format__("N<g")
<stdin>-2:1: DeprecationWarning: Format specifier 'N' is deprecated
  Decimal("0").__format__("N<g")
'0'
```

Fix (after applying the patches from #114563):

https://www.bytereef.org/contrib/0003-main-fix-deprecation-warning.patch

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-114683

**Comment by serhiy-storchaka** [comment]
Thank you @skrah. I commited changes based on your patch.
