### ISSUE TITLE
Add IndexError to tutorial datastructures list.pop doc

### ISSUE THREAD

**Issue by ShivnarenSrinivasan** [python/cpython#114648]
Documentation

In the [Datastructures](https://github.com/python/cpython/blob/main/Doc/tutorial/datastructures.rst?plain=1#L47-L54) tutorial, the `remove` and `index` methods mention that an `IndexError` may be raised. 
The tutorial is not intended to be an extensive reference, but I feel it is better to state the potential exception.

We could add the boldfaced text to the paragraph: 
> > `list.pop([i])`
Remove the item at the given position in the list, and return it. If no index is specified, a.pop() removes and returns the last item in the list. **It raises an IndexError if the list if the list is empty or the index is outside the list range.** (The square brackets around the i in the method signature denote that the parameter is optional, not that you should type square brackets at that position. You will see this notation frequently in the Python Library Reference.)

Thoughts?

### Linked PRs
* gh-114681
* gh-114841
* gh-114842

**Comment by serhiy-storchaka** [comment]
Looks reasonable. Do you mind to create a PR?

**Comment by ShivnarenSrinivasan** [comment]
Will do

take

**Comment by ShivnarenSrinivasan** [comment]
take

**Comment by terryjreedy** [comment]
Thank you for the report and PR.  This exception is part of list.pop's API.
