### ISSUE TITLE
unittest assertRaisesRegex does not check all expected argument names

### ISSUE THREAD

**Issue by RogerMarsh** [python/cpython#114675]
# Bug report

### Bug description:

```python
# Add a code block here, if required
import unittest

class C:
    def method(self, a, b):
        """Do nothing."""

class TestC(unittest.TestCase):
    def setUp(self):
        self.c = C()
    def test_method_1(self):
        self.assertRaisesRegex(
            TypeError,
            "".join(
                (
                    r"method\(\) missing 2 ",
                    "required positional arguments: 'a'",
                )
            ),
            self.c.method,
        )
    def test_method_2(self):
        self.assertRaisesRegex(
            TypeError,
            "".join(
                (
                    r"method\(\) missing 2 ",
                    "required positional argument: 'a'",
                )
            ),
            self.c.method,
        )
    def test_method_3(self):
        self.assertRaisesRegex(
            TypeError,
            "".join(
                (
                    r"method\(\) missing 2 ",
                    "required positional arguments: 'a' and 'b'",
                )
            ),
            self.c.method,
        )


if __name__ == "__main__":
    runner = unittest.TextTestRunner
    loader = unittest.defaultTestLoader.loadTestsFromTestCase
    runner().run(loader(TestC))
```

test_method_1 does not give a report similar to the one given for test_method_2  (the difference is the spelling of 'arguments').

test_method_3 gives the expected ok response.

Script attached (it repeats the code above first).

[try_unittest.txt](https://github.com/python/cpython/files/14075843/try_unittest.txt)

Did search on 'unittest assertraisesregex' but found nothing likely similar.

### CPython versions tested on:

3.11

### Operating systems tested on:

Other

**Comment by Eclips4** [comment]
Hello!
There's no bug.
Regular expression `r"method\(\) missing 2 required positional argument: 'a'"` doesn't match string `"C.method() missing 2 required positional arguments: 'a' and 'b'`. As you said, that's because of plural form of word `argument`.
So all of three tests works as expected. You need to write more *generic* regular expression to catch this situation.
