### ISSUE TITLE
isintance(boolean,int) is True

### ISSUE THREAD

**Issue by lLittleSUNl** [python/cpython#114693]
# Bug report

### Bug description:

```
print(isinstance(True,bool))
print(isinstance(True,int))
```
Accroding to the title.
Both of results are 'True'. It's a bug,isn't it?

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
There's no bug, because ``bool`` inherits from ``int``.
For more information: https://docs.python.org/3/library/stdtypes.html#boolean-type-bool
