### ISSUE TITLE
bug in count method

### ISSUE THREAD

**Issue by TealcSG1** [python/cpython#114699]
# Bug report

### Bug description:

'01010'.count('010') returns 1 , not 2

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment]
This is not a bug. In the [documentation](https://docs.python.org/3/library/stdtypes.html#str.count) for this method, it states:

> Return the number of non-overlapping occurrences of substring _sub_ in the range [_start_, _end_].

While there are 2 occurrences of the substring '010' in the string '01010', the 2 occurrences overlap. There is only one _non-overlapping_ occurrence of the substring '010' in the string '01010'.

**Comment by TealcSG1** [comment]
Thank you for your polite answer.
I'm sorry I didn't read the documentation.
