### ISSUE TITLE
Anaconda i386 distribution is not working with MS SQL Server database

### ISSUE THREAD

**Issue by amarjeeth123** [python/cpython#114676]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
Anaconda i386 distribution is a version of Linux distro.It is not working with Microsoft SQL Server.Please investigate this issue.

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
This is the tracker for CPython, not Anaconda.

Please report problems with Anaconda distributions to the Anaconda project.

(Problems with installers from https://www.python.org/downloads/ would be valid here.)
