### ISSUE TITLE
Expose unprefixed variants of `_PyCFunctionFast` and `_PyCFunctionFastWithKeywords`

### ISSUE THREAD

**Issue by davidhewitt** [python/cpython#114626]
`METH_FASTCALL` is documented as part of the stable API since Python 3.10.

The accompanying function pointer typedefs `_PyCFunctionFast` and `_PyCFunctionFastWithKeywords` have leading underscore names, which I understand to hint at these being private / internal APIs.

I think this is potentially an oversight and these function pointer typedefs should have new public names `PyCFunctionFast` and `PyCFunctionFastWithKeywords`?

### Linked PRs
* gh-114627
* gh-115561

**Comment by vstinner** [comment]
Thanks for making these two names public @davidhewitt!
