### ISSUE TITLE
GIL section of the FAQ is outdated (or shortly to be outdated)

### ISSUE THREAD

**Issue by da-woods** [python/cpython#114756]
# Documentation

https://docs.python.org/3.13/faq/library.html#can-t-we-get-rid-of-the-global-interpreter-lock (link is to the current alpha version)

Obviously work is in progress to remove the GIL which isn't reflected in the FAQ yet.

Also the second option:

> It has been suggested that the GIL should be a per-interpreter-state lock rather than truly global; interpreters then wouldn’t be able to share objects. Unfortunately, this isn’t likely to happen either.

If I understand correctly, interpreters with an isolated GIL are now at least partially implemented in a release version and again this isn't reflected in the FAQ.

### Linked PRs
* gh-114957

**Comment by da-woods** [comment]
Possibly also should be tagged `topic-subinterpreters` (I don't think I have the permissions to do so myself)

**Comment by willingc** [comment]
@da-woods Did merging #114957 resolve this issue?

**Comment by da-woods** [comment]
Yes, I think so. I'll close this.
