### ISSUE TITLE
test_pendingcalls_threaded times out on Windows free-threading builds

### ISSUE THREAD

**Issue by encukou** [python/cpython#114746]
`test.test_capi.test_misc.TestPendingCalls.test_pendingcalls_threaded` usually (but not always) times out on the [AMD64 Windows Server 2022 NoGIL 3.x](https://buildbot.python.org/all/#/builders/1241) buildbot, e.g. here: https://buildbot.python.org/all/#/builders/1241/builds/1116/steps/4/logs/stdio

It started 5 days ago, after #114262  (Implement GC for free-threaded builds) and #114479 (Make threading.Lock a real class, not a factory function), and it looks like it got more frequent after #113412 (Use pointer for interp->obmalloc state). (This is just from looking at the buildbot logs, I haven't bisected.)

### Linked PRs
* gh-114817

**Comment by encukou** [comment]
I cannot reproduce on my Windows 11 (10.0.22621.3007) VM :(

Faulthandler tracebacks (with source lines added):
```
Thread 0x00001f80 (most recent call first):
  File "C:\Users\Administrator\buildarea\3.x.itamaro-win64-srv-22-aws.x64.nogil\build\Lib\test\test_capi\test_misc.py", line 1344 in pendingcalls_thread
    context.event.set()
  File "C:\Users\Administrator\buildarea\3.x.itamaro-win64-srv-22-aws.x64.nogil\build\Lib\threading.py", line 1027 in run
...

Thread 0x000032d0 (most recent call first):
  File "C:\Users\Administrator\buildarea\3.x.itamaro-win64-srv-22-aws.x64.nogil\build\Lib\test\test_capi\test_misc.py", line 1304 in pendingcalls_wait
    a = i*i
  File "C:\Users\Administrator\buildarea\3.x.itamaro-win64-srv-22-aws.x64.nogil\build\Lib\test\test_capi\test_misc.py", line 1332 in test_pendingcalls_threaded
    self.pendingcalls_wait(context.l, n, context)
...
```

**Comment by terryjreedy** [comment]
On my Win10 fresh debug nogil build, test.test_capi paused several minutes on
`test_trashcan_python_class1 (test.test_capi.test_misc.CAPITest.test_trashcan_python_class1)`
I went away to eat and upon return it had finished ok in 14 minutes, which I believe is a few times as long as normal.

**Comment by encukou** [comment]
@colesbury Is this a high-priority issue for you, or normal behaviour at this stage of the feature?
We might want to increase the timeout, and revisit GC performance later.

**Comment by colesbury** [comment]
@encukou I'm planning to put out a PR to fix it today

**Comment by colesbury** [comment]
The six builds since the PR merged are all green: https://buildbot.python.org/all/#/builders/1241
