### ISSUE TITLE
argparse.FileType.__call__ ignores encoding and errors on '-'

### ISSUE THREAD

**Issue by cfra** [python/cpython#114724]
# Bug report

### Bug description:

I am using `argparse.FileType` like this:

```python
parser.add_argument("input", type=argparse.FileType('r', encoding='utf-8', errors='replace'))
```

When providing an actual file for input, this works as expected.

However, when using `-` to consume input from stdin, my program fails like this:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe7 in position 4723: invalid continuation byte
```

Looking through the implementation of `argparse.FileType` I see the following code:

```
    def __call__(self, string):
        # the special argument "-" means sys.std{in,out}
        if string == '-':
            if 'r' in self._mode:
                return _sys.stdin.buffer if 'b' in self._mode else _sys.stdin
            elif any(c in self._mode for c in 'wax'):
                return _sys.stdout.buffer if 'b' in self._mode else _sys.stdout
            else:
                msg = _('argument "-" with mode %r') % self._mode
                raise ValueError(msg)
```

Obviously, for the special case of `-` as argument, the `encoding` and `errors` settings are completely ignored.

I believe this is a bug: When I specify `argparse.FileType('r', encoding='utf-8', errors='replace')` as type, I expect to always receive a file with the proper `encoding` and `errors` setting, and not just sometimes.

At the very least, the documentation should point out the caveat that these settings only work for actual files.

Preferably, this would be fixed in a way that the functionality works consistently for stdin/stdout and actual files.

One idea could be to always use the binary stdin/stdout and use it as backing for an io wrapper with the proper encoding/errors setting, however I am not sure if there are any problems regarding backward-compatibly that need to to be considered e.g. when users use both the return value from the `FileType` and `sys.stdin` directly.

I would be willing to work on a resolution for this if somebody could provide a bit of guidance on what a good solution would look like.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by hpaulj** [comment]
Years ago I commented in a bug/issue that `FileType` was meant to be a sample `type` factory.  The original author corrected me, and said he intended it as a tool for quick-n-dirty scripts that took a simple pair of input and output files, much like what you'd expect from a shell functions.  This was in PY2 days, with fewer file modes.  I don't think `FileType` has ported to Py3 gracefully.

I don't know enough about stdio files to say whether what you want is feasible or not.  And I'm not sure it's a good idea to add more functionality to the existing function.  You can certainly write your own `type` function that works as you want.  Or let the parser just return a string, and you do your own open/close.

In Py3 we are encouraged to open files using the `with` context.  I tried to write a `FileType` function that did that, and found that handling `stdio` files was overly complicated.

**Comment by serhiy-storchaka** [comment]
FileType has been deprecated in 3.14.
