### ISSUE TITLE
"Porting Python2 to Python3" recommends tools that no longer support Python2

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#114785]
This section recommends several tools: https://docs.python.org/3/howto/pyporting.html#how-to-port-python-2-code-to-python-3

Including:
- pylint: https://github.com/pylint-dev/pylint/issues/1763
- coverage: https://pypi.org/project/coverage/ (python3 only)
- mypy: https://github.com/python/mypy/issues/12237
- tox: https://github.com/tox-dev/tox/issues/1130

But, these tools do not support Python2 anymore, so users will probably struggle with this advice.

CC @brettcannon as the author.

### Linked PRs
* gh-114805
* gh-115327
* gh-115328

**Comment by ericvsmith** [comment]
Is it time to retire this page entirely? There are plenty of sources available online that are kept more up-to-date.
