### ISSUE TITLE
`test_runpy.test_main_recursion_error()` exhausts the stack under WASI debug build

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#114743]
# Bug report

### Bug description:

Has to be run directly to trigger it.

```shell
cross-build/wasm32-wasi/python.sh -m test.test_runpy
```

Seen on wasmtime 17.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-114772

**Comment by cppenjoy** [comment]
❤️
