### ISSUE TITLE
WASI build fails on both SDK 20 and 21 (Mac OS)

### ISSUE THREAD

**Issue by thesuhas** [python/cpython#114736]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
On trying to build CPython for wasmtime with both SDK 20 and 21, I get an error on running: `python Tools/wasm/wasi.py configure-host`
Error:

![image](https://github.com/python/cpython/assets/54014218/aa15dbce-b9be-4a08-ad7e-171bdd9ef02d)
I've tried modifying the env vars to clang and tried to replace it with gcc as well. Still fails. Any pointers?

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Linked PRs
* gh-116771

**Comment by brettcannon** [comment]
Are you trying to build Python 3.11 using `Tools/wasm/wasi.py` (based on the "versions tested")? If so, that script has not been tested on anything but `main`, so you would need to use https://github.com/python/cpython/blob/3.11/Tools/wasm/wasm_build.py instead.

I've also only made sure a WASI build works under WASI-SDK 20 w/ wasmtime under preview 1 so far, so 21 isn't confirmed to work yet.

**Comment by brettcannon** [comment]
You can also look at `config.log` to see it it says anything interesting.

**Comment by brettcannon** [comment]
And did you try using `wasi.py build` first? I.e. did the build Python steps succeed and is there a specific reason you're doing it in discrete steps?

**Comment by thesuhas** [comment]
Hey sorry for the late reply. I did try `wasi.py build` first and it failed so I ran the steps individually. I'll re-run it and check the `config.log` and get back to you!

**Comment by hugovk** [comment]
Can this be closed now https://github.com/python/cpython/pull/116771 has been merged?

**Comment by brettcannon** [comment]
> Can this be closed now #116771 has been merged?

Yep! I was waiting for the PR to merge (the macOS runners were taking so long I had to log off before CI finished).
