### ISSUE TITLE
`warnings.warn(...)` arguments include '\*', which is wrong - 3.12

### ISSUE THREAD

**Issue by scotscotmcc** [python/cpython#114811]
# Documentation

Looking at the online python docs at https://docs.python.org/3.11/library/warnings.html#warnings.warn. The function call is listed on the site like this:
```python
warnings.warn(message, category=None, stacklevel=1, source=None, \*, skip_file_prefixes=None)
```

As far as I know (my apologies if I am very wrong), `\*` isn't a valid argument, and it should just be `*`.

Best guess is that since the actual code ([here](https://github.com/python/cpython/blob/0536bbb192c5ecca5e21385f82b0ac86f2e7e34c/Lib/warnings.py#L297-L298)) has a linebreak in the arguments, that linebreak got formatted for the docs as a `\*`.

I saw this all come up in [this stackoverflow question](https://stackoverflow.com/questions/77912637/what-is-in-python-function-definition#77915107) where other people thought it all through, i'm just posting the issue.

This seems to be new in 3.12

### Linked PRs
* gh-114819
* gh-114837

**Comment by hugovk** [comment]
Thank you for the report! 

Yep, this shows up at https://docs.python.org/3/library/warnings.html#warnings.warn but not https://docs.python.org/3.11/library/warnings.html#warnings.warn

Looking at the code:

https://github.com/python/cpython/blob/3e06cce36ad4ff8f35e6a6c05ee1afb5ee1f8031/Lib/warnings.py#L297-L298

You're right, this should just be `*`.

This means the arguments to the right of the asterisk are keyword-only.

I guess the original author added the slash in an attempt to escape it, but it's actually not needed here.

Would you like to make a PR to fix it?

The file to fix is https://github.com/python/cpython/blob/main/Doc/library/warnings.rst

**Comment by terryjreedy** [comment]
Thanks for catching and patching the error.
