### ISSUE TITLE
futures.standard_library raises ModuleNotFoundError: No module named 'imp' in Python 3.12

### ISSUE THREAD

**Issue by nkuehnle** [python/cpython#114890]
# Bug report

### Bug description:

```python
from future import standard_library
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
`future` is not part of the standard library. You may want to report this to https://github.com/PythonCharmers/python-future (though that project isn't getting a lot of updates any more, since few people still have to deal with Python 2 upgrades).
