### ISSUE TITLE
Add array.clear()

### ISSUE THREAD

**Issue by mikeziminio** [python/cpython#114894]
# Bug report

### Bug description:

```python
from array import array

x = array("B")
x.clear()    # AttributeError: 'array.array' object has no attribute 'clear'
```

But `array` is a `MutableSequence`, so we expect the clear() method to be implemented.
If this is correct, then I'm ready to work on PR.

Original issue from the typeshed repository: https://github.com/python/typeshed/issues/11008

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-114919

**Comment by aisk** [comment]
In my personal view, according to the original issue, the intention behind adding the `clear` method is to allow `array.array` to implement `collections.abc.MutableSequence`, so we can add a test to test it and ensure we don't break it in the future.

There is already a relevant test case in https://github.com/python/cpython/blob/main/Lib/test/test_collections.py#L1968, so what we need to do is simply include `array.array` in this existing test case.

**Comment by JelleZijlstra** [comment]
Thanks for your contribution!
