### ISSUE TITLE
Match on Enum with dataclass decorator

### ISSUE THREAD

**Issue by bedapisl** [python/cpython#114803]
# Bug report

### Bug description:

Hello,
when Enum with @dataclass decorator is used in a match statement, the results seem to be wrong. Consider this example:

```python
from enum import Enum, auto
from dataclasses import dataclass

@dataclass
class Color(str, Enum):
    Red = auto()
    Green = auto()

mode = Color.Green

match mode:
    case Color.Red:
        print(f"Matched RED, actual {mode}")
    case Color.Green:
        print(f"Matched GREEN, actual {mode}")
    case _:
        assert False

```

I think it should print:
```
Matched GREEN, actual Color.Green
```
but it prints:
```
Matched RED, actual Color.Green
```

I would suggest this either prints the expected result, or at least produces some error instead of the current behaviour. 

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-114891

**Comment by sobolevn** [comment]
Can you please explain your use-case a little bit more? It is uncommon to use `@dataclass` on `Enum`

**Comment by ericvsmith** [comment]
Agreed with @sobolevn: it's not clear why you'd want to do this. But if it is important, we'd probably need to add a parameter to `@dataclass` to not set `__match_args__, which I assume is what causes the problem.

**Comment by ethanfurman** [comment]
@ericvsmith, I tried deleting `__match_args__` from `Color`, and got the same results.  Also, turning an enum into a dataclass breaks basic behavior:

```python
>>> Color.Red == Color.Green
True
```

Perhaps the better solution is to reject enums as dataclasses?  I am unclear on what benefit a dataclass-enum would offer, since all members are already defined by the time the decorator gets control.

**Comment by brandtbucher** [comment]
I don't think `__match_args__` is a problem here, since there are no class patterns (we're matching against attributes of the `Color` class, not instances of it.

Honestly, this isn't an issue with `match`... I just have no idea what an `@dataclass`-decorated `Enum` is supposed to mean.

**Comment by bedapisl** [comment]
Hello,
I don't have a direct use case for this.

**Comment by sobolevn** [comment]
> Perhaps the better solution is to reject enums as dataclasses?

I can clearly see that this is reasonable. However, this will come with several downsides:
1. We have to check all `mro` for `Enum` and slow things down for all use-cases
2. This error seems to be rather rare to enforce it for everyone
3. There might be other custom magic / metaclass-heavy classes that won't work with `@dataclass`

So, maybe just close the issue for now? If this problem prooves to be common, we can get back to it.

**Comment by ethanfurman** [comment]
Perhaps a doc update stating that the proper way to use `dataclass` and `Enum` together is with an existing dataclass as a mixin to an enum.

The link in the enum HowTo document is `.. _enum-dataclass-support:`.
