### ISSUE TITLE
Simple addition yields inexact solution

### ISSUE THREAD

**Issue by Joao-Dionisio** [python/cpython#114815]
# Bug report

### Bug description:

I understand that numerics is a pain, but this seems like a straightforward computation

```python
# Add a code block here, if required
20.35 + 6.17 # the result is 26.520000000000003
```
Apologies if this is better suited somewhere else.

![image](https://github.com/python/cpython/assets/57299939/13991154-5361-46ce-b413-23f11b980039)

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
There's no bug.
For more information see https://docs.python.org/3/tutorial/floatingpoint.html.
