### ISSUE TITLE
Speed up `posixpath.realpath()`

### ISSUE THREAD

**Issue by barneygale** [python/cpython#114847]
Some optimizations to `posixpath.realpath()` are possible - see attached PR.

### Linked PRs
* gh-114848
* gh-117481

**Comment by encukou** [comment]
The introduction of a `querying` flag that's reset once changes behaviour, since `rest` can return back into an existing path.

Given a directory and a link to it:
```
$ mkdir a_dir
$ ln -s a_dir a_link
```

with Python 3.12 I get:
```
>>> os.path.realpath('foo/../a_link')
'/tmp/links/a_dir'
```
With this PR:
```
>>> os.path.realpath('foo/../a_link')
'/tmp/links/a_link'
```
The previous behaviour matches coreutils:
```
$ realpath -m foo/../a_link
/tmp/links/a_dir
```
