### ISSUE TITLE
`jit.c` always recompiles, even on non-JIT builds

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#114883]
I think I messed up the `Makefile` rules for `Python/jit.o` and `regen-jit`. Since `regen-jit` is "phony", the rule isn't in the dependency graph and `make` has no way of knowing if a recompile is necessary.

We *may* have to do something similar to what we did for the Windows builds and encode the dependencies in the Makefile. Or maybe there's an easier way. If anyone has any tips, please share!

### Linked PRs
* gh-114884

**Comment by zware** [comment]
I don't have a full understanding of how the JIT build works, but I think I'm on the cusp of a Makefile fix that you can tweak to work correctly for the JIT-enabled build.  PR to come.
