### ISSUE TITLE
Improved Errors for Missing Standard Library Modules (cf PEP 534)

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#114812]
# Feature or enhancement

### Proposal:

There was discussion of adding a hook to modify `ModuleNotFoundError` here:
https://peps.python.org/pep-0534/

The PEP was deferred. But the following tiny patch is sufficient to implement this:
```patch
--- a/Lib/importlib/_bootstrap.py
+++ b/Lib/importlib/_bootstrap.py
@@ -1301,6 +1301,9 @@ def _sanity_check(name, package, level):
 _ERR_MSG_PREFIX = 'No module named '
 _ERR_MSG = _ERR_MSG_PREFIX + '{!r}'
 
+def _get_module_not_found_error(name):
+    return ModuleNotFoundError(f'{_ERR_MSG_PREFIX}{name!r}', name=name)
+
 def _find_and_load_unlocked(name, import_):
     path = None
     parent = name.rpartition('.')[0]
@@ -1321,7 +1324,7 @@ def _find_and_load_unlocked(name, import_):
         child = name.rpartition('.')[2]
     spec = _find_spec(name, path)
     if spec is None:
-        raise ModuleNotFoundError(f'{_ERR_MSG_PREFIX}{name!r}', name=name)
+        raise _get_module_not_found_error(name)
     else:
         if parent_spec:
             # Temporarily add child we are currently importing to parent's
```
Then a distribution can monkeypatch `_get_module_not_found_error` if they want to.

cc @encukou 

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://peps.python.org/pep-0534/

### Linked PRs
* gh-114813

**Comment by brettcannon** [comment]
Are you injecting a function to override it?

**Comment by terryjreedy** [comment]
@encukou @ncoghlan PEP 534 authors: Implement this much without 'approval'?

I think this much maybe did not need PEP.  Did not read most of PEP.  Should rest be withdrawn?  or revived?

**Comment by hauntsaninja** [comment]
PEP 534 was written before we had `sys.stdlib_module_names`. This could be enough for us to provide a better error message within CPython itself, since it's documented as being the same on all platforms, including modules disabled at build time, etc

**Comment by hoodmane** [comment]
I think there's always going to be value in letting distributions provide extra information that the interpreter can't possibly know about. We want to distinguish between:

> We unvendored module <whatever> to save space, if you want to use it you have to install it first by doing <...>

and

> We unvendored module <whatever> because it only kind of works, if you want you can use it anyways by doing <...>

and

> We removed module <whatever> because it is completely broken.

Also stuff like:

> You don't currently have pandas installed but it's available as part of our distribution and you can get it by doing <...>

**Comment by encukou** [comment]
I'll be happy to revive the PEP, with you as co-author.

The proposed change still needs patching to modify the message, so I'm not convinced it's an improvement.

**Comment by hoodmane** [comment]
Actually, on further consideration maybe with `BaseException.add_note()` don't need anything for this at all, e.g.:
```py
orig_except_hook = sys.excepthook
def new_except_hook(ty, exc, tb):
   if isinstance(exc, ModuleNotFoundError):
      exc.add_note("My note")
   orig_except_hook(ty, exc, tb)
```

**Comment by hoodmane** [comment]
This part of the PEP is helpful advice:

> [Recommendation for Downstream Distributors](https://peps.python.org/pep-0534/#recommendation-for-downstream-distributors)
>
> By patching [site.py](https://docs.python.org/3.7/library/site.html) [[*]](https://peps.python.org/pep-0534/#id4) to provide their own implementation of the [sys.excepthook](https://docs.python.org/3/library/sys.html#sys.excepthook) function, Python distributors can display tailor-made error messages for any uncaught exceptions, including informing the user of a proper, distro-specific way to install missing standard library modules upon encountering a [ModuleNotFoundError](https://docs.python.org/3.7/library/exceptions.html#ModuleNotFoundError).

**Comment by hoodmane** [comment]
Thanks for the help everyone! I'm going to close this since I am happy with this `add_note` based approach.
