### ISSUE TITLE
Lists created by default value of class constructor kwarg refer to same list

### ISSUE THREAD

**Issue by Dano507** [python/cpython#114895]
# Bug report

### Bug description:

When a list variable is created by a kwarg's default value inside a class constructor, all class instances will refer to that same list. This doesn't feel like intentional behavior.

```python
class TestClass:
  def __init__(self, test_list=[]):
    self.data = test_list

  def add_data(self, data):
    self.data.append(data)

inst1 = TestClass()
inst2 = TestClass()

print(inst1.data, inst2.data)  # [] []
inst1.add_data("Shouldn't appear in inst2.data")
print(inst1.data, inst2.data)  # ["shouldn't appear in inst2.data"] ["shouldn't appear in inst2.data"]

# Should not be the same address, but they are
print(hex(id(inst1.data)))
print(hex(id(inst2.data)))
```
Here is a workaround for anyone with the same issue. This is more verbose, but mitigates the issue.
```python
class TestClass:
  def __init__(self, test_list=None):  # Replace default value with None
    self.data = test_list
    if self.data == None: self.data = []  # Add this line

  def add_data(self, data):
    self.data.append(data)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Thanks! However, this is longstanding, intended behaviour. Please see:

- https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects
- https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument

**Comment by Dano507** [comment]
I took a look through the python.org page and the behavior makes sense now.

Thanks for the links and the prompt reply!
