### ISSUE TITLE
Bug in block comments with escape characters.

### ISSUE THREAD

**Issue by massibronto** [python/cpython#114865]
# Bug report

### Bug description:

```python
print("start")

'''
fdf

escape
r'\Atestescape'

second
re.search(r'\f([a-z])(\d{6})', values["-IN-"])

block comment

'''

print("end")


input("pause..")
```

The issue happens when having escape characters inside block comments.
The block comment will break on the character sequence \A and \x and \d.
Error messages:
`blockcomment.py:4: SyntaxWarning: invalid escape sequence '\A'`
or
`blockcomment.py:4: SyntaxWarning: invalid escape sequence '\d'`
or
```
blockcomment.py", line 3
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 58-59: truncated \xXX escape
```

Whereas the block comment will not break on \f or \t

I would expect the block comment to completely ignore the inside, or am I wrong?

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
Python doesn't have block comments; what you're using is a string, which happens to work something like a block comment because it's ignored at runtime. The warning you cite is raised in strings and is correct.

**Comment by massibronto** [comment]
Thank you for pointing this out. Sorry for this misconception; I am not so familiar with the language yet.

**Comment by terryjreedy** [comment]
Please direct questions, including about possible bugs, to a help forum such as https://discuss.python.org/c/users/7
