### ISSUE TITLE
Race between `_PyParkingLot_Park` and `_PyParkingLot_UnparkAll` when handling interrupts

### ISSUE THREAD

**Issue by mpage** [python/cpython#114944]
# Bug report

### Bug description:

There is a potential race when `_PyParkingLot_UnparkAll` is executing in one thread and another thread is unblocked because of an interrupt in `_PyParkingLot_Park`. Consider the following scenario:

1. Thread T0 is [blocked](https://github.com/python/cpython/blob/f35c7c070ca6b49c5d6a97be34e6c02f828f5873/Python/parking_lot.c#L303) in `_PyParkingLot_Park` on address `A`.
2. Thread T1 executes `_PyParkingLot_UnparkAll` on address `A`. It finds the `wait_entry` for `T0` and [unlinks](https://github.com/python/cpython/blob/f35c7c070ca6b49c5d6a97be34e6c02f828f5873/Python/parking_lot.c#L369) its list node.
3. Immediately after (2), T0 is woken up due to an interrupt. It then segfaults trying to [unlink](https://github.com/python/cpython/blob/f35c7c070ca6b49c5d6a97be34e6c02f828f5873/Python/parking_lot.c#L320) the node that was previously unlinked in (2).

I haven't attempted to write a minimal repro for this. It occurs reliably on MacOS on [this PR](https://github.com/python/cpython/pull/114839) when running `./python.exe -m test test_asyncio.test_events --match test_get_event_loop_new_process`.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-114945

**Comment by mpage** [comment]
Paging Dr. @colesbury

**Comment by colesbury** [comment]
Ahh, good catch. We handle this case for the single unpark, but not unparkAll.
