### ISSUE TITLE
calendar module CLI option --first-weekday is missing from usage message

### ISSUE THREAD

**Issue by planet36** [python/cpython#114909]
# Documentation

PR https://github.com/python/cpython/pull/112241 added the `--first-weekday` option to the calendar module CLI.

It was only partly documented in `calendar.rst`, as it's missing from the first usage message.

>   python -m calendar [-h] [-L LOCALE] [-e ENCODING] [-t {text,html}]
>                      [-w WIDTH] [-l LINES] [-s SPACING] [-m MONTHS] [-c CSS]
>                      [year] [month]

This should be added
> [-f FIRST_WEEKDAY]

### Linked PRs
* gh-114910

**Comment by hugovk** [comment]
Tip for next time: docs things like this usually don't need an issue. Or they can re-use the original issue (https://github.com/python/cpython/issues/112240).
