### ISSUE TITLE
Feature Request: Add get_free_port() Function to socket Module

### ISSUE THREAD

**Issue by songyuc** [python/cpython#114927]
# Feature or enhancement

### Proposal:

I propose the addition of a new function, `get_free_port()`, to the `socket` module in Python. This function would serve the purpose of automatically finding and returning an available network port on the local machine. The primary goal of this function is to simplify the process of obtaining a free port for network applications, especially during development and testing, where hardcoding port numbers can lead to conflicts.

**Rationale:**
In network programming, especially in development environments, there's a common need to bind servers to free ports to avoid port conflicts. Currently, Python developers need to write additional code to handle this, which can be cumbersome and error-prone. A built-in `get_free_port()` function in the `socket` module would streamline this process.

The function would be particularly useful in scenarios where:
1. Multiple instances of a service or application need to run simultaneously on different ports.
2. Automated testing or continuous integration systems require dynamic allocation of ports to avoid conflicts with other running services.
3. Development environments where port numbers cannot be predetermined.

**Example Usage:**
```python
import socket

free_port = socket.get_free_port()
server.bind(('localhost', free_port))
```

**Implementation Details:**
The function could internally use a combination of existing socket methods to attempt to bind to a port (without actually starting a server) and return the chosen port number. It would handle the exception if the port is already in use and retry with a different port until a free one is found.

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
Not all protocols have the concept of a port. TCP and UDP do, ICMP does not. And the TCP "namespace" for used/free ports is different from UDP's. So at the very least, this would need to be tied to the protocol. You're also going to have a problem with race conditions: your code will still have to deal with being unable to bind to a port.

I suggest you bring this idea up https://discuss.python.org/c/ideas/6.

**Comment by ronaldoussoren** [comment]
Such a function would inherently introduce a race condition between getting a free port number an actually using it.

For tcp and udp you can bind to port 0 to get a free port and use `getsockname` to fetch the allocated port number, e.g:

```python
>>> import socket
>>> sd = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> sd.bind(('localhost', 0))
>>> sd.getsockname()
('127.0.0.1', 55671)
```

**Comment by ericvsmith** [comment]
I'm going to close this, since as @ronaldoussoren points out there are better ways to do this, and it should be discussed on d.p.o first.
