### ISSUE TITLE
Documentation says "The built-in exceptions listed below", but they are no longer just below that section

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#114967]
# Documentation

In the documentation of "Built-in Exceptions", the second paragraph states `The built-in exceptions listed below can be generated by the interpreter or built-in functions`. Because of the new sections "Exception context" and "Inheriting from built-in exceptions" were introduced in Python 3.9, the word "below" became ambiguous. I suggest changing it to `The built-in exceptions listed in the document...`.

### Linked PRs
* gh-114968
* gh-115033
* gh-115034

**Comment by terryjreedy** [comment]
You are interpreting 'below' a little too narrowly.  'in this document' is also ambiguous and too broad.  I considered closing this, however, I think 'listed in this chapter' should be clearer than either.
