### ISSUE TITLE
ast parsing and unparsing mismatchs with input

### ISSUE THREAD

**Issue by ze-gois** [python/cpython#114984]
# Bug report

### Bug description:

```python
import ast
z = "( 'a' and 'b' ) or ( 'c' and 'd' )"
print(ast.unparse(ast.parse(z)))
```
yields 
```
'a' and 'b' or ('c' and 'd')
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
Thanks for the issue! Would you mind explaining exactly what you think the bug is here? The original expression and the one produced by `ast.unparse` evaluate to the same thing, and they have identical ASTs

**Comment by jhenriquetdg** [comment]
Are them the same because `and` precedes `or` ?

Maybe it is not a bug.

**Comment by AlexWaygood** [comment]
Yes, `and` always binds more tightly than `or` — from the interpreter's point of view, the two expressions are identical :)
