### ISSUE TITLE
Popen misleading documentation

### ISSUE THREAD

**Issue by hvbtup** [python/cpython#114913]
# Documentation

It took me hours that I made an error in the code. However, this error was probably the result of an unfortunate formatting in the docs.

The documentation for `subprocess.Popen` reads:

If given, _startupinfo_ will be a [STARTUPINFO](https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO) object, which is passed to the underlying CreateProcess function. _creationflags_, if given, can be one or more of the following flags ...

I suggest to start the documentation for _creationflags_ in a new paragraph instead:

If given, _startupinfo_ will be a [STARTUPINFO](https://docs.python.org/3/library/subprocess.html#subprocess.STARTUPINFO) object, which is passed to the underlying CreateProcess function. 

_creationflags_, if given, can be one or more of the following flags ...

I mixed up options for `creationflags` and `startupinfo` in my code.

### Linked PRs
* gh-114941
* gh-114942
* gh-114943

**Comment by terryjreedy** [comment]
After looking at the doc, I agree that *creationflags* is a separate topic from *startupinfo*.  Given that this doc discusses each parameter or related parameters in separate paragraphs, these should be separate also.
