### ISSUE TITLE
Make iterable (and subscriptable) the `Namespace` object in argparse lib

### ISSUE THREAD

**Issue by milanbalazs** [python/cpython#114920]
# Feature or enhancement

### Proposal:

The `parse_args` method returns a `Namespace` type object and it's not iterable and subscriptable. It would be nice to iterate through the `Namespace` object and get the values directly form the object (subscriptable).

Now it's only possible to use the `vars` function (with getattr), which is not a really elegant solution. Eg.: to get the set arguments (bool parameters):

```python
args: argparse.Namespace = parser_object.parse_args()
set_args: list = list(arg for arg in vars(args) if getattr(args, arg))
```

It's not even possible:

```python
args: argparse.Namespace = parser_object.parse_args()
print(args["my_arg"]). # TypeError: 'Namespace' object is not subscriptable
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-114926

**Comment by serhiy-storchaka** [comment]
Python is not a JavaScript. Object and mapping are different concepts. You can use `vars()` and `getattr()` with a namespace object to iterate all attributes and values and get the specified attribute value.

**Comment by milanbalazs** [comment]
> Python is not a JavaScript. Object and mapping are different concepts. You can use `vars()` and `getattr()` with a namespace object to iterate all attributes and values and get the specified attribute value.

I don't really agree with you. I guess the `vars()` and `getattr()` usage to get the key/values from a "container" object is not an elegant solution. The Python provides opportunity to create iterable/subscriptable objects, so I think it's efficient to use that functionalities and it would be Pythonic solution.

**Comment by gaogaotiantian** [comment]
Could you give us an example where you need to iterate through an argparse namespace? I think we should justify the usage when we propose a new feature. Making the `Namespace` iterable and subscriptable is not difficult, but what for? Is it significantly better than the current object model? `argparse` is a very specific library and I can't think of a very common case where users need to iterate through all the options.

**Comment by milanbalazs** [comment]
> Could you give us an example where you need to iterate through an argparse namespace? I think we should justify the usage when we propose a new feature. Making the `Namespace` iterable and subscriptable is not difficult, but what for? Is it significantly better than the current object model? `argparse` is a very specific library and I can't think of a very common case where users need to iterate through all the options.

First of all, thanks for your feedback. For example, I have a Python script with several CLI arguments (Only bools) and it will be used from Shell scripts. It's required to set exactly one argument. 

I guess currently this is how it can be solved (representing with a small script):

```python
import argparse

parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)

parser.add_argument("--test_1", action="store_true")
parser.add_argument("--test_2", action="store_true")

args: argparse.Namespace = parser.parse_args()

# Check how many args are provided via CLI from Shell script (If the value is True, the arg is provided). 
set_args: list = list(arg for arg in vars(args) if getattr(args, arg))

if len(set_args) != 1:
    raise ValueError(f"Exactly 1 argument should be provided. You provided: {set_args}")
``` 

With my change (with last commit) the `list(arg for arg in vars(args) if getattr(args, arg))` can be change to:

```python
list(k for k, v in args if v)
```

I think my solution is much readable and logical solution (And in my opinion it's a Pythonic approach).

**Comment by gaogaotiantian** [comment]
The correct way to do this, is [mutually exclusive group](https://docs.python.org/3/library/argparse.html#argparse.ArgumentParser.add_mutually_exclusive_group)

```python
import argparse

parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("--test_1", action="store_true")
group.add_argument("--test_2", action="store_true")

# It will report error if not exactly one of the argument is provided
args: argparse.Namespace = parser.parse_args()
```

It's better to define it in the parsing rule, than checking it at run-time.

**Comment by milanbalazs** [comment]
Ahhh... Nice! I was not aware of that feature, it covers my above use-case. Thanks to let me know.

However, I think my change is just an extra function of `argparse` module as I mentioned. But feel free to close my ticket/PR if you think it's nonsense.

**Comment by gaogaotiantian** [comment]
In that case, I would suggest using the `append_const` action. You have multiple arguments that are similar options that you need to retrieve.

```python
import argparse

parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)
group = parser.add_mutually_exclusive_group(required=True)
group.add_argument("--test_1", dest="tests", action="append_const", const="test_1")
group.add_argument("--test_2", dest="tests", action="append_const", const="test_2")

# It will report error if not exactly one of the argument is provided
args: argparse.Namespace = parser.parse_args()
print(args.tests[0])
```

However, this is not the best solution. I think you are constructing your command line design wrong. If you want to specify a single test from the command line from many tests, it's not supposed to be passed by `test_1` and `test_2`. It should be `python script.py --test test_1`

The code to parse it should be

```python
import argparse

parser: argparse.ArgumentParser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--test", nargs=1, required=True)

# It will report error if not exactly one of the argument is provided
args: argparse.Namespace = parser.parse_args()
```

This does what you need and is much clearer than your parser design, if I understand your need correctly.

**Comment by terryjreedy** [comment]
Given that global namespaces are dicts and local namespaces are at least mappings, I don't think it nonsense to expect a Namespace to be iterable.  However, Its [doc](https://docs.python.org/3/library/argparse.html#the-namespace-object) says
> This class is deliberately simple, just an [object](https://docs.python.org/3/library/functions.html#object) subclass with a readable string representation.

It is an *object* subclass,  not a *dict* subclass.

>  If you prefer to have dict-like view of the attributes, you can use the standard Python idiom, [vars()](https://docs.python.org/3/library/functions.html#vars):

For a dict view, use the standard methods.  

From experience, mixing indexing with attributing, configing, getting&setting,  or similar gets messy.  Given everything in the doc and comments above, I also feel we need not and should not do so here.
