### ISSUE TITLE
Missing `clear` mixin method in MutableSequence's document

### ISSUE THREAD

**Issue by aisk** [python/cpython#114955]
Link: https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes

But `MutableSequence` do have this mixin method: https://github.com/python/cpython/blob/28bb2961ba2f650452c949fcfc75ccfe0b5517e9/Lib/_collections_abc.py#L1132

### Linked PRs
* gh-114956
* gh-114961
* gh-114962

**Comment by rhettinger** [comment]
Thanks for filing the issue and making the PR.
