### ISSUE TITLE
The attribute bigincrement has no effect on a tkinter Scale

### ISSUE THREAD

**Issue by lgquevedov** [python/cpython#115051]
# Documentation
I was studying the tkinter module. I wrote a small code to test the scale widget and found the bigincrement has not effect.
code:
```python
import tkinter as tk
root = tk.Tk()
# Crear una escala con bigincrement
escala = tk.Scale(root, from_=0, to=100, bigincrement=10)
escala.pack()
root.mainloop()
```
I try arrow keys mouse move , mouse clicks, etc... on  ubuntu 22.04.  The increment always was 1.

**Comment by terryjreedy** [comment]
Scale [doc:](https://www.tcl.tk/man/tcl8.6/TkCmd/scale.html)
>Some interactions with the scale cause its value to change by “large” increments; this option specifies the size of the large increments. If specified as 0, the large increments default to 1/10 the range of the scale.
...
Control-Up and Control-Left move the slider up (left) by the value of the -bigincrement option.
Control-Down and Control-Right move the slider down (right) by the value of the -bigincrement option.

For keys to work, the widget must have keyboard focus, which will be indicated by a black 'focus box' around the widget.  On Windows with your code, this seems to require the addition of `escala.focus_force()` after packing.  With this done, ctrl-<arrow> works.. However, setting an attribute to its default has no effect.  Setting bigincrement to 33, for instance, jumps 33.

Searching stackoverflow.com questions with the [tkinter] tag is a good way to learn tips for tkinter widgets.

Please ask question about usage or possible bugs at https://discuss.python.org/c/users/7 or elsewhere.

**Comment by lgquevedov** [comment]
Thanks. Your answer is good enough.
