### ISSUE TITLE
A paragraph in ctypes documentation refers to an example that is no longer present in the documentation

### ISSUE THREAD

**Issue by ztane** [python/cpython#115091]
# Documentation

In ctypes documentation for 3.11 there was this excerpt in [ctypes documentation](https://docs.python.org/3.11/library/ctypes.html#accessing-values-exported-from-dlls):

> [ctypes](https://docs.python.org/3.11/library/ctypes.html#module-ctypes) can access values like this with the in_dll() class methods of the type. pythonapi is a predefined symbol giving access to the Python C api:
> 
> ```
> >>> opt_flag = c_int.in_dll(pythonapi, "Py_OptimizeFlag")
> >>> print(opt_flag)
> c_long(0)
> >>>
> ```
> 
> If the interpreter would have been started with [-O](https://docs.python.org/3.11/using/cmdline.html#cmdoption-O), the sample would have printed c_long(1), or c_long(2) if [-OO](https://docs.python.org/3.11/using/cmdline.html#cmdoption-OO) would have been specified.

The [example was rewritten for 3.12](https://docs.python.org/3.12/library/ctypes.html#module-ctypes) to use the - probably more widely understood `Py_Version` instead:

> [ctypes](https://docs.python.org/3.12/library/ctypes.html#module-ctypes) can access values like this with the [in_dll()](https://docs.python.org/3.12/library/ctypes.html#ctypes._CData.in_dll) class methods of the type. pythonapi is a predefined symbol giving access to the Python C api:
> >>>
> 
> ```
> >>> version = ctypes.c_int.in_dll(ctypes.pythonapi, "Py_Version")
> >>> print(hex(version.value))
> 0x30c00a0
> ```

However the last paragraph referring to the old example is **still** present:

> _If the interpreter would have been started with [-O](https://docs.python.org/3.12/using/cmdline.html#cmdoption-O), the sample would have printed c_long(1), or c_long(2) if [-OO](https://docs.python.org/3.12/using/cmdline.html#cmdoption-OO) would have been specified._
> 

### Linked PRs
* gh-115092
* gh-115936

**Comment by encukou** [comment]
Thanks for the catch!
