### ISSUE TITLE
make_dataclass function creates incorrect dataclass when using field with default_factory

### ISSUE THREAD

**Issue by sindzicat** [python/cpython#115073]
# Bug report

### Bug description:

Hello all!

When I create some dataclass as usual, all works fine:

```python
from dataclasses import dataclass

@dataclass
class MyData:
    a: int = field(default_factory= lambda: 0**2)
    b: int = field(default_factory= lambda: 1**2)
    c: int = field(default_factory= lambda: 2**2)
    d: int = field(default_factory= lambda: 3**2)
    e: int = field(default_factory= lambda: 4**2)
    f: int = field(default_factory= lambda: 5**2)

MyData().c  # we get 4, that is correct answer
```

Now I need to create the same dataclass via `make_dataclass` function:

```python
from dataclasses import make_dataclass, field

MyData2 = make_dataclass(
    'MyData2',
    [(x, int, field(default_factory=lambda: i**2)) for i, x in enumerate('abcdef')],
    frozen=True,
    slots=True
)

MyData2().c # we get 25 (5**2 = 25), but we expect 4
```

Also I found that `MyData2` will return 25 for any its parameter, that is:

```python
MyData2().a  # 25
MyData2().b  # 25
MyData2().c  # 25
MyData2().d  # 25
MyData2().e  # 25
MyData2().f  # 25
```

It seems to me there is some bug in how `make_dataclass` function works...

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
This isn't related to `make_dataclass` function. That's how `lambda` works in loops (list comprehension in your case).
For more information read the docs: https://docs.python.org/3/faq/programming.html#why-do-lambdas-defined-in-a-loop-with-different-values-all-return-the-same-result

**Comment by sindzicat** [comment]
@Eclips4, thanks a lot! I didn't know such fact about lambda functions. Now my code works fine:

```python
MyData2 = make_dataclass(
    'MyData2',
    [(x, int, field(default_factory=lambda t=i: t**2)) for i, x in enumerate('abcdef')],
    frozen=True,
    slots=True
)
```
