### ISSUE TITLE
Argument Clinic generates incorrect code for METH_METHOD methods without args

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#115015]
# Bug report

Argument Clinic generates incorrect code for methods without arguments, that need the defining class (`METH_METHOD`). Currently, only positional arguments are checked; any keyword argument is silently accepted. This affects methods in several extension modules (see PR).

See also a055dac0b45031878a8196a8735522de018491e3.

### Linked PRs
* gh-115016
* gh-115067
* gh-115069

**Comment by erlend-aasland** [comment]
Repro for `ndbm`:

```python
import dbm.ndbm
db = dbm.ndbm("test", "c")
db.keys(foo=1, bar=2)
```

**Comment by erlend-aasland** [comment]
FTR, this bug is also present in 3.10, but I doubt this can be categorised as a security-fix, so this behaviour will probably remain in that version.

**Comment by encukou** [comment]
It's a bugfix, but it's also a backwards-incompatible change, and leaving the bug in wouldn't hurt very much.
Consider only fixing it in main.

**Comment by erlend-aasland** [comment]
cc. 3.12 and 3.11 RMs, @Yhg1s and @pablogsal

**Comment by erlend-aasland** [comment]
Keeping this open until there's a decision regarding backporting.

**Comment by pablogsal** [comment]
I don't mind backporting it but only if @Yhg1s agrees as I don't want 3.11 to have the fix but not 3.12

**Comment by encukou** [comment]
@serhiy-storchaka, did Thomas agree with the backports?

**Comment by serhiy-storchaka** [comment]
@encukou, it is an ordinary bugfix. A special permission is needed when we backport a feature or a bugfix that likely can break existing code.
