### ISSUE TITLE
This Adapter and converter recipes seems to be incorrect.

### ISSUE THREAD

**Issue by elf-deedlit** [python/cpython#115064]
# Documentation

I'm not sure if I'm understanding this correctly, but could this part be incorrect?
https://docs.python.org/library/sqlite3.html#adapter-and-converter-recipes

Incorrect parts
```python
sqlite3.register_adapter(datetime.datetime, adapt_datetime_epoch)
```

Fixed parts
```python
sqlite3.register_adapter(datetime.time, adapt_datetime_epoch)
```

**Comment by erlend-aasland** [comment]
A couple of lines above, you'll find the adapter:

```python
def adapt_datetime_epoch(val):
    """Adapt datetime.datetime to Unix timestamp."""
    return int(val.timestamp())
```

The docstring says: *adapt datetime.datetime to Unix timestamp.*
The adapter is registered correctly to adapt `datetime.datetime` objects using the `adapt_datetime_epoch` function:

```python
sqlite3.register_adapter(datetime.datetime, adapt_datetime_epoch)
```

The docs are correct; closing the issue.
