### ISSUE TITLE
Upgrade Windows and macOS installers to use SQLite 3.45

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#115009]
SQLite 3.45 was released [a couple of weeks ago](https://sqlite.org/releaselog/3_45_1.html). A patch version recently arrived, so more might follow. There are som bug fixes for long standing bugs included, so we might want to backport this to the 3.12 and 3.11 installers.

### Linked PRs
* gh-115065
* gh-115066
* gh-115071
* gh-115072
* gh-115110
* gh-115111
* gh-117443
* gh-117445
* gh-117981
* gh-118008

**Comment by JinBridger** [comment]
Hi! May I ask will 3.9 and 3.10 be updated to use SQLite 3.45.1? @erlend-aasland

**Comment by erlend-aasland** [comment]
> Hi! May I ask will 3.9 and 3.10 be updated to use SQLite 3.45.1? @erlend-aasland

Probably not. Normally we only backport these changes to bugfix versions (currently, those are 3.12 and 3.11). 3.10 and 3.9 are only accepting security patches.

**Comment by JinBridger** [comment]
> > Hi! May I ask will 3.9 and 3.10 be updated to use SQLite 3.45.1? @erlend-aasland
> 
> Probably not. Normally we only backport these changes to bugfix versions (currently, those are 3.12 and 3.11). 3.10 and 3.9 are only accepting security patches.

Got it. Thanks!

**Comment by erlend-aasland** [comment]
You could try [pysqlite3](https://pypi.org/project/pysqlite3/) or [apsw](https://pypi.org/project/apsw/) on PyPI :)

**Comment by deresatom** [comment]
> You could try [pysqlite3](https://pypi.org/project/pysqlite3/) or [apsw](https://pypi.org/project/apsw/) on PyPI :)

Thanks for the tip!

Btw, the latest 3.12.2 windows installer from python.org is installing 3.43.1 instead of 3.45.1.  shouldn't it install the latest as this is closed & merged? Thanks!

**Comment by erlend-aasland** [comment]
> Btw, the latest 3.12.2 windows installer (v3.12.2:6abddd9) from python.org is installing 3.43.1 instead of 3.45.1. shouldn't it install the latest as this is closed & merged? Thanks!

Unfortunately, the Windows PR was merged after 3.12.2 landed, IIRC. It should be included in 3.12.3, though.

**Comment by jiangwen365** [comment]
Hello! May I ask will 3.12.3 and 3.11.8 get the update of SQLite 3.45.2, which fixed some minor query result bugs? 
It would be great if it could catch up the next bug-fixing release which will come out soon.
Really appreicated~ @erlend-aasland

**Comment by felixxm** [comment]
> Hello! May I ask will 3.12.3 and 3.11.8 get the update of SQLite 3.45.2, which fixed some minor query result bugs? It would be great if it could catch up the next bug-fixing release which will come out soon. Really appreicated~ @erlend-aasland

I was thinking the same thing yesterday,  #117443, #117445. 

There are some [new bugfixes](https://sqlite.org/src/timeline?r=branch-3.45) in the 3.45 branch so we can try waiting a few days for 3.45.3 :thinking:

**Comment by erlend-aasland** [comment]
@jiangwen365, I don't think we'll get it in the upcoming 3.11 release; Pablo is already working on getting it out.

**Comment by erlend-aasland** [comment]
> @jiangwen365, I don't think we'll get it in the upcoming 3.11 release; Pablo is already working on getting it out.

Sorry, the last bug-fix 3.11 release is just out now, and the 3.11 branch is now only accepting security fixes. This means the bundled SQLite won't be updated unless there is a pressing security need.

**Comment by jiangwen365** [comment]
> > @jiangwen365, I don't think we'll get it in the upcoming 3.11 release; Pablo is already working on getting it out.
> 
> Sorry, the last bug-fix 3.11 release is just out now, and the 3.11 branch is now only accepting security fixes. This means the bundled SQLite won't be updated unless there is a pressing security need.

Many thanks! I have already moved my all production code to Python 3.12 since 3.12.1 came out. Was thinking many people were still using Python 3.11, and didn't realize 3.11 is already in security fix only status, while this sqlite version is actually a new feature release.

**Comment by erlend-aasland** [comment]
The Windows and macOS installers are now updated to use SQLite 3.45.3. The 3.12 backport for macOS is in flight, and Mariusz is working on the Windows backport.
