### ISSUE TITLE
unittest: hide `run` method

### ISSUE THREAD

**Issue by bullgom** [python/cpython#115014]
# Feature or enhancement

### Proposal:

I propose to change the name of the method `run` of class `unittest.TestCase` to `_run` or anything that hides it from users.

Without knowing that there is a method `run` already defined on the class, I defined one. However, when I run the test on vscode test explorer as debug mode, it outputs:
```
Error in sys.excepthook:

Original exception was:
```
Now, I can't post the code that reproduces the above problem exactly because it is company code.

But the following is similar:
```python
import unittest as ut

class MyTestCase(ut.TestCase):
    def test(self) -> None:
        with open("hello.txt", "w") as file:
            self.run(file)

    def run(self, file) -> None:
        pass
```
would recognize 0 tests and finish as OK. And it does not give any hint that I shouldn't have overriden the `run` method.

### Has this already been discussed elsewhere?

No response given

**Comment by gaogaotiantian** [comment]
The method is clearly [documented](https://docs.python.org/3/library/unittest.html#unittest.TestCase.run) so it's not a secret. When you inherit a class, overwritting its documented method will have an effect, that's just true to all classes. Also, the method is public as the users can use the method to **run** their tests. I don't see any reason to change the name - it breaks backward compatibility and it does not quite make sense. Also the workaround is really simple - just don't name your method `run` :)

**Comment by AlexWaygood** [comment]
@gaogaotiantian is correct — we wouldn't be able to remove this public API without a long and painful deprecation period. I don't think there's really a strong enough justification for that here

**Comment by bullgom** [comment]
> The method is clearly [documented](https://docs.python.org/3/library/unittest.html#unittest.TestCase.run) so it's not a secret. When you inherit a class, overwritting its documented method will have an effect, that's just true to all classes. Also, the method is public as the users can use the method to **run** their tests. I don't see any reason to change the name - it breaks backward compatibility and it does not quite make sense. Also the workaround is really simple - just don't name your method `run` :)

Sorry for lack of the will to read the docs. I always used the vscode's test explorer, so I never got to really use the `run` method by myself explicitly.
