### ISSUE TITLE
ModuleNotFoundError: _sqlite3

### ISSUE THREAD

**Issue by eightween** [python/cpython#115040]
# Bug report

### Bug description:

I could not find any appropriate issues addressing this, this may be a duplicate or side-relevant concern. 3.12 version attempts to import `_sqlite3` from `sqlite3.dbapi2`, causing a module resolution error. Below is the traceback:

```
...
  File "/home/18/.pyenv/versions/3.12.0/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/home/18/.pyenv/versions/3.12.0/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

**Comment by sobolevn** [comment]
Can you please share exact Linux and Windows versions?
How did you configure and build Python?
Have you tried `3.12.1`?

**Comment by erlend-aasland** [comment]
I would guess this is an issue with pyenv and/or its configuration/setup.

**Comment by terryjreedy** [comment]
`import _sqlite3` works in both 3.11.7 and 3.12.1 installed from python.org.
