### ISSUE TITLE
Argument Clinic does not check for errors in `PyBuffer_FillInfo` in generated code

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#115026]
# Bug report

AC generates: 
- https://github.com/python/cpython/blob/39ec7fbba84663ab760853da2ac422c2e988d189/Modules/clinic/_codecsmodule.c.h#L300
- https://github.com/python/cpython/blob/39ec7fbba84663ab760853da2ac422c2e988d189/Modules/clinic/_codecsmodule.c.h#L1102
- https://github.com/python/cpython/blob/39ec7fbba84663ab760853da2ac422c2e988d189/Modules/clinic/_codecsmodule.c.h#L1178
- https://github.com/python/cpython/blob/39ec7fbba84663ab760853da2ac422c2e988d189/Modules/clinic/_codecsmodule.c.h#L1647
- https://github.com/python/cpython/blob/39ec7fbba84663ab760853da2ac422c2e988d189/Modules/clinic/_ssl.c.h#L1300

However, `PyBuffer_FillInfo` can raise errors and return `-1` on multiple occasions, so it is not safe to not check for it.

I have a PR ready.

### Linked PRs
* gh-115027

**Comment by erlend-aasland** [comment]
Thanks!
