### ISSUE TITLE
unittest.mock.create_autospec does not respect wraps

### ISSUE THREAD

**Issue by infohash** [python/cpython#115074]
https://github.com/python/cpython/blob/13eb5215c9de9dd302f116ef0bca4ae23b02842b/Lib/unittest/mock.py#L2704-L2705

```python
from unittest import mock

import pytest


class MyClass:
    def my_func(self):
        raise ValueError


@pytest.mark.xfail
def test_my_func_with_autospec():
    my_func = mock.create_autospec(spec=MyClass.my_func, wraps=MyClass.my_func)
    with pytest.raises(ValueError):
        assert my_func(MyClass())


def test_my_func_without_autospec():
    my_func = mock.Mock(spec=MyClass.my_func, wraps=MyClass.my_func)
    with pytest.raises(ValueError):
        assert my_func(MyClass())
```
Should be run as is.

> wraps: Item for the mock object to wrap. If wraps is not None then calling the Mock will pass the call through to the wrapped object (returning the real result). Attribute access on the mock will return a Mock object that wraps the corresponding attribute of the wrapped object (so attempting to access an attribute that doesn’t exist will raise an [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError)).

**Comment by terryjreedy** [comment]
@infohash Please check if your issue is the same as  #75988.

**Comment by infohash** [comment]
Yes, it is. Closing as duplicate.
