### ISSUE TITLE
Add pystats counter for invalidated executors

### ISSUE THREAD

**Issue by mdboom** [python/cpython#115168]
# Feature or enhancement

### Proposal:

As discussed [in an investigation into why some pystats are surprising](https://github.com/faster-cpython/ideas/issues/652#issuecomment-1934168807), I suggested that it would be useful to have counts for when executors are invalidated (for example, when the globals or builtins dictionary changes).

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-115169

**Comment by hugovk** [comment]
The PR has been merged, OK to close or is there more to do?

**Comment by hugovk** [comment]
Triage: the linked PR is merged, can this be closed?

**Comment by mdboom** [comment]
Yes.
