### ISSUE TITLE
vcruntime140_threads.dll is erroneously vendored when building with Visual Studio 17.8

### ISSUE THREAD

**Issue by adang1345** [python/cpython#115167]
# Bug report

### Bug description:

As described in https://devblogs.microsoft.com/cppblog/c11-threads-in-visual-studio-2022-version-17-8-preview-2/, Visual Studio 17.8 introduced support for C11 threads, provided by `vcruntime140_threads.dll`. When I use the `Tools\msi\buildrelease.bat` script to build Python 3.12.2 on Windows using this Visual Studio version, the `vcruntime140_threads.dll` ends up in the Python distribution. For instance, the `python-3.12.2-embed-amd64.zip` file that is built contains the file `vcruntime140_threads.dll` at its root.

I traced the cause of this to https://github.com/python/cpython/blob/17689e3c41d9f61bcd1928b24d3c50c37ceaf3f2/PCbuild/pyproject.props#L253 which copies all DLLs matching the pattern `vcruntime*.dll` from the Visual C++ runtime directory. Starting with Visual Studio 17.8, this directory (which for me is `C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Redist\MSVC\14.38.33135\x64\Microsoft.VC143.CRT`) contains the file `vcruntime140_threads.dll`.

Given that we aren't using C11 threads on Windows, I think we should change that line to
`<VCRuntimeDLL Include="$(VCRedistDir)\Microsoft.VC*.CRT\vcruntime*.dll" Exclude="$(VCRedistDir)\Microsoft.VC*.CRT\vcruntime*_threads.dll" />` to ensure that the file is not included in the Python distribution. I can make a PR for this change.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-115176
* gh-115186
* gh-115187

**Comment by zooba** [comment]
Sounds good to me. It shouldn't be getting into the final installers, as we take the vcruntime from [this branch](https://github.com/python/cpython-bin-deps/tree/vcruntime) for release, but better to explicitly leave it out for now.

**Comment by zooba** [comment]
Thanks! The backports should auto-merge, so closing this as complete. I'll keep an eye on them in case they fail for some reason.
