### ISSUE TITLE
What's the difference?

### ISSUE THREAD

**Issue by Bigtoyka** [python/cpython#115129]
# Bug report

### Bug description:

1) 1 variant
```python
dig = int(input())
a = 1
while dig > 0:
    a = a * dig % 10
    dig = dig // 10
print(a)
```
2) 2 variant
```python
dig = int(input())
a = 1
while dig > 0:
    a *= dig % 10
    dig = dig // 10
print(a)
```
What's the difference? why is the code executed differently, even though the syntax is the same
dig = 415
first variant answer 0
second variant answer 20

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ruslansenatorov** [comment]
@Bigtoyka ок

**Comment by hugovk** [comment]
This is the issue tracker for bugs and new features in CPython, please ask questions like this in the help category of Discourse: https://discuss.python.org/c/users/7

**Comment by Bigtoyka** [comment]
> Hello! This happens because `a = a * dig % 10` and `a *= dig % 10` is not the same operations. The second one means calculate `dig % 10`, multiply this by `a` and then assign result in `a` variable.

the first one means calculate dig % 10,  multiply this by a and then assign result in a variable too. why u say, is not same. this is `a *= dig % 10` syntax sugar. No?

**Comment by hugovk** [comment]
Please ask at https://discuss.python.org/c/users/7.
