### ISSUE TITLE
Access all (even duplicate) annotations when preparing a class using a Metaclass

### ISSUE THREAD

**Issue by kohlrabi** [python/cpython#115144]
# Feature or enhancement

### Proposal:

I am in the process of experimenting with building my own DSL using Python and metaclasses. One of the ideas is to use annotations for type definitions (with actual semantics). Additionally it should be possible to use the same name twice within a definition:

```python
class Meta(type):
    class PrintPrepare(dict):
        def __setitem__(self, key, value):
            print(key, value)
            super().__setitem__(key, value)

    @classmethod
    def __prepare__(cls, name, *bases):
        return Meta.PrintPrepare()

    def __new__(cls, name, bases, dct):
        print(dct)
        new_cls = type.__new__(cls, name, bases, dct)
        return new_cls

class A(metaclass=Meta):
    a: int
    b: float
    c: float
    b: int
```
My idea was to use the metaclass `__prepare__` method to create a dict to access both the name and annotation, but alas the annotations are not passed to the dict being created, the `__setitem__` method only sees an empty `__annotations__` dict. In the `__new__` method of the metaclass the `dct` has all of `__annotations__`, though, but since it is a `dict` the duplicates are removed. To my knowledge thus there is no way to access the annotated fields field-by-field.

My workaround right now to handle multiple fields with the same name is to use assignment instead of annotation, then all fields are passed to `__getitem__` with key and value and I can handle the duplicate.

```python
class A(metaclass=Meta):
    a = int
    b = float
    c = float
    b = int
```

It would be a useful feature (to me) if the annotated fields were exposed field-by-field to the dict created in `__prepare__`, or if a separate `__prepare_annotations__` method was available. Does such a method already exists? 

Then I could use both annotations and assignments to provide different functionality.

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
You should bring this up on https://discuss.python.org/c/ideas/6

**Comment by MechanicPig** [comment]
You can do this by returning `dict(__annotations__=Meta.PrintPrepare())` instead of `Meta.PrintPrepare()` in your `__prepare__`.

**Comment by ronaldoussoren** [comment]
I don't think there's something to do here. 

The reason the @kohlrabi  sees an empty dict for `__annotations__` is that at runtime the `__annotations__` dict is added as needed and then updated. As @MechanicPig notes you can record all updates to the `__annotations__` dict by adding a suitable `__annotations__` value in the `__prepare__` method, e.g.:

```python
class Meta(type):
    class PrintPrepare(dict):
        def __setitem__(self, key, value):
            print("cls", key, value)
            super().__setitem__(key, value)

    class Annotations(dict):
        def __setitem__(self, key, value):
            print("anno", key, value)
            super().__setitem__(key, value)

    @classmethod
    def __prepare__(cls, name, *bases):
        return Meta.PrintPrepare({"__annotations__": Meta.Annotations()})

    def __new__(cls, name, bases, dct):
        print(dct)
        new_cls = type.__new__(cls, name, bases, dct)
        return new_cls

class A(metaclass=Meta):
    a: int
    b: float
    c: float
    b: int
```

This will print:

```
cls __module__ __main__
cls __qualname__ A
anno a <class 'int'>
anno b <class 'float'>
anno c <class 'float'>
anno b <class 'int'>
{'__annotations__': {'a': <class 'int'>, 'b': <class 'int'>, 'c': <class 'float'>}, '__module__': '__main__', '__qualname__': 'A'}
```

A different API to accomplish this would require discussion on discuss.python.org and likely a PEP.
