### ISSUE TITLE
Using / as a value for a parameter becomes a path after parse_args()

### ISSUE THREAD

**Issue by ewongbb** [python/cpython#115161]
# Bug report

### Bug description:

I am unsure if this is a python 3.11.3 argparse bug,  or a python 3.11.3 bug under Git Bash(from the git 2.41.0.3 installation)
(I'm guessing it's the latter)

I have Python 3.11.3 installed under a Git Bash (via the python 3.11 installation exe file to a path under j:\git) on a Windows 8.1 system.

I was fixing one of my scripts that allows specifying a string for an argument, i.e. -d testing,   but the string could also be a /, i.e. -d /

here is a minimal reproducible example.
```python

import argparse

def get_options():
    opts = argparse.ArgumentParser(description="get options")
    opts.add_argument("-d",
                                   help="specify dir",
                                   dest="use_dir",
                                   default=None,
                                   type=str)
    return opts.parse_args()


def main():
    opts = get_options()
    if opts.use_dir is not None:
        print("use_dir : %s" % opts.use_dir)

if __name__ == "__main__":
    main()
    
```

When I run the above script (in a git bash prompt), I get: 

use_dir: J:/git/

However, when I run the above script in a normal command prompt, I get:

use_dir: /

I tried the above script in a python 3.6.8  (I know, it's not supported now, but just for fun) I get:

use_dir: /

Unfortunately, I can't run python interactively under Git Bash as python just hangs.
However, I can run python in a command prompt and I get the following:

```
import argparse

opt = argparse.ArgumentParser(description="get opts")
opt.add_argument("-d", help="get dir", dest="use_dir", default=None, type=str)
p = opt.parse_args(["-d", "/'])
print(p)
```
I get:
Namespace(use_dir='/')

Any clarifications appreciated.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, Windows

**Comment by serhiy-storchaka** [comment]
Could you print `sys.argv`?

**Comment by ewongbb** [comment]
> Could you print `sys.argv`?

yes, it's a confirmation that git bash is screwing up the parsing.  Here's what I get:

with the above code + the following lines below ```print(opts.use_dir)```

```
   print(sys.argv)
```
I get:

```
J:/git/
['t2.py', '-d', 'j:/git/']

```

So, yeah,  I guess I was barking up the wrong tree.  Sorry about that.

**Comment by vadmium** [comment]
FYI in MSYS (used by Git Bash I believe) I think you can double the slash to escape this absolute path translation behaviour

**Comment by ericvsmith** [comment]
> FYI in MSYS (used by Git Bash I believe) I think you can double the slash to escape this absolute path translation behaviour

That is some unpleasant behavior in MSYS!
