### ISSUE TITLE
threading.Lock() and print() not always works

### ISSUE THREAD

**Issue by mhechthz** [python/cpython#115170]
# Bug report

### Bug description:

I start in a more complex application a multithreaded subroutine that calls a dll function and before giving the result back calls:
```python
with lock: 
        print(f"QUERY '{query_id}' finished ...",flush=True)
```
What I get on console is (sometimes):
```
QUERY 'erste' finished ...QUERY 'letzte' finished ...

QUERY 'g61kstrk_pos' finished ...
```
i.e. the next print() is called before the previous print() sets the linebreak `'\n'`.

It doesn't matter if im using `lock = threading.Lock()` or `lock = threading.Semaphore()`

If I do the following it seems to work as expected:

```python
with lock: 
        print(f"QUERY '{query_id}' finished ...\n",end="",flush=True)
```

Im still on Python 3.11.7 with the application, but maybe the reason for this bug is also in Python 3.12

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
Are you sure that all your threads use the same lock?

**Comment by mhechthz** [comment]
Yes, the lock is generated before calling the corresponding subroutine. Mainly this:

```python

...
with concurrent.futures.ThreadPoolExecutor() as executor:
        ...
        futures = {}
        for q in queries:
            ...
            lock = threading.Lock()
            futures[id] = executor.submit(_parallelRunQuery,lock,query_id,db_id,query,dbUser,dbPass,verbose)

...

def _parallelRunQuery(print_lock,query_id,db_id,query,dbUser=None,dbPass=None,verbose=False):
    result = ...
    with print_lock: 
        print(f"QUERY '{query_id}' finished ...\n",end="",flush=True)
    return result
```

**Comment by serhiy-storchaka** [comment]
So you used different locks.

**Comment by mhechthz** [comment]
![image](https://github.com/python/cpython/assets/37075144/7c19cf4f-ba38-40e2-9ee3-83f7d64561c9)
Thank you for showing me my mistake.
