### ISSUE TITLE
Typo in pickletools doc for long4 opcode

### ISSUE THREAD

**Issue by Legoclones** [python/cpython#115146]
# Documentation

The `doc` parameter for the `LONG4` opcode in [pickletools says](https://github.com/python/cpython/blob/ef3ceab09d2d0959c343c662461123d5b0e0b64b/Lib/pickletools.py#L1256):
```py
doc="""Long integer using found-byte length.

      A more efficient encoding of a Python long; the long4 encoding
      says it all."""
```

It should say `four-byte length` instead of `found-byte length`. 

### Linked PRs
* gh-115148
* gh-115155
* gh-115156

**Comment by Eclips4** [comment]
Hello!
Yes, there should be `four-byte length`. Would you like to send a PR with fix?

**Comment by Legoclones** [comment]
PR is located [here](https://github.com/python/cpython/pull/115148). Never done this before so feel free to change whatever needs to be changed!
