### ISSUE TITLE
Add argparse.ArgumentParser.get_subparsers() method

### ISSUE THREAD

**Issue by keithpenney** [python/cpython#115150]
# Feature or enhancement

### Proposal:

I have been writing a lot of hierarchical CLI scripts lately and have been noodling on ways to avoid replicating `argparse` code in every script.  I came across a use case which warrants the ability to get the `_SubParsersAction()` instance (returned by `parser.get_subparsers()`) from an existing `ArgumentParser` object.

## Example Usage Case

__foo.py__ exposes only to the "foo" CLI subcommand
```python
# =============== [foo.py] ===============
import argparse
def doFoo(args):
    print("doFoo")

def ArgumentParser(**kwargs):
    parser = argparse.ArgumentParser(**kwargs)
    parser.set_defaults(handler=lambda x: parser.print_help())
    subparsers = parser.add_subparsers(help="Subcommands")
    parserFoo = subparsers.add_parser("foo")
    parserFoo.set_defaults(handler=doFoo)
    return parser

if __name__ == "__main__":
    parser = ArgumentParser(description="The Foo Script")
    args = parser.parse_args()
    args.handler(args)
```

__bar.py__ exposes both the "foo" and "bar" CLI subcommands
```python
# =============== [bar.py] ===============
def doBar(args):
    print("doBar")

if __name__ == "__main__":
    import foo
    parser = foo.ArgumentParser(description="The Bar Script")

    # NOTE this hack is required to make the script run.  Will be eliminated with new method
    parser.get_subparsers = lambda: parser._subparsers._group_actions[-1]

    subparsers = parser.get_subparsers()
    parserBar = subparsers.add_parser("bar")
    parserBar.set_defaults(handler=doBar)
    args = parser.parse_args()
    args.handler(args)
```

## Implementation
The existing `ArgumentParser` API only raises two types of Exceptions, none of which apply here.  There are also several functions who happily return `None` when appropriate, so I decided to do that with this new function.  If you'd rather raise an Exception, be my guest.

```python
# Adding this simple method which returns the same object returned by "add_subparsers()"
# if it exists (None otherwise).
class ArgumentParser(_AttributeHolder, _ActionsContainer):
    #...
    def get_subparsers(self):
        if self._subparsers is None:
            return None
        if not hasattr(self._subparsers, '_group_actions'):
            return None
        if len(self._subparsers._group_actions) > 0:
            return self._subparsers._group_actions[-1]
        return None
```

I'm submitting a pull request with this addition and commensurate additions to `Lib/test/test_argparse.py` with a few assertions to test this simple feature.

If anyone can suggest a better approach, I'm certainly interested.  But this harmless enhancement doesn't appear to have many drawbacks in my estimation.  Please enlighten me if you believe otherwise.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-115151

**Comment by serhiy-storchaka** [comment]
I am not sure that this fits into the `argparse` design. Currently there are a lot of `add_*` methods, but there are no `get_*` methods (the only exception is `get_default()`, but it returns the default for the specified variable, not all defaults). There may even not be a single collection of things to use in the `get_*` method. Adding `get_*` methods may limit future development of `argparse`.

This would also complicate the `argparse` API which is already complicated.

If you need a list of subparsers, just maintain a list in your program and add new subparsers to it.

**Comment by serhiy-storchaka** [comment]
Closing because it doesn't fit very well with the overall design.
