### ISSUE TITLE
Possible NULL dereference in `getpath_joinpath()`

### ISSUE THREAD

**Issue by dTenebrae** [python/cpython#115136]
# Bug report

### Bug description:

```python
    wchar_t **parts = (wchar_t **)PyMem_Malloc(n * sizeof(wchar_t *));
    memset(parts, 0, n * sizeof(wchar_t *));
```
The return value of `PyMem_Malloc` not checked for NULL and dereferenced after it in memset()

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-115137
* gh-115157
* gh-115158

**Comment by hugovk** [comment]
Closing as the PR has been merged and backported. Thanks!
