### ISSUE TITLE
Typo in "What’s New In Python 3.13", `file:/` missing another trailing slash

### ISSUE THREAD

**Issue by edgarrmondragon** [python/cpython#115114]
# Documentation

The example URI prefix is missing a trailing slash:

<blockquote>
<p>Add <a class="reference internal" href="../library/pathlib.html#pathlib.Path.from_uri" title="pathlib.Path.from_uri"><code class="xref py py-meth docutils literal notranslate"><span class="pre">pathlib.Path.from_uri()</span></code></a>, a new constructor to create a <a class="reference internal" href="../library/pathlib.html#pathlib.Path" title="pathlib.Path"><code class="xref py py-class docutils literal notranslate"><span class="pre">pathlib.Path</span></code></a>
object from a ‘file’ URI (<code class="docutils literal notranslate"><span class="pre">file:/</span></code>).
(Contributed by Barney Gale in <a class="reference external" href="https://github.com/python/cpython/issues/107465">gh-107465</a>.)</p>
</blockquote>

https://github.com/python/cpython/blob/11ac6f5354ec7a4da2a7e052d27d636b5a41c714/Doc/whatsnew/3.13.rst#L394

### Linked PRs
* gh-115115

**Comment by barneygale** [comment]
Thank you for reporting + fixing!
