### ISSUE TITLE
regrtest: add --bisect option to run test.bisect_cmd on failed tests

### ISSUE THREAD

**Issue by vstinner** [python/cpython#115122]
When running tests with `-R 3:3` to check for a reference leak, it's not always obvious which tests lead to the leak. I propose to add a `--bisect` option which runs the `-m test.bisect_cmd` command to bisect failing tests.

### Linked PRs
* gh-115123

**Comment by vstinner** [comment]
I wrote this issue to debug issue gh-115124: AMD64 Windows11 Bigmem 3.x: test_bigmem failed with !_Py_IsImmortal(FROM_GC(gc)) assertion error.

**Comment by hugovk** [comment]
Closing because the PR has been merged. Please re-open if there's more needed here. Thanks!
