### ISSUE TITLE
``test_queue`` times out

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#115258]
# Bug report

### Bug description:

See https://github.com/python/cpython/actions/runs/7856342409/job/21439020143?pr=115257 for more details.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-115269
* gh-115361
* gh-115898
* gh-115940

**Comment by terryjreedy** [comment]
This has blocked CI from passing for a least one PR,  #115250 (now rerunning), but not for another, #115253.

**Comment by Eclips4** [comment]
> This has blocked CI from passing for a least one PR, #115250 (now rerunning), but not for another, #115253.

Also seems this issue is not specific to x86, another one fail on x64: https://github.com/python/cpython/pull/115232

**Comment by Eclips4** [comment]
Looks related to #104750

**Comment by terryjreedy** [comment]
Since our workflow does not allow over-riding CI failure from unrelated test failures, I think test_queue.PyPriorityQueueTest.test_shutdown_all_methods_in_many_threads should be skipped until fixed.

**Comment by gvanrossum** [comment]
Shall we just revert gh-104750? It seems I merged it prematurely, see https://github.com/python/cpython/pull/104750#issuecomment-1935449280.

**Comment by gvanrossum** [comment]
If you want to just revert the offending PR, gh-115265 is a full revert (it's currently marinating in CI).

If someone wants to volunteer to create an alternative PR that just disables that test (ideally only when Windows and free-threading are detected) that would be even better.

**Comment by colesbury** [comment]
I'll look into this on Monday. Here's a PR that temporarily skips this test on the free-threaded WIndows build, if we prefer that over reverting the PR: https://github.com/python/cpython/pull/115269

**Comment by colesbury** [comment]
It looks like the test also sometimes times out on the default Windows build. In this job it timed out after 10 minutes, was re-run, and then passed: https://github.com/python/cpython/actions/runs/7859086848/job/21444802020?pr=115269

**Comment by gvanrossum** [comment]
> It looks like the test also sometimes times out on the default Windows build. In this job it timed out after 10 minutes, was re-run, and then passed: https://github.com/python/cpython/actions/runs/7859086848/job/21444802020?pr=115269

Oh, then just skip these tests on Windows.

**Comment by gvanrossum** [comment]
I'll now commandeer this issue to track fixes to the offending tests. Hopefully @EpicWink has some ideas.

**Comment by itamaro** [comment]
going to remove the free-threading label since the current theory is that this isn't free-threading specific.

**Comment by brandtbucher** [comment]
We're seeing timeouts for `test_queue` on some AArch64 JIT builds too: https://github.com/python/cpython/actions/runs/7870838905?pr=115248

**Comment by gvanrossum** [comment]
Okay, just disable those two tests for all platforms. (I'm not in a position to do it myself right now.)

**Comment by Eclips4** [comment]
> Okay, just disable those two tests for all platforms. (I'm not in a position to do it myself right now.)

Done in #115361

**Comment by vstinner** [comment]
What's the status? The tests are skipped for 1 month. If nobody knows how to fix it, I would like to suggest to revert the change which introduced the unstable tests.

**Comment by gvanrossum** [comment]
> What's the status? The tests are skipped for 1 month. If nobody knows how to fix it, I would like to suggest to revert the change which introduced the unstable tests.

Funny you should ask. There is a fix by the original authors (gh-115940), it just requires review and some validation. I don't want to rush things. Could you maybe review that PR?

**Comment by gvanrossum** [comment]
The updated tests have been pushed.
