### ISSUE TITLE
About adding a multiset feature in python like cpp where we can append,delete,search,delete first element 

### ISSUE THREAD

**Issue by rushikeshkotkar04** [python/cpython#115287]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
```

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
Hello!
You can create a topic on https://discuss.python.org/c/ideas/6 for further discussion.
Now I'm going to close this.

**Comment by terryjreedy** [comment]
Note that Python has a multiset class in collections.counter, so you might need to just propose an enhancement to that.

**Comment by rishiko** [comment]
How to propose a enhancement it is much needed change in python.

**Comment by rishiko** [comment]
Actually that counter is not efficient and not sorted by default, have a
look on counter for multiset , i have a better one.
