### ISSUE TITLE
Better error message for string formatting 

### ISSUE THREAD

**Issue by Agent-Hellboy** [python/cpython#115224]
# Feature or enhancement

### Proposal:

what about throwing an exception as `argument is provided without any format specifier` for scenarios like below` 
```py
str = "jkg" 
ch = "ft"
new_str = str % ch 
```

```py

➜  cpython git:(main) ✗ ./python.exe l.py
Traceback (most recent call last):
  File "/Users/agent-hellboy/cpython/l.py", line 5, in <module>
    s = l % (p,k)
TypeError: argument is provided without any format specifier
```

btw, what should we check in the below function to achieve this? 
https://github.com/python/cpython/blob/5a173efa693a053bf4a059c82c1c06c82a9fa8fb/Objects/unicodeobject.c#L14507

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ericvsmith** [comment]
I suggest you discuss this on https://discuss.python.org/c/ideas/6 first. I don't know how disruptive this change would be, and maybe someone has an idea for better wording.

**Comment by Agent-Hellboy** [comment]
okay, btw, do people consume exceptions from https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_Format

**Comment by ericvsmith** [comment]
In my experience, with the question "do users of python do X?", even if X seems an unlikely or useless thing to do, the answer is "yes".

**Comment by Agent-Hellboy** [comment]
people doesn't show much interest , I will close it.
