### ISSUE TITLE
Tk doesn't work well with custom keyboard layouts

### ISSUE THREAD

**Issue by Mehdical-Man** [python/cpython#115230]
# Bug report

### Bug description:

Note: If `AltGr` isn't on your keyboard, press `Ctrl` + `Alt`. It does the same thing.
[Even though this issue is closed, it's still a problem](https://github.com/python/cpython/issues/66598)
## Problem with AltGr (Ctrl + Alt)
On my custom keyboard (created with [MSKLC](https://www.microsoft.com/en-gb/download/details.aspx?id=102134)), `ẞ` (U+1E9E, LATIN CAPITAL LETTER SHARP S) is assigned `AltGr` +  `Shift` + `S`. When I try to type it using my custom keyboard, it gets replaced with `?`.
```py
>>> weiß = "#ffffff" # Lowercase "ẞ" (ß) works though.
>>> STRA?E = "BERLIN" # Supposed to be STRAẞE 
```
It works correctly in other software like Notepad++.
### What is a dead key?
A dead key modifies the next character typed. 
Example: typing `` ` `` then `e` gives `è`   (`` ` `` is the dead key.) This sequence works in IDLE.
Some characters work as dead keys, but others don't.
### Dead keys that work
Pressing `¨` (U+00A8, DIAERESIS), which is assigned `AltGr`  + `2`, then `e`, gives me `ë`.
### Dead keys that don't work
When I press `´` (U+00B4, ACUTE ACCENT), which is assigned `AltGr`  + `'`,  then `y`, I should get `ý`. Instead I get `y`.
It also works correctly in other software like Notepad++.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
Essentially a duplicate.  See #66598.
