### ISSUE TITLE
The typical initialization of PyMutex in its comment document cannot be compiled on Windows

### ISSUE THREAD

**Issue by aisk** [python/cpython#115304]
https://github.com/python/cpython/blob/2939ad02be62110ffa2ac6c4d9211c85e1d1720f/Include/internal/pycore_lock.h#L28-L29

But it cannot be compiled outside a function on Windows: https://github.com/python/cpython/actions/runs/7862752441/job/21452578591 with this error:

```
`3>D:\a\cpython\cpython\Modules\rotatingtree.c(19,16): error C2099: initializer is not a constant [D:\a\cpython\cpython\PCbuild\pythoncore.vcxproj]` 
```

Also check here https://github.com/python/cpython/pull/115301/commits/be0427fc6551fb861b9a52bf726eeb539fbb277c#diff-266bed9d854389a88ddd0696e9a225a2570559901edf0e909de43dd1f49ce80aR19 to see the usage and the compile error.

Change it to `PyMutex m = {0};` can resolve this issue.

### Linked PRs
* gh-115305

**Comment by terryjreedy** [comment]
I don't understand the links above.  `pycore_lock.h`, 28-29, are as listed, but have nothing obvious to do with commit [2939ad0](https://github.com/python/cpython/commit/2939ad02be62110ffa2ac6c4d9211c85e1d1720f) for a pydoc fix.  Neither do those lines have any obvious connections with the compile error in `        random_value *= 1082527;` in rotatingtree.c.  The build report is not obviously linked back to a particular PR.

**Comment by aisk** [comment]
Hi @terryjreedy the compile error in the link should be: 

`3>D:\a\cpython\cpython\Modules\rotatingtree.c(19,16): error C2099: initializer is not a constant [D:\a\cpython\cpython\PCbuild\pythoncore.vcxproj]` (I'll update this to the first comment, sorry I forgot it yesterday)

And change the usage to `PyMutex m = {0};` got compile passed on Windows, see the commits in https://github.com/python/cpython/pull/115301

commit [2939ad0](https://github.com/python/cpython/commit/2939ad02be62110ffa2ac6c4d9211c85e1d1720f) have no connections to this issue, I guess you mixed this with other issues?
