### ISSUE TITLE
Add documentation to the pystats output (from summarize_stats.py)

### ISSUE THREAD

**Issue by mdboom** [python/cpython#115362]
# Feature or enhancement

### Proposal:

The output from `summarize_stats.py` ([example here](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20240210-3.13.0a3%2B-4821f08-PYTHON_UOPS/bm-20240210-azure-x86_64-python-4821f08674e290a396d2-3.13.0a3%2B-4821f08-pystats.md)) isn't terribly self-explanatory.  Adding more text (and tooltips) would be very helpful in making it more obvious.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-115365

**Comment by hugovk** [comment]
Closing because the PR's been merged. Thanks!
