### ISSUE TITLE
bytearray.extend: Misleading error message

### ISSUE THREAD

**Issue by smurfix** [python/cpython#115323]
### Bug description:

```python
b=bytearray(b"abc")
b.extend('def')
```
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' object cannot be interpreted as an integer```
```
… except that `bytes.extend` doesn't even accept integers as arguments; the error refers to the first element of the string, which happens also to be a string in Python. Meh.

Could CPython please complain about requiring the string to be encoded instead?

### CPython versions tested on:

main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-115332
* gh-115894
* gh-115895

**Comment by terryjreedy** [comment]
Behavior same back to 3.11.  The currently message is erroneous enough that backporting should be considered.

**Comment by terryjreedy** [comment]
After adding the backport tags and having them start, I changed my mind and closed them.
