### ISSUE TITLE
Refleaks in free-threading build on macOS

### ISSUE THREAD

**Issue by encukou** [python/cpython#115326]
# Bug report

The ARM64 MacOS M1 Refleaks NoGIL 3.x buildbot started detecting leaks in quite a few tests (`test_largefile`, `test_os`, `test_pickle`, `test_posix`, `test_shutil`), see e.g. https://buildbot.python.org/all/#/builders/1368/builds/182

Marking as release blocker since a stable buildbot is failing.
(But, freethreading is still experimental, so I recommend to defer this; it doesn't need to block the alpha.)

**Comment by Eclips4** [comment]
Bisected to #115236

**Comment by encukou** [comment]
Let's continue on the issue that caused this: #87804
