### ISSUE TITLE
RFE: please enable discussions tab in this repo

### ISSUE THREAD

**Issue by kloczek** [python/cpython#115381]
# Feature or enhancement

### Proposal:

IMO it would be really good to enable discussions tab in this repo.
For:
- general discussions
- possibility to convert issue thickets into discussions.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
We already have a discussion forum at https://discuss.python.org/. Adding another forum would likely lead to fragmentation.

**Comment by zware** [comment]
Agreed with Jelle; closing.

If you really want to pursue this, starting a discussion in the existing forum is the correct route to take.

**Comment by kloczek** [comment]
> We already have a discussion forum at https://discuss.python.org/. Adding another forum would likely lead to fragmentation.

But this is not integrated with github and not allows converting issue tickets to discussions.
