### ISSUE TITLE
Code snippets in dark theme are unreadable

### ISSUE THREAD

**Issue by raiyankamal** [python/cpython#115349]
# Documentation

When python docs are viewed in dark theme, code snippets are put against a light colour background. This makes white letters unreadable. Please see attached screenshot.

![Screenshot 2024-02-09 at 4 38 35 PM](https://github.com/python/cpython/assets/5496324/023dd5f4-a092-4f71-9ae5-32c27f42e404)

This screenshot was taken at: https://docs.python.org/3.8/library/csv.html

Steps to reproduce:
1. Visit https://docs.python.org/3.8/library/csv.html
2. Select theme "Dark" from the drop down menu in the top right corner.
3. Scroll to see any code snippet.

### Linked PRs
* gh-115351
* gh-115404

**Comment by hugovk** [comment]
> The minimal fix is probably to pin the theme to an older version that still works with Sphinx 2 (and no dark theme).

I've transferred this back to the CPython repo to use the issue number for this.

**Comment by hugovk** [comment]
PRs merged, let's close this.

The 3.8 and 3.9 docs will be deployed during their next releases, which as luck would have it, should be [this week](https://discuss.python.org/t/python-3-12-2-and-3-11-8-released/45268).

**Comment by terryjreedy** [comment]
3.8.19 and 3.9.19 were released March 19, 2024.  However, accessing the 3.8 and 3.9 docs displays doc for 3.8.18 and 3.9.18, not the new releases, and the problems remain.   #118199 is the new issue.
