### ISSUE TITLE
Replace STACK.append with STACK.push in Doc/library/dis.rst

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#115307]
# Documentation

I asked about this on [discuss.python.org](https://discuss.python.org/t/dis-py-stack-append-vs-stack-push/45330) but got no responses. Since the bagpipe didn't say "no" I'm opening a ticket and will create a PR.

Maybe things have changed since I last thought much about stacks, but conceptually, I believe their two primary operations are "push" and "pop". Somewhere along the way, several instances of `STACK.append` showed up in the descriptions of operations in the `dis` module documentation. I think they should be `STACK.push` instead.

### Linked PRs
* gh-115309

**Comment by gaogaotiantian** [comment]
I think the reason it uses `append` is because

> In the following, We will refer to the interpreter stack as STACK and describe operations on it as if it was a Python list. The top of the stack corresponds to STACK[-1] in this language.

Yes, `pop` and `push` are obvious operations for stack, but Python users might be more familiar with `append`. I'm not +1 or -1 for the change, but if we change from `append` to `push`, the line above needs to be changed as well.

**Comment by smontanaro** [comment]
Now that most push operations are given as `STACK.push`. I prefer to use the common language. That makes it easier to compare the docs with non-Python sources (data structure textbooks, for example).

**Comment by terryjreedy** [comment]
The purpose of discuss is to get support.  You got none.  I just added
>I oppose both the change and the reason given for doing it. When you have a real need for a non-auto backport, I would be willing to help.

Append is the way to push to a python list and since some of the opcodes are defined in terms of python code, append it should be.  In these examples, STACK is actually treated as a list, with indexing, and not just indexing, but Python's negative indexing.  It is not as a stack.  Stacks do does not have indexing, let alone negative indexing.

**Comment by smontanaro** [comment]
I even tagged the two people `git blame` told me were responsible for both the `STACK.append` and `STACK.push` lines in `dis.rst` but got no response (from anyone), despite discuss telling me it's now been viewed 176 times (probably more like 150 when I created the PR).
