### ISSUE TITLE
Please expose Expat >=2.6.0 API function `XML_SetReparseDeferralEnabled`

### ISSUE THREAD

**Issue by hartwork** [python/cpython#115398]
# Feature or enhancement

### Proposal:

Hello CPython team! :wave: 

Expat 2.6.0 introduced a new [function `XML_SetReparseDeferralEnabled`](https://libexpat.github.io/doc/api/latest/#XML_SetReparseDeferralEnabled) that currently neither [`xml.parsers.expat.XMLParserType` of pyexpat](https://docs.python.org/3/library/pyexpat.html#xmlparser-objects) nor [`xml.etree.ElementTree.XMLParser` of ElementTree](https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.XMLParser) give access to it, so when some Python-based library or application finds themselves in a situation where toggling reparse deferral is beneficial or needed for their scenario in the future, they will not be able to do so with ease or at all.

Please note that this is a sibling ticket to #90949 in some sense and implementations could be combined or done in one go, potentially.

Also please note that…
- for [`xml.etree.ElementTree.XMLParser`](https://docs.python.org/3/library/xml.etree.elementtree.html#xmlparser-objects) a new method `def flush(self):` could be a reasonable API addition based on the idea https://github.com/python/cpython/pull/115138#issuecomment-1932444270 ;
- the same seems to apply to [`xml.sax.xmlreader.IncrementalParser`](https://docs.python.org/3/library/xml.sax.reader.html#xml.sax.xmlreader.IncrementalParser).

I cannot provide a pull request on the topic economically myself unfortunately, but I am happy to support any related efforts (including voice calls on the topic as needed). Thanks in advance!

Best, Sebastian

CC #90949
CC #115133

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-115623
* gh-116248
* gh-116268
* gh-116270
* gh-116272
* gh-116275
* gh-116278
* gh-116301
* gh-116411

**Comment by hartwork** [comment]
@gpshead @serhiy-storchaka I'm glad I could be of help, thanks for the review :pray:

**Comment by hroncok** [comment]
:warning: Linux distro maintainers.

Python built `--with-system-expat` with expat \>= 2.6 will require expat \>= 2.6 on runtime as well. If you updated to expat >= 2.6 and built Python with this fix, do not allow your users to update Python without updating expat as well, or they will get `undefined symbol: XML_SetReparseDeferralEnabled` from pyexpat (e.g. when using the venv module).

https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/7XHGWHBQDNFKNGSZTP44SSD6PQKZPG6C/

cc @mgorny  @danigm @mcepl @mitya57 @asottile

**Comment by danigm** [comment]
> ⚠️ Linux distro maintainers.
> 
> Python built `--with-system-expat` with expat >= 2.6 will require expat >= 2.6 on runtime as well. If you updated to expat >= 2.6 and built Python with this fix, do not allow your users to update Python without updating expat as well, or they will get `undefined symbol: XML_SetReparseDeferralEnabled` from pyexpat (e.g. when using the venv module).
> 
> https://lists.fedoraproject.org/archives/list/python-devel@lists.fedoraproject.org/thread/7XHGWHBQDNFKNGSZTP44SSD6PQKZPG6C/
> 
> cc @mgorny @danigm @mcepl @mitya57 @asottile

Thanks for the heads up. As far as I know this shouldn't be a problem for Tumbleweed because how it's updated, but for Leap is something to keep in mind.

**Comment by ReimarBauer** [comment]
On MSS it was reported 2.6.1 works and 2.6.2 doesn't.

**Comment by jamesdalg** [comment]
This is still a recurring issue, years on.
