### ISSUE TITLE
Changelog filter in the docs is broken

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#115317]
# Bug report

Long ago I wrote a script [to filter changelog entries](https://docs.python.org/3.10/whatsnew/changelog.html).

This worked until 3.10, but broke starting from 3.11:
* https://docs.python.org/3.10/whatsnew/changelog.html (see the inputbox at the top)
* https://docs.python.org/3.11/whatsnew/changelog.html (the inputbox is missing)

This is because JQuery was removed, probably when Sphinx was updated in:
* #99380 
* https://github.com/sphinx-doc/sphinx/issues/7405

Assuming that changelog filtering is still valuable, it should be rewritten using vanilla javascript.

### Linked PRs
* gh-115324
* gh-115372
* gh-115373

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/115324.
