### ISSUE TITLE
SystemError triggered while attempting to raise a DeprecationWarning

### ISSUE THREAD

**Issue by asottile-sentry** [python/cpython#115377]
# Bug report

### Bug description:

smallest reproduction I have:

```
python3.12 -m venv venv
venv/bin/pip install protobuf==4.21.6
venv/bin/python -Werror -c 'import google._upb._message'
```

this crashes with:

```console
$ python -Werror -c 'import google._upb._message'
DeprecationWarning: Type google._upb._message.MessageMapContainer uses PyType_Spec with a metaclass that has custom tp_new. This is deprecated and will no longer be allowed in Python 3.14.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
SystemError: <class 'DeprecationWarning'> returned a result with an exception set
```

obviously the fix is to upgrade to something which doesn't crash -- but it should still gracefully produce the deprecation warning instead of crashing with SystemError

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
I believe this bug is in the third-party library, specifically here: https://github.com/protocolbuffers/protobuf/blob/ed400ea5177a3ed10e6749ceb99077649828008a/python/google/protobuf/pyext/map_container.cc#L902. This calls `PyType_FromSpecWithBases` without check for a NULL return value.

**Comment by asottile-sentry** [comment]
ah, usually I see SystemError I assume cpython problem -- but I agree with the assessment of not checking null there 👍
