### ISSUE TITLE
Fatal Python error: _PyMem_DebugMalloc: Python memory allocator called without holding the GIL

### ISSUE THREAD

**Issue by bchoudhary6415** [python/cpython#115395]
# Bug report

### Bug description:

While building my ibm_db extension using python3.12
I'm getting the above mentioned error.
I tried replacing PyMem_Free to PyMem_RawFree and PyMem_Malloc to PyMem_RawMalloc
But still getting the same error.
What steps do I need to take to resolve the above mentioned error.
I was not facing the issue with python3.11.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by mdboom** [comment]
Can you provide a self-contained example that reproduces the bug?

**Comment by bchoudhary6415** [comment]
Hi @mdboom,
Previously ibm_db extension compiled with the code - PyUnicode_FromUnicode, PyUnicode_GET_SIZE and PyUnicode_AS_UNICODE
As from python3.12 the above mentioned APIs is removed, 
so from the python documentation - https://docs.python.org/3.10/whatsnew/3.3.html?highlight=pyunicode_get_size#deprecated-functions-and-types-of-the-c-api
I found replacement for the above APIs as PyUnicode_FromWideChar, PyUnicode_GET_LENGTH and PyUnicode_AsWideCharString respectively.

After changing the code  and building my ibm_db extension it's started giving the above mentioned Error.

**Comment by ericvsmith** [comment]
@bchoudhary6415 : Unless you can provide us some code we can compile and test with, it's going to be difficult or impossible to help here.

**Comment by bchoudhary6415** [comment]
@ericvsmith 
After changing PyUnicode_GetSize() to PyUnicode_GetLength(), 
It started working for me.
Closing this issue.
Thanks
