### ISSUE TITLE
Enhancement Proposal: Improving the open Function in Python

### ISSUE THREAD

**Issue by ghost** [python/cpython#115333]
# Feature or enhancement

### Proposal:

I propose that the open function in Python should automatically detect the encoding of a file when the encoding parameter is not specified. This would save developers time and effort in determining the correct encoding of a file before opening it. The automatic encoding detection could be based on commonly used encoding algorithms such as chardet or cchardet, and could fallback to a default encoding if the detection fails. This enhancement would improve the usability of the open function and make it easier for developers to work with files in Python.

```python
# example
# Existing code without automatic encoding detection
with open('example.txt', 'r', encoding='utf-8') as f:
    content = f.read()

# Proposed code with automatic encoding detection
with open('example.txt', 'r') as f:
    content = f.read()
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

not anything... :)

**Comment by ericvsmith** [comment]
You should bring this up on https://discuss.python.org/c/ideas/6 before opening an issue here. That's the correct place to discuss ideas for changing python.

Personally I'd be opposed to this, unless you passed in a flag like `guess_encoding=True`. I'd never want python to by default try and figure out the encoding based on heuristics.

I'm going to close this, but if there's support on discuss.python.org then we can re-open it.
