### ISSUE TITLE
New warning: `missing braces around initializer [-Wmissing-braces]`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#115441]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/115440/files

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-115460

**Comment by colesbury** [comment]
I think the warning started in https://github.com/python/cpython/pull/115329. It occurs in the non-debug default build.

My guess is that the GCC doesn't like the definition of `_py_object_state_INIT()` anymore:

https://github.com/python/cpython/blob/bb791c7728e0508ad5df28a90b27e202d66a9cfa/Include/internal/pycore_runtime_init.h#L215-L216


cc @corona10

**Comment by colesbury** [comment]
We can just remove `_py_object_state_INIT` completely and not explicitly initialize `.object_state`. Zero initialization is fine for that field.

**Comment by Eclips4** [comment]
Thanks Sam for fixing!
