### ISSUE TITLE
Tier 2 optimizations for 3.13

### ISSUE THREAD

**Issue by markshannon** [python/cpython#115419]
# Feature or enhancement

## Prerequisites

- [x] Overhaul Symbol API and add tests: https://github.com/python/cpython/pull/116028
- [x] Re-enable optimizer by default: https://github.com/python/cpython/pull/116062
- [x] https://github.com/python/cpython/issues/116088

## Optimizations to be added to the tier 2 optimizer for 3.13

- [x] https://github.com/python/cpython/issues/115685
  - [x] Normal _TO_BOOL specializations and friends.
  - [x] TO_BOOL_ALWAYS_TRUE (only if it's worth it?)
- [x] #115651
- [x] https://github.com/python/cpython/issues/115480
  - #115478
  - #115507
  - #115550
  - #115710
- [ ] https://github.com/python/cpython/issues/115506
  - [ ] BINARY_OP https://github.com/python/cpython/issues/115758
  - [x] TO_BOOL https://github.com/python/cpython/issues/115759
- [x] #115819
  - [x] _GUARD_IS_TRUE_POP
  - [x] _GUARD_IS_FALSE_POP
  - [x] _GUARD_IS_NONE_POP
  - [x] _GUARD_IS_NOT_NONE_POP
- [ ] All remaining type and value propagation.
- [x] Extract type guards for `COMPARE_OP_INT/FLOAT/STR`
- [ ] https://github.com/python/cpython/issues/115687
  - [x] Split up into uops
  - [ ] Propagate bool value and constants too.
- [ ] Any remaining guard elimination not handled above
  - [ ] https://github.com/python/cpython/pull/116562 
  - [x] Eliminate/combine redundant stack checks (`_CHECK_STACK_SPACE`)
- [x] https://github.com/python/cpython/issues/115709
- [x] https://github.com/python/cpython/issues/116168
- [x] https://github.com/python/cpython/issues/116202
- [x] https://github.com/python/cpython/issues/116291

## If we have time:

- [x] https://github.com/python/cpython/issues/116381
  - [ ] https://github.com/python/cpython/issues/116432 
- [ ] Replace `CALL_TUPLE_1` for list and generator arguments
- [ ] Only specialize `CALL` in tier for type. Generate optimal argument handling code in tier 2.

### Linked PRs
* gh-116562
* gh-117997
* gh-118054
* gh-118088

**Comment by mdboom** [comment]
This is perhaps so rough as to be meaningless (i.e. uop counts != run time), but in an attempt to help prioritize these tasks, I thought I'd share some aggregate counts from a recent pyperformance run:

| Grouping | Uops included in group | Total |
| -- | -- | --: |
| TO_BOOL | TO_BOOL_ALWAYS_TRUE, TO_BOOL_BOOL, TO_BOOL_INT, TO_BOOL_LIST, TO_BOOL_NONE, TO_BOOL_STR, _TO_BOOL | 1,296,284,467 |
| LOAD_ATTR_MODULE | | 96,542,580 |
 | BINARY_OP | _BINARY_OP_MULTIPLY_INT, _BINARY_OP_ADD_INT, _BINARY_OP_SUBTRACT_INT, _BINARY_OP_ADD_UNICODE, _BINARY_OP, _BINARY_OP_MULTIPLY_FLOAT, _BINARY_OP_ADD_FLOAT, _BINARY_OP_SUBTRACT_FLOAT | 5,308,844,150 |
| COMPARE_OP | COMPARE_OP_INT, COMPARE_OP_STR, _COMPARE_OP, COMPARE_OP_FLOAT | 2,404,431,292 |
| CONTAINS_OP | | 1,654,609,694 |

@markshannon: Let me know if anything else like this would be helpful.

**Comment by markshannon** [comment]
3.13 is nearing release, so nothing more is going in 3.13.

Everything we didn't get done for 3.13 will get into 3.14 (if it hasn't been done already)
