### ISSUE TITLE
co_qualname "new in version" information missing in doc

### ISSUE THREAD

**Issue by christophe-papazian** [python/cpython#115405]
# Documentation

Usually documentation includes deprecated or "new in version" tags for all features.

the field `co_qualname` in code objects was added in python 3.11 but the documentation does not precise that, and it feels like it was always defined

https://docs.python.org/3/reference/datamodel.html#index-58

### Linked PRs
* gh-115411
* gh-115412
* gh-115413

**Comment by christophe-papazian** [comment]
Some proposal fix:

```
index 885ee825c1..88bc025c7c 100644
--- a/Doc/reference/datamodel.rst
+++ b/Doc/reference/datamodel.rst
@@ -1134,6 +1134,8 @@ Special read-only attributes
    * - .. attribute:: codeobject.co_qualname
      - The fully qualified function name
 
+       .. versionadded:: 3.11
+
    * - .. attribute:: codeobject.co_argcount
      - The total number of positional :term:`parameters <parameter>`
        (including positional-only parameters and parameters with default values)
```

**Comment by AlexWaygood** [comment]
> Some proposal fix:
> 
> ```
> index 885ee825c1..88bc025c7c 100644
> --- a/Doc/reference/datamodel.rst
> +++ b/Doc/reference/datamodel.rst
> @@ -1134,6 +1134,8 @@ Special read-only attributes
>     * - .. attribute:: codeobject.co_qualname
>       - The fully qualified function name
>  
> +       .. versionadded:: 3.11
> +
>     * - .. attribute:: codeobject.co_argcount
>       - The total number of positional :term:`parameters <parameter>`
>         (including positional-only parameters and parameters with default values)
> ```

Looks good to me! Would you like to make a PR?

**Comment by christophe-papazian** [comment]
ok, I'll do that.
