### ISSUE TITLE
Type/constant/value propagation for `BINARY_OP`

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#115480]
### Linked PRs
* gh-115478
* gh-115507
* gh-115550
* gh-115710
* gh-118050

**Comment by markshannon** [comment]
- [ ] Handle float operations. Factor out common code into helper function.
- [ ] Eliminate input constants and generate new constant (needs its own issue for more detailed design)

**Comment by Eclips4** [comment]
Can it be closed now?
