### ISSUE TITLE
`memoryview(memoryview())`should be a no-op

### ISSUE THREAD

**Issue by smurfix** [python/cpython#115414]
# Feature or enhancement

### Proposal:

`memoryview` objects are immutable. Creating a memoryview from an existing memoryview should therefore be a no-op.

```python
b = bytearray(b'abc')
m = memoryview(b)
n = memoryview(m)
assert n is m
```

This would eliminate the need for `if isinstance(b, memoryview): b = memoryview(b)` tests, as well as the creation of redundant or ephemeral memoryview objects when the buffer that's passed in may or may not be a memoryview; the CPython stdlib has ~50 instances of the latter.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by brianschubert** [comment]
This would be a breaking change:

```python
# Release n
>>> n.release()

# 'm' is still usuable
>>> m[0]
97

# 'n' is not
>>> n[0]
Traceback (most recent call last)
...
ValueError: operation forbidden on released memoryview object
```

**Comment by smurfix** [comment]
Ah. Thanks for the clarification.
