### ISSUE TITLE
enum.auto should use capitalised enumerable strings

### ISSUE THREAD

**Issue by craigcrawfordcts** [python/cpython#115509]
# Bug report

### Bug description:

Most languages dictate that the value and the name of the enumerable should be uppercase, for example with Java: https://docs.oracle.com/javase/tutorial/java/javaOO/enum.html

In python, a convenience method is provided `auto`, but neither in the description of `StrEnum` nor `auto` is it described that the enumerable values will be the lowercased variant of the enumerable's name.

This results in a failure to parse JSON objects using pydantic where the enumerable uses `auto` instead of directly defining the string, for example if those enumerable values were serialised in Java they are likely to be uppercased.

This results in a shooting-yourself-in-the-foot scenario if you believe you can just swap out your enum values for `auto`...

```python
from enum import StrEnum, auto
from pydantic import BaseModel
import pytest

class StringEnumType(StrEnum):
    SOME_STRING = "SOME_STRING"


class AutoEnumType(StrEnum):
    SOME_STRING = auto()


class BaseModelWithStringEnumType(BaseModel):
    some_enum: StringEnumType


class BaseModelWithAutoEnumType(BaseModel):
    some_enum: AutoEnumType

@pytest.mark.parametrize(
    "model",
    [
        (BaseModelWithStringEnumType),(BaseModelWithAutoEnumType)
    ]
)
def test(model: BaseModel):
    model = model.model_validate({
        "some_enum": "SOME_STRING"
    })
```

```
tests/unit/test_fail.py::test[BaseModelWithAutoEnumType] FAILED
tests/unit/test_fail.py::test[BaseModelWithStringEnumType] PASSED

================================================================================== FAILURES ===================================================================================
_______________________________________________________________________ test[BaseModelWithAutoEnumType] _______________________________________________________________________

model = <class 'unit.test_fail.BaseModelWithAutoEnumType'>

    @pytest.mark.parametrize(
        "model",
        [
            (BaseModelWithStringEnumType),(BaseModelWithAutoEnumType)
        ]
    )
    def test(model: BaseModel):
>       model = model.model_validate({
            "some_enum": "SOME_STRING"
        })
E       pydantic_core._pydantic_core.ValidationError: 1 validation error for BaseModelWithAutoEnumType
E       some_enum
E         Input should be 'some_string' [type=enum, input_value='SOME_STRING', input_type=str]

tests/unit/test_fail.py:27: ValidationError
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ethanfurman** [comment]
@craigcrawfordcts :
>  but neither in the description of StrEnum nor auto is it described that the enumerable values will be the lowercased variant of the enumerable's name

[enum docs](https://docs.python.org/3/library/enum.html#enum.auto) for `auto`:
> [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) defaults to the lower-cased version of the member name

[enum docs](https://docs.python.org/3/library/enum.html#enum.StrEnum) for `StrEnum`:
> Note Using [auto](https://docs.python.org/3/library/enum.html#enum.auto) with [StrEnum](https://docs.python.org/3/library/enum.html#enum.StrEnum) results in the lower-cased member name as the value.

If you want a different case, you can create your own base class:

```
class UpperStrEnum(StrEnum):
    @staticmethod
    def _generate_next_value_(name, *args):
        return name.upper()
```

**Comment by craigcrawfordcts** [comment]
Disappointing. Correct those are in the online version of the document, but they are not in the doc strings:
![image](https://github.com/python/cpython/assets/149721894/e2fabbac-4fa4-42f0-9bdf-8d74eba27440)

![image](https://github.com/python/cpython/assets/149721894/8d626ca3-83f4-42c7-b043-7c587cc387e1)

One could argue that the lowercased variant of an enum is not appropriate.

**Comment by alexdelorenzo** [comment]
The [`StrEnum` package on PyPI](https://pypi.org/project/StrEnum/) preserves case when using `auto()`
