### ISSUE TITLE
``codeobject.replace`` function is undocumented 

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#115572]
### Bug description:

``codeobject.replace`` function was introduced in a9f05d69ccbf3c75cdd604c25094282697789a62, but there's only a note in ``Doc/whatsnew``.
My folk @daler-sz would like to work on a fix :)

### CPython versions tested on:

3.11, 3.12, 3.13

### Linked PRs
* gh-115631
* gh-115632
* gh-115633

**Comment by AlexWaygood** [comment]
It looks like there are some very short docs on the method here: https://docs.python.org/3/library/types.html#types.CodeType.replace

But it's in the wrong place; all other code object attributes and methods are documented here: https://docs.python.org/3/reference/datamodel.html#code-objects.

Also, `types.CodeType` should link to the "proper" docs on code objects; it currently doesn't

**Comment by Eclips4** [comment]
Thnkas @daler-sz for fixing this!
