### ISSUE TITLE
enum.Flag with a flag set to None raises an exception

### ISSUE THREAD

**Issue by elicn** [python/cpython#115539]
# Bug report

### Bug description:

The following code snippet defines a `Flag` class denoting an unsupported flag with `None`.
```python
from enum import Flag

class TestFlag(Flag):
    O_NONE = 0
    O_ONE = 1
    O_TWO = 2
    O_FOUR = 4
    O_NOT_SUPPORTED = None
```

While working fine on earlier Python versions, this code raises an exception on Python 3.11 and 3.12 without even instantiating the class.

The snippet above on Python 3.9:
```python
Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from enum import Flag
>>> class TestFlag(Flag):
...     O_NONE = 0
...     O_ONE = 1
...     O_TWO = 2
...     O_FOUR = 4
...     O_NOT_SUPPORTED = None
...
>>>
```

Same snippet on Python 3.12:
```python
Python 3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from enum import Flag
>>> class TestFlag(Flag):
...     O_NONE = 0
...     O_ONE = 1
...     O_TWO = 2
...     O_FOUR = 4
...     O_NOT_SUPPORTED = None
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 593, in __new__
    raise exc.with_traceback(tb)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 583, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.752.0_x64__qbz5n2kfra8p0\Lib\enum.py", line 286, in __set_name__
    enum_class._flag_mask_ |= value
TypeError: unsupported operand type(s) for |=: 'int' and 'NoneType'
>>>
```

Works on:
 - Python 3.8 (Windows and Linux)
 - Python 3.9 (Windows and Linux)

Fails on:
 - Python 3.11 (Windows, Linux not tested)
 - Python 3.12 (Windows and Linux)

### CPython versions tested on:

3.8, 3.9, 3.11, 3.12

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-115636
* gh-115694
* gh-115695

**Comment by Jason-Y-Z** [comment]
Hey all, thanks for raising and triaging. I had a go at a simple fix - https://github.com/python/cpython/pull/115636

**Comment by ethanfurman** [comment]
@elicn : What error message would be useful when the `None` flag is combined with any others?  The four possible are `or`, `and`, `xor`, and `invert`.

**Comment by elicn** [comment]
Though `None` flags are not meant to be combined with other flags and expected to raise an exception when they are, it should still be OK to define them.

As for the error, I guess we can stick with the errors raised on earlier Python versions. That is:
```python
>>> # This should be OK
>>> TestFlag.O_ONE | TestFlag.O_TWO
<TestFlag.O_TWO|O_ONE: 3>

>>> # This should raise an exception
>>> TestFlag.O_ONE | TestFlag.O_NOT_SUPPORTED
Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    TestFlag.O_ONE | TestFlag.O_NOT_SUPPORTED
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\enum.py", line 902, in __or__
    return self.__class__(self._value_ | other._value_)
TypeError: unsupported operand type(s) for |: 'int' and 'NoneType'
>>>
```

I am not sure how you would like to restrict the values types though: should it support any type as long as it defines its behavior for bitwise and, or, xor and invert operations? or just `int`?

**Comment by ethanfurman** [comment]
The only supported values for flags are `0`, `None`, and positive integers.

A `TypeError` is fine, but the current message is not friendly.  Perhaps something along the lines of:

```
TypeError: 'TestFlag.O_NOT_SUPPORTED' cannot be combined with other flags
```

**Comment by Jason-Y-Z** [comment]
I have made the requested changes; please review again

**Comment by Jason-Y-Z** [comment]
Now that the relevant PR is merged, I assume we can close this issue now? @elicn

**Comment by elicn** [comment]
Thank you everyone for addressing the issue.
