### ISSUE TITLE
Windows test scripts don't escape commas properly

### ISSUE THREAD

**Issue by ambv** [python/cpython#115556]
In Windows batch file execution, a comma is one of the magic parameter delimiters. To pass a comma as parameter data, you have to use string quotes around that parameter, like:

```
.\Tools\buildbot\test.bat -M33g "-uall,extralargefile" test_zipfile64
```

However, now the quotes become part of the parameter. Inside `test.bat` we employ some command-line parsing and shifting, which requires us to *remove* the quotes from parameters, if any, for the code to continue working.

This is doubly complicated by the fact that `test.bat` passes execution to `rt.bat`, which does similar parsing there. The fix is needed there, too.

### Linked PRs
* gh-115557

**Comment by hugovk** [comment]
Closing because the PR has been merged. Please re-open if there's more needed here.
