### ISSUE TITLE
pip2 broken on installation for python 2.7 32bit installer (https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi)

### ISSUE THREAD

**Issue by Tazarus** [python/cpython#115562]
# Bug report

#### Issue:
The 32-bit version of Python 2.7 from the official site is broken on installation, and incapable of installing almost all packages
link for download: https://www.python.org/ftp/python/2.7.18/python-2.7.18.msi 

The problem should be relatively simple to fix, but the issue is the pre-bundled version of pip:
1. cannot be used to install most packages
2. cannot be updated via the direct pip2 install --upgrade pip, as pip v 24.0 is not compatible with it.

### Short Term Fix
To circumvent the issue you can use:
- pip2 -install --upgrade pip==20.3.4

Where pip2 can then perform as expected.

My results attempting to both upgrade pip and install virtualenv using the pip installation that comes default with the python installation:

```python
C:\Windows\System32>pip2 install --upgrade pip
You are using pip version 7.0.1, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting pip
  Using cached https://files.pythonhosted.org/packages/94/59/6638090c25e9bc4ce0c42817b5a234e183872a1129735a9330c472cc2056/pip-24.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\cftaz\appdata\local\temp\pip-build-_jcsmc\pip\setup.py", line 9
        f"pip{sys.version_info[0]}=pip._internal.cli.main:main",
                                                              ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\cftaz\appdata\local\temp\pip-build-_jcsmc\pip


C:\Windows\System32>pip2 install virtualenv
You are using pip version 7.0.1, however version 24.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting virtualenv
  Using cached https://files.pythonhosted.org/packages/94/d7/adb787076e65dc99ef057e0118e25becf80dd05233ef4c86f07aa35f6492/virtualenv-20.25.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 18, in <module>
    IOError: [Errno 2] No such file or directory: 'c:\\users\\cftaz\\appdata\\local\\temp\\pip-build-gd7und\\virtualenv\\setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\cftaz\appdata\local\temp\pip-build-gd7und\virtualenv
```

#### Recommended Solution:
When pip is being run in conjuction with python 2, it should default to installing the last compatible version, not the latest.

### Note:
> I was unable to select any python 2 versions in the Cpython versions tested on box, and I am unsure if python2 issues even get looked at anymore since it is depracated, but thought I would mention this just in case.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Sorry, but python2 and pip2 in state of EOL.
