### ISSUE TITLE
PEP 646 grammar changes are not documented

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#115528]
PEP-646 made some changes to the grammar, but neither is reflected in the language reference:

- https://docs.python.org/3/reference/expressions.html#subscriptions should mention that the right-hand side of a subscript can be a starred expression
- https://docs.python.org/3/reference/compound_stmts.html#function-definitions should mention that the annotation of an `*args` parameter can be a starred expression

References: python/peps#3671 (making the PEP final); python/cpython#31018 (implementation of the grammar changes)

### Linked PRs
* gh-120294
* gh-121181
* gh-124632
* gh-124633

**Comment by hugovk** [comment]
@mrahtz Hello! Pinging as author of https://github.com/python/cpython/pull/31018 and co-author of PEP-646. 

There's still a bit of work to be done for the PEP: document the changes, and mark the PEP as Final with a link to the docs.

Please could you co-ordinate with your co-authors to finish this off? Thank you!

**Comment by mrahtz** [comment]
Ooh thanks for the heads up! I'll try to get to this in the next week or so.

**Comment by AlexWaygood** [comment]
I think we're done here!
