### ISSUE TITLE
Python Install Fails Due To Newer Launcher

### ISSUE THREAD

**Issue by GadgetSteve** [python/cpython#115554]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
If you have a Windows machine with multiple versions of python installed the presence of a newer version of the installer can prevent updating the older python version installations.
For example installing in the following sequence, (all with `install py launcher` checked _(global or otherwise)_, tested with both 64 & 32 bit versions:

1. Python 3.11.7 _OK_
2. Python 3.12.1 _OK (Updates Launcher)_
3. Python 3.11.8 _Select Update or Customise with the py launcher ticked_ Part way through the install a pop-up is shown. 
![image](https://github.com/python/cpython/assets/5593690/22856aac-77e0-4f27-86d6-ff8be2973feb)
Select `OK` & Installation is wound back. Followed by: 
![image](https://github.com/python/cpython/assets/5593690/fedacd03-5200-438b-91bd-065b0d90fc62)
The relevant section of the log reads:
```log

[D824:8A50][2024-02-16T07:58:01]i325: Registering dependency: {02717f5c-724f-48a7-86c0-ee11d4de681c} on package provider: {8EEE1658-8844-4DAD-8A3B-7AF321C9A4FD}, package: tcltk_JustForMe
[D824:8A50][2024-02-16T07:58:01]i301: Applying execute package: launcher_JustForMe, action: Install, path: C:\Users\Gadge\AppData\Local\Package Cache\{8DFCF17F-8C82-4E21-96F1-B1777F61A757}v3.11.8150.0\launcher.msi, arguments: ' MSIFASTINSTALL="7" ADDLOCAL="DefaultFeature,AssociateFiles"'
[D824:8A50][2024-02-16T07:59:54]e000: Error 0x80070643: Failed to install MSI package.
[D824:8A50][2024-02-16T07:59:54]e000: Error 0x80070643: Failed to configure per-user MSI package.
[D824:8A50][2024-02-16T07:59:54]i319: Applied execute package: launcher_JustForMe, result: 0x80070643, restart: None
[D824:8A50][2024-02-16T07:59:54]e000: Error 0x80070643: Failed to execute MSI package.
[D824:8A50][2024-02-16T07:59:54]i351: Removing cached package: launcher_JustForMe, from path: C:\Users\Gadge\AppData\Local\Package Cache\{8DFCF17F-8C82-4E21-96F1-B1777F61A757}v3.11.8150.0\
[D824:8A50][2024-02-16T07:59:54]i329: Removed package dependency provider: {9E9F28A9-A7A6-4483-842C-07579F9D7FDD}, package: tcltk_JustForMe_d
```
4. Running `py -0` results in:
```
$ py -0
 -V:3.12          Python 3.12 (64-bit)
 -V:3.10          Python 3.10 (64-bit)
 -V:3.10-32       Python 3.10 (32-bit)
 -V:3.9           Python 3.9 (64-bit)
```
So I have now lost my Python 3.11 installation! ***Not very happy at this point!***
5. Re-running the installer, selecting `Customize Installation` and unticking `py launcher` will allow a successful installation **but**:
 - Many users may not realise this option will resolve the issue!
 - In controlled environments *such as at my work* an `unattend.xml` file or install script may prevent the user changing this option.

# Possible Resolutions

There is more than one way that this issue could be handled. If a newer py launcher is present:

- Skip installing py launcher silently or with a message but not an error. Unlikely to actually cause a problem but may invalidate some test environments.
- Offer to downgrade py launcher or leave the newer one.
- Offer the option to skip py launcher or cancel install _(with warning that old installation may be lost)_.

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-115793
* gh-116200
* gh-116201

**Comment by Eclips4** [comment]
cc @zooba

**Comment by zooba** [comment]
Could you post the entire log? There's an earlier detection section which is actually the relevant bit - it's supposed to detect newer versions and skip the install entirely.

**Comment by GadgetSteve** [comment]
@zooba Attached log of failed python install plus matching `launcher_JustForMe.log` found referenced.
[Python 3.11.8 (64-bit)_20240216075617.log](https://github.com/python/cpython/files/14339919/Python.3.11.8.64-bit._20240216075617.log)
[Python 3.11.8 (64-bit)_20240216075617_007_launcher_JustForMe.log](https://github.com/python/cpython/files/14339995/Python.3.11.8.64-bit._20240216075617_007_launcher_JustForMe.log)

**Comment by zooba** [comment]
Okay, so the "newer" launcher appears to be the one from 3.11.0rc2, which apparently got the version number 3.11.7923.0 by mistake. This mistake was fixed for the release, but is apparently going to start showing up now that 3.11.8's version number is higher again.

```
[D824:8A50][2024-02-16T07:56:17]i103: Detected related package: {0AC52D3D-7EB6-49C8-9F5A-45EE040B3421}, scope: PerMachine, version: 3.11.7923.0, language: 0 operation: MajorUpgrade
```

And the failure is because it was installed for all users, whereas 3.12 was not. The installer gets confused by detecting the launcher twice and chooses to upgrade the launcher (from 3.11.0rc2 to 3.11.8), but then chooses to do it just for the current user (matching 3.12.1). This then becomes a downgrade, which is prevented by the installer.

So the quickest immediate fix will be to go into Programs and Features and uninstall any "Python Launcher" entries you see. If one is obviously the 3.11.0rc2 version, uninstall that one, or else just get them all and then repair the 3.12 install to bring back the right one.

The fix we need on our side is in the bootstrapper logic that detects an already installed launcher, and it's probably to detect multiple launchers and refuse to do anything until one or the other is uninstalled (manually). There's probably some logic that can resolve the conflict most of the time, but it's not going to be as easily explainable as "you've got the launcher installed twice already and we're not going to add another one".

**Comment by GadgetSteve** [comment]
@zooba Thanks for the clarification. On my work machine I had the same sort of error but there is only a single py.exe to be found, (we are locked from installing to c:\Windows, Program Files, etc.), _unfortunately I am not permitted to export the log files from that machine._ It definitely had only a single version of the launcher installed.

**Comment by zooba** [comment]
Would you be able to confirm the package ID and version on that other machine? It'll be a "Detected related package" message like the one I quoted above, and ought to be immediately before a log line saying `Setting numeric variable 'AssociateFiles' ...`. Anything with an unusual looking version number may also be relevant.

(The package IDs are different for each version, so the version number is really helpful. They're mapped together using a different ID that is stable, but isn't shown in the logs here.)

**Comment by GadgetSteve** [comment]
Filtering the log files to the one that rolled back gives:
```
grin "Setting numeric variable.+auncher" -I "python 3.11.8 (64-bit)_20240215172929*".log -C3
.\Temp\Python 3.11.8 (64-bit)_20240215172929.log:
   55 - [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'Include_pip' to value 1
   56 - [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'Include_lib' to value 1
   57 - [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'CompileAll' to value 1
   58 : [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'Include_launcher' to value 1
   59 : [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'InstallLauncherAllUsers' to value 0
   60 + [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'Include_test' to value 0
   61 + [8520:4AE4][2024-02-15T17:29:29]i000: Setting numeric variable 'SimpleInstall' to value 0
   62 + [8520:4AE4][2024-02-15T17:29:29]i000: Setting string variable 'SimpleInstallDescription' to value 'Current User, No test suite.'  
   84 - [8520:7B70][2024-02-15T17:29:30]i000: Setting numeric variable 'Shortcuts' to value 1
   85 - [8520:7B70][2024-02-15T17:29:30]i000: Setting string variable 'InstallAllUsersState' to value 'disable'
   86 - [8520:7B70][2024-02-15T17:29:30]i103: Detected related package: {3B36061E-A25F-4E12-BFD1-68E724723D48}, scope: PerUser, version: 3
.12.2150.0, language: 0 operation: Downgrade
   87 : [8520:7B70][2024-02-15T17:29:30]i000: Setting numeric variable 'InstallLauncherAllUsers' to value 1
   88 + [8520:7B70][2024-02-15T17:29:30]i103: Detected related package: {3B36061E-A25F-4E12-BFD1-68E724723D48}, scope: PerUser, version: 3
.12.2150.0, language: 0 operation: Downgrade
   89 : [8520:7B70][2024-02-15T17:29:30]i000: Setting numeric variable 'InstallLauncherAllUsers' to value 0
   90 + [8520:7B70][2024-02-15T17:29:30]i103: Detected related package: {D86BDA9F-D389-445E-B3E6-C35EF9FD41C7}, scope: PerUser, version: 3
.11.4150.0, language: 0 operation: MajorUpgrade
   91 + [8520:7B70][2024-02-15T17:29:30]i103: Detected related package: {D86BDA9F-D389-445E-B3E6-C35EF9FD41C7}, scope: PerUser, version: 3
.11.4150.0, language: 0 operation: MajorUpgrade
   92 + [8520:7B70][2024-02-15T17:29:30]i101: Detected package: ucrt_AllUsers, state: Absent, cached: None
```
So it looks like there may have been a second launcher somewhere on the machine.

**Comment by zooba** [comment]
They're both per-user though, which is weird. It shouldn't be possible to do that.

In any case, I think it shows that the best way for us to handle this is to never change a "don't install launcher" into an "upgrade launcher" automatically, and probably to specifically try and detect the simultaneous peruser/permachine installs and block.

If anyone wants to take a look before I get to it, the code lives in `Tools\msi\bundle\bootstrap\PythonBootstrapperApplication.cpp`.
