### ISSUE TITLE
assert should fail or raise exception but it passes

### ISSUE THREAD

**Issue by sameraamar** [python/cpython#115552]
# Bug report

### Bug description:

```python
def test_assert():
    a = "abc\nefg"
    assert (a == 'abc\n','efg h')
```
The abve code has a comma by mistake in the right side of the comparison.
The assert passes successfuly when it should either Fail or throw exception,

Why is this important:
I had list of unit tests that got a comma by mistake and all unit tests passed successfuly for few weeks, till i found that they should have failed, by chance. This can cause instability in the system when one thinks all is good.

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Yes, because of parentheses this assertion is always evaluates to `True`
On newer Python versions you will get warning:
`SyntaxWarning: assertion is always true, perhaps remove parentheses?`
So, there's no bug.
