### ISSUE TITLE
[BUG] sqlite3 context manager hold resource and fail to release it.

### ISSUE THREAD

**Issue by ItamarShalev** [python/cpython#115537]
# Bug report

### Bug description:

        file = "test.db"
        with database.connect(file) as connection:
           pass
        os.remove("test.db") # Raise WinError 32 permission error
        
        
        
        
        file = "test.db"
        connection = database.connect(file)
        connection.close()
        os.remove("test.db") # OK
        
        
        
        

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by erlend-aasland** [comment]
The `sqlite3.Connection` context manager manages transactions, not files. See [How to use the connection context manager](https://docs.python.org/3/library/sqlite3.html#how-to-use-the-connection-context-manager) in the sqlite3 docs for more information.
