### ISSUE TITLE
tkinter menubar not calculated properly with none of the .geometry() methods when bundled into pyinstaller

### ISSUE THREAD

**Issue by jessielw** [python/cpython#115569]
# Bug report

### Bug description:

Utilizing tkinter I save the geometry of the windows for users, so they can re-open them at the same size/position as they closed them. This works great besides windows with a menu bar. The menu bar isn't calculated properly when calling the `root.geometry()` method (or any other variant). So the window shrinks in height each time it's closed, which is undesired. 

I can only reproduce this if I compile my program into a binary with pyinstaller (onefile and onedir mode). 

As a work around I am now doing this, but this does seem like a bug to me. 
```python
    def save_config_information_root():
        # root exit parser
        root_exit_parser = ConfigParser()
        root_exit_parser.read(config_file)

        # save main gui window position/geometry
        if root.wm_state() == "normal":
            root.config(menu="")
            root.update_idletasks()
            if (
                root_exit_parser["save_window_locations"]["windowx"]
                != root.geometry()
            ):
                root_exit_parser.set(
                    "save_window_locations", "windowx", root.geometry()
                )
                with open(config_file, "w") as root_exit_config_file:
                    root_exit_parser.write(root_exit_config_file)
```
Simply setting `menu=""` removes the menu and there for doesn't take it's size into consideration. 

Hopefully I posted this in the right place. I know that it's only reproducible when compiled with pyinstaller, but since pyinstaller only bundles the code, I am wondering if it's a deeper issue here. 

Thanks!

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
Please also ask the PyInstaller project about this. I'm not a PyInstaller, or Windows, user myself, but do know that bundling libraries can require some tweaks in the bundler to get functionality right. AFAIK PyInstaller has specific support for Tkinter.

**Comment by jlw4049** [comment]
Updating both of these issues as the same. The issue was is because I used something like so. 

```python
root = Tk()

def another_window():
     root.update_idletasks() # issue is here <-
     another_window = Window() # this is a top level, in this other window we calculate size based on root's geometry, this window also gets withdrawn immediately as we want it hidden unless we need it
     
# a lot of other main window code
if bundled:
     another_window()
# do a bunch of stuff on main window

root.mainloop()
```
The issue was `root.update_idletasks()`. Removing this allows the geometry to be properly calculated bundled/not bundled. I will close this.
