### ISSUE TITLE
inspect.Signature(obj) raises TypeError if obj is a bound method

### ISSUE THREAD

**Issue by edreamleo** [python/cpython#115630]
# Bug report

### Bug description:

If `obj` is a bound method, `inspect.Signature(obj)` raises `TypeError`.

Is this the expected behavior???

```python
print('obj:', repr(obj))
print('inspect.getdoc(obj)', inspect.getdoc(obj))
print('inspect.Signature(obj)', inspect.Signature(obj))
```

```console

obj: <bound method LeoQtFrame.getFocus of <LeoQtFrame: C:/Users/Dev/ekr.leo>>
inspect.getdoc(obj) None
Traceback (most recent call last):

[snip]

  File "C:\Repos\leo-editor\leo\core\leoKeys.py", line 829, in info
    print('inspect.Signature(obj)', inspect.Signature(obj))
                                    ^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Python\Python3.12\Lib\inspect.py", line 3029, in __init__
    for param in parameters:

TypeError: 'method' object is not iterable
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
There's no bug. Please, read the doc about the `inspect.Signature`: https://docs.python.org/3.12/library/inspect.html#inspect.Signature
Probably you've confused the `inspect.signature` with the `inspect.Signature`

**Comment by edreamleo** [comment]
@Eclips4 Thanks!
