### ISSUE TITLE
The pop method of set not random

### ISSUE THREAD

**Issue by peetm** [python/cpython#115648]
# Bug report

### Bug description:

The documentation for the `set`'s `pop` method says it removes an arbitrary member of a set ("Remove and return an arbitrary element from the set").  I read this as meaning that the element is randomly chosen - in other words, that 'arbitrary' and 'random' are the same thing, However, I don't believe CPython agrees, and so the wording may require clarification, or pop's implementation may need to change to make it truly random.

For example, in the following, and in my mind, it's unlikely (33%) that `thing1` and `thing2` will have the same value, and, if they differ, `thing3` will contain the remaining value; conversely, if they have the same value, `thing3` will receive, **randomly**, one of two possible remaining values.

However, trying this with CPython 3.12 and colab, the result is always `1 1 2`

```python
for _ in range(10):

    thing1 = {1, 2, 3}.pop()

    thing2 = {1, 2, 3}.pop()

    thing3 = ({1, 2, 3} - {thing1, thing2}).pop()

    print(thing1, thing2, thing3)
```

Trying this in CodeSkulptor3 produces what I think is the right result -  [https://py3.codeskulptor.org/#user309_UZFuLnBBwgVVAHh.py](url)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
"Arbitrary" means "we don't specify which one" here, not "randomly chosen".

**Comment by serhiy-storchaka** [comment]
Concur with @terryjreedy. The documentation says that it is arbitrary, not random.
