### ISSUE TITLE
Indentation in the documentation of multiprocessing.get_start_method

### ISSUE THREAD

**Issue by denialhaag** [python/cpython#115652]
# Documentation

There is a problem with the indentation in the documentation of [`multiprocessing.get_start_method`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.get_start_method). "Changed in version 3.8: [...]" and "New in version 3.4." should be indented.

### Linked PRs
* gh-115658
* gh-115659
* gh-115660

**Comment by hugovk** [comment]
Thanks for the report, would you like to create a PR to fix this?
