### ISSUE TITLE
Convert `LOAD_ATTR_MODULE` to a constant where the module is already a constant

### ISSUE THREAD

**Issue by markshannon** [python/cpython#115651]
Expressions like `mod.attr`, where `mod` is a module, are in almost all cases effectively constants. 

We should optimize them as such.
We already treat the `mod` as a constant, so it is a relatively simple step to treat `mod.attr` as a constant.

### Linked PRs
* gh-115711

**Comment by gvanrossum** [comment]
Can this be closed now?
