### ISSUE TITLE
Incorrect Py_XDECREFs in property

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#115618]
# Crash report

When `property` methods `getter()`, `setter()` or `deleter()`  are called with None as argument, they call `Py_XDECREF()` on it. Now, when None is immortal, it perhaps have no effect, but in earlier Python versions it could have bad consequences. It was not reported earlier only because nobody normally calls them with None.

### Linked PRs
* gh-115619
* gh-115620
* gh-115621

**Comment by eltoder** [comment]
@serhiy-storchaka Literally came here to report the same issue :-) It affects versions 3.10 and below, but does not cause a crash since python 3.12 since None became an immortal object.

**Comment by eltoder** [comment]
For the benefit of anyone finding this issue, here's a minimal reproduction example:
```python
p = property()
for _ in range(10000): p.getter(None)
```
results in
```
Fatal Python error: none_dealloc: deallocating None
Python runtime state: initialized

Current thread 0x00007fcd8c271000 (most recent call first):
  File "<stdin>", line 1 in <module>
Aborted
```
