### ISSUE TITLE
mimetypes.guess_extension returns different result in two computers with same Python version

### ISSUE THREAD

**Issue by andresespinosapc** [python/cpython#115666]
# Bug report

### Bug description:

I'm running the following code in my server and my local machine, both with the same Python version:

```python
import mimetypes

mimetypes.guess_extension('image/webp')
```

When I open the console in my server I get this:
`Python 3.9.18 (main, Aug 24 2023, 22:38:18)`
The result of the code is `None`

While in my local machine I get this:
`Python 3.9.18 (main, Sep  8 2023, 16:45:01)`
The result of the code is `.webp`

The only difference I see is that date, but I don't know what it means.

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

**Comment by hugovk** [comment]
The keyword is "guess".

The docs make no promise:

> The extension is not guaranteed to have been associated with any particular data stream, but would be mapped to the MIME type type by [guess_type()](https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_type). If no extension can be guessed for type, None is returned.

https://docs.python.org/3/library/mimetypes.html#mimetypes.guess_extension

Looking at the source, `guess_extensions` uses a database `_db` of MIME types:

https://github.com/python/cpython/blob/ecf16ee50e42f979624e55fa343a8522942db2e7/Lib/mimetypes.py#L324-L338

This is initialised from the Windows registry (where available) and a list of `knownfiles`:

https://github.com/python/cpython/blob/ecf16ee50e42f979624e55fa343a8522942db2e7/Lib/mimetypes.py#L357-L382

The known files are:

https://github.com/python/cpython/blob/ecf16ee50e42f979624e55fa343a8522942db2e7/Lib/mimetypes.py#L48-L58

If a file doesn't exist on your system, it is skipped.

I expect your local machine has the 'image/webp' MIME type in one of those files, but your server doesn't.

**Comment by andresespinosapc** [comment]
Ah ok, thanks

**Comment by ronaldoussoren** [comment]
There's also a built-in list of mime types, but that doesn't contain webp for python 3.9.

On macOS webp is included in /etc/apache2/mime.types, on the server YMMV.
