### ISSUE TITLE
Py launcher for Windows doesn't open Python 3.11

### ISSUE THREAD

**Issue by Welding-Torch** [python/cpython#115683]
# Bug report

### Bug description:

Hi there,

I installed **Python 3.11 from the Microsoft Store** today. I already have Python 3.9 (Installed from the Microsoft Store) and Python 3.8 (Installed from Thonny) on my laptop. If I try to launch either of those two Pythons using `py` launcher, I can do that. But if I try to launch Python 3.11, I get this error:

![image](https://github.com/python/cpython/assets/46340124/7b10f595-864d-45cb-9fd2-612654769abd)

*The Application was unable to start correctly.*

Is the py launcher not able to work with Python 3.11 from the Microsoft Store?

You may reproduce this example and try, please let me know if it is reproducible.

Similar issue:
#99442 handled by @zooba.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
Where did you install the launcher from? And if it's from 3.8 (seems likely, from your description), then yes, it doesn't have support for Store installs.

You can download the current latest version of the launcher (on its own) using `winget install Python.Launcher`[^1] or from https://www.python.org/ftp/python/3.12.2/win32/launcher.msi,[^2] which will update you to a version with support.

[^1]: I _believe_ this is the right command line, though I haven't tried it just now.

[^2]: This will only be the latest until the next release happens, but the structure of the URL isn't going to change, so substitute the current release in place of `3.12.2` to get the latest.

**Comment by Welding-Torch** [comment]
Thanks for the quickly reply.

I can't recall where I got the `py` launcher from because I got it in 2019, as confirmed by the date on the file:
![image](https://github.com/python/cpython/assets/46340124/7a4e6b6f-3594-4792-b2fd-99311ebdd391)


> And if it's from 3.8 (seems likely, from your description), then yes, it doesn't have support for Store installs.

Well, I'm able to switch between Python 3.9 (Installed from the Microsoft Store) and Python 3.8 (Installed from Thonny) easily using `py`. I just set `python=3.9` or `python=3.8` in the `py.ini` file, and it switches seamlessly.

 I'll download the latest version of the launcher and LYK if it detects Python 3.11

**Comment by Welding-Torch** [comment]
Running `winget install Python.Launcher` did not fix it. Actually, it didn't change the in `C:/Windows/py.exe` file at all.

![temp, del later](https://github.com/python/cpython/assets/46340124/87cda174-3c6c-4f55-b073-929db5e565c7)
_The Application was unable to start correctly._

**Comment by Welding-Torch** [comment]
I tried installing the .msi file. Interestingly, now there are two `py.exe` files on my laptop.
![image](https://github.com/python/cpython/assets/46340124/37775990-b429-4fc6-90d6-f3195dd58927)

**Comment by zooba** [comment]
You should be able to find "Python Launcher" in Programs and Features and remove one/both.

I think Winget changed their logic to only do per-user installs and just ignore all user ones, which is why it'll fail there. (They had some issue with people who use Winget to update everything all at once... I didn't quite follow, tbh.)

**Comment by Welding-Torch** [comment]
Yes, you are right. I was able to remove the old "Python Launcher" in Programs and Features.
