### ISSUE TITLE
numerous items in list have same id

### ISSUE THREAD

**Issue by s0urce-c0de** [python/cpython#115788]
# Bug report

### Bug description:

If I have multiple list that are the same in one list, the id of each list is the same. This can be an issue if people need multiple variations of one list.
```python
>>> n=[["y", "y", "y"], ["y", "y", "y"], ["y", "y", "y"]]
>>> for i in n:
...   print(id(n))
... 
140332368894784
140332368894784
140332368894784
>>> 
```

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
You are printing the id of the outer list `n` multiple times, so no wonder it's the same. The inner lists will definitely all be different.

The strings `"y"` may or may not have the same id(), as that's an implementation detail, but program logic shouldn't depend on these strings being identical.
