### ISSUE TITLE
Incorrect expected output in fibonacci program example

### ISSUE THREAD

**Issue by shivenducs1136** [python/cpython#115718]
# Documentation

Output of the [fibonacci program](https://docs.python.org/3/tutorial/introduction.html#:~:text=0%2C1%2C1%2C2%2C3%2C5%2C8%2C13%2C21%2C34%2C55%2C89%2C144%2C233%2C377%2C610%2C987%2C) which demostrates usage of `end=","` argument in print() method is incorrect  

## Actual Output 

 - Primary prompt symbol not present here
 
![image](https://github.com/python/cpython/assets/77795429/d4a29e42-8a33-4df5-af4a-a740e182d39c)

## Expected Output

 - Observe primary prompt symbol (>>>)

![image](https://github.com/python/cpython/assets/77795429/30074748-9541-4547-9f5b-19e6315da0eb)

### Reason

`end=","` argument is used to replace new line character with the specified character, thus new line is not printed.

**Comment by terryjreedy** [comment]
What you labelled 'Actual Output' is what the doc shows and what both the CPython REPL and what IDLE print  *in response to the given input*.  IDLE prints the next prompt on the next line, as it can and does look where the cursor is before printing the prompt, and inserts a newline as needed.   CPython REPL prints the prompt 'blindly' (tested with 3.8  and 3.13), as it assumes a 'dumb terminal' that cannot be queried and does not try to keep track of whether it last printed a newline or not.  In interactive mode, there is always a followup prompt after the end of the last output, and the docs consistently omit it, regardless of where it is.

I think this consistency should be kept and this issue closed.

@pablogsal A side note: now that you are optionally using a smart terminal feature for color, is there a smart terminal feature to inquire as to where the cursor is?  If so, do you think the REPL should ask?

**Comment by pablogsal** [comment]
> @pablogsal A side note: now that you are optionally using a smart terminal feature for color, is there a smart terminal feature to inquire as to where the cursor is? If so, do you think the REPL should ask?

That will be possible with the new REPL we are working on that uses `ncurses` underneath but with our current technology there isn't a way to query this unfortunately.

**Comment by terryjreedy** [comment]
In the meanwhile, the doc should remain as it is.

**Comment by shivenducs1136** [comment]
Thanks for explaination and consideration @terryjreedy @pablogsal
