### ISSUE TITLE
Make PyCode_GetFirstFree a PEP-689 unstable API

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#115756]
> It was and it wasn't. We don't really want to expose it, but if we don't then Cython and other C extensions will access the internal fields directly, which is worse.
>
> Now that we have an unstable API, it should probably be part of that.
I'd like all code object C APIs to be unstable, but it's probably too late for that.
>
> Maybe rename it to `PyUnstableCode_GetFirstFree`?

_Originally posted by @markshannon in https://github.com/python/cpython/pull/115654#discussion_r1497192136_
            

### Linked PRs
* gh-115781

**Comment by erlend-aasland** [comment]
`PyCode_GetFirstFree` was introduced in PR #100721.

**Comment by encukou** [comment]
The name should be `PyUnstable_Code_GetFirstFree` (extra underscore).

**Comment by wrongnull** [comment]
Souldn't this be applied to ```PyCode_GetNumFree``` too?

**Comment by vstinner** [comment]
The function is part of Python 3.12 release, and *after* Python 3.12, you want to downgrade the API to the unstable API in Python 3.13? It sounds too late for me, no?

**Comment by erlend-aasland** [comment]
> The function is part of Python 3.12 release, and _after_ Python 3.12, you want to downgrade the API to the unstable API in Python 3.13? It sounds too late for me, no?

I'll leave that for the C API WG ;)

**Comment by encukou** [comment]
> The function is part of Python 3.12 release, and after Python 3.12, you want to downgrade the API to the unstable API in Python 3.13? It sounds too late for me, no?

Downgrading means that the public name, `PyCode_GetFirstFree`, will be deprecated, but will be kept until the function's signature/behaviour changes (minimum 2 releases).
Do you think this should not be done?

**Comment by vstinner** [comment]
> Do you think this should not be done?

I don't think that it's worth it. If later, the function becomes stable, depending on the Python version, PyCode_GetFirstFree() may be deprecated or not, it sounds unpleasant for a minor issue.

Honestly, just elaborate the documentation to express more clearly the stability contract, no?

**Comment by encukou** [comment]
> If later, the function becomes stable

I don't think the intention is to ever make it stable. It exposes an implementation detail: free variables follow other ones in a code object.

> just elaborate the documentation to express more clearly the stability contract

This is the way to do that.

**Comment by vstinner** [comment]
Ping @markshannon

**Comment by encukou** [comment]
Thank you!
