### ISSUE TITLE
On WASI, time.process_time is not in seconds

### ISSUE THREAD

**Issue by encukou** [python/cpython#115714]
In a fresh WASI build, `time.process_time`, which should be in seconds, counts 10⁶ times faster than `time.time`:

```
>>> import time
>>> time.time(); time.process_time()
1708435312.596558
4775079350.12
>>> time.time(); time.process_time()
1708435313.0949461
4780063256.54
>>> time.get_clock_info('process_time')
namespace(implementation='clock_gettime(CLOCK_PROCESS_CPUTIME_ID)', monotonic=True, adjustable=False, resolution=1e-09)
```

It looks like [WASI might remove `CLOCK_PROCESS_CPUTIME_ID`](https://github.com/WebAssembly/wasi-libc/issues/266). Should we wait for that? Remove it from Python sooner? Work around the issue?

(Codespaces has an “unexpected error” for me right now, so I built the container from `.devcontainer/Dockerfile` directly. Hope that doesn't affect the result.)

### Linked PRs
* gh-115757

**Comment by encukou** [comment]
@brettcannon, your thoughts on this?

**Comment by brettcannon** [comment]
> I built the container from `.devcontainer/Dockerfile` directly. Hope that doesn't affect the result.

It shouldn't. All Codespaces does on top of that container is inject a git checkout and configures VS Code automatically.

**Comment by encukou** [comment]
It turns out the return value of `sysconf(_SC_CLK_TCK)` (number of clock ticks per second) is incorrect, at least for scaling times from `CLOCK_PROCESS_CPUTIME_ID` and `times()`.

I'll prepare a PR that avoids calling them in `time`.
