### ISSUE TITLE
Exercise the debug structs placed in PyRuntime

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#115773]
To avoid breaking external inspection, profilers and debuggers too often or to make supporting them too difficult, we added a [special offset struct](https://github.com/python/cpython/blob/5f7df88821347c5f44fc4e2c691e83a60a6c6cd5/Include/internal/pycore_runtime.h#L53) in the `PyRuntime` structure. Unfortunately there is nothing testing that this offsets are correct or that they are enough to analyse or profile a Python application on their own. To fix this, we should add some testing that exercises the offsets and ensure they are enough to serve the purpose they were added.

### Linked PRs
* gh-115774
* gh-116212
* gh-118591
* gh-120112
* gh-121283

**Comment by encukou** [comment]
@pablogsal, you probably have the most context here. Could you check #125402 and #129430?

**Comment by pablogsal** [comment]
I will try to take a look today

**Comment by encukou** [comment]
Thank you!
