### ISSUE TITLE
Bytecodes cleanup: promote TIER_{ONE,TWO}_ONLY to properties

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#115778]
Instead of
```
op(FOO, (left, right -- res)) {
    TIER_TWO_ONLY
    <actual code>
}
```
I'd like to be able to write
```
tier2 op(FOO, (left, right -- res)) {
    <actual code>
}
```

### Linked PRs
* gh-115815

**Comment by gvanrossum** [comment]
If someone wants to pick this up I'm happy to provide some clues as to where to make changes (but multi-file grep goes a long way. :-)

**Comment by Eclips4** [comment]
I would like to pick this up if you don't mind :)

**Comment by gvanrossum** [comment]
@Eclips4 Go for it! Remember to run `make regen-cases` frequently (after each change to the generator and each change to bytecodes.c or the redundancy eliminator input file).

**Comment by gvanrossum** [comment]
For the CI failures, see gh-115859.  Once that's fixed, please merge the latest main and push again.
