### ISSUE TITLE
Constant propagation for _TO_BOOL

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#115759]
# Feature or enhancement

### Proposal:

Parent issue https://github.com/python/cpython/issues/115506

### Has this already been discussed elsewhere?

No response given

**Comment by markshannon** [comment]
What is the issue?

**Comment by gvanrossum** [comment]
@Fidget-Spinner: How does this relate to gh-115685?

**Comment by gvanrossum** [comment]
We've done all we can in gh-115686.
