### ISSUE TITLE
segfault with PYTHON_LLTRACE=3 and PYTHON_UOPS=1 on debug build

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#115735]
# Crash report

### What happened?

On main, run
```
PYTHON_UOPS=1 PYTHON_LLTRACE=3 ./python 
```

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-115736

**Comment by Eclips4** [comment]
Bisected to 7b21403ccd16c480812a1e857c0ee2deca592be0
