### ISSUE TITLE
Double ``versionadded`` labels in ``typing.NoReturn`` doc

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#115777]
I think it was added by mistake:
https://github.com/python/cpython/blob/5f7df88821347c5f44fc4e2c691e83a60a6c6cd5/Doc/library/typing.rst#L957-L958

cc @JelleZijlstra @AlexWaygood 

### Linked PRs
* gh-116269
* gh-116361
* gh-116362

**Comment by Eclips4** [comment]
There's also a couple double ``versionadded`` labels in typing.rst: `typing.Counter`, `typing.Deque`, `typing.ChainMap`, `typing.AsyncContextManager`. For me it is not obvious why is this so.

**Comment by JelleZijlstra** [comment]
These are correct. The names were added in 3.5.4 and 3.6.2; i.e., they were not present in 3.5.3 and 3.6.1. Maybe there's a way to make that more clear.

**Comment by serhiy-storchaka** [comment]
I think that this is incorrect. Double `versionadded` directives only occur in `typing.rst`. In the rest of the documentation, and in most cases in `typing.rst`, other principle is used -- specify the earliest version such that all releases between the specified version and the documented version should have such feature. For example, if the feature was added in 3.7 and backported to 3.5.4 and 3.6.2, then the docs in the 3.6 and 3.7 branches will contain version 3.6.2, and the docs in the 3.3 branch will contain version 3.5.4.
