### ISSUE TITLE
`PCbuild\build.bat` script cannot generate `Python\generated_cases.c.h` files and so on

### ISSUE THREAD

**Issue by littlebutt** [python/cpython#115700]
# Bug report

### Bug description:

When I ran the script `PCbuild/build.bat` with and without the `--regen` argument, it could not regenerate `Python\generated_cases.c.h` file. I found the files in `Tools\cases_generateor` changed. Is it the reason why the script fail?

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-115708

**Comment by Eclips4** [comment]
The same applies for `tier2_redundancy_eliminator_cases.c.h`. cc @kenjin

**Comment by Eclips4** [comment]
@littlebutt can you confirm that #115708 solved the issue?

**Comment by littlebutt** [comment]
> @littlebutt can you confirm that #115708 solved the issue?

It works, thanks.
