### ISSUE TITLE
New warning: `variable ‘callable’ set but not used [-Wunused-but-set-variable]`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#115846]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/115815 and https://github.com/python/cpython/pull/113674

### CPython versions tested on:

CPython main branch

**Comment by Fidget-Spinner** [comment]
Oops. Can you please help me add the relevant `(void)callable` and stuff in `tier2_redundancy_eliminator_bytecodes.c`?

**Comment by Fidget-Spinner** [comment]
Nevermind, I will address them in https://github.com/python/cpython/pull/115848.

**Comment by Fidget-Spinner** [comment]
Should be fixed now I think.

**Comment by Eclips4** [comment]
Thanks Ken!
