### ISSUE TITLE
Doc: obsolete reference to MSI packages

### ISSUE THREAD

**Issue by partev** [python/cpython#115872]
https://docs.python.org/3.13/using/windows.html page refers to "MSI packages" in the following sentence:
To make Python available, the CPython team has compiled Windows installers (**MSI packages**) with every release for many years.

However, MSI packages have been replaced regular Windows installer since python-3.5; for example see here:
https://docs.python.org/3.13/whatsnew/3.5.html
Windows improvements:
* A new installer for Windows has replaced the old MSI.

because of this the reference for MSI packages should be removed from documentation here: https://docs.python.org/3.13/using/windows.html

### Linked PRs
* gh-115873
* gh-115876
* gh-115877

**Comment by terryjreedy** [comment]
I grepped Doc/*.rst and there are no other MSI references.  (There are some `.*MSI.*` words line MSIE (explorer).)  So unless there are MSIs hiding in comments or docstrings, which I think is pretty unlikely and not so visible to user if there are, this issue is truly done.
