### ISSUE TITLE
`ast.parse()` believes valid context manager py38 syntax to be invalid when `feature_version=(3, 8)` is passed

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#115881]
# Bug report

### Bug description:

The following code is completely valid on Python 3.8:

```python
from contextlib import nullcontext

with (
    nullcontext() if bool() else nullcontext()
):
    pass
```

However, following https://github.com/python/cpython/commit/0daba822212cd5d6c63384a27f390f0945330c2b (which was backported to Python 3.11 and Python 3.10), `ast.parse()` incorrectly throws an error if you try to parse this code with `feature_version=(3, 8)`:

```pycon
% python                                                                                                                         
Python 3.10.6 (main, Feb 24 2024, 10:35:05) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> source = """
... with (
...     nullcontext() if bool() else nullcontext()
... ):
...     pass
... """
>>> ast.parse(source, feature_version=(3, 8))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/alexw/.pyenv/versions/3.10.6/lib/python3.10/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 5
    pass
        ^
SyntaxError: Parenthesized context managers are only supported in Python 3.9 and greater
```

Cc. @hauntsaninja / @pablogsal 

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-115920
* gh-115959
* gh-115960
* gh-115980
* gh-116173
* gh-116174

**Comment by pablogsal** [comment]
I think there isn't going to be any super clean way to do this because this new construct has a non trivial syntactic overlap with the case reported here. This was precisely what made it impossible to do with the old parser. I think the best way is to revert https://github.com/python/cpython/commit/0daba822212cd5d6c63384a27f390f0945330c2b

**Comment by hauntsaninja** [comment]
Thanks for reporting! I think we can fix by adding another grammar rule which isn't too bad, but I agree reverting could be fine.

By the way, I notice that `with (contextlib.nullcontext(),): ...` and `with (contextlib.nullcontext(),): ...` parse differently with old and new parser! :-)

**Comment by pablogsal** [comment]
I prefer to revert the commit. The grammar is already quite complicated and we are automatically generating docs from it so I would recommend you try to keep complexity controlled

**Comment by pablogsal** [comment]
> By the way, I notice that `with (contextlib.nullcontext(),): ...` and `with (contextlib.nullcontext(),): ...` parse differently with old and new parser! :-)

Maybe it's because I am reading this in a phone but I cannot see any difference 😅

![image](https://github.com/python/cpython/assets/11718525/1ffe0795-43c1-4258-a3d5-5f6c97fe68eb)

**Comment by AlexWaygood** [comment]
> I prefer to revert the commit. The grammar is already quite complicated and we are automatically generating docs from it so I would recommend you try to keep complexity controlled

We'll want to backport the fix as well, so I agree that simply reverting feels safer for now (and _possibly_ consider a more complex solution for Python 3.13+ only? But I'll defer to those more experienced with hacking on the parser on whether that's worth it or not :)

**Comment by AlexWaygood** [comment]
> Do I remember correctly that `mypy` uses this? Is it still relevant?

Yes, we do use it at mypy! That's how I came across this issue in the first place -- after we started using a new version of black at mypy, I realised mypy could no longer type check its own codebase if you were using `--python-version 3.8` on Python 3.12: https://github.com/python/mypy/issues/16945

**Comment by lysnikolaou** [comment]
Got it. Thanks for the context @AlexWaygood!

**Comment by pablogsal** [comment]
The problem with `feature_version` is that is quite challenging to get this working in a consistent fashion. Different syntax constructs are in different version of the parser and having `feature_version` working consistently forces us to technically parse multiple grammars and our parser is not prepared to do so unless there is a fundamental check in the AST nodes that we can pinpoint to tell the difference.

I think at the very least we should document the limitations in the docs, to ensure that the fact that for example context managers with parentheses may not be detected is clear to end users.

What do people think?

**Comment by AlexWaygood** [comment]
The fix for the original issue has been merged and backported, but I'll leave this open so we can continue discussing what to do about the broader issue, and if necessary link more PRs here

**Comment by lysnikolaou** [comment]
Yup, let's document this at the very least. If we were ever to remove this, we'd have to go through a deprecation, cause it seems to be used in quite a few places.

**Comment by hauntsaninja** [comment]
Thanks Alex! Yes, I believe it's used by at least mypy, black, pytype. We should document more clearly that`feature_version` is a "best effort" sort of thing, here's a PR with some possible wording: https://github.com/python/cpython/pull/115980

I think the functionality is useful, even if limited, so I'd prefer not to deprecate

**Comment by hauntsaninja** [comment]
Okay, we did the revert, we've updated docs and I did the backports, so I think we can close. Let me know if I missed something!
