### ISSUE TITLE
Add operator.is_none()

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#115808]
# Feature or enhancement

### Proposal:

With floating point data, the `float('NaN')` special value is commonly used as a placeholder for missing values.  We provide `math.isnan` to support stripping out those values prior to sorting or summation:

```python
>>> from math import isnan
>>> from itertools import filterfalse
>>> data = [3.3, float('nan'), 1.1, 2.2]
>>> sorted(filterfalse(isnan, data))
[1.1, 2.2, 3.3]
```

For non-float data, the `None` special value is commonly used as a placeholder for missing values.  I propose a new function in the operator module analogous to `math.isnan()`:

```pycon
>>> data = ['c', None, 'a', 'b']
>>> sorted(filterfalse(is_none, data))
['a', 'b', 'c']
```

This helps fulfill a primary use case for the operator module which is to support functional programming with `map()`, `filter()`, etc.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-115814

**Comment by rhettinger** [comment]
For convenience, it might also be nice to have `is_not_none()`.   The matches what would be done in a typical list comprehension: `cleaned = [x for x in data if x is not None]`.   Also, it would save the need to know about *filterfalse()* in itertools module which is less well known that builtin functions.  A simple builtin *filter()* call will suffice: `mean(filter(is_not_none, data))`.

**Comment by AlexWaygood** [comment]
> For convenience, it might also be nice to have `is_not_none()`

Agreed -- I was going to suggest this. It also fits the general pattern of the `operator` module: we have both `is_` and `is_not`, both `truth` and `not_`, etc.
