### ISSUE TITLE
test_monitoring contains hardcoded line numbers

### ISSUE THREAD

**Issue by swtaarrs** [python/cpython#115836]
# Bug report

### Bug description:

`test_lines_single`, `test_lines_loop`, and `test_lines_two` in [`test_monitoring.LinesMonitoringTest`](https://github.com/python/cpython/blob/main/Lib/test/test_monitoring.py#L520) all contain some hardcoded line numbers in their expected values. They should consistently use offsets from `co_firstlineno` on the relevant code objects instead.

I ran into this while adding a test for gh-115832, and already have a fix ready to put up as a PR.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-115837

**Comment by itamaro** [comment]
Fix merged, closing the issue (please reopen if there's more left to do here).
