### ISSUE TITLE
Refactor operators

### ISSUE THREAD

**Issue by ThexXTURBOXx** [python/cpython#115830]
Reviews https://github.com/python/cpython/pull/115814#discussion_r1499490930, https://github.com/python/cpython/pull/115814#discussion_r1499490790, and https://github.com/python/cpython/pull/115814#discussion_r1499495023 show that there are a few things to refactor and/or optimize in regard to operators.
Furthermore, the documentation is sometimes rather hard to read without quotes, such as e.g., `"Same as a is None."` (which would be much better as `"Same as 'a is None'."` like @sobolevn proposed).

TODO:
 - Optimize C implementations as e.g., shown in https://github.com/python/cpython/pull/115814#discussion_r1499490930
 - Rephrase documentation as e.g., shown in https://github.com/python/cpython/pull/115814#discussion_r1499490790 and https://github.com/python/cpython/pull/115814#discussion_r1499495023

**Comment by sobolevn** [comment]
My 2c: the whole module refactoring is usually not-a-so-good idea :)
It might introduce new bugs, it damages the git history and does not bring us much value.

So, let's wait for some other voices: do people find this valuable enough? Or maybe they don't :)

I personally think that adding `'a is None'` is a good idea, it make the docs much nicer. But, adding `PyBool_FromLong` is very optional.

**Comment by rhettinger** [comment]
I agree with sobolevn that whole module refactoring isn't warranted here.  It would be a lot of code churn but offer zero value to the end user.
