### ISSUE TITLE
f-string extra braces with set() variable

### ISSUE THREAD

**Issue by ba05** [python/cpython#115829]
# Bug report

### Bug description:

Is this a bug? Output has braces when I don't think it should:

Input:
```python
f"Test foo {set([x for x in [1,2]])}"
```
Output:
```python
'Test foo {1, 2}'
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
This is not a bug. It's the same as:
```pycon
>>> str(set([x for x in [1,2]]))
'{1, 2}'
```
