### ISSUE TITLE
A problem with document annotations

### ISSUE THREAD

**Issue by jzsn2018** [python/cpython#115839]
# Documentation

I found a wrong comment in the documentation, the screenshot is as follows， The link is https://docs.python.org/3.10/tutorial/introduction.html#lists

![image](https://github.com/python/cpython/assets/33984354/a0b95964-ed08-4e83-bfdd-bc6c91d6c077)

The list here is directly append 216 instead of append 6 **3 , so the comment here can't be said to add the cube of 6

**Comment by ericvsmith** [comment]
Well, the cube of 6 is 216, so it's technically correct. I'm not sure why the example is trying to be so tricky, but it's not wrong.

**Comment by CharlieZhao95** [comment]
In my opinion, this comment will not confuse anyone. We can use `list.append(number)` or `list.append(expression)` here, and the comment explains why it's 216 here (because it's cube of 6).

**Comment by hugovk** [comment]
It was added in https://github.com/python/cpython/commit/86aecc360f8fd635a91c5b7ffe63b1b9a3e17a31 11 years ago by @ezio-melotti, via https://bugs.python.org/file30312/issue14097-3.diff in https://github.com/python/cpython/issues/58305.

Ezio: any chance you remember the reason for `216` rather than `6 ** 3`?

Maybe it's better like this; as @CharlieZhao95 points out, it's teaching two ways of appending. And this is a tutorial.

**Comment by ezio-melotti** [comment]
> Ezio: any chance you remember the reason for 216 rather than 6 ** 3?

I do: every cube before that was added as an `int` literal -- switching to `7 ** 3` shows that `.append` (like any other call) accepts arbitrary expressions and not just single (`int`) literals (or variables).  In addition, it ensures that the value is correct, and the result can be seen in the output a couple of lines later.

**Comment by hugovk** [comment]
Okay, thanks everyone, let's leave it as is! 🧊

**Comment by ericvsmith** [comment]
I'm okay with leaving it as-is. But maybe a comment explaining what's going on? It's obvious to experts, but without a comment as to why, maybe it's confusing.

**Comment by ezio-melotti** [comment]
I'm not sure it's worth explaining what's going on.  The focus here is explaining how lists work, and it's done by alternating short sentences and examples.  The fact that you can pass both literals and expressions is there more as a reminder that it can be done, and that it works for methods like `.append` too, but it's not the focus of this section.

It also seems to me that the confusion is more about the reason why I picked two different ways of adding cubes (somewhat understandable), then the functioning of the code itself.  IOW, people seem to understand that both ways work, and that's all that matters IMHO.
