### ISSUE TITLE
built in find function

### ISSUE THREAD

**Issue by mango-danbikim** [python/cpython#115849]
# Feature or enhancement

### Proposal:

```python
a = 'string'
b = a.find('s', 0, 0)
print(b)
```
'''
In upper code, start 0 to end 0 may represent index 0, but output of the code is -1.
(python 3.12.2)
For example, below code shows efficiency when supposing a to a index is find a.
Because,except for sub_string = None, if Len(sub_string) is 1.
it start 0 to 0,then the code loses my intention.
There's no reason find function isn't modified.
```
1def count_substring(string, sub_string) -> int:
2   c = 0
3   for i in range(len(string)):
4      if string.find(sub_string, i, i+len(sub_string)-1) != -1:
5         c += 1

    return c

if __name__ == '__main__':
    string = input().strip()
    sub_string = input().strip()
    
    count = count_substring(string, sub_string)
    print(count)
```

### Has this already been discussed elsewhere?

No response given

**Comment by ronaldoussoren** [comment]
The `str.find` method behaves as documented:

```
find(...) method of builtins.str instance
    S.find(sub[, start[, end]]) -> int

    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.

    Return -1 on failure.
```

In your example both start and stop are 0, which means your looking for `'s'` in an empty substring of `a`.

Please ask questions about using Python on https://discuss.python.org/c/users/7

**Comment by mango-danbikim** [comment]
> The `str.find` method behaves as documented:
> 
> ```
> find(...) method of builtins.str instance
>     S.find(sub[, start[, end]]) -> int
> 
>     Return the lowest index in S where substring sub is found,
>     such that sub is contained within S[start:end].  Optional
>     arguments start and end are interpreted as in slice notation.
> 
>     Return -1 on failure.
> ```
> 
> In your example both start and stop are 0, which means your looking for `'s'` in an empty substring of `a`.
> 
> Please ask questions about using Python on https://discuss.python.org/c/users/7

Good
