### ISSUE TITLE
Document in the main Enum page that super().__new__ should not be called

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#115821]
The HowTo page says [here](https://docs.python.org/3/howto/enum.html#when-to-use-new-vs-init) that `super().__new__` should not be called in user-defined `__new__` methods of an Enum (subclass), along with a short explanation for why it is the case.

But this is a hard limitation, not a bonus explanation. When I tried using the super, I ended up with an exception I didn't understand and the doc entry for `Enum.__new__` didn't help me at all as per why that was failing.

The explanation should probably remain in the howto page, but a similar red warning should be added to [`Enum.__new__`](https://docs.python.org/3/library/enum.html#enum.Enum.__new__), saying that calling `super().__new__` inside user-defined `__new__` functions is forbidden.

### Linked PRs
* gh-116063
* gh-116065

**Comment by ethanfurman** [comment]
That's a good idea.

Separately, how could the error message you received be made clearer?

**Comment by Gouvernathor** [comment]
The traceback was as follows :
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\parliamentarch\__init__.py", line 54, in <module>
    class FillingStrategy(enum.StrEnum):
  File "C:\Program Files\Python312\Lib\enum.py", line 593, in __new__
    raise exc.with_traceback(tb)
  File "C:\Program Files\Python312\Lib\enum.py", line 583, in __new__
    enum_class = super().__new__(metacls, cls, bases, classdict, **kwds)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python312\Lib\enum.py", line 266, in __set_name__
    enum_member = enum_class._new_member_(enum_class, *args)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\parliamentarch\__init__.py", line 56, in __new__
    super().__new__(cls, value)
  File "C:\Program Files\Python312\Lib\enum.py", line 1138, in __new__
    raise TypeError("%r has no members defined" % cls)
TypeError: <enum 'FillingStrategy'> has no members defined
>>>
```
I couldn't tell you how to solve it because I don't know any more about the situation than what the howto warning says.
