### ISSUE TITLE
Remove Emscripten from the docs

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#115977]
Since Emscripten is no longer a tier 3 platform we should probably remove mentions of it from the docs.

**Comment by tavallaie** [comment]
how we can help this issue? I need to know more to solve it.

**Comment by brettcannon** [comment]
Basically the docs say things like "Emscripten" or "not Emscripten" about platform support. Pretty much all mentions of "Emscripten" in the documentation should probably be removed.

**Comment by tavallaie** [comment]
Thansk, I will remove all of them, if there is any docs or related information about removing Emscripten like "why Emscripten is no longer a tier 3 platform "can mention in my PR please help me to find them.

**Comment by brettcannon** [comment]
> Thansk, I will remove all of them, if there is any docs or related information about removing Emscripten like "why Emscripten is no longer a tier 3 platform "can mention in my PR please help me to find them.

You don't need an official link; the core team knows the "why".

**Comment by ned-deily** [comment]
It looks like there are still some Emscripten references in the docs beyond the ones removed by #117057.

**Comment by freakboy3742** [comment]
@ned-deily Which references in particular are you referring to? 

As noted in [this comment](https://github.com/python/cpython/pull/117057#discussion_r1531598937), some of the Emscripten references were left in deliberately, reflecting the fact that the *functionality* exists, even if the platform isn't tier 3. This is analogous to the state of Android in previous releases - there are a handful of references to Android in the docs, even though Android isn't Tier 3 in those releases. 

I'm happy to do the cleanup on this if needed; I just need to be clear about what I'm cleaning up :-)

**Comment by nineteendo** [comment]
"Emscripten" is found in `library/intro.rst`, `library/sys.rst` & the release notes like mentioned in your comment. But also in `using/configure.rst`. If that's deliberate, then this issue should be closed, otherwise they should be removed from the latter.

**Comment by freakboy3742** [comment]
My read is that the mentions in `using/configure.rst` is in the same category as the ones in `library` - it's describing how to configure a build for Emscripten. That is still a valid configuration, just not a Tier 3 supported configuration.

**Comment by nineteendo** [comment]
OK, then I think you can close this.

**Comment by freakboy3742** [comment]
@ned-deily Did you have any specific concerns, or are you OK with closing this?

**Comment by ned-deily** [comment]
Sounds good, I think we can close this again.
