### ISSUE TITLE
Non-equation in random.uniform

### ISSUE THREAD

**Issue by pochmann3** [python/cpython#115921]
# Documentation

The [`random.uniform`](https://docs.python.org/3/library/random.html#random.uniform) doc says:

> the equation `a + (b-a) * random()`

That's not an equation. Just an expression.

The page mentions "equation" twice more right above, but I think those refer to actual equations like the `pdf(x) = ...` for [`random.gammavariate`](https://docs.python.org/3/library/random.html#random.gammavariate) and are thus correct.

### Linked PRs
* gh-115927
* gh-115928
* gh-115929

**Comment by terryjreedy** [comment]
Yes, `equation` should be `expression`.  For a uniform distribution, the equation is pdf = 1/(b-a) on [a, b], 0 elsewhere, so that the integral over the real line is 1.0.  PR soon.
