### ISSUE TITLE
Add map_pairwise to builtin functions

### ISSUE THREAD

**Issue by edward-b-1** [python/cpython#115912]
# Feature or enhancement

### Proposal:

```python
def all_equal(iterable):
    return all(map(operator.eq, iterable[1:], iterable[:-1])
```

Consider the following requirement for a function or operation:

- A function which takes as input an iterable and checks to see if all elements are equal

This is a fairly common requirement, but Python does not have a builtin function to support this. There are many ways to calculate the result using Python code, however for performance reasons a lazy-evaluated or short-circuit return builtin would be useful.

On the other hand, this operation can be composed from less complex operations.

- A "pairwise" version of `map` which rather than applying a unary function to an iterable applies a binary function to an iterable
- The existing builtin function `all`, which is a short circuit function (returns early if condition not met)

For this to be sensible, map would have to be lazy evaluated. I believe this is the case, please do correct me if I am wrong.

I would be interested in doing the work for this assuming that the community considers it to be a useful addition to the Python core library. I have never attempted to modify the Python source code before, but I know both C and Python, so I should be able to figure out how to do this, perhaps with some assistance. It would also be a good opportunity for me to learn more about the internal workings of Python, which is something I am interested in.

Could I get some initial feedback on whether or not adding something like this would be considered useful?

I'm not totally sure exactly how it should be done. If a `map_pairwise` was introduced, then why not higher-order versions which apply functions consisting of 3 arguments, or more?

I suppose one arguments against having a version which applies a trinary function, function of 4 arguments, etc, could be how to do the stride? For unary and binary it is obvious. Unary functions are applied to each element. A binary function is applied to every pair of elements. But then what do you do with a function which takes three arguments?

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
Hello!
You should create a topic on https://discuss.python.org/c/ideas/6 for further discussion.
From my point of view, it may take place not in builtins, but in `functools`.
Now I'm going to close this, later we can reopen this if necessary.

**Comment by edward-b-1** [comment]
Ok, I'll repost there. Thanks
