### ISSUE TITLE
xml.etree.ElementTree.Element's .text method is quadratic in appending content

### ISSUE THREAD

**Issue by alexmv** [python/cpython#115971]
# Bug report

### Bug description:

Python's text strings are optimized such that appends to them are linear in time:
```
In [1]: %%timeit -n1 -r1
   ...: text = ""
   ...: for i in range(400000):
   ...:     text += "<"
   ...:
64.4 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [2]: %%timeit -n1 -r1
   ...: text = ""
   ...: for i in range(800000):
   ...:     text += "<"
   ...:
144 ms ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

However, attempting the same with the `.text` property of an `xml.etree.ElementTree.Element` object finds it to be quadratic:
```
In [4]: %%timeit -n1 -r1
   ...: element = xml.etree.ElementTree.Element("a")
   ...: element.text = ""
   ...: for i in range(400000):
   ...:     element.text += "<"
   ...:
2.55 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [5]: %%timeit -n1 -r1
   ...: element = xml.etree.ElementTree.Element("a")
   ...: element.text = ""
   ...: for i in range(800000):
   ...:     element.text += "<"
   ...:
19.7 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

This makes libraries that depend on `xml.etree` easily susceptible to denial-of-service attacks:
```
In [6]: import html5lib

In [7]: %timeit -n1 -r1 html5lib.parse("&lt;" * 200000)
3.14 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [8]: %timeit -n1 -r1 html5lib.parse("&lt;" * 400000)
9.73 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)

In [9]: %timeit -n1 -r1 html5lib.parse("&lt;" * 800000)
28.2 s ± 0 ns per loop (mean ± std. dev. of 1 run, 1 loop each)
```

(thanks to @andersk for the investigation)

### CPython versions tested on:

3.10, 3.11, CPython main branch

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
dup of https://github.com/python/cpython/issues/99862

> Python's text strings are optimized such that appends to them are linear in time:

Not really, CPython tries to do it when it's convenient and possible, string is an immutable type so it's not always possible. As of now, I believe, only inplace add of local variables are optimized to do that.
