### ISSUE TITLE
Improve documentation for `pprint` module

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#115986]
# Documentation

The documentation for the `pprint` module could be improved in many respects:
- Most users will probably only ever need to use `pprint.pp()` or `pprint.pprint()`, but these are buried halfway down the module. It would be nice if these were the first things on the page.
- All examples in the documentation use `pprint.pprint()`, which has some unexpected behaviour. For example, it sorts dictionaries by default, which is somewhat unintuitive now that dictionaries maintain insertion order. I suggest we change the examples to use `pprint.pp()` instead, which has the more intuitive default of `sort_dicts=False`.
- Similarly, the docs for `pprint.pprint()` could explicitly call out that it has unintuitive defaults for things such as `sort_dicts` and link to `pprint.pp()`
- Some links in the module's documentation incorrectly point to the module itself (`pprint`) instead of the function `pprint.pprint()`.

These don't all necessarily need to be tackled in the same PR

### Linked PRs
* gh-116019
* gh-116061
* gh-116064
* gh-116085
* gh-116104
* gh-116382
* gh-116383
* gh-116614
* gh-117196
* gh-117197
* gh-117401
* gh-117403
* gh-118146
* gh-121098
* gh-121099

**Comment by Privat33r-dev** [comment]
Can I be assigned? I can do most of it in a day or two.

**Comment by gaogaotiantian** [comment]
The fact `pp` is not an alias for `pprint` surprised me. Personally I'd prefer to use a function that better explains itself (`pprint` is easier to understand than `pp`), without knowing the difference between them. I have some doubts about using `pp` as the default in all the examples, but that's just my two cents.

**Comment by Privat33r-dev** [comment]
### Progress tracker

> - [ ] Most users will probably only ever need to use `pprint.pp()` or `pprint.pprint()`, but these are buried halfway down the module. It would be nice if these were the first things on the page.
> - [ ] All examples in the documentation use `pprint.pprint()`, which has some unexpected behaviour. For example, it sorts dictionaries by default, which is somewhat unintuitive now that dictionaries maintain insertion order. I suggest we change the examples to use `pprint.pp()` instead, which has the more intuitive default of `sort_dicts=False`.
> - [ ] Similarly, the docs for `pprint.pprint()` could explicitly call out that it has unintuitive defaults for things such as `sort_dicts` and link to `pprint.pp()`
> - [ ] Some links in the module's documentation incorrectly point to the module itself (`pprint`) instead of the function `pprint.pprint()`.

**Comment by erlend-aasland** [comment]
The `pprint` docs could make good use of [param list markup](https://www.sphinx-doc.org/en/master/usage/domains/python.html#info-field-lists).

**Comment by erlend-aasland** [comment]
Quoting the pprint docs (regarding `PrettyPrinter.isreadable` and `PrettyPrinter.isrecursive`):

> The following methods provide the implementations for the corresponding
functions of the same names.  Using these methods on an instance is slightly
more efficient since new :class:`PrettyPrinter` objects don't need to be
created.

Is this something we want to highlight? (Are these functions much used at all?) At least, we _could_ mention this in the module level docs for `isreadable` and `isrecursive`.

**Comment by hugovk** [comment]
Thanks for https://github.com/python/cpython/pull/116614, @Privat33r-dev, merged!

Is there more to do for this issue?

**Comment by AlexWaygood** [comment]
I think the last remaining thing to do might be to move the documentation of the standard parameters the module uses from the documentation of the `PrettyPrinter` class (where they're somewhat buried) to a table near the top of the docs for the module as a whole, like I suggested in https://github.com/python/cpython/pull/116085#pullrequestreview-1908365757

**Comment by Privat33r-dev** [comment]
```rst
The formatted representation keeps objects on a single line if it can, and
breaks them onto multiple lines if they don't fit within the allowed width.
Construct :class:`PrettyPrinter` objects explicitly if you need to adjust the
width constraint.
```

Is it even true statement? Because we clearly can pass this as an argument to `pprint.pprint`/`pprint.pp` methods.

**Comment by erlend-aasland** [comment]
On #116085, we discussed having a separate table for the common parameters of `pprint.pprint` and `pprint.PrettyPrinter`. It seemed a good idea at the time, but now I'm not so sure anymore. I would like to reconsider using the Sphinx convention of param lists, so...:

1. in `pprint.pp`, we already point to `pprint.pprint` regarding the params; we can continue to do that (and `pprint.pprint` is just below, so it's easy to spot anyway)
2. in `pprint.pprint`, using Sphinx param list for handful of params
3. in `pprint.PrettyPrinter`, point to `pprint.pprint` (just like we do in `pprint.pp`)

Alternatively:

1. as above
2. create a Sphinx placeholder with the Sphinx param list
3. use the placeholder in `pprint.pprint` and `pprint.PrettyPrinter`; the list is not _that_ long, so IMO it is ok to duplicate it in the `pprint` docs

Thoughts?

**Comment by Privat33r-dev** [comment]
@erlend-aasland let's duplicate the params list in 1 function and in the class. DRY would be violated, but readability would be improved, which is more important than blindly following the principle.

**Comment by erlend-aasland** [comment]
> @erlend-aasland let's duplicate the params list in 1 function and in the class. DRY would be violated, but readability would be improved, which is more important than blindly following the principle.

Can you propose a PR?

**Comment by Privat33r-dev** [comment]
I guess it's resolved? :)

**Comment by erlend-aasland** [comment]
> @erlend-aasland, is there anything else you want to improve?

No, I think we're good for now :)
