### ISSUE TITLE
Bug in smtplib.py - Python 3.9 (and later?)

### ISSUE THREAD

**Issue by Mikebatty** [python/cpython#116051]
# Bug report

### Bug description:

While attempting to sent an email (using Kolab 16 - installed on a Alama 9 VM) containing HTML image date I generated the following trace back message:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/wallace/modules.py", line 166, in _sendmail
    _response = smtp.sendmail(sender, recipients, msg)
  File "/usr/lib64/python3.9/smtplib.py", line 875, in sendmail
    msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in position 4534: ordinal not in range(128)
```

Changing line 875 to:
```python
    msg = _fix_eols(msg).encode('utf-8')
```
seems to resolve the issue, but I am not sure if this the correct fix. 

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
There's not enough information here. 

Please provide a small, self-contained script that reproduces the error.

There are good tips at https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Mikebatty** [comment]
Hi Hugo,

When I send this email to my Googlemail account with using the unaltered 
smtplib.py code I get the following traceback:

Traceback (most recent call last):
   File "/usr/lib/python3.9/site-packages/wallace/modules.py", line 166, 
in _sendmail
     _response = smtp.sendmail(sender, recipients, msg)
   File "/usr/lib64/python3.9/smtplib.py", line 875, in sendmail
     msg = _fix_eols(msg).encode('ascii')
UnicodeEncodeError: 'ascii' codec can't encode character '\xa3' in 
position 4447: ordinal not in range(128)

When I change line 875 of smtplib.py to:

    msg = _fix_eols(msg).encode('utf-8')

as I've done for this email, it gets sent.

Note, this email has been sent from the new Kolab-16/AlmaLinux 9 email 
server that I am trying to setup and not my normal one which appears to 
work and is based on Kolab-16/Debian 10.

Regards,

Mike Batten. -------- Forwarded Message --------

  		SUBJECT:
  		Re: Request for new quotation

  		DATE:
  		Mon, 19 Feb 2024 14:46:42 +0000

  		FROM:
  		Mike Batten ***@***.***>

  		TO:
  		Great Gardeners ***@***.***>

Hi Michael,

I think you may not have received my earlier reply to you with out 
selection, so here goes again ...

Plants                                                                 
Cost each     No. required     Total Cost (ex VAT)
Ajuga reptans Braunhertz 9cm pot                     £1.95             
15                     £29.25
Athyrium filix-femina - Lady in red fern 2l pot     £5.75             4  
                      £23.00
Cyclamen coum album 9cm pot                         £3.35             7  
                      £23.45
Cyclamen hederifolium rose 9cm pot                 £3.35             7   
                     £23.45
Dicentra spectabilis 9cm pot                               £3.35         
    10                     £33.50
---------------------------------------------------------------------------------------------------------------
                                                              Totals      
                     43                    £132.65

Hope you get this this time and look forward to seeing you on the 6th

Regards,

Mike Batten.

On 09/02/2024 00:47, Great Gardeners wrote:

> Hi Mike,
> 
> The supplier just emailed me the plants with availability and costs.
> 
> They have a selection from each plant, so you can choose or we can do a 
> bigger mixture. Let me know your opinion.
> 
> All the prices exclude VAT, I would suggest to plant 60 plants there, 
> 15 from each plant. You can choose if you would like to have more 
> varieties of the same plants there or just four different plants.
> 
> Please find a selection below:
> Ajuga reptans Braunhertz 9cm pot -   £1.95
> Ajuga reptans Black Scallop 9cm pot - £1.95
> Athyrium filix-femina - Lady fern 2l pot - £6.75
> 
> Athyrium filix-femina - Lady in red fern 2l pot - £5.75
> Cyclamen coum album 9cm pot - £3.35
> Cyclamen coum rose 9cm pot - £3.35
> Cyclamen hederifolium album 9cm pot - £3.35
> Cyclamen hederifolium rose 9cm pot - £3.35
> Dicentra spectabilis 9cm pot  - £3.35
> 
> Once I know your opinion I will amend the quote and email it to you.
> 
> Have a nice weekend.
> 
> Kind regards,
> 
> Michael
> 
> Great Garden
> 
> Gardening  Landscaping  Design
> 
> E: ***@***.***
> 
> P: 01491 200 668
> 
> www.greatgarden.co.uk [1]


Links:
------
[1] http://www.greatgarden.co.uk/
--=_6aeeb2b62833027ae3cc13804bd6ac09
Content-Type: multipart/related;
 boundary="=_0d152236fac7a136062fd21ca6fdd518"

--=_0d152236fac7a136062fd21ca6fdd518
Content-Transfer-Encoding: quoted-printable
Content-Type: text/html; charset=UTF-8

<html><head><meta http-equiv=3D"Content-Type" content=3D"text/html; charset=
=3DUTF-8" /></head><body style=3D'font-size: 10pt; font-family: Verdana,Gen=
eva,sans-serif'>
<div id=3D"editbody1">
<div style=3D"font-size: 10pt; font-family: Verdana,Geneva,sans-serif;">
<div id=3D"v1editbody1">
<div style=3D"font-size: 10pt; font-family: Verdana,Geneva,sans-serif;">
<p>Hi Hugo,</p>
<p>When I send this email to my Googlemail account with using the unaltered=
 smtplib.py code I get the following traceback:</p>
<p>Traceback (most recent call last):<br />&nbsp; File "/usr/lib/python3.9/=
site-packages/wallace/modules.py", line 166, in _sendmail<br />&nbsp; &nbsp=
; _response =3D smtp.sendmail(sender, recipients, msg)<br />&nbsp; File "/u=
sr/lib64/python3.9/smtplib.py", line 875, in sendmail<br />&nbsp; &nbsp; ms=
g =3D _fix_eols(msg).encode('ascii')<br />UnicodeEncodeError: 'ascii' codec=
 can't encode character '\xa3' in position 4447: ordinal not in range(128)<=
/p>
<p><br />When I change line 875 of smtplib.py to:</p>
<p>&nbsp; &nbsp;msg =3D _fix_eols(msg).encode('utf-8')</p>
<p>as I've done for this email, it gets sent.</p>
<p>Note, this email has been sent from the new Kolab-16/AlmaLinux 9 email s=
erver that I am trying to setup and not my normal one which appears to work=
 and is based on Kolab-16/Debian 10.</p>
<p>Regards,</p>
<p>Mike Batten.</p>
-------- Forwarded Message --------
<div id=3D"v1v1forwardbody1">
<div>
<div class=3D"v1v1v1moz-forward-container">
<table class=3D"v1v1v1moz-email-headers-table" border=3D"0" cellspacing=3D"=
0" cellpadding=3D"0">
<tbody>
<tr>
<th align=3D"RIGHT" valign=3D"BASELINE" nowrap=3D"nowrap">Subject:</th>
<td>Re: Request for new quotation</td>
</tr>
<tr>
<th align=3D"RIGHT" valign=3D"BASELINE" nowrap=3D"nowrap">Date:</th>
<td>Mon, 19 Feb 2024 14:46:42 +0000</td>
</tr>
<tr>
<th align=3D"RIGHT" valign=3D"BASELINE" nowrap=3D"nowrap">From:</th>
<td>Mike Batten <a class=3D"v1v1v1moz-txt-link-rfc2396E" href=3D"mailto:mik=
***@***.***" ***@***.***&gt;</a></td>
</tr>
<tr>
<th align=3D"RIGHT" valign=3D"BASELINE" nowrap=3D"nowrap">To:</th>
<td>Great Gardeners <a class=3D"v1v1v1moz-txt-link-rfc2396E" href=3D"mailto=
***@***.***" ***@***.***&gt;<=
/a></td>
</tr>
</tbody>
</table>
<br /><br />
<p>Hi Michael,</p>
<p>I think you may not have received my earlier reply to you with out selec=
tion, so here goes again ...</p>
<p>Plants &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &=
nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; =
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp=
;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbs=
p;&nbsp; Cost each &nbsp;&nbsp;&nbsp; No. required &nbsp;&nbsp;&nbsp; Total=
 Cost (ex VAT)<br />Ajuga reptans Braunhertz 9cm pot &nbsp;&nbsp;&nbsp; &nb=
sp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &p=
ound;1.95 &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; 15 &nbsp;&nbs=
p;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nb=
sp;&nbsp; &pound;29.25<br />Athyrium filix-femina - Lady in red fern 2l pot=
 &nbsp;&nbsp;&nbsp; &pound;5.75 &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &nbs=
p;&nbsp; 4 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&=
nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &pound;23.00<br />Cyclamen coum =
album 9cm pot &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbs=
p;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &pound;3.35 &nbsp;&nbs=
p; &nbsp;&nbsp;&nbsp; &nbsp; &nbsp;&nbsp; 7 &nbsp;&nbsp; &nbsp;&nbsp; &nbsp=
;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &pou=
nd;23.45<br />Cyclamen hederifolium rose 9cm pot &nbsp;&nbsp; &nbsp;&nbsp; =
&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp; &pound;3.35 &nbsp;&nbsp;&nbsp;=
 &nbsp;&nbsp;&nbsp; &nbsp; &nbsp; 7 &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&=
nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &pound;23.45=
<br />Dicentra spectabilis 9cm pot &nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&n=
bsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&=
nbsp; &nbsp;&nbsp;&nbsp; &pound;3.35 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; =
&nbsp;&nbsp; 10 &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &n=
bsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &pound;33.50<br />---------------------=
---------------------------------------------------------------------------=
---------------<br />&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nb=
sp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &n=
bsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &=
nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; =
&nbsp; Totals &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbs=
p;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp;&nbsp; 43 &nbsp;&nbsp;&=
nbsp;&nbsp;&nbsp; &nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;&nbsp;&nbsp; &nbsp;=
 &pound;132.65</p>
<p>Hope you get this this time and look forward to seeing you on the 6th</p>
<p>Regards,</p>
<p>Mike Batten.</p>
<div class=3D"v1v1v1moz-cite-prefix">On 09/02/2024 00:47, Great Gardeners w=
rote:</div>
<blockquote style=3D"padding: 0 0.4em; border-left: #1010ff 2px solid; marg=
in: 0;">
<div dir=3D"ltr">Hi&nbsp;Mike,&nbsp;
<div>&nbsp;</div>
<div>The supplier just emailed&nbsp;me the plants with availability and cos=
ts.&nbsp;</div>
<div>&nbsp;</div>
<div>They have a selection from each plant, so you can choose or we can do =
a bigger&nbsp;mixture. Let me know your opinion.&nbsp;</div>
<div>&nbsp;</div>
<div>All the prices exclude VAT, I would suggest to plant 60 plants there, =
15 from each plant. You can choose if you would like to have more varieties=
&nbsp;of the same plants there or just four different plants.&nbsp;</div>
<div>&nbsp;</div>
<div>Please find a selection below:</div>
<div>Ajuga reptans Braunhertz 9cm&nbsp;pot&nbsp;-&nbsp; &nbsp;&pound;1.95
<div>Ajuga reptans Black Scallop 9cm pot - &pound;1.95&nbsp;&nbsp;</div>
<div>Athyrium filix-femina - Lady fern 2l pot - &pound;6.75&nbsp; &nbsp;</d=
iv>
<div>
<div class=3D"v1v1v1gmail_signature" dir=3D"ltr">
<div dir=3D"ltr">
<div>Athyrium filix-femina - Lady in red fern 2l pot - &pound;5.75</div>
<div>Cyclamen coum album 9cm pot - &pound;3.35</div>
<div>Cyclamen coum rose 9cm pot - &pound;3.35</div>
<div>Cyclamen hederifolium album 9cm pot - &pound;3.35</div>
<div>Cyclamen hederifolium rose 9cm pot - &pound;3.35</div>
<div>Dicentra spectabilis 9cm pot&nbsp; - &pound;3.35</div>
<div>&nbsp;</div>
<div>Once I know your opinion I will amend the quote and email it to&nbsp;y=
ou.&nbsp;</div>
<div>&nbsp;</div>
<div>Have a nice weekend.&nbsp;</div>
<div>&nbsp;</div>
<div>Kind&nbsp;regards,</div>
<div>&nbsp;</div>
<div>Michael</div>
</div>
</div>
</div>
<div>
<div class=3D"v1v1v1gmail_signature" dir=3D"ltr">
<div dir=3D"ltr">
<div>&nbsp;</div>
<div>
<table style=3D"color: #222222; border: none; border-collapse: collapse;"><=
colgroup><col width=3D"133" /><col width=3D"468" /></colgroup>
<tbody>
<tr style=3D"height: 76.5354pt;">
<td style=3D"vertical-align: top; overflow: hidden;"><img style=3D"margin-r=
ight: 0px;" ***@***.***" widt=
h=3D"112" height=3D"112" /></td>
<td style=3D"vertical-align: top; overflow: hidden;">
<p dir=3D"ltr" style=3D"line-height: 1.38; margin-top: 0pt; margin-bottom: =
0pt;"><span style=3D"font-size: 15pt; font-family: Montserrat,sans-serif; c=
olor: #99cc33; background-color: transparent; font-weight: 600; vertical-al=
ign: baseline; white-space: pre-wrap;">Great Garden</span></p>
<p dir=3D"ltr" style=3D"line-height: 1.38; margin-top: 0pt; margin-bottom: =
0pt;"><span style=3D"font-size: 11pt; font-family: Montserrat,sans-serif; c=
olor: #6f9426; background-color: transparent; font-weight: 600; vertical-al=
ign: baseline; white-space: pre-wrap;">Gardening&nbsp; Landscaping&nbsp; De=
sign</span></p>
<p dir=3D"ltr" style=3D"line-height: 1.38; margin-top: 0pt; margin-bottom: =
0pt;"><span style=3D"font-size: 9pt; font-family: Montserrat,sans-serif; co=
lor: #6f9426; background-color: transparent; font-weight: bold; vertical-al=
ign: baseline; white-space: pre-wrap;">E: </span><span style=3D"font-size: =
9pt; font-family: Montserrat,sans-serif; color: #4d584e; background-color: =
transparent; vertical-align: baseline; white-space: pre-wrap;"><a class=3D"=
v1v1v1moz-txt-link-freetext" style=3D"color: #1155cc;" href=3D"mailto:Love@=
greatgarden.co.uk" ***@***.***</a></span></p>
<p dir=3D"ltr" style=3D"line-height: 1.38; margin-top: 0pt; margin-bottom: =
0pt;"><span style=3D"font-size: 9pt; font-family: Montserrat,sans-serif; co=
lor: #6f9426; background-color: transparent; font-weight: bold; vertical-al=
ign: baseline; white-space: pre-wrap;">P: </span><span style=3D"font-size: =
9pt; font-family: Montserrat,sans-serif; color: #4d584e; background-color: =
transparent; vertical-align: baseline; white-space: pre-wrap;">01491 200 66=
8</span></p>
<p dir=3D"ltr" style=3D"line-height: 1.38; margin-top: 0pt; margin-bottom: =
0pt;"><span style=3D"font-size: 12pt; font-family: Montserrat,sans-serif; c=
olor: #dcb000; background-color: transparent; vertical-align: baseline; whi=
te-space: pre-wrap;"><a style=3D"color: #1155cc;" href=3D"http://www.greatg=
arden.co.uk/" target=3D"_blank" rel=3D"noopener noreferrer">www.greatgarden=
=2Eco.uk</a></span></p>
<div>&nbsp;</div>
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
</div>
</div>
<br />
<div class=3D"v1v1v1gmail_quote">
<blockquote class=3D"v1v1v1gmail_quote" style=3D"margin: 0px 0px 0px 0.8ex;=
 border-left: 1px solid #cccccc; padding-left: 1ex;">
<div>
<blockquote style=3D"padding: 0 0.4em; border-left: #1010ff 2px solid; marg=
in: 0;">
<div class=3D"v1v1v1gmail_quote">
<blockquote class=3D"v1v1v1gmail_quote" style=3D"margin: 0px 0px 0px 0.8ex;=
 border-left: 1px solid #cccccc; padding-left: 1ex;">
<div>
<blockquote style=3D"padding: 0 0.4em; border-left: #1010ff 2px solid; marg=
in: 0;">
<div class=3D"v1v1v1gmail_quote">
<blockquote class=3D"v1v1v1gmail_quote" style=3D"margin: 0px 0px 0px 0.8ex;=
 border-left: 1px solid #cccccc; padding-left: 1ex;">
<div class=3D"v1v1v1gmail_quote">
<blockquote class=3D"v1v1v1gmail_quote" style=3D"margin: 0px 0px 0px 0.8ex;=
 border-left: 1px solid #cccccc; padding-left: 1ex;">
<div>
<blockquote style=3D"padding: 0 0.4em; border-left: #1010ff 2px solid; marg=
in: 0;">
<div class=3D"v1v1v1gmail_quote">&nbsp;</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</blockquote>
</div>
</div>
</div>
</div>
</div>
</div>
</div>
</body></html>

--=_0d152236fac7a136062fd21ca6fdd518
Content-Transfer-Encoding: base64
Content-ID: ***@***.***>
Content-Type: image/gif;
 name=blocked.gif
Content-Disposition: inline;
 filename=blocked.gif;
 size=118

R0lGODlhZAAyAIAAAPrOzgAAACH5BAAAAAAALAAAAABkADIAAAJNhI+py+0Po5y02ouz3rz7D4bi
SJbmiabqyrbuC8fyTNf2jef6zvf+DwwKh8Si8YhMKpfMpvMJjUqn1Kr1is1qt9yu9wsOi8fksvls
KwAAOw==
--=_0d152236fac7a136062fd21ca6fdd518--

--=_6aeeb2b62833027ae3cc13804bd6ac09--

**Comment by hugovk** [comment]
Please could you comment via the GitHub website rather than replying? It's not possible to add code formatting to email replies, making it harder to read.

> Note, this email has been sent from the new Kolab-16/AlmaLinux 9 email
server that I am trying to setup and not my normal one which appears to
work and is based on Kolab-16/Debian 10.

Sorry, it's too much work for us to try and set up a Kolab-16/AlmaLinux 9 email server with just the right config to reproduce.

We'll need a _small_ script to run. Please read the link I shared last time for advice.

**Comment by Mikebatty** [comment]
Sorry, the only way I can reproduce the problem is to send and email via my server.  I have exported an example email  (zipped so it uploads) that causes the problem and attached.  While the problem is generated via a 'third-party' (i.e. the Kolab software) I believe the problem lies in your python code library.  At the very least, I don't think it should be failing with a traceback.

[smtpy.zip](https://github.com/python/cpython/files/14436980/smtpy.zip)

**Comment by dtrodrigues** [comment]
This isn't a bug in Python -- msg needs to either be a string containing only ASCII characters, or a bytestring: https://docs.python.org/3/library/smtplib.html#smtplib.SMTP.sendmail

If you encode msg prior to calling sendmail, the msg will not be modified.

See also: https://github.com/python/cpython/issues/69922
