### ISSUE TITLE
An error on the page https://docs.python.org/3/tutorial/introduction.html

### ISSUE THREAD

**Issue by girishkdesh** [python/cpython#116097]
# The error
The erroneous page link:
https://docs.python.org/3/tutorial/introduction.html#text

On this page go to the following part of the text...

String literals can span multiple lines. One way is using triple-quotes: """...""" or '''...'''. End of lines are automatically included in the string, but it’s possible to prevent this by adding a \ **at the end** of the line. The following example:
`print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")`

Here in the instruction before the code, it is asked to add the \ character at **the end of the line** but in the given example the \ character is placed at **the beginning of the line.**

# The Correction
The code given runs correctly. So the instruction must be wrong.
Replace **"at the end of the line"** by **"at the beginning of the line"**

**Comment by TeamSpen210** [comment]
No, the docs are correct. The `\` is placed at the start of the string, but it's the end of the first line of code. There's five lines in total, but in your description you omitted all the line breaks.

**Comment by hugovk** [comment]
And here's a screenshot showing correct placement:

![Screenshot_20240229_090731_Chrome](https://github.com/python/cpython/assets/1324225/48f74c2f-4c23-4f32-bde2-50409cc6311b)

Also from the OP, this example *does* have newlines in the right place, but the single backtick used for formatting on GitHub means it's shown as one line:

`print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")`

If I use three backticks it shows correctly:
```python
print("""\
Usage: thingy [OPTIONS]
     -h                        Display this usage message
     -H hostname               Hostname to connect to
""")
```
