### ISSUE TITLE
``test_interpreters`` fails when running with ``-R 3:3`` argument

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116099]
# Bug report

### Bug description:

```python
./python.exe -m test -R 3:3 test_interpreters
Using random seed: 922541786
0:00:00 load avg: 2.79 Run 1 test sequentially
0:00:00 load avg: 2.79 [1/1] test_interpreters
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XX. .../Include/object.h:1030: _Py_NegativeRefcount: Assertion failed: object has negative ref count
<object at 0x104847bc0 is freed>
Fatal Python error: _PyObject_AssertFailed: _PyObject_AssertFailed
Python runtime state: initialized

Current thread 0x00000001e11dd000 (most recent call first):
  <no Python frame>

Extension modules: _xxsubinterpreters, _xxinterpqueues (total: 2)
zsh: abort      ./python.exe -m test -R 3:3 test_interpreters
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-116164

**Comment by Eclips4** [comment]
Bisected to e80abd57a82ea1beae0a82423d45c6eb8c5c5c7
cc @ericsnowcurrently

**Comment by swtaarrs** [comment]
@colesbury figured out that it's caused by [this code](https://github.com/python/cpython/blob/d01886c5c9e3a62921b304ba7e5145daaa56d3cf/Modules/_xxinterpqueuesmodule.c#L1192-L1205) decrefing `qidobj` too many times.

@ericsnowcurrently, I'm preparing a PR for this but let me know if you were already working on it.

**Comment by ericsnowcurrently** [comment]
@swtaarrs I'll gladly review your PR.  Thanks for taking care of it!

What's your ETA?  Per https://github.com/python/cpython/issues/76785#issuecomment-1970555401, @encukou *may* revert gh-115566 within the next few hours.

**Comment by swtaarrs** [comment]
> What's your ETA?

The PR should be posted within a few minutes.
