### ISSUE TITLE
Omit optional fields from `ast.dump()`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#116023]
# Feature or enhancement

### Proposal:

```python
>>> ast.dump(ast.arguments())
'arguments(posonlyargs=[], args=[], kwonlyargs=[], kw_defaults=[], defaults=[])'
```
After #105858, it would be nice if `ast.dump()` also didn't output optional fields that are set to None or an empty string, so that its output is more concise. This should make it easier to understand the structure of large ASTs where most fields are missing.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-116037

**Comment by JelleZijlstra** [comment]
I noticed that the representation on an empty `ast.Tuple` changed from `Tuple(elts=[], ctx=Load())` to `Tuple(ctx=Load())`, and same for lists and dicts:

```
>>> ast.dump(ast.parse('[]'))
'Module(body=[Expr(value=List(ctx=Load()))])'
>>> ast.dump(ast.parse('{}'))
'Module(body=[Expr(value=Dict())])'
>>> ast.dump(ast.parse('()'))
'Module(body=[Expr(value=Tuple(ctx=Load()))])'
```

I think this is fine; it matches the constructor and it is analogous to how `list()`, `dict()`, and `tuple()` work. However, I thought I'd flag it in case others think these nodes should be special-cased.

**Comment by AlexWaygood** [comment]
> >>> ast.dump(ast.parse('[]'))
> 'Module(body=[Expr(value=List(ctx=Load()))])'
> >>> ast.dump(ast.parse('{}'))
> 'Module(body=[Expr(value=Dict())])'
> >>> ast.dump(ast.parse('()'))
> 'Module(body=[Expr(value=Tuple(ctx=Load()))])'

Why does the repr for `ast.Dict()` not include `ctx=Load()` in it, when `Tuple` and `List` do?

**Comment by AlexWaygood** [comment]
> Why does the repr for `ast.Dict()` not include `ctx=Load()` in it, when the reprs for `Tuple` and `List` do?

I see that the same thing happens on Python 3.12, so this definitely isn't a _regression_... but I'd still be curious if anybody knows why this _is_ different for the different nodes!

**Comment by JelleZijlstra** [comment]
It's because `ast.Dict` can't appear on the left-hand side of an assignment.

```
>>> [x] = (3,)
>>> (x,) = (3,)
>>> {x: x} = {3: 3}
  File "<stdin>", line 1
    {x: x} = {3: 3}
    ^^^^^^
SyntaxError: cannot assign to dict literal here. Maybe you meant '==' instead of '='?
```

I was thinking of whether we'd also want to default the `ctx` parameter of these and other nodes to `Load()`, but that's for another day.
