### ISSUE TITLE
FAQ: Replace PEP 6 link with devguide

### ISSUE THREAD

**Issue by hugovk** [python/cpython#116010]
# Documentation

This FAQ entry:

https://docs.python.org/3/faq/general.html#how-does-the-python-version-numbering-scheme-work

Says:

> See PEP 6 for more information about bugfix releases. 

But PEP 6 says:

> This PEP is obsolete. The current release policy is documented in the devguide. See also PEP 101 for mechanics of the release process. 

Let's update the link to point to the devguide instead.

PEP 387 (Backwards Compatibility Policy) would be worth linking as well. 

Are there any other PEP 6 references in the docs to update? 

### Linked PRs
* gh-116246
* gh-116286
* gh-116287

**Comment by Tabrizian** [comment]
@hugovk Created a PR here: https://github.com/python/cpython/pull/116246
