### ISSUE TITLE
Enum creation from values fails for certain values.

### ISSUE THREAD

**Issue by maflAT** [python/cpython#116040]
# Bug report

### Bug description:

Hello,
I tried to define an enum with custom initializer and tuple values, akin to the [Planet example](https://docs.python.org/3/howto/enum.html#planet).
When instantiating this enum from values it works for some values (0, 1) but fails for others (1, 0).

```python
from enum import Enum

class Cardinal(Enum):
    RIGHT = (1, 0)
    UP = (0, 1)
    LEFT = (-1, 0)
    DOWN = (0, -1)

    def __init__(self, x: int, y: int, /) -> None:
        self.x = x
        self.y = y

up = Cardinal(0, 1)  # works
right = Cardinal(1, 0)  # ValueError: 1 is not a valid Cardinal
right_ = Cardinal((1, 0))  # works
```
I'm not quite sure if I'm allowed to construct this enum from separate x and y parameters or if I need to pass a tuple.
Either way, it should either work for both (up and right) cases or fail for both cases.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-116072
* gh-116476
* gh-116508
* gh-116619

**Comment by hugovk** [comment]
Reproducible with the latest 3.13 alpha (3.13.0a4).

(3.11.8 gives `TypeError: <enum 0> cannot extend <enum 'Cardinal'>` for `up = Cardinal(0, 1)  # works`)

**Comment by ethanfurman** [comment]
In 3.11 you still have to use tuples; i.e. `Cardinal((0, 1))` -- not having to use a tuple is a 3.12 enhancement.
