### ISSUE TITLE
A bug while using Sets

### ISSUE THREAD

**Issue by FarhadSparrow** [python/cpython#116002]
# Bug report

### Bug description:

set1 = {False}
print(8 < 6 in set1)
The output is False but it must be True

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by TeamSpen210** [comment]
You need parentheses around `(8 < 6)`. Due to [comparison chaining](https://docs.python.org/3/reference/expressions.html#comparisons), this code is actually computing `(8 < 6) and (6 in set1)`, which is not what you want.

**Comment by FarhadSparrow** [comment]
> You need parentheses around `(8 < 6)`. Due to [comparison chaining](https://docs.python.org/3/reference/expressions.html#comparisons), this code is actually computing `(8 < 6) and (6 in set1)`, which is not what you want.

So then why this one is False too?
set1 = {False, 6}
print(8<6 in set1)
