### ISSUE TITLE
Add a fillvalue option to itertools.batched()

### ISSUE THREAD

**Issue by valorien** [python/cpython#116001]
# Feature or enhancement

### Proposal:

In a similar fashion to `itertools.zip_longest()`, adding a `fillvalue` option to `itertools.batched()` can be quite useful when generating batches that have specific alignment requirements.

Here's an example:
```python
## This program writes 16-bit aligned values to a file/buffer/etc ##

from itertools import batched

data: str = '8B40FABE5197C51AEE7F9344258739A3D'   # length = 33 characters

for batch in batched(data, 4): 
    """
    ('8', 'B', '4', '0')
    ('F', 'A', 'B', 'E')
    ('5', '1', '9', '7')
    ('C', '5', '1', 'A')
    ('E', 'E', '7', 'F')
    ('9', '3', '4', '4')
    ('2', '5', '8', '7')
    ('3', '9', 'A', '3')
    ('D',)  <- Not aligned, requires padding in writing function
    """
    some_write_function(batch)
```

Assuming `fillvalue` is available:
```python
for batch in batched(data 4, fillvalue='F'): 
    """
    ('8', 'B', '4', '0')
    ('F', 'A', 'B', 'E')
    ('5', '1', '9', '7')
    ('C', '5', '1', 'A')
    ('E', 'E', '7', 'F')
    ('9', '3', '4', '4')
    ('2', '5', '8', '7')
    ('3', '9', 'A', '3')
    ('D', 'F', 'F', 'F')   <- Aligned, no padding required in other functions
    """
    some_write_function(batch)
```

I've linked to a Discourse post where @rhettinger and other members have mentioned this option. I'd be happy to see this added if possible.

In any case, `itertools.batched()` is a wonderful addition. Thank you to everyone who contributed to it.

### Links to previous discussion of this feature:

https://discuss.python.org/t/add-batching-function-to-itertools-module/19357/38

**Comment by rhettinger** [comment]
Thank you for the suggestion but I had decided to not go down this path. The need seems to be uncommon and is easily met other `zip_longest()` as shown in the `grouper()` recipe.  Even the `more-itertools` package with its many variations has not gone down this path. Mostly, if a person wants a special case for an incomplete batch, they can easily add `if len(batch) < n: ...` and put in whatever special handling they want.

**Comment by valorien** [comment]
Appreciate the answer. Thank you @rhettinger.

**Comment by rhettinger** [comment]
I forgot the mention that there would be API issues as well.  With `zip_longest()` the fillvalue can meaningfully default to `None` since that tool always fills.  But for `batched()`, we would also need an on/off switch, defaulting to off.  Another less serious issue is that a `fillvalue` fights with the `strict` switch because it doesn't make sense to have them both.

**Comment by valorien** [comment]
That is a **very good** point which I seem to have completely missed. 
You're absolutely right, using `batched(fillvalue=None)` will just fill the "missing" fields with `None`, which means it can't be used as an "off switch". I guess there's no value that can, since anything placed after the `=` sign will be used as filling.

Perhaps a better solution (if somehow this comes up again) would be to create a separate `batched_fill(fillvalue=None)` function to address this issue. Unlikely, but a nice thought experiment.

Thanks again for the explanations and for your time, Raymond.
Much appreciated and have a great day.

**Comment by valorien** [comment]
I know the issue is closed, just wanted to point out for posterity that theoretically, `batched(fillvalue=MISSING)` can be used as an "off switch". A separate function won't be needed after all.
