### ISSUE TITLE
Issue with the precedence of the operator |

### ISSUE THREAD

**Issue by Mrwuliang** [python/cpython#116094]
# Bug report

### Bug description:

The | operator should have lower precedence than comparison operators such as >. However, in the program, when both | and > comparison operators are used simultaneously, they are evaluated from left to right, unlike when using 'or', which does not exhibit this behavior.
`print(True | 0 > 1)`
return False
`print(True or 0 > 1)`
return True

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by pochmann3** [comment]
> The | operator should have lower precedence than comparison operators such as >

Says who?

The [doc](https://docs.python.org/3/reference/expressions.html#operator-precedence) says the opposite

**Comment by Mrwuliang** [comment]
> True | 0 > 1



> > The | operator should have lower precedence than comparison operators such as >
> 
> Says who?
> 
> The [doc](https://docs.python.org/3/reference/expressions.html#operator-precedence) says the opposite.
> 
> It's not a bug if you'd just like Python to be different than how it is.

I observed that in both Java and C++, evaluating (True | 0 > 1) returns True.

**Comment by ericvsmith** [comment]
Python is conforming to its documented behavior, so I'm going to close this.
