### ISSUE TITLE
3.9 doc dark theme: code foreground fg color is background bg color

### ISSUE THREAD

**Issue by itsme300** [python/cpython#116113]
# Documentation
https://docs.python.org/3.9/library/multiprocessing.html#module-multiprocessing

eg: from multiprocessing import Pool

here 'Pool' is displayed in white and background color is also white which makes it look like below

from multiprocessing import

**Comment by itsme300** [comment]
sorry to have raised a duplicate bug. Thanks for the quick feedback.

**Comment by terryjreedy** [comment]
Made title possibly more discoverable.
