### ISSUE TITLE
Multidimensional List concatenation over individual indices not working

### ISSUE THREAD

**Issue by Morgroth** [python/cpython#116193]
# Bug report

### Bug description:

Append and Extend Functions for multidimensional lists are not working as expected. When used below (in the code for reproduction) for appending 1 to the 0th index of the list, it appends the value to all the indices instead of just 1. The same goes when used for appending a list. Extend also shows similar behaviour. This code was run on macOS with python 3.11.4

Code for Reproduction
```python
L = [[]] * 3

L[0].append(1)

print(L) # Expected - [[1],[],[]] ; Printed result - [[1], [1], [1]]

L = [[]] * 3

L[0].extend([1,2,3])

print(L) # Expected - [[1,2,3],[],[]] ; Printed result - [[1,2,3], [1,2,3], [1,2,3]]
```
Alternatives for performing the same operations do exist - 

```python
L = [[]] * 3

L[0] = [*L[0], *[1]]

print(L) # Expected and printed result - [[1], [], []]

L = [[]] * 3

L[0] = L[0] + [1]

print(L) # Expected and printed result - [[1], [], []]
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Hello!
There's no bug; it's a expected behaviour, for more information read the [doc](https://docs.python.org/3.12/faq/programming.html#how-do-i-create-a-multidimensional-list).
