### ISSUE TITLE
New warning: ``‘fmt’ may be used uninitialized in this function [-Wmaybe-uninitialized]``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116102]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/116101/files and https://github.com/python/cpython/pull/116096/files

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-116230

**Comment by sobolevn** [comment]
I think that there are multiple issues here:

```
» ./python.exe
Python 3.13.0a4+ (heads/main:186fa938766, Feb 29 2024, 13:50:11) [Clang 15.0.0 (clang-1500.0.40.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> _xxinterpqueues.get(1, 'a')
KeyboardInterrupt
>>> import _xxinterpqueues
>>> a = _xxinterpqueues.create(2, 0)
>>> _xxinterpqueues.get(1, 'a')
('a', 3)
>>> 
KeyboardInterrupt
>>> ^D
Assertion failed: (queues->count == 0), function _queues_fini, file _xxinterpqueuesmodule.c, line 689.
[1]    57640 abort      ./python.exe
```

1. Why `('a', 3)` is returned? `3` is not the default `fmt` for this queue
2. Why does it crash? `Assertion failed: (queues->count == 0), function _queues_fini, file _xxinterpqueuesmodule.c, line 689.`

CC @ericsnowcurrently

**Comment by ericsnowcurrently** [comment]
> 1. Why `('a', 3)` is returned? `3` is not the default `fmt` for this queue

It should have raised `QueueEmpty`.  When run your code locally I get `QueueEmpty`.

> 2. Why does it crash? `Assertion failed: (queues->count == 0), function _queues_fini, file _xxinterpqueuesmodule.c, line 689.`

I'm going to look into this.

**Comment by ericsnowcurrently** [comment]
I've fixed the warning.

As to "Why does it crash?", it's because the low-level module requires you to call `_xxinterpqueues.destroy()`.  Note that I didn't really intend for people to use the low-level module directly.  If this is a problem, we can address it separately from this issue.

**Comment by sobolevn** [comment]
@ericsnowcurrently I will open a new one, because I don't have the same result as you with `QueueEmpty` :(

**Comment by sobolevn** [comment]
Done: https://github.com/python/cpython/issues/116239

**Comment by ericsnowcurrently** [comment]
> Can we call .destroy() on module shut-down? It might fix this problem.

I'm taking care of this in gh-116328.
