### ISSUE TITLE
argparse is slow when parsing large number of optional flags

### ISSUE THREAD

**Issue by amyreese** [python/cpython#116159]
# Bug report

### Bug description:

When parsing positional vs optional arguments, the use of min with a
list comprehension inside of a loop [1][] results in quadratic time based
on the number of optional arguments given. When combined with use of
prefix based argument files and a large number of optional flags, this
can result in extremely slow parsing behavior.

Example test case: https://gist.github.com/amyreese/b825bc092210ea7b64287f033dc995d8

The test case parses a list of arguments that contains 30,000 copies
of `--flag=something`. This takes roughly 15-16 seconds to parse:

```console
$ ~/opt/cpython/bin/python3.13 -VV
Python 3.13.0a4+ (heads/main:0656509033, Feb 29 2024, 11:59:43) [Clang 15.0.0 (clang-1500.1.0.2.5)]

$ ~/opt/cpython/bin/python3.13 test_many_flags.py
parsed args in 15,195,914 µs
```

[1]: https://github.com/python/cpython/blob/fa1d675309c6a08b0833cf25cffe476c6166aba3/Lib/argparse.py#L2156

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-116162

**Comment by hugovk** [comment]
> Example test case: [gist.github.com/amyreese/b825bc092210ea7b64287f033dc995d8](https://gist.github.com/amyreese/b825bc092210ea7b64287f033dc995d8)

Including here for future reference:

```python
import argparse
import time

def main():
    parser = argparse.ArgumentParser(fromfile_prefix_chars="@")
    parser.add_argument("--flag", nargs="+")

    before = time.monotonic_ns()
    args = parser.parse_args(["--flag=something"] * 30_000)
    after = time.monotonic_ns()

    print(f"parsed args in {(after - before) // 1000:,} µs")

if __name__ == "__main__":
    main()
```

**Comment by erlend-aasland** [comment]
Thanks for the report and PR!
