### ISSUE TITLE
Leap Year Calculation for Replace Function Causes day is out of range for month

### ISSUE THREAD

**Issue by TRBaldim** [python/cpython#116175]
# Bug report

### Bug description:

```python
from datetime import datetime
exec_date = '2024-02-29'
current_date = datetime.strptime(exec_date, "%Y-%m-%d")
end_date = current_date.replace(year=current_date.year - 2, month=current_date.month, day=current_date.day)
```

We are trying to get the date of two years from now in Python datetime.

We are expecting to get a valid date 2 years from now. And that is giving the following error:

```
ValueError: day is out of range for month
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

### Linked PRs
* gh-116176

**Comment by a1448125** [comment]
In the strptime function, when the year is not specified but the date is February 29th, the default year is set to 1900. However, 1900 is not a leap year, which causes an error. Changing the default year to 1904 or removing the leap_year_fix check can resolve this issue. I'm not sure why the leap_year_fix check was added in the first place.😀

**Comment by a1448125** [comment]
Okay, I seem to have misunderstood the problem. In response to your question, two years later, February 29th does not exist, so this error is normal. I modified the code in hopes of fixing the error that occurs when the year is not entered.😀

**Comment by ericvsmith** [comment]
The standard library cannot solve this problem for you. You might mean 365*2 days from now, you might mean int(365.25)*2 days from now, you might mean something else. (And I realize 365.25 isn't correct for a large number of years, say 1000 years from now). The standard library does not contain this functionality, and it won't be added.

You'll need to either write the logic yourself, or use another library that provides this functionality, I think python-dateutil might.
