### ISSUE TITLE
Command to build `_testexternalinspection.o` gets truncated when building under WASI

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#116229]
### Bug description:

The output from `make` is:

```
z stack-size=524288 -Wl,--stack-first -Wl,--initial-memory=10485760   Modules/_testexternalinspection.o   -o Modules/_testexternalinspection.cpython-313d-wasm32-wasi.so
/bin/sh: 1: z: not found
```

It seems like the command is partially from `CONFIGURE_LDFLAGS_NODIST= -z stack-size=524288 -Wl,--stack-first -Wl,--initial-memory=10485760`.

And the `Makefile` line is:
```
Modules/_testexternalinspection$(EXT_SUFFIX):  Modules/_testexternalinspection.o; $(BLDSHARED)  Modules/_testexternalinspection.o $(MODULE__TESTEXTERNALINSPECTION_LDFLAGS) $(MODULE_LDFLAGS) -o Modules/_testexternalinspection$(EXT_SUFFIX)
```

But `BLDSHARED` is `BLDSHARED=	 $(PY_CORE_LDFLAGS)` in `Makefile`. That suggests there's some expansion failing.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

**Comment by erlend-aasland** [comment]
cc. @mhsmith

**Comment by mhsmith** [comment]
I'm not sure what's going on here, but I don't think it's caused by any of the things I've changed recently.

**Comment by erlend-aasland** [comment]
@brettcannon, how can I reproduce? I tried following the instructions in `Tools/wasm/README.md` but got no build failure.

**Comment by brettcannon** [comment]
> @brettcannon, how can I reproduce? I tried following the instructions in `Tools/wasm/README.md` but got no build failure.

@erlend-aasland the overall build will succeed, but `_testexternalinspection` won't be kept due to not being imported. I only noticed this because I had another build failure related to that module that I have fixed.

**Comment by mhsmith** [comment]
If I understand correctly, WASI doesn't actually support building shared library modules at all, so it doesn't set `BLDSHARED`. But `_testexternalinspection` was added to a small list of test modules at the bottom of Setup.stdlib.in which "MUST be build as shared libraries". And it just so happens that all the previous libraries on that list were skipped on WASI because it doesn't support `dlopen`.

**Comment by brettcannon** [comment]
@mhsmith Correct, but all the other modules fail due to not being importable (I have https://github.com/python/cpython/issues/115983 to track turning off building them in the first place). For some reason with `_testkexternalinspection` I see this odd situation where the command run gets truncated down to `z` and causes the compilation to fail.

**Comment by brettcannon** [comment]
The list of modules that @mhsmith referred to:

https://github.com/python/cpython/blob/c951e25c24910064a4c8b7959e2f0f7c0d4d0a63/Modules/Setup.stdlib.in#L170-L180

If we don't want to bother trying to figure out why the truncation is occurring I can just turn off trying to build this module under WASI (and all the other ones listed there).

**Comment by sobolevn** [comment]
I just tried the whole thing on my mac, I got expected result: `BLDSHARED=	$(CC) -bundle -undefined dynamic_lookup $(PY_CORE_LDFLAGS)`

No warning happened when running `make`.

**Comment by mhsmith** [comment]
@sobolevn: From that command line, it looks like you were building for macOS, not WASI.

**Comment by brettcannon** [comment]
I turned off building `_testexternalinspection` under WASI in https://github.com/python/cpython/pull/116528 . I'm going to close this as indirectly fixed, but if someone wanted to continue to dig into why the command is getting truncated I can open it again.
