### ISSUE TITLE
After opening a tkinter window, command line interpreter crashes after getting a command from the clipboard ending with a comment

### ISSUE THREAD

**Issue by rudyment** [python/cpython#116264]
# Bug report

### Bug description:

I use Python in Windows 1O.
If I enter the command 
w = tkinter.Tk() 
in the command line interpreter, the interpreter starts behaving strangely.
Commands entered directly from the keyboard 
and commands pasted from the clipboard and not ending with a comment, 
it continues to process as expected.
However, whenever I paste from the clipboard a command that ends with a line comment,
the interpreter crashes, and with it the entire command line window.
However, the window opened in tkinter remains open
and closes only when its close button is pressed.

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
I cannot repeat either with freshly updated and compiled main or with installed 3.12.2
```
f:\dev\3x>python
Running Debug|x64 interpreter...
Python 3.13.0a4+ (heads/main:0656509033, Mar  3 2024, 11:43:20) [MSC v.1932 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> w = tkinter.Tk()
>>> a = 3 # commetn
>>> a = 3 # commetn <pasted> behaves normally
>>> quit() # Tk window closes
```
When I repeated the above with 3.12.2  to the 'w' line and then pasted in the above, I got several SyntaxErrors, and  the tkinter disappeared, but no crash.  Interpreter continued normally. I repeated again from beginning pasting legal code and all was well.  Please copy and paste exactly what you did, though I suspect there is an idiosyncratic problem with your system.

**Comment by rudyment** [comment]
I apologize for the long pause, but in the confusion of the beginning of
the semester, 
your email got lost somewhere and I just found it now while cleaning out
my mail. 

After reading your reply, I tried the program on several other
computers, 
and indeed, and indeed, the problem I reported, for reasons unknown to
me, 
was only occurring on one. 

If I had noticed it earlier, I would not have reported anything. 

I'm sorry to have bothered 

Have a nice day 

Rudolf Pecinovsky

Dne 2024-03-03 18:00, Terry Jan Reedy napsal:

> I cannot repeat either with freshly updated and compiled main or with installed 3.12.2
> 
> f:\dev\3x>python
> Running Debug|x64 interpreter...
> Python 3.13.0a4+ (heads/main:0656509033, Mar  3 2024, 11:43:20) [MSC v.1932 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
>>>> import tkinter
>>>> w = tkinter.Tk()
>>>> a = 3 # commetn
>>>> a = 3 # commetn <pasted> behaves normally
>>>> quit() # Tk window closes
> 
> When I repeated the above with 3.12.2 to the 'w' line and then pasted in the above, I got several SyntaxErrors, and the tkinter disappeared, but no crash. Interpreter continued normally. I repeated again from beginning pasting legal code and all was well. Please copy and paste exactly what you did, though I suspect there is an idiosyncratic problem with your system. 
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> You are receiving this because you authored the thread.Message ID: ***@***.***>
 

Links:
------
[1]
https://github.com/python/cpython/issues/116264#issuecomment-1975230244
[2]

**Comment by terryjreedy** [comment]
Thank you for responding so we can close this.
