### ISSUE TITLE
The README of c-analyzer needs update

### ISSUE THREAD

**Issue by aisk** [python/cpython#116265]
# Documentation

https://github.com/python/cpython/blob/87faec28c78f6fa8eaaebbd1ababf687c7508e71/Tools/c-analyzer/README#L14

It is mentioned in the README about an `ignored-globals.txt` file, which was removed in #22841.

### Linked PRs
* gh-116284
* gh-116331
* gh-116332

**Comment by terryjreedy** [comment]
@ericsnowcurrently The mentioned PR was yours.  Doc looks correct with sentence simply removed.  PR submitted.

**Comment by ericsnowcurrently** [comment]
Thanks for pointing this out.
