### ISSUE TITLE
Misleading SyntaxError location on import typo

### ISSUE THREAD

**Issue by rzehumat** [python/cpython#116292]
# Bug report

### Bug description:

MRE: 
```
Python 3.13.0a4+ (heads/main:3383d6afa3, Mar  3 2024, 22:17:54) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> ipmort pandas
  File "<stdin>", line 1
    ipmort pandas
           ^^^^^^
SyntaxError: invalid syntax
```
The example above has a typo -- it should be `import`, but the error message does not say so. The fine-graded error location seems incorrect -- I would expect it to point at `ipmort`. Also, I am unsure whether it should be a `SyntaxError` or a `NameError`. (`pandas` is irrelevant here, it could be any package or module)

To compare, if there is just `ipmort`, the error message seems correct.
```
>>> ipmort
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    ipmort
NameError: name 'ipmort' is not defined
```

### CPython versions tested on:

3.10, 3.11, 3.12, CPython main branch

### Operating systems tested on:

Linux

**Comment by rzehumat** [comment]
I got few ideas to discuss, so I'd rather move it to [Discourse](https://discuss.python.org/t/error-messages-on-import/47511). So this issue probably could be closed until there are some outcomes.

**Comment by terryjreedy** [comment]
Like nearly all exceptions other than SyntaxError, NameError is a runtime error.  The parser/compiler only look at bad form so this is not a bug.  `ipmort +3` compiles and raises NameError when executed.

**Comment by rzehumat** [comment]
Thanks for explaining this, @terryjreedy
