### ISSUE TITLE
Python3.12 BUG: ModuleNotFoundError: No module named '_bz2'

### ISSUE THREAD

**Issue by Zhang-Junzhi** [python/cpython#116224]
### Bug description:

```python
import bz2
```
would result in an error:

> ModuleNotFoundError: No module named '_bz2'

The python was compiled with the following commands:
```
CFLAGS='-O3 -DNDEBUG' ./configure --enable-optimizations
make
make install
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by Zhang-Junzhi** [comment]
I recompile python 3.12, and look through the reports along with the compilation, and I found the following reports:

> The necessary bits to build these optional modules were not found:
> _bz2                  _dbm                  _gdbm              
> _lzma                 _tkinter              readline           
> To find the necessary bits, look in configure.ac and config.log.

I have no idea what to do to help python find these "necessary bits".

**Comment by Zhang-Junzhi** [comment]
I resolved this issue by installing libbz2-dev:
`sudo apt install libbz2-dev`
By the way, I was using Deepin Distro.

**Comment by gaogaotiantian** [comment]
You can refer to devguide for installing dependencies - https://devguide.python.org/getting-started/setup-building/#install-dependencies
