### ISSUE TITLE
re.search() returns an incorrect value for overlapping matches.

### ISSUE THREAD

**Issue by Swight1423** [python/cpython#116247]
# Bug report

### Bug description:

```python
import re
    repattern = re.compile("test")
    result = repattern.search("mytestest")
    print(result)
```
this results in <re.Match object; span=(2, 6), match='test'>
the expected value would be 2,5 if overlapping is allowed and 2 if it isn't.
this type of issue could lead to some significant stealthy bugs since one would expect the function to return accurate values. for example if my code was expecting a the string to be at least the length of the pattern from the last match this could cause a crash with a index out of range. if the code was complicated enough I might incorrectly think there was an off by one error elsewhere in my code(because functions like this tend to be assumed to be correct) leading to more bugs. and you may not know ahead of time if a text includes overlapping matches.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by pochmann3** [comment]
No bug, span correctly tells where the single match starts and ends, not where multiple matches start.

**Comment by tim-one** [comment]
With a bit more detail, `search()` only looks for the leftmost match (if any). If found, `.span` gives the _slice indices_ of that match, and

```python
>>> "mytesttest"[2 : 6]
'test'
```

correctly identifies the slice spanned by the leftmost match.

**Comment by Swight1423** [comment]
in that case wouldn't the correct span be 2,5 for the first match?

**Comment by tim-one** [comment]
No. Slice indexing is already well documented - just read it :wink:.

**Comment by Swight1423** [comment]
didn't realize ending index of spans were exclusive.

**Comment by tim-one** [comment]
It's more fruitful to view indices as being "between" sequence elements. For a sequence of length `n`, there are `n+1` interesting locations: before the leftmost element (slice index 0) through after the rightmost element (slice index `n`). So, e.g., the slice `lo:hi` spans `hi - lo` elements (assuming `lo <= hi`). Once you're used to it, it will spare you from a world of "off by 1" errors.

**Comment by terryjreedy** [comment]
@Swight1423 Please ask questions about possible bugs on our [Discourse help channel](https://discuss.python.org/c/users/7) or similar forums.  Answers given there are more visible to others.
