### ISSUE TITLE
SIGTSTP/SIGCONT handlers: print() statements in SIGCONT handler don’t work as expected

### ISSUE THREAD

**Issue by codeandfire** [python/cpython#116260]
# Bug report

### Bug description:

Minimal reproducible example:
```python
import signal

def sigtstp_handler(signum, frame):
    print(‘\nSuspended.’, end=‘’)
    signal.signal(signal.SIGTSTP, signal.SIG_DFL)
    signal.raise_signal(signal.SIGTSTP)
signal.signal(signal.SIGTSTP, sigtstp_handler)

def sigcont_handler(signum, frame):
    print(‘Resumed.’)
    print(‘Prompt: ‘, end=‘’)
signal.signal(signal.SIGCONT, sigcont_handler)

input(‘Prompt: ‘)
```

When this is run, and CTRL-Z is pressed at the `Prompt: ` -
```
$ python script.py
Prompt: ^Z
Suspended.
[1]+   Stopped               python script.py
```
i.e. suspension works out okay, but when we try to resume:
```
$ fg
python script.py
Resumed.

```
i.e. `Prompt: ` is not shown. Instead, we just get a blinking cursor, and if we enter some input at the cursor such as `xyz`:
```
$ fg
python script.py
Resumed.
xyz
Prompt: $
```
i.e. the `Prompt: ` appears after the input is received. (The second `$` is the shell prompt reappearing after the program finishes execution.)

I’ve tried the equivalent C code:
```c
#include <stdio.h>
#include <signal.h>

void sigtstp_handler(int signum)
{
    printf(“\nSuspended.”);
    signal(SIGTSTP, SIG_DFL);
    raise(SIGTSTP);
}

void sigcont_handler(int signum)
{
    printf(“Resumed.\n”);
    printf(“Prompt: “);
}

int main()
{
    char s[20];

    signal(SIGTSTP, sigtstp_handler);
    signal(SIGCONT, sigcont_handler);

    printf(“Prompt: “);
    scanf(“%s”, s);
    return 0;
}
```

Running this:
```
$ ./a.out
Prompt: ^Z

[1]+   Stopped                ./a.out
```
i.e. the `Suspended.` message is not displayed. Resuming:
```
$ fg
./a.out
Suspended.Resumed.
xyz
Prompt: $
```
i.e. the `Suspended.` message is displayed now, and the `Prompt: ` is again not displayed correctly.

This appears to be related to stdout line-buffering, so I try to disable that:
```c
int main()
{
    …
    signal(SIGTSTP, sigtstp_handler);
    signal(SIGCONT, sigcont_handler);
    setbuf(stdout, NULL);
    …
}
```
And indeed when I run it now:
```
$ ./a.out
Prompt: ^Z
Suspended.
[1]+   Stopped                ./a.out
$ fg
./a.out
Resumed.
Prompt: xyz
```
both suspension and resuming work out okay.

When I run Python in unbuffered mode, i.e.
```
$ python -u script.py
```
again, both suspension and resuming work out okay.

Additionally, if I add a newline before the `Prompt: ` in the SIGCONT handler:
```python
def sigcont_handler(signum, frame):
    print(‘Resumed.’)
    print(‘\nPrompt: ‘, end=’’)
```
then, without the `-u` option, the `Prompt: ` is displayed correctly upon resuming, albeit with a blank line between `Resumed.` and the `Prompt: ` (which is expected because of the added newline character).
```
$ python script.py
Prompt: ^Z
Suspended.
[1]+   Stopped                python script.py
$ fg
python script.py
Resumed.

Prompt: xyz
```

P.S.: I also created a [thread](https://discuss.python.org/t/setting-up-handlers-for-signals-sigtstp-and-sigcont/46911) on Discourse but got no response.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
This is not a problem with signal handling, but your code doesn't consider buffering. You should explicitly flush the stdout buffer when you want the output to appear before you write newline, e.g.:

```python
import signal
import sys

def sigtstp_handler(signum, frame):
    print("\nSuspended.", end="")
    signal.signal(signal.SIGTSTP, signal.SIG_DFL)
    signal.raise_signal(signal.SIGTSTP)
signal.signal(signal.SIGTSTP, sigtstp_handler)

def sigcont_handler(signum, frame):
    print("Resumed.")
    print("Prompt: ", end=""); sys.stdout.flush()
signal.signal(signal.SIGCONT, sigcont_handler)

input("Prompt: ")
```

**Comment by codeandfire** [comment]
That works, thank you @ronaldoussoren!
