### ISSUE TITLE
Provide async StreamWriter coroutine so memory does not go unbounded when write is blocked.

### ISSUE THREAD

**Issue by eliphatfs** [python/cpython#116279]
# Feature or enhancement

### Proposal:

For example, this snippet will cause memory consumption to fill up over time.
`Writer.write` does not block, and the data will be kept in buffer until TCP flow control accepts more.

However, it is common to have large file uploads and unpredictable client input in TCP clients.
Though users can implement the client using callbacks from flow control (see #81162), it is much easier to use and also better fits the design of asyncio to provide easy async write access to sockets.

```python
import asyncio
import psutil


async def simulate_slow_network(reader: asyncio.StreamReader, writer: asyncio.StreamWriter):
    while True:
        b = await reader.read(8192)
        if not len(b):
            break
        await asyncio.sleep(0.5)  # note that memory will not bulk up if removing the line


async def main():
    serv = await asyncio.start_server(simulate_slow_network, host='127.0.0.1', port=8192)
    reader, writer = await asyncio.open_connection(host="127.0.0.1", port=8192)
    writer: asyncio.StreamWriter
    for i in range(1024 ** 2):
        writer.write(b'0' * 8192)
        await asyncio.sleep(0)
        if i % 1024 == 0:
            print(psutil.Process().memory_info().rss / 1024 ** 2)
    serv.close()


if __name__ == '__main__':
    asyncio.run(main())
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by eliphatfs** [comment]
The feature was also requested in #68637. I am aware of the API design arguments, but I do not see how the memory requirement argument is refuted properly.

**Comment by gvanrossum** [comment]
@eliphatfs I don't see an API proposal yet -- only a problem statement. Please propose a specific API. It would be even better if you also (!) provided a draft PR with a tentative implementation.

**Comment by eliphatfs** [comment]
Okay, I will try to do one in one or two days.

**Comment by kumaraditya303** [comment]
If you don't want unbounded memory usage, you should drain the writer using `await writer.drain()`. 

See https://docs.python.org/3/library/asyncio-stream.html#asyncio.StreamWriter.write

**Comment by eliphatfs** [comment]
it is hard to decide when to await drain. it also costs performance to drop if the data flow is interrupted during the drain.
