### ISSUE TITLE
Disable the GIL by default in free-threaded builds

### ISSUE THREAD

**Issue by swtaarrs** [python/cpython#116329]
# Feature or enhancement

### Proposal:

Once #116167 is complete, users will be able to disable the GIL with `PYTHON_GIL=0`, but the GIL will remain enabled by default.

When we have enough confidence in the correctness of running without the GIL, we should change free-threaded builds to disable the GIL by default, as [described in PEP 703](https://peps.python.org/pep-0703/#pythongil-environment-variable).

This should be a very small code change, and is already detailed in [this comment](https://github.com/python/cpython/blob/258408239a4fe8a14919d81b73a16e2cfa374050/Python/ceval_gil.c#L454-L456).

**Comment by corona10** [comment]
From my view, at least we should pass all unit tests with `PYTHON_GIL=0`

**Comment by colesbury** [comment]
Done in https://github.com/python/cpython/pull/118295

**Comment by colesbury** [comment]
Combining with:

* gh-116749
