### ISSUE TITLE
Allow C extensions to declare compatibility with free-threading

### ISSUE THREAD

**Issue by swtaarrs** [python/cpython#116322]
# Feature or enhancement

There are a few pieces to this:
1. Add a `Py_mod_gil` slot, as [described in PEP 703](https://peps.python.org/pep-0703/#py-mod-gil-slot), that multi-phase init modules can use to indicate that they support free-threading.
2. Add a `PyModule_ExperimentalSetGIL()` function (discussed [here](https://github.com/python/cpython/pull/116882#discussion_r1575006053)) that single-phase init modules can use in place of `Py_mod_gil`.
3. Mark all built-in modules as free-threading compatible with one of the above mechanisms.
4. Enable the GIL while loading a C module and leave it permanently enabled if the module does not declare free-threading compatibility.

1-3 are addressed in gh-116882; 4 will be addressed in a separate PR.

### Linked PRs
* gh-116882
* gh-118560
* gh-118645
* gh-122268
* gh-122282
* gh-122284

**Comment by swtaarrs** [comment]
What [warning category](https://docs.python.org/3.12/library/warnings.html#warning-categories) should this issue? `ImportWarning` sounds like a good fit at first, but it's ignored by the default warning filters, which we don't want. Of the categories not ignored by default, `RuntimeWarning` seems like the best fit to me.

**Comment by colesbury** [comment]
@swtaarrs is this finished now?

**Comment by swtaarrs** [comment]
Yep!

**Comment by danielivascsenko2-ux** [comment]
> # Feature or enhancement
> There are a few pieces to this:
> 
> 1. Add a `Py_mod_gil` slot, as [described in PEP 703](https://peps.python.org/pep-0703/#py-mod-gil-slot), that multi-phase init modules can use to indicate that they support free-threading.
> 2. Add a `PyModule_ExperimentalSetGIL()` function (discussed [here](https://github.com/python/cpython/pull/116882#discussion_r1575006053)) that single-phase init modules can use in place of `Py_mod_gil`.
> 3. Mark all built-in modules as free-threading compatible with one of the above mechanisms.
> 4. Enable the GIL while loading a C module and leave it permanently enabled if the module does not declare free-threading compatibility.
> 
> 1-3 are addressed in [gh-116882](https://github.com/python/cpython/pull/116882); 4 will be addressed in a separate PR.
> 
> ### Linked PRs
> * [gh-116322: Add Py_mod_gil module slot #116882](https://github.com/python/cpython/pull/116882)
> * [gh-116322: Enable the GIL while loading C extension modules #118560](https://github.com/python/cpython/pull/118560)
> * [gh-116322: Rename PyModule_ExperimentalSetGIL to PyUnstable_Module_SetGIL #118645](https://github.com/python/cpython/pull/118645)
> * [gh-116322: Fix typo in the #ifdef check #122268](https://github.com/python/cpython/pull/122268)
> * [gh-116322: Fix typo in moduleobject.c #122282](https://github.com/python/cpython/pull/122282)
> * [[3.13] gh-116322: Fix typo in the GH-ifdef check (GH-122268) #122284](https://github.com/python/cpython/pull/122284)

Bro video magyar ul
