### ISSUE TITLE
Relax error string text expectations in SSL-related tests

### ISSUE THREAD

**Issue by WillChilds-Klein** [python/cpython#116333]
# Feature or enhancement

### Proposal:

This Issue is a follow-up to [prior discussion](https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505) on the python Ideas discussion board. Please see that page for background and discussion.

### Has this already been discussed elsewhere?

There is ongoing discussion of this feature proposal on [Python's discussion board](https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505) as well PR #116334.

### Links to previous discussion of this feature:

https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505

### Linked PRs
* gh-116334
* gh-117136
* gh-117227
* gh-117229

**Comment by gpshead** [comment]
Thanks for doing this. With a Google hat on: We've been meaning to push some of our BoringSSL diffs upstream, this nicely takes care of part of that.  The PR has been set to automerge.

Something that would be useful for CPython are build bots configured to build and testing against libraries like AWS-LC and BoringSSL as it'll help us maintain this kind of (rarely changing) test needs going forward.

On the BoringSSL side that isn't trivial to setup - but is on my long list of desirable things to look into so we can justify getting more of our boringssl support diffs upstream here without being seen as a maintenance burden.
