### ISSUE TITLE
New CI failures

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116391]
# Bug report

There are multiple CI failures right now:
- https://dev.azure.com/Python/cpython/_build/results?buildId=152036&view=logs&j=0fcf9c9b-89fc-526f-8708-363e467e119e&t=bd551f17-1f0d-5946-45f1-d677b25fe3f7 Windows has `test.test_multiprocessing_spawn.test_manager` failure
- AMD64 Debian PGO 3.x/7937 fails https://buildbot.python.org/all/#/builders/249/builds/7937 has 3 failures:
  - test.test_multiprocessing_fork.test_processes
  - test.test_multiprocessing_forkserver.test_processes
  - test.test_multiprocessing_spawn.test_processes

**Comment by gpshead** [comment]
reopen specific issues if any of these are still true. I doubt it, we'd not have been able to release 3.13 if so.
