### ISSUE TITLE
Warning: "'fprintf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'int64_t'"

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116386]
# Bug report

<img width="1297" alt="Снимок экрана 2024-03-06 в 00 54 29" src="https://github.com/python/cpython/assets/4660275/92f67751-1bba-438d-8a4a-f15e405c31fb">

Happens in `Modules/_xxinterpqueuesmodule.c`, spotted on https://github.com/python/cpython/pull/116371

### Linked PRs
* gh-116387

**Comment by ericsnowcurrently** [comment]
FTR, I fixed this in gh-116369.  However, in that PR I used `PRId64` one too many times and a new warning showed up.  (See https://github.com/python/cpython/pull/116369#issuecomment-1979773707.)  @sobolevn's PR fixes that.
