### ISSUE TITLE
New warnings: `variable ‘right’ set but not used [-Wunused-but-set-variable]`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#116424]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/116423/files and https://github.com/python/cpython/pull/116421/files

### CPython versions tested on:

CPython main branch

**Comment by Fidget-Spinner** [comment]
Duplicate of https://github.com/python/cpython/issues/116420

**Comment by Eclips4** [comment]
Oh, indeed. Sorry for the noise!
