### ISSUE TITLE
Casting KeyError to string adds extra quotes

### ISSUE THREAD

**Issue by finsberg** [python/cpython#116408]
# Bug report

### Bug description:

When calling `str` on a KeyError it adds extra quotes around the string. So the following example fails
```python
msg = "some message"
try:
    raise KeyError(msg)
except KeyError as ex:
    assert str(ex) == msg
```
while the following works
```python
msg = "some message"
try:
    raise KeyError(msg)
except KeyError as ex:
    assert str(ex) == f"'{msg}'"
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux, macOS

**Comment by AlexWaygood** [comment]
FWIW, while this does look strange, I'd recommend doing something like this instead as part of a test suite:

```py
msg = "some message"
try:
    raise KeyError(msg)
except KeyError as ex:
    assert ex.args == (msg,)
```

**Comment by finsberg** [comment]
I mean the following runs fine
```python
msg = "some message"
KeyError(msg).__str__() == f"'{msg}'"
LookupError(msg).__str__() == msg
```
so there is something special about `__str__` for `KeyError`.

**Comment by finsberg** [comment]
OK, looks like this is intentional: https://github.com/python/cpython/blob/main/Objects/exceptions.c#L2597-L2610

**Comment by ronaldoussoren** [comment]
The missing key reported by `KeyError` can be an arbitrary value. The current string representation gives different output for `KeyError("42")` and `KeyError(42)` and hence makes is slightly easier to debug unexpected key errors.
