### ISSUE TITLE
Use explicit constants in stack effects when known.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#116468]
We use `oparg` for stack effects even when `oparg` is a constant for a particular specialization.
For example `UNPACK_SEQUENCE_TUPLE` is defined as:
```
inst(UNPACK_SEQUENCE_TWO_TUPLE, (unused/1, seq -- values[oparg]))
```
resulting in slightly inefficient code. It should be defined as:
```
inst(UNPACK_SEQUENCE_TWO_TUPLE, (unused/1, seq -- val1, val0))
```

### Linked PRs
* gh-116469

**Comment by hugovk** [comment]
Triage: can this issue be closed?
