### ISSUE TITLE
Do not try to import `_winreg` in `platform` module

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116493]
# Bug report

`_winreg` was renamed to `winreg` during Python2 -> Python3 migration. Right now, there's no `_winreg` module.

Somehow this code got in 5 years ago in https://github.com/python/cpython/issues/80101 and https://github.com/python/cpython/commit/62dfd7d6fe11bfa0cd1d7376382c8e7b1275e38c

I think this was just missed during the code review and should be remove, I am going to send a PR that simplify this code.

### Linked PRs
* gh-116494

**Comment by serhiy-storchaka** [comment]
It was initially added as "winreg" in 9f3712c6f15b8bde9520932994146233fe1d0676, then renamed to "_winreg" in 270e19b060fc027c10d44a2f4941673b6165f419, then renamed back to "winreg" in 38feaf0fef244879411f094a7e68f542a6771dea (bpo-2879/gh-47128).
