### ISSUE TITLE
Split hot and cold parts of the templates.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#116422]
### Linked PRs
* gh-116813
* gh-116817
* gh-116832

**Comment by markshannon** [comment]
In order to split out the cold parts of instructions we will need to support jumps within executors.
Something like:
```
tier2 op(_JUMP_TIER2, (offset/4 --)) {
    JUMP_BY(offset);
}
```

@brandtbucher How much effort to support this in the JIT?
I assume not that much as the prototype must have supported `_POP_JUMP_IF_FALSE`.

**Comment by brandtbucher** [comment]
Not hard. We already loop once to get the total compiled size, so collecting offsets during that same step isn't difficult.

**Comment by brandtbucher** [comment]
And yeah, the prototype already did this at one point back when we had exit stubs.

**Comment by brandtbucher** [comment]
Maybe not worth pursuing yet, but just realized: if we make all jumps backwards (meaning, put cold stubs *before* the entry point) then we can emit the entire thing in one backward pass once we have a slab allocator.
