### ISSUE TITLE
Typo in documentation in the collections library.

### ISSUE THREAD

**Issue by yakovsushenok** [python/cpython#116485]
# Documentation
It seems like there is a typo on line 634 [here](https://github.com/python/cpython/blob/a8e814db96ebfeb1f58bc471edffde2176c0ae05/Lib/collections/__init__.py#L634)?

Instead of `in the some of original`, it should be `in some of the original`? 

### Linked PRs
* gh-116486
* gh-116489
* gh-116490

**Comment by varungole** [comment]
https://github.com/python/cpython/pull/116486
