### ISSUE TITLE
Possible undefined behavior in `arraymodule` and `getargs`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116447]
# Bug report

## Problem

Recently I got contacted by a team of static analysis enthusiasts, who analyze CPython's internals for bugs.

They have found this:

![photo_2024-03-07 10 15 01](https://github.com/python/cpython/assets/4660275/93817720-b74f-4be7-89b0-b7eb1b9d24b2)

Problematic lines:
- https://github.com/python/cpython/blob/40b79efae7f8e1e0d4fd50c13f8b7514203bc6da/Modules/arraymodule.c#L242-L250
- https://github.com/python/cpython/blob/40b79efae7f8e1e0d4fd50c13f8b7514203bc6da/Python/getargs.c#L615-L630
- `object.h` is ignored for now as unrelated

Basically, this issue is about `char` vs `unsigned char`.

Built with:

```
CC=clang CXX=clang++ CXXFLAGS=$"-fsanitize=integer,undefined" CFLAGS="-fsanitize=integer,undefined" LDFLAGS="-fsanitize=integer,undefined" ./configure
```

Built on Linux.

To reproduce this warning you would need to run this code with CPython built with some external extension, but it just finds the desribed issues:

```python
from array import array
array('B', [234])
```

**Important note**: I cannot find and reproduce any buggy behavior, I can only see the static analysis report.

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.

Reporter: Svyatoslav Tereshin (s.tereshin@fobos-nt.ru).

## Proposed solution

The solution is proposed by me :)

```diff
diff --git Modules/arraymodule.c Modules/arraymodule.c
index df09d9d8478..317f4974814 100644
--- Modules/arraymodule.c
+++ Modules/arraymodule.c
@@ -247,7 +247,7 @@ BB_setitem(arrayobject *ap, Py_ssize_t i, PyObject *v)
     if (!PyArg_Parse(v, "b;array item must be integer", &x))
         return -1;
     if (i >= 0)
-        ((char *)ap->ob_item)[i] = x;
+        ((unsigned char *)ap->ob_item)[i] = x;
     return 0;
 }
 
diff --git Python/getargs.c Python/getargs.c
index 08e97ee3e62..a7bfad4dd69 100644
--- Python/getargs.c
+++ Python/getargs.c
@@ -612,7 +612,7 @@ convertsimple(PyObject *arg, const char **p_format, va_list *p_va, int flags,
     switch (c) {
 
     case 'b': { /* unsigned byte -- very short int */
-        char *p = va_arg(*p_va, char *);
+        unsigned char *p = va_arg(*p_va, unsigned char *);
         long ival = PyLong_AsLong(arg);
         if (ival == -1 && PyErr_Occurred())
             RETURN_ERR_OCCURRED;
```

Why?
- `arraymodule` do similar casts for other setters, like: `(wchar_t *)ap->ob_item`, etc. This seems like a correct thing to do here as well
- `getargs`'s `'b'` works with `unsigned char`, according to the docs: https://github.com/python/cpython/blob/40b79efae7f8e1e0d4fd50c13f8b7514203bc6da/Doc/c-api/arg.rst#L232-L234

Local tests pass after this change.

However, I know that different platforms and different compilers might have different pitfalls here.
So, I would like to discuss this before I will send a patch (or if at all).

CC @serhiy-storchaka 

### Linked PRs
* gh-116459
* gh-116496
* gh-116497

**Comment by serhiy-storchaka** [comment]
It perhaps does not matter on platforms supported by Python, but changing `char *` to `unsigned char *` in these cases would not harm. This is correct from a purist point of view.
