### ISSUE TITLE
Warning: "variable ‘right’ set but not used" in `optimizer_cases.c.h`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116420]
# Bug report

<img width="983" alt="Снимок экрана 2024-03-06 в 19 36 37" src="https://github.com/python/cpython/assets/4660275/64916f6b-93bb-4723-9c62-9e86d57048bf">

CC @Fidget-Spinner 

### Linked PRs
* gh-116466

**Comment by Fidget-Spinner** [comment]
Will fix this soon with another PR later. Don't want to run like 4 macOS jobs just for a `(void)right` :).

**Comment by Fidget-Spinner** [comment]
Nevermind, it's big enough that I created its own PR for it.
