### ISSUE TITLE
C API: Move limited C API tests from _testcapi to a new _testlimitedcapi extension

### ISSUE THREAD

**Issue by vstinner** [python/cpython#116417]
Currently, the `_testcapi` C extension is partially built with the limited C API and partially with the non-limited C API. It can lead to some confusion: which API is being tested?

I proposed to create a new `_testlimitedcapi` extension which is only built with the limited C API. It can only access to the limited C API and so there is a lower risk to test the non-limited C API by mistake.

### Linked PRs
* gh-116419
* gh-116567
* gh-116568
* gh-116570
* gh-116571
* gh-116573
* gh-116598
* gh-116602
* gh-116974
* gh-116986
* gh-116993
* gh-117001
* gh-117006
* gh-117014

**Comment by vstinner** [comment]
Note to myself: `pyos.c` has no associated Python test!?

**Comment by serhiy-storchaka** [comment]
What Limited C API? Shouldn't there be multiple separately compiled extensions, one for each version?

**Comment by vstinner** [comment]
> What Limited C API? Shouldn't there be multiple separately compiled extensions, one for each version?

I only plan to test a single limited C API version per C file. IMO it's already better than not testing the limited C API.

* Currently, `Modules/_testlimitedcapi/parts.h` uses `#define Py_LIMITED_API 0x03050000` by default, Python 3.5.
* `heaptype_relative.c` needs the limited C API version 3.12 for `PyType_FromMetaclass()`.
* `vectorcall_limited.c` needs the limited C API version 3.12 for `PyObject_Vectorcall()`.

**Comment by serhiy-storchaka** [comment]
What is the purpose of testing the Limited C API separately? I thought that it is to check that these functions are available in the specified Limited C API version, but if we use higher version, this does not work.

There are many new functions in 3.13, so you would need to bump the version to 3.13.

`PySlice_GetIndicesEx()` is actually defined differently depending on Py_LIMITED_API.

**Comment by vstinner** [comment]
Ok, I moved almost all tests which are compatible with the limited C API to the new `_testlimitedcapi` extension. Most of `_testlimitedcapi` code is testing the limited C API version 3.5: an old version on purpose.

Later, we might consider to test the different implementation of a single function depending on the limited C API version, and test non-limited vs limited implementation. But I'm not sure how to avoid code duplication.

Since the initial goal is completed, I close the issue.
