### ISSUE TITLE
Too many tier 2 micro-ops are marked as escaping

### ISSUE THREAD

**Issue by markshannon** [python/cpython#116596]
# Bug report

### Bug description:

There are too many `_SET_IP` and `_CHECK_VALIDITY` micro-ops being inserted into tier 2 code.

There are two causes of this:
1. Too many micro-ops are marked as escaping
2. Python call uops do not technically escape but must be preceded by `_SET_IP` in order to correctly set the return address. We need a way of marking these, so that we insert `_SET_IP` before them, but do not needlessly insert `_CHECK_VALIDITY` after them.

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-116597

**Comment by hugovk** [comment]
Triage: can this issue be closed?

**Comment by markshannon** [comment]
Yes
