### ISSUE TITLE
`sortperf.py` is broken

### ISSUE THREAD

**Issue by pochmann3** [python/cpython#116576]
# Bug report

### Bug description:

It's supposed to measure sort speed for different kinds of data, from best to worst case. But currently it shows about the same speed for all kinds, because the same list object is sorted a thousand times. Which means all but the first sort are just sorting the already sorted list. And that dominates the total time, making the first=real sort insignificant.

Oddly it was specifically changed to be this way, [here](https://github.com/python/cpython/pull/114687/commits/7c2dd81535c67477188e9adf157f5fe158023ac8), from

```python
    def _prepare_data(self, loops: int) -> list[float]:
        bench = BENCHMARKS[self._name]
        return [
            bench(self._size, self._random)
            for _ in range(loops)
        ]
```
to:
```python
    def _prepare_data(self, loops: int) -> list[float]:
        bench = BENCHMARKS[self._name]
        return [bench(self._size, self._random)] * loops
```
There was even a [comment](https://github.com/python/cpython/pull/114687#issuecomment-1945650107) showing that all cases from best to worst now take about the same tiny time 29.2 us, calling it an optimization (and I think it refers to the above change). So is this intentional/desired? I highly doubt that, but if it's a mistake, it's really weird.

The whole update was btw called *"Move Lib/test/sortperf.py to Tools/scripts"*, but in reality it wasn't just moved but completely rewritten. I don't think that was good, in my opinion moves should just be moves, not hide massive changes.

@sobolevn @tim-one 

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-116577
* gh-116582
* gh-116583

**Comment by sobolevn** [comment]
Indeed, thanks for noticing! 👍

**Comment by pochmann3** [comment]
Thanks, looks alright now, both the code fix and the times in the PR comment.
