### ISSUE TITLE
Docs: incorrect error message

### ISSUE THREAD

**Issue by Privat33r-dev** [python/cpython#116563]
# Documentation

[Part 8](https://docs.python.org/3/tutorial/errors.html#syntax-errors) of the Python tutorial contains the following example:
```python
>>> while True print('Hello world')
  File "<stdin>", line 1
    while True print('Hello world')
                   ^
SyntaxError: invalid syntax
```

As tested on Python 3.12 and 3.13, the actual error highlight would be:
```py
>>> while True print('Hello world')
  File "<stdin>", line 1
    while True print('Hello world')
               ^^^^^
SyntaxError: invalid syntax
```

hence the following description might be inaccurate as well:
> The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected. The error is caused by (or at least detected at) the token preceding the arrow: in the example, the error is detected at the function [print()](https://docs.python.org/3/library/functions.html#print), since a colon (':') is missing before it. File name and line number are printed so you know where to look in case the input came from a script.

I guess that @pablogsal as an expert in a Python error messages might provide more data on current error handling :)

### Linked PRs
* gh-116569
* gh-116624
* gh-116625

**Comment by terryjreedy** [comment]
The change happened with the new parser in 3.10.  I will change the example and change the text to 'one or more'.  The rest is still the same for me also.  Thank you for linking to spot of the foul.
