### ISSUE TITLE
Updating a zip file with unexpected file size may corrupt its content

### ISSUE THREAD

**Issue by distantvale** [python/cpython#116500]
# Bug report

### Bug description:

Certain zip files were appended by random byte data incorrectly without properly opening the zip file and adding another member.
That data should generally be ignored or fixed (removed) the next time the file is opened for writing.
zipinfo shows a warning when opening such files:
`warning [AAA.ZIP]:  4096 extra bytes at beginning or within zipfile`
However python assumes the extra bytes are at the beginning of the zip file and sets the `concat` value equal to the size of the extra bytes.
When the file is opened for writing (for example, for removing a comment) and then closed, the file gets corrupted - all CD local header offets are increased by the concat value.

Notice the following code in zipfile.py when opening a zip file:
```python
# "concat" is zero, unless zip was concatenated to another file
    concat = endrec[_ECD_LOCATION] - size_cd - offset_cd
```

And later on the value gets applied to the local header offsets:
`x.header_offset = x.header_offset + concat`

I'm wondering if that `concat` value is even necessary - it's seems to be there in order to support cases in which the zip file was appended to another file, but that kind of scenario seems highly abnormal and not very generic, it's not a proper use-case of zip files as far as I can tell.
Furthermore, why would the local header ever gets offseted when a zip file is opened? It's assumed the zip file internal data is incorrect, I'd think internal zip data should never be updated unless explicitely requested (adding member, removing comment etc.).

Would appreciate if anyone can shed some light on the rationale behind this logic, as it seems to add support for one thing while breaking a different thing that might be more appropriate.

Thanks!

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
It is pretty common to have a zip file appended to another file.

* Self-extracting archives.
* Single-file programs that read resources from a zip file appended to executable.

Could you provide a small script that demonstrates the problem?

**Comment by distantvale** [comment]
Hey,

Sure, I can try to create such a zip, should be pretty straightforward.

Imagine taking a valid zip and appending the last X bytes from the file onto itself, so it becomes:

- compressed files content
- CD
- end of CD
- random bytes
- CD
- end of CD

python would open that zip file based on the 2nd end of CD (it reads from the end of the zip file) and not the 1st one, and since the location of the CD doesn't match the expected location, python thinks the zip file was appended to another file.
So it's enough to open the file in order to update the comment, and the zip file gets corrupted, since the CD is re-written with the wrong file offsets.

Does that make sense?

I think maybe it might be worth it to search for the CD from the beginning of the zip file and not assume that the end of CD is at the end of the file. It's more common to find corrupt data at the end of a zip file, so it might be a bit more robust to look for the CD/end of CD from the beginning of the file, which I would assume zipinfo does.

**Comment by distantvale** [comment]
any thoughts on this?

**Comment by serhiy-storchaka** [comment]
Sorry, I missed your comment. Thanks for the reminder.

No, I do not think that your example is a valid ZIP file. I am sure that most of other ZIP tools will complain. Of course, there are specialized programs like `pkzipfix` which scan the file from beginning and restore the central directory in case it was corrupted, but they are emergency tools, like programs that allow restoring recently deleted files or extract files from broken discs. Use such tools to fix broken ZIP files, but be aware that they are not panacea.

There is other exotic use case for reading a ZIP file from beginning: when it is read from a stream (network socket, pipe, magnetic type) and you have no place to save it all before the start of processing. This requires completely different API. I am not sure that it is worth to add such feature in the stdlib.

**Comment by distantvale** [comment]
No problem, closing this one then.
