### ISSUE TITLE
Consider adding public PyLong_GetSign() function

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#116560]
# Feature or enhancement

### Proposal:

Currently there is no way to determine the sign of the PyLongObject value and CPython extensions use private macroses like ``_PyLong_IsNegative()``: https://github.com/aleaxit/gmpy/blob/eb8dfcbd84abcfcb36b4adcb0d5c6d050731dd75/src/gmpy2_convert_gmp.c#L56

``PyLong_Sign()`` will offer GMP-like API to do this.

This was suggested before: https://github.com/python/cpython/issues/102471#issuecomment-1620284985

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-116561

**Comment by serhiy-storchaka** [comment]
I think that `PyLong_IsPositive()`, `PyLong_IsNegative()` and `PyLong_IsZero()` are more useful in practice, but there may also be a smaller need for `PyLong_Sign()`. I suggest to implement the former functions first, and then look if there are enough use cases left for the latter.

**Comment by skirpichev** [comment]
I worry only on PyLongObject input (probably as most consumers of API).  Why three functions better then one?  (Disclaimer: API, produced by C-API WG seems too generic for me; IMHO ``_PyLong_Sign()`` interface fits use cases in real world much better.)

**Comment by vstinner** [comment]
Implemented in commit https://github.com/python/cpython/commit/61d3ab32da92e70bb97a544d76ef2b837501024f

**Comment by skirpichev** [comment]
@vstinner, if I correctly interpret voting, PyLong_IsPositive/Negative/Zero API got support.  

Lets reopen this to track implementation, as it's part of the same API?

**Comment by serhiy-storchaka** [comment]
It is better to open a separate issue.
