### ISSUE TITLE
Creating a nested list with multiplication operand leads to memory pointer failure

### ISSUE THREAD

**Issue by fninsiima** [python/cpython#116584]
# Bug report

### Bug description:

To create a list of length `n` containing element `x`, the notation is `mylist = [x] * n`. For example, `mylist = [0] * 3` leads to `[0, 0, 0]`. In order to change the first element, the notation `mylist[0] = 1` changes `mylist` to `[1, 0, 0]`.

However, the notation to assign/alter an element changes when i created a nested list with the multiplication operand. 
```python
li = [[0]]*3 # leads to [[0], [0], [0]]
```

If I want to append an element to the first list via `li[0].append(3)`, I expect the output to be `[[0, 3], [0], [0]]`

However, the new output is `[[0, 3], [0, 3], [0, 3]]`.

Any change to an inner list of the nested list results in a change to all the inner lists.

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Hello!
There's no bug; it's a expected behaviour, for more information read the [doc](https://docs.python.org/3.12/faq/programming.html#how-do-i-create-a-multidimensional-list)
