### ISSUE TITLE
Mutable default values example - TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by dec1** [python/cpython#116535]
# Documentation

The example:

[dataclasses.html#mutable-default-values](https://docs.python.org/3/library/dataclasses.html#mutable-default-values)

```python
@dataclass
class D:
    x: list = []      # This code raises ValueError
    def add(self, element):
        self.x += element
```

not only raises the `ValueError` being discussed, but also an unwanted `TypeError` when you call `add()`, that distracts from the point of the example.
Would be better to call `append()` to add a single element to the list

### Linked PRs
* gh-116536
* gh-116538
* gh-116551
* gh-116552

**Comment by Privat33r-dev** [comment]
Your point is valid. Moreover, using `.append()` instead of `+=` would match the style used in the first example without dataclasses, which is going to increase consistency and remove distractions.

**Comment by ericvsmith** [comment]
Merged. Thanks!
