### ISSUE TITLE
Python now starts supporting JIT compile. It would be better to support AOT compile officially, too.

### ISSUE THREAD

**Issue by Foxchandaisuki** [python/cpython#116531]
# Feature or enhancement

### Proposal:

I am very happy to hear that Python now supports JIT(Just In Time) compile feature!

Although it makes Python program run much faster than now, still some problems remain.

One is that we still need Python to be installed at end-users' computers. Another one is that the program will be still slow at the starting moment.

Supporting AOT compile is the key to solve both problems above.

### Has this already been discussed elsewhere?

No response given

**Comment by terryjreedy** [comment]
I believe "Major feature proposals should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue. Wait until it's clear that most people support your idea before filling in this form." applies to this proposal.  If so, this GH issue should be closed and a new thread started on Discourse.

**Comment by sobolevn** [comment]
I agree with @terryjreedy, please open a new discussion on Discourse.
