### ISSUE TITLE
Docs improvement: external sites open in the same tab of browser, not new tab

### ISSUE THREAD

**Issue by ftnext** [python/cpython#116603]
# Documentation

In Python documentation, external sites open in the same tab of browser (e.g. PEP 602 link)
https://docs.python.org/3.13/whatsnew/3.13.html#summary-release-highlights

<img width="828" alt="image" src="https://github.com/python/cpython/assets/21273221/2c5c2555-ae4e-4d99-8b0c-d0e6011f0110">

### Linked PRs
* gh-116595

**Comment by hugovk** [comment]
Thank you Nikkie-san for opening the PR, and for thoroughly testing it.

Personally, I find it very annoying when websites take the choice away from me and open all external links in new tabs. I command+click when I want that to happen.

And usability and accessibility advice (and guidelines) generally discourage it:

* https://www.nngroup.com/articles/new-browser-windows-and-tabs/
* https://www.w3.org/TR/WCAG20-TECHS/G200.html
* https://it.wisc.edu/learn/make-it-accessible/develop-accessible-websites/when-to-open-links-in-a-new-tab/
* https://adrianroselli.com/2020/02/link-targets-and-3-2-5.html
