### ISSUE TITLE
test_concurrent_futures/test_shutdown.py: test_cancel_futures_wait_false flaky

### ISSUE THREAD

**Issue by colesbury** [python/cpython#116682]
The test looks like:

https://github.com/python/cpython/blob/bb66600558cb8d5dd9a56f562bd9531eb1e1685f/Lib/test/test_concurrent_futures/test_shutdown.py#L243-L250

The problem is that if the worker thread starts executing after the `shutdown()` call, then the task will be canceled (because `cancel_futures=True`) and nothing will be printed. This happens sometimes with the GIL and more frequently in the free-threaded build with the GIL disabled.

You can reliably trigger the problematic behavior by adding a short sleep at the beginning of the worker thread:

https://github.com/python/cpython/blob/bb66600558cb8d5dd9a56f562bd9531eb1e1685f/Lib/concurrent/futures/thread.py#L69-L70

i.e., add a `time.sleep(0.2)` before the `if` statement.

This test has been reported failing previously, but those issues were closed:

* https://github.com/python/cpython/issues/89099
* https://github.com/python/cpython/issues/88650 (not entirely clear if it's the same issue)

### Linked PRs
* gh-116683
* gh-116692
* gh-116693

**Comment by sobolevn** [comment]
This might be related? https://github.com/python/cpython/actions/runs/8261299493/job/22598342550

```
 ======================================================================
FAIL: test_check_output_timeout (test.test_subprocess.ProcessTestCaseNoPoll.test_check_output_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/cpython/cpython/Lib/test/test_subprocess.py", line 286, in test_check_output_timeout
    self.assertEqual(c.exception.output, b'BDFL')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: None != b'BDFL'

======================================================================
FAIL: test_check_output_timeout (test.test_subprocess.RunFuncTestCase.test_check_output_timeout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/runner/work/cpython/cpython/Lib/test/test_subprocess.py", line 1694, in test_check_output_timeout
    self.assertEqual(c.exception.output, b'BDFL')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: None != b'BDFL'

----------------------------------------------------------------------
```

**Comment by colesbury** [comment]
@sobolevn I think the underlying cause is different:
- `test_check_output_timeout` failure is due to starting a subprocess taking too long (>3 seconds) on a heavily loaded machine
- `test_cancel_futures_wait_false` failure was due to a race condition involving threads

They are similar in that sometimes the output is empty and the tests results are inconsistent.

**Comment by colesbury** [comment]
Let's open a separate issue for `test_check_output_timeout`
