### ISSUE TITLE
Make `_warnings.c` thread-safe in free-threaded build

### ISSUE THREAD

**Issue by colesbury** [python/cpython#116664]
# Feature or enhancement

The `warnings` implementation is split between Python (`warnings.py`) and C (`_warnings.c`). There are a few bits of code in the C module that are not thread-safe without the GIL:

The `Py_SETREF` calls are not thread-safe if concurrent writers try to overwrite the same field (e.g., `st->once_registry`). We can probably use critical sections to make it thread-safe.

`get_once_registry`: https://github.com/python/cpython/blob/df4784b3b7519d137ca6a1aeb500ef59e24a7f9b/Python/_warnings.c#L259

`get_default_action`:
https://github.com/python/cpython/blob/df4784b3b7519d137ca6a1aeb500ef59e24a7f9b/Python/_warnings.c#L290

`get_filter`:
https://github.com/python/cpython/blob/df4784b3b7519d137ca6a1aeb500ef59e24a7f9b/Python/_warnings.c#L315

Some uses of borrowed references are likely not thread-safe

* `_PyDict_GetItemWithError` (replace with `PyDict_GetItemRef`?)

### Linked PRs
* gh-116768
* gh-116959
* gh-117373
* gh-117374

**Comment by erlend-aasland** [comment]
I'd like to take a stab at this.

**Comment by erlend-aasland** [comment]
FYI: My CPython time is very fragmented these days, so I'll move forward with a handful of smaller PRs instead of one PR that fixes everything.

**Comment by erlend-aasland** [comment]
For the module state setref operations: AFAICS all of these happen in `warn_explicit()`[^1] helpers, so perhaps we can get away with running the `warn_explicit()` calls as critical sections.


[^1]: the C function, not the Python API

**Comment by erlend-aasland** [comment]
BTW, don't we need to protect `_warnings._filters_mutated`?

https://github.com/python/cpython/blob/0fa571dbcdf19b541276cb00bb929381930467b2/Python/_warnings.c#L1169-L1182

Possibly also the `already_warned(...)` calls, since that function reads `st->filters_version`.

**Comment by erlend-aasland** [comment]
(Reopening; #116768 introduced compilation warnings on non-free-treaded builds.)

**Comment by colesbury** [comment]
`_warnings._filters_mutated`: Yes, I think so. Although I think the whole way it's used in `catch_warnings` is not really thread-safe even with the GIL.

`already_warned(...)`: I think the calling code already does the locking? It would be good to add an assertion that it's locked at least.

**Comment by erlend-aasland** [comment]
> `_warnings._filters_mutated`: Yes, I think so. Although I think the whole way it's used in `catch_warnings` is not really thread-safe even with the GIL.

👍 BTW, I'm a little bit sceptical about using the `@critical_section` Argument Clinic directive here, since that uses the module object, and not the mutex in the module state, to lock the critical section. Perhaps it does not matter.

> `already_warned(...)`: I think the calling code already does the locking? It would be good to add an assertion that it's locked at least.

Yep, an assert would be good.
