### ISSUE TITLE
Inconsistent behavior for `sys.monitoring.events.CALL`

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#116626]
# Bug report

### Bug description:

According to the docs, `CALL` event should be emitted as long as there's a function call in Python code. However, `CALL_FUNCTION_EX` does it differently - it only emits the event when it's a call to C function. So monitoring the following code produce different results:

```python
def f(a, b):
    return a + b
f(1, 2)  # Emits CALL event
args = (1, 2)
f(*args)  # Does NOT emit CALL event
```

I think we should just fix `CALL_FUNCTION_EX` to make it work the same as the other CALL instructions.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-116627
* gh-116732

**Comment by markshannon** [comment]
Yes, `CALL_FUNCTION_EX` should behave exactly like other `CALL` instructions.

**Comment by hugovk** [comment]
Closing because the PR has been merged and backported. Please re-open if there's more needed here.
