### ISSUE TITLE
Race condition in `test_queue.test_shutdown_immediate_put_join`

### ISSUE THREAD

**Issue by colesbury** [python/cpython#116631]
There is a race condition in `test_shutdown_immediate_put_join` that leads to `ValueError: task_done() called too many times`. This happens frequently in the free-threaded build. It may also happen in the default build depending on when the GIL is released. You can reliably reproduce the issue by adding a short sleep at the start of [`Queue.task_done()`](https://gist.github.com/colesbury/18341ad58d3981b05b5d5703f296e53e).

The problem is that we call `q.task_done()` in a thread concurrently with `q.shutdown(immediate=True)`.

https://github.com/python/cpython/blob/3e45030076bf2cfab41c4456c73fb212b7322c60/Lib/test/test_queue.py#L581-L586

The queue has one unfinished task. If, `q.task_done()` finishes first then everything is okay. However, if the `q.shutdown(immediate=True)` happens first, it will remove the single outstanding task and the `q.task_done()` will raise an exception.

cc @EpicWink

### Linked PRs
* gh-116670

**Comment by EpicWink** [comment]
CC @YvesDup
