### ISSUE TITLE
Easy to corrupt interpreter state via ctypes.

### ISSUE THREAD

**Issue by gitamohr** [python/cpython#116671]
# Crash report

### What happened?

```python
>>> def murder(victim):
...     import sys, ctypes
...     c = ctypes.cdll.LoadLibrary('')
...     for i in range(sys.getrefcount(victim)):
...         _ = c.Py_DecRef(ctypes.c_voidp(id(victim)))
... 
>>> murder('goodbye cruel world')
>>> murder('goodbye cruel world')
Segmentation fault (core dumped)
```
Certainly `ctypes` is a big gun, but it might make sense to have `id()` not return the `PyObject *` directly.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.9.16 (main, Aug 26 2023, 05:05:37)  [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]

**Comment by JelleZijlstra** [comment]
That's what ctypes does. If you set off a bomb, don't be surprised if it explodes.

Changing the return value of `id()` would break lots of code and wouldn't change the essential fact that ctypes lets you break things in many ways if you are not careful.
