### ISSUE TITLE
Windows installer options ignored

### ISSUE THREAD

**Issue by DJMcMayhem** [python/cpython#116672]
# Bug report

### Bug description:

I am on Windows 10 and I'm trying to make a script that installs python 3.11.5 as well as a few other requirements my software has. When I run

````
python-3.11.5-amd64.exe /InstallAllUsers=1 /InstallLauncherAllUsers=0 /AppendPath=1
````

from the command line, it does not install for all users or append the path. I have tried uninstalling every version of python and the launcher before running this and that has no effect. I have also tried this with and without `/passive` or `/quiet` and it still does not seem to respect the options.

To be more specific, if I include `/passive` the installer runs but installs it for only one user into APPDATA. If I don't include `/passive`, then the installer popup that I get doesn't have "Install For All Users" or "Add executable to PATH" checked by default. 

I have also attempted this in both a regular command prompt and an elevated command prompt.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
These are not options, but argument specifiers. Pass them without the leading forward slash:

```
python-3.11.5-amd64.exe InstallAllUsers=1 InstallLauncherAllUsers=0 AppendPath=1
```

**Comment by DJMcMayhem** [comment]
@zooba Wow, that is exactly my problem. Now I feel silly for raising an issue for this when it was just a stupid little syntax error. I appreciate your help though.
