### ISSUE TITLE
unreachable switch-case in byteobject.c:_PyBytes_FormatEx() and unicodeobject.c:mainformatlong()

### ISSUE THREAD

**Issue by NGRsoftlab** [python/cpython#116639]
# Bug report

### Bug description:

These formating functions have similar code, example from https://github.com/python/cpython/blob/main/Objects/unicodeobject.c#L13912:
```C
    if (PyLong_CheckExact(v)
        && arg->width == -1 && arg->prec == -1
        && !(arg->flags & (F_SIGN | F_BLANK))
        && type != 'X')
    {
/*
... skipped ...
*/
        switch(type)
        {
/*
... skipped ...
*/
            case 'x':
            case 'X':
                base = 16;
                break;
        }
/*
... skipped ...
*/
```

https://github.com/python/cpython/blob/main/Objects/bytesobject.c#L832 is the other problem part.

case 'X' will never be reached, so it's useless, because type is checked never be equal to 'X'.

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-116640

**Comment by serhiy-storchaka** [comment]
It is safe to remove these lines, but I am not sure that it make the code clearer. It may even make it harder to read, because the absent case looks like a bug at first glance, and you may spend some time to ensure that it is not really a bug.

**Comment by NGRsoftlab** [comment]
@serhiy-storchaka you haven't closed this issue. Are you waiting for other commiters opinion, or should i do something?

**Comment by serhiy-storchaka** [comment]
Yes, I waited for other core developers or triagers opinion. Or you closing it yourself if I my arguments looked convincing to you.

Since this change is almost cosmetic and did not attract attention of other people, I close it.
