### ISSUE TITLE
Old generic `TypeAlias` syntax definition fails in runtime if `TypeVar` is on the right hand side

### ISSUE THREAD

**Issue by nerodono** [python/cpython#116645]
# Bug report

### Bug description:

Let's design `Identity[T]` generic type alias which will return type `T` when parametrized:
```python
from typing import TypeVar, TypeAlias

T = TypeVar("T")
Identity: TypeAlias = T

x: Identity[int] = 10
```
Mypy thinks that this code is well-formed: https://mypy-play.net/?mypy=master&python=3.12&gist=726a5b5a1f3e7f54a40ee0e51b0e9b97
pyright shares mypy's opinion

Apparently it fails in runtime:
```python
    x: Identity[int] = 10
       ~~~~~~~~^^^^^
TypeError: 'TypeVar' object is not subscriptable
```

This can be fixed if Identity is defined like so:
```python
Identity: TypeAlias = Annotated[T, AnyMetadataForExampleNone]
```

I think that's unintentional not only because mypy and pyright reporting this code as well-formed, but also because
```python
type Identity[T] = T
x: Identity[int] = 10
```
Works well, there could be ambiguity between how to interpret 3.11-style generic type alias definition above
```python
# 1. as
type Identity[T] = T
# 2. or as
T = TypeVar("T")
type Identity = T
```

But since latter is ill-formed - type-checker should interpret it as 1. Also both mypy and pyright distinguish the subscription of generic and type alias:
```python
T = TypeVar("T")
x: T[int] = 10 # ill-formed

Identity: TypeAlias = T
x: Identity[T] = 10 # well-formed
```
(According to both mypy and pyright).

I propose making TypeVar runtime subscription function to return it's argument, like: `T[R] = R`, but maybe there can be other options, like how it should be interpreted if multiple types supplied? `T[R, K] = ?`.
Also as @Tishka17 in private conversation pointed out, this can be design flaw if in the future we want to support higher kinded types, would it actually be?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS

**Comment by Eclips4** [comment]
cc @JelleZijlstra

**Comment by sobolevn** [comment]
I don't think that we should introduce `[]` to `TypeVar` objects, it is clearly defined now that `TypeVar` is not subscriptable. 

Some people might assume that `[]` on `TypeVar` means that HKTs are supported, while they are not: https://github.com/python/typing/issues/548#issuecomment-1892647812

Considering your example, aliasing type vars is also rather unpopular thing to do. When you can just use the typevar itself:

````python
Identity = TypeVar('Identity')

def something(obj: Identity) -> Identity: ...
```
Your work-around with `Annotated` is also a good idea 👍

**Comment by nerodono** [comment]
> I don't think that we should introduce `[]` to `TypeVar` objects, it is clearly defined now that `TypeVar` is not subscriptable.
> 
> Some people might assume that `[]` on `TypeVar` means that HKTs are supported, while they are not: [python/typing#548 (comment)](https://github.com/python/typing/issues/548#issuecomment-1892647812)
> 
> Considering your example, aliasing type vars is also rather unpopular thing to do. When you can just use the typevar itself:
> 
> ```python
> Identity = TypeVar('Identity')
> 
> def something(obj: Identity) -> Identity: ...
> ```
> Your work-around with `Annotated` is also a good idea 👍 
> ```

So this is an issue with mypy and pyright? Also can you provide a link where `TypeVar` is explicitly defined as unsubscriptable? Either on specification page or in documentation? Haven't found that info :(
By the way, IMO HKTs should not be expressed using plain old `TypeVar`s, it requires type-checker to infer kind of type every time `TypeVar` is defined and generally lone `TypeVar` (which can be either type or type constructor) looks suspicious, I suppose it should be done like:
```python
HKT = KindedTypeVar("HKT", "* -> *") # or KindedTypeVar("HKT", 2)
```

**Comment by webHikari** [comment]
![photo_5440871374257248353_y](https://github.com/python/cpython/assets/158005693/0a7c47cf-431a-4e02-9d1a-e58d5499f312)

**Comment by JelleZijlstra** [comment]
This isn't a bug, as already explained.

> Also can you provide a link where TypeVar is explicitly defined as unsubscriptable?

That's the wrong way around. Operations are unsupported unless explicitly supported.

**Comment by nerodono** [comment]
> This isn't a bug, as already explained.
> 
> > Also can you provide a link where TypeVar is explicitly defined as unsubscriptable?
> 
> That's the wrong way around. Operations are unsupported unless explicitly supported.

Should I report this to mypy and pyright so they will reject this code?

**Comment by nerodono** [comment]
> This isn't a bug, as already explained.
> 
> > Also can you provide a link where TypeVar is explicitly defined as unsubscriptable?
> 
> That's the wrong way around. Operations are unsupported unless explicitly supported.

Also consider the following:
https://mypy.readthedocs.io/en/stable/generics.html#generic-type-aliases

> Type aliases can be generic. In this case they can be used in two ways: Subscripted aliases are equivalent to original types with substituted type variables, so the number of type arguments must match the number of free type variables in the generic type alias. Unsubscripted aliases are treated as original types with free variables replaced with Any.

So mypy defines that each time `TypeVar` appear on the `TypeAlias`'s right hand side means that that `TypeAlias` becomes bound variable, implies `Identity[R] = R`, since we substitute all occurence of T in Identity with R.
Inverse logic like "runtime subscription of TypeVar should be explicitly defined, otherwise it is undefined" doesn't work because subscriptability is implied via `TypeAlias` semantics. Or am I missing something?

**Comment by nerodono** [comment]
> This isn't a bug, as already explained.
> 
> > Also can you provide a link where TypeVar is explicitly defined as unsubscriptable?
> 
> That's the wrong way around. Operations are unsupported unless explicitly supported.

Man, we either should fix this in mypy (by forbidding creation of such type alias or by adding subscriptability to the `TypeVar`s) or **at least** document this behavior as ill-formed runtime artifact. Master mypy branch still eats this example well, happily falling in runtime - https://mypy-play.net/?mypy=master&python=3.12&gist=68189965ae5883ba7cc088a182eedf32

I can try creating the PR with the option of your choice

**Comment by sobolevn** [comment]
Yes, mypy can be fixed here 👍
