### ISSUE TITLE
Multiple Objects share same Memory Address for a Attribute with a Default Value for the Parameter

### ISSUE THREAD

**Issue by JohnGrubba** [python/cpython#116673]
# Bug report

### Bug description:

```python
class TROCKENTEST:
    def __init__(self, ses: list[str] = []):
        self.ses = ses
        pass

    def add_str(self, string: str):
        self.ses.append(string)


if __name__ == "__main__":

    test1 = TROCKENTEST()
    test2 = TROCKENTEST()
    test3 = TROCKENTEST()
    test4 = TROCKENTEST()
    test5 = TROCKENTEST()
    test6 = TROCKENTEST()
    test7 = TROCKENTEST()
    test8 = TROCKENTEST()

    test1.add_str("SES")

    print(hex(id(test1.ses)))
    print(hex(id(test2.ses)))
    print(hex(id(test3.ses)))
    print(hex(id(test4.ses)))
    print(hex(id(test5.ses)))
    print(hex(id(test6.ses)))
    print(hex(id(test7.ses)))
    print(hex(id(test8.ses)))

    print(test1.ses)
    print(test2.ses)

```
- The expected Output should be different Memory Addresses for the Variables, but for some strange reason they are all the same... There is no way this is intended.
![image](https://github.com/python/cpython/assets/63007476/4e241339-66cb-4324-8bff-bbe883f612b7)

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects

**Comment by ericvsmith** [comment]
The default value is evaluated once, not every time the method is called. This is expected behavior.
