### ISSUE TITLE
Update the "switch or case statement" section of the Design & History FAQ

### ISSUE THREAD

**Issue by RH-TLagrone** [python/cpython#116613]
# Documentation

The section [Why isn't there a switch or case statement in Python?] of the [Design and History FAQ] is out-of-date. Python has had the `match` statement [since 3.10][match].

I propose updating [Why isn't there a switch or case statement in Python?] to read:

> Starting in Python 3.10, there is!
>
> The [`match` statement](https://docs.python.org/3/reference/compound_stmts.html#the-match-statement) is used for pattern matching:
>
> ```python
> def http_error(status):
>     match status:
>         case 400:
>             return "Bad request"
>         case 404:
>             return "Not found"
>         case 418:
>             return "I'm a teapot"
>         case _:
>             return "Something's wrong with the Internet"
> ```
>
> See [PEP 634](https://peps.python.org/pep-0634/) and [PEP 636](https://peps.python.org/pep-0636/) for more information.

This proposed content emulates [Why can’t I use an assignment in an expression?] (another section in the same document), which I believe is an effective (and already-established) template for addressing a similar issue.

[Design and History FAQ]: <https://docs.python.org/3/faq/design.html>
[Why can’t I use an assignment in an expression?]: <https://docs.python.org/3/faq/design.html#why-can-t-i-use-an-assignment-in-an-expression>
[Why isn't there a switch or case statement in Python?]: <https://docs.python.org/3/faq/design.html#why-isn-t-there-a-switch-or-case-statement-in-python>
[match]: <https://docs.python.org/3/reference/compound_stmts.html#the-match-statement>

**Comment by pochmann3** [comment]
> The section [...] is out-of-date. Python has had the `match` statement [since 3.10](https://docs.python.org/3/reference/compound_stmts.html#the-match-statement).

Hmm? The section already does mention the `match` statement.

And note the already existing issue https://github.com/python/cpython/issues/111307

**Comment by terryjreedy** [comment]
My PR #115899 for #111307 is waiting for a review, even just a 'looks good'.  If no one does, I will merge as is after rechecking.

**Comment by terryjreedy** [comment]
My PR #115899 for #111307 has been merged.
