### ISSUE TITLE
Add support for Android as a target platform

### ISSUE THREAD

**Issue by mhsmith** [python/cpython#116622]
I am now working on [PEP 738](https://peps.python.org/pep-0738/), which proposes adding Android as a Tier 3 supported platform for Python 3.13. I'll use this page to track all the issues related to this work.

This was previously managed at #71052, but most of that issue's history is now irrelevant, so I'm opening a fresh one. 

Android-related issues which were open before the PEP 738 work began:

* https://github.com/python/cpython/issues/71042
* https://github.com/python/cpython/issues/76391
* https://github.com/python/cpython/issues/75824
* https://github.com/python/cpython/issues/83032
* https://github.com/python/cpython/issues/91028
* https://github.com/python/cpython/issues/111225

Issues added during the PEP 738 work:

* #114875
* #116057

PRs from the PEP 738 work which are not linked to one of these issues will be listed below.

FYI: @freakboy3742 @encukou

### Linked PRs
* https://github.com/python/cpython/pull/115576
* https://github.com/python/cpython/pull/115917
* https://github.com/python/cpython/pull/115918
* https://github.com/python/cpython/pull/115923
* https://github.com/python/cpython/pull/115955
* https://github.com/python/cpython/pull/116215
* https://github.com/python/cpython/pull/116379
* https://github.com/python/cpython/pull/116423
* https://github.com/python/cpython/pull/116426
* https://github.com/python/cpython/pull/116617
* https://github.com/python/cpython/pull/116618
* gh-116758
* gh-117299
* gh-117878
* gh-118063
* gh-118352
* gh-121595
* gh-122487
* gh-122490
* gh-122521
* gh-122522
* gh-122530
* gh-122539
* gh-122698
* gh-122719
* gh-122764
* gh-122842
* gh-123061
* gh-123981
* gh-123982
* gh-123988
* gh-124012
* gh-124015
* gh-124034
* gh-124035
* gh-124259
* gh-124395
* gh-124462
* gh-124516

**Comment by freakboy3742** [comment]
@mhsmith I think this ticket can now be closed - can you confirm?

**Comment by vstinner** [comment]
> @AA-Turner AA-Turner closed this as completed in python/peps#3982 Oct 7, 2024 

Congrats @mhsmith!
