### ISSUE TITLE
Latests release of asyncio (3.4.3) seems to have an outdated base_events.py using the reserved async keyword

### ISSUE THREAD

**Issue by adalfarus** [python/cpython#116649]
# Bug report

### Bug description:

The bug is rather strange, it only occurs when starting the tests outside of the environment I use for development.
You easily try by running the following commands:

py -3.12 -m pip install aplustools --upgrade
upype import aplustools; aplustools.install_all_dependencies()
py -3.12 -m pip cache purge
py -3.12 -m pip install asyncio --upgrade
run_apt_tests

Heres what that resulted in for me:
...
C:\Users\user_>py -3.12 -m pip cache purge
Files removed: 438

C:\Users\user_>py -3.12 -m pip install asyncio --upgrade
Collecting asyncio
  Downloading asyncio-3.4.3-py3-none-any.whl.metadata (1.7 kB)
Downloading asyncio-3.4.3-py3-none-any.whl (101 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 1.5 MB/s eta 0:00:00
Installing collected packages: asyncio
Successfully installed asyncio-3.4.3

C:\Users\user_>run_apt_tests
Ensuring pytest is installed...
C:\Users\user_\AppData\Local\Programs\Python\Python312\python.exe -m pip install pytest
Requirement already satisfied: pytest in c:\users\user_\appdata\local\programs\python\python312\lib\site-packages (7.4.4)
Requirement already satisfied: iniconfig in c:\users\user_\appdata\local\programs\python\python312\lib\site-packages (from pytest) (2.0.0)
Requirement already satisfied: packaging in c:\users\user_\appdata\local\programs\python\python312\lib\site-packages (from pytest) (23.2)
Requirement already satisfied: pluggy<2.0,>=0.12 in c:\users\user_\appdata\local\programs\python\python312\lib\site-packages (from pytest) (1.4.0)
Requirement already satisfied: colorama in c:\users\user_\appdata\local\programs\python\python312\lib\site-packages (from pytest) (0.4.6)
Clearing directory test_data...
Creating directory test_data...
Running tests...
================================================= test session starts =================================================
platform win32 -- Python 3.12.1, pytest-7.4.4, pluggy-1.4.0 -- C:\Users\user_\AppData\Local\Programs\Python\Python312\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\user_\AppData\Local\Programs\Python\Python312\Lib\site-packages\aplustools
plugins: anyio-4.2.0
collected 10 items / 2 errors

======================================================= ERRORS ========================================================
_________________________________________ ERROR collecting tests/test_data.py _________________________________________
..\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
..\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\..\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
..\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\test_data.py:1: in <module>
    from aplustools.data import database, imagetools, updaters, faker
data\imagetools.py:5: in <module>
    from aiohttp import ClientSession
..\aiohttp\__init__.py:6: in <module>
    from .client import (
..\aiohttp\client.py:3: in <module>
    import asyncio
..\asyncio\__init__.py:21: in <module>
    from .base_events import *
E     File "C:\Users\user_\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncio\base_events.py", line 296
E       future = tasks.async(future, loop=self)
E                      ^^^^^
E   SyntaxError: invalid syntax
_______________________________________ ERROR collecting tests/test_general.py ________________________________________
..\_pytest\python.py:617: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
..\_pytest\pathlib.py:567: in import_path
    importlib.import_module(module_name)
..\..\importlib\__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1387: in _gcd_import
    ???
<frozen importlib._bootstrap>:1360: in _find_and_load
    ???
<frozen importlib._bootstrap>:1331: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:935: in _load_unlocked
    ???
..\_pytest\assertion\rewrite.py:186: in exec_module
    exec(co, module.__dict__)
tests\test_general.py:2: in <module>
    from aplustools.web import web_request
web\web_request.py:8: in <module>
    import asyncio
..\asyncio\__init__.py:21: in <module>
    from .base_events import *
E     File "C:\Users\user_\AppData\Local\Programs\Python\Python312\Lib\site-packages\asyncio\base_events.py", line 296
E       future = tasks.async(future, loop=self)
E                      ^^^^^
E   SyntaxError: invalid syntax

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
You don't have to install `asyncio`, that library is included in the standard library.  The asyncio project on PyPI is, or rather was, only relevant for users of Python 3.3 (which didn't have asyncio as part of the stdlib).

**Comment by adalfarus** [comment]
I thought it was still on pypi so you can get new releases, I didn't do a full reinstall of python so that could actually be the case

**Comment by adalfarus** [comment]
Still, I think it would be better for pypi to not let a user with a python version over 3.3 to install it like other standard libraries.

**Comment by ronaldoussoren** [comment]
> I thought it was still on pypi so you can get new releases, I didn't do a full reinstall of python so that could actually be the case

The version in the stdlib is the latest release, the version on PyPI has not been updated since 2015.

> Still, I think it would be better for pypi to not let a user with a python version over 3.3 to install it like other standard libraries.

I'm not an asyncio expert myself, but I agree that we should consider removing the download on PyPI to avoid this confusion.  That could break stuff for legitimate users for the PyPI download though (anyone stuck on on Python 3.3).

**Comment by adalfarus** [comment]
> > I thought it was still on pypi so you can get new releases, I didn't do a full reinstall of python so that could actually be the case
> 
> The version in the stdlib is the latest release, the version on PyPI has not been updated since 2015.
> 
> > Still, I think it would be better for pypi to not let a user with a python version over 3.3 to install it like other standard libraries.
> 
> I'm not an asyncio expert myself, but I agree that we should consider removing the download on PyPI to avoid this confusion. That could break stuff for legitimate users for the PyPI download though (anyone stuck on on Python 3.3).

The best course of action would be to upload a new package to pypi that is minorly bigger (like v3.4.4). That has a restriction of python version 3.4 or more. This wouldn't break anything for legitimate users. The package should give an obvious warning or notice when being imported or installed so the users of newer versions know that it's now part of the standart library. It could also just link to the standart library.

**Comment by gvanrossum** [comment]
I have heard about this before. There are literally tons of projects that, through some cargo-culting, have asyncio in their requirements.txt file. Many of these on recent Python versions.

The thing is, unless you do something truly weird with your sys.path, the stdlib version of asyncio is preferred over the installed package, so this isn't harmful, and project maintainers don't review their requirements.txt file for unneeded packages. So if we remove the asyncio package from PyPI, all those projects will fail to install, causing havoc for them and their dependencies.

Even if we upload a new version that is restricted to Python 3.3, it will cause the installation to fail. 

So my conclusion is that we should leave this alone and just tell users to stop installing asyncio when they complain. I will close the issue as not planned.
