### ISSUE TITLE
`re` incorrectly matches '$' at '\n' even if re.MULTILINE not set

### ISSUE THREAD

**Issue by danny0838** [python/cpython#116659]
# Bug report

### Bug description:

```python
re.search(r'^abc$', 'abc\n')  # expect: None, actual: <re.Match object; span=(0, 3), match='abc'>
re.sub(r'^abc$', r'foo', 'abc\n')  # expect: 'abc\n', actual: 'foo\n'
```

more tests:
```python
re.search(r'^abc$', 'abc')  # as expect: <re.Match object; span=(0, 3), match='abc'>
re.search(r'^abc$', 'abc ')  # as expect: None
re.search(r'^abc$', 'abc\r')  # as expect: None
re.search(r'^abc$', 'abc\r\n')  # as expect: None
re.search(r'^abc$', 'abc\f')  # as expect: None
```

### CPython versions tested on:

3.8, 3.12

### Operating systems tested on:

Windows

**Comment by pochmann3** [comment]
No bug, works [as documented](https://docs.python.org/3/library/re.html#index-2). For help understanding such issues, please instead ask [at Discourse](https://discuss.python.org/c/users/7).

**Comment by pochmann3** [comment]
Though the doc could be improved. Currently it says:

> Matches the end of the string or just before the newline at the end of the string, and in MULTILINE mode also matches before a newline.

I'd end that with:

> also matches before any other newline.

**Comment by danny0838** [comment]
Thanks. Didn't notice such inconsistency among different flavors.
