### ISSUE TITLE
`inspect.getmember` docs do not mention `__type_params__` for functions and classes

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116782]
# Bug report

Docs do not mention `__type_params__` key returned value for classes and functions: https://github.com/python/cpython/blob/a18c9854e8c255981f07c0a1c1503253f85b7540/Doc/library/inspect.rst#L47-L58 https://github.com/python/cpython/blob/a18c9854e8c255981f07c0a1c1503253f85b7540/Doc/library/inspect.rst#L75-L109

But, they are returned:

```python
>>> class A[T]: ...
... 
>>> import inspect
>>> dict(inspect.getmembers(A))['__type_params__']
(T,)
```

I will send a PR for that.

### Linked PRs
* gh-116783
* gh-116870

**Comment by hugovk** [comment]
Triage: can this issue be closed?
