### ISSUE TITLE
Direct invocation of `test_inspect/test_inspect.py` fails

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116785]
# Bug report

```pytb
» ./python.exe Lib/test/test_inspect/test_inspect.py
/Users/sobolev/Desktop/cpython2/Lib/test/test_inspect/test_inspect.py:43: ImportWarning: can't resolve package from __spec__ or __package__, falling back on __name__ and __path__
  from . import inspect_fodder as mod
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/Lib/test/test_inspect/test_inspect.py", line 43, in <module>
    from . import inspect_fodder as mod
ImportError: attempted relative import with no known parent package                                                         
```

I will send a PR.

### Linked PRs
* gh-116787
* gh-116794
* gh-116795

**Comment by vstinner** [comment]
Should we really encourage usage of running directly tests?

Maybe it's time to give up on ``if __name__ == '__main__': ...`` and promote the new unittest CLI instead:

```
./python -m unittest Lib/test/test_inspect/test_inspect.py
```

But well, I'm fine with the fix.

cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
It was useful to make every toplevel test be runnable as a script. But it never worked well for tests in subdirectories and required too many inconvenient changes, so I gave up on this.

**Comment by vstinner** [comment]
I always run "./python -m test <test_name>". The only time when I really have to run a test manually if when everything goes wrong and I need a fully control on what's going on. Like when I'm debugging regrtest or unittest.

**Comment by vstinner** [comment]
I close the issue, it's now fixed :-)

**Comment by terryjreedy** [comment]
I routinely run tests I am editing from the editor.  Of course, idlelib tests have worked that way from the beginning because I developed or tested them that way from the beginning.
