### ISSUE TITLE
Not solved or closed properly (https://github.com/python/cpython/issues/116649)

### ISSUE THREAD

**Issue by adalfarus** [python/cpython#116730]
> I have heard about this before. There are literally tons of projects that, through some cargo-culting, have asyncio in their requirements.txt file. Many of these on recent Python versions.
> 
> The thing is, unless you do something truly weird with your sys.path, the stdlib version of asyncio is preferred over the installed package, so this isn't harmful, and project maintainers don't review their requirements.txt file for unneeded packages. So if we remove the asyncio package from PyPI, all those projects will fail to install, causing havoc for them and their dependencies.
> 
> Even if we upload a new version that is restricted to Python 3.3, it will cause the installation to fail. 
> 
> So my conclusion is that we should leave this alone and just tell users to stop installing asyncio when they complain. I will close the issue as not planned.

_Originally posted by @gvanrossum in https://github.com/python/cpython/issues/116649#issuecomment-1991887592_
            
My approach is easily done and completely solves this issue (by uploading a new release that is minorly bigger and restricting it to Python 3,4+).
The code for it should look something like this: 
```python
import sys
import importlib

# Temporarily remove the current directory from sys.path to avoid import loop
current_dir = sys.path.pop(0)

# Import the standard asyncio library
standard_asyncio = importlib.import_module('asyncio')

# Restore the original sys.path
sys.path.insert(0, current_dir)

# Update the globals with the standard asyncio module's contents
globals().update(standard_asyncio.__dict__)
```

**Comment by hugovk** [comment]
This looks more like a general comment than a bug report or enhancement request, and probably should have been posted on the original issue, but you may be better off opening a thread at https://discuss.python.org if you want to continue discussing.

We want to keep this issue tracker more focused, thanks.
