### ISSUE TITLE
BLD: not all @LIBPYTHON@ changed to @MODULE_LDFLAGS@

### ISSUE THREAD

**Issue by tacaswell** [python/cpython#116745]
# Bug report

### Bug description:

Attempting to build numpy fails with the errors that look like:

```
FAILED: numpy/_core/_struct_ufunc_tests.cpython-313-x86_64-linux-gnu.so
cc  -o numpy/_core/_struct_ufunc_tests.cpython-313-x86_64-linux-gnu.so numpy/_core/_struct_ufunc_tests.cpython-313-x86_64-linux-gnu.so.p/src_umath__struct_ufunc_tests.c.o -Wl,--as-needed -Wl,--allow-shlib-undefined -Wl,-O1 -shared -fPIC -Wl,--start-group -lm -Wl,--end-group -Wall -O2 -pipe -fomit-frame-pointer -fno-strict-aliasing -Wmaybe-uninitialized -Wdeprecated-declarations -Wimplicit-function-declaration -march=native -DCYTHON_FAST_THREAD_STATE=0 @LIBPYTHON@
/usr/bin/ld: cannot find @LIBPYTHON@: No such file or directory
```

I bisected this back to

https://github.com/python/cpython/pull/115780/

and found that there were still two instances of `@LIBPYTHON@` left in the repo.  I will open a PR shortly.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-116746

**Comment by befeleme** [comment]
This issue has caused a lot of build failures in Fedora Python packages.

**Comment by erlend-aasland** [comment]
Thanks for the report and the fix!

**Comment by eli-schwartz** [comment]
> Attempting to build numpy fails with the errors that look like:

This issue report is wrong, and the fix is wrong. The error shown here indicates that downstream projects are specifically looking up `sysconfig.get_config_var('LIBPYTHON')` by absolute name -- deleting it from the Makefile entirely, does *not* mean that the correct information is accessed.

In particular, for your use case you'll now start linking to libpython when you don't want to. :)

**Comment by mhsmith** [comment]
Thanks – I've created #122764 to rename the variable back to LIBPYTHON.

Also, it turns out there was one more instance that I missed: Misc/python-config.in.
