### ISSUE TITLE
Support for function composition using '|' pipe operator.

### ISSUE THREAD

**Issue by v1k22** [python/cpython#116744]
# Feature or enhancement

### Proposal:

# Function Composition with Pipe Operator Proposal

## Proposal
This feature proposal suggests adding support for function composition using the pipe `|` operator in Python. Function composition is a powerful concept that allows developers to chain functions together to create new functions, enhancing code readability and maintainability. Similar to haskell, if we can use `|` pipe, it will make more sense giving a pipeline kind of flow while reading. Here are the proposed haskell example followed by how it should look in python.

## Haskell Example
In Haskell, function composition is achieved using the `.` operator. Here's an example:

```haskell
addTwo :: Int -> Int
addTwo x = x + 2

multiplyByThree :: Int -> Int
multiplyByThree x = x * 3

-- Compose addTwo and multiplyByThree
composedFunction :: Int -> Int
composedFunction = multiplyByThree . addTwo

result = composedFunction 5 -- Result: (5 + 2) * 3 = 21
```

## Python Example
In python, function composition should be achieved using the `|` operator. Here's an example:

```python
# Define sample functions
add_two = lambda x: x + 2
multiply_by_three = lambda x: x * 3

# Compose functions using the | operator
f= add_two | multiply_by_three

result = f(5)  # Result: (5 + 2) * 3 = 21
```

### Benefits

- **Improved Readability:** Composing functions becomes more intuitive and visually clear.
- **Enhanced Maintainability:** Code becomes easier to understand and modify.
- **Functional Programming Style:** Aligns with principles of functional programming for those who prefer that paradigm.

### Next Steps

We welcome discussion on the feasibility and potential implementation details.
Alternative syntax suggestions are also open for consideration.

### Reference implementation in python
- This user has already implemented similar functionality [link](https://github.com/ForeverWintr/metafunctions) but I would love if python supports more stable way of build-in function composition

### Has this already been discussed elsewhere?

No response given

**Comment by gaogaotiantian** [comment]
I believe this is a HUGE change to Python and should be discussed in disclosure first. This might even require a PEP even if it's favored by users. Personally I have doubts - this might work with single argument functions, what about the ones that need multiple arguments? How do you know when to unpack the returned tuple (dict) and when not to?

```python
f = add_two | multiply_by_three
# It is just equivalent to
def f(x):
    return multiply_by_three(add_two(x))
```

It's basically a syntax sugar to avoid chained calls, which might not be that common as Python is not a functional programming language (at least not how most people use it).

I don't think this aligns with Python philosophy, but you are welcome to (and should) post it on disclosure and see how others feel about it.

**Comment by terryjreedy** [comment]
I am quite sure that this has been proposed, and rejected, likely on the python-ideas list.  I would also check the rejected PEPs list in PEP 0.  Anyway, we really mean the initial text in New Feature template, partly paraphrased above ;-).
