### ISSUE TITLE
The documentation for ctypes may be ambiguous.

### ISSUE THREAD

**Issue by jnchen** [python/cpython#116851]
# Documentation

![image](https://github.com/python/cpython/assets/7893787/c2b25146-2c99-4d7f-acef-92ca9c7fbe19)

In this picture, after "from ctypes import *" then use the "libc.printf" may misleading the reader that libc from ctypes.
i think should remove "from ctypes import *" then tell reader this snippet continue with the above code

### Linked PRs
* gh-116852
* gh-116905
* gh-116906

**Comment by hugovk** [comment]
Shall we follow the advice in the [FAQ](https://docs.python.org/3/faq/programming.html#what-are-the-best-practices-for-using-import-in-a-module) and replace the other `from ctypes import *` with specific imports?

**Comment by Privat33r-dev** [comment]
> Shall we follow the advice in the [FAQ](https://docs.python.org/3/faq/programming.html#what-are-the-best-practices-for-using-import-in-a-module) and replace the other `from ctypes import *` with specific imports?

Sounds like a good idea. The whole doc seem inconsistent with `import` statements, probably they should be rearranged as well.

**Comment by Privat33r-dev** [comment]
@jnchen Thanks for the issue and PR, you make a good point
