### ISSUE TITLE
pystats: optimized_trace_length histogram includes exits

### ISSUE THREAD

**Issue by mdboom** [python/cpython#116808]
# Bug report

### Bug description:

With the addition of cold exits, the "optimized trace length" histogram now includes [the exit count + the optimized trace length](https://github.com/python/cpython/blob/main/Python/optimizer.c#L880).

While this is a useful metric for the overall executor size, it's no longer useful to see the amount of instructions that the optimizer was able to remove from the hot path.

I would suppose we break this out into two stats: the optimized trace length and the exit count.

Does this make sense, @markshannon?

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-116827

**Comment by mdboom** [comment]
Additionally, this hides data since the histogram maxes out at 8,192 (MAX_TRACE_LENGTH), and trace_length + exit_counts is frequently over that.

**Comment by markshannon** [comment]
The trace length historgrams should show lengths in number of uops, ignoring exits.
It should be trivial to fix once https://github.com/python/cpython/pull/116813 is merged, as that tracks the length of trace through optimization.

**Comment by mdboom** [comment]
> It should be trivial to fix once https://github.com/python/cpython/pull/116813 is merged, as that tracks the length of trace through optimization.

Sure, I think it's also trivial to fix now (and restore to old behavior), by tracking these two things separately -- I mainly wanted to get your take on whether tracking them as a single number was intentional:

```c
allocate_executor() {
   ...
   int size = exit_count*sizeof(_PyExitData) + length*sizeof(_PyUOpInstruction);
   ...
}
```

But if it's easier merge-wise to do this following or as part of #116813, that also makes sense.

**Comment by hugovk** [comment]
Triage: the linked PR is merged, can this be closed?

**Comment by mdboom** [comment]
Yes, it can be closed.  Sorry this fell through the cracks.
