### ISSUE TITLE
Make `sys.settrace`, `sys.setprofile`, and `sys.monitoring` thread safe in `--disable-gil` builds

### ISSUE THREAD

**Issue by DinoV** [python/cpython#116818]
# Feature or enhancement

### Proposal:

These need to work properly when called with multiple threads running.

https://github.com/colesbury/nogil-3.12/commit/82800d8ec8

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

https://github.com/python/cpython/issues/108219

### Linked PRs
* gh-116775

**Comment by colesbury** [comment]
I think this is done
