### ISSUE TITLE
Mark some tests `test_cmd_line` as `cpython_only`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116858]
# Bug report

There are different tests that are skipped due to various reasons (like exact `--help` output matches or `malloc` usages, frozen imports, etc) on other implementations. For example, RustPython: https://github.com/RustPython/RustPython/blob/92c8b371ae5db0d95bd8199bc42b08af115bb88a/Lib/test/test_cmd_line.py

Take note that some skips look more like bugs / incomplete features in RustPython, however it is better to mark some tests that we can be sure as CPython-only.

I have a PR ready with the full description of each case.

### Linked PRs
* gh-116859
* gh-116889
* gh-116890

**Comment by Eclips4** [comment]
FYI, there's already a similiar meta issue: #115142
