### ISSUE TITLE
PathFinder.invalidate_caches should include MetadataPathFinder.invalidate_caches

### ISSUE THREAD

**Issue by jaraco** [python/cpython#116811]
`MetadataPathFinder.invalidate_caches` should be called from `PathFinder.invalidate_caches`, as that will match the behavior that would happen if MetadataPathFinder were on `sys.meta_path`.

_Originally posted by @jaraco in https://github.com/python/cpython/issues/116763#issuecomment-1997511772_
            

### Linked PRs
* gh-116812
* gh-116864
* gh-116865

**Comment by jaraco** [comment]
`PathFinder` already delegates its `find_distributions` to `MetadataPathFinder`, so it's probably best to delegate this function as well.

**Comment by hugovk** [comment]
Closing as the PRs have been merged and backported. Please let us know if there's still more to do. Thanks!
