### ISSUE TITLE
`test_parserhack` in `test_future` is outdated

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#116860]
# Bug report

This test is written for python2.6, which is long gone. It tests some implementation detail with is also long gone:

https://github.com/python/cpython/blob/2cf18a44303b6d84faa8ecffaecc427b53ae121e/Lib/test/test_future_stmt/test_future.py#L174-L192

We have new tests for `print` keyword in other modules:

https://github.com/python/cpython/blob/2cf18a44303b6d84faa8ecffaecc427b53ae121e/Lib/test/test_exceptions.py#L176-L183

I propose to remove this test, it does not add any value and might be confusing to readers.

### Linked PRs
* gh-116861
* gh-119648
* gh-119649

**Comment by serhiy-storchaka** [comment]
For reference, the tested code was dead since 3.1 (e3944a5e1ecf67aa722fd9ce0c0a4ee72ee5ba2d).
