### ISSUE TITLE
Error configuring with TSAN

### ISSUE THREAD

**Issue by pitrou** [python/cpython#116891]
# Bug report

### Bug description:

I'm trying to enable TSAN on a local build on Ubuntu 22.04 using the system clang, and I get this weird error:
```console
$ CC=clang CXX=clang++ ./configure --with-thread-sanitizer --with-pydebug --disable-ipv6
[...]
checking for acosh... no
configure: error: Python requires C99 compatible libm
```

Strangely, this is the same configuration (Ubuntu 22.04, system clang) that works on the Github Actions CI.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by pitrou** [comment]
@colesbury Did you encounter this already?

**Comment by pitrou** [comment]
Ah, I was missing the `libclang-rt-14-dev` package for compiler-rt. This is fixed now.

**Comment by diptorupd** [comment]
@pitrou can you please share some more detail on what you did to resolve the issue? I am facing the exact same issue when trying to compile cpython from source using `clang-18` with the address sanitizer. I did install `libclang-rt-18-dev`, but that does no seem to help.

My configure command looks like this:

`CC=clang-18 CXX=clang++-18 ../configure --with-pymalloc --with-assertions --with-address-sanitizer --with-undefined-behavior-sanitizer --with-memory-sanitizer --with-pydebug --disable-ipv6 -C`
