### ISSUE TITLE
Itertools recipes improvements

### ISSUE THREAD

**Issue by pochmann3** [python/cpython#116842]
# roundrobin

https://github.com/python/cpython/blob/5f52d20a93908196f74271db8437cc1ba7e1e262/Doc/library/itertools.rst?plain=1#L1570-L1571

That looks weird. Round-robin with a single iterable? And the ranges aren't iterated? I suspect this was intended:

```python
collections.Counter(roundrobin(*ranges)) == collections.Counter(chain(*ranges))
```

# unique_everseen

These could be lazier by yielding *first* (before updating `seen`):

https://github.com/python/cpython/blob/7bbb9b57e67057d5ca3b7e3a434527fb3fcf5a2b/Doc/library/itertools.rst?plain=1#L894-L895
https://github.com/python/cpython/blob/7bbb9b57e67057d5ca3b7e3a434527fb3fcf5a2b/Doc/library/itertools.rst?plain=1#L900-L901

The similar "roughly equivalent" code of [`cycle`](https://docs.python.org/3.13/library/itertools.html#itertools.cycle) and the `factor` recipe also yield as early as they can.

# iter_index

https://github.com/python/cpython/blob/7bbb9b57e67057d5ca3b7e3a434527fb3fcf5a2b/Doc/library/itertools.rst?plain=1#L1420

Not really subsequence searches but *substring* searches. For example, "fbr" is a subsequence of "foobar", but they don't search for that. See [Subsequence](https://en.wikipedia.org/wiki/Subsequence?wprov=sfla1) and [Substring](https://en.wikipedia.org/wiki/Substring?wprov=sfla1) at Wikipedia.

@rhettinger

### Linked PRs
* gh-116846
* gh-116847

**Comment by rhettinger** [comment]
Yes to the roundrobin test update.

No to changing unique_everseen. In general, I update the loop invariant first. This helps me avoid bugs.  Also, changing the order doesn't change the total amount of work. It just shifts work from when the first element is emitted to when the iterator stops.

Yes to changing the subsequence terminology in the comment. It is really pedantic but we might as well change it to "continuous subsequence".  The word "substring" isn't quite right because it also applies to *bytes* and the user defined types that implement continuous subsequence searches.

I'll make the edits a bit later when I get home.

Thanks for looking over the code. Nice to know that someone besides me reads it.

**Comment by pochmann3** [comment]
> update the loop invariant first

Should the [`cycle`](https://docs.python.org/3.13/library/itertools.html#itertools.cycle) code then likewise do `saved.append(element)` before `yield element`?
        
> changing the order doesn't change the total amount of work

Depends. If the user for example only requests the first three (like `take(3, unique_everseen(...))`), then you add an element to the set unnecessarily.

> "continuous subsequence"

"contiguous" seems more popular, [18.400 results](
https://www.google.com/search?q=%22contiguous+subsequence%22) vs [4.930](https://www.google.com/search?q=%22continuous+subsequence%22).

> The word "substring" isn't quite right because it also applies to _bytes_ and the user defined types that implement continuous subsequence searches

The comment only talks about "bytes and str". And `bytes` are also sometimes called bytestrings, even [in the Python docs](https://docs.python.org/3/search.html?q=bytestring) (and they're definitely [strings](https://en.wikipedia.org/wiki/String_%28computer_science%29?wprov=sfla1) in general computer science terminology).

> Thanks for looking over the code. Nice to know that someone besides me reads it.

I love itertools and have been reading/checking all changes for a long time :-). Btw do you get notified about comments on merged commits? I [made one](https://github.com/python/cpython/commit/babb22da5a25c18a2d203bf72ba35e7861ca60ee#r122310665) once and don't know whether you saw it (you did do the change a while later).

**Comment by rhettinger** [comment]
Okay.  Fixed.

**Comment by rhettinger** [comment]
@pochmann3 You may interested in the issues I recently filed in the more-itertools docs.  Minor implementation tweaks have more of a payoff there because people run that code instead of just reading it.
