### ISSUE TITLE
`twine upload` erroneously says: `Start filename for 'leo' with 'leo'`

### ISSUE THREAD

**Issue by edreamleo** [python/cpython#116887]
# Bug report

### Bug description:

The dist directory contains two files, created by `python -m build`, both of which start with "leo":
```console
leo-6.7.8-6-py3-none-any.whl
leo-6.7.8-6.tar.gz
```
The wheel uploads correctly, but twine complains about the .tar.gz file:
```console
python -m twine upload -r testpypi dist/*
Uploading distributions to https://test.pypi.org/legacy/
Uploading leo-6.7.8-6-py3-none-any.whl
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.1/15.1 MB • 00:06 • 2.5 MB/s
Uploading leo-6.7.8-6.tar.gz
100% ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB • 00:03 • 3.4 MB/s
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Start filename for 'leo' with 'leo'.
```
Does anyone have any advice?

build 1.1.1, twine 5.0.0, Python 3.12.0 on Windows 11.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
This is the issue tracker for Python itself, please report problems with twine at https://github.com/pypa/twine/ and retry with `--verbose` for the report.
