### ISSUE TITLE
buildbot "AMD64 Ubuntu NoGIL 3.x" failing intermittently

### ISSUE THREAD

**Issue by jaraco** [python/cpython#116863]
Confirmed - the [same builder](https://buildbot.python.org/all/#/builders/1225) succeeded on the subsequent build. This builder does appear to be flaky right now.

<img width="1433" alt="image" src="https://github.com/python/cpython/assets/308610/c26dfab6-cf86-4b55-bfaf-872ed0bc830e">

_Originally posted by @jaraco in https://github.com/python/cpython/issues/116812#issuecomment-1999649582_

**Comment by colesbury** [comment]
cc @itamaro

**Comment by itamaro** [comment]
I restarted the worker, and it appears to be less flaky over the past week. Closing this issue for now - please re-open if flakiness is observed again.
