### ISSUE TITLE
docs(easy): Document that heap types need to support garbage collection

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#116935]
# Documentation

In https://docs.python.org/3/c-api/typeobj.html#c.Py_TPFLAGS_HEAPTYPE, it does not mention that the heap type must support GC. However this is actually the case. The type itself needs to be visited by the GC because it forms a reference cycle with its own module object. We should document this.

### Linked PRs
* gh-118021
* gh-118092

**Comment by neonene** [comment]
I think this is true when a heap type is created by `PyType_From*()` with a module explicitly specified.  As to #116934, `thread_handle_type` in `_threadmodule.c` does not hold a module, so switching from `tp_alloc()` back to `PyObject_New()` at the object creation would also fix the refleaks when GC cannot be respected.

**Comment by savannahostrowski** [comment]
I'd be happy to open a PR to update the docs but wanted to make sure I understand the comment above. 

@neonene Are you suggesting that heap types wouldn't have this requirement if `PyObject_New()` was used, making this documentation update unnecessary? If so, is that a favourable or in progress change?
