### ISSUE TITLE
Combine `_CHECK_FUNCTION_EXACT_ARGS` and `_CHECK_STACK_SPACE` uops?

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#116976]
These two uops always happen as a pair, and they contain a bunch of duplicate work (`func = ...` and `code = ...`). The second one doesn't use any cache entries. So they can be combined, hopefully saving a little bit of JIT template size (the combined template only needs to extract `code` once). Both only contain `DEOPT_IF()` calls.

A possible argument against would be that eventually we'd want to change one or the other to use `EXIT_IF()`. (Or can those coexist in one uop?)

CC: @brandtbucher @markshannon 

### Linked PRs
* gh-116977

**Comment by gvanrossum** [comment]
Brandt looked at this briefly and it looks like the individual templates are ~125 and ~115 bytes, while the combined template is ~165 bytes, so a clear win.

**Comment by gvanrossum** [comment]
I imagine there might be another possible future downside though: `_CHECK_STACK_SPACE` uops have the potential of being eliminated when they're redundant. (We currently don't do that though.)

I'd really like @markshannon's opinion here.

**Comment by markshannon** [comment]
I'd rather keep them separate. Having the uops separate means that they can be optimized separately, and superinstructions will put them back together they are a common(ish) pair.
