### ISSUE TITLE
json decode error in case of trailing comma is misleading

### ISSUE THREAD

**Issue by bluppfisk** [python/cpython#116960]
# Documentation

https://github.com/python/cpython/blob/main/Lib/json/decoder.py#L164

At line 164 in **json/decoder.py**, the error message is  "Expecting property name enclosed in double quotes" misleading: this error will be raised when trying to parse for example the following JSON:

```
{
 "date": {
  "$ref": "#/components/schemas/Datetime",
}
}
```

The real error here is a trailing comma, or a missing expected property name. The wording gives the impression that the property name is enclosed improperly.

IMHO it should be re-worded to (in descending order of my preference):

"Missing property name or property name not enclosed in double quotes"
or
"Property name missing or not enclosed in double quotes"
or
"Expecting property name, enclosed in double quotes"

It might even add "did you leave a trailing comma?"

Happy to submit a PR.

### Linked PRs
* gh-116961

**Comment by serhiy-storchaka** [comment]
The error is "Illegal trailing comma before end of object" in main.

**Comment by bluppfisk** [comment]
> The error is "Illegal trailing comma before end of object" in main.

Indeed, I made my diagnosis too quickly on Python3.11. Appreciate the improvement!
