### ISSUE TITLE
Make `os.path` a real module

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#116998]
# Feature or enhancement

### Proposal:

Currently `os.path` is an alias for `posixpath` / `ntpath`:

```python
# os.py
if 'posix' in _names:
    import posixpath as path
elif 'nt' in _names:
    import ntpath as path
else:
    raise ImportError('no os specific module found')

sys.modules['os.path'] = path
```

It would be easier for static type checkers to detect it if it was a real module (like in typeshed):

```python
# os/__init__.py
from os import path
```

```python
# os/path.py
import sys

_names = sys.builtin_module_names
if 'posix' in _names:
    from posixpath import *
    from posixpath import __all__ as __all__
elif 'nt' in _names:
    from ntpath import *
    from ntpath import __all__ as __all__
else:
    raise ImportError('no os specific module found')
```

_Note: in the repository there are 78 occurrences of `os.py` so they would need to be updated appropriately._

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-116999

**Comment by ericvsmith** [comment]
This change would be visible to user code. I'm not sure what it could break, but no doubt it would break something. I suggest discussing this on https://discuss.python.org/c/ideas/6 first.

**Comment by nineteendo** [comment]
Could you elaborate on how it would be visible? Is it simply being able to check the implementation?

```python
import ntpath
import posixpath
from os import path

if path is ntpath:
    print("nt")
elif path is posixpath:
    print("posix")
else:
    print("unknown")

```

**Comment by ericvsmith** [comment]
My point is: I'm not sure. But surely someone could write some code to tell, and we'd need to evaluate this. As you say, it matters to static type checkers, so maybe it matters to other code? The correct way to discuss changes like this is on d.p.o., which I see you've done. Thanks!

If the consensus there is to go ahead, we can re-open this issue.
