### ISSUE TITLE
pystats: Add some stats about where _Py_uop_analyse_and_optimize bails out

### ISSUE THREAD

**Issue by mdboom** [python/cpython#116996]
# Feature or enhancement

### Proposal:

It would be useful to know the cases where the new optimizer can't optimize a trace.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-116997

**Comment by hugovk** [comment]
Triage: the linked PR is merged, can this be closed?

**Comment by mdboom** [comment]
Closing as complete.
