### ISSUE TITLE
Error of escaping % sign in logging

### ISSUE THREAD

**Issue by SVETIK-LION** [python/cpython#116994]
# Bug report

### Bug description:

In strings with formatting we need escaping for sign "%".
Example:
```python
log.error('Percent: %s%%.', '42' )
```
Displays:
```python
Percent: 42%.
```

But in ordinary strings we do should not escaping for sign "%".
Example:
```python
log.error('Macros %_test_macros.')
```
Displays:
```python
Macros %_test_macros.
```
If I escape for a ordinary string then I get a double % sign.
Example:
```python
log.error('Macros %%_test_macros.')
```
Displays:
```python
Macros %%_test_macros.
```
Expected behavior - single % sign, as in C language.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
The [documentation](https://docs.python.org/3/library/logging.html#logging.Logger.debug) says:

> No % formatting operation is performed on msg when no args are supplied.

So this is not a bug, it's a feature request.

However, this is not backward compatible and I don't think it's very beneficial. For users who are not even familiar with %-format, a string is a string. Converting `%%` to `%` in a pure string feels off to me.

**Comment by serhiy-storchaka** [comment]
I concur with @gaogaotiantian. It is not a bug, it is a feature, that no formatting operation is performed when no args are supplied. You can pass already formatted message without bothering to escape formatting characters.

Changing this behaviour would be considered a regression by users.
