### ISSUE TITLE
Sync with importlib_metadata for Python 3.13

### ISSUE THREAD

**Issue by jaraco** [python/cpython#117089]
This issue tracks incorporating updates from importlib_metadata into CPython for Python 3.13, including:

### Linked PRs
* gh-117092
* gh-117094

**Comment by jaraco** [comment]
As I started looking into what it would take to move the tests from `Lib/test/test_importlib` to `Lib/test/test_importlib/metadata`, I found that there are more instances of the `mod` module leaking across tests, so I'll need to deal with that too.

**Comment by hugovk** [comment]
Triage: I think this is ready to be closed.
