### ISSUE TITLE
test_posix: test_sched_setaffinity() fails on CentOS9

### ISSUE THREAD

**Issue by vstinner** [python/cpython#117061]
# Bug report

Example of AMD64 CentOS9 3.x failure: https://buildbot.python.org/all/#/builders/838/builds/5082

```
======================================================================
FAIL: test_sched_setaffinity (test.test_posix.PosixTester.test_sched_setaffinity)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-CentOS9-ppc64le/build/Lib/test/test_posix.py", line 1343, in test_sched_setaffinity
    self.assertRaises(OSError, posix.sched_setaffinity, 0, [])
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: OSError not raised by sched_setaffinity
```

### Linked PRs
* gh-117126
* gh-117137
* gh-117138

**Comment by serhiy-storchaka** [comment]
The test calls `sched_setaffinity()` with a clear CPU affinity mask.

From the [man page](https://linux.die.net/man/2/sched_setaffinity):
> EINVAL
>
> The affinity bit mask mask contains no processors that are currently physically on the system and permitted to the process according to any restrictions that may be imposed by the "[cpuset](https://linux.die.net/man/7/cpuset)" mechanism described in cpuset(7).

The operation should fail with EINVAL since the clear mask obviously does not contain any processors. Was something changed in a new kernel?

**Comment by vstinner** [comment]
IMO we should remove the test `self.assertRaises(OSError, posix.sched_setaffinity, 0, [])`. We have to test that Python pass the right values to the syscall, but not test all cases of the syscall. I don't know why Centos9 kernel behaves differently than my Fedora 39 kernel.

**Comment by serhiy-storchaka** [comment]
Well, I think that we should test that it does not raise other exceptions (TypeError, SystemError, etc).

**Comment by vstinner** [comment]
Ok, I will propose a change to expect either: OSError or <no exception>.
