### ISSUE TITLE
When a class constructor has a keyword argument with a collection as a default value, it is shared between class instances

### ISSUE THREAD

**Issue by alvinary** [python/cpython#117007]
# Bug report

### Bug description:

I run into something that looks like unintended behavior. I did not find any similar open or closed issues here on Github. I apologize in advance if this was already discussed somewhere else!

When defining a class like this, with an empty collection as default argument (using `list()` instead of []), all instances wind up sharing a reference to the same object.

```python
class BugInstance:
    def __init__(self, buggy_list=list()):
        self.buggy_list = buggy_list
```

This is what happens when two separate instances are created using the default value:

```
>>> first = BugInstance()
>>> second = BugInstance()
>>> first.buggy_list.append(1)
>>> second.buggy_list
[1]
```

The same thing happens with sets, and probably other collections (not sure about other sorts of default values).
I tested this on CPython 3.11, but I think I had the same issue in a laptop with 3.9.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by carljm** [comment]
Although this is a common gotcha for people new to Python, it is intended behavior, not a bug. It's an inevitable consequence of the way default arguments are evaluated (once, at function definition time.) It is documented at https://docs.python.org/3/tutorial/controlflow.html#default-argument-values

The usual workaround is to use `None` as the argument default and create the mutable container internal to the function if `None` is received.

**Comment by terryjreedy** [comment]
https://discuss.python.org/c/users/7 is a better place to ask about possible bugs and whether something is documented.  Answers there are more visible.

**Comment by alvinary** [comment]
Thanks a lot to both!
