### ISSUE TITLE
uuid returns None as a version instead of 4

### ISSUE THREAD

**Issue by amacal** [python/cpython#117063]
# Bug report

### Bug description:

The following code snippet shows that returned version is None, but version 4 is expected.

```python
import uuid
print(uuid.UUID("4d1f9a23-016a-4ebf-0a9e-d6bc0bc5ac8b").version)
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
`.version` is only defined for `RFC_4122` uuids:

https://github.com/python/cpython/blob/8182319de33a9519a2f243ac8c35a20ef82a4d2d/Lib/uuid.py#L356-L361

While this value is not:

```python
>>> uuid.UUID("4d1f9a23-016a-4ebf-0a9e-d6bc0bc5ac8b").variant
'reserved for NCS compatibility'
```

**Comment by amacal** [comment]
I see, so it looks like it works as expected, and my UUID is not supposed to have a version because a version makes sense only for the RFC 4122 variant, not the NCS variant, where we don't interpret it, right?

**Comment by ericvsmith** [comment]
Yes. That's also how it's documented: https://docs.python.org/3/library/uuid.html#uuid.UUID.version
