### ISSUE TITLE
importlib.resources.abc.Traversable.joinpath docs incomplete

### ISSUE THREAD

**Issue by encukou** [python/cpython#117074]
[`importlib.resources.abc.Traversable.joinpath`](https://docs.python.org/3.13/library/importlib.resources.abc.html#importlib.resources.abc.Traversable.joinpath) should mention that it can take multiple descendants.

The versionchanged note should mention that some providers might still not support this.

@jaraco, this was officially added in 3.11, right?

### Linked PRs
* gh-117113
* gh-117571

**Comment by jaraco** [comment]
> this was officially added in 3.11, right?

It looks like the protocol was updated in importlib_resources 5.7 and Python 3.11, but it wasn't until later (importlib_resources 5.11 and Python 3.12) that `MultiplexedPath` added that support (so namespace packages wouldn't have support until Python 3.12). But yes, generally speaking, what you've described is correct.
