### ISSUE TITLE
`urllib.parse.parse_qs` behaves differenly in Python 3.9.2 compared to Python 3.9.1

### ISSUE THREAD

**Issue by nandgator** [python/cpython#117109]
# Bug report

#### Code

```python
from urllib.parse import parse_qs
parse_qs("q=search');alert(document.domain);", strict_parsing=True)
```

#### Expected Behavior

```
ValueError: bad query field: 'alert(document.domain)'
```

#### Actual Behavior

Python versions `3.9.2` and above does NOT raise `ValueError` even when `strict_parsing` is set `True`.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Linux

### Additional Context 

> from https://github.com/python-validators/validators/issues/338#issuecomment-2011014740

**Comment by serhiy-storchaka** [comment]
See #87133. Treating ";" as a query separator by default created a security issue.

Use `separator='&;'` to reproduce the old behavior.

**Comment by yozachar** [comment]
Hey, thanks for the reply. People running Python >= 3.9.2 and < 3.10 are in kind of a fix then, aren't they?

Also multi-character `separator=` doesn't seem to replicate the earlier behavior.

```python
Python 3.11.8 (main, Feb 12 2024, 14:50:05) [GCC 13.2.1 20230801] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from urllib.parse import parse_qs
>>> parse_qs("q=search');alert(document.domain);", strict_parsing=True, separator='&;')
{'q': ["search');alert(document.domain);"]}
```

instead you've to specify `separator=';'`

```python
>>> parse_qs("q=search');alert(document.domain);", strict_parsing=True, separator=';')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/urllib/parse.py", line 718, in parse_qs
    pairs = parse_qsl(qs, keep_blank_values, strict_parsing,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/urllib/parse.py", line 780, in parse_qsl
    raise ValueError("bad query field: %r" % (name_value,))
ValueError: bad query field: 'alert(document.domain)'
```

Will a patch be backported?

**Comment by serhiy-storchaka** [comment]
Ah, right, multicharacter `separator` does not work, so it is impossible to restore the old behavior exactly.

Is it worth to add support of multicharacter `separator`? Should it be considered a new feature or a bug fix? I don't know. You are the first person in three years to report the problem. Note that even if we consider this a bug, the change can only be backported to version 3.11.

cc @orsenthil, @Fidget-Spinner, @vstinner, @AdamGold

**Comment by vstinner** [comment]
The behavior changed on purpose to fix a security issue: https://python-security.readthedocs.io/vuln/urllib-query-string-semicolon-separator.html

**Comment by vstinner** [comment]
`parse_qs("q=search');alert(document.domain);", strict_parsing=True)`

The *strict* behavior is requested, IMO rejecting Javascript sounds like the right behavior. What makes you think that Python should reply something else? What is your expected behavior?

**Comment by yozachar** [comment]
> The strict behavior is requested, IMO rejecting Javascript sounds like the right behavior. What makes you think that Python should reply something else? What is your expected behavior?

Rejecting JavaScript indeed. It does not do so from Python v3.9.2, but I see now that the `separator` parameter has been added to the same version even though the [docs](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.parse_qs) claim it has been added only in v3.10.

I'll be closing this issue now.
