### ISSUE TITLE
Set up tagged pointers in the evaluation stack

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#117139]
# Feature or enhancement

### Proposal:

This issue mostly mirrors Mark's original one at https://github.com/faster-cpython/ideas/issues/632.

As part of PEP 703, tagged pointers will help achieve deferred reference counting.

Tagged pointers will also help the default GIL builds in 3.14 and future with unboxed ints.

Here's the initial design (open for comments):

We change the evaluation stack from  `PyObject *` to `PyTaggedObject`. `PyTaggedObject` looks like this.
```
typedef union PyTaggedObject {
    PyObject *obj;
    uintptr_t bits;
} PyTaggedObject;
```

Note: I am limiting the tagged pointers to just the evaluation stack (this is up for debate as well). The main reason is to keep the change as minimally invasive as possible for 3.13 and not leak out any implementation details for now. For example, I don't want to support tagged pointers in C API functions. This may/will change in 3.14.

Thanks to the cases generator, we can then autogenerate all the proper accessors to said object. For example, a stack effect of `PyObject *` will generate the code `effect.obj`, while a stack effect of `PyTaggedObject` (the new default) will generate the code  `(PyObject *)(effect.bits & ~TAGS)` or something similar.

Unboxed ints will also help both free-threaded and non-free-threaded builds by reducing refcounting even more for simple arithmetic operations (and making integer operations native). However, I am aiming for deferred tags in 3.13, and anything else is a plus.

Further note: due to wanting to respect immediate finalizers, we are not deferring that many objects. So this may not be a win on default builds. On free-threaded builds, I see a slight (10%) speedup on fibonacci microbenchmarks. Will benchmark on the default bulid as well and see the results.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-117186
* gh-118330
* gh-118450
* gh-118573
* gh-121127
* gh-121134
* gh-121244
* gh-122318
* gh-122830
* gh-122831
* gh-122956

```[tasklist]
### Tasks
- [ ] https://github.com/python/cpython/issues/118926
- [ ] https://github.com/python/cpython/issues/118930
```

**Comment by gvanrossum** [comment]
So the mentions of unboxed ints are speculative and not part of the initial implementation, right?

And the tagged pointers just have their tag bit(s) removed when used in the "blob of C code" that's the instruction definition's body. For example,
```
        inst(STORE_FAST, (value --)) {
            SETLOCAL(oparg, value);
        }
```
would expand its body to
```c
            SETLOCAL(oparg, (PyObject *)(value.bits & ~TAGS));
```

How do pointers receive their tag bit? Does every stack push just "or in" the tag bit(s)?

I recall trying to do this manually (before we had the generator) and it was a lot of work -- the code generator should make this much simpler. It also was quite a bit slower -- have you thought about this?

My biggest question is **what does the tag bit mean**? Is there a specific section of PEP 703 I should read to learn more about this?

**Comment by gvanrossum** [comment]
Okay...

So from this definition
```c
#define PACK(obj) ((PyTaggedObject){.bits = (uintptr_t)obj | _Py_IsImmortal(obj)})
```
I gather that the tag bit is (by default) only set if the object is immortal. From your **Motivation** here (and also from the section on deferred refcounting in PEP 703) I take it that the tag bit would also be set for selected objects like functions and methods.

Mark's original issue describes variants of INCREF/DECREF to check for the tag bit; presumably these variants should only be used in the interpreter.

@Fidget-Spinner Good luck!

**Comment by markshannon** [comment]
One thing to note:

If we are going to use tagged ints, all plain "borrow" transformations will need to be removed, as it is impossible to borrow a `PyObject *` from a tagged int or vice-versa.
Ultimately, we will want to extend the API that takes stack references to avoid having the double conversion ref -> `PyObject *` -> ref when calling common API functions that take `PyObject *`.

In cases where it is known that the stack ref is not an int we could add `StackRefNotInt_ToObjectBorrow` and the reverse, so avoid the cost of two conversions.
