### ISSUE TITLE
Subclass of `typing.Any` cannot be instantiated with arguments

### ISSUE THREAD

**Issue by Azureblade3808** [python/cpython#117110]
# Bug report

### Bug description:

```python
from typing import Any

class C(Any):
    def __init__(self, v): ...

C(0)   # TypeError: object.__new__() takes exactly one argument (the type to instantiate)
```

The fix should be easy. Just replace --

```python
        return super().__new__(cls, *args, **kwargs)
```

with --

```python
        return super().__new__(cls)
```

in `typing.Any.__new__(...)`, as the superclass is `object` and its `__new__` doesn't accept additional arguments.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-117111
* gh-117357
* gh-117358

**Comment by Eclips4** [comment]
Hello!
From my point of view, `typing.Any` shouldn't be subclassable as `typing.Final` and others.
cc @AlexWaygood @JelleZijlstra @sobolevn

**Comment by SantiiRepair** [comment]
Hey, but when I do it, I get a `TypeError`

```python
if TYPE_CHECKING:
    from ebinexpy.source import Ebinex
else:
    Ebinex = Any
```

`
TypeError: Any cannot be instantiated
`

**Comment by sobolevn** [comment]
In runtime `Any` cannot be called, that's correct :)

**Comment by SantiiRepair** [comment]
> In runtime `Any` cannot be called, that's correct :)

ahhhhh got it
