### ISSUE TITLE
Convert _ctypes extension module to multi-phase init

### ISSUE THREAD

**Issue by neonene** [python/cpython#117142]
# Feature or enhancement

### Proposal:

This issue is available to keep track of PRs, following the heap type conversion completed at #114314.

### TODO:
- ~[ ]  Make `free_list` in `malloc_closure.c` per-module variables.~ [rejected](https://github.com/python/cpython/pull/117874#issuecomment-2096089529)
- [x]  Fix intentional memory leaks of `StgInfo` during a finalization: [comment](https://github.com/python/cpython/pull/117181#issuecomment-2029764312).
- [x]  Enable `Py_MOD_MULTIPLE_INTERPRETERS_SUPPORTED`(DONE): [comment](https://github.com/python/cpython/pull/117181#discussion_r1557516762).
FUTURE?: `Py_MOD_PER_INTERPRETER_GIL_SUPPORTED` after a compatible `PyGILState_Ensure()` is introduced, see also the links below.

### Links to documents:

* [**libffi: a foreign function interface library**](https://gensoft.pasteur.fr/docs/libffi/3.3/libffi.pdf)
* [**libffi - GitHub**](https://github.com/libffi/libffi)

### Links to previous discussion of this feature:

* #103092
* #114314
* **`PyGILState_Ensure()`** for sub-interpreters:
  * #59956
  * #55124
    * [`_ctypes` patch](https://bugs.python.org/file20417/gilstateinterp.patch) (2011)

### Linked PRs
* gh-117143
* gh-117181
* gh-117189
* gh-117544
* gh-117874
* gh-117875
* gh-118139
* gh-119424
* gh-119468
* gh-119991
* gh-120008

**Comment by neonene** [comment]
Could anyone add this open issue to [the base issue's todo](https://github.com/python/cpython/issues/103092#issue-1644462938) (`port _ctypes` branch) as a checked (finished) leaf?  Thanks.

**Comment by ericsnowcurrently** [comment]
@encukou, this is done now, right?

**Comment by encukou** [comment]
I'll wait for more green buildbots before merging the 3.13 backport. Then it'll be done :)

**Comment by neonene** [comment]
In my understanding of https://github.com/python/cpython/pull/117181#discussion_r1557516762, the `closure_fcn` function in `callbacks.c` needs a new compatible `PyGILState_Ensure()` faimily like https://github.com/python/cpython/issues/59956#issuecomment-1749163682 to enable `Py_MOD_PER_INTERPRETER_GIL_SUPPORTED`?

Issue #55124 in 2011 has an experimantal patch: https://bugs.python.org/file20417/gilstateinterp.patch

**Comment by encukou** [comment]
Also mmap-based closure allocation needs a mutex, and I don't know how thread-safe the libffi API is. There might be other things.

**Comment by ericsnowcurrently** [comment]
FYI, `PyGILState_Ensure()` should work fine with subinterpreters, as of 3.12.  It was necessary to fix that for per-interpreter GIL.

**Comment by ericsnowcurrently** [comment]
Regarding mmap and libffi, aren't those resolved for free-threading builds?
