### ISSUE TITLE
HTMLParser has trouble with " inside values of attributes

### ISSUE THREAD

**Issue by pauser0000001** [python/cpython#117154]
# Bug report

### Bug description:

If you try to parse an HTML that has XML with namespaces inside an input variable value, you get the wrong list of attributes for the input variable, as the value is slitted by the " inside the value.

```python
import 
class TestHTMLParser(HTMLParser):
    def handle_starttag(self, tag, attrs):
        print("attributtes of", tag, attrs)

parser = TestHTMLParser()

parser.feed("""<html><body><form method="POST" name="hiddenform" action="https://somewhere"><input type="hidden" name="xml" value="<t:rs xmlns:t="http://schema">something</t:rs>"></form></body></html>""")

```
_Current result_ of input:
attributtes of input [('type', 'hidden'), ('name', 'xml'), ('value', '<t:rs xmlns:t='), ('http:', None), ('schema"', None)]
_Expected result_ of input:
attributes of input [('type', 'hidden'), ('name', 'xml'), ('value', '**<t:rs xmlns:t="http://schema">something</t:rs>**')]

### CPython versions tested on:

3.11, 3.12, 3.13

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
The behaviour of HTMLParser appears to be consistent with browsers, in `value="<t:rs xmlns:t="http://schema">something</t:rs>"` the first quote in the value ends the attribute definitions, that is this is parsed as `value="<t:rs xmlns:t="` followed by other attributes.

Why do you think this should be parsed otherwise?

**Comment by pauser0000001** [comment]
I'm Sorry, the problem was in my previous step, decoding too much.
