### ISSUE TITLE
Something is wrong

### ISSUE THREAD

**Issue by RohitMugalya** [python/cpython#117193]
# Bug report

### Bug description:

```
class Parent:
    def __init__(self, *args, **kwargs):
        print(args, kwargs)


p = Parent()


class Child(p):
    pass


print(Child)
child = Child()
```

Am I screwing the way inheritance works? I was so curious what happens if I pass an object or something else other than a class, inside `Child(...)` then I understand something it works behind the scene was like `Child(ParentClassName)`. `type('Child', (ParentClassName,), {...: ..., ...})`
the behavior is getting things different when trying to pass something other than a class. It would be nice if it raises an Error so it never happens accidentally at any point of time something like this.
```
if isinstance(ParentClassName, type):
    ...
else:
    raise Error("Inheritance must be of classes not with an object")
```

I found this when I was practicing *OOP* if my consideration is wrong tell me whether it is intended behavior?

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by aisk** [comment]
Hi, I think lots of Python versions have the same behavior, so this should not be considered as a bug.

According to the [devguide](https://devguide.python.org/triage/issue-tracker/#reporting-an-issue), if you want to discuss ideas for possible changes to future Python versions, or need some help about Python, you can create a new thread on https://discuss.python.org/.

**Comment by JelleZijlstra** [comment]
You don't explain clearly what the supposed bug is, but we're unlikely to change such a basic part of the language. As @aisk noted, you're better off starting a thread on Discuss first (preferably in the "Help" section).
