### ISSUE TITLE
venv/bin/activate script does not work as expected on zsh

### ISSUE THREAD

**Issue by Forgo7ten** [python/cpython#117148]
# Bug report

### Bug description:

In a new python workspace, lines 40 to 45 of the generated activate script are as follows:
```bash
VIRTUAL_ENV="/Users/user/code/PycharmProjects/PyTest/venv"
export VIRTUAL_ENV

_OLD_VIRTUAL_PATH="$PATH"
PATH="$VIRTUAL_ENV/bin:$PATH"
export PATH
```
But this script does not work as expected in my pycharm terminal (also a zsh terminal). I checked the $PATH environment variable and found that it was not written to PATH.
I need to change it to look like the following code so that this script can work properly. The modified position is the last line shown in the above code, line 45 of the activate script (my environment). This works fine in my environment.
```bash
-  export PATH
+  export PATH="$VIRTUAL_ENV/bin:$PATH"
```

I found the [source code](https://github.com/python/cpython/blob/d3de3a251efe213155b8996effe235408536d0e0/Lib/venv/scripts/common/activate#L50) of what may be the activation script and need to modify 50 lines in it. Maybe it can work normally if you make the following modifications.
```bash
   _OLD_VIRTUAL_PATH="$PATH"
   PATH="$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH"
-  export PATH
+  export PATH="$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH"
```

This problem causes me to need to modify the script every time I create a virtual environment through the `python -m venv venv` command, or just use the `./venv/bin/python` command to run python instead of the `python` command. This problem only occurs on my macOS, in ubuntu I can use venv just fine.

Is this situation a problem with my device? Is it possible to fix it by following my suggestion? I'd be more than happy to submit a PR for this.😀

In addition, I'm sorry that I don't quite understand whether "CPython versions tested" refers to the python version. My python versions are 3.8.10 and 3.9.6, neither of which work properly.

### CPython versions tested on:

3.8, 3.9

### Operating systems tested on:

macOS

**Comment by brianschubert** [comment]
There does not appear to be anything in those lines that is incompatible with zsh. `export PATH` is a valid command in zsh (see [17 Shell Builtin Commands](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#Shell-Builtin-Commands)) and is consistent with long standing POSIX shell behavior.  And FWIW, this works fine on my system (zsh 5.8.1 x86_64-ubuntu-linux-gnu).

**Comment by Forgo7ten** [comment]
> There does not appear to be anything in those lines that is incompatible with zsh. `export PATH` is a valid command in zsh (see [17 Shell Builtin Commands](https://zsh.sourceforge.io/Doc/Release/Shell-Builtin-Commands.html#Shell-Builtin-Commands)) and is consistent with long standing POSIX shell behavior. And FWIW, this works fine on my system (zsh 5.8.1 x86_64-ubuntu-linux-gnu).

@brianschubert I'm just giving a comprehensive description of the environment in which I operate. It works fine on my ubuntu too😊. But it doesn't work in my macOS.
Maybe there is a difference between `export PATH` and `export PATH="$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH"`? All in all it worked fine after I made the above changes.

**Comment by ericvsmith** [comment]
@Forgo7ten : what versions of zsh are you using on macOS and Ubuntu?

**Comment by ronaldoussoren** [comment]
> 
> @brianschubert I'm just giving a comprehensive description of the environment in which I operate. It works fine on my ubuntu too😊. But it doesn't work in my macOS. Maybe there is a difference between `export PATH` and `export PATH="$VIRTUAL_ENV/__VENV_BIN_NAME__:$PATH"`? All in all it worked fine after I made the above changes.

FWIW, it works fine for my on macOS (current 14.4, but I haven't had problems like this on older macOS versions either). 

Could this error be due to zsh customisations (shell profiles and the like)?

**Comment by Forgo7ten** [comment]
@ericvsmith @ronaldoussoren 😀Thank you very much for your enthusiastic help. I checked the profile line by line and found that it was caused by pyenv-virtualenv. Sorry for taking up your time😥.
