### ISSUE TITLE
IMAP Select unexpected response

### ISSUE THREAD

**Issue by ecoutinho** [python/cpython#117152]
# Bug report

### Bug description:

While connecting to a Davmail server using getmail, I got the following error:

`SimpleIMAPSSLRetriever:xxx@xxx:993:
xxx: operation error (IMAP error (command: SELECT => unexpected response: b'*  1843 EXISTS'))`

Notice that there are two spaces in '*  1843', not one as it was expected.

To overcome this, I've edited **imaplib.py** on line 131:

`_Untagged_status = br'\* (?P<data>\d+) (?P<type>[A-Z-]+)( (?P<data2>.*))?'`

changed it to:

`_Untagged_status = br'\*[ ]+(?P<data>\d+) (?P<type>[A-Z-]+)( (?P<data2>.*))?'`

Of course one might also argue that there weren't supposed to be two spaces in there...

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
If I read RFC 3501 correct there must be exactly 1 space here, in particular:

[A note at the start of the grammar](https://datatracker.ietf.org/doc/html/rfc3501#section-9) says:

> Note: [ABNF] rules MUST be followed strictly; in
>  particular:
> 
> (1) Except as noted otherwise, all alphabetic characters
> are case-insensitive.  The use of upper or lower case
> characters to define token strings is for editorial clarity
> only.  Implementations MUST accept these strings in a
> case-insensitive fashion.
> 
> **(2) In all cases, SP refers to exactly one space.  It is
> NOT permitted to substitute TAB, insert additional spaces,
> or otherwise treat SP as being equivalent to LWSP.**
> 
> (3) The ASCII NUL character, %x00, MUST NOT be used at any
> time.

And the grammar for a response is:

      response-data   = "*" SP (resp-cond-state / resp-cond-bye /
                  mailbox-data / message-data / capability-data) CRLF

My reading of this is that there should be exactly one space after the asterix and the IMAP server is therefore buggy.

**Comment by ecoutinho** [comment]
Thanks Ronald, I had a feeling that would be the case. I've reported it to the Davmail project, with the RFC information you've provided. Feel free to close this issue if you feel it's not your place to support non-compliant IMAP responses.

**Comment by ericvsmith** [comment]
I’m going to close this. I think the days of [Postel’s Law](https://en.wikipedia.org/wiki/Robustness_principle) are behind us. But thanks for the report.

**Comment by ecoutinho** [comment]
I'd like to add these debug logs at the Davmail server:

`2024-03-22 17:09:29,935 DEBUG [ImapConnection-55410] davmail.exchange.FolderLoadThread  - Still loading INBOX (3064 messages)`
`2024-03-22 17:09:29,938 DEBUG [ImapConnection-55410] davmail  - >  3064 EXISTS`
`2024-03-22 17:09:29,938 DEBUG [ImapConnection-55410] davmail  - > * 3 RECENT`

Could the error result from a missing asterisk in the response? It's a server bug in any case :)
