### ISSUE TITLE
Redudant comparison

### ISSUE THREAD

**Issue by VoroninArtemii** [python/cpython#117161]
### Description
There is a redudant comparison in the `Modules/clinic/unicodedata.c.h`
https://github.com/python/cpython/blob/40d75c2b7f5c67e254d0a025e0f2e2c7ada7f69f/Modules/clinic/unicodedata.c.h#L245-L249
The variable `_return_value` ranges from 0 to 255. And that's why it is never equal to -1. 

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.
Author A. Voronin.

### CPython versions tested on:
3.12

**Comment by serhiy-storchaka** [comment]
Yes, this is a generated code. It is not worth to specialize the generator to get rid of this tiny harmless comparison.
