### ISSUE TITLE
Wrong formatting in the "What's new in Python 3.13" article, "Improved Modules" section.

### ISSUE THREAD

**Issue by wchistow** [python/cpython#117194]
There is a wrong formatting In the "What's new in Python 3.13" article, "Improved Modules" section: name of the `base64` module is written smaller than other modules' names. Everything becomes clear if you look at the [source code of the article markup](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.13.rst?plain=1#L286):

```rst
asyncio
-------

...

base64
---       # <--
```

It can be seen that the characters `-` under the word `base64` are too few: there should be a word length (6), and now 3. Therefore, you just need to add three more `-`.

I could have submit a pull request myself, but it's too long ;) so, can you do it?

### Linked PRs
* gh-117198

**Comment by terryjreedy** [comment]
Also, `base64` is not included in the sidebar listing.  I will fix.  (Did you mean 'too late'?)
