### ISSUE TITLE
collection.ChainMap.fromkeys argument 'value' has incorrect argument kind

### ISSUE THREAD

**Issue by s04lg934jkg** [python/cpython#117215]
# Bug report

### Bug description:

fromkeys method of collection.ChainMap has vararg argument kind. Description of 'fromkeys' method and redirection to dict.fromkeys implies that there should be single value (positional only or keyword-or-positional kind of argument). 

see https://github.com/python/cpython/blob/eebea7e515462b503632ada74923ec3246599c9c/Lib/collections/__init__.py#L1040
    @classmethod
    def fromkeys(cls, iterable, *args):
        'Create a ChainMap with a single dict created from the iterable.'
        return cls(dict.fromkeys(iterable, *args))

While passing value to ChainMap.fromkeys works correctly, it may confuse the reader of the code. Anyway, it is more cosmetic issue than a bug. Suggest to change to more clear.

    @classmethod
    def fromkeys(cls, iterable, value=None):
        'Create a ChainMap with a single dict created from the iterable.'
        return cls(dict.fromkeys(iterable, value))

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-117493

**Comment by serhiy-storchaka** [comment]
cc @rhettinger

**Comment by rhettinger** [comment]
This would be nice improvement.   Do you want to submit a PR or have me do it?

We want to match the `dict.fromkeys()` signature including the slash for positional only.

```
>>> help(dict.fromkeys)
Help on built-in function fromkeys:

fromkeys(iterable, value=None, /) method of builtins.type instance
    Create a new dictionary with keys from iterable and values set to value
```
