### ISSUE TITLE
Is it possible to remove the feature of auto-completing parentheses for a callable in REPL?

### ISSUE THREAD

**Issue by beavailable** [python/cpython#117282]
# Bug report

### Bug description:

Sometimes it's just annoying:
- When I type `sys.getsi` and press `tab` to complete for me, I get `sys.getsizeof(`, but now I forget the signature of this function, I'll type `alt+shift+I` to go to the beginning of the line (I'm using vi mode in bash), and type `help(` then type `alt+shift+A` to go to the  end of the line, then I need to delete the annoying `(` and type `)` to get help.

    Another way is to first delete the annoying `(` and type `)`, then go to the beginning and type `help(` to get help, but either way is so uncomfortable for me.
- When I just want to pass a function name to another function as an argument, the `(` is just redundant.

I know that it's a useful feature, but I don't think it's necessary, and considering its drawbacks, I'd rather remove this feature.
Of course it's just my opinion (but if it's removed I'd be happy) . Now I just need a way to disable it (an environment variable would be ok, I can submit a PR if needed), please consider.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
An extra environment variable for CPython is a big thing, I doubt if this feature justfies one. Yes sometimes the extra `(` is not what you want, but in this case, it's about the frequency - what's the percentage that the user actually needs it. The cost for need/do not have and do not need/have is the same - one extra keyboard type, so if the percentage that the user needs it is higher than 50%, we should keep this feature. In my opinion, most of the time, when the user types a function name, they want to call it.

Sure it's possible that the user wants to pass a function name, but it's also entirely normal for them to pass the return value of the function call. The proposal just makes the life easier for some cases, and harder for others. And to be honest, I don't see a huge difference here. It's not like when the completer guesses wrong, the user needs to rewrite the whole thing.

From the reason above, I personally do not support changing it, or adding an environment variable to control it.

**Comment by beavailable** [comment]
Sorry for choosing a wrong tag and thanks for correcting it.

> An extra environment variable for CPython is a big thing, I doubt if this feature justfies one. 

OK, I agree.

> so if the percentage that the user needs it is higher than 50%, we should keep this feature.

But I don't agree this.

In this case, I think that completing `(` or not is not just about one extra keyboard type.
For the former, if that's what I want, it's fine; but if that's not, I need to delete the `(`, how I feel about this is that I just go one step forward and then one step back, it's not a good experience, and I'd think that the completion engine is not so intelligent, because it does things wrong.
For the latter, if that's what I want, it's fine; if that's not, I just need to continue coding without any bad feelings.
So it's not just about delete or type `(`, it's also about user experience.

From my experience, I think removing this feature would be better (I'll change the title later) . Though I also want to hear more opinions, so why don't we keep this issue open and let more people express their opinions?

Additionally, I often use vim (with lsp plugin) to write python code, as far as I know, most of lsp plugins do not complete `(` for a callable.

**Comment by beavailable** [comment]
> For some modern completers (VSCode for example), we have the luxury to do "multi completion". That is, we can complete the function name first, then hit tab again for the parenthesis (with some nice UI hint).

I have an idea that we can implement this feature, when the user press tab, if the function name isn't complete, then complete the name, otherwise complete `(` or `()`.
If you could accept this, I'll send a PR later.

**Comment by gaogaotiantian** [comment]
> I have an idea that we can implement this feature, when the user press tab, if the function name isn't complete, then complete the name, otherwise complete `(` or `()`. If you could accept this, I'll send a PR later.

The concern for this is that we do not have the UI hint. If the user is already used to the feature, they might feel comfortable with it, but it's not super intuitive. In modern editors like VSCode, there will be a hint for "what the completion would be" and that's intuitive. I'm also hesitated about having the "multi completion" without proper UI hint. So maybe we should hear more from the crowd about their feelings. And if need to, you should propose this in Disclosure (discussion.python.org) and see how other people feel about the feature.

**Comment by vadmium** [comment]
There’s already issue #58987 open about this

**Comment by beavailable** [comment]
@vadmium Thanks for the information, I'll close this one.
