### ISSUE TITLE
Breakpoint disables warning: sys:1: RuntimeWarning: coroutine 'status_change_listener' was never awaited

### ISSUE THREAD

**Issue by DanielAtCosmicDNA** [python/cpython#117207]
# Bug report

### Bug description:

With Python 3.11.2 when running `pytest -s` in the following repository: https://github.com/CosmicDNA/pynacl-middleware-canonical-example/tree/5882d0b7dd2d8438880477edf4b75a1f1f67df64

The following warning is printed on the terminal:

```terminal
sys:1: RuntimeWarning: coroutine 'status_change_listener' was never awaited
```

Now if you uncomment [line 75](https://github.com/CosmicDNA/pynacl-middleware-canonical-example/blob/5882d0b7dd2d8438880477edf4b75a1f1f67df64/pynacl_middleware_canonical_example/manager.py#L75) and debug the code in VS Code with the following launch.json within .vscode folder, the warning goes away.:

```json
{
  "configurations": [
    {
        "name": "Python: Module",
        "type": "debugpy",
        "request": "launch",
        "module": "pytest",
        "args": ["-s"],
        "justMyCode": true
    }
  ]
}
```

With the breakpoint instruction VS Code stops at line 75 and after resumed, no warning is printed out.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
This seems like you called an async coroutine without `await`. So somewhere in your code, you probably did something equivalent to
```python
status_change_listener()
```

when you should do
```python
await status_change_listener()
```

Adding trace (debugger) to your code might hide the issue because it has extra reference to the coroutine. However, I don't believe this is a CPython bug. In order to report a bug, you need a *minimal* reproducible example - preferably one with no external dependencies.

This looks too much like a bug in your own code.

**Comment by DanielAtCosmicDNA** [comment]
> This seems like you called an async coroutine without `await`. So somewhere in your code, you probably did something equivalent to
> 
> ```python
> status_change_listener()
> ```
> 
> when you should do
> 
> ```python
> await status_change_listener()
> ```
> 
> Adding trace (debugger) to your code might hide the issue because it has extra reference to the coroutine. However, I don't believe this is a CPython bug. In order to report a bug, you need a _minimal_ reproducible example - preferably one with no external dependencies.
> 
> This looks too much like a bug in your own code.

I do not think the warning should simply go away with the placement of a breakpoint.

Thank you for your feedback, it would be very helpful if you could pinpoint where you think there might be a problem in my own code.

**Comment by DanielAtCosmicDNA** [comment]
> This seems like you called an async coroutine without `await`. So somewhere in your code, you probably did something equivalent to
> 
> ```python
> status_change_listener()
> ```
> 
> when you should do
> 
> ```python
> await status_change_listener()
> ```
> 
> Adding trace (debugger) to your code might hide the issue because it has extra reference to the coroutine. However, I don't believe this is a CPython bug. In order to report a bug, you need a _minimal_ reproducible example - preferably one with no external dependencies.
> 
> This looks too much like a bug in your own code.

Here is the definition of status_change_listener: https://github.com/CosmicDNA/pynacl-middleware-canonical-example/blob/5882d0b7dd2d8438880477edf4b75a1f1f67df64/test/test_server.py#L10

And it is awaited at https://github.com/CosmicDNA/pynacl-middleware-canonical-example/blob/5882d0b7dd2d8438880477edf4b75a1f1f67df64/pynacl_middleware_canonical_example/listens.py#L40

**Comment by serhiy-storchaka** [comment]
Either add `await` for `gather()` or remove `async` from `async def _notify_listeners`.

**Comment by DanielAtCosmicDNA** [comment]
> Either add `await` for `gather()` or remove `async` from `async def _notify_listeners`.

With `await gather`, the error output is lengthier:
```terminal
Task was destroyed but it is pending!
task: <Task pending name='Task-16' coro=<Listens._notify_listeners() running at /home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/pynacl_middleware_canonical_example/listens.py:40> wait_for=<_GatheringFuture pending cb=[Task.task_wakeup()]>>
sys:1: RuntimeWarning: coroutine 'status_change_listener' was never awaited
```

With removing async from `_notify_listeners` the output is even lengthier than the previous one:
```
=================================================== warnings summary ===================================================
test/test_server.py::test_middleware
  /home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/.venv/lib/python3.11/site-packages/_pytest/threadexception.py:77: PytestUnhandledThreadExceptionWarning: Exception in thread ServerThread
  
  Traceback (most recent call last):
    File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
      self.run()
    File "/usr/lib/python3.11/threading.py", line 975, in run
      self._target(*self._args, **self._kwargs)
    File "/home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/pynacl_middleware_canonical_example/websocket/server.py", line 174, in _start
      loop.run_until_complete(run_async())
    File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
      return future.result()
             ^^^^^^^^^^^^^^^
    File "/home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/pynacl_middleware_canonical_example/websocket/server.py", line 167, in run_async
      self.listened.status = ServerStatus.Running
      ^^^^^^^^^^^^^^^^^^^^
    File "/home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/pynacl_middleware_canonical_example/listens.py", line 26, in __set__
      obj._notify_listeners_task = create_task(obj._notify_listeners(value))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/asyncio/tasks.py", line 374, in create_task
      task = loop.create_task(coro)
             ^^^^^^^^^^^^^^^^^^^^^^
    File "/usr/lib/python3.11/asyncio/base_events.py", line 436, in create_task
      task = tasks.Task(coro, loop=self, name=name, context=context)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  TypeError: a coroutine was expected, got <_GatheringFuture pending>
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================================= 1 passed, 1 warning in 0.17s =============================================
Task was destroyed but it is pending!
task: <Task pending name='Task-5' coro=<TCPConnector._resolve_host() running at /home/daniel/Workspaces/CosmicDNA/Stenography/pynacl-middleware-canonical-example/.venv/lib/python3.11/site-packages/aiohttp/connector.py:825> cb=[shield.<locals>._inner_done_callback() at /usr/lib/python3.11/asyncio/tasks.py:881]>
sys:1: RuntimeWarning: coroutine 'TCPConnector._resolve_host' was never awaited
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0459909d90>
```

as opposed to simply:
```terminal
sys:1: RuntimeWarning: coroutine 'status_change_listener' was never awaited
```

**Comment by DanielAtCosmicDNA** [comment]
> This looks too much like a bug in your own code.

The evidence is increasingly pointing otherwise @gaogaotiantian.

**Comment by gaogaotiantian** [comment]
> The evidence is increasingly pointing otherwise @gaogaotiantian.

I disagree, this still looks like a bug in your code instead of CPython.

But, feel free to make a minimum reproducible example that
* do not rely on any third party code (pytest, aiohttp, debugger other than pdb)
* simple enough that we don't need to clone a full project (a piece of code that can be copy/paste)

That would be a strong evidence that points to CPython itself. Most of the time when you put together the MRE, you'll know what's going wrong.

**Comment by DanielAtCosmicDNA** [comment]
I am closing this request as I was able to solve the problem with switching the order at [file test_server.py lines 18 and 24](https://github.com/CosmicDNA/pynacl-middleware-canonical-example/commit/dbd1e51e021554b2e7a6ee5bda36b199bfd87c01#diff-f0675922fcf6f6d7dd440209d2aedefc9de24811c6f64754fd54ffa782154eb5). Still it would be nice to understand why debugging with VS code hides the warning to be ever shown. Thank you @gaogaotiantian for your insights that were instrumental in achieving a solution.
