### ISSUE TITLE
Callable.collections

### ISSUE THREAD

**Issue by QuantumVoid855** [python/cpython#117353]
# Bug report

### Version: python 3.10.8
lib\site-packages\pyreadline\py3k_compat.py
line 8
```python
return isinstance(x, collections.Callable)
```
uses collections.Callable
but collections.Callable has been moved to collections.abc.Callable
causing python.exe to send a error at the start then working as normal

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
https://pypi.org/project/pyreadline/ is a third-party project, which apparently is no longer under active development (https://github.com/pyreadline/pyreadline). As such, you probably should aim to find a replacement if you want to use it with newer versions of Python.

**Comment by ericvsmith** [comment]
pyreadline is not part of CPython, it's a third party package that looks like it's no longer developed.
