### ISSUE TITLE
isinstance(list[anything], type) returns False since Python 3.11

### ISSUE THREAD

**Issue by sapetnioc** [python/cpython#117316]
# Bug report

### Bug description:

Types with subclasses such as `list[...]` or `dict[...]` are not considered to be instance of `type` by `isinstance()` whereas standard types (`list`, `dict`, ...) are. This difference is surprising if we consider, for instance, that `list` is in the `__mro__` of `list[int]`. I suspect that this inconsistency is a bug.

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
This was a deliberate change made due to a large number of issues that the previous behaviour caused. See https://github.com/python/cpython/issues/89828. I don't think we'll be changing this behaviour again.
