### ISSUE TITLE
forkserver.set_forkserver_preload() silent preload import failures when sys.path is required

### ISSUE THREAD

**Issue by doublex** [python/cpython#117378]
# Bug report

### Bug description:

Bug in `def main()`: https://github.com/python/cpython/blob/main/Lib/multiprocessing/forkserver.py#L167

The param `sys_path` is ignored. Result: `ModuleNotFoundError` for preloaded modules.

a) Using `sys_path` fixes this issue
b) Maybe better remove "pass" and report and error to simplify problem solving

```python
    if preload:
        if '__main__' in preload and main_path is not None:
            process.current_process()._inheriting = True
            try:
                spawn.import_main_path(main_path)
            finally:
                del process.current_process()._inheriting
+        if sys_path:
+            sys.path = sys_path
        for modname in preload:
            try:
                __import__(modname)
            except ImportError:
-                pass
+                warnings.warn('forkserver: preloading module failed %s' % modname)
```

### CPython versions tested on:

3.12

### Linked PRs
* gh-126538
* gh-126632
* gh-126633
* gh-126634
* gh-126635
* gh-126652
* gh-126653
* gh-126668
* gh-126669

**Comment by gpshead** [comment]
Thanks! This is an ironic bug. It has been there from the start for the forkserver. I suspect in a lot of environments it just didn't matter as the default path or PYTHONPATH from the environment was correct. But I can easily imagine situations where this would defeat the purpose of preloading or even potentially cause subtle bugs based on "" vs the absolute path determined at parent multiprocessing import time being in that preload's sys.path.

**Comment by doublex** [comment]
@gpshead 
Thank you very much for your efforts!
