### ISSUE TITLE
Handle non-iterables for `ntpath.commonpath`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117335]
# Bug report

### Bug description:

```python
>>> import ntpath
>>> ntpath.commonpath(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen ntpath>", line 826, in commonpath
ValueError: commonpath() arg is an empty sequence
```

Expected: `TypeError: 'NoneType' object is not iterable` like for `posixpath.commonpath`.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-117336

**Comment by serhiy-storchaka** [comment]
For reference, `posixpath.commonpath()` was changed in #114709. I forget to check also the `ntpath` implementation. :man_facepalming:

**Comment by nineteendo** [comment]
Yeah, I saw when your test failed when I changed `posixpath.commonpath()`.
But don't feel too bad, it happens to the best of us.

**Comment by nineteendo** [comment]
Maybe we could create `test_os_path.py` for common tests between `ntpath` & `posixpath`?
That would've probably caught this earlier.

**Comment by serhiy-storchaka** [comment]
Common tests are already defined in `test_genericpath.CommonTest`.
