### ISSUE TITLE
re.Match.__getitem__ may support tuples and slices

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#117329]
# Feature or enhancement

### Proposal:

Indexing a Match object, i.e. `m[g]`, is equivalent to `m.group(g)`, where it can only take a single integer or string argument. I think it may be extended to support the following:
1. `m[a, b]` for `m.group(a, b)`, basically `m[g] == m.group(*g)` if `g` is a tuple. Maybe we can also make `m[()]` and `m[(a,)]` return a tuple as well to be different from `m.group()` and `m.group(a)` / `m[a]`
2. `m[start:stop:step]` for slicing the `(m.group(0), m.group(1), m.group(2), ...)` tuple
3. A combination of 1. and 2. For example, `m[0, 3:5, 'name']` could give `(m.group(0), m.group(3), m.group(4), m.group('name'))`, or `(m.group(0), (m.group(3), m.group(4)), m.group('name'))`. I am not sure which one is better.

I am glad to create a PR if this proposal becomes accepted.

### Has this already been discussed elsewhere?

No response given

**Comment by serhiy-storchaka** [comment]
They do not add much functionality. All this can be expressed in other ways, and the need for this rarely arises.

I prefer to not add complexity in the code which already too complex without need.

Your item 3 shows ambiguity of the proposed feature.

**Comment by ericvsmith** [comment]
I'm going to close this. @HarryLHW : If you want to pursue this, you should open a discussion at https://discuss.python.org/c/ideas/6. If the decision is made to move forward, this issue can be re-opened.
