### ISSUE TITLE
dis [docs]: LOAD_SUPER_ATTR should push NULL instead of None if the lowest bit is set

### ISSUE THREAD

**Issue by Christopher-Chianelli** [python/cpython#117339]
# Documentation

The docs for LOAD_SUPER_ATTR currently states

> The low bit of namei signals to attempt a method load, as with [LOAD_ATTR](https://docs.python.org/3/library/dis.html#opcode-LOAD_ATTR), which results in pushing None and the loaded method. When it is unset a single value is pushed to the stack.

However, LOAD_METHOD/LOAD_ATTR push NULL to the stack, not None:

LOAD_ATTR
> Otherwise, NULL and the object returned by the attribute lookup are pushed.

Additionally, the code for LOAD_SUPER_ATTR seems to push NULL instead of None too: https://github.com/python/cpython/blob/efcc96844e7c66fcd6c23ac2d557ca141614ce9a/Python/generated_cases.c.h#L4499-L4502

### Linked PRs
* gh-117343
* gh-117345

**Comment by Fidget-Spinner** [comment]
Good catch. Would you like to open a PR?

**Comment by Christopher-Chianelli** [comment]
sURE.
