### ISSUE TITLE
`test_compileall.EncodingTest` is broken

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#117389]
# Bug report

This test was added a long time ago as a part of https://github.com/python/cpython/commit/4b00307425bb3219f269a13ba5a9526903d21ce8

But, it is broken right now for several reasons:
1. It does not assert anything at all, so it passes when it really should not
2. It uses `print` keyword from Python2, which really results in

```pytb
======================================================================
FAIL: test_error (test.test_compileall.EncodingTest.test_error)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/Lib/test/test_compileall.py", line 516, in test_error
    self.assertEqual(buffer.getvalue(), '')
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 'Listing \'/var/folders/vw/n7c5l8m94zb072h[327 chars]\n\n' != ''
- Listing '/var/folders/vw/n7c5l8m94zb072h487pnlpzm0000gn/T/tmpeolpbxlq'...
- Compiling '/var/folders/vw/n7c5l8m94zb072h487pnlpzm0000gn/T/tmpeolpbxlq/_test.py'...
- ***   File "/var/folders/vw/n7c5l8m94zb072h487pnlpzm0000gn/T/tmpeolpbxlq/_test.py", line 2
-     print u"€"
-     ^^^^^^^^^^
- SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?
- 


----------------------------------------------------------------------
```

But, we cannot see this failure, because the result of `compile_all` is ignored. And `sys.stdout` is not checked as well.

I will send a PR with the fix.

### Linked PRs
* gh-117390
* gh-118603
* gh-118604

**Comment by terryjreedy** [comment]
How do you get the error?  What is the purpose of compileall if errors are ignored?  Test if no crashes?

**Comment by sobolevn** [comment]
@terryjreedy this is what happens when you change `print()` function to `print` keyword in my PR.
