### ISSUE TITLE
Improve `os`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117361]
# Feature or enhancement

### Proposal:

I currently have several issues & PRs for `os`, here's an overview:

- Issues:
  - [x] #117201
  - [X] #117335
  - [X] #117338
  - [x] #117349
  - [x] #117352
  - [x] #117381
  - [x] #117383
  - [x] #117394
  - [x] #117402
- PRs:
  - [x] #117334
  - [X] #117336
  - [X] #117340
  - [x] #117350
  - [x] #117362
  - [x] #117382
  - [x] #117395

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by erlend-aasland** [comment]
I suggest closing this ticket. There is no clear goal, and there are no actionable items. The remaining open issue can stand for itself.
