### ISSUE TITLE
`test_clinic` fails with the `--forever` argument

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#117347]
# Bug report

### Bug description:

```python
./python -m test -q test_clinic --forever
Using random seed: 2016588083
0:00:00 load avg: 16.10 Run tests sequentially
test test_clinic failed -- Traceback (most recent call last):
  File "/home/eclips4/CLionProjects/cpython/Lib/test/test_clinic.py", line 2675, in test_cli_converters
    self.assertTrue(out.endswith(finale), out)
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: False is not true :
Legacy converters:
    B C D L O S U Y Z Z#
    b c d f h i l p s s# s* u u# w* y y# y* z z# z*

Converters:
    bool(accept={<class 'object'>})
    byte(bitwise=False)
    char()
    Custom()
    defining_class(type=None)
    double()
    fildes()
    float()
    int(accept={<class 'int'>}, type=None)
    long()
    long_long()
    object(converter=None, type=None, subclass_of=None)
    Py_buffer(accept={<class 'clinic.buffer'>})
    Py_complex()
    Py_ssize_t(accept={<class 'int'>})
    Py_UNICODE(accept={<class 'str'>}, zeroes=False)
    PyByteArrayObject()
    PyBytesObject()
    self(type=None)
    short()
    size_t()
    slice_index(accept={<class 'NoneType'>, <class 'int'>})
    str(accept={<class 'str'>}, encoding=None, zeroes=False)
    unicode()
    unsigned_char(bitwise=False)
    unsigned_int(bitwise=False)
    unsigned_long(bitwise=False)
    unsigned_long_long(bitwise=False)
    unsigned_short(bitwise=False)

Return converters:
    bool()
    Custom()
    double()
    float()
    int()
    long()
    object()
    Py_ssize_t()
    size_t()
    unsigned_int()
    unsigned_long()

All converters also accept (c_default=None, py_default=None, annotation=None).
All return converters also accept (py_default=None).



== Tests result: FAILURE ==

1 test failed:
    test_clinic

Total duration: 586 ms
Total tests: run=290 failures=1
Total test files: run=2 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-117363
* gh-117365
* gh-117366

**Comment by Eclips4** [comment]
Probably related to 7aa89bc43e0bcf49eee5a39b5a7ba8f996f20d00

**Comment by erlend-aasland** [comment]
cc. @vstinner

**Comment by erlend-aasland** [comment]
> Probably related to [7aa89bc](https://github.com/python/cpython/commit/7aa89bc43e0bcf49eee5a39b5a7ba8f996f20d00)

I can confirm that reverting 7aa89bc43e0bcf49eee5a39b5a7ba8f996f20d00 resolves this issue.

**Comment by erlend-aasland** [comment]
The test is failing because the custom converter from `test_no_access_to_members_in_converter_init` lingers after the first run.

**Comment by erlend-aasland** [comment]
Actually, the custom converter is added in three different tests:

- `test_badly_formed_return_annotation`
- `test_no_access_to_members_in_converter_init`
- `test_external`

I'm unable to trigger the problem if I disable _all_ these tests using the `-i` test runner option.

**Comment by erlend-aasland** [comment]
Well, perhaps the test is too strict; perhaps we should loosen it even more.

**Comment by vstinner** [comment]
I wrote PR gh-117363 to fix side effects of previous tests.

**Comment by vstinner** [comment]
> I can confirm that reverting https://github.com/python/cpython/commit/7aa89bc43e0bcf49eee5a39b5a7ba8f996f20d00 resolves this issue.

Well, the old code didn't care of test side effects. The new code is affected by these side effects. My PR fix test side effects.

**Comment by Eclips4** [comment]
Thanks Victor for fixing this!
