### ISSUE TITLE
Confusing wording in `os.path.lexists` docs

### ISSUE THREAD

**Issue by pfortin** [python/cpython#117360]
os.path.lexists(path)    https://docs.python.org/3/library/os.path.html#os.path.lexists

    Return True if path refers to an existing path. Returns **True** for broken symbolic links. Equivalent to [exists()](https://docs.python.org/3/library/os.path.html#os.path.exists) on platforms lacking [os.lstat()](https://docs.python.org/3/library/os.html#os.lstat).

Should read **False**

### Linked PRs
* gh-117679
* gh-117701

**Comment by eryksun** [comment]
`os.path.lexists()` doesn't follow symlinks, so it returns `True` for a broken symlink. Use `os.path.exists()` if you need `False` for a broken symlink.

**Comment by pfortin** [comment]
But what is the purpose of a function that only returns True?

**Comment by eryksun** [comment]
`os.path.lexists()` returns `True` only if `path` exists, regardless of the file type. It's useful when one needs to know whether anything with the given name exists, regardless of whether it's a regular file, directory, symlink, named pipe/socket, or device.

**Comment by terryjreedy** [comment]
If the doc matches the behavior, there is no bug.  If the behavior is intended, and useful, we are unlikely to change it.  Feature changes usually need be be discussed on [discuss/ideas](https://discuss.python.org/c/ideas/6).

**Comment by zware** [comment]
As already explained, there's no bug in the docs or implementation here.  However, we might be able to clarify the docs a bit: I think the confusion here came from the fact that the broken symlink case is called out explicitly *in a separate sentence*:

https://github.com/python/cpython/blob/01bd74eadbc4ff839d39762fae6366f50c1e116e/Doc/library/os.path.rst?plain=1#L148-L149

This reads a bit clearer to me:

> Return ``True`` if *path* refers to an existing path, including broken symbolic links.

**Comment by erlend-aasland** [comment]
Resolved by:

- #117679 
- #117701 (auto-merge enabled)
