### ISSUE TITLE
Handle leading `//` for `posixpath.realpath`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117338]
# Bug report

### Bug description:

```python
>>> import posixpath
>>> posixpath.realpath("//foo")
'/foo'
```

Expected: `//foo` with precisely two leading slashes, see: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap04.html#tag_04_13

This can be quite easily solved using `posixpath.splitroot`, see the PR.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-117340

**Comment by barneygale** [comment]
`os.path.realpath()` resolves the path using _the current OS's rules_, which might be more specific than POSIX. Both my Linux and macOS machines resolve `//foo` to `/foo`. Are there any supported Python platforms where `//` isn't resolved to `/`?

**Comment by nineteendo** [comment]
I'm currently on my Windows laptop, so I can't check.
In any case, the old implementation can never return `//foo` because `path` is set to `os.sep`.
Is there a needs investigation label?

**Comment by barneygale** [comment]
There doesn't seem to be as a "needs investigation" label. 

Happy to leave this issue open for a bit while you further research a repro case, but if we can't find one, then I think this issue should be closed as "can't repro".

**Comment by nineteendo** [comment]
In any case, the current behaviour is undocumented:

>Join two paths, normalizing and eliminating any symbolic links encountered in the second path.

Normalizing doesn't touch the double slash & `//` is not a symlink.

**Comment by barneygale** [comment]
You're quoting a comment above the internal `_joinrealpath()` function.

Both the `posixpath.realpath()` docstring, and [the online docs](https://docs.python.org/3/library/os.path.html#os.path.realpath), describe it as returning a _canonical path_.

**Comment by nineteendo** [comment]
OK, but that comment doesn't _document_ this feature, which it probably should, in case this works correctly.

**Comment by bluss** [comment]
Why do you want to fix this, and could you describe in more detail how the changes relate to the specification you are pointing to? I don't see what in the specification requires this.

**Comment by nineteendo** [comment]
Yep, the old behaviour seems to be correct (cd doesn't resolve symlinks), in that case the feature should just be documented and tested.

- macOS:
    ![Screenshot 2024-03-29 at 09 04 52](https://github.com/python/cpython/assets/65588599/e8905c2d-d863-4f1c-a0ed-1f0ef5e346ab)
- Pydroid 3:
    ![image](https://github.com/python/cpython/assets/65588599/0c7e8a57-c472-4fd3-a67f-17228c2415ab)

**Comment by barneygale** [comment]
We don't need to document every detail of how `realpath()` is implemented.

**Comment by nineteendo** [comment]
I've added just one sentence in this pull request: #117350:

> Join two paths, normalizing and eliminating any symbolic links encountered in the second path. _Two leading slashes are replaced by a single slash._

Where should I add the test though? It doesn't really fit in with the rest of the changes.
