### ISSUE TITLE
Deprecate glob.glob0() and glob.glob1()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#117337]
Undocumented functions `glob0()` and `glob1()` were just helpers for `glob.iglob()`. They are not underscored because the `glob` module has `__all__`. They survived numerous refactorings only because they were used in the `msilib` module and some MSI related scripts. But the `msilib` module and these scripts have been removed.

`glob1(root_dir, pattern)` is equivalent to `iglob1(os.path.join(glob.escape(root_dir), pattern))`, but more restricted and slightly faster, because it does not need to escape `root_dir` and process the result.

Other alternative is `iglob(pattern, root_dir=root_dir)`, which can even be faster, but it emits paths relative to `root_dir`. You can use `(os.path.join(root_dir, p) for p in iglob(pattern, root_dir=root_dir))` if you need to append `root_dir`. Actually, creating an efficient replacement of `glob1()` was one of purposes of `root_dir`.

`glob0(root_dir, name)` just checks that `os.path.join(root_dir, name)` exists. I did not see its use in third-party code.

### Linked PRs
* gh-117371

**Comment by barneygale** [comment]
Two small corrections: the functions return results that are relative to *dirname* (i.e. they don't include *dirname* as a prefix), and the return value is a list (so they're more similar to `glob()` than `iglob()`).

```python
>>> glob.glob0('Doc', 'about.rst')
['about.rst']
>>> glob.glob1('Doc', '*.rst')
['copyright.rst', 'contents.rst', 'license.rst', 'about.rst', 'bugs.rst', 'README.rst', 'glossary.rst']
```

Both functions can be approximated by `glob.glob(pattern, root_dir=dirname)` I believe, without the need to escape or join *dirname*.
