### ISSUE TITLE
codecs.Stream{Reader,Writer} close parent stream on __exit__

### ISSUE THREAD

**Issue by zougloub** [python/cpython#117322]
# Bug report

### Bug description:

There's a lack of symmetry in codecs.StreamWriter/StreamReader where for some reason it closes the parent stream.

Here's an example that should work, but highlights the issue (the 2nd streamwriter creation is not necessary to instantiate a `ValueError: I/O operation on closed file.`).

```python
import io
import codecs
def test_stream_writer_bug():
	with io.BytesIO() as fo_:
		workaround = False
		if workaround:
			codecs.StreamWriter.__exit__ = lambda self, et, ev, tb: None
		codecinfo = codecs.lookup("utf-8")
		with codecinfo.streamwriter(fo_) as fo:
			fo.write("Mojibaké")
		codecinfo = codecs.lookup("iso8859-15")
		with codecinfo.streamwriter(fo_) as fo:
			fo.write("Mojibaké")
		assert fo_.getvalue() == b"Mojibak\xc3\xa9Mojibak\xe9"
```

### CPython versions tested on:

3.11,3.12

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
What is the lack of symmetry? Both StreamWriter and StreamReader close the parent stream.

**Comment by zougloub** [comment]
Sorry, I mean, if they're not opening the stream why are they closing them... can't the backing stream handle its closing using its own `__exit__` ?

**Comment by serhiy-storchaka** [comment]
I think that the reason is the same as for `TextIOWrapper` -- you wrap the binary file and get a Unicode file. You do not need to keep a separate reference to the binary file and explicitly close it.

`TextIOWrapper` has `detach()`. Something similar can be added for `codecs` streams. But they are different from `TextIOWrapper` in many other ways. What are the reasons to use them instead of `TextIOWrapper`?

cc @malemburg

**Comment by malemburg** [comment]
Both StreamReader and StreamWriter instances can be used as context managers and then expose the same __exit__ behavior as regular files, so no surprises there. This is intended. 

If you don't want the implicit close, simply don't use them as context managers and only wrap the underlying file using a context manager.

**Comment by zougloub** [comment]
For some context: in [this code](https://gitlab.com/exmakhina/ansicat/-/merge_requests/1/diffs#61734582d62e14a5b870a2193f55ca94fb252e33_0_42) I have implemented a StreamWriter which may keep pending data until all writes have completed. So I kind of wanted to use `__enter__/__exit__`. And this is how I discovered that the base class was closing the backing stream.

And I was surprised that the following seemingly innocuous looking code wouldn't work:
```python
import io
import codecs
def test_stream_writer_bug():
	with io.BytesIO() as fo_:
		codecinfo = codecs.lookup("utf-8")
		with codecinfo.streamwriter(fo_) as fo:
			fo.write("Mojibaké")
		fo_.write(b"!")
```
Perhaps why this is a default behavior should be documented.
