### ISSUE TITLE
Fix error message for `ntpath.commonpath`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117381]
# Bug report

### Bug description:

```python
>>> import ntpath
>>> ntpath.commonpath(["/foo", "foo"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen ntpath>", line 808, in commonpath
ValueError: Can't mix absolute and relative paths
```

`/foo` is not an absolute path, but a rooted path, which can't be mixed with not-rooted paths.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-117382

**Comment by aisk** [comment]
The `ntpath.isabs('/foo')` returns `True`, so I think it's an absolute path.

I did some googling and found that Microsoft has a document which describes "relative rooted path": https://learn.microsoft.com/en-us/dotnet/api/system.io.path.ispathrooted?view=net-8.0#remarks

> A relative rooted path specifies a drive, but its fully qualified path is resolved against the current directory.

So I think the relative rooted path should be something like `C:foo`, but `/foo` still is an absolute path.

**Comment by nineteendo** [comment]
That was recently changed:

- #113829

The error message could also be "Can't mix rooted paths and not-rooted paths" as `/foo` is rooted and `foo` is not.

**Comment by zooba** [comment]
How does this change make life better or easier for those encountering this message?

At first glance, it appears to be getting into overly precise terminology that doesn't help educate or correct the caller.

**Comment by nineteendo** [comment]
The error message states: "Can't mix absolute and relative paths".
But `/foo` & `foo` are both relative according to `ntpath.isabs()`:

Path     | Rooted? | Absolute?
-------- | ------- | ---------
`c:/foo` | Yes     | Yes
`c:foo`  | Yes     | No
`/foo`   | Yes     | No
`foo`    | No      | No

So, this error message is factually incorrect.
But `/foo` is rooted and `foo` is not, so that's what the new error message is in that case.
On a side note, it could be useful to add `os.path.isrooted`.
