### ISSUE TITLE
Question about bytecodes of operator "in" and "=="

### ISSUE THREAD

**Issue by RashawnXue** [python/cpython#117423]
# Bug report

### Bug description:

Here are two pieces of Python codes, let' s name them *code1* and *code2*:
- code1:
```python
a = ('p' in 'python') == True
```
- code2:
```python
a = 'p' in 'python' == True
```

Obviously and actually, the result of `a` in *code1* should be `True`.

According to the [operator precedence](https://docs.python.org/3/reference/expressions.html#operator-precedence), the precedence of operator `in` is equal to the precedence of `==` , so we can see that the expression `'p' in 'python' == True` is evaluated from left to right -- in the normal order, so the result of `a` in *code2* should be `True` as well.

However, when I tried to run `code2`, the actual result of `a` is `False`.

I tried to check the bytecode of the two codes using the command:
```sh
python3 -m dis code1.py
python3 -m dis code2.py
```
And the result is showed below:
- bytecode of code1:
```plain text
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 ('p')
              4 LOAD_CONST               1 ('python')
              6 CONTAINS_OP              0
              8 LOAD_CONST               2 (True)
             10 COMPARE_OP              40 (==)
             14 STORE_NAME               0 (a)
             16 RETURN_CONST             3 (None)
```
- bytecode of code2:
```plain text
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 ('p')
              4 LOAD_CONST               1 ('python')
              6 SWAP                     2
              8 COPY                     2
             10 CONTAINS_OP              0
             12 COPY                     1
             14 POP_JUMP_IF_FALSE        6 (to 28)
             16 POP_TOP
             18 LOAD_CONST               2 (True)
             20 COMPARE_OP              40 (==)
             24 STORE_NAME               0 (a)
             26 RETURN_CONST             3 (None)
        >>   28 SWAP                     2
             30 POP_TOP
             32 STORE_NAME               0 (a)
             34 RETURN_CONST             3 (None)
```

It seems that everything goes smoothly in *code1*. But in *code2*, the evaluation result `True` of expression `'p' in 'python'` was popped from top of the stack, left `'python'` which was copied at `8 COPY  2` in the stack. So what I actually get is the evaluation result of `'python' == True`, which corresponds to the evaluation result of *code2*.

I wonder whether it is a feature of Python or not. But I think it is very counterintuitive and may cost too much time to debug. Maybe we could have a better way to interpret the code in this situation?

Thank you! 

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
Yes, this is a expected behavior.
The code `'p' in 'python' == True` actually "transform" to this: `'p' in 'python' and 'python' == True`
This is a long standing behavior and change this would break old code.

**Comment by RashawnXue** [comment]
Got it! Thanks for your reply!
