### ISSUE TITLE
A loop split between two hot executors never calls CHECK_EVAL_BREAKER()

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#117442]
When a tight for loop without calls is turned into two traces that transfer directly to each other, it seems that `CHECK_EVAL_BREAKER()` is never called, and the loop won't be interruptible.

See https://github.com/faster-cpython/ideas/issues/669#issuecomment-2030810567, where @brandtbucher and I reasoned that this might occur in the _nbody_ benchmark (when the max trace length is reduced to 400).

While we didn't observe the predicted speedup, we really do believe that in this case the thread is uninterruptible.

@markshannon Any thoughts?

### Linked PRs
* gh-118482

**Comment by brandtbucher** [comment]
Probably we should insert a `_CHECK_PERIODIC` at the *beginning* of a trace starting with `JUMP_BACKWARD`, rather than checking signals in `_JUMP_TO_TOP`. That way we also wouldn't need to check signals in `ENTER_EXECUTOR`, `_JUMP_TO_TOP`, and wherever else is necessary to fix this issue.
