### ISSUE TITLE
Extract the instruction sequence data structure into its own file and add a Python interface

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#117494]
The Instruction Sequence data structure used by the compiler/assembler should be extracted into its own file, so that it can be properly abstracted. It should get a convenient Python interface so that it can be directly accessed from tests without translation to and from a list-of-tuples representation.

### Linked PRs
* gh-117496

**Comment by encukou** [comment]
Since the PR was merged, the wasm32-wasi Non-Debug 3.x buildbot has been consistently failing in `test_dynamic`.
I can't reproduce the failure locally using .devcontainer.

@ericsnowcurrently, can you reproduce?

**Comment by iritkatriel** [comment]
Is there something I needed to change in the makefiles for WASI when I added a new source file?
