### ISSUE TITLE
Skip `test_gdb.test_backtrace.test_threads` in free-threaded build

### ISSUE THREAD

**Issue by colesbury** [python/cpython#117474]
# Feature or enhancement

The `test_threads` test checks that `py-bt` reports when a thread is waiting on the GIL. In the free-threaded build, the GIL will typically be disabled. I think we should just skip the test in that case.

https://github.com/python/cpython/blob/027fa2eccf39ddccdf7b416d16601277a7112054/Lib/test/test_gdb/test_backtrace.py#L53-L83

### Linked PRs
* gh-117475

**Comment by nineteendo** [comment]
Must this be backported or can this be closed?

**Comment by erlend-aasland** [comment]
Free-threading is only (partially) implemented in 3.13, so there is no need to backport this. Thanks for the ping!
