### ISSUE TITLE
support Logger Asynchronous Handler

### ISSUE THREAD

**Issue by KimSoungRyoul** [python/cpython#117414]
# Feature or enhancement

### Proposal:

hi 

Is there any discussion about async logger handler ?

need to support official async logger handler
https://github.com/async-worker/aiologger

```python
class AsyncHandler(Handler):
       def __init__(self):
           super().__init__()
           self.lock = asyncio.Lock() # instead of threading.RLock()
      
      async def emit(self, record)
            raise NotImplementedError(..)
      
      async def handle(self, record):
            ...
     
      async def flush(self):
            ...

logger = logging.getLogger("root")

async_stream_handler = AsyncStreamHandler()
logger.addHandler(async_stream_handler)


async main():
     logger.info("i am log.....")
     ....


asyncio.run(main())
```

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
Thank you for your suggestion. You should first discuss this feature request at https://discuss.python.org/c/ideas/6. If it's accepted there, we can re-open this issue.
