### ISSUE TITLE
print of CR and automatic line wrapping

### ISSUE THREAD

**Issue by agowa** [python/cpython#117473]
# Bug report

### Bug description:

This probably has already been reported however I was not able to find a ticket for it.

The `\r` behaves strangely when the former print statement overflow. This is especially strange when one resizes the terminal, as then it will behave differently than to one that had an explicit `\n` as it'll re-wrap the line.

Because of the behavior with terminal resizes I'd like to request looking into the behavior of printing `\r` (again). Currently it only clears to the beginning of the visible line. However when the terminal gets resized it also moves back into the former line and thereby it clearly shows that the terminal (probably also cpython) know that the line was wrapped and could have cleared it properly...

```python
import sys

# A string that exactly fills the entire line in the terminal, depends on your terminal size.
# I.E. print(full_line) will fill a single line completely
full_line = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbcccccccccccddddddddzzzyyy'

def test(initial_line, updated_line):
  print(initial_line, end='')
  print('\r' + ' ' * len(initial_line) + '\r', end='')
  print(updated_line, end='')
  sys.stdout.flush()

# This one works as expected and only 'test' is visible afterwards.
test(full_line, 'test')

# This one doesn't, the output wraps and the test is at the beginning of the 2nd line and the 1st one is filled with full_line.
test(full_line + overflow, 'test')
# This basically shows up similarly to:
print(full_line)
print('test')
# However when we now resize the terminal we see that it is NOT the same as test(full_line + overflow, 'test') will flow back into the 1st line where as the 2nd one won't.
# This is probably because of explicit ./. implicit \n for the line wrapping.
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by joel6948** [comment]
may be try the curses package 

import curses

```
def main(stdscr):
    stdscr.clear()
    full_line = 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabbbbbbbbbbbbcccccccccccddddddddzzzyyy'
    overflow = 'overflow'  # Add overflow characters for testing

    # Function to clear line and update content
    def test(initial_line, updated_line):
        stdscr.addstr(initial_line)
        stdscr.clrtoeol()  # Clear from cursor to end of line
        stdscr.addstr(updated_line)
        stdscr.refresh()

    test(full_line, 'test')

    # You can continue testing with overflow similarly

    stdscr.getch()  # Wait for user input before exiting

curses.wrapper(main)

```
`sudo apt-get install python3-curses
`

**Comment by agowa** [comment]
Thanks, I know that there are libraries that work around this bug. However as I wasn't able to find anyone actually reporting it I wanted to make sure the root issue gets addressed at some point at least.

**Comment by zware** [comment]
I don't believe this issue really has anything to do with Python.  Try redirecting the output from your script to a file, then `cat` the file.  I believe you'll see the same result: all Python is doing here is writing to the `stdout` file descriptor and everything else is up to your particular terminal program.

**Comment by agowa** [comment]
The thing is cpython is responsible for the `print(updated_line, end='')`

All it boils down for me is that the overflowing line should be handled by python and not by a library. It's an engine bug as I see it.

The main issue is that the handling of what counts as a single line is different between an overflowing line and one with explicit `\n` ending.

And because it is different the `\r` should also account for this and work in a consistent way. Currently it doesn't.

**Comment by picnixz** [comment]
`print` is only responsible to write to a file descriptor. There is no notion of "maximum width" out there. It just writes characters (think of it as a thin wrapper around C fprintf()). 

A third-party library is better fitted for handling automatic line wrapping and would offer portable ANSI support as well. For instance `rich` has a way to automatically reflow the line length when the terminal size changes.

In addition, adding a utility function for such feature should be discussed on discourse first (this is non-trivial): https://discuss.python.org/c/ideas/6. However, I highly doubt that the standard library will ever include this.

Closing as `not planned`.

**Comment by agowa** [comment]
@picnixz This doesn't sound logical to me right now. If it was as simple as you make it out to be "is only responsible to write to a file descriptor" I'd expect the behavior to be equal in both cases but it isn't.

Anyway, just going to accept the "not planned" then. Still think it's quite strange to not handle within the engine itself though...

**Comment by picnixz** [comment]
> I'd expect the behavior to be equal in both cases but it isn't.

`fprintf` does not require the notion of a terminal. Line wrapping is a *visual* feature and is not controlled by Python. Again, `print` writes to `sys.stdout` and the terminal is responsible for rendering its content. Whether it decides to print a new line or not, reflow it after resizing the terminal, depends on your terminal emulator but not on Python or C. 

Think of `sys.stdout` as a file and `print` as `write`. A file is simply a sequence of characters, some are "newline"-like and others not. For Python and C, there is no concept of an "overflowing" line. This concept is only known for the terminal (because it knows how many characters it can render on your screen on a single line).

> Or are you suggesting that print('\033[?7l', end='') is the 'official solution' for this? 

I missed that one, but it's probably the universal solution. ANSI sequences are meant for controlling how characters are printed *on the terminal* itself in general (progression bars are implemented using ANSI sequences otherwise you wouldn't be able to write multiple logical lines on the same physical line).
