### ISSUE TITLE
Floating point rounding error bug in assertAlmostEqual

### ISSUE THREAD

**Issue by jm-willy** [python/cpython#117456]
# Bug report

### Bug description:

The minimal reproducible code is too long but can easily be seen on the python console (x + small difference) - (x) = floating-point rounding error >= small difference. The bug output is included as comments. Fails with values other than one. 
```python
class TestDict(unittest.TestCase):
# Test if each sum is almost equal to 1
   def test_amino_acid_usage_sums(self):
      for i in human_codon_usage_dict:
         usage_sum = 0
         for j in human_codon_usage_dict[i]:e
            usage_sum += human_codon_usage_dict[i][j]
         # floating-point rounding error
         # self.assertAlmostEqual(usage_sum, 1, places=None, msg='amino acid {}'.format(i), delta=0.01)
         # gives: AssertionError: 1.01 != 1 within 0.01 delta (0.010000000000000009 difference)
         # but works with the raised delta
         # self.assertAlmostEqual(usage_sum, 1, places=None, msg='amino acid {}'.format(i), delta=0.010000000000000009)
         # solution
         self.assertLessEqual(usage_sum, 1.01, msg='amino acid {}'.format(i))
         self.assertGreaterEqual(usage_sum, 0.99, msg='amino acid {}'.format(i))
         # doesn't fail
         self.assertLessEqual(usage_sum, 1+0.01, msg='amino acid {}'.format(i))
         self.assertGreaterEqual(usage_sum, 1-0.01, msg='amino acid {}'.format(i))
      return
```

```python
# Explanation

#Passes 50% of rounding errors
# Half the time fails, the rounding error of diff makes it slightly larger than delta. 
# The other half of the time, the rounding error of diff makes it slightly smaller than delta and passes. 
diff = abs(first - second)
diff <= delta

#Covers the other 50% of rounding errors
# Passes, second +- delta gives no rounding errors is second is int or larger than. 
# If it does, half of the time slightly expands the upper and/or lower bounds making it slightly easier to pass.
# The other half fails because the boundaries are narrower than expected.
upper_bound = second + delta
lower_bound = second - delta
first <= upper_bound
first >= lower_bound

# Both cover 100% of errors
```
## UPDATE
```
# The comparison operators are insensitive to rounding with larger numbers 75% the time:
>>> 10.010000000000000009<=10.01
True
>>> 10.009999999999990905<=10.01
True
>>> 10.010000000000000009>=10.01
True
>>> 10.009999999999990905>=10.01
False # this one would have passed the original
# but diff <= delta fails with smaller ones:
>>> 0.010000000000000009<=0.01
False

# in practice the fix works 100% 
# since the arithmetic to get the upper and lower bounds 
# does not give errors that narrow the bounds
# the original is stuck at 50%
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Linked PRs
* gh-117458

**Comment by gaogaotiantian** [comment]
Hmm, I don't think this is a bug. Floating point is not precise by definition - it can't represent any arbitrary value. This is a very common issue for all programming language. The fix may patch some cases but I don't believe it solved the issue for good. In my opinion the extra check for corner cases is a bit redundant for an assertion that is supposed to "not precise".

**Comment by jm-willy** [comment]
- If the extra check is redundant, the original can be removed, as my fix covers more cases.

- The assertion is not supposed to be not be precise. Almost equal == within range, which is very precise. Implemented either way, all operations(subtraction, comparison, addition) involved are supposed to be precise, distorted only by floating point arithmetic.

- Lesser precision means losing all use provided by the assertion, because the point is to test that a value is not greater or less than a specific limit. Or maybe do you mean to put deltas like this **delta=0.010000000000000009** in the code?

- Which more explicit check is available to test if a value is within a desired range? The one I did above

**Comment by serhiy-storchaka** [comment]
If you want to test that the value is within the specified range, you should use assertLess, assertLessEqual, assertGreater, and assertGreaterEqual, depending on whether the range is open or closed. See, there are 4 combinations of open/closed boundaries. And you should be very accurate in choosing the limits.

**Comment by serhiy-storchaka** [comment]
If you want to check that the number is in the specified range, `assertAlmostEqual` is not right tool. Its purpose is to check that two numbers are approximately equal. Since "approximate equality" is not well defined, it allows you to control how much difference is tolerable.

**Comment by JelleZijlstra** [comment]
I agree this is not a bug.

**Comment by jm-willy** [comment]
@JelleZijlstra How is code that throws unwanted errors not a bug, when there's mathematically and functionally equal code which doesn't?

**Comment by serhiy-storchaka** [comment]
The bug is in your code that uses `assertAlmostEqual()` incorrectly. You use `assertAlmostEqual(first, second, delta=delta)` as `assertTrue(first >= second - delta and first <= second + delta)` or `assertTrue(second >= first - delta and second <= first + delta)` (or maybe `assertTrue(second <= first + delta and first <= second + delta)` or `assertTrue(first >= second - delta and second => first - delta)`?), but all these cases are not equivalent due to floating point errors. If you need a specific behavior which is different from the documented behavior in corner cases, write your conditions explicitly, and do not use `assertAlmostEqual()`.
