### ISSUE TITLE
Newest 3.12 install missing python312.dll - Windows 10

### ISSUE THREAD

**Issue by Wpinson** [python/cpython#117433]
# Bug report

### Bug description:

During installation, I get a "missing python312.dll" error, which has an instruction to reinstall.  Reinstalling using the Repair choice results in the same error.  If I try to uninstall, it fails, and a complete cleaning of the registry is required to reinstall, which results in the same thing.  If I go ahead and ignore the error (running the repair install results in a dialog saying the repair was successful, despite the dll error), then if I try to run Python, I still get an error:
[Python error.pdf](https://github.com/python/cpython/files/14828374/Python.error.pdf)

Note:  the installation is with the "custom" choice, selecting all install elements, and selecting all users, which installs the program at C:\program files\Python312.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
What installer did you run?  One from python.org (which?) or something else?  I and likely 1000s of others have installed each python.org installer on Win10 without issue.  Did you re-download?

**Comment by Wpinson** [comment]
Forgot to answer the other question - downloads were from the Python.org website.

**Comment by zooba** [comment]
Interesting. It looks like the 3.12.2 installs all succeeded, whether per-user or all users (notably, the pip step also succeeded, which relies on the copy of Python just installed).

I wonder whether you've got a partial install of an earlier 3.12 version? Did you navigate to the new install and double click on the new python.exe directly to see if you get the same error? And maybe see if files are actually missing.

If you're opening through the shortcut, you should be able to right-click it to open properties (might have to "Open file location" first and then get properties on the shortcut) to see exactly where it's pointing.

**Comment by Wpinson** [comment]
I downloaded 3.12.2 through the yellow "Download Python 3.12.2" button on the main Download page where it says "Download the latest version for Windows".  The download is the executable python-3.12.2-amd64.exe.  From my downloads folder, I right-clicked and selected "Run as administrator".

I think I also tried downloading it from the list under "Looking for a specific release?", clicking the download button to the right of 3.12.2, though not sure.  I downloaded at least 3 different times, and I think one of those times was from that list.

**Comment by zooba** [comment]
I mean the installed python.exe. The installer seems fine, but I'm not sure which one you're actually running on your machine when you get the error.

**Comment by Wpinson** [comment]
I got the error during install as well as when I tried to run Python.exe after install.  I checked the Python312 folders and also the Windows dll folder, and could not find python312.dll.  I checked several folders within python312, and also ran a file explorer search, in case the installer was just putting the dll file in the wrong place.  The search came up empty - no python312.dll existed on drive C.

After installing the 3.12.0, which worked, I now can see python312.dll (dated 10/2/23 1:27pm, if that matters), in the root of c:\program files\python312.

So it seems as if the dll file in question is missing from the 3.12.2 installer.

**Comment by Wpinson** [comment]
My apologies, but I can't spend any more time on this.  I am up and running with 3.12.0, and that will let me move forward with my project.

Regarding the antivirus program, I didn't change that between installing 3.12.2 and 3.12.0.  The newer one didn't work but the older one did.  So whatever is different between the two installers is probably the root cause.

If it helps, the antivirus loaded on my laptop is Trend Micro.  The machine itself is a Boxx "GoBoxx" G2180, loaded with Microsoft Windows 10 Pro Version 10.0.19045.

**Comment by zooba** [comment]
Okay, well, if you're done then there's nothing more we can do on this.

The difference between the two is every single fix that's been merged into 3.12 since its original release. Any of those could cause a virus scanner to decide that it looks like malicious code and delete it, though most scanners do provide notice that they've done it (not all - this wouldn't be the first time we've seen the behaviour).

If someone else encounters the same issues and can try some more things, we can reopen.

**Comment by zooba** [comment]
@Domigome Do you have logs? And can you open Powershell and run `Get-Package *Python*` and copy the results here?

**Comment by LucHyg** [comment]
I have also run into the same issue, been using various versions of python on my work machine for 7+ years, rolled back to a previous version and its running fine now.
