### ISSUE TITLE
Bug in ChainMap if one of the items is empty defaultdict

### ISSUE THREAD

**Issue by erastogi** [python/cpython#117576]
# Bug report

### Bug description:

```python
from collections import defaultdict, ChainMap
a = ChainMap({1: {2: "a"}}, defaultdict(dict), {3: {4 : "b"}})
print(dict(a))
# Output: {3: {}, 1: {2: 'a'}}
# Expected Output: {3: {4: 'b'}, 1: {2: 'a'}}
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by pochmann3** [comment]
You're not using `ChainMap` and there is no output...

**Comment by rhettinger** [comment]
I'm think the example was meant to look something like this:

```
>>> a = ChainMap({1: {2: "a"}}, defaultdict(dict), {3: {4 : "b"}})
>>> a[3]
{}
>>> a
ChainMap({1: {2: 'a'}}, defaultdict(<class 'dict'>, {3: {}}), {3: {4: 'b'}})
```

If that is the case, then this isn't a bug.  A defaultdict always shadows downstream mappings because is was specifically designed to always return some value whether or not a key is present.

**Comment by erastogi** [comment]
Thanks for clarifying. When I was converting ChainMap to dict, it was overriding the latest value for key 3.

**Comment by ericvsmith** [comment]
Since this doesn't seem to be a bug, I'm going to close this.
