### ISSUE TITLE
unicodedata: unicodedata.name() undocumented TypeError on empty string

### ISSUE THREAD

**Issue by wesinator** [python/cpython#117557]
# Bug report

### Bug description:

Consider the following:
```python
import unicodedata
unicodedata.name('')

unicodedata.name('a')

unicodedata.name('\x00')
```

```
Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    unicodedata.name('')
TypeError: name() argument 1 must be a unicode character, not str

'LATIN SMALL LETTER A'

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    unicodedata.name('\x00')
ValueError: no such name
```

It seems there are two issues here:
1. unicodedata.name() and possibly other `unicodedata` methods can have an undocumented TypeError exception. https://docs.python.org/3/library/unicodedata.html
2. The `TypeError` on an empty string doesn't really seem accurate, since the function can still take other string values of the same `str` type.

Either `TypeError` should be mentioned in documentation, or the handling of empty strings should be fixed in the library to return a `ValueError` instead.

[NO_TRAIN]::

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows, Other

### Linked PRs
* gh-117558
* gh-117631

**Comment by ronaldoussoren** [comment]
This appears to be an argument clinic issue, in particular the handling of `int(accept={str})`, which ends up in this part of argument clinic:

https://github.com/python/cpython/blob/0edde64a41c2c3eeb4fd495efe7fff3d631cae4b/Tools/clinic/libclinic/converters.py#L268-L282

This ends up with the same general error format for invalid types (`unicodedata.name(42.5)`) and for strings with an unexpected length like here (both empty strings and strings longer than one code point).

**Comment by erlend-aasland** [comment]
cc. @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Historically, it happened that in some cases character and string are treated as different types, even if technically characters are implemented as strings with length 1 in Python. It is not an Argument Clinic issue, `PyArg_Parse*` functions do the same, and maybe some handwritten parsers too.

It is a very old behavior, and I do not think that changing TypeError to ValueError is well justified here. It will break user code for sure. From semantic point of view, passing a non-1-character string is usually a programming error instead of a data driven error, and TypeError is more suitable for this.

**Comment by serhiy-storchaka** [comment]
Example of such behavior besides Argument Clinic and the `PyArg_Parse*` C API:
```
>>> 'abc'.center(10, '')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    'abc'.center(10, '')
    ~~~~~~~~~~~~^^^^^^^^
TypeError: The fill character must be exactly one character long
```

**Comment by erlend-aasland** [comment]
We could align Argument Clinic to match the error message of `PyArg_Parse`.

**Comment by serhiy-storchaka** [comment]
Other examples:
```pycon
>>> ord('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    ord('')
    ~~~^^^^
TypeError: ord() expected a character, but string of length 0 found
>>> '%c' % ''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    '%c' % ''
    ~~~~~^~~~
TypeError: %c requires int or char
>>> b'%c' % b''
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    b'%c' % b''
    ~~~~~~^~~~~
TypeError: %c requires an integer in range(256) or a single byte
```

**Comment by erlend-aasland** [comment]
In any case, the error message can be improved, so I think it is still an Argument Clinic issue.

**Comment by serhiy-storchaka** [comment]
If the code of the Argument Clinic converter looks weird to you, it is because it was aligned to match PyArg_Parse.

**Comment by erlend-aasland** [comment]
> Example of such behavior besides Argument Clinic and the `PyArg_Parse*` C API:
> 
> ```
> >>> 'abc'.center(10, '')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>     'abc'.center(10, '')
>     ~~~~~~~~~~~~^^^^^^^^
> TypeError: The fill character must be exactly one character long
> ```

Actually, this error message does not come from `PyArg_Parse*`, it comes from a custom Argument Clinic converter in `Objects/unicodeobject.c`. Perhaps we should consider embedding that converter in Argument Clinic for better reuse.

**Comment by serhiy-storchaka** [comment]
Yes, it is what I said. These examples do not use `PyArg_Parse*` or standard Argument Clinic converter.

**Comment by serhiy-storchaka** [comment]
As for the error message, I think the "a unicode character" part is fine, but "not str" may be confusing, because "a unicode character" is a string. If it was "not a string of length 2" or "not an empty string", it would be much more clear.

**Comment by erlend-aasland** [comment]
Yes, this is the issue ;)

**Comment by serhiy-storchaka** [comment]
If you agree, are you interesting to implement such change (adding the length instead of the type in the error message)? It requires slightly more complex changes than what you did in your PR. I could easily do it myself, but you've already gotten into this and I don't want to waste your efforts.

**Comment by erlend-aasland** [comment]
> If you agree, are you interesting to implement such change (adding the length instead of the type in the error message)? It requires slightly more complex changes than what you did in your PR. I could easily do it myself, but you've already gotten into this and I don't want to waste your efforts.

Yep, I agree we should do that. I don't have time for it the following days, but perhaps within the week, or the following week.

**Comment by serhiy-storchaka** [comment]
Well, then I have created it myself. It is much larger if include all cases.
