### ISSUE TITLE
Define test_search_anchor_at_beginning as CPU-heavy tests.

### ISSUE THREAD

**Issue by corona10** [python/cpython#117594]
Currently test_search_anchor_at_beginning requires to be completed in an absolute time.
This can be flaky at low CPU environment or slow alternative implementation like RustPython.

I would like to suggest adding `@support.requires_resource('cpu')` to the test.

https://github.com/python/cpython/blob/62aeb0ee69b06091396398de56dcb755ca3b9dc9/Lib/test/test_re.py#L2285-L2296

### Linked PRs
* gh-117595
* gh-117616

**Comment by youknowone** [comment]
Thank you! Related RustPython CI failure is: https://github.com/RustPython/RustPython/actions/runs/8580508887/job/23516638468
