### ISSUE TITLE
[BUG]  ZoneInfo does not support datetime.Time and utcoffset can't be retrieved

### ISSUE THREAD

**Issue by 07pepa** [python/cpython#117598]
# Bug report

### Bug description:

this function does not support datetime.time  https://github.com/python/cpython/blob/558b517bb571999ef36123635e0245d083a28305/Lib/zoneinfo/_zoneinfo.py#L187

```python
def test():
    from zoneinfo import ZoneInfo
    from datetime import time
    t=time(12, 4, 5, 123456, tzinfo=ZoneInfo("Europe/Prague"), fold=1)
    if t.tzinfo.utcoffset(None) is None:
        # if prevuous does not work this should but fails with
        # AttributeError: 'datetime.time' object has no attribute 'toordinal'
        t.tzinfo.utcoffset(t)
```

i propose checking if instance is time and then skip to ordinal like so
```python
 def _get_local_timestamp(self, dt):
        return (
                (dt.toordinal() - EPOCHORDINAL) * 86400 if not isinstance(dt, time) else 0
                + dt.hour * 3600
                + dt.minute * 60
                + dt.second
        )
```
this issue is blocker for https://github.com/pydantic/speedate/issues/62

if this is confirmed i am open to do PR or leave it to someone else Maybe there is something more i am not seeing

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by JamesParrott** [comment]
I can recreate this on Windows, but below, aren't you asking zoneinfo a question that has an ambiguous answer?
```
t=time(12, 4, 5, 123456, tzinfo=ZoneInfo("Europe/Prague"), fold=1)
t.tzinfo.utcoffset(t)
```

t.tzinfo.utcoffset(t)`utcoffset` expects a datetime, so that it can figure out whether or not "Europe/Prague" is on daylight savings time, at the datetime in question.

**Comment by 07pepa** [comment]
actualy this works with pytz  so maybe its pytz bug ?
```python

   from pytz import timezone
    from datetime import time
    t = time(12, 4, 5, 123456, tzinfo=timezone("Europe/Prague"), fold=1)
    if t.tzinfo.utcoffset(None) is None:
        print(t.tzinfo.utcoffset(t))
```

**Comment by JamesParrott** [comment]
I don't think it's a bug.  It's Python requiring you to be explicitly specify on which date you wish the daylight savings time to be used from, for a time zone's UTC offset.

**Comment by 07pepa** [comment]
That seems logical gona file bug on pytz

**Comment by JamesParrott** [comment]
Out of scope for CPython now  

But, @07pepa I don't think it's a bug in pytz either.  pytz has just chosen to always return self._utcoffset from TimeZone.utcoffset:

```
    def utcoffset(self, dt, is_dst=None):
        '''See datetime.tzinfo.utcoffset

        The is_dst parameter may be used to remove ambiguity during DST
        transitions.

        >>> from pytz import timezone
        >>> tz = timezone('America/St_Johns')
        >>> ambiguous = datetime(2009, 10, 31, 23, 30)

        >>> str(tz.utcoffset(ambiguous, is_dst=False))
        '-1 day, 20:30:00'

        >>> str(tz.utcoffset(ambiguous, is_dst=True))
        '-1 day, 21:30:00'

        >>> try:
        ...     tz.utcoffset(ambiguous)
        ... except AmbiguousTimeError:
        ...     print('Ambiguous')
        Ambiguous

        '''
        if dt is None:
            return None
        elif dt.tzinfo is not self:
            dt = self.localize(dt, is_dst)
            return dt.tzinfo._utcoffset
        else:
            return self._utcoffset
```
https://github.com/stub42/pytz/blob/fb43f957c5149e750c3be3cfc72b22ad94db4886/src/pytz/tzinfo.py#L422
