### ISSUE TITLE
Improve typing.TypeGuard docstring

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#117521]
The [current docstring](https://github.com/python/cpython/blob/1c434688866db79082def4f9ef572b85d85908c8/Lib/typing.py#L844) for `typing.TypeGuard` includes a single example, but that example does not use `TypeGuard`, and in fact demonstrates behavior that differs from that of `TypeGuard` in essential ways. It would be less confusing if the TypeGuard example actually exemplified TypeGuard.

### Linked PRs
* gh-117522
* gh-117538

**Comment by AlexWaygood** [comment]
It can't be backported any further than it already has been, as Python 3.11 is no longer accepting any changes unless they relate to security issues. So this can be closed now, thanks!
