### ISSUE TITLE
C API: Add PyTuple_GetItemRef(), similar to PyTuple_GetItem() but return a strong reference

### ISSUE THREAD

**Issue by vstinner** [python/cpython#117518]
I propose to add a new PyTuple_GetItemRef() function, similar to PyTuple_GetItem() but return a strong reference instead of a borrowed reference.

Other functions were added recently to return a strong reference:

* PyDict_GetItemRef(), PyDict_GetItemStringRef() -- issue gh-106004
* PyList_GetItemRef() -- issue gh-114329
* PyWeakref_GetRef() -- issue gh-105927
* PyImport_AddModuleRef() -- issue gh-105922

I already proposed adding PyTuple_GetItemRef() in 2020, but the idea was rejected: issue gh-86460. Since 2020, Free Threading (PEP 703) was added to Python and borrowed references don't play well with Free Threading.

### Linked PRs
* gh-117519
* gh-117920
* gh-118087

**Comment by vstinner** [comment]
@colesbury @erlend-aasland @serhiy-storchaka: What do you think of adding this function?

**Comment by erlend-aasland** [comment]
> @colesbury @erlend-aasland @serhiy-storchaka: What do you think of adding this function?

I'm not a part of the C API WG, but I'm +1 ;)

**Comment by serhiy-storchaka** [comment]
I do not think it is needed. Adding it means that there is something wrong with `PyTuple_GetItem()`, but it is not. Tuples are immutable, so as far as we keep a strong reference to a tuple, weak references to its elements are valid. There is a lot of code that relies on this, not only directly, but function call conventions and `PyArg_Parse*` API.

Adding `PyTuple_GetItemRef()` will not solve any problem. Replacing `PyTuple_GetItem()` with `PyTuple_GetItemRef()` will have significant performance impact, and in many cases just impossible.

**Comment by vstinner** [comment]
The problem is not the `tuple` data structure, the problem here is to promote usage of strong references, rather than borrowed references to prevent crashes caused by dangling pointers. Example where using a borrowed reference is dangerous:

```c
PyObject *tuple = Py_BuildValue("(iii)", 2000, 3000, 4000);
PyObject *number = PyTuple_GetItem(tuple, 0);

Py_DECREF(tuple);
// number is now a dangling pointer

... code using 'number' variable ...
```

Correct code using only strong references:

```c
PyObject *tuple = Py_BuildValue("(iii)", 2000, 3000, 4000);
PyObject *number = PyTuple_GetItemRef(tuple, 0);

Py_DECREF(tuple);
// number is now a dangling pointer

... code using 'number' variable ...
Py_DECREF(number);
```

My intent is to have a subset of the C API which does not use borrowed references, or at least, hide functions returning borrowed references, when alternativates using strong references exists. See also [PEP 743](https://peps.python.org/pep-0743/) – Add Py_COMPAT_API_VERSION to the Python C API.

**Comment by vstinner** [comment]
> There is a lot of code that relies on this, not only directly, but function call conventions and PyArg_Parse* API.

I don't plan to deprecate PyTuple_GetItem(). You can still use it if you are sure that you are holding a strong reference to the container (the tuple) while using its items.

**Comment by serhiy-storchaka** [comment]
If you want to create a strong reference, just call `Py_INCREF()`.

**Comment by erlend-aasland** [comment]
After re-reading [PEP-703](https://peps.python.org/pep-0703/#borrowed-references) I'm +0. Quoting from the PEP:

> Note that some APIs that return borrowed references, such as `PyTuple_GetItem`, are not problematic because tuples are immutable.

**Comment by vstinner** [comment]
> I already proposed adding PyTuple_GetItemRef() in 2020, but the idea was rejected: issue https://github.com/python/cpython/issues/86460. Since 2020, Free Threading (PEP 703) was added to Python and borrowed references don't play well with Free Threading.

See also this numpy issue: https://github.com/numpy/numpy/issues/26159

**Comment by erlend-aasland** [comment]
> > I already proposed adding PyTuple_GetItemRef() in 2020, but the idea was rejected: issue #86460. Since 2020, Free Threading (PEP 703) was added to Python and borrowed references don't play well with Free Threading.
> 
> See also this numpy issue: [numpy/numpy#26159](https://github.com/numpy/numpy/issues/26159)

That issue does not mention `PyTuple_GetItem` at all ;)
