### ISSUE TITLE
Need a detailed explanation of the below added line into documentation

### ISSUE THREAD

**Issue by imrankuruvitta** [python/cpython#117597]
consider this line "A class in an [except] clause is compatible with an exception if it is the same class or a base class thereof (but not the other way around — an except clause listing a derived class is not compatible with a base class)" which comes under errors and exception in python tutorial web page, please give clear explanation, because as it is not understandable by programmers who is new to python , added screenshot below
![Screenshot (1)](https://github.com/python/cpython/assets/39944760/84cc791a-1def-46e7-b658-7e296dc799b9)

### Linked PRs
* gh-117681
* gh-117700

**Comment by nineteendo** [comment]
An `except` clause catches all errors of the specified class and its derived classes:

```python
class ErrorA(Exception):
    pass

class ErrorAPlus(ErrorA):
    pass

class ErrorB(Exception):
    pass

for cls in [ErrorA, ErrorAPlus, ErrorB]:
    try:
        raise cls()
    except ErrorA:
        print("Caught error A")
```

Output:

```none
Caught error A
Caught error A
Traceback (most recent call last):
  File "c:\Users\wanne\Desktop\test.py", line 12, in <module>
    raise cls()
ErrorB
```

Do you think the docs need to be updated with this?

**Comment by imrankuruvitta** [comment]
Yes,  correct

**Comment by erlend-aasland** [comment]
Resolved by:

- #117681 
- #117700 (auto-merge enabled)
