### ISSUE TITLE
Raise TypeError for non-paths in `posixpath.relpath()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117584]
# Bug report

### Bug description:

```python
>>> import posixpath
>>> posixpath.relpath(None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen posixpath>", line 509, in relpath
ValueError: no path specified
```

Expected: TypeError like `npath.relpath()`.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-117585
* gh-119388

**Comment by erlend-aasland** [comment]
Changing the exception type is a backwards-incompatible change; some people will need to rewrite their exception handling to adapt to the new behaviour. Do the pro's outweigh the con's?

**Comment by nineteendo** [comment]
This is the same thing we did with non-iterables in `ntpath.commonpath()`: #117335
And it matches the error thrown by `ntpath.relpath()`, which better communicates what's wrong.

**Comment by erlend-aasland** [comment]
I'll defer to Serhiy, who is particularly interested in such cases. cc. @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
We usually do not bother with checking arguments more than necessary, especially in the Python code (which do not crash if you use wrong types or values). If the code happens to work outside the purposed area, well, someone can use it. If it fails with a weird error -- just do not do it. But in this case the change has zero performance cost, and TypeError is more suitable for `None`, `0` and `[]` than ValueError. It should be different from the error for `''` and `b''`.
