### ISSUE TITLE
Improve the performance of ntpath.expanduser()

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117686]
# Feature or enhancement

### Proposal:

In `ntpath.expanduser()`, `_get_bothseps()` is called in every loop iteration. It should be assigned instead:

```diff
 if isinstance(path, bytes):
+    seps = b'\\/'
     tilde = b'~'
 else:
+    seps = '\\/'
     tilde = '~'
 if not path.startswith(tilde):
     return path
 i, n = 1, len(path)
-while i < n and path[i] not in _get_bothseps(path):
+while i < n and path[i] not in seps:
     i += 1
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117634

### Linked PRs
* gh-117690

**Comment by terryjreedy** [comment]
To me, this is a clearly better.

**Comment by erlend-aasland** [comment]
Thanks!

**Comment by erlend-aasland** [comment]
Thanks!
