### ISSUE TITLE
Use set comprehension for `posixpath.commonpath()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117641]
# Feature or enhancement

### Proposal:

We can use a set comprehension to check if no absolute and relative paths are mixed:

```diff
-try:
-    isabs, = set(p[:1] == sep for p in paths)
-except ValueError:
-    raise ValueError("Can't mix absolute and relative paths") from None
+if len({p.startswith(sep) for p in paths}) != 1:
+    raise ValueError("Can't mix absolute and relative paths")
```

```diff
-prefix = sep if isabs else sep[:0]
+prefix = sep if paths[0].startswith(sep) else sep[:0]
```

This is faster and more readable.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117610

### Linked PRs
* gh-117652

**Comment by blhsing** [comment]
If the goal is to improve performance, it's likely better to use an approach that can short-circuit, such as the `all_equal` recipe from  the `itertools` doc.
