### ISSUE TITLE
Special case for "" & "." in `posixpath.abspath()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117639]
# Feature or enhancement

### Proposal:

We could add a special case for the current directory and return it without normalising. This speeds up `posixpath.relpath()` with one argument.

```diff
 def abspath(path):
     """Return an absolute path."""
     path = os.fspath(path)
     if isinstance(path, bytes):
-        if not path.startswith(b'/'):
-            path = join(os.getcwdb(), path)
+        sep = b'/'
+        curdir = b'.'
+        getcwd = os.getcwdb
     else:
-        if not path.startswith('/'):
-            path = join(os.getcwd(), path)
+        sep = '/'
+        curdir = '.'
+        getcwd = os.getcwd
+    if not path.startswith(sep):
+        if not path or path == curdir:
+            return getcwd()
+        path = join(getcwd(), path)
     return normpath(path)
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117610

### Linked PRs
* gh-117640

**Comment by nineteendo** [comment]
This speeds up `posixpath.relpath()` with 1 argument.

**Comment by AlexWaygood** [comment]
> This speeds up `posixpath.relpath()` with 1 argument at no cost.

I see. That would be useful information to edit into the issue description.

**Comment by erlend-aasland** [comment]
> This speeds up `posixpath.relpath()` with 1 argument at no cost.

How much is that speedup? According to your PR there is no speedup for the general call with one argument.

**Comment by nineteendo** [comment]
I'll do a benchmark soon. The pull request currently doesn't compare the performance of `posixpath.relpath()`, but it will be at most 13% faster.

**Comment by AlexWaygood** [comment]
> This special case makes `posixpath.relpath()` with a single argument 4-6% faster.

Hmm. In my opinion, this particular optimisation is not worth it for a speedup of that magnitude. The refactor makes the code of this function look quite odd (the kind of thing that somebody keen on "refactoring" or "simplifying" the code of `os.path` might propose rewriting in a PR), and it's quite unobvious to a reader of the code that it's been deliberately written that way in order to speedup `relpath()`.

**Comment by nineteendo** [comment]
OK, I was planning for a larger speedup anyway, that would apply to all relative paths: #117587.
