### ISSUE TITLE
Give _PyInstructionSequence a python interface and use it in compiler tests

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#117680]
Expose ``_PyInstructionSequence`` as a PyObject, and then the compiler tests would be able to work with it directly.

By giving this object functions to add a label/instruction, the logic of translating a convenient python representation to a C sequence does not need to be duplicated in the test harness, the process of constructing an instruction sequence from tests becomes the same as the one used in codegen, and re-uses the implementation of the instruction sequence data structure.

### Linked PRs
* gh-117629
* gh-118326

**Comment by terryjreedy** [comment]
/refuses/re uses/? (last line)
