### ISSUE TITLE
Speedup `os.path`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117609]
# Feature or enhancement

### Proposal:

There are (still) some minor optimisations possible in `os.path`, including some fast returns.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-117610

**Comment by barneygale** [comment]
Duplicate of #117349, please don't do this. The bug tracker is not your personal to-do list.

**Comment by nineteendo** [comment]
> Most PRs will require an issue number. Trivial changes, like fixing a typo, do not need an issue.

Must I link to the closed issue then? This PR is about further changes.

**Comment by barneygale** [comment]
If you think the previous issue was closed prematurely then you can leave a comment there asking for it to be re-opened.
