### ISSUE TITLE
错误：安装许多第三方库时，会出现bug

### ISSUE THREAD

**Issue by Leo-hele** [python/cpython#117602]
# Bug report

### Bug description:

安装第三方库时，会出现
```python
raise e
self.evaluate_statement(cur)
return self.evaluate_if(cur),
self.evaluate_codeblock(node.elseblock)
```
的循坏，导致无法安装，不知道是否是python的问题
提示：Cpython我看到好像是19.39

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by aisk** [comment]
Hi, according to the [devguide](https://devguide.python.org/triage/issue-tracker/#reporting-an-issue) if you are looking for help, please go to https://discuss.python.org/c/users/7 .

**Comment by 1649hele** [comment]
无法修改以前的内容。
________________________________
发件人: AN Long ***@***.***>
发送时间: 2024年4月7日 21:33
收件人: python/cpython ***@***.***>
抄送: 何乐 ***@***.***>; Manual ***@***.***>
主题: Re: [python/cpython] 错误：安装许多第三方库时，会出现bug (Issue #117602)


Hi, according to the devguide<https://devguide.python.org/triage/issue-tracker/#reporting-an-issue> if you are looking for help, please go to https://discuss.python.org/c/users/7 .

―
