### ISSUE TITLE
Explicit dictionary calling methods inside formatted string

### ISSUE THREAD

**Issue by FMorschel** [python/cpython#117650]
# Bug report

### Bug description:

Hi, I'm new to this repo and if I have missed any issues regarding this or if this should be placed somewhere else, please let me know so I can do it.

I created [this issue](https://github.com/microsoft/vscode/issues/209435) about a string interpolation bracket colouring for Dart and as the thread continued, I [came across the following](https://github.com/microsoft/vscode/issues/209435#issuecomment-2042588321) (explained below).

I'm not completely sure if this should work but since the `truncate` method works, I do believe that there is a problem here. My question would be if this is a problem with the Python extension for vscode, if this is an error in Python itself or if there could be a better error message. 

It gives me an error in the last line `SyntaxError: f-string: single '}' is not allowed` and paints every character (but the opening and closing brackets) inside the formatted string with the same colour as it's painting my string.

<details>

<summary> Screenshot from vscode </summary>

![Screenshot for painting inside vscode](https://github.com/microsoft/vscode-python/assets/52160996/acf7f4c3-0e5a-4d21-b24e-ef345e26ffbf)

</details>

```python
d = {1: 2}
keys = d.keys()

#interpolated string test
print(f'The value is {d[1]}\n{{1: 2}} -> {keys}.')

1.0.is_integer()
print(f'Is integer: {1.0.is_integer()}')

print(f'Testing {{1:2}.keys()}')
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by gaogaotiantian** [comment]
In f-string, double bracket `{{` has an explicit meaning - escape bracket. So that's a literal bracket `{` because the bracket itself has special meanings in f-string. That's what caused the syntax error. Breaking the double bracket should work - `print(f'Testing { {1:2}.keys() }')`

**Comment by FMorschel** [comment]
Oh, I see! Sorry for the inconvenience!

**Comment by FMorschel** [comment]
I still feel like there was a little problem here. If you agree, you can reopen this or open another issue in the extension tracker (if they are separate). 

If in that case, the double brackets could be parsed with another colour like the same that `\n` is painted, that could give people like me, a little bit more context instead of leaving them to be painted as the next colours for them.

This way both closing brackets would be painted alone in a different colour than the rest of the string and that could help to figure that out.

**Comment by FMorschel** [comment]
I've checked and inside PyCharm that is already a thing. Maybe this could be implemented inside the vscode extension as well?

**Comment by gaogaotiantian** [comment]
The VSCode extension is not part of CPython. You are probably looking for https://github.com/microsoft/vscode-python
