### ISSUE TITLE
Improve performance of os.join by replacing map with a direct method call

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#117648]
# Feature or enhancement

### Proposal:

We can improve performance of `os.join` by changing
```
        for b in map(os.fspath, p):
```
into
```
        for w in p:
            b=os.fspath(w)
```
The  `map` generator  takes time to create and the application of the method to each element also takes some time. A quick benchmark
```
main: 385 ns ± 11.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
map replaced: 328 ns ± 9.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

The idea still needs to be tested on other platforms and with longer sequences. 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-117654
* gh-117693
* gh-117697

**Comment by eendebakpt** [comment]
@nineteendo Is this something you are interested in to implement?

**Comment by nineteendo** [comment]
Yeah, I'll make another PR. :-) For `ntpath.join()` we can even remove the `os.fspath()` call alltogether, as we already have `splitroot()`:

```diff
-for p in map(os.fspath, paths):
+for p in paths:
    p_drive, p_root, p_path = splitroot(p)
```
