### ISSUE TITLE
PEP 737 implementation errors

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#117642]
# Bug report

For some reasons gh-111696 implemented `%T#` and `%N#` instead of `%#T` and `%#N`. It does not only contradict PEP 737, but does not match the general principles of prinf-like format, and can cause problems in future.

Tests, which were added in gh-111696, were removed in gh-116417, so now this feature is not tested.

### Linked PRs
* gh-117643

**Comment by vstinner** [comment]
I suppose that the issue can now be closed? Or did you spot other implementation issues?

**Comment by vstinner** [comment]
Thanks for the fix.
