### ISSUE TITLE
Why does this python program hang the terminal when it exits on Linux or WSL?

### ISSUE THREAD

**Issue by rtestardi** [python/cpython#117698]
# Bug report

### Bug description:

From what I can tell, this program confuses the terminal emulation on both Linux and WSL, on both python 2 and 3.

Once the program exits, characters are no longer echoed and normal terminal function ceases. I believe this is because the daemon thread is stuck in read(1) while the main thread exits.

You can recover the terminal by typing "reset" (which is not echoed) followed by Enter to run the reset command to reinitialize the terminal emulation.

You can avoid the problem by forcing the getchar thread to join the main thread before the main thread exits by using t2.join().

But I'd prefer to have a clean solution that just works -- any ideas?

Maybe the question I should ask is, how can I use getchar from a thread without being forced to do a join on exit? Is there a way? Maybe the answer is no. This code is for high-schoolers, so we are trying to keep it simple. Thanks!!!

Thanks!!!

```python
import sys
import time
import platform
import threading

def getchar():
    import tty, termios, sys
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    print("you pressed '" + ch + "'\r")
    return ch

def getcharThread():
    while getchar() != 'q':
        time.sleep(0.1)
    print("thread exit\r")

t2 = threading.Thread(target = getcharThread)
t2.daemon = True
t2.start()

time.sleep(2)
```
After running this program, I expect the terminal to still work normally. Instead, it does not echo characters (likely from the setraw() or read()).

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by eryksun** [comment]
Since the getchar thread is a daemon thread, the main thread doesn't automatically join it at exit. Instead, the main thread ultimately calls C `exit()`, which forcibly terminates the getchar thread. In this case, `tcsetattr()` doesn't get called to reset the terminal.

There's no problem if `getchar()` is called on the main thread. Generally, the UI of an application should be implemented on the main thread, and additional threads get created for asynchronous and parallel processing.

**Comment by rtestardi** [comment]
Thanks, @eryksun that all makes sense.  I agree there is no problem if getchar is called on the main thread.

I was just hoping there might be a simple solution.

I can confirm this works as well, explicitly restoring the tcsetattr on exit:

```python
import sys
import time
import platform
import threading
import tty, termios, sys

fd = None
old_settings = None

def getchar():
    global fd, old_settings
    fd = sys.stdin.fileno()
    old_settings = termios.tcgetattr(fd)
    try:
        tty.setraw(sys.stdin.fileno())
        ch = sys.stdin.read(1)
    finally:
        termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
    print("you pressed '" + ch + "'\r")
    return ch

def getcharThread():
    while getchar() != 'q':
        time.sleep(0.1)
    print("thread exit\r")

t2 = threading.Thread(target = getcharThread)
t2.daemon = True
t2.start()

time.sleep(2)

# restore the tty to the state before the pending getchar was called
termios.tcsetattr(fd, termios.TCSADRAIN, old_settings)
```
