### ISSUE TITLE
Python calendar module, and month method ...are inaccurate for September 1752 

### ISSUE THREAD

**Issue by profharris** [python/cpython#117792]
# Bug report

### Bug description:

```python
#  Comparing for a student demonstration, the Python 'calendar' module, with the Linux utility 'cal'...
#   The output generated for;  
>>> print(calendar.month(1752, 9)) 
#   is incorrect. The output looks like:
>>>  print(calendar.month(1752, 9))
   September 1752
Mo Tu We Th Fr Sa Su
             1  2  3
 4  5  6  7  8  9 10
11 12 13 14 15 16 17
18 19 20 21 22 23 24
25 26 27 28 29 30

#   monospace font needed for alignment...
#  
#    The generated output should be the same as this Linux cal example...
#   $ cal 9 1752
   September 1752
Su Mo Tu We Th Fr Sa
       1  2 14 15 16
17 18 19 20 21 22 23
24 25 26 27 28 29 30

# Not only is the classic Gregorian calendar versus Julian calendar adjustment not accounted for,
#  e.g. twelve missing days September 3rd-13th, Python calendar starts the first day of the month
#  for September 1752 on a Friday, instead of the correct Tuesday as September 1st 1752.
#   Am I missing something?
# 
# Prof. Michael P. Harris
# Del Mar College
# mpharris@delmar.edu

```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
From the calendar docs at https://docs.python.org/3/library/calendar.html: "The functions and classes defined in this module use an idealized calendar, the current Gregorian calendar extended indefinitely in both directions. "

So I think it's behaving correctly.

**Comment by hugovk** [comment]
In addition to what Eric says, the shortened September 1752 month was only for Great Britain and the British Empire, which is when they finally adopted the Gregorian calendar:

* https://www.timeanddate.com/calendar/monthly.html?country=9&month=9&year=1752

Catholic countries had already adopted it in 1582, so they had a full September 1752:

* https://www.timeanddate.com/calendar/monthly.html?year=1752&month=9&country=13

Compare also October 1582:

+ https://www.timeanddate.com/calendar/monthly.html?year=1582&month=10&country=9 
* https://www.timeanddate.com/calendar/monthly.html?year=1582&month=10&country=13 

More info:

* https://en.wikipedia.org/wiki/Adoption_of_the_Gregorian_calendar
