### ISSUE TITLE
Stale GIL glossary definition 

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#117739]
# Documentation

The definition of the GIL in the glossary is stale as a result of https://github.com/python/cpython/pull/116338 in Python 3.13.

Specifically:

> Past efforts to create a “free-threaded” interpreter (one which locks shared data at a much finer granularity) have not been successful because performance suffered in the common single-processor case. It is believed that overcoming this performance issue would make the implementation much more complicated and therefore costlier to maintain.

### Linked PRs
* gh-117740

**Comment by savannahostrowski** [comment]
About to open a PR to fix this!

**Comment by colesbury** [comment]
Thanks @savannahostrowski!
