### ISSUE TITLE
Palmpay, join Nwachukwu Chris on Skype

### ISSUE THREAD

**Issue by chris6090** [python/cpython#117794]
Hi Palmpay, Nwachukwu Chris would like to chat with you on Skype. It's free!

https://join.skype.com/invite/Ka3WlwKcwCdL

**Comment by zware** [comment]
@python/organization-owners, please block OP.  [Local history](https://github.com/python/cpython/issues?q=involves%3Achris6090) shows 4 spam issues, 1 spam PR, and further spam comments.  Activity in other repositories doesn't appear to make a clear case for a real human, either.  User has been reported to GitHub multiple times by multiple people, and it doesn't look like they're going to do anything about this one.

**Comment by hugovk** [comment]
GitHub Trust & Safety's reply to my third report yesterday in response to pointing to these issues:

1) https://github.com/python/cpython/issues/117730
2) https://github.com/python/cpython/issues/117523
3) https://github.com/python/cpython/pull/117384
4) https://github.com/python/cpython/issues/117582
 

> Hi Hugo, 
>
> Thanks for taking the time to let us know. It does appear that the reported content has been moderated or removed at this time. We'll take a look to see if any further action is necessary on our part. 
> 
> If you haven't already done so, you can block the user by following the instructions found here: 
> 
> [Blocking a user from your personal account](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-personal-account) 
> 
> [Blocking a user from your organization](https://docs.github.com/en/communities/maintaining-your-safety-on-github/blocking-a-user-from-your-organization)

🤷‍♂️

**Comment by ambv** [comment]
Blocked.
