### ISSUE TITLE
Allow CPython to build against cryptography libraries lacking post-handshake authentication

### ISSUE THREAD

**Issue by WillChilds-Klein** [python/cpython#117784]
# Feature or enhancement

### Proposal:

As part of a series of changes [discussed on the python Ideas board](https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505/6), this issue proposes placing guards around references to [TLSv1.3 post-handshake authentication](https://datatracker.ietf.org/doc/html/rfc8446#section-4.2.6) (PHA). This would CPython to build against cryptography libraries lacking full PHA support.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505/9

### Linked PRs
* gh-117785

**Comment by encukou** [comment]
Thanks!
As this is meant for unsupported builds, I'll not backport to 3.13. Y'all already have patching mechanism :)

Do you want to send more PRs for this issue?

**Comment by WillChilds-Klein** [comment]
No more PRs needed unless you'd like me to [add an AWS-LC integration test to CPython's CI](https://discuss.python.org/t/support-building-ssl-and-hashlib-modules-against-aws-lc/44505/11). Thank you for your reviews!
