### ISSUE TITLE
Missing grammar tests for match statement

### ISSUE THREAD

**Issue by ujan-r** [python/cpython#117724]
# Feature or enhancement

### Proposal:

[Lib/test/test_grammar.py](https://github.com/python/cpython/blob/630df37116b1c5b381984c547ef9d23792ceb464/Lib/test/test_grammar.py) doesn't contain any tests for the match statement.

Unless this was an intentional omission, I'll send in a PR tomorrow.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
The tests are in `Lib/test/test_patma.py`. It's possible that something is missing but they appear quite exhaustive.

**Comment by ujan-r** [comment]
Ah, I missed that in my search. Looks pretty exhaustive to me!
