### ISSUE TITLE
Argument Clinic: allow a `*args: object` parameter with following keyword-only parameters

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#117733]
# Bug report

There's a bug in clinic that prevents you from specifying a `*args: object` parameter with a following keyword-only parameter. I have a PR ready.

### Linked PRs
* gh-117734

**Comment by serhiy-storchaka** [comment]
How does it work now?
```
vararg_with_kw_only
    *args: object
    b: object
```

**Comment by serhiy-storchaka** [comment]
It seems that it works as expected (as in Python), so adding yet one `*` is not needed.
