### ISSUE TITLE
configure script is run with /bin/sh, but contains GNU bash logic

### ISSUE THREAD

**Issue by eli-schwartz** [python/cpython#117787]
# Bug report

### Bug description:

I just build the python 3.13 alpha on Gentoo to have available for testing. While doing so, I discovered the following message from Gentoo's QA framework:

```
 * QA Notice: Abnormal configure code
 * 
 * ./configure: 24692: test: Linux: unexpected operator
```

This happens when the shell itself hits code that isn't valid shell code.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-117788

**Comment by erlend-aasland** [comment]
Thanks for the report and fix!
