### ISSUE TITLE
Regression in tricky __dict__ use.

### ISSUE THREAD

**Issue by felixxm** [python/cpython#117838]
# Bug report

### Bug description:

I noticed a regression in Python 3.13.0 alpha 6. Django [`LazySettings`](https://github.com/django/django/blob/42bc81b1b6471c4fe364bc32b9dec180908e577e/django/conf/__init__.py#L45) started to [crash](https://github.com/django/django/actions/runs/8670508480/job/23778598639) because `_wrapper` is no longer set to the [`empty`](https://github.com/django/django/blob/42bc81b1b6471c4fe364bc32b9dec180908e577e/django/utils/functional.py#L245) sentinel. I bisected this regression to the c32dc47aca6e8fac152699bc613e015c44ccdba9, so it's related with the recent changes in `__dict__`.

Django's `LazySettings` and `LazyObject` are quite tricky. I will try to provide a small reproducer later.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
Issue #117750 is likely related to this.

**Comment by encukou** [comment]
The dict issue is fixed on main (#117808), but the Django tests now fail with another assertion added as part of the same change:
```
python: ./Include/internal/pycore_object.h:283: _PyObject_Init: Assertion `_PyType_HasFeature(typeobj, Py_TPFLAGS_HEAPTYPE) || _Py_IsImmortal(typeobj)' failed.
```

cc @markshannon

**Comment by markshannon** [comment]
Should be fixed by https://github.com/python/cpython/pull/117673.

**Comment by felixxm** [comment]
Let me confirm :male_detective:

**Comment by felixxm** [comment]
It works for me :tada: Many thanks for help :firefighter:
