### ISSUE TITLE
PGO: compiler warnings for source files with no profile data

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#117804]
PGO builds do not generated profile data for all source files. This means that for a PGO build, you may end up with compiler warnings for source files with no profile data. Do we want to silence these warnings? If we do, it _may_ be harder to spot if PGO builds fail to include profile data correctly.

Spotted while working on #117752.

### Linked PRs
* gh-117796
* gh-117859
* gh-117912

**Comment by erlend-aasland** [comment]
Example warning:

```console
gcc -bundle -undefined dynamic_lookup      Modules/syslogmodule.o   -o Modules/syslog.cpython-313-darwin.so
gcc  -fno-strict-overflow -Wsign-compare -Wunreachable-code -DNDEBUG -g -O3 -Wall    -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden -fprofile-instr-use=/Users/erlend.aasland/src/python/build-main/code.profclangd -I../main/Include/internal -I../main/Include/internal/mimalloc -IObjects -IInclude -IPython -I. -I../main/Include     -c ../main/Modules/termios.c -o Modules/termios.o
warning: no profile data available for file "termios.c" [-Wprofile-instr-unprofiled]
```

**Comment by zooba** [comment]
Unless they're actually disruptive (breaking builds), I'd rather leave them there by default.

Seems easy enough to add the suppression to CFLAGS manually, yeah? Should we just doc it?

**Comment by zooba** [comment]
It's one of these cases where if we suppress them once, we'll forget about coverage entirely, which is worse than simply continuing to not fix it (someone might be motivated to fix it in the future if they see it)

**Comment by erlend-aasland** [comment]
> Seems easy enough to add the suppression to CFLAGS manually, yeah? Should we just doc it?

I would be fine with that.
