### ISSUE TITLE
Shlex docs: improper syntax highlighting in code snippet

### ISSUE THREAD

**Issue by tuansuper** [python/cpython#117840]
# Snippet displays improper syntax highlight

In docs `shlex` of subtitle `Improved Compatibility with Shells`(https://docs.python.org/3/library/shlex.html#improved-compatibility-with-shells) ,the first snippet doesn't highlight properly.It should be highlighted in python scheme color.

### Linked PRs
* gh-117843
* gh-117844

**Comment by hugovk** [comment]
Thanks for the report, please see https://github.com/python/cpython/pull/117843 to fix it.
