### ISSUE TITLE
Stalling of Multiprocessing.Pool

### ISSUE THREAD

**Issue by suuuehgi** [python/cpython#117839]
# Bug report

### Bug description:

I have a weird behavior involving the multiprocessing module.

The following code stalls:
```python
import multiprocessing

import numpy as np
from skimage import io
from sklearn.cluster import KMeans

def create_model():
    sampled_pixels = np.random.randint(0, 255, (800,3))
    kmeans_model = KMeans(n_clusters=8, random_state=0).fit(sampled_pixels)

def process_image(test, test2):
    image  = np.random.randint(0, 255, (800,3))
    kmeans_model = KMeans(n_clusters=8, random_state=0).fit(image)
    image = kmeans_model.predict(image)

def main():

    create_model()

    with multiprocessing.Pool(1) as pool:

        pool.apply_async(process_image, args=('test', 'test'))

        pool.close()
        pool.join()

if __name__ == "__main__":
    main()
```

However, if I either remove the line `create_model()` OR change

```python
def process_image(test, test2)
# as well as
pool.apply_async(process_image, args=('test', 'test'))
```
to
```python
def process_image(test)`
# and
pool.apply_async(process_image, args=('test'))
```
the code runs successfully, as it should, since the arguments as well as the function call `create_model()` are completely redundant.

This was done in a fresh venv using `pip install numpy scikit-learn scikit-image`
```
> pip list
Package       Version
------------- ---------
imageio       2.34.0
joblib        1.4.0
lazy_loader   0.4
networkx      3.3
numpy         1.26.4
packaging     24.0
pillow        10.3.0
pip           23.2.1
scikit-image  0.23.1
scikit-learn  1.4.2
scipy         1.13.0
threadpoolctl 3.4.0
tifffile      2024.2.12

> python --version
Python 3.12.2

> pip --version
pip 23.2.1
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
This is not a CPython bug, this is a scikit-learn issue. The actual trigger is `lloyd_iter_chunked_dense` somehow stuck when there's another process using the same function. `lloyd_iter_chunked_dense` is a Cython function so I did not dig into it. You should report this to scikit-learn.

**Comment by suuuehgi** [comment]
Thanks for looking into this!

I think I tracked it down to [this](https://github.com/scikit-learn/scikit-learn/issues/23823) "bug" and indeed, `multiprocessing.set_start_method('spawn')` mitigates the problem.
