### ISSUE TITLE
Random exception of the Python interpreter in a free-threaded build.

### ISSUE THREAD

**Issue by APT64** [python/cpython#117864]
# Bug report

### Bug description:

```cpp
EXPORT VOID RunScript(char* name, int console_id, int argc, char* argv[]) {
	auto new_thread = PyThreadState_New(g_state->interp); //creating sub-main thread

	auto prev = PyThreadState_Swap(new_thread); //swap

	PyInterpreterConfig conf = { 0 };
	conf.check_multi_interp_extensions = 1;
	conf.allow_threads = 1;
	conf.gil = PyInterpreterConfig_OWN_GIL;
	
	PyThreadState* tstate;
	Py_NewInterpreterFromConfig(&tstate, &conf); // creating new interpreter in new thread
	PyEval_RestoreThread(tstate);

	ExecuteScript(name, console_id, argc, argv); //PyRun_String-like func

	PyThreadState_Clear(new_thread);
	PyThreadState_Delete(new_thread);
}
```

When executing such a function, python crashes after some time for various reasons, for example 
```pytb
Traceback (most recent call last):
  File "D:\server.py", line 300, in <module>
    main(sys.argv)
    ~~~~^^^^^^^^^^
  File "D:\server.py", line 297, in main
    run(args)
    ~~~^^^^^^
  File "D:\server.py", line 281, in run
    httpd = ThreadingHttpHandler(('0.0.0.0', int(args[0])), HttpRequestHandler)
            ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^
  File "D:\Lib\socketserver.py", line 452, in __init__
    BaseServer.__init__(self, server_address, RequestHandlerClass)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^
  File "D:\Lib\socketserver.py", line 207, in __init__
    self.__is_shut_down = threading.Event()
                          ~~~~~~~~~~~~~~~^^
  File "D:\Lib\threading.py", line 593, in __init__
    self._cond = Condition(Lock())
                 ~~~~~~~~~^^^^^^^^
  File "D:\Lib\socket.py", line 233, in __init__
    _socket.socket.__init__(self, family, type, proto, fileno)
    ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^
TypeError: descriptor '__init__' requires a '_socket.socket' object but received a 'Condition'
```
when trying to execute a script that starts an http server.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by colesbury** [comment]
I'm not sure any of this is related to the free-threaded build, but there are a few bugs in your code example:

- `Py_NewInterpreterFromConfig` sets the active thread-state. The subsequent `PyEval_RestoreThread()` crashes
-  You are missing a `Py_EndInterpreter()` 

Here is a similar, fixed example:

```c
    PyThreadState *prev = PyThreadState_Swap(NULL);

    PyInterpreterConfig conf = { 0 };
    conf.check_multi_interp_extensions = 1;
    conf.allow_threads = 1;
    conf.gil = PyInterpreterConfig_OWN_GIL;
    
    PyThreadState* tstate;
    Py_NewInterpreterFromConfig(&tstate, &conf); // creating new interpreter in new thread

    ExecuteScript(name, console_id, argc, argv); //PyRun_String-like func

    Py_EndInterpreter(tstate);
    PyThreadState_Swap(prev);
```

**Comment by APT64** [comment]
Oh yes, this is the rough code, the PyEval_RestoreThread() call has now been removed. However, I don't consider the lack of calling Py_EndInterpreter() to be the cause of the error, as it is just a memory leak. But in the error we can see that there seems to be object confusion in cpython.

**Comment by colesbury** [comment]
> I don't consider the lack of calling Py_EndInterpreter() to be the cause of the error, as it is just a memory leak

The lack of `Py_EndInterpreter()` is not just a memory leak. It also swaps the active thread state. Your original code example calls `PyThreadState_Clear()` with the wrong active interpreter. That can lead to all sorts of problems, including the ones you've described above.

I don't think there's anything more we can do with this issue without additional details that are sufficient to reproduce a bug in CPython.

**Comment by APT64** [comment]
Your fix just throws an exception (C0000005, EXCEPTION_ACCESS_VIOLATION)! in progress. The code I left above should be enough to reproduce the problem.

**Comment by colesbury** [comment]
It's not enough to reproduce the issue because the code run by `ExecuteScript` is not shown.

Here is the code I've tested that runs without issues:

<details>
<summary>Code Snippet</summary>

```c
static PyObject *
issue117864(PyObject *module, PyObject *arg)
{
    PyThreadState *prev = PyThreadState_Swap(NULL);

    PyInterpreterConfig conf = { 0 };
    conf.check_multi_interp_extensions = 1;
    conf.allow_threads = 1;
    conf.gil = PyInterpreterConfig_OWN_GIL;

    PyThreadState* tstate;
    Py_NewInterpreterFromConfig(&tstate, &conf); // creating new interpreter in new thread

    PyObject *globals = PyDict_New();
    PyObject *locals = PyDict_New();

    PyObject *r = PyRun_String("print('Hello, World!')", Py_file_input, globals, locals);
    if (r == NULL) {
        PyErr_Print();
    }
    Py_XDECREF(r);

    Py_EndInterpreter(tstate);
    PyThreadState_Swap(prev);
    Py_RETURN_NONE;
}
```
</details>

**Comment by APT64** [comment]
My program calls this code several times, so that inside the first ExecuteScript call there is another ExecuteScript call (for example, the autorun.py file runs other scripts through this code, which, by the way, is part of a custom cpython module). The first call (including the nested one) succeeds, but the second does not.
<img width="1280" alt="Безымянный" src="https://github.com/python/cpython/assets/88889465/6c279589-68f6-4ca5-9b1d-f74baf40798b">
