### ISSUE TITLE
Don't call `lookdict_index` in `delitemif_lock_held`

### ISSUE THREAD

**Issue by colesbury** [python/cpython#117826]
The `delitemif_lock_held` function calls `lookdict_index` and passes the returned `hashpos` to `delitem_common`. We should just pass the actual `hash` to `delitem_common`.

The existing code is confusing and unnecessary, but it's not exactly a bug. The behavior is fine because it's safe in this case to pretend the hashtable index (`hashpos`) is a hash value. The resulting `size_t i = (size_t)hash & mask` to compute the index from the hash is effectively a no-op.

https://github.com/python/cpython/blob/069de14cb948f56b37e507f367b99c5563d3685e/Objects/dictobject.c#L2635-L2645

https://github.com/python/cpython/blob/069de14cb948f56b37e507f367b99c5563d3685e/Objects/dictobject.c#L2502-L2504

https://github.com/python/cpython/blob/069de14cb948f56b37e507f367b99c5563d3685e/Objects/dictobject.c#L995-L1000

### Linked PRs
* gh-117869

**Comment by corona10** [comment]
@colesbury Now we can close the issue?

**Comment by colesbury** [comment]
Yes, thanks for fixing this @corona10
