### ISSUE TITLE
_testexternalinspection.c doesn't check for undefined TARGET_OS_OSX

### ISSUE THREAD

**Issue by jmroot** [python/cpython#117891]
# Bug report

### Bug description:

Similar to #117886, `TARGET_OS_OSX` is not defined by older macOS SDKs, and the code doesn't distinguish between it being undefined and being defined to 0.

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-117892

**Comment by ned-deily** [comment]
Thanks again for the issue. As discussed in the associated PR https://github.com/python/cpython/pull/117887, the suggested change has been rolled up and merged in PR https://github.com/python/cpython/pull/118073.
