### ISSUE TITLE
Restore removed Py_SetProgramName() and PySys_SetArgv() functions

### ISSUE THREAD

**Issue by vstinner** [python/cpython#117987]
My Fedora team identified that the removal of "Python initialization" functions impacts at least 17 projects. I propose to restore them to give more time to impacted projects to be updated to the new [PEP 587 PyConfig API](https://peps.python.org/pep-0587/) added to Python 3.8.

These functions were marked as deprecated in Python 3.11.

`Py_SetProgramName()` and/or `Py_SetPythonHome()`, 7 impacted projects:

* dionaea
* fontforge
* glade
* libreoffice
* neuron
* python-pyqt6
* python-pyside6

`PySys_SetArgv()` and/or `PySys_SetArgvEx()`, 12 impacted projects (glade and neuron are both lists):

* collectd
* glade
* gnumeric
* kernel
* nautilus-python
* nemo-extensions
* neuron
* obs-studio
* pyotherside
* remmina
* scribus
* sourcextractor++

In Python 3.13, I also proposed [PEP 741 – Python Configuration C API](https://peps.python.org/pep-0741/) but it's still a draft.

### Linked PRs
* gh-117993

**Comment by encukou** [comment]
Thank you! Every bit helps.
