### ISSUE TITLE
Rename 'open' function in the 'webpage' library

### ISSUE THREAD

**Issue by Adem-Kurt** [python/cpython#117911]
# Feature or enhancement

### Proposal:

The name of the `open` function in the `webbrowser` library should be changed because the `open` function is a built-in function in Python.

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
Thank you for the suggestion. But there's no conflict between the two names, and changing webbrowser would needlessly break existing code. I'm going to close this.
