### ISSUE TITLE
C API: Restore removed PyEval_InitThreads() function

### ISSUE THREAD

**Issue by vstinner** [python/cpython#117929]
Since Python 3.7, PyEval_InitThreads() does nothing, since the GIL is now always created: https://vstinner.github.io/python37-gil-change.html This function is deprecated since Python 3.9 and I removed it in Python 3.13 alpha1.

Problem: my Fedora team identified that 16 projects are affected by this function removal.

* collectd
* freeradius
* gnumeric
* libesedb
* libsigrokdecode
* OpenIPMI
* openscap
* profanity
* pyliblo
* pyotherside
* python-confluent-kafka
* python-cradox
* python-gphoto2
* python-simpleaudio
* python-subvertpy
* rb_libtorrent

I propose to restore the function in Python 3.13 beta1, and remove it again in Python 3.14 alpha1.

### Linked PRs
* gh-117931

**Comment by vstinner** [comment]
collectd doesn't seem to be affected for 3 years: https://github.com/collectd/collectd/commit/17d2fbe443b656bb0f74c204eb003cea22f94e60

```c
#if PY_VERSION_HEX < 0x03090000
  // deprecated. Called by Py_Initialize(). Removed in Py3.11
  // https://docs.python.org/3/c-api/init.html#c.PyEval_InitThreads
  PyEval_InitThreads();
#else
  Py_Initialize();
#endif
```

**Comment by vstinner** [comment]
gnumeric was fixed 4 months ago: https://gitlab.gnome.org/GNOME/gnumeric/-/commit/015de3d0df1d59e62e5bfeabab31834082b81196

**Comment by vstinner** [comment]
pyotherside: I proposed a fix, https://github.com/thp/pyotherside/pull/132/files

**Comment by corona10** [comment]
python-confluent-kafka: https://github.com/confluentinc/confluent-kafka-python/blob/5a87879681d28375a55203c4839338b13b668046/src/confluent_kafka/src/confluent_kafka.c#L3023-L3025
