### ISSUE TITLE
Increase minimum supported Sphinx to 6.2.1

### ISSUE THREAD

**Issue by hugovk** [python/cpython#117928]
# Documentation

Python 3.11 is now [only receiving security updates](https://devguide.python.org/versions/), so it's time to review the minimum Sphinx version user for 3.12+. We won't change the minimum for the 3.11 branch.

Using the same survey as https://github.com/python/cpython/issues/109209#issuecomment-1713859051:

Distro | CPython | Sphinx
-- | --: | --:
_Debian 12 Bookworm_ | _3.11.2_ | _5.3.0_
_Debian 13 Trixie (testing)_ | _3.11.6_ | _7.2.6_
_Debian Sid (unstable)_ | _3.11.8_ | _7.2.6_
Debian (experimental) | 3.12.1 | n/a
Fedora 39 | 3.12.2 | 6.2.1
Fedora 40 | 3.12.2 | 7.2.6
Fedora rawhide | 3.12.3 | 7.2.6
Gentoo | n/a | n/a
openSUSE Leap |   | 7.2.6
openSUSE Tumbleweed |   | 7.2.6
RHEL | n/a | n/a
**_Minimum Sphinx version for 3.12_** | **_3.12_** | **_6.2.1_**

References:

* https://packages.debian.org/sid/python3
* https://packages.debian.org/sid/python3-sphinx
* https://packages.fedoraproject.org/pkgs/python3.12/python3/
* https://packages.fedoraproject.org/pkgs/python-sphinx/python3-sphinx/
* https://software.opensuse.org/package/python-Sphinx

cc:
* @mitya57 / Debian
* @hroncok / Fedora / RHEL
* @mgorny / Gentoo
* @danigm / openSUSE
* @AA-Turner / CPython

* #117853

### Linked PRs
* gh-118321
* gh-121986
* gh-121993
* gh-121994

**Comment by hroncok** [comment]
Fedora: 6.2.1 is good enough for 3.12+

**Comment by danigm** [comment]
For openSUSE we're using right now:

 * Sphinx 7.2.6 to build cpython in Tumbleweed
 * Sphinx 4.2.0 to build cpython in Leap

cc @mcepl

**Comment by hugovk** [comment]
What Python version do you have in Leap? Is it still 3.6 as a base, and you can install newer versions as additional modules?

When do you plan to upgrade Sphinx in Leap? 

Sphinx 4.2.0 is ~3 years old: https://pypi.org/project/Sphinx/4.2.0/

**Comment by danigm** [comment]
> What Python version do you have in Leap? Is it still 3.6 as a base, and you can install newer versions as additional modules?
> 
> When do you plan to upgrade Sphinx in Leap?
> 
> Sphinx 4.2.0 is ~3 years old: https://pypi.org/project/Sphinx/4.2.0/

We've also python 3.11 in Leap, right now it's building using sphinx-build provided by Sphinx `4.2.0`, using the python 3.6 interpreter, but we've also the 3.11 version, that's `7.2.6`. So for future releases we can just use this modern version of Sphinx to build the python interpreter documentation.

So in this specific case, you can forget about the old 4.2.0 version and it should be okay to set the minimum supported Sphinx to 6.2.1. Shouldn't be a problem in openSUSE.

**Comment by mcepl** [comment]
> What Python version do you have in Leap? Is it still 3.6 as a base, and you can install newer versions as additional modules?

Python 3.6 will be main Python in SLE-15 for the length of the system support. However, we have also Python 3.11 in a separate additional module for the system. I am not sure whether we can use 3.11 for building of the base system packages, and certainly we would be patching documentation for long time to make it working with our base Python-3.6-based Sphinx.

> When do you plan to upgrade Sphinx in Leap?

Unless we manage to make something more recent working with Python 3.6, there will be basic Sphinx version 2.3.1, in the additional module we have 7.2.6, and it can be updated anytime.

**Comment by hugovk** [comment]
Thanks, sounds good, and we'll keep Sphinx 4.2.0 for the 3.11 branch.
