### ISSUE TITLE
Add `dir_fd` to `os.path.lexists()` & `os.path.isdir()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#117967]
# Feature or enhancement

### Proposal:

`glob` currently needs its own implementation of `os.path.lexists()` & `os.path.isdir()` to support `dir_fd`:

https://github.com/python/cpython/blob/f74e51229c83e3265f905dc15283bfe0ec1a659e/Lib/glob.py#L201-L222

We could refactor this by adding `dir_fd` to `os.path.lexists()` & `os.path.isdir()`:

```diff
-def lexists(path):
+def lexists(path, *, dir_fd: int | None = None):
     """Test whether a path exists.  Returns True for broken symbolic links"""
     try:
-        os.lstat(path)
+        os.lstat(path, dir_fd=dir_fd)
     except (OSError, ValueError):
         return False
     return True
```

```diff
-def isdir(s):
+def isdir(s, *, dir_fd: int | None = None):
     """Return true if the pathname refers to an existing directory."""
     try:
-        st = os.stat(s)
+        st = os.stat(s, dir_fd=dir_fd)
     except (OSError, ValueError):
         return False
     return stat.S_ISDIR(st.st_mode)
```

*Note: `nt._path_isdir()` (& `nt._path_lexists()` when #117842 lands) need to raise an error for this.*

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by nineteendo** [comment]
cc @serhiy-storchaka before I start implementing this: is this something you would support?

**Comment by serhiy-storchaka** [comment]
It is trivially implemented via `os.stat`. `glob` implements private helpers for historical reasons -- they should behave exactly like `os.path` versions.

If there will be other uses of such functions in several different places, it will be worth to add this feature.

**Comment by nineteendo** [comment]
@barneygale, do you think this can speed things up? It could also be used for #117737.

**Comment by barneygale** [comment]
I don't feel strongly about it. I note it would be the first `os.path` function to accept `dir_fd`.

**Comment by nineteendo** [comment]
> The builtin `_path_*` functions on Windows would have to be modified to raise `NotImplementedError` if the new `dir_fd` argument isn't `None`.

I see, I assumed Windows supported it too. Then it can only be used for refactoring `glob`.

> I note it would be the first `os.path` function to accept `dir_fd`.

At the moment it only seems to be needed for `glob`, so I'll leave it up to serhiy to decide.

**Comment by nineteendo** [comment]
I'm closing this as there's not much support. Feel free to re-open when you change your mind.
