### ISSUE TITLE
Adding support for file paths as arguments to pickle.load and pickle.dump

### ISSUE THREAD

**Issue by DevBhuyan** [python/cpython#117946]
# Feature or enhancement

### Proposal:

As a developer working with Python and Machine Learning, I have been using the pickle library for a long time to save objects. While the library provides a convenient way to store and retrieve Python objects, I've noticed a small improvement that could enhance the user experience and make our lives a bit easier.

Currently, when using `pickle.load` or `pickle.dump`, we need to explicitly open the file and pass the file object to these functions. For example:

```python
with open(file_path, 'wb') as file:
    pickle.dump(obj, file)
```
This approach works fine, but it requires writing the with statement and manually opening the file every time we want to load or dump objects. It would be more convenient and intuitive if the pickle.load and pickle.dump functions could directly accept file paths as arguments, in addition to file objects.

With this feature, users would have the option to provide either a file object or a file path string. If a file path is provided, the library would internally open the file in the appropriate mode (`rb` for loading and `wb` for dumping), perform the serialization or deserialization, and then close the file automatically.

Here's an example of how the updated usage would look like:
```python
# Dumping an object
pickle.dump(obj, 'data.pkl')

# Loading an object
loaded_obj = pickle.load('data.pkl')
```

I believe this small improvement would be beneficial to the Python community, especially for those who frequently use the pickle library. It would save a few lines of code and provide a more intuitive and convenient way to work with pickled objects.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-117949

**Comment by ericvsmith** [comment]
I'm opposed to adding more APIs that change their behavior based on the type of a parameter. You could always write a wrapper to provide the functionality you're after. I think this enhancement request should first be discussed on discuss.python.org.

**Comment by nineteendo** [comment]
This still needs to be closed.

**Comment by DevBhuyan** [comment]
Sure thing @ericvsmith. I've created a post on discuss.python.org and referenced this issue. Thanks for the suggestion, will keep this in mind next time. Have a nice day!
