### ISSUE TITLE
Maybe add a first() function to python?

### ISSUE THREAD

**Issue by Unknownuserfrommars** [python/cpython#117984]
# Feature or enhancement

### Proposal:

I suggest adding a first() function to lists, dictionaries, sets and other iterable objects that can return the first value of objects.
I know there are other ways, like next(iter()) or operator.itemgetter(0) or even just [0] (for lists and tuples). But this is not convenient enough (for me).
The first() function works like this:
1. input an iterable object
2. return the first value of the object
so, for example:
```py
my_list = [1,2,3,4,5]
print(first(my_list)) # This would give 1
my_set = {2,4,6,8,10}
print(first(my_set)) # This would give 2
my_dict = {'a':1, 'b':2}
print(first(my_dict)) # This would give a list ['a', 1]
```
The first() function can be stacked inside another first() function.
eg:
```py
# We'll still take the my_dict example from above
print(first(first(my_dict))) # This would give 'a'
```

It should be implemented as a nice break for people not wanting to type so much.

**Possible future features**
1. Supports more third-party types
2. Can be added as a method
eg:
```py
# We'll use the my_list example from above
print(my_list.first()) # This will also print 1, same effect as print(first(my_list))
```
*IMPORTANT NOTE*
When added as a Pandas method, add in the parameters `axis`, and maybe even `drop` to drop unwanted cols/rows in the output!

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ericvsmith** [comment]
Thank you for your suggest, @Unknownuserfrommars. For enhancements, please open a discussion on discuss.python.org and reference this issue there. I'm certain this issue has been discussed before, it would be good if you could find previous discussions and address any objections they had.

I'm going to close this, but it can always be re-opened.
