### ISSUE TITLE
`dataclasses`: 3.12.3 regression with `weakref_slot`

### ISSUE THREAD

**Issue by francis-clairicia** [python/cpython#118033]
# Bug report

### Bug description:

The `__weakref__` slot is not set for classes that have a `Generic[T]` base.

```python
from typing import Generic, TypeVar
from dataclasses import dataclass

T = TypeVar("T")

@dataclass(slots=True, weakref_slot=True)
class Token(Generic[T]):
    ctx: T

print(f"{Token.__slots__=!r}")
print(f"{hasattr(Token, '__weakref__')=}")
```

Output on 3.12.2:
```
Token.__slots__=('ctx', '__weakref__')
hasattr(Token, '__weakref__')=True
```

On 3.12.3:
```
Token.__slots__=('ctx',)
hasattr(Token, '__weakref__')=False
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-118099
* gh-118821
* gh-118822

**Comment by Eclips4** [comment]
Bisected to a22d05f04c074dbb4f71e7837f54c0bb693db75d.
Reproducible on current 3.12 branch.

**Comment by sobolevn** [comment]
Let's close this issue. I opened a new one for @carljm's suggestion about `__slots__` on C types. See https://github.com/python/cpython/pull/118099#discussion_r1575244611

**Comment by sobolevn** [comment]
https://github.com/python/cpython/issues/118829
