### ISSUE TITLE
Unittest not being found 

### ISSUE THREAD

**Issue by kalebers** [python/cpython#118028]
Hello,

I'm having a weird issue with Unittest. Since it's part of the main library, should work just importing the module. 

Although even I'm importing Unittest, I can't find any declaration or call any of it's functions, as the screenshot shows:
![image](https://github.com/python/cpython/assets/39911310/f9a5045d-9fde-4de7-8ab9-2c2531bd943f)

Thought it would be an issue with the latest version (3.12, not using the pre release). I installed versions 3.11 and 3.10, but still having the same issue. 

Any suggestions that may help fix the issue?

**Comment by Eclips4** [comment]
Hello!
Seems your problem is related to vscode extensions.
This repository is intended as CPython bug tracker, pleas ask for help for python-related questions there: https://discuss.python.org/c/users/7.
