### ISSUE TITLE
Add option for hidden command line arguments to argparse

### ISSUE THREAD

**Issue by mbUSC** [python/cpython#118057]
# Feature or enhancement

### Proposal:

Sometimes you don't want certain command line options (e.g. debug options) to show up in the user's help menu.

Proposal is to add a parameter `hidden=True` to `add_argument` to prevent this:
```
parser.add_argument('--debug-foo',
                         hidden=True,
                         action='store_true',
                         help='Print debug info for component foo')
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by zware** [comment]
This already exists, spelled `parser.add_argument(..., help=argparse.SUPPRESS)`.

Guido's time machine strikes again :)
