### ISSUE TITLE
_pydecimal.Decimal.__pow__ tries to compute 10**1000000000000000000 and thus doesn't terminate

### ISSUE THREAD

**Issue by cfbolz** [python/cpython#118027]
# Bug report

### Bug description:

`decimal.Decimal(2) ** 117` does not terminate when using the pure Python implementation `_pydecimal.py` of the `decimal` module, and setting the precision to `MAX_PREC`:

```python
import sys
if len(sys.argv) > 1 and sys.argv[1] == "pydecimal":
    # block _decimal
    sys.modules['_decimal'] = None

import decimal

with decimal.localcontext() as ctx:
    ctx.prec = decimal.MAX_PREC
    ctx.Emax = decimal.MAX_EMAX
    ctx.Emin = decimal.MIN_EMIN
    ctx.traps[decimal.Inexact] = 1
    D2 = decimal.Decimal(2)
    res = D2 ** 117
    print(res)
```

this behaves as follows:

```
./python decbug.py # instant
166153499473114484112975882535043072
$ ./python decbug.py pydecimal # hangs
^CTraceback (most recent call last):
  File "/home/cfbolz/projects/cpython/decbug.py", line 14, in <module>
    res = D2 ** 117
          ~~~^^~~~~
  File "/home/cfbolz/projects/cpython/Lib/_pydecimal.py", line 2436, in __pow__
    ans = self._power_exact(other, context.prec + 1)
          ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/cfbolz/projects/cpython/Lib/_pydecimal.py", line 2284, in _power_exact
    if xc > 10**p:
            ~~^^~
KeyboardInterrupt
```

The bug happens because `p` is the precision + 1 in the last traceback entry. `MAX_PREC = 999999999999999999` on 64-bit systems. Therefore the the [code in `_power_exact`](https://github.com/python/cpython/blob/6078f2033ea15a16cf52fe8d644a95a3be72d2e3/Lib/_pydecimal.py#L2187) tries to compute `10**1000000000000000000`, which obviously won't work.

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-118503

**Comment by nineteendo** [comment]
Hmm, it already takes too long for `ctx.prec = 999_999_999`. You don't need to set the value that high.

**Comment by cfbolz** [comment]
I disagree. The pure python implementation is plenty fast enough for a lot of purposes (it's in fact the default implementation in PyPy). And the result of 2**117 is not a very large number. So doing this computation should be instant and not defend on whether the precision is big or totally unreasonably big.

All we need to do is fix the logic in `_power_exact` somehow.

**Comment by nineteendo** [comment]
Hmm, can't we use `math.log10()` instead?

**Comment by nineteendo** [comment]
Someone will have to find another workaround.

**Comment by eendebakpt** [comment]
We could use log10 to filter out the extreme cases:
```
-if xc > 10**p:
+if (log10(xc) > p - 5) or xc > 10**p:
```
(the value 5 could probably be picked better, but it should be high enough to make this robust for any rounding errors)

Not a very elegant solution, so I will try to find a better approach

**Comment by eendebakpt** [comment]
We can check how the c implementation handles this case and adopt a similar strategy.

**Comment by tim-one** [comment]
A few lines down we have:

```python
        str_xc = str(xc)
```

So we could move that up, and change the test to:

```python
        if len(str_sc) > p:
```

The downside is that if `xc` is very large, conversion to string is expsnive. But `str(2)` is pretty fast ;-)

**Comment by eendebakpt** [comment]
I like the suggestion by @tim-one. If performance is a concern, we can create a simple lru cache (`str(xc)` might be big and expensive, but `len(str(xc))` ends up in the cache, so the cache will be very small)

**Comment by serhiy-storchaka** [comment]
A few lines above we have `m > p*100//_log10_lb(xc)`. It is the same condition (after transforming `xc`), but more exact. We perhaps can remove it or replace it with a post-conversion check, but then we will fall in other problem: https://github.com/python/cpython/issues/118164#issuecomment-2072259709.

**Comment by eendebakpt** [comment]
> A few lines down we have:
> 
> ```python
>         str_xc = str(xc)
> ```
> 
> So we could move that up, and change the test to:
> 
> ```python
>         if len(str_sc) > p:
> ```
> 
> The downside is that if `xc` is very large, conversion to string is expsnive. But `str(2)` is pretty fast ;-)

@tim-one Your test is not completely equivalent. For `p=2` and `xc=100` we have `len(str_xc) > p` true, but `xc > 10**p` false. Maybe this condition can never be reached because of the checks before, but that is not immediately clear to me. I checked the tests in test_decimal and there a no tests that covers the difference between the two tests above.

A pragmatic solution could be to modify the test to `len(str(xc-1)) > p`, but that is a bit slower because now both `str(xc)` and `str(xc-1)` have to be calculated.

**Comment by tim-one** [comment]
Yes, a positive int is representable with `p` digits in decimal floating-point iff its decimal string representation has no more than `p` digits, _or_ the string matches the regular expression `r"^10*$"`. There are many ways to code the latter test, but actually using `re` for it would still be approximately infinitely :wink: faster than computing `10**p` . Alternatives include obscurities like (untested):

```python
(len(sc) > p
 and sc.startswith('1')
 and all(ch == '0' for ch in islice(sc, 1, None)))
```

**Comment by tim-one** [comment]
But ... later code can change `xc` again in various ways, so maybe it can become 1 again. This code gives me a headache :wink:. My


... has no more than `p` digits, or the string matches the regular expression `r"^10*$"`


should be bulletproof regardless. Note too that there's another instance of the problematic `10**p` much earlier in the code:

```python
            if xc >= 10**p:
                return None
            xe = -e-xe
            return _dec_from_triple(0, str(xc), xe)
```

and again shortly followed by a `str(xc)`. 

My guess is the when code reaches either of these blocks, `xc` will almost always *be* representable, so the "early-out" test isn't actually saving any expense (the early-out test will fail, and we'll go on to compute the string anyway).

In the context of this function's use in CPython's int -> str conversion, there's no question about that: _all_ early-out tests in this function will fail, because int -> str conversion only ever asks for exactly representable powers.

**Comment by tim-one** [comment]
Oops! I put this comment on the other report instead. Here again:

Another possibility to address the immediate problem. This is untested, but I know the code well. In `_pylong.py`, just change
```python
                result = D2**w
```
to
```python
                result = D(1 << w)
```
Then the decimal `__pow__() ` won't be called at all. It may even be faster that way under the C decimal implementation too, although not enough so to matter in this context. `w` in the above is always "small".

**Comment by serhiy-storchaka** [comment]
There are many ways to check that `xc` is exactly `10**p`. For example, `str(xc) == '1' + '0' * p`. But this use case is not currently covered by tests, so if we make an error in the check code (for example remove it as a dead code), the tests will still pass. I am not even sure that it is not a dead code, that `xc` can be exactly `10**p` at this point.

**Comment by tim-one** [comment]
> We can check how the c implementation handles this case and adopt a similar strategy.

Heh. Stefan Krah (`libmpdec`'s author) was using `_pydecimal.py` to prototype an exact-power implementation. I downloaded the current source for `libmpdec` today, and this is its implementation of "exact power" (from `libmpdec\mpdecimal.c`):

```c
/*
 * TODO: Implement algorithm for computing exact powers from decimal.py.
 * In order to prevent infinite loops, this has to be called before
 * using Ziv's strategy for correct rounding.
 */
static int
_mpd_qpow_exact(mpd_t *result, const mpd_t *base, const mpd_t *exp,
                const mpd_context_t *ctx, uint32_t *status)
{
    return 0;
}
```

So "similar strategy" would be to comment out Python's exact-power function and never call it 🤣 

Which holds some attraction for me - but carries risk of changing results in some cases.

**Comment by tim-one** [comment]
Current `main` branch no longer tries to compute `10**p`, so closing this issue.
