### ISSUE TITLE
random.choice(dict_object)

### ISSUE THREAD

**Issue by RafaCabrera** [python/cpython#118075]
# Bug report

### Bug description:

```python
print("Choice dict:", random.choice({1:'a', 2:'b', 3:'c', 4:'d', 5:'e', 6:'f'}))
```
It runs perfectly sometimes and returns a value from the dictionary (>Choice dict:  a), but sometimes it crashes:

```
Traceback (most recent call last):
  File "/Users/.../pruebas.py", line 50, in <module>
    print("Choice dict:", random.choice({1:'a', 2:'b', 3:'c', 4:'d', 5:'e', 6:'f'}))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/random.py", line 374, in choice
    return seq[self._randbelow(len(seq))]
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 0
```

Regards.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by tim-one** [comment]
As the docs say, `choice()` works on "sequence types" (like., e.g., list, tuple, array.array, ..._). A dict is not a sequence type. But "duck typing" can make it _appear_ to be: it does support `len()`, and indexing. In fact, if the keys of a dict `d` are all and only the ints in `range(len(d))`, _everything_ `random.choice()` does will always work fine.

Python generally doesn't do explicit type checking in heavily called functions (like `choice()`), so I expect you'll just need to learn to live with this.

**Comment by RafaCabrera** [comment]
> As the docs say, `choice()` works on "sequence types" (like., e.g., list, tuple, array.array, ..._). A dict is not a sequence type. But "duck typing" can make it _appear_ to be: it does support `len()`, and indexing. In fact, if the keys of a dict `d` are all and only the ints in `range(len(d))`, _everything_ `random.choice()` does will always work fine.
> 
> Python generally doesn't do explicit type checking in heavily called functions (like `choice()`), so I expect you'll just need to learn to live with this.

I can live with this, don't worry, there are more important things in life than Python botches
