### ISSUE TITLE
Python 3.x fails to load a .so file in TCL through tkinter

### ISSUE THREAD

**Issue by vatsamail** [python/cpython#118049]
# Bug report

### Bug description:

Python 3.x (3.9.7) is giving the following error if I try to load a shared object TCL file. If I run manually it works.

Manual method:

```
shell> tclsh
%load blah.so
%cmd_in_blah
```

Python method:

```
from tkinter import *
tcl = Tcl()
ret = tcl.eval("load blah.so")
```
Gives an error here >>>:

```
*** Error in `python': free(): invalid pointer: 0x00002ae034fc8d00 ***
Abort
```
Please help. Thanks in Advance.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by terryjreedy** [comment]
Duplicated by #118051.
