### ISSUE TITLE
[feature request] pathlib.Path().asyncopen

### ISSUE THREAD

**Issue by gmankab** [python/cpython#118066]
# Feature or enhancement

### Proposal:

so, there is a pathlib in python, with very convenient method Path().open(), but it works only synchronously

and there is [aiofiles](https://pypi.org/project/aiofiles) lib that allows to open files asynchronously

can you please add a way to open files asyncronously in pathlib

for example:

```python
from pathlib import Path

async def main():
    myfile = Path('myfile')
    async with myfile.asyncopen('r') as file:
        print(await file.read())
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by nineteendo** [comment]
I suggest you close this issue and first discuss this on Discourse: https://discuss.python.org/c/ideas/6.
If you get support there, it can always be re-opened.

**Comment by Eclips4** [comment]
As @nineteendo said: this should firstly be discussed on Discourse.
