### ISSUE TITLE
float('inf') faster ways

### ISSUE THREAD

**Issue by alex77g2** [python/cpython#118045]
# Feature or enhancement

### Proposal:

The default way to set float variables to infinity is `float('inf')`, which is a very slow function call.
Another popular way is `math.inf`, which is much faster (7.5 times), but still involves an import and an internal LOAD_ATTR.
Using a number > FLOAT64_MAX is fastest way (and not documented), `a=1e999` (>1.8e+308).
`1e999 == float('inf')` is True. (factor 2 speed improvement if assignment `a=` is taken out.
IEEE 754-1985 specifies: 1.0/0.0==inf, 0.0/0.0=nan, but Python gives "ZeroDivisionError: float division by zero".

Summary: the fastest way is neither documented nor identical (each user could choose other large numbers, making code less comparable. And even Python is investing in performance, some low hanging fruits are ignored.
My suggestion: creating a zero-cost official number (or shortcut) for +inf, -inf, nan (e.g. following IEEE-spec like C). Python-interpreter simplifies (2.0+1.0) to 3.0 (at compile time), but 1.0/0.0 becomes a real BINARY_OP(/) at runtime (and causes a crash).
And mention the fastest way in documentaion.

A comparision script is below.
```python
echo "Speed Test Float 2024 (Windows+Linux)"
echo off
python --version
echo "float('inf') is slow .."
python -m timeit -s "import math;a=1.1" "a=float('inf')"
echo "math.inf is faster .."
python -m timeit -s "import math;a=1.1" "a=math.inf"
echo "1e999=inf is fastest .."
python -m timeit -s "import math;a=1.1" "a=1e999"
python -c "print('inf =', 1e999, 1e999==float('inf'))"
python -c "# print('inf =', 1.0/0.0) # crash vs. IEEE 754-1985 : 1.0/0.0==inf, 0.0/0.0=NaN"
echo "Test done."
pause
exit

Python 3.11.9
"float('inf') is slow .."
2000000 loops, best of 5: 182 nsec per loop
"math.inf is faster .."
10000000 loops, best of 5: 24.3 nsec per loop
"1e999=inf is fastest .."
20000000 loops, best of 5: 11.9 nsec per loop
inf = inf True
"Test done."

```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

https://www.quora.com/Which-literal-to-represent-infinity-is-faster-in-Python-1e309-math-inf-or-float-inf

**Comment by JelleZijlstra** [comment]
You missed the fastest way: `from math import inf`.

```
% python -m timeit -s "from math import inf; import math;a=1.1" "a=inf"  
50000000 loops, best of 5: 4.73 nsec per loop
% python -m timeit -s "from math import inf; import math;a=1.1" "a=1e999"
50000000 loops, best of 5: 5.92 nsec per loop
% python -m timeit -s "from math import inf; import math;a=1.1" "a=float('inf')"
10000000 loops, best of 5: 37 nsec per loop
% python -m timeit -s "from math import inf; import math;a=1.1" "a=math.inf"    
50000000 loops, best of 5: 7.28 nsec per loop
```

**Comment by nineteendo** [comment]
You can indeed just import the constants from `math` (or `cmath` if you need the imaginary versions):

```python
from cmath import inf, infj, nan, nanj
```

If you need negative infinity, that's a bit slower though (but I would focus on readibility):

```powershell
PS C:\Users\wanne\cpython> python -m timeit "a = float('-inf')"
>> python -m timeit -s "import math" "a = -math.inf"
>> python -m timeit -s "from math import inf" "a = -inf"
>> python -m timeit "a = -1e999"
2000000 loops, best of 5: 126 nsec per loop
10000000 loops, best of 5: 23.7 nsec per loop
20000000 loops, best of 5: 19.6 nsec per loop
20000000 loops, best of 5: 14.7 nsec per loop
```

**Comment by alex77g2** [comment]
Thanks. I was not aware that `import a from b` is different in performance than `b.a`.
But why we follow IEEE for "3.0/4.0" but not for "1.0/0.0" ?
It might be named a breaking change, but behavioral it would be a fixing change, that is not breaking anything existing.

**Comment by nineteendo** [comment]
It's breaking, many people rely on it:
https://github.com/search?q=%22except+ZeroDivisionError%22+language%3APython&type=code

**Comment by nineteendo** [comment]
I suggest you close this as not planned.

**Comment by alex77g2** [comment]
Ok, but one last question: change on compile time only would be possible?

**Comment by nineteendo** [comment]
Yeah, but it would be inconsistent (and less readable):

```python
ONE = 1
ZERO = 0
inf = 1 / 0  # OK
inf = ONE / ZERO  # NOK
```

**Comment by JelleZijlstra** [comment]
The reason `from math import inf; inf` is faster than `import math; math.inf` is that they compile to different code.

```
>>> dis.dis("from math import inf; a=inf")
  0           RESUME                   0

  1           LOAD_CONST               0 (0)
              LOAD_CONST               1 (('inf',))
              IMPORT_NAME              0 (math)
              IMPORT_FROM              1 (inf)
              STORE_NAME               1 (inf)
              POP_TOP
              LOAD_NAME                1 (inf)
              STORE_NAME               2 (a)
              RETURN_CONST             2 (None)
>>> dis.dis("import math; a=math.inf")
  0           RESUME                   0

  1           LOAD_CONST               0 (0)
              LOAD_CONST               1 (None)
              IMPORT_NAME              0 (math)
              STORE_NAME               0 (math)
              LOAD_NAME                0 (math)
              LOAD_ATTR                2 (inf)
              STORE_NAME               2 (a)
              RETURN_CONST             1 (None)
```

The first variant stores the name `inf` in the global namespace. Looking it up later is then just a single LOAD_NAME instruction. Conceptually, this does a dict lookup in the globals dictionary, but various forms of caching make it faster than a straight lookup.

The second variant, `math.inf`, has to first look up `math` in the globals (yielding a module object), then load the `inf` attribute, another dict lookup. There are again some optimization that make this faster, but at the end of the day it still does more work.

**Comment by pochmann3** [comment]
> dict lookup in the globals dictionary

Not if you import it inside a function, like `timeit` does in those examples.
