### ISSUE TITLE
Performance difference of C calling conventions

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118043]
# Documentation

The performance difference of these calling conventions is undocumented:

- [METH_VARARGS](https://docs.python.org/3/c-api/structures.html#c.METH_VARARGS)
- [METH_FASTCALL](https://docs.python.org/3/c-api/structures.html#c.METH_FASTCALL)
- [METH_O](https://docs.python.org/3/c-api/structures.html#c.METH_O)
- [METH_NOARGS](https://docs.python.org/3/c-api/structures.html#c.METH_NOARGS)

You would expect that `METH_FASTCALL` is faster than `METH_VARARGS`, but for `METH_O` & `METH_NOARGS` it isn't so clear.

**Comment by encukou** [comment]
We don't guarantee the relative performance of these calling conventions. Additionally, the performance also depends on the caller, not just the called function.

If this matters to you, you should experiment and measure the variants for your own use case, and for a particular build of Python.

I'll close the issue in a week if there are no objections.
