### ISSUE TITLE
[Breakage]: PyObject_New (aka _PyObject_New) no longer seems to call tp_new object slots automatically anymore.

### ISSUE THREAD

**Issue by AraHaan** [python/cpython#118096]
# Bug report

### Bug description:

I developed a C extension in the past that used to work for Python 3.9~3.11.4 without issues or crashes. Then After 3.11.9 and 3.12.0 all the way to the latest release of 3.12 I noticed that my call to ``self->async_task = (PyObject*)PyObject_New(AsyncExecutorTask, &PyAsyncExecutorTaskObject);`` no longer would automatically call the ``tp_new`` slot in ``PyAsyncExecutorTaskObject`` which is a hidden object member within my C extension code that I created a year ago. As such it puts my object into bad state and when I debug the ``start`` function right on it's ``Py_RETURN_NONE`` would be rerun automatically after it should have returned, this is fine until it gets to that objects ``tp_dealloc`` member function that it then crashes python with an access violation after it properly frees it's member objects (a few PyObject *'s). Somehow it seems to AV when it tries to rerun this statement at the end of it's dealloc function: ``Py_TYPE(self)->tp_free((PyObject*)self);``. Most likely this is due to this problem where ``tp_new`` on that object itself is getting skipped from being called which then results in ``tp_alloc`` on it not being called which results in the access violation that I face in my code.

Gist with simplified code that *should* reproduce this problem: https://gist.github.com/AraHaan/6746d7e91c9c3f54e3fc446c601da698 (gist also includes a test python script to debug the code in VS2022 using the Python Tools workload).

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Windows

**Comment by AraHaan** [comment]
Yep I have verified this IS the case. The fix I managed to come up with so far (feels like a hack) is to add this to my ``defines.h``

```c
static inline PyObject *_PyObject_New_FIXED(PyTypeObject *type)
{
  return type->tp_new(Py_TYPE(_PyObject_New(type)), Py_None, Py_None);
}

#define PyObject_New_FIXED(type, typeobj) ((type *)_PyObject_New_FIXED(typeobj))
```
And then change this line from:
```c
self->async_task = (PyObject*)PyObject_New(AsyncExecutorTask, &PyAsyncExecutorTaskObject);
```
to: 
```c
self->async_task = (PyObject*)PyObject_New_FIXED(AsyncExecutorTask, &PyAsyncExecutorTaskObject);
```

**Comment by colesbury** [comment]
`PyObject_New` did not call `tp_new` slot in 3.9-3.11 either. I don't think it ever called `tp_new`. This is from the 3.9 branch:

https://github.com/python/cpython/blob/882f62bd93fcd5775068c3b3d1e5ce62f2feaba3/Objects/object.c#L162-L171

https://github.com/python/cpython/blob/882f62bd93fcd5775068c3b3d1e5ce62f2feaba3/Include/objimpl.h#L125

**Comment by encukou** [comment]
You can call `PyObject_New` when implementing allocation for your custom objects.
To properly create an object of some type, [call the type](https://docs.python.org/3/c-api/call.html#object-calling-api), as in Python.

**Comment by jkloth** [comment]
Your gist shows that you are doing what amounts to a double free on your task object at [include\AsyncExecutorTask.h:86](https://gist.github.com/AraHaan/6746d7e91c9c3f54e3fc446c601da698#file-include-asyncexecutortask-h-L86).  The `N` format code consumes a reference to the task object while building the args tuple so there is no need for the following `Py_XDECREF` of the task object.

**Comment by AraHaan** [comment]
Ah yeah that is right, ``N`` format code tells it to steal the reference.

**Comment by jkloth** [comment]
With that fixed, your access violation should vanish.  Whilst `tp_new` was never being called, you were basically just *getting lucky* that this error had not occurred before.  This does mean that the given problem is not with Python, however.  

For resolving the initialization problem, as @encukou noted, is to create an instance using the type directly.    To create an object that calls the `tp_new`/`tp_init` slots, call the type directly as `PyObject_CallFunction(type, "O", arg)` or similar.

**Comment by AraHaan** [comment]
I tested it with ``PyObject_CallFunction`` however this is the result: ``TypeError: '_background_tasks.AsyncExecutorTask' object is not callable``.

**Comment by encukou** [comment]
Sorry for the delay.
That's an error you'd get when calling an instance of the `AsyncExecutorTask` type, rather than the `AsyncExecutorTask` type itself.

**Comment by picnixz** [comment]
I'm closing this one as `not an issue` considering Sam and Petr's answers and the fact that the OP managed to solve their issue.
