### ISSUE TITLE
PDB reports incorrect line numbers/trace on crash

### ISSUE THREAD

**Issue by profPlum** [python/cpython#118071]
# Bug report

### Bug description:

PDB gives incorrect stack trace & line numbers when it crashes. Almost always it will say that the file crashed on the very first line, which obviously isn't true. The bug can be reproduced in pure python.

Save the code below as `test.py`

```python
import pickle

with open('blah', 'w') as f:
    f.write('')

with open('blah', 'rb') as f:
    pickle.load(f)
```

Then run with `python -m pdb test.py`, hit continue and you will get this output:

<img width="561" alt="image" src="https://github.com/python/cpython/assets/4739054/eb90ab48-267f-42a5-8009-94c5f3891e30">

**This stack trace is incorrect because it says: `File "/Users/dwyerdeighan/Downloads/test.py", line 1, in <module>`**
Whereas if you single step through the file it will report the correct line number of the crash (the `pickle.load(f)` line).

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux, macOS

**Comment by gaogaotiantian** [comment]
The stack trace shows that the first line of your program is `import os`, but the first line of the program you gave is `import pickle`, so there must be some inconsistency there. Could you double check the example you gave?

**Comment by gaogaotiantian** [comment]
I tried to reproduce with the program you gave. 3.9 does have this issue. However, 3.9 is in security fix only. It works correctly on both 3.12 and 3.13(main), so there's nothing we will do here. Let me know if you have more questions.

**Comment by nineteendo** [comment]
I think we can close this now.
