### ISSUE TITLE
test_posixpath: test_expanduser_pwd2() fails on AMD64 Ubuntu Shared 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#118060]
Example of recent failure: https://buildbot.python.org/all/#/builders/506/builds/7698

```
FAIL: test_expanduser_pwd2 (test.test_posixpath.PosixPathTest.test_expanduser_pwd2)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/srv/buildbot/buildarea/3.x.bolen-ubuntu/build/Lib/test/test_posixpath.py", line 354, in test_expanduser_pwd2
    self.assertEqual(posixpath.expanduser('~' + name), home)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: '/var/lib/lxd' != '/var/lib/lxd/'
- /var/lib/lxd
+ /var/lib/lxd/
?             +
```

* Latest successful build: https://buildbot.python.org/all/#/builders/506/builds/7683
* First failing build: https://buildbot.python.org/all/#/builders/506/builds/7684

### Linked PRs
* gh-118061

**Comment by vstinner** [comment]
The test was added by commit 51132da0c4dac13500d9bb86b2fdad42091d3fd9. The test was changed by commit ccdcd1d95a9d6eda4df86811c4539f204beef817: "Fix test for posixpath.expanduser() when pw_dir ends with /".

cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Can it be closed now?

**Comment by vstinner** [comment]
AMD64 Ubuntu Shared 3.x buildbot worker is back to green, I close the issue.
