### ISSUE TITLE
static type checkers doesn't infer the type correctly under dataclass 

### ISSUE THREAD

**Issue by gkirchou** [python/cpython#118118]
# Bug report

### Bug description:

This should be reproducible for all Python versions that support dataclass. A relevant bug is reported to typeshed: https://github.com/python/typeshed/issues/11793

Static type checkers seems not smart enough to infer the type correctly in the below case:

```python
from collections import OrderedDict
from typing import reveal_type

od: OrderedDict[int, int] = OrderedDict()

class object:
  d: dict[int, int]

o = object()
o.d = od
reveal_type(o.d)
# `OrderedDict` for runtime
# `collections.OrderedDict[builtins.int, builtins.int]` for mypy
# `OrderedDict[int, int]` for pytype
```

```python
from collections import OrderedDict
import dataclasses
from typing import reveal_type

@dataclasses.dataclass
class dataclassObject(object):
  d: dict[int, int]                                                                                                        

o = dataclassObject(d=od)
reveal_type(o.d)
# `OrderedDict` for runtime
# `builtins.dict[builtins.int, builtins.int]` for mypy
# `Dict[int, int]` for pytype
```

### CPython versions tested on:

3.9, 3.11

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
This isn't a bug in CPython as CPython does not control what type checkers do. (I'd argue it's also not a bug in the type checkers, but that's a closer question.)

**Comment by gkirchou** [comment]
Thanks for the quick response always! I also agree with the dataclass's behavior.

For the further actions, I wonder if you consider to make `dataclass` side to report a warning message - say the given variable type is inconsistent to dataclass's variable, which may cause issues in static type checkers, so developers can be aware of and avoid this incorrect (but allowed) setup.

**Comment by AlexWaygood** [comment]
> For the further actions, I wonder if you consider to make `dataclass` side to report a warning message - say the given variable type is inconsistent to dataclass's variable, which may cause confusions in static type checkers, so developers can be aware of and avoid this incorrect (but allowed) setup.

That kind of runtime typechecking could significantly slow down the constructor methods of dataclasses. It's not the runtime's job, I'm afraid, to check that static type checkers are behaving in an intuitive way. Maybe static type checkers could add this kind of warning (but I'm not necessarily _sure_ that I agree that the behaviour here is unintuitive or incorrect — but anyway, it's not a discussion we should have here)
