### ISSUE TITLE
Unreadable dark theme syntax highlighting colors

### ISSUE THREAD

**Issue by pochmann3** [python/cpython#118199]
# Documentation

White on white is barely visible.

Only in 3.9 and lower, 3.10 and above are fine.

https://docs.python.org/3.9/library/functions.html#all

![Screenshot_20240423-232545](https://github.com/python/cpython/assets/150468338/f5b26b1a-b022-4862-bac6-ba81b929d626)

**Comment by terryjreedy** [comment]
This appears to be a duplicate of #115349.  A supposed fix was committed 2024-02-12&13 and should have been released as part of 3.8/9.19 on 2024-03-19.  However, freshly accessed https://docs.python.org/3.8/library/functions.html says it is the *3.8.18*, not 3.8.19 documentation. Ditto for https://docs.python.org/3.9/library/functions.html.  Both continue to have the white-on-white problem illustrated above.  The same is also true of the csv page, https://docs.python.org/3.8/library/csv.html, used to illustrate the previous issue.
@hugovk @ambv

**Comment by pochmann3** [comment]
Right, duplicate. (I only searched for "color", not "colour", and only in *open* issues).

**Comment by hugovk** [comment]
@JulienPalard Please can you check why the 3.8 and 3.9 security releases didn't trigger docs builds? And please can you start the builds?

**Comment by pochmann3** [comment]
Ok now I'm still shown 3.9.18, but now it's readable. It's not dark mode anymore, but that seems to be [the intended fix](https://github.com/python/cpython/issues/115349#issuecomment-1938942062).
