### ISSUE TITLE
Improve links in `ast.rst`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#118100]
# Bug report

There are two problems:
1. https://github.com/python/cpython/blob/15b3555e4a47ec925c965778a415dc11f0f981fd/Doc/library/ast.rst#L2539 but https://leoeditor.com/appendices.html#leoast-py does not exist anymore, correct link is https://leo-editor.github.io/leo-editor/appendices.html#leoast-py
2. I also propose to remove `parso`, because it is no longer maintained for the last 4 years, no new syntax since 3.9? is supported: https://github.com/davidhalter/parso/graphs/contributors

### Linked PRs
* gh-118101
* gh-118110

**Comment by hugovk** [comment]
Reminder: what's the next step after merging the PR and backport? :)

**Comment by sobolevn** [comment]
> Reminder: what's the next step after merging the PR and backport? :)

Openning a new issue and a new PR! 😄
