### ISSUE TITLE
Incorrect argument substitution on Unpack[tuple[...]]

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#118168]
# Bug report

### Bug description:

In the code below, all of the prints should be equivalent:

```python
from typing import Generic, Tuple, TypeVarTuple, Unpack

Ts = TypeVarTuple("Ts")

class Old(Generic[*Ts]): ...
class New[*Ts]: ...

PartOld = Old[int, *Ts]
print(PartOld[str])
print(PartOld[*tuple[str]])
print(PartOld[*Tuple[str]])
print(PartOld[Unpack[tuple[str]]])  # Old[int, typing.Unpack[tuple[str]]]
print(PartOld[Unpack[Tuple[str]]])

PartNew = New[int, *Ts]
print(PartNew[str])
print(PartNew[*tuple[str]])
print(PartNew[*Tuple[str]])
print(PartNew[Unpack[tuple[str]]])  # New[int, typing.Unpack[tuple[str]]]
print(PartNew[Unpack[Tuple[str]]])
```

However, the `Unpack[tuple[]]` variants print something different. This is because the implementation of `Unpack` doesn't deal correctly with builtin aliases. I'll send a PR.

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-118169
* gh-118178

**Comment by nineteendo** [comment]
It looks like you forgot to close this.
