### ISSUE TITLE
AST docs: Fix parameter markup

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#118181]
https://github.com/python/cpython/pull/116129#discussion_r1575794751

I'll try to do this in a bit, but if someone else gets to it first, feel free to pick it up.

### Linked PRs
* gh-124473
* gh-124600
* gh-124705

**Comment by tomasr8** [comment]
Was thinking about writing some wild regex for this :smile: but just to clarify, is this only about replacing parameter name markup like
```
``name``
```
with ``*name*``?

**Comment by Eclips4** [comment]
> Was thinking about writing some wild regex for this 😄 but just to clarify, is this only about replacing parameter name markup like
> 
> ```
> ``name``
> ```
> 
> with `*name*`?

Yeah, you're right. Would you like to send a PR with fix? I'd be happy to review it.

**Comment by tomasr8** [comment]
> Yeah, you're right. Would you like to send a PR with fix? I'd be happy to review it.

On it ;)
