### ISSUE TITLE
Why documentation on built-in function dir() only mentions returning attributes and not methods ?

### ISSUE THREAD

**Issue by mitzk215** [python/cpython#118147]
In python3 documentation page for built-in functions, in the section for [dir() function](https://docs.python.org/3/library/functions.html#dir), it describes that dir() function "only returns a list of valid attributes for that object". Why it doesn't say anything about returning methods as well since dir() function on object (for ex. class) returns all attributes and methods names as well. Is it because by attribute its trying to imply both attribute and method. If so then is it correct to do this since in programming attribute and method are not used interchangeably AFAIK.
![Screenshot from 2024-04-22 16-10-55](https://github.com/python/cpython/assets/35113893/f0a762c0-5153-44a4-adb2-98bbb0d9d396)

**Comment by terryjreedy** [comment]
Methods are a subgroup of attributes.  Our {glossary](https://docs.python.org/3/glossary.html) says this for [attribute](https://docs.python.org/3/glossary.html#term-attribute): "A value associated with an object which is usually referenced by name using dotted expressions. For example, if an object o has an attribute a it would be referenced as o.a."

Please be careful when quoting.  ""only returns a list of valid attributes for that object" is not part of the dir entry.

You can ask questions about interpreting our docs at https://discuss.python.org/c/users/7.

**Comment by mitz88** [comment]
Thanks for the clarification and apologies for misquoting.
