### ISSUE TITLE
Can't implement a descriptor properly under `classmethod`

### ISSUE THREAD

**Issue by erezinman** [python/cpython#118196]
# Bug report

### Bug description:

```python
class desc:
    owner = None
    
    def __init__(self, f):
        self.f = f
        
    def __set_name__(self, owner, name):
        self.owner = owner
        
    def __call__(self, *args, **kwargs):
        return self.f(*args, **kwargs)


class A:
    
    @classmethod
    @desc
    def a(cls):
        pass
    
A.a.__func__.owner   # --> None
```

The `__set_method__` function isn't called when under `classmethod`. What happens is that the `desc` instance is wrapped under a `MethodType`, that holds the instance in `__func__`, but doesn't call its `__set_name__`. We can't even tell in that context whether we're under `classmethod`. This means that we have to have a special `class<descriptor>` for every `<descriptor>` class we create. 

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by rhettinger** [comment]
This isn't a bug.  The `__set_name__` method isn't guaranteed to be discoverable within another descriptor.

**Comment by erezinman** [comment]
It's not just the `__set_name__`. This is not the only solution. The bug is
that you always need to implement two descriptors: one for regular methods,
and one for class methods.

TMHO, this is a result of a breach of KISS design-style, because you have
two similar cases that are processed dissimilarly:
When having a descriptor, the default metaclass replaces `MethodType` with
the descriptor, with its "name set" regularly.
On the other hand, with a class method, it is wrapped with `MethodType`
regardless of whether it is wrapped or not.

There are a at least few possible solutions to this. A partial list:
1. The simplest/worst - forbid by exception/warning having a descriptor
that implements `__set_name__` under `classmethod`.
2. Midway - keep that behavior, and call `__set_name__` in `MethodType`.
3. Extensive change - do not wrap `classmethod`s with `MethodType`, but
instead just have the `__get__`, `__set__`, `__delete__` functions called
with class as the instance directly from the metaclass (like with regular
descriptors). The `__set_name__` method will not have to change in this
case.

The solution also has to take `staticmethod` and the get-set-deal accessors
into account.

**Comment by rhettinger** [comment]
>  The bug is that you always need to implement two descriptors: one for regular methods, and one for class methods.

Inconvenience for a particular take isn't the same as being a bug.   At best, this is a feature request to improve composability of classmethod with custom user created descriptors.   That hasn't worked out well for us in the past.

Consider making a concrete proposal on python-ideas.  Ideally, pose some realistic use cases that programmers are likely to encounter.
