### ISSUE TITLE
sorry for trouble

### ISSUE THREAD

**Issue by neonarc4** [python/cpython#118215]
nvm i will do it myself

**Comment by nineteendo** [comment]
Close this issue and discuss on Discourse first: https://discuss.python.org/c/ideas/6. Re-open it if there's consensus.

**Comment by neonarc4** [comment]
u tell me consensus i dont have time to waste around ur community and ur opnion whole javascript community doing it why to bother i will do it without ur help

**Comment by Eclips4** [comment]
> u tell me consensus also u are not owner of python and i dont have time to waste around ur community and ur opnion whole javascript community doing it why to bother i will do it without ur help

Please be patient. Any major changes should be widely discussed before they're get implemented. 
Sorry, but reason "JavaScript has X so we should also have X" is not objective.
