### ISSUE TITLE
`os.path.realpath('notadir/', strict=True)` doesn't raise

### ISSUE THREAD

**Issue by barneygale** [python/cpython#118289]
# Bug report

### Bug description:

GNU coreutils `realpath -e` errors out when given a path to a file (not a directory) with a trailing slash:

```bash
$ realpath -e python/
realpath: python/: Not a directory
```

... but Python's `os.path.realpath(..., strict=True)` doesn't raise any error:

```python
>>> os.path.isfile('python')
True
>>> os.path.isdir('python')
False
>>> os.path.realpath('python/', strict=True)  # should raise NotADirectoryError
'/home/barney/projects/cpython/python'
>>> os.path.realpath('python/.', strict=True)  # should raise NotADirectoryError
'/home/barney/projects/cpython/python'
```

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-118290
* gh-120127
* gh-126815

**Comment by nineteendo** [comment]
Here's a list of all invalid paths for `posix.stat()`. All of these should raise an error for `posixpath.realpath()` in strict mode:

- New file: `newfile.txt` -> FileNotFoundError (OK)
- Under a file: `foo.txt/bar.txt` -> NotADirectoryError (**NOK**)
- Too long file name: `"a" * 256` -> OSError (OK)
- Too long path: `"a/" * 512` -> OSError (OK)
- Too many levels of symlinks: `"s/" * 33` -> OSError (**NOK**)

Should I make an issue for the symlinks?

**Comment by barneygale** [comment]
> Should I make an issue for the symlinks?

It's deliberate behaviour - `os.path.realpath()` doesn't place a limit on the number of symlink traversals, unlike Linux.

**Comment by nineteendo** [comment]
> It's deliberate behaviour - `os.path.realpath()` doesn't place a limit on the number of symlink traversals, unlike Linux or Mac.

You mean the built-in function in macOS?

```zsh
wannes@Stefans-iMac dirs % realpath s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s
realpath: s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s: Too many levels of symbolic links
```

Maybe a `max_symlinks` argument would make more sense? With `None` for the system default & `-1` for no limit.

**Comment by novaTopFlex** [comment]
I have just tested the `os.path.realpath()` function on my different `python3` versions and have gotten mostly the same issue.

If one is still on `python3.9`:
The `strict` argument is not an available argument in Python version 3.9.x.

If one is on `python3.10`, `python3.11`, `python3.12`, or `python3.13`:
The `strict` argument is recognized, but the code does not raise a `NotADirectoryError`.

**Comment by nineteendo** [comment]
`ntpath.realpath()` also raises an error, I'll try to check with coreutils as well.

```python
>>> import os
>>> os.path.realpath('s/' * 64, strict=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen ntpath>", line 722, in realpath
OSError: [WinError 1921] The name of the file cannot be resolved by the system: 'C:\\Users\\wanne\\path-picker\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s\\s'
```

**Comment by nineteendo** [comment]
Hmm, only with '--logical':

```zsh
wannes@Stefans-iMac dirs % grealpath -e s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s
/Users/wannes/path-picker/link-test/dirs
wannes@Stefans-iMac dirs % grealpath -L s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s
grealpath: s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s/s: Too many levels of symbolic links
```

**Comment by eryksun** [comment]
On POSIX systems, wouldn't it be reasonable for `posixpath.realpath()` in strict mode to try to match the behavior of [POSIX `realpath()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/realpath.html)? This fails with `ELOOP` if too many levels of symlinks are encountered. On Windows, WinAPI `CreateFileW()` fails with `ERROR_CANT_RESOLVE_FILENAME` (1921) in this case, and `ntpath.realpath()` in strict mode raises a corresponding `OSError`. That seems correct to me.

Linux:

```python
import os, ctypes
pg = ctypes.CDLL(None, use_errno=True)
buf = (ctypes.c_char * 4096)()
pg.realpath.restype = ctypes.c_char_p
pg.realpath.argtypes = (ctypes.c_char_p, ctypes.c_char_p)
for i in range(41):
    os.symlink(f's{i+1}', f's{i}')
open('s41', 'w').close()
```

```pycon
>>> os.path.realpath('s0', strict=True)
'/home/user/Temp/test/symlinks/s41'
>>> pg.realpath(b's0', buf)
>>> ctypes.get_errno() == errno.ELOOP
True
>>> os.strerror(errno.ELOOP)
'Too many levels of symbolic links'
```

**Comment by barneygale** [comment]
Would that be instead of, or in addition to, the existing symlink loop detection? The current code uses a `seen` dict that can grow to an arbitrary size. I'm guessing OSs use a counter because it's faster and uses less memory? (And presumably more resilient against DoS via long-but-not-looping chains of symlinks?)

**Comment by eryksun** [comment]
Python's `os.sysconf_names` dict is missing some of the names that are required by [Issue 7 of POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/functions/sysconf.html), including "SC_SYMLOOP_MAX" (added in Issue 6). Here's all of the missing names:

```text
SC_2_PBS
SC_2_PBS_ACCOUNTING
SC_2_PBS_CHECKPOINT
SC_2_PBS_LOCATE
SC_2_PBS_MESSAGE
SC_2_PBS_TRACK
SC_ADVISORY_INFO
SC_BARRIERS
SC_CLOCK_SELECTION
SC_CPUTIME
SC_HOST_NAME_MAX
SC_IPV6
SC_MONOTONIC_CLOCK
SC_RAW_SOCKETS
SC_READER_WRITER_LOCKS
SC_REGEXP
SC_SHELL
SC_SPAWN
SC_SPIN_LOCKS
SC_SPORADIC_SERVER
SC_SS_REPL_MAX
SC_SYMLOOP_MAX
SC_THREAD_CPUTIME
SC_THREAD_ROBUST_PRIO_INHERIT
SC_THREAD_ROBUST_PRIO_PROTECT
SC_THREAD_SPORADIC_SERVER
SC_TIMEOUTS
SC_TRACE
SC_TRACE_EVENT_FILTER
SC_TRACE_EVENT_NAME_MAX
SC_TRACE_INHERIT
SC_TRACE_LOG
SC_TRACE_NAME_MAX
SC_TRACE_SYS_MAX
SC_TRACE_USER_EVENT_MAX
SC_TYPED_MEMORY_OBJECTS
SC_V6_ILP32_OFF32
SC_V6_ILP32_OFFBIG
SC_V6_LP64_OFF64
SC_V6_LPBIG_OFFBIG
SC_V7_ILP32_OFF32
SC_V7_ILP32_OFFBIG
SC_V7_LP64_OFF64
SC_V7_LPBIG_OFFBIG
SC_XOPEN_STREAMS
SC_XOPEN_UUCP
```

**Comment by nineteendo** [comment]
Let's track this further in #118441.

**Comment by nineteendo** [comment]
How about secret symlinks? Should these be allowed in non-strict mode?

```zsh
wannes@Stefans-iMac dirs % sudo ls -l secret-symlink
l---------  1 wannes  staff  44 Jun 30  2023 secret-symlink -> /Users/wannes/path-picker/link-test/dirs/dir
wannes@Stefans-iMac dirs % grealpath -m secret-symlink
/Users/wannes/path-picker/link-test/dirs/secret-symlink
```

```python
>>> import posixpath
>>> posixpath.realpath("secret-symlink")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen posixpath>", line 435, in realpath
  File "<frozen posixpath>", line 495, in _joinrealpath
PermissionError: [Errno 13] Permission denied: 'secret-symlink'
```

**Comment by barneygale** [comment]
Looks like a bug to me!

**Comment by nineteendo** [comment]
OK, see #118447.

**Comment by nineteendo** [comment]
It has been a month, is there anyone who would also like to review the pull request?
