### ISSUE TITLE
Behaviour of ROUND function not as expected

### ISSUE THREAD

**Issue by kevintedder** [python/cpython#118294]
# Bug report

### Bug description:

O/S:  Ubuntu 23.10
H/W: AMD A6-3500 APU with Radeon™ HD Graphics × 3
Python:  Python 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0] on linux

I'm writing a small binary search function using very large integers and finding that it fails after ~20 loops.  I need to find the average between the MIN and MAX search area so I've used a simple calculation : mean = round( ( min + max ) / 2 ) to find the closest mid point. 

Having inspected the code many times I believe there could be an issue with the rounding function. Here are some sample tests I've performed:
>>> print( round( ( 51910641600234192896 + 51910641600234201088 ) / 2 ) )
51910641600234192896                                                                                                 # Returns the 1st number
>>> print( round( ( 51910641600234192896 + 51910641600234201089 ) / 2 ) )   # Increase by 1
51910641600234201088                                                                                                 # Returns the 2nd number - 1
>>> print( round( ( 51910641600234192896 + 51910641600234201087 ) / 2 ) )   # Decrease by 1
51910641600234192896                                                                                                 # Returns the 1st number

Clearly the results are not as I'd expect.  It is returning the lowest or highest number provided, not the mid point.

This only happens when the numbers are above 10^18 in length

Is this a bug?

PS.
The difference between the MIN and MAX (i.e MAX minus MIN)  is always multiples of 256 - i.e. 256, 512, 1024, 2048, 4096, 8192 ...      Is this a byte alignment issue?

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
`/` returns a float, and your numbers are big enough that the float can't represent the number exactly. Try using integer division (`//`) instead.

In the future, consider asking in the "Help" forum on https://discuss.python.org/ first.
