### ISSUE TITLE
Re-use old indent in `json.loads()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118299]
# Feature or enhancement

### Proposal:

Currently the indent is generated from scratch for each depth:

```python
_current_indent_level += 1
newline_indent = '\n' + _indent * _current_indent_level
```

We can easily re-use the old indent:

```python
newline_indent = old_newline_indent + _indent
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-118300

**Comment by serhiy-storchaka** [comment]
Could you show any benchmark results?

**Comment by nineteendo** [comment]
See the pull request: https://github.com/python/cpython/pull/118300#issue-2264665030

**Comment by nineteendo** [comment]
Do we close this? Or did you mean I could leave it at concatenation?
