### ISSUE TITLE
COMMON_FIELDS macro in funcobject.h leaks to user code

### ISSUE THREAD

**Issue by itamaro** [python/cpython#118207]
# Bug report

### Bug description:

the `COMMON_FIELDS` macro is defined [here](https://github.com/python/cpython/blob/7e87d30f1f30d39c3005e03195f3d7648b38a1e2/Include/cpython/funcobject.h#L11-L19), and can end up being included in user code (via `Python.h`).

"COMMON_FIELDS" is not a unique enough identifier, and can conflict with other use of the same name in user C/C++ code (has happened to us at Meta).

this macro is used only twice within the same header as it is defined, so it should be straight forward to undef it after it is used to prevent it from leaking (PR coming up).

### CPython versions tested on:

3.10, 3.12, 3.13

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-118208
* gh-118269

**Comment by encukou** [comment]
FWIW: I have a script *almost* ready to detect stray definitions without the `Py` prefix. Right now the focus is on getting features into 3.13 beta1; I plan to run the script after that.

**Comment by itamaro** [comment]
thanks @encukou ! waiting for the backport to land and then we can close this issue :)
