### ISSUE TITLE
JIT CI is broken due to `test_pathlib` and `test_posixpath`

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#118246]
Looks like something in emulation/QEMU changed and now `test_pathlib` and `test_posixpath` are causing the GHA workflow to fail for Linux Arm.

### Linked PRs
* gh-118247

**Comment by nineteendo** [comment]
Can it not be fixed? Or can we skip certain tests?

**Comment by barneygale** [comment]
Could you share a link to a failing GHA workflow please?

**Comment by brandtbucher** [comment]
> Can it not be fixed? Or can we skip certain tests?

Yeah, we could probably use the `--matchfile` option and maintain a text file with a list of individual failures under emulation... any volunteers?

The current PR is a good stopgap though, just to get things passing on PRs (we already skip a bunch of tests, so adding these isn't a huge change).

**Comment by savannahostrowski** [comment]
Yes, definitely - https://github.com/python/cpython/actions/runs/8820363755/job/24213816403

I'd like to spend time digging into the emulation failures but this is intended to provide fix in the meantime.

**Comment by barneygale** [comment]
Thanks for the link! It might have been aggravated by #117447 - perhaps under emulation, `lstat('/')` and `lstat('/..')` are returning different `st_ino`s for some reason.

**Comment by brandtbucher** [comment]
Ah, I missed that change. Thanks for digging into it.

**Comment by brandtbucher** [comment]
> Yeah, we could probably use the `--ignorefile` option and maintain a text file with a list of individual failures under emulation... any volunteers?

GH-118251

**Comment by brandtbucher** [comment]
@barneygale, is this something that you think is worth fixing in `os.ismount`? I don't think Python technically supports emulated environments, so it's not worth reverting any speed improvement or anything.

**Comment by brandtbucher** [comment]
This is done, then!
