### ISSUE TITLE
Requests code does not handle redirects correctly

### ISSUE THREAD

**Issue by klan30destine** [python/cpython#118304]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
My name is Adrian Hill.

I have struck a problem with the Python code (V3.12.3) where it is not handling a URL that has UTF8 characters in it. The Url is’

[https://www.abc.net.au/listen/programs/lunchtime-concert/jaime-martín-conducts-mahler-3/103656006](https://www.abc.net.au/listen/programs/lunchtime-concert/jaime-mart%C3%ADn-conducts-mahler-3/103656006)

(The utf8 character is in the martin text. The “i” is an “i acute”, (Uft8 char %C3%AD))

The problem is that the request for this URL returns a 307error (Temporary Redirect) in the response. When the Request code gets that 307 response, it is apparently not replying with the correct reply request using the new url in the response data from the initial request. (RFC2616) It then just keeps getting a recurring error of 307 and goes into a loop until it is caught by the code with a failure of Too Many Redirects
The browsers I have tried (Chrome and Firefox) work correctly when given the above URL

Could you have this problem investigated to determine if you can reproduce it and possibly update the Python code to fix it in the next version. (NB. I am not sure how long this specific URL will be available. If it expires, there will probably be another URL later that has UTF8 characters in it.)

Please let me know if you need more information.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
Hello, this is the issue tracker for the Python language itself. 

You can find the Requests issue tracker at https://github.com/psf/requests but you're probably better off asking at the help forum: https://discuss.python.org/c/users/7
