### ISSUE TITLE
RERAISE sys.monitoring event is reported twice

### ISSUE THREAD

**Issue by scoder** [python/cpython#118360]
# Bug report

### Bug description:

```python
from functools import partial

def raising():
    raise RuntimeError()

def passing():
    try:
        raising()
    except ValueError: pass
    except: raise

def print_event(*args):
    print(args)

def monitor():
    from sys import monitoring as smon
    tool_id = smon.DEBUGGER_ID
    smon.use_tool_id(tool_id, "TEST")
    smon.register_callback(tool_id, smon.events.RAISE, partial(print_event, "raise"))
    smon.register_callback(tool_id, smon.events.RERAISE, partial(print_event, "reraise"))
    smon.set_events(tool_id, smon.events.RAISE | smon.events.RERAISE)

    try:
        passing()
    except RuntimeError: pass

    smon.free_tool_id(tool_id)
```
Output:
```
('raise', <code object raising at 0x7efe33179940, file ".../mon.py", line 3>, 20, RuntimeError())
('raise', <code object passing at 0x7efe33135360, file ".../mon.py", line 6>, 12, RuntimeError())
('reraise', <code object passing at 0x7efe33135360, file ".../mon.py", line 6>, 52, RuntimeError())
('reraise', <code object passing at 0x7efe33135360, file ".../mon.py", line 6>, 58, RuntimeError())
('raise', <code object monitor at 0x562bc24e1f40, file ".../mon.py", line 15>, 412, RuntimeError())
```

It surprised me that `RAISE` events are generally reported whenever an exception is observed (not just when it's being raised), but the duplicate `RERAISE` events in the `passing` function really seem spurious.

Bytecode:
```
Disassembly of <code object passing at 0x7ff7250d7760, file "mon.py", line 6>:
   6           RESUME                   0

   7           NOP

   8   L1:     LOAD_GLOBAL              1 (raising + NULL)
               CALL                     0
               POP_TOP
       L2:     RETURN_CONST             0 (None)

  --   L3:     PUSH_EXC_INFO

   9           LOAD_GLOBAL              2 (ValueError)
               CHECK_EXC_MATCH
               POP_JUMP_IF_FALSE        3 (to L5)
               POP_TOP
       L4:     POP_EXCEPT
               RETURN_CONST             0 (None)

  10   L5:     POP_TOP
               RAISE_VARARGS            0

  --   L6:     COPY                     3
               POP_EXCEPT
               RERAISE                  1
ExceptionTable:
  L1 to L2 -> L3 [0]
  L3 to L4 -> L6 [1] lasti
  L5 to L6 -> L6 [1] lasti
```

Removing the `except ValueError: pass` line above makes no difference (just changes the offsets).

I found this while testing the C-API monitoring branch in https://github.com/python/cpython/pull/116413

Py3.12 has the same behaviour but gives this bytecode:
```
Disassembly of <code object passing at 0x7f58ecd9b9a0, file "mon.py", line 6>:
  6           0 RESUME                   0

  7           2 NOP

  8           4 LOAD_GLOBAL              1 (NULL + raising)
             14 CALL                     0
             22 POP_TOP
             24 RETURN_CONST             0 (None)
        >>   26 PUSH_EXC_INFO

  9          28 LOAD_GLOBAL              2 (ValueError)
             38 CHECK_EXC_MATCH
             40 POP_JUMP_IF_FALSE        3 (to 48)
             42 POP_TOP
             44 POP_EXCEPT
             46 RETURN_CONST             0 (None)

 10     >>   48 POP_TOP
             50 RAISE_VARARGS            0
        >>   52 COPY                     3
             54 POP_EXCEPT
             56 RERAISE                  1
ExceptionTable:
  4 to 22 -> 26 [0]
  26 to 42 -> 52 [1] lasti
  48 to 50 -> 52 [1] lasti
```

It seems that both `RAISE_VARARGS` and `RERAISE` trigger the event.

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
I don't think this is a bug. `RERAISE` is not an event when you "raise" the exception inside exception handler - that's still `RAISE`. `RERAISE` is more like an internal event the the interpreter decides to raise the exception somehow.

I think this is similar to #112086. Why do you think this is a bug? Does it contradict any documentation we have?

**Comment by scoder** [comment]
> Why do you think this is a bug?

What would be the reasoning for reporting the event twice, for the same function, when there's only a single `raise`? I also don't get two `RETURN` events when I write `return xyz` in my function. Why two `RERAISE` events for the exact same `raise` command?

**Comment by iritkatriel** [comment]
I think maybe the event should be emitted only for `RAISE_VARARGS` (which is the user-code `raise`) and not for the last `RERAISE`, which is for internal state maintenance. @markshannon does this make sense?

**Comment by gaogaotiantian** [comment]
> What would be the reasoning for reporting the event twice, for the same function, when there's only a single `raise`? I also don't get two `RETURN` events when I write `return xyz` in my function. Why two `RERAISE` events for the exact same `raise` command?

Do you mean `RERAISE` event should always corresponds to an explicit `raise`? That contradicts the current documentation.

```python
try:
    raise Exception()
finally:
    pass
```

There's no explicit `raise` in the code and the documentation uses this as an example for `RERAISE` event. Are you suggesting that we should not report an `RERAISE` event in this case?

**Comment by iritkatriel** [comment]
> I think maybe the event should be emitted only for `RAISE_VARARGS` (which is the user-code `raise`) and not for the last `RERAISE`, which is for internal state maintenance. @markshannon does this make sense?

I guess the issue is distinguishing a `RERAISE` from this scenario and a `RERAISE` which comes from an implicit case like in the previous comment. It would be hard at runtime, but less so at compile time - it could be encoded in the arg or RERAISE.

**Comment by gaogaotiantian** [comment]
If we could come up with some well-defined description for `RERAISE` event I would be all for it. Everything is kind of "intuitive" now - what should trigger the event and what should not. In that case I'm leaning forward to "do whatever the current implementation does", at least that will not hide events that the user might be interested in. From a tool developer's view, having extra stuff to filter out is often better than missing information.

**Comment by scoder** [comment]
> Are you suggesting that we should not report a RERAISE event in this case?

The fact that try-finally and (apparently) try-except reraise exceptions (rather than just keeping them live as long as they are not handled) feels like an implementation detail to me. But in the end, it's a matter of definition. I agree that a more precise explanation what makes up the events would help to clarify this. Iff we end up agreeing that the behaviour is really desired and not just an artefact of the current eval loop implementation.

**Comment by markshannon** [comment]
I don't think it is an implementation detail.


### Try finally 
The semantics of try-finally is that exception is "caught", the finally block executed, then the exception is reraised.
The sequence of events is something like:
```
RAISE
HANDLED
# Finally block events here
RERAISE
```

### Try except

Since Python is a dynamic language the `except ExClass` must be implemented as a test, so:
```Python
try:
    body
except ExClass:
    handler
```
must be implemented as something like:
```Python
try:
    body
except as ex:
    if isinstance(ex, ExClass):
       handler
    else:
        raise  # RERAISE event
```
Which generates 
```
RAISE
HANDLED
# Events for isinstance test
RERAISE
```

**Comment by markshannon** [comment]
> If we could come up with some well-defined description for RERAISE event I would be all for it.

How about this:

The VM/abstract machine must be in one of two states:
* Executing
* Unwinding

Executing is the normal state. Unwinding is the state between an exception being raised and it being handled or execution terminating.

One of the following events occur when the VM transitions from executing to unwinding and vice versa:

#### Executing -> Unwinding

* RAISE
* RERAISE
* C_RAISE

#### Unwinding -> Executing

* EXCEPTION_HANDLED

### Raise Events

* RAISE: A new exception is raised in Python code
* C_RAISE: An exception has been raised in C code and unwinding enters a Python frame
* RERAISE: The state changes to unwinding, but no new exception is created: The new exception being one that was previously handled by an `EXCEPTION_HANDLED` event

**Comment by markshannon** [comment]
Is there anything else to do here?
@scoder does the above description make sense to you?

**Comment by scoder** [comment]
Works for me.
