### ISSUE TITLE
Regular expression pattern with underscore character inconsistent for all the other chars used.

### ISSUE THREAD

**Issue by gryf** [python/cpython#118399]
# Bug report

### Bug description:

I want to search for some pattern like in the text: `Lorem __ipsum__ dolor sit amet`, which should match exactly `_ipsum_` I'm using a pattern `(?:(?<=[^\w]))_([^_\s]*?[^\s])_`. This gives result:
```python
import re

text = "Lorem __ipsum__ dolor sit amet"
re.search(r'(?:(?<=[^\w]))_([^_\s]*?[^\s])_', text)
# gives: None
```
even, if I escape undersore (i.e. `\_`) re.search still gives None. But, when I change underscore character to whatever else, it's all working fine:
```python
import re

text = "Lorem **ipsum** dolor sit amet"
re.search(r'(?:(?<=[^\w]))\*([^\*\s]*?[^\s])\*', text)
# gives: <re.Match object; span=(7, 14), match='*ipsum*'>
text = "Lorem ××ipsum×× dolor sit amet"
re.search(r'(?:(?<=[^\w]))×([^×\s]*?[^\s])×', text)
# gives: <re.Match object; span=(7, 14), match='×ipsum×'>
text = "Lorem ..ipsum.. dolor sit amet"
re.search(r'(?:(?<=[^\w]))\.([^\.\s]*?[^\s])\.', text)
# gives: <re.Match object; span=(7, 14), match='.ipsum.'>
```

Is it a bug, or underscore is treated different than all the other (even special) characters?

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
I think it's because `\w` matches `_` so your `(?:(?<=[^\w]))` prevented the match as the supposed match has a `_` prefix.

**Comment by terryjreedy** [comment]
Would not the same comment apply to `x` instead of `_`, which gives a different result?

**Comment by pochmann3** [comment]
@terryjreedy Does it? I get `None` as well:

```python
import re

text = "Lorem xxipsumxx dolor sit amet"
print(re.search(r'(?:(?<=[^\w]))x([^x\s]*?[^\s])x', text))
```

[Attempt This Online!](https://ato.pxeger.com/run?1=NY5BCsIwEADvecXSSxOxnkUs-YA_aFMoutKAacJmi-tbeulF_-RvVNTrHGZmfqQbD3FclvvE52r7DD6kSAyESjEKQw3FIRIGEPEpT0EETvESCbJn6ANyoRL5kTXhJmNPx0FTqe1O233ddO3VGSO66aTNbmXfIDsj5Ro-bmO-0V_7__AC)

Seems clearly not a Python bug.

**Comment by terryjreedy** [comment]
I get None for 'x' replacement on latest 3.11 and 3.113.

**Comment by gryf** [comment]
@gaogaotiantian oh, I see. `\w` will match anything from `[^a-zA-Z0-9_]` which excludes also `_` but not `*` or `×`.

Also, I'm sorry for choosing `×` character as a test - it's different from regular letter `x` as it is multiplication sign (`\u00d7`), which indeed gives match instead None:
```python
import re
# use × (\u00d7)
text = "Lorem ××ipsum×× dolor sit amet"
re.search(r'(?:(?<=[^\w]))×([^×\s]*?[^\s])×', text)
# gives: <re.Match object; span=(7, 14), match='×ipsum×'>
# use letter x
text = "Lorem xxipsumxx dolor sit amet"
re.search(r'(?:(?<=[^\w]))x([^x\s]*?[^\s])x', text)
# gives: None
```
