### ISSUE TITLE
Python recognising tuple having single list as a list only while trying to concatenate with another tuple.

### ISSUE THREAD

**Issue by josephbonyemmanuel** [python/cpython#118303]
# Bug report

### Bug description:

"""
I were using Jupiter Notebook for python programing in IBM SN Labs. It uses version gcc 9.4.0.

problem description:

While trying to concatenate two tuples using arguments, the interpreter treating the tuple with a single list as list and resulting in error.
"""
```python
# Add a code block here, if required

def con(a, b):
    return(a + b)

print(con(['a',1],['b',2]))
print(con((['a',1]),('b',2,)))
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

**Comment by JelleZijlstra** [comment]
That is not a tuple containing a list, it is merely a list with parentheses around it. You need a comma to make a tuple, like `([1, 2],)`.
