### ISSUE TITLE
New warning: ``assignment to ‘_PyInterpreterFrame *’ from incompatible pointer type ‘_Py_UopsSymbol *’ [-Wincompatible-pointer-types]``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#118343]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/118334/files and https://github.com/python/cpython/pull/118338/files

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-118430

**Comment by sobolevn** [comment]
Happens in [Python/optimizer_cases.c.h](https://github.com/python/cpython/pull/118324/files#diff-ed4567b3e67709ec57bf4df91ef058cfcbe00d7da11cd2a75e38241fa1ca99d2)

**Comment by nineteendo** [comment]
Any updates on this?

**Comment by sobolevn** [comment]
cc @markshannon https://github.com/python/cpython/commit/3e06c7f719b99cc7f5e8889319cff4980e41d3e8

**Comment by lysnikolaou** [comment]
FWIW, for those with setups where warnings are treated as errors (my Fedora does this, not sure why the defaults are different), one can do `CFLAGS="-Wno-error=incompatible-pointer-types" make` as a work-around until this is solved.

**Comment by corona10** [comment]
```
Python/optimizer_cases.c.h: In function ‘optimize_uops’:
Python/optimizer_cases.c.h:1444:23: error: assignment to ‘_PyInterpreterFrame *’ from incompatible pointer type ‘_Py_UopsSymbol *’ [-Wincompatible-pointer-types]
 1444 |             gen_frame = sym_new_not_null(ctx);
      |                       ^
make: *** [Makefile:3018: Python/optimizer_analysis.o] Error 1
make: *** Waiting for unfinished jobs....
```

Build failure with my Fedora 40. 
(gcc14)

**Comment by corona10** [comment]
The build failure is due to gcc 14 changed policy
Similar issue: https://forums.developer.nvidia.com/t/nvidia-modules-build-failure-with-upcoming-gcc-14-and-recent-kernels-due-to-misfiring-conftest-sh-test-heads-up/279072

**Comment by nineteendo** [comment]
Fixed for me too.

**Comment by corona10** [comment]
Issue fixed by https://github.com/python/cpython/pull/118380

**Comment by ZeroIntensity** [comment]
This might need to get reopened. I'm encountering this error when trying to compile with the JIT on the main branch (but not 3.13, FWIW).

**Comment by Eclips4** [comment]
> This might need to get reopened. I'm encountering this error when trying to compile with the JIT on the main branch (but not 3.13, FWIW).

It's looks like a new warning, so I think it's ok to open a new issue.

**Comment by ZeroIntensity** [comment]
Ok, will do.
