### ISSUE TITLE
Don't use `Py_BuildValue("(OO...)", a, b, ...)`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118379]
# Feature or enhancement

### Proposal:

This is an inefficient way to build a tuple:

```c
Py_BuildValue("(OO)", a, b)
```

This is faster, and more readable:

```c
PyTuple_Pack(2, a, b)
```

And if #118222 lands, we could use this even faster variant for length 1 & 2:

```c
PyTuple_Pack2( a, b)
```

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-118381

**Comment by serhiy-storchaka** [comment]
I already did something similar recently: #110093.
