### ISSUE TITLE
`dataclass` : there seems to be no way to create a class-level mutable object 

### ISSUE THREAD

**Issue by AndreFCruz** [python/cpython#118387]
# Bug report

### Bug description:

There seems to be no way of currently assigning a mutable-object class variable to a dataclass.

See the following code example for something that does not work:
```python
from dataclasses import dataclass, field

@dataclass
class Vehicle:
    number_of_wheels: int
    type_of_vehicle: str
    manufacturer: str

    # Class-level variable
    total_vehicles: list[int] = field(default_factory=list, init=False, repr=False)

    def __post_init__(self):
        Vehicle.total_vehicles.append(self.number_of_wheels)

    @classmethod
    def get_total_vehicles(cls):
        return cls.total_vehicles


# Example usage
car = Vehicle(4, "Car", "Toyota")
print(Vehicle.total_vehicles)

bike = Vehicle(2, "Bike", "Honda")
print(Vehicle.total_vehicles)
```

This throws: `AttributeError: type object 'Vehicle' has no attribute 'total_vehicles'`

One of the two following lines should be possible:
1.
```python
    total_vehicles: list[int] = field(default_factory=list, init=False, repr=False)
    # Throws: AttributeError: type object 'Vehicle' has no attribute 'total_vehicles'
```

Or 2.
```python
    total_vehicles: list[int] = []
    # Throws: ValueError: mutable default <class 'list'> for field total_vehicles is not allowed: use default_factory
```

**But** if instead of sharing a `list[int]` at the class-level we share an `int` the code now works fine:
```python
from dataclasses import dataclass, field

@dataclass
class Vehicle:
    number_of_wheels: int
    type_of_vehicle: str
    manufacturer: str

    # Class-level variable
    total_vehicles: int = field(default=0, init=False, repr=False)

    def __post_init__(self):
        Vehicle.total_vehicles += 1

    @classmethod
    def get_total_vehicles(cls):
        return cls.total_vehicles


# Example usage
car = Vehicle(4, "Car", "Toyota")
print(Vehicle.total_vehicles)

bike = Vehicle(2, "Bike", "Honda")
print(Vehicle.total_vehicles)
```

Outputs, as expected:
```
1
2
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
You need to use `typing.ClassVar`. See https://docs.python.org/3.10/library/dataclasses.html#class-variables.

**Comment by AndreFCruz** [comment]
Ah, my bad. Using `ClassVar` with `default` instead of `default_factory` works 👍 

I guess it's not immediately clear from the user point of view why an `int` type class-variable can be declared directly and mutable objects require a different initialization with `ClassVar`, since both are shared among all class instances. Maybe class-level ints should also be `typing.ClassVar[int]`.

Thanks for the response!
