### ISSUE TITLE
Broken `bdb.Bdb.user_call` API

### ISSUE THREAD

**Issue by George-Ogden** [python/cpython#118359]
# Bug report

### Bug description:

This is an issue with how `bdb.Bdb.user_call` is documented.
According to the [`bdb` documentation](https://docs.python.org/3/library/bdb.html#bdb.Bdb.user_call), `bdb.BdB.user_call` has two arguments, `frame` and `argument_list`. 
This is implemented in the `bdb` library [here](https://github.com/python/cpython/blob/3.12/Lib/bdb.py#L118).
However, according to the [`sys` documentation](https://docs.python.org/3/library/sys.html#sys.settrace), `sys.settrace` will always set the `arg` to `None` and the code above acknowledges that _"# XXX 'arg' is no longer used"_. 
I don't know if this is based on a previous version that would give the call arguments, but I think we should change the signature of `bdb.Bdb.user_call` to exclude the `argument_list` parameter or state in the documentation that it will be `None`.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-118368
* gh-118410

**Comment by gaogaotiantian** [comment]
Yes, we should change the documentation. We can't change the signature of the function because that would break backward compatibility.

**Comment by gaogaotiantian** [comment]
Thank you for reporting this. The docs is fixed in main and will be backported to 3.12.
