### ISSUE TITLE
Doc workflow is failing due to a missing file 'Doc/sphinx-warnings.txt'

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#118401]
# Bug report

### Bug description:

Example: https://github.com/python/cpython/actions/runs/8883326110/job/24389960128?pr=118368

```pytb
Traceback (most recent call last):
  File "/home/runner/work/cpython/cpython/Doc/tools/check-warnings.py", line 311, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/runner/work/cpython/cpython/Doc/tools/check-warnings.py", line 279, in main
    with Path("Doc/sphinx-warnings.txt").open(encoding="UTF-8") as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.3/x64/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'Doc/sphinx-warnings.txt'
```

The `'Doc/sphinx-warnings.txt'` file is a generated file so maybe we upgraded sphinx at some point and the new version does not generate the file if there's no warnings?

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-118403
* gh-118407

**Comment by hugovk** [comment]
We upgraded Sphinx an hour ago: https://github.com/python/cpython/pull/118397

Thanks for the report, I'll check it.

**Comment by hugovk** [comment]
Merged.

I restarted this docs build and it failed again:

https://github.com/python/cpython/actions/runs/8883326110/job/24395466270?pr=118368

It probably needs a new commit to re-sync or something? I updated the PR from `main`, and it now passed 👍 

https://github.com/python/cpython/actions/runs/8885080408/job/24395617997?pr=118368

Hopefully it won't happen again for new PRs.

Thanks!
