### ISSUE TITLE
Incorrect and overly-complicated islice example implementation in docs

### ISSUE THREAD

**Issue by FHTMitchell** [python/cpython#118476]
# Documentation

The `itertools.islice` reference implementation in the docs is complex and also slightly incorrect. For reference it is here

```python
def islice(iterable, *args):
    s = slice(*args)
    start, stop, step = s.start or 0, s.stop or sys.maxsize, s.step or 1
    it = iter(range(start, stop, step))
    try:
        nexti = next(it)
    except StopIteration:
        # Consume *iterable* up to the *start* position.
        for i, element in zip(range(start), iterable):
            pass
        return
    try:
        for i, element in enumerate(iterable):
            if i == nexti:
                yield element
                nexti = next(it)
    except StopIteration:
        # Consume to *stop*.
        for i, element in zip(range(i + 1, stop), iterable):
            pass
```

This does not correctly handle `stop == 0`, overwriting it to be `sys.maxsize` and also assumes its input is an iterator, not any iterable. 

It is also just hard to reason about. Instead I propose

```python
def islice(iterable, *args):
      s = slice(*args)
      start = s.start if s.start is not None else 0
      stop = s.stop
      step = s.step if s.step is not None else 1
      it = iter(iterable)
      for _ in zip(range(start), it):
          # Consume up to *start* position
          pass
      if stop is not None and stop <= start:
          return
      for i, element in enumerate(it, start):
          if (i - start) % step == 0:
              yield element
          if stop is not None and i + 1 >= stop:
              return
```

This matches `islice` exactly for these inputs

```python
for start in itertools.chain(range(6), [None]):
    for stop in itertools.chain(range(6), [None]):
        for step in itertools.chain(range(1, 6), [None]):
            for r in [range(0), range(4)]:
                it = iter(r)
                myx = list(islice(it, start, stop, step))
                myy = list(it)
                it = iter(r)
                pyx = list(itertools.islice(it, start, stop, step))
                pyy = list(it)
                msg = "ERR" if myx != pyx or myy != pyy else "ok"
                print(
                    f"{msg}: {r=}, {start=}, {stop=}, {step=}, {myx=}, {pyx=}, {myy=}, {pyy=}"
                )
```

### Linked PRs
* gh-118466
* gh-118559
* gh-118587
* gh-118588

**Comment by rhettinger** [comment]
> This does not correctly handle stop == 0, overwriting it to be sys.maxsize and also assumes its input is an iterator, not any iterable.

Thanks for noticing this.

> It is also just hard to reason about.

The original equivalent code was short and clear:

```
def islice(iterable, *args):
    s = slice(*args)
    it = iter(range(s.start or 0, s.stop or sys.maxsize, s.step or 1))
    nexti = next(it)
    for i, element in enumerate(iterable):
        if i == nexti:
            yield element
            nexti = next(it)
```

The current code was written by Cheryl Sabella to fix https://bugs.python.org/issue27212 .  It does look a little gross but that is mostly because of the newer requirement to catch StopIteration.

> Instead I propose ...

This does look nicer.  

For the last loop, try to come up with a variant that doesn't use a modulo operation in an inner loop. The real C code doesn't do that.  Try to mirror the C code logic as closely as possible so that the performance implications of the code are clear.  

Also, the new code needs to make it clear that the iterator gets consumed all the way to the *stop* argument. The current code does a good job at doing that.

Besides the changes you've already looked at, see if you can find a clean way to make the equivalent not depend on both *slice()* and *range()*.  Ideally, if it is not too messy, we want to communicate the actual *start*, *stop*, *step*, and *cnt* logic that is used in the C code rather than invisibly delegating it without explanation to *slice()* and *range()*.

**Comment by pochmann3** [comment]
Another (also passing your tests):

```python
def islice(iterable, *args):
    s = slice(*args)
    start = s.start or 0
    stop = s.stop
    step = s.step or 1
    indices = count() if stop is None else range(max(stop, start))
    nexti = start
    for i, element in zip(indices, iterable):
        if i == nexti:
            yield element
            nexti += step
```

[Attempt This Online!](https://ato.pxeger.com/run?1=lVKxTgMxDBWM_Qpz0wVCVSSEENINDKwMrFWHo82ViLskygWpR8WXsHQA_gm-BjvOtaBWFWSJ4-fnZzt-_XBdeLBm9Sl146wPoIPywdq6HVTeNpsnJHxqn0x4fwrV6eXXwfVMVaDbWk9VTpHlfa0kHJd-3oqrAeBpoQDG2cvOUGImBIZsWQ-jBFiX_NYlj-o9aGDgWXRrM8OclDzWkwvQFbN1C7fWKFB1q8CXZq7yplzkhEkWFlyEUYugKTX5oqfC9FoiUzXK4CQMPGuXJykJfYOps1gGdg9Fwbk2bjqdVvWsz_ULYeGTIvaWJnn4RuI8DdRdT304fSi1ybmPCyFhTM1NUgnMoab_TNnQ1B7amYSdzJ7tiTrm2BEGsnUuJr9D44joo0kl92ILbLoForVuQ77eovRLEvovU07sYnZrZtiG96q6H6rr9v-p7_brN-0c4ezm7i6jJaE-j4oojNOj2uOr4y3N7GO2O0MRMeI4r3HNt6LoVNkSg1-uYOmLFwnLWH6yrEuGYgMLibdLN5aS3nhvFyEGrJvNcBEywcu6WvH9DQ)

**Comment by pochmann3** [comment]
Or with your first half including the explicit consume-to-start loop:

```python
def islice(iterable, *args):
      s = slice(*args)
      start = s.start if s.start is not None else 0
      stop = s.stop
      step = s.step if s.step is not None else 1
      it = iter(iterable)
      for _ in zip(range(start), it):
          # Consume up to *start* position
          pass
      indices = count(start) if stop is None else range(start, stop)
      nexti = start
      for i, element in zip(indices, it):
          if i == nexti:
              yield element
              nexti += step
```

[Attempt This Online!](https://ato.pxeger.com/run?1=lVI9b9swEEU6-ldclcVy2SABgqIIoCnI2iFrEASqTTlEJR5B0kAUI78ki4e2_yn9KZ16R1IfsAwj5cIT37177073-tu0_hH17k2oxqD1oLy0HrF2s8piM3xCwpe40f7Xxlefv_45-buSFShXq6Wcc2b5vZYCFqVdu_xqBuE4KCBmxPfu2ZdUjaCzGKlqCB1o9PANtQRZOwnnPQdNoqDp32T3RkGqwtF-kYtEUKzKZnvHnaUKLTyA0vCszNyWei3nwVAuKL_vh88pXKN2m0bCxoBHWIS8BRh0yivUo1RTOtcp6xWNgecRhpiKB8_cGDke3I7kRYA7k1o-ecUNMzQyrgQRZSO17zpIchPzpEcFilhpDPBplaxXXaU9LEp_KsLM0wp8-Mni6b_pYV3Olo-l0mmKX2iCd9zbfTISOdzzuykDTR6hXQg4yOzYlql3MfecEmN0md_vz2G8JzafgE37RGitnJ_36y9g9LtEMJofYrY900_ho6pmpNq3_5_65rh-49YEZze3txkvCvf5sQjCND32Hr7auKQZ_sgOVygCxhxjFa36JItPlW0p-eUKtrZ4EbAN9lOEJgUyBmQk3CbdZCV90z01kc-ibraiRcjyuKy7Xbz_AQ)
