### ISSUE TITLE
`sys.stdout.write('hello\n')` flushes

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118541]
# Bug report

### Bug description:

```python
from sys import stdout
import time

stdout.write('hello\n')
time.sleep(10)
stdout.write('world\n')
```

Before sleep:

![before](https://github.com/python/cpython/assets/65588599/ec8049ae-b59d-4ab4-b0ac-6c28fd7fb46e)

After sleep:

![after](https://github.com/python/cpython/assets/65588599/ece30a25-f2a6-44f4-8593-1f30b47292cd)

This causes flickering when displaying text in a CLI, which is how I discovered this.

Current workaround:

```python
from sys import stdout
import time

def stdout_raw_write(s: str, /) -> int:
    """Write to stdout without automatic flusing."""
    pos: int = stdout.tell()
    stdout.buffer.write(s.encode())
    return pos + len(s)

stdout_raw_write('hello\n')
time.sleep(10)
stdout_raw_write('world\n')
```

If that's too disruptive, this could only be fixed for `print()`:

```python
@overload
def print(
    *values: object,
    sep: str | None = " ",
    end: str | None = "\n",
    file: _SupportsWriteAndFlush[str] | None = None,
    flush: Literal[True] | None = None
) -> None: ...

@overload
def print(
    *values: object,
    sep: str | None = " ",
    end: str | None = "\n",
    file: SupportsWrite[str] | None = None,
    flush: Literal[False]
) -> None: ...
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by ronaldoussoren** [comment]
This is not a bug, but is intentional and documented behaviour. 

The [documentation for sys](https://docs.python.org/3/library/sys.html#sys.stdout) says:
> When interactive, the stdout stream is line-buffered. Otherwise, it is block-buffered like regular text files. The stderr stream is line-buffered in both cases. You can make both streams unbuffered by passing the [-u](https://docs.python.org/3/using/cmdline.html#cmdoption-u) command-line option or setting the [PYTHONUNBUFFERED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONUNBUFFERED) environment variable.

**Comment by nineteendo** [comment]
Are you sure this is intentional (at least for `print()`), I didn't ask it to flush? When buffering is disabled, it gets even worse:

```python
from sys import stdout
import time

stdout.write('Hello, ')
time.sleep(10)
stdout.write('world!\n')
```

![before](https://github.com/python/cpython/assets/65588599/7c215cb7-0cd2-4876-8376-7006c5d9cad1)

![after](https://github.com/python/cpython/assets/65588599/5a5434ae-cc1d-4873-916f-95b18d8caf78)

**Comment by nineteendo** [comment]
> Depends on what you mean by worse ;-).

The flickering problem gets worse when it flushes on every write. I clear the screen, write all the text to display, and then flush. Without full buffering, the text will be flickering starting from the second line.

> With this code I only get output at the end (python3.12), because the first call to write doesn't include a newline and hence the output is not flushed in line-buffered mode.

That's because you didn't run the program with `python -u` (like in the text you quoted and the screenshot I sent).

> I don't see any kind of flickering with the code you showed when using Terminal.app, and IMHO that's at best a bug in the terminal emulator you use.

It happens on Pydroid 3 (`BusyBox v1.31.0 (2021-07-12 02:32:24 PDT) multi-call binary`).

**Comment by ronaldoussoren** [comment]
> > Depends on what you mean by worse ;-).
> 
> The flickering problem gets worse when it flushes on every write. I clear the screen, write all the text to display, and then flush. Without full buffering, the text will be flickering starting from the second line.
> 
> > With this code I only get output at the end (python3.12), because the first call to write doesn't include a newline and hence the output is not flushed in line-buffered mode.
> 
> That's because you didn't run the program with `python -u` (like in the text you quoted and the screenshot I sent).

`python -u` runs stdout in unbuffered mode, that results in more screen updates and that can result in flickering when the terminal emulator can't keep up.

Solution: don't run in unbuffered mode, but either run 

If you're trying to implement a full-screen interface you're better of using curses (stdlib) or better yet [rich]( https://pypi.org/project/rich/) or [textual](https://pypi.org/project/textual/). 

I fully expect you get the same behaviour when you write byte strings to stdout using `os.write`, e.g.:

```
import os
import time

os.write(1, b'Hello, ')
time.sleep(10)
os.write(1, b'world!\n')
```

**Comment by nineteendo** [comment]
It also happens on macOS if I take too long to write my text:

```python
from sys import stdout
import time

while True:
    stdout.write('\x1b[H')
    stdout.write('\x1b[J')
    for i in range(5):
        stdout.write(f'{i}\n')
        time.sleep(.01)
    stdout.flush()  # Done
```

<details><summary>show flickering</summary>

![flicker](https://github.com/python/cpython/assets/65588599/4ecd7484-c154-4515-9eda-55d81a137407)
</details>

> `python -u` runs stdout in unbuffered mode, that results in more screen updates and that can result in flickering when the terminal emulator can't keep up.

That was precisely my point.

> If you're trying to implement a full-screen interface you're better of using curses (stdlib) or better yet [rich](https://pypi.org/project/rich/) or [textual](https://pypi.org/project/textual/).

`curses` doesn't work on Windows... I haven't tested the others yet.

> I fully expect you get the same behaviour when you write byte strings to stdout using `os.write`, e.g.:

Yeah, same problem.

**Comment by ronaldoussoren** [comment]
> It also happens on macOS if I take too long to write my text:
> 
> ```python
> from sys import stdout
> import time
> 
> while True:
>     stdout.write('\x1b[H')
>     stdout.write('\x1b[J')
>     for i in range(5):
>         stdout.write(f'{i}\n')
>         time.sleep(.01)
>     stdout.flush()  # Done
> ```
> 
> show flickering

Sure, but that's to be expected because the code clears the terminal and then reemits the output.  That's not the correct way to get high performance full screen terminal UIs in Python or any other language.

> > `python -u` runs stdout in unbuffered mode, that results in more screen updates and that can result in flickering when the terminal emulator can't keep up.
> 
> That was precisely my point.

What should Python do about this? You can improve the experience by explicitly running in buffered mode, by adding the following before the while loop:

```python
stdout = open(1, "w", buffering=4096)
```

That will result in flicker less output with this script, but I'd still look into a library that's meant for textual user interfaces because there's a lot of tricks to improve the quality and performance of the UI.
> 
> > If you're trying to implement a full-screen interface you're better of using curses (stdlib) or better yet [rich](https://pypi.org/project/rich/) or [textual](https://pypi.org/project/textual/).
> 
> `curses` doesn't work on Windows... I haven't tested the others yet.
> 
> > I fully expect you get the same behaviour when you write byte strings to stdout using `os.write`, e.g.:
> 
> Yeah, same problem.


This is not a python bug, the interpreter behaves exactly as documented and intended.

**Comment by nineteendo** [comment]
rich doesn't restore the terminal back to its default settings unlike my own library [ansio](http://pypi.org/project/ansio): https://github.com/Textualize/rich/issues/3354
Also, you could close this as "not planned".

**Comment by terryjreedy** [comment]
To exactly control timing of writing to a terminal, one can write to an io.StringIO and write that to stdout exactly when wanted.

**Comment by nineteendo** [comment]
I wonder if it will handle the text in one step or multiple, as it's still line buffered.
