### ISSUE TITLE
Add thread-safety clarifications to the SSLContext documentation

### ISSUE THREAD

**Issue by mm-matthias** [python/cpython#118596]
# Documentation

Currently there is no documentation that tells anything about whether `SSLContext` is thread-safe or not and how it can be shared between different connections. Knowing how to share the `SSLContext` between different threads and connections is important for example to solve problems like [this](https://github.com/python/cpython/issues/95031).
This issue has also come up [here](https://github.com/psf/requests/pull/6667) where the matter was clarified by @tiran in [this comment](https://github.com/psf/requests/pull/6667):
> `SSLContext` is designed to be shared and used for multiple connections. It is thread safe as long as you don't reconfigure it once it is used by a connection. Adding new certs to the internal trust store is fine, but changing ciphers, verification settings, or mTLS certs can lead to surprising behavior. The problem is unrelated to threads and can even occur in a single-threaded program.

I have reworked this statement into a PR so that it's generally available for future reference.

### Linked PRs
* gh-118597
* gh-120595
* gh-120596

**Comment by nineteendo** [comment]
In 3 days, ask someone to review your pull request here: https://discuss.python.org/c/core-dev/23

**Comment by gpshead** [comment]
thanks!
