### ISSUE TITLE
'set()' would is as same as '{}'

### ISSUE THREAD

**Issue by CNLiuShuhan** [python/cpython#118543]
# Feature or enhancement

### Proposal:

When a set is cleared,the set will become the 'set()'  object,not the '{}' object.I wish 'set()' can as same as '{}'.
```python
>>>a = {1,2,3}
>>>a - {1,2,3}
set()
>>>a -= {1,2,3}
>>>a == {}
False
>>>a is {}
False
```
Thanks!

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by Eclips4** [comment]
Hello!
There's no error, because in Python we do not have an literal for empty set.
```
a = {}
print(type(a))
> <class 'dict'>
```
So, all of your code examples behave as expected. `{}` is stands for "empty dictionary"`.

**Comment by terryjreedy** [comment]
This is a matter of history.  Dicts were present in Python from the beginning, with `dict() == {}`.  Sets were added in early 2.x and `{}` was already taken for an empty dict rather than an empty set.  It would likely be different if both were added at the same time.
