### ISSUE TITLE
Allow perf to work without frame pointers

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#118518]
### Linked PRs
* gh-112254
* gh-118592
* gh-118640
* gh-118646
* gh-118654
* gh-118693
* gh-118708
* gh-130866
* gh-131059

**Comment by hugovk** [comment]
Triage: the linked PRs have been merged, can this be closed or is there more to do?

**Comment by pablogsal** [comment]
Thanks for the ping! Let's close it for now and open new issues we we need them
