### ISSUE TITLE
Window does not resize correctly on KDE

### ISSUE THREAD

**Issue by ZetaMap** [python/cpython#118554]
### Bug description:

I develop a library using tkinter and a people report me a bug with the window size on Fedora using KDE as desktop.

I tested, and the bug seems to only appear on linux distro using KDE.
As you can see in this video, the window not resizing automatically when a widget, like a Frame in this context, is resized with ``widget.config(width=..., height=...)`` function: 

https://github.com/ZetaMap/Kandinsky-Numworks/assets/56844734/e06fd90e-cd19-478d-9063-d9f59f57073b

idk how the bug works because in the video, I tested saving a file and... it works very well so idk...
Anyway, I tested all the ways to change the window size, and only the ``root.configure()`` function works to change the window size, but it's not really practical...

There is minimal code to reproduce the bug : 
```python
import tkinter, time

# Create things
root = tkinter.Tk()
f1 = tkinter.Frame(root)
f2 = tkinter.Frame(root)
# Pack everything
f1.pack()
f2.pack()
root.update()
root.resizable(0,0)
# Set default size
f1.config(width=200, height=300)
f2.config(width=100, height=200)
root.update()
# Sleep a little
time.sleep(2)
# And change the frame size
root.resizable(1,1)
f1.config(width=500, height=100)
f2.config(width=300, height=100)
root.update()

root.mainloop()
```
it will create the main window, create frames, disable resizing by user, change the size of frames, wait a little, enable resizing by user, and change another time the frames size.

And if you test this on a linux distro using KDE, it will work randomly and sometimes, only the width axis is resized. Like in the video:

https://github.com/python/cpython/assets/56844734/5e09eb5c-9d2a-469e-a46b-25c44f3e1ee4

Also if you want, there is [the function resizing the frames](https://github.com/ZetaMap/Kandinsky-Numworks/blob/c4221cb97cb348fe541c97b085b0b9158c016a82/src/kandinsky/util/stuff/gui.py#L167), of my library, i found a fix for linux but i don't like it because i need to know the size of the window. For local tests, there is the link to [the github repo](https://github.com/ZetaMap/Kandinsky-Numworks)
To install by pypi way: ``pip3 install --pre kandinsky ion-numworks``, and you can test with the demo game by running: ``python3 -m kandinsky``

So, as i say, the bug only appears on KDE desktop, and it doesn't matter whether Wayland or X11 is used.
Also idk if we can find a temporary fix for me, this will save me from making a dependency on a new version, if it's really a bug.

So thanks for your reply, and have a nice day =).

---

I think i found another bug when i tested my fix on Windows.
When ``root.configure("<width>x<height>")`` is called, the function ``widget.config(width=..., height=...)`` cannot resize the window, the size is fixed and we need to recreate a window.

Code to reproduce the bug:
```python
import tkinter, time

# Create things
root = tkinter.Tk()
f1 = tkinter.Frame(root)
f2 = tkinter.Frame(root)
# Pack everything
f1.pack()
f2.pack()
root.update()
root.resizable(0,0)
# Set default size
f1.config(width=200, height=300)
f2.config(width=100, height=200)
root.update()
# Sleep a little
time.sleep(2)
# Fix the size
root.geometry("600x400")
root.update()
# And wait a little
time.sleep(2)
# And change the frame size
root.resizable(1,1)
f1.config(width=500, height=100)
f2.config(width=300, height=100)
root.update()

root.mainloop()
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by ZetaMap** [comment]
Issue also related to tcl/tk support: https://core.tcl-lang.org/tk/tktview/3733b924a2c3d5df2607fbcde54eb0c3bca19cd1

**Comment by ZetaMap** [comment]
according to the tcl/tk support conversation, it appears to be a KWin bug and not KDE

**Comment by ZetaMap** [comment]
anyone ? no ? this bug is not important ? @terryjreedy

**Comment by zware** [comment]
As you mentioned, this looks like a KWin bug, not `tkinter` or even Tcl/Tk.  I'm sorry we can't help.

**Comment by terryjreedy** [comment]
Stackoverflow or a KWin-specific forum, if any, would be places to ask about working around KWin bugs.
