### ISSUE TITLE
Cannot pickle private inner classes

### ISSUE THREAD

**Issue by Atry** [python/cpython#118538]
# Bug report

### Bug description:

```python
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class MyOuterClass:
...     class MyInnerClass:
...         pass
...     @staticmethod
...     def public_inner():
...         return __class__.MyInnerClass()
...     class __MyInnerClass:
...         pass
...     @staticmethod
...     def private_inner():
...         return __class__.__MyInnerClass()
... 
>>> import pickle
>>> pickle.dumps(MyOuterClass.public_inner())
b'\x80\x04\x95-\x00\x00\x00\x00\x00\x00\x00\x8c\x08__main__\x94\x8c\x19MyOuterClass.MyInnerClass\x94\x93\x94)\x81\x94.'
>>> pickle.dumps(MyOuterClass.private_inner())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
_pickle.PicklingError: Can't pickle <class '__main__.MyOuterClass.__MyInnerClass'>: attribute lookup MyOuterClass.__MyInnerClass on __main__ failed
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by AlexWaygood** [comment]
This is a known limitation of the pickle module. The docs for the module state:

> Note that functions (built-in and user-defined) are pickled by fully [qualified name](https://docs.python.org/3/glossary.html#term-qualified-name), not by value. [[2]](https://docs.python.org/3/library/pickle.html#id8) This means that only the function name is pickled, along with the name of the containing module and classes. Neither the function’s code, nor any of its function attributes are pickled. Thus the defining module must be importable in the unpickling environment, and the module must contain the named object, otherwise an exception will be raised. [[3]](https://docs.python.org/3/library/pickle.html#id9)
> 
> Similarly, classes are pickled by fully qualified name, so the same restrictions in the unpickling environment apply. Note that none of the class’s code or data is pickled, so in the following example the class attribute attr is not restored in the unpickling environment:
> 
> ```py
> class Foo:
>     attr = 'A class attribute'
> 
> picklestring = pickle.dumps(Foo)
> ```
> 
> These restrictions are why picklable functions and classes must be defined at the top level of a module.

https://docs.python.org/3/library/pickle.html#what-can-be-pickled-and-unpickled

Since this is a documented limitation, I'm closing this for now, but I'm happy to reopen if you have a specific, workable proposal for how to lift this limitation :-)

**Comment by Atry** [comment]
@AlexWaygood I think it's not a documented limitation. 

The root cause is that `__MyInnerClass`'s `__qualname__` is set to `MyOuterClass.__MyInnerClass`, which is not name-mangled. When unpickling the the object, it is still possible to perform name-mangling to the convert it to the correct attribute name - `_MyOuterClass__MyInnerClass` even though the current implementation does not.

The document did not specify how to convert qualified name to the path of attribute names. In fact, the implementation is buggy because it does not perform name-mangling therefore it does not build the correct path of attribute names.

**Comment by Atry** [comment]
@AlexWaygood Could you reopen this issue because it is not a documented limitation?
