### ISSUE TITLE
Noted an issue while using input()

### ISSUE THREAD

**Issue by chandra122** [python/cpython#118637]
# Bug report

### Bug description:

Version used: python3.10 with venv -
[PythonPractice](https://github.com/python/cpython/assets/28337249/09a77aba-a243-4cae-8a30-2353e66c2a2c)
```
value = int(input())
# Trying to pass an integer value from command prompt ex: 4 throws

Traceback (most recent call last):
  File "D:\PythonPractice\Algorithms And Data Structures\linearsearchexamples.py", line 13, in <module>
    value = int(input().strip())
            ^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: ''
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello! This repository is intended as CPython bug tracker.
Ask for help here, please: https://discuss.python.org/c/users/7
