### ISSUE TITLE
Dead link for `linspace` recipe

### ISSUE THREAD

**Issue by trag1c** [python/cpython#118671]
# Documentation

https://github.com/python/cpython/blob/00d913c6718aa365027c6dcf850e8f40731e54fc/Doc/library/stdtypes.rst?plain=1#L1497-L1501

The "See also" section for `range` seems to have a dead link to the linspace recipe: https://code.activestate.com/recipes/579000/

### Linked PRs
* gh-118730
* gh-118754

**Comment by hugovk** [comment]
Here's a working link, would you like to open a PR to fix it? 

https://code.activestate.com/recipes/579000-equally-spaced-numbers-linspace/

Might be worth grepping for other broken ActiveState links.

**Comment by trag1c** [comment]
Sure! I'll also look for others :)
