### ISSUE TITLE
Remove shebang and executable bit from most modules

### ISSUE THREAD

**Issue by jaraco** [python/cpython#118673]
# Feature or enhancement

### Proposal:

In https://github.com/jaraco/backports.tarfile/issues/4, I discovered that the presence of a shebang and executable bit on the `tarfile` module signals to downstream packagers and users that the module can be treated like a script and executed directly. That expectation seems to stem from an incidental artifact of the original contribution happening to have been written as a script. In fact, back in those days, many developers including myself would add `#!/usr/bin/env python` to a Python file just to signal that the syntax was Python, so it may never have been intended to be executed directly.

Nevertheless, the presence of the shebang led to it being marked as executable in #64135.

Marking this module as executable prevents the module from ever being ported to a package (such as `backports.tarfile` does) without breaking that assumption. It also tempts users to execute a module with the incorrect Python version. Instead, users should be directed to runpy invocation (i.e. `python -m tarfile`).

This proposal only includes tarfile in the scope, but it also implies that other modules changed in #64135 should also have their shebangs removed except where explicitly desired (and presumably documented or tested as such).

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-118674
* gh-119658

**Comment by jaraco** [comment]
In the prior bug, gpshead [indicated](https://github.com/python/cpython/issues/64135#issuecomment-1093638240) that these shebangs should probably be removed.

@serhiy-storchaka Do you have any objections to removing executable bits and shebang from tarfile and maybe others?

**Comment by serhiy-storchaka** [comment]
I think it made more sense in the past, when:
* `python -m` did not exist.
* There was usually only one system Python.
* Python module (like `pydoc`) could be turned into a command by a symlink.
* In general, the stdlib code supported compatibility with several Python versions.

Today this is perhaps no longer relevant or less relevant. But it needs to be discussed with a wider audience to shape general policy.

**Comment by jaraco** [comment]
[Summarized and posted](https://discuss.python.org/t/removing-executable-bits-and-shebangs-from-incidental-modules/53532) in discourse.

**Comment by merwok** [comment]
See also https://github.com/python/cpython/issues/85792#issuecomment-1093881384 for previous discussion

**Comment by jaraco** [comment]
Sounds good. The consensus in the discourse is that we can remove them. I'll start a new PR as such.

**Comment by XuehaiPan** [comment]
How about adding `pre-commit` checks for this?

```yaml
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: destroyed-symlinks
```

------

https://github.com/python/cpython/blob/94e9585e99abc2d060cedc77b3c03e06b4a0a9c4/.pre-commit-config.yaml#L22-L34

**Comment by jaraco** [comment]
That seems reasonable. Probably relates more to the earlier PR to make things consistent than to this one (as the checks would pass both before and after). Feel free to prepare a PR.

**Comment by terryjreedy** [comment]
Not backporting this to 3.13 and 3.12 at least for turtledemo examples made it impossible to backport fixes to their docstrings without getting a merge conflict.  They all (most?) start with something like the following, with an unneeded first line and a now incorrect file name.
```
"""     turtle-example-suite:

             tdemo_bytedesign.py
```
I considered asking about backporting just the turtledemo changes, but it might be easier to write a program to make the changes and apply it to both main and 3.13 branches.
