### ISSUE TITLE
urllib.parse.quote docstring has invalid reStructuredText markup

### ISSUE THREAD

**Issue by stevepiercy** [python/cpython#118688]
# Bug report

### Bug description:

When using Sphinx to build documentation for themes that use the [Kitchen Sink](https://sphinx-themes.org/sample-sites/python-docs-theme/kitchen-sink/api/), which attempts to parse the docstring from urllib, I observe an error message.

`/opt/homebrew/Cellar/python@3.12/3.12.3/Frameworks/Python.framework/Versions/3.12/lib/python3.12/urllib/parse.py:docstring of urllib.parse.quote:13: ERROR: Unexpected indentation.`

These two lines of the docstring cannot be parsed:

https://github.com/python/cpython/blob/3.12/Lib/urllib/parse.py#L869-L870

```
    sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
                  / "*" / "+" / "," / ";" / "="
```

By adding a trailing `\` to line 869, it can be parsed. Alternatively, line 870 could be dedented to align with `sub-delims`.

I assume that all docstrings should have valid reStructuredText markup.

I am happy to submit a pull request with the preferred solution, whether it is one of these two or something else.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by encukou** [comment]
> I assume that all docstrings should have valid reStructuredText markup.

That is not the case. What are you basing this assumption on?

**Comment by stevepiercy** [comment]
@encukou https://peps.python.org/pep-0287/

**Comment by encukou** [comment]
Thanks. I see where the confusion is coming from.
PEP 287 is an informational PEP, [that is](https://peps.python.org/pep-0001/#pep-types):
> Informational PEPs do not necessarily represent a Python community consensus or recommendation, so users and implementers are free to ignore Informational PEPs or follow their advice.

And that PEP itself says (although in places obvious that aren't obvious now -- the PEP predates both Sphinx and Markdown):
- > reStructuredText is being proposed as a standard, not the only standard. Its use will be entirely optional.
- > The current policy for docstrings in the Python standard library is that they should be no more than concise hints, simple and markup-free (although many do contain ad-hoc implicit markup).


I'll close this issue, but join the doc-sig mailing list and ask about the PEP there.
