### ISSUE TITLE
Initialize/Finalize Python multiple time and import datetime each time lead to a memory corruption

### ISSUE THREAD

**Issue by neonene** [python/cpython#118608]
# Crash report

### What happened?

Example on Windows (debug build):

```py
# Taken from _ctypes issue: #116467
import subprocess
program = r"PCbuild\amd64\_testembed_d.exe"
cmd = [program, "test_repeated_init_exec", "import datetime"]   # or _datetime

for i in range(1, 11):
    print(f"   == Process #{i} ===")
    proc = subprocess.run(cmd)
    exitcode = proc.returncode
    print(f"=> exitcode {exitcode}")
    if exitcode:
        break
    print()
```

Output (7bbce383fa207ad83a6221bf70678c75c3c92142: CI failures with a similar test):
```
Running Debug|x64 interpreter...
   == Process #1 ===
--- Loop #1 ---
--- Loop #2 ---
Assertion failed: PyUnicode_CheckExact(ep_key), file C:\a\Objects\dictobject.c, line 1119
=> exitcode 3
```

It is an expected error on a debug build, which comes form [`_PyUnicode_ClearInterned()`](https://github.com/python/cpython/blob/ea2c0016502472aa8baa3149050ada776d17a009/Objects/unicodeobject.c#L14679) in `unicodeobject.c` of the commit ea2c001:

```c
void
_PyUnicode_ClearInterned(PyInterpreterState *interp)
{
    ...
    /* TODO:
     * Currently, the runtime is not able to guarantee that it can exit without
     * allocations that carry over to a future initialization of Python within
     * the same process. i.e:
     *   ./python -X showrefcount -c 'import itertools'
     *   [237 refs, 237 blocks]
     *
     * Therefore, this should remain disabled for until there is a strict guarantee
     * that no memory will be left after `Py_Finalize`.
     */
#ifdef Py_DEBUG
    ...
```
Currently, release builds avoid the `datetime` crash by leaking all interned strings.  Both the crash and the leak should be fixed before shipping 3.13 final.

<br>

This dedicated issue is requested in:

* #103092

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-118531

**Comment by vstinner** [comment]
Which parts of the code use interned strings?

**Comment by neonene** [comment]
If you mean `_datetimemodule.c`, `_datetime_exec()` is a place where assertion errors occur, trying to access dict keys (invalid interned strings).

https://github.com/python/cpython/blob/a8e5fed1007233f677d3539162257b99b920df00/Modules/_datetimemodule.c#L6871-L6918

**Comment by vstinner** [comment]
With a debug build, I confirm that an assertion fails at the first `PyDict_SetItemString()` call on `PyDateTime_DeltaType.tp_dict`, on the second `_datetime_exec()` call.

```c
PyObject *d = PyDateTime_DeltaType.tp_dict;
DATETIME_ADD_MACRO(d, "resolution", new_delta(0, 0, 1, 0));
```

For me, the root issue is that datetime doesn't use heap types but static types.

The symptom is that PyDict_SetItemString() calls PyUnicode_InternInPlace() and so stores interned strings, but interned strings are cleared at Python exit: in Py_Finalize().

Interned strings are just one symptom, but I expect other side effects of reusing static types between two Python executions.

IMO only isolated extensions are safe to be used with the "sub-interpreter" case:

* Use multiple interpreters using sub-interpreters
* Or init/finalize Python multiple times which is a similar but different case

**Comment by vstinner** [comment]
> Initialize/Finalize Python multiple time and import datetime each time lead to a memory corruption

That's one way to see the issue. Another way to see is that Python doesn't support datetime with "sub-interpreters" (see my previous message). This issue is about supporting sub-interpreters in datetime :-)

**Comment by neonene** [comment]
>Isolated sub-interpreters are not allowed to load a single-phase init module.

See: [PEP 554](https://peps.python.org/pep-0554/#interpreter-restrictions),  [C-API](https://docs.python.org/3/c-api/init.html?highlight=check_multi_interp_extensions#c.PyInterpreterConfig)

That's why PEP-687 needs to be completed.

**Comment by vstinner** [comment]
> Yes, but you prevented me from the heap types conversion at https://github.com/python/cpython/issues/103092#issuecomment-2024497734.

Right, I am afraid of regression. We should do the conversion in a specific order, step by step, to limit risk and be able to rollback if everything goes wrong.

> What case are you expecting?

Objects must not be shared between interpreters, including types. Each interpreter should have its own types to prevent any race condition / concurrent accesses, especially when each interpreter has its own GIL. I don't recall details.

It doesn't matter much. We both agree to isolate the extension.

My proposed plan: https://github.com/python/cpython/issues/117398#issuecomment-2094919605

**Comment by neonene** [comment]
Can the isolation be backported to 3.13?  Your concern for the sub-interpreters is another dedicated issue, which is not confirmed on release builds right now.

**Comment by vstinner** [comment]
> Can the isolation be backported to 3.13?

I prefer to not backport such large change.

For 3.12 and 3.13, we may just stop clearing interned strings at exit, and only do that at Py_Main() exit.
