### ISSUE TITLE
pathlib.Path().is_dir() & .is_file() return wrong or inconsistent results

### ISSUE THREAD

**Issue by dreamflow** [python/cpython#118652]
# Bug report

### Bug description:

`pathlib.Path().is_dir()` and `.is_file()` return
wrong or inconsistent results in the following examples :

```python
import pathlib
pathlib.Path(  ).is_dir () # -> True  # result wrong
pathlib.Path("").is_dir () # -> True  # result wrong
pathlib.Path(  ).is_file() # -> False # result inconsistent
```
expected would be the same correct results
that these corresponding method calls return :

```python
import pathlib , os
pathlib.Path("").is_file() # -> False
os.path.isdir (  ) # -> TypeError "missing required argument"
os.path.isdir ("") # -> False
os.path.isfile(  ) # -> TypeError "missing required argument"
os.path.isfile("") # -> False
```

### CPython version tested on:

```
python -VV
> Python 3.12.3 [MSC v.1938 64 bit (AMD64)]
```

### Operating system tested on:

Windows 10 64bit 22H2

**Comment by nineteendo** [comment]
Works as expected, they are equivalent to `'.'`:

```python
>>> import pathlib
>>> pathlib.Path()
PosixPath('.')
>>> pathlib.Path('')
PosixPath('.')
>>> pathlib.Path('.')
PosixPath('.')
```

And `os.stat()` raises an error for `''`, which is suppressed by `os.path.isdir()` & `os.path.isfile()`:

```python
>>> import os
>>> os.stat('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by dreamflow** [comment]
@nineteendo
thanks for the details ! now i understand
why `pathlib.Path("").is_dir()` returns `True`

but `pathlib.Path().is_dir() -> True`
doesn't feel right and also not that
without the path arg , `.is_dir()` returns
the opposite of `.is_file()` .

```python
import pathlib
pathlib.Path().is_dir () # -> True
pathlib.Path().is_file() # -> False
```

i'm wondering , if or what could be the intent or advantage
of not raising TypeError "missing required argument"
when the path arg is not provided in `Path()` for
`.is_dir()` or `.is_file()` ?

**Comment by eryksun** [comment]
> i'm wondering , if there is an intent or advantage
not to raise TypeError "missing required argument"
when the path arg is not provided in `Path()` for
`.is_dir()` or `.is_file()`

`pathlib.Path()` is equivalent to `pathlib.Path('.')`. This is [documented behavior](https://docs.python.org/3/library/pathlib.html#pure-paths).
