### ISSUE TITLE
Add TypeVar defaults for Generator and AsyncGenerator

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#118647]
Now that PEP 696 has landed, we should add defaults to the Generator and AsyncGenerator types for the send and return types.

cc @Gobot1234 @Daverball (https://github.com/python/typeshed/pull/11867#issuecomment-2095879825)

### Linked PRs
* gh-118648

**Comment by Gobot1234** [comment]
#110212 seems related as well
