### ISSUE TITLE
Inconsistent return types between SSLSocket and SSLObject certificate chain APIs

### ISSUE THREAD

**Issue by sethmlarson** [python/cpython#118658]
# Bug report

### Bug description:

The `get_verified_chain()` and `get_unverified_chain()` APIs for `SSLSocket` were updated in https://github.com/python/cpython/pull/109113, but the API wasn't updated for `SSLObject`. This leads to inconsistent return types, one returns `_ssl.Certificate` and the other returns `bytes`. It appears from https://github.com/python/cpython/pull/109113 that `bytes` is what's expected.

This [caused an issue for Windows and macOS](https://github.com/pypa/pip/pull/12662#issuecomment-2093887075) using Truststore which relies on these APIs for verifying certificates. A bugfix is coming for Truststore, but these APIs should return the same type.

cc @matiuszka

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-118669
* gh-123082
* gh-124598
* gh-124599
* gh-124972

**Comment by matiuszka** [comment]
Good catch. I overlooked this. I will fix it ASAP.

**Comment by matiuszka** [comment]
I fixed the types, sorry for the problems.
