### ISSUE TITLE
Add example of overload with default values

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118706]
# Documentation

Could we add an example of an overload with default values? e.g.

```python
@overload
def foo(*, bar: None = None) -> None: ...
@overload
def foo(*, bar: bool) -> bool: ...  # required argument
def foo(*, bar: bool | None = None) -> bool | None: ...
```

I wrote this with an ellipsis, which has overlap:

```python
@overload
def foo(*, bar: None = None) -> None: ...  # Overloaded function signatures 1 and 2 overlap with incompatible return types
@overload
def foo(*, bar: bool = ...) -> bool: ...
def foo(*, bar: bool | None = None) -> bool | None: ...
```

### Linked PRs
* gh-118726

**Comment by nineteendo** [comment]
Do we add it to the PEP, or do we modify the example in the docs?

```python
@overload
def process(response: None) -> None:
    ...
@overload
def process(response: int) -> tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response):
    ...  # actual implementation goes here
```

**Comment by davidlowryduda** [comment]
> Do we add it to the PEP, or do we modify the example in the docs?

It's not necessary to write a PEP for this. If you know where you think an example would fit well in the docs, then you can make a pull request with that change. Each pull request should typically cite an issue, and this issue would be a good issue to cite.

**Comment by nineteendo** [comment]
No, not a new PEP, I meant adding it to the other examples in the existing PEP: https://peps.python.org/pep-0484/#function-method-overloading.

**Comment by JelleZijlstra** [comment]
We don't change old PEPs. New examples should either be added to the CPython documentation (in this case, `Doc/library/typing.rst`) or the typing spec in https://github.com/python/typing.

**Comment by nineteendo** [comment]
I suggest we modify the example like this:

```python
@overload
def process(response: None = ...) -> None:
    ...
@overload
def process(response: int) -> tuple[int, str]:
    ...
@overload
def process(response: bytes) -> str:
    ...
def process(response=None):
    ...  # actual implementation goes here
```

Should we mention overlap as well?

```python
@overload
def unsafe_func(x: int = ...) -> int:
    ...
@overload
def unsafe_func(x: str = ...) -> str:
    ...
def unsafe_func(x = "abc"):
    return x
```

**Comment by nineteendo** [comment]
Do we close this or not? You rejected both my pull requests.

**Comment by JelleZijlstra** [comment]
Yes, I don't think there's anything to do here for CPython.
