### ISSUE TITLE
it seems "python -m ensurepip" fails when installing from python .org, on windows for python-3.13.0b1

### ISSUE THREAD

**Issue by stonebig** [python/cpython#118788]
# Bug report

### Bug description:

installing from python.org the Windows 64 installer x64.... no pip at the end of installation

trying (insisting) with a "python -m ensurepip" also blows out with a 

````
                ~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\WPy64-31300b1\python-3.13.0b1.amd64\Lib\tempfile.py", line 384, in mkdtemp
    _os.mkdir(file, 0o700)
    ~~~~~~~~~^^^^^^^^^^^^^OSError: [WinError 1332] Le mappage entre les noms de compte et les ID de sécurité n’a pas été effectué
````

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by stonebig** [comment]
and it was apparently ok for python-3.13.0a6 under same conditions

**Comment by JelleZijlstra** [comment]
cc @zooba. The error also appeared in #118773 (except it wasn't in French :) ).

**Comment by zooba** [comment]
Okay, same issue as the other one. Let's close this and keep focus over there.

We need to figure out what's special about the failing machines that they can't recognise standard ACL types.
