### ISSUE TITLE
Pathlib.Path.symlink_to() returns None instead of a valid object

### ISSUE THREAD

**Issue by adventurecomputer** [python/cpython#118704]
# Bug report

### Bug description:

```python
# Add a code block here, if required
from pathlib import Path
source=Path('link')
target=Path('target')
link=source.symlink_to(target)

print(link) # returns None

```

link is supposed to be a newly created symlink object.

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by eryksun** [comment]
The `symlink_to()` and `hardlink_to()` methods create a symlink or hardlink in the filesystem, but they do not return a `Path` object for it. This could be new behavior for a feature enhancement in Python 3.14, but it's not a bug.

**Comment by barneygale** [comment]
pathlib doesn't `return self` to facilitate method chaining at the moment. I'd rather not add support because it doesn't seem necessary and complicates the API slightly. But I'll keep an open mind if you'd like to put together a rationale @adventurecomputer!

**Comment by adventurecomputer** [comment]
I was testing codellama in my workflow, and this snippet came up as one of the suggestions. It seemed reasonable to assume the pattern of `<returned object> = <object>.instance_method()` was being followed and using pydoc the results don't show types of the return, so I assumed this was the case.
