### ISSUE TITLE
Future created by concurrent process pool executor is not a Future

### ISSUE THREAD

**Issue by shawn-peng** [python/cpython#118783]
# Bug report

### Bug description:

Future created by process pool executor can not be awaited

```python
import asyncio
from concurrent.futures import ProcessPoolExecutor

def bar():
    return True

if __name__ == '__main__':
    executor = ProcessPoolExecutor(2)
    
    task = executor.submit(bar)
    print(task)
    
    loop = asyncio.get_event_loop()
    print(loop.run_until_complete(task))
```

Reporting this,
```
<Future at 0x7f5c1ddf09a0 state=running>

Traceback (most recent call last):
  File "/mnt/e/workspace/DecoyFree_MSFDR/tests/future_test.py", line 17, in <module>
    print(loop.run_until_complete(task))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 628, in run_until_complete
    future = tasks.ensure_future(future, loop=self)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 615, in ensure_future
    return _ensure_future(coro_or_future, loop=loop)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 631, in _ensure_future
    raise TypeError('An asyncio.Future, a coroutine or an awaitable '
TypeError: An asyncio.Future, a coroutine or an awaitable is required
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
The `concurrent.futures.Future` is not the same as `asyncio.Future`, albeit the same name. That's why we have namespaces :)

**Comment by shawn-peng** [comment]
:) Disappointed. Found a work around, it's stupid though,

```python
import asyncio
from concurrent.futures import ProcessPoolExecutor

def bar():
    return True

def executor_submit(executor, func, *args):
    async def _wrap_future():
        return executor.submit(func, *args).result()
    return _wrap_future()

if __name__ == '__main__':
    executor = ProcessPoolExecutor(2)

    # task = executor.submit(bar)
    task = executor_submit(executor, bar)

    print(task)

    loop = asyncio.get_event_loop()

    print(loop.run_until_complete(task))
```

**Comment by zware** [comment]
That's not going to nice things to your event loop.  Have a look at the [`loop.run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) method.

**Comment by shawn-peng** [comment]
Not sure what you mean by "nice things to your event loop". I don't like the run_in_executor() method because I have to create the executor before the loop runs. However, I don't know what kind of an executor is needed at the beginning of the program.

**Comment by shawn-peng** [comment]
> That's not going to nice things to your event loop. Have a look at the [`loop.run_in_executor()`](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.loop.run_in_executor) method.

Hi @zware, thanks! Not sure what you mean by "nice things to your event loop". I don't like the run_in_executor() method because I have to create the executor before the loop runs. However, I don't know what kind of an executor is needed at the beginning of the program.

Would you please explain more about the problem using a wrapper function?

**Comment by zware** [comment]
The problem with the workaround you showed is that the call to `task.result()` in `executor_submit` will block the event loop.  `loop.run_in_executor` works exactly as your `executor_submit`, but does *not* block the event loop, allowing other coroutines to run while waiting for the result from the executor.

**Comment by shawn-peng** [comment]
> The problem with the workaround you showed is that the call to `task.result()` in `executor_submit` will block the event loop. `loop.run_in_executor` works exactly as your `executor_submit`, but does _not_ block the event loop, allowing other coroutines to run while waiting for the result from the executor.

Ah, I see. Thanks a lot @zware. Much appreciated! We should add some references in the doc of executor_submit(). I can help with that. What do you think?

**Comment by zware** [comment]
I'm not sure what you're wanting to add; can you give an example?

**Comment by shawn-peng** [comment]
I want to add something like the following in the documet of `executor.submit`
'If you have an asyncio loop is running and you have other tasks running in it and don't want them to be blocked while waiting the results, please use `loop.run_in_executor` to submit the jobs. The `loop.run_in_executor` method will create futures that can be awaited by asyncio interfaces. Please check the doc for details.'
