### ISSUE TITLE
"Paste mode" in the new REPL does not display the result of evaluated expressions

### ISSUE THREAD

**Issue by AlexWaygood** [python/cpython#118893]
We've discovered that if you manually type out a condition that evaluates to `False` in the new REPL, `False` is printed as the result, as expected...

```pycon
>>> (3, 13, 0, "final") < (3, 13, 0, "beta")
False
```

...but that if you copy and paste this condition into the REPL, nothing is printed (implying that the condition evaluates to `None`:

```pycon
>>> (3, 13, 0, "final") < (3, 13, 0, "beta")
>>> 
```

Thanks @Eclips4 for realising that the difference in behaviour here was due to copying-and-pasting the condition rather than typing it out!

_Originally posted by @AlexWaygood in https://github.com/python/cpython/issues/111201#issuecomment-2102541362_
            

### Linked PRs
* gh-119318
* gh-119408

**Comment by serhiy-storchaka** [comment]
It is not only with conditions, but with any expressions, including literals.

**Comment by AlexWaygood** [comment]
Looks like this is now fixed! (@pablogsal or @ambv please reopen if there's more to do!)
