### ISSUE TITLE
argparse: when wrong choice is selected, the error message prints available choices using `repr()` instead of `str()`

### ISSUE THREAD

**Issue by rindeal** [python/cpython#118839]
# Bug report

### Bug description:

 I tried using StrEnum for choices and it printed `choose from <Enum.FOO: 'foo'>, ...` instead of `choose from foo, ....`.

Fix in https://github.com/python/cpython/pull/117766

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-117766

**Comment by serhiy-storchaka** [comment]
This is actually a duplicate of #86357.
