### ISSUE TITLE
Inconsistent output of Theil-Sen regression for two same arrays with length lareger than 141

### ISSUE THREAD

**Issue by Yuhang-Zhang** [python/cpython#118884]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
import numpy as np
from sklearn.linear_model import TheilSenRegressor

a = np.random.rand(141)
b = np.random.rand(141)
a = a.reshape(-1,1)

for i in range(5):
    t = TheilSenRegressor()
    t.fit(a,b)
    print(t.coef_)
    print(t.intercept_)

c = np.random.rand(142)
d = np.random.rand(142)
c = c.reshape(-1,1)

for i in range(5):
    t = TheilSenRegressor()
    t.fit(c,d)
    print(t.coef_)
    print(t.intercept_)

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by nineteendo** [comment]
Please put your code in a code block;

    ```python
    # code here
    ```

**Comment by hauntsaninja** [comment]
While certainly interesting, this question is better off asked on the sklearn issue tracker. You might also want to look into the random_state argument.

**Comment by hauntsaninja** [comment]
From looking at the code, it's because https://github.com/scikit-learn/scikit-learn/blob/872124551/sklearn/linear_model/_theil_sen.py#L430 crosses 1e4

```
>>> np.rint(binom(141, 2))
9870.0
>>> np.rint(binom(142, 2))
10011.0
```

**Comment by Yuhang-Zhang** [comment]
> From looking at the code, it's because https://github.com/scikit-learn/scikit-learn/blob/872124551/sklearn/linear_model/_theil_sen.py#L430 crosses 1e4
> 
> ```
> >>> np.rint(binom(141, 2))
> 9870.0
> >>> np.rint(binom(142, 2))
> 10011.0
> ```

Hi, thank you very much for your reply! Sorry but I don't completely understand the meaning and the difference between np.rint(binom(141,2)) and np.rint(binom(142,2)). Actually I am doing a regression with data from two instruement measurements, so do you have any suggestion for this problem?
