### ISSUE TITLE
``asyncio REPL`` is not working on Windows

### ISSUE THREAD

**Issue by lschoe** [python/cpython#118817]
# Bug report

### Bug description:

Running the asyncio REPL with Python 3.13b1 on Windows gives 

```python
>py -3.13  -m asyncio
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Berry\AppData\Local\Programs\Python\Python313\Lib\asyncio\__main__.py", line 126, in <module>
    readline.set_completer(completer.complete)
    ^^^^^^^^
```
due to missing `readline` package.

Easy to fix by removing
https://github.com/python/cpython/blob/2f4db5a04d6fa7ba5c1c6b82b482dd7ca48f3382/Lib/asyncio/__main__.py#L108-L111
and inserting `import readline  # NoQA` before line 121:
https://github.com/python/cpython/blob/2f4db5a04d6fa7ba5c1c6b82b482dd7ca48f3382/Lib/asyncio/__main__.py#L120-L126

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-118819
* gh-118847

**Comment by Eclips4** [comment]
Thanks for the report!
