### ISSUE TITLE
Add canonical url for 3.14

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118857]
# Documentation

Currently you get a 404 when you go to http://docs.python.org/3.14, shouldn't we build it now development on 3.14 has started?

**Comment by Eclips4** [comment]
cc @hugovk

**Comment by hugovk** [comment]
@JulienPalard Does https://github.com/python/docsbuild-scripts need configuring for 3.14? Anything else? 

The devguide has been updated with the new branch info: https://github.com/python/devguide/pull/1319

Is this included in PEP 101, or does it need adding?

**Comment by nineteendo** [comment]
It's possible that we need to wait a couple more hours until it becomes available, as your commit is less than 24 hours ago: https://github.com/python/devguide/commit/0c56002c0b40358c25a397d8a3dce2a814824859

**Comment by nineteendo** [comment]
The docs just updated, and now there's an actual dead link:

![image](https://github.com/python/cpython/assets/65588599/c261d1f7-869e-4656-88c6-957f3aff5197)

> Last updated on May 09, 2024 (18:23 UTC).

**Comment by JulienPalard** [comment]
> The docs just updated, and now there's an actual dead link and the version select doesn't work:

The script is probably just building them. It takes time to build all translations.

**Comment by nineteendo** [comment]
Maybe, but if the problem doesn't resolve itself tomorrow, we'll need to investigate.

**Comment by nineteendo** [comment]
Still not fixed. Which workflow builds these?

**Comment by nineteendo** [comment]
Can you check them to see what's going on?

**Comment by nineteendo** [comment]
Well, apparently it seems to be a CDN issue. The wayback machine could load it: https://web.archive.org/web/20240510202408/https://docs.python.org/3.14.

**Comment by hugovk** [comment]
https://docs.python.org/3.14/ is loading for me now 👍

> Last updated on May 10, 2024 (19:04 UTC).

**Comment by nineteendo** [comment]
It's also loading for me now. You should've confirmed that first.
