### ISSUE TITLE
Zero-valued flag enum has no name

### ISSUE THREAD

**Issue by apple1417** [python/cpython#118820]
# Documentation

Quoting `Doc/howto/enum.rst:1148`:
```rst
- names of pseudo-flags are constructed from their members' names::

    >>> (Color.RED | Color.GREEN).name
    'RED|GREEN'
```
This section was originally added in 7aaeb2a3.

If you have a zero-valued flag, and you didn't explicitly give it a name, this doesn't seem to apply, it returns `None` instead.
```py
class NoZero(Flag):
    ONE = 1

class HasZero(Flag):
    ZERO = 0
    ONE = 1

print(NoZero(0).name, type(NoZero(0).name))   # None <class 'NoneType'>
print(HasZero(0).name, type(HasZero(0).name)) # ZERO <class 'str'>
```

I'm not entirely sure if this should be considered a documentation issue or a bug report (or both). It doesn't really feel like zero should be treated any differently from other unnamed combinations. But at the same time, I've tested, and this is already the existing behavior in 3.10 through 3.12, and it doesn't seem to be documented anywhere.

### Linked PRs
* gh-118848
* gh-120758
* gh-120759

**Comment by nineteendo** [comment]
The code for reference:

https://github.com/python/cpython/blob/82acc5f2113bffd0ed902851f4ccf5b9be8980b2/Lib/enum.py#L1507

https://github.com/python/cpython/blob/82acc5f2113bffd0ed902851f4ccf5b9be8980b2/Lib/enum.py#L1527-L1528

Bisecting...

**Comment by nineteendo** [comment]
cc @ethanfurman.

**Comment by ethanfurman** [comment]
The zero-flag name *is* constructed from its members -- it just doesn't have any members.  This could certainly be mentioned in the docs.

**Comment by nineteendo** [comment]
I'll make a pull request with an example.

**Comment by nineteendo** [comment]
It has been a month, does someone still need to review my pull request?

**Comment by nineteendo** [comment]
@erlend-aasland, could you ask someone on Discourse to review my PR? Or can it be merged?
