### ISSUE TITLE
Give AST nodes a useful `__eq__`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#118855]
# Feature or enhancement

### Proposal:

```pycon
>>> import ast
>>> ast.Load() == ast.Load()
False
```

It's useful for unit tests if equal nodes actually compare equal.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by Eclips4** [comment]
I would like to take this one if you don't mind :)

**Comment by JelleZijlstra** [comment]
Go for it!

**Comment by serhiy-storchaka** [comment]
Should it be recursive or not? See also #60191.

For things like `ast.Load()` it makes sense to make them singletons. This would automatically solve the problem with equal comparison.

**Comment by sobolevn** [comment]
Also, there are two ways to compare nodes. "exactly equal" including position and every other detail and "looks equal" when their content is similar: `ast.Name(id="a")` might look equal to other `ast.Name(id="a")`

Both are useful for static analysis tools.
