### ISSUE TITLE
Default argument for `__getitem__()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#118937]
# Feature or enhancement

### Proposal:

\>30.3k files use this syntax: [`a[()]`](https://github.com/search?q=%2F%5Cw%2B%5C%5B%5C%28%5C%29%5C%5D%2F+language%3APython&type=code). Could we allow specifying a default for `__getitem__()` & `__class_getitem__()`:

```python
class Tuple(tuple):
    def __class_getitem__(cls, item=(), /):
        return super().__class_getitem__(item)
```

The current SyntaxError for `a[]` isn't very helpful either:

```python
>>> tuple[()]
tuple[()]
>>> tuple[]
  File "<python-input-1>", line 1
    tuple[]
          ^
SyntaxError: invalid syntax
```

We already don't need parentheses in other cases: `tuple[int]`, `tuple[int, int]`.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
You can already add a default to your implementation of `__getitem__`, but there is no way to use the subscript syntax to call it with zero arguments. I assume you are suggesting that `X[]` would be changed to call `X.__getitem__()`.

That would be a change to the grammar, so definitely not a minor feature that we can accept without prior discussion. In fact, it would probably need a PEP.

Your link shows 30k uses of `[()]`. That's a lot, but in https://discuss.python.org/t/implicit-tuple-return-type/52903/61 you found more than 30 million uses of `x[a, b]`—indicating that the `x[()]` syntax is not especially common. I glanced through the first few results; some are uses of the empty tuple type `tuple[()]`, others are in various array or tensor libraries. I can't speak for the latter, but from a typing perspective I think `tuple[()]` is a clearer spelling for the empty tuple type than `tuple[]`.

**Comment by nineteendo** [comment]
https://discuss.python.org/t/allow-zero-arguments-for-subscript-syntax/53084
