### ISSUE TITLE
Python 3.13 b1 x64 Windows Installer problems

### ISSUE THREAD

**Issue by ThomasGessert** [python/cpython#118996]
# Bug report

### Bug description:

I tried the installer on two Win11 Pro systems (23H2, 24H2 beta), upgrade from a6 and fresh install. On both systems pip was broken afterwards.

Error message:
"no module named pip"

On the 24H2 system additionally the "scripts" folder got deleted while upgrading. The a6 installer works fine.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
Are you using a non-English version of Windows? There is a known issue causing pip to fail.

**Comment by ThomasGessert** [comment]
Yes, I'm on a german windows. Probably its worth to mention, that I did an all-user installation with precompile standard lib option.
