### ISSUE TITLE
Editing the last line in a block in the new REPL is buggy

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#118911]
# Bug report

### Bug description:

When editing the last line in a function in the new REPL, hitting Enter doesn't end the block if the last line has indentation on it.

![658451](https://github.com/python/cpython/assets/285352/04d90d25-ede8-43cf-9c96-f242b99e2127)

[Demo of the bug](https://asciinema.org/a/658451), [demo of what IPython does](https://asciinema.org/a/658452)

_Originally posted in https://github.com/python/cpython/issues/111201#issuecomment-2101869843_

Here are the noticeable differences in how IPython handles this situation:

1. When hitting the up arrow key to edit the block, the final blank line isn't included (the default cursor position is at the end of the last non-empty line.

![image](https://github.com/python/cpython/assets/285352/72a369c6-369d-47f7-a7a4-c357d744527b)

2. In IPython I tried purposely adding extra whitespace-only lines (not fully blank but instead containing 4 spaces) by hitting Enter, up arrow, End, Enter, up arrow, End, repeatedly. If I then hit Enter on the first line-followed-by-whitespace-only-lines it ends the block.

![image](https://github.com/python/cpython/assets/285352/1850c62d-5099-426b-8a43-d632410aaf17)

3. Hitting up arrow again, will strip whitespace from the end of the block (maybe this is how 1 above is implemented)

![image](https://github.com/python/cpython/assets/285352/10df6e87-e892-4c72-984d-150d79b8084a)

Implementing the behavior of 1 (or 3) above might be enough, though 2 seems like it would be even better.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-119355
* gh-119404

**Comment by lysnikolaou** [comment]
This has been fixed! Congrats @aelsayed95! 🎉 

I'm closing this, but feel free to reopen in case something's off.
