### ISSUE TITLE
get_type_hints raises TypeError for type union with "|" __or__ overload on python 3.9

### ISSUE THREAD

**Issue by sfc-gh-mvashishtha** [python/cpython#118919]
# Bug report

### Bug description:

Reproducible example:

```python
from __future__ import annotations
from typing import get_type_hints

def f() -> int | str:
    return 3

print(get_type_hints(f))
```

`from __future__ import annotations` lets me use the `__or__` overload for types to create union types, but `get_type_hints` can't recognize those types.

This is the root cause of https://github.com/gradio-app/gradio/pull/4228 and https://github.com/pydantic/pydantic/issues/2597

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

**Comment by nineteendo** [comment]
I don't think there's much we can do here, 3.9 only accepts security fixes. If you need help implementing a replacement for `get_type_hints()`, you can ask on StackOverflow or https://discuss.python.org/c/users/7.

**Comment by sfc-gh-mvashishtha** [comment]
Okay, for reference, there's a workaround on https://github.com/gradio-app/gradio/pull/4228
