### ISSUE TITLE
ChainMap.__contains__ and .get performance improvement.

### ISSUE THREAD

**Issue by dg-pb** [python/cpython#118932]
# Feature or enhancement

### Proposal:

```python
import collections as coll


class ChainMap2(coll.ChainMap):
    def __contains__(self, key):
        for mapping in self.maps:
            if key in mapping:
                return True
        return False

    def get(self, key, default=None):
        for mapping in self.maps:
            if key in mapping:
                return mapping[key]
        return default


maps = [dict(a=1), dict(a=2, b=2), dict(a=3, b=2, c=3)]
cm = coll.ChainMap(*maps)
cm2 = ChainMap2(*maps)


%timeit 'a' in cm               # 615 ns
%timeit 'c' in cm               # 752 ns
%timeit cm.get('a')             # 776 ns
%timeit cm.get('c')             # 1.46 µs

%timeit 'a' in cm2              # 140 ns
%timeit 'c' in cm2              # 198 ns
%timeit cm2.get('a')            # 147 ns
%timeit cm2.get('c')            # 208 ns
```

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://discuss.python.org/t/collections-chainmap-get-performance/41925

### Linked PRs
* gh-118946

**Comment by pochmann3** [comment]
I'm curious: how long does `cm2['c']` take?

**Comment by dgrigonis** [comment]
621 ns
Can't think of a way to improve it as it needs to be sensitive to `__missing__` implementations.

**Comment by rhettinger** [comment]
The change to `__contains__` is a good idea.  It's a bummer that `any()` with a generator expression does not perform well.

The `get` method should be left as-is.  The edit alters the semantics so that a override of `__contains__` in a ChainMap subclass would be bypassed.

**Comment by dgrigonis** [comment]
Makes sense, can't think of any way to keep that and not to iterate twice.

At least updating `__contains__` will boost performance of `get` too.

Should I issue PR or leave it to you?

**Comment by nineteendo** [comment]
How much slower is this? https://stackoverflow.com/a/44803103

```python
any(True for m in self.maps if key in m)
```

**Comment by dgrigonis** [comment]
> How much slower is this? https://stackoverflow.com/a/44803103
> 
> ```python
> any(True for m in self.maps if key in m)
> ```
Slightly faster than the original:
```
 %timeit 'a' in cm2    # 589 ns
%timeit 'c' in cm2   # 671 ns
```

**Comment by nineteendo** [comment]
... but slower than an actual for loop.

**Comment by dgrigonis** [comment]
```
%timeit any(map(opr.call, map(opr.attrgetter(' __contains__'), cm2.maps), itl.cycle([key])))
```
786 ns :)

**Comment by pochmann3** [comment]
> ```
> any(map(opr.call, map(opr.attrgetter(' __contains__'), cm2.maps), itl.cycle([key])))
> ```

Looks like a complicated version of (untested)
```
any(map(opr.contains, cm2.maps, itl.repeat(key)))
```

**Comment by dgrigonis** [comment]
> Looks like a complicated version of:
> 
> ```
> any(map(opr.contains, cm2.maps, itl.repeat(key)))
> ```

Which is the fastest I have seen without loop:
In [16]: %timeit 'a' in cm2 # 360 ns
In [17]: %timeit 'c' in cm2  # 424 ns

**Comment by CypherGrue** [comment]
With apology for late comment, it seems like ChainMap.get method makes two lookup in the dictionary when only one lookup is strictly necessary. The first lookup is for __contains__ and the second for __getitem__. Why not do something like:

```
    def get(self, key, default=None):
        try:
            return self[key]
        except KeyError:
            return default
```

My test:

```
from collections import ChainMap

N = 1000000
cm = ChainMap({i:i for i in range(N)})

for i in range(N):
    cm.get(i)
```

Before: real 0m0.327s
After: real 0m0.162s
