### ISSUE TITLE
translation error in fr/3/library/argparse.html

### ISSUE THREAD

**Issue by fkhn** [python/cpython#118971]
# Documentation

Here under is the current wording with the proposed modification in bold. 

Le paramètre metavar
.../... Ainsi, un argument positionnel unique avec dest='bar' est affiché comme bar et un argument  **~~positionnel~~ optionnel** unique --foo qui prend un seul argument sur la ligne de commande est affiché comme FOO. Par exemple :

**Comment by sobolevn** [comment]
cc @vstinner and @FFY00 who knows French :)

**Comment by JelleZijlstra** [comment]
Similar to #118972, please report this to the python-docs-fr repo.

**Comment by fkhn** [comment]
The link there [https://git.afpy.org/AFPy/python-docs-fr/issues/269](https://git.afpy.org/AFPy/python-docs-fr/issues/269)

**Comment by christopheNan** [comment]
Fixed by https://git.afpy.org/AFPy/python-docs-fr/pulls/270
