### ISSUE TITLE
ʰᵗᵗᵖˢ://ᵍⁱᵗʰᵘᵇ.ᶜᵒᵐ/ᵖʸᵗʰᵒⁿ/ᶜᵖʸᵗʰᵒⁿ/ᵇˡᵒᵇ/³.¹²/ᴸⁱᵇ%²ᶠʲˢᵒⁿ%²ᶠ__ⁱⁿⁱᵗ__.Save

### ISSUE THREAD

**Issue by collector88** [python/cpython#118980]
# Documentation

(A clear and concise description of the issue.)

**Comment by ronaldoussoren** [comment]
Please add a description of the problem when you create an issue.

**Comment by collector88** [comment]
I am responding to an email I'm not sure what it's concerning. Also I would need some form of identification. Other then an email.Thank you tj mb--Sent from my Android phone with mail.com Mail. Please excuse my brevity.On 5/13/24, 2:04 AM Ronald Oussoren ***@***.***> wrote:

   
  Closed #118980 as not planned.

**Comment by hugovk** [comment]
Reported to GitHub (see also spam PR approval: https://github.com/python/cpython/pull/104895#pullrequestreview-2051790837)
