### ISSUE TITLE
Contextvars + async generator + break + finally

### ISSUE THREAD

**Issue by sylvainmouquet** [python/cpython#118944]
# Bug report

### Bug description:

```python
import asyncio
import contextvars

async def gen():
    var = contextvars.ContextVar('one')

    token = var.set(1)

    ctx = contextvars.copy_context()
    print(list(ctx.items()))

    try:
        yield 1
        yield 2
    finally:
        ctx = contextvars.copy_context()
        print(list(ctx.items()))

        try:
            var.reset(token)
        except Exception as e:
            print(e.args)

async def main():
    async for i in gen():
        print(i)
        break

asyncio.run(main())
```

result :
```
[(<ContextVar name='one' at 0x107312930>, 1)]
1
[(<ContextVar name='one' at 0x107312930>, 1)]
("<Token var=<ContextVar name='one' at 0x107312930> at 0x107303480> was created in a different Context",)
```

In finally block it's not possible to manually reset the contextvars 

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by graingert** [comment]
Yes this is expected, because the finally is triggered by the garbage collector, where asyncio uses sys.set_asyncgen_hooks() to aclose the async generator in a new task.

If you want to ensure finalization in the same context use

```python
async def main():
    async with contextlib.aclosing(gen()) as agen:
        async for i in agen:
            print(i)
            break()
```

**Comment by graingert** [comment]
See also https://docs.python.org/3/reference/expressions.html#asynchronous-generator-functions

> If an asynchronous generator happens to exit early by break, the caller task being cancelled, or other exceptions, the generator’s async cleanup code will run and possibly raise exceptions or access context variables in an unexpected context–perhaps after the lifetime of tasks it depends, or during the event loop shutdown when the async-generator garbage collection hook is called. To prevent this, the caller must explicitly close the async generator by calling aclose() method to finalize the generator and ultimately detach it from the event loop.

**Comment by graingert** [comment]
I'm going to close this, as working as documented
