### ISSUE TITLE
Python 3.13.0b1 REPL sometimes swallows the output

### ISSUE THREAD

**Issue by hroncok** [python/cpython#119032]
# Bug report

### Bug description:

I was debugging a certain issue in setuptools tests in Python 3.13.0b1 REPL:

```pycon
>>> import os, posixpath
>>> path = r'\foo/bar.txt'
>>> os.path.pardir in path.split(posixpath.sep)
(no output)
```

I was worried. Shouldn't the result be True or False exclusively?

```pycon
>>> os.path.pardir in path.split(posixpath.sep)
>>> os.path.pardir in path.split(posixpath.sep)
False
>>> os.path.pardir in path.split(posixpath.sep)
False
>>> os.path.pardir in path.split(posixpath.sep)
False
>>> os.path.pardir in path.split(posixpath.sep)
False
>>> os.path.pardir in path.split(posixpath.sep)
False
```

Huh? Let's try again with something simpler:

```pycon
>>> 'a' in 'aaa'
>>> 'a' in 'aaa'
True
```

This appears to happen entirely at random for me.

```
$ python3.13
Python 3.13.0b1 (main, May  9 2024, 00:00:00) [GCC 14.1.1 20240507 (Red Hat 14.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'a' in 'aaa'
>>> 'a' in 'aaa'
True

$ python3.13
Python 3.13.0b1 (main, May  9 2024, 00:00:00) [GCC 14.1.1 20240507 (Red Hat 14.1.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 'a' in 'aaa'
True
>>> 'a' in 'aaa'
True
```

This is on Fedora Linux 39.

python3.13-3.13.0~b1-2.fc41.x86_64
readline-8.2-6.fc39.x86_64
ncurses-libs-6.4-7.20230520.fc39.1.x86_64

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
Did you paste the lines with swallowed output? If so, see https://github.com/python/cpython/issues/118893.

**Comment by hroncok** [comment]
Thanks. I did, but I did not notice that as I was mixing pasting,t typing and using the prompt history. 

This is a duplicate of https://github.com/python/cpython/issues/118893.
