### ISSUE TITLE
Implement the fast path for `list.__getitem__`

### ISSUE THREAD

**Issue by mpage** [python/cpython#119053]
# Feature or enhancement

### Proposal:

Implement the fast path for `list.__getitem__` [outlined in PEP-703](https://peps.python.org/pep-0703/#optimistically-avoiding-locking).

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119112
* gh-119309

**Comment by corona10** [comment]
@mpage Can I take a look at this one or you already work on this issue? (I am just asking to avoid the confliction)

**Comment by mpage** [comment]
@corona10 - Go for it!

**Comment by nineteendo** [comment]
Is there still something to do here?

**Comment by colesbury** [comment]
No, it's done thanks.
