### ISSUE TITLE
Defer `import warnings` in pathlib

### ISSUE THREAD

**Issue by barneygale** [python/cpython#119049]
As of GH-118793, the `warnings` module is used only once in pathlib, by `PurePath.is_reserved()`. We should be able to move the `import warnings` line into that method. But beware! Doing so seems to cause a failure in `test_io`, which needs further investigation.

### Linked PRs
* gh-119063
* gh-119106
* gh-119111
* gh-119119

**Comment by Eclips4** [comment]
Actually, it's used twice, in the `PurePath.is_reserved()` and in the `Path.__init__`

**Comment by Eclips4** [comment]
> But beware! Doing so seems to cause a failure in `test_io`, which needs further investigation.

I've written #119063 to address this. FYI, this is not related to ``pathlib`` :)

**Comment by barneygale** [comment]
Woot! Thank you @Eclips4 for sorting this :)
