### ISSUE TITLE
Documentation of pathlib.Path methods is disorganised

### ISSUE THREAD

**Issue by barneygale** [python/cpython#119054]
# Documentation

The docs for [`pathlib.Path` methods](https://docs.python.org/3.14/library/pathlib.html#methods) is disorganised. It was originally alphabetical, but over the last few years we've begun moving similar methods together. We ought to split it up into sections, to make it easier to navigate and absorb, e.g.:

- Parsing and generating URIs
- Querying file type and status
- Reading and writing files
- Iterating over directories
- Making paths absolute
- Expanding home directories
- Resolving symlinks
- Permissions
- Ownership
- Other methods

If this granularity is too fine, we could stick more stuff in "Other methods".

### Linked PRs
* gh-119055
* gh-119524
* gh-119951
* gh-119952
* gh-119954
* gh-119955
* gh-119956
* gh-120183
* gh-120184
* gh-120186
* gh-120462
* gh-120464
* gh-120465
* gh-120472
* gh-120473
* gh-120505
* gh-120967
* gh-120968
* gh-120970
* gh-121155
* gh-121156
* gh-121158
* gh-121167
* gh-121168
* gh-121169

**Comment by hugovk** [comment]
Thanks for doing all this! It's a good example of incrementally applying Diátaxis.

One thing I just noticed, the alt tag for the class diagram at the top of https://docs.python.org/3/library/pathlib.html is the same as the image path:

```html
<img alt="../_images/pathlib-inheritance.png" class="invert-in-dark-mode align-center" src="../_images/pathlib-inheritance.png">
```
I'm not sure why that is, we're not specifying an alt tag, so perhaps it's a Sphinx bug?

```rst
.. image:: pathlib-inheritance.png
   :align: center
   :class: invert-in-dark-mode
```

Anyway, let's add alt text so it's accessible for people using screen readers:

https://sublime-and-sphinx-guide.readthedocs.io/en/latest/images.html

**Comment by barneygale** [comment]
It's finished! Thank you for all the reviews :)
