### ISSUE TITLE
String module should have a string like printable but without whitespace

### ISSUE THREAD

**Issue by RustoMCSpit** [python/cpython#119067]
# Feature or enhancement

### Proposal:

```python
# import random as rd
import string

def passwordStrength(password):
    quality = 0
    if password[0].isdigit():
        quality += 1
    print (password[0])
    print (quality)

def passwordMake(length):
    password = []
    for x in range (length):        
        password.append(rd.choice(string.printable))
    password = ' '.join(password)
    password = ''.join(password.split())
    print (password)
    passwordStrength(password)
    

passwordMake(rd.randint(6, 20))

```

https://github.com/python/cpython/blob/3.12/Lib/string.py
in this, there is no convenient way just to have it produce characters that aren't whitespace.
the above is my roundabout method of trying to get around this.
i suggest a new string: "visible -- a string containing all ASCII characters considered printable (excluding whitespace)"

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119080

**Comment by RustoMCSpit** [comment]
this is a good first issue i suppose for people looking to make a PR

**Comment by serhiy-storchaka** [comment]
You can use `string.printable.replace(' ', '')` or `set(string.printable) - {' '}`. This can be easily modified to exclude other undesirable characters (for example `I`, `l` and `1` can be confused with each other, `''` can be confused with `"` or ``` `` ```).

`string.printable` is a historical artifact. Today it is superseded by the `str.isprintable()` methods combined with additional conditions. Every applications has its own conditions. Adding yet one string constant in the `string` module which differs only by a character from other string constant will likely confuse people.

**Comment by RustoMCSpit** [comment]
> Adding yet one string constant in the `string` module which differs only by a character from other string constant will likely confuse people.

i doubt anyone will be confused by a string constant. even if there are workarounds, it's just prettier and quicker to have another constant, helps the read-ability yk.

**Comment by pochmann3** [comment]
> differs only by a character

By six. Also ASCII 9 to 13.

**Comment by serhiy-storchaka** [comment]
How would you name the new constant? `string.printable_without_space`? Or more accurately `string.ascii_printable_without_whitespace`?

**Comment by RustoMCSpit** [comment]
> How would you name the new constant? `string.printable_without_space`? Or more accurately `string.ascii_printable_without_whitespace`?

string.visible

**Comment by nineteendo** [comment]
Is there a problem with this?

```python
from string import ascii_letters , digits , punctuation

visible = digits + ascii_letters + punctuation
```

**Comment by RustoMCSpit** [comment]
> Is there a problem with this?
> 
> ```python
> from string import ascii_letters, digits, punctuation
> 
> visible = digits + ascii_letters + punctuation
> ```

no, but it's less efficient then just having a visible constant which would be useful for a lot of use cases. it's sorta like asking 'why have ascii when you can just add lower and upper ascii?'

**Comment by nineteendo** [comment]
For reference here are the constants of the original version:

https://github.com/python/cpython/blob/c636014c430620325f8d213e9ba10d925991b8d7/Lib/string.py#L6-L12

Only `punctuation` & `printable` have been added since with the latter being the concatenation of all other strings.

**Comment by RustoMCSpit** [comment]
i still think visible is such a logical addition when someone needs all visible symbols fast. id hardly see it as bloat? i fully axknowledge what im suggestinf is just an efficiency / readability optimisation and there are work arounds but i see little reason why not to add it as a constant

**Comment by RustoMCSpit** [comment]
> > i see little reason why not to add it as a constant
> 
> The opposite question is relevant: what is the reason to add it? Where would it be useful? It's easy to add, but that's not a very good reason to add it.

already answered. tl;dr: convenience.

**Comment by encukou** [comment]
If we add something for convenience, it should be both convenient and correct for many users.

While I haven't done the research, use cases I can think of are better served with a slightly different set -- for example, exclude quotes or the backslash, exclude `O`/`0` and `l`/`I`/`1` for readability, or not limit the set to ASCII. For toy examples, `digits` + `ascii_letters` are fine.
