### ISSUE TITLE
Make ZeroDivisionError message more precise when floor-dividing by zero

### ISSUE THREAD

**Issue by E8zEbo8Luna** [python/cpython#119057]
# Feature or enhancement

### Proposal:

```python
try:
  10 // 0
except ZeroDivisionError as e:
  print(e) #returns integer division or modulo by zero

try:
  10 / 0
except ZeroDivisionError as e:
  print(e) #returns integer division by zero

try:
  10 % 0
except ZeroDivisionError as e:
  print(e) #returns integer modulo by zero
```

When floor dividing by zero the error says "division or modulo" but while (non-floor) dividing by zero or modulo-ing (?) it is more specific saying "division" or "modulo". I would recommend changing this to "floor division" or "division" because it would help with knowing what exactly the error is talking about.

Thank You!

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119066

**Comment by serhiy-storchaka** [comment]
I was thinking about it yesterday. Perhaps a better solution would be dropping " or modulo" and leaving only "integer division by zero" for `x / 0`, `x // 0` and `divmod(x, 0)`. It does not make difference whether it is a true division, a floor division, or if the modulo is involved, -- it is all division by zero.

But if make the error message more specific (add "floor"), should not it also replace "division or modulo" with "division and modulo" for `divmod(x, 0)`?

Whatever be done for integers, should be done for other numerical types.

cc @mdickinson

**Comment by mdickinson** [comment]
> Perhaps a better solution would be dropping " or modulo" and leaving only "integer division by zero" for `x / 0`, `x // 0` and `divmod(x, 0)`. It does not make difference whether it is a true division, a floor division, or if the modulo is involved, -- it is all division by zero.

+1

**Comment by serhiy-storchaka** [comment]
If it helps to harmonize the error messages, I support dropping also the type. The only difference may be if mixed types are involved, and the non-zero divisor is converted with losses to the zero of other type. But AFAIK there are no such cases in the core and the stdlib.

In the end, all ZeroDivisionError exceptions may have the same error message.

**Comment by sobolevn** [comment]
Ok, I agree. I will change my PR 👍

**Comment by sobolevn** [comment]
I think that I found one case that should not be changed:

```python
>>> 0 ** -1
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    0 ** -1
    ~~^^~~~
ZeroDivisionError: 0.0 cannot be raised to a negative power
```

I would not want to see "division by zero" here. In fact, it will be just `1 / 0`, but still it won't be very clear.

I also found that `0.0` is used when `0 ** -1`

**Comment by mdickinson** [comment]
Agreed that the power case shouldn't be changed
