### ISSUE TITLE
Change error message if module is already installed.

### ISSUE THREAD

**Issue by bulrush15** [python/cpython#119030]
# Feature or enhancement

### Proposal:

Currently if I try to install a module that is a standard module, I get this error message. This message is confusing to newbies. 

```
ERROR: Could not find a version that satisfies the requirement sqlite3 (from versions: none)
ERROR: No matching distribution found for sqlite3
```

Can you change the error message to check if the module is standard, or already installed? The 2 new error messages would be: 

```
ERROR: This module is a standard module and is already part of Python.
```

or

```
ERROR: This third-party module has already been installed.
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
This error is produced by an installer (probably https://github.com/pypa/pip), not by CPython itself, so this isn't the right place. I'd encourage you to submit your suggestion to pip instead.
