### ISSUE TITLE
venv tutorial wrong/confusing about python version used

### ISSUE THREAD

**Issue by deuberger** [python/cpython#119078]
# Documentation

From https://docs.python.org/3/tutorial/venv.html:

> [venv](https://docs.python.org/3/library/venv.html#module-venv) will usually install the most recent version of Python that you have available. If you have multiple versions of Python on your system, you can select a specific Python version by running python3 or whichever version you want.

https://docs.python.org/3/library/venv.html#module-venv though makes it clear that the venv will use `the Python installation from which the command was run`.

So I believe it should be updated to:

> [venv](https://docs.python.org/3/library/venv.html#module-venv) will install the Python version from which the command was run. If you have multiple versions of Python on your system, you can select a specific Python version by running python3 or whichever version you want.

### Linked PRs
* gh-119129
* gh-119141
* gh-119142

**Comment by nineteendo** [comment]
> If you have multiple versions of Python on your system, you can select a specific Python version by running python3 or whichever version you want.

Isn't this a bit redundant then?

**Comment by deuberger** [comment]
@nineteendo I wondered about that and I think yes it is partially redundant, but not entirely. How about:

[venv](https://docs.python.org/3/library/venv.html#module-venv) will install the Python version from which the command was run.   For instance, running `python3.8` will install version 3.8 specifically whereas running just `python` or `python3` might install any number of versions. See the [Python Setup and Usage documentation](https://docs.python.org/3/using/index.html) for additional details.

I'd be fine reducing it to just the first sentence as well, but new users may find the additional information helpful.

**Comment by nineteendo** [comment]
How about mentioning `python -V`? As it tells you which version will be installed.

**Comment by anushatomar13** [comment]
Hi @nineteendo ,
Have you reached a final conclusion on this issue yet?
If yes, can I take up this issue and start working on it?

**Comment by nineteendo** [comment]
I think this should be clear enough:

> [venv](https://docs.python.org/3/library/venv.html#module-venv) will install the Python version shown for [--version](https://docs.python.org/3/using/cmdline.html#cmdoption-version). For instance, excuting the command with `python3.8` will install version 3.8.

**Comment by deuberger** [comment]
Sorry, for the slow response. I thought of adding `--version` too, but thought it might be too much with what I had before. I like the suggestion from @nineteendo, but also propose the below slightly more verbose option that might add a little more clarity:

> [venv](https://docs.python.org/3/library/venv.html#module-venv) will install the Python version from which the command was run (as reported by the [--version](https://docs.python.org/3/using/cmdline.html#cmdoption-version) option).  For instance, excuting the command with python3.8 will install version 3.8.

**Comment by nineteendo** [comment]
Looks good, feel free to create a pull request.

**Comment by nineteendo** [comment]
Although, it might be more relevant to mention 3.12 or 3.13?
