### ISSUE TITLE
Popen.send_signal(sigint.SIGKILL) does not seem to work with Popen(*, shell=True)?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [python/cpython#119059]
### Bug description:

Not clear why, but on my system (Ubuntu 22.04.4, CPython 3.10.12), the following code shows that:
- `SIGINT` seems to be received when `shell=False`
- `SIGINT` does not seem to be received when `shell=True`
- `SIGABRT` can kill the program when `shell=True` -- but seems a bit too violent?

```python
import signal
from subprocess import Popen
import time

def signal_process(process, sig=signal.SIGINT, block=True, close_streams=True):
    if process.poll() is None:
        process.send_signal(sig)
    if close_streams:
        for stream in [process.stdin, process.stdout, process.stderr]:
            if stream is not None and not stream.closed:
                stream.close()
    if block:
        if process.poll() is None:
            process.wait()

def run_captured_process(args, *, shell, sig):
    # Start a process, wait a brief amount of time, then try to exit.
    proc = Popen(args, shell=shell)
    try:
        t_next = time.time() + 0.5
        while time.time() < t_next:
            assert proc.poll() is None
            time.sleep(0.1)
        print("Exiting")
    finally:
        signal_process(proc, sig=sig)
    print("  Done")

# Does not hang.
run_captured_process(["sleep", "1d"], shell=False, sig=signal.SIGINT)
# Does not hang.
run_captured_process("sleep 1d", shell=True, sig=signal.SIGABRT)

# Why does this hang?!!!
run_captured_process("sleep 1d", shell=True, sig=signal.SIGINT)
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by eryksun** [comment]
With `shell=True`, the script signals the shell (e.g. bash), which will ignore `SIGINT`. In this case, `SIGABRT` kills the shell and leaves the `sleep 1d` command running. To send `SIGINT` to the child of the shell as well, execute the shell as the group leader of a new process group by passing the `Popen` argument `process_group=0`, and signal the group via `os.killpg(process.pid, signal.SIGINT)`.

**Comment by EricCousineau-TRI** [comment]
Thanks! Yup, that worked.
I had to slightly change your suggestion, using https://stackoverflow.com/a/22582659/7829525 + looking at this code:
https://github.com/python/cpython/blob/v3.10.12/Modules/_posixsubprocess.c#L554-L555

Using `Popen(*, start_new_session=True)` and `os.killpg(os.getpgid(process.pid), signal.SIGINT)` seems to fix it.
Patch applied to code similar to above:
https://github.com/EricCousineau-TRI/repro/commit/f2aca66f7cb4237f2574019e9dc9606fbe25dbd0

**Comment by eryksun** [comment]
The `process_group` option was added in 3.11. Using a new process group is my preferred way to solve this for a non-interactive process. Creating a new session works as well. Note that with a new session, the child process won't have a controlling terminal (e.g. opening "/dev/tty" will fail), but that shouldn't matter for a non-interactive command.

**Comment by vstinner** [comment]
@eryksun gave a good explanation of the behavior and proposed a solution.

subprocess works as expected. I close the issue.
