### ISSUE TITLE
weird behavior of the import statement

### ISSUE THREAD

**Issue by plzfgme** [python/cpython#119086]
# Bug report

### Bug description:

File structure:

```text
 a
├──  __init__.py
├──  c.py
└──  d.py
```

File content:

```python
# __init__.py
b = "b"
from .c import c

__all__ = ["b", "c"]
```

```python
# c.py
c = "c"
```

```python
# d.py
d = "d"
```

Run in python:

```text
Python 3.11.9 (main, Jan  1 1980, 00:00:00) [Clang 16.0.6 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import a.b as b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'a.b'
>>> import a.c as c
>>> c
'c'
>>> import a.d as d
>>> d
<module 'a.d' from '/the/path/to/Python-3.11.9/a/d.py'>
```

I think for b and d, it works correctly because b is not a module and d is. But for c, I expect it to be a module, but it is actually a variable.

I am not familiar to python but I cannot find any info about this behavior, so I ask it here.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
This was discussed recently in #117860. It is not obvious that this is a bug. The code in `__init__.py` sets `c` to `'c'`. `import a.c as c` is equivalent to `import a.c; c = a.c`.

To avoid confusion try to not override the names which correspond to names of submodules with other values.

**Comment by plzfgme** [comment]
When I modify `__init__.py` to:

```python
# __init__.py
b = "b"
c = "c"

__all__ = ["b", "c"]
```

Module c was correctly imported:

```text
Python 3.11.9 (main, Jan  1 1980, 00:00:00) [Clang 16.0.6 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import a.b as b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'a.b'
>>> import a.c as c
>>> c
<module 'a.c' from '/the/path/to/Python-3.11.9/a/c.py'>
>>> import a.d as d
>>> d
<module 'a.d' from '/the/path/to/Python-3.11.9/a/d.py'>
```
