### ISSUE TITLE
Add the ``--duration`` option to the test suite

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#119050]
# Feature or enhancement

### Proposal:

I propose adding a new option ``--duration`` to our test suite. This would print the duration of each test that has run during the test suite, to the file that the user provides. 
So actual use case looks like that:
`./python.exe -m test --duration tmp/stats -R 3:3`
It's can be useful as the ``--slowest`` option, which already exists.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119051
* gh-119144
* gh-119148
* gh-119156
* gh-119157
* gh-119270
* gh-119272

**Comment by vstinner** [comment]
Why not reusing the JUnit output?

**Comment by Eclips4** [comment]
> Why not reusing the JUnit output?

JUnit cannot be used in a "hunt refleaks" mode. Although, using JUnit for this purpose would be great, but I do not see an easy solution to making it work with the "hunt refleaks" mode :(

**Comment by vstinner** [comment]
> JUnit cannot be used in a "hunt refleaks" mode. Although, using JUnit for this purpose would be great, but I do not see an easy solution to making it work with the "hunt refleaks" mode :(

We should write JUnit data into a file, and then load the file to write the XML. Not store these data into memory.

**Comment by vstinner** [comment]
> JUnit cannot be used in a "hunt refleaks" mode. Although, using JUnit for this purpose would be great, but I do not see an easy solution to making it work with the "hunt refleaks" mode :(

It's now supported! Is it enough for your use case?

**Comment by Eclips4** [comment]
> > JUnit cannot be used in a "hunt refleaks" mode. Although, using JUnit for this purpose would be great, but I do not see an easy solution to making it work with the "hunt refleaks" mode :(
> 
> It's now supported! Is it enough for your use case?

Yes, it is! Thanks Victor!
