### ISSUE TITLE
Misleading sqlite3.Cursor.rowcount docs

### ISSUE THREAD

**Issue by ioplju** [python/cpython#119096]
> rowcount
> 
> Read-only attribute that provides the number of modified rows for INSERT, UPDATE, DELETE, and REPLACE statements; is -1 for other statements, including CTE queries. It is only updated by the [execute()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.execute) and [executemany()](https://docs.python.org/3/library/sqlite3.html#sqlite3.Cursor.executemany) methods, after the statement has run to completion. This means that any resulting rows must be fetched in order for rowcount to be updated.

I'm new to the sqlite3 module so I've been reading the docs. The last sentence made me think for a moment about the need or not to call `fetchone()`, `fetchmany()` or `fetchall()` after calling `execute()` or `executemany()` in order to update `rowcount`.

I think it would be preferable to remove that last sentence (because _"after the statement has run to completion"_ is clear enough) or reword the last sentence (at least without the _"fetch"_ verb).

**Comment by erlend-aasland** [comment]
> I think it would be preferable to remove that last sentence (because _"after the statement has run to completion"_ is clear enough) or reword the last sentence (at least without the _"fetch"_ verb).

I'm not sure if "run to completion" is clear to everyone, so I do not think removing the last sentence makes the docs more clear. Some people will (incorrectly) assume that a statement has run to completion when `execute` returns, but that is not always the case. Perhaps we need something about this in _Explanation_.

**Comment by erlend-aasland** [comment]
Moreover, I prefer to use the verb _fetch_ as opposed to e.g. _retrieve_, since the methods used to **fetch** the remaining rows (and thus to run the statement to completion) are named _fetch**something**()_.

**Comment by felixxm** [comment]
TBH, I don't see how the current documentation is misleading. Extra clarification provided by this sentence is more than helpful. I'd close this issue.
