### ISSUE TITLE
Possible segfault in sys__getframe_impl in sysmodule.c

### ISSUE THREAD

**Issue by 3xt3r** [python/cpython#119002]
# Crash report

### What happened?

```python
static PyObject *
sys__getframe_impl(PyObject *module, int depth)
/*[clinic end generated code: output=d438776c04d59804 input=c1be8a6464b11ee5]*/
{
    PyThreadState *tstate = _PyThreadState_GET();
    PyFrameObject *f = PyThreadState_GetFrame(tstate);

    if (_PySys_Audit(tstate, "sys._getframe", "O", f) < 0) {
        Py_DECREF(f);
        return NULL;
    }
```
This implemention doesn't take in account case when PyThreadState_GetFrame returns NULL.
If PyThreadState_GetFrame returns a NULL, Py_DECREF will be failed with segfault. This hard to reproduce, but theoretically it can happen.

**Python version**
3.10.14

### CPython versions tested on:

3.10

**Comment by Eclips4** [comment]
Hello!
Sorry, but the 3.10 branch now only accepts security fixes.
The 3.12, 3.13, and 3.14 (main) branches are not affected by this issue.
