### ISSUE TITLE
Regular Expression: re.split behavior weird when have a sub pattern

### ISSUE THREAD

**Issue by WiC-htao** [python/cpython#119093]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
![gw9Uu0mujK](https://github.com/python/cpython/assets/72003571/dc291e42-6c02-49e1-9e2f-ca471397247e)

![KSeQC7v4yd](https://github.com/python/cpython/assets/72003571/79e5ee4d-e2f6-441d-aee8-3dd68ee8cb11)

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by blhsing** [comment]
Works as intended. A captured group with a quantifier captures only the first occurrence of the enclosed pattern.

**Comment by serhiy-storchaka** [comment]
Concur with @blhsing. You can use `re.finditer()` to see in details what was found.

For future, please use text instead of pictures for your examples. It is difficult to copy the code from a picture, it is also bad for visually impaired people.

**Comment by pochmann3** [comment]
> A capture group with a quantifier captures only the first occurrence of the enclosed pattern.

Don't you mean the *last* occurrence? `re.split(r'(\r|\n)+', 'x\n\n\ry')` returns `['x', '\r', 'y']`.

**Comment by blhsing** [comment]
> > A capture group with a quantifier captures only the first occurrence of the enclosed pattern.
> 
> Don't you mean the _last_ occurrence? `re.split(r'(\r|\n)+', 'x\n\n\ry')` returns `['x', '\r', 'y']`.
Ah yes my bad. Thanks for the correction!

**Comment by WiC-htao** [comment]
> Concur with @blhsing. You can use `re.finditer()` to see in details what was found.
> 
> For future, please use text instead of pictures for your examples. It is difficult to copy the code from a picture, it is also bad for visually impaired people.

Sorry for using pictures. I am working on a rdp, which is not allowed to copy. And I don't have a local dev env. But I will try my best in the future.
