### ISSUE TITLE
functools.cache treats a named positional argument as a different one from an unnamed one

### ISSUE THREAD

**Issue by filip-zyzniewski** [python/cpython#119120]
# Bug report

### Bug description:

```python
import functools
import sys


seen_args = set()


@functools.cache
def fun(arg):
    assert arg not in seen_args
    seen_args.add(arg)


print("Python version:", sys.version)

fun(5)
fun(5)
fun(arg=5)
```

First two calls behave OK, but the third one treats `arg=5` and `5` as different arguments for `fun(arg)`

```console
 ~ $ python3 test.py
Python version: 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
Traceback (most recent call last):
  File "/Users/Filip.Zyzniewski/test.py", line 18, in <module>
    fun(arg=5)
  File "/Users/Filip.Zyzniewski/test.py", line 10, in fun
    assert arg not in seen_args
           ^^^^^^^^^^^^^^^^^^^^
AssertionError
~ $
```

I would expect the second `fun(5)` and `fun(arg=5)` calls to return the cached entry for arg=5.

Perhaps some comparison of keyword argument names against named argument names is needed here?

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by rhettinger** [comment]
This is the documented behavior, "Distinct argument patterns may be considered to be distinct calls with separate cache entries.".   

Inspecting the wrapped function and comparing to argument names would be too expensive.
