### ISSUE TITLE
Python -VV should display whether the build is default build or free-threading.

### ISSUE THREAD

**Issue by corona10** [python/cpython#119132]
Currently, there is no way to identify whether the build is free-threaded or not through `python -VV`
See the pyperf and pyperformance case
* https://github.com/psf/pyperf/pull/189
* https://github.com/python/pyperformance/pull/336

The following display would be great.
```
Python 3.14.0a0 (heads/main-dirty:31a28cbae0, May 17 2024, 17:30:32, default) [GCC 14.1.1 20240507 (Red Hat 14.1.1-1)]

Python 3.14.0a0 (heads/main-dirty:31a28cbae0, May 17 2024, 17:30:32, free-threading) [GCC 14.1.1 20240507 (Red Hat 14.1.1-1)]
```

### Linked PRs
* gh-119134
* gh-119140
* gh-119143
* gh-119145
* gh-119153
* gh-135550
* gh-135565
* gh-135591
* gh-135594

**Comment by corona10** [comment]
cc @hugovk @vstinner @colesbury

**Comment by vstinner** [comment]
If we cannot agree on changing `sys.version`, at least, `python -VV` can be modified in `Python/initconfig.c`:

```
    if (print_version) {
        printf("Python %s\n",
                (print_version >= 2) ? Py_GetVersion() : PY_VERSION);
        return _PyStatus_EXIT(0);
    }
```

The code can be modified to log if Python is built with free-threading or not.

**Comment by corona10** [comment]
> If we cannot agree on changing sys.version, at least, python -VV can be modified in Python/initconfig.c:

It's better!
