### ISSUE TITLE
pathlib.Path.with_suffix(None) became allowed in Python 3.13b1

### ISSUE THREAD

**Issue by bluetech** [python/cpython#119113]
# Bug report

### Bug description:

In Python 3.13b1 (compared to Python 3.12 and earlier), the behavior of `pathlib.Path.with_suffix(None)` changed from raising an incidental `TypeError` to removing the suffix. This casues a [certain test](https://github.com/pytest-dev/pytest/blob/fdf3aa3fc35ee6d336eafef5016f308b5e57bddb/testing/test_legacypath.py#L36-L39) in pytest to fail. I am going to fix pytest to not rely on this in any case, but I think pathlib should either:

- Restore the previous behavior if it was unintended, or
- Update [the doc](https://docs.python.org/3.14/library/pathlib.html#pathlib.PurePath.with_suffix) that `None` is now accepted. Currently it says " If the suffix is an empty string, the original suffix is removed".

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-119124
* gh-119183

**Comment by nineteendo** [comment]
Bisected to https://github.com/python/cpython/commit/19a1fc1b3df30f64450d157dc3a5d40c992e347f

https://github.com/python/cpython/blob/100c7ab00ab66a8c0d54582f35e38d8eb691743c/Lib/pathlib/_abc.py#L208

I guess we could replace that with this:

```python
if suffix == '':
```

But we usually don't go out of our way to raise type errors.

**Comment by barneygale** [comment]
Thanks for reporting! Should be fixed in 3.13 beta 2.
