### ISSUE TITLE
`SLOW_SUM` flag in `sum` builtin

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#119192]
# Bug report

Here's a very strange condition that we have in our `sum` definition: https://github.com/python/cpython/blob/0abf997e75bd3a8b76d920d33cc64d5e6c2d380f/Python/bltinmodule.c#L2573-L2577

But, here are the strange parts:
1. `SLOW_SUM` is never documented
2. There are no `configure` options to set it
3. There are no other mentions of it in CPython
4. I was only able to find this mention of it on the internet: https://www.reddit.com/r/Python/comments/18vv3aa/what_is_slow_sum_in_the_cpython_source_code/
5. I don't think that it should exist, because it might change the builtin if this identifier is somehow magically defined. This would be a bug, because this is never documented / promised by us. It would be quite cryptic bug also
6. It is very old and still not "official", added in https://github.com/python/cpython/commit/8ce8a784bd672ba42975dec752848392ff9a7797

I propose to remove it and always have a single way how `sum` behaves.
I will send a PR.

### Linked PRs
* gh-119193

**Comment by rhettinger** [comment]
I wish you would leave this in. It helped greatly in testing, in proving that it really is an optimization, and in segregating the more complex optimization path from the core logic.

**Comment by tim-one** [comment]
OTOH, does it actually serve a purpose to give it a name? That is, wouldn't `#if 1` allow a 1-character edit to turn it off when that's wanted? You have to recompile to change the behavior anyway.

No strong opinion from me regardless. But if you haven't actually #_defined_ it in, say, the last year, you shouldn't have a strong opinion either :wink:.
