### ISSUE TITLE
Fraction wrongfully gets casted into float when given as argument to __rpow__

### ISSUE THREAD

**Issue by retooth2** [python/cpython#119189]
# Bug report

### Bug description:

When using the `**` operator with a Fraction as a base and an object that implements `__rpow__` as an exponent the fraction gets wrongfully casted into a float before being passed to `__rpow__`

```python
from fractions import Fraction

foo = Fraction(4, 3)

class One:
    def __rpow__(self, other):
        return other

bar = foo**One()
print(bar)
print(type(bar))
```

Expected Output
```
4/3
<class 'fractions.Fraction'>
```

Actual Output:
```
1.3333333333333333
<class 'float'>
```

Tested with Python 3.12.3

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-119236
* gh-119242
* gh-119255
* gh-119256
* gh-119298
* gh-119346
* gh-119347
* gh-119835
* gh-119836

**Comment by MojoVampire** [comment]
It's a mistake in the implementation of `Fraction.__pow__`; rather than returning `NotImplemented` when the type of the exponent is unrecognized and letting the other type handle it through `__rpow__` normally, it intentionally does `return float(a) ** b` (where `a` is the name given to `self`).

It does something similar when a fraction is raised to a fraction, but it at least makes more sense there (the comments note that raising a fraction to a fraction generally produces an irrational number, which can't be represented as a fraction in the first place).

**Comment by MojoVampire** [comment]
Is anyone working on a fix? If not, this is an easy one, I can do it.

I worry slightly about possible breakage of existing code, but:

1. The existing behavior is a *clear* break from the operator overloading rules, and not one justified by anything special about fractions (unlike the fraction to fractional power case)
2. The existing behavior loses data, while the fix would not, so if the existing behavior is desired, an `__rpow__` provider can always revert to the old behavior manually (they don't even need it to be version-specific; if they detect a `Fraction`, which can't be given right now, they convert to `float`; on older Python, they'll never see a `Fraction` in the first place)
3. I can't imagine many cases where this code path is exercised; if you're writing a type designed to work with numbers like this, it's almost always going to be part of the numeric tower, and should be able to handle other layers of the numeric tower appropriately.

**Comment by zitterbewegung** [comment]
@MojoVampire I am working on a fix I'm in the cpython sprint.

**Comment by MojoVampire** [comment]
Same. I'm the guy standing up cause my back is borked. Fix is pretty easy:

```
        elif isinstance(b, (float, complex)):
            return float(a) ** b
        else:
            return NotImplemented
```

replacing the existing final line. Tests are always the pain. I'll review when you're done.

**Comment by retooth2** [comment]
> 3. I can't imagine many cases where this code path is exercised; if you're writing a type designed to work with numbers like this, it's almost always going to be part of the numeric tower, and should be able to handle other layers of the numeric tower appropriately.

For context: I stumbled over the bug when implementing a wrapper number class for exact precision arithmetic that holds the data as a symbolic expression (so e.g. irrational numbers can be used in calculations without error). The class is designed to work with all builtin number types, e.g.

```python
a = Fraction(1, 3)
b = ExactNumber(Fraction(1, 2))
print(a**b)
```
```
ExactNumber(1/3**1/2)
```

My class is built on the sympy package that does similar things on its own, so this should also be relevant to them.
Anyway: Thanks for the quick response, I really appreciate it.

Best,
Fabian

**Comment by serhiy-storchaka** [comment]
I worked on this today. The issue itself may be not difficult, but I noticed that tests do not cover many cases in mixed Fraction arithmetic. #119236 adds many new tests, so we will see what other side effect our changes can cause.

**Comment by zitterbewegung** [comment]
@serhiy-storchaka I will look at this with @MojoVampire to see if there are any additional issues.

**Comment by zitterbewegung** [comment]
With this fix I see a test failure when manually putting in the new test_fractions code. 

`11 tests skipped (resource denied):
    test_curses test_peg_generator test_pyrepl test_smtpnet
    test_socketserver test_tkinter test_ttk test_urllib2net
    test_urllibnet test_winsound test_zipfile64

1 test failed:
    test_fractions

441 tests OK.

Total duration: 5 min 51 sec
Total tests: run=43,062 skipped=1,950
Total test files: run=467/478 failed=1 skipped=25 resource_denied=11
Result: FAILURE`

**Comment by serhiy-storchaka** [comment]
The new tests were purposed to fail with this change. They were added so that we can see what effect the change has and decide whether it is correct. If some visible changes are not correct, we should find other fixes for such cases.

I have other changes for mixed Fraction arithmetic, but I am not sure that they should be backported, so I'll create a separate PR.

**Comment by serhiy-storchaka** [comment]
See also #119838.
