### ISSUE TITLE
[Doc] no documentation for async with

### ISSUE THREAD

**Issue by youkaichao** [python/cpython#119191]
Surprisingly, I find the documentation https://docs.python.org/3/library/asyncio.html does not even mention `async with` . However, this kind of usage is quite popular in libraries such as `aiohttp` https://github.com/aio-libs/aiohttp .

**Comment by blhsing** [comment]
Note that `async with` is formally documented in https://docs.python.org/3.9/reference/compound_stmts.html#the-async-with-statement and mentioned in https://docs.python.org/3/library/asyncio-task.html .
