### ISSUE TITLE
Python is not getting location services permission

### ISSUE THREAD

**Issue by Pikman** [python/cpython#119139]
# Bug report

### Bug description:

Issue described here: https://superuser.com/questions/1841767/give-python-program-location-services-access-via-command-line-on-macos/1842838?noredirect=1#comment2914653_1842838

If i'm running code which requires "Location services" I'm not getting permission pop-up. If I'm going to permissions by myself and allow python - it shows as allowed but when I refresh it still shows as disabled. 
Other apps are working good.
![image](https://github.com/python/cpython/assets/10552854/89ac85fb-6938-4d14-b578-77d4e49e2dff)

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

**Comment by ronaldoussoren** [comment]
How did you install Python (Python.org installer, HomeBrew, ...) and which version of macOS are you on?

The setting works on my machine (macOS 14.5, python installed using the python.org installer).

Note that in general macOS requires info plist keys for this (see https://developer.apple.com/documentation/corelocation/requesting_authorization_to_use_location_services?language=objc), but AFAIK that's not enforced at the moment and our framework build doesn't include these keys.

The interaction with the permissions/entitlements system on macOS can also be annoy link finicky.

**Comment by Pikman** [comment]
I think python is built-in in macos distribution and controlled by Apple.. 
Still I can try to install version from brew or from python.org

**Comment by Pikman** [comment]
I had brew version installed, after I removed all of them original python3 (3.9) is working good and gave me pop-up windows. 
Thanks for help!
