### ISSUE TITLE
inconsistent bahaviour of `functools.partial` python and C

### ISSUE THREAD

**Issue by dg-pb** [python/cpython#119177]
# Bug report

### Bug description:

```python
    def __new__(cls, func, /, *args, **keywords):
        ...
        if hasattr(func, "func"):
```
```C
static PyObject *
partial_new(PyTypeObject *type, PyObject *args, PyObject *kw)
{
    int res = PyObject_TypeCheck(func, state->partial_type);
    ...
    if (res == 1) {
```
I believe python implementation should do:
```
if isinstance(func, cls):
```
Or were there any good reasons to check attribute instead?

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

macOS

**Comment by sobolevn** [comment]
Thanks for the report!

But, I think that this is duplicate of https://github.com/python/cpython/issues/100242
