### ISSUE TITLE
is_dataclass() returns True for non-dataclass subclass of dataclass

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#119260]
# Bug report

### Bug description:

If a dataclass has a subclass that is not itself a dataclass, `is_dataclass()` returns True on the subclass and its instances:

```python
from dataclasses import dataclass, is_dataclass

@dataclass
class X:
    y: int

class Z(X):
    pass

print(is_dataclass(Z))  # True
print(is_dataclass(Z()))  # True
```

Documentation of is_dataclass() for reference: https://docs.python.org/3.13/library/dataclasses.html#dataclasses.is_dataclass

Intuitively this seems wrong: Z is not itself a dataclass. In pyanalyze I wrote a replacement for `is_dataclass()` because I needed to check whether the exact class was a dataclass:

```python
def is_dataclass_type(cls: type) -> bool:
    try:
        return "__dataclass_fields__" in cls.__dict__
    except Exception:
        return False
```

Changing the CPython behavior might be impossible for compatibility reasons, but in that case, we should document and test this edge case.

cc @ericvsmith @carljm for dataclasses.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-119480
* gh-119760
* gh-119761

**Comment by blhsing** [comment]
I think the current behavior makes sense. A subclass of a dataclass still posesses all the characteristics of the dataclass even if it is not decorated with `dataclass`. Its instances can still be passed to `astuple`, `asdict` and `replace`. It's just that without the `dataclass` decorator it cannot declare additional fields.

**Comment by carljm** [comment]
I agree with @blhsing -- I think the current behavior is probably better.

This behavior should be explicitly tested and documented, though; currently it isn't.

**Comment by ericvsmith** [comment]
Agreed with @carljm, especially the part about adding tests and docs. I'm surprised there's no test for this.

**Comment by adiaholic** [comment]
> I think the current behavior makes sense. A subclass of a dataclass still possesses all the characteristics of the dataclass even if the subclass is not decorated with `dataclass`. Its instances can still be passed to `astuple`, `asdict` and `replace`. It's just that without the `dataclass` decorator it cannot declare additional fields.

I was able to declare additional fields in subclasses.

```
from dataclasses import dataclass, is_dataclass

@dataclass
class X:
    y: int

class Z(X):
    z: int = 0  # Adding a default field to demonstrate inheritance and dataclass behavior

print(is_dataclass(X))  # True
print(is_dataclass(Z))  # True, Z inherits from X and is also treated as a dataclass
```

**Comment by JelleZijlstra** [comment]
Your subclass also has the `@dataclass` decorator. This issue is about subclasses without the decorator.

**Comment by adiaholic** [comment]
> Your subclass also has the `@dataclass` decorator. This issue is about subclasses without the decorator.

My bad, corrected the example in the comment above 😃

**Comment by carljm** [comment]
> I was able to declare additional fields in subclasses.

No, you were able to add a normal Python class attribute to a subclass, which is sufficient to fool your test because of Python's normal behavior where instance attribute access falls back to the class. The thing you added in the subclass is not a dataclass field:

```
>>> Z.__dataclass_fields__.keys()
dict_keys(['y'])
>>> Z(y=1, z=2)
Traceback (most recent call last):
  File "<python-input-6>", line 1, in <module>
    Z(y=1, z=2)
    ~^^^^^^^^^^
TypeError: X.__init__() got an unexpected keyword argument 'z'
```

**Comment by carljm** [comment]
Thanks @adiaholic for the PR!
