### ISSUE TITLE
Remove legacy TODOs from code.

### ISSUE THREAD

**Issue by jeremyhylton** [python/cpython#119219]
# Bug report

### Bug description:

I left a few TODOs in the compiler code from its early development. They are no longer relevant. For example, they comment on issues to consider that do not appear to have been a priority in years. 

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-119223

**Comment by rhettinger** [comment]
Were those open items resolved or are they things we just don't care about anymore?

**Comment by jeremyhylton** [comment]
We don't care about them anymore. They didn't seem urgent enough for anyone
else to look at in the intervening years, and they don't seem critical
either. How important is a realloc for an allocation in an arena that
already has a fixed lifetime. Do you see a reason to think harder about it?

Jeremy

**Comment by rhettinger** [comment]
I was just curious.  Go ahead and do whatever makes sense to you.

**Comment by rubyFeedback** [comment]
>  Do you see a reason to think harder about it?

Perhaps nostalgia. We may all have higher ambitions when we were younger ... :)

(TODO entries are always a bit awkward though. Some TODOs I can solve quickly or
within a reasonable time; others stay there for years, so perhaps this applies to
the latter one as well, in which case it may be easier to just get rid of them rather
than let them linger.)
