### ISSUE TITLE
`contextlib.suppress` converts instances of a subtype of `ExceptionGroup` to an instance of the `ExceptionGroup` class

### ISSUE THREAD

**Issue by DetachHead** [python/cpython#119287]
# Bug report

### Bug description:

```python
from contextlib import suppress

class FooException(Exception): ...

class FooExceptionGroup(ExceptionGroup[Exception]): ...

try:
    with suppress(FooException):
        raise FooExceptionGroup("", [Exception()])
except ExceptionGroup as e:
    print(type(e))
```

in this code, the `suppress` context manager is expected to have no effect, as a `FooException` is not being raised within it. instead, it gets converted to an `ExceptionGroup` then re-raised.

expected output:
```
<class '__main__.FooExceptionGroup'>
```

actual output:
```
<class 'ExceptionGroup'>
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-119657
* gh-120105
* gh-120106

**Comment by TeamSpen210** [comment]
For `ExceptionGroup` subclasses, you need to implement the `derive()` method, so that other code knows how to create a new exception group. It can't call the class since yours could have additional required arguments. If you do that then you'll get back your subclass.

**Comment by DetachHead** [comment]
thanks, that seems to work. however i think this behavior should be documented either [in the docs for the `derive` method](https://docs.python.org/3/library/exceptions.html#BaseExceptionGroup.derive) (which currently only mentions that it's used by the `split` and `subgroup` methods, but not `contextlib.suppress`), or [in the docs for `contextlib.suppress`](https://docs.python.org/3/library/contextlib.html#contextlib.suppress) (which mentions that `ExceptionGroup`s are supported as of python 3.12, but not that the `derive` method is required for it to work correctly)
