### ISSUE TITLE
The docstrings for PyMapping_Values, PyMapping_Items and PyMapping_Keys are incorrect

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#119391]
# Documentation

The docstring for `PyMapping_Keys`

> /* On success, return a list or tuple of the keys in mapping object 'o'.

 does not reflect the documentation (see https://docs.python.org/3/c-api/mapping.html#c.PyMapping_Keys) or the implementation (see [abstract.c#L2519](https://github.com/python/cpython/blob/858b9e85fcdd495947c9e892ce6e3734652c48f2/Objects/abstract.c#L2519)) as `PyMapping_Keys` can only return a list. Similar for the other methods.

The docstrings show up in IDEs (such as Visual Studio Code) and can cause confusion. I encountered this when working on the making the json module compatible with free-threading

### Linked PRs
* gh-119392

**Comment by devdanzin** [comment]
The docstrings became incorrect after 0ccc0f6c7495be9043300e22d8f38e6d65e8884f.
