### ISSUE TITLE
Resolve deprecation warnings in Docs/tools

### ISSUE THREAD

**Issue by drts01** [python/cpython#119317]
# Documentation

The following scripts are throwing deprecation warnings.

- Docs/tools/extensions/pyspecific.py
- Docs/tools/extensions/glossary_search.py

```
PendingDeprecationWarning: nodes.Node.traverse() is obsoleted by Node.findall()
```

### Linked PRs
* gh-119319
* gh-119486
* gh-119487

**Comment by hugovk** [comment]
Looks like this is from docutils 0.18.1 (2021-11-23):

> New method Node.findall(): like Node.traverse() but returns an iterator. Obsoletes Node.traverse(). 

https://docutils.sourceforge.io/HISTORY.html#release-0-18-1-2021-11-23
