### ISSUE TITLE
'_PyLong_NumBits': identifier not found in 3.13

### ISSUE THREAD

**Issue by clin1234** [python/cpython#119336]
# Bug report

### Bug description:

While fixing pywin32 to let CI builds work in Python 3.13, the build process complained of not being able to find `_PyLong_NumBits`. All other Python versions in the CI built successfully.

```c
BOOL PyCom_VariantFromPyObject(PyObject *obj, VARIANT *var)
{
    // ...
    if (PyLong_Check(obj)) {
        int sign = _PyLong_Sign(obj);
        size_t nbits = _PyLong_NumBits(obj);
        if (nbits == (size_t)-1 && PyErr_Occurred())
            return FALSE;
    // ...
}
```

The function still exists in `main`, apparently inaccessible via the public C API since 3.13. What's the recommended replacement?

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-119418
* gh-119970

**Comment by ethanhs** [comment]
In https://github.com/python/cpython/commit/58469244beceb515c74cbdbd655256c0da569612 Victor restored

* `_PyLong_Copy()`
* `_PyLong_FromDigits()`
* `_PyLong_New()`
* `_PyLong_Sign()`

It seems reasonable to include `_PyLong_NumBits` as well.

**Comment by clin1234** [comment]
Will it be restored in the next beta 3.13 release, or will I have to wait until the first 3.14 alpha release?

**Comment by ethanhs** [comment]
I cannot make that call, but I made https://github.com/python/cpython/pull/119418 against 3.14 for now (it can be backported for 3.13 if that's what people decide). Eventually it seems like a good idea to make this public.

**Comment by clin1234** [comment]
> You can modify pywin32 to call the `bit_length()` method which returns a Python int object. Then if you need a `size_t`, you can call `PyLong_AsSize_t`.
> 
> If this function is called by one project, we should consider making it public, rather than restoring the old private function.

How would I access the built-in `bit_length()` method within the C API?

**Comment by da-woods** [comment]
> How would I access the built-in `bit_length()` method within the C API?

`PyObject_CallMethod(obj, "bit_length", NULL)`

(Not taking a view on whether that justifies not restoring the function though)

**Comment by vstinner** [comment]
A code search in PyPI top 7,500 projects found other projects:

* mariadb (1.1.10)
* pickle5 (0.0.12)
* zodbpickle (3.2)

pickle5 and zodbpickle contain copies of the Python source code, but MariaDB is a good usage example. So maybe it's worth it to add a function.

I created issue gh-119714: [C API] Add PyLong_GetNumBits() function.

**Comment by vstinner** [comment]
> A code search in PyPI top 7,500 projects found other projects:

@encukou also identified that **panda3d** uses it: https://github.com/panda3d/panda3d/blob/adb92428856853019583f398d27c5d34e44a9343/panda/src/putil/bitArray_ext.cxx#L28

**Comment by vstinner** [comment]
Function restored by commit https://github.com/python/cpython/commit/e50fac96e82d857ecc024b4cd4e012493b077064
