### ISSUE TITLE
`argparse.BooleanOptionalAction` does not yield mutually exclusive options

### ISSUE THREAD

**Issue by e-kwsm** [python/cpython#119375]
# Bug report

### Bug description:

```python
import argparse

p = argparse.ArgumentParser()
p.add_argument("--foo", action=argparse.BooleanOptionalAction)
print(p.parse_args(["--foo", "--no-foo"]))  # Namespace(foo=False)
print(p.parse_args(["--no-foo", "--foo"]))  # Namespace(foo=True)
```

Here `BooleanOptionalAction` is used, but the options, `--foo` and `--no-foo`, are *not* mutually exclusive, and the last one becomes effective without warning.

OTOH the below code

```python
import argparse

p = argparse.ArgumentParser()
g = p.add_mutually_exclusive_group()
g.add_argument("--foo", action="store_true")
g.add_argument("--no-foo", action="store_true")
p.parse_args(["--foo", "--no-foo"])
```

raises error:

```
usage: [-h] [--foo | --no-foo]
: error: argument --no-foo: not allowed with argument --foo
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by serhiy-storchaka** [comment]
This is the correct behavior. What do you expect?

**Comment by e-kwsm** [comment]
```python
>>> p.print_usage()
usage: [-h] [--foo | --no-foo]
```

indicates that the options, `--foo` and `--no-foo`, are mutually exclusive.

I don’t believe it makes sense to pass the both.

**Comment by makukha** [comment]
In my opinion, this is not a bug. [Mutually exclusive groups](https://docs.python.org/3/library/argparse.html#mutual-exclusion) is the only context in `argparse` docs where the concept of mutual exclusivity appear.

Being turned on and off seems natural for boolean options. Consider the case when command args need to be overridden:
```shell
$ export PIP="pip --cache-dir=~/.mycache"
$ ${PIP} --no-cache-dir <whatever>
```

**Comment by e-kwsm** [comment]
(`--cache-dir`/`--no-cache-dir` are a bit out of the context as the former takes a parameter.)

I don’t believe it is user-friendly. If this is a feature then the behaviour should be documented.

**Comment by serhiy-storchaka** [comment]
Why anybody want to have both `--foo` and `--no-foo` at first place? One of options is the default, so you only need it to cancel the other option. This is the purpose of having both options.

If you want to make them exclusive, just use an exclusive group. `[--foo | --no-foo]` in the help output indicates rather that only one of options (the last one) will have effect. We could use other notation to distinguish these variants, but I have nothing in my mind that would not look unusual and confusing.

**Comment by mpkocher** [comment]
> This is the correct behavior. What do you expect?

`--foo` and `--no-foo` are orthogonal, hence I assumed that these would behave somewhat similar to mutually exclusive arguments.  The argument formatting style is also suggesting this. 

The silent setting of the last argument provided (instead of raising an error) is a bit surprising.  


Perhaps this is just not consistent amongst libraries/communities. 

black uses click and it's fine with these conflicting flags. 

```bash
black --diff example.py  --no-color --color
```

While uv does raise exceptions (this might not the greatest example). 

```bash
uv tree --only-dev --no-dev
error: the argument '--only-dev' cannot be used with '--no-dev'

Usage: uv tree --only-dev
```
