### ISSUE TITLE
ZipFile.extractall() extracts to similarly named directories instead of the name of the zipfile

### ISSUE THREAD

**Issue by DWThayerMahan** [python/cpython#119442]
# Bug report

### Bug description:

I discovered that when extracting the file "testfile (2).zip" or "testfile2.zip", instead of creating a new directory of the same name, the folder "testfile" and its contents would be overwritten. This happens even if a directory named "testfile (2)" or "testfile2", respectively, is created before extraction.
```location = "assets/Session/"
if not os.path.exists(location):
    os.makedirs(location)
with open(location+name, "wb") as f:          #name is testfile (2).zip or similar
    f.write(data)
if os.path.exists(location+nameParts[0]):      #nameParts is the result of name.rsplit('.',1). i.e., ['testfile (2)', 'zip]
    return True, name, contents, tab, ProjectName, WOpen, WTitle, WBody, tz, DTkids, purl
with ZipFile(location+name, 'r') as z:
    try:
        z.extractall(location)                          #This results in the overwrite of the directory "testfile"
    except zipfile.error as e:
        print(e.name)
    else:
        print(os.path.exists(location+nameParts[0]))
        ```

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by serhiy-storchaka** [comment]
What is the content of files "testfile (2).zip" and "testfile2.zip" and how do you extract them? Could you provide minimal self-sufficient code to reproduce your issue?

**Comment by DWThayerMahan** [comment]
> What is the content of files "testfile (2).zip" and "testfile2.zip" and how do you extract them? Could you provide minimal self-sufficient code to reproduce your issue?

The contents are an mp4, a json, 2 txt files, and 2 csv files. I'm confused how that's relevant though considering the issue has to do with directory names. What is missing from the code sample provided to make it a reproduceable?

**Comment by serhiy-storchaka** [comment]
So how do you extract them? Your code is not self-sufficient, it contains many not defined names, and since it has returns, it must be a part of function.

Is it equivalent to the following code
```py
os.mkdir("testfile")
os.mkdir("testfile (2)")
with ZipFile("testfile (2).zip", 'r') as z:
    z.extractall("testfile (2)")
```
and the archive is extracted in the "testfile" directory instead of the "testfile (2)" directory?

**Comment by DWThayerMahan** [comment]
> So how do you extract them? Your code is not self-sufficient, it contains many not defined names, and since it has returns, it must be a part of function.
> 
> Is it equivalent to the following code
> 
> ```python
> os.mkdir("testfile")
> os.mkdir("testfile (2)")
> with ZipFile("testfile (2).zip", 'r') as z:
>     z.extractall("testfile (2)")
> ```
> 
> and the archive is extracted in the "testfile" directory instead of the "testfile (2)" directory?

ok i added more code and some comments to define some of the relevant variables

**Comment by serhiy-storchaka** [comment]
What is `location`?

You said that `z.extractall(location)` overwrites the "testfile" directory. Is `location` the path of the "testfile" directory? Does the archive contain the "testfile" directory?

Please provide a code that anybody can run and reproduce your results.

**Comment by DWThayerMahan** [comment]
location is "assets/Session/". testfile's location is "assets/Session/testfile". "testfile (2).zip" and "testfile2.zip" are extracted to "assets/Session/"

**Comment by serhiy-storchaka** [comment]
This is a correct behavior. `ZipFile.extractall()` extracts all members from the archive to the specified directory.

**Comment by DWThayerMahan** [comment]
I see, the issue is that there is a second folder inside the zip file of the name testfile that is overwritting the directory. exctractall() does not create a new folder unless one is specified?
