### ISSUE TITLE
Python 3.12.3 installer does not update py.exe in c:\windows

### ISSUE THREAD

**Issue by x95amk76** [python/cpython#119446]
# Bug report

### Bug description:

Upgrading python to 3.12.3 on a server.  I checked the option to add python to path and everything installed fine, but it didn't update the py.exe launcher.

Is there somewhere I can get a package to update the launcher itself or would I have to wait for the next version to be released ?

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
The Windows installer has an checkbox option to install py.exe.  Was it checked?  If sure, rerun the installer and click modify/repair (or maybe do so on add-apps dialog), and make sure it is click, it should install.  I do not know the rules for what the default is.

**Comment by zooba** [comment]
Already fixed in #118347

**Comment by x95amk76** [comment]
I did have the option checked to install py.exe.  I ran a repair with the option checked again and it still didn't update.  Tired the ALLUSERS=1 option as well and it didn't update the launcher.

I saw a related post to download the launcher.msi and run that but I just saw a command prompt window flicker and disappear, but the launcher didn't update.  I may try it again tonight though to see what I can see.

**Comment by zooba** [comment]
You might also be helped by uninstalling the old launcher (it has its own entry in Programs and Features). If you do that, then reinstalling 3.12.3 should bring it back (probably not just repairing, but I'm not 100% sure - maybe Modify will do it).
