### ISSUE TITLE
Python 3.12 docs website search results prioritizes "what's new" instead of actual topic

### ISSUE THREAD

**Issue by Saba-Sabato** [python/cpython#119423]
(I initially posted this in the [pythondotorg](https://github.com/python/pythondotorg/issues/2452) repo - where I was directed here. Copying the description from there verbatim)

**Describe the bug**
Searching for library modules on 3.12 returns first a list of "What's new in \<version\>" pages instead of the searched for module.

**To Reproduce**
1. Go to https://docs.python.org/3.12/index.html
2. Click on search box in top right corner, enter e.g. "asyncio" and hit enter
3. [Scroll through results](https://docs.python.org/3.12/search.html?q=asyncio)
4. See that the first result is "History and License" followed by 10 (!) "What’s New In Python \<version\>" results. The 11th result is the actual asyncio module.

**Expected behavior**
I would expect the asyncio module page to be the first result, or at the very least to appear very close to the top. This has been the case in previous versions of the website search.

**Screenshots**
(the list goes on a few more entries below the screenshot)
<img width="880" alt="image" src="https://github.com/python/pythondotorg/assets/20134422/43c44cd9-39f1-49ac-9800-ec59fe182245">

Compare with search from 3.11:
<img width="1118" alt="image" src="https://github.com/python/pythondotorg/assets/20134422/8e07f1c8-151d-4ea3-86c6-bc5454194399">

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome
 - Version 123

**Additional context**
This happens for other topics too, not only modules.

**Comment by pochmann3** [comment]
Maybe related and bothered me yesterday: I went to the [Table of Contents](https://docs.python.org/3/contents.html) and searched for "async" and had to step through quite a few occurrences in multiple  "What’s New In Python x.y" sections before I gave up and did something else.

**Comment by mi1acl** [comment]
I'm working on this one, will update in 2-3 hrs

**Comment by picnixz** [comment]
It might be an issue with Sphinx as well, so feel free to ping me. I remember we changed the search algorithm so this might have affected that, though I honestly don't know why the search would be different depending on the version.

**Comment by hugovk** [comment]
It sounds like Sphinx to me too: the 3.12 docs were created with Sphinx 7.3.7 and 3.11 with Sphinx 7.2.6 (the version is shown in the footer).

Should this be reported to https://github.com/sphinx-doc/sphinx?

**Comment by picnixz** [comment]
Definitely yes! I'll tag the relevant maintainers for that component.

**Comment by mi1acl** [comment]
I spent some time last night on this. Looks like there has been a change in the way Sphinx ranks the results. 

I changed the `searchtools.js` generated by the build process. The first 10 rows get score of 100 which they clearly shouldn't. the actual asyncio gets a score of 15.

**Comment by picnixz** [comment]
Yes we changed the ranking because other pages were affected but it appears that we did not consider thoses cases. I think we should sorting the results differently depending on the length of the title and where the match is done (like, is it at the beginning or not). 

Another possibility is that we incorrectly guessed the What's New asyncio because of the "title-like" section and handle it as the "principal" asyncio. I was expecting someone to open an issue meanwhile but I'll do it myself (I think it'd be best to continue the discussion on Sphinx' side).

**Comment by wlach** [comment]
> Yes we changed the ranking because other pages were affected but it appears that we did not consider thoses cases. I think we should sorting the results differently depending on the length of the title and where the match is done (like, is it at the beginning or not).

Just to be clear, the original code was clearly not working as intended but it appears that the bugs actually produced more desirable behaviour in some cases. I think there's a number of things we can do here, see the issue above for more discussion.

**Comment by wlach** [comment]
For what it's worth, updating the docs to use the latest minor version (7.4.x) of Sphinx should improve the results here somewhat. Give it a try!

**Comment by AA-Turner** [comment]
The current docs have been built with 7.4.6: https://docs.python.org/3.12/

A search for me (on mobile):

![image](https://github.com/user-attachments/assets/c295d3d5-3786-48a3-bafb-525d5b74c88f)

Seems improved!

A

**Comment by picnixz** [comment]
By the way, remember to clear your browser cache (CTRL+SHIFT+R on FF) (I needed to do otherwise I had the old results somewhat?)
