### ISSUE TITLE
Py_buffer.format declaration inconsistent with the docs

### ISSUE THREAD

**Issue by philthompson10** [python/cpython#119467]
# Bug report

### Bug description:

The declaration of the `format` field of the `Py_buffer` structure is `char *` but the documentation states it is `const char *`.

IMHO the declaration should be changed to match the docs.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-119475
* gh-119602
* gh-119603

**Comment by Eclips4** [comment]
Hello!
Would you like to send a PR with fix? :)

**Comment by philthompson10** [comment]
I'd like to - may take a while...

**Comment by adiaholic** [comment]
I have pushed a fix for this inconsistency. It would be great if @Eclips4 could review the changes and confirm if this resolves the issue. 

Feedback is highly appreciated!
