### ISSUE TITLE
multiprocessing child segfault when passing lock as an argument

### ISSUE THREAD

**Issue by DylanZA** [python/cpython#119413]
# Crash report

### What happened?

It seems that the below code will serialize the pointer to the lock handle over to the child process, and then rebuild the raw pointer in https://github.com/python/cpython/blob/main/Modules/_multiprocessing/clinic/semaphore.c.h#L331

this then segfaults the child process - which seems to cause new children to spin up.

```python
import multiprocessing
import os

def _init(l):
    print(os.getpid())
    print(l)

def main():
    ctx = multiprocessing.get_context(method="spawn")
    lock = multiprocessing.Lock()
    with ctx.Pool(1, initializer=_init, initargs=(lock,)) as pool:
        ret = pool.map(print, [1])

if __name__ == "__main__":
    main()
```

### CPython versions tested on:

3.10, 3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello! I guess this has been fixed in #107275. I cannot reproduce this in any of the 3.12, 3.13, or 3.14 branches. Versions lower than 3.12 do not accept bug fixes.

**Comment by DylanZA** [comment]
right - that makes sense. sorry for the noise in that case

**Comment by DylanZA** [comment]
fwiw for future people - the new error message makes it obvious that this change fixes the problem:
- lock = multiprocessing.Lock()
+lock = ctx.Lock()
