### ISSUE TITLE
Invalid escape sequences raise SyntaxWarning

### ISSUE THREAD

**Issue by Okarin99** [python/cpython#119458]
PEP 701 introduced with python version 3.12.3 claims to be backwards compatible.
But in python version 3.12.2 the string "\\.00" gives \\\\.00 and since python version 3.12.3 I get the follwing error:
`<stdin>:1: SyntaxWarning: invalid escape sequence '\.'`
`'\\.00'`

**Comment by pablogsal** [comment]
That has nothing to be with PEP 701. PEP 701 is about f-strings, not about strings in general. That change was introduced here:

https://github.com/python/cpython/commit/3483299a24e4

**Comment by terryjreedy** [comment]
The referenced commit is about octal sequences above 0o377.  The warning results from changing the invalid escape sequence warning from DeprecationWarning (usually invisible) to SyntaxWarning (usually visible, but not currently in IDLE and other possible circumstances) in 3.12 in issue #98401, PR #99011.  The same warning occurs with `'\.a'` and `'\.'`.

The change was in 3.12.0 and noted in [What' New 3.12](https://docs.python.org/3/whatsnew/3.12.html#other-language-changes):
>A backslash-character pair that is not a valid escape sequence now generates a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning), instead of [DeprecationWarning](https://docs.python.org/3/library/exceptions.html#DeprecationWarning).

If you want a single backslash in the string, either double it or precede the string with 'r': `'\\.00' == r'\.00'` is `True`.

**Comment by Okarin99** [comment]
Ahh ok that explains everything. I got this Error because Mathematica’s ExternalEvaluate didn’t use a valid escape sequence and I knew that in march all was working fine. I regularly update my system so I thought I was using python version 3.12.2 in march. But it turns out that Archlinux doesn’t update their python package that often, therefore I was using version 3.11.8 instead.
