### ISSUE TITLE
test_socket: testStream() fails on Fedora Rawhide

### ISSUE THREAD

**Issue by vstinner** [python/cpython#119461]
Example of failure: https://buildbot.python.org/all/#/builders/536/builds/7175

```
======================================================================
ERROR: testStream (test.test_socket.ThreadedVSOCKSocketStreamTest.testStream)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/test/test_socket.py", line 395, in _setUp
    self.__setUp()
    ~~~~~~~~~~~~^^
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/test/test_socket.py", line 538, in setUp
    self.conn, self.connaddr = self.serv.accept()
                               ~~~~~~~~~~~~~~~~^^
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/socket.py", line 295, in accept
    fd, addr = self._accept()
               ~~~~~~~~~~~~^^
TimeoutError: timed out

======================================================================
ERROR: testStream (test.test_socket.ThreadedVSOCKSocketStreamTest.testStream)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/test/test_socket.py", line 383, in raise_queued_exception
    raise self.queue.get()
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/test/test_socket.py", line 407, in clientRun
    self.clientSetUp()
    ~~~~~~~~~~~~~~~~^^
  File "/home/buildbot/buildarea/3.x.cstratak-fedora-rawhide-aarch64/build/Lib/test/test_socket.py", line 546, in clientSetUp
    self.cli.connect((cid, VSOCKPORT))
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
OSError: [Errno 19] No such device
```

### Linked PRs
* gh-119463
* gh-119465
* gh-119479
* gh-119484
* gh-129171
* gh-129440
* gh-129561
* gh-129564
* gh-129565
* gh-129566
* gh-130075

**Comment by vstinner** [comment]
It started failing around May 15, 2024.

First failure on x86-64: https://buildbot.python.org/all/#/builders/339/builds/5314

**Comment by vstinner** [comment]
> First failure on x86-64: https://buildbot.python.org/all/#/builders/339/builds/5314
> Latest success: https://buildbot.python.org/all/#/builders/339/builds/5313

The kernel was updated between the two builds.

* Before: `platform.platform: Linux-6.9.0-0.rc3.20240413git8f2c057754b2.35.fc41.aarch64-aarch64-with-glibc2.39.9000`
* After: `platform.platform: Linux-6.9.0-64.fc41.aarch64-aarch64-with-glibc2.39.9000`

**Comment by stratakis** [comment]
[changes.txt](https://github.com/python/cpython/files/15417113/changes.txt)

Package changes the day the build started failing.

**Comment by vstinner** [comment]
On Fedora **Rawhide** x86-64 and Linux kernel 6.9.0-64.fc41.x86_64, the device `/dev/vsock` **does** exist. get_cid() returns `4294967295`  which is `VMADDR_CID_ANY` (-1).

On Fedora **Stable** x86-64 and Linux kernel 6.8.10-300.fc40.x86_64, the device `/dev/vsock` **doesn't** exist. get_cid() returns `None` (if fails with `OSError`).

**Comment by vstinner** [comment]
Fixed by commit: https://github.com/python/cpython/commit/e94dbe4ed83460f18bd72563c5f09f6cdc71f604.
