### ISSUE TITLE
String format specifiers not accepted by object.__format__

### ISSUE THREAD

**Issue by blhsing** [python/cpython#119488]
# Bug report

### Bug description:

Given an instance of a class with `__str__` defined:
```python
class Foo:
    def __str__(self):
        return 'foo'

foo = Foo()
```
Formatting it will implicitly convert the object to a string:
```python
print(f'{foo}') # outputs "foo"
```
But adding a format specifier causes a `TypeError`:
```python
print(f'{foo:>10}') # TypeError: unsupported format string passed to Foo.__format__
```
Should this be considered a bug?

The current workaround is to explicitly convert the object to a string:
```python
print(f'{foo!s:>10}') # outputs "       foo"
```
But it seems counter-intuitive given how `f'{foo}'` does the conversion implicitly.

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux, Windows

**Comment by terryjreedy** [comment]
Please ask questions on our Discourse help channel: https://discuss.python.org/c/users/7 or elsewhere.

What you call a 'workaround' is the documented solution in https://docs.python.org/3/library/string.html#format-string-syntax if you do not define a `__format__` method.
> The conversion field causes a type coercion before formatting. Normally, the job of formatting a value is done by the [__format__()](https://docs.python.org/3/reference/datamodel.html#object.__format__) method of the value itself. However, in some cases it is desirable to force a type to be formatted as a string, overriding its own definition of formatting. By converting the value to a string before calling [__format__()](https://docs.python.org/3/reference/datamodel.html#object.__format__), the normal formatting logic is bypassed.

The format spec mini-language [section](https://docs.python.org/3/library/string.html#format-specification-mini-language) says "Most built-in types implement the following options for format specifications" and "A general convention is that an empty format specification produces the same result as if you had called [str()](https://docs.python.org/3/library/stdtypes.html#str) on the value."  Perhaps it should say that `object.__format__` only accepts an empty string, and so the same is true for classes that inherit that method.

**Comment by blhsing** [comment]
@terryjreedy Thanks. I'm aware of that portion of the current documentation, which addresses specifically how to force formatting as a string a user object that has a custom `__format__` defined.

In the case I'm reporting, however, the user object does not have a custom `__format__` defined, so through MRO it falls back to `object.__format__`, which, according to PEP-3101, should behave as if the format specifiers were passed to `format` after an implicit conversion of the object to a string:

> The `object.__format__` method is the simplest: It simply converts the object to a string, and then calls format again:
> ```python
> class object:
>     def __format__(self, format_spec):
>         return format(str(self), format_spec)
> ```

**Comment by terryjreedy** [comment]
The implementation and doc supercede the PEP.

**Comment by serhiy-storchaka** [comment]
This was a deliberate change. See https://github.com/python/cpython/issues/52242, https://github.com/python/cpython/issues/72571 and https://github.com/python/cpython/issues/73160.
