### ISSUE TITLE
Stop manually interning strings in pathlib

### ISSUE THREAD

**Issue by barneygale** [python/cpython#119518]
When parsing and normalizing a path, pathlib calls `sys.intern()` on the string parts:

https://github.com/python/cpython/blob/96b392df303b2cfaea823afcb462c0b455704ce8/Lib/pathlib/_local.py#L273

I've never been able to establish that this is a worthwhile thing to do. The implementation seems incomplete, because the path normalization only occurs when a user manually initialises a path object, and not in paths generated from `path.iterdir()`, `path.walk()`, etc. Drives/roots/anchors aren't interned despite most likely to be shared.

Previous discussion: https://github.com/python/cpython/pull/112856#issuecomment-1850272228

### Linked PRs
* gh-123356

**Comment by barneygale** [comment]
CC @pitrou

**Comment by pitrou** [comment]
It can probably be micro-optimized if you really care. For example I'm not sure the `str` call is still useful.
```python
>>> x = 'foo'
>>> %timeit str(x)
40.3 ns ± 0.169 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
>>> %timeit sys.intern(x)
46.9 ns ± 0.402 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
>>> %timeit sys.intern(str(x))
79.7 ns ± 0.635 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
>>> _intern = sys.intern
>>> %timeit _intern(x)
28.3 ns ± 0.11 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

**Comment by vstinner** [comment]
> The contention is that, if you keep a lot of related paths in memory, interning the path components would yield significant memory savings. 

Can pathlib have its own "interned strings" cache with a limit on the cache size? Well, I don't know if it's worth it :-)

Pseudo-code with a limit on 3 entries:

```py
cache = {}
def get(key):
    try:
        return cache[key]
    except KeyError:
        pass

    if len(cache) >= 3:
        return key

    cache[key] = key
    return key

abc = get(b'abc'.decode())
abc2 = get(b'abc'.decode())
assert abc2 is abc

d = get(b'd'.decode())
e = get(b'e'.decode())
e2 = get(b'e'.decode())
assert e2 is e

# cache no longer used
f = get(b'f'.decode())
print("cache size", len(cache))
```

Can pathlib remove entries from such cache?
