### ISSUE TITLE
Colorized output implemented in new REPL leaks into old REPL

### ISSUE THREAD

**Issue by eugenetriguba** [python/cpython#119551]
# Bug report

### Bug description:

When I run `PYTHON_BASIC_REPL=1 ./python.exe` from the `main` branch, the exception output is colorized:

<img width="1082" alt="Screenshot 2024-05-25 at 11 50 17" src="https://github.com/python/cpython/assets/15860938/a9934e01-070e-4982-bbe9-9ca5ce8199d4">

However, this isn't the case using the old REPL on older Python versions:

<img width="913" alt="Screenshot 2024-05-25 at 11 52 38" src="https://github.com/python/cpython/assets/15860938/af9aa2c0-7518-4753-8b3d-b818bb89a089">

Whether this is a "bug" can be decided on, but it is different behavior that _seemed_ like it was unintentional to me so I wanted to log it here.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by AlexWaygood** [comment]
I don't think this is actually anything to do with the REPL _per se_. I think this is just a consequence of the fact that all tracebacks -- in the REPL or otherwise -- are colourised on Python 3.13+, in a separate feature that has been added

**Comment by eugenetriguba** [comment]
@AlexWaygood Ah I appreciate the additional context there. I wasn't aware of that, thanks! Is this a "close, no issue here" then?

**Comment by AlexWaygood** [comment]
I think so, yup! See #112730 for more context :-)
