### ISSUE TITLE
Adjust deprecation warning re: testing truth value of `xml.etree.ElementTree.Element`

### ISSUE THREAD

**Issue by jacobtylerwalls** [python/cpython#119577]
Testing the truth value of an `ElementTree.Element` was deprecated in python 3.12 and scheduled for removal in 3.14. I have a patch ready.

- python/cpython#83122
- python/cpython#31149

### Linked PRs
* gh-119578
* gh-119762
* gh-120189
* gh-120190

**Comment by serhiy-storchaka** [comment]
AFAIK, the plan was to return True instead of raising an exception.

**Comment by jacobtylerwalls** [comment]
In favor of raising an error: https://github.com/python/cpython/issues/83122#issuecomment-1093848037
In favor of DeprecationWarning being the choice for an exception vs. FutureWarning being the choice to for a behavior change: https://github.com/python/cpython/issues/83122#issuecomment-1380113215

cc/ @gpshead who reviewed #31149, which changed FutureWarning to DeprecationWarning and documented that an exception would be raised.

**Comment by serhiy-storchaka** [comment]
Raising an exception in `__bool__()` is extremely uncommon behavior. For now, there is only one special case -- `NotImplemented`, and it is a very special case. On other hand, there is a precedence of `datetime.time` -- the midnight had the false boolean value, and now it has lost its special meaning and has the same boolean value like all other `datetime.time` values.

**Comment by jacobtylerwalls** [comment]
> What that means is that we need a PR to update the docs and the DeprecationWarning error message to reflect the new plan.

New PR: https://github.com/python/cpython/pull/119762

**Comment by hugovk** [comment]
Triage: closing because the PR has been merged, please re-open if still needed. Thanks!
