### ISSUE TITLE
Invalid Assert in PyState_FindModule()

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#119560]
# Crash report

### Bug description:

gh-118532 added an assert that is erroneously triggers if `PyState_FindModule()` is called before the provided module def has been initialized.  The assert should be removed.  (Python/import.c, line 460)

See https://github.com/ultrajson/ultrajson/issues/629.

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-119561
* gh-119632

**Comment by mgorny** [comment]
Thanks. I can confirm that after applying this on top of 3.13.0b1, ujson passes all tests.
