### ISSUE TITLE
Implement zipfile.Path.is_symlink

### ISSUE THREAD

**Issue by jaraco** [python/cpython#119588]
In jaraco/zipp#117, I learned that the current implementation of `is_symlink` might have a security risk if a user is relying on it to ensure that a zipfile has no symlinks before using another tool to extract it.

zipp 3.19.0 adds an implementation for `Path.is_symlink` to alleviate this risk.

CPython should adopt this change as well, possibly as a security fix.

### Linked PRs
* gh-119591
* gh-119985
* gh-119988
* gh-120043
* gh-120046

**Comment by jaraco** [comment]
The `is_symlink` was added in Python 3.12 (#102018) (note the backports of that PR only included one bugfix), so this change can be backported to Python 3.12 as a bugfix (no need to flag as a security fix).

**Comment by hugovk** [comment]
Triage: closing because the PR has been merged, please re-open if still needed. Thanks!
