### ISSUE TITLE
Remove ```asyncio``` deprecated objects and methods

### ISSUE THREAD

**Issue by SweetyAngel** [python/cpython#119627]
# Feature or enhancement

### Proposal:

There were deprecation warnings on asyncio ChildWatchers and methods, they are connected to. Now they are removed.

### Has this already been discussed elsewhere?

No response given

**Comment by kumaraditya303** [comment]
This is not so straightforward, the subprocesses needs to be reimplemented without watchers before removing it. That has to be done carefully, the code is fragile.

**Comment by SweetyAngel** [comment]
>  the subprocesses needs to be reimplemented without watchers before removing it

I want to get a small advice about will it be enough to keep only one, standart ChildWatcher?

**Comment by gvanrossum** [comment]
FWIW Previous discussions are at gh-94597 and gh-82772. IIRC the intention was to remove all *APIs* for getting/setting child watchers, but to leave one or more *implementations* as an internal detail.

I think that implementation could either be `ThreadedChildWatcher` or it could be a choice between `ThreadedChildWatcher` and `PidfdChildWatcher` depending on the platform (the latter on Linux, the former on all other UNIX systems). The current code uses that:
```
    def _init_watcher(self):
        with events._lock:
            if self._watcher is None:  # pragma: no branch
                if can_use_pidfd():
                    self._watcher = PidfdChildWatcher()
                else:
                    self._watcher = ThreadedChildWatcher()
```
Perhaps we can keep this approach for now, and just remove the deprecated watcher classes? (`BaseChildWatcher` and its subclasses, `SafeChildWatcher`, `FastChildWatcher` and `MultiLoopChildWatcher`.)

**Comment by kumaraditya303** [comment]
@SweetyAngel Would you like to continue work on this as Guido suggested? If not I'll take over and do it.

**Comment by SweetyAngel** [comment]
I ve already done it but i need to move it on new branch

**Comment by kumaraditya303** [comment]
I forgot actually I already have code for this, in a old branch, I'll resolve it and get it done faster. it will also include rewrite on child watchers.

**Comment by kumaraditya303** [comment]
I am creating a new issue for this with much smaller items to work with.
