### ISSUE TITLE
Build failure due to missing _Py_SINGLETON in static-extension-modules build (3.13 only)

### ISSUE THREAD

**Issue by kpfleming** [python/cpython#119661]
# Bug report

### Bug description:

While attempting to upgrade [python-build-standalone](https://github.com/indygreg/python-build-standalone/pull/264) to support Python 3.13 beta releases, we've run into a build failure which may be caused by Argument Clinic failing to ensure that all necessary `#include` directives are emitted into the source files it generates.

The failure can be seen [here](https://github.com/kpfleming/python-build-standalone/actions/runs/9149133735/job/25152446034#step:7:36777). Granted this is a very unusual way to build CPython, but given some of the discussions at the recent Packaging Summit it may become more valuable soon :-)

It was suggested that @vstinner might have the knowledge needed to understand what is happening here, so apologies in advance for the direct ping :-)

I'm happy to include patches into that build tree to see if we can overcome the problem before the next beta release, and I'm also happy to make that branch writable by others who want to try to help troubleshoot.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-119712
* gh-119716

**Comment by vstinner** [comment]
Can you attach generated Modules/clinic/_curses_panel.c.h file?

**Comment by vstinner** [comment]
Build command:

```
cpython-3.13> /usr/bin/aarch64-linux-gnu-gcc  -I/tools/deps/include/ncursesw -fno-strict-overflow -Wsign-compare -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -g -Og -Wall -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw   -std=c11 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -fvisibility=hidden  -I./Include/internal -I./Include/internal/mimalloc  -I. -I./Include -fPIC -I/tools/deps/include -I/tools/deps/include/ncursesw  -fPIC -DHAVE_NCURSESW=1 -DPy_BUILD_CORE_BUILTIN -c ./Modules/_curses_panel.c -o Modules/_curses_panel.o
```

**Comment by kpfleming** [comment]
We're building from the 3.13.0b1 tarball downloaded from python.org, which has that file (and presumably all of the other 'clinic' files) already generated and present in `Modules/clinic`.

**Comment by vstinner** [comment]
I wrote PR gh-119712 to add an explicit include to get the _Py_SINGLETON() macro. You can see that the PR changes Modules/clinic/_curses_panel.c.h to add:

```c
#if defined(Py_BUILD_CORE) && !defined(Py_BUILD_CORE_MODULE)
#  include "pycore_runtime.h"     // _Py_SINGLETON()
#endif
```

**Comment by kpfleming** [comment]
Thank you! We'll apply a local patch to do the same and see if we can get the build continue; there may be other files in the `clinic` directory with a similar issue.
