### ISSUE TITLE
Windows installer missing free-threading library

### ISSUE THREAD

**Issue by da-woods** [python/cpython#119679]
# Bug report

### Bug description:

Tested with Python 3.13b1 release.

I've been trying to help someone test a simple extension module with the free-threading interpreter on Windows, which ultimately failed because it was missing `python313t.lib` so was unable to link.

![image](https://github.com/python/cpython/assets/10536947/90602765-e9af-4c53-9dcd-f0b6e5727aad)

![image](https://github.com/python/cpython/assets/10536947/5961bdc6-bbfa-4b02-9367-0a7e1a0be4de)

Installed libraries:

![image](https://github.com/python/cpython/assets/10536947/3a3dc16e-928a-4563-948b-69508d4f136e)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-119790
* gh-119983
* gh-120133
* gh-120160

**Comment by zooba** [comment]
That's actually a shockingly short list of libs in there... do you have log files handy? They'll be under `%TEMP%\Python*.log`, and the main one I'm interested in will end with `dev` (and probably be the latest date, in case you have multiple installs).

**Comment by da-woods** [comment]
[Python 3.13.0b1 (64-bit)_20240528190955_004_dev_JustForMe.log](https://github.com/python/cpython/files/15474749/Python.3.13.0b1.64-bit._20240528190955_004_dev_JustForMe.log)

Here. Can provide other logs as needed.

I only have one install of 3.13 - I uninstalled and started from scratch for the sake of this issue.

**Comment by zooba** [comment]
Huh, no, it just looks like we've only ever shipped that few. I guess I'm so used to working with the Nuget packages that I had forgotten the MSI is more selective.

We should add the free-threaded libs to the old installer. We should also reduce the libs included in the other packages to avoid shipping too many files.

**Comment by stonebig** [comment]
I'm afraid to dicsover it didn't make it to b2.... by any luck am I wrong ?

**Comment by zooba** [comment]
It should be fixed in b2 - the later fix is for scripts that aren't part of the release, so shouldn't make a difference.

If you're doing a clean install and not seeing the files, please grab your log files and attach those as well.
