### ISSUE TITLE
Remove deprecated `code.co_lnotab`

### ISSUE THREAD

**Issue by picnixz** [python/cpython#119664]
# Feature or enhancement

### Proposal:

This is an issue to track the removal of ``code.co_lnotab`` deprecated since 3.12 and scheduled for removal in 3.14.

In https://github.com/python/cpython/issues/101865, it is marked "may be removed" but I think it should be removed. If not, we should harmonize the docs which sometimes state "will be removed" and sometimes say "may be removed" (also the corresponding tests are marked as "todo: remove in 3.14").

### Has this already been discussed elsewhere?

No, so we can discuss here whether we should remove it now or not.

### Links to previous discussion of this feature:

https://github.com/python/cpython/issues/101865

### Linked PRs
* gh-119665
* gh-120263

**Comment by iritkatriel** [comment]
> In #101865, it is marked "may be removed" but I think it should be removed.

What is the reason for removing it?

> ### Has this already been discussed elsewhere?
> This is a minor feature, which does not need previous discussion elsewhere

For someone who uses it and will be required to change their code this is not minor. We don't always remove things just because we can, if they are not getting in anyone's way. I think this decision needs to be discussed.

**Comment by picnixz** [comment]
Oh it was actually scheduled for removal in Python 3.14 (deprecated in 3.12). Actually, it was scheduled for removal for 3.12 but since no DeprecationWarning was set in 3.10, it got delayed (see https://peps.python.org/pep-0626/#backwards-compatibility).

**Comment by markshannon** [comment]
I don't see any need to remove this just yet.

We will probably need to remove it at some point, in order to change the internal format of the position table, but we might as well leave until then.

**Comment by picnixz** [comment]
Then would you consider the rewording of the removal notice as presented in #120263?

**Comment by picnixz** [comment]
(Closing as `wontfix` since I actually closed the PRs)
