### ISSUE TITLE
classmethod wrapping a property no longer works in Python 3.13

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#119628]
# Bug report

### Bug description:

In Python 3.12 and below, wrapping a `property` object with the `classmethod` decorator would result in a descriptor object that would act like a class-level property.

Here is the code to check this:

```python
class A:
    @classmethod
    @property
    def b(self):
        return 4

print(f"{A.b = }")
```

On Python 3.12 this prints `4`.

On Python 3.13 this currently prints `<bound method b of <class '__main__.A'>>`.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Probably related: #89519

**Comment by serhiy-storchaka** [comment]
This feature was deprecated in 3.11 and removed in 3.13.
