### ISSUE TITLE
Deprecate Py_IS_NAN/INFINITY/FINITE?

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#119613]
# Feature or enhancement

### Proposal:

isnan(), isinf() and isfinite() are part of C99, which is a requirement for 3.11+.  Probably, it does make sense to deprecate (undocumented) public macros and switch codebase to use C stdlib functions.

JFR: https://github.com/python/cpython/pull/119457#discussion_r1615985599

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-119619
* gh-119701
* gh-120020

**Comment by skirpichev** [comment]
CC @vstinner as author of 194a9526d8

I'll work on a patch.

**Comment by skirpichev** [comment]
First part: https://github.com/python/cpython/pull/119619

**Comment by vstinner** [comment]
> isnan(), isinf() and isfinite() are part of C99, which is a requirement for 3.11+. Probably, it does make sense to deprecate (undocumented) public macros and switch codebase to use C stdlib functions.

A code search on PyPI top 7,500 projects found 10 projects using these macros:

* Nuitka (2.1.2)
* aim (3.19.1)
* fastcluster (1.2.6)
* gmpy2 (2.1.5)
* msgspec (0.18.6)
* numba (0.59.0)
* pandas (2.2.1)
* python-rapidjson (1.16)
* simplejson (3.19.2)
* vowpalwabbit (9.9.0)

I suggest to update all of these projects before considering to deprecate these macros.

I would be fine with a **soft** deprecation. It's the kind of the issue which fall into [PEP 743 – Add Py_COMPAT_API_VERSION to the Python C API](https://peps.python.org/pep-0743/) territory: having a way to opt-out from deprecated macros, without forcing all projects to update their code.

**Comment by skirpichev** [comment]
@vstinner, these macroses were undocumented.  Should we (1) document them (with "deprecated" statement) and (2) add news entry?  Or (2) is enough?

> I would be fine with a soft deprecation.

If we don't announce removal (e.g. deprecated-removed statement) wouldn't this be a soft deprecation?

-------------

- [ ] Nuitka (2.1.2)
- [ ] aim (3.19.1)
- [ ] fastcluster (1.2.6)
- [x] gmpy2 (2.1.5) // https://github.com/aleaxit/gmpy/pull/485
- [ ] msgspec (0.18.6)
- [ ] numba (0.59.0)
- [ ] pandas (2.2.1)
- [ ] python-rapidjson (1.16)
- [ ] simplejson (3.19.2)
- [ ] vowpalwabbit (9.9.0)

**Comment by skirpichev** [comment]
Maybe this could go to 3.13?

**Comment by skirpichev** [comment]
Ok, last part: #119701
