### ISSUE TITLE
Add `--single-process` option to regrtest to always run tests sequentially (ignore `-jN` option)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#119727]
The Python release process runs tests sequentially. It catchs some issues which are ignored silently when running tests in parallel.

I propose adding `--sequentially` option to regrtest to always run tests sequentially. It can be used to ignore any `-jN` option and also to re-run failed tests sequentially.

### Linked PRs
* gh-119728
* gh-120456
* gh-123010
* gh-130359

**Comment by vstinner** [comment]
My motivation for this change is also a desire to change the regrtest default to -j0: run tests in parallel using the number of CPU.

**Comment by serhiy-storchaka** [comment]
This is an opposite of `--multiprocess`. Why not call it `--singleprocess`?

You can run tests with `-j1`, it will be sequentially, but in different processes.

**Comment by vstinner** [comment]
IMO "sequentially" is the right name. ``--multiprocess`` means in fact "running tests in parallel". Using multipe processes is just an implementation details. It could be threads or something else. The opposite of parallel is sequential. IMO it's too late to rename the `--multiprocess` option.

Note: there is already a ``--single`` option. ``--singleprocess`` sounds too close.

**Comment by serhiy-storchaka** [comment]
I will not insist.

The `--multiprocess` option has two effects: it runs the tests in parallel and runs every test is a separate process. It could be possible to run the tests in parallel using the process pull, but this is not how it is implemented now, and I do not think there is a benefit to implement such option. Currently there are three options:

* Run the tests sequentially in the same (main) process. By default.
* Run the tests sequentially in separate processes. `-j1`.
* Run the tests in parallel in separate processes. `-jN`.

**Comment by vstinner** [comment]
Implemented by change https://github.com/python/cpython/commit/4e8aa32245e2d72bf558b711ccdbcee594347615.
