### ISSUE TITLE
eval path in fileConfig from logging does not format properly Windows path

### ISSUE THREAD

**Issue by francescomandruvs** [python/cpython#119784]
I want to log into file using fileConfig and my lconfiguration file. I provide a simple example of how to reproduce my output (I'm using Python 3.11.9). 

```python
import logging.config

logging.config.fileConfig("path_of_your_logging.conf", defaults={"logpath": "C:\\Users\\{yourusename}\\example.log"})
logger = logging.getLogger(__name__)
logger.error("hi")
```

And this is my `logging.conf` file

```conf
[loggers]
keys=root

[handlers]
keys=consoleHandler,fileHandler

[formatters]
keys=simpleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler,fileHandler

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=simpleFormatter
args=(sys.stdout,)

[handler_fileHandler]
class=FileHandler
level=DEBUG
formatter=simpleFormatter
args=("%(logpath)s",)

[formatter_simpleFormatter]
format=%(asctime)s - %(name)s - %(levelname)s - %(message)s
```
The error that I get is the following (inside the fileConfig function):

```python
    args = eval(args, vars(logging))
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1
    ("C:\Users\{yourusename}\example.log",)
                                            ^
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape
```

The same code works on Unix and the way the I have found in order to make it work even with Windows is to parse my path with this function 

```python
def format_path(path):
    if os.name == 'nt':  # Windows requires escaping backslashes
        return str(path).replace('\\', '\\\\')
    else:
        return str(path)
```

I'm pretty sure there is a better way and maybe this is not a bug, however I don't find how to solve differently my issue.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
You could use forward slashes `"C:/Users/{yourusename}/example.log"`, or use a raw string `r"C:\\Users\\{yourusename}\\example.log"`, or even `"C:\\\\Users\\\\{yourusename}\\\\example.log"` I think should work (haven't tried it).

The documentation does mention that "args' is eval-ed, so this is the expected behavior. I'm going to close this. Please ask for further help at https://discuss.python.org/c/users/7
