### ISSUE TITLE
`io.IOBase` internal methods difference in `_pyio.py`

### ISSUE THREAD

**Issue by aminalaee** [python/cpython#119723]
# Bug report

### Bug description:

There are a few internal methods in the `io.IOBase` which accept no arguemnts in C implementation but the `_pyio.py` method can accept `msg` argument. Is this possible or worth it to fix this in the `_pyio.py` so they have the same signature?
I came across this in `typeshed` where the `msg` argument was optional, but the implementation didn't accept it.

https://github.com/python/cpython/blob/055c739536ad63b55ad7cd0b91ccacc33064fe11/Modules/_io/iobase.c#L835-L839

https://github.com/python/cpython/blob/055c739536ad63b55ad7cd0b91ccacc33064fe11/Lib/_pyio.py#L473
https://github.com/python/cpython/blob/055c739536ad63b55ad7cd0b91ccacc33064fe11/Lib/_pyio.py#L444

### CPython versions tested on:

CPython main branch

**Comment by zware** [comment]
These are internal implementation details that should never affect any user, they are not required to match between implementations.  In my view, it's a bug for `typeshed` to include `IOBase._checkClosed`; it already doesn't include the other private methods.
