### ISSUE TITLE
Add a "strict" option for map()

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#119793]
These two examples silently truncate the unmatched inputs:

```python
>>> list(map(pow, [1, 2, 3], [2, 2, 2, 2]))
[1, 4, 9]
>>> list(map(pow, [1, 2, 3, 4, 5], [2, 2, 2, 2]))
[1, 4, 9, 16]
```

The current workaround is:

```
starmap(pow, zip(vec1, vec2, strict=True))
```

Ideally, map() should support this directly.  The reasoning is the same reasoning that motivated the `strict` option for `zip()`

### Linked PRs
* gh-120471
* gh-126407

**Comment by brandtbucher** [comment]
PEP 618 [says](https://peps.python.org/pep-0618/#add-a-similar-feature-to-map):

> This PEP does not propose any changes to `map`, since the use of `map` with multiple iterable arguments is quite rare. However, this PEP’s ruling shall serve as precedent such a future discussion (should it occur).
>
> If rejected, the feature is realistically not worth pursuing. If accepted, such a change to `map` should not require its own PEP (though, like all enhancements, its usefulness should be carefully considered). For consistency, it should follow same API and semantics debated here for `zip`.

I'm +1 on the change, personally. Unassigning myself though since I don't have bandwidth to work on it right now (it seems like a good issue for someone newer looking to contribute some C code).

**Comment by SweetyAngel** [comment]
I want to implement it, but I cant find the definition of ```map``` object. Can you tell me please where it is located?

**Comment by zware** [comment]
See https://github.com/python/cpython/blob/bf098d4157158e1e4b2ea78aba4ac82d72e24cff/Python/bltinmodule.c#L1300-L1527

**Comment by brandtbucher** [comment]
The implementation *should* be almost identical to the implementation for `zip`, which is nice:

https://github.com/python/cpython/pull/20921/files#diff-e4fd8b8ee6a147f86c0719ff122aca6dfca36edbd4812c87892698b3b72e40a1

**Comment by nineteendo** [comment]
Brandt, should I credit you for the code I based my patch on?

**Comment by cool-RR** [comment]
Hey, I'm the guy who originally suggested `strict` for `zip`. I was just using `map` and wanting the same feature there, which prompted me to find this issue. I too am +1 on implementing it. If you do implement it, I'll be happy to write the documentation.

**Comment by nineteendo** [comment]
That would be much appreciated, although encukou doesn't think an example is necessary.

**Comment by cool-RR** [comment]
I see the documentation now, I agree an example isn't required. Good job.

**Comment by dg-pb** [comment]
This closes doors to another extension - adding keyword arguments to `map`.

Maybe it would be worth considering both at the same time and finding out what would be "joint optimum" to have good 7 convenient solutions to both?:
a) `map(func, arg1, arg2, c=arg3)`.
b) `map(func, arg1, arg2, strict=True)`.

What about achieving `map(func, arg1, arg2, c=arg3, strict=True)`?

Of course, one can always convert `func` into positional only version for this, but I expect performance penalty for doing so is going to be much large than performance benefit of `map(..., strict)` vs `startmap(..., zip(..., strict))`

**Comment by nineteendo** [comment]
In what case would you not want to supply the same keyword value for all calls though (e.g. using partial)? The benefit for having `strict=True` is generally useful and I would use it every time I call map with more than 1 iterable.

**Comment by encukou** [comment]
[The PR](https://github.com/python/cpython/pull/120471) is up for a final round of reviews.

**Comment by encukou** [comment]
Merged! Thank you @nineteendo for your work and patience, and thanks to all the reviewers who chimed in.

**Comment by cool-RR** [comment]
Congratulations @nineteendo , @encukou  and all reviewers for delivering this feature! I can't wait to use it.

**Comment by terryjreedy** [comment]
The open doc followup issue looks like a no-brainer, but needs review and verification.

**Comment by vstinner** [comment]
> The open doc followup issue looks like a no-brainer, but needs review and verification.

I merged the doc PR.
