### ISSUE TITLE
``test_ioctl`` fails on macOS

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#119770]
# Bug report

### Bug description:

```python
./python.exe -m test -v test_ioctl
== CPython 3.14.0a0 (heads/main:a5fef800d3, May 30 2024, 09:48:26) [Clang 15.0.0 (clang-1500.3.9.4)]
== macOS-14.5-arm64-arm-64bit-Mach-O little-endian
== Python build: debug
== cwd: /Users/admin/Projects/cpython/build/test_python_worker_4187æ
== CPU count: 8
== encodings: locale=UTF-8 FS=utf-8
== resources: all test resources are disabled, use -u option to unskip tests

Using random seed: 2309191984
0:00:00 load avg: 63.19 Run 1 test sequentially
0:00:00 load avg: 63.19 [1/1] test_ioctl
test_ioctl (test.test_ioctl.IoctlTests.test_ioctl) ... ok
test_ioctl_mutate (test.test_ioctl.IoctlTests.test_ioctl_mutate) ... ok
test_ioctl_mutate_1024 (test.test_ioctl.IoctlTests.test_ioctl_mutate_1024) ... ok
test_ioctl_mutate_2048 (test.test_ioctl.IoctlTests.test_ioctl_mutate_2048) ... ok
test_ioctl_signed_unsigned_code_param (test.test_ioctl.IoctlTests.test_ioctl_signed_unsigned_code_param) ... ERROR

======================================================================
ERROR: test_ioctl_signed_unsigned_code_param (test.test_ioctl.IoctlTests.test_ioctl_signed_unsigned_code_param)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/test/test_ioctl.py", line 85, in test_ioctl_signed_unsigned_code_param
    new_winsz = fcntl.ioctl(mfd, set_winsz_opcode_maybe_neg, our_winsz)
OSError: [Errno 25] Inappropriate ioctl for device

----------------------------------------------------------------------
Ran 5 tests in 0.003s

FAILED (errors=1)
test test_ioctl failed
test_ioctl failed (1 error)

== Tests result: FAILURE ==

1 test failed:
    test_ioctl

Total duration: 96 ms
Total tests: run=5
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-119818
* gh-119840
* gh-119862
* gh-119863

**Comment by Eclips4** [comment]
Unfortunately, this commit breaks backward compatibility. Previously, it was allowed to pass negative values for the `request` parameter and then they were converted to positive values. However, now, due to a change in the type from unsigned int to unsigned long, this is not working.

**Comment by vstinner** [comment]
This test is strange. Why passing negative request if its type is unsigned long? The value should be positive.

test_ioctl was skipped until recently. I fixed regrtest to test it: https://github.com/python/cpython/pull/119275

**Comment by Eclips4** [comment]
> This test is strange. Why passing negative request if its type is unsigned long? The value should be positive.
> 
> test_ioctl was always skipped until recently. I fixed regrtest to test it: #119275

Yes, I agree with you that this is strange. Our documentation does not mention that the `ioctl` request parameter can be negative. I think this test was broken by design.

**Comment by vstinner** [comment]
> Is there any chance that TIOCSWINSZ can be negative?

darwin-xnu uses uint32_t with the MSB bit set:

```c
#define IOC_IN          (__uint32_t)0x80000000
#define _IOC(inout, group, num, len) \
	(inout | ((len & IOCPARM_MASK) << 16) | ((group) << 8) | (num))
#define _IOW(g, n, t)     _IOC(IOC_IN,	(g), (n), sizeof(t))
#define TIOCSWINSZ      _IOW('t', 103, struct winsize)  /* set window size */
```

Source:
* https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/sys/ioccom.h#L85-L95
* https://github.com/apple/darwin-xnu/blob/2ff845c2e033bd0ff64b5b6aa6063a1f8f65aa32/bsd/sys/ttycom.h#L154

Python termios module stores the constant as `long` in `termios_constants` array, and then create an object using PyLong_FromLong()`.

The value may be negative or not depending on how C treats the integers. I would prefer to have a more reliable value.

**Comment by vstinner** [comment]
I wrote PR gh-119840 to make termios ioctl() constants positive and to update test_ioctl.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/64ff1e217d963b48140326e8b63c62f4b306f4a0
