### ISSUE TITLE
Document typing.NamedTupleMeta

### ISSUE THREAD

**Issue by Gouvernathor** [python/cpython#119782]
typing.NamedTuple doesn't support using a metaclass, or multiple inheritance with classes having metaclasses (such as abc.ABC(Meta)), because NamedTuple uses an undocumented metaclass underhand.
That limitation is not documented.
Since NamedTuple is a function and not a real instance of that metaclass, it's impossible to make your own subclass of both `type(NamedTuple)` (which is really `function`) and `abc.ABCMeta` in my case.

It is possible to use collections.namedtuple instead, but the syntax is obviously not as good and involves repetitions, names being put under quotes, and so on.

Using the undocumented `typing.NamedTupleMeta` metaclass, it is possible to solve the issue. So, I think the NamedTupleMeta should be documented for that use case.

One difference with ABC/ABCMeta is that using ABCMeta _replaces_ the use of ABC, whereas you apparently still need to have NamedTuple as a "base class" (even though it's not a class) when using NamedTupleMeta or a submetaclass.
I think this specificity should be explained (and possibly lifted at a later time if relevant), but that it's not blocking the feature from being relied upon and documented.

See https://discuss.python.org/t/abstract-base-namedtuple/54522
No previous discussion of that metaclass has been found on the Discourse, and it seems small enough not to be opened there.

**Comment by sobolevn** [comment]
Even if you use `NamedTupleMeta` directly in this case you will get:

```python
>>> import abc, typing
>>> NamedABC = type("NamedABC", (abc.ABCMeta, typing.NamedTupleMeta), {})
>>> class TupleAndABC(typing.NamedTuple, abc.ABC, metaclass=NamedABC):
...     ...

    Traceback (most recent call last):
        cls = super().__new__(mcls, name, bases, namespace, **kwargs)
        raise TypeError(
            'can only inherit from a NamedTuple type and Generic')
    TypeError: can only inherit from a NamedTuple type and Generic
```

Link: https://github.com/python/cpython/blob/3859e09e3d92d004978dd838f0511364e7edfb94/Lib/typing.py#L2968-L2971

I don't think that current `NamedTupleMeta` is useful because of this check. And I don't think that your initial example is valid.

So, is there really a point to expose and document this implementation detail?

**Comment by Gouvernathor** [comment]
No, there isn't. typing.NamedTuple would gain from being elevated to the same features that collections.namedtuple supports, but that's not a documentation issue.
