### ISSUE TITLE
isascii() method giving false for emojis but ord() function to find ascii values is giving ascii values. Update isascii() with new ascii list too

### ISSUE THREAD

**Issue by gvjahnavi23** [python/cpython#119718]
# Bug report

### Bug description:

isascii() method giving false for emojis but ord() function to find ascii values is giving ascii values. Update isascii() with new ascii list too
```
txt = "🤗"
x = txt.isascii()
y = ord(txt)
print(f"{txt} is ascii:{x}\n The ascii value is {y}")
```
**output**
🤗 is ascii:False
 The ascii value is 129303

### CPython versions tested on:

3.8, 3.11

### Operating systems tested on:

Windows

**Comment by graingert** [comment]
ord is documented as:

> Given a string representing one Unicode character, return an integer representing the Unicode code point of that character. For example, ord('a') returns the integer 97 and ord('€') (Euro sign) returns 8364. This is the inverse of [chr()](https://docs.python.org/3/library/functions.html#chr).

So the number returned doesn't have to be ascii.

**Comment by gvjahnavi23** [comment]
@graingert Thank you

**Comment by terryjreedy** [comment]
Please ask about behavior you do not understand on https://discuss.python.org/c/users/7.
