### ISSUE TITLE
Syntax errors in `else` blocks are reported at `else`

### ISSUE THREAD

**Issue by encukou** [python/cpython#119724]
Since #29513, syntax errors in `else` and `elif` blocks, like:
```python
if 1:
    pass
else:
    This is invalid syntax (sic)
```
are reported at the `else`:
```
  File "/tmp/repro.py", line 3
    else:
    ^^^^^^
SyntaxError: 'else' must match a valid statement here
```
This is quite unhelpful when a small typo is hiding in a large block.

@lysnikolaou, could you take a look?

### Linked PRs
* gh-119974
* gh-120013

**Comment by encukou** [comment]
@lysnikolaou Do you think this can be solved soon?

Beta 2 is coming up; if this can't be fixed quickly it might be better to revert #29513 and try again.

**Comment by lysnikolaou** [comment]
I gave this a go yesterday, but I couldn't come up with something that both fixes this and keeps the current behavior when there's an unmatched `else`/`elif`. I'll give another try later and report back.

**Comment by erlend-aasland** [comment]
Would you consider this an improvement?

```python
Python 3.14.0a0 (heads/autoconf/curses-dirty:739af749138, Jun  3 2024, 13:59:59) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> if 1:
...     pass
... else:
...     This is invalid syntax (sic)
  File "<unknown>", line 4
    This is invalid syntax (sic)
                                ^
SyntaxError: 'else' must match a valid statement here
>>> 
```

**Comment by encukou** [comment]
Hard to say with that example. Here is a less minimal one; IMO the error should be “near” the bad line:
```py
if 1:
    pass
else:
    while True:
        do_necessary_things()
        if should_end:
            retrun True  # sic
        do_correct_things()
        do_good_things()

```

**Comment by erlend-aasland** [comment]
In this case, yes it shows the offending line, but not the exact column.

**Comment by pablogsal** [comment]
Yeah, I think the correct thing to do here is reverting

**Comment by lysnikolaou** [comment]
I couldn't make it work well. Let's revert and reevaluate.

**Comment by pablogsal** [comment]
yeah, the ratio benefit/complexity it's quite important for these error messages and I prefer to have something dummer than showing incorrect things to the user or having to maintain some gigantic rule so it's fine to just not do it
