### ISSUE TITLE
Fix link in Python 3 porting 

### ISSUE THREAD

**Issue by findurance** [python/cpython#119779]
# Documentation

https://docs.python.org/3.12/howto/pyporting.html

`"You can find the old guide in the [archive](https://docs.python.org/3.12/howto/pyporting.html)."` 

Link points to the page itself, not to the actual archive.

### Linked PRs
* gh-119785
* gh-119788
* gh-119789

**Comment by hugovk** [comment]
Thanks for the report, we should change the link to https://docs.python.org/3.10/howto/pyporting.html and the text from "Since Python 3.13" to "Since Python 3.11".

Would you like to open a pull request to fix this?
