### ISSUE TITLE
Add asyncio.TaskGroup.ensure_future analogous to asyncio.ensure_future

### ISSUE THREAD

**Issue by germaniuss** [python/cpython#119742]
# Feature or enhancement

### Proposal:

Currently task groups support the `TaskGroup.create_task` function with the same interface as `asyncio.create_task`, it would be very useful to add a `TaskGroup.ensure_future` similar to `asyncio.ensure_future`. This would allow code that uses low level interfaces that return a future to use the new TaskGroup code, it would also enable code that returns an asyncio compatible Future-like object to be used with task groups.

The alternative is to create a coroutine that awaits the future and then use create_task with it, but that is a bit annoying and I believe there should be a builtin way to do this.

```python
...
def custom_future_function():
   return CustomCompatibleFuture()
...
async with asyncio.TaskGroup() as tg:
    tg.ensure_future(loop.run_in_executor(...))
    tg.ensure_future(custom_future_function())
...
```

### Has this already been discussed elsewhere?

No response given

**Comment by gvanrossum** [comment]
Interesting idea. Should the task group wait for such futures to complete in its exit handler?

**Comment by germaniuss** [comment]
It could be done by waiting for the futures in the exit handler. However, I don't think changing the exit handler is the approach I would take, instead Task could be modified to be able to wrap a future. If a Task is initialized with a future, setting eager_start to true would raise a RuntimeError, then all calls to methods inherited from Future would call those methods in the wrapped future object. Not sure how would the uncancel and cancelling method behave in that situation, but I'm sure it can be figured out.

**Comment by gvanrossum** [comment]
Sounds like the simpler solution for sure would be to do what you first suggested — just create a task with a coroutine that awaits the future. How often have you needed this feature? Would it really save you more than a line or two of code?

**Comment by germaniuss** [comment]
To be honest, not that often, but it would definitely be a nice addition for the times I have needed it. Really even making TaskGroup.ensure_future just create a coroutine would already be nice and simple enough to add.
I just didn't really like the extra layer of wrapping what is already a future in a coroutine that is then wrapped in a future that is the task.

**Comment by germaniuss** [comment]
Really I'm not even sure that wrapping a future in a task would be necessary since tasks are already futures and maybe it just works.

**Comment by germaniuss** [comment]
Just tested adding this to TaskGroup and can confirm that it just works and is much simpler than I thought. It's just create_task but removing actually creating the task and just using the future.
```python
def ensure_future(self, future):
        if not self._entered:
            raise RuntimeError(f"TaskGroup {self!r} has not been entered")
        if self._exiting and not self._tasks:
            raise RuntimeError(f"TaskGroup {self!r} is finished")
        if self._aborting:
            raise RuntimeError(f"TaskGroup {self!r} is shutting down")
        task = future
        if task.done():
            self._on_task_done(task)
        else:
            self._tasks.add(task)
            task.add_done_callback(self._on_task_done)
        return task
```

**Comment by gvanrossum** [comment]
Wait, that's not what `ensure_future()` currently does -- it would be confusing to have different semantics.

**Comment by kumaraditya303** [comment]
Yeah, ensure future is kinda low level stuff, hence create_task was added. I would suggest you just create a wrapper and await it.

**Comment by nineteendo** [comment]
Should we close this?

**Comment by germaniuss** [comment]
I'll leave that up to you, this would be a nice feature but there is an easy workaround

**Comment by nineteendo** [comment]
I would close it, your proposed behaviour is confusing and there are already more than enough issues on the tracker.
I'm trying to help bring that number down.
