### ISSUE TITLE
Please implement goto

### ISSUE THREAD

**Issue by Sur3** [python/cpython#119706]
# Feature or enhancement

### Proposal:

I really like the python programming language, but now that I am debugging a large program I am missing a goto statement to jump to specific lines of code for individual runs instead of commenting hundreds of lines out. Debugging with goto would be just a label and a goto statement and I could move the label to where I want it to be, these are only two lines of code changed instead of having to comment out hundreds of lines of code before what should be executed for the debugging purpose. The missing goto statement makes debugging code in python very inconvenient. Please implement it.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by Eclips4** [comment]
Hello!
Please, create a topic on https://discus.python.org/c/ideas/6 if you would like to discuss this feature.
Honestly, there's a very little chance that this will get implemented.
Also, we have a with statement in python which is really useful for resource-deallocation process.

**Comment by Eclips4** [comment]
Also is sounds like you need a debugging tool, not a goto statement.

**Comment by Sur3** [comment]
Ok thanks your pointer to the with statement was correct, I found https://github.com/snoack/python-goto which is using the with statement. It would be more convenient if this was in the main interpreter, but this addon also works for me for now.
