### ISSUE TITLE
Honor PyOS_InputHook in the new REPL

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#119842]
# Bug report

We are currently not calling `PyOS_InputHook` if is set before blocking for input in the new REPL

### Linked PRs
* gh-119843
* gh-120066

**Comment by mdboom** [comment]
Here's a good reproducer to ensure your changes are working (on Linux):

(`make install` is required to get `pkgconfig` working for all the dependencies).

```
pip install git+https://github.com/python-pillow/Pillow@d879f39
pip install matplotlib

$ python
>>> import matplotlib
>>> matplotlib.use("tkagg")
>>> from matplotlib import pyplot as plt
>>> plt.plot([1,2], [3,4])
[<matplotlib.lines.Line2D object at 0x7fd3f2be8050>]
>>> plt.show(block=False)
>>>
```

If working, a window should appear with a plot in it, and it should respond to mouse events etc.  It seems that on CPython main, this is broken, but works with `PYTHON_BASIC_REPL=1` set.

**Comment by mdboom** [comment]
Here's a much easier reproducer with no external dependencies:

```
from tkinter import *
root = Tk()
w = Label(root, text='Foo')
w.pack()
```

Current behavior I'm seeing:

CPython main: No window
CPython main / PYTHON_BASIC_REPL=1: Window is displayed, updated automatically with each line of entry (matches 3.12)
#119843: ` Fatal Python error: _PyThreadState_Attach: non-NULL old thread state`
#119843 / PYTHON_BASIC_REPL=1: Window is displayed, updated automatically with each line of entry (matches 3.12)

**Comment by tacaswell** [comment]
@mdboom Correct.  PyQt, wxpython, and the gtk bindings all provide their own verision of `PyOS_InputHook` as well and mpl provides one for macOSX. 

To be 100% sure the event loop is running as expected also add a "print on click" callback:

```python
from tkinter import *
root = Tk()
b = Button(root, text='bar', command=lambda: print('bob'))
w = Label(root, text='Foo')
b.pack()
w.pack()
```
