### ISSUE TITLE
Spill the stack pointer across calls in the interpreter.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#119866]
For performance we keep the stack pointer in a register, however this means that the stack pointer is invisible to debuggers and other tools. If we spill the stack pointer across "escaping" calls, then most of the time we want to inspect the evaluation the stack pointer should be in memory.
Spilling the stack pointer is also a necessary precursor to deferred reference counting: https://github.com/faster-cpython/ideas/issues/677, https://github.com/python/cpython/issues/117139, as it means there is no need to redundantly set the unused part of the stack to `NULL`.

Since the C compiler needs to spill values around calls, manually spilling the stack pointer has quite a low cost. It limits the freedom of the C compiler to allocate registers, but not that much.

### Linked PRs
* gh-119875
* gh-124392
* gh-131750

**Comment by Renatoff67** [comment]
# Exemplo de base de dados de usuários
usuarios = {
    "123": {"nome": "Alice", "senha": "alice123"},
    "456": {"nome": "Bob", "senha": "bob456"},
    "789": {"nome": "Charlie", "senha": "charlie789"}
}

# Função para buscar e exibir as informações do usuário
def buscar_usuario():
    id_usuario = id_entry.get()
    if id_usuario in usuarios:
        usuario = usuarios[id_usuario]
        nome_label.config(text=f"Nome: {usuario['nome']}")
        senha_label.config(text=f"Senha: {usuario['senha']}")
    else:
        messagebox.showerror("Erro", "ID não encontrado")
        nome_label.config(text="Nome: ")
        senha_label.config(text="Senha: ")

# Configuração da interface gráfica
root = tk.Tk()
root.title("Buscar Usuário")

frame = tk.Frame(root)
frame.pack(pady=20, padx=20)

id_label = tk.Label(frame, text="ID do Usuário:", font=("Helvetica", 12))
id_label.pack(pady=5)

id_entry = tk.Entry(frame, font=("Helvetica", 12))
id_entry.pack(pady=5)

buscar_btn = tk.Button(frame, text="Buscar", command=buscar_usuario)
buscar_btn.pack(pady=5)

nome_label = tk.Label(frame, text="Nome: ", font=("Helvetica", 12))
nome_label.pack(pady=5)

senha_label = tk.Label(frame, text="Senha: ", font=("Helvetica", 12))
senha_label.pack(pady=5)

root.mainloop()

**Comment by colesbury** [comment]
@markshannon, are you still planning to work on this? If not, I can take a look at it.
