### ISSUE TITLE
`ntpath.abspath()` always return absolute path

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#119826]
# Feature or enhancement

### Proposal:

`ntpath.abspath()` doesn't always return an absolute path:

```python
>>> import ntpath
>>> ntpath.abspath('C:\x00')
'C:\x00' # instead of 'C:\\Users\\wanne\\\x00'
>>> ntpath.abspath('\x00:')
'\x00:' # instead of '\x00:\\'
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #117587

### Linked PRs
* gh-119938
* gh-127534
* gh-127535

**Comment by nineteendo** [comment]
See current changes: https://github.com/python/cpython/compare/main...nineteendo:cpython:fix-ntpath.abspath?expand=1

**Comment by nineteendo** [comment]
cc @barneygale, @eryksun

**Comment by eryksun** [comment]
I'm mostly concerned with fixing `abspath()` on Windows, by (1) using a private `_path_normpath_ex()` function that supports preserving a leading "." component, and (2) fixing the fallback implementation to correctly support drive-relative paths.

The case of `normpath('C:.')` is a bug in the C implementation that can be fixed. The pure Python implementation of `ntpath.normpath()` returns the correct result, "C:". 

Note that no changes are required for the documented behavior and call signature of `normpath()` itself.

@barneygale, `pathlib.PureWindowsPath` was changed in 3.12+ to preserve an explicit leading "." in the case of relative paths that are ambiguous with drive-relative paths, such as ".\\C:spam", but not generally for relative paths, such as ".\\con". Would it possible and reasonable to make `pathlib.PureWindowsPath` always preserve an explicit initial ".", or maybe if there's only one subsequent component?

**Comment by nineteendo** [comment]
I split up the pull request to make it easier to review. Feel free to take a look if you have time.

**Comment by picnixz** [comment]
> The issue should probably be split up in 3:
> 1. `normpath('C:.')`: bug for relative paths
> 2. `abspath('C:\x00')`: always return absolute path
> 3. `abspath('./con')`: support qualified referencing
> The third counts as a feature, but I'm not sure about the first two.

_Originally posted by @nineteendo in https://github.com/python/cpython/issues/119938#issuecomment-2473447515_

Let's address the above points to decide whether this one should be closed as completed or not.

cc @erlend-aasland

**Comment by nineteendo** [comment]
The issue has already been split up, so we should decide whether `abspath()` not always returning an absolute path is a bug.

**Comment by nineteendo** [comment]
@zooba, can this be closed?

**Comment by nineteendo** [comment]
Thanks.
