### ISSUE TITLE
" , " Grammatical confusion!  -----   , 语法的迷惑 !

### ISSUE THREAD

**Issue by zhgna** [python/cpython#119844]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
Python 3.12.3

print('\n  , 运算符 ---------------------------------------- \n')
vint = [0,1,2,3,4,5]
print("# 有 , 号")
vl=len(vint),   # 有 , 号
print(type(vl))
print(vl)
if(isinstance(vl,tuple)):
    print("vl is tuple")
elif(isinstance(vl,int)):
    print("vl is int")
print("# 无 , 号")
vl=len(vint)    # 无 , 号
print(type(vl))
print(vl)
if(isinstance(vl,tuple)):
    print("vl is tuple")
elif(isinstance(vl,int)):
    print("vl is int")

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by zhgna** [comment]
, 运算符 ---------------------------------------- 

# 有,号
<class 'tuple'>
(6,)
vl is tuple
# 无,号
<class 'int'>
6
vl is int

Process finished with exit code 0

我很想知道 , 的语法规则
I would like to know the grammatical rules of ,

????????????????????????

**Comment by zufuliu** [comment]
Not a bug, https://docs.python.org/3/library/stdtypes.html#tuples

> Note that it is actually the comma which makes a tuple, not the parentheses. The parentheses are optional, except in the empty tuple case, or when they are needed to avoid syntactic ambiguity. For example, `f(a, b, c)` is a function call with three arguments, while `f((a, b, c))` is a function call with a 3-tuple as the sole argument.

**Comment by zhgna** [comment]
逗号在括号外面,也触发元组的语法规则吗?
vl=len(vint), # 有 , 号
print(type(vl))
请问,那一句定义元组了?

vl=len(vint), # 有 , 号
print(type(vl))
If the comma is outside the parentheses, does it also trigger the grammatical rules of the tuple?
Excuse me, which sentence defines the tuple?

**Comment by zufuliu** [comment]
I think you can ask help on https://discuss.python.org/c/users/7

**Comment by zhgna** [comment]
我想问你, 如果你不能指出明确的语法规则,那就别解释.我不希望得到整篇文档的模糊结果.
我英语不好,只能使用google翻译
I would like to ask you, if you can't point out a clear grammatical rule, then don't explain it. I don't want to get a vague result for the whole document.
