### ISSUE TITLE
[3.12] Lambda generators cause assertion failure: `python: Objects/genobject.c:400: gen_close: Assertion `exception_handler_depth > 0' failed.`

### ISSUE THREAD

**Issue by mgorny** [python/cpython#119897]
# Crash report

### What happened?

When CPython 3.12 is built with assertions enabled, the following snippet causes the interpreter to crash:

```python
x = lambda: (yield 3)
next(x())
```

```
$ ./python /tmp/LambdasTest.py 
python: Objects/genobject.c:400: gen_close: Assertion `exception_handler_depth > 0' failed.
Aborted (core dumped)
```

This doesn't happen with 3.11 or with main. From a quick bisect:

- #115818 (eb4774d2b7f5d50cd3cb8dc5abce9f94ce54197e) broke it on 3.12
- #111459 (52cc4af6ae9002f11605f91b672746c127494efd) fixed it on main

This was triggered in the wild by Nuitka's test suite: https://github.com/Nuitka/Nuitka/issues/2893.

CC @iritkatriel 

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.12.3+ (heads/3.12:6d9677d78e, Jun  1 2024, 11:06:51) [GCC 14.1.1 20240516]

### Linked PRs
* gh-120467
* gh-120658
* gh-120673

**Comment by mgorny** [comment]
Gentle ping.

**Comment by mgorny** [comment]
Given no reply, I'm going to revert this change in Gentoo. Hope that doesn't cause more issues.

**Comment by iritkatriel** [comment]
Thanks. I agree, let's revert the bad commit in 3.12.

**Comment by iritkatriel** [comment]
Thanks.

**Comment by mgorny** [comment]
Thank you!
