### ISSUE TITLE
Treat Fraction as a real value in mixed arithmetic operations with complex

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#119838]
In arithmetic operations, if one of operands is a `Fraction`, and the other operand is a `complex` or a `numbers.Complex`, the fraction is implicitly converted to a `complex`. Third-party types implementing the `numbers.Complex` interface can distinguish between real and complex operands. In future we can support the mixed real-complex arithmetic also for the builtin `complex` type. A fraction is a real value, so it makes sense to convert it to `float` instead of `complex` in such cases.

### Linked PRs
* gh-119839

**Comment by skirpichev** [comment]
> In future we can support the mixed real-complex arithmetic also for the builtin complex type.

Then this change will make sense.  Right now it contradicts to coercion rules for int/floats op complex.

Why in single codebase we will treat int's and Fraction's differently?  CC @mdickinson 

PS: But thank you for reminding me that I should fix also the "complex op Fraction" case in my pr:)

**Comment by mdickinson** [comment]
> A fraction is a real value, so it makes sense to convert it to `float` instead of `complex` in such cases.

+1
