### ISSUE TITLE
RegexFlag parameters not described in most re methods.

### ISSUE THREAD

**Issue by EdStauff** [python/cpython#119960]
# Documentation
In [https://docs.python.org/3/library/re.html](https://docs.python.org/3/library/re.html) (also 3.12, 3.13, and 3.14) the `flags` parameter is defined in the documentation for [`re.compile()`](https://docs.python.org/3/library/re.html#re.compile), but not for any other method that takes a `flags` parameter (`search, match, fullmatch, split, findall, finditer, sub, subn`).

I expected the documentation for each of those methods to at least specify the type of the `flags` parameter (presumably [`re.RegexFlag`](https://docs.python.org/3/library/re.html#re.RegexFlag)), with a link to the detailed description under the “Module Contents” section.
 

### Linked PRs
* gh-119978
* gh-120730
* gh-120908

**Comment by nineteendo** [comment]
Can this be closed?

**Comment by picnixz** [comment]
@kumaraditya303 it appears that the backport to 3.12 failed (maybe you missed the notification)

**Comment by kumaraditya303** [comment]
Seems like there was conflict while backporting, can you create the backport manually?

**Comment by picnixz** [comment]
I'll try! it's the first time I'm doing it but it shouldn't be that hard (I think).
