### ISSUE TITLE
A small typo in Doc/c-api/monitoring.rst

### ISSUE THREAD

**Issue by SweetyAngel** [python/cpython#119968]
# Documentation

The title of the page (https://docs.python.org/3.14/c-api/monitoring.html) should be "***Monitoring*** C API", not "***Monitorong*** C API"

### Linked PRs
* gh-119969
* gh-119971

**Comment by SweetyAngel** [comment]
This needs a backport to **3.13**

**Comment by sobolevn** [comment]
Thanks for the typo fix 👍
