### ISSUE TITLE
Dynamic string search algorithm selection

### ISSUE THREAD

**Issue by dg-pb** [python/cpython#119953]
# Feature or enhancement

### Proposal:

There is still a bit of ground to cover, but current results indicate that this could turn out to be fruitful.

The main idea is to dynamically switch from `Horspool` to `two-way` algorithm.

Below is the performance comparison of current string search versus current state of proposed approach.
<img width="829" alt="Screenshot 2024-06-02 at 21 56 48" src="https://github.com/python/cpython/assets/3577712/1ab349df-e568-47a5-b979-bd9558cef184">

The average percentage difference is close to 0, but it is still work in progress.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://discuss.python.org/t/optimize-str-find-aka-fastsearch/54483/13

**Comment by sweeneyde** [comment]
Let's discuss the ongoing proposals for fastearch.h here: https://github.com/python/cpython/issues/119702
