### ISSUE TITLE
Wrap some multi-line macros in ``do { ... } while(0)`` in ``symtable.c``

### ISSUE THREAD

**Issue by picnixz** [python/cpython#119981]
# Feature or enhancement

### Proposal:

While I was implementing #119976, I observed that some macros are not guarded against possible constructions because their content is only wrapped in `{}` but not in the classical `do { ... } while(0)` construction. 

For instance, the current `VISIT` macro sometimes requires the semi-colon and sometimes not depending on how it is used, which I find a bit confusing. I think it's preferrable to always require to add the `;`.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-119982

**Comment by sobolevn** [comment]
There are similar patterns in `compile.c`, maybe it is also worth taking a look? 🤔

**Comment by picnixz** [comment]
Yes, that's a good idea. Since I was going offline in a few minutes, could you either close this issue or edit the title so that we can perhaps track other files?

**Comment by sobolevn** [comment]
I prefer to open new ones for each piece of work :)
Thanks again!
