### ISSUE TITLE
Count the number of weekends between 2 dates

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#119950]
# Feature or enhancement

### Proposal:

This can be an important metric to calculate weekdays between 2 days. Given a holiday list, this function can be an important HR metric to calculate the number of working days between any two given dates.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-119948

**Comment by NobitaNoobie** [comment]
Thank you! I will rewrite my code here again:
def get_weekends_count(start_date , end_date):
            #self-defined function tiyasa khan
    #find the number of weekends between start_date and end_date
    #NOTE:::: START DATE < END DATE ALWAYS
            start_date_weekday = get_weekday(start_date)
            end_date_weekday = get_weekday(end_date)
            first_day_of_week_dayoftheweek = start_date_weekday
            total_days = (end_date - start_date).days + 1 #caution

            div = int(total_days / 7)
            rem = int(total_days % 7)

            num_weekends = div * 2
            
            for i in range(rem):
                if(first_day_of_week_dayoftheweek + i) % 7 in (5,6):
                    num_weekends += 1

            # print("WEEKENDS NO.",num_weekends)
            num_weekdays = (total_days - num_weekends)
            # print("WEEKDAYS NO.", num_weekdays)

            # # Exclude holidays from weekdays
            # for holiday in holidays:
            #     if start_date <= holiday <= end_date and holiday.weekday() not in (5, 6):
            #         num_weekdays -= 1

            return num_weekends

**Comment by nineteendo** [comment]
Please format you code like this:

````md
```python
# Code here
```
````

**Comment by NobitaNoobie** [comment]
Note: with an additional list, holidays, you can exclude user-defined holiday list.
```python
def get_weekends_count(start_date , end_date):
            #self-defined function tiyasa khan
    #find the number of weekends between start_date and end_date
    #NOTE:::: START DATE < END DATE ALWAYS
            start_date_weekday = get_weekday(start_date)
            end_date_weekday = get_weekday(end_date)
            first_day_of_week_dayoftheweek = start_date_weekday
            total_days = (end_date - start_date).days + 1 #caution

            div = int(total_days / 7)
            rem = int(total_days % 7)

            num_weekends = div * 2
            
            for i in range(rem):
                if(first_day_of_week_dayoftheweek + i) % 7 in (5,6):
                    num_weekends += 1

            # print("WEEKENDS NO.",num_weekends)
            num_weekdays = (total_days - num_weekends)
            # print("WEEKDAYS NO.", num_weekdays)

            # # Exclude holidays from weekdays
            # for holiday in holidays:
            #     if start_date <= holiday <= end_date and holiday.weekday() not in (5, 6):
            #         num_weekdays -= 1

            return num_weekends
```

**Comment by terryjreedy** [comment]
Why should this be in the stdlib?  And why was this not discussed on Discourse first?

**Comment by nineteendo** [comment]
I was also wondering that. Create a topic here: https://discuss.python.org/c/ideas/6
Note this isn't my idea, I simply created an issue because the pull request didn't have one.

**Comment by nineteendo** [comment]
Ask someone to re-open this after this has been discussed.

**Comment by NobitaNoobie** [comment]
I didn't know. I am new to this. Thanks @nineteendo

**Comment by hugovk** [comment]
For reference: https://discuss.python.org/t/a-function-to-check-number-of-weekends-between-two-days-in-the-calendar-module/54820

**Comment by NobitaNoobie** [comment]
yup @hugovk , I just wrote that discussion in the forum!
