### ISSUE TITLE
The behavior of `multithreading.Queue.empty()` when the Queue is closed is not explained in the docs 

### ISSUE THREAD

**Issue by marcoslimagon** [python/cpython#120012]
# Documentation

https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Queue.empty

It should be added that in case of the given method `Queue.empty()` is called after `Queue.close()` it will raise `OSError("handle is closed")``
(A clear and concise description of the issue.)

### Linked PRs
* gh-120102
* gh-120469
* gh-120470

**Comment by ericvsmith** [comment]
That seems like a good change. I don't think we would typically include the error text in the docs, but the fact that it raises `OSError` in that case is worth noting.

**Comment by rok** [comment]
This seems to have been resolved by #120102.

**Comment by hugovk** [comment]
@rok Thanks for checking, I've merged the backports, let's close now.
