### ISSUE TITLE
 Wrap some multi-line macros in `do { ... } while(0)` in `{codegen,compile}.c`

### ISSUE THREAD

**Issue by picnixz** [python/cpython#120017]
# Feature or enhancement

### Proposal:

Follow-up from the following observation (I'm sending a PR just after):

> There are similar patterns in `compile.c`, maybe it is also worth taking a look? 🤔

_Originally posted by @sobolevn in https://github.com/python/cpython/issues/119981#issuecomment-2145636560_
            

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-120018

**Comment by nineteendo** [comment]
Hmm, wouldn't it be better to re-use the previous issue?

**Comment by picnixz** [comment]
Well, Nikita preferred a new one (see https://github.com/python/cpython/issues/119981#issuecomment-2145641926).

**Comment by picnixz** [comment]
Closing since it was completed. I won't backport it since I didn't backport the others.
