### ISSUE TITLE
Typo in the documentation for the time module (specifically struct_time)

### ISSUE THREAD

**Issue by shoenot** [python/cpython#120078]
# Documentation

The table under class time.struct_time says 'tm_day' instead of 'tm_mday', which is incorrect.

### Linked PRs
* gh-120081
* gh-120084
* gh-120085

**Comment by shurj0** [comment]
submitted a pull request

**Comment by zware** [comment]
Please leave the issue open until the fix is merged :)

Good catch; the `m` was lost in GH-110862 for gh-101100.

**Comment by zware** [comment]
Thanks for the report and patch!
