### ISSUE TITLE
Minor improvements in ```colorsys``` module

### ISSUE THREAD

**Issue by SweetyAngel** [python/cpython#120120]
# Feature or enhancement

### Proposal:

There are some little improvements that need to be in a ```colorsys``` module:
- Minor optimization
- Minor links fixes
- Add support for CMYK color system

For other information, see the PR linled to this issue

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-120122

**Comment by serhiy-storchaka** [comment]
Let split this on several PRs.

* New functions.
* Doc fixes can be backported.
* The optimization needs some microbenchmarks to show that it actually takes place.

**Comment by serhiy-storchaka** [comment]
CMYK and other color spaces were discussed in #89933. I am not sure how its decision affects CMYK. cc @vstinner, @encukou.

**Comment by SweetyAngel** [comment]
> Let split this on several PRs.
> 
> * New functions.
> * Doc fixes can be backported.
> * The optimization needs some microbenchmarks to show that it actually takes place.

We are discussing this PR and are coming to the decision that it is not we actually want to see. So it will be most probably removed soon
