### ISSUE TITLE
Three typos in documentation

### ISSUE THREAD

**Issue by davidlowryduda** [python/cpython#120178]
# Documentation

I noticed a few typos in the documentation.

1. In `Doc/glossary.rst`, there is `immmortal` instead of `immortal`
2. In `Doc/library/dis.rst`, there is `oparand` instead of `operand`
3. In `Doc/library/pdb/rst`, there is `Accepatable` instead of `Acceptable`

I'm also submitting a PR to fix these.

### Linked PRs
* gh-120179

**Comment by gaogaotiantian** [comment]
Fixed in #120179
