### ISSUE TITLE
Possible bug with dataclasses

### ISSUE THREAD

**Issue by Alc-Alc** [python/cpython#120140]
# Bug report

### Bug description:

When `DefaultWithFieldInit().op()` is run, there is an exception as follows.

```
TypeError: some_func() takes 0 positional arguments but 1 was given
```

That class (`DefaultWithFieldInit`) has the field attribute (`op`) set to `init=False`. It seems the callable is handled as a method rather than a function and an implicit `self` is being sent. The other variants, "assigning a default directly" (class name: `Default`) and "assigning a default via a field" (class name: `DefaultWithField`) does not exhibit this behavior.

```python
from collections.abc import Callable
from dataclasses import dataclass, field


def some_func() -> int:
    return 1


@dataclass
class Default:
    op: Callable[[], int] = some_func


print(Default().op())  # works


@dataclass
class DefaultWithField:
    op: Callable[[], int] = field(default=some_func)


print(DefaultWithField().op())  # works


@dataclass
class DefaultWithFieldInit:
    op: Callable[[], int] = field(default=some_func, init=False)


print(DefaultWithFieldInit().op())  # fails, seems an implicit self is being sent
```

The doc for `init` [here](https://docs.python.org/3/library/dataclasses.html#dataclasses.field) mentions

> init: If true (the default), this field is included as a parameter to the generated [`__init__()`](https://docs.python.org/3/reference/datamodel.html#object.__init__) method.

This does not explain any behavioral changes other than the generated `__init__`.

Which means it should be similar to the following "normal class" variant that does work.

```python
class DefaultNormal:
    def __init__(self) -> None:
        self.op: Callable[[], int] = some_func


print(DefaultNormal().op())
```

If this is intended behavior, I would like if the docs make this explicit by mentioning a thing or two about this behavior.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

macOS

**Comment by SweetyAngel** [comment]
If ```init=False```, the class equals to this:
```python
@dataclass
class DefaultWithFieldInit:
    def op(self):
        return some_func()
```

So it needs a DefaultWithFieldInit parameter, like:
```python
def some_func(dwfi: DefaultWithFieldInit):
    return 1

**Comment by SweetyAngel** [comment]
But I suggest to fix this "bug"

**Comment by sobolevn** [comment]
I am not sure that this is a bug. Please, take a look at this code: https://github.com/python/cpython/blob/fd104dfcb838d735ef8128e3539d7a730d403422/Lib/dataclasses.py#L1011-L1029

When `default` is present, then `dataclass` will replace `field()` with the real default on a class. But, since `init` is set to `False`, it won't be shadowed on an instance level.

Basically this is the same as:

```python
>>> def some_func() -> int:
...     return 1
...     
>>> class Some:
...     f = some_func
...     
>>> Some.f
<function some_func at 0x101af4590>
>>> Some.f()
1
>>> Some().f()
Traceback (most recent call last):
  File "<python-input-5>", line 1, in <module>
    Some().f()
    ~~~~~~~~^^
TypeError: some_func() takes 0 positional arguments but 1 was given
```

Call this function as `DefaultWithFieldInit.op()`, or make a wrapper, or declare it as a `ClassVar`, or create an explicit method for it.

**Comment by ericvsmith** [comment]
I agree this isn't a bug in dataclasses, and is just how bound functions work. Thanks for the non-dataclasses example, @sobolevn!

**Comment by blhsing** [comment]
@sobolevn @ericvsmith This bug report is really about the discrepancy in behaviors of a field with a default between when `init=True` and when `init=False`. According to the doc, the `init` argument to `field` is supposed to specify only whether or not the field is included as a parameter to the generated `__init__`--the `init` argument should not decide whether the field is to become an instance attribute, which is not the case right now:
```python
from collections.abc import Callable
from dataclasses import dataclass, field

def some_func() -> int:
    return 1

@dataclass
class DefaultWithFieldInit:
    op1: Callable[[], int] = field(default=some_func)
    op2: Callable[[], int] = field(default=some_func, init=False)

print('op1' in DefaultWithFieldInit().__dict__) # True
print('op2' in DefaultWithFieldInit().__dict__) # False, but why? This is very surprising and counter-intuitive
```
A fix to this bug should ensure that a field should always be an instance attribute unless it has a default value of a data descriptor object, and we should change the wording of "descriptor" to "data descriptor" in the [Descriptor-typed fields](https://docs.python.org/3/library/dataclasses.html#descriptor-typed-fields) section of the doc.

**Comment by Alc-Alc** [comment]
> I agree this isn't a bug in dataclasses, and is just how bound functions work. Thanks for the non-dataclasses example, @sobolevn!

Thanks @sobolevn and @ericvsmith for responding. I understand why the non data class example works that way, but as @blhsing mentions, it really is about the discrepancy. By the time I wrote this reproducible example it was clear to me what the workaround could be but again, it's not something that is evident from reading the docs. As I mentioned in the description, this should at least warrant a note in the docs if this is intended.

That being said, a parameter that claims to affects the generated init should not cause this change. I touched upon this in the description as well.

> This does not explain any behavioral changes other than the generated __init__.
> Which means it should be similar to the following "normal class" variant that does work.

**Comment by sobolevn** [comment]
> According to the doc, the init argument to field is supposed to specify only whether or not the field is included as a parameter to the generated `__init__`--the init argument should not decide whether the field is to become an instance attribute

This is exactly what `__init__` does: it assigns instance attributes in the initializer. So, all fields that have `init=True` will automatically become instance attributes.

If you have suggestions about a better wordings in the docs - please, share them :)

**Comment by blhsing** [comment]
> This is exactly what `__init__` does: it assigns instance attributes in the initializer. So, all fields that have `init=True` will automatically become instance attributes.
> 
> If you have suggestions about better wordings in the docs - please, share them :)

If that is indeed the intention, we should perhaps change the wordings in the doc for the `init` argument from:

> `init`: If true (the default), this field is included as a parameter to the generated [`__init__()`](https://docs.python.org/3/reference/datamodel.html#object.__init__) method

to something like:

> `init`: If true (the default), this field is included as a parameter to the generated [`__init__()`](https://docs.python.org/3/reference/datamodel.html#object.__init__) method, and is initialized as an instance attribute
