### ISSUE TITLE
ProcessPoolExecutor() with the workers set to default crashes on Rocks 7.0 (Manzanita)

### ISSUE THREAD

**Issue by pri1712** [python/cpython#120192]
# Bug report

### Bug description:

I'm using Python  3.9.19 on Rocks 7.0 (Manzanita) , and when I do not set the number of threads to some value and let it default , it crashes. I have 64 cpu cores. Could the issue be that it is just using too much memory and then crashing? While debugging I set the number_workers parameter to 2 and it was working fine, just too slow, so using only 2 is not practically feasible for me.
I am currently running it with 8 workers and it is running fine for now.

Traceback (most recent call last):
  File "/data1/xyz/Displace2024_baseline/speaker_diarization/SHARC_check/wespeaker/diar/spectral_clusterer.py", line 264, in main
    for (subsegs, labels) in zip(subsegs_list,
  File "/data1/xyz/.conda/envs/wespeaker/lib/python3.9/concurrent/futures/process.py", line 562, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/data1/xyz/.conda/envs/wespeaker/lib/python3.9/concurrent/futures/_base.py", line 609, in result_iterator
    yield fs.pop().result()
  File "/data1/xyz/.conda/envs/wespeaker/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/data1/xyz/.conda/envs/wespeaker/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

Above is the error message I receive when I let the number of workers to default . 
**"Default value of max_workers is changed to min(32, os.cpu_count() + 4) ."** 
So in my case it is leading to the above error with 32 workers.

EDIT: Tried using 16 workers , it lead to the same issue.

Thanks.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
It seems like you are using some 3rd party libraries. With only the exception there's nothing we can do here. If it's a CPython issue, you should be able to reproduce this problem with only CPython (and its standard libraries). Otherwise you should put together a reproducible example and report to the library you are using first.

**Comment by pri1712** [comment]
Yes it seems to be an error due to some 3rd party library , when I ran outside the conda env it all works fine. Any idea as to why this would be happening and how do I find which library is causing this?

**Comment by aisk** [comment]
If it's not caused by CPython, you should open a ticket on https://discuss.python.org/c/users/7 for help. My personal suggestion is that if you are using Linux, using dmesg to check the kernel log may help.
