### ISSUE TITLE
Introduction docs, part 3.1.2: the length of a string slice

### ISSUE THREAD

**Issue by SweetyAngel** [python/cpython#120129]
### Problem
```the length of a slice is the difference of the indices``` works with negative indices also.
See:
```python
>>> word = 'python'
>>> len(word[-4:-1]), -1 - (-4)
(3, 3)
```

### Linked PRs
* gh-120130

**Comment by hugovk** [comment]
Closing, it was decided to leave this as-is: https://github.com/python/cpython/pull/120130#issuecomment-2161502610

Thanks anyway for the suggestion.
