### ISSUE TITLE
Flaky test ``test_preauth_data_to_tls_server`` in ``test_ssl``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#120162]
# Bug report

### Bug description:

```python
test_ssl failed -- Traceback (most recent call last):
  File "/Users/admin/Projects/cpython/Lib/test/test_ssl.py", line 5025, in test_preauth_data_to_tls_server
    self.non_linux_skip_if_other_okay_error(wrap_error)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/test/test_ssl.py", line 4972, in non_linux_skip_if_other_okay_error
    re.search('wrong.version.number', getattr(err, "reason", ""), re.I)):
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/admin/Projects/cpython/Lib/re/__init__.py", line 177, in search
    return _compile(pattern, flags).search(string)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-120185

**Comment by vstinner** [comment]
> Operating systems tested on: macOS

I fail to reproduce the issue on Linux. I tried the command:

```
./python -m test test_ssl -m test_preauth_data_to_tls_server -F -j10
```

**Comment by pygeek** [comment]
> > Operating systems tested on: macOS
> 
> I fail to reproduce the issue on Linux. I tried the command:
> 
> ```
> ./python -m test test_ssl -m test_preauth_data_to_tls_server -F -j10
> ```

The test helper function in question, `non_linux_skip_if_other_okay_error`, only targets non-Linux operating systems.

**Comment by pygeek** [comment]
I rebuilt the binary, and was unable to encounter the issue. I believe I had the incorrect configuration. Be sure to configure with `--pydebug`.
