### ISSUE TITLE
`SyntaxWarning: invalid escape sequence` should not trigger in comments

### ISSUE THREAD

**Issue by rolux** [python/cpython#120113]
# Bug report

### Bug description:

Currently, the syntax warning for single backslashes also triggers in comments.

This is inconvenient for multi-line comments including a shell command, which may legitimately contain unescaped backslashes.

Since shell commands in comments are a common use case, and backslashes a common occurrence in such commands, the syntax warning should be restricted to code outside of comments.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Hello!
Can you provide an example of code which triggers that error?

**Comment by rolux** [comment]
> Hello! Can you provide an example of code which triggers that error?

In my case, it was:

```python
"""
ffmpeg -r 60 -i data_lobby_Nurburgring\ -\ Nordschleife_Max\ RS/%08d.png -vcodec libx264 -pix_fmt yuv420p -crf 17 data_lobby_Nurburgring\ -\ Nordschleife_Max\ RS.mp4
"""
```

which triggered:

`SyntaxWarning: invalid escape sequence '\ '`

**Comment by Eclips4** [comment]
I'm guess this is related to nested f strings which were introduced in 3.12...?
cc @pablogsal

**Comment by rolux** [comment]
> I'm guess this is related to nested f strings which were introduced in 3.12...? cc @pablogsal

The `SyntaxWarning` was introduced in 3.12. The same code would have triggered a `DeprecationWarning` since 3.6.

The warning does not trigger in single-line comments (starting with `#`).

**Comment by picnixz** [comment]
I'm assuming you are actually using those backslashes in docstrings, i.e.,

```py
def foo():
	"""Hello I have a backslash here \."""
```

To avoid the warning, do something like.

```py
def foo():
	r"""Hello I have a backslash here \."""
	# note the 'r' before the quotes
```

The doc for the `r` prefix says:

> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such strings are called raw strings and treat backslashes as literal characters.

**Comment by rolux** [comment]
> How about using `r`-strings? because, AFAICT, what you need is a literal "\" (also, you should say that it triggers in strings and not in comments)

If triple-quoted r-strings are the (new) standard for multi-line comments, I consider the issue resolved.

**Comment by picnixz** [comment]
Err... actually the `r` prefix also works for single-quoted strings. Just keep in mind that you cannot end a literal string with "\\" even if you put the "r" (so something like `r"hello \"` does not work).

**Comment by rolux** [comment]
> @rolux:
> 
> > If triple-quoted r-strings are the (new) standard for multi-line comments with single backslashes, I consider the issue resolved.
> 
> To be very clear, triple-quoted strings have never been and will never be comments; they are strings just like any other except that they are allowed to contain unquoted newline characters. There is no such thing as a multi-line comment in Python, though triple-quoted strings are sometimes abused as such. If you choose to use them that way, you need to account for the fact that they are syntactically strings and will be parsed and compiled that way.

While you're of course correct that triple-quoted strings are, syntactically, nothing else than any other string, they are the de-factor standard for multi-line comments, docstrings and other types of documentation. Using r-strings is the correct solution if you want unescaped single backlashes, but I think that in practice, they are being used a lot for raw, unescaped content.

**Comment by NickWaterton** [comment]
> While you're of course correct that triple-quoted strings are, syntactically, nothing else than any other string, they are the de-facto standard for multi-line comments, docstrings and other types of documentation.

I would just like to point out that this is correct, so making this change will break all existing code that uses this commenting method. I for one would not look forward to editing thousands of lines of code in hundreds of files to add an "r" to the front of the comment.
