### ISSUE TITLE
cant move a long-named file to a loang-named dir

### ISSUE THREAD

**Issue by pokq** [python/cpython#120142]
# Bug report

### Bug description:

```python
import os
import shutil

if __name__ == '__main__':
    text = "kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk"
    file = text + '.txt'
    fd = text 
    with open(file, 'w') as f:
        pass
    if not os.path.exists(fd):
        os.mkdir(fd)
        
    if not os.path.exists(f'{fd}/{file}'):
        shutil.move(file, fd)

```
I can move it by hand ,but can't run this script

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by eryksun** [comment]
Please edit the text of the issue to paste the exception that gets raised and the traceback. Also, please describe what is meant by moving the file by hand. Do you mean dragging and dropping in Explorer, or cut/paste in Explorer? Or do you mean a shell command such as CMD's `move` command?

One last thing, please include the value of "LongPathsEnabled" in the registry key "HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\FileSystem". If it isn't enabled, then absolute file paths are limited to a length of 259 characters, except for "\\\\?\\" extended paths. The relative path in your example is 241 characters, in which case the path length of the working directory cannot exceed 18 characters, unless long paths are enabled or unless the resolved absolute path is converted to an extended path.

**Comment by pokq** [comment]
@eryksun I mean dragging and dropping in Explorer. and the error is [WinError 3]
```
    _winapi.CopyFile2(src_, dst_, flags)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。
```
thanks ,I will try with enable the key "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem"

**Comment by eryksun** [comment]
Windows error 3 is `ERROR_PATH_NOT_FOUND`. That's the typical error if a regular path exceeds the legacy limit of 259 characters when long paths aren't enabled in the registry.

**Comment by pokq** [comment]
@eryksun Okay,and I still have some confuse in python handle windows path proplems ,include python create `folder path` starts or ends with space charocters, and path have some low case or upper case characters. I will spend some time on it.

**Comment by eryksun** [comment]
Windows strips dots and spaces from the end of an opened path, unless it's an extended path. Thus a normal filename or directory name on Windows never ends with a dot or space character. Extra caution is needed when using extended paths to ensure that reserved names are never created. In 3.13+, you can check for a reserved name via `ntpath.isreserved()`. Fortunately with long path support in Windows 10+, there's less need for the use of extended paths.

Device names and paths on Windows normally are case-insensitive but case-preserving. On Windows 10+, the NTFS filesystem (i.e. the type of filesystem on the system "C:" drive) supports marking a directory as case-sensitive, which gets inherited by child directories. However, this is rarely used, except for compatibility with Windows Subsystem for Linux (WSL), or for particular development trees that require distinguishing names by case (e.g. a file named "python" next to a directory named "Python").

**Comment by pokq** [comment]
well, I tried, you're right .thanks.
