### ISSUE TITLE
collect function bug

### ISSUE THREAD

**Issue by fery-one** [python/cpython#120138]
# Bug report

### Bug description:

if you run the code below in  python, it can't collect the very simple expr with mv-derivative.

from sympy import Symbol, symbols, collect, expand
x = Symbol("x", real = True)
theta = Symbol("theta", real = True)
t = Symbol("t", real = True)
u = symbols('u', real = True, cls=Function)(x, theta, t)

expr = u.diff(x, x, t) * x + u.diff(x, x, t) * t
expr = collect(expand(expr), u.diff(x, x, t))

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
This appears to be a sympy issue. You should report it at https://github.com/sympy/sympy/issues
