### ISSUE TITLE
Incorrect case string in configure script

### ISSUE THREAD

**Issue by allsey87** [python/cpython#120154]
# Bug report

### Bug description:

I think this: https://github.com/python/cpython/blob/fd104dfcb838d735ef8128e3539d7a730d403422/configure#L12895

Should be: `Emscripten*|WASI*`

I could be wrong, but I think this will never be matched otherwise since even if `ac_sys_release` is empty, we would be trying to match `Emscripten` against `Emscripten/`

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-120173
* gh-120199
* gh-120204
* gh-120309

**Comment by allsey87** [comment]
I think the only reason why this hasn't been an issue/picked up before is that usually, for Emscripten builds, `emconfigure` is executed instead of `configure` which sets `LDSHARED` as an environment variable, causing the entire block to be bypassed.

**Comment by allsey87** [comment]
I can confirm that patching `configure` enabled me to move forwards. The values in the resulting `Makefile` now looks closer to what is generated in the Pyodide project with an extra `-shared` argument passed to `emcc`.

**Comment by erlend-aasland** [comment]
Thanks for the report! It sounds like you have a patch ready; would you like to open a PR?

**Comment by erlend-aasland** [comment]
Thanks for the report and the fix, @allsey87!

**Comment by vstinner** [comment]
@allsey87: Thanks for signing again the CLA with your second email address.

**Comment by encukou** [comment]
This broke the stable buildbot [wasm32-wasi Non-Debug 3.12](https://buildbot.python.org/all/#/builders/1372), see e.g. [here](https://buildbot.python.org/all/#/builders/1372/builds/359).

**Comment by allsey87** [comment]
Are you sure it was this commit? The error that you are getting sounds unrelated to this change:
```
wasm-ld: error: Modules/_testimportmultiple.o: relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `_testimportmultiple`; recompile with -fPIC
```

**Comment by vstinner** [comment]
> This broke the stable buildbot [wasm32-wasi Non-Debug 3.12](https://buildbot.python.org/all/#/builders/1372), see e.g. [here](https://buildbot.python.org/all/#/builders/1372/builds/359).

```
wasm-ld: error: Modules/_testimportmultiple.o: relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `_testimportmultiple`; recompile with -fPIC
wasm-ld: error: Modules/_testimportmultiple.o: relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `_foomodule`; recompile with -fPIC
wasm-ld: error: Modules/_testimportmultiple.o: relocation R_WASM_MEMORY_ADDR_SLEB cannot be used against symbol `_barmodule`; recompile with -fPIC
```

The difference between main and 3.12 is that 3.12 tries to build test modules such as `_testimportmultiple`.

=> I wrote https://github.com/python/cpython/pull/120309 to fix the issue.

**Comment by allsey87** [comment]
@vstinner not sure if this relevant, but #120204 did change the flags for the buildbot.

Previously:
```
checking LDSHARED... 
checking BLDSHARED flags... 
checking CCSHARED... 
checking LINKFORSHARED... 
checking CFLAGSFORSHARED... 
```
Now:
```
checking LDSHARED... $(CC) -shared
checking BLDSHARED flags... $(CC) -shared
checking CCSHARED... 
checking LINKFORSHARED... 
checking CFLAGSFORSHARED... 
```

**Comment by allsey87** [comment]
The linked PR are indeed merged. Closing.
