### ISSUE TITLE
devhelp documentation doesn't build with sphinx 7.2.6

### ISSUE THREAD

**Issue by danigm** [python/cpython#120150]
# Documentation

Sphinx raises an exception when trying to build the Python 3.13 documentation:

```pytb
$ cd Doc
$ sphinx-build -a -b devhelp . build/devhelp
...
dumping devhelp index...
 
Exception occurred:
File "/usr/lib/python3.11/site-packages/sphinx/environment/__init__.py", line 603, in get_doctree
    with open(filename, 'rb') as f:
         ^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/abuild/rpmbuild/BUILD/Python-3.13.0b2/Doc/build/devhelp/.doctrees/index.doctree'
```

This is due to the removal of `master_doc = 'contents'` in the `conf.py` file done in this PR: https://github.com/python/cpython/pull/117853

## Environment:

* os: **openSUSE Tumbleweed**
* python version: **Python 3.11.9**
* sphinx: **sphinx-build 7.2.6**
* sphinxcontrib-devhelp: **1.0.6**

**Comment by hugovk** [comment]
Thanks for the report.

> This is due to the removal of `master_doc = 'contents'` in the `conf.py` file done in this PR: #117853

It was replaced with `root_doc = 'contents'`, which was changed in Sphinx 4.0:

* https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-root_doc

This sounds like a bug with Sphinx or sphinxcontrib-devhelp, please could you report it to Sphinx?

* https://www.sphinx-doc.org/en/master/internals/contributing.html#bug-reports-and-feature-requests

**Comment by picnixz** [comment]
Confirmed as a Sphinx issue (it's both a core Sphinx issue and a `sphinxcontrib-devhelp` issue)
