### ISSUE TITLE
Unused code in `concurrent.future`

### ISSUE THREAD

**Issue by aisk** [python/cpython#120157]
# Bug report

### Bug description:

https://github.com/python/cpython/blob/fd104dfcb838d735ef8128e3539d7a730d403422/Lib/concurrent/futures/_base.py#L26C1-L32

The `_FUTURE_STATES` variable hasn't been used in this file, and nor in other files: https://github.com/search?q=repo%3Apython%2Fcpython%20_FUTURE_STATES&type=code  
  
And since it has an underscore prefix in the name, it's a private variable and won't be used by users.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-120187

**Comment by gaogaotiantian** [comment]
I would proceed with some extra caution there. It seems like even when it was first checked in, that variable is not referenced anywhere. So it's not like the usage was removed some time after the initial checked in and the variable was left there. It's possible that this was accidentally merged to begin with, but the code has been there for 14 years.

I'm not saying that we should not remove those, but I'll feel a bit more confident if we can figure out why it was there in the first place.
