### ISSUE TITLE
element doesn't serialize properly using tostring( elem,method ='html')

### ISSUE THREAD

**Issue by de-cooder** [python/cpython#120117]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
while converting node into string using [tostring](https://github.com/python/cpython/blob/10eac0269bce4e2ba575e5b549d3dd9a6da9349a/Lib/xml/etree/ElementTree.py#L1067) of ElementTree class with method = "HTML" it is not [serializng] correctly for [HTML empty node](https://github.com/python/cpython/blob/10eac0269bce4e2ba575e5b549d3dd9a6da9349a/Lib/xml/etree/ElementTree.py#L900)  [``def _serialize_html``](https://github.com/python/cpython/blob/10eac0269bce4e2ba575e5b549d3dd9a6da9349a/Lib/xml/etree/ElementTree.py#L904) this method converting the this ``<br/>`` -> ``<br>`` which is not correct. if again We will parse into using fromstring it will give error opening and ending tag is missing. 

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-120119

**Comment by Sanchit041** [comment]
> It is a valid HTML tag. By the way `fromstring` expects an XML input (by default), not HTML one. You need to implement a custom parser for that.

but still their can be self closing tag so they can be handled I had kept one example here

**Comment by picnixz** [comment]
Well.. this is a design choice. Strictly speaking, you are not required to use the full form `<tag></tag>` in HTML if your tag is a void tag. In addition, it was probably implemented like this to reduce the output size.

Now, if you want to convert XML to HTML back and forth, it should not be done via the `xml` module, unless you provide your HTML parser for that. Instead, I'd suggest using a third-party library such as `lxml`.

**Comment by serhiy-storchaka** [comment]
[Self-closing tags (`<tag />`) do not exist in HTML.](https://developer.mozilla.org/en-US/docs/Glossary/Void_element#self-closing_tags)

You can write `<br />`, and the HTML parser will ignore the slash, but this is not required and is not recommended. You can use `method='xml'` or write your own generator.
