### ISSUE TITLE
``fnctlmodule.fcntl_ioctl_impl`` has outdated format string

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#120296]
# Bug report

### Bug description:

After 92fab3356f4c61d4c73606e4fae705c6d8f6213b fcntl.ioctl `code` argument has type `unsigned long`, so 
this code should be updated:
from
```c
    if (PySys_Audit("fcntl.ioctl", "iIO", fd, code,
                    ob_arg ? ob_arg : Py_None) < 0) {
        return NULL;
    }
```
to
```c
    if (PySys_Audit("fcntl.ioctl", "ikO", fd, code,
                    ob_arg ? ob_arg : Py_None) < 0) {
        return NULL;
    }
```

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-120301

**Comment by Eclips4** [comment]
cc @vstinner

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/e5a7bc6f2eb9a3875063423caa67bb0ffcc3a6b8. I was surprised that @Eclips4 wasn't the author of the change, I just noticed it after merging the PR :-)
