### ISSUE TITLE
macOS: python3t shortcuts missing(?)

### ISSUE THREAD

**Issue by henryiii** [python/cpython#120286]
# Bug report

### Bug description:

Installing Python creates `python3` aliases, but there doesn't seem to be a matching `python3t` alias. There's a `python3.13t`, but `python3t` would be more future proof for a shabang, etc. This is what macOS installs:

```
cibuildwheel % find /Library/Frameworks/PythonT.framework/Versions/3.13/bin/
/Library/Frameworks/PythonT.framework/Versions/3.13/bin/
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//python3.13t
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//python3.13t-config
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//pip3.13
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//pip3
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//pip
/Library/Frameworks/PythonT.framework/Versions/3.13/bin//python3.13
```

There's pip aliases, but no `python3t` (this is also missing `python3`, though it has `python3.13`. I'm not sure if this is macOS specific, or if `python3t` is being avoided for now, or if it's just not come up yet, I didn't see it mentioned in issues.

From https://github.com/pypa/cibuildwheel/pull/1856#issuecomment-2156089380.

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-120457

**Comment by hugovk** [comment]
Is this only for macOS, or also Windows?

**Comment by mayeut** [comment]
It's the same on Windows (looking at the nugget package):
```
~ % find Downloads/python-freethreaded.3.13.0-b2.nupkg/tools -name 'python*.exe'
Downloads/python-freethreaded.3.13.0-b2.nupkg/tools/pythonw3.13t.exe
Downloads/python-freethreaded.3.13.0-b2.nupkg/tools/pythonw.exe
Downloads/python-freethreaded.3.13.0-b2.nupkg/tools/python.exe
Downloads/python-freethreaded.3.13.0-b2.nupkg/tools/python3.13t.exe
```

**Comment by zooba** [comment]
Windows has never included any aliases. We only have `python3.13t` because that's what the steering council said would be the equivalent of `python`.

**Comment by encukou** [comment]
As long as the free-threaded build is experimental, it should be used with a specific version number. If and when it stops being experimental, the `t` suffix will be dropped entirely.
`python3t` is *not* future-proof.


See the [Steering Council decision](https://github.com/python/steering-council/issues/221#issuecomment-1841593283): 
> Lets *not* have a generic `python3t` so long as we're in "experimental" phase as is the case for 3.13 until a future SC is asked to declare otherwise based on future core dev consensus on Discuss when the time feels right.

I'll close the issue.

**Comment by nineteendo** [comment]
Thanks, I wasn't aware of this.
