### ISSUE TITLE
flowgraph.c: push_cold_blocks_to_end: Assertion `prev_instr' failed

### ISSUE THREAD

**Issue by 15r10nk** [python/cpython#120225]
# Bug report

### Bug description:

The following code causes a crash with cpython 3.13 (56a7e0483436d1ebd2af97c02defe0e67c4bb495) and with the current main branch (d68a22e7a68ae09f7db61d5a1a3bd9c0360cf3ee)

```python
async def name_4():
    match b'':
        case True:
            pass
        case name_5 if f'e':
            {name_3: name_4 async for name_2 in name_5}
        case []:
            pass
    [[]]
```

output (Python 3.13.0b2+):
```python
python: Python/flowgraph.c:2282: push_cold_blocks_to_end: Assertion `prev_instr' failed.
```
I bisected the problem down to this commit 2091fb2a85c1aa2d9b22c02736b07831bd875c2a.
@iritkatriel can you take a look at it?

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-120235
* gh-120249

**Comment by iritkatriel** [comment]
>  @iritkatriel can you take a look at it?

Yes. Thank you.
