### ISSUE TITLE
urllib.parse.urlsplit has trouble with basic auth passwords that contain hashtags

### ISSUE THREAD

**Issue by tsiq-bradleyg** [python/cpython#120241]
# Bug report

### Bug description:

Code:
```python
from urllib.parse import urlsplit
urlsplit("postgresql://pg_user:pg_#password@rds.amazonaws.com:5432/db_name")
```
Actual Behavior
`SplitResult(scheme='postgresql', netloc='pg_user:pg_', path='', query='', fragment='password@rds.amazonaws.com:5432/db_name')`
Expected Behavior
`SplitResult(scheme='postgresql', netloc='pg_user:pg_#password@rds.amazonaws.com:5432', path='/db_name', query='', fragment='')`

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by tsiq-bradleyg** [comment]
I intend to submit a PR for this, unless somebody already has a fix.

**Comment by tsiq-bradleyg** [comment]
Follow up: Url encoding the hashtag solves the issue. So maybe this is an intentional behavior.

**Comment by aisk** [comment]
According to [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1), the `userinfo` is:

```
userinfo      = *( unreserved / pct-encoded / sub-delims / ":" )
```

while

```
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
reserved      = gen-delims / sub-delims
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
              / "*" / "+" / "," / ";" / "="
```

So the hashtag in `userinfo` is invalid.

**Comment by vadmium** [comment]
Same as #62340

**Comment by tsiq-bradleyg** [comment]
Duplicate, and not bug.
