### ISSUE TITLE
pickling & deepcopy of rruleset and rrule with cache

### ISSUE THREAD

**Issue by niccokunzmann** [python/cpython#120236]
# Feature or enhancement

### Proposal:

In case that rruleset and rrule are created with `cache=True`, they cannot be pickled.

I added these functions to the `copyreg` to pickle them and use copy.deepcopy on them:

```python
# Add a code block here, if required
from copyreg import pickle

def pickle_rrule_with_cache(self: rrule):
    """Make sure we can also pickle rrules that cache.

    This is mainly copied from rrule.replace.
    """
    new_kwargs = {"interval": self._interval,
                  "count": self._count,
                  "dtstart": self._dtstart,
                  "freq": self._freq,
                  "until": self._until,
                  "wkst": self._wkst,
                  "cache": False if self._cache is None else True }
    new_kwargs.update(self._original_rule)
    # from https://stackoverflow.com/a/64915638/1320237
    return functools.partial(rrule, new_kwargs.pop("freq"), **new_kwargs), ()

pickle(rrule, pickle_rrule_with_cache)

def pickle_rruleset_with_cache(rs: rruleset):
    """Pickle an rruleset."""
    # self._rrule = []
    # self._rdate = []
    # self._exrule = []
    # self._exdate = []
    return unpickle_rruleset_with_cache, (
        rs._rrule, rs._rdate, rs._exrule,
        rs._exdate, False if rs._cache is None else True
    )

def unpickle_rruleset_with_cache(rrule, rdate, exrule, exdate, cache):
    """unpickling the rruleset."""
    rs = rruleset(cache)
    for o in rrule: rs.rrule(o)
    for o in rdate: rs.rdate(o)
    for o in exrule: rs.exrule(o)
    for o in exdate: rs.exdate(o)
    return rs

pickle(rruleset, pickle_rruleset_with_cache)
```

However, it would be much nicer if these would reside in the `__reduce__` function of the respective classes.

Would it be a contribution to add this functionality?

Context:

- https://github.com/collective/icalendar/blob/9035a2204a9a6956f173f73793fc083951b78ee5/src/icalendar/timezone/zoneinfo.py#L89
- https://github.com/collective/icalendar/pull/623 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by serhiy-storchaka** [comment]
What is rruleset and rrule?

**Comment by picnixz** [comment]
Those are from third-party libraries: https://dateutil.readthedocs.io/en/stable/rrule.html and https://dateutil.readthedocs.io/en/stable/rrule.html#rruleset-examples.

However, the pickability of those interfaces is left to [dateutil](https://github.com/dateutil/dateutil) and not CPython, so you should open an issue on their side.

**Comment by serhiy-storchaka** [comment]
Thanks @picnixz. I agree with this.
