### ISSUE TITLE
Enhancement for OrderedDict: Add `reorder_by_values` method

### ISSUE THREAD

**Issue by Vikranth3140** [python/cpython#120246]
# Feature or enhancement

### Proposal:

**Enhancement for OrderedDict: Add `reorder_by_values` method**

This proposal aims to enhance the `OrderedDict` class in the `collections` module by adding a method `reorder_by_values` that reorders the dictionary based on its values. This functionality will allow users to sort their `OrderedDict` instances by value easily, providing additional flexibility and usability.

#### Code Example:
```python
class OrderedDict(dict):
    # existing methods ...

    def reorder_by_values(self):
        """Reorder the OrderedDict based on its values."""
        sorted_items = sorted(self.items(), key=lambda item: item[1])
        self.clear()
        for key, value in sorted_items:
            self[key] = value

# Example usage:
od = OrderedDict()
od['a'] = 3
od['b'] = 1
od['c'] = 2

od.reorder_by_values()
print(od)  # Output: OrderedDict([('b', 1), ('c', 2), ('a', 3)])
```

This method sorts the items in the `OrderedDict` based on their values and reorders the dictionary accordingly, improving its functionality and usability.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-120247

**Comment by sobolevn** [comment]
Please, first discuss new features on https://discuss.python.org/c/ideas/6 :)

Also, provide a strong reason why this should be added instead of this simple func:

```python
def reorder_by_values(obj):
  """Reorder the OrderedDict based on its values."""
  res = OrderedDict()
  sorted_items = sorted(obj.items(), key=lambda item: item[1])
  for key, value in sorted_items:
      res[key] = value
  return res
```

**Comment by rhettinger** [comment]
Why reorder in-place?  I would just sort data directly into a new instance:  `OrderedDict(items_already_sorted_however_you_want_them)`
