### ISSUE TITLE
Improve deprecation warning message, when a test case returns non `None` value

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#120388]
# Feature or enhancement

Right now there are two potential things we can improve in this warning message: https://github.com/python/cpython/blob/19435d299a1fae9ad9a6bbe6609e41ddfd7f6cbe/Lib/unittest/case.py#L605-L609

1. The returned value's type is not shown. It can be useful for users
2. A common case for this warning is that `async def test_some` is defined in a regular `TestCase` class, I think that we can improve this specific case and suggest to use `IsolatedAsyncioTestCase` instead

I have a patch ready.

### Linked PRs
* gh-120401

**Comment by AlexWaygood** [comment]
Thanks for doing this @sobolevn! :D
