### ISSUE TITLE
Missing type checking on `maxsize` arg of `queue.Queue` class during initialization

### ISSUE THREAD

**Issue by anchal00** [python/cpython#120319]
# Bug report

### Bug description:

```
>>> from queue import Queue
>>> 
>>> q = Queue(maxsize=None)
>>> q.put(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anchal/.pyenv/versions/3.9.6/lib/python3.9/queue.py", line 134, in put
    if self.maxsize > 0:
TypeError: '>' not supported between instances of 'NoneType' and 'int'
>>> 
>>> 
>>> 
>>> 
>>> q = Queue(maxsize=[12])
>>> 
>>> q.put(3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/anchal/.pyenv/versions/3.9.6/lib/python3.9/queue.py", line 134, in put
    if self.maxsize > 0:
TypeError: '>' not supported between instances of 'list' and 'int'
>>> 
```

The initializer for the Queue class should enforce type checking on the `maxsize` argument. Currently, it allows the creation of a Queue with an invalid argument type, which then causes the program to crash.

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

### Linked PRs
* gh-120369
* gh-120382

**Comment by sobolevn** [comment]
What will be different if you got a `TypeError` on `Queue(maxsize=None)` and not on `q.put(3)`?

It is documented to be `int`:

> maxsize is an integer that sets the upperbound limit on the number of items that can be placed in the queue.

https://docs.python.org/3/library/queue.html#queue.Queue

And `typeshed` also knows that it is an `int`: https://github.com/python/typeshed/blob/58f2a795bac5924367d21961af53a32af7bb5727/stdlib/queue.pyi#L33

So, any type-checker / IDE will point out that `None` is incorrect here.

**Comment by Zheaoli** [comment]
But I think we need an extra type here. not all of the developer use type-checker

**Comment by anchal00** [comment]
> What will be different if you got a TypeError on Queue(maxsize=None) and not on q.put(3)?

I am not talking about type checkers at all. Sure they can detect this and warn the developer. All I am suggesting is that the Queue API can be made more cleaner 

If we add extra type check there will be

1. **Zero surprises** - Python lets the flawed initialization happen but complains only when it is being used. It would be logically more correct and would make sense if Queue doesn't get created with wrong attributes in the first place.
The counter argument _'the behaviour would be exactly same and nothing would change'_ is right. To a program using a queue, it maybe wouldn't make much difference, but to the developers like me, it sure would. **It would behave exactly as it should**

2. **Consistency** - 
```
>>> from collections import deque
>>> 
>>> dq = deque(maxlen=[10])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: an integer is required
```
I'd like to know what is special about the Queue initialization that it differs from that of deque's. Of course they offer different access patterns and have different implementation details, but at a higher level, both of them are containers/data structures and should behave consistently where they can.

**Comment by pygeek** [comment]
> > What will be different if you got a TypeError on Queue(maxsize=None) and not on q.put(3)?
> 
> I am not talking about type checkers at all. Sure they can detect this and warn the developer. All I am suggesting is that the Queue API can be made more cleaner
> 
> If we add extra type check there will be
> 
> 1. **Zero surprises** - Python lets the flawed initialization happen but complains only when it is being used. It would be logically more correct and would make sense if Queue doesn't get created with wrong attributes in the first place.
>    The counter argument _'the behaviour would be exactly same and nothing would change'_ is right. To a program using a queue, it maybe wouldn't make much difference, but to the developers like me, it sure would. **It would behave exactly as it should**
> 2. **Consistency** -
> 
> ```
> >>> from collections import deque
> >>> 
> >>> dq = deque(maxlen=[10])
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: an integer is required
> ```
> 
> I'd like to know what is special about the Queue initialization that it differs from that of deque's. Of course they offer different access patterns and have different implementation details, but at a higher level, both of them are containers/data structures and should behave consistently where they can.

I would consider this a bug. This behavior is inconsistent between the python Queue and C API version of Queue. Furthermore, `multiprocessing.Queue` implicitly checks type here:

```
class Queue(object):

    def __init__(self, maxsize=0, *, ctx):
        if maxsize <= 0:
            # Can raise ImportError (see issues #3770 and #23400)
            from .synchronize import SEM_VALUE_MAX as maxsize
        self._maxsize = maxsize
```

**Comment by picnixz** [comment]
Why do we have two different PRs for the same issue?

**Comment by anchal00** [comment]
> > > What will be different if you got a TypeError on Queue(maxsize=None) and not on q.put(3)?
> > 
> > 
> > I am not talking about type checkers at all. Sure they can detect this and warn the developer. All I am suggesting is that the Queue API can be made more cleaner
> > If we add extra type check there will be
> > 
> > 1. **Zero surprises** - Python lets the flawed initialization happen but complains only when it is being used. It would be logically more correct and would make sense if Queue doesn't get created with wrong attributes in the first place.
> >    The counter argument _'the behaviour would be exactly same and nothing would change'_ is right. To a program using a queue, it maybe wouldn't make much difference, but to the developers like me, it sure would. **It would behave exactly as it should**
> > 2. **Consistency** -
> > 
> > ```
> > >>> from collections import deque
> > >>> 
> > >>> dq = deque(maxlen=[10])
> > Traceback (most recent call last):
> >   File "<stdin>", line 1, in <module>
> > TypeError: an integer is required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'd like to know what is special about the Queue initialization that it differs from that of deque's. Of course they offer different access patterns and have different implementation details, but at a higher level, both of them are containers/data structures and should behave consistently where they can.
> 
> I would consider this a bug. This behavior is inconsistent between the python Queue and C API version of Queue. Furthermore, `multiprocessing.Queue` implicitly checks type here:
> 
> ```
> class Queue(object):
> 
>     def __init__(self, maxsize=0, *, ctx):
>         if maxsize <= 0:
>             # Can raise ImportError (see issues #3770 and #23400)
>             from .synchronize import SEM_VALUE_MAX as maxsize
>         self._maxsize = maxsize
> ```
> 
> To answer your question about `queue.Queue` vs `collections.deque` . They serve separate purposes. `queue.Queue` actually makes use of `deque`. `deque` is a double ended queue, whereas `Queue` is not. `Queue` supports the following Queue types: [Queue](https://docs.python.org/3/library/queue.html#queue.Queue), [LifoQueue](https://docs.python.org/3/library/queue.html#queue.LifoQueue), or [PriorityQueue](https://docs.python.org/3/library/queue.html#queue.PriorityQueue) — generally it's s meant to be used as a job queue for multi-threaded applications (multi-producer, multi-consumer), which is why you'll find additional methods `.task_done` and `.join` in `queue.Queue`. `multiprocessing.Queue` almost identical, but designed to be as a task queue that can be used between multiple processes.

Thanx for explaining the differences @pygeek. I agree.
I think I didn't phrase it clearly but I was hoping to get a explanation for the counter argument( that we dont need type check here ) clarifying 'Why Queue is an exception when it comes to enforcing type check on size limit".

**Comment by picnixz** [comment]
Actually, there is also a small distinction between the constructor the Queue and a deque. `deque` is implemented in C, and the error "an integer is needed" is actually thrown not after an explicit check but because a conversion failed:

https://github.com/python/cpython/blob/ca5108a46d5da3978d4bd29717ea3fbdee772e66/Modules/_collectionsmodule.c#L1712-L1737

On line 1730, you have "maxlen = PyLong_AsSsize_t(maxlenobj);" which raises a TypeError directly. Alternatively, we could have another error message ("TypeError: argument should be integer or None, not 'str'" for instance) with 

```diff
/*[clinic input]
@critical_section
@text_signature "([iterable[, maxlen]])"
_collections.deque.__init__ as deque_init

    deque: dequeobject
    iterable: object = NULL
-    maxlen as maxlenobj: object = NULL
+    maxlen as maxlenobj: Py_ssize_t(accept={int, NoneType}) = None

A list-like sequence optimized for data accesses near its endpoints.
[clinic start generated code]*/
```

**Comment by pygeek** [comment]
> > > > What will be different if you got a TypeError on Queue(maxsize=None) and not on q.put(3)?
> > > 
> > > 
> > > I am not talking about type checkers at all. Sure they can detect this and warn the developer. All I am suggesting is that the Queue API can be made more cleaner
> > > If we add extra type check there will be
> > > 
> > > 1. **Zero surprises** - Python lets the flawed initialization happen but complains only when it is being used. It would be logically more correct and would make sense if Queue doesn't get created with wrong attributes in the first place.
> > >    The counter argument _'the behaviour would be exactly same and nothing would change'_ is right. To a program using a queue, it maybe wouldn't make much difference, but to the developers like me, it sure would. **It would behave exactly as it should**
> > > 2. **Consistency** -
> > > 
> > > ```
> > > >>> from collections import deque
> > > >>> 
> > > >>> dq = deque(maxlen=[10])
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > > TypeError: an integer is required
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > I'd like to know what is special about the Queue initialization that it differs from that of deque's. Of course they offer different access patterns and have different implementation details, but at a higher level, both of them are containers/data structures and should behave consistently where they can.
> > 
> > 
> > I would consider this a bug. This behavior is inconsistent between the python Queue and C API version of Queue. Furthermore, `multiprocessing.Queue` implicitly checks type here:
> > ```
> > class Queue(object):
> > 
> >     def __init__(self, maxsize=0, *, ctx):
> >         if maxsize <= 0:
> >             # Can raise ImportError (see issues #3770 and #23400)
> >             from .synchronize import SEM_VALUE_MAX as maxsize
> >         self._maxsize = maxsize
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To answer your question about `queue.Queue` vs `collections.deque` . They serve separate purposes. `queue.Queue` actually makes use of `deque`. `deque` is a double ended queue, whereas `Queue` is not. `Queue` supports the following Queue types: [Queue](https://docs.python.org/3/library/queue.html#queue.Queue), [LifoQueue](https://docs.python.org/3/library/queue.html#queue.LifoQueue), or [PriorityQueue](https://docs.python.org/3/library/queue.html#queue.PriorityQueue) — generally it's s meant to be used as a job queue for multi-threaded applications (multi-producer, multi-consumer), which is why you'll find additional methods `.task_done` and `.join` in `queue.Queue`. `multiprocessing.Queue` almost identical, but designed to be as a task queue that can be used between multiple processes.
> 
> Thanx for explaining the differences @pygeek. I think I didn't phrase it clearly but I was hoping to get a explanation for the counter argument( that we dont need type check here ) clarifying 'Why Queue is an exception when it comes to enforcing type check on size limit".

There's no reason to continue with instantiating an object that we know will eventually fail, so just fail quickly. Also, there is an implicit type check in `multiprocessing.queues.Queue` during initialization, which is needed due to platform specific `SemLock` size limitations. Lastly, in C API `queue.Queue` is cast as a (`Py_ssize_t`)[https://peps.python.org/pep-0353/] as it should, but. that also means that the Python implementation is inconsistent with it's C API counterpart.

So the motivation really is twofold—fail fast, maintain parity between the two Queue classes and their corresponding C API implementations, which users expect to behave near identically.
