### ISSUE TITLE
Optimize random.choice when there is just one item

### ISSUE THREAD

**Issue by Alex-Izquierdo** [python/cpython#120320]
# Feature or enhancement

### Proposal:

When the sequence has only one item there is no need to process randomness. I wonder why such an optimization is not present in the core. 
```python
In [2]: seq = ["value"]

In [3]: import random

In [4]: def no_len(seq):
   ...:     return random.choice(seq)
   ...: 

In [5]: def with_len(seq):
   ...:     if len(seq) == 1:
   ...:         return seq[0]
   ...:     return random.choice(seq)
   ...: 

In [6]: %timeit no_len(seq)
230 ns ± 7.37 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [7]: %timeit with_len(seq)
45.5 ns ± 1.45 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by Zheaoli** [comment]
I would like to PR for this

**Comment by Alex-Izquierdo** [comment]
> I would like to PR for this

Hi @Zheaoli I have the plan to create a PR, just I wanted to make sure if the people agree with it. It seemed to me a very obvious thing and maybe there is a reason to not do it that I'm missing.

**Comment by iritkatriel** [comment]
Adding the check will slow down the case where len > 1, which is the most common case.
