### ISSUE TITLE
3.12.4 not recognised as gzip format

### ISSUE THREAD

**Issue by hannahcass** [python/cpython#120304]
# Bug report

### Bug description:

With upgrade from 3.12.3 to 3.12.4 the tar.gz is not anymore recognised as gzip format and is not installable. This error is solved if python-version is capped not to include 3.12.4 as latest. 

![Screenshot 2024-06-10 at 10 09 39](https://github.com/python/cpython/assets/60735042/a78669d7-91d5-44a2-8522-5ed11d9144c9)

OS: Ubuntu-22.04

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
This is a problem with GitHub Actions, please follow the issue at https://github.com/actions/setup-python/issues/886.

**Comment by firewave** [comment]
This is not an issue with the GitHub action. I downloaded the file manually and it is totally garbled. It consists mostly of `ef bf bd` patterns.
