### ISSUE TITLE
PYTHON_BASIC_REPL is ignored by interactive inspect

### ISSUE THREAD

**Issue by eryksun** [python/cpython#120346]
# Bug report

### Bug description:

The code in `pymain_repl()` in "Modules/main.c" needs to check `_Py_GetEnv(config->use_environment, "PYTHON_BASIC_REPL")`. Otherwise running with `-i`, or with `PYTHONINSPECT` set in the environment, ends up running the new REPL instead of the basic REPL after the command or script finishes.

https://github.com/python/cpython/blob/02c1dfff073a3dd6ce34a11b038defde291c2203/Modules/main.c#L545-L550

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-120349
* gh-120351

**Comment by pablogsal** [comment]
On it

**Comment by pablogsal** [comment]
Fixed!
