### ISSUE TITLE
json.dumps() couldn't correctly convert a dictionary's key if the key's type is Integer class.

### ISSUE THREAD

**Issue by clockzhong** [python/cpython#120482]
# Bug report

### Bug description:

```python
import json
# Create a dictionary which key is integer:
adict = {1:"one", 2:"two"}
#convert to json string
json_string = json.dumps(adict)
print(json_string)
#output:
#{"1": "one", "2": "two"}
# the output is wrong
bdict = json.loads(json_string)
#This assert() should be True, but it failed, because  json.dumps() changed the 1 to "1", and 2 to "2", this is a wrong work
assert(list(adict)==list(bdict))
```
This is an old bug, I've checked python3.7 and 3.10/3.12, all of them have this bug. There should be a small logic mistake in our cpython code, I discovered this bug by accident in my project, and located the root cause in the cpython's core design. 

Thanks!

### CPython versions tested on:

3.8, 3.10

### Operating systems tested on:

Linux

**Comment by OTheDev** [comment]
In JSON, all object keys must be strings. The behavior you observe above is intentional and not a bug.

**Comment by sobolevn** [comment]
I agree with @OTheDev, please see the JSON spec: https://www.json.org/json-en.html

**Comment by clockzhong** [comment]
> In JSON, all object keys must be strings. The behavior you observe above is intentional and not a bug.

Thanks! @OTheDev , Perfect explanation! I agree, yes, this is not a bug, it's a feature defined by JSON Spec.
