### ISSUE TITLE
ability to use a kind of contextmanager with loop inside

### ISSUE THREAD

**Issue by Bfault** [python/cpython#120459]
# Feature or enhancement

### Proposal:

```python
@contextmanager
def try_catch_checkpoints(checkpoints, errors_list):
  for checkpoint in checkpoints:
    try:
      yield checkpoint
      break
    except errors_list as e:
      logger.warning(f"...")
  else:
    raise "..."

...
with try_catch_checkpoints(checkpoints, (ValueError)) as checkpoint:
  load_from_checkpoint(checkpoint)

...
with try_catch_checkpoints(checkpoints, (AnotherError)) as checkpoint:
  load_things(checkpoint)
```

Won't work due to several calls of `yield` (limited with `with` behavior)

it could work with using decorator and function but making functions for only this kind can lead to a dirty code.
I think with contextlib maybe there is a way to make it work 

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
PEP-343 introduced the `with` statement. A predecessor was PEP-340, which did support looping. I suggest you look at PEP-340, and why it was rejected.

I'm going to close this. The correct place to propose and discuss a new feature is https://discuss.python.org/c/ideas/6. I encourage you to open an issue there, after reading PEP-340. Be prepared to defend your proposal against the reasons that 340 was rejected.

Personally, I was excited for the looping allowed by PEP-340, and was disappointed that it was rejected. I'd look forward to another discussion of it.
