### ISSUE TITLE
Some classes which inherit `socketserver.TCPServer ` should override `allow_reuse_port`

### ISSUE THREAD

**Issue by idankap** [python/cpython#120485]
# Bug report

### Bug description:

In [#30072](https://github.com/python/cpython/pull/30072) there was a change to `socketserver.TCPServer` which added a new variable `allow_reuse_port` to support the usage of `SO_REUSEPORT` along with `SO_REUSEADDR`. The problem is that the classes which inherit from `socketserver.TCPServer` and override `allow_reuse_address` weren't updated to include the override of the new variable `allow_reuse_port`.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-120488

**Comment by aisk** [comment]
If we set `SO_REUSEPORT` to `True`, one server like a HTTP server or a XMLRPC Server can bind to the same port, for example, `localhost:1234`. And the kernel may dispatch the request to different server process randomly.

This is a perplexing behavior to people who didn't know about it, for example, when a user started a HTTP service process, and modified the source code, and forgot there was already a process there, then started a new one. Then he will see his change works randomly.

So I think it's not a good idea to set the `SO_REUSEPORT` on.

**Comment by nineteendo** [comment]
Can this be closed?
