### ISSUE TITLE
Improve documentation about private name mangling

### ISSUE THREAD

**Issue by picnixz** [python/cpython#120452]
Private mangling is quite common if you want to emulate a "private" interface without leaving the possibility of the interface being considered "protected" (in the C++/Java sense). I've seen a few constructions in the standard library that are using this so I think it should be clear (visually speaking) in the docs as well.

I tend to forget about the rule of "no transformation if name only consists of underscores" or "underscores stripped + 1 underscore", so I think it's good to highlight them.

### Linked PRs
* gh-120451
* gh-121715
* gh-121716

**Comment by Eclips4** [comment]
Isn't it covered by the https://docs.python.org/3/reference/expressions.html#expressions (Identifiers (Names) section)?

**Comment by picnixz** [comment]
Yes it is, but I wanted to improve the wording actually.

**Comment by picnixz** [comment]
Completed in #120451.
