### ISSUE TITLE
Remove unused imports from the stdlib

### ISSUE THREAD

**Issue by vstinner** [python/cpython#120417]
Using pyflakes or ruff, I found unused imports and I created this issue to remove them.

### Linked PRs
* gh-120420
* gh-120421
* gh-120429
* gh-120454
* gh-120461
* gh-120574
* gh-120622
* gh-120623
* gh-120626
* gh-120627
* gh-120628
* gh-120629
* gh-120630
* gh-120631
* gh-120632
* gh-120679
* gh-120680

**Comment by terryjreedy** [comment]
Victor, can this be closed?

**Comment by vstinner** [comment]
Please keep it open. I would like to visit some options for ssl and ctypes. And check imports in tests.

**Comment by vstinner** [comment]
The `#noqa: F401` comment was discussed in https://github.com/python/cpython/pull/120421. In short, it's a standard linter command to ignore "imported but unused" warning on the current line.

**Comment by encukou** [comment]
Could you link to the standard?

**Comment by vstinner** [comment]
> Could you link to the standard?

I don't think that there is a written standard. It's just that multiple linters adopted the same format. Examples:

* Flake8: https://flake8.pycqa.org/en/7.0.0/user/violations.html#in-line-ignoring-errors
* Ruff: https://docs.astral.sh/ruff/linter/#error-suppression
* pycodestyle: https://pycodestyle.pycqa.org/en/latest/intro.html#error-codes
* https://stackoverflow.com/questions/45346575/what-does-noqa-mean-in-python-comments

**Comment by encukou** [comment]
None of those documents explains what `F401` means (though some use it as an example).
So maybe explain it in a comment rather than use a link?

**Comment by hugovk** [comment]
Flake8 checks lint rules from plugins, each with its own alphabetical prefix. The F codes are from Pyflakes:

> F401: `module` imported but unused

https://flake8.pycqa.org/en/latest/user/error-codes.html#error-violation-codes

In more words in the Ruff docs:

> F401 unused-import: `{name}` imported but unused; consider using `importlib.util.find_spec` to test for availability

https://docs.astral.sh/ruff/rules/#pyflakes-f

**Comment by vstinner** [comment]
Ok, I'm now done with my batch of changes to remove unused imports.

If someone wants to automate the detection of unused imports, I suggest to open a new issue. Right now, in total, ruff check|grep F401 returns 173 lines. I didn't add `#noqa:F401` to these lines.
