### ISSUE TITLE
[tests] mangled names are incorrectly introspected by `test_pyclbr.py` 

### ISSUE THREAD

**Issue by picnixz** [python/cpython#120449]
# Bug report

### Bug description:

This is something I encountered when implementing #120422. It should not affect the `pyclbr.py` module itself since introspection is achieved without any loading (so the names are correctly picked).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-120450
* gh-120700
* gh-120701

**Comment by nineteendo** [comment]
Could you close this?

**Comment by picnixz** [comment]
(I was waiting for the backports to be merged but I missed the notification)

**Comment by nineteendo** [comment]
It's fine, you can occasionally go through your issues here: https://github.com/python/cpython/issues/created_by/picnixz
Or your pull requests here: https://github.com/python/cpython/pulls/picnixz
