### ISSUE TITLE
Link to `pprint` from `json.dump[s]()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120415]
# Documentation

I didn't know `pprint.pformat(..., width=1)` & `pprint.pprint(..., width=1)` existed, and always used `json.dumps(..., indent=4)` for pretty printing of Python objects. But the latter doesn't support all Python objects and often leads to too much whitespace:

```json
[
    [
        1
    ],
    [
        2
    ],
    [
        3
    ]
]
```

`pprint()` works way better here:

```python
>>> from pprint import pprint
>>> pprint([[1], [2], [3]], width=1)
[[1],
 [2],
 [3]]
```

### Linked PRs
* gh-120416

**Comment by serhiy-storchaka** [comment]
It has nothing to do with JSON, I do not think that such link is relevant. It can even cause confusion, because the subset of Python syntax is compatible with JSON, this can look like suggestion to use `pprint` to produce JSON.

**Comment by nineteendo** [comment]
JSON is not only used for storing data, it's also used for displaying information in human readable form, we even have an example of that. I even messed around with custom JSON encoders while there's a module that supports printing them out of the box. And like shown above, using it to print a list of lists doesn't work well.

**Comment by ericvsmith** [comment]
I think the number of people who use json to print out python objects, who would also read the json documentation and find a pprint reference to do something sort of (but not really) related is very, very small. I don't think this should be added.

**Comment by nineteendo** [comment]
Let me know if you change your mind.
