### ISSUE TITLE
There may be a bug or vulnerability in the assignment of a List here

### ISSUE THREAD

**Issue by KiloMaster** [python/cpython#120404]
# Bug report

### Bug description:

Here is the case ;  when i assign value to list， things is out of my control. 
when i just assign value to a[2][1]， Assignment of list happend on other index.
 I don't know if the design is like this or if there are bugs or vulnerabilities here.

In China, my email cannot be reached security@python.com. If there are security issues, please help me contact and forward relevant information to the security team.
```python
# Add a code block here, if required
import sys
print(sys.version)
#3.6.8 (default, Nov 14 2023, 16:29:52)
#[GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
a=[[0,0]]*6
print(a)
#[[0, 0], [0, 0], [0, 0], [0, 0], [0, 0], [0, 0]]
a[1]=[1,1]
print(a)
#[[0, 0], [1, 1], [0, 0], [0, 0], [0, 0], [0, 0]]
a[2][1]=2
print(a)
#[[0, 2], [1, 1], [0, 2], [0, 2], [0, 2], [0, 2]]
```
![图片](https://github.com/python/cpython/assets/13516855/acecc0c9-63d6-4439-b5e3-bae188d007ee)

### CPython versions tested on:

3.8

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
This is intended behavior, see https://docs.python.org/3/faq/programming.html#how-do-i-create-a-multidimensional-list for more information.
