### ISSUE TITLE
Simplify consumers by making `queue.Queue` an iterable

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120499]
# Feature or enhancement

### Proposal:

```python
class Iterator:
    def __init__(self, queue):
        self.queue = queue

    def __iter__(self):
        return self

    async def __next__(self):
        try:
            return self.queue.get_nowait()
        except (Empty, ShutDown):
            raise StopIteration

class Queue:
    ...
    def __iter__(self):
        return Iterator(self)
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #119154

### Linked PRs
* gh-120503

**Comment by sobolevn** [comment]
Sorry, I might be missing something obvious, but can you please explain a motivation behind this change?

**Comment by zware** [comment]
@nineteendo, *please* stop editing your posts after submission.  Edit *before* you submit, and don't submit until you aren't going to change it again.  There is not a window in which substantial edits are okay; email notifications will only ever contain the original version, which at this point is much different than what is now here.

**Comment by nineteendo** [comment]
> Sorry, I might be missing something obvious, but can you please explain a motivation behind this change?

Guido suggested this here: https://github.com/python/peps/pull/3782#discussion_r1603216889

> Adding `__aiter__` seems fairly uncontroversial now we have `shutdown`. It can just be discussed on Discourse. I'd recommend adding `__iter__` to non-asyncio `queues.Queue` as well, just like we added `shutdown` to both.

I've made a separate issue, because the title didn't match.

---

> _please_ stop editing your posts after submission

Reverted. I realised we didn't need a separate class, so that's why I use generator in the PR.

> Edit _before_ you submit, and don't submit until you aren't going to change it again.

Would you prefer me to create a new issue then?

**Comment by sobolevn** [comment]
@nineteendo thank you! Please, next time include this context in the issue :)

**Comment by zware** [comment]
> Would you prefer me to create a new issue then?

No, I would prefer that you *stop editing your posts* :).  Not even to revert previous edits, just no more edits.

My suggestion to edit before submission is intended for any post you make, not just new issues.  Make sure you're saying what you want to say on the first try; there's no benefit to saying the wrong thing quickly when you have unlimited time to get it right.  If your understanding of something changes, say so in a new message.

**Comment by nineteendo** [comment]
> My suggestion to edit before submission is intended for any post you make, not just new issues.

In the future I'll try to create an issue and PR on my own fork first. I don't make significant changes to regular comments (just fixing a typo or suggestion).

**Comment by nineteendo** [comment]
@Zac-HD, `multiprocessing.Queue.close()` doesn't prevent other processes from putting items on the queue.
So, I'm not sure how we can make this work without a sentinel for every reading process.
