### ISSUE TITLE
Add ability to use `weakref.WeakMethod` with `weakref.WeakSet`

### ISSUE THREAD

**Issue by alanhdu** [python/cpython#120466]
# Feature or enhancement

### Proposal:

Right now, there doesn't seem to be a great way of adding a `weakref.WeakMethod` to a `WeakSet`. If you try, yo uget something like:

```python
import weakref

class C:
    def method(self): pass

ci = C()

print("weakMethod:", weakref.WeakMethod(ci.method))   # works
print("s1:", weakref.WeakSet([C.method]))    # works
print("s2:", weakref.WeakSet([ci.method]))   # empty!
print("s3:", weakref.WeakSet([weakref.WeakMethod(ci.method)]))  # empty!
```

At least on Python 3.10, I can work around this by doing something like:
```python
weakset = weakref.WeakSet()
weakset.data.add(
    weakref.WeakMethod(ci.method, weakset._remove)
)
```

which AFAICT *does* work correctly, but the use of a private variables makes me uneasy.

xref https://stackoverflow.com/questions/78101036/weakmethod-in-weakset

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by rhettinger** [comment]
@pitrou Thoughts?

**Comment by pitrou** [comment]
No idea. I've never added methods to a weak set, let alone weak methods :-)

**Comment by rhettinger** [comment]
@alanhdu Why would you want to do this?   The point of a WeakSet is to create and manage weak references for you.

I don't think weak references aren't supposed to nest:

```
>>> class A:
...     pass
... 
>>> a = A()
>>> weakref.ref(weakref.ref(a))
Traceback (most recent call last):
    ...
    weakref.ref(weakref.ref(a))
TypeError: cannot create weak reference to 'weakref.ReferenceType' object
```

I guessing that you headed this direction because you couldn't get `s2` to work.  However, the set is only empty because the bound method is no longer alive.  But you can easily keep it alive:

```
import weakref

class C:
    def method(self): pass

ci = C()

print("weakMethod:", weakref.WeakMethod(ci.method))
print("s1:", weakref.WeakSet([C.method]))
bm = ci.method
print("s2:", weakref.WeakSet([bm]))

```

**Comment by rhettinger** [comment]
Marking this a closed because we don't have a good reason to move forward with it.

If a good reason and path forward does arise, feel free to reopen.

**Comment by alanhdu** [comment]
> Why would you want to do this? The point of a WeakSet is to create and manage weak references for you.

Sorry -- to clarify, what I want to do is to allow a `WeakSet` to contain a reference to a method, but where the weak reference is tied to the *object*'s lifetime and not the methods (which IIUC, is what `weakref.WeakMethod` does).

The more specific issue is that I have a `Cache` object that represents some local file system state. I'd like a method to delete all local state from all objects. I originally implemented this using:
```
_REGISTRY = WeakSet()   # some global variable

def clear_all_caches():
    for func in _REGISTRY:
        func()

class Cache:
    def __init__(self):
        _REGISTRY.add(self.cleanup)
    def cleanup(self):
         # some user-defined cleanup method
```

I think the suggestion you have does not do the same thing -- the reference is tied to `bm`'s lifetime rather than `ci`'s lifetime.

I can solve this with the workaround I posted (passing `weakset._remove` to the `WeakMethod` constructor), or by making my registry register the cache objects (`_REGISTRY.add(self)`) and adding a `if isinstance(func, Cache)` branch in the `clear_all_caches` code. Both seem fine to me, but I thought it'd be nice if there was a documented way of adding a weak method to a weak set.
