### ISSUE TITLE
Confusing code snippet in `type.Literal` docs

### ISSUE THREAD

**Issue by nhstanley** [python/cpython#120561]
# Documentation

There is a confusing use of `type` in a code snippet for `typing.Literal`). [Link to section.](https://docs.python.org/3/library/typing.html#typing.Literal) Here is the code snippet in question, reproduced here:

```python
def validate_simple(data: Any) -> Literal[True]:  # always returns True
    ...

type Mode = Literal['r', 'rb', 'w', 'wb']
def open_helper(file: str, mode: Mode) -> str:
    ...

open_helper('/some/path', 'r')      # Passes type check
open_helper('/other/path', 'typo')  # Error in type checker
```

Line 4 is the problematic one. At first when I saw this, I thought that maybe the `type` function can also serve as a keyword/statement, like the old `print` statement in python2. However, it throws a SyntaxError, as expected if `type` is only a function.

Re-writing it slightly, this code is actually runnable and checkable with mypy:

```python
from typing import Literal, Any
def validate_simple(data: Any) -> Literal[True]:  # always returns True
    ...

Mode = Literal['r', 'rb', 'w', 'wb']
def open_helper(file: str, mode: Mode) -> str:
    ...

open_helper('/some/path', 'r')      # Passes type check
open_helper('/other/path', 'typo')  # Error in type checker
```

While I realize not all code snippets are meant to be executable, I think this one is confusing. If others agree, I'd be happy to write a PR with the updated snippet.

**Comment by JelleZijlstra** [comment]
The `type` keyword is new syntax added in Python 3.12 (PEP-695). Mypy does not support it yet, but it will soon.
