### ISSUE TITLE
Error flagged in a different statement than the one where the actual error happens

### ISSUE THREAD

**Issue by zshameel** [python/cpython#120536]
# Bug report

### Bug description:

In the following code example, in line 5 'numbers' (list) is assigned to 'max' (int) when I actually intended to assign 'number' (int). However, the error is flagged in line 4 (**TypeError: '>' not supported between instances of 'int' and 'list'**)
Line 4 is correct, an int is compared with an int with the '>' operator, the actual error is in line 5 where a list is assigned to an int. It should flag the error in line 5.

```
# Finding largest number in a list 
1 numbers = [199, 100, 300, 200, 400, 10, 4000, 200] 
2 max = 0
3 for number in numbers:
4    if number > max:
5        max = numbers
6 print (max)

```

### CPython versions tested on:

3.9

### Operating systems tested on:

macOS

**Comment by JelleZijlstra** [comment]
Python is a dynamically typed language. Assigning a value of a different type is not an error.

You may want to use a static type checker (such as mypy or pyright) to catch issues like this.

**Comment by zshameel** [comment]
Hi @JelleZijlstra, assigning a value of a different type is not an error, of course. But in that case, the Python should not throw any errors at all. I raised this issue to highlight the fact that the error is thrown in the previous statement which is misleading.

**Comment by JelleZijlstra** [comment]
It's thrown in that statement on the next iteration of the loop.

**Comment by zshameel** [comment]
It took some time for me to understand this. Thanks @JelleZijlstra .
