### ISSUE TITLE
There is no `basic_install.zsh` script in the root project directory

### ISSUE THREAD

**Issue by shoyu-ramen** [python/cpython#120515]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by sobolevn** [comment]
Sorry, what is `basic_install.zsh`? There are no references to it in CPython's repo: https://github.com/search?q=repo%3Apython%2Fcpython%20basic_install.zsh&type=code
