### ISSUE TITLE
Skip `test_free_threading` with GIL

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120659]
# Feature or enhancement

### Proposal:

`test_free_threading` shouldn't run when the GIL is enabled. It takes 2 minutes on the default build, making it the slowest test in the suite.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

- #119599
- #120565

### Linked PRs
* gh-120660
* gh-120694

**Comment by blhsing** [comment]
> `test_free_threading` shouldn't run when the GIL is disabled.
I think you mean to say "should only run" rather than "shouldn't run".

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/360f14a493d8461d42dc646be40b4b6fb20db57a.
