### ISSUE TITLE
Remove tear-off menu feature in turtledemo

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#120633]
https://github.com/python/cpython/issues/58092 (BPO 13884) removed tear-off menu in IDLE, but it's still there in the turtledemo window. 

`tearoff=0` will disable tear-off vertical menu (it's even Windows 8's close window `x` style😨)

Last, I adjusted the scroll bar for previewing `py` files to the right. The original left side didn't fit the usage👀

There is no mention of tearoff in the Python docs, it seem like an outdated feature (but it is enabled by default)🤔

---
### Before
![2024-06-17 194554](https://github.com/python/cpython/assets/71213467/2a363f41-201b-484b-9cfb-2b8c86053e92)

### After
![2024-06-17 193430](https://github.com/python/cpython/assets/71213467/c1a4c619-2911-4e34-a329-6241643a7749)

### Linked PRs
* gh-120634
* gh-120725

**Comment by Wulian233** [comment]
CC: @terryjreedy

**Comment by terryjreedy** [comment]
I am not sure how our backcompatibility rule apply to turtledemo, so I did not backport, at least not yet.
