### ISSUE TITLE
Unexpected multiple module import

### ISSUE THREAD

**Issue by Guilty13** [python/cpython#120620]
# Bug report

### Bug description:

Seems like I found unexpected way to double-import module. To reproduce:
Dir structure:

module_dir -> first.py
second.py
start.py

**first.py**
```
print('First: do some init')

def start():
    print('Start first')
    import second
    second.start()

def some_function():
    print('Some public function')
```

**second.py**
```
import sys
sys.path.append('module_dir')
import first as other_module

def start():
    print('Start second')
    other_module.some_function()
```

**start.py**
```
import module_dir.first as first

if __name__ == "__main__":
    first.start()
```

Looks like "sys.path.append" causes "import" see module "first" as non-loaded module.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by Guilty13** [comment]
Output:
```
First: do some init
Start first
First: do some init
Start second
Some public function
```

**Comment by ronaldoussoren** [comment]
This is expected behaviour, "module_dir.first" and "first" are two different modules, even if they happen to resolve to the same file on the filesystem.

**Comment by Guilty13** [comment]
Thank you for asnwer!
