### ISSUE TITLE
[C API] Move private PyCode and PyOptimizer API to the internal C API

### ISSUE THREAD

**Issue by vstinner** [python/cpython#120642]
The private PyCode and PyOptimizer APIs use "unnamed structs/unions" which are not allowed in ISO C99: see https://github.com/python/cpython/issues/120293.

I propose to move private PyCode and PyOptimizer APIs to the internal C API.

6 PyUnstable optimizer functions are moved to the internal C API:

* PyUnstable_Replace_Executor()
* PyUnstable_SetOptimizer()
* PyUnstable_GetOptimizer()
* PyUnstable_GetExecutor()
* PyUnstable_Optimizer_NewCounter()
* PyUnstable_Optimizer_NewUOpOptimizer()

### Linked PRs
* gh-120643
* gh-121043
* gh-121644
* gh-121729

**Comment by ronaldoussoren** [comment]
These functions were added in #104584, and may be intended as an API used by other JITs as well (possibly with some changes).

**Comment by vstinner** [comment]
> These functions were added in https://github.com/python/cpython/issues/104584, and may be intended as an API used by other JITs as well (possibly with some changes).

These functions are still exported, but the few other JITs would have to update their code to include ``pycore_optimizer.h``. Is it ok?

**Comment by ronaldoussoren** [comment]
> > These functions were added in #104584, and may be intended as an API used by other JITs as well (possibly with some changes).
> 
> These functions are still exported, but the few other JITs would have to update their code to include `pycore_optimizer.h`. Is it ok?

I don't know. @markshannon added these function and may have an opinion on this.

**Comment by vstinner** [comment]
@iritkatriel @brandtbucher @Fidget-Spinner: Do you know anyone using these unstable functions? They were added to Python 3.13. I propose to move them to <pycore_optimizer.h>. In short, are you ok with https://github.com/python/cpython/pull/120643 ?

I prefer to move private APIs to the internal C API, and the API is causing C99 compatibility issues in strict mode (pedantic).

**Comment by markshannon** [comment]
I think it is fine to remove them, as no one is using it.
If there is interest in the future for plug in optimizers, we would probably want to offer a quite different API that allowed plugins to add additional passes, rather replace the whole of tier 2.

**Comment by vstinner** [comment]
> I think it is fine to remove them, as no one is using this API.

Oh ok. I updated my PR to remove the 6 PyUnstable functions from the public C API. Most of them have to be kept for tests, but I renamed them and moved them to the internal C API.
