### ISSUE TITLE
Allow EOF to exit pdb commands definition

### ISSUE THREAD

**Issue by gaogaotiantian** [python/cpython#120606]
# Feature or enhancement

### Proposal:

In `pdb` `commands` command, the user can use `exit` or a resume execution to exit the commands definition. However, EOF seems a very reasonable and intuitive way to exit as well. It's technically not a bug because we never said it should, but it's annoying and easy to fix.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-120607

**Comment by nineteendo** [comment]
Can this be closed?
