### ISSUE TITLE
 Protect multi-line macros expansions in `_test*.c` files

### ISSUE THREAD

**Issue by picnixz** [python/cpython#120674]
# Feature or enhancement

### Proposal:

In `Modules/_testbuffer.c` and `Modules/_testcapimodule.c`, there are some expansions that are not protected, although their usage is correct.

This issue is in continuation with https://github.com/python/cpython/issues/119981#issuecomment-2145636560 and #120017. There are other places where macro expansions are not protected, so I'll work on that when I've some free time (those PRs are quite easy to review and to implement IMO).

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-120675

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/7c5da94b5d674e112dc77f6494463014b7137193.
