### ISSUE TITLE
New REPL omits local variables when running ./python -i script.py

### ISSUE THREAD

**Issue by vstinner** [python/cpython#120798]
# Bug report

Example `script.py`:

```py
x = 1
```

Output:

```py
$ ./python -i script.py
>>> x
NameError: name 'x' is not defined
```

Using the basic REPL, it works as expected:

```py
$ PYTHON_BASIC_REPL=1 ./python -i script.py
>>> x
1
```

cc @pablogsal @ambv @lysnikolaou

**Comment by eryksun** [comment]
This is a duplicate of #120678.

**Comment by vstinner** [comment]
> This is a duplicate of https://github.com/python/cpython/issues/120678.

Oh right! I close my issue.
