### ISSUE TITLE
a bit better example in pathlib docs - maybe include example path that involves file in a folder(s)?

### ISSUE THREAD

**Issue by matkoniecz** [python/cpython#120794]
# Documentation

See https://docs.python.org/3/library/pathlib.html#concrete-paths

`Path('setup.py')` and `PosixPath('/etc')` and `WindowsPath('c:/Program Files/')` both have single level only.

Would it be OK to have example with file in a folder? say `PosixPath('/etc/hosts')` (if that is correct way to pass more complex paths to constructor...)

Would PR changing this would be welcome and have chances to be reviewed?

### Linked PRs
* gh-122887
* gh-122895
* gh-122896

**Comment by barneygale** [comment]
A few more examples wouldn't hurt, e.g. for `PosixPath` we could show:

```python
>>> PosixPath('/etc/hosts')
PosixPath('/etc/hosts')
>>> PosixPath('/home', 'mat', '.profile')
PosixPath('/home/mat/.profile')
```

Happy to review a PR

**Comment by barneygale** [comment]
Sorted. Thanks again for reporting, @matkoniecz!
