### ISSUE TITLE
`datetime.strftime("%Y")` is not padding correctly

### ISSUE THREAD

**Issue by martinvuyk** [python/cpython#120713]
# Bug report

### Bug description:

[docs](https://docs.python.org/3/library/datetime.html#strftime-strptime-behavior) say:
```text
%Y

Year with century as a decimal number.

0001, 0002, …, 2013, 2014, …, 9998, 9999
```

but this is what is happening

```python
from datetime import datetime

print(datetime(9, 6, 7).strftime("%Y-%m-%d")) # 9-06-07
print(datetime(99, 6, 7).strftime("%Y-%m-%d")) # 99-06-07
print(datetime(999, 6, 7).strftime("%Y-%m-%d")) # 999-06-07
```

### CPython versions tested on:

3.10

### Linked PRs
* gh-120820
* gh-121144
* gh-121145
* gh-122408
* gh-122409
* gh-135933
* gh-136387

**Comment by blhsing** [comment]
Reproducible on 3.10 but not on 3.11+.

**Comment by blhsing** [comment]
> I wonder whether this is a documentation issue or the output is platform depending.

Ah, so the issue is Linux-specific. When I reproduced the OP's issue on 3.10 I was doing it in Linux, while when I tested the code in 3.11 and 3.13 it was in Windows and the issue was not reproduced. Now I realized it has nothing to do with version but just platform.

**Comment by serhiy-storchaka** [comment]
The limitation for year >= 1000 was removed in bpo-11930 (gh-56139). But there were various problems with the newly added test `test_strftime_y2k`, it required several corrections.

For now, we cannot guarantee the result for %Y (and %G) with year < 1000. It is especially bad since `strptime()` _requires_ the year to be 4 digits.

**Comment by blhsing** [comment]
Since `datetime.strftime` already uses a wrapper function to handle format specifiers not conforming to the C `strftime`, I think it's reasonable to add this translation of `%Y` to `%4Y` there as needed by the platform.

**Comment by serhiy-storchaka** [comment]
Yes, but the problem is that %4Y is a glibc extension. There are platforms that return non-4-digit number and do not support %4Y. If we are going to guarantee 4 digits, the workaround may be much more complex.

**Comment by blhsing** [comment]
> Yes, but the problem is that %4Y is a glibc extension. There are platforms that return non-4-digit number and do not support %4Y. If we are going to guarantee 4 digits, the workaround may be much more complex.

With PR #120820 I've made sure that the translation is only used when explicitly supported by the platform so that it is at least an improvement and not a regression in any case. I did just revert my changes to the unit test to allow an outlier platform to pass the test.

**Comment by blhsing** [comment]
> Yes, but the problem is that %4Y is a glibc extension. There are platforms that return non-4-digit number and do not support %4Y. If we are going to guarantee 4 digits, the workaround may be much more complex.

On second thought, guaranteeing 4 digits is actually not complex since we can simply format the year with `"%04d"` using `sprintf`, which works on all platforms.

I've updated the PR accordingly so that a 4-digit year with century can now be guaranteed.

**Comment by serhiy-storchaka** [comment]
PR #120820 looks good if this is what we want to get. @pganssle, what are your thoughts?

Note that %G also needs a fix.

**Comment by blhsing** [comment]
> Note that %G also needs a fix.

Good point. I've updated the PR to account for `'%G'` then. Thanks.

**Comment by picnixz** [comment]
@serhiy-storchaka @blhsing I'm not sure why but we are seeing failures on JIT for the `test_strftime_y2k` on emulated Linux. Is it because emulated Linux have (yet) another weird case of glibc?

**Comment by blhsing** [comment]
> I'm not sure why but we are seeing failures on JIT for the `test_strftime_y2k` on emulated Linux. Is it because emulated Linux have (yet) another weird case of glibc?

Thanks for the heads-up  It is weird indeed that this can happen since according to the build log the configure script did detect that the platform would not 0-pad a century so the handler for `%Y` would format the year itself with `snprintf` using the `"%04ld"` format string.

Since this happens only on `aarch64` perhaps there is indeed some peculiarity of `snprintf` in the glibc of that platform.

Will try debugging this on a Mac later.

> Also, the reason we reverted the commits on 3.12 and 3.13 was because it was more of a feature than a bugfix?

It's a bug fix but was found to be incomplete, due to issue #122272.

**Comment by serhiy-storchaka** [comment]
Please open a new issue and provide more details.

**Comment by picnixz** [comment]
See https://github.com/python/cpython/issues/123681.
