### ISSUE TITLE
psutil fails (segfault) on macOS in the free-threaded (python3.13t) version

### ISSUE THREAD

**Issue by pkoning2** [python/cpython#120717]
# Bug report

### Bug description:

I used pip to install psutil on python 3.13 0b2, both the regular and the "t" version.  The regular one works; the t one fails at `import psutil` with a segfault.

Mac OS 12.7.5 on Apple M1 (ARM64).

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by gaogaotiantian** [comment]
Any extensions that uses more than Python would need to adapt to free-threading if they want to onboard. It's impossible for CPython to ensure all the C extensions work without GIL. So this should be an issue for `psutil` :)

**Comment by hugovk** [comment]
Please report to https://github.com/giampaolo/psutil/issues

**Comment by colesbury** [comment]
I think this is due to issues with the Python installers, not `psutil`.

**Comment by colesbury** [comment]
Depends on:
- https://github.com/python/cpython/pull/120889

**Comment by ned-deily** [comment]
Based on the descriptions here and in the linked issues, the original problem has been resolved. With current versions of Python 3.13 (python.org macOS 3.13.0b4), pip, and psutil, psutil no longer segfaults using the free-threaded variant.
