### ISSUE TITLE
Simplify chained comparison

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#120862]
This will feel more logical. It's a simple change that doesn't really change anything. So I skipped the news

![2024-06-18 201202](https://github.com/python/cpython/assets/71213467/381b24df-fc5b-4b8c-b984-90c026e66a5f)

### Linked PRs
* gh-120863

**Comment by terryjreedy** [comment]
PR replaces `cmp1 and cmp2` where both compares involve a particular variable with changed compare with variable in middle.

What checker found these?

**Comment by nineteendo** [comment]
Oh, can we close this?
