### ISSUE TITLE
CANT FIND THE FUCKING DOWNLOAD BUTTON

### ISSUE THREAD

**Issue by yourmomishot1234** [python/cpython#120819]
# Bug report

### Bug description:

CANT FIND THE FUCKING DOWNLOAD BUTTON

### CPython versions tested on:

3.10

**Comment by Eclips4** [comment]
You can download python at python.org.
Please, be patient next time.
Also, this repository is intended as a cpython bug tracker, please, ask for help there: https://discuss.python.org/c/users/7

**Comment by sobolevn** [comment]
<img width="1352" alt="Снимок экрана 2024-06-21 в 13 08 25" src="https://github.com/python/cpython/assets/4660275/4958ea54-f127-48f6-aa22-754f005c3421">

It is right there.
