### ISSUE TITLE
Typo in the documentation of the `cmd` parameter of `ftplib.FTP.retrbinary()`

### ISSUE THREAD

**Issue by g-pichler** [python/cpython#120823]
# Documentation

The documentation of the `cmd` parameter of `ftplib.FTP.retrbinary()` reads 
> **cmd** ([str](https://docs.python.org/3.14/library/stdtypes.html#str)) – An appropriate `STOR` command: `"STOR filename"`.

I suspect, this was copy-and-pasted from `ftplib.FTP.storbinary()`. I believe it should read

**cmd** ([str](https://docs.python.org/3.14/library/stdtypes.html#str)) – An appropriate `RETR` command: `"RETR filename"`.

### Linked PRs
* gh-120869
* gh-121694
* gh-121697
* gh-121706
* gh-121707

**Comment by terryjreedy** [comment]
Agreed. The retrbinary [doc entry](https://docs.python.org/3/library/ftplib.html#ftplib.FTP.retrbinary) does not match its docstring, which includes "cmd: A RETR command."   [RFC959](https://datatracker.ietf.org/doc/html/rfc959) confirms that this has the same format at the STOR command:  `"RETR <SP> <pathname> <CRLF>"`.  Would you like to make the PR?  (If not, I or someone else will.)  The blurb could just say `The ftplib.FTP.retrbinary command arg should be a "RETR" command, not a "STOR command".`.
