### ISSUE TITLE
python syntax paser error, cant run print after a comment

### ISSUE THREAD

**Issue by pokq** [python/cpython#120931]
# Bug report

### Bug description:

```python

# ("%")
print('test')


```

![屏幕截图 2024-06-24 103130](https://github.com/python/cpython/assets/115908818/f6755a0b-8481-44a8-a6a8-c4b43b7fb8f7)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
In standard Python repl, a line beginning with '%' after the '>>>' prompt is a syntax error, so I presume you well using IPython or something similar that intercepts and interprets `%Run`.

**Comment by pokq** [comment]
> In standard Python repl, a line beginning with '%' after the '>>>' prompt is a syntax error, so I presume you well using IPython or something similar that intercepts and interprets `%Run`.

yes, I find the real issue is the editor didn't show one space character.
