### ISSUE TITLE
Please give me this-ftp or http server

### ISSUE THREAD

**Issue by xuzhou2016** [python/cpython#120978]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
```

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

I use python for a long time (about 10 years), I like it. 
for most users,  if you want a http server,  just one line :   python -m http.server 8888,  and you can visit it  in explorer,   GOOD!
But,   what about if you want to upload a file ? 
Please add a  ftp  or http  server  to support  this.  ( one line, that's smart)
Thanks

June 25, 2024

**Comment by nineteendo** [comment]
> Major feature proposals should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue.

**Comment by nineteendo** [comment]
https://discuss.python.org/t/advice-for-file-upload/56640
