### ISSUE TITLE
Simplify consumers by adding `*.Queue.iter()` and `*.Queue.iter_nowait()`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120924]
# Feature or enhancement

### Proposal:

Currently consuming items from a queue is very complex. You need to

1. use an infinite while loop
2. call `queue.task_done()` after processing each item
3. add all worker tasks to a list
4. join the queue
5. cancel all worker tasks.
6. wait until all worker tasks are cancelled

By adding `asyncio.Queue.iter()` and `asyncio.Queue.iter_nowait()`, this becomes a lot easier, you only need to call `queue.shutdown()`. The same applies to synchronous queues.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

- #120503

### Linked PRs
* gh-120925
* gh-120927

**Comment by nineteendo** [comment]
This is an alternative to #120499 and #119154.

**Comment by vstinner** [comment]
> This is an alternative to https://github.com/python/cpython/issues/120499 and https://github.com/python/cpython/issues/119154.

Please open a single issue to discuss multiple alternatives. I suggest to close this issue.
