### ISSUE TITLE
queue.SimpleQueue() uses just a list in it's C implementation. deque wouuld be much faster.

### ISSUE THREAD

**Issue by socketpair** [python/cpython#120926]
# Feature or enhancement

### Proposal:

deque is much faster for operations like appendleft() + popright() than just a list. C implementation uses list (array) instead of linked-list (deque)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by rhettinger** [comment]
There *might* be a win here, but I think the current code is hard to beat.

**Comment by socketpair** [comment]
@rhettinger, yes, you are right, someone should do a benchmark. Theoretically, a linked list should be faster.

Circular buffer would be even better, but requires the queue to be bound to a specific size.

**Comment by erlend-aasland** [comment]
It's not worth it to keep an issue open for theoretical speedups; I suggest you try it out on your fork, benchmark it, and if there is a substantial performance gain, come back and create an issue.

**Comment by rhettinger** [comment]
The existing code implements a circular buffer on top of a C array.  Unlike a Python list, the `pop(0)` step is `O(1)`.  It looks like the only possible win would be in eliminating the resize steps when the ring buffer size doubles or halves.  Even then, the `memcpy()` step is very fast.  And if the buffer reaches a steady state size, there is almost zero overhead.

**Comment by socketpair** [comment]
Okay, @rhettinger if it uses ring buffer already, I think, I can do nothing in order to make it better. So, closing the issue.
