### ISSUE TITLE
`threading.local()` implementation is not thread-safe in the free-threaded build

### ISSUE THREAD

**Issue by colesbury** [python/cpython#120973]
# Bug report

The implementation of Python thread local variables (`threading.local()` or `_thread._local`) has some thread-safety issues. The issues are particularly relevant to the free-threaded build, but some can affect the default build too.

### local_clear loop over threads isn't safe

The `local_clear()` function is called when a thread local variable is destroyed. It loops over all threads in the interpreter and removes itself from their dictionaries.

https://github.com/python/cpython/blob/fd0f814ade43fa479bfbe76dc226424db14a9354/Modules/_threadmodule.c#L1568-L1581

This isn't thread-safe because after `HEAD_UNLOCK(runtime)`, the stored `tstate` might be deleted concurrently. This can happen even in the default build with the GIL enabled because `PyThreadState_Delete()` doesn't require the GIL to be held. However, it's less likely to occur in practice because `threading` module created threads hold onto the GIL until they're deleted.

### local_clear access to `tstate->dict` isn't thread-safe

In the free-threaded build, `local_clear()` may be run concurrently with some other thread's `PyThreadState_Clear()`. The access to another thread's `tstate->dict` isn't safe because it may be getting destroyed concurrently.

### Linked PRs
* gh-121655
* gh-122042

**Comment by corona10** [comment]
@mpage https://github.com/python/cpython/issues/118490 if the linked issue is related to this issue, please take a look at both of them :)
