### ISSUE TITLE
Add subprocess.shell(cmd) function: similar to os.system(), but use subprocess

### ISSUE THREAD

**Issue by vstinner** [python/cpython#120952]
# Feature or enhancement

Hi,

I propose to add a `subprocess.shell(cmd)` function similar to `os.system()`, but use `subprocess`: close file descriptors, restore signal handlers, etc. The function runs a shell command and so is vulnerable by design to shell injection vulnerability if an attacker can modify the shell command.

The function accepts keyword arguments: `subprocess.shell(cmd, env=env)`, `subprocess.shell(cmd, stdout=subprocess.PIPE)`, etc.

This proposition is related to os.system() soft deprecation: https://github.com/python/cpython/pull/120744

What do you think?

Victor

cc @gpshead @zooba 

### Linked PRs
* gh-121093

**Comment by zooba** [comment]
So essentially `shell = functools.partial(subprocess.run, shell=True)`? That seems fine to me.

**Comment by gpshead** [comment]
I think that functools.partial definition is exactly all this should be (though lets make sure it does _not_ allow `shell=False` to be passed - I don't recall off the top of my what functools.partial does in that situation).

Documentation wise it'd get listed in the subprocess docs _after_ `subprocess.run()` with a one or two sentence description that it is just "run" with "shell=True" for convenience. With an example. And with the caveats of shell=True being re-stated.

**Comment by barneygale** [comment]
Are we handing beginners a foot-shotgun by making shells (and all their quoting problems) easier to access? I like the explicit `subprocess.run(..., shell=True)` spelling, but maybe I've stockholm syndrome'd myself.

**Comment by zooba** [comment]
Possibly.

I think it has plenty of legitimate uses, which is why keeping `os.system` is important. But adding something new to support it is certainly endorsing its use. And it doesn't _really_ have much of a place in production or library code, while it does have an important place in scripting.

It's being added here so we can soft deprecate it elsewhere. I'd rather just leave the original one in place without any kind of deprecation.

**Comment by gpshead** [comment]
The benefit of this one is that it's `subprocess` backed with all that brings. I agree shell=True is not what I _promote_ use of but if we recommend people skip over `os.system` in favor of something else, `subprocess.shell` might make a good gateway drug out of `os` land.

`os.system` is, as the `os` module is generally intended to be, a thin wrapper around the platform's libc or platform provided `system()` or `_wsystem()` C calls.
