### ISSUE TITLE
Simplify consumers with iteration over `*.Queue`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#120947]
# Feature or enhancement

### Proposal:

Currently consuming items from a queue can be a bit more complex than necessary. You need to

1. use an infinite while loop
2. check for a sentinel or add all worker tasks to a list
3. call `q.task_done()` after processing each item
4. join the queue
5. cancel all worker tasks
6. wait until all worker tasks are cancelled

By allowing iteration over `*.Queue`, this becomes a bit easier, you only need to call `queue.shutdown()`.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

- #119154
- #120499
- #120924

### Linked PRs
- **Implementation A**: add `asyncio.Queue.__aiter__()` and `queue.Queue.__iter__()`
    * gh-120491
    * gh-120503
- **Implementation B**: add `*.Queue.iter()` and `*.Queue.iter_nowait()`
    * gh-120925

**Comment by vstinner** [comment]
Please keep discussions about alternatives in an unique issue, rather than opening one issue per alternative. I suggest to close this issue.

**Comment by nineteendo** [comment]
??? that's what this is.

**Comment by vstinner** [comment]
> Huh? That's what this is, it's a single issue to discuss the alternative solutions.

I'm asking the opposite: discuss your alternative in the existing issue, don't create a new issue just for an alternative.

**Comment by nineteendo** [comment]
OK, then I misunderstood this comment:

> Please **open a single issue to discuss multiple alternatives**. I suggest to close this issue.
