### ISSUE TITLE
(🎁) support docstrings on `type` statements

### ISSUE THREAD

**Issue by KotlinIsland** [python/cpython#120981]
# Feature or enhancement

### Proposal:

`type` statements are semantically similar to `class` and `def` statements, they should be able to define docstrings

example:
````python
type Banned = NotRequired[Never]
"""prevent a key from existing on a type

Example:
```py
class NotStrIterable[out_T](Iterable[out_T], Protocol):
    casefold: Banned
```
"""

help(A)  # just outputs the doc for `TypeAliasType`
````
```
Banned = class TypeAliasType(builtins.object)
 |  Type alias.
 |
 |  Type aliases are created through the type statement::
 |
 |      type Alias = int
...
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by nineteendo** [comment]
> Major feature proposals should generally be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue.

**Comment by sobolevn** [comment]
I think that this would be really uncommon for a non-block statement to support docstrings this way. 

Right now `__doc__` is not even assignable on `TypeAliasType` instances:

```python
>>> type A = int
>>> A.__doc__
'Type alias.\n\nType aliases are created through the type statement::\n\n    type Alias = int\n\nIn this example, Alias and int will be treated equivalently by static\ntype checkers.\n\nAt runtime, Alias is an instance of TypeAliasType. The __name__\nattribute holds the name of the type alias. The value of the type alias\nis stored in the __value__ attribute. It is evaluated lazily, so the\nvalue is computed only if the attribute is accessed.\n\nType aliases can also be generic::\n\n    type ListOrSet[T] = list[T] | set[T]\n\nIn this case, the type parameters of the alias are stored in the\n__type_params__ attribute.\n\nSee PEP 695 for more information.\n'
>>> A.__doc__ = 'My info'
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    A.__doc__ = 'My info'
    ^^^^^^^^^
AttributeError: 'typing.TypeAliasType' object attribute '__doc__' is read-only
```

**Comment by AlexWaygood** [comment]
Idon't think it's unreasonable to want to add a docstring to a type alias, but I agree with @sobolevn that this specific proposal would be pretty unprecedented. So we'd need to have a discussion over exactly how we'd want to add the feature. In short, I agree with @nineteendo — this would need to first be discussed on Discourse to hash out design details of the feature in a community forum, before opening a GitHub issue
