### ISSUE TITLE
cannot create a UNC path drive from parts

### ISSUE THREAD

**Issue by kfot** [python/cpython#120943]
# Bug report

### Bug description:

```python
# on Windows
import os
import pathlib 
parts = "\\\\", "host", "share", "whatever"
os.path.join(*parts)  # way 1, os.path is ntpath here
pathlib.Path(*parts)  # way 2, uses ntpath underneath
# None of these ways create a valid UNC. As a developer, I expect it to work the same as posixpath.join or have it documented why it doesn't
```

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Windows

**Comment by nineteendo** [comment]
What's the output and what did you expect?

**Comment by eryksun** [comment]
In 3.12 and 3.13, both `ntpath.join()` and `pathlib.Path` behave correctly for this case. Prior to 3.12, `pathlib.Path` behaves incorrectly by prematurely normalizing "\\\\" as the rooted path "\\". In 3.11, `ntpath.join()` behaves incorrectly by mistakenly joining "\\\\" and "host" with an extra "\\". These bugs aren't security issues, so I wouldn't expect them to get fixed.

Python 3.8.10
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('/host/share/whatever')
```

Python 3.9.13
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('/host/share/whatever')
```

Python 3.10.10
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('/host/share/whatever')
```

Python 3.11.9
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('/host/share/whatever')
```

Python 3.12.4
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('//host/share/whatever')
```

Python 3.13.0b2
```pycon
>>> parts = "\\\\", "host", "share", "whatever"
>>> os.path.join(*parts)
'\\\\host\\share\\whatever'
>>> pathlib.Path(*parts)
WindowsPath('//host/share/whatever')
```

**Comment by nineteendo** [comment]
Shouldn't the issue be closed in that case? Those branches only accept security fixes.
Or does the OP mean something else?

**Comment by eryksun** [comment]
I will close the issue if kfot confirms that `ntpath.join()` and `pathlib.Path` are correct in 3.12 and 3.13, and if no one makes a case for this being a security issue in 3.8-3.11. I don't see a case for that. They're just bugs that can be worked around, such as by pre-joining the drive component as "\\\\host\\share".

**Comment by kfot** [comment]
Thank you for clarifying that, please feel free to close the issue.
