### ISSUE TITLE
macOS installer is missing `pip` for free-threaded binaries

### ISSUE THREAD

**Issue by colesbury** [python/cpython#120962]
# Bug report

The official macOS installer, doesn't install `pip` for the free-threading binaries. Users need to run:

```
python3.13t -m ensurepip
```

And until the bundled pip is upgraded in https://github.com/python/cpython/issues/120888:

```
python3.13t -m pip install --upgrade pip
```

**Comment by ned-deily** [comment]
Thanks for the report. As a result, `pip` is now automatically installed to the free-threaded `PythonT.framework` for 3.13 when the `Free-threaded Python` option of the python.org installer for macOS is selected. The free-threaded installation option is now documented in the [Using Python on macOS](https://docs.python.org/3.13/using/mac.html#installing-free-threaded-binaries) documentation
