### ISSUE TITLE
Given type X = T ... X does not dereference to T

### ISSUE THREAD

**Issue by bionicles** [python/cpython#120920]
# Bug report

### Bug description:

**BUG (IMHO)**: If we create `type` aliases in python 3.12, then we can't call methods on aliased types. (This is the point of an alias!)

Seems like `type` could make `TypeAlias` instead of `TypeAliasType`.

`TypeAliasType` could be renamed `Deref[T](Protocol)` to implement new kinds of type aliases (a different, more abstract, extensibility issue)

_Correct implementation of deref for python may require GATs (generic associated types) to erase the generic `T` so we can write `Deref(Protocol)` without needing to pass in the type we aim to find just to find it_

```python
from typing import Protocol, Any, Tuple
from dataclasses import dataclass


class Transform(Protocol):
    @staticmethod
    def transform(value: Any) -> str:
        return f"{value=} transformed"


class CustomTransform(Transform):
    @staticmethod
    def transform(value: Any) -> str:
        return f"{value=} custom transformed"


@dataclass(frozen=True, slots=True)
class Group[T: Transform]:
    items: tuple[T, ...]

    @classmethod
    def new(cls) -> "Group[T]":
        return cls(())

    @classmethod
    def from_items(cls, items: Tuple[T, ...]) -> "Group[T]":
        return cls(items)


def test_collection():
    collection1 = Group[CustomTransform].new()
    print(collection1)  # > Group(items=())
    type TestGroup = Group[CustomTransform]
    collection2 = TestGroup.new()
    #                       ^^^ AttributeError: 'typing.TypeAliasType' object has no attribute 'new'
    print(collection2)
    assert collection1 == collection2


test_collection()
```
Result: multiple issues

![image](https://github.com/python/cpython/assets/24532336/1939e2cc-b185-4afe-96dc-f2b92c182cfc)

Further thoughts can be found here, in the long thread about the issue, I just think it's a bug we can fix. 

https://discuss.python.org/t/run-time-behaviour-of-typealiastype/43774/34

benefits of fixing this issue include being able to define classes with one liners like `type Xs = MyContainer[X]` and invoke methods on MyContainer by calling them on Xs. 

if Xs doesn't get methods of MyContainer then it's harmful to have types right now, because it is just confusing for no benefit.

docs imply `type X` is a type alias and not a type alias type
![image](https://github.com/python/cpython/assets/24532336/56d0101d-658b-43eb-b409-d94a0a84e993)

```py
from typing import TypeAlias, TypeAliasType


def test_python_type_alias():
    type X = int
    print(type(X))  # <class 'typing.TypeAliasType'> ... oops!
    # assert isinstance(X, TypeAlias)  # X could be a TypeAlias and this line could just work

    assert isinstance(X, TypeAliasType)
    assert "__abs__" in dir(int), "ensure integers have the method we want to call"
    # if the next line fails, it means type didn't dereference the alias
    assert "__abs__" in dir(X), "TypeAlias does not have methods of the aliased type"
    assert type(X) == int, "type(TypeAlias) did not dereference to the aliased type"
    # the following lines could also just work
    # assert isinstance(X, int) # is a TypeAlias[T] a T? YES!
    # further checks, play around with em
    # assert type(X).__name__ == "X"
    # assert type(X).__deref__ == int


# Idea: Rename TypeAliasType to Deref(Protocol).
# TypeAlias(Deref) default implementation
test_python_type_alias()
```
Result: multiple issues
![image](https://github.com/python/cpython/assets/24532336/9aeba092-c353-45df-a933-385f19c1cfad)

Please let me know if I'm doing it wrong and there's a workaround, but the python type keyword seems broken for my use case of just wanting to define new specific kinds of generic classes, because it creates aliases which don't quack like the thing they're aliasing. 

Thank you for your time and for your work on Python.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
The point of `type` is to make aliases that are usually used in *annotations* but I don't think it was meant to be used at runtime. In addition, a [TypeAliasType](https://docs.python.org/3/library/typing.html#typing.TypeAliasType) is only expected to expose some attributes and is not meant to be used as a runtime alias.

If you want runtime support, you need to use regular aliases (i.e., `Alias = Type`) and not `type Alias = Type` or `Alias: TypeAlias = Type`. Well, with `TypeAlias`, you will have runtime behaviour that matches what you want but I think its purpose is primarily for annotation-related contexts and type checking.

Personally, I would very much like that `type` behaves like a `typedef` in C/C++, but I'm not sure whether it was inteded as such.

Related discussions:
- https://discuss.python.org/t/pep-695-type-aliases-not-suitable-as-replacement-for-typing-typealias/43364/39 
- https://github.com/python/cpython/issues/114159.

**Comment by AlexWaygood** [comment]
Thanks @picnixz. This is the same theme as #114159, so I'll close this in favour of that thread so that discussion isn't fractured between the two issues.
