### ISSUE TITLE
-Wimplicit-fallthrough generating warnings

### ISSUE THREAD

**Issue by nohlson** [python/cpython#121040]
# Bug report

### Bug description:

Due to the addition of `-Wimplicit-fallthrough` as a `BASEFLAG` new warnings are generated.

This should be reverted until tooling is created to track these new warnings per https://github.com/python/cpython/issues/112301

Warnings can be found in builds https://buildbot.python.org/all/#/builders/721/builds/1465/steps/3/logs/warnings__143_ from https://github.com/python/cpython/pull/121030

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121041
* gh-121044

**Comment by sobolevn** [comment]
A potential fix could look something like:

```c
#if __has_attribute(__fallthrough__)
#  define _Py_FALLTHROUGH __attribute__((__fallthrough__))
#else
#  define _Py_FALLTHROUGH do { } while (0)
#endif
```

**Comment by vstinner** [comment]
Previous issues:

* https://github.com/python/cpython/issues/75106
* https://github.com/python/cpython/issues/75200

**Comment by vstinner** [comment]
> A potential fix could look something like: (...)

I wrote PR gh-121044 to fix these compiler warnings; the PR adds a new _Py_FALLTHROUGH macro.

**Comment by corona10** [comment]
> A potential fix could look something like:

It can not be the ultimate solution.
- Should check MSVC is accept this macro. (or do nothing if the compiler is MSVC)
- Even if we added the macro for our codebase, vendored libraries like libexpat should follow the new compiler rule.

**Comment by vstinner** [comment]
> Should check MSVC is accept this macro. (or do nothing if the compiler is MSVC)

Does MSC implement a flag like `-Wimplicit-fallthrough`? If not, I don't think that we should care about MSC in _Py_FALLTHROUGH macro.

> Even if we added the macro for our codebase, vendored libraries like libexpat should follow the new compiler rule.

If you want to use this compiler flag, you can use system libraries, instead of building embedded copies of libexpat and libmpdecimal.

**Comment by corona10** [comment]
> If you want to use this compiler flag, you can use system libraries, instead of building embedded copies of libexpat and libmpdecimal.

IIUC, the original intention was adopt those compiler flag as default not the optional.

**Comment by corona10** [comment]
> Does MSC implement a flag like -Wimplicit-fallthrough? If not, I don't think that we should care about MSC in _Py_FALLTHROUGH macro.

But it emits the compiler warning so we should provide dummy macro for the MSVC
see: https://github.com/python/cpython/pull/121044/files#r1654967484

**Comment by vstinner** [comment]
> But it emits the compiler warning so we should provide dummy macro for the MSVC
> see: https://github.com/python/cpython/pull/121044/files#r1654967484

You misunderstood the warning. It was only about `__has_attribute()`. I fixed this issue.

**Comment by vstinner** [comment]
Warnings were fixed by https://github.com/python/cpython/commit/12af8ec864225248c3d2916cb142a5e7ee36cbe2. I close the issue.
