### ISSUE TITLE
lexer handles raw string escapes differently than documentation

### ISSUE THREAD

**Issue by anabelle2001** [python/cpython#121014]
# Bug report

### Bug description:

According to the docs,
> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such strings are called raw strings and **treat backslashes as literal characters**[^1]

This does not hold during the lexing stage, where backslashes in raw strings always escape quotation marks:

```py
print(r'\') # Causes SyntaxError, should print a single backslash
print(r'\'') # Prints `\'`, should give a syntax error
```

[^1]:  <https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals>,

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
See https://docs.python.org/3/faq/programming.html#can-i-end-a-raw-string-with-an-odd-number-of-backslashes for your first example.

For the second, you're seeing the repr of a string that contains a single backslash. That's the correct behavior.
