### ISSUE TITLE
Add footer to github issues template like in xonsh shell

### ISSUE THREAD

**Issue by anki-code** [python/cpython#121042]
# Feature or enhancement

### Proposal:

Hello!

In [xonsh shell](https://github.com/xonsh/xonsh) project we have a [footer for issues](https://github.com/xonsh/xonsh/blob/0f2011d3028db878460c281ae7010a47ebea10b2/.github/ISSUE_TEMPLATE/new-issue.md?plain=1#L41-L42):

<img width="516" alt="image" src="https://github.com/python/cpython/assets/1708680/81e07f80-7cb9-4d1a-9df0-393086872497">

It works really well. It will be cool to have this footer in cpython repository.

Thanks!

## For community
⬇️  **Please click the 👍 reaction instead of leaving a `+1` or 👍  comment**

**Comment by sobolevn** [comment]
This looks nice, but from what I've seen we don't really have `+1` problem in the bug tracker, because most of the features are discussed on https://discuss.python.org 

What do others think?

**Comment by pochmann3** [comment]
I think this would add distracting noise to prevent distracting noise that doesn't exist anyway (as far as I can tell from reading lots of issue threads here - I think they'd annoy me enough that I'd remember seeing any). Where are all those problematic +1 or 👍 comments here?

**Comment by matkoniecz** [comment]
Also, if such spam is not large scale Github feature allowing to collapse or delete comments allows to manage it.

And footer itself is also annoying.

**Comment by hauntsaninja** [comment]
Yeah, this isn't solving a problem that this issue tracker has.

(Also note if you use the Github Refined browser extension, it will automatically collapse +1 comments)
