### ISSUE TITLE
Incorrect use of _PyLong_CompactValue()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#121153]
# Bug report

There are several errors related to use of `_PyLong_CompactValue()` in `longobject.c`.

* The result has type `Py_ssize_t`, not `intptr_t`. Although on most supported platforms it is the same.
* Type cast from unsigned integer to signed integer and from signed integer to unsigned integer should be explicit.
* Downcasting should be explicit.

Some of the current code may have undefined behavior.

### Linked PRs
* gh-121154
* gh-121536
* gh-121900
* gh-121901

**Comment by markshannon** [comment]
> The result has type Py_ssize_t, not intptr_t. Although on most supported platforms it is the same.

We should change the return type to `intptr_t` in that case. I thought it was.
