### ISSUE TITLE
Missing PyDECREF calls for ADDITEMS opcode of _pickle.c

### ISSUE THREAD

**Issue by Legoclones** [python/cpython#121137]
# Bug report

### Bug description:

In the `load_additems` function of [`Modules/_pickle.c`](https://github.com/python/cpython/blob/3.11/Modules/_pickle.c#L6629) (which handles the `ADDITEMS` opcode), [PyObject_GetAttr](https://docs.python.org/3/c-api/object.html#c.PyObject_GetAttr) is called and returns `add_func` on [line 6660](https://github.com/python/cpython/blob/3.11/Modules/_pickle.c#L6660). PyObject_GetAttr returns a new reference, but this reference is never decremented using Py_DECREF, so 2x calls to this function are added (compare to `do_append` function in the same file).

Pull request was made at https://github.com/python/cpython/pull/121136

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-121136
* gh-121139
* gh-121140

**Comment by gaogaotiantian** [comment]
Thanks for reporting and fixing this.
