### ISSUE TITLE
tracemalloc: add new `dump_snapshot()` and `load_snapshot()` functions implemented in C

### ISSUE THREAD

**Issue by vstinner** [python/cpython#121120]
Currently, `dump()` and `load()` methods of `tracemalloc.Snapshot` are implemented in Python using the `pickle` module. Problem: calling `dump()` allocates memory traced by Python and so this memory is seen in snapshot.

It's harder to analyze snapshots if they contain memory allocated by tracemalloc itself, especially if the leak is a single memory allocation (a single memory block).

I propose to reimplement these functions in C to avoid these issues: add new `dump_snapshot()` and `load_snapshot()` functions.

### Linked PRs
* gh-121121

**Comment by nineteendo** [comment]
Eh, shouldn't this be marked as not planned?

**Comment by vstinner** [comment]
I closed the issue since my C writer was slower and produced larger files, the Python reader was way slower.
