### ISSUE TITLE
wrong number sorting

### ISSUE THREAD

**Issue by Creative404** [python/cpython#121170]
# Bug report

### Bug description:

i saw that phyton doing bad job at sorting number that have 2 or more digits and contains "9" 
 ```python
b = {3,5,4,8,0}
NewSet=set([1,199,87,88,1,2,3]) 
c = b | NewSet
print(c)
```
Expected output :
`{0, 1, 2, 3, 4, 5, 8, 87, 88, 199}`

What i got:
`{0, 1, 2, 3, 4, 5, 199, 8, 87, 88}`

(sorry for bad English and poorly described error - i just start learning phyton) 

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Set is unordered data type: https://docs.python.org/3.12/reference/datamodel.html#set-types

This repository is a CPython bug tracker. Please, ask for help there: https://discuss.python.org/c/users/7

**Comment by tim-one** [comment]
As noted, sets are "unordered" - they make no promises about the order in which set elements are displayed. To get what you want, use `print(sorted(c))` instead.

```python
>>> print(sorted(c))
[0, 1, 2, 3, 4, 5, 8, 87, 88, 199]
```

**Comment by Creative404** [comment]
> Hello! Set is unordered data type: https://docs.python.org/3.12/reference/datamodel.html#set-types
> 
> This repository is a CPython bug tracker. Please, ask for help there: https://discuss.python.org/c/users/7

thank u and sorry for dumb topic

**Comment by Creative404** [comment]
> As noted, sets are "unordered" - they make no promises about the order in which set elements are displayed. To get what you want, use `print(sorted(c))` instead.
> 
> ```python
> >>> print(sorted(c))
> [0, 1, 2, 3, 4, 5, 8, 87, 88, 199]
> ```
thank you for help have great day and sorry for dumb noob question :D
