### ISSUE TITLE
'And' functionality between lists

### ISSUE THREAD

**Issue by Shar-01** [python/cpython#121148]
# Feature or enhancement

### Proposal:

```python
list1 = [1, 2, 3, 4]
list2 = [3, 4, 5, 6]
list3 = list1 and list2
print(list3)
[3, 4, 5, 6]
```
In a `logical and` operation between lists, the logic is not intuitive to users. 
- If list1 is considered false (empty, None, False, or zero), Python returns list1.
- If list1 is considered true (non-empty, non-zero, or True), Python returns list2

This logic does not align with the notions of `logical and` operation as perceived by users. Either, it should be similar to an intersection operation, or at least for understability, it should return a `boolean` such as if both lists are non-empty, it should return `True`, else, `False`. 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ronaldoussoren** [comment]
In general new features need discussion on discuss.python.org. In this case discussion would not be useful because changing the behaviour of here would break too much code (regardless of whether or not this is a useful change).

**Comment by terryjreedy** [comment]
In particular, the definitions of `and`, `or`, and `not` can only be customized for a class by customizing the definition of `__bool__`.  Other than that, the type of operands does not matter.

**Comment by pochmann3** [comment]
The current behavior already *is* a useful feature and expected (unless one hasn't read the documentation of `and`).

**Comment by Shar-01** [comment]
> The current behavior already _is_ a useful feature and expected (unless one hasn't read the documentation of `and`).

I do not understand how it is useful, let alone intuitive. I would any day directly use a ternary operator which is more readable for the current behavior.
