### ISSUE TITLE
importlib.abc: NameError: name 'warnings' is not defined

### ISSUE THREAD

**Issue by hroncok** [python/cpython#121279]
# Bug report

### Bug description:

```python
>>> import importlib.abc
>>> importlib.abc.TraversableResources
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    importlib.abc.TraversableResources
  File "/usr/lib64/python3.13/importlib/abc.py", line 34, in __getattr__
    warnings._deprecated(f"{__name__}.{name}", remove=(3, 14))
    ^^^^^^^^
NameError: name 'warnings' is not defined. Did you mean: 'Warning'? Or did you forget to import 'warnings'?
```

This is a result of https://github.com/python/cpython/pull/120429

Thew change on the main branch correctly removed unused `import warnings`, but ti got backported to 3.13 where the import is used.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-121281
* gh-121319

**Comment by hroncok** [comment]
Working on a PR.

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/dacf4ffa7982e13dce87ecb61b3b21e99375298a.

**Comment by encukou** [comment]
The fix fails in refleaks buildbots:
- https://buildbot.python.org/all/#/builders/1396/builds/229/steps/5/logs/stdio
- https://buildbot.python.org/all/#/builders/1431/builds/205

Reproducible with:
```
./python -m test test_importlib -m 'test_deprecated*' -R:
```

**Comment by hroncok** [comment]
The failure is `AssertionError: DeprecationWarning not triggered`

I assume that when the test runs multiple times, the DeprecationWarning is no longer triggered. I would need to see how other tests do this.

**Comment by vstinner** [comment]
> The fix fails in refleaks buildbots:

I propose a fix for that: https://github.com/python/cpython/pull/121319

**Comment by hroncok** [comment]
Apologies for breaking the buildbots. TIL I need to run my tests with `-R:` to check this.

**Comment by vstinner** [comment]
I'ts uncommon that tests only fail with -R, don't worry.

**Comment by vstinner** [comment]
> The fix fails in refleaks buildbots:

It should be fixed by: https://github.com/python/cpython/commit/ec0f801a7222a256a20d01c99aca69e6aa4b10ae
