### ISSUE TITLE
Immutable dictionary in Python

### ISSUE THREAD

**Issue by silas-wr** [python/cpython#121298]
# Feature or enhancement

### Proposal:

My proposal is that an immutable dictionary should be implemented. This would be useful in a case where a dictionary is desired, but it is likely to be corrupted by other threads in the code. An immutable dictionary would be accessible as usual, but it would not be modified/corrupted. There are two possible ways this could work:

1. separate `imdict` class
```python
# example of an immutable dictionary (version 1)
# in the example, mydict is an immutable dictionary containing the following key-value pairs:
# KEY: k1, VALUE: v1
# KEY: k2, VALUE: v2
# KEY: kN, VALUE: vN

mydict = imdict({k1: v1, k2: v2, kN: vN})

# in this situation, 'imdict()' is used to make the input dictionary immutable.
```
2. separate dictionary syntax
```python
# example of an immutable dictionary (version 2)
# in the example, mydict is an immutable dictionary containing the following key-value pairs:
# KEY: k1, VALUE: v1
# KEY: k2, VALUE: v2
# KEY: kN, VALUE: vN

mydict = ${k1: v1, k2: v2, kN: vN}

# in this situation, the '$' operator is used to make an immutable dictionary with the specified key-value pairs.
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by eendebakpt** [comment]
@silas-wr Thanks for the suggestion. There is already quite some discussion on this topic. See for example https://discuss.python.org/t/pep-603-adding-a-frozenmap-type-to-collections/2318.

**Comment by ericvsmith** [comment]
This change would require a PEP. I'm going to close this until the discussion d.p.o. reaches a conclusion, and a PEP is written.
