### ISSUE TITLE
Embedded Python 3.11.8 - `PyConfig_Read` does not fully setup `PyConfig`

### ISSUE THREAD

**Issue by stepanm-aparavi** [python/cpython#121239]
# Bug report

### Bug description:

Trying to upgrade from Python 3.10.7 provided by VCPKG 2023.06.20 to Python 3.11.8 provided by VCPKG 2024.06.15. The following code works in different ways:
```cpp
::PyConfig cfg{};
::PyConfig_InitIsolatedConfig(&cfg);
cfg.parse_argv = 1;
::PyConfig_SetArgv(&cfg, argc, argv); // argc=1, argv[0]="<path to executable>"
::PyConfig_SetString(&cfg, &cfg.home, "<path to execution directory>");
::PyConfig_Read(&cfg);
```
`PyConfig_Read` does not fully setup `cfg` on Python 3.11.8. `cfg.program_name`, `.platlibdir`, `.executable`, `.module_search_paths` etc. are null.
Whereas the same code on Python 3.10.7 sets all these fields with appropriate values.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by vstinner** [comment]
>  Whereas the same code on Python 3.10.7 sets all these fields with appropriate values.

Do you use these members? Can you elaborate your use case?

Well, the implementation of PyConfig changed with the introduction of `Modules/getpath.py` in Python 3.11. What you see is the expected behavior and not a bug.

cc @zooba

**Comment by stepanm-aparavi** [comment]
Found an issue with good explaining of these changes https://github.com/python/cpython/issues/101471
Thank you
