### ISSUE TITLE
Stackrefs (#118450) introduced a large performance regression on Windows 

### ISSUE THREAD

**Issue by mdboom** [python/cpython#121263]
### Bug description:

#118450 "Convert the evaluation stack to stack refs" (by @Fidget-Spinner) unfortunately seems to have introduced a [7% - 11% performance regression overall](https://github.com/faster-cpython/benchmarking-public/tree/main/results/bm-20240627-3.14.0a0-22b0de2) (though as much as 25% for some benchmarks) on Windows only.  Linux (both x86_64 and aarch64) and macOS (arm) seem to have a change beneath the noise threshold.  To be clear, @Fidget-Spinner's work is great and the lesson here is that for these sorts of sweeping low-level changes, we should have benchmarked on all of the Tier 1 platforms to be certain.

I don't know what the cause is -- it is probably MSVC not being able to "optimize through" something and introducing unnecessary overhead, but that's just a theory.

Cc: @brandtbucher, @markshannon 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-121270

**Comment by Fidget-Spinner** [comment]
@mdboom Thanks for bringing this up! In the past this was usually due to MSVC not being able to inline in the eval loop because its too big of a function. I can change all the static inlines to macros and try benchmarking again?

**Comment by mdboom** [comment]
> I can change all the static inlines to macros and try benchmarking again?

Sounds like a good first thing to try.  Thanks!
