### ISSUE TITLE
Tarfile is unnecessarily slow

### ISSUE THREAD

**Issue by jforberg** [python/cpython#121267]
# Bug report

### Bug description:

There is room for improvement in tarfile write performance. In a simple benchmark I find that tarfile spends most of its time doing repeated user name/group name queries.
https://gist.github.com/jforberg/86af759c796199740c31547ae828aef2

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121269

**Comment by gaogaotiantian** [comment]
Could you paste your cProfile output? I was a bit surprised that most of the time is spent on reading the pwd and grp.

**Comment by jforberg** [comment]
@gaogaotiantian Here is the output:

[cprofile.txt](https://github.com/user-attachments/files/16074501/cprofile.txt)

**Comment by picnixz** [comment]
Recategorizing this issue as per https://github.com/python/cpython/pull/121269#issuecomment-2448656905.
