### ISSUE TITLE
The extend method of a list returns None

### ISSUE THREAD

**Issue by dslj2017** [python/cpython#121256]
# Bug report

### Bug description:

options1 = ["A"]
options2 = ["b", "c", "d"]
options = options1.extend(options2)
print(options) 
# The output is None

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
This is a expected behavior.
This repository is intended as a CPython bug tracker.   Please, ask for help there: https://discuss.python.org/c/users/7
