### ISSUE TITLE
Remove backtracking from parsing tarfile members and headers

### ISSUE THREAD

**Issue by sethmlarson** [python/cpython#121285]
### Bug description:

Today the `tarfile` module parsing of header values allows for backtracking when parsing header values. Headers have a well-known format that doesn't require backtracking to parse reliably, the new method of parsing will only require a single pass over a byte stream.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-121286
* gh-123542
* gh-123543
* gh-123639
* gh-123640
* gh-123641
* gh-123642

**Comment by ethanfurman** [comment]
@sethmlarson, why is this a security issue?

**Comment by gpshead** [comment]
`main` version merged.  I'll let you work out any non-automatic backports.

**Comment by picnixz** [comment]
(I just added the labels that still require the backports and you could remove them one by one when you're done)

**Comment by frenzymadness** [comment]
The CVE description contains:

>  Regular expressions that allowed excessive backtracking during tarfile.TarFile header parsing are vulnerable to ReDoS via specifically-crafted tar archives.

but the test added to verify the fix does not cause/test the ReDoS. I mean, when you run the test with unpatched Python, it raises `tarfile.ReadError` as well just with a different message, for example:

```
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: ReadError('not an lzma file')
- method tar: ReadError('bad checksum')
```

Could you please help me understand how one of the regexes (fox example: `br"(\d+) ([^=]+)="`) can cause a regex backtracking? There is no combination of greedy nested quatifiers, greedy quantifiers are limited by the character class and I don't see a need for the regex algorithm to go back and consider another path if the match is not found.

**Comment by sethmlarson** [comment]
@frenzymadness Apologies for the confusion, not all of the regular expressions in the PR have issues with backtracking. The regex you mention was replaced to process the entire tar header block in one pass rather than multiple passes.

**Comment by mcepl** [comment]
Patch for Python 3.8 applies more or less painlessly on the 3.6 branch as well.
