### ISSUE TITLE
KeyboardInterrupt during paste breaks the new REPL

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#121295]
# Bug report

### Bug description:

To reproduce, type `f = """` then paste a giant block of text (I pasted [the text of Frankenstein](https://github.com/asweigart/codebreaker/blob/master/frankenstein.txt)) then press Ctrl+C immediately (while the text is being pasted).

```pycon
>>> f = """
<GIANT BLOCK OF TEXT>

Then hit Ctrl+C
```

After this the REPL will enter a state where it seems unable to *end* a block of code. The prompt changes to `...` and only Ctrl+C will quit out of the block.

Also nothing is displayed while typing until Enter is pressed.

Here's [an animation](https://asciinema.org/a/GMRyMxyzKjB0NxLt5MaQIsXyL) showing the issue:

![666571](https://github.com/python/cpython/assets/285352/3043824c-6361-4733-ab80-330f0b927a91)

This issue is also reproducible on the `main` branch.

I checked out commit 32a0faba439b239d7b0c242c1e3cd2025c52b8cf and I could not reproduce this, so the issue arose sometime after #120253 was merged. 

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121815
* gh-121826

**Comment by pygeek** [comment]
Which linux distro and version are you using? I was unable to reproduce on macOS 14.5.

**Comment by treyhunner** [comment]
> Which linux distro and version are you using? I was unable to reproduce on macOS 14.5 so the issue may be Linux specific.

I am running on Ubuntu Linux 22.04.4. I was able to reproduce the problem in both Gnome Terminal and in XTerm on my machine.

**Comment by mgmacias95** [comment]
I am working on this :)

**Comment by ambv** [comment]
Thanks for the fix, Marta! ⚡️⚡️⚡️
