### ISSUE TITLE
Variable Interchange in Multiprocessing

### ISSUE THREAD

**Issue by tanjt107** [python/cpython#121397]
# Bug report

### Bug description:

I have encountered an issue in my Python application that uses the multiprocessing module. The application generates unique IDs for each API request using the uuid library. It happened once that variables between two processes seem to interchange, leading to errors. For example, processes associated with UUIDs A and B might swap their variables, causing unexpected behavior. However, I am unable to reproduce this yet. Has anyone in the community experienced similar issues? Any insights or suggestions on how to debug and resolve this issue would be greatly appreciated.

Thank you!

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
For general discussions, please post in https://discuss.python.org/c/users/7
