### ISSUE TITLE
Minor error in simple_stmts.rst

### ISSUE THREAD

**Issue by Wondaeng** [python/cpython#121355]
# Documentation

https://github.com/python/cpython/blob/2f5f19e783385ec5312f7054827ccf1cdb6e14ef/Doc/reference/simple_stmts.rst?plain=1#L296

In this line, isn't it should be `assignment statement`, not `assignment expression`?

### Linked PRs
* gh-121356
* gh-121362
* gh-121363

**Comment by JelleZijlstra** [comment]
Thanks for the fix!
