### ISSUE TITLE
3.13 `copy.replace` isn't in `__all__`

### ISSUE THREAD

**Issue by max-muoto** [python/cpython#121300]
# Bug report

### Bug description:

`copy.replace` isn't exported as a part of `__all__` in the `copy` module. This seemed liked an oversight, as opposed to being intentional, but feel free to close this issue if not.

### CPython versions tested on:

3.13

### Linked PRs
* gh-121302
* gh-121304
* gh-121337

**Comment by max-muoto** [comment]
CC: @serhiy-storchaka

**Comment by pygeek** [comment]
https://github.com/python/cpython/pull/108752/files

**Comment by pygeek** [comment]
`super().__or__()`

**Comment by pygeek** [comment]
Nice catch:

https://github.com/python/cpython/pull/108752

**Comment by max-muoto** [comment]
> Hello!
> 
> Nice catch. This definitely should be in ``__all__`` since this is part of the public API.
> 
> Would you like to send a PR with fix?

Will do!

**Comment by max-muoto** [comment]
@Eclips4 https://github.com/python/cpython/pull/121302

**Comment by serhiy-storchaka** [comment]
Sure, this is an oversight. `pydoc copy` should show `replace`.

**Comment by max-muoto** [comment]
> Sure, this is an oversight. `pydoc copy` should show `replace`.

Do you want a separate PR here? Or can add it into the existing one I have.

**Comment by pygeek** [comment]
> @Eclips4 #121302

Trivial update, but we should probably add a regression test for `__all__`. See `support.test__all__` in the test directory.

**Comment by serhiy-storchaka** [comment]
Adding it to the module docstring is also a good idea. You can include this in your PR or create a separate PR if you wish.

**Comment by max-muoto** [comment]
> Adding it to the module docstring is also a good idea. You can include this in your PR or create a separate PR if you wish.

Let me just do that in the current PR, I'm also going to add a test case.

**Comment by Eclips4** [comment]
Thanks!
