### ISSUE TITLE
Creating new object instance doesn't reset arrays filled using append!

### ISSUE THREAD

**Issue by ynsbleng** [python/cpython#121396]
# Bug report

### Bug description:

```python
class book:
    def __init__(self, tags = []):
        self.tags = tags;

book1 = book();

book1.tags.append(0);

print(book1.tags); # this will print [0]

book2 = book(); # new instance of book

print(book2.tags); # this will print [0] where the expected result should be []
```

However, the following code should work properly:

```python
class book:
    def __init__(self, tags = []):
        self.tags = tags;

book1 = book();

book1.tags = [0];

print(book1.tags); # this will print [0]

book2 = book(); # new instance of book

print(book2.tags); # this will print [] as expected
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
This is not a bug. See https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects for an explanation of what's going on here.

**Comment by ynsbleng** [comment]
It's pretty confusing though, regardless of the programming language, when creating a new object instance, I expect to have a fresh object including the default parameters, keeping references to previous instances is just wrong in my opinion, but you Python guys have your own way of doing things, so whatever.
