### ISSUE TITLE
dis: BUILD_LIST docs incorrectly say count must be > 0

### ISSUE THREAD

**Issue by frigus02** [python/cpython#121367]
# Documentation

The `dis` module docs for `BUILD_LIST` (and `BUILD_SET` and `BUILD_TUPLE`) say that the `count` argument must be > 0:

https://github.com/python/cpython/blob/17d5b9df10f53ae3c09c8b22f27d25d9e83b4b7e/Doc/library/dis.rst?plain=1#L1081-L1098

But the code `[]` generates the instruction `BUILD_LIST 0`. [godbolt repro](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:1,lang:python,selection:(endColumn:3,endLineNumber:1,positionColumn:3,positionLineNumber:1,selectionStartColumn:3,selectionStartLineNumber:1,startColumn:3,startLineNumber:1),source:%5B%5D),l:'5',n:'1',o:'Python+source+%231',t:'0')),k:50.47766019988242,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:python312,filters:(b:'0',binary:'1',binaryObject:'1',commentOnly:'0',debugCalls:'1',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'0',verboseDemangling:'0'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:2,lang:python,libs:!(),options:'',overrides:!(),selection:(endColumn:50,endLineNumber:5,positionColumn:50,positionLineNumber:5,selectionStartColumn:50,selectionStartLineNumber:5,startColumn:50,startLineNumber:5),source:1),l:'5',n:'0',o:'+Python+3.12+(Editor+%231)',t:'0')),k:49.52233980011758,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',m:100,n:'0',o:'',t:'0')),version:4)

I assume either the docs are meant to say `assert count >= 0` or maybe the assert is only valid for `BUILD_TUPLE`?

### Linked PRs
* gh-122663
* gh-122683
* gh-122684

**Comment by Eclips4** [comment]
Hello! Thanks for the report.
https://github.com/python/cpython/pull/96462#discussion_r1068267879 says that count should not be zero, but actually it can:
```python
dis.dis("[]")
>>> dis.dis('[]')
  0           RESUME                   0

  1           BUILD_LIST               0
              RETURN_VALUE
>>>
```

cc @markshannon
