### ISSUE TITLE
Asyncio.Lock timeout

### ISSUE THREAD

**Issue by ewi2345** [python/cpython#121419]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
```
Deadlocks should be treaded in asyncio.Lock() more gracefully via timeout and an asyncio.TimeoutError - just my opinion and my feature suggestion 

### Has this already been discussed elsewhere?

No response given

**Comment by sobolevn** [comment]
Can you please be more specific? Do you have a reproducer? Can you point to some existing lines of code? What happens now? What do you expect to happen after the change? What does the documentation say about this behaviour?

**Comment by ewi2345** [comment]
I have had no problem with asyncio.Lock() yet (at least I am not aware of it) - so I am **not** reporting a bug ... and maybe my concern for making this feature request is totally unwarranted - but I have had a deadlock situation with threading.Lock() - It froze the entire app - I couldn't figure out exactly why, so I used threading.RLock() instead which raises a TimeoutError exception - Since then (and I also don't know why) - I never got from RLock a TimeoutError msg (yet).
But still, proactive, I would like to have the option to set a timeout on an asyncio.Lock(), because I want to trust asyncio that it informs me if something is wrong. Without a timeout, I would potentially not even detect that there was a hidden deadlock if it is used e.g. in an independent task. 
Based on my previous encounter with a deadlock .. and the increased complexity from dealing with events, I would assume that it would be a nightmare to find out why or how a deadlock happens. I personally would use the timeout parameter by default ... (precautionary) ..
What do I expect from the Timeout ? .. I get a raised error message telling me that there was within a certain code section a timeout related to asyncio.lock -- what do I expect without that feature -- the code section within "with asyncio.lock()" will potentially never executed and I would never informed about that - not good.

**Comment by Zheaoli** [comment]
This is a very interesting issue. In my experience, the author doesn't support Lock with timeout by default in std lib in most of the language like Go, Rust, etc.. FYI

1. https://docs.rs/tokio/latest/tokio/sync/struct.Mutex.html#method.lock
2.  https://pkg.go.dev/sync#Mutex.Lock

But the people need the Lock with timeout, so there are many third-party lib to support this. FYI

1. https://docs.rs/timed-locks/latest/timed_locks/
2. https://github.com/viney-shih/go-lock

In my opinion, I think it's necessary to support lock with timeout. But for compatibility, I suggest we add a new API named LockWithTimeout to support this feature.

**Comment by pygeek** [comment]
The omission is intentional. Here's what Python Docs have to say.

https://docs.python.org/3/library/asyncio-sync.html

> asyncio synchronization primitives are designed to be similar to those of the [threading](https://docs.python.org/3/library/threading.html#module-threading) module with two important caveats:

> asyncio primitives are not thread-safe, therefore they should not be used for OS thread synchronization (use [threading](https://docs.python.org/3/library/threading.html#module-threading) for that);
methods of these synchronization primitives do not accept the timeout argument; use the [asyncio.wait_for()](https://docs.python.org/3/library/asyncio-task.html#asyncio.wait_for) function to perform operations with timeouts.

Here's an example:

```
import asyncio

lock = asyncio.Lock()
timeout = 1

try:
    await asyncio.wait_for(lock.acquire(), timeout=timeout)
except asyncio.TimeoutError:
    ...
```

**Comment by ewi2345** [comment]
asyncio.lock() and threading.lock() are used in the context of the "Context Manager":  with .. it acquires and then releases a resource. I don't think that the suggested asyncio.wait_for(lock.acquire(), .. ) solution is as elegant as a simple "with asyncio.lock() ". 
Also, providing a warning: "asyncio primitives are not thread-safe," is good, so I need to prepare for the consequences with wait_for instead of await when I use asyncio in a multithreading context .. and that could be done .... 
However, the reminder,asynccio is not threat-safe means I can get into a situation of a deadlock with asyncio.lock() more likely then I thought -- but then what ??? Accept that statements are not executed without any message ... ?? Threading gave us a solution with RLock() and a timeout  ... Pls do this for asyncio.lock() as well. 
Or is the consequence: don't use asyncio.lock() anymore and threading.RLock() instead as soon as the app is multi-threading -- In that case I would suggest to include a more explicit disclaimer in the documentation ...

**Comment by gvanrossum** [comment]
This really should go to discuss.python.org first.

--Guido (mobile)

**Comment by kumaraditya303** [comment]
I am -1 on adding this to stdlib, this is better off being a package on pypi for now.
