### ISSUE TITLE
Too long path for File handling in open method

### ISSUE THREAD

**Issue by hirezadehghani** [python/cpython#121412]
# Bug report

### Bug description:

The open method for opening a file with too long path showing error that
_Exception has occurred: FileNotFoundError
_
otherwise error handler should get too long path error or the path variable support files in too long path I think that error maybe for that.

```python

file = open("/home/user/dir1/dir2/dir3/dir4/dir5/dir6/dir7/dir8/dataset/f1.txt")
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello!
We have a plenty of tests for long paths, so I think on CPython side is nothing to do. Are you sure that your file really exists?
Can you show the output from ``cat /home/user/dir1/dir2/dir3/dir4/dir5/dir6/dir7/dir8/dataset/f1.txt``?

**Comment by hirezadehghani** [comment]
yes my file exists already.
when I put my program and it's file to the /home/ it's works!
my directory is not have space in their names.

**Comment by hirezadehghani** [comment]
ok. 
`
germany usa 
apple banana orange
my name is Reza
`

**Comment by Eclips4** [comment]
Can you show the full traceback, please?

**Comment by hirezadehghani** [comment]
sure,

Exception has occurred: FileNotFoundError
[Errno 2] No such file or directory: 'f1.txt'
  File "/home/***/Documents/***/***/*-*/*-*/*/*-*/main.py", line 89, in <module>
    f = open("f1.txt")
FileNotFoundError: [Errno 2] No such file or directory: 'f1.txt'

file exists just in the main.py directory.

**Comment by Eclips4** [comment]
At first glance, the problem might be that you are running the interpreter from a different location than where "f1.txt" is located. If you are currently in the same directory as "main.py"(as far I understand the "f1.txt" is located at the same place), everything should be fine, but if you do something like `python path/to/directory/main.py`, you should specify the absolute path to "f1.txt". In the traceback you provided, I saw a relative path, which could be causing the issue.
