### ISSUE TITLE
PyGILState_Ensure() deadlocks when accessed from other C++ threads

### ISSUE THREAD

**Issue by cslr** [python/cpython#121463]
# Bug report

### Bug description:

Following python c api code deadlocks and does nothing on Ubuntu 24.04 LTS x86_64 gcc.

```
/*
 * This code deadlocks on python3-dev 3.12.3 (ubuntu 24.04 lts)
 *
 * g++ python_thread_test.cpp `python3-config --cflags --libs --embed`
 * ./a.out
 *
 * uname:
 * Linux softice 6.8.0-36-generic SMP PREEMPT_DYNAMIC x86_64 GNU/Linux
 */

#include <Python.h>
#include <thread>
#include <vector>
#include <iostream>


void thread_function() {
    // Ensure this thread has the GIL
    PyGILState_STATE gstate = PyGILState_Ensure();

    // Execute some Python code
    PyRun_SimpleString("print('Hello from std::thread!')");

    PyRun_SimpleString("print('Thread operation completed!')");

    // Release the GIL
    PyGILState_Release(gstate);
}

int main() {
    // Initialize the Python Interpreter
    Py_Initialize();

    // Create a vector of threads
    std::vector<std::thread> threads;

    // Launch threads
    for (int i = 0; i < 5; ++i) {
        threads.push_back(std::thread(thread_function));
    }

    // Join threads
    for (auto& t : threads) {
        t.join();
    }

    // Finalize the Python Interpreter
    Py_Finalize();

    return 0;
}
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
``thread_function`` calls ``PyGILState_Ensure`` twice and calls ``PyGILState_Release`` only once.

The call to ``PyGILState_Ensure`` after ``Py_END_ALLOW_THREADS`` is not necessary.

**Comment by cslr** [comment]
> `thread_function` calls `PyGILState_Ensure` twice and calls `PyGILState_Release` only once.
> 
> The call to `PyGILState_Ensure` after `Py_END_ALLOW_THREADS` is not necessary.

Oh. There was indeed bug in the example. I updated the example and it STILL deadlocks. (My larger software project deadlocks when it calls from threads to python and this example illustrates it.)

**Comment by cslr** [comment]
Oh. There was a stupid bug in the example but it still deadlocks after fixing it. Why?
  Tomas
On Sun, Jul 7, 2024 at 22:26, Ronald Oussoren ***@***.***&gt; wrote:  thread_function calls PyGILState_Ensure twice and calls PyGILState_Release only once.
The call to PyGILState_Ensure after Py_END_ALLOW_THREADS is not necessary.

**Comment by ronaldoussoren** [comment]
You should also release the GIL in the main thread, the easiest solution for that is to move the code that joins the worker threads into a Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS block.

That's needed because Py_Initialize also acquires the GIL and non of the code you're running on the main thread releases it.

**Comment by cslr** [comment]
Hi
Ok. It now works if I use saveThread which releases GIL in main(). However, I think it’s not good practice having to release GIL unless you call PyGILState_Ensure().
  Tomas
On Sun, Jul 7, 2024 at 23:12, Ronald Oussoren ***@***.***&gt; wrote:  You should also release the GIL in the main thread, the easiest solution for that is to move the code that joins the worker threads into a Py_BEGIN_ALLOW_THREADS/Py_END_ALLOW_THREADS block.
That's needed because Py_Initialize also acquires the GIL and non of the code you're running on the main thread releases it.

**Comment by ronaldoussoren** [comment]
> However, I think it’s not good practice having to release GIL unless you call PyGILState_Ensure().

You have to release the GIL when you run code that owns the GIL and want to give another thread the chance that get the GIL and run python code.  This may happen when you call a CPython API function that invokes python code, but even then the GIL will be reacquired before such an API call returns.

E.g.

```c

PyObject* someValue = ...; // Acquire a Python reference

PyObject* attribute = PyObject_GetAttrString(someValue, "key");

```

The API contract says that the GIL must be owned by the thread that calls ``PyObject_GetAttrString``. During that call the implementation may release and reacquire the GIL (for example when "someValue" is a Python class the runs "enough" bytecode in its ``_getattr__`` method).  Regardless of that thread will (re)own the GIL by the time ``PyObject_GetAttrString`` returns.

To ensure that the thread releases the GIL and other threads have enough time to run you have to explicitly release the GIL using ``Py_BEGIN_ALLOW_THREADS`` or similar code.

That's similar to how reference counts are managed: When running Python bytecode the interpreter will manage reference counts (and the GIL) for you, when running C code you'll have to manage both manually.
