### ISSUE TITLE
Barrier hangs indefinitely when arg `parties` < 0 or invalid type

### ISSUE THREAD

**Issue by pygeek** [python/cpython#121474]
# Bug report

### Bug description:

`threading.Barrier` at no point checks for valid `parties`. `parties`, of a negative value, or invalid type hang indefinitely on `.wait()`. This behavior is inconsistent from the behavior of any other `threading` primitives, which either conduct sanity checks on args during initialization, or fail at some point in their execution.

Steps to reproduce:

```python
from threading import Barrier
# negative
barrier = Barrier(-1) # <threading.Barrier at 0x10aa789b0: waiters=0/-1>
barrier.wait()

# invalid type string
barrier = Barrier("test") # <threading.Barrier at 0x10ae64980: waiters=0/test>
barrier.wait()

# invalid type float
barrier = Barrier(0.5) # <threading.Barrier at 0x10aa7a570: waiters=0/0.5>
barrier.wait()

# invalid type object
barrier = Barrier(object()) # <threading.Barrier at 0x10ae4f500: waiters=0/<object object at 0x10a878730>>
barrier.wait()
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-121480
* gh-122443
* gh-122444

**Comment by graingert** [comment]
asyncio.Barrier has this validation https://github.com/python/cpython/blob/3.12/Lib/asyncio/locks.py#L457

**Comment by pygeek** [comment]
> https://github.com/python/cpython/blob/3.12/Lib/asyncio/locks.py#L457

This is not related to `async.Barrier`. This is `threading.Barrier`

**Comment by graingert** [comment]
> > https://github.com/python/cpython/blob/3.12/Lib/asyncio/locks.py#L457
> 
> This issue is not related to `async.Barrier`. This is a bug in `threading.Barrier`
> 
> https://github.com/python/cpython/blob/3.12/Lib/threading.py#L670

Yeah my point is that asyncio.Barrier has this validation so threading.Barrier should have it also
