### ISSUE TITLE
The pyrepl cache doesn't play well with history

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#121499]
Type the following in the REPL:

```
>>> def foo():
...     x = 1
...     y = 2
...     z = 3
...
>>> def bar():
...     return 42
...
```

Now press up arrow 3 times to go to the `foo` function. The REPL shows:

```
>>> def bar():
...     x = 1
...     y = 2
...     z = 3
```

which is a weird mix between the two entries. 

I have bisected this to 32a0faba439b239d7b0c242c1e3cd2025c52b8cf

### Linked PRs
* gh-121531
* gh-121679

**Comment by pablogsal** [comment]
CC @godlygeek

**Comment by picnixz** [comment]
Could it be related to #120460?
