### ISSUE TITLE
Speed up `socket.errorTab` and lazy import `selectors`

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#121423]
# Feature or enhancement

![socket](https://github.com/python/cpython/assets/71213467/2d5674b2-8a9f-44cb-bdcf-e34ead4ca362)

```
>python -m timeit -n 1000 -s "import socket" "print(socket.__all__)"
1000 loops, best of 5: 407 usec per loop

>python -m timeit -n 1000 -s "import socket" "print(socket.__all__)"
1000 loops, best of 5: 352 usec per loop
```
1.15x faster

### Linked PRs
* gh-121424

**Comment by vstinner** [comment]
Implemented by https://github.com/python/cpython/commit/7bd964dbbe301059f3971b1be281bee0938bc70a.
