### ISSUE TITLE
PEP 703 Deferred reference counts

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#121459]
# Feature or enhancement

### Proposal:

[PEP 703](https://peps.python.org/pep-0703/#deferred-reference-counting) proposes deferred reference counting to reduce contention between threads on shared objects' reference count fields.

This issue is not in conflict with Faster CPython's scheme of fully removing reference counts in the eval loop. In fact, some of the work runs parallel to it and will actually help it.

There are 3 wins I can observe right now:
* deferring `LOAD_GLOBAL`
* deferring `LOAD_ATTR`
* deferring frames' strong references on the code object and function (this is the hardest of the three)

I shall proceed in this order.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-123128
* gh-124085
* gh-124101
* gh-124894
* gh-125711

**Comment by Fidget-Spinner** [comment]
This is implemented now.

**Comment by picnixz** [comment]
What about https://github.com/python/cpython/pull/124101? should this one be considered as optional?

**Comment by Fidget-Spinner** [comment]
@picnixz I'm waiting for the porting over the specializing intepreter to free threaded build to play out. If that works for LOAD_ATTR we wont need the PR anymore.
