### ISSUE TITLE
`os.path.normpath` documentation is not correctly indented

### ISSUE THREAD

**Issue by CBerJun** [python/cpython#121461]
# Documentation

https://github.com/python/cpython/blob/b765e4adf858ff8a8646f38933a5a355b6d72760/Doc/library/os.path.rst?plain=1#L384-L402

Note that on this line

https://github.com/python/cpython/blob/b765e4adf858ff8a8646f38933a5a355b6d72760/Doc/library/os.path.rst?plain=1#L392

a space is missing before `.. note::` directive.

### Linked PRs
* gh-121466
* gh-121472
* gh-121473

**Comment by sobolevn** [comment]
@CBerJun maybe you want to send a PR? :)

**Comment by terryjreedy** [comment]
When rendered, the missing space for the note directive results in an extra indent for the preceding paragraph.
```
os.path.normpath(path)

        Normalize a pathname by collapsing redundant separators ...

    Note ...
```
Also, the Changed item gets incorporated into the note.  Ugly.  Thanks for this issue and PR.
