### ISSUE TITLE
python loses track of re-assignment of variable

### ISSUE THREAD

**Issue by wyzarddoc72** [python/cpython#121448]
# Bug report

### Bug description:

```python

import sys
import tkinter as tk
from tkinter import ttk
from tkinter import messagebox
import os.path
import glob
import serial
import re

my_window = tk.Tk()
my_window.geometry('450x450')
my_window.title(' BaudRate test')

font1=('Times',18,'normal')

# need 2 things to happen- 1 put keys in a string ariable to send to combobox
# 2 function acess where int is returned for baudrate

#b_str = ''
#b_int = 0
global b_str
global b_int
global fb_strn 
global fb_intn 

b_str = tk.StringVar(my_window,)
b_int = tk.IntVar()

fb_strn = tk.StringVar()
fb_intn = tk.IntVar()

port_sel = tk.StringVar()
parm_sel_int = tk.IntVar()

var_parm = tk.StringVar()
var_parm_int = tk.StringVar()

parm_dic1 = tk.StringVar()



def baud_func(in_choice):
    '''function called with 'baud_str' returns string of values
        function called with string number returns integer of same [key] see print Statements'''
    global b_str
    global b_int
    #b_str = ''
    #b_int = 0
    baudrate = {'9600':9600,   # must use number as key and string as value 
           '19200':19200,  # tk.String var instead of int
           '38400':38401,
           '57600':57600,
           '115200':115200,
           } 
    if in_choice == 'baud_str':
        b_str = ''
        b_str = list(baudrate.keys())
    elif in_choice != 'baud_str':
        b_str = ''
        b_str = int(baudrate[in_choice])
    else: print("Need a Choice")
    return  b_str
    # Use examples
#print(baud_func('baud_str'))    
#print(type(baud_func('9600')))
#print(baud_func('38400'))

def fixS_baud():
    joe = str(baud_func('baud_str'))
    fb_strn.set(joe)
    return fb_strn

def fixI_baud():
    joe = baud_func('38400')
    print(type(joe))
    fb_intn.set(joe)
    return fb_intn

#print('tkStringVar print',fb_strn.get())
fixS_baud()

print('tkStringVar1 print',fb_strn.get())
fixI_baud()
print('tkStringVar1 print',fb_intn.get())

```

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by wyzarddoc72** [comment]
When run get's a tk.StringVar error but upon printing shows tk.IntVar is the type of variable can't be an error if value is int and sent to int tk.IntVar

**Comment by terryjreedy** [comment]
Please specify the claimed error.  What got, what expected.  Then reduce your code to the absolute minimum needed to exhibit the problem.

**Comment by wyzarddoc72** [comment]
Read my post and try the code and you will see the problem if your a real person
    On Saturday, July 6, 2024 at 05:40:14 PM MDT, Terry Jan Reedy ***@***.***> wrote:  
 
 


Please specify the claimed error. What got, what expected. Then reduce your code to the absolute minimum needed to exhibit the problem.

**Comment by gaogaotiantian** [comment]
> Read my post and try the code and you will see the problem if your a real person

This is not polite and please follow the code of conduct. Having a minimum reproducible example and a detailed description of your problem is important for us to diagnose the issue.

**Comment by wyzarddoc72** [comment]
you were provided the code and this is the error message
 "message": "Argument of type \"list[str] | int | StringVar\" cannot be assigned to parameter \"x\" of type \"ConvertibleToInt\" 
I am not polite when it comes to trite answers from legitimate complaints from responders who are too lazy to try the code I sent that exhibits the problem. I have 50+ years programming experience so if you are able to follow the code I sent without running you will see the statements are correct according to the rules of python, the problem is within the interpreter the object types are described by the print statements and according to them their should be no type conversion problems yet their are.

    On Saturday, July 6, 2024 at 07:25:37 PM MDT, Tian Gao ***@***.***> wrote:  
 
 



Read my post and try the code and you will see the problem if your a real person


This is not polite and please follow the code of conduct. Having a minimum reproducible example and a detailed description of your problem is important for us to diagnose the issue.

**Comment by itamaro** [comment]
Please direct questions to the [Python Help forum](https://discuss.python.org/c/users/7).

I don't see any evidence here that there's a bug in Python itself.
I read your post several times, and couldn't reproduce the reported error using Python 3.12.
If you still think you found a bug in Python, please follow the suggestions given to you by others to provide a clear and minimal reproducer, using a recent version of Python, and without violating the [Code of Conduct](https://policies.python.org/python.org/code-of-conduct/) or treating volunteers like they owe you anything.
