### ISSUE TITLE
3.11 documentation has no changelog entry for 3.11.9

### ISSUE THREAD

**Issue by sparrowt** [python/cpython#121484]
# Documentation

As listed on https://www.python.org/downloads/ the latest release of 3.11 is **3.11.9**

However on the changelog for 3.11 the latest release is **3.11.8** ⚠️
https://docs.python.org/3.11/whatsnew/changelog.html

Comparing with 3.12 where the latest release is 3.12.4, as expected the 3.12 changelog has 3.12.4 ✔️
https://docs.python.org/3.12/whatsnew/changelog.html

Is this a documentation bug that 3.11.9 isn't listed on the [3.11 changelog](https://docs.python.org/3.11/whatsnew/changelog.html)?

In fact _all_ of the documentation when on the `3.11` section says 3.11.8 in the title etc e.g. https://docs.python.org/3.11/index.html

**Comment by Eclips4** [comment]
cc @pablogsal

**Comment by hugovk** [comment]
See https://github.com/python/docsbuild-scripts/issues/169#issuecomment-1749683481, docs for security branches need to be built manually.

And see also https://github.com/python/cpython/issues/113726 about 3.8 and 3.9.

I think we're missing something in the process here.

What is the process for rebuilding docs when we make security releases? Where is this (or where should it be) documented? PEP 101?

cc @JulienPalard

**Comment by pablogsal** [comment]
@ambv you know if we are missing something? This was handled correctly for 3.10 automatically IIRC

**Comment by ambv** [comment]
We haven't built the docs automatically for sec branches ever.

**Comment by sparrowt** [comment]
Ok thanks for looking into it - it does seem to be a missing step in some process and is still showing 3.11.8 for me.

**Comment by ambv** [comment]
We will rebuild all docs for old versions late this week once the new security versions are released.

**Comment by sparrowt** [comment]
FYI the same has happened for 3.11.11, 3.10.16 and 3.9.21 which are all missing from their respective changelog pages (while 3.12.8 and 3.13.1 released on the same day are present on their changelog.html pages by contrast).

Perhaps this is normal 2 days after the release, but just flagging it in case it isn't. Thanks everyone!

https://docs.python.org/3.13/whatsnew/changelog.html#python-3-13-1-final ✅
https://docs.python.org/3.12/whatsnew/changelog.html#python-3-12-8-final ✅
https://docs.python.org/3.11/whatsnew/changelog.html) missing latest
https://docs.python.org/3.10/whatsnew/changelog.html missing latest
https://docs.python.org/3.9/whatsnew/changelog.html missing latest

**Comment by hugovk** [comment]
Security branches need manual builds and it takes ~16 hours for a full build (all languages and all formats -- HTML, PDF, etc).

3.11 is now done, 3.10 has begun: https://github.com/python/docsbuild-scripts/issues/216#issuecomment-2525095448

Tip: you can also check the version in the title and the timestamp in the footer of the homepage: for example, https://docs.python.org/3.10/ still on 3.10.15 and "Last updated on Sep 09, 2024".

**Comment by hugovk** [comment]
3.9-3.11 are now rebuilt:

* 3.11: 2024-12-07 11:37:08,426 INFO: Full build done (16h 18m 2s).
* 3.10: 2024-12-08 00:38:35,718 INFO: Full build done (12h 49m 46s).
* 3.9: 2024-12-09 09:35:58,914 INFO: Full build done (15h 18m 37s).

Thanks for the reminder!

**Comment by sparrowt** [comment]
Thanks! I wonder if there's some checklist (or nag bot) that could be updated so that the process is more future-proof?

**Comment by hugovk** [comment]
Yes, this was partly a bus factor issue, afaik it used to be just one person had access or knew how to do manually rebuilds.

I've now documented what's needed at https://github.com/python/docsbuild-scripts#manually-rebuild-a-branch, and two people plus four release managers have access to redo them. I'll tell the other RMs about this (although 3/4 are already in this issue :)
