### ISSUE TITLE
stale documentation about the minimum supported Windows version

### ISSUE THREAD

**Issue by partev** [python/cpython#121458]
# Documentation

["Using Python on Windows"](https://docs.python.org/3.14/using/windows.html)  section of the documentation says:

> This means that Python 3.14 supports Windows 8.1 and newer. If you require Windows 7 support, please install Python 3.8.

However, Windows 8.1 ESU has been [discontinued in January of 2023](https://support.microsoft.com/en-us/windows/windows-8-1-support-ended-on-january-10-2023-3cfd4cde-f611-496a-8057-923fba401e93) and therefore according to PEP 11 has been unsupported starting from python-3.12. It is not clear why we are mentioning Windows 7, so I recommend removing that sentence.

[Python 3.12 was released in October of 2023](https://docs.python.org/3.12/whatsnew/3.12.html) and therefore no longer supported Windows 8.1

### Linked PRs
* gh-121452

**Comment by eryksun** [comment]
> However, Windows 8.1 ESU has been discontinued in January of 2023

Note that Microsoft didn't offer ESU support for Windows 8.1. Regardless, PEP 11 is based on the extended support lifetime, not ESU. Extended support for Windows 8.1 ended on 10 January 2023, and Windows Server 2012 R2 was supported until 10 October 2023. Python 3.12 was released just before the latter date, on 2 October 2023, but it was decided that 3.12 would not support either Windows 8.1 or Windows Server 2012 R2.

Extended support for Windows Server 2016 will end on 12 January 2027. The version of Python that comes after 3.14 will probably be the last to support Server 2016. This corresponds to Windows 10 1607 (i.e. `NTDDI_WIN10_RS1`).

**Comment by willingc** [comment]
Given @zooba's response on the linked PR, I'm going to close this documentation issue as not planned.

If you wish to open a wider-scoped issue that addresses code changes, that would be helpful.

**Comment by willingc** [comment]
Closing
