### ISSUE TITLE
Extending an object's list attribute causes all new instances of the class to leak the value at __init__

### ISSUE THREAD

**Issue by serhez** [python/cpython#121527]
# Bug report

### Bug description:

If a list property of an object is extended (i.e., using `list.extend(list2)`), all new class instances will have the extended value from previous instances leaked into the new instance's property. This can be solved if you specify a new value for the property via an `__init__` argument. This is not solved with default `__init__` arguments. 

We can define some class:

```python
class _Problem:
    def __init__(
        self,
        uid: str,
        lid: str,
        description: str,
        parent: str | None = None,
        depth: int = 1,
        dependencies: list[str] = [],
        instructions: str = "",
        solution: str | None = None,
    ):
        self._uid = uid
        self._lid = lid
        print(f"__init__: {dependencies}")
        self._dependencies = dependencies
        self._parent = parent
        self._depth = depth
        self.description = description
        self.instructions = instructions
        self.solution = solution

    @property
    def dependencies(self) -> list[str]:
        return self._dependencies

    @dependencies.setter
    def dependencies(self, value: list[str]):
        self._dependencies = value
```

Then, we can test this behavior as:

```python
p = _Problem("1000", "1000", "Desc")
print(f"First problem (before): {p.dependencies}")
p.dependencies.extend(["1001", "1002"])
print(f"First problem (after): {p.dependencies}")

p = _Problem("1005", "1005", "Desc")
print(f"Next problem: {p.dependencies}")  # this leaks 

p = _Problem("1008", "1008", "Desc")
print(f"Next problem: {p.dependencies}")  # this also leaks

p = _Problem("1010", "1010", "Desc", dependencies=[])
print(f"Next problem: {p.dependencies}")  # this does not leak
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by ronaldoussoren** [comment]
see this FAQ: https://docs.python.org/3/faq/programming.html#why-are-default-values-shared-between-objects

The default value of a function/method is evaluated when creating the function, not when calling it. This results in sharing the same instance of a list object between instances, which is why modification of the "dependencies" attribute in one instance affects other instances.

This is not a bug, but expected behaviour. This can be confusing, but is also useful (as described in the FAQ). Changing this behaviour would break too much existing code.

**Comment by serhez** [comment]
Oh wow. Thank you for the super quick reply @ronaldoussoren! It's been super helpful.

I am guessing a lot of other people may have said this before, but even though I understand now why it happens (and it makes sense given Python rules), it would be great to change this so that default values are initialized per-call and not per-definition. It's not intuitive and it would've saved me (and likely others) hours of debugging. In any case, using `None` as default argument values seems like the workaround here. Thanks again! :)
