### ISSUE TITLE
New REPL does not work well with Tkinter

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#121588]
# Bug report

The simplest example, import Tkinter and create the root widget:
```pycon
>>> import tkinter
>>> root = tkinter.Tk()
>>> █
```
A new Tk window appeared and grabbed the focus. Switch back to the terminal and press the `<Up>` key --  nothing changed:
```pycon
>>> import tkinter
>>> root = tkinter.Tk()
>>> █
```
Press it again -- the last entered line appeared for editing:
```pycon
>>> import tkinter
>>> root = tkinter.Tk()
>>> root = tkinter.Tk()█
```
Press the `<Enter>` key and the edited line will be replaced by another line which will execute:
```pycon
>>> import tkinter
>>> root = tkinter.Tk()
>>> import tkinter
>>> █
```

cc @pablogsal

**Comment by serhiy-storchaka** [comment]
If press other cursor moving keys, the current line will be replaced by the correct line. But there are glitches: when you press the `<Left>` key, cursor moves right, and only when you continue to press it again it moves left (but I am not sure about its true position). And the opposite for for the `<Right>` keys.

**Comment by pablogsal** [comment]
Can you check if https://github.com/python/cpython/issues/121498 fixes the problem?

**Comment by pablogsal** [comment]
I tested manually and it fixes it on my end. Do you want to keep this open until we land https://github.com/python/cpython/pull/121498 ?

**Comment by serhiy-storchaka** [comment]
Yes, it solves this issue.

Closing as a duplicate of #121497.
