### ISSUE TITLE
dbm.sqlite3.open() raises an exception if file does not exist

### ISSUE THREAD

**Issue by srittau** [python/cpython#121573]
# Bug report

### Bug description:

Using Python 3.13b3 with a working sqlite3 module, the following code will always raise an exception:

```python
import dbm.sqlite3 as dbm

dbm.open("foo")
```

This will raise the rather unhelpful exception:

```
Traceback (most recent call last):
  File "/opt/ansible/pyenv/versions/3.13.0b3/lib/python3.13/dbm/sqlite3.py", line 64, in __init__
    self._cx = sqlite3.connect(uri, autocommit=True, uri=True)
               ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
sqlite3.OperationalError: unable to open database file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/srittau/foo.py", line 4, in <module>
    dbm.open("foo")
    ~~~~~~~~^^^^^^^
  File "/opt/ansible/pyenv/versions/3.13.0b3/lib/python3.13/dbm/sqlite3.py", line 140, in open
    return _Database(filename, flag=flag, mode=mode)
  File "/opt/ansible/pyenv/versions/3.13.0b3/lib/python3.13/dbm/sqlite3.py", line 66, in __init__
    raise error(str(exc))
dbm.sqlite3.error: unable to open database file
```

If I create the file `foo` (e.g. by running `touch foo` beforehand), everything works as expected. [The documentation](https://docs.python.org/3.13/library/dbm.html#module-dbm.sqlite3) doesn't mention that the file needs to exist already and the exception message is not terribly helpful either.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by srittau** [comment]
Ignore me. It seems that by default, only existing databases are read.

**Comment by erlend-aasland** [comment]
Ideally you should only see the `dbm.sqlite3.error` exception. We might want to tweak that.
