### ISSUE TITLE
asyncio module state should be locked with mutexes in free-threaded builds

### ISSUE THREAD

**Issue by Fidget-Spinner** [python/cpython#121621]
# Feature or enhancement

### Proposal:

Please see issue title.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-121622
* gh-121695
* gh-121774
* gh-121864
* gh-121915
* gh-121939
* gh-121943
* gh-122046
* gh-122048

**Comment by colesbury** [comment]
I think we also want to make `enter_task`, `leave_task`, and `swap_current_task` behave atomically. For example, `enter_task` makes two dict API calls that individually lock the dictionary, but the combined operation isn't atomic.

I can think of two strategies for this:
1) Try to replace multiple API calls with a single call. For example, I think `enter_task` may be able to use `PyDict_SetDefaultRef` and `leave_task` may be able to use `_PyDict_DelItemIf` with some modifications.
2) Use a critical section to lock the dict and use the "lock held" variants.

**Comment by Fidget-Spinner** [comment]
Fixed.
