### ISSUE TITLE
Remove explicit `object` inheritance in some tests in `test_unittest`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#121692]
# Bug report

### Bug description:

Some tests inside `test/test_unittest` still explicitly inherit from `object`:

https://github.com/python/cpython/blob/0a26aa5007cb32610366c31fbac846b5fe2f4f90/Lib/test/test_unittest/test_case.py#L30-L32

We should remove those.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121696

**Comment by GovernmentPlates** [comment]
On it
