### ISSUE TITLE
MimeTypes.add_type() is missing from the docs

### ISSUE THREAD

**Issue by steverep** [python/cpython#121658]
# Bug report

### Bug description:

```python
from mimetypes import MimeTypes

m = MimeTypes()
m.add_type # type checking error
```

The `add_type` method is not defined on the class interface, and also not defined in the RST file for the docs.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux, macOS, Windows

### Linked PRs
* gh-121665

**Comment by tomasr8** [comment]
Seems like the `add_type` method is missing from typeshed:
https://github.com/python/typeshed/blob/6a9b53e719a139c2d6b41cf265ed0990cf438192/stdlib/mimetypes.pyi#L42

**Comment by Eclips4** [comment]
Hello! Thanks for the report.
As @tomasr8 said, type checking error is coming from the fact that `Mimetypes.add_type` isn't defined in the typeshed stubs. Actually, yes, we need to update our docs to add this method. Would you like to send a pull request?

**Comment by Eclips4** [comment]
FYI, here's thePR for typeshed: https://github.com/python/typeshed/pull/12329

**Comment by stinovlas** [comment]
I'm working on this during EuroPython 2024 sprint.

**Comment by stinovlas** [comment]
> I'm working on this during EuroPython 2024 sprint.

Fixed in #121665.

**Comment by RafaelJohn9** [comment]
@Eclips4  has this issue been fixed? if not I would like to be assignedd

**Comment by Eclips4** [comment]
> @Eclips4 has this issue been fixed? if not I would like to be assignedd

There's an existing PR which solves the issue: #121665. We're just waiting for someone with ability to merge it.

**Comment by RafaelJohn9** [comment]
Aah nice 👍🙂
