### ISSUE TITLE
Incomplete test coverage for `ast.get_docstring`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#121671]
# Bug report

### Bug description:

The `ast.get_docstring` is missing test coverage:

![image](https://github.com/user-attachments/assets/82d0275e-79cd-4f91-a4c2-1683cdcfb0c9)

I'll send a PR with some additional tests ;)

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121674
* gh-121690
* gh-121691

**Comment by encukou** [comment]
Thank you for the fix!
