### ISSUE TITLE
pathlib docs: Method Path.absolute is missing from docs <v3.11 (also distinction from Path.resolve and rel. topics)

### ISSUE THREAD

**Issue by e-d-n-a** [python/cpython#121682]
# Documentation

Method `Path.absolute` is missing from docs <v3.11 (I checked all of them: 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 3.10).
It only appears in docs for v3.11+[3], although it is part of the class Path since `pathlib` was added in v3.4[1,2].

It would be useful to have, as one needs to see the distinction between `Path.absolute` and `Path.resolve` (which is included in the docs since v3.4) in regards to normalization or resolving symlinks for example (see docstrings or docs for v3.11[3]).

**Docstrings taken from `pathlib.py` of v3.9.17:**
(I appreciate the explicit mentioning of the treatment of '.' and '..' with Path.absolute in this version!)
```
    def absolute(self):
        """Return an absolute version of this path.  This function works
        even if the path doesn't point to anything.

        No normalization is done, i.e. all '.' and '..' will be kept along.
        Use resolve() to get the canonical path to a file.
        """

    def resolve(self, strict=False):
        """
        Make the path absolute, resolving all symlinks on the way and also
        normalizing it (for example turning slashes into backslashes under
        Windows).
        """
```
(these functions also appear next to each other in the code[4])

It would be nice, if the topics of "path normalization" and "symlink resolving" would be described more clearly in the context of those functions. The handling of '..' is mentioned in the context of `Path.resolve` and also `PurePaths` (in constructor and `PurePath.parent`).
Yet, the trap with `Path.absolute` is only mentioned by the documenation for `Path.resolve` stating:
`“..” components are also eliminated (this is the only method to do so):`

**Refs:**

1. [Blame for Method Path.absolute()](https://github.com/python/cpython/blame/3.9/Lib/pathlib.py#L1193)
2. [Commit including pathlib.py for v3.4](https://github.com/python/cpython/commit/31119e4f10d2905d0ed2c21a012dd9f45ec2fa61)
3. [Path.absolute() in Docs for v3.11](https://docs.python.org/3.11/library/pathlib.html#pathlib.Path.absolute)
4. [Path.absolute and Path.resolve in code of v3.11.9](https://github.com/python/cpython/blob/de54cf5be371a6f5e2e9f208c38def5f81d3ef02/Lib/pathlib.py#L971) (docstring for Path.absolute is simplified here though!)

**Comment by Eclips4** [comment]
Hello! Thanks for the report.
Unfortunately, we cannot fix that due to Python policy: versions older than 3.12 accept only security fixes. This one is not about security :(

**Comment by e-d-n-a** [comment]
I now found the issue (#73874) now, that actually discussed all this thoroughly from 2017 to 2023.
