### ISSUE TITLE
mpmath bug? 

### ISSUE THREAD

**Issue by tinyCtim** [python/cpython#121627]
# Bug report

### Bug description:

```python

# pi.py - 7/3/24

import mpmath

def machin_formula(precision):
    mpmath.mp.dps = precision  # Set the precision (number of decimal places)

    # Machin's formula: pi/4 = 4 * arctan(1/5) - arctan(1/239)
    pi_approx = 4 * (4 * mpmath.atan(1/5) - mpmath.atan(1/239))
    return pi_approx

# Calculate pi with up to n digits of precision
print("How many digits do you want?")
n = input()
pi_approximation = machin_formula(n)

print("Approximation of pi using Machin's formula")
print(pi_approximation)

```
leeunix@Lee:~$ python pi.py
How many digits do you want?
30
Approximation of pi using Machin's formula
3.14159265358979341070329540415

Only the first 16 digits are correct.

leeunix@Lee:~$ python
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
mpmath is a third-party package, not a part of CPython, so you should report this to the mpmath project, not here. Its issue tracker is at https://github.com/mpmath/mpmath/issues.

**Comment by tinyCtim** [comment]
Jelle, thank you so much. A friend has solved the problem
***@***.***:~$ python pi.pyHow many digits do you want?30Approximation of pi using Machin's ***@***.***:~$ nano ***@***.***:~$ cat pi.py
# pi.py - 7/3,11/24# fixed by Aaron West
import mpmath
def machin_formula(precision):    mpmath.mp.dps = precision  # Set the precision (number of decimal places)    # Machin's formula: pi/4 = 4 * arctan(1/5) - arctan(1/239)    pi_approx = 4 * (4 * mpmath.atan(1/mpmath.mpmathify(5)) - mpmath.atan(1/mpmath.mpmathify(239)))    return pi_approx
# Calculate pi with up to n digits of precisionprint("How many digits do you want?")n = input()pi_approximation = machin_formula(n)
print("Approximation of pi using Machin's formula")print(pi_approximation)
***@***.***:~$

    On Thursday, July 11, 2024 at 12:25:56 PM EDT, Jelle Zijlstra ***@***.***> wrote:  
 
 


mpmath is a third-party package, not a part of CPython, so you should report this to the mpmath project, not here. Its issue tracker is at https://github.com/mpmath/mpmath/issues.
