### ISSUE TITLE
Incorrect error message for `yield from`

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#121657]
# Bug report

### Bug description:

```python
% ./python.exe -c 'yield x'
  File "<string>", line 1
SyntaxError: 'yield' outside function
% ./python.exe -c 'yield from x'
  File "<string>", line 1
SyntaxError: 'yield' outside function
% ./python.exe -c 'async def f(): yield from x'
  File "<string>", line 1
SyntaxError: 'yield from' inside async function
```

The middle one should also say "yield from".

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-121680
* gh-121722
* gh-121768
* gh-121769
* gh-121961
* gh-121962

**Comment by JelleZijlstra** [comment]
This is very easy to fix but I'll leave it for a bit in case a new contributor wants to get familiar with making a CPython change. Pointers for the fix:

* The code to be changed is in `compile.c`, currently at line 6122 (search for "'yield' outside function" if it changes).
* Tests should be added, probably around here `Lib/test/test_generators.py:SyntaxError: 'yield' outside function`. The existing test only tests `yield`, not `yield from`; we should add more tests.

**Comment by serhiy-storchaka** [comment]
I am not sure 5his should be fixed, as technically the error message is correct.

The error message in the third example is more specific because `yield` is valid here.

**Comment by gege-hoho** [comment]
I will give it a try :)

**Comment by encukou** [comment]
The existing message was technically correct, but `yield from` is definitely better.
