### ISSUE TITLE
Add `dict` move_to_end(last=False) functionality in the `OrderedDict` documentation

### ISSUE THREAD

**Issue by Drblessing** [python/cpython#121781]
# Documentation

In the [OrderedDict Objects](https://docs.python.org/3/library/collections.html#ordereddict-objects) documentation it states: 

"A regular [dict](https://docs.python.org/3/library/stdtypes.html#dict) does not have an efficient equivalent for OrderedDict’s od.move_to_end(k, last=False) which moves the key and its associated value to the leftmost (first) position."

This can easily be accomplished in two ways: 

```python
value = d.pop(key)
d = {key: value, **d}
```

```python
value = d.pop(key)  # Remove the key-value pair from the dictionary
new_dict = {key: value}  # Create a new dictionary with the key-value pair
new_dict.update(d)  # Add the rest of the original dictionary
```

**Comment by ericvsmith** [comment]
I'm not sure those qualify as "efficient".

**Comment by Drblessing** [comment]
> I'm not sure those qualify as "efficient".

You're right. Definitely not space, maybe they're not too inefficient time wise?

**Comment by blhsing** [comment]
> > I'm not sure those qualify as "efficient".
> 
> You're right. Definitely not space, maybe they're not too inefficient time wise?

The proposed workaround requires *O(n)* complexity in both space and time, while with an `OrderedDict` only *O(1)* is required in both space and time.

**Comment by Drblessing** [comment]
> > > I'm not sure those qualify as "efficient".
> > 
> > 
> > You're right. Definitely not space, maybe they're not too inefficient time wise?
> 
> The proposed workaround requires _O(n)_ complexity in both space and time, while with an `OrderedDict` only _O(1)_ is required in both space and time.

Thanks for the correction!

**Comment by Drblessing** [comment]
>The proposed workaround requires O(n) complexity in both space and time, while with an OrderedDict only O(1) is required in both space and time.

Thank you for the correction.
