### ISSUE TITLE
Discrepancy in docs for `PyModule_AddObjectRef`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#121749]
# Bug report

### Bug description:

The docs for `PyModule_AddObjectRef` say:

https://github.com/python/cpython/blob/cae15267166e217822e3c58ac22b7817162f323a/Doc/c-api/module.rst?plain=1#L520-L521

However the function actually returns `-1` in that case:

https://github.com/python/cpython/blob/cae15267166e217822e3c58ac22b7817162f323a/Python/modsupport.c#L590-L597

We should update the documentation to reflect that.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121750
* gh-121752
* gh-121753

**Comment by GovernmentPlates** [comment]
On it

**Comment by encukou** [comment]
Thank you @tomasr8 for the report and @GovernmentPlates for the fix!
