### ISSUE TITLE
`python -m asyncio` returns 0 when failing with ENOTTY in the runner thread

### ISSUE THREAD

**Issue by zvyn** [python/cpython#121711]
# Bug report

### Bug description:

The return code at the end here is `0` when it should be `25` aka `ENOTTY`:

```
import subprocess
proc = subprocess.Popen(["./python", "-m", "asyncio"], stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
with proc:
    try:
        out, err = proc.communicate()
    finally:
        proc.kill()
proc.returncode
```

note: I tested this with `--disable-gil` configured

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121714
* gh-121718

**Comment by ambv** [comment]
Thanks, Milan! ✨ 🍰 ✨
