### ISSUE TITLE
mimalloc build fails on GNU/Hurd due to undeclared 'open'

### ISSUE THREAD

**Issue by sthibaul** [python/cpython#121731]
# Bug report

### Bug description:

# Bug description:

The compilation of mimalloc on GNU/Hurd currently fails with the following error:

```
In file included from ../Objects/mimalloc/prim/prim.c:22,
                 from ../Objects/mimalloc/static.c:37:
../Objects/mimalloc/prim/unix/prim.c: In function 'mi_prim_open':
../Objects/mimalloc/prim/unix/prim.c:82:10: error: implicit declaration of function 'open'; did you mean 'popen'? [-Werror=implicit-function-declaration]
   82 |   return open(fpath,open_flags);
      |          ^~~~
      |          popen
```

This is already fixed upstream by https://github.com/microsoft/mimalloc/commit/98abfe042cbb168309832b744bbed982d81bba6b . will submit a PR containing a backport

# CPython versions tested on:

CPython 3.13.0 b3

### CPython versions tested on:

3.13

### Operating systems tested on:

Other

### Linked PRs
* gh-121732
* gh-121773

**Comment by Eclips4** [comment]
Related: #113141
