### ISSUE TITLE
arm is slower than x86

### ISSUE THREAD

**Issue by alittlesir** [python/cpython#121786]
# Bug report

### Bug description:

```python
from datetime import datetime
from multiprocessing import Queue
import time

queue = Queue()

def f1():
    for i in range(1000):
        queue.put(i)

    for i in range(10):
        begin = time.time()
        for j in range(100):
            queue.get()
        end = time.time()
        print(end-begin)
f1()
```
this is on arm
```
0.0029609203338623047
0.0026922225952148438
0.0016870498657226562
0.0030052661895751953
0.0016798973083496094
0.002278566360473633
0.0025331974029541016
0.002166748046875	 
0.002488851547241211
0.0022156238555908203

```

this is on x86
```
0.008425235748291016
0.0005388259887695312
0.0005414485931396484
0.0005414485931396484
0.0005311965942382812
0.0005342960357666016
0.0005276203155517578
0.0005342960357666016
0.0005347728729248047
0.0005359649658203125

```

Why is the get method so much slower on the arm platform than on the x86 platform? Related to the CPU instruction set? It's confusing.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by aisk** [comment]
What are the exact specifications of the two CPUs you used for comparison?

**Comment by zware** [comment]
When comparing apples to oranges, your results may be bananas.

There are too many possible variables in play here for me to believe that this is really a Python-related issue.  If you can actually trace this difference to something within our control, please provide your evidence along with a request to reopen the issue.
