### ISSUE TITLE
Incomplete test coverage for `unittest.util`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#121708]
# Bug report

### Bug description:

`safe_repr`, `sorted_list_difference` and `unorderable_list_difference` inside `unittest.util` are not properly tested. I'll send a PR shortly with some tests ;)

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121713
* gh-121737
* gh-121738

**Comment by encukou** [comment]
Thank you!
