### ISSUE TITLE
Conceptual Flaw in Python's Iterator Behavior During Collection Modification

### ISSUE THREAD

**Issue by systemX-p01** [python/cpython#121858]
# Feature or enhancement

### Proposal:

Description of the Issue:

In Python, if an element is removed from a collection during iteration, the iterator does not account for the change in the collection’s structure. Consequently, the iterator can skip the next element or continue iterating over a modified collection, leading to incorrect and unpredictable results.

Example:

Consider the following Python code:
```python
collection = [1, 2, 3, 4, 5]
iterator = iter(collection)

for item in iterator:
    if item % 2 == 0:
        collection.remove(item)
    print(collection)
```
Expected Output:

```
[1, 2, 3, 4, 5]
[1, 3, 4, 5]
[1, 3, 4, 5]
[1, 3, 5]
[1, 3, 5]
```
Actual Output:

```
[1, 2, 3, 4, 5]
[1, 3, 4, 5]
[1, 3, 4, 5]
[1, 3, 5]
```

Comparison with Other Languages:

    Java: Throws ConcurrentModificationException if the collection is modified during iteration, ensuring safety and predictability.
    C#: Throws InvalidOperationException under similar circumstances, preventing unintended behavior.
    C++ (STL): Provides iterators that handle deletions correctly but requires careful management by the developer.
    
Possible solutions:
    Provide a flag or other option not to modify the current position upon deletion or modify it in accordance to the expected logic.

### Has this already been discussed elsewhere?

No response given

**Comment by ZeroIntensity** [comment]
Unfortunately, changing this behavior would break untold amounts of code.

**Comment by ZeroIntensity** [comment]
Well, I'm not too sure what you want the behavior to be. I wouldn't see this is a "critical mistake", the following code behaves exactly as I would expect it to:

```py
collection = [1, 2, 3, 4, 5]
iterator = iter(collection)

for item in iterator:
    if item % 2 == 0:
        collection.remove(item)
    print(collection)

# [1, 2, 3, 4, 5]
# [1, 3, 4, 5]
# [1, 3, 5]
```

**Comment by systemX-p01** [comment]
``
collection = [1, 2, 3, 4, 5]
iterator = iter(collection)

for item in iterator:
    if item == 2:
        collection.remove(item)
    print(collection)

The code should remove the item which == 2, if one expected it to behave logically, that is, properly process the collection after deletion of the element. However:

Expected output:
[1, 2, 3, 4, 5]
[1, 3, 4, 5]

Initial State:

    Collection: [1, 2, 3, 4, 5]
    Iterator points to 1.

First Iteration:

    Item: 1 (not removed)
    Collection: [1, 2, 3, 4, 5]
    Iterator moves to 2.

Second Iteration:

    Item: 2 (removed)
    Collection: [1, 3, 4, 5]
    Iterator skips to 4 (next item after the removed item), skipping 3.
    
That is the problem it SHOULD NOT point to 4, should the language processed it properly or had the means to redefine the behavior.

**Comment by Eclips4** [comment]
Hello!
Our docs mentions this case in tutorial section: https://docs.python.org/3/tutorial/controlflow.html#for-statements

As @ZeroIntensity said, changing this behavior would be a breaking change. This kind of change should be widely discussed, but, honestly, it is very unlikely that it will be accepted.

**Comment by systemX-p01** [comment]
@ZeroIntensity It is possible to store context and flags in the iterators to determine if the pointer should advance on next iteration or not. Just 1 bit is enough.

**Comment by ZeroIntensity** [comment]
I think we're getting to why this doesn't exist in the first place. General sequence iterators, like the one in your example, hold two things: an object, and an index. Every time `__next__` is called, it calls `__getitem__`, and it increments the index. There's no way for it to know whether the object was updated.

If you really want, you could implement your own iterator object that knows how to handle modification for certain types.

**Comment by systemX-p01** [comment]
It is probably not the best example, but the idea is that the item should have an option to be removed in the iteration without faulty behavior of the index, that is if Remove() is called on item, it should be removed and the index should not be incremented. Also, there is a way to know the object is updated, by storing the context.

I did implement more advanced wrapper over Python iterators, which are way too limited to filter and tag long sequences. It also uses flags to track the state of the object tree being iterated.

**Comment by ZeroIntensity** [comment]
> Remove() is called on item

How would that work? Will it compare against equality or identity? What happens when two identical items are in a sequence?

**Comment by systemX-p01** [comment]
Some quick code (totally different from the correct implementation, but suitable for illustrating the concept:

```
class DataWrapper:
    def __init__(self, collection):
        self.collection = collection

    def __iter__(self):
        return CorrectIterator(self.collection)

    def __str__(self):
        return str(self.collection)

class CorrectIterator:
    def __init__(self, collection):
        self.collection = collection
        self.index = 0

    def __iter__(self):
        return self

    def __next__(self):
        if self.index >= len(self.collection):
            raise StopIteration
        item = self.collection[self.index]
        self.index += 1
        return ItemWrapper(self, item, self.index - 1)

class ItemWrapper:
    def __init__(self, iterator, item, index):
        self.iterator = iterator
        self.item = item
        self.index = index

    def __eq__(self, other):
        if isinstance(other, ItemWrapper):
            return self.item == other.item
        return self.item == other

    def remove(self):
        del self.iterator.collection[self.index]
        self.iterator.index -= 1

# Example usage:
my_data = DataWrapper([1, 2, 2, 3, 3, 2, 4, 5])
for item in my_data:
    if item == 2:
        item.remove()
    print(my_data)
```
