### ISSUE TITLE
RPM version error for python3-3.9.18-3.el9_4.1.x86_64.rpm

### ISSUE THREAD

**Issue by jeffbaraton** [python/cpython#121846]
# Bug report

### Bug description:

I believe there was a mistake when building this rpm:
python3-3.9.18-3.el9_4.1.x86_64.rpm
and probably all rpm for python3-3.9.18-3.el9_4.1
the symptom is this:
Error: Transaction test error:
  file /usr/lib/.build-id/87/e512cce7f888765e427c4bf1af79e90ff89475 from install of XXXX conflicts with file from package python3-3.9.18-3.el9_4.1.x86_64

also, when you uninstall it, you can see this warning:
  Cleanup          : python3-3.9.18-3.el9_4.1.x86_64
warning: file /usr/lib/.build-id/87/e512cce7f888765e427c4bf1af79e90ff89475: remove failed: No such file or directory

if you look at the changelog for this RPM, it is missing the latest entry for 3.9.18-3.el9_4.1
yum install yum-plugin-changelog
yum changelog python3

you can also see it here:
https://oraclelinux.pkgs.org/9/ol9-baseos-latest-x86_64/python3-3.9.18-3.el9_4.1.x86_64.rpm.html
there is not changelog entry for a "latest version 3.9.18-3.el9_4.1" . (latest is 3.9.18-3.1)

Maybe the error is that 
3.9.18-3.el9_4.1 should actually be called 3.9.18-3.1.el9
when I run python -VV from 3.9.18-3.el9_4.1
I get
Python 3.9.18 (main, Jan 24 2024, 00:00:00) 
[GCC 11.4.1 20231218 (Red Hat 11.4.1-3)]

which is the exact same date as the changelog gives for 3.9.18-3.1

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by zware** [comment]
We don't produce binaries for any Linux distribution here; you'll need to report the issue to whoever created it (Oracle Linux?).
