### ISSUE TITLE
[C API] Segmentation fault in PyUnicodeWriter when writing nothing and with initial length = 0 

### ISSUE THREAD

**Issue by picnixz** [python/cpython#121849]
# Bug report

### Bug description:

While working on accelerating fnmatch, I wanted to use the PyUnicodeWriter API instead of extracting two substrings and use concat(). I encountered a segmentation fault when attempting to write an empty range *if* the writer allocated actually 0 characters:

```C
#include <Python.h>

int main(void) {
    Py_Initialize();
    PyUnicodeWriter *writer = PyUnicodeWriter_Create(0);
    PyObject *str = PyUnicode_FromString("abc");
    PyUnicodeWriter_WriteSubstring(writer, str, 3, 3); // SEGFAULT
    Py_DECREF(str);
    PyUnicodeWriter_Discard(writer);
    Py_Finalize();
    return 0;
}
```

Note that changing `PyUnicodeWriter_Create(0)` to `PyUnicodeWriter_Create(1)` make it work:

```C
#include <Python.h>

int main(void) {
    Py_Initialize();
    PyUnicodeWriter *writer = PyUnicodeWriter_Create(1);
    PyObject *str = PyUnicode_FromString("abc");
    PyUnicodeWriter_WriteSubstring(writer, str, 3, 3); // OK!
    Py_DECREF(str);
    PyUnicodeWriter_Discard(writer);
    Py_Finalize();
    return 0;
}
```

@vstinner I can investigate or you can take the task if you want (best is to also add a test and confirm that I did not misused the API). By the way, keeping 0 as a length estimation but writing a non-empty string works: 

```C
#include <Python.h>

int main(void) {
    Py_Initialize();
    PyUnicodeWriter *writer = PyUnicodeWriter_Create(0);
    PyObject *str = PyUnicode_FromString("abc");
    PyUnicodeWriter_WriteSubstring(writer, str, 2, 3); // OK!
    Py_DECREF(str);
    PyUnicodeWriter_Discard(writer);
    Py_Finalize();
    return 0;
}
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-121875
* gh-121896

**Comment by ZeroIntensity** [comment]
This is a bug. The problem is that `_PyUnicodeWriter_Prepare` does nothing if the length is zero, and simply leaves `writer->buffer` as `NULL` (it does this for both `PyUnicodeWriter_Create` and `PyUnicodeWriter_WriteSubstring`), but it still tries to copy the characters if the buffer is `NULL`, resulting in trying to dereference a `NULL` pointer.

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/121896 to fix the bug.

**Comment by picnixz** [comment]
Fixed by https://github.com/python/cpython/pull/121896
