### ISSUE TITLE
Add A Howto Page About Using Multiple Interpreters

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#121817]
While subinterpreters are not a new feature, there isn't much information about how to use them.  Part of this is because there is no stdlib module that exposes them to users (see PEP 734).  Regardless, it would be helpful to have a new Howto document that gives some instruction.

The page would include the following:

* how to create and use a subinterpreter from Python code (via my PEP 734 implementation on PyPI)
* how to communicate between interpreters
* a series of examples of how to use multiple interpreters for different concurrency/parallelism needs
* some minimal comparisons with multiprocessing, threads, and async

**Comment by benjamin-kirkbride** [comment]
> via my PEP 734 implementation on PyPI

Could you provide a link? Sounds interesting :)

**Comment by ericsnowcurrently** [comment]
FYI, I expect that I'll be moving that package to a different org and potentially renaming it (to "interpreters").

The @python/steering-council asked that I put up a PyPI package to get feedback before PEP 734 may be accepted.  However, we still haven't settled what approach to take on PyPI.  The most likely solution is a new PyPI org for semi-official packages (or perhaps just for packages that are under consideration for stdlib inclusion).  I would like to resolve that before landing this new Howto page.

**Comment by hugovk** [comment]
By the way, we requested the ["python" and "cpython" orgs in December](https://discuss.python.org/t/request-python-organisation-on-pypi/26545/9), but there's currently a big backlog in dealing with org requests. The good news is the PSF has just hired a [PyPI Support Specialist](https://pyfound.blogspot.com/2024/07/announcing-our-new-pypi-support.html) to work on things like this.

**Comment by ericsnowcurrently** [comment]
I'll probably table this in favor of gh-123152.
