### ISSUE TITLE
if you unpack a single element tuple containing a string, it thinks you have len(str) elements

### ISSUE THREAD

**Issue by cblackbu** [python/cpython#121828]
# Bug report

### Bug description:

**Code:**
```python
def greet_full(f, n):
    print(f'Hello {f} {n}')

def greet_first(f):
    print(f'Hello {f}')


lst_test_a = ['Jane', 'Doe']

tpl_test_a = ('John', 'Doe')

lst_test_b = ['Jane']

tpl_test_b = ('John')


greet_full(*lst_test_a)
greet_full(*tpl_test_a)

greet_first(*lst_test_b)
greet_first(*tpl_test_b)
```

**Result:**
First three calls to greet_*() work fine:
Hello Jane Doe
Hello John Doe
Hello Jane

However, the last call where it's unpacking tpl_test_b returns the following error message:
Exception has occurred: TypeError
greet_first() takes 1 positional argument but 4 were given
  File "C:\whatever\unpack.py", line 21, in <module>
    greet_first(*tpl_test_b)
TypeError: greet_first() takes 1 positional argument but 4 were given

**Expected:**
A single element tuple should be unpacked correctly and my code should be able to output "Hello John".  

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
`tpl_test_b = ('John')` does not create a single tuple, it creates a string. To make a tuple, write `('John',)`.

The comma makes the tuple, not the parentheses.

**Comment by cblackbu** [comment]
Hi Jelle,  I appreciate your insight into how it's currently broken.  This is still a bug, it just isn't related to unpacking.  Clearly, under this scenario Python's interpreter fails to recognize a tuple as a tuple.

**Comment by ned-deily** [comment]
This is not a bug and the reason why is expressly documented in the [Python Language Reference](https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy):

`A tuple of one item (a ‘singleton’) can be formed by affixing a comma to an expression (an expression by itself does not create a tuple, since parentheses must be usable for grouping of expressions).`
