### ISSUE TITLE
cmath.acosh(complex('±0+nanj')) should return complex('nan±pi/2j') (imaginary part sign is unspecified)

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#121889]
# Bug report

### Bug description:

As per C11 [DR#471](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm#dr_471) (adjusted resolution accepted for C17).  See glibc patch: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=5244527da1bfa751492e146d3e6ae128c59bfcc4

Currently, imaginary part is nan.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-121892

**Comment by mdickinson** [comment]
Fixed in #121892. As commented on the PR, I don't think this should be backported.
