### ISSUE TITLE
translates to "problem related to raising to a power

### ISSUE THREAD

**Issue by ioannism77** [python/cpython#121930]
# Bug report

### Bug description:

```python
# The problem when five is used in this arithmetic expression-equation.

>>>(1/5)**2
0.04000000000000001
>>>1/5**2
0.04
>>>(1/5)**2==1/5**2 
False
```

  The equation should be true and the first solution 0.04, such as the second one. This problem occurs only with five. I tried the same method with other numbers, like nine, eight, seven, six, four, three, two one and the outcome is true every time. This means that there is a inaccuracy only when five is used in this arithmetic expression-equation. 

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by nineteendo** [comment]
Could you please format your code correctly?

```python
>>> (1/5)**2
0.04000000000000001
>>> 1/5**2
0.04
>>> (1/5)**2==1/5**2
False
```

**Comment by zware** [comment]
Welcome to floating-point arithmetic :)

The results you're seeing are confusing until you understand what's going on, but correct.  Please see https://docs.python.org/3/tutorial/floatingpoint.html or https://0.30000000000000004.com/ for more information.

**Comment by nineteendo** [comment]
Maybe it's worth noting that `1/5**2` means

- `1 / (5 ** 2) == 1 / 25 == 0.04` and not
- `(1 / 5) ** 2 == 0.2 ** 2 == 0.04000000000000001`
