### ISSUE TITLE
`test_pyrepl` is taking 1 hour on refleaks buildbots

### ISSUE THREAD

**Issue by colesbury** [python/cpython#121988]
Looks like it started with ac07451116d52dd6a5545d27b6a2e3737ed27cf0 (cc @AlexWaygood).

https://buildbot.python.org/#/builders/259/builds/1189
https://buildbot.python.org/#/builders/1226/builds/2261

The last time this occurred (https://github.com/python/cpython/issues/121605) was because:
1) The refleaks buildbots run with a really long value for `SHORT_TIMEOUT`
2) `run_repl` was hanging until the timeout expired

### Linked PRs
* gh-121990
* gh-122064

**Comment by colesbury** [comment]
Oh, probably the same thing with `exit` vs `exit()`

https://github.com/python/cpython/blob/7dd52b63cef3ff60868dea510ef7a9adcc6611cc/Lib/test/test_pyrepl/test_pyrepl.py#L967

**Comment by nineteendo** [comment]
Is this fully fixed?
