### ISSUE TITLE
Read error on txt file

### ISSUE THREAD

**Issue by oklekamp** [python/cpython#121937]
# Bug report

### Bug description:

Reading a simple txt file, the program (dub1.py) gives read errors. Even when i delete the two records and run the program again, it gives the same result. Error on record 1315 and 19211. Even the total number of records read is incorrect.

a program written in rexx reads all records without a problem and shows the correct number of records in the file (ffotos.txt)

```python
# Add a code block here, if required
```
# dub1.py
# dubbel fotos uit f:
fin='d:\\ffotos.txt'
f=open(fin,encoding='UTF-8')
all=[]
t=0
a=0
sw=0
while a==0:
    t+=1
    try:
        line=f.readline()
        if line=='': break
        line=line[:-1]
        all.append(line)
    except:
        print(t,'read error')
       
print (t)    
[ffotos.txt](https://github.com/user-attachments/files/16274046/ffotos.txt)
![pythonerror](https://github.com/user-attachments/assets/f13600c4-687e-49e0-a931-54345def1cb4)

### CPython versions tested on:

3.12

**Comment by Eclips4** [comment]
Hello!
This repository is intended as a CPython bug tracker.
Please, ask Python-related questions there: https://discuss.python.org/c/users/
