### ISSUE TITLE
LoongArch to Tier 3

### ISSUE THREAD

**Issue by zangruochen** [python/cpython#121944]
Currently, go, gcc, kernel, llvm, and other upstream systems already support the loongarch architecture, and alpine and debian systems are integrating patches for the loongarch architecture.
I hope that python can alse support the loongarch architecture.
I've noticed that there are some conditions that need to be met for Tier 3 platform support, and I'd like to get guidance from the council.
I want to know what I should do as a first step?

**Comment by gaogaotiantian** [comment]
According to [PEP 11](https://peps.python.org/pep-0011/), you need at least two conditions:
1. A reliable buildbot. As github do not have loongarch hardware, that usually means you need to find some hardware dedicated to CPython build and hook it up.
2. A core dev signing up as a maintainer. You need to find at least one current core developer who's willing to support the platform and be the person of contact if anything goes wrong on the platform.
