### ISSUE TITLE
itertools.permutations not allowing to be called within two for loops

### ISSUE THREAD

**Issue by caballerofelipe** [python/cpython#122049]
# Bug report

### Bug description:

When storing a `itertools.permutations` to a variable and then running a `for p in permutations_var` two times in a row, the second time the loop doesn't work. I haven't seen the code or anything but it feels like the iterator implementation might have a problem.

This code stops after `print('hello')`:
```python
from itertools import permutations
perms = permutations([1,2,3])
for p in perms:
    print(p)
print('hello')
for p in perms:
    print(p)

## Returns:
# (1, 2, 3)
# (1, 3, 2)
# (2, 1, 3)
# (2, 3, 1)
# (3, 1, 2)
# (3, 2, 1)
# hello
```
This code runs as expected, `permutations` is casted to `list`.
```python
from itertools import permutations
perms = list(permutations([1,2,3]))
for p in perms:
    print(p)
print('hello')
for p in perms:
    print(p)

## Returns:
# (1, 2, 3)
# (1, 3, 2)
# (2, 1, 3)
# (2, 3, 1)
# (3, 1, 2)
# (3, 2, 1)
# hello
# (1, 2, 3)
# (1, 3, 2)
# (2, 1, 3)
# (2, 3, 1)
# (3, 1, 2)
# (3, 2, 1)
```

This code enters the second for-loop but starting where the previous for-loop stopped:
```python
from itertools import permutations
perms = permutations([1,2,3])
for p in perms:
    print(p)
    break
print('hello')
for p in perms:
    print(p)

## Returns:
# (1, 2, 3)
# hello
# (1, 3, 2)
# (2, 1, 3)
# (2, 3, 1)
# (3, 1, 2)
# (3, 2, 1)
```

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

**Comment by terryjreedy** [comment]
In general, iterators cannot be rerun.  This is discussed many places, such as the docs (FAQs, Reference) and likely on answer forums such as https://discuss.python.org/c/users/7 and stackoverflow.com.

**Comment by caballerofelipe** [comment]
Ohh I hadn't heard about that. I looked for something with `itertools.permutations` and didn't find what I was looking for, that's why I posted the bug.

Do you have a specific link with one of the discussions you mention? To read more about the subject...

Thanks BTW

**Comment by tim-one** [comment]
In general, iterating over "a sequence" can be done as many times as you like. These are generally objects supporting explicit indexing (str, list, tuple.  dict, bytes. array.array, ...). However, for any other kind of iterable object, you generally get a "one and done" stream of objects from iteration. This includes the results of nearly all `itertools` functions (possibly all of them, period - don't want to spend time checking),; some builtin functions like `map()`, `filter()`, and `zip()`; and all generator functions users may write.

Indeed, it's the purpose of `itertools.tee()` to "fork" a non-restartable iterator into multiple iterators that can revisit earlier results from the base iterator.
