### ISSUE TITLE
Outdated docstrings in `Lib/inspect.py`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#122058]
`inspect.isfunction` docstring is missing a:
- `__dict__`
- `__closure__`
- `__qualname__`
- `__module__`
- `__type_params__`

`inspect.isgenerator`:
- `gi_yieldfrom`
- `gi_suspended`(?) an undocumented attribute, I guess we should not expose it there
- `next` - an old attribute which has been removed, so should be removed from there as well

`inspect.isframe`:
- `clear`
- `f_trace_lines`
- `f_trace_opcodes`

`inspect.iscode`:
- `co_positions`
- `co_lines`
- `co_qualname`
- `replace`

I have a PR ready.

### Linked PRs
* gh-122059

**Comment by vstinner** [comment]
Fixed by commit https://github.com/python/cpython/commit/8ce70d6c697c8179e007169ba2ec5d3a0dc77362.
