### ISSUE TITLE
Error in Spanish translation

### ISSUE THREAD

**Issue by melchdev** [python/cpython#122036]
# Documentation

In the Spanish versión of _Tipos secuencia — list, tuple, range](https://docs.python.org/es/3/library/stdtypes.html#sequence-types-list-tuple-range)_  The first Table has an error:

<img width="602" alt="image" src="https://github.com/user-attachments/assets/fd411a82-b623-4eba-bfa3-0fb6aae2e78f">

It will be "el segmento de s desde i hasta j, con paso **k"**

**Comment by hugovk** [comment]
Please report to https://github.com/python/python-docs-es/issues/new
