### ISSUE TITLE
SBOM generation tool fails during gitignore filtering for libraries with no files

### ISSUE THREAD

**Issue by sethmlarson** [python/cpython#122044]
Within https://github.com/python/cpython/pull/119316 the libb2 library was removed. When running the SBOM generation tool a confusing error is raised during gitignore filtering instead of triggering the helpful error for the "no files for package" condition. This can be avoided by short-circuiting gitignore filtering when no files are present.

### Linked PRs
* gh-122045
* gh-122354
* gh-122355

**Comment by ZeroIntensity** [comment]
Looks like this is not a security issue, just a bug.

**Comment by Eclips4** [comment]
> Looks like this is not a security issue, just a bug.

I guess that all of the SBOM-related issues are actually related to type-security label.

**Comment by sethmlarson** [comment]
We can change the labeling scheme if it makes it less confusing! :)

**Comment by ZeroIntensity** [comment]
I was under the impression that `type-security` was reserved for things that actually posed a security thread, not things related to packages for cryptography and whatnot.

**Comment by hugovk** [comment]
Merged and backported, thanks!
