### ISSUE TITLE
AttributeError: 'os.stat_result' object has no attribute 'st_birthtime' on linux

### ISSUE THREAD

**Issue by Iftakharpy** [python/cpython#122035]
# Bug report

### Bug description:

On windows I can do `import os; next(os.scandir(".")).stat().st_birthtime` which gives me the file creation timestamp. <br>
When I tried to do the same on Linux I get the following error:
```ipython
In [17]: next(os.scandir(".")).stat().st_birthtime
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[17], line 1
----> 1 next(os.scandir(".")).stat().st_birthtime

AttributeError: 'os.stat_result' object has no attribute 'st_birthtime'
```

Python version 3.12

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

**Comment by devdanzin** [comment]
This might be expected behavior. [The docs](https://docs.python.org/3/library/os.html#os.stat_result.st_birthtime) say:
> This attribute is not always available, and may raise [AttributeError](https://docs.python.org/3/library/exceptions.html#AttributeError).

**Comment by ronaldoussoren** [comment]
``st_birthtime`` is only available on platforms where the platform C API has st_birthtime available, as well as on Windows where the information is available under a different name in the platform API.

Linux is not one of the platforms that has ``st_birthtime`` in its platform API, hence the ``AttributeError``.

**Comment by ZED149** [comment]
can someone explain how to get around this error?

**Comment by Iftakharpy** [comment]
I am assuming you are using Linux, in that case I would suggest using st_atime, st_ctime, st_mtime or the other attributes with _ns suffix. You [check out the docs](https://docs.python.org/3/library/os.html#os.stat_result.st_atime) for more.

**Comment by nakedboov** [comment]
It depends on used Linux kernel version. Since 4.11 st_birthtime is available. It may be retrieved via syscall statx (but not regular stat) or related api provided by libc.
