### ISSUE TITLE
All python build from source fail with error on my Mac

### ISSUE THREAD

**Issue by matthewyang204** [python/cpython#122050]
# Bug report

### Bug description:

```
Undefined symbols for architecture arm64:
  "_libintl_bindtextdomain", referenced from:
      __locale_bindtextdomain in _localemodule.o
      __locale_bindtextdomain in _localemodule.o
  "_libintl_dcgettext", referenced from:
      __locale_dcgettext in _localemodule.o
  "_libintl_dgettext", referenced from:
      __locale_dgettext in _localemodule.o
  "_libintl_gettext", referenced from:
      __locale_gettext in _localemodule.o
  "_libintl_setlocale", referenced from:
      __locale_setlocale in _localemodule.o
      __locale_setlocale in _localemodule.o
      __locale_localeconv in _localemodule.o
      __locale_localeconv in _localemodule.o
      __locale_localeconv in _localemodule.o
      __locale_localeconv in _localemodule.o
  "_libintl_textdomain", referenced from:
      __locale_textdomain in _localemodule.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Programs/_freeze_module] Error 1
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by ZeroIntensity** [comment]
I'm not sure this is a CPython issue. Based on [this issue](https://github.com/pyenv/pyenv/issues/1768), [this issue](https://github.com/pyenv/pyenv/issues/1877), and [this issue](https://github.com/pyenv/pyenv/issues/2441) from Pyenv, it looks like you're attempt to build CPython for ARM64 from an x86 Homebrew installation.

**Comment by ronaldoussoren** [comment]
As @ZeroIntensity writes this is due to having some libraries on the system that don't support the arm64 architecture, with as the most likely explanation that you have a homebrew installation for x86_64.

One way to verify: configure python with ``configure --enable-universalsdk --with-universal-archs=intel-64``.

**Comment by matthewyang204** [comment]
Okay, so it seems to have worked correctly this time until the very end, during `sudo make install`:
```
ginstall: cannot stat 'Modules/_blake2.cpython-313-darwin.so': No such file or directory
```

**Comment by 1oh1** [comment]
What worked for me (trying to build arm64 version of Python using pyenv) was to [install `gettext`](https://stackoverflow.com/questions/70152525/cannot-install-python-3-10-0-on-m1-apple-silicon-ld-symbols-not-found-for-a) with `brew install gettext`

Also, if you have multiple Homebrew versions installed, you may want to use something like this in your shell profile:
```
if [[ $(arch) != arm64* ]]
then
    # x86_64 Homebrew
    eval "$(/usr/local/bin/brew shellenv)"
    export PYENV_ROOT="$HOME/.pyenv-x86"
else
    # arm64 Homebrew
    eval "$(/opt/homebrew/bin/brew shellenv)"
    export PYENV_ROOT="$HOME/.pyenv"
    export LDFLAGS="-L/opt/homebrew/lib"
    export CPPFLAGS="-I/opt/homebrew/include"
fi

# PyENV config
[[ -d $PYENV_ROOT/bin ]] && export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init - zsh)"
```

**Comment by ned-deily** [comment]
For the record, having GNU `gettext`, which is GPLv3-licensed, is not required to build and run Python other than for some specific uses like for the `gettext` internationalization module. The build system looks for a `libintl.h` to determine whether to attempt to build with `gettext`. Apple does not supply `gettext` with macOS.
