### ISSUE TITLE
Add tests for the "roughly equivalent" implementations in itertools.rst

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#122066]
I am going to add a test case which does the following:

- Use a regex to search in `itertools.rst` for every code block after "roughly equivalent to".
- Extract the test cases from the code blocks (e.g. `# accumulate([1,2,3,4,5]) → 1 3 6 10 15`).
- Run the test cases with the `itertools` module.
- Run the test cases with the pure Python implementation.

### Linked PRs
* gh-122067

**Comment by rhettinger** [comment]
> Use a regex to search in itertools.rst for every code block after "roughly equivalent to".I

IMO all of this is a mostly pointless and painful exercise that will just create maintenance problems in perpetuity.  We *really* don't want to be running fragile bespoke regexes on the docs.

Please stick with the current approach.  For any of the interesting recipes, we have a regular unittest on a copy of the recipe.

> Extract the test cases from the code blocks (e.g. # accumulate([1,2,3,4,5]) → 1 3 6 10 15).

This is not a good idea.  The comments are in free format designed to communicate to well to humans but is not intended to be a parsable mini-dsl.

> Run the test cases with the pure Python implementation.

The "rough equivalents" will only pass a part of the corresponding test suite.  The generators used in the documentation differ from the C implementations that perform more error checking upon instantiation.

If you want to add a few more tests to unittest module for the equivalents, I would support the effort.  But really don't need or want a heroic and complicated effort to test these is a tightly coupled manner. It isn't work the effort, the disruption, or the harm to future maintenance.

**Comment by skirpichev** [comment]
> We really don't want to be running fragile bespoke regexes on the docs.

That seems to be an "implementation detail" of this proposal.  In the pr thread it was shown that it's possible to factor out such code snippets to a single module and include them using ``literalinclude`` sphinx directive.

> For any of the interesting recipes, we have a regular unittest on a copy of the recipe.

The drawback of such approach vs above one - copy should be kept in sync, that puts additional maintenance burden.

**Comment by rhettinger** [comment]
> it's possible to factor out such code snippets to a single module and include them using literalinclude sphinx directive.

I had thought of that but it will make maintaining the main doc file harder because the code won't be visible alongside the surrounding text.

> The drawback of such approach vs above one - copy should be kept in sync, that puts additional maintenance burden.

Yes.  But it is least problematic way. I've been maintaining the for 20 years.  It rarely changes and syncing hasn't been an issue.

I'm going to mark this as closed.  AFAICT there isn't a real problem to be solved here.  If the OP wants to extend the current approach and add a few more tests, he is welcome to do so.  But we don't have an actual problem to be solved here (or in the other code equivalents sprinkled through the docs).

Thanks for the suggestion, but any work here will likely cause more pain than it solves.

**Comment by rhettinger** [comment]
> copy should be kept in sync, that puts additional maintenance burden.

It is an infrequent and trivial burden.  IMO it is less of burden than the alternatives.
