### ISSUE TITLE
tarfile - Changelog versions change based on which doc version you are viewing

### ISSUE THREAD

**Issue by helloSeen** [python/cpython#122135]
# Documentation

I am trying to determine when the _filter_ parameter was added to the [TarFile.extractall() method](https://docs.python.org/3.12/library/tarfile.html#tarfile.TarFile.extractall). When viewing the 3.12 documentation it says the parameter was added in 3.12, however switching to 3.8 documentation it says the parameter was added in 3.8.17. It seems as though the documentation is set to say the parameter was added in the latest possible version.

This is, of course, not very helpful in determining when the change was actually implemented.

**Proposed changes:**
Review and update the change log comments in **tarfile** to accurately reflect when changes were added to Python.

**Comment by JelleZijlstra** [comment]
The changelogs are correct; it was added in all the bugfix versions of 3.8 through 3.11, as well as in 3.12. See PEP-706.

**Comment by hugovk** [comment]
And https://github.com/python/cpython/issues/102950 is the relevant issue with links to the 3.12 PR and each backport PR.
