### ISSUE TITLE
Move opcode magic number out of `Lib/importlib/_bootstrap_external.py`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#122188]
# Feature or enhancement

### Proposal:

The number changes way more frequently than it used to, and currently triggers a review request for CODEOWNERS on `Lib/importlib`. Maybe it's time to put it in its own file somewhere else?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122243
* gh-122503

**Comment by serhiy-storchaka** [comment]
I suggest also to move the history list of magic numbers to some other text file. Currently, adding a line changes line numbers and affects a lot of generated C lines in the frozen `_bootstrap_external` bytecode. This file can also be parsed to generate the versions table for the `py` launcher.
