### ISSUE TITLE
AttributeError on interpreter exit on Windows 3.13.0b4

### ISSUE THREAD

**Issue by astrelsky** [python/cpython#122185]
Apologies for not using one of the templates. I'm using the android app to report this and it insisted on opening a web browser to use the template. GitHub decided not to apply the selected labels too.

On windows, using ctrl+z to exit the interpreter results in the following

`AttributeError: module 'signal' has no attribute 'SIGSTOP'` `_pyrepl/commands.py:237`

**Comment by picnixz** [comment]
I think it's a duplicate of #119896

**Comment by astrelsky** [comment]
> Closing as a duplicate of #119896

Oh, sorry I missed it.

**Comment by picnixz** [comment]
No worries!
