### ISSUE TITLE
feat: __generic_str_support__

### ISSUE THREAD

**Issue by dan1hc** [python/cpython#122169]
# Feature or enhancement

### Proposal:

Could `str` methods take a `TypeVar('string', bound=str)` rather than `str` itself every time? (i.e. eliminate the need for a `# type: ignore[misc]` below).

Also, I think it might be cool to have generic `str[t.Any]`, such that the param could be used to indicate string casing.

```python
import typing as t

from . import typ


class DictLike:

    ___dataclass_fields__: dict[str[typ.snake_case], typ.AnyField[t.Any]]

    @classmethod
    def keys(cls) -> t.KeysView[str[typ.snake_case]]:
        """
        Return an iterator of keys like a `dict`.

        ---

        Removes any suffixed underscores from field names (`_`).

        """

        return t.KeysView(
            {
                k.rstrip('_'): v  # type: ignore[misc]
                for k, v
                in cls.__dataclass_fields__.items()
                }
            )

```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
`str[typ.snake_case]` is not currently valid in the type system or at runtime, as `str` is not a generic type. I can guess what you want it to mean but this idea doesn't seem to be at a stage where it can be added to CPython. 

You'll need to https://discuss.python.org/c/typing/32, explaining in detail what you want to change to the static type system, then probably write a PEP first.

**Comment by AlexWaygood** [comment]
> `str[typ.snake_case]` is not currently valid in the type system or at runtime, as `str` is not a generic type. I can guess what you want it to mean but this idea doesn't seem to be at a stage where it can be added to CPython.

It sounds like OP is proposing something similar to https://github.com/python/typing/issues/1202. Agree that discussion should either take place on that issue or in a new discuss.python.org thread; CPython is the wrong place.
