### ISSUE TITLE
Optional `raise` argument to os.getenv

### ISSUE THREAD

**Issue by jltf** [python/cpython#122162]
# Feature or enhancement

### Proposal:

It would be nice to make getenv function from os module to raise an exception when it is not found. It will tell clearly that variable is not set without defaulting it to None.

```python
from os import getenv

getenv("SOME_ENV_VARIABLE", raise=True) 
# should raise a ValueError exception instead of returning default value.
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by picnixz** [comment]
For the record, you cannot use `raise` as a keyword (but you can use `raises`). Alternatively, I suggest using sentinels instead:

```py
sentinel = object()
var = getenv("SOME_ENV_VARIABLE", sentinel) 
if var is sentinel:
	# do something
	...
```

I don't think we would introduce this kind of interface since it's `getenv` is essentially a wrapper around `dict.get` (which never raises).

**Comment by picnixz** [comment]
(Thanks Thomas, I forgot to close it...)
