### ISSUE TITLE
Python 3.12.4 does not include _sqlite3

### ISSUE THREAD

**Issue by satayyeb** [python/cpython#122166]
# Bug report

## Reproduce:
Try to import `sqlite3` in a python shell:
```python
  import sqlite3
```

It results in this error:
```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.12/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'
```

I solved the problem by installing python 3.12.3 instead of 3.12.4.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
How did you install 3.12.4? did you built it from scratch? or did you install it from your package manager? 

cc @erlend-aasland

**Comment by satayyeb** [comment]
> How did you install 3.12.4? did you built it from scratch? or did you install it from your package manager?
> 
> cc @erlend-aasland

I have built it from scratch using these commands:

```shell
wget https://www.python.org/ftp/python/3.12.4/Python-3.12.4.tgz
tar -xvf Python-3.12.3.tgz
cd Python-3.12.4/
./configure --enable-optimizations
sudo make install -j 20
```

**Comment by erlend-aasland** [comment]
You need to also install the sqlite3 dependencies before building. Please see the devguide:

- https://devguide.python.org/getting-started/setup-building/
