### ISSUE TITLE
NULL exception with an PyList_New created list which is **not** filled

### ISSUE THREAD

**Issue by aotto1968** [python/cpython#122148]
# Bug report

### Bug description:

I use the C api from python and due to a programming error a new list was created with 
```
PyObject* argsO = PyList_New(num+wrong_something);
``` 
which was explicitly partially *not* initialized. The funny thing about the error is that an output in python with 
```
print("callback2", vals, file=sys.stderr)
``` 
produced an output where the NOT initialized values ​​were marked with "\<NULL>":
```
callback2 ['0', 'main', '', <NULL>, <NULL>, <NULL>, <NULL>, <NULL>]
```
but the further processing in C with:
```
iterator = PyObject_GetIter(argsO);
while ((item = PyIter_Next(iterator))) { 
   LngErrorCheckN (strO = PyObject_Str(item)) 
   MkBufferListAppendSTR(args, PyUnicode_AsUTF8(strO));
   Py_CLEAR(strO);
   Py_CLEAR(item);
}
``` 
then ended up in a core dump of my extension: 
``` 
: BackTrace {
:   [ library              : filename                       : lineno ] function
:   [ -------              : --------                       : ------ ] --------
:   [ theLink              : c/sys_mq.c                     : 708    ] MqDisasterSignal
:   [ unknown              : unknown                        : 0      ] unknown
:   [ system               : ./Include/object.h             : 502    ] Py_INCREF
:   [ system               : Objects/listobject.c           : 3254   ] listiter_next
:   [ system               : Objects/abstract.c             : 2864   ] PyIter_Next
...
:   [ theKernel            : py/LibMkKernel_py.c            : 208    ] py_mkkernel_LngListToMkBufferListS
:   [ theKernel            : c/tmpl/mk_misc_check_lng.h     : 240    ] py_mkkernel_CheckBAC
:   [ theKernel            : py/MkBufferListC_py.c          : 195    ] py_mkkernel_MkBufferListC_AppendLA
```
where it is clearly visible that `PyIter_Next` *cannot* handle `NULL`.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
https://docs.python.org/3/c-api/list.html#c.PyList_New is explicit that you have to set all of the items in the list before using it.

If you use C, you are going to risk segfaults if you get something wrong.

**Comment by aotto1968** [comment]
I understand your point but it is real *clever* to set the new items to `NULL` (core dump) and not to `Py_None` ?

**Comment by aotto1968** [comment]
Another question: is it really guaranteed that a `NULL` never occurs?

I'm asking because `print(...)` seems to be able to handle `NULL` and I'm now wondering whether I need to expand my code so that it is `NULL` object safe.

**Comment by encukou** [comment]
`NULL` never occurs, unless it's documented (such as after `PyList_New`).
Some parts of Python doesn't crash on NULL -- usually older code from the time Python was being first put together (like `print`), and the parts used for debugging crashes. But most code will just crash. (If you're using the debug mode, it'll usually crash with an `assert`.)

**Comment by aotto1968** [comment]
thanks.
