### ISSUE TITLE
Accuracy issues of sum() specialization for floats/complexes

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#122234]
# Bug report

### Bug description:

Unfortunately, #121176 was merged with a bug:
https://github.com/python/cpython/blob/e9681211b9ad11d1c1f471c43bc57cac46814779/Python/bltinmodule.c#L2749-L2755
L2751 lacks cs_add().  Sorry for that.  Reproducer: ``sum([2j, 1., 10E100, 1., -10E100])`` (should be ``2+2j``).  I'll provide a patch.

But maybe cases for integer arguments also should use compensated summation?  E.g.:
https://github.com/python/cpython/blob/e9681211b9ad11d1c1f471c43bc57cac46814779/Python/bltinmodule.c#L2689-L2698
on L2694 (and use ``PyLong_AsDouble()``).  An example:
```pycon
>>> sum([1.0, 10E100, 1.0, -10E100])
2.0
>>> sum([1.0, 10**100, 1.0, -10**100])  # huh?
0.0
```
I would guess, that integer values in this case are treated as exact and they are allowed to smash floating-point result to garbage.  But...  This looks as a bug for me.  ``fsum()`` also chooses ``2.0``:
```pycon
>>> math.fsum([1.0, 10**100, 1.0, -10**100])
2.0
```

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-122236
* gh-122406

**Comment by skirpichev** [comment]
CC @rhettinger for the second part (integer values).  Is this an issue or a feature?

**Comment by skirpichev** [comment]
@picnixz, that's a feature.

Ok, it seems that in the second case PyLong_AsLongAndOverflow() just overflows and we fallback to the generic sum.  That's something copied from the specialization for integers and it wasn't changed in #100426.  Maybe it should?

**Comment by skirpichev** [comment]
Hmm, with PyLong_AsDouble() + compensated summation it's even faster!

```
./python -m timeit -r11 -s 'xs=[1.0, 10**100, 1.0, -10**100]' 'sum(xs)'
500000 loops, best of 11: 634 nsec per loop
```
while in the main:
```
$ ./python -m timeit -r11 -s 'xs=[1.0, 10**100, 1.0, -10**100]' 'sum(xs)'
500000 loops, best of 11: 801 nsec per loop
```

**Comment by skirpichev** [comment]
PR is ready for review: https://github.com/python/cpython/pull/122236

It combines fixes for floats and integers.  If second case requires more discussion or is "a feature", I can quickly revert that part.

**Comment by encukou** [comment]
The added error returns leak references. This was caught by the noGIL refleak buildbot (which runs more often than refleaks for regular-builds): https://buildbot.python.org/#/builders/1226/builds/2352/steps/6/logs/stdio

**Comment by Eclips4** [comment]
> The added error returns leak references. This was caught by the noGIL refleak buildbot (which runs more often than refleaks for regular-builds): https://buildbot.python.org/#/builders/1226/builds/2352/steps/6/logs/stdio

PR is ready: https://github.com/python/cpython/pull/122405

**Comment by encukou** [comment]
My PR #122406 looks exactly the same :)
IMO, it's better to associate the PR with this issue, so the fix-up PR is kept together with the original.

**Comment by picnixz** [comment]
Closing since the refleak is now fixed.
