### ISSUE TITLE
Improve error message for unbalanced unpacking

### ISSUE THREAD

**Issue by tusharsadhwani** [python/cpython#122239]
# Feature or enhancement

### Proposal:

This is great:

```pytb
>>> x, y, z = 1, 2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: not enough values to unpack (expected 3, got 2)
```

But here, it doesn't seem to tell how many values were found:

```pytb
>>> x, y, z = 1, 2, 3, 4
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: too many values to unpack (expected 3)
```

I was hoping to see `(expected 3, got 4)` here. The eval loop also seems to have access to an entire `PyList` object at this point, so getting its length for the error message should not cause any changes in behaviour.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122244

**Comment by HarryLHW** [comment]
What if the right hand side is an iterator, it will consume more elements of the iterator than before, e.g.

```
>>> a = iter(range(100))
>>> x, y, z = a
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    x, y, z = a
    ^^^^^^^
ValueError: too many values to unpack (expected 3)
>>> next(a). # instead of StopIteration
4 
>>> 
```

**Comment by tusharsadhwani** [comment]
I see! Would it be possible to only add the length for `Sequence` types?

**Comment by tusharsadhwani** [comment]
Also, isn't the current behaviour also slightly undesirable? the iterator had 4 values consumed from it, instead of 3. Is this behaviour to be depended upon? (These are genuine questions, this is my first time trying to reason about the interals of the eval loop.)

**Comment by tusharsadhwani** [comment]
OK thinking more about this, if it's an infinite iterator you definitely don't want to be stuck forever here.

**Comment by Eclips4** [comment]
> OK thinking more about this, if it's an infinite iterator you definitely don't want to be stuck forever here.

You're right - we need to know how many values are on the right side. But if we have infinity on the right, it will take forever. So, unfortunately, there's no way to do this, even though the idea is good. :( I think we should close this issue.
