### ISSUE TITLE
REPL auto-indentation is wrong with comments

### ISSUE THREAD

**Issue by HarryLHW** [python/cpython#122237]
# Bug report

### Bug description:

Currently, the REPL auto indentation is like this:
<img width="569" alt="image" src="https://github.com/user-attachments/assets/ee4fde4a-2bd7-4102-a67a-7b3c3753ad1b">

The correct one should be:
<img width="570" alt="image" src="https://github.com/user-attachments/assets/031e1218-08df-4d46-ba73-31c99da207cd">

I am working on a PR to fix this.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-122238
* gh-122383

**Comment by HarryLHW** [comment]
This is also incorrect when `"#"` happens to be the last non-whitespace character.
<img width="566" alt="image" src="https://github.com/user-attachments/assets/844cfc46-a41b-4941-94e2-bec5e441f82f">

**Comment by Wulian233** [comment]
Another https://github.com/python/cpython/issues/124096

<img width="716" alt="2024-09-15 192801" src="https://github.com/user-attachments/assets/c152bba1-408a-4e6d-9dd0-bf4a5162cffa">
