### ISSUE TITLE
Dictionary watchers deliver `added` event before it's guaranteed to be successful leading to possible incosistent state

### ISSUE THREAD

**Issue by DinoV** [python/cpython#122208]
# Bug report

### Bug description:

Currently dictionary watchers deliver the `PyDict_EVENT_ADDED` event before they have done everything that is necessary to ensure success. If the dictionary requires a resize for insertion to succeed (or a new keys object needs to be allocated from an empty dict) and that fails then the dictionary watcher will have inconsistent state to what's stored in the dictionary. Watchers should only receive the event when the dictionary implementation is guaranteed that it will succeed. 

The event can still be delivered before the insertion happens meaning there's no visible change in behavior except for the OOM case.

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-122207
* gh-122326
* gh-122327

**Comment by hugovk** [comment]
Triage: closing as the linked PRs are merged, please re-open if still needed.
