### ISSUE TITLE
`io.IOBase` docs often talk about byte offsets, but the same classes are used for string `io` types which use character offsets

### ISSUE THREAD

**Issue by andmis** [python/cpython#122299]
The `io.IOBase` docs often talk about byte offsets, but the same classes often act as base classes for the string `io` types, which use character offsets.

PR fixing one such issue: https://github.com/python/cpython/pull/121421/files

### Linked PRs
* gh-121421

**Comment by vadmium** [comment]
I wouldn’t call it a character offset; the number is not necessarily equal or even proportional to a number of characters. Consider multi-byte encodings, the newline encoder and decoder, and _pyio.StringIO with non-ASCII.

For character IO seeking, the offset is generally meant to be an opaque value returned by _tell_, or zero.

**Comment by picnixz** [comment]
Considering that multiple core devs expressed their reservation, I will close this one as `not planned`. If you want to discuss it more in details and/or may suggest a better wording that would be accurate as well, feel free to @ me.
