### ISSUE TITLE
`intern_static` is not thread-safe with multiple interpreters

### ISSUE THREAD

**Issue by colesbury** [python/cpython#122291]
# Bug report

Most static strings are interned during Python initialization in [`_PyUnicode_InitStaticStrings`](https://github.com/python/cpython/blob/5f6001130f8ada871193377954cfcfee01ef93b6/Include/internal/pycore_unicodeobject_generated.h). However, the `_Py_LATIN1_CHR` characters (code points 0-255) are static, but not interned. They may be interned later while the Python is running. This can happen for various reasons, including calls to `sys.intern`.

This isn't thread-safe: it modifies the hashtable `_PyRuntime.cached_objects.interned_strings`, which is shared across threads and interpreters, without any synchronization.

It also can break the interning identity invariant. You can have a non-static, interned 1-characters string later shadowed by the global interning of the static 1-character string.

**Suggestions**

* The `_PyRuntime.cached_objects.interned_strings` should be immutable. We should not modify it after `Py_Initialize()` until shutdown (i.e., `_PyUnicode_ClearInterned` called from `finalize_interp_types()`)
* The 1-character latin1 strings should be interned. This can either be by explicitly interning them during startup, or by handling 1-character strings  specially in `intern_common`.

cc @encukou @ericsnowcurrently 

### Linked PRs
* gh-122303
* gh-122347

**Comment by encukou** [comment]
Interning them makes sense. I'll send a PR.

**Comment by encukou** [comment]
FWIW:
> This isn't thread-safe: it modifies the hashtable _PyRuntime.cached_objects.interned_strings, which is shared across threads and interpreters, without any synchronization.

Yup, that's a bug, so the fix should be backported.

> It also can break the interning identity invariant. You can have a non-static, interned 1-characters string later shadowed by the global interning of the static 1-character string.

Hmm, interning a short string should give you the static singleton.
But the fix will definitely make this easier to follow, and harder to hide any bugs.

**Comment by encukou** [comment]
> interning a short string should give you the static singleton.

Before the PR for this issue we had:
https://github.com/python/cpython/blob/c08696286f52d286674f264eecf7b33a335a890b/Objects/unicodeobject.c#L15480-L15493

**Comment by colesbury** [comment]
Looks like this has been fixed for a while.
