### ISSUE TITLE
Support for @auto decorator.

### ISSUE THREAD

**Issue by zerserob** [python/cpython#122221]
# Feature or enhancement

### Proposal:

When creating an enum using `class` syntax, it would save much time to add `auto()` as the value for all members using the `@auto` class decorator.

Example:

```
@auto
class Example(Enum):
    FIRST
    SECOND
    THRD
```
is the same as:

```
class Example(Enum):
    FIRST = auto()
    SECOND = auto()
    THRD = auto()
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by picnixz** [comment]
This is not a valid syntax for now (you will have NameError exceptions being raised). For such feature, you should open a discourse topic: https://discuss.python.org/c/ideas/6.

Many issues exist such as how to deal if the named constant already exist in the outer scope, how to detect at compile time whether this is a legitimate NameError or not, etc, so I don't think it will get support.

Closing for now.
