### ISSUE TITLE
sklearn metrics module - mean squared value

### ISSUE THREAD

**Issue by sankalpjagdale** [python/cpython#122261]
# Bug report

### Bug description:

```python
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

axis_X = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9], [10]]).reshape(-1, 1)
axis_X_train = axis_X
axis_X_test = axis_X

axis_y_train = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
axis_y_test = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

model = linear_model.LinearRegression()
model.fit(axis_X_train, axis_y_train)
axis_y_predicted = model.predict(axis_X_test)

print("Results")
print("Mean squared error is:", mean_squared_error(axis_y_test, axis_y_predicted))
print("Weights:", model.coef_)
print("Intercept:", model.intercept_)
print("axis_y_test", axis_y_test)
print("axis_y_predicted", axis_y_predicted)

plt.scatter(axis_X_test, axis_y_test)
plt.plot(axis_X_test, axis_y_predicted)
plt.show()

```
Above code is about the perfect Linear regression .Here , the Means squared value should be equal to 0 but on running the code the value is not equal to 0 . the output MSE is -8.8814...... . Hence ,the module
[1.pdf](https://github.com/user-attachments/files/16371967/1.pdf)
 - sklearn.metrics import mean_squared_error  has a bug. kindly check the bug and resolve it asap.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
This is the issue tracker for Python itself, please report it to the sklearn tracker. Or you can try the help category of the discussion forum: https://discuss.python.org/c/help/7
