### ISSUE TITLE
Support command history in PyREPL on Windows

### ISSUE THREAD

**Issue by devdanzin** [python/cpython#122273]
# Feature or enhancement

### Proposal:

The new PyREPL doesn't currently support recording command history in Windows. Using the `_pyrepl.readline` module, it should be possible to save and load history files on that platform.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122274
* gh-127141
* gh-127289

**Comment by vstinner** [comment]
Thanks @devdanzin for your bug report and your fix!

**Comment by vstinner** [comment]
I closed https://github.com/python/cpython/issues/125154 as a duplicate of this issue.
