### ISSUE TITLE
Split up ``Lib/test/test_ast.py``

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#122292]
# Feature or enhancement

### Proposal:

``Lib/test/test_ast.py`` currently contains a ``ast`` test cases, and code-generated data such as ``exec_results``, ``eval_results`` and ``single_results``.

I propose to move the snippets which are used to generate these variables and the code which is generated into a separate file.

The ``test_ast`` directory would look like this:
* test_ast/test_ast.py - the previous version of test_ast.py but without the snippets and code-generation
* test_ast/test_cases.py - contains the snippets and code-generation

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122293
* gh-122393
* gh-122395

**Comment by vstinner** [comment]
The issue is now implemented. Thanks @Eclips4.
