### ISSUE TITLE
Make Download page translatable

### ISSUE THREAD

**Issue by rffontenelle** [python/cpython#122384]
# Documentation

The Python docs' Download page (https://docs.python.org/3/download.html) is not currently available for translation, hence differentiating from other pages that received the translations effort of the language teams.

Strings should be marked for translation, so the file's strings are properly extracted into translation files.

To reproduce:
1. `make -C Doc venv gettext`   # from local CPython checkout
2. search (unsuccessfully) strings in the .pot files generate in 'Doc/build/gettext/' directory for the translation strings that should be extracted from 'Doc/tools/templates/download.html' file (e.g. `grep -R 'These archives contain all the content in the documentation.' Doc/build/gettext`)

### Linked PRs
* gh-122385
* gh-122553
* gh-122554

**Comment by Wulian233** [comment]
A similar problem appears in the footer of every page. I tried to search for keywords, but couldn't find anything relevant.

![IMG_20240729_141406.jpg](https://github.com/user-attachments/assets/600ffb86-901a-4f2a-8d70-e4c4185feb67)

**Comment by hugovk** [comment]
Some of that comes from the theme, for example: https://github.com/python/python-docs-theme/blob/f1ba0f8c86f859be2a800fae8af00ec4a7e48039/python_docs_theme/layout.html#L147

**Comment by Wulian233** [comment]
looks there has `{% trans %}{% endtrans %}`, and I've switched a lot of different languages, but there's no actual translation 🤔🤔❓

**Comment by rffontenelle** [comment]
python-doc-theme is not being translated. It is a separate repository, and translators only translate the documentation for cpython repository. This should probably change.

**Comment by hugovk** [comment]
See https://github.com/python/python-docs-theme/issues/194 for localising the theme.

**Comment by Wulian233** [comment]
Good
