### ISSUE TITLE
Proposal: Add capability to compile Python code with dependencies into a standalone binary executable without bundling the interpreter

### ISSUE THREAD

**Issue by TimLai666** [python/cpython#122310]
# Feature or enhancement

### Proposal:

**Feature Request**

### Background
Currently, tools like PyInstaller are used to package Python applications into standalone executables. However, these tools bundle the Python interpreter along with the application code, which results in larger file sizes and some inefficiencies. Additionally, existing methods often encounter unexpected errors or issues, especially when executed in different environments (e.g., various operating systems).

### Proposal
Add a feature to CPython that allows direct compilation of Python code, along with its dependencies, into a standalone binary executable. This would eliminate the need to bundle the interpreter separately.

### Implementation Suggestion
Consider using Rust for implementation due to its performance and safety advantages. Rust's robust tooling and community support can aid in the development process.

### Benefits
- Reduced file sizes for compiled Python applications.
- Improved execution performance.
- Enhanced security and efficiency.
- Simplified deployment of Python applications.
- Reduced likelihood of encountering unexpected errors or issues across different environments.
- Easier for users without a background in Python or programming to run Python programs.
- Improved performance of the compiled executables.
- Integrated IDE support for quick packaging and deployment of Python applications.

### Example Use Cases
- Distributing Python applications to environments where Python is not pre-installed.
- Creating lightweight, efficient executables for Python scripts.
- Making Python programs more accessible to non-technical users.
- Enhancing the overall performance and efficiency of Python applications.
- Enabling IDEs to offer streamlined packaging and deployment features for Python applications.

### Promotion of Python
This feature would aid in the promotion of Python by making it easier for a wider range of users to run Python applications without needing to install a Python interpreter. Additionally, the improved performance and reliability of compiled executables would enhance Python's appeal for developing and distributing software.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://discuss.python.org/t/capability-to-compile-python-code-with-dependencies-into-a-standalone-binary-executable-without-bundling-the-interpreter/59241

**Comment by zware** [comment]
While this sounds like a nice feature, it's also a rather **enormous** ask.  It's definitely a [PEP](https://peps.python.org/pep-0001/)-worthy change, meaning that if you want to see this happen you'll need to find a core team member willing to sponsor the PEP, write the PEP, address objections/issues raised in discussion, figure out how an implementation would work, possibly write that implementation, and all of that before the PEP can be either accepted or rejected.  It's also not a new idea; you'll need to do a lot of research to find older discussions and address points brought up in those discussions.

The linked discussion is also only 2 hours old as of right now; there hasn't been nearly enough actual discussion there to warrant an open issue here.
