### ISSUE TITLE
Text Indices

### ISSUE THREAD

**Issue by kroshni** [python/cpython#122302]
![Screenshot 2024-07-26 135158](https://github.com/user-attachments/assets/95cb3b6d-8819-4764-bcc7-06b23061a86a)

The negative indices should be start from "n" of "Python"

**Comment by Wulian233** [comment]
GPT can explain your question

### Index Example

Consider the string "Python" with a length of 6. The indexing is as follows:

- Positive index: `P` `y` `t` `h` `o` `n`
  - 0   1   2   3   4   5   6
- Negative index: `P` `y` `t` `h` `o` `n`
  - -6 -5 -4 -3 -2 -1

### Slice Explanation

- Positive indices range from `0` to `6`, indicating positions between characters.
- Negative indices range from `-6` to `-1`, also indicating positions between characters.

In the image, `-1` represents the position to the right of the last character `n`, not the character itself. This indexing method ensures consistency in slicing operations:

- `word[0:6]` means from the first character 'P' to the last character 'n' (excluding the right endpoint 6).
- `word[-6:-1]` means from the first character 'P' to the position before the last character 'n' (excluding the right endpoint -1).

### Summary

- Both positive and negative indices indicate positions between characters.
- The slice `word[i:j]` means from index `i` to `j` (excluding `j`).
- Negative indices count from right to left, ensuring flexibility and consistency in slicing.

Therefore, `-1` in the image is correct as it represents the position to the right of the last character, not the character itself.

**Comment by kroshni** [comment]
> Not a bug.
> 
> There is no problem with the index -1 you said, but the document refers to slices, which is confused
> 
> GPT can explain your question
> 
> ### Index Example
> Consider the string "Python" with a length of 6. The indexing is as follows:
> 
> * Positive index: `P` `y` `t` `h` `o` `n`
>   
>   * 0   1   2   3   4   5   6
> * Negative index: `P` `y` `t` `h` `o` `n`
>   
>   * -6 -5 -4 -3 -2 -1
> 
> ### Slice Explanation
> * Positive indices range from `0` to `6`, indicating positions between characters.
> * Negative indices range from `-6` to `-1`, also indicating positions between characters.
> 
> In the image, `-1` represents the position to the right of the last character `n`, not the character itself. This indexing method ensures consistency in slicing operations:
> 
> * `word[0:6]` means from the first character 'P' to the last character 'n' (excluding the right endpoint 6).
> * `word[-6:-1]` means from the first character 'P' to the position before the last character 'n' (excluding the right endpoint -1).
> 
> ### Summary
> * Both positive and negative indices indicate positions between characters.
> * The slice `word[i:j]` means from index `i` to `j` (excluding `j`).
> * Negative indices count from right to left, ensuring flexibility and consistency in slicing.
> 
> Therefore, `-1` in the image is correct as it represents the position to the right of the last character, not the character itself.

But if we count in reverse order and start counting from -1 then it should be finish at -7

**Comment by Wulian233** [comment]
😥

**Comment by kroshni** [comment]
> > There is no problem with the index -1 you said, but the document refers to slices, which is confused
> 
> 😥

Yeah, I was confused about the correct indexing to access the letter 'n' in the string, considering that using -1 would print the letter 'o'.

**Comment by data-if** [comment]
Perception bug?
