### ISSUE TITLE
C++ embedding python type hints SyntaxError: invalid syntax？

### ISSUE THREAD

**Issue by trising** [python/cpython#122346]
# Bug report

### Bug description:

Sorry, forgive me, my native language is not English and I may not have expressed myself very clearly.

I got a SyntaxError: invalid syntax error when embedding Python in a C++project and using the selenium library

```c
int main(int argc, char* argv[])
{
    Py_InitializeEx(0);

    if (!Py_IsInitialized()) {
        return 125;
    }

    PyRun_SimpleString("import sys\n"
        "sys.path.append('E:/selenium')\n"
        "from selenium import webdriver\n"
        "browser = webdriver.Chrome()\n"
        "browser.get(\"http://www.google.com/\")"
    );

    Py_FinalizeEx();

    return 0;
}
```
![20240727154611](https://github.com/user-attachments/assets/f109922f-9e4a-49a8-abc4-6115e7ca05b6)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello! It seems that somehow you have got a Python library from version 3.12+, but your interpreter is obviously older than version 3.12, since it does not support the PEP-695 syntax.

**Comment by trising** [comment]
> Hello! It seems that somehow you have got a Python library from version 3.12+, but your interpreter is obviously older than version 3.12, since it does not support the [PEP-695](https://peps.python.org/695) syntax.

Thank you，the problem has been identified, caused by multiple different versions of the environment
