### ISSUE TITLE
__static_attributes__ doesn't include method calls

### ISSUE THREAD

**Issue by PierreQuentel** [python/cpython#122445]
# Feature or enhancement

### Proposal:

```python
class C:

  def f(self):
    self.x
    self.y[3]
    self.z()

print(C.__static_attributes__) # gives ('y', 'x'), but 'z' is absent
```
From 3.13 documentation, `__static_attributes__` is _A tuple containing names of attributes of this class which are accessed through self.X from any function in its body.`_. Is there a reason why subscriptions are included in the result, but not method calls ?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122446
* gh-122621

**Comment by Eclips4** [comment]
cc @iritkatriel

**Comment by markshannon** [comment]
`__static_attributes__` is supposed to be a static approximation of the *instance* attributes, not the class's attributes.
So including methods is counter productive.

Maybe probably should only be counting stores, not loads when filling `__static_attributes__`?

**Comment by iritkatriel** [comment]
> `__static_attributes__` is supposed to be a static approximation of the _instance_ attributes, not the class's attributes. So including methods is counter productive.
> 
> Maybe probably should only be counting stores, not loads when filling `__static_attributes__`?

I was thinking the same, but then we need to change the documentation as well to make this clear.

**Comment by PierreQuentel** [comment]
Thank you Irit and Mark !
