### ISSUE TITLE
Indicate whether the build was DEBUG, RELEASE, PGO or LTO in the REPL

### ISSUE THREAD

**Issue by picnixz** [python/cpython#122470]
# Feature or enhancement

### Proposal:

When you compile from source and open the REPL, the first line is

```
Python <version> (<HEAD>, <date>) [<compiler>] on <platform>
```

I would be happy if I knew whether I used `--with-pydebug`, `--enable-optimizations` or `--with-lto` without needing to import or check manually the Makefile. I don't want something too long but I'd like to suggest something like

```
Python <version> (<debug|release|optimized[<FLAGS>]>) (<HEAD>, <date>) [<compiler>] on <platform>
```

with optimization flags being 'pgo', 'lto' or 'bolt' (not sure if there are more optimizations that are available). Actually, I don't even where to check if it was configured using LTO or not...

### Links to previous discussion of this feature:

I couldn't find something related (hard to use the keyword "REPL" without getting thousands of results...) but I didn't search for a long time.

### Linked PRs
* gh-122473

**Comment by ned-deily** [comment]
Thanks for your suggestion but I question whether the benefit is worth the cost especially when the proposed PR touches so many files. We have had discussions about making more build configuration information being displayed at REPL startup but I also was not able to easily find those past issues. But, as I recall, the arguments against were along the lines of that adding this info would be of no interest to the overwhelming number of users of Python and changes their user experience while, on the other hand, the very small number of users (primarily core developers) who might be interested can easily access this information today through standard interfaces, such as `python -m sysconfig` and `python -m test.pythoninfo` at the command line or by parsing `sysconfig.get_config_var("CONFIG_ARGS")`, something which could even be added to one's [Python startup script](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP). And, as we've seen over the years, compilers change and new optimization technologies are introduced sometimes making today's build options of little interest tomorrow. Let's keep it simple.

**Comment by encukou** [comment]
I asked about a similar feature at the language summit -- showing unsupported builds/architectures, rather than configuration, at startup. People were mostly uninterested.

Please discuss the proposal on Discourse first.

**Comment by picnixz** [comment]
> such as python -m sysconfig and python -m test.pythoninfo at the command line or by parsing sysconfig.get_config_var("CONFIG_ARGS"), something which could even be added to one's [Python startup script](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONSTARTUP)

I wasn't aware of `sysconfig`! My PR is definitely an overkill since I make the startup script so I'll close it. Actually, I didn't want to show *all* options but the major ones when you have a DEBUG/RELEASE or PGO build are of interest when you 1) benchmarks 2) check if your code has assertions (though you could check it by running a test in refleak and see whether you get an error saying you're not in a debug build).

Sorry for the noise! Closing as not planned.

**Comment by ned-deily** [comment]
BTW, you did a very thorough job on the PR!

**Comment by picnixz** [comment]
I learned a lot with that as well, so I'm quite happy (but sorry for taking your time for reading the PR, both you and Petr)
