### ISSUE TITLE
About IDLE: direct discussion to DPO

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#122482]
Change About IDLE to direct discussions to discuss.python.org.  Users are already doing so.

Currently, idle-dev@python.org and idle-dev mailing list serve, 90+%, to collect spam.  The few user messages per year are off topic requests for help, mostly not about IDLE.  The email should be disabled and the mailing list archived, but these actions are not part of this tracker.

### Linked PRs
* gh-122483
* gh-122485
* gh-122486

**Comment by Wulian233** [comment]
Finished, we can close it :)
