### ISSUE TITLE
Fail to compile python with Intel 23 or 24

### ISSUE THREAD

**Issue by VictorEijkhout** [python/cpython#122412]
I've downloaded python from
```
wget https://www.python.org/ftp/python/${pythonver}/Python-${pythonver}.tgz
```
with both 3.11.0 and 3.12.4.

I build with
```
    ./configure --prefix=${prefixdir} \
                --enable-optimizations
    ( make && make install ) 2>&1
```

and the installation hangs on:
```
Compiling '/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/zoneinfo/_common.py'...
Compiling '/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/zoneinfo/_tzpath.py'...
Compiling '/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/zoneinfo/_zoneinfo.py'...
```

Aborting shows:
```
KeyboardInterrupt
  File "/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/concurrent/futures/process.py", line 244, in _process_worker
    call_item = call_queue.get(block=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/multiprocessing/queues.py", line 102, in get
    with self._rlock:
  File "/work2/00434/eijkhout/python/installation-3.11.0-intel/lib/python3.11/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
```

FWIW I was able to build successfully with gcc13.

**Comment by mpanoop** [comment]
@VictorEijkhout , were you using Intel Compiler when the installation hanged? If yes, which version of Intel Compiler are you using?

**Comment by vstinner** [comment]
Try to run test suite to see if something goes wrong:

`./python -m test --slow-ci`

**Comment by tlunet** [comment]
Same error as #91080 (although I don't understand why the later was closed ...)

**Comment by picnixz** [comment]
> although I don't understand why the later was closed ...

This is because the involved compiler (namely icpx) is not officially supported. We only support those that are listed on https://peps.python.org/pep-0011, hence the closed issue.

**Comment by tlunet** [comment]
Well, it may work with the next Intel OneAPI (icpx) release then, see #106424

**Comment by picnixz** [comment]
I'm not sure whether this issue needs to be closed or not since it's a compiler we don't officially support (well, for this specific issue we don't know the exact version also). I'm letting it opened but we might close it if there is no feedback from the OP.

**Comment by tlunet** [comment]
> I've just upgraded to Intel 2024.2 and with that it seems to compile.

And installation doesn't hang on ?

**Comment by VictorEijkhout** [comment]
Compile successful, no hang. The `cmath` test still fails. I'll dig into that.

**Comment by picnixz** [comment]
I'm closing this issue then (open a new one if the test still fails).
