### ISSUE TITLE
 Run the specified file, catching the wrong number of lines and the wrong text

### ISSUE THREAD

**Issue by liuzhongyi2** [python/cpython#122437]
# Bug report

### Bug description:

```python
import traceback

# 假设 '/storage/emulated/测试/测试.py' 是你要运行的脚本的路径
script_path = '/storage/emulated/测试/测试.py'

try:
    # 使用 exec 来运行另一个 Python 文件的内容
    with open(script_path, 'r') as script_file:
        code = compile(script_file.read(), script_path, 'exec')
        exec(code)
except Exception as e:
    # 获取异常的完整轨迹
    tb_info = traceback.format_exc()
    # 分割轨迹信息以获取文件名和行号
    file_line = tb_info.split('File "')[1].split('", line ')[0]
    line_number = tb_info.split('", line ')[1].split(')')[0]
    error_message = tb_info.split('\n')[-2]
    
    # 打印行号和错误信息
    print(f"错误发生在 {file_line} 的第 {line_number} 行")
    print(f"错误信息：{error_message}")
#获取错误行数
#print(e.__traceback__.tb_lineno)
```
It does not print the number of lines in the specified file, I really do not know how to do

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
This is the issue tracker for bugs in Python itself.

For help with your code, please ask in the discussion forum: https://discuss.python.org/c/help/7

**Comment by Wulian233** [comment]
又是你，这里不是求助程序的地方，是汇报cpython本身错误的地方。另外我在之前已经说过，不要用中文，别人看不懂https://github.com/python/cpython/issues/122382

You again, this is not the place to ask for help, this is the place to report cpython itself wrong. In addition, I have said before, do not use Chinese, others can not understand
