### ISSUE TITLE
Minor: 3.13t default install doesn't pip

### ISSUE THREAD

**Issue by dimaqq** [python/cpython#122497]
# Bug report

### Bug description:

macOS, installed 3.13.0b4 with the free-threading extra from python.org

```
> python3.13 -m pip

Usage:
  /Library/Frameworks/Python.framework/Versions/3.13/bin/python3.13 -m pip <command> [options]
...

> python3.13t -m pip
/usr/local/bin/python3.13t: No module named pip
```

can be trivially solved by `python3.13t -m ensurepip`

so, maybe not a big issue, though I wonder how come?

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by ned-deily** [comment]
The need to manually install pip was a [documented restriction](https://github.com/python/cpython/issues/120098) of the initial releases of free-threading support with the python.org macOS installer. The imminent 3.13.0rc1 release will remove that restriction.
