### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by 21-ko** [python/cpython#122537]
# Bug report

### Bug description:

```python
import struct

format = 'QQHIHQ'

bin = struct.pack(
    format,
    128,
    255,
    1, # H
    2, # I
    3, # H
    4  # Q
)

print("Packed bin:", bin)
print("Length of packed bin:", len(bin))
```

result:
```cmd
Packed bin: b'\x80\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00\x00\x00\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00'
Length of packed bin: 40
```

The length of the bin is output as 40 instead of 32.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by zware** [comment]
Please see the documentation, particularly the section on [Byte Order, Size, and Alignment](https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment).  To avoid implicit padding, use a format with an explicit byte order:

```pycon
>>> struct.pack('=QQHIHQ', 128, 255, 1, 2, 3, 4)
b'\x80\x00\x00\x00\x00\x00\x00\x00\xff\x00\x00\x00\x00\x00\x00\x00\x01\x00\x02\x00\x00\x00\x03\x00\x04\x00\x00\x00\x00\x00\x00\x00'
>>> len(_)
32
```

---

For future reference, if you're not sure whether something is a bug, please first ask on [Discourse](https://discuss.python.org/c/help/7/).

**Comment by 21-ko** [comment]
Oh... sorry 😳
