### ISSUE TITLE
Move the bodies of large instructions into helper functions.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#122598]
There are two reasons for this:
1. Big chunks of code slow down the JIT and the resulting machine code.
2. These big chunks of code usually have complex control flow which makes analysis of the code for stack spilling and top-of-stack much harder.

Using tokens are (a quite approximate) guide to complexity, here are the uops with over 200 tokens:

_CALL_BUILTIN_FAST_WITH_KEYWORDS 200
_BINARY_SUBSCR_GETITEM 203
_LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN 210
_CALL_METHOD_DESCRIPTOR_NOARGS 212
_CALL_METHOD_DESCRIPTOR_O 214
_LOAD_FROM_DICT_OR_GLOBALS 215
_YIELD_VALUE 219
_LOAD_SUPER_ATTR 241
_CALL_METHOD_DESCRIPTOR_FAST 247
_CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS 258
_DYNAMIC_EXIT 269
_STORE_ATTR_WITH_HINT 273
_SEND 274
_EXIT_TRACE 335
_CALL_ALLOC_AND_ENTER_INIT 358
_DO_CALL 365
_CALL_FUNCTION_EX 469
_CALL_KW 498

### Linked PRs
* gh-122601

**Comment by inzk** [comment]
> هناك سببان لهذا:
> 
> 1. تؤدي أجزاء كبيرة من التعليمات البرمجية إلى إبطاء JIT والتعليمات البرمجية الآلية الناتجة.
> 2. عادةً ما تحتوي أجزاء التعليمات البرمجية الكبيرة هذه على تدفق تحكم معقد مما يجعل تحليل التعليمات البرمجية للانسكاب في المكدس وأعلى المكدس أكثر صعوبة.
> 
> يعد استخدام الرموز دليلاً تقريبيًا إلى حد ما على التعقيد، وهنا وحدات UOP التي تحتوي على أكثر من 200 رمز:
> 
> _CALL_BUILTIN_FAST_WITH_KEYWORDS 200 _BINARY_SUBSCR_GETITEM 203 _LOAD_ATTR_GETATTRIBUTE_OVERRIDDEN 210 _CALL_METHOD_DESCRIPTOR_NOARGS 212 _CALL_METHOD_DESCRIPTOR_O 214 _LOAD_FROM_DICT_OR_GLOBALS 215 _YIELD_VALUE 219 _LOAD_SUPER_ATTR 241 _CALL_METHOD_DESCRIPTOR_FAST 247 _CALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS 258 _DYNAMIC_EXIT 269 _STORE_ATTR_WITH_HINT 273 _SEND 274 _EXIT_TRACE 335 _استدعاء_التخصيص_و_إدخال_المفتاح_358 _افعل_استدعاء 365 _استدعاء_وظيفة_التنفيذ 469 _استدعاء_مفتاح_المفتاح 498
> 
> ### العلاقات العامة المرتبطة
> * [GH-122598: نقل جسم عدد قليل من العمليات الدقيقة الكبيرة إلى وظائف مساعدة  #122601](https://github.com/python/cpython/pull/122601)

O

**Comment by markshannon** [comment]
Closing as duplicate of https://github.com/python/cpython/issues/117224
