### ISSUE TITLE
Clean up and microoptimize str.translate and charmap codec

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#122561]
Initially I just planned to get rid of `PyLong_AS_LONG` (undocumented transitional alias of `PyLong_AsLong`) in `Objects/unicodeobject.c`. But I have used opportunity to add few optimizations in the nearby code. I do not expect significant performance boost, but some overhead was removed in specific corner cases:

* `PyLong_AsLongAndOverflow` is now only called once for the replacement code (`PyLong_AS_LONG` was called twice).
* Using `PyMapping_GetOptionalItem` instead of `PyObject_GetItem` allows to avoid raising a `KeyError` if the translation table is a `dict`. I left this case in previous round (#106307) because this does not make the code simpler (we still need to handle other `LookupError`), but it still has a tiny performance benefit.

### Linked PRs
* gh-122932

**Comment by vstinner** [comment]
Do you plan to create a pull request?

**Comment by serhiy-storchaka** [comment]
I _thought_ that I already created a PR. Now I have to find where it went.
