### ISSUE TITLE
[cleanup] Remove removed functions from `Doc/data/refcounts.dat`

### ISSUE THREAD

**Issue by picnixz** [python/cpython#122555]
# Feature or enhancement

### Proposal:

This is a follow-up of https://github.com/python/cpython/pull/122331#discussion_r1699206142 where a typo was not spotted. Some functions are still in this file but were removed in previous versions (see the corresponding PR for how I detected them).

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122556

**Comment by vstinner** [comment]
Fixed by change https://github.com/python/cpython/commit/88030861e216ac791725c8784752201d6fe31329.

**Comment by picnixz** [comment]
Thank you Victor!
