### ISSUE TITLE
symtable: ste_free and ste_child_free are unused

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#122562]
`symtable.c` computes the `ste_free` and `ste_child_free` values but nothing in the code uses them. Let's clean up those fields.

cc @carljm @iritkatriel 

### Linked PRs
* gh-122563
* gh-122825

**Comment by carljm** [comment]
Assuming we aren't backporting this change (since it doesn't fix a bug, I don't think we should -- the argument in favor would be reducing conflicts on other backports), this issue should be ready to close?
