### ISSUE TITLE
What about making `arguments` attribute of class `inspect.BoundArgument` a dataclass

### ISSUE THREAD

**Issue by 2catycm** [python/cpython#122526]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
def foo(a:int, b:str)->float:
    pass
sig = inspect.signature(foo)
bound_args = sig.bind(1, "test")
a:int = bound_args.arguments.a
b:str = bound_args.arguments.b
```
Then the usage of `bound_args.arguments` are strongly typed and can be checked by the ide. 

### Has this already been discussed elsewhere?

No response given

**Comment by ericvsmith** [comment]
You should bring this up on https://discuss.python.org/c/ideas/6 first. But since the fields aren't known at compile time, I don't see how this would work. Be prepared to address that issue when you post.
