### ISSUE TITLE
Hack the find_closest() method from tkinter canvas

### ISSUE THREAD

**Issue by tmelorc** [python/cpython#122541]
According to
https://github.com/python/cpython/blob/46f5a4f9e1781ad8d60eb53bbaf6cd8534a286cd/Lib/tkinter/__init__.py#L3045

>         Return item which is closest to pixel at X, Y.
>         If several match take the top-most.
>         All items closer than HALO are considered overlapping (all are
>         closest). If START is specified the next below this tag is taken.

I'd like to know how to define a similar method to return the bottom-most, that is, the opposite of top-most.

**Comment by terryjreedy** [comment]
This issue tracker is for patching the CPython distribution.  Ask questions on discourse.python.org or elsewhere, such as stackoverflow.
