### ISSUE TITLE
socket module shutdown() constants SHUT_RD, etc not included in Constants section

### ISSUE THREAD

**Issue by jweaver-ca** [python/cpython#122519]
# Documentation

In documentation for socket module, the constants SHUT_RD, SHUT_WR, SHUT_RDWR are mentioned in the description for shutdown(), but they are missing from the Constants section on that page.

### Linked PRs
* gh-122543
* gh-123093
* gh-123094

**Comment by picnixz** [comment]
We don't document all of them one by one, but I think we can document them using `SHUT_*` like that.

**Comment by Damien-Chen** [comment]
Hi @picnixz,
you means adding `SHUT_*` in the below field ?
![image](https://github.com/user-attachments/assets/dd17a06a-a513-441f-af30-668bd4cb4be4)

**Comment by picnixz** [comment]
Mmh, perhaps not. They are generally used in arguments to the [setsockopt()](https://docs.python.org/3/library/socket.html#socket.socket.setsockopt) and [getsockopt()](https://docs.python.org/3/library/socket.html#socket.socket.getsockopt). A dedicated category could be made, like for https://docs.python.org/3/library/socket.html#socket.SIO_RCVALL (it's a group of 3 constants for a specific function).

**Comment by Damien-Chen** [comment]
Ok, so make a category like the below and mention these argument are used to the `socket.shutdown()` method of socket object. 
`SHUT_RD`
`SHUT_WR`
`SHUT_RDWR`

If my understanding is right ?
Thank you.

**Comment by picnixz** [comment]
Yes, something like that. Best is to see how the other constants are documented when they are grouped. You'll need to update the links to those constants as well.

**Comment by Damien-Chen** [comment]
I made a preliminary modification on documention, please help me check if there is anything need to change, thank you very much!
