### ISSUE TITLE
System error: impossible<bad format character> only in python 3.12

### ISSUE THREAD

**Issue by Bemnet-Suleman** [python/cpython#122518]
# Bug report

### Bug description:

```pytb
File "C:\Python\PycharmProjects\PSG\MikesDemos\Mike_Desktop_Widget_Drive_Usage.py", line 191, in <module>
    main(location)
  File "C:\Python\PycharmProjects\PSG\MikesDemos\Mike_Desktop_Widget_Drive_Usage.py", line 154, in main
    update_window(window)  # sets the progress bars
    ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python\PycharmProjects\PSG\MikesDemos\Mike_Desktop_Widget_Drive_Usage.py", line 89, in update_window
    usage = psutil.disk_usage('A:\\')
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Python\python3.12\Lib\site-packages\psutil\__init__.py", line 2005, in disk_usage
    return _psplatform.disk_usage(path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "X:\Python\python3.12\Lib\site-packages\psutil\_pswindows.py", line 280, in disk_usage
    total, free = cext.disk_usage(path)
                  ^^^^^^^^^^^^^^^^^^^^^
SystemError: argument 1 (impossible<bad format char>)

Process finished with exit code 1
```
It is not only with this it is in many more packages that work well with other version of python 3.
it is also happening in the built in python socket .
Thank you!

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by hugovk** [comment]
Please can you create a minimal sample of code that reproduces the problem?

See https://stackoverflow.com/help/minimal-reproducible-example

**Comment by Bemnet-Suleman** [comment]
Import socket

serverSocket = socket.socket(socket.AF_BLUETOOTH, socket.SOCK_STREAM, socket
.BTPROTO_RFCOMM)

addr="B8:27:EB:22:57:E0" #some random address

port = 3

serverSocket.bind((addr,port)) #or serverSocket.connect((addr,port))

serverSocket.listen(1)

"""i get the error :just in python 3.12

serverSocket.bind(("",port))

bt.bind (self._sockfd, addr, port)

SystemError: argument 2 (impossible<bad format char>)

"""

**Comment by ZeroIntensity** [comment]
Based on the traceback, this seems to be an error in [psutil](https://psutil.readthedocs.io/en/latest/), not CPython. See [this issue](https://github.com/giampaolo/psutil/issues/2252) on their repository.

**Comment by Bemnet-Suleman** [comment]
Thanks a lot sorry for any watste.
