### ISSUE TITLE
Repeated definition of PY_BUILTIN_HASHLIB_HASHES in configure.ac

### ISSUE THREAD

**Issue by msprotz** [python/cpython#122571]
# Bug report

### Bug description:

The PY_BUILTIN_HASHLIB_HASHES variable is defined twice in configure.ac, which
results in the corresponding #define appearing twice in the autoconf
confdefs.h, which results in an unconditional compile error, meaning the test
isn't testing what it is supposed to test. 

Found via https://github.com/python/cpython/pull/119316

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-122572
* gh-122763

**Comment by picnixz** [comment]
Closing since it was completed and backported.
