### ISSUE TITLE
Inconsistency between file names of SyntaxErrors and other Exceptions in the new repl

### ISSUE THREAD

**Issue by cfbolz** [python/cpython#122546]
A small issue, but the new repl reports `<unknown>` as the file name for `SyntaxErrors`, but `<python-input-x>` for other errors:

```
>>> a b c
  File "<unknown>", line 1
    a b c
      ^
SyntaxError: invalid syntax
>>> 1 / 0
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
```

Classic repl:
```
>>> a b c
  File "<stdin>", line 1
    a b c
      ^
SyntaxError: invalid syntax
>>> a
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
    a
NameError: name 'a' is not defined
>>> 
```

I think this is because `_pyrepl.console.InteractiveColoredConsole.showsyntaxerror` does not pass on the `filename` argument to the super method:

```python
    def showsyntaxerror(self, filename=None):
        super().showsyntaxerror(colorize=self.can_colorize)
```

Should probably wait till #122528 is done. Then, `InteractiveColoredConsole` could be simplified to overwrite only `_showtraceback`. The undocumented colorize keyword arguments that `showtraceback` and `showsyntaxerror` have gained for pyrepl could be removed again.

### Linked PRs
* gh-123217
* gh-123226
* gh-123233
* gh-123246
* gh-123247

**Comment by skirpichev** [comment]
pr is ready: https://github.com/python/cpython/pull/123217

**Comment by cfbolz** [comment]
there's another form of the bug, with `IndentationError`, which still shows `<unknown>`:

```python
>>>  b
  File "<unknown>", line 1
    b
IndentationError: unexpected indent
```

**Comment by skirpichev** [comment]
Yes, we should use less strict type check.  Correction: #123233.

**Comment by pablogsal** [comment]
I think we are done. Please reopen if we missed anything. Thanks @skirpichev for the PRs!
