### ISSUE TITLE
Change base OS image  to Ubuntu-24.04 in CI testing

### ISSUE THREAD

**Issue by Damien-Chen** [python/cpython#122544]
In current `ci.yml`, base OS image is `ubuntu-22.04`, should we move to the latest LTS verion: `ubuntu-24.04` ?

> 
>   pool:
>     vmImage: ubuntu-22.04

To go further, if we should replace all current CI testing which run on `ubuntu-22.04` to `ubuntu-24.04` ?

### Linked PRs
* gh-122566
* gh-122568
* gh-122570
* gh-122593
* gh-122594
* gh-125344
* gh-126479
* gh-126480
* gh-126619
* gh-126621
* gh-130260
* gh-130268
* gh-130295

**Comment by Eclips4** [comment]
cc @hugovk @ezio-melotti

**Comment by hugovk** [comment]
Thanks for the report, we're using `ubuntu-22.04` in Read the Docs, Azure Pipelines and GitHub Actions:

```console
❯ rg ubuntu-22.04
.readthedocs.yml
11:  os: ubuntu-22.04

.azure-pipelines/ci.yml
8:    vmImage: ubuntu-22.04

.azure-pipelines/pr.yml
8:    vmImage: ubuntu-22.04
20:    vmImage: ubuntu-22.04

.github/workflows/build.yml
47:    runs-on: ubuntu-22.04
198:    runs-on: ubuntu-22.04
264:    runs-on: ubuntu-22.04
378:    runs-on: ubuntu-22.04

.github/workflows/reusable-wasi.yml
12:    runs-on: ubuntu-22.04

.github/workflows/reusable-tsan.yml
22:    runs-on: ubuntu-22.04

.github/workflows/reusable-ubuntu.yml
17:    runs-on: ubuntu-22.04
```

Yes, let's upgrade, assuming all the dependencies and everything installs fine.

Would you like to open some PRs? I suggest a separate PR for each of Read the Docs, Azure Pipelines and GitHub Actions.

**Comment by Damien-Chen** [comment]
Sure!, Of course, I'd love to contribute to this, let me first investigate if it would affect the result of CI testing if just simply change `ubuntu-22.04` to `ubuntu-24.04`.

**Comment by hugovk** [comment]
The comment at the top says they should match:

https://github.com/python/cpython/blob/fda6bd842a2b93a501526f1b830eb900d935ac73/Tools/build/regen-configure.sh#L5-L8

Which should be the same as this one:

https://github.com/python/cpython/blob/fda6bd842a2b93a501526f1b830eb900d935ac73/.github/workflows/build.yml#L43-L47

**Comment by picnixz** [comment]
> The comment at the top says they should match:

Oh then we should update both of them then! (and I'll need to update my PR in the devguide as well)

**Comment by Damien-Chen** [comment]
Some other `yml` file based on `ubunut-latest`, for exmaple: in `jit.yml`. based on 
https://github.com/actions/runner-images description, `ubuntu-latest` is actually `ubuntu-22.04`, should those file mentioned `ubuntu-latest` need to upgrade ubuntu version ?

>          architecture: x86_64
            runner: ubuntu-latest
            compiler: gcc
          - target: x86_64-unknown-linux-gnu/clang
            architecture: x86_64
            runner: ubuntu-latest
            compiler: clang
          - target: aarch64-unknown-linux-gnu/gcc
            architecture: aarch64
            runner: ubuntu-latest
            compiler: gcc
          - target: aarch64-unknown-linux-gnu/clang
            architecture: aarch64
            runner: ubuntu-latest
            compiler: clang

**Comment by hugovk** [comment]
No, let's not change any `ubuntu-latest`.

In fact, https://github.com/actions/runner-images?tab=readme-ov-file#available-images says `ubuntu-24.04` is still beta, maybe we should wait until it is in GA (General Availability)?

Do you know when GA is planned?

**Comment by Damien-Chen** [comment]
According to there discussion in 
https://github.com/actions/runner-images/issues/9691
The GA will be somewhere in August-2024, I think it should be soon.

I think we can move all CI-testing step-by-step.
First change trivial CI testiing(like readthedocs) to `ubuntu-24.04` to test it. 
If everthing goes well, then we can move core part(like checking JIT) to `ubuntu-24.04` gradually

**Comment by AngelicaOvesdotter** [comment]
> In current `ci.yml`, base OS image is `ubuntu-22.04`, should we move to the latest LTS verion: `ubuntu-24.04` ?
> 
> > pool:
> > vmImage: ubuntu-22.04
> 
> To go further, if we should replace all current CI testing which run on `ubuntu-22.04` to `ubuntu-24.04` ?
> 
> ### Linked PRs
> * [gh-122544: Change OS image in GitHub Actions to ubuntu-24.04 #122566](https://github.com/python/cpython/pull/122566)
> * [gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04 #122568](https://github.com/python/cpython/pull/122568)
> * [gh-122544: Change OS image in Azure Pipelines to ubuntu-24.04 #122570](https://github.com/python/cpython/pull/122570)
> * [[3.13] gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04 (GH-122568) #122593](https://github.com/python/cpython/pull/122593)
> * [[3.12] gh-122544: Change OS image in readthedocs.yml to ubuntu-24.04 (GH-122568) #122594](https://github.com/python/cpython/pull/122594)

**Comment by AngelicaOvesdotter** [comment]
![image](https://github.com/user-attachments/assets/585ab893-2aa8-4295-b3c5-a74314b46e33)

**Comment by Damien-Chen** [comment]
Close PR for Azure Pipeline as it currently provide `ubuntu-24.04`

**Comment by Damien-Chen** [comment]
According to latest update in [Github Action](https://github.com/actions/runner-images), `ubuntu-24.04` is release as GA now, let`s continue to work it.

**Comment by hugovk** [comment]
Note: we pinned `ubuntu-latest` to `ubuntu-22.04` in `.github/workflows/jit.yml` because of some oddness with `ubuntu-24.04`. We'll upgrade it at some later date.

See https://github.com/python/cpython/pull/125564 / https://github.com/python/cpython/issues/125560.

**Comment by luapun** [comment]
MUJER HERMOSA
