### ISSUE TITLE
Incorrect minimum version of Python for Windows build bootstrapping

### ISSUE THREAD

**Issue by msprotz** [python/cpython#122573]
# Bug report

### Bug description:

Python now requires 3.10 to build itself, because `match` case statements have begun proliferating in the cpython repository. However, the Windows build still thinks 3.9 is enough, which results in a build error on a standard Visual Studio 2022 environment.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-122574
* gh-122674
* gh-122677

**Comment by Eclips4** [comment]
Hello!
I can build CPython using the 3.9 version. Can you please show the error?

**Comment by msprotz** [comment]
```
C:\Users\protz\Desktop\cpython\PCbuild>build
Using py -3.9 (found 3.9 with py.exe)
...
  Regenerate keyword.py
  Regenerate Global Objects
  # not changed: C:\Users\protz\Desktop\cpython\Include\internal\pycore_global_strings.h
  # not changed: C:\Users\protz\Desktop\cpython\Include\internal\pycore_runtime_init_generated.h
  # not changed: C:\Users\protz\Desktop\cpython\Include\internal\pycore_unicodeobject_generated.h
  # not changed: C:\Users\protz\Desktop\cpython\Include\internal\pycore_global_objects_fini_generated.h
  Regenerate cases
  Traceback (most recent call last):
    File "C:\Users\protz\Desktop\cpython\Tools\cases_generator\opcode_id_generator.py", line 8, in <module>
      from analyzer import (
    File "C:\Users\protz\Desktop\cpython\Tools\cases_generator\analyzer.py", line 724
      match part:
            ^
  SyntaxError: invalid syntax
C:\Users\protz\Desktop\cpython\PCbuild\regen.targets(93,5): error MSB3073: The command "py -3.9 Tools\cases_generator\o
pcode_id_generator.py Python\bytecodes.c" exited with code 1. [C:\Users\protz\Desktop\cpython\PCbuild\pythoncore.vcxpro
j]

Build FAILED.

C:\Users\protz\Desktop\cpython\PCbuild\regen.targets(93,5): error MSB3073: The command "py -3.9 Tools\cases_generator\o
pcode_id_generator.py Python\bytecodes.c" exited with code 1. [C:\Users\protz\Desktop\cpython\PCbuild\pythoncore.vcxpro
j]
    0 Warning(s)
    1 Error(s)
```

**Comment by msprotz** [comment]
This is without the --jit option -- I believe my other PR touched something related to global objects, which in turn triggered the invocation of cases_generator/opcode_id_generator.py, which failed, on the default build.

**Comment by msprotz** [comment]
This is the other PR: https://github.com/python/cpython/pull/119316

**Comment by Eclips4** [comment]
> This is without the --jit option -- I believe my other PR touched something related to global objects, which in turn triggered the invocation of cases_generator/opcode_id_generator.py, which failed, on the default build.

You're right.

**Comment by gpshead** [comment]
backports pending and assigned, closing.  thanks!
