### ISSUE TITLE
Add `platform.invalidate_caches` for invalidating cached results

### ISSUE THREAD

**Issue by picnixz** [python/cpython#122549]
# Feature or enhancement

### Proposal:

In #122525, it was observed that many functions of the `platform` module use cached results. This is, in practice, preferrable, but it should also be possible, if needed, to invalidate cached results. One use case is when the host name changes (i.e., one of the `uname()` components change).

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-122547

**Comment by kashav** [comment]
> One use case is when the host name changes (i.e., one of the uname() components change).

Mostly out of curiosity - is there any way to watch for host name change?

**Comment by picnixz** [comment]
Well.. you could have a task that runs every second and checks whether the host name changed or not. `socket.gethostname` gives you the runtime one, so you'll need to query it every second.

**Comment by picnixz** [comment]
Completed in 612ac283b81907d328891b102f5bfafcf62bd833.
