### ISSUE TITLE
Enforce and document restrictions for command line installations of python.org macOS installers

### ISSUE THREAD

**Issue by maltfield** [python/cpython#122579]
**Is your feature request related to a problem? Please describe.**

This is a request to update the documentation to include how to actually install Python on MacOS after downloading the `.pkg` file

 * https://docs.python.org/3/using/mac.html#getting-and-installing-python

**Describe the solution you'd like**

The documentation should include the commands to run to install the `.pkg` file and to then open a python interpreter to get a shell in python.

**Additional context**

This is especially confounding on headless systems. The docs say how to download, but then jump to `What you get after installing` without saying how the heck you actually do the install...

**Comment by ned-deily** [comment]
Sorry for the delay in responding, I just noticed your issue under the website tracker. Judging from the discussion in the linked Stackexchange issue, you have already discovered that the python.org installer for macOS does not currently allow selecting an install location other than in /Library/Frameworks and, optionally in addition, /usr/local/bin. I don't recall ever seeing the use of the `-domain` option on the `installer` command. The way the `.pkg` file is built, you aren't supposed to be able to specify an install location and, if you use the Apple-supplied GUI Installer.app, it will not offer that option. I'm surprised that `installer` doesn't honor that, as well, but [it looks like that has been its behavior for a long time](https://stackoverflow.com/questions/7751053/osx-installer-change-install-directory). While there are open issues to support relocatable installs on macOS, I will leave this open to see if there is anything we can do to mitigate the case you ran into here today. Also, including more information on doing command line installs would be a good thing, too.

**Comment by ned-deily** [comment]
Information on how to install python.org macOS installers from the command line is now included in the substantially revised [Using Python on macOS](https://docs.python.org/3.13/using/mac.html#installing-using-the-command-line) section of the [Python Setup and Usage](https://docs.python.org/3.13/using/index.html) document for Python 3.13 including the restriction on installation locations.
