### ISSUE TITLE
Add tests for ast optimizations

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#122666]
# Feature or enhancement

### Proposal:

Currently we have a one test case which testing that `optimize` parameter for ast.parse is working as expected.

I propose to add tests for these ast optimizations:
* Optimization for binary operations if left and right operands are constants
* Optimization for unary operations if operand is constant
* Optimization for `in` operator if right operand is constant list or set
* Folding of tuples
* Subscription for constant sequences (tuple, string)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122667
* gh-123359

**Comment by serhiy-storchaka** [comment]
Tests for optimization are included in test_peepholer.

**Comment by Eclips4** [comment]
> Tests for optimization are included in test_peepholer.

`test_peepholer` tests that something is present in the bytecode, but it doesn't tell which part of interpreter are responsible for that.
