### ISSUE TITLE
dataclass freeze specific fields

### ISSUE THREAD

**Issue by dsal3389** [python/cpython#122656]
# Feature or enhancement

## introduction 
freezing specific fields and not the whole class is common, to achieve that with the current dataclass implementation
we need to write a bit of code while the whole point of dataclasses is to create classes easily

```py
from dataclasses import dataclass, field, InitVar

@dataclass(repr=True)
class Person:
    p_name: InitVar[str]
    _name: str = field(init=False, repr=False)
    age: int

    @property
    def name(self) -> str:
        return self._name

    def __post_init__(self, name: str) -> None:
        self._name = name


p = Person(p_name="Bob", age=44)
print(p)
```
the code is ugly, we need to define `name` as `p_name` in the class annonations
because if we don't, the property name is colliding with the annotation name 

also when we run `print(p)` we missing on the field because we don't want to show
private fields on our `repr`
```
Person(age=44)
```

and even then the field is not safe from manipulation like it would be with frozen!
```py
p._name = "foo"
```

## solution

since `kw_only` can be specified on the class level and per field, it make sense to also 
do that for `frozen`
```python
from dataclass_test import dataclass, field


@dataclass(repr=True)
class Person:
    name: str = field(frozen=True)
    age: int


p = Person(name="bob", age=22)
```
now the code is much clearer, and when calling `repr` on our instance we see our field
```
Person(name='bob', age=22)
```
it is now a little bit more safe from manipulation
```
p.name = "foo"
```
expected error:
```
dataclass_test.FrozenInstanceError: cannot assign to field 'name'
```
## setting limitations
there are couple of scenarios where it make sense to limit that feature

### setting `frozen=False` on field for a frozen class
this should give us an error
```py
@dataclass(repr=True, frozen=True)
class Person:
    name: str = field(frozen=False)  # making `name` unfrozen on a frozen class
    age: int
```
expected error
```
ValueError: field `name` marked as not frozen on a frozen class `Person`
```

### setting frozen fields for `InitVar` and `ClassVar`
it doesn't make sense to create frozen fields on something that won't be
part of the instance

> this breaks backward compatibility, so probably won't be included in the changes

```py
@dataclass(repr=True)
class Person:
    name: str = field(frozen=True)
    age: int
    foo: InitVar[bool] = field(frozen=True)  # cannot make frozen `InitVar`
```
```py
@dataclass(repr=True)
class Person:
    name: str = field(frozen=True)
    age: int
    foo: ClassVar[bool] = field(frozen=True)  # cannot make frozen `ClassVar`
```
expected error
```
TypeError: field `name` cannot be frozen
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-122657

**Comment by ZeroIntensity** [comment]
I think this needs discussion on discourse.

**Comment by dsal3389** [comment]
so should I open a discussion and link to this issue?

**Comment by ZeroIntensity** [comment]
Sure, or just copy-paste the content of this issue.

**Comment by hugovk** [comment]
For reference, https://discuss.python.org/t/dataclasses-freezing-specific-fields-should-be-possible/59968 is the discussion.

**Comment by ericvsmith** [comment]
Since the discuss.python.org discussion didn't get any traction, I'm going to close this.
