### ISSUE TITLE
Much inflated memory usage in 3.12

### ISSUE THREAD

**Issue by rhpvorderman** [python/cpython#122619]
# Bug report

### Bug description:

I maintain an application [sequali](https://github.com/rhpvorderman/sequali), that works on high throughput sequencing data. Typically the memory usage is below 1 GB. With python 3.12 the memory balloons out to over 6GB in the same circumstance. 
However, if I put a memory tracker on the application (memray and memory_profiler), the memory stays normal again. 

Any idea how I can whittle this down to the actual bug? Could it be garbage collection related?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ZeroIntensity** [comment]
> However, if I put a memory tracker on the application (memray and memory_profiler), the memory stays normal again.

I'm certain that I've known of someone encountering this kind of "when I profile it goes back to normal" memory problem in the past year or so. Unfortunately, I don't remember how, or if they fixed it, but I'm pretty sure this isn't a CPython issue.

**Comment by rhpvorderman** [comment]
My bad. I am sorry, this seems specifically related to the bioconda distribution of the package. I used the conda-forge python 3.12 and the PyPI package and that mitigates the issue. So this is indeed not a python bug.

**Comment by rhpvorderman** [comment]
I found the issue. The fault was in my code. Specifically I created a `PyVarObject` directly using `PyObject_Malloc` and setting the reference count using `Py_SET_REFCNT`. That macro was changed in CPython 3.12 to leave immortal objects untouched. Unfortunately using `PyObject_Malloc` meant that the area of memory where the refcount was stored was sometimes already a high number thus designating the object as immortal. As a result the refcount was not set to 1 by the `Py_SET_REFCNT` macro. 

This also made sure the error was intermittent. Sometimes a memory pool that had been zeroed out would be used and the issue wouldn't occur. As soon as I found that this was the case, I simply run with the memory profiler multiple times until the issue occured and was able to pinpoint it that way. 

I changed the code to use `PyObject_NewVar` instead, as is appropriate for these cases. The reasons I did not do so initially was inexperience with `PyVarObject`. I did not know what to do and I adapted the code from `PyBytes_New`, which did use `PyObject_Malloc` and `Py_SET_REFCNT` directly.

**Comment by itamaro** [comment]
woah, this sounds like a dangerous footgun!

cc @ericsnowcurrently @encukou wdyt?
while it is [documented](https://docs.python.org/3/c-api/memory.html#c.PyObject_Malloc) that memory returned by `PyObject_Malloc` is "not initialized in any way", it is quite surprising that it can randomly return unintended immortal objects (and `Py_SET_REFCNT` wouldn't help).
perhaps there should be a warning added to the docs?

**Comment by rhpvorderman** [comment]
Should I make this in a new, not closed issue? I wonder how many C-extensions have fallen in this trap. Presumably not many.

**Comment by ZeroIntensity** [comment]
Though, it is odd to manually allocate a `PyVarObject`. You should be using `tp_new` and/or `tp_init` to properly initialize the object, or in rare cases `tp_alloc` -- I've never manually touched `PyObject_Malloc`.

**Comment by rhpvorderman** [comment]
@ZeroIntensity This is about implementing the tp_new function, not using it. PyObject_Malloc is a valid way to create a python object. It was done so in CPython itself. However PyObject_New and PyVarObject_New lead to much less headaches so I will be sure to use that always in the future.

**Comment by ZeroIntensity** [comment]
I would use `tp_alloc` there.
