### ISSUE TITLE
Add a `seconds` parameter to the constructor for `datetime.datetime`

### ISSUE THREAD

**Issue by hasanelfalakiy** [python/cpython#122691]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
dt = datetime(2024, 8, 15, 12, 30, 51.97)
```
please add the seconds part input feature supporting the float data type, because I want the need to calculate data with high accuracy 

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

**Comment by aisk** [comment]
As the document mentioned [^1], `datetime.datetime` supports [microsecond](https://docs.python.org/3/library/datetime.html#datetime.time.microsecond) part:

```
dt = datetime(2024, 8, 15, 12, 30, 51, 12345)
```

[^1]: https://docs.python.org/3/library/datetime.html#available-types

**Comment by RafaelJohn9** [comment]
@AlexWaygood  I will be working on this issue

**Comment by AlexWaygood** [comment]
Hi @RafaelJohn9, thanks for your interest in contributing! However, there's unfortunately nothing to be done here. The `datetime.datetime` constructor already has `seconds` and `microseconds` parameters, so supporting the `float` datatype for the `seconds` parameter would be redundant here. This issue has been marked as "pending" for a week now to indicate that it would be closed unless @hasanelfalakiy got back to us with further feedback about why this feature was needed despite these facts. No further feedback has been provided, so I'll close the issue now.

I'd recommend looking at issues with the "easy" label if you're looking for good issues to contribute to :-)

**Comment by RafaelJohn9** [comment]
thanks @AlexWaygood 👍,  let me go on looking then
