### ISSUE TITLE
cmath.tanh(±0+infj) and tanh(±0+nanj) should return ±0+nanj

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#122637]
# Bug report

### Bug description:

As per C11 [DR#471](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2244.htm#dr_471) (accepted for C17), ``ctanh (0 + i NaN)`` and ``ctanh (0 + i Inf)`` should return ``0 + i NaN`` (with "invalid" exception in the second case).  Currently, real part is nan.

This has corresponding implications for ``ctan(z)``, as its errors and special cases are handled as if the operation is implemented by ``-i*ctanh(i*z)``.

See glibc patch: https://sourceware.org/git/?p=glibc.git;a=commitdiff;h=d15e83c5f5231d971472b5ffc9219d54056ca0f1

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-122638

**Comment by skirpichev** [comment]
PR is ready for review: https://github.com/python/cpython/pull/122638

See also https://github.com/python/cpython/issues/121889

**Comment by mdickinson** [comment]
Closed in #122638, with thanks to @skirpichev. As with #121889, I don't think this is behaviour that should be changed in a bugfix release, so it's not a candidate for backport.

**Comment by skirpichev** [comment]
Great.  Now glibc's libm pass cmath_testcases.txt.

One minor note, now we have slightly misleading comment:
https://github.com/python/cpython/blob/e6fad7a0e3d824f4a3c9cd71a48208880606d705/Modules/cmathmodule.c#L157-L158
This (and fix for https://github.com/python/cpython/issues/121889) is available in C17, not C11.  Though, as you can see, glibc turns this on unconditionally.

Probably, we should adjust comment.

PS: And now this really closed.
