### ISSUE TITLE
Defect: collections.abc.Mapping (etc) inconsistently don't support virtual subclassing

### ISSUE THREAD

**Issue by JWCS** [python/cpython#122618]
https://github.com/python/cpython/blob/498376d7a7d6f704f22a2c963130cc15c17e7a6f/Lib/_collections_abc.py#L791

Relevant SO issue that still reflects this: https://stackoverflow.com/q/64503419/
``` python
class dictroproxy:
    def __init__(self, d): 
        self._d = d 
    def __getitem__(self, key):
        return self._d.__getitem__(key)
    def __contains__(self, key):
        return self._d.__contains__(key)
    def __len__(self):
        return self._d.__len__()
    def __iter__(self):
        return self._d.__iter__()
    def __eq__(self, other):
        if isinstance(other, dictroproxy):
            other = other._d
        return self._d.__eq__(other)
    def __ne__(self, other):
        return not self.__eq__(other)
    def get(self, key, default=None):
        return self._d.get(key, default)
    def keys(self):
        return self._d.keys()
    def values(self):
        return self._d.values()
    def items(self):
        return self._d.items()

if __name__ == "__main__":
    from collections.abc import Collection, Mapping
    dd = dictroproxy({"a": 1, "b": 2, "c": 3})
    print("Is collection?", isinstance(dd, Collection), issubclass(dictroproxy, Collection)) # True, True
    print("Is mapping?", isinstance(dd, Mapping), issubclass(dictroproxy, Mapping)) # False, False
```
It seems that a class that implements the requirements of Mapping, won't test that it is a Mapping, although it does and will satisfy the requirements and tests for a Collection.
Does this have to do with how Mapping's `__subclasshook__` is inherited from Collection? This seems to be a bug, at least for Mapping, and possibly with any similarly inherited subclasshook definitions?

**Comment by sobolevn** [comment]
I seems that you forgot about `.register` call:

```python
>>> from collections.abc import Mapping
>>> class Some: ...
... 
>>> Mapping.register(Some)
<class '__main__.Some'>
>>> isinstance(Some(), Mapping)
True
```

**Comment by JWCS** [comment]
No, that is intentional: the virtual subclasses work for other collections.abc classes, such as the aforementioned Collection, without registration, but they do not for Mapping. Is Mapping supposed to be an exception to the implemented behavior of other ABCs?

**Comment by dolfinus** [comment]
https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes
Footnote [1]

**Comment by sobolevn** [comment]
Yes, they are a bit different. This module is quite complex :(
I am going to close this, since everything is working as it is said in the docs.

Please, feel free to create a new issue if you have some ideas about how docs can be improved for this case!

**Comment by JWCS** [comment]
Ah, so it's not a bug, but a documented defect. Is there a rationale behind not extending the subclasshooks for these types? This seems like an arbitrarily self-inflicted discrepancy in the abc's.

**Comment by sobolevn** [comment]
My guess would be that `Mapping` is an old and widely used abstraction. Changing `isinstance` result for it would be a breaking change.

**Comment by JWCS** [comment]
The problem, and defect, is that would not be a breaking change, but a removal of a false negative, in a context wherein that is a useless result. 
The action response for an `issubclass(mappingClass, Mapping) == False`, is to further test manually that it does indeed support that protocol, and was not a false negative. If it is a true negative, nothing changes, nothing breaks. There is no current positive case, except for explicit subclassing or registration. There is no false positive case, so long as the test correctly checks sufficient method implementation. This is the case for half of the ABCs (views, mappings, sets, and sequences), apparently, which seems inconsistently useless for testing interface correctness at runtime, without forcing either patching the ABCs (ew), or re-implementing the checks that ought to be in subclasshooks.

**Comment by rhettinger** [comment]
>  Is there a rationale behind not extending the subclasshooks for these types? 

Yes, there is a reason and it is explained in the docs:

> Some simple interfaces are directly recognizable by the presence of the required methods (unless those methods have been set to `None`.
> ...
> Complex interfaces do not support this last technique because an interface is more than just the presence of method names. Interfaces specify semantics and relationships between methods that cannot be inferred solely from the presence of specific method names. For example, knowing that a class supplies `__getitem__`, `__len__`, and `__iter__` is insufficient for distinguishing a *Sequence* from a *Mapping*. 

Only the "one-trick ponies" allow us to infer semantics from the presence of a method.  Richer interfaces allow multiple distinct behaviors.

> This seems like an arbitrarily self-inflicted discrepancy in the abc's.

This isn't a discrepancy. It is just a fact of life.

**Comment by JWCS** [comment]
One last argument or consideration: if I'm understanding correctly, the current implementation (or lack thereof) is because the semantic intent of a class is not inferable from its minimal abstract method requirements (by that, no inferable difference between Sequence and Mapping, despite differing semantic intentions). In practice, however, an interface expecting a Mapping (etc) expects the full Mapping API, which includes the mixin methods. By this more useful and stricter definition, which all standard containers relevantly implement, the only ambiguous ABCs are the ItemsView and KeysView (since the Sequence type of ByteString is, well, a unique subtype) (and with the minimum requirement of ItemsView to contain tuples, they do have a one sided point of difference yet). 
All this to say, that while a class may implement multiple semantics, and therefore blur its semantic intention across several categories, from the perspective of testing it for fulfilling an interface requirement of said semantic, all the ABCs that don't offer a subclasshooks test against the full definition require either false positives, or 3rd party re-implementing the subclasshooks, since there is no native alternative means of testing.
