### ISSUE TITLE
invidual asyncio.Futures for async callbacks that may be cpu-bond.

### ISSUE THREAD

**Issue by nanoric** [python/cpython#122690]
# Feature or enhancement

### Proposal:

When we call cpu-bond operation in callback registed by Future.add_done_callback() 
 to a Future created by asyncio.run_coroutine_threadsafe(), asyncio's loop will be blocked by that cpu-bond operation.

See this code: print_every_1s() can't print every 1s because loop is blocked by get_md5(), which is a non-async callback.
```python
import asyncio
import time
from threading import Thread


async def print_every_1s():
    while True:
        print("hello!")
        await asyncio.sleep(1)


def get_md5():
    time.sleep(5)
    print("md5: 1234")


async def my_task():
    pass


def on_done(f):
    # some cpu-bond task, for example, gets md5 of a large file.
    get_md5()  # this blocks the processing loop
    asyncio.get_event_loop().stop()
    pass

if __name__ == "__main__":
    loop = asyncio.get_event_loop()
    th = Thread(target=loop.run_forever)
    th.start()

    f1 = asyncio.run_coroutine_threadsafe(print_every_1s(), loop)
    f1.add_done_callback(on_done)

    f2 = asyncio.run_coroutine_threadsafe(my_task(), loop)
    f2.add_done_callback(on_done)
    # f2.add_done_callback(on_async_compatible_done)

    print("th.join()")
    th.join()
    print("exit()!")
```

To resolve this, in current version(3.12) we must wrap callback into a asyncio-compatible style manually. This code might help(call create_task to a async function):
```python
def on_async_compatible_done(f):
    loop = asyncio.get_event_loop()

    async def async_compatible_callback(f):
        await asyncio.to_thread(get_md5)  # this doesn't blocks the processing loop
        loop.stop()
        pass
    loop.create_task(async_compatible_callback()) 
```

So a better solution might be making the whole callback async, without the need of wrapping:
```python
async def async_done():
    await asyncio.to_thread(get_md5) 
    asyncio.get_event_loop().stop()
```
To make the whole callback async, set_result must be async too.
So maybe a asyncio.Future might be a better choice?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ZeroIntensity** [comment]
I'm having a little trouble understanding the request here, but judging by the code block, I'm guessing this is a misinterpretation of how `asyncio` works. In the reproducer, you need to wrap `get_md5` with `asyncio.to_thread` to prevent it from blocking the event loop.

**Comment by nanoric** [comment]
> you need to wrap `get_md5` with `asyncio.to_thread` to prevent it from blocking the event loop.

I get your point. ```asyncio.to_thread``` is a wrapper of ```run_in_executor```.


----

And back to my suggestion:

My suggestion is to introduce a asyncio version of Future(Or give this Future the ability to switch between normal or async callback): So that we can add a async function as callback.

 > let's say a normal funcion is ``` def func(): ...```, a async function is ``` async def func(): ...```

---

Why a async function as callback is required:

Currently ```asyncio.to_thread``` or ```loop.run_in_executor``` returns a ```concurrent.Future```. This Future supports only adding **normal function** as callback.

This callback will be called in asyncio's even loop.

That is to say a normal function (perhaps a cpu-bond) is called in a async function. **The running of this normal function will block even loop.**

**Comment by nanoric** [comment]
So the future might be like this:
```python
class Future:
  async def set_result(...):
    ...
    await self.invoke_callbacks()
  async def invoke_callbacks():
    for callback_coro_generatorsin callback_coro_generators:
      # use normal function to generate a coroutine at done 
      # instead of generate a coroutine at the time ```add_done_callback()``` is called.
      await callback_coro_generator(); 
  async def add_done_callback(callback: Callable[[], Coroutine]):
    self.callback_coro_generators.append(callback)
```

**Comment by hmc-cs-mdrissi** [comment]
That's by design. Async is about cooperative multitasking where cooperative is key word. You can identity points where functions may stop and be swapped to different coroutine. Expensive cpu function being called in async function is intended to block event loop. Not blocking and swapping inside would be non-cooperative mulitasking and is roughly threading model where threads are allowed to swap at any time.

A key difference between threads vs async is whether a "task" will stop at defined points you control/see (async way) vs at any point (threading way).

**Comment by nanoric** [comment]
> You can identity points where functions may stop and be swapped to different coroutine. 

Yes you are definitely correct. And concurrent.Future stops we from ```identity points where functions may stop and be swapped to different coroutine```. Because a normal function is called inside even loop. And then we lost the ability to control where to switch to other coroutine before that normal function returns. Am I correct?

**Comment by kumaraditya303** [comment]
The callbacks should be non blocking. if you need to perform CPU bound work, consider using a queue etc to offload it to other threads or processes.

**Comment by ZeroIntensity** [comment]
`asyncio` is supposed to be for I/O bound operations (hence the name), I think it would be going the wrong direction to add features to support CPU bound tasks.
