### ISSUE TITLE
argparse: allow to override the type name in `'invalid %(type)s value: %(value)r'` error messages

### ISSUE THREAD

**Issue by calestyo** [python/cpython#122679]
# Feature or enhancement

### Proposal:

Hey.

When doing something like:
```python
class SomeEnumClass(enum.StrEnum):
    foo = enum.auto()
    bar = enum.auto()

parser.add_argument("--enum", type=SomeEnumClass, choices=[e.value  for e in SomeEnumClass])
```
and calls `--enum` with argument `baz`, it will error out with a message like:
```
my.py: error: argument --enum: invalid SomeEnumClass value: 'baz'
```
via:
https://github.com/python/cpython/blob/d0b92dd5ca46a10558857adeb7bb48ecf39fa783/Lib/argparse.py#L2540

For the end user (who sees this message), the `SomeEnumClass`-part may be rather useless, as it may be some arbitrary internal class name, which may or may not be related to the option.

So in principle I think one should be able to configure a string to be printed instead of `SomeEnumClass`.

One candidate would be of course `metavar`, but the problem with that is, that if one sets it, the `--help`-text would be different, too, and not longer print the choices, but rather the `metavar`, which one may not want.

The only way I've found to get that without extending `argparse` is:
```python
class SomeEnumClass(enum.StrEnum):
    foo = enum.auto()
    bar = enum.auto()
SomeEnumClass.__name__ = "blubb"
```
which causes:
```
my.py: error: argument --enum: invalid blubb value: 'baz'
```
to be printed,... but I guess is rather not really well defined, or is it?

Cheers,
Chris.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126939
* gh-127148
* gh-127149

**Comment by serhiy-storchaka** [comment]
You can register the type and specify it by name.
```py
parser.register('type', 'blubb', SomeEnumClass)
parser.add_argument("--enum", type='blubb', choices=[e.value  for e in SomeEnumClass])
```

**Comment by calestyo** [comment]
Nice... that should be added to the `argparse` documentation.

**Comment by calestyo** [comment]
@savannahostrowski thx :-)
