### ISSUE TITLE
The multiplication time of the "@" operation matrix is three times that of using the “numpy.dot”

### ISSUE THREAD

**Issue by FmingC** [python/cpython#122766]
import numpy as np
    import time
    
    x= np.random.randint(0, 10, size=(1000, 1000))
    y= np.random.randint(0, 10, size=(1000, 1000))
    # numpy.dot
    start_time = time.time()
    for _ in range(10):
        result=np.dot(x,y)
    end_time = time.time()
    print(end_time-start_time) #5.5381951332092285s
    
    # @
    start_time = time.time()
    for _ in range(10):
        result=x@y
    end_time = time.time()
    print(end_time-start_time) #16.594331979751587s

**Comment by JelleZijlstra** [comment]
CPython doesn't provide an implementation of the `@` operator; please report this issue to numpy instead.

For what it's worth, I couldn't reproduce this using numpy 2.0.1 and CPython 3.12.2 on Mac. If you report an issue to numpy, please make sure you are using the latest version of numpy and report the versions of numpy and Python and the operating system you are using.
