### ISSUE TITLE
Unexpected behavior overriding side_effect when using mock.patch with autospec=True

### ISSUE THREAD

**Issue by nahuelaguilar93** [python/cpython#122710]
# Bug report

### Bug description:

I want to use a mock.patch decorator over a class with many test with a default side_effect, and then in some specific tests replace that side_effect with some other behavior. When I try to replace the side_effect with an Exception, the mock code raises `TypeError: 'Exception' object is not iterable`. 

**Notice that this only happens when using `autospec=True` in the decorator.** When removed, or replaced with `spec=my_original_function`, everything works as expected.

Here is how to reproduce the issue.

```python
from unittest import TestCase
from mock import patch


def my_original_function():
    return 'my_original_function'


def my_default_side_effect():
    return 'my_default_side_effect'



@patch('tests.my_test.my_original_function', side_effect=my_default_side_effect, autospec=True)
class DebugTest(TestCase):
    def test_default_side_effect_works(self, my_patch):  # This works
        self.assertEqual(my_patch(), 'my_default_side_effect')

    def test_default_side_effect_can_be_replaced_with_new_function(self, my_patch):  # This works
        my_patch.side_effect = lambda: 'some_other_side_effect'
        self.assertEqual(my_patch(), 'some_other_side_effect')

    def test_default_side_effect_can_be_replaced_with_new_list(self, my_patch):  # This works
        my_patch.side_effect = ['other_side_effect_1', 'other_side_effect_2']
        self.assertEqual(my_patch(), 'other_side_effect_1')
        self.assertEqual(my_patch(), 'other_side_effect_2')

    def test_default_side_effect_can_be_replaced_with_new_exception(self, my_patch):  # This fails
        my_patch.side_effect = Exception('exception_side_effect')
        with self.assertRaisesRegex(Exception, 'exception_side_effect'):
            my_patch()
            # AssertionError: "exception_side_effect" does not match "'Exception' object is not iterable"
```

### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by blhsing** [comment]
Not reproducible with Python 3.8.

It appears that you're importing a third-party `mock` though. Can you retry your code after changing `from mock import patch` to `from unittest.mock import patch`?

**Comment by nahuelaguilar93** [comment]
You are right, I was mistakenly using an older version of the library. Replacing it with unittest.mock fixed it. Thank you!
