### ISSUE TITLE
Asyncio socket-level methods do not support SSLSocket

### ISSUE THREAD

**Issue by NoahStapp** [python/cpython#122706]
Attempting to use a `SSLSocket` with the`asyncio.loop.sock_sendall` method and the other socket-level async functions raises the following error:
```python
TypeError: Socket cannot be of type SSLSocket
```

This can be reproduced by the following if `socket` is a `SSLSocket`:
```python
 await asyncio.wait_for(loop.sock_sendall(socket, buf), timeout=timeout) 
```

However, the [ssl-nonblocking](https://docs.python.org/3/library/ssl.html#ssl-nonblocking) section of the docs says the following:

"See also: The [asyncio](https://docs.python.org/3/library/asyncio.html#module-asyncio) module supports [non-blocking SSL sockets](https://docs.python.org/3/library/ssl.html#ssl-nonblocking) and provides a higher level API. It polls for events using the [selectors](https://docs.python.org/3/library/selectors.html#module-selectors) module and handles [SSLWantWriteError](https://docs.python.org/3/library/ssl.html#ssl.SSLWantWriteError), [SSLWantReadError](https://docs.python.org/3/library/ssl.html#ssl.SSLWantReadError) and [BlockingIOError](https://docs.python.org/3/library/exceptions.html#BlockingIOError) exceptions. It runs the SSL handshake asynchronously as well."

Is this section specifically referencing the [streams](https://docs.python.org/3/library/asyncio-stream.html) API as the SSL-compatible asyncio API? The current wording is unclear and suggests to me that non-blocking `SSLSocket` sockets are supported by asyncio, despite the error above. Is there a different section that specifies that `SSLSocket` is not supported by the socket-level asyncio API?

### Linked PRs
* gh-128092
* gh-128093
* gh-128094

**Comment by ZeroIntensity** [comment]
I'm wondering if this isn't a mistake in the docs, but a bug in `_check_ssl_socket` (see [here](https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L203)):

```py
def _check_ssl_socket(sock):
    if ssl is not None and isinstance(sock, ssl.SSLSocket):
        raise TypeError("Socket cannot be of type SSLSocket")
```

It doesn't make much sense to me to raise the error when `ssl` *is not* `None`, it should be vice versa.

**Comment by ShaneHarvey** [comment]
The `ssl is not None` check is to ensure the `ssl` module is available (IIRC cpython can be built without the ssl module):
```python
try:
    import ssl
except ImportError:  # pragma: no cover
    ssl = None
```

**Comment by ZeroIntensity** [comment]
> The `ssl is not None` check is to ensure the `ssl` module is available (IIRC cpython can be built without the ssl module):
> 
> ```python
> try:
>     import ssl
> except ImportError:  # pragma: no cover
>     ssl = None
> ```

Yup, that's why the check is there, but I was wondering wondering if it was a mistake. Anyways, I take that back, this is a docs mistake.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/128092
