### ISSUE TITLE
Counter cannot count in timedelta 

### ISSUE THREAD

**Issue by DirkHoffmann** [python/cpython#122749]
# Bug report

### Bug description:

The `Counter` class of the `collections` package can count in `int` and in `float`. It is also possible to count in `datetime.timedelta` (and probably any other class, which implements addition `+` and subtraction `-` operations).

However, this only works for the first element (or bin) of the `dict()` (which is used as base class for `Counter`):

```python
from datetime import datetime
from collections import Counter
from time import sleep

c = Counter()

ts0 = datetime.now()
sleep(.3)
ts1 = datetime.now()
dt = ts1-ts0

c.update({1:dt})
print(c) # fine, approx. 300000µs
c.update({1:dt})
print(c) # two times: approx. 600000µs
c.update({2:dt}) # TypeError exception!
```

The last statement fails with 
```
Traceback (most recent call last):
  File "*****/timedeltaCounter.py", line 18, in <module>
    c.update({2:dt})
  File "/usr/lib64/python3.10/collections/__init__.py", line 665, in update
    self[elem] = count + self_get(elem, 0)
TypeError: unsupported operand type(s) for +: 'datetime.timedelta' and 'int'
```
(I tested also with python 3.12.)

Thus, counting works in `timedelta` units for the first element. It even allows tu update the same element/bin further on. But it fails, as soon as there is already bin filled in the `Counter`. 

It seems to me that defaulting to 0 (`self_get(elem, 0)`) is  a bad idea here, because it is an instance if `int`. This adds well to `int`, `float` and even `complex`. But the operation `timedelta+0` is not OK.

[This Stackoverflow issue](https://stackoverflow.com/questions/56100786/why-does-adding-two-counters-with-timedelta-values-raise-a-typeerror) should become obsolete with the bugfix.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-122751
* gh-122755

**Comment by rhettinger** [comment]
This is an interesting feature request. I'll mull it over for a while and see if any interesting discussion arises.

My first thought is that this is fundamentally at odds with the central design concept of the `Counter` class as a dictionary that returns `0` for missing keys. Essentially every other capability is built around that concept.

Sidenote: *timedelta* objects can easily be converted to *ints* with `c[event_key] += td.total_seconds()`.

**Comment by DirkHoffmann** [comment]
Thanks for your feedback, @rhettinger.

> My first thought is that this is fundamentally at odds with the central design concept of the `Counter` class as a dictionary that returns `0` for missing keys. Essentially every other capability is built around that concept.

There is no change with respect to that behaviour. (And I hope the tests would have revealed a problem of that kind.) If missing keys are requested, they are still 0. (Compatibility is kept.)

`timedelta` has a flaw as regards the possibility to add a neutral element, intuitively named `0`, but in this case required to be `timedelta(0)`. But improvement of `timedelta` is not the matter here. (Off-topic.)

> Sidenote: _timedelta_ objects can easily be converted to _ints_ with `c[event_key] += td.total_seconds()`.

Yes, but:
* Conversion costs more than referencing. (Efficiency argument.)
* Other classes which implement addition algebra will also be handled correctly by the patch, not only `timedelta`s. (Generalisation argument.)

I am referring to #122751.

**Comment by rhettinger** [comment]
Thank you for the suggestion but after much thought and experimentation, I am going to decline.

For the *timedelta* use case, I recommend a `defaultdict` based solution.  That will give you complete control over the identity element:

```
d = defaultdict(timedelta)
d['prep'] += timedelta(5)
d['deploy'] += timedelta(11)
d['verify'] += timedelta(2)
d['prep'] += timedelta(1)
d['deploy'] += timedelta(3)
d['verify'] += timedelta(2)
```

For the `Counter` class, I think this idea is forcing a square peg into a round hole.

The PR gives this working example:

```
c = Counter()
c.update({1:dt})
c.update({1:dt})
c.update({2:dt})
c.update({2:dt, 3:dt-dt, 42:(dt+dt)/2})
```

There are number of pain points. Here are a few:

* The lookups `c[0]` and `c[1]` now return different and incompatible data types.
* A call to the `subtract()` method fails when keys are missing: `c.subtract({2: dt, 4: dt})`
* The `total()` method fails.
* Basic accumulation operations fail: `c[4] += timedelta(5)`
* Multiset operations like `c - Counter({1: timedelta(5)})` fail even when the keys match

Again, I appreciate the suggestion and creativity but think this unnecessarily takes the `Counter` class onto thin ice for a niche use-case that is easily handled with other techniques.

**Comment by rhettinger** [comment]
A couple of other thoughts:

* This proposal doesn't work well with type annotations.
* Non-scalar addable types such as `tuple` and `str` should not be accumulated with `+`:

```
e = Counter()
e.update({10: 'abc'})
e.update({20: 'def'})
e.update({10: 'ghi'})
e.update({10: 'jkl'})
```

**Comment by DirkHoffmann** [comment]
Thank you for your explanations and the hint with `defaultdict`. (Actually my implementation with `Counter` is working. I just have to avoid the call to `update()` for new elements (to a non-empty `Counter`) and therefore go `if key in c: c.update({key: ts} else: c[key]=ts` in my user code. 

Did you notice all your criticism does _not_ affect the PR directly, but is rather generally valid for the current implementation of `Counter` indeed? My point for the PR was precisely to get rid of the incoherent reaction to 
```
>>> c.update({'a': timedelta(0)}); c.update({'b': timedelta(0)})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/collections/__init__.py", line 685, in update
    self[elem] = count + self_get(elem, 0)
                 ~~~~~~^~~~~~~~~~~~~~~~~~~
TypeError: unsupported operand type(s) for +: 'datetime.timedelta' and 'int'
```
Who would guess from the message that only the second occurence triggered the exception, but the first one had actually been executed?

**Comment by DirkHoffmann** [comment]
After some more thoughts:

* The point regarding `subtract()` is valid. It was an omission and should be patched in the same way as `update()`.
* The `Counter` class was probably not designed with the _intention_ to work with all "addable" classes (i.e. which implement a `+` operation, and as a corollary also `-`). But that is the magic of OO and in particular python: You can get surprising _and_ correct results, if the formal prerequisites are fulfilled. It looks completely obvious to me that `Counter` can be successfully used for all addable classes.
  * Therefore it would be nice, if all existing methods/functions work as equivalently as possible to the standard case. "Adding strings" in python is obviously a concatenation, and although I don't have a good use case in mind, it looks straightforward to me that it "must" work (and also lists, by the way).
  * Obviously, trying to make a total of strings, timestamps and numbers must fail. The `TypeError` is an obvious and easy to understand reaction in such a case.
* Semantically this is not a _Counter_ any more. But that concept was given up at the moment, when it was allowed to count in steps that are different from one or even negative. The name _Scaler_ or _Adder_ might be more appropriate in the general case, which I make out of it. Maybe the implementation of such a generalisation would be the right way to go, making _Counter_ a specialisation of the former with implementation for operations on "countables"?
  * Already allowing `float` and `complex` numbers made the name _Counter_ less appropriate to its actualy function.
* To be absolutely rigorous, the `total()` method should also be patched to work with "non-countables" (but "addables"). As the `sum()` built-in curiously works only for "addables to `int`", the classical `reduce(operator.add, c.values())` is a good substitute (which may only jump in case of a `TypeError` with `sum()`, if that makes a performance issue). Thanks python, which follows also functional paradigms!
  * Maybe a preliminary check of `len(set(map(type,c.values())))==1` could help to make sure that the _Counter_ contains all addable elements.

**Comment by rhettinger** [comment]
I get that you think this is a good idea and likely cannot be persuaded otherwise.  

I hope that you get that I have worked through your proposal , experimented with it, examined the implications, and have concluded that it would be a mistake.

Hopefully, we can both agree that a *defaultdict* is a reasonable starting point for achieving much of what you want to do.

At any rate, the proposal is rejected.  We will have to live with a class that is mostly doing a really good job of meeting the most common needs, most of the time.  That is not a bad outcome.
