### ISSUE TITLE
Is this doc wording about raw bytes literal correct?

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#122701]
Link: https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals

<img width="816" alt="Снимок экрана 2024-08-05 в 21 38 55" src="https://github.com/user-attachments/assets/e77cf7aa-49cf-4208-b253-9d7e1ee2ee48">

> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such strings are called raw strings

I don't think that it is a correct wording. You cannot call `rb''` as a "raw string", it is called "raw bytes". Or "raw bytes literal". Just like the docs docs in the next paragraph: 

> The 'rb' prefix of raw bytes literals has been added as a synonym of 'br'.

I propose to fix this by using this phrase:

> Both string and bytes literals may optionally be prefixed with a letter 'r' or 'R'; such objects are called raw strings and raw bytes respectively.

### Linked PRs
* gh-122702
* gh-122914
* gh-122915

**Comment by terryjreedy** [comment]
I don't think 'raw bytes' is really correct.  It is equivalent to 'raw strs', which also strikes me as wrong.  'Raw' applies to the interpretation of the code literal, not to the resulting Python object..  I believe the sentence in question dates back to 2.6 or 2.7 (git blame would tell).  The second 'string' is more generic than the first, encompassing both text and bytes literals (code strings defining sequences of internal character-like sequences).  Do you have evidence that some people are really confused?  I am not sure how to make the point better.

Side note: we have mostly stripped 2.x references from the doc.  The last sentence says that in the first sentence, 'literals' means (should be) 'literals without a u/U prefix'.
