### ISSUE TITLE
venv activate.csh fails when user prompt contains newline

### ISSUE THREAD

**Issue by brandyn** [python/cpython#122765]
# Bug report

### Bug description:

activate.csh uses "$prompt" in quotes like that, which fails when the user prompt contains a newline (error: unbalanced quotes).

Using $prompt:q or "$prompt:q" solves this with no harm, at least in tcsh (not sure about vanilla csh), at least for activate.  (Deactivate may have similar issue.)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-123751
* gh-124185

**Comment by JacekDuszenko** [comment]
sent a PR with a fix however there is a similar issue with `__VENV_PROMPT__` variable. When you set a custom prompt  e.g. with --prompt='"' the script crashes @  https://github.com/python/cpython/blob/main/Lib/venv/scripts/posix/activate.csh#L22.

It's fixable by extracting the concatenated `__VENV_PROMPT__` and `prompt` to a separate variable and then using it with ":q" on the next line while setting the prompt. 
Can send another PR with a fix if sounds good.
