### ISSUE TITLE
Upgrade bundled pip to 24.2

### ISSUE THREAD

**Issue by pradyunsg** [python/cpython#122744]
# Feature or enhancement

### Proposal:

`ensurepip`'s bundled version of pip gets updated to the current latest 24.2.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

N/A

### Linked PRs
* gh-122745
* gh-122746
* gh-122747
* gh-122776
* gh-122822
* gh-122823

**Comment by hugovk** [comment]
And all merged :)

**Comment by hugovk** [comment]
Maybe we should skip this test when ssl is missing?

cc @sethmlarson

**Comment by encukou** [comment]
We can ignore the message if it's expected; there's code for another warning already: #122776

The question for @sethmlarson or pip maintainers is, will pip stick with this wording?
It seems the user-facing name of the feature is [Using system certificate stores](https://pip.pypa.io/en/stable/topics/https-certificates/#using-system-certificate-stores).
IMO, it's not very clear whether pip falls back to `certifi` in this case (or what `certifi` is, for that matter).
