### ISSUE TITLE
Error handling of `RERAISE` is strange

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#122759]
# Bug report

There's a strange pattern used in `RERAISE` opcode: https://github.com/python/cpython/blob/4767a6e31c0550836b2af45d27e374e721f0c4e6/Python/bytecodes.c#L1174-L1189

Especially these lines: https://github.com/python/cpython/blob/4767a6e31c0550836b2af45d27e374e721f0c4e6/Python/bytecodes.c#L1180-L1187

It looks like the `assert` call is not needed here:
- In debug builds it will always crash, since `PyLong_Check(lasti)` will always be false
- In non-debug builds it will set `SystemError` as it should be (at least, I think so). That's the only line that matches `r'assert\(.*\);\n\s+_PyErr'`

I have a PR ready.

### Linked PRs
* gh-122760

**Comment by hugovk** [comment]
Triage: closing because the linked PR is merged, please re-open if still needed.
