### ISSUE TITLE
macOS installer: unreadable text in dark mode

### ISSUE THREAD

**Issue by hugovk** [python/cpython#122782]
# Bug report

## Steps to reproduce

1. Install the 3.12.5 macOS installer from https://www.python.org/downloads/release/python-3125/

2. Click through to the Read Me:

## Actual result

Some text is white on white background and unreadable:

![image](https://github.com/user-attachments/assets/bfc73c8d-9823-41c6-b6b2-10882be69969)

It's this text in code formatting: "SecTrustEvaluateWithError: symbol not found"

If I highlight the text with my mouse, it is temporarily readable:

![image](https://github.com/user-attachments/assets/fda067f8-afb7-41ab-94d4-cac2d1616abe)

## Expected result

All text is white (or a non-dark colour) on black (or a dark colour).

Looks okay in light mode:

![image](https://github.com/user-attachments/assets/666cce1e-8373-4a7f-9e7c-5adc43c9e5ad)

---

This was added in https://github.com/python/cpython/pull/122774, the added text is:

```rtf
\f4\fs23\fsmilli11900 \cf2 \cb3 \expnd0\expndtw0\kerning0
SecTrustEvaluateWithError: symbol not found. 
\f0\fs24 \cf0 \cb1 \kerning1\expnd0\expndtw0
```

See also previous issue: https://github.com/python/cpython/issues/103290.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by ned-deily** [comment]
Burned by rtf and the macOS Installer.app again! Thanks for the report. The ReadMe file included with the 3.12.6 macOS installer has been edited (01748b75de54c7ec70e345f704c886457f113fc8) and no longer has this problem.
