### ISSUE TITLE
Documentation for sets: Operator symbols do not map to the correct method names for custom implementations of set

### ISSUE THREAD

**Issue by dakra137** [python/cpython#122820]
ref: [https://docs.python.org/3.12/library/stdtypes.html#set] (https://docs.python.org/3.12/library/stdtypes.html#set) 

I created my own Customset class which implements almost all the methods of python sets. 

When I use instances of this Customset, many of the set operators fail. They fail with something similar to:
`TypeError: unsupported operand type(s) for -: 'Customset' and Customset'`   
or
`TypeError: '<=' not supported between instances of 'Customset' and Customset'`   
The operators that fail include: -, -=, &, &=, <, <=, >, >=, ^, ^=, |, |=, ==

I expected the operators to map to the methods names in the documentation on this page.   
Instead they map to usual magic dundermethod mappings from those operators to methods:

`-  ==> __sub__`  
`-= ==> __isub__`  
`&  ==> __and__`    
`&= ==> __iand__`  
`<  ==> __lt__`   
`<= ==> __le__`  
`>  ==> __gt__`  
`>= ==> __ge__`  
`^  ==> __xor__`  
`^= ==> __ixor__`  
`|  ==> __or__`  
`|= ==> __ior__`  
`== ==> __eq__`  

Recommendation:  
Include the dundermethod name to use for each operator when creating a custom implementation of set.
At the minimum provide a link to the page where the dundermethods for these operators are given.

**Comment by terryjreedy** [comment]
The dunder methods for operators are the same for *all* objects and are documented  [here](https://docs.python.org/3.12/reference/datamodel.html#special-method-names).  This doc should *not* be repeated for all objects or for any of them.  https://discuss.python.org/c/help/7 is a good place to ask about puzzling Python behavior.
