### ISSUE TITLE
Add code example to collections.UserString

### ISSUE THREAD

**Issue by feimvnc** [python/cpython#122892]
# Documentation

Link: https://docs.python.org/3.14/library/collections.html#userstring-objects

There is no code example in the section of UserString object, it will be helpful to have it and show how data attribute is used.  
I have few lines of code below, is it a good idea to add to it?  

#
>>> from collections import UserString
>>> class MyString(UserString):
...     def reverse_number(self):
...         return self.data[::-1]
... 
>>> my_string = MyString(123)
>>> print(my_string.reverse_number())
321
#

This is my first issue, please comment and guide, happy to submit a PR if someone think this is useful.

**Comment by rhettinger** [comment]
> I have few lines of code below, is it a good idea to add to it?

My preference is to not highlight this class. It has *very* few use cases and most folks would be better off by subclassing *str*.   Really, this only time this is needed is in an exotic case where you need to subclass from *str* AND some other incompatible type at the time AND don't care about the reduced performance.

**Comment by picnixz** [comment]
I knew about the existence of this class but never had to use it. I would also not try to sell this class by giving artificial examples.

**Comment by rhettinger** [comment]
Thanks for understanding.
