### ISSUE TITLE
Datetime nanosecond support

### ISSUE THREAD

**Issue by user529481** [python/cpython#122899]
# Feature or enhancement

### Proposal:

I'd like to request nanosecond support for datetime module. I've noticed a few packages truncate nanosecond data into microseconds, even though the data was originally stored in nanoseconds. This causes problems when serializing and deserializing data, due to the unexpected conversion when going from the package's representation of datetime to Python's representation.

Current work around include using Numpy's datetime64 object, Pandas' Timestamp class, and representing the time in Unix timestamps. The former two requires pulling in large dependencies, and may not be the first choice among developers, and the latter is workable but clunkier than having a direct nanosecond timescale format. 

I suspect a sizeable fraction of those who work with nanosecond data have their own workarounds. It would be a big time saver for many of us if datetime just worked out of the box for nanosecond scale data. 

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
> It looks like it has already been requested: #59648

You're right. Let's continue discussion there. I'm closing this issue as a duplicate.
