### ISSUE TITLE
Allow "-m json" instead of "-m json.tool"

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#122873]
# Feature or enhancement

### Proposal:

This is a feature proposal for allowing `python3 -m json` to work in addition to `python -m json.tool` and softly deprecating the use of `python3 -m json.tool`.

I [made a branch](https://github.com/python/cpython/compare/main...treyhunner:cpython:json-script2) to see what these changes might look like.

[Here is a separate branch](https://github.com/python/cpython/compare/main...treyhunner:cpython:json-script) which issues a `DeprecationWarning` .
However, since `json.tool` will continue working that warning may cause more hassle for end users than is worthwhile.

I think the no-warning approach may be more sensible.

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

[Discussion in Ideas discuss thread](https://discuss.python.org/t/allow-python-m-json-to-work-in-addition-to-python-m-json-tool/59835)

### Linked PRs
* gh-122884

**Comment by ncoghlan** [comment]
The "No warning" branch looks good to me (it would just need docs and News for me to approve a PR)

**Comment by Eclips4** [comment]
Hi @hugovk! Just a quick note:  `type-feature` label doesn't  require a version label: https://devguide.python.org/triage/labels/#type-labels

**Comment by hugovk** [comment]
> The "No warning" branch looks good to me (it would just need docs and News for me to approve a PR)


Agreed.

And change this in `Lib/json/tool.py`?

```diff
 def main():
-    prog = 'python -m json.tool'
+    prog = 'python -m json'
```

@treyhunner Would you like to put together a PR?

**Comment by treyhunner** [comment]
I will put together a PR shortly. 👍

**Comment by rhettinger** [comment]
+1 from me

**Comment by hugovk** [comment]
PR is here: https://github.com/python/cpython/pull/122884
