### ISSUE TITLE
Dead code in ceval_macros.h and ceval_gil.c

### ISSUE THREAD

**Issue by colesbury** [python/cpython#122860]
The `_Py_atomic_load_relaxed_int32` macro is no longer used:

https://github.com/python/cpython/blob/d3239976a8e66ae3e2f4314a6889d79cdc9a9625/Python/ceval_macros.h#L378-L383

https://github.com/python/cpython/blob/d3239976a8e66ae3e2f4314a6889d79cdc9a9625/Python/ceval_gil.c#L52-L57

### Linked PRs
* gh-122861

**Comment by neonene** [comment]
They were added by #32387.  I can confirm that the new `_Py_atomic_*` functions are all inlined by MSVC (Release, PGO).
