### ISSUE TITLE
SQLite Explain Statement Requiring Parameters Unnecessarily

### ISSUE THREAD

**Issue by Derothin** [python/cpython#122828]
# Bug report

### Bug description:

Attempting to execute a SQL statement that uses EXPLAIN which contains parameters (positional or named) without providing values for those parameters causes an error. However, this is not correct. SQLite does not need the parameters in this case as the statement is not run, only prepared and used to return the generated bytecode.

Example:
```
import sqlite3
database = sqlite3.connect(':memory:')
database.execute("EXPLAIN SELECT ?")

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 1, and there are 0 supplied.
```

If needed, you can verify that parameters are not required by trying the same statement in the SQLite3 CLI tool, or this trivial C program that just prints bytecode information.
```
#include <sqlite3.h>
#include <stdio.h>

int main(void) {

    sqlite3 *db;
    sqlite3_stmt *stmt;

    sqlite3_open(":memory:", &db);
    sqlite3_prepare_v2(db, "EXPLAIN SELECT ?", -1, &stmt, 0);

    while (sqlite3_step(stmt) != SQLITE_DONE) {
        int i;
        int num_cols = sqlite3_column_count(stmt);
        
        for (i = 0; i < num_cols; i++)
        {
            switch (sqlite3_column_type(stmt, i))
            {
            case (SQLITE3_TEXT):
                printf("%s, ", sqlite3_column_text(stmt, i));
                break;
            case (SQLITE_INTEGER):
                printf("%d, ", sqlite3_column_int(stmt, i));
                break;
            default:
                break;
            }
        }
        printf("\n");
    }

    sqlite3_finalize(stmt);
    sqlite3_close(db);
}
```

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by erlend-aasland** [comment]
Insert this after preparing your statement:

```c
printf("num params: %d\n", sqlite3_bind_parameter_count(stmt));
```

It will print: `num params: 1`.

In `Modules/_sqlite/cursor.c`, we call `sqlite3_bind_parameter_count()` in `bind_parameters()`, which is called every time we execute a statement (`_pysqlite_query_execute()`).

EXPLAIN (and EXPLAIN QUERY PLAN) operates at run-time, not at prepare-time, so if we are to add special handling for these, we'd have to manually detect them (`strncmp`) in `cursor.c`. My gut feeling is that we should not add special handling for debug statements like this.

**Comment by erlend-aasland** [comment]
Quoting [the SQLite docs](https://www.sqlite.org/lang_explain.html):

> The output from EXPLAIN and EXPLAIN QUERY PLAN is intended for interactive analysis and troubleshooting only. The details of the output format are subject to change from one release of SQLite to the next. Applications should not use EXPLAIN or EXPLAIN QUERY PLAN since their exact behavior is variable and only partially documented.

**Comment by erlend-aasland** [comment]
The above quote confirms my gut feeling; I don't think we should add special handling for EXPLAIN in the `sqlite3` module. I prefer to keep status quo.

**Comment by Derothin** [comment]
A little unfortunate for me that you think that, but more than reasonable.

What do you think of just having a Python function to emulate sqlite3_bind_parameter_count? Something that would return the number of positional parameters required or a list of parameter names. In my head I'm picturing something like the below, but even typing it out it felt kind of clunky.

```
sql = f"EXPLAIN {original_sql}"
params = sqlite3.get_parameters(sql)
if isinstance(params, list):
    database.execute(sql, {name: None for name in params})
else:
    database.execute(sql, [None]*n_param)
```

**Comment by erlend-aasland** [comment]
> What do you think of just having a Python function to emulate `sqlite3_bind_parameter_count`?

I don't think such an API belongs in the `sqlite3` module, since `sqlite3` tries to provide a PEP-249 compliant API; it does _not_ try to be a shim over the SQLite C API. Luckily, for this, we already have the magnificent `apsw` library, which does provide this kind of API:

https://rogerbinns.github.io/apsw/cursor.html#apsw.Cursor.bindings_count

**Comment by erlend-aasland** [comment]
For the OP issue, I'd instead recommend doing `EXPLAIN` experiments and query optimising using the SQLite CLI; it is better suited for query debugging.
