### ISSUE TITLE
Malformed payload can lead to infinite loops in zipfile.Path

### ISSUE THREAD

**Issue by jaraco** [python/cpython#122905]
As reported in https://github.com/jaraco/zipp/issues/119, malformed paths in a zipfile can lead to undesirable behaviors (infinite loops) when traversed using zipfile.Path.

This issue tracks porting that fix to CPython.

### Linked PRs
* gh-122906
* gh-122922
* gh-122923
* gh-122925
* gh-123160
* gh-123161
* gh-123162

**Comment by obfusk** [comment]
I provided some additional analysis here: https://www.openwall.com/lists/oss-security/2024/08/22/4

Also, the CVE and security announcement mistakenly say this affects methods of `zipfile.ZipFile` instead of `zipfile.Path`.
