### ISSUE TITLE
Request for documentation on building blockchains with Python

### ISSUE THREAD

**Issue by Ndhlovu1** [python/cpython#122987]
# Documentation

Python is a pretty great a language and it is overally great for building numerous types of apps.

I think that if Python could be used to build or easily interact with the Ethereum blockchain it would greatly boost python's user base.

It already has numerous easy to use frameworks such as django, which allow python to interact with numerous databases and easily produce APIs hence, if Python could also have easy in-built documentation on using django to work with ethereum would garner soo much more support from the blockchain enthusiasts.

**Comment by AA-Turner** [comment]
This won't be something that CPython does. There will most likely be numerous third-parties with blog posts or tutorials, though.

A
