### ISSUE TITLE
Global Access Failure in Nested Threaded Function

### ISSUE THREAD

**Issue by moyanj** [python/cpython#122976]
# Bug report

### Bug description:

Abstract：Nested Function Cannot Access Global Variable from Parent Function in Threaded Context
When I run this code:

```python
import threading

def b():
    frp_e = ''
    def a():
        global frp_e
        frp_e = frp_e + '666'
            
    threading.Thread(target=a).start()
            
threading.Thread(target=b).start()
```

It happened this error:

```
Exception in thread Thread-2 (a):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/media/sd/t.py", line 16, in a
    frp_e = frp_e + '666'
NameError: name 'frp_e' is not defined
```

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by picnixz** [comment]
This is not a global variable but a `nonlocal` variable here (`frp_e` is local to `b`). Global variables would have been in the global scope (i.e. outside of `b`).

Closing as a `non-issue`.
