### ISSUE TITLE
The GIL must be held to increment a reference count on debug builds

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#122904]
# Bug report

### Bug description:

When `Py_DEBUG` is defined (and incidentally, `Py_REF_DEBUG`), incrementing a reference count requires the GIL, but not on release builds.

For example:

```c
static PyObject *
func(PyObject *self, PyObject *arg) // METH_O
{
    Py_BEGIN_ALLOW_THREADS;
    Py_INCREF(arg); // Segfaults only on debug builds
    Py_END_ALLOW_THREADS;
    Py_RETURN_NONE;
}
```

C API users could assume that `Py_INCREF` is safe to use when the GIL is released (which it is, on release builds), making it impossible to use those extensions with debugging enabled.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
Py_INCREF is not safe when you do not own the GIL due to the risk of concurrent refcount updates (see also https://docs.python.org/3/c-api/init.html#thread-state-and-the-global-interpreter-lock).

**Comment by ZeroIntensity** [comment]
Ah, good to know. Would it be worth clarifying on the documentation for `Py_INCREF`?

**Comment by ronaldoussoren** [comment]
I don't think that is needed, the documentation I linked to clearly states that any API call must be done while holding the GIL (other than APIs related to GIL management).

**Comment by ZeroIntensity** [comment]
Right, but as I mentioned, users can and will mistake `Py_INCREF` for being allowed since it does not cause a memory error (under normal circumstances). Thanks for clarifying, anyway!
