### ISSUE TITLE
Extend deprecation warning period for bitwise inversion on ``bool`` type

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#122982]
# Feature or enhancement

### Proposal:

Since Python 3.12, attempting to use bitwise inversion on a bool type is raises a ``DeprecationWarning``:
```python
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> a = True
>>> ~a
<stdin>:1: DeprecationWarning: Bitwise inversion '~' on bool is deprecated. This returns the bitwise inversion of the underlying int object and is usually not what you expect from negating a bool. Use the 'not' operator for boolean negation or ~int(x) if you really want the bitwise inversion of the underlying int.
-2
>>>
```

I have a PR ready.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-122983
* gh-123306
* gh-123316
* gh-123317

**Comment by encukou** [comment]
It's deprecated, but why should it be removed now?

**Comment by encukou** [comment]
Oh, I see the plan to remove it in 3.14 is in the docs, but not all the places it should be :(

**Comment by hauntsaninja** [comment]
I think the removal is kind of breaking (see comments on https://github.com/python/cpython/pull/103487), I'd vote for extending the deprecation period beyond the 2 year minimum

**Comment by Eclips4** [comment]
> I think the removal might affect a number of users (e.g. see comments on #103487); I'd vote for extending the deprecation period beyond the 2 year minimum

I've read these comments and I agree with your opinion. I'll close the PR and open a new one to properly document the deprecation.

**Comment by serhiy-storchaka** [comment]
It is not necessary to close the PR. It can simply be postponed for few years.

**Comment by picnixz** [comment]
I've changed the title of the issue to highlight the fact that we are not removing it for now. We will change it later when we'll eventually remove it (just for tracking purposes)

**Comment by nineteendo** [comment]
Can't this be closed now?

**Comment by picnixz** [comment]
Mmmh. Yes. We'll open another issue if we want to really deprecate the behaviour.
