### ISSUE TITLE
3.13 Regression: `inspect.getsource()` returns incorrect source code

### ISSUE THREAD

**Issue by mhils** [python/cpython#122981]
# Bug report

### Bug description:

In Python 3.13rc1, `inspect.getsource()` sometimes returns a "random" line for some objects. 
For example, here's [`ssl.AlertDescription`](https://github.com/python/cpython/blob/v3.13.0rc1/Lib/ssl.py#L133-L136):

```shell
$ docker run --rm python:3.13-rc python -c "import inspect, ssl; print(inspect.getsource(ssl.AlertDescription))"
        super().shutdown(how)
```
This line is likely https://github.com/python/cpython/blob/v3.13.0rc1/Lib/ssl.py#L1334.

In contrast, on 3.12 and below, this raises an OSError (not ideal but also not wrong):

```shell
$ docker run --rm python:3.12-rc python -c "import inspect, ssl; print(inspect.getsource(ssl.AlertDescription))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.12/inspect.py", line 1285, in getsource
    lines, lnum = getsourcelines(object)
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 1267, in getsourcelines
    lines, lnum = findsource(object)
                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/inspect.py", line 1112, in findsource
    raise OSError('could not find class definition')
OSError: could not find class definition
```

I'm not sure why this is happening, but it also affects [pytest.PytestAssertRewriteWarning](https://github.com/pytest-dev/pytest/blob/38ad84bafd18d15ceff1960d636c693560337844/src/_pytest/warning_types.py#L20) and [pluggy.PluggyTeardownRaisedWarning](https://github.com/pytest-dev/pluggy/blob/5c16e15a963d5e66f37d05b1ccfb90adf71e8e0f/src/pluggy/_warnings.py#L11), which both extend custom classes that override `__module__`.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-123001
* gh-123182

**Comment by devdanzin** [comment]
Bisected to 153b3f75, introduced by #118475.

It happens because class `ssl.AlertDescription` now has a `__firstlineno__` attribute, and that is erroneously interpreted as a line number in ssl.py. It shares the same line number (1334) with other classes, like `SSLErrorNumber`, created via `IntEnum._convert_`. This line number corresponds to `IntEnum`'s line number in enum.py instead.

So ISTM the issue is that the construction of `__firstlineno__` for these classes is capturing the line number of the class generator definition instead of the class creation site.

cc @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Thank you for your report @mhils. I agree with @devdanzin analysis. `__firstlineno__` is not set for these enum classes, but inherited from the base class. There is a test for generated class, but it does not have a base class that has `__firstlineno__`.

#123001 should fix this.

**Comment by mhils** [comment]
Awesome - thank you two for getting to the bottom of this with lightning speed! ⚡🍰 😃

**Comment by mhils** [comment]
Thank you two again! I can confirm that the issue is fixed now for `ssl.AlertDescription` with 3.13rc2. Unfortunately our smoke tests still show a very similar error in this case here:

```shell
$ docker run --rm python:3.13.0rc2 bash -c \
    'pip install pluggy; python -c "import inspect, pluggy; print(inspect.getsource(pluggy.PluggyTeardownRaisedWarning))"'
[...]
    "PluginManager",
```
```shell
docker run --rm python:3.12 bash -c \
    'pip install pluggy; python -c "import inspect, pluggy; print(inspect.getsource(pluggy.PluggyTeardownRaisedWarning))"'
[...]
OSError: could not find class definition
```
(https://github.com/mitmproxy/pdoc/actions/runs/10772390037/job/29935976461?pr=730)

Would you like me to file a new issue, or do we keep it here? 

Thanks! 😃
