### ISSUE TITLE
"test" GitHub Action workflow cannot be run manually

### ISSUE THREAD

**Issue by nohlson** [python/cpython#122965]
# Bug report

### Bug description:

With the inclusion of `build_msi` into the `Change detection` job of `test` workflow in #121778 it isn't possible to **manually** run the workflow anymore:

![Screenshot 2024-08-13 at 12 52 04 AM](https://github.com/user-attachments/assets/c4503f9e-d06f-43ab-8149-f906fbdc2a3e)

This seems to be because the `Ana06/get-changed-files` action doesn't support `workflow_dispatch`:

![Screenshot 2024-08-13 at 12 57 34 AM](https://github.com/user-attachments/assets/df382d54-cadc-4959-97e2-e287cab173c6)

This type of error apparently does block CI.

I think the fix would be as simple as adding a condition that `github.event_name == 'pull_request'` to the `Get a list of the MSI installer-related files` step of the `Compute changed files` job.

Attn: @webknjaz 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-122966
* gh-123008
* gh-123009

**Comment by picnixz** [comment]
Closing as this was completed in https://github.com/python/cpython/pull/122966.
