### ISSUE TITLE
Memory Handling Issue with ctypes on Jetson AGX Xavier Developer Kit (ARM) Causing Inconsistent Data in Python Structures

### ISSUE THREAD

**Issue by TheBlind11** [python/cpython#122980]
# Bug report

### Bug description:

We are trying to have two microservices, a sender and a receiver, that communicate in a docker env. We tested the env in two vms with ubuntu 20.04 and 22.04 (on x86) and it works without any doubt, the point is that we need the env working on our Jetson AGX Xavier Developer Kit, it's not working on it and we really don't know why: same docker images, same python versions, same docker version, but not working.

This is our sender.
```
import ctypes
import numpy as np
import dvde_api_wrapper as dvde

FRAME_ROWS = 720
FRAME_COLS = 1280
COLOR_CHANNELS = 3

args_t = dvde.dvde_api__args_t()

class DataToCV(ctypes.Structure):
    _pack_ = 1
    _fields_ = [
        ("depth_image", ctypes.c_uint16 * (FRAME_ROWS * FRAME_COLS)),
        ("color_image", ctypes.c_ubyte * (FRAME_ROWS * FRAME_COLS * COLOR_CHANNELS))
    ] 

def sendDataToCV(data):
    args_t.subject = ctypes.c_char_p(b"usb-depth-camera" + b'\0')
    args_t.size = ctypes.sizeof(data)
    args_t.data = ctypes.cast(ctypes.pointer(data), ctypes.c_void_p)
    args_t.retcode = dvde.dvde_api__retcode_t.DVDE_API__NO_ERROR
    
    dvde.dvde_api.dvde_api__produce(ctypes.byref(args_t))

def main() -> None:

    data = DataToCV()

    try:
        while True:
            
            # Ottengo i frame dalla camera
            depth_frame = np.random.randint(0, 65536, size=(FRAME_ROWS, FRAME_COLS), dtype=np.uint16)
            color_frame = np.random.randint(0, 256, size=(FRAME_ROWS, FRAME_COLS, COLOR_CHANNELS), dtype=np.uint8)
            
            # Copy color frame to ctypes structure
            ctypes.memmove(data.depth_image, depth_frame.ctypes.data, depth_frame.nbytes)
            ctypes.memmove(data.color_image, color_frame.ctypes.data, color_frame.nbytes)

            # print("Depth sent:", list(data.depth_image)[:300])  # Print the first 100 elements for inspection
            # print("Color sent:", list(data.color_image)[:300])  # Print the first 100 elements for inspection
            
            sendDataToCV(data)

    except KeyboardInterrupt:
        print("Chiudo")

if __name__ == '__main__':

    # Esecuzione del programma
    main()
```

This is our receiver:
```
import ctypes
import numpy as np
import dvde_api_wrapper as dvde

FRAME_ROWS = 720
FRAME_COLS = 1280
COLOR_CHANNELS = 3

args_t = dvde.dvde_api__args_t()

class DataFromDepthCameraHal(ctypes.Structure):
	"""Struttura per i dati provenienti dalla camera di profondità"""
	_pack_ = 1
	_fields_ = [
		("depth_image", ctypes.c_uint16 * (FRAME_ROWS * FRAME_COLS)),
		("color_image", ctypes.c_ubyte * (FRAME_ROWS * FRAME_COLS * COLOR_CHANNELS))
    ]

def getFrames(frames):
	args_t.subject = ctypes.c_char_p(b"usb-depth-camera" + b'\0') # check queue name (need to change)
	args_t.size = ctypes.sizeof(frames)
	args_t.data = ctypes.cast(ctypes.pointer(frames), ctypes.c_void_p)
	args_t.retcode = dvde.dvde_api__retcode_t.DVDE_API__NO_ERROR
	
	dvde.dvde_api.dvde_api__consume(ctypes.byref(args_t))

def main() -> None:
	frames = DataFromDepthCameraHal()

	try:
		while True:
			# Ottengo i frame dalla camera
			getFrames(frames)

			# Convert ctypes arrays to NumPy arrays
			depth_image = np.frombuffer(frames.depth_image, dtype=np.uint16).reshape(FRAME_ROWS, FRAME_COLS)
			color_image = np.frombuffer(frames.color_image, dtype=np.uint8).reshape(FRAME_ROWS, FRAME_COLS, COLOR_CHANNELS)

			print("Depth received:", depth_image[:300])
			print("Color received:", color_image[:300])

	except KeyboardInterrupt:
		print("Programma interrotto")
		
if __name__ == '__main__':

	# Esecuzione del programma
	main()
```

The problem on our Jetson is that the second field of the ctypes structure in the receiver is full of zeros, I also tried to change the order putting color before of depth but the result on the second field is the same. This happens only on Jetson, not on the vms, we really don't know how to fix it. I also tried to add padding between the two fields of the structure, nothing changed.

We really need help, because we are going to an FSAE competition with our driverless car, this would compromise our event..

### CPython versions tested on:

3.8, 3.9

### Operating systems tested on:

Linux, Other

**Comment by ZeroIntensity** [comment]
At a glance, I'm (speculatively) thinking that this is a limitation on the hardware or on the system, since you're asking for nearly 3MB from the allocator. You could confirm this with:

```py
import ctypes

dll = ctypes.CDLL("libc.so.6")
dll.malloc.argtypes = ctypes.c_ssize_t,
dll.malloc.restype = ctypes.c_void_p
print(dll.malloc(2764800))  # Number of bytes that you're allocating
```

**Comment by TheBlind11** [comment]
> At a glance, I'm (speculatively) thinking that this is a limitation on the hardware or on the system, since you're asking for nearly 3MB from the allocator. You could confirm this with:
> 
> ```python
> import ctypes
> 
> dll = ctypes.CDLL("libc.so.6")
> dll.malloc.argtypes = ctypes.c_ssize_t,
> dll.malloc.restype = ctypes.c_void_p
> print(dll.malloc(2764800))  # Number of bytes that you're allocating
> ```

I tried what you asked, It seems to be working without any problem on Jetson, in particular it works outside and inside the docker env with the other microservices that communicate and the massage broker obv: while exchanging messages I try to allocate memory in another microservice with the code you provided and it prints out the memory address as expected. Thanks for your advice anyway.

Have you got any other ideas?

**Comment by TheBlind11** [comment]
The problem we had was not dealing with ctypes: we were using durable queues on our RabbbitMQ message broker, so it was trying to store every message on disk, but it wasn't able to do it, that's why we were losing part of data in communication. 

I'm so sorry for the inconvenience :)
