### ISSUE TITLE
Output chunk size for `ProcessPoolExecutor`

### ISSUE THREAD

**Issue by HAOCHENYE** [python/cpython#122964]
# Feature or enhancement

### Proposal:

For the current `ProcessPoolExecutor`, chunk size is only relevant to the input queue. However, in scenarios with high concurrency and short-running concurrent functions, frequent output transmissions from subprocesses to the main process can significantly impact efficiency.

Therefore, I was thinking about whether it would be possible to add a parameter like `output_chunk_size` or `chunk_out` to the `ProcessPoolExecutor`, allowing child processes to control the frequency of sending output chunks.

I've tried it in my case, and found that there is indeed a noticeable improvement in efficiency for my task. It works approximately like this:

```python
with ProcessPoolExecutor() as exector:
    for _ in exector(..., chunk_size=30, chunk_out=True):
        ...
```

If it is possible, I'd like to contribute to it.
### Has this already been discussed elsewhere?

No response given

**Comment by picnixz** [comment]
This feature probably requires a discussion: https://discuss.python.org/c/ideas/6. You should also be more precise when you talk about efficiency: what are the actual numbers? in which situations? Now, to summarize, you want to "block" children processes to send the data back to the main process until, let's say, 30 items are available (and then you would send them in one go?)

**Comment by picnixz** [comment]
Closing as `not planned` for now. The issue may be reopened when this (not-so-minor) feature receives sufficient support on discourse.
