### ISSUE TITLE
What’s the difference between “linesep” and “self.policy.linesep” in Lib.email.generator.Generator._write_headers?

### ISSUE THREAD

**Issue by mcepl** [python/cpython#122989]
https://github.com/python/cpython/blob/325e9b8ef400b86fb077aa40d5cb8cec6e4df7bb/Lib/email/generator.py#L230

Is there something special in the difference between `linesep` or `self.policy.linesep` or is it just a typo?

### Linked PRs
* gh-123002
* gh-123012

**Comment by terryjreedy** [comment]
Since the previous line 229 is `linesep = self.policy.linesep`, the `self.policy` in 230 is redundant, and should better be removed.  I'd call this a buglet, though 'performance' might be a better label.

**Comment by bitdancer** [comment]
Yeah, it's probably a refactoring leftover from when the code was written.
