### ISSUE TITLE
Unnecessary specialization failures of `LOAD_ATTR` and `STORE_ATTR` when attributes are shadowed by the object's class.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#123040]
This applies to both instances and classes.
If an object and it's class both have attributes with the same name, this prevents specialization of access to the object's attribute.
However, in this case specialization should only be prevented if the class's attribute is a data descriptor.

Example 1, instance:
```Py
class C:
    x = 1
    def __init__(self):
        self.x = 2

C().x
```
`C().x` above is `2`. It doesn't matter that `C.x` exists, provided it isn't a data descriptor.
This failure shows up as "shadowed" in the [stats](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20240814-3.14.0a0-f84754b-PYTHON_UOPS/bm-20240814-azure-x86_64-python-main-3.14.0a0-f84754b-pystats.md#load_attr-1)

Example 2, class:
```Py
class Meta(type):
    x = 1
class C(metaclass=Meta):
    x = 1

C.x
```
`C.x` is `2`. `Meta.x` doesn't change that, as it isn't a data descriptor.
This failure shows up as "metaclass attribute" in the [stats](https://github.com/faster-cpython/benchmarking/blob/main/results/bm-20240814-3.14.0a0-f84754b-PYTHON_UOPS/bm-20240814-azure-x86_64-python-main-3.14.0a0-f84754b-pystats.md#load_attr-1)

### Linked PRs
* gh-123219

**Comment by markshannon** [comment]
For `STORE_ATTR`, the failures show up in various ways, depending on the nature of the class's attribute.

**Comment by picnixz** [comment]
Should this one be categorized as a bug or a feature (AFAICT, it's not really a bug per se, it's just an inefficient path being taken)?

**Comment by markshannon** [comment]
I'll just tag it "performance"
