### ISSUE TITLE
Missing some obvious ast optimizations

### ISSUE THREAD

**Issue by wrongnull** [python/cpython#123080]
# Feature or enhancement

### Proposal:

suppose the following code
```python
1 in [1, 2]
```
it produces such byte code
```
  0           0 RESUME                   0

  1           2 LOAD_CONST               0 (1)
              4 LOAD_CONST               1 ((1, 2))
              6 CONTAINS_OP              0
              8 RETURN_VALUE
```
however, interpreter can easily fold such an expression to a constant in the ast_opt stage. This only applies if both ast nodes are ```Constant_kind```. But there is one obstacle. Types are not yet ready and have incomplete mro at the ast_opt stage. So we can't use functions like ```PyObject_RichCompare``` for this. We can compare pointers to PyObject instead, since we know that each object in a "constant expression" is internally a singleton (interned strings, integers from -5 to 255, etc.). Thus, for them, the ```==``` operator is semantically equal to the ```is``` operator. I'm going to make pull request for this

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-123081

**Comment by serhiy-storchaka** [comment]
The optimizer code is intentionally kept simple. Only necessary optimizations are performed, these that are common in user code. For example, `'-'*80`, `1/3` or `2**32-1`.

This idea was already proposed and rejected earlier, for example in #70909. I think that this issue should be closed for the same reasons.

**Comment by wrongnull** [comment]
> The optimizer code is intentionally kept simple. Only necessary optimizations are performed, these that are common in user code. For example, `'-'*80`, `1/3` or `2**32-1`.
> 
> This idea was already proposed and rejected earlier, for example in #70909. I think that this issue should be closed for the same reasons.

IMO since there is no strict definition of necessity if interpreter CAN optimize something in a reasonable amount of time it SHOULD do so

**Comment by serhiy-storchaka** [comment]
It's not done that way. You should have good reasons to do something, not to not do it. Adding new optimizations increases maintenance burden and has a risk of introducing new bugs.
