### ISSUE TITLE
Improve Code of Conduct & Security Policy files.

### ISSUE THREAD

**Issue by UjjwalSaini07** [python/cpython#123000]
# Feature or enhancement

### Make sure that Azure Pipeline is working fine, but it now show error of failed.
![Pipeline Failed](https://dev.azure.com/python/cpython/_apis/build/status/Azure%20Pipelines%20CI?branchName=main)

### Has this already been discussed elsewhere?

No response given

**Comment by picnixz** [comment]
My bad I wanted to comment but I closed the issue. 

Could you perhaps be more precise in what information you want?

**Comment by irfan-IT01** [comment]
there should be more complicated

**Comment by picnixz** [comment]
They are explained more in details externally, namely https://policies.python.org/python.org/code-of-conduct/ and https://www.python.org/dev/security/. I don't think this should be duplicated in the GitHub files themselves.

Closing as `not planned`.
