### ISSUE TITLE
PyArg_ParseTuple incorrectly parses the input with "ip" (int, bool), but does process correctly "ii" (int, int)

### ISSUE THREAD

**Issue by ajalexei** [python/cpython#123090]
# Bug report

### Bug description:

PyArg_ParseTuple seems to handle incorrectly if an integer/integers and a boolean/bool are passed as arguments to parse, e.g. for the format string "ip" or "iip", etc. It then produces the incorrect value for the first integer argument. In my code I get zero value for that first integer argument, and correct values for the the rest of the arguments. The issue seem to disappear if the qualifier for the boolean argument "p" is replaced with the integer one "i". The issue is also not there for the "Op" format string, e.g. when a Python object and a boolean are passed as arguments.

To illustrate the issue I created an example [module](https://github.com/ajalexei/PyArg_ParseTupleBug) that reproduces the bug. (The code is a bit too long to place it here directly, since it has to be a C extension)

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-123097

**Comment by skirpichev** [comment]
I don't think it's a bug.  You are using wrong C type for boolean value (should be int, not bool):
```c
static PyObject*
bug1(PyObject *o, PyObject *args)
{
    int a;
    int b;
    PyArg_ParseTuple(args, "ip", &a, &b);
    printf("%d %d\n", a, b);
    Py_RETURN_NONE;
}
```
```pycon
>>> import example
>>> example.bug1(-123, False)
-123 0
>>> example.bug1(123, False)
123 0
>>> example.bug1(123, True)
123 1
```

**Comment by ZeroIntensity** [comment]
Though, adding a format character for `_Bool`/`bool` could be a reasonable feature; perhaps something like `p#`?

**Comment by skirpichev** [comment]
JFR, this type added in https://github.com/python/cpython/issues/58910.  C99+ wasn't allowed at this point.  Now I think this does make sense.

But I would worry more about possible documentation issue.  Is this obvious that is assume int?

**Comment by ZeroIntensity** [comment]
> Is this obvious that is assume int?

I think so, `int` is listed as the output type next to the format character.

**Comment by ZeroIntensity** [comment]
I've created #123097 to add a format character that support the C `bool`.

**Comment by serhiy-storchaka** [comment]
I do not think that addition of a format unit for `_Bool` is well justified. `_Bool` is rarely used, and you always can use `int` which *is* the type for the result of relational and logical operators in C. `_Bool` is not even used in the Python's C API -- functions that return a boolean (like `PyTuple_Check()`) return `int`, and functions which take a boolean argument (like `PyUnicode_Splitlines()`) have an `int` parameter. There is a lack of support of more useful C types (unsigned integer types with range check, fixed width integer types) -- `_Bool` goes far behind them.

As for the concrete implementation, `*` for now is only used with `Py_buffer`, so introducing `p*` would be confusing. But there are not much other symbols which are worth to waste on this.

**Comment by ZeroIntensity** [comment]
> As for the concrete implementation, `*` for now is only used with `Py_buffer`, so introducing `p*` would be confusing. But there are not much other symbols which are worth to waste on this.

Oh! I was under the impression `*` and `#` were used as an "extension" for some format characters.

FWIW, the only issue this would solve is it *might* make it more clear (to those that don't read the docs, :stuck_out_tongue:) that `p` is for integers, not `bool`/`_Bool`, so users don't run into problems like this issue.

**Comment by skirpichev** [comment]
> I do not think that addition of a format unit for _Bool is well justified.

Perhaps, to save some space?

> _Bool is not even used in the Python's C API

On another hand, both ctypes and struct modules support it.  (Both use ``?`` code.)

> As for the concrete implementation, * for now is only used with Py_buffer, so introducing p* would be confusing.  But there are not much other symbols which are worth to waste on this.

I don't see strict mnemonic rules behind format codes for parsing in PyArg_Parse* ;)   So, why not just ``P``?

**Comment by ZeroIntensity** [comment]
>  So, why not just `P`?

Oh yeah, that's probably better... I'll update the PR (though, it seems like something that might not get merged based on Serhiy's comments.)

**Comment by ericvsmith** [comment]
I agree with @serhiy-storchaka that this isn't worth adding. If you want to pursue it, the correct thing to do is open an discussion at https://discuss.python.org/c/ideas/6. Until consensus is reached there, I suggest this issue be closed.

**Comment by ZeroIntensity** [comment]
I don't think this is worth trying to deal with on discourse, it was more just a spur-of-the-moment QoL thing. I'll close the PR, thanks!

**Comment by serhiy-storchaka** [comment]
> Perhaps, to save some space?

In very rare circumstances. Most of local variables are integers, pointers, floating-point numbers and arrays. You need to have more than one `_Bool`, `char` or `short` variables to save any space, and there is no guarantee of this -- the compiler can allocate full 32 bits for performance or optimize it out and use registers.

You can only save space if you have an array of booleans or multiple boolean fields in the structure (and bit fields may be more efficient for this), but this is not how `PyArg_ParseTuple` is used.

> On another hand, both ctypes and struct modules support it. (Both use `?` code.)

Because they need to work with the third-party C API. This is different from `PyArg_ParseTuple`.

And I think that using non-letter code for `_Bool` was a mistake.
