### ISSUE TITLE
FileNotFoundError im LXC container

### ISSUE THREAD

**Issue by DocMAX** [python/cpython#123099]
# Bug report

### Bug description:

https://forum.proxmox.com/threads/filenotfounderror-im-lxc-container.152965/

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
Please, explain the issue directly here instead of linking it to an external website. AFAICT, this may be an issue with the mount points, but I'm not sure we can do something here.

**Comment by ZeroIntensity** [comment]
Could #122890 be related?

**Comment by picnixz** [comment]
cc @barneygale as the path expert

**Comment by DocMAX** [comment]
Looks like it's a LXC container issue + Binfmt. I try to run a Windows EXE and it seems binfmt is not running. A very special use-case. Thus closing this.
