### ISSUE TITLE
enum.Flag __len__ missing "Added in version 3.11." in description

### ISSUE THREAD

**Issue by AlexChapman18** [python/cpython#123005]
# Documentation
\_\_len\_\_ is missing the tag "Added in version 3.11." in its description.

Page: https://docs.python.org/3/library/enum.html#enum.Flag

### Linked PRs
* gh-123007
* gh-123025
* gh-123026

**Comment by AA-Turner** [comment]
PR welcome!

A

**Comment by ethanfurman** [comment]
Thank you!
