### ISSUE TITLE
Error in the french version of Python documentation

### ISSUE THREAD

**Issue by Questionsdenombres** [python/cpython#123068]
# Documentation
https://docs.python.org/fr/3/library/stdtypes.html#boolean-operations-and-or-not

# Actual
The first line of the table reads: "si x est faux, alors x, sinon y".

# Expected:
The first line of the corresponding english table reads: "if x is true, then x, else y".
The expected translation is: "si x est **vrai**, alors x, sinon y".
It's more than a typo: the logic is reversed.

Thank you for your great job.

**Comment by picnixz** [comment]
I think this should be reported to https://git.afpy.org/AFPy/python-docs-fr since it only concerns localized docs (this repository doesn't host the translations).

@JulienPalard can you confirm that this is the right course to do?

**Comment by AA-Turner** [comment]
Yes, please report to the translations repo.

A
