### ISSUE TITLE
`shutil.copytree` returns errors in incorrect format

### ISSUE THREAD

**Issue by j8lp** [python/cpython#123039]
# Bug report

### Bug description:

When using `shutil.copytree`, the errors returned are not in the expected format of a list of 3-tuples `(srcname, dstname, exception)`. Instead, the errors are being returned as a long list of characters, making it difficult to parse and handle the errors programmatically.

**Steps to Reproduce:**
1. Use `shutil.copytree` to copy a directory tree where some errors are expected (e.g., permission issues, missing files).
2. Catch the `shutil.Error` exception.
3. Print or inspect the `shutil.Error` exception.

**Expected Behavior:**
The `shutil.Error` exception should contain a list of 3-tuples, where each tuple represents an error in the format `(srcname, dstname, exception)`.

**Actual Behavior:**
The `shutil.Error` exception contains a long list of characters instead of the expected 3-tuple format.

**Example Code:**
```python
import shutil

source = 'path/to/source'
destination = 'path/to/destination'

try:
    shutil.copytree(source, destination) 
except shutil.Error as e:
    print(e.args[0])  # This prints a long list of characters instead of a list of 3-tuples ```


### CPython versions tested on:

3.8

### Operating systems tested on:

Windows

**Comment by eendebakpt** [comment]
@j8lp You reported the bug for python 3.8, which only accepts [security fixes](https://devguide.python.org/versions/#status-of-python-versions). Could you reproduce the error on a more recent python version and report the contents of `e.args`?

On Python 3.12 (Windows) I can get a `FileNotFoundError` or a `PermissionError` (depending on the arguments that I pass to `shutil.copytree`). Both are not a`shutil.Error`, even though the documentation of [copytree](https://docs.python.org/3/library/shutil.html#shutil.copytree) suggest that `copytree` should return a `shutil.Error`.

**Comment by j8lp** [comment]
@eendebakpt Oh in that case it works in the latest version.  Shame.  I'll close the issue
