### ISSUE TITLE
Adding build Android test in Github Workflow 

### ISSUE THREAD

**Issue by Damien-Chen** [python/cpython#123016]
# Feature or enhancement

### Proposal:

I notice that [here](https://github.com/python/cpython/tree/main/Android) demonstrate the step of how to build and run python on Android, but CI/CD workflow doesn`t contain check/build/test on Android. 

If it`s necessary to add test on Android platform ?
Thanks.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by hugovk** [comment]
We use GitHub Actions for tier 1 supported platforms, where failures block the build:

https://peps.python.org/pep-0011/#tier-1

Android will be tier 3, so will be tested via a buildbot:

https://peps.python.org/pep-0011/#tier-3

This buildbot should be coming in the next few days:

https://github.com/python/cpython/pull/122990#discussion_r1717035599
