### ISSUE TITLE
itertools.tee optimal de-reference

### ISSUE THREAD

**Issue by dg-pb** [python/cpython#123056]
# Feature or enhancement

### Proposal:

Snippet below (by @tim-one) shows how objects are being held in memory longer than they are needed.

I suggest implementing immediate de-referencing / memory freeing.
1. So that `tee` covers more use-cases, namely big objects
2. So that it is in line with its "roughly equivalent" in docs

```python
from itertools import tee

class C:
    def __init__(self, i):
        self.i = i

    def __del__(self):
        print("bye bye", self.i)

it = (C(i) for i in range(500))
it1, it2 = tee(it)
for t in zip(it1, it2):
    print(t[0].i, t[1].i)
```

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

Briefly: https://discuss.python.org/t/challenge-quest-for-counting-iterator-length-at-c-speed/60042/28

**Comment by rhettinger** [comment]
We looked at this when `tee()` was first written.  The conclusion was that the added overhead of tracking tee internal reference counts wasn't worth it.  In its two decade history, not a single user has reported a problem with tee hanging on to a reference for the duration that a block is in use. It doesn't seem to be a problem in practice. I don't want to add logic that makes everyone pay for a problem that almost no one has.  We want tee operation to be as fast as possible.

Also before considering adding any complexity at all to the code, I first want to address a real problem.  We need to get rid of the possible *RuntimeError* and make `tee()` safe for use in free threaded builds.  This is much more important to users.
