### ISSUE TITLE
Remove `shutil.ExecError`

### ISSUE THREAD

**Issue by barneygale** [python/cpython#123084]
# Feature or enhancement

As of Python 3.5 / GH-64943 / a0934b2c1b939fdebee8dc18d49a0f6c52324773, `shutil.ExecError` exceptions are not raised in any circumstances. I propose that we delete the `ExecError` class and remove it from `__all__`.

### Linked PRs
* gh-123125

**Comment by ZeroIntensity** [comment]
A [quick GitHub search](https://github.com/search?q=%22from+shutil+import+ExecError%22+language%3APython&type=code&p=1) shows that some are still using it in one way or another, how about just turning this into a deprecated alias of `RuntimeError`, or something similar?

**Comment by picnixz** [comment]
Per our guidelines, we do not add version labels to features since they are implicitly targetting main: https://devguide.python.org/triage/labels/#type-labels
