### ISSUE TITLE
Simpler implementation of `Property` class in pure Python

### ISSUE THREAD

**Issue by dongbohu** [python/cpython#123176]
# Documentation

The `Descriptor Guide` Howto implements a sample `Property` class that is equivalent to `property` builtin class:
https://github.com/python/cpython/blob/bffed80230f2617de2ee02bd4bdded1024234dab/Doc/howto/descriptor.rst?plain=1#L1046

I wonder whether the `getter`, `setter` and `deleter` methods can be simplified like this:
```python
class Property:
    # ...
    def getter(self, fget):
        self.fget = fget
        return self

    def setter(self, fset):
        self.fset = fset
        return self

    def deleter(self, fdel):
        self.fdel = fdel
        return self
```
Thanks.

**Comment by picnixz** [comment]
The docs explicitly states:

https://github.com/python/cpython/blob/bffed80230f2617de2ee02bd4bdded1024234dab/Doc/howto/descriptor.rst?plain=1#L992-L993

In particular, the purpose is not to have a simple example but to have a pure Python equivalent matching the C implementation. 

Closing as `wontfix`.
