### ISSUE TITLE
dataclasses: mismatched assignment order with re-ordered kw-only params

### ISSUE THREAD

**Issue by mara004** [python/cpython#123180]
# Bug report

### Bug description:

With dataclasses, keyword-only fields are moved to make inheritance feasible:
```python
from dataclasses import dataclass, field

@dataclass(kw_only=True)
class AbstractPage:
    transforms: list = field(default_factory=list)
    overlays: list = field(default_factory=list)
    bookmarks: list = field(default_factory=list)

@dataclass
class Page (AbstractPage):
    doc: ...
    index: int
```

So the generated `__init__()` signature would look like this:
```python
def __init__(self, doc, index, transforms=..., overlays=..., bookmarks=...)
```

Great! However, when actually constructing an object, the order in which arguments have been assigned does not match the `__init__()` signature, resulting in a rather awful representation of the class:
```python
p = Page(..., 1)
print(repr(p))
print(vars(p))
```
```python
Page(transforms=[], overlays=[], bookmarks=[], doc=Ellipsis, index=1)
{'transforms': [], 'overlays': [], 'bookmarks': [], 'doc': Ellipsis, 'index': 1}
```
IMHO the order of assignments should match the order of `__init__()` arguments, so `doc` and `index` should go first, as when creating a `Page` object.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
When you say "the order of assignments", do you mean the order shown in `repr`? I think this is the same order as returned by `dataclasses.fields`.

Unfortunately I think the ship has sailed on this issue. I'm pretty sure we'd break someone's code if we made this change.

**Comment by mara004** [comment]
> When you say "the order of assignments", do you mean the order shown in repr?

I meant the order of `vars(p)`, which I thought would correspond to the order in which the attributes had been assigned to the object, imagining that that might be used as basis for the `__repr__()`. But otherwise, yes, the representation is my primary concern.

**Comment by mara004** [comment]
Or more generally, I was just thinking of the order in which field attributes are accessed in the generated procedures (init, repr, and anything else). This always seems to be the linear composition of parent and child fields, not the re-ordered init signature, which felt confusing to me.

**Comment by sobolevn** [comment]
I will take a look at what can be done! Thanks a lot for the report!

**Comment by ericvsmith** [comment]
I'm not convinced that anything needs changing here, especially if it's going to break any code or take new parameters to `@dataclass`.

**Comment by mara004** [comment]
Hmm, I understand backward compatibility is important, and you probably don't want to clutter dataclass with options.
On the other hand, the repr looking the way it does is still unfortunate.

**Comment by sobolevn** [comment]
So, I had time to dig into this issue. Here's what I found.
- We most likely cannot change the fields order in `repr`, because it might break tests / doctests / something else for people. Since there's no *real issue* in this (only aestetics), I don't recommend doing it
- Changing `vars()` output also does not make much sense, because it just returns a `dict`, order does not really matter much

So, I recommend closing this issue, because there are no clean ways forward.
Thanks a lot for the report though, it was interesting!

**Comment by mara004** [comment]
FWIW, in simple cases like the above, I suppose we could do something like this:

```python
@dataclass(kw_only=True)
class AbsPage:
    transforms: list = field(default_factory=list)
    overlays: list = field(default_factory=list)
    bookmarks: list = field(default_factory=list)
    
    def _repr_contents(self):
        return ", ".join(f"{k}={getattr(self, k)}" for k in AbsPage.__dataclass_fields__.keys())

@dataclass
class Page (AbsPage):
    doc: ...
    index: int
    
    def __repr__(self):
        return f"{type(self).__name__}({self.doc}, {self.index}, {super()._repr_contents()})"
```

It does need some manual spelling out though, and would become tedious with more elaborate cases.
