### ISSUE TITLE
Pasting long line in new REPL causes text to appear after >>>

### ISSUE THREAD

**Issue by Siecje** [python/cpython#123177]
# Bug report

### Bug description:

When I paste code that is one line and my REPL window is small the text that would not be shown because it is offscreen is displayed after pressing enter.

For example I am pasting 
```Python
thread = threading.Thread(target=lambda: threading.current_thread().name == 'MainThread')
```

After I paste and then press enter to create the object I see

```Python
>>> read')
```

I can't remove the text or use the arrow keys to navigate the letters since the >>> prompt is empty.

When the window is smaller more text is shown after `>>>`.

```
>>> thread = threading.Thread(target=lambda: threading.current_thread()\
                                                                                                                        >
>>> name == 'MainThread')
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-123267
* gh-123322
* gh-123324
* gh-123327

**Comment by skirpichev** [comment]
Hmm, can someone reproduce this on recent main?  Is this Mac-specific?  I can't reproduce this on Linux.

**Comment by pablogsal** [comment]
This seems partially related to the cache but not fully. Removing the line cache shows the following problem:


https://github.com/user-attachments/assets/25992730-f9cb-4775-9e08-817dad71b840

**Comment by pablogsal** [comment]
For some reason this only happens in the terminal app and not in iterm

**Comment by pablogsal** [comment]
Another problem: seems like the cache forces lines that warp around to also start with `>>>` (but they should not).

**Comment by pablogsal** [comment]
@godlygeek could you take a look at this if you have some free cycles?

**Comment by Siecje** [comment]
When I type random words like that as soon as I get to the end of the line I see strange behaviour including `>>>` moving.

https://github.com/user-attachments/assets/7fa81526-dfd2-4e97-b78c-f1cf3867e95c

**Comment by pablogsal** [comment]
What terminal are you using?

**Comment by pablogsal** [comment]
Can you try if https://github.com/python/cpython/pull/123267 fixes the other problem for you?

**Comment by Siecje** [comment]
> What terminal are you using?

The default "Terminal"

**Comment by pablogsal** [comment]
Can you run `echo $TERM_PROGRAM`?

**Comment by Siecje** [comment]
`Apple_Terminal`

**Comment by godlygeek** [comment]
Seems like there's two separate issues here, one with how Apple Terminal behaves when something is written to the last column of a line, and one with the cache. I understand what's causing the cache bug, but I'm still deciding how best to fix it.

**Comment by pablogsal** [comment]
> Seems like there's two separate issues here, one with how Apple Terminal behaves when something is written to the last column of a line, and one with the cache. I understand what's causing the cache bug, but I'm still deciding how best to fix it.

The apple terminal one it's being handled here: https://github.com/python/cpython/pull/123267
