### ISSUE TITLE
Source locations too broad for list comprehension iterable expression

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#123142]
# Bug report

Reported here: https://github.com/python/cpython/pull/120330#issuecomment-2295256627

```python
class Foo:
    def __iter__(self):
        assert False

a = [x for x in Foo()]
```

output (Python 3.12.5):
```python
Traceback (most recent call last):
  File "/home/frank/projects/executing/codi.py", line 5, in <module>
    a = [x for x in Foo()]
        ^^^^^^^^^^^^^^^^^^
  File "/home/frank/projects/executing/codi.py", line 3, in __iter__
    assert False
           ^^^^^
AssertionError
```

### Linked PRs
* gh-123173
* gh-123209
* gh-123210
* gh-123420
* gh-123435
* gh-123436

**Comment by picnixz** [comment]
Closing since completed in https://github.com/python/cpython/pull/123173 and backported.

**Comment by iritkatriel** [comment]
See https://github.com/python/cpython/pull/123173#issuecomment-2310829704
