### ISSUE TITLE
`configparser.InterpolationSyntaxError` with `%` in Configuration File

### ISSUE THREAD

**Issue by mshemuni** [python/cpython#123186]
# Bug report

### Bug description:

When using Python's `configparser` to parse a configuration file containing the `%` character, the code fails with an `InterpolationSyntaxError`. This issue arises even though the configuration file is correctly formatted for its intended use (e.g., Samba configuration).

#### Reproduction Steps:

Consider the following code:

```python
import configparser

config = configparser.ConfigParser()
config.read('/etc/samba/smb.conf')
config_dict = {section: dict(config.items(section)) for section in config.sections()}
```

If the configuration file contains any `%` characters, an `InterpolationSyntaxError` is raised. The error message typically looks like this:

```
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%h server (Samba, Ubuntu)'
```

#### Example Configuration:

Here’s a sample from the problematic configuration file:

```
[global]
   workgroup = WORKGROUP
   server string = %h server (Samba, Ubuntu)
   log file = /var/log/samba/log.%m
   max log size = 1000
   logging = file
   panic action = /usr/share/samba/panic-action %d
   server role = standalone server
   obey pam restrictions = yes
   unix password sync = yes
   passwd program = /usr/bin/passwd %u
   passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:* %n\n *password\supdated\ssuccessfully* .
   pam password change = yes
   map to guest = bad user
   usershare allow guests = yes

[printers]
   comment = All Printers
   browseable = no
   path = /var/spool/samba
   printable = yes
   guest ok = no
   read only = yes
   create mask = 0700

[print$]
   comment = Printer Drivers
   path = /var/lib/samba/printers
   browseable = yes
   read only = yes
   guest ok = no
```

#### Error Traceback:

The full error traceback when running the script:
```
$HOME/anaconda3/envs/lkbm/bin/python $HOME/Documents/GitHub/lkbm/tst.py 
Traceback (most recent call last):
  File "$HOME/Documents/GitHub/lkbm/tst.py", line 21, in <module>
    cnf = Conf("c.cnf")
  File "$HOME/Documents/GitHub/lkbm/pardus/conf/conf.py", line 13, in __init__
    config_dict = {section: dict(config.items(section)) for section in config.sections()}
  File "$HOME/Documents/GitHub/lkbm/pardus/conf/conf.py", line 13, in <dictcomp>
    config_dict = {section: dict(config.items(section)) for section in config.sections()}
  File "$HOME/anaconda3/envs/lkbm/lib/python3.10/configparser.py", line 861, in items
    return [(option, value_getter(option)) for option in orig_keys]
  File "$HOME/anaconda3/envs/lkbm/lib/python3.10/configparser.py", line 861, in <listcomp>
    return [(option, value_getter(option)) for option in orig_keys]
  File "$HOME/anaconda3/envs/lkbm/lib/python3.10/configparser.py", line 857, in <lambda>
    value_getter = lambda option: self._interpolation.before_get(self,
  File "$HOME/anaconda3/envs/lkbm/lib/python3.10/configparser.py", line 396, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "$HOME/anaconda3/envs/lkbm/lib/python3.10/configparser.py", line 443, in _interpolate_some
    raise InterpolationSyntaxError(
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%h server (Samba, Ubuntu)'

Process finished with exit code 1

```

#### Workaround:

To circumvent this issue, I replaced each `%` with `[percentage]` throughout the configuration file. After making this change, the code executed successfully:

```
{'global': {'workgroup': 'WORKGROUP', 'server string': '[percentage]h server (Samba, Ubuntu)', 'log file': '/var/log/samba/log.[percentage]m', ...}}
```

#### Testing:

I confirmed the issue by:

1. **Removing all lines with `%`:** The code executed without errors.
2. **Removing lines with `%` one by one:** The error persisted until all such lines were removed.
3. **Adding a new line with `%`:** The code failed again with the same error.

#### Conclusion:

The issue seems to be directly tied to the presence of `%` characters in the configuration file. This behavior limits the use of `configparser` for files that legitimately use `%` as part of their syntax, such as Samba configuration files.

Is there a way to handle such files with `configparser` without manual replacement of `%` characters? If not, could this be considered for a future enhancement?

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
I think interpolation require to explicitly specify a key, e.g., `%(something)h` and not `%h`.

cc @jaraco

**Comment by sobolevn** [comment]
I think that you just need to turn off `interpolation` by setting it to `None`, see: https://docs.python.org/3/library/configparser.html#customizing-parser-behaviour

```python
>>> import configparser
>>> config = configparser.ConfigParser(interpolation=None)
>>> config.read('ex.cfn')
>>> config_dict = {section: dict(config.items(section)) for section in config.sections()}
>>> config_dict
{'global': {'workgroup': 'WORKGROUP', 'server string': '%h server (Samba, Ubuntu)', 'log file': '/var/log/samba/log.%m', 'max log size': '1000', 'logging': 'file', 'panic action': '/usr/share/samba/panic-action %d', 'server role': 'standalone server', 'obey pam restrictions': 'yes', 'unix password sync': 'yes', 'passwd program': '/usr/bin/passwd %u', 'passwd chat': '*Enter\\snew\\s*\\spassword:* %n\\n *Retype\\snew\\s*\\spassword:* %n\\n *password\\supdated\\ssuccessfully* .', 'pam password change': 'yes', 'map to guest': 'bad user', 'usershare allow guests': 'yes'}, 'printers': {'comment': 'All Printers', 'browseable': 'no', 'path': '/var/spool/samba', 'printable': 'yes', 'guest ok': 'no', 'read only': 'yes', 'create mask': '0700'}, 'print$': {'comment': 'Printer Drivers', 'path': '/var/lib/samba/printers', 'browseable': 'yes', 'read only': 'yes', 'guest ok': 'no'}}
```

I hope this helps!

**Comment by jaraco** [comment]
I wonder if ConfigParser shouldn't simply ignore these values. After all, if `%%` or `%(` is required to signal interpolation, couldn't `%h` be treated like a literal value? That would give users like OP a less surprising experience, at the expense of users who have mis-typed an intended interpolation. That would also mean that `%%` would only need to be used when followed by `(`. Presumably the same treatment could be applied to the other interpolation method. I don't recall if this concern has been discussed before.

I don't feel strongly enough about it to file an issue, but I mention it as something to consider. If someone else feels like carrying the torch.

**Comment by sobolevn** [comment]
cc @ambv who commits to `configparser`
