### ISSUE TITLE
unable to build in visual studio 2022

### ISSUE THREAD

**Issue by quantrpeter** [python/cpython#123137]
# Bug report

### Bug description:

Hi, unable to build in visual studio 2022, any hints please?

![image](https://github.com/user-attachments/assets/40f99d22-89c1-481a-aa68-e06c1afd1189)

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
For such issues, we generally recommend posting on Stackoverflow or on discourse first. Check https://github.com/python/cpython/blob/main/PCbuild/readme.txt as well. 

Closing as a `non-CPython issue` for now. I suspect there are some configuration steps or include steps that were skipped or maybe the PATH variable is not updated (hence the include failures).
