### ISSUE TITLE
Missing error check in ast_opt.c

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#123171]
This line was copied from `fold_iter`. So, `fold_iter` has the same issue (no error handling for NULL values on calls to `PyFrozenSet_New`). Do you think it's OK to address this issue in this PR?

_Originally posted by @Eclips4 in https://github.com/python/cpython/pull/123081#discussion_r1722687840_
            

### Linked PRs
* gh-123172

**Comment by serhiy-storchaka** [comment]
What exactly is the error?

**Comment by pablogsal** [comment]
> What exactly is the error?

Check out https://github.com/python/cpython/pull/123172#issuecomment-2299658384
