### ISSUE TITLE
python3.9 consumes more memory than python3.7

### ISSUE THREAD

**Issue by xinsheng3** [python/cpython#123143]
# Feature or enhancement

### Proposal:

```python
import time


class TestCompare(object):
    @staticmethod
    def insert_packages():
        pass

    def setup(self):
        pass

    def process(self):
        pass

    def exit(self):
        pass


if __name__ == "__main__":
    while True:
        time.sleep(10)

```
[root@localhost ~]# python3 -V
Python 3.9.9
[root@localhost ~]# python3 python37_vs_python39.py &
[1] 233166
[root@localhost ~]# pmap -x 233166
233166:   python3 python37_vs_python39.py
Address           Kbytes     RSS   Dirty Mode  Mapping
0000aaaac5d40000       4       4       0 r-x-- python3.9
0000aaaac5d5f000       4       4       4 r---- python3.9
0000aaaac5d60000       4       4       4 rw--- python3.9
0000aaaae57b2000     532     476     476 rw---   [ anon ]
0000ffffa3556000    1684    1520    1520 rw---   [ anon ]
0000ffffa36fb000   18592     340       0 r---- locale-archive
0000ffffa4923000    1548    1132       0 r-x-- libc.so.6
0000ffffa4aa6000     104       0       0 ----- libc.so.6
0000ffffa4ac0000      12      12      12 r---- libc.so.6
0000ffffa4ac3000      12      12      12 rw--- libc.so.6
0000ffffa4ac6000      48      16      16 rw---   [ anon ]
0000ffffa4ad2000     524      60       0 r-x-- libm.so.6
0000ffffa4b55000     112       0       0 ----- libm.so.6
0000ffffa4b71000       4       4       4 r---- libm.so.6
0000ffffa4b72000       4       4       4 rw--- libm.so.6
0000ffffa4b73000     200      60       0 r-x-- libcrypt.so.1.1.0
0000ffffa4ba5000     116       0       0 ----- libcrypt.so.1.1.0
0000ffffa4bc2000       4       4       4 r---- libcrypt.so.1.1.0
0000ffffa4bc3000       4       4       4 rw--- libcrypt.so.1.1.0
0000ffffa4bc4000      32       0       0 rw---   [ anon ]
0000ffffa4bcc000    3052    2624       0 r-x-- libpython3.9.so.1.0
0000ffffa4ec7000     116       0       0 ----- libpython3.9.so.1.0
0000ffffa4ee4000      32      32      32 r---- libpython3.9.so.1.0
0000ffffa4eec000     216     216     216 rw--- libpython3.9.so.1.0
0000ffffa4f22000     136     128     128 rw---   [ anon ]
0000ffffa4f44000     148     148       0 r-x-- ld-linux-aarch64.so.1
0000ffffa4f73000      16      16      16 rw---   [ anon ]
0000ffffa4f78000      28      28       0 r--s- gconv-modules.cache
0000ffffa4f7f000       8       0       0 r----   [ anon ]
0000ffffa4f81000       4       4       0 r-x--   [ anon ]
0000ffffa4f82000       8       8       8 r---- ld-linux-aarch64.so.1
0000ffffa4f84000       8       8       8 rw--- ld-linux-aarch64.so.1
0000ffffd3f49000     132      60      60 rw---   [ stack ]
---------------- ------- ------- -------
total kB           27448    6928    2528

[root@localhost ~]# python3 -V
Python 3.7.9
[root@localhost ~]# python3 python37_vs_python39.py &
[1] 2591193
[root@localhost ~]# pmap -x 2591193
2591193:   python3 python37_vs_python39.py
Address           Kbytes     RSS   Dirty Mode  Mapping
0000aaaab0ae0000       4       4       0 r-x-- python3.7
0000aaaab0aff000       4       4       4 r---- python3.7
0000aaaab0b00000       4       4       4 rw--- python3.7
0000aaaabd4e5000     552     512     512 rw---   [ anon ]
0000ffff8f150000    1684    1528    1528 rw---   [ anon ]
0000ffff8f2f5000  210116     412       0 r---- locale-archive
0000ffff9c026000    1432    1188       0 r-x-- libc-2.28.so
0000ffff9c18c000      92       0       0 ----- libc-2.28.so
0000ffff9c1a3000      12      12      12 r---- libc-2.28.so
0000ffff9c1a6000      12      12      12 rw--- libc-2.28.so
0000ffff9c1a9000      12      12      12 rw---   [ anon ]
0000ffff9c1ac000     716     124       0 r-x-- libm-2.28.so
0000ffff9c25f000     112       0       0 ----- libm-2.28.so
0000ffff9c27b000       4       4       4 r---- libm-2.28.so
0000ffff9c27c000       4       4       4 rw--- libm-2.28.so
0000ffff9c27d000       8       8       0 r-x-- libutil-2.28.so
0000ffff9c27f000     116       0       0 ----- libutil-2.28.so
0000ffff9c29c000       4       4       4 r---- libutil-2.28.so
0000ffff9c29d000       4       4       4 rw--- libutil-2.28.so
0000ffff9c29e000      12      12       0 r-x-- libdl-2.28.so
0000ffff9c2a1000     112       0       0 ----- libdl-2.28.so
0000ffff9c2bd000       4       4       4 r---- libdl-2.28.so
0000ffff9c2be000       4       4       4 rw--- libdl-2.28.so
0000ffff9c2bf000     104     100       0 r-x-- libpthread-2.28.so
0000ffff9c2d9000      84       0       0 ----- libpthread-2.28.so
0000ffff9c2ee000       4       4       4 r---- libpthread-2.28.so
0000ffff9c2ef000       4       4       4 rw--- libpthread-2.28.so
0000ffff9c2f0000      16       4       4 rw---   [ anon ]
0000ffff9c2f4000     204      60       0 r-x-- libcrypt.so.1.1.0
0000ffff9c327000     112       0       0 ----- libcrypt.so.1.1.0
0000ffff9c343000       4       4       4 r---- libcrypt.so.1.1.0
0000ffff9c344000       4       4       4 rw--- libcrypt.so.1.1.0
0000ffff9c345000      32       0       0 rw---   [ anon ]
0000ffff9c34d000    2704    2368       0 r-x-- libpython3.7m.so.1.0
0000ffff9c5f1000      88       0       0 ----- libpython3.7m.so.1.0
0000ffff9c607000      24      24      24 r---- libpython3.7m.so.1.0
0000ffff9c60d000     408     392     340 rw--- libpython3.7m.so.1.0
0000ffff9c673000     128     128     128 rw---   [ anon ]
0000ffff9c693000     128     116       0 r-x-- ld-2.28.so
0000ffff9c6bf000      24      16      16 rw---   [ anon ]
0000ffff9c6c9000      28      28       0 r--s- gconv-modules.cache
0000ffff9c6d0000       4       4       0 r----   [ anon ]
0000ffff9c6d1000       4       4       0 r-x--   [ anon ]
0000ffff9c6d2000       4       4       4 r---- ld-2.28.so
0000ffff9c6d3000       8       8       8 rw--- ld-2.28.so
0000ffffe6098000     132      80      80 rw---   [ stack ]
---------------- ------- ------- -------
total kB          219276    7208    2728

python3.9.9   27448 KB
python3.7.9  219276 KB    

Why so much memory difference?

### Has this already been discussed elsewhere?

No response given

**Comment by picnixz** [comment]
Python 3.7 is EOL and Python 3.9 only accepts security patches. As for why more memory is required, it's probably because of additional objects being tracked. Many things changed in Python 3.9, especially in the interpreter. 

Closing as a `non CPython issue`. However, if a similar issue occurs between 3.12 and 3.13rc1 or 3.13rc1 and 3.14, then I'll re-open it.
