### ISSUE TITLE
strftime() and strptime() Format Codes %a and %b do not work with locale 

### ISSUE THREAD

**Issue by p5B2EA84B3** [python/cpython#123124]
# Bug report

### Bug description:

```pycon
Python 3.11.9 (main, Jul 11 2024, 01:05:32) [Clang 16.0.6 (https://github.com/llvm/llvm-project.git llvmorg-16.0.6-0-g7cbf1a on freebsd14
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getlocale()
('de_DE', 'UTF-8')
>>> from datetime import datetime
>>> datetime.strftime(datetime(2024, 3, 31, 23, 59), '%a %b %y %H:%M')
'Sun Mar 24 23:59'
```
Output should be:
```
So Mär 24 23:59
```
For `%a` and `%b` see https://docs.python.org/3.11/library/datetime.html#format-codes

### CPython versions tested on:

3.11

### Operating systems tested on:

Other

**Comment by serhiy-storchaka** [comment]
This is not obvious, but you have to call `locale.setlocale(locale.LC_ALL, '')` or `locale.setlocale(locale.LC_TIME, '')` to set the current locale.
