### ISSUE TITLE
_pyrepl.readline._ReadlineWrapper.get_line_buffer should return a `str`, not a `bytes` object

### ISSUE THREAD

**Issue by cfbolz** [python/cpython#123228]
# Bug report

### Bug description:

`_pyrepl.readline._ReadlineWrapper.get_line_buffer` should return a `str`, not a `bytes` object, because `readline.get_line_buffer` also returns an `str`, not a `bytes`.

this has very little effect in CPython, but in PyPy it causes various problem, because we don't have a `readline` module at all, and use `_pyrepl.readline` instead.

I'm working on a PR.

### CPython versions tested on:

3.13, CPython main branch

### Linked PRs
* gh-123281
* gh-123293
* gh-123302
* gh-123313

**Comment by skirpichev** [comment]
I took liberty to post a pr: https://github.com/python/cpython/pull/123281

**Comment by cfbolz** [comment]
this is now fixed, thanks everyone!

**Comment by cfbolz** [comment]
Ouch, there's a leaking file descriptor in the new test: https://github.com/python/cpython/pull/123281#issuecomment-2308457559
I know where, can fix it.
