### ISSUE TITLE
Add a built-in equivalent of C's `getch()`

### ISSUE THREAD

**Issue by foxypiratecove37350** [python/cpython#123256]
# Feature or enhancement

### Proposal:

I was making a Python program, and I had to get if the user typed a certain character, but without for the user to have to hit Enter, because my program only had to use one character. I didn't want to use a third-party packages because for most they use either platform-specific code, that I want to avoid for compatibility, or obscure solutions, and I also had the constraint to only use the standard library (+ platform-specific library in last resort).

Finally I used platform-specific libraries to access to the C library and use the `getch()` function.

But, I wondered: "CPython is made mostly in C, so that's in fact possible to add in it an equivalent of C's `getch()` that, when called, act the same as `getch()`?". So I propose you this feature, probably add this built-in function in a built-in module like `io` because it's related to inputs/outputs, or `os` because it's where there's most of built-in functions made in C.

Here's an example of what it will look like in Python:

```python
import io # or whatever you will put it in

prompt = "Press any key: "
key = io.read_char(promp) # read_char is an example name

print(f"You pressed the {key} key")
```

Thanks for taking my proposal into considerations.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by picnixz** [comment]
This feature is not a minor feature. We will need to make it platform-agnostic on our side so the workload might be non-trivial. It appears that https://stackoverflow.com/a/57503192/9579194 has a solution for you using tkinter (which Python supports if you install the external libraries, but it's not an external pip package per se). Alternatively, for Windows, you have the simple `msvcrt.getch` function and for UNIX, you can use `sys`, `tty` and `termios`: https://code.activestate.com/recipes/134892-getch-like-unbuffered-character-reading-from-stdin/.

If you want such feature in the standard library, please open a Discourse topic first: https://discuss.python.org/c/ideas/6.

Closing as `wontfix` for now. We will re-open this issue once it has gathered sufficient support from the community.

**Comment by foxypiratecove37350** [comment]
> This feature is not a minor feature. We will need to make it platform-agnostic on our side so the workload might be non-trivial. It appears that https://stackoverflow.com/a/57503192/9579194 has a solution for you using tkinter (which Python supports if you install the external libraries, but it's not an external pip package per se). Alternatively, for Windows, you have the simple `msvcrt.getch` function and for UNIX, you can use `sys`, `tty` and `termios`: https://code.activestate.com/recipes/134892-getch-like-unbuffered-character-reading-from-stdin/.
> 
> If you want such feature in the standard library, please open a Discourse topic first: https://discuss.python.org/c/ideas/6.
> 
> Closing as `wontfix` for now. We will re-open this issue once it has gathered sufficient support from the community.

I thought it was a minor feature, sorry.

**Comment by picnixz** [comment]
No worries! people (and myself included) always think that our features are minor but when you think more about it, the standard library does not want to have all small features inside it. It might be minor in size (and maybe in providing it) but we need to know whether it's useful or if users could live with a separate three-liner (well in this case it's not really a 3-liner but online resources tend to suggest that it's not that hard to implement).

**Comment by foxypiratecove37350** [comment]
I opened a topic on the Discuss for my proposal.

If there's any need for the devloppement, I can try to help. I practiced my C few time ago.

**Comment by hugovk** [comment]
> I opened a topic on the Discuss for my proposal.

For reference:

https://discuss.python.org/t/add-a-built-in-equivalent-of-cs-getch/61728
