### ISSUE TITLE
Creation of an internal decimal context for `_pylong` has side effects on `decimal`

### ISSUE THREAD

**Issue by picnixz** [python/cpython#123284]
# Bug report

### Bug description:

The `_decimal` module was recently fixed in #123243. I also found that `_pylong` leaks globals due to the creation of a global context to use as a local context:

```py
_unbounded_dec_context = decimal.getcontext().copy()
_unbounded_dec_context.prec = decimal.MAX_PREC
_unbounded_dec_context.Emax = decimal.MAX_EMAX
_unbounded_dec_context.Emin = decimal.MIN_EMIN
_unbounded_dec_context.traps[decimal.Inexact] = 1 # sanity check
```

This context is used as `with decimal.localcontext(_unbounded_dec_context)`. On the other hand `decimal.getcontext().copy()` returns a *copy* of the decimal context for the current thread (or set it to `decimal.DefaultContext` if none exists). Instead of setting it like that, I suggest that we construct a `decimal.Context()` object directly in `_pylong` instead of possibly polluting the `decimal` module (whether it's the C or the python implementation).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123285

**Comment by vstinner** [comment]
> _pylong leaks globals due to the creation of a global context to use as a local context

How do you see such leak?

**Comment by picnixz** [comment]
I just used `./python -X showrefcounts -c 'import _pylong'`. I don't really if it's the `_pylong` module itself that leaks or if it's the `decimal` module that leaks because `decimal.getcontext()` was called.

What I however know is that there is a side-effect on `decimal` because `_pylong` calls `decimal.getcontext()` and thus sets the decimal default's context. I'm not really sure whether it's an issue or not, but I was just looking at all `./python -X showrefcounts -c 'import MODULE'` for every module in `Lib` to see whether a module leaked or not. Feel free to close if you think this is a non-issue though.

**Comment by vstinner** [comment]
The problem is unrelated to `_pylong`, but related to decimal:

```
$ ./python -X showrefcount -c 'import decimal; decimal.getcontext()'
[207 refs, 138 blocks]
```

**Comment by picnixz** [comment]
Ok, one interrogation confirmed. I'll try to see what I can do tomorrow (not sure if I'll be able to though).

**Comment by picnixz** [comment]
So the reference leaks will be fixed by another PR. I won't bother about setting the decimal's default thread context?
