### ISSUE TITLE
Error when using VS2023 to build the interpreter

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#123294]
### Bug description:

Use VS2023 Community Edition to open PCbuild to build the py interpreter. After compiling, Is not found getpath.h appears, 
getpath.h does not really exist in the Python/frozen_modules directory
### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by rruuaanng** [comment]
getpath.h does not really exist in the Python/frozen_modules directory

**Comment by rruuaanng** [comment]
![屏幕截图 2024-08-25 205522](https://github.com/user-attachments/assets/0cb292be-faa3-44d1-b3d5-9f9f074bf7fe)

**Comment by aisk** [comment]
I can't reproduce the issue. Can you compile Python using the command line? Just run `PCbuild\build.bat -c Debug` in the root directory of the repository, and see if it builds successfully or fails. Then, paste the build log here.

For more information about building Python from the command line, see: https://devguide.python.org/getting-started/setup-building/ .

**Comment by rruuaanng** [comment]
> I can't reproduce the issue. Can you compile Python using the command line? Just run `PCbuild\build.bat -c Debug` in the root directory of the repository, and see if it builds successfully or fails. Then, paste the build log here.
> 
> 
> 
> For more information about building Python from the command line, see: https://devguide.python.org/getting-started/setup-building/ .

It been solved, thank
