### ISSUE TITLE
`super` builtin class

### ISSUE THREAD

**Issue by dongbohu** [python/cpython#123207]
# Documentation

I found the leading sentence in this paragraph a little misleading:
https://github.com/python/cpython/blob/ec89620e5e147ba028a46dd695ef073a72000b84/Doc/library/functions.rst?plain=1#L1961
because if the `object_or_type` is an object, it won't have `__mro__` attribute. The attribute should be `object.__class__.__mro__`.

On the other hand, if `object_or_type` is a type (class), then `__mro__` attribute does exist.

### Linked PRs
* gh-123417
* gh-123732
* gh-123733

**Comment by eendebakpt** [comment]
@dongbohu I agree it is a bit confusing. Maybe we can reformulate to something like

> The :attr:`~class.__mro__` attribute of the class corresponding to *object_or_type* lists the method ...

Maybe there are better suggestions, otherwise I will open a PR with this suggestion.

**Comment by dongbohu** [comment]
@eendebakpt: I think your proposed wording is much better. Thank you!
