### ISSUE TITLE
 PEP 617 consumes 2x RSS memory

### ISSUE THREAD

**Issue by xinsheng3** [python/cpython#123282]
# Feature or enhancement

### Proposal:

```python
import time


class MemoryCheck(object):
    @staticmethod
    def insert_packages():
        pass

    def setup(self):
        pass

    def process(self):
        pass

    def exit(self):
        pass


# copy total "class MemoryCheck(object)" for 512 times

if __name__ == "__main__":
    while True:
        time.sleep(10)

```

Copy the class in the preceding script for 512 times and verify the script.

[root@localhost ~]# python3 -V
Python 3.9.9
[root@localhost ~]# python3 test_512.py &
[4] 5715
[root@localhost ~]# pmap -x 5715|grep total
total kB           37256   16968   12176

------------------------------------------------------------------
[root@localhost ~]# python3 -V
Python 3.13.0b3+
[root@localhost ~]# python3 test_512.py &
[2] 2117463
[root@localhost ~]# pmap -x 2117463|grep total
total kB         1076668   31840   25384

python3.9    16968 KB
python3.13  31840KB,   2x memory difference

The difference in this RSS feed comes from this commit：
https://github.com/python/cpython/commit/c5fc15685202cda73f7c3f5c6f299b0945f58508

### Has this already been discussed elsewhere?

No response given

**Comment by Eclips4** [comment]
Hello!
PEP 617 says: "The cost of the memoization cache is that the parser will naturally use more memory than a simple LL(1) parser, which normally are table-based"
So I guess this behavior is excepted.

cc @pablogsal

**Comment by pablogsal** [comment]
Yeah, there is not much we can do here as this is the nature of the PEG parser with memoization. If you have concrete ideas or improvements I am happy to considet them but unfortunately a blanket issue it's not super valuable.
