### ISSUE TITLE
asyncio does not work properly in debug mode

### ISSUE THREAD

**Issue by zhoutaoq** [python/cpython#123251]
# Bug report

### Bug description:

```python
import asyncio
import sys
async def sample_coro():
    await asyncio.sleep(1)

print(sys.version_info)
print('----------------------------------------------------')
help(asyncio.Task)
print('----------------------------------------------------')
loop = asyncio.windows_events.ProactorEventLoop()
task = asyncio.Task(sample_coro(), loop=loop, eager_start=True)
print("ok")
```

When I start in "debug" mode, "help(asyncio.Task)" shows "asyncio.Task" without the "eager_start "parameter, resulting in the "TypeError: _patch_task.<locals>.task_new_init() got an unexpected keyword argument 'eager_start'", However, "asyncio.Task" in "run" mode has "eager_start" parameter, and it works properly

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
> When I start in "debug" mode

What do you mean by "debug" mode? Do you mean `python -d`? Also I can't find any reference to `_patch_task`. Did you use the latest version of Python 3.12? What is the output of `python -VV`?

**Comment by zhoutaoq** [comment]
I'm sorry I wasn't clear, but the debug mode I'm talking about is in pycharm, running as 'debug'
![企业微信截图_17244050322051](https://github.com/user-attachments/assets/3eb525a7-f119-408c-93a0-c2ab37eb6ad8)

**Comment by picnixz** [comment]
I think this is a PyCharm issue, which you likely need to report to pycharm then. What is the exact version of Python you are using? it might be the case that PyCharm is using another version as well. I found a reference to `_patch_task` but it's in 2022 so maybe the is some issue with the interpreter configuration?

**Comment by zhoutaoq** [comment]
> 我认为这是一个 PyCharm 问题，您可能需要向 pycharm 报告。您使用的 Python 的具体版本是什么？PyCharm 可能也在使用另一个版本。我找到了一个参考，`_patch_task`但它是 2022 年的，所以可能是解释器配置出了问题？

pycharm version: 2024.1.4
python version: 3.12.1
I tried to verify that there was a problem with the interpreter configuration, but was unsuccessful
Anyway, thanks for your reply.
