### ISSUE TITLE
New warnings: `  'initializing': conversion from '__int64' to 'int', possible loss of data [D:\a\cpython\cpython\PCbuild\pythoncore.vcxproj]`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#123205]
# Bug report

### Bug description:

Popped up in https://github.com/python/cpython/pull/123203/files

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-123206

**Comment by picnixz** [comment]
Ah I didn't see this one. I actually opened https://github.com/python/cpython/pull/123221 but I'm closing mine.
