### ISSUE TITLE
free-threading: set_default_allocator_unlocked is also exits on Linux

### ISSUE THREAD

**Issue by Zheaoli** [python/cpython#123295]
# Bug report

### Bug description:

About the environment

Kernel 

```text
Linux manjusaka-garuda 6.10.6-manjusakav4-xanmod1-1-manjusaka #1 SMP PREEMPT_DYNAMIC Fri, 23 Aug 2024 16:46:42 +0000 x86_64 GNU/Linux
```

ToolChain

```text
╰─ clang --version
clang version 18.1.8
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```

Distro: Garuda, a distro base on Arch

More detail, See https://gist.github.com/Zheaoli/23906655d0d8a05b53936c67915fd9eb

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123296

**Comment by picnixz** [comment]
Can we have more information (on your sample) on which distro it's being executed? we just know that something went wrong but it would be good to know the environment.

**Comment by Zheaoli** [comment]
> Can we have more information (i.e., update your gist) on which distro it's being executed? we just know that something went wrong but it would be good to know the environment.

Update in the gist

**Comment by picnixz** [comment]
(Closing as `not planned` since the OP is targetting the issue instead)
