### ISSUE TITLE
Never show deprectation messages via stderr - only log them only log once.

### ISSUE THREAD

**Issue by WolfgangFahl** [python/cpython#123307]
# Bug report

### Bug description:

Any python code i start might have some deprecated libraries that will make the actual output of my software hard to spot.
https://stackoverflow.com/questions/879173/how-to-ignore-deprecation-warnings-in-python
Discusses this in all detail and there is no proper standard fix available especially if you install scripts with pyprojec.toml.

I think the design must be changed to never ever use stderr or stdout without being explicitly asked to do so. The deprecation info needs to go to a standard place and be available on request so that in any environment an active deprectation check can be made. These deprecation messages may e.g. show on pip install or any other upgrade operation and generally warn "x deprecation issues to be solved ..." - if remember right npm works this way.

here is an example
```bash
wikiquery -d -l -s wiki -q "[[isA::Property]]" 2>&1 | grep -v "is deprecated"
  import pkg_resources
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('ruamel')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('sphinxcontrib')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/usr/local/lib/python3.10/dist-packages/pkg_resources/__init__.py:3144: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
ask:
[[isA::Property]]
{
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
This is not a bug. A warning is a kind of non-fatal exception and thus will be reported as such. You can however filter them as you want using `-W`: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONWARNINGS

In addition, the version being affected is 3.10, which only accepts security fixes. If you want to change the behaviour of warnings (e.g., by turning off the warnings filter by default), this should be discussed on Discourse first: https://discuss.python.org/c/ideas/6 (check whether there are existing discussions as well) (this requires a wider audience than what a GH issue could offer).

Closing as `wontfix`.

**Comment by WolfgangFahl** [comment]
Please reopen since you the filter option is exactly what i can not use easily at this point. It simply does not work as advertised and that is the bug that i am reporting. Just read the stackoverflow question and answers and take the frustration seriously. Won't fix will keep the frustration up.

**Comment by picnixz** [comment]
Yes, but this kind of feature requires more than an issue. For that, I'd suggest first a discourse discussion. We won't just make this change (we could be breaking CI/CDs). I'll gladly re-open it once the feature has sufficient support on Discourse.

**Comment by WolfgangFahl** [comment]
A link to discourse would be appreciated - i am not part of the core python community at this time and would not know which discourse is the one you are refering to.

**Comment by picnixz** [comment]
Sure! it would be the ideas topic: https://discuss.python.org/c/ideas/6

You just need to open a new topic (you can link this issue as well) but check whether there hasn't been a previous discussion on the matter first.

**Comment by WolfgangFahl** [comment]
see https://discuss.python.org/t/mitigating-python-deprecation-message-frustrations-by-improving-the-design-of-deprecation-message-handling/61985
