### ISSUE TITLE
sys.addaudithook

### ISSUE THREAD

**Issue by mwriter** [python/cpython#123390]
# Feature or enhancement

### Proposal:

```python

def audit_hook1(event, args):
	if event == "open":
		args[0] = "/new_path"
sys.addaudithook(audit_hook1)

def audit_hook2(event, func, args):
	if event == "open":
		func = open
		args = [ "/new_path", ]
		return func(*args)
sys.addaudithook(audit_hook2)

F = open("/path")
def audit_hook3(event, func, args):
	if event == "open" and args[0] == "/some_path":
		return F
sys.addaudithook(audit_hook3)
```

It seems to me that's possible to develop the idea with hooks and make them full-fledged.
I.e., allow to change the values of arguments or the final result of a call.
In its current form these are not essentially hooks but simply tracing and profiling.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by picnixz** [comment]
Hooks were standardized in [PEP 578](https://peps.python.org/pep-0578/) and thus I believe that any change to their scope should be discussed on Discourse first, namely here: https://discuss.python.org/c/ideas/6.

Those hooks were not meant for changing their arguments. They don't have priorities for instance, and are essentially for gathering information, and not meant to be handlers that could modify the values being passed over.

> Note that audit hooks are primarily for collecting information about internal or otherwise unobservable actions, whether by Python or libraries written in Python. They are not suitable for implementing a “sandbox”.

ref: https://docs.python.org/3/library/sys.html#sys.addaudithook

Closing as `wontfix` for now (sorry but this one is clearly not a minor feature).

**Comment by mwriter** [comment]
> Those hooks were not meant for changing their arguments

My job is just to suggest. Then think for yourself.
Hooks are a technique that allows to change the standard behavior of certain components. So it's a long way to real hooks.


> They are not suitable for implementing a “sandbox”.

Yeap, you immediately understood what I was getting at. After all, no independent sandbox has been created for python. This could be a real variant of what python lacks in terms of security.

> sorry but this one is clearly not a minor feature

No problem at all. I decided to just offer it as an opportunity to develop python to a new level. Further it's up to you :)

> Audit hooks are meant for auditing only.

The concept of hooks implies the possibility of a complete change in the behavior of the object to which hooks are applied.

**Comment by picnixz** [comment]
>  Hooks are a technique that allows to change the standard behavior of certain components. So it's a long way to real hooks.

Yes, but I don't think the goal for them was ever to be real hooks. Actually, you should suggest your ideas on Discourse. If there is enough support, we will be willing to add such support (though I think this should be another kind of hooks, not audit hooks).

> Moreover, it seemed to me that not many changes would be required there.

If you believe so, feel free to suggest an implementation as well as opening a discourse topic. I tend to close issues not because I don't want them, but because there are many ideas that need a wider audience in order to get feedback (my task is to redirect you where you could this audience, namely [discuss.python.org/c/ideas/6](https://discuss.python.org/c/ideas/6)).

**Comment by mwriter** [comment]
> Actually, you should suggest your ideas on Discourse

Why create an ecosystem of discussions around other forums if this is a great place to discuss. And you can create separate discussions. But this item is disabled in this repo for some reason.
And so it would be possible to transfer such topics there.

> If there is enough support, we will be willing to add such support (though I think this should be another kind of hooks, not audit hooks).

I understand. It just seemed more appropriate to rely on what already exists and has great potential.

> I tend to close issues not because I don't want them, but because there are many ideas that need a wider audience in order to get feedback

Understood, thanks. It seems to me that it is right to discuss this here, where the development process actually takes place.
The main thing is to leave your opinion for the future. And then let it be as it will be :)

**Comment by mwriter** [comment]
> They are not suitable for implementing a “sandbox”.

https://doc.pypy.org/en/latest/sandbox.html
And I also forgot to attach a link about the implementation of this in another python implementation.

**Comment by picnixz** [comment]
> Why create an ecosystem of discussions around other forums if this is a great place to discuss

This is the purpose of discourse (and the reason why issues have the question about whether the feature is minor or not, in the latter case, a Discourse thread is needed). If you want to discuss (or push for this feature), please discuss it on Discourse instead.

**Comment by mwriter** [comment]
> This is the purpose of discourse (and the reason why issues have the question about whether the feature is minor or not, in the latter case, a Discourse thread is needed)

In this case there is no point in discussing significance. Especially when there is such a thing in another python implementation. Then it's easier to open a new PEP right away :)
I was hoping to discuss it with the developers here. But your implementation - your rules :)
