### ISSUE TITLE
Document callables more explicitly

### ISSUE THREAD

**Issue by ryan-duve** [python/cpython#123392]
# Documentation

Currently, some options that expect callables [read like this in the documentation](https://docs.python.org/3/library/json.html#json.load):

> ```
> json.load(...)
> ```
>
> parse_constant, if specified, will be called with one of the following strings: '-Infinity', 'Infinity', 'NaN'. This can be used to raise an exception if invalid JSON numbers are encountered.

One potentially confusing interpretation of the above is "_if `parse_constant` is specific, then `json.load` will be called with..._".  It would be clearer if these were documented like the `object_hook` parameter right above it:

> object_hook is an optional function that will be called with the result...

This issue is being opened to tag a PR to that updates the documentation in this module like this:

```
<param>, if specified, will be called  ---->  <param> is an [optional] function that will be called
```

The goal is for the documentation to be more consistent and less likely for a user to misinterpret what will be called.

### Linked PRs
* gh-123394
* gh-123664
* gh-123665

**Comment by encukou** [comment]
The PRs are merged, I'll close the issue.
I'm not sure if you wanted to fix other docs than the `json` ones; if so we can reopen.
