### ISSUE TITLE
Setup failed 0x80070057 - The parameter is incorrect

### ISSUE THREAD

**Issue by juanamm** [python/cpython#123304]
# Bug report

### Bug description:
Hello,

A few days ago, I successfully installed Python 3.12.5 for Windows x64. I then completely uninstalled it. Today, I tried to reinstall it, but during the installation process, I accidentally pressed the cancel button. The installation was not completed, and now I am unable to reinstall Python. I receive the error "Setup failed 0x80070057 - The parameter is incorrect". I have attached the installation log for reference.
[Python 3.12.5 (64-bit)_20240825040658.log](https://github.com/user-attachments/files/16739348/Python.3.12.5.64-bit._20240825040658.log)

![python_setup_failed](https://github.com/user-attachments/assets/1d775eda-6daa-4fe2-a947-0f6b0ea9d380)

Any help would be greatly appreciated.
Thank you!

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
The issue seems to stem from here:

```text
[37D0:0B48][2024-08-25T04:06:58]e000: Error 0x80070057: Failed to convert version:  to DWORD64 for ProductCode: {0DC6C3A0-5CF6-46F6-B639-80DA74882478}
[37D0:0B48][2024-08-25T04:06:58]e151: Detect failed for package: lib_JustForMe, error: 0x80070057
```

**Comment by zooba** [comment]
Does the install appear in "Programs & Features" (also known as "Add and Remove Programs" or "Installed apps" depending on Windows version)? If so, can you "Modify" and then "Repair" it?

Failing that, you would probably have to search your registry for `{0DC6C3A0-5CF6-46F6-B639-80DA74882478}` (from the log that picnixz called out) and rename/remove any keys named that. It probably stopped uninstalling halfway through unregistering (somehow... that shouldn't be possible), and so completely removing where it's registered ought to handle it.

**Comment by juanamm** [comment]
In "Programs & Features" on Windows, there is no reference to the Python installation, so I cannot modify, repair or uninstall anything.

While searching the Windows registry for `{0DC6C3A0-5CF6-46F6-B639-80DA74882478}`, I found two keys identical to this one: `windows.data.apps.appmetadata${0dc6c3a0-5cf6-46f6-b639-80da74882478}`
in the path: `Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\CloudStore\Store\DefaultAccount\Cloud{*****fb7-7a64-4a74-8d41-51**********}$windows.data.apps.appmetadata$appmetadatalist\windows.data.apps.appmetadata${0dc6c3a0-5cf6-46f6-b639-80da74882478}`

What I did first was back up that registry key and then rename it to: `windows.data.apps.appmetadata${0dc6c3a0-5cf6-46f6-b639-80da74882478}_backup`

I tried reinstalling Python, and the error persists, so I decided to delete those keys completely, restart the system, and attempt to reinstall, but that didn’t work either.

Since I have no issues installing the previous version of Python 3.12.4, I have decided not to attempt installing 3.12.5 and will wait for a new version in the future that I can install.

Something is failing in the 3.12.5 setup that, if we cancel the installation before it finishes, causes this error.

If no one can think of another solution, you can close this "bug" and consider it resolved.

Let me know if you need any further adjustments!

Thank you @picnixz and @zooba for the help provided.

**Comment by zooba** [comment]
Last thing to try would be to open Powershell and run `Get-Package *python*` to see what it thinks is installed.

(We _might_ try doing `Uninstall-Package (Get-Package ...)` to remove them, but you need to be really careful with how you fill out that `...` to avoid messing up your machine more. Right now, I mainly want to see if there are any 3.12.5 MSIs installed at all.)

**Comment by juanamm** [comment]
Unfortunately no Python package was found.
`Get-Package *python*`
Result: `No package found for *python*'.`

![powersell](https://github.com/user-attachments/assets/59b76db8-ef8b-4ac6-a36a-8972b9c40a8b)


Thanks for the help.

**Comment by zooba** [comment]
I'm out of ideas then. Maybe double-check your Downloads folder for other `*.msi` files in case it's finding another one, but even in that case it shouldn't result in this error - it'd be a different one later during install.

If you or someone else comes up with a way to make this reoccur, it would be interesting to see a second set of logs, but until then I think we just have to close it.

**Comment by juanamm** [comment]
I successfully installed version 3.12.4 without any errors. After that, I tried installing the 3.12.5 update, but the same error persists. I hope that when a newer version is released, I'll be able to install it. Otherwise, I might have to stick with version 3.12.4. I've attached images of the installed version and a new log. My intention is not to reopen this thread, but just to inform you of what happened. Thank you very much

![python_version](https://github.com/user-attachments/assets/de80b874-3cdf-4c9b-b0dc-3814d2399918)
[Python 3.12.5 (64-bit)_20240828210906.log](https://github.com/user-attachments/files/16790289/Python.3.12.5.64-bit._20240828210906.log)

**Comment by zooba** [comment]
Yeah, hopefully you've gotten stuck with a corrupt cache of the 3.12.5 installer, and when 3.12.6 comes out it'll get the right one. I don't see anything unusual in the file that's failing to parse, and nobody else has reported this, so hopefully a fresh installer will work for you.
