### ISSUE TITLE
CONTAINS_OP can provide the operation name

### ISSUE THREAD

**Issue by Alexandr153** [python/cpython#123363]
# Feature or enhancement

### Proposal:

When referring to the ```in``` and ```not in``` operator, the dis module does not display in ```COMPARE_OP``` which operator is being used

```python
>>> dis.dis('a in b')
  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (a)
              4 LOAD_NAME                1 (b)
              6 CONTAINS_OP              0
              8 RETURN_VALUE

>>> dis.dis('a not in b')
  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (a)
              4 LOAD_NAME                1 (b)
              6 CONTAINS_OP              1
              8 RETURN_VALUE
```

But if we look at the output of many other operators, we see explicit notation there:

```
>>> dis.dis('a + b')
  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (a)
              4 LOAD_NAME                1 (b)
              6 BINARY_OP                0 (+)
             10 RETURN_VALUE
>>> dis.dis('a==b')
  0           0 RESUME                   0

  1           2 LOAD_NAME                0 (a)
              4 LOAD_NAME                1 (b)
              6 COMPARE_OP              40 (==)
             10 RETURN_VALUE
             
```

              

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-123387

**Comment by sobolevn** [comment]
Refs https://github.com/python/cpython/issues/123340

@Alexandr153 do you want to work on this? :)

**Comment by Alexandr153** [comment]
> Refs #123340
> 
> @Alexandr153 do you want to work on this? :) I would be happy to help.

Yes, I already tried to modify the module and it worked, but I think it is not the best option. I could look into the code in more detail, with your approval

**Comment by sobolevn** [comment]
You can take a look at https://github.com/python/cpython/pull/123348 It does a very similar thing.
