### ISSUE TITLE
Ambiguous error when using the same type defined in a different module.

### ISSUE THREAD

**Issue by manavsu** [python/cpython#123351]
# Bug report

### Bug description:

Parameter to MergeFrom() must be instance of same class: expected flywheel_threshold_symptom_pb2.FlywheelThresholdSymptomProto got flywheel_threshold_symptom_pb2.FlywheelThresholdSymptomProto.
  File "C:\code\autohealth\DemoHealthEvents.py", line 45, in make_symptom
    flywheel_symptom.flywheel_threshold_symptom.CopyFrom(threshold_symptom)
  File "C:\code\autohealth\DemoHealthEvents.py", line 66, in <module>
    my_symptom = make_symptom()
                 ^^^^^^^^^^^^^^
TypeError: Parameter to MergeFrom() must be instance of same class: expected flywheel_threshold_symptom_pb2.FlywheelThresholdSymptomProto got flywheel_threshold_symptom_pb2.FlywheelThresholdSymptomProto.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
This does not appear to be a CPython issue. Please give us the code that is causing an issue and why you believe it is a CPython issue.

**Comment by Eclips4** [comment]
Closing since there's no response from the OP.
