### ISSUE TITLE
Allow double-click on dialog.list_menu

### ISSUE THREAD

**Issue by LucMorizur** [python/cpython#123312]
# Feature or enhancement

### Proposal:

The choices displayed in dialog.list_menu can't be chosen with a double-click. You have to click once on the choice you make, and then click on button "OK" so to validate your choice. This makes two actions, when it would be possible to validate your choice with only one action — ie the double-click.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ZeroIntensity** [comment]
I'm not aware of Python having anything named `list_menu` in the stdlib. What is `dialog` here? I'm guessing this isn't a CPython issue.

**Comment by picnixz** [comment]
This was filed in https://github.com/autokey/autokey/issues/954 and I think it is something related to AHK only: https://github.com/autokey/autokey/blob/d8211b9a5f6d381e80410e0def506af4f332003e/lib/autokey/scripting/dialog_qt.py#L103. Closing as a `non CPython issue` (I've also checked the curses module and couldn't find anything related to it).

**Comment by LucMorizur** [comment]
Many thanks for your very fast answer. Yes indeed I first opened this issue on Autokey project. But after having done so, I thought that it was not something related to Autokey software, but with Python which is used by Autokey. Reading your first answer, I searched in the code used by Autokey, and found that list_menu in Autokey Python files, is using subprocess.Popen object, defined in cpython/Lib/subprocess.py . So maybe after all this enhancement request is indeed properly to be addressed to CPython project?
Many thanks for your reading and advices.

**Comment by ZeroIntensity** [comment]
AHK is written in Python, yeah. It uses `subprocess.Popen` to do whatever it needs, but there's nothing that CPython could do, since this is a downstream feature.

**Comment by LucMorizur** [comment]
Well, as Popen object is defined in a CPython module, I guess this is the place where its behaviour can be modified? As I understand it, it is not the _usage_ of this object which needs to be modified, so to change the final behaviour, but indeed the object itself, so that it can deliver the same result, whether the final user single-clicks on an item and clicks OK, or double-clicks on the item.

**Comment by terryjreedy** [comment]
The binding of user interface actions to invoke code is done in whatever GUI framework AHK is using and is entirely the responsibility of the AHK authors.

**Comment by LucMorizur** [comment]
OK, thank you [terryjreedy](https://github.com/terryjreedy) for the precision; sorry for this bad usage of ticket opening, I should have had the discussion first on a community forum.
