### ISSUE TITLE
Memory leak of `NoDefaultType` in `_typing`

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#123448]
# Bug report

### Bug description:

Quick reproducer:

```
$ ./python -X showrefcount -c "import _typing"
[8 refs, 0 blocks]
```

The underlying leaked object is `NoDefaultType`. I think this was caused by gh-118897 (cc @JelleZijlstra).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123449
* gh-123450

**Comment by JelleZijlstra** [comment]
Thanks!
