### ISSUE TITLE
Extract ZipInfo for archive functionality

### ISSUE THREAD

**Issue by jaraco** [python/cpython#123424]
In https://github.com/python/cpython/pull/123354, I found the need to copy code from zipfile into the test:

https://github.com/python/cpython/blob/9e108b8719752a0a2e390eeeaa8f52391f75120d/Lib/test/test_zipfile/_path/test_path.py#L662-L676

Let's instead extract that functionality in the zipfile module for re-use in the test (before it starts diverging).

### Linked PRs
* gh-123429

**Comment by jaraco** [comment]
Originally, I was planning to do it, but then I realized it might be an interesting one for others. Have at it!

**Comment by serhiy-storchaka** [comment]
See also #121402 that implements a similar feature.

I paused it because I am planning to try a different approach.

**Comment by obfusk** [comment]
Nothing against extracting the functionality if it's useful elsewhere, but the test doesn't actually depend on the compression or any of the metadata set by `for_name()`, just the file name. Nothing else should matter to `zipfile.Path` here. So removing `for_name()` and just using `zf.writestr(DirtyZipInfo("foo\\bar"), b"content")` should work fine.

**Comment by jaraco** [comment]
When I added the `for_name` to `DirtyZipInfo`, I was aiming to replace `writestr` without altering the way it worked. That is, every other test relies on `writestr`, so I wanted to construct an equivalent ZipInfo, assuming that whoever wrote `writestr` had reasons for defaulting the date_time, compression type, compression level, and external attrs. I wanted to avoid having to research the motivations for each of those concerns to see if they may apply to this specific case. I wanted to avoid the possibility that those attributes had a meaningful effect or worse did not have an effect today but would in the future. More importantly, I wanted to be sure that if writestr changed in the future to add additional behavior, this routine would inherit that same behavior. By reducing incidental variance, we improve reliability long-term.

**Comment by obfusk** [comment]
Passing a `ZipInfo` to `writestr()` will not set any of those attributes like passing only a filename (and thus having `writestr()` create the `ZipInfo`) will and is clearly supported as part of the current API. I rely on this regularly for Reproducible Builds where I need to set the attributes to specific values and using the current time would definitely be unacceptable.

And the fact that `writestr()` by default uses the current time means no two test runs ever use the exact same metadata, which is something I would generally try to avoid.

That said, even if I very much doubt any of the metadata would ever affect this specific test, and would consider that changing to be a bug, I agree that ensuring consistency wrt to `writestr()` behaviour between different tests is good. Just wanted to clarify the current situation :)

**Comment by picnixz** [comment]
Removing my assignment on this task since I didn't continue working on the associated PR (and have to prioritize my backlog).
