### ISSUE TITLE
TCP_QUICKACK is available on Windows, but is only implemented by the python runtime for Linux

### ISSUE THREAD

**Issue by nkinnan** [python/cpython#123476]
# Bug report

### Bug description:

```python
import socket
sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_QUICKACK, 1)
sock.getsockopt(socket.IPPROTO_TCP, socket.TCP_QUICKACK)
```

On windows this throws `AttributeError: module 'socket' has no attribute 'TCP_QUICKACK'`

Support is for this setting is available on windows, it just isn't implemented in the python runtime.  It's implemented for Linux and I believe for Mac as well, though I didn't check the latter.

I'm opening this mostly to track my PR as I already have the fix implemented.

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-123478

**Comment by vstinner** [comment]
Implemented by https://github.com/python/cpython/commit/b5aa271f86229f126c21805ff2bd3b95526818a4.
