### ISSUE TITLE
Incorrect ipaddress.ip_address.reverse_pointer with improved textual representation of IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by kellyjonbrazil** [python/cpython#123409]
# Bug report

### Bug description:

I'm seeing strange results with python 3.13 with the `ipaddress.ip_address.reverse_pointer` attribute with the new improved textual representation of IPv4-mapped IPv6 addresses:

IP Address: `::FFFF:192.168.1.35`

Results in a `reverse_pointer` of:

`5.3...1...8.6.1...2.9.1.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa`

instead of the old:

`3.2.1.0.8.a.0.c.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa`

Python 3.13:
```python
>>> import ipaddress
>>> ip = '::FFFF:192.168.1.35'
>>> ipaddress.ip_address(ip).reverse_pointer
'5.3...1...8.6.1...2.9.1.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'
```

Python 3.12:
```python
>>> import ipaddress
>>> ip = '::FFFF:192.168.1.35'
>>> ipaddress.ip_address(ip).reverse_pointer
'3.2.1.0.8.a.0.c.f.f.f.f.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa'
```

I'm not sure which one is more valid or if a pointer record is even relevant in the context of mapped addresses. The original way *seems* more correct to me if nothing for the fact that there are strange extra dots in the new output.

This is related to:

Issue: https://github.com/python/cpython/issues/87799

PR: https://github.com/python/cpython/pull/29345

_Originally posted by @kellyjonbrazil in https://github.com/python/cpython/issues/87799#issuecomment-2264098846_

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

@opavlyuk

### Linked PRs
* gh-123419
* gh-123606
* gh-135085
* gh-135086
* gh-135087
* gh-135088

**Comment by opavlyuk** [comment]
@kellyjonbrazil Godd catch! Thank you for logging that, and I apologize for missing it during testing.
@picnixz thank you for taking care of this!

**Comment by encukou** [comment]
Thanks @kellyjonbrazil for the report and @picnixz for the patch!

**Comment by picnixz** [comment]
You're welcome! (I hope that I didn't misread the RFC because it doesn't tell anything about mapped addresses; however I assumed that we first map IPv4 to IPv6 before rendering it, which is what was being done in 3.12.5)
