### ISSUE TITLE
Add type annotations to `secrets` module

### ISSUE THREAD

**Issue by EarlMilktea** [python/cpython#123479]
# Feature or enhancement

### Proposal:

As this module is very small, I'd like to submit a PR unless there're specific reasons to leave it untyped.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
We don't generally add type annotations for the standard library. Types for the secrets module are maintained [in typeshed](https://github.com/python/typeshed/blob/main/stdlib/secrets.pyi).

**Comment by EarlMilktea** [comment]
@JelleZijlstra

I see. Thank you for quick reply!
