### ISSUE TITLE
PyExc_IOError is initialised to NULL

### ISSUE THREAD

**Issue by jefflaing** [python/cpython#123486]
# Bug report

### Bug description:

According to https://docs.python.org/3.12/c-api/exceptions.html#index-6, PyExc_IOError is supposed to be a "compatibility alias to PyExc_OSError"

Running in the debugger confirms that it contains a NULL.

Spelunking the 3.12.4 sources cannot see any place where it is initialised.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by rruuaanng** [comment]
> # Bug report
> ### Bug description:
> 
> According to https://docs.python.org/3.12/c-api/exceptions.html#index-6, PyExc_IOError is supposed to be a "compatibility alias to PyExc_OSError"
> 
> Running in the debugger confirms that it contains a NULL.
> 
> Spelunking the 3.12.4 sources cannot see any place where it is initialised.
> ### CPython versions tested on:
> 
> 3.12
> ### Operating systems tested on:
> 
> Windows

Hey Jefflaing  
you mentioned PyExc_IOError wasn't initialized. I found it on line 21 of the exceptions.c file.

"""
Objects/exceptions.c: PyObject *PyExc_IOError = NULL;"
"""

**Comment by ronaldoussoren** [comment]
It is initialised in Objects/exceptions.c, ``INIT_ALIAS(IOError, OSError);``:

https://github.com/python/cpython/blob/0181aa2e3efedc6504b27f6fe74f096e5e454286/Objects/exceptions.c#L3791-L3805


Did you run into an issue where the value was ``NULL`` at runtime (after initialising)?

**Comment by jefflaing** [comment]
Hmmm, I'm pretty sure that when I copied the value of the global it was NULL - I'll have to double-check that my timing was not off - perhaps I managed to grab it before Py_Initialize had been run.  This is an old 2.7.6 extension that I am porting - perhaps it was statically populated back then...

**Comment by jefflaing** [comment]
Yes, the fact that it isn't populated until after Py_Initialize is what threw me.  The old codebase relied on a lot of these globals having static references to the underlying structures already in place.  I think I would have expected a #define to make that value a synonym of the other global, rather than a copy, but there ya go.
