### ISSUE TITLE
calendar.day_name returns a class object and not array

### ISSUE THREAD

**Issue by sspTest** [python/cpython#123445]
# Documentation

In the https://docs.python.org/3/library/calendar.html#calendar.day_name, its mentioned day_name returns "An array that represents the days of the week in the current locale." but it returns a class object. Also, it would be helpful to provide documentation with regards to how to use the object returned to obtain the day names.

### Linked PRs
* gh-123483
* gh-124500
* gh-124501

**Comment by m4t5** [comment]
Confirmed
`$python3
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.

import calendar
calendar.day_name
<calendar._localized_day object at 0x7fd3b687a020>

[x for x in calendar.day_name]
['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
`

**Comment by serhiy-storchaka** [comment]
`day_name` was a list, but then it was changed to a custom sequence in bpo-401842 (gh-33318).

We just need to change "array" to "sequence". The same for `day_abbr`, `month_name` and `month_abbr`.

We can also add more human readable repr for these sequences. But this is only for a new version.

**Comment by ericvsmith** [comment]
I agree with @serhiy-storchaka that there's no need to be more specific than "sequence". I don't see the need to be more specific here and constrain any future changes.

**Comment by m4t5** [comment]
I made a PR at https://github.com/python/cpython/pull/123483
