### ISSUE TITLE
Typo: global -> local

### ISSUE THREAD

**Issue by nissa-seru** [python/cpython#123406]
# Documentation

Bolded word in the snippet below should read 'local' instead of 'global'.

----

[What are the rules for local and global variables in Python?](https://docs.python.org/3/faq/programming.html#id10)
In Python, variables that are only referenced inside a function are implicitly **global**. If a variable is assigned a value...

**Comment by JelleZijlstra** [comment]
The existing text is correct, though it could be made clearer. A variable is implicitly global if it's only *read* within a function; it is local if it is *written* anywhere within the function.

**Comment by nissa-seru** [comment]
Apologies and thank you.
