### ISSUE TITLE
Unneccessary ast optimization

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#123403]
# Bug report

### Bug description:

AST optimizer is trying to optimize ``target`` of the following statements:
* `del` statement (`del a`) - target is a [target_list](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-target_list)
* Assign statement (``a = b``) target is a [target_list](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-target_list)
* AugAssign statement (``a += b``) target is a [augtarget](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-augtarget)
* AnnAssign statement (``a: int`` or ``a: int = 1``) target is a [augtarget](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-augtarget)
* TypeAlias statement (``type A = int``) target is a [identifier](https://docs.python.org/3/reference/lexical_analysis.html#grammar-token-python-grammar-identifier)
* For statement (``for a in b: pass``) target is a [target_list](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-target_list)
* Async for statement (``async for a in b: pass``) target is a [target_list](https://docs.python.org/3/reference/simple_stmts.html#grammar-token-python-grammar-target_list)

None of these targets contain anything that can be optimized.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123404

**Comment by JelleZijlstra** [comment]
Many (probably all) of these can in fact be optimized.

```
>>> ast.dump(ast.parse("del [1, 2][0 + 1]"))
'Module(body=[Delete(targets=[Subscript(value=List(elts=[Constant(value=1), Constant(value=2)], ctx=Load()), slice=BinOp(left=Constant(value=0), op=Add(), right=Constant(value=1)), ctx=Del())])])'
>>> ast.dump(ast.parse("del [1, 2][0 + 1]", optimize=1))
'Module(body=[Delete(targets=[Subscript(value=List(elts=[Constant(value=1), Constant(value=2)], ctx=Load()), slice=Constant(value=1), ctx=Del())])])'
```

**Comment by JelleZijlstra** [comment]
I think the only exception is the name of a type alias; that really can only be a name. But even then I'm not sure it's worth skipping the AST optimizer; it's useful to have it recurse into everything so we don't have to think about whether we're missing something.

**Comment by Eclips4** [comment]
> I think the only exception is the name of a type alias; that really can only be a name. But even then I'm not sure it's worth skipping the AST optimizer; it's useful to have it recurse into everything so we don't have to think about whether we're missing something.

I'm agree with you in general, but I'd like to skip AST optimization on a type alias :) Not a big deal, though.

Also, these optimizations that are related to assignments (as you have shown above with a del statement) haven't been tested. Do you think they're worth testing?

**Comment by JelleZijlstra** [comment]
> Do you think they're worth testing?

No strong opinion. I guess in theory we could test every AST node in the optimizer tests but that feels a bit repetitive.

**Comment by Eclips4** [comment]
I'm going to close this issue; I may open another issue about testing ast optimizations.
