### ISSUE TITLE
Remove unnecessary `:func:` parentheses

### ISSUE THREAD

**Issue by mattwang44** [python/cpython#123492]
# Documentation

The func role's parentheses are unnecessary as Sphinx will add them to the rendered output.

```rst
.. bad
:func:`!locale.resetlocale()`

.. good
:func:`!locale.resetlocale`
```

We're introducing a new rule to the sphinx-lint ([issue](https://github.com/sphinx-contrib/sphinx-lint/issues/114) & [PR](https://github.com/sphinx-contrib/sphinx-lint/pull/115)) and, since sphinx-lint utilizes CPython Docs in the CI, we'd like to also fix the issue.

### TODO:
- [x] fix on main branch
- [x] backport to 3.12
- [x] backport to 3.13

### Linked PRs
* gh-123493
* gh-123512
* gh-123513

**Comment by hugovk** [comment]
Thanks!
