### ISSUE TITLE
localeconv() returns a few int fields instead of bool

### ISSUE THREAD

**Issue by srittau** [python/cpython#123437]
# Feature or enhancement

### Proposal:

`locale.localeconv()` returns a `dict` with a few well-defined fields, copied over from the C stdlib call of the same name. A few of these fields, which are clearly intended to be booleans, currently return either `0` or `1`. The lines in question were last touched 24 years ago, so I assume that they precede the introduction of the `bool` type in Python. The following fields should be converted to `bool`:

* `p_cs_precedes`
* `n_cs_precedes`
* `p_sep_by_space`
* `n_sep_by_space`

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-123438

**Comment by ericvsmith** [comment]
Is it worth it to change these? Is it causing some practical problem? I know it's unlikely, but every change has the potential to break someone's code, and it needs to be worth the risk and churn.

**Comment by srittau** [comment]
I've just noticed that these fields can also be `CHAR_MAX` (i.e. 127) when using the C locale. So this won't work. Sorry for the noise.
