### ISSUE TITLE
Add `:root { color-scheme: light dark; }` to http.server directory list and error pages

### ISSUE THREAD

**Issue by YorikHansen** [python/cpython#123430]
# Feature or enhancement

### Proposal:

Allow browsers to apply light or dark themes to the http.server directory list according to the users prefered color scheme.

This can be done by adding the CSS [`color-scheme` property](https://developer.mozilla.org/en-US/docs/Web/CSS/color-scheme) to `:root` with the value `light dark`.

```css
:root {
    color-scheme: light dark;
}
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

Something similar was discussed previously in #95812. There it was [rejected](https://github.com/python/cpython/issues/95812#issuecomment-1209057716), as "[t]he listing [should] not contain any hardcoded colors". 

I agree with this statement, but I think the page should allow browsers to select their own color scheme and don't see it as a "a problem either with [the] configuration or with the browser", as long as the `color-scheme` property is not set properly.

### Linked PRs
* gh-123475

**Comment by picnixz** [comment]
I think we want to keep the HTML content the simplest as possible. While the feature you suggest is minor, if we accept it, then people might want to push for more things inside this method (e.g., custom colors passed as arguments, additional content, etc) but I believe that this method should be as simple as possible.

cc @serhiy-storchaka as the one that closed the other issue.

**Comment by ZeroIntensity** [comment]
I could see this being considered a bugfix instead of a feature, FWIW -- users might think that it's a bug for `http.server` to not use their default color scheme.

**Comment by hugovk** [comment]
PR at https://github.com/python/cpython/pull/123475.

**Comment by serhiy-storchaka** [comment]
I wonder why browsers do not set this by default?

**Comment by ZeroIntensity** [comment]
I would assume that it's because support for dark mode is lost the moment you change any colors with CSS.
