### ISSUE TITLE
`PyArg_UnpackTuple` is used with `name=""`

### ISSUE THREAD

**Issue by denballakh** [python/cpython#123446]
# Bug report

### Bug description:

`PyArg_UnpackTuple(args, "",` causes empty name to be used in error messages:
```py
>>> str.join.__get__()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError:  expected at least 1 argument, got 0
#         ^^

>>> try: str.join.__get__()
... except Exception as e: exc = e
...
>>> str(exc)
' expected at least 1 argument, got 0'
#^
```

According to my quick search, `PyArg_UnpackTuple(args, "",` is used 10 times in `Objects/typeobject.c` and 3 times in `Modules/_csv.c`.

### CPython versions tested on:

3.12, CPython main branch

### Linked PRs
* gh-123461
* gh-123462
* gh-123466
* gh-123470

**Comment by serhiy-storchaka** [comment]
I agree, this is a misuse. The right use is to pass NULL as the name, or better provide some related name if this is possible.

**Comment by sobolevn** [comment]
Thanks for the report! 👍
