### ISSUE TITLE
`--with-mimalloc` doesn't enable mimalloc

### ISSUE THREAD

**Issue by mdboom** [python/cpython#123477]
# Bug report

### Bug description:

I wanted to benchmark the performance of using mimalloc vs. pymalloc, but got tripped up the configuration of mimalloc.  (I understand mimalloc is required by and working with free-threaded builds, I wanted to measure its effect on a single-threaded GIL build). I'm not sure what the intended behavior is here, so not sure whether to classify it as a bug or not.

The `./configure --help` message for `--with-mimalloc` says:

```
--with-mimalloc         build with mimalloc memory allocator (default is yes
                        if C11 stdatomic.h is available.)
```

This builds with the mimalloc library, but does not actually enable it for use.  I realize that's exactly what the help string says, but it was a bit subtle and tripped me up.  Does it make sense to be building this in by default (on modern compilers), even if it's not being used?  How does one enable it otherwise?  I ended up making this patch:

```diff
diff --git a/Include/internal/pycore_pymem_init.h b/Include/internal/pycore_pymem_init.h
index c593edc86d9..1bee24e50e2 100644
--- a/Include/internal/pycore_pymem_init.h
+++ b/Include/internal/pycore_pymem_init.h
@@ -18,7 +18,7 @@ extern void * _PyMem_RawRealloc(void *, void *, size_t);
 extern void _PyMem_RawFree(void *, void *);
 #define PYRAW_ALLOC {NULL, _PyMem_RawMalloc, _PyMem_RawCalloc, _PyMem_RawRealloc, _PyMem_RawFree}

-#ifdef Py_GIL_DISABLED
+#if defined(Py_GIL_DISABLED) || defined(WITH_MIMALLOC)
 // Py_GIL_DISABLED requires mimalloc
 extern void* _PyObject_MiMalloc(void *, size_t);
 extern void* _PyObject_MiCalloc(void *, size_t, size_t);
diff --git a/Objects/obmalloc.c b/Objects/obmalloc.c
index dfeccfa4dd7..dadf11a9dd4 100644
--- a/Objects/obmalloc.c
+++ b/Objects/obmalloc.c
@@ -307,7 +307,7 @@ void* _PyObject_Realloc(void *ctx, void *ptr, size_t size);
 #  define PYMALLOC_ALLOC {NULL, _PyObject_Malloc, _PyObject_Calloc, _PyObject_Realloc, _PyObject_Free}
 #endif  // WITH_PYMALLOC

-#if defined(Py_GIL_DISABLED)
+#if defined(Py_GIL_DISABLED) || defined(WITH_MIMALLOC)
 // Py_GIL_DISABLED requires using mimalloc for "mem" and "obj" domains.
 #  define PYRAW_ALLOC MALLOC_ALLOC
 #  define PYMEM_ALLOC MIMALLOC_ALLOC
```

This patch, of course, would enable mimalloc by default for most users, and I'm not sure whether that's the intent or not.

Thoughts?

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by colesbury** [comment]
In the default build it can be enabled with the environment variable `PYTHONMALLOC=mimalloc`

https://docs.python.org/3.13/using/cmdline.html#envvar-PYTHONMALLOC

(In the free-threaded build mimalloc is always used)

**Comment by mdboom** [comment]
Oh, thanks.  I'll close this as just me not understanding how this is supposed to work...
