### ISSUE TITLE
_Py_DebugOffsets for PyLongObject are incorrect

### ISSUE THREAD

**Issue by godlygeek** [python/cpython#123484]
# Bug report

### Bug description:

All other debug offsets are relative to the start of the object, but the offsets for PyLongObject's fields are relative to the start of an inner object, and so each field's value is too small by `sizeof(PyObject)`.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123485
* gh-123499

**Comment by picnixz** [comment]
I believe this one can be closed, or is there something else to do?
