### ISSUE TITLE
sorted function failed

### ISSUE THREAD

**Issue by queency3** [python/cpython#123490]
# Bug report

### Bug description:

```python
a=[{'rowid': 136, 'class_symbol': '1060', 'peula_date': 20240618, 'hour': 1, 'class_id': 'z3', 'class_protocol': 'חינוך גופני הוקי הולה הופ עמידה על כריות', 'link': ''}, {'rowid': 146, 'class_symbol': '10', 'peula_date': 'None', 'hour': 20240624, 'class_id': '2', 'class_protocol': 'g', 'link': 'הזמנת ספר מניב בוקס המסע המופלא של אמילי'}]

sorted(a, key=lambda k: k['peula_date'] , reverse = True)
```

Error:
```
File "/home/yair/home_dir/code/school/back_end/transaction.py", line 47, in convert_peulot_tuple_to_list
    a = sorted(myList, key=lambda k: k['peula_date'] , reverse = True)
TypeError: '<' not supported between instances of 'int' and 'str'
```
*** system ***
=================
Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
[GCC 10.2.1 20210110] on linux

*** remark ***
================
i don't know the cpython version i'm at if any 
and i didn't tested it on cpython !!
i just wanted to sumup and send this bug 

### CPython versions tested on:

3.9

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
Hello.
Type of value of the key `peula_date` must be the same (or comparable with other types) in each dict.
So, there's no bug.

This repository is intended as a CPython bug tracker, please ask python-related questions there: https://discuss.python.org/c/users/7

**Comment by queency3** [comment]
you right !
