### ISSUE TITLE
`PyMapping_Check()` returns 1 for strings and bytes and bytearray

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#123482]
# Bug report

### Bug description:

`types.MappingProxyType` allows to test this easily:

```python
>>> from types import MappingProxyType
>>> MappingProxyType(""), MappingProxyType(b""), MappingProxyType(bytearray())
(mappingproxy(''), mappingproxy(b''), mappingproxy(bytearray(b'')))
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
Why is this a bug? Strings are mappings from integers to strings. The docs [say](https://docs.python.org/3/c-api/mapping.html#c.PyMapping_Check) that the function returns true for Python classes with `__getitem__`; they don't say explicitly that C classes which support subscripting using `mp_subscript` are also considered mapping, but I'm not sure how we could distinguish them reliably.

**Comment by nineteendo** [comment]
Yeah, but I want to implement `isinstance(obj, collections.abc.Mapping)` in C.

**Comment by nineteendo** [comment]
I also don't understand why this doesn't count for list.

**Comment by JelleZijlstra** [comment]
Then `PyMapping_Check` is not the right thing to use. Despite the similar names, they check for very different things. To write in C `isinstance(obj, collections.abc.Mapping)`, you can use import/attribute APIs to get a hold of the `collections.abc.Mapping` class, then use https://docs.python.org/3/c-api/object.html#c.PyObject_IsInstance to do the `isinstance` check.

**Comment by nineteendo** [comment]
Yeah, I already feared that. I guess I won't bother then.
