### ISSUE TITLE
Possibility to add host to URI returned by `Path.as_uri()`

### ISSUE THREAD

**Issue by pekkaklarck** [python/cpython#123598]
# Feature or enhancement

### Proposal:

[Path.as_uri()](https://docs.python.org/3/library/pathlib.html#pathlib.PurePath.as_uri) currently always returns URIs with the `file:///` prefix and omits the host component of the file URI scheme (see [RFC 8089](https://datatracker.ietf.org/doc/html/rfc8089) for the full spec or [Wikipedia](https://en.wikipedia.org/wiki/File_URI_scheme) for simpler documentation). Omitting the host is often fine, but in some cases it should be included. My concrete use case is creating terminal hyperlinks where the [spec](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#file-uris-and-the-hostname) recommends [including the host component](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#file-uris-and-the-hostname).

My proposal is to add an optional argument to `Path.as_uri()` to allow adding the host. There could either be something like `include_host: bool = False` to enable adding the host name returned by `socket.getfqdn()` or `host: str|None = None` to make it possible to explicitly specify the host name to use. The former would be more convenient to use in the common case, and would be enough in my immediate use case, but the latter would be more flexible.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by pekkaklarck** [comment]
UNC paths complicate this on Windows and i believe this would in general be more useful on POSIX.

After thinking this a bit more, my implementation proposal is:
1. Add `host: str|None = None` (or `hostname`) argument. Let the user call `socket.getfqdn()` or whatever works for them.
2. If there's no host component in the generated URI, add it.
3. If there already is a host component, either replace it or raise a ValueError. I believe this can happen only with UNC paths.

Although I believe being able to add the host component makes sense in general, and the above approach ought to work fine, this might anyway be too niche to be added. In my [use case with terminal hyperlinks]( https://github.com/robotframework/robotframework/issues/5189) ,it turned out that Windows Terminal doesn't support file URIs with a host name and on WSL the host name can easily be misconfigured yielding invalid URIs, and in the end we decided to use URIs without the host name on all OSes.

Feel free to close this issue if you don't consider adding the functionality worth the effort.

**Comment by barneygale** [comment]
Thanks! I'll close this as I think the proposed Windows behaviour is too subtle. Windows APIs for parsing file URIs generally treat all URIs with non-empty authorities as encoding _UNC paths_, e.g. see .NET's [`Uri.IsUnc`](https://learn.microsoft.com/en-us/dotnet/api/system.uri.isunc?view=net-8.0):

> This property always returns `true` if the URI has the file:// scheme and specifies a host component.

So even for non-UNC paths like `c:/foo/bar`, adding a hostname would likely cause misinterpretation.
