### ISSUE TITLE
Move typing-related usage of PEP585 generics from `typing` docs to `collections.abc`

### ISSUE THREAD

**Issue by sterliakov** [python/cpython#123523]
# Documentation

As pointed out in #123521, currently we have typing-related usage of PEP585 generics (`Generator`, `Callable`, `Coroutine`, etc.) explained on [`typing`](https://docs.python.org/3/library/typing.html#typing.Generator) page. However, those aliases are deprecated, and there's no backlink from their `collections.abc` [counterparts](https://docs.python.org/3/library/collections.abc.html#collections.abc.Generator).

So, currently all users of the recommended modern option (`collections.abc` generics) have no documentation regarding their use in typing context at hand. Worse, classes there don't even have their generic arguments listed - only the name:

> `class collections.abc.Generator`

This clearly should be fixed. At minimum the following needs to hold:

* `collections.abc` aliases have their generic arguments listed in the docs
* All typing-related info from corresponding `typing` docs entries should be reachable from `collections.abc` docs.

Upon some thinking I agree with @ZeroIntensity that moving all information to `collections.abc` and only retaining deprecation warning with a link in `typing` docs could be the most ergonomic option.

### Linked PRs
* gh-123544
* gh-123790
* gh-123792

**Comment by ZeroIntensity** [comment]
@JelleZijlstra, as a typing expert, does this approach seem good to you?

**Comment by AA-Turner** [comment]
As a user of collections generics, this would be quite useful, and seems appropriate now that Python 3.8 is nearing end-of-life. Happy to defer to others' views, though.

A

**Comment by sterliakov** [comment]
I think +3 on the last comment is a good enough indicator - I'll grab this and open a PR soon.
