### ISSUE TITLE
Add a `goto found_unused_or_dummy` in the set_add_entry function

### ISSUE THREAD

**Issue by satori1995** [python/cpython#123514]
# Bug report

### Bug description:

There's a missing line of code inside the set_add_entry function in the Objects/setobject.c file

![image](https://github.com/user-attachments/assets/c1528028-de93-42e1-8605-380585f4bca8)

When a dummy entry is found, it should jump directly to the found_unused_or_dummy label.

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Linked PRs
* gh-123515

**Comment by rhettinger** [comment]
This edit doesn't look correct.   

Suppose `z` was inserted with a collision chain of `x -> y` giving `x -> y -> z`  And then `y` was deleted giving `x -> DUMMY -> z`.  Later `z` is added again.  With the proposed edit, there would be an early out at the dummy entry giving `x -> z -> z`, failing to eliminate the duplicate.

**Comment by satori1995** [comment]
I understand now, thank you for your explanation. I didn't consider it thoroughly enough.
