### ISSUE TITLE
inconsistent behaviour with TemporaryDirectory

### ISSUE THREAD

**Issue by asingh9530** [python/cpython#123519]
# Bug report

### Bug description:

Hi Team,
`TemporayDirectory()` from `tempfile` module is showing inconsistent behaviour, following is the way to check this bug.

Context of issue:  Typically creating a temporary directory using `TemporaryDirectory()` is done under `with` context and after the context is finished the temporary directory get's removed, but I have by accident tried using `TemporaryDirectory(`) without any `with` context and it shows weird behaviour.

- Using `TemporaryDirectory()` in terminal using following code 
```python
import tempfile
temp_dir = tempfile.TemporaryDirectory().name
```
outputs - 
```
/var/folders/0s/qnrk8b3d67d43q2350hd_r6m0000gn/T/tmpi2hxpnl0
```
but if we try to `cd` it, throws error which it should as the directory didn't exists and got removed as soon as it got created.

- Using `TemporaryDirectory()` in terminal using following code 
```python
import tempfile
temp_dir = tempfile.TemporaryDirectory()
temp_dir.name
```
outputs - 
```
/var/folders/0s/qnrk8b3d67d43q2350hd_r6m0000gn/T/tmpr3x8v0kb
```
but if we try to `cd` it, works perfectly fine and the directory exists which it should not as we are not using it under any with context or atleast show similar behaviour like above case.

`TemporaryDirectory()` also shows inconsistent behaviour with `pytest` as the test cases run using 1s methods fails but with 2nd method succeeds 

I am not sure if I am missing something, here are environment config

- Os -> macOS [14.4.1]
- python -> 3.10.13 
- anaconda -> 23.3.1

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by ethanfurman** [comment]
In your first example, the `TemporaryDirectory` object is not saved (not assigned to anything), so it is immediately thrown away and the created directory is removed.

In your second example, you are saving the `TemporaryDirectory` to a name, so it is not thrown away and the created directory persists.

**Comment by asingh9530** [comment]
@ethanfurman Thanks this answers the above two.
