### ISSUE TITLE
Incorrect code snippet for `BUILD_TUPLE` in `dis`  docs

### ISSUE THREAD

**Issue by jlallas384** [python/cpython#123550]
# Documentation

The code snippet in the docs removes the last *count* items from the stack before creating the tuple instead of first creating the tuple from the last *count* items and then removing them from the stack. 
https://github.com/python/cpython/blob/917283ada6fb01a3221b708d64f0a5195e1672dc/Doc/library/dis.rst?plain=1#L1113-L1124

### Linked PRs
* gh-123551
* gh-123555
* gh-123556

**Comment by AA-Turner** [comment]
Would you be willing to open a PR?

A
