### ISSUE TITLE
Document "!" token in lexical analysis document

### ISSUE THREAD

**Issue by Glyphack** [python/cpython#123579]
# Documentation

I think after [PEP701](https://peps.python.org/pep-0701/) The `!` character became a token.
But this is not listed like other tokens:
- https://docs.python.org/3/reference/lexical_analysis.html#delimiters
- https://docs.python.org/3/reference/lexical_analysis.html#operators

It is mentioned in the grammar though: https://docs.python.org/3/reference/lexical_analysis.html#formatted-string-literals

I think it would be helpful to list it in https://docs.python.org/3/reference/lexical_analysis.html or remove the rest of tokens and refer to Grammar/Tokens file so the list is always up to date.

### Linked PRs
* gh-123612
* gh-123637
* gh-123638

**Comment by lysnikolaou** [comment]
Thanks for opening an issue @Glyphack! That's a good point. Would you like to submit a PR that adds `!` to the list of operators in https://docs.python.org/3/reference/lexical_analysis.html#operators?

**Comment by Glyphack** [comment]
Yess I will do thanks for clarifying.

**Comment by lysnikolaou** [comment]
Fixed in https://github.com/python/cpython/pull/123612. Thanks @Glyphack!
