### ISSUE TITLE
End period issue

### ISSUE THREAD

**Issue by CSShanmughapriya** [python/cpython#123532]
# Bug report

### Bug description:

```python
# if the file(Priya.txt) contain the text line by line as 1st line Sathya, 2nd line Suriya, 3rd line Priya, as per the below code it will come Sathya
Suriya
Priya
but if i give "print(line.strip(), end=".")" the line did not come separately, it will come run on-line, why? the output should not come like "Sathya.
Suriya.
Priya."
```
with open("D:\\Sathian\\Priya.txt", "r") as file:
    for line in file:
        print(line.strip())

### CPython versions tested on:

3.9

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
This repository is intended as a CPython bug tracker. Please, ask python-related questions there: https://discuss.python.org/c/users/7
