### ISSUE TITLE
Match statement's `signed_number` token is not properly defined

### ISSUE THREAD

**Issue by CBerJun** [python/cpython#123580]
# Documentation

It seems that the last line in the following production list intended to define the token `signed_number` but mistakenly put it inside the definition of `literal_pattern`.

https://github.com/python/cpython/blob/91b7f2e7f6593acefda4fa860250dd87d6f849bf/Doc/reference/compound_stmts.rst?plain=1#L836-L844

The intended meaning might be:
```
signed_number: NUMBER | "-" NUMBER
```

### Linked PRs
* gh-123582
* gh-123623
* gh-123624

**Comment by Eclips4** [comment]
Thanks for the report!
Would you like to send a PR with fix? :)

**Comment by picnixz** [comment]
Closing as completed and backported.
