### ISSUE TITLE
`_tkinter` leaks type references on initialization

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#123504]
# Bug report

### Bug description:

Reproducer:
```
$ ./python -Xshowrefcount -c "import tkinter"
```

Seems to be caused by the use of `AddObjectRef` on a strong reference in the `_tkinter` initialization function, causing a double `Py_INCREF`.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-123505
* gh-123662

**Comment by serhiy-storchaka** [comment]
#123505 was not correct. You need to:

1. Restore `m_size`.
2. Define `m_travel`.

**Comment by ZeroIntensity** [comment]
I'll submit a PR within in the hour, sorry!

**Comment by serhiy-storchaka** [comment]
It would also be nice if one of the subinterpreters experts would take a look at this change.
