### ISSUE TITLE
urlparse() should decode percent-encoding in userinfo

### ISSUE THREAD

**Issue by SmartHypercube** [python/cpython#123644]
# Bug report

### Bug description:

[RFC 3986 3.2.1](https://datatracker.ietf.org/doc/html/rfc3986#section-3.2.1) says `userinfo = *( unreserved / pct-encoded / sub-delims / ":" )`, so userinfo can contain `pct-encoded` parts and I would expect them to be automatically decoded when parsed. I also tested and confirmed that cURL will decode percent-encoding in userinfo.

This decoding is important because username may be email address which contains `@`, and password may contain symbols like `%`, `@`, etc. If one manipulates URLs using `urllib.parse`, the current behavior can lead to hard-to-notice bugs.

### How to reproduce
```python3
import urllib.parse
parse_result = urllib.parse.urlparse('http://a%40b:c%25d@e/')
print(parse_result.username, parse_result.password)
```

### Expected output
```
a@b c%d
```

### Actual output
```
a%40b c%25d
```

### CPython versions tested on:

3.9, 3.12

### Operating systems tested on:

Linux

**Comment by pygeek** [comment]
This is consistent with every implementation of url parse that I am aware of. For example:

node 22.6.0 and safari 17.5

```
> new URL("/", "http://a%40b:c%25d@e")
URL {
  href: 'http://a%40b:c%25d@e/',
  origin: 'http://e',
  protocol: 'http:',
  username: 'a%40b',
  password: 'c%25d',
  host: 'e',
  hostname: 'e',
  port: '',
  pathname: '/',
  search: '',
  searchParams: URLSearchParams {},
  hash: ''
}
>
```

**Comment by pygeek** [comment]
What you are looking for is `urllib.parse.unquote`. `urllib.parse.urlparse` does not unquote:

```
>>> urllib.parse.unquote("http://a%40b:c%25d@e/")
'http://a@b:c%d@e/'
```

**Comment by SmartHypercube** [comment]
I see. That makes sense. Thanks for your reply!

(I was thinking "since it already parsed the URL, why not unquote it?" But the path and query components actually cannot be unquoted at this stage. Only individual parts of the path and individual keys and values of the query can be safely unquoted. Similarly, userinfo as a whole cannot be safely unquoted. Only username and password can be safely unquoted. So "only parse, not unquote" for all components is a very reasonable design for `urlparse`.)
