### ISSUE TITLE
math.average function proposal

### ISSUE THREAD

**Issue by zykron1** [python/cpython#123658]
# Feature or enhancement

### Proposal:

I noticed that python has no average function built in as far as I know. I propose a function like math.average that calculates the average of a list. The functionality should look like so:

```python3
import math
math.average([1,3]) # The average between 1 and 3 is 2

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

_No response_

<!-- gh-linked-prs -->
### Linked PRs
* gh-123659
<!-- /gh-linked-prs -->

**Comment by zykron1** [comment]
Will make a PR soon

**Comment by rruuaanng** [comment]
You should try to implement avg at an inline level, with support for iterators, rather than at the module level.

**Comment by zykron1** [comment]
Edit: Seems like there is an average function in python in statistics.mean. Maybe this should be a builtin function like @rrruuaanng suggested?

**Comment by rruuaanng** [comment]
For example, builtin function sum() and max()

**Comment by blhsing** [comment]
> Seems like there is an average function in python in statistics.mean. Maybe this should be a builtin function like @rrruuaanng suggested?

But why does it need to be a built-in function? I don't think calculation of average is needed nearly as much as calculations of sum and max, so it's fine to keep it in the standard library.

**Comment by zykron1** [comment]
> > Seems like there is an average function in python in statistics.mean. Maybe this should be a builtin function like @rrruuaanng suggested?
> 
> But why does it need to be a built-in function? I don't think calculation of average is needed nearly as much as calculations of sum and max, so it's fine to keep it in the standard library.

That is a valid criticism, indeed functions like `sum` and `max` are more commonly used. However my interest in getting builtin function like `avg` stems from the idea of providing a more consistent and convenient user experience. Many people might just not want the weight that comes with importing a module. Having a built in function would provide a more simplified and lightweight feel, aligning with Python's accessibility and ease of use.

That said, I understand that adding too many built-ins can lead to bloat. In my opinion, a builtin like `avg` would meet the criteria for a builtin. Ultimately, it's about making Python easier and more intuitive to use in everyday scenarios.

**Comment by ericvsmith** [comment]
Feature requests need to be discussed at https://discuss.python.org/c/ideas/6. Please open a conversation there. I'm going to close this issue, but it can be re-opened if the idea is accepted.

But I'll warn you that there's basically no chance that adding this as a built in function will be accepted.
