### ISSUE TITLE
Accidentally left ``lel.patch`` in 3.12 branch

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#123646]
# Bug report

### Bug description:

[This](https://github.com/python/cpython/blob/3.12/lel.patch) was added by accident in https://github.com/python/cpython/commit/7dec3d7acbb072e0d5cd7357c1ddf12d3c667e8a.

I have a PR ready.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-123647

**Comment by zware** [comment]
Good catch!

**Comment by pablogsal** [comment]
Thanks @Eclips4 😓
