### ISSUE TITLE
A save function in the Turtle module

### ISSUE THREAD

**Issue by yngvem** [python/cpython#123614]
# Feature or enhancement

### Proposal:

I've used `turtle.py` quite a bit in my teaching, and a common question is how learners can save their files. Now, the turtle library only supports saving the drawings as postscript files by calling the cryptic command `turtle.getscreen().getcanvas().postscript(file=filename)`. Whenever a learner asks “How can I print what I made?”, I’ll have to show them that extremely scary command with method chaining -- not the best snippet to show someone who’s still struggling with functions…

If we instead had a `turtle.save("filename.ps")`, then I could tell the learners to use that function and an online postscript to pdf converter, which should be understandable to most learners

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

### Links to previous discussion of this feature:

https://discuss.python.org/t/improving-the-turtle-library/61840

### Linked PRs
* gh-123617

**Comment by yngvem** [comment]
@MarieRoald and I will submit a pull request on this shortly

**Comment by rruuaanng** [comment]
> @MarieRoald and I will submit a pull request on this shortly
Hi yngvem, if you don't have time to complete the commit, please close the pull, I have a complete pull with documentation

**Comment by hugovk** [comment]
@rruuaanng Please be patient and allow the authors time to work on this in their own time. It has only been ~36 hours since the PR was opened. 

We are absolutely not in a rush here, the deadline for new features in 3.14 is the [first beta in May 2025](https://peps.python.org/pep-0745/#release-schedule). I suggest finding something else to work on.

**Comment by rruuaanng** [comment]
> @rruuaanng Please be patient and allow the authors time to work on this in their own time. It has only been ~36 hours since the PR was opened.
> 
> We are absolutely not in a rush here, the deadline for new features in 3.14 is the [first beta in May 2025](https://peps.python.org/pep-0745/#release-schedule). I suggest finding something else to work on.

Okey, I'm sorry
