### ISSUE TITLE
Dictionary and set documentation mixup

### ISSUE THREAD

**Issue by AttilaLiptak** [python/cpython#123621]
# Documentation

https://docs.python.org/3/reference/datamodel.html

3.2.7.1. Dictionaries

The documentation says the following: 
"Dictionaries are mutable; they can be created by the {...} notation."

However any Python interpreter shows the following result:
>>>print(type({}))
<class 'dict'>
print(type({...}))
>>> <class 'set'>

I suspect the documentation mixes up the empty set and empty dictionary creation.

### Linked PRs
* gh-123648
* gh-123653
* gh-123654

**Comment by sobolevn** [comment]
Would you like to send a PR? I agree that using a valid set literal to show how `dict`s are created is not right.

**Comment by sobolevn** [comment]
Thanks, I will send one more PR with some extra changes in a separate issue! 👍
