### ISSUE TITLE
Clinical Research- Critical data infiltration by third party

### ISSUE THREAD

**Issue by clmaley** [python/cpython#123674]
Dear Github Data Team,

I am reaching out with an urgent matter regarding unauthorized access
to my computer and personal data, which I believe is connected to
third-party sources. This situation has severely impacted my role in
research, and despite extensive efforts to resolve it over the past
few months, I have seen no progress.

I have sought help from the cybersecurity teams at both the University
of Chicago and the University of Illinois, in addition to tech support
from HP, Lenovo, and Best Buy.
Unfortunately, the responses I"ve received have been unhelpful. The
only suggested solution-deleting OneNote-has proven ineffective,
leaving my systems vulnerable and my research at risk.

The invasiveness of this issue has created a distressing environment
for me, and it is becoming increasingly critical that I receive some
form of assistance or information. If these access issues are related
to Microsoft products or services, I need clarity on that matter
urgently. Conversely, if there is no affiliation, I would appreciate
any guidance you can provide on how to proceed, as I am running out of
options.

This problem has now reached a level of urgency that my universities
are considering involving the FBI Cybercrime team. If the ongoing
issues are compromising sensitive patient data, the cleanup process
will only become more complicated, which is unacceptable.

I kindly ask that you treat this matter with utmost priority. Please
contact me at your earliest convenience, either via email or by
calling (630) 732-0021, to provide any insights or assistance you can
offer.

Thank you for your prompt attention to this dire issue. I look forward
to your swift response.

Sincerely,

Christine Maley
Research Assistant
Department of Neurosurgery
University of Illinois Chicago

630-732-0021

**Comment by hugovk** [comment]
Hello, this is the public issue tracker for the Python programming language, and I don't believe we can assist you.

If you want to contact GitHub itself, I suggest you open a ticket with them directly via:

https://support.github.com/request

**Comment by clmaley** [comment]
Is there a way for me to uninstall this software completely??

**Comment by ZeroIntensity** [comment]
Do you have reason to believe that Python is the cause of the problem?

**Comment by clmaley** [comment]
I know that python is affiliated with github in terms of language? There are very literally thousands of different sites that I am being "tracked" by; no one knows how to remove them and unless there is an investigation or inquiry of some sort the information collected is WILDLY inappropriate. I made a GitHub account to try to understand what was going on after the top IT security teams both had no clue what to do, but that increases the parameters on my account? It is an absolute mess.
