### ISSUE TITLE
zipfile.Path.name uses inappropriate Windows semantics

### ISSUE THREAD

**Issue by jaraco** [python/cpython#123693]
# Bug report

### Bug description:

In https://github.com/python/cpython/pull/123426#issuecomment-2324839726, we learned that Python 3.10 (only) ended up with a version of `zipfile.Path` that uses [`pathlib.Path` (platform-variable) behavior](https://github.com/python/cpython/blob/d3f39cefe721db643957d48316ac98c5e279f0c3/Lib/zipfile.py#L2441-L2443) for parsing the name. As a result, zipfiles with names like `V: foo` or `foo\bar` get incorrect names and are thus broken.

This issue was revealed by applying additional tests for GH-123270.

The issue was corrected incidentally in zipp 3.16.2 and Python 3.11. The issue does not affect Python 3.9.

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

### Linked PRs
* gh-123694

**Comment by hugovk** [comment]
PR merged, closing issue.
