### ISSUE TITLE
tsan: fix race:sock_recv_impl suppressions for free-thread building

### ISSUE THREAD

**Issue by Zheaoli** [python/cpython#123695]
# Feature or enhancement

### Proposal:

The root cause of this race here is we use the same socket in the server and client side in our test. I think this is wrong

FYI https://github.com/python/cpython/blob/main/Lib/test/test_socket.py#L4817-L4825

I think we just need make a small patch for test case

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-123697

**Comment by mpage** [comment]
Thanks for doing this! We're tracking work to remove TSAN suppressions for free-threading builds in https://github.com/python/cpython/issues/117657. Can you please close this issue and associate https://github.com/python/cpython/pull/123697 with https://github.com/python/cpython/issues/117657?
