### ISSUE TITLE
Some missing handle types in `ctypes.wintypes`

### ISSUE THREAD

**Issue by jlallas384** [python/cpython#123610]
There are some missing handle types such as `HFILE` or `HCURSOR`
https://github.com/python/cpython/blob/57c471a6880956338549380fc5fb35c986937901/Lib/ctypes/wintypes.py#L62-L90

https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types

### Linked PRs
* gh-123721
* gh-124086

**Comment by rruuaanng** [comment]
> There are some missing handle types such as `HFILE` or `HCURSOR`缺少一些句柄类型，例如 `HFILE` 或 `HCURSOR`
> 
> https://github.com/python/cpython/blob/57c471a6880956338549380fc5fb35c986937901/Lib/ctypes/wintypes.py#L62-L90
> 
> https://learn.microsoft.com/en-us/windows/win32/winprog/windows-data-types

Which version of Python interpreter does the problem occur in？
