### ISSUE TITLE
When dividing - 0 with - 1 in python

### ISSUE THREAD

**Issue by I337402** [python/cpython#123796]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
- 0 / - 1   => Python output => - 0.00  , ideally it should be => 0.00  ( without minus sign , please correct ) 
![Minus Zero](https://github.com/user-attachments/assets/99b4592c-3617-4768-b3b7-1b7556976a3c)

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by I337402** [comment]
even 0 / - 1 => gives output as - 0. 00  !!!

**Comment by tim-one** [comment]
Adding a gloss: in `-0 / -1`, the first unary minus is applied to the int 0, giving the int 0. There is no negative int 0.  So it's the same as `0/-1`, which converted to the float `0.0/-1.0`, which is again `-0.0`.
