### ISSUE TITLE
`secrets.randbits` returns only nonnegative integers

### ISSUE THREAD

**Issue by Kodiologist** [python/cpython#123789]
# Documentation

The docstring of `secrets.randbits` reads, in its entirety, "Return an int with *k* random bits." In fact, it only generates nonnegative integers, like its sister function `random.getrandbits`.

### Linked PRs
* gh-123801
* gh-123830
* gh-123831

**Comment by AA-Turner** [comment]
PR welcome! 

A

**Comment by Wulian233** [comment]
Now we can close this🎉

**Comment by Kodiologist** [comment]
Looks good. Thanks.
