### ISSUE TITLE
`time.strftime` does't work properly with format specifier `%f` on Windows

### ISSUE THREAD

**Issue by igor-sadchenko** [python/cpython#123788]
When using the `time.strftime()` function with the format string `"%Y-%m-%dT%H:%M:%S.%f000Z"` on Windows, the `%f` specifier for microseconds does not work as expected. The same format works correctly on Linux and macOS.

**Example code:**

```python
import time
time.strftime("%Y-%m-%dT%H:%M:%S.%fZ", time.gmtime())
```

**Expected behavior:**

The `%f` specifier should return the microsecond part of the time when used in the `time.strftime()` format string, similar to how it works on Linux and macOS.

Example output on Linux/macOS:

```
2024-09-06T14:53:10.123000Z
```

**Actual behavior on Windows:**

On Windows, the `%f` specifier is not recognized by `time.strftime()`, and no microseconds are included in the output.

Example output on Windows:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid format string
```

**Platform Information:**

- **OS:** Windows 10 (also tested on other Windows versions)
- **Python version:** Affected on Python 3.x (tested on Python 3.8, 3.9, 3.10, 3.11, 3.12)

**Additional information:**

- The `%f` specifier seems to work correctly on Unix-based systems (Linux/macOS).
- The issue might be related to how the Windows implementation of `time.strftime()` interacts with the underlying system libraries.
- This is inconsistent behavior across different platforms, and it would be ideal for `%f` to work consistently.

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Linux, macOS, Windows

**Comment by picnixz** [comment]
I'm surprised that it actually works on Linux/Darwin because the docs are clear for this: https://docs.python.org/3.13/library/time.html#time.strftime

> The %f format directive only applies to [strptime()](https://docs.python.org/3.13/library/time.html#time.strptime), not to [strftime()](https://docs.python.org/3.13/library/time.html#time.strftime). However, see also [datetime.datetime.strptime()](https://docs.python.org/3.13/library/datetime.html#datetime.datetime.strptime) and [datetime.datetime.strftime()](https://docs.python.org/3.13/library/datetime.html#datetime.datetime.strftime) where the %f format directive [applies to microseconds](https://docs.python.org/3.13/library/datetime.html#format-codes).

By the way, it does not work on Linux:

```pycon
>>> import time
... time.strftime("%Y-%m-%dT%H:%M:%S.%fZ", time.gmtime())
...
'2024-09-06T15:09:14.%fZ'
```

In addition:

> Additional directives may be supported on certain platforms, but only the ones listed here have a meaning standardized by ANSI C. To see the full set of format codes supported on your platform, consult the [strftime(3)](https://manpages.debian.org/strftime(3)) documentation.

**Comment by picnixz** [comment]
Closing as `not planned` since the OP did not reply and the behaviour is documented.
