### ISSUE TITLE
ParseResult._replace() usage encouraged in python docs

### ISSUE THREAD

**Issue by seanbudd** [python/cpython#123750]
# Documentation

[urlparse](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.urlparse) documentation encourages using the `_replace` method of a `ParseResult`. My understanding is that internal underscored functions are not reliable parts of the API and usage should not be encouraged. Alternatively, can this function be made public?

**Comment by zware** [comment]
Odd though it be, `ParseResult._replace` *is* [a public method](https://docs.python.org/3/library/collections.html#collections.somenamedtuple._replace).   In general, you are correct that in most cases such names are considered implementation details and you should not rely on them (or at least we won't listen to your complaints if you do and we break them :) ), but this is a special case where the underscore is just to avoid collisions with whatever could wind up in someone's `namedtuple` type.
