### ISSUE TITLE
Availability of `ptsname_r` is not checked at runtime on macOS

### ISSUE THREAD

**Issue by zanieb** [python/cpython#123797]
# Bug report

### Bug description:

Use of this was recently added in Python 3.13 but it is only available in macOS 10.13.4+ and there is not a proper runtime check for availability. This means that in `python-build-standalone` we need to ban the symbol instead of allowing proper weak linking.

See discussion at https://github.com/indygreg/python-build-standalone/pull/319#discussion_r1747174338

Similar to https://github.com/python/cpython/issues/75782

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-123806
* gh-124270

**Comment by zanieb** [comment]
This is a `build` issue but I can't make those.

**Comment by zanieb** [comment]
I believe this was resolved?

**Comment by sobolevn** [comment]
Yes, thanks a lot, @zanieb, for the report! 👍
