### ISSUE TITLE
sqlite3 usage of context manager leads to memory accumulation

### ISSUE THREAD

**Issue by tychoa-npo** [python/cpython#123739]
# Bug report

### Bug description:

Running the following script leads to an increasing amount of memory usage of the python process.
```python
# Sqlite3 memory consumption minimal example

## setup

import time
import sqlite3

class Foo:

    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

## Running it
def main():
    db = sqlite3.connect("dummy.db")
    db.execute("CREATE TABLE IF NOT EXISTS dummy(x INTEGER PRIMARY KEY ASC, y, z)")
    for i in range(10_000_000):
        db.execute("INSERT INTO dummy (y, z) VALUES (?, ?)", (i,i+2))
    db.close()

    for i in range(1_000):
        with sqlite3.connect("dummy.db", check_same_thread=False) as db:
            cursor = db.cursor()
            cursor.execute("SELECT * FROM dummy WHERE x = ?;", (i,))
            rows = [Foo(r[0], r[1], r[2]) for r in cursor.fetchall()]

        print(i)
        time.sleep(0.1)

main()
```

Running the following script keeps a constant memory usage.
```python
# Sqlite3 memory consumption minimal example

## setup

import time
import sqlite3

class Foo:

    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

## Running it
def main():
    db = sqlite3.connect("dummy.db")
    db.execute("CREATE TABLE IF NOT EXISTS dummy(x INTEGER PRIMARY KEY ASC, y, z)")
    for i in range(10_000_000):
        db.execute("INSERT INTO dummy (y, z) VALUES (?, ?)", (i,i+2))
    db.close()

    for i in range(1_000):
        db = sqlite3.connect("dummy.db", check_same_thread=False)
        cursor = db.cursor()
        cursor.execute("SELECT * FROM dummy WHERE x = ?;", (i,))
        rows = [Foo(r[0], r[1], r[2]) for r in cursor.fetchall()]
        db.close()

        print(i)
        time.sleep(0.05)

main()
```

This leads me to believe that the context manager, of which its usage is recommended, leads to an unnecessary amount of memory usage. I suspect this is related to closing the database connection. When omitting the `db.close` call, similar behavior occurs as when using the context manager.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by ZeroIntensity** [comment]
I haven't had a chance to try and reproduce this yet, but I'd like to work on it. At a glance (assuming there's an actual leak here), there's probably a missing call to `close` inside the `__exit__`.

**Comment by graingert** [comment]
It's intentional that the sqlite.Connection context manager doesn't call self.close: https://docs.python.org/3/library/sqlite3.html#how-to-use-the-connection-context-manager

But it should still be garbage collected correctly

**Comment by zashab** [comment]
what is this

**Comment by ZeroIntensity** [comment]
Looks like user-error. As mentioned by @graingert, `with` does not call `db.close`, leading to leaked resources in this case. The `database` object itself does get cleaned up eventually:

```
$ ./python -Xshowrefcount test.py
<sys>:0: ResourceWarning: unclosed database in <sqlite3.Connection object at 0x708b07795590>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
...
[0 refs, 0 blocks]
```

@encukou, this needs `pending`.

**Comment by tychoa-npo** [comment]
Ah, I misunderstood then, my fault. I expected the context manager to take care of more than just committing and rollback (similar to how file handlers work). If this is intended behavior, this can be closed, although I am curious why this is intended?

**Comment by erlend-aasland** [comment]
> If this is intended behavior, this can be closed, although I am curious why this is intended?

If you follow the link provided by Thomas in https://github.com/python/cpython/issues/123739#issuecomment-2332118521, you'll be able to read from the docs that this is the expected behavious.

Regarding the _intended_ behaviour, I don't know. The third-party library `pysqlite` was incorporated into the standard library _as it was_ in 2006, with this functionality already implemented. It was a decision made _before_ it was incorporated into the standard library. Changing the behaviour of this context manager would have been a major breaking change; thousands of code bases would have been broken. We will not go down that path. This is why we have _documented_ the existing behaviour explicitly, using a "note" for improved visibility.

**Comment by tychoa-npo** [comment]
Clear! That makes sense, apologies for the trouble.
