### ISSUE TITLE
Simplifying ascii-decode

### ISSUE THREAD

**Issue by rhpvorderman** [python/cpython#123894]
# Feature or enhancement

### Proposal:

This is a trivial enhancement of the ascii_decode function in unicodeobject.c. By using memcpy on unaligned pointers, the compiler will use unaligned loads on platforms that support it. Most platforms do. 

Currently the ascii_decode function looks very byzantine. By writing it slightly differently using memcpy, lots of lines can be removed while also becoming more readable in my opinion. 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-123895

**Comment by vstinner** [comment]
I close the issue since the PR was closed: https://github.com/python/cpython/pull/123895
