### ISSUE TITLE
Testing math_testcases.txt lacks support for signed zeros

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#123836]
# Feature or enhancement

### Proposal:

This file tested, using result_check() helper:
https://github.com/python/cpython/blob/beee91cdcc0dbecab252f7c5c7c51e2adb8edc26/Lib/test/test_math.py#L175
which lacks checking of zero sign (while some entries in the data file - have signed zeros).  C.f. cmath_testcases.txt, which tested with rAssertAlmostEqual(), that *has* such special case:
https://github.com/python/cpython/blob/beee91cdcc0dbecab252f7c5c7c51e2adb8edc26/Lib/test/test_cmath.py#L124-L131

I think that first helper should be adjusted to do same.  I'll work on a patch.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-123854
* gh-124161
* gh-124162
* gh-124171
* gh-124186
* gh-124187

**Comment by skirpichev** [comment]
PR is ready for review: https://github.com/python/cpython/pull/123854

**Comment by vstinner** [comment]
Implemented as https://github.com/python/cpython/commit/28aea5d07d163105b42acd81c1651397ef95ea57. Backports will follow.

**Comment by encukou** [comment]
This broke the Windows 10 buildbot: https://github.com/python/cpython/pull/123854#issuecomment-2354940205

**Comment by skirpichev** [comment]
Fix: https://github.com/python/cpython/pull/124171

**Comment by vstinner** [comment]
Congrats @skirpichev for this nice enhancement.
