### ISSUE TITLE
_wmi missing in sys.stdlib_module_names

### ISSUE THREAD

**Issue by mtnpke** [python/cpython#123892]
# Bug report

### Bug description:

Given that `import _wmi` succeeds on a minimal Python distribution (embeddable amd64 downloaded from https://www.python.org/downloads/release/python-3130rc2/ for example), should `_wmi` not be included in `sys.stdlib_module_names`?

```
python-3.13.0rc2-embed-amd64 $ .\python.exe
Python 3.13.0rc2 (tags/v3.13.0rc2:ec61006, Sep  6 2024, 22:13:49) [MSC v.1940 64 bit (AMD64)] on win32
>>> import sys
>>> "_wmi" in sys.stdlib_module_names
False
>>> import _wmi
>>>
```

(My use case is that I am generating license exports automatically and any packages that are not resolvable to a distribution and not included in `stdlib_module_names` lead to an error or need special-casing.)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-123893
* gh-123896
* gh-123897

**Comment by mtnpke** [comment]
That was fast! Thanks!

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/fb1b51a58df4315f7ef3171a5abeb74f132b0971. Backports will follow.

Sadly, the list of Windows extensions is maintained manually by hand, and we forgot the _wmi extension. It's now fixed.

**Comment by vstinner** [comment]
Thanks for the bug report @mtnpke.
