### ISSUE TITLE
3.13 __static_attributes__ ignores self parameters other than "self"

### ISSUE THREAD

**Issue by jsaponara** [python/cpython#123860]
# Bug report

### Bug description:

Using a self parameter other than "self", __static_attributes__ is empty (in 3.13.0rc2):

```python
>>> class C:
...     def foo(self, a):
...         self.a = a
...         
>>> C.__static_attributes__
('a',)
>>> class D:
...     def foo(me, a):
...         me.a = a
...         
>>> D.__static_attributes__
()
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by Eclips4** [comment]
cc @iritkatriel

**Comment by iritkatriel** [comment]
This is working as designed. ``__static_attributes__`` is a heuristic, it's not intended to work in all cases. Heuristics work best with idiomatic code.
