### ISSUE TITLE
Result not expected on simple math operation

### ISSUE THREAD

**Issue by quique05** [python/cpython#123850]
# Bug report

### Bug description:

```python
# Add a code block here, if required
14*0.02+2
```
Tested on python 3.12.0 and 3.12.6.
Type 14*0.02+2 and get 2.2800000000000002
Type 14*0.01+2 and get 2.14
Type 14*0.03+2 and get 2.42

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by savannahostrowski** [comment]
I can reproduce this on Mac as well with 3.12.5.

**Comment by ericvsmith** [comment]
This is not a bug. See https://docs.python.org/3.14/tutorial/floatingpoint.html
