### ISSUE TITLE
test_sqlite3/test_dump.py Fails if SQLite Foreign Keys Enabled

### ISSUE THREAD

**Issue by Derothin** [python/cpython#123849]
# Bug report

### Bug description:

Just compiled 3.13.0rc2 today and ran into this issue with test_sqlite3. [A commit](https://github.com/python/cpython/commit/de777e490fb356d7bcc7c907141c20a5135d97df) added an intentional foreign key violation in test_dump.py, but the test doesn't consider that SQLite may have been compiled with foreign keys enabled by default. Just needs to have that turned off for the test.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-123859
* gh-125163

**Comment by erlend-aasland** [comment]
Fixed in `main` and the `3.13` branch. Thanks for the report, @Derothin, and thanks for the fix, @felixxm!
