### ISSUE TITLE
Support `wasm32-wasip1` as the default WASI target triple

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#123877]
# Bug report

### Bug description:

https://bytecodealliance.zulipchat.com/#narrow/stream/219900-wasi/topic/Is.20.60wasm32-wasi.60.20retired.20in.20preference.20for.20.60wasm32-wasip1.60.3F points out that `wasm32-wasi` is soft deprecated in favour of `wasm32-wasip1` so that `wasm32-wasi` can be claimed for WASI 1.0. As such, we should move over to making `-wasip1` the target triple.

This will require https://github.com/python/cpython/pull/123042 as well as a version of https://github.com/brettcannon/cpython/commit/2959f15d94d44e48a1efa3bd616c26ad5683a1ee .

### CPython versions tested on:

3.13

### Operating systems tested on:

Other

### Linked PRs
* gh-126552
* gh-126561

**Comment by vstinner** [comment]
Can't we wait for Python 3.14 to make such change? A soft deprecation doesn't sound like something urgent.

**Comment by brettcannon** [comment]
> Can't we wait for Python 3.14 to make such change?

I'm not making the change until 3.13.1 if that's what you're worried about. But I don't want to leave `wasm32-wasi` hard-coded as the default target in case WASI 1.0 comes in before the end of 2029 and Python 3.13 suddenly doesn't build out of the box for WASI because we left in the old triple.

I also have a PR to make it easy enough to specify the triple as well, so it won't be a costly transition to specify it manually so some workflow works in 3.13.0 and 3.13.1.

**Comment by brettcannon** [comment]
This is in `main`, but cherry-picker couldn't make it work for 3.13. I've [asked for opinions from the Bytecode Alliance if people think it's worth backporting](https://bytecodealliance.zulipchat.com/#narrow/channel/394175-SIG-Guest-Languages/topic/Is.20it.20worth.20updating.20Python.203.2E13.20to.20specify.20.60wasm32-wasip1.60.3F).

**Comment by brettcannon** [comment]
https://github.com/python/buildmaster-config/pull/555 should fix the buildbots.

**Comment by brettcannon** [comment]
Once  https://github.com/python/cpython/pull/126561 lands then I will make a PR to update the buildbot config.
