### ISSUE TITLE
Add `symtable` to the list of modules with a CLI 

### ISSUE THREAD

**Issue by picnixz** [python/cpython#123834]
Documenting the `symtable` CLI was first not considered since it previously included self-tests. This is no more the case and the module now features a full-fledged CLI (only since 3.13).

As such, I suggest adding it to the list of modules documented in `cmdline.rst`.

--- 

* Related: https://github.com/python/cpython/pull/109112
* Specialization of: #109435 

### Linked PRs
* gh-123835
* gh-123862

**Comment by vstinner** [comment]
Merged, thanks.
