### ISSUE TITLE
REPL indentation after print or evaluation is printed

### ISSUE THREAD

**Issue by Siecje** [python/cpython#123863]
# Bug report

### Bug description:

With Python 3.13.0rc2 after the REPL prints the next `>>>` prompt is indented. Is this a bug or a feature?

```Python
>>> False
False
     >>> 
>>> print('False')
False
     >>> 
>>> 1 == 2
False
     >>> 
>>> 1 == 1
True
    >>> 
>>> 
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by lysnikolaou** [comment]
Can't reproduce either. @Siecje Can you give us more information about your terminal configuration?
