### ISSUE TITLE
Broken Zope.dev datetime references

### ISSUE THREAD

**Issue by otkd** [python/cpython#123843]
# Documentation

Broken zope.dev references in https://github.com/python/cpython/blob/8ef8354ef15e00d484ac2ded9442b789c24b11e0/Modules/_datetimemodule.c#L2 and https://github.com/python/cpython/blob/8ef8354ef15e00d484ac2ded9442b789c24b11e0/Lib/test/datetimetester.py#L3

### Linked PRs
* gh-123844
* gh-123846

**Comment by terryjreedy** [comment]
Adams PR is an alternative 'instead-of' PR which I think should likely be preferred.
