### ISSUE TITLE
buildrelease.bat uses same build directory for AMD64 and ARM64

### ISSUE THREAD

**Issue by adang1345** [python/cpython#123915]
# Bug report

### Bug description:

When I build Python 3.11.10 installers using `Tools\msi\buildrelease.bat -x64 -arm64`, the AMD64 files under `PCbuild\amd64\en-us` are deleted when the ARM64 build starts.

This is due to a typo in the build directory for ARM64 in `Tools\msi\buildrelease.bat`, which has `set BUILD=%Py_OutDir%amd64\`. This build directory conflicts with that for AMD64 and should instead be `set BUILD=%Py_OutDir%arm64\`. I'll create a PR.

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

### Linked PRs
* gh-123918
* gh-123921
* gh-123922

**Comment by zooba** [comment]
Thanks!
