### ISSUE TITLE
faulthandler's `dump_traceback` doesn't handle case where top-most frame is `FRAME_OWNED_BY_CSTACK`

### ISSUE THREAD

**Issue by colesbury** [python/cpython#123967]
# Bug report

We properly skip trampoline frames when they are not the top-most frame:

https://github.com/python/cpython/blob/3bd942f106aa36c261a2d90104c027026b2a8fb6/Python/traceback.c#L979-L982

But if `tstate->current_frame` is a trampoline frame (i.e., `FRAME_OWNED_BY_CSTACK`) then `dump_traceback` will crash if faulthandler is triggered when executing a trampoline frame. 

### Linked PRs
* gh-127329
* gh-127362
* gh-127363

**Comment by picnixz** [comment]
Closing since completed and backported.
