### ISSUE TITLE
ftplib cannot connect to server which has banner / welcome message configured

### ISSUE THREAD

**Issue by kegabor** [python/cpython#123911]
# Bug report

### Bug description:

Scenario:
Setup: There is a running FTP server configured to send welcome message to user, like:
    `Hello, this is my FTP server, please login`
Test: Connect to this FTP server and validate the login banner.
Unexpected result:
```  File "/x/y/FtpServerChecker.py", line x, in ftp_connect
    welcome_msg = new_ftp.connect(host, port, timeout)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ftplib.py", line 162, in connect
    self.welcome = self.getresp()
                   ^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/ftplib.py", line 255, in getresp
    raise error_proto(resp)
ftplib.error_proto: test disclaimer
```

Based on code https://github.com/python/cpython/blame/main/Lib/ftplib.py#L162 the welcome message is handled the same way as any FTP response, but there is no restriction I could find related to banner. 
It means if it's not starting with number 1-3 then error is raised. Moreover if the 4th character is not a '-', then only 1 line is read.

My suggestion is to simply read out the buffer in connect() like: 
```
  def connect(...)
    ...
    self.welcome = self.readwelcome()
    return self.welcome

  def readwelcome(self):
    '''Get the welcome message during connect()'''
    welcome = self.sock.recv(self.maxline).decode()
    if self.debugging:
      print('*welcome* ', self.sanitize(welcome))
    return welcome
```

### CPython versions tested on:

3.9, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by picnixz** [comment]
The server is expected to reply using standard reply codes (see RFC 959). For details, see https://datatracker.ietf.org/doc/html/rfc959. The welcome/banner message must in particular send first the reply code and the whatever is after (see §4.2 of the RFC and §6 for the state automaton). 

Long story short, the server is expected to reply according to RFC 959 (and format its messages accordingly).

**Comment by kegabor** [comment]
I see your point and tend to accept, but I still curious, what code should be used in the welcome message?
The RFC does not mention this special message, that comes before "220 Service ready" and not command initiated.
It is even not fit into the mentioned state diagrams in §6 in "Login sequence", as there the first step is asking USER name, but welcome message comes earlier.
The closest is 214 as a help message.

**Comment by picnixz** [comment]
Ah sorry §6. I thought it had more details. Actually, the RFC is poorly documented so my bad for this. I think the server should simply send something like

```text
220- Hello this is the welcome message.
220- This is the second line of the welcome.
220 The last line does not contain a hyphenation.
```

This *should* do the trick. If it doesn't, I think we have a doc issue.

**Comment by kegabor** [comment]
Good news, the code is needed only in the first and last line, so between them can be anything (except any code in the first 3 position).
The code 220 is for waiting waiting for input, but it's a separate message after the "greeting"

**Comment by picnixz** [comment]
AFAIU, 220 is used for greeting as well (emphasis mine):

> One important group of informational replies is the connection
greetings. Under normal circumstances, a server will send a 220
reply, "awaiting input", when the connection is completed. **The
user should wait for this greeting message** before sending any
commands

I can't find a specific reply code to use for the welcome message only (one that is not 220).

**Comment by kegabor** [comment]
I'll close this ticket as no issue, and I'll suggest to the server's owners to format their welcome message accordingly.
I have to mention that there are FTP clients which accepts any kind of greetings, and needs only properly formatted FTP messages after that.

Thanks @picnixz  for your time and help!

**Comment by picnixz** [comment]
> 214 Help message. On how to use the server or the meaning of a particular non-standard command. 

I incorrectly assumed that this one would only be used as a reply of the help command actually. But if it can be used as the initial greeting message, that should be fine.

**Comment by kegabor** [comment]
I've tried with a test server, and it also accepts two 220 messages. First is the welcome message, while the second is the default "220 Service ready for new user", that I couldn't modify.
