### ISSUE TITLE
codegen should ideally not need to know the optimization level

### ISSUE THREAD

**Issue by iritkatriel** [python/cpython#123958]
Optimization level is used for things that can be done in ast_opt. I'll try to move them there. 

### Linked PRs
* gh-123959
* gh-124143

**Comment by hugovk** [comment]
PR merged, closing issue.

**Comment by iritkatriel** [comment]
There's another usage still to remove.

**Comment by hugovk** [comment]
Thanks, sorry I was too quick with the close button :)

**Comment by Eclips4** [comment]
So, the only remaining occurrence of `OPTIMIZATION_LEVEL` is related to the ``assert`` statement.
@iritkatriel, are you currently working  on this? If not, can I attempt to fix it?

**Comment by iritkatriel** [comment]
I have a patch for it. Thanks.

**Comment by iritkatriel** [comment]
I got as far as I could with this, the assert optimization needs to stay in ast_opt (see discussion on PR).
