### ISSUE TITLE
Move RE examples to Python HOWTOs

### ISSUE THREAD

**Issue by adorilson** [python/cpython#124053]
# Documentation

I suggest moving the [Regular Expression Examples](https://docs.python.org/3.13/library/re.html#regular-expression-examples) section to Python HOWTOs. The /library will have only the module reference.

**Comment by eendebakpt** [comment]
There is indeed the [Regular Expression HOWTO](https://docs.python.org/3/howto/regex.html) that might be a good place. In any case it seems good to link to the HOWTO at the top of the examples section (the HOWTO is mentioned on the library page, but it is mid-text and could easily be missed)

Moving to the HOWTO seems to match the Diataxis framework, see [Adopting the Diátaxis framework for Python documentation](https://discuss.python.org/t/adopting-the-diataxis-framework-for-python-documentation/15072), but I am not familiar enough with the python documentation structure to decide whether we actually want to move those examples.

**Comment by rhettinger** [comment]
I recommend leaving it as is.  People commonly never find the HOWTO docs.  Also, for people who struggle with main regex docs (as many do), the examples section is a welcome respite.

Adding a link to existing HOWTO is reasonable but the regex doc examples should remain in place (we have many parts of the docs with examples and recipes, none of those should be moved to HOWTO).
