### ISSUE TITLE
``test_asyncio.test_base_events`` leaks references in free-threaded build

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#124068]
# Bug report

### Bug description:

```python
eclips4@nixos ~/p/p/cpython (main)> ./python -m test -R 3:3 test_asyncio.test_base_events
Using random seed: 315532800
0:00:00 load avg: 7.88 Run 1 test sequentially in a single process
0:00:00 load avg: 7.88 [1/1] test_asyncio.test_base_events
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XX3 333
test_asyncio.test_base_events leaked [3, 3, 3] references, sum=9
test_asyncio.test_base_events failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_asyncio.test_base_events

Total duration: 18.4 sec
Total tests: run=111
Total test files: run=1/1 failed=1
Result: FAILURE
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-124069

**Comment by Eclips4** [comment]
Bisected to https://github.com/python/cpython/commit/8810e286fa48876422d1b230208911decbead294

**Comment by picnixz** [comment]
cc @Fidget-Spinner @colesbury (technically, `@me` as well since I've been involved :'))

**Comment by colesbury** [comment]
I'll take a look. I saw something similar when working on https://github.com/python/cpython/pull/124026 with a reference leak involving generators/coroutines and exceptions frames.
