### ISSUE TITLE
redefinition in closure functions 

### ISSUE THREAD

**Issue by MirS0bhan** [python/cpython#124002]
# Bug report

### Bug description:

i think it could be a bug or maybe we just need a PEP but I issue it here 
in closure functions we cant redefine a var that has defined before in the parent function 
as the normal action I think it should resolve it because is happens normally but when we use it in a 
redefinition it doesn't work.

```python
def foo(x: int):
    x: int = x * x
    def john():
        x: int = x + x
        return x
    return john
```
error: Unresolved reference 'x'

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ZeroIntensity** [comment]
You can do this with the `nonlocal ` keyword.

**Comment by MirS0bhan** [comment]
should not it be a norm behavior ?

**Comment by ZeroIntensity** [comment]
That would break untold amounts of code :(

You can refactor your code to use `nonlocal` to get the behavior you want:

```py
def foo(x: int):
    x: int = x * x
    def john():
        nonlocal x
        x: int = x + x
        return x
    return john
```

**Comment by ZeroIntensity** [comment]
@encukou, this should get closed as not planned.

**Comment by terryjreedy** [comment]
Requiring `nonlocal` to modify nonlocal names is the same as requiring `global` to modify globals.  Otherwise, names are looked up in locals first.  The keyword says to skip locals.

**Comment by terryjreedy** [comment]
Questions like this should be posted to the help channel on discuss.python.org.

**Comment by MirS0bhan** [comment]
actually it wasn't just a question. I suggest we could automate it because that's so simple move. we had call it before of definition so it should work. anyway
