### ISSUE TITLE
upgrade Unicode database to 16.0.0

### ISSUE THREAD

**Issue by benjaminp** [python/cpython#124016]
https://blog.unicode.org/2024/09/announcing-unicode-standard-version-160.html

### Linked PRs
* gh-124017

**Comment by terryjreedy** [comment]
Among other things, "This version adds 5,185 new characters, including 3,995 additional Egyptian Hieroglyph characters plus seven new scripts, seven new emoji characters, and over 700 symbols from legacy computing environments, for a total of 154,998 characters." and a new annex about hieroglyphs.
