### ISSUE TITLE
Typo in comment in Modules/Setup.bootstrap.in

### ISSUE THREAD

**Issue by khobaib529** [python/cpython#124099]
# Documentation

There is a typo in the comment within the `Modules/Setup.stdlib.in` file. The comment in 3rd line is "This file is autogenerated from Modules/Setup.stdlib.in".

but as I observed the file is auto generated from Modules/Setup.bootstrap.in file. it should be fixed

I want to fix this

### Linked PRs
* gh-124100

**Comment by Wulian233** [comment]
Can you point out which line of the word is misspelled, thanks

**Comment by picnixz** [comment]
Actually `Modules/Setup.stdlib.in` are the template files used by the [makesetup](https://github.com/python/cpython/blob/401fff7423ca3c8bf1d02e594edfd1412616a559/Modules/makesetup) to then generate `Modules/Setup.stdlib`. So this is, AFAIR, not a typo.

cc @terryjreedy

**Comment by sobolevn** [comment]
Yes, this is not a typo. This is a template for the future `Setup.stdlib` file:
<img width="788" alt="Снимок экрана 2024-09-16 в 10 59 38" src="https://github.com/user-attachments/assets/04535986-96ab-462a-b493-39f3814272cb">

**Comment by terryjreedy** [comment]
Got it.
