### ISSUE TITLE
Duplicate entry for the same configparser change in 3.13 release

### ISSUE THREAD

**Issue by yatmanov** [python/cpython#124124]
# Documentation

When reading the What’s New In Python 3.13 notes, I noticed that there are two identical entries describing the same change in configparser module. You can see it the attached screenshot.
![image](https://github.com/user-attachments/assets/00dca993-a3db-4f5f-aa91-6af824efeaa7)

I thought it worth bringing to your attention so that you could tidy up the release notes to make them easier for users to read.

**Comment by hugovk** [comment]
Thanks for the report!

This has already been fixed in `main`: https://github.com/python/cpython/pull/123874 -> https://docs.python.org/dev/whatsnew/3.13.html#configparser

And is awaiting merge for 3.13: https://github.com/python/cpython/pull/123879
