### ISSUE TITLE
with python 3.12 it is not supporting jupyter notebook notebook.nbextensions 

### ISSUE THREAD

**Issue by Darshan2104** [python/cpython#124184]
# Bug report

### Bug description:

```
It is giving below error while installing nbextension with python version 3.12.6

ModuleNotFoundError: No module named 'notebook.nbextensions'

command used to install is : jupyter contrib nbextension install --user
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by skirpichev** [comment]
I'm not sure why do you think it's a CPython issue.  Probably, you should report this first to https://github.com/ipython-contrib/jupyter_contrib_nbextensions.

Have you installed first the jupyter_contrib_nbextensions package?

**Comment by terryjreedy** [comment]
This seems like a problem with 3rd parth software.  Contact the jupyter or nbextension people, or ask for help on discuss.python.org or stackoverflow or ???.  Say what exactly you did if not the command the message said to use, and give full error message.
