### ISSUE TITLE
Looping through empty list yields a None object

### ISSUE THREAD

**Issue by jwezel** [python/cpython#124159]
# Bug report

### Bug description:

I've stumbled over a seemingly impossible situation where a `for` loop over an empty list yields a `None` object in its body. The code starts on line 136 of module [listconfig.py](https://github.com/omry/omegaconf/blob/6f9656bf091f6cb1ebfe22c926e60e1c9d25ca02/omegaconf/listconfig.py#L136) of [OmegaConf](https://github.com/omry/omegaconf). See the attached log of the terminal session demonstrating the effect.
[situation.txt](https://github.com/user-attachments/files/17023888/situation.txt)
[situation-nocolor.txt](https://github.com/user-attachments/files/17023981/situation-nocolor.txt)

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by sobolevn** [comment]
Can you please try to create a smaller reproducer? Right now it is not clear from the issue: how can one try to reproduce the problem.

**Comment by jwezel** [comment]
Sure, here is a zip. Create a venv, install `requirements.txt` and run `t2.py` through python 3.12.

[reproduction.zip](https://github.com/user-attachments/files/17024685/reproduction.zip)

**Comment by nineteendo** [comment]
Here's a smaller reproducer, but this doesn't seem a problem in CPython:

```python
import os

from omegaconf import OmegaConf
from yaml import safe_load_all


def _config(topic, config, prepend=None, append=None):
    path = next(
        p
        for p in (
            ([config[topic.lower()]] if config and config.get(
                topic.lower()) else [])
            + (prepend or [])
            + [
                f"${{oc.env:INFRA_{topic.upper()},''}}",
                f"{topic.lower()}.yaml",
                f"{topic.lower()}",
                f"${{oc.env:HOME}}/.config/infra/{topic.lower()}.yaml",
                f"${{oc.env:HOME}}/.config/infra/{topic.lower()}",
            ]
            + (append or [])
        )
        if os.path.exists(p)
    )
    with open(path) as infile:
        data = list(safe_load_all(infile))

    result = {}
    for value in data:
        result.update(value)

    return result


cliConfig = OmegaConf.from_cli([])
Config = OmegaConf.create({"hosts": {}, "hostgroups": {}})
Config.merge_with(_config("config", config=cliConfig))
Config.merge_with(cliConfig)
hosts = _config("hosts", config=Config)
hostgroups = _config("hostgroups", config=Config)
Config.hosts = {}
Config.hostgroups = {}
Config.hostgroups["ALL"] = {"name": "ALL",
                            "vars": {}, "hosts": [], "groups": []}
for hostname, host in ((str(k), v) for k, v in hosts.items()):
    Config.hosts[hostname] = host_ = {"name": hostname, "vars": {}}
    for groupname in host["groups"]:
        if groupname not in Config.hostgroups:
            Config.hostgroups[groupname] = {
                "name": groupname, "vars": {}, "hosts": [host_], "groups": []}
            Config.hostgroups["ALL"].groups.extend(
                [g for n, g in Config.hostgroups[groupname].items(
                ) if n not in Config.hostgroups["ALL"].groups],
            )
        else:
            Config.hostgroups[groupname].hosts.append(host_)

for groupname, group in ((str(k), v) for k, v in hostgroups.items()):
    group_ = Config.hostgroups[groupname]
    group_.vars = group.get("vars", {})
    if groupname not in Config.hostgroups["ALL"].groups:
        Config.hostgroups[groupname].groups.append(group_)
```

**Comment by zware** [comment]
This is not a bug in Python.  `omegaconf`'s `ListConfig.append` method is doing its best to hide self-incriminating evidence here:

https://github.com/omry/omegaconf/blob/v2.3.0/omegaconf/listconfig.py#L296-L301
