### ISSUE TITLE
"AssertionError: SRE module mismatch" in /main/Lib/tokenize.py

### ISSUE THREAD

**Issue by iladshyan** [python/cpython#124114]
# Bug report

### There is an AssertionError when running /main/Lib/tokenize.py.

> python --version
Python 3.11.1

Here is the Traceback:
Traceback (most recent call last):
  File "c:\Users\<USER>\py\cpython\Lib\tokenize.py", line 33, in <module>    
    import re
  File "c:\Users\<USER>\py\cpython\Lib\re\__init__.py", line 126, in <module>
    from . import _compiler, _parser
  File "c:\Users\<USER>\py\cpython\Lib\re\_compiler.py", line 18, in <module>
    assert _sre.MAGIC == MAGIC, "SRE module mismatch"
           ^^^^^^^^^^^^^^^^^^^
AssertionError: SRE module mismatch

I am somewhat new to this by the way.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by iladshyan** [comment]
> Hello!
> 
> This often happens when you switching through the branches and forget to clean repository.
> 
> Try this:
> 
> ```
> 
> git clean -fdx
> 
> pcbuild/build.bat -c Debug
> 
> ```

Thank you for the quick response! I'll try out your fix, will update you on it soon.

**Comment by JelleZijlstra** [comment]
This can also happen if you use an installed Python to run code from the repository directly.

**Comment by terryjreedy** [comment]
I have gotten this or similar just from not recompiling after an update.

**Comment by iladshyan** [comment]
> This can also happen if you use an installed Python to run code from the repository directly.

This should be it. I didn't know you have to run the tokenizer from the builded python, I thought it was just a normal python script and ran it in my installed python. My bad
