### ISSUE TITLE
Improve speed of shutil.copytree

### ISSUE THREAD

**Issue by mengqinyuan** [python/cpython#124117]
I wrote a discussion on disscuss.python.org, Link [here](https://discuss.python.org/t/significantly-improve-shutil-copytree/62078). Do you think it is good? What I need to improve? You should mention the comments because they are more useful than the article, I think.

**Comment by Wulian233** [comment]
Oh, you didn't create the issue in temple format, which might cause some inconvenience😟

**Comment by mengqinyuan** [comment]
> Oh, you didn't create the issue in temple format, which might cause some inconvenience😟

What is the temple format?

**Comment by Wulian233** [comment]
https://github.com/python/cpython/issues/new?assignees=&labels=type-feature&projects=&template=feature.yml

The template Feature or enhancement issue will automatically add type-feature labels, and there is a area for describing the issue and previous discussions

An example: https://github.com/python/cpython/issues/124111

**Comment by mengqinyuan** [comment]
Thank you.

**Comment by rruuaanng** [comment]
> I wrote a discussion on disscuss.python.org, Link [here](https://discuss.python.org/t/significantly-improve-shutil-copytree/62078). Do you think it is good? What I need to improve? You should mention the comments because they are more useful than the article, I think.

I‘m read your article, and I think that the time consumption of copytree comes from the recursive backtracking. If you could eliminate that, the speed would increase exponentially. Of course, this idea is based on not using any external syntax.

**Comment by mengqinyuan** [comment]
Ok，I write a test : 

```python
import os
import shutil

def copytree_iterative(src, dst, symlinks=False, ignore=None,
                       copy_function=shutil.copy2, ignore_dangling_symlinks=False,
                       dirs_exist_ok=False):
    """Copy a directory recursively using an iterative approach."""
    if os.path.exists(dst) and not dirs_exist_ok:
        raise FileExistsError(f"Destination path '{dst}' already exists")

    if not os.path.exists(dst):
        os.makedirs(dst)

    names = os.listdir(src)
    if ignore is not None:
        ignored_names = ignore(src, names)
    else:
        ignored_names = set()

    entries = [(src, dst, name) for name in names if name not in ignored_names]

    while entries:
        srcobj, dstname, srcentry_name = entries.pop()
        srcentry_path = os.path.join(srcobj, srcentry_name)
        dstentry_path = os.path.join(dstname, srcentry_name)

        if os.path.isdir(srcentry_path):
            if not os.path.exists(dstentry_path):
                os.makedirs(dstentry_path)
            entries.extend([(srcentry_path, dstentry_path, name)
                            for name in os.listdir(srcentry_path)
                            if name not in ignored_names])
        else:
            copy_function(srcentry_path, dstentry_path)

def create_source_directory(directory_path):
    try:
        os.makedirs(directory_path)
        print(f"Directory '{directory_path}' created successfully.")
    except FileExistsError:
        print(f"Directory '{directory_path}' already exists.")
    except Exception as e:
        print(f"Error creating directory: {e}")

def write_files(directory_path, num_files):
    for i in range(num_files):
        file_path = os.path.join(directory_path, f"file_{i}.txt")
        with open(file_path, "w") as file:
            file.write(f"This is file {i}.")
import time
def benchmark_copytree(func, *args):
    start_time = time.perf_counter()
    func(*args)
    end_time = time.perf_counter()
    print(f"{func.__name__} : {end_time - start_time:.6f} seconds")

def rmove_directory(directory_path):
    try:
        shutil.rmtree(directory_path)
        print(f"Directory '{directory_path}' removed successfully.")
    except FileNotFoundError:
        print(f"Directory '{directory_path}' does not exist.")
    except Exception as e:
        print(f"Error removing directory: {e}")

# Example usage
if __name__ == "__main__":
    create_source_directory("source")
    write_files("source", 50000)

    benchmark_copytree(copytree_iterative, "source", "destination")
    rmove_directory("source")
    rmove_directory("destination") # remove folders for the next time test

    create_source_directory("source")
    write_files("source", 50000)
    benchmark_copytree(shutil.copytree, "source", "destination")

    rmove_directory("source")
    rmove_directory("destination")

```

Result here: 
copytree : 140.506028 seconds
copytree_iterative : 147.229518 seconds

I use newest python 3.12.6, Core i5 8th Gen.

**Comment by mengqinyuan** [comment]
Could someone help me to write more difficult tests? I don't have much time becuase I have to go school. **Sorry**

**Comment by rruuaanng** [comment]
> Ok，I write a test : 
> 
> 
> 
> ```python
> 
> import os
> 
> import shutil
> 
> 
> 
> def copytree_iterative(src, dst, symlinks=False, ignore=None,
> 
>                        copy_function=shutil.copy2, ignore_dangling_symlinks=False,
> 
>                        dirs_exist_ok=False):
> 
>     """Copy a directory recursively using an iterative approach."""
> 
>     if os.path.exists(dst) and not dirs_exist_ok:
> 
>         raise FileExistsError(f"Destination path '{dst}' already exists")
> 
> 
> 
>     if not os.path.exists(dst):
> 
>         os.makedirs(dst)
> 
> 
> 
>     names = os.listdir(src)
> 
>     if ignore is not None:
> 
>         ignored_names = ignore(src, names)
> 
>     else:
> 
>         ignored_names = set()
> 
> 
> 
>     entries = [(src, dst, name) for name in names if name not in ignored_names]
> 
> 
> 
>     while entries:
> 
>         srcobj, dstname, srcentry_name = entries.pop()
> 
>         srcentry_path = os.path.join(srcobj, srcentry_name)
> 
>         dstentry_path = os.path.join(dstname, srcentry_name)
> 
> 
> 
>         if os.path.isdir(srcentry_path):
> 
>             if not os.path.exists(dstentry_path):
> 
>                 os.makedirs(dstentry_path)
> 
>             entries.extend([(srcentry_path, dstentry_path, name)
> 
>                             for name in os.listdir(srcentry_path)
> 
>                             if name not in ignored_names])
> 
>         else:
> 
>             copy_function(srcentry_path, dstentry_path)
> 
> 
> 
> def create_source_directory(directory_path):
> 
>     try:
> 
>         os.makedirs(directory_path)
> 
>         print(f"Directory '{directory_path}' created successfully.")
> 
>     except FileExistsError:
> 
>         print(f"Directory '{directory_path}' already exists.")
> 
>     except Exception as e:
> 
>         print(f"Error creating directory: {e}")
> 
> 
> 
> def write_files(directory_path, num_files):
> 
>     for i in range(num_files):
> 
>         file_path = os.path.join(directory_path, f"file_{i}.txt")
> 
>         with open(file_path, "w") as file:
> 
>             file.write(f"This is file {i}.")
> 
> import time
> 
> def benchmark_copytree(func, *args):
> 
>     start_time = time.perf_counter()
> 
>     func(*args)
> 
>     end_time = time.perf_counter()
> 
>     print(f"{func.__name__} : {end_time - start_time:.6f} seconds")
> 
> 
> 
> def rmove_directory(directory_path):
> 
>     try:
> 
>         shutil.rmtree(directory_path)
> 
>         print(f"Directory '{directory_path}' removed successfully.")
> 
>     except FileNotFoundError:
> 
>         print(f"Directory '{directory_path}' does not exist.")
> 
>     except Exception as e:
> 
>         print(f"Error removing directory: {e}")
> 
> 
> 
> # Example usage
> 
> if __name__ == "__main__":
> 
>     create_source_directory("source")
> 
>     write_files("source", 50000)
> 
> 
> 
>     benchmark_copytree(copytree_iterative, "source", "destination")
> 
>     rmove_directory("source")
> 
>     rmove_directory("destination") # remove folders for the next time test
> 
> 
> 
>     create_source_directory("source")
> 
>     write_files("source", 50000)
> 
>     benchmark_copytree(shutil.copytree, "source", "destination")
> 
> 
> 
>     rmove_directory("source")
> 
>     rmove_directory("destination")
> 
> 
> 
> ```
> 
> 
> 
> Result here: 
> 
> copytree : 140.506028 seconds
> 
> copytree_iterative : 147.229518 seconds
> 
> 
> 
> I use newest python 3.12.6, Core i5 8th Gen.
> 
> 
> 
> 

Oh，I don't want it
