### ISSUE TITLE
New build warnings: `warning: unused function 'round_down' [-Wunused-function]`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#124122]
# Bug report

### Bug description:

Popped up during the build on macOS
```
./Modules/_ctypes/cfield.c:49:12: warning: unused function 'round_down' [-Wunused-function]
Py_ssize_t round_down(Py_ssize_t numToRound, Py_ssize_t multiple)
           ^
./Modules/_ctypes/cfield.c:59:12: warning: unused function 'round_up' [-Wunused-function]
Py_ssize_t round_up(Py_ssize_t numToRound, Py_ssize_t multiple)
           ^
./Modules/_ctypes/cfield.c:409:12: warning: unused function 'BUILD_SIZE' [-Wunused-function]
Py_ssize_t BUILD_SIZE(Py_ssize_t bitsize, Py_ssize_t offset) {
           ^
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-124123

**Comment by picnixz** [comment]
Irit already took care of that here I think: https://github.com/python/cpython/pull/124010

**Comment by Eclips4** [comment]
> Irit already took care of that here I think: #124010

Yeah, you're right. I'm going to close this one and attached PR, sorry for making noise!

**Comment by vstinner** [comment]
Fixed by https://github.com/python/cpython/commit/453da532fee26dc4f83d4cab77eb9bdb17b941e6
