### ISSUE TITLE
Incorrect shutil.copytree() behaviour with symlink=False and ignore_dangling_symlinks=True

### ISSUE THREAD

**Issue by dabuahoid** [python/cpython#124132]
# Bug report

### Bug description:

Duplicate of https://github.com/python/cpython/issues/91205 to raise again attention to quickly fix this bug since still present in Python 3.12.6!

### CPython versions tested on:

3.8, 3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by hugovk** [comment]
Thanks but we don't need two issues for this.
