### ISSUE TITLE
ntpath not adding slash after drive letters

### ISSUE THREAD

**Issue by matan1008** [python/cpython#124167]
# Bug report

### Bug description:

```python
import ntpath
print(ntpath.join('c:', 'x', 'y'))
```

I would expect the following code to print `'c:\\x\\y'`, yet it prints `'c:x\\y'`, Would you expect a PR that changes the current behaviour? 

### CPython versions tested on:

3.10, 3.11, 3.12, 3.13, CPython main branch

### Operating systems tested on:

Linux, Windows

**Comment by Wulian233** [comment]
In my previous PR
https://github.com/python/cpython/pull/122372
I found that `ntpath` and `nturl2path` are not documented. In the comment of nturl2path, it is mentioned that it is only used by urllib, but it is not in the urllib folder and is not a private module with an _ prefix, so we can import and use it freely.

https://github.com/python/cpython/blob/main/Lib/nturl2path.py

Searching for "import nturl2path" on GitHub also shows that a considerable number of people use it. I am curious why these two modules do not have documentation, is it a historical legacy issue? 

https://github.com/python/cpython/issues/120423

I want to answer this question, but I don't know if it's a feature or a bug, so we have to read the source code

@hugovk sorry ping, what do you think🤔

**Comment by Wulian233** [comment]
oh, ntpath is a part of os.path 
https://github.com/python/cpython/blob/main/Doc%2Flibrary%2Fos.path.rst#L7-L8

**Comment by terryjreedy** [comment]
In CommandPrompt, `cd C:Users` fails.  If same is true of `os.chdir('C:Users')`, then this seems a bug.

**Comment by barneygale** [comment]
https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file says:

> If a file name begins with only a disk designator but not the backslash after the colon, it is interpreted as a relative path to the current directory on the drive with the specified letter. Note that the current directory may or may not be the root directory depending on what it was set to during the most recent "change directory" operation on that disk. Examples of this format are as follows:

> - "C:tmp.txt" refers to a file named "tmp.txt" in the current directory on drive C.
> - "C:tempdir\tmp.txt" refers to a file in a subdirectory to the current directory on drive C.

**Comment by zware** [comment]
This is not a bug, it's an oddity of Windows file paths.  On POSIX-ish platforms, there are relative (`some/path/rooted/in/cwd/example.py`) and absolute (`/some/path/rooted/at/the/root/example.py`) paths.  On Windows each drive has its own current working directory (cwd), so there are relative (`some\path\rooted\in\cwd\example.py`), absolute (`C:\some\path\on\drive_c\rooted\in\drive_c_root\example.py`), drive-relative[^1] (`C:some\path\on\drive_c\rooted\in\drive_c_cwd\example.py`), and drive-agnostic-absolute[^1] (`\some\path\on\current\drive\at\its\root\example.py`).  `ntpath` can't guess what kind you actually want, so if you want a rooted path you need to provide the root in addition to the drive.

[^1]: Not sure what the real names should be

**Comment by matan1008** [comment]
So in the above example (or in pathlib) what is the correct way to get `PureWindowsPath('c:/x/y')`? `PureWindowsPath('c:') / '\\x' / 'y'`?

**Comment by zware** [comment]
That would be fine, as would `PureWindowsPath('c:\\') / 'x' / 'y'` or `PureWindowsPath('c:') / '/' / 'x' / 'y'`
