### ISSUE TITLE
Delete the redundant conditional statements in traceback.c

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#124265]
# Feature or enhancement

```python
```
https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L974-L985

In the above code, it seems that  it's redundant.
https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L983

Removing this extra if statement may eliminate the time consumed by the conditional statement.
In https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L975-L976
if frame is empty, it may not be executed
https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L979-L982
So it will not be executed
https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L983-L986

Logically speaking, if the `frame` is not NULL, then `frame->previous` can't be NULL either. This means `frame->previous->previous` won't be NULL either. If the `frame` has a forward link, `frame->next`, then it will have a unique successor.

If there are errors in my proposal or I don't understand the code base, please point out my mistakes, thanks.
### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-124272

**Comment by skirpichev** [comment]
> Logically speaking, if the frame is not NULL, then frame->previous can't be NULL either.

Yet, this is tested on L976.  Either above statement is false, or L976 test could be removed as well.

**Comment by rruuaanng** [comment]
> > Logically speaking, if the frame is not NULL, then frame->previous can't be NULL either.
> 
> Yet, this is tested on L976. Either above statement is false, or L976 test could be removed as well.

Maybe I need a minimal test that will trigger the deletion of the if statement.

**Comment by rruuaanng** [comment]
I hid the targets I needed to modify by commenting them out.
https://github.com/python/cpython/blob/7a2d77c903f29d7ea08b870b8e3fa2130f667a59/Python/traceback.c#L983-L985

I then ran the tests using `./python Lib\test\test_traceback.py`.
It seemed to run well as it passed all 347 tests in about 8.3 seconds.
```
PS E:\code\cc\cpython\alpha\cpython-main> ./python .\Lib\test\test_traceback.py
Running Debug|x64 interpreter...
...........................................................................................................................................................................................................................................................................................................................................................
----------------------------------------------------------------------
Ran 347 tests in 8.303s

OK
```

**Comment by skirpichev** [comment]
Well, it's clear, that removing this check trigger CI failures.  I think it's required.
