### ISSUE TITLE
http.server.BaseHTTPRequestHandler.parse_request func has bug!!!

### ISSUE THREAD

**Issue by Firebasky** [python/cpython#124271]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
in:https://github.com/python/cpython/blob/main/Lib/http/server.py#L307
If the requested version is HTTP/2, there will be an exception.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by rruuaanng** [comment]
When writing issue titles, please skip any symbols that don’t relate to the content. thanks.

**Comment by rruuaanng** [comment]
> # Bug report
> ### Bug description:
> 
> ```python
> # Add a code block here, if required
> ```
> 
> in:https://github.com/python/cpython/blob/main/Lib/http/server.py#L307 If the requested version is HTTP/2, there will be an exception.
> ### CPython versions tested on:
> 
> CPython main branch
> ### Operating systems tested on:
> 
> macOS

Maybe you should show the error codefile.

**Comment by rruuaanng** [comment]
I'm writing a simple test
```
import http.server
import socketserver
from typing import override

PORT = 8000

class Server(http.server.SimpleHTTPRequestHandler):
    @override
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(b'''
                         <html>
                         <body>
                            <h1>Hello, world!</h1>
                         </body>
                         </html>''')

with socketserver.TCPServer(('', PORT), Server) as httpd:
    print(f'run server on {PORT}')
    httpd.serve_forever()
```
My bash
```
@RUANG MINGW64 /e/code/cc/cpython/alpha/cpython-main$> curl -v --http2 http://localhost:8000
*   Trying 127.0.0.1:8000...
* Connected to localhost (127.0.0.1) port 8000 (#0)
> GET / HTTP/1.1
> Host: localhost:8000
> User-Agent: curl/7.87.0
> Accept: */*
> Connection: Upgrade, HTTP2-Settings
> Upgrade: h2c
> HTTP2-Settings: AAMAAABkAAQCAAAAAAIAAAAA
>
* Mark bundle as not supporting multiuse
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< Server: SimpleHTTP/0.6 Python/3.14.0a0
< Date: Fri, 20 Sep 2024 08:45:02 GMT
< Content-type: text/html
<

                         <html>
                         <body>
                            <h1>Hello, world!</h1>
                         </body>
                         </html>* Closing connection 0
```
So, It's ok.

**Comment by rruuaanng** [comment]
I wrote a testfile, server
```
import http.server
import socketserver
from typing import override

PORT = 8000

class Server(http.server.SimpleHTTPRequestHandler):
    @override
    def do_GET(self):
        self.send_response(200)
        self.send_header("Content-type", "text/html")
        self.end_headers()
        self.wfile.write(b'''
                         <html>
                         <body>
                            <h1>Hello, world!</h1>
                         </body>
                         </html>''')

with socketserver.TCPServer(('', PORT), Server) as httpd:
    print(f'run server on {PORT}')
    httpd.serve_forever()
```
client
```
import httpx

url = "http://localhost:8000"

with httpx.Client(http2=True) as client:
    r = client.get(url)
    print(f'status: {r.status_code}')
    print(f'body: {r.text}')
```

My bash
```
$ python Issue/client.py 
status: 200
body:
                         <html>
                         <body>
                            <h1>Hello, world!</h1>
                         </body>
                         </html>
```

**Comment by skirpichev** [comment]
> If the requested version is HTTP/2, there will be an exception.

Is this a legal string?

**Comment by skirpichev** [comment]
Quote RFC 2145:
```
      HTTP uses a "<major>.<minor>" numbering scheme to indicate
      versions of the protocol. The protocol versioning policy is
      intended to allow the sender to indicate the format of a message
      and its capacity for understanding further HTTP communication,
      rather than the features obtained via that communication.  No
      change is made to the version number for the addition of message
      components which do not affect communication behavior or which
      only add to extensible field values.  The <minor> number is
      incremented when the changes made to the protocol add features
      which do not change the general message parsing algorithm, but
      which may add to the message semantics and imply additional
      capabilities of the sender. The <major> number is incremented when
      the format of a message within the protocol is changed."
```
It doesn't say that either part is optional.

I don't think it's a bug.

**Comment by Firebasky** [comment]
> > # Bug report
> > ### Bug description:
> > ```python
> > # Add a code block here, if required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in:https://github.com/python/cpython/blob/main/Lib/http/server.py#L307 If the requested version is HTTP/2, there will be an exception.
> > ### CPython versions tested on:
> > CPython main branch
> > ### Operating systems tested on:
> > macOS
> 
> Maybe you should show the error codefile. And when writing issue titles, please skip any symbols that don’t relate to the content. thanks.



> > # Bug report
> > ### Bug description:
> > ```python
> > # Add a code block here, if required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in:https://github.com/python/cpython/blob/main/Lib/http/server.py#L307 If the requested version is HTTP/2, there will be an exception.
> > ### CPython versions tested on:
> > CPython main branch
> > ### Operating systems tested on:
> > macOS
> 
> Maybe you should show the error codefile. And when writing issue titles, please skip any symbols that don’t relate to the content. thanks.

I got it!

**Comment by Firebasky** [comment]
> > # Bug report
> > ### Bug description:
> > ```python
> > # Add a code block here, if required
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > in:https://github.com/python/cpython/blob/main/Lib/http/server.py#L307 If the requested version is HTTP/2, there will be an exception.
> > ### CPython versions tested on:
> > CPython main branch
> > ### Operating systems tested on:
> > macOS
> 
> Maybe you should show the error codefile. And when writing issue titles, please skip any symbols that don’t relate to the content. thanks.

i got it.

**Comment by skirpichev** [comment]
> POST /test HTTP/2

@Firebasky, could you please point to RFC, which permits such query?

**Comment by rruuaanng** [comment]
> > POST /test HTTP/2
> 
> @Firebasky, could you please point to RFC, which permits such query?

I think this issue can be close.
![图片](https://github.com/user-attachments/assets/34595a7a-30a6-4b89-bfb0-ae0a821c8f8f)

above img from RFC7540.

**Comment by skirpichev** [comment]
Ok, RFC for HTTP-Version in the Request-Line was [quoted above](https://github.com/python/cpython/issues/124271#issuecomment-2363243724).

I'm going to close this, unless OP will find a standard, which permit to omit minor version in HTTP/2.
