### ISSUE TITLE
 Request for Clarification on Experimental Status of Free-Threaded Builds with GIL in CPython 3.13

### ISSUE THREAD

**Issue by briensea** [python/cpython#124287]
# Documentation

I’ve been exploring the documentation on free-threaded builds in CPython 3.13, specifically around the use of the `--disable-gil` option during build configuration.

The documentation states:

> `--disable-gil` enables experimental support for running Python without the Global Interpreter Lock (GIL): free-threading build.  
> ([Source: Python 3.13 Configuration](https://docs.python.org/3.13/using/configure.html))

It also mentions that free-threaded execution:

> allows for full utilization of available CPU cores by running threads in parallel. The mode is experimental, with some expected bugs and a substantial single-threaded performance hit. Free-threaded builds support optionally running with the GIL enabled at runtime using the environment variable `PYTHON_GIL` or the command-line option `-X gil`.  
> ([Source: What's New in Python 3.13](https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-free-threaded-cpython))

However, it's unclear whether a free-threaded build **with** the GIL enabled (either via the `PYTHON_GIL` environment variable or `-X gil` option) should still be considered **experimental**. My specific questions are:

1. Is enabling the GIL at runtime (in a free-threaded build) still part of the experimental feature set, or is this a more stable pathway for Python 3.13?
2. Are there any known limitations or issues when running a free-threaded build with the GIL enabled, in contrast to the standard GIL-enabled CPython build?

I’ve been unable to find a clear answer to this and would appreciate any additional insights or clarifications on this point.

Thank you for your time and for all the great work on Python!

**Comment by colesbury** [comment]
Yes, the free-threaded build is experimental including enabling the GIL at runtime.

The most important limitation is that you still need to compile C extensions specifically for the free-threaded build. Looking at https://peps.python.org/pep-0703/#backwards-compatibility:

* Refcounting always uses biased refcounting in the free-threaded build, with the potentital associated changes in lifetimes. (Some objects may live longer than they would normally. I don't think this is likely to come up very often)
* Mimalloc is always used so there are still the limitations on the memory allocator mentioned in the PEP

**Comment by corona10** [comment]
To make an addition to Sam's comment,

IMO, everything under the `--disable-gil ` build should be considered experimental. Every implementation detail can be changed in a future version, and even behavior details can be changed.
And the following command says everything :)

![Screenshot from 2024-09-21 11-52-36](https://github.com/user-attachments/assets/776c48dc-f580-48e6-a751-b167ae7e5c96)
