### ISSUE TITLE
Asterisk (*) list duplication bug

### ISSUE THREAD

**Issue by muffpy** [python/cpython#124238]
# Bug report

### Bug description:

```python
>>> m = [[] for i in range(5)] # normal list
>>> l = [[]] * 5 # buggy list
>>> m
[[], [], [], [], []]
>>> l
[[], [], [], [], []]
>>> m == l
True
>>> m[0].append(1)
>>> l[0].append(1)
>>> m == l
False
>>> m
[[1], [], [], [], []]
>>> l
[[1], [1], [1], [1], [1]]
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Hello!
There's no bug, this behavior is expected: https://docs.python.org/3/faq/programming.html#how-do-i-create-a-multidimensional-list

Also, if you read the message that I just deleted, please don't download anything from this link. It's spam.
Note that this repository is intended as a CPython bug tracker, ask python-related questions there: https://discuss.python.org/c/users/7
