### ISSUE TITLE
RFC 9637 not implemented by ipaddress module

### ISSUE THREAD

**Issue by csirmazbendeguz** [python/cpython#124217]
# Bug report

### Bug description:

```python
>>> import ipaddress
>>> ip_address = ipaddress.ip_address("3fff::")
>>> ip_address.is_global
True
```

[RFC 9637](https://www.rfc-editor.org/rfc/rfc9637.html) registered the address block `3fff::/20` as **NOT** globally reachable in the [IANA IPv6 Special-Purpose Address Registry](https://www.iana.org/assignments/iana-ipv6-special-registry/iana-ipv6-special-registry.xhtml), but the `ipaddress` module doesn't respect this.

### CPython versions tested on:

3.11

### Operating systems tested on:

macOS

### Linked PRs
* gh-124240
* gh-124282
* gh-124283

**Comment by y5c4l3** [comment]
Added it to reserved blocks and unit tests: #124240

**Comment by ZeroIntensity** [comment]
@vstinner the 3.13 backport PR is still open, are we sure this should be closed?

**Comment by vstinner** [comment]
> @vstinner the 3.13 backport PR is still open, are we sure this should be closed?

It's easier for me to close the issue, to help me tracking what has been done or not.

The 3.13 branch is blocked until Python 3.13 final release. After that, all 3.13 changes will be merged one by one.
