### ISSUE TITLE
The index method of the tuple is incorrect

### ISSUE THREAD

**Issue by liuhuang2099** [python/cpython#124268]
# Bug report

### Bug description:

```python
# The result is 0? why? I think it should be three
```
tupleTest = (1,5,'gg',True,'kk',False)
print(tupleTest.index(True))

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
That's because ``1==True``:)

**Comment by skirpichev** [comment]
The [algorithm](https://github.com/python/cpython/blob/3e36e5aef18e326f5d1081d73ee8d8fefa1d82f8/Objects/tupleobject.c#L568-L595) roughly equal to:
```pycon
def index(tup, val):
    for i, el in enumerate(tup):
        if el == val:
            return i
    raise ValueError
```

Probably this could be closed.

**Comment by liuhuang2099** [comment]
> The [algorithm](https://github.com/python/cpython/blob/3e36e5aef18e326f5d1081d73ee8d8fefa1d82f8/Objects/tupleobject.c#L568-L595) roughly equal to:
> 
> ```python
> def index(tup, val):
>     for i, el in enumerate(tup):
>         if el == val:
>             return i
>     raise ValueError
> ```
> 
> Probably this could be closed.
Well, thank you! you gave a good idea, I can use enumeration method to match
for i,j in enumerate(tupleTest):
    print(i,j)

Returned result:
0 1
1 5
2 gg
3 True
4 kk
5 False

**Comment by skirpichev** [comment]
Ok, I'm closing this.  I think that [documentation](https://docs.python.org/3/library/stdtypes.html#typesseq-common) is clear, that for membership tests (``x in s``) or in ``s.index(x)`` - tested equality of elements.

Perhaps, next time you could ask first on https://discuss.python.org/c/help/7, if you find something surprising in the language like that and docs doesn't help you.

@ZeroIntensity for second look

**Comment by ZeroIntensity** [comment]
Yeah, `index` uses the C equivalent of an `==` comparison internally, so this is expected. Thank you, Sergey!
