### ISSUE TITLE
str.format() raises misleading error when using negative indices

### ISSUE THREAD

**Issue by makukha** [python/cpython#124294]
# Bug report

### Bug description:

This is a duplicate of #95846. The problem [appeared on Stackoverflow](https://stackoverflow.com/questions/78997513/why-is-there-typeerror-string-indices-must-be-integers-when-using-negative-in), but I didn't manage to reopen the old issue.

```doctest
>>> x = [1,2,3]
>>> '{x[-1]}'.format(x=x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list indices must be integers or slices, not str
>>> x = (1,2,3)
>>> '{x[-1]}'.format(x=x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple indices must be integers or slices, not str
```

### Expected results:
* Correct error message: TypeError: ___ indices must be **_non-negative_** integers or slices
* Documentation updated to clearly state that list indices can't be negative.

As long as this issue is not critical, I would be glad to provide PR.

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-124372

**Comment by rruuaanng** [comment]
This issue was raised in https://github.com/python/cpython/issues/95846.

Proposed by `JelleZijlstra`, this modification may compromise backward compatibility, and I suggest that perhaps this issue can be ignored.

**Comment by makukha** [comment]
@rruuaanng what about updating docs? Should I create new issue?

**Comment by rruuaanng** [comment]
> @rruuaanng
> 
>     1. Can error message be updated like "... indices must be non-negative integers or slices"?
> 
>     2. Should docs be updated to clearly state that only non-negative integers are allowed?

I think we could add an extra tip, like suggesting the use of `f'...'` syntax, or mention that this syntax doesn't allow negative indexing.

Maybe this issue should be left for the core developers to answer.

**Comment by ericvsmith** [comment]
It's not so easy to modify the exception message, because where it's raised there's no knowledge of what the caller is expecting. And duplicating the logic at the caller site just to change the error message would be a maintenance burden. But if you come up with a patch I'd look at it.

**Comment by ericvsmith** [comment]
Per the discussion on the PR, I'm closing this.
