### ISSUE TITLE
Reference counting stats do not account for immortal objects.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#124284]
### Bug description:

The reference counting stats ([for example](https://github.com/faster-cpython/benchmarking-public/blob/main/results/bm-20240914-3.14.0a0-401fff7-PYTHON_UOPS/bm-20240914-azure-x86_64-python-401fff7423ca3c8bf1d0-3.14.0a0-401fff7-pystats.md#object-stats)) show stats for increfs and decrefs (both in the interpreter and in the rest of the executable).

One might assume that is the number of `Py_INCREF` and `Py_DECREF`s executed, but it is not. It is the number of `Py_INCREF` and `Py_DECREF` where the object in question is mortal. We should add stats for `Py_INCREF` and `Py_DECREF`s of immortal objects as well.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-124288

**Comment by vstinner** [comment]
@markshannon: I suppose that this issue can now be closed since the change https://github.com/python/cpython/commit/c87b0e4a462f98c418f750c6c95d4d8715c38332 was merged.
