### ISSUE TITLE
built python from source but pip executables in scripts are for the wrong cpu type

### ISSUE THREAD

**Issue by wmjb** [python/cpython#124290]
# Bug report

### Bug description:

I've cross compiled python 3.12.x for windows arm32, however when using python there seems to be confusion about what processor type of the system it is running on, for example when pip creates an executable in scripts folder it builds it for the x86 processor type.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by brianschubert** [comment]
Could you clarify how you’re building CPython, and how you’re running pip (what commands, what output)? 

Are you encountering any issues with CPython itself, or just with pip? If only with pip, this may be an issue for https://github.com/pypa/pip (pip is a different project than CPython).

**Comment by AA-Turner** [comment]
Per the above, please provide a reproducer demonstrating that fault lies with CPython. Closing until then.

A
