### ISSUE TITLE
% in documentation breaks Argumentparser

### ISSUE THREAD

**Issue by BIRDSLab** [python/cpython#124260]
# Bug report

### Bug description:

```python
from argparse import ArgumentParser
parser = ArgumentParser()
parser.add_argument(
    "-v", dest="verbose", 
    help="duck around %", 
    action='store_true' 
)    
# Find out
options = parser.parse_args()
```
Run this with a '-h' on the commandline, and watch the pretty backtrace

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by ZeroIntensity** [comment]
This is intended, `%` is used for format strings. To escape it, use `%%` (see [the docs](https://docs.python.org/3/library/argparse.html#help)):

```py
parser.add_argument(
    "-v", dest="verbose", 
    help="duck around %%",
    action='store_true' 
)    
```

**Comment by terryjreedy** [comment]
Please ask about puzzling behavior on https://discuss.python.org/c/help/7, where answers are more visible to others.
