### ISSUE TITLE
Windows Installer update with "keep current options" uninstalled the free-threaded binaries

### ISSUE THREAD

**Issue by TBBle** [python/cpython#124254]
# Bug report

### Bug description:

I used the installer to upgrade from a Python 3.13.0rc1 install to a Python 3.13.0rc2 install. In the 3.13.0rc1 install, I had installed the free-threaded binaries.

When upgrading, I chose the first option, "Upgrade Now".

After the upgrade, the free-threaded binaries were no longer installed, and I had to rerun the installer and modify the install to add them.

Other non-default install options, such as installing the debug binaries, were not lost.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-124279
* gh-124347

**Comment by zooba** [comment]
Yeah, looks like it was missed from the [list of features](https://github.com/python/cpython/blob/main/Tools/msi/bundle/bootstrap/PythonBootstrapperApplication.cpp#L200) in the bootstrapper. It should only need to be added there.

We can fix it in 3.13.1. Anyone upgrading from RC will lose the setting, but that's okay. It's installed properly by 3.13.0 and so updates after that will be fine.

**Comment by itamaro** [comment]
@zooba, with gh-124279 (+backport) merged, is there anything left to do here?
closing the issue, but please re-open if there's more left to do!
