### ISSUE TITLE
Modules being cached and not being able to reload the modules until uninstall and reinstall

### ISSUE THREAD

**Issue by zarif98** [python/cpython#124354]
# Bug report

### Bug description:

I have been modifying this GitHub repo for awhile and have noticed that I am unable to see any of the changes being made to my code. Running my code with debugger and breakpoints also does not let the breakpoint hit after I've made my changes to the code. The only way for my breakpoints to hit is when I uninstall and reinstall Python 3.12.

I have tried reloading my modules every time which does not work. I have also disallowed Python caching which also does not work. The only promise that I have seen is installing and reinstalling Python 3.12

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
Please read the [devguide](https://devguide.python.org/getting-started/setup-building/) about how to build an interpreter.
You need to clone CPython, make changes and then build the interpreter. So, there's no bug.


This repository is intended as a CPython bug tracker, if you have any questions related to Python/CPython please ask it there: https://discuss.python.org/c/users/7
