### ISSUE TITLE
`_PyObject_IS_GC()` should not use `PyType_HasFeature()`

### ISSUE THREAD

**Issue by neonene** [python/cpython#124344]
# Feature or enhancement

### Proposal:

`_PyObject_IS_GC()` is one of the most frequently used functions, which keeps using `PyType_HasFeature()` rather than `_PyType_HasFeature()`.

I know it has no performance issues since introduced, but switching to use `_PyType_HasFeature()` would make more sense:

* Include/internal/pycore_object.h

```c
// Fast inlined version of PyObject_IS_GC()
static inline int
_PyObject_IS_GC(PyObject *obj)
{
    PyTypeObject *type = Py_TYPE(obj);
    return (PyType_IS_GC(type)
            && (type->tp_is_gc == NULL || type->tp_is_gc(obj)));
}
...
// Fast inlined version of PyType_IS_GC()
#define _PyType_IS_GC(t) _PyType_HasFeature((t), Py_TPFLAGS_HAVE_GC)
```

* Include/objimpl.h
```c
/* Test if a type has a GC head */
#define PyType_IS_GC(t) PyType_HasFeature((t), Py_TPFLAGS_HAVE_GC)
```

cc @vstinner

### Linked PRs
* gh-124349

**Comment by vstinner** [comment]
Do you want to propose a PR?

**Comment by vstinner** [comment]
Implemented in https://github.com/python/cpython/commit/d9d5b3d2ef770224b39987dbce7bb5c616fe3477.
