### ISSUE TITLE
Optimize Endianness Handling in ctypes Module

### ISSUE THREAD

**Issue by Harikrishna-Srinivasan** [python/cpython#124351]
# Feature or enhancement

### Proposal:

1. Global variable _OTHER_ENDIAN, in the _other_endian function to check for endianness but declared at the module level, leading to potential side effects.

Redundant Type Checks slows down recursion:
```
if hasattr(typ, _OTHER_ENDIAN):
if isinstance(typ, _array_type):
if issubclass(typ, (Structure, Union)):
```
Issue: Multiple checks on each call can be inefficient, especially if called frequently.

2. In the __setattr__ method of the _swapped_meta class,
```fields = []
for desc in value:
    fields.append((name, _other_endian(typ)) + rest)
```
Issue: Always creates a new list, even when no modifications are needed, which adds overhead.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-124355
* gh-124407
* gh-124410

**Comment by skirpichev** [comment]
> Global variable _OTHER_ENDIAN, in the _other_endian function to check for endianness but declared at the module level, leading to potential side effects.

Why you think so, could you provide an example?

> Always creates a new list, even when no modifications are needed, which adds overhead.

How you are suggesting to avoid this?

**Comment by picnixz** [comment]
Closing since the related PRs were closed and the change is cosmetic only (the constant is global but private).
