### ISSUE TITLE
Incorrect formatting small negative floats

### ISSUE THREAD

**Issue by bomzheg** [python/cpython#124327]
# Bug report

### Bug description:

```python
>>> f"{-0.00000001:.2f}"
'-0.00'
```
expected result is 0.00

### CPython versions tested on:

3.10, 3.11, 3.12

### Operating systems tested on:

Linux, Windows

**Comment by Eclips4** [comment]
Hello! Thanks for the report.

In fact, you can use `z` format specifier which was introduced in 3.11 (b0b836b20cb56c225874a4a39ef895f89ab2970f):
```python
>>> f"{-0:z.2f}"
'0.00'
```

So, there's no bug.

**Comment by terryjreedy** [comment]
Unless accompanied by a reference to the Python doc, 'expected' usually means 'according to my experience, knowledge, and desire'.

@bomzheg https://discuss.python.org/c/help/7 is a better place to ask about possible bugs, as answers are more easily found there by others.
