### ISSUE TITLE
Need tests for gettext support in argparse

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#124432]
`argparse` supports localization of error messages and helps with `gettext`. But currently there is no any test for `gettext` support in `argparse`. There were several bugs related to improper use of gettext and we cannot be sure that all bugs are fixed or that old bugs will not reappear. We need to add tests for every translated string in `argparse`.

**Comment by tomasr8** [comment]
This issue seems related: #124295 
Anyway, what's best way to test this? Run pygettext and compare the PO file?

**Comment by serhiy-storchaka** [comment]
Then closing this issue.

I thought that we should run the parser with different options to produce different error messages with installed special translator that transforms the original text in simply recognizable way. But there may be better ways.
