### ISSUE TITLE
Review and simplify argparse docs

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#124478]
The argparse docs have become pretty lengthy. This is in part due to the examples, which are somewhat duplicative of the tutorial. I'd like to go through the docs to see if we can dedupe and pare things down to make them more readable.

### Linked PRs
* gh-124877
* gh-125162
* gh-125164

**Comment by rruuaanng** [comment]
I believe that argparse does not need to display sample code, only the public API needs to be shown.
I'm reviewing the argparse documentation and trying to simplify it.

**Comment by hugovk** [comment]
I disagree, but argparse is part of the public API and sample code is useful to  show how to use it.
