### ISSUE TITLE
Update bundled Tcl/Tk to 8.6.15 (Windows, macOS installer)

### ISSUE THREAD

**Issue by zware** [python/cpython#124448]
### Proposal:

8.6.15 was released on Sep 13, 2024

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-124449
* gh-124453
* gh-125795
* gh-125796
* gh-125800
* gh-125801

**Comment by zware** [comment]
See also gh-124111.

**Comment by serhiy-storchaka** [comment]
Note that we still have not updated the bundled version on Windows to 8.6.14 in 3.12 (see #116145).

**Comment by aivarannamaa** [comment]
> Note that we still have not updated the bundled version on Windows to 8.6.14 in 3.12 (see https://github.com/python/cpython/issues/116145).

Does Tk 8.6.14 need to go to Python 3.12 first?

I see that both macOS and Windows installers have been updated to Tcl/Tk 8.6.15 in the main branch. Is there something still blocking this for Python 3.13 branch?
