### ISSUE TITLE
Set name for reusable workflow

### ISSUE THREAD

**Issue by corona10** [python/cpython#124471]
![Screenshot from 2024-09-24 13-54-42](https://github.com/user-attachments/assets/b6d882ad-b7d9-494c-9ae1-efb8c31da135)

Visibility does not look good; let's set the name.

cc @hugovk 

### Linked PRs
* gh-124475
* gh-125256
* gh-125257

**Comment by webknjaz** [comment]
FTR, I've left a comment over in the PR with an example of what I came up with in my projects: https://github.com/python/cpython/pull/124475#pullrequestreview-2355833790. Hopefully, that'll be useful.
