### ISSUE TITLE
Skip additional tests for emulated Linux JIT CI jobs

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#124408]
There have been a number of failed tests on emulated Linux JIT CI runs, related to`test_datetime` lately. We should add them to the list of skipped tests for now.

See https://github.com/python/cpython/actions/runs/10942493409/job/30380093772?pr=124101 as an example.

### Linked PRs
* gh-124466

**Comment by blhsing** [comment]
@savannahostrowski It seems that @serhiy-storchaka has been relatively busy since I submitted PR #123861 to fix the `test_datetime` issue for Linux JIT CI run. Instead of disable the test do you think you can help take a look into reviewing the PR?

**Comment by savannahostrowski** [comment]
@blhsing Thanks for sharing this - it slipped past my inbox. I don't have the expertise to know if that change will resolve the problem, so I'll leave the review to others for now. That said, it'd be ideal to land a more robust fix for this. The skipped tests may address the problem in the short term. I'm happy to revert the change later on if need be.
