### ISSUE TITLE
framelocalsproxy_new() crash if called with no arguments

### ISSUE THREAD

**Issue by vstinner** [python/cpython#124513]
# Bug report

Example on Python 3.13.0rc2:

```
$ python3.13
>>> import sys
>>> FrameLocalsProxy=type([sys._getframe().f_locals for x in range(1)][0])
... 
>>> FrameLocalsProxy()
Erreur de segmentation (core dumped)
```

The bug was discovered by zope.interface test suite: https://github.com/zopefoundation/zope.interface/issues/323#issuecomment-2373346327

I'm working on a fix.

### Linked PRs
* gh-124515
* gh-124539

**Comment by ZeroIntensity** [comment]
Everything is done here, right?
