### ISSUE TITLE
File "/root/miniconda3/lib/python3.11/wave.py", line 250, in initfp     raise Error('file does not start with RIFF id') wave.Error: file does not start with RIFF id

### ISSUE THREAD

**Issue by MonolithFoundation** [python/cpython#124581]
File "/root/miniconda3/lib/python3.11/wave.py", line 250, in initfp
    raise Error('file does not start with RIFF id')
wave.Error: file does not start with RIFF id

**Comment by picnixz** [comment]
Could we have a better error report? what kind of file did you give to `initfp`?

**Comment by ZeroIntensity** [comment]
This error comes up when trying to call `wave.open` on a file that is not a `wav` file, so not a CPython issue. @MonolithFoundation, I would double check to make sure that your file is actually an audio file.
