### ISSUE TITLE
Reference leaks on current main

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#124586]
# Bug report

### Bug description:

Noted by @picnixz in https://github.com/python/cpython/pull/119827#issuecomment-2375619532:
```python
Failed tests:

    test__interpchannels
    test_capi
    test__interpreters
    test_ast
    test_importlib

Test leaking resources:

    test_importlib: references
    test_ast: references
    test__interpchannels: references
    test__interpreters: memory blocks
    test_capi: memory blocks
    test_capi: references
    test__interpreters: references
    test_importlib: memory blocks
    test_ast: memory blocks
    test__interpchannels: memory blocks
```

I'm bisecting a bad commit right now.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

**Comment by Eclips4** [comment]
Bisected to d9296529eb0a65f988e8600d3073977dff0ce5a9.
Seems related to handling immortal objects in subinterpeters.

**Comment by ZeroIntensity** [comment]
I don't think this is related to subinterpreters, but more that the `Placeholder` singleton isn't stored elsewhere, so it's never freed. It just gets reinitialized for every subinterpreter, so the leak seems greater.

I can try and fix this much later today, but anyone feel free to try and do it before me.

**Comment by vstinner** [comment]
The issue can be reproduced with:

```
$ ./python -m test -R 3:3 test_ast -m test_subinterpreter
(...)
test_ast leaked [106, 106, 106] references, sum=318
(...)
```

which can be simplified to:

```py
    def test_subinterpreter(self):
        code = dedent('import _functools')
        res = support.run_in_subinterp(code)
        self.assertEqual(res, 0)
```

**Comment by vstinner** [comment]
I wrote PR gh-124601 to fix the leak.

**Comment by vstinner** [comment]
The leak was fixed by https://github.com/python/cpython/pull/124601.
