### ISSUE TITLE
Wrong type for `parameters` argument of `inspect.Signature` 

### ISSUE THREAD

**Issue by dShvetsov** [python/cpython#124589]
# Documentation

It is written that that [parameters](https://github.com/python/cpython/blob/main/Lib/inspect.py#L2893) should be an OrderedDict, when in fact it should be a tuple or list

**Comment by skirpichev** [comment]
What's wrong?!

```pycon
Python 3.14.0a0 (heads/gh-101410/math_error_message:30be617897, Sep 21 2024, 09:14:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import inspect
>>> inspect.signature(sum)
<Signature (iterable, /, start=0)>
>>> _.parameters
mappingproxy(OrderedDict({'iterable': <Parameter "iterable">, 'start': <Parameter "start=0">}))
```

**Comment by dShvetsov** [comment]
```
In [67]: p = inspect.Parameter(name='a', kind=inspect.Parameter.KEYWORD_ONLY)

In [68]: sig = inspect.Signature(parameters=OrderedDict(a=p))
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[68], line 1
----> 1 sig = inspect.Signature(parameters=OrderedDict(a=p))

File ~/opt/miniconda3/envs/test-framework/lib/python3.11/inspect.py:2987, in Signature.__init__(self, parameters, return_annotation, __validate_parameters__)
   2984 seen_default = False
   2986 for param in parameters:
-> 2987     kind = param.kind
   2988     name = param.name
   2990     if kind < top_kind:

AttributeError: 'str' object has no attribute 'kind'
```

**Comment by dShvetsov** [comment]
Ah, ok, I misunderstood the documentation, it is not about constructor of the class. Sorry

**Comment by AA-Turner** [comment]
From https://docs.python.org/dev/library/inspect.html#inspect.Signature (emphasis added):

> The optional parameters argument is **a sequence of [Parameter](https://docs.python.org/dev/library/inspect.html#inspect.Parameter) objects**, which is validated to check that there are no parameters with duplicate names, and that the parameters are in the right order, i.e. positional-only first, then positional-or-keyword, and that parameters with defaults follow parameters without defaults.
