### ISSUE TITLE
# Bug report

### ISSUE THREAD

**Issue by MandeepSinghPB08** [python/cpython#124514]
# Bug report

Example on Python 3.13.0rc2:

```
$ python3.13
>>> import sys
>>> FrameLocalsProxy=type([sys._getframe().f_locals for x in range(1)][0])
... 
>>> FrameLocalsProxy()
Erreur de segmentation (core dumped)
```

The bug was discovered by zope.interface test suite: https://github.com/zopefoundation/zope.interface/issues/323#issuecomment-2373346327

I'm working on a fix.

_Originally posted by @vstinner in https://github.com/python/cpython/issues/124513_

**Comment by ZeroIntensity** [comment]
Hi,

I'm assuming this is a misclick?

**Comment by brianschubert** [comment]
For reference: #124513
