### ISSUE TITLE
ctypes.Union & ctypes.Structure: common features should be tested on both types

### ISSUE THREAD

**Issue by encukou** [python/cpython#124570]
Currently, `Lib/test/test_ctypes/test_structure.py` is very long, but `Lib/test/test_ctypes/test_union.py` only has recent additions.
A lot of the Structure tests apply to Union as well, and should be run on both. My plan is:

- Move tests of common features to `Lib/test/test_ctypes/test_structunion.py`, and use the “common base class + two subclasses” pattern used for tests of similar classes
- Keep the Structure-specific tests in `Lib/test/test_ctypes/test_structure.py`

### Linked PRs
* gh-124976

**Comment by rruuaanng** [comment]
It seems like the workload is quite heavy. I don't think it's necessary just to organize an almost stable and unchanging module.

**Comment by encukou** [comment]
But ctypes isn't stable and unchanging. In 3.14 the struct/union packing algorithm is replaced and moved to Python code. That on its own deserves better Union tests.
