### ISSUE TITLE
Please restore the loop param to staggered.staggered_race

### ISSUE THREAD

**Issue by bdraco** [python/cpython#124639]
# Bug report

### Bug description:

The following remove the `loop` param from `staggered.staggered_race` :

https://github.com/python/cpython/pull/124390
https://github.com/python/cpython/pull/124574
https://github.com/python/cpython/pull/124573

~~its wasn't scheduled for removal until [3.16](https://github.com/python/cpython/commit/3fbbedb0ad64eeba7284d1244158b892497d55c8#diff-44556baf5b5e0be424424f6a3058952ceef4bd6a73637f138df33e93def215f7L74)~~ this never merged

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Linked PRs
* gh-124700
* gh-124744

**Comment by Eclips4** [comment]
Hello!
Thanks for the report.

`asyncio.staggered_race` should not be used directly. It is a private API that is not documented anywhere in the documentation. If you want to use `staggered_race, `please install the 3rd party package async-stagger: https://github.com/twisteroidambassador/async_stagger.

**Comment by bdraco** [comment]
Its a bit unexpected to have deprecation warnings in it given its not intended for public use.

**Comment by ZeroIntensity** [comment]
FWIW, there was no deprecation emitted. That got removed right after the PR got merged. @Eclips4 should we reopen this? I guess this is too much of a breaking change for a patch release.

**Comment by ZeroIntensity** [comment]
@bdraco, we're going to add back the `loop` parameter for 3.12. (I'm not sure what the deprecation plan is, I think it's supposed to be 3.14?)

Anyways, this will allow use of `eager_task_factory` on prior aiohttp versions. However, we're officially marking `staggered_race` as a private API (and will rename it to `_staggered_race`). Please copy the current implementation into third parties for future use, as we're not guaranteeing any future support past 3.12 (or maybe 3.13, I think that's undecided).

**Comment by bdraco** [comment]
Thank you!

**Comment by ZeroIntensity** [comment]
@Eclips4 are you working on this? Or should I write a patch (sorry, should have clarified yesterday).

**Comment by kumaraditya303** [comment]
> we're going to add back the loop parameter for 3.12
> we're officially marking staggered_race as a private API (and will rename it to _staggered_race). 

Where was this decided? was this discussed at the ongoing sprints?

**Comment by ZeroIntensity** [comment]
> > we're going to add back the loop parameter for 3.12
> > we're officially marking staggered_race as a private API (and will rename it to _staggered_race).
> 
> Where was this decided? was this discussed at the ongoing sprints?

On Discord. @ambv said it, I think?

**Comment by kumaraditya303** [comment]
> On Discord. @ambv said it, I think?

I don't agree with adding back loop parameter and ignoring it, it is wrong to do.

**Comment by Yhg1s** [comment]
I'm sorry, but our backward compatibility and change policy (https://peps.python.org/pep-0387/) is clear in this. The original PR (#124390) makes changes that are not suitable for backport, and that includes both 3.12 and 3.13 (at this point). It's also not suitable to do in 3.14 without a deprecation period or an exemption to the policy (see the last item in https://peps.python.org/pep-0387/#basic-policy-for-backwards-compatibility), but that's @hugovk's call.

Please roll back the changes in 3.12 and 3.13, since releases are coming this tuesday.

**Comment by Eclips4** [comment]
> I'm sorry, but our backward compatibility and change policy (https://peps.python.org/pep-0387/) is clear in this. The original PR (#124390) makes changes that are not suitable for backport, and that includes both 3.12 and 3.13 (at this point). It's also not suitable to do in 3.14 without a deprecation period or an exemption to the policy (see the last item in https://peps.python.org/pep-0387/#basic-policy-for-backwards-compatibility), but that's @hugovk's call.
> 
> Please roll back the changes in 3.12 and 3.13, since releases are coming this tuesday.

Thank you, Thomas, for your feedback on this! 
I understand that you would like to revert the changes (including the bug fix), is that correct?

**Comment by Yhg1s** [comment]
I have no opinion on the _bugfix_, but the removal of a keyword argument from a non-private API can't happen in the backport (and can't happen in main without following PEP 387).

**Comment by bdraco** [comment]
It would be nice to keep the bugfix, although the new code seems to cause `aiohttp` CI to hang on python 3.13 only (https://github.com/aio-libs/aiohttp/pull/9311). I have not have been able to find the root cause yet though.

**Comment by ZeroIntensity** [comment]
@Yhg1s is it needed to revert the whole fix? The nicer option would be to add `loop` back to all versions with a 3.16 removal plan and just have it do nothing for compatibility, or alternatively, we could use the private API of `TaskGroup` to make sure that the `loop` argument actually persists.

**Comment by kumaraditya303** [comment]
I am adding back the loop param but the PR doesn't ignores it completely, it actually uses it. This is the best fix for the time being.

**Comment by ZeroIntensity** [comment]
FWIW, this doesn't affect 3.13 yet, because gh-124573 hasn't been merged.

**Comment by ambv** [comment]
> I am adding back the loop param but the PR doesn't ignores it completely, it actually uses it.

That's what I suggested on Discord.

**Comment by gvanrossum** [comment]
But IIUC there's a 3.12 release planned for Tuesday too, and that *is* affected.

I am still unclear on the use case for passing loop=. The test (which existed before this changed and which Kumar is proposing to restore as part of the fix here) just passes a loop that becomes the current loop by the time anything runs.

How is aiohttp using the loop= argument? I would love to see a test that creates a multi-loop scenario similar to what aiohttp uses, and that passes in older 3.12 releases. We can then check if the same test passes in updated 3.12+ branches.

This feels urgent because of the expected 3.12 release. If we can't get confidence that Kumar's hack (patching `tg._loop`) will actually work with the older aiohttp versions, we should roll back the 3.12 backport of #124390 (the 3.13 backport wasn't merged, so it's safe).

Maybe someone should at least try Kumar's #124700 with an earlier (unpatched) aiohttp version?

@kumaraditya303 @bdraco

**Comment by bdraco** [comment]
> How is aiohttp using the loop= argument? I would love to see a test that creates a multi-loop scenario similar to what aiohttp uses, and that passes in older 3.12 releases. We can then check if the same test passes in updated 3.12+ branches.

`aiohttp` uses `aiohappyeyeballs` which is essentially a vendored subset of `loop.create_connection` that skips the dns resolution since `aiohttp` has its uses it own resolver. This was needed because `loop.create_connection` has no way to pass `local_addr_infos` and `addr_infos`

In `aiohappyeyeballs` 2.4.0 and older `loop` was passed https://github.com/aio-libs/aiohappyeyeballs/blob/v2.4.0/src/aiohappyeyeballs/impl.py#L96 as the `loop` passing was copied from an earlier version of `loop.create_connection`
https://github.com/python/cpython/blob/63e54e6d4227e7cbdbb2a0ea69d11a904951f3a9/Lib/asyncio/base_events.py#L1020

The primary concern was that users who upgrade to a cpython with the new implementation that drops the `loop` arg would experience breakage.

It mitigate that risk, [we removed passing `loop` in 2.4.1+](https://github.com/aio-libs/aiohappyeyeballs/commit/5f80b7951f32d727039d9db776a17a6eba8877cd) as we assume there are no use cases where loop needs to be passed (hopefully we are not wrong on that). The net result is this hopefully limits the potential breakage to users who have `aiohappyeyeballs` < 2.4.1 and upgrade their cpython.

I will test https://github.com/python/cpython/pull/124700 with aiohappyeyeballs 2.4.0 which was the last version to pass the `loop` arg.

**Comment by bdraco** [comment]
I patched a production system using `aiohttpeyeballs==2.4.0` and with `cpython` 3.12.4 by replacing `asyncio/staggered.py` with the `staggered.py` I checked out from https://github.com/python/cpython/pull/124700

- I verified loop was passed down and set as `tg._loop`
- I verified connections were established as expected.

**Comment by bdraco** [comment]
Thank you for looking at this. I hope that I have explained it well enough.

**Comment by gvanrossum** [comment]
> Thank you for looking at this. I hope that I have explained it well enough.

Yes, thanks! So it really is the case that the loop passed in must be the currently running loop. Maybe instead of hacking `tg._loop` we should just check that? Put e.g.
```py
assert loop is None or loop is events.get_running_loop()
```
(or better, some kind of check that raises a `ValueError`).

I tried modifying the test to use `loop=events.get_running_loop()` and it just hung; hitting ^C printed some weird errors.

**Comment by graingert** [comment]
What's the purpose of the loop kwarg here? Is it to avoid an expensive call to get_running_loop? If so TaskGroup could just call current_task().get_loop()

**Comment by bdraco** [comment]
The new implementation doesn't seem to handle multiple winners in the same iteration of the event loop as we received https://github.com/aio-libs/aiohappyeyeballs/issues/100 today

I was able to write a test to simulate the problem https://github.com/aio-libs/aiohappyeyeballs/blob/e3519bbebf2069eee0aff0dfde50689c742ba97f/tests/test_staggered.py#L33

```python
    loop = asyncio.get_running_loop()
    winners = []
    finish = loop.create_future()

    async def coro(idx):
        await finish
        winners.append(idx)
        return idx

    coros = [partial(coro, idx) for idx in range(4)]

    task = loop.create_task(staggered_race(coros, delay=0.00001))
    await asyncio.sleep(0.1)
    loop.call_soon(finish.set_result, None)
    winner, index, excs = await task
```

I ended up writing a new implementation for `aiohappyeyeballs` that should work on 3.8-3.13+ https://github.com/aio-libs/aiohappyeyeballs/blob/main/src/aiohappyeyeballs/_staggered.py

**Comment by kumaraditya303** [comment]
Closing as the change was reverted in all branches

**Comment by twisteroidambassador** [comment]
> I thought we fixed this with a separate implementation already.

Right, I see it now. Thanks!
