### ISSUE TITLE
Regarding whether we should add `Py_CurrentArch` or `Py_ArchName` 

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#124650]
I personally believe that while it may not be necessary to make it public, there should be a similar way to intuitively obtain the current architecture.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

For more details, see https://discuss.python.org/t/regarding-whether-we-should-add-py-currentarch-or-py-archname-function/65191.

**Comment by rruuaanng** [comment]
cc @zooba @vstinner

**Comment by skirpichev** [comment]
Mentioned thread has no comments at all.  I think we should wait outcome of this discussion, then reopen issue if need.
