### ISSUE TITLE
Pyrepl on windows is blocking where it shouldn't

### ISSUE THREAD

**Issue by DinoV** [python/cpython#124628]
# Bug report

### Bug description:

ReadConsoleInput is documented as always returning at least one input. This breaks things in a couple of spots:
- searching inputs and hitting ctrl-c. This blocks reading, a 2nd ctrl-c is required, and then the interpreter crashes.
- Background exceptions with a partial input. This should display the exception and do a keyboard interrupt, but it only happens on the next keypress.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-124629
* gh-124638

**Comment by rruuaanng** [comment]
This issue is it should close? Them look like merged.
