### ISSUE TITLE
Support parsing negative scientific notation and complex numbers in argparse

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#124693]
# Bug report

Per https://github.com/python/cpython/issues/123945#issuecomment-2379781453

### Linked PRs
* gh-124823

**Comment by serhiy-storchaka** [comment]
`argparse` is weird. `-x -y` is considered an error if `-x` is known option that requires argument. This is a part of the design -- they prefer to consider it more likely that the user did not specify an argument for the option than that the argument begins with a dash. This creates a lot of inconvenience (see for example #66623, #118551, and more was closed), so there is a heuristic to compensate for this for the most common cases. For example, consider number-like arguments positional if there are no number-like options defined. The heuristic works not in 100%, and changing it can introduce new false positive or false negative cases.

That is why any changes should be treated with caution. I prefer not to merge the changes right now, but to wait for a while in case new circumstances arise. After all, this is not a very important case.

In any case this is rather a new feature than a bug.

**Comment by savannahostrowski** [comment]
That makes sense. I totally agree and understand the hesitancy. There are lots of inconsistencies like this lying around, and fixing any one of them could definitely have side effects.

That said, I would like to understand what we are looking for in waiting. More specifically, what would we need to see to feel comfortable merging this change? Do you have specific criteria in mind?

**Comment by serhiy-storchaka** [comment]
I do not know. It takes time to think things over. Perhaps new thoughts will arise while working on other issues.

I thought about how it can affect cases such as `xargs` or `head` which support number-like options and allow option grouping (`xargs -0n1` and `head -5v`). It doesn't seem to make things any worse.

Nothing wrong with your PR (as it looks to me now), and most likely it will be merged in a week or two.

**Comment by savannahostrowski** [comment]
Thanks for clarifying. Just wanted to make sure that there wasn't anything else to be done here that could help!

**Comment by serhiy-storchaka** [comment]
Even if I did not solve any related issues, I think that this change is on safe side.
