### ISSUE TITLE
Code Error In Documentation Section - 3.1.2 

### ISSUE THREAD

**Issue by kgothatsontsane** [python/cpython#124658]
# Documentation

There is a code anomaly which I have found in the Documentation on the following page:
https://docs.python.org/3/tutorial/introduction.html

Under the heading: 3.1.2. Text
There is codeblock that is meant to illustrate how to escape quotes in Python.
<img width="853" alt="Screenshot 2024-09-27 at 10 24 06" src="https://github.com/user-attachments/assets/a4b44f9e-0be1-40f9-83af-ec278b3b6535">

The last example in particular looked odd to me and I tried it out on my Python REPL and got the following result, which is contradictory to the example in the documentation.
![Screenshot 2024-09-27 at 10 34 02](https://github.com/user-attachments/assets/1eb3abda-8f6f-461c-bdf6-1f0acd6e0d7f)

The version of the documentation I am reading is version 3.12.6:
<img width="910" alt="image" src="https://github.com/user-attachments/assets/cabacdf6-c10a-404a-97d5-c0b5ec80952a">

My Python REPL is running version 3.12.1: 
![image](https://github.com/user-attachments/assets/da11add1-0e3f-489a-ad0c-c94f6c30aa2b)

Any feedback would be appreciated.

I can open a pull request to correct it.

**Comment by AA-Turner** [comment]
You're using IPython, which isn't the default REPL. Please verify this with the standard Python REPL. 

Moreover, printing with or without enclosing quotes here isn't important, as the demonstration is of escaping quotes in the input text. I don't think any change here is needed.

A

**Comment by skirpichev** [comment]
I can confirm, that CPython repl (both "new" and old) works as expected:
```
$ ./python
Python 3.14.0a0 (heads/main:6f9525dd3f, Sep 27 2024, 11:15:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> '"Isn\'t," they said.'
'"Isn\'t," they said.'$ ./python
Python 3.14.0a0 (heads/main:6f9525dd3f, Sep 27 2024, 11:15:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> '"Isn\'t," they said.'
'"Isn\'t," they said.'
>>> 
$ PYTHON_BASIC_REPL=1 ./python
Python 3.14.0a0 (heads/main:6f9525dd3f, Sep 27 2024, 11:15:30) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> '"Isn\'t," they said.'
'"Isn\'t," they said.'
>>>
```

I would guess, OP run IPython console with some customization set (displayed not repr(str), rather print(str)), because per default I got same as in CPython.
