### ISSUE TITLE
_decimal: Store a module state in objects for faster access

### ISSUE THREAD

**Issue by neonene** [python/cpython#124688]
# Feature or enhancement

### Proposal:

It is known to be efficient to get a module state from an object directly rather than from a type.  The same can go for the `_decimal`'s context object (i.e. extending the `PyDecContextObject` struct).

Extending `PyDecObject`, which made no perf difference for me, seems to be a waste of memory with many objects.

cc @vstinner @erlend-aasland @mdboom

### Links to previous discussion of this feature:

* #119663

### Linked PRs
* gh-124691

**Comment by picnixz** [comment]
Closing since completed in dc12237ab092f0eee7ec5882196997804e635075.
