### ISSUE TITLE
Windows uninstaller breaks on legacy OS's

### ISSUE THREAD

**Issue by Lost-Entrepreneur439** [python/cpython#124616]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
When attempting to uninstall Python on a legacy Windows version (such as Windows 7), the uninstaller fails as it has a version check. If someone manages to bypass the check in the installer thinking it'll just work, or use a kernel extender, if they decide they want to uninstall Python, they have to delete Python's directories manually. I can understand having a version check in the installer, but you should always be able to uninstall something, even if the app doesn't support the OS (if anything, that should be a reason to uninstall it)

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by zware** [comment]
It seems to me that if the version check was defeated for installation, it can be defeated the same way for *un*installation.

**Comment by ericvsmith** [comment]
Since Python isn't supported on Windows 7, I don't think there's anything to do here.

**Comment by zooba** [comment]
Unfortunately, the installer and the uninstaller are the same executable with the same version check. The only difference is whether they detect an existing installation or not.

We don't have to do anything special to bypass our own version check. Users who do it are entirely on their own - there are plenty of ways to get older versions of Python onto Windows 7 besides using our installer.

**Comment by Lost-Entrepreneur439** [comment]
> Unfortunately, the installer and the uninstaller are the same executable with the same version check. The only difference is whether they detect an existing installation or not.
> 
> We don't have to do anything special to bypass our own version check. Users who do it are entirely on their own - there are plenty of ways to get older versions of Python onto Windows 7 besides using our installer.

I'm still a very beginner programmer, but would it not be possible to just implement an if-then-else to check if python's installed, if it isn't, skip the version check, otherwise do the check? I get that Python may not support legacy operating systems, but just about every other app lets you uninstall it from Windows 7 or 8.0, even if the installer doesn't let you, some of the apps I've tested this with even do Python's approach where the installer also acts as the uninstaller, and yup, doesn't let you install on Windows 7, but if you already have it installed, lets you run the installer and uninstall it despite running an unsupported OS, because lets be honest, not letting you uninstall the app is sketchy and may steer people away from using it in the future. Why is it so hard for Python to do this? i can't imagine it would be that difficult or time consuming to implement a simple if-then-else.

**Comment by zooba** [comment]
Yes, it's code, so it's possible to do anything.

But we don't have to do anything for when people bypass our safety checks. The whole point of the check is to prevent use on unsupported operating systems, and if people choose to bypass that, they really are on their own. We aren't doing anything "sketchy" here - the user who bypassed the safety check is doing something sketchy.

I appreciate your concern about compatibility modes, but the version check that we use isn't affected by that. (Very easy to check - just enable compatibility mode on the installer and see if it blocks you. You can even check the log files.)

**Comment by Lost-Entrepreneur439** [comment]
> Yes, it's code, so it's possible to do anything.
> 
> But we don't have to do anything for when people bypass our safety checks. The whole point of the check is to prevent use on unsupported operating systems, and if people choose to bypass that, they really are on their own. We aren't doing anything "sketchy" here - the user who bypassed the safety check is doing something sketchy.
> 
> I appreciate your concern about compatibility modes, but the version check that we use isn't affected by that. (Very easy to check - just enable compatibility mode on the installer and see if it blocks you. You can even check the log files to see it detects "Windows 10" (we don't have a message for Win11 in there.)

One last thing, the check does have a real reason to be bypassed. Python has implemented an artificial check for some reason, without any OS or Python modifications, 3.9 and 3.10 have no problems running on Windows 7, and while I haven't tested myself, I guarantee 3.12 will work with no problems on Windows 8, as both developer wise and end-user wise, 8.1 introduced almost nothing new, it was really just a service pack for 8.

**Comment by ericvsmith** [comment]
Sure, you might consider it a valid use case, and it might work. But it's unsupported by us, so you're entirely on your own.

**Comment by zooba** [comment]
You can bypass it by building from source, using someone else's build, or even using our builds from nuget.org. You just don't get to use the main installer.

This is a free, open source project, where ready-to-use binaries are a generosity and shouldn't be assumed. We do them to encourage use and growth of the language, and they are biased towards the majority user, not the ones who are capable of building from source. And the majority of users will end up with an unsupported OS by mistake - the block is there to let them know about that mistake very quickly.

And for what it's worth, 3.12 won't load on Windows 8. We were able to fix a build issue easily because we already considered it unsupported, but if it were supported, we'd have had to revert actual functionality in order to bring it back. Chances are, nobody was at all affected by either the original bug or our fix, in large part because of the block. We consider such low impact a great achievement.
