### ISSUE TITLE
_Py_ThreadId() fails when compiled using GCC on Windows

### ISSUE THREAD

**Issue by tonyroberts** [python/cpython#124609]
# Bug report

### Bug description:

It should be possible to build a C extension module using GCC on Windows, but when defining Py_GIL_DISABLED any call to _Py_ThreadId fails.

The if/defs in _Py_ThreadId look for _MSC_VER to be defined to determine whether it's a Windows build or not, but that specifies the VS version and not whether the build is for Windows or not.

Instead it would be better to use _WIN32 (see https://learn.microsoft.com/en-us/cpp/preprocessor/predefined-macros?view=msvc-170)

Something along these lines...

```
#if defined(_WIN32)
#include <intrin.h>
#endif

static inline uintptr_t
_Py_ThreadId(void)
{
    uintptr_t tid;
#if defined(_WIN32) && defined(_M_X64)
    tid = __readgsqword(48);
#elif defined(_WIN32) && defined(_M_IX86)
    tid = __readfsdword(24);
#elif defined(_WIN32) && defined(_M_ARM64)
    tid = __getReg(18);
...
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-124663
* gh-124698

**Comment by colesbury** [comment]
I'd be happy to review a PR to support GCC on Windows

**Comment by tonyroberts** [comment]
Thanks @colesbury, I'll put a PR together tomorrow. Should be a very minor change I think

**Comment by zooba** [comment]
Just looking at the proposed code now, I think you'll need to check both `_MSC_VER` (which ought to determine whether `intrin.h` and `__readgsqword` is available) and `_WIN32` for whether we should be using those registers and offsets.

If GCC on Windows provides the same intrinsics but doesn't define the compatible `_MSC_VER` (which I thought it did?) then we probably need an additional check there. `MS_WINDOWS` is better than `_WIN32` generally, but we really want to be checking for these features with the correct conditions and not whichever happen to usually line up (or else we cause bugs like this one, where it didn't line up properly 😉 )

**Comment by tonyroberts** [comment]
Hi @zooba,

I just did a quick check and gcc on windows doesn't define _MSC_VER (at least not using winlibs' gcc 14.1.0). Happy to use MS_WINDOWS. _WIN32 is used elsewhere in the code already but if new code is using that in preference then let's go with that.

The problem with the code right now (https://github.com/python/cpython/blob/a4d1fdfb152c46e3e05aa6e91a44a9fd0323b632/Include/object.h#L174) is that if _MSC_VER isn't defined then it uses the "#elif defined(__x86_64__)" block, which will compile but crash.

With the change to MS_WINDOWS, if __readgsqword is not available then the code will fail to compile, which seems preferable to it compiling the wrong code and causing an error at runtime. Perhaps a specific check for a minimum _MSC_VER could be added (if defined) to give an explicit compile error? Do you know the min value for _MSC_VER that is required? Looks like it's been there since at least VS 2015, but the docs online don't go back further than that (https://learn.microsoft.com/en-us/cpp/intrinsics/readgsbyte-readgsdword-readgsqword-readgsword?view=msvc-140).

Thanks!

**Comment by zooba** [comment]
> if _MSC_VER isn't defined then it uses the "#elif defined(**x86_64**)" block, which will compile but crash.

Right, so you need a check for when the target OS is Windows (`MS_WINDOWS`) but the compiler is not MSVC (`_MSC_VER`), and then provide alternative (or copies of) code that will work in that situation.

_Maybe_ GCC on Windows has the same intrinsics, but I'm not aware of anything that requires or enforces that. If it is somehow enforced, then sure, but if not then we should detect GCC on Windows explicitly, even if it uses the same code.

Trying to detect too many things with too few conditions is why this bug came up in the first place. Now that we know, let's use the right conditions for all the cases. I don't know those off the top of my head, so when you figure them out, submit a PR and we ought to be able to tell if it looks reasonable or not.
