### ISSUE TITLE
Spurious "Type does not define the tp_name field" in 3.13.0rc2t

### ISSUE THREAD

**Issue by dpdani** [python/cpython#124768]
# Bug report

### Bug description:

I'm hitting some (I believe) spurious errors when using my C extension with the latest rc.
Due to the nature of the exception, I would suppose that the build type should not affect it, but it does:

- [tests failing in free-threaded build](https://github.com/dpdani/cereggii/actions/runs/11092903810/job/30818514965?pr=27#step:8:122)
- [tests passing in default build](https://github.com/dpdani/cereggii/actions/runs/11092903810/job/30818514860?pr=27#step:8:25)
- the tests pass for the free-threaded build with rc1 (don't have this on CI -- tested locally)
<details>
  <summary>3.13.0rc1 test logs</summary>

```text
====================== test session starts =======================
platform linux -- Python 3.13.0rc1, pytest-7.4.2, pluggy-1.5.0
rootdir: /home/dp/repos/thesis/cereggii
plugins: reraise-2.1.2
collected 96 items                                               

tests/test_atomic_dict.py .............s....s.....ss...... [ 33%]
.                                                          [ 34%]
tests/test_atomic_int.py ................................. [ 68%]
.......................                                    [ 92%]
tests/test_atomic_ref.py ......                            [ 98%]
tests/test_basics.py .                                     [100%]

================= 92 passed, 4 skipped in 0.60s ==================
```
</details>

The free-threaded build is using the deadsnakes action, and I believe that's CPython's `main` from yesterday.

After double-checking, I'm pretty sure I'm setting the `tp_name` field correctly everywhere, apologies in advance if I made a mistake.

### CPython versions tested on:

3.13, CPython main branch

### Operating systems tested on:

Linux

**Comment by ZeroIntensity** [comment]
At a quick glance, it looks like this type object is missing `tp_name`: https://github.com/dpdani/cereggii/blob/e887f1f060ad94ceb8e16b6ab2f62f29c7a1d8ea/src/include/atomic_dict_internal.h#L47

Though, I'm not sure why this only occurs on the free-threaded build.

**Comment by dpdani** [comment]
After removing it ([commit](https://github.com/dpdani/cereggii/pull/27/commits/dc15a739bded7973c193bf36e4bee8328da4d405)), it's still [failing with the same error message](https://github.com/dpdani/cereggii/actions/runs/11102570787/job/30842651477#step:8:122).
(It wasn't being used.)

Thanks for the catch anyways, that's something I needed to clean up.

**Comment by ZeroIntensity** [comment]
Could you narrow this down to what class is causing this? I'm hesitant to mark this as a blocker because we don't have a proper reproducer yet.

**Comment by dpdani** [comment]
I've tried commenting everything except for:
- `CereggiiConstant_Type` ([commit](https://github.com/dpdani/cereggii/blob/939907956cfc5c4cef70f233cc9bbc806e396038/src/cereggii/cereggii.c#L344)) ([failure](https://github.com/dpdani/cereggii/actions/runs/11111180999/job/30870519811?pr=27#step:8:122))
- `AtomicInt_Type` ([commit](https://github.com/dpdani/cereggii/blob/63c7bbcf22b5f704759d3b705878eb45c46cd4b4/src/cereggii/cereggii.c#L360)) ([failure](https://github.com/dpdani/cereggii/actions/runs/11110942979/job/30869786039#step:8:129))

Both are failing in exactly the same way.

I haven't tried every single type, I suspect they would behave the same.

**Comment by ZeroIntensity** [comment]
Sorry, I don't know how to reproduce this. Trying to use CMake builds for locally installed Python versions is a PITA, and I wasn't able to get it working with setuptools. If you could come up with a more standalone reproducer, that would be useful.

Another possible case here is that this is memory corruption; something getting passed to `PyType_Ready` could be any arbitrary memory, and if that memory happens to have a `NULL` at the same offset as `tp_name`, then that would cause problems. I suggest running through valgrind to rule out that possibility.

**Comment by dpdani** [comment]
Understood, no problem.

Will try to make a minimal repro, or will confirm it's some bug with my code, as soon as I can.

**Comment by dpdani** [comment]
Hello there 👋

I can confirm it was a bug with my code. Thank you for your patience 🙏

**Comment by ZeroIntensity** [comment]
For future reference, what was the bug? It's helpful for us to know in case this issue comes up in the future :)

**Comment by dpdani** [comment]
Unfortunately, I couldn't really pin-point the problem: I fixed a number of bugs related to jumping the target Python version to 3.9 to 3.13.

Now I don't think it was related to any of those bugs, though.

While I was fixing stuff I switched the action for the free-threaded build from `deadsnakes/action` to `astral-sh/setup-uv`.
It appears the problem is actually still there if I switch back to the deadsnakes action:
- [with deadsnakes](https://github.com/dpdani/cereggii/actions/runs/11444942806/job/31840954441) ([commit](https://github.com/dpdani/cereggii/pull/27/commits/fff3f8680c220315be639170b079ea86acdb8946))
- [with uv](https://github.com/dpdani/cereggii/actions/runs/11444970401/job/31841029392) ([commit](https://github.com/dpdani/cereggii/pull/27/commits/b7e63d9f68e61dbc65dcadc3670193bdc7233e02))

I'm very confused at this point, I was thinking it was related to my code, but it looks like it's not.
