### ISSUE TITLE
`test_class.TestInlineValues.test_detach_materialized_dict_no_memory` leaks references

### ISSUE THREAD

**Issue by mpage** [python/cpython#124722]
# Bug report

### Bug description:

Refleaks tests are failing on main due to a leak from `test_class.TestInlineValues.test_detach_materialized_dict_no_memory`:

```
> ./python -m test -R 3:3 test_class --match test.test_class.TestInlineValues.test_detach_materialized_dict_no_memory
Using random seed: 1105673167
0:00:00 load avg: 1.71 Run 1 test sequentially in a single process
0:00:00 load avg: 1.71 [1/1] test_class
beginning 6 repetitions. Showing number of leaks (. for 0 or less, X for 10 or more)
123:456
XX1 111
test_class leaked [1, 1, 1] references, sum=3
test_class leaked [1, 1, 1] memory blocks, sum=3
test_class failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_class

Total duration: 223 ms
Total tests: run=1 (filtered)
Total test files: run=1/1 (filtered) failed=1
Result: FAILURE
>
```
That test was added in gh-124627. 
cc @markshannon @DinoV 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-124769
* gh-124777

**Comment by ZeroIntensity** [comment]
I'll look into this soon. At a glance, the leak itself is probably not related to the PR.

**Comment by sobolevn** [comment]
@ZeroIntensity sorry, I didn't write a message here. I was also working on this issue.
Please, take a look at my PR: https://github.com/python/cpython/pull/124769

**Comment by ZeroIntensity** [comment]
Oh, perfect! I'll take a look at the PR.
