### ISSUE TITLE
Fix compiler warnings on JIT builds where `-mno-outline-atomics` are not supported.

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#124820]
See https://github.com/python/cpython/actions/runs/11115927540/job/30887579831?pr=124813#step:6:1063 as an example.

Related to a change I made in https://github.com/python/cpython/pull/124443/files#diff-700c6057d24addce74e8787edb5f5556f718299f6ef1742cbb1d79580cdb535cR144

### Linked PRs
* gh-124821
* gh-124883

**Comment by vstinner** [comment]
> See https://github.com/python/cpython/actions/runs/11115927540/job/30887579831?pr=124813#step:6:1063 as an example.

```
clang: warning: 'x86_64' does not support '-mno-outline-atomics'; flag ignored [-Woption-ignored]
clang: warning: 'x86_64' does not support '-mno-outline-atomics'; flag ignored [-Woption-ignored]
clang: warning: 'x86_64' does not support '-mno-outline-atomics'; flag ignored [-Woption-ignored]
clang: warning: 'x86_64' does not support '-mno-outline-atomics'; flag ignored [-Woption-ignored]
```
