### ISSUE TITLE
6.2.4. Displays for lists, sets and dictionaries: Grammar seems wrong

### ISSUE THREAD

**Issue by gpapashvili** [python/cpython#124876]
# Documentation

Under 6.2.4. Displays for lists, sets and dictionaries, the grammar is given as:

`comp_for      ::=  ["async"] "for" target_list "in" or_test [comp_iter]`

Should it be `or_test` or `atom` , i.e.:

`comp_for      ::=  ["async"] "for" target_list "in" atom [comp_iter]`

Or am I missing something?

**Comment by tomasr8** [comment]
[Link to the docs for reference](https://docs.python.org/3/reference/expressions.html#displays-for-lists-sets-and-dictionaries)

I think it's correct, `or_test` includes more complex expressions besides just atoms e.g. you can do:
```python
[x for x in a or b]
```
where `a or b` matches `or_test`.

**Comment by skirpichev** [comment]
> I think it's correct, or_test includes more complex expressions besides just atoms

From the [grammar](https://docs.python.org/3/reference/expressions.html#boolean-operations) it looks like or_test doesn't include atoms, isn't?

**Comment by tomasr8** [comment]
> > I think it's correct, or_test includes more complex expressions besides just atoms
> 
> From the [grammar](https://docs.python.org/3/reference/expressions.html#boolean-operations) it looks like or_test doesn't include atoms, isn't?

I think it does via `comparison` -> `or_expr` -> `shift_expr` -> ... -> `primary` -> `atom`

**Comment by gpapashvili** [comment]
> [Link to the docs for reference](https://docs.python.org/3/reference/expressions.html#displays-for-lists-sets-and-dictionaries)
> 
> I think it's correct, `or_test` includes more complex expressions besides just atoms e.g. you can do:
> 
> ```python
> [x for x in a or b]
> ```
> 
> where `a or b` matches `or_test`.

Agree.
