### ISSUE TITLE
Intermittent timerfd failure on Android

### ISSUE THREAD

**Issue by mhsmith** [python/cpython#124873]
# Bug report

This happens quite often, but usually doesn't cause a buildbot failure because it passes on the second attempt. However, it's now double-failed twice:

* https://buildbot.python.org/#/builders/1594/builds/54
* https://buildbot.python.org/#/builders/1594/builds/141

```
======================================================================
FAIL: test_timerfd_poll (test.test_os.TimerfdTests.test_timerfd_poll)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/data/user/0/org.python.testbed/files/python/lib/python3.14/test/test_os.py", line 4390, in test_timerfd_poll
    self.check_timerfd_poll(False)
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/data/user/0/org.python.testbed/files/python/lib/python3.14/test/test_os.py", line 4378, in check_timerfd_poll
    self.assertEqual(self.read_count_signaled(fd), 1)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 2 != 1

----------------------------------------------------------------------
Ran 367 tests in 12.334s

FAILED (failures=1, skipped=120)
test test_os failed
```

### Linked PRs
* gh-127101
* gh-127105
* gh-127279
* gh-127290

**Comment by mhsmith** [comment]
I was able to reproduce this by doing something else on the emulator while running the test repeatedly in -F mode – starting Chrome was usually enough. My initial understanding of the test was that the process would need to be suspended for at least 1/8 of a second for it to fail this way, but surely if that was happening, lots of other time-sensitive tests would fail as well. More detailed investigation is needed.

Since this is a Linux-only feature exposed via a BSD-based libc, it’s also possible Android's implementation is buggy, or at least different enough that it breaks assumptions in the test.

For now I'll disable the test to avoid the buildbots posting useless messages on GitHub. It would be no great loss to disable the entire timerfd feature on Android, since it's a Linux-only feature which isn't widely used. But since it's already been released as part of 3.13, that would technically be a breaking change rather than a bug fix.

**Comment by mhsmith** [comment]
Sorry for the slow reply. Unfortunately this won't fix the failure, because it's happening at a point in the test earlier than any of the CLOCK_RES variables are involved.

This hasn't caused any full buildbot failures since #127101 was merged, but there have been failures which passed on a rerun and are therefore reported as warnings:
* https://buildbot.python.org/#/builders/1590/builds/231 – `test_timerfd_ns_poll`
* https://buildbot.python.org/#/builders/1590/builds/235 – `test_timerfd_ns_select` and `test_timerfd_poll`

So I've created #127279 to revert #127101 and skip these tests until we have time to investigate this further.

**Comment by vstinner** [comment]
The test is now skipped on Android: https://github.com/python/cpython/commit/4ca2c82862e3810a7d68799df2bb5198a9afb219.

**Comment by mhsmith** [comment]
Similar report on Gentoo: #126112.
