### ISSUE TITLE
HTTP to HTTPS redirect forgets original method [urllib.request]

### ISSUE THREAD

**Issue by Jean-Luc-Picard-2021** [python/cpython#124815]
# Bug report

### Bug description:

```python
>>> request = urllib.request.Request('https://wildorchard.com/collections/teaware', method='HEAD')
>>> response = urllib.request.urlopen(request)
>>> response.read()
b''
>>> request = urllib.request.Request('http://wildorchard.com/collections/teaware', method='HEAD')
>>> response = urllib.request.urlopen(request)
>>> response.read()
b'<!doctype html>\n<html class="no-js" lang="en">\n<head>\n\n\n  
```
In the first request everything works finde, the HEAD method doesn't return a response
body, subsequently response.read() gives a byte sequent of length zero.

In the second request, the final URL is the same, but something goes wrong, mostlikely
during redirect the method gets lost, since now the response body is not empty.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by dltacube** [comment]
I wonder if this has anything to do with it:

https://docs.python.org/3/library/urllib.request.html#httpredirecthandler-objects
> The default implementation of this method does not strictly follow [RFC 2616](https://datatracker.ietf.org/doc/html/rfc2616.html), which says that 301 and 302 responses to POST requests must not be automatically redirected without confirmation by the user. In reality, browsers do allow automatic redirection of these responses, changing the POST to a GET, and the default implementation reproduces this behavior.

**Comment by dltacube** [comment]
I think this is fixed in python 3.14

**Comment by skirpichev** [comment]
Yes, I think it's a duplicate of #99730.

**Comment by Jean-Luc-Picard-2021** [comment]
The change might be incomplete, since it only keeps HEAD.
But the protocoll is such that all methods are preserved,
not only HEAD, but also DELETE, PUT, etc..

**Comment by skirpichev** [comment]
Probably, description should be updated with another example (not HEAD).

**Comment by dltacube** [comment]
> It all depends on the particular 30x response status.

Do other status codes have their methods changed as well? Looking at https://github.com/python/cpython/issues/99730 it seems like 302's were used to test the patch.

> not only HEAD, but also DELETE, PUT, etc..

I think the intention is to change  `POST` and `PUT` requests to `GET` is intentional from what I'm seeing in the documentation. The others I'm not sure but it seems like it'd be ok so long as the request has no payload.

**Comment by Jean-Luc-Picard-2021** [comment]
Its a little bit difficult to find an Echo server which
does redirect. I have one written by myself and
opened a new ticket for DELETE issue:

https://github.com/python/cpython/issues/124857
