### ISSUE TITLE
Improve invalid input type handling in `tomllib.loads`

### ISSUE THREAD

**Issue by hukkin** [python/cpython#124835]
# Feature or enhancement

### Proposal:

`tomllib.loads` only accepts str as input. Given bytes, it throws
```
TypeError: a bytes-like object is required, not 'str'
```

This is a bubbled up exception from the `replace` method on line https://github.com/python/cpython/blob/4129a74a3772a2fa75a3b8f642f6b4cf18520e0e/Lib/tomllib/_parser.py#L74 which is otherwise fine, but the message has bytes and str the wrong way around, which can be very confusing. I propose catching the exception and raising a new TypeError with an improved message.

While at it, I also propose catching any AttributeErrors from this line of code and raising the same new TypeError instead. As a result, a sensible TypeError is raised in nearly all cases where incorrect type is passed in.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

Original issue report by @mechsin on Tomli's issue tracker: https://github.com/hukkin/tomli/issues/223
PR: https://github.com/python/cpython/pull/124587

### Linked PRs
* gh-124587

**Comment by StanFromIreland** [comment]
Do we want to backport this change? It is partly a bug fix (error message is flipped). Maybe it could be split?

See also: https://github.com/python/cpython/issues/132655

**Comment by hauntsaninja** [comment]
I didn't backport because it can change the exception type (also because slightly less confusing error messages that aren't super critical are little more feature than bug)
