### ISSUE TITLE
PEP 8

### ISSUE THREAD

**Issue by SALAMANDRA69** [python/cpython#124890]
# Bug report

### Bug description:

```python
>>> 50 - 5 * 6
>>> (50 - 5 * 6) / 4
```
![2024-10-02_15-26-58](https://github.com/user-attachments/assets/5293aefc-1d0f-41bd-a84d-558e94cf6655)

The documentation of version 3.12.7 in paragraph 3.1.1. Numbers provides an example of arithmetic expressions. In the example, there are 4 spaces missing, between the "*" sign.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
Thanks for the report, but PEP 8 need not be followed everywhere. It's a guideline for the standard library, nothing else. And even in the standard library there are exceptions, as the document itself says.

**Comment by SALAMANDRA69** [comment]
Thank you for your quick response to my suggestion. I understand that PEP8 does not have to be followed everywhere, but this is the beauty of the code and I think that beauty can be observed in the documentation to show this to users.

**Comment by zuo** [comment]
@SALAMANDRA69 You don't need to apologize, we all are learning... :)

**Comment by terryjreedy** [comment]
Please consider posting such questions/claims/observations to https://discuss.python.org/c/help/7 first.  Discussion there helps more people.
