### ISSUE TITLE
TypeAliasType does not recognize type parameter after use of Concatenate and cannot be subscripted

### ISSUE THREAD

**Issue by Daraan** [python/cpython#124904]
# Bug report

### Bug description:

After using Concatenate to recursively replace a ParamSpec of a `TypeAliasType`, another subscription with a type param is possible but the type param is not recognized.

In the last part the following code (`C2T = C2[T]   # <---  should create a generic`), however it's parameters are empty and it cannot be subscripted further:

Consider the following code sample, also availiable on [pyright playground](https://pyright-play.net/?code=GYJw9gtgBALgngBwJYDsDmUkQWEMoAqiApgIIA2SAhgM5ELEA0UAwmCgMZUzErdNQAClRBUIAZQYdmpFHGb1iANREBYAFChIUDmHLliHGEnY0AdFQBGHTNlz4WVfVYMaNAYigAKVDGYAqf0EASigAWgA%2BKBoYEA14BlYAbUDBAF0oAF5WJ3IXYiS2Tn4%2BHiTfZnTmGJA0t3UCLMISFRAvACICduCNQQAmJuFRCSkO-u76zx8UP0wZgKC%2B0Mjo2I0WAeyWQvYuHlKCiqE%2BtLr1DygAeQBpC%2BnZgmWomvWARkatpIIzqaOap9WcXULFeAH0ak0QQQkjUzpNvEcjo9ws81sC%2Bh9WH0vmcECBfF4NgQzKDQQgRGJiDwQDRST11FNQvD7sw-rEAS90eDYpCMTDYj9mgwAKIgcAgABcyS8AB4OHkaDQoAByXzKiLMAB%2BjwySCVKDA%2BCoUDQvGI%2BJs8toNA0QA)

```python
from typing import TypeAliasType, Concatenate, ParamSpec, Any, TypeVar
from collections.abc import Callable

# (**P) -> str
type C[**P] =  Callable[P, str]

T = TypeVar("T")
P2 = ParamSpec("P2")

# (int, **P2) -> str
C2 = C[Concatenate[int, P2]]

# OK
# (T) -> str
C1T = C[T]
# (str) -> str
C1_str = C1T[str]

# -------- 

# (int, T) -> str
C2T = C2[T]   # <--- does not create a generic
print(C2T.__parameters__)  # <-- is empty
# () 

# (int, str) -> str
C2_str = C2T[str]  # <-- cannot be subscripted
# TypeError: C[(<class 'int'>, ~T)] is not a generic class

```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by tomasr8** [comment]
I think this will be fixed by this PR https://github.com/python/cpython/pull/124512
When I run your example on that branch, I get non-empty `__parameters__`:

```python
>>> C2T = C2[T]
>>> C2T.__parameters__
(~T,)
```

**Comment by Eclips4** [comment]
Thanks for the investigation, Tomas.
So I guess we can close this as a duplicate of #124445?

**Comment by Daraan** [comment]
It's definitely similar, I'll close it and will check it later again. Thanks for checking!
