### ISSUE TITLE
About exception value ​​of memoryview attribute

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#124995]
# Bug report

### Bug description:

```python
>>> mv = memoryview(bytes(b'abcdef'))
>>> mv.c_contiguous
True
>>> mv.f_contiguous
True
```
Why can the memory of byte sequence be arranged in both C-style and F-style order? This makes me feel very confused.

### CPython versions tested on:

CPython main branch

**Comment by TeamSpen210** [comment]
It's a one-dimensional array. Fortran/C styles have to do with the order of the dimensions, but there's only one way to arrange one dimension so there's no difference.

**Comment by skirpichev** [comment]
Maybe it worth to mention in the glossary?

**Comment by rruuaanng** [comment]
> It's a one-dimensional array. Fortran/C styles have to do with the order of the dimensions, but there's only one way to arrange one dimension so there's no difference.

Okay, I'm see it from `python-library` documentation. Thank for you reply.
