### ISSUE TITLE
AttributeError in "iter_attachments" on "is_attachment" call

### ISSUE THREAD

**Issue by sgeulette** [python/cpython#124936]
# Bug report

### Bug description:

Hello,
Using Python 3.10.15, I have an error calling "iter_attachments()" on an "email.message.EmailMessage" object.
The email is produced by a multifunction printer. It is well opened in thunderbird.
Error is the following:
```python
  File "/home/user/.pyenv/versions/3.10.15/lib/python3.10/email/message.py", line 1080, in iter_attachments
    not part.is_attachment() and subtype not in seen):
AttributeError: 'MIMEText' object has no attribute 'is_attachment'
```
The problematic part (`part.as_string()`) is the following : 
`Content-Type: text/html; charset="us-ascii"\nMIME-Version: 1.0\nContent-Transfer-Encoding: 7bit\n\n<html><body><p></p></body></html>`
I have from time to time the same problem with other emails (not only email from scanner).

Regards

An example of a problematic email is zipped...[
[error_is_attachment.zip](https://github.com/user-attachments/files/17245025/error_is_attachment.zip)
](url)

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by zuo** [comment]
I could not reproduce the error using the email message you attached – neither under Py3.10 nor the main branch version.

I tried:

```python
>>> import email, email.policy
>>> with open('error_is_attachment.eml', 'rb') as f:
...     m = email.message_from_binary_file(f, policy=email.policy.default)
>>> list(m.iter_attachments())
```

@sgeulette What are your steps to reproduce the error?

**Comment by sgeulette** [comment]
Sorry, my fault.
I didn't realized that another part of code had modified the original message. 
I close the issue.
