### ISSUE TITLE
Cross builds: distinguish between installation prefix and host prefix in configure.ac?

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#124932]
In Emscripten and wasi builds, and presumably for other cross builds, the build file system and the host file system look different. It's natural to want to install into `cross-build/$TARGET/lib` and then mount that as `/lib` in the host file system. `wasi.py` has to mess around with setting `PYTHONPATH` because `prefix` is set to a path from the build machine. I think it would simplify this if we distinguish between 

* `prefix` -- the path in the build file system where we want to install the files 
* `host_prefix` -- the path in the host file system where getpath.c will look for the files

And similarly for `exec_prefix` and `host_exec_prefix`.

cc @brettcannon @freakboy3742

### Linked PRs
* gh-124933

**Comment by brettcannon** [comment]
In regards to the `wasi.py` reference:

https://github.com/python/cpython/blob/1f9025a4e7819bb4f7799784710f0f3750a9ca31/Tools/wasm/wasi.py#L222-L228

**Comment by brettcannon** [comment]
This has been deemed Emscripten-specific over in the PR.

**Comment by hoodmane** [comment]
Resolved by https://github.com/python/cpython/pull/124933
