### ISSUE TITLE
`os.path.exists` and `lexists` no longer allow a keyword argument on Windows

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#124917]
# Bug report

### Bug description:

Historically `os.path.exists` and `os.path.lexists` have accepted their argument as a keyword, `path=`. However, in 3.13 on Windows (#118755) these functions were reimplemented in C and the C functions only accept a positional argument. This was detected by typeshed CI (python/typeshed#12730).

Probably doesn't have a lot of practical effect (why would you use keyword arguments for these functions?), but it's better to keep this consistent. I'll send a PR.

### CPython versions tested on:

3.13

### Linked PRs
* gh-124918
* gh-125332
* gh-125334

**Comment by nineteendo** [comment]
Can you close this?
