### ISSUE TITLE
`barry_as_FLUFL` future flag does not work in new REPL

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#124960]
# Bug report

New REPL:

```python
>>> from __future__ import barry_as_FLUFL
>>> 1 <> 2
  File "<python-input-1>", line 1
    1 <> 2
      ^^
SyntaxError: invalid syntax
```

Old REPL:

```python
>>> from __future__ import barry_as_FLUFL
>>> 1 <> 2
True
```

I understand that this is just an easter egg :)

### Linked PRs
* gh-124999
* gh-125475

**Comment by warsaw** [comment]
Clearly this is a showstopper bug requiring @Yhg1s to delay Python 3.13.0 for another week and another RC!  No respect for the [FLUFL](https://peps.python.org/pep-0401/) eh @pablogsal ??? 😭

**Comment by Yhg1s** [comment]
I can't believe it, just last week @ambv and @pablogsal were complaining about how easter eggs were getting removed, and here they are, organising a coup! Clearly this should be fixed as soon as possible[^1]!!!!

[^1]: which means 3.13.1

**Comment by nineteendo** [comment]
Hmm, it looks like it's working in the commit that introduced the new REPL: f27f8c790af1233d499b795af1c0d1b36aaecaf5

<img width="933" alt="Screenshot 2024-10-05 at 21 52 09" src="https://github.com/user-attachments/assets/b9371017-5290-4c0d-941f-7ea678b4dd5e">

**Comment by nineteendo** [comment]
Bisected to a3e4fec8734a304d654e4ae24a4aa2f41a7b0640.

**Comment by nineteendo** [comment]
It's failing at this line:

https://github.com/python/cpython/blob/a3e4fec8734a304d654e4ae24a4aa2f41a7b0640/Lib/_pyrepl/simple_interact.py#L86

**Comment by nineteendo** [comment]
Note that this is equivalent to:

```python
tree = compile(source, filename, symbol, ast.PyCF_ONLY_AST)
```

Which doesn't use `codeop.Compile()`.

**Comment by nineteendo** [comment]
Is this acceptable?

```diff
diff --git a/Lib/_pyrepl/simple_interact.py b/Lib/_pyrepl/simple_interact.py
index d65b6d0d627..6e24860d3c8 100644
--- a/Lib/_pyrepl/simple_interact.py
+++ b/Lib/_pyrepl/simple_interact.py
@@ -83,7 +83,7 @@ def showtraceback(self):
 
     def runsource(self, source, filename="<input>", symbol="single"):
         try:
-            tree = ast.parse(source)
+            tree = self.compile.compiler(source, filename, symbol, ast.PyCF_ONLY_AST)
         except (OverflowError, SyntaxError, ValueError):
             self.showsyntaxerror(filename)
             return False
diff --git a/Lib/codeop.py b/Lib/codeop.py
index 6ad60e7f850..8a77075b487 100644
--- a/Lib/codeop.py
+++ b/Lib/codeop.py
@@ -44,6 +44,7 @@
 # Caveat emptor: These flags are undocumented on purpose and depending
 # on their effect outside the standard library is **unsupported**.
 PyCF_DONT_IMPLY_DEDENT = 0x200
+PyCF_ONLY_AST = 0x400
 PyCF_ALLOW_INCOMPLETE_INPUT = 0x4000
 
 def _maybe_compile(compiler, source, filename, symbol):
@@ -109,11 +110,13 @@ class Compile:
     def __init__(self):
         self.flags = PyCF_DONT_IMPLY_DEDENT | PyCF_ALLOW_INCOMPLETE_INPUT
 
-    def __call__(self, source, filename, symbol, **kwargs):
-        flags = self.flags
+    def __call__(self, source, filename, symbol, flags=0, **kwargs):
+        flags |= self.flags
         if kwargs.get('incomplete_input', True) is False:
             flags &= ~PyCF_DONT_IMPLY_DEDENT
             flags &= ~PyCF_ALLOW_INCOMPLETE_INPUT
+        if flags & PyCF_ONLY_AST:
+            return compile(source, filename, symbol, flags, True)
         codeob = compile(source, filename, symbol, flags, True)
         for feature in _features:
             if codeob.co_flags & feature.compiler_flag:
```

**Comment by pablogsal** [comment]
> Clearly this is a showstopper bug requiring @Yhg1s to delay Python 3.13.0 for another week and another RC!  No respect for the [FLUFL](https://peps.python.org/pep-0401/) eh @pablogsal ??? 😭 

![image](https://github.com/user-attachments/assets/20a100d2-05ec-4e6f-bc20-3a0b0587bc03)

**Comment by nineteendo** [comment]
There's no specific code in the PR to handle this easter egg, so I think the bug applies to all syntax changing futures. It just so happens this is currently the only future that changes syntax. If it did not exist, it might have been very tedious to figure this out when adding one in the future.

**Comment by JelleZijlstra** [comment]
@nineteendo's code looks reasonable to me; please submit a PR!

Note that support in the old REPL was also somewhat broken (this is #125331):
```
% python3.12
Python 3.12.4 (main, Jul 24 2024, 15:24:11) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from __future__ import barry_as_FLUFL; print(1 <> 2)
  File "<stdin>", line 1
    from __future__ import barry_as_FLUFL; print(1 <> 2)
                                                   ^^
SyntaxError: invalid syntax
>>> from __future__ import barry_as_FLUFL
>>> print(1 <> 2)
True
>>> 
```

**Comment by ambv** [comment]
The immediate fix is landed. Keeping this open because of the [long-standing bug](https://github.com/python/cpython/pull/124999#discussion_r1794061779) preventing the future import to work when parsed in one pass with its usage.

**Comment by nineteendo** [comment]
Jelle has already opened a separate issue for that: #125331, so I would close this one.

**Comment by ambv** [comment]
Alright, let's do that then. Thanks!
