### ISSUE TITLE
Tokenize does not roundtrip {{ after \n

### ISSUE THREAD

**Issue by wyattscarpenter** [python/cpython#125008]
# Bug report

### Bug description:

```python
import tokenize, io
source_code = r'''
f"""{80 * '*'}\n{{test}}{{details}}{{test2}}\n{80 * '*'}"""
'''
tokens = tokenize.generate_tokens(io.StringIO(source_code).readline)
x = tokenize.untokenize((t,s) for t, s, *_ in tokens)
print(x)
```

Expected:
```

f"""{80 *'*'}\n{{test}}{{details}}{{test2}}\n{80 *'*'}"""

```

Got:
```

f"""{80 *'*'}\n{test}}{{details}}{{test2}}\n{80 *'*'}"""

```

Note the absence of a second { in the {{ after the \n — but in no other positions.

Unlike some other roundtrip failures of tokenize, some of which are minor infelicities, this one actually creates a syntactically invalid program on roundtrip, which is quite bad. You get a `SyntaxError: f-string: single '}' is not allowed` when trying to use the results.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-125013
* gh-125020
* gh-125021

**Comment by wyattscarpenter** [comment]
Furthermore, here is the output of the following code:
```py3
import tokenize, io
source_code = r'f"\n{{test}}"'
tokens = tokenize.generate_tokens(io.StringIO(source_code).readline)
for t in tokens:
  print(t)
```

```py3
TokenInfo(type=61 (FSTRING_START), string='f"', start=(1, 0), end=(1, 2), line='f"\\n{{test}}"')
TokenInfo(type=62 (FSTRING_MIDDLE), string='\\n{', start=(1, 2), end=(1, 5), line='f"\\n{{test}}"')
TokenInfo(type=62 (FSTRING_MIDDLE), string='test}', start=(1, 6), end=(1, 11), line='f"\\n{{test}}"')
TokenInfo(type=63 (FSTRING_END), string='"', start=(1, 12), end=(1, 13), line='f"\\n{{test}}"')
TokenInfo(type=4 (NEWLINE), string='', start=(1, 13), end=(1, 14), line='f"\\n{{test}}"')
TokenInfo(type=0 (ENDMARKER), string='', start=(2, 0), end=(2, 0), line='')
```

So, it seems that the line is getting in alright, but the \n{{ is getting turned into a \n{ in the tokenizer somehow.

**Comment by AlexWaygood** [comment]
It looks like this was a regression in Python 3.12; I can't reproduce the behaviour with Python 3.11. I'm guessing it was caused by the PEP-701 changes.

**Comment by AlexWaygood** [comment]
Reproduced on the `main` branch as well.

**Comment by tomasr8** [comment]
This seems to happen with other escape characters as well:

```python
import tokenize, io
source_code = r'f"""\t{{test}}"""'
tokens = tokenize.generate_tokens(io.StringIO(source_code).readline)
x = tokenize.untokenize((t,s) for t, s, *_ in tokens)
print(x)  # f"""\t{test}}"""
```

```python
import tokenize, io
source_code = r'f"""\r{{test}}"""'
tokens = tokenize.generate_tokens(io.StringIO(source_code).readline)
x = tokenize.untokenize((t,s) for t, s, *_ in tokens)
print(x)  # f"""\r{test}}"""
```

**Comment by tomasr8** [comment]
I think the issue is in this method:

https://github.com/python/cpython/blob/16cd6cc86b3ba20074ae3eefb61aeb24ee1544f7/Lib/tokenize.py#L187-L208

This [PR](https://github.com/python/cpython/pull/115171) fixed the handling of Unicode literals (e.g. `\\N{foo}`), but it seems to only
be checking for the presence of backslashes without checking if they are followed by `N`. This appears to fix that:

```diff
            if character == "{":
                n_backslashes = sum(
                    1 for char in _itertools.takewhile(
                        "\\".__eq__,
                        characters[-2::-1]
                    )
                )
-               if n_backslashes % 2 == 0:
+               if n_backslashes % 2 == 0 or characters[-1] != "N":
                    characters.append(character)
                else:
                    consume_until_next_bracket = True
```

**Comment by wyattscarpenter** [comment]
Extremely late for me to say this, but I thought I'd add: I only unearthed this bug because I'm working on code that incidentally tries to tokenizer-roundtrip everything in https://github.com/hauntsaninja/mypy_primer. So, doing something like that (possibly literally just that) as a test case for tokenize could perhaps be a good idea to prevent future regressions — although setting that up sounds like a hassle!

**Comment by tomasr8** [comment]
We actually already do that here for some random files in the test folder:

https://github.com/python/cpython/blob/26d627779f79d8d5650fe7be348432eccc28f8f9/Lib/test/test_tokenize.py#L1822-L1835

Though, so far it only compares the tokens, not the actual source code. I'd like to extend this check to compare the source code as well here: https://github.com/python/cpython/pull/126010
