### ISSUE TITLE
Python 3.13.0 release notes contain wrong link to GIL feature

### ISSUE THREAD

**Issue by leandrodamascena** [python/cpython#125052]
# Documentation

Link: https://www.python.org/downloads/release/python-3130/
Section: New features

> An [experimental free-threaded build mode](https://docs.python.org/3.13/whatsnew/3.13.html#an-experimental-just-in-time-jit-compiler), which disables the Global Interpreter Lock, allowing threads to run more concurrently. The build mode is available as an experimental feature in the Windows and macOS installers as well.

It's linked to https://docs.python.org/3.13/whatsnew/3.13.html#an-experimental-just-in-time-jit-compiler instead of https://docs.python.org/3.13/whatsnew/3.13.html#whatsnew313-free-threaded-cpython.

**Comment by hugovk** [comment]
Thanks, I've fixed the link.
