### ISSUE TITLE
`this_instr` should be const in generated code. `this_instr` is generated, and should be `const`.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#125039]
# Bug report

### Bug description:

We currently generate
```C
_Py_CODEUNIT *this_instr =...
```
we should generate 
```C
_Py_CODEUNIT* const this_instr =...
```
to prevent it being accidentally changed.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-125071

**Comment by tomasr8** [comment]
The linked PR has been merged, can we close this issue?
