### ISSUE TITLE
pdb: can't debug a script with arguments

### ISSUE THREAD

**Issue by Jamim** [python/cpython#125115]
# Bug report

### Bug description:

_Hello everyone,_

With Python 3.13, `pdb` doesn't pass arguments like `-b` or `--bar` to a script while it works fine with Python 3.12.

<details><summary><b>test.py</b></summary>
<p>

```python
import sys

print(' '.join(sys.argv))
```

</p>
</details> 

✅ Good:
```
$ python3.13 -m pdb -c continue -c quit test.py foo
test.py foo
The program finished and will be restarted
```
🐛 **Bad:**
```
$ python3.13 -m pdb -c continue -c quit test.py foo --bar
usage: pdb [-h] [-c command] (-m module | pyfile) [args ...]
pdb: error: unrecognized arguments: --bar
```
✅ Good:
```
$ python3.12 -m pdb -c continue -c quit test.py foo --bar
test.py foo --bar
The program finished and will be restarted
```

_Best regards!_

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-125424
* gh-125547
* gh-140933
* gh-141635

**Comment by gaogaotiantian** [comment]
Yes that's a bug when `pdb` switched to `argparse`. I'll fix it but It would be in the next 3.13 release. In the meantime, you should be able to explicitly pass the argument to the script instead of `pdb` by `./python -m pdb -c continue -c quit -- test.py foo --bar`

**Comment by gaogaotiantian** [comment]
Fixed in #125424

**Comment by bulrush15** [comment]
This is still an problem in Python 3.14.0.

**Comment by gaogaotiantian** [comment]
@bulrush15 could you give a repro? What command did not work for you? The command above works for me on 3.14 and 3.15.

**Comment by bulrush15** [comment]
I have Python 3.14.0 on Windows 2025 Datacenter edition v24H2.

This python command fails: `python -m pdb pacetool.py -pacetablescsv`. Note the "-p" beginning of "-pacetablescsv". This seems to cause problems. The error this command gives is:

```
usage: python.exe -m pdb [-h] [-c command] (-m module | -p pid | pyfile) [args ...]
python.exe -m pdb: error: argument -p/--pid: invalid int value: 'acetablescsv'
```

This command works. Note that no long option in this case begins with "-p": `python -m pdb piecework.py -daily -test -adminemailonly`

Python 3.14: Also note that "-p" (lowercase) is not part of the `python -h` or `python --help-all` screens but uppercase "-P" is. 

These programs all worked fine on Python 3.11.9. These programs all work fine without "-m pdb". It's using pdb that's the issue. pdb seems to process command line options differently between Python 3.11.9 and Python 3.14.

Make a project dir with an environment. You can make a totally fake program with a fake parameter to test it. Make a program "test.py" that contains: 

```
print("Hello world")
```

Activate your environment and now do: `python -m pdb test.py -pacetablescsv`

**Comment by gaogaotiantian** [comment]
The culprit here is `-pacetablescsv`. The command line argument convention for Python is to use a single dash (`-`) as "short options", which means it should take one letter. In this specific case, your command is equivalent (from `argparse`'s view) as

```
python -m pdb test.py -p acetablescsv
```

`-p` is used by `pdb` to attach to a process, that's where the conflict is.

I still believe that we can make this better. I need to think about it.
