### ISSUE TITLE
Use the public PyUnicodeWriter API

### ISSUE THREAD

**Issue by vstinner** [python/cpython#125196]
Replace `PyUnicode_New()`, `PyUnicode_CopyCharacters()`, etc. with `PyUnicodeWriter`. It avoids creating incomplete Unicode strings: see [Avoid creating incomplete/invalid objects](https://github.com/capi-workgroup/api-evolution/issues/36).

### Linked PRs
* gh-125199
* gh-125201
* gh-125202
* gh-125214
* gh-125219
* gh-125220
* gh-125222
* gh-125227
* gh-125242
* gh-125249
* gh-125262
* gh-125270
* gh-125271
* gh-125458
* gh-125528

**Comment by vstinner** [comment]
I also replaced `PyUnicode_New(0, 0)` with `Py_GetConstant(Py_CONSTANT_EMPTY_STR)` in commit b9a8ca0a6aa9251cb798f34f0c9d2cc95107eec6.

**Comment by encukou** [comment]
There's also a behaviour change: #125222 -- PyUnicodeWriter_Discard(NULL) does nothing
