### ISSUE TITLE
Make `pthread_self()` return a non-zero value in `thread_pthread_stubs.h`

### ISSUE THREAD

**Issue by colesbury** [python/cpython#125161]
Currently our stub for `pthread_self()` (used by WASI) just returns zero:

https://github.com/python/cpython/blob/37228bd16e3ef97d32da08848552f7ef016d68ab/Python/thread_pthread_stubs.h#L106-L109

I propose we return a non-zero value for better consistency with functional pthread implementations. For example:

```c
 PyAPI_FUNC(pthread_t) pthread_self(void) 
 { 
     return (pthread_t)(uintptr_t)&py_tls_entries; 
 } 
```

### Why?

We occasionally assume that `PyThread_get_thread_ident_ex()` returns a non-zero value. For example:

* https://github.com/python/cpython/issues/110455
* In `_PyRecursiveMutex` for the owner field (oops)

We can work around these issues with `#ifndef HAVE_PTHREAD_STUBS` or by fixing the `_PyRecursiveMutex` implementation, but I think we might save ourselves a few headaches in the future by just making the `pthread_self()` stub behave a bit more like actual pthread implementations.

cc @brettcannon @kumaraditya303 

### Linked PRs
* gh-125303

**Comment by kumaraditya303** [comment]
I agree, it's better to fix WASI stubs.

**Comment by brettcannon** [comment]
Fine by me!
