### ISSUE TITLE
Spelling Error

### ISSUE THREAD

**Issue by ghost** [python/cpython#125168]

**Comment by JamesMcCarthy21** [comment]
Hello PhantomEclipse741,

My name is James McCarthy, and I’m a second-year student in the Associate of Science in Computer Science program at Lakeland Community College. For a class project, I need to help resolve an issue in a repository. May I claim this issue for my project? I will begin working on it right away.
Thank you for your consideration!

Best regards,
James McCarthy

**Comment by skirpichev** [comment]
In general, obvious typos doesn't require an issue.  Just fix them and start with a pr.

Use a common sense.  Probably it's not wise to open a pr just for one spelling error alone.  But if you read entire file/module and you are sure that there is no other typos - I think it's ok.

**Comment by Mariatta** [comment]
@skirpichev next time please don't use phrase like "use common sense". It may be common sense to you but not to others.

It would have been better and more welcoming to simply say "Typos don't require an issue, open the PR" without using subjective words like "obvious", "common sense", or "wise/not wise".

@JamesMcCarthy21 please go ahead and open a PR.

**Comment by skirpichev** [comment]
> please don't use phrase like "use common sense"

@Mariatta, sorry.  *My* "common sense" was obviously wrong, now I know it, thanks.

**Comment by JamesMcCarthy21** [comment]
Thank you @Mariatta!

**Comment by Eclips4** [comment]
Thank you, James!
