### ISSUE TITLE
[Windows] New REPL does not preserve history between sessions

### ISSUE THREAD

**Issue by pfmoore** [python/cpython#125154]
# Bug report

### Bug description:

I have downloaded Python 3.13.0, Windows 64 bit version from python.org. I have done nothing to customise it.

I start Python. type "12" at the REPL, and press enter. The value 12 is displayed. I hit Ctrl-Z to exit (same happens if I type "exit"). I restart Python and hit the up arrow key. It does *not* retrieve the "12" from my previous session.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by hroncok** [comment]
I was [unable to reproduce this problem on Fedora](https://discuss.python.org/t/python-3-13-0-final-has-been-released/66972/8). This might be Windows-specific.

**Comment by devdanzin** [comment]
This is a (supposedly) known limitation, as history support in Windows hasn't been added so far. I took a stab at it in #122274.

**Comment by pfmoore** [comment]
:-(

That's something that should probably be publicised much better, then, as it's a surprising and (in my case at least) frustrating limitation compared to the old OS-provided REPL. I'm not sure it's bad enough that I'd switch *off* the new REPL, but it will take some getting used to.

**Comment by skirpichev** [comment]
Sounds like https://github.com/python/cpython/issues/121245 reappears. Does this build has readline support?

**Comment by vstinner** [comment]
> Sounds like https://github.com/python/cpython/issues/121245 reappears. Does this build has readline support?

Windows has no readline module.

**Comment by vstinner** [comment]
This issue is a duplicate of https://github.com/python/cpython/issues/122273 which was fixed by https://github.com/python/cpython/commit/3c7a90a83146dc6e55f6f9ecd9af0bf9682f98a6.
