### ISSUE TITLE
Tkinter does not run in 3.13.0

### ISSUE THREAD

**Issue by litiegang1989** [python/cpython#125179]
# Bug report

### Bug description:

I can not use Tkinter in the version of 3.13.0, even if I just import tkinter will have a wrong. I try to run the program on two different laptops, and have the same problem.
# 
from tkinter import *
```
Process finished with exit code -1073741819 (0xC0000005)


### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by terryjreedy** [comment]
Works fine for me when installed with the new python.org installer.
```
C:\Users\Terry>py
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from tkinter import *
>>> dir()
['ACTIVE', 'ALL', 'ANCHOR', 'ARC', 'BASELINE', 'BEVEL', 'BOTH', 'BOTTOM', 'BROWSE', 'BUTT', 'BaseWidget', 'BitmapImage', 'BooleanVar', 'Button', 'CASCADE', 'CENTER', 'CHAR', 'CHECKBUTTON', 'CHORD', 'COMMAND', 'CURRENT', 'CallWrapper', 
<...>
'image_names', 'image_types', 'mainloop']
>>>
```
Please give exact details of how you got your python binary and exact how you ran it.

Note: the triple backticks should enclose code and output but not the template headings and responses.

**Comment by colesbury** [comment]
Did you install the free-threaded binaries? Tkinter is broken on free-threaded Windows 3.13t: https://github.com/python/cpython/issues/118973

**Comment by terryjreedy** [comment]
I have been running IDLE on locally build free-threading builds since March 15 this year, so this is a packaging issue.
```
Python 3.14.0a0 experimental free-threading build (heads/main:440632adb29, Oct  9 2024, 10:25:28) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> dir()
['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'tkinter']
```

**Comment by joshburnett** [comment]
I see this issue when running Python from within a venv:

```python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> root = tkinter.Tk()
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    root = tkinter.Tk()
  File "C:\Users\jburnett1\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/MY_USER_NAME/AppData/Local/Programs/Python/Python313/lib/tcl8.6 C:/Users/jburnett1/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/MY_USER_NAMEAppData/Local/Programs/lib/tcl8.6 C:/Users/MY_USER_NAME/AppData/Local/Programs/Python/library C:/Users/MY_USER_NAME/AppData/Local/Programs/library C:/Users/MY_USER_NAME/AppData/Local/Programs/tcl8.6.14/library C:/Users/MY_USER_NAME/AppData/Local/tcl8.6.14/library
```

Running in the base Python install works OK. I'm not running the free-threaded build.

I'm testing on Windows 11, though I've seen [a report of this on Windows 10](https://discuss.python.org/t/3-13-0-tkinter-versus-venv-in-windows-10/67151) as well.

**Comment by litiegang1989** [comment]
> Works fine for me when installed with the new python.org installer.
> 
> ```
> C:\Users\Terry>py
> Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from tkinter import *
> >>> dir()
> ['ACTIVE', 'ALL', 'ANCHOR', 'ARC', 'BASELINE', 'BEVEL', 'BOTH', 'BOTTOM', 'BROWSE', 'BUTT', 'BaseWidget', 'BitmapImage', 'BooleanVar', 'Button', 'CASCADE', 'CENTER', 'CHAR', 'CHECKBUTTON', 'CHORD', 'COMMAND', 'CURRENT', 'CallWrapper', 
> <...>
> 'image_names', 'image_types', 'mainloop']
> >>>
> ```
> 
> Please give exact details of how you got your python binary and exact how you ran it.
> 
> Note: the triple backticks should enclose code and output but not the template headings and responses.

**Comment by litiegang1989** [comment]
![20241010-071407](https://github.com/user-attachments/assets/ec4574bd-1229-494c-995d-7e133178a337)
I download the installer from the official site.I test again on Windows 11, If I install with the option clicked, it will have this problem. If I install without download free-threaded binaries, tkinter can run normally.

**Comment by terryjreedy** [comment]
@joshburnett Please open a separate issue for failures, if any, that only occur with venv.  Reference threads on discuss.python.org if this is claimed.
