### ISSUE TITLE
Make PyInitConfig_Free(NULL) a no-op

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#125234]
# Feature or enhancement

I think that it would simplify the code if make `PyInitConfig_Free(NULL)` a no-op. Currently it requires the argument to be non-NULL. This would simplify the code:
```c
PyInitConfig *config = NULL;
// some code
if (error_occurred) {
    goto Error;
}
config = PyInitConfig_Create();
if (config == NULL) {
    goto Error;
}
// some other code
if (error_occurred) {
    goto Error;
}
// more code
Error:
// release resources
if (config == NULL) {
    PyInitConfig_Free(config);
}
// release resources
```

Most Python resources are represented as Python objects, so `Py_XDECREF(NULL)` works for them. `PyMem_Free(NULL)` and `PyRawMem_Free(NULL)` work for raw memory blocks. `PyInitConfig_Free()` is one of few (or only one) API that cannot be used in such idiom.

### Linked PRs
* gh-125266

**Comment by efimov-mikhail** [comment]
> is one of few (or only one) 

I've made a list of such function implementations.

```
-> % grep -rnI 'PyAPI.*Py.*Free' | sed 's/.*) //' | grep -v '^_Py' 
PyMem_Free(void *ptr);
PyMem_RawFree(void *ptr);
PyObject_Free(void *ptr);
PyCode_GetFreevars(PyCodeObject *code);
PyInitConfig_Free(PyInitConfig *config);
PyInitConfig_FreeStrList(size_t length, char **items);
```

Function PyCode_GetFreevars, obviously, is not from the list of free functions.
From other 5 functions only PyInitConfig_Free can not be called with NULL.

IMO, make PyInitConfig_Free(NULL) a no-op is a good idea.
