### ISSUE TITLE
gzip.compress output is non-deterministic

### ISSUE THREAD

**Issue by bmwiedemann** [python/cpython#125260]
# Bug report

### Bug description:

```python
import gzip
gzip.compress(b'')
```
output varies by default, which breaks reproducible builds in cases such as
https://github.com/getmoto/moto/blob/fc60bd1c5f6e6184e30a6db8b65059a2855cd28e/setup.py#L28

GNU gzip (since 1.10) defaults to a zero timestamp for compressing stdin. And after year 2106, no mtime could be stored anyway.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-125261

**Comment by ZeroIntensity** [comment]
Per @AA-Turner, I'm marking this as a feature.

**Comment by thesamesam** [comment]
See also https://github.com/python/cpython/issues/112346 for the OS field.

**Comment by Rogdham** [comment]
Should the same change be made in the default for `mtime` parameter in `GzipFile.__init__`? @bmwiedemann @AA-Turner
