### ISSUE TITLE
Error compiling Python 3.13.0 when Sqlite compiled with foreign-key enabled by default.

### ISSUE THREAD

**Issue by coleifer** [python/cpython#125203]
# Bug report

### Bug description:

My system sqlite is compiled with support for foreign keys:

```
sqlite> pragma compile_options;
...
DEFAULT_FOREIGN_KEYS
...
```

This causes a test failure when attempting to compile Python 3.13.0:

```python

======================================================================
ERROR: test_table_dump (test.test_sqlite3.test_dump.DumpTests.test_table_dump)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/charles/code/python-3.13.0/Lib/test/test_sqlite3/test_dump.py", line 45, in test_table_dump
    [self.cu.execute(s) for s in expected_sqls]
     ~~~~~~~~~~~~~~~^^^
sqlite3.IntegrityError: FOREIGN KEY constraint failed

----------------------------------------------------------------------
```

The test-case should likely disable foreign-key pragma before beginning in order to be correct in all cases.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by tomasr8** [comment]
Seems to be related to this issue https://github.com/python/cpython/issues/123849
Though it looks like the 3.13 backport which fixes the test failure has not been merged yet: https://github.com/python/cpython/pull/125163

**Comment by coleifer** [comment]
Yes, feel free to close as duplicate, thanks for triaging this @tomasr8.
