### ISSUE TITLE
Cannot explicitly select free-threaded installation with Python Launcher for Windows

### ISSUE THREAD

**Issue by thegamecracks** [python/cpython#125223]
# Bug report

### Bug description:

After running the Python 3.13.0 64-bit Windows installer with the option "Download free-threaded binaries (experimental)" checked, the free-threaded executable shows in the launcher's list of installations, but it fails to recognize the CLI arguments `-3.13t` or `-3.13t-64` when trying to select it explicitly:

```python
C:\Users\home>py -0
Installed Pythons found by py Launcher for Windows
 -3.13t-64 *
 -3.13-64
 -3.12-64
 -3.11-64
 -3.10-64
 -3.9-64
 -3.8-64


C:\Users\home>py
Python 3.13.0 experimental free-threading build (tags/v3.13.0:60403a5, Oct  7 2024, 09:53:29) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

C:\Users\home>py -3.13
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

C:\Users\home>py -3.13t
Unknown option: -3
usage: C:\Users\home\AppData\Local\Programs\Python\Python313\python3.13t.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.

C:\Users\home>py -3.13t-64
Unknown option: -3
usage: C:\Users\home\AppData\Local\Programs\Python\Python313\python3.13t.exe [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try `python -h' for more information.
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by zooba** [comment]
It looks like you've got an old version of the launcher installed. It should be showing `-V` options in the output. Maybe check if you've installed an older version for all users (it'll appear as "Python Launcher" under Apps/Programs & Features/Add Remove Programs).

I'd have to go digging through old posts, but I have a feeling that you need to use the `-V` option to get the free-threaded install right now (that is, `-V:3.13t`). That's not what the docs say though. Obviously this only matters while it's experimental - once we've committed to free threading it will merge back in and the `t` goes away.

**Comment by thegamecracks** [comment]
> It looks like you've got an old version of the launcher installed. It should be showing `-V` options in the output.

It indeed appears my launcher came from Python 3.12.2, judging from the first few digits in the Installed apps screen. After uninstalling it and getting the launcher back from the 3.13 installer's Modify page, it now shows my installations as you described:
```py
C:\Users\home>py -0
 -V:3.13t *       Python 3.13 (64-bit, freethreaded)
 -V:3.13          Python 3.13 (64-bit)
 -V:3.12          Python 3.12 (64-bit)
 -V:3.11          Python 3.11 (64-bit)
 -V:3.10          Python 3.10 (64-bit)
 -V:3.9           Python 3.9 (64-bit)
 -V:3.8           Python 3.8 (64-bit)

C:\Users\home>py -3.13t
Python 3.13.0 experimental free-threading build (tags/v3.13.0:60403a5, Oct  7 2024, 09:53:29) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```
@zooba Thanks for the help!
