### ISSUE TITLE
Support for function importing via regex

### ISSUE THREAD

**Issue by JosephTJennings** [python/cpython#125295]
# Feature or enhancement

### Proposal:

```python
Idea: from database_api import update_* 
Current: from database_api import update_success, update_failure, update_running, update_initialized
```

This could clean up some code bases by allowing users to regex match some functions when importing. Full Regex matching may be slightly difficult, as an MVP, support for asterisks (*) matching would go a long way.
In the above codeblock, this would import all functions which start with "update_" from the module database_api.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by JelleZijlstra** [comment]
This is a major feature that would need a PEP and discussion on https://discuss.python.org first. You should start by posting in the Ideas thread on Discuss, but as a warning, it's very unlikely that this feature will gain any traction.
