### ISSUE TITLE
win 10 Python-3.13.0 tkinter fails in venv

### ISSUE THREAD

**Issue by replabrobin** [python/cpython#125235]
# Bug report

### Bug description:

Installed python 3.13.0 in windows 10 at c:\python313

created venv at c:\users\rptla\tmp\py313

Tkinter based app failed to start in the venv. After testing tkinter I see these results ie error in venv starting Tk() wotks in installed.

In the venv
```bash
(py313) C:\Users\rptla\tmp\py313>python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> root = tkinter.Tk()
Traceback (most recent call last):
  File "<python-input-1>", line 1, in <module>
    root = tkinter.Tk()
  File "C:\python313\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/python313/lib/tcl8.6 C:/lib/tcl8.6 C:/lib/tcl8.6 C:/library C:/library C:/tcl8.6.14/library C:/tcl8.6.14/library



This probably means that Tcl wasn't installed properly.

>>>
```

in installed python
```bash
C:\Python313\Lib\tkinter>\python313\python
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> root=tkinter.Tk()
>>>
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-125250
* gh-125312

**Comment by y5c4l3** [comment]
Behaviors of TCL paths on Windows are sort of different, they look it up at `sys.prefix` which could be a venv root. PR changes it to `sys.base_prefix`.

https://github.com/python/cpython/blob/f9ae5d1cee2f8927a71cd4f1f66f10050a4f658a/Modules/_tkinter.c#L146

**Comment by RicardoEscobar** [comment]
My guess is that this requieres a 3.13.1 patch to fix it.

**Comment by joshburnett** [comment]
I see the same failure in Windows 11 as well, running in a venv:

```
Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tkinter
>>> root = tkinter.Tk()
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    root = tkinter.Tk()
  File "C:\Users\jburnett1\AppData\Local\Programs\Python\Python313\Lib\tkinter\__init__.py", line 2459, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    C:/Users/MY_USER_NAME/AppData/Local/Programs/Python/Python313/lib/tcl8.6 C:/Users/jburnett1/AppData/Local/Programs/Python/lib/tcl8.6 C:/Users/MY_USER_NAMEAppData/Local/Programs/lib/tcl8.6 C:/Users/MY_USER_NAME/AppData/Local/Programs/Python/library C:/Users/MY_USER_NAME/AppData/Local/Programs/library C:/Users/MY_USER_NAME/AppData/Local/Programs/tcl8.6.14/library C:/Users/MY_USER_NAME/AppData/Local/tcl8.6.14/library
```

Running in the base Python install works OK.

My python.org-installed version is installed for just my user, and I do see the above-mentioned `init.tcl` file in `C:\Users\MY_USER_NAME\AppData\Local\Programs\Python\Python313\tcl\tcl8.6` but this directory is not listed in the traceback as one of the ones being searched.

**Comment by y5c4l3** [comment]
Bisects to https://github.com/python/cpython/commit/c67121ac6bf8ee36d79de92ef68fc3fde178d2a3, cc @vstinner would you mind having a look at my PR? :-)

**Comment by vstinner** [comment]
On Windows, when I build Python from source, TCL is loaded from `externals\tcltk-8.6.15.0` directory using an absolute path, so the bug was not spotted before. Even with a venv, `externals\tcltk-8.6.15.0` is found and used.

Thank you for the bug report and the fix.

**Comment by GnikSuc** [comment]
I have this same issue on win11. I also tried to add tcl and tk folders from source into \venv\Lib\site-packages, but it had no effect.

**Comment by vstinner** [comment]
> I have this same issue on win11. I also tried to add tcl and tk folders from source into \venv\Lib\site-packages, but it had no effect.

You should wait for Python 3.13.1 release to get the fix. You can use Python 3.12 in the meanwhile.

**Comment by Bran-Mak-Morn** [comment]
I can confirm the above - 3.13.0 Python Tcl wasn't installed properly (I'm using W11, Pycharm, venv). So you either provide paths for your Tkinter projects and keep 3.13.0 - an example below:

import os
os.environ['TCL_LIBRARY'] = r'path......'
os.environ['TK_LIBRARY'] = r'path......'

or go back to 3.12. :)

**Comment by bersbersbers** [comment]
I have used @replabrobin's workaround (setting environment variables) to mitigate this issue to a large degree.

Unfortunately, I have also noticed that this approach

> still leaves the command window visible.

For the record, I believe that is a separate issue, and I just came across #126084 which seems to take care of it.

**Comment by bvermeulen** [comment]
Until fixed add the following to your environment variables:

`TCL_LIBRARY = C:\Users\<user>\AppData\Local\Programs\Python\Python313\tcl\tcl8.6`

**Comment by grottixwoods** [comment]
I confirm, I encountered the same problem _tkinter.TclError: Can't find a usable init.tcl in the following directories...This probably means that Tcl wasn't installed properly.

As I understand it, the real problem is in python 3.13 running in venv. We are waiting for the patch.

**Comment by pnkmem429** [comment]
I'm sure it will be fixed soon, but if there are someone who don't want to use absolute path and don't want to downgrade Python,
then here's a fix:
1. Go to `TCL_LIBRARY = C:\Users\<user>\AppData\Local\Programs\Python\Python313\`
2. Copy `tcl` folder entirely
3. Go to your `venv` folder
4. Paste in the root of your `venv` folder

**Comment by deducture** [comment]
thx it helps

**Comment by TyPy2023** [comment]
I couldn't wait for a fix for the bug to come out, I did as you suggested, and it worked right away!
Thank you

**Comment by RicardoEscobar** [comment]
13.3.1 just dropped. I'll check if they fixed it...

**Comment by c-g-u** [comment]
Works now with 13.3.1.

**Comment by phaabe** [comment]
still same issue on uv `v0.5.26` with python `3.13.1`

I tried to install pysimplegui and run a simple example.

**Comment by tuxsol** [comment]
Same issue with 3.13.2

File "<snip>/customtkinter/__init__.py", line 5, in <module>
    from tkinter import Variable, StringVar, IntVar, DoubleVar, BooleanVar
ModuleNotFoundError: No module named 'tkinter'

**Comment by RanaUniverse** [comment]
so is this full issue is created in uv not in python.
i checked in ubuntu 24.04 where python 3.12 is installed, i found this also not work there

**Comment by zooba** [comment]
This is a better discussion to start at https://discuss.python.org under the "Help" category. It's certainly not related to this issue.
