### ISSUE TITLE
add const type in python 3.15 version

### ISSUE THREAD

**Issue by et2300** [python/cpython#125347]
# Feature or enhancement

### Proposal:

```python
const variable = 1# read only
variable += 1# error 

```

### Has this already been discussed elsewhere?

I have already discussed this feature proposal on Discourse

**Comment by et2300** [comment]
@gaogaotiantian

**Comment by skirpichev** [comment]
@et2300, could you please provide link to this discussion?  I can't find anything in recent topics, but such proposal are recurring (e.g. https://discuss.python.org/t/33531, https://discuss.python.org/t/26629).

**Comment by sobolevn** [comment]
@et2300 this will require a discussion and a PEP! 👍 
Please, start with https://discuss.python.org first. I am sure that this was discussed previously as well.

**Comment by skirpichev** [comment]
> this will require a discussio

@sobolevn, OP claims that this was discussed on d.p.o.
