### ISSUE TITLE
Using functools.partial to make functions not considered as methods when given as enum values no longer works

### ISSUE THREAD

**Issue by bluthej** [python/cpython#125316]
# Bug report

### Bug description:

On python 3.10-3.12, the following snippet prints `True`, while on Python 3.13.0 it prints `False`:

```python
from enum import Enum
from functools import partial


def a():
    pass


def b():
    pass


class MyCallables(Enum):
    A = a
    B = partial(b)


print(MyCallables.B in MyCallables)
```

This is because `MyCallables.B`  is considered to be `functools.partial(<function b at 0x756d7f0065c0>)` on 3.13.0, when it used to be `<MyCallables.B: functools.partial(<function b at 0x71f7cbc407c0>)>` before.

This is something I've been using to allow function values in enums not to be considered methods, which I most likely got from [this thread](https://stackoverflow.com/a/40339397/23446760). In the example above, `A` would always be considered a method.

It seems like on 3.13.0, the "wrapper class" approach is the only one that works.

### CPython versions tested on:

3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-125361

**Comment by ericvsmith** [comment]
@rhettinger

**Comment by ZeroIntensity** [comment]
Confirmed on current main as well.

**Comment by serhiy-storchaka** [comment]
This is an intentional change, and it is documented. See #121027.

Using `staticmethod()` to set a callable attribute without making it a method is more common idiom.

**Comment by bluthej** [comment]
@serhiy-storchaka maybe my title was not well formulated. This is what my issue boiled down to in my mind but I realize this is not exactly my problem, my problem is with the behavior I laid out in the snippet.

It used to be that we could use `partial` in order to use a function as the value for an enum variant while still having that variant act like one. With the breaking change you mentioned this is no longer possible, the enum variant is considered to be the function itself. But that's just a consequence (maybe even unintended, I don't know). 

At least there is still the wrapper class approach that works! I guess I'll just update the stackoverflow thread I mentioned in case people run into that.

**Comment by bluthej** [comment]
I should probably add that using `staticmethod` in that context doesn't do the trick.

**Comment by serhiy-storchaka** [comment]
As was mentioned in other answer, there is a better solution -- use `enum.member()` (I did not know about it!).

**Comment by bluthej** [comment]
Thanks for the tip! I had seen that answer but since it wasn't upvoted much I didn't try 😅

**Comment by hacscred** [comment]
I think this kind of randomly changing semantics scares away companies. Is there even any subset of Python that won't be subject to random changes? 

I think it's bad for Python's image. 

Torvalds doesn't break userland. Working programs written for version 3.12 shouldn't break for such "reasons". 

Perhaps there is a way for programs running in 3.13 to request 3.12 semantics, but if there isn't it is a very good argument to never ever write anything in Python again, because it's a moving target.

**Comment by ZeroIntensity** [comment]
@hacscred This kind of feedback isn't helpful--we don't intentionally break code, this is a regression. Please read PEP-387 for our backwards compatibility policy.

**Comment by MegaIng** [comment]
> This kind of feedback isn't helpful--we don't intentionally break code, this is a regression. Please read [PEP-387](https://peps.python.org/387) for our backwards compatibility policy.

No, this is clearly wrong. #121089 was an intentional break in backwards compatibility, disregarding PEP-387 with the argument that "this will only rarely break code".

**Comment by ZeroIntensity** [comment]
Yes, but this specific case with `Enum` was a regression and was fixed for this case. If that PR is causing more problems, open a new issue.
