### ISSUE TITLE
Syntax error display skips the first line of the traceback

### ISSUE THREAD

**Issue by SukramLeinad** [python/cpython#125380]
# Bug report

### Bug description:

Steps to reproduce:
```python
c := 3
```
Expected is:
```
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    c := 3
      ^^
SyntaxError: invalid syntax
```

But the actual result is:
```
  File "<python-input-0>", line 1
    c := 3
      ^^
SyntaxError: invalid syntax
```

While the visual difference is small, it could reflect an actual bug.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by AlexWaygood** [comment]
This seems to be a general problem with all syntax errors. It doesn't seem like it's a recent change, though; I can reproduce the difference in display from other kinds of exceptions with older Python versions as well:

```console
~/dev % python3.11 -c "c := 3"                  
  File "<string>", line 1
    c := 3
      ^^
SyntaxError: invalid syntax
~/dev [1] % python3.11 -c "a"     
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'a' is not defined
```

**Comment by skirpichev** [comment]
Is this a bug at all? :)  There is no traceback, it's not a runtime error.

**Comment by SukramLeinad** [comment]
> Is this a bug at all? :) There is no traceback, it's not a runtime error.

I would argue that it is a bug for the following reasons: 
1) Python has put a lot of work into improving error reporting recently. This bug pretty much negates that, especially for inexperienced users who are very easily confused. 
2) CPython is the basis for various Python shells like Pythonwin.exe, which have certain expectations as they reformat errors statements. A case in point is https://github.com/mhammond/pywin32/issues/2393#issuecomment-2408748817 where the buggy error statement gets even more corrupted.
3) The problem could be a symptom of an actually more serious underlying bug, so it's worth investigating. For example, I noticed that not only the first line is skipped, but also the module on the second line.

**Comment by skirpichev** [comment]
> especially for inexperienced users who are very easily confused

Wouldn't they be *more* confused with a line "Traceback ..." where is no actual traceback object?

Actually, it's documented that the header "Traceback (most recent call last)" shouldn't be printed here:
https://docs.python.org/3.13/library/traceback.html#traceback.print_exception

> various Python shells like Pythonwin.exe, which have certain expectations as they reformat errors statements

If they expect something else than documented in the Python docs - it's not CPython's fault.

> I noticed that not only the first line is skipped, but also the module on the second line.

But there is no module, isn't?  Your code has syntax error, it's not compiled.

**Comment by skirpichev** [comment]
CC @pablogsal

**Comment by SukramLeinad** [comment]
> Wouldn't they be _more_ confused with a line "Traceback ..." where is no actual traceback object?

Sorry, but that is beside my point.

> Actually, it's documented that the header [...]

I just noticed that Pythonwin.exe - like CPython - correctly prints the headers for all errors except syntax errors. So I don't think the defect is directly related to the traceback.print_exception method.

> But there is no module, isn't? Your code has syntax error, it's not compiled.

That is a good point.

**Comment by SukramLeinad** [comment]
Ok, got it:
As the code has a syntax error, it is not compiled.
As it is not compiled, it cannot be executed.
As it is not executed, there is no traceback object.
As there is no traceback object, the header “Traceback (most recent call last):” is omitted.

I agree this is not a defect. Sorry for your inconvenience...

**Comment by skirpichev** [comment]
> I don't think the defect is directly related to the traceback.print_exception method.

I don't think there is a defect at all.  Current behaviour seems to be correct and documented.  The old repl uses mentioned print_exception().  The new repl uses format_exception() method, that has arguments with same meaning.
