### ISSUE TITLE
Missing reference docs for dynamic module attributes

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#125423]
# Documentation

I was looking for a link to suggest a module level `__getattr__` as a potential solution to a problem, and couldn't find anything in the language reference about the feature.

https://docs.python.org/3/whatsnew/3.7.html#whatsnew37-pep562 just links back to the PEP rather than anywhere in the regular docs.

(intentionally not marking as already triaged, as this could be a dupe - searching on my phone didn't pick up any obvious hits but I could easily have missed something relevant)

**Comment by skirpichev** [comment]
See https://docs.python.org/3.13/reference/datamodel.html#customizing-module-attribute-access

a follow up: PEP 726

**Comment by AA-Turner** [comment]
Is [3.3.2.1. Customizing module attribute access](https://docs.python.org/3/reference/datamodel.html#customizing-module-attribute-access) enough, or were you looking for an intersphinx target?

A

**Comment by ncoghlan** [comment]
That'll do it - I just failed to find it via searching!
