### ISSUE TITLE
Doc for ConfigParser misses `allow_unnamed_section=False` param

### ISSUE THREAD

**Issue by litlighilit** [python/cpython#125436]
Currently

[doc for configparser.ConfigParser](https://docs.python.org/release/3.13.0/library/configparser.html#configparser.ConfigParser)

misses `allow_unnamed_section=False` param, which is added in https://github.com/python/cpython/pull/117273

![Screenshot_2024-10-14-16-21-01-815_org.mozilla.firefox-edit.jpg](https://github.com/user-attachments/assets/adc5f269-e364-4c4d-9272-4f73ccc5f220)

### Linked PRs
* gh-125437
* gh-126421

**Comment by Eclips4** [comment]
Hello!
Thanks for the report. Would you like to send a PR with fix? :)

**Comment by litlighilit** [comment]
Ok

**Comment by litlighilit** [comment]
Wait, I suddenly find

**Comment by litlighilit** [comment]
> I suddenly find that 'Changed since 3.13' is missing for ConfigParser  allow_unnamed_section, too.

Shall I append this fix in the same PR?

**Comment by Eclips4** [comment]
> I suddenly find that 'Changed since 3.13' is missing for ConfigParser allow_unnamed_section, too.
> 
> Also decription about "When allow_unnamed_section is True,..." should goes below https://docs.python.org/3/library/configparser.html#configparser.ConfigParser, like any other params

Yeah, you're right. Let's only do things related to `allow_unnamed_section` in #125436 and other improvements in the follow-up PR.

**Comment by litlighilit** [comment]
Ok.

at least as of now, all commits are about `allow_unnamed_section*`
