### ISSUE TITLE
Remove `PyUnicode_READY` in `unicodeobject.h`

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#125449]
# Feature or enhancement

### Proposal:

```python
# Add a code block here, if required
```
In https://github.com/python/cpython/blob/main/Doc/deprecations/c-api-pending-removal-in-future.rst.
```
PyUnicode_READY Unneeded since Python 3.12.
```

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-125450

**Comment by picnixz** [comment]
Unless there is a real need to remove public macros/functions, even if they are useless, we usually don't do it. We don't want to un-necessarily break code that are still using them (the maintenance cost does not seem that hard).

cc @vstinner

**Comment by rruuaanng** [comment]
As far as I investigated. In the master branch, there is no file using it.

**Comment by picnixz** [comment]
Yes, but what about external code? it's located in a header, so anyone can include them. The pending removal section has no planned removal date so unless there is a real need to remove it, we should first plan *when* it should be removed.

**Comment by vstinner** [comment]
Please keep this function. I suggest to close the issue.

A code search on `PyUnicode_READY` in PyPI top 7,500 projects found 133 matching lines in 43 projects.
