### ISSUE TITLE
csv.writer states csv module has no 'writer' member

### ISSUE THREAD

**Issue by sumguyinspain** [python/cpython#125480]
# Documentation

When i attempted to write to a csv file it said that the module 'csv' has no 'writer' or  'QUOTE_MINIMAL' member.
After this  i attempted to copy exactly what is in the documentation and it gave the same error.

**Comment by JelleZijlstra** [comment]
What version of Python are you running? You may be using an old version.

**Comment by sumguyinspain** [comment]
python 311

**Comment by ericvsmith** [comment]
You should ask this question on https://discuss.python.org/c/help/7 . You probably have your own module named csv.
