### ISSUE TITLE
Remove `Py_TPFLAGS_HAVE_FINALIZE` macro

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#125447]
# Feature or enhancement

### Proposal:

In https://github.com/python/cpython/blob/main/Doc/deprecations/c-api-pending-removal-in-future.rst, Many of these goals have been achieved, and this one doesn't seem to have been removed.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-125448

**Comment by rruuaanng** [comment]
I agree with keeping it in the header file. But I think it is necessary to remove its use in the code base.

**Comment by vstinner** [comment]
If you want to remove such constant, you should start by deprecating, and help projects to stop using it.

A code search in PyPI top 7,500 projects found that 6 projects are using it:

* Cython (3.0.9)
* Nuitka (2.1.2)
* catboost (1.2.3)
* cffi (1.16.0)
* gevent (24.2.1)
* orjson (3.9.15)

Check how these projects use the constant.

**Comment by rruuaanng** [comment]
It seems that the projects used for use are limited. I'll go to the classifier of these projects to solve these problems.

**Comment by da-woods** [comment]
Why is there any kind of urgency with this? Why not follow the normal process and announce an actual version well in advance and then wait until then. 

Ultimately this is just an extra unused numeric constant that's hanging around so isn't doing any immediate harm. 

Cython still supports Python 3.7 for the moment so does use the constant for that version. I'm sure we could work around the removal. But I'm not sure it's the best use of our time to have to respond to a sudden, unannounced and unnecessary removal.

**Comment by vstinner** [comment]
There is no urgency. I suggest to close this issue.
