### ISSUE TITLE
Allow the usage of the grave accent character (`) for string literals and string formatting

### ISSUE THREAD

**Issue by harmin-parra** [python/cpython#125418]
# Feature or enhancement

### Proposal:

Currently, string literals in python are surrounded by apostrophes (') or quotation marks (")

```
a = "first string"
b = 'second string'
```
The inconvenience is that if we want a string containing both `'` and `"`, we need to escape them

```
c = "string with \" and ' characters"
d = 'string with " and \' characters'
e = f"string {a} with \" and {b} with ' characters"
```
It would be nice to use the accent character as a third option to surround string literals and string substitutions, so I can do
```
f = `string with " and ' characters without escaping`
g = f`string {a} with " and {b} with ' characters without escaping`
```

It is the case with **Javascript** and **node.js**

### Has this already been discussed elsewhere?

No response given

**Comment by rruuaanng** [comment]
This may add an additional string representation, which I think should be considered seriously, rather than blindly following the implementation of other languages. I'm trying to test this change.

**Comment by rruuaanng** [comment]
I almost forgot, it seems that this can meet your need
```
s = ''' 'a' "b" '''
```

**Comment by skirpichev** [comment]
Yet another type of quotes is not a minor feature request - this is something, that should be discussed on https://discuss.python.org/c/ideas/6 first.  Then we can consider to reopen this issue.

**Comment by terryjreedy** [comment]
Backticks were part of Python syntax until 2.7 as +- equivalent to [repr](https://docs.python.org/2.7/reference/expressions.html#string-conversions).  They were not popular with most people and reuse would face opposition.  Any discussion should start with a review of the discussion then.

**Comment by harmin-parra** [comment]
> I almost forgot, it seems that this can meet your need
> 
> ```
> s = ''' 'a' "b" '''
> s = f''' '{1}' "{1}" '''
> ```

Thanks for the tip
