### ISSUE TITLE
f_lineno has different results on Windows and Linux

### ISSUE THREAD

**Issue by Almenon** [python/cpython#125422]
# Bug report

### Bug description:

On Windows 10, `f_lineno` is 1. On WSL (Ubuntu 20), it is 611. I don't see any mention of cross-platform differences called out in the [bdb docs](https://docs.python.org/3.12/library/bdb.html), so I'm wondering if this is a bug.

```python
import bdb

f = {}

class areplDebug(bdb.Bdb):
    # override
    def user_line(self,frame):
        global f
        f = frame

b = areplDebug()
b.run('x=1+5',{},{})

print('frame lineno is ' + str(f.f_lineno)) # 611 on Linux, 1 on Windows 
import linecache
line = linecache.getline(f.f_code.co_filename, f.f_lineno)
print('frame file is: ' + f.f_code.co_filename) # '/home/almenon/.pyenv/versions/3.12.7/lib/python3.12/bdb.py' on Linux,  `<string>` on windows
print('frame line is: ' + line) # '            sys.settrace(None)\n' on Linux, None on Windows
```

It's not a WSL-specific issue because I'm getting the same error in Github CI. See https://github.com/Almenon/AREPL-backend/actions/runs/11316437382/job/31468723754?pr=193

**Reproduction**:
Checkout https://github.com/Almenon/AREPL-backend/tree/8aab53e834be9ec4c1a41de08831107446051bc5. Then:
```
cd AREPL-backend/python
python -m pip install -r requirements.txt
pytest
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

### Linked PRs
* gh-125427
* gh-125530
* gh-125531

**Comment by Almenon** [comment]
Another thing I should mention is that Python 3.8 through 3.11 all pass the unit tests in Linux (i.e. `f_lineno` is 1)

**Comment by gaogaotiantian** [comment]
Not all changes were listed on whatsnew :) Sometimes the changes were not user visible, or not important enough to make it (there are a lot of commits to stdlib in a version). This is not super serious but it is something we should fix. I'll work on it.

**Comment by Almenon** [comment]
oh cool, it's an actual bug? This is the first bug I've found in Python :D 

What should the desired behavior be? I'm not sure if 611 is correct or 1

**Comment by gaogaotiantian** [comment]
It should be `1`. `611` is from `bdb.py` and the user should not receive any events from `bdb.py`.
