### ISSUE TITLE
error message is misleading when executing await on non-async func 

### ISSUE THREAD

**Issue by sandeep-gh** [python/cpython#125511]
# Bug report

### Bug description:

```python
 def wrapper(afunc):
    async def hook(arg):
        arg = arg + 1
        return await afunc(arg)
    return hook


# bug missing async keyword
def afunc(arg):
    print(f"afunc called with arg = {arg}")
    pass

callback_func = wrapper(afunc)

import asyncio
asyncio.run(callback_func(5))

```
The error message is: 
`TypeError: object NoneType can't be used in 'await' expression`

The object is of type function , just not async function. 

### CPython versions tested on:

3.11

### Operating systems tested on:

Other

**Comment by picnixz** [comment]
I agree (though AFAICT it should be `afunc(6)` but that's besides the point). I'm closing it as a `non-CPython issue`. More precisely, if you were to unroll the construction, `callback_fun` would be equivalent to:

```py
async def callback_func(x):
	x = x + 1
	z = afunc(x)  # your 'afunc' returns None
	t = await z   # await None raises normally
	return t
```
