### ISSUE TITLE
Deprecate `prefix_chars` in `argument_group`

### ISSUE THREAD

**Issue by savannahostrowski** [python/cpython#125542]
Now, after `conflict_handler` and `argument_default` have been documented, we can deprecate `prefix_chars`. @savannahostrowski, are you interesting? We should just add a runtime warning in the `_ArgumentGroup` constructor, test, and documentation (the `deprecated` instruction and something in What's New).

_Originally posted by @serhiy-storchaka in https://github.com/python/cpython/issues/89819#issuecomment-2414391217_

https://docs.python.org/3/library/argparse.html#argument-groups
            

### Linked PRs
* gh-125563

**Comment by serhiy-storchaka** [comment]
Strictly, speaking, there was no need to open a new issue, as this change is the solution for #89819.

**Comment by savannahostrowski** [comment]
D'oh! My bad—I must have mistakenly done this, thinking the other issue was closed after I documented the other two parameters!
