### ISSUE TITLE
it's no longer possible to delete items from f_locals (FrameLocalsProxy) in 3.13+

### ISSUE THREAD

**Issue by deanagarrott** [python/cpython#125590]
# Bug report

### Bug description:

```python
           try:
                driver.switch_to.alert.accept()
                driver.switch_to.alert.dismiss()
            except:
                pass
```
In the example script above, if the code falls into the except: pass block due to an alert not being displayed, the script will ultimately fail (even if no coding errors are encountered) with FAILED (errors=1) .
Also, the following messages will be displayed in the output:
![image](https://github.com/user-attachments/assets/76aedcbb-a68c-44a8-81e1-6b599aa1f5a8)

This code works fine in Python 3.12. The script succeeds with message OK and none of the above error messages. We can't move to 3.13 version until this is fixed.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-125616
* gh-125797

**Comment by JelleZijlstra** [comment]
This sounds like an issue in the version of `pydevd` bundled by the Microsoft Python extension.

I assume it's related to the FrameLocalsProxy changes from PEP-667; cc @gaogaotiantian.

**Comment by ZeroIntensity** [comment]
Maybe `FrameLocalsProxy` should just implement pop? (Or better yet, the rest of the `dict` interface.)

**Comment by graingert** [comment]
> Maybe `FrameLocalsProxy` should just implement pop? (Or better yet, the rest of the `dict` interface.)

problem is you cannot remove items from FrameLocalsProxy: https://github.com/python/cpython/blob/d83fcf8371f2f33c7797bc8f5423a8bca8c46e5c/Objects/frameobject.c#L162

**Comment by markshannon** [comment]
Popping and deleting keys in the "extras" dict should be fine.
It gets complicated when the key is a "fast" local.

In the style of the PEP, this would give us:

```Py

    def __delitem__(self, name):
        del self._extra_locals[name]

    def pop(self, name, default):
        return self._extra_locals.pop(name, default)
```

**Comment by gaogaotiantian** [comment]
The semantics of `f_locals` has changed. `f_locals` used to be a pure dict which was written back to the real locals on certain occasions (the most common one is returning from trace functions). The old behavior, when you remove a key from `f_locals`, if it was written back, was to set the local variable to `None` and generate a warning - a very inconsistent and confusing behavior.

**Comment by gaogaotiantian** [comment]
> Popping and deleting keys in the "extras" dict should be fine. It gets complicated when the key is a "fast" local.

Let's allow popping and deleting keys in extras, and generate an exception (we are generating one now on `del`) if the user tries to remove a real local variable. Do we consider this a bug so we need to backport it to 3.13?

**Comment by graingert** [comment]
> The semantics of `f_locals` has changed. `f_locals` used to be a pure dict which was written back to the real locals on certain occasions (the most common one is returning from trace functions). The old behavior, when you remove a key from `f_locals`, if it was written back, was to set the local variable to `None` and generate a warning - a very inconsistent and confusing behavior.

how do you generate the warning?

I tried this on 3.12 and didn't see a warning, and the local didn't get set to None:

```python
import sys

class A:
    pass


def foo():
    a = A()
    f_locals = sys._getframe().f_locals
    del f_locals['a']
    print(a)
    print(f_locals)


foo()
```


```
 graingert@conscientious  ~/projects  python3.12 -Werror demo.py
<__main__.A object at 0x7ae782f40230>
{}
 graingert@conscientious  ~/projects  python3.13 -Werror demo.py
Traceback (most recent call last):
  File "/home/graingert/projects/demo.py", line 15, in <module>
    foo()
    ~~~^^
  File "/home/graingert/projects/demo.py", line 10, in foo
    del f_locals['a']
        ~~~~~~~~^^^^^
TypeError: cannot remove variables from FrameLocalsProxy
```

**Comment by deanagarrott** [comment]
Hello. Just checking back on this bug. Is there a plan to fix it and update the current Python 3.13 version with the fix? If so, when is that expected so I can reinstall Python 3.13? Thanks.

**Comment by gaogaotiantian** [comment]
The fix is in #125590 and it should be merged soon. We don't update the *current version* of 3.13, so 3.13.0 will be always like this without the fix. However, 3.13.1 should come up with the fix. It's estimated to be released two months after 3.13.0 so probably December.

**Comment by deanagarrott** [comment]
> The fix is in #125590 and it should be merged soon. We don't update the _current version_ of 3.13, so 3.13.0 will be always like this without the fix. However, 3.13.1 should come up with the fix. It's estimated to be released two months after 3.13.0 so probably December.

Has version 3.13.1 been released yet?

**Comment by graingert** [comment]
Expected on the 12th https://peps.python.org/pep-0719/#bugfix-releases

**Comment by JelleZijlstra** [comment]
I believe the release is currently in progress, actually. The announcements should come shortly.

**Comment by graingert** [comment]
https://discuss.python.org/t/python-3-13-1-3-12-8-3-11-11-3-10-16-and-3-9-21-are-now-available/73214

It's out
