### ISSUE TITLE
Wrap unused argument in _sqlite/connection.c with Py_UNUSED

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#125510]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
It seems that in _sqlite/connection.c, although the function argument are named unused, they do not actually use `__attribute__((unused))`. I'm not sure if this is intentional, but doing so can eliminate warnings from the compiler under -Wall.

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-125509

**Comment by hugovk** [comment]
Please fill in the issue template. Why is this a bug?

**Comment by rruuaanng** [comment]
Sorry, I have added the issue description.

**Comment by erlend-aasland** [comment]
I'm sorry, but this is probably encouraged by my acceptance of #125351. We don't usually encourage cosmetic changes like this. I probably should've rejected #125351.

Let's not go into a blanket change where we add `Py_UNUSED` all over the place. If unused arg warnings become a problem, let's fix them when they appear.

**Comment by ZeroIntensity** [comment]
It's worth noting that naming something `unused` should mark it as unused to the compiler anyway. I'm not going to dig through source right now, but I'm like 70% sure that `Py_UNUSED(name)` expands to `unused_name`, so changing really has no effect.
