### ISSUE TITLE
Unused code warning in `_testembed.c`

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#125517]
# Bug report

Link: https://github.com/python/cpython/actions/runs/11333284963/job/31517440086#step:6:1315

Report:

```
./Programs/_testembed.c:1904:5: warning: code will never be executed [-Wunreachable-code]
    const char *err_msg;
    ^~~~~~~~~~~~~~~~~~~~
sed -e "s,/usr/bin/env python3,/usr/local/bin/python3.14," < ./Tools/scripts/pydoc3 > build/scripts-3.14/pydoc3.14
./Programs/_testembed.c:2052:5: warning: code will never be executed [-Wunreachable-code]
    const char *err_msg;
sed -e "s,@EXENAME@,/usr/local/bin/python3.14," < ./Misc/python-config.in >python-config.py
    ^~~~~~~~~~~~~~~~~~~~
```

Source of problem:
- We cannot have `goto` targets on variable declarations.
- So, they are declared right above: https://github.com/python/cpython/blob/cc5a225cdc2a5d4e035dd08d59cef39182c10a6c/Programs/_testembed.c#L1903-L1910
- So, this warning marks `const char *err_msg;` as unreachable code

I propose to declare this variable before the first `goto`. This way we can remove this warning. And since this is just a test, we can do that freely.

### Linked PRs
* gh-125518

**Comment by vstinner** [comment]
On Fedora 40 with clang 18.1.8, I get the following warning:

```
./Programs/_testembed.c:1906:5: warning: label followed by a declaration is a C23 extension [-Wc23-extensions]
 1906 |     const char *err_msg;
      |     ^
1 warning generated.
```
