### ISSUE TITLE
colors are missing on (Base)ExceptionGroup tracebacks in the pyrepl

### ISSUE THREAD

**Issue by graingert** [python/cpython#125593]
### Bug description:

```python
import sys

class InvalidFruitException(Exception):
    pass


def eat_fruit(fruit):
    if fruit == "banana":
        raise InvalidFruitException("no herbs please, only fruit")
    if fruit == "rock":
        raise InvalidFruitException("too tough")


def demo_continue_loop():
    food = ["apple", "rock", "orange", "banana"]
    exceptions = []
    try:
        for i, f in enumerate(food):
            try:
                eat_fruit(f)
            except Exception as e:
                e.add_note(f"failed on loop {i=} {f=}")
                exceptions.append(e)
        if exceptions:
            raise ExceptionGroup("multiple errors eating food", exceptions)
    finally:
        del exceptions  # no refcycles please!

def main():
    demo_continue_loop()
    return 0

if __name__ == "__main__":
    sys.exit(main())
```

here's the output:
https://asciinema.org/a/681263
![681263](https://github.com/user-attachments/assets/825aa0ef-5b9d-45f2-a356-7a7176fac0cc)

I'd expect the `eat_fruit()` parts to be highlighted in red

### CPython versions tested on:

3.13, 3.14

### Operating systems tested on:

Linux, macOS

This was added in https://github.com/python/cpython/issues/112730 but it looks like ExceptionGroups were missed

### Linked PRs
* gh-125681
* gh-126021

**Comment by Eclips4** [comment]
@graingert are you working on this issue? If not, @wrongnull would like to take this one :)

**Comment by graingert** [comment]
@Eclips4 no I've not looked into it yet

**Comment by graingert** [comment]
one minor request I have is that exception notes have a color distinct to exception messages

**Comment by wrongnull** [comment]
I'm working on this and found a fix. The pull request will be sent tomorrow
