### ISSUE TITLE
Make `ctrl-c` interrupt `threading.Lock.acquire()` on Windows

### ISSUE THREAD

**Issue by colesbury** [python/cpython#125541]
# Feature or enhancement

Since Python 3.2, pressing `ctrl-c` (`SIGINT`) interrupts `threading.Lock.acquire()` on POSIX platforms, including Linux and macOS. However, this does not work on Windows. 

Now that `threading.Lock` and `threading.RLock` use `PyMutex` and `_PyRecursiveMutex` internally, this should be a lot easier to implement efficiently.

See also https://github.com/python/cpython/issues/125058

cc @pitrou @zooba @gpshead 

### Linked PRs
* gh-125546

**Comment by pitrou** [comment]
You mean here https://github.com/python/cpython/blob/aac89b54c5ee03c4d64fbdfbb6ea3001e26aa83a/Python/parking_lot.c#L114 ?

**Comment by colesbury** [comment]
Yes, we can use `WaitForMultipleObjectsEx()` with `_PyOS_SigintEvent()` there without performance implications because that is the slow path that's only taken if the thread is about to block.
