### ISSUE TITLE
Incorrect format passed to `__annotate__` function

### ISSUE THREAD

**Issue by sobolevn** [python/cpython#125507]
# Bug report

Consider this example:

```python
class My:
    def __annotate__(format):
        assert format == 2, format
        return {}

import annotationlib
annotationlib.get_annotations(My, format=2)
```

This will fail with:

```
Traceback (most recent call last):
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 7, in <module>
    annotationlib.get_annotations(My, format=2)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/sobolev/Desktop/cpython2/Lib/annotationlib.py", line 688, in get_annotations
    return dict(_get_dunder_annotations(obj))
                ~~~~~~~~~~~~~~~~~~~~~~~^^^^^
  File "/Users/sobolev/Desktop/cpython2/Lib/annotationlib.py", line 817, in _get_dunder_annotations
    ann = _BASE_GET_ANNOTATIONS(obj)
  File "/Users/sobolev/Desktop/cpython2/ex.py", line 3, in __annotate__
    assert format == 2, format
           ^^^^^^^^^^^
AssertionError: 1
```

I think that we should still pass the format in `_BASE_GET_ANNOTATIONS`.

I will try to fix this, since this affects my other PR: https://github.com/python/cpython/pull/122262

CC @JelleZijlstra 

### Linked PRs
* gh-125534

**Comment by sobolevn** [comment]
Ok, this is not so easy. What happens here:
1. We try to get `__annotations__` first with `format=VALUE` via https://github.com/python/cpython/blob/aa18fd55d575a04e3aa782fedcd08dced26676e0/Lib/annotationlib.py#L817
2. If it fails with a `NameError` we actually try to call `__annotate__` with `format=FORWARDREF`: https://github.com/python/cpython/blob/aa18fd55d575a04e3aa782fedcd08dced26676e0/Lib/annotationlib.py#L692-L693

My code in https://github.com/python/cpython/pull/122262 never had any `NameError`s, so it never actually received the second call

But the question is: this is a good API? For me it feels like a very nuaced one with a lot of corner-cases.

**Comment by sobolevn** [comment]
Practical question, how can I differentiate two calls in https://github.com/python/cpython/blob/3b26e36e55f85a73866fa0ae04cb190ea6be01de/Lib/dataclasses.py#L1614-L1630
1. When calling with `format=VALUE` the first time, so it can be later called with `format=FORWARDREF`
2. When calling with `format=VALUE` the only time, because this is what was asked by the end user

**Comment by JelleZijlstra** [comment]
Would #124415 help here?

**Comment by sobolevn** [comment]
@JelleZijlstra hm, I don't think so. Here's my simplified reproducer with #124415 applied:

```python
import annotationlib

class My:
    def __annotate__(format):
        assert format == annotationlib.Format.FORWARDREF, format
        # Fails with: `AssertionError: 1`
        return {}

annotationlib.get_annotations(My, format=annotationlib.Format.FORWARDREF)
```

So, looks like it does still make the first call with `format=1`, even when asked to get forward refs explicitly.

**Comment by JelleZijlstra** [comment]
I understand the issue now. You want to return `typing.Any` in VALUE format, but in FORWARDREF format you want to avoid importing `typing` and return `ForwardRef("typing.Any")` directly.

For FORWARDREF format, we currently try using `__annotations__` directly before we call `__annotate__(FORWARDREF)`. If we change the order in which these operations happen, we could avoid your issue. I'll work on a PR for that.

**Comment by carljm** [comment]
To me it seems like a useful, and sensible, invariant that if you successfully get `VALUES` annotations (the default), then `FORWARDREFS` annotations will be identical to that. `FORWARDREFS` is intended for cases where `VALUES` would fail with `NameError`, and the API is designed around that assumption. I would prefer not to permit objects where `FORWARDREFS` annotations permanently differ from `VALUES` annotations. So I would rather not make changes here.

To me, the proposed approach for dataclasses seems like over-optimization. I think it's fine to always import `typing` -- someone is introspecting an annotation that uses `typing.Any`, after all. There may be other possibilities to avoid this, but I would need to look at the problem more.

**Comment by larryhastings** [comment]
What Carl said.  This should be documented behavior: if `__annotations__` is set, that value will be returned for `VALUES` or `FORWARDREF` formats and `__annotate__` won't be called.

**Comment by JelleZijlstra** [comment]
Thanks, then let's stick with the current behavior.
