### ISSUE TITLE
Configure `EXEEXT` hacks are interfering with `AX_C_FLOAT_WORDS_BIGENDIAN`

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#125698]
# Bug report

### Bug description:

We mess up `EXEEXT` in `configure.ac`:

https://github.com/python/cpython/blob/cda0ec8e7c4e9a010e5f73c5afaf18f86cb27b97/configure.ac#L1323-L1340

This creates problems[^1], since `AX_C_FLOAT_WORDS_BIGENDIAN` expects `EXEEXT` and `ac_exeext` to be the same. `EXEEXT` and `ac_exeext` are set up by `AC_PROG_CC`:

https://github.com/python/cpython/blob/cda0ec8e7c4e9a010e5f73c5afaf18f86cb27b97/configure.ac#L1026

We can mitigate this by:

1. setting `ac_exeext=$EXEEXT` after L1340 in `configure.ac`
2. use another variable than `EXEEXT`; for example `EXE_SUFFIX`
3. other workarounds?

My gut feel regarding these is that I'd really not like to add more `EXEEXT` hacks, so I'd like to avoid 1). 2) _should_ be ok, given that no-one else are depending on `EXEEXT` (cc. @hroncok).

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux, macOS, Other

[^1]: https://github.com/python/cpython/pull/125571#issuecomment-2422385731, https://github.com/python/cpython/pull/125571#issuecomment-2422414137

### Linked PRs
* gh-125699
* gh-125758
* gh-125995
* gh-126006
* gh-126007

**Comment by erlend-aasland** [comment]
cc. @damelang, author of `AX_C_FLOAT_WORDS_BIGENDIAN`.

**Comment by erlend-aasland** [comment]
Another workaround, _could_ be to move the float checks to before our `EXEEXT` hacks, but who knows what will break next time.

**Comment by hroncok** [comment]
> cc. @hroncok

I am not entirely sure what's my input here supposed to be.

**Comment by erlend-aasland** [comment]
> I am not entirely sure what's my input here supposed to be.

I just suspected a third-party consumer of our build system would like to receive a heads-up when I proposed a rename of one of the configure/Make variables.

Anyway, as I feared, the renaming broke CI, so I'm reverting it. I suggest instead to amend Dan Amelang's patch to use `ac_exeext` iso. `EXEEXT`.

**Comment by erlend-aasland** [comment]
I amended Dan's patch to use `ac_exeext` in Codespaces, and can confirm that that approach works for WASI.

**Comment by erlend-aasland** [comment]
See https://github.com/python/cpython-devcontainers/pull/30 for a proposed patch.

**Comment by erlend-aasland** [comment]
> I amended Dan's patch to use `ac_exeext` in Codespaces, and can confirm that that approach works for WASI.

OTOH, most of the macros in autoconf-archive does actually use `EXEEXT`, and not `ac_exeext`, implying that if we should land https://github.com/python/cpython-devcontainers/pull/30, we'd possibly run into a similar issue with another macro at a later point[^1]. Perhaps we should just work around this in `configure.ac` by making sure `ac_exeext` is set to the same as `EXEEXT`.

[^1]: yet another reason to switch to a more modern build system

**Comment by erlend-aasland** [comment]
Landed on the following solution:

- https://github.com/python/cpython/pull/125995

Automerge enabled for the backports. Closing this as completed.
