### ISSUE TITLE
An enhancement for type hinting

### ISSUE THREAD

**Issue by Unknownuserfrommars** [python/cpython#125602]
# Feature or enhancement

### Proposal:

So type hinting is GREAT. Don't get me wrong, but that is ACTUALLY THE BEST THING PYTHON EVER HAD AND NO KIDDING.
But then, type hints can't deal with cases like this:
```python
def bundle(what_ever_kwargs) -> list[dict*8]:
pass
```
So this is not supported. But to be PRECISE, we want to state that this function EXACTLY RETURNS 8 dictionaries.
So can we add support for this kind of type hinting (in 3.14 maybe?)

### Has this already been discussed elsewhere?

No response given

**Comment by sobolevn** [comment]
@Unknownuserfrommars in the meantime you can use `tuple[dict, dict, dict, dict, dict, dict, dict, dict]` as a type that returns exactly 8 dicts :)

**Comment by nineteendo** [comment]
This works at runtime, but mypy doesn't understand it:
https://mypy-play.net/?mypy=latest&python=3.12&gist=b8c2f957417f3600cb34563b200adb02

```python
>>> list[(dict,) * 8]
list[dict, dict, dict, dict, dict, dict, dict, dict]
```
