### ISSUE TITLE
Allow 3.13 py.exe can be use on PCBuild

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#125625]
# Bug report

### Bug description:

> @rem It is fine to add new versions tot
his list when they have released,
> @rem but we do not use prerelease bu
ilds here

### CPython versions tested on:

3.13, 3.14, CPython main branch

### Operating systems tested on:

Windows

### Linked PRs
* gh-125626
* gh-125649
* gh-125650

**Comment by zware** [comment]
Thanks :)
