### ISSUE TITLE
ProactorEventLoop raises AssertionError

### ISSUE THREAD

**Issue by BoilingNine** [python/cpython#125659]
# Bug report

### Bug description:

when I  from a child thread in a while True loop call asyncio.run to send msg. After a while asyncio logs an AssertionError.
[issue 78014 like this](https://github.com/python/cpython/issues/78014) but that closed
```python
assert f is self._write_fut # f is <_OverlappedFuture finished result=6>  self._write_fut is <_OverlappedFuture finished result=36>
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, Windows
```[tasklist]
### Tasks
```

**Comment by ZeroIntensity** [comment]
Hi, could you provide a reproducer?

**Comment by BoilingNine** [comment]
> Hi, could you provide a reproducer?

I can't provide a reproducer,Because I don't know why this problem is happening,But he's a must in my code

**Comment by ZeroIntensity** [comment]
It's still possible for this to be a bug in user code--exceptions in the standard library don't necessarily indicate a bug.

**Comment by BoilingNine** [comment]
> It's still possible for this to be a bug in user code--exceptions in the standard library don't necessarily indicate a bug.
Minimum code is this
```python
import asyncio
import threading

import uvicorn
from fastapi import FastAPI
from fastapi import WebSocket
from starlette.websockets import WebSocketDisconnect

# main app
app = FastAPI(title='test', debug=True,
              version='0.0.1', description="""test""",
              on_startup=[]
              )

def send_msg(websocket):
    while True:
        asyncio.run(websocket.send_text("This is the message sent by the child thread"))


@app.websocket("/")
async def root(websocket: WebSocket):
    await websocket.accept()
    t_record = threading.Thread(target=send_msg,args=[websocket])
    t_record.daemon = True
    t_record.start()
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        print("xxxxx")

if __name__ == '__main__':
    uvicorn.run("main:app",
                host="127.0.0.1",
                port=8000)

```
requirements 
```python
fastapi==0.115.2
uvicorn==0.32.0
websockets==13.1
```
An error is triggered when I link this interface. I used python3.11.9.

**Comment by ZeroIntensity** [comment]
> I used python3.11.9.

I couldn't reproduce this on Python 3.12. 3.11 is a security-only version, so we can't fix it if there is a bug.

Though, your code does look a little off. Generally, it's a bad idea to await a coroutine that was spawned in another event loop. I would refactor this to use a task:

```py
async def send_msg(websocket):
    while True:
        await websocket.send_text("This is the message sent by the child thread")


@app.websocket("/")
async def root(websocket: WebSocket):
    await websocket.accept()
    task = asyncio.create_task(send_msg())
    try:
        while True:
            await websocket.receive_text()
    except WebSocketDisconnect:
        task.cancel()
        print("xxxxx")
```

Anyways, I don't think this is an issue on our end.

**Comment by graingert** [comment]
@ZeroIntensity in your example you leak a task as you don't wait for it to handle the cancel.

It would be better to use an anyio TaskGroup here (FastAPI depends on anyio so it's available)

It's

```python
import anyio

async def send_msg(websocket):
    while True:
        await websocket.send_text("This is the message sent by the child thread")


@app.websocket("/")
async def root(websocket: WebSocket):
    await websocket.accept()
    try:
        async with anyio.create_task_group() as tg:
            tg.start_soon(send_msg, websocket)
            while True:
                await websocket.receive_text()
    except* WebsocketDisconnect:
        print("xxxxx")
```
