### ISSUE TITLE
Python implementation of `json.loads()` accepts invalid unicode escapes

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#125660]
# Bug report

### Bug description:

While reviewing #125652 and reading the documentation of [`int()`](https://docs.python.org/3/library/functions.html#int), I realised this condition in `json.decoder` is insufficient:

https://github.com/python/cpython/blob/f203d1cb52f7697140337a73841c8412282e2ee0/Lib/json/decoder.py#L61

```python
>>> import sys
>>> sys.modules["_json"] = None
>>> import json
>>> json.loads(r'["\u 000", "\u-000", "\u+000", "\u0_00"]')
['\x00', '\x00', '\x00', '\x00']
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-125683
* gh-125694
* gh-125695

**Comment by nineteendo** [comment]
cc @serhiy-storchaka

**Comment by nineteendo** [comment]
Maybe something like this? Although it might be a better idea to use a stricter function.

```python
esc = s[end:end + 4].strip()
if "_" not in esc and len(esc) == 4 and esc[0] not in "+-" and esc[1] not in "xX":
```

**Comment by serhiy-storchaka** [comment]
Either this, or simply use regexp.

**Comment by nineteendo** [comment]
Could there be other code that suffers from this problem?

**Comment by taleinat** [comment]
> Could there be other code that suffers from this problem?

Possibly, but that's out of context for this issue. If someone finds such issues they should be reported separately.
