### ISSUE TITLE
Multiprocessing Lock and RLock - invalid representation string on MacOSX.

### ISSUE THREAD

**Issue by YvesDup** [python/cpython#125679]
# Bug report

### Bug description:

Due of absence of the `sem_getvalue` C function in the MacOSX semaphore implementation, `Lock` and `RLock` representation strings are invalid in the `multiprocessing` module.

Call to `self._semlock._get_value()` raises an exception, and set part of repr with **'unknown'**.  
```py
import multiprocessing as mp
print(mp.Lock()     #  <Lock(owner=unknown)> vs <Lock(owner=None)> on Linux
print(mp.RLockj())  #  <RLock(unknown, unknown)> vs <RLock(None, 0)> on Linux
```

I propose to replace in the  `__repr__` method of each class the following test:
https://github.com/python/cpython/blob/37e533a39716bf7da026eda2b35073ef2eb3d1fb/Lib/multiprocessing/synchronize.py#L177
https://github.com/python/cpython/blob/37e533a39716bf7da026eda2b35073ef2eb3d1fb/Lib/multiprocessing/synchronize.py#L203

with `elif not self._semlock._is_zero():`.

This method is available and valid on each OS.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-125680
* gh-126533
* gh-126534

**Comment by gpshead** [comment]
Thanks!
