### ISSUE TITLE
Invalid an inconsistent results with python 3.13 without GIL

### ISSUE THREAD

**Issue by rkojedzinszky** [python/cpython#125646]
# Bug report

### Bug description:

I was experiencing with python 3.13 and with `--disable-gil`. I wrote my own little benchmark, and found it utilizes as many cpus as I have. Howewer, at the end I found the results strange and incorrect. The simple attached script demonstrates this.

```python
import threading
import sys

gsum = 0

def adder(n):
    global gsum

    i = 0
    for j in range(n):
        i += j

    gsum += i

def adder2(n):
    global gsum

    i = 0
    for j in range(n):
        gsum += j

def main():
    target = adder
    if len(sys.argv) > 1:
        target = adder2
    ts = []
    for n in range(2):
        t = threading.Thread(target=target, args=(10000000,))
        t.start()
        ts.append(t)

    for t in ts:
        t.join()

    global gsum
    print (gsum)

if __name__ == '__main__':
        main()
```

Running this script with my Debian's python (3.11.2) I get same results with functions `adder` or `adder2`. Howewer, when running with a locally built python 3.13, I get different results:

```
cpython$ python3 /tmp/parallel.py 
99999990000000
cpython$ python3 /tmp/parallel.py adder2
99999990000000
cpython$ ./python /tmp/parallel.py 
99999990000000
cpython$ ./python /tmp/parallel.py adder2
50779273597226
cpython$ ./python /tmp/parallel.py adder2
51710162160658
cpython$ ./python /tmp/parallel.py adder2
51725284970429
```

The first two invocations use my OS's python.

My python 3.13 compile time flags:
```
cpython$ ./python -msysconfig|grep CONFIG_ARGS
	CONFIG_ARGS = "'--disable-gil' '--enable-optimizations'"
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
`gsum += j` is not thread safe. 3.12 has a special mechanism about when GIL is dropped so this code happens to work consistently. That's not a promise and people should not rely on that.

**Comment by rkojedzinszky** [comment]
I've rewritten the code this way:

```

import threading
import sys


class G:
    def __init__(self):
        self.sum = 0


def adder(n, g: G):
    i = 0
    for j in range(n):
        i += j

    g.sum += i


def adder2(n, g: G):
    for j in range(n):
        g.sum += j


def main():
    g = G()
    target = adder
    if len(sys.argv) > 1:
        target = adder2
    ts = []
    for n in range(2):
        t = threading.Thread(target=target, args=(10000000, g))
        t.start()
        ts.append(t)

    for t in ts:
        t.join()

    print(g.sum)


if __name__ == '__main__':
    main()
```

I've eliminated the global variable. Is this normal that this still fails?

**Comment by rkojedzinszky** [comment]
I assumed that GIL-less python is somehow smart, and existing python code needs no change when running with an interpreter without GIL. So, I accept that this is how it should work, but then it's not just simple as configure with `--disable-gil` flag, and let's run all existing python code with a speedup.

**Comment by gaogaotiantian** [comment]
Like I said, `g.sum += j` is not thread-safe, regardless of the existence of GIL. If you run it in an older version of Python, maybe 3.9, it will be inconsistent too. It's not thread-safe by definition. A recent version of Python (sorry I can't remember which) introduced a mechanism where GIL is only released on branches, which happened to make the code consistent. It's *not* promised, it's *not* a feature, there's no backward compatibility guarantee. It's entirely possible that on 3.14, even with GIL, the code would be inconsistent.

Users should write thread-safe code, instead of relying on an undocumented behavior.

> existing python code needs no change when running with an interpreter without GIL

That's the goal but that won't happen. The realistic target is to minimize the change. And maybe for most code, no change. But again, it definitely does not mean that *all* code will behave exactly like before (otherwise what's the point of removing GIL?). Wrong code could still produce wrong result (and sometimes they produce the expected result).

**Comment by ZeroIntensity** [comment]
> I assumed that GIL-less python is somehow smart, and existing python code needs no change when running with an interpreter without GIL.

It *could* be, but if we locked code for every operation, then that will slow things down significantly, and isn't much better than just keeping the GIL.

**Comment by rkojedzinszky** [comment]
Yes, I totally understand threaded applications. Howewer, I really assumed that GILless python is compatible with existing code. Perhaps, many code is wrong, howewer, my simple code worked in all python because of the GIL. Perhaps wrongly, but many code assumed that behavior. Now, python without GIL is a _new_ language, with performance boost, but in reality not compatible with existing code. Thanks, I'll need to adapt to this.

**Comment by gaogaotiantian** [comment]
> my simple code worked in all python because of the GIL

```
$ python3.9 example.py adder2
65111534429047
$ python3.10 example.py adder2
99999990000000
```

I don't think it's fair to say `python3.10` is a *new* language compared to `python3.9` and not compatible with existing code, do you?

**Comment by gaogaotiantian** [comment]
Anyway, seems like you already got your answer and this is indeed an expected behavior, so I'll close the issue.

**Comment by colesbury** [comment]
In theory we could try to make this behave atomically. I'm not sure it's worthwhile. I don't think the performance would be much of an issue, but the bytecode changes might be tricky or awkward.

For example, the relevant bytecode is:

```
              LOAD_GLOBAL              2 (gsum)
              LOAD_FAST                2 (j)
              BINARY_OP               13 (+=)
              STORE_GLOBAL             1 (gsum)
```

If we did something like:

```
              LOAD_FAST                2 (j)
              BINARY_OP_GLOBAL      1 13 (gsum, +=)
```

We could make `BINARY_OP_GLOBAL` behave atomically and it would probably be at least as fast as the current implementation. But it might require multiple operands and all our current opcodes have at most one operand.

**Comment by gaogaotiantian** [comment]
I think making `+=` atomic is probably not worth it. And the issue brought up is not only about `+=`. In fact, in python3.13, you can do any operation in the for loop and they will all be atomic as long as you don't call functions and there are no branches. I don't think we can or should keep that in no-gil version.

**Comment by rkojedzinszky** [comment]
@gaogaotiantian thanks for all your answers, now I (and perhaps others) must treat python as a language with real threading support, with all of its consequences. My construct was definitely wrong, in any threading language that operation should be guarded by a lock or mutex.
