### ISSUE TITLE
Handle SIGTERM in asyncio

### ISSUE THREAD

**Issue by PSanetra** [python/cpython#125688]
# Feature or enhancement

### Proposal:

#32105 did introduce handling of `SIGINT` signals in `asyncio.run()`. I think it makes sense to support handling of `SIGTERM` signals in the same way as both signals are intended for shutting down a process gracefully. `SIGTERM` is also the default signal to stop a container: https://docs.docker.com/reference/cli/docker/container/stop/

### Has this already been discussed elsewhere?

No response given

**Comment by ZeroIntensity** [comment]
cc @graingert, you're better at dealing with asyncio stuff than I am.

**Comment by graingert** [comment]
cpython doesn't define a handler for SIGTERM for synchronous code, so I don't think asyncio should either

**Comment by ZeroIntensity** [comment]
@PSanetra, I'm going to suggest taking this to [DPO](https://discuss.python.org/). If it's not clear that something is a no-brainer, it generally has to get discussed there.

**Comment by graingert** [comment]
Let's close this for now
