### ISSUE TITLE
Python implementation of `json.loads()` accepts non-ascii digits

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#125682]
# Bug report

### Bug description:

You should be careful when matching unicode regexes:

https://github.com/python/cpython/blob/a0f5c8e6272a1fd5422892d773923b138e77ae5f/Lib/json/scanner.py#L11-L13

```python
>>> import sys
>>> sys.modules["_json"] = None
>>> import json
>>> json.loads("[1\uff10, 0.\uff10, 0e\uff10]")
[10, 0.0, 0.0]
```

I think it's safer to use `[0-9]` instead of `\d` here.

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

### Linked PRs
* gh-125687
* gh-125692
* gh-125693

**Comment by ZeroIntensity** [comment]
Why is this a bug? `int` and `float` support this as well:

```py
>>> int("\uff10")
0
>>> float("0e\uff10")
0.0
```

Arguably, the bug is that the C implementation *does not* support it.

**Comment by taleinat** [comment]
This can indeed be considered a bug, since it does not conform to the JSON specification in the standards.

See, for example, [Section 6: Numbers in IETF RFC 8259](https://datatracker.ietf.org/doc/html/rfc8259#section-6), which clearly defines the supported digits.

**Comment by ZeroIntensity** [comment]
Ah, I've applied the appropriate labels. Thank you for clarification :)

**Comment by hauntsaninja** [comment]
Good spot!
