### ISSUE TITLE
Some weird `make test` behavior

### ISSUE THREAD

**Issue by warsaw** [python/cpython#125669]
# Bug report

### Bug description:

To varying degrees, this affects the 3.12, 3.13,  and main branches.  Other branches are also probably affected but I haven't tested them.  They aren't showstoppers, but they are annoying.

1. `make test` breaks the terminal.  All input is hidden until you run the `reset` command.
2. Tcl/Tk tests hijack keyboard input.   This is doesn't seem to affect 3.12, moderately affects 3.13, and really breaks on main.  Essentially the tests pop up tons of windows, lots of stuff happens in those windows, and while that test is running, the desktop is largely unusable.  You can get some mouse events through, but no keyboard events.   It's especially bad with `main` - you basically can't get anything done until the tests complete.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-125730

**Comment by brandtbucher** [comment]
I'm definitely in favor of changing this. I use `make test` locally, and it's become increasingly frustrating to try to do *anything* while tests are running. If people really need to test GUI stuff locally like this, maybe we can provide them with an additional make target.

**Comment by tomasr8** [comment]
To turn off all GUI tests, you can disable the `gui` resource: `EXTRATESTOPTS="-uall,-gui" make test`, though maybe it should be the default for `make test`?

**Comment by sobolevn** [comment]
I proposed changing the `--fast-ci` definition to not spawn these windows: https://github.com/python/cpython/pull/125730
