### ISSUE TITLE
AST Parsed Decorator: col_offset Value for Decorator is Function Position +1.

### ISSUE THREAD

**Issue by horw** [python/cpython#125778]
# Bug report

### Bug description:

```python
import ast

code = """
@lala
def some_function():
    pass
"""

parsed_code = ast.parse(code)

fn = parsed_code.body[0]
print(fn.name, fn.col_offset)
dc = fn.decorator_list[0]
print(dc.id, dc.col_offset)

```

Output:
```
some_function 0
lala 1
```

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by skirpichev** [comment]
@horw, what you expected?

Does make sense for me, e.g.:
```py
>>> import ast
... 
... code = """
... @  lala
... def some_function():
...     pass
... """
... 
... parsed_code = ast.parse(code)
... 
... fn = parsed_code.body[0]
... print(fn.name, fn.col_offset)
... dc = fn.decorator_list[0]
... print(dc.id, dc.col_offset)
... 
some_function 0
lala 3
```

**Comment by horw** [comment]
I expect it to count the '@' position.

**Comment by skirpichev** [comment]
Why?

**Comment by skirpichev** [comment]
CC @Eclips4

**Comment by picnixz** [comment]
For instance:

```py
@foo
def    bar(): pass
```

has the following dump:

```
Module(
  body=[
    FunctionDef(
      name='bar',
      args=arguments(),
      body=[
        Pass(
          lineno=2,
          col_offset=14,
          end_lineno=2,
          end_col_offset=18)],
      decorator_list=[
        Name(
          id='foo',
          ctx=Load(),
          lineno=1,
          col_offset=1,
          end_lineno=1,
          end_col_offset=4)],
      lineno=2,
      col_offset=0,
      end_lineno=2,
      end_col_offset=18)])
```

As you can see, the col_offset for the `def` keyword is 0 and not something else, namely `FunctionDef` nodes are characterized by the position of their def and not the position of the function name. On the other hand, the decorator list is not a node per se, but can be seen as a "scope" containing some names. In the above example, the identifier 'foo' is a Name node (not some (non-existing) DecoratorNode). Therefore, it is correct that its column offset is 1 and not 0.

**Comment by Eclips4** [comment]
Hello!
I agree with @picnixz's explanation. This behavior is expected :)
