### ISSUE TITLE
`pyuwsgi` isn't installed

### ISSUE THREAD

**Issue by max0nT** [python/cpython#125775]
# Crash report

### What happened?

I'm trying replace python 3.12 to 3.13 and when I run `poetry install` almost all packeges is installed except `pyuwsgi`. But one is able to be isntalled when version is 3.12. This is a bug in the new version isn't it? There is screen of failed installing below. P.S.: C compiler is installed
![image](https://github.com/user-attachments/assets/c55718c6-0118-442d-b6ef-fbe6d2ef0cf6)

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
This is because pyuwsgi doesn't have precompiled binary wheels for 3.13 yet: https://pypi.org/project/pyuwsgi/#files 

This is not a CPython issue, please report it directly to the pyuwsgi project: https://uwsgi-docs.readthedocs.io/en/latest/
