### ISSUE TITLE
Remove deprecated `zipimport.zipimporter.load_module`

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#125747]
# Feature or enhancement

### Proposal:

These function have been deprecated since Python 3.10
At https://github.com/python/cpython/blob/main/Lib/zipimport.py#L224-L225
```python
msg = ("zipimport.zipimporter.load_module() is deprecated and slated for "
               "removal in Python 3.12; use exec_module() instead")
```
We forget remove this

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

```[tasklist]
### Tasks
```

**Comment by terryjreedy** [comment]
Duplicate of #125746.
