### ISSUE TITLE
reword some parts of "Using Python on Unix platforms"

### ISSUE THREAD

**Issue by partev** [python/cpython#125766]
I suggest the following changes to "Using Python on Unix platforms" on Linux section.

https://docs.python.org/3.14/using/unix.html#on-linux

1. "You can easily compile the latest version of Python from source." -> "You can compile the latest version of Python from source." remove the word "easily", because it is not needed.
2. "In the event that Python doesn’t come preinstalled and isn’t in the repositories as well, you can easily make packages for your own distro." -> "In the event that the latest version of Python doesn’t come preinstalled and isn’t in the repositories as well, you can make packages for your own distro." . There are two changes here "Python" -> "the latest version of Python", this is because all Linux distros have python, so the only reason to make your own python package is to get the latest version of Python. The second change is to remove the word "easily" again, because it is unnecessary.

### Linked PRs
* gh-125743
* gh-125793
* gh-125794

**Comment by zware** [comment]
Thanks for the report and patch :)
