### ISSUE TITLE
Add turtle module into installion option tcl/tk

### ISSUE THREAD

**Issue by CoderTCY** [python/cpython#125729]
# Feature or enhancement

### Proposal:

Just as the title said, add turtle module into the option in the picture:
![pic](https://github.com/user-attachments/assets/ad845f43-b672-4823-a115-99963b5b9977)
Because the turtle module is a tool requiring tkinter, why should it added since the user didn't want to install tkinter?

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126176

**Comment by Wulian233** [comment]
This is a literal description level problem, and not installing tcl/tk will cancel the installation of turtle. I don't think that's necessary. Should we add both tkinter turtle turtledemo IDLE

https://github.com/python/cpython/blob/main/PC/layout/main.py#L39-L40

**Comment by TanChenyu** [comment]
> This is a literal description level problem, and not installing tcl/tk will cancel the installation of turtle. I don't think that's necessary. Should we add both tkinter turtle turtledemo IDLE
> 
> https://github.com/python/cpython/blob/main/PC/layout/main.py#L39-L40

But I still found turtle.py in Lib folder even I didn't tick the option, is it a bug?
And sorry for my poor english ~_~

**Comment by Wulian233** [comment]
I sorry for my mistake. You were right. Unchecking tcl/tk will remove the installation of turtledemo,

https://github.com/python/cpython/blob/main/Tools%2Fmsi%2Ftcltk%2Ftcltk.wixproj#L31-L31

 but turtle will still be installed. However, turtle depends on tkinter.
https://github.com/python/cpython/blob/main/Lib%2Fturtle.py#L101-L101

**Comment by Wulian233** [comment]
BTW, I think this a bug

**Comment by terryjreedy** [comment]
I have informally suggested this somewhere once, but never made an issue.  It seems sensible, so thanks.  I do not know the situation on Mac, so included it also.  What *nix distributions do is out of our hands.

What does turtle do when `import turtle` fails?

I believe that there is some tkinter code somewhere in tools.  If so, it should fail gracefully.  IDLE tries to fail gracefully (write a message) if `import tkinter` fails and it was started from a console in such a way that there is a `sys.__stdout__` to write to.  Tools may not be installed anyway; are more likely to be started from a terminal; and have less bulk that turtle;  so omitting them seems less important.

**Comment by zooba** [comment]
Is the proposal here to list "turtle" as something that is added/removed with the Tcl/Tk option (that is, update the text in the installer)? Or do we need to actually make it add/remove with that option (that is, update the behaviour of the installer)?

I'm pretty sure we stopped distributing the Tools directory a while ago.

**Comment by terryjreedy** [comment]
Both:
1. Omit turtle along with idlelib and turtledemo when tck/tk and (_)tkinter are omitted.  (Two people say above that this is not the case now.  Turtle is installed when it cannot run.)
2. Modify label: "tcl/tk, tkinter, IDLE, and turtle" and desciption: "Installs tkinter, turtle, and the IDLE development environment."

I an not sure what happens on Macs.

**Comment by ned-deily** [comment]
> I a not sure what happens on Macs.

The Python for macOS installers we provide on python.org do not have an option to not install tkinter, IDLE, or turtle.

**Comment by terryjreedy** [comment]
Thanks.  Then this is Windows only.

**Comment by TanChenyu** [comment]
> Is the proposal here to list "turtle" as something that is added/removed with the Tcl/Tk option (that is, update the text in the installer)? Or do we need to actually make it add/remove with that option (that is, update the behaviour of the installer)?
> 
> I'm pretty sure we stopped distributing the Tools directory a while ago.

Change the behaviour. And I am confused about "just update the text in the installer", because the turtle.py will always kept.
