### ISSUE TITLE
wrong opname in 3.13 dis module documentation

### ISSUE THREAD

**Issue by stopa27** [python/cpython#125875]
According to python 3.13 changelog there are three new opcodes replacing FORMAT_VALUE - CONVERT_VALUE, FORMAT_SIMPLE and FORMAT_WITH_SPEC. 
But in https://docs.python.org/3/library/dis.html there are mentioned CONVERT_VALUE, FORMAT_SIMPLE and FORMAT_SPEC

### Linked PRs
* gh-126319
* gh-126320

**Comment by tomasr8** [comment]
Looks like a typo in the docs, would you like to open a PR?

**Comment by corona10** [comment]
@willingc and @Mariatta 
@rimi0108 She is the first-time contributor who is participating in the CPython Sprint KR today.
She is going to take a look at this issue :)

**Comment by corona10** [comment]
Thank you @rimi0108 for contributing, let's close the issue :)
