### ISSUE TITLE
InterpreterPoolExecutor Raises Attribute Error on Lambdas

### ISSUE THREAD

**Issue by paultiq** [python/cpython#125865]
# Bug report

### Bug description:

3.14.0a1+ [34653bb](https://github.com/python/cpython/commit/34653bba644aa5481613f398153757d7357e39ea), Windows 64bit

The following code raises an attribute error: 

```python
from concurrent.futures.interpreter import InterpreterPoolExecutor

with InterpreterPoolExecutor() as executor:
    future = executor.submit(lambda x: 10)
    
result = future.result() 
print(result)
```

This code runs:
```py
from concurrent.futures import ThreadPoolExecutor

with ThreadPoolExecutor() as executor:
    future = executor.submit(lambda: 10)

result = future.result()  # Get the result of the function
print(result)
```

Error:
```
AttributeError: module '__main__' has no attribute '<lambda>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\scratch\cpython\PCbuild\amd64\test1.py", line 4, in <module>
    future = executor.submit(lambda: 10)
  File "C:\scratch\cpython\Lib\concurrent\futures\thread.py", line 210, in submit
    task = self._resolve_work_item_task(fn, args, kwargs)
  File "C:\scratch\cpython\Lib\concurrent\futures\interpreter.py", line 64, in resolve_task
    data = pickle.dumps((fn, args, kwargs))
_pickle.PicklingError: Can't pickle <function <lambda> at 0x000001455882EDA0>: it's not found as __main__.<lambda>
when serializing tuple item 0
```

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Windows

**Comment by paultiq** [comment]
Unclear if related to https://github.com/python/cpython/issues/125864, so I filed separately, but they're similar.

**Comment by ZeroIntensity** [comment]
Yeah, lambdas can't get picked. I don't think there's anything that can be done.

**Comment by paultiq** [comment]
From the doc, https://github.com/python/cpython/blob/main/Doc/library/concurrent.futures.rst, I expected InterpreterPoolExecutor to behave similarly to ThreadPoolExecutor... yet in this regards, it behaves similar to ProcessPoolExecutor. 

The opening paragraph says: "It is a [:class:`ThreadPoolExecutor`](https://github.com/python/cpython/blob/main/Doc/library/concurrent.futures.rst#id32) subclass, which means each worker is running in its own thread.", which perhaps could be clarified that certain behaviors are more consistent with ProcessPoolExecutor.

**Comment by ZeroIntensity** [comment]
Sure, if you want to submit a PR updating the docs mentioning pickle limitations, that's fine. I'm fine with closing this, though.

**Comment by paultiq** [comment]
Fine to close, I'll mull over the doc and mnay suggest something. Thx.
