### ISSUE TITLE
Setting `None` to `skip_file_prefixes` of `warnings.warn()` gets error

### ISSUE THREAD

**Issue by hyperkai** [python/cpython#125818]
# Bug report

### Bug description:

[The doc](https://docs.python.org/3/library/warnings.html#warnings.warn) of `warnings.warn()` says `skip_file_prefixes` is `None` by default as shown below:

> warnings.warn(message, category=None, stacklevel=1, source=None, *, skip_file_prefixes=None)

But, setting `None` to `skip_file_prefixes` gets the error as shown below:

```python
import warnings

warnings.warn(message='Warning',
              category=None,
              stacklevel=1,
              source=None,
              skip_file_prefixes=None) # Error
            # ↑ ↑ ↑ ↑ ↑ ↑ ↑ ↑ ↑ ↑ ↑ ↑
```

> TypeError: warn() argument 'skip_file_prefixes' must be tuple, not None

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-125823
* gh-126216
* gh-126217

**Comment by tomasr8** [comment]
This is probably just a typo in the docs. The default value for that parameter as actually an empty tuple:

https://github.com/python/cpython/blob/4848b0b92ce2737cea08fa3b322fd0f0a671bb07/Lib/warnings.py#L302-L316


(It's also the case for the C module) The docs mention it too:

> [...] If supplied, it must be a tuple of strings.

Would you like to open a PR to fix the method signature in the docs?

**Comment by rruuaanng** [comment]
Maybe the task of repairing this document can be entrusted to me.
If there is no comment, I will launch a PR.

**Comment by erlend-aasland** [comment]
Thanks for the report, Kai, and thanks for the PR, James.
