### ISSUE TITLE
Add types for typing library: Mutable, Immutable

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python/cpython#125869]
# Feature or enhancement

### Proposal:

```python
from typing import Mutable, Immutable
# checker ok
a: Mutable = [1, 2, 3]
b: Immutable = (1, 2, 3)
# checker will be show errors for IDLEs
a: Mutable = (1, 2, 3)
b: Immutable = [1, 2, 3]
```

### Has this already been discussed elsewhere?

No response given

**Comment by hugovk** [comment]
> ### Has this already been discussed elsewhere?
> No response given

Thanks for the suggestion, please open a discussion about this first:

https://discuss.python.org/c/typing/32

And let's close this for now.

**Comment by hugovk** [comment]
Thanks for opening the discussion.

For reference: https://discuss.python.org/t/add-types-for-typing-library-mutable-immutable/68880.
