### ISSUE TITLE
Outdated post PEP-709 comment in `Python/codegen.c`

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#125832]
# Bug report

### Bug description:

After the implementation of https://peps.python.org/pep-0709/, this comment looks wrong:
https://github.com/python/cpython/blob/57e3c59bb64fc2f8b2845a7e03ab0abb029ccd02/Python/codegen.c#L4079-L4090

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-126322
* gh-126344
* gh-126345
* gh-126346

**Comment by picnixz** [comment]
Haven't checked in the code yet but generator expressions do not seem to be concerned by the inlining:

> Generator expressions are currently not inlined in the reference implementation of this PEP. In the future, some generator expressions may be inlined, where the returned generator object does not leak.

**Comment by rimi0108** [comment]
I will take a look :)

**Comment by corona10** [comment]
@willingc 

@rimi0108 is going to take a look at this issue during the sprint :)

**Comment by corona10** [comment]
Thanks for the contribution! @rimi0108

**Comment by corona10** [comment]
We need to handle backport patch as well.
