### ISSUE TITLE
improve fnmatch.fnmatch documentation

### ISSUE THREAD

**Issue by gordcodes** [python/cpython#125848]
# Documentation

In the documentation for fnmatch.
https://docs.python.org/3/library/fnmatch.html

It says that "Both parameters are case-normalized using os.path.normcase()". 

This implies that the strings are always case normalized but if you dive into the description of os.path.normcase, it's actually OS dependent. Windows is case insensitive while non Windows is case sensitive.

So I would like the documentation clarified with something basic like " Both parameters are case-normalized using os.path.normcase(), which behaves differently based on OS."

**Comment by picnixz** [comment]
It says that they are case-normalized using `os.path.normcase` and the docs of the latter says:

> Normalize the case of a pathname. On Windows, convert all characters in the pathname to lowercase, and also convert forward slashes to backward slashes. On other operating systems, return the path unchanged.

I don't think we'll need to restate it. cc @barneygale

**Comment by picnixz** [comment]
@gordcodes Thank you for your suggestion but we'll be closing this as `wont fix` as per Carol's suggestion.
