### ISSUE TITLE
pdb fails when setting a breakpoint to function names with generics-type annotations

### ISSUE THREAD

**Issue by baco** [python/cpython#125885]
# Bug report

### Bug description:

When having the new genetics syntax type annotations on a function:
```python
def bar[T](): ...
```
establishing a breakpoint returns the following message:
```
(Pdb) break bar
*** The specified object 'bar' is not a function or was not found along sys.path.
```

This also happens with _temporary breakpoins_ `tbreak`. This was tested using Python versions from Debian official repositories. The failure appears in 3.13.0 and 3.12.6.

Analyzing with @asottile they point out that the following lines: [Lib/pdb.py:121](https://github.com/python/cpython/blob/34653bba644aa5481613f398153757d7357e39ea/Lib/pdb.py#L121), [Lib/pdb.py:141](https://github.com/python/cpython/blob/34653bba644aa5481613f398153757d7357e39ea/Lib/pdb.py#L141) may be causing this behavior.

This issue relates to #125884 

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by gaogaotiantian** [comment]
This repros in 3.12 as well I believe?

**Comment by baco** [comment]
> This repros in 3.12 as well I believe?

Indeed, my bad saying it was not (got mixed up with the previous issue).
