### ISSUE TITLE
Infinite Regex search

### ISSUE THREAD

**Issue by jvahue** [python/cpython#125814]
# Bug report

### Bug description:

The following regular expression never seems to terminate when run against the second element in the list (data0) below.  Notice the only difference is at the very end of the second string ACARSMgr.c vs. the first string has A429Recv.c which matches, the second should not match and terminate.  If you run each string individually the first string terminates with a match and the second never finished ... at least while I waited (5+ minutes).  I know the regex is a little gnarly, but the compiler did not complain so I assume it is valid.  I tried it at regex101.com and most things failed except Go and Rust, others timed out

```python
# Add a code block here, if required
import re
descriptionRe = re.compile(
"Ignoring return value of function '.*?\\((?:(?:struct |enum )?.*?[, ]?)+\\)' \\(compare with ([Ll]ine[ \\t]+[0-9 ]+|[Ll]ines[ \\t]+[0-9, ]+), file <srcRoot>\\\\Utility\\.h, module <srcRoot>\\\\A429Recv\\.c\\)"
)
>>> data0 = [
"Ignoring return value of function 'strncpy_safe(char *, long, const char *, long)' (compare with line 59, file <srcRoot>\\Utility.h, module <srcRoot>\\A429Recv.c)", 
"Ignoring return value of function 'strncpy_safe(char *, long, const char *, long)' (compare with line 59, file <srcRoot>\\Utility.h, module <srcRoot>\\ACARSMgr.c)"
]
data = [i for i in data0 if descriptionRe.search(i)]
```

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Windows

**Comment by ericvsmith** [comment]
You should test it with the regex module on PyPI: https://pypi.org/project/regex/

**Comment by blhsing** [comment]
The pattern `(?:(?:struct |enum )?.*?[, ]?)+` is causing what is known as [catastrophic backtracking](https://www.regular-expressions.info/catastrophic.html). In this case you can avoid it by replacing `.*?` with `[^)]*`.

**Comment by picnixz** [comment]
IIRC, the SRE lib tries to avoid some catastrophic backtracking but does not aim to prevent all of them. So I'm not sure that we can do much =/ cc @serhiy-storchaka.

**Comment by serhiy-storchaka** [comment]
Concur with @blhsing. This is a normal behavior for NFA implementation of regular expressions. It can be avoided by rewriting the pattern.

**Comment by jvahue** [comment]
Thanks for your help on this, much appreciated.


Jeff Vahue

Knowlogic mobile 508.404.0067

knowlogic.com



________________________________
