### ISSUE TITLE
`gc.get_objects` can corrupt in-progress GC in free threading build

### ISSUE THREAD

**Issue by colesbury** [python/cpython#125859]
# Bug report

### Background

The free threading GC uses two queue-like data structures to keep track of objects:

* [`struct worklist`](https://github.com/python/cpython/blob/aaed91cabcedc16c089c4b1c9abb1114659a83d3/Python/gc_free_threading.c#L36-L42), which is a singly linked list that repurposes `ob_tid` for the linked list pointer

* [`_PyObjectStack`](https://github.com/python/cpython/blob/aaed91cabcedc16c089c4b1c9abb1114659a83d3/Include/internal/pycore_object_stack.h#L24-L26), which is effectively a dynamically sized array of `PyObject*`. (Implemented using a linked list of fixed size array buffers).

The `struct worklist` data structure is convenient because enqueueing objects doesn't require a memory allocation and so can't fail. However, an object can only be part of one "worklist" at a time, because each object has only one `ob_tid` field.

### Bug

Other threads can run while the GC is [finalizing cyclic garbage](https://github.com/python/cpython/blob/aaed91cabcedc16c089c4b1c9abb1114659a83d3/Python/gc_free_threading.c#L1257-L1263) and [while it's calling `tp_clear()`](https://github.com/python/cpython/blob/aaed91cabcedc16c089c4b1c9abb1114659a83d3/Python/gc_free_threading.c#L1272-L1284) and other clean-up.

During that time, some thread may call `gc.get_objects()`, which can return otherwise "unreachable" objects. The implementation of [`_PyGC_GetObjects`](https://github.com/python/cpython/blob/aaed91cabcedc16c089c4b1c9abb1114659a83d3/Python/gc_free_threading.c#L1514-L1519) temporarily pushes objects to a `struct worklist`, including objects that might already be part of some other worklist, overwriting the linked list pointer. This essentially corrupts the state of the in-progress GC and causes assertion failures.

### Proposed fix

* We should probably exclude objects in the "unreachable" (i.e. `_PyGC_BITS_UNREACHABLE`) from being returned by `gc.get_objects()`
* We should limit the use of `struct worklist` to the actual GC and use `_PyObjectStack` (or some other data structure) in `_PyGC_GetObjects()`. This reduces the risk of bugs causing an object to be added to more than one worklist.

### Linked PRs
* gh-125882
* gh-125921

**Comment by rruuaanng** [comment]
Hi @colesbury, if there is no objection, I would like to take over this task. I will submit a PR in the next few days. I will take plan `We should probably exclude objects in the "unreachable" (i.e. _PyGC_BITS_UNREACHABLE) from being returned by gc.get_objects()`.
I think using plan
`We should limit the use of struct worklist to the actual GC and use _PyObjectStack (or some other data structure) in _PyGC_GetObjects(). This reduces the risk of bugs causing an object to be added to more than one worklist.`
may cause the memory usage to become higher. So I choose a simple conditional return

**Comment by colesbury** [comment]
@rruuaanng - thank you for the offer, but I've already started working on this
