### ISSUE TITLE
ModuleNotFoundError: No module named 'distutils.msvccompiler'

### ISSUE THREAD

**Issue by tr1ppyb0y** [python/cpython#125836]
# Bug report

### Bug description:

It is regarding this error when installing, `pip install pylzma`

![image](https://github.com/user-attachments/assets/a865ce3f-6bf9-4876-9803-c7865beca941)

Same error occurs when I am running these commands in python shell, `from distutils import msvccompiler` or `from distutils.msvccompiler import MSVCCompiler`

Although, when I tried to `import` the `MSVCCompiler` in python shell with this command, `from distutils._msvccompiler import MSVCCompiler` it imported just fine. Please see the screenshot below.
![image](https://github.com/user-attachments/assets/d0d07022-2621-4fab-b36e-855ed40d47be)

I think it's just file naming issue, but please correct me if I am wrong.
![image](https://github.com/user-attachments/assets/02978099-03dc-427b-8b51-d7ff2670bcd7)

Please help.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
Sorry, but you should report this instead to the pylzma project.  The distutils package was removed from the stdlib in CPython 3.12.

**Comment by tr1ppyb0y** [comment]
Sorry, my bad.
Didn't know that. Thanks!!

**Comment by SouravLinkuna** [comment]
@tr1ppyb0y can yo let me know how did you resolved this issue?

**Comment by tr1ppyb0y** [comment]
> @tr1ppyb0y can yo let me know how did you resolved this issue?


Please refer to this reply, I have explained in detail,
https://github.com/fancycode/pylzma/issues/77#issuecomment-2429130679
