### ISSUE TITLE
Setting `bool` values to `lineno` argument of `warnings.filterwarnings()` and `warnings.simplefilter()` works

### ISSUE THREAD

**Issue by hyperkai** [python/cpython#125899]
# Bug report

### Bug description:

Setting the `float` value `3.14` to `lineno` argument of [warnings.filterwarnings()](https://docs.python.org/3/library/warnings.html#warnings.filterwarnings) and [warnings.simplefilter()](https://docs.python.org/3/library/warnings.html#warnings.simplefilter) gets the error message as shown below:

```python
import warnings
                                       # ↓ ↓ ↓ ↓ ↓ ↓
warnings.filterwarnings(action="ignore", lineno=3.14) # Error
warnings.simplefilter(action="ignore", lineno=3.14) # Error
                                     # ↑ ↑ ↑ ↑ ↑ ↑
print(warnings.filters)
```

> AssertionError: lineno must be an int >= 0

But setting the `bool` values `True` and `False` to `lineno` argument of `warnings.filterwarnings()` and `warnings.simplefilter()` works as shown below:

```python
import warnings
                                       # ↓ ↓ ↓ ↓ ↓ ↓
warnings.filterwarnings(action="ignore", lineno=True)
warnings.filterwarnings(action="ignore", lineno=False)
                                        # ↑ ↑ ↑ ↑ ↑ ↑
                                     # ↓ ↓ ↓ ↓ ↓ ↓
warnings.simplefilter(action="ignore", lineno=True)
warnings.simplefilter(action="ignore", lineno=False)
                                      # ↑ ↑ ↑ ↑ ↑ ↑
print(warnings.filters)
# [('ignore', None, <class 'Warning'>, None, False),
#  ('ignore', None, <class 'Warning'>, None, True)]
```

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
`bool` is a subclass of `int` so this is not really an issue per se IMO. They can be considered as 0 or 1. I don't think we should have a dedicated `if isinstance(x, bool)` just to raise an appropriate error.

I don't think we need to make those functions entirely fool-proof for any kind of int-subclasses. There is a trade-off between practicability and purity IMO.

cc @ncoghlan

**Comment by brettcannon** [comment]
I'm going to close this as this is just part of the cost of `bool` being a subclass of `int` and there's no way we can (or will) sprinkle type checks for `bool` everywhere `int` is acceptable. Your best option is to have your linter detect this sort of thing.
