### ISSUE TITLE
the link to "Contributing to Docs" redirects to a different URL

### ISSUE THREAD

**Issue by partev** [python/cpython#125909]
On the main python documentation page: https://docs.python.org/3.14/

there is a link to [Contributing to Docs](https://devguide.python.org/docquality/#helping-with-documentation) which links to "https://devguide.python.org/docquality/#helping-with-documentation" which redirects to "https://devguide.python.org/documentation/help-documenting/index.html#helping-with-documentation".

I think the link should directly link to "https://devguide.python.org/documentation/help-documenting/"

### Linked PRs
* gh-125826
* gh-125929
* gh-125930

**Comment by picnixz** [comment]
Closing since completed and backported.
