### ISSUE TITLE
ClassVar breaks dataclass fields

### ISSUE THREAD

**Issue by michael-123123** [python/cpython#125994]
# Bug report

### Bug description:

Hi,

I searched issues and couldn't find anything similar to this.
I'm not 100% sure it's a bug - possibly this is desired behavior?

To reproduce:

```python
from dataclasses import Field, field, dataclass
from typing import ClassVar


class A:
    sentinel: ClassVar[Field] = field()


@dataclass
class B:
    sentinel: ClassVar[Field] = field()


print("Class A")
print(A.sentinel)
print(A().sentinel)
print()


print("Class B")
try:
    print(B.sentinel)
except AttributeError as ex:
    print(ex)

try:
    print(B().sentinel)
except AttributeError as ex:
    print(ex)

print()
```

Output:
```shell
Class A
Field(name=None,type=None,default=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,default_factory=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,_field_type=None)
Field(name=None,type=None,default=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,default_factory=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),kw_only=<dataclasses._MISSING_TYPE object at 0x78ec801c1010>,_field_type=None)

Class B
type object 'B' has no attribute 'sentinel'
'B' object has no attribute 'sentinel'
```

Upon inspection of `B.__dataclass_fields__` the `sentinel` field does appear in `B`. 
Which is somewhat confusing behavior.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by ericvsmith** [comment]
It's not clear what you're trying to accomplish.

`__dataclass_fields__` is private. Use `dataclasses.fields()` and you'll see it's not a normal field. You've not initialized the class field to anything.

This is the normal way to initialize a ClassVar.
```pycon
>>> @dataclass
... class B:
...     sentinel: ClassVar = 3
```

**Comment by michael-123123** [comment]
Hi @ericvsmith.
Thanks for the quick reply.

I realize that.
Let me clarify that I wanted to have a class variable that **is** of type `Field`.

The point I was making with the bug report is that if you want a `ClassVar` of type `Field` -- 
then it is neither a class var nor an attribute of the instance.

This may be some kind of undefined/undocumented behavior.
I would expect this to just be a regular class variable of type Field (like in class `A` in my example)

**Comment by michael-123123** [comment]
Actually I am closing this bug -- this behavior is documented.
The workaround (in case anyone is interested) is:
```python
@dataclass
class B:
    x: ClassVar[Field] = field(default=field())
```

**Comment by ericvsmith** [comment]
Wouldn't this do the same thing?
```python
@dataclass
class B:
    x: ClassVar[Field] = field()
```
Although maybe this would be better:
```python
@dataclass
class B:
    x: ClassVar[Field] = field(default_factory=field)
```
