### ISSUE TITLE
Divide in large numbers not working well

### ISSUE THREAD

**Issue by AminBidad1** [python/cpython#125971]
# Bug report

### Bug description:

I Write a code with large numbers( 10**18<n ) and I have understand that python in large numbers can't divide well.
for example:
```python
n = 123140801928338636
print(n)  # 123140801928338636
print(n/2)  # 6.157040096416932e+16
print(int(n/2))  # 61570400964169320
from math import floor, ceil
print(floor(n/2))  # 61570400964169320
print(ceil(n/2))  # 61570400964169320
print(int(n/2)*2 == n)  # False
```
this bug can create security bugs in products.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

**Comment by graingert** [comment]
fyi you can use `x // y` for floored quotient of x and y:

```python
n = 123140801928338636
print(n)
print(n // 2)
```

**Comment by picnixz** [comment]
The division `/` always returns a float even if the result would be an integer. hence it's an expected result. As Thomas said, you need to use `//`.

Closing as a `non-CPython issue`.

**Comment by AminBidad1** [comment]
> fyi you can use `x // y` for floored quotient of x and y:
> 
> ```python
> >>> n = 123140801928338636
> ... print(n)
> ... print(n // 2)
> ... 
> 123140801928338636
> 61570400964169318
> >>> 
> ```

you're right. I forgotten.

**Comment by AminBidad1** [comment]
> The division `/` always returns a float even if the result would be an integer. hence it's an expected result (namely, you'll get numerical imprecision because of that and hence your assertion failure). As Thomas said, you need to use `//`.
> 
> Closing as a `non-CPython issue`.

Thanks.
