### ISSUE TITLE
Asyncio Queue maxsize parameter is not being used

### ISSUE THREAD

**Issue by V-H-R-Oliveira** [python/cpython#125949]
# Bug report

### Bug description:

Hello, in the Asyncio Queue class the `maxsize` argument is not being used, so it seems to always create an unbounded queue.

If it is a bug, the solution  is very simple: ` self._queue = collections.deque(maxsize)`

Current implementation:
https://github.com/python/cpython/blob/e68d4b08ff13a06a2c2877f63bf856e6bf3c2e77/Lib/asyncio/queues.py#L33C1-L61C42

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by zware** [comment]
Thanks for the report!

However, I don't believe we want to make any change here.  When a `deque` reaches `maxlen`, adding anything else to it *discards* items from the other end, which we never want from a `Queue`.  The queue manages its own size separately, and there's no significant advantage to limiting the size of a `deque` (in fact, a peek at the implementation of `deque` suggests that it might actually be more performant to leave it unbounded).

Please correct me if I've misunderstood the suggestion, but I'm going to go ahead and close the issue.
