### ISSUE TITLE
Embeddable distribution for 3.13 includes Tcl/Tk DLL files

### ISSUE THREAD

**Issue by lir-ht** [python/cpython#126074]
# Bug report

### Bug description:

I noticed that the size of the embeddable distribution for Windows increased by roughly 2 MB between 3.12 and 3.13 (in the 32-bit distribution when unpacked), despite the PEP 594 dead batteries removal. This turns out to be in part because 3.13, unlike earlier versions, includes the files `tcl86t.dll` and `tk86t.dll` which together take up around 2.6 MB.

Should these DLL files really be included in the embeddable distribution? Since the `_tkinter` module and the rest of Tkinter isn't included, it doesn't seem like these files are of any use.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-126143
* gh-126453

**Comment by rruuaanng** [comment]
Can this issue be closed? It seems to have been completed ;)

**Comment by zware** [comment]
Thanks for the report, @lir-ht!  This will be fixed in v3.13.1.
