### ISSUE TITLE
Ignore directories containing only `__pycache__` in `test_makefile_test_folders`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#126014]
# Feature or enhancement

### Proposal:

While working on some tests, sometimes when switching branches I have a leftover `__pycache__` directory in an otherwise empty test folder. This can happen for example when converting a test file into its own directory.

`test_makefile_test_folders` already ignores empty folders and `__pycache__` folders separately. I think it'd be nice if it also ignored folders which only contain `__pycache__`.

cc @sobolevn since you added this test originally :)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126066
* gh-126109
* gh-126110
* gh-140466
* gh-144268
* gh-144269

**Comment by picnixz** [comment]
Closing since completed and backported.

**Comment by stefanor** [comment]
There's a variant of this bug where a directory *containing* only a single `__pycache__` is not included. I've run into this while bisecting across large swathes of history, which leave empty directories around.
