### ISSUE TITLE
Bug: Reference leak in `_asyncio_Task___init___impl` in `_asynciomodule.c`

### ISSUE THREAD

**Issue by Nico-Posada** [python/cpython#126083]
# Bug report

### Bug description:

I discovered this while working on https://github.com/python/cpython/issues/126080. If the func is given a context that isn't `None`, instead of doing `Py_XSETREF` it'll just do a regular assignment meaning that whatever was there before wont have its reference count decreased.

https://github.com/python/cpython/blob/25441592db179e9f5e6c896d1a691459a23e3422/Modules/_asynciomodule.c#L2122-L2124

```python
import asyncio
import sys

# for convenience so I dont have to set up everything else for a Task obj
# and can just focus on the ref leak
class Break:
    def __str__(self):
        raise Exception("break")

async def coro():
    pass

task = asyncio.Task.__new__(asyncio.Task)
co = coro()

obj = object()
print("refcount before bug", sys.getrefcount(obj))

for _ in range(10000):
    try:
        task.__init__(co, context=obj, name=Break())
    except: pass

print("refcount after bug", sys.getrefcount(obj))
```

Output
```
refcount before bug 2
refcount after bug 10002
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

### Linked PRs
* gh-126103
* gh-126229
* gh-126230

**Comment by sobolevn** [comment]
Yes, `Py_XSETREF` seems like a good solution here. @Nico-Posada, please send a PR :)
