### ISSUE TITLE
Add PyLong_IsPositive/Zero/Negative() functions

### ISSUE THREAD

**Issue by skirpichev** [python/cpython#126061]
as alternative API to PyLong_GetSign().

It seems, C-API WG is positive on this, see https://github.com/capi-workgroup/decisions/issues/29.  This issue will track implementation.

### Linked PRs
* gh-126065
* gh-126788

**Comment by rruuaanng** [comment]
If possible, could you give it to me?

**Comment by skirpichev** [comment]
In principle, I've patch ready.  But please do!  Only set pr as draft until C-API WG issue is open.

**Comment by rruuaanng** [comment]
Oh thank you, Sergey!
