### ISSUE TITLE
`sys.audit(0)` aborts due to an assertion in debug build

### ISSUE THREAD

**Issue by devdanzin** [python/cpython#126018]
# Crash report

### What happened?

There is an assert in `sysmodule.c` that makes the interpreter abort when calling `sys.audit` with a non-string value in debug builds:
https://github.com/python/cpython/blob/f6cc7c8bd01d8468af70a65e550abef3854d0754/Python/sysmodule.c#L522

```python
Python 3.14.0a1+ (heads/main:c5b99f5c2c, Oct 26 2024, 12:35:53) [GCC 13.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.audit(9)
python: ./Python/sysmodule.c:522: sys_audit: Assertion `PyUnicode_Check(args[0])' failed.
Aborted (core dumped)
```

This assert seems completely unnecessary, as the code that runs the hooks (which only triggers if there is some hook registered) will raise an exception if the first argument to `sys.audit` isn't a string:

```python
Python 3.14.0a1+ (heads/remove_sysaudit_assert:ba8ac4d398, Oct 26 2024, 19:45:11) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.addaudithook(lambda *args: None)
>>> sys.audit(9)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    sys.audit(9)
    ~~~~~~~~~^^^
TypeError: expected str for argument 'event', not int
```

I'll submit a trivial PR removing this assert.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux, Windows

### Output from running 'python -VV' on the command line:

Python 3.14.0a1+ (heads/main:c5b99f5c2c, Oct 26 2024, 12:35:53) [GCC 13.2.0]

### Linked PRs
* gh-126020
* gh-126042

**Comment by picnixz** [comment]
I'm assuming that this affects all versions unless the assertion was added recently (I didn't actually check it before applying the labels)

**Comment by devdanzin** [comment]
> Ok, 3.12 is actually not affected:

Hmm. The assert was deliberately added in https://github.com/python/cpython/pull/108965. @vstinner, what do you think about the proposal to remove the eager assert for non-string argument to `sys.audit`?

**Comment by picnixz** [comment]
Closing since completed and backported. Thanks!
