### ISSUE TITLE
module_from_spec

### ISSUE THREAD

**Issue by mwriter** [python/cpython#126039]
# Bug report

### Bug description:

This may not be a bug, but it's a weirdness.
Why is there an automatic implicit re-registration of the builtins module in the latter case?
```python
import sys
import importlib.util

import email

name = "email"

spec = importlib.util.find_spec(name)

sys.modules[name] = "ha"
print(sys.modules[name]) # ha

importlib.util.module_from_spec(spec)
print(sys.modules[name]) # ha

import builtins

name = "builtins"

spec = importlib.util.find_spec(name)

sys.modules[name] = "ha"
print(sys.modules[name]) # ha

importlib.util.module_from_spec(spec)
print(sys.modules[name]) # <module 'builtins' (built-in)>
```

### CPython versions tested on:

3.12, 3.13

**Comment by ZeroIntensity** [comment]
`builtins` is needed by the interpreter for all sorts of things. It probably decides to do this instead of crashing, so I don't think there's anything that can be done here.

**Comment by mwriter** [comment]
> `builtins` is needed by the interpreter for all sorts of things. It probably decides to do this instead of crashing, so I don't think there's anything that can be done here.

This isn't true :)
I can do this
```python
import builtins

name = "builtins"

spec = importlib.util.find_spec(name)

sys.modules[name] = "ha"
print(sys.modules[name]) # ha

importlib.util.module_from_spec(spec)
print(sys.modules[name]) # ha
```
Perhaps I will present this part of my research soon. Although it was bullied on the main forum.

**Comment by ZeroIntensity** [comment]
Yes, because you don't overwrite `builtins` there. The interpreter intentionally keeps its own copy of `builtins`, it doesn't surprise me that it swaps it out if it needs to.

**Comment by ZeroIntensity** [comment]
In general, black magic with `sys.modules` won't be encouraged or fixed on the Python side. I suggest for both of your issues you use the private C API to manually mess with things, you have more power there.

**Comment by mwriter** [comment]
> The interpreter intentionally keeps its own copy of `builtins`

According to my research, all copies can be overwritten.

> In general, black magic with `sys.modules` won't be encouraged or fixed on the Python side

There are no problems for me here. At the python level, I can change everything myself.
But there is a clear discrepancy in the logic of the code's behavior.

> I suggest for both of your issues you use the private C API to manually mess with things

For example?

**Comment by ZeroIntensity** [comment]
> According to my research, all copies can be overwritten.

Sure, but that doesn't mean we have to support it :)

> For example?

Truly overwriting the `sys.modules`:

```c
#define Py_BUILD_CORE
#include "pycore_interp.h"

static PyObject *
overwrite_sys_modules(PyObject *self, PyObject *obj)
{
    PyInterpreterState *interp = PyInterpreterState_Get();
    Py_SETREF(interp->imports.modules, Py_NewRef(obj));
    Py_RETURN_NONE;
}
```

**Comment by mwriter** [comment]
> Sure, but that doesn't mean we have to support it

This is understandable. It was only in the context of the behavior inconsistency in the original example here. But for me it's not a problem at all. I just decided to write :)

> Truly overwriting the

Thanks for the example.
