### ISSUE TITLE
Add `__class_getitem__` support to `memoryview`

### ISSUE THREAD

**Issue by brianschubert** [python/cpython#126012]
# Feature or enhancement

### Proposal:

`memoryview` was made generic in typeshed in https://github.com/python/typeshed/pull/12247. Mypy recently received a report (https://github.com/python/mypy/issues/18053) due to it not being subscriptable at runtime:
```python
>>> memoryview[int]
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    memoryview[int]
    ~~~~~~~~~~^^^^^
TypeError: type 'memoryview' is not subscriptable
```
It seems that `memoryview` should be made subscriptable at runtime, like other standard library classes that are generic in typeshed.

Happy to make a PR if there's agreement that this should be added.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126013

**Comment by picnixz** [comment]
Closing since completed. Thanks for the contribution.
