### ISSUE TITLE
Segmentation fault after deleting __fields__ attribute from ast.AST

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126105]
# Crash report

### What happened?

```bash
>>> import ast
>>> dir(ast.AST)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_attributes', '_fields']
>>> del ast.AST._fields
>>> dir(ast.AST)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__match_args__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '_attributes']
>>> t = ast.AST(arg1=123)
Segmentation fault
```

This happens because *fields* variable is [null-pointer here](../tree/3.11/Python/Python-ast.c#L863), moreover it was previously checked for null [here](../tree/3.11/Python/Python-ast.c#L831).

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.11.9 (main, Oct 28 2024, 23:26:29) [GCC 13.2.0]

### Linked PRs
* gh-126115
* gh-126130
* gh-126132

**Comment by picnixz** [comment]
cc @Eclips4 @JelleZijlstra (Would adding `Py_TPFLAGS_IMMUTABLETYPE` work or is it too restrictive?)

**Comment by sobolevn** [comment]
I can confirm, that this still happens on `main`:

```
Python 3.14.0a1+ (heads/main:19e93e2e269, Oct 28 2024, 11:42:01) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> del ast.AST._fields
>>> t = ast.AST(arg1=123)
[1]    85885 segmentation fault  ./python.exe
                          
```

> Py_TPFLAGS_IMMUTABLETYPE

I think that this is an overkill and it change the semantics here. We can just modify the code and check for `NULL` explicitly. 

See https://github.com/python/cpython/blob/9b14083497f50213f908c1359eeaf47c97161347/Parser/asdl_c.py#L877

**Comment by picnixz** [comment]
Oh yes, we only need to modify:

```
    if (PyObject_GetOptionalAttr((PyObject*)Py_TYPE(self), state->_fields, &fields) < 0) {
        goto cleanup;
    }
```

with a NULL check beforehand I think. What do you think?

**Comment by Eclips4** [comment]
> cc @Eclips4 @JelleZijlstra (Would adding `Py_TPFLAGS_IMMUTABLETYPE` work or is it too restrictive?)

If you are talking about making nodes immutable, we can't do that because a lot of code relies on the fact that nodes are mutable. So it would be a huge breaking change.

**Comment by Eclips4** [comment]
Thank you Valery for the report and Nikita for the fix.
