### ISSUE TITLE
Undeprecate getopt and optparse

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#126180]
See discussion at https://discuss.python.org/t/getopt-and-optparse-vs-argparse/69618. Seems that all support this.

`argparse` has many issues, some are fundamental and cannot be easily worked around. Its implements behavior different from the behavior of other Unix/Linux programs in subtle ways. It is still not mature to be the preferable Python module for CLI.

`getopt` is a de-facto cross-language standard. Many programmers that came from other programming languges are already familiar with it. It is very simple, so even if there are other CLI modules, it should be left in the stdlib.

`optparse` provides an object-oriented interface. Even if it has less features than `argparse`, it is more stable and has less bugs. It should be the preferable Python module for CLI.

### Linked PRs
* gh-126186
* gh-126227
* gh-128191

**Comment by ncoghlan** [comment]
I missed that @serhiy-storchaka had already created a PR for this, so https://github.com/python/cpython/pull/126227 is an alternative take on the same change.
