### ISSUE TITLE
Potential null pointer dereference in `PySSLSession_richcompare`

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126106]
# Bug report

### Bug description:

Pointer *left* is dereferenced [here](../blob//3.11/Modules/_ssl.c#L5027), but null-pointer check [is done later](../blob//3.11/Modules/_ssl.c#L5029). Correct code should look like this:

```c
    int result;
    if (left == NULL || right == NULL) {
        PyErr_BadInternalCall();
        return NULL;
    }

    PyTypeObject *sesstype = ((PySSLSession*)left)->ctx->state->PySSLSession_Type;
```

### CPython versions tested on:

3.11

### Linked PRs
* gh-126111
* gh-126116
* gh-126117

**Comment by picnixz** [comment]
Thanks for spotting this. This still happens on main. Feel free to open a PR (I can do it as well if you want).
