### ISSUE TITLE
Upgrade bundled pip to 24.3

### ISSUE THREAD

**Issue by ThomasWaldmann** [python/cpython#126188]
# Feature or enhancement

### Proposal:

`ensurepip`'s bundled version of pip gets updated to the current latest 24.3.

### Background:

The pip 24.2 wheel bundled into current python releases is broken and does not work at all on old macOS releases (like e.g. macOS Sierra / High Sierra).

This issue was fixed and released as pip 24.3, so this ticket is intended as a reminder to not forget to update the bundled pip in CPython to at least that version.

There is still the broken pip 24.2 there:

- https://github.com/python/cpython/tree/3.12/Lib/ensurepip/_bundled
- https://github.com/python/cpython/tree/3.13/Lib/ensurepip/_bundled
- https://github.com/python/cpython/tree/main/Lib/ensurepip/_bundled
 
Please replace **all** pip 24.2 by >=24.3.

### CPython versions tested on:

3.12, 3.13, CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-126805
* gh-126806
* gh-126813

**Comment by ThomasWaldmann** [comment]
@pradyunsg Please check. ^^^

**Comment by sbidoul** [comment]
Yep, no worries, I keep an eye on the timeline. Currently waiting on a `packaging` release to address https://github.com/pypa/pip/issues/13053, which should also happen soon, as @pradyunsg is on it.

**Comment by sbidoul** [comment]
This is now done.

**Comment by hugovk** [comment]
Thank you @sbidoul!
