### ISSUE TITLE
Possible null pointer dereference of freevars in _PyCompile_LookupArg

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126238]
# Bug report

### Bug description:

*freevars* is [checked for null](https://github.com/python/cpython/blob/d467d9246cbe0ce5dc149c4c74223bb8374ece73/Python/compile.c#L893C1-L895C10), but later [possible dereference happens](https://github.com/python/cpython/blob/d467d9246cbe0ce5dc149c4c74223bb8374ece73/Python/compile.c#L904). Maybe replacing Py_DECREF  by Py_XDECREF should do the trick.

### CPython versions tested on:

3.11

### Linked PRs
* gh-126239
* gh-126474
* gh-126475

**Comment by federicovalenso** [comment]
FYI @sobolevn

**Comment by ZeroIntensity** [comment]
Yeah, that looks incorrect. Simply changing it to `Py_XDECREF` should work. PR welcome :)
