### ISSUE TITLE
Revisit `getopt` and `optparse` soft deprecations

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#126225]
Duplicate of #126180 

----

(Based on @serhiy-storchaka's Discourse thread at https://discuss.python.org/t/getopt-and-optparse-vs-argparse/69618 ).

I'm going to draft a PR for this, and wanted an issue number for the NEWS entry. 

The PR will be initially marked as DO-NOT-MERGE, as this feels like a change that needs an explicit +1 from the next SC (since we'd be reversing a deprecation that come from a previously approved PEP: https://peps.python.org/pep-0389/#deprecation-of-optparse)

Interestingly, the deprecation notice in `getopt` goes *against* the contents of PEP 389 ("The getopt module will not be deprecated. However, its documentation will be updated to point to argparse in a couple of places.")

### Linked PRs
* gh-126227

**Comment by ncoghlan** [comment]
The `getopt` deprecation was added in #106535 for Python 3.13 (as I discovered when looking at What's New while drafting a PR)

**Comment by zware** [comment]
See also gh-126180/GH-126186.

**Comment by ncoghlan** [comment]
D'oh! Those hadn't been mentioned in the Discourse thread, and I forgot to check GitHub itself.
