### ISSUE TITLE
Convert one-element list to tuple in Python.

### ISSUE THREAD

**Issue by kmrul** [python/cpython#126234]
# Bug report

### Bug description:

Input
```python
tuple([1])
```
Expected output:
```python 
(1)
```
However, I got this:
```python
(1,)
```

But for multiple element list convert to tuple is working fine.

### CPython versions tested on:

3.9, 3.10, 3.11

### Operating systems tested on:

Linux, macOS, Windows

**Comment by skirpichev** [comment]
> Expected output:

Sorry, but why you expect this output?!  One-element tuples covered in many places of CPython docs, including the tutorial:
https://docs.python.org/3/tutorial/datastructures.html#tuples-and-sequences

**Comment by terryjreedy** [comment]
Except for an empty tuple (`()`), commas, not parentheses, define a tuple, with 1 element tuple requiring a trailing comma.
