### ISSUE TITLE
`time.rst` uses `the same than`, which is grammatically incorrect

### ISSUE THREAD

**Issue by alpaylan** [python/cpython#126256]
# Documentation

The [`time` documentation](https://docs.python.org/3.13/library/time.html#time.monotonic) uses `the same clock than time.monotonic` instead of `the same clock as time.monotonic`, which is [grammatically false](https://dictionary.cambridge.org/grammar/british-grammar/same-similar-identical) as far as I can tell.

### Linked PRs
* gh-126257
* gh-126258

**Comment by sobolevn** [comment]
PR is welcome!

**Comment by alpaylan** [comment]
I accidentally opened the PR in my fork first 🤕 Opened it now.

**Comment by sobolevn** [comment]
Thanks! I set backport PRs for automerge, going to close this issue.
