### ISSUE TITLE
Possible null pointer dereference of variable args  in _PyPegen_collect_call_seqs

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126240]
# Crash report

### What happened?

*args* [can be NULL as a result of](https://github.com/python/cpython/blob/d467d9246cbe0ce5dc149c4c74223bb8374ece73/Parser/action_helpers.c#L1130) `_Py_asdl_expr_seq_new`, and then [dereference happens](https://github.com/python/cpython/blob/d467d9246cbe0ce5dc149c4c74223bb8374ece73/Parser/action_helpers.c#L1134C9-L1134C51).

Return value of _Py_asdl_expr_seq_new` is usually checked, for example [here](https://github.com/python/cpython/blob/d467d9246cbe0ce5dc149c4c74223bb8374ece73/Parser/action_helpers.c#L229C1-L232C6) and in other places.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-126241
* gh-126243
* gh-126245

**Comment by picnixz** [comment]
Thanks for this one! I'll hunt other missing NULL check in `PyPegen` at the same time.
