### ISSUE TITLE
`make regen-all` doesn't pass `-f` to argument clinic

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#126206]
# Bug report

### Bug description:

Output:

```none
python3.13 ./Tools/clinic/clinic.py --make --exclude Lib/test/clinic.test.c --srcdir .
Error in file 'Modules/posixmodule.c' on line 13087:
Checksum mismatch! Expected '9756767bdbdabe94', computed '1da32369b7d9fd4b'. Suggested fix: remove all generated code including the end marker, or use the '-f' option.
make: *** [clinic] Error 1
```

This makes it harder to fix merge conflicts, see: https://discuss.python.org/t/reducing-merge-conflicts-in-generated-code/68537/8

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

macOS

### Linked PRs
* gh-126244

**Comment by erlend-aasland** [comment]
If you get conflicts in generated code you should examine the conflict. If there are real issues, fix them; if not, regenerate clinic code using `-f`, as suggested by the error message. See also the devguide and the Argument Clinic HOWTO.

**Comment by nineteendo** [comment]
Sure, if the generated code is in `.c` files should probably be examined as it might contain incompatible changes. But why can't it overwrite `.c.h` files automatically? That code is fully generated (at least for `Modules/posixmodule.c`).

I know that I can run `Tools/clinic/clinic.py -f Modules/posixmodule.c`, but this just a waste of time.

**Comment by erlend-aasland** [comment]
There is no discussion of using `-f` in the original issue nor in the commit message that added the `clinic` target. I'm not sure _why_ we don't forcefully recreate generated code, but I would be fine with such a change. The `clinic-tests` target, for example, uses the `-f` option when running `clinic.py`.

**Comment by erlend-aasland** [comment]
Adding `-f` would not conflict with the check-generated-files CI check, so we should be fine CI wise.

**Comment by erlend-aasland** [comment]
Thanks for the suggestion; `make clinic` (and any other target that implicitly depends on `clinic`) now forcefully regenerates clinic code.
