### ISSUE TITLE
Python 3.13

### ISSUE THREAD

**Issue by TacticsPro** [python/cpython#126228]
# Bug report

### Bug description:

There is a bug while install pip install PyQt5 it fails to build Pyqt5-sip and ask to install Microsoft vc++ 14.0 which is not needed in python older version 3.12

Machine: Windows 10 and 11
success tried : on  Python 3.12 and 3.11
failed tried : on Python 3.13

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
Sorry, but you should report that issue to an appropriate project.

See https://www.riverbankcomputing.com/software/pyqt/

**Comment by Rakicc** [comment]
But the issue is related to new release of Python 3.13  only not for older version, hence there is no bug in Pyqt5.

**Comment by Rakicc** [comment]
> Sorry, but you should report that issue to an appropriate project.
> 
> See https://www.riverbankcomputing.com/software/pyqt/

But the issue is related to new release of Python 3.13 only not for older version, hence there is no bug in Pyqt5.

**Comment by skirpichev** [comment]
To me it's clear that issue is related to PyQt5 and/or build dependencies of that package.

**Comment by Rakicc** [comment]
> To me it's clear that issue is related to PyQt5 and/or build dependencies of that package.

Sorry to say.. 
I have tested with Python 3.12  and 3.11 it install same version of PyQt5 with latest pip..
but not in python 3.13

**Comment by Rakicc** [comment]
I have tested with Python 3.12 and 3.11 it install same version of PyQt5 with latest pip..
but not in python 3.13

**Comment by adang1345** [comment]
The report should probably go to https://github.com/Python-SIP/sip, which has not yet released wheels for Python 3.13.

**Comment by skirpichev** [comment]
pyqt has wheels also only for Py3.8.

**Comment by Rakicc** [comment]
yes The issue is related to sip pyton  3.13 not able to install sip too. hence PyQt5 is getting error at building Pyqt5-sip
