### ISSUE TITLE
Use `Py_VERSION` to represent different version

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#126232]
# Feature or enhancement

### Proposal:

Actually, there's been an issue that has been bothering me, why not use macros to represent Python version? Using raw hexadecimal numbers seems a bit odd, even though it doesn't affect functionality. I think it might be beneficial to add a macro similar to `KERNEL_VERSION` to represent a Python version. This would make the code more readable when defining different versions of the API.
```C
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= 0x03070000
```
replace with
```C
#if !defined(Py_LIMITED_API) || Py_LIMITED_API+0 >= Py_VERSION(3, 7)
```
So, it's usage is obvious. It's original version can be used
```
_Py_VERSION(3, 7, 2)
_Py_VERSION(3, 8, 1)
...
```

### Has this already been discussed elsewhere?

No response given

**Comment by picnixz** [comment]
There has been an opened discussion on a similar functionality: https://discuss.python.org/t/adding-py-pack-version/58887. I'd advise continuing the discussion out there instead (and close this issue for now).

cc @vstinner @encukou

**Comment by hugovk** [comment]
And there's a discussion specifically about this one at https://discuss.python.org/t/can-we-make-the-api-version-more-readable/69767.

Agreed to close for now, we can re-open later.
