### ISSUE TITLE
Inconsistent result when using StrEnum in f-string

### ISSUE THREAD

**Issue by cappuddono** [python/cpython#126299]
# Bug report

### Bug description:

I define a subclass of StrEnum, and use it in a f-string:

```python
class FruitEnum(StrEnum):
    APPLE = 'apple'

print(f'Example1: {FruitEnum.APPLE}')
# Example1: apple
print(f'Example2: {FruitEnum.APPLE=}')
# Example2: FruitEnum.APPLE=<FruitEnum.APPLE: 'apple'>
```

The behaviour of printing StrEnum members in f-strings is different. This seems not intuitive. Is this a bug?

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
Docs [says](https://docs.python.org/3.13/reference/lexical_analysis.html#formatted-string-literals): When the equal sign '=' is provided, the output will have the expression text, the '=' and the evaluated value ... By default, the '=' causes the [repr()](https://docs.python.org/3.13/library/functions.html#repr) of the expression to be provided, unless there is a format specified.

So, you get repr output on rhs in the second case.  That can be illustrated on simpler example:
```pycon
>>> s = "xxx"
>>> print(f'{s}')
xxx
>>> print(f'{s=}')
s='xxx'
```
