### ISSUE TITLE
Support options with optional arguments

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#126374]
# Feature or enhancement

GNU `getopt` supports options with optional arguments. For example GNU `grep` can be used with option `--color=auto` and with just `--color`. Unix `getopt` does not need it, because it stops after encountering first nonoption argument, but GNU `getopt` needs it to support options intermixed with positional arguments. `getopt.gnu_getopt()` needs it for the same reason.

Neither `optparse` nor `argparse` directly support such kind of optional arguments. It can be supported in `optparse` with custom callback, but support of optional arguments in `argparse` is non-standard. In future I'm planning to add support of such kind of optional arguments in `argparse`, and maybe in `optparse`.

### Linked PRs
* gh-126375

**Comment by serhiy-storchaka** [comment]
The Python implementation of `getopt` should be as powerful and flexible as the C implementation. This will help to port programs from other programming languages to Python. This feature was in the TODO list since beginning.

This feature will also be added in `argparse`, I just haven't decided on one of the three interface options yet (special `nargs` value, new `add_argument()` option, or the part of a new `argparse` mode). I will decide after implementing that new mode.

I thing that options with optional argument can be supported in `optparse` by using a custom callback. I am not sure whether a more direct support is needed.

This module will be undeprecated (see #126180). It was not changed (except mass stdlib changes) in the last 15 years, so it is difficult to find an interested person for review. I asked for help and @gpshead reviewed #126393 which was created on the top of #126375. His comment did not question the feasibility of these changes, only the style of the tests code. Which I took as acceptance in principle.

**Comment by mhsmith** [comment]
> Neither `optparse` nor `argparse` directly support such kind of optional arguments.

Isn't this supported by argparse's [`nargs='?'`](https://docs.python.org/3/library/argparse.html#nargs)?

**Comment by serhiy-storchaka** [comment]
No, argparse's `nargs='?'` has different semantic. In argparse, `--color=auto` and `--color auto` are the same. The value can only be omitted if the option is at the end of the command line or followed by other option or `--`, e.g. `--color --recursive auto` or `--color -- auto`.
