### ISSUE TITLE
syntaxwarning invalid escape sequence

### ISSUE THREAD

**Issue by sec13b** [python/cpython#126356]
How i fix " syntaxwarning invalid escape sequence"

After i made update i get this error  DeprecationWarning (< 3.12) or a SyntaxWarning (3.12+)

**Comment by sobolevn** [comment]
Can you please provide what code raises this warning?

**Comment by tomasr8** [comment]
It's hard to tell without seeing the code but you probably have a string which contains an unrecognized escape sequence: https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences

**Comment by tomasr8** [comment]
> for all Impacket scripts.

Could you please provide a concrete code sample that we can run that causes this warning?

**Comment by terryjreedy** [comment]
Please ask questions about using python on forums such as https://discuss.python.org/c/help/7.
