### ISSUE TITLE
Simplify stdlib code by using `itertools.batched()`

### ISSUE THREAD

**Issue by lgeiger** [python/cpython#126317]
#98364 introduced `itertools.batched()` but since it's pretty new it's still rarely used inside the standard library.

[`pickle.py` includes a custom version](https://github.com/python/cpython/blob/f0c6fccd08904787a39269367f09f263d496114c/Lib/pickle.py#L1038-L1040) multiple times which all could be replaced by `itertools.batched()` for improved readability.
This probably has a negligible performance impact (at the very least it won't be slower) but should make the code easier to understand.

Let me know if you're interested in a contribution for this or whether you'd rather not have the extra churn for a minor change like this.

### Linked PRs
* gh-126323

**Comment by picnixz** [comment]
I'm not sure we want to refactor `pickle.py`, especially not the pure Python implementation.

**Comment by dongwooklee96** [comment]
If you don't mind me taking over, I'll work on it.

**Comment by serhiy-storchaka** [comment]
There is no great need in such change, but it makes the code slightly smaller, so I have no objections. Please show the results of microbenchmarks for pickling large list, dict and set. Even a small speedup would be an additional argument for this change. A slowdown would be a sign that there is something wrong with itertools.batched().

**Comment by dongwooklee96** [comment]
`bench.py`
```
import pickle
import pyperf

large_list = list(range(10**6))  # 1,000,000 list
large_dict = {str(i): i for i in range(10**6)}  # 1,000,000 dict
large_set = set(range(10**6))  # 1,000,000 set

def pickle_save(data, filename):
    with open(filename, "wb") as f:
        pickle.dump(data, f)

def pickle_load(filename):
    with open(filename, "rb") as f:
        return pickle.load(f)

def run_benchmarks():
    runner = pyperf.Runner()

    # Pickle dump test
    runner.bench_func("pickle_save_large_list", pickle_save, large_list, "large_list.pkl")
    runner.bench_func("pickle_save_large_dict", pickle_save, large_dict, "large_dict.pkl")
    runner.bench_func("pickle_save_large_set", pickle_save, large_set, "large_set.pkl")

    # Pickle load test
    runner.bench_func("pickle_load_large_list", pickle_load, "large_list.pkl")
    runner.bench_func("pickle_load_large_dict", pickle_load, "large_dict.pkl")
    runner.bench_func("pickle_load_large_set", pickle_load, "large_set.pkl")

if __name__ == "__main__":
    run_benchmarks()
```

```
+------------------------+---------+-----------------------+
| Benchmark              | base    | patch                 |
+========================+=========+=======================+
| pickle_save_large_list | 14.1 ms | 15.0 ms: 1.06x slower |
+------------------------+---------+-----------------------+
| pickle_save_large_set  | 16.6 ms | 15.7 ms: 1.06x faster |
+------------------------+---------+-----------------------+
| pickle_load_large_list | 71.7 ms | 64.8 ms: 1.11x faster |
+------------------------+---------+-----------------------+
| pickle_load_large_dict | 307 ms  | 290 ms: 1.06x faster  |
+------------------------+---------+-----------------------+
| pickle_load_large_set  | 82.7 ms | 77.6 ms: 1.07x faster |
+------------------------+---------+-----------------------+
| Geometric mean         | (ref)   | 1.04x faster          |
+------------------------+---------+-----------------------+
```

The result of running the benchmark using pyperf.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @dongwooklee96.
