### ISSUE TITLE
strftime %p (AM/PM) not working with French locale

### ISSUE THREAD

**Issue by ChronoBoot** [python/cpython#126383]
# Bug report

### Bug description:

Description:
When using French locale (fr_FR.UTF-8), strftime's %p format (AM/PM) doesn't work as documented.

Steps to reproduce:
```python
from datetime import datetime
import locale

# Set French locale
locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')

now = datetime.now()
print("AM/PM only:", now.strftime('%p'))  # Returns empty string
```

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

**Comment by simple-is-great** [comment]
Can I take a look at this one?

**Comment by ronaldoussoren** [comment]
This is a bug in the locale definitions macOS, on my macOS 15.1 system. As such this is not something we can fix on our end.

% env LC_TIME='fr_FR.UTF-8' date  +"%H:%M %p"
08:54 

% date  +"%H:%M %p"
08:54 AM

The latter is with the default system locale, which is an English one for me.

**Comment by serhiy-storchaka** [comment]
This is not a bug. Some cultures just have no equivalent of AM/PM, this is mostly an English specific. You should either use the 24-hour format for machine-readable data or use the 12-hour format in less formal context -- "2nd hour of the night", "6 hours of the morning", etc.

**Comment by tomasr8** [comment]
> Some cultures just have no equivalent of AM/PM, this is mostly an English specific.

True, but at least according to the latest version of [CLDR](https://cldr.unicode.org/downloads/cldr-46) which is used e.g. by babel, `fr_FR` uses AM/PM as well. But yeah, this is not a python bug.

**Comment by serhiy-storchaka** [comment]
I do not see it as defined for `fr`: https://unicode.org/cldr/charts/46/by_type/date_&_time.gregorian.html#5e8542fc1cce0474

**Comment by tomasr8** [comment]
> I do not see it as defined for `fr`: https://unicode.org/cldr/charts/46/by_type/date_&_time.gregorian.html#5e8542fc1cce0474

Strange, I was looking at day periods in the JSON data which contain this:
```json
"dayPeriods": {
  "format": {
    "abbreviated": {
      "midnight": "minuit",
      "am": "AM",
      "noon": "midi",
      "pm": "PM",
      "morning1": "matin",
      "afternoon1": "après-midi",
      "evening1": "soir",
      "night1": "matin"
    }
  }
}
```
Anyway, not really relevant to this issue I suppose..

**Comment by ronaldoussoren** [comment]
As discussed this is not an issue in Python.
