### ISSUE TITLE
`url` variable in `urllib._urlsplit` should be `path`

### ISSUE THREAD

**Issue by KentaroJay** [python/cpython#126376]
Hello Python team! I hope you're doing well. 

Please take a look at the code [here](https://github.com/python/cpython/blob/9441993f272f42e4a97d90616ec629a11c06aa3a/Lib/urllib/parse.py#L515C5-L515C50):
https://github.com/python/cpython/blob/9441993f272f42e4a97d90616ec629a11c06aa3a/Lib/urllib/parse.py#L515

The function `_urlsplit` is to return a tuple containing scheme, netloc, **path**, query, and fragment. However variable that corresponds to **path** is named `url`.

I think this is some kind of typo, I am eager to refactor this if that's the case.

Likewise, there are several lines with the same naming. I'll fix them too.

**Comment by rruuaanng** [comment]
Is it return the right value? I'm referring to URL :)
(Maybe the name isn't that important.)

**Comment by serhiy-storchaka** [comment]
This is a local variable and its name is irrelevant. Its name just an artifact of the early implementation.

We usually reject pure cosmetic changes.
