### ISSUE TITLE
Module audioop Not Found

### ISSUE THREAD

**Issue by Carlimero12** [python/cpython#126395]
# Bug report

### Bug description:

In the newest version of Python, the module audioop is not in the main Library which causes Modules like discord.py to crash.
Luckly there's an manual fix to it by installin it manually with 'pip install audioop-lts'
Please include it back beacause the installing manually is annoyinng

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows
```[tasklist]
### Tasks
```

**Comment by erlend-aasland** [comment]
`audioop` was removed as part of the PEP-594 cleanup. It's removal has been promoted since 3.11.
