### ISSUE TITLE
Register multiprocessing proxy types to an appropriate collections.abc class

### ISSUE THREAD

**Issue by tungol** [python/cpython#126417]
# Feature or enhancement

### Proposal:

For consistency with the types that they proxy, I believe that `multiprocessing.managers.ListProxy` should be registered to `collections.abc.MutableSequence` and `multiprocessing.managers.DictProxy` should be registered to `collections.abc.MutableMapping`. This could be done by registering either those types themselves or by registering their base classes, `BaseListProxy` and `_BaseDictProxy`.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

I discovered that these weren't registered to their ABCs while working on typeshed, so a little previous discussion occurred in issues in that repo:

https://github.com/python/typeshed/pull/12893

https://github.com/python/typeshed/pull/12892

### Linked PRs
* gh-126419
* gh-126435
* gh-126436
* gh-126454
* gh-126674
* gh-126675

**Comment by AlexWaygood** [comment]
Thanks @tungol!

**Comment by gpshead** [comment]
FYI - The backports of the validation test don't work on 3.13 or earlier because ListProxy in those versions does not have the methods added to 3.14 by https://github.com/python/cpython/pull/103133.

I'll close those backports.

**Comment by AlexWaygood** [comment]
The backports of the original PR are being reverted in:
- https://github.com/python/cpython/pull/126734
- https://github.com/python/cpython/pull/126735

(We're not reverting it for 3.14+, it's a good change! But there were concerns raised in https://github.com/python/cpython/issues/126451 over whether it was a good idea to backport this kind of change, and I think those concerns were reasonable.)
