### ISSUE TITLE
Windows py Launcher Defaults to Python 3.13t

### ISSUE THREAD

**Issue by zetaloop** [python/cpython#126467]
# Bug report

### Bug description:

When invoking the `py` launcher on Windows without specifying a version, it defaults to the experimental free-threading build of Python 3.13 (`python3.13t`) instead of the standard release. This behavior is unexpected, as users typically expect the launcher to default to the standard stable version.

**Steps to Reproduce:**

1. Install Python 3.13 with experimental free-threaded binaries.
2. Run the command `py`.
3. Observe the Python version that is launched.

**Observed Output:**

```
Python 3.13.0 experimental free-threading build (tags/v3.13.0:60403a5, Oct 7 2024, 09:53:29) [MSC v.1941 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

When listing available Python versions using `py --list`, the output is:

```
 -V:3.13t *       Python 3.13 (64-bit, freethreaded)
 -V:3.13          Python 3.13 (64-bit)
 -V:3.12          Python 3.12 (64-bit)
 -V:3.11          Python 3.11 (64-bit)
```

This issue may cause unintended use of an experimental Python build, leading to unexpected behavior in scripts and applications.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by ZeroIntensity** [comment]
cc @zooba

**Comment by zetaloop** [comment]
Should the `py` launcher prioritize non-suffixed versions over suffixed ones (e.g., defaulting to `3.13` rather than `3.13t`)?

**Comment by zooba** [comment]
No, the `py` launcher uses its existing rules to sort tags. There's no version logic in there.

If you don't want it to default to the default tag, you can [customize your default](https://docs.python.org/3.13/using/windows.html#customizing-default-python-versions) or choose not to install the experimental build.
