### ISSUE TITLE
register contextvars.Context to collections.abc.Mapping

### ISSUE THREAD

**Issue by tungol** [python/cpython#126451]
# Feature or enhancement

### Proposal:

`contextvars.Context` is documented as implementing the collections.abc.Mapping interface. I believe we should register it to the abc, so an `isinstance` check can work.

This is similar to https://github.com/python/cpython/issues/126417 .

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

A small amount of prior discussion occurred in an issue for typeshed: https://github.com/python/typeshed/pull/12873

### Linked PRs
* gh-126452
* gh-126518
* gh-126519
* gh-126734
* gh-126735

**Comment by JelleZijlstra** [comment]
Could you list out all the methods on Mapping to confirm it really conforms with the interface? I'd like to prevent another case similar to #125420.

**Comment by tungol** [comment]
Sure.

Mapping methods are: `__getitem__`,` __iter__`, `__len__`, `__contains__`, `keys`, `items`, `values`, `get`, `__eq__`, and `__ne__`. All are present on Context:

```
>>> from contextvars import Context
>>> Context.__getitem__
<slot wrapper '__getitem__' of '_contextvars.Context' objects>
>>> Context.__iter__
<slot wrapper '__iter__' of '_contextvars.Context' objects>
>>> Context.__len__
<slot wrapper '__len__' of '_contextvars.Context' objects>
>>> Context.__contains__
<slot wrapper '__contains__' of '_contextvars.Context' objects>
>>> Context.keys
<method 'keys' of '_contextvars.Context' objects>
>>> Context.items
<method 'items' of '_contextvars.Context' objects>
>>> Context.values
<method 'values' of '_contextvars.Context' objects>
>>> Context.get
<method 'get' of '_contextvars.Context' objects>
>>> Context.__eq__
<slot wrapper '__eq__' of '_contextvars.Context' objects>
>>> Context.__ne__
<slot wrapper '__ne__' of '_contextvars.Context' objects>
```

**Comment by hauntsaninja** [comment]
I was surprised that we backported this

**Comment by sobolevn** [comment]
I was too :) 
But, we backported https://github.com/python/cpython/pull/126419 
So, I decided to be consistent. If you think that these backports should be reverted - then I have no objections :)

**Comment by JelleZijlstra** [comment]
The risky aspect to me is that `isinstance(..., Mapping)` will start behaving differently in a patch release. That may have unexpected effects for some users.

**Comment by tungol** [comment]
As the person who kicked this off: I have no opinion about the backports.

**Comment by AlexWaygood** [comment]
The failing tests in https://github.com/python/cpython/pull/126674 and https://github.com/python/cpython/pull/126675 seem to validate folks' concerns about the backports of these PRs. I'll open a revert PR for these tomorrow.

**Comment by AlexWaygood** [comment]
Thanks everybody for voicing your concerns! Appreciate it.

**Comment by AlexWaygood** [comment]
Backports are being reverted in:
- https://github.com/python/cpython/pull/126734
- https://github.com/python/cpython/pull/126735
