### ISSUE TITLE
move `Callable` and other types that don't belong in `collections.abc` to another module

### ISSUE THREAD

**Issue by DetachHead** [python/cpython#126470]
# Feature or enhancement

### Proposal:

types like `Callable` and `Awaitable` are completely unrelated to "collections", therefore `collections.abc` is clearly the wrong place for them, so the fact that `typing.Callable` and `typing.Awaitable` are deprecated in favor of these aliases is very confusing.

imo they should either be moved to a different module, or the versions in `typing` should be un-deprecated until a more suitable location for them is decided

### Has this already been discussed elsewhere?

No response given

**Comment by KotlinIsland** [comment]
erm, excuse me? don't you know that you are supposed to create a thread on Discus if you want to change something?????

**Comment by KotlinIsland** [comment]
+ `Hashable`

**Comment by rruuaanng** [comment]
+1

**Comment by Zheaoli** [comment]
+1

**Comment by Viicos** [comment]
Duplicate: https://github.com/python/cpython/issues/69823

**Comment by DetachHead** [comment]
> +1, would you like to submit a PR?

sure. what module should i put them in? or should i just un-deprecate them for now so a decision can be made in the future regarding where they should go?

> Duplicate: #69823

that issue is quite old and seems to have been closed without a proper solution, so if we close this issue as a duplicate i think that one should be re-opened

**Comment by DetachHead** [comment]
https://discuss.python.org/t/move-callable-and-other-types-that-dont-belong-in-collections-abc-to-another-module/70407
