### ISSUE TITLE
Programmatically sending indented code to 3.13 REPL causes indentation error

### ISSUE THREAD

**Issue by anthonykim1** [python/cpython#126449]
# Bug report

## Bug Report 

------------------------------------------------

### Bug Description

Hello, I am working on improving REPL and Terminal experience for people using VS Code Python, and we have been experiencing the indentation issue similar to one you would see in https://github.com/python/cpython/issues/124096.

I do realize there are indentation error issue mentioned such as one above, but I wasn't sure if it is rooted from same problem since the one in #124096 is Windows, and I am seeing it on MacOS ARM (tested on zsh, xterm.js since we are talking about terminal in VS Code). 

From what I've seen, the indentation gets messed up when we programmatically send a indented string into the 3.13 REPL launched from the VS Code Terminal. If I were to send the exact same Python code to 3.13 and to non-3.13(such as 3.9) REPL programmatically, it will lead to two different result:
- One from Python3.9 (or non-3.13) will be fine, but code sent to 3.13 REPL will suffer from additional indentation as you see below: 

<img width="1101" alt="Screenshot 2024-11-05 at 8 00 12 AM" src="https://github.com/user-attachments/assets/6ae06037-dd9f-4b18-944e-dffb5c123951">

What I found surprising during my investigation is that copy-pasting the exact same code, works fine when I manually copy and paste to external Terminal (Both outside of VS Code and also inside VS Code Terminal) 

I'm suspecting that there are either:
1. Magical copy-paste detection mechanism built into 3.13 REPL (such via custom sequences or some environment variable) that VS Code is missing to do. 
2. Something in the new auto-identation that does not accept programmatic send of text to REPL that does not respect pre-idented Python code to be run. 

Another issue related to 3.13 REPL in VS Code: https://github.com/python/cpython/issues/126131

Thanks in advance for your help and care.

/cc @brettcannon @pablogsal @Tyriar 
### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by brettcannon** [comment]
And /cc @ambv

**Comment by ambv** [comment]
@anthonykim1, you can programatically paste code using bracketed pasting, in which case additional indentation won't be inserted by the REPL.

**Comment by ambv** [comment]
The REPL accepts interactive input and automatically indents. How is that a bug? Do you have a suggestion how a TTY application is supposed to automatically discover "programmatic input"? AFAICT this is what bracketed paste is for, it's literally for pre-formatted input.

**Comment by Tyriar** [comment]
@ambv oh sorry I thought this was https://github.com/python/cpython/issues/126131 😅 you're right. Bracketed paste mode is the right fix here on our end

**Comment by anthonykim1** [comment]
Thanks everyone for your help. I've just recently merged some changes in the vscode-python repo with the suggested bracketed paste mode and things are looking good so far :)
