### ISSUE TITLE
Guide to the parser contains an obsolete link to Changing CPython's grammar

### ISSUE THREAD

**Issue by valerii-software** [python/cpython#126509]
# Documentation

cpython/InternalDocs/parser.md line 20
```md
See the devguide's [Changing CPython's grammar](https://devguide.python.org/developer-workflow/grammar/#grammar)
```
The link refers to https://devguide.python.org/developer-workflow/grammar/#grammar with such content:
```text
This document is now part of the [CPython Internals Docs](https://github.com/python/cpython/blob/main/InternalDocs/changing_grammar.md).
```
The link inside refers to https://github.com/python/cpython/blob/main/InternalDocs/changing_grammar.md which is in the same directory as an initial parsed.md docs file.
So it is suggested to use a relative path to the file as such
```md
See the devguide's [Changing CPython's grammar](./changing_grammar.md)
```

### Linked PRs
* gh-126510

**Comment by Eclips4** [comment]
Hello! Thanks for the report. Would you like to send a PR with fix? :)

**Comment by Eclips4** [comment]
Thank you Valerii for the report and for the fix!
