### ISSUE TITLE
add setter for pathlib.stem

### ISSUE THREAD

**Issue by thawn** [python/cpython#126537]
# Feature or enhancement

### Proposal:

It would be nice to have the option to modify the stem of a file name directly.

Say I have a Path '/tmp/myfile.npy':
```python
file_path = Path('/tmp/myfile.npy')
```
if the file exists, I want to change the file name to '/tmp/myfile-1.npy', in order to avoid overwriting it, I currently need to do the following:
```python
if file_path.exists():
    file_path = file_path.parents / (file_path.stem + '-1' + file_path.suffix)
```
It would be much cleaner, if I could instead just do the following:
```python
if file_path.exists():
    file_path.stem += '-1'
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by ericvsmith** [comment]
By design Paths are immutable and hashable, so this can't be implemented. If it were implemented, they could no longer be used as dictionary keys, for example.

**Comment by thawn** [comment]
o.k. that makes sense

**Comment by thawn** [comment]
thanks for taking the time to explain the issue :-)
