### ISSUE TITLE
Issue building wheel for psycopg2-binary 2.9.9 on Python 3.13 in virtual environment

### ISSUE THREAD

**Issue by mickfree** [python/cpython#126522]
# Bug report

### Bug description:

Description:

When installing dependencies from requirements.txt in a virtual environment with Python 3.13, the installation fails with a subprocess error during the wheel building process for psycopg2-binary version 2.9.9.

The error message indicates that pg_config is missing, which is required to build psycopg2 from source. It suggests adding the directory containing pg_config to the $PATH or specifying the full path.

Steps to Reproduce:

Install Python 3.13.
Set up a virtual environment and activate it.
Run pip install -r requirements.txt with psycopg2-binary==2.9.9 listed as a dependency.
Expected Behavior:

The dependencies, including psycopg2-binary, should install without any issues.

Actual Behavior:

The installation process fails with an error indicating that pg_config is missing, and the wheel for psycopg2-binary cannot be built.

Environment:

Python version: 3.13
psycopg2-binary version: 2.9.9
Operating System: windows 11

Additional Information:

![74f3a0b3-2bb0-426f-885c-4d0132b70719](https://github.com/user-attachments/assets/b0ec36cc-d986-46ff-82db-82b6afaa8ecc)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
Please open bugreport in appropriate project: https://github.com/psycopg/psycopg2/issues

**Comment by hugovk** [comment]
Similar to https://github.com/python/cpython/issues/126521, you'll need to upgrade psycopg2-binary to get precompiled wheels for 3.13:

 * https://pypi.org/project/psycopg2-binary/2.9.10/#files

* https://pypi.org/project/psycopg2-binary/2.9.9/#files
