### ISSUE TITLE
Guides to the parser and grammar contain obsolete links to devguide

### ISSUE THREAD

**Issue by valerii-software** [python/cpython#126529]
# Documentation

Mentioned it for parsed.md in this Issue #126509

Closed in this PR #126510

Found the same issue in compiler.md, and searched through InternalDocs for any other appearance of devguide links, found nothing except two in compiler.md ("Guide to the parser" and "Changing CPython’s grammar").
Also mentioned that in this PR #126510 I added a relative link as `./`, but in InternalDocs only filename as a path is used, so it is better to change it from `./changing_grammar.md` to `changing_grammar.md`

### Linked PRs
* gh-126530

**Comment by rruuaanng** [comment]
Is it possible to close the issue? It seems to have been done :)
