### ISSUE TITLE
`fnmatch` module has incorrect(misleading) translation to Ukrainian (uk) about on which king of wildcards are supported ('які _не_ відрізняються від регулярних виразів')

### ISSUE THREAD

**Issue by salmira** [python/cpython#126582]
# Documentation

Incorrect and misleading translation of the module `fnmatch` description, in the first phrase:

EN: https://docs.python.org/3.13/library/fnmatch.html
> This module provides support for Unix shell-style wildcards, `which are _not_ the same as regular expressions`

UK: https://docs.python.org/uk/3/library/fnmatch.html
> Цей модуль підтримує символи підстановки у стилі оболонки Unix, `які _не_ відрізняються від регулярних виразів`

In this translation, the bold phrase in Ukrainian (UK) version means `which _are the same_ as regular expressions`. It is quite an opposite to the intended meaning!

Correct translation of  `which are _not_ the same as` is 
- either: `які _не_ відповідають регулярним виразам`;
- or: `які _не_ те саме, що регулярні вирази`;
- or: `які _відрізняються_ від регулярних виразів`.

**Comment by Eclips4** [comment]
Hi! 

Please report this to https://github.com/python/python-docs-uk.
For some reason I can't transfer it there :(

**Comment by salmira** [comment]
Thank, I will do that.

**Comment by hugovk** [comment]
> For some reason I can't transfer it there :(

It's [because](https://docs.github.com/en/issues/tracking-your-work-with-issues/administering-issues/transferring-an-issue-to-another-repository):

> To transfer an open issue to another repository, you must have write access to the repository the issue is in and the repository you're transferring the issue to.
