### ISSUE TITLE
Issue installing pandas 2.2.2 with Python 3.13 in a virtual environment

### ISSUE THREAD

**Issue by mickfree** [python/cpython#126521]
# Bug report

### Bug description:

Description:

I recently upgraded to Python 3.13, and while working with Django, I need to set up a virtual environment. After creating the environment, I attempt to install dependencies by running the command:

"pip install -r requirements.txt"

The installation progresses normally until it reaches pandas version 2.2.2. At this point, it stalls and does not proceed further.

This issue seems to be specific to the combination of Python 3.13 and pandas 2.2.2, as it wasn't an issue with previous Python versions.

Steps to Reproduce:

Install Python 3.13.
Set up a virtual environment and activate it.
Run pip install -r requirements.txt with pandas==2.2.2 listed as a dependency.
Expected Behavior:

The dependencies, including pandas, should install without any issues.

Actual Behavior:

The installation process stalls at the pandas 2.2.2 installation step, with no further progress.

Environment:

Python version: 3.13
Pandas version: 2.2.2
Django: 5.1.2
Operating System: windows 11 

Additional Information:

![d51a48ce-4022-4d4c-b5a1-9c131b9a7e6c](https://github.com/user-attachments/assets/d6c53ffb-f842-4932-b3d3-f006b9df149a)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
Sorry, but here is bugtracker for the CPython.

You should report this issue here: https://github.com/pandas-dev/pandas/issues.  Please include more information, e.g. run pip with --verbose option.  I would guess, that it not "stalls", but built package (pandas v2.2.2 has no binary wheels for CPython 3.13) - that might take some time.

**Comment by hugovk** [comment]
Try pandas 2.2.3, I see it has precompiled wheels for 3.13:

https://pypi.org/project/pandas/2.2.3/#files

And 2.2.2 didn't:

https://pypi.org/project/pandas/2.2.2/#files
