### ISSUE TITLE
zipfile.Path.open is slow when opening for writing in a ZIP with many entries

### ISSUE THREAD

**Issue by janhicken** [python/cpython#126565]
# Bug report

### Bug description:

I'm using the `zipfile` module to create a ZIP file with thousands of members. Each file is created by creating a corresponding `zipfile.Path` object first and then calling `.open()` on it.

The implementation of `open()` contains a check whether the file already exists when opening a file in read mode:

```python
if not self.exists() and zip_mode == 'r':
    raise FileNotFoundError(self)
```

However, `self.exists()` is called even in write mode, because it is the `and` operator's first argument.
The call to `self.exists()` is quite slow however, because this requires the ZIP file's `.namelist()` to be computed, which in turn requires to compute all the implied directories. After all, this is the reason why the `FastLookup` optimization exists for ZIP files in read mode.

I found this issue after profiling my application and was surprised that more than half of its execution time was spent in computing implied ZIP directories.

I would propose to swap the `and` arguments so the check looks like this:

```python
if zip_mode == "r" and not self.exists():
    raise FileNotFoundError(self)
```

This will cause the `self.exists()` check to only be run in read mode, where the check is fast because of `FastLookup` anyway.

I'm happy to provide a pull request with this change.

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-126576
* gh-126642
* gh-126643

**Comment by picnixz** [comment]
I'd say such PR would be welcomed and you could also check if other tests need that kind of optimization. Let me confirm with a core dev: cc @jaraco

**Comment by jaraco** [comment]
This fix is also available on older Pythons with zipp 3.21.0.

**Comment by picnixz** [comment]
Closing since backported and completed. Thank you all.

**Comment by gpshead** [comment]
thanks for finding and fixing this!
