### ISSUE TITLE
Allow the use of strings as loading or saving paths for JSON

### ISSUE THREAD

**Issue by moyanj** [python/cpython#126629]
# Feature or enhancement

### Proposal:

Allow the use of strings as loading or saving paths for JSON. 

It maintains the original API, but allows strings to be passed in when passing in file descriptors.This makes it easy to load or save JSON files.

Just like this:
```python
import json

data = {
    "a":"b"
}
json.dump(data, "a.json")  # before: json.dump(data, open("a.json","w"))
```

I have submitted a pull request. #126626

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

#87623 
#85456
#80559

### Linked PRs
* gh-126626

**Comment by moyanj** [comment]
I have read some discussions about this issue.I think this is a meaningless pull request, so I will close it.

**Comment by nineteendo** [comment]
If you still want a convenience function, you can use https://pypi.org/project/jsonyx.
