### ISSUE TITLE
Unexpected behaviour of `__subclasshook__` with `abc` 

### ISSUE THREAD

**Issue by SimonKoop** [python/cpython#126604]
# Bug report

### Bug description:

When using `__subclasshook__` on a childclass of another class, this can lead to unexpected behaviour for `issubclass` when used on a parent class or sibling class as shown in the following two code examples:
```python
import abc

class X(metaclass=abc.ABCMeta):
    pass

class Y(X):
    pass

class Z(X):
    pass

define_magic = True  # try toggling this value
if define_magic:
    class Magic(Y):
        @classmethod
        def __subclasshook__(cls, maybe_subclass):
            if issubclass(maybe_subclass, Z):
                return True
            return NotImplemented
    
assert issubclass(Z, Y) == define_magic
```

and 

```python
import abc

use_meta:bool = False  # try toggling this

if use_meta:
    class Module(metaclass=abc.ABCMeta):
        pass
else:
    class Module:
        pass 

class StatefulModule(Module):
    pass


class RegularLayer(Module):
    pass

class MaybeStatefulLayer(StatefulModule):
    pass

class SpecificRegularLayer(RegularLayer):
    pass

class SpecialModuleCollection(Module, metaclass=abc.ABCMeta):
    @classmethod
    def __subclasshook__(cls, maybe_subclass):
        if issubclass(maybe_subclass, (RegularLayer, MaybeStatefulLayer)):
            return True
        return NotImplemented
    pass
    
class SpecificSpecialModule(StatefulModule, SpecialModuleCollection):
    pass
    
assert issubclass(SpecificRegularLayer, StatefulModule) == use_meta
```
The code examples are based on https://github.com/patrick-kidger/equinox/issues/893

### CPython versions tested on:

3.10, 3.11, 3.13

### Operating systems tested on:

Linux, Windows

**Comment by AlexWaygood** [comment]
Hmm, not sure I see anything to do with the `typing` module or typing internals here @picnixz :-)

To me, this looks like a bug report to do with the `abc` module

**Comment by picnixz** [comment]
Oh, I thought that typing and abc were actually tight to each others hence the label. Thanks for the clarification Alex!

**Comment by ZeroIntensity** [comment]
Isn't `abc` pure-Python? I would think this needs the `stdlib` label, there's no C code at play here.

**Comment by picnixz** [comment]
The `abc` module has a C implementation but also a Python implementation. I assume that the issue is with the C implementation in this case but I can add the `stdlib` label as well!

**Comment by brianschubert** [comment]
Not too familiar with abc internals, but taking a quick look at the implementation, it looks like this may be the relevant snippet (taken from `_abc__abc_subclasscheck_impl`, which is called from `ABCMeta.__subclasscheck__`):
https://github.com/python/cpython/blob/54c63a32d06cb5f07a66245c375eac7d7efb964a/Modules/_abc.c#L799-L825

My (naive) reading of this is that this is intentional behavior. Checking whether a class is a subclass of an ABC involves performing subclass checks against _each_ subclass of the ABC.

**Comment by ZeroIntensity** [comment]
> The `abc` module has a C implementation but also a Python implementation. I assume that the issue is with the C implementation in this case but I can add the `stdlib` label as well!

Ah, I didn't realize it had an accelerator.

**Comment by SimonKoop** [comment]
> My (naive) reading of this is that this is intentional behavior. Checking whether a class is a subclass of an ABC involves performing subclass checks against each subclass of the ABC, hence why checking issubclass(Z, Y) involves the result of issubclass(Z, Magic)

You're right, in the second code example, I forgot that the `__subclasshook__` would be inherited by `SpecificSpecialModule` resulting in `SpecificRegularLayer` being a subclass of `SpecificSpecialModule` which in turn is a subclass of `StatefulModule`. 
My apologies for the incorrect bug report.

**Comment by picnixz** [comment]
(Closing as a `not a bug`)
