### ISSUE TITLE
Emscripten support: Remove `--with-emscripten-target`

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#126691]
It's possible to support both node and the browser with a single configuration, for instance Pyodide does this. I think this is preferable since it's fewer options to have test coverage for or to not cover and be in doubt about whether they work. Requires refactoring the way the Python.html example and node runner work.

cc @freakboy3742 

### Linked PRs
* gh-126787

**Comment by freakboy3742** [comment]
If this is possible, I agree it would be preferable.
