### ISSUE TITLE
<spam>

### ISSUE THREAD

**Issue by LeoniClemente** [python/cpython#126656]
# Crash report

### What happened?

```python
# Add a code block here, if required
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

### Output from running 'python -VV' on the command line:

reparo de falhas

**Comment by picnixz** [comment]
Please, do NOT create un-necessary bug reports like that.

See https://github.com/python/cpython/issues/126641#issuecomment-2466753931.

**Comment by terryjreedy** [comment]
translate.google.com says Portuguese (Brazil) "fault repair")

**Comment by terryjreedy** [comment]
Por favor, NÃO crie relatórios de bugs desnecessários como esse.

**Comment by terryjreedy** [comment]
t.g correct: GH profile says from São Gonçalo,  a municipality in Rio de Janeiro, Brazil.
