### ISSUE TITLE
Missing module aifc ..... please check there is a missing module which is sooo irritating mee

### ISSUE THREAD

**Issue by hyperbeast111** [python/cpython#126661]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
The aifc module was removed in CPython 3.13, among others "dead batteries".  It was deprecated since 3.11.

Is this your issue?  If not, please describe it in more details.  See https://devguide.python.org/triage/issue-tracker/#reporting-an-issue for some hints on how post useful bugreports.

**Comment by ZeroIntensity** [comment]
If you want the dead battery back, you can [install it off PyPI](https://pypi.org/project/standard-aifc/).
