### ISSUE TITLE
CPython should not assume that pthread_self returns the same value in fork parent and child

### ISSUE THREAD

**Issue by nico** [python/cpython#126688]
Summarized from https://github.com/SerenityOS/serenity/issues/25263 by request of @colesbury:

It seems that at least Python 3.13 relies on pthread_self returning the same value in both the parent and the child process.
[PyThread_get_thread_ident_ex](https://github.com/python/cpython/blob/3.13/Python/thread_pthread.h#L349)

POSIX doesn't seem to mention if the value returned by pthread_self should be inherited by the child process.  
[pthread_self](https://pubs.opengroup.org/onlinepubs/9799919799/functions/pthread_self.html)
[fork](https://pubs.opengroup.org/onlinepubs/9799919799/functions/fork.html)

(It is the case on Linux, Hurd, FreeBSD, OpenBSD, Cygwin. It isn't on SerenityOS, and also not on Solaris 9/HP-UX 11 per https://bugs.python.org/issue7242.

It looks like the code add broke things is from this commit https://github.com/python/cpython/commit/e21057b99967eb5323320e6d1121955e0cd2985e added in https://github.com/python/cpython/pull/118523 as part of https://github.com/python/cpython/issues/117657

### Linked PRs
* gh-126692
* gh-126765
* gh-127121

**Comment by oskar-skog** [comment]
I think this can be closed now.

**Comment by ericsnowcurrently** [comment]
There may be other code that makes the same assumption about the thread ID.  For example, in `PyOS_AfterFork_Child()`:

https://github.com/python/cpython/blob/09c240f20c47db126ad7e162df41e5c2596962d4/Modules/posixmodule.c#L655-L658

This would break only on debug builds (or at least `!defined(NDEBUG)`).

I'm guessing there are other places too.
