### ISSUE TITLE
Add exec_c and eval_c

### ISSUE THREAD

**Issue by kailando** [python/cpython#126605]
# Feature or enhancement

### Proposal:

I want to add two functions to the CPython programming language. They interact with the CPython backend itself. Here they are:
```python
exec_c()
eval_c()
```

It would make Python _way_ more customizable.
They would have full access to the global variables of the backend, so it could be used as an **extender** for the project,
or you could use it to **test a driver**, say:
You have a driver that nullifies `BugKeCheck2` (the function that raises BSODs) and want to test it, but don't have `gcc`, etc...
You are familiar with Python, but you know you have to raise it from low(_er_)-level C, so you do:
```python
exec_c("BugKeCheck.BugKeCheck1.BugKeCheck2();", accept_errors=True)
```

Example:
```python
# P.S.: I don't know how to code in C, so im using what I do know
exec_c('"Hello" >> stdout;') # None
eval_c('"Hello" >> stdout;') # "Hello"
```
**[EDIT: I am not a big fan of this anymore.]**

### Has this already been discussed elsewhere?

This is a minor feature **[EDIT: This is proven otherwise, as it _"needs a PEP"_ (-_@sobolevn_. Nov 10, 2024)]**, which does not need previous discussion elsewhere

**Comment by ZeroIntensity** [comment]
Well, this wouldn't be possible to implement, unless we decided it would be a good idea to spend a few years developing our own C compiler. With that being said, this is probably my favorite feature idea ever :smile:

**Comment by vasily-v-ryabov** [comment]
There is a 3rd-party package cppyy which can do exactly the same. It is a Python wrapped C/C++ JIT compiler cling.

Also Python standard library has module ctypes which load DLL or SO binary library and call any function that may be written originally in pure C programming language. For other languages there are some bindings like PyO3 for Rust which do the same interoperability with already compiled code.

New proposals should be clearly compared with such existing solutions.

**Comment by sobolevn** [comment]
Bun JS runtime allows something similar: https://bun.sh/blog/compile-and-run-c-in-js
It uses tinycc inside and compiles C code on the fly.

It might be a fun idea for a side project.

**Comment by kailando** [comment]
Ok, I will talk about this on the CPython forum, but this is a minor feature so I wouldn't expect it to go there.

**Comment by kailando** [comment]
> Interesting idea, but how could Python execute C code without a C compiler? It's a very big project to be able to run arbitrary C code in a script language. I don't believe this is something CPython currently intends to do.
> 
> Also, for big features like this, you should discuss it in discuss.python.org first :)

I don't think this would be classified as a _big_ feature.

**Comment by sobolevn** [comment]
@kailando it is. It will also require a PEP.

**Comment by kailando** [comment]
@sobolevn Why would it need a PEP?
Also, I'm gonna cancel this idea, because I'm not a big fan of it anymore.

**Comment by ZeroIntensity** [comment]
Because additions to builtins require PEPs, and the maintenance cost would be huge.

> Also, I'm gonna cancel this idea, because I'm not a big fan of it anymore.

I still think this is a super fun idea, but I also think that there's a better chance of Python 4 being released tomorrow than this ever getting accepted.
