### ISSUE TITLE
Indentation fix to one line of the source code?

### ISSUE THREAD

**Issue by zhangyx1998** [python/cpython#126757]
Hi, is there a reason that this [line](https://github.com/python/cpython/blob/03924b5deeb766fabd53ced28ba707e4dd08fb60/Python/bltinmodule.c#L3339) is indented differently?

If not, will it be ok if I open a PR to make it align with others?

(Not really a big deal...)

### Linked PRs
* gh-126758

**Comment by terryjreedy** [comment]
No obvious reason.  Looks like a typo fix.  I suggest make a PR.
