### ISSUE TITLE
`frozenset` could be "updated" by `|=` operator, is this intended?

### ISSUE THREAD

**Issue by DanielYang59** [python/cpython#126783]
# Bug report

### Bug description:

The `|=` operator behaves unexpectedly when used with `frozenset`, where it creates a new instance. This can be misleading because it effectively updates it. I would expect this to trigger a `TypeError`?

```python
fs = frozenset([1, 2, 3])

print(id(fs))  # 4379466816

fs |= {4, 5}

print(fs)  # >>> frozenset({1, 2, 3, 4, 5})

print(id(fs))  # ID changed to 4379462560

```

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12, 3.13

### Operating systems tested on:

macOS

**Comment by nineteendo** [comment]
No, only the reference is updated:

```python
>>> set1 = set2 = frozenset([1, 2, 3])
>>> set2 |= {4, 5} # equivalent to set2 = set2 | {4, 5}
>>> set1
frozenset({1, 2, 3})
>>> set2
frozenset({1, 2, 3, 4, 5})
```

**Comment by skirpichev** [comment]
I don't anything wrong in this, consider:
```pycon
>>> i = 1234
>>> id(i)
140639472689744
>>> i += 1
>>> i
1235
>>> id(i)
140639472686640
```

On another hand, docs [says](https://docs.python.org/3.13/library/stdtypes.html#frozenset): "The following table lists operations available for [set](https://docs.python.org/3.13/library/stdtypes.html#set) that do not apply to immutable instances of [frozenset](https://docs.python.org/3.13/library/stdtypes.html#frozenset): 
update(*others)
set |= other | ...

    Update the set, adding elements from all others."

Seems to be a docs issue.

**Comment by ZeroIntensity** [comment]
If you're interested in mutating immutable objects, please look into footguns such as [ctypes](https://docs.python.org/3/library/ctypes.html) :smile:

I don't see anything that looks like a bug here.

**Comment by nineteendo** [comment]
https://docs.python.org/3/reference/datamodel.html#object.__iadd__:

> if *x* is an instance of a class with an `__iadd__` method, ``x += y`` is equivalent to ``x = x.__iadd__(y)`` . If :meth:`__iadd__` does not exist, or if ``x.__iadd__(y)`` returns `NotImplemented`, ``x.__add__(y)`` and ``y.__radd__(x)`` are considered, as with the evaluation of ``x + y``.

**Comment by ZeroIntensity** [comment]
Maybe we could have decided it could raise a `TypeError` 20 years ago. Now, changing that would break untold amounts of code. Sorry :(

**Comment by DanielYang59** [comment]
> Read my comment above, the same applies to __ior__().

Thanks that's really helpful. I thought `|=` would internally call `__ior__` exactly and it turns out it falls back to `x = x.__or__(y)`. I really appreciate this :)

> Maybe we could have decided it could raise a TypeError 20 years ago. Now, changing that would break untold amounts of code. Sorry :(

Understandable :)

**Comment by ZeroIntensity** [comment]
They work, but those methods don't behave on `frozenset` as they do `set`.
