### ISSUE TITLE
pygettext: Add support for multi-argument gettext functions

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#126700]
# Feature or enhancement

### Proposal:

This came up while adding translation tests for various stdlib modules: https://github.com/python/cpython/issues/124295 and https://github.com/python/cpython/pull/126698. More specifically: https://github.com/python/cpython/issues/124295#issuecomment-2440904998

pygettext currently only supports single-argument `gettext` and its aliases (can be controlled via CLI arguments). `pgettext`, `ngettext`, etc., are not supported. pygettext should support these by default. I'm gonna take a stab at this hopefully this week :)

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126912

**Comment by serhiy-storchaka** [comment]
Thank you @tomasr8. I did not expect that you can do this before making pygettext to use AST parser.
