### ISSUE TITLE
 C:\Users\uset\AppData\Local\Programs\Python\Python313\Scripts\jupyter.exe\__main__.py:7: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious and fails to parse leap day. The default behavior will change in Python 3.15 to either always raise an exception or to use a different default year (TBD). To avoid trouble, add a specific year to the input & format.

### ISSUE THREAD

**Issue by pandu07031993** [python/cpython#126728]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```

C:\Users\uset\AppData\Local\Programs\Python\Python313\Scripts\jupyter.exe\__main__.py:7: DeprecationWarning: Parsing dates involving a day of month without a year specified is ambiguious
and fails to parse leap day. The default behavior will change in Python 3.15
to either always raise an exception or to use a different default year (TBD).
To avoid trouble, add a specific year to the input & format.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by skirpichev** [comment]
That seems to be not related to the CPython, rather to https://github.com/jupyter/.  Please report issue to an appropriate project.
