### ISSUE TITLE
Docs: Missing EOL banner on 3.8 documentation

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#126751]
# Documentation

This warning is present on the documentation of 2.7 and 3.4-3.7, but not on 3.8:

![image](https://github.com/user-attachments/assets/ef15e764-4cc9-41ea-987e-bcd9944ba347)

**Comment by AA-Turner** [comment]
This is already tracked in docsbuild-scripts.

A

**Comment by nineteendo** [comment]
Found it: https://github.com/python/docsbuild-scripts/issues/216
