### ISSUE TITLE
`ast.literal_eval` Segmentation Fault in Python 3.10

### ISSUE THREAD

**Issue by EgodPrime** [python/cpython#126710]
# Crash report

### What happened?

```python
a = 'P/a'*200000
import ast
ast.literal_eval(a)
```

The above code makes Python 3.10 crash with Segmentation Fault. 

### CPython versions tested on:

3.9, 3.10

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.10.15 (main, Oct  3 2024, 07:27:34) [GCC 11.2.0]

**Comment by skirpichev** [comment]
BTW, in 3.11+ we have:
```pycon
>>> a = 'P/a'*200000
>>> import ast
>>> ast.literal_eval(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/ast.py", line 64, in literal_eval
    node_or_string = parse(node_or_string.lstrip(" \t"), mode='eval')
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RecursionError: maximum recursion depth exceeded during ast construction
```

**Comment by EgodPrime** [comment]
Sorry, this issue is a mistake commit, I have made a new one

**Comment by zware** [comment]
For future reference, there was no need to create a new issue, this one could easily have been updated.  I very nearly closed the new one as a duplicate before catching up here.

Duplicate of gh-126711.
