### ISSUE TITLE
Outdated `pprint.pp` doc example about pypi `sampleproject` version

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#126731]
# Documentation

Currently, the examples in `pprint` that demonstrate the `pprint.pp` function are outdated. The last edit was in 2018, six years ago, and the JSON link in the example now points to `sampleproject` (see https://github.com/python/cpython/pull/10201). The documentation currently references version 1.2 of `sampleproject`, which was released in 2015 (https://pypi.org/project/sampleproject/#history). The latest version is now 4.0, released last week. Thus, the information in the documentation no longer matches the current state, and I have submitted a PR to address this.  The information varies widely over the past nine years

A possible question might be: do we need to frequently update this example? The answer is no—it changes infrequently and thus won’t increase maintenance overhead.

### Linked PRs
* gh-126732
* gh-126818
* gh-126819

**Comment by brianschubert** [comment]
Perhaps we should pin the version in the URL so that the example won't become stale again in the future? For example:
```python
with urlopen('https://pypi.org/pypi/sampleproject/1.2.0/json') as resp:
    ...
````
