### ISSUE TITLE
Overflow if `co_exceptiontable` is absurdly large

### ISSUE THREAD

**Issue by federicovalenso** [python/cpython#126858]
# Bug report

### Bug description:

```python
f.__code__ = f.__code__.replace(co_linetable=bytes(bytearray(2**31+1)))
```

It can lead to overflow in [assemble.c](https://github.com/python/cpython/blob/c0f045f7fd3bb7ccf9828f4bfad55347d097fd41/Python/assemble.c#L139C9-L139C30)

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
Actually, how is `co_exceptiontable` related to `a_except_table`?

**Comment by ZeroIntensity** [comment]
This one doesn't seem like it's worth fixing, there's plenty of ways to crash the interpreter by messing with code objects.

**Comment by picnixz** [comment]
I think I'll close this one unless you can find me a simple reproducer.
