### ISSUE TITLE
Outdated docs about `asyncio.start_server()`

### ISSUE THREAD

**Issue by beavailable** [python/cpython#126896]
# Documentation
Since 3.13, the function `asyncio.start_server()` has added a parameter named `keep_alive` (see https://github.com/python/cpython/pull/112485), but the docs didn't completely update in that PR, so the website still shows the old function signature (see https://docs.python.org/3/library/asyncio-stream.html#asyncio.start_server).

It's actually my fault and I'll submit a PR to fix it.

### Linked PRs
* gh-126897
* gh-126934

**Comment by gpshead** [comment]
thanks!
