### ISSUE TITLE
Internal docs: Update code blocks in `garbage_collector.md` to improve syntax highlighting

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#126882]
Code blocks in [garbage_collector.md](https://github.com/python/cpython/blob/main/InternalDocs/garbage_collector.md) are annotated with `pycon` which doesn't play well GitHub's syntax highlighting (and neither with VS Code's Markdown preview):

![image](https://github.com/user-attachments/assets/cd6bbf90-d85c-40eb-ab76-6df85a111efa)

I suggest we change that to `python` which highlights the code blocks properly:

![image](https://github.com/user-attachments/assets/8d47e881-d89f-40c5-a5d2-f8a60db9d5fb)

### Linked PRs
* gh-126887

**Comment by bhagwant4040** [comment]
`class Proxy:
    def __init__(self):
        self._config = {}

    def __getattr__(self, name):
        if name in self._config:
            return self._config[name]
        raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

    def __setattr__(self, name, value):
        if name == '_config':
            super().__setattr__(name, value)
        else:
            self._config[name] = value

    def __delattr__(self, name):
        if name in self._config:
            del self._config[name]
        else:
            raise AttributeError(f"'{self.__class__.__name__}' object has no attribute '{name}'")

# Example usage
if __name__ == "__main__":
    from unittest.mock import patch

    p = Proxy()
    p.a = True
    print(p.a)  # Output: True

    with patch.object(p, 'a', False):
        print(p.a)  # Output: False (mocked)

    print(p.a)  # Output: True (original value)`

Key Changes Explained
Use of a Private Dictionary:

The _config dictionary is used to store attributes, which helps avoid conflicts with the class's built-in methods and attributes.
Correct __getattr__ Implementation:

The __getattr__ method checks if the requested attribute exists in _config and raises an AttributeError if it does not.
Proper __setattr__ Method:

The __setattr__ method ensures that the special _config attribute is set using super(), while other attributes are stored in the _config dictionary.
Accurate __delattr__ Method:

The __delattr__ method correctly deletes attributes from _config without setting them to a default value, allowing for proper attribute deletion.
Conclusion
This final implementation of the Proxy class ensures that it behaves correctly with attribute access, setting, and deletion, making it compatible with unittest.mock.patch. You can use this class in your tests without encountering the issues previously discussed.

**Comment by javert42** [comment]
This is my first attempt at a contribution (to any project--not just cpython), so I welcome any feedback!

I still need to sign the CLA, and figure out how step number 8 from the Developer's Guide applies.
