### ISSUE TITLE
subprocess.run("clip", ...) gives me a wrong the wrong output in the wrong language

### ISSUE THREAD

**Issue by JulianDominic** [python/cpython#126873]
# Bug report

### Bug description:

I wrote the following code to convert a multi-line string into a single-line string.

It works as expected with other strings except for the following `is_anagram` C function.

```python
import subprocess 

def split_newlines(string:str):
    return string.split("\n")

def get_num_tabs(string:str):
    count = 0
    tabs = 0
    for i in range(len(string)):
        if string[i] == ' ':
            count += 1
            if count % 4 == 0:
                tabs += 1
        else:
            break
    return tabs

raw =\
"""\
bool is_anagram(char *s1, char *s2) {
    // If they aren't the same length, they are clearly not anagrams
    if (strlen(s1) != strlen(s2)) {
        return false;
    }

    // Use two arrays to count the number of characters (either ALL lower or ALL upper)
    int arr1[26] = {0};
    int arr2[26] = {0};

    while (*s1 != '\0') {
        if (isalpha(*s1) && islower(*s1)) {
            arr1[*s1 - 'a'] += 1;
        }
        s1++;
    }
    while (*s2 != '\0') {
        if (isalpha(*s2) && islower(*s2)) {
            arr2[*s2 - 'a'] += 1;
        }
        s2++;
    }

    // If they have the same count, then they are the same
    for (int i = 0; i < 26; i++) {
        if (arr1[i] != arr2[i]) {
            return false;
        }
    }
    return true;
}\
"""

s = split_newlines(raw)
lines = [sen.strip() for sen in s]
tabs = [get_num_tabs(w) for w in s]
result = ""
for line, tab in zip(lines, tabs):
    result += r'\t' * tab + line + r'\n'
print(result)
subprocess.run("clip", text=True, input=result)
```

print(result) actually gives me the correct result of

```
bool is_anagram(char *s1, char *s2) {\n\t// If they aren't the same length, they are clearly not anagrams\n\tif (strlen(s1) != strlen(s2)) {\n\t\treturn false;\n\t}\n\n\t// Use two arrays to count the number of characters (either ALL lower or ALL upper)\n\tint arr1[26] = {0};\n\tint arr2[26] = {0};\n\n\twhile (*s1 != '') {\n\t\tif (isalpha(*s1) && islower(*s1)) {\n\t\t\tarr1[*s1 - 'a'] += 1;\n\t\t}\n\t\ts1++;\n\t}\n\twhile (*s2 != '') {\n\t\tif (isalpha(*s2) && islower(*s2)) {\n\t\t\tarr2[*s2 - 'a'] += 1;\n\t\t}\n\t\ts2++;\n\t}\n\n\t// If they have the same count, then they are the same\n\tfor (int i = 0; i < 26; i++) {\n\t\tif (arr1[i] != arr2[i]) {\n\t\t\treturn false;\n\t\t}\n\t}\n\treturn true;\n}\n
```

However, what gets copied into my clipboard is some Chinese text with other symbols

```
潢汯椠彳湡条慲⡭档牡⨠ㅳ‬档牡⨠㉳ 屻屮⽴ 晉琠敨⁹牡湥琧琠敨猠浡⁥敬杮桴‬桴祥愠敲挠敬牡祬渠瑯愠慮牧浡屳屮楴⁦猨牴敬⡮ㅳ 㴡猠牴敬⡮㉳⤩笠湜瑜瑜敲畴湲映污敳尻屮絴湜湜瑜⼯唠敳琠潷愠牲祡⁳潴挠畯瑮琠敨渠浵敢⁲景挠慨慲瑣牥⁳攨瑩敨⁲䱁⁌潬敷⁲牯䄠䱌甠灰牥尩屮楴瑮愠牲嬱㘲⁝‽ほ㭽湜瑜湩⁴牡㉲㉛崶㴠笠細尻屮屮睴楨敬⠠猪‱㴡✠✀ 屻屮屴楴⁦椨慳灬慨⨨ㅳ ☦椠汳睯牥⨨ㅳ⤩笠湜瑜瑜瑜牡ㅲ⩛ㅳⴠ✠❡⁝㴫ㄠ尻屮屴絴湜瑜瑜ㅳ⬫尻屮絴湜瑜桷汩⁥⨨㉳℠‽'⤧笠湜瑜瑜晩⠠獩污桰⡡猪⤲☠…獩潬敷⡲猪⤲ 屻屮屴屴慴牲嬲猪′‭愧崧⬠‽㬱湜瑜瑜屽屮屴獴⬲㬫湜瑜屽屮屮⽴ 晉琠敨⁹慨敶琠敨猠浡⁥潣湵ⱴ琠敨⁮桴祥愠敲琠敨猠浡履屮晴牯⠠湩⁴⁩‽㬰椠㰠㈠㬶椠⬫ 屻屮屴楴⁦愨牲嬱嵩℠‽牡㉲楛⥝笠湜瑜瑜瑜敲畴湲映污敳尻屮屴絴湜瑜屽屮牴瑥牵⁮牴敵尻絮湜
```

I have tested this on Python 3.13.0 and Python 3.12.5

I have tested this on both Windows 10 and Windows 11.

I assume this is a Windows-only issue because when tried to run it on WSL Ubuntu 24.04, it gave me an error: `FileNotFoundError: [Errno 2] No such file or directory: 'clip'`

I forgot to mention, I do not have any Chinese keyboards installed. Only English (United States) US Keyboard, and English (Singapore) US Keyboard.

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
1. Have you tried using the shell itself, without Python (namely call "clip [...]" directly?) does it work outside of Python?
2. I'm not entirely sure it's a Python issue but maybe more of how to use `clip`?
3. Can you check the output of `run(...)`? does it exit with a code 0?

**Comment by nineteendo** [comment]
It looks like utf8 is being interpreted as utf16 (or something similar):

```python
print(b"""\
bool is_anagram(char *s1, char *s2) {
    // If they aren't the same length, they are clearly not anagrams
    if (strlen(s1) != strlen(s2)) {
        return false;
    }\
""".decode("utf_16_le"))
```

```none
潢汯椠彳湡条慲⡭档牡⨠ㅳ‬档牡⨠㉳ ੻††⼯䤠⁦桴祥愠敲❮⁴桴⁥慳敭氠湥瑧ⱨ琠敨⁹牡⁥汣慥汲⁹潮⁴湡条慲獭 †椠⁦猨牴敬⡮ㅳ 㴡猠牴敬⡮㉳⤩笠 †††爠瑥牵⁮慦獬㭥 †素
```

**Comment by picnixz** [comment]
Then, instead of using `text=True` maybe passing the input as bytes and specifying the encoding could help?

**Comment by JulianDominic** [comment]
> 1. Have you tried using the shell itself, without Python (namely call "clip [...]" directly?) does it work outside of Python?
> 
>     2. I'm not entirely sure it's a Python issue but maybe more of how to use `clip`?
> 
>     3. Can you check the output of `run(...)`? does it exit with a code 0?
> 
>     4. Can you try escaping the entire text? Maybe some characters need to be escaped. Can you try normal hexadecimal + spaces multi-line text (no asterisks, no tabs, etc)
> 
>     5. What "other strings" are you referring to?

1. I have just tested, yes it works outside of Python. I saved the single-line string `bool is_anagram...` to a new file `test.txt`. Then I ran `clip < test.txt`. I got the correct output.
2. I have not considered that, might be?
3. Yes it does, `CompletedProcess(args='clip', returncode=0)`.
4. I have just replaced `'\t'` with `'    '` (4 spaces). Still the same output. However, now when I prefix `\` to an asterisk, I get an error `<>:19: SyntaxWarning: invalid escape sequence '\*'`, BUT the output is as expected (with the new `\`).
5. I don't want to flood this message but I used other C functions I made such as:

```
// Greatest Common Divisor (needs abs to be strict)
// gcd(a,b) = gcd(b,r) . stops when r = 0 or 1
int gcd(int a, int b) {
    a = abs(a);
    b = abs(b);

    while (b > 0) {
        int r = a % b;
        a = b;
        b = r;
    }
    return a;
}
```

then it will give me (correct)  

```
// Greatest Common Divisor (needs abs to be strict)\n// gcd(a,b) = gcd(b,r) . stops when r = 0 or 1\nint gcd(int a, int b) {\n\ta = abs(a);\n\tb = abs(b);\n\n\twhile (b > 0) {\n\t\tint r = a % b;\n\t\ta = b;\n\t\tb = r;\n\t}\n\treturn a;\n}\n
```

**Comment by JulianDominic** [comment]
Ok, I found the problem. It was a complete user error here!

`\0` was causing clip to do funny things because I think clip probably looks for the terminating character?

My solution is just to add the `r` in front of my triple quotes!
