### ISSUE TITLE
Decimal.shift does not fully obey its context arg?

### ISSUE THREAD

**Issue by brent-ridian** [python/cpython#126854]
# Bug report

### Bug description:

My motivation for supplying a context arg is to try and cure some disastrous behavior of shift.

Consider this code:
```
from decimal import Decimal

d = Decimal("-79341.2900373")
print(f"{d.shift(10) = !s}")
print(f"{d.shift(-10) = !s}")
```

That code prints:
```
d.shift(10) = -793412900373000.0000000
d.shift(-10) = -0.0000079
```

The first result, for other = 10, is what I expect: the digits of d were shifted 10 places to the left of the decimal point.

The second result, for other = -10, already shows a problem: the digits of d were shifted 10 places to the right of the decimal point **but then the 10 rightmost digits (3412900373) were dropped, which I consider to be bad**.

Now rerun the above code but with d modified to have a lot more digits after the decimal point, say
`d = Decimal("-79341.29003731915145181119441986083984375")`

That code now prints:
```
d.shift(10) = -1.194419860839843750000000000E-8
d.shift(-10) = -1.91514518111944198E-18
```

**These results are vastly different than what I expect.**

----------

From web searches, I am aware that this behavior occurs because of how Decimal does operations exactly and then rounds, drops digits, etc according to some context.

For example, [this link describes similar unexpected behavior in Decimal.normalize](https://github.com/python/cpython/issues/105774).

The final answer in the link above by ghedsouza is to call normalize with a custom Context that ought to stop rounding.

I have verified (by throwing tons of randomly generated Decimals at it) that ghedsouza's custom Context seems to perfectly cure normalize.

----------

Can ghedsouza's approach also cure defects in shift?

Consider this code, where I now call shift with a context arg equal to ghedsouza's Context:
```
from decimal import Context, Decimal, Inexact, MAX_EMAX, MAX_PREC, MIN_EMIN

CONTEXT_ROUND_NEVER = Context(
	traps = [Inexact],
	prec = MAX_PREC,
	Emax = MAX_EMAX,
	Emin = MIN_EMIN,
)

print(f"{CONTEXT_ROUND_NEVER = }")

d = Decimal("-79341.29003731915145181119441986083984375")
print(f"{d.shift(10, CONTEXT_ROUND_NEVER) = !s}")
print(f"{d.shift(-10, CONTEXT_ROUND_NEVER) = !s}")
```

That code prints:
```
CONTEXT_ROUND_NEVER = Context(prec=999999999999999999, rounding=ROUND_HALF_EVEN, Emin=-999999999999999999, Emax=999999999999999999, capitals=1, clamp=0, flags=[], traps=[Inexact])
d.shift(10, CONTEXT_ROUND_NEVER) = -793412900373191.51451811194419860839843750000000000
d.shift(-10, CONTEXT_ROUND_NEVER) = -0.00000793412900373191514518111944198
```

The d.shift(10) result is now perfect, exactly what I expect.

The d.shift(-10) result, while vastly improved, does have this defect: **it dropped the final digits that should have been on the right end (6083984375).**

As near as I can tell, the settings in that CONTEXT_ROUND_NEVER instance are so broad that this should NOT have happened: d.shift(-10) should have dropped no digits.

_To me, it is as if Decimal.shift does not fully obey its context arg_ (at least for right shifts, negative values of other).

So, does shift have a bug?

Or (more likely) is there some subtle behavior in Decimal and/or Context which explains why this behavior is happening?

----------

Final note.

According to its documentation, the Decimal.shift method ought to merely move the Decimal's digit about the decimal point (i.e. be equivalent to multiplying by a power of 10):
https://docs.python.org/3/library/decimal.html#decimal.Decimal.shift

There is no warning in that documentation about any of the completely unexpected behaviors described above.
But there needs to be.

### CPython versions tested on:

3.12

### Operating systems tested on:

Windows

**Comment by tim-one** [comment]
> According to its documentation, the Decimal.shift method ought to merely move the Decimal's digit about the decimal point (i.e. be equivalent to multiplying by a power of 10):

It sounds like you want the `scaleb()` method instead:

```python
>>> from decimal import Decimal
>>> d = Decimal("-79341.2900373")
>>> d.scaleb(10)
Decimal('-7.93412900373E+14')
>>> d.scaleb(-10)
Decimal('-0.00000793412900373')
```

**Comment by skirpichev** [comment]
Yes, behaviour is expected.  It match specification: https://speleotrove.com/decimal/damisc.html#refshift.

But perhaps we can adjust documentation like [mpd_qshift](https://www.bytereef.org/mpdecimal/doc/libmpdec/various.html#shift): Set result to a shifted by b places. b must be in the range [-prec, prec]. A negative b indicates a right shift, a positive b a left shift. _Digits that do not fit are discarded._

Lets just add last sentence to sphinx docs & docstring.

**Comment by tim-one** [comment]
@skirpichev, unclear to me. "Digits that do not fit" means essentially nothing to me - fit _what_? The spec here is clear as mud to me. But then, despite that I've used `decimal` heavily, I've never had a use for its `shift()` or `rotate()`. Pretty sure the OP here doesn't need them either, but really wants `scaleb()` instead (which is useful and clear).

**Comment by skirpichev** [comment]
> "Digits that do not fit" means essentially nothing to me - fit what?

Well, to the digits array.  Keep in mind the whole text (sphinx docs for Decimal.shift): "Return the result of shifting the digits of the first operand by an amount specified by the second operand. The second operand must be an integer in the range -precision through precision. The absolute value of the second operand gives the number of places to shift. If the second operand is positive then the shift is to the left; otherwise the shift is to the right. Digits shifted into the coefficient are zeros. The sign and exponent of the first operand are unchanged. _Digits that do not fit are discarded._"

Maybe sentence must be inserted right before "The sign and exponent [...]".

I agree, it's not ideal.  But probably will prevent issues like current one.  People will be not surprised that rightmost digits might be dropped.  Or leftmost, whatever:
```pycon
>>> from decimal import Decimal
>>> d = Decimal("-79341.2900373")
>>> d.shift(10)
Decimal('-793412900373000.0000000')
>>> d.shift(20)
Decimal('-129003730000000000000.0000000')
```

Some Decimal methods have examples.  Perhaps, this one should also include them to make things clear, i.e. that this beast actually is simple and stupid (like rotate()) and exist (IMO) just to conform to the specification (like rotate()).

> The spec here is clear as mud to me.

Sure I would appreciate better wording.

**Comment by tim-one** [comment]
What "digits array"? That concept isn't mentioned in the docs. Even if it were, it would leave examples like this one baffling:

```python
>>> d = Decimal('79341.29003731915145181119441986083984375')
>>> d.shift(-10)
Decimal('1.91514518111944198E-18')
```

That is, yes, it threw away the last 10 digits, but it _also_ threw away the _first_ 12 digits.

Yes, I know why, but I think it would damage the docs to devote as many words as it would take to explain it. 

Provided the OP confirms that `scaleb()` is what they actually wanted, I'd just close this as "not planned". `shift()` and `rotate()` seem useless you're working with integers that fit in the current working precision - _then_ what they do is already clear enough from trying a few examples.

**Comment by skirpichev** [comment]
@brent-ridian, what do you think about [scaleb suggestion](https://github.com/python/cpython/issues/126854#issuecomment-2477990662) above?  Is this something you expected from shift()?

**Comment by brent-ridian** [comment]
> > According to its documentation, the Decimal.shift method ought to merely move the Decimal's digit about the decimal point (i.e. be equivalent to multiplying by a power of 10):
> 
> It sounds like you want the `scaleb()` method instead:

**Yes, the scaleb method also works.**

_It has at least 2 distinct advantages for me:_

1) its name reads better: it more precisely indicates the intent I want

2) it works exactly as expected with Context objects

_First, even if you just use the default Context (precision of 28 digits), its behavior is superior to shift_: while digits can be dropped, they are always the most insignificant digits.  **So, at least your answer is not utterly invalid like shift can be.**

_Second, if I use the CONTEXT_ROUND_NEVER defined in my original post above, then all digits are preserved._

To demonstrate these points, continue the example from my original post:

Use
`d = Decimal("-79341.29003731915145181119441986083984375")`

shift here produces unmitigated disasters:
```
d.shift(10) = -1.194419860839843750000000000E-8
d.shift(-10) = -1.91514518111944198E-18
```

scaleb with the default Context produces rounded but sane results (final digits of 1986083984375 get rounded to 2):
```
d.scaleb(10) = -793412900373191.5145181119442
d.scaleb(-10) = -0.000007934129003731915145181119442
```

scaleb with CONTEXT_ROUND_NEVER behaves perfectly, preserving all digits:
```
d.scaleb(10, context = CONTEXT_ROUND_NEVER) = -793412900373191.5145181119441986083984375
d.scaleb(-10, context = CONTEXT_ROUND_NEVER) = -0.000007934129003731915145181119441986083984375
```

Thanks tim-one!

**Comment by brent-ridian** [comment]
> Yes, behaviour is expected. It match specification: https://speleotrove.com/decimal/damisc.html#refshift.

It does match the spec, but the spec is defective: it utterly violates the principle of least surprise.

I wonder if there is ever going to be a bank or fintech that goes bankrupt because some programmer thought that by using Decimal he was doing precise math, but he was not aware of this behavior, and some number turned out orders of magnitude different than expected.

> But perhaps we can adjust documentation

If you unable to alter the behavior of this method (your hands are likely tied, I get it), then the docstring on shift & rotate needs RADICAL change, no mere small adjustment.

Its very first sentences should be something like:
"This method is present only to satisfy the IBM decimal number spec, where this method is call the rotate function.
Due to unexpected behavior that will be explained below, this method is dangerous to use, and should almost certainly be avoided."

The next paragraph could be the current docstring.

Then there should be an entire new paragraph explaining that completely unexpected results may happen.  This paragraph should use examples like from this post, and should explain exactly why the results were obtained.

Then there should be a final paragraph that says that most users probably want the scaleb method, which behaves like what they expect.

The docstring for scaleb should use examples like what I posted above to show how it interacts with precisions and Contexts.

**Comment by brent-ridian** [comment]
My original post noted that if I use my custom CONTEXT_ROUND_NEVER, then shift with positive values for its other arg seems to finally work as expected.  But shift with negative values is not yet ideal: it still drops final digits.

Contrast this behavior with the scaleb method: in my post above, I showed that scaleb with CONTEXT_ROUND_NEVER behaves perfectly (never drops digits) for both positive and negative values.

Is there some remaining lurking bug in shift that causes it to not fully obey CONTEXT_ROUND_NEVER?

**Comment by tim-one** [comment]
`decimal` implements a novel mix of floating-point and fixed-point ideas. `scaleb()` belongs to the former, and `shift()` and `rotate()` to the latter. The latter do exactly what people expect them to do _provided that_ they're  applied to integers that fit in the current working precision.  Picture a decimal integer register with `prec` digits, and nothing about them is surprising.

We can't change what they do, because the underlying `libmpdec` is not maintained by us, and `libmpdec` has extensive testing for compliance with the relevant standards. Stefan Krah (who maintains the external `libmpdec` library Python relies on to do the real work) is very unlikely to budge either.

I'd be happy to add words saying that `shift()` and `rotate()` are intended to be applied to integers that fit in the current `prec`, but not more than just that. In all the years Python offered `decimal`, I don't recall them even being mentioned before in an issue report.

**Comment by brent-ridian** [comment]
> I'd be happy to add words saying that `shift()` and `rotate()` are intended to be applied to integers that fit in the current `prec`, but not more than just that

I feel strongly that 1 additional sentence like what you propose is a good start but is not enough.

Can you also add examples, like from this post, that show how shift/rotate produces expected results (when applied to integers that fit in the current `prec`) but can produce surprising results (when applied to integers that bigger than the current `prec`)?

**Comment by tim-one** [comment]
I would not. When the docs say "don't poke the bear", you're on your if you insist on poking it anyway :wink:. These functions are barely used, and it damages the docs to add words that are of no practical value to almost anyone.  

I understand that you're especially sensitive to this because it caused you to waste time. But, so far, you're a universe with only one resident I know of. Limited time is better spent on lower cost/benefit issues - there are a  _lot_ of issues here.

**Comment by skirpichev** [comment]
Maybe examples will be less surprising, if you do normalization first (this does not matter for scaleb(), but does for shift() or rotate()).  Consider last Tim's example:
```pycon
>>> d = Decimal('79341.29003731915145181119441986083984375')
>>> d  # it's not normalized
Decimal('79341.29003731915145181119441986083984375')
>>> d.shift(-10)
Decimal('1.91514518111944198E-18')
>>> +d
Decimal('79341.29003731915145181119442')
>>> (+d).shift(-10)
Decimal('0.00000793412900373191514')
>>> str(+d)[:-10]
'79341.2900373191514'
>>> d.scaleb(-10)
Decimal('0.000007934129003731915145181119442')
>>> (+d).scaleb(-10)
Decimal('0.000007934129003731915145181119442')
```

**Comment by tim-one** [comment]
Yes, these are "fixed point" gimmicks, and it doesn't really matter to that where you picture the decimal point being placed in the `prec`-width conceptual register. What matters to this in `+d` is that unary plus rounds `d` back (if needed) first to the most-significant `prec` digits. _Then_ `shift()/rotate()` are more obvious than not. But I'd still be surprised to see real code that knows what it's doing pass anything other than an integer. `shift()`, e.g., is emphatically not trying to multiply by a power of 10. It., and `rotate()`, are combinatorial operations on the individual digits.
