### ISSUE TITLE
Restore docstrings in `ssl`

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#126890]
# Bug report

### Bug description:

As mentioned [here](https://github.com/python/cpython/issues/124984#issuecomment-2477870588), apparently I stripped some of the docstrings while switching things over to argument clinic in the big SSL thread safety fix (GH-124993). 

I'm not certain how much needs to be restored, but I'll get to fixing this sometime this weekend or next week.

cc @JelleZijlstra, @neonene

### CPython versions tested on:

3.14, CPython main branch

### Linked PRs
* gh-127281
* gh-127513

**Comment by neonene** [comment]
Related: https://github.com/python/cpython/pull/113160#issuecomment-1859979037

**Comment by JelleZijlstra** [comment]
> I'm not certain how much needs to be restored

All of them, unless there's some specific reason not to. And even if then, they could be restored as comments.

**Comment by ZeroIntensity** [comment]
Yeah, but I don't know how many docstrings there were originally yet.

**Comment by encukou** [comment]
@ZeroIntensity, are you still planning to add these back?

> Yeah, but I don't know how many docstrings there were originally yet.

Nineteen or so:
```
$ git show 4c53b25 | grep '^-.*PyDoc' | wc -l
19
```

**Comment by ZeroIntensity** [comment]
I am! Sorry for the delay, I've gotten sidetracked with some other issues. I'll have plenty of time today to get this done.
