### ISSUE TITLE
Error in floor division

### ISSUE THREAD

**Issue by Sx4DoW** [python/cpython#126872]
# Bug report

### Bug description:

print(8 // 0.2)
print(8 / 0.2)

Expected output: 
40.0
40.0

Output:
39.0
40.0

why on earth does 8 // 0.2 return 39?

### CPython versions tested on:

3.11

### Operating systems tested on:

Windows

**Comment by rishi93** [comment]
Might help to read about IEEE 754. 0.2 is not exactly 0.2 in binary representation. It's a bit more, that's why the result comes out to 39.9999 something, and the floor of that is 39.

To get the behaviour that you're expecting, you should use `decimal.Decimal`

**Comment by JelleZijlstra** [comment]
See https://docs.python.org/3/faq/design.html#why-are-floating-point-calculations-so-inaccurate .

**Comment by aforwork-ctrl** [comment]
The same problem with 15.6//2.6. (a//b) may give a wrong result for some float a and b when(a/b) is really an integer number and so (a//b) must be exactly equal to (a/b).
To get correct results you can use the math.floor(a/b) instead of (a//b).
