### ISSUE TITLE
Emscripten support: Use es6 modules 

### ISSUE THREAD

**Issue by hoodmane** [python/cpython#126898]
We are in the future and ES6 module support is finally universal in mainstream JavaScript runtimes (Firefox was the straggler but finally added Module WebWorker support in v114 released on June 6 2023). They have many benefits, such as fewer global variables and more sanity. We should switch to using them.

cc @freakboy3742

### Linked PRs
* gh-126903

**Comment by sobolevn** [comment]
Thank you!
