### ISSUE TITLE
Add a API to start a coroutine.

### ISSUE THREAD

**Issue by ZTG0421** [python/cpython#126936]
# Feature or enhancement

### Proposal:

Add a new API to behave like `loop.run_until_complete(asyncio.sleep(0))`, which runs all tasks in the loop until the first `await`. This helps to return control to the main thread like in JavaScript, instead of returning to the event loop.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by issamhaimour** [comment]
> # Feature or enhancement
> 
> ### Proposal:
> 
> Add a new API to behave like `loop.run_until_complete(asyncio.sleep(0))`, which runs all tasks in the loop until the first `await`. This helps to return control to the main thread like in JavaScript, instead of returning to the event loop.
> 
> ### Has this already been discussed elsewhere?
> 
> This is a minor feature, which does not need previous discussion elsewhere
> 
> ### Links to previous discussion of this feature:
> 
> _No response_

**Comment by ZeroIntensity** [comment]
We already sort of have this. It's called an [eager task factory](https://docs.python.org/3/library/asyncio-task.html#eager-task-factory), which will immediately run a task until its first `await` upon creating it.

**Comment by ZTG0421** [comment]
My point is when executing all async task reaches the first await,exit the event loop.

**Comment by graingert** [comment]
I think it should be better to open a discussion on https://discuss.python.org/c/async-sig/20 first and show some example code of what sort of program would need this feature

**Comment by graingert** [comment]
Ah there's https://anyio.readthedocs.io/en/stable/api.html#anyio.wait_all_tasks_blocked

It's a bit of a hack, but if it were implemented directly in asyncio could be much nicer
