### ISSUE TITLE
fdb import error

### ISSUE THREAD

**Issue by ghassenTn** [python/cpython#126948]
# Bug report

### Bug description:

import fdb
ImportError: cannot import name 'resetlocale' from 'locale' (/usr/lib/python3.13/locale.py). Did you mean: 'setlocale'?

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by clintonroy** [comment]
https://docs.python.org/3/whatsnew/3.13.html#locale

**Comment by ghassenTn** [comment]
solved thanks
