### ISSUE TITLE
Crash in _PyXI_ApplyErrorCode()

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#126986]
# Crash report

### Bug description:

This is a problem in Python/crossinterp.c, as exposed by the _interpreters module.

reproducer:

1. interp is running as "main" in thread 1
2. thread 2 calls `_PyXI_Enter()`, which emits the `_PyXI_ERR_ALREADY_RUNNING` error code
3. thread 1 finishes
4. thread 2 calls `_PyXI_ApplyError()`
5. `_PyXI_ApplyError()` calls `_PyInterpreterState_FailIfNotRunning()` to raise the exception, but it doesn't raise anything

I noticed this while working on gh-126914.

### CPython versions tested on:

3.14

### Linked PRs
* gh-126988
* gh-126995
* gh-127112

**Comment by ZeroIntensity** [comment]
Affecting 3.13(t) as well:
```
$ ./python x.py
python: Python/crossinterp.c:988: _PyXI_ApplyErrorCode: Assertion `_PyInterpreterState_IsRunningMain(interp)' failed.
```
