### ISSUE TITLE
Update "credits" command output

### ISSUE THREAD

**Issue by StanFromIreland** [python/cpython#126911]
# Bug report

### Bug description:

```python
credits
```
Returns
`Thanks to CWI, CNRI, BeOpen.com, Zope Corporation and a cast of thousands
    for supporting Python development.  See www.python.org for more information.`

Which should be updated as the BeOpen.com domain has changed ownership and this command is always recommended by IDLE.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-126913
* gh-126973
* gh-126974

**Comment by maleycl** [comment]
Stan I apologize profusely; i was attempting to work on fixing my account with different services, becayse as yoiu can see i've had a dair amount of issues
 But right now my computer is entIy under attack? I have been blocked and logged out of everything as soon as it was being seen that I was clooking at cloudflare

**Comment by terryjreedy** [comment]
Seems like a good idea.

>  this command is always recommended by IDLE

IDLE's opening splash lines are currently the same as the standard REPL, though I intend to modify the ending "Type" line.

**Comment by hugovk** [comment]
Thank you!
