### ISSUE TITLE
Make `pyvenv.cfg`-relocation part of the interpreter initialization instead of the `site` module

### ISSUE THREAD

**Issue by FFY00** [python/cpython#126985]
# Feature or enhancement

### Proposal:

Currently, the mechanism behind virtual environments is implemented in the `site` module. This means that disabling the `site` initialization (passing `-S`) disables virtual environments.

I would like to move the virtual environment detection from `site` to the interpreter initialization (`getpath`), which would essentially consist of setting `sys.prefix` to `sys.exec_prefix` to the virtual environment prefix in `getpath`.

The motivation is the same as GH-126793, the same UX example applies. Running `python -S -m ensurepip` inside a virtual environment would install to the system, instead of the virtual environment.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-126987
* gh-127968

**Comment by befeleme** [comment]
Cross-referencing for visibility: https://github.com/python/cpython/issues/128779 - this has started to happen since Python 3.14.0a3
