### ISSUE TITLE
Missing Py_DECREF for load_build in _pickle.c

### ISSUE THREAD

**Issue by Legoclones** [python/cpython#126991]
# Bug report

### Bug description:

In the `load_build` function of [`Modules/_pickle.c`](https://github.com/python/cpython/blob/3.11/Modules/_pickle.c#L5168), if setting a value in a dictionary fails, the `dict` variable does not have its reference counter decreased.

Pull request was made at https://github.com/python/cpython/pull/126990

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

### Linked PRs
* gh-126990
* gh-127018
* gh-127019
* gh-127031
* gh-127063
* gh-127064

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @Legoclones. #127031 adds a test for this leak, as well as coverage tests for other corner cases.
