### ISSUE TITLE
Add retry function to Python standard library

### ISSUE THREAD

**Issue by jude253** [python/cpython#126927]
# Feature or enhancement

### Proposal:

I often find myself adding retry functionality in many different places.  I think it would be super helpful if there was retry functionality in the python standard library by default.  I think this is super helpful with API calls.

Ideally, it would have nice and easy syntax with good enough default values that can be further configured if needed.

Example: 
```python

@retry
def user_function(arg1, arg2, kwarg='something'):
    pass

```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-126928
* gh-126943

**Comment by hugovk** [comment]
Major feature proposals should be discussed on [Discourse](https://discuss.python.org/c/ideas/6) before opening a GitHub issue. Please open a topic over there and we can re-open this when it's clear there's support for this idea. Thank you.
