### ISSUE TITLE
Replacing "Windows only: ..." with the `.. availability:: Windows` directive in `ctypes` doc.

### ISSUE THREAD

**Issue by junkmd** [python/cpython#127082]
# Documentation

This is a follow-up to gh-126615.  
In the `ctypes` documentation, the supported platforms were previously described in plain text.  
This will be replaced with a more modern approach using directives.

### Linked PRs
* gh-127099
* gh-127144
* gh-127145

**Comment by Eclips4** [comment]
Thank you @junkmd!
