### ISSUE TITLE
Outdated `socket.NETLINK_*` constants 

### ISSUE THREAD

**Issue by tungol** [python/cpython#127072]
# Feature or enhancement

### Proposal:

When working through the constants in `socket` for typeshed, I found that these appear to be obsolete:

```python
NETLINK_ARPD: int  # linux 2.0 to 2.6.12 (EOL August 2005)
NETLINK_ROUTE6: int  # linux 2.2 to 2.6.12 (EOL August 2005)
NETLINK_SKIP: int  # linux 2.0 to 2.6.12 (EOL August 2005)
NETLINK_TAPBASE: int  # linux 2.2 to 2.6.12 (EOL August 2005)
NETLINK_TCPDIAG: int  # linux 2.6.0 to 2.6.13 (EOL December 2005)
NETLINK_W1: int  # linux 2.6.13 to 2.6.17 (EOL October 2006)
```

The netlink constants are defined in `include/linux/netlink.h` on linux 2.0 to 3.6. Starting in 3.7 they moved to `include/uapi/linux/netlink.h`. I've annotated these with the versions of linux where I was able to find them, and confirmed that they're not present in FreeBSD's Netlink implementation either.

I suspect these can be safely removed, but I'm not terribly familiar with Netlink myself.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127256

**Comment by rruuaanng** [comment]
If you wish, they can be removed. Currently they are no longer present in `uapi/linux/netlink.h` in the master branch. But if I could, I'd like this to be given to me ;)

**Comment by tungol** [comment]
I have no intention to open an MR related to this issue myself, if that's what you mean. If you know what the correct thing to do here is, please go ahead!

If you haven't seen it, you might also be interested in this related issue I opened: https://github.com/python/cpython/issues/127069

**Comment by rruuaanng** [comment]
I'll submit a PR to remove them soon. Netlink first appeared in linux1.3, and if I remember correctly. As far as I can remember, no other os to support `netlink` (FreeBSD only partially compatible.)

**Comment by picnixz** [comment]
Closing since completed.
