### ISSUE TITLE
Remove lazy dictionary tracking

### ISSUE THREAD

**Issue by markshannon** [python/cpython#127010]
# Feature or enhancement

### Proposal:

In order to reduce the overhead of cycle GC detection for objects that cannot be part of cycles, we lazily untrack tuples and dictionary that only refer to objects that cannot be part of a cycle.

This is fine for tuples, but dictionaries are mutable, so we need to check every time a dictionary is modified whether it needs to be tracked.

Since most objects no longer have a `__dict__` dictionary, the complexity and overhead of this lazy tracking is not worth the small benefit in the cycle GC.

This was originally implemented in https://github.com/python/cpython/pull/126502, but is largely orthogonal to the main purpose of that PR, so should be implemented separately.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127027

**Comment by nascheme** [comment]
This sounds like a good idea to me.
