### ISSUE TITLE
Add missing description for codes in `http.HTTPStatus`

### ISSUE THREAD

**Issue by donbarbos** [python/cpython#127089]
# Bug report

### Bug description:

We have Enum of **`62`** HTTP status codes. They stores in `http.HTTPStatus` class and **`14`** of them don't have description field.
I think it is not-obvious behavior when calling the description field, one code returns text and another returns an empty string:
```python
import http
assert http.HTTPStatus.PROCESSING.description == ''
assert http.HTTPStatus.OK.description == 'Request fulfilled, document follows'
```

Path file: [`./Lib/http/__init__.py`](https://github.com/python/cpython/blob/main/Lib/http/__init__.py)
List of codes with empty description:
```python
    PROCESSING = 102, 'Processing'
    EARLY_HINTS = 103, 'Early Hints'
    MULTI_STATUS = 207, 'Multi-Status'
    ALREADY_REPORTED = 208, 'Already Reported'
    IM_USED = 226, 'IM Used'
    UNPROCESSABLE_CONTENT = 422, 'Unprocessable Content'
    LOCKED = 423, 'Locked'
    FAILED_DEPENDENCY = 424, 'Failed Dependency'
    TOO_EARLY = 425, 'Too Early'
    UPGRADE_REQUIRED = 426, 'Upgrade Required'
    VARIANT_ALSO_NEGOTIATES = 506, 'Variant Also Negotiates'
    INSUFFICIENT_STORAGE = 507, 'Insufficient Storage'
    LOOP_DETECTED = 508, 'Loop Detected'
    NOT_EXTENDED = 510, 'Not Extended'
```

*I am ready to send PR*

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-127100

**Comment by picnixz** [comment]
I think it's good for completeness but is it possible for the strings to match the RFC if any?

**Comment by donBarbos** [comment]
I have not seen such RFC and I think that the description was created by the developers. but I can try to search for the necessary RFCs and if I don't find them I will inform you

**Comment by picnixz** [comment]
IIRC those codes are described in rfc2616. If there is no short description, let's just use their name.

**Comment by donBarbos** [comment]
I didn't find any mentions of the description in the RFCs that were specified in this file (there are only phrases):
https://github.com/python/cpython/blob/1629d2ca56014beb2d46c42cc199a43ac97e3b97/Lib/http/__init__.py#L7-L25

I found only commit which was made in 2014 and where the description field was added. But there are no explanations:
https://github.com/python/cpython/commit/e4db76967d7fb0ec0f5a98a9603ca5563f4a8320#diff-7b8ddb05aa75662657f99bf3fcd7778a8f3b37083edafe2c274d42edf6ea05f5R28

So I send a PR where the description same like phrase?

**Comment by donBarbos** [comment]
@picnixz could you take a look at my PR #127100?, i was not sure that i need to add `Misc/NEWS.d/...` file
