### ISSUE TITLE
FileIO Strace test fails on Gentoo (test_fileio test_syscalls_read) 

### ISSUE THREAD

**Issue by cmaloney** [python/cpython#127076]
# Bug report

### Bug description:

Initially reported in PR comments: https://github.com/python/cpython/pull/123413

There looks like three cases to investigate/work on from this:

1. Gentoo + `musl` -> there is an extra mmap call
2. Gentoo + sandbox -> many additional calls (Probably an environment to disable in if can detect)
3. Should there be a more general switch to disable?

relates to: gh-120754

My first thought for 1 is `mmap` could generally be filtered out (it has shown up moderately frequently in my testing on other systems, generally used for memory allocation in wrapping). Working on setting up a Gentoo environment to test / experiment / investigate locally and develop patches.

cc:  @mgorny, @vstinner, @gpshead, @hauntsaninja

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-127086
* gh-127088

**Comment by cmaloney** [comment]
@mgorny good to close / Gentoo build working with latest main (and hopefully that will mean with next alpha as well)?

**Comment by mgorny** [comment]
Yes, looks like these tests now pass on musl, and are skipped in sandbox. Thanks a lot!
