### ISSUE TITLE
[spam]

### ISSUE THREAD

**Issue by Rafaegsbhsg** [python/cpython#127075]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
BBOO

### CPython versions tested on:

3.14, CPython main branch

**Comment by Rafaegsbhsg** [comment]
Bbbb

**Comment by hugovk** [comment]
@python/organization-owners Please block @Rafaegsbhsg (see also https://github.com/python/cpython/issues/127074).

**Comment by JacobCoffee** [comment]
Done
