### ISSUE TITLE
argparse: remove the type, choices, and metavar parameters but still in the documentation.

### ISSUE THREAD

**Issue by loan75** [python/cpython#127013]
# Documentation

As indicated in the what's new of python3.14, Remove the type, choices, and metavar parameters of argparse.
https://docs.python.org/3.14/whatsnew/3.14.html#id1

But these arguments are still present in the documentation:
https://docs.python.org/3.14/library/argparse.html#type

i guess they should be removed.

**Comment by ericvsmith** [comment]
They were only removed for `action=BooleanOptionalAction`, not in general. But I don't see that documented for `BooleanOptionalAction`.

**Comment by loan75** [comment]
Indeed, I didn't fully understand the documentation! My bad.
Thank your for your quick response.
