### ISSUE TITLE
`<not running>` console spam when running tests

### ISSUE THREAD

**Issue by colesbury** [python/cpython#127152]
Since gh-126855, running tests, such as via `make test` now prints out lots of lines like:

* https://github.com/python/cpython/pull/126855

> `0:00:44 load avg: 17.49 [477/480] test.test_multiprocessing_forkserver.test_processes passed (36.9 sec) -- running (82): <not running> (44.1 sec), <not running> (34.7 sec), <not running> (39.3 sec), <not running> (38.9 sec), <not running> (34.0 sec), <not running> (36.8 sec), <not running> (38.7 sec), <not running> (42.4 sec), <not running> (44.3 sec), <not running> (44.6 sec), <not running> (44.6 sec), <not running> (33.6 sec), test.test_multiprocessing_spawn.test_processes (43.9 sec), <not running> (34.1 sec), <not running> (33.9 sec), <not running> (43.7 sec), <not running> (44.6 sec), <not running> (44.1 sec), <not running> (37.6 sec), <not running> (36.7 sec), <not running> (44.6 sec), <not running> (43.8 sec), <not running> (35.9 sec), <not running> (38.4 sec), <not running> (36.3 sec), test.test_concurrent_futures.test_wait (44.1 sec), <not running> (44.1 sec), <not running> (43.9 sec), <not running> (44.5 sec), <not running> (34.6 sec), <not running> (43.3 sec), <not running> (42.9 sec), <not running> (37.7 sec), <not running> (34.5 sec), <not running> (33.6 sec), <not running> (35.2 sec), <not running> (36.9 sec), <not running> (33.6 sec), <not running> (33.4 sec), <not running> (37.1 sec), <not running> (33.4 sec), <not running> (34.0 sec), <not running> (38.1 sec), <not running> (40.5 sec), <not running> (40.0 sec), <not running> (39.9 sec), <not running> (43.9 sec), <not running> (44.5 sec), <not running> (44.5 sec), <not running> (39.0 sec), <not running> (34.2 sec), <not running> (35.6 sec), <not running> (36.3 sec), <not running> (43.0 sec), <not running> (33.5 sec), <not running> (35.5 sec), <not running> (43.5 sec), <not running> (42.5 sec), <not running> (40.8 sec), <not running> (33.7 sec), <not running> (39.5 sec), test_subprocess (34.9 sec), <not running> (33.4 sec), <not running> (35.2 sec), <not running> (44.0 sec), <not running> (35.8 sec), <not running> (44.0 sec), <not running> (41.6 sec), <not running> (34.0 sec), <not running> (36.2 sec), <not running> (38.9 sec), <not running> (40.5 sec), <not running> (43.2 sec), <not running> (33.6 sec), <not running> (36.7 sec), <not running> (39.2 sec), <not running> (34.8 sec), <not running> (37.8 sec), <not running> (39.3 sec), <not running> (34.3 sec), <not running> (34.2 sec), <not running> (34.4 sec)`

I think the `<not running>` prints are unintentional.

cc @sobolevn

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/127153 to fix the regression.
