### ISSUE TITLE
recommend what to use instead of asyncio.get_event_loop in 3.14 what's new

### ISSUE THREAD

**Issue by graingert** [python/cpython#127174]
Could you please mention what should be used instead?

_Originally posted by @hroncok in https://github.com/python/cpython/pull/126354#discussion_r1853686937_
            

### Linked PRs
* gh-127640

**Comment by graingert** [comment]
Currently:

```python
import asyncio

async def amain():
    await asyncio.sleep(0)
    print("slept")

asyncio.get_event_loop().run_until_complete(amain())
```

Will fail on 3.14

Code should use 

```python
import asyncio

async def amain():
    await asyncio.sleep(0)
    print("slept")

asyncio.run(amain())
```

Instead

**Comment by graingert** [comment]
It may be that a user will need to interleave synchronous code with calls into and back out of the event loop in which case `with asyncio.Runner() as runner: runner.run(...)` should be used

**Comment by graingert** [comment]
It's the what's new section

**Comment by kumaraditya303** [comment]
@graingert Would you like to send a PR for it? I'll review it.

**Comment by graingert** [comment]
I'll give it a go, feel free for someone else to do it if it's not done by next week
