### ISSUE TITLE
Turn off PGO for JIT CI

### ISSUE THREAD

**Issue by brandtbucher** [python/cpython#127154]
I don't think we need PGO turned on in JIT CI for non-debug jobs. It's mostly just a waste of time, and doesn't really give us any additional information.

@mdboom, I know that the Windows PGO builds were a nice canary for "breaking" ceval.c under MSVC (since it's not tested in CI or any buildbot), but I figure our weekly benchmarking runs are a good enough "buildbot" for that, so we don't need to run it all the time on PRs.

@savannahostrowski, want to take this?

### Linked PRs
* gh-127212

**Comment by mdboom** [comment]
Yeah, I agree that PGO+JIT together doesn't add much value.

Historically, I don't think our benchmarking stuff has been a soon-enough canary for MSVC, so I'd still like to see a buildbot specifically test that configuration.  I think I'll file a separate bug for that -- no need for that to hold this up.
