### ISSUE TITLE
reporting "cannot access local variable ... where it is not associated with a value" in the wrong place when using += 

### ISSUE THREAD

**Issue by inhahe** [python/cpython#127292]
# Bug report

### Bug description:

```
>>> i = 1
>>> def a():
...   print(i)
...
>>> a()
1
>>> i = 1
>>> def a():
...   i = 2
...   print(i)
...
>>> a()
2
>>> i = 1
>>> def a():
...   i += 1
...   print(i)
...
>>> a()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in a
UnboundLocalError: cannot access local variable 'i' where it is not associated with a value
```
Sorry if this isn't actually a bug, but I can't believe this was intentional...it makes no sense.

### CPython versions tested on:

3.11, 3.13

### Operating systems tested on:

Windows

Edit:
Okay, so I did some more testing and realized that
```
i = 1
def a():
  i = i + 1
  print(i)
```
also results in this error, but at the `i = i + 1` line and not the `print(i)` line.
So I guess the problem is just a clash between the local name and the global name.
But it's confusing that when you use `+=` it results in the variable no longer being global OR local and gives an error the next time you try to use it..
In my actual use case, it highlighted the variable in a statement unrelated to the assignment like 10 lines down from the assignment.

**Comment by inhahe** [comment]
Okay, so I did some more testing and realized that
```
i = 1
def a():
  i = i + 1
  print(i)
```
also results in this error.
So I guess the problem is just a clash between the local name and the global name.
But it's confusing that when you use += it results in the variable no longer being global OR local and gives an error the next time you try to use it..

**Comment by skirpichev** [comment]
Why do you think it's a bug?

Documentation [says](https://docs.python.org/3.13/reference/executionmodel.html#binding-of-names): "If a name is bound in a block, it is a local variable of that block, unless declared as [nonlocal](https://docs.python.org/3.13/reference/simple_stmts.html#nonlocal) or [global](https://docs.python.org/3.13/reference/simple_stmts.html#global)."

In your last example you just do ``i = i + 1`` explicitly.  But traceback from the first example (at least for 3.13) looks ok for me:
```pycon
>>> def a():
...     i += 2
...     print(i)
...     
>>> a()
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    a()
    ~^^
  File "<python-input-3>", line 2, in a
    i += 2
    ^
UnboundLocalError: cannot access local variable 'i' where it is not associated with a value
```

I don't think it's a bug.

**Comment by inhahe** [comment]
> Why do you think it's a bug?
> 
> Documentation [says](https://docs.python.org/3.13/reference/executionmodel.html#binding-of-names): "If a name is bound in a block, it is a local variable of that block, unless declared as [nonlocal](https://docs.python.org/3.13/reference/simple_stmts.html#nonlocal) or [global](https://docs.python.org/3.13/reference/simple_stmts.html#global)."
> 
> In your last example you just do `i = i + 1` explicitly. But traceback from the first example (at least for 3.13) looks ok for me:
> 
> ```
> >>> def a():
> ...     i += 2
> ...     print(i)
> ...     
> >>> a()
> Traceback (most recent call last):
>   File "<python-input-4>", line 1, in <module>
>     a()
>     ~^^
>   File "<python-input-3>", line 2, in a
>     i += 2
>     ^
> UnboundLocalError: cannot access local variable 'i' where it is not associated with a value
> ```
> 
> I don't think it's a bug.

I realized it's not so much a bug but reporting the error in a weird place (for me) when using +=. It seems for you it reported it where the assignment is, for me it reported it later on. Not sure why it seems different for us.

**Comment by skirpichev** [comment]
> I see it did say line 2 for you, which is the same as it said for me

It's correct.  Line 2 is not the print statement.  It's augmented assignment.  Don't forgot the function definition line (and lines counts from 1, not 0).

Here is an example on py3.8:
```pycon
>>> i = 1
>>> def a():
...     print(1)
...     i += 1
... 
>>> a()
1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in a
UnboundLocalError: local variable 'i' referenced before assignment
```

**Comment by inhahe** [comment]
Oh, right. 
```
>>> import mylexer
>>> print(mylexer.parse("""a = "[123]+?"\nb = '34'""", "341"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\temp\mylexer.py", line 22, in parse
    if ignore:
       ^^^^^^
UnboundLocalError: cannot access local variable 'ignore' where it is not associated with a value
```

**Comment by inhahe** [comment]
> Yes, you are correct, guessing that it's because you referenced _local_ `i` before in code (with augmented assignment). Here is a simple example:

Yeah, it's definitely because of the `ignore += rule`. I just think the error should have occurred at the assignment instead of at the `if ignore:` to make it more intuitive, and also more consistent `i = i + 1` and `i += 1` where i is an integer.

**Comment by skirpichev** [comment]
That's because in you case ``+=`` operation had no chance to be executed.  Try to change in my example f(0) to f(1).

**Comment by inhahe** [comment]
I think it was executed. One reason is that in debugging the problem I had commented out that line and I no longer got the error. Another reason is that if that line isn't executed then it's equivalent to
```
i = 1
def a():
   print(i)
```
which is perfectly valid and doesn't render an error.

**Comment by skirpichev** [comment]
> I think it was executed.

It *might* be executed, but not with example input which you have provided.  Try a different one - and you will get a different error, just as for my toy case f(0) vs f(1).

> One reason is that in debugging the problem I had commented out that line and I no longer got the error.

That's because in other places you only referenced the ``ignore`` variable, so it binds to the global.  But when you add ``+=`` (regardless where in the function) - it's can't be interpreted as a global anymore (you can change this, using global statement).

> Another reason is that if that line isn't executed then it's equivalent to

The compiled code will be *not* equivalent.  Try to comment out that ``+=`` operation and compare the dis output for your module.

**Comment by inhahe** [comment]
Oh, so you're saying it behaves differently depending on whether the +=
line is in there or not regardless of whether it's actually in the code
path? Ok, interesting/weird.

**Comment by skirpichev** [comment]
If you read quoted above chapter "4. Execution model" - that shouldn't surprise you.  What would be weird - expect that actual code for a function block will depend on it's input.
