### ISSUE TITLE
list imaplib in `pip list` package list

### ISSUE THREAD

**Issue by AMDphreak** [python/cpython#127273]
# Feature or enhancement

### Proposal:

when checking whether piplib is installed, I shouldn't need to look at 5 different web pages to figure out that it is a native library and will not be listed in the local packages list with `pip list`. I wasted my time and effort installing `imap` because imaplib is both not listed and not intuitively named.

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

This has not been discussed elsewhere. Make your tools discoverable and auditable from a minimal knowledge perspective.

**Comment by Eclips4** [comment]
Hello!
The `imaplib` module is a part of Python's stdlib. `pip list` is showing modules that have been installed via pip, when `imaplib` is certainly isn't one of them. You can discover more capabilities of Python's stdlib here: https://docs.python.org/3/library/
