### ISSUE TITLE
`ExtensionFileLoader.load_module` aborts when initialized with a path containing null-bytes

### ISSUE THREAD

**Issue by devdanzin** [python/cpython#127208]
# Crash report

### What happened?

It's possible to abort a debug build by initializing a `_frozen_importlib_external.ExtensionFileLoader` with a path containing null-bytes, then calling `load_module()`:

```python
import _frozen_importlib_external

_frozen_importlib_external.ExtensionFileLoader("a", "\x00").load_module(None)
```
Abort message:
```
python: Python/import.c:939: hashtable_key_from_2_strings: Assertion `strlen(key) == size - 1' failed.
Aborted
```
Found using [fusil](https://github.com/devdanzin/fusil) by @vstinner.

### CPython versions tested on:

3.12, 3.13, 3.14, CPython main branch

### Operating systems tested on:

Linux

### Output from running 'python -VV' on the command line:

Python 3.14.0a2+ (heads/main:0af4ec3, Nov 20 2024, 21:45:19) [GCC 13.2.0]

### Linked PRs
* gh-127400
* gh-127418
* gh-127419

**Comment by devdanzin** [comment]
Another way to trigger:
```python
>>> import _imp
>>> class n:
...   name = "A"
...   origin = "\x00"
...
>>> _imp.create_dynamic(n, 1)
python: Python/import.c:939: hashtable_key_from_2_strings: Assertion `strlen(key) == size - 1' failed.
Aborted
```

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/127400 to fix the issue.

**Comment by picnixz** [comment]
Closing since completed and backported.
