### ISSUE TITLE
Correct name of zconf.in.h is zconf.h.in

### ISSUE THREAD

**Issue by smurav** [python/cpython#127248]
The file zconf.in.h should be renamed to zconf.h.in (https://github.com/python/cpython-source-deps/blob/4dc98e1909830e2bdc2a9cc2236e3c5d5037335b/zconf.h.in).

https://github.com/python/cpython/blob/c595eae84c7f665eced09ce67a1ad83b7574d6e5/PCbuild/pythoncore.vcxproj#L418

### Linked PRs
* gh-127249

**Comment by ZeroIntensity** [comment]
PR welcome :)
