### ISSUE TITLE
Confusing single quotes and/or apostrophe

### ISSUE THREAD

**Issue by funkyrailroad** [python/cpython#127265]
# Documentation

The first apostrophe threw me off, and I realized it doesn't make sense for the second apostrophe to indicate the possessive case either. Then I realized the "apostrophes" are supposed to be single quotes around the word `arrow`. Nowhere else in the docs is the word `arrow` surrounded in single quotes, so I think they should be removed for consistency.

### Linked PRs
* gh-127267
* gh-127268
* gh-127269

**Comment by zware** [comment]
It's not clear to me what you're reporting; can you please link to where you're seeing this issue?

**Comment by funkyrailroad** [comment]
It's in section 8.1 https://docs.python.org/3/tutorial/errors.html

Here's a PR in progress:

https://github.com/python/cpython/pull/127267

**Comment by zware** [comment]
Thanks for the report and patch!  This is now fixed in 3.12 and later.
