### ISSUE TITLE
sys.set_int_max_str_digits ValueError Message is Inaccurate

### ISSUE THREAD

**Issue by amhamor** [python/cpython#127238]
The sys.set_int_max_str_digits ValueError message is shown to be inaccurate in the following Python interpreter execution sequence:

```
>>> import sys
>>> sys.set_int_max_str_digits(maxdigits=639)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: maxdigits must be 0 or larger than 640
>>> sys.set_int_max_str_digits(maxdigits=640)
>>>
```

The sys.set_int_max_str_digits ValueError message states that "maxdigits" must be larger than "640." However, "sys.set_int_max_str_digits(maxdigits=640)" is a valid statement for Python to execute. Because argument "640" is valid for built-in function "sys.set_int_max_str_digits" and 640 is not larger than 640, this results in a discrepancy between what the ValueError message states as true and what is actually true.

### Linked PRs
* gh-127241

**Comment by ZeroIntensity** [comment]
cc @skirpichev

**Comment by terryjreedy** [comment]
Passing 639 raises the ValueError, so 640 is the lower limit as [documented](https://docs.python.org/3/library/stdtypes.html#int-max-str-digits): "The lowest limit that can be configured is 640 digits as provided in [sys.int_info.str_digits_check_threshold](https://docs.python.org/3/library/sys.html#sys.int_info).  Indeed
```
sys.int_info
sys.int_info(bits_per_digit=30, sizeof_digit=4, default_max_str_digits=4300, str_digits_check_threshold=640)
```
So, /larger/at least/ in the error message, wherever it lives.  (I am guessing that 640 = 8 lines of 80 digits.)

**Comment by skirpichev** [comment]
> I am guessing that 640 = 8 lines of 80 digits.

I would guess it's just a joke, referring to other famous quote (or to the myth about...) :D  In ``Include/internal/pycore_long.h`` we have "640 digits should be enough for anyone." - gps

> So, /larger than/at least/ in the error message

Here is a small pr, doing something like that: https://github.com/python/cpython/pull/127241
