### ISSUE TITLE
concurrent.future.thread._python_exit: continuing blocking while exceptions occureded on windows.

### ISSUE THREAD

**Issue by SekaiArendelle** [python/cpython#127282]
# Bug report

### Bug description:

on windows, Thread.join is sometimes terrible because exception can not interrupt its blocking.

```python
import threading
import time

def task():
    while True:
        time.sleep(1)

t = threading.Thread(target=task)
t.start()
t.join()
```
you can't exit this program by Ctrl+C on windows.

we can easily fix it to let exceptions been raisen.

```py

import threading
import time

def task():
    while True:
        time.sleep(1)

t = threading.Thread(target=task)
t.start()
while t.is_alive():
    t.join(timeout=2)
```

this is what I want to fix in _python_exit, which been registered in atexit-call and it costs me a lot of time to realize what's problem with my program.

I'll send pr soon.

### CPython versions tested on:

3.9, 3.10, 3.11, 3.12

### Operating systems tested on:

Windows

### Linked PRs
* gh-127283

**Comment by ZeroIntensity** [comment]
cc @zooba as the Windows expert. The reproducer can be killed by just CTRL+C-ing twice on Linux.

**Comment by zooba** [comment]
I would prefer to make [`PyThread_join_thread`](https://github.com/python/cpython/blob/db5c5763f3e3172f1dd011355b41469770dafc0f/Python/thread_nt.h#L233-L239) aware of `_PyOS_SigintEvent` so that it can abort its wait.

**Comment by GoodenoughPhysicsLab** [comment]
> That said, I am certain we have discussed this before, and presumably it's not so easy. I don't remember exactly why, but there'll be an issue somewhere with details.

No matter how difficult it is, I want to have a try.

**Comment by GoodenoughPhysicsLab** [comment]
I'm too busy near by. But, I surprisingly found that the problem of `Thread.join` have been solved when I was trying to solve it this afternoon. Therefore, I'll close this issue. I really thanks to people who have solved this problem.
