### ISSUE TITLE
Unable to access any source downloads from python.org

### ISSUE THREAD

**Issue by zyd14** [python/cpython#127307]
# Bug report

### Bug description:

We regularly download source distributions from python.org/ftp to initialize clusters with and all the sudden we're seeing Access Denied errors. All the links from https://www.python.org/downloads/ seem to lead to python.org/ftp, which all give Access Denied errors. This seems like quite a big deal, I'm sure I'm not the only one expecting to be able to pull these distributions.

First seen around 11/26/2024 21:53 pm UTC

### CPython versions tested on:

3.13
3.10

### Operating systems tested on:

macOS

**Comment by nchepanov-plaid** [comment]
We are seeing this too. First failure 2024-11-26 18:11:52 UTC, a different version of Python than what's reported above

**Comment by miikka-johnson-infinitusai** [comment]
seeing as well - https://www.python.org/ftp/python/3.11.10/Python-3.11.10.tgz

**Comment by zyd14** [comment]
Seeing it in requests from London and from central US

**Comment by brianschubert** [comment]
Cross repo duplicate: https://github.com/python/pythondotorg/issues/2663

**Comment by Yadan-Wei** [comment]
Same issue here, cannot access any version.

**Comment by danieljaffe** [comment]
My team is having the same issue downloading any version of Python from https://www.python.org/ftp/python/

**Comment by gaboth22** [comment]
Being impacted by this.

**Comment by hauntsaninja** [comment]
cc @JacobCoffee in case you know how to route this :-)

**Comment by tjhorner** [comment]
I am able to download source tarballs again.

**Comment by Yadan-Wei** [comment]
I am able to download 3.9.20 too.

**Comment by zyd14** [comment]
I'm able to pull downloads again too for 3.10 and 3.13. I'll close this since it seems to be fixed

**Comment by JacobCoffee** [comment]
I am out today but from what I can (loosely) gather it was due to a DDOS issue
