### ISSUE TITLE
Document `traceback.print_list`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#127347]
`traceback.print_list` is currently [undocumented](https://docs.python.org/3.14/library/traceback.html), let's fix that! I'll send a PR shortly :)

### Linked PRs
* gh-127348
* gh-127569
* gh-127570

**Comment by tomasr8** [comment]
You're right, I should've done some research to understand why it's undocumented. I'll check tomorrow :)

**Comment by tomasr8** [comment]
So I did some code archaeology and the function was added in https://github.com/python/cpython/commit/dcc057a79360cd24837143acd53d2da551b62920 together with `format_list`. Neither were documented in this commit. `format_list` and a bunch of other functions (except for `print_list`) were documented (in `Doc/lib/libtraceback.text`) two years later in https://github.com/python/cpython/commit/bca1207ac8f2faeb990f6fe6be1441358a394d50. The docs were then migrated from tex to rst in https://github.com/python/cpython/commit/116aa62bf54a39697e25f21d6cf6799f7faa1349. To me this just seems like an unintentional omission so I think it makes sense to document it. Not sure if we should add `versionadded` (can we for such an old function?) or a What's New entry.

> What is the difference with `format_list()`?

`print_list` is a wrapper on top of `format_list` which directly prints the stack trace.

**Comment by serhiy-storchaka** [comment]
What about `__all__`. `format_list` was not initially in `__all__`.

**Comment by Eclips4** [comment]
> What about `__all__`. `format_list` was not initially in `__all__`.

A bunch of `__all__` were added in 40fc160, and it seems like an unintentional omission to me. (`print_last` and `print_list` sound pretty similar, so it's easy to omit one of them, I guess.)

**Comment by serhiy-storchaka** [comment]
Thank you for your investigation. Let document that function, but only add it to `__all__` in main (because it may be a breaking change). No versionadded is needed if it was here before 3.0.

**Comment by StanFromIreland** [comment]
This issue can be closed. A PR has been merged and just backports are left.

**Comment by tomasr8** [comment]
> This issue can be closed. A PR has been merged and just backports are left.

The backports still require some manual work, I'd prefer to keep this open until they are merged as well :)
