### ISSUE TITLE
PyType_HasFeature may dereference a NULL pointer

### ISSUE THREAD

**Issue by alonrs** [python/cpython#127320]
# Bug report

### Bug description:

In `Modules/_testcapi/list.c` [`list_clear`](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Modules/_testcapi/list.c#L43) function. `NULLABLE(obj)` may set `obj` to NULL. Then, it calls [PyList_Clear](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Objects/listobject.c#L1409)
which in turn calls [PyList_Check](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Include/listobject.h#L24) and then [PyType_FastSubclass](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Include/object.h#L776) that calls [PyType_HasFeature](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Include/object.h#L760) with `type = NULL`, which is derefernced [here](https://github.com/python/cpython/blob/6d3b5206cfaf5a85c128b671b1d9527ed553c930/Include/object.h#L770).

A similar phenomenon happens in other `Modules/_testcapi/list.c` functions as well.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
I think it's meant to allow testing for crashes. There should be some comments saying that we have CRASH(...). It's just that we have no way to pass NULL to the CAPI from Python except by saying that None is equivalent to NULL for the specific test.

cc @encukou for confirmation

**Comment by encukou** [comment]
Yes, you can use `_testcapi.list_clear(None)` to see what happens if you call `PyList_Clear(NULL)`. You get a crash. Both are the intended behaviour :)
