### ISSUE TITLE
Add support for OpenSSL 3.4

### ISSUE THREAD

**Issue by encukou** [python/cpython#127330]
# Feature or enhancement

OpenSSL 3.4 is out and it needs:
- new error information
- adding to multissltests

I plan to document what I learned about the process in `make_ssl_data.py` and point to that from all the places that need changing.

### Linked PRs
* gh-127331
* gh-139603

**Comment by asvetlov** [comment]
@encukou Is the issue complete?
Could we close it?

**Comment by encukou** [comment]
Yes, thank you for the follow-up.
