### ISSUE TITLE
Non-`None` return value from generator should throw RuntimeError

### ISSUE THREAD

**Issue by jvm-pangea** [python/cpython#127306]
# Bug report

### Bug description:

```python

def y1(*args):
    return args

def y2(*args):
    return args
    yield 3

print("y1: " + str(list(y1(1, 2, 3, 4))))
print("y2: " + str(list(y2(1, 2, 3, 4))))

```

While the `yield` in `y2` is unreachable (this happened to me while re-writing a function and leaving what I thought was dead code at the end), y2 is considered a Generator, and iterating over it produces an immediate `StopIteration` error with `args` as the argument, which manifests as an empty iterator.

I can't imagine a good reason to create a `StopIteration` exception with a non-`None` argument. With a `None` argument, this signals the basic case where a Generator is returning an empty iterator.

Consider throwing `RuntimeError` when `StopIteration` is raised with a non-`None` valued error when calling `next` to prevent this confusing behaviour.

### CPython versions tested on:

3.10

### Operating systems tested on:

macOS

**Comment by brianschubert** [comment]
Hi jvm-pangea, using `return` in generators is an intentional feature. You can see [PEP 380](https://peps.python.org/pep-0380/) for some of the original motivation and use cases.

**Comment by nineteendo** [comment]
This feels like a problem for a linter to flag.

**Comment by jvm-pangea** [comment]
PEP 380 will take some time for me to grok, it's pretty dense.

Is there no way to know when executing the byte-code that you're handling a `StopIteration` in the context of a `yield from` (where it is expected) vs. in a naked generator where the non-`None` valued exception would clearly be problematic?

**Comment by picnixz** [comment]
I agree that this is more a linter issue rather than a core issue. If you want to change the current behaviour a PEP is likely needed or at least a d.p.o thread (https://discuss.python.org/c/ideas/6).

**Comment by jvm-pangea** [comment]
Opened discussion:

https://discuss.python.org/t/foot-gun-no-runtimeerror-on-non-none-return-from-generator-outside-of-yield-from/72579

**Comment by ZeroIntensity** [comment]
Per DPO, there's nothing we can do :(
