### ISSUE TITLE
multiline input in terminal

### ISSUE THREAD

**Issue by RustoMCSpit** [python/cpython#127379]
# Feature or enhancement

### Proposal:

put simply, i need to regularly input multiple lines into my terminal and have python interpret that as is. for an oversimplified example:

Enter your groceries: kiwi
apple
banana
orange

yes, i know there are workarounds such as while loops or sys.stdin.readlines() but those have cons and dont exactly work as intended. for example, sys.stdin.readlines() would require me to only have one needed multiline input.

in my opinion, input() should be for single lines while (something along the lines of) longinput() should take multiple lines into account

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by skirpichev** [comment]
> yes, i know there are workarounds such as while loops or sys.stdin.readlines()

Or you can just enter multiline string:
```pycon
>>> """kiwi
... apple
... banana
... orange"""
'kiwi\napple\nbanana\norange'
>>> print(_)
kiwi
apple
banana
orange
```

> This is a minor feature

I don't think it is.  IIUC, you suggest to introduce a new builtin.  Correct?

If so, it's not a minor feature and it should be discussed first on https://discuss.python.org/c/ideas/6

**Comment by nineteendo** [comment]
You can also use [`iter()`](https://docs.python.org/3/library/functions.html#iter):

```python
>>> "\n".join(iter(input, ""))
kiwi
apple
banana
orange

'kiwi\napple\nbanana\norange'
```

**Comment by RustoMCSpit** [comment]
> > yes, i know there are workarounds such as while loops or sys.stdin.readlines()
> 
> Or you can just enter multiline string:
> 
> ```
> >>> """kiwi
> ... apple
> ... banana
> ... orange"""
> 'kiwi\napple\nbanana\norange'
> >>> print(_)
> kiwi
> apple
> banana
> orange
> ```
> 
> > This is a minor feature
> 
> I don't think it is. IIUC, you suggest to introduce a new builtin. Correct?
> 
> If so, it's not a minor feature and it should be discussed first on https://discuss.python.org/c/ideas/6

not pratical if youre not working with 4 items but rather 400.

**Comment by RustoMCSpit** [comment]
> You can also use [`iter()`](https://docs.python.org/3/library/functions.html#iter):
> 
> ```python
> >>> "\n".join(iter(input, ""))
> kiwi
> apple
> banana
> orange
> 
> 'kiwi\napple\nbanana\norange'
> ```

i cant, some inputs would have a space between them

e.g. celery sticks

and some times inputs would be separated with a line break

e.g. 

grapes

celery sticks

**Comment by skirpichev** [comment]
> not pratical if youre not working with 4 items but rather 400.

To me, entering 400 items in console is not practical in any way.

Ok.  I assume we interpreted your proposal correctly.  New builtin is not a minor feature.  Please discuss your proposal first on https://discuss.python.org/c/ideas/6.  If it will have some support - we can reopen this issue.

**Comment by nineteendo** [comment]
> some times inputs would be separated with a line break

Then you can use <kbd>Ctrl</kbd>+<kbd>D</kbd>:

```python
>>> sys.stdin.read()
kiwi
apple
banana
orange'kiwi\napple\nbanana\norange'
```

You can do this multiple times.

**Comment by RustoMCSpit** [comment]
> > some times inputs would be separated with a line break
> 
> Then you can still use Ctrl+D:
> 
> ```python
> >>> sys.stdin.read()
> kiwi
> apple
> banana
> orange'kiwi\napple\nbanana\norange'
> ```
> 
> You can do this multiple times.

exactly, thats the problem

**Comment by RustoMCSpit** [comment]
the links are broken? is the site down

**Comment by RustoMCSpit** [comment]
https://discuss.python.org/t/multiline-input-in-terminal/72807

**Comment by RustoMCSpit** [comment]
ive added it, i cant see a better workaround as is or any reason to object but comment there

**Comment by skirpichev** [comment]
> what would be practical?

Any text editor, probably.
