### ISSUE TITLE
Unable to force color output on Windows

### ISSUE THREAD

**Issue by PalmtopTiger** [python/cpython#127353]
# Bug report

### Bug description:

In [can_colorize function](https://github.com/python/cpython/blob/3a77980002845c22e5b294ca47a12d62bf5baf53/Lib/_colorize.py#L34), nt._supports_virtual_terminal call takes precedence over checking of environment variables. If the terminal emulator does not support this mode, the environment variables are not checked. This is contrary to the behavior on POSIX OSes, where variables are checked first.

There are third-party terminal emulators that support ANSI color codes, but do not support the new API added in Windows 10. For example, ConEmu and Cmder.

Also, the current behavior makes it impossible to output errors with ANSI codes to a file or through a pipe.

Screenshot of exception in ConEmu terminal:
![241128153324_unp](https://github.com/user-attachments/assets/3524e563-5320-4f52-b72d-bb4f863a7dc0)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-127354
* gh-127886
* gh-127889
* gh-127926
* gh-127944

**Comment by hugovk** [comment]
Thank you!

**Comment by PalmtopTiger** [comment]
@hugovk, thank you too!
