### ISSUE TITLE
phyton indirme yapılamıyor 

### ISSUE THREAD

**Issue by hfkaya** [python/cpython#127309]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
![Ekran görüntüsü 2024-11-27 011628](https://github.com/user-attachments/assets/54bdaddd-8eb4-40c6-bd15-5166d595e9b9)
 herhangi bir sorun olmamasına ramen bu hatayı alıyorum ve indirme işlemini başarı ile sonuçlandıramıyorum lütfen yardım edin...

### CPython versions tested on:

3.13

### Operating systems tested on:

Other

**Comment by Eclips4** [comment]
Duplicate of https://github.com/python/cpython/issues/127307
