### ISSUE TITLE
Document `gettext.c2py`

### ISSUE THREAD

**Issue by tomasr8** [python/cpython#127373]
`gettext.c2py` is currently not [documented](https://docs.python.org/3.14/library/gettext.html). This function is used internally by `GNUTranslations` but it's also useful on its own when dealing with translations. I have a PR on the way ;)

### Linked PRs
* gh-127374

**Comment by serhiy-storchaka** [comment]
It is an internal function, it is not a part of the public API.

**Comment by serhiy-storchaka** [comment]
It is not in `__all__`. Underscore is needed if `__all__` is not used.

This function is not in the public API first, and all other (including the lack of documentation) is derivative.

**Comment by tomasr8** [comment]
Ok thanks! I was just wondering because I sent another PR (https://github.com/python/cpython/pull/127348) previously which documents `traceback.print_list` which is also not in `__all__` but there were no objections to that one :confused:

**Comment by serhiy-storchaka** [comment]
I am not sure about `print_list`, but `c2py` is clearly not purposed to be used by external code.

I think I already rejected a similar proposal for another `gettext` function. Prefixing with underscore is not required for private names, and the absence of an underscore prefix is not always a sign of a public name.

**Comment by tomasr8** [comment]
Got it, thanks for the clarification!
