### ISSUE TITLE
On MacOS Sequoia IMKClient and IMKSession warning in Terminal apps

### ISSUE THREAD

**Issue by ndegroot** [python/cpython#127352]
# Bug report

### Bug description:

In the terminal of Macos Sequoia 15.1.1 the below logging is shown when using certain (GUI en TIU) frameworks. Not critical. 

```terminal
2024-11-26 22:43:42.634 python[33014:3805202] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-26 22:43:42.634 python[33014:3805202] +[IMKInputSession subclass]: chose IMKInputSession_Modern# 
```
Minimal script:
```python
import tkinter as tk
tk._test()
```
Seems that the OS falls back to  a legacy version of the IMK input. Application are supposed to update the use of [inputmethod](https://developer.apple.com/documentation/inputmethodkit?language=objc) at least that what's suggested...

## Mentions:
[qt issue](https://bugreports.qt.io/projects/PYSIDE/issues/PYSIDE-2877?filter=allissues)
[apple discussion](https://discussions.apple.com/thread/255761734?sortBy=rank)
[post](https://github.com/zegervdv/homebrew-zathura/issues/129#issuecomment-2360382975)

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by ned-deily** [comment]
If you have a recent version of Tcl/Tk 8.6.x installed on the same version of macOS, you will probably see the same messages if you run a Tk app written in Tcl (no Python involved) from the command line, for instance starting the Tcl `wish` shell and then selecting its Widget Demo from the menu bar. If you would like to pursue this, the place to do so would likely be the Tk issue tracker here: https://core.tcl-lang.org/tk.

```
$ wish8.6
% 2024-12-02 00:14:27.171 wish8.6[36250:20498071] +[IMKClient subclass]: chose IMKClient_Modern
2024-12-02 00:14:27.171 wish8.6[36250:20498071] +[IMKInputSession subclass]: chose IMKInputSession_Modern
```
