### ISSUE TITLE
Unexpected behavior in f-strings with nested quotes

### ISSUE THREAD

**Issue by BertLindeman** [python/cpython#127428]
# Bug report

### Bug description:

This "program" prints ```run``` 
```python
print(f"{"run"}")
```

This syntax is invalid as the nested double quotes should conflict with the outer ones.
It is expected to raise a SyntaxError.

This program (the same, but just without the 'f', so no f-string) 
```python
print("{"run"}")
```

reports:
```
  File "/home/bert/py/pybricks/issue/issue_1954_fstring_problem_syntax_simple_OK.py", line 2
    print("{"run"}")
          ^^^^^^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

### CPython versions tested on:

3.10, 3.12

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
This syntax was newly added in Python 3.12. See PEP-701.

**Comment by BertLindeman** [comment]
Thanks Jelle,

Bert
