### ISSUE TITLE
AIX build broken with Illegal instruction 

### ISSUE THREAD

**Issue by ayappanec** [python/cpython#127417]
# Bug report

### Bug description:

AIX build is broken with Illegal instruction after this merge https://github.com/python/cpython/pull/126025

./_bootstrap_python ./Programs/_freeze_module.py abc ./Lib/abc.py Python/frozen_modules/abc.h
./_bootstrap_python ./Programs/_freeze_module.py codecs ./Lib/codecs.py Python/frozen_modules/codecs.h
./_bootstrap_python ./Programs/_freeze_module.py io ./Lib/io.py Python/frozen_modules/io.h
./_bootstrap_python ./Programs/_freeze_module.py _collections_abc ./Lib/_collections_abc.py Python/frozen_modules/_collections_abc.h
./_bootstrap_python ./Programs/_freeze_module.py _sitebuiltins ./Lib/_sitebuiltins.py Python/frozen_modules/_sitebuiltins.h
./_bootstrap_python ./Programs/_freeze_module.py genericpath ./Lib/genericpath.py Python/frozen_modules/genericpath.h
gmake: *** [Makefile:1767: Python/frozen_modules/io.h] Illegal instruction
gmake: *** Waiting for unfinished jobs....
gmake: *** [Makefile:1764: Python/frozen_modules/codecs.h] Illegal instruction
gmake: *** [Makefile:1776: Python/frozen_modules/genericpath.h] Illegal instruction
gmake: *** [Makefile:1773: Python/frozen_modules/_sitebuiltins.h] Illegal instruction
gmake: *** [Makefile:1770: Python/frozen_modules/_collections_abc.h] Illegal instruction
gmake: *** [Makefile:1761: Python/frozen_modules/abc.h] Illegal instruction (core dumped)

Looking into the core,

dbx ./_bootstrap_python core
Illegal instruction (illegal opcode) in find_first_nonascii at line 5118 in file "Objects/unicodeobject.c" ($t1)
 5118       size_t u = load_unaligned(p, end - p) & ASCII_CHAR_MASK;
(dbx) where
find_first_nonascii(start = 0x0000000100463852, end = 0x0000000000000140), line 5118 in "unicodeobject.c"
PyUnicode_DecodeUTF8(??, ??, ??), line 5371 in "unicodeobject.c"

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-127433

**Comment by ZeroIntensity** [comment]
cc @methane

**Comment by picnixz** [comment]
Build bots are also broken. See: https://github.com/python/cpython/pull/126025#discussion_r1863825857.
