### ISSUE TITLE
More readable module constant addition statement

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#127435]
# Feature or enhancement

### Proposal:

I would like to ask if we need to package the addition of macro and constant for some modules in `Modules/*`? I think they should be like `socketmodule.c`, maybe it will be better. If allowed, I'll submit the PR. Like this:
```
#define ADD_INT_MACRO(MOD, INT) do {                    \
    if (PyModule_AddIntConstant(MOD, #INT, INT) < 0) {  \
        goto error;                                     \
    }                                                   \
} while (0)

#ifdef AF_APPLETALK
    /* Appletalk DDP */
    ADD_INT_MACRO(m, AF_APPLETALK);
#endif
```

for example:
from `posixmodule.c`
```
#ifdef TMP_MAX
    if (PyModule_AddIntMacro(m, TMP_MAX)) return -1;
#endif
#ifdef WCONTINUED
    if (PyModule_AddIntMacro(m, WCONTINUED)) return -1;
#endif
```
from `symtablemodule.c`
```
if (PyModule_AddIntMacro(m, USE) < 0) return -1;
if (PyModule_AddIntMacro(m, DEF_GLOBAL) < 0) return -1;
```
I'm not sure if this is a cosmetic change, but I think it's necessary since there are only a few old modules that don't have this.

### Has this already been discussed elsewhere?

No response given

**Comment by rruuaanng** [comment]
cc @vstinner

**Comment by picnixz** [comment]
We tend to avoid packaging macros like that, except for the C API tests which has some macros or hashlib-related code which also some macros. It would be better to have an ERRACTION suite that would be executed on error instead of just jumping to an 'error' label which may or may not exist. But honestly, considering the number of modules that would be affected and the additional indirection that it could cause while reading code, I doubt it would be accepted.

**Comment by serhiy-storchaka** [comment]
I do not see how this is anything but cosmetic changes. Cosmetic changes are allowed if the maintainer of that code decided that this will make the future maintenance easier. For every case it should be decided separately. We should not take a solution and look for problems, we should look for a suitable solution for each problem.

**Comment by rruuaanng** [comment]
I see. I'll package all unpackaged statements in all modules today. Stay tuned :)

**Comment by picnixz** [comment]
> I see. I'll package all unpackaged statements in all modules today. Stay tuned :)

I'm not sure that we decided to do this. Please, ask the maintainer of each module you want to change whether this is needed or not before creating a corresponding PR.

**Comment by rruuaanng** [comment]
I agree that I'll list all the modules that need to be modified and complete them as required.

**Comment by serhiy-storchaka** [comment]
I a maintainer of some module need this, they can change the code of the corresponding module. Currently there is no need to massrewrite all modules.

See also an alternative idea in #86542.

**Comment by rruuaanng** [comment]
I'll read it carefully today and try to realize it in the near future.
