### ISSUE TITLE
Compute dictionary values ​​in parallel

### ISSUE THREAD

**Issue by vivodi** [python/cpython#127459]
# Feature or enhancement

### Proposal:

The following code takes 4 seconds to run. If the values ​​in the dictionary can be calculated in parallel, it only takes 2 seconds.
```python
import asyncio
import time

async def main():
    start = time.time()
    dic = {
        'a': await asyncio.sleep(2),
        'b': await asyncio.sleep(2)
    }
    end = time.time()
    print(f'elapsed time: {end - start} seconds')

asyncio.run(main())
```
Current output:
```
elapsed time: 4 seconds
```
Expected output:
```
elapsed time: 2 seconds
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by itamaro** [comment]
Hello!

Note that when talking about asyncio, it's about doing things *concurrently*, not necessarily *in parallel*.

What you're describing in the example is possible today using asyncio task groups:

```py
import asyncio
import time

async def main():
    start = time.time()
    d = {}
    async with asyncio.TaskGroup() as tg:
        d['a'] = tg.create_task(asyncio.sleep(2))
        d['b'] = tg.create_task(asyncio.sleep(2))
    end = time.time()
    print(f'elapsed time: {end - start} seconds')

asyncio.run(main())
```

executing this, I get:

```sh
$ python3 demo.py
elapsed time: 2.00158429145813 seconds
```

If you're proposing to somehow have the dictionary constructor itself automagically behave the same way, it would be a much more significant proposal which would require discussion in [the ideas category on Discuss](https://discuss.python.org/c/ideas/6).

Alternatively, you may be interested in posting on [the help category](https://discuss.python.org/c/help/7).

**Comment by vivodi** [comment]
I've added a new topic in the ideas category: https://discuss.python.org/t/enable-dictionary-constructor-to-compute-values-concurrently/72937
