### ISSUE TITLE
Add examples for all Python features in doc

### ISSUE THREAD

**Issue by ArtemIsmagilov** [python/cpython#127489]
# Feature or enhancement

### Proposal:

Doc text about id func
...
Example 
```python
 id("string")
>>>46764578
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

In Rust, all std features have one or more examples.

Please, add in doc 1, 2 examples with code. It's need for simple visualisation, demonstrating features.

hex func have examples, its cool!
https://docs.python.org/3/library/functions.html#hex

But, id func haven't example 
https://docs.python.org/3/library/functions.html#id

I think that in general everything that is in Python in the documentation should be with at least one example of how to apply it. Let's take an example from Rust!

This is a big problem, because it is not clear how to apply the language features and in what situation. a small example will give me an idea of how the correct application of features looks like.

**Comment by AA-Turner** [comment]
This is an existing goal, there exist preliminary efforts to start this with string methods. Closing as duplicate.

A

**Comment by tomasr8** [comment]
> This is an existing goal, there exist preliminary efforts to start this with string methods. Closing as duplicate.
> 
> A

Is there an existing issue that we can link to?

**Comment by hugovk** [comment]
Yes, here's one: https://github.com/python/cpython/pull/119445
