### ISSUE TITLE
Add `PyMem_Raw{New,Resize}` convenience macros

### ISSUE THREAD

**Issue by picnixz** [python/cpython#127415]
# Feature or enhancement

### Proposal:

We have convenience macros for `PyMem_New` and `PyMem_Resize` to allocate memory for *n* objects of the given type without checking if `n * sizeof(T)` would overflow but we don't have any for the raw allocators. I suggest adding those two macros.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127416

**Comment by encukou** [comment]
It seems to me that they wouldn't be worth it. `PyMem_RawCalloc(sizeof(T), n)` isn't that much worse to type than `PyMem_RawNew(T, n)`, and `PyMem_Resize` isn't very convenient if you want proper error handling.

**Comment by ZeroIntensity** [comment]
Looking at the PR, I think the biggest difference would be that `PyMem_RawNew` doesn't zero-out the memory. I personally don't find that useful, but I guess some users that are gung-ho on performance might like it.

**Comment by picnixz** [comment]
It isn't that much worse but it does use a different allocator function (one being calloc(), the other one being malloc()). In addition, IIRC, calloc() sets the memory to 0 while malloc() leaves area of memory uninitialized. For downstream users, I feel that it's better that they retain the semantics they want as well.

**Comment by ZeroIntensity** [comment]
I do see some usage, but Petr is less easily convinced. Generally for C API changes, you need to bicker with the C API WG first: https://github.com/capi-workgroup/decisions/issues

**Comment by picnixz** [comment]
Oh right. I'll move the discussion there (I tend to forget about the C API WG when the feature is small enough but I can try writing a more convincing proposal tomorrow)

**Comment by Covitluat77** [comment]
I am the one who made the algorithms for uniswap I have reached over a 3 billion in my uniswap app

**Comment by picnixz** [comment]
Having failed to convince the C API WG (and because I was less and less convinced as well), I will not push for this feature for now.
