### ISSUE TITLE
Allow to show specialized bytecode via `dis` CLI

### ISSUE THREAD

**Issue by picnixz** [python/cpython#127413]
# Feature or enhancement

### Proposal:

It's already possible to show specialized bytecode using `dis.dis(code, adaptive=True)` but it's not possible to do it from the CLI. I think we can add a flag `-S` that does it (most of the other flags are exposed to the CLI).

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127414

**Comment by JelleZijlstra** [comment]
Doesn't bytecode only get specialized after it is run? The CLI will show bytecode for code that's never run, so it will never be specialized.

**Comment by picnixz** [comment]
> The CLI will show bytecode for code that's never run, so it will never be specialized.

Actually, `dis.dis(adaptive=True)` does show specialized bytecode. Or maybe I'm not using the correct terminology? For instance, a simple `return None` shows a LOAD_CONST + RETURN and not a LOAD_CONST_IMMORTALIZED, which is what I found weird.

**Comment by picnixz** [comment]
An example:

### Non-specialized bytecode

```sh
echo 'x = None' | ./python -m dis
  0           RESUME                   0

  1           LOAD_CONST               0 (None)
              STORE_NAME               0 (x)
              LOAD_CONST               0 (None)
              RETURN_VALUE
```

### Specialized bytecode

```sh
echo 'x = None' | ./python -m dis -S
  0           RESUME                   0

  1           LOAD_CONST_IMMORTAL      0 (None)
              STORE_NAME               0 (x)
              LOAD_CONST_IMMORTAL      0 (None)
              RETURN_VALUE
```
