### ISSUE TITLE
set(r) mutates r

### ISSUE THREAD

**Issue by pvm2** [python/cpython#127493]
# Bug report

### Bug description:

```python
r = [('a',)]
r = filter(lambda x:x[-1] != '.', r)
print(sum(1 for _ in r) == len(set(r))) # -> False
set(r)
print(sum(1 for _ in r) == len(set(r))) # -> True
```

Happens on Windows 3.13.0 and Python 3.14.0a2+ (heads/main:7ea523f47cd, Dec  2 2024, 00:11:08) [GCC 11.4.0] on linux (with WSL Ubuntu). I discovered this on Windows 3.12.(5 I think) so maybe it's been around for longer. 

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

**Comment by graingert** [comment]
This is expected behavior, the filter generator is being consumed

**Comment by graingert** [comment]
You should use: 

```python
r_list = [('a',)]
r = {x for x in r_list if x[-1] != "."}
```

**Comment by pvm2** [comment]
Yeah makes sense sorry
