### ISSUE TITLE
iOS `clang` aliases crash with "invalid directory name" error if called with arguments having spaces

### ISSUE THREAD

**Issue by FeodorFitsner** [python/cpython#127434]
# Bug report

### Bug description:

While doing cross-compilation of Python packages for iOS calling [`arm64-apple-ios-clang`](https://github.com/python/cpython/blob/main/iOS/Resources/bin/arm64-apple-ios-clang) script (and other aliases as well) fails if arguments contain spaces, for example:

```
arm64-apple-ios-clang -DPACKAGE_TARNAME="aaa" -DPACKAGE_STRING="aaa 1.2.2" -c -o src/main.o src/main.c
```

gives `clang: invalid directory name: '1.2.2"'` error.

To fix that `$@` inside script should be wrapped with quotes: `"$@"`.

I'm going to make PR.
 

### CPython versions tested on:

3.12

### Operating systems tested on:

macOS

### Linked PRs
* gh-127575
* gh-127624

**Comment by ZeroIntensity** [comment]
cc @freakboy3742

**Comment by FeodorFitsner** [comment]
Original issue: https://github.com/beeware/Python-Apple-support/pull/241#pullrequestreview-2468845162

**Comment by FeodorFitsner** [comment]
Yes, I'm going to make a PR.
