### ISSUE TITLE
UnboundLocalError where the unassigned variable is a function

### ISSUE THREAD

**Issue by aer0aa** [python/cpython#127445]
# Bug report

### Bug description:

It gives this error:
```
Traceback (most recent call last):
  File "C:\Users\calev\Documents\solitaire.py", line 198, in <module>
    move()
  File "C:\Users\calev\Documents\solitaire.py", line 90, in move
    tmr = int(tmr)
UnboundLocalError: cannot access local variable 'int' where it is not associated with a value
```
I haven't been able to replicate this and I think the whole code is too long to include in this report, so I've linked to it [here](https://pastebin.com/ki0HMuZR), answer "M" and then anything to get the error. This happens to all uses of ``int()`` in the ``move()`` function, and it keeps happening even when I rename or move it.
I'm on Windows 11

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Windows

**Comment by ronaldoussoren** [comment]
Please don't use this issue tracker to debug problems with your script.

The error is that you use ``int`` as a local variable in the function and intent to call the global ``int`` at other places in the same function.

**Comment by aer0aa** [comment]
> Please don't use this issue tracker to debug problems with your script.
> 
> The error is that you use `int` as a local variable in the function and intent to call the global `int` at other places in the same function.

I've fixed it by adding `global int` to the function. Still, I've never needed to do that before and I'm not sure how I was using `int` as a variable

**Comment by picnixz** [comment]
Your issue is that you did

```py
    try:
        int = int(de)
    except:
        if de == "C" or de == "c":
            cancel = True
```

So you're re-assigning the `int` built-in. You should use another variable name.
