### ISSUE TITLE
Re：The re.findall method has bugs, resulting in incomplete returned data.

### ISSUE THREAD

**Issue by WANGKANG1717** [python/cpython#127498]
# Bug report

### Bug description:

# code
```python
import re

word = open("test.txt", "r", encoding="utf-8").read()
with open("test.txt", "w", encoding="utf-8") as f:
    f.write(word)

match_str = r"^\d+．[ ]*（[ \d]+分）[\w\W]+?(?=(^\d+．[ ]*（[ \d]+分）.+)|[一二三四五六七八九十]、.+|####end)"

res_findall = re.findall(match_str, word, flags=re.M)
print(len(res_findall))

res_finditer = []
for i in re.finditer(match_str, word, flags=re.M):
    res_finditer.append(i.group())
print(len(res_finditer))

print("-------------- res_findall -------------------------")
for r in res_findall:
    print(r)
    print("---------------------------")

print("=================================== res_finditer ===================================")
for r in res_finditer:
    print(r)
    print("===================================")

```

# test.txt
"""
2015年四川省高考物理试卷

一、选择题：每题6分，每题给出的四个选项中，有的只有一个选项，有的有多个选项符合题目要求，全部选地的得6分，选对但不全的得3分，有选错和不选的得0分
1．（6分）在同一位置以相同的速率把三个小球分别沿水平、斜向上、斜向下方向抛出，不计空气阻力，则落在同一水平地面时的速度大小（　　）
A．一样大	B．水平抛出的最大
C．斜向上抛的最大	D．斜向下抛的最大
2．（6分）平静湖面传播着一列水面波（横波），在波的传播方向上有相距3m的甲、乙两个小木块随波上下运动，测得两个小木块每分钟都上下30次，甲在波谷时，乙在波峰，且两木块之间有一个波峰．这列水面波（　　）
A．频率是30Hz	B．波长是3m	C．波速是1m/s	D．周期是0.1s
3．（6分）直线P1P2过均匀玻璃球球心O，细光束a、b平行且关于P1P2对称，由空气射入玻璃球的光路如图．a、b光相比（　　）

A．玻璃对a光的折射率较大
B．玻璃对a光的临界角较小
C．b光在玻璃中的传播速度较小
D．b光在玻璃中的传播时间较短
4．（6分）小型手摇发电机线圈共N匝，每匝可简化为矩形线圈abcd，磁极间的磁场视为匀强磁场，方向垂直于线圈中心轴OO′，线圈绕OO′匀速转动，如图所示，矩形线圈ab边和cd边产生的感应电动势的最大值都为e0，不计线圈电阻，则发电机输出电压（　　）

A．峰值是e0	B．峰值是2e0	C．有效值是e0	D．有效值是Ne0
5．（6分）登上火星是人类的梦想，“嫦娥之父”欧阳自远透露：中国计划于2020年登陆火星．地球和火星公转视为匀速圆周运动，忽略行星自转影响，根据如表，火星和地球相比（　　）
A．火星的公转周期较小
B．火星做圆周运动的加速度较小
C．火星表面的重力加速度较大
D．火星的第一宇宙速度较大
6．（6分）如图所示，半圆槽光滑、绝缘、固定、圆心是O，最低点是P，直径MN水平，a、b是两个完全相同的带正电小球（视为点电荷），b固定在M点，a从N点静止释放，沿半圆槽运动经过P点到达某点Q（图中未画出）时速度为零．则小球a（　　）

A．从N到Q的过程中，重力与库仑力的合力先增大后减小
B．从N到P的过程中，速率先增大后减小
C．从N到Q的过程中，电势能一直增加
D．从P到Q的过程中，动能减少量小于电势能增加量
7．（6分）如图所示，S处有一电子源，可向纸面内任意方向发射电子，平板MN垂直于纸面，在纸面内的长度L=9.1cm，中点O与S间的距离d=4.55cm，MN与SO直线的夹角为θ，板所在平面有电子源的一侧区域有方向垂直于纸面向外的匀强磁场，磁感应强度B=2.0×10﹣4T．电子质量m=9.1×10﹣31kg，电量e=1.6×10﹣19C，不计电子重力．电子源发射速度v=1.6×106m/s的一个电子，该电子打在板上可能位置的区域的长度为l，则（　　）

A．θ=90°时，l=9.1cm	B．θ=60°时，l=9.1cm
C．θ=45°时，l=4.55cm	D．θ=30°时，l=4.55cm

二、非选择题：（共68分）
8．（6分）某同学在“探究弹力和弹簧伸长的关系”时，安装好实验装置，让刻度尺零刻度与弹簧上端平齐，在弹簧下端挂1个钩码，静止时弹簧长度为l1，如图1所示，图2是此时固定在弹簧挂钩上的指针在刻度尺（最小分度是1毫米）上位置的放大图，示数l1=　   　cm．在弹簧下端分别挂2个、3个、4个、5个相同钩码，静止时弹簧长度分别是l2、l3、l4、l5，已知每个钩码质量是50g，挂2个钩码时，弹簧弹力F2=　   　N（当地重力加速度g=9.8m/s2）．要得到弹簧伸长量x，还需要测量的是　   　．作出F﹣x曲线，得到弹力与弹簧伸长量的关系．

9．（11分）用实验测一电池的内阻r和一待测电阻的阻值Rx，已知电池的电动势约6V，电池内阻和待测电阻阻值都为数十欧．可选用的实验器材有：
电流表A1（量程0～30mA）；
电流表A2（量程0～100mA）；
电压表V（量程0﹣6V）；
滑动变阻器R1（阻值0～5Ω）
滑动变阻器R2（阻值0～300Ω）；
开关S一个，导线若干条．

某同学的实验过程如下：
Ⅰ．设计如图1所示的电路图，正确连接电路．
Ⅱ．将R的阻值调到最大，闭合开关，逐次调小R的阻值，测出多组U和I的值，并记录．以U为纵轴．I为横轴．得到如图2所示的图线．
Ⅲ．断开开关，将Rx改接在B、C之间．A与B直接相连，其他部分保持不变．重复Ⅱ的步骤，得到另一条U﹣I图线，图线与横轴I的交点坐标为（I0，0），与纵轴U的交点坐标为（0，U0）．
回答下列问题：
①电流表应选用　   　，滑动变阻器应选用
②由图2的图线，得电源内阻r=　   　Ω；
③用I0、U0和r表示待测电阻的关系式Rx=　   　，代入数值可得Rx；
④若电表为理想电表，Rx接在B、C之间与接在A、B之间，滑动变阻器滑片都从最大阻值位置调到某同一位置，两种情况相比，电流表示数变化范围　   　，电压表示数变化范围　   　（选填“相同”或“不同”）
10．（15分）严重的雾霾天气，对国计民生已造成了严重的影响，汽车尾气是形成雾霾的首要污染源，“铁腕治污”已成为国家的工作重点．地铁列车可实现零排放、大力发展地铁，可以大大减少燃油公交车的使用，减少汽车尾气排放．若一地铁列车从甲站由静止启动后做直线运动，先匀加速运动20s达最高速度72km/h，再匀速运动80s，接着匀减速运动15s到达乙站停住，设列车在匀加速运动阶段牵引力为1×106N，匀速运动阶段牵引力的功率为6×103kW，忽略匀减速运动阶段牵引力所做的功．
（1）求甲站到乙站的距离；
（2）如果燃油公交车运行中做的功与该列车从甲站到乙站牵引力做的功相同，求公交车排放气态污染物的质量．（燃油公交车每做1焦耳功排放气态污染物3×10﹣6克）
11．（17分）如图所示，粗糙、绝缘的直轨道OB固定在水平桌面上，B端与桌面边缘对齐，A是轨道上一点，过A点并垂直于轨道的竖直面右侧有大小E=1.5×106N/C，方向水平向右的匀强电场．带负电的小物体P电荷量是2.0×10﹣6C．质量m=0.25kg，与轨道间动摩擦因数μ=0.4．P从O点由静止开始向右运动，经过0.55s到达A点．到达B点时速度是5m/s，到达空间D点时的速度与竖直方向的夹角为α，且tanα=1.2．P在整个运动过程中始终受到水平向右的某外力F作用．F大小与P的速率v的关系如表所示．P视为质点，电荷量保持不变，忽略空气阻力，取g=10m/s2．求：
（1）小物体P从开始运动至速率为2m/s所用的时间；
（2）小物体P从A运动至D的过程，电场力做的功．

12．（19分）如图所示，金属导轨MNC和PQD，MN与PQ平行且间距为L，所在平面与水平面夹角为α，N、Q连线与MN垂直，M、P间接有阻值为R的电阻；光滑直导轨NC和QD在同一水平面内，与NQ的夹角都为锐角θ．均匀金属棒ab和ef质量均为m，长均为L，ab棒初始位置在水平导轨上与NQ重合；ef棒垂直放在倾斜导轨上，与导轨间的动摩擦因数为μ（μ较小），由导轨上的小立柱1和2阻挡而静止。空间有方向竖直的匀强磁场（图中未画出）。两金属棒与导轨保持良好接触。不计所有导轨和ab棒的电阻，ef棒的阻值为R，最大静摩擦力与滑动摩擦力大小相等，忽略感应电流产生的磁场，重力加速度为g。
（1）若磁感应强度大小为B，给ab棒一个垂直于NQ、水平向右的速度v1，在水平导轨上沿运动方向滑行一段距离后停止，ef棒始终静止，求此过程ef棒上产生的热量；
（2）在（1）问过程中，ab棒滑行距离为d，求通过ab棒某横截面的电量；
（3）若ab棒以垂直于NQ的速度v2在水平导轨上向右匀速运动，并在NQ位置时取走小立柱1和2，且运动过程中ef棒始终静止。求此状态下最强磁场的磁感应强度及此磁场下ab棒运动的最大距离。

####end

"""

# The correct return is:
```txt
['1．（6分）在同一位置以相同的速率把三个小球分别沿水平、斜向上、斜向下方向抛出，不计空气阻力，则落在同一水平地面时的速度大小（\u3000\u3000）\nA．一样大\tB．水平抛出的最 大\nC．斜向上抛的最大\tD．斜向下抛的最大\n', '2．（6分）平静湖面传播着一列水面波（横波），在波的传播方向上有相距3m的甲、乙两个小木块随波上下运动，测得两个小木块每分钟都 上下30次，甲在波谷时，乙在波峰，且两木块之间有一个波峰．这列水面波（\u3000\u3000）\nA．频率是30Hz\tB．波长是3m\tC．波速是1m/s\tD．周期是0.1s\n', '3．（6分）直线P1P2过均 匀玻璃球球心O，细光束a、b平行且关于P1P2对称，由空气射入玻璃球的光路如图．a、b光相比（\u3000\u3000）\n\nA．玻璃对a光的折射率较大\nB．玻璃对a光的临界角较小\nC．b光在玻璃中的传播速度较小\nD．b光在玻璃中的传播时间较短\n', '4．（6分）小型手摇发电机线圈共N匝，每匝可简化为矩形线圈abcd，磁极间的磁场视为匀强磁场，方向垂直于线圈中心轴OO′，线圈绕OO′匀速转动，如图所示，矩形线圈ab边和cd边产生的感应电动势的最大值都为e0，不计线圈电阻，则发电机输出电压（\u3000\u3000）\n\nA．峰值是e0\tB．峰值是2e0\tC．有效值是e0\tD．有效值是Ne0\n', '5．（6分）登上火星是人类的梦想，“嫦娥之父”欧阳自远透露：中国计划于2020年登陆火星．地球和火星公转视为匀速圆周运动，忽略行星自转影响，根据如表，火星和地球相比（\u3000\u3000）\nA．火星的公转周期较小\nB．火星做圆周运动的加速度较小\nC．火星表面的重力加速度较大\nD．火星的第一宇宙速度较大\n', '6．（6分）如图所示，半圆槽光滑、绝 缘、固定、圆心是O，最低点是P，直径MN水平，a、b是两个完全相同的带正电小球（视为点电荷），b固定在M点，a从N点静止释放，沿半圆槽运动经过P点到达某点Q（图中未画出）时速度为零 ．则小球a（\u3000\u3000）\n\nA．从N到Q的过程中，重力与库仑力的合力先增大后减小\nB．从N到P的过程中，速率先增大后减小\nC．从N到Q的过程中，电势能一直增加\nD．从P到Q的过程中，动能减少量小于电势能增加量\n', '7．（6分）如图所示，S处有一电子源，可向纸面内任意方向发射电子，平板MN垂直于纸面，在纸面内的长度L=9.1cm，中点O与S间的距离d=4.55cm，MN与SO直线的夹角为θ，板所在平面有电子源的一侧区域有方向垂直于纸面向外的匀强磁场，磁感应强度B=2.0×10﹣4T．电子质量m=9.1×10﹣31kg，电量e=1.6×10﹣19C，不计电子重力．电子源发射速度v=1.6×106m/s的一个电子，该电子打在板上可能位置的区域的长度为l，则（\u3000\u3000）\n\nA．θ=90°时，l=9.1cm\tB．θ=60°时，l=9.1cm\nC．θ=45°时，l=4.55cm\tD．θ=30°时，l=4.55cm\n\n', '8．（6分）某同学在“探究弹力和弹簧伸长的关系”时，安装好实验装置，让刻度尺零刻度与弹簧上端平齐，在弹簧下端挂1个钩码，静止时弹簧长度为l1，如图1所示，图2是此时固定在弹簧挂钩上的指针在刻度尺（最小分度是1毫米）上位置的放大图，示数l1=\u3000   \u3000cm．在弹簧下端分别挂2个、3个、4个、5个相同钩码，静止时弹簧长度分别是l2、l3、l4、l5，已知每个钩码质量是50g，挂2个钩码时，弹簧弹力F2=\u3000   \u3000N（当地重力加速度g=9.8m/s2）．要得到弹簧伸长量x，还需要测量的是\u3000   \u3000．作出F﹣x曲线，得到弹力与弹簧 伸长量的关系．\n\n', '9．（11分）用实验测一电池的内阻r和一待测电阻的阻值Rx，已知电池的电动势约6V，电池内阻和待测电阻阻值都为数十欧．可选用的实验器材有：\n电流表A1（量程0～30mA）；\n电流表A2（量程0～100mA）；\n电压表V（量程0﹣6V）；\n滑动变阻器R1（阻值0～5Ω）\n滑动变阻器R2（阻值0～300Ω）；\n开关S一个，导线若干条．\n\n某同学的实验过程如下：\nⅠ．设计如图1所示的电路图，正确连接电路．\nⅡ．将R的阻值调到最大，闭合开关，逐次调小R的阻值，测出多组U和I的值，并记录．以U为纵轴．I为横轴．得到如图2所示的图线．\nⅢ．断开开关，将Rx改接在B、C之间．A与B直接相连，其他部分保持不变．重复Ⅱ的步骤，得到另一条U﹣I图线，图线与横轴I的交点坐标为（I0，0），与纵轴U的交点坐标为（0，U0）．\n回答下列问题：\n①电流表应选用\u3000   \u3000，滑动变阻器应选用\n②由图2的图线，得电源内阻r=\u3000   \u3000Ω；\n③用I0、U0和r表示待测电阻的关系式Rx=\u3000   \u3000，代入数值可得Rx；\n④若电表为理想电表，Rx接在B、C之间与接在A、B之间，滑动变阻器滑片都从最大阻值位置调到某同一位置，两种情况相比，电流表示数变化范围\u3000   \u3000，电压表示数变化范围\u3000   \u3000（选填“相同”或“不同”）\n', '10．（15分）严重的雾霾天气，对国计民生已造成了严重的影响，汽车尾气是形成雾霾的首要污染源，“铁腕治污”已成为国家的工作重点．地铁列车可实现零排放、大力发展地铁，可以大大减少燃油公交车的使用，减少汽车尾气排放．若一地铁列车从甲站由静止启动后做直线运动，先匀加速运动20s达最高速度72km/h，再匀速运动80s，接着 匀减速运动15s到达乙站停住，设列车在匀加速运动阶段牵引力为1×106N，匀速运动阶段牵引力的功率为6×103kW，忽略匀减速运动阶段牵引力所做的功．\n（1）求甲站到乙站的距离；\n（2） 如果燃油公交车运行中做的功与该列车从甲站到乙站牵引力做的功相同，求公交车排放气态污染物的质量．（燃油公交车每做1焦耳功排放气态污染物3×10﹣6克）\n', '11．（17分）如图所示 ，粗糙、绝缘的直轨道OB固定在水平桌面上，B端与桌面边缘对齐，A是轨道上一点，过A点并垂直于轨道的竖直面右侧有大小E=1.5×106N/C，方向水平向右的匀强电场．带负电的小物体P电荷量 是2.0×10﹣6C．质量m=0.25kg，与轨道间动摩擦因数μ=0.4．P从O点由静止开始向右运动，经过0.55s到达A点．到达B点时速度是5m/s，到达空间D点时的速度与竖直方向的夹角为α，且tanα=1.2 ．P在整个运动过程中始终受到水平向右的某外力F作用．F大小与P的速率v的关系如表所示．P视为质点，电荷量保持不变，忽略空气阻力，取g=10m/s2．求：\n（1）小物体P从开始运动至速率 为2m/s所用的时间；\n（2）小物体P从A运动至D的过程，电场力做的功．\n\n', '12．（19分）如图所示，金属导轨MNC和PQD，MN与PQ平行且间距为L，所在平面与水平面夹角为α，N、Q连线与MN垂直，M、P间接有阻值为R的电阻；光滑直导轨NC和QD在同一水平面内，与NQ的夹角都为锐角θ．均匀金属棒ab和ef质量均为m，长均为L，ab棒初始位置在水平导轨上与NQ重合；ef棒垂直放在倾斜导轨上，与导轨间的动摩擦因数为μ（μ较小），由导轨上的小立柱1和2阻挡而静止。空间有方向竖直的匀强磁场（图中未画出）。两金属棒与导轨保持良好接触。不计所有导轨和ab棒的电阻 ，ef棒的阻值为R，最大静摩擦力与滑动摩擦力大小相等，忽略感应电流产生的磁场，重力加速度为g。\n（1）若磁感应强度大小为B，给ab棒一个垂直于NQ、水平向右的速度v1，在水平导轨上 沿运动方向滑行一段距离后停止，ef棒始终静止，求此过程ef棒上产生的热量；\n（2）在（1）问过程中，ab棒滑行距离为d，求通过ab棒某横截面的电量；\n（3）若ab棒以垂直于NQ的速度v2 在水平导轨上向右匀速运动，并在NQ位置时取走小立柱1和2，且运动过程中ef棒始终静止。求此状态下最强磁场的磁感应强度及此磁场下ab棒运动的最大距离。\n\n\n']
```

# But re.findall returned incorrect data:
```txt
['2．（6分）平静湖面传播着一列水面波（横波），在波的传播方向上有相距3m的甲、乙两个小木块随波上下运动，测得两个小木块每分钟都上下30次，甲在波谷时，乙在波峰，且两木块之间 有一个波峰．这列水面波（\u3000\u3000）', '3．（6分）直线P1P2过均匀玻璃球球心O，细光束a、b平行且关于P1P2对称，由空气射入玻璃球的光路如图．a、b光相比（\u3000\u3000）', '4 ．（6分）小型手摇发电机线圈共N匝，每匝可简化为矩形线圈abcd，磁极间的磁场视为匀强磁场，方向垂直于线圈中心轴OO′，线圈绕OO′匀速转动，如图所示，矩形线圈ab边和cd边产生的感应 电动势的最大值都为e0，不计线圈电阻，则发电机输出电压（\u3000\u3000）', '5．（6分）登上火星是人类的梦想，“嫦娥之父”欧阳自远透露：中国计划于2020年登陆火星．地球和火星公转 视为匀速圆周运动，忽略行星自转影响，根据如表，火星和地球相比（\u3000\u3000）', '6．（6分）如图所示，半圆槽光滑、绝缘、固定、圆心是O，最低点是P，直径MN水平，a、b是两个完 全相同的带正电小球（视为点电荷），b固定在M点，a从N点静止释放，沿半圆槽运动经过P点到达某点Q（图中未画出）时速度为零．则小球a（\u3000\u3000）', '7．（6分）如图所示，S处有 一电子源，可向纸面内任意方向发射电子，平板MN垂直于纸面，在纸面内的长度L=9.1cm，中点O与S间的距离d=4.55cm，MN与SO直线的夹角为θ，板所在平面有电子源的一侧区域有方向垂直于纸 面向外的匀强磁场，磁感应强度B=2.0×10﹣4T．电子质量m=9.1×10﹣31kg，电量e=1.6×10﹣19C，不计电子重力．电子源发射速度v=1.6×106m/s的一个电子，该电子打在板上可能位置的区域的长度为l，则（\u3000\u3000）', '', '9．（11分）用实验测一电池的内阻r和一待测电阻的阻值Rx，已知电池的电动势约6V，电池内阻和待测电阻阻值都为数十欧．可选用的实验器材有：', '10．（15分）严重的雾霾天气，对国计民生已造成了严重的影响，汽车尾气是形成雾霾的首要污染源，“铁腕治污”已成为国家的工作重点．地铁列车可实现零排放、大力发展地铁，可以大大减少 燃油公交车的使用，减少汽车尾气排放．若一地铁列车从甲站由静止启动后做直线运动，先匀加速运动20s达最高速度72km/h，再匀速运动80s，接着匀减速运动15s到达乙站停住，设列车在匀加速运动阶段牵引力为1×106N，匀速运动阶段牵引力的功率为6×103kW，忽略匀减速运动阶段牵引力所做的功．', '11．（17分）如图所示，粗糙、绝缘的直轨道OB固定在水平桌面上，B端与桌面 边缘对齐，A是轨道上一点，过A点并垂直于轨道的竖直面右侧有大小E=1.5×106N/C，方向水平向右的匀强电场．带负电的小物体P电荷量是2.0×10﹣6C．质量m=0.25kg，与轨道间动摩擦因数μ=0.4．P从O点由静止开始向右运动，经过0.55s到达A点．到达B点时速度是5m/s，到达空间D点时的速度与竖直方向的夹角为α，且tanα=1.2．P在整个运动过程中始终受到水平向右的某外力F作用．F大小与P的速率v的关系如表所示．P视为质点，电荷量保持不变，忽略空气阻力，取g=10m/s2．求：', '12．（19分）如图所示，金属导轨MNC和PQD，MN与PQ平行且间距为L，所在平面与水平面 夹角为α，N、Q连线与MN垂直，M、P间接有阻值为R的电阻；光滑直导轨NC和QD在同一水平面内，与NQ的夹角都为锐角θ．均匀金属棒ab和ef质量均为m，长均为L，ab棒初始位置在水平导轨上与NQ重合；ef棒垂直放在倾斜导轨上，与导轨间的动摩擦因数为μ（μ较小），由导轨上的小立柱1和2阻挡而静止。空间有方向竖直的匀强磁场（图中未画出）。两金属棒与导轨保持良好接触。不计 所有导轨和ab棒的电阻，ef棒的阻值为R，最大静摩擦力与滑动摩擦力大小相等，忽略感应电流产生的磁场，重力加速度为g。', '']
```

# You can see that the first and eighth data are missing

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
Considering the SO explanation, I'm closing this one as `wont fix`.
