### ISSUE TITLE
Add list.remove_duplicates() method

### ISSUE THREAD

**Issue by AvitalOhayon** [python/cpython#127531]
# Feature or enhancement

### Proposal:

**Rationale:**

Currently there's no straightforward way to remove duplicates while preserving order. Common solutions like `list(dict.fromkeys(lst))` or using sets are either non-intuitive or don't preserve order.

**Proposed API:**
```python
lst = [1, 2, 2, 3, 1]
lst.remove_duplicates()  # returns [1, 2, 3]
```

**Has this already been discussed elsewhere?**
This is a minor feature, which does not need previous discusions elsewhere.

**Comment by graingert** [comment]
This is a pretty major feature, and would need to be discussed here first: https://discuss.python.org/c/ideas/6
