### ISSUE TITLE
`_Py_RefcntAdd` doesn't increment ref count stats

### ISSUE THREAD

**Issue by EdNutting** [python/cpython#127599]
# Bug report

### Bug description:

Hi,

I am unsure if this intentional or not so apologies if this turns out not to be a bug. 

The code for `_Py_RefcntAdd` does not include `_Py_INCREF_STAT_INC`. This appears to mean the statistics do not track these additions to the reference count, which are increments (although not increments by `1`, they are increasing the ref count in a single operation).

https://github.com/python/cpython/blob/ad9d059eb10ef132edd73075fa6d8d96d95b8701/Include/internal/pycore_object.h#L121

I believe this may be an oversight because this stat should be tracked, and also because the corresponding decrement ref count code does call `_Py_DECREF_STAT_INC` (e.g. https://github.com/python/cpython/blob/ad9d059eb10ef132edd73075fa6d8d96d95b8701/Include/internal/pycore_object.h#L383 )

I have checked the callers of `_Py_RefcntAdd` (in `listobject.c` and `tupleobject.c`) and they do not separately perform the stats tracking.

Is this an issue or is there a reason this ref count increment is excluded?

Thanks,
Ed

### CPython versions tested on:

3.12, 3.13

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-127717
* gh-127963
* gh-128712
* gh-128713

**Comment by ZeroIntensity** [comment]
Looks like a bug. We're missing `_Py_INCREF_IMMORTAL_STAT_INC` for immortal objects as well.

**Comment by EdNutting** [comment]
Thank you for such a quick reply! I'll try to clone CPython separately to create a PR to fix these over the next few days.

**Comment by Eclips4** [comment]
Thank you @EdNutting!
