### ISSUE TITLE
Wrong platform selection for _freeze_module

### ISSUE THREAD

**Issue by smurav** [python/cpython#127559]
https://github.com/python/cpython/blob/8c3fd1f245fbdc747966daedfd22ed48491309dc/PCbuild/pcbuild.proj#L21

_freeze_module uses wrong Win32 platform when I pass x64 platform to build.bat.

### Linked PRs
* gh-127560

**Comment by zooba** [comment]
Not a bug: you should pass `PreferredToolArchitecture=x64` if you want to change the build platform.
