### ISSUE TITLE
Free threading locking issues in `listobject.c`

### ISSUE THREAD

**Issue by colesbury** [python/cpython#127536]
# Bug report

In https://github.com/python/cpython/pull/127524, @mpage suggested adding an assert to check that the list object is locked when calling `ensure_shared_on_resize`. This uncovers a few more locking issues.

Additionally, we may return out of the critical section without unlocking here:

https://github.com/python/cpython/blob/c7dec02de2ed4baf3cd22ad094350265b52c18af/Objects/listobject.c#L956-L964

### Linked PRs
* gh-127580
* gh-127613

**Comment by corona10** [comment]
Ah.. it's my fault, I will take a look at it

**Comment by colesbury** [comment]
Thanks @corona10. I started some work on this (but didn't finish) yesterday. Here's what I had in case it's helpful:

https://github.com/colesbury/cpython/commit/49268ba74408cf36ae9ded8772a149704a2ab610

**Comment by picnixz** [comment]
@colesbury Are the build bot failures possibly related to that one or not? if not, I think we can close this one.

**Comment by colesbury** [comment]
I think the buildbot failures are unrelated. The other s390x 3.13 buildbots are passing. https://buildbot.python.org/#/builders/1469 is passing, but the runs slowed down (including on `test_site`) around the same time, but on the *following* commit, which makes me think some sort of network issue or problem with the machine.
