### ISSUE TITLE
Inconsistent scope search in comprehensions

### ISSUE THREAD

**Issue by Tikkoneus** [python/cpython#127542]
# Bug report

### Bug description:

```python
class Foo:
    A = [1,2,3]
    B = [2,3,4]

    FOO = [x for x in A]           # works
    BAR = [x for x in A if x in B] # NameError 'B' is not defined??
    BAZ = [x for x in A if x in A] # NameError 'A' is not defined??
    BAT = (lambda A,B: [x for x in A if x in B])(A,B) # explicit binding works
```

BAR produces:
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    class Foo:
    ^^^^^^^^^^
    ...<6 lines>...
        BAT = (lambda A,B: [x for x in A if x in B])(A,B) # explicit binding works
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "test.py", line 6, in Foo
    BAR = [x for x in A if x in B] # NameError 'B' is not defined??
                                ^
NameError: name 'B' is not defined
```

and, similarly, BAZ produces
```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    class Foo:
    ^^^^^^^^^^
    ...<6 lines>...
        BAT = (lambda A,B: [x for x in A if x in B])(A,B) # explicit binding works
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "test.py", line 7, in Foo
    BAZ = [x for x in A if x in A] # NameError 'A' is not defined??
                                ^
NameError: name 'A' is not defined
```

It appears that with no conditional the comprehension scope searches the class scope; but variable references within a conditional are not resolved using the same scope search (it appears to `LOAD_GLOBAL A`). Note that this latter behavior does not affect the resolution of variables _outside_ the conditional expression in the same comprehension. 

Also tested on 3.6 and 3.8, though those aren't options in this form.

### CPython versions tested on:

3.9, 3.13

### Operating systems tested on:

Windows

**Comment by JelleZijlstra** [comment]
This is correct behavior. Scopes nested within class scopes cannot see the class scope. See https://discuss.python.org/t/pep-709-one-behavior-change-that-was-missed-in-the-pep/26691 for some context.

**Comment by Tikkoneus** [comment]
I'm sorry, I don't quite follow. Since conditional expressions don't introduce new scope shouldn't both the comprehension and the conditional within it have the same enclosing scopes (regardless of whether it's nested or inlined)? How is it that the comprehension for FOO sees the class scope, as does the comprehension for BAR, but _only the conditional expression within_ the comprehension for BAR doesn't see class scope?

**Comment by JelleZijlstra** [comment]
The outermost iterable in a comprehension is evaluated in the enclosing scope.
