### ISSUE TITLE
Remove comment questioning 4-digit restriction for ‘Y’ in datetime.strptime patterns

### ISSUE THREAD

**Issue by bombs-kim** [python/cpython#127552]
found a comment in _strptime.py that I believe is unnecessary and potentially outdated:
https://github.com/python/cpython/blob/8c3fd1f245fbdc747966daedfd22ed48491309dc/Lib/_strptime.py#L304

The comment reads:
`# XXX: Does 'Y' need to worry about having less or more than 4 digits?`

This question seems irrelevant based on the current documentation and implementation standards. Here are my reasons:

1. Python documentation specifies a 4-digit restriction
The [Python documentation](https://docs.python.org/3/library/datetime.html#datetime.datetime.strptime) for datetime.strptime states: The `strptime()` method can parse years in the full [1, 9999] range, but years < 1000 must be zero-filled to 4-digit width. This makes it clear that Y is explicitly designed for 4-digit years only.

2. Supporting more than 4 digits is impractical
Years with 5 or more digits cannot be represented in the resulting datetime type. The datetime implementation enforces the [1, 9999] year range, which inherently limits support for larger year values.

3. Support for fewer than 4 digits tends to not standard-compliant
Some popular specifications expect a minimum of 4 digits for representing a year:
* ISO 8601: Requires at least 4 digits for year representation.
* RFC 3339: Also requires at least 4 digits for the year.
* POSIX.1-2008: While the standard doesn’t explicitly mandate the number of digits for %Y, implementations commonly expect 4 digits as a minimum.

Given these points, I propose removing the comment as it no longer adds value and could potentially confuse contributors or maintainers. If desired, I can submit a pull request to address this.

### Linked PRs
* gh-127590
* gh-127649
* gh-127650

**Comment by terryjreedy** [comment]
@brettcannon git blame says you added this comment in 2003 in commit 474335ce17c120eb74a17c5c4fd138694c535f77

**Comment by brettcannon** [comment]
Actually that comment was moved in 2003, but it [came into existence in Dec 2002](https://github.com/python/cpython/commit/5efc50d8afd31dc4cb0ef1b58899943eb0e4cb67), so just shy of 22 years ago. 😅

Anyway, since the implementation has required 4 digits since my code was first committed in July 2002, I think it's safe to say that the comment is no longer necessary. 😁

@bombs-kim if you want to do a PR then go for it! Otherwise I'm assigning this to myself not to forget about it.

**Comment by serhiy-storchaka** [comment]
Glibc implementation of `strftime()` can produce less than 4 digits. So currently `strptime()` is not compatible with system `strftime()`. There are some workarounds for `datetime`, but in the `time` module this is still an unsolved issue.

**Comment by bombs-kim** [comment]
@brettcannon
Thank you for the context on the comment’s history! I’d be happy to submit a PR to remove it. I’ll proceed with that shortly.

@serhiy-storchaka
I think you raise a valid point about compatibility with `strftime()` in some systems. However, I believe that specific issue might be better addressed in a separate issue or discussion, as it goes beyond the scope of this comment removal?
