### ISSUE TITLE
6.4.3. Pacchetti in Directory Multiple - missing Italian translation in tutorial

### ISSUE THREAD

**Issue by massimomartucci** [python/cpython#127515]
# Documentation

in https://docs.python.org/it/3/tutorial/modules.html , the first paragraph still has to be translated into Italian:

Packages support one more special attribute, [__path__](https://docs.python.org/it/3/reference/datamodel.html#module.__path__). This is initialized to be a [sequence](https://docs.python.org/it/3/glossary.html#term-sequence) of strings containing the name of the directory holding the package’s __init__.py before the code in that file is executed. This variable can be modified; doing so affects future searches for modules and subpackages contained in the package.

**Comment by AlexWaygood** [comment]
Hiya! You'll want to open an issue over at https://github.com/python/python-docs-it :-)
