### ISSUE TITLE
Check for type consistency for `PyUnicodeError` API

### ISSUE THREAD

**Issue by picnixz** [python/cpython#127691]
# Feature or enhancement

### Proposal:

This is a follow-up to https://github.com/python/cpython/pull/123380#discussion_r1865910020.

The idea is to add assertion type-checks when calling helper functions on unicode objects:

```C
    assert(PyObject_TypeCheck(exc, (PyTypeObject*)&PyExc_UnicodeError));
```

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127694

**Comment by encukou** [comment]
Thank you for the fix!
Do you want to add more, or should we close the issue?

**Comment by picnixz** [comment]
I don't think I'll add more in this specific PR. If I find something else I forgot, I'll just reuse it. I'll close this one as completed. Thanks for the merge!
