### ISSUE TITLE
`_SelectorSocketTransport.writelines` is missing a flow control check allowing writes to fill memory until exhausted

### ISSUE THREAD

**Issue by bdraco** [python/cpython#127655]
# Bug report

### Bug description:

This is the public issue for GHSA-fw89-6wjj-8j95

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, macOS

### Linked PRs
* gh-127656
* gh-127663
* gh-127664

**Comment by picnixz** [comment]
@bdraco I put all security labels but does it affect 3.9/3.10/3.11? (can't check for now)

**Comment by bdraco** [comment]
Its 3.12/3.13 only since `writelines` was implemented in asyncio selector transport in 3.12

**Comment by kumaraditya303** [comment]
Thanks @bdraco 

I assume aiohttp would be affected by this too if it uses writelines. If possible do share any performance numbers you have of how much impact the zero copy writes have made to aiohttp.

**Comment by bdraco** [comment]
> Thanks @bdraco
> 
> I assume aiohttp would be affected by this too if it uses writelines. If possible do share any performance numbers you have of how much impact the zero copy writes have made to aiohttp.

https://github.com/aio-libs/aiohttp/pull/10126 is the PR from a few hours ago that turned off zero copy writes

The [codspeed](https://github.com/aio-libs/aiohttp/pull/10126#issuecomment-2521586686) report shows the degrade performances however its not so great because we were pushing the CI pretty hard at the time and it wasn't keeping up.

This run https://codspeed.io/aio-libs/aiohttp/runs/675241d947498039ef29339c is probably the best one to look at as its going to show the difference the `memcpy` makes.

**Comment by bdraco** [comment]
Closing issue as linked PRs are merged
