### ISSUE TITLE
Issue in `binascii.{a2b,b2a}_qp` functions with newlines characters

### ISSUE THREAD

**Issue by picnixz** [python/cpython#127696]
# Bug report

### Bug description:

This was detected here: https://github.com/python/cpython/actions/runs/12200589926/job/34037087571#step:22:214

```py
>>> import binascii
>>> x = b'\n\r\n'
>>> y = binascii.b2a_qp(x, quotetabs=False, istext=True, header=False)
>>> z = binascii.a2b_qp(y, header=False)
>>> x
b'\n\r\n'
>>> y
'\n\n'
>>> z
b'\n\n'
```

I *think* the issue should only concern new lines characters like that but I honestly don't know whether this is the expected result or not. Note that the docs say:

> If the optional argument header is present and false, newline characters will be encoded as well; otherwise linefeed conversion might corrupt the binary data stream.

So it appears that '\r\n' is not correctly encoded as such. I'll investigate.

### CPython versions tested on:

CPython main branch

### Related

- #64320

**Comment by picnixz** [comment]
... This is a known issue in the code:

```C
    /* XXX: this function has the side effect of converting all of
     * the end of lines to be the same depending on this detection
     * here */
```

@serhiy-storchaka what can we do :( should we consider `\r\n` lines as being a single newline character or...?

**Comment by picnixz** [comment]
I'll consider this one different from #64320 since the `binascii.{a2b,b2a}_qp` functions were made to reflect the quopri module. But on the other hand, I don't know whether it's better to keep everything under the same issue (at least, here we would only focus on binascii and possibly change the tests and acknowledge the issue as a feature).

**Comment by picnixz** [comment]
Ok, so the pure Python implementation of `quopri` is correct:

```py
>>> import quopri
>>> quopri.encodestring(b'\n\r\n')
b'\n\n'  # C implementation
>>> quopri.a2b_qp = quopri.b2a_qp = None
>>> quopri.encodestring(b'\n\r\n')
b'\n=0D\n'  # Python implementation
```

**Comment by picnixz** [comment]
I think we should force the {encode,decode} functions to be compose as the identity. We explicitly state in `binascii.{a2b,b2a}_qp` docs that we don't want stream corruption. As a user, I expect `dec(enc(x)) == x`. @serhiy-storchaka Do you think we would break things if we were to do this? (namely reflect the Python implementation)

**Comment by serhiy-storchaka** [comment]
Isn't this a duplicate of #62222 (which cover more cases)?

**Comment by picnixz** [comment]
Oh... I didn't think there was yet another one. I'll close this one in favor of the other (it has a nicer issue number). Sorry for the duplicate (I'll also post the above).
