### ISSUE TITLE
Python 3.13 update fails on Linux Mint 22, ppa:deadsnakes/ppa

### ISSUE THREAD

**Issue by mrmatteastwood** [python/cpython#127625]
### Bug description:

An update for Python 3.13 arrived through the Linux Mint Update Manager yesterday and it cannot be installed. The following error messages appear:

```
E: /var/cache/apt/archives/python3.13_3.13.1-1+noble1_amd64.deb: trying to overwrite '/usr/bin/python3.13', which is also in package python3.13-minimal 3.13.0-1+noble1
E: /var/cache/apt/archives/libpython3.13-stdlib_3.13.1-1+noble1_amd64.deb: trying to overwrite '/etc/python3.13/sitecustomize.py', which is also in package libpython3.13-minimal:amd64 3.13.0-1+noble1
```

It sounds like there is a conflict of packages. Python 3.13 was installed from the deadsnakes PPA a few weeks ago.

### CPython versions tested on:

3.13

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
Please report issues in the deadsnakes PPA directly to https://github.com/deadsnakes/issues
