### ISSUE TITLE
No validation on erroneous creation of 2 or more parameter variables (VAR_KEYWORD and VAR_POSITIONAL) in inspect.Signature

### ISSUE THREAD

**Issue by ApostolFet** [python/cpython#127610]
# Bug report

### Bug description:

We can create `inspect.Signature` with two or more variable parameters, but this will be syntactically incorrect when defining the function manually:
```python
import inspect

parameters = [
    inspect.Parameter("args", kind=inspect.Parameter.VAR_POSITIONAL),
    inspect.Parameter("other_args", kind=inspect.Parameter.VAR_POSITIONAL),
    inspect.Parameter("kwargs", kind=inspect.Parameter.VAR_KEYWORD),
    inspect.Parameter("other_kwargs", kind=inspect.Parameter.VAR_KEYWORD),
]

signature = inspect.Signature(parameters)
print(signature)
```
OUTPUT:
```
(*args, *other_args, **kwargs, **other_kwargs)
```
And naturally we get a syntax error when defining a function with such a signature:
```python
def func(*args, *other_args, **kwargs, **other_kwargs):
    ...
```
OUTPUT:
```
  File "/home/apostol_fet/inspect_signature.py", line 13
    def func(*args, *other_args, **kwargs, **other_kwargs):
                    ^
SyntaxError: * argument may appear only once
```
Can we add validations for this case in `inspect.Signature.__init__`?
I would like to send a PR to fix this if it is not intended behavior.

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux, Windows

### Linked PRs
* gh-127657

**Comment by Eclips4** [comment]
cc @serhiy-storchaka 

I do think that this check would be useful. We already have a check for situations where user is trying to create a signature with a variadic keyword parameter before a variadic positional parameter:
```python
>>> import inspect
>>> parameters = [
...     inspect.Parameter("args", kind=inspect.Parameter.VAR_KEYWORD),
...     inspect.Parameter("kwargs", kind=inspect.Parameter.VAR_POSITIONAL),
... ]
>>> inspect.Signature(parameters)
Traceback (most recent call last):
  File "<python-input-2>", line 1, in <module>
    inspect.Signature(parameters)
    ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/home/eclips4/programming/programming-languages/cpython/Lib/inspect.py", line 2958, in __init__
    raise ValueError(msg)
ValueError: wrong parameter order: variadic keyword parameter before variadic positional parameter
>>>
```

**Comment by skirpichev** [comment]
> I would like to send a PR to fix this if it is not intended behavior.

Definitely is a bug.  Why do we want to produce syntactically incorrect Signature objects?!

**Comment by Agent-Hellboy** [comment]
Is it okay if I work on it, assuming OP isn’t working on it?

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution, @ApostolFet.
