### ISSUE TITLE
`re` patterns with improperly positioned Line Anchors ($,^) don't error during compilation, yield false positives when matched against the empty string (e.g: `.match("")`)

### ISSUE THREAD

**Issue by anabelle2001** [python/cpython#127644]
# Bug report

## Summary
The re library in Python does not raise an error when attempting to parse an unmatchable that incorrectly uses line anchors ($ and ^). 

```python3
re.compile("$$")  # Expected: Compilation Error
re.compile("^^") Expected: Compilation Error 
```

Furthermore, any regex composed entirely of line anchors will always match the empty string:
```python3
print(bool(re.compile("$$").match("")))   # Expected: Compilation Error, Got: True
print(bool(re.compile("$$$$$$").match(""))) # Expected: Compilation Error, Got: True
```

## Expected Behavior

Compilation of invalid patterns using $ and ^ (e.g., "$^", "$$", "$$$$$$", etc.) should raise an error during re.compile().
Patterns containing only $ and ^ should not match an empty string unless explicitly designed to do so (e.g., via .* or equivalent).

## Actual Behavior

Patterns with improper usage of line anchors ($ and ^) compile without error.
All patterns consisting only of $ and ^ unexpectedly match an empty string, when the only patterns in that group that should match are /$/, /^/, and /^$/

## Suggested Fix

Update the re library to strictly validate anchor usage during re.compile() and raise errors for invalid patterns.
Ensure that patterns like "$^", "$$", and "$$$$$$" behave consistently and intuitively, aligning with common regex behavior.

 ## More Test Cases
```python3
print(bool(re.compile("$$").match("")))   # Expected: Compilation Error, Got: True
print(bool(re.compile("$$$$$$").match(""))) # Expected: Compilation Error, Got: True
print(bool(re.compile("$$$$$$.*").match(""))) # Expected: Compilation Error, Got: True
print(bool(re.compile("$$$$$$.*").match("a"))) # Expected: False, Got: False
print(bool(re.compile("$$$$^^$$").match("")))  # Expected: Compilation Error, Got: True
```

here's an example of how other invalid regexes are handled:

```python3
print(bool(re.compile("[[").match(""))) # Expected: Compilation Error, Got: FutureWarning and Exception
```

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
The documentation for `match()` says (emphasis mine):

> If **zero** or more characters at the beginning of string match this regular expression, return a corresponding [Match](https://docs.python.org/3/library/re.html#re.Match)

So it's as expected. In addition, the pattern is *valid* so even if the behaviour may not be as you expected, there shouldn't be any *compilation error* (it's not an error per se).

@serhiy-storchaka could you confirm my analysis?

**Comment by serhiy-storchaka** [comment]
I confirm.

What made you think this must be an error, @anabelle2001? Have you encountered this behavior in any other regexp implementations?

**Comment by anabelle2001** [comment]
huh. looks like i was wrong here. the formal definition for regexes in perl, javascript, and xml specify that ^ and $ are assertions that the cursor is at the start / end of a line.
