### ISSUE TITLE
Drop `--wasi preview2` from `wasi.py`

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#127652]
# Bug report

### Bug description:

Need to remove

https://github.com/python/cpython/blob/23f2e8f13c4e4a34106cf96fad9329cbfbf8844d/Tools/wasm/wasi.py#L300-L301

as we only officially support preview1.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Other

### Linked PRs
* gh-127704

**Comment by rruuaanng** [comment]
Do we need to fix it to `--wasi preview1`?, or just remove it `--wasi preview2`.

**Comment by brettcannon** [comment]
> Do we need to fix it to `--wasi preview1`?, or just remove it `--wasi preview2`.

There is no `--wasi preview1` flag; this is just to remove the flag as it's not necessary and is technically experimental (see the PR I just posted).

**Comment by brettcannon** [comment]
The automatic backport to 3.13 failed, but since this is an optional change I'm not going to worry about it.
