### ISSUE TITLE
Add `SCHED_DEADLINE` and `SCHED_NORMAL` constants to `os` module

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#127688]
# Feature or enhancement

### Proposal:

This issue suggests adding new os constants.

`os.SCHED_DEADLINE`
```
# deadline scheduling
# Set the current schedule to real-time schedule, To be precise, it
# is not real-time scheduling, but it is relatively real-time.
prio = os.sched_param(sched_priority=10)
os.sched_setscheduler(0, os.SCHED_DEADLINE, prio)
```

`SCHED_NORMAL` is the same as `SCHED_OTHER`.
But to run in the old linux, we can't remove `SCHED_OTHER`, even if it no longer exists in the current main branch.
But we still need to add `SCHED_NORMAL`, because `SCHED_OTHER` only exists in the old distribution.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-127689

**Comment by encukou** [comment]
I don't have `SCHED_NORMAL` on my Fedora 41. I'd like to test with a system that has it; are you aware of one?

**Comment by rruuaanng** [comment]
Can you try running the following code? `SCHED_NORMAL` has been present in Linux 2.6.12 and still exists in later versions.

```
#include <linux/sched.h>
#include <stdio.h>                                                                                                                                                                                                                                                                                                                                                      
int main()
{
        printf("%d ", SCHED_NORMAL);
        /* It should output 0 */
        return 0;
}
```
In pyrepl
```
>>> import os
>>> os.SCHED_NORMAL
0
>>> os.SCHED_OTHER
0
```

ref:
https://github.com/torvalds/linux/blob/9ee1c939d1cb936b1f98e8d81aeffab57bae46ab/include/linux/sched.h#L132
my os: `Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-86-generic x86_64)`

**Comment by encukou** [comment]
Looking around, it seems like the kernel headers in `linux/*.h` are meant for the kernel, rather than user-space programs -- e.g. [from this LWN article](https://lwn.net/Articles/113349/):

> The use of kernel headers in user space has long been discouraged.

I didn't find any official source saying it's OK to include `linux/sched.h` outside the kernel. Am I overthinking this?

**Comment by encukou** [comment]
OK.
Merged, thank you for the contribution!
