### ISSUE TITLE
`test_binascii.test_b2a_qp_a2b_qp_round_trip` flaky

### ISSUE THREAD

**Issue by colesbury** [python/cpython#127697]
The hypothesis test test_b2a_qp_a2b_qp_round_trip checks that `binascii.a2b_qp(binascii.b2a_qp(<value>))` gives the original value. However, this is not always true when `istext=True` (the default) and the value contains a mix of `\n` and `\r\n` new lines.

```python
import binascii
>>>binascii.b2a_qp(b'\n\r\n', istext=True)
b'\n\n'
>>> binascii.a2b_qp(b'\n\n')
b'\n\n'
```

https://github.com/python/cpython/blob/36c6178d372b075e9c74b786cfb5e47702976b1c/Lib/test/test_binascii.py#L413-L426

See also https://github.com/python/cpython/issues/64320

Seen in https://github.com/python/cpython/actions/runs/12200589926/job/34037087571

cc @sobolevn @picnixz

**Comment by colesbury** [comment]
@picnixz already filed the issue: https://github.com/python/cpython/issues/127696

**Comment by picnixz** [comment]
xD that's what happens when two people work on the same issue but not in the same room
