### ISSUE TITLE
Python 3.10.16 release is missing GPG signatures

### ISSUE THREAD

**Issue by edmorley** [python/cpython#127601]
# Bug report

### Bug description:

The Python 3.10.16 release is missing the GPG signature files (note no "GPG" column in the table):
https://www.python.org/downloads/release/python-31016/

eg:

```
$ curl -I https://www.python.org/ftp/python/3.10.16/Python-3.10.16.tgz.asc
HTTP/2 404
content-type: text/html
x-clacks-overhead: GNU Terry Pratchett
server: nginx
via: 1.1 varnish, 1.1 varnish, 1.1 varnish
accept-ranges: bytes
age: 0
date: Wed, 04 Dec 2024 12:02:53 GMT
x-served-by: cache-lga21939-LGA, cache-lga21939-LGA, cache-lhr-egll1980061-LHR
x-cache: MISS, HIT, MISS
x-cache-hits: 0, 3, 0
x-timer: S1733313773.280317,VS0,VE73
strict-transport-security: max-age=63072000; includeSubDomains; preload
content-length: 146
```

This is causing our release process for the new binaries to fail, blocking releasing this security update to users:
https://github.com/heroku/heroku-buildpack-python/actions/runs/12159162945/job/33908683580#step:4:19

All of the other releases mentioned in https://blog.python.org/2024/12/python-3131-3128-31111-31016-and-3921.html have their GPG signatures, as does the last Python 3.10.x release (3.10.15).

This seems to be a repeat of #123807.

cc @pablogsal 

### CPython versions tested on:

3.10

### Operating systems tested on:

Linux

**Comment by hugovk** [comment]
Thanks for the report, we're looking into it.

**Comment by hugovk** [comment]
The GPG signatures are now in place:

https://www.python.org/downloads/release/python-31016/

**Comment by edmorley** [comment]
Thank you :-)
