### ISSUE TITLE
Importing submodule overwrites global namespace in `__init__.py`

### ISSUE THREAD

**Issue by ChenyangGao** [python/cpython#127623]
# Bug report

### Bug description:

Assume that I have a module with the following directory structure:

```
./test_module
├── __init__.py
└── myfunction.py
```

The specific code inside the files is as follows:

`__init__.py`

```python
def myfunction():
    print("myfunction")

def main():
    myfunction()
```

`myfunction.py` is an empty file.

```console
Python 3.13.0 | packaged by Anaconda, Inc. | (main, Oct  7 2024, 16:25:56) [Clang 14.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from test_module import main
>>> main()
myfunction
>>> main.__globals__["myfunction"]
<function test_module.myfunction()>
```

Everything works fine up to this point, but when I import the `myfunction` module, it modifies the global namespace of the already imported `__init__` module:

```console
>>> from test_module.myfunction import *
>>> myfunction
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    myfunction
NameError: name 'myfunction' is not defined
>>> main()
Traceback (most recent call last):
  File "<python-input-4>", line 1, in <module>
    main()
    ~~~~^^
  File "/Users/gcy/test_module/__init__.py", line 5, in main
    myfunction()
    ~~~~~~~~~~^^
TypeError: 'module' object is not callable
>>> main.__globals__["myfunction"]
<module 'test_module.myfunction' from '/Users/gcy/test_module/myfunction.py'>
```

### CPython versions tested on:

3.13

### Operating systems tested on:

macOS

**Comment by skirpichev** [comment]
I think this it how the import statement expected to work, i.e.: https://docs.python.org/3.13/reference/simple_stmts.html#the-import-statement

What do you expected instead and why?

**Comment by ChenyangGao** [comment]
> I think this it how the import statement expected to work, i.e.: https://docs.python.org/3.13/reference/simple_stmts.html#the-import-statement
> 
> What do you expected instead and why?

I hope that if a name is already in the __init__.py, it won't be overwritten in any subsequent imports

Someone who wants to import a submodule should write it like this

```python
import module.name as name
```

But if you import like this, use the name already in the __init__.py first

```python
from module import name
```

**Comment by terryjreedy** [comment]
There is no `__init__` module; `test_module.__init__.py` populates a module named 'test_module', just as `tkinter.__init__.py` populates the 'tkinter' module.  There is no bug in the '>>>' interactions, which take place in the `__main__` module. If you need more explanation, please ask on a help forum such as https://discuss.python.org/c/help/7.  If you ask on the latter, where other beginners can see the explaination, I or someone will explain more.

**Comment by terryjreedy** [comment]
Re-reading, this is actually a feature change which, even if technically possible (I an not sure), would break lots of code, making it 'socially' impossible.
