### ISSUE TITLE
Add colour to `test.regrtest` output

### ISSUE THREAD

**Issue by hugovk** [python/cpython#127718]
# Feature or enhancement

In Python 3.13 we added colour output to the new REPL, tracebacks and doctest, and in 3.14 to unittest, that can also be controlled with the `PYTHON_COLORS`, `NO_COLOR` and `FORCE_COLOR` environment variables:

* https://docs.python.org/3.14/whatsnew/3.14.html#unittest
* https://docs.python.org/3.14/using/cmdline.html#using-on-controlling-color

Let's add colour to `test.regrtest` output.

### Linked PRs
* gh-127719

**Comment by JainamDosi** [comment]
Hey , i would like to contribute to this issue , can you just help me get started , please ?

**Comment by hugovk** [comment]
Hello, thank you for your interest. The link directly above your comment, and the one under "Linked PRs" in the issue description, are to a PR that already implements this.

See https://devguide.python.org/getting-started/fixing-issues/ for some tips.
