### ISSUE TITLE
`PyUnstable_AtExit` isn't well tested and undocumented

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#127791]
# Bug report

### Bug description:

While working on #126908, @vstinner noted that this part of `PyUnstable_AtExit` looks wrong: https://github.com/python/cpython/blob/cef0a90d8f3a94aa534593f39b4abf98165675b9/Modules/atexitmodule.c#L45-L47

This will result in loss of callbacks after one has been stored, because the second-to-last one is always overwritten. Noted in gh-118915, `PyUnstable_AtExit` is also undocumented. I'll work on fixing both.

### CPython versions tested on:

3.13, 3.14, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-127793
* gh-127819

**Comment by disconnect3d** [comment]
> This will result in loss of callbacks after one has been stored (...)

Hi, just out of curiosity: what does this exactly mean? Is this a memory leak or an UAF?

**Comment by ZeroIntensity** [comment]
Memory leak, I think? The next pointer in the linked list is overwritten.
