### ISSUE TITLE
Update docstrings to official standard

### ISSUE THREAD

**Issue by StanFromIreland** [python/cpython#127723]
# Documentation

Some files have a mixture of both `" ... "` and `""" ... """` docstrings should we mass update them to `""" ...  """` which I believe is the standard as per PEP 257.

> For consistency, always use """triple double quotes""" around docstrings.

I can mass update this so that it all conforms to the standard if it will be merged.

**Comment by ericvsmith** [comment]
Thanks, but this is a cosmetic change, and not the kind of change we usually accept.
