### ISSUE TITLE
(TYPO) Error message value swap  -> ValueError: not enough values to unpack 

### ISSUE THREAD

**Issue by HumanBot000** [python/cpython#127796]
# Bug report

### Bug description:

```python
for a,b in string:
```
This raised issue is ```ValueError: not enough values to unpack (expected 2, got 1)``` 
But it should be
```
ValueError: not enough values to unpack (expected 1, got 2)
```
 because two values should be unpacked, whilst string expects only one

### CPython versions tested on:

3.10

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
I can't reproduce this behavior on Python 3.9-3.14. Can you please provide the full code?

**Comment by HumanBot000** [comment]
> Hello! I can't reproduce this behavior on Python 3.9-3.14. Can you please provide the full code?

```python
    for a, b in "foo":
        # Nothing in here
        pass
 ```
 Results in
 ```
 ValueError: not enough values to unpack (expected 2, got 1)
 ```
 Exact Python version is ```3.10.10```

**Comment by JelleZijlstra** [comment]
The error message is correct. The for loop iterates over the string, so on each iteration we do something like `a, b = c`, where `c` is a single-character string (from iterating over the string). That means we expect an iterable with 2 members (for a and b), but we get one with one member (the character), as the error message says.

**Comment by Eclips4** [comment]
Oh, I misunderstood you. Yes, as @JelleZijlstra said, there's no bug. We expect two elements (a, b), but after the first iteration, we have only one element, which is incorrect.

**Comment by terryjreedy** [comment]
As Jelle said, there is only 1 value in each iteration.  The first iteration tries to execute `a,b = 'f'`.
