### ISSUE TITLE
tuple.__str__ call __repr__ and not __str__ for underlying items.

### ISSUE THREAD

**Issue by ccossou** [python/cpython#127760]
# Bug report

### Bug description:

After numpy 2.0, __repr__ changed for all numpy types (e.g; np.int64 and np.float64). 

This had an impact on tuple.__str__, because it seems that tuple.__str__ refers to item.__repr__ instead of __str__. 

Here, I use Python 3.12.8 and numpy 2.2.0

We now have this behavior:
```python
>>> import numpy as np
>>> x = np.int64(45)
>>> print((x,x))
(np.int64(45), np.int64(45))
>>> print(x)
45
```

If you use python 3.11.11 and numpy 1.26.0, you had:
```python
>>> import numpy as np
>>> x = np.int64(45)
>>> print((x,x))
(45, 45)
>>> print(x)
45
```

I personally think that the type has no place in a __str__ conversion, but that's my opinion. Thus, I'm not sure it's a bug or a feature. But I would tend to think that tuple.__str__ should call __str__ and tuple.__repr__ should call __repr__

### CPython versions tested on:

3.11, 3.12

### Operating systems tested on:

Linux

**Comment by picnixz** [comment]
It would be a feature and a breaking-change feature. For most simple containers, the `__str__` method is the same as their `__repr__` method (this is already the case in Python 3.9). The docs also say (emphasis mine):

> Called by [str(object)](https://docs.python.org/3/library/stdtypes.html#str), the default [`__format__()`](https://docs.python.org/3/reference/datamodel.html#object.__format__) implementation, and the built-in function [print()](https://docs.python.org/3/library/functions.html#print), to compute the **"informal"** or nicely printable string representation of an object. The return value must be a [str](https://docs.python.org/3/library/stdtypes.html#textseq) object.
> 
> This method differs from [`object.__repr__()`](https://docs.python.org/3/reference/datamodel.html#object.__repr__) in that there is no expectation that [`__str__()`](https://docs.python.org/3/reference/datamodel.html#object.__str__) return a valid Python expression: a more convenient or concise representation can be used.

Now, if you want to make containers use `__str__` for their items, this should be discussed on Discourse (https://discuss.python.org/c/ideas/6) and likely would need a PEP. I'm going to close this one as `not planned` (sorry, this issue requires a wider discussion).
