### ISSUE TITLE
Global and nonlocal exception aliases are removed from scope

### ISSUE THREAD

**Issue by noahbkim** [python/cpython#127771]
# Bug report

### Bug description:

When you alias an exception caught in `except` to a `global` or `nonlocal` name, that name will be removed from its original scope. For `global`:

```python
error = None

def f():
    global error
    try:
        raise ValueError()
    except ValueError as error:
        pass

# Output
error before: None
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    print(f"error after: {error}")
                          ^^^^^
NameError: name 'error' is not defined. Did you mean: 'OSError'?
```

For `nonlocal`:

```python
def g():
    error = None

    def f():
        nonlocal error
        try:
            raise ValueError()
        except ValueError as error:
            pass

    print(f"error before: {error}")
    f()
    print(f"error after: {error}")

g()

# Output
error before: None
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    g()
  File "test.py", line 13, in g
    print(f"error after: {error}")
                          ^^^^^
UnboundLocalError: cannot access local variable 'error' where it is not associated with a value
```

This is a bit counterintuitive. Is it intended behavior for any reason?

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by ronaldoussoren** [comment]
The behaviour is described in [the language reference](https://docs.python.org/3/reference/compound_stmts.html#except-clause).  [PEP 3110](https://peps.python.org/pep-3110/) explains why the feature was added, basically to avoid reference loops between the caught exception and the current frame that need the GC to clear up when using local variables.

**Comment by noahbkim** [comment]
Thanks for the quick response. While it'd be nice for explicitly `global`/`nonlocal` names to be exempt from this rule, it's such a niche case that I'm happy with "working as intended".
