### ISSUE TITLE
Fix detection of Windows Server 2025 by `platform.py`

### ISSUE THREAD

**Issue by Wulian233** [python/cpython#127732]
# Feature or enhancement

### Proposal:

Windows Server 2025 was officially released a month ago and is now detected as Server 2022 instead of Server 2025

Microsoft Lifecycle:
https://learn.microsoft.com/en-us/lifecycle/products/windows-server-2025
https://www.microsoft.com/en-us/windows-server/blog/

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-127733
* gh-127762
* gh-127763

**Comment by zooba** [comment]
Once the backports are merged, this can be closed.
