### ISSUE TITLE
PEP 649: incorrect `__annotations__` when type with same name is created inside class

### ISSUE THREAD

**Issue by randolf-scholz** [python/cpython#127701]
# Bug report

### Bug description:

I played around with `__annotations__`, and noticed that it returns an incorrect result when a type is defined both inside and outside the class scope: [[mypy-playground]](https://mypy-play.net/?mypy=latest&python=3.12&gist=66e613308ca9b7e244c23fbd9ff076e8)

```python
class Bar: ...

class Foo:
    x: Bar = Bar()

    class Bar: ...
    y: Bar = Bar()

reveal_type(Foo.x)  # __main__.Bar
reveal_type(Foo.y)  # __main__.Foo.Bar
assert isinstance(Foo.x, Bar)  # ✅
assert isinstance(Foo.y, Foo.Bar)  # ✅
```

However, `Foo.__annotations__` returns `{'x': <class '__main__.Foo.Bar'>, 'y': <class '__main__.Foo.Bar'>}`

### CPython versions tested on:

3.14.0~a2 from deadsnakes PPA

### Operating systems tested on:

Linux

**Comment by carljm** [comment]
I think this is expected and intended behavior with PEP 649. Annotation expressions become lazily resolved, so it is not expected that the resolution results will be the same as the eager resolution of names in normal non-annotation expressions.

**Comment by JelleZijlstra** [comment]
Carl is correct, this is expected behavior.
