### ISSUE TITLE
The error message for odd-length input to `bytes.fromhex` is cryptic

### ISSUE THREAD

**Issue by Kodiologist** [python/cpython#127740]
# Bug report

### Bug description:

```pytb
Python 3.14.0a2+ (main, Dec  8 2024, 10:50:32) [GCC 14.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> bytes.fromhex('deadbee')
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    bytes.fromhex('deadbee')
    ~~~~~~~~~~~~~^^^^^^^^^^^
ValueError: non-hexadecimal number found in fromhex() arg at position 7
>>> bytes.fromhex('deadbeef')
b'\xde\xad\xbe\xef'
```

I suggest: `ValueError: fromhex() arg must be of even length`.

### CPython versions tested on:

3.12, CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-127756
* gh-127818

**Comment by srinivasreddy** [comment]
@Kodiologist are you working on it ?

**Comment by Kodiologist** [comment]
Nope, it's up for grabs right now.

**Comment by srinivasreddy** [comment]
I am taking it .

**Comment by picnixz** [comment]
Marking this one as a feature rather than a bug since changing exception messages may break CI (https://github.com/python/mypy/pull/17849) and users may rely on exception messages.

**Comment by rhettinger** [comment]
> users may rely on exception messages.

Users may, but users shouldn't ;-).

We don't want to change error messages unnecessarily; however, if the error message is bad, it should get fixed.  To misquote Spock, the needs of many people reading error messages outweigh the needs of the few who overspecify their tests.

Bad error messages are a major source of user frustration.

**Comment by picnixz** [comment]
I'm not against changing the error message but I honestly think we don't need to backport it to 3.12 and 3.13 (personally I wouldn't be against the backports but I learned the hard way that changing error messages in bug fix releases could cause un-necessary additional work =/).

**Comment by hauntsaninja** [comment]
Thanks for fixing this, like Raymond says, better error messages are very valuable

cfbolz chose not to backport the PR, which seems fine to me. After all, the worse error message was around for 18 years old. So closing the issue, but if someone feels strongly about backport, by all means do so
