### ISSUE TITLE
asyncio.create_subprocess_shell() cannot be killed if command contains a pipe

### ISSUE THREAD

**Issue by n-peugnet** [python/cpython#127874]
# Bug report

### Bug description:

I am trying to run a subprocess shell command using asyncio.create_subprocess_shell() and then kill it after some amount of time.
When the command contains a pipe, then the subprocess is impossible to kill from within python. It can still be killed from the outside obviously (e.g. the kill command).

Here is a code that exhibits this behaviour:

```python
import asyncio

async def test():
    proc = await asyncio.create_subprocess_shell("yes | while read l; do sleep 1; echo $l; done")
    await asyncio.sleep(1)
    proc.kill()
    await proc.wait()

asyncio.run(test())
```

A similar command, without a pipe, can be killed, for example: `"while true; do sleep 1; echo test; done"`

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux

**Comment by n-peugnet** [comment]
Well, after searching a little bit more, I found this solution but with Popen: https://github.com/python/cpython/issues/119059#issuecomment-2111355552

As it seems asyncio's subprocesses are based on this function I tested this code and it seems to work correctly:

```python
import asyncio
import os
import signal

async def test():
    proc = await asyncio.create_subprocess_shell(
        "yes | while read l; do sleep 1; echo $l; done",
        process_group=0,
    )
    await asyncio.sleep(1)
    os.killpg(proc.pid, signal.SIGINT)
    await proc.wait()

asyncio.run(test())
```

**Comment by asvetlov** [comment]
Yes, asyncio subprocesses are based on Popen.
And yes, nothing to do here from asyncio perspective; the mentioned comment describes the problem and the solution very well.
