### ISSUE TITLE
`PySequence_In` is not documented

### ISSUE THREAD

**Issue by ghost** [python/cpython#127896]
# Documentation

`PySequence_In` is part of the limited C-API, and has no document. PEP 3100 ( https://peps.python.org/pep-3100/ ) says this function is "To be removed," but it has not been removed in the latest version, so documentation seems to be needed.

### Linked PRs
* gh-127979

**Comment by ZeroIntensity** [comment]
New applications shouldn't use it, we just keep it for the limited API. I'm not sure we need to encourage more usage by documenting it.

**Comment by encukou** [comment]
It's exactly equivalent to `PySequence_Contains`.

The docs should mention that it's deprecated, and show the preferred spelling.

**Comment by koyuki7w** [comment]
If this function is deprecated, should we add [Py_DEPRECATED](https://docs.python.org/3/c-api/intro.html#c.Py_DEPRECATED) to the declaration?
https://github.com/python/cpython/blob/2de048ce79e621f5ae0574095b9600fe8595f607/Include/abstract.h#L773

**Comment by ZeroIntensity** [comment]
No idea what the precedent is here, but I suspect that it should be [soft deprecated](https://docs.python.org/3/glossary.html#term-soft-deprecated) for compatibility reasons.

**Comment by skirpichev** [comment]
> The docs should mention that it's deprecated, and show the preferred spelling.

Formally, it's not deprecated yet;)

> I suspect that it should be [soft deprecated](https://docs.python.org/3/glossary.html#term-soft-deprecated) for compatibility reasons.

Maybe not.  [Search on the Github](https://github.com/search?q=%2FPySequence_In+*%5C%28%2F+AND+NOT+is%3Afork&type=code) shows only few projects, which use this.  On another hand, support this has 0 maintenance burden.
