### ISSUE TITLE
argparser's `parse_known_args` parses incorrectly if an unhandled arg is a prefix of a handled arg

### ISSUE THREAD

**Issue by nathan-az** [python/cpython#127808]
# Bug report

### Bug description:

```python
from argparse import ArgumentParser


args = [f'--argname_full', "foo", f'--argname', 'bar']

parser = ArgumentParser()
parser.add_argument(args[0], type=str, default=None)

parsed_args = parser.parse_known_args(args)
print(parsed_args)

# prints:
# (Namespace(argname_full='bar'), [])
```
I'm unsure whether this is a bug or an unfortunate side effect of having to handle shorthand argument names. Note that not only is the arg value not the expected one (`foo`), but the "middle" args are completely lost in the tuple.

I came across this issue by having automatically injected args suffixed with `date` and another with `datetime`, and our library only expecting the `datetime` one (then having it assigned the wrong value). This can be handled by renaming args or adding the arg to the parser, but it seems reasonable that this could cause relatively silent errors in other cases.

Apologies if this is documented or expected behaviour but I was unable to find other examples.

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, macOS

**Comment by Agent-Hellboy** [comment]
Hi @nathan-az 
> Apologies if this is documented or expected behaviour but I was unable to find other examples.

refer https://docs.python.org/3/library/argparse.html?utm_source=chatgpt.com#allow-abbrev and see if this is what you are looking for 

```python
from argparse import ArgumentParser

args = [f'--argname_full', "foo", f'--argname', 'bar']

parser = ArgumentParser()
parser.add_argument(args[0], type=str, default=None)

parsed_args = parser.parse_known_args(args)
print(parsed_args)

# prints:
#(Namespace(argname_full='foo'), ['--argname', 'bar'])
```

**Comment by nathan-az** [comment]
Ah perfect. I think enabling `allow_abbrev` by default can cause some unpredictable behaviour (e.g. `_date` and `_datetime` case), but probably has a good reason. Closing as this is clearly by design and is properly documented, cheers.
