### ISSUE TITLE
Unexpected outcome while accessing the value of a dictionary

### ISSUE THREAD

**Issue by amitesh-the-coder** [python/cpython#127834]
# Bug report

### Bug description:

```python
d = {(1, 2, 3): 'ab'} #Initializing a  dictionary
d[(1,2,3)]
>>>'ab' #output of d[(1,2,3)] as expected
d[1,2,3]
>>>'ab' #expected error while executing d[1,2,3] but got the output 'ab'
```
![Screenshot 2024-12-11 222713](https://github.com/user-attachments/assets/3786478f-7149-4c7e-bbc9-5a1e0b073652)

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

**Comment by Eclips4** [comment]
Hello!
I don't see any error on your screenshot, can you elaborate, please?

**Comment by amitesh-the-coder** [comment]
> Hello! I don't see any error on your screenshot, can you elaborate, please?
i was expecting an error while executing d[1,2,3] as 1,2,3 should be given as tuple that is d[(1,2,3)]

**Comment by srinivasreddy** [comment]
That is not an error,  parentheses are optional .

**Comment by Eclips4** [comment]
> > Hello! I don't see any error on your screenshot, can you elaborate, please?
> 
> i was expecting an error while executing d[1,2,3] as 1,2,3 should be given as tuple that is d[(1,2,3)]

Ah, sorry, I misunderstood you. Parentheses in tuple syntax is optional.
```python
x = (1, 2, 3)
# or
x = 1, 2, 3
```
So, there's no bug.
