### ISSUE TITLE
Unable to build a HACL* module on macOS under Catalina

### ISSUE THREAD

**Issue by aeiouaeiouaeiouaeiouaeiouaeiou** [python/cpython#127897]
# Bug report

### Bug description:

The recent HACL* change in Python 3.14.0a2 cause local build breakage on macOS below Catalina due to lack of support for `aligned_alloc` (also `memset_s` on older macOS <10.9).

Fixes for the affected dependency have already been submitted to the repositories:
- https://github.com/FStarLang/karamel/pull/504
- https://github.com/hacl-star/hacl-star/pull/1012

### CPython versions tested on:

3.14

### Operating systems tested on:

macOS

### Linked PRs
* gh-127932

**Comment by gpshead** [comment]
Thanks for taking this on and working to get the fixes properly into the upstream repos.

FYI - macos catalina 10.15 is end of life and insecure for anyone to have attached to a network.  But we do appear to still support building back to 10.13 for some reason so this seemed worthwhile.

Closing as I believe that merge should fix it?
