### ISSUE TITLE
Moving `_PyMem_RawStrdup` to private API causes build failure

### ISSUE THREAD

**Issue by clin1234** [python/cpython#127991]
#106320 causes build failure in https://github.com/marcelotduarte/cx_Freeze/issues/2568#issuecomment-2545781130

What is the recommended replacement for the now private function?

**Comment by tomasr8** [comment]
Made private here: https://github.com/python/cpython/pull/107187

I think as a replacement you can do what the function is doing internally, that is, call `PyMem_RawMalloc` and `memcpy`:
https://github.com/python/cpython/blob/52d552cda7614c7aa9f08b680089c630587e747f/Objects/obmalloc.c#L1047-L1057

**Comment by ZeroIntensity** [comment]
@vstinner Do you think it's worth adding a public variation of `PyMem_Strdup` and `PyMem_RawStrdup`?

**Comment by vstinner** [comment]
@clin1234: Would you be ok to close the issue? Or do you think that something else should be done? I'm not sure why you closed your cx_Freeze upstream PR.

**Comment by clin1234** [comment]
I made a separate pull request replacing the private function with strdup (marcelotduarte/cx_Freeze#2738)
