### ISSUE TITLE
Add Base2 encoding methods (Base2MSBF and Base2LSBF) to the Base64 module

### ISSUE THREAD

**Issue by FajarKim** [python/cpython#127977]
# Feature or enhancement

### Proposal:

I propose adding new encoding methods to the Base64 module to support Base2 encoding with two variations:

- Base2MSBF (Most Significant Bit First)
- Base2LSBF (Least Significant Bit First)

These methods are designed to enable bit-level encoding with configurable bit order:

- Base2MSBF: Arranges bits from the most significant to the least significant.
- Base2LSBF: Arranges bits from the least significant to the most significant.

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-127978

**Comment by picnixz** [comment]
Hi, thanks for the suggestion but this can be achieved natively and does not require an additional function for `base64`. This module is meant to host the functions described by [RFC 4648](https://datatracker.ietf.org/doc/html/rfc4648.html) and "base-2" encoding is not part of it.

One could however imagine adding some "binarify" method to `binascii` which has `hexlify` but transforming bytes to their binary representation can be achieved using `format`. Similarly if you want to change the bit order, then it would suffice to reverse the sequence.

I'm closing this one as `not planned` but feel free to open a discourse proposal (after checking if a similar feature has already been requested): https://discuss.python.org/c/ideas/6 or ask for help on https://discuss.python.org/c/help/7 if you need help. I don't see much the usecase for it, especially if there are one-liners alternatives.
