### ISSUE TITLE
Add `STARTF_HOLOGRAPHIC` constant to `_winapi` module

### ISSUE THREAD

**Issue by rruuaanng** [python/cpython#127961]
# Feature or enhancement

### Proposal:

This issue suggests adding new _winapi constants.

It is usually in the `dwFlags` member of `lpStartupInfo` parameter of `CreateProcess` and is used to run the application on a holographic device, such as Microsoft HoloLens or Windows Mixed Reality (Maybe there are others, but I haven't heard of them.)

e.g.
```
_winapi.CreateProcess(
                    python_exe, cmd,
                    None, None, False, 0, env, None,
                    STARTUPINFO(dwFlags=STARTF_HOLOGRAPHIC))
```
(It is only available in the when the system DDI is greater than win10 future.)

@zooba

### Has this already been discussed elsewhere?

No response given

**Comment by rruuaanng** [comment]
I'm not sure if this flag is worth adding, so I'll have to wait for Steve answer.

**Comment by zooba** [comment]
Yeah, I really don't know what the future holds here on what's best to do about it.

In general though, the `_winapi` module is only to support the standard library, so if we don't have a use for it in the stdlib, we wouldn't add it. I don't believe we have a need for this constant, so let's leave it for now.
