### ISSUE TITLE
[tests] Backport test_cext and test_cppext (C API tests) from main to the 3.12 branch

### ISSUE THREAD

**Issue by vstinner** [python/cpython#127906]
The C API is not well tested in the 3.12 branch. I propose to backport test_cext and test_cppext from the main branch to the 3.12 branch.

Example of recent C++ regression: https://github.com/python/cpython/issues/127902

### Linked PRs
* gh-127908
* gh-127912
* gh-127914
* gh-127915
* gh-127916
* gh-127919
* gh-127920
* gh-127923
* gh-127993
* gh-127994
* gh-132902
* gh-132904
* gh-132905

**Comment by vstinner** [comment]
On the 3.12 branch, test_cext currently fails with these warnings:

```
  C:\victor\python\3.12\include\cpython/unicodeobject.h(205): error C2220: the following warning is treated as an error
  C:\victor\python\3.12\include\cpython/unicodeobject.h(205): warning C4100: '_unused_op': unreferenced formal parameter
  C:\victor\python\3.12\include\cpython/unicodeobject.h(395): warning C4100: '_unused_op': unreferenced formal parameter
  C:\victor\python\3.12\include\cpython/pytime.h(192): warning C4115: 'timeval': named type definition in parentheses
  extension.c(22): warning C4100: '_unused_module': unreferenced formal parameter
  extension.c(44): warning C4100: '_unused_module': unreferenced formal parameter
```

I backported MSVC support in Py_UNUSED() to 3.12 to fix unicodeobject.h: PR gh-127907.

**Comment by vstinner** [comment]
> C:\victor\python\3.12\include\cpython/pytime.h(192): warning C4115: 'timeval': named type definition in parentheses

I wrote https://github.com/python/cpython/pull/127908 to fix this pytime.h warning.

**Comment by vstinner** [comment]
I tested manually: with "[3.12] gh-127906: Test the limited C API in test_cppext", test_cppext is able to catch https://github.com/python/cpython/issues/127902 regression!

**Comment by encukou** [comment]
A 3.13 buildbots is failing on `test_cext`: https://buildbot.python.org/#/builders/1419/builds/385

**Comment by encukou** [comment]
Also, on 3.12, `Py_LIMITED_API` tests should be skipped under `Py_TRACE_REFS`; see https://buildbot.python.org/#/builders/1197/builds/1034/steps/6/logs/stdio

**Comment by vstinner** [comment]
> Also, on 3.12, Py_LIMITED_API tests should be skipped under Py_TRACE_REFS; see https://buildbot.python.org/#/builders/1197/builds/1034/steps/6/logs/stdio

Oh, right: I created PR gh-127993 to fix this buildbot.

**Comment by vstinner** [comment]
> A 3.13 buildbots is failing on test_cext: https://buildbot.python.org/#/builders/1419/builds/385

```
  extension.c(56): error C2220: the following warning is treated as an error
  extension.c(56): warning C4116: unnamed type definition in parentheses
```

Oh, I see. I forgot to backport yet another fix for Py_BUILD_ASSERT_EXPR() on Windows. I created PR gh-127994 to fix this buildbot as well.

Thanks @encukou for reporting these issues! Sadly, test_cext and test_cppext are skipped on GitHub CI jobs since they are too slow.

**Comment by vstinner** [comment]
The 3.12 TraceRefs and 3.13 buildbots are back to green. I close the issue.

**Comment by encukou** [comment]
Thank you!
