### ISSUE TITLE
Clinic causes compiler warnings when a setter is defined before a getter with a docstring

### ISSUE THREAD

**Issue by ZeroIntensity** [python/cpython#128083]
# Bug report

### Bug description:

Found while working on #127946

This is sort of an extension to #127341, but not the exact same issue. If you define a setter before a getter, and then that getter has a docstring, a macro redefinition warning will occur, because the setter code sets the docstring to `NULL`.

Quick repro:

```c
/*[clinic input]
@setter
Test.test
[clinic start generated code]*/

/*[clinic input]
@getter
Test.test

my silly docstring
[clinic start generated code]*/
```

The simplest fix is to just `#undef` the `DOCSTR` macro in the getter if it's been defined already. I have a PR at #127950.

### CPython versions tested on:

CPython main branch

### Operating systems tested on:

Linux

### Linked PRs
* gh-128102

**Comment by erlend-aasland** [comment]
Thanks for the report and the fix, Peter!
