### ISSUE TITLE
Add BidirectionalDict recipe to `collections`

### ISSUE THREAD

**Issue by nineteendo** [python/cpython#128001]
# Documentation

Originally suggested by [@picnixz's comment](https://discuss.python.org/t/add-bimap-a-bidirectional-dictionary-to-collections-module/73113/11), recipe by me:

```python
class BidirectionalDict(UserDict):
    def __init__(self, *args, **kwargs):
        self.inverse_data = {}
        super().__init__(*args, **kwargs)

    def __setitem__(self, key, value):
        if key in self.data:
            if value == (old_value := self.data[key]):
                return

            del self.inverse_data[old_value]

        if value in self.inverse_data:
            raise ValueError("Duplicate value")

        self.data[key] = value
        self.inverse_data[value] = key

    def __delitem__(self, key):
        value = self.data[key]
        del self.data[key]
        del self.inverse_data[value]

    @property
    def inverse(self):
        inverse_bidict = BidirectionalDict()
        inverse_bidict.data = self.inverse_data
        inverse_bidict.inverse_data = self.data
        return inverse_bidict
```

**Comment by picnixz** [comment]
My suggestion about the recipes was to first have a recipe-like page for `collections` itself. Currently, no such page exists but I don't know if @rhettinger would be willing to have a recipe page for this module. As for the above recipe,  I'm not sure if a recipe based on UserDict and not inheriting `collections.abc.Mapping` instead is preferrable or not with two explicit internal dicts and an explicit interface (same as Guava's BiMap)

**Comment by nineteendo** [comment]
Well, can't we just add it as a UserDict recipe like the other recipes?

- [ChainMap Examples and Recipes](https://docs.python.org/3/library/collections.html#chainmap-examples-and-recipes)
- [deque Recipes](https://docs.python.org/3/library/collections.html#deque-recipes)
- [OrderedDict Examples and Recipes](https://docs.python.org/3/library/collections.html#ordereddict-examples-and-recipes)

As for inheriting from UserDict:

- the implementation is easier (no need to implement `__getitem__`, `__iter__`, and `__len__`)
- it implements more methods for us: `__repr__`, `__or__`, `__ror__`, `__ior__`, `__copy__`, `copy` and `fromkeys`

**Comment by picnixz** [comment]
- `fromkeys` wouldn't be helpful because you have one value mapped to multiple keys. So in a bimap, this would cause a "duplicated value error". 
- I missed the recipes section, my bad.

**Comment by rhettinger** [comment]
If someone wants a bidirectional dictionary, they should `pip install` a mature, well documented tool such as:  https://github.com/jab/bidict.  

Also, this isn't suitable as a "recipe". We mostly use those to teach ways to use, extend, or modify existing tools in the standard library.  It might qualify as an FAQ, but it isn't even a frequently asked question. Also there are many possible implementation strategies and APIs. It isn't the job of the docs to choose between those. It isn't even clear that a class based solution is any better than what most people typically do with two simple dictionaries and a dual update.

If anything were to be added to collections, the `SortedContainers` project would be a much better candidate. However, even that is having a better life outside of the standard library.
