### ISSUE TITLE
generate numpy modules from python, cython, and numpy source code

### ISSUE THREAD

**Issue by dshawshank** [python/cpython#128084]
# Bug report

### Bug description:

Hello everyone, has anyone tried to generate numpy modules from python, cython, and numpy source code? I wonder if you can share some of the files generated by the generation process, including those *.c files generated from *.c.src suffix files (for example, arraytypes.c files converted from arraytypes.c.src).

### CPython versions tested on:

3.11

### Operating systems tested on:

Linux, Windows

**Comment by skirpichev** [comment]
You opened issue, claiming you have found a bug.  Could you, please, a clear and concise description of what happened?

So far, this looks you are asking for help.  This is a bug tracker for CPython, not a support forum.  Then better is to start a thread in https://discuss.python.org/c/help/7 or ask for help in numpy mail lists.
