### ISSUE TITLE
Fix the font size and shortcut display of the turtledemo menu

### ISSUE THREAD

**Issue by Xiaokang2022** [python/cpython#128062]
### Bug description:

The font size of turtledemo's menu bar is too large and the shortcut keys are not displayed well enough.

Actually:

<img width="732" alt="2024-12-18-18-07-39" src="https://github.com/user-attachments/assets/496c27e6-00c4-4b85-8d20-671e92a38792" />

But better: (Changed the font and the way shortcuts are displayed)

<img width="732" alt="2024-12-18-18-05-29" src="https://github.com/user-attachments/assets/f4e96311-d656-483f-ab33-be19c9187e6d" />

I'll create a PR later to fix it.

### CPython versions tested on:

3.13

### Operating systems tested on:

Windows

### Linked PRs
* gh-128063
* gh-128101

**Comment by terryjreedy** [comment]
On my MacBook Air, with a small screen, fontsize 12 is too small as the default, used for the top bar, appears to be 14.  Command+- and Command+= are the keys that work in the text widget.  Agree with leaving size alone and using the standard accelerator option.

**Comment by terryjreedy** [comment]
The 3.12 backport failed with a merge conflict.  I consider it low priority.
