### ISSUE TITLE
Difference Between Lock and RLock in Python Threading

### ISSUE THREAD

**Issue by codexguru666** [python/cpython#128177]
# Documentation
The difference between Lock and RLock in Python's threading module lies in how they behave when the thread that owns the lock tries to acquire it again (reentrancy) and what happens when the thread releases it:

Lock (Non-Reentrant Lock)
A Lock can be acquired by a thread only once. If the same thread tries to acquire it again without first releasing it, the thread will block and potentially lead to a deadlock.
If the thread holding the lock returns (e.g., its function ends), the lock remains acquired, and other threads will continue to block until it is explicitly released.
Example:
import threading

lock = threading.Lock()

def example_lock():
    lock.acquire()
    print("Lock acquired")
    # lock.acquire()  # This would block and cause a deadlock.
    lock.release()
    print("Lock released")

example_lock()

(A clear and concise description of the issue.)

**Comment by rruuaanng** [comment]
>  class threading.RLock
    This class implements reentrant lock objects. A reentrant lock must be released by the thread that acquired it. Once a thread has acquired a reentrant lock, the same thread may acquire it again without blocking; the thread must release it once for each time it has acquired it.

> class threading.Lock
    The class implementing primitive lock objects. Once a thread has acquired a lock, subsequent attempts to acquire it block, until it is released; any thread may release it.

Emm... It seems that their documentation is very clear, maybe I didn't understand your question.

ref:
https://docs.python.org/3.14/library/threading.html#threading.Lock
https://docs.python.org/3.14/library/threading.html#threading.RLock

**Comment by picnixz** [comment]
I agree that the documentation is sufficiently clear. We also mention the possibility of deadlocking (just the paragraph above RLock's docs). Closing as `not an issue`.
