### ISSUE TITLE
Multiprocessing code succeeds in 3.13 but fails in 3.14

### ISSUE THREAD

**Issue by nickdrozd** [python/cpython#128145]
# Bug report

### Bug description:

The following code runs successfully in 3.13.1 (and earlier versions) but fails in 3.14.0a3+ (5a584c8f54b):

```python
from __future__ import annotations

from unittest import TestCase
from multiprocessing import Manager, Pool

LETTERS: dict[str, int]

def add_letter(letter: str) -> None:
    LETTERS[letter] += 1

class TestAsdf(TestCase):
    def setUp(self):
        global LETTERS

        LETTERS = Manager().dict(
            a = 0,
            s = 0,
            d = 0,
            f = 0,
        )

    def test_asdf(self):
        with Pool() as pool:
            pool.map(
                add_letter,
                list('asdf'))

        print(LETTERS)
```

Run successfully, it produces this output:

```
$ python3.11 -m unittest asdf

{'a': 1, 's': 1, 'd': 1, 'f': 1}
```

In 3.14, it fails with `NameError`:

```pytb
$ python3.14 -m unittest asdf

======================================================================
ERROR: test_asdf (asdf.TestAsdf.test_asdf)
----------------------------------------------------------------------
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.14/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/home/nick/asdf.py", line 9, in add_letter
    LETTERS[letter] += 1
    ^^^^^^^
NameError: name 'LETTERS' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nick/asdf.py", line 24, in test_asdf
    pool.map(
    ~~~~~~~~^
        add_letter,
        ^^^^^^^^^^^
        list('asdf'))
        ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.14/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/local/lib/python3.14/multiprocessing/pool.py", line 774, in get
    raise self._value
NameError: name 'LETTERS' is not defined
```

This example looks stupid, but it is based on real-world test code.

### CPython versions tested on:

3.11, 3.13, 3.14, CPython main branch

### Operating systems tested on:

Linux

**Comment by JelleZijlstra** [comment]
I believe this is because of a change in the default start method on Linux. See https://github.com/python/cpython/issues/125714#issuecomment-2423296713 for a fuller explanation.

**Comment by nickdrozd** [comment]
I don't understand how that relates to this code. How should this code be updated to work in 3.14?

**Comment by picnixz** [comment]
> I don't understand how that relates to this code. 

Global objects are not picked the same way they are picked now.

> How should this code be updated to work in 3.14?

I believe using `multiprocessing.set_start_method('fork')` should be sufficient but I haven't tested the solution (we changed the default start method from 'fork' to 'forkserver' on Linux)

**Comment by nickdrozd** [comment]
Thanks, `set_start_method('fork')` is the solution here.

It would be good to make it explicit in the "What's new" page that this can be a breaking change on Linux and that `set_start_method('fork')` retains the old behavior. Currently Linux is only obliquely mentioned as "platforms other than macOS & Windows", and `set_start_method` is mentioned but without the critical `'fork'` arg.

https://github.com/python/cpython/issues/84559#issuecomment-1416278935 predicts "people requiring "fork" will have an unhappy surprise to debug in 3.14" -- that time is now upon us.

**Comment by picnixz** [comment]
I can think of something for improving the changelog. You're right in saying that this is a breaking change. I also think we should highligh it in the final release notes (cc @hugovk as the RM)

**Comment by CypherGrue** [comment]
Simpler test case for this

```python
from multiprocessing import Process, set_start_method

g = None

def process():
    global g
    print ('forked', g)

if __name__ == '__main__':
    g = 1
    print ('main', g)

    #set_start_method('fork')
    Process(target=process).start()
```

3.9: forked 1
3.12: forked 1
3.13: forked 1
3.14: forked None
3.14 with set_start_method('fork'): forked 1
