### ISSUE TITLE
Allow to customize XML declaration header when writing ElementTree output

### ISSUE THREAD

**Issue by pprossi** [python/cpython#128136]
# Feature or enhancement

### Proposal:

At the moment it is hardcoded with single quotes and differs from examples in the documentation.

https://github.com/python/cpython/blob/5a584c8f54bbeceae7ffa501291e29b7ddc8a0b9/Lib/xml/etree/ElementTree.py#L722

### Has this already been discussed elsewhere?

No response given

### Linked PRs
* gh-128095

**Comment by picnixz** [comment]
Closing as `not planned` for now as per https://github.com/python/cpython/pull/128095#issuecomment-2558492471.
