### ISSUE TITLE
Add feature from Microsoft VBA language: Ability to pause, edit and then RESUME code after modification during runtime instead of having to rerun. Saves enormous time!

### ISSUE THREAD

**Issue by MyProjectsPage** [python/cpython#128163]
# Feature or enhancement

### Proposal:

Hi,

Microsoft VBA programming language has a fantastic feature which is that you can pause the code during runtime, make an edit, and resume the running with the new modifications without having to restart the program from all over again. This saves hours!

Imagine this situation: Your code has been running for an hour then you discover an upcoming line that you'd like to modify to avoid an error. You pause the code, fix it, and resume the program. Currently you have to rerun the whole code from all over again for the tinest modification, which is very annoying.

This is somehow similar to Jupyter notebook concept but without having to live with the drawbacks of using a Jupyter notebook. Can python script somehow treat each line behind the scenes as if it is a seperate jupyter notebook cell?

Thanks

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by hugovk** [comment]
Hello, this tracker is for bugs and well-defined enhancements.

Please discuss this first in the Ideas https://discuss.python.org/c/ideas/6 or Help https://discuss.python.org/c/users/7 forums.
