### ISSUE TITLE
_thread.get_ident returns a result with an exception set

### ISSUE THREAD

**Issue by AraHaan** [python/cpython#128189]
# Bug report

### Bug description:

I am working on a python program that is async in nature and is carefully created using the C API as a C extension by using a generic awaitable object, Sadly, I had to implement what ``asyncio.run`` does manually due to it not liking how the awaitable object is designed because the only way to get the awaitable object the C api function returns is that it must first run the function in order for ``asyncio.run`` to then await the awaitable. However the 3.14 change to throw RuntimeError when get_event_loop() is called prior to ``asyncio.run`` actually creating it became a problem that I needed to solve with manually doing:

```py
loop = asyncio.new_event_loop()
asyncio.set_event_loop(loop)
loop.run_until_complete(awaitable)
loop.close()
```

from the C code. Everything works well, Except when I Ctrl+C the program to terminate it and ``loop.close()`` returns NULL, I then ``PyErr_Print()``'d it and see that:

```
Traceback (most recent call last):
  File "asyncio\base_events.py", line 707, in run_until_complete
  File "asyncio\base_events.py", line 678, in run_forever
  File "asyncio\base_events.py", line 1995, in _run_once
  File "asyncio\windows_events.py", line 446, in select
  File "asyncio\windows_events.py", line 775, in _poll
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "asyncio\proactor_events.py", line 688, in close
  File "threading.py", line 1435, in current_thread
SystemError: <built-in function get_ident> returned a result with an exception set
RuntimeError: Result of closing the event loop was 'NULL'.
```

And I seen the line and it looks that threading.py set's it's ``get_ident()`` to ``_thread.get_ident()`` and then uses it on the line the traceback mentions. The issue is, it's hard to debug why the ``_thread.get_ident()`` function did this.

See also: https://github.com/ZeroIntensity/pyawaitable/issues/36

### CPython versions tested on:

3.14, CPython main branch

### Operating systems tested on:

Windows

**Comment by picnixz** [comment]
cc @ZeroIntensity (since you're active and I'm not)

**Comment by ZeroIntensity** [comment]
Will investigate a bit later.

**Comment by ZeroIntensity** [comment]
I haven't look at it too hard, but this is probably just something that happens as a result of how you're dealing with CTRL+C. `PyThreadHandleObject_get_ident` is probably being *called* with a `KeyboardInterrupt` set. Are you missing a `NULL` check somewhere?

**Comment by AraHaan** [comment]
It could be because I don't call ``PyErr_Clear()`` after I check the errors from ``run_until_complete`` (which is obtained from ``PyErr_Occurred()``). This is within the if ``error`` not ``NULL`` and then I do some error checks to filter out specific errors. That might be the problem.

**Comment by picnixz** [comment]
Is this one still valid? or can this be closed?

**Comment by ZeroIntensity** [comment]
I'm pretty sure this is user-error.

**Comment by AraHaan** [comment]
Yeah, the error indicator was not cleared prior to the call to “close”.
