### ISSUE TITLE
[DOC] `__new__()` is (indeed) a static method

### ISSUE THREAD

**Issue by eliegoudout** [python/cpython#128162]
The doc [states](https://docs.python.org/3/reference/datamodel.html#object.__new__):
> object.__new__(cls[, ...])
>
>    Called to create a new instance of class `cls.`[`__new__()`](https://docs.python.org/3/reference/datamodel.html#object.__new__) is a **static method** (special-cased so you need not declare it as such) that takes the class of which an instance was requested as its first argument.

Should it not be "**class method**" instead?

**Comment by TeamSpen210** [comment]
No, it is actually turned into [a static method](https://github.com/python/cpython/blob/2a66dd33dfc0b845042da9bb54aaa4e890733f54/Objects/typeobject.c#L4264-L4266). But when called, [`cls` is passed manually](https://github.com/python/cpython/blob/2a66dd33dfc0b845042da9bb54aaa4e890733f54/Objects/typeobject.c#L10263). You can see this by doing `SomeClass.__dict__['__new__']`, to bypass the descriptor and see the actual stored object.

**Comment by eliegoudout** [comment]
Oh great! My bad, thank you for pointers! :)

**Comment by eliegoudout** [comment]
Could you help me understand the reason behind this?
