### ISSUE TITLE
Error during build on unguarded use of new symbols on macOS

### ISSUE THREAD

**Issue by zanieb** [python/cpython#128135]
# Feature or enhancement

### Proposal:

CPython builds run against the latest macOS version and unguarded use of new symbols does not throw an error. However, building CPython on older versions of macOS is supported. Consequently, regressions are not caught, e.g.:

- https://github.com/python/cpython/issues/128134
- https://github.com/python/cpython/issues/123797
- https://github.com/python/cpython/issues/75782

Enabling `-Werror=unguarded-availability-new` would be great to catch these before they become a problem downstream.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Links to previous discussion of this feature:

This was discussed briefly [in Discord]( https://discord.com/channels/854719841091715092/1319027902322446373/1319341178633584753)

**Comment by zanieb** [comment]
(Working on a patch for this)

**Comment by zanieb** [comment]
Another complexity is https://github.com/astral-sh/python-build-standalone/issues/210 / https://github.com/astral-sh/python-build-standalone/pull/422 — if this is in the `CFLAGS` in `sysconfig` it is used to build extension modules in some packages which causes failures.

**Comment by zanieb** [comment]
Perhaps this is dumb to ask, but.. this flag is clang only? I don't think there's an obvious equivalent integration in gcc?

**Comment by picnixz** [comment]
I'm not aware of an equivalent one for gcc. Btw, I think we already had an issue for this one: https://github.com/python/cpython/issues/100384 but I think it's better to keep the latest in this case unless you want to move the discussion out there.

**Comment by zanieb** [comment]
Ah thank you @picnixz — I don't have a preference for which issue we use but agree it makes sense to close one of them.

**Comment by picnixz** [comment]
Let's move the discussion on the original one. I'll edit the issue to include your findings.
