### ISSUE TITLE
Improve performance of copy.copy

### ISSUE THREAD

**Issue by eendebakpt** [python/cpython#128118]
# Feature or enhancement

### Proposal:

Similar to the approached used for `copy.deepcopy` in #114266 we can simplifly the implementation of `copy.copy` and improve performance by checking on the type of the argument using a lookup. 

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

### Linked PRs
* gh-128119

**Comment by erlend-aasland** [comment]
Resolved with:

- #128119
