### ISSUE TITLE
Add missing error checks for usages of `PyIter_Next`

### ISSUE THREAD

**Issue by WolframAlph** [python/cpython#128198]
# Bug report

### Bug description:

Not all usages of `PyIter_Next` in the codebase comply with specified behavior: https://github.com/python/cpython/blob/180d417e9f9456defd4c5b53cae678c318287921/Objects/abstract.c#L2905-L2919.
One example would be: https://github.com/python/cpython/blob/180d417e9f9456defd4c5b53cae678c318287921/Objects/frameobject.c#L246-L268

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-128199
* gh-128272
* gh-128273

**Comment by picnixz** [comment]
Closing since completed and backported. Thanks for the fix.
