### ISSUE TITLE
`Doc/requirements-oldest-sphinx.txt` needs to be regenerated

### ISSUE THREAD

**Issue by Eclips4** [python/cpython#128227]
# Bug report

### Bug description:

Due to https://github.com/python/cpython/security/dependabot/12 and https://github.com/python/cpython/security/dependabot/11, the dependency file must be regenerated (it's fine if those links go nowhere, only triagers and core devs see it). CPython Doc is not vulnerable to these two CVE's, but I guess it's ok to bump Jinja's minor version to "silence" these dependabot alerts.

New contributors are welcome!
You need to:
* clone CPython repository and `cd` to the `Doc` directory
* create && activate venv
* `pip install "Sphinx~=7.2.6"`
* Output of `pip freeze` should be pasted into `Doc/requirements-oldest-sphinx` (from line 15 to the end)

Do not write the `NEWS` entry, triage/core dev will aply `skip-news` label. 

### CPython versions tested on:

CPython main branch

### Linked PRs
* gh-128228
* gh-128229
* gh-128230

**Comment by wrongnull** [comment]
I'm going to send a pr
Thanks for the opportunity @Eclips4

**Comment by Eclips4** [comment]
Thank you!
