### ISSUE TITLE
[Feature req] Wayland support for TKInter

### ISSUE THREAD

**Issue by Twig6943** [python/cpython#128204]
# Feature or enhancement

### Proposal:

(I don't know where to post this)

### Has this already been discussed elsewhere?

No response given

### Links to previous discussion of this feature:

.

**Comment by ZeroIntensity** [comment]
Tkinter works on Wayland for me. What system are you using? Anyways, this has to be discussed on [DPO](https://discuss.python.org/c/ideas/6).

**Comment by Twig6943** [comment]
@ZeroIntensity It runs via xwayland. I'll create an issue over at the python forums soon.

**Comment by Twig6943** [comment]
https://discuss.python.org/t/feature-request-wayland-support-for-tkinter/75198
