### ISSUE TITLE
Allow to skip XML declaration in minidom's toprettyxml / toxml / writexml

### ISSUE THREAD

**Issue by G-Guillard** [python/cpython#128285]
# Feature or enhancement

### Proposal:

The XML declaration is currently hardcoded in `Document.writexml()`, which is in turn called by `toxml()` and `toprettyxml()`.

It is often convenient to use these functions to parse XML which purpose is to be inserted in another XML document, but one has to get rid of the declaration set by `writexml()`.

It would be handy and trivial to add a default `xml_declaration=True` parameter, which would skip the declaration when set to False.

### Has this already been discussed elsewhere?

This is a minor feature, which does not need previous discussion elsewhere

**Comment by picnixz** [comment]
Wouldn't https://docs.python.org/3/library/xml.etree.elementtree.html#xml.etree.ElementTree.ElementTree.write be sufficient for your needs? I'm not sure we want to change the API of minidom which was meant to be minimalistic.

**Comment by G-Guillard** [comment]
It does indeed, with the help of ElementTree.indent for pretty printing.

Thanks !

**Comment by picnixz** [comment]
Closing as `not planned` for now, but the feature request was legitimate though.
