### ISSUE TITLE
Docs: the result of running example code of `itertools.tee` is not correct

### ISSUE THREAD

**Issue by Snoopy1866** [python/cpython#128372]
# Documentation

I’m using Python 3.13 and learning about itertools.tee from the [official Python documentation](https://docs.python.org/3.13/library/itertools.html#itertools.tee). I copied the example code for the lookahead function, but when I ran it in the REPL, the output wasn’t the same as described in the documentation.

Look at the pictures below for more details about the diffrent output between REPL and documentation.

![image](https://github.com/user-attachments/assets/f3fd5151-3e5e-4eb8-9be0-409cf582e1b1)

![image](https://github.com/user-attachments/assets/2b236ccd-abd4-41c7-a3b5-9599d48e4aa2)

# Enviroment
- Windows 11 23H2 22631.4602
- Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32

**Comment by skirpichev** [comment]
Can't reproduce this on Linux:
```pycon
>>> from itertools import tee
>>> def lookahead(tee_iterator):
...      "Return the next value without moving the input forward"
...      [forked_iterator] = tee(tee_iterator, 1)
...      return next(forked_iterator)
...      
>>> iterator = iter('abcdef')
>>> [iterator] = tee(iterator, 1)
>>> next(iterator)
'a'
>>> lookahead(iterator)
'b'
>>> next(iterator)
'b'
```

Can you try latest 3.13 release?
