### ISSUE TITLE
'python3-distutils' has no installation candidate

### ISSUE THREAD

**Issue by devansh-903** [python/cpython#128376]
# Bug report

### Bug description:

```python
# Add a code block here, if required
```
Package python3-distutils is not available, but is referred to by another package.. This may mean that the package is missing, has been obsoleted, or
is only available from another source
E: Package 'python3-distutils' has no installation candidate

### CPython versions tested on:

3.12

### Operating systems tested on:

Linux

**Comment by skirpichev** [comment]
It's not clear what exactly you run to get this output, but the distutils module removed from the stdlib in 3.12.

**Comment by terryjreedy** [comment]
There is no 'python-distutils' listed on pypi.org.  Perhaps the other, unnamed, package meant to import [standard-distutils](https://pypi.org/project/standard-distutils/).  The latter appears to be a copy of the latest distutils from the stdlib as of 3.11.9.  Inform the other package maintainer of the bug.  Many packages have a sibling distutils package, as evident from searching pypi for 'distutils'.
