### ISSUE TITLE
SRE: Atomic Grouping (?>...) is not supported

### ISSUE THREAD

**Issue by b7a711ff-d634-47b2-ad1b-41e5ae806c8b** [python/cpython#34627]
BPO | [433030](https://bugs.python.org/issue433030)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @ezio-melotti, @serhiy-storchaka
PRs | <li>python/cpython#31982</li>
Files | <li>[issue2636-01.patch](https://bugs.python.org/file10646/issue2636-01.patch "Uploaded as text/plain at 2008-06-17.17:49:03 by timehorse")</li><li>[re_atomic_groups.patch](https://bugs.python.org/file37182/re_atomic_groups.patch "Uploaded as text/plain at 2014-11-11.20:23:00 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2001-06-14.08:30:56.000>
labels = ['expert-regex', 'type-feature', 'library', '3.11']
title = 'SRE: Atomic Grouping (?>...) is not supported'
updated_at = <Date 2022-03-21.16:28:37.831>
user = 'https://bugs.python.org/effbot'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-21.16:28:37.831>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Regular Expressions']
creation = <Date 2001-06-14.08:30:56.000>
creator = 'effbot'
dependencies = []
files = ['10646', '37182']
hgrepos = []
issue_num = 433030
keywords = ['patch']
message_count = 12.0
messages = ['53164', '63284', '63288', '64634', '64735', '65777', '68337', '113201', '114621', '231041', '231049', '415685']
nosy_count = 10.0
nosy_names = ['effbot', 'georg.brandl', 'terry.reedy', 'rsc', 'timehorse', 'ezio.melotti', 'mrabarnett', 'THRlWiTi', 'abacabadabacaba', 'serhiy.storchaka']
pr_nums = ['31982']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue433030'
versions = ['Python 3.11']
```

</p></details>

**Comment by hugovk** [comment]
Closing because GH-31982 has been merged.

**Comment by gpshead** [comment]
This feature addition led to https://github.com/python/cpython/issues/106052
