### ISSUE TITLE
locale.resetlocale is broken

### ISSUE THREAD

**Issue by 4c2b7522-0b4f-44bf-88f6-bd714c4af4b8** [python/cpython#35920]
BPO | [504219](https://bugs.python.org/issue504219)
--- | :---
Nosy | @malemburg, @tim-one, @loewis, @mhammond, @akuchling, @birkenfeld, @birkenfeld, @ncoghlan, @devdanzin
Dependencies | <li>bpo-813449: locale.getdefaultlocale doesnt handle all locales gracefully</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2002-01-16.04:56:12.000>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'locale.resetlocale is broken'
updated_at = <Date 2021-12-23.23:26:47.402>
user = 'https://bugs.python.org/syvere'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-23.23:26:47.402>
actor = 'ajaksu2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2002-01-16.04:56:12.000>
creator = 'syvere'
dependencies = ['813449']
files = []
hgrepos = []
issue_num = 504219
keywords = []
message_count = 13.0
messages = ['8774', '8775', '8776', '8777', '8778', '8779', '8780', '8781', '114172', '185023', '185041', '240667', '293297']
nosy_count = 11.0
nosy_names = ['lemburg', 'tim.peters', 'loewis', 'mhammond', 'akuchling', 'georg.brandl', 'georg.brandl', 'jlgijsbers', 'syvere', 'meonkeys', 'ncoghlan', 'ajaksu2']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue504219'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by ncoghlan** [comment]
Trying to come up with a short LC_MONETARY example for PEP-538, I just ran into what seems to be a related problem with locale.resetlocale(), which is that it doesn't work properly for categories other than LC_CTYPE: locale.getdefaultlocale() doesn't let you say which category you're actually interested in, so even if you specific a category for resetlocale(), it's going to look at the LC_CTYPE setting, \*NOT* the one for the category you're interested in.


So perhaps a suitable design change here would be to update resetlocale() to just pass an empty string (letting the underlying platform API call figure out the right default), rather than passing the result of locale.getdefaultlocale()?

**Comment by arhadthedev** [comment]
The issue is no longer reproducible (at least on Windows 10; can someone test it on Vista?):

```python
>>> import locale
>>> locale.getlocale(locale.LC_NUMERIC)
(None, None)
>>> locale.getdefaultlocale()
<stdin>:1: DeprecationWarning: Use setlocale(), getpreferredencoding(False) and getlocale() instead
('ru_RU', 'cp1251')
>>> locale.setlocale(locale.LC_ALL, 'no_NO')
'no_NO'
>>> locale.getlocale(locale.LC_ALL)
('no_NO', 'ISO8859-1')
>>> locale.getlocale(locale.LC_NUMERIC)
('no_NO', 'ISO8859-1')
```

**Comment by erlend-aasland** [comment]
> The issue is no longer reproducible (at least on Windows 10; can someone test it on Vista?):

Windows 10, Norwegian Nynorsk locale, Python 3.11:

```console
H:\> py -3.11
Python 3.11.0b1 (main, May  7 2022, 22:58:47) [MSC v.1931 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> locale.getdefaultlocale()
<stdin>:1: DeprecationWarning: Use setlocale(), getencoding() and getlocale() instead
('nn_NO', 'cp1252')
>>> locale.resetlocale()
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "C:\Program Files\Python311\Lib\locale.py", line 636, in resetlocale
_setlocale(category, _build_localename(getdefaultlocale()))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
locale.Error: unsupported locale setting
>>>
```

**Comment by vstinner** [comment]
Oh, I forgot to deprecate resetlocale() when I deprecated getdefaultlocale(). I proposed https://github.com/python/cpython/pull/93196 to deprecate resetlocale(). See https://github.com/python/cpython/issues/90817 for the rationale.

**Comment by AA-Turner** [comment]
`locale.resetlocale()` is now deprecated from Python 3.11 and will be removed in 3.13 (#93196), closing this issue.

A

**Comment by vstinner** [comment]
You should use ``locale.setlocale(locale.LC_ALL, "")`` instead.

**Comment by alexcTropic** [comment]
How can we modify the default value now?
