### ISSUE TITLE
Support RFC 2392 in email package

### ISSUE THREAD

**Issue by warsaw** [python/cpython#37351]
BPO | [626452](https://bugs.python.org/issue626452)
--- | :---
Nosy | @warsaw, @tiran, @devdanzin, @bitdancer, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2002-10-21.18:00:49.000>
labels = ['type-feature', 'library', 'expert-email']
title = 'Support RFC 2392 in email package'
updated_at = <Date 2015-02-23.04:29:13.967>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2015-02-23.04:29:13.967>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'email']
creation = <Date 2002-10-21.18:00:49.000>
creator = 'barry'
dependencies = []
files = []
hgrepos = []
issue_num = 626452
keywords = []
message_count = 8.0
messages = ['53667', '53668', '59296', '168955', '168956', '168957', '168958', '169001']
nosy_count = 7.0
nosy_names = ['barry', 'christian.heimes', 'ajaksu2', 'r.david.murray', 'meatballhat', 'martin.panter', 'moijes12']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue626452'
versions = ['Python 3.4']
```

</p></details>

**Comment by arhadthedev** [comment]
> A clear and concise description of what the bug is.

@warsaw Ten years passed since the last activity. Can the issue be declared officially dead and buried for good?

**Comment by warsaw** [comment]
@arhadthedev 

> Ten years passed since the last activity. Can the issue be declared officially dead and buried for good?

Yup.  Until and unless some volunteer comes forward, I don't see RDM or myself having the bandwidth to add it.
