### ISSUE TITLE
ftplib: Strict RFC 959 (telnet in command channel)

### ISSUE THREAD

**Issue by 23aeb1a4-d162-4473-a32d-9adcac86cf2c** [python/cpython#39394]
BPO | [821862](https://bugs.python.org/issue821862)
--- | :---
Nosy | @phdru, @ods, @giampaolo
Files | <li>[ftplib.py.patch](https://bugs.python.org/file5624/ftplib.py.patch "Uploaded as text/plain at 2003-10-11.18:04:55 by @phdru"): The patch for ftplib.py to implement telnet option</li><li>[ftplib.py.patch2](https://bugs.python.org/file5625/ftplib.py.patch2 "Uploaded at 2004-10-21.09:52:23 by @phdru"): This is another solution to the same problem. Instead of patching FTP class the patch creates TelnetFTP subclass.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2003-10-11.18:04:55.000>
labels = ['type-bug', 'library']
title = 'ftplib: Strict RFC 959 (telnet in command channel)'
updated_at = <Date 2013-05-26.00:59:29.963>
user = 'https://github.com/phdru'
```

bugs.python.org fields:
```python
activity = <Date 2013-05-26.00:59:29.963>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2003-10-11.18:04:55.000>
creator = 'phd'
dependencies = []
files = ['5624', '5625']
hgrepos = []
issue_num = 821862
keywords = ['patch']
message_count = 4.0
messages = ['44756', '84537', '114127', '114133']
nosy_count = 3.0
nosy_names = ['phd', 'ods', 'giampaolo.rodola']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue821862'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by zitterbewegung** [comment]
I am seeing if the patches apply cleanly to main and then if they don't I will see if I can do a manual application.
