### ISSUE TITLE
Enhance frame handing in warnings.warn() to skip by module rather that stacklevel

### ISSUE THREAD

**Issue by doerwalter** [python/cpython#39615]
BPO | [850482](https://bugs.python.org/issue850482)
--- | :---
Nosy | @doerwalter, @devdanzin, @jayvdb
Files | <li>[diff.txt](https://bugs.python.org/file5709/diff.txt "Uploaded as text/plain at 2003-11-27.23:12:08 by @doerwalter")</li><li>[diff2.txt](https://bugs.python.org/file5710/diff2.txt "Uploaded as text/plain at 2007-04-08.11:44:55 by @doerwalter")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2003-11-27.23:12:08.000>
labels = ['type-feature', 'library']
title = 'Enhance frame handing in warnings.warn()'
updated_at = <Date 2015-12-10.08:16:31.826>
user = 'https://github.com/doerwalter'
```

bugs.python.org fields:
```python
activity = <Date 2015-12-10.08:16:31.826>
actor = 'jayvdb'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2003-11-27.23:12:08.000>
creator = 'doerwalter'
dependencies = []
files = ['5709', '5710']
hgrepos = []
issue_num = 850482
keywords = ['patch']
message_count = 6.0
messages = ['44953', '44954', '44955', '44956', '82016', '256170']
nosy_count = 4.0
nosy_names = ['doerwalter', 'zseil', 'ajaksu2', 'jayvdb']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue850482'
versions = ['Python 3.2']
```

</p></details>

### Linked PRs
* gh-100840
* gh-101407

**Comment by gpshead** [comment]
Assigning to me to see if I get to this as I'm really wanting this feature while trying to add a warning deep within an an complicated package with multiple public API surfaces at different stacklevels.

**Comment by merwok** [comment]
Skipping by module seems good, but the implementation relies on file names — could it be module or package name?

**Comment by gpshead** [comment]
It seems like "by fully qualified module name" is what code authors might want as that's how we think... But in practice that might be hard to implement in a reliable manner.  The `__file__` module or package prefix match effectively lets you do that.

Investigating... The code objects in the frame appears to have a `.co_qualname` attribute, but it that always set?
Code objects are always defined within a file thus co_filename should be set for anything coming from a .py source file in a module or package (C extensions or manual code object creation could supply whatever "filename" they want, but those unusual things aren't cases I'd worry about matching and skipping), but code objects are not required to have names or qualified names (lambdas, comprehension expressions, nested functions, etc)...

It might be possible to get the base module name itself via frame.f_globals.__name__ but even that sounds unreliable, and using just the __name__ as a match to skip is pretty non-specific.

I'll poke around, but I'm not sure if it is possible.

The other constraint I've been keeping in this code: It must be a fast check. warn() should not do a lot of computation.

**Comment by gpshead** [comment]
I don't believe module or package name is possible. Indeed `frame.f_code.co_qualname` doesn't give a module or package name. Frames and code objects don't have any reference back to a module or namespace. So I don't see any easy, fast, and reliable way to do that beyond the filename based match as my PR implements.

**Comment by gpshead** [comment]
I'm calling this fixed as it can skip by filename now which was a performant way to implement this.
