### ISSUE TITLE
Add datetime.time.strptime and datetime.date.strptime

### ISSUE THREAD

**Issue by 3a57c1f3-e3d5-476c-8e8d-dc193f0a42f4** [python/cpython#41431]
BPO | [1100942](https://bugs.python.org/issue1100942)
--- | :---
Nosy | @amauryfa, @abalkin, @vstinner, @devdanzin, @berkerpeksag, @soltysh, @matrixise, @vajrasky, @matheusportela, @pganssle
PRs | <li>python/cpython#5578</li>
Files | <li>[strptime.diff](https://bugs.python.org/file6427/strptime.diff "Uploaded as text/plain at 2005-01-12.14:54:54 by josh-sf")</li><li>[strptime2.diff](https://bugs.python.org/file6428/strptime2.diff "Uploaded as text/plain at 2005-02-02.22:00:44 by josh-sf"): time.strptime and date.strptime as well</li><li>[date-strptime.patch](https://bugs.python.org/file14351/date-strptime.patch "Uploaded as text/plain at 2009-06-23.23:18:57 by @amauryfa")</li><li>[issue1100942.diff](https://bugs.python.org/file17599/issue1100942.diff "Uploaded as text/plain at 2010-06-09.15:17:21 by @abalkin")</li><li>[issue1100942_pure.diff](https://bugs.python.org/file26446/issue1100942_pure.diff "Uploaded as text/plain at 2012-07-20.09:19:09 by Juarez.Bochi")</li><li>[issue1100942_pure2.diff](https://bugs.python.org/file26452/issue1100942_pure2.diff "Uploaded as text/plain at 2012-07-20.14:18:45 by Juarez.Bochi")</li><li>[issue1100942_v4.diff](https://bugs.python.org/file29117/issue1100942_v4.diff "Uploaded as text/plain at 2013-02-18.19:25:34 by @berkerpeksag")</li><li>[issue1100942_full.patch](https://bugs.python.org/file33240/issue1100942_full.patch "Uploaded as text/plain at 2013-12-20.23:28:14 by @soltysh"): Full (merged) patch against current HEAD</li><li>[issue1100942_20140409.patch](https://bugs.python.org/file34778/issue1100942_20140409.patch "Uploaded as text/plain at 2014-04-09.20:05:34 by @soltysh"): Patch fixed against current default branch</li><li>[issue1100942.patch](https://bugs.python.org/file39345/issue1100942.patch "Uploaded as text/plain at 2015-05-11.21:23:03 by @soltysh")</li><li>[issue1100942-3.6.patch](https://bugs.python.org/file44044/issue1100942-3.6.patch "Uploaded as text/plain at 2016-08-08.07:11:57 by @matrixise")</li><li>[issue1100942_20170722.patch](https://bugs.python.org/file47032/issue1100942_20170722.patch "Uploaded as text/plain at 2017-07-22.08:03:47 by @matheusportela")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2005-01-12.14:53:01.000>
labels = ['extension-modules', 'type-feature', '3.8']
title = 'Add datetime.time.strptime and datetime.date.strptime'
updated_at = <Date 2018-08-20.19:46:06.268>
user = 'https://bugs.python.org/josh-sf'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-20.19:46:06.268>
actor = 'p-ganssle'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2005-01-12.14:53:01.000>
creator = 'josh-sf'
dependencies = []
files = ['6427', '6428', '14351', '17599', '26446', '26452', '29117', '33240', '34778', '39345', '44044', '47032']
hgrepos = []
issue_num = 1100942
keywords = ['patch', 'needs review']
message_count = 48.0
messages = ['47516', '47517', '47518', '47519', '47520', '82109', '89650', '103731', '103732', '106805', '106807', '107402', '114247', '126013', '162732', '165882', '165905', '165906', '165929', '174743', '174746', '182336', '184577', '206495', '206498', '206500', '206519', '206717', '215472', '215474', '215491', '215537', '215559', '215843', '242569', '242803', '242809', '242917', '272149', '273568', '279331', '279333', '279334', '298841', '298842', '311783', '313948', '321550']
nosy_count = 22.0
nosy_names = ['jafo', 'guettli', 'amaury.forgeotdarc', 'belopolsky', 'sonderblade', 'alanvgreen', 'vstinner', 'ajaksu2', 'josh-sf', 'cvrebert', 'tiktuk', 'adam-collard', 'westley.martinez', 'berker.peksag', 'maciej.szulik', 'Juarez.Bochi', 'petre', 'matrixise', 'vajrasky', 'Julian.Gindi', 'matheus.v.portela', 'p-ganssle']
pr_nums = ['5578']
priority = None
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1100942'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-120752

**Comment by ac0fe71c-dd58-48d3-a60d-861ac82a4ad5** [comment]
The patch is broken against Python 3.7. I'll try working on it.

**Comment by ac0fe71c-dd58-48d3-a60d-861ac82a4ad5** [comment]
Also, may I move this issue to a GitHub PR?

**Comment by abalkin** [comment]
> I have updated the patch for 3.8, create a PR ..

@matrixise, I don't see a PR linked to this issue.

**Comment by abalkin** [comment]
Found it: GH-5578.

**Comment by gadewis949** [comment]
"_environ_"
 "_CGI.py_"
 "_Start_Response_"
 "_Response_Header_"
 "_Header_Name_"
 "_Header_Value_"
 "_Header_Name_" == "_ahmedsoltan.abomariam@gmail.com_"
 "_Start_Response_"
 "_CGI-999_“
 "_call_"
 "_call_str_"
 "_call_String_"
 "_Str_byte_"
 "_String_Bytes_"
 "_String_Type_"
 "_os.environ_"
 ”_input.info_”
 “_String_type_" == "_01112888935_"
 "_Strt_Response_"
 "_sys.info_"
 "_exc.info_"
 "_Response_Headers_"
 "_Header_Name_"
 "_Header_Value_"
 "_Type_String_"
 "_write_( )_""
 "_Write_(String-Content)_"
 "_import_snake.yml_"
 "_install_($176jbnpv6c^dj^&dcy#fb0=-
d81gej5w5zum1f20Ce=w+_w5u)_"
"""
"_if_code_change_" == "_excute_"
"_excute_All_Contribution_"
"_Contribute_Header_"
"_getttribute_"'$176jbnpv6c^dj^&dcy#fb0=-
d81gej5w5zum1f20Ce=w+_w5u
"_Attribute_only_ahmedsoltan.abonariam@gmail.com_"
"_var_immediatly_"
"_Trolling_Explicity_"
"_def_(Date)_"
"_(Date)_" == (05/30/2024)_"
"_input.info_"
"_main_( )_.._egg\_"

**Comment by Nad834** [comment]
> BPO	[1100942](https://bugs.python.org/issue1100942)
> Nosy	[@amauryfa](https://github.com/amauryfa), [@abalkin](https://github.com/abalkin), [@vstinner](https://github.com/vstinner), [@devdanzin](https://github.com/devdanzin), [@berkerpeksag](https://github.com/berkerpeksag), [@soltysh](https://github.com/soltysh), [@matrixise](https://github.com/matrixise), [@vajrasky](https://github.com/vajrasky), [@matheusportela](https://github.com/matheusportela), [@pganssle](https://github.com/pganssle)
> PRs	
> * [WIP: bpo-1100942: Add datetime.time.strptime and datetime.date.strptime #5578](https://github.com/python/cpython/pull/5578)
> Files	
> * [strptime.diff](https://bugs.python.org/file6427/strptime.diff)
> * [strptime2.diff](https://bugs.python.org/file6428/strptime2.diff): time.strptime and date.strptime as well
> * [date-strptime.patch](https://bugs.python.org/file14351/date-strptime.patch)
> * [issue1100942.diff](https://bugs.python.org/file17599/issue1100942.diff)
> * [issue1100942_pure.diff](https://bugs.python.org/file26446/issue1100942_pure.diff)
> * [issue1100942_pure2.diff](https://bugs.python.org/file26452/issue1100942_pure2.diff)
> * [issue1100942_v4.diff](https://bugs.python.org/file29117/issue1100942_v4.diff)
> * [issue1100942_full.patch](https://bugs.python.org/file33240/issue1100942_full.patch): Full (merged) patch against current HEAD
> * [issue1100942_20140409.patch](https://bugs.python.org/file34778/issue1100942_20140409.patch): Patch fixed against current default branch
> * [issue1100942.patch](https://bugs.python.org/file39345/issue1100942.patch)
> * [issue1100942-3.6.patch](https://bugs.python.org/file44044/issue1100942-3.6.patch)
> * [issue1100942_20170722.patch](https://bugs.python.org/file47032/issue1100942_20170722.patch)
> _Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state._
> 
> Show more details
