### ISSUE TITLE
Adding a recvexactly() to socket.socket: receive exactly n bytes

### ISSUE THREAD

**Issue by d816e26d-971d-4c07-a243-608d3c125b03** [python/cpython#41448]
BPO | [1103213](https://bugs.python.org/issue1103213)
--- | :---
Nosy | @loewis, @pfalcon, @irmen, @pitrou, @vstinner, @giampaolo, @vadmium
Files | <li>[socketmodulepatch.txt](https://bugs.python.org/file16762/socketmodulepatch.txt "Uploaded as text/plain at 2010-04-05.15:07:44 by @irmen"): patch for Modules/socketmodule.c</li><li>[libpatch.txt](https://bugs.python.org/file16763/libpatch.txt "Uploaded as text/plain at 2010-04-05.15:08:24 by @irmen"): patch for Lib/socket.py</li><li>[docpatch.txt](https://bugs.python.org/file16764/docpatch.txt "Uploaded as text/plain at 2010-04-05.15:08:59 by @irmen"): patch for Doc/library/socket.rst</li><li>[recvall.patch](https://bugs.python.org/file40344/recvall.patch "Uploaded as text/plain at 2015-09-03.15:47:42 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2005-01-16.04:02:31.000>
labels = ['extension-modules', 'type-feature']
title = 'Adding a recvexactly() to socket.socket: receive exactly n bytes'
updated_at = <Date 2016-04-08.22:49:31.159>
user = 'https://github.com/irmen'
```

bugs.python.org fields:
```python
activity = <Date 2016-04-08.22:49:31.159>
actor = 'pfalcon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2005-01-16.04:02:31.000>
creator = 'irmen'
dependencies = []
files = ['16762', '16763', '16764', '40344']
hgrepos = []
issue_num = 1103213
keywords = ['patch']
message_count = 16.0
messages = ['47558', '47559', '99844', '101178', '101206', '102374', '102382', '102391', '114395', '234117', '234126', '234157', '239975', '249662', '250402', '254428']
nosy_count = 7.0
nosy_names = ['loewis', 'pfalcon', 'irmen', 'pitrou', 'vstinner', 'giampaolo.rodola', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1103213'
versions = ['Python 3.2']
```

</p></details>

**Comment by iritkatriel** [comment]
This is almost 20 years old, it has been abandoned by the OP and I don't think anyone else is likely to pick it up. Marking as pending and will close it soon if nobody will object.
