### ISSUE TITLE
send/recv SEGMENT_SIZE should be used more in socketmodule

### ISSUE THREAD

**Issue by d816e26d-971d-4c07-a243-608d3c125b03** [python/cpython#41449]
BPO | [1103350](https://bugs.python.org/issue1103350)
--- | :---
Nosy | @irmen, @devdanzin, @tjguk, @bitdancer, @briancurtin, @erlend-aasland

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2005-01-16.15:01:11.000>
labels = ['extension-modules', 'type-feature']
title = 'send/recv SEGMENT_SIZE should be used more in socketmodule'
updated_at = <Date 2021-03-15.09:58:09.165>
user = 'https://github.com/irmen'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-15.09:58:09.165>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2005-01-16.15:01:11.000>
creator = 'irmen'
dependencies = []
files = []
hgrepos = []
issue_num = 1103350
keywords = []
message_count = 8.0
messages = ['60634', '60635', '82111', '114398', '114485', '115605', '127745', '388721']
nosy_count = 6.0
nosy_names = ['irmen', 'ajaksu2', 'tim.golden', 'r.david.murray', 'brian.curtin', 'erlendaasland']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1103350'
versions = ['Python 3.3']
```

</p></details>

**Comment by arhadthedev** [comment]
@erlend-aasland Can the issue be closed then? I grepped for `SEGMENT_SIZE` in `Modules/` and got no match.

**Comment by erlend-aasland** [comment]
The OP says it "should be used more on Windows". I don't know Windows, so I can't answer that. I observe that the person who opened this issue does not know Windows either.

Wild guess: the devs who wrote the socket module code in the first place probably know better than both me and the issue reporter, so I think the code is fine as it is (that is: we can close this). Maybe @zooba or @eryksun could chime in.

**Comment by zooba** [comment]
It's meaningless to me, and without a more compelling case, I'm not going to research it.
