### ISSUE TITLE
making builtin exceptions more informative

### ISSUE THREAD

**Issue by 86bc8ce2-6ce3-455f-a831-b3a2a11cc10c** [python/cpython#41852]
BPO | [1182143](https://bugs.python.org/issue1182143)
--- | :---
Nosy | @doerwalter, @rhettinger, @pitrou, @devdanzin, @ezio-melotti, @bitdancer, @berkerpeksag, @iritkatriel
Files | <li>[Issue1182143_1.patch](https://bugs.python.org/file38551/Issue1182143_1.patch "Uploaded as text/plain at 2015-03-19.03:24:07 by George Jenkins")</li><li>[Issue1182143_1hg.patch](https://bugs.python.org/file38872/Issue1182143_1hg.patch "Uploaded as text/plain at 2015-04-09.02:05:22 by George Jenkins"): Patch generated via mercurial</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2005-04-13.11:02:55.000>
labels = ['interpreter-core', 'type-feature']
title = 'making builtin exceptions more informative'
updated_at = <Date 2021-12-10.19:57:33.239>
user = 'https://bugs.python.org/sdementen'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.19:57:33.239>
actor = 'ajaksu2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2005-04-13.11:02:55.000>
creator = 'sdementen'
dependencies = []
files = ['38551', '38872']
hgrepos = []
issue_num = 1182143
keywords = ['patch']
message_count = 13.0
messages = ['61192', '61193', '61194', '87799', '87892', '238489', '240304', '242447', '245599', '245603', '245883', '253415', '257268']
nosy_count = 10.0
nosy_names = ['doerwalter', 'rhettinger', 'sdementen', 'pitrou', 'ajaksu2', 'ezio.melotti', 'r.david.murray', 'berker.peksag', 'George Jenkins', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1182143'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
This kind of thing was proposed several times. The objections are

1. increase in references to objects
2. only new/updated code will populate the new info so we will never be able to assume it is there, undermining the usefulness of the whole thing


I would add that I’m not sure why this feature is so useful - in the immediate context of the failed operation we know which key/name we just looked up. If the exception was allowed to propagate on, is it really that useful to have programmatic access to the key?  Can anyone suggest a use case?
