### ISSUE TITLE
Big speedup in email message parsing

### ISSUE THREAD

**Issue by 040a6c67-9f49-475c-a0fb-294ef5661fed** [python/cpython#42213]
BPO | [1243730](https://bugs.python.org/issue1243730)
--- | :---
Nosy | @warsaw, @devdanzin, @bitdancer, @serhiy-storchaka
Files | <li>[t.dif](https://bugs.python.org/file6740/t.dif "Uploaded as application/octet-stream at 2005-07-23.22:07:37 by lpd"): Patches for email/FeedParser.py</li><li>[1243730.diff](https://bugs.python.org/file6741/1243730.diff "Uploaded as text/plain at 2006-05-28.01:12:04 by @warsaw")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2005-07-23.22:07:37.000>
labels = ['library', 'expert-email', 'performance']
title = 'Big speedup in email message parsing'
updated_at = <Date 2017-10-28.12:23:16.151>
user = 'https://bugs.python.org/lpd'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-28.12:23:16.151>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'email']
creation = <Date 2005-07-23.22:07:37.000>
creator = 'lpd'
dependencies = []
files = ['6740', '6741']
hgrepos = []
issue_num = 1243730
keywords = ['patch']
message_count = 5.0
messages = ['48615', '48616', '48617', '124717', '184191']
nosy_count = 6.0
nosy_names = ['barry', 'holdenweb', 'lpd', 'ajaksu2', 'r.david.murray', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'pending'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue1243730'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
This issue was reported for python 2.4 and has been idle for over a decade. Shall we close it?

**Comment by warsaw** [comment]
> Shall we close it?

I dunno, maybe we can get to it for Python 2027! 😜 

Yes, let's close it. It's here for posterity in case anybody wants to resurrect it.
