### ISSUE TITLE
allow unicode arguments for robotparser.can_fetch

### ISSUE THREAD

**Issue by 3da0707d-f262-40c9-bcc7-95cefbde6746** [python/cpython#42942]
BPO | [1437699](https://bugs.python.org/issue1437699)
--- | :---
Nosy | @malemburg, @birkenfeld, @terryjreedy, @osvenskan
Files | <li>[PythonSessionsShowingRobotParserError.txt](https://bugs.python.org/file8267/PythonSessionsShowingRobotParserError.txt "Uploaded as text/plain at 2006-02-23.21:07:54 by @osvenskan"): Interactive Python sessions (2.4 & 2.3) showing how to recreate</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-02-23.21:07:54.000>
labels = ['type-feature', 'expert-unicode']
title = 'allow unicode arguments for robotparser.can_fetch'
updated_at = <Date 2014-02-03.19:40:45.276>
user = 'https://github.com/osvenskan'
```

bugs.python.org fields:
```python
activity = <Date 2014-02-03.19:40:45.276>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Unicode']
creation = <Date 2006-02-23.21:07:54.000>
creator = 'osvenskan'
dependencies = []
files = ['8267']
hgrepos = []
issue_num = 1437699
keywords = []
message_count = 9.0
messages = ['54740', '54741', '54742', '54743', '54744', '54745', '115006', '115022', '121019']
nosy_count = 4.0
nosy_names = ['lemburg', 'georg.brandl', 'terry.reedy', 'osvenskan']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1437699'
versions = ['Python 3.2']
```

</p></details>

**Comment by iritkatriel** [comment]
This has been abandoned for over a decade. Marking as pending and will close it soon unless someone will object.
