### ISSUE TITLE
addheaders for urlopen / open / xxxx_open

### ISSUE THREAD

**Issue by 1409fbaa-f956-4d99-a567-589cf071a381** [python/cpython#43055]
BPO | [1453973](https://bugs.python.org/issue1453973)
--- | :---
Nosy | @orsenthil

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-03-19.18:55:38.000>
labels = ['type-feature', 'library']
title = 'addheaders for urlopen / open / xxxx_open'
updated_at = <Date 2019-05-02.04:31:14.527>
user = 'https://bugs.python.org/kxroberto'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-02.04:31:14.527>
actor = 'josiahcarlson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2006-03-19.18:55:38.000>
creator = 'kxroberto'
dependencies = []
files = []
hgrepos = []
issue_num = 1453973
keywords = []
message_count = 2.0
messages = ['61227', '61228']
nosy_count = 2.0
nosy_names = ['orsenthil', 'kxroberto']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1453973'
versions = ['Python 3.4']
```

</p></details>

**Comment by arhadthedev** [comment]
To not repeat `addheaders` argument between `urlopen` calls, use `urllib.request.OpenerDirector`. From https://docs.python.org/3/library/urllib.request.html:

> ```python
> import urllib.request
> opener = urllib.request.build_opener()
> opener.addheaders = [('User-agent', 'Mozilla/5.0')]
> opener.open('http://www.example.com/')
> ```
