### ISSUE TITLE
Wave.py support for ulaw and alaw audio

### ISSUE THREAD

**Issue by 07022039-83af-42c2-b52d-96949c7c28f6** [python/cpython#43330]
BPO | [1483545](https://bugs.python.org/issue1483545)
--- | :---
Nosy | @amauryfa, @serhiy-storchaka
Files | <li>[wave.py_unified_diff.zip](https://bugs.python.org/file7234/wave.py_unified_diff.zip "Uploaded as application/zip at 2006-05-07.23:23:40 by ewoudenberg"): unified diff from Lib/wave.py (At revision: 45934) to a wave.py with ulaw/alaw support</li><li>[wave24.py](https://bugs.python.org/file13931/wave24.py "Uploaded as text/plain at 2009-05-08.19:14:05 by ewoudenberg"): Wave.py from python 2.4 with patch applied</li><li>[wave25.py](https://bugs.python.org/file13932/wave25.py "Uploaded as text/plain at 2009-05-08.19:14:47 by ewoudenberg"): Wave.py from python 2.5 with patch applied</li><li>[wave.py](https://bugs.python.org/file36465/wave.py "Uploaded as text/plain at 2014-08-25.07:30:34 by ewoudenberg"): Wave.py from python 2.7 with patch applied</li><li>[test_wave.py](https://bugs.python.org/file36466/test_wave.py "Uploaded as text/plain at 2014-08-25.07:32:51 by ewoudenberg"): test_wave.py with added tests for ulaw and alaw format files.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-05-07.23:23:39.000>
labels = ['type-feature', 'library']
title = 'Wave.py support for ulaw and alaw audio'
updated_at = <Date 2014-08-25.07:32:51.887>
user = 'https://bugs.python.org/ewoudenberg'
```

bugs.python.org fields:
```python
activity = <Date 2014-08-25.07:32:51.887>
actor = 'ewoudenberg'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2006-05-07.23:23:39.000>
creator = 'ewoudenberg'
dependencies = []
files = ['7234', '13931', '13932', '36465', '36466']
hgrepos = []
issue_num = 1483545
keywords = ['patch']
message_count = 5.0
messages = ['50204', '87462', '87463', '87499', '199865']
nosy_count = 3.0
nosy_names = ['amaury.forgeotdarc', 'ewoudenberg', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1483545'
versions = ['Python 2.7']
```

</p></details>

**Comment by AA-Turner** [comment]
These patches are targetting Python 2.7 and earlier so I would be surprised if they apply today -- I'd sugest closing this issue.

A

**Comment by kumaraditya303** [comment]
A new issue targeting main branch can be created if desired, also the patch would have to be a PR not  a diff.
