### ISSUE TITLE
wm_attributes doesn't take keyword arguments

### ISSUE THREAD

**Issue by 67b7e3ee-c650-4643-a690-f7725ac3f411** [python/cpython#43457]
BPO | [1500773](https://bugs.python.org/issue1500773)
--- | :---
Nosy | @loewis, @asvetlov
Files | <li>[Tkinter.patch](https://bugs.python.org/file7311/Tkinter.patch "Uploaded as text/plain at 2006-06-05.06:35:27 by gregcouch"): wm_attributes patch</li><li>[issue1500773.diff](https://bugs.python.org/file10548/issue1500773.diff "Uploaded as text/plain at 2008-06-07.22:21:00 by gpolo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/loewis'
closed_at = None
created_at = <Date 2006-06-05.06:35:26.000>
labels = ['type-feature', 'expert-tkinter']
title = "wm_attributes doesn't take keyword arguments"
updated_at = <Date 2012-03-21.19:45:52.695>
user = 'https://bugs.python.org/gregcouch'
```

bugs.python.org fields:
```python
activity = <Date 2012-03-21.19:45:52.695>
actor = 'asvetlov'
assignee = 'loewis'
closed = False
closed_date = None
closer = None
components = ['Tkinter']
creation = <Date 2006-06-05.06:35:26.000>
creator = 'gregcouch'
dependencies = []
files = ['7311', '10548']
hgrepos = []
issue_num = 1500773
keywords = ['patch']
message_count = 4.0
messages = ['50427', '50428', '50429', '67668']
nosy_count = 5.0
nosy_names = ['loewis', 'gregcouch', 'klappnase', 'gpolo', 'asvetlov']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1500773'
versions = ['Python 3.2']
```

</p></details>

### Linked PRs
* gh-111404

**Comment by serhiy-storchaka** [comment]
The proposed PR contains the following changes:

1. `w.wm_attributes()` without arguments returns a dict instead of a tuple or a str.
    E.g. it returns `{'alpha': 1.0, 'topmost': 0, 'zoomed': 0, 'fullscreen': 0, 'type': ''}` instead of `('-alpha', 1.0, '-topmost', 0, '-zoomed', 0, '-fullscreen', 0, '-type', '')`, and, when wantobjects is 0, it returns `{'alpha': '1.0', 'topmost': '0', 'zoomed': '0', 'fullscreen': '0', 'type': ''}` instead of `'-alpha 1.0 -topmost 0 -zoomed 0 -fullscreen 0 -type {}'`.
    This is a breaking change!
    You still can get the old result when pass None as argument: `w.wm_attributes(None)`.
2. When called with a single argument to get a value, it allow to omit the minus prefix. E.g. `w.wm_attributes('alpha')`. `w.wm_attributes('-alpha')` also supported, but is now silently deprecated.
3. It can be called with keyword arguments to set attributes. E.g. `w.wm_attributes(alpha=0.5)`. Old way `w.wm_attributes('-alpha', 0.5)` also works, but it is now silently deprecated.

**Comment by serhiy-storchaka** [comment]
Opened a discussion https://discuss.python.org/t/tkinter-wm-attributes-needs-breaking-changes/37360.

**Comment by serhiy-storchaka** [comment]
My request for unconditional changing the returned value was rejected: https://github.com/python/steering-council/issues/211. Instead it was proposed to add an optional argument `return_python_dict=False`.
