### ISSUE TITLE
Bad behaviour in <ossaudio audio device>.obuf*

### ISSUE THREAD

**Issue by 68dc37d8-3097-4586-9373-76345ef538cd** [python/cpython#44040]
BPO | [1566331](https://bugs.python.org/issue1566331)
--- | :---
Nosy | @tiran, @raplin

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-09-27.13:19:49.000>
labels = ['extension-modules', 'type-bug', '3.9', '3.10', '3.11']
title = 'Bad behaviour in <ossaudio audio device>.obuf*'
updated_at = <Date 2021-10-20.12:39:09.354>
user = 'https://bugs.python.org/samdennis'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-20.12:39:09.354>
actor = 'christian.heimes'
assignee = 'gward'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2006-09-27.13:19:49.000>
creator = 'samdennis'
dependencies = []
files = []
hgrepos = []
issue_num = 1566331
keywords = []
message_count = 5.0
messages = ['30030', '30031', '114835', '304127', '404440']
nosy_count = 5.0
nosy_names = ['gward', 'samdennis', 'rluse', 'christian.heimes', 'richaplin']
pr_nums = []
priority = 'low'
resolution = None
stage = 'test needed'
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue1566331'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by 60a507b9-9007-4a9c-87cf-f53dd62a46d3** [comment]
Hi there yes this is very much an issue on Arm linux (e.g. Armbian). Calling any function that triggers a call to \_ssize(..) - a function which is clearly intended to have no side-effects - instead resets the number of channels (and sample format?) by calling IOCTLs "SNDCTL_DSP_SETFMT" and "SNDCTL_DSP_CHANNELS" with arguments of zero as a way to query the current values. 

This doesn't work on many drivers; e.g. they take '0' as meaning 'mono' and switch to one channel. 

To repro:
        import ossaudiodev
        self.dsp=ossaudiodev.open("/dev/dsp1","w")
        self.dsp.setfmt(ossaudiodev.AFMT_S16_LE)
        self.dsp.channels(2)  #\<\<Set to stereo
        self.dsp.speed(96000)
        ...
        self.bufSize=self.dsp.bufsize()
        ...

```py
        #This will output audio in the wrong format (mono)! Remove the innocent looking "bufsize" test above and it will correctly output stereo
        self.dsp.write(someData)
```



Frustrating bug! ;-)

**Comment by AA-Turner** [comment]
The `ossaudiodev` module has now been deprecated and will be removed (see PEP-594 & #91217 for details), closing.

A
