### ISSUE TITLE
release GIL while doing I/O operations in the mmap module

### ISSUE THREAD

**Issue by 052306b5-29e9-4fe2-91f8-d1180c7be5a4** [python/cpython#44098]
BPO | [1572968](https://bugs.python.org/issue1572968)
--- | :---
Nosy | @pitrou, @briancurtin, @jnwatson, @ZackerySpytz, @isidentical
PRs | <li>python/cpython#14114</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-10-08.00:26:31.000>
labels = ['extension-modules', '3.9', 'performance']
title = 'release GIL while doing I/O operations in the mmap module'
updated_at = <Date 2019-06-15.15:48:30.691>
user = 'https://bugs.python.org/luks'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-15.15:48:30.691>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2006-10-08.00:26:31.000>
creator = 'luks'
dependencies = []
files = []
hgrepos = []
issue_num = 1572968
keywords = ['patch']
message_count = 8.0
messages = ['61261', '61262', '84542', '102453', '102465', '102466', '342561', '343989']
nosy_count = 8.0
nosy_names = ['pitrou', 'luks', 'brian.curtin', 'neologix', 'adiroiban', 'jnwatson', 'ZackerySpytz', 'BTaskaya']
pr_nums = ['14114']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue1572968'
versions = ['Python 3.9']
```

</p></details>

**Comment by gvanrossum** [comment]
This seems stuck, and it’s really old (2006!). 

@isidentical Could I interest you in providing that patch you mentioned?

**Comment by gvanrossum** [comment]
Once the Unix PR lands, should we keep this open hoping someone will do it for Windows, or close it?

**Comment by hauntsaninja** [comment]
The Unix PR has landed and I don't intend to make one for Windows (don't have access to a machine or a use case). This has been open since 2006, so I vote we close it.
