### ISSUE TITLE
[doc] os.execvp[e] on win32 fails for current directory

### ISSUE THREAD

**Issue by 96dc93d3-a39f-48bf-827a-81d9a5adf9eb** [python/cpython#44123]
BPO | [1576313](https://bugs.python.org/issue1576313)
--- | :---
Nosy | @loewis, @bitdancer
Files | <li>[python-win32-execvp.patch](https://bugs.python.org/file7576/python-win32-execvp.patch "Uploaded as text/plain at 2006-10-13.00:57:39 by snaury")</li><li>[Issue1576313.diff](https://bugs.python.org/file35690/Issue1576313.diff "Uploaded as text/plain at 2014-06-19.14:09:58 by BreamoreBoy"): Add one sentence to os.rst</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-10-13.00:57:39.000>
labels = ['type-bug', '3.8', '3.9', '3.10', 'docs']
title = '[doc] os.execvp[e] on win32 fails for current directory'
updated_at = <Date 2020-11-06.19:58:06.206>
user = 'https://bugs.python.org/snaury'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-06.19:58:06.206>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2006-10-13.00:57:39.000>
creator = 'snaury'
dependencies = []
files = ['7576', '35690']
hgrepos = []
issue_num = 1576313
keywords = ['patch']
message_count = 11.0
messages = ['51239', '51240', '51241', '51242', '51243', '51244', '109177', '109184', '220948', '220952', '220980']
nosy_count = 6.0
nosy_names = ['loewis', 'snaury', 'techtonik', 'mcmahon_m', 'r.david.murray', 'docs@python']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue1576313'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-93826

**Comment by hugovk** [comment]
> So I'm changing this to a doc bug

Closing this issue, https://github.com/python/cpython/pull/93826 has been merged that updates the docs.
