### ISSUE TITLE
sndhdr.what() does not recognize wav file

### ISSUE THREAD

**Issue by a6c6505b-7e67-4c94-9eab-a81332347b8b** [python/cpython#44318]
BPO | [1611944](https://bugs.python.org/issue1611944)
--- | :---
Files | <li>[Audio01.rar](https://bugs.python.org/file2251/Audio01.rar "Uploaded as application/rar at 2006-12-09.09:55:59 by klankschap"): wav in rar archive</li><li>[sndhdr.diff](https://bugs.python.org/file11501/sndhdr.diff "Uploaded as text/plain at 2008-09-16.11:38:45 by matthijs"): Patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2006-12-09.02:37:48.000>
labels = ['type-bug', 'library']
title = 'sndhdr.what() does not recognize wav file'
updated_at = <Date 2020-09-19.19:04:33.906>
user = 'https://bugs.python.org/klankschap'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-19.19:04:33.906>
actor = 'georg.brandl'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2006-12-09.02:37:48.000>
creator = 'klankschap'
dependencies = []
files = ['2251', '11501']
hgrepos = []
issue_num = 1611944
keywords = ['patch']
message_count = 7.0
messages = ['30765', '30766', '30767', '30768', '30769', '30770', '73294']
nosy_count = 2.0
nosy_names = ['klankschap', 'matthijs']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue1611944'
versions = ['Python 3.1', 'Python 2.7', 'Python 3.2']
```

</p></details>

**Comment by hugovk** [comment]
Note the sndhdr module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
> Note the sndhdr module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

`snhdr` has been deprecated in part because it has no active maintainer in the core dev team. Now that the module is deprecated, bugfixes and improvements to the module will be low priority; moreover, the fact that this issue has not seen any activity since 2008 indicates that this problem probably does not affect a large number of users. I am therefore closing this issue.

Cc. @klankschap, @matthijs
