### ISSUE TITLE
cgi.py multipart/form-data

### ISSUE THREAD

**Issue by 6c07f3ce-50da-4d3a-b3ce-8cce9fd37fab** [python/cpython#44313]
BPO | [1610654](https://bugs.python.org/issue1610654)
--- | :---
Nosy | @atsuoishimoto, @orsenthil, @pitrou, @bitdancer, @florentx, @hynek, @serhiy-storchaka
Files | <li>[issue1610654.patch](https://bugs.python.org/file36895/issue1610654.patch "Uploaded as text/plain at 2014-10-13.08:49:27 by rishi.maker.forum")</li><li>[issue1610654_1.patch](https://bugs.python.org/file36927/issue1610654_1.patch "Uploaded as text/plain at 2014-10-15.00:45:48 by rishi.maker.forum")</li><li>[issue1610654_2.patch](https://bugs.python.org/file37128/issue1610654_2.patch "Uploaded as text/plain at 2014-11-04.13:50:45 by rishi.maker.forum")</li><li>[issue1610654_3.patch](https://bugs.python.org/file37149/issue1610654_3.patch "Uploaded as text/plain at 2014-11-08.14:44:24 by rishi.maker.forum")</li><li>[issue1610654_4.patch](https://bugs.python.org/file37399/issue1610654_4.patch "Uploaded as text/plain at 2014-12-09.14:44:03 by rishi.maker.forum")</li><li>[issue1610654_5.patch](https://bugs.python.org/file37400/issue1610654_5.patch "Uploaded as text/plain at 2014-12-09.14:53:05 by rishi.maker.forum")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2006-12-07.09:18:18.000>
labels = ['library', 'performance']
title = 'cgi.py multipart/form-data'
updated_at = <Date 2019-04-26.17:29:15.916>
user = 'https://bugs.python.org/teyc'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.17:29:15.916>
actor = 'BreamoreBoy'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2006-12-07.09:18:18.000>
creator = 'teyc'
dependencies = []
files = ['36895', '36927', '37128', '37149', '37399', '37400']
hgrepos = []
issue_num = 1610654
keywords = ['patch']
message_count = 21.0
messages = ['61046', '110090', '114915', '119535', '166021', '178292', '222416', '222557', '222591', '222952', '229235', '229262', '229265', '229285', '229389', '230170', '230620', '230860', '231554', '232377', '232379']
nosy_count = 10.0
nosy_names = ['ishimoto', 'orsenthil', 'pitrou', 'teyc', 'r.david.murray', 'flox', 'hynek', 'serhiy.storchaka', 'Chui.Tey', 'rishi.maker.forum']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue1610654'
versions = ['Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as pep 594 and no improvement or bugs will be fixed.
