### ISSUE TITLE
Parameter list mismatches (portation problem)

### ISSUE THREAD

**Issue by 107ae353-ce2b-4b5c-89c7-ef79c6aff372** [python/cpython#44525]
BPO | [1648268](https://bugs.python.org/issue1648268)
--- | :---
Nosy | @loewis, @serhiy-storchaka
Files | <li>[tested.diff](https://bugs.python.org/file7745/tested.diff "Uploaded as text/plain at 2007-02-16.16:42:59 by ked-tao"): Diff of tested changes.</li><li>[untested.diff](https://bugs.python.org/file7746/untested.diff "Uploaded as text/plain at 2007-02-16.16:46:49 by ked-tao"): Diff of untested changes</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2007-01-30.22:15:43.000>
labels = ['interpreter-core', 'type-bug']
title = 'Parameter list mismatches (portation problem)'
updated_at = <Date 2018-06-03.12:33:48.724>
user = 'https://bugs.python.org/ked-tao'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-03.12:33:48.724>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2007-01-30.22:15:43.000>
creator = 'ked-tao'
dependencies = []
files = ['7745', '7746']
hgrepos = []
issue_num = 1648268
keywords = ['patch']
message_count = 7.0
messages = ['51817', '51818', '51819', '51820', '51821', '110517', '318539']
nosy_count = 4.0
nosy_names = ['loewis', 'nnorwitz', 'ked-tao', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue1648268'
versions = ['Python 3.1', 'Python 2.7', 'Python 3.2']
```

</p></details>

**Comment by JelleZijlstra** [comment]
This appears to be fixed for `dict_popitem`, as Serhyi mentioned above. I believe the WASM porting effort fixed a few other instances, because WASM is strict about this. I will close this issue; if any concrete places come up where this is still a problem, please open a more focused issue.
