### ISSUE TITLE
[PATCH] Debuggers need a way to change the locals of a frame

### ISSUE THREAD

**Issue by a5ae9dfd-b19f-4ed7-b289-70236f9e865e** [python/cpython#44556]
BPO | [1654367](https://bugs.python.org/issue1654367)
--- | :---
Nosy | @loewis, @arigo, @rhettinger, @fabioz
Files | <li>[test_frames.py](https://bugs.python.org/file8288/test_frames.py "Uploaded as text/plain at 2007-02-07.17:12:28 by @fabioz")</li><li>[test_save_locals.py](https://bugs.python.org/file33917/test_save_locals.py "Uploaded as text/plain at 2014-02-04.22:41:30 by @fabioz"): Some cases where changing frame.f_locals fails</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2007-02-07.17:12:28.000>
labels = ['interpreter-core', 'type-feature']
title = '[PATCH] Debuggers need a way to change the locals of a frame'
updated_at = <Date 2014-02-06.15:47:40.284>
user = 'https://github.com/fabioz'
```

bugs.python.org fields:
```python
activity = <Date 2014-02-06.15:47:40.284>
actor = 'fabioz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2007-02-07.17:12:28.000>
creator = 'fabioz'
dependencies = []
files = ['8288', '33917']
hgrepos = []
issue_num = 1654367
keywords = ['patch']
message_count = 14.0
messages = ['55003', '55004', '55005', '110520', '113625', '114415', '210233', '210265', '210266', '210275', '210374', '210400', '210402', '210403']
nosy_count = 4.0
nosy_names = ['loewis', 'arigo', 'rhettinger', 'fabioz']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1654367'
versions = ['Python 3.3']
```

</p></details>

**Comment by gaogaotiantian** [comment]
This is already done.
