### ISSUE TITLE
improve telnetlib.Telnet so option negotiation becomes easie

### ISSUE THREAD

**Issue by cf40402a-f203-4f98-8392-8fca41a67ee0** [python/cpython#44693]
BPO | [1678077](https://bugs.python.org/issue1678077)
--- | :---
Nosy | @jackdied
Files | <li>[telnetlib-add-handle-option.patch](https://bugs.python.org/file7858/telnetlib-add-handle-option.patch "Uploaded as text/plain at 2007-03-10.22:11:38 by sonderblade")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/jackdied'
closed_at = None
created_at = <Date 2007-03-10.22:11:38.000>
labels = ['type-feature', 'library']
title = 'improve telnetlib.Telnet so option negotiation becomes easie'
updated_at = <Date 2020-09-19.19:04:48.915>
user = 'https://bugs.python.org/sonderblade'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-19.19:04:48.915>
actor = 'georg.brandl'
assignee = 'jackdied'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2007-03-10.22:11:38.000>
creator = 'sonderblade'
dependencies = []
files = ['7858']
hgrepos = []
issue_num = 1678077
keywords = ['patch']
message_count = 4.0
messages = ['52166', '52167', '52168', '85039']
nosy_count = 3.0
nosy_names = ['jimjjewett', 'sonderblade', 'jackdied']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1678077'
versions = ['Python 3.4']
```

</p></details>

**Comment by hugovk** [comment]
Note the telnetlib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.
