### ISSUE TITLE
zipfile.testzip() using progressive file reads

### ISSUE THREAD

**Issue by f3de81e4-f48e-4151-85fb-ec788fcb77c4** [python/cpython#45108]
BPO | [1739648](https://bugs.python.org/issue1739648)
--- | :---
Nosy | @pitrou, @serhiy-storchaka
Files | <li>[testzip_in_chunks.diff](https://bugs.python.org/file8057/testzip_in_chunks.diff "Uploaded as text/plain at 2007-06-19.10:56:48 by gradha")</li><li>[zipfile_testzip_amcintyre.diff](https://bugs.python.org/file9057/zipfile_testzip_amcintyre.diff "Uploaded as text/plain at 2008-01-04.14:47:17 by alanmcintyre"): updated patch</li><li>[testzip-patch2.diff](https://bugs.python.org/file14847/testzip-patch2.diff "Uploaded as text/plain at 2009-09-06.18:56:23 by alanmcintyre"): Addition of test for ZipFile.testzip</li><li>[testzip-patch3.diff](https://bugs.python.org/file18533/testzip-patch3.diff "Uploaded as text/plain at 2010-08-14.20:41:36 by alanmcintyre"): patch updated against python3 trunk</li><li>[testzip-patch4.patch](https://bugs.python.org/file25402/testzip-patch4.patch "Uploaded as text/plain at 2012-04-29.06:36:58 by @serhiy-storchaka"): Updated and reloaded for review</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2007-06-19.10:56:48.000>
labels = ['tests', 'library', 'performance']
title = 'zipfile.testzip() using progressive file reads'
updated_at = <Date 2014-02-03.19:53:56.455>
user = 'https://bugs.python.org/gradha'
```

bugs.python.org fields:
```python
activity = <Date 2014-02-03.19:53:56.455>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2007-06-19.10:56:48.000>
creator = 'gradha'
dependencies = []
files = ['8057', '9057', '14847', '18533', '25402']
hgrepos = []
issue_num = 1739648
keywords = ['patch']
message_count = 12.0
messages = ['52784', '55306', '59226', '87724', '92325', '111534', '111541', '113930', '143972', '159551', '159583', '176742']
nosy_count = 4.0
nosy_names = ['gradha', 'alanmcintyre', 'pitrou', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'languishing'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue1739648'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this was done in       

r65761 | antoine.pitrou | 2008-08-17 08:06:29 -0500 (Sun, 17 Aug 2008) | 3 lines
    
      fix ZipFile.testzip() to work with very large embedded files

(commit 4cd6a95dfeb06950a2566e23e7e2bc9eb8c59775).

**Comment by serhiy-storchaka** [comment]
Yes, the change to testzip has already been made. as was said in https://github.com/python/cpython/issues/45108#issuecomment-1094032983. But the issue was kept open for other patch, which added some tests and improved the docstring.
