### ISSUE TITLE
Limiting data copy in xmlrpclib

### ISSUE THREAD

**Issue by e64f38c1-6df8-4f80-9fe1-38af94d5176c** [python/cpython#45148]
BPO | [1747670](https://bugs.python.org/issue1747670)
--- | :---
Nosy | @loewis, @pitrou, @serhiy-storchaka
Files | <li>[xmlrpclib.patch](https://bugs.python.org/file8070/xmlrpclib.patch "Uploaded as text/plain at 2007-07-04.09:54:37 by kilobug")</li><li>[xmlrpc_less_copy.diff](https://bugs.python.org/file29519/xmlrpc_less_copy.diff "Uploaded as text/plain at 2013-03-21.01:43:21 by Thomas Fenzl")</li><li>[xmlrpc_less_copy-1.diff](https://bugs.python.org/file29579/xmlrpc_less_copy-1.diff "Uploaded as text/plain at 2013-03-26.09:41:19 by Thomas Fenzl")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2007-07-04.09:54:37.000>
labels = ['library', 'performance']
title = 'Limiting data copy in xmlrpclib'
updated_at = <Date 2016-01-20.09:57:29.986>
user = 'https://bugs.python.org/kilobug'
```

bugs.python.org fields:
```python
activity = <Date 2016-01-20.09:57:29.986>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2007-07-04.09:54:37.000>
creator = 'kilobug'
dependencies = []
files = ['8070', '29519', '29579']
hgrepos = []
issue_num = 1747670
keywords = ['patch']
message_count = 12.0
messages = ['52808', '110892', '110900', '110920', '184825', '184949', '184950', '184961', '185264', '189963', '190134', '190136']
nosy_count = 5.0
nosy_names = ['loewis', 'pitrou', 'kilobug', 'serhiy.storchaka', 'Thomas Fenzl']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'pending'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue1747670'
versions = ['Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
Apart from this being abandoned for 9 years, the change proposed here is only valid if end() is only called once. Is this guaranteed?  I can't find anything about this in the doc.

I suggest we close the issue.
