### ISSUE TITLE
textwrap doesn't linebreak on "\n"

### ISSUE THREAD

**Issue by 870315e4-24b5-4f6b-85cd-51bd4a52ff51** [python/cpython#46167]
BPO | [1859](https://bugs.python.org/issue1859)
--- | :---
Nosy | @gvanrossum, @birkenfeld, @terryjreedy, @jcea, @mdickinson, @pitrou, @bitdancer, @cjerdonek, @serhiy-storchaka
Dependencies | <li>bpo-15510: textwrap.wrap(&#x27;&#x27;) returns empty list</li>
Files | <li>[textwrap-fix.patch](https://bugs.python.org/file9192/textwrap-fix.patch "Uploaded as text/plain at 2008-01-17.12:46:49 by palfrey"): Patch for the issue</li><li>[issue1859_docs.diff](https://bugs.python.org/file19676/issue1859_docs.diff "Uploaded as text/plain at 2010-11-20.15:24:04 by jerith")</li><li>[textwrap_2010-11-23.diff](https://bugs.python.org/file19791/textwrap_2010-11-23.diff "Uploaded as text/plain at 2010-11-23.20:19:16 by mrabarnett")</li><li>[line_break_tests.patch](https://bugs.python.org/file34519/line_break_tests.patch "Uploaded as text/plain at 2014-03-19.15:15:58 by dbudinova"): tests for  linebreak on "\n"</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-01-17.12:40:01.280>
labels = ['type-feature', 'library']
title = 'textwrap doesn\'t linebreak on "\\n"'
updated_at = <Date 2014-06-24.07:00:10.465>
user = 'https://bugs.python.org/palfrey'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-24.07:00:10.465>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-01-17.12:40:01.280>
creator = 'palfrey'
dependencies = ['15510']
files = ['9192', '19676', '19791', '34519']
hgrepos = []
issue_num = 1859
keywords = ['patch']
message_count = 46.0
messages = ['60026', '60027', '60031', '60032', '60038', '60039', '60040', '60042', '60043', '60045', '60047', '60048', '95469', '95483', '95547', '95562', '95797', '95798', '95800', '95831', '96064', '116915', '121658', '121663', '121914', '122189', '122196', '122200', '122222', '122242', '122244', '122246', '158106', '158107', '158135', '166625', '166627', '166629', '166809', '166811', '166816', '166941', '167373', '167381', '167412', '214103']
nosy_count = 17.0
nosy_names = ['gvanrossum', 'gward', 'georg.brandl', 'terry.reedy', 'jcea', 'mark.dickinson', 'tlynn', 'pitrou', 'palfrey', 'jerith', 'mrabarnett', 'r.david.murray', 'chris.jerdonek', 'paul.j3', 'serhiy.storchaka', 'otto', 'dbudinova']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue1859'
versions = ['Python 3.2']
```

</p></details>

**Comment by iritkatriel** [comment]
There were several votes in the long discussion for leaving this as it is. Marking and pending and will close soon if nobody will object.
