### ISSUE TITLE
dbmmodule bool function is performance prohibitive

### ISSUE THREAD

**Issue by 55c0789d-3aa5-4e63-bdd6-719e605b63a7** [python/cpython#46412]
BPO | [2159](https://bugs.python.org/issue2159)
--- | :---
Nosy | @jcea
Files | <li>[dbm_bool.patch](https://bugs.python.org/file34879/dbm_bool.patch "Uploaded as text/plain at 2014-04-15.16:33:13 by eolson"): Add nb_bool for ndbm and gdbm</li><li>[dbm_bool_b.patch](https://bugs.python.org/file34886/dbm_bool_b.patch "Uploaded as text/plain at 2014-04-15.18:54:17 by eolson"): Add nb_bool for ndbm and gdbm</li><li>[dbm_bool_c.patch](https://bugs.python.org/file34895/dbm_bool_c.patch "Uploaded as text/plain at 2014-04-15.20:34:27 by eolson")</li><li>[dbm_bool_d.patch](https://bugs.python.org/file34916/dbm_bool_d.patch "Uploaded as text/plain at 2014-04-16.17:50:47 by eolson"): Add nb_bool for ndbm and gdbm</li><li>[dbm_bool_e.patch](https://bugs.python.org/file35150/dbm_bool_e.patch "Uploaded as text/plain at 2014-05-04.15:01:47 by eolson"): Add nb_bool for ndbm and gdbm</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/jcea'
closed_at = None
created_at = <Date 2008-02-22.00:41:14.969>
labels = ['extension-modules', 'performance']
title = 'dbmmodule inquiry function is performance prohibitive'
updated_at = <Date 2014-05-04.15:01:48.260>
user = 'https://bugs.python.org/johansen'
```

bugs.python.org fields:
```python
activity = <Date 2014-05-04.15:01:48.260>
actor = 'eolson'
assignee = 'jcea'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2008-02-22.00:41:14.969>
creator = 'johansen'
dependencies = []
files = ['34879', '34886', '34895', '34916', '35150']
hgrepos = []
issue_num = 2159
keywords = ['patch']
message_count = 23.0
messages = ['62668', '64126', '64447', '65080', '65081', '68106', '68107', '80737', '216330', '216361', '216382', '216519', '217098', '217542', '217557', '217568', '217662', '217669', '217670', '217671', '217676', '217685', '217877']
nosy_count = 5.0
nosy_names = ['jafo', 'jcea', 'johansen', 'ysj.ray', 'eolson']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue2159'
versions = ['Python 3.5']
```

</p></details>

**Comment by gvanrossum** [comment]
This looks worthy. I propose to make a new patch that works with 3.11. Also Python code that uses “if db:” should probably use “if db is not None:”, else an empty db will be reopened over and over.

**Comment by gvanrossum** [comment]
I have a new PR (#96692). It's based on eolson's (Eric Olson's) last patch, from 2014. Alas, I don't have an email or GH username to attribute.

**Comment by gvanrossum** [comment]
This will be in 3.12.
