### ISSUE TITLE
speedup for / while / if with better bytecode

### ISSUE THREAD

**Issue by pitrou** [python/cpython#46711]
BPO | [2459](https://bugs.python.org/issue2459)
--- | :---
Nosy | @rhettinger, @gpshead, @jcea, @pitrou, @giampaolo, @tiran, @djc, @phsilva
Files | <li>[predict_loop.diff](https://bugs.python.org/file9877/predict_loop.diff "Uploaded as text/plain at 2008-03-27.16:21:48 by @arigo")</li><li>[for_iter.patch](https://bugs.python.org/file12923/for_iter.patch "Uploaded as text/plain at 2009-02-02.20:36:52 by @pitrou")</li><li>[trunk-opt-loop.patch](https://bugs.python.org/file13227/trunk-opt-loop.patch "Uploaded as text/plain at 2009-03-02.06:11:39 by jyasskin"): for_iter.patch merged with python/issues-test-cpython#4715</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-03-22.22:25:03.988>
labels = ['interpreter-core', 'performance']
title = 'speedup for / while / if with better bytecode'
updated_at = <Date 2014-06-22.12:04:07.520>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-22.12:04:07.520>
actor = 'BreamoreBoy'
assignee = 'jyasskin'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2008-03-22.22:25:03.988>
creator = 'pitrou'
dependencies = []
files = ['9877', '12923', '13227']
hgrepos = []
issue_num = 2459
keywords = ['patch']
message_count = 31.0
messages = ['64343', '64359', '64364', '64367', '64383', '64506', '64537', '64572', '64573', '64577', '64599', '64603', '66027', '68687', '80591', '80593', '80598', '80995', '81029', '81958', '81962', '81976', '82556', '82557', '83003', '83012', '83022', '83088', '106883', '192575', '221249']
nosy_count = 15.0
nosy_names = ['nnorwitz', 'collinwinter', 'rhettinger', 'gregory.p.smith', 'jcea', 'tzot', 'pitrou', 'giampaolo.rodola', 'christian.heimes', 'jyasskin', 'stutzbach', 'lauromoura', 'djc', 'phsilva', 'BreamoreBoy']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'languishing'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue2459'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
This experiment was abandoned over a decade ago and things have moved on since then. Unless someone objects I will close the issue.

**Comment by pitrou** [comment]
Definitely outdated :-)
