### ISSUE TITLE
email.feedparser regex duplicate

### ISSUE THREAD

**Issue by 74c4563b-ab1c-43d8-9219-30c4eca796bc** [python/cpython#46931]
BPO | [2679](https://bugs.python.org/issue2679)
--- | :---
Nosy | @ezio-melotti
Files | <li>[2679.patch](https://bugs.python.org/file27132/2679.patch "Uploaded as text/plain at 2012-09-06.05:33:34 by moijes12"): Change in patch : NLCRE_crack  = NLCRE_bol</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-04-24.13:52:19.311>
labels = ['3.8', 'library', '3.9', '3.10']
title = 'email.feedparser regex duplicate'
updated_at = <Date 2020-10-25.23:24:50.146>
user = 'https://bugs.python.org/jimjjewett'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-25.23:24:50.146>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-04-24.13:52:19.311>
creator = 'jimjjewett'
dependencies = []
files = ['27132']
hgrepos = []
issue_num = 2679
keywords = ['patch']
message_count = 2.0
messages = ['65723', '169904']
nosy_count = 2.0
nosy_names = ['jimjjewett', 'ezio.melotti']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue2679'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by hugovk** [comment]
I think we can close this issue: it's 15 years old, the patch is 10 years old. The patch is simple enough but no-one's been too bothered by the duplication in all this time.
