### ISSUE TITLE
Test issue

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#47020]
BPO | [2771](https://bugs.python.org/issue2771)
--- | :---
Nosy | @pitrou, @nedbat, @ezio-melotti, @zware, @matrixise, @ewdurbin
PRs | <li>python/cpython#46</li><li>python/cpython#56</li><li>python/cpython#55</li><li>python/cpython#59</li><li>python/cpython#60</li><li>python/cpython#61</li><li>python/cpython#62</li><li>python/cpython#63</li><li>python/cpython#70</li><li>python/cpython#107</li><li>python/cpython#18614</li>
Dependencies | <li>bpo-12345: Add math.tau</li><li>bpo-12346: Python source code build fails with old mercurial</li>
Superseder | <li>bpo-2771: Test issue</li>
Files | <li>[README.diff](https://bugs.python.org/file19097/README.diff "Uploaded as text/plain at 2010-10-01.22:09:31 by @loewis")</li><li>[a.diff](https://bugs.python.org/file21018/a.diff "Uploaded as text/plain at 2011-03-06.16:49:20 by @loewis")</li><li>[6a1c8fcce229.diff](https://bugs.python.org/file21103/6a1c8fcce229.diff "Uploaded as text/plain at 2011-03-13.16:15:05 by @loewis")</li><li>[sometext.txt](https://bugs.python.org/file21659/sometext.txt "Uploaded as text/plain at 2011-04-13.23:12:54 by @pitrou")</li><li>[foo](https://bugs.python.org/file21665/foo "Uploaded as text/plain at 2011-04-14.19:31:38 by @loewis")</li><li>[test.txt](https://bugs.python.org/file23266/test.txt "Uploaded as text/plain at 2011-09-29.22:19:21 by vsemionov"): test</li><li>[unnamed](https://bugs.python.org/file23322/unnamed "Uploaded as text/plain at 2011-10-06.10:41:28 by @ezio-melotti")</li><li>[issue12753-3.diff](https://bugs.python.org/file23323/issue12753-3.diff "Uploaded as text/plain at 2011-10-06.10:41:29 by @ezio-melotti")</li><li>[issue12753-3.diff](https://bugs.python.org/file23324/issue12753-3.diff "Uploaded as text/plain at 2011-10-06.10:48:51 by @ezio-melotti")</li><li>[unnamed](https://bugs.python.org/file23325/unnamed "Uploaded as text/plain at 2011-10-06.10:50:52 by @ezio-melotti"): This is a "test"</li><li>[issue12753-3.diff](https://bugs.python.org/file23326/issue12753-3.diff "Uploaded as text/plain at 2011-10-06.10:50:52 by @ezio-melotti")</li><li>[b17f9a10235f.diff](https://bugs.python.org/file27089/b17f9a10235f.diff "Uploaded as text/plain at 2012-09-01.19:24:48 by @ezio-melotti")</li><li>[entities.py](https://bugs.python.org/file27301/entities.py "Uploaded as text/plain at 2012-09-25.18:37:29 by @ezio-melotti")</li><li>[issue18958-2.diff](https://bugs.python.org/file35887/issue18958-2.diff "Uploaded as text/plain at 2014-07-07.17:23:37 by @ezio-melotti")</li><li>[testtestpatch](https://bugs.python.org/file39817/testtestpatch "Uploaded at 2015-06-26.15:18:33 by testbpo"): test</li><li>[issue18958-2.diff](https://bugs.python.org/file39819/issue18958-2.diff "Uploaded as text/plain at 2015-06-26.15:38:50 by testbpo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ezio-melotti'
closed_at = None
created_at = <Date 2008-05-05.16:40:44.378>
labels = ['easy', 'type-bug', 'tests', '3.11']
title = 'Test issue'
updated_at = <Date 2022-04-08.18:14:51.526>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.18:14:51.526>
actor = 'ezio.melotti'
assignee = 'ezio.melotti'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2008-05-05.16:40:44.378>
creator = 'gvanrossum'
dependencies = ['12345', '12346']
files = ['19097', '21018', '21103', '21659', '21665', '23266', '23322', '23323', '23324', '23325', '23326', '27089', '27301', '35887', '39817', '39819']
hgrepos = ['1', '2', '148']
issue_num = 2771
keywords = ['easy']
message_count = 145.0
messages = ['66272', '70327', '82492', '82495', '82496', '83238', '83244', '83245', '83438', '85703', '85704', '85706', '85707', '85709', '85711', '85712', '117840', '123996', '123997', '130141', '130313', '130314', '130315', '130316', '130317', '130318', '130320', '130323', '130325', '130328', '130352', '130353', '130354', '130355', '130356', '130357', '130358', '130359', '130360', '130363', '130364', '130365', '130371', '130708', '130711', '130746', '131876', '131877', '131887', '132862', '143322', '144642', '144643', '144644', '144988', '144989', '144990', '144991', '147556', '147558', '148435', '154050', '158528', '161311', '164482', '164498', '164499', '166660', '169819', '171493', '171496', '171545', '171565', '171566', '171569', '175115', '175117', '175601', '175602', '175604', '175609', '175610', '175611', '175612', '175613', '175614', '175801', '177455', '184606', '185210', '185211', '186162', '186457', '190899', '200373', '210887', '210888', '210899', '216745', '216749', '222481', '226864', '226865', '240911', '244636', '244637', '281623', '282111', '282209', '284785', '284786', '284856', '285373', '286827', '296933', '301677', '303086', '326188', '326189', '326190', '326354', '326503', '326930', '327448', '330748', '330753', '332292', '332369', '335253', '335254', '335258', '335263', '335266', '335267', '335270', '338799', '338800', '344722', '344723', '352015', '394297', '394298', '394456', '405354', '416999']
nosy_count = 7.0
nosy_names = ['pitrou', 'nedbat', 'ezio.melotti', 'python-dev', 'zach.ware', 'matrixise', 'EWDurbin']
pr_nums = ['46', '56', '55', '59', '60', '61', '62', '63', '70', '107', '18614']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'open'
superseder = '2771'
type = 'behavior'
url = 'https://bugs.python.org/issue2771'
versions = ['Python 3.11']
```

</p></details>

**Comment by ezio-melotti** [comment]
𝔹𝔹

**Comment by ezio-melotti** [comment]
test

**Comment by ezio-melotti** [comment]
test
