### ISSUE TITLE
curses for windows (alternative patch)

### ISSUE THREAD

**Issue by 9432cd65-9f88-4bc6-8ad6-72e5ab1c730d** [python/cpython#47138]
BPO | [2889](https://bugs.python.org/issue2889)
--- | :---
Nosy | @loewis, @pfmoore, @jkloth, @Trundle, @ipatrol, @ulfalizer, @madebr
Files | <li>[curses_win_port.patch.txt](https://bugs.python.org/file10339/curses_win_port.patch.txt "Uploaded as text/plain at 2008-05-16.06:38:18 by techtonik")</li><li>[curses_win_compile.bat](https://bugs.python.org/file10340/curses_win_compile.bat "Uploaded as application/octet-stream at 2008-05-16.06:39:47 by techtonik")</li><li>[python-pdcurses.patch](https://bugs.python.org/file12862/python-pdcurses.patch "Uploaded as text/plain at 2009-01-26.00:49:33 by zhirsch")</li><li>[python-pdcurses-2.patch](https://bugs.python.org/file13282/python-pdcurses-2.patch "Uploaded as text/plain at 2009-03-09.09:56:48 by zhirsch")</li><li>[python-pdcurses-3.patch](https://bugs.python.org/file15171/python-pdcurses-3.patch "Uploaded as text/plain at 2009-10-21.07:24:17 by jmb")</li><li>[pdcurses-changes.patch](https://bugs.python.org/file20492/pdcurses-changes.patch "Uploaded as text/plain at 2011-01-23.11:49:09 by Prasun Ratn"): Changes to Lib/test/test_curses.py Modules/_cursesmodule.c PC/mkstemp.c PC/pyconfig.h PCbuild/_curses.vcproj PCbuild/_curses_panel.vcproj PCbuild/pcbuild.sln PCbuild/pdcurses.vcproj PCbuild/pythoncore.vcproj</li><li>[pdcurses.patch](https://bugs.python.org/file20493/pdcurses.patch "Uploaded as text/plain at 2011-01-23.11:50:10 by Prasun Ratn"): pdcurses source</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-05-16.06:38:26.189>
labels = ['extension-modules', 'type-feature', 'OS-windows']
title = 'curses for windows (alternative patch)'
updated_at = <Date 2021-04-05.14:37:31.276>
user = 'https://bugs.python.org/techtonik'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-05.14:37:31.276>
actor = 'jkloth'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Windows']
creation = <Date 2008-05-16.06:38:26.189>
creator = 'techtonik'
dependencies = []
files = ['10339', '10340', '12862', '13282', '15171', '20492', '20493']
hgrepos = []
issue_num = 2889
keywords = ['patch']
message_count = 23.0
messages = ['66920', '67288', '80554', '82781', '83365', '94309', '114011', '114013', '114370', '114399', '114740', '114770', '114778', '116224', '126887', '128191', '185746', '222640', '236384', '237855', '237857', '349089', '375683']
nosy_count = 16.0
nosy_names = ['loewis', 'paul.moore', 'techtonik', 'jkloth', 'rpetrov', 'zhirsch', 'Trundle', 'cgohlke', 'jmb', 'ipatrol', 'Prasun Ratn', 'christoph.baumgartner', 'Taylor.Marks', 'Mario Figueiredo', 'ulfalizer', 'maarten']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue2889'
versions = ['Python 3.3']
```

</p></details>

**Comment by erlend-aasland** [comment]
@pfmoore:
> Unless someone is going to step up and do all of that (and keep it maintained until it gets merged, which probably won't be till 3.6) *and* there's one of the core devs willing to support the code going forward once its committed, then I think closing this as "won't fix" and referring to the external packages is the best solution.

+1

Also, the [windows-curses](https://pypi.org/project/windows-curses/) package seems to be fairly up to date for those who want to use PDCurses on Windows.

**Comment by AA-Turner** [comment]
Closing as windows-curses exists, and per Paul & Erlend. If someone would like to do the work to implement curses on windows, we could re-open this issue or discuss in a new one (referencing 3.12+ rather than 3.6!)

A

**Comment by irvinren** [comment]
> Closing as windows-curses exists, and per Paul & Erlend. If someone would like to do the work to implement curses on windows, we could re-open this issue or discuss in a new one (referencing 3.12+ rather than 3.6!)
> 
> A



> Closing as windows-curses exists, and per Paul & Erlend. If someone would like to do the work to implement curses on windows, we could re-open this issue or discuss in a new one (referencing 3.12+ rather than 3.6!)
> 
> A

Windows-curses quit silently on Cpython3.12. is it possible to reopen this issue?

**Comment by irvinren** [comment]
@AA-Turner 
windows-curses stopped active development and looking for another maintainer, is it possible to reopen this issue?
[https://github.com/zephyrproject-rtos/windows-curses/issues/50#issuecomment-1835851654](url)

**Comment by irvinren** [comment]
> See also #40725.

that one seems not for MSVC compiler. Could I directly try this patch?

**Comment by irvinren** [comment]
> See also #40725.

that one seems not for MSVC compiler. Could I directly try this patch?

**Comment by erlend-aasland** [comment]
> that one seems not for MSVC compiler. Could I directly try this patch?

I'm not sure which patch you are referring to, but I'd expect _all_ the attached files both in _this_ issue and #40725 to be **seriously outdated**; I would not expect any of these to merge cleanly into `main`, and even if they would merge "cleanishly", I would not expect them to compile. Any attempt at getting this ball rolling again would have to start by either adapting one of the outdated patches to work with the current C API, or by writing the extension module from scratch.

**Comment by cgohlke** [comment]
FWIW, I moved the code and build script used for https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses to https://github.com/cgohlke/python-curses-build

**Comment by ashm-dev** [comment]
Ping. Is this issue still relevant?
