### ISSUE TITLE
PyMemberDef missing in limited API / Deprecate structmember.h

### ISSUE THREAD

**Issue by benjaminp** [python/cpython#47146]
BPO | [2897](https://bugs.python.org/issue2897)
--- | :---
Nosy | @loewis, @smontanaro, @birkenfeld, @rhettinger, @abalkin, @vstinner, @benjaminp, @berkerpeksag, @serhiy-storchaka, @matrixise, @erlend-aasland, @MatzeB
PRs | <li>python/cpython#20462</li><li>python/cpython#22419</li>
Dependencies | <li>bpo-24065: Outdated *_RESTRICTED flags in structmember.h</li><li>bpo-28349: Issues with PyMemberDef flags</li>
Files | <li>[issue2897.diff](https://bugs.python.org/file44943/issue2897.diff "Uploaded as text/plain at 2016-10-03.18:05:44 by @abalkin")</li><li>[issue2897-docs-3x.diff](https://bugs.python.org/file44976/issue2897-docs-3x.diff "Uploaded as text/plain at 2016-10-05.16:23:31 by @abalkin")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2008-05-16.22:45:11.685>
labels = ['interpreter-core', 'expert-C-API', 'type-feature', '3.10', 'docs']
title = 'PyMemberDef missing in limited API / Deprecate structmember.h'
updated_at = <Date 2020-09-26.20:51:31.703>
user = 'https://github.com/benjaminp'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-26.20:51:31.703>
actor = 'erlendaasland'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Interpreter Core', 'C API']
creation = <Date 2008-05-16.22:45:11.685>
creator = 'benjamin.peterson'
dependencies = ['24065', '28349']
files = ['44943', '44976']
hgrepos = []
issue_num = 2897
keywords = ['patch']
message_count = 21.0
messages = ['66972', '67028', '67062', '79242', '79244', '277971', '277973', '277976', '277982', '277985', '277986', '277988', '278136', '342468', '370098', '370100', '370101', '370104', '370106', '370107', '370138']
nosy_count = 15.0
nosy_names = ['loewis', 'skip.montanaro', 'georg.brandl', 'rhettinger', 'belopolsky', 'vstinner', 'benjamin.peterson', 'Arfrever', 'herzbube', 'docs@python', 'berker.peksag', 'serhiy.storchaka', 'matrixise', 'erlendaasland', 'Matthias Braun']
pr_nums = ['20462', '22419']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue2897'
versions = ['Python 3.10']
```

</p></details>

* PR: gh-99014

**Comment by encukou** [comment]
I ran into this issue, so I made a PR: #99014
The twist is that old code doesn't need to change. That would be unnecessary churn. Keeping a few weirdly named aliases around is not a maintenance burden, and since they need the extra header they won't pollute new code.
