### ISSUE TITLE
_zip_directory_cache untested and undocumented

### ISSUE THREAD

**Issue by fijal** [python/cpython#47202]
BPO | [2953](https://bugs.python.org/issue2953)
--- | :---
Nosy | @birkenfeld, @ncoghlan, @tarekziade, @merwok, @ericsnowcurrently

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-05-23.20:26:03.700>
labels = ['extension-modules', 'type-bug', 'docs']
title = '_zip_directory_cache untested and undocumented'
updated_at = <Date 2013-04-07.15:22:57.800>
user = 'https://bugs.python.org/fijal'
```

bugs.python.org fields:
```python
activity = <Date 2013-04-07.15:22:57.800>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Extension Modules']
creation = <Date 2008-05-23.20:26:03.700>
creator = 'fijal'
dependencies = []
files = []
hgrepos = []
issue_num = 2953
keywords = []
message_count = 19.0
messages = ['67267', '84384', '84397', '84911', '85069', '85585', '85586', '85591', '85595', '85597', '85598', '85599', '85608', '85610', '85660', '118403', '175807', '175808', '175810']
nosy_count = 6.0
nosy_names = ['georg.brandl', 'ncoghlan', 'fijal', 'tarek', 'eric.araujo', 'eric.snow']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue2953'
versions = ['Python 2.7', 'Python 3.3']
```

</p></details>

**Comment by erlend-aasland** [comment]
Maciej, in https://github.com/python/cpython/issues/47202#issuecomment-1093423324

> The bug with this is that setuptools uses it (and even relies on what is
there and in what order), while it has no single tests and no documentation.

Maciej, in https://github.com/python/cpython/issues/47202#issuecomment-1093423332:

> I propose to have a clean api on zipimporter how to invalidate it's
caches. Maybe a general mechanism for that, I don't know.

Éric, in https://github.com/python/cpython/issues/47202#issuecomment-1093423343:

> If zipimport now works with the invalidate_caches system, then we do have a documented way of clearing the cache, and I would recommend closing this bug [...]

In 2024, setuptools does not use it anymore, and zipimport supports `invalidate_caches()`. Looks to me we can close this as outdated.

**Comment by brettcannon** [comment]
Thanks, @erlend-aasland for the digging! Closing the issue.
