### ISSUE TITLE
Add shutil.open

### ISSUE THREAD

**Issue by f601c944-163b-4aa4-8d5d-9c031a35257c** [python/cpython#47427]
BPO | [3177](https://bugs.python.org/issue3177)
--- | :---
Nosy | @ronaldoussoren, @tebeka, @pitrou, @larryhastings, @giampaolo, @benjaminp, @mcepl, @merwok, @bitdancer, @smarnach, @Fak3, @danpla
Files | <li>[os_startfile.diff](https://bugs.python.org/file10715/os_startfile.diff "Uploaded as text/plain at 2008-06-24.02:34:21 by ganadist"): patch that implemented os.startfile()</li><li>[shutil_open.py](https://bugs.python.org/file25310/shutil_open.py "Uploaded as text/plain at 2012-04-23.08:04:31 by cvrebert"): implementation sketch</li><li>[shutil_launch.py](https://bugs.python.org/file25311/shutil_launch.py "Uploaded as text/plain at 2012-04-23.10:29:19 by Hobson.Lane"): The last 1/3rd of Rebert's implementation of shutil.open()</li><li>[shutil_open.patch](https://bugs.python.org/file25312/shutil_open.patch "Uploaded as text/plain at 2012-04-23.10:39:44 by Hobson.Lane"): Implementation of shutil_open feature, untested on Windows</li><li>[shutil_open.patch](https://bugs.python.org/file25315/shutil_open.patch "Uploaded as text/plain at 2012-04-23.16:09:45 by Hobson.Lane")</li><li>[shutil_open.patch](https://bugs.python.org/file25317/shutil_open.patch "Uploaded as text/plain at 2012-04-23.16:34:06 by Hobson.Lane"): provides shutil.launch() to do os.startfile() cross-platform</li><li>[shutil_open.patch](https://bugs.python.org/file25319/shutil_open.patch "Uploaded as text/plain at 2012-04-23.17:35:04 by Hobson.Lane"): another round of improvement</li><li>[shutil_open.patch](https://bugs.python.org/file25332/shutil_open.patch "Uploaded as text/plain at 2012-04-23.23:53:31 by cvrebert"): revised patch</li><li>[issue3177-os_startfile_macosx.txt](https://bugs.python.org/file26624/issue3177-os_startfile_macosx.txt "Uploaded as text/plain at 2012-07-31.16:03:32 by @ronaldoussoren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-06-23.11:38:23.901>
labels = ['type-feature', 'library']
title = 'Add shutil.open'
updated_at = <Date 2018-03-02.17:06:15.586>
user = 'https://bugs.python.org/ganadist'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-02.17:06:15.586>
actor = 'Socob'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-06-23.11:38:23.901>
creator = 'ganadist'
dependencies = []
files = ['10715', '25310', '25311', '25312', '25315', '25317', '25319', '25332', '26624']
hgrepos = []
issue_num = 3177
keywords = ['patch']
message_count = 62.0
messages = ['68623', '68650', '68664', '140059', '140275', '140276', '140280', '140283', '140415', '140416', '140418', '140419', '157216', '157246', '157247', '157258', '159000', '159001', '159004', '159005', '159006', '159007', '159008', '159009', '159010', '159017', '159020', '159029', '159030', '159034', '159037', '159038', '159039', '159043', '159044', '159051', '159056', '159058', '159059', '159062', '159063', '159064', '159065', '159068', '159069', '159121', '159505', '159507', '161569', '161613', '161631', '161687', '161688', '161837', '161852', '161853', '161854', '161858', '167011', '310214', '311549', '311552']
nosy_count = 19.0
nosy_names = ['ronaldoussoren', 'tebeka', 'pitrou', 'larry', 'giampaolo.rodola', 'benjamin.peterson', 'mcepl', 'eric.araujo', 'ganadist', 'Arfrever', 'r.david.murray', 'cvrebert', 'rosslagerwall', 'smarnach', 'Roman.Evstifeev', 'Hobson.Lane', 'plakhotich', 'Socob', 'amirjn']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue3177'
versions = ['Python 3.3']
```

</p></details>

**Comment by dbarnett** [comment]
Hello from 2024! :wave: 

Any hope of getting a shutil.open implementation landed still? It looks like this issue stalled out after 2012...

It's been discussed on a popular [StackOverflow question](https://stackoverflow.com/questions/434597/open-document-with-default-os-application-in-python-both-in-windows-and-mac-os), and there's now a [universal-startfile] package on PyPI attempting to offer the same thing.

**Comment by merwok** [comment]
I don’t think there is a well thought-out proposal, or a big need for this.
Third-party modules can fill the need.

**Comment by dbarnett** [comment]
What's the rationale for "not a big need"? To me the popular StackOverflow questions (+ lots of dupes of it) suggest otherwise. 

I was actually considering to publish my own third-party module for it, but would prefer to make it a drop-in polyfill with whatever's planned for standard library here (and the half-working os.startfile) instead of trying to freehand a signature myself.

@all could anyone help direct me to min viable behavior if I were volunteering to implement it in a module?

**Comment by dbarnett** [comment]
K, I've implemented a quick https://pypi.org/project/shopen/ with my understanding of what a shutil.open should offer. IMO it'd still be great to have those batteries come included with python, but for now I can iterate there on ironing out the wrinkles.

**Comment by zed** [comment]
Often `shutil_open = webbrowser.open` works.
