### ISSUE TITLE
Option in pydoc to show docs from private methods

### ISSUE THREAD

**Issue by 1bc946c9-bbad-48a6-8fcc-0f910153036b** [python/cpython#47446]
BPO | [3196](https://bugs.python.org/issue3196)
--- | :---
Nosy | @abalkin
Files | <li>[pydoc.privatenames.patch](https://bugs.python.org/file10727/pydoc.privatenames.patch "Uploaded as text/plain at 2008-06-25.09:32:32 by mortenlj"): Adding option to include private names to pydoc</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-06-25.09:32:34.926>
labels = ['type-feature', 'library']
title = 'Option in pydoc to show docs from private methods'
updated_at = <Date 2010-10-25.02:36:21.163>
user = 'https://bugs.python.org/mortenlj'
```

bugs.python.org fields:
```python
activity = <Date 2010-10-25.02:36:21.163>
actor = 'r.david.murray'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-06-25.09:32:34.926>
creator = 'mortenlj'
dependencies = []
files = ['10727']
hgrepos = []
issue_num = 3196
keywords = ['patch']
message_count = 3.0
messages = ['68722', '110146', '111204']
nosy_count = 2.0
nosy_names = ['belopolsky', 'mortenlj']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'languishing'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue3196'
versions = ['Python 3.2']
```

</p></details>

**Comment by iritkatriel** [comment]
This has been abandoned for over a decade. I suggest we close it and if someone comes up with a need/use case it can be reopened or a new issue created.
