### ISSUE TITLE
make built-in tokenizer available via Python C API

### ISSUE THREAD

**Issue by b7a711ff-d634-47b2-ad1b-41e5ae806c8b** [python/cpython#47603]
BPO | [3353](https://bugs.python.org/issue3353)
--- | :---
Nosy | @amauryfa, @meadori, @berkerpeksag, @serhiy-storchaka, @asottile, @DimitrisJim, @pablogsal
Dependencies | <li>bpo-25643: Python tokenizer rewriting</li>
Files | <li>[issue3353.diff](https://bugs.python.org/file10961/issue3353.diff "Uploaded as text/plain at 2008-07-23.22:53:02 by kirkshorts"): Patch to move the include file etc</li><li>[82706ea73ada.diff](https://bugs.python.org/file35730/82706ea73ada.diff "Uploaded as text/plain at 2014-06-22.18:36:53 by Andrew.C")</li><li>[issue3353.patch](https://bugs.python.org/file38992/issue3353.patch "Uploaded as text/plain at 2015-04-14.16:07:58 by djmitche"): issue3353.patch</li><li>[issue3353-2.patch](https://bugs.python.org/file38999/issue3353-2.patch "Uploaded as text/plain at 2015-04-14.18:06:30 by djmitche"): issue3353-2.patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-07-14.11:32:15.414>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'make built-in tokenizer available via Python C API'
updated_at = <Date 2021-01-27.21:14:20.006>
user = 'https://bugs.python.org/effbot'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-27.21:14:20.006>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2008-07-14.11:32:15.414>
creator = 'effbot'
dependencies = ['25643']
files = ['10961', '35730', '38992', '38999']
hgrepos = ['260']
issue_num = 3353
keywords = ['patch']
message_count = 34.0
messages = ['69650', '70101', '70102', '70181', '70227', '70305', '143717', '221293', '240882', '240927', '240967', '245939', '289535', '289537', '289584', '289585', '289587', '289590', '289591', '385736', '385756', '385788', '385790', '385791', '385792', '385793', '385794', '385795', '385796', '385797', '385798', '385799', '385808', '385811']
nosy_count = 12.0
nosy_names = ['effbot', 'amaury.forgeotdarc', 'djmitche', 'kirkshorts', 'meador.inge', 'berker.peksag', 'serhiy.storchaka', 'superluser', 'Andrew.C', 'Anthony Sottile', 'Jim Fasarakis-Hilliard', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue3353'
versions = ['Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Could you submit a PR for this? 

I haven't seen any objections to this change, a PR will expose this to more people and a clear decision on whether this change is warranted can be finally made (I hope).

**Comment by da6b7fff-0e4f-4c5e-b3e5-47fd12537ac6** [comment]
If the patch still applies cleanly, I have no issues with you or anyone opening a PR.  I picked this up several years ago at the PyCon sprints, and don't remember a thing about it, nor have I touched any other bit of the CPython source since then.  So any merge conflicts would be very difficult for me to resolve.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Okay, I'll take a look at it over the next days and try and submit a PR after fixing any issues that might be present.

**Comment by serhiy-storchaka** [comment]
Please hold this until finishing bpo-25643.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Thanks for linking the dependency, Serhiy :-) 

Is there anybody currently working on the other issue? Also, shouldn't both issues now get retagged to Python 3.7?

**Comment by serhiy-storchaka** [comment]
I am working on the other issue (the recent patch is still not published). Sorry, but two issues modify the same code and are conflicting. Since I believe that this issue makes less semantic changes, I think it would be easier to rebase it after finishing bpo-25643 than do it in contrary order.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
That makes sense to me, I'll wait around until the dependency is resolved.

**Comment by lysnikolaou** [comment]
Since 3.12 the Python `tokenize` module uses the C tokenizer internally. Is this enough to close this issue?

**Comment by pablogsal** [comment]
Yup
