### ISSUE TITLE
urlparse - relative url parsing and joins to be RFC3986 compliance

### ISSUE THREAD

**Issue by orsenthil** [python/cpython#47897]
BPO | [3647](https://bugs.python.org/issue3647)
--- | :---
Nosy | @gpshead, @orsenthil, @vadmium
Files | <li>[urlparse_rfc3986-py26.diff](https://bugs.python.org/file11208/urlparse_rfc3986-py26.diff "Uploaded as text/plain at 2008-08-22.12:54:31 by @orsenthil")</li><li>[urlparse_rfc3986-py3k.diff](https://bugs.python.org/file11209/urlparse_rfc3986-py3k.diff "Uploaded as text/plain at 2008-08-22.12:55:00 by @orsenthil")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = None
created_at = <Date 2008-08-22.12:54:33.965>
labels = ['type-feature', 'library']
title = 'urlparse - relative url parsing and joins to be RFC3986 compliance'
updated_at = <Date 2015-02-09.00:10:27.387>
user = 'https://github.com/orsenthil'
```

bugs.python.org fields:
```python
activity = <Date 2015-02-09.00:10:27.387>
actor = 'martin.panter'
assignee = 'orsenthil'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-08-22.12:54:33.965>
creator = 'orsenthil'
dependencies = []
files = ['11208', '11209']
hgrepos = []
issue_num = 3647
keywords = ['patch']
message_count = 6.0
messages = ['71743', '72067', '74851', '74852', '74856', '109962']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'jjlee', 'orsenthil', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue3647'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It seems that the current code is much more RFC3986 compliant. I suppose that the proposed patches are outdated and the problem is already solved.
