### ISSUE TITLE
_curses, _curses_panel & _multiprocessing can't be build in 2.6b3 w/ SunStudio 12

### ISSUE THREAD

**Issue by 95617188-7979-4c94-90ec-327a8478a27b** [python/cpython#48036]
BPO | [3786](https://bugs.python.org/issue3786)
--- | :---
Nosy | @loewis, @jcea, @vstinner, @merwok, @serhiy-storchaka
Files | <li>[EKIT.patch](https://bugs.python.org/file14951/EKIT.patch "Uploaded as text at 2009-09-23.05:31:56 by iandekit"): patch for lack of mvwchgat and wchgat</li><li>[bug3786.patch](https://bugs.python.org/file26171/bug3786.patch "Uploaded as text/plain at 2012-06-27.05:07:00 by Justin.Venus")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-09-05.09:55:20.360>
labels = ['build']
title = "_curses, _curses_panel & _multiprocessing can't be build in 2.6b3 w/ SunStudio 12"
updated_at = <Date 2017-11-01.17:54:25.874>
user = 'https://bugs.python.org/mschmarck'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-01.17:54:25.874>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2008-09-05.09:55:20.360>
creator = 'mschmarck'
dependencies = []
files = ['14951', '26171']
hgrepos = []
issue_num = 3786
keywords = ['patch']
message_count = 16.0
messages = ['72579', '72581', '72584', '72752', '72768', '72770', '72836', '84920', '93023', '148522', '149005', '149009', '164119', '164875', '164905', '305387']
nosy_count = 9.0
nosy_names = ['loewis', 'jcea', 'vstinner', 'enchanter', 'eric.araujo', 'mschmarck', 'iandekit', 'serhiy.storchaka', 'Justin.Venus']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue3786'
versions = ['Python 3.2', 'Python 3.3']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
bpo-31919 have made \_curses be built on OpenIndiana with the default curses library. I suppose this have fixed this issue on Solaris too.

But configuring \_curses to use XPG4 curses is a different issue.

**Comment by AA-Turner** [comment]
Solaris isn't a PEP-11 supported platform, I might suggest closing this issue.

A

**Comment by vstinner** [comment]
There is @kulikjak who is interested in improving Solaris support in Python. If we close all Solaris issues, maybe it would be useful to add an ``OS-solaris`` label first. So if someone else wants to dig into old closed (rejected) Solaris issues, there is an easy way to list all of them.

**Comment by merwok** [comment]
A meta-ticket or project board could be better than a label!

**Comment by vstinner** [comment]
I would prefer to not create a project if the OS is not supported by PEP 11. The purpose of PEP 11 is to reduce the maintenance burden. Adding a project increases the maintenance burden: who maintains the project? what should people do with this project?

**Comment by kulikjak** [comment]
Oh, I didn't know about this issue. I recently created #91964 to fix this/similar issue.

As for listing all the issues, all of those I created have **Solaris** in their name so searching from them should be simple enough (at least those created by me).

Closing this issue seems reasonable - it's filed against _fairly_ old runtime, and we are not using Sun/Solaris Studio to compile Python for some time and AFAIK neither do other Solaris distributions.

As for other PRs filed against Solaris, Is there something I can do to help with them being reviewed / merged? Would it e.g., help if those were reviewed by people from other Solarises (I believe I know somebody from both Illumos and OmniOS)? I am happy to help with whatever is necessary to get them merged.

**Comment by AA-Turner** [comment]
Closing per Jakub's rationale.

I agree with Victor -- I'm not searching activley for Solaris issues to close them, but given the update to PEP 11 it would be useful to know what the rules of engagement are for unsupported platforms.

Given anyone can create a project on their own fork and add issues, perhaps @kulikjak could create one on an offical Solaris / Oracle fork of CPython to track solaris related issues?

A

**Comment by kulikjak** [comment]
Well, I guess that's possible, but do you think that anybody except for me would realistically look there for Solaris related issues? How would that work?

**Comment by jcea** [comment]
I am interested in Python working in Solaris/Illumos platforms too.
