### ISSUE TITLE
unittest: display time used by each test case

### ISSUE THREAD

**Issue by 54ba40f2-e737-40de-b848-a39d2cb8c2e9** [python/cpython#48330]
BPO | [4080](https://bugs.python.org/issue4080)
--- | :---
Nosy | @rhettinger, @giampaolo, @ezio-melotti, @merwok, @voidspace
PRs | <li>python/cpython#12271</li>
Files | <li>[pyunit_time.patch](https://bugs.python.org/file11751/pyunit_time.patch "Uploaded as text/plain at 2008-10-08.20:28:14 by pprokop"): display time of each unit test - patch</li><li>[unittest_runTime.patch](https://bugs.python.org/file15332/unittest_runTime.patch "Uploaded as text/plain at 2009-11-14.19:00:28 by pprokop"): test case run time measure patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-10-08.20:28:15.274>
labels = ['tests', 'type-feature', 'library', '3.9']
title = 'unittest: display time used by each test case'
updated_at = <Date 2020-02-16.12:49:33.700>
user = 'https://bugs.python.org/pprokop'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-16.12:49:33.700>
actor = 'giampaolo.rodola'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2008-10-08.20:28:15.274>
creator = 'pprokop'
dependencies = []
files = ['11751', '15332']
hgrepos = []
issue_num = 4080
keywords = ['patch']
message_count = 17.0
messages = ['74545', '87989', '95253', '109448', '110692', '110800', '110883', '154650', '154678', '154687', '154769', '154771', '154776', '155721', '176157', '337648', '362067']
nosy_count = 8.0
nosy_names = ['rhettinger', 'techtonik', 'giampaolo.rodola', 'ezio.melotti', 'eric.araujo', 'pprokop', 'michael.foord', 'piotr.dobrogost']
pr_nums = ['12271']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue4080'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-103309
* gh-103209

**Comment by hugovk** [comment]
Closing, the PR has been merged: https://github.com/python/cpython/pull/12271 👍
