### ISSUE TITLE
function with modified __name__ uses original name when there's an arg error

### ISSUE THREAD

**Issue by efd54b2f-2106-478f-aa8c-13cab7280b31** [python/cpython#48572]
BPO | [4322](https://bugs.python.org/issue4322)
--- | :---
Nosy | @jcea, @benjaminp, @bitdancer, @berkerpeksag, @vadmium, @iritkatriel
Dependencies | <li>bpo-2786: Names in function call exception should have class names, if they&#x27;re methods</li>
Files | <li>[issue4322.patch](https://bugs.python.org/file34318/issue4322.patch "Uploaded as text/plain at 2014-03-09.21:34:23 by mchelem")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2008-11-14.06:44:18.058>
labels = ['type-bug', 'library', '3.11']
title = "function with modified __name__ uses original name when there's an arg error"
updated_at = <Date 2021-11-26.16:39:47.344>
user = 'https://bugs.python.org/erickt'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-26.16:39:47.344>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2008-11-14.06:44:18.058>
creator = 'erickt'
dependencies = ['2786']
files = ['34318']
hgrepos = []
issue_num = 4322
keywords = ['patch']
message_count = 7.0
messages = ['75853', '75886', '194424', '212988', '213183', '249573', '407068']
nosy_count = 8.0
nosy_names = ['jcea', 'benjamin.peterson', 'erickt', 'r.david.murray', 'berker.peksag', 'martin.panter', 'mchelem', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue4322'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103459

**Comment by furkanonder** [comment]
When too many arguments are passed to a function, a `TypeError` is generated using `__qualname__`.  I created a [PR](https://github.com/python/cpython/pull/103459) that solves the problem by updating the `__qualname__` attribute when the function's `__name__` attribute is changed. I know it's not a very good solution so I'm waiting for your ideas and suggestions.

**Comment by rhettinger** [comment]
I'm not sure I agree that there is a problem.  ISTM that reporting the original `__qualname__` is useful because it can be related back the original source code.  Presumably, that is what you really want when tracking down a bug.

**Comment by JelleZijlstra** [comment]
I also don't see a problem here. If you change `__qualname__`, the error message reflects that:

```
>>> def foo(): pass
... 
>>> foo.__qualname__ = "bar"
>>> foo(1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: bar() takes 0 positional arguments but 1 was given
```
