### ISSUE TITLE
Make python code compilable with a C++ compiler

### ISSUE THREAD

**Issue by abalkin** [python/cpython#49055]
BPO | [4805](https://bugs.python.org/issue4805)
--- | :---
Nosy | @malemburg, @abalkin, @serhiy-storchaka
Files | <li>[c++-patch.diff](https://bugs.python.org/file12527/c%2B%2B-patch.diff "Uploaded as text/plain at 2009-01-02.04:56:40 by @abalkin")</li><li>[c++-patch-2.diff](https://bugs.python.org/file12560/c%2B%2B-patch-2.diff "Uploaded as text/plain at 2009-01-03.05:17:16 by @abalkin")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-01-02.04:56:46.153>
labels = ['type-feature']
title = 'Make python code compilable with a C++ compiler'
updated_at = <Date 2012-12-03.08:08:08.342>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2012-12-03.08:08:08.342>
actor = 'Arfrever'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2009-01-02.04:56:46.153>
creator = 'belopolsky'
dependencies = []
files = ['12527', '12560']
hgrepos = []
issue_num = 4805
keywords = ['patch']
message_count = 12.0
messages = ['78756', '78764', '78821', '78822', '78823', '78928', '79130', '79162', '79182', '79194', '79201', '79248']
nosy_count = 4.0
nosy_names = ['lemburg', 'belopolsky', 'Arfrever', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue4805'
versions = ['Python 3.4']
```

</p></details>

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/91321
