### ISSUE TITLE
wave.py: add writesamples() and readsamples()

### ISSUE THREAD

**Issue by a2cfeebf-2f9d-4445-bb05-7649090f0b16** [python/cpython#49163]
BPO | [4913](https://bugs.python.org/issue4913)
--- | :---
Nosy | @terryjreedy, @bitdancer, @serhiy-storchaka
Files | <li>[wave_futz.zip](https://bugs.python.org/file12703/wave_futz.zip "Uploaded as application/zip at 2009-01-12.14:37:34 by alex_python_org"): wave.py read/write-samples logic and test program.</li><li>[wave_futz.zip](https://bugs.python.org/file12985/wave_futz.zip "Uploaded as application/x-download at 2009-02-08.21:22:44 by alex_python_org"): Code that could be added to wave.py. And amended test_wave.py.</li><li>[wave_futz.py](https://bugs.python.org/file18451/wave_futz.py "Uploaded as text/plain at 2010-08-09.07:21:56 by alex_python_org"): patches and such-like for Python's wave.py</li><li>[test_wave.py](https://bugs.python.org/file18452/test_wave.py "Uploaded as text/plain at 2010-08-09.07:23:06 by alex_python_org"): Modified test for wave.py.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-01-11.02:16:42.537>
labels = ['type-feature', 'library']
title = 'wave.py: add writesamples() and readsamples()'
updated_at = <Date 2014-05-13.11:14:33.291>
user = 'https://bugs.python.org/alexpythonorg'
```

bugs.python.org fields:
```python
activity = <Date 2014-05-13.11:14:33.291>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2009-01-11.02:16:42.537>
creator = 'alex_python_org'
dependencies = []
files = ['12703', '12985', '18451', '18452']
hgrepos = []
issue_num = 4913
keywords = ['patch']
message_count = 27.0
messages = ['79586', '79616', '79617', '79618', '79619', '79643', '79644', '79660', '79668', '79669', '79678', '79681', '79686', '79691', '79692', '79714', '79716', '81419', '113363', '113393', '113395', '217034', '217036', '217042', '217045', '217053', '218434']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'gpolo', 'r.david.murray', 'alex_python_org', 'serhiy.storchaka', 'Joeboy']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue4913'
versions = ['Python 3.5']
```

</p></details>

**Comment by AA-Turner** [comment]
It's been ~8 years since the most recent request for a patch with no action, perhaps this issue can be closed as there seems to be no need for the feature? `audioop` as mentioned by Serhiy is now deprecated and will be removed (PEP-594).

A

**Comment by erlend-aasland** [comment]
> It's been ~8 years since the most recent request for a patch with no action, perhaps this issue can be closed as there seems to be no need for the feature? `audioop` as mentioned by Serhiy is now deprecated and will be removed ([PEP-594](https://peps.python.org/594)).
> 
> A

+1; closing.
