### ISSUE TITLE
Green-box doc glitch: winhelp version only

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#49638]
BPO | [5388](https://bugs.python.org/issue5388)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @ezio-melotti
Files | <li>[Py31doc.jpg](https://bugs.python.org/file14388/Py31doc.jpg "Uploaded as image/jpeg at 2009-06-29.16:56:57 by @terryjreedy"): Scrollbar in grammar box</li><li>[py31doc.png](https://bugs.python.org/file14412/py31doc.png "Uploaded as image/png at 2009-06-30.23:21:10 by @ezio-melotti"): No scrollbars in grammar box</li><li>[py31doc-vista.png](https://bugs.python.org/file14414/py31doc-vista.png "Uploaded as image/png at 2009-07-01.05:20:37 by @ezio-melotti"): Scrollbar on Vista</li><li>[py31doc-win2k3.png](https://bugs.python.org/file14416/py31doc-win2k3.png "Uploaded as image/png at 2009-07-01.05:57:32 by @ezio-melotti"): Scrollbar on Win2k3 Server</li><li>[py31doc-winxpsp2.png](https://bugs.python.org/file14417/py31doc-winxpsp2.png "Uploaded as image/png at 2009-07-01.05:59:28 by @ezio-melotti"): No scrollbars on WinXP SP2</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-02-27.19:45:52.680>
labels = ['docs']
title = 'Green-box doc glitch: winhelp version only'
updated_at = <Date 2013-10-11.18:59:58.192>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2013-10-11.18:59:58.192>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2009-02-27.19:45:52.680>
creator = 'terry.reedy'
dependencies = []
files = ['14388', '14412', '14414', '14416', '14417']
hgrepos = []
issue_num = 5388
keywords = []
message_count = 10.0
messages = ['82863', '89780', '89784', '89788', '89867', '89956', '89961', '89963', '199491', '199498']
nosy_count = 3.0
nosy_names = ['georg.brandl', 'terry.reedy', 'ezio.melotti']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue5388'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by CAM-Gerlach** [comment]
This appears to display correctly in all supported online HTML versions of the docs and the ancient Windows CHM help has been dropped as of 3.11, so can this be closed now?

**Comment by arhadthedev** [comment]
3.11 (the only bugfix branch) removed the Windows Help files so closing.
