### ISSUE TITLE
Pass MS CRT debug flags into subprocesses

### ISSUE THREAD

**Issue by 61337411-43fc-4a9c-b8d5-4060aede66d0** [python/cpython#49869]
BPO | [5619](https://bugs.python.org/issue5619)
--- | :---
Nosy | @loewis, @atsuoishimoto, @kristjanvalur, @tjguk, @asvetlov, @zware, @zooba
Files | <li>[_multiprocessing.patch.zip](https://bugs.python.org/file13526/_multiprocessing.patch.zip "Uploaded as application/x-zip-compressed at 2009-03-31.21:19:33 by @asvetlov"): patch for suppressing multiprocessing unittest run on Windows</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-03-31.04:13:01.768>
labels = ['type-bug', 'tests']
title = 'Pass MS CRT debug flags into subprocesses'
updated_at = <Date 2014-06-30.21:50:19.674>
user = 'https://github.com/loewis'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-30.21:50:19.674>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2009-03-31.04:13:01.768>
creator = 'loewis'
dependencies = []
files = ['13526']
hgrepos = []
issue_num = 5619
keywords = []
message_count = 17.0
messages = ['84750', '84913', '84940', '85024', '85027', '85029', '85031', '85036', '85050', '85053', '85058', '85059', '85061', '85188', '85200', '85201', '139709']
nosy_count = 10.0
nosy_names = ['loewis', 'ishimoto', 'kristjan.jonsson', 'ocean-city', 'tim.golden', 'jnoller', 'asvetlov', 'catalin.iacob', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue5619'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by vstinner** [comment]
Tests which are expected to crash now use ``with support.SuppressCrashReport(): ...``.

Moreover, since 2009, Python got new debug features like faulthandler, timeout in regrtest (implemented with faulthandler), etc.

I close the issue.
