### ISSUE TITLE
xml.dom.minidom does not escape CR, LF and TAB characters within attribute values

### ISSUE THREAD

**Issue by 60b82e4a-1f0a-4077-b0e7-151b2bf3097d** [python/cpython#50002]
BPO | [5752](https://bugs.python.org/issue5752)
--- | :---
Nosy | @amauryfa, @devdanzin, @dvarrazzo, @ezio-melotti, @wking, @mitar, @moriyoshi
Files | <li>[minidom_test.py](https://bugs.python.org/file13921/minidom_test.py "Uploaded as text/plain at 2009-05-08.09:53:34 by Tomalak"): A small test script that outlines the problem</li><li>[test_toxml.py](https://bugs.python.org/file13960/test_toxml.py "Uploaded as text/plain at 2009-05-11.21:27:13 by sechi_francesco"): New test script to demonstrate that the patch proposed works</li><li>[test_multiline_roundtrip.diff](https://bugs.python.org/file13966/test_multiline_roundtrip.diff "Uploaded as text/plain at 2009-05-12.03:29:28 by @devdanzin"): Tomalak's minidom_test.py as unittest,  patch for test_minidom</li><li>[minidom.patch](https://bugs.python.org/file13977/minidom.patch "Uploaded as text/plain at 2009-05-13.12:11:57 by Tomalak"): Proposed patch to minidom.py</li><li>[minidom.diff](https://bugs.python.org/file18184/minidom.diff "Uploaded as text/plain at 2010-07-24.17:21:21 by BreamoreBoy"): Old file before new file in patch.</li><li>[minidom.py](https://bugs.python.org/file18325/minidom.py "Uploaded as text/plain at 2010-08-02.16:47:21 by @wking"): monkey patch module applying minidom.diff</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-04-14.11:13:06.464>
labels = ['expert-XML', 'easy', 'type-bug']
title = 'xml.dom.minidom does not escape CR, LF and TAB characters within attribute values'
updated_at = <Date 2019-06-22.20:28:40.662>
user = 'https://bugs.python.org/Tomalak'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-22.20:28:40.662>
actor = 'mitar'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['XML']
creation = <Date 2009-04-14.11:13:06.464>
creator = 'Tomalak'
dependencies = []
files = ['13921', '13960', '13966', '13977', '18184', '18325']
hgrepos = []
issue_num = 5752
keywords = ['patch', 'easy']
message_count = 33.0
messages = ['85964', '87178', '87332', '87333', '87351', '87429', '87431', '87432', '87526', '87527', '87528', '87564', '87586', '87590', '87604', '87609', '87676', '87679', '87681', '90548', '90676', '110999', '111493', '111642', '112497', '112570', '119728', '142964', '185398', '185408', '185419', '185423', '185576']
nosy_count = 13.0
nosy_names = ['effbot', 'amaury.forgeotdarc', 'ajaksu2', 'piro', 'ezio.melotti', 'sayap', 'Tomalak', 'devon', 'labrat', 'mitar', 'moriyoshi', 'gauges', 'Jens.Grivolla']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue5752'
versions = ['Python 2.6', 'Python 3.1', 'Python 2.7', 'Python 3.2']
```

</p></details>

### Linked PRs
* gh-107947

**Comment by jbaker6953** [comment]
I had to make an updated version of this monkey patch for a project I was working on. I leave it here for anyone's reference. The old instance method overwrite was bombing out with `TypeError: function() argument 'code' must be code, not function` so I just changed it for my needs. It works well with my data set.

https://gist.github.com/jbaker6953/deb9a8e4eae1e622f467fc9b4edf11db

**Comment by hugovk** [comment]
Looks like this has been fixed by https://github.com/python/cpython/pull/107947.
