### ISSUE TITLE
pyexpat build failure on Solaris 10 for 2.6.1/2.6.2

### ISSUE THREAD

**Issue by ac853621-76da-4341-8113-1ad15689240b** [python/cpython#50548]
BPO | [6299](https://bugs.python.org/issue6299)
--- | :---
Nosy | @vstinner, @koobs
Files | <li>[python-issue6299.patch](https://bugs.python.org/file33902/python-issue6299.patch "Uploaded as text/plain at 2014-02-04.12:11:49 by @koobs")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-06-17.20:07:52.681>
labels = ['build']
title = 'pyexpat build failure on Solaris 10 for 2.6.1/2.6.2'
updated_at = <Date 2014-02-04.13:14:23.856>
user = 'https://bugs.python.org/enchanter'
```

bugs.python.org fields:
```python
activity = <Date 2014-02-04.13:14:23.856>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2009-06-17.20:07:52.681>
creator = 'enchanter'
dependencies = []
files = ['33902']
hgrepos = []
issue_num = 6299
keywords = ['patch']
message_count = 7.0
messages = ['89478', '97311', '189732', '210162', '210189', '210201', '210215']
nosy_count = 3.0
nosy_names = ['vstinner', 'enchanter', 'koobs']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue6299'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as Python versions 2.6 - 3.5 are not supported. If this issue still exists, create a new issue targeting supported python versions with a reproducer.
