### ISSUE TITLE
curses line wrap broken when mixing full- and half-width unicode characters

### ISSUE THREAD

**Issue by 18b861ca-5711-4b12-ae81-b12738b5ab97** [python/cpython#50982]
BPO | [6733](https://bugs.python.org/issue6733)
--- | :---
Nosy | @vstinner, @ezio-melotti

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-08-19.00:43:20.678>
labels = ['type-bug', 'library']
title = 'curses line wrap broken when mixing full- and half-width unicode characters'
updated_at = <Date 2015-04-14.13:10:25.061>
user = 'https://bugs.python.org/fugounashi'
```

bugs.python.org fields:
```python
activity = <Date 2015-04-14.13:10:25.061>
actor = 'cabiad'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2009-08-19.00:43:20.678>
creator = 'fugounashi'
dependencies = []
files = []
hgrepos = []
issue_num = 6733
keywords = []
message_count = 4.0
messages = ['91721', '91986', '92000', '240877']
nosy_count = 4.0
nosy_names = ['vstinner', 'ezio.melotti', 'fugounashi', 'cabiad']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue6733'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3']
```

</p></details>

**Comment by crazymerlyn** [comment]
Is this still an issue? I can't reproduce it at least on my system (Python 3.12 on Linux).
The only reference i can find to a fix online though is https://lists.gnu.org/archive/html/bug-ncurses/2005-03/msg00061.html which is older than this bug.

**Comment by vstinner** [comment]
On Python 3.12.5 on Linux (and ncurses-devel-6.4-12.20240127.fc40.x86_64), I get this output:

![Capture d’écran du 2024-08-26 17-01-03](https://github.com/user-attachments/assets/fade43e3-7c58-49d3-9611-cc10bf5a387f)

It seems correct to me. If someone can still reproduce the issue, please reopen the issue (with a screenshot).
