### ISSUE TITLE
[doc] codecs.open() + eol (windows)

### ISSUE THREAD

**Issue by 4dde3638-27b8-4e5d-a986-4b2ff9c99e87** [python/cpython#51511]
BPO | [7262](https://bugs.python.org/issue7262)
--- | :---
Nosy | @malemburg, @amauryfa, @iritkatriel, @kumaraditya303
PRs | <li>python/cpython#30231</li>
Files | <li>[eol-bug.py](https://bugs.python.org/file15256/eol-bug.py "Uploaded as text/plain at 2009-11-04.14:13:28 by shamilbi"): code to reproduce</li><li>[7262.patch](https://bugs.python.org/file34309/7262.patch "Uploaded as text/plain at 2014-03-09.06:23:24 by analyst"): Patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/malemburg'
closed_at = None
created_at = <Date 2009-11-04.14:13:29.252>
labels = ['easy', 'type-bug', '3.9', '3.10', '3.11', 'docs']
title = '[doc] codecs.open() + eol (windows)'
updated_at = <Date 2021-12-22.12:25:06.153>
user = 'https://bugs.python.org/shamilbi'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-22.12:25:06.153>
actor = 'kumaraditya'
assignee = 'lemburg'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2009-11-04.14:13:29.252>
creator = 'shamilbi'
dependencies = []
files = ['15256', '34309']
hgrepos = []
issue_num = 7262
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['94888', '94895', '94898', '189621', '212957', '408163']
nosy_count = 6.0
nosy_names = ['lemburg', 'amaury.forgeotdarc', 'shamilbi', 'analyst', 'iritkatriel', 'kumaraditya']
pr_nums = ['30231']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue7262'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by hauntsaninja** [comment]
Thanks, looks like this was completed
