### ISSUE TITLE
shlex refactoring

### ISSUE THREAD

**Issue by c4cbafac-9b68-4e7f-b763-bf55ad41f7c4** [python/cpython#51843]
BPO | [7594](https://bugs.python.org/issue7594)
--- | :---
Nosy | @mhammond, @ezio-melotti, @merwok
Files | <li>[shlex-py2.6.4-20091229.patch](https://bugs.python.org/file15692/shlex-py2.6.4-20091229.patch "Uploaded as text/plain at 2009-12-29.08:07:35 by ferringb"): shlex-py2.6.4 refactoring</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2009-12-29.08:07:40.084>
labels = ['library', 'performance']
title = 'shlex refactoring'
updated_at = <Date 2011-06-14.16:03:49.376>
user = 'https://bugs.python.org/ferringb'
```

bugs.python.org fields:
```python
activity = <Date 2011-06-14.16:03:49.376>
actor = 'eric.araujo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2009-12-29.08:07:40.084>
creator = 'ferringb'
dependencies = []
files = ['15692']
hgrepos = []
issue_num = 7594
keywords = ['patch', 'needs review']
message_count = 3.0
messages = ['96987', '96988', '105118']
nosy_count = 4.0
nosy_names = ['mhammond', 'ferringb', 'ezio.melotti', 'eric.araujo']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue7594'
versions = ['Python 3.3']
```

</p></details>

**Comment by iritkatriel** [comment]
The proposed refactor had some issue with it (according to the comments) and seems to have been abandoned for over a decade. I will close the issue unless someone sees a point in leaving it open.
