### ISSUE TITLE
[Windows] cgi handling of POSTed files is broken in Windows

### ISSUE THREAD

**Issue by 2983f4cd-0e5d-4389-b3ca-a3aa30e6310b** [python/cpython#52324]
BPO | [8077](https://bugs.python.org/issue8077)
--- | :---
Nosy | @gvanrossum, @birkenfeld, @pfmoore, @orsenthil, @tjguk, @MLModel, @bitdancer, @PierreQuentel, @zware, @zooba
PRs | <li>python/cpython#25652</li>
Files | <li>[cgi-post-broken.zip](https://bugs.python.org/file16465/cgi-post-broken.zip "Uploaded as application/zip at 2010-03-06.01:43:37 by @MLModel"): zipped demo of problem</li><li>[http-server.patch](https://bugs.python.org/file25440/http-server.patch "Uploaded as text/plain at 2012-05-03.07:54:26 by @PierreQuentel"): Patch for http.server.CGIHTTPRequestHandler</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = None
created_at = <Date 2010-03-06.01:43:39.134>
labels = ['type-bug', '3.10', 'OS-windows']
title = '[Windows] cgi handling of POSTed files is broken in Windows'
updated_at = <Date 2021-04-27.14:24:08.871>
user = 'https://github.com/MLModel'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-27.14:24:08.871>
actor = 'vstinner'
assignee = 'orsenthil'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2010-03-06.01:43:39.134>
creator = 'MLModel'
dependencies = []
files = ['16465', '25440']
hgrepos = []
issue_num = 8077
keywords = ['patch']
message_count = 5.0
messages = ['100509', '101211', '107405', '107960', '159838']
nosy_count = 11.0
nosy_names = ['gvanrossum', 'georg.brandl', 'paul.moore', 'ggenellina', 'orsenthil', 'tim.golden', 'MLModel', 'r.david.murray', 'quentel', 'zach.ware', 'steve.dower']
pr_nums = ['25652']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8077'
versions = ['Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/ ) hence closing.
