### ISSUE TITLE
urllib.unquote decodes percent-escapes with Latin-1

### ISSUE THREAD

**Issue by 25a81009-9caa-4147-a13b-b4843223656b** [python/cpython#52383]
BPO | [8136](https://bugs.python.org/issue8136)
--- | :---
Nosy | @orsenthil, @ezio-melotti, @merwok, @karlcow, @serhiy-storchaka
Files | <li>[urllib-unquote-fix.patch](https://bugs.python.org/file16541/urllib-unquote-fix.patch "Uploaded as text/plain at 2010-03-14.08:48:19 by mgiuca"): Patch for urllib.unquote</li><li>[urllib-unquote-explain.patch](https://bugs.python.org/file16545/urllib-unquote-explain.patch "Uploaded as text/plain at 2010-03-14.12:25:23 by mgiuca"): Patch just for test cases and documentation</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-03-14.08:48:21.713>
labels = ['type-bug', 'library']
title = 'urllib.unquote decodes percent-escapes with Latin-1'
updated_at = <Date 2017-06-05.05:53:36.921>
user = 'https://bugs.python.org/mgiuca'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-05.05:53:36.921>
actor = 'karlcow'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-03-14.08:48:21.713>
creator = 'mgiuca'
dependencies = []
files = ['16541', '16545']
hgrepos = []
issue_num = 8136
keywords = ['patch']
message_count = 5.0
messages = ['101045', '101046', '101054', '101077', '295168']
nosy_count = 6.0
nosy_names = ['orsenthil', 'ezio.melotti', 'eric.araujo', 'mgiuca', 'karlcow', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8136'
versions = ['Python 2.7']
```

</p></details>

**Comment by b5530672-af90-4755-8dcc-6d0806f6cc01** [comment]
bpo-8143 was fixed.

```pycon
Python 2.7.10 (default, Feb  7 2017, 00:08:15) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib
>>> urllib.unquote(u"%CE%A3")
u'\xce\xa3'
```


What should become of this one?

**Comment by serhiy-storchaka** [comment]
The problem has already been fixed. You can specify encoding as argument (UTF-8 is used by default).

>>> from urllib.parse import *
>>> unquote("%CE%A3")
'Σ'
>>> unquote("%CE%A3", encoding="latin1")
'Î£'
