### ISSUE TITLE
time.strftime() and Unicode characters on Windows

### ISSUE THREAD

**Issue by 90d7de53-1470-4a68-827a-9ad9a88e8dfe** [python/cpython#52551]
BPO | [8304](https://bugs.python.org/issue8304)
--- | :---
Nosy | @terryjreedy, @pfmoore, @abalkin, @vstinner, @ericvsmith, @tjguk, @ezio-melotti, @shimizukawa, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-04-03.15:08:42.673>
labels = ['3.8', '3.9', 'extension-modules', 'expert-unicode', 'type-bug', '3.10', 'library', 'OS-windows']
title = 'time.strftime() and Unicode characters on Windows'
updated_at = <Date 2021-03-08.19:17:29.084>
user = 'https://bugs.python.org/AndiDogold'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-08.19:17:29.084>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Library (Lib)', 'Unicode', 'Windows']
creation = <Date 2010-04-03.15:08:42.673>
creator = 'AndiDog_old'
dependencies = []
files = []
hgrepos = []
issue_num = 8304
keywords = []
message_count = 16.0
messages = ['102269', '102298', '102310', '102332', '102335', '159341', '222667', '226114', '251554', '251558', '251560', '255043', '255133', '388241', '388277', '388286']
nosy_count = 12.0
nosy_names = ['terry.reedy', 'paul.moore', 'belopolsky', 'vstinner', 'eric.smith', 'tim.golden', 'ezio.melotti', 'AndiDog_old', 'shimizukawa', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8304'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-125193
* gh-125657
* gh-125658
* gh-125661

**Comment by serhiy-storchaka** [comment]
Yet a couple bugs.

On platforms without `wcsftime()`:
```pycon
>>> print(ascii(time.strftime('\udcf0\udc9f\udc90\udc8d')))
'\U0001f40d'
```
The result depends on the locale encoding. The above was for UTF-8.

I expect the similar result for `time.strftime('\ud83d\udc0d')` on platforms with `wcsftime()` and 16-bit wchar_t.

**Comment by serhiy-storchaka** [comment]
Python's `time.strftime()` now passes only ASCII strings to C's `strftime()`, so there are no encoding errors. But the result of `strftime()` still can contain non-ASCII data and it need to be decoded. I think that switching to `wstrftime()` would make decoding less prone to locale misconfiguration errors.
