### ISSUE TITLE
zipimporter find_module fullname mis-documented

### ISSUE THREAD

**Issue by 02aa5882-8266-4192-aa79-4f5630ea2cae** [python/cpython#52647]
BPO | [8400](https://bugs.python.org/issue8400)
--- | :---
Nosy | @gpshead, @kmtracey, @cool-RR, @ericsnowcurrently, @serhiy-storchaka, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-04-14.15:20:40.742>
labels = ['3.8', 'type-bug', '3.7']
title = 'zipimporter find_module fullname mis-documented'
updated_at = <Date 2020-01-24.23:26:31.133>
user = 'https://github.com/kmtracey'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-24.23:26:31.133>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2010-04-14.15:20:40.742>
creator = 'kmtracey'
dependencies = []
files = []
hgrepos = []
issue_num = 8400
keywords = []
message_count = 8.0
messages = ['103132', '109467', '134584', '175527', '175565', '175566', '342587', '342665']
nosy_count = 9.0
nosy_names = ['gregory.p.smith', 'kmtracey', 'rfk', 'cool-RR', 'tjd.rodgers', 'eric.snow', 'serhiy.storchaka', 'superluser', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8400'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by hugovk** [comment]
Closing this as `find_module` is deprecated since 3.10 and slated for 3.12 removal:

* https://docs.python.org/3/library/zipimport.html#zipimport.zipimporter.find_module
* https://docs.python.org/3/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/issues/70319
* https://github.com/python/cpython/pull/23469
