### ISSUE TITLE
cgitb sends a bogus HTTP header if the app crashes before finishing headers

### ISSUE THREAD

**Issue by cfc9f3e0-e33f-4ecd-9ddd-4123842d6c1e** [python/cpython#52950]
BPO | [8704](https://bugs.python.org/issue8704)
--- | :---
Nosy | @orsenthil, @cthart

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-05-13.14:12:50.822>
labels = ['easy', '3.8', 'type-bug', 'library']
title = 'cgitb sends a bogus HTTP header if the app crashes before finishing headers'
updated_at = <Date 2022-03-15.14:23:55.676>
user = 'https://bugs.python.org/stutzbach'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-15.14:23:55.676>
actor = 'cthart'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-05-13.14:12:50.822>
creator = 'stutzbach'
dependencies = []
files = []
hgrepos = []
issue_num = 8704
keywords = ['easy']
message_count = 9.0
messages = ['105633', '105690', '105705', '193189', '294027', '364186', '376811', '389031', '415246']
nosy_count = 10.0
nosy_names = ['orsenthil', 'stutzbach', 'igs', 'meatballhat', 'ysj.ray', 'p0lar_bear', '\xd0\x90\xd1\x80\xd1\x82\xd1\x83\xd1\x80 \xd0\x9a\xd0\xbb\xd0\xb5\xd1\x81\xd1\x83\xd0\xbd', 'coyot', 'Ryan Tu', 'cthart']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8704'
versions = ['Python 3.8']
```

</p></details>

**Comment by ghost** [comment]
Apache started strict check of headers ch
aracters to be valid recently. That causes it fail on "\<--: spam".

```
[Sat May 20 13:09:23.056673 2017] [http:error] [pid 26379] [client 12.34.567.41:60988] AH02429: Response header name '<!--' contains invalid characters, aborting request, referer: http://example.com/
```

http://apache-http-server.18135.x6.nabble.com/Bug-60863-New-Apache-proxy-2-4-25-can-disable-header-check-Set-Cookie-td5036120.html

The workaround is to put:
HttpProtocolOptions Unsafe
line into your apache .conf

**Comment by hugovk** [comment]
Yep, deprecated in 3.11 and removed in 3.13: see [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

@cthart Some good news: a fork has been made by @jackrosenthal:

* https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508/23?u=hugovk
* https://github.com/jackrosenthal/python-cgi

> Contributions are accepted, but should be focused on bug fixes instead of new features or major refactoring.

Because there's [no maintainer for this module in CPython](https://peps.python.org/pep-0594/#deprecated-modules), perhaps it would be better to close this issue and instead put energy into the fork?

**Comment by AlexWaygood** [comment]
> Because there's no maintainer for this module in CPython, perhaps it would be better to close this issue and instead put energy into the fork?

I think so. I'm going to close this issue for now, but I'm happy to reopen if somebody wants to persuasively argue for why this issue should be fixed in CPython despite the deprecation.

Cc. @cthart

**Comment by cthart** [comment]
Good call. A fork available via GitHub / PyPi is a perfect solution for this library. My interest is only in the `cgitb` part, which I believe could be modernised to use CSS for displaying Python stack traces in a marked up format.
