### ISSUE TITLE
accept keyword arguments on most base type methods and builtins

### ISSUE THREAD

**Issue by gpshead** [python/cpython#52952]
BPO | [8706](https://bugs.python.org/issue8706)
--- | :---
Nosy | @rhettinger, @gpshead, @ezio-melotti, @merwok, @briancurtin, @methane, @ericsnowcurrently, @berkerpeksag, @vadmium, @serhiy-storchaka, @nchammas
Files | <li>[8706.patch](https://bugs.python.org/file24644/8706.patch "Uploaded as text/plain at 2012-02-26.13:00:35 by gruszczy")</li><li>[8706_2.patch](https://bugs.python.org/file24650/8706_2.patch "Uploaded as text/plain at 2012-02-26.19:29:29 by gruszczy")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-05-13.19:10:53.581>
labels = ['extension-modules', 'interpreter-core', 'type-feature', '3.7']
title = 'accept keyword arguments on most base type methods and builtins'
updated_at = <Date 2017-01-21.07:13:37.955>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2017-01-21.07:13:37.955>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Interpreter Core']
creation = <Date 2010-05-13.19:10:53.581>
creator = 'gregory.p.smith'
dependencies = []
files = ['24644', '24650']
hgrepos = []
issue_num = 8706
keywords = ['patch']
message_count = 25.0
messages = ['105652', '154340', '154379', '154491', '154493', '154505', '154506', '154507', '154509', '154510', '154522', '154524', '154528', '154534', '154725', '154743', '154745', '154748', '154749', '223570', '241589', '241606', '241610', '285924', '285942']
nosy_count = 16.0
nosy_names = ['rhettinger', 'gregory.p.smith', 'ezio.melotti', 'eric.araujo', 'Arfrever', 'brian.curtin', 'gruszczy', 'methane', 'meatballhat', 'eric.snow', 'Ramchandra Apte', 'berker.peksag', 'martin.panter', 'serhiy.storchaka', 'Julien.Palard', 'nchammas']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue8706'
versions = ['Python 3.7']
```

</p></details>

**Comment by arhadthedev** [comment]
Is this idea still worth implementation? It seems that the only methods touched by the patches and still unported to Argument Clinic are thin wrappers around `_Py_bytes_*` and alike.

**Comment by gpshead** [comment]
I'll just close it. In the 13 years since filing the idea argument clinic was invented and a lot has moved to that. points made above and in other discussions about the keyword argument remain true, and in 3.8 we got https://peps.python.org/pep-0570/ for positional only arguments from the Python side via the `/` token. So a request to do it everywhere makes even less sense.

Performance wise, I expect the existing faster cpython work may ultimately change the shape of what does and doesn't perform well. It could, for example, specialize around differences in argument passing styles in hot paths if that winds up being worthwhile.
