### ISSUE TITLE
Windows registry path not ignored with -E option

### ISSUE THREAD

**Issue by 526682a6-78fb-44af-b846-03e1b28ca823** [python/cpython#53147]
BPO | [8901](https://bugs.python.org/issue8901)
--- | :---
Nosy | @ncoghlan, @pitrou, @benjaminp, @merwok, @ericsnowcurrently, @zooba, @ZackerySpytz
PRs | <li>python/cpython#18169</li>
Files | <li>[IgnoreWindowsRegistry_27.patch](https://bugs.python.org/file17558/IgnoreWindowsRegistry_27.patch "Uploaded as text/plain at 2010-06-05.02:39:22 by flashk"): Patch for 2.7</li><li>[IgnoreWindowsRegistry_32.patch](https://bugs.python.org/file17559/IgnoreWindowsRegistry_32.patch "Uploaded as text/plain at 2010-06-05.02:39:45 by flashk"): Patch for 3.2</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-06-05.02:39:23.706>
labels = ['interpreter-core', 'type-bug', '3.9']
title = 'Windows registry path not ignored with -E option'
updated_at = <Date 2020-03-30.16:06:33.221>
user = 'https://bugs.python.org/flashk'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-30.16:06:33.221>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2010-06-05.02:39:23.706>
creator = 'flashk'
dependencies = []
files = ['17558', '17559']
hgrepos = []
issue_num = 8901
keywords = ['patch', 'needs review']
message_count = 8.0
messages = ['107121', '107244', '108468', '216183', '216189', '365212', '365328', '365329']
nosy_count = 9.0
nosy_names = ['jpe', 'ncoghlan', 'pitrou', 'benjamin.peterson', 'eric.araujo', 'flashk', 'eric.snow', 'steve.dower', 'ZackerySpytz']
pr_nums = ['18169']
priority = 'normal'
resolution = 'fixed'
stage = 'commit review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue8901'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this can be closed.
