### ISSUE TITLE
test_capi.test_no_FatalError_infinite_loop crash on Windows

### ISSUE THREAD

**Issue by briancurtin** [python/cpython#53362]
BPO | [9116](https://bugs.python.org/issue9116)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @vsajip, @pitrou, @vstinner, @tjguk, @ezio-melotti, @briancurtin, @zware, @zooba
Dependencies | <li>bpo-5619: Pass MS CRT debug flags into subprocesses</li>
Files | <li>[py3k_fix_test_capi_crash.patch](https://bugs.python.org/file18809/py3k_fix_test_capi_crash.patch "Uploaded as text/plain at 2010-09-09.07:55:52 by ocean-city")</li><li>[test_capi.diff](https://bugs.python.org/file25457/test_capi.diff "Uploaded as text/plain at 2012-05-05.09:35:43 by @vsajip"): Slight change to test assertion needed to pass on Windows</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-06-29.15:58:26.076>
labels = ['interpreter-core', 'tests', 'OS-windows', 'type-crash']
title = 'test_capi.test_no_FatalError_infinite_loop crash on Windows'
updated_at = <Date 2014-10-14.17:11:48.119>
user = 'https://github.com/briancurtin'
```

bugs.python.org fields:
```python
activity = <Date 2014-10-14.17:11:48.119>
actor = 'skrah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Tests', 'Windows']
creation = <Date 2010-06-29.15:58:26.076>
creator = 'brian.curtin'
dependencies = ['5619']
files = ['18809', '25457']
hgrepos = []
issue_num = 9116
keywords = ['patch']
message_count = 22.0
messages = ['108914', '108915', '110902', '112128', '112132', '112152', '113155', '115246', '115249', '115635', '115921', '115931', '116008', '121187', '121258', '149413', '150922', '159982', '160031', '160072', '182471', '222202']
nosy_count = 13.0
nosy_names = ['georg.brandl', 'terry.reedy', 'vinay.sajip', 'pitrou', 'vstinner', 'ocean-city', 'tim.golden', 'ezio.melotti', 'brian.curtin', 'catalin.iacob', 'python-dev', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue9116'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as it is "fixed enough", feel free to reopen if required.
