### ISSUE TITLE
Add a a way to determine float format

### ISSUE THREAD

**Issue by benjaminp** [python/cpython#53438]
BPO | [9192](https://bugs.python.org/issue9192)
--- | :---
Nosy | @mdickinson, @benjaminp, @ezio-melotti

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-07-07.18:25:58.128>
labels = ['interpreter-core', 'type-feature']
title = 'Add a a way to determine float format'
updated_at = <Date 2012-10-26.17:55:45.327>
user = 'https://github.com/benjaminp'
```

bugs.python.org fields:
```python
activity = <Date 2012-10-26.17:55:45.327>
actor = 'mark.dickinson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2010-07-07.18:25:58.128>
creator = 'benjamin.peterson'
dependencies = []
files = []
hgrepos = []
issue_num = 9192
keywords = []
message_count = 2.0
messages = ['109488', '173867']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'benjamin.peterson', 'ezio.melotti', 'hieu.nguyen']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue9192'
versions = ['Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
This is over a decade old and the proposal doesn't seem to be clear. I will close it soon unless someone objects.

**Comment by mdickinson** [comment]
@iritkatriel Closing sounds fine to me. The statement that "the only format that Python realistically supports these days is the IEEE 754 binary64 format" is even more true now than it was when I wrote it 10 years ago, and moreover CPython now requires IEEE 754 format.

For detecting endianness we have `sys.byteorder`. That assumes that it's safe to assume a single byte order for integers and floats, but while not guaranteed by the relevant standards, it seems to be a safe assumption in practice.
