### ISSUE TITLE
FIPS support for hashlib

### ISSUE THREAD

**Issue by davidmalcolm** [python/cpython#53462]
BPO | [9216](https://bugs.python.org/issue9216)
--- | :---
Nosy | @gpshead, @pitrou, @vstinner, @tiran, @rbtcollins, @dhellmann, @davidmalcolm, @dholth, @sigmavirus24, @stratakis, @yrobla, @hroncok, @csabella, @miss-islington
PRs | <li>python/cpython#5548</li><li>python/cpython#16044</li><li>python/cpython#19520</li><li>python/cpython#19524</li><li>python/cpython#19703</li><li>python/cpython#20258</li><li>python/cpython#20320</li>
Files | <li>[py3k-hashlib-fips-issue9216.patch](https://bugs.python.org/file17970/py3k-hashlib-fips-issue9216.patch "Uploaded as text/plain at 2010-07-12.18:48:08 by @davidmalcolm"): Patch against py3k branch</li><li>[0001-Rework-_hashlib-caching-moving-per-hash-cached-data-.patch](https://bugs.python.org/file23172/0001-Rework-_hashlib-caching-moving-per-hash-cached-data-.patch "Uploaded as text/plain at 2011-09-16.19:45:45 by @davidmalcolm")</li><li>[0002-Add-error-handling-to-initialization-of-_hashlib.patch](https://bugs.python.org/file23173/0002-Add-error-handling-to-initialization-of-_hashlib.patch "Uploaded as text/plain at 2011-09-16.19:46:23 by @davidmalcolm")</li><li>[0003-Add-optional-usedforsecurity-argument-in-various-pla.patch](https://bugs.python.org/file23174/0003-Add-optional-usedforsecurity-argument-in-various-pla.patch "Uploaded as text/plain at 2011-09-16.19:46:38 by @davidmalcolm")</li><li>[0004-_hashlib-Add-selftest-for-FIPS-mode-and-usedforsecur.patch](https://bugs.python.org/file23175/0004-_hashlib-Add-selftest-for-FIPS-mode-and-usedforsecur.patch "Uploaded as text/plain at 2011-09-16.19:46:48 by @davidmalcolm")</li><li>[virtualenv_distribute](https://bugs.python.org/file26205/virtualenv_distribute "Uploaded as text/plain at 2012-06-29.00:39:35 by lukecarrier")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-07-10.00:22:13.168>
labels = ['type-feature', 'library', '3.9', '3.10']
title = 'FIPS support for hashlib'
updated_at = <Date 2020-05-22.18:22:39.610>
user = 'https://github.com/davidmalcolm'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-22.18:22:39.610>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-07-10.00:22:13.168>
creator = 'dmalcolm'
dependencies = []
files = ['17970', '23172', '23173', '23174', '23175', '26205']
hgrepos = []
issue_num = 9216
keywords = ['patch']
message_count = 47.0
messages = ['109808', '109891', '110124', '144152', '144153', '144154', '155688', '155741', '155846', '164308', '164328', '166575', '166576', '172302', '191130', '285593', '285640', '285643', '285676', '285677', '285678', '285679', '285681', '285683', '285684', '285706', '285895', '285897', '298454', '298484', '348186', '348747', '352231', '352253', '360716', '366436', '367189', '367193', '367194', '367195', '367197', '367668', '367960', '368065', '369430', '369622', '369625']
nosy_count = 19.0
nosy_names = ['gregory.p.smith', 'pitrou', 'vstinner', 'christian.heimes', 'rbcollins', 'rpetrov', 'doughellmann', 'dmalcolm', 'dholth', 'jpokorny', 'bkabrda', 'lukecarrier', 'icordasc', 'cstratak', 'yolanda.robla', 'hroncok', 'cheryl.sabella', 'Andrew DiPrinzio', 'miss-islington']
pr_nums = ['5548', '16044', '19520', '19524', '19703', '20258', '20320']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue9216'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by 9e52e825-79ef-486a-b7ef-17c53dabda51** [comment]
I have been able to use this flag on RHEL and Centos. Is it possible that this has been completed?

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
@Andrew

This has already been implemented downstream for RHEL and centos.

**Comment by arhadthedev** [comment]
@gpshead Is the issue relevant after transition to HACL\*?

**Comment by gpshead** [comment]
OpenSSL is still the default.  regardless, this issue was completed ages ago as far as I can tell.

Let commercial-distro-motivated folks open new _specific_ issues for things they want to see done for anything that remains feature wise here.
