### ISSUE TITLE
plistlib should create non-naïve datetime objects

### ISSUE THREAD

**Issue by f3a57b6c-0e9f-4c0b-9aae-06de94080770** [python/cpython#53502]
BPO | [9256](https://bugs.python.org/issue9256)
--- | :---
Nosy | @ronaldoussoren, @abalkin, @ned-deily, @bitdancer, @hynek
Files | <li>[plistdt.py](https://bugs.python.org/file17993/plistdt.py "Uploaded as text/plain at 2010-07-14.01:34:01 by wiml"): a simple test case</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ronaldoussoren'
closed_at = None
created_at = <Date 2010-07-14.01:34:02.327>
labels = ['OS-mac', 'type-bug', 'library']
title = 'plistlib should create non-na\xc3\xafve datetime objects'
updated_at = <Date 2014-06-30.00:02:22.179>
user = 'https://bugs.python.org/wiml'
```

bugs.python.org fields:
```python
activity = <Date 2014-06-30.00:02:22.179>
actor = 'belopolsky'
assignee = 'ronaldoussoren'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2010-07-14.01:34:02.327>
creator = 'wiml'
dependencies = []
files = ['17993']
hgrepos = []
issue_num = 9256
keywords = []
message_count = 3.0
messages = ['110249', '110250', '162471']
nosy_count = 6.0
nosy_names = ['ronaldoussoren', 'belopolsky', 'ned.deily', 'r.david.murray', 'wiml', 'hynek']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue9256'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-113363
* gh-113627
* gh-113645

**Comment by ronaldoussoren** [comment]
I've added a feature label because changing this is a feature change and likely can only be done by adding a new option to plist parsers.

**Comment by ronaldoussoren** [comment]
O my, the PR causes builtbot failures (looks like 32 bit time_t)

**Comment by hugovk** [comment]
Triage: can this be re-closed following the recent fix PRs?
