### ISSUE TITLE
code.InteractiveInterpreter fails to change locals when invoked in a function

### ISSUE THREAD

**Issue by 058e80dc-802d-4eef-a928-8c60c6e60d9c** [python/cpython#53520]
BPO | [9274](https://bugs.python.org/issue9274)
--- | :---
Nosy | @bitdancer
Files | <li>[bug87405a.py](https://bugs.python.org/file18029/bug87405a.py "Uploaded as text/plain at 2010-07-16.17:21:03 by ericp"): Standalone Python code that shows how local vars aren't modified in a function</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-07-16.17:21:04.578>
labels = ['type-bug', 'docs']
title = 'code.InteractiveInterpreter fails to change locals when invoked in a function'
updated_at = <Date 2019-04-26.20:43:43.157>
user = 'https://bugs.python.org/ericp'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.20:43:43.157>
actor = 'BreamoreBoy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2010-07-16.17:21:04.578>
creator = 'ericp'
dependencies = []
files = ['18029']
hgrepos = []
issue_num = 9274
keywords = []
message_count = 8.0
messages = ['110464', '110468', '110471', '110523', '110524', '110525', '110527', '228118']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'ericp', 'docs@python']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue9274'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by ncoghlan** [comment]
With the implementation of PEP 667 in 3.13, `sys.getframe().f_locals` now supports reliable modification of local variables, even in optimized frames: https://docs.python.org/3.13/whatsnew/3.13.html#defined-mutation-semantics-for-locals
