### ISSUE TITLE
Don't use east/west of UTC in date/time documentation

### ISSUE THREAD

**Issue by abalkin** [python/cpython#53551]
BPO | [9305](https://bugs.python.org/issue9305)
--- | :---
Nosy | @tim-one, @freddrake, @abalkin, @vadmium, @crwilcox, @pganssle, @csabella, @ravipudi, @slateny
PRs | <li>python/cpython#31697</li>
Dependencies | <li>bpo-7229: Manual entry for time.daylight can be misleading</li><li>bpo-8810: TZ offset description is unclear in docs</li>
Files | <li>[datetime_doc_remove_east_west.diff](https://bugs.python.org/file19694/datetime_doc_remove_east_west.diff "Uploaded as text/plain at 2010-11-20.19:11:14 by henriquebastos")</li><li>[datetime_doc_remove_east_west_2.diff](https://bugs.python.org/file19709/datetime_doc_remove_east_west_2.diff "Uploaded as text/plain at 2010-11-20.20:46:25 by rbp")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-07-19.16:21:43.892>
labels = ['easy', 'type-feature', 'docs']
title = "Don't use east/west of UTC in date/time documentation"
updated_at = <Date 2022-03-05.16:55:35.124>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-05.16:55:35.124>
actor = 'slateny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2010-07-19.16:21:43.892>
creator = 'belopolsky'
dependencies = ['7229', '8810']
files = ['19694', '19709']
hgrepos = []
issue_num = 9305
keywords = ['patch', 'easy']
message_count = 24.0
messages = ['110774', '110905', '110910', '110911', '110912', '110916', '110917', '110918', '110919', '110926', '121726', '121727', '121728', '121745', '121751', '121765', '126020', '185565', '221916', '257935', '304934', '332985', '333045', '361715']
nosy_count = 15.0
nosy_names = ['tim.peters', 'fdrake', 'belopolsky', 'techtonik', 'rbp', 'docs@python', 'henriquebastos', 'Rodolpho.Eckhardt', 'martin.panter', 'crwilcox', 'p-ganssle', 'cheryl.sabella', 'Ajay Mahato', 'ravipudi', 'slateny']
pr_nums = ['31697']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue9305'
versions = ['Python 3.2']
```

</p></details>

**Comment by csabella** [comment]
Would one of the original authors of the patches like to create a GitHub pull request for this issue?

**Comment by slateny** [comment]
Closed per [comment](https://github.com/python/cpython/pull/31697#issuecomment-1122642714)
