### ISSUE TITLE
argparse: Problem with defaults for variable nargs when using choices

### ISSUE THREAD

**Issue by 66cd4d65-ca98-40f6-88cd-7335b752bca6** [python/cpython#53834]
BPO | [9625](https://bugs.python.org/issue9625)
--- | :---
Nosy | @rhettinger, @macfreek, @ericvsmith, @merwok, @cedk, @berkerpeksag, @lanzz, @jameshcorbett, @zumoshi
Files | <li>[issue9625.diff](https://bugs.python.org/file26471/issue9625.diff "Uploaded as text/plain at 2012-07-21.22:19:22 by bethard")</li><li>[issue9625.patch](https://bugs.python.org/file27858/issue9625.patch "Uploaded as text/plain at 2012-11-03.16:00:08 by @cedk")</li><li>[issue9625_1.patch](https://bugs.python.org/file30709/issue9625_1.patch "Uploaded as text/plain at 2013-06-27.06:33:20 by paul.j3")</li><li>[issue9625_2.patch](https://bugs.python.org/file30762/issue9625_2.patch "Uploaded as text/plain at 2013-07-03.21:36:34 by paul.j3")</li><li>[notes.txt](https://bugs.python.org/file35128/notes.txt "Uploaded as text/plain at 2014-05-02.02:04:05 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-08-17.09:19:03.116>
labels = ['type-bug', 'library', '3.9']
title = 'argparse: Problem with defaults for variable nargs when using choices'
updated_at = <Date 2020-12-21.23:36:46.142>
user = 'https://bugs.python.org/thesociable'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-21.23:36:46.142>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-08-17.09:19:03.116>
creator = 'thesociable'
dependencies = []
files = ['26471', '27858', '30709', '30762', '35128']
hgrepos = []
issue_num = 9625
keywords = ['patch']
message_count = 17.0
messages = ['114108', '151780', '151807', '151857', '166086', '174642', '191224', '191932', '192258', '192716', '217677', '285865', '347742', '356859', '357064', '374581', '374592']
nosy_count = 16.0
nosy_names = ['rhettinger', 'bethard', 'macfreek', 'eric.smith', 'eric.araujo', 'ced', 'Sworddragon', 'thesociable', 'regis', 'berker.peksag', 'paul.j3', 'sebix', 'lanzz', 'Jan Huta\xc5\x99', 'jameshcorbett', 'zumoshi']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue9625'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-124495

**Comment by NichtJens** [comment]
> Another workaround for who might ever need it. The benefit of this solution comparing to a custom type is that argparse will generate the help string properly with the choices, and this solution does workaround the place when the bug happens:
> 
> ```python
>     class Choices(tuple):
>     ...
> ```

Thanks @JooEiras, this is a very nice workaround, but I think it can be simplified:

```python
class Choices(tuple):

    def __init__(self, _iterable=None, default=None):
        # _iterable is already handled by tuple.__new__
        self.default = default or []

    def __contains__(self, item):
        return super().__contains__(item) or item == self.default
```

This has the added benefit of being able to set `default` when creating the object, and working when omitting `default=choices.default` from `parser.add_argument(...)`.

Any concerns about this change?

**Comment by serhiy-storchaka** [comment]
I think that we should allow arbitrary `default` and should omit checks if the default value is used. It can fail only if the programmer provides `default` that does not pass the check. The check does not check input, it restricts the programmer. In this case it always fail because `default` and `choices` are always incompatible if `nargs='*'`.

This also allows to distinguish the default value from the specified value if `nargs='?'`.
