### ISSUE TITLE
pdb go stack up/down

### ISSUE THREAD

**Issue by fc79d49b-3dee-4b39-bd81-7f67e89e93f9** [python/cpython#53842]
BPO | [9633](https://bugs.python.org/issue9633)
--- | :---
Nosy | @birkenfeld, @ncoghlan, @blueyed, @merwok, @asvetlov, @meadori, @xdegaye, @iritkatriel
PRs | <li>python/cpython#11041</li>
Files | <li>[issue9633.patch](https://bugs.python.org/file18706/issue9633.patch "Uploaded as text/plain at 2010-09-02.03:10:31 by @meadori"): py3k patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-08-18.12:17:16.520>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'pdb go stack up/down'
updated_at = <Date 2020-10-22.22:46:16.422>
user = 'https://bugs.python.org/MarkusPrller'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-22.22:46:16.422>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-08-18.12:17:16.520>
creator = 'Markus.Pr\xc3\xb6ller'
dependencies = []
files = ['18706']
hgrepos = []
issue_num = 9633
keywords = ['patch']
message_count = 7.0
messages = ['114213', '114218', '114231', '115358', '176270', '304391', '379375']
nosy_count = 9.0
nosy_names = ['georg.brandl', 'ncoghlan', 'blueyed', 'eric.araujo', 'asvetlov', 'meador.inge', 'xdegaye', 'Markus.Pr\xc3\xb6ller', 'iritkatriel']
pr_nums = ['11041']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue9633'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ncoghlan** [comment]
Note that we're currently looking into this as something that could be potentially addressed by PEP-558 and any related changes to the way that function locals interact with trace hooks: https://bugs.python.org/issue30744#msg304388

**Comment by gaogaotiantian** [comment]
This is no longer the case after PEP 667.
