### ISSUE TITLE
add an optional "default" argument to tokenize.detect_encoding

### ISSUE THREAD

**Issue by eda57068-96ad-4b33-8431-9c528f59a6a6** [python/cpython#53980]
BPO | [9771](https://bugs.python.org/issue9771)
--- | :---
Nosy | @vstinner, @benjaminp, @merwok, @florentx, @berkerpeksag, @serhiy-storchaka
Files | <li>[detect_encoding_default.diff](https://bugs.python.org/file18745/detect_encoding_default.diff "Uploaded as text/plain at 2010-09-04.11:32:06 by @florentx"): Patch, apply to 3.x</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-09-04.11:32:08.849>
labels = ['type-feature', 'library']
title = 'add an optional "default" argument to tokenize.detect_encoding'
updated_at = <Date 2014-11-02.12:11:24.713>
user = 'https://github.com/florentx'
```

bugs.python.org fields:
```python
activity = <Date 2014-11-02.12:11:24.713>
actor = 'berker.peksag'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-09-04.11:32:08.849>
creator = 'flox'
dependencies = []
files = ['18745']
hgrepos = []
issue_num = 9771
keywords = ['patch']
message_count = 3.0
messages = ['115567', '122106', '173002']
nosy_count = 6.0
nosy_names = ['vstinner', 'benjamin.peterson', 'eric.araujo', 'flox', 'berker.peksag', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue9771'
versions = ['Python 3.5']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Is there any use case besides the [Tools/scripts/findnocoding.py](https://github.com/python/cpython/blob/main/Tools/scripts/findnocoding.py) script? It is a special tool and it needs to look under the hood.

There are many ways of working with Python sources:

1. Open a file in binary mode, read the content as bytes, and pass it to compile(). You do not even know what encoding was used.
2. Open a text file with `tokenize.open()`.
3. Use `tokenize.detect_encoding()` and manually decode the rest of the file. It is the least convenient way.

**Comment by AA-Turner** [comment]
Closing per Victor, it's been several days with no comments to the contrary.

A
