### ISSUE TITLE
Py_Initialize crashes when stdout has been redirected with freopen

### ISSUE THREAD

**Issue by 0256312c-56f5-4ea4-bc26-b80ba7def6c5** [python/cpython#54289]
BPO | [10080](https://bugs.python.org/issue10080)
--- | :---
Nosy | @amauryfa, @pitrou, @tiran, @tjguk, @briancurtin
Files | <li>[py_main.c](https://bugs.python.org/file19212/py_main.c "Uploaded as text/plain at 2010-10-13.04:11:13 by Mitchell.Stokes"): Sample Program</li><li>[py_main_fileno_check.c](https://bugs.python.org/file19219/py_main_fileno_check.c "Uploaded as text/plain at 2010-10-13.18:54:03 by Mitchell.Stokes")</li><li>[py_main_dup2.c](https://bugs.python.org/file19220/py_main_dup2.c "Uploaded as text/plain at 2010-10-13.18:54:16 by Mitchell.Stokes")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-10-13.04:11:13.984>
labels = ['OS-windows', 'type-crash']
title = 'Py_Initialize crashes when stdout has been redirected with freopen'
updated_at = <Date 2013-07-05.23:58:34.038>
user = 'https://bugs.python.org/MitchellStokes'
```

bugs.python.org fields:
```python
activity = <Date 2013-07-05.23:58:34.038>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2010-10-13.04:11:13.984>
creator = 'Mitchell.Stokes'
dependencies = []
files = ['19212', '19219', '19220']
hgrepos = []
issue_num = 10080
keywords = []
message_count = 8.0
messages = ['118502', '118504', '118515', '118540', '118546', '118562', '118565', '192378']
nosy_count = 6.0
nosy_names = ['amaury.forgeotdarc', 'pitrou', 'christian.heimes', 'tim.golden', 'brian.curtin', 'Mitchell.Stokes']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = None
status = 'languishing'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue10080'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by kumaraditya303** [comment]
This is fixed on main branch and 3.10
