### ISSUE TITLE
spwd returning different value depending on privileges

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#54597]
BPO | [10388](https://bugs.python.org/issue10388)
--- | :---
Nosy | @loewis, @pitrou, @giampaolo, @rbtcollins, @bitdancer, @serhiy-storchaka, @vajrasky
Files | <li>[fix_error_message_getspall.patch](https://bugs.python.org/file31384/fix_error_message_getspall.patch "Uploaded as text/plain at 2013-08-20.14:27:05 by @vajrasky")</li><li>[fix_error_message_getspall_v2.patch](https://bugs.python.org/file33404/fix_error_message_getspall_v2.patch "Uploaded as text/plain at 2014-01-10.09:59:45 by @vajrasky")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-11-11.14:03:10.753>
labels = ['type-bug', 'library']
title = 'spwd returning different value depending on privileges'
updated_at = <Date 2015-07-25.19:11:49.548>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2015-07-25.19:11:49.548>
actor = 'rbcollins'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-11-11.14:03:10.753>
creator = 'giampaolo.rodola'
dependencies = []
files = ['31384', '33404']
hgrepos = []
issue_num = 10388
keywords = ['patch']
message_count = 19.0
messages = ['120950', '195689', '195692', '207793', '207839', '207841', '207843', '207846', '207856', '207860', '207863', '233254', '233260', '233261', '233266', '233289', '247376', '247377', '247378']
nosy_count = 7.0
nosy_names = ['loewis', 'pitrou', 'giampaolo.rodola', 'rbcollins', 'r.david.murray', 'serhiy.storchaka', 'vajrasky']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue10388'
versions = ['Python 3.6']
```

</p></details>

**Comment by hugovk** [comment]
Note the spwd module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AA-Turner** [comment]
Closing per Hugo's comment.

A
