### ISSUE TITLE
AST Optimization: inlining of function calls

### ISSUE THREAD

**Issue by davidmalcolm** [python/cpython#54608]
BPO | [10399](https://bugs.python.org/issue10399)
--- | :---
Nosy | @rhettinger, @gpshead, @ncoghlan, @abalkin, @orsenthil, @pitrou, @vstinner, @giampaolo, @benjaminp, @phsilva, @alex, @davidmalcolm, @meadori, @ericsnowcurrently, @mbdevpl, @isidentical, @Jongy
Files | <li>[py3k-ast-optimization-inlining-2010-11-12-001.patch](https://bugs.python.org/file19583/py3k-ast-optimization-inlining-2010-11-12-001.patch "Uploaded as text/plain at 2010-11-12.20:16:48 by @davidmalcolm")</li><li>[before.png](https://bugs.python.org/file19584/before.png "Uploaded as image/png at 2010-11-12.20:18:28 by @davidmalcolm"): AST of the sample source before optimization</li><li>[after.png](https://bugs.python.org/file19585/after.png "Uploaded as image/png at 2010-11-12.20:18:58 by @davidmalcolm"): AST of the sample source after optimization</li><li>[py3k-ast-pyoptimize-2010-11-19-006.patch](https://bugs.python.org/file19649/py3k-ast-pyoptimize-2010-11-19-006.patch "Uploaded as text/plain at 2010-11-20.01:10:35 by @davidmalcolm")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/davidmalcolm'
closed_at = None
created_at = <Date 2010-11-12.20:16:50.439>
labels = ['interpreter-core', 'performance']
title = 'AST Optimization: inlining of function calls'
updated_at = <Date 2020-11-19.01:06:26.992>
user = 'https://github.com/davidmalcolm'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-19.01:06:26.992>
actor = 'phsilva'
assignee = 'dmalcolm'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2010-11-12.20:16:50.439>
creator = 'dmalcolm'
dependencies = []
files = ['19583', '19584', '19585', '19649']
hgrepos = []
issue_num = 10399
keywords = ['patch']
message_count = 17.0
messages = ['121068', '121076', '121082', '121114', '121151', '121579', '121581', '121585', '121586', '121597', '121778', '121786', '122233', '122237', '122344', '245630', '255516']
nosy_count = 27.0
nosy_names = ['jhylton', 'nnorwitz', 'rhettinger', 'gregory.p.smith', 'ncoghlan', 'belopolsky', 'sdahlbac', 'orsenthil', 'titanstar', 'pitrou', 'vstinner', 'giampaolo.rodola', 'thomaslee', 'benjamin.peterson', 'phsilva', 'alex', 'rfk', 'dmalcolm', 'meador.inge', 'THRlWiTi', 'fijall', 'eric.snow', 'jcon', 'pas', 'mbdevpl', 'BTaskaya', 'Yonatan Goldschmidt']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue10399'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
This looks like an interesting research project that was abandoned 12 years ago. Is there any point leaving the issue open?

**Comment by pitrou** [comment]
I don't think so.

**Comment by vstinner** [comment]
I closed the issue. CPython code evolved a lot. The optimization work in Python 3.11 changed ceval.c a lot.
