### ISSUE TITLE
cgitb.py should assume a binary stream for output

### ISSUE THREAD

**Issue by b5a9ce10-d67f-478f-ab78-b08d099eb753** [python/cpython#54688]
BPO | [10479](https://bugs.python.org/issue10479)
--- | :---
Nosy | @freddrake, @facundobatista, @orsenthil

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-11-21.05:37:14.091>
labels = ['3.10', 'type-bug', '3.8', '3.9', 'expert-unicode']
title = 'cgitb.py should assume a binary stream for output'
updated_at = <Date 2020-11-16.21:55:03.466>
user = 'https://bugs.python.org/vpython'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-16.21:55:03.466>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Unicode']
creation = <Date 2010-11-21.05:37:14.091>
creator = 'v+python'
dependencies = []
files = []
hgrepos = []
issue_num = 10479
keywords = []
message_count = 2.0
messages = ['121865', '127574']
nosy_count = 4.0
nosy_names = ['fdrake', 'facundobatista', 'orsenthil', 'v+python']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue10479'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by hugovk** [comment]
I think we can close this old issue as the cgitb module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/), https://github.com/python/cpython/issues/91217 and https://github.com/python/cpython/pull/32410.

**Comment by AlexWaygood** [comment]
> I think we can close this old issue as the cgitb module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/), #91217 and #32410.

Cc. @freddrake, @facundobatista, @vpython
