### ISSUE TITLE
subprocess and deadlock avoidance

### ISSUE THREAD

**Issue by b5a9ce10-d67f-478f-ab78-b08d099eb753** [python/cpython#54691]
BPO | [10482](https://bugs.python.org/issue10482)
--- | :---
Nosy | @ncoghlan, @4kir4, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-11-21.06:16:01.170>
labels = ['type-feature', 'library']
title = 'subprocess and deadlock avoidance'
updated_at = <Date 2019-03-15.21:59:23.467>
user = 'https://bugs.python.org/vpython'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-15.21:59:23.467>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-11-21.06:16:01.170>
creator = 'v+python'
dependencies = []
files = []
hgrepos = []
issue_num = 10482
keywords = []
message_count = 9.0
messages = ['121871', '122264', '123058', '123059', '123454', '123517', '123521', '222894', '245560']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'v+python', 'akira', 'rosslagerwall', 'martin.panter', 'brandjon']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue10482'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
> Related: [bpo-1260171](https://bugs.python.org/issue?@action=redirect&bpo=1260171), essentially proposing streaming readers and writers for communicate() instead of fixed buffers, but without using OS threads.

Should this be closed on the same basis?   

CC @gpshead

**Comment by gpshead** [comment]
> Should this be closed on the same basis?

Yep, thanks!
