### ISSUE TITLE
Tools/unicode/gencodec.py error

### ISSUE THREAD

**Issue by abalkin** [python/cpython#54761]
BPO | [10552](https://bugs.python.org/issue10552)
--- | :---
Nosy | @malemburg, @loewis, @ronaldoussoren, @abalkin, @ned-deily, @ezio-melotti, @hynek, @vadmium, @iritkatriel
Files | <li>[issue10552.diff](https://bugs.python.org/file19842/issue10552.diff "Uploaded as text/plain at 2010-11-27.21:15:08 by @abalkin")</li><li>[issue10552a.diff](https://bugs.python.org/file19874/issue10552a.diff "Uploaded as text/plain at 2010-11-29.18:36:46 by @abalkin")</li><li>[10552-remove-apple-files.txt](https://bugs.python.org/file32565/10552-remove-apple-files.txt "Uploaded as text/plain at 2013-11-10.18:24:50 by @akuchling"): Remove problematic mapping files before parsing</li><li>[10552-remove-apple-files-v2.txt](https://bugs.python.org/file37687/10552-remove-apple-files-v2.txt "Uploaded as text/plain at 2015-01-13.05:57:29 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-11-27.20:29:09.821>
labels = ['OS-mac', 'type-bug', 'expert-unicode']
title = 'Tools/unicode/gencodec.py error'
updated_at = <Date 2021-11-24.21:35:33.300>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-24.21:35:33.300>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Demos and Tools', 'macOS', 'Unicode']
creation = <Date 2010-11-27.20:29:09.821>
creator = 'belopolsky'
dependencies = []
files = ['19842', '19874', '32565', '37687']
hgrepos = []
issue_num = 10552
keywords = ['patch']
message_count = 15.0
messages = ['122549', '122559', '122565', '122585', '122586', '122829', '122837', '122842', '122843', '122850', '122858', '122916', '202543', '233902', '406955']
nosy_count = 9.0
nosy_names = ['lemburg', 'loewis', 'ronaldoussoren', 'belopolsky', 'ned.deily', 'ezio.melotti', 'hynek', 'martin.panter', 'iritkatriel']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue10552'
versions = ['Python 3.2', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
@ned-deily Is there anything left to do here for Mac or can we close it?

**Comment by ned-deily** [comment]
I know next to nothing about this other than the `mac_*` codecs referenced date back decades to classic Mac OS (9 and earlier) and, AFAIK, aren't used today except perhaps in some dusty legacy code. @malemburg, what do you think?

**Comment by malemburg** [comment]
I tried to run the script against the MAPPINGS/VENDORS/APPLE/ dir files and still get the `TypeError: '<' not supported between instances of 'tuple' and 'int'` for some of the files.

This is apparently a bug in the script which occurs when the mapping files map a single char to multiple code points. Simply removing the sorting fixes the problem, but I have not checked whether the resulting mappings are any good.

Given that these existing mac_*.py encoding mappings won't change anymore, the script works for those mappings and that we don't need to regenerate those codecs anytime soon, I'd suggest to close the ticket.
