### ISSUE TITLE
Add test for curses haskey replacement

### ISSUE THREAD

**Issue by 2b0d3ffc-0546-40f1-879d-e788a176fcd0** [python/cpython#54807]
BPO | [10598](https://bugs.python.org/issue10598)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka, @CuriousLearner
Files | <li>[issue10598.patch](https://bugs.python.org/file19903/issue10598.patch "Uploaded as text/plain at 2010-12-02.10:47:01 by lehmannro")</li><li>[has_key.diff](https://bugs.python.org/file39412/has_key.diff "Uploaded as text/plain at 2015-05-18.01:00:47 by @terryjreedy")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2010-12-01.20:12:43.473>
labels = ['tests', 'type-feature', 'library']
title = 'Add test for curses haskey replacement'
updated_at = <Date 2017-11-08.23:10:20.170>
user = 'https://bugs.python.org/rtarnell'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.23:10:20.170>
actor = 'BreamoreBoy'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2010-12-01.20:12:43.473>
creator = 'rtarnell'
dependencies = []
files = ['19903', '39412']
hgrepos = []
issue_num = 10598
keywords = ['patch']
message_count = 7.0
messages = ['123007', '123062', '221664', '226124', '243443', '243445', '305893']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'lehmannro', 'rtarnell', 'serhiy.storchaka', 'CuriousLearner']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue10598'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by CuriousLearner** [comment]
Is this bug still valid or we can just close it?

**Comment by hugovk** [comment]
Thanks for testing, closing as no longer reproducible.
