### ISSUE TITLE
ZipFile: add a filename_encoding argument

### ISSUE THREAD

**Issue by a15f0e1c-8505-401e-a0e3-653e6d54b44d** [python/cpython#54823]
BPO | [10614](https://bugs.python.org/issue10614)
--- | :---
Nosy | @loewis, @amauryfa, @vstinner, @methane, @serhiy-storchaka
Superseder | <li>bpo-28080: Allow reading member names with bogus encodings in zipfile</li>
Files | <li>[non-ascii-cp932.zip](https://bugs.python.org/file19935/non-ascii-cp932.zip "Uploaded as application/octet-stream at 2010-12-04.10:45:06 by ocean-city"): built with python2.7</li><li>[zipfile.patch](https://bugs.python.org/file26372/zipfile.patch "Uploaded as text/plain at 2012-07-13.04:16:19 by umedoblock"): decode_filename zipfile.patch</li><li>[encodings.py](https://bugs.python.org/file26376/encodings.py "Uploaded as text/plain at 2012-07-13.14:44:18 by umedoblock")</li><li>[10614-zipfile-encoding.patch](https://bugs.python.org/file46043/10614-zipfile-encoding.patch "Uploaded as text/plain at 2016-12-26.13:02:10 by @methane")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2010-12-03.07:41:56.474>
labels = ['3.7', 'type-feature', 'library']
title = 'ZipFile: add a filename_encoding argument'
updated_at = <Date 2016-12-26.13:06:43.489>
user = 'https://bugs.python.org/ocean-city'
```

bugs.python.org fields:
```python
activity = <Date 2016-12-26.13:06:43.489>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2010-12-03.07:41:56.474>
creator = 'ocean-city'
dependencies = []
files = ['19935', '26372', '26376', '46043']
hgrepos = []
issue_num = 10614
keywords = ['patch']
message_count = 15.0
messages = ['123197', '123201', '123202', '123229', '123332', '126791', '136233', '165351', '165384', '165386', '200187', '200193', '200311', '284025', '284026']
nosy_count = 10.0
nosy_names = ['loewis', 'amaury.forgeotdarc', 'vstinner', 'ocean-city', 'methane', 'THRlWiTi', 'Laurent.Mazuel', 'umedoblock', 'serhiy.storchaka', 'Sergey.Dorofeev']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = '28080'
type = 'enhancement'
url = 'https://bugs.python.org/issue10614'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by Akasurde** [comment]
@serhiy-storchaka I think https://github.com/python/cpython/pull/32007 resolves this issue, what do you think? Thanks,

**Comment by serhiy-storchaka** [comment]
Yes, thank you for the reminder.

Closing as a duplicate of #72267.
