### ISSUE TITLE
Simple CSS fix for left margin at docs.python.org

### ISSUE THREAD

**Issue by df501793-f767-4b11-a23d-de40a0e0e148** [python/cpython#55145]
BPO | [10936](https://bugs.python.org/issue10936)
--- | :---
Nosy | @freddrake, @birkenfeld, @ezio-melotti, @merwok, @DeVil2O

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-01-18.19:12:00.071>
labels = ['easy', 'type-bug', '3.8', '3.9', '3.10', 'docs']
title = 'Simple CSS fix for left margin at docs.python.org'
updated_at = <Date 2020-10-30.23:24:34.345>
user = 'https://bugs.python.org/cdunn2001'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-30.23:24:34.345>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2011-01-18.19:12:00.071>
creator = 'cdunn2001'
dependencies = []
files = []
hgrepos = []
issue_num = 10936
keywords = ['easy']
message_count = 14.0
messages = ['126477', '126685', '126690', '126691', '126692', '126693', '126703', '126704', '126738', '126769', '126770', '126774', '130632', '344103']
nosy_count = 7.0
nosy_names = ['fdrake', 'georg.brandl', 'ezio.melotti', 'eric.araujo', 'cdunn2001', 'docs@python', 'codevil_2o']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue10936'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by CAM-Gerlach** [comment]
It seems as if this is somewhat addressed; the sidebar responsively collapses to a hamburger menu when the screen is too narrow or too zoomed in that it would take up too much of it. If there is any remaining work, presumably this should issue should be transferred to the Python-Docs-Theme repo. However, migrating to a much more modern, responsive and accessible theme, like Furo/Lutra, would be much better long-term fix.

**Comment by ezio-melotti** [comment]
I think this can be closed.  Once we switch to a new theme, we should make sure not to reintroduce this (and related) issues.

cc @pradyunsg
