### ISSUE TITLE
Make the Mac installer more like the Windows installer

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#55438]
BPO | [11229](https://bugs.python.org/issue11229)
--- | :---
Nosy | @rhettinger, @ronaldoussoren, @ned-deily, @roseman

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2011-02-16.23:34:42.111>
labels = ['type-feature', 'expert-installation']
title = 'Make the Mac installer more like the Windows installer'
updated_at = <Date 2015-09-18.16:31:35.974>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2015-09-18.16:31:35.974>
actor = 'markroseman'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2011-02-16.23:34:42.111>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 11229
keywords = []
message_count = 3.0
messages = ['128702', '190278', '190279']
nosy_count = 4.0
nosy_names = ['rhettinger', 'ronaldoussoren', 'ned.deily', 'markroseman']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue11229'
versions = ['Python 3.3']
```

</p></details>

**Comment by terryjreedy** [comment]
@ned-deily (and others) Is this Mac installer request still relevant after changes in the last decade?

**Comment by ronaldoussoren** [comment]
The proposal is still as relevant as it was 10 years ago, but it is also unlikely that anything will change here unless anyone steps up to actually do the work (which is non trivial).
