### ISSUE TITLE
python.exe on OS X shared-llbrary build erroneously linked to MacPorts python library

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#55654]
BPO | [11445](https://bugs.python.org/issue11445)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @merwok, @koobs
Files | <li>[issue-11445-linkflags.txt](https://bugs.python.org/file30820/issue-11445-linkflags.txt "Uploaded as text/plain at 2013-07-06.15:25:11 by @ronaldoussoren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2011-03-08.22:24:52.376>
labels = ['OS-mac', 'build']
title = 'python.exe on OS X shared-llbrary build erroneously linked to MacPorts python library'
updated_at = <Date 2014-08-04.03:36:12.165>
user = 'https://github.com/smontanaro'
```

bugs.python.org fields:
```python
activity = <Date 2014-08-04.03:36:12.165>
actor = 'koobs'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Build', 'macOS']
creation = <Date 2011-03-08.22:24:52.376>
creator = 'skip.montanaro'
dependencies = []
files = ['30820']
hgrepos = []
issue_num = 11445
keywords = ['needs review']
message_count = 11.0
messages = ['130379', '130394', '130395', '130405', '130418', '130420', '130455', '130490', '131134', '145713', '192453']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'eric.araujo', 'samueljohn', 'eduardocereto', 'koobs', 'esc24']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue11445'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by ned-deily** [comment]
My apologies for the long delay in getting back to this. With the reworking of how standard library modules find their dependencies starting in 3.11, that is, by supporting both `pkg-config` and by adding module-specific environment variables for each external library, such as `ZLIB_CFLAGS` and `ZLIB_LIBS`, there is no longer a need to add third-party libraries to the top-level `LDFLAGS` and `CPPFLAGS` variables. `./configure --help` has information about the available variables and the [devguide now has specific recommendations for building with MacPorts and Homebrew libraries](https://devguide.python.org/getting-started/setup-building/#install-dependencies) with current releases. Let's close this issue; if there are still problems with this, we can open a new one that reflects the current build environment.
