### ISSUE TITLE
re.sub confusion between count and flags args

### ISSUE THREAD

**Issue by df4ce302-29f4-4836-8ca5-c2e493b9ca74** [python/cpython#56166]
BPO | [11957](https://bugs.python.org/issue11957)
--- | :---
Nosy | @rhettinger, @terryjreedy, @vstinner, @ericvsmith, @jwilk, @ezio-melotti, @merwok, @serhiy-storchaka
Dependencies | <li>bpo-23591: enum: Add Flags and IntFlags</li>
Files | <li>[patch_11957](https://bugs.python.org/file30821/patch_11957 "Uploaded as text/plain at 2013-07-06.15:47:09 by umi")</li><li>[re_keyword_only.patch](https://bugs.python.org/file37067/re_keyword_only.patch "Uploaded as text/plain at 2014-10-29.16:09:21 by @vstinner")</li><li>[re_check_flags_type.patch](https://bugs.python.org/file44825/re_check_flags_type.patch "Uploaded as text/plain at 2016-09-25.21:14:29 by @serhiy-storchaka")</li><li>[re_deprecate_positional_count.patch](https://bugs.python.org/file44826/re_deprecate_positional_count.patch "Uploaded as text/plain at 2016-09-25.21:14:44 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ezio-melotti'
closed_at = None
created_at = <Date 2011-04-29.18:27:10.198>
labels = ['expert-regex', 'type-feature', '3.7']
title = 're.sub confusion between count and flags args'
updated_at = <Date 2017-04-14.18:55:29.189>
user = 'https://bugs.python.org/mindauga'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-14.18:55:29.189>
actor = 'jwilk'
assignee = 'ezio.melotti'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2011-04-29.18:27:10.198>
creator = 'mindauga'
dependencies = ['23591']
files = ['30821', '37067', '44825', '44826']
hgrepos = []
issue_num = 11957
keywords = ['patch']
message_count = 27.0
messages = ['134806', '134820', '134830', '135371', '135386', '135391', '136657', '143520', '186784', '186825', '186832', '186844', '186856', '192416', '230223', '230224', '230226', '230236', '230237', '230238', '230358', '230375', '277386', '277398', '291655', '291659', '291677']
nosy_count = 13.0
nosy_names = ['rhettinger', 'terry.reedy', 'vstinner', 'eric.smith', 'jwilk', 'ezio.melotti', 'eric.araujo', 'mrabarnett', 'python-dev', 'mindauga', 'serhiy.storchaka', 'mmilkin', 'umi']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue11957'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-107767
* gh-107778

**Comment by vstinner** [comment]
My issue bpo-30072 has been marked as a duplicate of this one. Copy of my [msg291650](https://bugs.python.org/msg291650):

The re API seems commonly misused. Example passing a re flag to re.sub():

```pycon
>>> re.sub("A", "B", "ahah", re.I)
'ahah'
```


No error, no warning, but it doesn't work. Oh, sub has 5 paramters, no 4...

I suggest to convert count and flags to keyword-only parameters. To not break the world, especially legit code passing the count parameter as a position argument, an option is to have a deprecation period if these two parameters are passed a positional-only parameter.

--

Another option would be to rely on the fact that re flags are now enums instead of raw integers, and so add basic type check...

Is there are risk of applications using re flags serialized by pickle from Pyhon \< 3.6 and so getting integers?

Maybe the check should only be done if flags are passing as positional-only argument... but the implementation of such check seems may be overkill for such simple and performance-critical function, no?

See issue bpo-30067 for a recent bug in the Python stdlib!

**Comment by serhiy-storchaka** [comment]
Victor, I borrowed Guido's time machine and wrote patches implementing both your suggestions a half year ago.

**Comment by ec31e85c-a35c-494f-805f-21a63c135c1b** [comment]
\+                raise TypeError("sub() takes from 2 to 4 positional arguments "
\+                                "but %d were given" % (4 + len(args)))

It's actually 3 to 5 for sub() and subn().

**Comment by Zac-HD** [comment]
I'd like to propose that we merge Serhiy's second patch, which deprecates passing count and maxsplit arguments as positional arguments.

- There is a slight slowdown for cases where the arguments are already passed by keyword, which is larger in the deprecated case.  However, this is easy to work around by using explicitly `re.compile()`'d patterns, which is already common in performance-sensitive code.
- https://github.com/python/cpython/issues/99918#issuecomment-1333382582 counts _sixteen_ equivalent issues which have been opened against CPython.  This is clearly a substantial and recurring confusion, and while linters have recently started flagging this I would prefer an upstream solution which can help new programmers too.
- https://github.com/python/cpython/pull/95151 suggests that there is appetite for migrating positional-or-keyword params to keyword-only in the standard library when the status quo is confusing or error-prone.

If necessary, I'd be happy to write or organize a PR.

**Comment by hauntsaninja** [comment]
Thanks for bumping this, I'd forgotten about it. As you can tell by my previous comments, I think this is something we need to do. Just fixed another one of these a couple weeks ago. I'll open a PR with Serhiy's patch

**Comment by serhiy-storchaka** [comment]
It is an old patch and it required polishing.
