### ISSUE TITLE
Doc: remove errors about mixed-type comparisons.

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#56276]
BPO | [12067](https://bugs.python.org/issue12067)
--- | :---
Nosy | @rhettinger, @terryjreedy, @mdickinson, @benjaminp, @ezio-melotti, @stevendaprano, @bitdancer, @cjerdonek, @berkerpeksag, @vadmium, @andy-maier, @csabella, @humbdrag
PRs | <li>python/cpython#3199</li><li>python/cpython#30624</li><li>python/cpython#30625</li><li>python/cpython#30651</li><li>python/cpython#30667</li>
Dependencies | <li>bpo-29321: Wrong documentation (Language Ref) for unicode and str comparison</li>
Files | <li>[issue12067-expressions.diff](https://bugs.python.org/file27256/issue12067-expressions.diff "Uploaded as text/plain at 2012-09-22.05:41:58 by mikehoy")</li><li>[issue12067-expressions_v2.diff](https://bugs.python.org/file27442/issue12067-expressions_v2.diff "Uploaded as text/plain at 2012-10-05.21:20:51 by mikehoy"): Minor wording changes.</li><li>[issue12067-expressions_v3.diff](https://bugs.python.org/file35843/issue12067-expressions_v3.diff "Uploaded as text/plain at 2014-07-03.19:34:31 by @andy-maier"): Andy's version of the patch for the 3.5 tip</li><li>[issue12067-expressions_v4.diff](https://bugs.python.org/file35845/issue12067-expressions_v4.diff "Uploaded as text/plain at 2014-07-04.01:15:09 by @andy-maier"): Updates (see message), for v3.5 tip</li><li>[issue12067-expressions-py34_v5.diff](https://bugs.python.org/file35850/issue12067-expressions-py34_v5.diff "Uploaded as text/plain at 2014-07-04.10:47:58 by @andy-maier"): v5 of the patch, targeting 3.4.</li><li>[issue12067-expressions-py34_v6.diff](https://bugs.python.org/file35851/issue12067-expressions-py34_v6.diff "Uploaded as text/plain at 2014-07-04.10:57:28 by @andy-maier"): v6 (same as v5, just now created properly), targeting 3.4.</li><li>[issue12067-expressions-py34_v7.diff](https://bugs.python.org/file35853/issue12067-expressions-py34_v7.diff "Uploaded as text/plain at 2014-07-04.11:27:29 by @andy-maier"): v7 (same as v5, just now created properly), targeting 3.4.</li><li>[issue12067-expressions-py34_v8.diff](https://bugs.python.org/file35924/issue12067-expressions-py34_v8.diff "Uploaded as text/plain at 2014-07-11.14:23:01 by @andy-maier"): v8 (improved doc and added tests), targeting 3.4.</li><li>[try_eq.py](https://bugs.python.org/file35938/try_eq.py "Uploaded as text/plain at 2014-07-13.14:00:07 by @andy-maier"): Test program for py34 for equality of collections</li><li>[try_eq.out](https://bugs.python.org/file35939/try_eq.out "Uploaded as text/plain at 2014-07-13.14:00:53 by @andy-maier"): Output of try_eq.py with cpython 3.4.1</li><li>[issue12067-expressions-py34_v9.diff](https://bugs.python.org/file35971/issue12067-expressions-py34_v9.diff "Uploaded as text/plain at 2014-07-16.14:56:11 by @andy-maier"): v9 of the patch, targeting 3.4.</li><li>[issue12067-expressions-py34_v10.diff](https://bugs.python.org/file36896/issue12067-expressions-py34_v10.diff "Uploaded as text/plain at 2014-10-13.09:07:24 by @andy-maier"): v10 of the patch, targeting 3.4</li><li>[issue12067-expressions-py34_delta-v9-v10.diff](https://bugs.python.org/file36897/issue12067-expressions-py34_delta-v9-v10.diff "Uploaded as text/plain at 2014-10-13.11:46:17 by @andy-maier"): delta between v9 and v10 of the patch</li><li>[issue12067-expressions-py34_v11.diff](https://bugs.python.org/file36920/issue12067-expressions-py34_v11.diff "Uploaded as text/plain at 2014-10-14.18:17:11 by @andy-maier"): v11 of the patch, targeting 3.4</li><li>[issue12067-expressions-py34_v12.diff](https://bugs.python.org/file36978/issue12067-expressions-py34_v12.diff "Uploaded as text/plain at 2014-10-20.09:26:26 by @andy-maier"): v12 of the patch, targeting 3.4</li><li>[issue12067-expressions-py3.5_v13.diff](https://bugs.python.org/file38183/issue12067-expressions-py3.5_v13.diff "Uploaded as text/plain at 2015-02-20.11:00:06 by @vadmium")</li><li>[issue12067-expressions-py3.5_v14.diff](https://bugs.python.org/file38303/issue12067-expressions-py3.5_v14.diff "Uploaded as text/plain at 2015-03-02.18:05:07 by @andy-maier"): v14 of the patch, targeting 3.5 (default)</li><li>[issue12067-expressions-py3.6_v15.diff](https://bugs.python.org/file39970/issue12067-expressions-py3.6_v15.diff "Uploaded as text/plain at 2015-07-22.02:37:03 by @vadmium")</li><li>[issue12067-expressions-py3.6_v16.diff](https://bugs.python.org/file40052/issue12067-expressions-py3.6_v16.diff "Uploaded as text/plain at 2015-07-29.04:44:27 by @vadmium")</li><li>[expressions-py2.7.diff](https://bugs.python.org/file46372/expressions-py2.7.diff "Uploaded as text/plain at 2017-01-21.11:19:52 by @vadmium")</li><li>[expressions-py2.7_v17.diff](https://bugs.python.org/file46398/expressions-py2.7_v17.diff "Uploaded as text/plain at 2017-01-24.03:26:11 by @vadmium")</li><li>[expressions-py3.7_v17.diff](https://bugs.python.org/file46399/expressions-py3.7_v17.diff "Uploaded as text/plain at 2017-01-24.04:06:28 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-05-12.21:59:33.279>
labels = ['easy', 'type-feature', 'tests', 'docs']
title = 'Doc: remove errors about mixed-type comparisons.'
updated_at = <Date 2022-01-26.02:09:04.532>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-26.02:09:04.532>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Tests']
creation = <Date 2011-05-12.21:59:33.279>
creator = 'terry.reedy'
dependencies = ['29321']
files = ['27256', '27442', '35843', '35845', '35850', '35851', '35853', '35924', '35938', '35939', '35971', '36896', '36897', '36920', '36978', '38183', '38303', '39970', '40052', '46372', '46398', '46399']
hgrepos = []
issue_num = 12067
keywords = ['patch', 'easy']
message_count = 53.0
messages = ['135873', '135875', '135890', '148760', '148774', '170887', '170936', '170952', '170953', '170966', '171012', '172148', '183786', '222204', '222209', '222254', '222257', '222270', '222275', '222276', '222278', '222310', '222442', '222747', '222772', '222938', '223217', '226496', '226522', '226529', '228769', '229217', '229229', '229236', '229240', '229245', '229327', '229328', '229721', '236269', '237069', '247079', '247088', '247559', '251405', '251406', '285948', '286128', '286439', '295145', '295222', '300787', '411699']
nosy_count = 17.0
nosy_names = ['rhettinger', 'terry.reedy', 'mark.dickinson', 'benjamin.peterson', 'ezio.melotti', 'steven.daprano', 'r.david.murray', 'cvrebert', 'chris.jerdonek', 'docs@python', 'python-dev', 'berker.peksag', 'martin.panter', 'mikehoy', 'andymaier', 'cheryl.sabella', 'humbdrag']
pr_nums = ['3199', '30624', '30625', '30651', '30667']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue12067'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

### Linked PRs
* gh-104694

**Comment by csabella** [comment]
It appears all the patches for this issue have been applied.  Is the only open item the changes to test_compare?

**Comment by vadmium** [comment]
Yes I think I committed all the documentation. Someone needs to decide whether to use Andy’s tests as they are, or perhaps modify or drop some or all of them.

**Comment by csabella** [comment]
I've created a PR for the changes to test_compare from v16 of the patch.

**Comment by terryjreedy** [comment]
I revised #3199, cutting out duplicated instances and all tests involving identity, not just the 3 that fail now .  The result is about half as big.
