### ISSUE TITLE
smtplib.SMTP_SSL leaks socket connections on SSL error

### ISSUE THREAD

**Issue by 335f435e-efd7-41ce-b565-d8691a22e6fd** [python/cpython#56587]
BPO | [12378](https://bugs.python.org/issue12378)
--- | :---
Nosy | @pitrou, @giampaolo, @tiran, @bitdancer, @zvyn
Files | <li>[issue12378_py27.patch](https://bugs.python.org/file35743/issue12378_py27.patch "Uploaded as text/plain at 2014-06-23.23:13:10 by bhm")</li><li>[issue12378_py35.patch](https://bugs.python.org/file36037/issue12378_py35.patch "Uploaded as text/plain at 2014-07-22.23:14:34 by @zvyn")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-06-20.19:44:23.587>
labels = ['3.7', 'library', 'performance']
title = 'smtplib.SMTP_SSL leaks socket connections on SSL error'
updated_at = <Date 2017-09-06.16:49:07.354>
user = 'https://bugs.python.org/joeshaw'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.16:49:07.354>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-06-20.19:44:23.587>
creator = 'joeshaw'
dependencies = []
files = ['35743', '36037']
hgrepos = []
issue_num = 12378
keywords = ['patch']
message_count = 10.0
messages = ['138753', '138754', '138764', '138795', '221211', '221379', '221383', '221837', '223706', '301482']
nosy_count = 10.0
nosy_names = ['pitrou', 'giampaolo.rodola', 'christian.heimes', 'r.david.murray', 'joeshaw', 'jesstess', 'catalin.iacob', 'kasun', 'zvyn', 'bhm']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue12378'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by tiran** [comment]
Not a bug in the SSL module.

**Comment by hugovk** [comment]
I think this can be closed?

The smtpd module is deprecated in 3.11 and set for removal in 3.13.

And asyncore was deprecated in 3.6 and will be removed in 3.12.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
> I think this can be closed?
> 
> The smtpd module is deprecated in 3.11 and set for removal in 3.13.
> 
> And asyncore was deprecated in 3.6 and will be removed in 3.12.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

Agreed. There also has not been any significant activity on this issue since 2014, indicating that this problem probably does not affect a large number of users.

Cc. @giampaolo, @bitdancer, @zvyn, @joeshaw
