### ISSUE TITLE
cgi.parse_multipart is broken on 3.x

### ISSUE THREAD

**Issue by a76d5361-6ea7-4356-91b1-8b6933a8c392** [python/cpython#56620]
BPO | [12411](https://bugs.python.org/issue12411)
--- | :---
Nosy | @gvanrossum, @orsenthil, @glyph, @merwok, @bitdancer, @florentx, @PierreQuentel, @iritkatriel
Files | <li>[cgi-coverage.diff](https://bugs.python.org/file22470/cgi-coverage.diff "Uploaded as text/plain at 2011-06-25.15:09:07 by jonas.wagner")</li><li>[cgi-coverage-2.diff](https://bugs.python.org/file22567/cgi-coverage-2.diff "Uploaded as text/plain at 2011-07-04.11:26:34 by jonas.wagner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = None
created_at = <Date 2011-06-25.15:09:07.664>
labels = ['type-bug', 'library']
title = 'cgi.parse_multipart is broken on 3.x'
updated_at = <Date 2021-12-13.17:35:22.092>
user = 'https://bugs.python.org/jonaswagner'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-13.17:35:22.092>
actor = 'iritkatriel'
assignee = 'orsenthil'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-06-25.15:09:07.664>
creator = 'jonas.wagner'
dependencies = []
files = ['22470', '22567']
hgrepos = []
issue_num = 12411
keywords = ['patch']
message_count = 14.0
messages = ['139082', '139649', '139668', '139742', '139752', '139757', '139803', '180417', '180425', '180428', '180429', '180456', '180457', '408461']
nosy_count = 13.0
nosy_names = ['gvanrossum', 'orsenthil', 'glyph', 'eric.araujo', 'jonas.wagner', 'r.david.murray', 'efosmark', 'milesck', 'MHordecki', 'flox', 'quentel', 'python-dev', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = None
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue12411'
versions = ['Python 3.2', 'Python 3.3']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/).
