### ISSUE TITLE
gettext breaks on empty plural-forms value

### ISSUE THREAD

**Issue by djc** [python/cpython#56634]
BPO | [12425](https://bugs.python.org/issue12425)
--- | :---
Nosy | @malemburg, @loewis, @akuchling, @ned-deily, @djc, @merwok, @serhiy-storchaka
Files | <li>[issue12425.patch](https://bugs.python.org/file38918/issue12425.patch "Uploaded as text/plain at 2015-04-13.15:08:35 by @akuchling")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-06-28.07:38:27.095>
labels = ['type-bug', 'library']
title = 'gettext breaks on empty plural-forms value'
updated_at = <Date 2017-09-23.19:56:11.763>
user = 'https://github.com/djc'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-23.19:56:11.763>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-06-28.07:38:27.095>
creator = 'djc'
dependencies = []
files = ['38918']
hgrepos = []
issue_num = 12425
keywords = ['patch', 'needs review']
message_count = 5.0
messages = ['139347', '139435', '240618', '240679', '302802']
nosy_count = 9.0
nosy_names = ['lemburg', 'loewis', 'akuchling', 'ned.deily', 'djc', 'eric.araujo', 'Arfrever', 'serhiy.storchaka', 'bkabrda']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue12425'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Sorry, I don't see a value of issuing warning if the following line of the code is failed. Why not raise an exception instead?

A warning can be issued in the case of lacking nplurals= which is not used in Python implementation.

I think additional checks should be added in msgfmt.py. GNU msgfmt checks that plural= and nplurals= are specified if there are plural form translations.

**Comment by m-aciek** [comment]
> GNU msgfmt checks that plural= and nplurals= are specified if there are plural form translations.

For what it's worth I wasn't able to reproduce that with 0.22.4 nor 0.21.1 GNU msgfmt. Tested on Django admin translation file with both `Plural-Forms` body emptied, broken (random characters) and removed (along with header key).

**Comment by merwok** [comment]
This is old, with the upstream bug closed.

**Comment by m-aciek** [comment]
I've created https://github.com/python/cpython/pull/112895 with a ValueError (and a description) in place of an IndexError.
