### ISSUE TITLE
Chained tracebacks are confusing because the first traceback is minimal

### ISSUE THREAD

**Issue by bitdancer** [python/cpython#56744]
BPO | [12535](https://bugs.python.org/issue12535)
--- | :---
Nosy | @birkenfeld, @rhettinger, @terryjreedy, @ncoghlan, @benjaminp, @ezio-melotti, @merwok, @bitdancer, @ericsnowcurrently, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-07-11.17:33:03.089>
labels = ['interpreter-core', 'type-feature', 'library', '3.9', '3.10']
title = 'Chained tracebacks are confusing because the first traceback is minimal'
updated_at = <Date 2021-12-30.00:05:54.431>
user = 'https://github.com/bitdancer'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-30.00:05:54.431>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2011-07-11.17:33:03.089>
creator = 'r.david.murray'
dependencies = []
files = []
hgrepos = []
issue_num = 12535
keywords = []
message_count = 10.0
messages = ['140153', '140158', '140159', '140160', '140176', '140471', '140478', '164670', '188653', '409337']
nosy_count = 11.0
nosy_names = ['georg.brandl', 'rhettinger', 'terry.reedy', 'ncoghlan', 'benjamin.peterson', 'ezio.melotti', 'eric.araujo', 'r.david.murray', 'eric.snow', 'isoschiz', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue12535'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
> This was created about 10 years ago, I wonder if people still feel there is a need to change something here, or did we all get used to the status quo by now?

I'll take the silence as indication that there is no longer interest in this. Feel free to reopen if I'm wrong.

**Comment by ibro45** [comment]
I was looking for how to reverse the order of the chained tracebacks and came across this. Frameworks that combine several other libraries can end up having quite a long chain, and I always need to scroll up to find whatever the main issue is. An option to reverse the order of the traceback chain could be a minimal solution to achieve satisfactory results. I think it would also satisfy users who are trying to extract only the top exception (links below). Just wanted to indicate that there is some interest:
- https://stackoverflow.com/questions/38824798/python-how-to-catch-inner-exception-of-exception-chain
- https://stackoverflow.com/questions/1603940/how-can-i-modify-a-python-traceback-object-when-raising-an-exception
- https://stackoverflow.com/questions/63184408/catching-outer-exceptions-in-python
