### ISSUE TITLE
test_long.test_nan_inf() failed on OpenBSD (powerpc)

### ISSUE THREAD

**Issue by 50f649cd-adde-4d34-ae26-9b73c543f714** [python/cpython#56798]
BPO | [12589](https://bugs.python.org/issue12589)
--- | :---
Nosy | @mdickinson, @vstinner
Files | <li>[pyconfig.h](https://bugs.python.org/file22854/pyconfig.h "Uploaded as text/plain at 2011-08-07.09:08:34 by landry"): openbsd/macppc pyconfig for python 3.2.1</li><li>[math.h](https://bugs.python.org/file22855/math.h "Uploaded as text/plain at 2011-08-07.09:08:58 by landry"): openbsd/macppc math.h</li><li>[pyconfig.h.wrong](https://bugs.python.org/file22856/pyconfig.h.wrong "Uploaded as text/plain at 2011-08-07.10:16:52 by landry"): broken pyconfig.h</li><li>[build-macppc.log](https://bugs.python.org/file22857/build-macppc.log "Uploaded as text/plain at 2011-08-07.10:17:21 by landry"): python 3.2.1 failing build log</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-07-19.21:40:34.263>
labels = ['type-bug', 'tests']
title = 'test_long.test_nan_inf() failed on OpenBSD (powerpc)'
updated_at = <Date 2019-03-16.00:00:24.422>
user = 'https://bugs.python.org/rpointel'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-16.00:00:24.422>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2011-07-19.21:40:34.263>
creator = 'rpointel'
dependencies = []
files = ['22854', '22855', '22856', '22857']
hgrepos = []
issue_num = 12589
keywords = []
message_count = 21.0
messages = ['140697', '140698', '140758', '140803', '140817', '140825', '140836', '140863', '140865', '140884', '140886', '140887', '140889', '140890', '140891', '140894', '141741', '141742', '142743', '143186', '221768']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'vstinner', 'rpointel', 'landry']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue12589'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
This issue is very old and a lot of things have changed since then as such I am closing it. Feel free to create a new issue targeting supported python versions if this issue still exists.

**Comment by vstinner** [comment]
Moreover, Python 3.11 has build changes:

* Building Python now requires a C11 compiler without optional C11 features.
* Building Python now requires a C99 <math.h> header file providing the following functions: copysign(), hypot(), isfinite(), isinf(), isnan(), round().

https://docs.python.org/dev/whatsnew/3.11.html#build-changes
