### ISSUE TITLE
Docs for "Using Python on a Macintosh" needs to be updated

### ISSUE THREAD

**Issue by c93b9d13-1980-4d52-bebf-34cc25382d0a** [python/cpython#56803]
BPO | [12594](https://bugs.python.org/issue12594)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @scottmacpherson, @tomy0000000, @cmhzc
Files | <li>[pythonusage_mac.patch](https://bugs.python.org/file35526/pythonusage_mac.patch "Uploaded as text/plain at 2014-06-07.21:25:16 by yuly")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2011-07-20.15:00:56.914>
labels = ['OS-mac', 'docs']
title = 'Docs for "Using Python on a Macintosh" needs to be updated'
updated_at = <Date 2021-03-04.11:54:11.859>
user = 'https://bugs.python.org/hop'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-04.11:54:11.859>
actor = 'tomy0000000'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'macOS']
creation = <Date 2011-07-20.15:00:56.914>
creator = 'hop'
dependencies = []
files = ['35526']
hgrepos = []
issue_num = 12594
keywords = ['patch']
message_count = 8.0
messages = ['140744', '140761', '219980', '219989', '219998', '273253', '387651', '387654']
nosy_count = 8.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'docs@python', 'hop', 'yuly', 'macpherson.scott', 'tomy0000000', 'cmhzc']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue12594'
versions = []
```

</p></details>

**Comment by zitterbewegung** [comment]
This has already be rewriten and should be closed.

**Comment by ned-deily** [comment]
After a very long delay, the [macOS section](https://docs.python.org/3.13/using/mac.html) of the [Python Setup and Usage](https://docs.python.org/3.13/using/index.html) document has undergone an extensive rewrite and expansion for the upcoming Python 3.13 release. Since it is so old, let's close this issue. Feel free to open new issues against the new document.
