### ISSUE TITLE
Optimization/refactoring for {bytearray, bytes, unicode}.strip()

### ISSUE THREAD

**Issue by 23dad19e-9ca4-43ba-8483-d783d18dcb4c** [python/cpython#57016]
BPO | [12807](https://bugs.python.org/issue12807)
--- | :---
Nosy | @pitrou, @vstinner, @benjaminp, @ezio-melotti
Files | <li>[stringlib_strip.patch](https://bugs.python.org/file23124/stringlib_strip.patch "Uploaded as text/plain at 2011-09-10.01:05:39 by jcon"): Move strip() to stringlib</li><li>[stringlib_strip2.patch](https://bugs.python.org/file23383/stringlib_strip2.patch "Uploaded as text/plain at 2011-10-12.00:38:57 by jcon"): v2</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-08-22.02:59:00.730>
labels = ['interpreter-core', 'performance']
title = 'Optimization/refactoring for {bytearray, bytes, unicode}.strip()'
updated_at = <Date 2015-04-14.20:21:27.792>
user = 'https://bugs.python.org/jcon'
```

bugs.python.org fields:
```python
activity = <Date 2015-04-14.20:21:27.792>
actor = 'msoucy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2011-08-22.02:59:00.730>
creator = 'jcon'
dependencies = []
files = ['23124', '23383']
hgrepos = []
issue_num = 12807
keywords = ['patch']
message_count = 9.0
messages = ['142660', '142882', '142941', '142942', '143822', '144752', '144871', '145379', '145445']
nosy_count = 6.0
nosy_names = ['pitrou', 'vstinner', 'benjamin.peterson', 'ezio.melotti', 'jcon', 'msoucy']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue12807'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
@pitrou what is the status of this?

**Comment by pitrou** [comment]
@iritkatriel It's probably massively out of date.
