### ISSUE TITLE
inspect.getsource only works for objects loaded from files, not interactive session

### ISSUE THREAD

**Issue by 5df057ac-c83d-447e-8c45-910556b17608** [python/cpython#57129]
BPO | [12920](https://bugs.python.org/issue12920)
--- | :---
Nosy | @terryjreedy, @ned-deily, @merwok, @bitdancer, @PCManticore, @Naddiseo, @BlckKnght, @native-api, @vmsp, @Ark-kun

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-09-06.18:37:57.848>
labels = ['interpreter-core', '3.8', 'expert-IDLE', 'type-bug', '3.7']
title = 'inspect.getsource only works for objects loaded from files, not interactive session'
updated_at = <Date 2020-11-30.02:13:01.074>
user = 'https://github.com/PCManticore'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-30.02:13:01.074>
actor = 'Ark-kun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'Interpreter Core']
creation = <Date 2011-09-06.18:37:57.848>
creator = 'Claudiu.Popa'
dependencies = []
files = []
hgrepos = []
issue_num = 12920
keywords = []
message_count = 15.0
messages = ['143645', '143773', '143790', '143831', '185179', '245714', '245721', '245723', '252846', '265815', '297768', '297797', '328836', '331659', '382107']
nosy_count = 12.0
nosy_names = ['terry.reedy', 'ned.deily', 'eric.araujo', 'r.david.murray', 'Claudiu.Popa', 'Naddiseo', 'Steven.Barker', 'Ivan.Pozdeev', 'zorceta', 'nikitakit', 'vmsp', 'Ark-kun']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue12920'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-111197

**Comment by a112f6b9-61d0-4bf0-8679-04d3662796fc** [comment]
So, what would be the right approach here? Store the interactive session's input text in memory?

**Comment by bitdancer** [comment]
Probably.  Figure out a protocol to inject them into linecache, perhaps.  But I'm not sure such a thing would be accepted.  If you can figure out a way to make it work at least theoretically, it would probably be best to talk about it on python-ideas first.

In the meantime it would be nice to improve the error message, which is what we should use this issue for.

**Comment by liudonghua123** [comment]
It would be convenient if `inspect.getsource` support user defined functions/classes in REPL environment.

Is there some simple hack ways like `ipython` does. I am writing an app which embed a simple repl shell, and I really need this features. I want to found how `ipython` achieved this, but it involved a lot of other stuffs.

**Comment by iritkatriel** [comment]
CC @pablogsal

**Comment by pablogsal** [comment]
This works now as part of https://github.com/python/cpython/pull/110775

We can add some tests and close the issue

**Comment by liudonghua123** [comment]
From https://github.com/greenplum-db/GreenplumPython/pull/139, I found I can use `dill.source.getsource` as fallback to `inspect.getsource`.

![6d167b52a45059c758348e43584e5a7](https://github.com/python/cpython/assets/2276718/071c9a00-28ff-4699-b550-05516e8dc0b0)

**Comment by merwok** [comment]
Please read previous comments: the next version of Python will fix this directly.
(Unsure if that means 3.12 or 3.13!)
