### ISSUE TITLE
pdb throws AttributeError at end of debugging session

### ISSUE THREAD

**Issue by ee1f588e-7771-4f9c-b4f6-b9593b1610a0** [python/cpython#57253]
BPO | [13044](https://bugs.python.org/issue13044)
--- | :---
Nosy | @amauryfa, @nedbat, @asvetlov, @meadori, @xdegaye, @serhiy-storchaka, @applio
Files | <li>[debug.py](https://bugs.python.org/file23242/debug.py "Uploaded as text/plain at 2011-09-25.16:36:21 by akl"): Trivial script to demonstrate issue</li><li>[bdb_leak.diff](https://bugs.python.org/file47577/bdb_leak.diff "Uploaded as text/plain at 2018-05-08.20:27:41 by @xdegaye")</li><li>[lazy_import.diff](https://bugs.python.org/file47578/lazy_import.diff "Uploaded as text/plain at 2018-05-08.20:28:03 by @xdegaye")</li><li>[gdb_backtrace.txt](https://bugs.python.org/file47579/gdb_backtrace.txt "Uploaded as text/plain at 2018-05-08.20:28:14 by @xdegaye")</li><li>[global_destructors.diff](https://bugs.python.org/file47581/global_destructors.diff "Uploaded as text/plain at 2018-05-10.20:08:48 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-09-25.16:36:22.166>
labels = ['type-bug', 'library']
title = 'pdb throws AttributeError at end of debugging session'
updated_at = <Date 2018-05-10.20:36:35.281>
user = 'https://bugs.python.org/akl'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-10.20:36:35.281>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-09-25.16:36:22.166>
creator = 'akl'
dependencies = []
files = ['23242', '47577', '47578', '47579', '47581']
hgrepos = []
issue_num = 13044
keywords = ['patch']
message_count = 11.0
messages = ['144525', '144534', '176273', '176987', '176993', '242344', '242345', '315894', '316297', '316373', '316377']
nosy_count = 9.0
nosy_names = ['amaury.forgeotdarc', 'nedbat', 'asvetlov', 'meador.inge', 'xdegaye', 'akl', 'serhiy.storchaka', 'davin', 'cfbearden']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue13044'
versions = ['Python 2.7']
```

</p></details>

**Comment by gaogaotiantian** [comment]
Unable to reproduce with `main` (currently 3.13). Please reopen this if you can still repro with modern Python.
