### ISSUE TITLE
namedtuple row factory for sqlite3

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#57508]
BPO | [13299](https://bugs.python.org/issue13299)
--- | :---
Nosy | @rhettinger, @ncoghlan, @merwok, @akheron, @serhiy-storchaka, @dlenski, @YoSTEALTH, @erlend-aasland
Files | <li>[issue_13299.patch](https://bugs.python.org/file26909/issue_13299.patch "Uploaded as text/plain at 2012-08-20.03:20:31 by Russell.Sim")</li><li>[issue_13299.1.patch](https://bugs.python.org/file26945/issue_13299.1.patch "Uploaded as text/plain at 2012-08-21.12:16:24 by Russell.Sim")</li><li>[issue_13299.2.patch](https://bugs.python.org/file26946/issue_13299.2.patch "Uploaded as text/plain at 2012-08-21.12:49:55 by Russell.Sim")</li><li>[sqlite_namedtuplerow.patch](https://bugs.python.org/file37673/sqlite_namedtuplerow.patch "Uploaded as text/plain at 2015-01-11.08:05:09 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-10-31.00:32:25.001>
labels = ['type-feature']
title = 'namedtuple row factory for sqlite3'
updated_at = <Date 2021-08-05.07:15:53.393>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-05.07:15:53.393>
actor = 'intellimath'
assignee = 'ghaering'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2011-10-31.00:32:25.001>
creator = 'ncoghlan'
dependencies = []
files = ['26909', '26945', '26946', '37673']
hgrepos = []
issue_num = 13299
keywords = ['patch']
message_count = 19.0
messages = ['146670', '146738', '147474', '168617', '168748', '168761', '168762', '168763', '218657', '218668', '223704', '223725', '224702', '224707', '233839', '234424', '394912', '395065', '398970']
nosy_count = 11.0
nosy_names = ['rhettinger', 'ghaering', 'ncoghlan', 'eric.araujo', 'petri.lehtinen', 'serhiy.storchaka', 'dlenski', 'Russell.Sim', 'YoSTEALTH', 'erlendaasland', 'intellimath']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue13299'
versions = ['Python 3.5']
```

</p></details>

**Comment by erlend-aasland** [comment]
FTR, here's a benchmark using @serhiy-storchaka's approach w/LRU cache:

<details>
<summary>bench-row.py</summary>

```python
import pyperf

from textwrap import dedent


SETUP_DEF=dedent("""
    import sqlite3
    cx = sqlite3.connect(":memory:")
""")
SETUP_ROW=dedent("""
    import sqlite3
    cx = sqlite3.connect(":memory:")
    cx.row_factory = sqlite3.Row
""")
SETUP_NAMED=dedent("""
    import sqlite3
    cx = sqlite3.connect(":memory:")
    cx.row_factory = sqlite3.NamedTupleRow
""")
STMT=dedent("""
    cx.execute("select 1 as 'a', 2 as 'b'").fetchall()
""")

runner = pyperf.Runner()
runner.timeit(name="default", stmt=STMT, setup=SETUP_DEF)
runner.timeit(name="row", stmt=STMT, setup=SETUP_ROW)
runner.timeit(name="named", stmt=STMT, setup=SETUP_NAMED)
```

</details>

```
$ python ../cpython-stuff/bench-row.py
.....................
default: Mean +- std dev: 2.48 us +- 0.02 us
.....................
row: Mean +- std dev: 2.60 us +- 0.02 us
.....................
named: Mean +- std dev: 3.71 us +- 0.03 us
```

Following up Serhiy's suggestion to add a `cursor.fieldnames()` method shows a small improvement:

```
$ python ../cpython-stuff/bench-row.py
.....................
default: Mean +- std dev: 2.48 us +- 0.02 us
.....................
row: Mean +- std dev: 2.60 us +- 0.02 us
.....................
named: Mean +- std dev: 3.26 us +- 0.05 us
```

**Comment by merwok** [comment]
These years, I would prefer a dataclass conversion rather than a named tuple.

**Comment by erlend-aasland** [comment]
> These years, I would prefer a dataclass conversion rather than a named tuple.

I'm curious why?

IMO, named tuples are a better fit. A dataclass factory would be considerably slower than using named tuples, and it does not offer subscripting nor slicing out of the box.

**Comment by merwok** [comment]
I don’t like using named tuples after all!  I prefer having attribute access only, it’s more explicit that tuple positions.
Nowadays I see named tuples as a great thing to add attributes to some data structure that used to be a tuple only, but as a tool to define new lightweight data classes I prefer the dataclasses module.

**Comment by erlend-aasland** [comment]
More importantly; is it worth it to pursue this issue further? Is the performance acceptable?

**Comment by merwok** [comment]
I think that named tuples still make sense for a row factory.  But I am the wrong person to evaluate performance numbers.

**Comment by erlend-aasland** [comment]
An alternative approach is simply to add attribute access to sqlite3.Row.

**Comment by erlend-aasland** [comment]
FYI, I've added a namedtuple row factory as an example in the proposed "row factory how-to" in gh-99507. Perhaps it is suffictient to keep this as an example/recipe in the docs instead of adding it as a new feature.

**Comment by erlend-aasland** [comment]
The sqlite3 docs now include a "row factory how-to" that includes a recipe for a simple `namedtuple` row factory (though without the class creation cache optimisation). I'm not sure it is worth it to add the `namedtuple` row factory as a feature, thought; some users want a named tuple, some want a dataclass, some want something else.

In the light of the docs update, I now suggest to close this feature request.
