### ISSUE TITLE
sched.py: speedup cancel() method

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#57660]
BPO | [13451](https://bugs.python.org/issue13451)
--- | :---
Nosy | @rhettinger, @pitrou, @giampaolo, @serhiy-storchaka
PRs | <li>python/cpython#22759</li>
Files | <li>[sched-cancel-speedup.patch](https://bugs.python.org/file23750/sched-cancel-speedup.patch "Uploaded as text/plain at 2011-11-22.01:03:41 by @giampaolo")</li><li>[cancel-later-approach.patch](https://bugs.python.org/file23753/cancel-later-approach.patch "Uploaded as text/plain at 2011-11-22.09:03:42 by @giampaolo")</li><li>[cancel.patch](https://bugs.python.org/file23785/cancel.patch "Uploaded as text/plain at 2011-11-26.13:35:31 by @giampaolo")</li><li>[bench.py](https://bugs.python.org/file23786/bench.py "Uploaded as text/plain at 2011-11-26.13:36:03 by @giampaolo")</li><li>[cancel_2.patch](https://bugs.python.org/file27489/cancel_2.patch "Uploaded as text/plain at 2012-10-08.12:08:28 by @serhiy-storchaka")</li><li>[cancel3.patch](https://bugs.python.org/file32136/cancel3.patch "Uploaded as text/plain at 2013-10-15.20:13:24 by @giampaolo")</li><li>[cancel_4.patch](https://bugs.python.org/file32138/cancel_4.patch "Uploaded as text/plain at 2013-10-15.21:37:46 by @serhiy-storchaka")</li><li>[cancel_4b.patch](https://bugs.python.org/file32281/cancel_4b.patch "Uploaded as text/plain at 2013-10-21.15:33:35 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2011-11-22.01:03:42.140>
labels = ['library', '3.9', 'performance']
title = 'sched.py: speedup cancel() method'
updated_at = <Date 2020-10-27.04:05:56.626>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-27.04:05:56.626>
actor = 'vstinner'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2011-11-22.01:03:42.140>
creator = 'giampaolo.rodola'
dependencies = []
files = ['23750', '23753', '23785', '23786', '27489', '32136', '32138', '32281']
hgrepos = []
issue_num = 13451
keywords = ['patch']
message_count = 20.0
messages = ['148103', '148105', '148108', '148403', '149292', '172377', '199978', '199988', '200012', '200015', '200016', '200017', '200023', '200043', '200792', '200802', '219316', '228045', '267780', '350176']
nosy_count = 5.0
nosy_names = ['rhettinger', 'pitrou', 'giampaolo.rodola', 'stutzbach', 'serhiy.storchaka']
pr_nums = ['22759']
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue13451'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
This issue was created over a decade ago and the discussion indicates there is no consensus about the suggested optimisation. Any objections to closing it?

**Comment by gvanrossum** [comment]
Is this module even useful? It looks like a basic algorithm I implemented over 3 decades ago. Do we need this in the stdlib? As was noted earlier, asyncio has a similar event queue but it's different enough that it couldn't reuse the code here (note that asyncio also manages its own clock, and doesn't use locks). I imagine that other packages needing something like this probably also mostly wrote their own (heapq is very handy for this!) rather than using this module (dang, the `scheduler` class name doesn't even start with a capital `S`, it's so old :-).

**Comment by vstinner** [comment]
> Is this module even useful?

In top PyPI 5000 projects, 5 projects use the ``sched`` module:

* apache-airflow
* newrelic
* python-redis-lock
* spotinst-agent
* spotinst-agent-2

Example with the newrelic code:

```
self._scheduler = sched.scheduler(self._harvest_timer, self._harvest_shutdown.wait)
...
self._scheduler.enter(event_harvest_config.report_period_ms / 1000.0, 1, self._harvest_flexible, ())
...
self._scheduler.run()
...
```

I used the command: ``./search_pypi_top.py PYPI-2020-09-01/ 'import sched *$|from sched import' -q``.

If we would like to remove the module, we should start by deprecating it. https://peps.python.org/pep-0594/ doesn't schedule the removal of the sched module :-)

**Comment by gvanrossum** [comment]
Okay, never mind then. (Thanks for the research!)

But let’s just close this.
