### ISSUE TITLE
Tkinter Tk args and Gnome Shell application name

### ISSUE THREAD

**Issue by 5094b1c2-01f9-4228-8f45-254689cdb25e** [python/cpython#57762]
BPO | [13553](https://bugs.python.org/issue13553)
--- | :---
Nosy | @terryjreedy, @serwy, @serhiy-storchaka
PRs | <li>python/cpython#4786</li>
Files | <li>[tk_wm_test.py](https://bugs.python.org/file23875/tk_wm_test.py "Uploaded as text/plain at 2011-12-08.01:12:08 by th9")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-12-08.01:12:08.669>
labels = ['3.7', '3.8', 'type-bug', 'expert-tkinter', 'docs']
title = 'Tkinter Tk args and Gnome Shell application name'
updated_at = <Date 2018-02-02.22:13:29.485>
user = 'https://bugs.python.org/th9'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-02.22:13:29.485>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Tkinter']
creation = <Date 2011-12-08.01:12:08.669>
creator = 'th9'
dependencies = []
files = ['23875']
hgrepos = []
issue_num = 13553
keywords = ['patch']
message_count = 7.0
messages = ['149013', '149768', '149980', '150055', '150070', '166948', '224883']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'roger.serwy', 'docs@python', 'th9', 'zup', 'serhiy.storchaka']
pr_nums = ['4786']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue13553'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-100440
* gh-100441

**Comment by hauntsaninja** [comment]
Took a couple years, but https://github.com/python/cpython/pull/4786 almost completes this. The only thing missing I can tell from @terryjreedy's comment above is the docstring disambiguation of "Toplevel"
