### ISSUE TITLE
Increase test coverage for pstats.py

### ISSUE THREAD

**Issue by 13cda6a3-6985-4eaf-b6f1-363f4df13ffd** [python/cpython#57879]
BPO | [13670](https://bugs.python.org/issue13670)
--- | :---
Nosy | @birkenfeld, @briancurtin, @iritkatriel
Files | <li>[test_pstats.diff](https://bugs.python.org/file24098/test_pstats.diff "Uploaded as text/plain at 2011-12-28.14:13:27 by andrea.crotti")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2011-12-28.14:13:28.618>
labels = ['easy', 'type-feature', 'tests']
title = 'Increase test coverage for pstats.py'
updated_at = <Date 2022-03-22.21:55:07.934>
user = 'https://bugs.python.org/andreacrotti'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.21:55:07.934>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2011-12-28.14:13:28.618>
creator = 'andrea.crotti'
dependencies = []
files = ['24098']
hgrepos = []
issue_num = 13670
keywords = ['easy', 'newcomer friendly']
message_count = 6.0
messages = ['150290', '150291', '150292', '221790', '338076', '415821']
nosy_count = 4.0
nosy_names = ['georg.brandl', 'brian.curtin', 'andrea.crotti', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue13670'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-103928
* gh-111447

**Comment by corona10** [comment]
Now we can close the issue.

@tigercosmos 
Thanks for the contribution! 

@gaogaotiantian 
Thanks for the review!
