### ISSUE TITLE
Allow objects implemented in pure Python to export PEP 3118 buffers

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#58006]
BPO | [13797](https://bugs.python.org/issue13797)
--- | :---
Nosy | @rhettinger, @mdickinson, @ncoghlan, @pitrou, @scoder, @alex, @ericsnowcurrently, @vadmium
Dependencies | <li>bpo-10181: Problems with Py_buffer management in memoryobject.c (and elsewhere?)</li>
Files | <li>[llindstrom-newbuffer-0dd8ba1c2c2c.tar.gz](https://bugs.python.org/file31329/llindstrom-newbuffer-0dd8ba1c2c2c.tar.gz "Uploaded as application/x-gzip at 2013-08-16.22:53:36 by kermode"): Extension module containing BufferMixin and Py_buffer. Source.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-01-16.10:29:10.732>
labels = ['interpreter-core']
title = 'Allow objects implemented in pure Python to export PEP 3118 buffers'
updated_at = <Date 2016-03-23.04:03:54.804>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2016-03-23.04:03:54.804>
actor = 'siemer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2012-01-16.10:29:10.732>
creator = 'ncoghlan'
dependencies = ['10181']
files = ['31329']
hgrepos = []
issue_num = 13797
keywords = []
message_count = 11.0
messages = ['151347', '151351', '154683', '154684', '154692', '154855', '156440', '156479', '156485', '163058', '195436']
nosy_count = 13.0
nosy_names = ['rhettinger', 'siemer', 'mark.dickinson', 'ncoghlan', 'kermode', 'pitrou', 'scoder', 'Arfrever', 'alex', 'sbt', 'eric.snow', 'martin.panter', 'Jacob.Holm']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue13797'
versions = ['Python 3.6']
```

</p></details>

**Comment by merwok** [comment]
@JelleZijlstra can this be closed thanks to the Buffer PEP?

**Comment by JelleZijlstra** [comment]
Yes! Fixed by PEP-688.
