### ISSUE TITLE
exception error in _scproxy.so when called after fork

### ISSUE THREAD

**Issue by 720022a9-ff7b-48e4-b36b-b0ab66b9caeb** [python/cpython#58037]
BPO | [13829](https://bugs.python.org/issue13829)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @bitdancer, @evanj, @grimreaper, @willingc, @PythonCoderAS
Files | <li>[debug_urlopen.py](https://bugs.python.org/file47503/debug_urlopen.py "Uploaded as text/plain at 2018-03-27.18:28:30 by triccare triccare")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-01-19.18:42:02.027>
labels = ['OS-mac', '3.7', '3.8', 'type-crash']
title = 'exception error in _scproxy.so when called after fork'
updated_at = <Date 2020-11-09.09:02:42.368>
user = 'https://bugs.python.org/Dankamp'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-09.09:02:42.368>
actor = 'ronaldoussoren'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2012-01-19.18:42:02.027>
creator = 'Dan.kamp'
dependencies = []
files = ['47503']
hgrepos = []
issue_num = 13829
keywords = []
message_count = 16.0
messages = ['151648', '151705', '151706', '151736', '151773', '151831', '181426', '181427', '182341', '192440', '269109', '269174', '272109', '314543', '355808', '380577']
nosy_count = 10.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'r.david.murray', 'evanj', 'Julian.Scheid', 'Dan.kamp', 'eitan.adler', 'willingc', 'triccare triccare', 'ThePokestarFan']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'pending'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue13829'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
> I propose closing this as 3th-party or out-of-date:

Done.

**Comment by warsaw** [comment]
I'll bet it's a symptom of [fork-without-exec](https://wefearchange.org/2018/11/forkmacos.rst.html) that I wrote about 3 years ago.  If so, it is not fixable in Python.

**Comment by ronaldoussoren** [comment]
> I'll bet it's a symptom of [fork-without-exec](https://wefearchange.org/2018/11/forkmacos.rst.html) that I wrote about 3 years ago. If so, it is not fixable in Python.

It is.
