### ISSUE TITLE
Summary tables for argparse add_argument options

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#58058]
BPO | [13850](https://bugs.python.org/issue13850)
--- | :---
Nosy | @rhettinger, @ncoghlan, @ezio-melotti, @merwok, @bitdancer, @masklinn, @berkerpeksag, @matrixise
PRs | <li>python/cpython#12070</li>
Files | <li>[argparse-actions-matrix](https://bugs.python.org/file25018/argparse-actions-matrix "Uploaded as text/plain at 2012-03-25.17:21:50 by @masklinn"): matrix of actions for add_argument parameters</li><li>[argparse-actions-matrix-v2](https://bugs.python.org/file38917/argparse-actions-matrix-v2 "Uploaded as text/plain at 2015-04-13.14:56:13 by @matrixise")</li><li>[patch13850v0.patch](https://bugs.python.org/file38966/patch13850v0.patch "Uploaded as text/plain at 2015-04-13.21:07:23 by ttz"): first version of patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-01-24.05:54:57.629>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Summary tables for argparse add_argument options'
updated_at = <Date 2019-03-24.06:00:34.485>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-24.06:00:34.485>
actor = 'matrixise'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2012-01-24.05:54:57.629>
creator = 'ncoghlan'
dependencies = []
files = ['25018', '38917', '38966']
hgrepos = []
issue_num = 13850
keywords = ['patch']
message_count = 22.0
messages = ['151880', '151881', '151889', '151891', '151895', '151918', '151926', '151928', '151930', '156760', '156762', '159565', '223250', '240616', '240617', '240752', '240816', '240817', '336768', '336805', '336814', '338719']
nosy_count = 12.0
nosy_names = ['rhettinger', 'ncoghlan', 'bethard', 'ezio.melotti', 'eric.araujo', 'r.david.murray', 'xmorel', 'docs@python', 'tshepang', 'berker.peksag', 'matrixise', 'ttz']
pr_nums = ['12070']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue13850'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-124227

**Comment by savannahostrowski** [comment]
This is can be closed as completed now as both https://github.com/python/cpython/pull/124227 and https://github.com/python/cpython/pull/91726 have been merged.
