### ISSUE TITLE
tempfile.NamedTemporaryFile not particularly useful on Windows

### ISSUE THREAD

**Issue by 60d03d29-c5b1-42bb-a951-2da3e8114aab** [python/cpython#58451]
BPO | [14243](https://bugs.python.org/issue14243)
--- | :---
Nosy | @pfmoore, @jaraco, @ncoghlan, @pitrou, @ericvsmith, @tjguk, @jwilk, @merwok, @bitdancer, @njsmith, @methane, @dabrahams, @ethanfurman, @sorcio, @vadmium, @zware, @dlenski, @eryksun, @zooba, @ethanhs, @Ev2geny
PRs | <li>python/cpython#22431</li> <li>python/cpython#97015</li>
Files | <li>[ntempfile.py](https://bugs.python.org/file26215/ntempfile.py "Uploaded as text/plain at 2012-06-30.05:45:36 by @dlenski")</li><li>[share.py](https://bugs.python.org/file26229/share.py "Uploaded as text/plain at 2012-07-02.13:34:34 by sbt")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-03-10.02:14:08.216>
labels = ['type-feature', 'library', '3.10', 'OS-windows']
title = 'tempfile.NamedTemporaryFile not particularly useful on Windows'
updated_at = <Date 2021-05-01.01:32:51.852>
user = 'https://github.com/dabrahams'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-01.01:32:51.852>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2012-03-10.02:14:08.216>
creator = 'dabrahams'
dependencies = []
files = ['26215', '26229']
hgrepos = []
issue_num = 14243
keywords = ['patch']
message_count = 83.0
messages = ['155278', '155309', '155316', '155317', '155333', '155365', '155374', '155375', '155457', '157639', '157925', '157927', '157946', '157947', '157948', '157949', '157952', '164358', '164369', '164375', '164392', '164433', '164487', '164495', '164496', '164497', '164503', '164504', '164505', '164509', '164514', '164617', '184053', '184056', '184088', '228371', '244762', '288473', '288504', '288520', '288521', '288538', '288540', '376593', '376645', '376649', '376656', '376659', '376662', '376663', '376664', '376665', '376666', '376684', '376697', '376702', '377580', '390498', '390805', '390806', '390810', '390814', '390888', '390894', '390899', '390903', '390906', '390908', '390911', '392252', '392253', '392257', '392442', '392447', '392470', '392479', '392480', '392483', '392484', '392505', '392511', '392515', '392559']
nosy_count = 26.0
nosy_names = ['paul.moore', 'jaraco', 'ncoghlan', 'pitrou', 'eric.smith', 'tim.golden', 'jwilk', 'eric.araujo', 'r.david.murray', 'njs', 'methane', 'dabrahams', 'ethan.furman', 'davide.rizzo', 'sbt', 'Gabi.Davar', 'martin.panter', 'piotr.dobrogost', 'zach.ware', 'dlenski', 'eryksun', 'steve.dower', 'Carl Osterwisch', 'ethan smith', 'ev2geny', 'chary314']
pr_nums = ['22431']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14243'
versions = ['Python 3.10']
```

</p></details>

**Comment by afad9e83-6c14-4084-a82b-90e46d20c65e** [comment]
I just stumbled onto this though I'm not writing for Windows.  Instead, I'm on Fedora 25 with Python 3.5.2 and I went nearly crazy tracing down what seemed to be inconsistent behavior.  My use case has Python using NamedTemporaryFile(delete=True) in a CM to produce content fed into a subprocess.  The code had been reliably working and then it just didn't.  The only thing changing was the content being written, an rendered Jinja2 template.  I believe the fate is determined by the content length.  In debugging another problem, I'd been trivializing the template and once it got down to about 3k (rendered) the subprocess began seeing a file whose length was 0 bytes.  Make the template bigger and all works again.  Calling close() resolves the issue, but of course requires delete=False which removed much of the value of this object.  Preliminary testing looks like flush() may also resolve the issue.

Have I just been naive and getting lucky all along because this is expected or is there something else fishy here worth investigation?

**Comment by ncoghlan** [comment]
John, your problem sounds different - if you're opening the files in binary mode, then you'll be getting a default buffer that's probably 4k or 8k in size, so if you're writing less content than that, the subprocess won't see anything until you explicitly flush() the buffer to disk (and even if you're writing more than that, the subprocess may see a truncated version without an explicit flush()). 

By contrast, the issue here relates to the fact that on Windows it's currently necessary to do the following in order to get multiple handles to a NamedTemporaryFile:

1. Open the file in the current process
2. Write content to the file
3*. Close the file in the current process
4. Open the file by name in another process (or the current process)
5. Read content from the file
6. Close the second file handle
7*. Delete the file

\*On POSIX systems, you can just skip step 3 and leave closing the original file handle until step 7, and that's the design that the current NamedTemporaryFile is built around. Most of the discussion above is about figuring out how to make that same approach "just work" on Windows (perhaps with some additional flags used in step 4), rather than  providing a third option beyond the current delete-on-close and delete-manually.

**Comment by afad9e83-6c14-4084-a82b-90e46d20c65e** [comment]
Okay Nick. Thanks for the detailed info. I suspected buffering was a factor, but wasn't certain. Would it be worthwhile pursuing a note in the docs or would that constitute clutter over what should be a standard assumption? I was thrown off course for all the prior uses without issues, but in hindsight I don't know offhand how many involved a subprocess.

**Comment by ncoghlan** [comment]
John: I don't think it would be clutter to have an explicit reminder about that point in the NamedTemporaryFile documentation, so feel free to file a separate enhancement issue for it.

**Comment by eryksun** [comment]
Nick wrote:
> 1. Open the file in the current process
> 2. Write content to the file
> 3*. Close the file in the current process

In step 1, do you mean calling NamedTemporaryFile with delete=False? In that case there's no immediate problem with opening the file again in Windows. If you mean calling NamedTemporaryFile with delete=True, then step 3 deletes the file. 

Adding support for Windows share modes would be useful in general and would help within the current process. However, users may also need to open the temporary file in another process. Most programs don't open their files with shared delete access. 

There's a workaround to allow the file to be opened normally, but it involves setting the delete disposition and then clearing it in a pointless dance. It would be better to implement an option such as delete=AFTER_CM_EXIT, to try to remove the file without relying on O_TEMPORARY. The downside is that the file won't be deleted if the interpreter crashes, gets terminated or if another process has the file open without delete sharing.

**Comment by eryksun** [comment]
Richard wrote:
> while a handle is open with share mode X, you can only reopen 
> the file if you also use share mode X

To clarify, the share mode is not a property of a handle. It's a property of a File object. A handle is a generic reference to any kind of kernel object, not just a File.

The following is a brief discussion about access sharing and the way file deletion works in Windows. Both of these tend to frustrate Unix programmers who end up supporting Windows. In this discussion, a "File", with an uppercase 'F', is the Windows kernel object type that references an open device or file-system directory, file, or stream. A "file", with a lowercase 'f', is a data file.

Shared access is implemented for File objects [1] and tracked in a SHARE_ACCESS record. When opening a file or directory, its shared access state is updated by the kernel function IoCheckShareAccess [2]. Discretionary shared access is primarily a concern for file systems, but volume devices and disk devices (e.g. \\\\.\\C: and \\\\.\\PhysicalDrive0) also use it. Devices that are flagged for mandatory exclusive access [3] (e.g. \\\\.\\COM1) generally ignore the share mode. Some non-exclusive devices also ignore the share mode (e.g. \\\\.NUL and \\\\.CON). 

If it's not ignored, the share mode affects delete, write, read, and execute access. The following File access rights are affected: DELETE, FILE_WRITE_DATA, FILE_APPEND_DATA, FILE_READ_DATA, and FILE_EXECUTE. The share mode thus affects any combination of generic access -- GENERIC_ALL, GENERIC_WRITE, GENERIC_READ, GENERIC_EXECUTE. 

A File object's requested sharing is stored in its SharedDelete, SharedWrite, and SharedRead members. The granted access that's relevant to the share mode is stored in the DeleteAccess, WriteAccess (write/append), and ReadAccess (read/execute) members. Given these values, checking for a sharing violation and updating the shared access counts uses the following logic:

```c
    RequireSharedDelete = DeleteAccessCount > 0;
    RequireSharedWrite = WriteAccessCount > 0;
    RequireSharedRead = ReadAccessCount > 0;
    DenyDeleteAccess = SharedDeleteCount < OpenCount;
    DenyWriteAccess = SharedWriteCount < OpenCount;
    DenyReadAccess = SharedReadCount < OpenCount;
    
    if (RequireSharedDelete && !SharedDelete ||
        RequireSharedWrite && !SharedWrite ||
        RequireSharedRead && !SharedRead ||
        DenyDeleteAccess && DeleteAccess ||
        DenyWriteAccess && WriteAccess ||
        DenyReadAccess && ReadAccess)
    {
        return STATUS_SHARING_VIOLATION;
    }
```


    OpenCount++;
    DeleteAccessCount += DeleteAccess;
    WriteAccessCount += WriteAccess;
    ReadAccessCount += ReadAccess;
    SharedDeleteCount += SharedDelete;
    SharedWriteCount += SharedWrite;
    SharedReadCount += SharedRead;

For example, to be granted delete access, all existing File object references must share delete access. However, if a file is opened with delete sharing but delete access hasn't been granted, then it can be opened again without delete sharing.

The SHARE_ACCESS structure is usually stored in a file (or stream) control block (FCB/SCB), which is a structure that coordinates access to a file or directory across multiple File objects. The FsContext member of a File object points at the FCB. 

A file system stores its private state for a File in a context control block (CCB), to which the File's FsContext2 member points. The CCB is where a file system tracks, for example, whether the file should be deleted when the object is closed. 

Deleting a file sets a delete disposition in the FCB/SCB (or LCB if hard links are supported). The file can't be unlinked until all referencing File objects have been closed and the underlying FCB/SCB/LCB is closing. Until then a 'deleted' file is still linked in the parent directory and prevents the directory from being deleted.

A deleted but still referenced file is in a semi-zombie state. Windows file systems don't allow opening such a file for any access, but it can still be accessed via existing objects. If one of these File objects has delete access, it can be used to unset the delete disposition (e.g. via SetFileInformationByHandle) to make the file accessible again.

[1]: https://msdn.microsoft.com/en-us/library/ff545834
[2]: https://msdn.microsoft.com/en-us/library/ff548341
[3]: https://msdn.microsoft.com/en-us/library/ff563827

**Comment by zware** [comment]
As far as I can tell, this was fixed with the merge of GH-97015.
