### ISSUE TITLE
More test coverage for hmac

### ISSUE THREAD

**Issue by d1563a69-7ad6-4024-9671-2a3f675304cf** [python/cpython#58530]
BPO | [14322](https://bugs.python.org/issue14322)
--- | :---
Nosy | @eamanu, @iritkatriel, @CCLDArjun
PRs | <li>python/cpython#26636</li>
Files | <li>[test_hmac.patch](https://bugs.python.org/file24865/test_hmac.patch "Uploaded as text/plain at 2012-03-15.17:13:28 by packetslave"): Old</li><li>[test_hmac.patch](https://bugs.python.org/file24896/test_hmac.patch "Uploaded as text/plain at 2012-03-17.04:17:37 by packetslave")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-03-15.17:13:28.755>
labels = ['easy', '3.8', '3.9', '3.10', 'library', 'type-feature', 'tests']
title = 'More test coverage for hmac'
updated_at = <Date 2021-06-17.11:49:39.078>
user = 'https://bugs.python.org/packetslave'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-17.11:49:39.078>
actor = 'eamanu'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2012-03-15.17:13:28.755>
creator = 'packetslave'
dependencies = []
files = ['24865', '24896']
hgrepos = []
issue_num = 14322
keywords = ['patch', 'easy']
message_count = 9.0
messages = ['155913', '156041', '156134', '156758', '172265', '221970', '379374', '395484', '395593']
nosy_count = 3.0
nosy_names = ['eamanu', 'iritkatriel', 'CCLDArjun']
pr_nums = ['26636']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14322'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by hugovk** [comment]
Thanks @CCLDArjun for GH-26636! It's merged, let's close this issue.

For further coverage improvements to hmac, we can re-use/re-open this issue or create a new one.
