### ISSUE TITLE
argparse: subparsers, argument abbreviations and ambiguous option

### ISSUE THREAD

**Issue by dc77e73f-34fd-4b9a-a1e6-be964f19ab84** [python/cpython#58573]
BPO | [14365](https://bugs.python.org/issue14365)
--- | :---
Nosy | @merwok
Files | <li>[argparse_subparsers_ambiguous_bug.py](https://bugs.python.org/file24928/argparse_subparsers_ambiguous_bug.py "Uploaded as text/plain at 2012-03-18.20:27:59 by jakub"): Bug reproduction</li><li>[argparse_dirty_hack.py](https://bugs.python.org/file24945/argparse_dirty_hack.py "Uploaded as text/plain at 2012-03-19.18:10:15 by jakub")</li><li>[subparser_optionals.diff](https://bugs.python.org/file26466/subparser_optionals.diff "Uploaded as text/plain at 2012-07-21.20:02:48 by bethard")</li><li>[subparser_patch.diff](https://bugs.python.org/file31901/subparser_patch.diff "Uploaded as text/plain at 2013-09-29.04:30:27 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-03-18.20:27:59.700>
labels = ['type-bug', 'library']
title = 'argparse: subparsers, argument abbreviations and ambiguous option'
updated_at = <Date 2014-08-07.22:47:31.748>
user = 'https://bugs.python.org/jakub'
```

bugs.python.org fields:
```python
activity = <Date 2014-08-07.22:47:31.748>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-03-18.20:27:59.700>
creator = 'jakub'
dependencies = []
files = ['24928', '24945', '26466', '31901']
hgrepos = []
issue_num = 14365
keywords = ['patch']
message_count = 14.0
messages = ['156272', '156279', '156280', '156290', '156302', '156304', '156306', '156352', '166059', '198456', '198507', '198508', '198563', '225044']
nosy_count = 5.0
nosy_names = ['bethard', 'eric.araujo', 'tshepang', 'paul.j3', 'jakub']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14365'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3']
```

</p></details>

### Linked PRs
* gh-124631
* gh-124759
* gh-124760

**Comment by Conchylicultor** [comment]
It's 2022 and I'm still affected by this.

```python
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("--flagA", type=str)
parser.add_argument("--flagB", type=str)
subparser = parser.add_subparsers(title="command")
build_parser = subparser.add_parser("build")
build_parser.add_argument("--flag", type=str)

parser.parse_args(["build", "--flag=asd"])
```
Raises
```
debug_flags.py: error: ambiguous option: --flag=asd could match --flagA, --flagB
```

**Comment by serhiy-storchaka** [comment]
#124631 fixes this issue by delaying the check for ambiguous options until the option been consumed. The option for subparser is consumed by the subparser, not the parent parser, so it is no longer error.
