### ISSUE TITLE
Argparse incorrectly handles '--' as argument to option

### ISSUE THREAD

**Issue by eb124d96-f186-4a94-9acb-5e04fc7f01dc** [python/cpython#58572]
BPO | [14364](https://bugs.python.org/issue14364)
--- | :---
Nosy | @rhettinger, @merwok, @bitdancer, @mmaker, @vadmium, @shihai1991, @horazont
PRs | <li>python/cpython#15714</li>
Files | <li>[foo.py](https://bugs.python.org/file24926/foo.py "Uploaded as text/plain at 2012-03-18.14:29:12 by @mmaker")</li><li>[issue14364.test.patch](https://bugs.python.org/file29938/issue14364.test.patch "Uploaded as text/plain at 2013-04-19.08:12:09 by @mmaker")</li><li>[dbldash.patch](https://bugs.python.org/file45944/dbldash.patch "Uploaded as text/plain at 2016-12-17.17:52:20 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-03-18.14:29:12.929>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = "Argparse incorrectly handles '--' as argument to option"
updated_at = <Date 2021-03-23.01:07:11.301>
user = 'https://github.com/mmaker'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-23.01:07:11.301>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-03-18.14:29:12.929>
creator = 'maker'
dependencies = []
files = ['24926', '29938', '45944']
hgrepos = []
issue_num = 14364
keywords = ['patch', 'needs review']
message_count = 17.0
messages = ['156254', '156256', '156275', '156293', '187283', '187344', '187346', '187349', '262545', '262558', '283501', '351230', '353865', '354001', '354049', '354066', '389361']
nosy_count = 9.0
nosy_names = ['rhettinger', 'bethard', 'eric.araujo', 'r.david.murray', 'maker', 'martin.panter', 'paul.j3', 'shihai1991', 'jssfr']
pr_nums = ['15714']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14364'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by vadmium** [comment]
I expect this is now fixed for 3.11+ via #109475
