### ISSUE TITLE
Suggestion to improve argparse's help messages for "store_const"

### ISSUE THREAD

**Issue by de93e8c0-0749-4cb3-a0be-cb16cee3a389** [python/cpython#58709]
BPO | [14504](https://bugs.python.org/issue14504)
--- | :---
Files | <li>[demo.py](https://bugs.python.org/file25129/demo.py "Uploaded as text/plain at 2012-04-05.08:34:11 by Amnon.Harel")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-04-05.08:34:11.730>
labels = ['type-feature', 'library']
title = 'Suggestion to improve argparse\'s help messages for "store_const"'
updated_at = <Date 2012-07-21.20:38:59.314>
user = 'https://bugs.python.org/AmnonHarel'
```

bugs.python.org fields:
```python
activity = <Date 2012-07-21.20:38:59.314>
actor = 'bethard'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-04-05.08:34:11.730>
creator = 'Amnon.Harel'
dependencies = []
files = ['25129']
hgrepos = []
issue_num = 14504
keywords = []
message_count = 2.0
messages = ['157554', '166064']
nosy_count = 2.0
nosy_names = ['bethard', 'Amnon.Harel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14504'
versions = ['Python 3.3']
```

</p></details>

**Comment by terryjreedy** [comment]
@iritkatriel @rhettinger Either of you have opinion on this? Close?

**Comment by iritkatriel** [comment]
I don't think the proposal makes the help easier to read. I find this pretty confusing:

`-H, --hammer use a hammer (default: wrench)`

So I'm -1 on this.
