### ISSUE TITLE
Allow multilevel subdirectories in cgi_directories

### ISSUE THREAD

**Issue by b5a9ce10-d67f-478f-ab78-b08d099eb753** [python/cpython#58770]
BPO | [14565](https://bugs.python.org/issue14565)
--- | :---
Nosy | @orsenthil, @PierreQuentel, @vadmium
Files | <li>[CGIHTTPServer.patch](https://bugs.python.org/file26684/CGIHTTPServer.patch "Uploaded as text/plain at 2012-08-04.11:49:24 by oscar.campos"): Patch for CGIHTTPServer - Py2.7</li><li>[http-server.patch](https://bugs.python.org/file26685/http-server.patch "Uploaded as text/plain at 2012-08-04.11:50:10 by oscar.campos"): Patch for http.server Py3.2</li><li>[http-server.patch](https://bugs.python.org/file26686/http-server.patch "Uploaded as text/plain at 2012-08-04.13:01:52 by oscar.campos"): Patch for http.server (default branch)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-04-12.18:21:06.080>
labels = ['type-feature', 'library']
title = 'Allow multilevel subdirectories in cgi_directories'
updated_at = <Date 2015-10-03.11:46:04.807>
user = 'https://bugs.python.org/vpython'
```

bugs.python.org fields:
```python
activity = <Date 2015-10-03.11:46:04.807>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-04-12.18:21:06.080>
creator = 'v+python'
dependencies = []
files = ['26684', '26685', '26686']
hgrepos = []
issue_num = 14565
keywords = ['patch']
message_count = 12.0
messages = ['158158', '158163', '160062', '160111', '160119', '160169', '160187', '167402', '167420', '252076', '252175', '252206']
nosy_count = 5.0
nosy_names = ['orsenthil', 'v+python', 'quentel', 'martin.panter', 'oscar.campos']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14565'
versions = ['Python 3.6']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/) and further no improvements or bug fixes will be made to the module.
