### ISSUE TITLE
TypeError: truncate() takes no keyword arguments

### ISSUE THREAD

**Issue by 14258245-1f58-40f0-99ff-e97d21101aa5** [python/cpython#58791]
BPO | [14586](https://bugs.python.org/issue14586)
--- | :---
Nosy | @birkenfeld, @pitrou, @bitdancer, @berkerpeksag, @vadmium
Files | <li>[test.py](https://bugs.python.org/file25219/test.py "Uploaded as text/plain at 2012-04-15.02:04:32 by TheBiggerGuy"): Test file</li><li>[truncate.ver1.patch](https://bugs.python.org/file25246/truncate.ver1.patch "Uploaded as text/plain at 2012-04-16.21:56:04 by TheBiggerGuy"): First Version allowing both positional and keyword parameters</li><li>[truncate.ver2.patch](https://bugs.python.org/file25251/truncate.ver2.patch "Uploaded as text/plain at 2012-04-17.09:40:30 by TheBiggerGuy"): Second Version (still needs work)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-04-15.02:04:32.463>
labels = ['interpreter-core', 'type-bug', '3.10', 'docs']
title = 'TypeError: truncate() takes no keyword arguments'
updated_at = <Date 2020-12-15.23:28:33.148>
user = 'https://bugs.python.org/TheBiggerGuy'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-15.23:28:33.148>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Interpreter Core']
creation = <Date 2012-04-15.02:04:32.463>
creator = 'TheBiggerGuy'
dependencies = []
files = ['25219', '25246', '25251']
hgrepos = []
issue_num = 14586
keywords = ['patch']
message_count = 14.0
messages = ['158308', '158388', '158403', '158410', '158494', '158495', '158507', '158509', '158513', '158535', '158547', '158548', '244937', '251139']
nosy_count = 7.0
nosy_names = ['georg.brandl', 'pitrou', 'r.david.murray', 'docs@python', 'berker.peksag', 'martin.panter', 'TheBiggerGuy']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14586'
versions = ['Python 3.10']
```

</p></details>

**Comment by slateny** [comment]
Fixed per #91950
