### ISSUE TITLE
spurious stat() calls in importlib

### ISSUE THREAD

**Issue by pitrou** [python/cpython#58809]
BPO | [14604](https://bugs.python.org/issue14604)
--- | :---
Nosy | @pitrou, @tiran, @ericsnowcurrently

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-04-17.11:58:51.304>
labels = ['library', 'performance']
title = 'spurious stat() calls in importlib'
updated_at = <Date 2020-01-29.00:55:27.014>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-29.00:55:27.014>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-04-17.11:58:51.304>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 14604
keywords = []
message_count = 2.0
messages = ['158546', '158910']
nosy_count = 4.0
nosy_names = ['pitrou', 'christian.heimes', 'neologix', 'eric.snow']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue14604'
versions = ['Python 3.3']
```

</p></details>

**Comment by iritkatriel** [comment]
This issue has been idle for over a decade. I will close it unless someone indicates that they still want to go back to it.

**Comment by brettcannon** [comment]
I'm going to preemptively close this as any perf improvements around this have either already been done or are not important enough to be a concern.
