### ISSUE TITLE
Pdb does not stop at a breakpoint

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#58956]
BPO | [14751](https://bugs.python.org/issue14751)
--- | :---
Nosy | @xdegaye
Files | <li>[pdb_default.patch](https://bugs.python.org/file25494/pdb_default.patch "Uploaded as text/plain at 2012-05-08.13:00:17 by @xdegaye")</li><li>[pdb_default_2.patch](https://bugs.python.org/file25561/pdb_default_2.patch "Uploaded as text/plain at 2012-05-13.15:48:49 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-08.13:00:17.907>
labels = ['type-bug', 'library']
title = 'Pdb does not stop at a breakpoint'
updated_at = <Date 2012-05-13.15:48:49.831>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2012-05-13.15:48:49.831>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-05-08.13:00:17.907>
creator = 'xdegaye'
dependencies = []
files = ['25494', '25561']
hgrepos = []
issue_num = 14751
keywords = ['patch']
message_count = 2.0
messages = ['160202', '160518']
nosy_count = 1.0
nosy_names = ['xdegaye']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14751'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3']
```

</p></details>

### Linked PRs
* gh-124454
* gh-125548
* gh-125549

**Comment by gaogaotiantian** [comment]
Fixed in #124454
