### ISSUE TITLE
INCA: Inline Caching meets Quickening in Python 3.3

### ISSUE THREAD

**Issue by 53b19d1c-5499-4dec-b629-68ee58faee99** [python/cpython#58962]
BPO | [14757](https://bugs.python.org/issue14757)
--- | :---
Nosy | @gvanrossum, @pitrou, @vstinner, @jab, @davidmalcolm, @meadori, @ericsnowcurrently, @1st1
Files | <li>[20120508-inca.patch](https://bugs.python.org/file25499/20120508-inca.patch "Uploaded as text/plain at 2012-05-08.17:37:43 by sbrunthaler"): Patch against 2f563908ebc5 (Jesus Cea, Thu Apr 26 17:05:31 2012 +0200)</li><li>[20120511-inca.patch](https://bugs.python.org/file25541/20120511-inca.patch "Uploaded as text/plain at 2012-05-11.21:32:08 by sbrunthaler"): Patches CALL_FUNCTION quickening, supersedes previous patch file.</li><li>[20120511-inca-perf.txt](https://bugs.python.org/file25542/20120511-inca-perf.txt "Uploaded as text/plain at 2012-05-11.21:34:01 by sbrunthaler"): perf.py performance on i7-920, Linux 3.0.0-19</li><li>[20120510-vanilla-perf.txt](https://bugs.python.org/file25543/20120510-vanilla-perf.txt "Uploaded as text/plain at 2012-05-11.21:35:03 by sbrunthaler"): perf.py performance baseline measurement on i7-920, Linux 3.0.0-19</li><li>[20120514-inca.patch](https://bugs.python.org/file25586/20120514-inca.patch "Uploaded as text/plain at 2012-05-14.20:31:29 by sbrunthaler"): Patch including quickening of INPLACE_* instructions, supersedes previous patch file (20120511-inca.patch)</li><li>[20120514-inca-perf.txt](https://bugs.python.org/file25588/20120514-inca-perf.txt "Uploaded as text/plain at 2012-05-14.20:39:01 by sbrunthaler"): perf.py results including INPLACE_* quickening; 12 repetitions on i7-920, summarized</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-08.17:37:54.816>
labels = ['interpreter-core', 'performance']
title = 'INCA: Inline Caching meets Quickening in Python 3.3'
updated_at = <Date 2021-10-08.15:39:59.203>
user = 'https://bugs.python.org/sbrunthaler'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-08.15:39:59.203>
actor = 'gvanrossum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2012-05-08.17:37:54.816>
creator = 'sbrunthaler'
dependencies = []
files = ['25499', '25541', '25542', '25543', '25586', '25588']
hgrepos = ['124']
issue_num = 14757
keywords = ['patch']
message_count = 13.0
messages = ['160216', '160222', '160224', '160225', '160228', '160230', '160453', '160457', '160666', '160870', '160881', '275492', '403482']
nosy_count = 10.0
nosy_names = ['gvanrossum', 'pitrou', 'vstinner', 'jab', 'cvrebert', 'dmalcolm', 'meador.inge', 'eric.snow', 'sbrunthaler', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue14757'
versions = ['Python 3.3']
```

</p></details>

**Comment by iritkatriel** [comment]
I'm closing this issue as the discussion has moved to the faster-cpython repo, and there is no further action to take here.

**Comment by vstinner** [comment]
Python 3.11 and Python 3.12 implement [PEP 659: Specializing Adaptive Interpreter](https://peps.python.org/pep-0659/)  instead.
