### ISSUE TITLE
setup.py only adds /prefix/lib, not /prefix/lib64

### ISSUE THREAD

**Issue by pitrou** [python/cpython#58996]
BPO | [14791](https://bugs.python.org/issue14791)
--- | :---
Nosy | @doko42, @jcea, @pitrou, @ned-deily, @davidmalcolm, @iritkatriel
Files | <li>[setup_lib64.patch](https://bugs.python.org/file25551/setup_lib64.patch "Uploaded as text/plain at 2012-05-12.16:40:42 by @pitrou")</li><li>[setup.diff](https://bugs.python.org/file26313/setup.diff "Uploaded as text/plain at 2012-07-08.00:24:11 by @doko42")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-12.16:40:42.512>
labels = ['3.10', 'type-bug', '3.8', '3.9', 'build']
title = 'setup.py only adds /prefix/lib, not /prefix/lib64'
updated_at = <Date 2020-11-07.10:02:02.370>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-07.10:02:02.370>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2012-05-12.16:40:42.512>
creator = 'pitrou'
dependencies = []
files = ['25551', '26313']
hgrepos = []
issue_num = 14791
keywords = ['patch']
message_count = 6.0
messages = ['160478', '160483', '164956', '164965', '380458', '380492']
nosy_count = 7.0
nosy_names = ['doko', 'jcea', 'pitrou', 'ned.deily', 'Arfrever', 'dmalcolm', 'iritkatriel']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14791'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`setup.py` no longer used to build CPython since 3.12 (see #94474).
