### ISSUE TITLE
Pdb does not stop at a breakpoint set on the line of a function definition

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#59013]
BPO | [14808](https://bugs.python.org/issue14808)
--- | :---
Nosy | @birkenfeld, @xdegaye
Files | <li>[pdb_default.patch](https://bugs.python.org/file25578/pdb_default.patch "Uploaded as text/plain at 2012-05-14.15:36:58 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-14.15:36:58.639>
labels = ['type-bug', 'library']
title = 'Pdb does not stop at a breakpoint set on the line of a function definition'
updated_at = <Date 2012-05-25.11:56:43.789>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2012-05-25.11:56:43.789>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-05-14.15:36:58.639>
creator = 'xdegaye'
dependencies = []
files = ['25578']
hgrepos = []
issue_num = 14808
keywords = ['patch']
message_count = 2.0
messages = ['160629', '161574']
nosy_count = 2.0
nosy_names = ['georg.brandl', 'xdegaye']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14808'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3']
```

</p></details>

### Linked PRs
* gh-110582
* gh-112470

**Comment by gaogaotiantian** [comment]
With #110852, `break func` will assign the correct line number for function that is already defined.

**Comment by hugovk** [comment]
Fixed by https://github.com/python/cpython/pull/110582, thanks!

**Comment by gaogaotiantian** [comment]
Actually, there's still a case that's inconsistent. I did not figure out a solution then but I have a patch now. Let's reopen this and close it after the new PR is merged.

**Comment by gaogaotiantian** [comment]
With #112470 merged, this problem is fully fixed.
