### ISSUE TITLE
argparse: creating an already defined subparsers does not raises an exception

### ISSUE THREAD

**Issue by c954cffc-fb7c-4758-b351-de69dfb87859** [python/cpython#59061]
BPO | [14856](https://bugs.python.org/issue14856)
--- | :---
Nosy | @bitdancer, @bradengroom, @iritkatriel
PRs | <li>python/cpython#10159</li><li>python/cpython#10159</li><li>python/cpython#10159</li>
Files | <li>[argparse_no_dup_subparsers.diff](https://bugs.python.org/file25637/argparse_no_dup_subparsers.diff "Uploaded as text/plain at 2012-05-19.12:27:50 by eacb")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-19.12:27:50.832>
labels = ['type-feature', 'library', '3.11']
title = 'argparse: creating an already defined subparsers does not raises an exception'
updated_at = <Date 2021-12-02.23:11:09.228>
user = 'https://bugs.python.org/eacb'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-02.23:11:09.228>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-05-19.12:27:50.832>
creator = 'eacb'
dependencies = []
files = ['25637']
hgrepos = []
issue_num = 14856
keywords = ['patch']
message_count = 5.0
messages = ['161112', '161359', '166087', '328667', '407555']
nosy_count = 5.0
nosy_names = ['bethard', 'r.david.murray', 'eacb', 'bradengroom', 'iritkatriel']
pr_nums = ['10159', '10159', '10159']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14856'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Adding a parser with a name or an alias that matches an existing parser was forbidden in bpo-39716 (gh-83897).
