### ISSUE TITLE
PyRun_InteractiveLoop fails to run interactively when using a Linux pty that's not tied to stdin/stdout

### ISSUE THREAD

**Issue by 0993b773-768a-4be1-b651-8aae35cfe5e3** [python/cpython#59121]
BPO | [14916](https://bugs.python.org/issue14916)
--- | :---
Nosy | @pmp-p, @miss-islington
PRs | <li>python/cpython#22190</li><li>python/cpython#31006</li><li>python/cpython#31065</li>
Files | <li>[working.c](https://bugs.python.org/file25706/working.c "Uploaded as text/plain at 2012-05-25.15:42:37 by Kevin.Barry"): A test program that hopefully causes the behavior described. You need xterm, and libreadline and libncurses (with the respective headers.)</li><li>[Python-2.6.8-Run_Interactive-fix.patch](https://bugs.python.org/file26491/Python-2.6.8-Run_Interactive-fix.patch "Uploaded as text/plain at 2012-07-24.01:26:29 by Kevin.Barry")</li><li>[working2.c](https://bugs.python.org/file26492/working2.c "Uploaded as text/plain at 2012-07-24.01:39:08 by Kevin.Barry"): A test program to be used with a version of Python built with the patch (Python-2.6.8-Run_Interactive-fix.patch) above.</li><li>[Python-2.6.6-Run_Interactive-fix.patch](https://bugs.python.org/file26501/Python-2.6.6-Run_Interactive-fix.patch "Uploaded as text/plain at 2012-07-24.15:46:27 by Kevin.Barry"): The second iteration of a patch to fix interactivity from the C API.</li><li>[working3.c](https://bugs.python.org/file26503/working3.c "Uploaded as text/plain at 2012-07-24.15:54:23 by Kevin.Barry"): A simplified version of the previous example that demonstrates the problem (before patch) and proper functionality (after patch.)</li><li>[bug.sh](https://bugs.python.org/file29432/bug.sh "Uploaded as application/x-shellscript at 2013-03-17.20:44:03 by emmanuel")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-05-25.15:42:37.991>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.7', 'library']
title = "PyRun_InteractiveLoop fails to run interactively when using a Linux pty that's not tied to stdin/stdout"
updated_at = <Date 2022-02-03.23:32:27.732>
user = 'https://bugs.python.org/KevinBarry'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-03.23:32:27.732>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2012-05-25.15:42:37.991>
creator = 'Kevin.Barry'
dependencies = []
files = ['25706', '26491', '26492', '26501', '26503', '29432']
hgrepos = []
issue_num = 14916
keywords = ['patch']
message_count = 19.0
messages = ['161586', '166258', '166259', '166301', '166303', '172411', '184395', '184399', '184403', '184410', '184537', '184812', '185144', '185229', '185250', '252224', '376640', '412317', '412486']
nosy_count = 5.0
nosy_names = ['pmpp', 'Kevin.Barry', 'emmanuel', 'Yauheni Kaliuta', 'miss-islington']
pr_nums = ['22190', '31006', '31065']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue14916'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been fixed
