### ISSUE TITLE
PyLong_FromString documentation should state that the string must be null-terminated

### ISSUE THREAD

**Issue by cec27142-3e69-4559-b1f3-dfb15f5b4183** [python/cpython#59200]
BPO | [14995](https://bugs.python.org/issue14995)
--- | :---
Nosy | @Rosuav, @MojoVampire, @Cryvate, @Cryvate
PRs | <li>python/cpython#26774</li>
Files | <li>[PyLong_FromString-doc.patch](https://bugs.python.org/file25812/PyLong_FromString-doc.patch "Uploaded as text/plain at 2012-06-04.00:32:51 by rfk")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-06-04.00:32:52.870>
labels = ['easy', '3.11', 'type-feature', 'docs']
title = 'PyLong_FromString documentation should state that the string must be null-terminated'
updated_at = <Date 2021-06-18.04:13:42.001>
user = 'https://bugs.python.org/rfk'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-18.04:13:42.001>
actor = 'josh.r'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2012-06-04.00:32:52.870>
creator = 'rfk'
dependencies = []
files = ['25812']
hgrepos = []
issue_num = 14995
keywords = ['patch', 'easy']
message_count = 3.0
messages = ['162242', '212559', '396032']
nosy_count = 6.0
nosy_names = ['rfk', 'docs@python', 'Rosuav', 'josh.r', 'Cryvate', 'cryvate']
pr_nums = ['26774']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue14995'
versions = ['Python 3.11']
```

</p></details>

**Comment by JustAnotherArchivist** [comment]
Has it been considered to instead change the function to fit its description, i.e. *not* require a NULL-terminated string? I have a use case that would benefit from this (decoding arbitrary ints when parsing JSON without `memcpy` or mangling to insert a `NUL`).

**Comment by Rosuav** [comment]
It's documented as taking a `const char *` bytestring, which is C's standard NUL-terminated string. The current behaviour does fit the documentation. If you want a version that doesn't require a `\0` at the end of the string, you'd probably do best to write it as a more restricted function (eg no support for bases other than 10, unless that is actually a requirement).

**Comment by JustAnotherArchivist** [comment]
@Rosuav No, the behaviour does not fit the documentation. The problem isn't the end of `str` but that the string might contain more than just the number to be parsed. The documentation implies that `"1234 foo"` should be parseable, resulting in an `int(1234)` and `**pend` pointing at the `f`. Instead, the function expects a NUL immediately after the int (and any optional whitespace). And that is not what the documentation says.

**Comment by Rosuav** [comment]
Hmm, I'm not convinced that it implies that `"1234 foo"` is parseable. But if there is an issue, it's one with documentation clarity, not with the code failing to fit the specification.

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed
