### ISSUE TITLE
argparse: nargs='*' positional argument doesn't accept any items if preceded by an option and another positional

### ISSUE THREAD

**Issue by 5f2d8a61-4b19-43bf-9ffd-44f07bbdd0ef** [python/cpython#59317]
BPO | [15112](https://bugs.python.org/issue15112)
--- | :---
Nosy | @cjerdonek, @vadmium
Files | <li>[argparse_fix_empty_nargs_star.patch](https://bugs.python.org/file26097/argparse_fix_empty_nargs_star.patch "Uploaded as text/plain at 2012-06-22.21:54:42 by waltermundt"): Proposed fix</li><li>[15112.patch](https://bugs.python.org/file26485/15112.patch "Uploaded as text/plain at 2012-07-22.21:53:46 by bethard")</li><li>[mixed.patch](https://bugs.python.org/file31457/mixed.patch "Uploaded as text/plain at 2013-08-25.02:11:57 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-06-20.04:15:47.146>
labels = ['type-bug', 'library']
title = "argparse: nargs='*' positional argument doesn't accept any items if preceded by an option and another positional"
updated_at = <Date 2018-06-30.21:19:15.871>
user = 'https://bugs.python.org/waltermundt'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-30.21:19:15.871>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-06-20.04:15:47.146>
creator = 'waltermundt'
dependencies = []
files = ['26097', '26485', '31457']
hgrepos = []
issue_num = 15112
keywords = ['patch']
message_count = 14.0
messages = ['163249', '163497', '166173', '178481', '196066', '196112', '196434', '221999', '226315', '226316', '226320', '243453', '262842', '320808']
nosy_count = 9.0
nosy_names = ['bethard', 'gfxmonk', 'devurandom', 'chris.jerdonek', 'tshepang', 'martin.panter', 'paul.j3', 'waltermundt', 'leonard.gerard']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue15112'
versions = ['Python 2.7', 'Python 3.2', 'Python 3.3', 'Python 3.4']
```

</p></details>

### Linked PRs
* gh-124303
* gh-124436
* gh-124437

**Comment by serhiy-storchaka** [comment]
Unfortunately, such solution does not help in the positional argument with nargs='*' if followed by an option and another positional argument:
```py
from argparse import *

parser = ArgumentParser()
parser.add_argument('-x', action='store_true')
parser.add_argument('y', nargs='*')
parser.add_argument('z')

parser.parse_args('yy -x zz'.split(' '))
```
I tried the variant that fixes it, but it breaks other cases, which look more common. Solution that would support all cases requires complete rewriting the argparse code. I think that we should accept a simpler imperfect solution (which can be qualified as a bugfix) until we get a perfect solution.

`parse_intermixed_args()` does not support PARSER and REMAINDER. It is a bunch of hacks and is not thread-safe.

**Comment by serhiy-storchaka** [comment]
Closing as the original case was fixed, and more general solution waits its time.
