### ISSUE TITLE
Optimize BytesIO to do  less reallocations when written, similarly to StringIO

### ISSUE THREAD

**Issue by 786d3f11-b763-4414-a03f-abc264e0b72d** [python/cpython#59586]
BPO | [15381](https://bugs.python.org/issue15381)
--- | :---
Nosy | @ncoghlan, @pitrou, @scoder, @vstinner, @benjaminp, @meadori, @berkerpeksag, @hynek, @dw, @serhiy-storchaka
Files | <li>[bytesio_resized_bytes-2.patch](https://bugs.python.org/file26461/bytesio_resized_bytes-2.patch "Uploaded as text/plain at 2012-07-20.20:30:26 by @serhiy-storchaka")</li><li>[bytesio_resized_bytes-3.patch](https://bugs.python.org/file32536/bytesio_resized_bytes-3.patch "Uploaded as text/plain at 2013-11-07.17:33:42 by @serhiy-storchaka")</li><li>[bytesio_resized_bytes-4.patch](https://bugs.python.org/file36180/bytesio_resized_bytes-4.patch "Uploaded as text/plain at 2014-07-31.15:00:17 by @serhiy-storchaka")</li><li>[bytesio_faster_readline.patch](https://bugs.python.org/file36369/bytesio_faster_readline.patch "Uploaded as text/plain at 2014-08-14.10:29:21 by @serhiy-storchaka")</li><li>[bytesio_resized_bytes-5.patch](https://bugs.python.org/file36371/bytesio_resized_bytes-5.patch "Uploaded as text/plain at 2014-08-14.20:05:58 by @serhiy-storchaka")</li><li>[bytesio_resized_bytes-6.patch](https://bugs.python.org/file37939/bytesio_resized_bytes-6.patch "Uploaded as text/plain at 2015-01-31.12:23:45 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2012-07-17.12:12:45.969>
labels = ['library', 'performance']
title = 'Optimize BytesIO to do  less reallocations when written, similarly to StringIO'
updated_at = <Date 2019-03-15.22:56:18.774>
user = 'https://bugs.python.org/elibendersky'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-15.22:56:18.774>
actor = 'BreamoreBoy'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-07-17.12:12:45.969>
creator = 'eli.bendersky'
dependencies = []
files = ['26461', '32536', '36180', '36369', '36371', '37939']
hgrepos = []
issue_num = 15381
keywords = ['patch']
message_count = 47.0
messages = ['165715', '165716', '165718', '165748', '165760', '165780', '165795', '165883', '165884', '165901', '165935', '165937', '165976', '165977', '165978', '165979', '165980', '165981', '165995', '166005', '166007', '166008', '166043', '171205', '202374', '203034', '203045', '224409', '225272', '225274', '225276', '225295', '225298', '225306', '225311', '225316', '225317', '225318', '234885', '235103', '235326', '235339', '235340', '235353', '236003', '236007', '236011']
nosy_count = 17.0
nosy_names = ['ncoghlan', 'pitrou', 'scoder', 'vstinner', 'benjamin.peterson', 'stutzbach', 'Arfrever', 'eli.bendersky', 'meador.inge', 'tshepang', 'python-dev', 'jcon', 'berker.peksag', 'hynek', 'dw', 'serhiy.storchaka', 'kmike']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue15381'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
> No, I'm working on more advanced patch.

@serhiy-storchaka are you still planning to work on this?
