### ISSUE TITLE
PEP 3121, 384 refactoring applied to _datetime module

### ISSUE THREAD

**Issue by 732b3c98-2f26-43cc-b130-a731693f141a** [python/cpython#59595]
BPO | [15390](https://bugs.python.org/issue15390)
--- | :---
Nosy | @malemburg, @loewis, @abalkin, @pitrou, @asvetlov, @pganssle, @iritkatriel
Files | <li>[_datetimemodule_pep3121-384_v0.patch](https://bugs.python.org/file26431/_datetimemodule_pep3121-384_v0.patch "Uploaded as text/plain at 2012-07-18.21:33:46 by Robin.Schreiber")</li><li>[_datetimemodule_pep3121-384_v1.patch](https://bugs.python.org/file26803/_datetimemodule_pep3121-384_v1.patch "Uploaded as text/plain at 2012-08-14.18:09:26 by Robin.Schreiber")</li><li>[_datetimemodule_pep3121-384_v2.patch](https://bugs.python.org/file26817/_datetimemodule_pep3121-384_v2.patch "Uploaded as text/plain at 2012-08-15.08:50:18 by Robin.Schreiber")</li><li>[_datetimemodule_pep3121-384_v3.patch](https://bugs.python.org/file28274/_datetimemodule_pep3121-384_v3.patch "Uploaded as text/plain at 2012-12-10.10:39:26 by Robin.Schreiber")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-07-18.21:33:52.042>
labels = ['extension-modules', '3.11', 'performance']
title = 'PEP 3121, 384 refactoring applied to _datetime module'
updated_at = <Date 2021-12-08.15:27:50.710>
user = 'https://bugs.python.org/RobinSchreiber'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-08.15:27:50.710>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2012-07-18.21:33:52.042>
creator = 'Robin.Schreiber'
dependencies = []
files = ['26431', '26803', '26817', '28274']
hgrepos = []
issue_num = 15390
keywords = ['patch', 'pep3121']
message_count = 12.0
messages = ['165805', '166126', '168215', '168218', '168229', '168266', '168334', '170154', '170249', '177274', '177277', '408025']
nosy_count = 8.0
nosy_names = ['lemburg', 'loewis', 'belopolsky', 'pitrou', 'asvetlov', 'Robin.Schreiber', 'p-ganssle', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue15390'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
@RobinSchreiber I'm closing this because, a decade on, the patch is very much out of date. Please create a new issue if you would like to pursue this.
