### ISSUE TITLE
os.chmod() does not follow symlinks on Windows

### ISSUE THREAD

**Issue by f76e6224-bf87-486c-9d7b-4352d21c7be7** [python/cpython#59616]
BPO | [15411](https://bugs.python.org/issue15411)
--- | :---
Nosy | @atsuoishimoto, @tjguk, @asvetlov, @zware
Files | <li>[chmod_symlink_win32.patch](https://bugs.python.org/file26462/chmod_symlink_win32.patch "Uploaded as text/plain at 2012-07-21.08:31:18 by @atsuoishimoto")</li><li>[chmod_symlink_win32_2.patch](https://bugs.python.org/file26464/chmod_symlink_win32_2.patch "Uploaded as text/plain at 2012-07-21.09:49:52 by @atsuoishimoto")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-07-21.08:31:23.124>
labels = ['type-feature', 'library', 'OS-windows']
title = 'os.chmod() does not follow symlinks on Windows'
updated_at = <Date 2019-04-26.19:53:54.688>
user = 'https://github.com/atsuoishimoto'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.19:53:54.688>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2012-07-21.08:31:23.124>
creator = 'ishimoto'
dependencies = []
files = ['26462', '26464']
hgrepos = []
issue_num = 15411
keywords = ['patch']
message_count = 3.0
messages = ['165996', '166003', '223300']
nosy_count = 4.0
nosy_names = ['ishimoto', 'tim.golden', 'asvetlov', 'zach.ware']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue15411'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-113049

**Comment by serhiy-storchaka** [comment]
Unfortunately, the patch by @atsuoishimoto is too old and cannot be applied to the current code. The difference is so larger, that it is easier to write a new code from scratch than try to resolve conflicts iteratively.

Which I did. My PR uses a different approach. Instead of resolving the symlink path, it opens a handle and changes file attributes by the handle (it is the recommended way). In future it may be possible to implement also `os.fchmod()`.

**Comment by serhiy-storchaka** [comment]
Now `os.chmod()` supports `follow_symlinks=True` on Windows. But by default it does not follow symlinks. Few versions later (in 3.15 or later) we can change the default. It will allow users to use `os.lchmod()` or `os.chmod(follow_symlinks=False)` if they need the old behavior, and it will work in several versions.
