### ISSUE TITLE
Eliminate the use of deprecated OS X APIs in getpath.c

### ISSUE THREAD

**Issue by ned-deily** [python/cpython#59703]
BPO | [15498](https://bugs.python.org/issue15498)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily
Files | <li>[issue15498-v1.txt](https://bugs.python.org/file26622/issue15498-v1.txt "Uploaded as text/plain at 2012-07-31.12:03:03 by @ronaldoussoren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ronaldoussoren'
closed_at = None
created_at = <Date 2012-07-30.07:34:24.426>
labels = ['OS-mac', '3.11']
title = 'Eliminate the use of deprecated OS X APIs in getpath.c'
updated_at = <Date 2021-11-27.11:57:12.234>
user = 'https://github.com/ned-deily'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-27.11:57:12.234>
actor = 'iritkatriel'
assignee = 'ronaldoussoren'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2012-07-30.07:34:24.426>
creator = 'ned.deily'
dependencies = []
files = ['26622']
hgrepos = []
issue_num = 15498
keywords = ['needs review']
message_count = 4.0
messages = ['166863', '166991', '173828', '354378']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue15498'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-111546

**Comment by ned-deily** [comment]
Thanks for the PR, @aisk! Merged for release in 3.13.0a2.

**Comment by ned-deily** [comment]
Apparently I didn't test the PR enough. It turns out that the include of `mach-o/dyld.h` is needed to build on older versions of macOS, at least on macOS 10.13 and earlier. Otherwise, `getpath.c` fails with something similar to:

```
./Modules/getpath.c:730:13: error: implicit declaration of function '_NSGetExecutablePath' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]

```
I'm not quite sure why it compiles without error on more recent versions of macOS but, looking at the Apple Open Source site it does appear that they made some significant updates to dyld in more recent releases.

**Comment by chrstphrchvz** [comment]
For a long time, the synopsis section of `man 3 dyld` has said to include `<mach-o/dyld.h>` for the function declaration of `_NSGetExecutablePath()`. This example program does not include that header:

```c
#include <stdint.h>
int main(void){
    char buf[1];
    uint32_t bufsize = 0;
    return _NSGetExecutablePath(buf, &bufsize);
}
```

Compiling this program with LLVM.org Clang 17.0.6 (obtained from MacPorts) emits the expected implicit function declaration error. But compiling it with recent AppleClang (e.g. from Xcode 14.2 or Command Line Tools 15.0) succeeds without warnings or errors. I do not know if this expected AppleClang behavior for `_NSGetExecutablePath()`, or an AppleClang bug. But it is arguably a portability issue and inconsistent with documentation.
