### ISSUE TITLE
cgi.FieldStorage should not call read_multi on files

### ISSUE THREAD

**Issue by 516d41e8-0128-4f37-894d-430a76c97c10** [python/cpython#59769]
BPO | [15564](https://bugs.python.org/issue15564)
--- | :---
Nosy | @orsenthil, @bitdancer, @jshields
Files | <li>[cgibug.py](https://bugs.python.org/file26764/cgibug.py "Uploaded as text/plain at 2012-08-11.13:03:44 by patrick.vrijlandt"): Testscript (requires bottle) and exception traceback</li><li>[test_cgi4.py](https://bugs.python.org/file26780/test_cgi4.py "Uploaded as text/plain at 2012-08-13.09:40:10 by patrick.vrijlandt")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-08-06.09:31:45.694>
labels = ['type-bug', 'library']
title = 'cgi.FieldStorage should not call read_multi on files'
updated_at = <Date 2017-03-13.17:58:31.365>
user = 'https://bugs.python.org/patrickvrijlandt'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-13.17:58:31.365>
actor = 'jshields'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-08-06.09:31:45.694>
creator = 'patrick.vrijlandt'
dependencies = []
files = ['26764', '26780']
hgrepos = []
issue_num = 15564
keywords = []
message_count = 10.0
messages = ['167548', '167921', '167953', '168007', '168016', '168021', '168073', '178750', '254852', '289545']
nosy_count = 7.0
nosy_names = ['orsenthil', 'cboos', 'v+python', 'r.david.murray', 'patrick.vrijlandt', 'mbordas', 'jshields']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue15564'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1556cb30-0131-412e-80c0-1e0671761275** [comment]
I ran into this issue as well. I think it is something cgi.py will need to handle correctly when this type of file is uploaded from a browser's file input.

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/) and further no improvements or bug fixes will be made to the module.
