### ISSUE TITLE
Support OpenCSW in setup.py

### ISSUE THREAD

**Issue by 92935ae4-c5d3-4cd3-81e6-25bec3013308** [python/cpython#59848]
BPO | [15643](https://bugs.python.org/issue15643)
--- | :---
Nosy | @loewis, @merwok
Files | <li>[csw_setup.py.diff](https://bugs.python.org/file26789/csw_setup.py.diff "Uploaded as text/plain at 2012-08-13.22:15:34 by flub")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-08-13.22:15:35.322>
labels = ['type-bug', 'build']
title = 'Support OpenCSW in setup.py'
updated_at = <Date 2012-08-17.18:08:54.814>
user = 'https://bugs.python.org/flub'
```

bugs.python.org fields:
```python
activity = <Date 2012-08-17.18:08:54.814>
actor = 'eric.araujo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2012-08-13.22:15:35.322>
creator = 'flub'
dependencies = []
files = ['26789']
hgrepos = []
issue_num = 15643
keywords = ['patch']
message_count = 3.0
messages = ['168156', '168315', '168455']
nosy_count = 3.0
nosy_names = ['loewis', 'flub', 'eric.araujo']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue15643'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`setup.py` no longer used to build CPython since 3.12 (see #94474).

**Comment by merwok** [comment]
That’s true. If people still want to use opencsw for building CPython, please open a new feature request targetting the current build system.
