### ISSUE TITLE
PEP 3121, 384 Refactoring applied to socket module

### ISSUE THREAD

**Issue by 732b3c98-2f26-43cc-b130-a731693f141a** [python/cpython#59913]
BPO | [15708](https://bugs.python.org/issue15708)
--- | :---
Nosy | @iritkatriel
Files | <li>[socket_pep3121-384_v0.patch](https://bugs.python.org/file26870/socket_pep3121-384_v0.patch "Uploaded as text/plain at 2012-08-16.21:26:26 by Robin.Schreiber")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-08-16.21:26:27.669>
labels = ['extension-modules', '3.11', 'performance']
title = 'PEP 3121, 384 Refactoring applied to socket module'
updated_at = <Date 2021-12-08.15:32:48.434>
user = 'https://bugs.python.org/RobinSchreiber'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-08.15:32:48.434>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2012-08-16.21:26:27.669>
creator = 'Robin.Schreiber'
dependencies = []
files = ['26870']
hgrepos = []
issue_num = 15708
keywords = ['pep3121']
message_count = 2.0
messages = ['168416', '408028']
nosy_count = 2.0
nosy_names = ['Robin.Schreiber', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue15708'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
@RobinSchreiber I'm closing this because, a decade on, the patch is very much out of date. Please create a new issue if you would like to pursue this.
