### ISSUE TITLE
PEP 3121, 384 Refactoring applied to ossaudio module

### ISSUE THREAD

**Issue by 732b3c98-2f26-43cc-b130-a731693f141a** [python/cpython#59940]
BPO | [15735](https://bugs.python.org/issue15735)
--- | :---
Nosy | @iritkatriel
Files | <li>[ossaudiodev_pep3121-384_v0.patch](https://bugs.python.org/file26924/ossaudiodev_pep3121-384_v0.patch "Uploaded as text/plain at 2012-08-20.09:54:59 by Robin.Schreiber")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-08-20.09:55:01.221>
labels = ['extension-modules', '3.11', 'performance']
title = 'PEP 3121, 384 Refactoring applied to ossaudio module'
updated_at = <Date 2021-12-08.15:22:50.982>
user = 'https://bugs.python.org/RobinSchreiber'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-08.15:22:50.982>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2012-08-20.09:55:01.221>
creator = 'Robin.Schreiber'
dependencies = []
files = ['26924']
hgrepos = []
issue_num = 15735
keywords = ['pep3121']
message_count = 2.0
messages = ['168642', '408024']
nosy_count = 2.0
nosy_names = ['Robin.Schreiber', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue15735'
versions = ['Python 3.11']
```

</p></details>

**Comment by AA-Turner** [comment]
The `ossaudiodev` module has now been deprecated and will be removed (see PEP-594 & #91217 for details), closing.

A
