### ISSUE TITLE
[meta issue] PEP 3121, 384 Refactoring

### ISSUE THREAD

**Issue by abalkin** [python/cpython#59991]
BPO | [15787](https://bugs.python.org/issue15787)
--- | :---
Nosy | @loewis, @ncoghlan, @abalkin, @pitrou, @vstinner
Dependencies | <li>bpo-14732: PEP 3121 Refactoring applied to _csv module</li><li>bpo-14935: PEP 384 Refactoring applied to _csv module</li><li>bpo-14936: PEP 3121, 384 refactoring applied to curses_panel module</li><li>bpo-15140: PEP 384 inconsistent with implementation</li><li>bpo-15389: PEP 3121, 384 refactoring applied to curses module</li><li>bpo-15390: PEP 3121, 384 refactoring applied to _datetime module</li><li>bpo-15650: PEP 3121, 384 refactoring applied to dbm module</li><li>bpo-15651: PEP 3121, 384 refactoring applied to elementtree module</li><li>bpo-15652: PEP 3121, 384 refactoring applied to gdbm module</li><li>bpo-15653: PEP 3121, 384 refactoring applied to hashopenssl module</li><li>bpo-15666: PEP 3121, 384 refactoring applied to lzma module</li><li>bpo-15667: PEP 3121, 384 refactoring applied to pickle module</li><li>bpo-15668: PEP 3121, 384 Refactoring applied to random module</li><li>bpo-15669: PEP 3121, 384 Refactoring applied to sre module</li><li>bpo-15670: PEP 3121, 384 Refactoring applied to ssl module</li><li>bpo-15671: PEP 3121, 384 Refactoring applied to struct module</li><li>bpo-15672: PEP 3121, 384 Refactoring applied to testbuffer module</li><li>bpo-15673: PEP 3121, 384 Refactoring applied to testcapi module</li><li>bpo-15674: PEP 3121, 384 Refactoring applied to _thread module</li><li>bpo-15675: PEP 3121, 384 Refactoring applied to array module</li><li>bpo-15680: PEP 3121 refactoring applied to audioop module</li><li>bpo-15681: PEP 3121 refactoring applied to binascii module</li><li>bpo-15682: PEP 3121 refactoring applied to fpectl module</li><li>bpo-15684: PEP 3121 refactoring applied to fpetest module</li><li>bpo-15685: PEP 3121, 384 Refactoring applied to itertools module</li><li>bpo-15686: PEP 3121, 384 Refactoring applied to md5 module</li><li>bpo-15687: PEP 3121, 384 Refactoring applied to mmap module</li><li>bpo-15688: PEP 3121 Refactoring applied to nis module</li><li>bpo-15689: PEP 3121, 384 Refactoring applied to operator module</li><li>bpo-15690: PEP 3121, 384 Refactoring applied to parser module</li><li>bpo-15691: PEP 3121, 384 Refactoring applied to posix module</li><li>bpo-15697: PEP 3121 refactoring applied to pwd module</li><li>bpo-15698: PEP 3121, 384 Refactoring applied to pyexpat module</li><li>bpo-15700: PEP 3121, 384 Refactoring applied to resource module</li><li>bpo-15703: PEP 3121, 384 Refactoring applied to select module</li><li>bpo-15704: PEP 3121, 384 Refactoring applied to sha1 module</li><li>bpo-15705: PEP 3121, 384 Refactoring applied to sha256 module</li><li>bpo-15706: PEP 3121, 384 Refactoring applied to sha512 module</li><li>bpo-15707: PEP 3121, 384 Refactoring applied to signal module</li><li>bpo-15708: PEP 3121, 384 Refactoring applied to socket module</li><li>bpo-15709: PEP 3121, 384 Refactoring applied to termios module</li><li>bpo-15711: PEP 3121, 384 Refactoring applied to time module</li><li>bpo-15712: PEP 3121, 384 Refactoring applied to unicodedata module</li><li>bpo-15713: PEP 3121, 384 Refactoring applied to zipimport module</li><li>bpo-15714: PEP 3121, 384 Refactoring applied to grp module</li><li>bpo-15721: PEP 3121, 384 Refactoring applied to tkinter module</li><li>bpo-15722: PEP 3121, 384 Refactoring applied to decimal module</li><li>bpo-15733: PEP 3121, 384 Refactoring applied to winapi module</li><li>bpo-15734: PEP 3121, 384 Refactoring applied to spwd module</li><li>bpo-15735: PEP 3121, 384 Refactoring applied to ossaudio module</li><li>bpo-15848: PEP 3121, 384 Refactoring applied to xxsubtype module</li><li>bpo-15849: PEP 3121, 384 Refactoring applied to xx module</li><li>bpo-15884: PEP 3121, 384 Refactoring applied to ctypes module</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-08-27.03:36:04.806>
labels = ['extension-modules', 'type-feature', '3.11']
title = '[meta issue] PEP 3121, 384 Refactoring'
updated_at = <Date 2021-07-28.22:21:25.308>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-28.22:21:25.308>
actor = 'belopolsky'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2012-08-27.03:36:04.806>
creator = 'belopolsky'
dependencies = ['14732', '14935', '14936', '15140', '15389', '15390', '15650', '15651', '15652', '15653', '15666', '15667', '15668', '15669', '15670', '15671', '15672', '15673', '15674', '15675', '15680', '15681', '15682', '15684', '15685', '15686', '15687', '15688', '15689', '15690', '15691', '15697', '15698', '15700', '15703', '15704', '15705', '15706', '15707', '15708', '15709', '15711', '15712', '15713', '15714', '15721', '15722', '15733', '15734', '15735', '15848', '15849', '15884']
files = []
hgrepos = []
issue_num = 15787
keywords = []
message_count = 8.0
messages = ['169177', '169179', '194600', '194602', '194889', '195098', '381428', '398434']
nosy_count = 6.0
nosy_names = ['loewis', 'ncoghlan', 'belopolsky', 'pitrou', 'vstinner', 'Robin.Schreiber']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue15787'
versions = ['Python 3.11']
```

</p></details>

**Comment by AA-Turner** [comment]
The linked #44470 has been closed, closing this one.

A
