### ISSUE TITLE
Truncated POST data in CGI script on Windows 7

### ISSUE THREAD

**Issue by 9d0386cc-a1ac-44f7-8720-498a74ff3ea9** [python/cpython#60270]
BPO | [16066](https://bugs.python.org/issue16066)
--- | :---
Nosy | @tjguk
Files | <li>[Truncated_POST_data_in_CGI_script_on_Win7.zip](https://bugs.python.org/file27322/Truncated_POST_data_in_CGI_script_on_Win7.zip "Uploaded as application/zip at 2012-09-27.21:50:45 by Alexander.Martin"): server script, HTML file and Python script for error reproduction</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-09-27.21:50:46.908>
labels = ['type-bug', 'library', 'OS-windows']
title = 'Truncated POST data in CGI script on Windows 7'
updated_at = <Date 2019-04-26.18:07:20.505>
user = 'https://bugs.python.org/AlexanderMartin'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.18:07:20.505>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2012-09-27.21:50:46.908>
creator = 'Alexander.Martin'
dependencies = []
files = ['27322']
hgrepos = []
issue_num = 16066
keywords = []
message_count = 4.0
messages = ['171394', '171417', '224271', '228365']
nosy_count = 3.0
nosy_names = ['tim.golden', 'Alexander.Martin', 'Eyal.Gruss']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16066'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/) and further no improvements or bug fixes will be made to the module.
