### ISSUE TITLE
list duplicate test names with patchcheck

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#60283]
BPO | [16079](https://bugs.python.org/issue16079)
--- | :---
Nosy | @rhettinger, @gpshead, @vstinner, @rbtcollins, @ned-deily, @ezio-melotti, @merwok, @cjerdonek, @xdegaye, @ambv, @miss-islington
PRs | <li>python/cpython#12827</li><li>python/cpython#12828</li><li>python/cpython#12886</li><li>python/cpython#12940</li><li>python/cpython#12950</li>
Files | <li>[duplicate_test_names.patch](https://bugs.python.org/file27326/duplicate_test_names.patch "Uploaded as text/plain at 2012-09-28.10:15:36 by @xdegaye")</li><li>[duplicate_code_names.py](https://bugs.python.org/file27375/duplicate_code_names.py "Uploaded as text/plain at 2012-10-01.16:49:48 by @xdegaye")</li><li>[std_lib_duplicates.txt](https://bugs.python.org/file27376/std_lib_duplicates.txt "Uploaded as text/plain at 2012-10-01.16:50:30 by @xdegaye")</li><li>[duplicate_code_names_2.py](https://bugs.python.org/file31891/duplicate_code_names_2.py "Uploaded as text/plain at 2013-09-28.15:28:24 by @xdegaye")</li><li>[ignored_duplicates](https://bugs.python.org/file31892/ignored_duplicates "Uploaded as text/plain at 2013-09-28.15:28:47 by @xdegaye")</li><li>[duplicate_code_names_3.py](https://bugs.python.org/file48265/duplicate_code_names_3.py "Uploaded as text/plain at 2019-04-13.16:34:39 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-09-28.10:15:37.662>
labels = ['easy', 'tests', 'type-bug', 'library', '3.9']
title = 'list duplicate test names with patchcheck'
updated_at = <Date 2019-11-27.18:45:45.910>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-27.18:45:45.910>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2012-09-28.10:15:37.662>
creator = 'xdegaye'
dependencies = []
files = ['27326', '27375', '27376', '31891', '31892', '48265']
hgrepos = []
issue_num = 16079
keywords = ['patch', 'easy']
message_count = 31.0
messages = ['171428', '171499', '171505', '171509', '171511', '171512', '171513', '171519', '171536', '171544', '171548', '171558', '171559', '171576', '171734', '198525', '198586', '229625', '340168', '340219', '340221', '340252', '340286', '340295', '340323', '340584', '340585', '340687', '340785', '340786', '351668']
nosy_count = 11.0
nosy_names = ['rhettinger', 'gregory.p.smith', 'vstinner', 'rbcollins', 'ned.deily', 'ezio.melotti', 'eric.araujo', 'chris.jerdonek', 'xdegaye', 'lukasz.langa', 'miss-islington']
pr_nums = ['12827', '12828', '12886', '12940', '12950']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16079'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-109161

**Comment by erlend-aasland** [comment]
Superseded by python/core-workflow#505

**Comment by merwok** [comment]
Isn’t that repo for tooling and meta issues?

IMO this should stay in the CPython tracker for visibility.

**Comment by erlend-aasland** [comment]
> Isn’t that repo for tooling and meta issues?

Yes, and CI issues. Most relevant comments in this thread are about running these checks in CI. So it belongs in the core-workflow repo.

**Comment by erlend-aasland** [comment]
Ok, I reopen the ticket.
