### ISSUE TITLE
sys.path[0] security issues

### ISSUE THREAD

**Issue by jdemeyer** [python/cpython#60406]
BPO | [16202](https://bugs.python.org/issue16202)
--- | :---
Nosy | @birkenfeld, @jaraco, @ncoghlan, @vstinner, @tiran, @benjaminp, @tarekziade, @jwilk, @merwok, @ericsnowcurrently, @hynek, @jdemeyer, @zooba, @aw1231
Files | <li>[fix_distutils.patch](https://bugs.python.org/file27542/fix_distutils.patch "Uploaded as text/plain at 2012-10-12.16:03:55 by robertwb")</li><li>[fix_distutils.patch](https://bugs.python.org/file27543/fix_distutils.patch "Uploaded as text/plain at 2012-10-12.18:36:44 by robertwb")</li><li>[sys_path_security.patch](https://bugs.python.org/file27923/sys_path_security.patch "Uploaded as text/plain at 2012-11-08.13:39:23 by @jdemeyer")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/merwok'
closed_at = None
created_at = <Date 2012-10-11.20:10:23.538>
labels = ['type-security', 'interpreter-core', '3.8', '3.9', '3.10', '3.7']
title = 'sys.path[0] security issues'
updated_at = <Date 2021-02-03.18:21:55.365>
user = 'https://github.com/jdemeyer'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-03.18:21:55.365>
actor = 'christian.heimes'
assignee = 'eric.araujo'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2012-10-11.20:10:23.538>
creator = 'jdemeyer'
dependencies = []
files = ['27542', '27543', '27923']
hgrepos = []
issue_num = 16202
keywords = ['patch']
message_count = 24.0
messages = ['172686', '172709', '172722', '172736', '172750', '172755', '172756', '172762', '172764', '172766', '172768', '172798', '172799', '172803', '172812', '172981', '172983', '172998', '173000', '175155', '275215', '275598', '311782', '386330']
nosy_count = 21.0
nosy_names = ['georg.brandl', 'jaraco', 'ncoghlan', 'vstinner', 'ThomasAH', 'christian.heimes', 'schmir', 'robertwb', 'benjamin.peterson', 'tarek', 'jwilk', 'eric.araujo', 'Arfrever', 'iankko', 'eric.snow', 'hynek', 'jdemeyer', 'steve.dower', 'Alan.Williams', 'vbraun', 'hasufell']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue16202'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by hauntsaninja** [comment]
I think this can be closed since #57684 and #31542
