### ISSUE TITLE
mmap() dumps core upon resizing the underlying file

### ISSUE THREAD

**Issue by 7271e16d-99ec-4ea6-9fed-c7e74fa58904** [python/cpython#60416]
BPO | [16212](https://bugs.python.org/issue16212)
--- | :---
Nosy | @jcea, @pitrou, @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-10-12.14:04:23.961>
labels = ['3.10', '3.8', 'expert-IO', 'type-crash', '3.9']
title = 'mmap() dumps core upon resizing the underlying file'
updated_at = <Date 2020-11-06.16:38:53.124>
user = 'https://bugs.python.org/VladimirUshakov'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-06.16:38:53.124>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2012-10-12.14:04:23.961>
creator = 'Vladimir.Ushakov'
dependencies = []
files = []
hgrepos = []
issue_num = 16212
keywords = []
message_count = 21.0
messages = ['172745', '172746', '172759', '172760', '172761', '172765', '172782', '172783', '172785', '172826', '172835', '172837', '172842', '172857', '172859', '172860', '172862', '172864', '172866', '172889', '172892']
nosy_count = 5.0
nosy_names = ['jcea', 'pitrou', 'christian.heimes', 'neologix', 'Vladimir.Ushakov']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue16212'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
Closing as this has been open for over a decade, and several core devs have indicated they believe there is nothing that can be done.

**Comment by terryjreedy** [comment]
Vladimir, if you ever see this, thanks for opening the discussion.  However,  'all costs' in
> I thought that the possibility to crash the interpreter is something to be avoided at all costs.
https://github.com/python/cpython/issues/60416#issuecomment-1093596917
in practice becomes 'any reasonable cost'.  Given the lack of in the field reports coupled with lack of real progress, I agree with Irit.
