### ISSUE TITLE
Undocumented (?) behaviour change in argparse from 3.2.3 to 3.3.0

### ISSUE THREAD

**Issue by 89f44229-f3d4-4c3d-99a4-85378e700e1e** [python/cpython#60512]
BPO | [16308](https://bugs.python.org/issue16308)
--- | :---
Nosy | @bitdancer, @asvetlov, @mmaker, @epicfaace
Files | <li>[subparse.py](https://bugs.python.org/file27694/subparse.py "Uploaded as text/plain at 2012-10-24.13:44:20 by telmich")</li><li>[subparse2.py](https://bugs.python.org/file27695/subparse2.py "Uploaded as text/plain at 2012-10-24.14:12:13 by telmich")</li><li>[subparse3.py](https://bugs.python.org/file27696/subparse3.py "Uploaded as text/plain at 2012-10-24.14:17:18 by telmich")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-10-24.09:22:33.064>
labels = ['library']
title = 'Undocumented (?) behaviour change in argparse from 3.2.3 to 3.3.0'
updated_at = <Date 2019-08-25.00:50:08.945>
user = 'https://bugs.python.org/telmich'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-25.00:50:08.945>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-10-24.09:22:33.064>
creator = 'telmich'
dependencies = []
files = ['27694', '27695', '27696']
hgrepos = []
issue_num = 16308
keywords = []
message_count = 17.0
messages = ['173659', '173672', '173681', '173683', '173684', '173685', '173686', '173688', '173690', '173691', '173692', '175167', '177237', '187255', '187343', '350412', '350415']
nosy_count = 8.0
nosy_names = ['bethard', 'Arfrever', 'r.david.murray', 'asvetlov', 'maker', 'paul.j3', 'telmich', 'epicfaace']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue16308'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by savannahostrowski** [comment]
Since both 3.23 and 3.30 are EOL, I'm going to close this.

**Comment by serhiy-storchaka** [comment]
Did you mean 3.2 and 3.3 @savannahostrowski?

I agree that this is not a bug. This is just the current default behavior of `argparse`. There is an existing option to change it, so nothing to do from our side.
