### ISSUE TITLE
pdb raises BdbQuit on 'quit' when started with set_trace

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#60650]
BPO | [16446](https://bugs.python.org/issue16446)
--- | :---
Nosy | @giampaolo, @asvetlov, @xdegaye
Files | <li>[issue16446.patch](https://bugs.python.org/file29208/issue16446.patch "Uploaded as text/plain at 2013-02-23.20:59:55 by nailor")</li><li>[quit.py](https://bugs.python.org/file29231/quit.py "Uploaded as text/plain at 2013-02-25.12:07:21 by @xdegaye")</li><li>[branch-27.patch](https://bugs.python.org/file29232/branch-27.patch "Uploaded as text/plain at 2013-02-25.12:08:53 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-11-08.23:09:53.394>
labels = ['type-bug', 'library']
title = "pdb raises BdbQuit on 'quit' when started with set_trace"
updated_at = <Date 2014-07-19.21:24:34.417>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2014-07-19.21:24:34.417>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-11-08.23:09:53.394>
creator = 'xdegaye'
dependencies = []
files = ['29208', '29231', '29232']
hgrepos = []
issue_num = 16446
keywords = ['patch']
message_count = 8.0
messages = ['175205', '176275', '182596', '182821', '182932', '182933', '219213', '219230']
nosy_count = 5.0
nosy_names = ['giampaolo.rodola', 'asvetlov', 'xdegaye', 'nailor', 'rmarko']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16446'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by gaogaotiantian** [comment]
I don't think currently we are planning to change the semantics of `quit` - `continue` is doing exactly that. Close as not planned, feel free to discuss more if anyone has different opinions.
