### ISSUE TITLE
Allow ssl certificates to be specified from memory rather than files.

### ISSUE THREAD

**Issue by 84401114-8e59-4056-83cb-632106c0b648** [python/cpython#60691]
BPO | [16487](https://bugs.python.org/issue16487)
--- | :---
Nosy | @jcea, @orsenthil, @pitrou, @kristjanvalur, @giampaolo, @tiran, @njsmith, @asvetlov, @jgehrcke, @dstufft, @Martiusweb
PRs | <li>python/cpython#2449</li>
Files | <li>[sslpatch1.patch](https://bugs.python.org/file28002/sslpatch1.patch "Uploaded as text/plain at 2012-11-16.15:10:12 by @kristjanvalur")</li><li>[sslpatch2.patch](https://bugs.python.org/file28866/sslpatch2.patch "Uploaded as text/plain at 2013-01-27.02:55:24 by @kristjanvalur")</li><li>[ssl.patch](https://bugs.python.org/file30707/ssl.patch "Uploaded as text/plain at 2013-06-26.22:50:01 by @kristjanvalur")</li><li>[ssl2.patch](https://bugs.python.org/file30718/ssl2.patch "Uploaded as text/plain at 2013-06-27.23:15:28 by @kristjanvalur")</li><li>[ssl2.patch](https://bugs.python.org/file32612/ssl2.patch "Uploaded as text/plain at 2013-11-14.12:11:33 by @kristjanvalur")</li><li>[python_16487_jgehrcke_01.patch](https://bugs.python.org/file44092/python_16487_jgehrcke_01.patch "Uploaded as text/plain at 2016-08-13.12:58:25 by @jgehrcke")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2012-11-16.15:10:15.811>
labels = ['expert-SSL', '3.8', 'type-feature', '3.7', '3.9']
title = 'Allow ssl certificates to be specified from memory rather than files.'
updated_at = <Date 2020-03-01.22:19:26.571>
user = 'https://github.com/kristjanvalur'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-01.22:19:26.571>
actor = 'kristjan.jonsson'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2012-11-16.15:10:15.811>
creator = 'kristjan.jonsson'
dependencies = []
files = ['28002', '28866', '30707', '30718', '32612', '44092']
hgrepos = []
issue_num = 16487
keywords = ['patch']
message_count = 67.0
messages = ['175691', '175692', '175701', '175709', '175741', '175779', '175806', '175809', '180734', '180736', '180737', '190997', '191018', '191828', '191838', '191847', '191859', '191860', '191862', '191868', '191922', '191923', '191924', '191936', '191937', '191938', '191941', '191942', '191957', '191970', '202800', '202828', '202829', '202832', '202833', '246488', '246489', '246492', '246494', '246495', '246496', '246555', '272585', '275288', '277173', '281457', '293908', '297068', '303514', '307153', '307154', '307296', '307298', '307299', '307320', '307322', '307357', '307372', '307373', '307377', '307380', '307681', '309841', '324686', '362692', '363074', '363101']
nosy_count = 13.0
nosy_names = ['jcea', 'orsenthil', 'pitrou', 'kristjan.jonsson', 'giampaolo.rodola', 'christian.heimes', 'njs', 'asvetlov', 'jgehrcke', 'brandon-rhodes', 'dstufft', 'martius', 'Lord Anton Hvornum']
pr_nums = ['2449']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue16487'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by orsenthil** [comment]
Hi Jan-Philip, we might be close on this one. 
Could you convert your latest patch into PR against (https://github.com/python/cpython). Is will help to record you as the author as we can discuss the patch in python sprints and get this in. :-) Thanks!

**Comment by d1262d3a-e001-4120-aca1-c359b5bd2ab5** [comment]
Hey Senthil and Christian!

> Could you convert your latest patch into PR against https://github.com/python/cpython

That was fun. There we go: https://github.com/python/cpython/pull/2449

I hope I was not too late with that for the 3.7 development.

**Comment by d1262d3a-e001-4120-aca1-c359b5bd2ab5** [comment]
Hey Antoine, Christian, Senthil!

I have invested quite a bit more time to double-check my responses to the questions asked so far, clarified where appropriate, and updated the pull request on GitHub after manually resolving the merge conflicts that accumulated over time.

I would very much appreciate to get another round of feedback. Can we somehow expedite this? I am available for pushing this further, so that maybe we can still land this in 3.7 after we missed 3.6 last year.

Based on the diff this change \_appears_ to be risky but I would like to stress again that I approached this issue pretty conservatively. I tried to make this a conceptually backwards-compatible change by keeping the old code path intact (the old tests pass, too, but this is not the best criterion here).

Cheers and thanks!

Jan-Philip

**Comment by d1262d3a-e001-4120-aca1-c359b5bd2ab5** [comment]
Hello! I would very much appreciate if we can find a way for us to get another review for the last patch.

I did most of the work in August 2016 and got a review from Senthil and Christian which I processed. When I got back to the patch for converting it to the GitHub workflow about a year later I realized that the details faded from my mind. 4 months later, after re-digging into the details, I went into the patch again and resolved the merge conflicts that accumulated over time. Antoine kindly left another round of comments which I replied to.

Now, 2 months after that last effort I'd like to not forget about the details again, but instead be able to respond to review feedback while still being on top of the matter. So, any kind and level of feedback would be greatly appreciated.

Thank you!

**Comment by orsenthil** [comment]
Hello JP, I had been little inactive for a while (\>2 years). However, I think, I can take now some load in CPython world and I will take this ticket/feature forward this Sunday (1-Dec-2017).

If Christian (or currently active committers) don't get to it before, then expect from me to move this forward. Thank you.

**Comment by tiran** [comment]
I'm -1 on the patch. Any new feature and API shall follow https://www.python.org/dev/peps/pep-0543/. I have some code that adds a proper Certificate class that wraps OpenSSL's X509* type.

**Comment by pitrou** [comment]
Christian, what is the status of PEP-543? Is someone actively working on it?  Should we hope for a resolution (i.e. an implementation accepted in the stdlib) in the near future?

I'm worried about such purity arguments.  It reminds me of when we decided to freeze distutils because distutils2 was to become the future (and then distlib took that place, etc.).  In the end "the future" hasn't really happened and distutils has rotten without a clear path forward for users (except the venerable setuptools, which has its own issues).

**Comment by tiran** [comment]
I'm working on a PEP that builds on top of PEP-543 and addresses some issues like IDNA bpo-28414, OpenSSL/LibreSSL compatibility, hostname verification, verification chain, and TLS 1.3. As part of the PEP implementation, I'll add a certificate class.

I don't to introduce yet another way to load a certificate. The C code is already complicated enough.

**Comment by 84401114-8e59-4056-83cb-632106c0b648** [comment]
OP here, lurking.
The need to load server certificates from memory is quite real. Some seven
years ago I wrote custom code to handle that for CCPs python branch, and
contributed patches to that effect.
It's always dismaying to see how peoples efforts get bogged down by one
thing or another.  So, now there is a pep that prohibits this change?  Fun
times.

2017-11-30 12:03 GMT+00:00 Christian Heimes \<report@bugs.python.org\>:

>
> Christian Heimes \<lists@cheimes.de\> added the comment:
>
> I'm working on a PEP that builds on top of PEP-543 and addresses some
> issues like IDNA bpo-28414, OpenSSL/LibreSSL compatibility, hostname
> verification, verification chain, and TLS 1.3. As part of the PEP
> implementation, I'll add a certificate class.
>
> I don't to introduce yet another way to load a certificate. The C code is
> already complicated enough.
>
> \----------
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue16487\>
> _______________________________________
>

**Comment by Martiusweb** [comment]
FWIW, PyOpenSSL allows to load certificates and keys from a memory buffer and much more. It's also fairly easy to switch from ssl to PyOpenSSL.

It's probably a viable alternative in many cases.

**Comment by njsmith** [comment]
My impression was that progress on PEP-543 is temporarily stalled and not going to be finished for 3.7. Is that wrong?

There's going to need to be a significant amount of shimming to implement the PEP-543 interfaces on top of ssl no matter what you do. Maybe it would be best to merge a simple load_cert_chain_from_buffer method now for 3.7, and worry about redesigning the world later?

**Comment by alonbl** [comment]
Hello,
Any news? it is important to be able to use private key from external devices and it fairly trivial to let openssl implement this. In future it can be extended but for now, please support it with minimal effort if using the openssl way.
Thanks,

**Comment by arhadthedev** [comment]
Closing; see https://github.com/python/cpython/pull/2449#issuecomment-1429164471 for explanation.

**Comment by lapcchan** [comment]
@jgehrcke thanks for your patch and although it's not getting merge but it does help us to avoid writing keyfile on disk.

it's seems that workaround patches are not welcome so i am expecting this feature request will remains open for another 10yrs lol

**Comment by GunGunGun** [comment]
Kinda demoralising to know this won't be improved, but well up to some point Python really needs to move on from OpenSSL and switch to RustTLS or something like, OpenSSL isn't that open, it's so restricted that's why it's getting hit hard by TLSFingerprint, no way to workaround btw.
