### ISSUE TITLE
allow constructors to be documented separately from class

### ISSUE THREAD

**Issue by cjerdonek** [python/cpython#60772]
BPO | [16568](https://bugs.python.org/issue16568)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @ncoghlan, @ezio-melotti, @merwok, @cjerdonek

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-11-28.09:03:32.756>
labels = ['type-feature', 'docs']
title = 'allow constructors to be documented separately from class'
updated_at = <Date 2012-12-03.08:10:13.511>
user = 'https://github.com/cjerdonek'
```

bugs.python.org fields:
```python
activity = <Date 2012-12-03.08:10:13.511>
actor = 'Arfrever'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2012-11-28.09:03:32.756>
creator = 'chris.jerdonek'
dependencies = []
files = []
hgrepos = []
issue_num = 16568
keywords = []
message_count = 6.0
messages = ['176524', '176567', '176619', '176621', '176623', '176625']
nosy_count = 8.0
nosy_names = ['georg.brandl', 'terry.reedy', 'ncoghlan', 'ezio.melotti', 'eric.araujo', 'Arfrever', 'chris.jerdonek', 'docs@python']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue16568'
versions = []
```

</p></details>

**Comment by AA-Turner** [comment]
I think just documenting ``.. method:: __init__`` would work -- this is for example done in [difflib](https://docs.python.org/dev/library/difflib.html#difflib.HtmlDiff.__init__).

A

**Comment by terryjreedy** [comment]
In a file, the class and each method can have separate docstrings.  In the class doc, there are separate entries for the class and the `__init__` methods, and occasionally the `__new__` method.  Elsewhere in the doc, we have class and method role directives.  I don't see a need for new constructor and initializer directives.  In any case, I think any further (meta) discussion is a doc or devguide discussion.
