### ISSUE TITLE
Solaris ctypes_test failures

### ISSUE THREAD

**Issue by 61445b73-060a-4ec5-9f1f-4009594539a1** [python/cpython#60937]
BPO | [16733](https://bugs.python.org/issue16733)
--- | :---
Nosy | @jcea, @vstinner, @tiran, @tpn, @meadori
Files | <li>[ctypes.out](https://bugs.python.org/file28371/ctypes.out "Uploaded as text/plain at 2012-12-19.23:24:42 by yippi"): python program and output showing failures</li><li>[0001-Fix-ctypes-bitfield-test-code-to-account-for-compile.patch](https://bugs.python.org/file47580/0001-Fix-ctypes-bitfield-test-code-to-account-for-compile.patch "Uploaded as text/plain at 2018-05-09.00:45:35 by gco")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-12-19.23:24:47.165>
labels = ['type-bug', 'tests']
title = 'Solaris ctypes_test failures'
updated_at = <Date 2018-05-09.22:49:51.729>
user = 'https://bugs.python.org/yippi'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-09.22:49:51.729>
actor = 'gco'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2012-12-19.23:24:47.165>
creator = 'yippi'
dependencies = []
files = ['28371', '47580']
hgrepos = []
issue_num = 16733
keywords = ['patch']
message_count = 6.0
messages = ['177792', '206342', '211499', '223813', '316300', '316341']
nosy_count = 7.0
nosy_names = ['jcea', 'vstinner', 'christian.heimes', 'trent', 'meador.inge', 'yippi', 'gco']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16733'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.3 is unsupported, if this issue exists on supported Python versions please create a new issue with reproducer. 
Also note that Solaris is not supported as per [PEP 11](https://peps.python.org/pep-0011/#support-tiers).
