### ISSUE TITLE
Make CPython test package discoverable

### ISSUE THREAD

**Issue by zware** [python/cpython#60952]
BPO | [16748](https://bugs.python.org/issue16748)
--- | :---
Nosy | @terryjreedy, @ezio-melotti, @merwok, @bitdancer, @cjerdonek, @ericsnowcurrently, @zware, @serhiy-storchaka
Dependencies | <li>bpo-14408: Support ./python -m unittest in test_socket</li><li>bpo-16852: Fix test discovery for test_genericpath.py</li><li>bpo-16888: Fix test discovery for test_array.py</li><li>bpo-16968: Fix test discovery for test_concurrent_futures.py</li><li>bpo-18258: Fix test discovery for test_codecmaps*.py</li><li>bpo-20008: Clean up/refactor/make discoverable test_decimal</li><li>bpo-22002: Make full use of test discovery in test subpackages</li>
Files | <li>[issue16748.diff](https://bugs.python.org/file28523/issue16748.diff "Uploaded as text/plain at 2013-01-02.02:10:52 by @ezio-melotti")</li><li>[issue16748_genericpath.diff](https://bugs.python.org/file28535/issue16748_genericpath.diff "Uploaded as text/plain at 2013-01-02.23:05:44 by @zware"): For test_*path.py</li><li>[issue16748_genericpath.v2.diff](https://bugs.python.org/file28542/issue16748_genericpath.v2.diff "Uploaded as text/plain at 2013-01-03.15:08:29 by @zware"): test_*path.py version 2</li><li>[checkTestOverriding.diff](https://bugs.python.org/file28689/checkTestOverriding.diff "Uploaded as text/plain at 2013-01-11.10:49:03 by @serhiy-storchaka"): Hacking patch which prints test methods overriding</li><li>[test_overriding.txt](https://bugs.python.org/file28690/test_overriding.txt "Uploaded as text/plain at 2013-01-11.10:59:22 by @serhiy-storchaka"): List of overridden test methods</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ezio-melotti'
closed_at = None
created_at = <Date 2012-12-22.01:02:27.055>
labels = ['type-bug', 'tests']
title = 'Make CPython test package discoverable'
updated_at = <Date 2020-01-29.00:34:50.166>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-29.00:34:50.166>
actor = 'brett.cannon'
assignee = 'ezio.melotti'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2012-12-22.01:02:27.055>
creator = 'zach.ware'
dependencies = ['14408', '16852', '16888', '16968', '18258', '20008', '22002']
files = ['28523', '28535', '28542', '28689', '28690']
hgrepos = []
issue_num = 16748
keywords = ['patch']
message_count = 49.0
messages = ['177913', '177925', '177927', '178091', '178140', '178156', '178420', '178425', '178428', '178737', '178749', '178795', '178812', '178831', '178835', '178839', '178840', '178841', '178861', '178932', '178947', '178956', '178958', '178965', '179055', '179286', '179288', '179292', '179296', '179297', '179298', '179305', '179308', '179316', '179319', '179347', '179349', '179361', '179370', '179634', '179635', '179663', '179665', '179956', '179971', '179980', '179996', '189292', '191487']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'ezio.melotti', 'eric.araujo', 'r.david.murray', 'chris.jerdonek', 'python-dev', 'eric.snow', 'zach.ware', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16748'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Can this issue be closed? I finished conversion from `test_main()` to `unittest.main()` in #89392, but I did test all tests with `unittest discover`.

**Comment by zware** [comment]
Sounds good to me.  Thanks for finishing it off, Serhiy!
