### ISSUE TITLE
execfile/exec execution in other than global scope uses locals(), leading to undefined behavior

### ISSUE THREAD

**Issue by 9432cd65-9f88-4bc6-8ad6-72e5ab1c730d** [python/cpython#60985]
BPO | [16781](https://bugs.python.org/issue16781)
--- | :---
Nosy | @terryjreedy, @benjaminp, @bitdancer, @miss-islington
PRs | <li>python/cpython#24469</li><li>python/cpython#24470</li><li>python/cpython#24471</li>
Files | <li>[b3.py](https://bugs.python.org/file28434/b3.py "Uploaded as text/plain at 2012-12-26.00:15:47 by techtonik")</li><li>[a.py](https://bugs.python.org/file28435/a.py "Uploaded as text/plain at 2012-12-26.00:22:21 by techtonik")</li><li>[b2.py](https://bugs.python.org/file28436/b2.py "Uploaded as text/plain at 2012-12-26.00:22:29 by techtonik")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-12-26.00:15:50.597>
labels = ['type-bug', '3.8', '3.9', '3.10', 'docs']
title = 'execfile/exec execution in other than global scope uses locals(), leading to undefined behavior'
updated_at = <Date 2021-02-07.14:14:23.542>
user = 'https://bugs.python.org/techtonik'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-07.14:14:23.542>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2012-12-26.00:15:50.597>
creator = 'techtonik'
dependencies = []
files = ['28434', '28435', '28436']
hgrepos = []
issue_num = 16781
keywords = ['patch']
message_count = 14.0
messages = ['178177', '178180', '178184', '178190', '178232', '178253', '178255', '178442', '178456', '178472', '386576', '386577', '386578', '386591']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'techtonik', 'benjamin.peterson', 'Arfrever', 'r.david.murray', 'docs@python', 'miss-islington']
pr_nums = ['24469', '24470', '24471']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16781'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by furkanonder** [comment]
@terryjreedy The issue seems to have been resolved. I think we can close the issue.
