### ISSUE TITLE
argparse group nesting lost on inheritance

### ISSUE THREAD

**Issue by e1d29b37-30c5-4023-830b-f8e2f5354e80** [python/cpython#61011]
BPO | [16807](https://bugs.python.org/issue16807)
--- | :---
Nosy | @dougalsutherland, @iritkatriel
Files | <li>[argparse_mutex_parent.patch](https://bugs.python.org/file28473/argparse_mutex_parent.patch "Uploaded as text/plain at 2012-12-29.01:39:23 by @dougalsutherland"): patch fixing the problem and adding a test</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2012-12-29.01:39:27.035>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'argparse group nesting lost on inheritance'
updated_at = <Date 2021-12-10.16:54:57.102>
user = 'https://github.com/dougalsutherland'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.16:54:57.102>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2012-12-29.01:39:27.035>
creator = 'dougalsutherland'
dependencies = []
files = ['28473']
hgrepos = []
issue_num = 16807
keywords = ['patch']
message_count = 5.0
messages = ['178459', '222934', '223047', '223158', '408222']
nosy_count = 4.0
nosy_names = ['bethard', 'paul.j3', 'dougalsutherland', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16807'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-125210
* gh-125308
* gh-125309

**Comment by serhiy-storchaka** [comment]
@djsutherland, is it your patch? Are you interesting in creating a PR?

**Comment by serhiy-storchaka** [comment]
The page of the original author of the patch @dougalsutherland was moved to @djsutherland, but that page has different name, and I do not know if they are the same person or relatives. So I used the old name to credit the author in #125210.

**Comment by djsutherland** [comment]
Oh wow, this has been a while!

I am the same person; I changed my name years ago. Please change the ACKS in the other patch to Danica J Sutherland; thanks @serhiy-storchaka!

**Comment by serhiy-storchaka** [comment]
Done. Thank you for your contribution, Danica, and sorry it took too long to review your patch.
