### ISSUE TITLE
warnings.simplefilter should validate input

### ISSUE THREAD

**Issue by 7227ac6e-e071-42b0-9479-676fdb34fe4f** [python/cpython#61049]
BPO | [16845](https://bugs.python.org/issue16845)
--- | :---
Nosy | @berkerpeksag, @seberg, @vajrasky, @nanjekyejoannah, @Bonifacio2, @DanielNoord
PRs | <li>python/cpython#26696</li><li>python/cpython#31983</li>
Files | <li>[add_assert_in_simplefilter.patch](https://bugs.python.org/file32131/add_assert_in_simplefilter.patch "Uploaded as text/plain at 2013-10-15.08:58:30 by @vajrasky")</li><li>[issue16845.diff](https://bugs.python.org/file35773/issue16845.diff "Uploaded as text/plain at 2014-06-24.19:09:44 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-01-03.00:42:06.501>
labels = ['easy', 'type-feature', 'library', '3.10']
title = 'warnings.simplefilter should validate input'
updated_at = <Date 2022-03-18.19:52:15.032>
user = 'https://github.com/seberg'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-18.19:52:15.032>
actor = 'danielnoord'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-01-03.00:42:06.501>
creator = 'seberg'
dependencies = []
files = ['32131', '35773']
hgrepos = []
issue_num = 16845
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['178867', '199985', '221480', '395747', '415522']
nosy_count = 7.0
nosy_names = ['python-dev', 'berker.peksag', 'seberg', 'vajrasky', 'nanjekyejoannah', 'Bonifacio2', 'danielnoord']
pr_nums = ['26696', '31983']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue16845'
versions = ['Python 3.10']
```

</p></details>

**Comment by DanielNoord** [comment]
See https://github.com/python/cpython/pull/31983.

I see no reason to pursue this. `warnings.simplefilter("error", int)` does not raise a `TypeError` later on, even when warnings a raised. Adding validation only makes this unnecessarily stricter while that is not needed. The documentation is clear that `Warning` classes are preferred.

**Comment by encukou** [comment]
I agree.
