### ISSUE TITLE
Fix test discovery for test_concurrent_futures.py

### ISSUE THREAD

**Issue by zware** [python/cpython#61172]
BPO | [16968](https://bugs.python.org/issue16968)
--- | :---
Nosy | @brettcannon, @ezio-melotti, @cjerdonek, @vadmium, @zware, @serhiy-storchaka
PRs | <li>python/cpython#8099</li>
Files | <li>[test_concurrent_futures_discovery.diff](https://bugs.python.org/file28729/test_concurrent_futures_discovery.diff "Uploaded as text/plain at 2013-01-14.22:19:33 by @zware"): Fix discovery, but not test_main</li><li>[test_concurrent_futures_discovery.v2.diff](https://bugs.python.org/file28819/test_concurrent_futures_discovery.v2.diff "Uploaded as text/plain at 2013-01-24.22:30:49 by @zware"): v2, test_main replaced but gives warning</li><li>[test_concurrent_futures_discovery.v3.diff](https://bugs.python.org/file28881/test_concurrent_futures_discovery.v3.diff "Uploaded as text/plain at 2013-01-28.15:29:39 by @zware"): Version 3</li><li>[test_concurrent_futures_discovery.v4.diff](https://bugs.python.org/file28896/test_concurrent_futures_discovery.v4.diff "Uploaded as text/plain at 2013-01-29.17:50:11 by @zware"): Version 4</li><li>[test_concurrent_futures_discovery.v5.diff](https://bugs.python.org/file31191/test_concurrent_futures_discovery.v5.diff "Uploaded as text/plain at 2013-08-08.03:29:38 by @zware"): Version 5</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-01-14.22:19:34.136>
labels = ['3.7', '3.8', 'type-bug', 'tests']
title = 'Fix test discovery for test_concurrent_futures.py'
updated_at = <Date 2021-09-17.19:33:58.330>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-17.19:33:58.330>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-01-14.22:19:34.136>
creator = 'zach.ware'
dependencies = []
files = ['28729', '28819', '28881', '28896', '31191']
hgrepos = []
issue_num = 16968
keywords = ['patch']
message_count = 26.0
messages = ['179983', '179984', '179985', '179992', '179993', '179997', '179998', '180041', '180551', '180566', '180567', '180689', '180860', '180876', '180917', '180950', '186531', '194533', '194643', '194910', '222058', '222107', '273260', '321072', '321160', '402081']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ezio.melotti', 'chris.jerdonek', 'martin.panter', 'zach.ware', 'serhiy.storchaka']
pr_nums = ['8099']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16968'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
> test_concurrent_futures was made discoverable by Victor Stinner in [bpo-37421](https://bugs.python.org/issue?@action=redirect&bpo=37421). It used tearDownModule() to run threading_cleanup() and reap_children().

Sounds like we can close this, then.

**Comment by erlend-aasland** [comment]
Fixed by gh-14563 in gh-81602.
