### ISSUE TITLE
argparse: mismatch between choices parsing and usage/error message

### ISSUE THREAD

**Issue by cjerdonek** [python/cpython#61181]
BPO | [16977](https://bugs.python.org/issue16977)
--- | :---
Nosy | @ericvsmith, @cjerdonek, @iritkatriel
Files | <li>[argparse.patch](https://bugs.python.org/file28769/argparse.patch "Uploaded as text/plain at 2013-01-18.15:51:21 by jeffknupp")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-01-16.02:30:07.460>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'argparse: mismatch between choices parsing and usage/error message'
updated_at = <Date 2021-12-10.15:38:13.260>
user = 'https://github.com/cjerdonek'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.15:38:13.260>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-01-16.02:30:07.460>
creator = 'chris.jerdonek'
dependencies = []
files = ['28769']
hgrepos = []
issue_num = 16977
keywords = ['patch']
message_count = 13.0
messages = ['180068', '180069', '180136', '180153', '180187', '180197', '180208', '180216', '180218', '192254', '192295', '192715', '408213']
nosy_count = 5.0
nosy_names = ['eric.smith', 'chris.jerdonek', 'paul.j3', 'jeffknupp', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue16977'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-124578
* gh-124755
* gh-124756

**Comment by serhiy-storchaka** [comment]
This can even be classified as a minor security issue. The current behavior is most likely not what most of users mean. It allows invalid data to pass the primary validation. Examples with string `choices` is present in the documentation and tests, so many users can use it unaware of the flaw.

#124578 converts the string `choices` value to list, adds tests, and updates examples.

There is a similar issue with bytes and bytearray, but it has much less chance to occur (you need a special type converter that can return int and bytes), so I leave it as is.
