### ISSUE TITLE
Shared modules built with Modules/Setup are not found when run from build directory

### ISSUE THREAD

**Issue by Yhg1s** [python/cpython#61297]
BPO | [17095](https://bugs.python.org/issue17095)
--- | :---
Nosy | @loewis, @Yhg1s, @vstinner, @larryhastings, @ned-deily, @matrixise
Files | <li>[getpath.diff](https://bugs.python.org/file28928/getpath.diff "Uploaded as text/plain at 2013-01-31.21:54:56 by @Yhg1s")</li><li>[issue17095_modules_setup.patch](https://bugs.python.org/file35344/issue17095_modules_setup.patch "Uploaded as text/plain at 2014-05-25.03:30:12 by @ned-deily")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2013-01-31.21:54:56.549>
labels = ['build']
title = 'Shared modules built with Modules/Setup are not found when run from build directory'
updated_at = <Date 2014-10-18.09:09:12.698>
user = 'https://github.com/Yhg1s'
```

bugs.python.org fields:
```python
activity = <Date 2014-10-18.09:09:12.698>
actor = 'matrixise'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2013-01-31.21:54:56.549>
creator = 'twouters'
dependencies = []
files = ['28928', '35344']
hgrepos = []
issue_num = 17095
keywords = ['patch']
message_count = 12.0
messages = ['181048', '219070', '219554', '219555', '225978', '226548', '226894', '229421', '229490', '229637', '229638', '229639']
nosy_count = 9.0
nosy_names = ['loewis', 'twouters', 'vstinner', 'larry', 'ned.deily', 'Arfrever', 'python-dev', 'matrixise', 'John.Malmberg']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue17095'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by ned-deily** [comment]
There has been a lot of work in the Python initialization area including Setup since this issue was opened. And there hasn't been much interest in it including from me. Let's just close it.
