### ISSUE TITLE
incorrect line numbers in backtrace after removing a trace function

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#61479]
BPO | [17277](https://bugs.python.org/issue17277)
--- | :---
Nosy | @jcea, @atsuoishimoto, @abalkin, @xdegaye, @phmc
Files | <li>[tracer.py](https://bugs.python.org/file29162/tracer.py "Uploaded as text/plain at 2013-02-22.16:42:48 by @xdegaye")</li><li>[generator.py](https://bugs.python.org/file29163/generator.py "Uploaded as text/plain at 2013-02-22.16:43:21 by @xdegaye")</li><li>[backtrace_lno.patch](https://bugs.python.org/file29170/backtrace_lno.patch "Uploaded as text/plain at 2013-02-23.14:34:37 by @xdegaye")</li><li>[traced_frame.patch](https://bugs.python.org/file29222/traced_frame.patch "Uploaded as text/plain at 2013-02-24.16:57:42 by @xdegaye")</li><li>[lineno_getter.patch](https://bugs.python.org/file35915/lineno_getter.patch "Uploaded as text/plain at 2014-07-09.14:45:54 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-02-22.16:42:49.093>
labels = ['interpreter-core', 'type-bug']
title = 'incorrect line numbers in backtrace after removing a trace function'
updated_at = <Date 2017-12-20.08:56:12.397>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-20.08:56:12.397>
actor = 'ishimoto'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2013-02-22.16:42:49.093>
creator = 'xdegaye'
dependencies = []
files = ['29162', '29163', '29170', '29222', '35915']
hgrepos = []
issue_num = 17277
keywords = ['patch']
message_count = 8.0
messages = ['182672', '182710', '182746', '182867', '182879', '182955', '222620', '246274']
nosy_count = 6.0
nosy_names = ['jcea', 'ishimoto', 'belopolsky', 'nikratio', 'xdegaye', 'pconnell']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17277'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by gaogaotiantian** [comment]
This seems to be already fixed. I can't reproduce with 3.13. Close for done.
