### ISSUE TITLE
__slots__ on PyVarObject subclass

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#61497]
BPO | [17295](https://bugs.python.org/issue17295)
--- | :---
Nosy | @ronaldoussoren, @amauryfa, @vstinner, @vadmium
Superseder | <li>bpo-1173475: __slots__ for subclasses of variable length types</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-02-25.16:24:22.254>
labels = ['interpreter-core', 'type-bug']
title = '__slots__ on PyVarObject subclass'
updated_at = <Date 2015-03-12.05:27:03.174>
user = 'https://github.com/ronaldoussoren'
```

bugs.python.org fields:
```python
activity = <Date 2015-03-12.05:27:03.174>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2013-02-25.16:24:22.254>
creator = 'ronaldoussoren'
dependencies = []
files = []
hgrepos = []
issue_num = 17295
keywords = []
message_count = 5.0
messages = ['182959', '184637', '184640', '185397', '237914']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'amaury.forgeotdarc', 'vstinner', 'martin.panter']
pr_nums = []
priority = 'low'
resolution = 'duplicate'
stage = 'resolved'
status = 'open'
superseder = '1173475'
type = 'behavior'
url = 'https://bugs.python.org/issue17295'
versions = ['Python 3.4']
```

</p></details>

**Comment by encukou** [comment]
For this to work, the interpreter must know the type's memory layout.
So, in 2023 in Python 3.12, we can solve it for types with PEP 697's `Py_TPFLAGS_ITEMS_AT_END`, but for `tuple` or `int` we'd need to make their layout known (possibly we could hardcode it for those types only, but even then, documenting what kind of access is safe re. other types or subclasses might turn out to be a PEP-sized chunk of work).

Let's use gh-103740 for enabling this with `Py_TPFLAGS_ITEMS_AT_END`.
