### ISSUE TITLE
doctest test finder doesnt find line numbers of properties

### ISSUE THREAD

**Issue by 5c73c3f1-a755-4c78-96dd-40b0c879cd4b** [python/cpython#61648]
BPO | [17446](https://bugs.python.org/issue17446)
--- | :---
Nosy | @blueyed, @bitdancer, @RonnyPfannschmidt, @Vgr255, @mscuthbert, @timofurrer
PRs | <li>python/cpython#3419</li>
Files | <li>[fix_issue_17446.patch](https://bugs.python.org/file41769/fix_issue_17446.patch "Uploaded as text/plain at 2016-02-01.01:51:28 by @timofurrer")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-03-17.16:08:27.046>
labels = ['type-bug', '3.7']
title = 'doctest test finder doesnt find line numbers of properties'
updated_at = <Date 2019-10-28.17:25:43.144>
user = 'https://github.com/RonnyPfannschmidt'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-28.17:25:43.144>
actor = 'blueyed'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2013-03-17.16:08:27.046>
creator = 'Ronny.Pfannschmidt'
dependencies = []
files = ['41769']
hgrepos = []
issue_num = 17446
keywords = ['patch']
message_count = 12.0
messages = ['184384', '228122', '259300', '259306', '259618', '259620', '259621', '261372', '262146', '293747', '303699', '355572']
nosy_count = 6.0
nosy_names = ['blueyed', 'r.david.murray', 'Ronny.Pfannschmidt', 'abarry', 'mscuthbert', 'tuxtimo']
pr_nums = ['3419']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17446'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-113161
* gh-113164
* gh-113165

**Comment by f8c46d9f-f92e-420f-956b-d795f5ff26ab** [comment]
just poking to see if this patch is worth trying to get into 3.7

**Comment by f8c46d9f-f92e-420f-956b-d795f5ff26ab** [comment]
A pull request has been in for about a month -- is it possible to review or merge or comment?  Thanks!

**Comment by mscuthbert** [comment]
The code I contributed to 3.7 is still, I believe, the best path forward.  Based on my experiences trying to contribute to cpython, I will not be continuing on this issue.  It can be closed.
