### ISSUE TITLE
OS X test for Tk availability doesn't work

### ISSUE THREAD

**Issue by alex** [python/cpython#61698]
BPO | [17496](https://bugs.python.org/issue17496)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @glyph, @alex, @roseman
Files | <li>[tk-cond.diff](https://bugs.python.org/file29510/tk-cond.diff "Uploaded as text/plain at 2013-03-20.19:50:04 by @alex")</li><li>[issue-17496.txt](https://bugs.python.org/file29990/issue-17496.txt "Uploaded as text/plain at 2013-04-23.12:30:21 by @ronaldoussoren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ronaldoussoren'
closed_at = None
created_at = <Date 2013-03-20.19:50:05.038>
labels = ['OS-mac', 'type-bug', 'expert-tkinter', '3.8', '3.7', 'tests']
title = "OS X test for Tk availability in runtktests.py doesn't work"
updated_at = <Date 2018-06-27.07:17:07.088>
user = 'https://github.com/alex'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-27.07:17:07.088>
actor = 'ronaldoussoren'
assignee = 'ronaldoussoren'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Tests', 'Tkinter']
creation = <Date 2013-03-20.19:50:05.038>
creator = 'alex'
dependencies = []
files = ['29510', '29990']
hgrepos = []
issue_num = 17496
keywords = ['patch']
message_count = 14.0
messages = ['184784', '184843', '184844', '184845', '184846', '184850', '184851', '184862', '187632', '193592', '219025', '219028', '320500', '320551']
nosy_count = 6.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'glyph', 'alex', 'markroseman', 'jesstess']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17496'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-118390
* gh-125392
* gh-125393

**Comment by serhiy-storchaka** [comment]
runtktests.py was removed in f59ed3c310a7ceebf2a56a84ea969a7f75d95b64 (bpo-45229).

**Comment by ronaldoussoren** [comment]
> > runtktests.py was removed in [f59ed3c](https://github.com/python/cpython/commit/f59ed3c310a7ceebf2a56a84ea969a7f75d95b64) ([bpo-45229](https://bugs.python.org/issue?@action=redirect&bpo=45229)).
> 
> The code is now in `Lib/test/support/__init__.py`, and it is still a nuisance on macOS.
> 
> https://github.com/python/cpython/blob/23d0371bb99b1df183c36883e256f82fdf6a4bea/Lib/test/support/__init__.py#L247-L269

It might be worthwhile to check if using the output of `launchctl managername` is more useful. This is Aqua for GUI sessions and Background for SSH sessions.  The disadvantage is that this subcommand is documented as part of the legacy subcommands, but that's not worse that using `GetCurrentProcess` which is explicitly deprecated.

**Comment by erlend-aasland** [comment]
`launchctl managername` indeed looks more useful. As you say, the man page says it is a legacy command. Quoting `launchctl --help`:

> When using a legacy subcommand which manipulates a domain, the target domain is
inferred from the current execution context. When run as root (whether it is
via a root shell or sudo(1)), the target domain is assumed to be the
system-wide domain. When run from a normal user's shell, the target is assumed
to be the per-user domain for that current user.

We're not manipulating anything, so it seems to me we can safely use the legacy command to query the manager name.

**Comment by erlend-aasland** [comment]
Quoting Ned:

> Also, "launchctl managername" does not appear to be available on releases prior to 10.6, releases we still support.

IIRC, we don't officially support 10.6 anymore.

**Comment by ronaldoussoren** [comment]
> Quoting Ned:
> 
> > Also, "launchctl managername" does not appear to be available on releases prior to 10.6, releases we still support.
> 
> IIRC, we don't officially support 10.6 anymore.

Not in CI at least. Anyone supporting old OS versions can keep using the old check, MacPorts already carries a number of patches to support ancient versions of macOS.

**Comment by erlend-aasland** [comment]
Something like #118390 should work; if `launchctl` fails, we skip with a message similar to what we have now; if it succeeds, use the result (and if the result is garbled, something is incredibly wrong, so don't fail graciously)

**Comment by erlend-aasland** [comment]
I believe we can now close this. Thanks to everyone involved.
