### ISSUE TITLE
Document the circumstances where the locals() dict get updated

### ISSUE THREAD

**Issue by 9432cd65-9f88-4bc6-8ad6-72e5ab1c730d** [python/cpython#61746]
BPO | [17546](https://bugs.python.org/issue17546)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @amauryfa, @ncoghlan, @nedbat, @merwok, @bitdancer, @florentx, @ericsnowcurrently, @vadmium
Files | <li>[locals_doc.patch](https://bugs.python.org/file29614/locals_doc.patch "Uploaded as text/plain at 2013-03-30.21:53:50 by @bitdancer")</li><li>[issue17546.stoneleaf.01.patch](https://bugs.python.org/file37711/issue17546.stoneleaf.01.patch "Uploaded as text/plain at 2015-01-15.04:44:00 by @ethanfurman")</li><li>[locals_doc.03.patch](https://bugs.python.org/file39833/locals_doc.03.patch "Uploaded as text/plain at 2015-06-29.15:09:56 by @vadmium")</li><li>[locals_doc.04.patch](https://bugs.python.org/file45735/locals_doc.04.patch "Uploaded as text/plain at 2016-12-03.04:44:04 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-03-25.17:20:11.304>
labels = ['type-feature', '3.7', 'docs']
title = 'Document the circumstances where the locals() dict get updated'
updated_at = <Date 2016-12-03.04:44:05.501>
user = 'https://bugs.python.org/techtonik'
```

bugs.python.org fields:
```python
activity = <Date 2016-12-03.04:44:05.501>
actor = 'martin.panter'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2013-03-25.17:20:11.304>
creator = 'techtonik'
dependencies = []
files = ['29614', '37711', '39833', '45735']
hgrepos = []
issue_num = 17546
keywords = ['patch']
message_count = 42.0
messages = ['185213', '185215', '185216', '185260', '185276', '185282', '185290', '185320', '185321', '185324', '185325', '185327', '185332', '185335', '185336', '185339', '185350', '185358', '185359', '185399', '185404', '185405', '185440', '185473', '185491', '185544', '185558', '185567', '185575', '185585', '185593', '185601', '185613', '185615', '234049', '234072', '234076', '234078', '245922', '245924', '245942', '282267']
nosy_count = 13.0
nosy_names = ['georg.brandl', 'terry.reedy', 'amaury.forgeotdarc', 'ncoghlan', 'techtonik', 'nedbat', 'bgailer', 'eric.araujo', 'r.david.murray', 'flox', 'docs@python', 'eric.snow', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue17546'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ncoghlan** [comment]
PEP 667 has resolved this issue for Python 3.13b1
