### ISSUE TITLE
unable to disable -r in run_tests.py

### ISSUE THREAD

**Issue by doko42** [python/cpython#61974]
BPO | [17774](https://bugs.python.org/issue17774)
--- | :---
Nosy | @doko42, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-04-17.13:03:01.616>
labels = ['3.8', 'type-bug', 'tests']
title = 'unable to disable -r in run_tests.py'
updated_at = <Date 2019-05-18.01:19:59.944>
user = 'https://github.com/doko42'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-18.01:19:59.944>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-04-17.13:03:01.616>
creator = 'doko'
dependencies = []
files = []
hgrepos = []
issue_num = 17774
keywords = []
message_count = 2.0
messages = ['187160', '342781']
nosy_count = 2.0
nosy_names = ['doko', 'cheryl.sabella']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17774'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
run_tests.py no longer exists.

**Comment by terryjreedy** [comment]
The default today is to run tests sequentially in alphabetical order.  Passing -r randomizes the sequential order.  Passing -jn runs tests in what appears to be a deterministic but undocumented and likely subject-to-change non-alphabetical order.  Passing both randomizes a parallel run.  So it seems the request above is fulfilled and is appropriately closed.  It does not matter what the situation was in 3.8.  Starting parallel tests alphabetically would not result in them finishing and being reported alphabetically.
