### ISSUE TITLE
Unhelpful UnboundLocalError due to del'ing of exception target

### ISSUE THREAD

**Issue by warsaw** [python/cpython#61992]
BPO | [17792](https://bugs.python.org/issue17792)
--- | :---
Nosy | @warsaw, @ncoghlan, @tiran, @benjaminp, @ezio-melotti, @bitdancer, @pmp-p, @ericsnowcurrently, @serhiy-storchaka, @phmc, @MojoVampire, @ilevkivskyi, @iritkatriel, @aaronwsmith
PRs | <li>python/cpython#24976</li>
Files | <li>[issue17792.diff](https://bugs.python.org/file29936/issue17792.diff "Uploaded as text/plain at 2013-04-19.04:53:21 by @ezio-melotti")</li><li>[issue17792-2.diff](https://bugs.python.org/file29989/issue17792-2.diff "Uploaded as text/plain at 2013-04-23.11:37:03 by @ezio-melotti")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-04-18.23:55:22.492>
labels = ['expert-tkinter', 'type-crash', '3.11']
title = "Unhelpful UnboundLocalError due to del'ing of exception target"
updated_at = <Date 2021-10-02.03:18:05.344>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-02.03:18:05.344>
actor = 'sppraveenkumarinfo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tkinter']
creation = <Date 2013-04-18.23:55:22.492>
creator = 'barry'
dependencies = []
files = ['29936', '29989']
hgrepos = []
issue_num = 17792
keywords = ['patch']
message_count = 21.0
messages = ['187313', '187315', '187319', '187320', '187322', '187326', '187327', '187328', '187339', '187342', '187382', '187433', '187627', '187639', '187640', '187645', '389264', '394902', '394903', '402980', '402992']
nosy_count = 15.0
nosy_names = ['barry', 'ncoghlan', 'christian.heimes', 'benjamin.peterson', 'ezio.melotti', 'Arfrever', 'r.david.murray', 'pmpp', 'eric.snow', 'serhiy.storchaka', 'pconnell', 'josh.r', 'levkivskyi', 'iritkatriel', 'aaronwsmith']
pr_nums = ['24976']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue17792'
versions = ['Python 3.11']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Is this issue already resolved?

**Comment by terryjreedy** [comment]
Yes, #24976 as described in https://github.com/python/cpython/issues/61992#issuecomment-1093614265 is the solution.  Anyone wanting further change should open a new issue.
