### ISSUE TITLE
There is no way to get a list of available codecs

### ISSUE THREAD

**Issue by pfmoore** [python/cpython#62078]
BPO | [17878](https://bugs.python.org/issue17878)
--- | :---
Nosy | @malemburg, @doerwalter, @pfmoore, @ncoghlan, @vstinner, @ezio-melotti
Files | <li>[codecs_searchers.py](https://bugs.python.org/file30107/codecs_searchers.py "Uploaded as text/plain at 2013-05-02.13:45:44 by dmi.baranov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-04-30.09:51:57.400>
labels = ['type-bug', 'library', 'expert-unicode']
title = 'There is no way to get a list of available codecs'
updated_at = <Date 2013-05-02.16:00:48.141>
user = 'https://github.com/pfmoore'
```

bugs.python.org fields:
```python
activity = <Date 2013-05-02.16:00:48.141>
actor = 'dmi.baranov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Unicode']
creation = <Date 2013-04-30.09:51:57.400>
creator = 'paul.moore'
dependencies = []
files = ['30107']
hgrepos = []
issue_num = 17878
keywords = []
message_count = 13.0
messages = ['188147', '188247', '188252', '188267', '188268', '188269', '188270', '188271', '188272', '188273', '188274', '188275', '188277']
nosy_count = 7.0
nosy_names = ['lemburg', 'doerwalter', 'paul.moore', 'ncoghlan', 'vstinner', 'ezio.melotti', 'dmi.baranov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17878'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by Nosh-Ware** [comment]
Is there no progress on this issue after all this time? Was really hoping to use this feature...

(I do understand that this is absolutely not a important feature by far and don't meant to distract from much more important features or fixes but I do find it kind of funny the amount of time this has been overlooked for if this really hasn't been done yet... Also sorry for necroposting)

**Comment by malemburg** [comment]
There is a list of standard codecs in the docs: https://docs.python.org/3/library/codecs.html#standard-encodings

I guess beyond that there hasn't been much interest in getting such functionality, also because it's not easy to implement, given that the codecs lookup works a lot like importing modules: you don't know whether a module exists until you try to import it.

Closing the ticket for now.
