### ISSUE TITLE
argparse: mutually exclusive groups full of help-suppressed args can cause AssertionErrors

### ISSUE THREAD

**Issue by b31dad55-0575-4ef0-a6d2-34cb8da700d2** [python/cpython#62090]
BPO | [17890](https://bugs.python.org/issue17890)
--- | :---
Nosy | @terryjreedy, @bitdancer, @vadmium, @iritkatriel
Files | <li>[argparse-assertfail.py](https://bugs.python.org/file30102/argparse-assertfail.py "Uploaded as text/plain at 2013-05-02.00:43:01 by gholms"): Test case</li><li>[7691d1d4b955.diff](https://bugs.python.org/file30108/7691d1d4b955.diff "Uploaded as text/plain at 2013-05-02.13:53:44 by Yogesh.Chaudhari"): gholms repo</li><li>[Issue17890-27.patch](https://bugs.python.org/file30110/Issue17890-27.patch "Uploaded as text/plain at 2013-05-02.16:22:44 by Yogesh.Chaudhari"): Resolution for Python 2.7 issue17890</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-05-02.00:43:02.387>
labels = ['type-bug', 'library']
title = 'argparse: mutually exclusive groups full of help-suppressed args can cause AssertionErrors'
updated_at = <Date 2021-12-10.16:06:27.619>
user = 'https://bugs.python.org/gholms'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.16:06:27.619>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-05-02.00:43:02.387>
creator = 'gholms'
dependencies = []
files = ['30102', '30108', '30110']
hgrepos = ['187']
issue_num = 17890
keywords = ['patch']
message_count = 17.0
messages = ['188250', '188253', '188278', '188291', '188295', '188306', '188337', '188379', '188413', '188984', '189054', '189064', '189065', '189355', '193191', '259189', '408217']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'bethard', 'r.david.murray', 'martin.panter', 'paul.j3', 'Yogesh.Chaudhari', 'gholms', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'patch review'
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue17890'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4']
```

</p></details>

### Linked PRs
* gh-105039

**Comment by encukou** [comment]
The reproducer needs a narrow enough console, or a bigger number for the `'eggs' * 20`.

This was fixed in #96311.
