### ISSUE TITLE
lzma module very slow with line-oriented reading.

### ISSUE THREAD

**Issue by a9df0fde-7689-421b-b7f0-1aa0a7f58766** [python/cpython#62203]
BPO | [18003](https://bugs.python.org/issue18003)
--- | :---
Nosy | @rhettinger, @pitrou, @vstinner, @larryhastings, @merwok, @vadmium, @serhiy-storchaka
Files | <li>[decomp-optim.patch](https://bugs.python.org/file39586/decomp-optim.patch "Uploaded as text/plain at 2015-06-01.13:51:13 by @vadmium")</li><li>[decomp-optim.v2.patch](https://bugs.python.org/file39604/decomp-optim.v2.patch "Uploaded as text/plain at 2015-06-03.11:12:52 by @vadmium")</li><li>[decomp-optim.v3.patch](https://bugs.python.org/file39640/decomp-optim.v3.patch "Uploaded as text/plain at 2015-06-06.14:19:56 by @serhiy-storchaka")</li><li>[decomp-optim.v4.patch](https://bugs.python.org/file39662/decomp-optim.v4.patch "Uploaded as text/plain at 2015-06-09.13:41:11 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2013-05-17.22:27:24.084>
labels = ['library', 'performance']
title = 'lzma module very slow with line-oriented reading.'
updated_at = <Date 2015-06-10.03:07:25.210>
user = 'https://bugs.python.org/MichaelFox'
```

bugs.python.org fields:
```python
activity = <Date 2015-06-10.03:07:25.210>
actor = 'martin.panter'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-05-17.22:27:24.084>
creator = 'Michael.Fox'
dependencies = []
files = ['39586', '39604', '39640', '39662']
hgrepos = []
issue_num = 18003
keywords = ['patch']
message_count = 44.0
messages = ['189488', '189542', '189550', '189552', '189553', '189567', '189568', '189575', '189592', '189605', '189611', '189616', '189665', '189668', '189675', '189676', '189679', '189680', '189922', '198144', '198146', '198160', '198161', '233870', '244582', '244691', '244696', '244698', '244702', '244729', '244734', '244735', '244738', '244739', '244904', '244909', '244967', '244969', '245064', '245066', '245067', '245090', '245096', '245107']
nosy_count = 10.0
nosy_names = ['rhettinger', 'pitrou', 'vstinner', 'larry', 'nadeem.vawda', 'eric.araujo', 'Arfrever', 'martin.panter', 'serhiy.storchaka', 'Michael.Fox']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue18003'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
It sounds from the discussion that this optimization was considered not worth doing after all. Shall we close the issue as suggested in https://github.com/python/cpython/issues/62203#issuecomment-1093617164?
