### ISSUE TITLE
Updating _fields_ of a derived struct type yields a bad cif

### ISSUE THREAD

**Issue by 2d975570-5778-44d0-a1fd-d61cd551eaa4** [python/cpython#62260]
BPO | [18060](https://bugs.python.org/issue18060)
--- | :---
Nosy | @amauryfa, @abalkin, @meadori, @websurfer5
PRs | <li>python/cpython#13374</li>
Files | <li>[t1.py](https://bugs.python.org/file30369/t1.py "Uploaded as text/plain at 2013-05-25.19:07:25 by lauri.alanko"): Test case</li><li>[t2.py](https://bugs.python.org/file48332/t2.py "Uploaded as text/plain at 2019-05-16.22:56:45 by @websurfer5"): test case uses PyCStructUnionType_update_stgdict() but not PyCStgDict_clone()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-05-25.19:07:26.282>
labels = ['ctypes', '3.7', '3.8', 'type-crash']
title = 'Updating _fields_ of a derived struct type yields a bad cif'
updated_at = <Date 2019-05-17.04:20:58.133>
user = 'https://bugs.python.org/laurialanko'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-17.04:20:58.133>
actor = 'Jeffrey.Kintscher'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2013-05-25.19:07:26.282>
creator = 'lauri.alanko'
dependencies = []
files = ['30369', '48332']
hgrepos = []
issue_num = 18060
keywords = ['patch']
message_count = 6.0
messages = ['189992', '228414', '342505', '342520', '342532', '342676']
nosy_count = 5.0
nosy_names = ['amaury.forgeotdarc', 'belopolsky', 'meador.inge', 'lauri.alanko', 'Jeffrey.Kintscher']
pr_nums = ['13374']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue18060'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-113623
* gh-113624

**Comment by serhiy-storchaka** [comment]
The `length` field was used in two incompatible meanings. In `PyCStgDict_clone()` it was the total number of items in `ffi_type_pointer.elements` (excluding the trailing null). In `PyCStructUnionType_update_stgdict()` and `_init_pos_args()` it was the the number of items added in this class, not including inherited items. There are two ways to resolve this:

1. Calculate the total number in `PyCStgDict_clone()` by traversing recursively base classes.
2. Keep the total number in `length` and change `PyCStructUnionType_update_stgdict()` and `_init_pos_args()`.

I choose the second option as simpler in long term.
