### ISSUE TITLE
Add an 'attr' attribute to AttributeError

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#62356]
BPO | [18156](https://bugs.python.org/issue18156)
--- | :---
Nosy | @brettcannon, @vstinner, @6502, @benjaminp, @ezio-melotti, @merwok, @alex, @flying-sheep, @serhiy-storchaka, @zhangyangyu
Files | <li>[attributeerror-attr.patch](https://bugs.python.org/file30829/attributeerror-attr.patch "Uploaded as text/plain at 2013-07-06.16:56:11 by kermit666")</li><li>[client.py](https://bugs.python.org/file40757/client.py "Uploaded as text/plain at 2015-10-12.16:30:54 by Shubham Dash")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-06-07.15:31:50.189>
labels = ['interpreter-core', 'type-feature']
title = "Add an 'attr' attribute to AttributeError"
updated_at = <Date 2017-08-18.16:16:17.429>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-18.16:16:17.429>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2013-06-07.15:31:50.189>
creator = 'brett.cannon'
dependencies = []
files = ['30829', '40757']
hgrepos = ['203']
issue_num = 18156
keywords = ['patch']
message_count = 15.0
messages = ['190754', '190783', '190787', '190788', '190789', '192466', '192468', '192470', '192555', '229928', '230501', '230504', '261307', '261355', '261394']
nosy_count = 11.0
nosy_names = ['brett.cannon', 'vstinner', 'ag6502', 'benjamin.peterson', 'ezio.melotti', 'eric.araujo', 'alex', 'flying sheep', 'serhiy.storchaka', 'kermit666', 'xiang.zhang']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18156'
versions = ['Python 3.4']
```

</p></details>

**Comment by hauntsaninja** [comment]
This has existed since Python 3.10 ("name" attribute)
