### ISSUE TITLE
ERROR: test_no_optimize_flag on Mageia Linux Cauldron x86-64 with certain configure flags

### ISSUE THREAD

**Issue by 59062004-5199-4539-afa5-e89c3bd56d93** [python/cpython#62388]
BPO | [18188](https://bugs.python.org/issue18188)
--- | :---
Nosy | @pitrou, @giampaolo, @bitdancer, @shlomif
Files | <li>[python-3.4.1-make-test.txt](https://bugs.python.org/file36434/python-3.4.1-make-test.txt "Uploaded as text/plain at 2014-08-22.05:38:26 by @shlomif")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-06-11.10:32:08.612>
labels = ['type-bug', 'tests']
title = 'ERROR: test_no_optimize_flag on Mageia Linux Cauldron x86-64 with certain configure flags'
updated_at = <Date 2019-04-26.20:29:35.329>
user = 'https://github.com/shlomif'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.20:29:35.329>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-06-11.10:32:08.612>
creator = 'shlomif'
dependencies = []
files = ['36434']
hgrepos = []
issue_num = 18188
keywords = []
message_count = 9.0
messages = ['190959', '190961', '190963', '190967', '190969', '190970', '190975', '224442', '225646']
nosy_count = 4.0
nosy_names = ['pitrou', 'giampaolo.rodola', 'r.david.murray', 'shlomif']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18188'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.4 is not supported and our CI is passing so closing. If this issue exists, a new issue with reproducer targeting supported python versions should be created.
