### ISSUE TITLE
running a suite with no tests is not an error

### ISSUE THREAD

**Issue by rbtcollins** [python/cpython#62432]
BPO | [18232](https://bugs.python.org/issue18232)
--- | :---
Nosy | @terryjreedy, @rbtcollins, @ezio-melotti, @voidspace, @mgorny, @kamilturek
PRs | <li>python/cpython#24893</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-06-16.19:32:39.867>
labels = ['type-feature', 'tests', '3.10']
title = 'running a suite with no tests is not an error'
updated_at = <Date 2021-03-16.12:25:51.548>
user = 'https://github.com/rbtcollins'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-16.12:25:51.548>
actor = 'mgorny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-06-16.19:32:39.867>
creator = 'rbcollins'
dependencies = []
files = []
hgrepos = []
issue_num = 18232
keywords = ['patch']
message_count = 8.0
messages = ['191282', '191611', '192331', '226617', '226620', '226631', '388669', '388682']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'rbcollins', 'ezio.melotti', 'michael.foord', 'mgorny', 'kamilturek']
pr_nums = ['24893']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18232'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-102051

**Comment by gpshead** [comment]
https://discuss.python.org/t/unittest-fail-if-zero-tests-were-discovered/21498

**Comment by terryjreedy** [comment]
#98903 makes the Python test suite fail is no test are run.
@vstinner Do you think unittest should be modified?

**Comment by vstinner** [comment]
> @vstinner Do you think unittest should be modified?

I don't know unittest test runner. I have no opinion. Changing the behavior would be backward incompatible.

As a libregrtest user.... and as the author of the change (!), I like the new Python test runner (libregrtest) behavior, obviously :-) https://discuss.python.org/t/unittest-fail-if-zero-tests-were-discovered/21498/5

**Comment by merwok** [comment]
I think it should be an error, for reasons explained in the thread.
Using the same error code as pytest seems good.
