### ISSUE TITLE
ElementTree -- provide a way to ignore namespace in tags and searches

### ISSUE THREAD

**Issue by 8e115224-c151-4882-8772-a3cb861f588d** [python/cpython#62504]
BPO | [18304](https://bugs.python.org/issue18304)
--- | :---
Nosy | @rhettinger, @scoder, @vadmium
Files | <li>[etree_strip_namespaces.patch](https://bugs.python.org/file43912/etree_strip_namespaces.patch "Uploaded as text/plain at 2016-07-27.17:59:04 by @scoder")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-06-26.03:48:17.212>
labels = ['expert-XML', '3.8', 'type-feature', 'library']
title = 'ElementTree -- provide a way to ignore namespace in tags and searches'
updated_at = <Date 2021-03-23.15:12:20.604>
user = 'https://bugs.python.org/brycenesbitt'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-23.15:12:20.604>
actor = 'lars.hammarstrand'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'XML']
creation = <Date 2013-06-26.03:48:17.212>
creator = 'brycenesbitt'
dependencies = []
files = ['43912']
hgrepos = []
issue_num = 18304
keywords = ['patch']
message_count = 19.0
messages = ['191894', '194896', '194899', '194901', '194906', '194919', '194920', '194923', '216768', '216774', '235724', '271448', '271466', '271472', '271475', '305405', '341000', '341001', '389391']
nosy_count = 9.0
nosy_names = ['rhettinger', 'scoder', 'eli.bendersky', 'martin.panter', 'brycenesbitt', 'pocek', 'jjmiller50', 'Tim Chambers', 'lars.hammarstrand']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18304'
versions = ['Python 3.8']
```

</p></details>

**Comment by 2d5775f8-5d93-408d-8cb5-28be7bd311be** [comment]
I suggest adding the option to keep the namespace prefixes in the tree when reading in (will it need to set a tree wide variable for the instance?). I haven't looked at the etree internals in detail.

Add a function to ElementTree that returns the tag using the namespace prefix (eg. treenode.tagpre). Namespaces and prefixes are cached and used to expand the prefix only when absolutely required. Some XML/xpath search operations currently assume the full expanded namespaces not prefixes which may lead to side-effects.
You can leave the default behaviour for compatibility.
Using prefixes in the tree storage and searches would reduce memory and CPU time (when no expansion is required).

**Comment by aigarius** [comment]
This is really messing up a lot of workflows. Example:

```
import io
import xml.etree.ElementTree as ET

afile = io.BytesIO(b'<?xml version="1.0" encoding="UTF-8" standalone="yes"?><root xmlns="http://example.com/2008/test.nsp"><child><grand></grand></child></root>')
et = ET.parse(afile)
afile.seek(0)
et.write(afile)
afile.seek(0)
afile.read()

Output: 
b'<ns0:root xmlns:ns0="http://example.com/2008/test.nsp"><ns0:child><ns0:grand /></ns0:child></ns0:root><child><grand></grand></child></root>'

```

Who asked Python to rewrite the name of *all* tags to include the id of the *only* namespace that is there in the document? It should automatically figure out the default namespace and consistently use it *as* the default namespace. Plus it is losing the XML version information tag. The expectation would be that parsing and dumping a simple XML file like that would produce byte-identical output.

**Comment by scoder** [comment]
> The expectation would be that parsing and dumping a simple XML file like that would produce byte-identical output.

This is an invalid assumption. XML parser applies a couple of adaptations such as whitespace normalisation that prevent byte-identical reproduction. Additionally, namespace prefixes are volatile, they do not have semantic meaning but only exist for technical reasons. There is no reason (apart from human readability) why namespace prefixes need to be preserved across input-output cycles.

If you want byte-identical reproduction, use canonical XML. That's the one and only reason why it exists.

**Comment by scoder** [comment]
> Who asked Python to rewrite the name of _all_ tags to include the id of the _only_ namespace that is there in the document? It should automatically figure out the default namespace and consistently use it _as_ the default namespace.

I don't think everyone would be happy about the slowdown in serialisation that this would introduce. Currently, the prefix mapping can be built on the fly during serialisation. In order to optimise the namespace prefixes for the case of a single namespace, we'd have to walk the entire document up-front to collect all namespaces, then create a prefix mapping, and then walk the entire tree again to serialise it using that mapping.

This double walk would hit all serialisations, not only those that use namespaces, or those that use multiple namespaces. The intention to produce slightly more human readable XML output in a single use case really is not worth that impact.

**Comment by scoder** [comment]
After resolving https://github.com/python/cpython/issues/72425 and https://github.com/python/cpython/issues/74670 back in 2019 (Python 3.8), I actually think that we can close this issue. The main processing problems with wildcards should be resolved by these changes.
