### ISSUE TITLE
Fix Bluetooth address parser

### ISSUE THREAD

**Issue by eb124d96-f186-4a94-9acb-5e04fc7f01dc** [python/cpython#62764]
BPO | [18564](https://bugs.python.org/issue18564)
--- | :---
Nosy | @pitrou, @vstinner, @mmaker, @serhiy-storchaka, @zooba, @csabella
PRs | <li>python/cpython#12864</li>
Files | <li>[btoverflow.patch](https://bugs.python.org/file31041/btoverflow.patch "Uploaded as text/plain at 2013-07-26.17:59:04 by @mmaker")</li><li>[issue18564.1.patch](https://bugs.python.org/file31056/issue18564.1.patch "Uploaded as text/plain at 2013-07-27.21:43:16 by @mmaker")</li><li>[issue18564.2.patch](https://bugs.python.org/file35112/issue18564.2.patch "Uploaded as text/plain at 2014-04-30.12:19:20 by @mmaker")</li><li>[issue18564.3.patch](https://bugs.python.org/file35146/issue18564.3.patch "Uploaded as text/plain at 2014-05-03.16:49:47 by @mmaker")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-07-26.17:59:05.783>
labels = ['extension-modules', '3.8', 'type-bug', '3.7']
title = 'Fix Bluetooth address parser'
updated_at = <Date 2019-05-26.17:59:02.673>
user = 'https://github.com/mmaker'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-26.17:59:02.673>
actor = 'maker'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2013-07-26.17:59:05.783>
creator = 'maker'
dependencies = []
files = ['31041', '31056', '35112', '35146']
hgrepos = []
issue_num = 18564
keywords = ['patch']
message_count = 16.0
messages = ['193736', '193795', '196305', '196306', '196309', '217453', '217664', '217665', '217825', '218128', '220189', '339896', '340421', '340444', '340676', '340694']
nosy_count = 8.0
nosy_names = ['pitrou', 'vstinner', 'Arfrever', 'neologix', 'maker', 'serhiy.storchaka', 'steve.dower', 'cheryl.sabella']
pr_nums = ['12864']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18564'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Closing, since there is no the claimed integer overflow here, and the PR was broken since 2019.
