### ISSUE TITLE
test failures on KFreeBSD

### ISSUE THREAD

**Issue by doko42** [python/cpython#62851]
BPO | [18651](https://bugs.python.org/issue18651)
--- | :---
Nosy | @loewis, @doko42, @ronaldoussoren, @vstinner
Files | <li>[kfreebsd.diff](https://bugs.python.org/file31148/kfreebsd.diff "Uploaded as text/plain at 2013-08-04.10:07:05 by @doko42")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-08-04.10:07:05.911>
labels = ['type-bug', 'tests']
title = 'test failures on KFreeBSD'
updated_at = <Date 2019-04-26.20:17:09.175>
user = 'https://github.com/doko42'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.20:17:09.175>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-08-04.10:07:05.911>
creator = 'doko'
dependencies = []
files = ['31148']
hgrepos = []
issue_num = 18651
keywords = ['patch']
message_count = 5.0
messages = ['194336', '194345', '194447', '194452', '224454']
nosy_count = 5.0
nosy_names = ['loewis', 'doko', 'ronaldoussoren', 'vstinner', 'salinger']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18651'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.4 is not supported anymore, feel free to create a new issue for supported python versions if the issue still exists.
