### ISSUE TITLE
Wrong struct members name for spwd module

### ISSUE THREAD

**Issue by ce7d5904-2ae0-4bc9-8085-2279bf8114aa** [python/cpython#62878]
BPO | [18678](https://bugs.python.org/issue18678)
--- | :---
Nosy | @pitrou, @bitdancer, @vajrasky
Files | <li>[spwd_struct_members_name_fix.patch](https://bugs.python.org/file31183/spwd_struct_members_name_fix.patch "Uploaded as text/plain at 2013-08-07.14:49:59 by @vajrasky")</li><li>[spwd_struct_members_name_fix_v2.patch](https://bugs.python.org/file31358/spwd_struct_members_name_fix_v2.patch "Uploaded as text/plain at 2013-08-18.15:04:47 by @vajrasky")</li><li>[spwd_struct_members_name_fix_v3.patch](https://bugs.python.org/file32152/spwd_struct_members_name_fix_v3.patch "Uploaded as text/plain at 2013-10-17.04:08:41 by @vajrasky")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-08-07.14:50:00.737>
labels = ['extension-modules', 'type-bug']
title = 'Wrong struct members name for spwd module'
updated_at = <Date 2014-03-08.13:51:49.389>
user = 'https://github.com/vajrasky'
```

bugs.python.org fields:
```python
activity = <Date 2014-03-08.13:51:49.389>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2013-08-07.14:50:00.737>
creator = 'vajrasky'
dependencies = []
files = ['31183', '31358', '32152']
hgrepos = []
issue_num = 18678
keywords = ['patch']
message_count = 8.0
messages = ['194618', '194619', '195566', '200107', '202074', '202075', '212917', '212930']
nosy_count = 4.0
nosy_names = ['pitrou', 'r.david.murray', 'python-dev', 'vajrasky']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue18678'
versions = ['Python 3.4']
```

</p></details>

**Comment by hugovk** [comment]
Note the spwd module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.
