### ISSUE TITLE
Increased test coverage for uu and telnet

### ISSUE THREAD

**Issue by b19910a1-40f7-4118-a30c-4e7896825923** [python/cpython#62931]
BPO | [18731](https://bugs.python.org/issue18731)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka
Files | <li>[telnet_uu_tests.patch](https://bugs.python.org/file31284/telnet_uu_tests.patch "Uploaded as text/plain at 2013-08-13.21:04:21 by Alex.Volkov")</li><li>[uu_test_v2.patch](https://bugs.python.org/file31489/uu_test_v2.patch "Uploaded as text/plain at 2013-08-27.22:44:21 by Alex.Volkov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-08-13.21:04:21.998>
labels = ['type-feature', 'tests']
title = 'Increased test coverage for uu and telnet'
updated_at = <Date 2014-11-19.07:42:26.715>
user = 'https://bugs.python.org/AlexVolkov'
```

bugs.python.org fields:
```python
activity = <Date 2014-11-19.07:42:26.715>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-08-13.21:04:21.998>
creator = 'Alex.Volkov'
dependencies = []
files = ['31284', '31489']
hgrepos = []
issue_num = 18731
keywords = ['patch']
message_count = 2.0
messages = ['196325', '231357']
nosy_count = 3.0
nosy_names = ['ezio.melotti', 'serhiy.storchaka', 'Alex.Volkov']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18731'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by hugovk** [comment]
I think we can close this one, especially as the uu module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.
