### ISSUE TITLE
timeit: Use thousands separators and print number of loops per second

### ISSUE THREAD

**Issue by e1cead32-4084-4b7e-a521-93555dbdc563** [python/cpython#63175]
BPO | [18975](https://bugs.python.org/issue18975)
--- | :---
Nosy | @tim-one, @pitrou, @ezio-melotti, @bitdancer, @serhiy-storchaka, @jstasiak, @csabella
Files | <li>[timeit.patch](https://bugs.python.org/file31672/timeit.patch "Uploaded as text/plain at 2013-09-08.16:00:30 by @jstasiak")</li><li>[timeit-v2.patch](https://bugs.python.org/file31673/timeit-v2.patch "Uploaded as text/plain at 2013-09-08.16:16:11 by @jstasiak")</li><li>[timeit-v3-actual-changes.patch](https://bugs.python.org/file31683/timeit-v3-actual-changes.patch "Uploaded as text/plain at 2013-09-08.19:48:10 by @jstasiak")</li><li>[timeit-v3-pep8.patch](https://bugs.python.org/file31684/timeit-v3-pep8.patch "Uploaded as text/plain at 2013-09-08.19:48:27 by @jstasiak")</li><li>[timeit-v3-actual-changes-no-separators.patch](https://bugs.python.org/file31786/timeit-v3-actual-changes-no-separators.patch "Uploaded as text/plain at 2013-09-16.01:17:46 by @jstasiak")</li><li>[timeit-v4-actual-changes.patch](https://bugs.python.org/file31792/timeit-v4-actual-changes.patch "Uploaded as text/plain at 2013-09-16.09:54:48 by @jstasiak")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-09-08.16:00:31.283>
labels = ['type-feature', 'library']
title = 'timeit: Use thousands separators and print number of loops per second'
updated_at = <Date 2017-08-27.13:46:09.639>
user = 'https://github.com/jstasiak'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-27.13:46:09.639>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-09-08.16:00:31.283>
creator = 'jstasiak'
dependencies = []
files = ['31672', '31673', '31683', '31684', '31786', '31792']
hgrepos = []
issue_num = 18975
keywords = ['patch']
message_count = 18.0
messages = ['197274', '197276', '197282', '197286', '197287', '197303', '197305', '197308', '197314', '197315', '197316', '197852', '197858', '197869', '197878', '197882', '197885', '300916']
nosy_count = 7.0
nosy_names = ['tim.peters', 'pitrou', 'ezio.melotti', 'r.david.murray', 'serhiy.storchaka', 'jstasiak', 'cheryl.sabella']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue18975'
versions = ['Python 3.4']
```

</p></details>

**Comment by csabella** [comment]
Reviewing this patch, it appears that the PEP-8 changes to timeit.py are already in the source and the discussion of the thousands separator is no longer an issue with the underscore changes in 3.6 (meaning underscore now seems the way to separate digits in large numbers, although it seems the vote was to remove all separators from timeit anyway).

That would leave the `loops per second` request the only one still needed from this patch.  But, with the subsequent change of selecting the time unit in timeit, perhaps this patch would need to be modified to print 'loops per {timeunit}'?
