### ISSUE TITLE
precise time.time() under Windows 8: use GetSystemTimePreciseAsFileTime

### ISSUE THREAD

**Issue by pitrou** [python/cpython#63207]
BPO | [19007](https://bugs.python.org/issue19007)
--- | :---
Nosy | @malemburg, @tim-one, @abalkin, @pitrou, @vstinner, @tjguk, @4kir4, @zware, @eryksun, @zooba
Files | <li>[time_precise.patch](https://bugs.python.org/file40088/time_precise.patch "Uploaded as text/plain at 2015-07-31.22:01:32 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-09-12.19:44:34.318>
labels = ['type-feature', 'library', 'OS-windows', '3.11']
title = 'precise time.time() under Windows 8: use GetSystemTimePreciseAsFileTime'
updated_at = <Date 2021-06-13.22:48:09.141>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-13.22:48:09.141>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2013-09-12.19:44:34.318>
creator = 'pitrou'
dependencies = []
files = ['40088']
hgrepos = []
issue_num = 19007
keywords = ['patch']
message_count = 9.0
messages = ['197538', '197539', '197541', '224358', '247024', '247778', '247779', '247808', '395767']
nosy_count = 10.0
nosy_names = ['lemburg', 'tim.peters', 'belopolsky', 'pitrou', 'vstinner', 'tim.golden', 'akira', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue19007'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-116822

**Comment by vstinner** [comment]
I wrote PR gh-116822 to use GetSystemTimePreciseAsFileTime() in time.time().

By the way, I also modified modified time.monotonic() to use QueryPerformanceCounter(): commit 846ad5a26ac0ff988a3fceec8f8e830f68bdf48a of issue gh-88494.

**Comment by vstinner** [comment]
Feature implemented in https://github.com/python/cpython/commit/1d95451be1f3080904c00cc4c4a6cc519efdf321. For the delay @pitrou, it took 12 years to implemente the function :-) I suppose that the delay was until all Windows versions supported by Python provide the function.
