### ISSUE TITLE
IDNA prefix should be case insensitive

### ISSUE THREAD

**Issue by 5e94c52b-378b-4f2f-9944-6a68db570d05** [python/cpython#63283]
BPO | [19083](https://bugs.python.org/issue19083)
--- | :---
Nosy | @loewis, @ZackerySpytz
PRs | <li>python/cpython#17726</li>
Files | <li>[upper-idna.patch](https://bugs.python.org/file31858/upper-idna.patch "Uploaded as text/plain at 2013-09-24.15:20:50 by Pepijn.de.Vos")</li><li>[upper-idna.patch](https://bugs.python.org/file31878/upper-idna.patch "Uploaded as text/plain at 2013-09-26.18:24:12 by Pepijn.de.Vos")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-09-24.15:20:51.183>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'IDNA prefix should be case insensitive'
updated_at = <Date 2021-05-22.17:27:48.889>
user = 'https://bugs.python.org/PepijndeVos'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-22.17:27:48.889>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-09-24.15:20:51.183>
creator = 'Pepijn.de.Vos'
dependencies = []
files = ['31858', '31878']
hgrepos = []
issue_num = 19083
keywords = ['patch']
message_count = 4.0
messages = ['198360', '198437', '198438', '198448']
nosy_count = 3.0
nosy_names = ['loewis', 'Pepijn.de.Vos', 'ZackerySpytz']
pr_nums = ['17726']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue19083'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-116866
* gh-116867

**Comment by encukou** [comment]
I'm not entirely convinced about doing the backports: the bug's been there for a decade, it doesn't look like a very important bug to fix. If it's backported to 3.12.3, programs tested there may break on 3.12.0
