### ISSUE TITLE
textwrap.dedent doesn't work properly with strings containing CRLF

### ISSUE THREAD

**Issue by 546a96b5-11f4-4421-8e22-4ec72254fb4f** [python/cpython#63678]
BPO | [19479](https://bugs.python.org/issue19479)
--- | :---
Nosy | @terryjreedy, @ncoghlan, @pitrou, @serhiy-storchaka, @emilyemorehouse
Files | <li>[dedent.patch](https://bugs.python.org/file32519/dedent.patch "Uploaded as text/plain at 2013-11-06.22:43:42 by alexis.d")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-02.14:50:18.362>
labels = ['type-feature', 'library', '3.11']
title = "textwrap.dedent doesn't work properly with strings containing CRLF"
updated_at = <Date 2022-01-21.07:03:38.371>
user = 'https://bugs.python.org/alexisd'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-21.07:03:38.371>
actor = 'georg.brandl'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-11-02.14:50:18.362>
creator = 'alexis.d'
dependencies = []
files = ['32519']
hgrepos = []
issue_num = 19479
keywords = ['patch']
message_count = 5.0
messages = ['201975', '202294', '296984', '297001', '297004']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ncoghlan', 'pitrou', 'serhiy.storchaka', 'alexis.d', 'emilyemorehouse']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue19479'
versions = ['Python 3.11']
```

</p></details>

**Comment by emilyemorehouse** [comment]
@georg.brandl and @terry.reedy, this issue was mentioned again recently (http://bugs.python.org/issue30754). 

Would you like to revisit it?

**Comment by terryjreedy** [comment]
Emily, do you have any opinion on the issue?  The complaint seems plausible, but I have not looked at the docs, nor the code to understand the import of '[^ \\t\\n]' (re for 'anything but space, tab, newline') matches '\\r'.

Alexis, you must sign the PSF contributor license agreement,
https://www.python.org/psf/contrib/
before we can use your patch.

**Comment by serhiy-storchaka** [comment]
I'm not sure that textwrap.dedent() should support the CRLF line separator. Usually the conversion between different line separators (CRLF, CR, LF) used in in external files and LF used internally is done at I/O level.

In any case this looks to me like rather a new feature than a bug fix.

**Comment by merwok** [comment]
Recent discussion was not in favour of changing this: https://discuss.python.org/t/add-support-for-crlf-in-textwrap-dedent/24022/5
