### ISSUE TITLE
request to reopen Issue837046 - pyport.h redeclares gethostname() if SOLARIS is defined

### ISSUE THREAD

**Issue by 48a1c83e-ecd9-4a3d-af39-0728a4f092e0** [python/cpython#63760]
BPO | [19561](https://bugs.python.org/issue19561)
--- | :---
Nosy | @jcea, @bitdancer, @0-wiz-0, @kulikjak
PRs | <li>python/cpython#23208</li>
Files | <li>[Python26-10-gethostname.patch](https://bugs.python.org/file32584/Python26-10-gethostname.patch "Uploaded as text/plain at 2013-11-12.14:39:40 by risto3")</li><li>[tp.cpp](https://bugs.python.org/file32592/tp.cpp "Uploaded as text/plain at 2013-11-13.04:36:21 by risto3"): test program</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-12.14:39:41.350>
labels = ['build', '3.8', '3.9', '3.10']
title = 'request to reopen Issue837046 - pyport.h redeclares gethostname() if SOLARIS is defined'
updated_at = <Date 2020-12-22.16:36:14.544>
user = 'https://bugs.python.org/risto3'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-22.16:36:14.544>
actor = 'kulikjak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2013-11-12.14:39:41.350>
creator = 'risto3'
dependencies = []
files = ['32584', '32592']
hgrepos = []
issue_num = 19561
keywords = ['patch']
message_count = 8.0
messages = ['202690', '202715', '202718', '202723', '202730', '240296', '380584', '380585']
nosy_count = 7.0
nosy_names = ['jcea', 'r.david.murray', 'wiz', 'python-dev', 'risto3', 'jbeck', 'kulikjak']
pr_nums = ['23208']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue19561'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-108817
* gh-108824
* gh-108832

**Comment by vstinner** [comment]
@kulikjak proposed at PR: https://github.com/python/cpython/pull/23208

**Comment by vstinner** [comment]
Thanks for the fix @kulikjak, it's now merged in the 3 maintained branches.

**Comment by vstinner** [comment]
See also issue #78469: Declare sethostname in socketmodule.c for SOLARIS.
