### ISSUE TITLE
Frame annotation

### ISSUE THREAD

**Issue by doerwalter** [python/cpython#63784]
BPO | [19585](https://bugs.python.org/issue19585)
--- | :---
Nosy | @doerwalter, @ncoghlan, @pitrou, @vstinner
Files | <li>[frame-annotation.diff](https://bugs.python.org/file32614/frame-annotation.diff "Uploaded as text/plain at 2013-11-14.17:09:29 by @doerwalter")</li><li>[code-annotation.diff](https://bugs.python.org/file32834/code-annotation.diff "Uploaded as text/plain at 2013-11-25.12:02:10 by @doerwalter")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-14.17:09:30.400>
labels = ['interpreter-core', 'type-feature']
title = 'Frame annotation'
updated_at = <Date 2014-01-16.04:29:39.677>
user = 'https://github.com/doerwalter'
```

bugs.python.org fields:
```python
activity = <Date 2014-01-16.04:29:39.677>
actor = 'ncoghlan'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2013-11-14.17:09:30.400>
creator = 'doerwalter'
dependencies = []
files = ['32614', '32834']
hgrepos = ['214']
issue_num = 19585
keywords = ['patch']
message_count = 10.0
messages = ['202862', '202864', '202865', '202902', '202908', '204329', '204337', '204364', '204410', '208233']
nosy_count = 4.0
nosy_names = ['doerwalter', 'ncoghlan', 'pitrou', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue19585'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
We now have PEP 678, so I'm closing. If there is a need for annotations on frames rather than the exception, I think this should be re-discovered in today's context, and a PEP proposed.

cc @Zac-HD
