### ISSUE TITLE
test_nntplib: sporadic failures, test_article_head_body()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#63812]
BPO | [19613](https://bugs.python.org/issue19613)
--- | :---
Nosy | @vstinner, @mcepl, @berkerpeksag, @vadmium, @koobs
Files | <li>[koobs-freebsd-10-python-3x-build-4682.txt](https://bugs.python.org/file43901/koobs-freebsd-10-python-3x-build-4682.txt "Uploaded as text/plain at 2016-07-27.00:58:18 by @koobs")</li><li>[ending-dot.patch](https://bugs.python.org/file43903/ending-dot.patch "Uploaded as text/plain at 2016-07-27.03:17:03 by @vadmium")</li><li>[ending-dot.v2.patch](https://bugs.python.org/file43905/ending-dot.v2.patch "Uploaded as text/plain at 2016-07-27.03:35:14 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-15.17:30:45.877>
labels = ['type-bug', 'tests']
title = 'test_nntplib: sporadic failures, test_article_head_body()'
updated_at = <Date 2020-05-22.21:28:47.631>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-22.21:28:47.631>
actor = 'chris.jerdonek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-11-15.17:30:45.877>
creator = 'vstinner'
dependencies = []
files = ['43901', '43903', '43905']
hgrepos = []
issue_num = 19613
keywords = ['patch', 'buildbot']
message_count = 19.0
messages = ['202961', '224475', '224476', '224481', '245538', '268972', '271423', '271426', '271428', '271429', '297134', '297529', '306936', '325829', '325921', '325923', '325924', '343039', '369649']
nosy_count = 5.0
nosy_names = ['vstinner', 'mcepl', 'berker.peksag', 'martin.panter', 'koobs']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue19613'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by vstinner** [comment]
Sorry, I lost track of this issue. What is the status?

@Martin: Do you want to convert your latest patch into a PR?

**Comment by vadmium** [comment]
It looks like I was fairly confident about my patch, but it was all theoretical and I was never able to analyze the failure myself.

Sorry but I am unlikely to spend much time on this or open a pull request any time soon.

**Comment by vadmium** [comment]
Victor opened bpo-32128 with the same complaint. I think I found the offending article:

```pycon
>>> server = NNTP_SSL("nntp.aioe.org")
>>> [response, count, first, last, name] = server.group("comp.lang.python")
>>> last
199267
>>> pprint(server.article(199265)[1].lines)
[. . .
 b'Date: Fri, 24 Nov 2017 15:44:26 -0800 (PST)',
 . . .
 b'Message-ID: <dcaddc9c-a7b7-4120-bd30-304f58566d3d@googlegroups.com>',
 b'Subject: Re: Python loop and web server (bottle) in the same script (Posting',
 b'     On Python-List Prohibited)',
 . . .
 b'Content-Transfer-Encoding: quoted-printable',
 . . .
 b'If processing is I/O bound and not CPU bound, then asyncio should work fine=',
 b'.']
```


The body uses Quoted-printable encoding, and the previous line ends with an equals sign “=”, meaning a soft line break. So the full stop is on its own because the encoder didn’t want to fit it on the previous line. This is valid (albeit quirky) encoding, and not a problem with the NNTP library.

**Comment by hugovk** [comment]
I think we can close this old issue because the nntplib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
Cc. @mcepl, @berkerpeksag, @vadmium, @koobs

**Comment by AlexWaygood** [comment]
> I think we can close this old issue because the nntplib module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

Cc. @mcepl, @berkerpeksag, @vadmium, @koobs

**Comment by mcepl** [comment]
I did that already when creating https://git.sr.ht/~mcepl/nntplib
