### ISSUE TITLE
test_nntplib: sporadic failures, network isses? server down?

### ISSUE THREAD

**Issue by vstinner** [python/cpython#63955]
BPO | [19756](https://bugs.python.org/issue19756)
--- | :---
Nosy | @pitrou, @vstinner, @berkerpeksag, @vadmium, @miss-islington
PRs | <li>python/cpython#9446</li><li>python/cpython#9447</li><li>python/cpython#9448</li><li>python/cpython#9450</li><li>python/cpython#9461</li>
Files | <li>[test_nntplib_logs.txt](https://bugs.python.org/file43441/test_nntplib_logs.txt "Uploaded as text/plain at 2016-06-17.21:20:33 by @berkerpeksag")</li><li>[nntp-server.patch](https://bugs.python.org/file43464/nntp-server.patch "Uploaded as text/plain at 2016-06-19.05:31:19 by @vadmium"): Custom local server</li><li>[original-order.diff](https://bugs.python.org/file43478/original-order.diff "Uploaded as text/plain at 2016-06-20.03:15:11 by @vadmium"): Smaller diff representing above changes</li><li>[multi-connect.patch](https://bugs.python.org/file46018/multi-connect.patch "Uploaded as text/plain at 2016-12-24.02:57:25 by @vadmium"): Each test creates new connection</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-24.18:07:31.280>
labels = ['3.7', '3.8', 'type-bug', 'tests']
title = 'test_nntplib: sporadic failures, network isses? server down?'
updated_at = <Date 2020-05-22.21:28:12.797>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-22.21:28:12.797>
actor = 'chris.jerdonek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2013-11-24.18:07:31.280>
creator = 'vstinner'
dependencies = []
files = ['43441', '43464', '43478', '46018']
hgrepos = []
issue_num = 19756
keywords = ['patch', 'buildbot']
message_count = 25.0
messages = ['204248', '204262', '223333', '245587', '268742', '268745', '268841', '268882', '283915', '292451', '297123', '325821', '325857', '325861', '325873', '325875', '325878', '325885', '325887', '325889', '325893', '325896', '325917', '325931', '369650']
nosy_count = 5.0
nosy_names = ['pitrou', 'vstinner', 'berker.peksag', 'martin.panter', 'miss-islington']
pr_nums = ['9446', '9447', '9448', '9450', '9461']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue19756'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
> ERROR: setUpClass (test.test_nntplib.NetworkedNNTP_SSLTests)

I wrote an obvious fix for this one: issue bpo-30188.

**Comment by vstinner** [comment]
Any progress on this issue?

Martin: Can you please convert your latest patch into a Pull Request?

**Comment by hugovk** [comment]
I think we can close this old issue and its [PR](https://github.com/python/cpython/pull/9461) because the nntplib module is deprecated in 3.11 and set for removal in 3.13?

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
@pitrou, @vstinner, @berkerpeksag, @vadmium, @miss-islington 

The original problem for which this issue as opened no longer appears to be affecting CPython (`test_nntplib` no longer sporadically fails, as far as I'm aware). Moreover, as @hugovk states, the `nntplib` module [is now deprecated](https://peps.python.org/pep-0594/#deprecated-modules), and has no active maintainer in the core dev team. This means enhancements and bugfixes for the module are now considered low priority.

Given the large backlog of issues in the CPython repo, I am therefore closing this issue.
