### ISSUE TITLE
NNTP: add post_message wrapper to post Email Message objects

### ISSUE THREAD

**Issue by c588983e-5cc4-4370-abc3-2109e4e34acc** [python/cpython#63969]
BPO | [19770](https://bugs.python.org/issue19770)
--- | :---
Nosy | @pitrou, @bitdancer, @csabella
PRs | <li>python/cpython#18061</li>
Files | <li>[nntp_test.py](https://bugs.python.org/file32836/nntp_test.py "Uploaded as text/plain at 2013-11-25.13:08:28 by sobczyk")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-11-25.12:28:44.337>
labels = ['3.8', 'type-feature', 'library']
title = 'NNTP: add post_message wrapper to post Email Message objects'
updated_at = <Date 2020-01-19.06:56:33.754>
user = 'https://bugs.python.org/sobczyk'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-19.06:56:33.754>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-11-25.12:28:44.337>
creator = 'sobczyk'
dependencies = []
files = ['32836']
hgrepos = []
issue_num = 19770
keywords = ['patch']
message_count = 10.0
messages = ['204331', '204336', '204342', '204346', '204347', '204348', '204349', '339874', '339879', '339981']
nosy_count = 4.0
nosy_names = ['pitrou', 'r.david.murray', 'sobczyk', 'cheryl.sabella']
pr_nums = ['18061']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue19770'
versions = ['Python 3.8']
```

</p></details>

**Comment by hugovk** [comment]
I think we can close this old issue because the nntplib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.
