### ISSUE TITLE
Update multiprocessing.spawn to use runpy.run_path

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#64177]
BPO | [19978](https://bugs.python.org/issue19978)
--- | :---
Nosy | @brettcannon, @ncoghlan, @nanjekyejoannah
Dependencies | <li>bpo-19697: Document the possible values for __main__.__spec__</li><li>bpo-19946: Handle a non-importable __main__ in multiprocessing</li><li>bpo-19982: Add a &quot;target&quot; parameter to runpy.run_path and runpy.run_module</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2013-12-13.16:44:41.261>
labels = ['library']
title = 'Update multiprocessing.spawn to use runpy.run_path'
updated_at = <Date 2019-08-06.17:41:06.983>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-06.17:41:06.983>
actor = 'nanjekyejoannah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2013-12-13.16:44:41.261>
creator = 'brett.cannon'
dependencies = ['19697', '19946', '19982']
files = []
hgrepos = []
issue_num = 19978
keywords = []
message_count = 2.0
messages = ['206117', '349122']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ncoghlan', 'jnoller', 'sbt', 'nanjekyejoannah']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue19978'
versions = ['Python 3.5']
```

</p></details>

**Comment by gpshead** [comment]
closing as obsolete as runpy.run_path doesn't appear to have that feature.  the general concept may have merit but needs someone aware of multiprocessing internals and exact compatibility semantics to decide.
