### ISSUE TITLE
Derby #7: Convert 51 sites to Argument Clinic across 3 files -> Derby: Convert the ElementTree module to use Argument Clinic

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#64358]
BPO | [20159](https://bugs.python.org/issue20159)
--- | :---
Nosy | @scoder, @larryhastings
Dependencies | <li>bpo-20141: Argument Clinic: broken support for &#x27;O!&#x27;</li><li>bpo-20157: Argument Clinic generates wrong keyword parameter name for &quot;default&quot;</li>
Files | <li>[etree_clinic.patch](https://bugs.python.org/file33526/etree_clinic.patch "Uploaded as text/plain at 2014-01-18.11:51:16 by @serhiy-storchaka")</li><li>[etree_clinic_2.patch](https://bugs.python.org/file38837/etree_clinic_2.patch "Uploaded as text/plain at 2015-04-05.09:53:29 by @serhiy-storchaka")</li><li>[etree_clinic_3.patch](https://bugs.python.org/file39285/etree_clinic_3.patch "Uploaded as text/plain at 2015-05-04.07:05:21 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-01-07.09:29:26.417>
labels = ['extension-modules', 'expert-XML', 'type-feature', 'expert-argument-clinic']
title = 'Derby #7: Convert 51 sites to Argument Clinic across 3 files -> Derby: Convert the ElementTree module to use Argument Clinic'
updated_at = <Date 2015-05-04.12:52:21.290>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2015-05-04.12:52:21.290>
actor = 'serhiy.storchaka'
assignee = 'eli.bendersky'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'XML', 'Argument Clinic']
creation = <Date 2014-01-07.09:29:26.417>
creator = 'serhiy.storchaka'
dependencies = ['20141', '20157']
files = ['33526', '38837', '39285']
hgrepos = []
issue_num = 20159
keywords = ['patch']
message_count = 13.0
messages = ['207518', '207597', '207624', '207630', '207631', '207632', '207633', '207638', '240106', '242545', '242546', '242552', '242554']
nosy_count = 4.0
nosy_names = ['scoder', 'larry', 'eli.bendersky', 'python-dev']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue20159'
versions = ['Python 3.5']
```

</p></details>

**Comment by arhadthedev** [comment]
Closing after gh-64383 (see discussion in that issue and #triage Discord channel).
