### ISSUE TITLE
The Great Argument Clinic Conversion Derby Meta-Issue

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#64386]
BPO | [20187](https://bugs.python.org/issue20187)
--- | :---
Nosy | @warsaw, @larryhastings, @bitdancer, @serhiy-storchaka
Dependencies | <li>bpo-20133: Derby: Convert the audioop module to use Argument Clinic</li><li>bpo-20148: Derby: Convert the _sre module to use Argument Clinic</li><li>bpo-20151: Derby: Convert the binascii module to use Argument Clinic</li><li>bpo-20152: Derby #15: Convert 50 sites to Argument Clinic across 9 files</li><li>bpo-20159: Derby #7: Convert 51 sites to Argument Clinic across 3 files -&gt; Derby: Convert the ElementTree module to use Argument Clinic</li><li>bpo-20168: Derby: Convert the _tkinter module to use Argument Clinic</li><li>bpo-20170: Derby #1: Convert 137 sites to Argument Clinic in Modules/posixmodule.c</li><li>bpo-20171: Derby #2: Convert 115 sites to Argument Clinic in Modules/_cursesmodule.c</li><li>bpo-20172: Derby #3: Convert 67 sites to Argument Clinic across 4 files (Windows)</li><li>bpo-20173: Derby #4: Convert 53 sites to Argument Clinic across 5 files</li><li>bpo-20174: Derby #5: Convert 50 sites to Argument Clinic across 3 files</li><li>bpo-20175: Derby #6: Convert 50 sites to Argument Clinic across 8 files</li><li>bpo-20177: Derby #8: Convert 28 sites to Argument Clinic across 2 files</li><li>bpo-20178: Derby #9: Convert 52 sites to Argument Clinic across 11 files</li><li>bpo-20179: Derby #10: Convert 50 sites to Argument Clinic across 4 files</li><li>bpo-20180: Derby #11: Convert 50 sites to Argument Clinic across 9 files</li><li>bpo-20181: Derby #12: Convert 50 sites to Argument Clinic across 4 files</li><li>bpo-20182: Derby #13: Convert 50 sites to Argument Clinic across 5 files</li><li>bpo-20183: Derby #14: Convert 41 sites to Argument Clinic across 5 files</li><li>bpo-20184: Derby #16: Convert 50 sites to Argument Clinic across 9 files</li><li>bpo-20185: Derby #17: Convert 49 sites to Argument Clinic across 13 files</li><li>bpo-20186: Derby #18: Convert 31 sites to Argument Clinic across 23 files</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2014-01-08.00:31:45.475>
labels = ['type-feature', 'expert-email', 'expert-argument-clinic']
title = 'The Great Argument Clinic Conversion Derby Meta-Issue'
updated_at = <Date 2018-06-14.17:51:04.719>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-14.17:51:04.719>
actor = 'BreamoreBoy'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['email', 'Argument Clinic']
creation = <Date 2014-01-08.00:31:45.475>
creator = 'larry'
dependencies = ['20133', '20148', '20151', '20152', '20159', '20168', '20170', '20171', '20172', '20173', '20174', '20175', '20177', '20178', '20179', '20180', '20181', '20182', '20183', '20184', '20185', '20186']
files = []
hgrepos = []
issue_num = 20187
keywords = []
message_count = 9.0
messages = ['207649', '207650', '207697', '208152', '208170', '208171', '208172', '208686', '208687']
nosy_count = 4.0
nosy_names = ['barry', 'larry', 'r.david.murray', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue20187'
versions = ['Python 3.4']
```

</p></details>

**Comment by AA-Turner** [comment]
@larryhastings Is this issue still relevant? All the AC PRs listed in the header are either merged or closed.

A

**Comment by kumaraditya303** [comment]
Individual issue can be created if required as this is completed.
