### ISSUE TITLE
setup.py: do not add system header locations when cross compiling

### ISSUE THREAD

**Issue by 95226e59-5ffc-4f16-ace8-c7dbbbb29bfd** [python/cpython#64410]
BPO | [20211](https://bugs.python.org/issue20211)
--- | :---
Nosy | @doko42, @vstinner, @zware, @tpetazzoni, @yan12125
Files | <li>[0001-setup.py-do-not-add-invalid-header-locations.patch](https://bugs.python.org/file33393/0001-setup.py-do-not-add-invalid-header-locations.patch "Uploaded as text/plain at 2014-01-09.23:02:08 by @tpetazzoni")</li><li>[no-native-headers-libraries.patch](https://bugs.python.org/file45830/no-native-headers-libraries.patch "Uploaded as text/plain at 2016-12-10.08:34:27 by @xdegaye")</li><li>[multiarch.patch](https://bugs.python.org/file45893/multiarch.patch "Uploaded as text/plain at 2016-12-14.10:19:04 by @xdegaye")</li><li>[multiarch_2.patch](https://bugs.python.org/file45894/multiarch_2.patch "Uploaded as text/plain at 2016-12-14.10:25:38 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-01-09.23:02:08.889>
labels = ['build', '3.7']
title = 'setup.py: do not add system header locations when cross compiling'
updated_at = <Date 2019-12-10.08:12:27.238>
user = 'https://github.com/tpetazzoni'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-10.08:12:27.238>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2014-01-09.23:02:08.889>
creator = 'thomas-petazzoni'
dependencies = []
files = ['33393', '45830', '45893', '45894']
hgrepos = []
issue_num = 20211
keywords = ['patch']
message_count = 12.0
messages = ['207805', '237380', '261435', '282640', '282641', '282836', '282837', '282841', '282843', '283182', '283183', '283184']
nosy_count = 7.0
nosy_names = ['doko', 'vstinner', 'python-dev', 'zach.ware', 'thomas-petazzoni', 'yan12125', 'hundeboll']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue20211'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`setup.py` no longer used to build CPython since 3.12 (see #94474).
