### ISSUE TITLE
Update patchcheck to looks for files with clinic comments

### ISSUE THREAD

**Issue by meadori** [python/cpython#64463]
BPO | [20264](https://bugs.python.org/issue20264)
--- | :---
Nosy | @ncoghlan, @pitrou, @larryhastings, @ezio-melotti, @meadori, @zware
Dependencies | <li>bpo-20326: Argument Clinic should use a non-error-prone syntax to mark text signatures</li>
Files | <li>[patchcheck-clinic.patch](https://bugs.python.org/file33471/patchcheck-clinic.patch "Uploaded as text/plain at 2014-01-15.03:12:38 by @meadori")</li><li>[detect.py](https://bugs.python.org/file33765/detect.py "Uploaded as text/plain at 2014-01-28.08:31:56 by @larryhastings"): Example script that sanity-checks all Clinic blocks in a file.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/meadori'
closed_at = None
created_at = <Date 2014-01-15.03:12:39.547>
labels = ['type-feature', 'expert-argument-clinic', 'build']
title = 'Update patchcheck to looks for files with clinic comments'
updated_at = <Date 2015-02-25.15:33:37.719>
user = 'https://github.com/meadori'
```

bugs.python.org fields:
```python
activity = <Date 2015-02-25.15:33:37.719>
actor = 'serhiy.storchaka'
assignee = 'meador.inge'
closed = False
closed_date = None
closer = None
components = ['Build', 'Argument Clinic']
creation = <Date 2014-01-15.03:12:39.547>
creator = 'meador.inge'
dependencies = ['20326']
files = ['33471', '33765']
hgrepos = []
issue_num = 20264
keywords = ['patch']
message_count = 5.0
messages = ['208132', '208133', '209070', '209165', '209511']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'pitrou', 'larry', 'ezio.melotti', 'meador.inge', 'zach.ware']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue20264'
versions = ['Python 3.4']
```

</p></details>

**Comment by erlend-aasland** [comment]
As I understand the OP, this is covered by the fairly new `check_generated_files` job in the CI. Closing as outdated.
