### ISSUE TITLE
concurrent.futures.as_completed() installs waiters for already completed Futures

### ISSUE THREAD

**Issue by db431f97-1886-4d6a-8181-337023d3059a** [python/cpython#64496]
BPO | [20297](https://bugs.python.org/issue20297)
--- | :---
Nosy | @brianquinlan, @mdickinson, @vstinner
Files | <li>[as_completed_proposed.py](https://bugs.python.org/file33590/as_completed_proposed.py "Uploaded as text/plain at 2014-01-21.15:19:28 by glangford")</li><li>[as_completed_proposed.patch](https://bugs.python.org/file33654/as_completed_proposed.patch "Uploaded as text/plain at 2014-01-23.13:48:02 by @vstinner")</li><li>[test_dupfuture.py](https://bugs.python.org/file33657/test_dupfuture.py "Uploaded as text/plain at 2014-01-23.14:43:21 by glangford")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-01-18.21:19:35.870>
labels = ['library', 'performance']
title = 'concurrent.futures.as_completed() installs waiters for already completed Futures'
updated_at = <Date 2014-07-18.16:46:17.165>
user = 'https://bugs.python.org/glangford'
```

bugs.python.org fields:
```python
activity = <Date 2014-07-18.16:46:17.165>
actor = 'glangford'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-01-18.21:19:35.870>
creator = 'glangford'
dependencies = []
files = ['33590', '33654', '33657']
hgrepos = []
issue_num = 20297
keywords = ['patch']
message_count = 7.0
messages = ['208418', '208593', '208652', '208921', '208942', '208943', '208974']
nosy_count = 3.0
nosy_names = ['bquinlan', 'mark.dickinson', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue20297'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by iritkatriel** [comment]
This issue seems to have been abandoned 8 years ago. Shall we close it or is someone planning to work on it?

cc @glangford
