### ISSUE TITLE
Argument Clinic: add "nullable ints"

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#64540]
BPO | [20341](https://bugs.python.org/issue20341)
--- | :---
Nosy | @loewis, @birkenfeld, @rhettinger, @larryhastings, @jkloth, @zware, @serhiy-storchaka, @vajrasky, @MojoVampire
Files | <li>[larry.nullable.ints.draft](https://bugs.python.org/file33605/larry.nullable.ints.draft "Uploaded as text/plain at 2014-01-22.03:17:59 by @larryhastings")</li><li>[larry.nullable.ints.draft.2](https://bugs.python.org/file33635/larry.nullable.ints.draft.2 "Uploaded as text/plain at 2014-01-22.21:05:12 by @larryhastings")</li><li>[larry.nullable.ints.draft.3](https://bugs.python.org/file33639/larry.nullable.ints.draft.3 "Uploaded as text/plain at 2014-01-22.23:48:33 by @larryhastings")</li><li>[larry.nullable.ints.4.txt](https://bugs.python.org/file36165/larry.nullable.ints.4.txt "Uploaded as text/plain at 2014-07-30.14:08:32 by @larryhastings")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2014-01-22.03:18:01.912>
labels = ['extension-modules', 'type-feature', 'expert-argument-clinic']
title = 'Argument Clinic: add "nullable ints"'
updated_at = <Date 2020-03-18.18:40:55.337>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-18.18:40:55.337>
actor = 'brett.cannon'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Argument Clinic']
creation = <Date 2014-01-22.03:18:01.912>
creator = 'larry'
dependencies = []
files = ['33605', '33635', '33639', '36165']
hgrepos = []
issue_num = 20341
keywords = []
message_count = 37.0
messages = ['208740', '208741', '208751', '208764', '208766', '208767', '208770', '208771', '208773', '208775', '208777', '208782', '208795', '208808', '208809', '208810', '208813', '208851', '208852', '208866', '208867', '208885', '208919', '208945', '208950', '208998', '209004', '209010', '209013', '209024', '209027', '224309', '224310', '224463', '224464', '224465', '224493']
nosy_count = 10.0
nosy_names = ['loewis', 'georg.brandl', 'rhettinger', 'larry', 'jkloth', 'Yury.Selivanov', 'zach.ware', 'serhiy.storchaka', 'vajrasky', 'josh.r']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue20341'
versions = ['Python 3.4']
```

</p></details>

**Comment by erlend-aasland** [comment]
There has been no further requests for this feature since 2014/2015. I suggest to close this as wont-implement. If someone really wants to drive this further, they can re-open.

**Comment by serhiy-storchaka** [comment]
See also #112068.
