### ISSUE TITLE
sqlite dumpiter dumps invalid script when virtual tables are used

### ISSUE THREAD

**Issue by 5c73c3f1-a755-4c78-96dd-40b0c879cd4b** [python/cpython#64662]
BPO | [20463](https://bugs.python.org/issue20463)
--- | :---
Nosy | @bitdancer, @RonnyPfannschmidt, @palaviv, @tirkarthi
Files | <li>[20463.patch](https://bugs.python.org/file45049/20463.patch "Uploaded as text/plain at 2016-10-10.18:04:18 by @palaviv")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-01-31.19:57:36.445>
labels = ['extension-modules', 'type-bug']
title = 'sqlite dumpiter dumps invalid script when virtual tables are used'
updated_at = <Date 2018-09-23.16:16:06.541>
user = 'https://github.com/RonnyPfannschmidt'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-23.16:16:06.541>
actor = 'xtreak'
assignee = 'ghaering'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2014-01-31.19:57:36.445>
creator = 'Ronny.Pfannschmidt'
dependencies = []
files = ['45049']
hgrepos = []
issue_num = 20463
keywords = ['patch']
message_count = 3.0
messages = ['209825', '248823', '278437']
nosy_count = 5.0
nosy_names = ['ghaering', 'r.david.murray', 'Ronny.Pfannschmidt', 'palaviv', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue20463'
versions = ['Python 2.7']
```

</p></details>

### Linked PRs
* gh-108340
* gh-108563
* gh-108564
* gh-108565

**Comment by erlend-aasland** [comment]
My plan for `iterdump` is to align it with the implementation in the SQLite shell, but I haven't gotten around to it yet. I think @palaviv's patch is a step in the right direction, and I don't think we should block that patch, just because `iterdump` also has other problems.

**Comment by erlend-aasland** [comment]
Hm, bug or feature; this issue was originally labeled as a "bug". But, the source code clearly included the comment:

```python
# NOTE: Virtual table support not implemented
```

In this case, I believe the correct label should have been "feature", not "bug", so I'm inclined _not_ to backport it.

**Comment by erlend-aasland** [comment]
I'm going to close this as resolved. Virtual table support has been added to Python 3.13. If you disagree, please ping me, or re-open.

**Comment by RonnyPfannschmidt** [comment]
I consider it a bug as the output wasn't valid,it should error if it cant make it,

**Comment by erlend-aasland** [comment]
> I consider it a bug as the output wasn't valid,it should error if it cant make it,

Hm, yeah, that is a valid point that weighs heavier than the comment.

**Comment by erlend-aasland** [comment]
OTOH, this changes the behaviour, which is an argument not to backport it.

**Comment by RonnyPfannschmidt** [comment]
@erlend-aasland personally i prefer people see a error when they dump rather than when they later load that dump

this bug in the worst case makes a broken backup silently appear working - not failing early causes more damage

silent breakage/invalid datagen is imho worse than adding a error where else people have hidden broken data until they test again

**Comment by RonnyPfannschmidt** [comment]
ftr - imho its fine to have a backport that just finally raises a NotImplementedError rather than silently dumping broken data

**Comment by erlend-aasland** [comment]
> ftr - imho its fine to have a backport that just finally raises a NotImplementedError rather than silently dumping broken data

I'd rather backport the fix. Anyway, you've convinced me; I agree that this is more a bugfix than a new feature. I'll prepare backports through 3.11.

**Comment by erlend-aasland** [comment]
Thanks for you input, @RonnyPfannschmidt.

**Comment by erlend-aasland** [comment]
Backports are queued; marking this as resolved.
