### ISSUE TITLE
_findLib_crle and _get_soname broken on latest SunOS 5.11

### ISSUE THREAD

**Issue by 2ebefccc-6706-4477-9cbe-24fb3ab325b1** [python/cpython#64863]
BPO | [20664](https://bugs.python.org/issue20664)
--- | :---
Nosy | @amauryfa, @abalkin, @meadori, @vadmium
Files | <li>[opensolaris-ctypes-python-2.7.patch](https://bugs.python.org/file35362/opensolaris-ctypes-python-2.7.patch "Uploaded as text/plain at 2014-05-26.03:51:42 by jquast"): patch against 2.7</li><li>[opensolaris-ctypes-python-3.x.patch](https://bugs.python.org/file35363/opensolaris-ctypes-python-3.x.patch "Uploaded as text/plain at 2014-05-26.03:52:08 by jquast"): python 3.x</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-02-17.20:25:40.363>
labels = ['ctypes', 'type-bug', '3.7']
title = '_findLib_crle and _get_soname broken on latest SunOS 5.11'
updated_at = <Date 2017-01-28.23:00:08.308>
user = 'https://bugs.python.org/rygorde4'
```

bugs.python.org fields:
```python
activity = <Date 2017-01-28.23:00:08.308>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2014-02-17.20:25:40.363>
creator = 'rygorde4'
dependencies = []
files = ['35362', '35363']
hgrepos = []
issue_num = 20664
keywords = ['patch']
message_count = 3.0
messages = ['211438', '219123', '286421']
nosy_count = 6.0
nosy_names = ['amaury.forgeotdarc', 'belopolsky', 'meador.inge', 'martin.panter', 'jquast', 'rygorde4']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue20664'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
The code that the patch modifies has been rewritten inhttps://github.com/python/cpython/issues/66826. Closing this as out of date.
