### ISSUE TITLE
[doc] Clarify copyreg.pickle() documentation

### ISSUE THREAD

**Issue by f7385517-0a24-49a2-83fd-f4eca87773fa** [python/cpython#65022]
BPO | [20823](https://bugs.python.org/issue20823)
--- | :---
Nosy | @serhiy-storchaka, @miss-islington, @kumaraditya303
PRs | <li>python/cpython#30230</li><li>python/cpython#30669</li><li>python/cpython#30670</li>
Files | <li>[copyreg.patch](https://bugs.python.org/file34263/copyreg.patch "Uploaded as text/plain at 2014-03-02.08:53:01 by peter.otten")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-03-02.08:46:06.048>
labels = ['easy', 'type-bug', '3.9', '3.10', '3.11', 'docs']
title = '[doc] Clarify copyreg.pickle() documentation'
updated_at = <Date 2022-01-18.20:17:10.000>
user = 'https://bugs.python.org/peterotten'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.20:17:10.000>
actor = 'miss-islington'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2014-03-02.08:46:06.048>
creator = 'peter.otten'
dependencies = []
files = ['34263']
hgrepos = []
issue_num = 20823
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['212541', '288092', '296271', '410883', '410884', '410885']
nosy_count = 5.0
nosy_names = ['peter.otten', 'docs@python', 'serhiy.storchaka', 'miss-islington', 'kumaraditya']
pr_nums = ['30230', '30669', '30670']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue20823'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-102656
* gh-103892
* gh-104098

**Comment by serhiy-storchaka** [comment]
The phrase "\*function* should return either a string or a tuple containing two or three elements." de-facto is outdated too. Since Python 2.3 a tuple returned by the function must have two to five elements.

copyreg.constructor() no longer does anything useful, and the constructor parameter of copyreg.pickle() is virtually ignored.

**Comment by serhiy-storchaka** [comment]
Could you update your patch Peter, and since CPython development is moved to GitHub, create a pull request?

**Comment by slateny** [comment]
The PR updated the wording on `TypeError` for `constructor`, but it looks like the wording on the 2/3 elements still needs an update.

**Comment by furkanonder** [comment]
@slateny What exactly do you mean by `wording on the 2/3 elements`?

**Comment by slateny** [comment]
I was referring to [Serhiy's comment above](https://github.com/python/cpython/issues/65022#issuecomment-1093647991) regarding the wording of `copyreg.pickle`.

**Comment by furkanonder** [comment]
@serhiy-storchaka   I [updated](https://github.com/python/cpython/pull/102656) the  copyreg.pickle function description as;
```
function must return either a string or a tuple containing two or five elements. 
```

**Comment by nanjekyejoannah** [comment]
@serhiy-storchaka  can decide when to close this, @furkanonder  the doc update is merged.
