### ISSUE TITLE
Undefined behavior flagged by Clang 3.4 (Python 3.5 from hg)

### ISSUE THREAD

**Issue by 873bc774-1538-46b2-932f-97fc1aaed8c5** [python/cpython#65131]
BPO | [20932](https://bugs.python.org/issue20932)
--- | :---
Nosy | @benjaminp, @vadmium, @serhiy-storchaka
Files | <li>[python-3.5-make.txt](https://bugs.python.org/file34428/python-3.5-make.txt "Uploaded as text/plain at 2014-03-15.02:37:24 by Jeffrey.Walton"): Results of 'make' with Clang's undefined behavior sanitizer.</li><li>[python-3.5-make-test.txt](https://bugs.python.org/file34429/python-3.5-make-test.txt "Uploaded as text/plain at 2014-03-15.02:38:54 by Jeffrey.Walton"): Results of 'make test' with Clang's undefined behavior sanitizer.</li><li>[audioop_signed_left_shift.patch](https://bugs.python.org/file34493/audioop_signed_left_shift.patch "Uploaded as text/plain at 2014-03-18.18:54:24 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-03-15.02:37:32.855>
labels = ['build']
title = 'Undefined behavior flagged by Clang 3.4 (Python 3.5 from hg)'
updated_at = <Date 2016-07-20.13:27:29.450>
user = 'https://bugs.python.org/JeffreyWalton'
```

bugs.python.org fields:
```python
activity = <Date 2016-07-20.13:27:29.450>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2014-03-15.02:37:32.855>
creator = 'Jeffrey.Walton'
dependencies = []
files = ['34428', '34429', '34493']
hgrepos = []
issue_num = 20932
keywords = ['patch']
message_count = 8.0
messages = ['213625', '213630', '213631', '213632', '213634', '214004', '214006', '270870']
nosy_count = 4.0
nosy_names = ['benjamin.peterson', 'martin.panter', 'serhiy.storchaka', 'Jeffrey.Walton']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue20932'
versions = ['Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as it is out of date.
