### ISSUE TITLE
Enhance obmalloc allocation strategy

### ISSUE THREAD

**Issue by 84401114-8e59-4056-83cb-632106c0b648** [python/cpython#65419]
BPO | [21220](https://bugs.python.org/issue21220)
--- | :---
Nosy | @tim-one, @pitrou, @kristjanvalur, @vstinner, @larryhastings
Files | <li>[obmalloc.patch](https://bugs.python.org/file34836/obmalloc.patch "Uploaded as text/plain at 2014-04-14.18:23:01 by @kristjanvalur")</li><li>[obmalloc.patch](https://bugs.python.org/file34876/obmalloc.patch "Uploaded as text/plain at 2014-04-15.15:45:59 by @kristjanvalur")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-04-14.18:23:06.032>
labels = ['interpreter-core', 'performance']
title = 'Enhance obmalloc allocation strategy'
updated_at = <Date 2014-04-28.09:42:20.550>
user = 'https://github.com/kristjanvalur'
```

bugs.python.org fields:
```python
activity = <Date 2014-04-28.09:42:20.550>
actor = 'kristjan.jonsson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2014-04-14.18:23:06.032>
creator = 'kristjan.jonsson'
dependencies = []
files = ['34836', '34876']
hgrepos = []
issue_num = 21220
keywords = ['patch']
message_count = 12.0
messages = ['216156', '216316', '216338', '216440', '216441', '216443', '216529', '216530', '216533', '216544', '217230', '217353']
nosy_count = 6.0
nosy_names = ['tim.peters', 'pitrou', 'kristjan.jonsson', 'vstinner', 'larry', 'neologix']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue21220'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
This experiment seems to have been abandoned 8 years ago. Shall we close the issue or is anyone still interested in continuing?

**Comment by vstinner** [comment]
@nascheme @tim-one @serhiy-storchaka @methane: Would you like to continue this pymalloc optimization experiment? Or should we just abandon it?

**Comment by nascheme** [comment]
I vote to close.  A new issue can be created or it can be re-opened if someone really wants to pursue it.

**Comment by methane** [comment]
Me too
