### ISSUE TITLE
Better support for AF_PACKET on opensolaris (illumos)

### ISSUE THREAD

**Issue by 5eda0096-0008-48f6-9ea3-295e7c876921** [python/cpython#65486]
BPO | [21287](https://bugs.python.org/issue21287)
--- | :---
Nosy | @jcea
Files | <li>[dyson-socketmodule-ifindex.patch](https://bugs.python.org/file34961/dyson-socketmodule-ifindex.patch "Uploaded as text/plain at 2014-04-18.04:27:29 by igor.pashev"): Update: check for sys/sockio.h</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-04-17.18:39:07.878>
labels = ['build', 'library']
title = 'Better support for AF_PACKET on opensolaris (illumos)'
updated_at = <Date 2014-04-19.10:06:26.438>
user = 'https://bugs.python.org/igorpashev'
```

bugs.python.org fields:
```python
activity = <Date 2014-04-19.10:06:26.438>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-04-17.18:39:07.878>
creator = 'igor.pashev'
dependencies = []
files = ['34961']
hgrepos = []
issue_num = 21287
keywords = ['patch']
message_count = 2.0
messages = ['216727', '216845']
nosy_count = 3.0
nosy_names = ['jcea', 'neologix', 'igor.pashev']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue21287'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.4 is not supported. Create a new issue targeting main branch if required.
