### ISSUE TITLE
NNTPLib connections become corrupt after long periods of activity

### ISSUE THREAD

**Issue by 56379c18-a76c-440d-adea-be88477daa40** [python/cpython#65667]
BPO | [21468](https://bugs.python.org/issue21468)
--- | :---
Nosy | @pitrou, @jwilk, @bitdancer, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-05-10.16:23:18.176>
labels = ['library']
title = 'NNTPLib connections become corrupt after long periods of activity'
updated_at = <Date 2014-09-07.03:47:32.980>
user = 'https://bugs.python.org/JamesMeneghello'
```

bugs.python.org fields:
```python
activity = <Date 2014-09-07.03:47:32.980>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-05-10.16:23:18.176>
creator = 'James.Meneghello'
dependencies = []
files = []
hgrepos = []
issue_num = 21468
keywords = []
message_count = 4.0
messages = ['218223', '219193', '219211', '226527']
nosy_count = 5.0
nosy_names = ['pitrou', 'jwilk', 'r.david.murray', 'martin.panter', 'James.Meneghello']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue21468'
versions = ['Python 3.2', 'Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by hugovk** [comment]
Let's close this old issue because the nntplib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
> Let's close this old issue because the nntplib module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

Cc. @jwilk, @bitdancer, @vadmium
