### ISSUE TITLE
[Windows] installations should include pythonX.exe and pythonX.Y.exe executables

### ISSUE THREAD

**Issue by 8421ad57-537e-4f22-8e81-3d310b1b1b0f** [python/cpython#65705]
BPO | [21506](https://bugs.python.org/issue21506)
--- | :---
Nosy | @loewis, @pfmoore, @tjguk, @zware, @eryksun, @zooba, @edmorley

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-05-14.11:36:10.643>
labels = ['type-feature', 'expert-installation', '3.10', 'OS-windows']
title = '[Windows] installations should include pythonX.exe and pythonX.Y.exe executables'
updated_at = <Date 2021-03-18.22:07:25.470>
user = 'https://github.com/edmorley'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-18.22:07:25.470>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2014-05-14.11:36:10.643>
creator = 'edmorley'
dependencies = []
files = []
hgrepos = []
issue_num = 21506
keywords = []
message_count = 14.0
messages = ['218521', '218522', '218535', '218537', '218549', '218553', '218554', '218556', '218565', '218572', '251552', '251559', '251820', '389043']
nosy_count = 8.0
nosy_names = ['loewis', 'paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'edmorley', 'ahiijny']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21506'
versions = ['Python 3.10']
```

</p></details>

**Comment by chrisoldwood** [comment]
> The file is so small that a second copy is just as cheap - literally everything is in the DLL. It could certainly be added to 3.6, and I'll probably get to it eventually, but right now I'm still focused on 3.5.

Can I confirm that this is still a valid workaround today with `3.11`? i.e. I'm assuming there are no _obvious_ shortcomings [1] from taking this approach after installing the standard package. (There were so many potential ways to workaround this - copy binary, symbolic link, `.bat` file wrapper, Chocolately's `shimgen`, etc. that I wanted to pick one that actual Python people would choose as they would know best 🙂.)

---

[1] Aside from any permissions required, e.g. creating symbolic links, or other programs assuming it's a binary called `python3.exe` which would preclude a `python3.{bat,cmd}` wrapper script.

**Comment by zooba** [comment]
> Can I confirm that this is still a valid workaround today with `3.11`?

Yep. As I've mentioned elsewhere, nothing much has changed here.

In a virtual environment, you'll need to copy the `venv/Scripts/python.exe` and not the original install. You can also rename `py.exe` to `python3.exe` and it will behave like `py.exe -V:PythonCore/3 ...` (or `py.exe -3 ...`), which may be more to your liking, depending on your setup.

**Comment by zooba** [comment]
#99185 is a newer version of this bug, so I'd rather close this and keep that one open.
