### ISSUE TITLE
Tkinter + OSX + Spaces : Multiple file dialogues created

### ISSUE THREAD

**Issue by f5043314-a2aa-4387-9c3c-24643859f90b** [python/cpython#65720]
BPO | [21521](https://bugs.python.org/issue21521)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-05-18.08:55:40.078>
labels = ['OS-mac', 'type-bug', 'expert-tkinter']
title = 'Tkinter + OSX + Spaces : Multiple file dialogues created'
updated_at = <Date 2020-12-15.16:40:28.011>
user = 'https://bugs.python.org/rovf'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-15.16:40:28.011>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Tkinter']
creation = <Date 2014-05-18.08:55:40.078>
creator = 'rovf'
dependencies = []
files = []
hgrepos = []
issue_num = 21521
keywords = []
message_count = 2.0
messages = ['218736', '383076']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'serhiy.storchaka', 'rovf']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = None
status = 'pending'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue21521'
versions = ['Python 3.4']
```

</p></details>

**Comment by resnbl** [comment]
FWIW: just tried OP's script, but without the Spaces switch, and `initialdir=` works fine for me.
Mac OS 12.3.1
Python 3.10.1
Tk 8.6.12

**Comment by ronaldoussoren** [comment]
@resnbl : thanks for the update

I'm closing this issue because this is not a problem with recent versions of the Python installer.  The original issue is likely a problem with the version of Tk used at the time. Since then we've moved to a much newer version of Tk that contains a lot of bug fixes and other enhancements.
