### ISSUE TITLE
try to use hashtable in pickle

### ISSUE THREAD

**Issue by 79528080-9d85-4d18-8a2a-8b1f07640dd7** [python/cpython#65755]
BPO | [21556](https://bugs.python.org/issue21556)
--- | :---
Nosy | @tim-one, @pitrou, @vstinner, @avassalotti, @serhiy-storchaka
Files | <li>[pickle_use_hashtable.diff](https://bugs.python.org/file35319/pickle_use_hashtable.diff "Uploaded as text/plain at 2014-05-22.20:55:04 by neologix")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-05-22.20:55:07.161>
labels = ['type-feature']
title = 'try to use hashtable in pickle'
updated_at = <Date 2014-05-23.09:26:44.682>
user = 'https://bugs.python.org/neologix'
```

bugs.python.org fields:
```python
activity = <Date 2014-05-23.09:26:44.682>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2014-05-22.20:55:07.161>
creator = 'neologix'
dependencies = []
files = ['35319']
hgrepos = []
issue_num = 21556
keywords = ['patch']
message_count = 7.0
messages = ['218920', '218948', '218949', '218950', '218951', '218952', '218953']
nosy_count = 6.0
nosy_names = ['tim.peters', 'pitrou', 'vstinner', 'alexandre.vassalotti', 'neologix', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21556'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
Interesting discussion, but I think the conclusion is that there is no hope for this patch. Marking as pending with a view to closing this soon, unless someone objects.
