### ISSUE TITLE
Clean up turtle.py code formatting

### ISSUE THREAD

**Issue by jesstess** [python/cpython#65772]
BPO | [21573](https://bugs.python.org/issue21573)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ezio-melotti, @bitdancer, @AnishShah

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-05-25.01:48:23.909>
labels = ['type-feature']
title = 'Clean up turtle.py code formatting'
updated_at = <Date 2016-02-06.09:04:38.015>
user = 'https://bugs.python.org/jesstess'
```

bugs.python.org fields:
```python
activity = <Date 2016-02-06.09:04:38.015>
actor = 'anish.shah'
assignee = 'jesstess'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2014-05-25.01:48:23.909>
creator = 'jesstess'
dependencies = []
files = []
hgrepos = []
issue_num = 21573
keywords = ['gsoc']
message_count = 12.0
messages = ['219068', '219072', '219410', '219427', '219438', '219462', '219476', '219524', '219536', '219537', '219610', '223765']
nosy_count = 9.0
nosy_names = ['rhettinger', 'terry.reedy', 'gregorlingl', 'ezio.melotti', 'r.david.murray', 'jesstess', 'ingrid', 'Lita.Cho', 'anish.shah']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21573'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-104218

**Comment by arhadthedev** [comment]
Current status:

> Run turtle.py through a [PEP-8](https://peps.python.org/8) checker and fix the issues that are reasonable to fix.

> Run turtle.py through a linter like pyflakes and fix reasonable linter issues.

In fact, we should do this for the whole library, no special treatment is required for `Lib/turtle.py` here.

> Examine commented out code, and either remove it or open a ticket if it represents an issue that should be fixed.

Only three occurrences are left:

https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/turtle.py#L105 https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/turtle.py#L143-L144 https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/turtle.py#L601-L602

> Examine # XXX comments, and either remove them if they are no longer applicable, or open tickets for them if they still represent bugs and then remove them.

Only two occurrences are left:

https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/turtle.py#L3754-L3755 https://github.com/python/cpython/blob/e5b8b19d99861c73ab76ee0175a685acf6082d7e/Lib/turtle.py#L3756-L3758

However, **should we address these cosmetic issues**?

**Comment by terryjreedy** [comment]
Reformatting correct, comprehensible, and needed code is against PEP 8 unless part of a bigger review and refactoring.  Code is needed if is removal, as opposed to replacement, breaks some intended function.  Removing unneeded code, whether discovered by a linter or otherwise, is routine as it inhibits performance or comprehension.  So such removals are not purely cosmetic.

I think all 3 commented-out chunks should be removed.  I will prepare a PR with explanations.  I will consider the XXX comments as I do so.

**Comment by terryjreedy** [comment]
Except for these 5 items, I want to close this as I consider anything else as either done, obsolete, or something for another issue.
