### ISSUE TITLE
Allow copying of CodecInfo objects

### ISSUE THREAD

**Issue by bd0a318e-1f52-42d4-a694-e00a65313ddc** [python/cpython#66143]
BPO | [21944](https://bugs.python.org/issue21944)
--- | :---
Nosy | @malemburg, @berkerpeksag
Files | <li>[copy_codecinfo.patch](https://bugs.python.org/file35912/copy_codecinfo.patch "Uploaded as text/plain at 2014-07-09.11:52:07 by lehmannro"): patch to current default</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-07-09.11:52:09.214>
labels = ['type-feature', 'library', '3.11']
title = 'Allow copying of CodecInfo objects'
updated_at = <Date 2021-11-26.22:44:37.352>
user = 'https://bugs.python.org/lehmannro'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-26.22:44:37.352>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-07-09.11:52:09.214>
creator = 'lehmannro'
dependencies = []
files = ['35912']
hgrepos = []
issue_num = 21944
keywords = ['patch']
message_count = 2.0
messages = ['222609', '236755']
nosy_count = 3.0
nosy_names = ['lemburg', 'lehmannro', 'berker.peksag']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue21944'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-100432
* gh-109235

**Comment by furkanonder** [comment]
@lehmannro Are you gonna continue this task?

**Comment by furkanonder** [comment]
The [PR](https://github.com/python/cpython/pull/100432) is ready for review.

@serhiy-storchaka Can you review it?

**Comment by serhiy-storchaka** [comment]
Thanks @lehmannro for the initial patch and @furkanonder for bringing the issue to a successful end.
