### ISSUE TITLE
Implement atomic operations on non-x86 platforms

### ISSUE THREAD

**Issue by a1dfbe9e-43a5-49dc-9a3f-a56b2022fe03** [python/cpython#66237]
BPO | [22038](https://bugs.python.org/issue22038)
--- | :---
Nosy | @vstinner, @koobs
Files | <li>[atomic.patch](https://bugs.python.org/file36035/atomic.patch "Uploaded as text/plain at 2014-07-22.17:24:12 by Vitor.de.Lima"): A patch implemeting atomic operating using the GCC builtins</li><li>[atomicv2.patch](https://bugs.python.org/file36151/atomicv2.patch "Uploaded as text/plain at 2014-07-29.16:46:07 by Vitor.de.Lima"): A patch implemeting atomic operating using the GCC builtins and the stdatomic.h header</li><li>[atomicv3.patch](https://bugs.python.org/file37500/atomicv3.patch "Uploaded as text/plain at 2014-12-18.20:14:03 by gustavotemple")</li><li>[atomicv4.patch](https://bugs.python.org/file37694/atomicv4.patch "Uploaded as text/plain at 2015-01-13.18:51:09 by gustavotemple")</li><li>[atomicv5.patch](https://bugs.python.org/file37704/atomicv5.patch "Uploaded as text/plain at 2015-01-14.11:27:00 by gustavotemple")</li><li>[atomic_pointer.patch](https://bugs.python.org/file37706/atomic_pointer.patch "Uploaded as text/plain at 2015-01-14.15:06:20 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-07-22.17:24:12.307>
labels = ['interpreter-core', 'type-feature']
title = 'Implement atomic operations on non-x86 platforms'
updated_at = <Date 2015-03-17.21:59:03.297>
user = 'https://bugs.python.org/VitordeLima'
```

bugs.python.org fields:
```python
activity = <Date 2015-03-17.21:59:03.297>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2014-07-22.17:24:12.307>
creator = 'Vitor.de.Lima'
dependencies = []
files = ['36035', '36151', '37500', '37694', '37704', '37706']
hgrepos = []
issue_num = 22038
keywords = ['patch']
message_count = 25.0
messages = ['223676', '223740', '224235', '232813', '232836', '232839', '232901', '233706', '233707', '233745', '233942', '233944', '233955', '233958', '233959', '233960', '233991', '233993', '234023', '234029', '234030', '234031', '234037', '237945', '238348']
nosy_count = 9.0
nosy_names = ['vstinner', 'Arfrever', 'neologix', 'python-dev', 'koobs', 'John.Malmberg', 'Vitor.de.Lima', 'gustavotemple', 'lbianc']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue22038'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by gpshead** [comment]
anything left to do on this issue?

**Comment by vstinner** [comment]
> anything left to do on this issue?

I didn't hear any complain about Include/internal/pycore_atomic.h recently. Previously, it was indirectly included by ``#include <Python.h>``. But I moved the header file to the internal C API which fixed C++ issues and other compiler issues. I close the issue.
