### ISSUE TITLE
asyncio: support multiprocessing (support fork)

### ISSUE THREAD

**Issue by c824905b-7819-4e30-8e6a-16f463dc2e26** [python/cpython#66285]
BPO | [22087](https://bugs.python.org/issue22087)
--- | :---
Nosy | @gvanrossum, @pitrou, @1st1, @thehesiod, @miss-islington
PRs | <li>python/cpython#7208</li><li>python/cpython#7215</li><li>python/cpython#7218</li><li>python/cpython#7226</li><li>python/cpython#7232</li><li>python/cpython#7233</li>
Files | <li>[test_loop.py](https://bugs.python.org/file36117/test_loop.py "Uploaded as text/plain at 2014-07-26.18:01:38 by dan.oreilly"): Test script demonstrating the issue</li><li>[handle_mp_unix.diff](https://bugs.python.org/file36118/handle_mp_unix.diff "Uploaded as text/plain at 2014-07-26.18:20:15 by dan.oreilly"): Patch that makes _UnixDefaultEventLoopPolicy create a new loop object if get_event_loop is called in a forked mp child process</li><li>[handle-mp_unix2.patch](https://bugs.python.org/file36119/handle-mp_unix2.patch "Uploaded as text/plain at 2014-07-26.20:13:57 by dan.oreilly"): Use os.getpid() instead of multiprocessing. Store pid state in Policy instance rather than the Loop instance.</li><li>[handle_mp_unix_with_test.diff](https://bugs.python.org/file36134/handle_mp_unix_with_test.diff "Uploaded as text/plain at 2014-07-27.16:09:52 by dan.oreilly"): Adds a unit test to previous patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-07-26.18:01:10.150>
labels = ['type-bug', 'expert-asyncio']
title = 'asyncio: support multiprocessing (support fork)'
updated_at = <Date 2018-05-30.00:56:36.541>
user = 'https://bugs.python.org/danoreilly'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-30.00:56:36.541>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2014-07-26.18:01:10.150>
creator = 'dan.oreilly'
dependencies = []
files = ['36117', '36118', '36119', '36134']
hgrepos = []
issue_num = 22087
keywords = ['patch']
message_count = 23.0
messages = ['224082', '224084', '224085', '224097', '224125', '224140', '224143', '224144', '224145', '226698', '235404', '235411', '288327', '297222', '297226', '297227', '297229', '318077', '318092', '318135', '318140', '318143', '318144']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'pitrou', 'zmedico', 'yselivanov', 'thehesiod', 'dan.oreilly', 'miss-islington']
pr_nums = ['7208', '7215', '7218', '7226', '7232', '7233']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue22087'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

### Linked PRs
* gh-99539
* gh-99745
* gh-99756
* gh-99769

**Comment by a504a022-18ff-484f-abb3-b4c5557c05a0** [comment]
I believe this is now worse due to https://github.com/python/asyncio/pull/452

before I was able to simply create a new run loop from sub-processes however you will now get the error "Cannot run the event loop while another loop is running".  The state of the run loop should not be preserved in sub-processes either.

**Comment by pitrou** [comment]
The approach in Dan's patches looks sane to me and I agree the issue needs fixing.  Dan, would you like to submit a PR for this?  We're using Github for patch submissions now.

**Comment by 1st1** [comment]
> The approach in Dan's patches looks sane to me and I agree the issue needs fixing.  Dan, would you like to submit a PR for this?  We're using Github for patch submissions now.


Mind that the patch is very outdated and we already have these checks in get_event_loop.

**Comment by pitrou** [comment]
It seems there's a check in the top-level get_event_loop() function but not in the DefaultEventLoopPolicy.get_event_loop() method.

(also: wow, that stuff is complicated)

**Comment by 1st1** [comment]
> It seems there's a check in the top-level get_event_loop() function but not in the DefaultEventLoopPolicy.get_event_loop() method.

Yes, as users aren't supposed to work with policies directly.

> (also: wow, that stuff is complicated)

Yep. Please assign me to review if you submit a PR.

**Comment by gvanrossum** [comment]
This must be one of the longest-open asyncio bugs -- it dates from 2014! It was almost fixed in 2018 but the fix was rolled back because @1st1 wanted to do it "properly". Alas, that seemed too ambitious a plan, and it was never heard from again (unless a fix was committed without reference to this issue).

**Comment by kumaraditya303** [comment]
I'll fix this in 3.12 but this won't be backported to older branches. I'll write up the details for implementation here, but I'll keep things simple. For now I am thinking of when the event loop is created, to register a [fork handler](https://docs.python.org/3/library/os.html#os.register_at_fork) to close the wakeup fd, any sockets e.g self-pipe and not share the event loop.

**Comment by kumaraditya303** [comment]
See https://github.com/python/cpython/issues/66285

The PR does two things with a fork handler:
- Reset the event loop registry so that child and parent process do not share the same event loop.
- Reset the `wakeupfd` in child so that when a signal is sent to child, the signal handler of the parent is not called.

I have added two tests, first tests that event loop is not shared across forked processes and the second tests that the wakeup fd is reset.

**Comment by gvanrossum** [comment]
Is the intention of this PR that after the fork() call the child can use all asyncio functionality and everything should work?

Maybe we should discuss what exactly we guarantee after this PR (and perhaps what guarantees already hold -- I presume if the forked child creates a brand new loop everything did work already except for signals?)

**Comment by gvanrossum** [comment]
In particular the PR's title seems to claim that _everything_ related to forking and asyncio will be fixed. How much do you yourself believe that claim?

**Comment by kumaraditya303** [comment]
> In particular the PR's title seems to claim that everything related to forking and asyncio will be fixed. How much do you yourself believe that claim?

Everything should work in forked process as it normally does without fork, I have added test for this in the latest commit.

**Comment by gvanrossum** [comment]
Let's keep this open until the buildbot results come in. Lukasz is bisecting them as we speak.

**Comment by Sagor0078** [comment]
asyncio's event loop is typically initialized in the main process and is not designed to be inherited by child processes created via multiprocessing. am i right?
