### ISSUE TITLE
wsgiref doesn't appear to ever set REMOTE_HOST in the environ

### ISSUE THREAD

**Issue by alex** [python/cpython#66425]
BPO | [22229](https://bugs.python.org/issue22229)
--- | :---
Nosy | @pjeby, @alex, @berkerpeksag, @isidentical

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-08-19.17:34:05.563>
labels = ['type-bug', 'library']
title = "wsgiref doesn't appear to ever set REMOTE_HOST in the environ"
updated_at = <Date 2019-11-18.22:03:20.358>
user = 'https://github.com/alex'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-18.22:03:20.358>
actor = 'BTaskaya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-08-19.17:34:05.563>
creator = 'alex'
dependencies = []
files = []
hgrepos = []
issue_num = 22229
keywords = []
message_count = 2.0
messages = ['225534', '356918']
nosy_count = 4.0
nosy_names = ['pje', 'alex', 'berker.peksag', 'BTaskaya']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue22229'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

### Linked PRs
* gh-111441

**Comment by corona10** [comment]
Merge the PR, Even if someone overrides WSGIRequestHandler there is the documentation that the user should care about: https://docs.python.org/3/library/wsgiref.html?highlight=wsgirequesthandler#wsgiref.simple_server.WSGIRequestHandler
