### ISSUE TITLE
argparse support for "python -m module" in help

### ISSUE THREAD

**Issue by daf46b87-a9e9-4381-bf23-8c373c9135e6** [python/cpython#66436]
BPO | [22240](https://bugs.python.org/issue22240)
--- | :---
Nosy | @tebeka, @ncoghlan, @jwilk, @zertrin, @SamuelMarks, @Septatrix
Files | <li>[prog.diff](https://bugs.python.org/file36424/prog.diff "Uploaded as text/plain at 2014-08-20.19:59:10 by @tebeka"): Patch</li><li>[prog2.diff](https://bugs.python.org/file36453/prog2.diff "Uploaded as text/plain at 2014-08-24.17:42:58 by @tebeka"): Patch</li><li>[prog3.diff](https://bugs.python.org/file36461/prog3.diff "Uploaded as text/plain at 2014-08-25.03:45:18 by @tebeka"): Patch</li><li>[prog3.diff](https://bugs.python.org/file36476/prog3.diff "Uploaded as text/plain at 2014-08-26.11:18:32 by @tebeka"): Patch</li><li>[prog-module-name-handler.patch](https://bugs.python.org/file48643/prog-module-name-handler.patch "Uploaded as text/plain at 2019-10-05.04:05:03 by @SamuelMarks"): Patch for handling `python -m` syntax in argument parser ouptut</li><li>[patch.diff](https://bugs.python.org/file50174/patch.diff "Uploaded as text/plain at 2021-07-23.16:08:11 by @Septatrix")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-08-20.19:59:11.381>
labels = ['type-feature', 'library']
title = 'argparse support for "python -m module" in help'
updated_at = <Date 2021-08-08.22:41:00.591>
user = 'https://github.com/tebeka'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-08.22:41:00.591>
actor = 'Nils Kattenbeck'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-08-20.19:59:11.381>
creator = 'tebeka'
dependencies = []
files = ['36424', '36453', '36461', '36476', '48643', '50174']
hgrepos = []
issue_num = 22240
keywords = ['patch']
message_count = 23.0
messages = ['225586', '225608', '225669', '225831', '225834', '225838', '225862', '225863', '225865', '225911', '225913', '226578', '226606', '226622', '226697', '226706', '226707', '353987', '353989', '397764', '398076', '398698', '399244']
nosy_count = 9.0
nosy_names = ['tebeka', 'ncoghlan', 'peter.otten', 'bethard', 'jwilk', 'paul.j3', 'zertrin', 'samuelmarks', 'Nils Kattenbeck']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue22240'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-124799

**Comment by serhiy-storchaka** [comment]
#124799 mostly implements @ncoghlan's algorithm from https://github.com/python/cpython/issues/66436#issuecomment-1093662866 and adds tests and documentation.

@ncoghlan, I would appreciate your review of the documentation, as it is difficult to me. Feel free to rewrite it completely.

**Comment by serhiy-storchaka** [comment]
It looks to me that testing `__main__.__spec__.name` for `'__main__'` is enough. Additional checks are redundant, and checking that `sys.argv[0]` is equal to `__main__.__spec__.origin` with the trailing `__main__.py` removed is hard due to difference in normalization on Unix and Windows.
