### ISSUE TITLE
mailbox.MH chokes on directories without .mh_sequences

### ISSUE THREAD

**Issue by a174b59b-fd77-4640-8b72-26c02feb729d** [python/cpython#66515]
BPO | [22319](https://bugs.python.org/issue22319)
--- | :---
Nosy | @warsaw, @bitdancer, @serhiy-storchaka
PRs | <li>python/cpython#804</li>
Files | <li>[mailbox_mh_sequences.diff](https://bugs.python.org/file36515/mailbox_mh_sequences.diff "Uploaded as text/plain at 2014-09-01.00:52:19 by gumnos"): A patch that wraps the open() call in a try/except/else block</li><li>[mailbox_mh_sequences_lbyl.diff](https://bugs.python.org/file36516/mailbox_mh_sequences_lbyl.diff "Uploaded as text/plain at 2014-09-01.00:57:21 by gumnos"): A look-before-you-leap version of the patch that is much simpler, but has a minor race-condition compared to the other one.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-09-01.00:44:46.030>
labels = ['3.7', 'type-feature', 'library', 'expert-email']
title = 'mailbox.MH chokes on directories without .mh_sequences'
updated_at = <Date 2017-04-16.16:58:40.225>
user = 'https://bugs.python.org/gumnos'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-16.16:58:40.225>
actor = 'r.david.murray'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'email']
creation = <Date 2014-09-01.00:44:46.030>
creator = 'gumnos'
dependencies = []
files = ['36515', '36516']
hgrepos = []
issue_num = 22319
keywords = ['patch']
message_count = 8.0
messages = ['226197', '226228', '290093', '291738', '291749', '291754', '291757', '291759']
nosy_count = 4.0
nosy_names = ['barry', 'gumnos', 'r.david.murray', 'serhiy.storchaka']
pr_nums = ['804']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue22319'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-113482

**Comment by serhiy-storchaka** [comment]
I consider this issue as a new feature.

[PR 804](https://github.com/python/cpython/pull/804) makes get_sequences() and set_sequences() working when the ".mh_sequences" file does not exist.

The open question is what to do with lock(). Currently it fails if the ".mh_sequences" file does not exist. Is it correct to create the ".mh_sequences" file in lock() or this invalidates the lock?

Is it safe to change the file open mode in set_sequences() from "r+" to "w" (the file is truncated later)?

**Comment by serhiy-storchaka** [comment]
Ping.

**Comment by bitdancer** [comment]
Honestly, given the open questions my inclination would be to reject this.

**Comment by serhiy-storchaka** [comment]
Do you mean rejecting the support of Claws Mail IMAP-cache folder or just the patch?

**Comment by bitdancer** [comment]
The support.  ClawsMail is broken, IMO.

**Comment by bitdancer** [comment]
If there is a way to resolve the lock issue we can consider it.  But (without looking at the code again) I suspect the locking is too deeply embedded in the mbox logic for this to be a safe change.

**Comment by serhiy-storchaka** [comment]
I am sorry, I rushed to merge #804 without noticing that there are still open questions. I hope that the subsequent PR #113482 addresses them.
