### ISSUE TITLE
mimetypes.guess_type("//example.com") misinterprets host name as file name

### ISSUE THREAD

**Issue by vadmium** [python/cpython#66543]
BPO | [22347](https://bugs.python.org/issue22347)
--- | :---
Nosy | @ned-deily, @vadmium, @maxking, @corona10, @miss-islington
PRs | <li>python/cpython#15522</li><li>python/cpython#15685</li><li>python/cpython#15687</li><li>python/cpython#16724</li><li>python/cpython#16725</li><li>python/cpython#16727</li><li>python/cpython#16728</li>
Dependencies | <li>bpo-35939: Remove urllib.parse._splittype from mimetypes.guess_type</li>
Files | <li>[mimetypes-host.patch](https://bugs.python.org/file38222/mimetypes-host.patch "Uploaded as text/plain at 2015-02-24.05:53:54 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-09-06.02:52:37.225>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'mimetypes.guess_type("//example.com") misinterprets host name as file name'
updated_at = <Date 2019-10-15.07:30:25.613>
user = 'https://github.com/vadmium'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-15.07:30:25.613>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-09-06.02:52:37.225>
creator = 'martin.panter'
dependencies = ['35939']
files = ['38222']
hgrepos = []
issue_num = 22347
keywords = ['patch']
message_count = 15.0
messages = ['226467', '236479', '335123', '351156', '351157', '351158', '351162', '351164', '351167', '354471', '354521', '354535', '354538', '354543', '354697']
nosy_count = 5.0
nosy_names = ['ned.deily', 'martin.panter', 'maxking', 'corona10', 'miss-islington']
pr_nums = ['15522', '15685', '15687', '16724', '16725', '16727', '16728']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue22347'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-117217
* gh-117256
* gh-117257
* gh-117258

**Comment by serhiy-storchaka** [comment]
`guess_type()` is too ambiguous. Its input is either URL or a file path, but you cannot always distinguish one from other. URL should escape some characters if they are occurred in the path, and it not always ends with a path. It can can with a host name (as in the original report), a fragment, a query, all this can lead to wrong result.

I think that the only way to solve this issue is to split it on two functions -- for URLs and for file paths. Or add a boolean parameter, but it is less convenient.

I propose to add `guess_file_type()` which only works with file paths, and deprecate accepting file paths in `guess_type()`.

**Comment by vstinner** [comment]
> I propose to add guess_file_type() which only works with file paths, and deprecate accepting file paths in guess_type().

This is a good idea since support for file paths was added to Python 3.8, and before it only accepted an URL.

I expect such function to be able to return `"image/gif"` for a filename `"image.gif"`!

**Comment by serhiy-storchaka** [comment]
#117217 is based on the reverted PR #15522, but makes the URL parsing more reliable. The argument is interpreted as URL only if it has a scheme and does not look like a Windows path. Also fixed support of UNC paths on Windows (an issue similar to #115892).

**Comment by vadmium** [comment]
That might be a sensible compromise. So accept either a full URL or path, but not a relative URL. RFC 3986 allows single-letter URL schemes, but no such schemes are registered, so it might be okay to treat them as drive letters instead.

**Comment by serhiy-storchaka** [comment]
#117258 adds `guess_file_type()`. Passing file path in `guess_type()` is deprecated in documentation only. There are too many uses of `guess_type()` with a file path, so emitting a deprecation warning at runtime will be added many years later.

In addition, `guess_file_type()` works with bytes paths. `guess_type()` always returns `(None, None)` and may emit a bytes warning.

Yet one difference: file `foo\.html` is considered an HTML file on Posix, but has an unknown MIME type on Windows.
