### ISSUE TITLE
Tkinter doesn't handle Unicode dead key combinations on Windows

### ISSUE THREAD

**Issue by 90ff3b65-5c08-4f89-bb59-3f03c3cccbb5** [python/cpython#66598]
BPO | [22408](https://bugs.python.org/issue22408)
--- | :---
Nosy | @terryjreedy, @vstinner, @ned-deily, @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2014-09-24.08:34:13.850>
created_at = <Date 2014-09-14.15:44:55.729>
labels = ['expert-tkinter', 'expert-unicode', 'OS-windows']
title = "Tkinter doesn't handle Unicode dead key combinations on Windows"
updated_at = <Date 2015-04-27.12:52:03.591>
user = 'https://bugs.python.org/Drekin'
```

bugs.python.org fields:
```python
activity = <Date 2015-04-27.12:52:03.591>
actor = 'THRlWiTi'
assignee = 'none'
closed = True
closed_date = <Date 2014-09-24.08:34:13.850>
closer = 'ned.deily'
components = ['Tkinter', 'Unicode', 'Windows']
creation = <Date 2014-09-14.15:44:55.729>
creator = 'Drekin'
dependencies = []
files = []
hgrepos = []
issue_num = 22408
keywords = []
message_count = 9.0
messages = ['226872', '226893', '226906', '227380', '227385', '227388', '227392', '227415', '227422']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'vstinner', 'ned.deily', 'ezio.melotti', 'THRlWiTi', 'serhiy.storchaka', 'Drekin']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue22408'
versions = ['Python 3.4']
```

</p></details>

**Comment by terryjreedy** [comment]
On duplicate #115230, @rardyy wrote...
---
Note: If AltGr isn't on your keyboard, press Ctrl + Alt. It does the same thing.
https://github.com/python/cpython/issues/66598
Problem with AltGr (Ctrl + Alt)

On my custom keyboard (created with [MSKLC](https://www.microsoft.com/en-gb/download/details.aspx?id=102134)), ẞ (U+1E9E, LATIN CAPITAL LETTER SHARP S) is assigned AltGr +  Shift + S. When I try to type it using my custom keyboard, it gets replaced with ?.

>>> weiß = "#ffffff" # Lowercase "ẞ" (ß) works though.
>>> STRA?E = "BERLIN" # Supposed to be STRAẞE 

It works correctly in other software like Notepad++.
Problem with [dead keys](https://en.wikipedia.org/wiki/Dead_key)
What is a dead key?

A dead key modifies the next character typed.
Example: typing ` then e gives è (` is the dead key.) This sequence works in IDLE.
Some characters work as dead keys, but others don't.
Dead keys that work

Pressing ¨ (U+00A8, DIAERESIS), which is assigned AltGr + 2, then e, gives me ë.
Dead keys that don't work

When I press ´ (U+00B4, ACUTE ACCENT), which is assigned AltGr + ', then y, I should get ý. Instead I get y.
It also works correctly in other software like Notepad++.

**Comment by terryjreedy** [comment]
Tcl/tk event sequences are composed of 1 (most commonly) or more (somewhat rarely) event patterns, each of which has 1 or more fields.  [Official explanation](https://www.tcl.tk/man/tcl8.6/TkCmd/bind.html)  There are multiple event issues brought up in the various comments above.

1. Modifiers keys are possible fields that precede a non-modifier field.  They are listed in the MODIFIERS section of the linked page. 'AltGr' is not one of them.  IDLE/Tkinker/Python cannot change this.  It is possible that tcl/tk cannot either -- if OSes do not send it as a separate event.  'rardyy' says that 'AltGr' is equivalent to 'Ctrl+Alt'.  If so, one should just use the latter.

2. As mentioned above, tk recognizes multi-pattern sequences.  They typically use one pattern to modify the meaning of another pattern.  A typical use seems to be mapping AltGr patterns to a unicode modifier characters, such as accents. 

3. I know that at least some Windows IMEs work fine with tk, tkinter, and hence IDLE.  I know someone that types Japanese chars and text into IDLE.

4. Questions about using keyboard layouts and AltGr in particular should be directed elsewhere.  Searching SO for 'AltGR' returns  [485 posts](https://stackoverflow.com/search?q=AltGr&s=dae3aa27-5e06-4e36-b529-e4fa8e607c2c).  Only two are tagged 'tkinter'.
