### ISSUE TITLE
Module source files not found when cross-compiling

### ISSUE THREAD

**Issue by 5b0ee324-0775-4a9f-aa11-891a300c18ca** [python/cpython#66888]
BPO | [22699](https://bugs.python.org/issue22699)
--- | :---
Nosy | @doko42, @ned-deily, @xdegaye, @zooba, @moreati, @wscullin, @isuruf, @iliis
PRs | <li>python/cpython#28397</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-10-22.15:49:06.114>
labels = ['build', '3.8', '3.9']
title = 'Module source files not found when cross-compiling'
updated_at = <Date 2021-09-16.20:52:16.007>
user = 'https://bugs.python.org/bill9889'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-16.20:52:16.007>
actor = 'isuruf'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Cross-Build']
creation = <Date 2014-10-22.15:49:06.114>
creator = 'bill9889'
dependencies = []
files = []
hgrepos = []
issue_num = 22699
keywords = ['patch']
message_count = 16.0
messages = ['229828', '248441', '350532', '364574', '364575', '364577', '364635', '364658', '364662', '364683', '364685', '364686', '364687', '364693', '364706', '364715']
nosy_count = 9.0
nosy_names = ['doko', 'ned.deily', 'xdegaye', 'steve.dower', 'Alex.Willmer', 'bill9889', 'wscullin', 'isuruf', 'iliis']
pr_nums = ['28397']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue22699'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by CristiFati** [comment]
Lot of time later what if you `CFLAGS="-m32" LDFLAGS="-m32" configure ...` ?

**Comment by erlend-aasland** [comment]
Several years later, we've now tossed out `setup.py` from the repo, the build system has changed to adapt for cross-compiling scenarios like Android and iOS. I'm aligned to close this as outdated. Marking it as pending close. If someone disagrees, please shout.
