### ISSUE TITLE
httplib/http.client in method _tunnel used HTTP/1.0 CONNECT method

### ISSUE THREAD

**Issue by c71b2b87-f1e4-4c98-967d-ac18ff337b10** [python/cpython#66897]
BPO | [22708](https://bugs.python.org/issue22708)
--- | :---
Nosy | @orsenthil, @bitdancer, @berkerpeksag, @vadmium, @demianbrecht, @vo-va
PRs | <li>python/cpython#742</li><li>python/cpython#8305</li>
Files | <li>[py2.7.httplib.patch](https://bugs.python.org/file36996/py2.7.httplib.patch "Uploaded as text/plain at 2014-10-23.06:21:22 by @vo-va"): pach for python 2.7</li><li>[issue22708.patch](https://bugs.python.org/file38808/issue22708.patch "Uploaded as text/plain at 2015-04-02.15:14:56 by @demianbrecht")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = None
created_at = <Date 2014-10-23.06:21:23.450>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'httplib/http.client in method _tunnel used HTTP/1.0 CONNECT method'
updated_at = <Date 2021-11-07.18:37:03.856>
user = 'https://github.com/vo-va'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-07.18:37:03.856>
actor = 'eric.araujo'
assignee = 'orsenthil'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-10-23.06:21:23.450>
creator = 'vova'
dependencies = []
files = ['36996', '38808']
hgrepos = []
issue_num = 22708
keywords = ['patch']
message_count = 6.0
messages = ['229856', '229876', '229915', '239921', '239952', '241237']
nosy_count = 6.0
nosy_names = ['orsenthil', 'r.david.murray', 'berker.peksag', 'martin.panter', 'demian.brecht', 'vova']
pr_nums = ['742', '8305']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue22708'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by Qubits01** [comment]
Sad to see the patch is not implemented 8 years after the issue was opened.

**Comment by arhadthedev** [comment]
gh-8305 is merged so closing as done.
