### ISSUE TITLE
cgitb html: wrong encoding for utf-8

### ISSUE THREAD

**Issue by d943741b-dd32-4a1a-b522-8ba0d540c2df** [python/cpython#66935]
BPO | [22746](https://bugs.python.org/issue22746)
--- | :---
Nosy | @amauryfa, @vstinner, @ezio-melotti, @bitdancer, @serhiy-storchaka
Files | <li>[cgibug.py](https://bugs.python.org/file37044/cgibug.py "Uploaded as text/plain at 2014-10-27.18:48:57 by wrohdewald")</li><li>[22746.patch](https://bugs.python.org/file37047/22746.patch "Uploaded as text/plain at 2014-10-28.04:21:13 by wrohdewald")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-10-27.18:48:57.478>
labels = ['type-bug', 'library', 'expert-unicode']
title = 'cgitb html: wrong encoding for utf-8'
updated_at = <Date 2014-12-03.07:50:08.854>
user = 'https://bugs.python.org/wrohdewald'
```

bugs.python.org fields:
```python
activity = <Date 2014-12-03.07:50:08.854>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Unicode']
creation = <Date 2014-10-27.18:48:57.478>
creator = 'wrohdewald'
dependencies = []
files = ['37044', '37047']
hgrepos = []
issue_num = 22746
keywords = ['patch']
message_count = 11.0
messages = ['230085', '230099', '230117', '230131', '230133', '230134', '230148', '230149', '230159', '230361', '232073']
nosy_count = 6.0
nosy_names = ['amaury.forgeotdarc', 'vstinner', 'ezio.melotti', 'r.david.murray', 'wrohdewald', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue22746'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by hugovk** [comment]
I think we can close this? The cgitb module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/), https://github.com/python/cpython/issues/91217 and https://github.com/python/cpython/pull/32410.

**Comment by AlexWaygood** [comment]
> I think we can close this? The cgitb module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/), #91217 and #32410.

Cc. @amauryfa, @wrohdewald
