### ISSUE TITLE
document behavior of calling atexit.register() while atexit._run_exitfuncs is running

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#67056]
BPO | [22867](https://bugs.python.org/issue22867)
--- | :---
Nosy | @smontanaro, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-11-13.20:52:37.164>
labels = ['docs']
title = 'document behavior of calling atexit.register() while atexit._run_exitfuncs is running'
updated_at = <Date 2015-07-21.07:43:20.900>
user = 'https://github.com/smontanaro'
```

bugs.python.org fields:
```python
activity = <Date 2015-07-21.07:43:20.900>
actor = 'ethan.furman'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2014-11-13.20:52:37.164>
creator = 'skip.montanaro'
dependencies = []
files = []
hgrepos = []
issue_num = 22867
keywords = []
message_count = 2.0
messages = ['231135', '231354']
nosy_count = 3.0
nosy_names = ['skip.montanaro', 'docs@python', 'martin.panter']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue22867'
versions = []
```

</p></details>

### Linked PRs
* gh-104473

**Comment by iritkatriel** [comment]
The atexit functions are invoked in LIFO order, so I think it's not a good idea to add more after the first one started running. We don't currently forbid, it and I wouldn't argue in favour of doing so, but we shouldn't encourage it.

**Comment by smontanaro** [comment]
This has been idle for "awhile." Should we just put our heads together and decide how best to document this behavior?

**Comment by iritkatriel** [comment]
I'm not sure what the behaviour is. Or rather, what behaviour we want to commit to.

**Comment by smontanaro** [comment]
I'm not sure that committing to any particular behavior is the right thing to do without some more discussion. Maybe just warn that calling `atexit.register` after `_PyAtExit_Call` has been invoked is undefined. There's no mention of that corner case in the 3.11 or 3.12 documentation as it stands.
