### ISSUE TITLE
New matmul operator crashes modules compiled with CPython3.4

### ISSUE THREAD

**Issue by amauryfa** [python/cpython#67209]
BPO | [23020](https://bugs.python.org/issue23020)
--- | :---
Nosy | @malemburg, @loewis, @amauryfa, @pitrou, @benjaminp
Files | <li>[mytest.c](https://bugs.python.org/file37397/mytest.c "Uploaded as text/plain at 2014-12-09.12:42:12 by @amauryfa")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2014-12-09.12:31:43.258>
labels = ['type-feature', 'docs']
title = 'New matmul operator crashes modules compiled with CPython3.4'
updated_at = <Date 2015-07-05.10:41:46.925>
user = 'https://github.com/amauryfa'
```

bugs.python.org fields:
```python
activity = <Date 2015-07-05.10:41:46.925>
actor = 'pitrou'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2014-12-09.12:31:43.258>
creator = 'amaury.forgeotdarc'
dependencies = []
files = ['37397']
hgrepos = []
issue_num = 23020
keywords = []
message_count = 10.0
messages = ['232372', '232373', '232381', '232395', '232396', '232398', '232413', '232418', '232430', '246305']
nosy_count = 7.0
nosy_names = ['lemburg', 'loewis', 'amaury.forgeotdarc', 'pitrou', 'benjamin.peterson', 'Arfrever', 'docs@python']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23020'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
@encukou Is any of this still relevant?

**Comment by encukou** [comment]
It's not. If compiling with 3.4 and then importing in 3.5 ever worked, it was a coincidence.

The flags  `Py_TPFLAGS_HAVE_FINALIZE` and `Py_TPFLAGS_HAVE_VERSION_TAG` have no purpose. We're not adding new ones, but can't repurpose the bits for existing ones, so they're still around.
Perhaps Python 2 had an informal “best effort ABI compatibility” policy, but it's not something we can realistically test and adhere to. The Limited API subset is challenging enough.

[Docs](https://docs.python.org/3/c-api/stable.html#stable) have been improving over time, but even 3.3 mentions “the API compatibility does not extend to binary compatibility” (except with stable ABI).
