### ISSUE TITLE
csv writer needs more quoting rules

### ISSUE THREAD

**Issue by ca7ace24-b88c-4714-94ae-52605b2ac070** [python/cpython#67230]
BPO | [23041](https://bugs.python.org/issue23041)
--- | :---
Nosy | @smontanaro, @rhettinger, @bitdancer, @berkerpeksag, @serhiy-storchaka, @yoonghm, @erdnaxeli, @msetina
PRs | <li>python/cpython#29469</li>
Files | <li>[issue23041.patch](https://bugs.python.org/file37444/issue23041.patch "Uploaded as text/plain at 2014-12-14.05:14:53 by krypten"): Patch for resolving issue 23041. According to message 232560 and 232563</li><li>[issue23041_test.patch](https://bugs.python.org/file37445/issue23041_test.patch "Uploaded as text/plain at 2014-12-14.05:45:00 by krypten"): Test cases added for testing as behaviour proposed in message 232560</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/smontanaro'
closed_at = None
created_at = <Date 2014-12-12.16:36:45.576>
labels = ['easy', 'type-feature', 'library', '3.11']
title = 'csv needs more quoting rules'
updated_at = <Date 2022-02-24.00:07:17.586>
user = 'https://bugs.python.org/samwyse'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-24.00:07:17.586>
actor = 'samwyse'
assignee = 'skip.montanaro'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2014-12-12.16:36:45.576>
creator = 'samwyse'
dependencies = []
files = ['37444', '37445']
hgrepos = []
issue_num = 23041
keywords = ['patch', 'easy']
message_count = 26.0
messages = ['232560', '232561', '232563', '232596', '232607', '232630', '232676', '232677', '232681', '261141', '261146', '261147', '341460', '358461', '396621', '396641', '396642', '396643', '401607', '401608', '405951', '406013', '406015', '406017', '412463', '413867']
nosy_count = 11.0
nosy_names = ['skip.montanaro', 'rhettinger', 'samwyse', 'r.david.murray', 'berker.peksag', 'serhiy.storchaka', 'krypten', 'yoonghm', 'tegdev', 'erdnaxeli', 'msetina']
pr_nums = ['29469']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23041'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103491
* gh-103598

**Comment by regexaurus** [comment]
https://www.google.com/search?q=python+csv+quote+all+except+empty+string
brought me here... 😉

**Comment by smontanaro** [comment]
Where do we stand on this? If it's not going to make it into 3.12, I'm inclined to just close the PR and close this as "won't fix".

**Comment by samwyse** [comment]
What needs to be done to make this happen?  Is there anything else I can/need to do?  Did @krypten do anthing other than changing PyString_Check to PyUnicode_Check?

**Comment by serhiy-storchaka** [comment]
Please find popular applications or standard CSV implementations for popular programming languages which distinguish `""` and an empty field when load the CSV data.

**Comment by msetina** [comment]
Can this land in next version?

**Comment by smontanaro** [comment]
I posted a request for action on the [committers forum](https://discuss.python.org/t/can-we-get-some-action-on-this-pr/25710).

**Comment by merwok** [comment]
PR merged, thanks folks!

I realize too late that we should have added a note in whatsnew.  Can someone make a quick PR?

**Comment by smontanaro** [comment]
> PR merged, thanks folks!

Thanks for your quick work Éric.

> I realize too late that we should have added a note in whatsnew. Can someone make a quick PR?

Not sure I did it correctly, but here's a simple PR.

https://github.com/python/cpython/pull/103491

**Comment by samwyse** [comment]
Whoop!  Whoop!  Whoop!
It only took eight years, but it's finally across the finish line!
Many thanks to Skip, Éric, Serhiy, and everyone else who helped make this possible.

**Comment by msetina** [comment]
Thanks everyone who made this possible. CSV is a funny place.Now we meditate until official release and distros to pick it up.....

**Comment by serhiy-storchaka** [comment]
Wait, #29469 only changes writer, not reader. There are no tests for reader with new quoting styles, so we cannot be sure that nothing is broken.

Also, why do we need both QUOTE_STRINGS and QUOTE_NOTNULL? In what cases the difference is meaningful?

@samwyse, could you please provide external links to specifications of the difference between `""` and an empty field?

**Comment by smontanaro** [comment]
> There are no tests for reader with new quoting styles, so we cannot be sure that nothing is broken.

It's quite possible I failed to properly describe the changes in whatsnew. It does, indeed, only affect the writer, but as far as I can tell, the writer tests do exercise that code. Here's the switch statement from csv_writerow as noted by `llvm-cov`:

```
      899: 1263:        switch (dialect->quoting) {
        -: 1264:        case QUOTE_NONNUMERIC:
        4: 1265:            quoted = !PyNumber_Check(field);
        4: 1266:            break;
        -: 1267:        case QUOTE_ALL:
       10: 1268:            quoted = 1;
       10: 1269:            break;
        -: 1270:        case QUOTE_STRINGS:
        4: 1271:            quoted = PyUnicode_Check(field);
        4: 1272:            break;
        -: 1273:        case QUOTE_NOTNULL:
        4: 1274:            quoted = field != Py_None;
        4: 1275:            break;
        -: 1276:        default:
      877: 1277:            quoted = 0;
      877: 1278:            break;
        -: 1279:        }

```

Perhaps all that needs doing is to fix my hurried whatsnew entry to remove the `reader` reference.

**Comment by merwok** [comment]
> It does, indeed, only affect the writer

Oh oops!  Does this mean that the csv module can write files with the new quoting styles that it can’t read back?

**Comment by smontanaro** [comment]
@merwok It does kinda seem that way. Is half a loaf better than none? I'm not the person who wrote (or asked for) the changes, as I don't actually do anything unusual with CSV files (just the normal stuff...).

**Comment by smontanaro** [comment]
Looking at @samwyse's original post above, it seems all he wanted was to modify the writer. Sam, can you comment whether you think these two new data items should (try to) round trip?

**Comment by samwyse** [comment]
Back when I first submitted this, I was only interested in the writer. Later, people discussed being able to round trip the data, so I added references to the reader. We can drop the those references and open new request to add those.

As I was coding up the new tests for the writer, it occurred to me that we should use the same input for all quoting roles, so that the differences in the quoting rules are more obvious.

What is the dropdead date for 3.12?

**Comment by terryjreedy** [comment]
Beta1 is due in early May.  However, later betas are for fixing bugs in new features included in beta1.

I understand that there is a use for writing files to be written elsewhere, but round-tripping would seem better to me.

**Comment by samwyse** [comment]
Adding two more tests for readers is trivial. As I look at _csv.c, however, I can't really see an easy way to distinguish between «,,» and «,"",». So unless someone more knowledgeable than I thinks that it's simple, I propose that we punt this down the road, making the two new quoting rules illegal for reader objects for the time being. I am updating my branch to do this now.

**Comment by samwyse** [comment]
I think I have made it, so that using the new quoting rules in reader objects will raise an error. Note that I am not entirely confident in my ability to copy and paste C code.

**Comment by smontanaro** [comment]
Thinking more about the problem, I think it's wrong to do anything to the reader. In its entire history, the reader has never done any sort of type inference. That would be exactly what distinguishing an empty field from a quoted empty field would be, a (small) bit of type inference. Once you let the camel's nose under the tent, he's going to want to join the party and will ask for type inference of float, int, complex, and who knows what-all.

The better course at this point would be to adjust the docs to state that the two new quoting rules have no effect in the reader. My apologies for not thinking of this sooner (like a year or two ago).

**Comment by samwyse** [comment]
I'm not going to fire up the interpreter to check, but I thought that if a field looked like a number, then it was converted to float, and I further thought that only applied to unquoted fields. But my memory has been awful since the pandemic. Anyway, I like that plan.

**Comment by smontanaro** [comment]
Python's `csv` module always returns strings. The Pandas CSV file read does infer types though.

```
% cat names.csv
first_name,last_name,age
Eric,Idle,47
John,Cleese,99
% python
Python 3.12.0a7+ (heads/main-dirty:330a942b63, Apr 14 2023, 06:59:05) [Clang 14.0.3 (clang-1403.0.22.14.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import csv
>>> for row in csv.reader(open("names.csv")):
...   print(row)
... 
['first_name', 'last_name', 'age']
['Eric', 'Idle', '47']
['John', 'Cleese', '99']
>>> ^D
```

**Comment by msetina** [comment]
If I can add my pinch of salt. Here we colide data and programming world. In data world None is a value of a type. In Python None is a separate type. 
Using a paradigm from data world Oracle will equate empty string in strings with None. MS would not. 
On the reader side if you have a CSV to read and you want to preserve NULL values normally in non quoted there would be a special character combination (^N or something) to represent a NULL, so reader would be able to parse it.
Then came Microsoft where someone was not checking with others and used quoted values which are more expensive and thought that it was a good idea to use empty field for None. And for this a reader needs to infere None.
In Python using non quoted values in CSV is good, but there is an if, when users encounter MS produced CSV and want None values preserved. Maybe MS is not the only one, but they stepped on my toe.

**Comment by smontanaro** [comment]
I certainly understand the desire to interoperate with the MS CSV ecosystem, as that has traditionally been the _de facto_ "spec" for what it means to read and write CSV files. Still, I think  the topic would be too involved to deal with properly between now and May 1. I propose limiting the change for now to just the writer, fixing any doc bits which suggest there are any changes to the reader, then going through the usual PEP process to investigate making changes to the semantics of the reader.

**Comment by smontanaro** [comment]
Would someone like to work on a PEP regarding type conversion in the reader?

**Comment by erlend-aasland** [comment]
I'll try to summarise the state of this issue:

The proposed feature was to add more quoting rules to the `csv` _writer_. This has been implemented (with docs and tests)[^1]. @serhiy-storchaka requested in https://github.com/python/cpython/issues/67230#issuecomment-1508151585 that the issue be held open:

> Wait, #29469 only changes writer, not reader. There are no tests for reader with new quoting styles, so we cannot be sure that nothing is broken. [...]

@samwyse remarked in https://github.com/python/cpython/issues/67230#issuecomment-1509119833:

> [..] I can't really see an easy way [for csv reader] to distinguish between «,,» and «,"",». So unless someone more knowledgeable than I thinks that it's simple, I propose that we punt this down the road, making the two new quoting rules illegal for reader objects for the time being. [...]

@smontanaro https://github.com/python/cpython/issues/67230#issuecomment-1510375208:

> Thinking more about the problem, I think it's wrong to do anything to the reader. In its entire history, the reader has never done any sort of type inference. That would be exactly what distinguishing an empty field from a quoted empty field would be, a (small) bit of type inference. [...]

> The better course at this point would be to adjust the docs to state that the two new quoting rules have no effect in the reader. [...]

@smontanaro https://github.com/python/cpython/issues/67230#issuecomment-1513932517:

> Would someone like to work on a PEP regarding type conversion in the reader?

I suggest to close this as completed (the csv writer feature was implemented) and to open up a new issue regarding what to do with the csv reader.

[^1]: we should amend the issue title to reflect that the feature request was for the csv _writer_ only

**Comment by serhiy-storchaka** [comment]
> the reader has never done any sort of type inference.

But it does.
```
>>> next(csv.reader(['123,"123"']))
['123', '123']
>>> next(csv.reader(['123,"123"'], quoting=csv.QUOTE_NONNUMERIC))
[123.0, '123']
```
If quoting style is QUOTE_NONNUMERIC, it returns non-quoted field as numeric. I expect the same for None.

**Comment by erlend-aasland** [comment]
As I already wrote, I suggest to summarise the needed reader changes in a new issue.

**Comment by smontanaro** [comment]
> > the reader has never done any sort of type inference.
> 
> But it does.
> ```
> >>> next(csv.reader(['123,"123"']))
> ['123', '123']
> >>> next(csv.reader(['123,"123"'], quoting=csv.QUOTE_NONNUMERIC))
> [123.0, '123']
> ```
> If quoting style is QUOTE_NONNUMERIC, it returns non-quoted field as numeric. I expect the same for None.

That's not really inferring the type in my book. It's effectively being told by the programmer that unquoted numeric strings are to be returned as numbers. If it was inferring the type, your first example would also spit out a float as the first value.

**Comment by serhiy-storchaka** [comment]
Right, and I suggest that QUOTE_NOTNULL is told by the programmer that unquoted empty strings are to be returned as None.

**Comment by serhiy-storchaka** [comment]
It is perhaps too late to make this change in 3.12, so we can open a new issue.

**Comment by serhiy-storchaka** [comment]
Opened #113732.
