### ISSUE TITLE
Improve termcap detection in setup.py

### ISSUE THREAD

**Issue by 868eeb65-7235-4ffe-96c6-3bfdea8a38f0** [python/cpython#67473]
BPO | [23284](https://bugs.python.org/issue23284)
--- | :---
Nosy | @bitdancer, @skrah, @koobs, @mjeveritt
Files | <li>[34d54cc5ecfd.diff](https://bugs.python.org/file37796/34d54cc5ecfd.diff "Uploaded as text/plain at 2015-01-20.22:55:05 by pooryorick")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-01-20.22:51:23.645>
labels = ['build']
title = 'Improve termcap detection in setup.py'
updated_at = <Date 2019-09-30.01:35:11.922>
user = 'https://bugs.python.org/pooryorick'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-30.01:35:11.922>
actor = 'veremitz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2015-01-20.22:51:23.645>
creator = 'pooryorick'
dependencies = []
files = ['37796']
hgrepos = ['292']
issue_num = 23284
keywords = ['patch']
message_count = 12.0
messages = ['234399', '234699', '234981', '234982', '234983', '234987', '234988', '234995', '235005', '235007', '235035', '235036']
nosy_count = 5.0
nosy_names = ['pooryorick', 'r.david.murray', 'skrah', 'koobs', 'veremitz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue23284'
versions = ['Python 2.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`setup.py` no longer used to build CPython since 3.12 (see #94474).

And Python 2.7 no longer supported. Is this issue actual in newer Python versions?
