### ISSUE TITLE
Turn SIG_DFL and SIG_IGN into functions

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#67514]
BPO | [23325](https://bugs.python.org/issue23325)
--- | :---
Nosy | @warsaw, @brettcannon, @vstinner, @giampaolo, @tiran, @serhiy-storchaka, @zhangyangyu, @miss-islington
PRs | <li>python/cpython#8920</li><li>python/cpython#31759</li><li>python/cpython#31768</li>
Files | <li>[signal_std_handlers.patch](https://bugs.python.org/file37868/signal_std_handlers.patch "Uploaded as text/plain at 2015-01-26.20:38:29 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-01-26.20:38:30.138>
labels = ['type-feature', 'library', '3.9', '3.10', '3.11']
title = 'Turn SIG_DFL and SIG_IGN into functions'
updated_at = <Date 2022-03-31.17:54:28.870>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-31.17:54:28.870>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-01-26.20:38:30.138>
creator = 'serhiy.storchaka'
dependencies = []
files = ['37868']
hgrepos = []
issue_num = 23325
keywords = ['patch']
message_count = 14.0
messages = ['234775', '238327', '238495', '238538', '324075', '324084', '324096', '411037', '411045', '411104', '414747', '414749', '414765', '414767']
nosy_count = 9.0
nosy_names = ['barry', 'brett.cannon', 'vstinner', 'giampaolo.rodola', 'christian.heimes', 'eli.bendersky', 'serhiy.storchaka', 'xiang.zhang', 'miss-islington']
pr_nums = ['8920', '31759', '31768']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23325'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
Do we still want to do this?
While accepting `0` and `1` is undocumented, it's been that way for very long. IMO, it needs a deprecation period if it's changed.

That said, I don't think they should be changed. Counterpoints to the rationale:


* Enums already have names and self-descriptive representation.
* Docstrings don't seem very important to me
* These are special. IMO, the fact that the signature of signal() includes these is a *good* thing, documentation-wise.
* I'm not sure what you meant by pickle portability. Compatibility with what? In the proposed PR, it's pickled as `_signal.SIG_DFL`, depending on the CPython-specific C module.

I recommend closing.

**Comment by vstinner** [comment]
I agree to close the issue. I close it.

If tomorrow someone comes with a stronger use case, I can change my mind :-)

Anyway, @serhiy-storchaka, it was interesting to explore this idea. Maybe if it was done 10 or 15 years ago, it would make more sense. Today, we have to learn with these special cases.

---

If `SIG_DFL` and `SIG_IGN` become functions, people will want to call them, and I expect that it will complicated to implement `SIG_DFL`: you should call `signal.raise_signal(signum)`... but with which signal number? If we store the signal number, the same `SIG_DFL` object cannot be used for two signals. Or they should be fake functions which always fail, for example `raise NotImplementedError()`. But users may expect a different behavior.

I would be ok with replacing `SIG_DFL` and `SIG_IGN` with special non-callable objects, different than int. But I'm not sure the benefits are worth it compared to the risk of breaking existing code. Currently, it's possible to convert them to int. Should it still be the case if they are changed? If yes, what's the point?

> They will have names and self-descriptive representation.
> They will have docstrings.
> The signature of signal() will be simpler. The type of second argument would be function.
> Their pickling will be portable.

I'm not convinced that these problems are important enough compared to drawbacks.

I don't think that it's common to serialize/deserialize signal **handlers**! If your program does that, add special a case in your problem, no?

---

At the C level, these values are special function pointers:

```c
/usr/include/bits/signum-generic.h:#define	SIG_ERR	 ((__sighandler_t) -1)	/* Error return.  */
/usr/include/bits/signum-generic.h:#define	SIG_DFL	 ((__sighandler_t)  0)	/* Default action.  */
/usr/include/bits/signum-generic.h:#define	SIG_IGN	 ((__sighandler_t)  1)	/* Ignore signal.  */
```

In Python 3.13, there are now enums:

```
$ ./python
Python 3.13.0a5+ (heads/pr/116482:582a42056e, Mar 22 2024, 15:44:14) [GCC 13.2.1 20240316 (Red Hat 13.2.1-7)] on linux
>>> import signal
>>> signal.SIG_DFL
<Handlers.SIG_DFL: 0>
>>> signal.SIG_IGN
<Handlers.SIG_IGN: 1>
```

pickle serializes them as `signal.SIG_IGN` as `signal.Handlers(*(1,))`:

```py
import pickle, pickletools, signal
pickletools.dis(pickle.dumps(signal.SIG_IGN))
```

Output (commented):

```
    0: \x80 PROTO      4
    2: \x95 FRAME      29
   11: \x8c SHORT_BINUNICODE 'signal'
   19: \x94 MEMOIZE    (as 0)
   20: \x8c SHORT_BINUNICODE 'Handlers'    <== signal.Handlers
   30: \x94 MEMOIZE    (as 1)
   31: \x93 STACK_GLOBAL
   32: \x94 MEMOIZE    (as 2)
   33: K    BININT1    1   <== value 1
   35: \x85 TUPLE1
   36: \x94 MEMOIZE    (as 3)
   37: R    REDUCE
   38: \x94 MEMOIZE    (as 4)
   39: .    STOP
highest protocol among opcodes = 4
```

> Their pickling will be portable.

As @ethanfurman wrote, Handlers can be modified for that.
