### ISSUE TITLE
support encoded filename in Content-Disposition for HTTP in cgi.FieldStorage

### ISSUE THREAD

**Issue by b963a228-3341-41e2-9f22-3c3b78b439cd** [python/cpython#67622]
BPO | [23434](https://bugs.python.org/issue23434)
--- | :---
Nosy | @warsaw, @ezio-melotti, @bobince, @bitdancer, @vadmium, @serhiy-storchaka, @demianbrecht, @pawciobiel
PRs | <li>python/cpython#6027</li>
Files | <li>[test_cgi.py-v2.7.5-rfc6266_filename.patch](https://bugs.python.org/file38092/test_cgi.py-v2.7.5-rfc6266_filename.patch "Uploaded as text/plain at 2015-02-11.08:53:52 by Myroslav.Opyr"): test revealing the issue</li><li>[cgi.py-v2.7.5-rfc6266_filename.patch](https://bugs.python.org/file38094/cgi.py-v2.7.5-rfc6266_filename.patch "Uploaded as text/plain at 2015-02-11.10:32:25 by Myroslav.Opyr"): rfc6266 powered fix</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-02-10.14:54:47.750>
labels = ['3.7', '3.8', 'expert-email', 'type-feature', 'library', 'expert-unicode']
title = 'support encoded filename in Content-Disposition for HTTP in cgi.FieldStorage'
updated_at = <Date 2020-01-08.10:45:02.342>
user = 'https://bugs.python.org/MyroslavOpyr'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-08.10:45:02.342>
actor = 'aclover'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Unicode', 'email']
creation = <Date 2015-02-10.14:54:47.750>
creator = 'Myroslav.Opyr'
dependencies = []
files = ['38092', '38094']
hgrepos = []
issue_num = 23434
keywords = ['patch']
message_count = 11.0
messages = ['235688', '235732', '235734', '235909', '236101', '236365', '314265', '314297', '359224', '359533', '359577']
nosy_count = 10.0
nosy_names = ['barry', 'ezio.melotti', 'aclover', 'r.david.murray', 'Myroslav.Opyr', 'martin.panter', 'piotr.dobrogost', 'serhiy.storchaka', 'demian.brecht', 'pawciobiel']
pr_nums = ['6027']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23434'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by hugovk** [comment]
Closing, because the cgi module was deprecated in Python 3.11 and will be removed in 3.13:

* [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/)
* https://github.com/python/cpython/issues/91217

It has been moved to a separate package on PyPI, maintained by the community:

* https://discuss.python.org/t/pep-594-take-2-removing-dead-batteries-from-the-standard-library/13508/23?u=hugovk
* https://pypi.org/project/legacy-cgi/
