### ISSUE TITLE
undefined behavior in Objects/obmalloc.c

### ISSUE THREAD

**Issue by 63b67124-4b9a-4d47-9e93-6414df8e305a** [python/cpython#67691]
BPO | [23503](https://bugs.python.org/issue23503)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = None
created_at = <Date 2015-02-23.21:18:56.610>
labels = ['interpreter-core', 'type-bug']
title = 'undefined behavior in Objects/obmalloc.c'
updated_at = <Date 2016-09-19.08:40:15.568>
user = 'https://bugs.python.org/dwightguth'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-19.08:40:15.568>
actor = 'vstinner'
assignee = 'vstinner'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-02-23.21:18:56.610>
creator = 'dwight.guth'
dependencies = []
files = []
hgrepos = []
issue_num = 23503
keywords = []
message_count = 3.0
messages = ['236465', '276955', '276956']
nosy_count = 2.0
nosy_names = ['vstinner', 'dwight.guth']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue23503'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
These macros have now been moved to https://github.com/python/cpython/blob/main/Include/internal/pycore_obmalloc_init.h

**Comment by vstinner** [comment]
Python is tested by ASAN, MSAN and UBSAN, and different memory debuggers. Last years, nobody reported an issue about this code. IMO it's just fine. Moreover, no fix was proposed. I just close the issue.
