### ISSUE TITLE
using asyncio.iscoroutinefunction() on a functools.partial object

### ISSUE THREAD

**Issue by 15e9f43b-288f-4445-a6c8-05b36ae11f37** [python/cpython#67707]
BPO | [23519](https://bugs.python.org/issue23519)
--- | :---
Nosy | @gvanrossum, @vstinner, @mathieui, @1st1
Files | <li>[example_partial.py](https://bugs.python.org/file38246/example_partial.py "Uploaded as text/plain at 2015-02-26.13:26:19 by @mathieui")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2015-02-26.17:52:33.200>
created_at = <Date 2015-02-25.11:00:39.941>
labels = ['type-feature', 'invalid', 'expert-asyncio']
title = 'using asyncio.iscoroutinefunction() on a functools.partial object'
updated_at = <Date 2017-06-09.02:28:01.054>
user = 'https://github.com/mathieui'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.02:28:01.054>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2015-02-26.17:52:33.200>
closer = 'gvanrossum'
components = ['asyncio']
creation = <Date 2015-02-25.11:00:39.941>
creator = 'mathieui'
dependencies = []
files = ['38246']
hgrepos = []
issue_num = 23519
keywords = []
message_count = 8.0
messages = ['236569', '236570', '236592', '236660', '236668', '236693', '295475', '295478']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'vstinner', 'mathieui', 'yselivanov', 'curtmcd']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = None
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23519'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by 21b84a72-fd75-4d59-a151-18e4b882570e** [comment]
There are use cases for this. I hit the problem and eventually wound up here, so I'd like to make a case to re-open.

My project has a callback registry of asyncio handler routines.

```py
register_callback(condition1, handler1)
register_callback(condition2, handler2)
...
```


I want to register many callbacks, but use only one handler and an argument to differentiate it. I realize our callback systems should provide for a cookie, but it doesn't. 

```py
register_callback(condition1, functools.partial(handler, 'detail1'))
register_callback(condition2, functools.partial(handler, 'detail2'))
```


The callback registry makes sure iscoroutinefunction(handler) because we don't want to defer error checking to the distant future. But iscoroutinefunction() returns False for the partial function. I was hopeful that this might work, but alas, no:

```py
register_callback(condition1,
                  asyncio.coroutine(functools.partial(handler, 'detail1')))
```

**Comment by gvanrossum** [comment]
Use a lambda instead of partial. It's more pythonic.

**Comment by graingert** [comment]
this is fixed in https://github.com/python/cpython/issues/79071

**Comment by graingert** [comment]
looking at this more clearly - this is a bug in `asyncio.iscoroutinefunction` that was fixed for `inspect.iscoroutinefunction`

this code will now work - if you use `async def handler(detail):`

```python
register_callback(condition1, functools.partial(handler, 'detail1'))
register_callback(condition2, functools.partial(handler, 'detail2'))
```

here's a demo:
```python
import inspect
import functools
import asyncio

async def demo(v):
    pass


@asyncio.coroutine
def demo_old(v):
    pass


print(f"{inspect.iscoroutinefunction(functools.partial(demo, v=1))=}")
print(f"{asyncio.iscoroutinefunction(functools.partial(demo, v=1))=}")
print(f"{inspect.iscoroutinefunction(functools.partial(demo_old, v=1))=}")
print(f"{asyncio.iscoroutinefunction(functools.partial(demo_old, v=1))=}")

# this prints:
# /home/graingert/projects/bar.py:10: DeprecationWarning: "@coroutine" decorator is deprecated since Python 3.8, use "async def" instead
#   def demo_old(v):
# inspect.iscoroutinefunction(functools.partial(demo, v=1))=True
# asyncio.iscoroutinefunction(functools.partial(demo, v=1))=True
# inspect.iscoroutinefunction(functools.partial(demo_old, v=1))=False
# asyncio.iscoroutinefunction(functools.partial(demo_old, v=1))=False
```

**Comment by gvanrossum** [comment]
So can I close this? (I'm not sure what happened here exactly, I don't recall reopening, maybe GitHub did something funky?)

**Comment by graingert** [comment]
> So can I close this? (I'm not sure what happened here exactly, I don't recall reopening, maybe GitHub did something funky?)

ah I thought you were cryptically telling me the issue was still valid when you re-opened this - it caused me to re-read the issue and find that it is actually still a bug - although now only relevant on python 3.10 and maybe on 3.11

**Comment by graingert** [comment]
I have a PR to fix it here https://github.com/python/cpython/pull/94907 but I think it would be better to drop `asyncio.iscoroutinefunction`, `asyncio.coroutines._is_coroutine` and make `_wrap_awaitable` a real async fn

**Comment by gvanrossum** [comment]
Honestly if this is fixed in 3.11 by deleting `asyncio.coroutine` I would leave 3.10 alone.

Deleting `asyncio.iscoroutinefunction` would be problematic since it is ostensibly public so would have to be deprecated. But it sounds like you believe it could just become an alias for `inspect.iscoroutinefunction` if we change `_wrap_awaitable`? That sounds like we could do (though it's a bit late for 3.11 -- in main a.k.a. 3.12 I'd be okay with this though).

**Comment by graingert** [comment]
I opened an issue for that removal https://github.com/python/cpython/issues/94912

**Comment by gvanrossum** [comment]
Okay, closing this issue as fixed.
