### ISSUE TITLE
Reduce the number of comparisons for range checking.

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#67741]
BPO | [23553](https://bugs.python.org/issue23553)
--- | :---
Nosy | @rhettinger, @pitrou, @serhiy-storchaka
Files | <li>[size_t.diff](https://bugs.python.org/file38281/size_t.diff "Uploaded as text/plain at 2015-03-01.06:19:19 by @rhettinger"): Fix deque casts</li><li>[bounds_check_list.diff](https://bugs.python.org/file38282/bounds_check_list.diff "Uploaded as text/plain at 2015-03-01.07:14:55 by @rhettinger"): Faster bounds checking for lists.</li><li>[bounds_check_deque.diff](https://bugs.python.org/file38283/bounds_check_deque.diff "Uploaded as text/plain at 2015-03-01.07:50:31 by @rhettinger"): Faster bounds checking for deques</li><li>[valid_index.diff](https://bugs.python.org/file38293/valid_index.diff "Uploaded as text/plain at 2015-03-02.04:13:49 by @rhettinger"): Isolate the technique in an in-lineable function call</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-03-01.00:50:38.601>
labels = ['interpreter-core', 'performance']
title = 'Reduce the number of comparisons for range checking.'
updated_at = <Date 2015-03-02.04:13:50.021>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2015-03-02.04:13:50.021>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-03-01.00:50:38.601>
creator = 'rhettinger'
dependencies = []
files = ['38281', '38282', '38283', '38293']
hgrepos = []
issue_num = 23553
keywords = ['patch']
message_count = 13.0
messages = ['236928', '236931', '236933', '236934', '236935', '236938', '236939', '236940', '236942', '236945', '236946', '236948', '237011']
nosy_count = 5.0
nosy_names = ['rhettinger', 'pitrou', 'Arfrever', 'python-dev', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue23553'
versions = ['Python 3.5']
```

</p></details>

**Comment by iritkatriel** [comment]
Is there anything left to do on this issue?  It seems that at least some of it was already done in c20830804df99535b5566e93a4e56afd16cf0e99 and  f1aa8aed4a8ce9753ffa8713e7d3461663e0624d.
