### ISSUE TITLE
Implement __format__ for Fraction

### ISSUE THREAD

**Issue by 82db5dad-736b-4ac3-88c5-b5ba2c5e2b8c** [python/cpython#67790]
BPO | [23602](https://bugs.python.org/issue23602)
--- | :---
Nosy | @rhettinger, @mdickinson, @scoder, @ericvsmith, @ezio-melotti, @skrah, @vadmium, @serhiy-storchaka, @wm75, @skirpichev, @suutari
Files | <li>[issue23602.patch](https://bugs.python.org/file38378/issue23602.patch "Uploaded as text/plain at 2015-03-07.17:07:25 by @suutari"): Fraction.__format__ implementation, test cases and documentation</li><li>[issue23602v2.patch](https://bugs.python.org/file38394/issue23602v2.patch "Uploaded as text/plain at 2015-03-08.22:33:34 by @suutari")</li><li>[issue23602v3.patch](https://bugs.python.org/file38413/issue23602v3.patch "Uploaded as text/plain at 2015-03-09.22:23:51 by @suutari")</li><li>[issue23602v4.patch](https://bugs.python.org/file38728/issue23602v4.patch "Uploaded as text/plain at 2015-03-29.16:20:59 by @suutari"): Fraction.__format__ implementation, test cases and docs, Decimal.__format__ Py and C API unification with test cases</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2015-03-07.17:06:09.308>
labels = ['type-feature', 'library']
title = 'Implement __format__ for Fraction'
updated_at = <Date 2021-04-23.08:41:52.382>
user = 'https://github.com/suutari'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-23.08:41:52.382>
actor = 'Sergey.Kirpichev'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-03-07.17:06:09.308>
creator = 'tuomas.suutari'
dependencies = []
files = ['38378', '38394', '38413', '38728']
hgrepos = []
issue_num = 23602
keywords = ['patch']
message_count = 29.0
messages = ['237460', '237461', '237468', '237524', '237525', '237526', '237575', '237579', '237583', '237714', '237715', '238813', '239048', '239056', '239336', '239337', '239338', '239342', '239495', '239498', '239501', '239502', '239503', '239504', '239515', '239594', '239664', '239668', '239733']
nosy_count = 11.0
nosy_names = ['rhettinger', 'mark.dickinson', 'scoder', 'eric.smith', 'ezio.melotti', 'skrah', 'martin.panter', 'serhiy.storchaka', 'wolma', 'Sergey.Kirpichev', 'tuomas.suutari']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23602'
versions = ['Python 3.5']
```

</p></details>

### Linked PRs
* gh-100161
* gh-111320

**Comment by mdickinson** [comment]
Done for float-style formatting in #100161. I'm planning to make a new PR that adds support for the `d` presentation format before closing this issue.

**Comment by mdickinson** [comment]
> I'm planning to make a new PR that adds support for the `d` presentation format before closing this issue.

See #111320.

**Comment by skirpichev** [comment]
@mdickinson, https://github.com/python/cpython/pull/111320 was merged.  From the issue thread it seems one could be closed.

**Comment by mdickinson** [comment]
@skirpichev It could indeed! Thanks.
