### ISSUE TITLE
Modifications to support iOS as a cross-compilation target

### ISSUE THREAD

**Issue by 12cd5ddb-1b49-4d91-ac6c-8fce79b8b268** [python/cpython#67858]
BPO | [23670](https://bugs.python.org/issue23670)
--- | :---
Nosy | @doko42, @ronaldoussoren, @ncoghlan, @ned-deily, @bitdancer, @freakboy3742, @rovitotv, @Lukasa, @rkuska, @mpaolini, @moreati, @controversial, @Mariatta
Files | <li>[20150314.diff](https://bugs.python.org/file38493/20150314.diff "Uploaded as text/plain at 2015-03-15.06:24:58 by @freakboy3742"): Patch for Python 3.4.2 source tree</li><li>[20150426.diff](https://bugs.python.org/file39207/20150426.diff "Uploaded as text/plain at 2015-04-26.04:01:42 by @freakboy3742"): Updated patch for Python 3.4.2 source tree</li><li>[20150504.diff](https://bugs.python.org/file39286/20150504.diff "Uploaded as text/plain at 2015-05-04.07:46:04 by @freakboy3742"): Updated patch with support for running the test suite.</li><li>[20150628.diff](https://bugs.python.org/file39824/20150628.diff "Uploaded as text/plain at 2015-06-28.13:46:33 by @freakboy3742"): Updated patch, passing test suite on iOS simulator.</li><li>[20150704.diff](https://bugs.python.org/file39862/20150704.diff "Uploaded as text/plain at 2015-07-04.16:36:18 by @freakboy3742"): Update 5 - only failing ctypes-related tests on device.</li><li>[20151221.diff](https://bugs.python.org/file41376/20151221.diff "Uploaded as text/plain at 2015-12-21.02:00:35 by @freakboy3742"): Update 6 - single source tree for libffi_ios</li><li>[20160301-brokentests.diff](https://bugs.python.org/file42059/20160301-brokentests.diff "Uploaded as text/plain at 2016-03-02.00:11:11 by @moreati"): Incomplete rebase of Update 6 against Python 3.6dev</li><li>[20160217.diff](https://bugs.python.org/file42060/20160217.diff "Uploaded as text/plain at 2016-03-02.01:35:57 by @freakboy3742"): Patch against 3.5.1</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2015-03-15.06:25:47.056>
labels = ['type-feature', '3.7', 'build']
title = 'Modifications to support iOS as a cross-compilation target'
updated_at = <Date 2019-09-04.00:08:40.855>
user = 'https://github.com/freakboy3742'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-04.00:08:40.855>
actor = 'josh.r'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Build', 'Cross-Build']
creation = <Date 2015-03-15.06:25:47.056>
creator = 'freakboy3742'
dependencies = []
files = ['38493', '39207', '39286', '39824', '39862', '41376', '42059', '42060']
hgrepos = ['300']
issue_num = 23670
keywords = ['patch']
message_count = 28.0
messages = ['238125', '238127', '238129', '238133', '238134', '238138', '238156', '238167', '238190', '238191', '238197', '238211', '240307', '241187', '241189', '242040', '242547', '245903', '246266', '256780', '256797', '261093', '261095', '267030', '267064', '267092', '284441', '305628']
nosy_count = 15.0
nosy_names = ['doko', 'ronaldoussoren', 'ncoghlan', 'ned.deily', 'r.david.murray', 'cvrebert', 'freakboy3742', 'Todd.Rovito', 'bkabrda', 'Lukasa', 'rkuska', 'mpaolini', 'Alex.Willmer', 'Luke Taylor', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue23670'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 12cd5ddb-1b49-4d91-ac6c-8fce79b8b268** [comment]
For those interested, I've started tracking these patches on Github: https://github.com/freakboy3742/cpython 

The 3.4, 3.5 and 3.6 branches are tested and compile as of the time of this comment; the master branch has also been updated, in preparation for the release of 3.7.

I haven't submitted pull requests because there are still some issues that Ned raised in discussions at PyCon US.

**Comment by ned-deily** [comment]
After discussion with @freakboy3742, we agreed that much has changed since this issue was opened and so it makes most sense to close this issue in favor of a new one, with PRs targeted for 3.13, that reflect the current approaches and changes needed in cpython, for the most part, simpler changes.
