### ISSUE TITLE
Library and include paths not added when cross-compiling on localized system

### ISSUE THREAD

**Issue by a510d378-e1cb-4429-b8ae-2b8528bee3bd** [python/cpython#67955]
BPO | [23767](https://bugs.python.org/issue23767)
--- | :---
Nosy | @doko42, @tpetazzoni, @ZackerySpytz
PRs | <li>python/cpython#24919</li>
Files | <li>[0001-Override-system-locale-and-set-to-default-when-addin.patch](https://bugs.python.org/file38671/0001-Override-system-locale-and-set-to-default-when-addin.patch "Uploaded as text/plain at 2015-03-24.20:03:59 by kernevil"): Patch to override system locale</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-03-24.20:04:00.218>
labels = ['build']
title = 'Library and include paths not added when cross-compiling on localized system'
updated_at = <Date 2021-03-18.15:54:46.267>
user = 'https://bugs.python.org/kernevil'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-18.15:54:46.267>
actor = 'doko'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2015-03-24.20:04:00.218>
creator = 'kernevil'
dependencies = []
files = ['38671']
hgrepos = []
issue_num = 23767
keywords = ['patch']
message_count = 3.0
messages = ['239173', '244395', '389024']
nosy_count = 5.0
nosy_names = ['doko', 'Arfrever', 'thomas-petazzoni', 'kernevil', 'ZackerySpytz']
pr_nums = ['24919']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue23767'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by erlend-aasland** [comment]
setup.py no longer exists; closing this issue as outdated.
