### ISSUE TITLE
Missing sanity checks for various C library function calls...

### ISSUE THREAD

**Issue by 4c4ec529-4950-4229-a691-2e33119aa84f** [python/cpython#68066]
BPO | [23878](https://bugs.python.org/issue23878)
--- | :---
Nosy | @terryjreedy, @vstinner, @ned-deily, @ZackerySpytz
PRs | <li>python/cpython#15424</li><li>python/cpython#15555</li>
Files | <li>[getpath.c.patch](https://bugs.python.org/file38848/getpath.c.patch "Uploaded as text/plain at 2015-04-06.17:00:27 by dogbert2")</li><li>[ffi.c.patch](https://bugs.python.org/file38849/ffi.c.patch "Uploaded as text/plain at 2015-04-06.17:01:00 by dogbert2"): patch file (diff -u) for this bug</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-28.21:59:13.862>
created_at = <Date 2015-04-06.17:00:27.258>
labels = ['interpreter-core', 'type-bug', '3.9']
title = 'Missing sanity checks for various C library function calls...'
updated_at = <Date 2019-08-28.22:02:08.513>
user = 'https://bugs.python.org/dogbert2'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-28.22:02:08.513>
actor = 'ZackerySpytz'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-28.21:59:13.862>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2015-04-06.17:00:27.258>
creator = 'dogbert2'
dependencies = []
files = ['38848', '38849']
hgrepos = []
issue_num = 23878
keywords = ['patch']
message_count = 8.0
messages = ['240160', '240161', '240179', '240180', '240439', '240440', '350689', '350690']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'vstinner', 'ned.deily', 'dogbert2', 'ZackerySpytz']
pr_nums = ['15424', '15555']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue23878'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
Reopened as per https://github.com/python/cpython/pull/15555#issuecomment-892701128.

**Comment by iritkatriel** [comment]
Closing again. I don't think this has anything to do with https://github.com/python/cpython/pull/15555.

**Comment by vstinner** [comment]
The _Py_FindEnvConfigValue() function was removed in Python 3.11 :-)
