### ISSUE TITLE
Define EXIT_SUCCESS and EXIT_FAILURE constants in sys

### ISSUE THREAD

**Issue by abalkin** [python/cpython#68241]
BPO | [24053](https://bugs.python.org/issue24053)
--- | :---
Nosy | @abalkin, @pitrou, @scoder, @rbtcollins, @skrah, @berkerpeksag, @vadmium, @serhiy-storchaka, @eamanu, @eedmunds, @Fat-Zer
PRs | <li>python/cpython#14773</li>
Files | <li>[issue24053.patch](https://bugs.python.org/file39197/issue24053.patch "Uploaded as text/plain at 2015-04-24.16:29:54 by @abalkin")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2015-04-24.15:47:49.923>
labels = ['easy', 'type-feature', '3.8']
title = 'Define EXIT_SUCCESS and EXIT_FAILURE constants in sys'
updated_at = <Date 2022-02-19.08:03:29.457>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-19.08:03:29.457>
actor = 'mark.dickinson'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2015-04-24.15:47:49.923>
creator = 'belopolsky'
dependencies = []
files = ['39197']
hgrepos = []
issue_num = 24053
keywords = ['patch', 'easy']
message_count = 37.0
messages = ['241949', '241953', '241960', '241962', '241966', '241972', '241978', '242061', '242126', '242129', '242130', '242131', '242132', '242133', '242135', '242137', '242139', '242141', '242142', '242143', '242144', '242145', '242146', '242147', '242148', '242149', '242150', '242151', '242152', '242153', '242154', '247081', '255473', '331714', '332526', '413528', '413537']
nosy_count = 11.0
nosy_names = ['belopolsky', 'pitrou', 'scoder', 'rbcollins', 'skrah', 'berker.peksag', 'martin.panter', 'serhiy.storchaka', 'eamanu', 'edmundselliot@gmail.com', 'Fat-Zer']
pr_nums = ['14773']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24053'
versions = ['Python 3.8']
```

</p></details>

**Comment by arhadthedev** [comment]
> If I am alone in finding exit(EXIT_FAILURE) clearer than exit(1), I should certainly drop my proposal.

@abalkin Currently, `sys.exit(message)` chooses the `EXIT_SUCCESS`/`EXIT_FAILURE` code depending on whether the message is `None`.

Is `sys.exit(EXIT_FAILURE)`/`sys.exit(EXIT_FAILURE)` still relevant then?

**Comment by calestyo** [comment]
> Is sys.exit(EXIT_SUCCESS)/sys.exit(EXIT_FAILURE) still relevant then?

Maybe one doesn't want to give an actual message but just control the exit status?

Also I have for example code, where depending on what happens I set some `exit_status` variable. But I don't e.g. just pass that to `sys.exit()` in the end, but have another `if` before, that would want to check something like `exit_status  != EXIT_SUCCESS` and do extra things depending on that.<br>
So I think one really "needs" the symbol.

Also, these are really standardised system symbols, so people might want to use them for checking exit statuses of subprocesses and not just as part of `sys.exit()`.


As for the discussion about `sys` vs. `os`... AFAIU POSIX, only `EXIT_SUCCESS` is defined to be a fixed value (`0`)... so I'd interpret that as `EXIT_FAILURE` being potentially platform-dependent.<br>
Oh and it was mentioned that `EX_OK` would be documented as UNIX-only, but current documentation seems to say "Availability: Unix, Windows.".

**Comment by pitrou** [comment]
Hmm... let's be pragmatic here. `sys.exit(0)` is known to exit with success. `sys.exit(non-zero integer)` is known to be a failure exit. Which exit code you choose is on you: many CLI utilities can actually return different error codes depending on the actual error.

Since all concrete use cases are well-served already, I will close this isuue.
