### ISSUE TITLE
pstats: sub-millisecond display

### ISSUE THREAD

**Issue by 9787827c-78cc-4d77-be81-21e7d5656b49** [python/cpython#68272]
BPO | [24084](https://bugs.python.org/issue24084)
--- | :---
Nosy | @birkenfeld, @vstinner, @ned-deily, @methane, @serhiy-storchaka, @romuald
PRs | <li>python/cpython#3931</li>
Files | <li>[pstats-microseconds.patch](https://bugs.python.org/file39237/pstats-microseconds.patch "Uploaded as text/plain at 2015-04-30.16:27:50 by @romuald")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-04-30.16:27:51.902>
labels = ['3.8', 'type-feature', 'library']
title = 'pstats: sub-millisecond display'
updated_at = <Date 2019-11-22.12:37:17.741>
user = 'https://github.com/romuald'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-22.12:37:17.741>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-04-30.16:27:51.902>
creator = 'Romuald'
dependencies = []
files = ['39237']
hgrepos = []
issue_num = 24084
keywords = ['patch']
message_count = 6.0
messages = ['242277', '303966', '303981', '304248', '304249', '313498']
nosy_count = 6.0
nosy_names = ['georg.brandl', 'vstinner', 'ned.deily', 'methane', 'serhiy.storchaka', 'Romuald']
pr_nums = ['3931']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24084'
versions = ['Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
Hum, "2447µs" makes the output more difficult to parse (by a program) and to read (by a human). Why not always displaying 6 digits (after the dot) for the two "percall" columns.

**Comment by 9787827c-78cc-4d77-be81-21e7d5656b49** [comment]
I figured we didn't want to change the size of the columns (+12 COL), but this could easily be done yes

**Comment by serhiy-storchaka** [comment]
I concur with Victor. This change likely breaks graphical viewers of pstat data.

How gprof and similar tools solve the problem of outputting sub-millisecond timings?

**Comment by vstinner** [comment]
> I concur with Victor. This change likely breaks graphical viewers of pstat data.

I propose to \*do* break the format by always displaying percall timings with a precision of 6 digits.

**Comment by arhadthedev** [comment]
Closing because there is no progress for the last five years on what output format would be readable.

However, feel free to ping me to reopen the issue and PR back if there is a chance to revive them.
