### ISSUE TITLE
In pdb using "until X" doesn't seem to have effect in commands

### ISSUE THREAD

**Issue by caa1f590-a756-4182-9fca-331c8e237b9b** [python/cpython#68328]
BPO | [24140](https://bugs.python.org/issue24140)
--- | :---
Nosy | @birkenfeld, @xdegaye
Files | <li>[test.py](https://bugs.python.org/file39326/test.py "Uploaded as text/plain at 2015-05-09.15:40:33 by vyktor")</li><li>[minimal.py](https://bugs.python.org/file39327/minimal.py "Uploaded as text/plain at 2015-05-09.15:49:21 by vyktor"): Minmal reproducable example</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-05-07.11:31:04.988>
labels = ['type-bug', 'library']
title = 'In pdb using "until X" doesn\'t seem to have effect in commands'
updated_at = <Date 2015-05-09.19:41:21.063>
user = 'https://bugs.python.org/vyktor'
```

bugs.python.org fields:
```python
activity = <Date 2015-05-09.19:41:21.063>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-05-07.11:31:04.988>
creator = 'vyktor'
dependencies = []
files = ['39326', '39327']
hgrepos = []
issue_num = 24140
keywords = []
message_count = 5.0
messages = ['242711', '242800', '242813', '242816', '242837']
nosy_count = 3.0
nosy_names = ['georg.brandl', 'xdegaye', 'vyktor']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24140'
versions = ['Python 3.2']
```

</p></details>

**Comment by gaogaotiantian** [comment]
Fixed in #124401
