### ISSUE TITLE
Support |= for parameters in converters

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#68333]
BPO | [24145](https://bugs.python.org/issue24145)
--- | :---
Nosy | @warsaw, @rhettinger, @gpshead, @ncoghlan, @larryhastings, @zware, @serhiy-storchaka
Files | <li>[larry.clinic.or.equals.for.parameters.1.txt](https://bugs.python.org/file39322/larry.clinic.or.equals.for.parameters.1.txt "Uploaded as text/plain at 2015-05-08.12:33:11 by @larryhastings")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2015-05-08.12:33:11.955>
labels = ['type-feature', 'expert-argument-clinic']
title = 'Support |= for parameters in converters'
updated_at = <Date 2018-06-14.10:28:23.675>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-14.10:28:23.675>
actor = 'taleinat'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2015-05-08.12:33:11.955>
creator = 'larry'
dependencies = []
files = ['39322']
hgrepos = []
issue_num = 24145
keywords = []
message_count = 5.0
messages = ['242756', '242758', '242759', '242784', '242801']
nosy_count = 7.0
nosy_names = ['barry', 'rhettinger', 'gregory.p.smith', 'ncoghlan', 'larry', 'zach.ware', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24145'
versions = ['Python 3.5']
```

</p></details>

**Comment by erlend-aasland** [comment]
A lot of methods and functions have been converted the last 9 years, and so far, there has been no problems with the current syntax. I think Serhiy, Raymond, and Nick's remarks still hold. (Also, I agree with Raymond, so count me as -1.)

Suggesting to close this as wont-implement.
