### ISSUE TITLE
test_mailcap fails if a mailcap file contains a non-decodable character

### ISSUE THREAD

**Issue by d17ed360-6e47-418f-9b03-45f13f57d78e** [python/cpython#68340]
BPO | [24152](https://bugs.python.org/issue24152)
--- | :---
Nosy | @ned-deily
Files | <li>[results](https://bugs.python.org/file39330/results "Uploaded as text/plain at 2015-05-09.20:45:44 by petrosr2")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-05-09.20:45:44.388>
labels = ['library']
title = 'test_mailcap fails if a mailcap file contains a non-decodable character'
updated_at = <Date 2015-05-09.21:42:06.442>
user = 'https://bugs.python.org/petrosr2'
```

bugs.python.org fields:
```python
activity = <Date 2015-05-09.21:42:06.442>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-05-09.20:45:44.388>
creator = 'petrosr2'
dependencies = []
files = ['39330']
hgrepos = ['308']
issue_num = 24152
keywords = []
message_count = 3.0
messages = ['242840', '242842', '242843']
nosy_count = 2.0
nosy_names = ['ned.deily', 'petrosr2']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue24152'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by hugovk** [comment]
Note that mailcap will be deprecated in Python 3.11 and removed in 3.13:

* [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/)
* https://github.com/python/cpython/issues/91217

**Comment by AA-Turner** [comment]
Closing per Hugo's comment.

A

**Comment by hugovk** [comment]
Actually closing per my comment :)

Plus 3.12 is now closed to new features, and realistically this won't be fixed in the next two weeks.

https://discuss.python.org/t/postponing-3-12-beta-1-feature-freeze/26406/11?u=hugovk
