### ISSUE TITLE
test_trace uses test_pprint

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#68403]
BPO | [24215](https://bugs.python.org/issue24215)
--- | :---
Nosy | @terryjreedy, @abalkin, @larryhastings, @bitdancer, @serhiy-storchaka
Files | <li>[issue24215.patch](https://bugs.python.org/file39431/issue24215.patch "Uploaded as text/plain at 2015-05-19.13:33:37 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-05-17.05:55:50.073>
labels = ['type-bug', 'tests']
title = 'test_trace uses test_pprint'
updated_at = <Date 2018-06-03.15:47:58.591>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-03.15:47:58.591>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2015-05-17.05:55:50.073>
creator = 'serhiy.storchaka'
dependencies = []
files = ['39431']
hgrepos = []
issue_num = 24215
keywords = ['patch']
message_count = 10.0
messages = ['243386', '243416', '243582', '243584', '243588', '243592', '243594', '243614', '243679', '318561']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'belopolsky', 'larry', 'r.david.murray', 'python-dev', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24215'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

### Linked PRs
* gh-108910
* gh-109104
* gh-109105

**Comment by hugovk** [comment]
The linked PRs have been merged, can this issue be closed?
