### ISSUE TITLE
OSError 17 due to _multiprocessing/semaphore.c assuming a one-to-one Pid -> process mapping.

### ISSUE THREAD

**Issue by 7cbc12be-fad0-4960-8f44-7adf5caa913a** [python/cpython#68491]
BPO | [24303](https://bugs.python.org/issue24303)
--- | :---
Nosy | @vstinner, @vapier, @benjaminp, @djc, @floppym, @applio
PRs | <li>python/cpython#10279</li>
Files | <li>[test-issue24303.py](https://bugs.python.org/file39594/test-issue24303.py "Uploaded as text/plain at 2015-06-02.07:38:10 by @vapier")</li><li>[mp_sem_race.diff](https://bugs.python.org/file39679/mp_sem_race.diff "Uploaded as text/plain at 2015-06-11.06:11:49 by neologix")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/applio'
closed_at = None
created_at = <Date 2015-05-27.18:22:59.163>
labels = ['type-bug', 'library']
title = 'OSError 17 due to _multiprocessing/semaphore.c assuming a one-to-one Pid -> process mapping.'
updated_at = <Date 2018-11-01.05:41:44.496>
user = 'https://bugs.python.org/PaulHobbs'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-01.05:41:44.496>
actor = 'benjamin.peterson'
assignee = 'davin'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-05-27.18:22:59.163>
creator = 'Paul Hobbs'
dependencies = []
files = ['39594', '39679']
hgrepos = []
issue_num = 24303
keywords = ['patch', 'needs review']
message_count = 17.0
messages = ['244211', '244425', '244435', '244592', '244657', '244658', '244797', '245156', '260058', '260061', '260185', '260208', '328934', '328944', '329043', '329045', '329046']
nosy_count = 13.0
nosy_names = ['vstinner', 'vapier', 'benjamin.peterson', 'djc', 'jnoller', 'Arfrever', 'neologix', 'python-dev', 'sbt', 'floppymaster', 'davin', 'Paul Hobbs', 'ryan.petrello']
pr_nums = ['10279']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24303'
versions = ['Python 2.7', 'Python 3.3']
```

</p></details>

**Comment by gpshead** [comment]
This was fixed in Python 3 by having the name be created in Python similar to how that 2.7 patch does it.

  https://github.com/python/cpython/blob/3.11/Lib/multiprocessing/synchronize.py#L122

That code has been there for 11 years via https://github.com/python/cpython/commit/84ed9a68bd9a13252b376b21a9167dabae254325 which was the change implementing the larger refactoring mentioned by the author of this issue.
