### ISSUE TITLE
Better repr for threading objects

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#68579]
BPO | [24391](https://bugs.python.org/issue24391)
--- | :---
Nosy | @rhettinger, @terryjreedy, @pitrou, @vstinner, @larryhastings, @rbtcollins, @berkerpeksag, @serhiy-storchaka, @applio
PRs | <li>python/cpython#20534</li>
Files | <li>[threading_objects_reprs.patch](https://bugs.python.org/file39637/threading_objects_reprs.patch "Uploaded as text/plain at 2015-06-06.10:23:36 by @serhiy-storchaka")</li><li>[threading_objects_reprs_2.patch](https://bugs.python.org/file39642/threading_objects_reprs_2.patch "Uploaded as text/plain at 2015-06-06.15:42:01 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2015-06-06.10:21:42.594>
labels = ['type-feature', 'library', '3.11']
title = 'Better repr for threading objects'
updated_at = <Date 2021-09-29.10:08:23.064>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-29.10:08:23.064>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-06-06.10:21:42.594>
creator = 'serhiy.storchaka'
dependencies = []
files = ['39637', '39642']
hgrepos = []
issue_num = 24391
keywords = ['patch']
message_count = 18.0
messages = ['244896', '244900', '244902', '244903', '244905', '244907', '244910', '244911', '244912', '244917', '244958', '245267', '248084', '250446', '275649', '370327', '402699', '402843']
nosy_count = 9.0
nosy_names = ['rhettinger', 'terry.reedy', 'pitrou', 'vstinner', 'larry', 'rbcollins', 'berker.peksag', 'serhiy.storchaka', 'davin']
pr_nums = ['20534']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24391'
versions = ['Python 3.11']
```

</p></details>

**Comment by hauntsaninja** [comment]
Thanks, looks like this has been completed. There's a separate issue for corresponding changes to multiprocessing
