### ISSUE TITLE
webbrowser.py update to use argparse.py

### ISSUE THREAD

**Issue by e8b18e15-b174-47da-b66c-e974cfb122f9** [python/cpython#68583]
BPO | [24395](https://bugs.python.org/issue24395)
--- | :---
Nosy | @birkenfeld, @berkerpeksag
Files | <li>[webbrowser.py](https://bugs.python.org/file39641/webbrowser.py "Uploaded as text/plain at 2015-06-06.15:22:56 by Hasan Diwan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-06-06.15:22:59.767>
labels = ['type-feature', 'library']
title = 'webbrowser.py update to use argparse.py'
updated_at = <Date 2019-03-15.22:00:55.953>
user = 'https://bugs.python.org/HasanDiwan'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-15.22:00:55.953>
actor = 'BreamoreBoy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-06-06.15:22:59.767>
creator = 'Hasan Diwan'
dependencies = []
files = ['39641']
hgrepos = []
issue_num = 24395
keywords = []
message_count = 3.0
messages = ['244913', '244915', '244918']
nosy_count = 3.0
nosy_names = ['georg.brandl', 'berker.peksag', 'Hasan Diwan']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24395'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-117047

**Comment by CAM-Gerlach** [comment]
Just to confirm, `getopt` is [still used in `webbrowser`](https://github.com/python/cpython/blob/457a459c7804950d4c27a243b176eb933ec87a06/Lib/webbrowser.py#L601) as of the beginning of the Python 3.13 cycle. Replacing it with argparse would improve usability, reduce manual argument parsing code and avoid the use of a legacy module, per #105735

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/117047.
