### ISSUE TITLE
xml.dom.minidom: performance issue with Node.insertBefore()

### ISSUE THREAD

**Issue by 705f9d9f-f280-49da-bc48-8abdfed87cf5** [python/cpython#68612]
BPO | [24424](https://bugs.python.org/issue24424)
--- | :---
Nosy | @benjaminp, @berkerpeksag, @serhiy-storchaka
Files | <li>[minidom.insertBefore.patch](https://bugs.python.org/file39674/minidom.insertBefore.patch "Uploaded as text/plain at 2015-06-10.13:29:15 by Robert Haschke"): simple patch for this issue</li><li>[minidom.insertBefore.patch](https://bugs.python.org/file43414/minidom.insertBefore.patch "Uploaded as text/plain at 2016-06-16.14:52:52 by Robert Haschke"): patch in unified diff format</li><li>[minidom_example.py](https://bugs.python.org/file43436/minidom_example.py "Uploaded as text/plain at 2016-06-17.12:45:52 by Robert Haschke"): example demonstrating the performance boost</li><li>[minidom_example2.py](https://bugs.python.org/file43438/minidom_example2.py "Uploaded as text/plain at 2016-06-17.14:39:06 by @serhiy-storchaka"): example demonstrating the performance regression</li><li>[etree_example.py](https://bugs.python.org/file43439/etree_example.py "Uploaded as text/plain at 2016-06-17.14:39:42 by @serhiy-storchaka")</li><li>[minidom.insertBefore2.patch](https://bugs.python.org/file43445/minidom.insertBefore2.patch "Uploaded as text/plain at 2016-06-18.06:41:48 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2015-06-10.13:29:16.632>
labels = ['expert-XML', 'performance']
title = 'xml.dom.minidom: performance issue with Node.insertBefore()'
updated_at = <Date 2016-06-18.15:21:46.035>
user = 'https://bugs.python.org/RobertHaschke'
```

bugs.python.org fields:
```python
activity = <Date 2016-06-18.15:21:46.035>
actor = 'Robert Haschke'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['XML']
creation = <Date 2015-06-10.13:29:16.632>
creator = 'Robert Haschke'
dependencies = []
files = ['39674', '43414', '43436', '43438', '43439', '43445']
hgrepos = []
issue_num = 24424
keywords = ['patch']
message_count = 13.0
messages = ['245128', '254134', '268664', '268669', '268671', '268710', '268722', '268726', '268731', '268736', '268741', '268767', '268815']
nosy_count = 5.0
nosy_names = ['benjamin.peterson', 'berker.peksag', 'serhiy.storchaka', 'Robert Haschke', 'guihome']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue24424'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
This optimization was mostly relevant to 2.7, which is no longer going to be updated. Shall we close this issue?
