### ISSUE TITLE
Add metrics to future objects (concurrent or asyncio?)

### ISSUE THREAD

**Issue by d13f0d4a-d7b9-4a53-b145-327702474f5e** [python/cpython#68639]
BPO | [24451](https://bugs.python.org/issue24451)
--- | :---
Nosy | @gvanrossum, @brianquinlan, @pitrou, @vstinner, @giampaolo, @1st1
Files | <li>[prototype.patch](https://bugs.python.org/file39711/prototype.patch "Uploaded as text/plain at 2015-06-15.18:42:57 by Joshua.Harlow"): prototype patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-06-14.17:16:11.198>
labels = ['type-feature', 'library']
title = 'Add metrics to future objects (concurrent or asyncio?)'
updated_at = <Date 2015-06-15.18:42:59.137>
user = 'https://bugs.python.org/JoshuaHarlow'
```

bugs.python.org fields:
```python
activity = <Date 2015-06-15.18:42:59.137>
actor = 'Joshua.Harlow'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-06-14.17:16:11.198>
creator = 'Joshua.Harlow'
dependencies = []
files = ['39711']
hgrepos = []
issue_num = 24451
keywords = ['patch']
message_count = 5.0
messages = ['245345', '245370', '245371', '245383', '245402']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'bquinlan', 'pitrou', 'vstinner', 'giampaolo.rodola', 'yselivanov', 'Joshua.Harlow']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24451'
versions = []
```

</p></details>

**Comment by willingc** [comment]
I will close this issue as overly broad for Asyncio and say there would be performance considerations. If there is a specific desired metric based on the current asyncio implementation, let's open a new issue and discuss that metric in a more scoped manner. Thanks.
