### ISSUE TITLE
Can't specify encoding with fileinput and inplace=True

### ISSUE THREAD

**Issue by 9505c713-bcdd-4f76-9351-74d1a4b0dea9** [python/cpython#68682]
BPO | [24494](https://bugs.python.org/issue24494)
--- | :---
Nosy | @bitdancer, @lilydjwg

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-06-24.03:47:29.040>
labels = ['type-feature', 'library']
title = "Can't specify encoding with fileinput and inplace=True"
updated_at = <Date 2015-06-24.13:38:34.413>
user = 'https://github.com/lilydjwg'
```

bugs.python.org fields:
```python
activity = <Date 2015-06-24.13:38:34.413>
actor = 'r.david.murray'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-06-24.03:47:29.040>
creator = 'lilydjwg'
dependencies = []
files = []
hgrepos = []
issue_num = 24494
keywords = []
message_count = 2.0
messages = ['245711', '245740']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'lilydjwg']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24494'
versions = ['Python 3.6']
```

</p></details>

**Comment by smheidrich** [comment]
Since 3.10 added the `encoding` parameter to `input` and `FileInput`, can this be closed as no longer needed?

The docs for the [`hook_encoded`](https://docs.python.org/3/library/fileinput.html#fileinput.hook_encoded) convenience function now mention:

>Deprecated since version 3.10: This function is deprecated since [fileinput.input()](https://docs.python.org/3/library/fileinput.html#fileinput.input) and [FileInput](https://docs.python.org/3/library/fileinput.html#fileinput.FileInput) now have encoding and errors parameters.

So I think the same thing applies across the board to encoding-via-hook functionality such as what this ticket requests, doesn't it?

**Comment by arhadthedev** [comment]
Can confirm, gh-25272 added the parameter into both places.
