### ISSUE TITLE
shutil.which wrong result on Windows

### ISSUE THREAD

**Issue by 81103f55-b23b-4743-b9a9-dc110d7aef44** [python/cpython#68693]
BPO | [24505](https://bugs.python.org/issue24505)
--- | :---
Nosy | @pfmoore, @tjguk, @bitdancer, @zware, @SpecLad, @eryksun, @zooba, @bharel
Files | <li>[which2.py](https://bugs.python.org/file39805/which2.py "Uploaded as text/plain at 2015-06-24.22:09:39 by bobjalex"): A sample of 'which' function corrected</li><li>[issue 24505 proposed patch windows cmd semantics.patch](https://bugs.python.org/file41338/issue%2024505%20proposed%20patch%20windows%20cmd%20semantics.patch "Uploaded as text/plain at 2015-12-17.19:47:32 by tobytobkin"): Proposed patch following cmd.exe semantics</li><li>[issue-24505-proposed-patch-2.patch](https://bugs.python.org/file41459/issue-24505-proposed-patch-2.patch "Uploaded as text/plain at 2015-12-31.05:42:34 by tobytobkin")</li><li>[new_which_bug_files.zip](https://bugs.python.org/file42365/new_which_bug_files.zip "Uploaded as application/x-zip-compressed at 2016-04-04.16:48:42 by bobjalex"): ZIP file with suggested file updates</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-06-24.22:09:39.162>
labels = ['type-bug', '3.8', '3.9', '3.10', 'library', 'OS-windows']
title = 'shutil.which wrong result on Windows'
updated_at = <Date 2021-03-20.14:30:08.693>
user = 'https://bugs.python.org/bobjalex'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-20.14:30:08.693>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2015-06-24.22:09:39.162>
creator = 'bobjalex'
dependencies = []
files = ['39805', '41338', '41459', '42365']
hgrepos = []
issue_num = 24505
keywords = ['patch']
message_count = 20.0
messages = ['245780', '245792', '245885', '245887', '252329', '252341', '252355', '252358', '252359', '252367', '256242', '256373', '256613', '257248', '258413', '258415', '262854', '262875', '348640', '389137']
nosy_count = 10.0
nosy_names = ['paul.moore', 'tim.golden', 'r.david.murray', 'zach.ware', 'SpecLad', 'eryksun', 'steve.dower', 'bobjalex', 'bar.harel', 'tobytobkin']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24505'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by eryksun** [comment]
This issue was resolved by #103179.
