### ISSUE TITLE
the f_lineno getter is broken

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#68753]
BPO | [24565](https://bugs.python.org/issue24565)
--- | :---
Nosy | @abalkin, @blueyed, @xdegaye, @serhiy-storchaka
PRs | <li>python/cpython#6233</li><li>python/cpython#12419</li>
Files | <li>[f_lineno.patch](https://bugs.python.org/file39865/f_lineno.patch "Uploaded as text/plain at 2015-07-04.20:36:37 by @xdegaye")</li><li>[f_lineno_tests.patch](https://bugs.python.org/file39866/f_lineno_tests.patch "Uploaded as text/plain at 2015-07-04.20:37:06 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-07-04.20:36:38.056>
labels = ['interpreter-core', '3.8', 'type-bug', '3.7', '3.9']
title = 'the f_lineno getter is broken'
updated_at = <Date 2019-12-05.11:21:41.373>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-05.11:21:41.373>
actor = 'blueyed'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-07-04.20:36:38.056>
creator = 'xdegaye'
dependencies = []
files = ['39865', '39866']
hgrepos = []
issue_num = 24565
keywords = ['patch']
message_count = 8.0
messages = ['246275', '246276', '314237', '314243', '314409', '314410', '339667', '357845']
nosy_count = 4.0
nosy_names = ['belopolsky', 'blueyed', 'xdegaye', 'serhiy.storchaka']
pr_nums = ['6233', '12419']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24565'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by gaogaotiantian** [comment]
It's been a while and the mechanisms were changed a lot in the past couple of versions. There's no usage of `frame->f_trace` in `PyFrame_GetLineNumber` anymore. The example given above also worked correctly for main. Close this for now, if someone found a repro, feel free to reopen this.
