### ISSUE TITLE
Subclass of property doesn't preserve instance __doc__ when using doc= argument

### ISSUE THREAD

**Issue by embray** [python/cpython#68954]
BPO | [24766](https://bugs.python.org/issue24766)
--- | :---
Nosy | @bitdancer, @Bluehorn, @ethanfurman, @embray, @berkerpeksag, @iritkatriel
PRs | <li>python/cpython#2487</li>
Files | <li>[property-doc.patch](https://bugs.python.org/file40086/property-doc.patch "Uploaded as text/plain at 2015-07-31.17:02:02 by @embray"): Initial proposed patch</li><li>[property-doc-test.patch](https://bugs.python.org/file40181/property-doc-test.patch "Uploaded as text/plain at 2015-08-14.19:27:00 by @embray")</li><li>[property-doc-test2.patch](https://bugs.python.org/file40504/property-doc-test2.patch "Uploaded as text/plain at 2015-09-18.14:27:11 by @embray")</li><li>[issue24766.diff](https://bugs.python.org/file42683/issue24766.diff "Uploaded as text/plain at 2016-05-02.12:39:25 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-07-31.17:02:03.577>
labels = ['interpreter-core', 'type-bug', '3.11']
title = "Subclass of property doesn't preserve instance __doc__ when using doc= argument"
updated_at = <Date 2021-10-21.15:30:13.977>
user = 'https://github.com/embray'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-21.15:30:13.977>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-07-31.17:02:03.577>
creator = 'erik.bray'
dependencies = []
files = ['40086', '40181', '40504', '42683']
hgrepos = []
issue_num = 24766
keywords = ['patch']
message_count = 12.0
messages = ['247756', '247758', '248604', '248606', '250937', '250990', '250994', '250997', '251006', '264642', '264646', '404608']
nosy_count = 6.0
nosy_names = ['r.david.murray', 'torsten', 'ethan.furman', 'erik.bray', 'berker.peksag', 'iritkatriel']
pr_nums = ['2487']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue24766'
versions = ['Python 3.11']
```

</p></details>

**Comment by embray** [comment]
@serhiy-storchaka thanks for helping get this done. I've been totally inactive in core Python development for some years now and forgot about this. Always fun to see some very minor bug reported 9 years ago fixed 🙃

**Comment by serhiy-storchaka** [comment]
You are welcome. I'm working on pushing old forgotten PRs.
