### ISSUE TITLE
Allow incremental I/O to blobs in sqlite3

### ISSUE THREAD

**Issue by 141584eb-3466-4a50-9de2-229f55877e5f** [python/cpython#69093]
BPO | [24905](https://bugs.python.org/issue24905)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @palaviv, @eamanu, @erlend-aasland, @nightlark
PRs | <li>python/cpython#271</li><li>python/cpython#30356</li><li>python/cpython#30680</li>
Files | <li>[blob.patch](https://bugs.python.org/file41798/blob.patch "Uploaded as text/plain at 2016-02-03.21:36:09 by @palaviv")</li><li>[blob2.patch](https://bugs.python.org/file44142/blob2.patch "Uploaded as text/plain at 2016-08-18.18:17:53 by @palaviv")</li><li>[blob3.patch](https://bugs.python.org/file46531/blob3.patch "Uploaded as text/plain at 2017-02-05.22:20:17 by @palaviv")</li><li>[blob4.patch](https://bugs.python.org/file46549/blob4.patch "Uploaded as text/plain at 2017-02-06.18:16:34 by @palaviv")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-08-21.08:05:21.911>
labels = ['extension-modules', 'type-feature', '3.8']
title = 'Allow incremental I/O to blobs in sqlite3'
updated_at = <Date 2022-01-20.12:42:10.486>
user = 'https://bugs.python.org/jimminter'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-20.12:42:10.486>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2015-08-21.08:05:21.911>
creator = 'jim_minter'
dependencies = []
files = ['41798', '44142', '46531', '46549']
hgrepos = []
issue_num = 24905
keywords = ['patch']
message_count = 28.0
messages = ['248945', '259262', '259520', '272873', '272883', '273052', '286957', '287040', '287065', '287081', '287162', '288515', '288517', '288519', '288724', '288725', '297205', '315450', '329457', '372225', '399813', '409494', '409580', '409584', '409591', '409592', '410920', '411021']
nosy_count = 9.0
nosy_names = ['ghaering', 'berker.peksag', 'serhiy.storchaka', 'jim_minter', 'waldhol', 'palaviv', 'eamanu', 'erlendaasland', 'rmast']
pr_nums = ['271', '30356', '30680']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue24905'
versions = ['Python 3.8']
```

</p></details>

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
I opened a PR in github. I tagged some other developers if that will not start a discussion on the API I will post in the python-ideas.

**Comment by serhiy-storchaka** [comment]
Is there similar API in other databases?

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
I am not a DB expert but from a quick search I couldn't find a similar API. I did find a few API's in other programming languages to sqlite blob:
1. https://jgallagher.github.io/rusqlite/rusqlite/blob/index.html
2. https://godoc.org/github.com/mxk/go-sqlite/sqlite3
3. http://www.ch-werner.de/javasqlite/SQLite/Blob.html

It seems like most of them give the same API as apsw.

**Comment by serhiy-storchaka** [comment]
Small discussion is started at pull request [1]. There are doubts about the usefulness of incremental I/O API. SQLite is rarely used for storing blobs of the size of hundreds of megabytes. For smaller blobs it may be enough to read or write all data at once. There are also questions about the support of len(), since other file-like objects don't support len().

This discussion remembered me about mmap objects. mmap objects implement two protocols: file protocol and sequence protocol (including the support of len()). The BLOB object looks similar to the mmap object. sqlite3_blob_write() may only modify the contents of the BLOB; it is not possible to increase the size of a BLOB using this API. Maybe implement the sequence protocol in the BLOB object? Or implement only the sequence protocol and drop away the file protocol?

[1] https://github.com/python/cpython/pull/271

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
Just to make sure when you say "sequence protocol" you thin about the doing blob[4:6] = "ab"?

I actually think this is a nice feature. The Blob and the mmap object has a lot in common so I think that making the same API will be best. I think that adding the sequence protocol in addition to the file protocol is best.

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
Pinging. As I mentioned in the PR I need a little help with \_\_contains__.

**Comment by JelleZijlstra** [comment]
@erlend-aasland can we close this issue with #30680 merged, or do you want to keep it for further API enhancements for blobs?

**Comment by erlend-aasland** [comment]
> @erlend-aasland can we close this issue with #30680 merged, or do you want to keep it for further API enhancements for blobs?

Let's keep it open until we've got context manager and mapping support in place.

**Comment by erlend-aasland** [comment]
Incremental I/O for blobs is now supported in the sqlite3 extension module in the upcoming Python 3.11 release. Thanks a lot to @palaviv, @JelleZijlstra, and everyone else who contributed by commenting and reviewing.

IMO, the implementation can benefit from further tweaks, but let's do that in separate issues if needed.

**Comment by erlend-aasland** [comment]
cc. @eamanu, @nightlark
