### ISSUE TITLE
Add a test which uses the ast module to compile the stdlib

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#69169]
BPO | [24981](https://bugs.python.org/issue24981)
--- | :---
Nosy | @brettcannon, @rhettinger, @terryjreedy, @1st1, @iritkatriel
Files | <li>[temast.py](https://bugs.python.org/file40359/temast.py "Uploaded as text/plain at 2015-09-04.19:54:14 by @terryjreedy")</li><li>[tem_ast2.py](https://bugs.python.org/file40360/tem_ast2.py "Uploaded as text/plain at 2015-09-04.21:58:22 by @terryjreedy")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-09-01.20:49:15.728>
labels = ['tests']
title = 'Add a test which uses the ast module to compile the stdlib'
updated_at = <Date 2021-08-31.20:12:25.571>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-31.20:12:25.571>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2015-09-01.20:49:15.728>
creator = 'brett.cannon'
dependencies = []
files = ['40359', '40360']
hgrepos = []
issue_num = 24981
keywords = []
message_count = 8.0
messages = ['249516', '249526', '249817', '249818', '249819', '249826', '249839', '400775']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'rhettinger', 'terry.reedy', 'yselivanov', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue24981'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
Closing as out of date because test_stdlib_validates does this.
