### ISSUE TITLE
Allow passing "delete=False" to TemporaryDirectory

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#69212]
BPO | [25024](https://bugs.python.org/issue25024)
--- | :---
Nosy | @birkenfeld, @ncoghlan, @pitrou, @bitdancer, @serhiy-storchaka, @maurorodrigues, @asottile, @epicfaace, @CAM-Gerlach, @Septatrix, @nyuszika7h, @beliaev-maksim
PRs | <li>python/cpython#24793</li>
Files | <li>[TemporaryDirectory_delete_false.patch](https://bugs.python.org/file40694/TemporaryDirectory_delete_false.patch "Uploaded as text/plain at 2015-10-06.04:39:21 by @maurorodrigues")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-03-26.19:32:11.879>
created_at = <Date 2015-09-08.05:36:20.331>
labels = ['type-feature', 'library']
title = 'Allow passing "delete=False" to TemporaryDirectory'
updated_at = <Date 2021-11-02.10:35:39.100>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-02.10:35:39.100>
actor = 'beliaev-maksim'
assignee = 'none'
closed = True
closed_date = <Date 2020-03-26.19:32:11.879>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2015-09-08.05:36:20.331>
creator = 'Antony.Lee'
dependencies = []
files = ['40694']
hgrepos = []
issue_num = 25024
keywords = ['patch']
message_count = 22.0
messages = ['250158', '250217', '250386', '250387', '252375', '364345', '364453', '364458', '364461', '364466', '364468', '365103', '365105', '365106', '365107', '365108', '365109', '382595', '387785', '388220', '394462', '405499']
nosy_count = 12.0
nosy_names = ['georg.brandl', 'ncoghlan', 'pitrou', 'r.david.murray', 'serhiy.storchaka', 'maurosr', 'Anthony Sottile', 'epicfaace', 'CAM-Gerlach', 'Nils Kattenbeck', 'nyuszika7h', 'beliaev-maksim']
pr_nums = ['24793']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25024'
versions = ['Python 3.6']
```

</p></details>

**Comment by CAM-Gerlach** [comment]
Changing the close reason to reflect the previous reality; I also note that this was brought up again in #100131 with a corresponding PR, which FWIW I'm now supportive of. Perhaps
