### ISSUE TITLE
Fix fcntl module to accept 'unsigned long' type commands for ioctl(2).

### ISSUE THREAD

**Issue by koobs** [python/cpython#69214]
BPO | [25026](https://bugs.python.org/issue25026)
--- | :---
Nosy | @larryhastings, @ceronman, @vadmium, @serhiy-storchaka, @koobs, @corona10

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-09-08.06:35:17.934>
labels = ['interpreter-core', 'easy', 'type-bug']
title = "(FreeBSD/OSX) Fix fcntl module to accept 'unsigned long' type commands for ioctl(2)."
updated_at = <Date 2019-08-25.10:01:51.693>
user = 'https://github.com/koobs'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-25.10:01:51.693>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-09-08.06:35:17.934>
creator = 'koobs'
dependencies = []
files = []
hgrepos = []
issue_num = 25026
keywords = ['easy']
message_count = 10.0
messages = ['250163', '250164', '250166', '250170', '250173', '250174', '250178', '250322', '296062', '350447']
nosy_count = 6.0
nosy_names = ['larry', 'ceronman', 'martin.panter', 'serhiy.storchaka', 'koobs', 'corona10']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25026'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

### Linked PRs
* gh-119498
* gh-119504
* gh-119505
* gh-119905
* gh-119906

**Comment by vadmium** [comment]
Maybe bpo-16124 is related; it mentions 64-bit values, but it sounds like an obscure use case.

**Comment by emaste** [comment]
bpo-16124 is https://github.com/python/cpython/issues/60328

> The question is: are ioctl codes outside of the unsigned int range used on BSD family or Mac OS X?

I don't have an authoritative answer for other BSDs or OS X, but for FreeBSD they are not. In addition, we have hidden the warning under a diagnostic option in https://github.com/freebsd/freebsd-src/commit/a90fb6cf3cb05ef3b60cb35007cd9c42b2ce3b39

**Comment by vstinner** [comment]
> The question is: are ioctl codes outside of the unsigned int range used on BSD family or Mac OS X?

Linux manual page of ioctl clearly uses the `unsigned long` type for the *request* parameter: https://man7.org/linux/man-pages/man2/ioctl.2.html

```
       int ioctl(int fd, unsigned long request, ...);
```

Python should use the right type. I wrote PR gh-119498 to fix the *request* parameter of `fcntl.ioctl()`.

**Comment by vstinner** [comment]
* FreeBSD uses `unsigned long request`: https://man.freebsd.org/cgi/man.cgi?ioctl
* macOS uses `unsigned long request`: https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man2/ioctl.2.html
* Solaris uses `int request`: https://docs.oracle.com/cd/E23824_01/html/821-1463/ioctl-2.html
* POSIX uses `int request`: https://pubs.opengroup.org/onlinepubs/009695399/functions/ioctl.html

Linux, FreeBSD, macOS uses `unsigned long`. IMO we should take care of these platforms. Solaris is not supported by Python (PEP 11).

**Comment by vstinner** [comment]
This change broke test_ioctl on macOS: https://github.com/python/cpython/issues/119770

So I created two PRs to revert the change in 3.12 and 3.13 branches.

**Comment by Eclips4** [comment]
Thank you Victor for your work!

**Comment by vstinner** [comment]
I went through FreeBSD issues recently and decided to fix this 9 years old issue.
