### ISSUE TITLE
test_uuid fails with pywin32 installed

### ISSUE THREAD

**Issue by zware** [python/cpython#69285]
BPO | [25098](https://bugs.python.org/issue25098)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-09-14.04:23:54.980>
labels = ['type-bug', 'library', 'OS-windows']
title = 'test_uuid fails with pywin32 installed'
updated_at = <Date 2017-09-28.15:21:44.103>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-28.15:21:44.103>
actor = 'zach.ware'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2015-09-14.04:23:54.980>
creator = 'zach.ware'
dependencies = []
files = []
hgrepos = []
issue_num = 25098
keywords = []
message_count = 4.0
messages = ['250612', '250634', '303237', '303256']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25098'
versions = ['Python 3.4']
```

</p></details>

**Comment by vstinner** [comment]
Zachary: any update on this issue? Is it still a bug?

**Comment by zware** [comment]
Still fails on Python 3.6.1 with pypiwin32-220; those are the versions I have handy to check on.  I've not managed to report it to pywin32 or look into it any deeper, though.  If someone can confirm that it's definitely their bug, this can be closed as third-party.

**Comment by zware** [comment]
This apparently hasn't bothered anyone in several years, so I'm just going to go ahead and close it.
