### ISSUE TITLE
Confusing (?) warning when run deprecated module as script

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#69391]
BPO | [25204](https://bugs.python.org/issue25204)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @ericsnowcurrently, @serhiy-storchaka
Files | <li>[warnings_surface.patch](https://bugs.python.org/file40536/warnings_surface.patch "Uploaded as text/plain at 2015-09-21.18:22:00 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-09-21.18:22:00.832>
labels = ['extension-modules', 'library']
title = 'Confusing (?) warning when run deprecated module as script'
updated_at = <Date 2015-09-21.18:42:02.582>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2015-09-21.18:42:02.582>
actor = 'Arfrever'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Library (Lib)']
creation = <Date 2015-09-21.18:22:00.832>
creator = 'serhiy.storchaka'
dependencies = []
files = ['40536']
hgrepos = []
issue_num = 25204
keywords = ['patch']
message_count = 1.0
messages = ['251247']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'Arfrever', 'eric.snow', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue25204'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
I think it should have just been `stacklevel=1` when at module level.

**Comment by brettcannon** [comment]
I think it's fine since the stack level is designed to trigger on the import statement. Since `imp` didn't have an `__main__` semantics (that I can remember), I don't think this is worth changing at this point (especially with imp removed in 3.12).
