### ISSUE TITLE
Enhancing the argparse help output

### ISSUE THREAD

**Issue by 917acfef-b076-4032-9ba6-f271eefe6fc3** [python/cpython#69494]
BPO | [25307](https://bugs.python.org/issue25307)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-10-03.20:58:03.409>
labels = ['type-feature', 'library']
title = 'Enhancing the argparse help output'
updated_at = <Date 2015-10-09.18:40:15.479>
user = 'https://bugs.python.org/Sworddragon'
```

bugs.python.org fields:
```python
activity = <Date 2015-10-09.18:40:15.479>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-10-03.20:58:03.409>
creator = 'Sworddragon'
dependencies = []
files = []
hgrepos = []
issue_num = 25307
keywords = []
message_count = 5.0
messages = ['252239', '252243', '252244', '252246', '252250']
nosy_count = 3.0
nosy_names = ['bethard', 'Sworddragon', 'paul.j3']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25307'
versions = ['Python 3.6']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
More compact invocation is produced in the current code:
```
usage: [-h] [-t] [--test2] [-u {choice1,choice2} [{choice1,choice2} ...]]

options:
  -h, --help            show this help message and exit
  -t, --test1           Description1
  --test2               Description2
  -u, --test3 {choice1,choice2} [{choice1,choice2} ...]
                        Description3
```
This solved a half of this issue.

As for lining up short and long option strings, this is a too niche feature. I do not recall other program which does this. On other hand, additional indentation for `--test2` could look like a continuation of the previous line, like a wrapped out long option list `-t, --test1, --test2` (there are no comma after `--test1`, but this may go unnoticed). So I think that this is not good for default behavior and do not deserve a special option. But you can implement this yourself as a Formatter subclass, as was said above.
