### ISSUE TITLE
telnetlib: process_rawq() and binary data

### ISSUE THREAD

**Issue by 758e61a0-ba49-467a-9ddd-9b08a9f167c8** [python/cpython#69521]
BPO | [25334](https://bugs.python.org/issue25334)
--- | :---
Nosy | @terryjreedy, @bitdancer
Files | <li>[telnetlib.diff](https://bugs.python.org/file40710/telnetlib.diff "Uploaded as text/plain at 2015-10-07.13:17:10 by mwalle")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-10-07.13:17:10.875>
labels = ['type-feature', 'library']
title = 'telnetlib: process_rawq() and binary data'
updated_at = <Date 2015-10-09.19:07:47.689>
user = 'https://bugs.python.org/mwalle'
```

bugs.python.org fields:
```python
activity = <Date 2015-10-09.19:07:47.689>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-10-07.13:17:10.875>
creator = 'mwalle'
dependencies = []
files = ['40710']
hgrepos = []
issue_num = 25334
keywords = ['patch']
message_count = 2.0
messages = ['252472', '252636']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'r.david.murray', 'mwalle']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25334'
versions = ['Python 3.6']
```

</p></details>

**Comment by hugovk** [comment]
Note the telnetlib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AA-Turner** [comment]
Closing per Hugo's comment.

A
