### ISSUE TITLE
Add type checks to urllib.request.Request

### ISSUE THREAD

**Issue by ezio-melotti** [python/cpython#69625]
BPO | [25439](https://bugs.python.org/issue25439)
--- | :---
Nosy | @ezio-melotti, @vadmium, @CuriousLearner
PRs | <li>python/cpython#10616</li>
Files | <li>[urllib_request_param_type_check.patch](https://bugs.python.org/file40819/urllib_request_param_type_check.patch "Uploaded as text/plain at 2015-10-20.16:27:38 by Nan Wu")</li><li>[urllib_request_param_type_check_2.patch](https://bugs.python.org/file40830/urllib_request_param_type_check_2.patch "Uploaded as text/plain at 2015-10-20.22:44:18 by Nan Wu")</li><li>[urllib_request_param_type_check_3.patch](https://bugs.python.org/file40850/urllib_request_param_type_check_3.patch "Uploaded as text/plain at 2015-10-23.16:50:38 by Nan Wu")</li><li>[urllib_request_param_type_check_4.patch](https://bugs.python.org/file40912/urllib_request_param_type_check_4.patch "Uploaded as text/plain at 2015-10-31.19:01:15 by Nan Wu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/CuriousLearner'
closed_at = None
created_at = <Date 2015-10-19.09:31:23.861>
labels = ['3.7', '3.8', 'type-feature', 'library', 'easy']
title = 'Add type checks to urllib.request.Request'
updated_at = <Date 2018-11-21.11:51:33.180>
user = 'https://github.com/ezio-melotti'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-21.11:51:33.180>
actor = 'CuriousLearner'
assignee = 'CuriousLearner'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-10-19.09:31:23.861>
creator = 'ezio.melotti'
dependencies = []
files = ['40819', '40830', '40850', '40912']
hgrepos = []
issue_num = 25439
keywords = ['patch', 'easy']
message_count = 16.0
messages = ['253173', '253175', '253176', '253231', '253252', '253267', '253519', '253585', '253586', '253587', '253802', '253814', '253815', '257266', '330136', '330192']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'martin.panter', 'Nan Wu', 'CuriousLearner']
pr_nums = ['10616']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25439'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by encukou** [comment]
The PR went unreviewed for years. Sorry for that.

As I said on the PR: I think the issue made much more sense when it was opened, Python 3 was new and mixing up str and bytes was much more common than today. Also, we now have generic tools to detect type errors early -- static type checkers.
I think that today, it's best to close without action.
