### ISSUE TITLE
sys.exit() caught in async event loop exception handler

### ISSUE THREAD

**Issue by be3361d6-08f5-4239-bc8c-ef6e1846e3fe** [python/cpython#69675]
BPO | [25489](https://bugs.python.org/issue25489)
--- | :---
Nosy | @gvanrossum, @bitdancer, @asvetlov, @1st1, @iritkatriel
Files | <li>[test_sys_exit_in_exception_handler.py](https://bugs.python.org/file40867/test_sys_exit_in_exception_handler.py "Uploaded as text/plain at 2015-10-27.11:25:55 by jinty"): Test Case</li><li>[future.patch](https://bugs.python.org/file40869/future.patch "Uploaded as text/plain at 2015-10-27.16:05:21 by @1st1")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-10-27.11:25:55.941>
labels = ['expert-asyncio']
title = 'sys.exit() caught in async event loop exception handler'
updated_at = <Date 2022-03-22.13:11:35.019>
user = 'https://bugs.python.org/jinty'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.13:11:35.019>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2015-10-27.11:25:55.941>
creator = 'jinty'
dependencies = []
files = ['40867', '40869']
hgrepos = []
issue_num = 25489
keywords = ['patch']
message_count = 27.0
messages = ['253529', '253540', '253543', '253544', '253549', '253552', '253554', '253555', '253556', '253557', '253558', '253576', '253594', '253601', '253603', '253686', '253723', '253746', '415599', '415618', '415619', '415620', '415621', '415622', '415737', '415738', '415742']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'r.david.murray', 'asvetlov', 'yselivanov', 'jinty', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue25489'
versions = ['Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
The simplest solution is to just let the loop call the exception handler with `call_soon` rather than calling it manually.

**Comment by gvanrossum** [comment]
Isn't that (b)? @asvetlov didn't seem to think that would work (see his message above).

**Comment by kumaraditya303** [comment]
No, I propose to call exception handler with `call_soon` rather than (b) which is about rescheduling the raised error with `call_soon`.

**Comment by gvanrossum** [comment]
Okay, but I don't know how we can assess that your solution will be an improvement *in real-world code* and not cause further issues. Maybe we should carefully analyze the consequences once you have a draft PR up.

**Comment by kumaraditya303** [comment]
@gvanrossum: Try the following patch:
```diff
diff --git a/Lib/asyncio/futures.py b/Lib/asyncio/futures.py
index 4bd9629e9eb..973f61451d7 100644
--- a/Lib/asyncio/futures.py
+++ b/Lib/asyncio/futures.py
@@ -103,7 +103,7 @@ def __del__(self):
         }
         if self._source_traceback:
             context['source_traceback'] = self._source_traceback
-        self._loop.call_exception_handler(context)
+        self._loop.call_soon(lambda: self._loop.call_exception_handler(context))
 
     __class_getitem__ = classmethod(GenericAlias)
 

```

Script:
```py
import sys
sys.modules['_asyncio'] = None
import asyncio

def handler(loop, context):
    print('Got error, exiting')
    sys.exit(42)

async def boom():
    await asyncio.sleep(1)
    raise Exception('boom')

loop = asyncio.get_event_loop()

# Schedule a call to hello_world()
loop.set_exception_handler(handler)
loop.create_task(boom())
loop.run_forever()
```

**Comment by gvanrossum** [comment]
The lambda isn't even needed, you can write
```py
        self._loop.call_soon(self._loop.call_exception_handler, context)
```

**Comment by gvanrossum** [comment]
But the more I think about this the less I like it. There are quite a few `__del__` methods in asyncio, and most of then call `warnings.warn`, which may raise an exception -- which is then ignored. Many also call `self.close()`, which in many cases can also raise.

I think the OP's best workaround is, as they said, `os._exit(42)`. Second-best would seem to be `loop.call_soon(sys.exit, 42)`.

So I would like to close as "not planned".

@jinty Do you have any further comments, 7 years later?

**Comment by jinty** [comment]
@gvanrossum I have long since moved on with a workaround, so don't have any skin in the game anymore.

But for my original usecase of writing a piece of crash-only software, os._exit() would have likely been a better implementation. I still think it's surprising that my example testcase didn't work, but fixing it is sounds like it's not worth complexity or risk of unintended consequences.

**Comment by gvanrossum** [comment]
Thanks — there is always complexity somewhere, I think it’s a reasonable balance now. Closing.
