### ISSUE TITLE
Attempt to further increase test coverage of calendar module

### ISSUE THREAD

**Issue by 05fcf7b2-de89-43f3-a37d-afc37af82fa0** [python/cpython#69714]
BPO | [25528](https://bugs.python.org/issue25528)
--- | :---
Nosy | @rhettinger, @vadmium, @serhiy-storchaka, @matrixise, @iritkatriel
Files | <li>[mywork.patch](https://bugs.python.org/file40916/mywork.patch "Uploaded as text/plain at 2015-11-01.09:57:43 by Rohit Mediratta"): Patch to increase coverage for 3 additional lines</li><li>[mywork_update.patch](https://bugs.python.org/file41109/mywork_update.patch "Uploaded as text/plain at 2015-11-21.08:59:10 by Rohit Mediratta"): Updated patch showing the correct diff</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-11-01.09:57:43.791>
labels = ['type-feature', 'tests']
title = 'Attempt to further increase test coverage of calendar module'
updated_at = <Date 2022-03-22.21:27:14.499>
user = 'https://bugs.python.org/RohitMediratta'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.21:27:14.499>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2015-11-01.09:57:43.791>
creator = 'Rohit Mediratta'
dependencies = []
files = ['40916', '41109']
hgrepos = []
issue_num = 25528
keywords = ['patch']
message_count = 7.0
messages = ['253836', '254421', '255047', '255416', '255417', '255423', '415815']
nosy_count = 6.0
nosy_names = ['rhettinger', 'martin.panter', 'serhiy.storchaka', 'matrixise', 'Rohit Mediratta', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25528'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-93655

**Comment by AA-Turner** [comment]
This hasn't been converted into a PR, if someone would like to we can re-open this issue in the future.

A

**Comment by AA-Turner** [comment]
Reopening as a new PR has appeared (#93655).

A

**Comment by terryjreedy** [comment]
@bxsx Please leave the issue number off the commit message for all PR branch commits after the first.  It spams the issue with unneeded info that is also on the PR itself.
