### ISSUE TITLE
ctypes+callbacks+fork+selinux = crash

### ISSUE THREAD

**Issue by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [python/cpython#69839]
BPO | [25653](https://bugs.python.org/issue25653)
--- | :---
Nosy | @arigo, @vstinner, @tiran, @encukou, @eryksun
Files | <li>[x.py](https://bugs.python.org/file44353/x.py "Uploaded as text/plain at 2016-09-03.07:44:42 by @arigo")</li><li>[y.py](https://bugs.python.org/file50134/y.py "Uploaded as text/plain at 2021-06-30.08:32:42 by @encukou")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-11-18.06:03:04.279>
labels = ['3.10', 'ctypes', '3.8', '3.9', 'type-crash']
title = 'ctypes+callbacks+fork+selinux = crash'
updated_at = <Date 2021-09-29.20:44:13.579>
user = 'https://github.com/arigo'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-29.20:44:13.579>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2015-11-18.06:03:04.279>
creator = 'arigo'
dependencies = []
files = ['44353', '50134']
hgrepos = []
issue_num = 25653
keywords = []
message_count = 6.0
messages = ['254831', '274288', '274290', '274304', '396773', '402907']
nosy_count = 5.0
nosy_names = ['arigo', 'vstinner', 'christian.heimes', 'petr.viktorin', 'eryksun']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue25653'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
With current main, I can't reproduce. The downstream issues are closed, and Fedora doesn't carry a patch for this.
I don't know if there's still work to do in libffi, but, it does look like there's nothing more to do in CPython.
