### ISSUE TITLE
asyncio.Server class documented but not exported

### ISSUE THREAD

**Issue by 05fb81a7-2c51-4b5c-8fc9-c47d3b5b5933** [python/cpython#69935]
BPO | [25749](https://bugs.python.org/issue25749)
--- | :---
Nosy | @gvanrossum, @vstinner, @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/asvetlov'
closed_at = None
created_at = <Date 2015-11-27.19:28:36.651>
labels = ['3.8', 'type-bug', '3.7', 'expert-asyncio']
title = 'asyncio.Server class documented but not exported'
updated_at = <Date 2017-12-21.12:38:39.835>
user = 'https://bugs.python.org/RonFrederick'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-21.12:38:39.835>
actor = 'Ron Frederick'
assignee = 'asvetlov'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2015-11-27.19:28:36.651>
creator = 'Ron Frederick'
dependencies = []
files = []
hgrepos = []
issue_num = 25749
keywords = []
message_count = 14.0
messages = ['255476', '255477', '255497', '255502', '255505', '308827', '308840', '308841', '308843', '308845', '308848', '308849', '308850', '308868']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'vstinner', 'asvetlov', 'yselivanov', 'Ron Frederick']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25749'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
On main branch this issue is fixed:

```py
>>> import asyncio
>>> 'Server' in asyncio.__all__
True
```

**Comment by gvanrossum** [comment]
There was also mention of adding AbstractServer to the docs. Did this ever happen?

**Comment by kumaraditya303** [comment]
No, AbstractServer is not documented as it is  earlier in this thread is pointed that AbstractServer is too abstract to be usable by third party applications as it does not provide access to connected sockets and once a abstract class is documented changing it is backwards incompatible change. I plan on working on a proposal to fix the AbstractServer and document it but it is outside of this issue so closed this issue as the initial issue of "Server" not exported is fixed.

**Comment by gvanrossum** [comment]
Thanks for the update. The plan sounds good!
