### ISSUE TITLE
CPython hangs on error __context__ set to the error itself

### ISSUE THREAD

**Issue by 1st1** [python/cpython#69968]
BPO | [25782](https://bugs.python.org/issue25782)
--- | :---
Nosy | @birkenfeld, @terryjreedy, @ncoghlan, @cjerdonek, @ambv, @serhiy-storchaka, @1st1, @corona10, @miss-islington, @sweeneyde, @sobolevn, @iritkatriel
PRs | <li>python/cpython#20543</li><li>python/cpython#20539</li><li>python/cpython#27626</li><li>python/cpython#27706</li><li>python/cpython#27707</li>
Files | <li>[Issue25782.patch](https://bugs.python.org/file41212/Issue25782.patch "Uploaded as text/plain at 2015-12-02.18:32:16 by @1st1")</li><li>[Issue25782_2.patch](https://bugs.python.org/file41214/Issue25782_2.patch "Uploaded as text/plain at 2015-12-02.19:41:55 by @1st1")</li><li>[Issue25782_3.patch](https://bugs.python.org/file41219/Issue25782_3.patch "Uploaded as text/plain at 2015-12-02.22:01:08 by @1st1")</li><li>[Issue25782_4.patch](https://bugs.python.org/file41341/Issue25782_4.patch "Uploaded as text/plain at 2015-12-17.22:58:06 by @1st1")</li><li>[set_context_reordering.patch](https://bugs.python.org/file41354/set_context_reordering.patch "Uploaded as text/plain at 2015-12-18.16:04:18 by @serhiy-storchaka")</li><li>[set_context_reordering2.patch](https://bugs.python.org/file43380/set_context_reordering2.patch "Uploaded as text/plain at 2016-06-13.20:34:00 by @serhiy-storchaka")</li><li>[Issue25782_5.patch](https://bugs.python.org/file43381/Issue25782_5.patch "Uploaded as text/plain at 2016-06-13.20:36:27 by @serhiy-storchaka")</li><li>[issue27122_broken_cm.py](https://bugs.python.org/file43382/issue27122_broken_cm.py "Uploaded as text/plain at 2016-06-13.23:03:56 by @ncoghlan"): Explicit reproducer for python/issues-test-cpython#27122</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2015-12-02.17:14:01.351>
labels = ['interpreter-core', 'type-bug', '3.9', '3.10', '3.11']
title = 'CPython hangs on error __context__ set to the error itself'
updated_at = <Date 2021-08-11.12:41:10.037>
user = 'https://github.com/1st1'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-11.12:41:10.037>
actor = 'corona10'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2015-12-02.17:14:01.351>
creator = 'yselivanov'
dependencies = []
files = ['41212', '41214', '41219', '41341', '41354', '43380', '43381', '43382']
hgrepos = []
issue_num = 25782
keywords = ['patch']
message_count = 71.0
messages = ['255731', '255739', '255740', '255744', '255747', '255752', '255753', '255754', '255758', '255759', '255760', '255766', '255767', '255768', '255770', '255771', '255772', '255773', '255775', '255776', '255780', '255781', '255788', '255995', '256618', '256644', '256681', '256687', '256688', '268309', '268310', '268465', '268467', '268472', '268473', '268485', '268509', '268563', '268565', '268567', '268578', '283459', '291825', '291826', '291828', '314242', '314430', '370401', '370404', '370420', '391637', '399080', '399091', '399092', '399093', '399094', '399099', '399100', '399218', '399219', '399220', '399227', '399228', '399230', '399243', '399281', '399310', '399314', '399325', '399332', '399387']
nosy_count = 16.0
nosy_names = ['georg.brandl', 'terry.reedy', 'ncoghlan', 'chris.jerdonek', 'lukasz.langa', 'Yury.Selivanov', 'python-dev', 'serhiy.storchaka', 'yselivanov', 'Rotem Yaari', 'larsonreever', 'corona10', 'miss-islington', 'Dennis Sweeney', 'sobolevn', 'iritkatriel']
pr_nums = ['20543', '20539', '27626', '27706', '27707']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25782'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by 76e893be-1ec8-4707-a969-4cbdc46bfb28** [comment]
My patch works for your example too.  Since it checks for loops in \_\_context__ setter, you shouldn't be able to create complicated loops. However, since PyException_SetContext and PyException_SetCause are public APIs, and their return type is 'void', I can't raise an error when a C code introduces a cycle, in that case, the exc-\>cause/exc-\>context will be set to NULL.(I came to this bug via the ExitStack + subprocess bpo-27122 which merely has a suggested workaround patch as a band aid that might help until this is fixed) 
Thanks: http://driverwhiz.com/device-drivers

**Comment by larryhastings** [comment]
Why is this still open?  GPS: didn't your checkin last June fix this?

**Comment by serhiy-storchaka** [comment]
Because we have two alternate solutions, issue25782_5.patch and set_context_reordering2.patch.

**Comment by iritkatriel** [comment]
> Serhiy, I'm not closing this yet in case you'd like to finish implementing your PR. If not, feel free to close.

I don't think we should do try to prevent cycles from being created. That means traversing the whole cause and context tree every time we add a new link in the chain, which is quadratic overall. We should only try to detect cycles when we have another reason to traverse the tree.
