### ISSUE TITLE
Make Profile.print_stats support sorting by mutiple values

### ISSUE THREAD

**Issue by 6fefdbba-0358-497b-8b75-41887f04f2ba** [python/cpython#69990]
BPO | [25804](https://bugs.python.org/issue25804)
--- | :---
Nosy | @birkenfeld, @JelleZijlstra, @DanielNoord
Files | <li>[print_stats.patch](https://bugs.python.org/file41247/print_stats.patch "Uploaded as text/plain at 2015-12-05.08:25:51 by wdv4758h"): enhance print_stats</li><li>[print_stats_with_test.patch](https://bugs.python.org/file41249/print_stats_with_test.patch "Uploaded as text/plain at 2015-12-05.13:24:31 by wdv4758h"): refactor patch & add tests</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-12-05.08:25:52.232>
labels = ['type-feature', 'library']
title = 'Make Profile.print_stats support sorting by mutiple values'
updated_at = <Date 2022-03-16.08:34:17.207>
user = 'https://bugs.python.org/wdv4758h'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-16.08:34:17.207>
actor = 'danielnoord'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-12-05.08:25:52.232>
creator = 'wdv4758h'
dependencies = []
files = ['41247', '41249']
hgrepos = []
issue_num = 25804
keywords = ['patch']
message_count = 5.0
messages = ['255935', '255940', '255952', '267273', '415329']
nosy_count = 5.0
nosy_names = ['georg.brandl', 'SilentGhost', 'wdv4758h', 'JelleZijlstra', 'danielnoord']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue25804'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-104590

**Comment by furkanonder** [comment]
The [PR](https://github.com/python/cpython/pull/104590) ready for review.
