### ISSUE TITLE
Mixing multiprocessing pool and subprocess may create zombie process, and cause program to hang.

### ISSUE THREAD

**Issue by 9c921203-1a53-4d2d-bca1-173f9227143f** [python/cpython#70015]
BPO | [25829](https://bugs.python.org/issue25829)
--- | :---
Nosy | @gpshead, @bitdancer, @applio
Files | <li>[hang_multiprocess_subprocess.py](https://bugs.python.org/file41275/hang_multiprocess_subprocess.py "Uploaded as text/plain at 2015-12-09.10:04:32 by amikoren@yahoo.com"): reducted script to demonstrate the hang</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-12-09.10:04:34.164>
labels = ['extension-modules', 'type-bug']
title = 'Mixing multiprocessing pool and subprocess may create zombie process, and cause program to hang.'
updated_at = <Date 2016-03-29.06:30:49.767>
user = 'https://bugs.python.org/amikorenyahoocom'
```

bugs.python.org fields:
```python
activity = <Date 2016-03-29.06:30:49.767>
actor = 'rpcope1'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2015-12-09.10:04:34.164>
creator = 'amikoren@yahoo.com'
dependencies = []
files = ['41275']
hgrepos = []
issue_num = 25829
keywords = []
message_count = 6.0
messages = ['256150', '256156', '256157', '256168', '256175', '256264']
nosy_count = 6.0
nosy_names = ['gregory.p.smith', 'r.david.murray', 'sbt', 'davin', 'amikoren@yahoo.com', 'rpcope1']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25829'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by gpshead** [comment]
We recommend people use the multiprocessing `forkserver` or `spawn` start methods instead of `fork` to avoid issues related to threads.  regardless, there have been many other little subprocess file descriptor handling related issue cleanups since this was filed.  I cannot reproduce it locally after letting the reproducer code run for a few minutes, i'm just going to close this.
