### ISSUE TITLE
code_context not available in exec()

### ISSUE THREAD

**Issue by 025c240f-c8f8-44fa-8f75-029c49b9dbbb** [python/cpython#70140]
BPO | [25952](https://bugs.python.org/issue25952)
--- | :---
Nosy | @1st1, @tirkarthi, @iritkatriel
Files | <li>[issue.py](https://bugs.python.org/file41421/issue.py "Uploaded as text/plain at 2015-12-25.16:14:47 by Grzegorz Krasoń"): demonstration</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2015-12-25.16:14:47.411>
labels = ['type-bug', 'library', '3.11']
title = 'code_context not available in exec()'
updated_at = <Date 2021-12-01.22:46:38.922>
user = 'https://bugs.python.org/GrzegorzKraso'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-01.22:46:38.922>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2015-12-25.16:14:47.411>
creator = 'Grzegorz Kraso\xc5\x84'
dependencies = []
files = ['41421']
hgrepos = []
issue_num = 25952
keywords = []
message_count = 2.0
messages = ['256998', '407501']
nosy_count = 4.0
nosy_names = ['yselivanov', 'Grzegorz Kraso\xc5\x84', 'xtreak', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue25952'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
It's different now in head - if you change your code to look at

`s[2].code_context `

you get 

`["exec('foo()')\n"]`


This is probably as good as it can get with exec. We are running a string in the current scope, and I don't think it's possible to associate a source file to whatever that string will end up parsing to.
