### ISSUE TITLE
Class __dict__ iteration order changing due to type instance key-sharing

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#70248]
BPO | [26060](https://bugs.python.org/issue26060)
--- | :---
Nosy | @warsaw, @rhettinger, @amauryfa, @ncoghlan, @benjaminp, @markshannon, @serhiy-storchaka, @1st1, @Vgr255
Files | <li>[ns_reordering_bug.py](https://bugs.python.org/file41550/ns_reordering_bug.py "Uploaded as text/plain at 2016-01-09.12:56:10 by @ncoghlan"): Reproducer used for hg bisect</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-01-09.12:56:11.844>
labels = []
title = 'Class __dict__ iteration order changing due to type instance key-sharing'
updated_at = <Date 2020-09-11.23:13:21.183>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-11.23:13:21.183>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2016-01-09.12:56:11.844>
creator = 'ncoghlan'
dependencies = []
files = ['41550']
hgrepos = []
issue_num = 26060
keywords = []
message_count = 4.0
messages = ['257824', '258107', '258112', '258113']
nosy_count = 12.0
nosy_names = ['barry', 'rhettinger', 'beazley', 'amaury.forgeotdarc', 'ncoghlan', 'benjamin.peterson', 'ionelmc', 'Mark.Shannon', 'pingebretson', 'serhiy.storchaka', 'yselivanov', 'abarry']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue26060'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
I'm unable to reproduce this on main. Does this bug still exist?

**Comment by markshannon** [comment]
Not since 3.6 or 3.7, when dicts became ordered.
