### ISSUE TITLE
pdb fails to access variables closed over

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#70260]
BPO | [26072](https://bugs.python.org/issue26072)
--- | :---
Nosy | @birkenfeld, @xdegaye, @devjoe
Files | <li>[default.patch](https://bugs.python.org/file45115/default.patch "Uploaded as text/plain at 2016-10-16.09:55:21 by @devjoe"): show proper information when Pdb fails to create a closure</li><li>[free_variables.patch](https://bugs.python.org/file45509/free_variables.patch "Uploaded as text/plain at 2016-11-16.20:37:32 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-01-10.05:16:24.039>
labels = ['3.7', 'type-bug', 'library']
title = 'pdb fails to access variables closed over'
updated_at = <Date 2016-11-22.11:54:13.971>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2016-11-22.11:54:13.971>
actor = 'Chun-Yu Tseng'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-01-10.05:16:24.039>
creator = 'Antony.Lee'
dependencies = []
files = ['45115', '45509']
hgrepos = []
issue_num = 26072
keywords = ['patch']
message_count = 10.0
messages = ['257888', '277181', '277578', '278761', '280912', '280930', '280933', '280988', '281016', '281469']
nosy_count = 4.0
nosy_names = ['georg.brandl', 'xdegaye', 'Jes\xc3\xbas G\xc3\xb3mez', 'Chun-Yu Tseng']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue26072'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by gaogaotiantian** [comment]
Fixed by #111094
