### ISSUE TITLE
Garbage collection of unused input sections from CPython binaries

### ISSUE THREAD

**Issue by ae6878ec-d873-4297-8b64-d05d471e780d** [python/cpython#70473]
BPO | [26285](https://bugs.python.org/issue26285)
--- | :---
Nosy | @malemburg, @gpshead, @pitrou, @scoder, @vstinner, @benjaminp, @skrah, @vadmium, @zware, @serhiy-storchaka, @1st1, @zooba
Files | <li>[cpython2-deadcode-v01.patch](https://bugs.python.org/file41805/cpython2-deadcode-v01.patch "Uploaded as text/plain at 2016-02-04.15:56:27 by alecsandru.patrascu")</li><li>[cpython3-deadcode-v01.patch](https://bugs.python.org/file41806/cpython3-deadcode-v01.patch "Uploaded as text/plain at 2016-02-04.15:56:38 by alecsandru.patrascu")</li><li>[gc-removed-cpython2.txt](https://bugs.python.org/file41808/gc-removed-cpython2.txt "Uploaded as text/plain at 2016-02-04.21:30:45 by alecsandru.patrascu")</li><li>[gc-removed-cpython3.txt](https://bugs.python.org/file41809/gc-removed-cpython3.txt "Uploaded as text/plain at 2016-02-04.21:30:51 by alecsandru.patrascu")</li><li>[c_ext3.zip](https://bugs.python.org/file41819/c_ext3.zip "Uploaded as application/octet-stream at 2016-02-05.12:50:48 by alecsandru.patrascu")</li><li>[gc-removed-zones-cpython3.txt](https://bugs.python.org/file41851/gc-removed-zones-cpython3.txt "Uploaded as text/plain at 2016-02-08.13:48:17 by alecsandru.patrascu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-02-04.15:56:28.787>
labels = ['build', 'performance']
title = 'Garbage collection of unused input sections from CPython binaries'
updated_at = <Date 2020-11-04.21:39:41.524>
user = 'https://bugs.python.org/alecsandrupatrascu'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-04.21:39:41.524>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2016-02-04.15:56:28.787>
creator = 'alecsandru.patrascu'
dependencies = []
files = ['41805', '41806', '41808', '41809', '41819', '41851']
hgrepos = []
issue_num = 26285
keywords = ['patch']
message_count = 11.0
messages = ['259572', '259576', '259581', '259593', '259594', '259596', '259597', '259598', '259657', '259768', '259844']
nosy_count = 13.0
nosy_names = ['lemburg', 'gregory.p.smith', 'pitrou', 'scoder', 'vstinner', 'benjamin.peterson', 'skrah', 'martin.panter', 'zach.ware', 'serhiy.storchaka', 'yselivanov', 'steve.dower', 'alecsandru.patrascu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue26285'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
This issue has been idle for 6 years. I will close it unless someone indicates that they are interested in continuing to investigate this suggestion.

**Comment by vstinner** [comment]
It looked like a good idea, but removing functions which are part of the public C API (like PyMem_RawMalloc()) is just wrong and cannot be done. I don't think that the change is correct. I close the issue.
