### ISSUE TITLE
Solaris 10 build issues

### ISSUE THREAD

**Issue by 36c7f256-1862-4f36-9b09-72f307def08f** [python/cpython#70496]
BPO | [26308](https://bugs.python.org/issue26308)
--- | :---
Nosy | @jcea, @gsauthof
Files | <li>[python-3.5.1-solaris10.diff](https://bugs.python.org/file41852/python-3.5.1-solaris10.diff "Uploaded as text/plain at 2016-02-08.15:06:58 by @gsauthof")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-02-08.15:07:00.160>
labels = ['build']
title = 'Solaris 10 build issues'
updated_at = <Date 2016-02-11.04:55:47.719>
user = 'https://github.com/gsauthof'
```

bugs.python.org fields:
```python
activity = <Date 2016-02-11.04:55:47.719>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2016-02-08.15:07:00.160>
creator = 'gms'
dependencies = []
files = ['41852']
hgrepos = []
issue_num = 26308
keywords = ['patch']
message_count = 1.0
messages = ['259852']
nosy_count = 2.0
nosy_names = ['jcea', 'gms']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue26308'
versions = ['Python 3.5']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.5 is not supported. If this issue exists on supported python version, create a new issue. Also note that Solaris is not a supported platform as per PEP 11.
