### ISSUE TITLE
_scproxy and Python Launcher fail to build wtih GNU gcc on macOS 10.13+

### ISSUE THREAD

**Issue by 3f2a6b76-88c7-476a-81b5-48e84e633beb** [python/cpython#70505]
BPO | [26317](https://bugs.python.org/issue26317)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @vstinner, @ned-deily, @corona10, @websurfer5
PRs | <li>python/cpython#13306</li><li>python/cpython#19681</li><li>python/cpython#20176</li><li>python/cpython#20177</li><li>python/cpython#20182</li>
Files | <li>[log](https://bugs.python.org/file41865/log "Uploaded as text/plain at 2016-02-09.04:35:33 by Robert P Fischer"): Log file from attempt to build Python</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2016-02-09.04:36:24.611>
labels = ['OS-mac', 'build', '3.9']
title = '_scproxy and Python Launcher fail to build wtih GNU gcc on macOS 10.13+'
updated_at = <Date 2020-05-19.08:11:12.595>
user = 'https://bugs.python.org/RobertPFischer'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-19.08:11:12.595>
actor = 'Arfrever'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Build', 'macOS']
creation = <Date 2016-02-09.04:36:24.611>
creator = 'Robert P Fischer'
dependencies = []
files = ['41865']
hgrepos = []
issue_num = 26317
keywords = ['patch']
message_count = 27.0
messages = ['259914', '259927', '259929', '260113', '260162', '260194', '260195', '260215', '331768', '342037', '342055', '342081', '342139', '342179', '342432', '359893', '359894', '359922', '359923', '369213', '369218', '369224', '369227', '369246', '369247', '369248', '369325']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'vstinner', 'ned.deily', 'Arfrever', 'python-dev', 'Robert P Fischer', 'corona10', 'Jeffrey.Kintscher']
pr_nums = ['13306', '19681', '20176', '20177', '20182']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue26317'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
Is this still a valid issue? @corona10?

**Comment by ned-deily** [comment]
The original PR to add separate OBJC config variables was reverted due to the buildbot failures and was never reapplied. So I expect it is still an issue for those who want to try to build Python on macOS with gcc. It's not something we recommend and is perhaps of even less importance with the introduction of Apple Silicon Macs and their build dependencies on the Apple compiler tool chain. I don't have any immediate plans to pursue it so I'm deassigning myself if someone else wants jump in.

**Comment by ned-deily** [comment]
Also, the PR would need to be updated to deal with the subsequent changes to Modules/Setup et al to allow building of _scproxy without Distutils.

**Comment by erlend-aasland** [comment]
I'm marking it as pending (close). If Dong-hee or anyone else want to pursue this, feel free to remove the label and pick up the loose ends.

**Comment by erlend-aasland** [comment]
No-one has jumped in here. Closing this; feel free to reopen if you disagree.

**Comment by barracuda156** [comment]
@erlend-aasland @ned-deily It would be nice to have it re-opened. The problem still exists.
