### ISSUE TITLE
Crash calling sqlite3_close with invalid pointer

### ISSUE THREAD

**Issue by e4fea311-21d6-4694-aa94-63f0cb055dca** [python/cpython#70575]
BPO | [26387](https://bugs.python.org/issue26387)
--- | :---
Nosy | @serhiy-storchaka, @erlend-aasland
Files | <li>[sqlite_connection.c.patch](https://bugs.python.org/file41958/sqlite_connection.c.patch "Uploaded as text/plain at 2016-02-18.17:59:33 by scorp"): Bugfix patch</li><li>[sqlite_connection.c.patch](https://bugs.python.org/file41970/sqlite_connection.c.patch "Uploaded as text/plain at 2016-02-19.10:54:24 by scorp"): Next patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = None
created_at = <Date 2016-02-18.17:59:33.753>
labels = ['extension-modules', 'library', 'type-crash']
title = 'Crash calling sqlite3_close with invalid pointer'
updated_at = <Date 2021-10-18.11:42:47.338>
user = 'https://bugs.python.org/scorp'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-18.11:42:47.338>
actor = 'erlendaasland'
assignee = 'serhiy.storchaka'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Library (Lib)']
creation = <Date 2016-02-18.17:59:33.753>
creator = 'scorp'
dependencies = []
files = ['41958', '41970']
hgrepos = []
issue_num = 26387
keywords = ['patch']
message_count = 9.0
messages = ['260472', '260516', '260663', '261359', '261363', '261367', '261411', '404177', '404178']
nosy_count = 4.0
nosy_names = ['ghaering', 'serhiy.storchaka', 'scorp', 'erlendaasland']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue26387'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by erlend-aasland** [comment]
There has been no reproducer -- suggesting to close this and marking it as invalid.
