### ISSUE TITLE
RLock undocumented behavior in case of multiple acquire

### ISSUE THREAD

**Issue by e9f94252-e58c-475a-b35e-962b2e021864** [python/cpython#70795]
BPO | [26608](https://bugs.python.org/issue26608)
--- | :---
Nosy | @MojoVampire, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-03-22.06:56:38.096>
labels = ['easy', '3.11', 'library', 'docs']
title = 'RLock undocumented behavior in case of multiple acquire'
updated_at = <Date 2021-06-18.14:35:22.245>
user = 'https://bugs.python.org/smbrd'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-18.14:35:22.245>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2016-03-22.06:56:38.096>
creator = 'smbrd'
dependencies = []
files = []
hgrepos = ['348']
issue_num = 26608
keywords = ['easy']
message_count = 4.0
messages = ['262165', '262231', '270216', '396068']
nosy_count = 5.0
nosy_names = ['docs@python', 'josh.r', 'ahxxm', 'smbrd', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue26608'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-103853
* gh-119436
* gh-119437

**Comment by samatjain** [comment]
Working on this at PyCon 2023's cpython sprint.

**Comment by samatjain** [comment]
Notes while trying to update the documentation:

> First acquisition returns boolean and further acquisitions return 1. This is also not mentioned in documentation.

This longer seems to be true; acquire appears to always return `True` or `False`. Also, the documentation has a statement:

> If more than one thread is blocked waiting until the lock is unlocked, only one at a time will be able to grab ownership of the lock. There is no return value in this case.

I have no idea what this means; why would it not return True or False? Confirmed w/ @gpshead it doesn't make sense. It's able to acquire the lock or not!

Here's a test program I have been fiddling with:

```python
import operator
import time
import threading

LEVEL_LIMIT: int = 10
THREADS_MAX = 16

global_rlock = threading.RLock()


def recursively_lock(level: int):
    """Test for RLock. Recusively call itself and observe the return value of acquire/release."""

    tid = threading.get_ident()

    if level == LEVEL_LIMIT:
        print(f"{LEVEL_LIMIT=} reached, stopping recursion")
        return

    print(f"Started {tid=}")

    rv = global_rlock.acquire(blocking=False)
    if rv:
        print(f"RLock acquire()={rv} at {level=} for {tid=}")
        time.sleep(0.1)

        recursively_lock(level + 1)

        rv = global_rlock.release()
        print(f"RLock release()={rv} at {level=}")
    else:
        print(f"Unable to acquire lock for {tid=} {rv=}")


if __name__ == "__main__":
    threads: list[threading.Thread] = []
    for i in range(0, THREADS_MAX):
        threads.append(threading.Thread(target=recursively_lock, args=(0,)))

    for t in threads:
        t.start()
    # map(operator.methodcaller("start"), threads)

    map(operator.methodcaller("join"), threads)
    print("Hello world")

```

I've been unable to replicate the case where None is returned, or acquire not returning True or False.

**Comment by samatjain** [comment]
The old docs mention that `acquire` returns `None`, this seems not the case looking at `rlock_acquire`'s implementation https://github.com/python/cpython/blob/main/Modules/_threadmodule.c#L355

Double checked by gpshead
