### ISSUE TITLE
Deprecate register_adapter() and register_converter() in sqlite3

### ISSUE THREAD

**Issue by berkerpeksag** [python/cpython#70838]
BPO | [26651](https://bugs.python.org/issue26651)
--- | :---
Nosy | @malemburg, @rhettinger, @ethanfurman, @berkerpeksag, @erlend-aasland, @iafisher, @Strongbeard
Files | <li>[deprecate_adapters.diff](https://bugs.python.org/file42309/deprecate_adapters.diff "Uploaded as text/plain at 2016-03-27.16:57:44 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-03-27.16:57:46.141>
labels = ['extension-modules', 'type-feature', '3.11']
title = 'Deprecate register_adapter() and register_converter() in sqlite3'
updated_at = <Date 2021-11-21.18:46:22.084>
user = 'https://github.com/berkerpeksag'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-21.18:46:22.084>
actor = 'ethan.furman'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2016-03-27.16:57:46.141>
creator = 'berker.peksag'
dependencies = []
files = ['42309']
hgrepos = []
issue_num = 26651
keywords = ['patch']
message_count = 5.0
messages = ['262525', '262561', '403356', '403385', '406729']
nosy_count = 8.0
nosy_names = ['lemburg', 'rhettinger', 'ghaering', 'ethan.furman', 'berker.peksag', 'erlendaasland', 'iafisher', 'Strongbeard']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue26651'
versions = ['Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
Based on this discussion and [the discussion over at Discourse](https://discuss.python.org/t/deprecate-default-built-in-sqlite3-converters-and-adapters/15781?u=erlendaasland), I suggest closing this issue as "wont-implement".

**Comment by erlend-aasland** [comment]
Closing this in favour of gh-90016.
