### ISSUE TITLE
multiprocessing sentinel resource leak

### ISSUE THREAD

**Issue by 72a2cdf7-c1a0-4d2b-a11e-83e6b89ef3f6** [python/cpython#70919]
BPO | [26732](https://bugs.python.org/issue26732)
--- | :---
Nosy | @pitrou, @vstinner, @applio
PRs | <li>python/cpython#2813</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-10.21:58:21.521>
labels = ['3.7', 'library', 'performance']
title = 'multiprocessing sentinel resource leak'
updated_at = <Date 2017-07-31.00:12:15.278>
user = 'https://bugs.python.org/quick-b'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-31.00:12:15.278>
actor = 'quick-b'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-04-10.21:58:21.521>
creator = 'quick-b'
dependencies = []
files = []
hgrepos = []
issue_num = 26732
keywords = []
message_count = 13.0
messages = ['263153', '263154', '263282', '298844', '298846', '299051', '299052', '299157', '299174', '299418', '299419', '299424', '299531']
nosy_count = 8.0
nosy_names = ['holdenweb', 'pitrou', 'vstinner', 'jnoller', 'sbt', 'davin', 'Winterflower', 'quick-b']
pr_nums = ['2813']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue26732'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
This is expected with the "fork" method, but also happens with the "forkserver" method.

**Comment by pitrou** [comment]
New changeset 896145d9d266ee2758cfcd7691238cbc1f9e1ab8 by Antoine Pitrou in branch 'master':
bpo-26732: fix too many fds in processes started with the "forkserver" method (bpo-2813)
https://github.com/python/cpython/commit/896145d9d266ee2758cfcd7691238cbc1f9e1ab8

**Comment by vstinner** [comment]
The newly added test now hangs on almost all Windows buildbots, see:
http://bugs.python.org/issue31009#msg299050

**Comment by vstinner** [comment]
By the way, 3.6 is marked as affected, but the change wasn't backported to 3.6?

**Comment by 72a2cdf7-c1a0-4d2b-a11e-83e6b89ef3f6** [comment]
Thank you for the fix, pitrou!

Regarding your comment regarding the behavior being expected with the "fork" method, I would suggest a documentation modification in the description of the fork method to add something to the effect of "All resources of the parent are inherited by the child process; this includes the ability of later children to act as the parent of earlier children via the various functions in this package."

**Comment by vstinner** [comment]
Antoine: Do you want to backport your change 896145d9d266ee2758cfcd7691238cbc1f9e1ab8 to Python 3.6? If yes, don't forget to include my fix 302bbbe9ba5c72559913e2ea006c921f698a729d for Windows (bpo-31009).

If you prefer, I can handle the backport.

**Comment by pitrou** [comment]
Victor, you can try to backport the fix, it should be interesting, though I suspect you will run into conflicts :-)

**Comment by pitrou** [comment]
Kevin:

> Regarding your comment regarding the behavior being expected with the "fork" method, I would suggest a documentation modification in the description of the fork method to add something to the effect of "All resources of the parent are inherited by the child process; this includes the ability of later children to act as the parent of earlier children via the various functions in this package."

I would rather keep the latter part ("the ability of later children to act as the parent of earlier children via the various functions in this package") an implementation detail rather than a documented feature.  Who knows, perhaps some day we'll change the implementation so that those are not inherited anymore.

**Comment by holdenweb** [comment]
IIRC sockets can be marked as inheritable or not. It seems to me it would be a useful enhancement to allow the same determination for the pipes.

**Comment by 72a2cdf7-c1a0-4d2b-a11e-83e6b89ef3f6** [comment]
Hi Antoine,

> ... an implementation detail rather than a documented feature

I understand your desire, but this is a leaky abstraction and I would still suggest that it should be more clear that the fork method will inherit \*all* resources from the parent, including multiprocessing internal resources related to other processes.  This is potentially important if there are (a) large numbers of processes to be created and (b) for security aspects.

Regards,
  Kevin

**Comment by iritkatriel** [comment]
Backport to 3.6 is no longer relevant. Is there anything left to do here?
