### ISSUE TITLE
Mock(2.0.0).assert_has_calls() raise AssertionError in two same calls

### ISSUE THREAD

**Issue by cbf59f81-48a5-4c7d-8126-681c5e2f29d5** [python/cpython#70939]
BPO | [26752](https://bugs.python.org/issue26752)
--- | :---
Nosy | @rbtcollins, @cjw296, @voidspace, @mariocj89, @guboi72, @tirkarthi
Files | <li>[test.py](https://bugs.python.org/file42460/test.py "Uploaded as text/plain at 2016-04-14.07:43:23 by jekin000")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-14.07:43:24.290>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'Mock(2.0.0).assert_has_calls() raise AssertionError in two same calls'
updated_at = <Date 2019-08-01.06:00:38.882>
user = 'https://bugs.python.org/jekin000'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-01.06:00:38.882>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-04-14.07:43:24.290>
creator = 'jekin000'
dependencies = []
files = ['42460']
hgrepos = []
issue_num = 26752
keywords = []
message_count = 8.0
messages = ['263375', '287728', '288222', '306390', '336914', '337023', '337025', '348841']
nosy_count = 8.0
nosy_names = ['rbcollins', 'cjw296', 'michael.foord', 'jekin000', 'jwdevel', 'mariocj89', 'guboi72', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue26752'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 95082ff2-0fd4-4315-ab2a-25921ceb5487** [comment]
This also seems to apply to unittest.mock in Python3.4.

I described my similar issue on SO: http://stackoverflow.com/questions/42212433/what-is-wrong-with-this-simple-py-test-use-case

It seems like it may be the same issue described here.

For reference, this is my repro case:

```py
from unittest.mock import patch, call

    class Foo:
        def __init__(self):
            pass
        def my_method(self, value):
            pass
    
    def test_foo():
        with patch('test.Foo', autospec=True) as MockFoo:
            m = MockFoo()
            m.my_method(123)
            MockFoo.assert_has_calls([call(), call().my_method(123)])
```


It fails with:

    ...
    E               AssertionError: Calls not found.
    E               Expected: [call(), call().my_method(123)]
    E               Actual:   [call(), call().my_method(123)]

Which seems nonsensical to me.

Removing the `value` parameter and the `123` arguments in the test makes it pass(!)

**Comment by 95082ff2-0fd4-4315-ab2a-25921ceb5487** [comment]
This got a little discussion over at http://lists.idyll.org/pipermail/testing-in-python/2017-February/007012.html

The current evidence seem to indicate this is indeed a bug in the implementation of assert_has_calls.

**Comment by cc3b868c-5465-488c-b949-839b45f5fa83** [comment]
As pointed here: https://github.com/testing-cabal/mock/issues/353,

this issue is related to the method assert_has_calls or probably any calls that use the method _call_matcher to match calls. Given that you mock a class and spec it, since we always bind to the _spec_signature (e.g. the constructor signature), when it is a method call then it bind() throws a TypeError looking like `missing a require argument`. A possible solution would be to include method signatures into the spec.

**Comment by iritkatriel** [comment]
I can't reproduce this now. I think it was fixed in https://github.com/python/cpython/issues/81052.
