### ISSUE TITLE
Obmalloc lock LOCK_INIT and LOCK_FINI are never used

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#70940]
BPO | [26753](https://bugs.python.org/issue26753)
--- | :---
Nosy | @tim-one, @pitrou, @vstinner, @larryhastings
Files | <li>[larry.refresh.lock.macros.for.obmalloc.diff](https://bugs.python.org/file42479/larry.refresh.lock.macros.for.obmalloc.diff "Uploaded as text/plain at 2016-04-16.08:43:46 by @larryhastings")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2016-04-14.07:55:46.714>
labels = ['interpreter-core', 'type-bug']
title = 'Obmalloc lock LOCK_INIT and LOCK_FINI are never used'
updated_at = <Date 2016-04-16.08:43:49.225>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2016-04-16.08:43:49.225>
actor = 'larry'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-04-14.07:55:46.714>
creator = 'larry'
dependencies = []
files = ['42479']
hgrepos = []
issue_num = 26753
keywords = ['patch']
message_count = 6.0
messages = ['263377', '263381', '263382', '263441', '263541', '263542']
nosy_count = 4.0
nosy_names = ['tim.peters', 'pitrou', 'vstinner', 'larry']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue26753'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
These macros were removed by @benjaminp in https://github.com/python/cpython/pull/5805
