### ISSUE TITLE
Add truncated SHA512/224 and SHA512/256

### ISSUE THREAD

**Issue by tiran** [python/cpython#71021]
BPO | [26834](https://bugs.python.org/issue26834)
--- | :---
Nosy | @gpshead, @tiran, @vadmium, @nicktimko, @sir-sigurd
Files | <li>[cpython-cheimes-0001-Add-truncate-SHA512-224-and-SHA512-256-hash-algorith.patch](https://bugs.python.org/file42578/cpython-cheimes-0001-Add-truncate-SHA512-224-and-SHA512-256-hash-algorith.patch "Uploaded as text/plain at 2016-04-23.19:27:39 by @tiran")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-23.19:27:41.121>
labels = ['extension-modules', '3.11', 'type-feature', 'docs']
title = 'Add truncated SHA512/224 and SHA512/256'
updated_at = <Date 2021-10-21.13:11:03.824>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-21.13:11:03.824>
actor = 'christian.heimes'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Extension Modules']
creation = <Date 2016-04-23.19:27:41.121>
creator = 'christian.heimes'
dependencies = []
files = ['42578']
hgrepos = []
issue_num = 26834
keywords = ['patch']
message_count = 4.0
messages = ['264068', '266471', '316086', '404598']
nosy_count = 6.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'docs@python', 'martin.panter', 'nicktimko', 'sir-sigurd']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue26834'
versions = ['Python 3.11']
```

</p></details>

**Comment by gpshead** [comment]
if this feature is to be openssl only, people can already access these digests via `hashlib.new`.

The only reason to do more would be if we wanted to guarantee their availability by including them in `Modules/sha2module.c` and document them as always available.

I'm closing this as Not Planned. But please don't let that stop anyone from reopening it if they would like to see guaranteed availability with top level constructor function names.
