### ISSUE TITLE
setting SO_REUSEPORT fails at API 21

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#71045]
BPO | [26858](https://bugs.python.org/issue26858)
--- | :---
Nosy | @gvanrossum, @vstinner, @giampaolo, @pjenvey, @xdegaye, @Fak3, @1st1, @moreati, @yan12125
Dependencies | <li>bpo-27027: add the &#x27;is_android&#x27; attribute to test.support</li>
Files | <li>[test.asyncio.patch](https://bugs.python.org/file42610/test.asyncio.patch "Uploaded as text/plain at 2016-04-26.13:37:22 by @xdegaye")</li><li>[test.asyncio_2.patch](https://bugs.python.org/file42940/test.asyncio_2.patch "Uploaded as text/plain at 2016-05-22.08:24:56 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-26.13:37:22.784>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'setting SO_REUSEPORT fails at API 21'
updated_at = <Date 2017-12-10.14:24:43.827>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-10.14:24:43.827>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2016-04-26.13:37:22.784>
creator = 'xdegaye'
dependencies = ['27027']
files = ['42610', '42940']
hgrepos = []
issue_num = 26858
keywords = ['patch']
message_count = 22.0
messages = ['264281', '264602', '264605', '264635', '264653', '264662', '264666', '264690', '265928', '266061', '276615', '285392', '285394', '285402', '285406', '302351', '302357', '304704', '304708', '307947', '307950', '307960']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'vstinner', 'giampaolo.rodola', 'pjenvey', 'xdegaye', 'Roman.Evstifeev', 'yselivanov', 'Alex.Willmer', 'yan12125']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue26858'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by pjenvey** [comment]
Note that this isn't an android specific issue: See bpo-19901, and 9791c5d55f52 for an appropriate solution patch.

(Renaming title)

**Comment by gvanrossum** [comment]
Can't you just submit a PR? It's so easy now!

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Philip, 9791c5d55f52 was commited in november 2013 and bpo-19901 was closed in december 2013, so how can they be an appropriate solution for a problem reported on 2017-01-13 in [msg285392](https://bugs.python.org/msg285392) ?

**Comment by gvanrossum** [comment]
I assume he means that a similar piece of code should be inserted elsewhere. I am still waiting for Philip's PR though.

**Comment by kumaraditya303** [comment]
Closing as android is not supported, if you want to work on this, then create a new issue targeting main branch and the patch would have to be PRs.

**Comment by gvanrossum** [comment]
So are we now going to close all issues listed in https://github.com/python/cpython/issues/71052 as “Android not supported”? That seems backwards, since the (laudable) goal is to support Android.

**Comment by kumaraditya303** [comment]
> So are we now going to close all issues listed in https://github.com/python/cpython/issues/71052 as “Android not supported”? That seems backwards, since the (laudable) goal is to support Android.

No atleast I won't, I only close issue which have old patches and no comments in last 2~3 years and patch does not apply cleanly. I try patch before closing.

```console
error: patch failed: Lib/test/test_asyncio/test_base_events.py:1505
error: Lib/test/test_asyncio/test_base_events.py: patch does not apply
error: patch failed: Doc/library/asyncio-eventloop.rst:345
error: Doc/library/asyncio-eventloop.rst: patch does not apply
```

**Comment by kumaraditya303** [comment]
If anyone wants to port CPython to other platforms then IMO they should target main branch and land patches otherwise the old patches would conflicts and get out of date.

**Comment by gvanrossum** [comment]
Okay, just making clear what you're doing. That sounds like a reasonable process.

**Comment by pmp-p** [comment]
Closing dangling issues is really not a problem if at least a specifig tag ( aosp? ) is added to those, so people that may have time to work on can find them easy.
