### ISSUE TITLE
android: add platform.android_ver()

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#71042]
BPO | [26855](https://bugs.python.org/issue26855)
--- | :---
Nosy | @malemburg, @vstinner, @pmp-p, @Fak3, @moreati, @yan12125
Files | <li>[platform.patch](https://bugs.python.org/file42606/platform.patch "Uploaded as text/plain at 2016-04-26.13:18:31 by @xdegaye")</li><li>[android_ver.patch](https://bugs.python.org/file42721/android_ver.patch "Uploaded as text/plain at 2016-05-04.19:47:19 by @yan12125")</li><li>[android_ver.patch](https://bugs.python.org/file42723/android_ver.patch "Uploaded as text/plain at 2016-05-04.20:10:42 by @yan12125"): Patch version 2</li><li>[android_ver.patch](https://bugs.python.org/file42813/android_ver.patch "Uploaded as text/plain at 2016-05-11.11:57:53 by @yan12125"): Patch version 3</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-26.13:18:31.861>
labels = ['3.7', 'type-feature', 'library', 'build']
title = 'android: add platform.android_ver()'
updated_at = <Date 2019-12-10.08:09:38.614>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-10.08:09:38.614>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Cross-Build']
creation = <Date 2016-04-26.13:18:31.861>
creator = 'xdegaye'
dependencies = []
files = ['42606', '42721', '42723', '42813']
hgrepos = []
issue_num = 26855
keywords = ['patch']
message_count = 23.0
messages = ['264277', '264317', '264369', '264373', '264374', '264376', '264377', '264852', '264854', '264856', '265145', '265294', '265307', '267409', '267413', '267415', '280147', '280166', '307662', '307667', '307672', '307685', '308040']
nosy_count = 6.0
nosy_names = ['lemburg', 'vstinner', 'pmpp', 'Roman.Evstifeev', 'Alex.Willmer', 'yan12125']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue26855'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-116674

**Comment by mhsmith** [comment]
We're currently discussing PEP 738, which contains a different specification for `android_ver`. Please post any comments here:
* https://github.com/python/peps/pull/3651
