### ISSUE TITLE
Meta-issue: support of the android platform

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#71052]
BPO | [26865](https://bugs.python.org/issue26865)
--- | :---
Nosy | @ethanfurman, @xdegaye, @ericsnowcurrently, @Fak3, @zware, @moreati, @yan12125, @ethanhs
Dependencies | <li>bpo-16255: subrocess.Popen needs /bin/sh but Android only has /system/bin/sh</li><li>bpo-23968: rename the platform directory from plat-$(MACHDEP) to plat-$(PLATFORM_TRIPLET)</li><li>bpo-26849: android does not support versioning in SONAME</li><li>bpo-26851: android compilation and link flags</li><li>bpo-26853: missing symbols in curses and readline modules on android</li><li>bpo-26854: missing header on android for the ossaudiodev module</li><li>bpo-26855: android: add platform.android_ver()</li><li>bpo-26856: android does not have pwd.getpwall()</li><li>bpo-26857: gethostbyname_r() is broken on android</li><li>bpo-26858: setting SO_REUSEPORT fails at API 21</li><li>bpo-26862: android: SYS_getdents64 does not need to be defined on android API 21</li><li>bpo-26863: android lacks some declarations for the posix module</li><li>bpo-26884: android: cross-compilation of extension module links to the wrong python library</li><li>bpo-26918: android: test_pipes fails</li><li>bpo-26919: on Android python fails to decode/encode command line arguments</li><li>bpo-26920: android: test_sys fails</li><li>bpo-26924: android: test_concurrent_futures fails</li><li>bpo-26925: android: test_multiprocessing_main_handling fails</li><li>bpo-26926: test_io large file test failure on 32 bits Android platforms</li><li>bpo-26927: test_mmap does not handle ValueError when no large file support</li><li>bpo-26928: _bootlocale imports locale at startup on Android, causing test_site to fail</li><li>bpo-26929: android: test_strptime fails</li><li>bpo-26931: android: test_distutils fails</li><li>bpo-26932: RTLD_* macros are not defined on Android</li><li>bpo-26933: android: test_posixpath fails</li><li>bpo-26934: android: test_faulthandler fails</li><li>bpo-26935: android: test_os fails</li><li>bpo-26936: android: test_socket fails</li><li>bpo-26937: the chown() method of the tarfile.TarFile class fails on Android</li><li>bpo-26938: android: test_concurrent_futures hangs on armv7</li><li>bpo-26939: android: test_functools hangs on armv7</li><li>bpo-26940: android: test_importlib hangs on armv7</li><li>bpo-26941: android: test_threading hangs on armv7</li><li>bpo-26942: android: test_ctypes crashes on armv7 and aarch64</li><li>bpo-26944: test_posix: Android &#x27;id -G&#x27; is entirely wrong or missing the effective gid</li><li>bpo-27027: add the &#x27;is_android&#x27; attribute to test.support</li><li>bpo-27442: expose the Android API level in sysconfig.get_config_vars()</li><li>bpo-27472: add the &#x27;unix_shell&#x27; attribute to test.support</li><li>bpo-27606: Android cross-built for armv5te with clang and &#x27;-mthumb&#x27; crashes with SIGSEGV or SIGILL</li><li>bpo-27627: clang fails to build ctypes on Android armv7</li><li>bpo-27659: Prohibit implicit C function declarations</li><li>bpo-28180: Implementation of the PEP 538: coerce C locale to C.utf-8</li><li>bpo-28538: _socket module cross-compilation error on android-24</li><li>bpo-28562: test_asyncio fails on Android upon calling getaddrinfo()</li><li>bpo-28596: on Android _bootlocale on startup relies on too many library modules</li><li>bpo-28662: catch also PermissionError in tests when spawning a non existent program</li><li>bpo-28664: test_bz2 fails with BrokenPipeError when bunzip2 is missing</li><li>bpo-28668: instanciation of multiprocessing.Queue raises ImportError in test_logging</li><li>bpo-28683: bind() on a unix socket raises PermissionError on Android for a non-root user</li><li>bpo-28684: [asyncio] bind() on a unix socket raises PermissionError on Android for a non-root user</li><li>bpo-28740: Add sys.getandroidapilevel()</li><li>bpo-28746: cannot set_inheritable() for a file descriptor on Android</li><li>bpo-28759: access to mkfifo, mknod and hard links is controled by SELinux MAC on Android</li><li>bpo-28762: lockf() is available now on Android API level 24, but the F_LOCK macro is not defined</li><li>bpo-28764: test_mailbox fails when run as a non-root user on Android API 24</li><li>bpo-28996: wcscoll is broken on Android and test_locale fails</li><li>bpo-28997: test_readline.test_nonascii fails on Android</li><li>bpo-29040: building Android with android-ndk-r14</li><li>bpo-29176: /tmp does not exist on Android and is used by curses.window.putwin()</li><li>bpo-29177: skip tests of test_logging when bind() raises PermissionError (non-root user on Android)</li><li>bpo-29180: skip tests that raise PermissionError in test_os (non-root user on Android)</li><li>bpo-29181: skip tests that raise PermissionError in test_tarfile (non-root user on Android)</li><li>bpo-29184: skip tests of test_socketserver when bind() raises PermissionError (non-root user on Android)</li><li>bpo-29185: test_distutils fails on Android API level 24</li><li>bpo-32031: Do not use the canonical path in pydoc test_mixed_case_module_names_are_lower_cased</li><li>bpo-32059: detect_modules() in setup.py must also search the sysroot paths</li><li>bpo-32126: [asyncio] test failure when the platform lacks a functional  sem_open()</li><li>bpo-32138: android: test_faulthandler fails also on API 24</li><li>bpo-32139: android: locale is modified by test_strftime</li><li>bpo-32199: uuid.getnode() should return the MAC address on Android</li><li>bpo-32202: [ctypes] all long double tests fail on android-24-x86_64</li><li>bpo-32203: [ctypes] test_struct_by_value fails on android-24-arm64</li><li>bpo-32205: test.pythoninfo does not print the cross-built sysconfig data</li><li>bpo-32210: Add platform.android_ver()  to test.pythoninfo for Android platforms</li><li>bpo-32246: test_regrtest alters the execution environment on Android</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-26.15:36:51.967>
labels = ['type-feature', '3.7', 'build']
title = 'Meta-issue: support of the android platform'
updated_at = <Date 2017-12-10.09:31:57.501>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-10.09:31:57.501>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2016-04-26.15:36:51.967>
creator = 'xdegaye'
dependencies = ['16255', '23968', '26849', '26851', '26853', '26854', '26855', '26856', '26857', '26858', '26862', '26863', '26884', '26918', '26919', '26920', '26924', '26925', '26926', '26927', '26928', '26929', '26931', '26932', '26933', '26934', '26935', '26936', '26937', '26938', '26939', '26940', '26941', '26942', '26944', '27027', '27442', '27472', '27606', '27627', '27659', '28180', '28538', '28562', '28596', '28662', '28664', '28668', '28683', '28684', '28740', '28746', '28759', '28762', '28764', '28996', '28997', '29040', '29176', '29177', '29180', '29181', '29184', '29185', '32031', '32059', '32126', '32138', '32139', '32199', '32202', '32203', '32205', '32210', '32246']
files = []
hgrepos = []
issue_num = 26865
keywords = []
message_count = 41.0
messages = ['264310', '264485', '264746', '264791', '265610', '265963', '265988', '266075', '266085', '269236', '269296', '269718', '270045', '270942', '271148', '271389', '271516', '271522', '271547', '271567', '271568', '271571', '271731', '279496', '279733', '279983', '280653', '281209', '281367', '282661', '283113', '283477', '283780', '284743', '284757', '284854', '285493', '285772', '307901', '307902', '307948']
nosy_count = 8.0
nosy_names = ['ethan.furman', 'xdegaye', 'eric.snow', 'Roman.Evstifeev', 'zach.ware', 'Alex.Willmer', 'yan12125', 'ethan smith']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue26865'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-115576
* gh-115917
* gh-115918
* gh-115923
* gh-115955
* gh-116215
* gh-116379
* gh-116423
* gh-116426
* gh-116617
* gh-116618

**Comment by mhsmith** [comment]
I am now working on [PEP 738](https://peps.python.org/pep-0738/), which proposes adding Android as a Tier 3 supported platform for Python 3.13. I'll use this comment to track the issues related to this work.

FYI: @freakboy3742 @encukou @xdegaye 

The only remaining open issues from the Dependencies list above (last updated 2017-12-10) are:

* https://github.com/python/cpython/issues/71042
* https://github.com/python/cpython/issues/76391

Other open Android-related issues:

* https://github.com/python/cpython/issues/75824
* https://github.com/python/cpython/issues/83032
* https://github.com/python/cpython/issues/91028
* https://github.com/python/cpython/issues/111225

**Comment by vstinner** [comment]
> I am now working on [PEP 738](https://peps.python.org/pep-0738/), which proposes adding Android as a Tier 3 supported platform for Python 3.13. I'll use this comment to track the issues related to this work.

Would you mind to open a new issue? This one already has a long history, it may be hard to track the issue and history.

**Comment by mhsmith** [comment]
OK, I've opened #116622. @vstinner: Please close #71052 for me.

**Comment by erlend-aasland** [comment]
Superseded by #116622

**Comment by vstinner** [comment]
> OK, I've opened https://github.com/python/cpython/issues/116622.

Thank you!
