### ISSUE TITLE
Document PyModule_AddObject's behavior on error

### ISSUE THREAD

**Issue by berkerpeksag** [python/cpython#71055]
BPO | [26868](https://bugs.python.org/issue26868)
--- | :---
Nosy | @nirs, @berkerpeksag, @serhiy-storchaka, @matrixise, @animalize, @miss-islington, @brandtbucher
PRs | <li>python/cpython#15725</li><li>python/cpython#16037</li><li>python/cpython#16038</li>
Dependencies | <li>bpo-26871: Change weird behavior of PyModule_AddObject()</li>
Files | <li>[csv.diff](https://bugs.python.org/file42623/csv.diff "Uploaded as text/plain at 2016-04-27.05:36:44 by @berkerpeksag")</li><li>[addobject_doc.diff](https://bugs.python.org/file42630/addobject_doc.diff "Uploaded as text/plain at 2016-04-27.09:52:42 by @berkerpeksag")</li><li>[issue26868_v2.diff](https://bugs.python.org/file43328/issue26868_v2.diff "Uploaded as text/plain at 2016-06-10.05:37:39 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-04-27.05:36:44.758>
labels = ['extension-modules', '3.8', 'type-bug', '3.7']
title = "Document PyModule_AddObject's behavior on error"
updated_at = <Date 2019-09-12.12:29:12.788>
user = 'https://github.com/berkerpeksag'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-12.12:29:12.788>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2016-04-27.05:36:44.758>
creator = 'berker.peksag'
dependencies = ['26871']
files = ['42623', '42630', '43328']
hgrepos = []
issue_num = 26868
keywords = ['patch']
message_count = 12.0
messages = ['264350', '264358', '264367', '264375', '264388', '268088', '276977', '330940', '351260', '352135', '352140', '352141']
nosy_count = 7.0
nosy_names = ['nirs', 'berker.peksag', 'serhiy.storchaka', 'matrixise', 'malin', 'miss-islington', 'brandtbucher']
pr_nums = ['15725', '16037', '16038']
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue26868'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by hauntsaninja** [comment]
This has been documented, looks like https://github.com/python/cpython/issues/83004 is to track fixing the various call sites
