### ISSUE TITLE
The danger of PyType_FromSpec()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#71166]
BPO | [26979](https://bugs.python.org/issue26979)
--- | :---
Nosy | @loewis, @nascheme, @ncoghlan, @encukou, @serhiy-storchaka, @ctismer, @Dormouse759

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-05-08.18:24:38.790>
labels = ['type-security', '3.7', '3.8', 'docs']
title = 'The danger of PyType_FromSpec()'
updated_at = <Date 2018-10-26.14:37:17.269>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-26.14:37:17.269>
actor = 'Christian.Tismer'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-05-08.18:24:38.790>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 26979
keywords = []
message_count = 13.0
messages = ['265152', '318493', '325061', '325070', '325149', '325307', '325321', '325360', '325427', '325516', '325523', '325526', '328554']
nosy_count = 8.0
nosy_names = ['loewis', 'nascheme', 'ncoghlan', 'petr.viktorin', 'docs@python', 'serhiy.storchaka', 'Christian.Tismer', 'Dormouse759']
pr_nums = []
priority = 'high'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue26979'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
I close the issue.

> But since PyType_FromSpec() creates heap types, tp_new is inherited from the base 'object' class. Converted types unexpectedly becomes callable and pickleable.

Issued fixed by adding Py_TPFLAGS_DISALLOW_INSTANTIATION to Python 3.10.

> When a type is converted from a static type to a heaptype via PyType_FromSpec, and the tp_dealloc field is NULL, then subtype_dealloc is inserted.

Since Python 3.8, the dealloc function must now decrement a reference to its type: https://docs.python.org/dev/c-api/typeobj.html#c.PyTypeObject.tp_dealloc

Having a NULL tp_dealloc may be treated as an error.

---

@ctismer: Your feedback is very valuable. Please open issues for remaining issues which are not fixed in Python 3.13.
