### ISSUE TITLE
Mark up of references in different form

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#71223]
BPO | [27036](https://bugs.python.org/issue27036)
--- | :---
Nosy | @birkenfeld, @vadmium, @serhiy-storchaka
Files | <li>[refs_forms.patch](https://bugs.python.org/file42869/refs_forms.patch "Uploaded as text/plain at 2016-05-16.08:33:39 by @serhiy-storchaka")</li><li>[refs_forms2.patch](https://bugs.python.org/file42877/refs_forms2.patch "Uploaded as text/plain at 2016-05-16.20:34:35 by @serhiy-storchaka")</li><li>[refs_forms3.patch](https://bugs.python.org/file42890/refs_forms3.patch "Uploaded as text/plain at 2016-05-18.11:14:52 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-05-16.08:33:48.897>
labels = ['type-feature', 'docs']
title = 'Mark up of references in different form'
updated_at = <Date 2016-05-18.11:14:52.852>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2016-05-18.11:14:52.852>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-05-16.08:33:48.897>
creator = 'serhiy.storchaka'
dependencies = []
files = ['42869', '42877', '42890']
hgrepos = []
issue_num = 27036
keywords = ['patch']
message_count = 9.0
messages = ['265686', '265688', '265731', '265746', '265759', '265760', '265767', '265824', '265826']
nosy_count = 5.0
nosy_names = ['georg.brandl', 'docs@python', 'python-dev', 'martin.panter', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27036'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by slateny** [comment]
Would this be resolved?

**Comment by serhiy-storchaka** [comment]
Thank you for the reminder @slateny. It is resolved now.
