### ISSUE TITLE
tokenize.__all__ list is incomplete

### ISSUE THREAD

**Issue by 0f80442c-dac4-4ee5-9d1a-02e06b613d86** [python/cpython#71299]
BPO | [27112](https://bugs.python.org/issue27112)
--- | :---
Nosy | @vadmium, @serhiy-storchaka
Files | <li>[tokenize_all.patch](https://bugs.python.org/file42976/tokenize_all.patch "Uploaded as text/plain at 2016-05-24.20:56:34 by Unit03")</li><li>[tokenize_all.v2.patch](https://bugs.python.org/file44373/tokenize_all.v2.patch "Uploaded as text/plain at 2016-09-05.18:36:40 by Unit03")</li><li>[tokenize_all.v2.1.patch](https://bugs.python.org/file44374/tokenize_all.v2.1.patch "Uploaded as text/plain at 2016-09-05.18:36:54 by Unit03")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-05-24.20:56:35.561>
labels = ['type-feature', 'library']
title = 'tokenize.__all__ list is incomplete'
updated_at = <Date 2016-09-09.06:29:57.326>
user = 'https://bugs.python.org/Unit03'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-09.06:29:57.326>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-05-24.20:56:35.561>
creator = 'Unit03'
dependencies = []
files = ['42976', '44373', '44374']
hgrepos = []
issue_num = 27112
keywords = ['patch']
message_count = 9.0
messages = ['266275', '266304', '266309', '266312', '266340', '266390', '266579', '274418', '275268']
nosy_count = 3.0
nosy_names = ['martin.panter', 'serhiy.storchaka', 'Unit03']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27112'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-105907

**Comment by hauntsaninja** [comment]
Looks fixed by https://github.com/python/cpython/pull/105907, thanks everyone!
