### ISSUE TITLE
Add support for symlinks to zipfile

### ISSUE THREAD

**Issue by 53352fb6-19f0-49db-bc1c-39026b308ee0** [python/cpython#71505]
BPO | [27318](https://bugs.python.org/issue27318)
--- | :---
Nosy | @Yhg1s, @bochecha, @serhiy-storchaka, @eryksun, @henryiii, @ldoktor
Files | <li>[zipfile-symlink.patch](https://bugs.python.org/file43388/zipfile-symlink.patch "Uploaded as text/plain at 2016-06-14.11:55:33 by @ldoktor"): zipfile-symlink-v1</li><li>[zipfile-symlink.patch](https://bugs.python.org/file43399/zipfile-symlink.patch "Uploaded as text/plain at 2016-06-15.10:08:43 by @ldoktor"): zipfile-symlink-v2</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-06-14.11:55:34.124>
labels = ['type-feature', 'library', '3.10']
title = 'Add support for symlinks to zipfile'
updated_at = <Date 2022-01-19.16:59:26.727>
user = 'https://github.com/ldoktor'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-19.16:59:26.727>
actor = 'Henry Schreiner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-06-14.11:55:34.124>
creator = 'ldoktor'
dependencies = []
files = ['43388', '43399']
hgrepos = []
issue_num = 27318
keywords = ['patch']
message_count = 4.0
messages = ['268552', '268562', '268616', '295014']
nosy_count = 7.0
nosy_names = ['twouters', 'alanmcintyre', 'bochecha', 'serhiy.storchaka', 'eryksun', 'Henry Schreiner', 'ldoktor']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27318'
versions = ['Python 3.10']
```

</p></details>

**Comment by ae7a4afe-6203-48cc-8e47-9b86bac85915** [comment]
Do note that extracting a zipfile with symlinks might lead to unexpected results, for example if the path pointed to is outside of the extract dir.

Maybe the behaviour introduced in this patch should not be the default, but instead `extract` and `extractall` could take a new flag `preserve_symlinks` which would default to False? (to keep the same default as today)

**Comment by gpshead** [comment]
closing as a duplicate of https://github.com/python/cpython/issues/82102

**Comment by sysia48** [comment]
..
