### ISSUE TITLE
xml.sax.saxutils.escape doesn't escape multiple characters safely

### ISSUE THREAD

**Issue by 846f2249-b8db-4ea2-bfe4-b714cf763f15** [python/cpython#71616]
BPO | [27429](https://bugs.python.org/issue27429)
--- | :---
Nosy | @vadmium, @serhiy-storchaka, @zhangyangyu, @tylerjohnhughes
Files | <li>[escapetest.py](https://bugs.python.org/file43594/escapetest.py "Uploaded as text/plain at 2016-06-30.23:28:04 by @tylerjohnhughes"): Behavior Example</li><li>[issue27429.patch](https://bugs.python.org/file43616/issue27429.patch "Uploaded as text/plain at 2016-07-03.12:17:43 by @zhangyangyu")</li><li>[sax_escape_doc.patch](https://bugs.python.org/file43617/sax_escape_doc.patch "Uploaded as text/plain at 2016-07-03.14:17:00 by @zhangyangyu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-06-30.23:28:04.390>
labels = ['expert-XML', 'type-feature', 'docs']
title = "xml.sax.saxutils.escape doesn't escape multiple characters safely"
updated_at = <Date 2016-07-03.14:17:00.767>
user = 'https://github.com/tylerjohnhughes'
```

bugs.python.org fields:
```python
activity = <Date 2016-07-03.14:17:00.767>
actor = 'xiang.zhang'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'XML']
creation = <Date 2016-06-30.23:28:04.390>
creator = 'tylerjohnhughes'
dependencies = []
files = ['43594', '43616', '43617']
hgrepos = []
issue_num = 27429
keywords = ['patch']
message_count = 5.0
messages = ['269634', '269763', '269766', '269767', '269768']
nosy_count = 5.0
nosy_names = ['docs@python', 'martin.panter', 'serhiy.storchaka', 'xiang.zhang', 'tylerjohnhughes']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27429'
versions = ['Python 3.5']
```

</p></details>

**Comment by nanjekyejoannah** [comment]
Associated PR has been merged.
