### ISSUE TITLE
Integrate tkinter and asyncio (and async)

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#71733]
BPO | [27546](https://bugs.python.org/issue27546)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @serhiy-storchaka, @1st1, @maximesteisel, @tritium21, @gbtami
Files | <li>[tkselector.py](https://bugs.python.org/file43769/tkselector.py "Uploaded as text/plain at 2016-07-18.04:10:07 by @terryjreedy")</li><li>[tkloop.py](https://bugs.python.org/file43770/tkloop.py "Uploaded as text/plain at 2016-07-18.04:10:27 by @terryjreedy")</li><li>[tkaloop.py](https://bugs.python.org/file43802/tkaloop.py "Uploaded as text/plain at 2016-07-20.04:38:36 by @terryjreedy"): Update tk widget with async for and iterator</li><li>[loop_tk.py](https://bugs.python.org/file43826/loop_tk.py "Uploaded as text/plain at 2016-07-22.07:48:25 by @terryjreedy"): root.update in its own callback loop</li><li>[idle-async.diff](https://bugs.python.org/file43828/idle-async.diff "Uploaded as text/plain at 2016-07-22.08:26:12 by @terryjreedy"): run IDLE with asyncio loop and update callback</li><li>[loopspeed.py](https://bugs.python.org/file43849/loopspeed.py "Uploaded as text/plain at 2016-07-24.01:47:38 by @terryjreedy"): Loops/second with minimal counting loop</li><li>[tkcrawl.py](https://bugs.python.org/file43873/tkcrawl.py "Uploaded as text/plain at 2016-07-25.04:47:30 by @gvanrossum")</li><li>[loop_tk2.py](https://bugs.python.org/file43887/loop_tk2.py "Uploaded as text/plain at 2016-07-26.05:41:15 by @terryjreedy"): Tkinter example with parallel async coroutines</li><li>[loop_tk3.py](https://bugs.python.org/file43899/loop_tk3.py "Uploaded as text/plain at 2016-07-26.17:21:24 by @terryjreedy"): Use while + await sleep instead of for + atimer</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-07-18.04:10:10.520>
labels = ['type-feature']
title = 'Integrate tkinter and asyncio (and async)'
updated_at = <Date 2022-04-06.01:39:33.192>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-06.01:39:33.192>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2016-07-18.04:10:10.520>
creator = 'terry.reedy'
dependencies = []
files = ['43769', '43770', '43802', '43826', '43828', '43849', '43873', '43887', '43899']
hgrepos = []
issue_num = 27546
keywords = ['patch']
message_count = 23.0
messages = ['270688', '270693', '270724', '270855', '270955', '270976', '270979', '271120', '271194', '271227', '271228', '271230', '271231', '271238', '271324', '271380', '271398', '271421', '271422', '271433', '297263', '416670', '416838']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'terry.reedy', 'Ludovic.Gasc', 'serhiy.storchaka', 'yselivanov', 'Maxime S', 'tritium', 'gbtami']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27546'
versions = ['Python 3.6']
```

</p></details>

**Comment by pitrou** [comment]
If you're interesting in this, you should take a look at what Twisted has done, since they have a history of integrating with various GUI toolkits.
You'll find everything in the "twisted.internet" package:
https://github.com/twisted/twisted/tree/trunk/src/twisted/internet

It appears that for Tk, they use an ugly busy-loop trick as proposed here.

**Comment by kumaraditya303** [comment]
FWIW, this is best left to a separate third party package on pypi rather than in stdib. Unless someone disagree I propose to close this.
