### ISSUE TITLE
Support bytes-like objects when base is given to int()

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#71759]
BPO | [27572](https://bugs.python.org/issue27572)
--- | :---
Nosy | @rhettinger, @bitdancer, @vadmium, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#779</li>
Files | <li>[bytes_like_support_to_int.patch](https://bugs.python.org/file43790/bytes_like_support_to_int.patch "Uploaded as text/plain at 2016-07-19.09:01:58 by @zhangyangyu")</li><li>[bytes_like_support_to_int_v2.patch](https://bugs.python.org/file43825/bytes_like_support_to_int_v2.patch "Uploaded as text/plain at 2016-07-22.06:55:08 by @zhangyangyu")</li><li>[deprecate_byte_like_support_in_int.patch](https://bugs.python.org/file44841/deprecate_byte_like_support_in_int.patch "Uploaded as text/plain at 2016-09-27.10:24:07 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-07-19.08:56:16.627>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Support bytes-like objects when base is given to int()'
updated_at = <Date 2018-09-17.07:17:27.531>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-17.07:17:27.531>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-07-19.08:56:16.627>
creator = 'xiang.zhang'
dependencies = []
files = ['43790', '43825', '44841']
hgrepos = []
issue_num = 27572
keywords = ['patch']
message_count = 11.0
messages = ['270818', '270972', '270973', '270975', '270989', '270994', '270999', '271009', '271101', '277509', '290032']
nosy_count = 5.0
nosy_names = ['rhettinger', 'r.david.murray', 'martin.panter', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['779']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27572'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Created [PR 779](https://github.com/python/cpython/pull/779) for the deprecation.

**Comment by iritkatriel** [comment]
According to the discussion on the PR both @serhiy-storchaka and @brettcannon have concerns about this change. Marking as pending so we can make a decision either way.

**Comment by arhadthedev** [comment]
@zhangyangyu ping?

**Comment by JelleZijlstra** [comment]
My preference would be to close this issue with no action, leaving the current behavior in place. If we were adding these APIs today we shouldn't add support for arbitrary buffers, but the support is there now, it doesn't cost us a lot, and deprecating support may break some users, so I don't think it's worth deprecating the support as #779 proposes.
