### ISSUE TITLE
[doc] configparser: modifying default_section at runtime

### ISSUE THREAD

**Issue by b9150c8f-e4a5-40c6-b508-755ac742b18a** [python/cpython#71770]
BPO | [27583](https://bugs.python.org/issue27583)
--- | :---
Nosy | @bitdancer, @ambv, @wm75, @slateny
PRs | <li>python/cpython#31562</li>
Files | <li>[bug_configparser_default_section.py](https://bugs.python.org/file43808/bug_configparser_default_section.py "Uploaded as text/plain at 2016-07-21.12:54:13 by rk"): testcase (for Py3)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-07-21.12:54:13.554>
labels = ['easy', 'type-bug', '3.9', '3.10', '3.11', 'library', 'docs']
title = '[doc ] configparser: modifying default_section at runtime'
updated_at = <Date 2022-02-25.04:50:50.798>
user = 'https://bugs.python.org/rk'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-25.04:50:50.798>
actor = 'slateny'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2016-07-21.12:54:13.554>
creator = 'rk'
dependencies = []
files = ['43808']
hgrepos = []
issue_num = 27583
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['270918', '270930', '270931', '270932', '281232']
nosy_count = 6.0
nosy_names = ['r.david.murray', 'docs@python', 'lukasz.langa', 'wolma', 'rk', 'slateny']
pr_nums = ['31562']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue27583'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-109088
* gh-109089

**Comment by hugovk** [comment]
Thanks, fixed via https://github.com/python/cpython/pull/31562 and backports to 3.11.
