### ISSUE TITLE
Migrate IDLE context menu items to shell extension

### ISSUE THREAD

**Issue by zooba** [python/cpython#71790]
BPO | [27603](https://bugs.python.org/issue27603)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @zooba, @vedgar

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-07-24.03:59:59.653>
labels = ['expert-IDLE', 'type-feature', 'expert-installation', '3.10', 'OS-windows']
title = 'Migrate IDLE context menu items to shell extension'
updated_at = <Date 2020-06-06.23:39:26.672>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-06.23:39:26.672>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'Installation', 'Windows']
creation = <Date 2016-07-24.03:59:59.653>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 27603
keywords = []
message_count = 10.0
messages = ['271123', '271124', '284922', '285190', '285223', '285237', '285242', '285257', '285271', '370854']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'veky', 'Shane Smith']
pr_nums = []
priority = 'low'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27603'
versions = ['Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
After skimming through the @zooba's comments, it seems to me that solving this issue would be added complexity for little benefit.

**Comment by zooba** [comment]
To make it even more fun, the new context menu in Windows 11 won't show our entries anyway. Apparently people disliked long context menus enough that they all get hidden behind an extra click, and if there is a way to add things back in (which apparently some tools know how to do), we'd end up with the same design of putting them all under a submenu.
