### ISSUE TITLE
[Patch] Use arc4random_buf() on CloudABI

### ISSUE THREAD

**Issue by 4e251d9f-fcc0-4e8a-bd74-31ae42f282c8** [python/cpython#71841]
BPO | [27654](https://bugs.python.org/issue27654)
--- | :---
Nosy | @ncoghlan, @vstinner, @tiran, @EdSchouten
Files | <li>[patch-arc4random](https://bugs.python.org/file43950/patch-arc4random "Uploaded as text/plain at 2016-07-30.10:56:14 by @EdSchouten"): Patch for using arc4random_buf() on CloudABI</li><li>[patch-arc4random](https://bugs.python.org/file44434/patch-arc4random "Uploaded as text/plain at 2016-09-07.12:47:08 by @EdSchouten"): Patch that also has comments</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = None
created_at = <Date 2016-07-30.10:56:14.894>
labels = ['interpreter-core']
title = '[Patch] Use arc4random_buf() on CloudABI'
updated_at = <Date 2016-09-07.13:20:23.211>
user = 'https://github.com/EdSchouten'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-07.13:20:23.211>
actor = 'christian.heimes'
assignee = 'vstinner'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-07-30.10:56:14.894>
creator = 'EdSchouten'
dependencies = []
files = ['43950', '44434']
hgrepos = []
issue_num = 27654
keywords = []
message_count = 5.0
messages = ['271680', '274749', '274802', '274807', '274808']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'vstinner', 'christian.heimes', 'EdSchouten']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue27654'
versions = ['Python 3.6']
```

</p></details>

**Comment by benjaminp** [comment]
CloudABI is no more.

**Comment by vstinner** [comment]
> CloudABI is no more.

Oh. I didn't know:

* https://github.com/NuxiNL/cloudabi#note-this-project-is-unmaintained
* https://en.wikipedia.org/wiki/Capsicum_(Unix)#CloudABI
