### ISSUE TITLE
[posixmodule] [Refactoring patch] Simply call into *at() functions unconditionally when present

### ISSUE THREAD

**Issue by 4e251d9f-fcc0-4e8a-bd74-31ae42f282c8** [python/cpython#71888]
BPO | [27701](https://bugs.python.org/issue27701)
--- | :---
Nosy | @matrixise, @moreati, @EdSchouten
Files | <li>[posixmodule-refactoring.diff](https://bugs.python.org/file44033/posixmodule-refactoring.diff "Uploaded as text/plain at 2016-08-07.08:45:44 by @EdSchouten"): Patch for making posixmodule more CloudABI friendly</li><li>[patch-issue27701](https://bugs.python.org/file44561/patch-issue27701 "Uploaded as text/plain at 2016-09-11.18:07:38 by @EdSchouten")</li><li>[27701.diff](https://bugs.python.org/file45181/27701.diff "Uploaded as text/plain at 2016-10-22.05:17:05 by @EdSchouten")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-08-07.08:45:56.003>
labels = ['extension-modules']
title = '[posixmodule] [Refactoring patch] Simply call into *at() functions unconditionally when present'
updated_at = <Date 2016-10-22.05:17:07.594>
user = 'https://github.com/EdSchouten'
```

bugs.python.org fields:
```python
activity = <Date 2016-10-22.05:17:07.594>
actor = 'EdSchouten'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2016-08-07.08:45:56.003>
creator = 'EdSchouten'
dependencies = []
files = ['44033', '44561', '45181']
hgrepos = []
issue_num = 27701
keywords = ['patch']
message_count = 3.0
messages = ['272114', '275822', '279180']
nosy_count = 3.0
nosy_names = ['matrixise', 'Alex.Willmer', 'EdSchouten']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue27701'
versions = ['Python 3.6']
```

</p></details>

**Comment by benjaminp** [comment]
CloudABI is no more.
