### ISSUE TITLE
cgi.FieldStorage can't parse simple body with Content-Length and no Content-Disposition

### ISSUE THREAD

**Issue by ff3c57f5-3299-468f-b8d1-9d38587cf0ae** [python/cpython#71964]
BPO | [27777](https://bugs.python.org/issue27777)
--- | :---
Nosy | @jackjansen, @srittau, @Cito, @ned-deily, @merwok, @ethanfurman, @PierreQuentel, @bertjwregeer, @berkerpeksag, @AraHaan, @remilapeyre, @eykamp, @bertjwregeer, @kulikjak, @ar45, @bnmnetp
PRs | <li>python/cpython#7804</li><li>python/cpython#10771</li><li>python/cpython#11764</li><li>python/cpython#11764</li><li>python/cpython#11764</li><li>python/cpython#21457</li>
Files | <li>[test](https://bugs.python.org/file44124/test "Uploaded as text/plain at 2016-08-16.13:55:45 by rr-")</li><li>[cgi.py](https://bugs.python.org/file44125/cgi.py "Uploaded as text/plain at 2016-08-16.14:16:07 by @AraHaan")</li><li>[bug27777.patch](https://bugs.python.org/file45527/bug27777.patch "Uploaded as text/plain at 2016-11-18.05:19:51 by @bertjwregeer"): patchset for bug27777</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = None
created_at = <Date 2016-08-16.13:55:45.934>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = "cgi.FieldStorage can't parse simple body with Content-Length and no Content-Disposition"
updated_at = <Date 2022-02-11.13:48:50.611>
user = 'https://bugs.python.org/rr'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-11.13:48:50.611>
actor = 'eric.araujo'
assignee = 'ethan.furman'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-08-16.13:55:45.934>
creator = 'rr-'
dependencies = []
files = ['44124', '44125', '45527']
hgrepos = []
issue_num = 27777
keywords = ['patch']
message_count = 29.0
messages = ['272856', '272857', '272858', '277482', '277483', '277536', '281075', '281793', '281794', '319179', '319438', '319443', '319451', '319480', '319534', '319993', '320503', '320506', '330626', '334882', '334890', '342504', '349264', '366308', '368837', '377493', '386175', '387809', '413071']
nosy_count = 20.0
nosy_names = ['jackjansen', 'srittau', 'cito', 'ned.deily', 'eric.araujo', 'ethan.furman', 'quentel', 'X-Istence', 'berker.peksag', 'Decorater', 'rr-', 'remi.lapeyre', 'watusimoto', 'Bert JW Regeer', 'kulikjak', 'Aron Podrigal', 'elgow', 'Fran Boon', 'Tim Nyborg2', 'bnmnetp']
pr_nums = ['7804', '10771', '11764', '11764', '11764', '21457']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue27777'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by AlexWaygood** [comment]
The `cgi` module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements for this module will no longer be accepted. I am therefore closing this issue.

**Comment by merwok** [comment]
Is it stated in the PEP that the deprecation for 3.13 means that fixes can’t be done in current bugfix branches?

**Comment by merwok** [comment]
No, sounds fine to me in this case.  Thanks for finding the devguide reference!
