### ISSUE TITLE
test failures under Bash on Windows / WSL

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#72056]
BPO | [27869](https://bugs.python.org/issue27869)
--- | :---
Nosy | @brettcannon, @pfmoore, @taleinat, @tjguk, @zware, @zooba, @siorai

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-08-26.18:40:37.308>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = 'test failures under Bash on Windows / WSL'
updated_at = <Date 2018-10-18.18:12:20.248>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-18.18:12:20.248>
actor = 'taleinat'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2016-08-26.18:40:37.308>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 27869
keywords = []
message_count = 9.0
messages = ['273714', '274255', '274266', '292469', '292545', '292551', '299950', '324902', '327994']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'paul.moore', 'taleinat', 'tim.golden', 'zach.ware', 'steve.dower', 'paul.waldorf']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue27869'
versions = ['Python 3.7']
```

</p></details>

**Comment by brettcannon** [comment]
Under Creators Update with a clean Ubuntu 16.04 image and only installing clang and make, I built with `CC=clang ./configure; make -s -j` and ran with `./python -m test -j0 -x test_socket` (test_socket hung in a previous run; I let it run for 10 minutes previously):

348 tests OK.

19 tests failed:
    test_asyncio test_asyncore test_epoll test_fcntl test_ftplib
    test_httpservers test_import test_mmap test_multiprocessing_fork
    test_multiprocessing_forkserver test_multiprocessing_spawn test_os
    test_posix test_resource test_selectors test_signal
    test_subprocess test_time test_unicode_file

36 tests skipped:
    test_bz2 test_crypt test_ctypes test_curses test_dbm_gnu
    test_dbm_ndbm test_devpoll test_gdb test_gzip test_idle
    test_kqueue test_lzma test_msilib test_nis test_ossaudiodev
    test_readline test_smtpnet test_socketserver test_sqlite test_ssl
    test_startfile test_tcl test_timeout test_tix test_tk
    test_ttk_guionly test_ttk_textonly test_turtle test_urllib2net
    test_urllibnet test_winconsoleio test_winreg test_winsound
    test_xmlrpc_net test_zipfile64 test_zlib

Total duration: 3 min 56 sec
Tests result: FAILURE

**Comment by brettcannon** [comment]
Running the tests with -uall didn't change the results.

**Comment by brettcannon** [comment]
When failures are bit more isolated they should probably be reported to https://github.com/microsoft/bashonwindows .

**Comment by brettcannon** [comment]
Running with `./python -m test -u all -j0` causes test_ssl to hang so that needs to also be skipped (otherwise failures look to be the same from a test module level):

19 tests failed:
    test_asyncio test_asyncore test_epoll test_fcntl test_ftplib
    test_httpservers test_import test_mmap test_multiprocessing_fork
    test_multiprocessing_forkserver test_multiprocessing_spawn test_os
    test_posix test_resource test_selectors test_signal
    test_subprocess test_time test_unicode_file

24 tests skipped:
    test_bz2 test_curses test_dbm_gnu test_dbm_ndbm test_devpoll
    test_gdb test_idle test_kqueue test_lzma test_msilib
    test_ossaudiodev test_readline test_sqlite test_startfile test_tcl
    test_tix test_tk test_ttk_guionly test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_zipfile64

**Comment by arhadthedev** [comment]
Is the issue still present? I have no WSL/WSL2 on hands to check.

**Comment by brettcannon** [comment]
I'll do a build and test run to see if any of this still holds.

**Comment by brettcannon** [comment]
```
== Tests result: FAILURE ==

421 tests OK.

1 test failed:
    test_tools

27 tests skipped:
    test.test_asyncio.test_windows_events
    test.test_asyncio.test_windows_utils test_ctypes test_dbm_ndbm
    test_devpoll test_gdb test_idle test_ioctl test_kqueue
    test_launcher test_peg_generator test_smtpnet test_sqlite3
    test_ssl test_stable_abi_ctypes test_startfile test_tcl test_tix
    test_tkinter test_ttk test_ttk_textonly test_turtle
    test_winconsoleio test_winreg test_winsound test_wmi
    test_zipfile64

Total duration: 30 min
Tests result: FAILURE
```

That looks good enough to me!
