### ISSUE TITLE
Socket accept exhaustion during high TCP traffic

### ISSUE THREAD

**Issue by 211147a3-7e92-419f-aa56-1451fdafb290** [python/cpython#72093]
BPO | [27906](https://bugs.python.org/issue27906)
--- | :---
Nosy | @gvanrossum, @vstinner, @1st1
Files | <li>[testservice.zip](https://bugs.python.org/file44286/testservice.zip "Uploaded as application/zip at 2016-08-31.01:57:22 by kevinconway"): Service example for testing</li><li>[multi-accept.patch](https://bugs.python.org/file44287/multi-accept.patch "Uploaded as text/plain at 2016-08-31.01:58:02 by kevinconway"): Patchfile with proposed solution.</li><li>[multi-accept-2.patch](https://bugs.python.org/file44289/multi-accept-2.patch "Uploaded as text/plain at 2016-08-31.04:09:26 by kevinconway"): Patch file with test</li><li>[multi-accept-3.patch](https://bugs.python.org/file44321/multi-accept-3.patch "Uploaded as text/plain at 2016-09-01.13:11:29 by kevinconway"): Patch with test and comment</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/1st1'
closed_at = None
created_at = <Date 2016-08-31.01:57:24.161>
labels = ['expert-asyncio']
title = 'Socket accept exhaustion during high TCP traffic'
updated_at = <Date 2017-04-01.05:47:54.133>
user = 'https://bugs.python.org/kevinconway'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-01.05:47:54.133>
actor = 'serhiy.storchaka'
assignee = 'yselivanov'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2016-08-31.01:57:24.161>
creator = 'kevinconway'
dependencies = []
files = ['44286', '44287', '44289', '44321']
hgrepos = []
issue_num = 27906
keywords = ['patch']
message_count = 16.0
messages = ['273989', '273990', '273991', '273992', '273993', '273996', '274121', '274143', '276498', '276499', '276501', '276526', '276582', '276584', '276586', '276592']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'vstinner', 'python-dev', 'yselivanov', 'kevinconway']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue27906'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by kumaraditya303** [comment]
This seems fixed, anything left to do here?

**Comment by gvanrossum** [comment]
Since a PR was merged that claims to address this, I will just close the issue and remove the pending label.
