### ISSUE TITLE
PEP 467 -- Minor API improvements for binary sequences

### ISSUE THREAD

**Issue by d054863a-9491-4a34-91d1-97859318a343** [python/cpython#72110]
BPO | [27923](https://bugs.python.org/issue27923)
--- | :---
Nosy | @ncoghlan, @ned-deily, @methane, @ethanfurman, @elias6, @vadmium, @serhiy-storchaka, @Rondom
PRs | <li>python/cpython#3237</li>
Files | <li>[pep467.patch](https://bugs.python.org/file44312/pep467.patch "Uploaded as text/plain at 2016-09-01.00:56:16 by @elias6"): Patch with PEP 467 changes</li><li>[pep467_doc_changes.patch](https://bugs.python.org/file44313/pep467_doc_changes.patch "Uploaded as text/plain at 2016-09-01.01:18:05 by @elias6")</li><li>[pep467.patch](https://bugs.python.org/file44316/pep467.patch "Uploaded as text/plain at 2016-09-01.07:07:44 by @vadmium"): Regenerated</li><li>[pep467_doc_changes.patch](https://bugs.python.org/file44317/pep467_doc_changes.patch "Uploaded as text/plain at 2016-09-01.07:08:34 by @vadmium")</li><li>[no_bytes_from_int.patch](https://bugs.python.org/file44329/no_bytes_from_int.patch "Uploaded as text/plain at 2016-09-01.18:19:13 by @serhiy-storchaka")</li><li>[pep467_attempt2.patch](https://bugs.python.org/file44332/pep467_attempt2.patch "Uploaded as text/plain at 2016-09-01.19:24:59 by @elias6")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = None
created_at = <Date 2016-09-01.00:56:19.631>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'PEP 467 -- Minor API improvements for binary sequences'
updated_at = <Date 2018-08-30.17:17:17.305>
user = 'https://github.com/elias6'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-30.17:17:17.305>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-09-01.00:56:19.631>
creator = 'elias'
dependencies = []
files = ['44312', '44313', '44316', '44317', '44329', '44332']
hgrepos = []
issue_num = 27923
keywords = ['patch']
message_count = 32.0
messages = ['274082', '274084', '274085', '274098', '274099', '274109', '274155', '274161', '274165', '274170', '274291', '274388', '274397', '276074', '276078', '276084', '277059', '277304', '277377', '278497', '278498', '278504', '306235', '306236', '311365', '311382', '311383', '311384', '311550', '311556', '311578', '321446']
nosy_count = 9.0
nosy_names = ['ncoghlan', 'ned.deily', 'methane', 'ethan.furman', 'elias', 'martin.panter', 'serhiy.storchaka', 'Rondom', 'amirjn']
pr_nums = ['3237']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue27923'
versions = ['Python 3.8']
```

</p></details>

**Comment by d054863a-9491-4a34-91d1-97859318a343** [comment]
Can someone here merge my pull request? If not, then what else needs to be done for my change to be included in 3.7?

**Comment by serhiy-storchaka** [comment]
I don't think these changes should be merged.

For bytes.zeros(N), you can use b'\\0' * N.

For iterbytes() methods, I think that the general function which works with any sequence that support slicing would be more useful.

**Comment by erlend-aasland** [comment]
Suggesting to close this and the linked PR, as the PEP is still not accepted. An issue can be opened if the PEP is updated for 3.12 and ends up being accepted.

**Comment by kumaraditya303** [comment]
As suggested above, this can be reopened when the PEP is accepted.
