### ISSUE TITLE
Clarify %(prog)s in argparse help formatter returns basename of sys.argv[0] by default

### ISSUE THREAD

**Issue by 13bd9cc7-04b0-4774-9e07-8b0322e89dcc** [python/cpython#72179]
BPO | [27992](https://bugs.python.org/issue27992)
--- | :---
Nosy | @rhettinger, @py-user, @tirkarthi
PRs | <li>python/cpython#12717</li>
Files | <li>[argparse_sys-argv-0-part.diff](https://bugs.python.org/file44420/argparse_sys-argv-0-part.diff "Uploaded as text/plain at 2016-09-07.03:10:52 by @py-user"): Specifies term</li><li>[argparse_sys-argv-0-basename.diff](https://bugs.python.org/file48245/argparse_sys-argv-0-basename.diff "Uploaded as text/plain at 2019-04-07.06:46:18 by @py-user"): Specifies term to basename</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-09-07.03:10:52.945>
labels = ['3.7', '3.8', 'type-bug', 'library', 'docs']
title = 'Clarify %(prog)s in argparse help formatter returns basename of sys.argv[0] by default'
updated_at = <Date 2019-10-24.08:47:12.535>
user = 'https://github.com/py-user'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-24.08:47:12.535>
actor = 'xtreak'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2016-09-07.03:10:52.945>
creator = 'py.user'
dependencies = []
files = ['44420', '48245']
hgrepos = []
issue_num = 27992
keywords = ['patch']
message_count = 4.0
messages = ['274729', '339287', '339557', '339558']
nosy_count = 5.0
nosy_names = ['rhettinger', 'docs@python', 'py.user', 'paul.j3', 'xtreak']
pr_nums = ['12717']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue27992'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by slateny** [comment]
Resolved per https://github.com/python/cpython/pull/30298
