### ISSUE TITLE
Streamline repr(partial object)

### ISSUE THREAD

**Issue by cd293b3e-6d38-412b-8370-a46a9aaee518** [python/cpython#72249]
BPO | [28062](https://bugs.python.org/issue28062)
--- | :---
Nosy | @rhettinger, @ncoghlan, @serhiy-storchaka, @Vgr255
Files | <li>[functools_partial_repr_1.patch](https://bugs.python.org/file44529/functools_partial_repr_1.patch "Uploaded as text/plain at 2016-09-10.12:12:42 by @Vgr255")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-09-10.12:12:43.179>
labels = ['type-bug', 'library']
title = 'Streamline repr(partial object)'
updated_at = <Date 2016-09-10.12:40:13.692>
user = 'https://github.com/Vgr255'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-10.12:40:13.692>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-09-10.12:12:43.179>
creator = 'abarry'
dependencies = []
files = ['44529']
hgrepos = []
issue_num = 28062
keywords = ['patch']
message_count = 2.0
messages = ['275628', '275632']
nosy_count = 4.0
nosy_names = ['rhettinger', 'ncoghlan', 'serhiy.storchaka', 'abarry']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28062'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-101910

**Comment by furkanonder** [comment]
The [PR](https://github.com/python/cpython/pull/101910) is ready for review. @serhiy-storchaka

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @Vgr255 and @furkanonder.

I do not think that it is worth to backport this change.
