### ISSUE TITLE
Deprecate isdst argument in email.utils.localtime

### ISSUE THREAD

**Issue by abalkin** [python/cpython#72346]
BPO | [28159](https://bugs.python.org/issue28159)
--- | :---
Nosy | @abalkin, @bitdancer, @aw1231, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-09-14.21:55:13.766>
labels = ['easy', 'library', '3.11']
title = 'Deprecate isdst argument in email.utils.localtime'
updated_at = <Date 2022-02-08.16:46:38.005>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-08.16:46:38.005>
actor = 'Alan.Williams'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-09-14.21:55:13.766>
creator = 'belopolsky'
dependencies = []
files = []
hgrepos = []
issue_num = 28159
keywords = ['easy']
message_count = 7.0
messages = ['276492', '281078', '281125', '281127', '281139', '281161', '412846']
nosy_count = 4.0
nosy_names = ['belopolsky', 'r.david.murray', 'Alan.Williams', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue28159'
versions = ['Python 3.11']
```

</p></details>

**Comment by terryjreedy** [comment]
@aw1231 Thank you for sticking with the review process for a year to get this to completion.  Next time, please do not put `gh-######` in the branch title as it triggers an unneeded duplicate report of every commit here on the issue.  I believe anything else without `gh-` or a literal `#` prefix would not do this.

**Comment by aw1231** [comment]
Thanks to you both! I forgot about this! I'll be sure to format the branch properly next time. Thanks again!
