### ISSUE TITLE
The 'subprocess' module leaks memory when called in certain ways

### ISSUE THREAD

**Issue by 2dfda3e9-bda3-45c1-94d6-cd5751f640b8** [python/cpython#72352]
BPO | [28165](https://bugs.python.org/issue28165)
--- | :---
Nosy | @vstinner, @bitdancer, @ztane, @The-Compiler
Files | <li>[Memory-Leak-Test.zip](https://bugs.python.org/file44723/Memory-Leak-Test.zip "Uploaded as application/zip at 2016-09-17.21:14:53 by Xavion"): All test files - in correct hierarchy</li><li>[Test.sh](https://bugs.python.org/file44724/Test.sh "Uploaded as text/plain at 2016-09-17.21:16:12 by Xavion"): Memory monitoring script</li><li>[Test-1.py](https://bugs.python.org/file44725/Test-1.py "Uploaded as text/plain at 2016-09-17.21:16:46 by Xavion"): First test case</li><li>[Test-2.py](https://bugs.python.org/file44726/Test-2.py "Uploaded as text/plain at 2016-09-17.21:17:19 by Xavion"): Second test case</li><li>[Test-1-no-gc.log](https://bugs.python.org/file44727/Test-1-no-gc.log "Uploaded as text/x-log at 2016-09-17.21:18:49 by Xavion"): First test results - no garbage collection</li><li>[Test-1-gc.log](https://bugs.python.org/file44728/Test-1-gc.log "Uploaded as text/x-log at 2016-09-17.21:19:10 by Xavion"): First test results - garbage collection enforced</li><li>[Test-2-no-gc.log](https://bugs.python.org/file44729/Test-2-no-gc.log "Uploaded as text/x-log at 2016-09-17.21:19:30 by Xavion"): Second test results - no garbage collection</li><li>[Test-2-gc.log](https://bugs.python.org/file44730/Test-2-gc.log "Uploaded as text/x-log at 2016-09-17.21:20:00 by Xavion"): Second test results - garbage collection enforced</li><li>[Test-3.py](https://bugs.python.org/file44749/Test-3.py "Uploaded as text/plain at 2016-09-20.07:43:52 by @vstinner")</li><li>[Test-3a.py](https://bugs.python.org/file44761/Test-3a.py "Uploaded as text/plain at 2016-09-20.22:40:14 by Xavion"): Third test case (revised)</li><li>[Test-3a-no-gc.log](https://bugs.python.org/file44762/Test-3a-no-gc.log "Uploaded as text/x-log at 2016-09-20.22:41:14 by Xavion"): Third test results - no garbage collection</li><li>[Test-3a-gc.log](https://bugs.python.org/file44763/Test-3a-gc.log "Uploaded as text/x-log at 2016-09-20.22:41:54 by Xavion"): Third test results - garbage collection enforced</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-09-15.04:31:15.193>
labels = ['library', 'performance']
title = "The 'subprocess' module leaks memory when called in certain ways"
updated_at = <Date 2016-09-20.22:41:54.050>
user = 'https://bugs.python.org/Xavion'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-20.22:41:54.050>
actor = 'Xavion'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-09-15.04:31:15.193>
creator = 'Xavion'
dependencies = []
files = ['44723', '44724', '44725', '44726', '44727', '44728', '44729', '44730', '44749', '44761', '44762', '44763']
hgrepos = []
issue_num = 28165
keywords = []
message_count = 19.0
messages = ['276514', '276515', '276517', '276523', '276539', '276775', '276794', '276850', '276950', '276986', '276987', '276989', '276990', '276994', '277009', '277010', '277012', '277015', '277077']
nosy_count = 5.0
nosy_names = ['vstinner', 'r.david.murray', 'ztane', 'The Compiler', 'Xavion']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue28165'
versions = ['Python 3.5']
```

</p></details>

**Comment by certara-msale** [comment]
Was there ever a resolution to this question? I think I'm having the same issue, memory gradually creeping up with calls to pOpen. I'm saving the process

proc = Popen(command, stdout=DEVNULL, stderr=STDOUT)
then calling poll to see if it is done
if not proc.poll() is None

seems to accumulate ~ 5 Gb of memory with 100,000 calls.
Is the a better way to do this, or was there an answer to the original question?

thanks

**Comment by vstinner** [comment]
Test-3a.py doesn't show any memory leak. I close the issue again.

Output on Linux (Fedora) with Python 3.11 beta1 if I uncomment the grep line:

```
$ python3.11 Test-3a.py 
.VmRSS:	   10472 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10700 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
.VmRSS:	   10704 kB
(...)
```
