### ISSUE TITLE
argparse with subcommands difference in python 2.7 / 3.5

### ISSUE THREAD

**Issue by 66602375-6580-429c-aa75-d5c5adcf4124** [python/cpython#72397]
BPO | [28210](https://bugs.python.org/issue28210)
--- | :---
Nosy | @bitdancer, @timgraham, @Mariatta
Files | <li>[test_argparse.py](https://bugs.python.org/file44751/test_argparse.py "Uploaded as text/plain at 2016-09-20.08:43:54 by stephan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-09-20.08:43:54.408>
labels = ['type-bug']
title = 'argparse with subcommands difference in python 2.7 / 3.5'
updated_at = <Date 2016-09-28.21:12:42.761>
user = 'https://bugs.python.org/stephan'
```

bugs.python.org fields:
```python
activity = <Date 2016-09-28.21:12:42.761>
actor = 'Mariatta'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2016-09-20.08:43:54.408>
creator = 'stephan'
dependencies = []
files = ['44751']
hgrepos = []
issue_num = 28210
keywords = []
message_count = 5.0
messages = ['277017', '277028', '277099', '277154', '277566']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'paul.j3', 'Tim.Graham', 'stephan', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28210'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by savannahostrowski** [comment]
Given that 2.7 and 3.5 are both EOL, I think this issue is obsolete at this point. 

I will close this, but if someone disagrees and believes it should be left open, please let me know, and I'll be happy to reopen it.

**Comment by terryjreedy** [comment]
Definitely obsolete.  The 2010 issue referenced above, now on GH, is still open.  Whether it should be is a different question.
