### ISSUE TITLE
Make public the current private known hash functions in the C-API

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#72643]
BPO | [28457](https://bugs.python.org/issue28457)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka
Dependencies | <li>bpo-28123: _PyDict_GetItem_KnownHash ignores DKIX_ERROR return</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-10-16.23:42:23.101>
labels = ['interpreter-core', '3.7']
title = 'Make public the current private known hash functions in the C-API'
updated_at = <Date 2016-10-23.20:25:07.656>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2016-10-23.20:25:07.656>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-10-16.23:42:23.101>
creator = 'rhettinger'
dependencies = ['28123']
files = []
hgrepos = []
issue_num = 28457
keywords = []
message_count = 2.0
messages = ['278788', '279284']
nosy_count = 2.0
nosy_names = ['rhettinger', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue28457'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Since there was no comment for 8 years, I suppose the this feature is not very important. So I prefer to keep the status quo: keep these API in the internal C API for now.
