### ISSUE TITLE
[Patch] Make os.umask() optional

### ISSUE THREAD

**Issue by 4e251d9f-fcc0-4e8a-bd74-31ae42f282c8** [python/cpython#72687]
BPO | [28501](https://bugs.python.org/issue28501)
--- | :---
Nosy | @EdSchouten
Files | <li>[umask-optional.diff](https://bugs.python.org/file45183/umask-optional.diff "Uploaded as text/plain at 2016-10-22.05:31:43 by @EdSchouten"): Patch for making the presence of os.umask() optional</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-10-22.05:31:45.054>
labels = ['extension-modules']
title = '[Patch] Make os.umask() optional'
updated_at = <Date 2016-10-22.05:31:45.054>
user = 'https://github.com/EdSchouten'
```

bugs.python.org fields:
```python
activity = <Date 2016-10-22.05:31:45.054>
actor = 'EdSchouten'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2016-10-22.05:31:45.054>
creator = 'EdSchouten'
dependencies = []
files = ['45183']
hgrepos = []
issue_num = 28501
keywords = ['patch']
message_count = 1.0
messages = ['279182']
nosy_count = 1.0
nosy_names = ['EdSchouten']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue28501'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
I think this was added in a6ca8eee225. 

CC @tiran

**Comment by benjaminp** [comment]
I think CloudABI is also on ice, so the original motivation doesn't exist anymore.
