### ISSUE TITLE
ICC compiler check is too permissive

### ISSUE THREAD

**Issue by bd9e6527-4c12-48c7-9bed-693f45a463a0** [python/cpython#72770]
BPO | [28584](https://bugs.python.org/issue28584)
--- | :---
Nosy | @vstinner, @zware, @MojoVampire, @mathstuf, @struktured, @iritkatriel
Files | <li>[icc-pattern-check-fix.patch](https://bugs.python.org/file45307/icc-pattern-check-fix.patch "Uploaded as text/plain at 2016-11-01.21:22:45 by @struktured"): suggested patch</li><li>[icc-find.patch](https://bugs.python.org/file47595/icc-find.patch "Uploaded as text/plain at 2018-05-17.15:12:34 by locutusofborg")</li><li>[icc-find-v2.patch](https://bugs.python.org/file47597/icc-find-v2.patch "Uploaded as text/plain at 2018-05-17.15:15:57 by locutusofborg")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-01.21:22:46.602>
labels = ['build', 'expert-installation', '3.9', '3.10', '3.11']
title = 'ICC compiler check is too permissive'
updated_at = <Date 2022-03-22.06:31:58.078>
user = 'https://github.com/struktured'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.06:31:58.078>
actor = 'mathstuf'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2016-11-01.21:22:46.602>
creator = 'struktured'
dependencies = []
files = ['45307', '47595', '47597']
hgrepos = []
issue_num = 28584
keywords = ['patch']
message_count = 5.0
messages = ['279893', '280049', '316944', '316946', '415558']
nosy_count = 7.0
nosy_names = ['vstinner', 'zach.ware', 'josh.r', 'mathstuf', 'struktured', 'locutusofborg', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue28584'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as icc is not supported as per PEP 11. Also the patch would have to be created against main branch as a PR if this is still an issue.

**Comment by mathstuf** [comment]
@LocutusOfBorg commit e4fa74f78a7bd0f5178f70c9d90af429631f2ad4 is still not 100% correct because `mpicc` will trip it. If ICC is really no longer supported, should these branches raise an error? `mpicc` is still tricky to support though as one needs to divine what the underlying compiler is.
