### ISSUE TITLE
argparse claims '*' positional argument is required in error output

### ISSUE THREAD

**Issue by c103b3da-8d2d-4263-a996-57e557bc5081** [python/cpython#72795]
BPO | [28609](https://bugs.python.org/issue28609)
--- | :---
Nosy | @benhoyt, @charlierproctor, @iritkatriel
Files | <li>[optional_arguments.patch](https://bugs.python.org/file45357/optional_arguments.patch "Uploaded as text/plain at 2016-11-04.19:22:12 by @charlierproctor"): Check that action.nargs not in [OPTIONAL, ZERO_OR_MORE]</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-04.15:19:23.095>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = "argparse claims '*' positional argument is required in error output"
updated_at = <Date 2021-12-10.17:07:21.760>
user = 'https://bugs.python.org/rrt'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.17:07:21.760>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-11-04.15:19:23.095>
creator = 'rrt'
dependencies = []
files = ['45357']
hgrepos = []
issue_num = 28609
keywords = ['patch']
message_count = 12.0
messages = ['280052', '280072', '280074', '280161', '280169', '280171', '280180', '280181', '280230', '288644', '343614', '408225']
nosy_count = 6.0
nosy_names = ['benhoyt', 'paul.j3', 'charlie.proctor', 'rrt', 'svenevs', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28609'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-124306
* gh-124421
* gh-124422

**Comment by 8029d403-64fb-4202-9817-4695852d288d** [comment]
I definitely agree with Reuben here -- I just ran into this issue while creating a "production quality" tool, and the help message produced by argparse with nargs='\*' confused me too. It's pretty clear that this is a simple bug in argparse's production of that usage message: it says ARGUMENT is required, but it isn't.

However, the workaround of specifying an (unused) default is a reasonable workaround in the meantime -- thanks Paul.

**Comment by vkoukis** [comment]
I would like to say that I also bumped into this, the usage text / error message is self-contradictory. The end result is very confusing to users.

I understand there is a workaround, but I couldn't find any mention of it anywhere in the documentation, and Googling for this buggy argparse behavior didn't come up with this GitHub issue.

**Comment by serhiy-storchaka** [comment]
I agree that the current error message that requires an argument with `nargs='*'` is misleading.

It is even worse for `nargs=REMAINDER`, because it refers to argument name not mentioned in the "usage" line:
```py
from argparse import *
parser = ArgumentParser()
parser.add_argument('COMMAND', help='command to run')
parser.add_argument('ARGUMENT', nargs=REMAINDER, help='arguments to COMMAND')
parser.parse_args([])
```
Output:
```
usage: [-h] COMMAND ...
: error: the following arguments are required: COMMAND, ARGUMENT
```

I think that it is an error to mark such positional arguments as required.

I guess that the reason of marking `nargs='*'` without `default` as required lies in the way how conflicts in mutually exclusive groups were detected. The code simply checked if the value is the same as the default value, and this obviously does not work for `[]`. Fixing this code allows to make all positional arguments with `nargs='*'` non-required.

As for `nargs=REMAINDER`, I think it was just an omission.
