### ISSUE TITLE
Provide PDB hook to customize how to find source files

### ISSUE THREAD

**Issue by de89d561-f47f-4804-bb57-3f4ca93fd317** [python/cpython#72796]
BPO | [28610](https://bugs.python.org/issue28610)
--- | :---
Nosy | @xdegaye
Files | <li>[debug_script.py](https://bugs.python.org/file45358/debug_script.py "Uploaded as text/plain at 2016-11-04.20:18:25 by @xdegaye")</li><li>[debug_script.patch](https://bugs.python.org/file45366/debug_script.patch "Uploaded as text/plain at 2016-11-05.16:51:49 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-04.16:18:28.108>
labels = ['3.7', 'type-feature', 'library']
title = 'Provide PDB hook to customize how to find source files'
updated_at = <Date 2016-11-08.20:33:34.899>
user = 'https://bugs.python.org/PinkuSurana'
```

bugs.python.org fields:
```python
activity = <Date 2016-11-08.20:33:34.899>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-11-04.16:18:28.108>
creator = 'Pinku Surana'
dependencies = []
files = ['45358', '45366']
hgrepos = []
issue_num = 28610
keywords = ['patch']
message_count = 5.0
messages = ['280056', '280077', '280117', '280335', '280344']
nosy_count = 2.0
nosy_names = ['xdegaye', 'Pinku Surana']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28610'
versions = ['Python 3.7']
```

</p></details>

**Comment by gaogaotiantian** [comment]
It seems like the problem is solved so I'll close this for now. If anyone would like to pursue more about this matter, feel free to reopen.
