### ISSUE TITLE
[Patch] Stop using inet_ntoa() when possible.

### ISSUE THREAD

**Issue by 4e251d9f-fcc0-4e8a-bd74-31ae42f282c8** [python/cpython#72805]
BPO | [28619](https://bugs.python.org/issue28619)
--- | :---
Nosy | @EdSchouten
Files | <li>[patch-inet_ntoa.diff](https://bugs.python.org/file45364/patch-inet_ntoa.diff "Uploaded as text/plain at 2016-11-05.11:37:20 by @EdSchouten"): Patch for socketmodule to use inet_ntop() when available</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-05.11:37:21.542>
labels = ['extension-modules', '3.7']
title = '[Patch] Stop using inet_ntoa() when possible.'
updated_at = <Date 2016-11-05.11:37:21.542>
user = 'https://github.com/EdSchouten'
```

bugs.python.org fields:
```python
activity = <Date 2016-11-05.11:37:21.542>
actor = 'EdSchouten'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2016-11-05.11:37:21.542>
creator = 'EdSchouten'
dependencies = []
files = ['45364']
hgrepos = []
issue_num = 28619
keywords = ['patch']
message_count = 1.0
messages = ['280109']
nosy_count = 1.0
nosy_names = ['EdSchouten']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue28619'
versions = ['Python 3.7']
```

</p></details>

**Comment by erlend-aasland** [comment]
I can't see how this is a problem in the current socket module source code. Suggesting closing this issue. cc. @tiran

**Comment by benjaminp** [comment]
CloudABI is no more.
