### ISSUE TITLE
Fix code example in Python 3.5 telnetlib documentation

### ISSUE THREAD

**Issue by 13e75a57-3359-44e7-a9fb-2f1f28c512a2** [python/cpython#72847]
BPO | [28661](https://bugs.python.org/issue28661)
--- | :---
Nosy | @jackdied, @bitdancer, @tiabc, @normanlorrain
Files | <li>[weather.py](https://bugs.python.org/file50124/weather.py "Uploaded as text/plain at 2021-06-22.18:58:45 by @normanlorrain")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-10.19:16:31.542>
labels = ['easy', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = 'Fix code example in Python 3.5 telnetlib documentation'
updated_at = <Date 2021-06-22.18:58:45.391>
user = 'https://github.com/tiabc'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-22.18:58:45.391>
actor = 'Norman Lorrain'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-11-10.19:16:31.542>
creator = 'tiabc'
dependencies = []
files = ['50124']
hgrepos = []
issue_num = 28661
keywords = ['easy']
message_count = 5.0
messages = ['280536', '280549', '280563', '280586', '396357']
nosy_count = 5.0
nosy_names = ['jackdied', 'r.david.murray', 'docs@python', 'tiabc', 'Norman Lorrain']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28661'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by hugovk** [comment]
Note the telnetlib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AA-Turner** [comment]
Closing per Hugo's comment.

A
