### ISSUE TITLE
Add documentation for METH_FASTCALL and _PyObject_FastCall*()

### ISSUE THREAD

**Issue by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [python/cpython#72991]
BPO | [28805](https://bugs.python.org/issue28805)
--- | :---
Nosy | @warsaw, @vstinner, @methane, @skrah, @serhiy-storchaka, @jdemeyer, @miss-islington, @isidentical
PRs | <li>python/cpython#14079</li><li>python/cpython#14136</li><li>python/cpython#14137</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-26.11:08:54.537>
labels = ['type-feature', '3.7', 'docs']
title = 'Add documentation for METH_FASTCALL and _PyObject_FastCall*()'
updated_at = <Date 2019-12-01.09:13:41.667>
user = 'https://github.com/skrah'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-01.09:13:41.667>
actor = 'BTaskaya'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-11-26.11:08:54.537>
creator = 'skrah'
dependencies = []
files = []
hgrepos = []
issue_num = 28805
keywords = ['patch']
message_count = 14.0
messages = ['281766', '281771', '281778', '281784', '281785', '303701', '303702', '303703', '303704', '345577', '345762', '345789', '345790', '357673']
nosy_count = 9.0
nosy_names = ['barry', 'vstinner', 'methane', 'skrah', 'docs@python', 'serhiy.storchaka', 'jdemeyer', 'miss-islington', 'BTaskaya']
pr_nums = ['14079', '14136', '14137']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28805'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by warsaw** [comment]
This and the \_PyObject_FastCall* APIs really do need to be documented, especially if they're going to be used in the interpreter itself.  The leading underscore signifies that it's not part of the public API (well, METH_FASTCALL doesn't have a leading underscore).

When these are not documented, then they aren't discoverable, so there are cases where it may be useful but will be overlooked.  It also means that folks will be inclined to cargo cult the few existing uses without perhaps understanding the full semantics.

Can we please document these for Python 3.7 at least?

**Comment by vstinner** [comment]
> Can we please document these for Python 3.7 at least?

I chose to not document FASTCALL on purpose in Python 3.6, I wanted to keep everything private, until we get enough feedback and stabilize the API.

Recently, the FASTCALL API changed: METH_FASTCALL doesn't support keywords anymore. You have to pass METH_FASTCALL|METH_KEYWORDS.

It seems like the API became stable.

I don't know if we should make the API public or not. PyPy would complain as usual that we give them more work to do :-D

**Comment by vstinner** [comment]
I suggest to document the following 4 functions/macros:

```c
PyAPI_FUNC(PyObject *) _PyObject_FastCallDict(
    PyObject *callable,
    PyObject **args,
    Py_ssize_t nargs,
    PyObject *kwargs);

PyAPI_FUNC(PyObject *) _PyObject_FastCallKeywords(
    PyObject *callable,
    PyObject **args,
    Py_ssize_t nargs,
    PyObject *kwnames);

#define _PyObject_FastCall(func, args, nargs) \
    _PyObject_FastCallDict((func), (args), (nargs), NULL)

#define _PyObject_CallNoArg(func) \
    _PyObject_FastCallDict((func), NULL, 0, NULL)
```


And the METH_FASTCALL and METH_FASTCALL|METH_KEYWORDS calling convention.

**Comment by vstinner** [comment]
> It would also be nice if Cython could use it automatically.

Cython is using FASTCALL since Python 3.6.

**Comment by hauntsaninja** [comment]
Thanks, I think we can close this docs issue as completed
