### ISSUE TITLE
os.environ should preserve the case of the OS keys ?

### ISSUE THREAD

**Issue by e888b79e-0010-4e57-af49-96f92d830757** [python/cpython#73010]
BPO | [28824](https://bugs.python.org/issue28824)
--- | :---
Nosy | @pfmoore, @tjguk, @bitdancer, @zware, @eryksun, @zooba, @tzickel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-11-28.18:55:46.277>
labels = ['type-bug', '3.9', '3.10', '3.11', 'library', 'OS-windows']
title = 'os.environ should preserve the case of the OS keys ?'
updated_at = <Date 2022-03-02.11:19:53.537>
user = 'https://github.com/tzickel'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-02.11:19:53.537>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2016-11-28.18:55:46.277>
creator = 'tzickel'
dependencies = []
files = []
hgrepos = []
issue_num = 28824
keywords = []
message_count = 10.0
messages = ['281906', '281909', '281910', '281912', '281914', '281915', '281918', '387676', '414115', '414141']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'r.david.murray', 'benrg', 'zach.ware', 'eryksun', 'steve.dower', 'tzickel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28824'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by valkom1** [comment]
Ugly workaround:
`environ_upper = {k.upper():v for k,v in dict(os.environ).items()}`

**Comment by vmatt** [comment]
If you don't have duplicate entries, and want to just uppercase all envs, you can do it with this one-liner:
`environ_upper = {k.upper():v for k,v in dict(os.environ).items()}`

**Comment by karrtikr** [comment]
Given this is now documented that keys are always converted to upper case in #101754, should we close this? @zooba @brettcannon
