### ISSUE TITLE
Make str.count one character for latin1 string faster

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#73107]
BPO | [28921](https://bugs.python.org/issue28921)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @zhangyangyu
Files | <li>[latin1-str-count-one-character.patch](https://bugs.python.org/file45816/latin1-str-count-one-character.patch "Uploaded as text/plain at 2016-12-09.14:38:23 by @zhangyangyu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-09.14:38:24.328>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Make str.count one character for latin1 string faster'
updated_at = <Date 2016-12-12.16:49:06.876>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2016-12-12.16:49:06.876>
actor = 'xiang.zhang'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-12-09.14:38:24.328>
creator = 'xiang.zhang'
dependencies = []
files = ['45816']
hgrepos = []
issue_num = 28921
keywords = ['patch']
message_count = 5.0
messages = ['282784', '282785', '282800', '282803', '283027']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28921'
versions = ['Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
This was rejected as too complex in 2016 and has been idle since. Marking as pending with a view to closing soon unless someone will object.
