### ISSUE TITLE
[doc] The fact that multiprocess.Queue uses serialization should be documented.

### ISSUE THREAD

**Issue by e2e7f7f4-43b4-4f22-aa3d-f9277ef52b4e** [python/cpython#73159]
BPO | [28973](https://bugs.python.org/issue28973)
--- | :---
Nosy | @bitdancer, @applio, @Bernhard10, @iritkatriel
Files | <li>[mwe.py](https://bugs.python.org/file45899/mwe.py "Uploaded as text/plain at 2016-12-14.14:38:29 by @Bernhard10"): Minimal working example to reproduce this bug/ surprising behaviour.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-14.14:38:29.506>
labels = ['easy', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = '[doc] The fact that multiprocess.Queue uses serialization should be documented.'
updated_at = <Date 2021-08-07.13:17:33.028>
user = 'https://github.com/Bernhard10'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-07.13:17:33.028>
actor = 'r.david.murray'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2016-12-14.14:38:29.506>
creator = 'Bernhard10'
dependencies = []
files = ['45899']
hgrepos = []
issue_num = 28973
keywords = ['easy']
message_count = 8.0
messages = ['283192', '283193', '283195', '283198', '283199', '283206', '398809', '399179']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'docs@python', 'davin', 'Bernhard10', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue28973'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-121686
* gh-121727
* gh-121728

**Comment by digitalfotografen** [comment]
I am starting a doc PR on this during this weekends EuroPython Sprints and plan to have it finished by this weekend

**Comment by gpshead** [comment]
thanks!  there might be seen as adding some redundancy in the multiprocessing docs, but that's a larger "should this doc be rewritten from a different perspective?" kind of issue. This new text at least gets the important information stated directly, in the places I expect readers are likely to see it. Rather than inferring it from other notes in the docs.
