### ISSUE TITLE
nntplib is broken when responses are longer than _MAXLINE

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#73157]
BPO | [28971](https://bugs.python.org/issue28971)
--- | :---
Nosy | @tiran, @mcepl, @xdegaye, @vadmium, @zware, @serhiy-storchaka, @zhangyangyu, @Carreau
Files | <li>[test_nntplib.log](https://bugs.python.org/file45897/test_nntplib.log "Uploaded as text/plain at 2016-12-14.11:54:12 by @xdegaye")</li><li>[nntplib_maxline.patch](https://bugs.python.org/file45901/nntplib_maxline.patch "Uploaded as text/plain at 2016-12-14.21:12:14 by @xdegaye")</li><li>[nntplib_maxbytes.patch](https://bugs.python.org/file45939/nntplib_maxbytes.patch "Uploaded as text/plain at 2016-12-17.15:15:31 by @xdegaye")</li><li>[max_over_line.patch](https://bugs.python.org/file46020/max_over_line.patch "Uploaded as text/plain at 2016-12-24.06:54:18 by @vadmium")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-14.11:54:14.048>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'nntplib is broken when responses are longer than _MAXLINE'
updated_at = <Date 2019-05-21.18:29:17.222>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-21.18:29:17.222>
actor = 'mcepl'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-12-14.11:54:14.048>
creator = 'xdegaye'
dependencies = []
files = ['45897', '45901', '45939', '46020']
hgrepos = []
issue_num = 28971
keywords = ['patch', 'buildbot']
message_count = 34.0
messages = ['283189', '283205', '283207', '283208', '283218', '283226', '283236', '283261', '283265', '283294', '283367', '283423', '283424', '283425', '283429', '283430', '283490', '283508', '283509', '283510', '283512', '283536', '283619', '283683', '283924', '343037', '343053', '343055', '343056', '343057', '343062', '343064', '343069', '343078']
nosy_count = 9.0
nosy_names = ['christian.heimes', 'mcepl', 'xdegaye', 'python-dev', 'martin.panter', 'zach.ware', 'serhiy.storchaka', 'xiang.zhang', 'mbussonn']
pr_nums = []
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28971'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by hugovk** [comment]
Update: the nntplib module is now deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by kumaraditya303** [comment]
Closed as the module is deprecated.
