### ISSUE TITLE
copy.copy fails on threading.local subclass

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#73153]
BPO | [28967](https://bugs.python.org/issue28967)
--- | :---
Nosy | @ned-deily, @serhiy-storchaka, @JelleZijlstra
Files | <li>[thread_local_copy.py](https://bugs.python.org/file45886/thread_local_copy.py "Uploaded as text/plain at 2016-12-14.06:09:47 by @JelleZijlstra")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-14.06:09:48.373>
labels = ['type-bug', '3.7']
title = 'copy.copy fails on threading.local subclass'
updated_at = <Date 2016-12-15.08:54:54.565>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2016-12-15.08:54:54.565>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2016-12-14.06:09:48.373>
creator = 'JelleZijlstra'
dependencies = []
files = ['45886']
hgrepos = []
issue_num = 28967
keywords = ['3.6regression']
message_count = 4.0
messages = ['283165', '283167', '283169', '283260']
nosy_count = 3.0
nosy_names = ['ned.deily', 'serhiy.storchaka', 'JelleZijlstra']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue28967'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
Since it's not a regression, and it's not clear whether it is a useful feature, I am closing the issue. If someone will come up with a requirement for this feature they will create a new issue and explain the use case.
