### ISSUE TITLE
Custom functions in sqlite receive None on invalid UTF-8

### ISSUE THREAD

**Issue by 34b5bed8-5a21-4553-9b3a-83cd0e64005a** [python/cpython#73207]
BPO | [29021](https://bugs.python.org/issue29021)
--- | :---
Nosy | @berkerpeksag, @palaviv
Files | <li>[29021.patch](https://bugs.python.org/file46164/29021.patch "Uploaded as text/plain at 2017-01-05.22:22:16 by @palaviv")</li><li>[29021-fixed.patch](https://bugs.python.org/file46166/29021-fixed.patch "Uploaded as text/plain at 2017-01-05.22:51:39 by @palaviv")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-20.09:24:51.228>
labels = ['3.7', 'type-bug', 'library']
title = 'Custom functions in sqlite receive None on invalid UTF-8'
updated_at = <Date 2017-04-15.18:18:47.435>
user = 'https://bugs.python.org/IngoRuhnke'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-15.18:18:47.435>
actor = 'palaviv'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-12-20.09:24:51.228>
creator = 'Ingo Ruhnke'
dependencies = []
files = ['46164', '46166']
hgrepos = []
issue_num = 29021
keywords = ['patch']
message_count = 7.0
messages = ['283674', '284673', '284700', '284776', '284783', '284924', '291726']
nosy_count = 4.0
nosy_names = ['ghaering', 'berker.peksag', 'Ingo Ruhnke', 'palaviv']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29021'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
In my patch I use sqlite3_create_function_v2 which was added in sqlite 3.7.3 (2010-10-08). There were a few problems after adding sqlite3_stmt_readonly in 284676cf2ac8 as can be seen in issue bpo-29355. sqlite3_stmt_readonly was added in 3.7.4 (2010-12-07) so I guess using sqlite3_create_function_v2 will cause the same problems.

Do you think I should find another way to fix this issue? I can follow all the user functions and free on my own but that will make the code more complex. On the other hand I can add this fix in ifdef and the behavior will be different when using sqlite in versions smaller then 3.7.3.

**Comment by erlend-aasland** [comment]
Is this still a problem? I tried the repro from the OP, but I was unable to spot the inconsistency. I'm not sure the added complexity is worth it. Considering closing this issue.
