### ISSUE TITLE
Coverage influence tests, make some of them fail

### ISSUE THREAD

**Issue by 0dc499de-344b-46e9-abb6-e45131ef806e** [python/cpython#73234]
BPO | [29048](https://bugs.python.org/issue29048)
--- | :---
Nosy | @brettcannon, @nedbat, @bitdancer, @serhiy-storchaka, @iselind
Files | <li>[coverity-tests-warnings.patch](https://bugs.python.org/file45998/coverity-tests-warnings.patch "Uploaded as text/plain at 2016-12-22.13:46:23 by @serhiy-storchaka")</li><li>[no-stderr.diff](https://bugs.python.org/file46025/no-stderr.diff "Uploaded as text/plain at 2016-12-24.17:09:47 by @iselind")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-22.11:56:16.153>
labels = ['3.7', 'type-bug', 'tests']
title = 'Coverage influence tests, make some of them fail'
updated_at = <Date 2017-03-07.17:36:45.004>
user = 'https://github.com/iselind'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-07.17:36:45.004>
actor = 'brett.cannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2016-12-22.11:56:16.153>
creator = 'patriki'
dependencies = []
files = ['45998', '46025']
hgrepos = []
issue_num = 29048
keywords = ['patch']
message_count = 19.0
messages = ['283828', '283833', '283837', '283838', '283840', '283944', '283945', '283947', '283957', '283958', '283959', '283960', '283962', '283963', '283967', '283968', '283969', '283970', '283971']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'nedbat', 'r.david.murray', 'serhiy.storchaka', 'patriki']
pr_nums = []
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29048'
versions = ['Python 3.7']
```

</p></details>

**Comment by AA-Turner** [comment]
@iselind is this issue still relevant for 3.11/3.12?

A

**Comment by iselind** [comment]
> @iselind is this issue still relevant for 3.11/3.12?
> 
> A

I have no idea actually. I've not looked at this since about my last comment to this issue, 6 years ago...

**Comment by AA-Turner** [comment]
Unless anyone speaks to the contrary, I'd suggest closing this issue then -- if there are still issues with coverage we can open a new one.

A

**Comment by brettcannon** [comment]
I'm proactively closing this. If any tests fail due to coverage then separate tests per failing test can be opened.
