### ISSUE TITLE
sqlite3 timestamp converter cannot handle timezone

### ISSUE THREAD

**Issue by 5ec79aa0-9d42-4588-818e-392293205e92** [python/cpython#73285]
BPO | [29099](https://bugs.python.org/issue29099)
--- | :---
Nosy | @malemburg, @abalkin, @serhiy-storchaka, @zhangyangyu, @hassanbot
Files | <li>[sqlite3.patch](https://bugs.python.org/file46067/sqlite3.patch "Uploaded as text/plain at 2016-12-28.23:04:29 by bozo.kopic")</li><li>[sqlite3-2.patch](https://bugs.python.org/file46081/sqlite3-2.patch "Uploaded as text/plain at 2016-12-29.17:49:14 by bozo.kopic")</li><li>[sqlite3-2.patch](https://bugs.python.org/file46082/sqlite3-2.patch "Uploaded as text/plain at 2016-12-29.18:21:21 by @serhiy-storchaka"): Regenerated for review</li><li>[sqlite3-3.patch](https://bugs.python.org/file46254/sqlite3-3.patch "Uploaded as text/plain at 2017-01-11.09:21:51 by @zhangyangyu"): Based on -2, addressing comments.</li><li>[timestamptz.patch](https://bugs.python.org/file46265/timestamptz.patch "Uploaded as text/plain at 2017-01-12.05:45:36 by @zhangyangyu")</li><li>[timestamptz-2.patch](https://bugs.python.org/file46277/timestamptz-2.patch "Uploaded as text/plain at 2017-01-13.09:23:56 by @zhangyangyu")</li><li>[timestamptz-3.patch](https://bugs.python.org/file46279/timestamptz-3.patch "Uploaded as text/plain at 2017-01-13.11:23:12 by @zhangyangyu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-28.23:04:29.635>
labels = ['3.8', 'type-feature', 'library']
title = 'sqlite3 timestamp converter cannot handle timezone'
updated_at = <Date 2020-09-18.07:14:50.133>
user = 'https://bugs.python.org/bozokopic'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-18.07:14:50.133>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2016-12-28.23:04:29.635>
creator = 'bozo.kopic'
dependencies = []
files = ['46067', '46081', '46082', '46254', '46265', '46277', '46279']
hgrepos = []
issue_num = 29099
keywords = ['patch']
message_count = 34.0
messages = ['284205', '284231', '284240', '284241', '284243', '284245', '284252', '284291', '284318', '285211', '285227', '285229', '285230', '285231', '285232', '285243', '285245', '285287', '285288', '285289', '285291', '285371', '285372', '285375', '285377', '285381', '285385', '285985', '285989', '285990', '285992', '285993', '377068', '377090']
nosy_count = 7.0
nosy_names = ['lemburg', 'ghaering', 'belopolsky', 'serhiy.storchaka', 'xiang.zhang', 'bozo.kopic', 'hassanbot']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29099'
versions = ['Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
As per [discussion on Discourse](https://discuss.python.org/t/deprecate-default-built-in-sqlite3-converters-and-adapters/15781?u=erlendaasland), we will deprecate the built-in, default adapters and converters. Thus, this issue is now superseded by gh-90016.
