### ISSUE TITLE
unicode_concatenate() optimization is not signal-safe (not atomic)

### ISSUE THREAD

**Issue by 7efd87b8-8087-4d55-bd88-007b82aa3b7f** [python/cpython#73282]
BPO | [29096](https://bugs.python.org/issue29096)
--- | :---
Nosy | @arigo, @llllllllll
Files | <li>[patch2.diff](https://bugs.python.org/file46151/patch2.diff "Uploaded as text/plain at 2017-01-05.07:04:31 by @arigo")</li><li>[patch1.diff](https://bugs.python.org/file46153/patch1.diff "Uploaded as text/plain at 2017-01-05.07:06:58 by @arigo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2016-12-28.20:38:35.674>
labels = ['interpreter-core', '3.7']
title = 'unicode_concatenate() optimization is not signal-safe (not atomic)'
updated_at = <Date 2017-01-05.07:06:58.087>
user = 'https://bugs.python.org/TedMeyer'
```

bugs.python.org fields:
```python
activity = <Date 2017-01-05.07:06:58.087>
actor = 'arigo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2016-12-28.20:38:35.674>
creator = 'Ted Meyer'
dependencies = []
files = ['46151', '46153']
hgrepos = []
issue_num = 29096
keywords = ['patch']
message_count = 4.0
messages = ['284196', '284197', '284198', '284710']
nosy_count = 3.0
nosy_names = ['arigo', 'llllllllll', 'Ted Meyer']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29096'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by graingert** [comment]
The unicode_concatenate function was deleted and the code is now here: https://github.com/python/cpython/blob/d9d5b3d2ef770224b39987dbce7bb5c616fe3477/Python/bytecodes.c#L596-L637

**Comment by graingert** [comment]
This no longer reproduces for me, this only runs in one op-code so there's no way for the signal to show up between opcodes
