### ISSUE TITLE
Implicit namespace packages in Python 3.6

### ISSUE THREAD

**Issue by 559e26c8-6e49-4373-b6ba-a0229f62f8ab** [python/cpython#73330]
BPO | [29144](https://bugs.python.org/issue29144)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericvsmith, @ericsnowcurrently, @stratakis, @torsava, @frenzymadness
Files | <li>[test_namespace_package.sh](https://bugs.python.org/file46129/test_namespace_package.sh "Uploaded as application/x-shellscript at 2017-01-03.18:27:01 by @frenzymadness"): Bash script to reproduce the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-03.18:27:01.746>
labels = ['type-bug']
title = 'Implicit namespace packages in Python 3.6'
updated_at = <Date 2017-07-31.09:09:05.223>
user = 'https://github.com/frenzymadness'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-31.09:09:05.223>
actor = 'frenzy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-01-03.18:27:01.746>
creator = 'frenzy'
dependencies = []
files = ['46129']
hgrepos = []
issue_num = 29144
keywords = ['3.6regression']
message_count = 8.0
messages = ['284587', '290635', '298579', '298624', '298642', '298689', '298703', '299544']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'ncoghlan', 'eric.smith', 'eric.snow', 'cstratak', 'torsava', 'frenzy']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29144'
versions = ['Python 3.6']
```

</p></details>

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
Bumped upon a similar issue today where a package I was working on couldn't import a module from one of its dependencies (which was not the case in python 3.5).

One of the lines that fail is this [0] with:
ModuleNotFoundError: No module named 'repoze.who.\_compat'

And the project that it depends on is this [1]

The projects are old, however what might have caused this behavior change? It seems kinda isolated but that the exact cause has not been pinpointed.

[0] https://github.com/repoze/repoze.who-sqlalchemy/blob/master/tests/databasesetup_elixir.py#L25
[1] https://github.com/repoze/repoze.who/tree/master/repoze/who

**Comment by 559e26c8-6e49-4373-b6ba-a0229f62f8ab** [comment]
Hello.

I've met this issue again in moksha project [0] where namespace package is used.

- module moksha.common is installed via RPM to site-packages and there isn't file moksha/__init__.py so the implicit way to create namespace package is used there.
- moksha.hub module is built in a buildroot and there is moksha/__init__.py file so this module uses different way which causes that import of moksha.common is failing.

We can delete moksha/__init__.py from buildroot of moksha.hub but then we cannot run tests with `python setup.py test`.

Error message is:
error in moksha.hub setup command: Distribution contains no modules or packages for namespace package 'moksha'

The second possibility is ship moksha/__init__.py file in python-moksha-common RPM. The question is: Why there isn't moksha/__init__.py file in RPM even when the source tarball contains it? Because of setuptools!

Setuptools skips installation of \_\_init__.py file when namespace package is recognized with the message:
Skipping installation of /builddir/build/BUILDROOT/python-moksha-common-1.2.5-1.fc27.x86_64/usr/lib/python3.6/site-packages/moksha/__init__.py (namespace package)

Questions summary:
- Why there is such big difference between Python 3.5 and Python 3.6?
- Why does setuptools skip installation of \_\_init__.py file but it needs them to run tests of namespace subpackage?

Thank you!
Lumír

[0] https://github.com/mokshaproject/moksha

**Comment by ncoghlan** [comment]
Are you able to confirm the version of setuptools involved is the same in both cases?

The reason I ask is that the interaction between pkg_resources-style namespace packages and native ones is known to be temperamental (https://packaging.python.org/guides/packaging-namespace-packages/#creating-a-namespace-package), and the suggested resolution is to make sure that if you're using pkg_resources namespaces at all then \*all* packages contributing to the namespace should be using them.

**Comment by 559e26c8-6e49-4373-b6ba-a0229f62f8ab** [comment]
Hello.

I've tried the build of python-moksha-common on Fedora rawhide [0] and Fedora 25 [1].

Fedora rawhide: Python 2.7.13 and 3.6.1, setuptools 36.2.0
Fedora 25: Python 2.7.13 and 3.5.3, setuptools 25.1.1

Source tarball of moksha.common contains pkg_resources-style \_\_init__.py file and the setuptools skipped installation of this file in all (four) cases.

It seems that setuptools do the same in all versions but the problem comes with Python 3.6 which is more strict than Python 3.5 in behavior related to namespace packages.

So, when one part of namespace package doesn't contain \_\_init__.py file and other part contains pkg_resources-style \_\_init__.py file:
- in Python 2.7 and 3.5 everything works
- in Python 3.6 submodules cannot import each other

The question is whether it is a bug/feature in Python 3.6 and setuptools should install pkg_resources-style \_\_init__.py or not.

What do you think?

[0] https://koji.fedoraproject.org/koji/taskinfo?taskID=20606746
[1] https://koji.fedoraproject.org/koji/taskinfo?taskID=20606838

**Comment by brettcannon** [comment]
Without looking into what changed, I say Python 3.6 being more strict in what is a namespace package is reasonable and setuptools needs to be better about installing pkg_resources-using \_\_init__.py files.

**Comment by ncoghlan** [comment]
At the Python level, the rules are simple: the first directory on sys.path that contains an \_\_init__.py file is identified as a self-contained package. It is then up to that \_\_init__.py file to emulate namespace package behaviour (by extending \_\_path__) if that's what the author intended.

Nothing changed in Python 3.6 in terms of that, and it's been that way ever since native namespace packages were introduced.

So if there's a behavioural change in the pkg_resources namespace emulation in going from Python 3.5 to 3.6 that occurs with both old & new versions of setuptools, then I see two main possible candidates for that:

1. Something changed in one of the APIs that setuptools uses to recalculate \_\_path__

2. Something changed in importlib where we're not respecting runtime changes to \_\_path__ properly, and are instead relying on either \_\_spec__.submodule_search_locations or a stale cached version of \_\_path__

Neither of those is something we \*intended* to change in 3.6, so I think it's reasonable to categorise this as 3.6 regression at the standard library level (even though setuptools will likely need to work around it anyway, given the earliest we'll be able to fix it is in 3.6.3)

**Comment by 559e26c8-6e49-4373-b6ba-a0229f62f8ab** [comment]
Thank you for the replies. I created an issue [0] on setuptools GitHub (without reply yet) because I also think that setuptools should install pkg_resources-style \_\_init__.py files.

[0] https://github.com/pypa/setuptools/issues/1097

**Comment by iritkatriel** [comment]
@frenzymadness is there anything left to do here?

**Comment by frenzymadness** [comment]
Thank you for the ping. I don't think there is anything more to do here. Could you please close the issue? I cannot.
