### ISSUE TITLE
sys._enablelegacywindowsfsencoding() don't apply to os.fsencode and os.fsdecode

### ISSUE THREAD

**Issue by 1d2dd152-882b-45e3-9c1e-e6d57cf2072e** [python/cpython#73427]
BPO | [29241](https://bugs.python.org/issue29241)
--- | :---
Nosy | @malemburg, @pfmoore, @vstinner, @tjguk, @methane, @zware, @zooba, @JGoutin, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-11.12:28:01.427>
labels = ['type-bug', '3.7', 'OS-windows']
title = "sys._enablelegacywindowsfsencoding() don't apply to os.fsencode and os.fsdecode"
updated_at = <Date 2022-01-17.01:40:59.439>
user = 'https://github.com/JGoutin'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-17.01:40:59.439>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2017-01-11.12:28:01.427>
creator = 'JGoutin'
dependencies = []
files = []
hgrepos = []
issue_num = 29241
keywords = []
message_count = 18.0
messages = ['285220', '285238', '285290', '285354', '285374', '285393', '285398', '285421', '285423', '285424', '285429', '285888', '285969', '285975', '285979', '312378', '410719', '410738']
nosy_count = 9.0
nosy_names = ['lemburg', 'paul.moore', 'vstinner', 'tim.golden', 'methane', 'zach.ware', 'steve.dower', 'JGoutin', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29241'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-107729

**Comment by methane** [comment]
Mercurial was affected by this bug.
@indygreg fixed this bug by replacing `os.fsencode()` with `a.encode("mbcs", "ignore")`.

https://repo.mercurial-scm.org/hg/rev/00e0c5c06ed5

Now I am strong +1 to deprecate `_enablelegacywindowsfsencoding`.
Since Python 3.12 is now beta, document only deprecation for 3.12, and emit DeprecatedWarning from Python 3.13.

**Comment by vstinner** [comment]
IMO it's time to deprecate it since https://peps.python.org/pep-0686/ got approved for Python 3.15. As you can see, supporting other encodings than UTF-8 remains complicated and is less tested. For me, this legacy encoding was supposed to be a temporary thing to ease the  Python on Windows migration to UTF-8.

**Comment by vstinner** [comment]
I wrote an article about PEP 529: https://vstinner.github.io/python36-utf8-windows.html

**Comment by vstinner** [comment]
This issue can be fixed by adding a private os._update_fs_encoding() function which would update fsencode(), fsdecode(), and os.environ functions. sys._enablelegacyfsencoding() would call it if os is cached in sys.modules. Something like that.

**Comment by methane** [comment]
We can not fix every possible cached fsencoding, and paths already encoded in utf-8.
If Mercurail can use PYTHONLEGACYWINDOWSFSENCODING instead of `_enablelegacywindowsfsencoding`, no need to fix/keep it.

**Comment by vstinner** [comment]
Every attempt to change the filesystem encoding at runtime was a big failure: https://vstinner.github.io/painful-history-python-filesystem-encoding.html

I already proposed to deprecate sys._enablelegacywindowsfsencoding() some years ago, but apparently it was too early.

**Comment by zooba** [comment]
> I already proposed to deprecate sys._enablelegacywindowsfsencoding() some years ago, but apparently it was too early.

I don't remember your proposal, but it was always meant to be deprecated. Just never actually seemed important enough to do it.

Fixing this would require making `fsencode` and `fsdecode` less efficient for everyone, all the time. I don't think it's worth it.

**Comment by methane** [comment]
Almost only user of legacywindowsfsencoding is Mercurial. So we need help from Mercurial developer...

**Comment by methane** [comment]
Since there is no reply from Mercurial developers, I merged the deprecation of `_enablelegacywindowsfsencoding`.
Can we close this issue as "won't fix"?

**Comment by zooba** [comment]
Sounds good to me
