### ISSUE TITLE
Support recursive wildcards in pathlib.PurePath.match()

### ISSUE THREAD

**Issue by 93e0a5b0-4ee0-4d83-8772-6b2247e3fb5c** [python/cpython#73435]
BPO | [29249](https://bugs.python.org/issue29249)
--- | :---
Nosy | @pitrou, @RonnyPfannschmidt, @serhiy-storchaka, @wimglenn, @JulienPalard, @virtuald, @andunai, @barneygale, @eumiro

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-12.10:19:54.004>
labels = ['3.8', 'type-feature', '3.7', '3.9', 'docs']
title = 'Pathlib glob ** bug'
updated_at = <Date 2021-06-04.19:42:17.687>
user = 'https://bugs.python.org/JonWalsh'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-04.19:42:17.687>
actor = 'christian.heimes'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-01-12.10:19:54.004>
creator = 'Jon Walsh'
dependencies = []
files = []
hgrepos = []
issue_num = 29249
keywords = []
message_count = 11.0
messages = ['285297', '285305', '285308', '285311', '285323', '307854', '307866', '325735', '361147', '382535', '386795']
nosy_count = 12.0
nosy_names = ['pitrou', 'docs@python', 'Ronny.Pfannschmidt', 'serhiy.storchaka', 'wim.glenn', 'mdk', 'virtuald', 'Jon Walsh', 'Andrew Dunai', 'Isaac Muse', 'barneygale', 'eumiro']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29249'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-101398
* gh-114350

**Comment by barneygale** [comment]
I have a PR that implements this (pending another fix), but it doesn't support newlines in filenames or patterns. Is that any use, or should I try to work up a version that supports embedded newlines too? #101398

**Comment by barneygale** [comment]
I've fixed support for newlines in my patch. I believe these two PRs will resolve this issue:

- #101363
- #101398 

Would a core dev be willing to review, please? Thanks!

**Comment by barneygale** [comment]
First PR has landed. This one is now ready:

- #101398

It also makes `match()` about 10x faster in some cases!

**Comment by barneygale** [comment]
Thanks for your patience all. This is now implemented in [49f90ba](https://github.com/python/cpython/commit/49f90ba1eae56708b1894441418c13ad8e8ea9a8) / #101398, and will become available in Python 3.13!

**Comment by barneygale** [comment]
Re-opening. I'm beginning to think that the implied `**/` prefix limits the usefulness of this method, as it makes it impossible to match relative paths from the left hand side, and makes it subtly incompatible with `glob()`.

I'm going to put up a PR that reverts `match()` back to 3.12 behaviour, and instead adds a `globmatch()` method.

**Comment by barneygale** [comment]
Re-resolving. This is now implemented as [`PurePath.full_match()`](https://docs.python.org/3.13/library/pathlib.html#pathlib.PurePath.full_match)
