### ISSUE TITLE
os.cpu_count is problematic on sparc/solaris

### ISSUE THREAD

**Issue by a46f81ef-bc6c-413a-8ccc-52ad6e96ebc1** [python/cpython#73451]
BPO | [29265](https://bugs.python.org/issue29265)
--- | :---
Nosy | @vstinner, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-13.17:48:34.324>
labels = ['type-bug', 'library']
title = 'os.cpu_count is problematic on sparc/solaris'
updated_at = <Date 2017-01-13.22:28:44.539>
user = 'https://bugs.python.org/phantal'
```

bugs.python.org fields:
```python
activity = <Date 2017-01-13.22:28:44.539>
actor = 'phantal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-01-13.17:48:34.324>
creator = 'phantal'
dependencies = []
files = []
hgrepos = []
issue_num = 29265
keywords = []
message_count = 5.0
messages = ['285430', '285431', '285432', '285441', '285446']
nosy_count = 3.0
nosy_names = ['vstinner', 'r.david.murray', 'phantal']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29265'
versions = ['Python 3.6']
```

</p></details>

**Comment by kulikjak** [comment]
As per the current documentation, `os.cpu_count()` should return _"number of logical CPUs in the system"_, and so returning 256 on a 32 core machine with 8 threads is correct.

We've previously hit the issue of hitting the cap on max open file handles as well and solved it by running the test suite with `ulimit -n 16384`.

**Comment by vstinner** [comment]
> os.cpu_count is problematic on sparc/solaris

The issue title is misleading. os.cpu_count() is correct. The problem is more that the default file descriptor is too low for a machine with 256 logical CPUs ("threads") when running `./python -m test -j0` which spawns `os.process_cpu_count() + 2` worker processes.

You can specify the number of worker processes: `./python -m test -j20`, or you can increase the file descriptor limit.

Is there anything to do on the Python side? Should regrtest limit the number of worker processes based on the current file descriptor limit? I have no idea how to compute a number of processes based on a maximum number of file descriptors.

**Comment by vstinner** [comment]
The bare minimum which can be easily done is to emit a warning if the FD limit looks too small compared to the -jN argument. Maybe with instructions on how to fix the issue (reduce -jN value or increase FD limit).

**Comment by kulikjak** [comment]
That is true. In our case, IIRC, we saw occasional issues when building with fd limit of 4096 with 514 worker processes. So I'd propose warning the user when the fd limit is less than 10 times the worker count?

**Comment by vstinner** [comment]
On Linux, the default FD limit is 1024 but I never got such issue. Well, my laptop "only" has 12 logical CPUs. Which process is impacted by the issue? The main process which spawns and manages the 514 worker processes? Does Python even need a single FD for worker process?

**Comment by kulikjak** [comment]
Sorry for such a long delay.

I looked into this and apparently it wasn't the test suite, but pgo phase when this was an issue (back when pgo was running the entire test suite). Also, it seems that back then the default limit on our build machines might have been lower.

Anyway, when I change the limit a lot all the way to 512 and run the test suite, I see the following error:

```
Warning -- regrtest worker thread failed: Traceback (most recent call last):
  File "/builds/python37/Python-3.7.17/Lib/test/libregrtest/runtest_mp.py", line 284, in run
    mp_result = self._runtest(test_name)
  File "/builds/python37/Python-3.7.17/Lib/test/libregrtest/runtest_mp.py", line 249, in _runtest
    retcode, stdout, stderr = self._run_process(test_name)
  File "/builds/python37/Python-3.7.17/Lib/test/libregrtest/runtest_mp.py", line 194, in _run_process
    popen = run_test_in_subprocess(test_name, self.ns)
  File "/builds/python37/Python-3.7.17/Lib/test/libregrtest/runtest_mp.py", line 74, in run_test_in_subprocess
    **kw)
  File "/builds/python37/Python-3.7.17/Lib/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/builds/python37/Python-3.7.17/Lib/subprocess.py", line 1457, in _execute_child
    errpipe_read, errpipe_write = os.pipe()
OSError: [Errno 24] Too many open files

Kill <TestWorkerProcess #1 running test=test_support pid=44123 time=8.7 sec> process group
Kill <TestWorkerProcess #2 running test=test_fork1 pid=44801 time=4.4 sec> process group
...
Kill <TestWorkerProcess #175 running test=test_pickletools pid=45171 time=2.3 sec> process group
0:00:14 load avg: 33.55 Waiting for <TestWorkerProcess #95 running test=test_posix pid=45022 time=4.5 sec> thread for 1.1 sec

== Tests result: FAILURE ==
```
which looks like the main process, but I guess that e.g. subprocess tests might fail as well?

**Comment by encukou** [comment]
SPARC/Solaris is unsupported per PEP-11.

I'll close the bug.
Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back.
I encourage such people to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping.
