### ISSUE TITLE
Fused multiply-add: proposal to add math.fma()

### ISSUE THREAD

**Issue by d53266d1-005f-41a4-9f68-6ba663f9bdf2** [python/cpython#73468]
BPO | [29282](https://bugs.python.org/issue29282)
--- | :---
Nosy | @mdickinson, @pitrou, @vstinner, @stevendaprano, @skrah, @nschloe, @serhiy-storchaka, @efahl, @cdonovick
PRs | <li>python/cpython#17987</li>
Files | <li>[xmathmodule.c](https://bugs.python.org/file46298/xmathmodule.c "Uploaded as text/plain at 2017-01-16.10:02:24 by juraj.sukop")</li><li>[example.py](https://bugs.python.org/file46299/example.py "Uploaded as text/plain at 2017-01-16.10:02:37 by juraj.sukop")</li><li>[setup.py](https://bugs.python.org/file46300/setup.py "Uploaded as text/plain at 2017-01-16.10:02:45 by juraj.sukop")</li><li>[fma_reference.py](https://bugs.python.org/file46304/fma_reference.py "Uploaded as text/plain at 2017-01-16.19:04:11 by @mdickinson")</li><li>[math_fma.patch](https://bugs.python.org/file46321/math_fma.patch "Uploaded as text/plain at 2017-01-17.21:02:45 by @mdickinson")</li><li>[math_fma2.patch](https://bugs.python.org/file46345/math_fma2.patch "Uploaded as text/plain at 2017-01-19.19:46:15 by @mdickinson")</li><li>[math_fma3.patch](https://bugs.python.org/file46346/math_fma3.patch "Uploaded as text/plain at 2017-01-19.20:03:33 by @mdickinson")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-16.10:01:37.166>
labels = ['3.7', 'type-feature', 'library']
title = 'Fused multiply-add: proposal to add math.fma()'
updated_at = <Date 2021-06-19.09:24:45.622>
user = 'https://bugs.python.org/jurajsukop'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-19.09:24:45.622>
actor = 'mark.dickinson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-01-16.10:01:37.166>
creator = 'juraj.sukop'
dependencies = []
files = ['46298', '46299', '46300', '46304', '46321', '46345', '46346']
hgrepos = []
issue_num = 29282
keywords = ['patch']
message_count = 36.0
messages = ['285547', '285549', '285550', '285551', '285552', '285553', '285557', '285564', '285565', '285566', '285582', '285682', '285685', '285836', '285837', '285839', '285840', '285841', '285843', '285844', '285955', '285956', '285957', '285958', '285959', '286201', '312431', '312432', '312433', '312480', '312488', '359903', '359911', '359913', '359921', '359926']
nosy_count = 11.0
nosy_names = ['mark.dickinson', 'pitrou', 'vstinner', 'steven.daprano', 'skrah', 'nschloe', 'python-dev', 'serhiy.storchaka', 'eric.fahlgren', 'juraj.sukop', 'donovick']
pr_nums = ['17987']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29282'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-116667

**Comment by tannergooding** [comment]
It's worth noting that if you want a performant and open source implementation, you have:
* The official AMD's implementation: https://github.com/amd/aocl-libm-ose/blob/master/src/isa/avx/fmaf.c
  * In plain C, portable, no intrinsics
  * BSD 3-Clause
* The Berkeley SoftFloat implementation: https://github.com/ucb-bar/berkeley-softfloat-3/blob/master/source/s_mulAddF32.c
  * In plain C, portable, no intrinsics
  * Not as well optimized

I believe there is also one available from netlib, but I don't have that link handy. Arm typically has algorithms available on its repository, but doesn't provide one for `fma` because all Arm64 based hardware provide an `fma` instruction natively: https://github.com/ARM-software/optimized-routines

**Comment by clairvoyante** [comment]
@tannergooding double(64bits float) version is desired, maybe :
https://github.com/amd/aocl-libm-ose/blob/master/src/isa/avx/fma.c
https://github.com/ucb-bar/berkeley-softfloat-3/blob/master/source/s_mulAddF64.c

**Comment by tannergooding** [comment]
Yes, if you want the 64-bit (`double`) versions they exist in neighboring files. Notably doing something like `(float)fma((double)x, (double)y, (double)z)` may not be sufficient in all cases if you want a 32-bit (`float`) result. There is a subset of operations for which the rounding twice is known to be a non-issue, but I don't recall off the top of my head if `fma` is included in that, so it may be desirable to have both (and there may even be a performance difference).

**Comment by vstinner** [comment]
My previous attempt in 2020 failed. I try again in 2024: PR https://github.com/python/cpython/pull/116667

**Comment by vstinner** [comment]
Function added by commit https://github.com/python/cpython/commit/8e3c953b3acd7c656f66696806c9ae917e816492. I only took 7 years only Linux, macOS and Windows get a good support of fma() :-)
