### ISSUE TITLE
httplib: wrong Host header when connecting to IPv6 link-local address

### ISSUE THREAD

**Issue by ea99edd8-57bd-49ef-ad59-30f5d1a2675e** [python/cpython#73561]
BPO | [29375](https://bugs.python.org/issue29375)
--- | :---
Nosy | @gpshead, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-01-25.20:14:44.074>
labels = ['3.7', 'type-bug', 'library']
title = 'httplib: wrong Host header when connecting to IPv6 link-local address'
updated_at = <Date 2017-01-26.21:13:35.139>
user = 'https://bugs.python.org/JonathanGuthrie'
```

bugs.python.org fields:
```python
activity = <Date 2017-01-26.21:13:35.139>
actor = 'JonathanGuthrie'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-01-25.20:14:44.074>
creator = 'JonathanGuthrie'
dependencies = []
files = []
hgrepos = []
issue_num = 29375
keywords = []
message_count = 3.0
messages = ['286276', '286286', '286333']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'martin.panter', 'JonathanGuthrie']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29375'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-93324

**Comment by mib1185** [comment]
Hi,
according to the [dev-guid - reviewing](https://devguide.python.org/getting-started/pull-request-lifecycle/#reviewing), i would like to "ping" this issue.
Do you mind to have a look into the linked PR? Unfortunately it is without a review since more than a year, but it is a quite small PR to fix this issue.
thx

**Comment by mib1185** [comment]
Hi,
according to the [dev-guid - reviewing](https://devguide.python.org/getting-started/pull-request-lifecycle/#reviewing), i would like to "ping" this issue.
Do you mind to have a look into the linked PR?
thx
