### ISSUE TITLE
Backport Travis configuration

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#73715]
BPO | [29529](https://bugs.python.org/issue29529)
--- | :---
Nosy | @brettcannon, @ncoghlan, @methane
PRs | <li>python/cpython#25</li><li>python/cpython#26</li><li>python/cpython#27</li>
Dependencies | <li>bpo-29528: Encrypt IRC channel details for Travis</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brettcannon'
closed_at = <Date 2017-02-20.10:21:23.393>
created_at = <Date 2017-02-10.23:59:00.442>
labels = []
title = 'Backport Travis configuration'
updated_at = <Date 2017-02-20.10:21:23.392>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-20.10:21:23.392>
actor = 'methane'
assignee = 'brett.cannon'
closed = True
closed_date = <Date 2017-02-20.10:21:23.393>
closer = 'methane'
components = []
creation = <Date 2017-02-10.23:59:00.442>
creator = 'brett.cannon'
dependencies = ['29528']
files = []
hgrepos = []
issue_num = 29529
keywords = []
message_count = 5.0
messages = ['287576', '287627', '288104', '288106', '288173']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'ncoghlan', 'methane']
pr_nums = ['25', '26', '27']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29529'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by brettcannon** [comment]
Once the Travis config stabilizes then it should be backported to all active branches.

**Comment by brettcannon** [comment]
https://github.com/python/core-workflow/issues/19 should be decided upon before backporting anything.

**Comment by ncoghlan** [comment]
New changeset 3337d33a4518f7ab8a7ab6c9a75b8b92ba348b27 by Nick Coghlan in branch '3.6':
[backport to 3.6] bpo-29529: Add .travis.yml to 3.6 branch (#25)
https://github.com/python/cpython/commit/3337d33a4518f7ab8a7ab6c9a75b8b92ba348b27

**Comment by ncoghlan** [comment]
New changeset 24bfe15e83c24bf2c2e2654050da809553789002 by Nick Coghlan in branch '3.5':
[backport to 3.5] bpo-29529: Add .travis.yml to 3.5 branch (#26)
https://github.com/python/cpython/commit/24bfe15e83c24bf2c2e2654050da809553789002

**Comment by methane** [comment]
New changeset 98604c7683f41f04c633935bb582399c50db838c by GitHub in branch '2.7':
bpo-29529: Add .travis.yml to 2.7 branch (GH-27)
https://github.com/python/cpython/commit/98604c7683f41f04c633935bb582399c50db838c
