### ISSUE TITLE
Encrypt IRC channel details for Travis

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#73714]
BPO | [29528](https://bugs.python.org/issue29528)
--- | :---
Nosy | @brettcannon, @vstinner, @bitdancer, @zware, @dstufft
PRs | <li>python/cpython#13</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-11.04:05:00.203>
created_at = <Date 2017-02-10.23:58:09.745>
labels = []
title = 'Encrypt IRC channel details for Travis'
updated_at = <Date 2017-03-25.00:55:00.358>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-25.00:55:00.358>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-11.04:05:00.203>
closer = 'zach.ware'
components = []
creation = <Date 2017-02-10.23:58:09.745>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 29528
keywords = []
message_count = 3.0
messages = ['287575', '287591', '290455']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'vstinner', 'r.david.murray', 'zach.ware', 'dstufft']
pr_nums = ['13']
priority = 'high'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29528'
versions = []
```

</p></details>

**Comment by brettcannon** [comment]
Donald pointed out on IRC we should encrypt a channel key for IRC so that it doesn't get flooded from people's forks. See https://docs.travis-ci.com/user/notifications#Channel-key for documentation on how to do this.

**Comment by zware** [comment]
Fixed in [PR13](https://github.com/python/cpython/pull/13).

**Comment by vstinner** [comment]
New changeset 4538ddcacc8e8f00d5d36d7bc84e551a56ce6da2 by Victor Stinner (Donald Stufft) in branch 'master':
Fix bpo-29528 Use a secure variable to stop spam (#13)
https://github.com/python/cpython/commit/4538ddcacc8e8f00d5d36d7bc84e551a56ce6da2
