### ISSUE TITLE
functools.partial is not compatible between 2.7 and 3.5

### ISSUE THREAD

**Issue by e91ea210-bcce-436c-a9f7-dfe96635cc0d** [python/cpython#73718]
BPO | [29532](https://bugs.python.org/issue29532)
--- | :---
Nosy | @rhettinger, @stevendaprano, @methane, @serhiy-storchaka, @naoyuki-kamo
PRs | <li>python/cpython#190</li><li>python/cpython#198</li><li>python/cpython#209</li><li>python/cpython#222</li><li>python/cpython#703</li><li>python/cpython#552</li>
Files | <li>[partial-copy-kwargs.patch](https://bugs.python.org/file46633/partial-copy-kwargs.patch "Uploaded as text/plain at 2017-02-11.11:10:12 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-22.09:53:25.891>
created_at = <Date 2017-02-11.07:20:01.590>
labels = ['3.7', 'type-bug', 'library']
title = 'functools.partial is not compatible between 2.7 and 3.5'
updated_at = <Date 2017-03-31.16:36:21.417>
user = 'https://github.com/naoyuki-kamo'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:21.417>
actor = 'dstufft'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-22.09:53:25.891>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-02-11.07:20:01.590>
creator = 'naoyuki'
dependencies = []
files = ['46633']
hgrepos = []
issue_num = 29532
keywords = ['patch']
message_count = 8.0
messages = ['287594', '287595', '287598', '287673', '287832', '288197', '288309', '288347']
nosy_count = 5.0
nosy_names = ['rhettinger', 'steven.daprano', 'methane', 'serhiy.storchaka', 'naoyuki']
pr_nums = ['190', '198', '209', '222', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29532'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by e91ea210-bcce-436c-a9f7-dfe96635cc0d** [comment]
The code:
from functools import partial
def f(a):
    print(a)
d = {'a': 3}
g = partial(f, \*\*d)
g()
d['a'] = 5 
g()

On python2.7, gets
3
but on python3.5, gets
5

is it a bug?

**Comment by stevendaprano** [comment]
Confirmed that in Python 2.7 calling g() before and after modifying the dict prints 3 both times; calling g() before modifying the dict prints 3, then after modifying it prints 5.

Python 3.3 behaves like 2.7, so this sounds like a regression in 3.5 or maybe 3.4.

**Comment by serhiy-storchaka** [comment]
Yes, this can be considered a bug. Following patch fixes it.

**Comment by methane** [comment]
patch LGTM.

**Comment by rhettinger** [comment]
Agree that this is a bug.  Patch and test looks good.

**Comment by serhiy-storchaka** [comment]
New changeset 9639e4ab6d5bd3ca0ab34fef127e9fc84b6b88b9 by GitHub in branch 'master':
bpo-29532: Altering a kwarg dictionary passed to functools.partial() (#190)
https://github.com/python/cpython/commit/9639e4ab6d5bd3ca0ab34fef127e9fc84b6b88b9

**Comment by serhiy-storchaka** [comment]
New changeset e48fd93bbb36c6d80aa4eb6af09f58c69d8cf965 by GitHub in branch '3.6':
bpo-29532: Altering a kwarg dictionary passed to functools.partial() no longer affects a partial object after creation. (#209)
https://github.com/python/cpython/commit/e48fd93bbb36c6d80aa4eb6af09f58c69d8cf965

**Comment by serhiy-storchaka** [comment]
New changeset 5010a77a4da76d8d3fd861a63a7f1ce8f0e9c520 by GitHub in branch '3.5':
[3.5] bpo-29532: Altering a kwarg dictionary passed to functools.partial() no longer affects a partial object after creation. (#222)
https://github.com/python/cpython/commit/5010a77a4da76d8d3fd861a63a7f1ce8f0e9c520
