### ISSUE TITLE
Python 2.7.13 for Windows broken (from prompt)

### ISSUE THREAD

**Issue by 403afa69-b8de-45b7-8fcb-deff770245ed** [python/cpython#73711]
BPO | [29525](https://bugs.python.org/issue29525)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-18.21:01:33.724>
created_at = <Date 2017-02-10.13:28:11.620>
labels = ['invalid', 'OS-windows', 'type-crash']
title = 'Python 2.7.13 for Windows broken (from prompt)'
updated_at = <Date 2017-02-18.21:01:33.723>
user = 'https://bugs.python.org/FrakN'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-18.21:01:33.723>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-18.21:01:33.724>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-02-10.13:28:11.620>
creator = 'Frak N'
dependencies = []
files = []
hgrepos = []
issue_num = 29525
keywords = []
message_count = 8.0
messages = ['287532', '287533', '287540', '287577', '287578', '287589', '287684', '288091']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Frak N']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue29525'
versions = ['Python 2.7']
```

</p></details>

**Comment by 403afa69-b8de-45b7-8fcb-deff770245ed** [comment]
I used to have an older version of python 2.7 that has worked for years. I just upgraded to 2.7.13 for Windows, 32 bit and now, I can't get the interpreter to run from the command line. It just returns to the DOS prompt.

c:\\Python27\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
c:\\Python27\>python

PC:
OS: Windows 7 - 64 bit (I am intentionally using the 32bit of python)
Processor: AMD PhenomII 975 Processor. 3.6GHz
RAM: 16GB

**Comment by tjguk** [comment]
Although I don't remember seeing a crash out as quick as this, common 
causes for this kind of thing are to do with environment variables 
pointing to still-existing or part-existing installations. Can you try:

set PY

from a command prompt, please, to see if any Python-related env vars are 
present. (Typically PYTHONHOME is the culprit)

**Comment by zooba** [comment]
Readline is also a common culprit when it's crashing out at the interactive prompt. Try either uninstalling or upgrading any packages that may include a readline module.

**Comment by 403afa69-b8de-45b7-8fcb-deff770245ed** [comment]
c:\\Python27\>SET PY
Environment variable PY not defined


I don't know anything about readline or how to find what uses it.

**Comment by vstinner** [comment]
To get more information during the Python initialization, you can try to run:

python -X faulthandler -S -v

* -X faulthandler: dump a traceback if python crashed (is it the case? I don't understand from the bug report)
* -S disables the site module
* -v enables verbose mode

**Comment by eryksun** [comment]
It doesn't appear to be a crash, but seems like the REPL is quitting because there's no input (e.g. like stdin is redirected to NUL). Echo %errorlevel%; it's probably 0. 

readline (pyreadline) is probably the culprit. Try the following shell commands to temporarily disable it:

    ren C:\Python27\Lib\site-packages\readline.py readline.py.bak
    del C:\Python27\Lib\site-packages\readline.pyc

If it's not installed, then these commands will fail.

**Comment by 403afa69-b8de-45b7-8fcb-deff770245ed** [comment]
Excellent analysis guys! Thank you!

The -X faulthandler option didn't work.
The -S -v, however, did. 
Finally, renaming and deleting the readline entries fixed it such that I can now launch the REPL. 
Question. What does " disables the site module" for the -S option mean?

Now, what do I do about the (py)readline issue? Do I need to reinstall something?

Logs below:


c:\\Python27\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

c:\\Python27\>python -X faulthandler -S -v
-X is reserved for implementation-specific arguments
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try \`python -h' for more information.

c:\\Python27\>python -X
-X is reserved for implementation-specific arguments
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try \`python -h' for more information.

c:\\Python27\>python -X -faulthandler -S -v
-X is reserved for implementation-specific arguments
usage: python [option] ... [-c cmd | -m mod | file | -] [arg] ...
Try \`python -h' for more information.

```pycon
c:\Python27>python  -S -v
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
>>> ^Z
```


\# clear \_\_builtin__._
\# clear sys.path
\# clear sys.argv
\# clear sys.ps1
\# clear sys.ps2
\# clear sys.exitfunc
\# clear sys.exc_type
\# clear sys.exc_value
\# clear sys.exc_traceback
\# clear sys.last_type
\# clear sys.last_value
\# clear sys.last_traceback
\# clear sys.path_hooks
\# clear sys.path_importer_cache
\# clear sys.meta_path
\# clear sys.flags
\# clear sys.float_info
\# restore sys.stdin
\# restore sys.stdout
\# restore sys.stderr
\# cleanup \_\_main__
\# cleanup[1] zipimport
\# cleanup[1] signal
\# cleanup[1] exceptions
\# cleanup[1] \_warnings
\# cleanup sys
\# cleanup \_\_builtin__
\# cleanup ints: 6 unfreed ints
\# cleanup floats

c:\\Python27\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

c:\\Python27\>ren C:\\Python27\\Lib\\site-packages\\readline.py readline.py.bak

c:\\Python27\>del C:\\Python27\\Lib\\site-packages\\readline.pyc

c:\\Python27\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>\>\>

**Comment by zooba** [comment]
You should be able to update whatever package installed that module. Unfortunately, we can't guess what that would be, but it's probably worthwhile updating all the packages you have installed.
