### ISSUE TITLE
Travis: doc job is broken

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73713]
BPO | [29527](https://bugs.python.org/issue29527)
--- | :---
Nosy | @brettcannon, @vstinner, @zware, @refi64
PRs | <li>python/cpython#16</li><li>python/cpython#7</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-12.21:55:17.682>
created_at = <Date 2017-02-10.23:49:33.905>
labels = ['3.7', 'tests']
title = 'Travis: doc job is broken'
updated_at = <Date 2017-03-25.00:56:35.754>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-25.00:56:35.754>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-12.21:55:17.682>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-02-10.23:49:33.905>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29527
keywords = []
message_count = 8.0
messages = ['287573', '287574', '287579', '287586', '287617', '287629', '287655', '290456']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'vstinner', 'zach.ware', 'refi64']
pr_nums = ['16', '7']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29527'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
I suggest to disable the job until it's fixed, just to fix Travis right now. This issue will track the bug to find a solution.

https://travis-ci.org/python/cpython/jobs/200517775

```sh
$ make html SPHINXBUILD="./venv/bin/python3 -m sphinx" SPHINXOPTS="-nW -q -b linkcheck"
./venv/bin/python3 -m sphinx -b html -d build/doctrees -D latex_paper_size= -nW -q -b linkcheck . build/html 
```


Warning, treated as error:
WARNING: latex_preamble is deprecated. Use latex_elements['preamble'] instead.

make: *** [build] Error 1

**Comment by brettcannon** [comment]
What would it take to simply fix the docs?

And we shouldn't disable the check entirely if fixing it is difficult, but instead just let warnings be warnings until we fix all warnings and then make them be errors again.

**Comment by vstinner** [comment]
> And we shouldn't disable the check entirely if fixing it is difficult, but instead just let warnings be warnings until we fix all warnings and then make them be errors again.

Ok, I changed my change (I got the same proposal in the PR). So I removed -W option:
https://github.com/python/cpython/commit/0d5f11061a873e9fb67ae59e46b3313e5ba22fc3

**Comment by 6c71e414-5f93-49b5-bb0f-c482d8783102** [comment]
Trying to fix this in https://github.com/python/cpython/pull/9...but...

Currently there are approx \*pause for effect* 6,245 warnings!

Out of those, around 6,243 are 'reference target not found' warnings, spanning over 290 files:


/media/ryan/stuff/cpython/Doc/whatsnew/3.7.rst:121: WARNING: c:member reference target not found: doc
/media/ryan/stuff/cpython/Doc/whatsnew/3.7.rst:121: WARNING: c:type reference target not found: PyGetSetDef
/media/ryan/stuff/cpython/Doc/whatsnew/3.7.rst:121: WARNING: c:type reference target not found: wrapperbase
/media/ryan/stuff/cpython/Doc/whatsnew/3.7.rst:157: WARNING: py:mod reference target not found: ntpath
../../Misc/NEWS:348: WARNING: py:data reference target not found: socket.TCP_CONGESTION
../../Misc/NEWS:348: WARNING: py:data reference target not found: socket.TCP_USER_TIMEOUT
../../Misc/NEWS:1005: WARNING: py:data reference target not found: socket.TCP_CONGESTION
../../Misc/NEWS:1005: WARNING: py:data reference target not found: socket.TCP_USER_TIMEOUT
../../Misc/NEWS:2718: WARNING: py:obj reference target not found: idlelib/*.py
../../Misc/NEWS:2718: WARNING: py:obj reference target not found: idle_test/test_*.py
../../Misc/NEWS:2837: WARNING: c:func reference target not found: malloc
../../Misc/NEWS:2883: WARNING: c:func reference target not found: PyObject_Malloc


For some reason, I don't feel like fixing 6,200 warnings is really feasible (or at least for me), so would it be worth it to, in the mean time, disable this specific kind of warning, at least for the CI builds?

**Comment by brettcannon** [comment]
It really depends on why the warnings are there. If it's a configuration issue with how [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is being built then that can be fixed to deal with a lot of warnings upfront. Otherwise we can also strip out the references from [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) to deal with the warnings.

**Comment by zware** [comment]
[PR16](https://github.com/python/cpython/pull/16) made the Travis build situation better, but we still have some warnings to look into.  I thought we had a PR for that, but I can't seem to find it.

**Comment by vstinner** [comment]
I see that Travis CI now compiles the doc to HTML, there is a single warning and the doc works. So I close the issue. Thanks!

If you want to upgrade Sphinx, fix more warnings, etc. : please open new more specific issues for these tasks.

**Comment by vstinner** [comment]
New changeset 0d5f11061a873e9fb67ae59e46b3313e5ba22fc3 by Victor Stinner in branch 'master':
Don't treat warnings as error in Travis docs job (#7)
https://github.com/python/cpython/commit/0d5f11061a873e9fb67ae59e46b3313e5ba22fc3
