### ISSUE TITLE
Python3 error while building on Alt-F

### ISSUE THREAD

**Issue by 9c22f19a-4770-4526-9ac3-39abe0b74599** [python/cpython#73727]
BPO | [29541](https://bugs.python.org/issue29541)
--- | :---
Nosy | @vadmium, @iritkatriel
Files | <li>[build.log](https://bugs.python.org/file46636/build.log "Uploaded as text/plain at 2017-02-13.07:52:07 by Honza Skýpala"): Log from build process</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-21.17:32:40.446>
created_at = <Date 2017-02-13.07:52:21.820>
labels = ['build']
title = 'Python3 error while building on Alt-F'
updated_at = <Date 2022-01-21.17:32:40.445>
user = 'https://bugs.python.org/HonzaSkpala'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-21.17:32:40.445>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-21.17:32:40.446>
closer = 'iritkatriel'
components = ['Build']
creation = <Date 2017-02-13.07:52:21.820>
creator = 'Honza Sk\xc3\xbdpala'
dependencies = []
files = ['46636']
hgrepos = []
issue_num = 29541
keywords = []
message_count = 7.0
messages = ['287666', '287667', '287669', '287690', '287723', '330879', '411157']
nosy_count = 3.0
nosy_names = ['martin.panter', 'Honza Sk\xc3\xbdpala', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29541'
versions = ['Python 3.6']
```

</p></details>

**Comment by 9c22f19a-4770-4526-9ac3-39abe0b74599** [comment]
While trying to build Python 3.6.0 on emmbedded Linux device — D-Link DNS-320L running Alt-F firmware (Linux 3.18.28 #1 Fri Jun 17 14:44:39 WEST 2016 armv5tel GNU/Linux), it fails with

./python: can't resolve symbol 'crypt'
make: *** [sharedmods] Error 1

I can see the python executable is compiled fine in the source directory, if I try to run it, then it does work, including some quick tests (calculations, os.getcwd, random.randint -- works fine). 

I can also see that compiling the crypt modules did not report any errors and the .o file is present on the disk. I guess it is some kind of linking error?

Attaching the log from the build.

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
My patch at https://hg.python.org/cpython/rev/ca2f024ce7cb may help. It points out missing symbols earlier.

**Comment by 9c22f19a-4770-4526-9ac3-39abe0b74599** [comment]
Hi Chi Hsuan Yen, thanks for trying to help, unfortunately no change, still getting the same error.

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
That's super strange. crypt() is used in \_crypt module only, and this modules is not used elsewhere in Python. A few more tests may help diagnostics

1. What's the result of ```./python -E```?
2. Does `import crypt` run fine in ./python?
3. Are there pre-installed Python on Alt-F? Uninstall them first may help
4. Is there a symbol called crypt in `nm ./python`?

**Comment by 9c22f19a-4770-4526-9ac3-39abe0b74599** [comment]
1. What's the result of ```./python -E```?

Python 3.6.0 (default, Feb 13 2017, 08:16:44)
[GCC 4.5.4 20120202 (prerelease)] on linux
Type "help", "copyright", "credits" or "license" for more information.

2. Does `import crypt` run fine in ./python?

No, gives the error
./python: can't resolve symbol 'crypt'

3. Are there pre-installed Python on Alt-F? Uninstall them first may help

No, there is no python preinstalled (no python3, not even python2)

4. Is there a symbol called crypt in `nm ./python`?

No, `nm ./python | grep crypt` gives no results
