### ISSUE TITLE
bugs.python.org does not redirect to HTTPS

### ISSUE THREAD

**Issue by d773c561-b325-48b1-bfe1-9da0d2513867** [python/cpython#73724]
BPO | [29538](https://bugs.python.org/issue29538)
--- | :---
Nosy | @yan12125, @paulschreiber

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-13.10:28:32.604>
created_at = <Date 2017-02-12.23:43:58.610>
labels = ['type-security']
title = 'bugs.python.org does not redirect to HTTPS'
updated_at = <Date 2017-02-13.15:12:18.116>
user = 'https://github.com/paulschreiber'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-13.15:12:18.116>
actor = 'yan12125'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-13.10:28:32.604>
closer = 'berker.peksag'
components = []
creation = <Date 2017-02-12.23:43:58.610>
creator = 'paulschreiber'
dependencies = []
files = []
hgrepos = []
issue_num = 29538
keywords = []
message_count = 4.0
messages = ['287661', '287668', '287698', '287703']
nosy_count = 2.0
nosy_names = ['yan12125', 'paulschreiber']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue29538'
versions = []
```

</p></details>

**Comment by d773c561-b325-48b1-bfe1-9da0d2513867** [comment]
bugs.python.org does not redirect HTTP requests to HTTPS and does not provide Strict Transport Security.

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
Duplicate of http://psf.upfronthosting.co.za/roundup/meta/issue463

**Comment by d773c561-b325-48b1-bfe1-9da0d2513867** [comment]
The issue you linked to:
http://psf.upfronthosting.co.za/roundup/meta/issue463

covers psf.upfronthosting.co.za (which doesn't support HTTPS at all) and not bugs.python.org (which supports, but does not enforce HTTPS).

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
From CPython's developer guide [1]:

"Issues about the tracker should be reported to the meta tracker."

> which doesn't support HTTPS at all

I don't know where I should go for issues about the meta tracker. Maybe a meta-meta tracker? :D

[1] http://cpython-devguide.readthedocs.io/tracker.html
