### ISSUE TITLE
python -m spacy.en.download undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz

### ISSUE THREAD

**Issue by aea3fc78-423e-4dd9-9d0e-8403df9c7cb7** [python/cpython#73728]
BPO | [29542](https://bugs.python.org/issue29542)
--- | :---
Nosy | @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-13.10:39:48.740>
created_at = <Date 2017-02-13.10:35:03.790>
labels = ['build']
title = 'python -m spacy.en.download undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz'
updated_at = <Date 2017-02-13.10:39:48.738>
user = 'https://bugs.python.org/VladimirShebunyaev'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-13.10:39:48.738>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-13.10:39:48.740>
closer = 'berker.peksag'
components = []
creation = <Date 2017-02-13.10:35:03.790>
creator = 'Vladimir Shebunyaev'
dependencies = []
files = []
hgrepos = []
issue_num = 29542
keywords = []
message_count = 2.0
messages = ['287674', '287675']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'Vladimir Shebunyaev']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29542'
versions = ['Python 2.7']
```

</p></details>

**Comment by aea3fc78-423e-4dd9-9d0e-8403df9c7cb7** [comment]
I have  (python 2.7.13 Anaconda 4.3.0 64bit Ubuntu 16 )
tried

python -m spacy.en.download

and got

/home/vshebuniayeu/anaconda2/bin/python: /home/vshebuniayeu/anaconda2/lib/python2.7/site-packages/spacy/serialize/huffman.so: undefined symbol: \_ZSt24__throw_out_of_range_fmtPKcz

**Comment by berkerpeksag** [comment]
Thanks for the report, but spacy is not part of the Python standard library. Please report your problem to spacy developers.
