### ISSUE TITLE
datetime hash is deterministic in some cases

### ISSUE THREAD

**Issue by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [python/cpython#73721]
BPO | [29535](https://bugs.python.org/issue29535)
--- | :---
Nosy | @malemburg, @tim-one, @rhettinger, @mdickinson, @abalkin, @vstinner, @tiran, @benjaminp, @davidmalcolm, @serhiy-storchaka, @miss-islington, @epicfaace
PRs | <li>python/cpython#1937</li><li>python/cpython#15264</li><li>python/cpython#15269</li><li>python/cpython#15454</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-24.10:29:35.140>
created_at = <Date 2017-02-11.15:16:53.358>
labels = ['type-bug', '3.8', '3.9', 'docs']
title = 'datetime hash is deterministic in some cases'
updated_at = <Date 2019-08-24.10:29:35.132>
user = 'https://github.com/arigo'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-24.10:29:35.132>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-08-24.10:29:35.140>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-02-11.15:16:53.358>
creator = 'arigo'
dependencies = []
files = []
hgrepos = []
issue_num = 29535
keywords = ['patch']
message_count = 19.0
messages = ['287601', '287602', '287607', '287609', '295165', '295167', '349636', '349653', '349731', '349750', '349780', '349801', '349828', '349853', '349865', '350285', '350297', '350357', '350361']
nosy_count = 13.0
nosy_names = ['lemburg', 'tim.peters', 'rhettinger', 'mark.dickinson', 'belopolsky', 'vstinner', 'christian.heimes', 'benjamin.peterson', 'dmalcolm', 'docs@python', 'serhiy.storchaka', 'miss-islington', 'epicfaace']
pr_nums = ['1937', '15264', '15269', '15454']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29535'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [comment]
The documentation on the hash randomization says that date, time and datetime have a hash based on strings, that is therefore nondeterministic in several runs of Python.  I may either be missing a caveat, or the actual implementation does not follow its promise in case a timezone is attached to the datetime or time object:

\~/svn/python/3.7-debug/python -c "import datetime;print(hash(d                      atetime.datetime(2016,10,10,0,0,0,0,datetime.timezone(datetime.timedelta(0, 36000)))))"
(this gives -6021186165085109055 all the time)

\~/svn/python/3.7-debug/python -c "import datetime;print(hash(datetime.time(0,0,0,0, datetime.timezone(datetime.timedelta(0, 36000)))))"
(this gives -3850122659820237607 all the time)

**Comment by tiran** [comment]
Only the hash of str and bytes are randomized/ The types date, datetime and time are not subject to hash randomization. Same for int, float, bool and None.

**Comment by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [comment]
That's not what the docs say.  E.g.: https://docs.python.org/3/reference/datamodel.html#object.\_\_hash__ says

    By default, the __hash__() values of str, bytes and datetime objects are “salted” with an unpredictable random value. Although they remain constant within an individual Python process, they are not predictable between repeated invocations of Python.

Morever, this command really prints changing numbers:

\~/svn/python/3.7-debug/python -c "import datetime;print(hash(d                      atetime.datetime(2016,10,10,0,0,0,0)))"

**Comment by tiran** [comment]
I only checked Python 2.7. For Python 3.x it's a bit more complicated:

timedelta: PyObject_Hash(), always the same hash value
date: \_Py_HashBytes(), always a randomized hash value
time: \_Py_HashBytes() for offset = None, PyObject_Hash() for offset != 0
datetime: \_Py_HashBytes() for offset = None, PyObject_Hash() for offset != 0
timezone: PyObject_Hash() (inherited from object)

I don't know why the datetime module doesn't use hash randomization for datetime and time objects with an offset. MAL is the master of (date)time. He might know.

**Comment by rhettinger** [comment]
Rather than changing the documentation, I would prefer to have this fixed for date/time/datetiem unless MAL has a reason not to make the change.

For timezone, I don't think we really care.  

For timedelta, it is reasonable to always be the same hash.  It isn't conceptually different from the float given by s.total_seconds() or a tuple of (days, seconds, microseconds).

**Comment by serhiy-storchaka** [comment]
It looks to me that this difference is not intentional. This is just a consequence of the fact that \_\_hash__ functions for some of these objects use the hash of the pickle state which is a bytes object.
