### ISSUE TITLE
Allow login to bugs.python.org with Google account

### ISSUE THREAD

**Issue by d773c561-b325-48b1-bfe1-9da0d2513867** [python/cpython#73730]
BPO | [29544](https://bugs.python.org/issue29544)
--- | :---
Nosy | @berkerpeksag, @paulschreiber

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-13.19:20:38.956>
created_at = <Date 2017-02-13.15:07:47.448>
labels = ['type-feature']
title = 'Allow login to bugs.python.org with Google account'
updated_at = <Date 2017-02-13.19:20:38.954>
user = 'https://github.com/paulschreiber'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-13.19:20:38.954>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-13.19:20:38.956>
closer = 'berker.peksag'
components = []
creation = <Date 2017-02-13.15:07:47.448>
creator = 'paulschreiber'
dependencies = []
files = []
hgrepos = []
issue_num = 29544
keywords = []
message_count = 2.0
messages = ['287701', '287722']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'paulschreiber']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29544'
versions = []
```

</p></details>

**Comment by d773c561-b325-48b1-bfe1-9da0d2513867** [comment]
I created a standard account on bugs.python.org with username paulschreiber and email address paulschreiber at gmail.com.

Later, I attempted to log in to bugs.python.org using Google and was shown an error message:
    There is already an account for paulschreiber@gmail.com

Instead of showing me the error message, I should have been logged in.

**Comment by berkerpeksag** [comment]
Thanks for the report. Feature requests about bugs.python.org should be reported to http://psf.upfronthosting.co.za/roundup/meta/
