### ISSUE TITLE
Improve docstring for str.index

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#73735]
BPO | [29549](https://bugs.python.org/issue29549)
--- | :---
Nosy | @rhettinger, @ncoghlan, @benhoyt, @serhiy-storchaka, @zhangyangyu, @lisroach, @Mariatta, @CuriousLearner
PRs | <li>python/cpython#147</li><li>python/cpython#204</li><li>python/cpython#256</li><li>python/cpython#1028</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/lisroach'
closed_at = <Date 2017-04-05.06:32:02.545>
created_at = <Date 2017-02-13.20:57:22.161>
labels = ['3.7', 'docs']
title = 'Improve docstring for str.index'
updated_at = <Date 2017-04-10.21:38:58.744>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-10.21:38:58.744>
actor = 'Mariatta'
assignee = 'lisroach'
closed = True
closed_date = <Date 2017-04-05.06:32:02.545>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-02-13.20:57:22.161>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 29549
keywords = []
message_count = 17.0
messages = ['287724', '288025', '288027', '288234', '288235', '288353', '288354', '288402', '288404', '288405', '288408', '288465', '288470', '288494', '291154', '291159', '291397']
nosy_count = 8.0
nosy_names = ['rhettinger', 'ncoghlan', 'benhoyt', 'serhiy.storchaka', 'xiang.zhang', 'lisroach', 'Mariatta', 'CuriousLearner']
pr_nums = ['147', '204', '256', '1028']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29549'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by rhettinger** [comment]
The docstring for str.index() needs to be synced with the main documentation rather than presuming knowledge of str.find().

Currently it reads:

```pycon
>>> help(str.index)
Help on method_descriptor:
```


```py
index(...)
    S.index(sub[, start[, end]]) -> int
    
    Like S.find() but raise ValueError when the substring is not found.
```


And it should read more like str.find:

```py
help(str.find)
Help on method_descriptor:

find(...)
    S.find(sub[, start[, end]]) -> int
    
    Return the lowest index in S where substring sub is found,
    such that sub is contained within S[start:end].  Optional
    arguments start and end are interpreted as in slice notation.
    
    Return -1 on failure.
```


Lisa, it would be great if you could draft-up a patch.

**Comment by 8029d403-64fb-4202-9817-4695852d288d** [comment]
Good call. Additionally, it's weird to me that the docstring for str.find() says "Return -1 on failure." because the string not being found is not a "failure". Like the docs (https://docs.python.org/3.5/library/stdtypes.html#str.find) say, the str.find() docstring should say "Return -1 if sub is not found."

**Comment by serhiy-storchaka** [comment]
str.index() still is not converted to Argument Clinic (this is not easy). The docstring needs to be rewritten when convert it to Argument Clinic in any case. It would be nice to make it Argument Clinic compatible right now. The first line line should be short description, following paragraph(s) can describe more details, the description shouldn't refer to the metavariable S.

Docstrings for str, bytes and bytearray methods should be synchronised. Look also at docstrings for the index() method in other sequence types (list, tuple, deque, array, Sequence).

**Comment by lisroach** [comment]
I tried to have a go at making the str.index Argument Clinic compatible, Serhiy can you take a look at my commits and let me know if this is the correct way of doing it: 

https://github.com/python/cpython/compare/master...lisroach:master

If it looks good I will make a pull request. Thanks!

**Comment by serhiy-storchaka** [comment]
No need to add Argument Clinic code. Just make docstrings in the style of of Argument Clinic descriptions.

**Comment by Mariatta** [comment]
CuriousLearner,

I see that you have PRs against this issue.
The issue is currently assigned to Lisa.
I respectfully request that you choose a different issue to work on and to withdraw your pull request.

Please choose an issue that is not currently assigned to anyone. If an issue is assigned, please ask first before working on it. 

Thank you.

**Comment by CuriousLearner** [comment]
Mariatta, I apologize for this. I completely missed to see that this was already assigned to someone else.

I've withdrawn my PR.

Thanks.

**Comment by rhettinger** [comment]
Serhiy, I'm not sure what you're referring to by "Just make docstrings in the style of of Argument Clinic descriptions".   For the time being, I would like the docstring to match that of str.find().  The point of the patch is to decouple the two.  

AC issues and migrations can wait.  At this point, AC adoption has been more disruptive that helpful in a number of cases.

**Comment by zhangyangyu** [comment]
Lisa, could you make a PR? It could let more developers see your patch.

**Comment by rhettinger** [comment]
Please everyone.  Ease up.  This is a very simple patch.  Copy what is done in str.find to str.index.  It doesn't need infinite discussion and debate.  I assigned this to Lisa to give her practice.  It wasn't intended to have five developers jump in and shove it back and forth.  Let's let simple things be simple and not waste the time of new contributors.

**Comment by serhiy-storchaka** [comment]
I mean that this work is useless since it will be lost when convert str.index to Argument Clinic. Well, even when don't use Argument Clinic, but make str.index() be supported by inspect.signature(), the docstring should be significantly rewritten.

I think there are many other easy documentation issues for practicing.

And all proposed PRs change only the docstring of str.index. They don't touch docstrings of str.rindex, bytes.index, bytes.rindex, bytearray.index and bytearray.rindex. I can't approve such changes.

**Comment by lisroach** [comment]
I'll just go ahead and make my PR, let me know what else needs to be done.

Serhiy, if you could point me in the direction of how to write the docstring so that it is in the Argument Clinic style I would be happy to take a look.

**Comment by Mariatta** [comment]
Thanks for the PR, Lisa. 

Serhiy, Raymond, could you both review this? Thanks.
I can do the merge and backport once it gets both of your approval :)

Also,should this be applied to 3.5 too?

**Comment by serhiy-storchaka** [comment]
Write docstrings in following style:

"index($self, sub, start=0, end=sys.maxsize, /)\\n"
"--\\n"
"\\n"
"\<The summary line\>\\n"
"\\n"
"\<Rest of multiline\\n"
"description\>"

Extract the summary line. Don't use the metavariable "S" since it no longer defined in the signature.

**Comment by rhettinger** [comment]
New changeset 43ba8861e0ad044efafa46a7cc04e12ac5df640e by Raymond Hettinger (Lisa Roach) in branch 'master':
bpo-29549: Fixes docstring for str.index (#256)
https://github.com/python/cpython/commit/43ba8861e0ad044efafa46a7cc04e12ac5df640e

**Comment by rhettinger** [comment]
Thanks Lisa.

**Comment by Mariatta** [comment]
New changeset 577fc04a7157f6e904cffd6a0e1ad83d3460acd6 by Mariatta in branch '3.6':
[3.6] bpo-29549: Fixes docstring for str.index (GH-256) (GH-1028)
https://github.com/python/cpython/commit/577fc04a7157f6e904cffd6a0e1ad83d3460acd6
