### ISSUE TITLE
Issue in Dictionary fromkeys

### ISSUE THREAD

**Issue by e2da6c24-999a-48ff-ab58-f065df8f90e4** [python/cpython#73738]
BPO | [29552](https://bugs.python.org/issue29552)
--- | :---
Nosy | @pfmoore, @tjguk, @vadmium, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-14.12:10:24.214>
created_at = <Date 2017-02-14.09:27:46.405>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'Issue in Dictionary fromkeys'
updated_at = <Date 2017-02-14.12:10:24.213>
user = 'https://bugs.python.org/prudvibt81'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-14.12:10:24.213>
actor = 'prudvibt81'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-14.12:10:24.214>
closer = 'prudvibt81'
components = ['Windows']
creation = <Date 2017-02-14.09:27:46.405>
creator = 'prudvibt81'
dependencies = []
files = []
hgrepos = []
issue_num = 29552
keywords = []
message_count = 6.0
messages = ['287747', '287748', '287749', '287770', '287771', '287772']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'martin.panter', 'zach.ware', 'steve.dower', 'prudvibt81']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29552'
versions = ['Python 2.7']
```

</p></details>

**Comment by e2da6c24-999a-48ff-ab58-f065df8f90e4** [comment]
If we load the keys and values using fromkeys on dic.
Later the modification in the values is reflects for all keys in the DIC, please follow the below code.

```pycon
#######################################################################################
PS C:\Python27> py
Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> input = ['1','2']
>>> result = {}
>>> result = result.fromkeys(input,[])  >>>> Issue with this line
>>>
>>> result
{'1': [], '2': []}
>>>
>>> result['1'].append("item1")
>>>
>>> result
{'1': ['item1'], '2': ['item1']}   >>>>>>>>>>>>>>>>>> Here result['2'] also overwrites
>>>
>>> result['1'].append("item2")    
>>> result
{'1': ['item1', 'item2'], '2': ['item1', 'item2']}   >>>>>>>>>>>>>>>>>> Here result['2'] also overwrites
>>>
>>>
#######################################################################################
```

**Comment by e2da6c24-999a-48ff-ab58-f065df8f90e4** [comment]
Workaround is replace the below 2 lines with "result ={D_IP:[] for D_IP in input}"

\==========================
```py
result = {}
result = result.fromkeys(input,[])  >>>> Issue with this line
```
==========================

**Comment by e2da6c24-999a-48ff-ab58-f065df8f90e4** [comment]
Also observed that ID of the values are pointing same, its ok.
But if some one later modified that values which causes the un-usual output.

```pycon
>>> id(result['1'])
38121184
>>> id(result['2'])
38121184
```

**Comment by vadmium** [comment]
This is similar to the problem of building a list by repeating one item: \<https://docs.python.org/2.7/faq/programming.html#how-do-i-create-a-multidimensional-list\>.

With dict.fromkeys(), the resulting dictionary maps each specified key object to the one and only value object (empty list) you passed to fromkeys(). If you look up one of the keys, it returns the list object. If you modify that object, all references to that object will see the update.

The difference with the dictionary comprehension workaround is that the interpreter executes the expressions “D_IP” and “[]” once for each iteration of “input”, resulting in a new empty list instance each iteration. But when you call fromkeys(), you pass a single object. The fromkeys() method just copies references; it does not create objects itself.

If the id() function returns the same identity, it means you have two references to the same underlying object instance. This is the same as checking “result['1'] is result['2']”.

**Comment by vadmium** [comment]
I suggest to close this as not a bug.

**Comment by e2da6c24-999a-48ff-ab58-f065df8f90e4** [comment]
Thanks Martin , I will close it.
