### ISSUE TITLE
Python behavioral difference between Linux and AIX

### ISSUE THREAD

**Issue by 5924b2aa-8b9c-444f-a9b3-b208f098a22d** [python/cpython#73731]
BPO | [29545](https://bugs.python.org/issue29545)
--- | :---
Nosy | @ericvw, @addaleax

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-02-13.15:46:52.409>
labels = []
title = 'Python behavioral difference between Linux and AIX'
updated_at = <Date 2017-03-17.15:48:23.298>
user = 'https://bugs.python.org/gireeshpunathil'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-17.15:48:23.298>
actor = 'aixtools@gmail.com'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-02-13.15:46:52.409>
creator = 'gireeshpunathil'
dependencies = []
files = []
hgrepos = []
issue_num = 29545
keywords = []
message_count = 2.0
messages = ['287706', '289766']
nosy_count = 4.0
nosy_names = ['ericvw', 'gireeshpunathil', 'aixtools@gmail.com', 'addaleax']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29545'
versions = []
```

</p></details>

**Comment by 5924b2aa-8b9c-444f-a9b3-b208f098a22d** [comment]
Here is my python code (parent):

```py
#!/usr/bin/env python
import errno
import os
import pty
from subprocess import Popen, STDOUT
```


master_fd, slave_fd = pty.openpty()
proc = Popen(['./a.out'],stdout=slave_fd, close_fds=True)
os.close(slave_fd)
data = os.read(master_fd, 512)
print('got ' + repr(data))

```c
Child(C++):
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>

int main()
{
        printf("hello world\n");
        exit(0);
}
```


behavior: 
Linux:
got 'hello world\\r\\r\\n'
AIX: Hangs.

versions:
Linux:
Linux 2.6.32-131.12.1.el6.x86_64 #1 SMP Sun Jul 31 16:44:56 EDT 2011 
x86_64 x86_64 x86_64 GNU/Linux
AIX: 1 6 00F460A94C00
Python: 2.7.10

**Comment by 349513ba-0efb-4c7b-884a-6c4d85313e4a** [comment]
Curious.

First pass: using python2.7.12 also hanged as program, on the close()

second pass: interactive - do the read first, then the close - seems to work:

root@x064:[/data/prj/python/issues/29545]cat hello.py
#!/usr/bin/env python
import errno
import os
import pty
from subprocess import Popen, STDOUT

```pycon
master_fd, slave_fd = pty.openpty()
proc = Popen(['./hello'],stdout=slave_fd, close_fds=True)
os.close(slave_fd)
data = os.read(master_fd, 512)
print('got ' + repr(data))
root@x064:[/data/prj/python/issues/29545]python
Python 2.7.12 (default, Sep 29 2016, 12:02:17) [C] on aix5
Type "help", "copyright", "credits" or "license" for more information.
>>> import errno
import os
import pty
from subprocess import Popen, STDOUT
>>> >>> >>> >>>
>>> master_fd, slave_fd = pty.openpty()
>>> master_fd
3
>>> slave_fd
4
>>> proc = Popen(['./hello'],stdout=slave_fd, close_fds=True)
>>> data = os.read(master_fd, 512)
>>> datat
'hello world\r\n'
>>> os.close(slave_fd)
>>> print (got '
  File "<stdin>", line 1
    print (got '
               ^
SyntaxError: EOL while scanning string literal
>>> print('got ' + repr(data))
got 'hello world\r\n'
>>> quit()
```


pass 3:
swap the close() and the read() and the program works fine.

"hello.py" 11 lines, 265 characters

root@x064:[/data/prj/python/issues/29545]cat hello.py
#!/usr/bin/env python
import errno
import os
import pty
from subprocess import Popen, STDOUT

master_fd, slave_fd = pty.openpty()
proc = Popen(['./hello'],stdout=slave_fd, close_fds=True)
data = os.read(master_fd, 512)
os.close(slave_fd)
print('got ' + repr(data))

root@x064:[/data/prj/python/issues/29545]./hello.py
got 'hello world\\r\\n'
root@x064:[/data/prj/python/issues/29545]

**Comment by iritkatriel** [comment]
Python 2.X is no longer supported.
