### ISSUE TITLE
Mac build-installer touch step fails after github conversion

### ISSUE THREAD

**Issue by db3l** [python/cpython#73736]
BPO | [29550](https://bugs.python.org/issue29550)
--- | :---
Nosy | @db3l, @larryhastings, @ned-deily, @zware
PRs | <li>python/cpython#456</li><li>python/cpython#458</li>
Superseder | <li>bpo-23404: &#x27;make touch&#x27; does not work with git clones of the source repository</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = <Date 2017-06-10.18:27:17.302>
created_at = <Date 2017-02-13.21:24:45.936>
labels = ['build', '3.7']
title = 'Mac build-installer touch step fails after github conversion'
updated_at = <Date 2017-06-10.18:27:17.301>
user = 'https://github.com/db3l'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.18:27:17.301>
actor = 'ned.deily'
assignee = 'ned.deily'
closed = True
closed_date = <Date 2017-06-10.18:27:17.302>
closer = 'ned.deily'
components = ['Build']
creation = <Date 2017-02-13.21:24:45.936>
creator = 'db3l'
dependencies = []
files = []
hgrepos = []
issue_num = 29550
keywords = []
message_count = 5.0
messages = ['287726', '287727', '290302', '290306', '295650']
nosy_count = 4.0
nosy_names = ['db3l', 'larry', 'ned.deily', 'zach.ware']
pr_nums = ['456', '458']
priority = None
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '23404'
type = 'compile error'
url = 'https://bugs.python.org/issue29550'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by db3l** [comment]
The "make touch" step during the Mac installer builds on the bolen-dmg build slave no longer works after the conversion to github, which breaks the daily builds on the 3.* branches.

It looks like in bpo-23404 Zachary disabled the touch step for the buildbots for now to avoid the issue in general builds, so perhaps the same thing should be done in build-installer pending a more general replacement of that step.

**Comment by ned-deily** [comment]
Thanks, I'll take a look.

**Comment by ned-deily** [comment]
New changeset 5ddddb166d9979161624c17cce3bdc11e1d9f3b8 by Ned Deily in branch '3.6':
bpo-29550: Temporarily skip "make touch" in Mac installer build. (#456) (#458)
https://github.com/python/cpython/commit/5ddddb166d9979161624c17cce3bdc11e1d9f3b8

**Comment by ned-deily** [comment]
New changeset 7cd9b22e98a5b7a99a7539500ea946a7a58e1c8d by Ned Deily in branch 'master':
bpo-29550: Temporarily skip "make touch" in Mac installer build. (#456)
https://github.com/python/cpython/commit/7cd9b22e98a5b7a99a7539500ea946a7a58e1c8d

**Comment by ned-deily** [comment]
The changes for bpo-23404 removed "make touch" including from the installer build.
