### ISSUE TITLE
Add c code coverage to codecov

### ISSUE THREAD

**Issue by abalkin** [python/cpython#73733]
BPO | [29547](https://bugs.python.org/issue29547)
--- | :---
Nosy | @brettcannon, @abalkin

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2017-02-13.16:54:51.164>
labels = ['3.7', 'tests']
title = 'Add c code coverage to codecov'
updated_at = <Date 2017-02-13.18:30:07.699>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-13.18:30:07.699>
actor = 'brett.cannon'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-02-13.16:54:51.164>
creator = 'belopolsky'
dependencies = []
files = []
hgrepos = []
issue_num = 29547
keywords = []
message_count = 2.0
messages = ['287710', '287720']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'belopolsky']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29547'
versions = ['Python 3.7']
```

</p></details>

**Comment by abalkin** [comment]
I had it done in my fork of cpython-mirror: https://github.com/abalkin/cpython/tree/ci

**Comment by brettcannon** [comment]
I have https://github.com/python/core-workflow/issues/2 sitting open for this specific idea. :) If Codecov will do the appropriate merging between coverage.py and lcov then I think it's worth a PR to set it up.

**Comment by hugovk** [comment]
No longer relevant, we removed coverage from the CI in https://github.com/python/cpython/pull/25679.
