### ISSUE TITLE
Remove unused #include <langinfo.h>

### ISSUE THREAD

**Issue by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [python/cpython#73742]
BPO | [29556](https://bugs.python.org/issue29556)
--- | :---
Nosy | @ncoghlan, @vstinner, @yan12125
PRs | <li>python/cpython#98</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.10:06:24.733>
created_at = <Date 2017-02-14.16:06:53.585>
labels = ['type-feature', '3.7', 'build']
title = 'Remove unused #include <langinfo.h>'
updated_at = <Date 2017-11-24.10:06:24.732>
user = 'https://github.com/yan12125'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.10:06:24.732>
actor = 'yan12125'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.10:06:24.733>
closer = 'yan12125'
components = ['Build']
creation = <Date 2017-02-14.16:06:53.585>
creator = 'yan12125'
dependencies = []
files = []
hgrepos = []
issue_num = 29556
keywords = []
message_count = 4.0
messages = ['287780', '287782', '287900', '306882']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'vstinner', 'yan12125']
pr_nums = ['98']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29556'
versions = ['Python 3.7']
```

</p></details>

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
This #include is added in b744ba1d14c5487576c95d0311e357b707600b47 (bpo-8610) and later the use of CODESET is removed in d64e8a75e5138d5e5970f0c70995ae5cc377c421 (bpo-9642).

Found this in investigating bpo-29436

Add haypo as both commit is written by you

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
Hmmm, seems there are more redundant #include \<langinfo.h\>; let me check one by one

**Comment by vstinner** [comment]
New changeset 72e81d00eee685cfe33aaddf2aa9feef2d07591f by Victor Stinner in branch 'master':
bpo-29556: Remove unused #include \<langinfo.h\> (#98)
https://github.com/python/cpython/commit/72e81d00eee685cfe33aaddf2aa9feef2d07591f

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
As https://github.com/python/cpython/pull/98 is merged, this issue is fixed. Thanks haypo for the review!
