### ISSUE TITLE
Update Python Software Foundation Copyright Year

### ISSUE THREAD

**Issue by orsenthil** [python/cpython#73741]
BPO | [29555](https://bugs.python.org/issue29555)
--- | :---
Nosy | @malemburg, @ncoghlan, @orsenthil, @VanL, @Mariatta, @jdevries3133
Files | <li>[pr-4.diff](https://bugs.python.org/file46638/pr-4.diff "Uploaded as text/plain at 2017-02-14.16:01:58 by @orsenthil")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-23.12:06:23.717>
created_at = <Date 2017-02-14.16:02:00.576>
labels = ['3.7', 'invalid', 'docs']
title = 'Update Python Software Foundation Copyright Year'
updated_at = <Date 2021-07-23.12:06:23.716>
user = 'https://github.com/orsenthil'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-23.12:06:23.716>
actor = 'orsenthil'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-07-23.12:06:23.717>
closer = 'orsenthil'
components = ['Documentation']
creation = <Date 2017-02-14.16:02:00.576>
creator = 'orsenthil'
dependencies = []
files = ['46638']
hgrepos = []
issue_num = 29555
keywords = ['patch']
message_count = 5.0
messages = ['287779', '295155', '299824', '398032', '398047']
nosy_count = 7.0
nosy_names = ['lemburg', 'ncoghlan', 'orsenthil', 'vanl', 'docs@python', 'Mariatta', 'jack__d']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29555'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by orsenthil** [comment]
In the attached patch, I updated the copyright year to 2017 at places it was mentioned until 2016.

There was a suggestion that we remove the copyright line of Python Software Foundation from module headers since the code is already covered 1) by top level copyright mention, 2) The mention of copyright is inconsistent in modules, 3) will avoid unnecessary churn every year. 

This idea needs to be vetted by PSF Board and legal staff.

**Comment by Mariatta** [comment]
Any update about this? 
Who do we need to talk to in order to move forward?
Thanks.

**Comment by ncoghlan** [comment]
Van, could you take a look at Senthil & Mariatta's questions above regarding our handling of the copyright year in CPython's module headers?
