### ISSUE TITLE
profile/pstat doc clariification

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73740]
BPO | [29554](https://bugs.python.org/issue29554)
--- | :---
Nosy | @berkerpeksag, @Carreau
PRs | <li>python/cpython#88</li><li>python/cpython#88</li><li>python/cpython#88</li><li>python/cpython#227</li><li>python/cpython#228</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-22.01:56:40.006>
created_at = <Date 2017-02-14.16:00:59.418>
labels = ['type-bug', '3.7', 'docs']
title = 'profile/pstat doc clariification'
updated_at = <Date 2017-02-22.01:56:40.005>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-22.01:56:40.005>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-22.01:56:40.006>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-02-14.16:00:59.418>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29554
keywords = []
message_count = 4.0
messages = ['287778', '288267', '288325', '288326']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'mbussonn']
pr_nums = ['88', '88', '88', '227', '228']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29554'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
profile .rst say:

> Each restriction is either an integer (to select a count of lines), or a decimal fraction between 0.0 and 1.0 inclusive (to select a percentage of lines), \*\*or a regular expression\*\*

Actually it accept a string that will be compiled to a regex.

Profile.py also mention:

> (i.e., in addition to the old -1, 0, 1, or 2)

Which is not really helpful, to newcomers to Python who do not know what these are meant to be. Either explaining (or removing if considered old behavior that should be stopped) seem to be better alternative.

See https://github.com/python/cpython/pull/88

**Comment by berkerpeksag** [comment]
New changeset 8fb1f6e039cbdeb333d83b7a62f0f37af4ce6e02 by Berker Peksag in branch 'master':
bpo-29554: Improve docs for pstat module and profile. (#88)
https://github.com/python/cpython/commit/8fb1f6e039cbdeb333d83b7a62f0f37af4ce6e02

**Comment by berkerpeksag** [comment]
New changeset 6336f0d156feec0f109a8d01da108cf96e3d9c60 by GitHub in branch '3.5':
bpo-29554: Improve docs for pstat module and profile. (#88) (#228)
https://github.com/python/cpython/commit/6336f0d156feec0f109a8d01da108cf96e3d9c60

**Comment by berkerpeksag** [comment]
New changeset b067a5eef7fdf69264d3578654996fc3755df4ea by GitHub in branch '3.6':
bpo-29554: Improve docs for pstat module and profile. (#88) (#227)
https://github.com/python/cpython/commit/b067a5eef7fdf69264d3578654996fc3755df4ea
