### ISSUE TITLE
Update Devguide about building documentation.

### ISSUE THREAD

**Issue by 32d36863-b68e-4e37-8cd2-94293053580a** [python/cpython#73749]
BPO | [29563](https://bugs.python.org/issue29563)
--- | :---
Nosy | @brettcannon, @zware, @jdlh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-15.23:49:24.803>
created_at = <Date 2017-02-15.02:46:18.378>
labels = ['type-feature', '3.7', 'docs']
title = 'Update Devguide about building documentation.'
updated_at = <Date 2017-02-15.23:49:24.802>
user = 'https://github.com/JDLH'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-15.23:49:24.802>
actor = 'brett.cannon'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-15.23:49:24.803>
closer = 'brett.cannon'
components = ['Documentation']
creation = <Date 2017-02-15.02:46:18.378>
creator = 'JDLH'
dependencies = []
files = []
hgrepos = []
issue_num = 29563
keywords = []
message_count = 5.0
messages = ['287808', '287814', '287873', '287889', '287903']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'docs@python', 'zach.ware', 'JDLH']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29563'
versions = ['Python 3.7']
```

</p></details>

**Comment by 32d36863-b68e-4e37-8cd2-94293053580a** [comment]
The Devguide section 7.5.1 "Building the documentation" / "Using make / make.bat" is out of date.  The document lists 10 documentation targets for `make`. The [Doc/Makefile](https://github.com/python/cpython/blob/main/Doc/Makefile) lists 17. 

One important omission is `make check`, which looks for errors in reStructuredText syntax, using `rstlint.py`. It's important for contributors to know about and to run `make check`, because with the move to GitHub, the project is running make check after pulling in new code.  If contributors haven't cleaned up their submissions, the build fails.

I suggest that the following improvements be made:

1. rewrite the bullet list "Available make targets are:" in 7.5.1 https://cpython-devguide.readthedocs.io/documenting.html#using-make-make-bat to match the list of targets in [Doc/Makefile:21](https://github.com/python/cpython/blob/main/Doc/Makefile#L21)-38.

2. add a comment that `make help` will give the most up-to-date list of targets from the makefile, which might be better than the list in the Devguide.

3. add `make help` to both [Doc/Makefile:21](https://github.com/python/cpython/blob/main/Doc/Makefile#L21)-38 and Devguide 7.5.1.

4. add to Devguide 6.3. "Helping with the Developer’s Guide" an instruction to run `make check` before submitting a pull request to the Devguide.

**Comment by zware** [comment]
I'd suggest replacing as much as possible in the [devguide](https://devguide.python.org) with a link to [Doc/README.rst](https://github.com/python/cpython/blob/main/Doc/README.rst) (or [Doc/README.txt](https://github.com/python/cpython/blob/main/Doc/README.txt), if that's what it still is).  Other improvements should be made in the README.

**Comment by brettcannon** [comment]
Would you mind moving this issue over to https://github.com/python/devguide/issues where we track [devguide](https://devguide.python.org) issues, Jim?

**Comment by 32d36863-b68e-4e37-8cd2-94293053580a** [comment]
Per request from Brett Cannon, I've moved this issue to https://github.com/python/devguide/issues/116 . Please continue the discussion there.

**Comment by brettcannon** [comment]
Thanks for moving the issue, Jim!
