### ISSUE TITLE
threading.Timer class: Continue periodical execution till action returns True

### ISSUE THREAD

**Issue by 34349917-2616-4cf4-b7c9-4bda2f98b87a** [python/cpython#73755]
BPO | [29569](https://bugs.python.org/issue29569)
--- | :---
Nosy | @tim-one, @rhettinger, @pitrou, @slytomcat, @csabella
PRs | <li>python/cpython#191</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/pitrou'
closed_at = <Date 2017-04-05.15:27:34.779>
created_at = <Date 2017-02-15.14:54:10.568>
labels = ['3.7', 'type-feature', 'library']
title = 'threading.Timer class: Continue periodical execution till action returns True'
updated_at = <Date 2017-06-06.14:23:23.667>
user = 'https://github.com/slytomcat'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.14:23:23.667>
actor = 'slytomcat'
assignee = 'pitrou'
closed = True
closed_date = <Date 2017-04-05.15:27:34.779>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-02-15.14:54:10.568>
creator = 'slytomcat'
dependencies = []
files = []
hgrepos = []
issue_num = 29569
keywords = []
message_count = 6.0
messages = ['287858', '288398', '291155', '291163', '295251', '295263']
nosy_count = 5.0
nosy_names = ['tim.peters', 'rhettinger', 'pitrou', 'slytomcat', 'cheryl.sabella']
pr_nums = ['191']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29569'
versions = ['Python 3.7']
```

</p></details>

**Comment by 34349917-2616-4cf4-b7c9-4bda2f98b87a** [comment]
I think that functionality of threading.Timer class can be easily extended to generate the sequence of runs with specified period. The idea comes from the GLib.timeout_add function. 

Run method of threading.Timer should look like:

```py
    def run(self):
        """Continue execution after wait till function returns True"""
        while(not self.finished.wait(self.interval)):
            if not self.function(*self.args, **self.kwargs):
                break
        self.finished.set()
```

**Comment by rhettinger** [comment]
Ideally, proposed API expansions should be based on a demonstrated user need. This API is over decade old and I don't recall a single user request for this functionality.  A quick scan of StackOverflow didn't turn-up any questions or answers on the subject.

I don't see anything intrinsically wrong with the idea, but in the absence of demonstrated need, it is likely to become unused cruft with it attendant burden on maintenance and cognitive load.

**Comment by rhettinger** [comment]
Antoine, do you care to make the call on this one?

**Comment by pitrou** [comment]
This will obviously break some existing code which passes a function returning true to Timer.  I concur with Raymond: I don't think this is a good idea.  Also, the Timer class itself is a rather simplistic answer to the problem of scheduling callbacks in the future (it uses a dedicated thread per callback, which is extremely wasteful).  You'll find better solutions in more modern toolkits, such as asyncio; or you can easily write your own logic yourself.

**Comment by csabella** [comment]
This bug report has been closed, but the PR is still open.  Please close the PR.  Thank you.

**Comment by 34349917-2616-4cf4-b7c9-4bda2f98b87a** [comment]
done

2017-06-06 14:28 GMT+03:00 Cheryl Sabella \<report@bugs.python.org\>:

>
> Cheryl Sabella added the comment:
>
> This bug report has been closed, but the PR is still open.  Please close
> the PR.  Thank you.
>
> \----------
> nosy: +csabella
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29569\>
> _______________________________________
>
