### ISSUE TITLE
test_re is failing when local is set for `en_IN`

### ISSUE THREAD

**Issue by ecd7c7a5-9835-451b-b7a2-4836efc23815** [python/cpython#73757]
BPO | [29571](https://bugs.python.org/issue29571)
--- | :---
Nosy | @warsaw, @doko42, @pfmoore, @ncoghlan, @vstinner, @tjguk, @benjaminp, @ezio-melotti, @zware, @serhiy-storchaka, @zooba, @ultimatecoder, @Naman-Bhalla, @tirkarthi
PRs | <li>python/cpython#149</li><li>python/cpython#153</li><li>python/cpython#154</li><li>python/cpython#422</li><li>python/cpython#554</li><li>python/cpython#555</li><li>python/cpython#556</li><li>python/cpython#2686</li><li>python/cpython#12099</li><li>python/cpython#12108</li><li>python/cpython#12178</li>
Files | <li>[test_re_locale_flag.patch](https://bugs.python.org/file46641/test_re_locale_flag.patch "Uploaded as text/plain at 2017-02-15.22:57:27 by @serhiy-storchaka")</li><li>[loc.py](https://bugs.python.org/file48187/loc.py "Uploaded as text/plain at 2019-03-05.12:34:20 by @vstinner")</li><li>[loc.log](https://bugs.python.org/file48188/loc.log "Uploaded as text/x-log at 2019-03-05.12:34:26 by @vstinner")</li><li>[_testcapi.patch](https://bugs.python.org/file48189/_testcapi.patch "Uploaded as text/plain at 2019-03-05.12:34:33 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-05.15:26:32.126>
created_at = <Date 2017-02-15.17:29:11.116>
labels = ['expert-regex', 'type-bug', '3.8', '3.7', 'tests', 'OS-windows']
title = 'test_re is failing when local is set for `en_IN`'
updated_at = <Date 2019-03-05.15:26:32.125>
user = 'https://github.com/ultimatecoder'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-05.15:26:32.125>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-05.15:26:32.126>
closer = 'vstinner'
components = ['Regular Expressions', 'Tests', 'Windows']
creation = <Date 2017-02-15.17:29:11.116>
creator = 'jaysinh.shukla'
dependencies = []
files = ['46641', '48187', '48188', '48189']
hgrepos = []
issue_num = 29571
keywords = ['patch']
message_count = 37.0
messages = ['287867', '287879', '287880', '287882', '287893', '287894', '287933', '288056', '288065', '288068', '288069', '288101', '288102', '289054', '289071', '289072', '289073', '289074', '289075', '289076', '289077', '289118', '290268', '290269', '290272', '310947', '310948', '311074', '311076', '336826', '336855', '336877', '336878', '336883', '337185', '337200', '337204']
nosy_count = 15.0
nosy_names = ['barry', 'doko', 'paul.moore', 'ncoghlan', 'vstinner', 'tim.golden', 'benjamin.peterson', 'ezio.melotti', 'mrabarnett', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'jaysinh.shukla', 'Naman-Bhalla', 'xtreak']
pr_nums = ['149', '153', '154', '422', '554', '555', '556', '2686', '12099', '12108', '12178']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29571'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ecd7c7a5-9835-451b-b7a2-4836efc23815** [comment]
Description:
    A test case is failing while running `./python -m test -v test_re`.

Traceback:
$\>./python -m test -v test_re
== CPython 3.7.0a0 (default, Feb 15 2017, 22:28:32) [GCC 5.4.0 20160609]
==   Linux-4.4.0-62-generic-x86_64-with-debian-stretch-sid little-endian
==   hash algorithm: siphash24 64bit
==  cwd: /home/bigj/Jaysinh/cpython_git/cpython/build/test_python_613
==  encodings: locale=UTF-8, FS=utf-8
Testing with flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0)
Run tests sequentially
0:00:00 [1/1] test_re
test_re_benchmarks (test.test_re.ExternalTests)
re_tests benchmarks ... ok
test_re_tests (test.test_re.ExternalTests)
re_tests test suite ... ok
test_overlap_table (test.test_re.ImplementationTest) ... ok
test_bytes (test.test_re.PatternReprTests) ... ok
test_inline_flags (test.test_re.PatternReprTests) ... ok
test_locale (test.test_re.PatternReprTests) ... ok
test_long_pattern (test.test_re.PatternReprTests) ... ok
test_multiple_flags (test.test_re.PatternReprTests) ... ok
test_quotes (test.test_re.PatternReprTests) ... ok
test_single_flag (test.test_re.PatternReprTests) ... ok
test_unicode_flag (test.test_re.PatternReprTests) ... ok
test_unknown_flags (test.test_re.PatternReprTests) ... ok
test_without_flags (test.test_re.PatternReprTests) ... ok
test_anyall (test.test_re.ReTests) ... ok
test_ascii_and_unicode_flag (test.test_re.ReTests) ... ok
test_backref_group_name_in_exception (test.test_re.ReTests) ... ok
test_basic_re_sub (test.test_re.ReTests) ... ok
test_big_codesize (test.test_re.ReTests) ... ok
test_bigcharset (test.test_re.ReTests) ... ok
test_bug_113254 (test.test_re.ReTests) ... ok
test_bug_114660 (test.test_re.ReTests) ... ok
test_bug_117612 (test.test_re.ReTests) ... ok
test_bug_1661 (test.test_re.ReTests) ... ok
test_bug_16688 (test.test_re.ReTests) ... ok
test_bug_20998 (test.test_re.ReTests) ... ok
test_bug_2537 (test.test_re.ReTests) ... ok
test_bug_29444 (test.test_re.ReTests) ... ok
test_bug_3629 (test.test_re.ReTests) ... ok
test_bug_418626 (test.test_re.ReTests) ... ok
test_bug_448951 (test.test_re.ReTests) ... ok
test_bug_449000 (test.test_re.ReTests) ... ok
test_bug_449964 (test.test_re.ReTests) ... ok
test_bug_462270 (test.test_re.ReTests) ... ok
test_bug_527371 (test.test_re.ReTests) ... ok
test_bug_581080 (test.test_re.ReTests) ... ok
test_bug_612074 (test.test_re.ReTests) ... ok
test_bug_6509 (test.test_re.ReTests) ... ok
test_bug_6561 (test.test_re.ReTests) ... ok
test_bug_725106 (test.test_re.ReTests) ... ok
test_bug_725149 (test.test_re.ReTests) ... ok
test_bug_764548 (test.test_re.ReTests) ... ok
test_bug_817234 (test.test_re.ReTests) ... ok
test_bug_926075 (test.test_re.ReTests) ... ok
test_bug_931848 (test.test_re.ReTests) ... ok
test_bytes_str_mixing (test.test_re.ReTests) ... ok
test_category (test.test_re.ReTests) ... ok
test_character_set_errors (test.test_re.ReTests) ... ok
test_compile (test.test_re.ReTests) ... ok
test_constants (test.test_re.ReTests) ... ok
test_dealloc (test.test_re.ReTests) ... ok
test_debug_flag (test.test_re.ReTests) ... ok
test_dollar_matches_twice (test.test_re.ReTests)
$ matches the end of string, and just before the terminating ... ok
test_empty_array (test.test_re.ReTests) ... ok
test_enum (test.test_re.ReTests) ... ok
test_error (test.test_re.ReTests) ... ok
test_expand (test.test_re.ReTests) ... ok
test_finditer (test.test_re.ReTests) ... ok
test_flags (test.test_re.ReTests) ... ok
test_getattr (test.test_re.ReTests) ... ok
test_getlower (test.test_re.ReTests) ... ok
test_group (test.test_re.ReTests) ... ok
test_group_name_in_exception (test.test_re.ReTests) ... ok
test_groupdict (test.test_re.ReTests) ... ok
test_ignore_case (test.test_re.ReTests) ... ok
test_ignore_case_range (test.test_re.ReTests) ... ok
test_ignore_case_set (test.test_re.ReTests) ... ok
test_inline_flags (test.test_re.ReTests) ... ok
test_issue17998 (test.test_re.ReTests) ... ok
test_keep_buffer (test.test_re.ReTests) ... ok
test_keyword_parameters (test.test_re.ReTests) ... ok
test_large_search (test.test_re.ReTests) ... ok
test_large_subn (test.test_re.ReTests) ... ok
test_locale_caching (test.test_re.ReTests) ... skipped 'test needs en_US.iso88591 locale'
test_locale_flag (test.test_re.ReTests) ... FAIL
test_lookahead (test.test_re.ReTests) ... ok
test_lookbehind (test.test_re.ReTests) ... ok
test_match_getitem (test.test_re.ReTests) ... ok
test_match_repr (test.test_re.ReTests) ... ok
test_misc_errors (test.test_re.ReTests) ... ok
test_multiple_repeat (test.test_re.ReTests) ... ok
test_not_literal (test.test_re.ReTests) ... ok
test_nothing_to_repeat (test.test_re.ReTests) ... ok
test_other_escapes (test.test_re.ReTests) ... ok
test_pattern_compare (test.test_re.ReTests) ... ok
test_pattern_compare_bytes (test.test_re.ReTests) ... ok
test_pickling (test.test_re.ReTests) ... ok
test_qualified_re_split (test.test_re.ReTests) ... ok
test_qualified_re_sub (test.test_re.ReTests) ... ok
test_re_escape (test.test_re.ReTests) ... ok
test_re_escape_byte (test.test_re.ReTests) ... ok
test_re_escape_non_ascii (test.test_re.ReTests) ... ok
test_re_escape_non_ascii_bytes (test.test_re.ReTests) ... ok
test_re_findall (test.test_re.ReTests) ... ok
test_re_fullmatch (test.test_re.ReTests) ... ok
test_re_groupref (test.test_re.ReTests) ... ok
test_re_groupref_exists (test.test_re.ReTests) ... ok
test_re_groupref_overflow (test.test_re.ReTests) ... ok
test_re_match (test.test_re.ReTests) ... ok
test_re_split (test.test_re.ReTests) ... ok
test_re_subn (test.test_re.ReTests) ... ok
test_repeat_minmax (test.test_re.ReTests) ... ok
test_repeat_minmax_overflow (test.test_re.ReTests) ... ok
test_repeat_minmax_overflow_maxrepeat (test.test_re.ReTests) ... ok
test_scanner (test.test_re.ReTests) ... ok
test_scoped_flags (test.test_re.ReTests) ... ok
test_search_coverage (test.test_re.ReTests) ... ok
test_search_dot_unicode (test.test_re.ReTests) ... ok
test_search_star_plus (test.test_re.ReTests) ... ok
test_special_escapes (test.test_re.ReTests) ... ok
test_sre_byte_class_literals (test.test_re.ReTests) ... ok
test_sre_byte_literals (test.test_re.ReTests) ... ok
test_sre_character_class_literals (test.test_re.ReTests) ... ok
test_sre_character_literals (test.test_re.ReTests) ... ok
test_stack_overflow (test.test_re.ReTests) ... ok
test_string_boundaries (test.test_re.ReTests) ... ok
test_sub_template_numeric_escape (test.test_re.ReTests) ... ok
test_symbolic_groups (test.test_re.ReTests) ... ok
test_symbolic_refs (test.test_re.ReTests) ... ok
test_unlimited_zero_width_repeat (test.test_re.ReTests) ... ok
test_weakref (test.test_re.ReTests) ... ok

\======================================================================
FAIL: test_locale_flag (test.test_re.ReTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/bigj/Jaysinh/cpython_git/cpython/Lib/test/test_re.py", line 1422, in test_locale_flag
    self.assertTrue(pat.match(bletter))
AssertionError: None is not true
```


----------------------------------------------------------------------
Ran 120 tests in 2.079s

FAILED (failures=1, skipped=1)
test test_re failed
test_re failed

1 test failed:
    test_re

Total duration: 2 sec
Tests result: FAILURE

Local value:
$\>locale
LANG=en_IN
LANGUAGE=en_IN:en
LC_CTYPE="en_IN"
LC_NUMERIC="en_IN"
LC_TIME="en_IN"
LC_COLLATE="en_IN"
LC_MONETARY="en_IN"
LC_MESSAGES="en_IN"
LC_PAPER="en_IN"
LC_NAME="en_IN"
LC_ADDRESS="en_IN"
LC_TELEPHONE="en_IN"
LC_MEASUREMENT="en_IN"
LC_IDENTIFICATION="en_IN"
LC_ALL=

Operating system: Ubuntu 16.04 LTS(64 bit)

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
I'm just wondering whether the problem is just due to the locale's encoding being UTF-8. The locale support in re really only works with encodings that use 1 byte/character.

**Comment by serhiy-storchaka** [comment]
Locale encoding is ISO8859-1. This test is skipped on non 8-bit locale.

This is a problem with tests, not with the re module. I don't have a solution.

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
The report says "==  encodings: locale=UTF-8, FS=utf-8".

It says that "test_locale_caching" was skipped, but also that "test_locale_flag" failed.

**Comment by serhiy-storchaka** [comment]
Good point. The test used locale.getlocale() and it returned returned ('en_IN', 'ISO8859-1').

Following patch makes the test using locale.getpreferredencoding(False), the same encoding as was reported at the header of test report.

**Comment by vstinner** [comment]
> Following patch ...

Seriously? Not a GitHub pull request? ;-) (old habit?)

**Comment by serhiy-storchaka** [comment]
> Seriously? Not a GitHub pull request? ;-) (old habit?)

I'm not experienced with git, and [devguide](https://devguide.python.org) still looks not ready.

**Comment by ncoghlan** [comment]
I have a few folks hitting this at the PyCon Pune sprints, so I'm going to apply Serhiy's patch :)

**Comment by ncoghlan** [comment]
Looking into this at the PyCon Pune sprints, the problem appears to be arising due to the following difference in behaviour when the unqualifed `en_IN` locale is set:

```sh
$ LANG=en_IN.UTF-8 python3 -c "import locale; print(locale.getlocale(locale.LC_CTYPE), locale.getpreferredencoding(False), sep='\n')"
('en_IN', 'UTF-8')
UTF-8

$ LANG=en_IN python3 -c "import locale; print(locale.getlocale(locale.LC_CTYPE), locale.getpreferredencoding(False), sep='\n')"
('en_IN', 'ISO8859-1')                                                                                                       
UTF-8
```


re.LOCALE is presumably picking up the "UTF-8" rather than the "ISO8859-1", and hence the test is failing.

**Comment by serhiy-storchaka** [comment]
Yes, please push it Nick.

**Comment by ncoghlan** [comment]
New changeset ace5c0fdd9b962e6e886c29dbcea72c53f051dc4 by GitHub in branch 'master':
bpo-29571: Use correct locale encoding in test_re (#149)
https://github.com/python/cpython/commit/ace5c0fdd9b962e6e886c29dbcea72c53f051dc4

**Comment by ncoghlan** [comment]
New changeset 0683d6889bd4430599d22e12e201b8e9c45be5a2 by GitHub in branch '3.6':
[3.6] bpo-29571: Use correct locale encoding in test_re (#149) (#153)
https://github.com/python/cpython/commit/0683d6889bd4430599d22e12e201b8e9c45be5a2

**Comment by ncoghlan** [comment]
New changeset 760f596b6a4b5514afe35e521621f484aef35413 by GitHub in branch '3.5':
[3.5] bpo-29571: Use correct locale encoding in test_re (#149) (#154)
https://github.com/python/cpython/commit/760f596b6a4b5514afe35e521621f484aef35413

**Comment by zware** [comment]
This seems to have broken test_re on Windows, see https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.1

I found this change to be the culprit via git bisect, unfortunately we didn't have any working CI on Windows (buildbots were otherwise broken) at the time this was merged.

**Comment by benjaminp** [comment]
Yep, I think we should merge https://github.com/python/cpython/pull/422 and revert ncoghlan's change.

**Comment by serhiy-storchaka** [comment]
I'm not sure this will help on Windows.

**Comment by serhiy-storchaka** [comment]
And I don't understand why my fix doesn't work on Windows.

**Comment by benjaminp** [comment]
But the test was never broken on windows.

**Comment by benjaminp** [comment]
getpreferredencoding() takes a completely different path on windows
(returns a codepage) and isn't related to the C locale.

**Comment by ncoghlan** [comment]
I'm with Serhiy on this one: if the "re" module isn't using locale.getpreferredencoding(), then there's something odd going on.

It just sounds like the disconnect on Windows is the opposite of the one we hit on Linux without Benjamin's patch, perhaps due to the UTF-8 mode changes - it wouldn't surprise me to learn that the re module is still using mbcs there instead of utf-8.

**Comment by benjaminp** [comment]
I don't see what's odd about it. re.LOCALE uses the C locale, which one
obtains from locale.getlocale(). getpreferredencoding() is not
documented to have anything to do with the C locale, and indeed on
Windows it may be completely different.

**Comment by ncoghlan** [comment]
Thanks for the explanation - given that, I agree that simply reverting the attempted test-based fix and instead relying on the bpo-20087 updates is the way to go.

**Comment by benjaminp** [comment]
New changeset 6a4b04cd337347d074ae0140fb13dca5bd4b11ef by Benjamin Peterson in branch '3.6':
Revert "bpo-29571: Use correct locale encoding in test_re (#149)" (#554) (#555)
https://github.com/python/cpython/commit/6a4b04cd337347d074ae0140fb13dca5bd4b11ef

**Comment by benjaminp** [comment]
New changeset 312f7dfb7c669fcfc43020951b7f8ff521200ad7 by Benjamin Peterson in branch '3.5':
Revert "bpo-29571: Use correct locale encoding in test_re (#149)" (#554) (#556)
https://github.com/python/cpython/commit/312f7dfb7c669fcfc43020951b7f8ff521200ad7

**Comment by benjaminp** [comment]
New changeset 21a74312f2d1ddee71fade709af49d078085ec30 by Benjamin Peterson in branch 'master':
Revert "bpo-29571: Use correct locale encoding in test_re (#149)" (#554)
https://github.com/python/cpython/commit/21a74312f2d1ddee71fade709af49d078085ec30
