### ISSUE TITLE
Upgrade installers to OpenSSL 1.0.2k

### ISSUE THREAD

**Issue by zware** [python/cpython#73758]
BPO | [29572](https://bugs.python.org/issue29572)
--- | :---
Nosy | @pfmoore, @ronaldoussoren, @vstinner, @larryhastings, @tiran, @tjguk, @ned-deily, @zware, @zooba
PRs | <li>python/cpython#439</li><li>python/cpython#442</li><li>python/cpython#443</li><li>python/cpython#444</li><li>python/cpython#457</li><li>python/cpython#459</li><li>python/cpython#2835</li><li>python/cpython#2836</li><li>python/cpython#3445</li><li>python/cpython#3447</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = <Date 2017-07-24.08:04:34.505>
created_at = <Date 2017-02-15.18:06:12.057>
labels = ['type-security', 'OS-mac', 'expert-installation', 'expert-SSL', '3.7', 'OS-windows']
title = 'Upgrade installers to OpenSSL 1.0.2k'
updated_at = <Date 2019-05-10.18:01:33.550>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-10.18:01:33.550>
actor = 'ned.deily'
assignee = 'ned.deily'
closed = True
closed_date = <Date 2017-07-24.08:04:34.505>
closer = 'ned.deily'
components = ['Installation', 'macOS', 'Windows', 'SSL']
creation = <Date 2017-02-15.18:06:12.057>
creator = 'zach.ware'
dependencies = []
files = []
hgrepos = []
issue_num = 29572
keywords = []
message_count = 15.0
messages = ['287877', '288924', '288925', '288938', '290303', '290304', '290314', '290316', '290317', '290318', '290589', '290627', '298931', '298932', '307873']
nosy_count = 9.0
nosy_names = ['paul.moore', 'ronaldoussoren', 'vstinner', 'larry', 'christian.heimes', 'tim.golden', 'ned.deily', 'zach.ware', 'steve.dower']
pr_nums = ['439', '442', '443', '444', '457', '459', '2835', '2836', '3445', '3447']
priority = 'high'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue29572'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zware** [comment]
It's that time once again (as of a few weeks ago).  This one doesn't seem to be a high severity update, though.  Also, it seems that 1.1.0e is due tomorrow; I'm not sure if that means 1.0.2l will also come out tomorrow, so we'll want to hold off until at least then anyway.  This is mostly just a reminder for now.

**Comment by ned-deily** [comment]
Steve, Zach: can we get this in for 3.6.1?

**Comment by zware** [comment]
Yes*.

**Comment by zware** [comment]
Done on Windows except for [PR444](https://github.com/python/cpython/pull/444) for 2.7, which is waiting on Travis.

**Comment by ned-deily** [comment]
New changeset 343d48379c31f31cb0bcc843c537990c4283703d by Ned Deily in branch '3.6':
bpo-29572: Update macOS installer build to OpenSSL 1.0.2k (#457) (#459)
https://github.com/python/cpython/commit/343d48379c31f31cb0bcc843c537990c4283703d

**Comment by ned-deily** [comment]
New changeset cfcd76777e35c83d548d8736f5d7dc92fe56d806 by Ned Deily in branch 'master':
bpo-29572: Update macOS installer build to OpenSSL 1.0.2k (#457)
https://github.com/python/cpython/commit/cfcd76777e35c83d548d8736f5d7dc92fe56d806

**Comment by zware** [comment]
New changeset f9a6516117f96397aa9c5bd58ea13b111b86b257 by Zachary Ware in branch '2.7':
bpo-29572: Update Windows build to OpenSSL 1.0.2k (GH-444)
https://github.com/python/cpython/commit/f9a6516117f96397aa9c5bd58ea13b111b86b257

**Comment by zware** [comment]
New changeset fc64c351c7757f0ebdb7da65cb74871e494a2add by Zachary Ware in branch 'master':
bpo-29572: Update Windows build to OpenSSL 1.0.2k (GH-439)
https://github.com/python/cpython/commit/fc64c351c7757f0ebdb7da65cb74871e494a2add

**Comment by zware** [comment]
New changeset 03f7cb060414b17d88cb406f3e09f26c902d8658 by Zachary Ware in branch '3.6':
bpo-29572: Update Windows build to OpenSSL 1.0.2k (GH-442)
https://github.com/python/cpython/commit/03f7cb060414b17d88cb406f3e09f26c902d8658

**Comment by zware** [comment]
New changeset dd2000cbe475da48fdc94e8f05618e9f460077fd by Zachary Ware in branch '3.5':
bpo-29572: Update Windows build to OpenSSL 1.0.2k (GH-443)
https://github.com/python/cpython/commit/dd2000cbe475da48fdc94e8f05618e9f460077fd

**Comment by vstinner** [comment]
FYI I started to track OpenSSL versions in my "Python security" documentation:
http://python-security.readthedocs.io/ssl.html#openssl-versions

It seems like all pull requests are merged. Can the issue be closed now?

**Comment by ned-deily** [comment]
> It seems like all pull requests are merged. Can the issue be closed now?

Not quite yet.

**Comment by ned-deily** [comment]
New changeset 002f778ecab98f4725a08f35d68f78559a13e47a by Ned Deily in branch '3.5':
bpo-29572: Update macOS installer build to OpenSSL 1.0.2k (#457) (bpo-2835)
https://github.com/python/cpython/commit/002f778ecab98f4725a08f35d68f78559a13e47a

**Comment by ned-deily** [comment]
New changeset 8d41de62b9e21090c3a1ccb951ba7034a2b74180 by Ned Deily in branch '2.7':
bpo-29572: Update macOS installer build to OpenSSL 1.0.2k (#457) (bpo-2836)
https://github.com/python/cpython/commit/8d41de62b9e21090c3a1ccb951ba7034a2b74180
