### ISSUE TITLE
Windows Buildbot 2.7 is broken

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73756]
BPO | [29570](https://bugs.python.org/issue29570)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @methane, @zware, @serhiy-storchaka, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-15.03:46:50.461>
created_at = <Date 2017-02-15.16:54:36.026>
labels = ['tests', 'OS-windows']
title = 'Windows Buildbot 2.7 is broken'
updated_at = <Date 2017-05-15.08:47:25.310>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-15.08:47:25.310>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-15.03:46:50.461>
closer = 'zach.ware'
components = ['Tests', 'Windows']
creation = <Date 2017-02-15.16:54:36.026>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29570
keywords = ['buildbot']
message_count = 9.0
messages = ['287863', '293620', '293629', '293634', '293658', '293662', '293666', '293671', '293688']
nosy_count = 8.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'methane', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29570'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
Example of failure:
http://buildbot.python.org/all/builders/AMD64%20Windows8%202.7/builds/67/steps/test/logs/stdio

FAIL: test_incrementaldecoder (test.test_codecencodings_iso2022.Test_ISO2022_KR)
=\> failure with newline, maybe caused by the migration to GitHub: see issue bpo-29530

ERROR: test_bug_1727780 (test.test_random.WichmannHill_TestBasicOps)
ImportError: No module named random
=\> ... no idea, can it be related to the commit 0f48ecddfb79ef541500ecfcbda0b4178af1cc29 which only changes a comment!?

**Comment by serhiy-storchaka** [comment]
test_bug_1727780 failure looks related to newlines conversion.

**Comment by vstinner** [comment]
Oh I forgot to cmose this old issue. It was fixed in the meanwhile.

@Serhiy: if you saw a bug recently, please open a new issue.

**Comment by serhiy-storchaka** [comment]
It doesn't look fixed. I found this issue because I got a report about buildbot failure from buildbot@python.org yesterday.

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%202.7/builds/81/steps/test/logs/stdio

test_random is failed when read \*.pck files. They are marked as binary in .gitattributes, but this is not enough. Seems the attribute "binary" only means that text diff is not used. For disabling newlines translations "eol=lf" should be used.

**Comment by zware** [comment]
Jeremy, have you recreated your checkouts since .gitattributes was committed?

**Comment by jkloth** [comment]
All builders have been reset and pass, with the exception of the VS9 one which is a different problem.

**Comment by zware** [comment]
Thank you Jeremy, we'll call this one closed now.  We should open a new issue about the VS9.0 builder failure, which as you say is entirely unrelated.

**Comment by serhiy-storchaka** [comment]
Thank you Jeremy.

**Comment by vstinner** [comment]
Yeah, thank you Jeremy!
