### ISSUE TITLE
"Built-in Functions" not being functions

### ISSUE THREAD

**Issue by 89042997-fe19-49d2-aba2-a4861a6d999e** [python/cpython#73766]
BPO | [29580](https://bugs.python.org/issue29580)
--- | :---
Nosy | @malemburg, @rhettinger, @bitdancer, @serhiy-storchaka, @pochmann

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-18.01:39:31.829>
created_at = <Date 2017-02-16.17:32:50.607>
labels = ['invalid', 'type-feature', '3.7', 'docs']
title = '"Built-in Functions" not being functions'
updated_at = <Date 2017-02-19.19:09:18.474>
user = 'https://github.com/pochmann'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-19.19:09:18.474>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-18.01:39:31.829>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-02-16.17:32:50.607>
creator = 'Stefan Pochmann'
dependencies = []
files = []
hgrepos = []
issue_num = 29580
keywords = []
message_count = 6.0
messages = ['287961', '287962', '287965', '287967', '288051', '288155']
nosy_count = 6.0
nosy_names = ['lemburg', 'rhettinger', 'r.david.murray', 'docs@python', 'serhiy.storchaka', 'Stefan Pochmann']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29580'
versions = ['Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 89042997-fe19-49d2-aba2-a4861a6d999e** [comment]
About https://docs.python.org/3/library/functions.html: The title "Built-in Functions", the table header "Built-in Functions" and the "functions" in the URL all suggest that what's on this page are functions. But many things on that page don't appear to be functions, like "range" or "dict". They appear to be callable types instead. For example "range":

```pycon
    >>> type(range)
    <class 'type'>
    >>> import types
    >>> isinstance(range, types.FunctionType)
    False
    >>> isinstance(range, types.BuiltinFunctionType)
    False
```


Compare with "abs":

```pycon
    >>> type(abs)
    <class 'builtin_function_or_method'>
    >>> isinstance(abs, types.FunctionType)
    False
    >>> isinstance(abs, types.BuiltinFunctionType)
    True
```


The text between title and table talks about "functions and types", but the title/tableheader/URL disagree.

Also, the table is wrong in saying that "abs()" etc are functions. Should say "abs" instead, i.e., remove the "()".

Many, like "abs", aren't even allowed to be called like that, as it results in "TypeError: abs() takes exactly one argument (0 given)".

**Comment by 89042997-fe19-49d2-aba2-a4861a6d999e** [comment]
The page also contains many references like "As repr(), return a string containing..." where the "()" should be removed.

**Comment by malemburg** [comment]
While "functions" may not be accurate anymore, they are all callables.

Historically, those callables were functions. Later on some of the built-ins were replaced with type objects.

Regarding your last comment: It is common in Python to write "func()" for callables in Python. The "()" signal the callable property.

**Comment by bitdancer** [comment]
Agreed with Marc.  I don't think there is anything to do here.  The fact that python allows classes (which are callables) to be substituted for functions is a strength, but can lead to confusion (and people getting upset when classes end up with lowercase names :)

I think it would be more confusing than helpful to say "Built-in Callables".

**Comment by rhettinger** [comment]
I concur with the other respondents and am going to mark this as closed.

**Comment by serhiy-storchaka** [comment]
See also bpo-11975.
