### ISSUE TITLE
Improve some deprecations in the importlib

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73762]
BPO | [29576](https://bugs.python.org/issue29576)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @serhiy-storchaka, @Carreau
PRs | <li>python/cpython#32</li><li>python/cpython#703</li><li>python/cpython#552</li><li>python/cpython#1285</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-16.02:00:59.787>
created_at = <Date 2017-02-16.01:27:33.887>
labels = ['type-feature', '3.7', 'docs']
title = 'Improve some deprecations in the importlib'
updated_at = <Date 2017-04-29.04:06:51.374>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-29.04:06:51.374>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-16.02:00:59.787>
closer = 'brett.cannon'
components = ['Documentation']
creation = <Date 2017-02-16.01:27:33.887>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29576
keywords = []
message_count = 5.0
messages = ['287908', '287909', '292277', '292286', '292561']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'docs@python', 'serhiy.storchaka', 'mbussonn']
pr_nums = ['32', '703', '552', '1285']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29576'
versions = ['Python 3.7']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
A couple of function in importlib are marked as deprecated in the documentation but do not raise deprecation warnings.

As the same time it would be great to improve some deprecation warnings and docstring to include the version since when this is deprecated. 

This should be take care of by https://github.com/python/cpython/pull/32

**Comment by brettcannon** [comment]
New changeset 1d4601c2c6952d03fc4dda2b041be9aa8713c0bc by Brett Cannon in branch 'master':
bpo-29576: add explicit deprecation for importlib.abc.find_loader() and find_module() (GH-32)
https://github.com/python/cpython/commit/1d4601c2c6952d03fc4dda2b041be9aa8713c0bc

**Comment by serhiy-storchaka** [comment]
This change made test_importlib emitting warnings. See bpo-30158.

**Comment by vstinner** [comment]
This issue introduced new warnings when running test_importlib: see issue bpo-30158.

**Comment by serhiy-storchaka** [comment]
New changeset 3cc8259b71ef784a9f7593f04da96043afe2228a by Serhiy Storchaka in branch 'master':
bpo-30158: Fix deprecation warnings in test_importlib introduced by bpo-29576. (bpo-1285)
https://github.com/python/cpython/commit/3cc8259b71ef784a9f7593f04da96043afe2228a
