### ISSUE TITLE
test_asyncio & test_multiprocessing_forkserver failed

### ISSUE THREAD

**Issue by 0b4ff046-781b-42de-86d9-093dc0009030** [python/cpython#73775]
BPO | [29589](https://bugs.python.org/issue29589)
--- | :---
Nosy | @vstinner, @mwidjaja, @zhangyangyu, @mlouielu
Files | <li>[tests.output](https://bugs.python.org/file46643/tests.output "Uploaded as text/plain at 2017-02-17.13:23:18 by Dima Zhukov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-22.06:26:07.092>
created_at = <Date 2017-02-17.13:23:20.965>
labels = ['type-bug', 'build']
title = 'test_asyncio & test_multiprocessing_forkserver failed'
updated_at = <Date 2018-05-29.11:06:50.834>
user = 'https://bugs.python.org/DimaZhukov'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.11:06:50.834>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-22.06:26:07.092>
closer = 'xiang.zhang'
components = ['Build']
creation = <Date 2017-02-17.13:23:20.965>
creator = 'Dima Zhukov'
dependencies = []
files = ['46643']
hgrepos = []
issue_num = 29589
keywords = []
message_count = 7.0
messages = ['288005', '288188', '288288', '288335', '288338', '288339', '318007']
nosy_count = 5.0
nosy_names = ['vstinner', 'mawidjaj', 'xiang.zhang', 'Dima Zhukov', 'louielu']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29589'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0b4ff046-781b-42de-86d9-093dc0009030** [comment]
Hi, i'm new to Python. Just have downloded source code and tried to install it, but "make test" failed 2 test: test_asyncio  and test_multiprocessing_forkserver. How bad is it and what should i do? Logs attached

**Comment by zhangyangyu** [comment]
Hi Dima, can you stably reproduce the failures? Or try with the latest 3.6 code?

**Comment by 0b4ff046-781b-42de-86d9-093dc0009030** [comment]
Just tried with 3.4.6 version. Same test failed

**Comment by 01b59998-d5e4-4468-854c-89f56688811a** [comment]
Both test_asyncio & test_multiprocessing_forkserver work for me. I'm on the latest 3.6 and Mac OS 10.11.6

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Both test_asyncio & test_multiprocessing_forkserver passed on latest 3.6 and 4.8.3-1-ARCH.

**Comment by zhangyangyu** [comment]
Hmm, it seems not Python's fault. I can't reproduce the failure either. So I am going to close this issue.
