### ISSUE TITLE
Unfinished sentence in howto/clinic.rst

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73782]
BPO | [29596](https://bugs.python.org/issue29596)
--- | :---
Nosy | @larryhastings, @vadmium, @Carreau, @Mariatta
PRs | <li>python/cpython#1710</li><li>python/cpython#1975</li><li>python/cpython#1976</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-06.21:40:13.830>
created_at = <Date 2017-02-18.01:12:12.615>
labels = ['3.7', 'expert-argument-clinic', 'docs']
title = 'Unfinished sentence in howto/clinic.rst'
updated_at = <Date 2017-06-06.21:40:13.829>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.21:40:13.829>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-06.21:40:13.830>
closer = 'Mariatta'
components = ['Documentation', 'Argument Clinic']
creation = <Date 2017-02-18.01:12:12.615>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29596
keywords = []
message_count = 7.0
messages = ['288048', '288532', '294737', '295294', '295303', '295305', '295306']
nosy_count = 6.0
nosy_names = ['larry', 'docs@python', 'martin.panter', 'mbussonn', 'Mariatta', 'Steven Rumbalski']
pr_nums = ['1710', '1975', '1976']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29596'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
Around line 1400 of [Doc/howto/clinic.rst](https://github.com/python/cpython/blob/main/Doc/howto/clinic.rst)

  ``two-pass``
    A buffer like ``buffer``.  However, a two-pass buffer can only
    be written once, and it prints out all text sent to it during
    all of processing, even from Clinic blocks *after* the

I've rarely be kept in such suspense ! Unless it's a reference to Monty Python's "The Man Who Finishes Other People's Sentences". In which case, I must say it's

**Comment by a1284355-ccfa-4c5d-85ad-0c500c13c3ef** [comment]
Truncated sentence was always truncated.

Introduced on commit bebf73511a1250fc768bcb7192b5b3c3fd04d8f2
from Issue bpo-20287: Argument Clinic's output is now configurable, allowing
delaying its output or even redirecting it to a separate file.
https://github.com/python/cpython/commit/bebf73511a1250fc768bcb7192b5b3c3fd04d8f2

Another issue from the same commit that still exists today:

buffer
    Save up all most of the output from Clinic, to be written into your file near the end.
            ^^^^^^^^

Perhaps what was meant was 'almost all'?

**Comment by vadmium** [comment]
Currently for the “buffer” destination, it says

Suppress . . ., write . . . to ``block``, and write everything else to ``file``.

Would it be more correct to change “file“ to “buffer”? I.e.

Suppress . . ., write . . . to ``block``, and write everything else to ``buffer``.

**Comment by Mariatta** [comment]
New changeset ec19ba210bba2c3097232a05d7dbe093beb5f833 by Mariatta (gfyoung) in branch 'master':
bpo-29596: Improve clinic howto documentation (GH-1710)
https://github.com/python/cpython/commit/ec19ba210bba2c3097232a05d7dbe093beb5f833

**Comment by Mariatta** [comment]
New changeset 063f0b358331322d84f85008e6c01f80ff321fd6 by Mariatta (gfyoung) in branch '3.6':
bpo-29596: Improve clinic howto documentation (GH-1710) (GH-1976)
https://github.com/python/cpython/commit/063f0b358331322d84f85008e6c01f80ff321fd6

**Comment by Mariatta** [comment]
New changeset ee9de30aa0dbcfd848e4200944674a084d963588 by Mariatta (gfyoung) in branch '3.5':
bpo-29596: Improve clinic howto documentation (GH-1710) (GH-1975)
https://github.com/python/cpython/commit/ee9de30aa0dbcfd848e4200944674a084d963588

**Comment by Mariatta** [comment]
Thanks everyone :)
