### ISSUE TITLE
Write unit tests for pdb module

### ISSUE THREAD

**Issue by ea9bdd8c-963f-4dbe-99f7-67641d814d76** [python/cpython#73784]
BPO | [29598](https://bugs.python.org/issue29598)
--- | :---
Nosy | @methane, @xdegaye, @serhiy-storchaka, @micgeronimo, @isidentical
PRs | <li>python/cpython#218</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-02-19.09:49:40.599>
labels = ['3.7', 'tests']
title = 'Write unit tests for pdb module'
updated_at = <Date 2019-11-30.16:37:13.325>
user = 'https://github.com/micgeronimo'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-30.16:37:13.325>
actor = 'BTaskaya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-02-19.09:49:40.599>
creator = 'Artem Muterko'
dependencies = []
files = []
hgrepos = []
issue_num = 29598
keywords = []
message_count = 6.0
messages = ['288123', '288126', '288349', '288459', '288593', '357659']
nosy_count = 5.0
nosy_names = ['methane', 'xdegaye', 'serhiy.storchaka', 'Artem Muterko', 'BTaskaya']
pr_nums = ['218']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29598'
versions = ['Python 3.7']
```

</p></details>

**Comment by ea9bdd8c-963f-4dbe-99f7-67641d814d76** [comment]
I want to write unit tests for pdb module of stdlib. Should I create one pull request for entire module or should I split work into several pull requests?

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Please use one single PR only when the tests are focused on a single topic and can be collected in their own class. When the tests are focused on breakpoints for example.

**Comment by serhiy-storchaka** [comment]
It would be better to move all tests for internal functions in separate TestCase class. It should be clear that this is testing of implementation details and we are free to change tests when change the implementation.

There are some tests for find_function(). They should be moved too. Note that there is a bug in find_function() (it opens a file with default encoding).

Tests for internal functions don't free us from testing the same functionality as a part of high level functions.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
> Note that there is a bug in find_function() (it opens a file with default encoding).

Please open an issue.

**Comment by serhiy-storchaka** [comment]
And decorate this test class with test.support.cpython_only.
