### ISSUE TITLE
__new__ / __init__ calls during unpickling not documented correctly

### ISSUE THREAD

**Issue by bef3b989-2e47-4e9c-91d3-504408b50b75** [python/cpython#73783]
BPO | [29597](https://bugs.python.org/issue29597)
--- | :---
Nosy | @pkch, @serhiy-storchaka
Superseder | <li>bpo-27635: pickle documentation says that unpickling may not call __new__</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-18.20:47:07.686>
created_at = <Date 2017-02-18.20:31:11.876>
labels = ['docs']
title = '__new__ / __init__ calls during unpickling not documented correctly'
updated_at = <Date 2017-02-18.20:47:07.684>
user = 'https://github.com/pkch'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-18.20:47:07.684>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-18.20:47:07.686>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-02-18.20:31:11.876>
creator = 'max'
dependencies = []
files = []
hgrepos = []
issue_num = 29597
keywords = []
message_count = 2.0
messages = ['288088', '288090']
nosy_count = 3.0
nosy_names = ['docs@python', 'max', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '27635'
type = None
url = 'https://bugs.python.org/issue29597'
versions = ['Python 3.6']
```

</p></details>

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
According to the [docs](https://docs.python.org/3/library/pickle.html#pickling-class-instances):

> Note: At unpickling time, some methods like `__getattr__()`, `__getattribute__()`, or `__setattr__()` may be called upon the instance. In case those methods rely on some internal invariant being true, the type should implement `__getnewargs__()` or `__getnewargs_ex__()` to establish such an invariant; otherwise, neither `__new__()` nor `__init__()` will be called.

It seems, however, that this note is incorrect. First, `__new__` is called even if `__getnewargs__` isn't implemented. Second, `__init__` is not called even if it is (while the note didn't say that `__init__` would be called when `__getnewargs__` is defined, the wording does seem to imply it).


```py
class A:
    def __new__(cls, *args):
        print('__new__ called with', args)
        return object.__new__(cls)
    
    def __init__(self, *args):
        print('__init__ called with', args)
        self.args = args
        
    def __getnewargs__(self):
        print('called')
        return ()
    
a = A(1)
s = pickle.dumps(a)
a = pickle.loads(s) # __new__ called, not __init__
delattr(A, '__getnewargs__') 
a = A(1)
s = pickle.dumps(a)
a = pickle.loads(s) # __new__ called, not __init__
```

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-27635.
