### ISSUE TITLE
Returning an exception object from a coroutine triggers implicit exception chaining?!?

### ISSUE THREAD

**Issue by njsmith** [python/cpython#73786]
BPO | [29600](https://bugs.python.org/issue29600)
--- | :---
Nosy | @njsmith, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#644</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-12.21:04:58.138>
created_at = <Date 2017-02-19.13:44:49.407>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Returning an exception object from a coroutine triggers implicit exception chaining?!?'
updated_at = <Date 2017-03-14.13:38:14.161>
user = 'https://github.com/njsmith'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-14.13:38:14.161>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-12.21:04:58.138>
closer = 'yselivanov'
components = ['Interpreter Core']
creation = <Date 2017-02-19.13:44:49.407>
creator = 'njs'
dependencies = []
files = []
hgrepos = []
issue_num = 29600
keywords = []
message_count = 4.0
messages = ['288133', '289503', '289577', '289583']
nosy_count = 3.0
nosy_names = ['njs', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['644']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29600'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by njsmith** [comment]
The following code prints "KeyError()", which is obviously wrong and rather baffling. Just passing an exception object around \*as an object* should not trigger implicit exception chaining!

If you replace the async functions with regular functions then it prints "None", as expected.

Checked on 3.5, 3.6, and more-or-less current master -- bug is present in all 3.

\------------

```py
async def f():
    return ValueError()

async def g():
    try:
        raise KeyError
    except:
        value_error = await f()
        print(repr(value_error.__context__))
```


try:
    g().send(None)
except StopIteration:
    pass

**Comment by 1st1** [comment]
What a bizarre bug.  Created a PR with a fix.  

Nathaniel, please put me in a nosy list when you submit issues about generators/coroutines.

**Comment by serhiy-storchaka** [comment]
I am wondering how much of other uses of PyErr_SetObject() are affected by similar bugs?

**Comment by 1st1** [comment]
> I am wondering how much of other uses of PyErr_SetObject() are affected by similar bugs?

Only when we use an exception to carry a return value.  AFAIK StopIteration is the only such case.
