### ISSUE TITLE
Github organization link is secret and not accessible from core-dev guide

### ISSUE THREAD

**Issue by CuriousLearner** [python/cpython#73785]
BPO | [29599](https://bugs.python.org/issue29599)
--- | :---
Nosy | @ncoghlan, @berkerpeksag, @CuriousLearner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-19.13:47:23.576>
created_at = <Date 2017-02-19.11:37:36.752>
labels = ['type-bug', 'docs']
title = 'Github organization link is secret and not accessible from core-dev guide'
updated_at = <Date 2017-02-19.14:40:46.844>
user = 'https://github.com/CuriousLearner'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-19.14:40:46.844>
actor = 'CuriousLearner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-19.13:47:23.576>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-02-19.11:37:36.752>
creator = 'CuriousLearner'
dependencies = []
files = []
hgrepos = []
issue_num = 29599
keywords = []
message_count = 3.0
messages = ['288131', '288134', '288140']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'docs@python', 'berker.peksag', 'CuriousLearner']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29599'
versions = []
```

</p></details>

**Comment by CuriousLearner** [comment]
On visiting link: https://docs.python.org/devguide/coredev.html#github

The first sentence is "You will be added to the Python core team on GitHub."

The ``Python core team`` refers to a link to Github which is not accessible to anyone except for those who are part of the organization.

I'd like to suggest to either remove the link from the documentation or make the team visible to public.

**Comment by berkerpeksag** [comment]
Thanks for the report. I agree that the link can be removed. We have a separate issue tracker for [devguide](https://devguide.python.org) at https://github.com/python/devguide/issues Please report this there.

**Comment by CuriousLearner** [comment]
Thanks a lot Berker! I've reported the issue there at https://github.com/python/devguide/issues/124
