### ISSUE TITLE
ssl do_handshake fails on https-proxy (aka. https over https-proxy)

### ISSUE THREAD

**Issue by 3ff34944-17fb-4040-a532-bb0170fb365e** [python/cpython#73796]
BPO | [29610](https://bugs.python.org/issue29610)
--- | :---
Nosy | @tiran, @vadmium
Superseder | <li>bpo-29394: Cannot tunnel TLS connection through TLS connection</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-02-21.04:30:22.840>
created_at = <Date 2017-02-21.03:29:07.104>
labels = ['expert-SSL', 'type-bug']
title = 'ssl do_handshake fails on https-proxy (aka. https over https-proxy)'
updated_at = <Date 2017-02-21.04:30:22.825>
user = 'https://bugs.python.org/PhusLu'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-21.04:30:22.825>
actor = 'martin.panter'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-02-21.04:30:22.840>
closer = 'martin.panter'
components = ['SSL']
creation = <Date 2017-02-21.03:29:07.104>
creator = 'Phus Lu'
dependencies = []
files = []
hgrepos = []
issue_num = 29610
keywords = []
message_count = 2.0
messages = ['288259', '288265']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'martin.panter', 'Phus Lu']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29394'
type = 'behavior'
url = 'https://bugs.python.org/issue29610'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 3ff34944-17fb-4040-a532-bb0170fb365e** [comment]
Background:

I'm working on adding https-proxy[1] support to python-requests https://github.com/phuslu/requests_httpsproxy

Issue:
ssl module(python 2.7) counld establish ssl handshakes over a https-proxy

Reproduce Steps:
I setup a https-proxy in bwg.phus.lu:443

```pycon
>>> import socket,ssl
>>> sock = ssl.wrap_socket(socket.create_connection(('bwg.phus.lu', 443)))
>>> sock.sendall('CONNECT httpbin.org:443 HTTP/1.0\r\n\r\n')
36
>>> sock.recv()
'HTTP/1.1 200 OK\r\n\r\n'
>>> ssl.wrap_socket(sock)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    ssl.wrap_socket(sock)
  File "/usr/lib/python2.7/ssl.py", line 943, in wrap_socket
    ciphers=ciphers)
  File "/usr/lib/python2.7/ssl.py", line 611, in __init__
    self.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
SSLError: [SSL: UNKNOWN_ALERT_TYPE] unknown alert type (_ssl.c:661)
```



[1] https://www.chromium.org/developers/design-documents/secure-web-proxy

**Comment by vadmium** [comment]
It looks like you are trying to tunnel one SSL or TLS connection through another SSL/TLS connection (instead of through a plain OS socket). There is already a bug recently opened about this: bpo-29394.

Basically, the SSL module doesn’t support this, and the documentation should be clarified to say something like wrap_socket() only accepts basic socket.socket() objects, not subclasses. However, in Python 3.5+ I think you could use the BIO layer to hook in your intermediate SSL socket (or any other transport).
