### ISSUE TITLE
TextIOWrapper's write_through option behave differently between C and pure Python implementation.

### ISSUE THREAD

**Issue by methane** [python/cpython#73797]
BPO | [29611](https://bugs.python.org/issue29611)
--- | :---
Nosy | @benjaminp, @methane, @serhiy-storchaka
Superseder | <li>bpo-15571: Python version of TextIOWrapper ignores &quot;write_through&quot; arg</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-19.15:08:22.548>
created_at = <Date 2017-02-21.09:50:54.072>
labels = ['invalid', 'type-bug', '3.7', 'expert-IO']
title = "TextIOWrapper's write_through option behave differently between C and pure Python implementation."
updated_at = <Date 2017-05-19.15:08:22.546>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-19.15:08:22.546>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-19.15:08:22.548>
closer = 'serhiy.storchaka'
components = ['IO']
creation = <Date 2017-02-21.09:50:54.072>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 29611
keywords = []
message_count = 2.0
messages = ['288282', '293957']
nosy_count = 4.0
nosy_names = ['benjamin.peterson', 'stutzbach', 'methane', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = '15571'
type = 'behavior'
url = 'https://bugs.python.org/issue29611'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by methane** [comment]
In C implementation, write() calls underlaying flush() method when write_through=True.

https://github.com/python/cpython/blob/3.6/Modules/_io/textio.c

    if (self->write_through)
        text_needflush = 1;
    if (self->line_buffering &&
        (haslf ||
         PyUnicode_FindChar(text, '\r', 0, PyUnicode_GET_LENGTH(text), 1) != -1))
        needflush = 1;


But pure Python implementation doesn't care write_through option at all.

https://github.com/python/cpython/blob/3.6/Lib/_pyio.py

```py
        self.buffer.write(b)
        if self._line_buffering and (haslf or "\r" in s):
            self.flush()
```


When PyPy 3.5 is released, this difference may affects PyPy users.
(I hadn't checked how PyPy provide io module.)

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-15571.
