### ISSUE TITLE
pip_gui

### ISSUE THREAD

**Issue by 68a7c046-34fc-45aa-9421-c6df4435992a** [python/cpython#73794]
BPO | [29608](https://bugs.python.org/issue29608)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ncoghlan, @ned-deily, @bitdancer, @berkerpeksag, @dstufft, @mec-is
Files | <li>[Screenshot (70).png](https://bugs.python.org/file46655/Screenshot%20%2870%29.png "Uploaded as image/png at 2017-02-20.20:35:01 by Shyam Sunder"): Gui Bug</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-20.22:54:45.125>
created_at = <Date 2017-02-20.20:35:01.486>
labels = []
title = 'pip_gui'
updated_at = <Date 2017-02-20.22:57:44.310>
user = 'https://bugs.python.org/ShyamSunder'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-20.22:57:44.310>
actor = 'ezio.melotti'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-20.22:54:45.125>
closer = 'berker.peksag'
components = []
creation = <Date 2017-02-20.20:35:01.486>
creator = 'Shyam Sunder'
dependencies = []
files = ['46655']
hgrepos = []
issue_num = 29608
keywords = []
message_count = 2.0
messages = ['288238', '288249']
nosy_count = 10.0
nosy_names = ['rhettinger', 'terry.reedy', 'ncoghlan', 'ned.deily', 'r.david.murray', 'berker.peksag', 'dstufft', 'upendra-k14', 'lorenzogotuned', 'Shyam Sunder']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29608'
versions = ['Python 2.7']
```

</p></details>

**Comment by 68a7c046-34fc-45aa-9421-c6df4435992a** [comment]
I am not able see the text of the radio button clearly in the welcome page of search and install packages

**Comment by berkerpeksag** [comment]
pip_gui is not part of the Python standard library. Please use https://github.com/upendra-k14/pip_gui/issues to report your problem.
