### ISSUE TITLE
Broken stack_effect for CALL_FUNCTION_EX

### ISSUE THREAD

**Issue by 3d8b0940-bf71-4d2d-940d-1c177a2e5f08** [python/cpython#73793]
BPO | [29607](https://bugs.python.org/issue29607)
--- | :---
Nosy | @methane, @serhiy-storchaka, @serprex, @MatthieuDartiailh
PRs | <li>python/cpython#202</li><li>python/cpython#219</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-02-21.17:34:36.718>
created_at = <Date 2017-02-20.19:50:39.357>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Broken stack_effect for CALL_FUNCTION_EX'
updated_at = <Date 2017-03-31.16:36:13.277>
user = 'https://github.com/MatthieuDartiailh'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:13.277>
actor = 'dstufft'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-02-21.17:34:36.718>
closer = 'methane'
components = ['Interpreter Core']
creation = <Date 2017-02-20.19:50:39.357>
creator = 'mdartiailh'
dependencies = []
files = []
hgrepos = []
issue_num = 29607
keywords = []
message_count = 6.0
messages = ['288230', '288232', '288292', '288297', '288311', '288312']
nosy_count = 4.0
nosy_names = ['methane', 'serhiy.storchaka', 'Demur Rumed', 'mdartiailh']
pr_nums = ['202', '219', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29607'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3d8b0940-bf71-4d2d-940d-1c177a2e5f08** [comment]
The computation of the stack_effect of the CALL_FUNCTION_EX does not reflect the use of the argument to the opcode.

Currently stack_effect expect two flags (one on 0x01 and one on 0x02) corresponding to whether positional arguments and keyword arguments are being passed. However in the current implementation the argument of CALL_FUNCTION_EX is either 0 or 1 depending on the presence of keyword arguments. According to Serhiy Storchaka, the behavior of stack_effect is a left-over of the previous implementation and should be fixed.

**Comment by serhiy-storchaka** [comment]
The fix LGTM. Please add the [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) entry.

**Comment by 3d8b0940-bf71-4d2d-940d-1c177a2e5f08** [comment]
I added the [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) entry under Python 3.7. I guess it will be backported to 3.6 when cherry-pinking.

**Comment by serhiy-storchaka** [comment]
New changeset 3a9ac827c7c87dffc60c4200323948551bcb6662 by Serhiy Storchaka in branch 'master':
bpo-29607: Fix stack_effect computation for CALL_FUNCTION_EX (#202)
https://github.com/python/cpython/commit/3a9ac827c7c87dffc60c4200323948551bcb6662

**Comment by methane** [comment]
New changeset 3ab24bdd47fdd9d45719ad49f93d3878d4442d7e by GitHub in branch '3.6':
bpo-29607: Fix stack_effect computation for CALL_FUNCTION_EX (GH-219)
https://github.com/python/cpython/commit/3ab24bdd47fdd9d45719ad49f93d3878d4442d7e

**Comment by methane** [comment]
Thanks, Matthieu.
