### ISSUE TITLE
telnetlib.Telnet.write gives confusing error message when a string is passed in

### ISSUE THREAD

**Issue by 2df14aea-354c-46a6-8f5c-342c9f465901** [python/cpython#73807]
BPO | [29621](https://bugs.python.org/issue29621)
--- | :---
Nosy | @jackdied, @bitdancer, @berkerpeksag, @johnthagen, @corona10

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.06:35:59.082>
created_at = <Date 2017-02-22.16:35:21.364>
labels = ['3.7', 'type-feature', 'library']
title = 'telnetlib.Telnet.write gives confusing error message when a string is passed in'
updated_at = <Date 2017-05-05.06:35:59.080>
user = 'https://github.com/johnthagen'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.06:35:59.080>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.06:35:59.082>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-02-22.16:35:21.364>
creator = 'John Hagen'
dependencies = []
files = []
hgrepos = []
issue_num = 29621
keywords = []
message_count = 5.0
messages = ['288371', '292500', '292501', '292502', '293046']
nosy_count = 5.0
nosy_names = ['jackdied', 'r.david.murray', 'berker.peksag', 'John Hagen', 'corona10']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29621'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2df14aea-354c-46a6-8f5c-342c9f465901** [comment]
I was recently helping someone learn Python 3 from Python 2 and they were confused by error resulting from the following easy-to-make mistake:

```py
import telnetlib

tn = telnetlib.Telnet('localhost')
tn.write('hello')
```


```pytb
Traceback (most recent call last):
  File "/Users/user/PycharmProjects/python-test/main.py", line 4, in <module>
    tn.write('hello')
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/telnetlib.py", line 287, in write
    if IAC in buffer:
TypeError: 'in <string>' requires string as left operand, not bytes
```


What is confusing is that the solution is to pass in `bytes`, not a `str`, but the place where this manifests is in an `in` operator with the first argument as a `bytes` (telnetlib.IAC).

Perhaps a simple isinstance(buffer, bytes) could be used to throw a `TypeError` or something a bit more helpful.

It also doesn't help that for some reason Googling "python telnet" only seems to bring up the Python 2 docs link, rather than Python 3 or both.

**Comment by corona10** [comment]
I submitted PR to handle this issue like this way.

```py
tn.write([b'data sample without IAC'])
File "/Users/corona10/cpython/Lib/telnetlib.py", line 288, in write
    raise TypeError('%s must be a bytes-like type.' % buffer)
TypeError: [b'data sample without IAC'] must be a bytes-like type.
```

**Comment by bitdancer** [comment]
We generally don't do this kind of type checking in the standard library.  The message may not be clear, but it is accurate and decipherable, especially given the fact that the write parameter name is 'buffer'.  I don't think anything should be done here.  If you want type checking use the types module :)

Thanks for the PR, @corona10, but I think we should just close this issue.  Other devs may disagree, though, so I'm not closing it myself.

On the other hand, enhancing telnetlib to also work with strings might be a nice project for someone.  It would require some design discussion, though, so I don't think anyone should hop on it without discussing it somewhere first (python-ideas, maybe?).

**Comment by corona10** [comment]
Thanks for the response. I agree with you. :)

**Comment by berkerpeksag** [comment]
I agree with David. The documentation of the method starts with "Write a byte string to the socket [...]" and the example at https://docs.python.org/3/library/telnetlib.html#telnet-example is pretty clear.
