### ISSUE TITLE
SimpleXMLRPCDispatcher._dispatch mangles tracebacks when invoking RPC calls through _dispatch

### ISSUE THREAD

**Issue by 391bd9a6-b6c9-41a7-bb54-73f1ff581e7a** [python/cpython#73801]
BPO | [29615](https://bugs.python.org/issue29615)
--- | :---
Nosy | @loewis, @serhiy-storchaka, @petr-motejlek
PRs | <li>python/cpython#260</li><li>python/cpython#478</li><li>python/cpython#479</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.21:13:55.521>
created_at = <Date 2017-02-21.20:30:25.353>
labels = ['3.7', 'type-bug', 'library']
title = 'SimpleXMLRPCDispatcher._dispatch mangles tracebacks when invoking RPC calls through _dispatch'
updated_at = <Date 2017-03-31.16:36:09.952>
user = 'https://github.com/petr-motejlek'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:09.952>
actor = 'dstufft'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-17.21:13:55.521>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-02-21.20:30:25.353>
creator = 'petr@motejlek.net'
dependencies = []
files = []
hgrepos = []
issue_num = 29615
keywords = []
message_count = 4.0
messages = ['288319', '290297', '290298', '290351']
nosy_count = 3.0
nosy_names = ['loewis', 'serhiy.storchaka', 'petr@motejlek.net']
pr_nums = ['260', '478', '479', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29615'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 391bd9a6-b6c9-41a7-bb54-73f1ff581e7a** [comment]
Hello,

We discovered that SimpleXMLRPCDispatcher mangles tracebacks printed from within the invoked RPC methods when an object that has \_dispatch(method, params) defined has been registered with it

Steps to reproduce
- use https://docs.python.org/3.4/library/xmlrpc.server.html#xmlrpc.server.SimpleXMLRPCServer.register_instance and register within SimpleXMLRPCDispatcher an object with the \_dispatch(method, params) method defined
- invoke any RPC method that prints a traceback (perhaps raise an exception in it, catch it and use logging.exception to log it) --\> the traceback will display a very strange looking KeyError (its value being the name of the invoked method) and then the actual exception that was fed into logging.exception

The reason for this is that SimpleXMLRPCDispatcher.\_dispatch first attempts to acquire the function to invoke by reading from the functions registered with the dispatcher. When this attempt fails, KeyError is raised. During its handling different approaches are taken to acquire the function and for all but one when the function is acquired, handling of the KeyError ends and the function is called properly, outside of the except block

However, in the case of objects that define the \_dispatch(method, params) function, the \_dispatch(method, params) function is called straight away, still within the except block handling the KeyError, and this leads to the mangled traceback

This behavior is neither documented, nor expected (we believe) and thus the code should be changed

Will submit a PR (incl. tests) for this later on

**Comment by serhiy-storchaka** [comment]
New changeset c6e199f2e9a2514c3fd220aaa4bd23fa1d6da8c9 by Serhiy Storchaka (Petr Motejlek) in branch '3.5':
bpo-29615: backport to 3.5 (#479)
https://github.com/python/cpython/commit/c6e199f2e9a2514c3fd220aaa4bd23fa1d6da8c9

**Comment by serhiy-storchaka** [comment]
New changeset 3405792b024e9c6b70c0d2355c55a23ac84e1e67 by Serhiy Storchaka (Petr Motejlek) in branch '3.6':
bpo-29615: backport to 3.6 (#478)
https://github.com/python/cpython/commit/3405792b024e9c6b70c0d2355c55a23ac84e1e67

**Comment by serhiy-storchaka** [comment]
New changeset 3c6314c08d8ab1cfefbf6c2e27c095a7d4ba5f6e by Serhiy Storchaka (Petr Motejlek) in branch 'master':
bpo-29615: SimpleXMLRPCDispatcher no longer chains KeyError (#260)
https://github.com/python/cpython/commit/3c6314c08d8ab1cfefbf6c2e27c095a7d4ba5f6e
