### ISSUE TITLE
configparser.ConfigParser.read() does not accept Pathlib path as a single argument.

### ISSUE THREAD

**Issue by 3873e664-9d3f-406b-bb16-a4d912ca397a** [python/cpython#73809]
BPO | [29623](https://bugs.python.org/issue29623)
--- | :---
Nosy | @mcepl, @berkerpeksag, @DavidCEllis
PRs | <li>python/cpython#242</li><li>python/cpython#432</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-03.18:25:22.565>
created_at = <Date 2017-02-22.18:48:55.601>
labels = ['3.7', 'type-bug', 'library']
title = 'configparser.ConfigParser.read() does not accept Pathlib path as a single argument.'
updated_at = <Date 2018-03-06.19:26:27.420>
user = 'https://github.com/DavidCEllis'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-06.19:26:27.420>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-03.18:25:22.565>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-02-22.18:48:55.601>
creator = 'David Ellis'
dependencies = []
files = []
hgrepos = []
issue_num = 29623
keywords = []
message_count = 3.0
messages = ['288378', '290326', '290328']
nosy_count = 3.0
nosy_names = ['mcepl', 'berker.peksag', 'David Ellis']
pr_nums = ['242', '432']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29623'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3873e664-9d3f-406b-bb16-a4d912ca397a** [comment]
Trying to use configparser.ConfigParser.read on a pathlib object results in a TypeError. If supplied in a list it works as expected.

```pycon
Repro:
    >>> import pathlib, configparser
    >>> configparser.ConfigParser().read(pathlib.Path('some.ini'))
```


    TypeError: 'PosixPath' object is not iterable

The issue appears to be line 690 which checks for str before attempting to iterate and doesn't check for os.PathLike (or bytes?).

This was actually mentioned as an example where pathlib did not work here: https://bugs.python.org/issue22570

**Comment by berkerpeksag** [comment]
New changeset 21ce65aa67f0dc63002ab0a5fb21ef921cf5279e by Berker Peksag in branch '3.6':
[3.6] bpo-29623: Make PathLike objects work with ConfigParser.read() (#242) (#432)
https://github.com/python/cpython/commit/21ce65aa67f0dc63002ab0a5fb21ef921cf5279e

**Comment by berkerpeksag** [comment]
New changeset 85b8d01c916b482dac937b93ede1e53b1db0361c by Berker Peksag (David Ellis) in branch 'master':
bpo-29623: Make PathLike objects work with ConfigParser.read() (#242)
https://github.com/python/cpython/commit/85b8d01c916b482dac937b93ede1e53b1db0361c
