### ISSUE TITLE
REPL tab-completion triggers code execution

### ISSUE THREAD

**Issue by df2c16d9-e835-4bf0-a373-441d4d104450** [python/cpython#73816]
BPO | [29630](https://bugs.python.org/issue29630)
--- | :---
Nosy | @tiran, @serhiy-storchaka, @mlouielu, @franciscod
PRs | <li>python/cpython#248</li>
Files | <li>[wat.py](https://bugs.python.org/file46662/wat.py "Uploaded as text/plain at 2017-02-23.08:14:27 by @franciscod")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-23.12:44:37.673>
created_at = <Date 2017-02-23.08:14:27.498>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'REPL tab-completion triggers code execution'
updated_at = <Date 2017-02-23.12:44:37.672>
user = 'https://github.com/franciscod'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-23.12:44:37.672>
actor = 'Francisco Demartino'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-23.12:44:37.673>
closer = 'Francisco Demartino'
components = ['Interpreter Core']
creation = <Date 2017-02-23.08:14:27.498>
creator = 'Francisco Demartino'
dependencies = []
files = ['46662']
hgrepos = []
issue_num = 29630
keywords = []
message_count = 12.0
messages = ['288420', '288421', '288422', '288424', '288427', '288428', '288431', '288433', '288435', '288438', '288439', '288444']
nosy_count = 4.0
nosy_names = ['christian.heimes', 'serhiy.storchaka', 'louielu', 'Francisco Demartino']
pr_nums = ['248']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29630'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by df2c16d9-e835-4bf0-a373-441d4d104450** [comment]
On the REPL, when autocompleting with the TAB key, getattr is called, potentially triggering code execution.

This took me by surprise. Until you press RETURN, it should be pretty safe to go around autocompleting with certainty that you won't run any code. But that might be just my opinion.

What do you think?

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
I can reproduce the problem in Python 3.7.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Could it be the problem from readline?
Using python 2 with readline trigger same behavior.

**Comment by df2c16d9-e835-4bf0-a373-441d4d104450** [comment]
This branch (working on the PR) fixes it:

https://github.com/franciscod/cpython/tree/bpo-29630

**Comment by serhiy-storchaka** [comment]
This is how Python works. Accessing an attribute (and even checking that the attribute exists) can trigger code executing.

Changes in https://github.com/franciscod/cpython/tree/bpo-29630 break autocompliting of proxy objects. And in any case it triggers code execution due to calling eval().

I think this is not a bug and changing current behavior can decrease usability.

**Comment by tiran** [comment]
I agree with Serhiy. There is no way to safely inspect any Python object without triggering some dunder functions like \_\_getattr__, \_\_getattribute__ or \_\_dir__.

**Comment by df2c16d9-e835-4bf0-a373-441d4d104450** [comment]
I've updated that branch and made a pull request (https://github.com/python/cpython/pull/248)

I think this is a good compromise: inspect.getattr_static can tell if it's a property, and in that case we don't call getattr on it to prevent code execution on the completion. If it isn't a property, the current codepath is preserved.

**Comment by tiran** [comment]
Your change is not backwards compatible and makes auto-completion less useful.

**Comment by df2c16d9-e835-4bf0-a373-441d4d104450** [comment]
> There is no way to safely inspect any Python object without triggering some dunder functions like \_\_getattr__, \_\_getattribute__ or \_\_dir__.

But somehow inspect.getattr_static can do it?

> Your change is not backwards compatible and makes auto-completion less useful.

Why is it less useful? The only change is not executing property getters when showing completion options. It's removing a surprising code execution before the newline is received.

Should CPython keep backwards compatibility of this execution-on-completion at the REPL?

**Comment by serhiy-storchaka** [comment]
It is less useful because don't work with dynamic attributes (with \_\_getattar__ and \_\_getattribute__). And if executing property getters is an issue (I don't think it is), this change doesn't fix it completely.

**Comment by tiran** [comment]
inspect.getattr_static \*tries* to get attributes without triggering dunder methods. It's neither fully compatible to getattr() nor does it guarantee that no code is triggered. The function may or may not be secure.

Surprise or not surprise is a matter of perspective. I don't find it surprising.

It's incompatible because it gives different results:

```pycon
>>> class Example:
...     @property
...     def example(self):
...          def func(): pass
...          return func
... 
>>> e = Example()
>>> e.exa<TAB>
>>> e.example(
```


```py
with your patch, I'm getting:
>>> e.exa<TAB>
>>> e.example
```


Do you notice the difference?

**Comment by df2c16d9-e835-4bf0-a373-441d4d104450** [comment]
Serhiy, Chris, thank you for your additional comments. They surely helped me understand why my solution to this "problem?" isn't that good (also I slept on it a bit and maybe that helped).

I still ponder for a way to get autocompletion while guarranteeing no code will run, but a) any getter code is meant to run in that way, and b) it would somehow need to know the result of running that code without running it (Tricky, huh?).

Thanks again for your patience. I feel enlightened :)
