### ISSUE TITLE
rgb_to_hls in colorsys.py

### ISSUE THREAD

**Issue by 5c008e86-8fae-4634-ae74-8596b15a7659** [python/cpython#73815]
BPO | [29629](https://bugs.python.org/issue29629)
--- | :---
Nosy | @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-23.10:01:26.054>
created_at = <Date 2017-02-23.05:55:34.897>
labels = ['type-bug', 'invalid']
title = 'rgb_to_hls in colorsys.py'
updated_at = <Date 2017-02-23.10:01:26.053>
user = 'https://bugs.python.org/madhavendrasharma'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-23.10:01:26.053>
actor = 'madhavendra.sharma'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-23.10:01:26.054>
closer = 'madhavendra.sharma'
components = []
creation = <Date 2017-02-23.05:55:34.897>
creator = 'madhavendra.sharma'
dependencies = []
files = []
hgrepos = []
issue_num = 29629
keywords = []
message_count = 5.0
messages = ['288410', '288412', '288416', '288417', '288434']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'madhavendra.sharma']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29629'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 5c008e86-8fae-4634-ae74-8596b15a7659** [comment]
Calculations in rgb_to_hls at line number 67 in python version 2.7.3 for "h" the hue component are not correct according reference mentioned in the same source file "en.wikipedia.org/wiki/HSV_color_space".


code snippet:

```py
    if r == maxc:
        #h = (bc-gc) #current code
        h = (bc-gc)%6 # suggestion
    elif g == maxc:
        h = 2.0+rc-bc
    else:
        #h = 4.0+gc-rc #current code
        h = 4.0+rc-gc # suggestion
```


    #h = (h/6.0) % 1.0 not required 
    
    # h = 60 *h # component should be multiplied by 60 but it depends on user

**Comment by serhiy-storchaka** [comment]
All coordinates in RGB and HSV spaces are floating point numbers between 0.0 and 1.0. In Wikipedia article h is a degree value between 0° and 360°.

Could you provide an example of rgb_to_hls() returning invalid result?

**Comment by 5c008e86-8fae-4634-ae74-8596b15a7659** [comment]
Please check examples in en.wikipedia.org/wiki/HSL_and_HSV

I picked one of them
for R = .750, B=0.250, G=0.750 
corresponding HLS value are H= 300 = (5.0 * 60) , L =  .5, S=.5

but colorsys.rgb_to_hls(0.75 ,  0.25,  0.75) gives following output
(0.8333333333333334, 0.5, 0.5)
h\*60 = 0.8333333333333334 * 60 is not equal to 300

correct out put should be (5.0, 0.5, 0.5) or if h is multiplied by 60 then (300, 0.5, 0.5)

Thank you.
Madhavendra Sharma

**Comment by serhiy-storchaka** [comment]
0.8333333333333334 * 360 is equivalent to 300.

**Comment by 5c008e86-8fae-4634-ae74-8596b15a7659** [comment]
OK, That's fine. 
Thanks for the clarification.

But most of the calculations I found for the conversion from RGB to HLS contains H = 60 * h' that's why I could not interpret it properly. Even on the same wiki page calculations specific to RGB to HLS were that way only.

Thank you.
