### ISSUE TITLE
struct objects can no longer be pickled

### ISSUE THREAD

**Issue by 1ee290ce-1439-48e1-995e-ea6930888408** [python/cpython#73814]
BPO | [29628](https://bugs.python.org/issue29628)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-23.05:22:51.459>
created_at = <Date 2017-02-23.03:55:45.984>
labels = ['invalid', 'OS-windows', 'type-crash']
title = 'struct objects can no longer be pickled'
updated_at = <Date 2017-02-23.05:59:53.956>
user = 'https://bugs.python.org/mesheb82'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-23.05:59:53.956>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-23.05:22:51.459>
closer = 'serhiy.storchaka'
components = ['Windows']
creation = <Date 2017-02-23.03:55:45.984>
creator = 'mesheb82'
dependencies = []
files = []
hgrepos = []
issue_num = 29628
keywords = []
message_count = 4.0
messages = ['288401', '288406', '288407', '288411']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'mesheb82', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue29628'
versions = ['Python 3.6']
```

</p></details>

**Comment by 1ee290ce-1439-48e1-995e-ea6930888408** [comment]
When I run the following code on Windows/Linux for \< Python 3.6, I have no problems.  When I run in Python 3.6.0, I get the subsequent traceback.

I checked the release notes and only saw the following struct module note related to half-floats: Issue bpo-11734

```py
from struct import Struct
import copy
this_fails = Struct('<i')
copy.deepcopy(this_fails)
```



```pytb
Traceback (most recent call last):
  File "test_script.py", line 12, in <module>
    copy.deepcopy(this_fails)
  File "F:\Anaconda\envs\py36\lib\copy.py", line 169, in deepcopy
    rv = reductor(4)
TypeError: can't pickle Struct objects
```



To be clear, I'm copying struct objects as part of a larger class.  As I'm running many function calls where I create the same struct objects, saving the common struct objects allows me to get a factor of 2x speedup on my code.  Deleting the saved struct objects at the end of file reading (and before the deepcopy takes place) fixes the problem.

**Comment by serhiy-storchaka** [comment]
> When I run the following code on Windows/Linux for \< Python 3.6, I have no problems.

You have a problem. Did you try to use the copied object? It is a broken Struct object.

```pycon
>>> copied = copy.deepcopy(this_fails)
>>> copied.format
>>> copied.size
-1
>>> copied.pack(42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: pack expected -1 items for packing (got 1)
>>> copied.unpack(b'abcd')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: unpack requires a bytes object of length -1
```


Copying Struct object never worked. Now it raises an error rather than silently creating a broken object.

**Comment by 1ee290ce-1439-48e1-995e-ea6930888408** [comment]
Thank you.

On Wed, Feb 22, 2017 at 9:22 PM, Serhiy Storchaka \<report@bugs.python.org\>
wrote:

```pytb
>
> Serhiy Storchaka added the comment:
>
> > When I run the following code on Windows/Linux for < Python 3.6, I have
> no problems.
>
> You have a problem. Did you try to use the copied object? It is a broken
> Struct object.
>
> >>> copied = copy.deepcopy(this_fails)
> >>> copied.format
> >>> copied.size
> -1
> >>> copied.pack(42)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> struct.error: pack expected -1 items for packing (got 1)
> >>> copied.unpack(b'abcd')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> struct.error: unpack requires a bytes object of length -1
>
> Copying Struct object never worked. Now it raises an error rather than
> silently creating a broken object.
>
> 
```
----------
> nosy: +serhiy.storchaka
> resolution:  -\> not a bug
> stage:  -\> resolved
> status: open -\> closed
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29628\>
> _______________________________________
>

**Comment by serhiy-storchaka** [comment]
As a workaround you can make Struct pickleable:

```py
from struct import Struct
import copy, copyreg
def pickle_struct(s):
    return Struct, (s.format,)

copyreg.pickle(Struct, pickle_struct)

s1 = Struct('<i')
s2 = copy.deepcopy(s1)
```
