### ISSUE TITLE
Error “importlib.h, importlib_external.h updated. You will need to rebuild pythoncore to see the changes.” is reported when build Python on Winodws

### ISSUE THREAD

**Issue by caf6608e-2d5e-4f39-9e1b-7afab21ff198** [python/cpython#73817]
BPO | [29631](https://bugs.python.org/issue29631)
--- | :---
Nosy | @zware, @KarenHuang2016
Files | <li>[Python3_x86_build.log](https://bugs.python.org/file46664/Python3_x86_build.log "Uploaded as text/plain at 2017-02-23.10:01:15 by @KarenHuang2016")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-08.21:38:49.580>
created_at = <Date 2017-02-23.10:01:40.166>
labels = ['build']
title = 'Error \xe2\x80\x9cimportlib.h, importlib_external.h updated. You will need to rebuild pythoncore to see the changes.\xe2\x80\x9d is reported when build Python on Winodws'
updated_at = <Date 2017-09-08.21:38:49.579>
user = 'https://github.com/KarenHuang2016'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-08.21:38:49.579>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-08.21:38:49.580>
closer = 'zach.ware'
components = ['Build']
creation = <Date 2017-02-23.10:01:40.166>
creator = 'Karen'
dependencies = []
files = ['46664']
hgrepos = []
issue_num = 29631
keywords = []
message_count = 2.0
messages = ['288436', '301738']
nosy_count = 2.0
nosy_names = ['zach.ware', 'Karen']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29631'
versions = ['Python 3.6']
```

</p></details>

**Comment by caf6608e-2d5e-4f39-9e1b-7afab21ff198** [comment]
We use VS2015 to build Python(branch 3.6)on Windows. It failed with error "importlib.h, importlib_external.h updated. You will need to rebuild pythoncore to see the changes". This error is reported from Python 3.6 branch revision 3ab24bd. The detailed error log file is attached. Could you please help to take a look? Thank you so much!

Here is repro steps:
1. git clone -b "3.6" -c core.autocrlf=true https://github.com/python/cpython.git D:\\Python3\\src
2. checkout the revision to 3ab24bd.
3. build -e -r -v

**Comment by zware** [comment]
Hi Karen,

You may have already noticed that this has been fixed since you reported it; sorry it's taken so long for anybody to reply!  The issue was that importlib.h and importlib_external.h (generated files) were not checked in when their source files were changed, as is our convention for those files.  We have since enabled pre-merge CI to check this sort of thing.
