### ISSUE TITLE
Spurious failures in test_collections in releak hunting mode after typing is imported

### ISSUE THREAD

**Issue by ilevkivskyi** [python/cpython#73824]
BPO | [29638](https://bugs.python.org/issue29638)
--- | :---
Nosy | @gvanrossum, @rhettinger, @vstinner, @serhiy-storchaka, @ilevkivskyi
PRs | <li>python/cpython#469</li><li>python/cpython#482</li><li>python/cpython#483</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ilevkivskyi'
closed_at = <Date 2017-03-18.05:38:56.479>
created_at = <Date 2017-02-23.23:47:47.939>
labels = ['3.7', 'tests', 'performance']
title = 'Spurious failures in test_collections in releak hunting mode after typing is imported'
updated_at = <Date 2017-03-24.22:53:30.573>
user = 'https://github.com/ilevkivskyi'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:53:30.573>
actor = 'serhiy.storchaka'
assignee = 'levkivskyi'
closed = True
closed_date = <Date 2017-03-18.05:38:56.479>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-02-23.23:47:47.939>
creator = 'levkivskyi'
dependencies = []
files = []
hgrepos = []
issue_num = 29638
keywords = []
message_count = 13.0
messages = ['288495', '289014', '289015', '289016', '289017', '289018', '289019', '289025', '289032', '289036', '289037', '290295', '290296']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'rhettinger', 'vstinner', 'stutzbach', 'serhiy.storchaka', 'levkivskyi']
pr_nums = ['469', '482', '483']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29638'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ilevkivskyi** [comment]
This command:

./python -c 'import runpy, typing; runpy.run_module("test")' -R 5:5 test_collections

Sometimes gives spurious failures like this:

test_collections leaked [0, 0, 3, -3, 3] memory blocks, sum=3

I think this is because ABC caches of typing.ChainMap, typing.Counter, and typing.DefaultDict are not cleared by refleak.py/dash_R_cleanup (presumably because inspect.isabstract returns False on those)

Adding a manual clean-up of these cashes to cleanup_cashes() fixes the "leak".

**Comment by serhiy-storchaka** [comment]
If there are problems with ABC caches of typing.ChainMap, typing.Counter, and typing.DefaultDict, why not add corresponding clearing methods obj.\_abc_cache.clear and obj.\_abc_negative_cache.clear to typing.\_cleanups ?

Why there are problems only with ABC caches of these three types?

**Comment by ilevkivskyi** [comment]
> why not add corresponding clearing methods obj.\_abc_cache.clear and obj.\_abc_negative_cache.clear to typing.\_cleanups ?

OK, this is another possible solution. I didn't think about this, because now typing.\_cleanups only clear generic caches (not ABC caches).

> Why there are problems only with ABC caches of these three types?

Normally, ABC caches are cleared in dash_R_cleanup, but I think that the problem is that inspect.isabstract returns False for these three types (unlike other types in typing module), see line 147 in refleak.py:

```py
        if not isabstract(abc):
            continue
```


Actually now I think that the code in dash_R_cleanup might not clear some other caches also. So maybe we just need to add all ABC caches to typing.\_cleanups (just in case). What do you think, Serhiy?

**Comment by serhiy-storchaka** [comment]
> So maybe we just need to add all ABC caches to typing.\_cleanups (just in case).

I don't know. Sorry, I didn't remember exactly reasons why I didn't move the clearing of all ABC caches into clear_caches(). Perhaps I suspected that this can have unwanted consequences or decrease performance too much.

Are typing.ChainMap and others actually abstract classes? If yes, then perhaps there is something wrong with inspect.isabstract(). If no, then why ABC caches for these classes exist and non-empty?

**Comment by ilevkivskyi** [comment]
> Are typing.ChainMap and others actually abstract classes?

They are abstract classes in the sense that they are instances of abc.ABCMeta. However, for some reasons inspect checks \_\_flags__ attribute. The latter probably reflects the fact that Deque etc. do not have abstract methods (they still need to be instances of abc.ABCMeta because they need to be generic).

I don't think that we need to change behaviour of inspect because it could be backward incompatible. I would either make changes to refleak or typing (adding few more cleanups in either place).

**Comment by serhiy-storchaka** [comment]
What if explicitly set \_\_abstractmethods__ = True for these types?

**Comment by ilevkivskyi** [comment]
> What if explicitly set \_\_abstractmethods__ = True for these types?

Unfortunately this does not help. I think this is because dash_R_cleanup only clears caches for classes in collections.abc.\_\_all__ and their immediate .\_\_subclasses__(). Making this recursive (i.e. also clearing caches of \_\_subclasses__() of \_\_subclasses__() etc) will probably fix the problem (provided we also add \_\_abstractmethods__ = True). However, this looks a bit too complex for me. I would rather add few more typing.\_cleanups (anyway this failure only happens with typing ABCs)

**Comment by serhiy-storchaka** [comment]
I just wonder is there any other negative consequences? inspect.isabstract() returning False for abstract class looks a bug to me.

If you just want to add a workaround in dash_R_cleanup, I think it would be better to generate the list of all abstract classes and add three typing classes to it.

clear_caches() is called before running every test, but ABC caches are cleared not so often.

**Comment by ilevkivskyi** [comment]
> If you just want to add a workaround in dash_R_cleanup, I think it would be better to generate the list of all abstract classes and add three typing classes to it.

Yes, I just updated the PR.

I have found something else unrelated to typing, this test (in exactly this order):

./python -m test -R 5:5 test_abc test_functools

fails with a reproducible pattern:

test_functools leaked [0, 3, 1, 0, 0] memory blocks, sum=4

If you are happy with the PR now, we could open two separate issues for possible bug in inspect.isabstract and refleak in test_functools after test_abc. (the latter however might be potentially somehow related to abc caches)

**Comment by serhiy-storchaka** [comment]
Thank you Ivan! Seems this has fixed bpo-25744. Don't you mind to backport your changes to 3.6 and 3.5?

**Comment by ilevkivskyi** [comment]
> Seems this has fixed bpo-25744.

This is interesting, if I remember correctly the relevant typing classes were added only recently. I will take a look at how to back-port this (probably this will require some code changes)

**Comment by serhiy-storchaka** [comment]
New changeset b414e349eb6a6140a81ccec249bae3abe939e836 by Serhiy Storchaka (Ivan Levkivskyi) in branch '3.6':
bpo-29638: Fix spurious refleaks after typing is imported (#469) (#483)
https://github.com/python/cpython/commit/b414e349eb6a6140a81ccec249bae3abe939e836

**Comment by serhiy-storchaka** [comment]
New changeset 7acffa23c9e7866e5b4b98b8f3c28b14ec1c688c by Serhiy Storchaka (Ivan Levkivskyi) in branch 'master':
bpo-29638: Fix spurious refleaks after typing is imported (#469)
https://github.com/python/cpython/commit/7acffa23c9e7866e5b4b98b8f3c28b14ec1c688c
