### ISSUE TITLE
--enable-optimizations compiler flag has no effect

### ISSUE THREAD

**Issue by 80e5890a-9e17-44a9-8783-3eedb15a7037** [python/cpython#73829]
BPO | [29643](https://bugs.python.org/issue29643)
--- | :---
Nosy | @vstinner, @methane, @aw1621107
PRs | <li>python/cpython#129</li><li>python/cpython#869</li><li>python/cpython#870</li><li>python/cpython#871</li><li>python/cpython#873</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-28.16:51:50.888>
created_at = <Date 2017-02-24.23:20:10.836>
labels = ['type-bug', '3.7', 'build']
title = '--enable-optimizations compiler flag has no effect'
updated_at = <Date 2017-03-28.16:51:50.887>
user = 'https://github.com/aw1621107'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-28.16:51:50.887>
actor = 'methane'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-28.16:51:50.888>
closer = 'methane'
components = ['Build']
creation = <Date 2017-02-24.23:20:10.836>
creator = 'awang'
dependencies = []
files = []
hgrepos = []
issue_num = 29643
keywords = []
message_count = 7.0
messages = ['288535', '288536', '288537', '290705', '290730', '290731', '290741']
nosy_count = 3.0
nosy_names = ['vstinner', 'methane', 'awang']
pr_nums = ['129', '869', '870', '871', '873']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29643'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 80e5890a-9e17-44a9-8783-3eedb15a7037** [comment]
PR submitted here: https://github.com/python/cpython/pull/129

**Comment by vstinner** [comment]
The flag has an effect, I tested it today ;-)

Can you please elaborate why you consider that the flag has no effect?

**Comment by 80e5890a-9e17-44a9-8783-3eedb15a7037** [comment]
At least when I last built Python, configure always said that optimizations were not enabled regardless of whether I passed in the flag.

From what it looked like to me, it's because configure uses the $enableval variable to store the result of the check for --enable-optimizations, but the script checks $withval

**Comment by methane** [comment]
New changeset 8cea5929f52801b0ce5928b46ef836e99a24321a by INADA Naoki (Alex Wang) in branch 'master':
bpo-29643: Fix check for --enable-optimizations (GH-129)
https://github.com/python/cpython/commit/8cea5929f52801b0ce5928b46ef836e99a24321a

**Comment by methane** [comment]
New changeset f01de61a8efea8319c65365898982f929d59a895 by INADA Naoki in branch '3.6':
bpo-29643: Fix check for --enable-optimizations (GH-869)
https://github.com/python/cpython/commit/f01de61a8efea8319c65365898982f929d59a895

**Comment by methane** [comment]
New changeset e6a49531568561fe5aaf662259ecb7b4bc2426be by INADA Naoki in branch '3.5':
bpo-29643: Fix check for --enable-optimizations (GH-871)
https://github.com/python/cpython/commit/e6a49531568561fe5aaf662259ecb7b4bc2426be

**Comment by methane** [comment]
New changeset 6a04ef7ceddae0930eba6cc57ba2ebfcef00abab by INADA Naoki in branch '2.7':
bpo-29643: Fix check for --enable-optimizations (GH-873)
https://github.com/python/cpython/commit/6a04ef7ceddae0930eba6cc57ba2ebfcef00abab
