### ISSUE TITLE
Python 3.6.0

### ISSUE THREAD

**Issue by 064b147d-1909-4665-ac07-705095c837ce** [python/cpython#73833]
BPO | [29647](https://bugs.python.org/issue29647)
--- | :---
Nosy | @bitdancer, @PedanticHacker, @lazka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-25.17:53:11.346>
created_at = <Date 2017-02-25.10:44:46.569>
labels = ['interpreter-core', 'type-crash']
title = 'Python 3.6.0'
updated_at = <Date 2017-02-25.18:25:00.480>
user = 'https://github.com/PedanticHacker'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-25.18:25:00.480>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-25.17:53:11.346>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-02-25.10:44:46.569>
creator = 'PedanticHacker'
dependencies = []
files = []
hgrepos = []
issue_num = 29647
keywords = []
message_count = 3.0
messages = ['288557', '288559', '288573']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'PedanticHacker', 'lazka']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue29647'
versions = ['Python 3.6']
```

</p></details>

**Comment by 064b147d-1909-4665-ac07-705095c837ce** [comment]
I managed to create an app that crashes the latest stable version of Python, that is 3.6.0 at the time of this writing.

My application is written in Python using wxPython Phoenix 3rd-party GUI library/toolkit. I am running Windows 10 Home 64-bit version OS, the latest version of it, the Anniversary Edition with all its updates.

How I did it? Well, I made an event in my GUI app where clicking the X button puts up a message dialog to the user, saying "Do you really wanna close this app?" and the "Yes" button destroys the whole object, thus exiting the application.

But now the catch! I also made a taskbar icon which includes a menu item to also exit the application: same message dialog with Yes/No buttons.

Let's crash this baby! If you click the X button and not choosing either "Yes" or "No" but instead have this message dialog wait and in the mean time you right-click the taskbar icon and choose the "Exit" menu item and choose "Yes". Then click another "Yes" of that waiting message dialog and BOOM! Voila, we have killed PYthon interpreter.

Is that a bug in my code or does Python have a weakness?

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
That sounds like a problem with wxPython which you should report to them: http://trac.wxwidgets.org/

When you do, try to attach a minimal code example with your instructions so others can reproduce the error.

**Comment by bitdancer** [comment]
Agreed with Christoph.  If the wxPython team finds there really is a bug in cpython itself triggering this, they (or you) can open a new issue with specifics.
