### ISSUE TITLE
Importing webbrowser outputs a message on stderr

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73830]
BPO | [29644](https://bugs.python.org/issue29644)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka, @davesteele
PRs | <li>python/cpython#289</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-25.09:56:30.669>
created_at = <Date 2017-02-25.05:59:09.772>
labels = ['3.7', 'type-bug', 'library']
title = 'Importing webbrowser outputs a message on stderr'
updated_at = <Date 2017-03-24.23:46:20.615>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:46:20.615>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-25.09:56:30.669>
closer = 'ncoghlan'
components = ['Library (Lib)']
creation = <Date 2017-02-25.05:59:09.772>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29644
keywords = []
message_count = 8.0
messages = ['288542', '288543', '288544', '288547', '288548', '288549', '288552', '290402']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'serhiy.storchaka', 'daves']
pr_nums = ['289']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29644'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Importing webbrowser has a side effect. It outputs a message on stderr.

```pycon
>>> import webbrowser
/usr/bin/xdg-settings: 1: /usr/bin/xdg-settings: kreadconfig5: not found
```


This is a regression introduced in bpo-24241.

**Comment by ncoghlan** [comment]
I think an appropriate way of handling this would be to route both stdout and stderr in the subprocess to subprocess.DEVNULL.

**Comment by serhiy-storchaka** [comment]
Just stderr. stdout contains the requested value.

And I think that an external program shouldn't be ran at import time. It would be better to defer its run until its output is required.

**Comment by ncoghlan** [comment]
Ah, and I think I'm not seeing this locally because I have both Gtk and KDE components installed (my main desktop is KDE, but Firefox and various other components are still Gtk apps).

**Comment by serhiy-storchaka** [comment]
I see this because my main desktop is KDE, but optional libkf5config-bin package is not installed.

**Comment by ncoghlan** [comment]
I considered that problem of "subprocess invocation as a side-effect of import", but in this case the output is needed by the immediately following "register_X_browsers()" call, as it affects how those browsers get inserted into webbrowser.\_tryorder.

That means there isn't any obvious way to delay it without a fairly significant refactoring of how the module works :(

**Comment by ncoghlan** [comment]
The specific problem reported has been resolved, so closing this one.

If anyone's able to figure out a way to defer this to post-import somehow, I think that would make a good enhancement proposal.

**Comment by ncoghlan** [comment]
New changeset 140792bd514ee4ba739fda899785bea3ce746f05 by Nick Coghlan in branch 'master':
bpo-29644: suppress subprocess output from webbrowser (#289)
https://github.com/python/cpython/commit/140792bd514ee4ba739fda899785bea3ce746f05
