### ISSUE TITLE
Missed reference to create_module() in versionadded (import.rst)

### ISSUE THREAD

**Issue by c6a24554-5737-4174-b47e-54fc0403b8dc** [python/cpython#73834]
BPO | [29648](https://bugs.python.org/issue29648)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericsnowcurrently, @marco-buttu, @Mariatta
PRs | <li>python/cpython#277</li><li>python/cpython#290</li><li>python/cpython#314</li><li>python/cpython#315</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-26.15:41:55.679>
created_at = <Date 2017-02-25.11:22:08.905>
labels = ['3.7', 'docs']
title = 'Missed reference to create_module() in versionadded (import.rst)'
updated_at = <Date 2017-03-24.23:42:22.346>
user = 'https://github.com/marco-buttu'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:42:22.346>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-26.15:41:55.679>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-02-25.11:22:08.905>
creator = 'marco.buttu'
dependencies = []
files = []
hgrepos = []
issue_num = 29648
keywords = []
message_count = 7.0
messages = ['288560', '288572', '288596', '288597', '290385', '290387', '290392']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ncoghlan', 'docs@python', 'eric.snow', 'marco.buttu', 'Mariatta']
pr_nums = ['277', '290', '314', '315']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29648'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
In the first `versionadded` of the Loader section [1] of [Doc/reference/import.rst](https://github.com/python/cpython/blob/main/Doc/reference/import.rst), there is no reference to `create_module()`:

.. versionadded:: 3.4
   The create_module() method of loaders.

It should be:

.. versionadded:: 3.4
   The :meth:\`\~importlib.abc.Loader.create_module\` method of loaders.

I will make a PR.

[1] https://docs.python.org/3/reference/import.html#loaders

**Comment by Mariatta** [comment]
Thanks, Marco. Your change looks good to me.
I'm now wondering if this should have been 'versionchanged' instead of 'versionadded'. Perhaps other core devs can confirm this.

Thanks :)

**Comment by ncoghlan** [comment]
Version added is correct here, as the "create_module()" methods are all new in 3.4, and the traditional granularity for deciding "addition or change?" is that new functions, methods, and attributes are always additions, even if they're being added to a class definition.

**Comment by Mariatta** [comment]
Thanks for the clarification, Nick :)

Marco, I merged your PR, and backported to 3.5 and 3.6 branches.
Thanks!

**Comment by Mariatta** [comment]
New changeset 63ed9bc94d8df45b16aee9b92f658ebb34aa1012 by Mariatta in branch '3.5':
bpo-29648: import.rst: Add reference to create_module() (GH-290) (GH-315)
https://github.com/python/cpython/commit/63ed9bc94d8df45b16aee9b92f658ebb34aa1012

**Comment by Mariatta** [comment]
New changeset 7333d1760e12cf27bcf63265f72521892285c10a by Mariatta in branch '3.6':
bpo-29648: import.rst: Add reference to create_module() (GH-290) (GH-314)
https://github.com/python/cpython/commit/7333d1760e12cf27bcf63265f72521892285c10a

**Comment by Mariatta** [comment]
New changeset 46ce7599af82a929506baeaaee5c149970440c4c by Mariatta (Marco Buttu) in branch 'master':
bpo-29648: import.rst: Add reference to create_module() (GH-290)
https://github.com/python/cpython/commit/46ce7599af82a929506baeaaee5c149970440c4c
