### ISSUE TITLE
struct.pack_into check boundary error message ignores offset

### ISSUE THREAD

**Issue by 9da18a29-a07d-4828-a801-24cc911246de** [python/cpython#73835]
BPO | [29649](https://bugs.python.org/issue29649)
--- | :---
Nosy | @serhiy-storchaka, @andrewnester, @mlouielu
PRs | <li>python/cpython#424</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-04.10:47:37.875>
created_at = <Date 2017-02-25.13:53:04.073>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'struct.pack_into check boundary error message ignores offset'
updated_at = <Date 2017-04-04.10:47:37.874>
user = 'https://github.com/mlouielu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-04.10:47:37.874>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-04.10:47:37.875>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-02-25.13:53:04.073>
creator = 'louielu'
dependencies = []
files = []
hgrepos = []
issue_num = 29649
keywords = []
message_count = 11.0
messages = ['288564', '288882', '288884', '288885', '288886', '288887', '288978', '289021', '290081', '291119', '291120']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'andrewnester', 'louielu']
pr_nums = ['424']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29649'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
For this situation, check boundary error message didn't correctly show out.

```pycon
>>> import struct
>>> import ctypes
>>> byte_list = ctypes.create_string_buffer(1)
>>> struct.pack_into('b', byte_list, 5, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
struct.error: pack_into requires a buffer of at least 1 bytes
```


Since offset is setting at 5, it should at least need `offset + soself->s_size` bytes to store it.

**Comment by 85518756-5bea-4efa-9ce9-5daf552d31b1** [comment]
Thanks! Just added PR fixing this.

**Comment by serhiy-storchaka** [comment]
I'm not sure the new error message is better. It is not known what is wrong -- the size of the buffer, or the offset?

I think that the better error message should include three numbers: the offset, the size of the destination buffer, and the size of packed data or the minimal size of the destination buffer.

**Comment by 85518756-5bea-4efa-9ce9-5daf552d31b1** [comment]
yeah, I also thought about this too.
Something like 'pack_into requires a buffer of at least 6 bytes (size is 1, offset is 5)'

**Comment by serhiy-storchaka** [comment]
Or "pack_into requires a buffer of at least 6 bytes for packing 1 bytes at offset 5".

**Comment by 85518756-5bea-4efa-9ce9-5daf552d31b1** [comment]
thanks Serhiy! just implemented your variant in my PR.

**Comment by serhiy-storchaka** [comment]
Different error messages are needed if original offset \< 0. For example packing 4 bytes with offset -2 always fails, not depending of the size of the buffer. Packing into buffer of size 10 with offset -11 always fails, not depending of the size of packed data.

struct.pack_into('\<I', bytearray(10), -2, 123)
struct.pack_into('\<B', bytearray(10), -11, 123)

**Comment by 85518756-5bea-4efa-9ce9-5daf552d31b1** [comment]
Thanks Serhiy! Just implemented new error messages in my PR for case you mentioned.

**Comment by 85518756-5bea-4efa-9ce9-5daf552d31b1** [comment]
any updates on this issue? looks like PR is ready to go

**Comment by serhiy-storchaka** [comment]
New changeset f78b119364b521307237a1484ba5f43f42300898 by Serhiy Storchaka (Andrew Nester) in branch 'master':
bpo-29649: Improve struct.pack_into() boundary error messages (#424)
https://github.com/python/cpython/commit/f78b119364b521307237a1484ba5f43f42300898

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Andrew.
