### ISSUE TITLE
Fix evaluation order of keys/values in dict comprehensions

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#73838]
BPO | [29652](https://bugs.python.org/issue29652)
--- | :---
Nosy | @rhettinger, @ncoghlan, @Janzert, @zhangyangyu, @DimitrisJim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-09-17.23:36:16.137>
created_at = <Date 2017-02-25.19:54:43.014>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'Fix evaluation order of keys/values in dict comprehensions'
updated_at = <Date 2019-09-17.23:36:16.137>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-17.23:36:16.137>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2019-09-17.23:36:16.137>
closer = 'brett.cannon'
components = ['Interpreter Core']
creation = <Date 2017-02-25.19:54:43.014>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29652
keywords = []
message_count = 5.0
messages = ['288578', '288623', '315832', '315874', '351088']
nosy_count = 6.0
nosy_names = ['rhettinger', 'ncoghlan', 'janzert', 'xiang.zhang', 'Jim Fasarakis-Hilliard', 'EvKounis']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29652'
versions = ['Python 3.8']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Reported from [1] and similar to bpo-11205 

Currently the evaluation order for keys and values in a dictionary comprehension follows that of assignments. The values get evaluated first and then the keys:

```py
    def printer(v):
        print(v, end=' ')
        return v

    d = {printer(i): printer(j) for i, j in [(1, 2), (3, 4)]}
    # 2 1 4 3
```


This seems to conflict with the semantics as described in the Semantics section of PEP-274 [2] and according to my interpretation of the reference manual (I'd expect the evaluation to be similar to dict-displays).

How should this be addressed? Fix the evaluation order or specify this edge case an "Implementation detail" in the reference manual?

I already have a fix for this lying around (changes to `compiler_sync_comprehension_generator`, `compiler_sync_comprehension_generator` and a switch in `MAP_ADD`) and can make a pull request if required.

I'm not sure if this is classified as a bug per-se so I only tagged Py3.7 for it.

 [1] http://stackoverflow.com/questions/42201932/order-of-operations-in-a-dictionary-comprehension
 [2] https://www.python.org/dev/peps/pep-0274/#semantics

**Comment by rhettinger** [comment]
I think the current behavior is correct and desirable (as you say, it follows the order that would take place in an assignment, making it easy to roll-up existing for-loop code into a dict comprehension or to unroll and existing comprehension). Also, I think changing the behavior might risk introducing bugs into existing code that may have unconsciously relied on the existing order.  My recommendation is to document the current value-first behavior.

For the other issue, 11205, I agree with the discussion there that key-first-value-second makes more sense in the context of literals which are normally evaluated left-to-right.
