### ISSUE TITLE
abstractmethod does not work when deriving from Exception

### ISSUE THREAD

**Issue by a5ad8fb9-cdef-4530-9287-4bb63eba5fb9** [python/cpython#73836]
BPO | [29650](https://bugs.python.org/issue29650)
--- | :---
Nosy | @chrysn, @zhangyangyu
Superseder | <li>bpo-5996: abstract class instantiable when subclassing built-in types</li>
Files | <li>[demo.py](https://bugs.python.org/file46668/demo.py "Uploaded as text/plain at 2017-02-25.16:46:45 by @chrysn"): demo that should throw TypeError</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-26.08:06:38.894>
created_at = <Date 2017-02-25.16:46:46.142>
labels = ['type-bug', '3.7']
title = 'abstractmethod does not work when deriving from Exception'
updated_at = <Date 2017-02-26.08:06:38.892>
user = 'https://github.com/chrysn'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-26.08:06:38.892>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-26.08:06:38.894>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-02-25.16:46:46.142>
creator = 'chrysn'
dependencies = []
files = ['46668']
hgrepos = []
issue_num = 29650
keywords = []
message_count = 2.0
messages = ['288571', '288590']
nosy_count = 2.0
nosy_names = ['chrysn', 'xiang.zhang']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '5996'
type = 'behavior'
url = 'https://bugs.python.org/issue29650'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a5ad8fb9-cdef-4530-9287-4bb63eba5fb9** [comment]
The "TypeError: Can't instantiate abstract class C with abstract methods x" exception does not get raised when when the involved ABCMeta class is derived from an Exception.

The attached file shows that a class without an implementation of an abstractmethod can get instanciated; replacing the derivation from Exception with a derivation from another class (say, A) makes the instanciation throw the proper TypeError.

**Comment by zhangyangyu** [comment]
Yes. This is the case for builtin types which usually get their own \_\_new__ methods. See bpo-5996.
