### ISSUE TITLE
Inconsistent/undocumented urlsplit/urlparse behavior on invalid inputs

### ISSUE THREAD

**Issue by 1bc9703c-451a-4e27-ba2c-90664e117b42** [python/cpython#73837]
BPO | [29651](https://bugs.python.org/issue29651)
--- | :---
Nosy | @rhettinger, @orsenthil, @howinator
PRs | <li>python/cpython#1128</li><li>python/cpython#1596</li><li>python/cpython#1597</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-16.05:50:14.977>
created_at = <Date 2017-02-25.19:45:27.149>
labels = ['3.7', 'type-bug', 'library', 'docs']
title = 'Inconsistent/undocumented urlsplit/urlparse behavior on invalid inputs'
updated_at = <Date 2017-05-16.05:50:14.976>
user = 'https://bugs.python.org/vfaronov'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-16.05:50:14.976>
actor = 'orsenthil'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-16.05:50:14.977>
closer = 'orsenthil'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2017-02-25.19:45:27.149>
creator = 'vfaronov'
dependencies = []
files = []
hgrepos = []
issue_num = 29651
keywords = []
message_count = 6.0
messages = ['288577', '288959', '291640', '293748', '293750', '293751']
nosy_count = 5.0
nosy_names = ['rhettinger', 'orsenthil', 'docs@python', 'vfaronov', 'Howie Benefiel']
pr_nums = ['1128', '1596', '1597']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29651'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1bc9703c-451a-4e27-ba2c-90664e117b42** [comment]
There is a problem with the standard library's urlsplit and urlparse functions, in Python 2.7 (module urlparse) and 3.2+ (module urllib.parse).

The documentation for these functions [1] does not explain how they behave when given an invalid URL.

One could try invoking them manually and conclude that they tolerate anything thrown at them:

```pycon
>>> urlparse('http:////::\\\\!!::!!++///')
ParseResult(scheme='http', netloc='', path='//::\\\\!!::!!++///',
params='', query='', fragment='')

>>> urlparse(os.urandom(32).decode('latin-1'))
ParseResult(scheme='', netloc='', path='\x7f¼â1gdä»6\x82', params='',
query='', fragment='\n\xadJ\x18+fli\x9cÛ\x9ak*ÄÅ\x02³F\x85Ç\x18')
```


Without studying the source code, it is impossible to know that there is a very narrow class of inputs on which they raise ValueError [2]:

```pycon
>>> urlparse('http://[')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.5/urllib/parse.py", line 295, in urlparse
    splitresult = urlsplit(url, scheme, allow_fragments)
  File "/usr/lib/python3.5/urllib/parse.py", line 345, in urlsplit
    raise ValueError("Invalid IPv6 URL")
ValueError: Invalid IPv6 URL
```


This could be viewed as a documentation issue. But it could also be viewed as an implementation issue. Instead of raising ValueError on those square brackets, urlsplit could simply consider them \*invalid* parts of an RFC 3986 reg-name, and lump them into netloc, as it already does with other \*invalid* characters:

```pycon
>>> urlparse('http://\0\0æí\n/')
ParseResult(scheme='http', netloc='\x00\x00æí\n', path='/', params='',
query='', fragment='')
```


Note that the raising behavior was introduced in Python 2.7/3.2.

See also bpo-8721 [3].


[1] https://docs.python.org/3/library/urllib.parse.html
[2] https://github.com/python/cpython/blob/e32ec93/Lib/urllib/parse.py#L406-L408
[3] http://bugs.python.org/issue8721

**Comment by rhettinger** [comment]
A note in the docs would be useful.  This API is far too well established to make any behavioral changes at this point.

**Comment by 5e8488f1-8376-4a7f-be3c-ceee2c8c4a6f** [comment]
I'm going to make a note in the documentation. I should have a PR for it in about 1 day.

**Comment by orsenthil** [comment]
New changeset f6e863d868a621594df2a8abe072b5d4766e7137 by Senthil Kumaran (Howie Benefiel) in branch 'master':
 bpo-29651 - Cover edge case of square brackets in urllib docs (bpo-1128)
https://github.com/python/cpython/commit/f6e863d868a621594df2a8abe072b5d4766e7137

**Comment by orsenthil** [comment]
New changeset 72e5aa1ef812358b3b113e784e7365fec13dfd69 by Senthil Kumaran in branch '3.5':
 bpo-29651 - Cover edge case of square brackets in urllib docs (bpo-1128) (bpo-1597)
https://github.com/python/cpython/commit/72e5aa1ef812358b3b113e784e7365fec13dfd69

**Comment by orsenthil** [comment]
New changeset 75b8a54bcad70806d9dcbbe20786f4d9092ab39c by Senthil Kumaran in branch '3.6':
 bpo-29651 - Cover edge case of square brackets in urllib docs (bpo-1128) (bpo-1596)
https://github.com/python/cpython/commit/75b8a54bcad70806d9dcbbe20786f4d9092ab39c
