### ISSUE TITLE
webbrowser module import has heavy side effects

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73831]
BPO | [29645](https://bugs.python.org/issue29645)
--- | :---
Nosy | @terryjreedy, @ncoghlan, @serhiy-storchaka, @mlouielu
PRs | <li>python/cpython#484</li><li>python/cpython#703</li>
Files | <li>[webbrowser-delayed-initialization.patch](https://bugs.python.org/file46667/webbrowser-delayed-initialization.patch "Uploaded as text/plain at 2017-02-25.11:48:56 by @serhiy-storchaka")</li><li>[webbrowser-delayed-initialization-2.patch](https://bugs.python.org/file46670/webbrowser-delayed-initialization-2.patch "Uploaded as text/plain at 2017-02-25.22:50:54 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-08.15:20:37.722>
created_at = <Date 2017-02-25.09:26:58.434>
labels = ['3.7', 'library', 'performance']
title = 'webbrowser module import has heavy side effects'
updated_at = <Date 2017-03-24.22:40:47.558>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:40:47.558>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-08.15:20:37.722>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-02-25.09:26:58.434>
creator = 'serhiy.storchaka'
dependencies = []
files = ['46667', '46670']
hgrepos = []
issue_num = 29645
keywords = ['patch']
message_count = 10.0
messages = ['288551', '288561', '288562', '288563', '288566', '288585', '288587', '288589', '288930', '290260']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ncoghlan', 'serhiy.storchaka', 'louielu']
pr_nums = ['484', '703']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue29645'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`import webbrowser` has heavy side effects. It searches a number of executables. On X Window it also runs external program xdg-settings.

Cold start:

```sh
$ time ./python -c ''
```


real	0m1.719s
user	0m0.088s
sys	0m0.036s

```sh
$ time ./python -c 'import webbrowser'
```


real	0m5.713s
user	0m0.308s
sys	0m0.196s

Hot start:

```sh
$ time ./python -c ''
```


real	0m0.094s
user	0m0.072s
sys	0m0.020s

```sh
$ time ./python -c 'import webbrowser'
```


real	0m1.026s
user	0m0.284s
sys	0m0.100s

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
What is the different of Cold start and Hot start? It that CPU speed or something else.

In Linux 4.9.11 with i7-2k, I can't reproduce the significant real time you gave:

\# CPU gov powersave
$ time ./python -c 'import webbrowser'
0.16s user 0.02s system 93% cpu 0.200 total

\# CPU gov performance
$ time ./python -c 'import webbrowser'
0.08s user 0.00s system 82% cpu 0.093 total

**Comment by serhiy-storchaka** [comment]
Following patch makes searching of all platform browsers delayed until it is needed. In addition it makes webbrowser.register() thread safe.

Cold start:

```sh
$ time ./python -c 'import webbrowser'
```


real	0m2.851s
user	0m0.224s
sys	0m0.056s

Hot start:

```sh
$ time ./python -c 'import webbrowser'
```


real	0m0.259s
user	0m0.232s
sys	0m0.024s

**Comment by serhiy-storchaka** [comment]
> What is the different of Cold start and Hot start?

Disk caches are dropped before cold start.

```sh
$ echo 3 | sudo tee /proc/sys/vm/drop_caches
```

**Comment by ncoghlan** [comment]
Nice, this is much cleaner than the current approach!

The one thing I would suggest is a new test case that:

- asserts webbrowser.\_tryorder is None
- asserts webbrowser.\_browsers is empty
- calls webbrowser.get()
- asserts webbrowser.\_tryorder is non-empty
- asserts webbrowser.\_browsers is non-empty

I wouldn't worry about explicitly testing the thread safety. That's just a normal double-checked locking pattern, so I think code review is sufficient to address that - the only way for it to break is for something to go horribly wrong in threading.RLock().

**Comment by serhiy-storchaka** [comment]
Added tests.

**Comment by ncoghlan** [comment]
Patch LGTM.

Serhiy, did you want to take this as a chance to run through the new GitHub PR workflow?

Current details are at https://docs.python.org/devguide/pullrequest.html

**Comment by serhiy-storchaka** [comment]
The new GitHub PR workflow still looks cumbersome and unclear to me. It needs using a lot of git commands different for different branches (and some command are failed or don't work as I expected when I try to repeat sequences from the [devguide](https://devguide.python.org)). How to convert a patch to a pull request? How to get a list of added and modified files? What is the best way to revert all changes and changes in selected files? How to retrieve changes from pull request for local testing? Is there a way to edit otherpeople's pull request (add an entry in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS), etc) before merging it in the main repository? I wait until the [devguide](https://devguide.python.org) be more comprehensive.

**Comment by terryjreedy** [comment]
This will help IDLE startup (though webbrowser should not be imported on windows, where os.startfile is used instead).

This is a somewhat separate issue, but should the Windows code be modified for Win10 and Microsoft Edge?

**Comment by serhiy-storchaka** [comment]
New changeset a7cba27aea138311117e2ab1d91584efcfeac4ec by Serhiy Storchaka in branch 'master':
bpo-29645: Speed up importing the webbrowser module. (#484)
https://github.com/python/cpython/commit/a7cba27aea138311117e2ab1d91584efcfeac4ec
