### ISSUE TITLE
Typo in the docstring of timeit.Timer.autorange

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#73847]
BPO | [29661](https://bugs.python.org/issue29661)
--- | :---
Nosy | @rhettinger, @zhangyangyu
PRs | <li>python/cpython#331</li><li>python/cpython#353</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zhangyangyu'
closed_at = <Date 2017-02-28.03:30:15.227>
created_at = <Date 2017-02-27.04:02:11.906>
labels = ['3.7', 'library']
title = 'Typo in the docstring of timeit.Timer.autorange'
updated_at = <Date 2017-03-24.23:35:51.895>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:35:51.895>
actor = 'xiang.zhang'
assignee = 'xiang.zhang'
closed = True
closed_date = <Date 2017-02-28.03:30:15.227>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-02-27.04:02:11.906>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 29661
keywords = []
message_count = 6.0
messages = ['288619', '288625', '288627', '288688', '290360', '290361']
nosy_count = 2.0
nosy_names = ['rhettinger', 'xiang.zhang']
pr_nums = ['331', '353']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29661'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
The docstring of timeit.Timer.autorange currently reads

     |      Return the number of loops so that total time >= 0.2.
     |      
     |      Calls the timeit method with *number* set to successive powers of
     |      ten (10, 100, 1000, ...) up to a maximum of one billion, until
     |      the time taken is at least 0.2 second, or the maximum is reached.
     |      Returns ``(number, time_taken)``.
     |      
     |      If *callback* is given and is not None, it will be called after
     |      each trial with two arguments: ``callback(number, time_taken)``.

Note the contradiction between the return values documented in the first and second paragraphs (the second one is correct).

**Comment by rhettinger** [comment]
How about:
    Return the number of loops and time taken so that total time \>= 0.2.

Instead of:
    Return the number of loops so that total time \>= 0.2.

The proposed "calculate" instead of "return" isn't really correct.

**Comment by zhangyangyu** [comment]
Of course that is okay. I didn't do what you propose since I thought it's somewhat superfluous, what is returned is mentioned below. I choose 'calculate' when I see 'Automatically determine how many times to call timeit()' in the documentation.

**Comment by zhangyangyu** [comment]
Thanks Raymond!

**Comment by zhangyangyu** [comment]
New changeset c4a786b8ad2a625594551ab3bc991a6831ba7688 by Xiang Zhang in branch '3.6':
bpo-29661: fix contradiction in timeit.Timer.autorange's docstring (GH-331) (GH-353)
https://github.com/python/cpython/commit/c4a786b8ad2a625594551ab3bc991a6831ba7688

**Comment by zhangyangyu** [comment]
New changeset ecf39bbc97adc0fb67654602e37d0d8313e9be9d by Xiang Zhang in branch 'master':
bpo-29661: fix contradiction in timeit.Timer.autorange's docstring (GH-331)
https://github.com/python/cpython/commit/ecf39bbc97adc0fb67654602e37d0d8313e9be9d
