### ISSUE TITLE
Certain errors during IMPORT_STAR can leak a reference

### ISSUE THREAD

**Issue by 26262e33-08fc-41fc-b1f2-696d14f054d2** [python/cpython#73841]
BPO | [29655](https://bugs.python.org/issue29655)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @Carreau, @corsix
PRs | <li>python/cpython#301</li><li>python/cpython#348</li><li>python/cpython#349</li><li>python/cpython#510</li>
Files | <li>[issue29655-2.7.patch](https://bugs.python.org/file46678/issue29655-2.7.patch "Uploaded as text/plain at 2017-02-28.06:13:33 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-15.10:49:37.372>
created_at = <Date 2017-02-25.21:26:53.534>
labels = ['interpreter-core', 'performance']
title = 'Certain errors during IMPORT_STAR can leak a reference'
updated_at = <Date 2017-03-24.23:45:06.809>
user = 'https://github.com/corsix'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:45:06.809>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-15.10:49:37.372>
closer = 'berker.peksag'
components = ['Interpreter Core']
creation = <Date 2017-02-25.21:26:53.534>
creator = 'Peter Cawley'
dependencies = []
files = ['46678']
hgrepos = []
issue_num = 29655
keywords = ['patch']
message_count = 8.0
messages = ['288582', '288664', '288665', '288694', '290263', '290362', '290363', '290399']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'mbussonn', 'Peter Cawley']
pr_nums = ['301', '348', '349', '510']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29655'
versions = ['Python 2.7']
```

</p></details>

**Comment by 26262e33-08fc-41fc-b1f2-696d14f054d2** [comment]
In the implementation of the IMPORT_STAR opcode, if the call to PyFrame_FastToLocalsWithError fails, or f_locals is NULL, then control flow jumps to the error handler without performing a decref on the "from" variable. As the "from" variable is initialised by POPping from the stack, the reference is leaked.

**Comment by serhiy-storchaka** [comment]
It looks to me that 2.7 has this bug.

**Comment by berkerpeksag** [comment]
I ignored 2.7 because you know... it's 2.7 :) And you said [1] that it doesn't have a big effect on real applications.

[1] https://github.com/python/cpython/pull/301#issuecomment-282789185

**Comment by serhiy-storchaka** [comment]
But it is \*very easy* to fix this bug in 2.7.

**Comment by serhiy-storchaka** [comment]
New changeset 9fbb65e6464b56c6d677090e185c9fe16a80ed96 by Serhiy Storchaka in branch '2.7':
bpo-29655: Fixed possible reference leaks in `import *`. (#301) (#510)
https://github.com/python/cpython/commit/9fbb65e6464b56c6d677090e185c9fe16a80ed96

**Comment by berkerpeksag** [comment]
New changeset 0dadf56737f591c83d18db5e445960d39448583e by Berker Peksag in branch '3.5':
bpo-29655: Fixed possible reference leaks in `import *`. (#301) (#349)
https://github.com/python/cpython/commit/0dadf56737f591c83d18db5e445960d39448583e

**Comment by berkerpeksag** [comment]
New changeset 7accf2033d03025cc5324f8b9d22582bca3623e9 by Berker Peksag in branch '3.6':
bpo-29655: Fixed possible reference leaks in `import *`. (#301) (#348)
https://github.com/python/cpython/commit/7accf2033d03025cc5324f8b9d22582bca3623e9

**Comment by serhiy-storchaka** [comment]
New changeset 160edb43571311a3785785c1dfa784afc52d87be by Serhiy Storchaka (Matthias Bussonnier) in branch 'master':
bpo-29655: Fixed possible reference leaks in `import *`. (#301)
https://github.com/python/cpython/commit/160edb43571311a3785785c1dfa784afc52d87be
