### ISSUE TITLE
Combining thread and process, process hangs (sometimes)

### ISSUE THREAD

**Issue by 4c72cab4-78db-4921-a7a3-06639c5c5a35** [python/cpython#73844]
BPO | [29658](https://bugs.python.org/issue29658)
--- | :---
Nosy | @rhettinger, @applio

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/applio'
closed_at = <Date 2017-02-27.13:39:57.394>
created_at = <Date 2017-02-26.13:48:30.222>
labels = ['type-bug', 'invalid']
title = 'Combining thread and process, process hangs (sometimes)'
updated_at = <Date 2017-02-27.13:39:57.393>
user = 'https://bugs.python.org/djstrong'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-27.13:39:57.393>
actor = 'djstrong'
assignee = 'davin'
closed = True
closed_date = <Date 2017-02-27.13:39:57.394>
closer = 'djstrong'
components = []
creation = <Date 2017-02-26.13:48:30.222>
creator = 'djstrong'
dependencies = []
files = []
hgrepos = []
issue_num = 29658
keywords = []
message_count = 5.0
messages = ['288594', '288595', '288610', '288624', '288641']
nosy_count = 3.0
nosy_names = ['rhettinger', 'davin', 'djstrong']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29658'
versions = ['Python 3.5']
```

</p></details>

**Comment by 4c72cab4-78db-4921-a7a3-06639c5c5a35** [comment]
I have this code, which sometimes hangs (1 of 5 runs):

\# -*- coding: utf-8 -*-

```py
import sys
import threading
import multiprocessing

mpl = multiprocessing.log_to_stderr()
mpl.setLevel(1)


class A(threading.Thread):
    def __init__(self):
        super(A, self).__init__()

    def run(self):
        print(self.name, 'RUN')

        for line in sys.stdin: #increases probability of hanging
            pass

        print(self.name, 'STOP')


class B(multiprocessing.Process):
    def __init__(self):
        super(B, self).__init__()

    def run(self):
        print(self.name, 'RUN')


a = A()
a.start()

b = B()
b.start()
print('B started', b, b.is_alive(), b.pid)
print('A', a)

a.join()
b.join()

print('FINISHED')
```


I am running it on Ubuntu with command: echo "" | python3 time_test4.py

Output is:
Thread-1 RUN
B started \<B(B-1, started)\> True 31439
A \<A(Thread-1, started 139779252864768)\>
Thread-1 STOP

**Comment by 4c72cab4-78db-4921-a7a3-06639c5c5a35** [comment]
Sometimes the output is:
Thread-1 RUN
Thread-1 STOP
B started \<B(B-1, started)\> True 20187
A \<A(Thread-1, started 139773917562624)\>
[INFO/B-1] child process calling self.run()


but "print" in "run" method of process is not executed.

**Comment by 4c72cab4-78db-4921-a7a3-06639c5c5a35** [comment]
It is confirmed with other hardware with Python 3.5.2. Process is forked, but method "run" is not executing.

**Comment by rhettinger** [comment]
Unless I'm misreading what you're trying to do, this doesn't seem like a bug to me.   In general, when combining threading with multiple processes, the rule is to fork first and then launch threads (so that none of the thread ids or locks accidentally get shared across processes).

**Comment by 4c72cab4-78db-4921-a7a3-06639c5c5a35** [comment]
Thank you! I couldn't find information about first forking then launching threads.
