### ISSUE TITLE
Document that print/format_exception ignore etype

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73846]
BPO | [29660](https://bugs.python.org/issue29660)
--- | :---
Nosy | @Carreau, @Mariatta
PRs | <li>python/cpython#344</li><li>python/cpython#1913</li><li>python/cpython#1914</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-02.03:27:41.923>
created_at = <Date 2017-02-27.01:21:38.865>
labels = ['3.7', 'docs']
title = 'Document that print/format_exception ignore etype'
updated_at = <Date 2017-06-02.03:27:41.922>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-02.03:27:41.922>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-02.03:27:41.923>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-02-27.01:21:38.865>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29660
keywords = []
message_count = 7.0
messages = ['288617', '294973', '294974', '294976', '294977', '294978', '294979']
nosy_count = 3.0
nosy_names = ['docs@python', 'mbussonn', 'Mariatta']
pr_nums = ['344', '1913', '1914']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29660'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
As far as I can tell, http://bugs.python.org/issue17911 made a couple of function in traceback ignore their first arguments (etype) and infer the type from the second one (evalue). 

(In git 6bc2c1e7 and 2f0441f0 respectively).

At least print_exception and format_exception are affected.

This likely affect http://bugs.python.org/issue26389 (who wish to expand same API to remove these parameters).

And inconsistency with `format_exception_only` which does need `etype` should be checked. 

If etype is a deprecated parameter it should be noted, and should likely raise a DeprecationWarning as well when set.

**Comment by Mariatta** [comment]
New changeset cdb89cd72cbc66e4626914b4a71b9052ddb3a32a by Mariatta (Matthias Bussonnier) in branch 'master':
bpo-29660: traceback: Document that etype is ignored in some places. (GH-344)
https://github.com/python/cpython/commit/cdb89cd72cbc66e4626914b4a71b9052ddb3a32a

**Comment by Mariatta** [comment]
Thanks Matthias.

I can backport this later today.
Or do you want to do it? :)
You can use cherry_picker.py https://github.com/python/core-workflow/tree/master/cherry_picker

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
Thanks @Mariatta, I'll try to cherry-pick!

**Comment by Mariatta** [comment]
New changeset e417d12d728103445b8516a35f643536e401f120 by Mariatta (Matthias Bussonnier) in branch '3.6':
bpo-29660: traceback: Document that etype is ignored in some places. (GH-344) (GH-1913)
https://github.com/python/cpython/commit/e417d12d728103445b8516a35f643536e401f120

**Comment by Mariatta** [comment]
New changeset cca3d4aa25a7aea0cda90dd2aa012f58c85e7e24 by Mariatta (Matthias Bussonnier) in branch '3.5':
bpo-29660: traceback: Document that etype is ignored in some places. (GH-344) (GH-1914)
https://github.com/python/cpython/commit/cca3d4aa25a7aea0cda90dd2aa012f58c85e7e24

**Comment by Mariatta** [comment]
Thanks :)
