### ISSUE TITLE
Make collections.deque json serializable

### ISSUE THREAD

**Issue by 508f7627-3797-4332-8a63-a38898672f33** [python/cpython#73849]
BPO | [29663](https://bugs.python.org/issue29663)
--- | :---
Nosy | @rhettinger, @tarekziade, @serhiy-storchaka
Superseder | <li>bpo-20774: collections.deque should ship with a stdlib json serializer</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-27.11:08:31.754>
created_at = <Date 2017-02-27.10:21:30.955>
labels = ['3.7', 'type-bug', 'library']
title = 'Make collections.deque json serializable'
updated_at = <Date 2017-02-27.11:08:31.753>
user = 'https://github.com/tarekziade'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-27.11:08:31.753>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-27.11:08:31.754>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-02-27.10:21:30.955>
creator = 'tarek'
dependencies = []
files = []
hgrepos = []
issue_num = 29663
keywords = []
message_count = 3.0
messages = ['288629', '288630', '288635']
nosy_count = 3.0
nosy_names = ['rhettinger', 'tarek', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '20774'
type = 'behavior'
url = 'https://bugs.python.org/issue29663'
versions = ['Python 3.7']
```

</p></details>

**Comment by 508f7627-3797-4332-8a63-a38898672f33** [comment]
collections.deque could be serialized in JSON as a simple array.

The only thing we can lose in the process is the maxlen value, but I think it's a decent behaviour to ignore it when encoding and to set it to None when decoding.

**Comment by rhettinger** [comment]
+1 This isn't really different that how we handle tuples and I can see that it would be useful to be able to dump a deque into JSON.  I concur that it is reasonable to ignore maxlen because that is primarily a convenience feature (auto-popping on overflow) rather than something that is intrinsic to the semantics of data itself.

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-20774.
