### ISSUE TITLE
SimpleHTTPRequestHandler should support browser cache

### ISSUE THREAD

**Issue by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [python/cpython#73840]
BPO | [29654](https://bugs.python.org/issue29654)
--- | :---
Nosy | @vstinner, @PierreQuentel, @serhiy-storchaka
PRs | <li>python/cpython#298</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-02.10:27:13.993>
created_at = <Date 2017-02-25.21:20:35.748>
labels = ['3.7', 'type-feature', 'library']
title = 'SimpleHTTPRequestHandler should support browser cache'
updated_at = <Date 2017-07-31.22:35:58.707>
user = 'https://github.com/PierreQuentel'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-31.22:35:58.707>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-02.10:27:13.993>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-02-25.21:20:35.748>
creator = 'quentel'
dependencies = []
files = []
hgrepos = []
issue_num = 29654
keywords = []
message_count = 7.0
messages = ['288581', '291028', '291029', '299405', '299472', '299543', '299588']
nosy_count = 4.0
nosy_names = ['vstinner', 'v+python', 'quentel', 'serhiy.storchaka']
pr_nums = ['298']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29654'
versions = ['Python 3.7']
```

</p></details>

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
SimpleHTTPServer send a Last-Modified response header, but doesn't take into account the If-Modified-Since header if it was sent by the user agent. 

If a url matches a file and this file was not modified after the value of the If-Modified-Since header, the server should return HTTP status 304 (Not Modified).

**Comment by serhiy-storchaka** [comment]
New changeset 351adda54bed3afbbf6db7725699679e68722d7d by Serhiy Storchaka (Pierre Quentel) in branch 'master':
bpo-29654 : Support If-Modified-Since HTTP header (browser cache) (#298)
https://github.com/python/cpython/commit/351adda54bed3afbbf6db7725699679e68722d7d

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Pierre.

**Comment by vstinner** [comment]
FYI there was a race condition, impacting Windows. I just fixed it: bpo-31066, commit 28ce07ae9e34c70eea6b52515c7e00001cefd41e.

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
Thanks for telling me. I must have run the test hundreds of times now, on a
Windows 7 PC, and this bug never occured.

Just for my information, why do you add temp.flush() in the "with" block ?
I thought the context manager took care of this.

2017-07-28 18:19 GMT+02:00 STINNER Victor \<report@bugs.python.org\>:

>
> STINNER Victor added the comment:
>
> FYI there was a race condition, impacting Windows. I just fixed it:
> bpo-31066, commit 28ce07ae9e34c70eea6b52515c7e00001cefd41e.
>
> \----------
> nosy: +haypo
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29654\>
> _______________________________________
>

**Comment by serhiy-storchaka** [comment]
Thank you Victor!

I suppose temp.flush() is a remnant of other (unsuccessful) attempt to fix a race condition.

**Comment by vstinner** [comment]
I suppose temp.flush() is a remnant of other (unsuccessful) attempt to fix
a race condition.

I didn't try only with .flush(). I prefer to explicitly .flush(), just in
case :-) Using correctly a file system is complex because of all layers of
caching.
