### ISSUE TITLE
Add function to gc module to check if any reference cycles have been reclaimed.

### ISSUE THREAD

**Issue by 8ce5a782-71dd-4338-8224-b2eb4d26d1b6** [python/cpython#73857]
BPO | [29671](https://bugs.python.org/issue29671)
--- | :---
Nosy | @mdickinson, @Sagiri

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-01.08:46:15.033>
created_at = <Date 2017-02-27.20:35:12.214>
labels = ['type-feature', '3.7']
title = 'Add function to gc module to check if any reference cycles have been reclaimed.'
updated_at = <Date 2017-03-01.08:46:15.032>
user = 'https://github.com/Sagiri'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-01.08:46:15.032>
actor = 'mark.dickinson'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-01.08:46:15.033>
closer = 'mark.dickinson'
components = []
creation = <Date 2017-02-27.20:35:12.214>
creator = 'Kevin Mills'
dependencies = []
files = []
hgrepos = []
issue_num = 29671
keywords = []
message_count = 5.0
messages = ['288668', '288669', '288670', '288672', '288700']
nosy_count = 2.0
nosy_names = ['mark.dickinson', 'Kevin Mills']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29671'
versions = ['Python 3.7']
```

</p></details>

**Comment by 8ce5a782-71dd-4338-8224-b2eb4d26d1b6** [comment]
The intro paragraph for the gc module's documentation says:

> Since the collector supplements the reference counting already used in Python, you can disable the collector if you are sure your program does not create reference cycles.

How would you ever be sure of that?

While you can prevent reference cycles in your own code, what about your dependencies? You'd have to look through the code of all of your dependencies and transitive dependencies (including the standard library) to verify that none introduce reference cycles. And then you'd have to redo that work when upgrading any of them.

I propose adding a function to the gc module that returns True if the gc has reclaimed at least one reference cycle in the course of the current program's execution.

With that, it would be possible to, a program could, before it exits, force a collection and then check if any reference cycles were found over the program's lifetime, and then the programmer could use that information to decide whether they can safely turn off the gc or not.

Obviously that wouldn't guarantee that you could safely turn of the gc (it's possible that garbage with reference cycles is created on other runs of the program) it would at least be some information.

**Comment by mdickinson** [comment]
If I understand correctly, you can already achieve what you want by:

1. Disabling gc (with gc.disable()) at the beginning of your code, and possibly adding a `gc.collect()` immediately afterwards for good measure.
2. Doing a gc.collect() (and taking note of the return value) at the end of your code.
3. To be on the safe side, also check whether there's anything in `gc.garbage`.

If no reference cycles were created, `gc.collect()` will return `0`, and `gc.garbage` will be empty.

**Comment by mdickinson** [comment]
An addendum: I'd note that avoiding reference cycles altogether is hard in modern-day Python. For example, any dynamically-created class creates a reference cycle between the class and its MRO:

```pycon
>>> import gc
>>> gc.disable()
>>> gc.collect()
0
>>> class A(object):
...     pass
... 
>>> del A
>>> gc.collect()
6
```

**Comment by 8ce5a782-71dd-4338-8224-b2eb4d26d1b6** [comment]
gc.disable() at the beginning and then analyzing the results of gc.collect() actually does do what I was wanting, thank you.

Reference cycles in and of themselves aren't the problem. It's only a problem if garbage contains reference cycles. In a normal program, a class wouldn't generally ever become garbage, so it wouldn't be a problem.

**Comment by mdickinson** [comment]
> In a normal program, a class wouldn't generally ever become garbage,

Right; it's only really a problem with dynamically-created classes. Some parts of the standard library (like ctypes), generate such classes.

Okay to close this as rejected?
