### ISSUE TITLE
f-strings don't change the values as expected.

### ISSUE THREAD

**Issue by f7b4c825-fa89-4f72-8e71-bf2b1b97ec9c** [python/cpython#73854]
BPO | [29668](https://bugs.python.org/issue29668)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[crazy.png](https://bugs.python.org/file46673/crazy.png "Uploaded as image/png at 2017-02-27.17:25:39 by rafael.capucho")</li><li>[file.py](https://bugs.python.org/file46674/file.py "Uploaded as text/plain at 2017-02-27.17:37:10 by rafael.capucho")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-27.17:58:47.689>
created_at = <Date 2017-02-27.17:25:39.267>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = "f-strings don't change the values as expected."
updated_at = <Date 2017-02-27.18:15:17.781>
user = 'https://bugs.python.org/rafaelcapucho'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-27.18:15:17.781>
actor = 'rafael.capucho'
assignee = 'none'
closed = True
closed_date = <Date 2017-02-27.17:58:47.689>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-02-27.17:25:39.267>
creator = 'rafael.capucho'
dependencies = []
files = ['46673', '46674']
hgrepos = []
issue_num = 29668
keywords = []
message_count = 7.0
messages = ['288649', '288651', '288654', '288655', '288657', '288658', '288659']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'rafael.capucho']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29668'
versions = ['Python 3.6']
```

</p></details>

**Comment by f7b4c825-fa89-4f72-8e71-bf2b1b97ec9c** [comment]
In the attached file, the lines 4 and 6 have the same structure, the line 4 changes the value of {a} properly, the line 6 didn't.

Thank you.

**Comment by serhiy-storchaka** [comment]
Please provide your example as a text.

**Comment by f7b4c825-fa89-4f72-8e71-bf2b1b97ec9c** [comment]
```
a = "some_underscored_value"


u = (f" hello `{a}` cruel world"
     " hi")

print(u)

query = (f"SELECT COUNT(*) "
         "FROM `{a}` entry "
         "WHERE entry.type == 'device' "
         "AND entry.instance == {a}")

print(query)
```

**Comment by serhiy-storchaka** [comment]
What you get? What you expect?

**Comment by f7b4c825-fa89-4f72-8e71-bf2b1b97ec9c** [comment]
I got:

SELECT COUNT(*) FROM `{a}` entry WHERE entry.type == 'device' AND entry.instance == {a}

I expect the value of `{a}` changed, like:

SELECT COUNT(*) FROM `some_underscored_value` entry WHERE entry.type == 'device' AND entry.instance == some_underscored_value

**Comment by serhiy-storchaka** [comment]
The expression is a concatenation of f-string expression f"SELECT COUNT(*) " and three string literals. If you want to substitute the "a" value, convert string literals into f-string expressions:

```py
query = (f"SELECT COUNT(*) "
         f"FROM `{a}` entry "
         f"WHERE entry.type == 'device' "
         f"AND entry.instance == {a}")
```


or

```py
query = ("SELECT COUNT(*) "
         f"FROM `{a}` entry "
         "WHERE entry.type == 'device' "
         f"AND entry.instance == {a}")
```


But be aware that using f-string expressions for formatting SQL queries is not safe in general case. Instead, use the DB-API’s parameter substitution.

**Comment by f7b4c825-fa89-4f72-8e71-bf2b1b97ec9c** [comment]
Serhiy Storchaka,

Thank you for your explanation.
