### ISSUE TITLE
Some gdb macros are broken in 3.6

### ISSUE THREAD

**Issue by abalkin** [python/cpython#73859]
BPO | [29673](https://bugs.python.org/issue29673)
--- | :---
Nosy | @abalkin, @vstinner, @ned-deily, @stratakis, @Dormouse759
PRs | <li>python/cpython#6126</li><li>python/cpython#6399</li><li>python/cpython#6400</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-04-06.22:17:40.069>
created_at = <Date 2017-02-28.00:02:47.045>
labels = ['3.7', '3.8']
title = 'Some gdb macros are broken in 3.6'
updated_at = <Date 2018-04-06.22:17:40.068>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-06.22:17:40.068>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-04-06.22:17:40.069>
closer = 'ned.deily'
components = []
creation = <Date 2017-02-28.00:02:47.045>
creator = 'belopolsky'
dependencies = []
files = []
hgrepos = []
issue_num = 29673
keywords = ['patch']
message_count = 10.0
messages = ['288684', '288685', '288687', '313954', '314935', '314947', '315033', '315037', '315038', '315039']
nosy_count = 5.0
nosy_names = ['belopolsky', 'vstinner', 'ned.deily', 'cstratak', 'Dormouse759']
pr_nums = ['6126', '6399', '6400']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29673'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by abalkin** [comment]
Some gdb macros defined in [Misc/gdbinit](https://github.com/python/cpython/blob/main/Misc/gdbinit) got broken when \_PyUnicode_AsString was renamed to PyUnicode_AsUTF8.

(gdb) pystack
No symbol "\_PyUnicode_AsString" in current context.

**Comment by abalkin** [comment]
I tried to simply replace  \_PyUnicode_AsString with PyUnicode_AsUTF8, but it looks like code structure has changed and the pyframe and pystack macros don't work anymore.

**Comment by smontanaro** [comment]
Note that these macros were always expected to be fragile. They depend to a great extent on the layout of the functions in [Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c). I've had to tweak them a couple times over the years.

I'm pretty sure the gdb instance I have available to me at work wasn't configured --with-python, and corporate policies would prevent me from downloading the source and building my own private version. For me, [Misc/gdbinit](https://github.com/python/cpython/blob/main/Misc/gdbinit) is likely to be the best I can do for the foreseeable future. 

If the layout of ceval.c has changed sufficiently between Python 2.x and 3.x, perhaps two versions of gdbinit are warranted, with the version delivered for Python 3 being appropriate for the current release.
