### ISSUE TITLE
Missing import of bisect in the documentation examples

### ISSUE THREAD

**Issue by c6a24554-5737-4174-b47e-54fc0403b8dc** [python/cpython#73855]
BPO | [29669](https://bugs.python.org/issue29669)
--- | :---
Nosy | @rhettinger, @marco-buttu
Files | <li>[import_bisect.patch](https://bugs.python.org/file46676/import_bisect.patch "Uploaded as text/plain at 2017-02-27.18:58:06 by @marco-buttu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-02-28.04:23:23.611>
created_at = <Date 2017-02-27.18:58:06.972>
labels = ['type-feature', '3.7', 'docs']
title = 'Missing import of bisect in the documentation examples'
updated_at = <Date 2017-02-28.04:23:23.610>
user = 'https://github.com/marco-buttu'
```

bugs.python.org fields:
```python
activity = <Date 2017-02-28.04:23:23.610>
actor = 'rhettinger'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-02-28.04:23:23.611>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-02-27.18:58:06.972>
creator = 'marco.buttu'
dependencies = []
files = ['46676']
hgrepos = []
issue_num = 29669
keywords = ['patch']
message_count = 2.0
messages = ['288663', '288691']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'marco.buttu']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29669'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
There is no import of bisect.bisect() and bisect.bisect_left() in the documentation. IMHO the examples are clearer and more complete if we import these functions, as in the attached patch.

**Comment by rhettinger** [comment]
Sorry, but I think this is a waste.  A number of the example sections presume that the module under discussion has been imported.   Also, these docs have been around for a long time without the slightest indication of confusion.
