### ISSUE TITLE
SysLogHandler does not seem to always expand %(loglevel)s properly

### ISSUE THREAD

**Issue by 374dfb4f-6643-4c12-8f07-b7fa83008b28** [python/cpython#73861]
BPO | [29675](https://bugs.python.org/issue29675)
--- | :---
Nosy | @vsajip
Files | <li>[bad.py](https://bugs.python.org/file46679/bad.py "Uploaded as text/plain at 2017-02-28.10:42:29 by thread13"): test file to reproduce the bug</li><li>[good.py](https://bugs.python.org/file46680/good.py "Uploaded as text/plain at 2017-02-28.10:44:20 by thread13")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-01.07:28:38.670>
created_at = <Date 2017-02-28.10:42:29.715>
labels = ['invalid']
title = 'SysLogHandler does not seem to always expand %(loglevel)s properly'
updated_at = <Date 2017-03-01.07:28:38.669>
user = 'https://bugs.python.org/thread13'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-01.07:28:38.669>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-01.07:28:38.670>
closer = 'vinay.sajip'
components = []
creation = <Date 2017-02-28.10:42:29.715>
creator = 'thread13'
dependencies = []
files = ['46679', '46680']
hgrepos = []
issue_num = 29675
keywords = []
message_count = 4.0
messages = ['288702', '288703', '288704', '288742']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'thread13']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29675'
versions = ['Python 2.7']
```

</p></details>

**Comment by 374dfb4f-6643-4c12-8f07-b7fa83008b28** [comment]
On Ubuntu LTS 16.04, SysLogHandler with a custom formatter does not seem to expand loglevel/levelno fields properly, when there are square brackets ( see the attached examples ). Instead, it seems to replace '[%(loglevel)s]' with a '[pid]', and '%(loglevel)s' with 'LOGLEVEL[pid]' .

To test, run 'journalctl -f | grep test_test_test' on one console, and the attached files on another. The output for 'bad.py' looks as follows:
\===
Feb 28 21:30:05 hostname \<test_test_test\>[7117]: logging was configured for process \<7117\>
\===

And should have looked like:
\===
Feb 28 21:30:05 hostname \<test_test_test\>[INFO]: logging was configured for process \<7117\>
\===

For 'good.py', the output is as follows:
\===
Feb 28 21:30:04 hostname \<test_test_test\>INFO[7114]: logging was configured for process \<7114\>
\===

and should have probably been: 
\===
Feb 28 21:30:04 hostname \<test_test_test\>INFO: logging was configured for process \<7114\>
\===

Kind regards, /t13

**Comment by 374dfb4f-6643-4c12-8f07-b7fa83008b28** [comment]
Attaching the other file mentioned.

**Comment by 374dfb4f-6643-4c12-8f07-b7fa83008b28** [comment]
PS. I'm not sure if that is a systemd/journald issue, or indeed a Python bug.

However, it would be nice to clear one possibility. 

For a StreamHandler, it all works as it should.

**Comment by vsajip** [comment]
This is not a bug - logging is formatting the message as per the specified format string. It then prepends the priority and sends the result to the socket. What you are seeing is just how systemd/journald interpret the message that's sent.
