### ISSUE TITLE
gdb/libpython.py does not work with gdb 7.2

### ISSUE THREAD

**Issue by abalkin** [python/cpython#73866]
BPO | [29680](https://bugs.python.org/issue29680)
--- | :---
Nosy | @abalkin, @vstinner, @Mariatta
PRs | <li>python/cpython#363</li><li>python/cpython#363</li><li>python/cpython#534</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2017-03-01.02:36:44.303>
labels = ['type-bug', '3.7']
title = 'gdb/libpython.py does not work with gdb 7.2'
updated_at = <Date 2017-03-27.11:21:30.157>
user = 'https://github.com/abalkin'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.11:21:30.157>
actor = 'vstinner'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = ['Demos and Tools']
creation = <Date 2017-03-01.02:36:44.303>
creator = 'belopolsky'
dependencies = []
files = []
hgrepos = []
issue_num = 29680
keywords = []
message_count = 7.0
messages = ['288730', '288752', '288757', '290279', '290286', '290352', '290587']
nosy_count = 3.0
nosy_names = ['belopolsky', 'vstinner', 'Mariatta']
pr_nums = ['363', '363', '534']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29680'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by abalkin** [comment]
Printing the backtrace in gdb results in Python errors:

```pytb
(gdb) bt
...
#6  0x00007ffff7ba9745 in _PyEval_EvalCodeWithName (_co=<code at remote 0x7ffff1983f40>, globals=Traceback (most recent call last):
  File "/home/a/.virtualenvs/3.6g/bin/python3.6-gdb.py", line 1358, in to_string
    return pyop.get_truncated_repr(MAX_OUTPUT_LEN)
  File "/home/a/.virtualenvs/3.6g/bin/python3.6-gdb.py", line 243, in get_truncated_repr
    self.write_repr(out, set())
  File "/home/a/.virtualenvs/3.6g/bin/python3.6-gdb.py", line 702, in write_repr
    for pyop_key, pyop_value in self.iteritems():
  File "/home/a/.virtualenvs/3.6g/bin/python3.6-gdb.py", line 669, in iteritems
    entries, nentries = self._get_entries(keys)
  File "/home/a/.virtualenvs/3.6g/bin/python3.6-gdb.py", line 717, in _get_entries
    except gdb.error:
AttributeError: 'module' object has no attribute 'error'
...
```

**Comment by vstinner** [comment]
It's a regression introduced in Python 3.6 by CPython change:
https://github.com/python/cpython/commit/d7d2bc8798da3b083e383e949ba01d61b78e4e4d

gdb.error was introduced in gdb 7.3 by the commit 07ca107c2d958b45633ef0cdcce7219a95f0cf01:
https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=commit;f=gdb/python/python.c;h=07ca107c2d958b45633ef0cdcce7219a95f0cf01

**Comment by abalkin** [comment]
Victor, the gdb commit that you mentioned introduced gdb.GdbError which is different from gdb.error. [1]  The correct commit is 621c83642d17cf523c20f55f2ed945a7ec95ea6a. [2]

[1] https://sourceware.org/gdb/current/onlinedocs/gdb/Exception-Handling.html#Exception-Handling
[2] https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=621c83642d17cf523c20f55f2ed945a7ec95ea6a

**Comment by Mariatta** [comment]
New changeset 23b26c4e206427a9e0a1d39240c17a049cf8c732 by Mariatta in branch '3.6':
Fixes bpo-29680: Older gdb does not have gdb.error. (GH-363) (GH-534)
https://github.com/python/cpython/commit/23b26c4e206427a9e0a1d39240c17a049cf8c732

**Comment by Mariatta** [comment]
PR has been merged and backported into 3.6.

If there is nothing else, please close this :)

Thanks.

**Comment by abalkin** [comment]
New changeset 661ca8843fed1183e38db06e52d59ac300bf1c2a by Lev Abalkin in branch 'master':
Fixes bpo-29680: Older gdb does not have gdb.error. (#363)
https://github.com/python/cpython/commit/661ca8843fed1183e38db06e52d59ac300bf1c2a

**Comment by vstinner** [comment]
@belopolsky: [Tools/gdb/libpython.py](https://github.com/python/cpython/blob/main/Tools/gdb/libpython.py) still uses gdb.error in gdb.selected_frame():

        try:
            frame = cls.get_selected_frame()
        except gdb.error:
            # No frame: Python didn't start yet
            return None

See my commit 610f5d739dd22bce352bde59dce3985c73aaefab. Should we change this line as well?

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/363
