### ISSUE TITLE
getopt fails to handle option with missing value in middle of list

### ISSUE THREAD

**Issue by 4a25b443-0fe8-4370-b4e2-61276f57a232** [python/cpython#73867]
BPO | [29681](https://bugs.python.org/issue29681)
--- | :---
Nosy | @vadmium, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-01.06:17:34.279>
created_at = <Date 2017-03-01.03:32:30.858>
labels = ['invalid', 'type-bug', 'library']
title = 'getopt fails to handle option with missing value in middle of list'
updated_at = <Date 2017-03-01.06:17:34.260>
user = 'https://bugs.python.org/MarshallGiguere'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-01.06:17:34.260>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-01.06:17:34.279>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-01.03:32:30.858>
creator = 'Marshall Giguere'
dependencies = []
files = []
hgrepos = []
issue_num = 29681
keywords = []
message_count = 3.0
messages = ['288731', '288737', '288740']
nosy_count = 3.0
nosy_names = ['martin.panter', 'serhiy.storchaka', 'Marshall Giguere']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29681'
versions = ['Python 2.7', 'Python 3.4']
```

</p></details>

**Comment by 4a25b443-0fe8-4370-b4e2-61276f57a232** [comment]
```pycon
Python 3.4.3 (default, Nov 17 2016, 01:08:31) 
[GCC 4.8.4] on linux
>>> from getopt import getopt
>>> argv = [ '-a', '-b', '-c', '-d', 'foo']
>>> opts, args = getopt( argv, 'abc:d:')
>>> opts
[('-a', ''), ('-b', ''), ('-c', '-d')]
>>> args
['foo']
```


Expected behavior:
opts = [('-a', ''), ('-b', ''), ('-c', ''), ('-d', 'foo')]
Throws execption:
getopt.GetoptError: option -c requires argument

Note that -c requires a value, getopt swallows the next option '-d' as the argument to -c.  However, if -c is the last option on the command line getopt properly throws an execption "getopt.GetoptError: option -c requires argument".

The documentation states that getopt will throw an exception when an option requiring a value is missing and exception will be thrown.
"exception getopt.GetoptError
This is raised when an unrecognized option is found in the argument list or when an option requiring an argument is given none."

The option -c requires an argument, none was given, no exception is thrown.  Instead the next option, '-d', is taken as the argument.  I have also tried this test on 2.7 with the same result.

**Comment by vadmium** [comment]
It's not clear what you expected the behaviour to be. A function cannot both raise an exception and return a value.

In any case, you are correct in saying "the next option, '-d', is taken as the argument." I do not think this is a bug. See \<http://pubs.opengroup.org/onlinepubs/9699919799/functions/getopt.html\> for the Posix specification of "getopt".

Perhaps you are confused by a bug or quirk of "argparse", where it treats most CLI arguments that begin with a dash specially, even if according to Posix they would be associated with an option. See bpo-9334.

**Comment by serhiy-storchaka** [comment]
I concur with Martin. This is not a bug.
