### ISSUE TITLE
_PyCode_SetExtra behaviour wrong on allocation failure and after realloc

### ISSUE THREAD

**Issue by 25ae6a71-41ac-46e0-88e8-2d6eaa95af85** [python/cpython#73869]
BPO | [29683](https://bugs.python.org/issue29683)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @brianfcoleman
PRs | <li>python/cpython#376</li><li>python/cpython#402</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-03-03.05:35:28.233>
created_at = <Date 2017-03-01.08:52:12.857>
labels = ['interpreter-core', '3.7', 'performance']
title = '_PyCode_SetExtra behaviour wrong on allocation failure and after realloc'
updated_at = <Date 2017-03-31.16:36:12.804>
user = 'https://github.com/brianfcoleman'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:12.804>
actor = 'dstufft'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-03-03.05:35:28.233>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-01.08:52:12.857>
creator = 'brianfcoleman'
dependencies = []
files = []
hgrepos = []
issue_num = 29683
keywords = []
message_count = 6.0
messages = ['288745', '288747', '288833', '288858', '290341', '290348']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'brianfcoleman']
pr_nums = ['376', '402', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29683'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 25ae6a71-41ac-46e0-88e8-2d6eaa95af85** [comment]
On PyMem_Malloc failure, \_PyCode_SetExtra should set co_extra-\>ce_size = 0.
On PyMem_Realloc failure, \_PyCode_SetExtra should set co_extra-\>ce_size = 0.
On PyMem_Realloc success, \_PyCode_SetExtra should set all unused slots in co_extra-\>ce_extras to NULL.

I will add a GitHub PR for this shortly.

**Comment by 25ae6a71-41ac-46e0-88e8-2d6eaa95af85** [comment]
I have now added a Github pull request here:
https://github.com/python/cpython/pull/376

**Comment by 25ae6a71-41ac-46e0-88e8-2d6eaa95af85** [comment]
I have created a pull request to backport the fix onto 3.6 here:
https://github.com/python/cpython/pull/402

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Brian.

**Comment by serhiy-storchaka** [comment]
New changeset a6e84933d204f807e0e81b6a2237193b2e8ab89a by Serhiy Storchaka (Brian Coleman) in branch '3.6':
bpo-29683 - Fixes to \_PyCode_SetExtra when co_extra-\>ce-\>extras is (#402)
https://github.com/python/cpython/commit/a6e84933d204f807e0e81b6a2237193b2e8ab89a

**Comment by vstinner** [comment]
New changeset 6a9122ce6969902e119133dac660bf515616c7dd by Victor Stinner (Brian Coleman) in branch 'master':
bpo-29683 - Fixes to \_PyCode_SetExtra when co_extra-\>ce-\>extras is (#376)
https://github.com/python/cpython/commit/6a9122ce6969902e119133dac660bf515616c7dd
