### ISSUE TITLE
contextlib.contextmanager may incorrectly unchain RuntimeError

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#73878]
BPO | [29692](https://bugs.python.org/issue29692)
--- | :---
Nosy | @rhettinger, @ncoghlan, @serhiy-storchaka, @JelleZijlstra, @Mariatta, @svelankar
PRs | <li>python/cpython#891</li><li>python/cpython#949</li><li>python/cpython#1079</li><li>python/cpython#1105</li><li>python/cpython#1107</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ncoghlan'
closed_at = <Date 2017-04-13.10:17:40.288>
created_at = <Date 2017-03-02.10:11:35.188>
labels = ['type-bug', '3.7']
title = 'contextlib.contextmanager may incorrectly unchain RuntimeError'
updated_at = <Date 2017-04-13.10:17:40.286>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.10:17:40.286>
actor = 'Mariatta'
assignee = 'ncoghlan'
closed = True
closed_date = <Date 2017-04-13.10:17:40.288>
closer = 'Mariatta'
components = []
creation = <Date 2017-03-02.10:11:35.188>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 29692
keywords = ['3.5regression']
message_count = 10.0
messages = ['288793', '290813', '291183', '291185', '291466', '291468', '291472', '291594', '291596', '291597']
nosy_count = 6.0
nosy_names = ['rhettinger', 'ncoghlan', 'serhiy.storchaka', 'JelleZijlstra', 'Mariatta', 'svelankar']
pr_nums = ['891', '949', '1079', '1105', '1107']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29692'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ncoghlan** [comment]
As part of PEP-479, an extra check was added to contextlib.\_GeneratorContextManager to avoid getting confused when a StopIteration exception was raised in the body of the with statement, and hence thrown into the generator body implementing the context manager.

This extra check should only be used when the passed in exception is `StopIteration`, but that guard is currently missing, so it may unchain arbitrary RuntimeError exceptions if they set their `__cause__` to the originally passed in value.

Compare the current contextmanager behaviour:

```
>>> from contextlib import contextmanager
>>> @contextmanager
... def chain_thrown_exc():
...     try:
...         yield
...     except Exception as exc:
...         raise RuntimeError("Chained!") from exc
... 
>>> with chain_thrown_exc():
...     1/0
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero
```

To the expected inline behaviour:

```
>>> try:
...     1/0
... except Exception as exc:
...     raise RuntimeError("Chained!") from exc
... 
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
ZeroDivisionError: division by zero

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
RuntimeError: Chained!

```

**Comment by serhiy-storchaka** [comment]
The \_\_exit__() method doesn't conform PEP-8.

PEP-8: """Be consistent in return statements. Either all return statements in a function should return an expression, or none of them should. If any return statement returns an expression, any return statements where no value is returned should explicitly state this as return None , and an explicit return statement should be present at the end of the function (if reachable)."""

The \_\_exit__() method has explicit "return False", bare "return", and implicit "return" at the end of the method. Together with different styles in different "except" clauses this makes it slightly hard to read.

**Comment by rhettinger** [comment]
PEP-8's rule makes sense elsewhere, but for context managers I think an implicit return None is the norm and that making it explicit wouldn't improve readability.

**Comment by serhiy-storchaka** [comment]
Then the exception for the \_\_exit__ method should be documented in PEP-8.

**Comment by ncoghlan** [comment]
New changeset 00c75e9a45ff0366c185e9e8a2e23af5a35481b0 by Nick Coghlan (svelankar) in branch 'master':
bpo-29692: contextlib.contextmanager may incorrectly unchain RuntimeError (GH-949)
https://github.com/python/cpython/commit/00c75e9a45ff0366c185e9e8a2e23af5a35481b0

**Comment by ncoghlan** [comment]
This has been merged for 3.7, but cherry-picks to the other branches are still needed.

I also inadvertently missed adding svelankar's name (Siddharth Velankar) to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS), so that oversight will need to be tidied up as well.

**Comment by ncoghlan** [comment]
New changeset e8a6bb4f3936123f3eca0b6cea05e2875a2722bc by Nick Coghlan in branch 'master':
bpo-29692: Add missing ACKS entry (bpo-1079)
https://github.com/python/cpython/commit/e8a6bb4f3936123f3eca0b6cea05e2875a2722bc

**Comment by Mariatta** [comment]
New changeset 9b409ff41ceb2d7ea7e8d25a7bbf5eb7d46625f3 by Mariatta in branch '3.6':
[3.6] bpo-29692: contextlib.contextmanager may incorrectly unchain RuntimeError (GH-949) (bpo-1105)
https://github.com/python/cpython/commit/9b409ff41ceb2d7ea7e8d25a7bbf5eb7d46625f3

**Comment by Mariatta** [comment]
New changeset 4d015a40a7b9c3c1b8cfbe81453187d700a43163 by Mariatta in branch '3.5':
[3.5] bpo-29692: contextlib.contextmanager may incorrectly unchain RuntimeError (GH-949) (bpo-1107)
https://github.com/python/cpython/commit/4d015a40a7b9c3c1b8cfbe81453187d700a43163

**Comment by Mariatta** [comment]
PR has been backported into 3.5 and 3.6. Thanks all :)
