### ISSUE TITLE
no %z directive for strptime in python2, doc says nothing about it

### ISSUE THREAD

**Issue by f18467eb-51ed-4907-a86f-19236d4ecfb1** [python/cpython#73876]
BPO | [29690](https://bugs.python.org/issue29690)
--- | :---
Nosy | @bitdancer, @deronnax

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-02.13:36:00.090>
created_at = <Date 2017-03-02.07:31:29.175>
labels = ['invalid', 'type-bug', 'library']
title = 'no %z directive for strptime in python2, doc says nothing about it'
updated_at = <Date 2017-03-06.07:32:14.312>
user = 'https://github.com/deronnax'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-06.07:32:14.312>
actor = 'deronnax'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-02.13:36:00.090>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-03-02.07:31:29.175>
creator = 'deronnax'
dependencies = []
files = []
hgrepos = []
issue_num = 29690
keywords = []
message_count = 3.0
messages = ['288782', '288800', '289069']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'deronnax']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29690'
versions = ['Python 2.7']
```

</p></details>

**Comment by f18467eb-51ed-4907-a86f-19236d4ecfb1** [comment]
```pytb
➜  ~ cat dt.py 
from datetime import *
dt = datetime.strptime('+1720', '%z')
print(dt)
➜  ~ python2 dt.py 
Traceback (most recent call last):
  File "dt.py", line 2, in <module>
    dt = datetime.strptime('+1720', '%z')
  File "/usr/lib/python2.7/_strptime.py", line 324, in _strptime
    (bad_directive, format))
ValueError: 'z' is a bad directive in format '%z'
➜  ~ python3 dt.py
1900-01-01 00:00:00+17:20
```


We should either mention it in doc, either cherry-pick the code from python3

**Comment by bitdancer** [comment]
This almost qualifies as a FAQ :)

In 2.7 (and in 3.x, though we've added some additional platform independent stuff there), strptime supports what the platform supports, and this is documented: "The following is a list of all the format codes that the C standard (1989 version) requires, and these work on all platforms with a standard C implementation. Note that the 1999 version of the C standard added additional format codes."

Windows, for one, is not a standard C implementation in that sense.

Note that the python3 documentation is a bit clearer about this than the 2.7 docs.  If you want to open a PR to backport the doc improvements, feel free to reopen this issue.

**Comment by f18467eb-51ed-4907-a86f-19236d4ecfb1** [comment]
Neither documentation is clear on whether each of those flags are available for strptime too. A precision should be added on a flag if it's not available for strptime. What do you think ?
