### ISSUE TITLE
Minor regression in PyEval_CallObjectWithKeywords()

### ISSUE THREAD

**Issue by methane** [python/cpython#73870]
BPO | [29684](https://bugs.python.org/issue29684)
--- | :---
Nosy | @vstinner, @methane
PRs | <li>python/cpython#87</li><li>python/cpython#378</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-01.12:37:29.511>
created_at = <Date 2017-03-01.09:20:00.223>
labels = []
title = 'Minor regression in PyEval_CallObjectWithKeywords()'
updated_at = <Date 2017-03-31.16:36:12.571>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:12.571>
actor = 'dstufft'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-01.12:37:29.511>
closer = 'vstinner'
components = []
creation = <Date 2017-03-01.09:20:00.223>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 29684
keywords = ['3.6regression']
message_count = 4.0
messages = ['288748', '288755', '290353', '290354']
nosy_count = 2.0
nosy_names = ['vstinner', 'methane']
pr_nums = ['87', '378', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29684'
versions = []
```

</p></details>

**Comment by methane** [comment]
This issue is spin off bpo-29548.

```py
PyEval_CallObjectWithKeywords(PyObject *func, PyObject *args, PyObject *kwargs)
should raise TypeError when kwargs is not dict.
But after this commit [1], assert(PyDict_Check(kwargs)) can be called when args==NULL.
```


[1] https://github.com/python/cpython/commit/155ea65e5c88d250a752ee5321860ef11ede4085

**Comment by vstinner** [comment]
Both PR have been merged, I close the issue.

**Comment by methane** [comment]
New changeset 023532e558bb0c5bf60195aebbafe63a0bebd85e by INADA Naoki in branch '3.6':
bpo-29684: Fix minor regression of PyEval_CallObjectWithKeywords. (GH-378)
https://github.com/python/cpython/commit/023532e558bb0c5bf60195aebbafe63a0bebd85e

**Comment by methane** [comment]
New changeset 3824cd8fd44f287ea2a76120a39ee76eb34bbf32 by INADA Naoki in branch 'master':
bpo-29684: Fix regression of PyEval_CallObjectWithKeywords (GH-87)
https://github.com/python/cpython/commit/3824cd8fd44f287ea2a76120a39ee76eb34bbf32
