### ISSUE TITLE
Wrong ECDH configuration with OpenSSL 1.1

### ISSUE THREAD

**Issue by tiran** [python/cpython#73883]
BPO | [29697](https://bugs.python.org/issue29697)
--- | :---
Nosy | @tiran, @ned-deily, @dstufft
PRs | <li>python/cpython#395</li><li>python/cpython#397</li><li>python/cpython#398</li><li>python/cpython#399</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-03-03.19:21:10.945>
created_at = <Date 2017-03-02.16:18:22.938>
labels = ['expert-SSL', 'type-bug', '3.7']
title = 'Wrong ECDH configuration with OpenSSL 1.1'
updated_at = <Date 2017-03-24.23:14:30.855>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:14:30.855>
actor = 'dstufft'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-03-03.19:21:10.945>
closer = 'dstufft'
components = ['SSL']
creation = <Date 2017-03-02.16:18:22.938>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 29697
keywords = ['3.6regression']
message_count = 7.0
messages = ['288812', '288813', '288914', '290343', '290344', '290345', '290346']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'ned.deily', 'dstufft']
pr_nums = ['395', '397', '398', '399']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29697'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by tiran** [comment]
I think I made a mistake during the port to OpenSSL 1.1.x. defined(OPENSSL_VERSION_1_1) is on the wrong ifndef block.

\------------------------------------------------------------------
Old code

```c
#ifndef OPENSSL_NO_ECDH
    /* Allow automatic ECDH curve selection (on OpenSSL 1.0.2+), or use
       prime256v1 by default.  This is Apache mod_ssl's initialization
       policy, so we should be safe. */
#if defined(SSL_CTX_set_ecdh_auto)
    SSL_CTX_set_ecdh_auto(self->ctx, 1);
#else
    {
        EC_KEY *key = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
        SSL_CTX_set_tmp_ecdh(self->ctx, key);
        EC_KEY_free(key);
    }
#endif
#endif
```


------------------------------------------------------------------
New code with OpenSSL 1.1.x compatibility

```c
#ifndef OPENSSL_NO_ECDH
    /* Allow automatic ECDH curve selection (on OpenSSL 1.0.2+), or use
       prime256v1 by default.  This is Apache mod_ssl's initialization
       policy, so we should be safe. OpenSSL 1.1 has it enabled by default.
     */
#if defined(SSL_CTX_set_ecdh_auto) && !defined(OPENSSL_VERSION_1_1)
    SSL_CTX_set_ecdh_auto(self->ctx, 1);
#else
    {
        EC_KEY *key = EC_KEY_new_by_curve_name(NID_X9_62_prime256v1);
        SSL_CTX_set_tmp_ecdh(self->ctx, key);
        EC_KEY_free(key);
    }
#endif
#endif
```

**Comment by tiran** [comment]
The bug report was too much of a "memo to me" brain dump. Let me clarify.

For OpenSSL 1.0.2 we can call SSL_CTX_set_ecdh_auto() to enable ECDH curves. For OpenSSL \< 1.0.2 it was necessary to configure a curve with SSL_CTX_set_tmp_ecdh(). OpenSSL \>= 1.1.0 does neither need ecdh_auto nor tmp_ecdh. 

```c
#if !defined(OPENSSL_NO_ECDH) && !defined(OPENSSL_VERSION_1_1)
...
#endif
```

**Comment by ned-deily** [comment]
Since the PRs have been merged, can this issue be closed now?

**Comment by dstufft** [comment]
New changeset f1a696efd6ca674579e25de29ec4053ff5a5ade1 by Donald Stufft in branch '2.7':
bpo-29697: Don't use OpenSSL \<1.0.2 fallback on 1.1+ (GH-399)
https://github.com/python/cpython/commit/f1a696efd6ca674579e25de29ec4053ff5a5ade1

**Comment by dstufft** [comment]
New changeset 784ba7c8ad53638c94270011d55d2536ff0cd2dd by Donald Stufft in branch '3.6':
bpo-29697: Don't use OpenSSL \<1.0.2 fallback on 1.1+ (#397)
https://github.com/python/cpython/commit/784ba7c8ad53638c94270011d55d2536ff0cd2dd

**Comment by dstufft** [comment]
New changeset 564ace834f23587937b325e3545abe3f17fdbd2a by Donald Stufft in branch '3.5':
bpo-29697: Don't use OpenSSL \<1.0.2 fallback on 1.1+ (GH-398)
https://github.com/python/cpython/commit/564ace834f23587937b325e3545abe3f17fdbd2a

**Comment by dstufft** [comment]
New changeset 8ae264ce6dfcd6923d7bbde0e975389bea7d9881 by Donald Stufft in branch 'master':
bpo-29697: Don't use OpenSSL \<1.0.2 fallback on 1.1+ (GH-395)
https://github.com/python/cpython/commit/8ae264ce6dfcd6923d7bbde0e975389bea7d9881
