### ISSUE TITLE
Error 0x80070003: Failed to launch elevated child process

### ISSUE THREAD

**Issue by 7180b0e6-0c34-41b9-a129-7337c8c3d9e3** [python/cpython#73888]
BPO | [29702](https://bugs.python.org/issue29702)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba
Files | <li>[Python 3.5.3 (64-bit)_20170302121038.log](https://bugs.python.org/file46690/Python%203.5.3%20%2864-bit%29_20170302121038.log "Uploaded as text/plain at 2017-03-02.21:49:04 by alevonian"): Installation log file.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-18.06:06:57.647>
created_at = <Date 2017-03-02.21:49:04.703>
labels = ['type-bug', 'expert-installation', 'OS-windows']
title = 'Error 0x80070003: Failed to launch elevated child process'
updated_at = <Date 2017-06-18.06:06:57.646>
user = 'https://bugs.python.org/alevonian'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-18.06:06:57.646>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-18.06:06:57.647>
closer = 'eryksun'
components = ['Installation', 'Windows']
creation = <Date 2017-03-02.21:49:04.703>
creator = 'alevonian'
dependencies = []
files = ['46690']
hgrepos = []
issue_num = 29702
keywords = []
message_count = 7.0
messages = ['288834', '288848', '288891', '288910', '288928', '294097', '296260']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'alevonian', 'Kai Shen']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29702'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 7180b0e6-0c34-41b9-a129-7337c8c3d9e3** [comment]
For some reason, after uninstalling Python 3.5.2 on my Windows 10 (64 bit - latest version), I am no longer able to install any new version of Python after version 3.4.3

I keep getting the failure to elevate privileges. I have of course tried to run the installer as Admin, or even launch a command prompt as admin or powershell as admin then run the installer with no luck. 

Disabling Windows Defender did not help.

I have also lowered UAC all the way down, to no reporting, still no luck.

The log file attached is for the 64 bit installer for 3.5.3 but I get identical results with the 32 bit installers for version 3.5.2 and 3.5.1.

I can install latest Anaconda and also Python 3.4.3 without issues.

I also had no problem installing 3.5.3 on another of my machines with same Windows 10 (64 bit) and that machine accepts the install without issues.

Once again, I had version 3.5.2 running fine until I uninstalled it to upgrade.

**Comment by eryksun** [comment]
The error message is misleading. It happens that WiX is trying to run an elevated process (see the WiX functions CoreLaunchApprovedExe, CoreElevate, ElevationElevate, and PipeLaunchChildProcess). However, the actual error code has nothing to do with elevation. Error code 0x80070003 is a 32-bit HRESULT error originating from the Windows API (0x8007). The 16-bit Windows error is ERROR_PATH_NOT_FOUND (0x0003). According to the installation log, this error is from trying to shell execute "C:\\Users\\ALEVON\~1\\AppData\\Local\\Temp\\{8D001A8F-7F1F-4183-A574-76127D642F75}\\.be\\python-3.5.3-amd64.exe". Notably the error is in the path instead of ERROR_FILE_NOT_FOUND (0x0002), so the problem may have been that one of the parent directories was missing.

**Comment by 7180b0e6-0c34-41b9-a129-7337c8c3d9e3** [comment]
Hi Eryk,
I did think of that as well so I actually navigated to that temp folder (from the log) which the installer created (every time it runs, it creates a new temp folder and places the executable there) and executed that directly and got exactly the same log message.
So the folder exists, since the installer is creating it, and the .exe exists.
Armen

      From: Eryk Sun \<report@bugs.python.org\>
 To: alevonian@yahoo.com 
 Sent: Thursday, March 2, 2017 7:20 PM
 Subject: [bpo-29702] Error 0x80070003: Failed to launch elevated child process

Eryk Sun added the comment:

The error message is misleading. It happens that WiX is trying to run an elevated process (see the WiX functions CoreLaunchApprovedExe, CoreElevate, ElevationElevate, and PipeLaunchChildProcess). However, the actual error code has nothing to do with elevation. Error code 0x80070003 is a 32-bit HRESULT error originating from the Windows API (0x8007). The 16-bit Windows error is ERROR_PATH_NOT_FOUND (0x0003). According to the installation log, this error is from trying to shell execute "C:\\Users\\ALEVON\~1\\AppData\\Local\\Temp\\{8D001A8F-7F1F-4183-A574-76127D642F75}\\.be\\python-3.5.3-amd64.exe". Notably the error is in the path instead of ERROR_FILE_NOT_FOUND (0x0002), so the problem may have been that one of the parent directories was missing.

\----------
nosy: +eryksun

_______________________________________
Python tracker \<report@bugs.python.org\>
\<http://bugs.python.org/issue29702\>
_______________________________________

**Comment by eryksun** [comment]
When run directly from the temp directory path that's reported in the log, does the new log say that the installer is trying to run python-3.5.3-amd64.exe from that same path, or is it trying to run it from a new directory?

**Comment by 7180b0e6-0c34-41b9-a129-7337c8c3d9e3** [comment]
If I close the failure to run dialog, the temp directory is also destroyed, thus getting rid of the temp executable, however, while the fail dialog is up and I travel to where it says it fails to run the executable, it then yet creates another temp guid directory and logs a failure as unable to run from the thing it just created.So I can recursively launch and fail.
I don't understand why it wants to run another executable that is itself when it is already running it.

      From: Eryk Sun \<report@bugs.python.org\>
 To: alevonian@yahoo.com 
 Sent: Friday, March 3, 2017 10:44 AM
 Subject: [bpo-29702] Error 0x80070003: Failed to launch elevated child process

Eryk Sun added the comment:

When run directly from the temp directory path that's reported in the log, does the new log say that the installer is trying to run python-3.5.3-amd64.exe from that same path, or is it trying to run it from a new directory?

\----------

_______________________________________
Python tracker \<report@bugs.python.org\>
\<http://bugs.python.org/issue29702\>
_______________________________________

**Comment by e8c9f46f-cdde-4fbc-8cea-060581baab7e** [comment]
when you perform the installation and choose the "Download debugging symbols" or "Download debug binaries", make sure your internet connection is up and available.

**Comment by 7180b0e6-0c34-41b9-a129-7337c8c3d9e3** [comment]
OK, so this bug tuned out to be related to the Windows 10 version I had prior to the just now updated 1703.
I discovered one other Visual Studio installation that was failing.
However, after the update to the latest Windows 1703, the installation issues are resolved.

So we can close this as it seems it was a possibly broken windows 10 version. As a reminder, I was only experiencing this issue on only 1 machine.

Cheers.
