### ISSUE TITLE
Weird keyword parameter names in builtins

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73881]
BPO | [29695](https://bugs.python.org/issue29695)
--- | :---
Nosy | @brettcannon, @rhettinger, @vstinner, @bitdancer, @serhiy-storchaka
PRs | <li>python/cpython#486</li><li>python/cpython#518</li><li>python/cpython#520</li><li>python/cpython#703</li><li>python/cpython#552</li>
Files | <li>[deprecate-keyword-x.patch](https://bugs.python.org/file46684/deprecate-keyword-x.patch "Uploaded as text/plain at 2017-03-02.14:54:04 by @serhiy-storchaka")</li><li>[deprecate-keyword-sequence.patch](https://bugs.python.org/file46685/deprecate-keyword-sequence.patch "Uploaded as text/plain at 2017-03-02.14:54:17 by @serhiy-storchaka")</li><li>[deprecate-bad-keywords.patch](https://bugs.python.org/file46686/deprecate-bad-keywords.patch "Uploaded as text/plain at 2017-03-02.16:05:13 by @serhiy-storchaka")</li><li>[remove-bad-keywords.patch](https://bugs.python.org/file46702/remove-bad-keywords.patch "Uploaded as text/plain at 2017-03-06.06:54:12 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-07.19:47:54.772>
created_at = <Date 2017-03-02.14:54:04.612>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Weird keyword parameter names in builtins'
updated_at = <Date 2017-03-31.16:36:09.226>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:09.226>
actor = 'dstufft'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-07.19:47:54.772>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-02.14:54:04.612>
creator = 'serhiy.storchaka'
dependencies = []
files = ['46684', '46685', '46686', '46702']
hgrepos = []
issue_num = 29695
keywords = ['patch']
message_count = 19.0
messages = ['288802', '288803', '288804', '288805', '288806', '288808', '288809', '288811', '289052', '289067', '289068', '289105', '289107', '289110', '289114', '289115', '290285', '290289', '290294']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'rhettinger', 'vstinner', 'r.david.murray', 'serhiy.storchaka']
pr_nums = ['486', '518', '520', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29695'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patches deprecate the "x" keyword parameter in int(), bool() and float() and the "sequence" keyword parameter in list() and tuple(). Name "x" is meaningless, and name "sequence" is misleading (any iterable is accepted, not just sequence). The documentation uses name "iterable" for list() and tuple().

It is never documented that any of these parameters are accepted by keywords. There was only a test for int(), but it was added just for increasing coverity, not to test intended behavior. Does this mean that the support of keyword arguments can be removed without deprecation?

The general idea got preliminary approval from Guido (https://mail.python.org/pipermail/python-ideas/2017-March/044959.html).

**Comment by bitdancer** [comment]
I don't think we should do it without deprecation, since it could break working code.  But it certainly sounds like a marginal case: I doubt there is \*much* code that uses the existing keyword names.

**Comment by vstinner** [comment]
R. David Murray added the comment:
> I don't think we should do it without deprecation, since it could break working code.  But it certainly sounds like a marginal case: I doubt there is \*much* code that uses the existing keyword names.

I'm not sure that it's worth it to add a deprecation warning in Python
3.7. It's trivial to fix code passing an argument by keyword rather
than by position.

**Comment by serhiy-storchaka** [comment]
Well, I was feeling the same, but asked just for the case.

Could you then look at deprecation messages? I'm sure that 'The "x" keyword argument of int() is deprecated' is not the best wording, and may be even ugly wording. Could you please suggest better wording David?

Patches don't document new deprecations because it is not documented that keyword arguments are supported either. Is mentioning in What's New enough?

**Comment by vstinner** [comment]
"What's New in Python 3.7" has a section for such changes: "Porting to
Python 3.7: Changes to the Python API".
https://docs.python.org/dev/whatsnew/3.7.html#porting-to-python-3-7

Oh, I see that you already made a similar change but this one had a
deprecation period of 2 releases (3.5 and 3.6): "A format string
argument for string.Formatter.format() is now positional-only."

See also the positional-only arguments discussion on python-ideas:
* https://mail.python.org/pipermail/python-ideas/2017-February/044879.html
* https://mail.python.org/pipermail/python-ideas/2017-March/044956.html

**Comment by bitdancer** [comment]
So these will become positional only?  In that case I'd say "Using 'x' as a keyword argument is deprecated; specify the value as a positional argument instead"

**Comment by serhiy-storchaka** [comment]
See also bpo-20283. Obviously wrong keyword parameter names in regex methods were deprecated in 2.7, 3.3 and 3.4 and removed in 3.6.

**Comment by serhiy-storchaka** [comment]
Thank you David! Updated warning messages for your suggestion and added entries in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) and What's New.

**Comment by rhettinger** [comment]
I concur with Victor and Serhiy that we can bypass a deprecation phase here and just get it done.  In the rare case of int(x=3.14), the fix is trivial.

**Comment by serhiy-storchaka** [comment]
I already merged the patch as 58d23e68068996c76cac78887ec67dee68cdbc72.

If you think that it would be better to remove without deprecation, the following patch does this.

**Comment by rhettinger** [comment]
I do think it would be better to not have the deprecation.

**Comment by vstinner** [comment]
> If you think that it would be better to remove without deprecation, the following patch does this.

@Serhiy: Can you please create a PR for it?

**Comment by serhiy-storchaka** [comment]
If David agrees with this.

**Comment by bitdancer** [comment]
If Raymond is on the side of skipping the deprecation than I'm good with it.  Like I said, this is a marginal case.

**Comment by serhiy-storchaka** [comment]
Thanks all!

**Comment by vstinner** [comment]
Unhappy buildbot.

http://buildbot.python.org/all/builders/AMD64%20Debian%20root%203.x/builds/456/steps/test/logs/stdio

\======================================================================
ERROR: test_keyword_arguments (test.test_descr.ClassPropertiesAndMethods)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/root/buildarea/3.x.angelico-debian-amd64/build/Lib/test/test_descr.py", line 3451, in test_keyword_arguments
    list.__init__(a, sequence=[0, 1, 2])
TypeError: list() does not take keyword arguments
```


======================================================================
ERROR: test_keywords (test.test_descr.ClassPropertiesAndMethods)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/root/buildarea/3.x.angelico-debian-amd64/build/Lib/test/test_descr.py", line 2888, in test_keywords
    self.assertEqual(int(x=1), 1)
TypeError: 'x' is an invalid keyword argument for this function
```

**Comment by brettcannon** [comment]
New changeset d908fd9ee1c307f7066023eb2031c0f509036cbc by Brett Cannon (Serhiy Storchaka) in branch 'master':
bpo-29695: Fixed tests after removing keyword args support in some basic type constructors. (GH-520)
https://github.com/python/cpython/commit/d908fd9ee1c307f7066023eb2031c0f509036cbc

**Comment by serhiy-storchaka** [comment]
New changeset 2e5642422f6234fd8d0c082142b27340e588f96e by Serhiy Storchaka in branch 'master':
bpo-29695: Remove bad keyword parameters in int(), bool(), float(), list() and tuple(). (#518)
https://github.com/python/cpython/commit/2e5642422f6234fd8d0c082142b27340e588f96e

**Comment by serhiy-storchaka** [comment]
New changeset 58d23e68068996c76cac78887ec67dee68cdbc72 by Serhiy Storchaka in branch 'master':
bpo-29695: Deprecated using bad named keyword arguments in builtings: (#486)
https://github.com/python/cpython/commit/58d23e68068996c76cac78887ec67dee68cdbc72
