### ISSUE TITLE
Fix asyncio to support instantiation of new event loops in subprocesses

### ISSUE THREAD

**Issue by 1st1** [python/cpython#73889]
BPO | [29703](https://bugs.python.org/issue29703)
--- | :---
Nosy | @larryhastings, @ned-deily, @1st1
PRs | <li>python/cpython#404</li><li>python/cpython#410</li><li>python/cpython#411</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/1st1'
closed_at = <Date 2017-03-03.19:28:23.958>
created_at = <Date 2017-03-02.21:55:45.240>
labels = ['type-bug', '3.7', 'release-blocker', 'expert-asyncio']
title = 'Fix asyncio to support instantiation of new event loops in subprocesses'
updated_at = <Date 2017-03-31.16:36:25.591>
user = 'https://github.com/1st1'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:25.591>
actor = 'dstufft'
assignee = 'yselivanov'
closed = True
closed_date = <Date 2017-03-03.19:28:23.958>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-03-02.21:55:45.240>
creator = 'yselivanov'
dependencies = []
files = []
hgrepos = []
issue_num = 29703
keywords = ['3.5regression', '3.6regression']
message_count = 8.0
messages = ['288835', '288836', '288837', '288915', '288919', '290336', '290337', '290340']
nosy_count = 3.0
nosy_names = ['larry', 'ned.deily', 'yselivanov']
pr_nums = ['404', '410', '411', '552']
priority = 'release blocker'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29703'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1st1** [comment]
Proxy for https://github.com/python/asyncio/pull/497

Ned, this needs to be in 3.6.1, working code from 3.4 doesn't work in 3.6.0: http://stackoverflow.com/questions/42546099/python-asyncio-migrate-from-3-4-to-3-5/42566336#42566336

**Comment by ned-deily** [comment]
OK. I assume you will make PRs for python/cpython and cherry-pack to the 3.6 and 3.5 branches?

**Comment by 1st1** [comment]
> OK. I assume you will make PRs for python/cpython and cherry-pack to the 3.6 and 3.5 branches?

Yes, working on it!

**Comment by ned-deily** [comment]
With the PRs merged, can this issue be closed now?

**Comment by 1st1** [comment]
Yes, closing the issue. Thanks, Ned!

**Comment by 1st1** [comment]
New changeset 8b73b6198bc0753c5ce6e8f91eb7bddc2bd42a73 by Yury Selivanov in branch '3.5':
bpo-29703: asyncio: Fix creating new event loops in child processes. (#411)
https://github.com/python/cpython/commit/8b73b6198bc0753c5ce6e8f91eb7bddc2bd42a73

**Comment by 1st1** [comment]
New changeset 01e5230ef0b28658cf7311be199363eda98808bd by Yury Selivanov in branch '3.6':
bpo-29703: asyncio: Fix creating new event loops in child processes. (#404) (#410)
https://github.com/python/cpython/commit/01e5230ef0b28658cf7311be199363eda98808bd

**Comment by 1st1** [comment]
New changeset ba7e1f9a4e06c0b4ad594fd64edcaf7292515820 by Yury Selivanov in branch 'master':
bpo-29703: asyncio: Fix creating new event loops in child processes. (#404)
https://github.com/python/cpython/commit/ba7e1f9a4e06c0b4ad594fd64edcaf7292515820
