### ISSUE TITLE
shutil.rmtree should not fail with FileNotFoundError (race condition)

### ISSUE THREAD

**Issue by 39c07e1b-89c0-4d3a-896b-96ef642f9223** [python/cpython#73885]
BPO | [29699](https://bugs.python.org/issue29699)
--- | :---
Nosy | @giampaolo, @serhiy-storchaka, @dkg, @jessefarnham, @websurfer5, @iritkatriel, @coroa
PRs | <li>python/cpython#13580</li>
Files | <li>[breaker.c](https://bugs.python.org/file46687/breaker.c "Uploaded as text/x-csrc at 2017-03-02.19:12:23 by @dkg"): C program to tickle the shutil.rmtree race condition</li><li>[demo.py](https://bugs.python.org/file46688/demo.py "Uploaded as text/plain at 2017-03-02.19:13:29 by @dkg")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-02.19:12:23.996>
labels = ['type-bug', 'library']
title = 'shutil.rmtree should not fail with FileNotFoundError (race condition)'
updated_at = <Date 2021-12-14.21:57:38.726>
user = 'https://github.com/dkg'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-14.21:57:38.726>
actor = 'coroa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-03-02.19:12:23.996>
creator = 'dkg'
dependencies = []
files = ['46687', '46688']
hgrepos = []
issue_num = 29699
keywords = ['patch']
message_count = 10.0
messages = ['288822', '288823', '319374', '321458', '343530', '396167', '396177', '396185', '396186', '408570']
nosy_count = 8.0
nosy_names = ['giampaolo.rodola', 'serhiy.storchaka', 'dkg', 'jesse.farnham', 'Jeffrey.Kintscher', 'iritkatriel', 'noamda', 'coroa']
pr_nums = ['13580']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29699'
versions = []
```

</p></details>

**Comment by 39c07e1b-89c0-4d3a-896b-96ef642f9223** [comment]
There is a race condition in shutil.rmtree, where if a file gets removed between when rmtree plans to remove it and when it gets around to removing it, a FileNotFound exception gets raised.

The expected semantics of rmtree imply that if the filesystem tree is removed, then the command has succeeded, so it doesn't make sense for rmtree to raise a FileNotFound error if someone else happened to have deleted the file before rmtree gets to it.

I'm attaching a C program (for GNU/Linux) which uses inotify to remove the other file in a directory when either file is removed.  This triggers the rmtree failure.

This behavior has caused a number of workarounds in external projects, like:

  https://bitbucket.org/vinay.sajip/python-gnupg/commits/492fd45ca073a90aac434320fb0c8fe8d01f782b
  https://git.gnupg.org/cgi-bin/gitweb.cgi?p=gpgme.git;a=commitdiff;h=de8494b16bc50c60a8438f2cae1f8c88e8949f7a

It would be better for shutil.rmtree to ignore this particular exception (FileNotFoundError).

Another option for users is to set ignore_errors=True, but this ends up ignoring \*all* errors, which doesn't seem like the right decision.

Finally, of course, a user could specify some sort of onerror function that explictly ignores FileNotFoundError, but this seems pretty complicated for the common pattern.

It's possible that shutil.rmtree() wants to raise FileNotFoundError if the actual argument passed by the user does not itself exist, but it really doesn't make sense to raise that error for any of the elements further down in the tree.

**Comment by 39c07e1b-89c0-4d3a-896b-96ef642f9223** [comment]
and here is python demonstration script that will build breaker.c and then use it to cause the error to be raised from shutils.rmtree.

the output of demo.py looks like this:

```pytb
make: 'breaker' is up to date.
Traceback (most recent call last):
  File "./demo.py", line 14, in <module>
    shutil.rmtree('xx')
  File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
FileNotFoundError: [Errno 2] No such file or directory: 'b'
```

**Comment by serhiy-storchaka** [comment]
Done in the duplicate issue #81441.
