### ISSUE TITLE
Use namedtuple in string.Formatter.parse iterator response

### ISSUE THREAD

**Issue by facundobatista** [python/cpython#73882]
BPO | [29696](https://bugs.python.org/issue29696)
--- | :---
Nosy | @rhettinger, @facundobatista, @ericvsmith, @serhiy-storchaka, @csabella, @pablogsal
PRs | <li>python/cpython#3980</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-26.19:26:55.143>
created_at = <Date 2017-03-02.15:34:03.483>
labels = ['3.7', 'type-bug', 'library']
title = 'Use namedtuple in string.Formatter.parse iterator response'
updated_at = <Date 2019-05-26.19:26:55.143>
user = 'https://github.com/facundobatista'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-26.19:26:55.143>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-26.19:26:55.143>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-03-02.15:34:03.483>
creator = 'facundobatista'
dependencies = []
files = []
hgrepos = []
issue_num = 29696
keywords = ['patch']
message_count = 10.0
messages = ['288807', '288854', '288873', '288874', '288907', '304533', '304548', '304570', '304571', '342720']
nosy_count = 6.0
nosy_names = ['rhettinger', 'facundobatista', 'eric.smith', 'serhiy.storchaka', 'cheryl.sabella', 'pablogsal']
pr_nums = ['3980']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29696'
versions = ['Python 3.7']
```

</p></details>

**Comment by facundobatista** [comment]
Right now:

```pycon
>>> Formatter().parse("mira como bebebn los peces en el {rio} {de} {la} plata")
<formatteriterator object at 0x7f1fc7c7f150>
>>> next(_)
('mira como bebebn los peces en el ', 'rio', '', None)
```


This returned tuple should be a namedtuple, so it's self-explained for people exploring this (and usage of the fields become clearer)

**Comment by rhettinger** [comment]
I think this is all C coded, so it would entail making a new structseq object.

**Comment by ericvsmith** [comment]
It's in string.py, so it would be easy just to add a namedtuple there:

```py
class Formatter:
...
    def parse(self, format_string):
        return _string.formatter_parser(format_string)
```


I don't see a need to add a structseq to \_string, since it's a private API.

**Comment by serhiy-storchaka** [comment]
collections is a moderately heavy module with many dependencies. string is a light module, it imports only \_string. I'm -1 for using namedtuple in the string module.

**Comment by rhettinger** [comment]
I would also rather see string.py left light weight.  It would be better to change the upstream C code to use structseq.

**Comment by serhiy-storchaka** [comment]
I'm not convinced that a named tuple is needed here.

**Comment by ericvsmith** [comment]
It does seem like overkill for something that's rarely used. I'm -0 on the structseq version.

**Comment by pablogsal** [comment]
IMHO this change makes things a bit more consistent. In lots of places when a tuple is returned, a `structseq` is used to improve readability on the returned result. Some examples of this are:

* grp.struct_group
* os.terminal_size
* pwd.struct_passwd
* resource.struct_rusage
* signal.struct_siginfo
* time.struct_time
* spwd.struct_spwd
* sys.float_info
* sys.int_info
* string.FormatterItem
* sys.hash_info
* sys.getwindowsversion
* sys.flags
* sys.version_info
* sys.thread_info

**Comment by pablogsal** [comment]
With the exception of string.FormatterItem, which is the change at hand.
