### ISSUE TITLE
Can't read data from Transport after asyncio.SubprocessStreamProtocol closes

### ISSUE THREAD

**Issue by 35e5f348-5b4c-46dc-914b-60f70128bf8f** [python/cpython#73890]
BPO | [29704](https://bugs.python.org/issue29704)
--- | :---
Nosy | @1st1, @SethMichaelLarson
PRs | <li>python/cpython#405</li><li>python/cpython#415</li><li>python/cpython#416</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-03.23:12:44.377>
created_at = <Date 2017-03-02.22:24:23.132>
labels = ['type-bug', 'expert-asyncio']
title = "Can't read data from Transport after asyncio.SubprocessStreamProtocol closes"
updated_at = <Date 2017-03-31.16:36:23.221>
user = 'https://github.com/SethMichaelLarson'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:23.221>
actor = 'dstufft'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-03.23:12:44.377>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-03-02.22:24:23.132>
creator = 'SethMichaelLarson'
dependencies = []
files = []
hgrepos = []
issue_num = 29704
keywords = []
message_count = 4.0
messages = ['288839', '290327', '290333', '290335']
nosy_count = 2.0
nosy_names = ['yselivanov', 'SethMichaelLarson']
pr_nums = ['405', '415', '416', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29704'
versions = []
```

</p></details>

**Comment by 35e5f348-5b4c-46dc-914b-60f70128bf8f** [comment]
Copied from https://github.com/python/asyncio/issues/484

"""
From https://bugs.python.org/issue23242#msg284930

The following script is used to reproduce the bug:

```py
import asyncio

async def execute():
    process = await asyncio.create_subprocess_exec(
        "timeout", "0.1", "cat", "/dev/urandom", stdout=asyncio.subprocess.PIPE)

    while True:
        data = await process.stdout.read(65536)
        print('read %d bytes' % len(data))
        if data:
            await asyncio.sleep(0.3)
        else:
            break
```


asyncio.get_event_loop().run_until_complete(execute())

will produce following output and terminate with exception:

```pytb
read 65536 bytes
read 65536 bytes
Traceback (most recent call last):
  File "read_subprocess.py", line 18, in <module>
    asyncio.get_event_loop().run_until_complete(execute())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "read_subprocess.py", line 9, in execute
    data = await process.stdout.read(65536)
  File "/usr/lib/python3.6/asyncio/streams.py", line 634, in read
    self._maybe_resume_transport()
  File "/usr/lib/python3.6/asyncio/streams.py", line 402, in _maybe_resume_transport
    self._transport.resume_reading()
  File "/usr/lib/python3.6/asyncio/unix_events.py", line 401, in resume_reading
    self._loop._add_reader(self._fileno, self._read_ready)
AttributeError: 'NoneType' object has no attribute '_add_reader'
```


When the process exits https://github.com/python/asyncio/blob/master/asyncio/unix_events.py#L444 is called which sets this.\_loop = None
Next time read() is called on the pipe the above exception is thrown.
I have tried to fix this issue myself but would sometimes have read terminate too early and miss the last chunks of data.
"""

- BotoX

**Comment by 1st1** [comment]
New changeset f7f024a721d53978d03129e8eb5111d4f74534a9 by Yury Selivanov (Seth M. Larson) in branch '3.5':
bpo-29704: Fix asyncio.SubprocessStreamProtocol closing (#405)
https://github.com/python/cpython/commit/f7f024a721d53978d03129e8eb5111d4f74534a9

**Comment by 1st1** [comment]
New changeset 604faba1db724951ee440337099d111e3ecade49 by Yury Selivanov (Seth M. Larson) in branch '3.6':
bpo-29704: Fix asyncio.SubprocessStreamProtocol closing (#405)
https://github.com/python/cpython/commit/604faba1db724951ee440337099d111e3ecade49

**Comment by 1st1** [comment]
New changeset 481cb70a724687d12553d38a749c16034af68a1e by Yury Selivanov (Seth M. Larson) in branch 'master':
bpo-29704: Fix asyncio.SubprocessStreamProtocol closing (#405)
https://github.com/python/cpython/commit/481cb70a724687d12553d38a749c16034af68a1e
