### ISSUE TITLE
os.path.ismount() always returns false for mount --bind on same filesystem

### ISSUE THREAD

**Issue by 0e0a1a20-73a8-476f-96b7-67fc1c757dc7** [python/cpython#73893]
BPO | [29707](https://bugs.python.org/issue29707)
--- | :---
Nosy | @tiran, @serhiy-storchaka, @eryksun, @ollieparanoid, @csabella, @miss-islington, @R030t1
PRs | <li>python/cpython#11238</li><li>python/cpython#11560</li><li>python/cpython#11560</li><li>python/cpython#11560</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-09.14:02:55.512>
created_at = <Date 2017-03-03.07:09:34.579>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'os.path.ismount() always returns false for mount --bind on same filesystem'
updated_at = <Date 2021-05-03.04:01:51.327>
user = 'https://github.com/ollieparanoid'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-03.04:01:51.327>
actor = 'R0b0t1'
assignee = 'none'
closed = True
closed_date = <Date 2019-04-09.14:02:55.512>
closer = 'christian.heimes'
components = ['Library (Lib)']
creation = <Date 2017-03-03.07:09:34.579>
creator = 'Oliver Smith'
dependencies = []
files = []
hgrepos = []
issue_num = 29707
keywords = ['patch']
message_count = 12.0
messages = ['288863', '301053', '331908', '331921', '331922', '332137', '333652', '333653', '339751', '339752', '361367', '392763']
nosy_count = 9.0
nosy_names = ['christian.heimes', 'serhiy.storchaka', 'eryksun', 'Oliver Smith', 'cheryl.sabella', 'Alex Richman', 'miss-islington', 'Mikko Korkalo', 'R0b0t1']
pr_nums = ['11238', '11560', '11560', '11560']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29707'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 0e0a1a20-73a8-476f-96b7-67fc1c757dc7** [comment]
After mounting a folder to another folder on the same filesystem with mount --bind, os.path.ismount() still returns False on the destination folder (although there is a mountpoint).

A shell script to reproduce this is below.

(Maybe this can be fixed by using /proc/mounts (if available, may not be the case eg. for chroots) for verifying, if the destination folder is really a mountpoint on POSIX/Linux. Although I am not sure how consistent that is through POSIX.)


\---
#!/bin/sh
\# Output:
\# contents of /tmp/destination (should have test.py -\> obviously mounted):
\# test.py
\# os.path.ismount(): False

\# create source and destination folders
source=/tmp/source
destination=/tmp/destination
mkdir -p $source $destination

\# add the python script in the source folder
echo "import os.path" \>\> $source/test.py
echo "print('os.path.ismount(): ' + str(os.path.ismount('$destination')))" \>\> $source/test.py

\# do the mount --bind
sudo mount --bind $source $destination
echo "contents of $destination (should have test.py -\> obviously mounted):"
ls $destination

\# show the python bug
python3 $source/test.py

\# clean up
sudo umount $destination
rm $source/test.py
rm -d $source $destination

**Comment by 239cf45e-7612-4642-805d-169b7b3b6598** [comment]
Can confirm, ran into this issue.  It's because os.path.ismount() works by checking if the path's parent is on a different device (e.g. st_dev is the same for 'path/' and 'path/..'), which obviously it is for a bind mount on the same filesystem.

It is actually documented that this is how it works (https://docs.python.org/2/library/os.path.html#os.path.ismount) but it's more of a passing comment than a warning, and who reads the docs for such an apparently simple function anyway? ;)

Agree that it should be fixed by parsing /proc/mounts instead of the current mess, perhaps using getmntent(3) and friends.
