### ISSUE TITLE
--enable-optimizations does not work with --enable-shared

### ISSUE THREAD

**Issue by 1ab50fdb-b567-44f6-bf87-3f18782bc529** [python/cpython#73898]
BPO | [29712](https://bugs.python.org/issue29712)
--- | :---
Nosy | @pitrou, @stratakis, @halfcoder, @eric957

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-03.15:45:23.118>
labels = ['build']
title = '--enable-optimizations does not work with --enable-shared'
updated_at = <Date 2019-02-15.10:27:51.664>
user = 'https://github.com/halfcoder'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-15.10:27:51.664>
actor = 'Ringding'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2017-03-03.15:45:23.118>
creator = 'halfcoder'
dependencies = []
files = []
hgrepos = []
issue_num = 29712
keywords = []
message_count = 4.0
messages = ['288898', '292927', '313644', '335598']
nosy_count = 5.0
nosy_names = ['pitrou', 'Ringding', 'cstratak', 'halfcoder', 'eric957']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29712'
versions = ['Python 3.6']
```

</p></details>

**Comment by 1ab50fdb-b567-44f6-bf87-3f18782bc529** [comment]
I want to altinstall 3.6 with LTO+PGO optimizations, so:

./configure --enable-shared --enable-optimizations --prefix=$HOME/.local LDFLAGS=-Wl,-rpath=$HOME/.local/lib
make

(./configure arguments refer to issue bpo-27685)

But I get in trouble when running compiled python to generate posix vars:

...
gcc -pthread -shared -Wl,-rpath=/home/halfcoder/.local/lib -fprofile-generate  -Wl,--no-as-needed -o libpython3.so -Wl,-hlibpython3.so libpython3.6m.so
gcc -pthread -Wl,-rpath=/home/halfcoder/.local/lib -fprofile-generate  -Xlinker -export-dynamic -o python [Programs/python.o](https://github.com/python/cpython/blob/main/Programs/python.o) -L. -lpython3.6m -lpthread -ldl  -lutil   -lm
LD_LIBRARY_PATH=/home/halfcoder/.local/src/Python-3.6.0-optmiz ./python -E -S -m sysconfig --generate-posix-vars ;\
if test $? -ne 0 ; then \
        echo "generate-posix-vars failed" ; \
        rm -f ./pybuilddir.txt ; \
        exit 1 ; \
fi
./python: symbol lookup error: ./python: undefined symbol: __gcov_indirect_call_profiler
generate-posix-vars failed
make[2]: *** [pybuilddir.txt] Error 1
make[2]: Leaving directory `/home/halfcoder/.local/src/Python-3.6.0-optmiz'
make[1]: *** [build_all_generate_profile] Error 2
make[1]: Leaving directory `/home/halfcoder/.local/src/Python-3.6.0-optmiz'
make: *** [profile-opt] Error 2

gcc information below:

Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)

**Comment by pitrou** [comment]
For the record, --enable-shared generally produces slower builds than by default.  The slowdown depends on the platform, but it's noticeable on x86-64 and much more on ARM.

**Comment by kumaraditya303** [comment]
The error was because of setting rpath, otherwise main branch can be compiled successfully.
