### ISSUE TITLE
String changes whether or not '\x81' is present

### ISSUE THREAD

**Issue by 50bc5976-a816-4461-9378-e65b2bc56bc6** [python/cpython#73899]
BPO | [29713](https://bugs.python.org/issue29713)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-03.17:17:36.352>
created_at = <Date 2017-03-03.16:04:43.975>
labels = ['type-bug']
title = "String changes whether or not '\\x81' is present"
updated_at = <Date 2017-03-03.17:17:36.338>
user = 'https://bugs.python.org/dagnam'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-03.17:17:36.338>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-03.17:17:36.352>
closer = 'r.david.murray'
components = []
creation = <Date 2017-03-03.16:04:43.975>
creator = 'dagnam'
dependencies = []
files = []
hgrepos = []
issue_num = 29713
keywords = []
message_count = 2.0
messages = ['288900', '288903']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'dagnam']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29713'
versions = ['Python 2.7']
```

</p></details>

**Comment by 50bc5976-a816-4461-9378-e65b2bc56bc6** [comment]
print '\\xa3\\xb5\\xdd\\xf7\\xa9\\xa7\\xab\\xd8\\xef\\xc7\\xac\\xf4\\xfb\\xb7'
#gives
£µÝ÷©§«ØïÇ¬ôû·

print '\\xa3\\xb5\\xdd\\xf7\\xa9\\xa7\\xab\\xd8\\xef\\xc7\\xac\\xf4\\xfb\\xb7\\x81'
#gives 
ﾣﾵÝ÷ﾩﾧﾫØïǬôûﾷﾁ

print '\\x81\\xa3'        print '\\xa3'
ﾁﾣ                      £

**Comment by bitdancer** [comment]
It works fine for me.  If I write the data to a file (using print) and look at it with vi, I see your expected string with \<81\> on the end.  It also works fine in my console (which otherwise produces mostly unknown character glyphs; I'm using a utf8 locale) if I use unicode, or python3.

So, the problem is not with python, it must be your terminal emulator or whatever else it is you are using to inspect the results.
