### ISSUE TITLE
socket.gethostbyname, getaddrinfo etc broken on MacOS 10.12

### ISSUE THREAD

**Issue by 5be04445-60f1-4361-86a4-a7c19877ceb8** [python/cpython#73891]
BPO | [29705](https://bugs.python.org/issue29705)
--- | :---
Nosy | @ned-deily, @ssbarnea

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-03.02:45:56.114>
created_at = <Date 2017-03-02.23:36:55.785>
labels = ['type-bug', 'library']
title = 'socket.gethostbyname, getaddrinfo etc broken on MacOS 10.12'
updated_at = <Date 2018-11-04.17:29:22.438>
user = 'https://bugs.python.org/JamesCrowther'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-04.17:29:22.438>
actor = 'ssbarnea'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-03.02:45:56.114>
closer = 'ned.deily'
components = ['Library (Lib)']
creation = <Date 2017-03-02.23:36:55.785>
creator = 'James Crowther'
dependencies = []
files = []
hgrepos = []
issue_num = 29705
keywords = []
message_count = 8.0
messages = ['288840', '288842', '288843', '288844', '288845', '288846', '288847', '329242']
nosy_count = 3.0
nosy_names = ['ned.deily', 'ssbarnea', 'James Crowther']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29705'
versions = ['Python 3.5']
```

</p></details>

**Comment by 5be04445-60f1-4361-86a4-a7c19877ceb8** [comment]
Currently I can't use socket to resolve host names to IP addresses. This is something critical to mine as well as other applications that run over networks. 
When I attempt to do the following:

```py
import socket
socket.getaddrinfo(hostname, None)
```


or 

```py
socket.gethostbyname(hostname)
```


I get 

socket.gaierror: [Errno 8] nodename nor servename provided, or not known.

This works perfectly on both linux kubuntu 16.0. and windows 7,10. 

Seems that the introduction of Yosemite might be the point at which this broke by doing a simple google search for "macos socket.gethostbyname gaierror".

**Comment by ned-deily** [comment]
What value are you using for hostname?

**Comment by 5be04445-60f1-4361-86a4-a7c19877ceb8** [comment]
Hi Ned, 
	Doesn’t seem to matter, I can try my local host name given by;

```py
socket.gethostname()
```


or I can try another host on the network, same result. 

If I do the exact same operation using the same python version on windows or linux, then I get the expected result from gethostbyname which is the ip address of the host. Also on macOS 10.6.8 this still works, using the same version of python.

Happy to give more details if you need.

James

**Comment by ned-deily** [comment]
Sorry, I can't reproduce that behavior with my macOS 10.12, 10.11, or 10.10 systems if the hostname is a valid string including "localhost".  If the string is empty or hostname is None, then I see Errno 8.

```pycon
$ /usr/local/bin/python3.6
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> hostname = 'python.org'
>>> socket.getaddrinfo(hostname, None)
[(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('23.253.135.79', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('23.253.135.79', 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('2001:4802:7901::e60a:1375:0:6', 0, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2001:4802:7901::e60a:1375:0:6', 0, 0, 0))]
>>> hostname = "localhost"
>>> socket.getaddrinfo(hostname, None)
[(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
>>> hostname = ""
>>> socket.getaddrinfo(hostname, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
```


Perhaps there is something different about your hostname configuration on your Mac?  macOS has some unusual ways of configuring the hostname resolutions.  I don't have time at the moment to investigate further.  But Python's socket module interfaces tend to be very thin wrappers around the underlying OS provided APIs.  Perhaps you could test with a small C program that does the equivalent.

**Comment by 5be04445-60f1-4361-86a4-a7c19877ceb8** [comment]
Hi Ned, 
	Currently running 10.12.3. and output is as follows

```pycon
Jamess-MacBook-pro:crowdrender_repository jamesmac$ python3.5
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> hostname = socket.gethostname()
>>> socket.getaddrinfo(hostname, None)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 8] nodename nor servname provided, or not known
>>> 
```


This is a commonly prescribed method of resolving the ip address of your own machine on a LAN, also if I try another machines hostname which is on the local network, I get the same result. 

As for the experiments you tried, these do work, but that is not what I want to use the socket library for, I want to query the IP address of hosts on the LAN, localhost is no use to me, its just the loop back address.

I have a windows machine on my network and its hostname is James-PC, if i do

```py
socket.getaddrinfo(“James-PC”)
```


I get the same error. This works if I reboot the mac (the same one that is having the issues) into linux and run the exact same command. I get the expected output from getaddrinfo. 

So, how come this approach doesn’t work on my mac? Also why are others having the same issue with Yosemite and sierra, this is not just me that is reporting this odd behaviour too. I’ve seen it in other forums.

Kind Regards

James

```pytb
> On 3 Mar 2017, at 11:41 am, Ned Deily <report@bugs.python.org> wrote:
> 
> 
> Ned Deily added the comment:
> 
> Sorry, I can't reproduce that behavior with my macOS 10.12, 10.11, or 10.10 systems if the hostname is a valid string including "localhost".  If the string is empty or hostname is None, then I see Errno 8.
> 
> $ /usr/local/bin/python3.6
> Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
> [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
> Type "help", "copyright", "credits" or "license" for more information.
>>>> import socket
>>>> hostname = 'python.org'
>>>> socket.getaddrinfo(hostname, None)
> [(<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('23.253.135.79', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('23.253.135.79', 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('2001:4802:7901::e60a:1375:0:6', 0, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('2001:4802:7901::e60a:1375:0:6', 0, 0, 0))]
>>>> hostname = "localhost"
>>>> socket.getaddrinfo(hostname, None)
> [(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('::1', 0, 0, 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('127.0.0.1', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('127.0.0.1', 0))]
>>>> hostname = ""
>>>> socket.getaddrinfo(hostname, None)
> Traceback (most recent call last):
>  File "<stdin>", line 1, in <module>
>  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/socket.py", line 743, in getaddrinfo
>    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
> socket.gaierror: [Errno 8] nodename nor servname provided, or not known
> 
> Perhaps there is something different about your hostname configuration on your Mac?  macOS has some unusual ways of configuring the hostname resolutions.  I don't have time at the moment to investigate further.  But Python's socket module interfaces tend to be very thin wrappers around the underlying OS provided APIs.  Perhaps you could test with a small C program that does the equivalent.
> 
> 
```
----------
> 
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29705\>
> _______________________________________

**Comment by ned-deily** [comment]
James, I'm sorry I didn't show it but using socket.gethostname() as the source of hostname works just fine, too.

```py
import socket
>>> hostname = socket.gethostname()
>>> hostname
'harj.local'
>>> socket.getaddrinfo(hostname, None)
[(<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('fe80::8d8:1de3:dfa:e34c%en1', 0, 0, 5)), (<AddressFamily.AF_INET6: 30>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('fe80::8d8:1de3:dfa:e34c%en1', 0, 0, 5)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_DGRAM: 2>, 17, '', ('10.0.1.7', 0)), (<AddressFamily.AF_INET: 2>, <SocketKind.SOCK_STREAM: 1>, 6, '', ('10.0.1.7', 0))]
```


I don't know what to tell you other than the behavior you are seeing is almost certainly not a Python issue.  There are many other ways to explore host names, like using the "host" command line utility or "netstat".  But that is all beyond the scope of this bug tracker.  If you need more assistance, perhaps ask on one of the StackExchange forums or Apple lists.  I'm going to close this issue; if you are able to isolate what appears to be a Python issue here, please feel free to re-open this.  Good luck!

**Comment by 5be04445-60f1-4361-86a4-a7c19877ceb8** [comment]
Hi Ned, 
	Thats ok, thanks! I’m going to try it on another machine, its really strange, I’m wondering what I might have done on my mac to cause it to flake out like this. Will do some more testing with other macs running 10.12 and see if they have the same behaviour, by the way, thanks for running that last test as it shows that this call is actually working on some systems. I really need to know the reason why its not working on mine, I have about 120 users and need to be sure that they’re not going to have our next build break if we rely on this call. 

Thanks :D

James
