### ISSUE TITLE
Short-circuiting not only on False and True

### ISSUE THREAD

**Issue by 89042997-fe19-49d2-aba2-a4861a6d999e** [python/cpython#73895]
BPO | [29709](https://bugs.python.org/issue29709)
--- | :---
Nosy | @rhettinger, @Mariatta, @pochmann
PRs | <li>python/cpython#433</li><li>python/cpython#436</li><li>python/cpython#437</li><li>python/cpython#438</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-03-03.21:36:46.712>
created_at = <Date 2017-03-03.12:11:40.111>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Short-circuiting not only on False and True'
updated_at = <Date 2017-03-24.23:02:34.970>
user = 'https://github.com/pochmann'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.23:02:34.970>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-03-03.21:36:46.712>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-03-03.12:11:40.111>
creator = 'Stefan Pochmann'
dependencies = []
files = []
hgrepos = []
issue_num = 29709
keywords = ['easy']
message_count = 8.0
messages = ['288881', '288908', '288909', '288934', '290320', '290321', '290322', '290324']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'Mariatta', 'Stefan Pochmann']
pr_nums = ['433', '436', '437', '438']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29709'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 89042997-fe19-49d2-aba2-a4861a6d999e** [comment]
The notes at https://docs.python.org/3/library/stdtypes.html#boolean-operations-and-or-not say that `or` "only evaluates the second argument if the first one is False" and that `and` "only evaluates the second argument if the first one is True". Should say "false" and "true" instead of "False" and "True".

**Comment by rhettinger** [comment]
Mariatta, would you like to fix this one (False -\> false and True -\> true).

**Comment by Mariatta** [comment]
Thanks, Raymond. I made the PR :)
I can backport to 2.7, 3.5, and 3.6 once it's accepted.

**Comment by Mariatta** [comment]
Committed and backported to 2.7, 3.5, and 3.6.
Thanks all :)

**Comment by Mariatta** [comment]
New changeset fc59e5c7073af4d9255644a83933dd5b14c7f722 by Mariatta in branch '2.7':
bpo-29709: Improve Boolean Operations documentation (#433) (#438)
https://github.com/python/cpython/commit/fc59e5c7073af4d9255644a83933dd5b14c7f722

**Comment by Mariatta** [comment]
New changeset 6e965d9e78b278f2f720a932e7b149cb7d88bd72 by Mariatta in branch '3.5':
bpo-29709: Improve Boolean Operations documentation (#433) (#436)
https://github.com/python/cpython/commit/6e965d9e78b278f2f720a932e7b149cb7d88bd72

**Comment by Mariatta** [comment]
New changeset 1936ba93c900d47d0c8c915184ac2fa7773c952e by Mariatta in branch '3.6':
bpo-29709: Improve Boolean Operations documentation (#433) (#437)
https://github.com/python/cpython/commit/1936ba93c900d47d0c8c915184ac2fa7773c952e

**Comment by Mariatta** [comment]
New changeset 8eb531d9db0861e14222445fcaebe1a373bba170 by Mariatta in branch 'master':
bpo-29709: Improve Boolean Operations documentation (#433)
https://github.com/python/cpython/commit/8eb531d9db0861e14222445fcaebe1a373bba170
