### ISSUE TITLE
heapq.merge docs are misleading with the "reversed" flag

### ISSUE THREAD

**Issue by 142dd71a-3b78-4356-8a97-570a83d9a4a0** [python/cpython#73908]
BPO | [29722](https://bugs.python.org/issue29722)
--- | :---
Nosy | @rhettinger, @AdamNiederer
PRs | <li>python/cpython#300</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-03-11.18:20:34.813>
created_at = <Date 2017-03-05.03:26:38.023>
labels = ['type-bug', '3.7', 'docs']
title = 'heapq.merge docs are misleading with the "reversed" flag'
updated_at = <Date 2017-03-11.18:20:34.812>
user = 'https://github.com/AdamNiederer'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-11.18:20:34.812>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-03-11.18:20:34.813>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-03-05.03:26:38.023>
creator = 'adamniederer'
dependencies = []
files = []
hgrepos = []
issue_num = 29722
keywords = []
message_count = 2.0
messages = ['288997', '289449']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'adamniederer']
pr_nums = ['300']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29722'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 142dd71a-3b78-4356-8a97-570a83d9a4a0** [comment]
The docs for heapq.merge are a little misleading. Iterables passed into heapq.merge with the reversed flag set to True must be sorted from largest to smallest to achieve the desired sorting effect, but the paragraph describing the function in the general case states that they should be sorted from smallest to largest.

**Comment by rhettinger** [comment]
The PR was applied to 3.7.  I don't think it is worth backing.
