### ISSUE TITLE
can't interpolate byte string with \x00 before replacement identifier

### ISSUE THREAD

**Issue by ad40ad1e-1791-42cc-b881-fe46275e9e39** [python/cpython#73900]
BPO | [29714](https://bugs.python.org/issue29714)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#499</li><li>python/cpython#504</li><li>python/cpython#703</li><li>python/cpython#552</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zhangyangyu'
closed_at = <Date 2017-03-06.10:18:22.945>
created_at = <Date 2017-03-03.19:05:28.034>
labels = ['interpreter-core', 'type-bug', '3.7']
title = "can't interpolate byte string with \\x00 before replacement identifier"
updated_at = <Date 2017-03-31.16:36:26.220>
user = 'https://bugs.python.org/NickHuber'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-31.16:36:26.220>
actor = 'dstufft'
assignee = 'xiang.zhang'
closed = True
closed_date = <Date 2017-03-06.10:18:22.945>
closer = 'xiang.zhang'
components = ['Interpreter Core']
creation = <Date 2017-03-03.19:05:28.034>
creator = 'Nick Huber'
dependencies = []
files = []
hgrepos = []
issue_num = 29714
keywords = ['3.6regression']
message_count = 10.0
messages = ['288912', '288916', '289065', '289085', '289086', '289087', '289092', '289106', '290290', '290291']
nosy_count = 4.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'xiang.zhang', 'Nick Huber']
pr_nums = ['499', '504', '703', '552']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29714'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ad40ad1e-1791-42cc-b881-fe46275e9e39** [comment]
```pycon
Python 3.6.0 (default, Mar  3 2017, 00:15:36) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'a\x00%i' % 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: not all arguments converted during bytes formatting
>>> b'a%i' % 1
b'a1'
>>> b'a%i\x00' % 1
b'a1\x00'
```



On python3.5, this works in all the scenarios

```pycon
Python 3.5.1 (default, Jan 14 2017, 03:58:20) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> b'a\x00%i' % 1
b'a\x001'
>>> b'a%i' % 1
b'a1'
>>> b'a%i\x00' % 1
b'a1\x00'
```

**Comment by serhiy-storchaka** [comment]
Could this be due to using \_PyBytesWriter?

**Comment by zhangyangyu** [comment]
The problem is now \_PyBytes_FormatEx uses strchr to sniff %. It should use memchr instead.

**Comment by zhangyangyu** [comment]
Thanks for the report, Nick!

**Comment by vstinner** [comment]
I confirm that I introduced the regression with the commit fa7762ec066aa3632a25b6a52bb7597b8f17c2f3: "Issue bpo-25349: Optimize bytes % args using the new private \_PyBytesWriter API". Sorry about that, I always forget that str*() functions should not be used in Python since we support embedded null bytes :-/ It seems like only Python 3.6.0 release is affected.

"git tag --contains fa7762ec066aa3632a25b6a52bb7597b8f17c2f3" also returns v3.5.2, but I don't understand since I only pushed my change to the 3.6 branch...

**Comment by vstinner** [comment]
Oh, and thank you for adding new unit tests ;-) Do we need similar unit tests for str%args and str.format()?

**Comment by zhangyangyu** [comment]
I think no. String is not affected now and its code uses related macros so I don't think it could suffer possible regression.

**Comment by vstinner** [comment]
Xiang Zhang added the comment:
> I think no. String is not affected now and its code uses related macros so I don't think it could suffer possible regression.

Regressions are not something "expected", shit happens, all the time.
Unexpected corner cases are common :-)

**Comment by zhangyangyu** [comment]
New changeset df6d7b406f3d1b2e4e2014751bfa25574c4df222 by Xiang Zhang in branch '3.6':
[3.6] bpo-29714: Fix a regression that bytes format may fail when containing zero bytes inside. (GH-504)
https://github.com/python/cpython/commit/df6d7b406f3d1b2e4e2014751bfa25574c4df222

**Comment by zhangyangyu** [comment]
New changeset b76ad5121e2cfa89d6476d700cbcb65b7ffc39ac by Xiang Zhang in branch 'master':
bpo-29714:  Fix a regression that bytes format may fail when containing zero bytes inside. (GH-499)
https://github.com/python/cpython/commit/b76ad5121e2cfa89d6476d700cbcb65b7ffc39ac
