### ISSUE TITLE
potential silent truncation in PyLong_AsVoidPtr

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#73906]
BPO | [29720](https://bugs.python.org/issue29720)
--- | :---
Nosy | @mdickinson, @vstinner, @serhiy-storchaka, @orenmn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-27.12:15:25.605>
created_at = <Date 2017-03-04.16:12:04.664>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'potential silent truncation in PyLong_AsVoidPtr'
updated_at = <Date 2017-03-27.12:15:25.604>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.12:15:25.604>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-27.12:15:25.605>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-03-04.16:12:04.664>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 29720
keywords = []
message_count = 7.0
messages = ['288984', '290487', '290586', '290593', '290594', '290599', '290602']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'vstinner', 'serhiy.storchaka', 'Oren Milman']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29720'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
I am not sure whether such a platform exists, but on a platform where
SIZEOF_VOID_P \< SIZEOF_LONG, PyLong_AsVoidPtr (which is in
[Objects/longobject.c](https://github.com/python/cpython/blob/main/Objects/longobject.c)) is:
    long x;
    if (PyLong_Check(vv) && \_PyLong_Sign(vv) \< 0)
        x = PyLong_AsLong(vv);
    else
        x = PyLong_AsUnsignedLong(vv);
    if (x == -1 && PyErr_Occurred())
        return NULL;
    return (void \*)x;
Thus, for example, 'PyLong_AsVoidPtr(PyLong_FromUnsignedLong(ULONG_MAX))'
would silently truncate ULONG_MAX, and return without an error.

An easy fix would be (mainly) to add to PyLong_AsVoidPtr
'Py_BUILD_ASSERT(SIZEOF_LONG \<= SIZEOF_VOID_P);', but I am not sure we can
make that assumption.

Note that a compile time error is already raised:
    - by [Objects/longobject.h](https://github.com/python/cpython/blob/main/Objects/longobject.h), in case SIZEOF_VOID_P is different from
      SIZEOF_INT, SIZEOF_LONG and SIZEOF_LONG_LONG
    - by [Modules/_multiprocessing/multiprocessing.h](https://github.com/python/cpython/blob/main/Modules/_multiprocessing/multiprocessing.h), in case SIZEOF_VOID_P is
      different from SIZEOF_LONG and SIZEOF_LONG_LONG

**Comment by serhiy-storchaka** [comment]
I don't think there is a bug. There are several ways to get the integer representation of the pointer. PyLong_FromVoidPtr() is the most straightforward. From Python side id() uses it. printf("%p") is a way of getting string representation of the pointer, that string can be converted to integer. This way is used in object.\_\_repr__(). Usually %p formats the pointer as hexadecimal, but the sign is not defined. Therefore when the pointer is converted to the integer it can be interpreted as either signed or unsigned integer. PyLong_AsVoidPtr() should accept both representations.

**Comment by vstinner** [comment]
"I am not sure whether such a platform exists, but on a platform where SIZEOF_VOID_P \< SIZEOF_LONG, PyLong_AsVoidPtr ..."

I'm suite sure that every C function of CPython breaks if this assumption becomes wrong :-) Such platform doesn't exist.

You can add the build assertion if it makes you more confortable ;-)

**Comment by serhiy-storchaka** [comment]
> I'm suite sure that every C function of CPython breaks if this assumption becomes wrong :-) Such platform doesn't exist.

Did you meant 64-bit Windows? ;-)

**Comment by vstinner** [comment]
> Did you meant 64-bit Windows? ;-)

On Windows 64-bit, sizeof(void*) \> sizeof(long), not the opposite.

**Comment by serhiy-storchaka** [comment]
Ah, you are right. I don't know whether Python supports such platform after dropping support of DOS.

But in any case I don't see any issue here.

Oren will be not active until August, so we should make the decision about closing the issue or changing the code without him.

**Comment by vstinner** [comment]
I closed the issue.

@Oren: Please reopen the issue with a pull request if you consider that the assertion is worth it.
