### ISSUE TITLE
collections.abc.Reversible doesn't fully support the reversing protocol

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73913]
BPO | [29727](https://bugs.python.org/issue29727)
--- | :---
Nosy | @gvanrossum, @rhettinger, @serhiy-storchaka, @ilevkivskyi, @pablogsal
PRs | <li>python/cpython#21338</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ilevkivskyi'
closed_at = <Date 2020-07-05.21:43:40.098>
created_at = <Date 2017-03-05.18:49:23.099>
labels = ['3.7', 'type-bug', 'library']
title = "collections.abc.Reversible doesn't fully support the reversing protocol"
updated_at = <Date 2020-07-05.21:43:40.097>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-05.21:43:40.097>
actor = 'pablogsal'
assignee = 'levkivskyi'
closed = True
closed_date = <Date 2020-07-05.21:43:40.098>
closer = 'pablogsal'
components = ['Library (Lib)']
creation = <Date 2017-03-05.18:49:23.099>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29727
keywords = ['patch']
message_count = 5.0
messages = ['289039', '289040', '289043', '292265', '373050']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'rhettinger', 'stutzbach', 'serhiy.storchaka', 'levkivskyi', 'pablogsal']
pr_nums = ['21338']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29727'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
collections.abc.Reversible doesn't work with types that are supported by reserved() but neither have the \_\_reversed__ method nor are explicitly registered as collections.abc.Sequence. For example:

```pycon
>>> issubclass(array.array, collections.abc.Reversible)
False 
```


The reversing protocol as well as the iterating protocol is supported not only by special method, but implicitly if the class has implemented \_\_getitem__ and \_\_len__ methods.

```pycon
>>> class Counter(int):
...   def __getitem__(s, i): return i
...   def __len__(s): return s
... 
>>> list(reversed(Counter(10)))
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]
>>> issubclass(Counter, collections.abc.Reversible)
False
```


typing.Reversible starves from the same bug. See https://github.com/python/typing/issues/170.

**Comment by rhettinger** [comment]
I don't think this is a bug.  The purpose collections.abc.Reversible is to recognize type where the behavior has been guaranteed, not to recognize all types where it happens to work.

Part of the original reason for introducing ABCs in the first place was that in general there is no reliable way to detect whether a class defining \_\_getitem__ is a sequence or a mapping.

A creator of such a class either needs to subclass from Sequence or register as a Sequence.  The fact that reversed(Counter(10)) happens to work is no more interesting that the fact Counter(10)[5] happens to work eventhough isinstance(Counter, Sequence) returns False.

**Comment by rhettinger** [comment]
One other thought:  array.array() object should probably be registered so that it recognizable as a Sequence and as Reversible.

**Comment by gvanrossum** [comment]
I'm with Raymond.

I propose to register array.array() in all the appropriate places and then close this bug as a won't fix.

The typing issue might eventually be resolved via PEP-544 (if accepted), or not -- the"fallback protocols" based on \_\_getitem__ and \_\_len__ seem to be a complicating special case that we may want to put off.
