### ISSUE TITLE
Ability to filter warnings to print current stack

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#73917]
BPO | [29731](https://bugs.python.org/issue29731)
--- | :---
Nosy | @pitrou, @vstinner, @tiran, @Carreau
PRs | <li>python/cpython#498</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-06.05:59:48.725>
labels = ['3.8', 'type-feature', 'library']
title = 'Ability to filter warnings to print current stack'
updated_at = <Date 2019-05-28.23:37:17.281>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-28.23:37:17.281>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-03-06.05:59:48.725>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 29731
keywords = []
message_count = 1.0
messages = ['289066']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'christian.heimes', 'mbussonn']
pr_nums = ['498']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29731'
versions = ['Python 3.8']
```

</p></details>

**Comment by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [comment]
The warning module is extremely useful, especially the ability to change various level of verbosity and filter by multiple criteria. 

It is though sometime hard to pinpoint why a warning was triggered, or actually what triggered a warning. This is often due to the fact that libraries don't set the `stacklevel=...`  correctly, that it is hard to get right (like at import time), or because warnings get triggered by complex, not obvious codepaths.

One workaround is to switch from `always`/`once` to "error" to raise exceptions, but that can be quite troublesome in production, if other warnings are encountered in the meantime.


Would it be accepted to add a warning filter type "stack" (or whatever name please you ...) that would not only print the current warning,  but the stack leading to it. That is to say output almost identical as "error" but not actually raising ?

Assuming above is reasonable, I have a working patch (both in the c and py implementation of warnings), though it can't seem to find how respect the `stacklevel=...` parameter unless `warn_explicit` is changed to allow an additional `frame` argument. Would adding this field be acceptable ?
Or arguably, if one is interested in the stack, ignoring the stacklevel may make sens as one may want to explore the full reason of the warning (ie its source that may be hidden by stacklevel=... ) , and not only what triggered it.

**Comment by iritkatriel** [comment]
The OP closed the PR, so I'm closing the issue as well.
