### ISSUE TITLE
Expose TCP_NOTSENT_LOWAT

### ISSUE THREAD

**Issue by njsmith** [python/cpython#73914]
BPO | [29728](https://bugs.python.org/issue29728)
--- | :---
Nosy | @njsmith, @Mariatta
PRs | <li>python/cpython#477</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-23.03:58:10.536>
created_at = <Date 2017-03-05.19:07:58.014>
labels = ['3.7', 'library']
title = 'Expose TCP_NOTSENT_LOWAT'
updated_at = <Date 2017-03-24.16:33:43.969>
user = 'https://github.com/njsmith'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.16:33:43.969>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-23.03:58:10.536>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-03-05.19:07:58.014>
creator = 'njs'
dependencies = []
files = []
hgrepos = []
issue_num = 29728
keywords = []
message_count = 3.0
messages = ['289041', '290021', '290097']
nosy_count = 2.0
nosy_names = ['njs', 'Mariatta']
pr_nums = ['477']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29728'
versions = ['Python 3.7']
```

</p></details>

**Comment by njsmith** [comment]
https://github.com/python/cpython/pull/477

**Comment by Mariatta** [comment]
Thanks, Nathaniel. I merged your patch :)

**Comment by Mariatta** [comment]
New changeset 1e2147b9d75a64df370a9393c2b5b9d170dc0afd by Mariatta (Nathaniel J. Smith) in branch 'master':
bpo-29728: Provide socket.TCP_NOTSENT_LOWAT (#477)
https://github.com/python/cpython/commit/1e2147b9d75a64df370a9393c2b5b9d170dc0afd
