### ISSUE TITLE
test_xmlrpc raises DeprecationWarnings

### ISSUE THREAD

**Issue by 170ffa89-f0d3-4127-9de7-e20f1aa88525** [python/cpython#73912]
BPO | [29726](https://bugs.python.org/issue29726)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @okay19, @petr-motejlek
PRs | <li>python/cpython#481</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-03-15.11:14:23.635>
created_at = <Date 2017-03-05.17:15:54.455>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_xmlrpc raises DeprecationWarnings'
updated_at = <Date 2017-03-15.11:14:23.584>
user = 'https://github.com/okay19'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-15.11:14:23.584>
actor = 'berker.peksag'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-03-15.11:14:23.635>
closer = 'berker.peksag'
components = ['Tests']
creation = <Date 2017-03-05.17:15:54.455>
creator = 'dillon.brock'
dependencies = []
files = []
hgrepos = []
issue_num = 29726
keywords = []
message_count = 4.0
messages = ['289026', '289027', '289050', '289667']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'dillon.brock', 'petr@motejlek.net']
pr_nums = ['481']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29726'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 170ffa89-f0d3-4127-9de7-e20f1aa88525** [comment]
In 3 unit tests, test_xmlrpc calls assertRaises(Exception, expectedRegex='method'), causing DeprecationWarnings. These calls should be replaced with assertRaisesRegex(Exception, 'method').

0:20:56 [378/404] test_xmlrpc
127.0.0.1 - - [05/Mar/2017 11:53:45] "POST / HTTP/1.1" 200 -
127.0.0.1 - - [05/Mar/2017 11:53:45] "POST / HTTP/1.1" 200 -
/home/dillon/src/cpython/Lib/test/test_xmlrpc.py:430: DeprecationWarning: 'expected_regex' is an invalid keyword argument for this function
  with self.assertRaises(Exception, expected_regex='method'):
/home/dillon/src/cpython/Lib/test/test_xmlrpc.py:423: DeprecationWarning: 'expected_regex' is an invalid keyword argument for this function
  with self.assertRaises(Exception, expected_regex='method'):
/home/dillon/src/cpython/Lib/test/test_xmlrpc.py:415: DeprecationWarning: 'expected_regex' is an invalid keyword argument for this function
  with self.assertRaises(Exception, expected_regex='method'):

**Comment by serhiy-storchaka** [comment]
Thank you Dillon! Could you backport your changes to 3.6 and 3.5?

**Comment by 170ffa89-f0d3-4127-9de7-e20f1aa88525** [comment]
The cherry-pick is causing a merge conflict because 3.6 and 3.5 do not include the SimpleXMLRPCDispatcherTestCase that this fix modifies. Should I backport that entire test case as well as the fix?

**Comment by berkerpeksag** [comment]
Thanks, Dillon! I went ahead and backported [PR 481](https://github.com/python/cpython/pull/481) to 3.5 and 3.6 branches.
