### ISSUE TITLE
unoptimal calls to PyNumber_Check

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#73916]
BPO | [29730](https://bugs.python.org/issue29730)
--- | :---
Nosy | @rhettinger, @mdickinson, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#622</li><li>python/cpython#650</li>
Files | <li>[patchVer2.diff](https://bugs.python.org/file46721/patchVer2.diff "Uploaded as text/plain at 2017-03-12.16:29:57 by @orenmn"): patch2 diff file</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-03-12.22:39:00.069>
created_at = <Date 2017-03-05.23:11:18.826>
labels = ['type-feature', '3.7', 'expert-IO']
title = 'unoptimal calls to PyNumber_Check'
updated_at = <Date 2017-03-24.22:21:13.190>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:21:13.190>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-03-12.22:39:00.069>
closer = 'serhiy.storchaka'
components = ['IO']
creation = <Date 2017-03-05.23:11:18.826>
creator = 'Oren Milman'
dependencies = []
files = ['46721']
hgrepos = []
issue_num = 29730
keywords = ['patch']
message_count = 12.0
messages = ['289048', '289051', '289458', '289483', '289488', '289489', '289502', '289506', '289514', '289516', '289532', '290191']
nosy_count = 4.0
nosy_names = ['rhettinger', 'mark.dickinson', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['622', '650']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29730'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
\------------ current state \------------
```c
if (PyNumber_Check(obj)) {
    someVar = PyNumber_AsSsize_t(obj, SomeError);
    if (someVar == -1 && PyErr_Occurred()) {
        return errVal;
    }
}
else {
    PyErr_Format(PyExc_TypeError,
                 "integer argument expected, got '%.200s'",
                 Py_TYPE(obj)->tp_name);
    return errVal;
}
```


Something similar to this happens in:
    - [Modules/mmapmodule.c](https://github.com/python/cpython/blob/main/Modules/mmapmodule.c) in mmap_convert_ssize_t
    - [Modules/_io/_iomodule.c](https://github.com/python/cpython/blob/main/Modules/_io/_iomodule.c) in \_PyIO_ConvertSsize_t
    - [Modules/_io/stringio.c](https://github.com/python/cpython/blob/main/Modules/_io/stringio.c) in:
        * \_io_StringIO_read_impl
        * \_io_StringIO_readline_impl
        * \_io_StringIO_truncate_impl

(Moreover, in:
    - [Objects/bytes_methods.c](https://github.com/python/cpython/blob/main/Objects/bytes_methods.c) in parse_args_finds_byte
    - [Objects/exceptions.c](https://github.com/python/cpython/blob/main/Objects/exceptions.c) in oserror_init
PyNumber_AsSsize_t is called only if PyNumber_Check returns true.)

Note that:
    - PyNumber_Check checks whether nb_int != NULL or nb_float != NULL.
    - PyNumber_AsSsize_t calls PyNumber_Index, which, before calling
      nb_index, raises a TypeError (with a similar error message) in case
      nb_index == NULL.
    - The docs say '... when \_\_index__() is defined \_\_int__() should also be
      defined ...'.
So the behavior with and without the call to PyNumber_Check is quite the same.
The only potential advantage of calling PyNumber_Check is skipping the call to
PyNumber_AsSsize_t.
But PyNumber_AsSsize_t would be called also in case
nb_index == NULL and (nb_int != NULL or nb_float != NULL).
Thus, the only case in which the call to PyNumber_Check might be useful, is
when nb_int == nb_float == nb_index == NULL.


\------------ proposed changes \------------
Either remove each of these calls to PyNumber_Check, or at least replace it
with a call to PyIndex_Check, which checks whether nb_index != NULL, and thus
would be more useful than PyNumber_Check.

Note that such a change shouldn't affect the behavior, except for a slightly
different wording of the error message in case a TypeError is raised.

**Comment by rhettinger** [comment]
+1 for removing each of these calls to PyNumber_Check.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
after some closer examination, ISTM that in [Objects/exceptions.c](https://github.com/python/cpython/blob/main/Objects/exceptions.c), we can't
remove PyNumber_Check to optimize or simplify the code, as the argument
'filename' can be either an integer type (only in case the error is a
BlockingIOError), or quite anything else, except for None.

We could replace PyNumber_Check(filename) with PyIndex_Check(filename), but
this would change the behavior of BlockingIOError.
IMHO, this isn't that important, and thus we should leave the code in
[Objects/exceptions.c](https://github.com/python/cpython/blob/main/Objects/exceptions.c) as is.

anyway, I would soon create a pull request to remove all other
aforementioned calls to PyNumber_Check.

**Comment by serhiy-storchaka** [comment]
I think it would be better to replace PyNumber_Check() with PyIndex_Check() and change error messages to more specific. In IO related functions the accepted values are integers and None. In bytes/bytearray methods -- integers and bytes-like objects.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
"In bytes/bytearray methods -- integers and bytes-like objects."
(I guess you refer to parse_args_finds_byte (in [Objects/bytes_methods.c](https://github.com/python/cpython/blob/main/Objects/bytes_methods.c)))
so you suggest that in case (!PyIndex_Check(tmp_subobj)), we also check whether
(PyByteArray_Check(tmp_subobj) or PyBytes_Check(tmp_subobj)), and raise an
error if needed?

anyway, you and Raymond suggest different things. how do we proceed?

**Comment by serhiy-storchaka** [comment]
The call of PyNumber_Check() is redundant if we don't bother about error message. But if we want to have accurate error message we should check types before converting.

In parse_args_finds_byte we should check rather PyObject_CheckBuffer() (and maybe PyBytes_Check() for fast path if this makes sense). Perhaps some methods need to check also PyTuple_Check().

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
"Perhaps some methods need to check also PyTuple_Check()."
which methods?

anyway, a new patch diff file is attached, according to your other seggustions,
Serhiy.
(I ran the test module, and some tests of my own, and it seems that the patch
doesn't break anything.)

**Comment by serhiy-storchaka** [comment]
Please open a PR for review.

Checking PyTuple_Check() is needed if this code is used in startswith() and endswith().

"integer argument or None expected" -- I'm not sure this wording is correct enough. What wording is used in other similar code? I'm sure there other functions that accept int or None.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
I am sorry, but I guess I am missing something about startswith() and
endswith().
ISTM that PyTuple_Check() is already called by unicode_startswith,
unicode_endswith and \_Py_bytes_tailmatch, which already raise a TypeError
with an appropriate error message
(e.g. "%s first arg must be bytes or a tuple of bytes, not %s").


```c
I searched the codebase, and found that in most places, if PyIndex_Check(obj)
is true, then obj is described as 'integer' in error messages. rarely, obj
would be described as 'int'.
I found only two relevant TypeError messages of functions that accept an
integer type or None (BTW, I took the term 'integer type' from
https://docs.python.org/3.7/reference/atamodel.html?highlight=__index__#object.__index__.):
    - in Modules/posixmodule.c in dir_fd_converter():
      PyErr_Format(PyExc_TypeError,
                   "argument should be integer or None, not %.200s",
                   Py_TYPE(o)->tp_name);
    - in Modules/_functoolsmodule.c in lru_cache_new():
      PyErr_SetString(PyExc_TypeError, "maxsize should be integer or None");
```


so I changed the error messages in my patch to the form of
'argument should be ...' (which is, IMHO, much clearer).


also, now that the new PR was created, should I close the old one?

**Comment by serhiy-storchaka** [comment]
LGTM. Thank you Oren.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
thanks for the reviews :)

**Comment by serhiy-storchaka** [comment]
New changeset 004251059b9c5e48d47cb30b94bcb92cb44d3adf by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-29730: replace some calls to PyNumber_Check and improve some error messages (#650)
https://github.com/python/cpython/commit/004251059b9c5e48d47cb30b94bcb92cb44d3adf
