### ISSUE TITLE
Optimize functools.partial() for positional arguments

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73921]
BPO | [29735](https://bugs.python.org/issue29735)
--- | :---
Nosy | @rhettinger, @ncoghlan, @vstinner, @methane, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#516</li>
Files | <li>[bench_fastcall_partial.py](https://bugs.python.org/file46725/bench_fastcall_partial.py "Uploaded as text/plain at 2017-03-14.12:08:12 by @vstinner")</li><li>[partial_stack_usage.py](https://bugs.python.org/file46726/partial_stack_usage.py "Uploaded as text/plain at 2017-03-14.15:02:02 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-14.20:42:37.565>
created_at = <Date 2017-03-06.13:22:45.988>
labels = ['extension-modules', '3.7', 'performance']
title = 'Optimize functools.partial() for positional arguments'
updated_at = <Date 2017-03-24.22:19:27.049>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:19:27.049>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-14.20:42:37.565>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-03-06.13:22:45.988>
creator = 'vstinner'
dependencies = []
files = ['46725', '46726']
hgrepos = []
issue_num = 29735
keywords = []
message_count = 10.0
messages = ['289100', '289103', '289112', '289120', '289578', '289579', '289580', '289582', '289594', '290183']
nosy_count = 6.0
nosy_names = ['rhettinger', 'ncoghlan', 'vstinner', 'methane', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['516']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue29735'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The pull request makes functools.partial() faster for positional arguments. It avoids the creation of a tuple for positional arguments. It allocates a small buffer for up to 5 parameters. But it seems like even if the small buffer is not used, it's still faster.

Use small buffer, total: 2 positional arguments.

haypo@smithers$ ./python -m perf timeit -s 'from functools import partial; f = lambda x, y: None; g = partial(f, 1)' 'g(2)' --duplicate=100 --compare-to ../master-ref/python --python-names=ref:patch --python-names=ref:patch
ref: ..................... 138 ns +- 1 ns
patch: ..................... 121 ns +- 1 ns

Median +- std dev: [ref] 138 ns +- 1 ns -\> [patch] 121 ns +- 1 ns: 1.14x faster (-12%)


Don't use small buffer, total: 6 positional arguments.

haypo@smithers$ ./python -m perf timeit -s 'from functools import partial; f = lambda a1, a2, a3, a4, a5, a6: None; g = partial(f, 1, 2, 3, 4, 5)' 'g(6)' --duplicate=100 --compare-to ../master-ref/python --python-names=ref:patch --python-names=ref:patch
ref: ..................... 156 ns +- 1 ns
patch: ..................... 136 ns +- 0 ns

Median +- std dev: [ref] 156 ns +- 1 ns -\> [patch] 136 ns +- 0 ns: 1.15x faster (-13%)


Another benchmark  with 10 position arguments:

haypo@smithers$ ./python -m perf timeit -s 'from functools import partial; f = lambda a1, a2, a3, a4, a5, a6, a7, a8, a9, a10: None; g = partial(f, 1, 2, 3, 4, 5)' 'g(6, 7, 8, 9, 10)' --duplicate=100 --compare-to ../master-ref/python --python-names=ref:patch --python-names=ref:patch
ref: ..................... 193 ns +- 1 ns
patch: ..................... 166 ns +- 2 ns

Median +- std dev: [ref] 193 ns +- 1 ns -\> [patch] 166 ns +- 2 ns: 1.17x faster (-14%)

**Comment by vstinner** [comment]
functools.partial() is commonly used in the the asyncio module. The asyncio doc suggests to use it, because of deliberate limitations of the asyncio API.

**Comment by serhiy-storchaka** [comment]
What about C stack consumption? Is not this increase it?

Since nested partial()\`s are collapsed, you need to interlace them with other wrapper for testing.

```py
def decorator(f):
    def wrapper(*args):
        return f(*args)
    return wrapper

def f(*args): pass

for i in range(n):
    f = partial(f)
    f = decorator(f)

f(1, 2)
```

**Comment by serhiy-storchaka** [comment]
If the underlying function doesn't support fast call, and either args or pto-\>args are empty, partial_call() makes two unneeded copyings. Arguments are copied from a tuple to the raw array and from the array to new tuple. This is what the current code does, but this can be avoided.

If the underlying function doesn't support fast call, and both args and pto-\>args are not empty, patched partial_call() makes one unneeded copyings. Arguments are copied from tuples to the raw array and from the array to the new tuple. Only one copying is needed (from tuples to the new tuple).

**Comment by vstinner** [comment]
> If the underlying function doesn't support fast call, and both args and pto-\>args are not empty, patched partial_call() makes one unneeded copyings.

The simple workaround is to revert changes using FASTCALL in partial_call().

But for best performances, it seems like we need two code paths depending if the function supports fastcall or not. I will try to write a patch for that.

**Comment by vstinner** [comment]
bench_fastcall_partial.py: more complete microbenchmark.

I rewrote my patch:

* I added \_PyObject_HasFastCall(callable): return 1 if callable supports FASTCALL calling convention for positional arguments
* I splitted partial_call() into 2 subfunctions: partial_fastcall() is specialized for FASTCALL, partial_call_impl() uses PyObject_Call() with a tuple for positional arguments

The patch fixes the performance regression for VARARGS and optimize FASTCALL:

haypo@smithers$ ./python -m perf compare_to ref.json patch.json --table 
+-----------------------------+---------+------------------------------+
| Benchmark                   | ref     | patch                        |
+=============================+=========+==============================+
| partial Python, 1+1 arg     | 135 ns  | 118 ns: 1.15x faster (-13%)  |
+-----------------------------+---------+------------------------------+
| partial Python, 2+0 arg     | 114 ns  | 91.4 ns: 1.25x faster (-20%) |
+-----------------------------+---------+------------------------------+
| partial Python, 5+1 arg     | 151 ns  | 135 ns: 1.12x faster (-11%)  |
+-----------------------------+---------+------------------------------+
| partial Python, 5+5 arg     | 192 ns  | 168 ns: 1.15x faster (-13%)  |
+-----------------------------+---------+------------------------------+
| partial C VARARGS, 2+0 arg  | 153 ns  | 127 ns: 1.20x faster (-17%)  |
+-----------------------------+---------+------------------------------+
| partial C FASTCALL, 1+1 arg | 111 ns  | 93.7 ns: 1.18x faster (-15%) |
+-----------------------------+---------+------------------------------+
| partial C FASTCALL, 2+0 arg | 63.9 ns | 64.6 ns: 1.01x slower (+1%)  |
+-----------------------------+---------+------------------------------+

Not significant (1): partial C VARARGS, 1+1 arg

**Comment by vstinner** [comment]
> What about C stack consumption? Is not this increase it?

Yes, my optimization consumes more C stack: small_stack allocates 80 bytes on the stack (for 5 positional arguments). Is it an issue?

**Comment by serhiy-storchaka** [comment]
Nice results.

You made a great work for decreasing C stack consumption. It would be sad to lose it without good reasons. Could you please compare two variants, with and without small stack?

**Comment by vstinner** [comment]
I measured that my patch (pull request) increases the stack usage of 64 bytes per partial_call() call. I consider that it's accepted for a speedup between 1.12x faster and 1.25x faster.

Attached partial_stack_usage.py requires  testcapi_stack_pointer.patch of issue bpo-28870.

Original:

f(): [1000 calls] 624.0 B per call
f2(): [1000 calls] 624.0 B per call

Patched:

f(): [1000 calls] 688.0 B per call (+64 B)
f2(): [1000 calls] 688.0 B per call (+64 B)

**Comment by vstinner** [comment]
New changeset 0f7b0b397e12514ee213bc727c9939b66585cbe2 by Victor Stinner in branch 'master':
bpo-29735: Optimize partial_call(): avoid tuple (#516)
https://github.com/python/cpython/commit/0f7b0b397e12514ee213bc727c9939b66585cbe2
