### ISSUE TITLE
Optimize concatenating empty tuples

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73923]
BPO | [29737](https://bugs.python.org/issue29737)
--- | :---
Nosy | @rhettinger, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#524</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-25.05:53:51.161>
created_at = <Date 2017-03-06.19:48:36.848>
labels = ['interpreter-core', '3.7', 'performance']
title = 'Optimize concatenating empty tuples'
updated_at = <Date 2017-03-25.10:14:50.903>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-25.10:14:50.903>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-25.05:53:51.161>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-06.19:48:36.848>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29737
keywords = []
message_count = 6.0
messages = ['289129', '289149', '289150', '290283', '290466', '290471']
nosy_count = 3.0
nosy_names = ['rhettinger', 'vstinner', 'serhiy.storchaka']
pr_nums = ['524']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue29737'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Since tuples are immutable, concatenating with empty tuple can be optimized by returning an opposite argument.

Microbenchmarks (the difference is larger for larger tuples):

```sh
$ ./python -m perf timeit --duplicate=100 -s 'a = (1, 2)' 'a + ()'
Unpatched:  Median +- std dev: 288 ns +- 12 ns
Patched:    Median +- std dev: 128 ns +- 5 ns

$ ./python -m perf timeit --duplicate=100 -s 'a = (1, 2)' '() + a'
Unpatched:  Median +- std dev: 285 ns +- 16 ns
Patched:    Median +- std dev: 128 ns +- 6 ns
```


Non-empty tuples are not affected:

```sh
$ ./python -m perf timeit --duplicate=100 -s 'a = (1, 2)' 'a + a'
Unpatched:  Median +- std dev: 321 ns +- 24 ns
Patched:    Median +- std dev: 317 ns +- 26 ns
```

**Comment by rhettinger** [comment]
Is it at all common to concatenate empty tuples?  This seems like optimizing something that rarely occurs.

Also, the timings can be misleading if in real code these changes cause new branch mispredictions here which can slow the common case.  See http://stackoverflow.com/questions/11227809

**Comment by serhiy-storchaka** [comment]
I agree with your comments Raymond, but let me to expose my reasons.

An idea of optimizing empty tuple concatenating is inspired by partial(). It concatenates two tuples of arguments and it is common when one of tuple is empty. Current C implementation makes special case for this (and does this suboptimal). With optimized empty tuple concatenating it could be simpler and more efficient. Even when C implementation of partial() will not use this feature (see bpo-29735), I hope it can help in Python implementation of partial() and other partial-like functions.

**Comment by serhiy-storchaka** [comment]
New changeset 98e80c2babac0003182c3482c6c5437ea111e795 by Serhiy Storchaka in branch 'master':
bpo-29737: Optimize concatenating with empty tuple. (#524)
https://github.com/python/cpython/commit/98e80c2babac0003182c3482c6c5437ea111e795

**Comment by serhiy-storchaka** [comment]
The PR already was merged when you wrote your comment Raymond. If you insist I can revert it. But 0f7b0b397e12514ee213bc727c9939b66585cbe2 depends on it.

**Comment by vstinner** [comment]
I like the change. It prevents to duplicate tuples and so reduce the memory
footprint. PGO compilation helps branch prediction anyway.
