### ISSUE TITLE
Optimize builtin types constructor

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73922]
BPO | [29736](https://bugs.python.org/issue29736)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#519</li>
Files | <li>[bench.py](https://bugs.python.org/file46705/bench.py "Uploaded as text/plain at 2017-03-06.14:56:14 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-10.23:45:29.457>
created_at = <Date 2017-03-06.14:56:14.659>
labels = ['3.7', 'performance']
title = 'Optimize builtin types constructor'
updated_at = <Date 2017-08-10.23:45:29.451>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-10.23:45:29.451>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-10.23:45:29.457>
closer = 'vstinner'
components = []
creation = <Date 2017-03-06.14:56:14.659>
creator = 'vstinner'
dependencies = []
files = ['46705']
hgrepos = []
issue_num = 29736
keywords = []
message_count = 10.0
messages = ['289111', '289113', '289134', '289137', '289156', '289840', '289841', '289844', '289931', '300130']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['519']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue29736'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Attached PR replaces PyArg_ParseTupleAndKeywords() with
\_PyArg_ParseTupleAndKeywordsFast() to optimize the constructor of the
builtin types:

* bool: bool_new()
* bytes: bytes_new()
* complex: complex_new()
* float: float_new()
* int: long_new()
* list: list_init()
* str: unicode_new()
* tuple: tuple_new()

When using keywords, the speedup is between 1.55x faster and 1.92x faster.

When using only positional arguments, the speedup is between 1.07x faster and 1.14x faster.

Results of attached bench.py:

+-----------------------------------------------+--------+---------------------+
| Benchmark                                     | ref    | changed             |
+===============================================+========+=====================+
| complex(real=0.0, imag=0.0)                   | 452 ns | 1.92x faster (-48%) |
+-----------------------------------------------+--------+---------------------+
| bytes("x", encoding="ascii", errors="strict") | 498 ns | 1.88x faster (-47%) |
+-----------------------------------------------+--------+---------------------+
| str(b"x", encoding="ascii")                   | 340 ns | 1.55x faster (-35%) |
+-----------------------------------------------+--------+---------------------+
| list([None])                                  | 208 ns | 1.14x faster (-12%) |
+-----------------------------------------------+--------+---------------------+
| int(0)                                        | 113 ns | 1.11x faster (-10%) |
+-----------------------------------------------+--------+---------------------+
| float(1.0)                                    | 110 ns | 1.10x faster (-9%)  |
+-----------------------------------------------+--------+---------------------+
| str("x")                                      | 115 ns | 1.10x faster (-9%)  |
+-----------------------------------------------+--------+---------------------+
| tuple((None,))                                | 111 ns | 1.10x faster (-9%)  |
+-----------------------------------------------+--------+---------------------+
| bytes(b"x")                                   | 126 ns | 1.10x faster (-9%)  |
+-----------------------------------------------+--------+---------------------+
| bool(True)                                    | 107 ns | 1.09x faster (-8%)  |
+-----------------------------------------------+--------+---------------------+
| complex(0.0, 0.0)                             | 176 ns | 1.07x faster (-7%)  |
+-----------------------------------------------+--------+---------------------+

**Comment by serhiy-storchaka** [comment]
The half of constructors no longer use PyArg_ParseTupleAndKeywords().

I would wait until constructors be converted to Argument Clinic. There are ready patches for some of these builtin types, patches for other are in proggress.

**Comment by vstinner** [comment]
> I would wait until constructors be converted to Argument Clinic. There are ready patches for some of these builtin types, patches for other are in proggress.

Do you have links for these changes? It's painful to search for Argument Clinic changes, the issue title doesn't say anything except "derby \<number\>" :-/

**Comment by serhiy-storchaka** [comment]
float, list: bpo-20185.

**Comment by serhiy-storchaka** [comment]
Actually there is an issue with using Argument Clinic for constructors. I wrote a patch that fixes it and converts constructors of basic types to Argument Clinic a half year ago, but it was not finished and published due to focusing on 3.6. I'll update and publish it soon.

**Comment by serhiy-storchaka** [comment]
Victor, could you please rebase your PR? And maybe rerun benchmarks?

**Comment by vstinner** [comment]
Ok, will do.

**Comment by serhiy-storchaka** [comment]
And include bytearray.

**Comment by vstinner** [comment]
The following types were patched to use Argument Clinic (use now \_PyArg_ParseTupleAndKeywordsFast or don't accept keyword arguments anymore):

* complex
* float (don't accept keywords anymore)
* list
* tuple

The following types still uses PyArg_ParseTupleAndKeywords:

* bytes
* bytearray
* int (PyLong)
* str (unicode_new)

bool doesn't accept keywords anymore and uses now PyArg_UnpackTuple().

**Comment by vstinner** [comment]
I lost interest in this issue. I closed my PR, now I close this old issue.
