### ISSUE TITLE
asyncio get_extra_info() throws exception

### ISSUE THREAD

**Issue by fafhrd91** [python/cpython#73928]
BPO | [29742](https://bugs.python.org/issue29742)
--- | :---
Nosy | @bitdancer, @1st1, @fafhrd91
PRs | <li>python/cpython#494</li><li>python/cpython#525</li><li>python/cpython#645</li><li>python/cpython#646</li><li>python/cpython#703</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-12.21:06:52.123>
created_at = <Date 2017-03-06.22:35:43.479>
labels = ['3.7', 'expert-asyncio']
title = 'asyncio get_extra_info() throws exception'
updated_at = <Date 2017-03-24.22:21:52.700>
user = 'https://github.com/fafhrd91'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:21:52.700>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-12.21:06:52.123>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-03-06.22:35:43.479>
creator = 'fafhrd91'
dependencies = []
files = []
hgrepos = []
issue_num = 29742
keywords = []
message_count = 8.0
messages = ['289138', '289139', '289140', '289141', '289142', '290192', '290193', '290196']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'yselivanov', 'fafhrd91']
pr_nums = ['494', '525', '645', '646', '703']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29742'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by fafhrd91** [comment]
https://github.com/python/asyncio/issues/494

**Comment by fafhrd91** [comment]
exception on get_extra_info() on closed ssl transport

```
Feb 18 13:18:09 btc electrumx_server.py[1732]: ERROR:ElectrumX:[15328] Traceback (most recent call last):
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.11.1-py3.5.egg/lib/jsonrpc.py", line 528, in process_single_request
Feb 18 13:18:09 btc electrumx_server.py[1732]:     result = await self.handle_payload(payload, self.request_handler)
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.11.1-py3.5.egg/lib/jsonrpc.py", line 608, in handle_payload
Feb 18 13:18:09 btc electrumx_server.py[1732]:     return await handler(**kw_args)
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.11.1-py3.5.egg/server/session.py", line 282, in banner
Feb 18 13:18:09 btc electrumx_server.py[1732]:     if self.is_tor():
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.11.1-py3.5.egg/server/session.py", line 259, in is_tor
Feb 18 13:18:09 btc electrumx_server.py[1732]:     peer_info = self.peer_info()
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/local/lib/python3.5/dist-packages/electrumx-0.11.1-py3.5.egg/lib/jsonrpc.py", line 764, in peer_info
Feb 18 13:18:09 btc electrumx_server.py[1732]:     return self.transport.get_extra_info('peername')
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/lib/python3.5/asyncio/sslproto.py", line 306, in get_extra_info
Feb 18 13:18:09 btc electrumx_server.py[1732]:     return self._ssl_protocol._get_extra_info(name, default)
Feb 18 13:18:09 btc electrumx_server.py[1732]:   File "/usr/lib/python3.5/asyncio/sslproto.py", line 537, in _get_extra_info
Feb 18 13:18:09 btc electrumx_server.py[1732]:     return self._transport.get_extra_info(name, default)
Feb 18 13:18:09 btc electrumx_server.py[1732]: AttributeError: 'NoneType' object has no attribute 'get_extra_info'
```

**Comment by bitdancer** [comment]
Thanks for the report and PR, but your fix is not obviously correct.  In general exceptions are the way in Python that errors are reported, and asking for extra_info on a closed stream is an error.  The exception raised is not clear, so perhaps the asyncio folks will want to improve it.  Or perhaps I'm wrong and they will want to return None, but I'll be a bit surprised if that is the case :)

**Comment by fafhrd91** [comment]
get_extra_info() returns optional transport information, I think it is ok to return None for closed transport.
https://github.com/python/cpython/blob/master/Lib/asyncio/transports.py#L18

I propose this feature initially, during early tulip development
but now I think it is not good api.

**Comment by 1st1** [comment]
> Thanks for the report and PR, but your fix is not obviously correct.  

Not for this particular asyncio method though, see asyncio PEP [1]. But there's an actual bug in the PR, instead of returning `None` we should return `default`.

[1] https://www.python.org/dev/peps/pep-3156/#methods-for-all-transports

**Comment by 1st1** [comment]
New changeset db522dc86294a99f46a63cd5b54c7c4ab8017c96 by Yury Selivanov in branch '3.5':
bpo-29742: asyncio get_extra_info() throws exception (#525) (#646)
https://github.com/python/cpython/commit/db522dc86294a99f46a63cd5b54c7c4ab8017c96

**Comment by 1st1** [comment]
New changeset 99f8d33a94c8951fd6b2d5f079d20be698150993 by Yury Selivanov in branch '3.6':
bpo-29742: asyncio get_extra_info() throws exception (#525) (#645)
https://github.com/python/cpython/commit/99f8d33a94c8951fd6b2d5f079d20be698150993

**Comment by 1st1** [comment]
New changeset 2b27e2e6a35c3d3e369612b984017fe0d1bfcf0c by Yury Selivanov (Nikolay Kim) in branch 'master':
bpo-29742: asyncio get_extra_info() throws exception (#525)
https://github.com/python/cpython/commit/2b27e2e6a35c3d3e369612b984017fe0d1bfcf0c
