### ISSUE TITLE
zipfile raises wrong exception for some incorrect passwords

### ISSUE THREAD

**Issue by 92a8c186-d8e4-4ba6-98b7-569174c59511** [python/cpython#73925]
BPO | [29739](https://bugs.python.org/issue29739)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @jcushman
Files | <li>[fail.py](https://bugs.python.org/file46706/fail.py "Uploaded as text/plain at 2017-03-06.20:48:17 by @jcushman"): Reproduction script</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-11-23.17:01:18.261>
created_at = <Date 2017-03-06.20:48:19.245>
labels = ['invalid', 'type-bug', 'library']
title = 'zipfile raises wrong exception for some incorrect passwords'
updated_at = <Date 2021-11-23.17:01:18.261>
user = 'https://github.com/jcushman'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-23.17:01:18.261>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-11-23.17:01:18.261>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2017-03-06.20:48:19.245>
creator = 'jcushman'
dependencies = []
files = ['46706']
hgrepos = []
issue_num = 29739
keywords = []
message_count = 6.0
messages = ['289132', '289152', '289175', '289177', '296269', '296290']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'jcushman']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29739'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by 92a8c186-d8e4-4ba6-98b7-569174c59511** [comment]
This bug arises when attempting to unzip a password-protected zipfile using the wrong password.

Usually when zipfile extraction is attempted with an incorrect password, zipfile raise `RuntimeError("Bad password for file")`. But for a small subset of passwords (about .4% of possible passwords), it instead raises `BadZipfile("Bad CRC-32 for file")`.

Attached is a script that attempts to decrypt a zip file using every 3-letter uppercase password. (This assumes you have first created the zip file, by running something like: `echo "stuff" > /tmp/foo.txt; zip -e -P password /tmp/foo.zip /tmp/foo.txt`.)

The specific passwords that trigger the wrong exception will vary each time the zip file is created. On my system, for a particular zip file, the result is this output:


BadZipFile b'ACB'
BadZipFile b'AMJ'
BadZipFile b'ASL'
BadZipFile b'AZV'
BadZipFile b'BCI'
BadZipFile b'BMV'
BadZipFile b'BQG'
BadZipFile b'BRB'
BadZipFile b'BYH'
BadZipFile b'CHU'
BadZipFile b'CTV'
BadZipFile b'DEF'
BadZipFile b'DHJ'
BadZipFile b'DSR'
BadZipFile b'EWG'
BadZipFile b'GOK'
BadZipFile b'GUK'
BadZipFile b'HGL'
BadZipFile b'HPV'
BadZipFile b'IAC'
BadZipFile b'IGQ'
BadZipFile b'IHG'
BadZipFile b'ILB'
BadZipFile b'IRJ'
BadZipFile b'JDW'
BadZipFile b'JIT'
BadZipFile b'JMK'
BadZipFile b'JPD'
BadZipFile b'JWL'
BadZipFile b'JXS'
BadZipFile b'KAR'
BadZipFile b'KKH'
BadZipFile b'LNW'
BadZipFile b'MEL'
BadZipFile b'NDY'
BadZipFile b'NFJ'
BadZipFile b'NLU'
BadZipFile b'NQU'
BadZipFile b'OXC'
BadZipFile b'PHA'
BadZipFile b'PQY'
BadZipFile b'QCN'
BadZipFile b'QFT'
BadZipFile b'QMB'
BadZipFile b'QWZ'
BadZipFile b'QYS'
BadZipFile b'RBR'
BadZipFile b'SKU'
BadZipFile b'SLG'
BadZipFile b'STU'
BadZipFile b'SUP'
BadZipFile b'UCD'
BadZipFile b'UOA'
BadZipFile b'UQM'
BadZipFile b'VAO'
BadZipFile b'VEQ'
BadZipFile b'VJW'
BadZipFile b'VVH'
BadZipFile b'WDA'
BadZipFile b'XCR'
BadZipFile b'XIY'
BadZipFile b'XLG'
BadZipFile b'YJA'
BadZipFile b'YMA'
BadZipFile b'YRB'
BadZipFile b'ZHT'
BadZipFile b'ZVJ'
BadZipFile b'ZWR'
BadZipFile b'ZZT'
69 out of 17576 passwords raise BadZipFile


Versions:

I reproduced this in Python 2.7.10 and 3.6.0, using a zip file created on Mac OS 10.12.3 with this zip version: 


```sh
$ zip --version
Copyright (c) 1990-2008 Info-ZIP - Type 'zip "-L"' for software license.
This is Zip 3.0 (July 5th 2008), by Info-ZIP.
Compiled with gcc 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34) for Unix (Mac OS X) on Jul 30 2016.
```

**Comment by serhiy-storchaka** [comment]
ZIP file has something like 8-bit control sum for checking the validity of the password. With the chance 1/256 the check is passed for wrong password. This is unavoidable.

**Comment by 92a8c186-d8e4-4ba6-98b7-569174c59511** [comment]
Ah, thanks! That makes sense. I see it's documented in "man unzip" as well:

"The correct password will always check out against the header, but there is a 1-in-256 chance that an incorrect password will as well.  (This is a security feature of the PKWARE zipfile format; it helps prevent brute-force attacks  that  might otherwise gain a large speed advantage by testing only the header.)  In the case that an incorrect password is given but it passes the header test anyway, either an incorrect CRC will be generated for  the  extracted  data  or  else  unzip  will  fail  during  the  extraction  because  the ``decrypted'' bytes do not constitute a valid compressed data stream."

Would it make sense to add a note to documentation for zipfile functions that take a password?

**Comment by serhiy-storchaka** [comment]
I don't think that this makes much sense. The exception raised for wrong password is not documented, even the fact that some exception is raised is not documented. In very rare cases you can read a data without any error using wrong password, but the result will be of course not correct.

**Comment by serhiy-storchaka** [comment]
Actually this feature helps to do the brute-force attack. 255 of 256 passwords can be rejected by testing only the header. Old ZIP files encryption is very weak, it isn't used in serious applications.

**Comment by 92a8c186-d8e4-4ba6-98b7-569174c59511** [comment]
Agreed that no one should be using zip encryption. :) I hit this issue working on an academic exercise. I'm fine with closing this. 

(I do think the exception types in zipfile set up a trap for the programmer here: Python throws a different exception type 1/256 of the time for the same error case, which is undocumented and hard to discover by trial and error. It's pretty unlikely that anyone would write a correct `try-except` block for zip decryption on their first few attempts, and someone who needs to catch bad passwords but not bad zip files will most likely ship broken code. But just catching RuntimeError and BadZipfile gets you pretty close, so I don't think it's a big deal.)
