### ISSUE TITLE
Update marshal docs to Python 3

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73932]
BPO | [29746](https://bugs.python.org/issue29746)
--- | :---
Nosy | @bitdancer, @vadmium, @serhiy-storchaka, @Mariatta
PRs | <li>python/cpython#547</li><li>python/cpython#630</li><li>python/cpython#631</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-03-12.08:16:34.147>
created_at = <Date 2017-03-07.10:41:07.785>
labels = ['type-bug', '3.7', 'docs']
title = 'Update marshal docs to Python 3'
updated_at = <Date 2017-03-24.22:25:38.888>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:25:38.888>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-03-12.08:16:34.147>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-03-07.10:41:07.785>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29746
keywords = []
message_count = 5.0
messages = ['289157', '289431', '290216', '290217', '290219']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'martin.panter', 'serhiy.storchaka', 'Mariatta']
pr_nums = ['547', '630', '631']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29746'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The marshal module documentation still uses terms from Python 2. It mentions sys.stdin and os.popen() as legitimate sources (but they are text files).

**Comment by vadmium** [comment]
One other difference between 2 and 3 is that Python 3 has two kinds of “binary” files. In most cases, a subset of the BufferedIOBase API is assumed, which does “exact” reads and writes. I understand this is how Python 2 files worked. But there is also RawIOBase, which does short reads and writes.

Perhaps it is worth clarifying if the file objects have to be the “buffered” kind or not. In my patches for bpo-24291 and bpo-26721, I resorted to wording like

The “write” method . . . should write each chunk in full, like BufferedIOBase.

**Comment by serhiy-storchaka** [comment]
New changeset 4652d82a51e6530a4f820588a6209d3295963bdb by Serhiy Storchaka in branch '3.6':
bpo-29746: Update marshal docs to Python 3. (#547) (#631)
https://github.com/python/cpython/commit/4652d82a51e6530a4f820588a6209d3295963bdb

**Comment by serhiy-storchaka** [comment]
New changeset f12f820ef887b009ce70e67e71b8690f30c605ee by Serhiy Storchaka in branch '3.5':
bpo-29746: Update marshal docs to Python 3. (#547) (#630)
https://github.com/python/cpython/commit/f12f820ef887b009ce70e67e71b8690f30c605ee

**Comment by serhiy-storchaka** [comment]
New changeset c611a5b1d4fab0123bf622f06c3bfa510221dc32 by Serhiy Storchaka in branch 'master':
bpo-29746: Update marshal docs to Python 3. (#547)
https://github.com/python/cpython/commit/c611a5b1d4fab0123bf622f06c3bfa510221dc32
