### ISSUE TITLE
Outdated int() docstring

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73935]
BPO | [29749](https://bugs.python.org/issue29749)
--- | :---
Nosy | @brettcannon, @vstinner, @serhiy-storchaka, @svelankar
PRs | <li>python/cpython#565</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-09.00:29:32.245>
created_at = <Date 2017-03-07.13:44:49.483>
labels = ['3.7']
title = 'Outdated int() docstring'
updated_at = <Date 2017-03-24.22:40:12.727>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:40:12.727>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-09.00:29:32.245>
closer = 'brett.cannon'
components = []
creation = <Date 2017-03-07.13:44:49.483>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29749
keywords = []
message_count = 6.0
messages = ['289163', '289246', '289251', '289252', '289255', '290258']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'vstinner', 'serhiy.storchaka', 'svelankar']
pr_nums = ['565']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29749'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
bpo-29695 removed "bad keyword parameters in int(), bool(), float(), list() and tuple()", but int docstring (at least) is now outdated:

```pycon
haypo@selma$ ./python
Python 3.7.0a0 (master:8f6b344d368c15c3fe56c65c2f2776e7766fef55, Mar  7 >>> help(int)
class int(object)
 |  int(x=0) -> integer
 |  int(x, base=10) -> integer
 ...
>>> int(x=0)
TypeError: 'x' is an invalid keyword argument for this function
```

**Comment by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [comment]
int docstring is the only one that needs to be changed. docstrings for float,tuple and list look fine to me.

**Comment by serhiy-storchaka** [comment]
int() can be called without argument.

**Comment by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [comment]
True, but the docstring says "return 0 if no arguments are given". So please let me know, if you want me to still change it i.e. add int() or keep it as it is. Thanks.

**Comment by serhiy-storchaka** [comment]
After converting int.\_\_new__() to Argument Clinic this issue will become outdated.

**Comment by brettcannon** [comment]
New changeset 390a0969c1206a37c86961ebf7ef3050681ed8dd by Brett Cannon (svelankar) in branch 'master':
bpo-29749: Update int() docstring (GH-565)
https://github.com/python/cpython/commit/390a0969c1206a37c86961ebf7ef3050681ed8dd
