### ISSUE TITLE
test_site failing on AppVeyor

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#73949]
BPO | [29763](https://bugs.python.org/issue29763)
--- | :---
Nosy | @brettcannon, @pfmoore, @tjguk, @zware, @zooba
PRs | <li>python/cpython#624</li><li>python/cpython#625</li><li>python/cpython#841</li><li>python/cpython#939</li><li>python/cpython#942</li><li>python/cpython#954</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zware'
closed_at = <Date 2017-03-12.04:41:01.305>
created_at = <Date 2017-03-08.21:39:39.635>
labels = ['3.7', 'type-bug', 'tests', 'OS-windows']
title = 'test_site failing on AppVeyor'
updated_at = <Date 2017-05-14.20:49:48.358>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-14.20:49:48.358>
actor = 'zach.ware'
assignee = 'zach.ware'
closed = True
closed_date = <Date 2017-03-12.04:41:01.305>
closer = 'zach.ware'
components = ['Tests', 'Windows']
creation = <Date 2017-03-08.21:39:39.635>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 29763
keywords = []
message_count = 7.0
messages = ['289260', '289473', '290222', '290223', '290961', '290965', '293659']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = ['624', '625', '841', '939', '942', '954']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29763'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by brettcannon** [comment]
E.g. https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.142. This looks to be the last consistent failure on AppVeyor.

**Comment by zware** [comment]
This should be fixed by [PR624](https://github.com/python/cpython/pull/624) and [PR625](https://github.com/python/cpython/pull/625).

**Comment by zware** [comment]
New changeset 7c6d6e056460753c916348feee0e4916a97d7c86 by Zachary Ware in branch '3.6':
bpo-29763: Use support.unlink instead of os.unlink (GH-624) (GH-625)
https://github.com/python/cpython/commit/7c6d6e056460753c916348feee0e4916a97d7c86

**Comment by zware** [comment]
New changeset 93710c152e6bcfffdf2f1f15bb5f75b013aef422 by Zachary Ware in branch 'master':
bpo-29763: Use support.unlink instead of os.unlink (GH-624)
https://github.com/python/cpython/commit/93710c152e6bcfffdf2f1f15bb5f75b013aef422

**Comment by zware** [comment]
New changeset b94d7fd4efa877d649cea9c8125c8869ffe0c32d by Zachary Ware in branch 'master':
bpo-29763: Use unittest cleanup in test_site (GH-841)
https://github.com/python/cpython/commit/b94d7fd4efa877d649cea9c8125c8869ffe0c32d

**Comment by zware** [comment]
New changeset cd815edf012dc6dd20dfeef91951270e96607616 by Zachary Ware in branch 'master':
Revert "bpo-29763: Use unittest cleanup in test_site (GH-841)" (GH-942)
https://github.com/python/cpython/commit/cd815edf012dc6dd20dfeef91951270e96607616

**Comment by zware** [comment]
New changeset d48214f22c84f3d949457c854e263074994b6fa2 by Zachary Ware in branch 'master':
bpo-29763: Clean up \_pth tests (GH-954)
https://github.com/python/cpython/commit/d48214f22c84f3d949457c854e263074994b6fa2
