### ISSUE TITLE
Use "raise from None"

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73948]
BPO | [29762](https://bugs.python.org/issue29762)
--- | :---
Nosy | @serhiy-storchaka, @MojoVampire
PRs | <li>python/cpython#569</li><li>python/cpython#3978</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-05.06:39:04.265>
created_at = <Date 2017-03-08.21:14:36.264>
labels = ['3.7', 'type-feature', 'library']
title = 'Use "raise from None"'
updated_at = <Date 2017-10-12.21:02:42.171>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-12.21:02:42.171>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-05.06:39:04.265>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-08.21:14:36.264>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29762
keywords = []
message_count = 5.0
messages = ['289258', '289266', '289267', '289274', '291161']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'josh.r']
pr_nums = ['569', '3978']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29762'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Sometimes after catching some exception the new exception of more appropriate type and with more appropriate message is raised. The initial exception often is not relevant to the final exception, it is raised only due to using EAFP rather than LBYL. It should be excluded from the traceback by using "raise from None". This idiom is often used. Following PR makes it be used in more cases.

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
To tie the exceptions to the actual line, would it perhaps make sense to copy over the traceback of the original exception using .with_traceback?

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
Particularly when the type of the exception isn't being changed, it's only altering the message to provide more information?

**Comment by serhiy-storchaka** [comment]
I don't think this is needed. The traceback points to the actual line -- the line with the "raise" statement.

**Comment by serhiy-storchaka** [comment]
New changeset 5affd23e6f42125998724787025080a24839266e by Serhiy Storchaka in branch 'master':
bpo-29762: More use "raise from None". (#569)
https://github.com/python/cpython/commit/5affd23e6f42125998724787025080a24839266e
