### ISSUE TITLE
build python failed on test_socket due to unused_port is actually used.

### ISSUE THREAD

**Issue by 0ad20666-5c21-42d0-910b-7c128d28c1ac** [python/cpython#73953]
BPO | [29767](https://bugs.python.org/issue29767)
--- | :---
Nosy | @vstinner, @zhangyangyu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-11.21:46:47.106>
created_at = <Date 2017-03-09.03:54:20.780>
labels = ['build']
title = 'build python failed on test_socket due to unused_port is actually used.'
updated_at = <Date 2017-09-11.21:46:47.104>
user = 'https://bugs.python.org/ShuoLi'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-11.21:46:47.104>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-11.21:46:47.106>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-03-09.03:54:20.780>
creator = 'Shuo Li'
dependencies = []
files = []
hgrepos = []
issue_num = 29767
keywords = []
message_count = 5.0
messages = ['289268', '289279', '289351', '289354', '301908']
nosy_count = 3.0
nosy_names = ['vstinner', 'xiang.zhang', 'Shuo Li']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29767'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0ad20666-5c21-42d0-910b-7c128d28c1ac** [comment]
I am running a debian system. And trying to build cpython3.6 from source. 
When I run make altinstall, it failed on test_socket. Reporting cli attribute is missing.

After some trouble shooting, it seems the support.get_unused_port() is not reliable. Then I modified it and return a port I am sure no one is using, the build succeeded.

**Comment by zhangyangyu** [comment]
Could you show the failure message here? And you could make your patch a PR on GitHub.

**Comment by 0ad20666-5c21-42d0-910b-7c128d28c1ac** [comment]
The error message is just a "Port already used".

Possible cause 1: find_port default interface is HOST, which is 127.0.0.1. And in most test cases, they use 0.0.0.0. So they are on different interface. 

2: system reuse the port, since I build python on a busy server, that is possible.

**Comment by 0ad20666-5c21-42d0-910b-7c128d28c1ac** [comment]
```pytb
Another error message:
Unhandled exception in thread started by <bound method ThreadableTest.clientRun of <test.test_socket.NetworkConnectionAttributesTest testMethod=testSourceAddress>>
Traceback (most recent call last):
  File "/tmp/python3.6/Python-3.6.0/Lib/test/test_socket.py", line 293, in clientRun
    self.clientTearDown()
  File "/tmp/python3.6/Python-3.6.0/Lib/test/test_socket.py", line 4379, in clientTearDown
    self.cli.close()
AttributeError: 'NetworkConnectionAttributesTest' object has no attribute 'cli'
```

**Comment by vstinner** [comment]
I am sorry but it is not possible to fix the issue since we don't have enough information to identify or reproduce the bug.
