### ISSUE TITLE
2.7.12 compile error from ssl related

### ISSUE THREAD

**Issue by 8288e86c-8e79-4882-9d1f-fbfd6a21d531** [python/cpython#73951]
BPO | [29765](https://bugs.python.org/issue29765)
--- | :---
Nosy | @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-03-10.19:54:47.204>
created_at = <Date 2017-03-09.01:00:20.420>
labels = ['expert-SSL', 'build', 'invalid']
title = '2.7.12 compile error from ssl related'
updated_at = <Date 2017-03-10.19:54:47.202>
user = 'https://bugs.python.org/ada'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-10.19:54:47.202>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-03-10.19:54:47.204>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2017-03-09.01:00:20.420>
creator = 'ada'
dependencies = []
files = []
hgrepos = []
issue_num = 29765
keywords = []
message_count = 4.0
messages = ['289262', '289329', '289371', '289405']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'ada']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29765'
versions = ['Python 2.7']
```

</p></details>

**Comment by 8288e86c-8e79-4882-9d1f-fbfd6a21d531** [comment]
Download the python version 2.7.12 source code from official web site.
Compile the python code by the following steps:
sudo ./configure
sudo make
sudo make install

but from make, I get the following errors:
/Modules/_ssl.c: In function ‘_create_tuple_for_X509_NAME’:
./Modules/_ssl.c:684: error: dereferencing pointer to incomplete type
./Modules/_ssl.c:701: error: dereferencing pointer to incomplete type
./Modules/_ssl.c: In function ‘_get_peer_alt_names’:
./Modules/_ssl.c:804: error: dereferencing pointer to incomplete type
./Modules/_ssl.c:809: error: dereferencing pointer to incomplete type
./Modules/_ssl.c:815: error: dereferencing pointer to incomplete type
./Modules/_ssl.c:876: warning: ‘ASN1_STRING_data’ is deprecated (declared at /usr/local/include/openssl/asn1.h:553)
./Modules/_ssl.c: In function ‘_get_crl_dp’:
./Modules/_ssl.c:1029: error: dereferencing pointer to incomplete type
./Modules/_ssl.c: In function ‘PySSL_compression’:
./Modules/_ssl.c:1446: error: dereferencing pointer to incomplete type
./Modules/_ssl.c:1448: error: dereferencing pointer to incomplete type
./Modules/_ssl.c: In function ‘context_new’:
./Modules/_ssl.c:2000: warning: ‘TLSv1_method’ is deprecated (declared at /usr/local/include/openssl/ssl.h:1596)
./Modules/_ssl.c:2003: warning: ‘TLSv1_1_method’ is deprecated (declared at /usr/local/include/openssl/ssl.h:1602)

please help me check where I take a mistake. The related information is:
Linux version: 
Linux root:2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
OpenSSL version: 
[root@root Python-2.7.12]# rpm -aq | grep openssl
openssl-static-1.0.1e-48.el6_8.4.x86_64
openssl-1.0.1e-48.el6_8.4.x86_64
openssl-devel-1.0.1e-48.el6_8.4.x86_64
COMPILER version: 
[root@root Python-2.7.12]# yum list installed | grep -i  gcc
gcc.x86_64                           4.4.7-17.el6                       
gcc-c++.x86_64                       4.4.7-17.el6                       
gcc-gfortran.x86_64                  4.4.7-17.el6                       
libgcc.i686                          4.4.7-17.el6                       
libgcc.x86_64                        4.4.7-17.el6                       


Thanks in advance.

**Comment by tiran** [comment]
/usr/local looks wrong. Did you install a custom build of OpenSSL? What's the output of

    rpm -qf /usr/local/include/openssl/asn1.h

?

**Comment by 8288e86c-8e79-4882-9d1f-fbfd6a21d531** [comment]
The output is: 

[root@root local]# rpm -qf /usr/local/include/openssl/asn1.h 
file /usr/local/include/openssl/asn1.h is not owned by any package

**Comment by tiran** [comment]
You have some custom, unsupported version of OpenSSL installed in /usr/local. That custom version is not compatible with Python 2.7.12.
