### ISSUE TITLE
Unintentionally deleted line on library/collections.rst

### ISSUE THREAD

**Issue by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [python/cpython#73958]
BPO | [29772](https://bugs.python.org/issue29772)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @cocoatomo
PRs | <li>python/cpython#581</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-09.15:56:01.597>
created_at = <Date 2017-03-09.14:44:56.632>
labels = ['docs']
title = 'Unintentionally deleted line on library/collections.rst'
updated_at = <Date 2017-03-24.22:38:11.577>
user = 'https://github.com/cocoatomo'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:38:11.577>
actor = 'rhettinger'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-09.15:56:01.597>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-03-09.14:44:56.632>
creator = 'cocoatomo'
dependencies = []
files = []
hgrepos = []
issue_num = 29772
keywords = []
message_count = 3.0
messages = ['289300', '289303', '290248']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'serhiy.storchaka', 'cocoatomo']
pr_nums = ['581']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29772'
versions = ['Python 2.7']
```

</p></details>

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
The last part of "Counter objects" section has a strange line: "in Smalltalk."

https://docs.python.org/2.7/library/collections.html#counter-objects

The line just before "in Smalltalk" might be deleted by accident.
Related issue is bpo-25910 [1]_ and the applied patch is this [2]_, although an intended patch might looks like this [3]_.

.. [1] http://bugs.python.org/issue25910

.. [2] https://hg.python.org/cpython/rev/14e00e7e4d51#l15.7
   patch for the 2.7 branch

.. [3] https://hg.python.org/cpython/rev/ce5ef48b5140#l21.7
   patch for the 3.5 branch

I will create a pull request.

**Comment by rhettinger** [comment]
Nice catch.

**Comment by rhettinger** [comment]
New changeset 309fb90f6895c47e7b41df3d739db45e8ec136c9 by Raymond Hettinger (cocoatomo) in branch '2.7':
Insert the line which should not have been deleted (#581)
https://github.com/python/cpython/commit/309fb90f6895c47e7b41df3d739db45e8ec136c9
