### ISSUE TITLE
Executable help output (--help) at commandline is wrong for option -B

### ISSUE THREAD

**Issue by e463ac05-e672-47f9-984a-f51a19831e40** [python/cpython#73956]
BPO | [29770](https://bugs.python.org/issue29770)
--- | :---
Nosy | @brettcannon, @tds333, @zhangyangyu
PRs | <li>python/cpython#590</li><li>python/cpython#612</li><li>python/cpython#613</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-11.06:16:53.678>
created_at = <Date 2017-03-09.12:49:52.622>
labels = ['type-feature', '3.7', 'docs']
title = 'Executable help output (--help) at commandline is wrong for option -B'
updated_at = <Date 2017-03-24.22:27:57.691>
user = 'https://github.com/tds333'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:27:57.691>
actor = 'xiang.zhang'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-11.06:16:53.678>
closer = 'xiang.zhang'
components = ['Documentation']
creation = <Date 2017-03-09.12:49:52.622>
creator = 'tds333'
dependencies = []
files = []
hgrepos = []
issue_num = 29770
keywords = []
message_count = 5.0
messages = ['289287', '289538', '290226', '290229', '290230']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'tds333', 'docs@python', 'xiang.zhang']
pr_nums = ['590', '612', '613']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29770'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by e463ac05-e672-47f9-984a-f51a19831e40** [comment]
The output for "python --help" for the option -B is wrong.
It contains also the old pyo files. But they were removed.

Output is:

-B     : don't write .py[co] files on import; also PYTHONDONTWRITEBYTECODE=x

should be:

-B     : don't write .pyc files on import; also PYTHONDONTWRITEBYTECODE=x

**Comment by e463ac05-e672-47f9-984a-f51a19831e40** [comment]
Thanks for fixing this so fast. Good work.

**Comment by zhangyangyu** [comment]
New changeset ce222c87706b1062f7fc03867d1867aa4848dd7b by Xiang Zhang in branch '3.5':
bpo-29770: remove outdated PYO related info (GH-590) (GH-613)
https://github.com/python/cpython/commit/ce222c87706b1062f7fc03867d1867aa4848dd7b

**Comment by zhangyangyu** [comment]
New changeset 16416c22f9b8d9e067506d3a98f661756c80389c by Xiang Zhang in branch '3.6':
bpo-29770: remove outdated PYO related info (GH-590) (GH-612)
https://github.com/python/cpython/commit/16416c22f9b8d9e067506d3a98f661756c80389c

**Comment by zhangyangyu** [comment]
New changeset 0710d754255e731e6fcc3f206b51db6156da17c8 by Xiang Zhang in branch 'master':
bpo-29770: remove outdated PYO related info (GH-590)
https://github.com/python/cpython/commit/0710d754255e731e6fcc3f206b51db6156da17c8
