### ISSUE TITLE
Modernize properties

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73962]
BPO | [29776](https://bugs.python.org/issue29776)
--- | :---
Nosy | @ethanfurman, @serhiy-storchaka
PRs | <li>python/cpython#585</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-19.06:41:14.370>
created_at = <Date 2017-03-09.17:10:02.447>
labels = ['3.7', 'type-feature', 'library']
title = 'Modernize properties'
updated_at = <Date 2017-03-24.22:09:17.099>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:09:17.099>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-19.06:41:14.370>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-09.17:10:02.447>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29776
keywords = []
message_count = 5.0
messages = ['289309', '289315', '289316', '289325', '290165']
nosy_count = 2.0
nosy_names = ['ethan.furman', 'serhiy.storchaka']
pr_nums = ['585']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29776'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Following PR updates Python sources to use new shiny syntax for properties. It replaces the old code

```py
    def _foo(self):
        ...

    def _set_foo(self, value):
        ...

    foo = property(_foo, _set_foo)
```


with the new code

```py
    @property
    def foo(self):
        ...

    @foo.setter
    def foo(self, value):
        ...
```


New syntax was added in Python 2.4.

**Comment by ethanfurman** [comment]
Have you made sure nothing calls the replaced functions manually?

Such as:

    ...
    self._set_foo(9)
    ...

**Comment by serhiy-storchaka** [comment]
I replaced only private getters and setters. All tests passed.

**Comment by serhiy-storchaka** [comment]
I have checked and none from replaced function is used. But just for the case I reverted changes for [Lib/xml/dom/](https://github.com/python/cpython/blob/main/Lib/xml/dom). Here used more complex logic for generating other properties.

**Comment by serhiy-storchaka** [comment]
New changeset bdf6b910f9ea75609caee498a975af03b6d23f67 by Serhiy Storchaka in branch 'master':
bpo-29776: Use decorator syntax for properties. (#585)
https://github.com/python/cpython/commit/bdf6b910f9ea75609caee498a975af03b6d23f67
