### ISSUE TITLE
There appears to be a spurious ^0 in sys.version for 3.6.1rc1

### ISSUE THREAD

**Issue by pfmoore** [python/cpython#73961]
BPO | [29775](https://bugs.python.org/issue29775)
--- | :---
Nosy | @pfmoore, @ned-deily, @zooba
Superseder | <li>bpo-27593: Deprecate sys._mercurial and create sys._git</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = <Date 2017-03-09.20:14:57.309>
created_at = <Date 2017-03-09.16:25:23.950>
labels = ['interpreter-core', 'type-bug']
title = 'There appears to be a spurious ^0 in sys.version for 3.6.1rc1'
updated_at = <Date 2017-03-09.20:14:57.307>
user = 'https://github.com/pfmoore'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-09.20:14:57.307>
actor = 'ned.deily'
assignee = 'ned.deily'
closed = True
closed_date = <Date 2017-03-09.20:14:57.309>
closer = 'ned.deily'
components = ['Interpreter Core']
creation = <Date 2017-03-09.16:25:23.950>
creator = 'paul.moore'
dependencies = []
files = []
hgrepos = []
issue_num = 29775
keywords = []
message_count = 2.0
messages = ['289305', '289326']
nosy_count = 3.0
nosy_names = ['paul.moore', 'ned.deily', 'steve.dower']
pr_nums = []
priority = None
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '27593'
type = 'behavior'
url = 'https://bugs.python.org/issue29775'
versions = ['Python 3.6']
```

</p></details>

**Comment by pfmoore** [comment]
The 3.6.1rc1 build seems to have a spurious "^0" at the end of the version, before the VCS ID - 3.6.1rc1^0):

```pycon
>py -3.6
Python 3.6.1rc1 (v3.6.1rc1^0:e0fbe5feee4f9c00f09eb9659c2182183036261a, Mar  4 2017, 20:00:12) [MSC v.1900 64 bit (AMD64)] on win32
>>> sys.version
'3.6.1rc1 (v3.6.1rc1^0:e0fbe5feee4f9c00f09eb9659c2182183036261a, Mar  4 2017, 20:00:12) [MSC v.1900 64 bit (AMD64)]'
```


It's not showing in sys.version_info, so it's probably only cosmetic. Also, I don't think this is really a release blocker - just marking it as such so it gets checked (I wonder if it's an artifact of the github migration, I think git uses ^0 to mean something specific in relation to commit IDs?)

I've only checked on Windows. I don't know if it's the same on Unix.

If it's deemed cosmetic, I'm happy for it to be downgraded to non-blocking, or even closed as not an issue. Just wanted to flag it up in case it's a symptom of something deeper.

**Comment by ned-deily** [comment]
Thanks, Paul, we are aware of the spurious ^0.  It will be resolved under bpo-25793.
