### ISSUE TITLE
Improve zipfile handling of corrupted extra field

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73960]
BPO | [29774](https://bugs.python.org/issue29774)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#583</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-09.16:48:24.053>
created_at = <Date 2017-03-09.15:27:35.689>
labels = ['3.7', 'type-feature', 'library']
title = 'Improve zipfile handling of corrupted extra field'
updated_at = <Date 2017-03-24.22:38:20.480>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:38:20.480>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-09.16:48:24.053>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-09.15:27:35.689>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29774
keywords = []
message_count = 4.0
messages = ['289302', '289307', '289311', '290249']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['583']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29774'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The zipfile module can raise struct.error when process corrupted extra field. This issue was partially resolved by bpo-14315. Following PR converts struct.error to BadZipFile in other case.

**Comment by vstinner** [comment]
I merged your PR, thanks!

I don't think that this minor enhancement on error message is worth it to be backported. It only impacts corrupted ZIP files, and 3.6 and older already raise an error message.

I updated manually the PR status, it seems like the GitHub bot is still broken.

**Comment by serhiy-storchaka** [comment]
I think the same.

**Comment by vstinner** [comment]
New changeset feccdb2a249a71be330765be77dee57121866779 by Victor Stinner (Serhiy Storchaka) in branch 'master':
bpo-29774: Improve error reporting for corrupted extra field in ZIP file. (#583)
https://github.com/python/cpython/commit/feccdb2a249a71be330765be77dee57121866779
