### ISSUE TITLE
Registration link sent via email by the tracker is http

### ISSUE THREAD

**Issue by 2636780d-49d5-42ba-91c2-9933afb6ce3b** [python/cpython#73971]
BPO | [29785](https://bugs.python.org/issue29785)
--- | :---
Nosy | @ezio-melotti

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ezio-melotti'
closed_at = <Date 2017-03-11.00:30:48.348>
created_at = <Date 2017-03-10.14:52:38.325>
labels = []
title = 'Registration link sent via email by the tracker is http'
updated_at = <Date 2017-03-11.00:55:19.554>
user = 'https://bugs.python.org/pep'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-11.00:55:19.554>
actor = 'pep.'
assignee = 'ezio.melotti'
closed = True
closed_date = <Date 2017-03-11.00:30:48.348>
closer = 'ezio.melotti'
components = ['Demos and Tools']
creation = <Date 2017-03-10.14:52:38.325>
creator = 'pep.'
dependencies = []
files = []
hgrepos = []
issue_num = 29785
keywords = []
message_count = 3.0
messages = ['289372', '289425', '289428']
nosy_count = 2.0
nosy_names = ['ezio.melotti', 'pep.']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29785'
versions = []
```

</p></details>

**Comment by 2636780d-49d5-42ba-91c2-9933afb6ce3b** [comment]
The link[1] sent via email by the tracker for registration confirmation is http, whereas https is already setup on the tracker itself.

Would it be possible to change it to https.

[1] http://bugs.python.org/?@action=confrego&otk=TOKEN

**Comment by ezio-melotti** [comment]
Could you report this to http://psf.upfronthosting.co.za/roundup/meta/ ?

**Comment by 2636780d-49d5-42ba-91c2-9933afb6ce3b** [comment]
On 11 March 2017 00:30:48 GMT+00:00, Ezio Melotti \<report@bugs.python.org\> wrote:
>
>Ezio Melotti added the comment:
>
>Could you report this to http://psf.upfronthosting.co.za/roundup/meta/
>?

No problem! Sorry for the noise
