### ISSUE TITLE
Convert some builtin types constructors to Argument Clinic

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#73979]
BPO | [29793](https://bugs.python.org/issue29793)
--- | :---
Nosy | @vstinner, @larryhastings, @serhiy-storchaka
PRs | <li>python/cpython#615</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-19.07:16:16.777>
created_at = <Date 2017-03-11.13:46:33.699>
labels = ['interpreter-core', 'type-feature', '3.7', 'expert-argument-clinic']
title = 'Convert some builtin types constructors to Argument Clinic'
updated_at = <Date 2017-03-24.22:08:44.617>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:08:44.617>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-19.07:16:16.777>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Argument Clinic']
creation = <Date 2017-03-11.13:46:33.699>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29793
keywords = []
message_count = 4.0
messages = ['289446', '289451', '289453', '290162']
nosy_count = 3.0
nosy_names = ['vstinner', 'larry', 'serhiy.storchaka']
pr_nums = ['615']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29793'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Following PR converts some builtin types constructors to Argument Clinic:

complex.\_\_new__
float.\_\_new__
function.\_\_new__
int.\_\_new__
mappingproxy.\_\_new__
module.\_\_init__
property.\_\_init__
structseq.\_\_new__

**Comment by vstinner** [comment]
Cool. You can close my issue, this one supersed it.

**Comment by serhiy-storchaka** [comment]
str, bytes and bytearray still are not converted.

**Comment by serhiy-storchaka** [comment]
New changeset 18b250f844bf8b2d1a81c2d2dcc74e850364fe35 by Serhiy Storchaka in branch 'master':
bpo-29793: Convert some builtin types constructors to Argument Clinic. (#615)
https://github.com/python/cpython/commit/18b250f844bf8b2d1a81c2d2dcc74e850364fe35
