### ISSUE TITLE
Erroneous link in shutil.copy description

### ISSUE THREAD

**Issue by 2636780d-49d5-42ba-91c2-9933afb6ce3b** [python/cpython#73970]
BPO | [29784](https://bugs.python.org/issue29784)
--- | :---
Nosy | @serhiy-storchaka, @zhangyangyu, @Mariatta
PRs | <li>python/cpython#601</li><li>python/cpython#602</li><li>python/cpython#608</li><li>python/cpython#609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-03-11.03:41:18.950>
created_at = <Date 2017-03-10.14:45:51.829>
labels = ['3.7', 'docs']
title = 'Erroneous link in shutil.copy description'
updated_at = <Date 2017-03-24.22:28:26.578>
user = 'https://bugs.python.org/pep'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:28:26.578>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-03-11.03:41:18.950>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-03-10.14:45:51.829>
creator = 'pep.'
dependencies = []
files = []
hgrepos = []
issue_num = 29784
keywords = []
message_count = 8.0
messages = ['289370', '289393', '289395', '289396', '289433', '290231', '290232', '290233']
nosy_count = 5.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'xiang.zhang', 'Mariatta', 'pep.']
pr_nums = ['601', '602', '608', '609']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29784'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 2636780d-49d5-42ba-91c2-9933afb6ce3b** [comment]
https://docs.python.org/3/library/shutil.html#shutil.copy

The link to "copy()" in the description seems to be pointing to the copy module, but I suppose it was meant to point at shutil.copy.

**Comment by zhangyangyu** [comment]
Thanks for your report, Maxime! I open PRs to fix it.

**Comment by zhangyangyu** [comment]
Assigned to Mariatta :-).

**Comment by serhiy-storchaka** [comment]
See also bpo-21818. I suspect there are other incorrect references.

**Comment by Mariatta** [comment]
Thanks all :)
I fixed the two references to copy() in shutil docs, and backported to 3.5 and 3.6.
Since this particular issue is fixed, I'm closing this. If people find other incorrect references, they can open another ticket.

**Comment by Mariatta** [comment]
New changeset 701f13ab930b62a634579951dc610f737f461135 by Mariatta in branch '3.6':
bpo-29784: Fix the reference to shutil.copy in the docs (GH-602) (GH-608)
https://github.com/python/cpython/commit/701f13ab930b62a634579951dc610f737f461135

**Comment by Mariatta** [comment]
New changeset 518d8fcb89896dd30fbf11c667ee4e6b509e4dd9 by Mariatta in branch '3.5':
bpo-29784: Fix the reference to shutil.copy in the docs (GH-602) (GH-609)
https://github.com/python/cpython/commit/518d8fcb89896dd30fbf11c667ee4e6b509e4dd9

**Comment by Mariatta** [comment]
New changeset 70ee0cd5c2a3dba82cb8e0c0742c012f9134c040 by Mariatta in branch 'master':
bpo-29784: Fix the reference to shutil.copy in the docs (GH-602)
https://github.com/python/cpython/commit/70ee0cd5c2a3dba82cb8e0c0742c012f9134c040
