### ISSUE TITLE
Internal importlib frames visible when module imported by import_module throws exception

### ISSUE THREAD

**Issue by ba0e35ee-9fbf-46aa-aa77-27d09fc7efc5** [python/cpython#73973]
BPO | [29787](https://bugs.python.org/issue29787)
--- | :---
Nosy | @brettcannon

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-13.16:50:33.810>
created_at = <Date 2017-03-10.15:50:57.826>
labels = ['type-bug', 'invalid']
title = 'Internal importlib frames visible when module imported by import_module throws exception'
updated_at = <Date 2017-03-14.16:22:18.380>
user = 'https://bugs.python.org/ulope'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-14.16:22:18.380>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-13.16:50:33.810>
closer = 'brett.cannon'
components = []
creation = <Date 2017-03-10.15:50:57.826>
creator = 'ulope'
dependencies = []
files = []
hgrepos = []
issue_num = 29787
keywords = []
message_count = 4.0
messages = ['289381', '289541', '289574', '289602']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'ulope']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29787'
versions = ['Python 3.6']
```

</p></details>

**Comment by ba0e35ee-9fbf-46aa-aa77-27d09fc7efc5** [comment]
Importing a module that raises an exception on import trough `importlib.import_module()` causes importlib to not strip it's internal frames from the traceback.


Minimal example:

--a.py--
import importlib

```py
importlib.import_module("b")
--a.py--
```



--b.py--
raise Exception()
--b.py--

```pytb
#~ python3.6 a.py
Traceback (most recent call last):
  File "a.py", line 3, in <module>
    importlib.import_module("b")
  File "/Users/ulo/.pythonz/pythons/CPython-3.6.0/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 978, in _gcd_import
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load
  File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "/Users/ulo/t/b.py", line 1, in <module>
    raise Exception()
Exception
```

**Comment by brettcannon** [comment]
That's because the frame-stripping trick is done through import.c which importlib.import_module() doesn't pass through. So thanks for the report, Ulrich, but it is working as expected and we won't be changing import_module() to pass through the C code to keep the C code to a minimum.

**Comment by ba0e35ee-9fbf-46aa-aa77-27d09fc7efc5** [comment]
Thanks for the fast response. 
However I disagree with the assertion that this is "working as expected". IMO the same arguments apply as in the original ticket (esp. Georg Brandls) http://bugs.python.org/issue15110#msg163258.

It is unexpected, confusing (esp. to newer devs) and adds a lot of (unnecessary) noise to tracebacks.

Also this basically demotes `import_module` to second rate league since it doesn't get to enjoy the niceties of "proper" import which is unfortunate since it's used heavily for example in django.

**Comment by brettcannon** [comment]
Yep, I agree it isn't as nice as syntactic import, but that can happen when you're not getting to use dedicated bytecode like syntactic import does.

If you can come up with a patch that adds hardly any more C code -- say about 10 or 20 lines? -- I would consider reviewing the patch.
