### ISSUE TITLE
print documentation: flush is also a keyword argument

### ISSUE THREAD

**Issue by 44e5505c-21d4-4aeb-8a54-37ebb523e067** [python/cpython#73977]
BPO | [29791](https://bugs.python.org/issue29791)
--- | :---
Nosy | @berkerpeksag, @Lucioric2000
PRs | <li>python/cpython#1093</li><li>python/cpython#1111</li><li>python/cpython#1112</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-13.13:17:49.281>
created_at = <Date 2017-03-10.21:06:33.249>
labels = ['type-bug', '3.7', 'docs']
title = 'print documentation: flush is also a keyword argument'
updated_at = <Date 2017-04-13.13:17:49.280>
user = 'https://github.com/Lucioric2000'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.13:17:49.280>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-13.13:17:49.281>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-03-10.21:06:33.249>
creator = 'Lucio Ricardo Montero Valenzuela'
dependencies = []
files = []
hgrepos = []
issue_num = 29791
keywords = []
message_count = 5.0
messages = ['289411', '291608', '291612', '291613', '291614']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'Lucio Ricardo Montero Valenzuela']
pr_nums = ['1093', '1111', '1112']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29791'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 44e5505c-21d4-4aeb-8a54-37ebb523e067** [comment]
In the print() function documentation (https://docs.python.org/3/library/functions.html#print), the first line says "Print objects to the text stream file, separated by sep and followed by end. sep, end and file, if present, must be given as keyword arguments.", but the function definition is said to be "print(*objects, sep=' ', end='\\n', file=sys.stdout, flush=False)". Based on the Python user function definition grammar, the only way of passing an value to a non-star parameters that appear after a star-parameter is with the keyword (so the interpreter knows not to push the value into the star-parameter list/mapping). So the flush parameter can be set only naming explicitly the keyword 'flush' ¿Isn't it?. So the first line of the print() function documentation should say "Print objects to the text stream file, separated by sep and followed by end. sep, end, file and flush, if present, must be given as keyword arguments.". Flush is a new parameter, so maybe you forgot to update this line of the documentation to include it.
Best regards.

**Comment by berkerpeksag** [comment]
New changeset 61b9ac93712df8092a25223cd56fa6528359792b by Berker Peksag in branch 'master':
bpo-29791: Clarify that flush is keyword-only argument (bpo-1093)
https://github.com/python/cpython/commit/61b9ac93712df8092a25223cd56fa6528359792b

**Comment by berkerpeksag** [comment]
New changeset df9783720e40773e7854d2f4e4cfc93f0a2c08b8 by Berker Peksag in branch '3.5':
bpo-29791: Clarify that flush is keyword-only argument (GH-1093)
https://github.com/python/cpython/commit/df9783720e40773e7854d2f4e4cfc93f0a2c08b8

**Comment by berkerpeksag** [comment]
New changeset 119d94ad37a99ecb0b8329467d04cd9d909e310e by Berker Peksag in branch '3.6':
bpo-29791: Clarify that flush is keyword-only argument (GH-1093)
https://github.com/python/cpython/commit/119d94ad37a99ecb0b8329467d04cd9d909e310e

**Comment by berkerpeksag** [comment]
Thanks for the report!
