### ISSUE TITLE
zipfile: Add absolute_path option, disabled by default

### ISSUE THREAD

**Issue by vstinner** [python/cpython#73975]
BPO | [29789](https://bugs.python.org/issue29789)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
Files | <li>[test2.zip](https://bugs.python.org/file46716/test2.zip "Uploaded as application/zip at 2017-03-10.16:36:40 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-10.16:36:40.795>
created_at = <Date 2017-03-10.16:14:54.985>
labels = ['type-security', 'invalid', '3.7', 'library']
title = 'zipfile: Add absolute_path option, disabled by default'
updated_at = <Date 2017-03-10.16:36:40.793>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-10.16:36:40.793>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-10.16:36:40.795>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-03-10.16:14:54.985>
creator = 'vstinner'
dependencies = []
files = ['46716']
hgrepos = []
issue_num = 29789
keywords = []
message_count = 3.0
messages = ['289389', '289391', '289392']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue29789'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Same issue than tarfile issue bpo-29788, but on zipfile.

I suggest to add a boolean absolute_path option to zipfile, disabled by default.

**Comment by serhiy-storchaka** [comment]
Is this issue exists on zipfile?

**Comment by vstinner** [comment]
Oh, it seems like zipfile is not affected by the issue, only tarfile. The documentation is correct:
https://docs.python.org/dev/library/zipfile.html#zipfile.ZipFile.extract

You can test using attached test2.zip.

haypo@selma$ python3 -m zipfile -l \~/test2.zip 
File Name                                             Modified             Size
/home/haypo/test                               2017-03-10 17:29:06            5

haypo@selma$ cd $HOME
haypo@selma$ rm -rf z/
haypo@selma$ mkdir z
haypo@selma$ cd z
haypo@selma$ python3 -m zipfile -e \~/test2.zip .
haypo@selma$ find
.
./home
./home/haypo
./home/haypo/test
haypo@selma$ cat \~/test
cat: /home/haypo/test: No such file or directory
