### ISSUE TITLE
Deadlock with multiprocessing.Queue()

### ISSUE THREAD

**Issue by bef3b989-2e47-4e9c-91d3-504408b50b75** [python/cpython#73983]
BPO | [29797](https://bugs.python.org/issue29797)
--- | :---
Nosy | @tim-one, @pkch, @eryksun, @applio

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-12.15:52:23.668>
created_at = <Date 2017-03-12.05:45:09.862>
labels = ['invalid', 'type-bug', 'library']
title = 'Deadlock with multiprocessing.Queue()'
updated_at = <Date 2017-03-12.15:52:23.667>
user = 'https://github.com/pkch'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-12.15:52:23.667>
actor = 'tim.peters'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-12.15:52:23.668>
closer = 'tim.peters'
components = ['Library (Lib)']
creation = <Date 2017-03-12.05:45:09.862>
creator = 'max'
dependencies = []
files = []
hgrepos = []
issue_num = 29797
keywords = []
message_count = 4.0
messages = ['289479', '289480', '289490', '289492']
nosy_count = 4.0
nosy_names = ['tim.peters', 'max', 'eryksun', 'davin']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29797'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
Using multiprocessing.Queue() with several processes writing very fast results in a deadlock both on Windows and UNIX.

For example, this code:

```py
from multiprocessing import Process, Queue, Manager
import time, sys

def simulate(q, n_results):
    for i in range(n_results):
        time.sleep(0.01)
        q.put(i)

def main():
    n_workers = int(sys.argv[1])
    n_results = int(sys.argv[2])

    q = Queue()
    proc_list = [Process(target=simulate, 
        args=(q, n_results),
        daemon=True) for i in range(n_workers)]

    for proc in proc_list:
        proc.start()

    for i in range(5):
        time.sleep(1)
        print('current approximate queue size:', q.qsize())
        alive = [p.pid for p in proc_list if p.is_alive()]
        if alive:
            print(len(alive), 'processes alive; among them:', alive[:5])
        else:
            break

    for p in proc_list:
        p.join()

    print('final appr queue size', q.qsize())


if __name__ == '__main__':
    main()
```



hangs on Windows 10 (python 3.6) with 2 workers and 1000 results each, and on Ubuntu 16.04 (python 3.5) with 100 workers and 100 results each. The print out shows that the queue has reached the full size, but a bunch of processes are still alive. Presumably, they somehow manage to lock themselves out even though they don't depend on each other (must be in the implementation of Queue()):

current approximate queue size: 9984
47 processes alive; among them: [2238, 2241, 2242, 2244, 2247]
current approximate queue size: 10000
47 processes alive; among them: [2238, 2241, 2242, 2244, 2247]

The deadlock disappears once multiprocessing.Queue() is replaced with multiprocessing.Manager().Queue() - or at least I wasn't able to replicate it with a reasonable number of processes and results.

**Comment by tim-one** [comment]
I think this is expected.  Add this as the first line of `simulate()` and the problem should go away:

```py
    q.cancel_join_thread()
```


As the docs say, a Queue works with a background thread, which feeds incoming data from an internal buffer to a (interprocess) pipe.  By default, a process using the Queue attempts to join that thread when the process exits.  But since you never take anything off the queue, the thread waits forever, hoping for the pipe to drain so it can feed in the rest of its buffer.

But see the docs for why you don't really want to use .cancel_join_thread():  the process will just exit then, and the data in the internal buffer will most likely simply be lost.

A Manager.Queue doesn't have this problem because it runs in its own (Manager) process:  q.put() sends the data to that process at once, without buffering anything.  So if you have write-only Queues, that's the way to go ;-)

**Comment by eryksun** [comment]
On Windows the "QueueFeederThread" in each child process is blocked in WaitForMultipleObjects in PipeConnection.\_send_bytes. The pipe buffer size is 8 KiB, and each pickled int is 5-6 bytes. With 2 processes the pipe is full after sending (256 + 469) * 2 == 1450 int objects. Joining this feeder thread waits until all of the data is sent, however long that takes. This appears to be working correctly as designed.

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
Yes, this makes sense. My bad, I didn't realize processes might need to wait until the queue is consumed.

I don't think there's any need to update the docs either, nobody should have production code that never reads the queue (mine was a test of some other issue).

**Comment by HarshGrandeur** [comment]
I have written a simple code using the docs, but it is getting stuck after the last iteration. The code works perfectly if we use less iterations.
```
from multiprocessing import Process, Queue
import os
import signal
def f(q):
    for i in range(10000):
        q.put([42, None, 'hello'])
        print("Iteration ", i , " " , os.getpid())
if __name__ == '__main__':
    q = Queue()
    p = Process(target=f, args=(q,))
    p.start()
    print(q.get())    # prints "[42, None, 'hello']"
    p.join(1)
```

**Comment by tim-one** [comment]
@HarshGrandeur, read the docs more carefully. You can't be this careless with a Queue :wink:. If you put something on it, some process needs to take it off, or the program may hang forever.


>Warning:
> As mentioned above, if a child process has put items on a queue (and it has not used [JoinableQueue.cancel_join_thread], then that process will not terminate until all buffered items have been flushed to the pipe.
 > This means that if you try joining that process you may get a deadlock unless you are sure that all items which have been put on the queue have been consumed. Similarly, if the child process is non-daemonic then the parent process may hang on exit when it tries to join all its non-daemonic children.
 > Note that a queue created using a manager does not have this issue. See [Programming guidelines]
