### ISSUE TITLE
Add tests for header API of 'urllib.request.Request' class

### ISSUE THREAD

**Issue by ecd7c7a5-9835-451b-b7a2-4836efc23815** [python/cpython#73985]
BPO | [29799](https://bugs.python.org/issue29799)
--- | :---
Nosy | @vadmium, @ultimatecoder, @iritkatriel
PRs | <li>python/cpython#643</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-14.20:09:10.937>
created_at = <Date 2017-03-12.12:49:16.501>
labels = ['3.7', 'type-feature', 'tests']
title = "Add tests for header API of 'urllib.request.Request' class"
updated_at = <Date 2021-06-14.20:09:10.936>
user = 'https://github.com/ultimatecoder'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-14.20:09:10.936>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-14.20:09:10.937>
closer = 'iritkatriel'
components = ['Tests']
creation = <Date 2017-03-12.12:49:16.501>
creator = 'jaysinh.shukla'
dependencies = []
files = []
hgrepos = []
issue_num = 29799
keywords = []
message_count = 3.0
messages = ['289515', '391230', '395846']
nosy_count = 3.0
nosy_names = ['martin.panter', 'jaysinh.shukla', 'iritkatriel']
pr_nums = ['643']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29799'
versions = ['Python 3.7']
```

</p></details>

**Comment by vadmium** [comment]
I think the RequestTests class really belongs in test_urllib2, which already has a RequestHdrsTests class testing these APIs.

BTW test_urllib.py (no 2) is mainly for testing the stuff that came from Python 2’s “urllib” module, but the Request class is in “urllib2” instead.
