### ISSUE TITLE
Incorrect error message on invalid __class__ assignments

### ISSUE THREAD

**Issue by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [python/cpython#73980]
BPO | [29794](https://bugs.python.org/issue29794)
--- | :---
Nosy | @stevendaprano, @pppery, @zhangyangyu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-12.02:15:13.986>
created_at = <Date 2017-03-11.16:00:21.239>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'Incorrect error message on invalid __class__ assignments'
updated_at = <Date 2017-03-12.02:15:13.970>
user = 'https://github.com/pppery'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-12.02:15:13.970>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-12.02:15:13.986>
closer = 'steven.daprano'
components = ['Interpreter Core']
creation = <Date 2017-03-11.16:00:21.239>
creator = 'ppperry'
dependencies = []
files = []
hgrepos = []
issue_num = 29794
keywords = []
message_count = 2.0
messages = ['289448', '289463']
nosy_count = 3.0
nosy_names = ['steven.daprano', 'ppperry', 'xiang.zhang']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29794'
versions = ['Python 3.6']
```

</p></details>

**Comment by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [comment]
If you try to set the \_\_class__ of a type which doesn't support "\_\_class__" assignments, you get the error message:

    TypeError: __class__ assignment only supported for heap types or ModuleType subclasses

However, the actual restriction doesn't require a subclass of "ModuleType"; the below code works:

```py
    import random
    class M(type(random)):pass
    random.__class__ = M
```


Thus the error message is incorrect.

**Comment by stevendaprano** [comment]
Your example works because random is a module:

py\> from types import ModuleType
py\> import random
py\> type(random) is ModuleType
True

Since random is an instance of ModuleType, your class M is a subclass of ModuleType, and assigning to random.\_\_class__ is allowed.

I'm closing this issue, but if can demonstrate an actual problem, please feel free to re-open it.
