### ISSUE TITLE
test for token.py, and consistency tests for tokenize.py

### ISSUE THREAD

**Issue by bitdancer** [python/cpython#73998]
BPO | [29812](https://bugs.python.org/issue29812)
--- | :---
Nosy | @bitdancer, @berkerpeksag, @serhiy-storchaka, @ammaraskar, @DimitrisJim
PRs | <li>python/cpython#681</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-12.02:22:57.482>
created_at = <Date 2017-03-14.23:03:41.823>
labels = ['3.7', 'easy', 'type-feature', 'tests']
title = 'test for token.py, and consistency tests for tokenize.py'
updated_at = <Date 2017-07-12.02:22:57.462>
user = 'https://github.com/bitdancer'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-12.02:22:57.462>
actor = 'ammar2'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-12.02:22:57.482>
closer = 'ammar2'
components = ['Tests']
creation = <Date 2017-03-14.23:03:41.823>
creator = 'r.david.murray'
dependencies = []
files = []
hgrepos = []
issue_num = 29812
keywords = ['easy']
message_count = 7.0
messages = ['289628', '289702', '289704', '297532', '297533', '297575', '298192']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'berker.peksag', 'serhiy.storchaka', 'ammar2', 'Jim Fasarakis-Hilliard']
pr_nums = ['681']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29812'
versions = ['Python 3.7']
```

</p></details>

**Comment by bitdancer** [comment]
http://bugs.python.org/issue24622 made reminded me that a while back we added tests for the keyword module that includes a test that if you run it, you get the result that is checked in.  The same thing could be done for the token.py module.  And then we could add a cross-check test that tokenize.py has all the symbols defined as well.

**Comment by ammaraskar** [comment]
This is my first real substantial testing change so I'd appreciate all feedback. The way I did the cross-check doesn't actually rely on any of the information from the test_keyword style regeneration test. 

I think this approach is a lot simpler, and will prevent mistakes like the one seen in http://bugs.python.org/issue24622

**Comment by bitdancer** [comment]
The cross check test itself doesn't depend on a regeneration, but it does depend on the information in token.h.  Meanwhile the validity of \*that* is checked by regeneration in your test_token tests.  This is exactly what I had in mind :).

So, I haven't done a full review, but the quick glance I took looked good.

**Comment by serhiy-storchaka** [comment]
See also bpo-30455. Don't these issues conflict one other?

**Comment by berkerpeksag** [comment]
Yes, they are. I like the idea of generating C files from [Lib/token.py](https://github.com/python/cpython/blob/main/Lib/token.py). Let's see what David thinks about bpo-30455.

**Comment by bitdancer** [comment]
I have no opinion on that issue.  I opened this issue to fix a hole in our validation, but if that hole no longer exists after that (subsequently opened :) issue is resolved, then this isn't needed (sorry, Ammar, and thank you for your work!)

**Comment by ammaraskar** [comment]
No problem, closing this in favor of bpo-30455.
