### ISSUE TITLE
Requesting version info with lowercase -v or -vv causes an import crash

### ISSUE THREAD

**Issue by e368e5ec-4a13-4787-ae33-47ac6128712a** [python/cpython#73992]
BPO | [29806](https://bugs.python.org/issue29806)
--- | :---
Nosy | @methane

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-14.03:33:57.587>
created_at = <Date 2017-03-14.03:18:20.697>
labels = ['invalid', 'docs']
title = 'Requesting version info with lowercase -v or -vv causes an import crash'
updated_at = <Date 2017-03-14.03:33:57.586>
user = 'https://bugs.python.org/AnneTheAgile'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-14.03:33:57.586>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-14.03:33:57.587>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-03-14.03:18:20.697>
creator = 'AnneTheAgile'
dependencies = []
files = []
hgrepos = []
issue_num = 29806
keywords = []
message_count = 2.0
messages = ['289561', '289562']
nosy_count = 3.0
nosy_names = ['methane', 'docs@python', 'AnneTheAgile']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29806'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by e368e5ec-4a13-4787-ae33-47ac6128712a** [comment]
In trying to test the new feature in 3.6.0, 
$ python -VV  # get more info than python -V or python --version 
I found several oddities. 

1.On both  Amazon Linux AMI Python 2.7.12 and also Anaconda Python 3.6.0, using lowercase v's causes a crash on some kind of import.

1a.AWS first lines are:
[ec2-user@ip-172-31-2-101 \~]$ python -v
\# installing zipimport hook
import zipimport # builtin
\# installed zipimport hook
\# /usr/lib64/python2.7/site.pyc matches /usr/lib64/python2.7/site.py
import site # precompiled from /usr/lib64/python2.7/site.pyc

1b.Conda first lines are:
(py36aws)me:tool-aws me$ python -v
import \_frozen_importlib # frozen
import \_imp # builtin
import sys # builtin
import '\_warnings' # \<class '\_frozen_importlib.BuiltinImporter'\>
//etc 

1c.In both cases, after lots of stuff, must quit python with 
quit()

2.Anaconda does not provide more information. Is that expected?
(py36aws) $ python -VV
Python 3.6.0 :: Continuum Analytics, Inc.
(py36aws)$ python -V
Python 3.6.0 :: Continuum Analytics, Inc.
(py36aws)$ python --version
Python 3.6.0 :: Continuum Analytics, Inc.

**Comment by methane** [comment]
> 1.On both  Amazon Linux AMI Python 2.7.12 and also Anaconda Python 3.6.0, using lowercase v's causes a crash on some kind of import.

Lowercase -v is not version, it's "verbose". and -vv is "very verbose".
So it's not crash, just a verbose message about importing.

> 2.Anaconda does not provide more information. Is that expected?

output of -V and -VV is implementation detail.  No standard format is specified by Python language.
PyPy has different output too.
