### ISSUE TITLE
ArgParse page in library reference rewrite

### ISSUE THREAD

**Issue by 05014b7d-d21c-41f2-9248-6baf305018c5** [python/cpython#73993]
BPO | [29807](https://bugs.python.org/issue29807)
--- | :---
Nosy | @vadmium, @sweavo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-14.06:18:04.353>
labels = ['docs']
title = 'ArgParse page in library reference rewrite'
updated_at = <Date 2017-03-14.10:09:55.966>
user = 'https://github.com/sweavo'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-14.10:09:55.966>
actor = 'martin.panter'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-03-14.06:18:04.353>
creator = 'sweavo'
dependencies = []
files = []
hgrepos = []
issue_num = 29807
keywords = []
message_count = 2.0
messages = ['289569', '289576']
nosy_count = 3.0
nosy_names = ['docs@python', 'martin.panter', 'sweavo']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29807'
versions = ['Python 2.7']
```

</p></details>

**Comment by 05014b7d-d21c-41f2-9248-6baf305018c5** [comment]
Originally raise as https://github.com/python/pythondotorg/issues/1059

Although it's a reference page, it is clouded by too many examples and too little reference material. Moreover, the examples are not real-world applications of argument parsing.

I propose removing the "process some integers" example, replacing it with something more typically gnu style, e.g., myapp.py [--quiet] [--log-level \_n_] [--title=STR] {get | put} [FSPEC [, FSPEC...]]. This shows the user how to to many of the common command-line tasks.

[I'm tentatively offering to do this, but I haven't yet found the content I need to revise.]

**Comment by vadmium** [comment]
Also see bpo-26602 and bpo-11176, each with patches. Perhaps you could help review and combine them.

**Comment by savannahostrowski** [comment]
The argparse documentation was recently reworked quite significantly (see https://github.com/python/cpython/issues/124478) and many examples were removed in favour of leaning more heavily on the existing tutorial (including the original intro tutorial about processing integers). I am going to close this for now since this issue is quite old, but happy to revisit if we have additional aspects we'd like to address.
