### ISSUE TITLE
SyslogHandler: should not raise exception in constructor if connection fails

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#73994]
BPO | [29808](https://bugs.python.org/issue29808)
--- | :---
Nosy | @vsajip, @socketpair, @Mariatta
PRs | <li>python/cpython#663</li><li>python/cpython#695</li><li>python/cpython#696</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.15:27:08.639>
created_at = <Date 2017-03-14.09:36:41.420>
labels = ['3.7', 'type-bug', 'library']
title = 'SyslogHandler: should not raise exception in constructor if connection fails'
updated_at = <Date 2017-05-10.11:12:11.263>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.11:12:11.263>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-17.15:27:08.639>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-03-14.09:36:41.420>
creator = 'socketpair'
dependencies = []
files = []
hgrepos = []
issue_num = 29808
keywords = []
message_count = 13.0
messages = ['289573', '289609', '289611', '289627', '289635', '289762', '289765', '289768', '290168', '290169', '290171', '293391', '293401']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'socketpair', 'Mariatta']
pr_nums = ['663', '695', '696']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29808'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
Syslog handler already able to ignore temporary errors while seding logs. So he knows that syslog server may be not reachable at the moment. But when we say about constructor, it fails with error. I have fixed that -- now it will ignore such errors, and try to re-connect on every logging as it was before. C's version does the same.

**Comment by vsajip** [comment]
Can you provide a short script which demonstrates exactly the problem you're trying to solve?

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
Nothing special. Just try to create SysLogHandler when syslog server is down. Exception will be raised.

**Comment by vsajip** [comment]
> Nothing special. Just try to create SysLogHandler when syslog server is down.

Which specific syslog configuration? UDP listener, Unix socket listener, or both?

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
Syslog, listening on local machine via UNIX socket.

**Comment by Mariatta** [comment]
Does this need backport into 3.5 and 3.6?

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
Yes, I want this simple patch to be back-ported. We use Python 3.5 in our projects.

**Comment by vsajip** [comment]
Sorry, I was a bit too hasty closing the issue.

**Comment by vsajip** [comment]
New changeset e59af55c28b657cdf57c71a7b0837c9e9f4b2a31 by Vinay Sajip in branch '3.5':
bpo-29808: Do not fail in SysLogHandler constructor if syslog isn't available. (#695)
https://github.com/python/cpython/commit/e59af55c28b657cdf57c71a7b0837c9e9f4b2a31

**Comment by vsajip** [comment]
New changeset 46e81d3345b979f835740a228857906dca0f59c0 by Vinay Sajip in branch '3.6':
bpo-29808: Do not fail in SysLogHandler constructor if syslog isn't available. (#696)
https://github.com/python/cpython/commit/46e81d3345b979f835740a228857906dca0f59c0

**Comment by vsajip** [comment]
New changeset 1b038e073807ecb6fd176edaf3386a8e3205416e by Vinay Sajip (Коренберг Марк) in branch 'master':
bpo-29808: SysLogHandler: Do not fail if initial connect to syslog failed (#663) (#663)
https://github.com/python/cpython/commit/1b038e073807ecb6fd176edaf3386a8e3205416e

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
@vinay.sajip

I don't see this change in Python 3.5.3:

https://github.com/python/cpython/blob/v3.5.3/Lib/logging/handlers.py#L806

How can this be true?

**Comment by vsajip** [comment]
> How can this be true?

Perhaps it didn't make the cut for that specific release? Seems to be in the 3.5 branch OK.
