### ISSUE TITLE
PyTuple_GetSlice does not always return a new tuple

### ISSUE THREAD

**Issue by 84dd73fe-9313-425f-aae0-390228a90839** [python/cpython#73999]
BPO | [29813](https://bugs.python.org/issue29813)
--- | :---
Nosy | @rhettinger, @zhangyangyu, @MSeifert04

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-15.04:25:20.848>
created_at = <Date 2017-03-15.02:40:50.677>
labels = ['type-bug', 'invalid', 'docs']
title = 'PyTuple_GetSlice does not always return a new tuple'
updated_at = <Date 2017-03-16.02:53:00.626>
user = 'https://github.com/MSeifert04'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-16.02:53:00.626>
actor = 'MSeifert'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-15.04:25:20.848>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-03-15.02:40:50.677>
creator = 'MSeifert'
dependencies = []
files = []
hgrepos = []
issue_num = 29813
keywords = []
message_count = 5.0
messages = ['289632', '289636', '289638', '289639', '289703']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'xiang.zhang', 'MSeifert']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29813'
versions = []
```

</p></details>

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
The PyTuple_GetSlice documentation says it "Take a slice of the tuple pointed to by p from low to high and return it as a new tuple." [0] However in case the start is \<= 0 and the stop is \>= tuplesize it doesn't return the promised "new tuple", it just returns the tuplepointer after incrementing it's refcount [1].

The behaviour is fine (it gave me a bit of a headache though), however could a note/warning/sentence be included in the docs mentioning that special case?

[0] https://docs.python.org/3/c-api/tuple.html#c.PyTuple_GetSlice
[1] https://github.com/python/cpython/blob/master/Objects/tupleobject.c#L414

**Comment by zhangyangyu** [comment]
I think the description is fine. :-( What leads to your headache?

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
> What leads to your headache?

That depending on the arguments to "PyTuple_GetSlice" I get "SystemError: ..\\Objects\\tupleobject.c:156: bad argument to internal function" when using PyTuple_SetItem on the (supposedly) new tuple. 

Maybe I just misunderstood the word "new" in the documentation. :-)

**Comment by rhettinger** [comment]
I think the docs are fine as-is.  Whether an identical tuple is new or not is an implementation detail.

IMO, the docs would create more confusion by trying to over-explain, "slicing of tuples always returns a new tuple when the result tuple is distinct from the original; however, in the case where the result tuple is not distinct, the implementation is at liberty to return the original tuple instead of a new tuple.  Since tuples are immutable, this should make no difference at all to the user."

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
I rather thought about something along the lines of: "Take a slice of the tuple pointed to by \*p* from \*low* to \*high* and return it as a tuple. Whether the returned tuple is new or not is an implementation detail (and may depend on the value of the arguments)." Because from the point of the C-API tuples aren't immutable, at least not if they are new (refcount 1).

Thank you both for your feedback. I'll leave it closed as "not a bug", I got the point about over-explaining. :)
