### ISSUE TITLE
TypeError in traceback.print_exc - unicode does not have the buffer interface

### ISSUE THREAD

**Issue by jaraco** [python/cpython#73995]
BPO | [29809](https://bugs.python.org/issue29809)
--- | :---
Nosy | @jaraco, @vstinner, @ezio-melotti, @vadmium, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-14.22:35:24.580>
created_at = <Date 2017-03-14.14:29:49.482>
labels = ['library', 'expert-unicode']
title = 'TypeError in traceback.print_exc - unicode does not have the buffer interface'
updated_at = <Date 2017-03-15.01:04:48.566>
user = 'https://github.com/jaraco'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-15.01:04:48.566>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-14.22:35:24.580>
closer = 'jaraco'
components = ['Library (Lib)', 'Unicode']
creation = <Date 2017-03-14.14:29:49.482>
creator = 'jaraco'
dependencies = []
files = []
hgrepos = []
issue_num = 29809
keywords = []
message_count = 7.0
messages = ['289592', '289597', '289598', '289599', '289625', '289626', '289631']
nosy_count = 5.0
nosy_names = ['jaraco', 'vstinner', 'ezio.melotti', 'martin.panter', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29809'
versions = ['Python 2.7']
```

</p></details>

**Comment by jaraco** [comment]
I'm writing a routine that captures exceptions and logs them to a database. In doing so, I encountered a situation that when parsing a Unicode file that has an IndentationError (SyntaxError), print_exc will fail when it tries to render the unicode line. Here's a script that replicates the failure.

\# coding: utf-8

```py
from __future__ import unicode_literals

import io
import sys
import traceback

PY3 = sys.version_info > (3,)

print(sys.version)

buffer = io.StringIO() if PY3 else io.BytesIO()
```


try:
	args = str('\<tokenize\>'), 7, 2, '  // test'
	raise IndentationError('failed', args)
except Exception:
	traceback.print_exc(file=buffer)


And the output


```pytb
$ python2 test-unicode-tb.py       
2.7.13 (default, Dec 24 2016, 21:20:02) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
Traceback (most recent call last):
  File "test-unicode-tb.py", line 19, in <module>
    traceback.print_exc(file=buffer)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 233, in print_exc
    print_exception(etype, value, tb, limit, file)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 128, in print_exception
    _print(file, line, '')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/traceback.py", line 13, in _print
    file.write(str+terminator)
TypeError: 'unicode' does not have the buffer interface
```



The same test runs without error on Python 3. It's surprising to me that I'm the first person to encounter this issue. Is it possible I'm abusing the tokenize module and a unicode value shouldn't be present in the args for the IndentationError?

**Comment by jaraco** [comment]
A complimentary error will occur on Python 3 if a bytes member exists in the SyntaxError, though I suspect that would be an invalid usage.

**Comment by serhiy-storchaka** [comment]
format_exception_only() produces a Unicode string for SyntaxError with Unicode source line.

```pycon
>>> traceback.format_exception_only(SyntaxError, SyntaxError('failed', ('<tokenize>', 7, 2, u'  // test')))
['  File "<tokenize>", line 7\n', u'    // test\n', '    ^\n', 'SyntaxError: failed\n']
```


But io.BytesIO() accepts only binary strings.

The similar issue is caused by Unicode file name:

```pycon
>>> traceback.format_exception_only(SyntaxError, SyntaxError('failed', (u'<tokenize>', 7, 2, '  // test')))
[u'  File "<tokenize>", line 7\n', '    // test\n', '    ^\n', 'SyntaxError: failed\n']
```


But Unicode error message doesn't produce Unicode output:

```pycon
>>> traceback.format_exception_only(SyntaxError, SyntaxError(u'failed', ('<tokenize>', 7, 2, '  // test')))
['  File "<tokenize>", line 7\n', '    // test\n', '    ^\n', 'SyntaxError: failed\n']
```


How you got a Unicode source line in SyntaxError?

**Comment by vstinner** [comment]
sys.stderr.write() accepts Unicode (encoded to sys.stderr.encoding), whereas io.BytesIO.write() requires bytes:

```pycon
>>> import sys; sys.stderr.write(u'\xe9\n')
é

>>> import io; io.BytesIO().write(u'\xe9\n')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'unicode' does not have the buffer interface
```



You should write an helper function (class with a write method) encoding Unicode strings.


> The same test runs without error on Python 3.

Yeah, it's now time to upgrade to Python 3 ;-)

**Comment by jaraco** [comment]
> How you got a Unicode source line in SyntaxError?

Good question. Took me a while to replicate the exact conditions, but here's an example:

#coding: utf-8

```py
from __future__ import unicode_literals

import tokenize
import io

code = """
   //
  //
"""
buf = io.StringIO(code)
```


try:
  list(tokenize.generate_tokens(buf.readline))
except Exception as exc:
  print(exc.args)


It outputs:
('unindent does not match any outer indentation level', ('\<tokenize\>', 3, 2, u'  //\\n'))


> Yeah, it's now time to upgrade to Python 3 ;-)

Love to. Currently, we're blocked in that our code relies on SimpleParse, which doesn't support Python 3.


> You should write an helper function (class with a write method) encoding Unicode strings.


Good idea. I was pondering what I might use as a workaround and your suggestion sounds suitable. I'll report back how well that works.

**Comment by jaraco** [comment]
As a workaround, I wrapped BytesIO thus and it works for our needs.

```py
class LenientIO(io.BytesIO):
    """
    A version of BytesIO that can accept unicode or
    bytes. See http://bugs.python.org/issue29809
    """
    def write(self, value):
        if isinstance(value, six.text_type):
            value = value.encode('utf-8')
        super(LenientIO, self).write(value)
```



I'll recommend we close as wontfix, given the limited impact, unless it's demonstrated elsewhere.

**Comment by vadmium** [comment]
FWIW I tend to use cStringIO.StringIO as a Python 2 replacement for io.StringIO to avoid this str vs unicode problem. But that only accepts ASCII, so won't help you if you really need the UTF-8 encoding step.
