### ISSUE TITLE
Broken link to "GUI Programming with Python: QT Edition" book

### ISSUE THREAD

**Issue by c6a24554-5737-4174-b47e-54fc0403b8dc** [python/cpython#74006]
BPO | [29820](https://bugs.python.org/issue29820)
--- | :---
Nosy | @marco-buttu, @Mariatta
PRs | <li>python/cpython#685</li><li>python/cpython#688</li><li>python/cpython#689</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.02:59:08.576>
created_at = <Date 2017-03-15.15:29:20.917>
labels = ['easy', '3.7', 'docs']
title = 'Broken link to "GUI Programming with Python: QT Edition" book'
updated_at = <Date 2017-03-24.22:18:08.766>
user = 'https://github.com/marco-buttu'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:18:08.766>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-17.02:59:08.576>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-03-15.15:29:20.917>
creator = 'marco.buttu'
dependencies = []
files = []
hgrepos = []
issue_num = 29820
keywords = ['easy']
message_count = 8.0
messages = ['289678', '289680', '289720', '289724', '289743', '290176', '290177', '290178']
nosy_count = 3.0
nosy_names = ['docs@python', 'marco.buttu', 'Mariatta']
pr_nums = ['685', '688', '689']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29820'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
In [*] the link to "GUI Programming with Python: QT Edition by Boudewijn Rempt", does not work.  I did not find an official web page for this book, but it is really outdated (2002), so maybe we can take only the reference to the Mark Summerfield's book, about PyQt4.  Let me know, so in case I will open a PR.


[*] https://docs.python.org/3/library/othergui.html

**Comment by Mariatta** [comment]
Maybe instead of referencing to the books, we add reference to the wiki
https://wiki.python.org/moin/PyQt

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
Hi Mariatta, all the other seealso entries (PyGObject, PySide, ...) have references to some specific books and tutorials.  No one has a reference to the wiki, maybe because there is already a reference to it (at the end of the page).  IMHO we can keep the PyQt description consistent with the other GUIs descriptions, and we can fix the broken URL just removing the reference to the outdated book.  What do you think?

**Comment by Mariatta** [comment]
Thanks, Marco. That sounds good. Let's just remove the reference to the books from both PyQt and wxPython.

**Comment by Mariatta** [comment]
Thanks Marco :) I merged your PR, and backported to 3.5 and 3.6.

There are some merge conflict with the 2.7 branch, so I decided not to bother with it.

**Comment by Mariatta** [comment]
New changeset 3fce38c540681a736b7e5ca7611758f7bc159c9e by Mariatta in branch '3.6':
bpo-29820: othergui.rst: Remove outdated information  (GH-685) (GH-688)
https://github.com/python/cpython/commit/3fce38c540681a736b7e5ca7611758f7bc159c9e

**Comment by Mariatta** [comment]
New changeset 091d90f9a429b81b046cb83582062941f8ded9da by Mariatta in branch '3.5':
bpo-29820: othergui.rst: Remove outdated information  (GH-685) (GH-689)
https://github.com/python/cpython/commit/091d90f9a429b81b046cb83582062941f8ded9da

**Comment by Mariatta** [comment]
New changeset 1bb0f3762ec5104014aeed0ae6e9d64598d8fcac by Mariatta (Marco Buttu) in branch 'master':
bpo-29820: othergui.rst: Remove outdated information  (GH-685)
https://github.com/python/cpython/commit/1bb0f3762ec5104014aeed0ae6e9d64598d8fcac
