### ISSUE TITLE
mimetypes guesses XSL mimetype when passed an XML file

### ISSUE THREAD

**Issue by 05211b49-0e65-422f-bde2-06871ee0eebf** [python/cpython#74009]
BPO | [29823](https://bugs.python.org/issue29823)
--- | :---
Nosy | @vadmium
Superseder | <li>bpo-1043134: Add preferred extensions for MIME types</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-08.22:17:56.816>
created_at = <Date 2017-03-16.03:53:24.638>
labels = ['3.7', 'library']
title = 'mimetypes guesses XSL mimetype when passed an XML file'
updated_at = <Date 2017-05-08.22:17:56.815>
user = 'https://bugs.python.org/AlekseyBilogur'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-08.22:17:56.815>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-08.22:17:56.816>
closer = 'martin.panter'
components = ['Library (Lib)']
creation = <Date 2017-03-16.03:53:24.638>
creator = 'Aleksey Bilogur'
dependencies = []
files = []
hgrepos = []
issue_num = 29823
keywords = []
message_count = 2.0
messages = ['289705', '289706']
nosy_count = 2.0
nosy_names = ['martin.panter', 'Aleksey Bilogur']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1043134'
type = None
url = 'https://bugs.python.org/issue29823'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 05211b49-0e65-422f-bde2-06871ee0eebf** [comment]
Copied over from an unanswered StackOverflow thread (http://stackoverflow.com/questions/42542433/why-does-python-mimetype-guess-xsl-when-passed-an-xml-file):

When passed a file with a mimetype application/xml, the Python std lib mimetypes.guess_extension method guesses an .xsl extension. This is actually hard-coded in.

This seems wrong to me. But what do I know?

**Comment by vadmium** [comment]
Perhaps a duplicate of bpo-1043134?
