### ISSUE TITLE
inspect.isabstract does not work on abstract base classes during __init_subclass__

### ISSUE THREAD

**Issue by b1c60934-e65c-4706-a995-f91319cd0592** [python/cpython#74008]
BPO | [29822](https://bugs.python.org/issue29822)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka, @1st1, @ilevkivskyi, @Soares
PRs | <li>python/cpython#678</li><li>python/cpython#1979</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-07.04:22:59.935>
created_at = <Date 2017-03-15.17:06:09.728>
labels = ['3.7', 'type-bug', 'library']
title = 'inspect.isabstract does not work on abstract base classes during __init_subclass__'
updated_at = <Date 2017-06-07.04:22:59.934>
user = 'https://github.com/Soares'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-07.04:22:59.934>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-07.04:22:59.935>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-15.17:06:09.728>
creator = 'So8res'
dependencies = []
files = []
hgrepos = []
issue_num = 29822
keywords = []
message_count = 8.0
messages = ['289682', '289788', '289793', '289794', '289823', '292231', '295313', '295314']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'serhiy.storchaka', 'yselivanov', 'levkivskyi', 'So8res']
pr_nums = ['678', '1979']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29822'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b1c60934-e65c-4706-a995-f91319cd0592** [comment]
Here's an example test that fails:

```py
def test_isabstract_during_init_subclass(self):
    from abc import ABCMeta, abstractmethod

    isabstract_checks = []

    class AbstractChecker(metaclass=ABCMeta):
        def __init_subclass__(cls):
            abstract_checks.append(inspect.isabstract(cls))

    class AbstractClassExample(AbstractChecker):

        @abstractmethod
        def foo(self):
            pass

    class ClassExample(AbstractClassExample):
        def foo(self):
            pass

    self.assertEqual(isabstract_checks, [True, False])
```


To run the test, you'll need to be on a version of python where bpo-29581 is fixed (e.g., a cpython branch with https://github.com/python/cpython/pull/527 merged) in order for \_\_init_subclass__ to work with ABCMeta at all in the first place. I have a simple patch to inspect.isabstract that fixes this, and will make a PR shortly.

**Comment by ilevkivskyi** [comment]
Serhiy, sorry for a distraction, but it looks like here is one more situation where inspect.isabstract is problematic, similar to what was discussed in http://bugs.python.org/issue29638 recently.

**Comment by serhiy-storchaka** [comment]
Is this an alternate fix of bpo-29638?

**Comment by b1c60934-e65c-4706-a995-f91319cd0592** [comment]
I didn't know about bpo-29638, and I'm not sure whether my PR fixes it. Looking at that bug, I don't think that my PR would fix it, because I still trust TPFLAGS_IS_ABSTRACT when \_\_abstractmethods__ exists. That said, I'm not clear on how the cache works, so it's possible that my PR would fix 29638.

My issue appears when one uses py3.6's new \_\_init_subclass__ hook with an ABC. \_\_init_subclass__ is run by type.\_\_new__, which means that, as of py3.6, users can (in a natural/reasonable way) inspect ABCMeta classes before ABCMeta.\_\_new__ finishes executing. I didn't see any reasonable way to have ABCMeta.\_\_new__ finish setting up the ABC before calling super().\_\_new__, so I figured the fix should go into inspect.isabstract. But there may be better solutions I just didn't think of.

**Comment by serhiy-storchaka** [comment]
LGTM, but would be nice if Yury and Nick take a look.

**Comment by serhiy-storchaka** [comment]
New changeset fcfe80ec2592fed8b3941c79056a8737abef7d3b by Serhiy Storchaka (Nate) in branch 'master':
bpo-29822: Make inspect.isabstract() work during \_\_init_subclass__. (#678)
https://github.com/python/cpython/commit/fcfe80ec2592fed8b3941c79056a8737abef7d3b

**Comment by serhiy-storchaka** [comment]
New changeset 09b6c0c71ea944f7e8b46998f3ebaf5b9fbe15f6 by Serhiy Storchaka (Nate) in branch '3.6':
[3.6] bpo-29822: make inspect.isabstract() work during \_\_init_subclass__ (bpo-1979)
https://github.com/python/cpython/commit/09b6c0c71ea944f7e8b46998f3ebaf5b9fbe15f6

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Nate.
