### ISSUE TITLE
Get rid of C limitation for shift count in right shift

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74002]
BPO | [29816](https://bugs.python.org/issue29816)
--- | :---
Nosy | @mdickinson, @vstinner, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#680</li><li>python/cpython#1258</li>
Files | <li>[patchDraft1.diff](https://bugs.python.org/file46727/patchDraft1.diff "Uploaded as text/plain at 2017-03-15.21:00:49 by @orenmn"): a patch draft for reference only. also handles big positive ints</li><li>[long-shift-overflow-long-long.diff](https://bugs.python.org/file46747/long-shift-overflow-long-long.diff "Uploaded as text/plain at 2017-03-20.19:02:18 by @serhiy-storchaka")</li><li>[long-shift-overflow-divrem1.diff](https://bugs.python.org/file46748/long-shift-overflow-divrem1.diff "Uploaded as text/plain at 2017-03-20.19:02:33 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-30.07:00:24.059>
created_at = <Date 2017-03-15.08:55:17.278>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Get rid of C limitation for shift count in right shift'
updated_at = <Date 2017-04-22.18:50:11.618>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-22.18:50:11.618>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-30.07:00:24.059>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-15.08:55:17.278>
creator = 'serhiy.storchaka'
dependencies = []
files = ['46727', '46747', '46748']
hgrepos = []
issue_num = 29816
keywords = ['patch']
message_count = 19.0
messages = ['289650', '289651', '289652', '289654', '289658', '289660', '289662', '289692', '289697', '289751', '289767', '289878', '289898', '289984', '290011', '290012', '290824', '290826', '292133']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'vstinner', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['680', '1258']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29816'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Currently the value of right operand of the right shift operator is limited by C Py_ssize_t type.

```pycon
>>> 1 >> 10**100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
>>> (-1) >> 10**100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
>>> 1 >> -10**100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
>>> (-1) >> -10**100
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
```


But this is artificial limitation. Right shift can be extended to support arbitrary integers. `x >> very_large_value` should be 0 for non-negative x and -1 for negative x. `x >> negative_value` should raise ValueError.

```pycon
>>> 1 >> 10
0
>>> (-1) >> 10
-1
>>> 1 >> -10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative shift count
>>> (-1) >> -10
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: negative shift count
```

**Comment by vstinner** [comment]
If we change something, I suggest to be consistent with lshift. I expect a memory error on "1 \<\< (1 \<\< 1024)" (no unlimited loop before a global system collapse please ;-))

**Comment by vstinner** [comment]
FYI I saw recently that the C limitation of len() was reported in the "owasp-pysec" project:
https://github.com/ebranca/owasp-pysec/wiki/Overflow-in-len-function

I don't understand what such "deliberate" limitation was reported in a hardened CPython project?

**Comment by serhiy-storchaka** [comment]
> If we change something, I suggest to be consistent with lshift. I expect a memory error on "1 \<\< (1 \<\< 1024)" (no unlimited loop before a global system collapse please ;-))

I agree that left shift should raise an ValueError rather than OverflowError for large negative shifts. But is hard to handle large positive shifts. `1 << count` consumes `count*2/15` bytes of memory. There is a gap between the maximal value of bits represented as Py_ssize_t (PY_SSIZE_T_MAX) and the number of bits of maximal Python int (PY_SSIZE_T_MAX*15/2). _PyLong_NumBits() starves from the same issue. I think an OverflowError is appropriate here for denoting the platform and implementation limitation.

**Comment by serhiy-storchaka** [comment]
This may be a part of this issue or a separate issue: bytes(-1) raises a ValueError, but bytes(-10\*\*100) raises an OverflowError.

**Comment by vstinner** [comment]
> I think an OverflowError is appropriate here for denoting the platform and implementation limitation.

It's common that integer overflow on memory allocation in C code raises a MemoryError, not an OverflowError.

```pycon
>>> "x" * (2**60)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
MemoryError
```


I suggest to raise a MemoryError.

**Comment by serhiy-storchaka** [comment]
This is not MemoryError. On 32-bit platform `1 << (sys.maxsize + 1)` raises an OverflowError, but `1 << sys.maxsize << 1` can be calculated.

**Comment by serhiy-storchaka** [comment]
Unfortunately it is hard to totally avoid OverflowError in right shift. Righ shift of huge positive value can get non-zero result even if shift count is larger than PY_SSIZE_T_MAX. [PR 680](https://github.com/python/cpython/pull/680) just decreases the opportunity of getting a OverflowError.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
i played a little with a patch earlier today, but stopped because I
am short on time.

anyway, just in case my code is not totally rubbish, I attach my
patch draft, which should avoid OverflowError also for big positive
ints.

(of course, I don't suggest to use my code instead of [PR 680](https://github.com/python/cpython/pull/680). I just
put it here in case it might be useful for someone.)

(on my Windows 10, it passed some manual tests by me, and the test
module (except for test_venv, which fails also without the patch))

**Comment by serhiy-storchaka** [comment]
Thank you Oren, but your code doesn't work when PY_SSIZE_T_MAX \< b \< PY_SSIZE_T_MAX * PyLong_SHIFT and a \> 2 ** b. When you drop wordshift and left only loshift_d you should drop lower wordshift digits in a.

The code for left shift would be even more complex.

**Comment by serhiy-storchaka** [comment]
Updated PR. Now OverflowError is never raised if the result is representable.

Mark, could you please make a review?

**Comment by mdickinson** [comment]
> Mark, could you please make a review?

I'll try to find time this week. At least in principle, the change sounds good to me.

**Comment by serhiy-storchaka** [comment]
Here are two patches. The first uses C long long arithmetic (it corresponds current [PR 680](https://github.com/python/cpython/pull/680)), the second uses PyLong arithmetic. What is easier to read and verify?

**Comment by mdickinson** [comment]
I much prefer the `divrem1`-based version: it makes fewer assumptions about relative sizes of long / long long / size_t and about the number of bits per digit. I'd rather not have another place that would have to be carefully examined in the future if the number of bits per digit changed again. Overall, [Objects/longobject.c](https://github.com/python/cpython/blob/main/Objects/longobject.c) is highly portable, and I'd like to keep it that way as much as possible.

**Comment by serhiy-storchaka** [comment]
Updated the PR to divrem1-based version. The drawback is that divrem1 can fail with MemoryError while C long long arithmetic always works for integers of the size less than 1 exbibyte.

**Comment by serhiy-storchaka** [comment]
The special case would be not needed if limit Python ints on 32-bit platforms to approximately 2\*\*2\*\*28. int.bit_length() could be simpler too.

**Comment by serhiy-storchaka** [comment]
New changeset 918403cfc3304d27e80fb792357f40bb3ba69c4e by Serhiy Storchaka in branch 'master':
bpo-29816: Shift operation now has less opportunity to raise OverflowError. (#680)
https://github.com/python/cpython/commit/918403cfc3304d27e80fb792357f40bb3ba69c4e

**Comment by serhiy-storchaka** [comment]
Thank you for your review Mark.

**Comment by serhiy-storchaka** [comment]
New changeset 997a4adea606069e01beac6269920709db3994d1 by Serhiy Storchaka in branch 'master':
Remove outdated note about constraining of the bit shift right operand. (bpo-1258)
https://github.com/python/cpython/commit/997a4adea606069e01beac6269920709db3994d1
