### ISSUE TITLE
Fail at divide a negative integer number for a positive integer number

### ISSUE THREAD

**Issue by d5ee8318-5b63-4978-ba91-52c15b0c15af** [python/cpython#74001]
BPO | [29815](https://bugs.python.org/issue29815)
--- | :---
Nosy | @vadmium, @eryksun, @thomazs

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-15.10:39:48.842>
created_at = <Date 2017-03-15.07:56:40.440>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'Fail at divide a negative integer number for a positive integer number'
updated_at = <Date 2017-03-15.10:39:48.839>
user = 'https://github.com/thomazs'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-15.10:39:48.839>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-15.10:39:48.842>
closer = 'eryksun'
components = ['Interpreter Core']
creation = <Date 2017-03-15.07:56:40.440>
creator = 'marcosthomazs'
dependencies = []
files = []
hgrepos = []
issue_num = 29815
keywords = []
message_count = 6.0
messages = ['289647', '289648', '289655', '289656', '289659', '289665']
nosy_count = 3.0
nosy_names = ['martin.panter', 'eryksun', 'marcosthomazs']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29815'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by d5ee8318-5b63-4978-ba91-52c15b0c15af** [comment]
At divide a negative integer number for a positive integer number, the result is wrong. For example, in operation:

a, b, c = -7, 2, 7
d = divmod(a, b)
print a//b, a%b, c[0], c // b, c%b

The values printed are -4  1 3 1

**Comment by vadmium** [comment]
If you ignore the c[0] argument, the rest looks fine to me. See the documentation at \<https://docs.python.org/2/reference/expressions.html#binary-arithmetic-operations\> and \<https://docs.python.org/2/library/stdtypes.html#numeric-types-int-float-long-complex\>.

The double-slash operator is called “floor division”. If you are expecting some other rounding, see \<https://docs.python.org/2/faq/programming.html#why-does-22-10-return-3\>.

**Comment by d5ee8318-5b63-4978-ba91-52c15b0c15af** [comment]
I'm sorry, but was a typing error. Try this operations:

a, b, c = 7, -7, 2
print "1:", a // c, a % c
print "2:", b // c, b % c

the result is:
1: 3 1
2: -4 1

The division is the same, except by the signal (variable b is negative, but both, variables "a" and "b" are integers).

**Comment by d5ee8318-5b63-4978-ba91-52c15b0c15af** [comment]
Try this operations, in interactive environment:

>\> 7 // 2
3
>\> -7 // 2
-4

**Comment by d5ee8318-5b63-4978-ba91-52c15b0c15af** [comment]
Note that mathematic expression is wrong. -7 divided by 2 is -3, not -4

**Comment by eryksun** [comment]
> -7 divided by 2 is -3, not -4

Integer division in Python is floor division, and it's self-consistent with the implementation of the modulo operation such that the following identity is satisfied: (a % n) == a - n * (a // n). For example: 

    (-7 % 2) == -7 - 2 * (-7 // 2)
           1 == -7 - 2 * (-4)
             == -7 + 8

This behavior is consistent with mathematical analysis languages such as MATLAB, Mathematica, Mathcad, and R. It's also consistent with Ruby, Perl, and Tcl. However, it's different from C, C++, C#, Java, PHP and many other languages. See the following Wikipedia article:

https://en.wikipedia.org/wiki/Modulo_operation

Please do not change the status and resolution of this issue again. This is not a bug.
