### ISSUE TITLE
importing module shutil executes file 'copy.py'

### ISSUE THREAD

**Issue by c552fd60-98d1-4d5a-8314-02d22f84ddbd** [python/cpython#74007]
BPO | [29821](https://bugs.python.org/issue29821)
--- | :---
Nosy | @vstinner, @eryksun, @ammaraskar

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-15.21:06:17.552>
created_at = <Date 2017-03-15.16:35:14.229>
labels = ['type-bug', 'invalid']
title = "importing module shutil executes file 'copy.py'"
updated_at = <Date 2017-03-15.23:41:18.555>
user = 'https://bugs.python.org/OliverEtchebarnedrmad'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-15.23:41:18.555>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-15.21:06:17.552>
closer = 'ammar2'
components = []
creation = <Date 2017-03-15.16:35:14.229>
creator = 'Oliver Etchebarne (drmad)'
dependencies = []
files = []
hgrepos = []
issue_num = 29821
keywords = []
message_count = 5.0
messages = ['289681', '289696', '289698', '289699', '289700']
nosy_count = 4.0
nosy_names = ['vstinner', 'eryksun', 'ammar2', 'Oliver Etchebarne (drmad)']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29821'
versions = ['Python 3.3', 'Python 3.4']
```

</p></details>

**Comment by c552fd60-98d1-4d5a-8314-02d22f84ddbd** [comment]
I didn't research this issue further. Create a file 'test.py', and write only 'import shutil'. Then create a file 'copy.py' in the same directory, and write something inside, like 'print ("OH NO")'.

When you run test.py, 'copy.py' is executed, and prints the string. Tested with python 3.5 and 3.6. Works as expected (test.py doing nothing) in python 2.7

**Comment by ammaraskar** [comment]
I was only able to recreate this under 3.4 and 3.3, and both of them are under "security" status on https://docs.python.org/devguide/#status-of-python-branches

Should this be marked as won't fix?

**Comment by ammaraskar** [comment]
As per discussion with haypo on irc, this is not a bug since essentially you've made a file which shadows the following stdlib module https://docs.python.org/3/library/copy.html

When shutil goes to import the copy module, your copy module is given higher priority in the import machinery which is why your code gets executed. You can read up more about this here: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-name-shadowing-trap

**Comment by vstinner** [comment]
Run "python3 -I script.py" to not insert '' (current directory) at the first position of sys.path.
https://docs.python.org/dev/using/cmdline.html#cmdoption-I

**Comment by eryksun** [comment]
> Run "python3 -I script.py" to not insert '' (current directory) 
> at the first position of sys.path.

That should be "script directory", not "current directory". We only add the current directory to sys.path in interactive mode, and for -c and -m. Adding the current directory to sys.path when running a script would be silly and cause endless grief.
