### ISSUE TITLE
Don't refer to getsockaddrarg in error messages

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74018]
BPO | [29832](https://bugs.python.org/issue29832)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#687</li><li>python/cpython#3163</li>
Files | <li>[testPatches.py](https://bugs.python.org/file47093/testPatches.py "Uploaded as text/plain at 2017-08-20.21:55:40 by @orenmn"): a dirty script to test PR 3163</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-11.16:51:32.723>
created_at = <Date 2017-03-17.06:43:17.378>
labels = ['extension-modules', 'type-feature', '3.7']
title = "Don't refer to getsockaddrarg in error messages"
updated_at = <Date 2018-09-11.16:51:32.721>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-11.16:51:32.721>
actor = 'benjamin.peterson'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-11.16:51:32.723>
closer = 'benjamin.peterson'
components = ['Extension Modules']
creation = <Date 2017-03-17.06:43:17.378>
creator = 'serhiy.storchaka'
dependencies = []
files = ['47093']
hgrepos = []
issue_num = 29832
keywords = []
message_count = 5.0
messages = ['289745', '289784', '300608', '303541', '325028']
nosy_count = 3.0
nosy_names = ['benjamin.peterson', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['687', '3163']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29832'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
getsockaddrarg() is an internal C function in the socket module implementation used in a number of socket methods (bind(), connect(), connect_ex(), sendto(), sendmsg()) for creating C structure sock_addr_t from Python tuple. Error messages raised when pass incorrect socket address argument to these function contain the name "getsockaddrarg" despite the fact that it is not directly exposed at Python level, nor the name of standard C function.

```pycon
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
>>> s.bind(42)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: getsockaddrarg: AF_INET address must be tuple, not int
>>> s.bind(())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: getsockaddrarg() takes exactly 2 arguments (0 given)
```


I think that error messages shouldn't refer to non-existing function "getsockaddrarg()".

This issue is a part of more general bpo-28261.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
note that bpo-15988 also left 3 changes for this issue to fix, as can be
seen by searching for '29832' in the comments of [PR 668](https://github.com/python/cpython/pull/668).

```py
for example, this issue should also fix the following inconsistent
error messages:
>>> socket.socket(family=socket.AF_INET6).bind(('::1', -1))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: getsockaddrarg: port must be 0-65535.
>>> socket.socket(family=socket.AF_INET6).bind(('::1', -1 << 1000))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C long
```

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
here is a dirty script to test my PR.

the script contains tests to anything I managed to test using my
Windows 10 and Ubuntu 16.04 VM, i.e. all of the changes, except for
the 'unsupported CAN protocol' message, and the changes of the code
that handles the PF_SYSTEM family.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Should i remove the code that i wasn't able to test from the PR, and
leave such changes to someone that is able to test it?

(of course, if there is some way i can do it using a VM, please point
that out, and i would try to set up this VM.)
