### ISSUE TITLE
" don't work on Mac under IDLE

### ISSUE THREAD

**Issue by 0caf9c44-82fe-4a96-8f03-0c9744728d6a** [python/cpython#74012]
BPO | [29826](https://bugs.python.org/issue29826)
--- | :---
Nosy | @terryjreedy, @ned-deily
Superseder | <li>bpo-24170: IDLE crashes when I press ^  caret key</li>
Files | <li>[Screen Shot 2017-03-16 at 09.34.26.png](https://bugs.python.org/file46729/Screen%20Shot%202017-03-16%20at%2009.34.26.png "Uploaded as image/png at 2017-03-16.09:35:22 by Marco Viscito"): error message recieved when IDLE crashes</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-16.22:33:58.371>
created_at = <Date 2017-03-16.09:35:22.858>
labels = ['expert-IDLE', 'type-crash']
title = '" don\'t work on Mac under IDLE'
updated_at = <Date 2017-09-15.12:52:11.609>
user = 'https://bugs.python.org/MarcoViscito'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.12:52:11.609>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-16.22:33:58.371>
closer = 'ned.deily'
components = ['IDLE']
creation = <Date 2017-03-16.09:35:22.858>
creator = 'Marco Viscito'
dependencies = []
files = ['46729']
hgrepos = []
issue_num = 29826
keywords = []
message_count = 4.0
messages = ['289711', '289736', '289738', '289739']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'ned.deily', 'Marco Viscito']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '24170'
type = 'crash'
url = 'https://bugs.python.org/issue29826'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0caf9c44-82fe-4a96-8f03-0c9744728d6a** [comment]
When typing the ' key or the " key on the IDLE Python application for macOS, the application. I think it might have something to do with that beta version of Tcl/Tk (8.5.9) as Python says it is 'unstable'.

**Comment by ned-deily** [comment]
Yes, this is a symptom of using the default Apple-supplied macOS Tcl/Tk.  See https://www.python.org/download/mac/tcltk/ for more information as the warning in IDLE suggests.  If you are using Python 3.6.0 downloaded from python.org, the simple solution is to install the latest Tcl/Tk 8.5.x (not 8.6.x) from ActiveState assuming your use is compatible with the ActiveTcl license.

**Comment by terryjreedy** [comment]
Marco, did you see this message?
 (r"WARNING: The version of Tcl/Tk ({0}) in use may"
  r" be unstable.\\n"
  r"Visit http://www.python.org/download/mac/tcltk/"
  r" for current information.".format(patchlevel))
Or is it somehow lost?

Ned, the version check for this message is only done for Cocoa.  Is this restriction correct?

**Comment by ned-deily** [comment]
> Is this restriction correct?

Yes
