### ISSUE TITLE
os.path.exists seems can not recgnize "~"

### ISSUE THREAD

**Issue by 0508a1ae-5852-4f8a-82fb-0a7a2fb2644d** [python/cpython#74017]
BPO | [29831](https://bugs.python.org/issue29831)
--- | :---
Nosy | @vadmium, @MojoVampire, @3xp10it

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.01:57:10.923>
created_at = <Date 2017-03-17.01:43:15.677>
labels = ['type-bug', 'invalid']
title = 'os.path.exists seems can not recgnize "~"'
updated_at = <Date 2017-03-17.01:57:10.886>
user = 'https://github.com/3xp10it'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-17.01:57:10.886>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-17.01:57:10.923>
closer = 'martin.panter'
components = []
creation = <Date 2017-03-17.01:43:15.677>
creator = 'quanyechavshuo'
dependencies = []
files = []
hgrepos = []
issue_num = 29831
keywords = []
message_count = 3.0
messages = ['289740', '289741', '289742']
nosy_count = 3.0
nosy_names = ['martin.panter', 'josh.r', 'quanyechavshuo']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29831'
versions = []
```

</p></details>

**Comment by 0508a1ae-5852-4f8a-82fb-0a7a2fb2644d** [comment]
os.system is ok to recgnize "\~",but os.path.exists can not recgnize "\~".

eg:

```py
#1.py:
import os
os.system("ls -al ~/.zshrc")
```


python3 1.py

output:
-rw-r--r--  1 root  wheel  5391  3 14 18:12 /var/root/.zshrc


```py
#2.py:
import os
a=os.path.exists("~/.zshrc")
print(a)
```


python3 2.py

output:
False

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
That's because os.system is executing the command in a shell (which expands \~). Without shell support, ~ doesn't mean anything unless used with the APIs that specifically support it (e.g. os.path.expanduser).

You wanted os.path.exists(os.path.expanduser('\~/.zshrc'))

This is not a bug.

**Comment by vadmium** [comment]
I agree with Josh. This is how it is supposed to work.

os.system calls the shell (e.g. Bash) rather than running the "ls" program directly. Unix shells translate "\~" to the home directory (as well as translating a lot of other stuff, e.g. spaces to separate CLI arguments).

But if you pass "\~" to os.path.exists (or most other functions), that goes directly to the operating system and looks for a directory literally called "\~". If you created a directory with that name, it should return True then.
