### ISSUE TITLE
python3 pycopg2 import issue on solaris 10

### ISSUE THREAD

**Issue by 510638ba-ed9b-42ec-bec3-b81d9f199618** [python/cpython#74023]
BPO | [29837](https://bugs.python.org/issue29837)
--- | :---
Nosy | @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.15:43:33.237>
created_at = <Date 2017-03-17.15:40:22.396>
labels = ['build', 'invalid']
title = 'python3 pycopg2 import issue on solaris 10'
updated_at = <Date 2017-03-17.15:43:33.200>
user = 'https://bugs.python.org/juwang'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-17.15:43:33.200>
actor = 'eric.smith'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-17.15:43:33.237>
closer = 'eric.smith'
components = ['Build']
creation = <Date 2017-03-17.15:40:22.396>
creator = 'juwang'
dependencies = []
files = []
hgrepos = []
issue_num = 29837
keywords = []
message_count = 2.0
messages = ['289763', '289764']
nosy_count = 2.0
nosy_names = ['eric.smith', 'juwang']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29837'
versions = ['Python 3.3']
```

</p></details>

**Comment by 510638ba-ed9b-42ec-bec3-b81d9f199618** [comment]
Hi,

I have installed psycopg2 through pip3, but when I tried to import it, I got the following error. what could be the problem?

help\> psycopg2  
problem in psycopg2 - ImportError: ld.so.1: python3.3: fatal: relocation error: file /opt/csw/lib/python3.3/site-packages/psycopg2/_psycopg.so: symbol timeradd: referenced symbol not found 
\------------------------ 

thanks 

justin

**Comment by ericvsmith** [comment]
This would be an issue for pscyopg2 support, not the Python bug tracker.

You're probably using an unsupported combination of psycopg2 and postgres libraries.
