### ISSUE TITLE
Remove nturl2path from test_sundry and amend its docstring

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74022]
BPO | [29836](https://bugs.python.org/issue29836)
--- | :---
Nosy | @brettcannon, @DimitrisJim
PRs | <li>python/cpython#694</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-17.18:17:05.512>
created_at = <Date 2017-03-17.15:35:26.830>
labels = []
title = 'Remove nturl2path from test_sundry and amend its docstring'
updated_at = <Date 2017-03-24.22:13:27.400>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.22:13:27.400>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-17.18:17:05.512>
closer = 'brett.cannon'
components = []
creation = <Date 2017-03-17.15:35:26.830>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29836
keywords = []
message_count = 3.0
messages = ['289760', '289761', '290170']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'Jim Fasarakis-Hilliard']
pr_nums = ['694']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29836'
versions = []
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
After discussion on [1] this PR removes nturl2path from test_sundry and ammends its docstring to include a note on how it is an implementation detail and tested elsewhere.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Whoops:

[1]: https://mail.python.org/mailman/private/core-mentorship/2017-March/003832.html

**Comment by brettcannon** [comment]
New changeset cb5297a9e6b51c736ab8564b1a123577ba0dd2ad by Brett Cannon (Jim Fasarakis-Hilliard) in branch 'master':
bpo-29836: Remove nturl2path from test_sundry and amend the module docstring (GH-694)
https://github.com/python/cpython/commit/cb5297a9e6b51c736ab8564b1a123577ba0dd2ad
