### ISSUE TITLE
Check that sq_length and mq_length return non-negative result

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74024]
BPO | [29838](https://bugs.python.org/issue29838)
--- | :---
Nosy | @rhettinger, @terryjreedy, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#700</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-16.07:07:23.672>
created_at = <Date 2017-03-17.19:39:52.215>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Check that sq_length and mq_length return non-negative result'
updated_at = <Date 2017-04-16.07:07:23.671>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-16.07:07:23.671>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-16.07:07:23.672>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-17.19:39:52.215>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29838
keywords = []
message_count = 7.0
messages = ['289777', '290107', '290110', '290111', '290145', '290148', '291737']
nosy_count = 4.0
nosy_names = ['rhettinger', 'terry.reedy', 'vstinner', 'serhiy.storchaka']
pr_nums = ['700']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29838'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Following PR adds several asserts for checking that sq_length and mq_length either return non-negative result or raise an exception.

One assert already was in PySequence_GetItem().

**Comment by terryjreedy** [comment]
The changes appear consistent within themselves (ie, no apparent typos), and the one for builtin len appears to fix a bug that would allow negative length.  Can tests be written in Python that fail without the patch?   Or would mis-behaving classes have to be written in C?

**Comment by serhiy-storchaka** [comment]
Mis-behaving classes have to be written in C. If the \_\_len__ method in Python class returns a negative value, ValueError is raised in slot_sq_length().

PySequence_GetItem() already contains an assertion that sq_length returns negative value only when an exception is set. The patch just extends this to other cases of calling sq_length and mq_length.

**Comment by serhiy-storchaka** [comment]
The alternate approach is raising SystemError rather than crashing in debug build on assertion. Since this check is used in exceptional case (when a raised exception is expected) it doesn't slow down working code.

**Comment by rhettinger** [comment]
Please don't add more code to critical paths.  

There is no demonstrated need for an additional check here.  The current code has worked well for millions of users for many years.

Also, there are too many checks in common paths and some of them are redundant.  We need less of this, not more.

**Comment by serhiy-storchaka** [comment]
assert() is no-op in release build and that are not critical parts.

Actually the patch decreases the number of checks in release build. Runtime check PyErr_Occurred() is moved into assert() in builtin_len().

**Comment by serhiy-storchaka** [comment]
New changeset 813f943c592cf225871b99cffc99304c8cbbee40 by Serhiy Storchaka in branch 'master':
bpo-29838: Add asserts for checking results of sq_length and mq_length slots. (#700)
https://github.com/python/cpython/commit/813f943c592cf225871b99cffc99304c8cbbee40
