### ISSUE TITLE
Avoid raising OverflowError in bool()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74026]
BPO | [29840](https://bugs.python.org/issue29840)
--- | :---
Nosy | @rhettinger, @terryjreedy, @mdickinson, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1211</li>
Dependencies | <li>bpo-29839: Avoid raising OverflowError in len() when __len__() returns negative large value</li>
Files | <li>[bool-overflow.diff](https://bugs.python.org/file46731/bool-overflow.diff "Uploaded as text/plain at 2017-03-17.20:35:34 by @serhiy-storchaka")</li><li>[bool-no-overflow-double-call.patch](https://bugs.python.org/file46826/bool-no-overflow-double-call.patch "Uploaded as text/plain at 2017-04-22.15:18:18 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-23.07:14:38.991>
created_at = <Date 2017-03-17.20:27:26.527>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Avoid raising OverflowError in bool()'
updated_at = <Date 2017-04-23.07:14:38.989>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-23.07:14:38.989>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-23.07:14:38.991>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-17.20:27:26.527>
creator = 'serhiy.storchaka'
dependencies = ['29839']
files = ['46731', '46826']
hgrepos = []
issue_num = 29840
keywords = ['patch']
message_count = 8.0
messages = ['289781', '290139', '290606', '290615', '292064', '292121', '292140', '292156']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'mark.dickinson', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1211']
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29840'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
For now bool() raises OverflowError if \_\_bool__ is not defined and \_\_len__ returns large value.

```pycon
>>> class A:
...     def __len__(self):
...         return 1 << 1000
... 
>>> bool(A())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: cannot fit 'int' into an index-sized integer
>>> bool(range(1<<1000))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
```


Proposed patch makes bool() returning True if len() raises OverflowError.

This is an alternate solution of bpo-28876.

**Comment by terryjreedy** [comment]
https://docs.python.org/3/library/functions.html#bool refers to
https://docs.python.org/3/library/stdtypes.html#truth

The latter says that values are true ("All other values are considered true") unless one of certain conditions holds.  For user-defined classes, the condition is that the class defines a \_\_bool__() or \_\_len__() method and that the first of those methods returns the bool False or integer zero.

I easily interpret this as meaning that bool(x) (should) \*always* return True or False.  In particular, for user classes, any exception in user-coded \_\_bool__ or \_\_len__ (should be) included in "does not return integer zero or bool value False".  This would mean that 'True' would truly be the default return for Bool().

There is currently an unstated exception for raised Exceptions.  This issue proposes an exception to the exception for OverflowErrors (once negative lengths consistently raise ValueErrors and never OverflowErrors).  While this sensible in itself, I am completely happy with the added complication.  I would like to either reconsider the exception for Exceptions or make it explicit.

Patch has new text and What's New entry.  Added logic in object.c looks correct.

**Comment by vstinner** [comment]
Serhiy: Can you please create a pull request? It would be easier to review.

**Comment by serhiy-storchaka** [comment]
This issue depends on bpo-29839. Tests are failed until the patch of bpo-29839 is merged.

**Comment by vstinner** [comment]
Hum, I dislike this change since it's non-obvious what/who is raising the OverflowError. If an object calls a function in \_\_len__() and the function raises OverflowError, should we consider that object is "true"? In temptation to guess, I prefer to not guess but passthrough the exception.

If you want to support bool(range(1\<\<1000)), we need to get the result of \_\_len__() as a Python object rather than a C Py_ssize_t.

Maybe, if \_\_len__() raises an OverflowError: call again the len(), but using the "\_\_len__" method instead of the slot?

**Comment by serhiy-storchaka** [comment]
I had similar doubts about this patch and needed opinions of other core developers.

> Maybe, if \_\_len__() raises an OverflowError: call again the len(), but using the "\_\_len__" method instead of the slot?

Following patch implements this idea. I don't like it because it is too complicated.

I think that we should either document that raising an OverflowError by \_\_len__() is normal and interpreted as true in Boolean context, or document that \_\_len__() should return a value not larger than sys.maxsize, otherwise len() and bool() can raise an OverflowError (see bpo-15718).

**Comment by vstinner** [comment]
If someone wants to return a value larger than maxsize and support bool():
it is already possible right now by defining a \_\_bool__ method no? If yes,
I suggest to only document this CPython implementation detail (consequence
of slots, for efficiency) and suggest to use \_\_bool__ for such corner case.

I also dislike retrying to call "\_\_len__" method instead of the slot. It
can have annoying side effects.

**Comment by serhiy-storchaka** [comment]
This was documented in bpo-15718.
