### ISSUE TITLE
Path takes and ignores **kwargs

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#74033]
BPO | [29847](https://bugs.python.org/issue29847)
--- | :---
Nosy | @brettcannon, @pitrou, @serhiy-storchaka, @jstasiak, @JelleZijlstra, @DimitrisJim, @remilapeyre, @uriyyo
PRs | <li>python/cpython#13399</li><li>python/cpython#19632</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-18.15:22:47.434>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.7', 'library']
title = 'Path takes and ignores **kwargs'
updated_at = <Date 2020-06-10.22:05:47.572>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-10.22:05:47.572>
actor = 'remi.lapeyre'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-03-18.15:22:47.434>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 29847
keywords = ['patch']
message_count = 9.0
messages = ['289817', '289896', '289897', '289902', '289944', '289945', '289946', '289998', '369520']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'pitrou', 'serhiy.storchaka', 'jstasiak', 'JelleZijlstra', 'Jim Fasarakis-Hilliard', 'remi.lapeyre', 'uriyyo']
pr_nums = ['13399', '19632']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29847'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-118793

**Comment by JelleZijlstra** [comment]
pathlib.Path.\_\_new__ takes \*\*kwargs, but doesn't do anything with them (https://github.com/python/cpython/blob/master/Lib/pathlib.py#L979). This doesn't appear to be documented.

This feature should presumably be either documented or removed (probably removed unless I'm missing some reason for having it).

Brief discussion on a typeshed PR at https://github.com/python/typeshed/pull/991#discussion-diff-105813974R100

**Comment by brettcannon** [comment]
Yep, kwargs should be dropped since it isn't used or documented: https://docs.python.org/3/library/pathlib.html#pathlib.PurePath (probably just a hold-over from when it did in some earlier version of the code).

**Comment by JelleZijlstra** [comment]
Thanks, I'll add a PR. This doesn't need to be documented, right?

**Comment by serhiy-storchaka** [comment]
The support of \*\*kwargs in Path.\_\_new__ is needed if you want to implement a subclass of Path with \_\_init__ accepting keyword arguments (and since Path constructor takes variable number of positional arguments, new arguments should be keyword-only).

```pycon
>>> import pathlib
>>> class MyPath(pathlib.PosixPath):
...     def __init__(self, *args, spam=False):
...         self.spam = spam
... 
>>> p = MyPath('/', spam=True)
>>> p
MyPath('/')
>>> p.spam
True
```


Removing \*\*kwargs from Path.\_\_new__ will break the above example.

```pycon
>>> MyPath('/', spam=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() got an unexpected keyword argument 'spam'
```

**Comment by brettcannon** [comment]
Shoot, that's too bad. I guess we should document it then so people are aware that keyword arguments are ignored, else we will break subclasses. There's also an unfortunate difference between PurePath and Path as PurePath doesn't have this quirk.

**Comment by serhiy-storchaka** [comment]
I don't know whether it was the intension of Antoine or just an oversight. I don't know whether it is used in the wild. But we can at least raise a TypeError for concrete classes PosixPath and WindowsPath if ignoring keyword arguments is a problem. Many extension types don't take keyword arguments, but their subclasses accept and ignore keyword arguments. For example:

```pycon
>>> filter(None, [], foo=123)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: filter() does not take keyword arguments
>>> class X(filter): pass
... 
>>> X(None, [], foo=123)
<__main__.X object at 0xb6fdcacc>
```

**Comment by pitrou** [comment]
> The support of \*\*kwargs in Path.\_\_new__ is needed if you want to implement a subclass of Path with \_\_init__ accepting keyword arguments

I don't remember exactly, but I think this was the intention indeed.  There was originally an openat-using subclass, and IIRC it took additional parameters (such as the directory fd). That got scrapped quite early in the process, so we can remove the \*\*kwargs thing now.

**Comment by brettcannon** [comment]
Then I vote for Serhiy's idea of simply raising an exception in the concrete subclasses when a keyword argument is given.

**Comment by jaraco** [comment]
As reported in the dupe bug, this bug led to masking a user mistake.

**Comment by barneygale** [comment]
#100481 would fix this without breaking subclassing by adding an `__init__()` method.

**Comment by brettcannon** [comment]
I took https://github.com/python/cpython/pull/19632 as a fix, but it can obviously be tweaked as long as the deprecation warning sticks around.
