### ISSUE TITLE
file access, other drives

### ISSUE THREAD

**Issue by addf576f-a5de-40bc-af37-9ba9bf04e6ff** [python/cpython#74036]
BPO | [29850](https://bugs.python.org/issue29850)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-19.16:49:27.721>
created_at = <Date 2017-03-18.22:02:19.823>
labels = ['type-bug', 'OS-windows']
title = 'file access, other drives'
updated_at = <Date 2017-03-19.16:49:27.719>
user = 'https://bugs.python.org/GabrielPOTTER'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-19.16:49:27.719>
actor = 'Gabriel POTTER'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-19.16:49:27.721>
closer = 'Gabriel POTTER'
components = ['Windows']
creation = <Date 2017-03-18.22:02:19.823>
creator = 'Gabriel POTTER'
dependencies = []
files = []
hgrepos = []
issue_num = 29850
keywords = []
message_count = 7.0
messages = ['289830', '289831', '289832', '289837', '289849', '289851', '289857']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Gabriel POTTER']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29850'
versions = ['Python 3.6']
```

</p></details>

**Comment by addf576f-a5de-40bc-af37-9ba9bf04e6ff** [comment]
If python 3 is installed on another drive (for instance D:/), then it cannot access any C:/ files, but can access D:/ files.

I use:
open("C:/path/....")
The same function did work under python 2.7 but now doesn't anymore.

That means that os.path.isfile, open(file).... do not work.

Any help ?

**Comment by addf576f-a5de-40bc-af37-9ba9bf04e6ff** [comment]
To be precise, i cannot detect (only know if the file exist) any file located in
C:/Windows/... (in particulary System32)

contrary to Python 2.7 where it was possible.

**Comment by pfmoore** [comment]
Please provide a script reproducing this issue, and precise details of your Python version. It's extremely unlikely that the problem is as broad as you describe, as otherwise we'd have lots of reports of issues. But we'll need a more specific description to pinpoint the actual problem here.

**Comment by eryksun** [comment]
When you say "to be precise...C:/Windows/...System32", do you mean that this is the only directory that you've tested? If so, what you're seeing may be WOW64 file-system redirection, if your 2.7 installation is 64-bit and 3.6 installation is 32-bit, or vice versa. 

In a WOW64 process, accessing the %SystemRoot%\\System32 directory in most cases gets redirected to the 32-bit system directory, %SystemRoot%\\SysWOW64. You can access the native system directory via %SystemRoot%\\SysNative.

**Comment by addf576f-a5de-40bc-af37-9ba9bf04e6ff** [comment]
Thanks for your answers. I'll try to be as precise as possible.

The problem i have is really specific:
I have a custom file, that i added in C:/Windows/System32/

I have a Windows 10 x64 computer, with 2 versions of python installed:
- Python 2.7, in C:\\Python27
- Python 3.6, in D:\\Programms\\Python3

I use a sample of code with the two different versions:

* With Python 2.7:

```pycon
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isfile(os.path.normpath("C:/Users/gpotter/Desktop/test.txt"))
True
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/cmd.exe"))
True
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/windump.exe"))
True
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/do_not_exist.stg"))
False
```



* Now, with Python 3.6:

```pycon
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 07:18:10) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path.isfile(os.path.normpath("C:/Users/gpotter/Desktop/test.txt"))
True
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/cmd.exe"))
True
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/windump.exe"))
False
>>> os.path.isfile(os.path.normpath("C:/Windows/System32/do_not_exist.stg"))
False
```


As you can see, Python 2.7 acts normally for everything. Python 3.6 does detect cmd.exe as a correct file, but do not detects windump.exe, the file that I added manually.

**Comment by pfmoore** [comment]
As you see from the banner, your Python 3.6 is 32-bit but your Python 2.7 is 64-bit.

I'd suggest you try 64-bit Python 3.6. This definitely looks like the SysWOW64 issue Eryk described.

**Comment by addf576f-a5de-40bc-af37-9ba9bf04e6ff** [comment]
Thanks a lot, that resolved it.
