### ISSUE TITLE
curses online documentation typo

### ISSUE THREAD

**Issue by 8a5ab3d6-7af6-4727-97d1-7e51609d872c** [python/cpython#74042]
BPO | [29856](https://bugs.python.org/issue29856)
--- | :---
Nosy | @DimitrisJim, @Mariatta, @McSinyx
PRs | <li>python/cpython#730</li><li>python/cpython#731</li><li>python/cpython#732</li><li>python/cpython#733</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-03-20.03:59:49.012>
created_at = <Date 2017-03-20.02:52:31.355>
labels = ['3.7', 'docs']
title = 'curses online documentation typo'
updated_at = <Date 2017-03-24.20:19:12.304>
user = 'https://github.com/McSinyx'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.20:19:12.304>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-03-20.03:59:49.012>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-03-20.02:52:31.355>
creator = 'McSinyx'
dependencies = []
files = []
hgrepos = []
issue_num = 29856
keywords = []
message_count = 8.0
messages = ['289868', '289869', '289870', '289872', '290133', '290134', '290135', '290136']
nosy_count = 4.0
nosy_names = ['docs@python', 'Jim Fasarakis-Hilliard', 'Mariatta', 'McSinyx']
pr_nums = ['730', '731', '732', '733']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29856'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8a5ab3d6-7af6-4727-97d1-7e51609d872c** [comment]
I think there is a typo in curses online documentation about key constants:

https://docs.python.org/3.7/library/curses.html#constants

The key KEY_SEXIT is described as `Shifted Dxit' while I think that should be `Shifted Exit'.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Nice catch, that's a typo indeed. If you'd like, submit a PR [see https://docs.python.org/devguide/#quick-start] to address this.

**Comment by Mariatta** [comment]
Thanks for the report, Raphael.
And thanks Jim, I made a PR just as you commented :)

**Comment by Mariatta** [comment]
Typo fixed and backported into 2.7, 3.5 and 3.6.
Thanks :)

**Comment by Mariatta** [comment]
New changeset 7cc071c96b95e7422f64cb436d547c952e0ca52f by Mariatta in branch '3.5':
bpo-29856: Fix typo in curses documentation (GH-730) (GH-732)
https://github.com/python/cpython/commit/7cc071c96b95e7422f64cb436d547c952e0ca52f

**Comment by Mariatta** [comment]
New changeset 91f79db02acb9f82c738bb0b2f7bfc3260b90930 by Mariatta in branch '2.7':
bpo-29856: Fix typo in curses documentation (GH-730) (GH-733)
https://github.com/python/cpython/commit/91f79db02acb9f82c738bb0b2f7bfc3260b90930

**Comment by Mariatta** [comment]
New changeset d1f566f6bddc67e9870eaa75ae477208b9a199be by Mariatta in branch '3.6':
bpo-29856: Fix typo in curses documentation (GH-730) (GH-731)
https://github.com/python/cpython/commit/d1f566f6bddc67e9870eaa75ae477208b9a199be

**Comment by Mariatta** [comment]
New changeset 64508780d72769e4c7afc67a511c057261c578f6 by Mariatta in branch 'master':
bpo-29856: Fix typo in curses documentation (GH-730)
https://github.com/python/cpython/commit/64508780d72769e4c7afc67a511c057261c578f6
