### ISSUE TITLE
multiprocessing Pool keeps objects (tasks, args, results) alive too long

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74047]
BPO | [29861](https://bugs.python.org/issue29861)
--- | :---
Nosy | @pitrou, @vstinner, @applio, @zhangyangyu
PRs | <li>python/cpython#743</li><li>python/cpython#800</li><li>python/cpython#801</li><li>python/cpython#803</li><li>python/cpython#1120</li><li>python/cpython#1132</li><li>python/cpython#1133</li><li>python/cpython#1472</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-24.15:04:38.949>
created_at = <Date 2017-03-20.18:14:14.443>
labels = ['3.7', 'library', 'performance']
title = 'multiprocessing Pool keeps objects (tasks, args, results) alive too long'
updated_at = <Date 2017-05-05.07:47:13.988>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.07:47:13.988>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-24.15:04:38.949>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-03-20.18:14:14.443>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 29861
keywords = []
message_count = 14.0
messages = ['289894', '289895', '290086', '290088', '290089', '290092', '291587', '291628', '291629', '291646', '291648', '291649', '293061', '293064']
nosy_count = 5.0
nosy_names = ['pitrou', 'vstinner', 'sbt', 'davin', 'xiang.zhang']
pr_nums = ['743', '800', '801', '803', '1120', '1132', '1133', '1472']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29861'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
The various workers in multiprocessing.Pool keep a reference to the last encountered task or task result.  This means some data may be kept alive even after the caller is done with them, as long as some other task doesn't clobber the relevant variables.

Specifically, Pool.\_handle_tasks(), Pool.\_handle_results() and the toplevel worker() function fail to clear references at the end of each loop.

Originally reported at https://github.com/dask/distributed/issues/956

**Comment by pitrou** [comment]
Quick patch below.  I'll make a PR once I have time to :-)

```diff
diff --git a/Lib/multiprocessing/pool.py b/Lib/multiprocessing/pool.py
index ffdf426..945afa2 100644
--- a/Lib/multiprocessing/pool.py
+++ b/Lib/multiprocessing/pool.py
@@ -128,6 +128,8 @@ def worker(inqueue, outqueue, initializer=None, initargs=(), maxtasks=None,
             util.debug("Possible encoding error while sending result: %s" % (
                 wrapped))
             put((job, i, (False, wrapped)))
+
+        task = job = result = func = args = kwds = None
         completed += 1
     util.debug('worker exiting after %d tasks' % completed)
 
@@ -402,6 +404,8 @@ class Pool(object):
                 if set_length:
                     util.debug('doing set_length()')
                     set_length(i+1)
+            finally:
+                task = taskseq = job = None
         else:
             util.debug('task handler got sentinel')
 
@@ -445,6 +449,7 @@ class Pool(object):
                 cache[job]._set(i, obj)
             except KeyError:
                 pass
+            task = job = obj = None
 
         while cache and thread._state != TERMINATE:
             try:
@@ -461,6 +466,7 @@ class Pool(object):
                 cache[job]._set(i, obj)
             except KeyError:
                 pass
+            task = job = obj = None
 
         if hasattr(outqueue, '_reader'):
             util.debug('ensuring that outqueue is not full')
```

**Comment by pitrou** [comment]
New changeset 8988945cdc27ffa86ba8c624e095b51c459f5154 by Antoine Pitrou in branch 'master':
bpo-29861: release references to multiprocessing Pool tasks (#743)
https://github.com/python/cpython/commit/8988945cdc27ffa86ba8c624e095b51c459f5154

**Comment by pitrou** [comment]
New changeset cc3331fec8b7a61c3f06c097eac85bfa38490758 by Antoine Pitrou in branch '3.6':
bpo-29861: release references to multiprocessing Pool tasks (#743) (#800)
https://github.com/python/cpython/commit/cc3331fec8b7a61c3f06c097eac85bfa38490758

**Comment by pitrou** [comment]
New changeset 80cb6ed4db9bae09de1e9ad6001d11cb45a4c1cc by Antoine Pitrou in branch '3.5':
bpo-29861: release references to multiprocessing Pool tasks (#743) (#801)
https://github.com/python/cpython/commit/80cb6ed4db9bae09de1e9ad6001d11cb45a4c1cc

**Comment by pitrou** [comment]
New changeset 5084ff7ddfe68969d95af12075016f309718aea8 by Antoine Pitrou in branch '2.7':
bpo-29861: release references to multiprocessing Pool tasks (#743) (#803)
https://github.com/python/cpython/commit/5084ff7ddfe68969d95af12075016f309718aea8

**Comment by zhangyangyu** [comment]
Hi, Antoine, after this change, I sometimes see tests fail for 3.5 branch, for example http://buildbot.python.org/all/builders/x86%20Ubuntu%20Shared%203.5/builds/194/steps/test/logs/stdio.

**Comment by pitrou** [comment]
I can't reproduce here, on Ubuntu 16.04, after running the test 500 times.

**Comment by pitrou** [comment]
Ok, I can reproduce now.

**Comment by pitrou** [comment]
New changeset 685cdb9acc3fca04a9897d88b89771ddfd50e772 by Antoine Pitrou in branch 'master':
Relax test timing (bpo-29861) to avoid sporadic failures (bpo-1120)
https://github.com/python/cpython/commit/685cdb9acc3fca04a9897d88b89771ddfd50e772

**Comment by pitrou** [comment]
New changeset 413a8913aee255d0635e4ddbb9c343d9e5e76fea by Antoine Pitrou in branch '3.6':
Relax test timing (bpo-29861) to avoid sporadic failures (bpo-1120) (bpo-1132)
https://github.com/python/cpython/commit/413a8913aee255d0635e4ddbb9c343d9e5e76fea

**Comment by pitrou** [comment]
New changeset 47f24a018f6a9c3ed996d2b83a7ebd0d1f905827 by Antoine Pitrou in branch '3.5':
Relax test timing (bpo-29861) to avoid sporadic failures (bpo-1120) (bpo-1133)
https://github.com/python/cpython/commit/47f24a018f6a9c3ed996d2b83a7ebd0d1f905827

**Comment by vstinner** [comment]
> New changeset 685cdb9acc3fca04a9897d88b89771ddfd50e772 by Antoine Pitrou in branch 'master':
> Relax test timing (bpo-29861) to avoid sporadic failures (bpo-1120)

Oh, this change wasn't backported to 2.7 and caused the bpo-30269. I proposed a backport: https://github.com/python/cpython/pull/1472 I will merge it once tests pass ;-)

**Comment by vstinner** [comment]
New changeset fd6094cdebb5736745d164e0207de2d4cb0b50dc by Victor Stinner in branch '2.7':
Relax test timing (bpo-29861) to avoid sporadic failures (bpo-1120) (bpo-1472)
https://github.com/python/cpython/commit/fd6094cdebb5736745d164e0207de2d4cb0b50dc
