### ISSUE TITLE
smtplib.py doesn't capitalize EHLO.

### ISSUE THREAD

**Issue by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [python/cpython#74046]
BPO | [29860](https://bugs.python.org/issue29860)
--- | :---
Nosy | @warsaw, @bitdancer, @soltysh, @rahul-kumi, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-18.23:47:55.766>
created_at = <Date 2017-03-20.14:32:53.266>
labels = ['invalid', '3.7', 'library', 'expert-email']
title = "smtplib.py doesn't capitalize EHLO."
updated_at = <Date 2022-01-18.23:47:55.765>
user = 'https://bugs.python.org/LordAntonHvornum'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.23:47:55.765>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-18.23:47:55.766>
closer = 'iritkatriel'
components = ['Library (Lib)', 'email']
creation = <Date 2017-03-20.14:32:53.266>
creator = 'Lord Anton Hvornum'
dependencies = []
files = []
hgrepos = []
issue_num = 29860
keywords = []
message_count = 7.0
messages = ['289886', '289888', '289889', '289890', '289891', '289907', '410916']
nosy_count = 6.0
nosy_names = ['barry', 'r.david.murray', 'maciej.szulik', 'Lord Anton Hvornum', 'rahul-kumi', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29860'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
```
  File "mail.py", line 9, in <module>
    smtp_server.starttls(context)
  File "/usr/lib/python3.6/smtplib.py", line 748, in starttls
    self.ehlo_or_helo_if_needed()
  File "/usr/lib/python3.6/smtplib.py", line 600, in ehlo_or_helo_if_needed
    (code, resp) = self.helo()
  File "/usr/lib/python3.6/smtplib.py", line 429, in helo
    (code, msg) = self.getreply()
  File "/usr/lib/python3.6/smtplib.py", line 393, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
```

This happens due to the server expecting commands (like EHLO, STARTTLS) being strict upper-case. And when the SMTP command isn't, it drops us.

This is a rare edge case since most mail servers handles shady client data in numerous different ways (such as gmail never sending QUIT for instance).

I don't know of a work-around for this and the documentation states `EHLO` is being sent (https://docs.python.org/3/library/smtplib.html), so I guess the lib assumes that's the case as well.

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
Turns out, this goes for a lot more commands, such as:

```
Traceback (most recent call last):
  File "mail.py", line 12, in <module>
    smtp_server.sendmail(fromaddr, toaddrs, msg)
  File "/usr/lib/python3.6/smtplib.py", line 866, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
```

The command that the server refused was:

    mail FROM:<my_mail@gmail.com> size=11

Again, this is mostly because traditionally server commands are upper case (even tho RFC 821 defines that they can be any syntax, such as `mAiL FroM`).

But it would be nice if Python could keep consistency in it's syntax IMHO.

**Comment by bitdancer** [comment]
It is interesting that in all the years smtplib has been in use, this is the first time (as far as I know) this has been reported as a problem.  I don't see any reason to object to changing it to send the commands in upper case, but the server you are talking to is definitely out of spec with the RFC :)

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
Seeing as I'm the one who built the server, it sure is out of spec :)

I could also quickly correct for this "issue" server-side.
So this is more of a "style guideline" change client-side - If no one opposes of keeping commands stylistically the same.

**Comment by bitdancer** [comment]
On the other hand, the current mixed case sending found a bug in your code, so it has some value.  I'm neither in favor nor in objection to the change, at this point.

**Comment by warsaw** [comment]
Is EHLO the only command sent in lower case?  I think it might not be.

I suppose I'm a solid ±0 on changing this (how's that for a completely neutral endorsement?).  I won't do the change myself, but I'd review a pull request.
