### ISSUE TITLE
Misuse of Py_SIZE in dict.fromkey()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74050]
BPO | [29864](https://bugs.python.org/issue29864)
--- | :---
Nosy | @methane, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#747</li><li>python/cpython#750</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-21.06:53:59.243>
created_at = <Date 2017-03-21.06:02:12.946>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Misuse of Py_SIZE in dict.fromkey()'
updated_at = <Date 2017-03-24.20:09:03.994>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-24.20:09:03.994>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-21.06:53:59.243>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-21.06:02:12.946>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29864
keywords = []
message_count = 5.0
messages = ['289915', '289922', '289924', '289925', '290115']
nosy_count = 3.0
nosy_names = ['methane', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['747', '750']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29864'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
In dict.fromkeys() implementation when a dict is passed its size is determined by using the Py_SIZE macro. This is not correct since PyDictObject is not a PyVarObject (but see bpo-28988).

**Comment by zhangyangyu** [comment]
How about 3.6, Serhiy? I see you treat this as a bugfix on the PR.

**Comment by serhiy-storchaka** [comment]
Yes, I treat this as a bugfix but I hesitated about backporting it. Py_SIZE works "by accident" and we can't change the layout of PyDictObject structure in maintain branches.

I have backported the fix to 3.6, but not to other branches since PyDict_GET_SIZE was added in 3.6 and other branches would need modifying the patch.

**Comment by zhangyangyu** [comment]
I think 3.6 is enough.

**Comment by serhiy-storchaka** [comment]
New changeset af839fe2fef12dbbc8083fc7f01daee48a85a916 by Serhiy Storchaka in branch '3.6':
bpo-29864: Don't use Py_SIZE for dict object. (#747) (#750)
https://github.com/python/cpython/commit/af839fe2fef12dbbc8083fc7f01daee48a85a916
