### ISSUE TITLE
IDLE quit unexpectedly

### ISSUE THREAD

**Issue by 0c0769a7-ed4b-464b-b808-06f3e018c4f6** [python/cpython#74061]
BPO | [29875](https://bugs.python.org/issue29875)
--- | :---
Nosy | @terryjreedy, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-03-22.05:32:22.582>
created_at = <Date 2017-03-22.05:09:16.274>
labels = ['expert-IDLE']
title = 'IDLE quit unexpectedly'
updated_at = <Date 2017-03-22.05:32:22.574>
user = 'https://bugs.python.org/igorafm'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-22.05:32:22.574>
actor = 'ned.deily'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-03-22.05:32:22.582>
closer = 'ned.deily'
components = ['IDLE']
creation = <Date 2017-03-22.05:09:16.274>
creator = 'igorafm'
dependencies = []
files = []
hgrepos = []
issue_num = 29875
keywords = []
message_count = 2.0
messages = ['289970', '289971']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'ned.deily', 'igorafm']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29875'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0c0769a7-ed4b-464b-b808-06f3e018c4f6** [comment]
Hi! I'm a newbie, both in this community and with Python. I downloaded Python today (March 22, 2017, version 3.6.1) and as I was following a tutorial on how to build my first program (the classical Hello World) with Python, the IDLE window closed and my Mac showed the following message: "IDLE quit unexpectedly". It happens every time I type the ' (single quotation mark).I've tried 10 times so far and it keeps happening. 
Thank you!

**Comment by ned-deily** [comment]
Welcome to the world of Python! You most likely saw a message similar to this when the IDLE shell window opened:

WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.

If you follow that link, you'll see that you need to install a newer version of Tcl/Tk 8.5.x to avoid bugs in Tcl/Tk; the easiest solution is to download and install ActiveTcl 8.5 from ActiveState as described.
