### ISSUE TITLE
The link referring to "Python download page" is broken

### ISSUE THREAD

**Issue by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [python/cpython#74074]
BPO | [29888](https://bugs.python.org/issue29888)
--- | :---
Nosy | @ned-deily, @cocoatomo
PRs | <li>python/cpython#820</li><li>python/cpython#823</li><li>python/cpython#824</li><li>python/cpython#826</li><li>python/cpython#827</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-27.03:02:26.629>
created_at = <Date 2017-03-23.18:04:23.360>
labels = ['3.7', 'docs']
title = 'The link referring to "Python download page" is broken'
updated_at = <Date 2017-03-27.03:02:26.628>
user = 'https://github.com/cocoatomo'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.03:02:26.628>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-27.03:02:26.629>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-03-23.18:04:23.360>
creator = 'cocoatomo'
dependencies = []
files = []
hgrepos = []
issue_num = 29888
keywords = []
message_count = 10.0
messages = ['290057', '290103', '290104', '290531', '290540', '290541', '290542', '290543', '290556', '290559']
nosy_count = 3.0
nosy_names = ['ned.deily', 'docs@python', 'cocoatomo']
pr_nums = ['820', '823', '824', '826', '827']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29888'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
The download page [1]_ contains a link intended to refer to the release page of the corresponding Python version [2]_.

.. [1] `Download Python 2.7.13 Documentation <https://docs.python.org/2.7/download.html>`_

.. [2] e.g. `Python 2.7.8 Release <https://www.python.org/download/releases/2.7.8/>`_

Although, this link is broken for three reasons.

1. Wrong template syntax

   `Present code <https://github.com/python/cpython/blob/2.7/Doc/tools/templates/download.html#L78-L80>`_::

      <p>{% trans download_page="https://www.python.org/download/releases/{{ release[:5] }}/" %}HTML Help
      (<tt>.chm</tt>) files are made available in the "Windows" section
      on the <a href={{ download_page }}>Python download page</a>.{% endtrans %}</p>

   Fixed code::

      <p>{% trans download_page="https://www.python.org/download/releases/" + release[:5] + "/" %}HTML Help
      (<tt>.chm</tt>) files are made available in the "Windows" section
      on the <a href="{{ download_page }}">Python download page</a>.{% endtrans %}</p>

2. Unexpected version number

   The URL contains a Python version string (i.e. ``release[:5]``), but for Python 2.7.13, ``release[:5]`` evaluates to ``'2.7.1'`` which obviously wrong as a version string.

3. Non-existent release pages for some versions

   www.python.org has pages which URLs are https://www.python.org/download/releases/\<version\>/ with \<version\> = 2.7.1--8, although has no pages with \<version\> = 2.7.9 and so on.

   Is https://www.python.org/downloads/release/python-2713/ an appropriate page to refer?

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
According to the table on the Downloads page [1]_, relations between Python versions and version specific release pages are listed as follows:

   2.7.0  -\> https://www.python.org/download/releases/2.7/
   2.7.1  -\> https://www.python.org/download/releases/2.7.1/
   2.7.2  -\> https://www.python.org/download/releases/2.7.2/
   2.7.3  -\> https://www.python.org/download/releases/2.7.3/
   2.7.4  -\> https://www.python.org/download/releases/2.7.4/
   2.7.5  -\> https://www.python.org/download/releases/2.7.5/
   2.7.6  -\> https://www.python.org/download/releases/2.7.6/
   2.7.7  -\> https://www.python.org/download/releases/2.7.7/
   2.7.8  -\> https://www.python.org/downloads/release/python-278/
   2.7.9  -\> https://www.python.org/downloads/release/python-279/
   2.7.10 -\> https://www.python.org/downloads/release/python-2710/
   2.7.11 -\> https://www.python.org/downloads/release/python-2711/
   2.7.12 -\> https://www.python.org/downloads/release/python-2712/
   2.7.13 -\> https://www.python.org/downloads/release/python-2713/

   3.0.0  -\> https://www.python.org/download/releases/3.0/
   3.0.1  -\> https://www.python.org/download/releases/3.0.1/

   3.1.0  -\> https://www.python.org/download/releases/3.1/
   3.1.1  -\> https://www.python.org/download/releases/3.1.1/
   3.1.2  -\> https://www.python.org/download/releases/3.1.2/
   3.1.3  -\> https://www.python.org/download/releases/3.1.3/
   3.1.4  -\> https://www.python.org/download/releases/3.1.4/
   3.1.5  -\> https://www.python.org/downloads/release/python-315/

   3.2.0  -\> https://www.python.org/download/releases/3.2/
   3.2.1  -\> https://www.python.org/download/releases/3.2.1/
   3.2.2  -\> https://www.python.org/download/releases/3.2.2/
   3.2.3  -\> https://www.python.org/download/releases/3.2.3/
   3.2.4  -\> https://www.python.org/download/releases/3.2.4/
   3.2.5  -\> https://www.python.org/download/releases/3.2.5/
   3.2.6  -\> https://www.python.org/downloads/release/python-326/

   3.3.0  -\> https://www.python.org/download/releases/3.3.0/
   3.3.1  -\> https://www.python.org/download/releases/3.3.1/
   3.3.2  -\> https://www.python.org/download/releases/3.3.2/
   3.3.3  -\> https://www.python.org/download/releases/3.3.3/
   3.3.4  -\> https://www.python.org/download/releases/3.3.4/
   3.3.5  -\> https://www.python.org/download/releases/3.3.5/
   3.3.6  -\> https://www.python.org/downloads/release/python-336/

   3.4.0  -\> https://www.python.org/download/releases/3.4.0/
   3.4.1  -\> https://www.python.org/downloads/release/python-341/
   3.4.2  -\> https://www.python.org/downloads/release/python-342/
   3.4.3  -\> https://www.python.org/downloads/release/python-343/
   3.4.4  -\> https://www.python.org/downloads/release/python-344/
   3.4.5  -\> https://www.python.org/downloads/release/python-345/
   3.4.6  -\> https://www.python.org/downloads/release/python-346/

   3.5.0  -\> https://www.python.org/downloads/release/python-350/
   3.5.1  -\> https://www.python.org/downloads/release/python-351/
   3.5.2  -\> https://www.python.org/downloads/release/python-352/
   3.5.3  -\> https://www.python.org/downloads/release/python-353/

   3.6.0  -\> https://www.python.org/downloads/release/python-360/
   3.6.1  -\> https://www.python.org/downloads/release/python-361/


.. [1] https://www.python.org/downloads/

I will create a pull request for Python 2.7, 3.5 and 3.6.

**Comment by ned-deily** [comment]
Thanks for noticing this.  The change in URLs was due to the introduction of the "new" python.org website a few years ago;  the canonical form of the URL for releases introduced after the move to the new web site is indeed  https://www.python.org/downloads/release/python-xyz/ so that should be the URL form used for current and future releases.  Another approach would be to add aliases on the web site to redirect from /releases/x.y.z to /release/python-xyz/ but, at this point, I don't think that's necessary.  A PR to fix the generated docs would be great.

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
I just created two pull requests.

\+ PR for 2.7 -\> https://github.com/python/cpython/pull/823
\+ PR for 3.5 or newer -\> https://github.com/python/cpython/pull/824

**Comment by ned-deily** [comment]
New changeset f8beb9831acd5cf80b9c56aea5864e16118c5400 by Ned Deily (cocoatomo) in branch 'master':
bpo-29888: Fix the link referring to the "Python download page" (GH-824)
https://github.com/python/cpython/commit/f8beb9831acd5cf80b9c56aea5864e16118c5400

**Comment by ned-deily** [comment]
New changeset ceff32fb833e7be42508ffa73344e2e56865e54b by Ned Deily in branch '3.6':
bpo-29888: Fix the link referring to the "Python download page" (GH-824) (GH-826)
https://github.com/python/cpython/commit/ceff32fb833e7be42508ffa73344e2e56865e54b

**Comment by ned-deily** [comment]
New changeset 8ce3085bf167b702989a9db466078b5676e825e3 by Ned Deily in branch '3.5':
bpo-29888: Fix the link referring to the "Python download page" (GH-824) (GH-827)
https://github.com/python/cpython/commit/8ce3085bf167b702989a9db466078b5676e825e3

**Comment by ned-deily** [comment]
Thanks for the pull requests!  I've merged to master, 3.6, and 3.5 and I left a comment for the 2.7 PR.  By the way, next time you make a PR, please feel free to add your name to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS).

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
@ned.deily Thank you for the commend. I updated the 2.7 PR.

**Comment by ned-deily** [comment]
New changeset 6f95b37f290e0225aed5f8f7733ad0730601201b by Ned Deily (cocoatomo) in branch '2.7':
bpo-29888: Fix the link referring to "Python download page" (GH-823)
https://github.com/python/cpython/commit/6f95b37f290e0225aed5f8f7733ad0730601201b
