### ISSUE TITLE
Allow GMT timezones to be used in datetime.

### ISSUE THREAD

**Issue by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [python/cpython#74071]
BPO | [29885](https://bugs.python.org/issue29885)
--- | :---
Nosy | @vadmium, @serhiy-storchaka, @AraHaan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-25.00:09:17.270>
created_at = <Date 2017-03-23.06:35:08.351>
labels = ['3.7', 'library']
title = 'Allow GMT timezones to be used in datetime.'
updated_at = <Date 2017-11-25.00:09:17.269>
user = 'https://github.com/AraHaan'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-25.00:09:17.269>
actor = 'Decorater'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-25.00:09:17.270>
closer = 'Decorater'
components = ['Library (Lib)']
creation = <Date 2017-03-23.06:35:08.351>
creator = 'Decorater'
dependencies = []
files = []
hgrepos = []
issue_num = 29885
keywords = []
message_count = 3.0
messages = ['290027', '290028', '290029']
nosy_count = 3.0
nosy_names = ['martin.panter', 'serhiy.storchaka', 'Decorater']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29885'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
I noticed that there is no ways to convert local times to GMT if I realize that some other object (sometimes from a server) is using GMT and they happen to be ahead of my current time. As such it would be great if one can convert their current time that can be in an datetime object to an GMT time to see how much time has passed since something happened on their zone if so desired (otherwise can cause undesired or undefined consequences).

**Comment by serhiy-storchaka** [comment]
Use pytz (https://pypi.python.org/pypi/pytz).

**Comment by vadmium** [comment]
Does the “astimezone” method work for you? \<https://docs.python.org/3.5/library/datetime.html#datetime.datetime.astimezone\>

```pycon
>>> from datetime import *
>>> aedt = timezone(+timedelta(hours=11))
>>> local = datetime.now(aedt)
>>> format(local)
'2017-03-23 19:14:41.410334+11:00'
>>> gmt = local.astimezone(timezone.utc)
>>> format(gmt)
'2017-03-23 08:14:41.410334+00:00'
```
