### ISSUE TITLE
Constructor of ipaddress.IPv*Interface does not follow documentation

### ISSUE THREAD

**Issue by 8261aa84-e702-455d-ad8f-b513a205490a** [python/cpython#74076]
BPO | [29890](https://bugs.python.org/issue29890)
--- | :---
Nosy | @ericvsmith, @Kentzo, @zhangyangyu, @mlouielu, @humbdrag
PRs | <li>python/cpython#816</li><li>python/cpython#30862</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-03-23.21:59:48.893>
labels = ['easy', 'type-bug']
title = 'Constructor of ipaddress.IPv*Interface does not follow documentation'
updated_at = <Date 2022-01-24.21:29:56.167>
user = 'https://github.com/Kentzo'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-24.21:29:56.167>
actor = 'humbdrag'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-03-23.21:59:48.893>
creator = 'Ilya.Kulakov'
dependencies = []
files = []
hgrepos = []
issue_num = 29890
keywords = ['patch', 'easy']
message_count = 9.0
messages = ['290062', '290069', '290462', '290469', '290472', '290473', '290479', '305134', '308855']
nosy_count = 6.0
nosy_names = ['eric.smith', 'pmoody', 'Ilya.Kulakov', 'xiang.zhang', 'louielu', 'humbdrag']
pr_nums = ['816', '30862']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29890'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
As per documentation, it should understand the same arguments as IPv\*Network.

Unfortunately it does not recognize netmask in string form. Hence the following code will fail:

```py
    ipaddress.ip_interface(('192.168.1.10', '255.255.255.0'))

while the following will work:
```


    ipaddress.ip_network(('192.168.1.10', '255.255.255.0'), strict=False)

**Comment by ericvsmith** [comment]
This should be easy enough to fix, at least in IPv4Interface.\_\_init__. It needs to copy some of IPv4Network.\_\_init__, dealing with address[1] and calling \_make_netmask(). Currently, it just calls int(address[1]).

I haven't looked at IPv6Interface.

Tests are also needed, of course.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
The document here says: https://docs.python.org/3/library/ipaddress.html#interface-objects

""IPv4Interface is a subclass of IPv4Address""

trying with:

```pycon
>>> ipaddress.IPv4Address(('192.168.128.0', '255.255.255.0'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/ipaddress.py", line 1284, in __init__
    self._ip = self._ip_int_from_string(addr_str)
  File "/usr/lib/python3.6/ipaddress.py", line 1118, in _ip_int_from_string
    raise AddressValueError("Expected 4 octets in %r" % ip_str)
ipaddress.AddressValueError: Expected 4 octets in "('192.168.128.0', '255.255.255.0')"
```


So the behavior of IPv4Interface seem to be correct?

**Comment by ericvsmith** [comment]
While an IPv4Interface may be a subclass of an IPv4Address, it definitely has more information attached to it: the netmask of the network it's on. So an interface (like a network) needs to allow additional parameters to specify the netmask.

It should be true that IPv4Interface is like IPv4Network, but it will allow arbitrary host bits. A IPv4Network in strict mode will have all zeros for the host bits, while a IPv4Network in non-strict mode will allow ones in the host bits (see Ilya's original example).

If you look at IPv4Interface.\_\_init__, it actually does just that: creates an IPv4Network with strict=False, then extracts the network parts. I'm not exactly sure why it also has the int(address[1]) code there, too, since IPvv4Network deals with the address[1] part. I would think extracting \_prefixlen from the network (as it does later in \_\_init__ for the non-tuple case) would be good enough.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Eric: I made the patch, reference to which IPv\*Network dealing with tuple. Should I also add the unittest for it?

Also, can you help me code review this, thanks.

**Comment by ericvsmith** [comment]
Thanks! Yes, we'll need tests.

I'm out of town most of the weekend, but I'll look at this as soon as I can.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Add unittest. Since IPv6 do not support prefix netmask ('ffff:ff00::'), it have only test like this:

>\>\> a = ipaddress.ip_interface(('dead:beaf::', '32'))
>\>\> b = ipaddress.ip_interface('dead:beaf::/32')
>\>\> str(a) == str(b)

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
Can this be included into the next bugfix release?

**Comment by furkanonder** [comment]
@JelleZijlstra The issue seems to be resolved in this [PR](https://github.com/python/cpython/pull/30862).

**Comment by JelleZijlstra** [comment]
Yes, thanks!
