### ISSUE TITLE
test_normalization doesn't work

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74073]
BPO | [29887](https://bugs.python.org/issue29887)
--- | :---
Nosy | @brettcannon, @terryjreedy, @vstinner, @benjaminp, @berkerpeksag, @serhiy-storchaka, @iritkatriel
PRs | <li>python/cpython#905</li><li>python/cpython#1196</li><li>python/cpython#2271</li><li>python/cpython#2272</li><li>python/cpython#2275</li><li>python/cpython#2344</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-19.14:10:07.657>
created_at = <Date 2017-03-23.16:57:10.553>
labels = ['3.7', 'type-bug', 'tests']
title = "test_normalization doesn't work"
updated_at = <Date 2020-09-19.14:10:07.656>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-19.14:10:07.656>
actor = 'benjamin.peterson'
assignee = 'none'
closed = True
closed_date = <Date 2020-09-19.14:10:07.657>
closer = 'benjamin.peterson'
components = ['Tests']
creation = <Date 2017-03-23.16:57:10.553>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29887
keywords = []
message_count = 15.0
messages = ['290053', '290175', '290605', '290636', '290816', '290832', '290848', '290878', '291922', '291925', '291932', '296310', '296336', '296404', '377163']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'terry.reedy', 'vstinner', 'benjamin.peterson', 'berker.peksag', 'serhiy.storchaka', 'iritkatriel']
pr_nums = ['905', '1196', '2271', '2272', '2275', '2344']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29887'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It needs to fetch http://www.pythontest.net/unicode/9.0.0/NormalizationTest.txt (8.0.0 in 3.5) but get the 404 error.

**Comment by terryjreedy** [comment]
Fetching the file requires '-u urlfetch' or '-u all'.  For me, the test 'works' by skipping test_main.  Loading www.pythontest.net refers one to https://github.com/python/pythontestdotnet/.  Pinging contributors there.

**Comment by vstinner** [comment]
http://www.pythontest.net/unicode/7.0.0/NormalizationTest.txt exists, but not http://www.pythontest.net/unicode/8.0.0/NormalizationTest.txt nor http://www.pythontest.net/unicode/9.0.0/NormalizationTest.txt

Maybe the dev who upgrade Unicode to 8.0 and then 9.0 forgot to upload required files to the pythontest website?

I confirm that 8.0 and 9.0 lacks from https://github.com/python/pythontestdotnet/tree/master/www/unicode

**Comment by brettcannon** [comment]
Benjamin did the update to 9.0.0.

We should probably update [Tools/unicode/makeunicodedata.py](https://github.com/python/cpython/blob/main/Tools/unicode/makeunicodedata.py) to print out in the end that the appropriate file needs to be added to pythontest.net \*\*before** merging an update to unicodedata.

**Comment by benjaminp** [comment]
We should change the tests to fail if they get a 404.

**Comment by vstinner** [comment]
Benjamin: "We should change the tests to fail if they get a 404."

Good idea. Currently, the test is explicitly skipped on this case. Since "-u urlfetch" option must be explicitly passed on the command line, it makes sense to fail on that case.

I proposed https://github.com/python/cpython/pull/905 change for that. Not sure if it's worth to backport such change to older Python versions?

**Comment by vstinner** [comment]
New changeset 722a3af092b94983aa26f5e591fb1b45e2c2a0ff by Victor Stinner in branch 'master':
bpo-29887: Test normalization now fails if download fails (#905)
https://github.com/python/cpython/commit/722a3af092b94983aa26f5e591fb1b45e2c2a0ff

**Comment by vstinner** [comment]
Oh, Zachary reported me the following failure which is legitimate. The code doesn't handle correctly read-only library directory.

The test should try to write the file in a temporary file, or simply skip the test.

http://buildbot.python.org/all/builders/x86%20Gentoo%20Installed%20with%20X%203.x/builds/500/steps/test/logs/stdio

\======================================================================
FAIL: test_main (test.test_normalization.NormalizationTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.installed/build/target/lib/python3.7/test/test_normalization.py", line 42, in test_main
    check=check_version)
PermissionError: [Errno 13] Permission denied: '/buildbot/buildarea/3.x.ware-gentoo-x86.installed/build/target/lib/python3.7/test/data/NormalizationTest.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/buildbot/buildarea/3.x.ware-gentoo-x86.installed/build/target/lib/python3.7/test/test_normalization.py", line 44, in test_main
    self.fail(f"Could not retrieve {TESTDATAURL}")
AssertionError: Could not retrieve http://www.pythontest.net/unicode/9.0.0/NormalizationTest.txt
```


----------------------------------------------------------------------
Ran 2 tests in 0.149s

**Comment by vstinner** [comment]
> The test should try to write the file in a temporary file, or simply skip the test.

I proposed https://github.com/python/cpython/pull/1196 to skip the test in that case.

Creating a temporary file is more complex since the API doesn't work as a context manager, and it's unclear who would be responsible to remove the temporary file.

**Comment by vstinner** [comment]
New changeset d13d54748d3a7db023d9db37223ea7d40bb8f8e3 by Victor Stinner in branch 'master':
bpo-29887: test_normalization handles PermissionError (bpo-1196)
https://github.com/python/cpython/commit/d13d54748d3a7db023d9db37223ea7d40bb8f8e3

**Comment by vstinner** [comment]
Cool! "x86 Gentoo Installed with X 3.x" succeeded.

**Comment by vstinner** [comment]
New changeset 51f40a81a4acbc85cb1034750fb16cb1854b2315 by Victor Stinner (Mariatta) in branch '3.6':
[3.6] bpo-29887: Test normalization now fails if download fails (GH-905) (bpo-2271)
https://github.com/python/cpython/commit/51f40a81a4acbc85cb1034750fb16cb1854b2315

**Comment by vstinner** [comment]
New changeset acdf159b245aaac28f54dd10606911386ab39058 by Victor Stinner in branch '3.6':
bpo-29887: test_normalization handles PermissionError (bpo-1196) (bpo-2275)
https://github.com/python/cpython/commit/acdf159b245aaac28f54dd10606911386ab39058

**Comment by vstinner** [comment]
New changeset 070ba85a8f45819d9197bce4541cd594d79d247c by Victor Stinner (Mariatta) in branch '3.5':
[3.5] bpo-29887: Test normalization now fails if download fails (GH-905) (bpo-2272)
https://github.com/python/cpython/commit/070ba85a8f45819d9197bce4541cd594d79d247c
