### ISSUE TITLE
struct.Struct Addition

### ISSUE THREAD

**Issue by 1b8b9392-df29-400a-8625-f44843db437b** [python/cpython#74089]
BPO | [29903](https://bugs.python.org/issue29903)
--- | :---
Nosy | @rhettinger, @mdickinson, @vstinner, @meadori, @vadmium, @serhiy-storchaka, @palaviv
PRs | <li>python/cpython#817</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-21.23:37:22.136>
created_at = <Date 2017-03-25.15:44:48.389>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'struct.Struct Addition'
updated_at = <Date 2017-04-21.23:37:22.134>
user = 'https://github.com/palaviv'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-21.23:37:22.134>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-21.23:37:22.136>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-03-25.15:44:48.389>
creator = 'palaviv'
dependencies = []
files = []
hgrepos = []
issue_num = 29903
keywords = []
message_count = 6.0
messages = ['290486', '290488', '290490', '290495', '290501', '292082']
nosy_count = 7.0
nosy_names = ['rhettinger', 'mark.dickinson', 'vstinner', 'meador.inge', 'martin.panter', 'serhiy.storchaka', 'palaviv']
pr_nums = ['817']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29903'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
I would like to suggest that the struct.Struct class will support addition. For example you will be able to do:

```pycon
>>> s1 = Struct(">L")
>>> s2 = Struct(">B")
>>> s3 = s1 + s2
>>> s3.format
b">LB"
```

**Comment by serhiy-storchaka** [comment]
What is the purpose of this feature? Note that the layout of the structure consisting of two structures is not the same as the layout of the structure consisting of the same fields as separate structures.

```c
struct {
    struct {
        char a;
        short b;
    } s1;
    struct {
        char c;
        int d;
    } s2;
}
```


and

```c
struct {
    char a;
    short b;
    char c;
    int d;
}
```


can have different sizes and offsets of fields.

As for the concrete implementation, it looks to me that Struct('2L') + Struct('25B') results to Struct('2L5B').

**Comment by rhettinger** [comment]
I concur with Serhiy that this proposal is likely to cause more problems than it solves.

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
I have two use cases for this feature:
1.

```c
struct a {
    int a;
#ifdef VER2
    unsigned int b;
#endif
}
```


```pycon
Now I may do:
>>> ver1 = Struct("i")
>>> ver2 = ver1 + Struct("I")
```


2.

```c
struct a {
    int a;
    union inner {
        int b;
        unsigned int c;
    } u;
}
```


```pycon
As you can see with this feature I may do:
>>> start = Struct("i")
>>> union_b = Struct("i")
>>> union_c = Struct("I")
>>> version_a = start + union_b
>>> version_b = start + union_c
```


If you have a big struct with many options in the union this save's copying the initial format.

> As for the concrete implementation, it looks to me that Struct('2L') + Struct('25B') results to Struct('2L5B').

I will fix the case when there is no format provided.

**Comment by vadmium** [comment]
For the native alignment case (prefix code @), perhaps you can already use the “ctypes” module, which supports structures with more complicated embedded fields.

For the the unaligned modes (prefixes =, \<, \> and !), I am a little sympathetic. In the past, I wanted to make various structures that extended from a common base structure:

```py
HSF_VOL_DESC = Struct("< B 5s B")

# Python 3's "Struct.format" is a byte string!
NSR_DESC = Struct(HSF_VOL_DESC.format.decode() + "B")
```


But I think if bpo-21071 was fixed (change Struct.format to text string, or perhaps add a new attribute), I would be happy enough writing

```py
NSR_DESC = Struct(HSF_VOL_DESC.format_str + "B")
```


Transforming Aviv’s examples:

```py
s3 = Struct(s1.format_str + s2.format_str[1:])
s3 = Struct(s1.format_str + "B")  # if s2 is not needed on its own
ver2 = Struct(ver1.format_str + "I")
version_a = Struct(start.format_str + union_b.format_str[1:])
```

**Comment by vstinner** [comment]
I dislike this feature. I reject it: Serhiy, Raymond and me dislike it.

I never needed this feature and a correct implementation can be very complex if you have to take care of endian, alignement, etc. It's trivial to implement you own add using the format attribute if you want the simple implementation format1+format2.
