### ISSUE TITLE
ElementTree.fromstring raises undocumented UnicodeError

### ISSUE THREAD

**Issue by 1bc9703c-451a-4e27-ba2c-90664e117b42** [python/cpython#74082]
BPO | [29896](https://bugs.python.org/issue29896)
--- | :---
Nosy | @terryjreedy, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-25.04:28:39.564>
created_at = <Date 2017-03-24.14:34:37.981>
labels = ['type-bug', 'invalid', 'docs']
title = 'ElementTree.fromstring raises undocumented UnicodeError'
updated_at = <Date 2017-03-25.04:28:39.547>
user = 'https://bugs.python.org/vfaronov'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-25.04:28:39.547>
actor = 'r.david.murray'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-25.04:28:39.564>
closer = 'r.david.murray'
components = ['Documentation']
creation = <Date 2017-03-24.14:34:37.981>
creator = 'vfaronov'
dependencies = []
files = []
hgrepos = []
issue_num = 29896
keywords = []
message_count = 3.0
messages = ['290091', '290308', '290463']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'r.david.murray', 'docs@python', 'vfaronov']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29896'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 1bc9703c-451a-4e27-ba2c-90664e117b42** [comment]
```pycon
>>> from xml.etree import ElementTree as ET
>>> ET.fromstring(b'<\xC4/>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.6/xml/etree/ElementTree.py", line 1314, in XML
    parser.feed(text)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc4 in position 0: invalid continuation byt
e
```


The documentation for xml.etree.ElementTree does not mention that it can raise UnicodeError, only ParseError.

I think that either the above error should be wrapped in a ParseError, or the documentation should be amended.

This happens at least on 3.6, 3.5 and 2.7.

**Comment by terryjreedy** [comment]
I disagree.  The docs only sporadically mention specific exceptions for specific functions.  UnicodeDecodeError can occur any place bytes are decoded to unicode.  I think this should be closed.

Builtin exceptions are documented in https://docs.python.org/3/library/exceptions.html.  Module docs document additional exceptions defined in a module.  ParseError is one such.  https://docs.python.org/3/library/xml.etree.elementtree.html#exceptions.  It is not specifically mentioned in the entry for fromstring or .feed.

I also disagree that the decode error should be wrapped as a parse error.  It happens before parsing in the data preparation step, and the UnicodeDecodeError message give 3 pieces of information specific to the problem.

**Comment by bitdancer** [comment]
Agreed with Terry.  The general policy in Python is that we let errors bubble up unless there is a good reason to do something else with them.  And errors that bubble up are not, in general, documented.  (In short, Python is not Java :)
