### ISSUE TITLE
zlib missing when --enable--optimizations option appended

### ISSUE THREAD

**Issue by e5aaf2ca-3b8d-4d9b-91bd-b87a18061e02** [python/cpython#74085]
BPO | [29899](https://bugs.python.org/issue29899)
--- | :---
Nosy | @vstinner, @ned-deily, @yuanzimiaoKyren, @iritkatriel
Files | <li>[config.log](https://bugs.python.org/file46757/config.log "Uploaded as text/x-log at 2017-03-27.11:46:39 by @yuanzimiaoKyren")</li><li>[make.log](https://bugs.python.org/file46758/make.log "Uploaded as text/x-log at 2017-03-27.11:47:09 by @yuanzimiaoKyren")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-12-09.00:20:27.362>
created_at = <Date 2017-03-25.05:19:41.159>
labels = ['type-bug']
title = 'zlib missing when --enable--optimizations option appended'
updated_at = <Date 2021-12-09.00:20:27.361>
user = 'https://bugs.python.org/kyren'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-09.00:20:27.361>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-12-09.00:20:27.362>
closer = 'iritkatriel'
components = []
creation = <Date 2017-03-25.05:19:41.159>
creator = 'kyren \xe5\x8e\x9f\xe5\xad\x90\xe5\x96\xb5'
dependencies = []
files = ['46757', '46758']
hgrepos = []
issue_num = 29899
keywords = []
message_count = 9.0
messages = ['290465', '290485', '290516', '290581', '290591', '290592', '290597', '290598', '408057']
nosy_count = 5.0
nosy_names = ['vstinner', 'ned.deily', 'kyren \xe5\x8e\x9f\xe5\xad\x90\xe5\x96\xb5', 'kyren', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29899'
versions = ['Python 3.3']
```

</p></details>

**Comment by e5aaf2ca-3b8d-4d9b-91bd-b87a18061e02** [comment]
i think it happens to all versions that recognizes the optimizations option. At least I confirmed python version 3.4.6, 3.5.3, 3.6.1, when `--enable-optimizations` is appended, `zlib` cannot be imported, `No module named zlib`. I'm working on Ubuntu 14.04 by the way. I don't know if it's system specific.

**Comment by ned-deily** [comment]
--enable-optimizations does not exist in Python 3.4.x so any failures there must be due to something else.  Are there any build errors?  Can you show exactly where the message comes from?

**Comment by 2b20c3a9-51f8-4f76-9d5b-c7b5c817b236** [comment]
There's no build errors. The compiling and installing process is error-free. Take 3.5.3 as example, it's all good until you enter 3.5.3 python shell and type `import zlib`, it gives `No module name zlib`. I solved by make a `libz.so` link in my `/lib` dir to the `libz.so.1` file in my `/lib/x86_64-linux-gnu` dir according to a thread in Ubuntu forum. It may be system specific, I don't know yet.

**Comment by vstinner** [comment]
Can you please attach config.log file? And maybe also redirect the output of "make" into a log file and then attach this log file as well? Example: make 2\>&1 \>make.log.

**Comment by 2b20c3a9-51f8-4f76-9d5b-c7b5c817b236** [comment]
This is the config.log.

**Comment by 2b20c3a9-51f8-4f76-9d5b-c7b5c817b236** [comment]
This is make.log.

**Comment by vstinner** [comment]
Strange, I don't see any obvious error related to the C "z" lib or to the Python "zlib" module.

Example on my system:

```pycon
haypo@selma$ python3
Python 3.5.2 (default, Sep 14 2016, 11:28:32) 
[GCC 6.2.1 20160901 (Red Hat 6.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import zlib
>>> zlib
<module 'zlib' from '/usr/lib64/python3.5/lib-dynload/zlib.cpython-35m-x86_64-linux-gnu.so'>
>>> 
haypo@selma$ ldd /usr/lib64/python3.5/lib-dynload/zlib.cpython-35m-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007fff22f2e000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f88e1fe0000)
	libpython3.5m.so.1.0 => /lib64/libpython3.5m.so.1.0 (0x00007f88e1b13000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f88e18f5000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f88e152f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f88e132b000)
	libutil.so.1 => /lib64/libutil.so.1 (0x00007f88e1126000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f88e0e1d000)
	/lib64/ld-linux-x86-64.so.2 (0x000055d00b915000)
haypo@selma$ ldd /usr/lib64/python3.5/lib-dynload/zlib.cpython-35m-x86_64-linux-gnu.so^C
haypo@selma$ ls -l /lib64/libz.so.1
lrwxrwxrwx. 1 root root 13  5 févr.  2016 /lib64/libz.so.1 -> libz.so.1.2.8
```


Can you check if you have a "zlib.(...).so" file in /usr/lib64/python3.5/lib-dynload/? (ajust to the right directory)

**Comment by vstinner** [comment]
See also the issue bpo-29641 "make install failure when using ./configure --enable-optimizations".
