### ISSUE TITLE
PYTHONLEGACYWINDOWSIOENCODING isn't implemented

### ISSUE THREAD

**Issue by eryksun** [python/cpython#74084]
BPO | [29898](https://bugs.python.org/issue29898)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @ezio-melotti, @berkerpeksag, @zware, @eryksun, @zooba
PRs | <li>python/cpython#1576</li><li>python/cpython#1609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-16.21:32:02.484>
created_at = <Date 2017-03-24.22:34:03.001>
labels = ['type-bug', 'OS-windows', 'expert-IO', '3.7', 'expert-unicode', 'docs']
title = "PYTHONLEGACYWINDOWSIOENCODING isn't implemented"
updated_at = <Date 2017-05-16.21:32:02.483>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-16.21:32:02.483>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-16.21:32:02.484>
closer = 'berker.peksag'
components = ['Documentation', 'Unicode', 'Windows', 'IO']
creation = <Date 2017-03-24.22:34:03.001>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 29898
keywords = []
message_count = 6.0
messages = ['290240', '290357', '290467', '290489', '293756', '293798']
nosy_count = 9.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'ezio.melotti', 'docs@python', 'berker.peksag', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = ['1576', '1609']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29898'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by eryksun** [comment]
The environment variable PYTHONLEGACYWINDOWSIOENCODING is documented here:

https://docs.python.org/3/using/cmdline.html#envvar-PYTHONLEGACYWINDOWSIOENCODING

but not actually implemented. Also, I think setting PYTHONIOENCODING to anything except UTF-8 should disable using io.\_WindowsConsoleIO.

**Comment by zooba** [comment]
It's actually called "PYTHONLEGACYWINDOWSSTDIO" in [Python/pylifecycle.c](https://github.com/python/cpython/blob/main/Python/pylifecycle.c), which is also what PEP-528 says it should be, so this is a docs issue.

You're correct that PYTHONIOENCODING is overridden by detection of a real console, however, PYTHONIOENCODING doesn't currently set a flag anywhere, and the (required for compatibility) defaults on Windows would make it look like it's always been set to something else.

In my opinion, you should set PYTHONLEGACYWINDOWSSTDIO to indicate that even though we know the incoming encoding (Unicode from an interactive console), you don't care and you want to override it with a default value. Then use PYTHONIOENCODING to set that default value. This is most consistent with the existing use of PYTHONIOENCODING (it's the default unless you know exactly which encoding you are getting).

**Comment by eryksun** [comment]
I prefer the name PYTHONLEGACYWINDOWSIOENCODING for symmetry with both PYTHONIOENCODING and PYTHONLEGACYWINDOWSFSENCODING, but I suppose you changed it to make it more visually distinguished from the latter.

I discovered this issue due to the modified behavior of PYTHONIOENCODING. It's not really a disruptive change, but it looks wrong based solely on the --help text description of PYTHONIOENCODING. An alternative would be to set Py_LegacyWindowsStdioFlag in \_Py_InitializeEx_Private either when PYTHONLEGACYWINDOWSSTDIO is set or when PYTHONIOENCODING isn't a case-insensitive match for "utf-8" with an optional :errors spec. That way people get exactly what they asked for, even if it's mojibake nonsense given the console's current input and output codepages.

**Comment by zooba** [comment]
Sure, but you're proposing a change to a correctly documented (apart from the variable name) and released behavior. It can't be changed in 3.6, and I don't see a compelling reason to have different behavior in 3.7.

**Comment by berkerpeksag** [comment]
New changeset 87fa8a780e9045a26c735f085c07bba4b2d0be60 by Berker Peksag in branch 'master':
bpo-29898: Fix incorrect env variable name (GH-1576)
https://github.com/python/cpython/commit/87fa8a780e9045a26c735f085c07bba4b2d0be60

**Comment by berkerpeksag** [comment]
New changeset 0d267041c40a3ab655676b885c0ba35ed9685848 by Berker Peksag in branch '3.6':
bpo-29898: Fix incorrect env variable name (GH-1576)
https://github.com/python/cpython/commit/0d267041c40a3ab655676b885c0ba35ed9685848
