### ISSUE TITLE
Distutils blows up with an incorrect pypirc, should be caught

### ISSUE THREAD

**Issue by 57414627-bc7f-4a16-8517-231c44d27ccc** [python/cpython#74081]
BPO | [29895](https://bugs.python.org/issue29895)
--- | :---
Nosy | @merwok, @berkerpeksag, @zooba, @dstufft
Files | <li>[issue29895_test.diff](https://bugs.python.org/file46863/issue29895_test.diff "Uploaded as text/plain at 2017-05-14.06:33:06 by @berkerpeksag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-03.18:21:24.376>
created_at = <Date 2017-03-24.14:24:33.594>
labels = ['3.7', 'type-bug', 'library']
title = 'Distutils blows up with an incorrect pypirc, should be caught'
updated_at = <Date 2021-02-03.18:21:24.375>
user = 'https://bugs.python.org/TommyCarpenter'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-03.18:21:24.375>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-03.18:21:24.376>
closer = 'steve.dower'
components = ['Distutils']
creation = <Date 2017-03-24.14:24:33.594>
creator = 'Tommy Carpenter'
dependencies = []
files = ['46863']
hgrepos = []
issue_num = 29895
keywords = ['patch']
message_count = 4.0
messages = ['290090', '293637', '293860', '386351']
nosy_count = 5.0
nosy_names = ['eric.araujo', 'berker.peksag', 'steve.dower', 'dstufft', 'Tommy Carpenter']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29895'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 57414627-bc7f-4a16-8517-231c44d27ccc** [comment]
Full details and stacktrace are at: http://stackoverflow.com/questions/43001446/python-pypi-configparser-blowing-up-when-pointing-to-certain-repo/43001770#43001770

Essentially, I had an index-servers section that listed a repo, that was not listed in the remainder of the .pypirc file. Instead of distutils catching this, it blows up in an obscure ConfigParsing error.

**Comment by berkerpeksag** [comment]
Thanks for the report, Tommy. I think the configparser exception is pretty descriptive here. You had a .pypirc file like the following:

    [distutils]
    index-servers = 
      pypi
      global

    [pypi]
    username:spam
    password:eggs

You passed -r global and you got:

```pytb
    Traceback (most recent call last):
      ...
    ConfigParser.NoSectionError: No section: 'global'
```


Which says you don't have a section named 'global' in your .pypirc.

There are three options here:

a) do nothing
b) catch configparser.NoSectionError and raise a distutils exception with better wording. Since we don't have DistutilsConfigError, I'm not sure which one is more appropriate here.
c) ignore configparser.NoSectionError if server name cannot be found in sections in PyPIRCCommand.\_read_pypirc(). IMO this is the worst option.

Here is a test case to demonstrate the problem described at the SO question.

**Comment by 57414627-bc7f-4a16-8517-231c44d27ccc** [comment]
Hi,

I think option B might be best, because the issue was that I didn't know at first that the problem was in my .pypirc. I think this stack trace is not the most elegant way for the user to figure that out. Maybe catching this and then presenting a human readable error to the user would be better.
