### ISSUE TITLE
Overlapping tests between list_tests and seq_tests

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74098]
BPO | [29912](https://bugs.python.org/issue29912)
--- | :---
Nosy | @brettcannon, @DimitrisJim
PRs | <li>python/cpython#847</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-27.19:36:11.034>
created_at = <Date 2017-03-26.23:42:37.128>
labels = ['type-bug', 'tests']
title = 'Overlapping tests between list_tests and seq_tests'
updated_at = <Date 2017-03-27.19:36:11.034>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.19:36:11.034>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-27.19:36:11.034>
closer = 'brett.cannon'
components = ['Tests']
creation = <Date 2017-03-26.23:42:37.128>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29912
keywords = []
message_count = 3.0
messages = ['290550', '290590', '290638']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'Jim Fasarakis-Hilliard']
pr_nums = ['847']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29912'
versions = []
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Seems the CommonTests class defined in list_tests duplicates the testing performed by seq_tests.CommonTests in the following functions:

    test_index, test_count

Additionally, a part of test_imul from list_tests.CommonTests can be moved to seq_tests.CommonTests. (specifically, up until `        self.assertEqual(u, self.type2test([]))`).

Am I missing some non-obvious thing here or can I safely remove the two test functions in list_tests.CommonTests and move (while also adding a super call) part of test_imul from list_tests.CommonTests to test_imul in seq_tests.CommonTests?

Some links:

[1a] seq_tests test_index: https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/seq_tests.py#L363
[1b] list_tests test_index:
https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/list_tests.py#L376

[2a] seq_tests test_count:
https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/seq_tests.py#L344
[2b] list_tests test_count:
https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/list_tests.py#L357

[3a] seq_tests test_imul:
https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/seq_tests.py#L300
[3b] list_tests test_imul:
https://github.com/python/cpython/blob/1e73dbbc29c96d0739ffef92db36f63aa1aa30da/Lib/test/list_tests.py#L550

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Correction: test_index \*partially* duplicates the base class method. It too can be modified to use super like test_imul.

**Comment by brettcannon** [comment]
New changeset d702c50049207d825c1d5925fbc7306514fa9a0a by Brett Cannon (Jim Fasarakis-Hilliard) in branch 'master':
bpo-29912: Remove redundant tests in list_tests that are found in seq_tests (GH-847)
https://github.com/python/cpython/commit/d702c50049207d825c1d5925fbc7306514fa9a0a
