### ISSUE TITLE
Fix a number of error message typos

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74090]
BPO | [29904](https://bugs.python.org/issue29904)
--- | :---
Nosy | @serhiy-storchaka, @DimitrisJim
PRs | <li>python/cpython#818</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-28.15:01:27.168>
created_at = <Date 2017-03-25.17:35:41.379>
labels = ['3.7']
title = 'Fix a number of error message typos'
updated_at = <Date 2017-03-28.15:01:27.167>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-28.15:01:27.167>
actor = 'Jim Fasarakis-Hilliard'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-28.15:01:27.168>
closer = 'Jim Fasarakis-Hilliard'
components = []
creation = <Date 2017-03-25.17:35:41.379>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29904
keywords = []
message_count = 3.0
messages = ['290491', '290493', '290494']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Jim Fasarakis-Hilliard']
pr_nums = ['818']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29904'
versions = ['Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Specifically, the list I've currently found in .py files:

- \_pyio.py:

```py
    ValueError("flush of closed file")
    ValueError("flush of closed file")
```


"of" -\> "on" for both.

- configparser.py:

```py
    ValueError("Required argument `source' not given.")
    ValueError("Cannot specify both `filename' and `source'. "
```


fix \` on the quotes on argument names.

- windows_utils.py

```py
    ValueError("I/O operatioon on closed pipe")
```


"operatioon" -\> "operation"

- proactor_events.py, asynchat.py:

    TypeError('data argument must be byte-ish (%r)',
    raise TypeError('data argument must be byte-ish (%r)',

AFAIK, "byte-ish" isn't used elsewhere, the author probably mean to go for "bytes-like object".

- \_header_value_parser.py:

    errors.HeaderParseError("expected atom at a start of "

"at a start of " -\> "at the start of "

- http/cookiejar.py:

    raise ValueError("filename must be string-like")
    
I think "must be a str" was intended.

**Comment by serhiy-storchaka** [comment]
Do you want to create a pull request?

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Sure, Serhiy, I'll make a PR in a bit.
