### ISSUE TITLE
types.coroutine monkey patches original function

### ISSUE THREAD

**Issue by f27798ab-a662-4975-abb2-6b742415affc** [python/cpython#74095]
BPO | [29909](https://bugs.python.org/issue29909)
--- | :---
Nosy | @bitdancer, @1st1
Files | <li>[types.coroutine.py](https://bugs.python.org/file46756/types.coroutine.py "Uploaded as text/plain at 2017-03-27.00:03:11 by Omnifarious"): A possible fix</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/1st1'
closed_at = None
created_at = <Date 2017-03-26.08:59:57.335>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'types.coroutine monkey patches original function'
updated_at = <Date 2017-03-27.00:03:13.208>
user = 'https://bugs.python.org/Omnifarious'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.00:03:13.208>
actor = 'Omnifarious'
assignee = 'yselivanov'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-03-26.08:59:57.335>
creator = 'Omnifarious'
dependencies = []
files = ['46756']
hgrepos = []
issue_num = 29909
keywords = []
message_count = 5.0
messages = ['290518', '290532', '290534', '290538', '290551']
nosy_count = 3.0
nosy_names = ['Omnifarious', 'r.david.murray', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29909'
versions = ['Python 3.7']
```

</p></details>

**Comment by f27798ab-a662-4975-abb2-6b742415affc** [comment]
The types.coroutine decorator for Python 3.6 (and I suspect for Python 3.6.1 as well) simply monkey patches the function it's passed and then returns it. This results in behavior that I found somewhat surprising.

```py
def bar():
   yield 5

foo = types.coroutine(bar)
```


foo is bar

And, so now both foo and bar are now awaitable. I wasn't really expecting this, and while it's minor, it also doesn't really seem like the right thing to do.

**Comment by bitdancer** [comment]
Yes, that looks wrong to me.  IMO it should be returning a new function object, not updating the \_\_code__ of the existing object.  I couldn't figure when that is actually triggered, though.  

There are also some other oddnesses, given the definition of 'coroutine' in the 'types' module docs.  type(x) returns 'coroutine' only when you actually \*call* the async def function.  I think that's correct, but the docs need rewording.  However, if I call coroutine on the equivalent non-async-def generator, types(x()) returns generator, not coroutine.  So it doesn't seem to be doing what it says on the label, at least not in all cases.

**Comment by bitdancer** [comment]
Oops, I didn't meant to close this.

**Comment by 1st1** [comment]
Yeah, we can fix this. However, I don't want to push the fix to 3.6, too much code uses this function now. So it's going to be 3.7 only.

**Comment by f27798ab-a662-4975-abb2-6b742415affc** [comment]
Here's an update to types.coroutine that fixes the problem for me.

**Comment by kumaraditya303** [comment]
Is it worth changing now? I don't think as it can cause regression in code relying on this.
