### ISSUE TITLE
TypeErrors not formatting values correctly

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74091]
BPO | [29905](https://bugs.python.org/issue29905)
--- | :---
Nosy | @josiahcarlson, @vstinner, @giampaolo, @1st1, @DimitrisJim
PRs | <li>python/cpython#819</li><li>python/cpython#993</li><li>python/cpython#2061</li><li>python/cpython#2060</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-10.09:00:18.966>
created_at = <Date 2017-03-25.21:10:20.380>
labels = ['3.7', 'type-bug', 'library', 'expert-asyncio']
title = 'TypeErrors not formatting values correctly'
updated_at = <Date 2017-06-10.09:00:18.953>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.09:00:18.953>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-10.09:00:18.966>
closer = 'vstinner'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-03-25.21:10:20.380>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 29905
keywords = []
message_count = 3.0
messages = ['290499', '291134', '295624']
nosy_count = 6.0
nosy_names = ['josiahcarlson', 'vstinner', 'giampaolo.rodola', 'stutzbach', 'yselivanov', 'Jim Fasarakis-Hilliard']
pr_nums = ['819', '993', '2061', '2060']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29905'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Specifically, in both [Lib/async/proactor_events.py](https://github.com/python/cpython/blob/main/Lib/async/proactor_events.py) and asynchat.py there's a comma where a % should be thereby not formatting the value correctly:

    TypeError('data argument must be byte-ish (%r)', type(data))
    TypeError('data argument must be byte-ish (%r)', type(data))

proposed fix is to change them to:

    TypeError('data argument must be a bytes-like object, not %r' % type(data).__name__)
    TypeError('data argument must be a bytes-like object, not %r' % type(data).__name__)

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
As per #bpo-25002 and, specifically #msg250151, the TypeError in `asynchat` should probably not be included, I'll just make a PR for the TypeError in asyncio/proactor_events

**Comment by vstinner** [comment]
It seems like the bug has been fixed in all branches, so I close the issue.
