### ISSUE TITLE
Uninstall command line in Windows registry does not uninstall

### ISSUE THREAD

**Issue by f7a29477-11b6-4add-a132-918438c57010** [python/cpython#74097]
BPO | [29911](https://bugs.python.org/issue29911)
--- | :---
Nosy | @pfmoore, @tjguk, @zooba, @chrullrich
PRs | <li>python/cpython#5119</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2018-01-18.03:34:25.141>
created_at = <Date 2017-03-26.18:09:34.235>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'Uninstall command line in Windows registry does not uninstall'
updated_at = <Date 2018-01-18.03:34:25.140>
user = 'https://github.com/chrullrich'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-18.03:34:25.140>
actor = 'steve.dower'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2018-01-18.03:34:25.141>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-03-26.18:09:34.235>
creator = 'chrullrich'
dependencies = []
files = []
hgrepos = []
issue_num = 29911
keywords = ['patch']
message_count = 3.0
messages = ['290544', '290554', '290558']
nosy_count = 4.0
nosy_names = ['paul.moore', 'tim.golden', 'steve.dower', 'chrullrich']
pr_nums = ['5119']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29911'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
The Windows installation package registers a command line for uninstalling the package. Running this command line does not uninstall the package.

The command line ends with "/modify". For uninstallation, it should be "/passive /uninstall".

Windows provides for separate command lines for modifying and uninstalling packages to be set in the "Uninstall" subkey:

- ModifyPath: Command line for modifying the package
- UninstallString: Command line for removing the package

By setting both keys, the ARP control panel will display separate buttons for the two operations.

Having an uninstallation command line that does not do what it says, and in fact causes modal UI to be presented, also interferes with automated package management.

Ceterum censeo: This bug would have been avoided by using MSI as the distribution package format, because "msiexec /qn /x [ProductCode]" would have been correct regardless of what the registry says, and even if the registry does not say anything because the Uninstall key (as well as the uninstaller executable itself) were actually deleted months ago as part of some expired user profile. See bug bpo-25166.

**Comment by zooba** [comment]
I'll take a look at having separate commands set, but the component responsible is external and this may be an issue for them.

Also, for future reference, continuing to point out that you would have preferred an MSI does not help you get faster assistance, and does not count as more "votes" towards any change. Continuing to add it will eventually annoy the volunteers who work on CPython sufficiently that you may find it very hard to get any attention at all.

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
Thank you.


As for the pointing out: It worked for Cato, didn't it? He may not have lived to see it, but his perseverance in the face of rejection eventually brought about the years-long bloody war he had dreamed about.

(Any historical inaccuracies in the above are the property of the author.)
