### ISSUE TITLE
Remove unused imports found by pyflakes

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74105]
BPO | [29919](https://bugs.python.org/issue29919)
--- | :---
Nosy | @terryjreedy, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#137</li><li>python/cpython#2105</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-03-27.14:06:56.092>
created_at = <Date 2017-03-27.13:05:13.378>
labels = ['type-feature', '3.7']
title = 'Remove unused imports found by pyflakes'
updated_at = <Date 2017-06-11.09:54:32.513>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-11.09:54:32.513>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-03-27.14:06:56.092>
closer = 'vstinner'
components = []
creation = <Date 2017-03-27.13:05:13.378>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29919
keywords = []
message_count = 5.0
messages = ['290607', '290613', '290614', '295695', '295696']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'vstinner', 'serhiy.storchaka']
pr_nums = ['137', '2105']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29919'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Attached PR removes unused imports found by pyflakes. It makes also minor PEP-8 coding style fixes on modified imports.

**Comment by serhiy-storchaka** [comment]
LGTM.

**Comment by vstinner** [comment]
New changeset d6debb24e06152a827769b0cac24c47deccdeac1 by Victor Stinner in branch 'master':
bpo-29919: Remove unused imports found by pyflakes (#137)
https://github.com/python/cpython/commit/d6debb24e06152a827769b0cac24c47deccdeac1

**Comment by terryjreedy** [comment]
I will backport idlelib changes that apply.

**Comment by terryjreedy** [comment]
New changeset c6696feb09a8cf13e13e42ed9cc0b8c2e8795800 by terryjreedy in branch '3.6':
[3.6] bpo-29919 Remove unused imports from idlelib [GH-137] (bpo-2105)
https://github.com/python/cpython/commit/c6696feb09a8cf13e13e42ed9cc0b8c2e8795800
