### ISSUE TITLE
Wrong link target in PyMethodDef documentation

### ISSUE THREAD

**Issue by 84dd73fe-9313-425f-aae0-390228a90839** [python/cpython#74103]
BPO | [29917](https://bugs.python.org/issue29917)
--- | :---
Nosy | @orsenthil, @serhiy-storchaka, @MSeifert04, @csabella
PRs | <li>python/cpython#890</li><li>python/cpython#890</li><li>python/cpython#894</li><li>python/cpython#895</li><li>python/cpython#896</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-30.05:30:26.320>
created_at = <Date 2017-03-27.10:31:12.598>
labels = ['type-bug', '3.7', 'docs']
title = 'Wrong link target in PyMethodDef documentation'
updated_at = <Date 2017-03-30.05:30:26.320>
user = 'https://github.com/MSeifert04'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-30.05:30:26.320>
actor = 'orsenthil'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-03-30.05:30:26.320>
closer = 'orsenthil'
components = ['Documentation']
creation = <Date 2017-03-27.10:31:12.598>
creator = 'MSeifert'
dependencies = []
files = []
hgrepos = []
issue_num = 29917
keywords = []
message_count = 7.0
messages = ['290575', '290634', '290798', '290799', '290809', '290810', '290811']
nosy_count = 5.0
nosy_names = ['orsenthil', 'docs@python', 'serhiy.storchaka', 'MSeifert', 'cheryl.sabella']
pr_nums = ['890', '890', '894', '895', '896']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29917'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
The `link`-target of the "type" struct member is the python built-in "type".  See [1].

I think it should not be a link at all.

[1] https://docs.python.org/3.7/c-api/structures.html#c.PyMemberDef

**Comment by serhiy-storchaka** [comment]
Agree. I noticed this when making a review of [PR 831](https://github.com/python/cpython/pull/831), but forgot to open an issue.

**Comment by csabella** [comment]
I am working on a pull request for this issue.

**Comment by orsenthil** [comment]
New changeset c3c7ef088583cc12bd218138036d1edb6de9c63f by Senthil Kumaran (csabella) in branch 'master':
bpo-29917: DOC: Remove link from PyMethodDef (#890)
https://github.com/python/cpython/commit/c3c7ef088583cc12bd218138036d1edb6de9c63f

**Comment by orsenthil** [comment]
New changeset da6ad2f780d187fbfdea330d1037766ae7bdb778 by Senthil Kumaran in branch '3.6':
bpo-29917: DOC: Remove link from PyMethodDef (#890) (#894)
https://github.com/python/cpython/commit/da6ad2f780d187fbfdea330d1037766ae7bdb778

**Comment by orsenthil** [comment]
New changeset d1dbbaab01354f01faa696aff1280db3b349e354 by Senthil Kumaran in branch '3.5':
bpo-29917: DOC: Remove link from PyMethodDef (#890) (#895)
https://github.com/python/cpython/commit/d1dbbaab01354f01faa696aff1280db3b349e354

**Comment by orsenthil** [comment]
New changeset 3ceca68741f8a2d3a4436b6d54eae76aa5bcc4c5 by Senthil Kumaran in branch '2.7':
bpo-29917: DOC: Remove link from PyMethodDef (#890) (#896)
https://github.com/python/cpython/commit/3ceca68741f8a2d3a4436b6d54eae76aa5bcc4c5
