### ISSUE TITLE
No explicit documentation for PyGetSetDef and getter and setter C-API

### ISSUE THREAD

**Issue by 84dd73fe-9313-425f-aae0-390228a90839** [python/cpython#74102]
BPO | [29916](https://bugs.python.org/issue29916)
--- | :---
Nosy | @serhiy-storchaka, @MSeifert04
PRs | <li>python/cpython#831</li><li>python/cpython#3607</li><li>python/cpython#3609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-09-16.11:35:35.901>
created_at = <Date 2017-03-27.10:26:54.570>
labels = ['type-feature', '3.7', 'docs']
title = 'No explicit documentation for PyGetSetDef and getter and setter C-API'
updated_at = <Date 2017-09-16.11:36:24.520>
user = 'https://github.com/MSeifert04'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-16.11:36:24.520>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-09-16.11:35:35.901>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-03-27.10:26:54.570>
creator = 'MSeifert'
dependencies = []
files = []
hgrepos = []
issue_num = 29916
keywords = ['patch']
message_count = 5.0
messages = ['290574', '302263', '302332', '302333', '302334']
nosy_count = 3.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'MSeifert']
pr_nums = ['831', '3607', '3609']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29916'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
A copy of the struct definition can be found in the typeobject documentation [1]. There is also some explanation of the "closure" function pointer in the extending tutorial [2].

However the struct isn't explicitly defined as "c:type" so the 6 links to it in the documentations go nowhere.

I also submitted a pull request.

[1] https://docs.python.org/3.6/c-api/typeobj.html#c.PyTypeObject.tp_getset
[2] https://docs.python.org/3/extending/newtypes.html

**Comment by serhiy-storchaka** [comment]
New changeset da67e0d644bd3185efdaa4d15cc2ac0828ca83f9 by Serhiy Storchaka (Michael Seifert) in branch 'master':
bpo-29916: Include PyGetSetDef in C API extension documentation. (#831)
https://github.com/python/cpython/commit/da67e0d644bd3185efdaa4d15cc2ac0828ca83f9

**Comment by serhiy-storchaka** [comment]
New changeset 51ea80697b023595cdd79c7696589a04cc581693 by Serhiy Storchaka (Michael Seifert) in branch '3.6':
bpo-29916: Include PyGetSetDef in C API extension documentation. (#831) (bpo-3607)
https://github.com/python/cpython/commit/51ea80697b023595cdd79c7696589a04cc581693

**Comment by serhiy-storchaka** [comment]
New changeset 41376241e364e4f84cd14631634604edbd105da0 by Serhiy Storchaka (Michael Seifert) in branch '2.7':
bpo-29916: Include PyGetSetDef in C API extension documentation. (#831) (bpo-3609)
https://github.com/python/cpython/commit/41376241e364e4f84cd14631634604edbd105da0

**Comment by serhiy-storchaka** [comment]
Thank you Michael for your contribution.
