### ISSUE TITLE
Drop Mac OS X Tiger support in Python 3.7?

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74101]
BPO | [29915](https://bugs.python.org/issue29915)
--- | :---
Nosy | @warsaw, @rhettinger, @vstinner, @benjaminp, @ned-deily, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-03.10:37:42.442>
created_at = <Date 2017-03-27.09:29:04.736>
labels = ['build', '3.7']
title = 'Drop Mac OS X Tiger support in Python 3.7?'
updated_at = <Date 2018-02-27.19:34:03.144>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-27.19:34:03.144>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-03.10:37:42.442>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-03-27.09:29:04.736>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29915
keywords = []
message_count = 11.0
messages = ['290570', '290623', '290625', '290628', '290653', '292885', '311180', '311184', '311185', '311186', '313017']
nosy_count = 6.0
nosy_names = ['barry', 'rhettinger', 'vstinner', 'benjamin.peterson', 'ned.deily', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29915'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Hi,

Last september I already proposed the same thing for Python 3.6 (issue bpo-28099), but Ned Deily asked to keep OS X Tiger supper.

The Tiger buildbot fails since many years:
http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/479/steps/test/logs/stdio

It doesn't seem like anyone take care of this buildbot.

Mac OS X Tiger was released in 2004 (13 years ago). The last update was 10.4.11: November 14, 2007 (9 years ago).

"Support status: Unsupported as of September 2009, Safari support ended November 2010."
https://en.wikipedia.org/wiki/Mac_OS_X_Tiger

**Comment by rhettinger** [comment]
Is there any downside to keeping this code?

**Comment by ned-deily** [comment]
>The Tiger buildbot fails since many years:
>http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/479/steps/test/logs/stdio

That's not true.  The one failing test, test_uuid, was just added last month.  Note that the 3.5 Tiger buildbot has not test failures.

So, one question that perhaps you and Barry can answer is what is the significance of that failure.

>It doesn't seem like anyone take care of this buildbot.

That's also not true.  David Bolen, the owner of the buildbot, is very responsive to requests for updates of third-party libraries on the buildbot.

Getting back to the support of OS X 10.4, to the best of my knowledge we currently do not document anywhere exactly what levels of OS X we support.  We could do that and, yes, we could explicitly drop support for 10.4.  However, at the moment, there just seems to be this one issue which we should understand better before deciding anything.  But, more importantly, at the moment, the 10.4 Tiger buildbot is the \*only* working Mac buildbot we have.  Two other Mac buildbots we've had, the "Snow Leopard" and "Yosemite" buildbots have been off-line for many months.  Until we have other working OS X buildbots, the Tiger one should remain.  It is serving a useful purpose.

**Comment by ned-deily** [comment]
Here's where the Tiger 3.x buildbot started failing:

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/363

with this commit 0b8432538acf45d7a605fe68648b4712e8d9cee3

**Comment by vstinner** [comment]
Raymond Hettinger: "Is there any downside to keeping this code?"

I don't think that we have much code specific to Tiger, except maybe some skips in unit tests. Maybe we can just remove the buildbot but don't touch the code.

My issue is more that I would like to see green buildbots. I don't see the purpose of having a buildbot if it's known to be broken. It's a pain to recall which buildbots are known to be broken or not.


> That's not true.  The one failing test, test_uuid, was just added last month.  Note that the 3.5 Tiger buildbot has not test failures.

Ah? I didn't know. Maybe my issue was more that Tiger fails randomly. In fact, I don't recall exactly why I wanted to drop Tiger support :-)


> But, more importantly, at the moment, the 10.4 Tiger buildbot is the \*only* working Mac buildbot we have.

Oh wow, I didn't know. Travis CI provides Linux containers, AppVeyor provides Windows VMs. Is there a similar free service for macOS? Or maybe not free for everyone, but free for the Python CI?


> Here's where the Tiger 3.x buildbot started failing: (...)

I created the issue bpo-29925 for test_uuid failure.


> Until we have other working OS X buildbots, the Tiger one should remain.  It is serving a useful purpose.

My general view on buildbots is that one buildbot needs a maintainer or should go away.

Yeah, I have to long term plan to remove most buildbots :-D For example, the situation didn't evolved for the OpenIndiana buildbot...

**Comment by vstinner** [comment]
All tests pass again on 2.7, 3.5, 3.6 and master branches, so I have no more reason to drop Tiger support :-)

I close the issue. I may reopen it later if I find a better reason to drop Tiger support ;-)
