### ISSUE TITLE
ipaddress.ip_interface __lt__ check seems to be broken

### ISSUE THREAD

**Issue by 3a37abd6-e522-4049-958c-60aefc9639d0** [python/cpython#74117]
BPO | [29931](https://bugs.python.org/issue29931)
--- | :---
Nosy | @ncoghlan, @berkerpeksag, @serhiy-storchaka, @zhangyangyu, @Mariatta, @s-sanjay
PRs | <li>python/cpython#879</li><li>python/cpython#2217</li><li>python/cpython#2218</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-15.14:17:26.165>
created_at = <Date 2017-03-28.10:37:20.702>
labels = ['3.7', 'type-bug', 'library']
title = 'ipaddress.ip_interface __lt__ check seems to be broken'
updated_at = <Date 2017-06-15.14:17:26.164>
user = 'https://github.com/s-sanjay'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.14:17:26.164>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-15.14:17:26.165>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-03-28.10:37:20.702>
creator = 'Sanjay'
dependencies = []
files = []
hgrepos = []
issue_num = 29931
keywords = []
message_count = 7.0
messages = ['290695', '290700', '290964', '291112', '291684', '296098', '296099']
nosy_count = 7.0
nosy_names = ['ncoghlan', 'pmoody', 'berker.peksag', 'serhiy.storchaka', 'xiang.zhang', 'Mariatta', 'Sanjay']
pr_nums = ['879', '2217', '2218']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29931'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3a37abd6-e522-4049-958c-60aefc9639d0** [comment]
```pycon
The less than check for ip_interface behavior seems weird. I am not sure if this is by design. We are just comparing the network address but when network address is equal we should compare the ip address.
The expectation is if a < b is False then b <= a must be True
>>> import ipaddress
>>> a = ipaddress.ip_interface("1.1.1.1/24")
>>> b = ipaddress.ip_interface("1.1.1.2/24")
>>> a < b
False
>>> b <= a
False
>>> a == b
False
>>> 
This happens with both v4 and v6
The tests were passing because in ComparisonTests we were testing with prefix length of 32 which means the whole ip address became the network address.
I have made a fix here:
https://github.com/s-sanjay/cpython/commit/14975f58539308b7af5a1519705fb8cd95ad7951
I can add more tests and send PR but before that I wanted to confirm the behavior.
```

**Comment by serhiy-storchaka** [comment]
Indeed, this looks as a bug.

```pycon
>>> a < b
False
>>> b > a
True
```

**Comment by serhiy-storchaka** [comment]
New changeset 7bd8d3e794782582a4ad1c9749424fff86802c3e by Serhiy Storchaka (s-sanjay) in branch 'master':
bpo-29931 fix \_\_lt__ check in ipaddress.ip_interface for both v4 and v6. (#879)
https://github.com/python/cpython/commit/7bd8d3e794782582a4ad1c9749424fff86802c3e

**Comment by Mariatta** [comment]
Serhiy, just checking whether this needs backport? The PR has the backport to 3.5 and 3.6 labels, but it's not indicated in this ticket.
If it doesn't need backport, then perhaps we can close this issue.
Thanks.

**Comment by berkerpeksag** [comment]
I think we should backport this to at least 3.6.

**Comment by serhiy-storchaka** [comment]
New changeset cf58dfb44cc11d41ea1473cd7436618b210b8258 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-29931 fix \_\_lt__ check in ipaddress.ip_interface for both v4 and v6. (GH-879) (bpo-2217)
https://github.com/python/cpython/commit/cf58dfb44cc11d41ea1473cd7436618b210b8258

**Comment by serhiy-storchaka** [comment]
New changeset c5a6fb654a280c7b17f1d348e2e40d62ca04c5d3 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-29931 fix \_\_lt__ check in ipaddress.ip_interface for both v4 and v6. (GH-879) (bpo-2218)
https://github.com/python/cpython/commit/c5a6fb654a280c7b17f1d348e2e40d62ca04c5d3
