### ISSUE TITLE
Useless argument in call to PyErr_Format

### ISSUE THREAD

**Issue by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [python/cpython#74110]
BPO | [29924](https://bugs.python.org/issue29924)
--- | :---
Nosy | @vstinner, @SylvainDe
PRs | <li>python/cpython#854</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-27.21:40:03.639>
created_at = <Date 2017-03-27.20:55:22.829>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Useless argument in call to PyErr_Format'
updated_at = <Date 2017-03-27.21:40:03.637>
user = 'https://github.com/SylvainDe'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-27.21:40:03.637>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-27.21:40:03.639>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-03-27.20:55:22.829>
creator = 'SylvainDe'
dependencies = []
files = []
hgrepos = []
issue_num = 29924
keywords = []
message_count = 7.0
messages = ['290645', '290648', '290649', '290654', '290657', '290659', '290660']
nosy_count = 2.0
nosy_names = ['vstinner', 'SylvainDe']
pr_nums = ['854']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29924'
versions = ['Python 3.7']
```

</p></details>

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Very uninteresting issue I've found while looking at the code.

In [Objects/call.c](https://github.com/python/cpython/blob/main/Objects/call.c), in \_PyMethodDef_RawFastCallDict(PyMethodDef \*method, PyObject \*self, PyObject \*\*arg...), we have


   no_keyword_error:
       PyErr_Format(PyExc_TypeError,
                    "%.200s() takes no keyword arguments",
                    method-\>ml_name, nargs);

The `nargs` seems pointless.

This issue is mosly opened to have a record number to open a commit but it raises a few questions:

 - would it make sense to try to use GCC/CLang's logic around \_\_attribute__ to have this kind of things checked during compilation as much as possible ?

 - would it make sense to define very small functions wrapping some calls to `PyErr_Format` so that one can use function with a very clear signature at (almost) no cost? This would be specially relevant for error raised in multiple places with the same message (The trio PyMethodDef *method/PyExc_TypeError/"%.200s() takes no keyword arguments" is a good candidate for this). I'd be happy for work on this but I'm afraid this would correspond to something Raymond Hettinger asks new comers not to do : "Don't be a picture straightener" ( https://speakerdeck.com/pybay2016/raymond-hettinger-keynote-core-developer-world ).

I've filled the impacted version as 3.7 as there is no real impacted version from a user point of view.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
I forgot to copy the link but here is a description of what I had in mind for the first idea.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
http://julio.meroh.net/2011/06/validating-format-strings-in-custom-c.html

**Comment by larryhastings** [comment]
This is not an Argument Clinic issue.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Seems to be introduced via 250e4b0063fab35770719b64d1e36209c4aa2596 in January this year.

**Comment by vstinner** [comment]
New changeset d67a103702cf57de90a62c90f7ae969c23d96218 by Victor Stinner (Sylvain) in branch 'master':
bpo-29924: Remove useless argument (#854)
https://github.com/python/cpython/commit/d67a103702cf57de90a62c90f7ae969c23d96218

**Comment by vstinner** [comment]
Thank you SylvainDe, I merged your fix!

About the GCC \_\_attribute__ idea: I'm not sure, since Python uses some extra formatters (I don't recall which one). If you succeed to write something working, please open a new issue!

Since the initial bug is fixed, I close the issue now.
