### ISSUE TITLE
Missing word ("be") in error message ("first argument must a type object")

### ISSUE THREAD

**Issue by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [python/cpython#74118]
BPO | [29932](https://bugs.python.org/issue29932)
--- | :---
Nosy | @brettcannon, @SylvainDe, @DimitrisJim
PRs | <li>python/cpython#888</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-29.18:09:44.066>
created_at = <Date 2017-03-28.12:35:05.450>
labels = ['type-feature', '3.7']
title = 'Missing word ("be") in error message ("first argument must a type object")'
updated_at = <Date 2017-03-29.18:09:44.065>
user = 'https://github.com/SylvainDe'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-29.18:09:44.065>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-29.18:09:44.066>
closer = 'brett.cannon'
components = []
creation = <Date 2017-03-28.12:35:05.450>
creator = 'SylvainDe'
dependencies = []
files = []
hgrepos = []
issue_num = 29932
keywords = []
message_count = 4.0
messages = ['290701', '290710', '290714', '290789']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'SylvainDe', 'Jim Fasarakis-Hilliard']
pr_nums = ['888']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29932'
versions = ['Python 3.7']
```

</p></details>

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Very uninteresting issue but error message should probably be "first argument must BE a type object" in `array__array_reconstructor_impl` in [Modules/arraymodule.c](https://github.com/python/cpython/blob/main/Modules/arraymodule.c) .

This has been introduced with ad077154d0f305ee0ba5bf41d3cb47d1d9c43e7b .

I'll handle this issue in the next day.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Indeed, quickly glancing over the error messages there's another small typo in https://github.com/python/cpython/blob/master/Modules/arraymodule.c#L2371:

    "array indices must be integer" -> "array indices must be integers"

might as well fix that in your PR too (maybe also change the title to: "Fix small error message typos in arraymodule.c"?)

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
..and another one here https://github.com/python/cpython/blob/master/Modules/arraymodule.c#L2145:

"\_\_reduce_ex__ argument should an integer" -\> ".. should be .."

**Comment by brettcannon** [comment]
New changeset a90e64b78d74b80a7cbcca2237280c724b99431b by Brett Cannon (Sylvain) in branch 'master':
bpo-29932: Fix small error message typos in arraymodule.c (GH-888)
https://github.com/python/cpython/commit/a90e64b78d74b80a7cbcca2237280c724b99431b
