### ISSUE TITLE
asyncio: set_write_buffer_limits() doc doesn't specify unit of the parameters

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74119]
BPO | [29933](https://bugs.python.org/issue29933)
--- | :---
Nosy | @vstinner, @berkerpeksag, @1st1, @Mariatta
PRs | <li>python/cpython#2262</li><li>python/cpython#2532</li><li>python/cpython#2533</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-10-25.23:00:11.408>
created_at = <Date 2017-03-28.13:18:59.252>
labels = ['easy', 'type-feature', '3.7', 'docs', 'expert-asyncio']
title = "asyncio: set_write_buffer_limits() doc doesn't specify unit of the parameters"
updated_at = <Date 2017-10-25.23:00:11.370>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-25.23:00:11.370>
actor = 'berker.peksag'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-10-25.23:00:11.408>
closer = 'berker.peksag'
components = ['Documentation', 'asyncio']
creation = <Date 2017-03-28.13:18:59.252>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29933
keywords = ['easy']
message_count = 8.0
messages = ['290712', '290713', '290716', '296480', '297090', '297501', '297502', '305014']
nosy_count = 5.0
nosy_names = ['vstinner', 'docs@python', 'berker.peksag', 'yselivanov', 'Mariatta']
pr_nums = ['2262', '2532', '2533']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29933'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The asyncio set_write_buffer_limits() documentation doesn't specify unit of high and low parameters. Moreover, it would to explain better the effect of high and low:

* pause_writing() is called when the buffer size becomes larger or equal to high
* (if writing is pause) resume_writing() is called when the buffer size becomes smaller or equal to low

**Comment by vstinner** [comment]
See also https://github.com/asyncio-doc/asyncio-doc/issues/17 for a more general documentation request on asyncio parameters (on the external asyncio doc).

**Comment by vstinner** [comment]
It would also be nice to:

* link to set_write_buffer_limits() from drain()
* link to set_write_buffer_limits() from pause_writing() / resume_writing()
* mention asyncio default values for set_write_buffer_limits(): low=16 kB, high=64 kB (kb? kib? i never know :-/)

**Comment by Mariatta** [comment]
New changeset 5200a7c7f9ea65a96330c5f276f4acc6ec70854e by Mariatta (Kojo Idrissa) in branch 'master':
bpo-29933: Improve set_write_buffer_limits description (GH-2262)
https://github.com/python/cpython/commit/5200a7c7f9ea65a96330c5f276f4acc6ec70854e

**Comment by vstinner** [comment]
Oh, thanks for the documentation! Now the change should just be backported to other branches.

**Comment by Mariatta** [comment]
New changeset 4685e56596f9f332e402c79c913a73b19f4411e1 by Mariatta (Kojo Idrissa) in branch '3.5':
[3.5] bpo-29933: Improve set_write_buffer_limits description (GH-2262) (GH-2533)
https://github.com/python/cpython/commit/4685e56596f9f332e402c79c913a73b19f4411e1

**Comment by Mariatta** [comment]
New changeset 03af4282423b1c287a194664f90496cfc9cf20c7 by Mariatta (Kojo Idrissa) in branch '3.6':
[3.6] bpo-29933: Improve set_write_buffer_limits description (GH-2262) (GH-2532)
https://github.com/python/cpython/commit/03af4282423b1c287a194664f90496cfc9cf20c7

**Comment by berkerpeksag** [comment]
[PR 2262](https://github.com/python/cpython/pull/2262) has been merged and backported to bugfix branches so I think this issue can be closed now.
