### ISSUE TITLE
Unnecessary code in the c-api/exceptions.c

### ISSUE THREAD

**Issue by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [python/cpython#74113]
BPO | [29927](https://bugs.python.org/issue29927)
--- | :---
Nosy | @cocoatomo, @zhangyangyu, @mlouielu
PRs | <li>python/cpython#866</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-29.05:31:10.721>
created_at = <Date 2017-03-28.02:23:00.716>
labels = ['interpreter-core', '3.7']
title = 'Unnecessary code in the c-api/exceptions.c'
updated_at = <Date 2017-03-29.05:31:34.598>
user = 'https://github.com/cocoatomo'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-29.05:31:34.598>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-29.05:31:10.721>
closer = 'xiang.zhang'
components = ['Interpreter Core']
creation = <Date 2017-03-28.02:23:00.716>
creator = 'cocoatomo'
dependencies = []
files = []
hgrepos = []
issue_num = 29927
keywords = []
message_count = 4.0
messages = ['290678', '290685', '290769', '290770']
nosy_count = 3.0
nosy_names = ['cocoatomo', 'xiang.zhang', 'louielu']
pr_nums = ['866']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29927'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
1. BufferError is PRE_INIT'ed twice, and also POST_INIT'ed twice.
2. Using macros (PRE_INIT, POST_INIT and ADD_ERRNO) with following unnecessary semicolons.

These unnecessary code have no semantic effect, but is somehow confusing.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
It seems somehow the patch at bpo-3295 make the mistake, commit faa54a39295 at 2007-08-19 add the PRE_INIT(BufferError) and POST_INIT(BufferError), but in bpo-3295 `buffererror.patch` didn't saw it.

**Comment by zhangyangyu** [comment]
New changeset c431854a0963d4ec2875efab2d2425a738895280 by Xiang Zhang (Louie Lu) in branch 'master':
bpo-29927: Remove duplicate BufferError init and unnecessary semicolons (GH-866)
https://github.com/python/cpython/commit/c431854a0963d4ec2875efab2d2425a738895280

**Comment by zhangyangyu** [comment]
Since the unnecessary codes have no semantic effect, I think they only need to go in 3.7. Thanks for your report and patch!
