### ISSUE TITLE
Compiler warning in _ctypes_test.c

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74125]
BPO | [29939](https://bugs.python.org/issue29939)
--- | :---
Nosy | @vsajip, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#902</li><li>python/cpython#1038</li><li>python/cpython#1039</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-07.22:24:54.189>
created_at = <Date 2017-03-29.06:44:44.117>
labels = ['ctypes', 'build', '3.7']
title = 'Compiler warning in _ctypes_test.c'
updated_at = <Date 2017-04-07.22:24:54.187>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-07.22:24:54.187>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-07.22:24:54.189>
closer = 'vinay.sajip'
components = ['ctypes']
creation = <Date 2017-03-29.06:44:44.117>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29939
keywords = []
message_count = 8.0
messages = ['290771', '290778', '291231', '291232', '291233', '291234', '291304', '291305']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'vstinner', 'serhiy.storchaka']
pr_nums = ['902', '1038', '1039']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue29939'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Compiler warning was introduced by bpo-29565.

/home/serhiy/py/cpython/Modules/_ctypes/_ctypes_test.c: In function ‘_testfunc_large_struct_update_value’:
/home/serhiy/py/cpython/Modules/_ctypes/_ctypes_test.c:53:42: warning: parameter ‘in’ set but not used [-Wunused-but-set-parameter]
 \_testfunc_large_struct_update_value(Test in)
                                          ^

**Comment by vsajip** [comment]
Yes, this is on my radar. I'm planning to make some changes to this file in response to bpo-22273, and will stick in a (void) in to get rid of the warning.

**Comment by vsajip** [comment]
Should be fixed by 164d30e.

**Comment by serhiy-storchaka** [comment]
Thanks Vinay!

**Comment by vstinner** [comment]
IHMO it's worth it to backport the fix, since Benjamin showed that GCC optimizer removes the function body and so defeat the purpose of the test.

**Comment by vsajip** [comment]
Added relevant "needs backport" tags to PR, will get to it soon. Reopening till then.

**Comment by vsajip** [comment]
New changeset d0d575a6db8cb3b2a720be9f404af3d754da9a5d by Vinay Sajip in branch '3.6':
bpo-29939: suppress compiler warnings in \_ctypes_test (bpo-1038)
https://github.com/python/cpython/commit/d0d575a6db8cb3b2a720be9f404af3d754da9a5d

**Comment by vsajip** [comment]
New changeset ae0915e42d8cd96e5ced1fc442ea078b4a59e82d by Vinay Sajip in branch '3.5':
Closes bpo-29939: suppress compiler warnings in \_ctypes_test (bpo-1039)
https://github.com/python/cpython/commit/ae0915e42d8cd96e5ced1fc442ea078b4a59e82d
