### ISSUE TITLE
subprocess.run calling bash on windows10 cause 0x80070057 error when capture stdout with PIPE

### ISSUE THREAD

**Issue by 709d4b94-89dd-4c9f-a128-dd0d0d835bd5** [python/cpython#74124]
BPO | [29938](https://bugs.python.org/issue29938)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @SLAPaper

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-03-29.22:40:53.949>
created_at = <Date 2017-03-29.00:56:06.957>
labels = ['type-bug', 'OS-windows']
title = 'subprocess.run calling bash on windows10 cause 0x80070057 error when capture stdout with PIPE'
updated_at = <Date 2017-03-29.22:46:43.626>
user = 'https://github.com/SLAPaper'
```

bugs.python.org fields:
```python
activity = <Date 2017-03-29.22:46:43.626>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-03-29.22:40:53.949>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2017-03-29.00:56:06.957>
creator = 'SLAPaper'
dependencies = []
files = []
hgrepos = []
issue_num = 29938
keywords = []
message_count = 2.0
messages = ['290762', '290795']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'SLAPaper']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29938'
versions = ['Python 3.6']
```

</p></details>

**Comment by 709d4b94-89dd-4c9f-a128-dd0d0d835bd5** [comment]
print(subprocess.run("bash -c ls", shell=True, stdout=subprocess.PIPE, encoding='utf_16_le').stdout)
\# 错误: 0x80070057
\# error: 0x80070057

And the returncode is 4294967295.

OS: Simp-Chinese Win10; Bash on Windows(Ubuntu 14.04 LTS).
Python 3.5 and Python 3.6 produce the same issue.

While not capture stdout, the command works just fine and output the result onto screen.

**Comment by eryksun** [comment]
The initial release of WSL doesn't support passing non-console standard handles from Windows to Linux, or vice versa. It will work if you switch to a Windows Insider preview build. Otherwise you'll have to wait for the Windows 10 Creators Update. 

See the following video and blog post by Ben Hillis for a discussion of the architecture changes that were made to support this feature:

https://blogs.msdn.microsoft.com/wsl/2016/10/19/windows-and-ubuntu-interoperability
