### ISSUE TITLE
"keys and values" preferred to "keys and elements" for dict constituent

### ISSUE THREAD

**Issue by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [python/cpython#74138]
BPO | [29952](https://bugs.python.org/issue29952)
--- | :---
Nosy | @methane, @cocoatomo
PRs | <li>python/cpython#917</li><li>python/cpython#922</li><li>python/cpython#923</li><li>python/cpython#924</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-22.03:10:23.148>
created_at = <Date 2017-03-31.03:40:13.311>
labels = ['3.7', 'docs']
title = '"keys and values" preferred to "keys and elements" for dict constituent'
updated_at = <Date 2017-04-22.03:10:23.126>
user = 'https://github.com/cocoatomo'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-22.03:10:23.126>
actor = 'cocoatomo'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-22.03:10:23.148>
closer = 'cocoatomo'
components = ['Documentation']
creation = <Date 2017-03-31.03:40:13.311>
creator = 'cocoatomo'
dependencies = []
files = []
hgrepos = []
issue_num = 29952
keywords = []
message_count = 5.0
messages = ['290890', '290895', '290898', '290899', '290900']
nosy_count = 3.0
nosy_names = ['methane', 'docs@python', 'cocoatomo']
pr_nums = ['917', '922', '923', '924']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29952'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
In the section "6.10.1. Value comparisons" [1]_::

   Equality comparison of the keys and elements enforces reflexivity.

would be

   Equality comparison of the keys and values enforces reflexivity.

because we usually call an entry of dict as "key-value pair".

.. [1] https://docs.python.org/3.6/reference/expressions.html#value-comparisons

**Comment by methane** [comment]
New changeset cdcac039fb447f2ab04efcacbe663751bb2cb4ec by INADA Naoki (cocoatomo) in branch 'master':
bpo-29952: Use usual terminology of dict (GH-917)
https://github.com/python/cpython/commit/cdcac039fb447f2ab04efcacbe663751bb2cb4ec

**Comment by methane** [comment]
New changeset 4c75fbb485c0e42181aab95c2ae92c597915827c by INADA Naoki in branch '3.6':
bpo-29952: Use usual terminology of dict  (GH-922)
https://github.com/python/cpython/commit/4c75fbb485c0e42181aab95c2ae92c597915827c

**Comment by methane** [comment]
New changeset f3158121132a1519439bf4c7dba3333b07802d6d by INADA Naoki in branch '3.5':
bpo-29952: Use usual terminology of dict (GH-923)
https://github.com/python/cpython/commit/f3158121132a1519439bf4c7dba3333b07802d6d

**Comment by methane** [comment]
New changeset 5aa913d72317d7632781fb71a7b45a2b5e31558e by INADA Naoki in branch '2.7':
bpo-29952: Use usual terminology of dict (GH-924)
https://github.com/python/cpython/commit/5aa913d72317d7632781fb71a7b45a2b5e31558e
