### ISSUE TITLE
PyArg_ParseTupleAndKeywords exception messages containing "function"

### ISSUE THREAD

**Issue by 84dd73fe-9313-425f-aae0-390228a90839** [python/cpython#74137]
BPO | [29951](https://bugs.python.org/issue29951)
--- | :---
Nosy | @vstinner, @bitdancer, @vadmium, @serhiy-storchaka, @MSeifert04
PRs | <li>python/cpython#916</li><li>python/cpython#2028</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-09.07:49:51.648>
created_at = <Date 2017-03-31.00:03:07.242>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'PyArg_ParseTupleAndKeywords exception messages containing "function"'
updated_at = <Date 2017-06-09.16:27:08.634>
user = 'https://github.com/MSeifert04'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.16:27:08.634>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-09.07:49:51.648>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-03-31.00:03:07.242>
creator = 'MSeifert'
dependencies = []
files = []
hgrepos = []
issue_num = 29951
keywords = []
message_count = 12.0
messages = ['290885', '290894', '290896', '290902', '290903', '290904', '290907', '290910', '290931', '291356', '291357', '295553']
nosy_count = 5.0
nosy_names = ['vstinner', 'r.david.murray', 'martin.panter', 'serhiy.storchaka', 'MSeifert']
pr_nums = ['916', '2028']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29951'
versions = ['Python 3.7']
```

</p></details>

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
Some exceptions thrown by `PyArg_ParseTupleAndKeywords` refer to "function" or "this function" even when a function name was specified.

For example:

```pycon
>>> import bisect
>>> bisect.bisect_right([1,2,3,4], 2, low=10)
TypeError: 'low' is an invalid keyword argument for this function
```


Wouldn't it be better to replace the "this function" part (if given) with the actual function name?

**Comment by serhiy-storchaka** [comment]
LGTM in general. I was going to make similar changes.

While we a here, maybe add the function name to other TypeError messages specific to the function? "Required argument '%U' (pos %d) not found" and "Argument given by name ('%U') and position (%d)", but not to "keywords must be strings".

Classified this as an enhancement.

**Comment by serhiy-storchaka** [comment]
And while we are here, please change "keywords must be strings" to "keyword arguments must be strings" as in PyArg_ValidateKeywordArguments(). And maybe make all TypeError messages starting from a lower letter for uniformity.

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
Thank you for the suggestions, I added them to the PR. If you want 

But are you sure about the "keywords must be strings" -\> "keyword arguments must be strings" change? I always thought the key is the "keyword" and the value the "(keyword) argument".

**Comment by serhiy-storchaka** [comment]
Martin, could you please take a look? Does the wording of error messages look good English? Do you have to suggest some enhancements?

**Comment by serhiy-storchaka** [comment]
> But are you sure about the "keywords must be strings" -\> "keyword arguments must be strings" change? I always thought the key is the "keyword" and the value the "(keyword) argument".

Now, after you have made change, I have doubts. Yes, it looks ambiguous. Maybe "keyword names"? Martin, David, what are your thoughts?

**Comment by vadmium** [comment]
In this test, “keyword arguments” is definitely wrong:

```pycon
 >>> f(**{1:2})
-TypeError: f() keywords must be strings
+TypeError: f() keyword arguments must be strings
```


To me, a keyword argument is a \_value_ passed in using the f(name=. . .) syntax, and the keyword is the name that identifies it (usually becomes a parameter name in the function implementation). So I think the original was better. But if you think the original can be confusing, “keyword names” would also work.

The other messages look okay to me.

**Comment by serhiy-storchaka** [comment]
I agree. PyArg_ValidateKeywordArguments() fooled me. Now I see that it would be better to change only PyArg_ValidateKeywordArguments().

**Comment by bitdancer** [comment]
If you want to be completely unambiguous, you could say "keyword argument names".  "keyword argument" appears to mean different things in different contexts; sometimes it means the name and the value together, sometimes one or the other.  Usually which one it is is clear from context, but it seems in this case it is not clear.

**Comment by serhiy-storchaka** [comment]
New changeset 64c8f705c0121a4b45ca2c3bc7b47b282e9efcd8 by Serhiy Storchaka (Michael Seifert) in branch 'master':
bpo-29951: Include function name for some error messages in `PyArg_ParseTuple*` (#916)
https://github.com/python/cpython/commit/64c8f705c0121a4b45ca2c3bc7b47b282e9efcd8

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Michael. Since most builtin and extension functions and methods now use Argument Clinic and provide a function name, this should be a great enhancement.

**Comment by vstinner** [comment]
New changeset f9f1ccace395a8f65b60dc12567a237b4002fd18 by Victor Stinner (Serhiy Storchaka) in branch 'master':
Fix regression in error message introduced in bpo-29951. (bpo-2028)
https://github.com/python/cpython/commit/f9f1ccace395a8f65b60dc12567a237b4002fd18
