### ISSUE TITLE
unnecessary LBYL for key contained in defaultdict, lib2to3/btm_matcher

### ISSUE THREAD

**Issue by 93fb711d-fdf4-46a8-9dad-0481f9581972** [python/cpython#74143]
BPO | [29957](https://bugs.python.org/issue29957)
--- | :---
Nosy | @rhettinger, @benjaminp, @selik, @DimitrisJim, @Mariatta
PRs | <li>python/cpython#938</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-08.21:43:04.019>
created_at = <Date 2017-04-01.04:37:19.136>
labels = ['3.7', 'expert-2to3']
title = 'unnecessary LBYL for key contained in defaultdict, lib2to3/btm_matcher'
updated_at = <Date 2017-04-08.21:43:04.018>
user = 'https://github.com/selik'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-08.21:43:04.018>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-08.21:43:04.019>
closer = 'Mariatta'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-04-01.04:37:19.136>
creator = 'selik'
dependencies = []
files = []
hgrepos = []
issue_num = 29957
keywords = []
message_count = 9.0
messages = ['290955', '290956', '290957', '290960', '290962', '290993', '290998', '291025', '291339']
nosy_count = 5.0
nosy_names = ['rhettinger', 'benjamin.peterson', 'selik', 'Jim Fasarakis-Hilliard', 'Mariatta']
pr_nums = ['938']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29957'
versions = ['Python 3.7']
```

</p></details>

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
Minor, but it looks like someone decided to use a defaultdict but forgot to remove the checks for whether a key exists.

Creating a defaultdict(list):
https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/lib2to3/btm_matcher.py#L100

Checking for the key, then initializing an empty list:
https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/lib2to3/btm_matcher.py#L120

Again:
https://github.com/python/cpython/blob/6f0eb93183519024cb360162bdd81b9faec97ba6/Lib/lib2to3/btm_matcher.py#L137

Because the ``results`` is getting returned, perhaps it'd be better to use a regular dict and dict.setdefault instead of a defaultdict.

**Comment by rhettinger** [comment]
Nice catch.  You've got sharp eyes.

Do you want to submit a pull request or have another dev work on it?

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
I'll submit a pull request momentarily.

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
PR submitted. I also signed the contributor agreement, but the bot doesn't seem to have noticed.

**Comment by Mariatta** [comment]
Thanks for the PR Michael :)

It may take one US business day for the CLA to be received.
Then a core dev has to manually update the label in GitHub.

**Comment by rhettinger** [comment]
Rather than removing the defaultdict, I think a cleaner fix is to just remove the unnecessary LBYL.   That leaves the code a little more compact, faster, and nice looking.

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
Ok, I'll change the PR.

**Comment by benjaminp** [comment]
New changeset 11fa3c7cd1b151e302d4eee0369cafbaf151c8fb by Benjamin Peterson (Michael Selik) in branch 'master':
bpo-29957: change LBYL key lookup to dict.setdefault (#938)
https://github.com/python/cpython/commit/11fa3c7cd1b151e302d4eee0369cafbaf151c8fb

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
bump to close issue now that PR was merged
