### ISSUE TITLE
More compact sets and frozensets created from sets

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74147]
BPO | [29961](https://bugs.python.org/issue29961)
--- | :---
Nosy | @rhettinger, @methane, @serhiy-storchaka
PRs | <li>python/cpython#946</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-04-01.15:53:26.586>
created_at = <Date 2017-04-01.11:52:41.898>
labels = ['interpreter-core', '3.7', 'performance']
title = 'More compact sets and frozensets created from sets'
updated_at = <Date 2017-04-02.05:36:13.906>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-02.05:36:13.906>
actor = 'serhiy.storchaka'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-04-01.15:53:26.586>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-04-01.11:52:41.898>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 29961
keywords = []
message_count = 7.0
messages = ['290980', '290992', '290997', '291020', '291021', '291022', '291023']
nosy_count = 3.0
nosy_names = ['rhettinger', 'methane', 'serhiy.storchaka']
pr_nums = ['946']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29961'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
For now new set and frozenset objects can allocate 2 times larger table than necessary when are created from set or dict. For example if the size n of the original set is the power of two, resulting set will allocate the table of 4\*n rather that 2\*n. Up to 20% of new sets use twice more memory than necessary.

Proposed patch makes set_merge() allocating the table of size n\*5/3 instead of n\*2. This is the minimal size necessary for inserting all elements with fill ration \<=60%.

```sh
$ ./python -c 'N = 6000; from sys import getsizeof; s = [getsizeof(frozenset(set(range(n)))) for n in range(N)]; print( [(n, s[n]) for n in range(N) if not n or s[n] != s[n-1]] )'
Unpatched:  [(0, 112), (5, 240), (8, 368), (16, 624), (32, 1136), (64, 2160), (128, 4208), (256, 8304), (512, 16496), (1024, 32880), (2048, 65648), (4096, 131184)]
Patched:    [(0, 112), (5, 240), (9, 368), (19, 624), (38, 1136), (77, 2160), (153, 4208), (307, 8304), (614, 16496), (1229, 32880), (2457, 65648), (4915, 131184)]
```

**Comment by rhettinger** [comment]
FWIW, I've long considered this to be a feature of set and dicts, it is the only way a user can affect sparseness.  For lookup only sets, the extra sparseness is a virtue (fewer collisions).  So, I would like to leave the current code in-place.  

With sets the goals are different from dicts.  I place less value on compactness and more value on fast membership testing.  And with dicts, the norm is that the looked-up key usually exists.  With sets, the goal isn't looking an element known to be in the set, but more about determining whether an element is in the set.  Accordingly, sets have to optimize for misses as well as hits.

In the future, please assign set feature requests to me so that I don't miss them.

**Comment by serhiy-storchaka** [comment]
There is a program that uses 32 GB for sets. The patch could save up to 6 GB for it.

I understood your arguments when you lowered the maximal fill ration from 2/3 to 60%. But in that case the fill ratio is between 15% and 30%! Isn't it too small?

**Comment by methane** [comment]
I also feel set created from iterator is too large sometimes.
Especially, frozenset is used for "unordered tuple" dict key sometimes.

```sh
$ python -c 'N = 6000; from sys import getsizeof; s = [getsizeof(frozenset(range(n))) for n in range(N)]; print( [(n, s[n]) for n in range(N) if not n or s[n] != s[n-1]] )'
[(0, 224), (5, 736), (21, 2272), (85, 8416), (341, 32992), (1365, 131296), (5461, 524512)]

$ python -c 'N = 6000; from sys import getsizeof; s = [getsizeof(dict.fromkeys(range(n))) for n in range(N)]; print( [(n, s[n]) for n in range(N) if not n or s[n] != s[n-1]] )'
[(0, 240), (6, 368), (11, 648), (22, 1184), (43, 2280), (86, 4704), (171, 9320), (342, 18528), (683, 36968), (1366, 73824), (2731, 147560), (5462, 295008)]
```


set size increases by \*4 each resize.
This is code of set_add_entry():

    if ((size_t)so->fill*5 < mask*3)
        return 0;
    return set_table_resize(so, so->used>50000 ? so->used*2 : so->used*4);

If we simply replace `so->used>50000 ? so->used*2 : so->used*4` with `so->used*2`, there may be not enough room when there are some dummy entries. (used + dummy = fill).

But how about replacing `*4` with `*3`?
In general, load factor after resize will be changed from 12.5% ~ 25% to 16.6% ~ 33.3%. It seems OK to me.
In case of no removal (e.g. constructor called with iterator), set size increases by *2 each time:

```pycon
>>> for n in range(3, 20):
...     print(math.ceil(2 ** n * 3/5) * 3, 2 ** (n+1))
15 16
30 32
60 64
117 128
231 256
462 512
924 1024
1845 2048
3687 4096
7374 8192
14748 16384
29493 32768
58983 65536
117966 131072
235932 262144
471861 524288
943719 1048576
```

**Comment by rhettinger** [comment]
You guys seem to have an enormous about of spare time and seem to feel to need to redesign every single thing you see.  Please slow down and allow me to breathe a bit.  I cannot keep up with a new "let's change x" every single day.  This set object has been a successful design for a very long time.  I like the balance that it has struck and do not want to constantly mess with its tuning or parameters.

I working on bigger ideas at the moment that will make all of this irrelevant but can't make progress with you two proposing micro changes on an almost daily basis.

Please pick some actual bugs to go fix or implement a feature request to propel the language forward.  Eating up 100% of my development time is crippling my ability to contribute.  And I've grown weary of revisiting old ground over and over.  Please move on.

**Comment by methane** [comment]
OK, sorry about bothering you.

**Comment by serhiy-storchaka** [comment]
Okay. I was going to provide patches for other set's weirdness (for example a set can increase its size after removing elements), but with your reaction I see that this doesn't make sense. I wash my hands from fixing set.
