### ISSUE TITLE
re.match failed to match left square brackets as the first char

### ISSUE THREAD

**Issue by 889f74a1-6ab9-4f32-813a-38eecf13a7f4** [python/cpython#74145]
BPO | [29959](https://bugs.python.org/issue29959)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-01.07:44:16.345>
created_at = <Date 2017-04-01.07:38:49.820>
labels = ['expert-regex', 'type-bug', 'invalid']
title = 're.match failed to match left square brackets as the first char'
updated_at = <Date 2017-04-05.06:19:52.816>
user = 'https://bugs.python.org/boqu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-05.06:19:52.816>
actor = 'bo qu'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-01.07:44:16.345>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-01.07:38:49.820>
creator = 'bo qu'
dependencies = []
files = []
hgrepos = []
issue_num = 29959
keywords = []
message_count = 3.0
messages = ['290968', '290969', '291158']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'bo qu']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29959'
versions = ['Python 3.5']
```

</p></details>

**Comment by 889f74a1-6ab9-4f32-813a-38eecf13a7f4** [comment]
if "[" is the first char in a string, then re.match can't match any pattern from the string, but re.findall works fine

details as follows:

```pycon
[da@namenode log]$ python3
Python 3.4.3 (default, Jun 14 2015, 14:23:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import re
>>> cyzd="[abc]"
>>> cyzd
'[abc]'
>>> pattern="ab(.*)"
>>> pattern
'ab(.*)'
>>> match=re.match(pattern, cyzd)
>>> match
>>> pattern=r'ab(.*)'     
>>> re.findall(pattern, cyzd)
['c]']
```

**Comment by serhiy-storchaka** [comment]
re.match() checks if the beginning of the string matches the regular expression pattern. Use re.search() if you want to find the match not at the beginning of the string.

https://docs.python.org/3/library/re.html#re.match
https://docs.python.org/3/library/re.html#re.search

**Comment by 889f74a1-6ab9-4f32-813a-38eecf13a7f4** [comment]
hi Serhiy Storchaka
thank you for your explanation, it helps a lot

2017-04-01 15:44 GMT+08:00 Serhiy Storchaka \<report@bugs.python.org\>:

>
> Serhiy Storchaka added the comment:
>
> re.match() checks if the beginning of the string matches the regular
> expression pattern. Use re.search() if you want to find the match not at
> the beginning of the string.
>
> https://docs.python.org/3/library/re.html#re.match
> https://docs.python.org/3/library/re.html#re.search
>
> \----------
> nosy: +serhiy.storchaka
> resolution:  -\> not a bug
> stage:  -\> resolved
> status: open -\> closed
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue29959\>
> _______________________________________
>
