### ISSUE TITLE
multiprocessing.Pool.__exit__() calls terminate() instead of close()

### ISSUE THREAD

**Issue by 702a5500-6f30-4cf1-bd63-c0dd44ddb1b8** [python/cpython#74140]
BPO | [29954](https://bugs.python.org/issue29954)
--- | :---
Nosy | @pitrou, @MojoVampire, @applio, @s3rvac

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-01.09:19:52.251>
created_at = <Date 2017-03-31.16:35:59.646>
labels = ['3.7', 'type-bug', 'library']
title = 'multiprocessing.Pool.__exit__() calls terminate() instead of close()'
updated_at = <Date 2017-04-01.09:19:52.224>
user = 'https://github.com/s3rvac'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-01.09:19:52.224>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-01.09:19:52.251>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-03-31.16:35:59.646>
creator = 's3rvac'
dependencies = []
files = []
hgrepos = []
issue_num = 29954
keywords = []
message_count = 3.0
messages = ['290923', '290951', '290972']
nosy_count = 4.0
nosy_names = ['pitrou', 'josh.r', 'davin', 's3rvac']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29954'
versions = ['Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 702a5500-6f30-4cf1-bd63-c0dd44ddb1b8** [comment]
multiprocessing.Pool.\_\_exit__() calls terminate() instead of close(). Why? Wouldn't it be better (and more expected from a user's point of view) if it called close()?

Reasons:

- Calling close() would wait until all tasks are completed before shutting down the pool instead of terminating them abruptly when some of them may still be running.

- concurrent.futures.ProcessPoolExecutor.\_\_exit__() calls shutdown(wait=True), which waits until all tasks are finished. In this regard, the behavior of Pool.\_\_exit__() is inconsistent.

See also this comment by Dan O'Reilly (http://bugs.python.org/msg242120), who expressed an identical concern two years ago.

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
I suspect it's far too late to change this, given compatibility constraints. If you want it to close instead of terminate, contextlib.closing is always an option.

**Comment by pitrou** [comment]
I agree it's far too late.  Multiple existing libraries may rely on the current behaviour.
