### ISSUE TITLE
[doc] %z directive has no effect on the output of time.strptime

### ISSUE THREAD

**Issue by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [python/cpython#74150]
BPO | [29964](https://bugs.python.org/issue29964)
--- | :---
Nosy | @brettcannon, @bitdancer, @vadmium, @hugovk, @miss-islington, @iritkatriel
PRs | <li>python/cpython#30354</li><li>python/cpython#30608</li><li>python/cpython#30609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-15.09:26:58.943>
created_at = <Date 2017-04-02.20:19:38.615>
labels = ['3.11', 'type-feature', 'docs']
title = '[doc] %z directive has no effect on the output of time.strptime'
updated_at = <Date 2022-01-15.09:26:58.942>
user = 'https://bugs.python.org/PaulPinterits'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-15.09:26:58.942>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-01-15.09:26:58.943>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-04-02.20:19:38.615>
creator = 'Paul Pinterits'
dependencies = []
files = []
hgrepos = []
issue_num = 29964
keywords = ['patch']
message_count = 12.0
messages = ['291041', '291042', '291043', '291044', '291045', '291046', '291086', '291093', '407368', '410605', '410609', '410611']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'r.david.murray', 'docs@python', 'martin.panter', 'hugovk', 'miss-islington', 'iritkatriel']
pr_nums = ['30354', '30608', '30609']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29964'
versions = ['Python 3.11']
```

</p></details>

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
%z is listed as a supported directive in the python 3 documentation (https://docs.python.org/3.5/library/time.html#time.strftime), but it doesn't actually do anything:

```pycon
>>> from time import strptime
>>> strptime('+0000', '%z') == strptime('+0200', '%z')
True
```


As far as I can tell, there aren't any footnotes saying that %z might not be supported on some platforms, like it was back in python 2.

In case it matters, I'm using python 3.5.3 on linux.

**Comment by vadmium** [comment]
Are you sure? It works for me:

```pycon
>>> strptime("+0200", "%z").tm_gmtoff
7200
>>> strptime("+0000", "%z").tm_gmtoff
0
```


The "struct_time" class is documented as a named tuple, but the time zone offset is not one of the tuple elements, so isn’t going to be checked for equality.

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
I see. You're right, it does make a difference.

However, this behaviour is quite unexpected. Perhaps I just didn't read the docs carefully enough, but it wasn't clear to me that the time module had such half-baked support for time zones.

An unsuspecting user, like me, reads the documentation on strptime, which directs you to strftime. There you read that %z is a supported directive. Along the way you've come across the conversion table, which tells you that mktime() can convert struct_time objects to timestamps. But then when you try to parse a time string, the information gets lost somewhere along the way:

```pycon
>>> mktime(strptime("+0000", "%z")) == mktime(strptime("+0200", "%z"))
True
```


If you visit the section about struct_time objects, you find this footnote:
"Changed in version 3.3: tm_gmtoff and tm_zone attributes are available on platforms with C library supporting the corresponding fields in struct tm."

But even after reading that, I'd still expect the tm_gmtoff attribute to have some sort of effect and not get silently discarded.

**Comment by vadmium** [comment]
As far as I can see, the documentation only claims that “mktime” converts local time. If you saw a suggestion that it supports arbitrary time zones, please point it out.

**Comment by 0c97e840-ae8b-4fa9-b95e-fe2331d61b5b** [comment]
No no, the docs are correct. This was definitely my mistake. I'm just trying to say that it's rather confusing how there's only partial support for time zones. When I saw that there is support for parsing the time zone offset, I assumed that the functions provided in the time module would be enough to solve my problem - having to rely on the datetime module to have proper time zone support caught me by surprise. It's quite counterintuitive.

**Comment by vadmium** [comment]
We could change this to a documentation issue if you have any suggestions to make the documentation clearer.

I understand the “time” module is mainly a wrapper or emulator of the OS’s own strptime, mktime, etc functions, which explains some of these quirks.

**Comment by bitdancer** [comment]
Yes, that's exactly right.  'time' is a low-level os-function wrapper, and inherits many of the deficiencies of the platform.  datetime attempts to be a more comprehensive, portable solution.  (But even it has its quirks...timezones are \*hard*.)

**Comment by brettcannon** [comment]
There's actually a footnote pointing out that %z is not supported by all libc implementations: https://docs.python.org/3/library/time.html#id2. Probably adding a note for %z in the strftime() table would be good.
