### ISSUE TITLE
"AMD64 FreeBSD 9.x 3.x" tries to rebuild Include/opcode.h, timestamp issue

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74153]
BPO | [29967](https://bugs.python.org/issue29967)
--- | :---
Nosy | @vstinner, @vadmium, @zware, @koobs
Superseder | <li>bpo-23404: &#x27;make touch&#x27; does not work with git clones of the source repository</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.23:44:57.889>
created_at = <Date 2017-04-03.10:29:43.235>
labels = ['build', '3.7']
title = '"AMD64 FreeBSD 9.x 3.x" tries to rebuild Include/opcode.h, timestamp issue'
updated_at = <Date 2017-05-02.23:44:57.888>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.23:44:57.888>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.23:44:57.889>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-04-03.10:29:43.235>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29967
keywords = []
message_count = 4.0
messages = ['291059', '291060', '291061', '291066']
nosy_count = 4.0
nosy_names = ['vstinner', 'martin.panter', 'zach.ware', 'koobs']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '23404'
type = None
url = 'https://bugs.python.org/issue29967'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
"make buildbottest" on "AMD64 FreeBSD 9.x 3.x" fails with:
\---
Cannot generate ./Include/opcode.h, python not found !
To skip re-generation of ./Include/opcode.h run \<make touch\> or \<make -t ./Include/opcode.h\>.
Otherwise, set python in PATH and run configure or run \<make PYTHON_FOR_GEN=python\>.
*** [./Include/opcode.h] Error code 1
\---
http://buildbot.python.org/all/builders/AMD64%20FreeBSD%209.x%203.x/builds/123/steps/test/logs/stdio

Python has a "make touch" command which uses "hg --config extensions.touch=Tools/hg/hgtouch.py touch -v", but CPython moved to Git.

**Comment by vstinner** [comment]
See issue bpo-23404: "'make touch' does not work with git clones of the source repository".

**Comment by vstinner** [comment]
According to koobs, the buildbot slave has "python2" and "python2.7" commands, but no "python".

See issue bpo-26662 for my previous complain on "python": Python build system should use "python2" or "python3", not "python".

**Comment by vadmium** [comment]
I think this is the same underlying problem as bpo-23404. Either we get “make touch” working without Mercurial, or we use some other mechanism to either disable regeneration by default (my preference), or disable regeneration by explicit request (possible compromise with Nick who liked the automatic regeneration because it saved him remembering other commands: \<https://mail-archive.com/search?l=mid&q=CADiSq7d2NV0hbcQB1bYvc9M2qUYZiYC7RsG=fnw7tdWia2YmQg@mail.gmail.com\>).
