### ISSUE TITLE
Severe open file leakage running asyncio SSL server

### ISSUE THREAD

**Issue by d57b5364-f6d2-47a4-9eea-4b46812cfd4a** [python/cpython#74156]
BPO | [29970](https://bugs.python.org/issue29970)
--- | :---
Nosy | @giampaolo, @asvetlov, @mocmocamoc, @1st1, @fafhrd91, @kyuupichan
PRs | <li>python/cpython#4825</li><li>python/cpython#4939</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/1st1'
closed_at = <Date 2017-12-19.20:02:01.780>
created_at = <Date 2017-04-03.14:10:15.014>
labels = ['expert-asyncio', '3.7', 'performance']
title = 'Severe open file leakage running asyncio SSL server'
updated_at = <Date 2017-12-20.19:27:29.217>
user = 'https://github.com/kyuupichan'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-20.19:27:29.217>
actor = 'asvetlov'
assignee = 'yselivanov'
closed = True
closed_date = <Date 2017-12-19.20:02:01.780>
closer = 'asvetlov'
components = ['asyncio']
creation = <Date 2017-04-03.14:10:15.014>
creator = 'kyuupichan'
dependencies = []
files = []
hgrepos = []
issue_num = 29970
keywords = ['patch']
message_count = 14.0
messages = ['291071', '291135', '296294', '296297', '296298', '308084', '308146', '308673', '308676', '308765', '308769', '308784', '308785', '308786']
nosy_count = 6.0
nosy_names = ['giampaolo.rodola', 'asvetlov', 'mocmocamoc', 'yselivanov', 'fafhrd91', 'kyuupichan']
pr_nums = ['4825', '4939']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue29970'
versions = ['Python 3.7']
```

</p></details>

**Comment by d57b5364-f6d2-47a4-9eea-4b46812cfd4a** [comment]
Original report at old repo here:  https://github.com/python/asyncio/issues/483

There this is reported fixed by https://github.com/python/cpython/pull/480

I wish to report that whilst the above patch might have a small positive effect, it is far from solving the actual issue.  Several users report eventual exhaustion of the open file resource running SSL asyncio servers.

Here are graphs provided by a friend running my ElectrumX server software, first accepting SSL connections and the second accepting TCP connections only.  Both of the servers were monkey-patched with the pull-480 fix above, so this is evidence it isn't solving the issue.

http://imgur.com/a/cWnSu

As you can see, the TCP server (which has far less connections; most users use SSL) has no leaked file handles, whereas the SSL server has over 300.

This becomes an easy denial of service vector against asyncio servers.  One way to trigger this (though I doubt it explains the numbers above) is simply to connect to the SSL server from telnet, and do nothing.  asyncio doesn't time you out, the telnet session seems to sit there forever, and the open file resources are lost in the SSL handshake stage until the remote host kindly decides to disconnect.

I suspect these resource issues all revolve around the SSL handshake process, certainly at the opening of a connection, but also perhaps when closing.

As the application author I am not informed by asyncio of a potential connection until the initial handshake is complete, so I cannot do anything to close these phantom socket connections.  I have to rely on asyncio to be properly handling DoS issues and it is not currently doing so robustly.

**Comment by 1st1** [comment]
I'm assigning this to myself to make sure I don't forget about this. If someone wants to tackle this please feel free to reassign.

**Comment by fafhrd91** [comment]
question is, should asyncio handle timeouts or leave it to caller?

https://github.com/python/cpython/pull/480 fixes leak during handshake.

**Comment by d57b5364-f6d2-47a4-9eea-4b46812cfd4a** [comment]
@Nikolay Kim

As I note in the original submission, 480 was tested and does NOT solve this issue.  Thanks.

**Comment by fafhrd91** [comment]
I see. this is server specific problem. as a temp solution I'd use proxy for ssl termination.
