### ISSUE TITLE
MatchObject __getitem__() should support slicing and len

### ISSUE THREAD

**Issue by 93fb711d-fdf4-46a8-9dad-0481f9581972** [python/cpython#74151]
BPO | [29965](https://bugs.python.org/issue29965)
--- | :---
Nosy | @ericvsmith, @ezio-melotti, @serhiy-storchaka, @zhangyangyu, @selik

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-03.18:45:02.009>
created_at = <Date 2017-04-03.03:44:12.813>
labels = ['expert-regex', 'type-feature', '3.7']
title = 'MatchObject __getitem__() should support slicing and len'
updated_at = <Date 2017-04-03.18:45:02.008>
user = 'https://github.com/selik'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-03.18:45:02.008>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-03.18:45:02.009>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-03.03:44:12.813>
creator = 'selik'
dependencies = []
files = []
hgrepos = []
issue_num = 29965
keywords = []
message_count = 8.0
messages = ['291050', '291051', '291055', '291057', '291084', '291087', '291088', '291090']
nosy_count = 6.0
nosy_names = ['eric.smith', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'xiang.zhang', 'selik']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29965'
versions = ['Python 3.7']
```

</p></details>

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
Currently, slicing a MatchObject causes an IndexError and len() a TypeError. It's natural to expect slicing and len to work on objects of a finite length that index by natural numbers.

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
This would also enable negative indexing, which currently raises "IndexError: no such group".

Edit: I meant whole numbers, not natural numbers.

**Comment by zhangyangyu** [comment]
See also bpo-24454.

**Comment by serhiy-storchaka** [comment]
This has already been discussed in other issues. Adding support of indexing opened a can of worms.

len() for match objects is ambiguous because of the group 0. Implementing len() will make the match object iterable, but in a way incompatible with bpo-9529 (because of the group 0).

As for slicing and negative indexes, what is the use case? Do you know that you can get a tuple of groups by passing several arguments to group()? A regular expression usually has known set of groups, so you can just enumerate the indices (or better names) of needed groups (they can be not sequential).

**Comment by ericvsmith** [comment]
Short of a compelling use case, I suggest we reject this enhancement request. len() was deliberately not added in bpo-24454. It's not like any normal code would be iterating over match groups.

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
Yesterday I wanted to do a destructuring bind on a slice of groups in a finditer. Similar situation to the use case of Issue bpo-24454. It might not be "normal code" but I end up in that situation every month or so when parsing semi-structured documents. I found myself wishing for a mapping-destructuring bind, but that's another story.

I haven't read the full discussion of ``len`` on MatchObject yet, but I tentatively agree with Brandon Rhodes' comment in Issue bpo-19536:

"My retort is that concentric groups can happen anyway:
that Group Zero, holding the entire match, is not really
as special as the newcomer might suspect, because you can
always wind up with groups inside of other groups; it is
simply part of the semantics of regular expressions that
groups might overlap or might contain one another ..."

@Serhiy, I was unaware of the feature of passing several arguments to groups. Unfortunately, the regex pattern I was using had a very large set of groups. A slice would have been particularly elegant. Passing several arguments to mo.groups() will be helpful, but still more awkward than a slice.

Perhaps it is a can of worms, but I was pleased to see indexing available and was disappointed not to find the typically supported corresponding features.

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
Sorry, it looks like I got the issue number wrong. My comparison should not have been with bpo-24454, but instead with an issue I can't locate at the moment. Reproducing the example:

```py
    for g0, g1, g2 in re.finditer(r'(\d+)/(\d+)', 'Is 1/3 the same as 2/6?'):
        ratio = Fraction(int(g1), int(g2))
```


Better:

```py
    for mo in re.finditer(r'(\d+)/(\d+)', 'Is 1/3 the same as 2/6?'):
        ratio = Fraction(*map(int, mo[1:3]))
```


The map in the last one isn't very pretty, but I hope it illustrates the gist of what I'd like to do for a much larger pattern with many capture groups.

**Comment by serhiy-storchaka** [comment]
You can use mo.group(1, 2). If you need to slice arbitrary groups, you can slice the result of the groups() method (which is just a tuple).

The re module is already complex, and let use existing API rather than add the new one.
