### ISSUE TITLE
Travis CI docs broken: UnboundLocalError: local variable 'prefix' referenced before assignment

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74159]
BPO | [29973](https://bugs.python.org/issue29973)
--- | :---
Nosy | @vstinner, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-03.16:13:56.948>
created_at = <Date 2017-04-03.15:34:14.337>
labels = ['3.7', 'tests', 'docs']
title = "Travis CI docs broken: UnboundLocalError: local variable 'prefix' referenced before assignment"
updated_at = <Date 2017-04-03.16:13:56.947>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-03.16:13:56.947>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-03.16:13:56.948>
closer = 'vstinner'
components = ['Documentation', 'Tests']
creation = <Date 2017-04-03.15:34:14.337>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 29973
keywords = []
message_count = 4.0
messages = ['291075', '291076', '291077', '291079']
nosy_count = 3.0
nosy_names = ['vstinner', 'docs@python', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29973'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
https://travis-ci.org/python/cpython/jobs/218107336

CPython: master branch
Sphinx 1.5.4

make[1]: Entering directory \`/home/travis/build/python/cpython/Doc'
./venv/bin/python -m sphinx -b suspicious -d build/doctrees -D latex_elements.papersize= -q -W . build/suspicious 

Exception occurred:
  File "/home/travis/virtualenv/python3.6.0/lib/python3.6/site-packages/sphinx/domains/python.py", line 317, in before_content
    if prefix:
UnboundLocalError: local variable 'prefix' referenced before assignment

**Comment by serhiy-storchaka** [comment]
This already is fixed in mainstream. https://github.com/sphinx-doc/sphinx/issues/3597

Sphinx 1.5.5 will be released soon. https://github.com/sphinx-doc/sphinx/issues/3598

**Comment by vstinner** [comment]
https://pypi.org/project/Sphinx/1.5.5/ has been released. How can I schedule a recheck on Travis CI on PRs where the docs job failed?

**Comment by vstinner** [comment]
Oh, Zachary Were "restarted the docs job on most of the blocked PRs". So I close this issue.

That one was hopefully quickly fixed :-)
