### ISSUE TITLE
typing.get_type_hints doesn't really work for classes with ForwardRefs

### ISSUE THREAD

**Issue by 5b4972c1-ebbb-4b77-83a7-66c99dd93336** [python/cpython#74152]
BPO | [29966](https://bugs.python.org/issue29966)
--- | :---
Nosy | @simonpercivall, @ilevkivskyi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.16:27:36.452>
created_at = <Date 2017-04-03.10:21:14.654>
labels = ['type-bug', 'library']
title = "typing.get_type_hints doesn't really work for classes with ForwardRefs"
updated_at = <Date 2017-09-15.16:27:36.450>
user = 'https://github.com/simonpercivall'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.16:27:36.450>
actor = 'levkivskyi'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.16:27:36.452>
closer = 'levkivskyi'
components = ['Library (Lib)']
creation = <Date 2017-04-03.10:21:14.654>
creator = 'simon.percivall'
dependencies = []
files = []
hgrepos = []
issue_num = 29966
keywords = []
message_count = 4.0
messages = ['291058', '291139', '291517', '302264']
nosy_count = 2.0
nosy_names = ['simon.percivall', 'levkivskyi']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29966'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5b4972c1-ebbb-4b77-83a7-66c99dd93336** [comment]
For classes with ForwardRef annotations, typing.get_type_hints is unusable.

As example, we have two files:

a.py:
class Base:
    a: 'A'

```py
class A:
    pass
```


b.py:
from a import Base

```py
class MyClass(Base):
    b: 'B'

class B:
    pass
```



>\>\> from typing import get_type_hints
>\>\> from b import MyClass
>\>\> get_type_hints(MyClass) #  NameError


What should globals/locals be here?

**Comment by ilevkivskyi** [comment]
You could try:

```py
glob = globals.copy()
glob.update(a.__dict__)
glob.update(b.__dict__)
```


You can do this automatically following MyClass.\_\_mro__ and then collecting relevant \_\_module__ attributes on bases.

However, there is little chance this will be fixed in typing itself. It is difficult to cover all possible cases, so that users should choose custom globals/locals for their needs.

**Comment by 5b4972c1-ebbb-4b77-83a7-66c99dd93336** [comment]
It think it's important to document this caveat in `get_type_hints`, that there is virtually _no_ way to use it safely with a class, and that there will always be a high risk of getting an exception unless using this function in a highly controlled setting.

This also, as a consequence, means that there is no "best-effort" support for collecting type hints from a class hierarchy, and every instance of trying to use this function with classes, or traversing \_\_annotations__ "manually", will need to be solved ad-hoc and from scratch by the user (until someone publishes a "typing-utils" package on PyPI).

**Comment by ilevkivskyi** [comment]
This is now fixed (to a reasonable extent) by https://github.com/python/cpython/commit/f350a268a7071ce7d7a5bb86a9b1229782d4963b on master, and backported to 3.6.
