### ISSUE TITLE
cgi.parse_multipart is not consistent with FieldStorage

### ISSUE THREAD

**Issue by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [python/cpython#74165]
BPO | [29979](https://bugs.python.org/issue29979)
--- | :---
Nosy | @orsenthil, @PierreQuentel, @vadmium
PRs | <li>python/cpython#990</li><li>python/cpython#991</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = <Date 2017-05-08.12:09:05.956>
created_at = <Date 2017-04-04.08:58:51.066>
labels = ['3.7', 'type-bug', 'library']
title = 'cgi.parse_multipart is not consistent with FieldStorage'
updated_at = <Date 2019-11-17.22:09:31.631>
user = 'https://github.com/PierreQuentel'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-17.22:09:31.631>
actor = 'martin.panter'
assignee = 'orsenthil'
closed = True
closed_date = <Date 2017-05-08.12:09:05.956>
closer = 'orsenthil'
components = ['Library (Lib)']
creation = <Date 2017-04-04.08:58:51.066>
creator = 'quentel'
dependencies = []
files = []
hgrepos = []
issue_num = 29979
keywords = []
message_count = 4.0
messages = ['291117', '291122', '291491', '293233']
nosy_count = 3.0
nosy_names = ['orsenthil', 'quentel', 'martin.panter']
pr_nums = ['990', '991']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29979'
versions = ['Python 3.7']
```

</p></details>

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
In the cgi module, the parse_multipart() function duplicates code from FieldStorage, and the result is not compliant with that of FieldStorage for requests sent with multipart/form-data : for non-file fields, the value associated with a key is a list of \*bytes* in parse_multipart() and a list of \*strings* for FieldStorage (the bytes decoded with the argument "encoding" passed to FieldStorage()).

I will propose a PR on the Github repo with a version of parse_multipart that uses FieldStorage and returns the same result (values as strings). The function will take an additional argument "encoding".

**Comment by orsenthil** [comment]
Looking forward to this.

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
Senthil,

Can you take a look at the Pull Request when you have time ? The correct PR is #991, not #990.

**Comment by orsenthil** [comment]
New changeset cc3fa204d357be5fafc10eb8c2a80fe0bca998f1 by Senthil Kumaran (Pierre Quentel) in branch 'master':
bpo-29979: Rewrite cgi.parse_multipart to make it consistent with FieldStorage (#991)
https://github.com/python/cpython/commit/cc3fa204d357be5fafc10eb8c2a80fe0bca998f1
