### ISSUE TITLE
Change typing.TYPE_CHECKING doc example

### ISSUE THREAD

**Issue by 5d1e3346-9dbe-41bc-9617-b2ac2702d4ba** [python/cpython#74160]
BPO | [29974](https://bugs.python.org/issue29974)
--- | :---
Nosy | @berkerpeksag, @ilevkivskyi, @JelleZijlstra, @Mortal
PRs | <li>python/cpython#982</li><li>python/cpython#1297</li><li>python/cpython#1299</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-26.14:28:41.505>
created_at = <Date 2017-04-03.17:32:43.641>
labels = ['type-bug', '3.7', 'docs']
title = 'Change typing.TYPE_CHECKING doc example'
updated_at = <Date 2017-04-26.15:21:38.194>
user = 'https://github.com/Mortal'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-26.15:21:38.194>
actor = 'levkivskyi'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-26.14:28:41.505>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-04-03.17:32:43.641>
creator = 'rav'
dependencies = []
files = []
hgrepos = []
issue_num = 29974
keywords = []
message_count = 11.0
messages = ['291085', '291101', '291121', '292332', '292334', '292351', '292352', '292353', '292354', '292361', '292362']
nosy_count = 5.0
nosy_names = ['docs@python', 'berker.peksag', 'levkivskyi', 'JelleZijlstra', 'rav']
pr_nums = ['982', '1297', '1299']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29974'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 5d1e3346-9dbe-41bc-9617-b2ac2702d4ba** [comment]
The documentation of typing.TYPE_CHECKING has an example (introduced in issue bpo-26141) that would lead to NameError at runtime. The example shows how to limit the import of "expensive_mod" to type checkers, but then goes on to use "expensive_mod.some_type" in a type annotation that is evaluated at runtime ("local_var: expensive_mod.some_type"). The use case of TYPE_CHECKING is probably meant for type annotations placed in comments, e.g. "local_var  # type: expensive_mod.some_type".

**Comment by JelleZijlstra** [comment]
The example is actually correct; I just confirmed by running it in my shell. Type annotations on local variables are not evaluated at runtime; see PEP-526.

**Comment by 5d1e3346-9dbe-41bc-9617-b2ac2702d4ba** [comment]
I have updated the patch after feedback from Jelle Zijlstra and Ivan Levkevskyi. Indeed the example was correct; the patch now adds wording from PEP-484 and PEP-526 to clarify why a function parameter annotation needs to be in quotes and a local variable annotation does not.

**Comment by berkerpeksag** [comment]
New changeset 87c07fe9d908d0a2143fcc8369255c6ff3241503 by Berker Peksag (Mathias Rav) in branch 'master':
bpo-29974: Improve typing.TYPE_CHECKING example (GH-982)
https://github.com/python/cpython/commit/87c07fe9d908d0a2143fcc8369255c6ff3241503

**Comment by berkerpeksag** [comment]
87c07fe9d908d0a2143fcc8369255c6ff3241503 should still be backported to 3.5 and 3.6 branches so please don't close it yet.

**Comment by ilevkivskyi** [comment]
> 87c07fe9d908d0a2143fcc8369255c6ff3241503 should still be backported to 3.5 and 3.6 branches so please don't close it yet.

Thanks for making backport PRs! (and sorry for closing prematurely)

**Comment by berkerpeksag** [comment]
New changeset 271a289a03ad10c91c5326bde3020f1cdf6a1fff by Berker Peksag in branch '3.5':
bpo-29974: Improve typing.TYPE_CHECKING example (GH-982)
https://github.com/python/cpython/commit/271a289a03ad10c91c5326bde3020f1cdf6a1fff

**Comment by berkerpeksag** [comment]
New changeset 04f389b8b357c8507b6c9642adcb8b956489e034 by Berker Peksag in branch '3.6':
bpo-29974: Improve typing.TYPE_CHECKING example (GH-982)
https://github.com/python/cpython/commit/04f389b8b357c8507b6c9642adcb8b956489e034

**Comment by berkerpeksag** [comment]
Now all backport PRs have been merged. Thanks for the PR, Mathias.

> Thanks for making backport PRs! (and sorry for closing prematurely)

No problem, thanks for the reviews! By the way, sorry I missed the typo in your last name while doing the initial merge.

**Comment by 5d1e3346-9dbe-41bc-9617-b2ac2702d4ba** [comment]
Sorry for making a typo in your last name, Ivan Levkivskyi! I should know better and use copy-and-paste.

**Comment by ilevkivskyi** [comment]
> Sorry for making a typo in your last name

No problem!
This actually happened maaany times with me :-)
