### ISSUE TITLE
Add option to get all errors from create_connection in an ExceptionGroup

### ISSUE THREAD

**Issue by bitdancer** [python/cpython#74166]
BPO | [29980](https://bugs.python.org/issue29980)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @tiran, @bitdancer, @1st1, @nanjekyejoannah, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-04.17:12:21.325>
labels = ['expert-asyncio']
title = 'OSError: multiple exceptions should preserve the exception type if it is common'
updated_at = <Date 2020-11-25.23:31:25.518>
user = 'https://github.com/bitdancer'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-25.23:31:25.518>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-04-04.17:12:21.325>
creator = 'r.david.murray'
dependencies = []
files = []
hgrepos = []
issue_num = 29980
keywords = []
message_count = 5.0
messages = ['291126', '291127', '291288', '340147', '381869']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'terry.reedy', 'christian.heimes', 'r.david.murray', 'aymeric.augustin', 'yselivanov', 'nanjekyejoannah', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue29980'
versions = []
```

</p></details>

**Comment by bitdancer** [comment]
If all connections fail (not file :)

**Comment by terryjreedy** [comment]
I agree.  And if the sub-exceptions are different, prepend them to the messages in the OSError list.

**Comment by iritkatriel** [comment]
Do we want to do this with ExceptionGroup for 3.11?

**Comment by gvanrossum** [comment]
Perhaps, though we’d have to add a flag to enable that behavior, since raising EG  would be a backwards incompatible change.

**Comment by vstinner** [comment]
Would it be possible to mark the new *all_errors* parameter as a keyword-only parameter?

**Comment by pamelafox** [comment]
I ran into this while using asyncio.create_connection, which is also what was being used in the linked issue above in the websockets library. The referenced code commit fixing this issue is for sockets.py, however, not for the asyncio version.

 What do you think of adding to asyncio.base_events.py create_connection, using same keyword arg `all_errors`? It works nicely in my local test.

```
@@ -980,7 +981,7 @@ async def create_connection(
             local_addr=None, server_hostname=None,
             ssl_handshake_timeout=None,
             ssl_shutdown_timeout=None,
-            happy_eyeballs_delay=None, interleave=None):
+            happy_eyeballs_delay=None, interleave=None, all_errors=False):
         """Connect to a TCP server.
 
         Create a streaming transport connection to a given internet host and
@@ -1072,6 +1073,8 @@ async def create_connection(
                 if len(exceptions) == 1:
                     raise exceptions[0]
                 else:
+                    if all_errors:
+                        raise ExceptionGroup("create_connection failed", exceptions)
                     # If they all have the same str(), raise one.
                     model = str(exceptions[0])
                     if all(str(exc) == model for exc in exceptions):
```

Here's my code that uses it:

```
async def check_ports(host: str, start: int, end: int, max=10):
    found = 0
    for port in range(start, end):
        try:
            future = asyncio.open_connection(host=host, port=port, all_errors=True)
            r, w = await asyncio.wait_for(future, timeout=timeout)
            yield port
            found += 1
            w.close()
            if found >= max:
                return
        except* ConnectionRefusedError:
            pass
        except* asyncio.TimeoutError:
            pass # closed
```

**Comment by iritkatriel** [comment]
@pamelafox Go ahead and create a new issue and PR for this. It's too late for 3.11, but it could go into 3.12 if the asyncio maintainers agree.

Though, you should check all_errors before len(exceptions). If all_errors then you should always raise an ExceptionGroup, even if it's only of size 1.

**Comment by pamelafox** [comment]
@iritkatriel Okay, sounds good, I'll work on that. And yeah I realized after posting that diff that it needs to go earlier. Thank you!
