### ISSUE TITLE
Update Index for set, dict, and generator 'comprehensions'

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#74167]
BPO | [29981](https://bugs.python.org/issue29981)
--- | :---
Nosy | @akuchling, @terryjreedy, @bitdancer, @mlouielu, @miss-islington, @DahlitzFlorian
PRs | <li>python/cpython#995</li><li>python/cpython#20272</li><li>python/cpython#22836</li><li>python/cpython#22837</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-25.02:57:18.912>
created_at = <Date 2017-04-04.18:01:11.476>
labels = ['easy', 'type-bug', '3.8', '3.9', '3.10', 'docs']
title = "Update Index for set, dict, and generator 'comprehensions'"
updated_at = <Date 2020-10-25.02:57:18.912>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-25.02:57:18.912>
actor = 'methane'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-10-25.02:57:18.912>
closer = 'methane'
components = ['Documentation']
creation = <Date 2017-04-04.18:01:11.476>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 29981
keywords = ['patch', 'easy']
message_count = 10.0
messages = ['291129', '291132', '296580', '369475', '369489', '369490', '369501', '379165', '379554', '379555']
nosy_count = 7.0
nosy_names = ['akuchling', 'terry.reedy', 'r.david.murray', 'docs@python', 'louielu', 'miss-islington', 'DahlitzFlorian']
pr_nums = ['995', '20272', '22836', '22837']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29981'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by terryjreedy** [comment]
The index currently has

comprehensions
   \*list\*

```py
with *list* linked to 6.2.5 List displays.  I suggest:
```


1. Link \*comprehensions* to 6.2.4. Displays for lists, sets and dictionaries
2. Add subentries \*set*, \*dict*, and \*generator* linked to
2a. 6.2.6. Set displays
2b. 6.2.7. Dictionary displays
2c. 6.2.8. Generator expressions

We don't \*call* generator expressions 'generator comprehensions', but that is what they are syntactically and one looking for 'comprehensions' should be able to find them there.

There is already

\*list*
   ...
   \*comprehensions*
   ...
\*list comprehensions\*

with 'list' and 'list comprehensions' linked to glossary entries, while 'list, comprehensions' links to the same section as 'comprehensions, list'.  

3. Add 'set/dictionary, comprehensions' sub-entries linked like 'list, com
4. Add Glossary entries and links like 'list comprehensions'

**Comment by terryjreedy** [comment]
See bpo-29983 for expanding the title of the 'atoms' section containing subsections on comprehensions.

**Comment by bitdancer** [comment]
On the PR Berker wrote:

   I'm wondering if we should still advertise the use of set([...]). We replaced all instances of it with set literals in the stdlib.

set([...]) is part of the language, and the python documentation is also a specification of the language, so I think the reference \*must* stay.
