### ISSUE TITLE
Issue in extending documentation

### ISSUE THREAD

**Issue by c136c390-61c6-4c0c-96bc-7598ec06f7f1** [python/cpython#74161]
BPO | [29975](https://bugs.python.org/issue29975)
--- | :---
Nosy | @terryjreedy, @vadmium, @bunseokbot
PRs | <li>python/cpython#983</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-07.19:29:47.308>
created_at = <Date 2017-04-04.02:36:41.068>
labels = ['invalid', 'type-bug', '3.7', 'docs']
title = 'Issue in extending documentation'
updated_at = <Date 2017-04-07.19:29:47.306>
user = 'https://github.com/bunseokbot'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-07.19:29:47.306>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-07.19:29:47.308>
closer = 'terry.reedy'
components = ['Documentation']
creation = <Date 2017-04-04.02:36:41.068>
creator = 'Namjun Kim'
dependencies = []
files = []
hgrepos = []
issue_num = 29975
keywords = []
message_count = 3.0
messages = ['291098', '291099', '291287']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'docs@python', 'martin.panter', 'Namjun Kim']
pr_nums = ['983']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29975'
versions = ['Python 3.7']
```

</p></details>

**Comment by c136c390-61c6-4c0c-96bc-7598ec06f7f1** [comment]
https://docs.python.org/3.7/extending/extending.html

"Should it become a dangling pointer, C code which raises the exception could cause a core dump or other unintended side effects."

The typo error in this sentence.

"If it become a dangling pointer, C code which raises the exception could cause a core dump or other unintended side effects."

fix the typo error.

**Comment by vadmium** [comment]
FWIW I don’t see any error in the first quote. “Should X happen, Y happens” is valid English. Though I admit this kind of grammar is not used that often.

If it is too hard to understand, it should be okay to change it to “If it becomes a danging pointer, . . .”.

[become → becomes]

**Comment by terryjreedy** [comment]
I agree with the rejection on the PR.
