### ISSUE TITLE
tempfile.TemporaryDirectory fails to delete itself

### ISSUE THREAD

**Issue by bef3b989-2e47-4e9c-91d3-504408b50b75** [python/cpython#74168]
BPO | [29982](https://bugs.python.org/issue29982)
--- | :---
Nosy | @gvanrossum, @pfmoore, @tjguk, @pkch, @zware, @serhiy-storchaka, @zooba, @CAM-Gerlach, @websurfer5
PRs | <li>python/cpython#24793</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2021-03-14.18:11:24.171>
created_at = <Date 2017-04-04.18:26:18.456>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = 'tempfile.TemporaryDirectory fails to delete itself'
updated_at = <Date 2021-03-14.18:11:24.171>
user = 'https://github.com/pkch'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-14.18:11:24.171>
actor = 'gvanrossum'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2021-03-14.18:11:24.171>
closer = 'gvanrossum'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-04-04.18:26:18.456>
creator = 'max'
dependencies = []
files = []
hgrepos = []
issue_num = 29982
keywords = ['patch']
message_count = 6.0
messages = ['291130', '292562', '388219', '388246', '388318', '388680']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'paul.moore', 'tim.golden', 'max', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'CAM-Gerlach', 'Jeffrey.Kintscher']
pr_nums = ['24793']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29982'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
There's a known issue with `shutil.rmtree` on Windows, in that it fails intermittently. 

The issue is well known (https://mail.python.org/pipermail/python-dev/2013-September/128353.html), and the agreement is that it cannot be cleanly solved inside `shutil` and should instead be solved by the calling app. Specifically, python devs themselves faced it in their test suite and solved it by retrying delete.

However, what to do about `tempfile.TemporaryDirectory`? Is it considered the calling app, and therefore should retry delete when it calls `shutil.rmtree` in its `cleanup` method?

I don't think `tempfile` is protected by the same argument that `shutil.rmtree` is protected, in that it's too messy to solve it in the standard library. My rationale is that while it's very easy for the end user to retry `shutil.rmtree`, it's far more difficult to fix the problem with `tempfile.TempDirectory` not deleting itself - how would the end user retry the `cleanup` method (which is called from `weakref.finalizer`)?

So perhaps the retry loop should be added to `cleanup`.

**Comment by gvanrossum** [comment]
A simpler approach would be to simply ignore the error when it occurs in TemporaryDirectory.\_cleanup. There are no absolute guarantees about tempfile always cleaning up -- just a best effort. The complexity (and potential delays) of a retry loop seem more risky than simply occasionally not cleaning up -- that happens anyways, for a variety of reasons.
