### ISSUE TITLE
error of parsing encoded words in email of standard library

### ISSUE THREAD

**Issue by c34f15eb-b5a0-43ac-a0ed-8ed6ae70be16** [python/cpython#74179]
BPO | [29993](https://bugs.python.org/issue29993)
--- | :---
Nosy | @warsaw, @rhettinger, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-05.17:34:29.979>
created_at = <Date 2017-04-05.09:30:45.404>
labels = ['type-bug', 'invalid', 'expert-email']
title = 'error of parsing encoded words in email of standard library'
updated_at = <Date 2017-04-05.17:39:17.631>
user = 'https://bugs.python.org/sijianliang'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-05.17:39:17.631>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-05.17:34:29.979>
closer = 'r.david.murray'
components = ['email']
creation = <Date 2017-04-05.09:30:45.404>
creator = 'sijian liang'
dependencies = []
files = []
hgrepos = []
issue_num = 29993
keywords = []
message_count = 5.0
messages = ['291171', '291182', '291184', '291189', '291190']
nosy_count = 4.0
nosy_names = ['barry', 'rhettinger', 'r.david.murray', 'sijian liang']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue29993'
versions = ['Python 2.7']
```

</p></details>

**Comment by c34f15eb-b5a0-43ac-a0ed-8ed6ae70be16** [comment]
This issue is fixed in python3
see https://github.com/python/cpython/commit/07ea53cb218812404cdbde820647ce6e4b2d0f8e

**Comment by rhettinger** [comment]
Barry, is this something that should go back to 2.7 or is that pretty much settled business at this point?

**Comment by warsaw** [comment]
On Apr 05, 2017, at 03:26 PM, Raymond Hettinger wrote:

>Barry, is this something that should go back to 2.7 or is that pretty much
>settled business at this point?

I think we should not backport this.  It's a behavior change and my concern
would be that anybody who's bitten by this in Python 2.7 is either already
dealing with it or has already worked around it.  I wouldn't want to change
that in a 2.7 point release.

@r.david.murray might have a different opinion.

**Comment by bitdancer** [comment]
I consciously decided not to backport this to 2.7 at the time, though I'm not sure I said that out loud.  I think it is too much of a behavior change for 2.7.

**Comment by bitdancer** [comment]
Actually, looking at the issue related to the patch, we conferred at the time, Barry, and decided on no backports.  It was applied only to default.  Sijian: the reason we put the issue number in the commit message is because the issue often contains relevant discussion that can supplement the commit message.
