### ISSUE TITLE
inspect.isgeneratorfunction not working with partial functions

### ISSUE THREAD

**Issue by 9777c58c-4c48-4581-835d-9b40a023da52** [python/cpython#74173]
BPO | [29987](https://bugs.python.org/issue29987)
--- | :---
Nosy | @terryjreedy, @vadmium
Files | <li>[testcode.py](https://bugs.python.org/file46776/testcode.py "Uploaded as text/plain at 2017-04-04.23:35:14 by Thomas Antony"): Test code demonstrating the bug</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-07.20:23:13.924>
created_at = <Date 2017-04-04.23:35:15.074>
labels = ['type-feature', '3.7']
title = 'inspect.isgeneratorfunction not working with partial functions'
updated_at = <Date 2017-04-07.20:27:44.954>
user = 'https://bugs.python.org/ThomasAntony'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-07.20:27:44.954>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-07.20:23:13.924>
closer = 'terry.reedy'
components = []
creation = <Date 2017-04-04.23:35:15.074>
creator = 'Thomas Antony'
dependencies = []
files = ['46776']
hgrepos = []
issue_num = 29987
keywords = []
message_count = 6.0
messages = ['291147', '291150', '291156', '291169', '291290', '291291']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'martin.panter', 'Thomas Antony']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue29987'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9777c58c-4c48-4581-835d-9b40a023da52** [comment]
When inspect.isgeneratorfunction is called on the output of functools.partial, it returns False even if the original function was a generator function. Test case is attached. 

Tested in fresh conda environment running Python 3.6.1

**Comment by vadmium** [comment]
Doesn't seem like a bug to me.

Even if there was special support for "partial" objects, that won't help with other ways of producing the same sort of thing.

```py
test2 = functools.partial(test, a=10)

@functools.wraps(test)
def test2():
    return test(a=10)
```


Both ways produce a callable that returns a generator-iterator instance, but neither callables are really generator functions.

**Comment by 9777c58c-4c48-4581-835d-9b40a023da52** [comment]
Is there any way to distinguish such callables from "normal" functions without actually calling them?

**Comment by vadmium** [comment]
Not in general. I think you would have to make special cases for partial functions, \_\_wrapped__, and whatever else there is, and combinations of these. It would be very hard to determine the correct result for test2 in

```py
test2 = lambda: test(a=10)  # test2() returns a generator

def test(a):
    '''Redefined as a non-generator!'''
# Now test2() returns None
```


Maybe there is an argument for supporting partial as a new feature, but I don’t think it is a bug. I think there is precedent with the inspect.getargspec etc.

**Comment by terryjreedy** [comment]
A generator function \*gf* is a function that contain \*yield* in its body.  When it is compiled, flag CO_GENERATOR is set in gf.\_\_code__.co_flags.  When the function is called, the flag is queried and if set, a special path is taken that attaches the live but suspended code instance to a generator instance.

\*isgeneratorfunction* tests that an object is a function and that the flag is set.

```py
    return bool((isfunction(object) or ismethod(object)) and
                object.__code__.co_flags & CO_GENERATOR)
```


This is exactly what it should do.

Any function could potentially call a generator function and return its result.  Martin's \*test2*, with or without the wrapper, is an example.

Note that \*iscoroutinefunction* and \*isaynchgenfunction* follow the same pattern, but with different flags.  A 4th flag is queried by \*isawaitable*. The return object of any of these could also by returned by other functions.

**Comment by terryjreedy** [comment]
If you want to know if a function returns a generator, you have to call it and pass the result to \*isgenerator*, or use type-annotated functions (see the typing module) and static type checkers.
