### ISSUE TITLE
Documentation recommends raising TypeError from tp_richcompare

### ISSUE THREAD

**Issue by aa295720-5a49-4ff0-b9cc-4061f453b2dc** [python/cpython#74172]
BPO | [29986](https://bugs.python.org/issue29986)
--- | :---
Nosy | @rhettinger, @ssbr, @bitdancer, @jdemeyer, @JulienPalard, @miss-islington, @iritkatriel
PRs | <li>python/cpython#987</li><li>python/cpython#16095</li><li>python/cpython#16097</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-20.10:19:15.645>
created_at = <Date 2017-04-04.22:51:53.965>
labels = ['docs']
title = 'Documentation recommends raising TypeError from tp_richcompare'
updated_at = <Date 2020-10-20.10:19:15.645>
user = 'https://github.com/ssbr'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-20.10:19:15.645>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-10-20.10:19:15.645>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-04-04.22:51:53.965>
creator = 'Devin Jeanpierre'
dependencies = []
files = []
hgrepos = []
issue_num = 29986
keywords = ['patch']
message_count = 8.0
messages = ['291144', '291145', '291146', '291149', '338940', '352315', '352317', '377898']
nosy_count = 8.0
nosy_names = ['rhettinger', 'Devin Jeanpierre', 'r.david.murray', 'docs@python', 'jdemeyer', 'mdk', 'miss-islington', 'iritkatriel']
pr_nums = ['987', '16095', '16097']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue29986'
versions = []
```

</p></details>

**Comment by aa295720-5a49-4ff0-b9cc-4061f453b2dc** [comment]
am not sure when TypeError is the right choice. Definitely, most of the time I've seen it done, it causes trouble, and NotImplemented usually does something better.

For example, see the work in https://bugs.python.org/issue8743 to get set to interoperate correctly with other set-like classes --- a problem caused by the use of TypeError instead of returning NotImplemented (e.g. https://hg.python.org/cpython/rev/3615cdb3b86d).

This advice seems to conflict with the usual and expected behavior of objects from Python: e.g. object().\_\_lt__(1) returns NotImplemented rather than raising TypeError, despite \< not "making sense" for object. Similarly for file objects and other uncomparable classes. Even complex numbers only return NotImplemented!


```pycon
>>> 1j.__lt__(1j)
NotImplemented
```



If this note should be kept, this section could use a decent explanation of the difference between "undefined" (should return NotImplemented) and "nonsensical" (should apparently raise TypeError). Perhaps a reference to an example from the stdlib.

**Comment by aa295720-5a49-4ff0-b9cc-4061f453b2dc** [comment]
Sorry, forgot to link to docs because I was copy-pasting from the PR:

https://docs.python.org/2/c-api/typeobj.html#c.PyTypeObject.tp_richcompare

https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_richcompare

> Note: If you want to implement a type for which only a limited set of comparisons makes sense (e.g. == and !=, but not \< and friends), directly raise TypeError in the rich comparison function.

**Comment by bitdancer** [comment]
The documentation is technically correct, as far as I can see.  bpo-8743 is not about disallowing certain comparison operations, but rather incorrectly implementing the earlier sentence in that same doc section: "If the comparison is undefined, it must return Py_NotImplemented".  Perhaps the wording should be changed so that instead of saying "only a limited set of comparisons makes sense" it says "if you wish to disallow certain comparison operations while allowing others".  It should also probably be demoted from being a '.. note', since it is, as you note, an exceptional case, not a common one.

But you might be right that it would be better to delete it altogether, since it is generally better to let the comparison machinery raise the error if none of the types implements the comparison...what would be the rationale for a blanket \*dis\*allowing of a particular comparison operation?  

Let's see what Raymond thinks.

**Comment by aa295720-5a49-4ff0-b9cc-4061f453b2dc** [comment]
Yeah, I agree there might be a use-case (can't find one offhand, but in principle), but I think it's rare enough that you're more likely to be led astray from reading this note -- almost always, NotImplemented does what you want.

In a way this is a special case of being able to raise an exception at all, which is mentioned earlier ("if another error occurred it must return NULL and set an exception condition.")
