### ISSUE TITLE
CPython contribution docs reference missing /issuetracker page

### ISSUE THREAD

**Issue by 3b947fab-979e-486a-ab42-9b758222c04f** [python/cpython#74187]
BPO | [30001](https://bugs.python.org/issue30001)
--- | :---
Nosy | @Mariatta, @strugee

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-06.03:36:12.216>
created_at = <Date 2017-04-06.00:50:49.908>
labels = ['docs']
title = 'CPython contribution docs reference missing /issuetracker page'
updated_at = <Date 2017-04-06.17:01:14.044>
user = 'https://github.com/strugee'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-06.17:01:14.044>
actor = 'strugee'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-06.03:36:12.216>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-06.00:50:49.908>
creator = 'strugee'
dependencies = []
files = []
hgrepos = []
issue_num = 30001
keywords = []
message_count = 3.0
messages = ['291202', '291206', '291237']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'strugee']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30001'
versions = []
```

</p></details>

**Comment by 3b947fab-979e-486a-ab42-9b758222c04f** [comment]
https://cpython-devguide.readthedocs.io/pullrequest.html#licensing (and presumably other pages in this project) references https://cpython-devguide.readthedocs.io/issuetracker, but this page returns 404 Not Found.

**Comment by Mariatta** [comment]
Thanks for the report, Alex.

The issue tracker for the [devguide](https://devguide.python.org) is at https://github.com/python/devguide

Do you mind filling the issue there?
I'm closing this since this tracks only issues for CPython.
Thanks :)

**Comment by 3b947fab-979e-486a-ab42-9b758222c04f** [comment]
Filed https://github.com/python/devguide/issues/156.

Sorry for the noise! I just assumed everything went through bpo. Guess not :)
