### ISSUE TITLE
HTMLParser class is not thread safe

### ISSUE THREAD

**Issue by 440511f0-8c8e-4852-8882-6e4b30628032** [python/cpython#74197]
BPO | [30011](https://bugs.python.org/issue30011)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @ale
PRs | <li>python/cpython#1140</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-15.16:01:18.413>
created_at = <Date 2017-04-07.08:26:37.520>
labels = ['easy', 'type-bug', 'library']
title = 'HTMLParser class is not thread safe'
updated_at = <Date 2017-04-15.16:01:18.413>
user = 'https://github.com/ale'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-15.16:01:18.413>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-15.16:01:18.413>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-07.08:26:37.520>
creator = 'ale2017'
dependencies = []
files = []
hgrepos = []
issue_num = 30011
keywords = ['easy']
message_count = 5.0
messages = ['291256', '291704', '291706', '291709', '291717']
nosy_count = 3.0
nosy_names = ['ezio.melotti', 'serhiy.storchaka', 'ale2017']
pr_nums = ['1140']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30011'
versions = ['Python 2.7']
```

</p></details>

**Comment by 440511f0-8c8e-4852-8882-6e4b30628032** [comment]
SYMPTOM:
When used in a multithreaded program, instances of a class derived from HTMLParser may convert an entity or leave it alone, in an apparently random fashion.

CAUSE:
The class has a static attribute, entitydefs, which, on first use, is initialized from None to a dictionary of entity definitions.  Initialization is not atomic.  Therefore, instances in concurrent threads assume that initialization is complete and catch a KeyError if the entity at hand hasn't been set yet.  In that case, the entity is left alone as if it were invalid.

WORKAROUND:
class Dummy(HTMLParser):
	"""this class is defined here so that we can initialize its base class"""
	def \_\_init__(self):
		HTMLParser.\_\_init__(self)

```py
# Initialize HTMLParser by loading htmlentitydefs
dummy = Dummy()
dummy.feed('<a href="&amp;">')
del dummy, Dummy
```

**Comment by 440511f0-8c8e-4852-8882-6e4b30628032** [comment]
On Fri 14/Apr/2017 19:44:29 +0200 Serhiy Storchaka wrote:
> 
> Changes by Serhiy Storchaka \<storchaka+cpython@gmail.com\>:
> 
> 
> \----------
> pull_requests: +1272

Thank you for your fix, Serhiy.  It makes the class behave consistently.
 However, busy processes are going to concurrently build multiple
temporary entitydefs objects before one of them wins, which is probably
worse than the greedy starting that such lazy initialization tries to
avoid in the first place.  Doesn't that design deserve a comment in the
code, at least?

Greetings
Ale

**Comment by serhiy-storchaka** [comment]
There is nothing wrong with building entitydefs multiple times since the result is same. An alternative is using locking, but this is more cumbersome solution. And building entitydefs is much faster than importing the threading module.

```sh
$ ./python -m timeit -s 'from HTMLParser import HTMLParser; p = HTMLParser()' -- 'HTMLParser.entitydefs = None; p.unescape("&amp;")'
1000 loops, best of 3: 412 usec per loop

$ ./python -m timeit -s 'import sys; m = sys.modules.copy()' -- 'import threading; sys.modules.clear(); sys.modules.update(m)'
100 loops, best of 3: 5.43 msec per loop
```


Current solution is faster in single-thread case, correct likely fast enough in multi-thread case.

**Comment by 440511f0-8c8e-4852-8882-6e4b30628032** [comment]
Serhiy's analysis is correct.  If anything more than a comment is going
to make its way to the code, I'd suggest to move dictionary building to
its own function, so that it can be called either on first use --like
now-- or before threading if the user is concerned.

I agree there is nothing wrong with multiple builds.  My point is just a
minor, bearable inefficiency.  It can be neglected.  Its most annoying
case is probably with test suites, which are more likely to shoot up a
bunch of new threads all at once.

Greetings
Ale

**Comment by serhiy-storchaka** [comment]
New changeset 50f948edda0e6465e194ecc50b85fa2646039b8d by Serhiy Storchaka in branch '2.7':
bpo-30011: Fixed race condition in HTMLParser.unescape(). (bpo-1140)
https://github.com/python/cpython/commit/50f948edda0e6465e194ecc50b85fa2646039b8d
