### ISSUE TITLE
report bug

### ISSUE THREAD

**Issue by 772ab2a4-5dc5-4c58-b3ce-c9b9c01a5099** [python/cpython#74193]
BPO | [30007](https://bugs.python.org/issue30007)
--- | :---
Nosy | @zhangyangyu, @Yaredoh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-06.13:12:07.385>
created_at = <Date 2017-04-06.12:45:18.490>
labels = []
title = 'report bug'
updated_at = <Date 2017-04-06.13:12:07.383>
user = 'https://github.com/Yaredoh'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-06.13:12:07.383>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-06.13:12:07.385>
closer = 'xiang.zhang'
components = []
creation = <Date 2017-04-06.12:45:18.490>
creator = 'Yaredoh'
dependencies = []
files = []
hgrepos = []
issue_num = 30007
keywords = []
message_count = 2.0
messages = ['291225', '291226']
nosy_count = 2.0
nosy_names = ['xiang.zhang', 'Yaredoh']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30007'
versions = []
```

</p></details>

**Comment by 772ab2a4-5dc5-4c58-b3ce-c9b9c01a5099** [comment]
Hello,

I am using python 3.6 could you look at this bug. Thanks.

/home/yared/anaconda3/lib/python3.6/site-packages/mlimages/util/file_api.py
in add_ext_name(cls, path, ext_name)     63     @classmethod     64
 def add_ext_name(cls, path, ext_name):---\> 65         name, ext =
os.path.splitext(os.path.basename(path))     66         added =
os.path.join(os.path.dirname(path), name + ext_name + ext)     67
   return added
/home/yared/anaconda3/lib/python3.6/posixpath.py in basename(p)    142
def basename(p):    143     """Returns the final component of a
pathname"""--\> 144     p = os.fspath(p)    145     sep = \_get_sep(p)
 146     i = p.rfind(sep) + 1

TypeError: expected str, bytes or os.PathLike object, not ImageProperty

**Comment by zhangyangyu** [comment]
This tracker is for CPython developing. Your problem is in the third party module. You could refer Google or stackoverflow.
