### ISSUE TITLE
Initial bytes to BytesIO cannot be seeked to

### ISSUE THREAD

**Issue by 1d37b124-541b-4b8d-9563-623a828ff7d6** [python/cpython#74196]
BPO | [30010](https://bugs.python.org/issue30010)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[bytesio_bug.py](https://bugs.python.org/file46784/bytesio_bug.py "Uploaded as text/plain at 2017-04-07.07:40:15 by Samuli G"): An example exhibiting the bug on Python 3.6.0</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-07.07:55:10.322>
created_at = <Date 2017-04-07.07:40:16.102>
labels = ['type-bug', 'invalid', 'expert-IO']
title = 'Initial bytes to BytesIO cannot be seeked to'
updated_at = <Date 2017-04-07.07:55:10.321>
user = 'https://bugs.python.org/SamuliG'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-07.07:55:10.321>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-07.07:55:10.322>
closer = 'serhiy.storchaka'
components = ['IO']
creation = <Date 2017-04-07.07:40:16.102>
creator = 'Samuli G'
dependencies = []
files = ['46784']
hgrepos = []
issue_num = 30010
keywords = []
message_count = 2.0
messages = ['291254', '291255']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Samuli G']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30010'
versions = ['Python 3.6']
```

</p></details>

**Comment by 1d37b124-541b-4b8d-9563-623a828ff7d6** [comment]
The initial bytes provided for the BytesIO constructor are lost when the stream is written to.

Seeking to offset zero, and then getting the value of the entire buffer results of getting only the bytes that have been appended by calling "write".

**Comment by serhiy-storchaka** [comment]
This is expected behavior. When you write to ByitesIO you overwrites the old content.

If you want to append to ByitesIO, first move the position to the end: b.seek(0, io.SEEK_END).
