### ISSUE TITLE
Integer conversion failure

### ISSUE THREAD

**Issue by bc32d54b-212e-4d78-b482-263a73578987** [python/cpython#74195]
BPO | [30009](https://bugs.python.org/issue30009)
--- | :---
Nosy | @serhiy-storchaka, @eryksun, @nvutri
Files | <li>[int_bug.py](https://bugs.python.org/file46783/int_bug.py "Uploaded as text/plain at 2017-04-07.04:02:05 by @nvutri"): Code to reproduce error for int</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-07.04:19:16.773>
created_at = <Date 2017-04-07.04:02:05.900>
labels = ['invalid', 'type-bug', 'library']
title = 'Integer conversion failure'
updated_at = <Date 2017-04-07.04:20:16.769>
user = 'https://github.com/nvutri'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-07.04:20:16.769>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-07.04:19:16.773>
closer = 'eryksun'
components = ['Library (Lib)']
creation = <Date 2017-04-07.04:02:05.900>
creator = 'nvutri'
dependencies = []
files = ['46783']
hgrepos = []
issue_num = 30009
keywords = []
message_count = 3.0
messages = ['291249', '291250', '291251']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'eryksun', 'nvutri']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30009'
versions = ['Python 2.7']
```

</p></details>

**Comment by bc32d54b-212e-4d78-b482-263a73578987** [comment]
This code below shows a situation when Python int() library would return a value of int(1.0) -\> 0.0

\---------------CODE\----------------------------
```py
CHANGES = [1.00, 0.50, 0.25, 0.10, 0.05, 0.01]
```


\# This code was originally to solve the least number of changes needed.
\# However, in an attempt to solve this. A bug is found.

```py
def get_change(R):
    for change in CHANGES:
        # This division and int() is where failure is happening
        num = int(R / change)
        # This printing line shows the failure.
        print 'int(%s)\t = %s' % (R / change, num)
        R = R - num * change
    print 'R = %s' % R

get_change(4.01)
```


\-------------OUTPUT\----------------------

int(4.01)	 = 4
int(0.02)	 = 0
int(0.04)	 = 0
int(0.1)	 = 0
int(0.2)	 = 0
int(1.0)	 = 0    # This should be 1, right?
R = 0.01

**Comment by eryksun** [comment]
Use %r instead of %s to show the repr. Hopefully that should clear things up for you. int() truncates toward 0. The float in this case is slightly less than 1.

**Comment by serhiy-storchaka** [comment]
"%s" rounds float representation to 12 digits in Python 2.7. Replace "%s" with "%r" and you will get precise representation of floats.

int(4.01)        = 4
int(0.019999999999999574)        = 0
int(0.03999999999999915)         = 0
int(0.09999999999999787)         = 0
int(0.19999999999999574)         = 0
int(0.9999999999999787)  = 0
R = 0.009999999999999787

See also https://docs.python.org/2/tutorial/floatingpoint.html .
