### ISSUE TITLE
Get rid of using EnvironmentError and IOError

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74208]
BPO | [30022](https://bugs.python.org/issue30022)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka
PRs | <li>python/cpython#1051</li><li>python/cpython#2107</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-04-16.07:47:56.846>
created_at = <Date 2017-04-08.10:05:39.209>
labels = ['type-feature', '3.7']
title = 'Get rid of using EnvironmentError and IOError'
updated_at = <Date 2017-06-11.10:27:25.720>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-11.10:27:25.720>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-04-16.07:47:56.846>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-04-08.10:05:39.209>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30022
keywords = []
message_count = 4.0
messages = ['291332', '291697', '291745', '295700']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'serhiy.storchaka']
pr_nums = ['1051', '2107']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30022'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
EnvironmentError and IOError now are aliases to OSError. But some code still use them. Proposed patch replaces all uses of EnvironmentError and IOError (except tests and scripts) with OSError. This will make the code cleaner and more uniform.

**Comment by terryjreedy** [comment]
I checked the patch and it appears to be a clean search/replace.  I assume that the aliases have the same diff in C as in Python.

The only idlelib replacement is in run.py, where I (mistakenly) added IOError in 3.3 and 3.4 as well as in 2.7.  This must have been after a previous global replacement.  I would like this change backported to 3.6 to keep the files identical.

**Comment by serhiy-storchaka** [comment]
New changeset 55fe1ae9708d81b902b6fe8f6590e2a24b1bd4b0 by Serhiy Storchaka in branch 'master':
bpo-30022: Get rid of using EnvironmentError and IOError (except test… (bpo-1051)
https://github.com/python/cpython/commit/55fe1ae9708d81b902b6fe8f6590e2a24b1bd4b0

**Comment by terryjreedy** [comment]
New changeset 59422a29ee3a95866c4f7e037bdfffd5768afddd by terryjreedy in branch '3.6':
[3.6]bpo-30022: idlelib.run IOError -\> OSError [GH-1051] (bpo-2107)
https://github.com/python/cpython/commit/59422a29ee3a95866c4f7e037bdfffd5768afddd
