### ISSUE TITLE
Hashable doesn't check for __eq__

### ISSUE THREAD

**Issue by bef3b989-2e47-4e9c-91d3-504408b50b75** [python/cpython#74212]
BPO | [30026](https://bugs.python.org/issue30026)
--- | :---
Nosy | @rhettinger, @pkch

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-04-09.18:40:47.039>
created_at = <Date 2017-04-09.16:23:03.527>
labels = ['invalid', 'docs']
title = "Hashable doesn't check for __eq__"
updated_at = <Date 2017-04-09.18:40:47.037>
user = 'https://github.com/pkch'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-09.18:40:47.037>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-04-09.18:40:47.039>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-04-09.16:23:03.527>
creator = 'max'
dependencies = []
files = []
hgrepos = []
issue_num = 30026
keywords = []
message_count = 3.0
messages = ['291382', '291383', '291385']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'max']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30026'
versions = []
```

</p></details>

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
I think collections.abc.Hashable.\_\_subclasshook__ should check \_\_eq__ method in addition to \_\_hash__ method. This helps detect classes that are unhashable due to:

to \_\_eq__ = None

Of course, it still cannot detect:

def \_\_eq__: return NotImplemented

but it's better than nothing.

In addition, it's probably worth documenting that explicitly inheriting from Hashable has (correct but unexpected) effect of \*suppressing* hashability that was already present:

```py
from collections.abc import Hashable
class X: pass
assert issubclass(X, Hashable)
x = X()

class X(Hashable): pass
assert issubclass(X, Hashable)
x = X() # Can't instantiate abstract class X with abstract methods
```

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
Sorry, this should be just a documentation issue.

I just realized that \_\_eq__ = None isn't correct anyway, so instead we should just document that Hashable cannot check for \_\_eq__ and that explicitly deriving from Hashable suppresses hashability.

**Comment by rhettinger** [comment]
> # Can't instantiate abstract class X with abstract methods

Sorry, this is how ABCs are supposed to work.  They use @abstractmethod to specify requirements that a subclass if required to implement.  The ABC metaclass then enforces that requirement, preventing instantiation unless those requirements are met.  If not met, they give a reasonably clear error message, "TypeError: Can't instantiate abstract class A with abstract methods \_\_hash__".
