### ISSUE TITLE
email module base64-encodes utf-8 text

### ISSUE THREAD

**Issue by 2c8ee9fa-7f11-45f7-b140-44790542eb15** [python/cpython#74219]
BPO | [30033](https://bugs.python.org/issue30033)
--- | :---
Nosy | @warsaw, @jribbens, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-10.18:23:53.835>
created_at = <Date 2017-04-10.17:45:40.786>
labels = ['type-bug', 'library', 'expert-email']
title = 'email module base64-encodes utf-8 text'
updated_at = <Date 2017-04-10.19:16:35.167>
user = 'https://github.com/jribbens'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-10.19:16:35.167>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-10.18:23:53.835>
closer = 'r.david.murray'
components = ['Library (Lib)', 'email']
creation = <Date 2017-04-10.17:45:40.786>
creator = 'jribbens'
dependencies = []
files = []
hgrepos = []
issue_num = 30033
keywords = []
message_count = 4.0
messages = ['291435', '291439', '291445', '291449']
nosy_count = 3.0
nosy_names = ['barry', 'jribbens', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30033'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 2c8ee9fa-7f11-45f7-b140-44790542eb15** [comment]
The email module, when creating text parts using character encoding utf-8, base64-encodes the output even though this is often inappropriate (e.g. if it is a Western language it is almost never appropriate).

```pycon
>>> from email.mime.text import MIMEText
>>> m = MIMEText("hello", _charset="utf-8")
>>> m.as_string()
'Content-Type: text/plain; charset="utf-8"\nMIME-Version: 1.0\nContent-Transfer-Encoding: base64\n\naGVsbG8=\n'
```

**Comment by bitdancer** [comment]
Yes, this sub-optimal, but it's the way it works in the legacy API, and we aren't going to change the legacy (compat32) API at this point.  The new policies and the new API in python3 handle this sensibly.

**Comment by 2c8ee9fa-7f11-45f7-b140-44790542eb15** [comment]
Just a note for anyone finding this in searching results: it appears that what David means by "python3 API" is actually a new API in Python 3.6 (email.message.EmailMessage).

**Comment by bitdancer** [comment]
The API exists in python3.5 and python3.4 as well, it was just provisional.  Very few things changed between the provisional version and the final version in 3.6.
