### ISSUE TITLE
make test.support.temp_cwd() fork-safe

### ISSUE THREAD

**Issue by 6c8a72cc-9872-4016-ae96-23477ed791a8** [python/cpython#74214]
BPO | [30028](https://bugs.python.org/issue30028)
--- | :---
Nosy | @gpshead, @vsajip, @vstinner, @tiran, @methane, @serhiy-storchaka, @akruis, @miss-islington
PRs | <li>python/cpython#1066</li><li>python/cpython#1074</li><li>python/cpython#5824</li><li>python/cpython#5825</li><li>python/cpython#5826</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-23.16:28:33.464>
created_at = <Date 2017-04-09.20:00:25.062>
labels = ['3.7', '3.8', 'type-bug', 'tests']
title = 'make test.support.temp_cwd() fork-safe'
updated_at = <Date 2018-02-23.16:28:33.462>
user = 'https://github.com/akruis'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-23.16:28:33.462>
actor = 'gregory.p.smith'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-23.16:28:33.464>
closer = 'gregory.p.smith'
components = ['Tests']
creation = <Date 2017-04-09.20:00:25.062>
creator = 'anselm.kruis'
dependencies = []
files = []
hgrepos = []
issue_num = 30028
keywords = ['patch']
message_count = 14.0
messages = ['291396', '291413', '291415', '291417', '291418', '291420', '291422', '291423', '291424', '291426', '312609', '312618', '312641', '312642']
nosy_count = 8.0
nosy_names = ['gregory.p.smith', 'vinay.sajip', 'vstinner', 'christian.heimes', 'methane', 'serhiy.storchaka', 'anselm.kruis', 'miss-islington']
pr_nums = ['1066', '1074', '5824', '5825', '5826']
priority = 'normal'
resolution = 'fixed'
stage = 'commit review'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30028'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 6c8a72cc-9872-4016-ae96-23477ed791a8** [comment]
The context manager test.support.temp_cwd() creates a temporary directory and removes it on exit. The test runner test.regrtest uses this context manager.

I observed an annoying behaviour of test.support.temp_cwd() on Linux/UNIX: if the code, that runs in the temp_cwd() context forks and if the forked child terminates (without calling exec), then the temporary directory will be removed twice: by the child and by the parent. This can cause errors in the parent, if the parent tries to access the no longer existing directory.

I discovered this problem, when a test in test_multiprocessing_fork failed and the test directory for the complete test.regrtest-run got removed. Of course all other tests failed too.

I propose to modify test.support.temp_cwd() to remove the created directory only, if the process id (os.getpid()) is unchanged. I'll create a pull request.

**Comment by serhiy-storchaka** [comment]
Is os.getpid always available? I have found hasattr(os, 'getpid') in the logging module.

**Comment by tiran** [comment]
The line is from 2006. Some parts of the logging module are much older, maybe even from the time Python had DOS support.

**Comment by 6c8a72cc-9872-4016-ae96-23477ed791a8** [comment]
I had the same concerns about os.getpid(), but test.support uses it unconditionally in various places. See https://github.com/python/cpython/blob/master/Lib/test/support/__init__.py#L803 for an example.

**Comment by serhiy-storchaka** [comment]
Then LGTM.

**Comment by vstinner** [comment]
I proposed [PR 1074](https://github.com/python/cpython/pull/1074) to remove the hasattr(os, 'getpid') from logging.LogRecord constructor.

**Comment by methane** [comment]
bpo-28156 added HAVE_GETPID check.
Maybe, we should have dummy getpid() for CloudABI?

**Comment by vstinner** [comment]
Naoki:
> bpo-28156 added HAVE_GETPID check.
> Maybe, we should have dummy getpid() for CloudABI?

Oh. If os.getpid() is not always available, the documentation should be updated.

**Comment by methane** [comment]
> Oh. If os.getpid() is not always available, the documentation should be updated.

Yes, but CloudABI is not officially supported platform.
They have many patches to run Python on CloudABI. https://github.com/NuxiNL/cloudabi-ports/tree/master/packages/python

How can we document about it?  I hadn't used it.

os.getlogin document says `Availability: Unix, Windows.` [1]
Is it proper way to indicate "there may be some minor platforms which doesn't provide this."?
[1] https://docs.python.org/3.6/library/os.html#os.getlogin

**Comment by serhiy-storchaka** [comment]
> os.getlogin document says `Availability: Unix, Windows.`

Originally this meant "not in Mac OS, DOS, OS/2, VMS". But now the support of all these platforms is dropped and the note is outdated.
