### ISSUE TITLE
Improve queens demo (use argparse and singular form)

### ISSUE THREAD

**Issue by 37255eef-8b90-4b1c-a8ee-42ba7295b578** [python/cpython#74217]
BPO | [30031](https://bugs.python.org/issue30031)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ericvsmith, @bitdancer, @PavloKapyshin, @mlouielu
PRs | <li>python/cpython#1084</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-04-18.16:42:16.841>
created_at = <Date 2017-04-10.13:06:37.969>
labels = ['easy', 'type-feature', '3.7']
title = 'Improve queens demo (use argparse and singular form)'
updated_at = <Date 2017-04-18.16:42:16.840>
user = 'https://github.com/PavloKapyshin'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-18.16:42:16.840>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-04-18.16:42:16.841>
closer = 'rhettinger'
components = ['Demos and Tools']
creation = <Date 2017-04-10.13:06:37.969>
creator = 'paka'
dependencies = []
files = []
hgrepos = []
issue_num = 30031
keywords = ['easy']
message_count = 11.0
messages = ['291428', '291432', '291436', '291438', '291440', '291698', '291801', '291804', '291814', '291819', '291838']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'eric.smith', 'r.david.murray', 'paka', 'louielu']
pr_nums = ['1084']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30031'
versions = ['Python 3.7']
```

</p></details>

**Comment by 37255eef-8b90-4b1c-a8ee-42ba7295b578** [comment]
Currently [Tools/demo/queens.py](https://github.com/python/cpython/blob/main/Tools/demo/queens.py):

 - does manual sys.argv parsing
 - says “Found 1 solutions”

I propose to: 1) use argparse; 2) if q.nfound == 1, use “solution”. I you are ok with this, I’ll make a pull request.

**Comment by ericvsmith** [comment]
I think these are reasonable improvements. Also, move the initialization of "silent" in to \_\_new__.

**Comment by bitdancer** [comment]
I'm not sure about using argparse.  Currently the demo uses no imports.  I'm not strongly against, though.

Did you mean \_\_init__ instead of \_\_new__?  Also, its value could be made True and False instead of 0 and 1.  (Which tells you how old this demo is.)

**Comment by ericvsmith** [comment]
Oops, yes, \_\_init__.

Plenty of the demos use imports. I think it would be clearer with argparse, but I also don't feel strongly about it.

**Comment by bitdancer** [comment]
Yeah, I was wondering if part of the demo was to show something that can be done with no library support...but that probably isn't the case.

**Comment by terryjreedy** [comment]
I prefer use of argparse.  Patch \*looks* good reading it, but I cannot test yet.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
I make some review at GitHub.

Do David and Terry suggest to also fix the problem about PEP-8 coding style, since this demo have many places didn't fit PEP-8.

**Comment by 37255eef-8b90-4b1c-a8ee-42ba7295b578** [comment]
Louie Lu, thank you for the review.

Different quotes were already used in file, so someone should
decide which ones must be used: single or double.

Regarding the -n option, I tried to be backwards compatible. Again,
a decision is needed.

The only place where I had a choice to not do something related to
PEP-8 was adding a line between Queens class and main function.
I decided to mention that fact in pull request. In other places I
had to follow contribution guide (therefore add code that follows
style guide).

**Comment by rhettinger** [comment]
Please focus on the task at hand and don't worry about PEP-8ing the existing code.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Pavlo, you are right, making the argument have backward compatible is good. String quote I'll prefer `'` more than `"`.

**Comment by rhettinger** [comment]
After more thought on the subject, I think the n-queens demo should be left as is.  The demo is principally about the class and not about being a command-line tool.  Also, it is reasonable and appropriate to use sys.argv directly for such a simple API.  How to do so is a legitimate example itself.  Not all uses of sys.argv need argparse.

In other words, I don't think the proposed changes makes anyone's life better and in the some ways makes the example less approachable for teaching purposes (my area of expertise).

The example works fine as-is.  Changing it seems like unnecessary code churn and already eating some of our time.

Thank you for the idea.  It never hurts to look around for ways to improve code.  Though I don't think there was a new win in this case, don't let that discourage you.  Please continue to look for improvements :-)
