### ISSUE TITLE
test_xml_etree and test_xml_etree_c fail due to AssertionError: unhandled warning DeprecationWarning

### ISSUE THREAD

**Issue by 80036ac5-bb84-4d39-8416-02cd8e51707d** [python/cpython#74213]
BPO | [30027](https://bugs.python.org/issue30027)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka
PRs | <li>python/cpython#1065</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-12.13:01:33.439>
created_at = <Date 2017-04-09.19:36:58.335>
labels = ['tests']
title = 'test_xml_etree and test_xml_etree_c fail due to AssertionError: unhandled warning DeprecationWarning'
updated_at = <Date 2017-04-12.13:01:33.438>
user = 'https://bugs.python.org/Arfrever'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-12.13:01:33.438>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-12.13:01:33.439>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-04-09.19:36:58.335>
creator = 'Arfrever'
dependencies = []
files = []
hgrepos = []
issue_num = 30027
keywords = []
message_count = 4.0
messages = ['291392', '291394', '291395', '291549']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'Arfrever', 'eli.bendersky', 'serhiy.storchaka']
pr_nums = ['1065']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30027'
versions = ['Python 2.7']
```

</p></details>

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
test_xml_etree.py and test_xml_etree_c.py on 2.7 branch fail since this commit:

commit 68903b656d4e1011525a46cbd1338c6cbab83d6d
Author: Serhiy Storchaka \<storchaka@gmail.com\>
Date:   Sun Apr 2 16:55:43 2017 +0300

    bpo-15083: Convert ElementTree doctests to unittests. (#906)


Output of test suite:

[388/399] test_xdrlib
[389/399] test_xml_etree
/tmp/cpython/Lib/test/test_xml_etree.py:1674: DeprecationWarning: Overriding \_\_eq__ blocks inheritance of \_\_hash__ in 3.x
  class MutatingElementPath(str):
/tmp/cpython/Lib/test/test_xml_etree.py:1684: DeprecationWarning: Overriding \_\_eq__ blocks inheritance of \_\_hash__ in 3.x
  class BadElementPath(str):
test test_xml_etree crashed -- \<type 'exceptions.AssertionError'\>: unhandled warning DeprecationWarning('Overriding \_\_eq__ blocks inheritance of \_\_hash__ in 3.x',)
[390/399/1] test_xml_etree_c
test test_xml_etree_c crashed -- \<type 'exceptions.AssertionError'\>: unhandled warning DeprecationWarning('classic int division',)
[391/399/2] test_xmllib
...
360 tests OK.
2 tests failed:
    test_xml_etree test_xml_etree_c
Re-running failed tests in verbose mode
Re-running test 'test_xml_etree' in verbose mode
/tmp/cpython/Lib/test/test_xml_etree.py:1674: DeprecationWarning: Overriding \_\_eq__ blocks inheritance of \_\_hash__ in 3.x
  class MutatingElementPath(str):
/tmp/cpython/Lib/test/test_xml_etree.py:1684: DeprecationWarning: Overriding \_\_eq__ blocks inheritance of \_\_hash__ in 3.x
  class BadElementPath(str):
...
Ran 117 tests in 0.934s

```pytb
OK
test test_xml_etree crashed -- <type 'exceptions.AssertionError'>: unhandled warning DeprecationWarning('Overriding __eq__ blocks inheritance of __hash__ in 3.x',)
Traceback (most recent call last):
  File "./Lib/test/regrtest.py", line 989, in runtest_inner
  File "/tmp/cpython/Lib/test/test_xml_etree.py", line 2671, in test_main
    support.run_unittest(*test_classes)
  File "/tmp/cpython/Lib/test/test_xml_etree.py", line 2630, in __exit__
    self.checkwarnings.__exit__(*args)
  File "/tmp/cpython/Lib/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/tmp/cpython/Lib/test/test_support.py", line 905, in _filterwarnings
    raise AssertionError("unhandled warning %r" % reraise[0])
AssertionError: unhandled warning DeprecationWarning('Overriding __eq__ blocks inheritance of __hash__ in 3.x',)
Re-running test 'test_xml_etree_c' in verbose mode
...
Ran 118 tests in 0.112s

OK (skipped=19)
test test_xml_etree_c crashed -- <type 'exceptions.AssertionError'>: unhandled warning DeprecationWarning('classic int division',)
Traceback (most recent call last):
  File "./Lib/test/regrtest.py", line 989, in runtest_inner
  File "/tmp/cpython/Lib/test/test_xml_etree_c.py", line 64, in test_main
    test_xml_etree.test_main(module=cET)
  File "/tmp/cpython/Lib/test/test_xml_etree.py", line 2671, in test_main
    support.run_unittest(*test_classes)
  File "/tmp/cpython/Lib/test/test_xml_etree.py", line 2630, in __exit__
    self.checkwarnings.__exit__(*args)
  File "/tmp/cpython/Lib/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/tmp/cpython/Lib/test/test_support.py", line 905, in _filterwarnings
    raise AssertionError("unhandled warning %r" % reraise[0])
AssertionError: unhandled warning DeprecationWarning('classic int division',)
2 tests failed again:
    test_xml_etree test_xml_etree_c
```

**Comment by serhiy-storchaka** [comment]
Ah, I ran tests with -Wa and -We, but forgot to run with -3. Thank you for noticing this Arfrever!

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
To reproduce problem when running only these 2 files, use e.g.:
python2.7 -3 -m test.test_xml_etree
python2.7 -3 -m test.test_xml_etree_c

For full test suite, this -3 option is set in Makefile:
TESTPYTHON=     $(RUNSHARED) ./$(BUILDPYTHON) -Wd -3 -E -tt $(TESTPYTHONOPTS)

**Comment by serhiy-storchaka** [comment]
New changeset 65c5b096ac2c6608d296f1603cd4792086108c95 by Serhiy Storchaka in branch '2.7':
bpo-30027: Fix Py3k warnings in test_xml_etree. (bpo-1065)
https://github.com/python/cpython/commit/65c5b096ac2c6608d296f1603cd4792086108c95
