### ISSUE TITLE
[RFC] PyMemberDef.name should be const char *

### ISSUE THREAD

**Issue by 892ced02-b53d-4325-9f58-50e009295e29** [python/cpython#74221]
BPO | [30035](https://bugs.python.org/issue30035)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[test.cpp](https://bugs.python.org/file46795/test.cpp "Uploaded as text/plain at 2017-04-11.04:34:43 by Sunyeop Lee"): c++ source code to reproduce the problem</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-09.17:59:39.872>
created_at = <Date 2017-04-11.04:34:45.085>
labels = ['extension-modules', 'build']
title = '[RFC] PyMemberDef.name should be const char *'
updated_at = <Date 2017-11-09.17:59:39.871>
user = 'https://bugs.python.org/SunyeopLee'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-09.17:59:39.871>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-09.17:59:39.872>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-04-11.04:34:45.085>
creator = 'Sunyeop Lee'
dependencies = []
files = ['46795']
hgrepos = []
issue_num = 30035
keywords = []
message_count = 2.0
messages = ['291459', '291676']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Sunyeop Lee']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30035'
versions = ['Python 3.6']
```

</p></details>

**Comment by 892ced02-b53d-4325-9f58-50e009295e29** [comment]
PyMemberDef from Noddy examaple: https://docs.python.org/3/extending/newtypes.html

static PyMemberDef Noddy_members[] = {
    {"first", T_OBJECT_EX, offsetof(Noddy, first), 0,
     "first name"},
    {"last", T_OBJECT_EX, offsetof(Noddy, last), 0,
     "last name"},
    {"number", T_INT, offsetof(Noddy, number), 0,
     "noddy number"},
    {NULL}  /* Sentinel \*/
};

When compiling the code with the PyMemberDef above with GCC, it compiles well. However, with G++, ISO C++11 complains(warns) it is deprecated to convert string literal to 'char \*' is deprecated [-Wc++11-compat-deprecated-writable-strings]

Should the example code be fixed, or should PyMemberDef fixed? I think PyMemberDef.name should bo const char * instead of char \*.

Compiled with:
g++ test.cpp -I/usr/local/Cellar/python3/3.6.0/Frameworks/Python.framework/Versions/3.6/include/python3.6m -L/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/config-3.6m-darwin -lpython3.6m -fPIC -shared

Compiler versions:

```sh
$ gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

$ g++ -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 8.1.0 (clang-802.0.38)
Target: x86_64-apple-darwin16.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by serhiy-storchaka** [comment]
PyMemberDef.name already is "const char \*" in 3.7 (see bpo-28761).

Adding the const qualifier in other branches can break existing code that assigns PyMemberDef.name to a variable of type "char \*". This is not appropriate for bugfix releases.
