### ISSUE TITLE
Resuming a 'yield from' stack is broken if a signal arrives in the middle

### ISSUE THREAD

**Issue by njsmith** [python/cpython#74225]
BPO | [30039](https://bugs.python.org/issue30039)
--- | :---
Nosy | @vstinner, @njsmith, @1st1
PRs | <li>python/cpython#1081</li><li>python/cpython#1640</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/1st1'
closed_at = <Date 2017-06-09.21:07:32.657>
created_at = <Date 2017-04-11.09:33:27.080>
labels = ['interpreter-core', 'type-bug', '3.7']
title = "Resuming a 'yield from' stack is broken if a signal arrives in the middle"
updated_at = <Date 2017-06-10.08:52:13.435>
user = 'https://github.com/njsmith'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.08:52:13.435>
actor = 'vstinner'
assignee = 'yselivanov'
closed = True
closed_date = <Date 2017-06-09.21:07:32.657>
closer = 'yselivanov'
components = ['Interpreter Core']
creation = <Date 2017-04-11.09:33:27.080>
creator = 'njs'
dependencies = []
files = []
hgrepos = []
issue_num = 30039
keywords = []
message_count = 8.0
messages = ['291469', '293887', '293902', '293903', '295578', '295579', '295580', '295620']
nosy_count = 3.0
nosy_names = ['vstinner', 'njs', 'yselivanov']
pr_nums = ['1081', '1640']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30039'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by njsmith** [comment]
If we have a chain of generators/coroutines that are 'yield from'ing each other, then resuming the stack works like:

- call send() on the outermost generator
- this enters \_PyEval_EvalFrameDefault, which re-executes the YIELD_FROM opcode
- which calls send() on the next generator
- which enters \_PyEval_EvalFrameDefault, which re-executes the YIELD_FROM opcode
- ...etc.

However, every time we enter \_PyEval_EvalFrameDefault, the first thing we do is to check for pending signals, and if there are any then we run the signal handler. And if it raises an exception, then we immediately propagate that exception \*instead* of starting to execute bytecode. This means that e.g. a SIGINT at the wrong moment can "break the chain" – it can be raised in the middle of our yield from chain, with the bottom part of the stack abandoned for the garbage collector.

The fix is pretty simple: there's already a special case in \_PyEval_EvalFrameEx where it skips running signal handlers if the next opcode is SETUP_FINALLY. (I don't see how this accomplishes anything useful, but that's another story.) If we extend this check to also skip running signal handlers when the next opcode is YIELD_FROM, then that closes the hole – now the exception can only be raised at the innermost stack frame.

This shouldn't have any performance implications, because the opcode check happens inside the "slow path" after we've already determined that there's a pending signal or something similar for us to process; the vast majority of the time this isn't true.

I'll post a PR in a few minutes that has a test case that demonstrates the problem and fails on current master, plus the fix.

**Comment by 1st1** [comment]
New changeset ab4413a7e9bda95b6fcd517073e2a51dafaa1624 by Yury Selivanov (Nathaniel J. Smith) in branch 'master':
bpo-30039: Don't run signal handlers while resuming a yield from stack (bpo-1081)
https://github.com/python/cpython/commit/ab4413a7e9bda95b6fcd517073e2a51dafaa1624

**Comment by vstinner** [comment]
The change should be backported to 3.5 and 3.6, right? The change seems very short and safe. IMHO it's ok to backport.

**Comment by 1st1** [comment]
Yes, I'll do the backport.

**Comment by 1st1** [comment]
New changeset e89f95bfd0881a9b80c3b1430d154a77bdf5a824 by Yury Selivanov in branch '3.6':
[3.6] bpo-30039: Don't run signal handlers while resuming a yield from stack (GH-1081) (bpo-1640)
https://github.com/python/cpython/commit/e89f95bfd0881a9b80c3b1430d154a77bdf5a824

**Comment by vstinner** [comment]
Why not backporting the fix to 3.5 as well?

**Comment by 1st1** [comment]
I don't think we need to. Isn't 3.5 is in security/important bug fix mode? I don't view this change as an important one (it's just a nice thing to have).

**Comment by vstinner** [comment]
Yury Selivanov added the comment:
> I don't think we need to. Isn't 3.5 is in security/important bug fix mode? I don't view this change as an important one (it's just a nice thing to have).

Not yet, it still accept bug fixes:
https://docs.python.org/devguide/#status-of-python-branches
