### ISSUE TITLE
inspect documentation on code attributes incomplete

### ISSUE THREAD

**Issue by 11571bd7-cc8f-4b80-a34f-d13719c58596** [python/cpython#74223]
BPO | [30037](https://bugs.python.org/issue30037)
--- | :---
Nosy | @vadmium, @Dutcho
Superseder | <li>bpo-26985: Information about CodeType in inspect documentation is outdated</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-11.08:27:16.316>
created_at = <Date 2017-04-11.07:51:50.672>
labels = ['type-feature', 'docs']
title = 'inspect documentation on code attributes incomplete'
updated_at = <Date 2017-04-11.08:27:16.302>
user = 'https://github.com/Dutcho'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-11.08:27:16.302>
actor = 'martin.panter'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-11.08:27:16.316>
closer = 'martin.panter'
components = ['Documentation']
creation = <Date 2017-04-11.07:51:50.672>
creator = 'Dutcho'
dependencies = []
files = []
hgrepos = []
issue_num = 30037
keywords = []
message_count = 2.0
messages = ['291464', '291465']
nosy_count = 3.0
nosy_names = ['docs@python', 'martin.panter', 'Dutcho']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '26985'
type = 'enhancement'
url = 'https://bugs.python.org/issue30037'
versions = ['Python 3.6']
```

</p></details>

**Comment by 11571bd7-cc8f-4b80-a34f-d13719c58596** [comment]
The table at the top of the inspect documentation (https://docs.python.org/3/library/inspect.html#types-and-members) omits co_cellvars, co_freevars, and co_kwonlyargcount attributes of type code

(note: the type's doc string does provide these attributes)

**Comment by vadmium** [comment]
Looks like a there is already a patch discussed at bpo-26985.
