### ISSUE TITLE
The bugs website doesn't use httpS by default

### ISSUE THREAD

**Issue by 11571bd7-cc8f-4b80-a34f-d13719c58596** [python/cpython#74222]
BPO | [30036](https://bugs.python.org/issue30036)
--- | :---
Nosy | @tiran, @berkerpeksag, @Mariatta, @Dutcho

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-13.11:35:20.080>
created_at = <Date 2017-04-11.07:45:41.629>
labels = ['type-bug', 'docs']
title = "The bugs website doesn't use httpS by default"
updated_at = <Date 2017-04-13.13:57:39.669>
user = 'https://github.com/Dutcho'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.13:57:39.669>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-13.11:35:20.080>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-11.07:45:41.629>
creator = 'Dutcho'
dependencies = []
files = []
hgrepos = []
issue_num = 30036
keywords = []
message_count = 3.0
messages = ['291463', '291602', '291616']
nosy_count = 4.0
nosy_names = ['christian.heimes', 'berker.peksag', 'Mariatta', 'Dutcho']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30036'
versions = ['Python 3.6']
```

</p></details>

**Comment by 11571bd7-cc8f-4b80-a34f-d13719c58596** [comment]
The footer of httpS://python.org links to httP://bugs.python.org, compromising user data for login and register options

**Comment by Mariatta** [comment]
Thanks for the report.
Issue with the footer of python.org website can be filed at https://github.com/python/pythondotorg

Regarding the fact that bugs.python.org does not use https by default, it is being tracked here http://psf.upfronthosting.co.za/roundup/meta/issue463

I'm closing this and marking as duplicate.
Thanks :)

**Comment by berkerpeksag** [comment]
I've changed the bugs.p.o link to use HTTPS at python.org.
