### ISSUE TITLE
fcntl module for windows platform

### ISSUE THREAD

**Issue by 163a8eef-9405-4fa2-84ed-55ec72debb17** [python/cpython#74229]
BPO | [30043](https://bugs.python.org/issue30043)
--- | :---
Nosy | @vstinner, @karan-logixal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-11.14:03:36.220>
created_at = <Date 2017-04-11.13:41:57.946>
labels = ['invalid', 'performance']
title = 'fcntl module for windows platform'
updated_at = <Date 2017-04-11.14:03:36.218>
user = 'https://github.com/karan-logixal'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-11.14:03:36.218>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-11.14:03:36.220>
closer = 'vstinner'
components = []
creation = <Date 2017-04-11.13:41:57.946>
creator = 'kk_pednekar'
dependencies = []
files = []
hgrepos = []
issue_num = 30043
keywords = []
message_count = 2.0
messages = ['291493', '291496']
nosy_count = 2.0
nosy_names = ['vstinner', 'kk_pednekar']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30043'
versions = []
```

</p></details>

**Comment by 163a8eef-9405-4fa2-84ed-55ec72debb17** [comment]
is there any fcntl module alternative available that would support windows platform??

in any of futures release of python is it possible that fcntl would support windows??

**Comment by vstinner** [comment]
The Python bug tracker is not a forum. Please ask such question on a Python help mailing list or any Python forum, but not here. Thank you ;-)

(No, there is no fcntl module on Windows.)
