### ISSUE TITLE
URL Quoting page links to function Bytes instead of defintion

### ISSUE THREAD

**Issue by csabella** [python/cpython#74238]
BPO | [30052](https://bugs.python.org/issue30052)
--- | :---
Nosy | @birkenfeld, @ncoghlan, @wimglenn, @Mariatta, @csabella
PRs | <li>python/cpython#1271</li><li>python/cpython#1339</li><li>python/cpython#1915</li><li>python/cpython#1921</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-06.02:20:48.154>
created_at = <Date 2017-04-12.12:49:34.666>
labels = ['type-bug', '3.7', 'docs']
title = 'URL Quoting page links to function Bytes instead of defintion'
updated_at = <Date 2019-06-21.21:27:29.843>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-21.21:27:29.843>
actor = 'cheryl.sabella'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-06.02:20:48.154>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-12.12:49:34.666>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30052
keywords = []
message_count = 17.0
messages = ['291546', '291575', '292215', '292301', '292428', '292440', '292484', '292520', '294982', '295015', '295019', '295020', '295229', '295230', '345881', '345882', '346253']
nosy_count = 6.0
nosy_names = ['georg.brandl', 'ncoghlan', 'docs@python', 'wim.glenn', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1271', '1339', '1915', '1921']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30052'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
On the URL Quoting page, the following line:

`string may be either a str or a bytes.`

Has the `str` link to:
https://docs.python.org/3/library/stdtypes.html#str

But the `bytes` link to:
https://docs.python.org/3/library/functions.html#bytes

Should the `bytes` link to?
https://docs.python.org/3/library/stdtypes.html#bytes

**Comment by csabella** [comment]
I've looked into this a little more and it seems that, in all instances, the :class:\`bytes\` and :class:\`bytearray\` mark-up link to the Built-In Functions page instead of the Built-In Types page.

It also looks like the Built-In Functions page has specific code for many types (dict, frozenset, memoryview, list, tuple, str, etc) so that it wouldn't link to this (the functions) page.  However, bytes and bytearray aren't part of that list.  I don't know if they were excluded on purpose or if their links should behave like the other types.

Please let me know if this should change.

**Comment by csabella** [comment]
Since no one has said that this change shouldn't be made, I'll start working on this.

**Comment by ncoghlan** [comment]
New changeset c6db4811f9ea3aeff0e1fafe1c60a22835ef359e by Nick Coghlan (csabella) in branch 'master':
bpo-30052: Link `bytes` & `bytearray` to stdtypes not functions  (GH-1271)
https://github.com/python/cpython/commit/c6db4811f9ea3aeff0e1fafe1c60a22835ef359e

**Comment by csabella** [comment]
FYI.

When I tested this change locally, I needed to do a 'make clean' then a 'make html' for all the pages to relink to the stdtypes page for :class:\`bytes\`.  I had asked on the IRC channel about that and thought maybe the merge into the master would do that automatically, but checking some of the links (like on the urllib.parse page), it didn't update them.

**Comment by ncoghlan** [comment]
Indeed, checking the dev build at https://docs.python.org/dev/library/urllib.parse.html#url-quoting shows it still linking to the old location.

Perhaps the `autobuild-dev-html` target in the Makefile should be adding `-E` and `-a` so it always regenerates everything, rather than re-using the potentially stale cached info from the previous day?

**Comment by csabella** [comment]
I don't think it would add a lot of time or processing to rebuild it daily, would it?  Seems safer than not doing it.

**Comment by ncoghlan** [comment]
New PR disabling the output caching and adding a corresponding NEWS entry: https://github.com/python/cpython/pull/1339

On my local machine, it takes a "nothing changed" build from less than 2 seconds to just under 2 minutes, but I think that's fine for a daily build task.

**Comment by Mariatta** [comment]
New changeset 1c92c0edca413c6f8ce8ec326a67451ae751ead9 by Mariatta in branch '3.6':
bpo-30052: Link `bytes` & `bytearray` to stdtypes not functions  (GH-1271) (GH-1915)
https://github.com/python/cpython/commit/1c92c0edca413c6f8ce8ec326a67451ae751ead9

**Comment by csabella** [comment]
Sorry, Mariatta.  I didn't realize this was waiting for a backport.

**Comment by ncoghlan** [comment]
New changeset 7a82f9c2b94d31c8f4cc8bb8e3151765d8b148d7 by Nick Coghlan in branch 'master':
bpo-30052: Always regenerate cross-references (bpo-1339)
https://github.com/python/cpython/commit/7a82f9c2b94d31c8f4cc8bb8e3151765d8b148d7

**Comment by ncoghlan** [comment]
Not your fault, Cheryl! I unfortunately got distracted and didn't follow up on the backports for several PRs I merged a while back. Mariatta has been graciously cleaning some of those up rather than leaving them lingering the way I had been :)

I also just noticed that I never merged the PR to always regenerate the cross-references, so I went ahead and did that, and also submitted the corresponding 3.6 backport PR.

**Comment by Mariatta** [comment]
New changeset 798cfb212383a6f5a31b610825d1af1d376804b2 by Mariatta (Nick Coghlan) in branch '3.6':
bpo-30052: Always regenerate cross-references (GH-1339) (GH-1921)
https://github.com/python/cpython/commit/798cfb212383a6f5a31b610825d1af1d376804b2

**Comment by Mariatta** [comment]
Backport PR looks good so I went ahead and merged it :)
Thanks.
