### ISSUE TITLE
Typos in Doc/library/select.rst

### ISSUE THREAD

**Issue by 5b68c441-639c-4083-a0a1-85f8c4fa2978** [python/cpython#74233]
BPO | [30047](https://bugs.python.org/issue30047)
--- | :---
Nosy | @serhiy-storchaka, @osamu0329nakamura, @Mariatta
PRs | <li>python/cpython#1086</li><li>python/cpython#1098</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-04-13.03:03:28.943>
created_at = <Date 2017-04-11.23:22:47.047>
labels = ['3.7', 'docs']
title = 'Typos in Doc/library/select.rst'
updated_at = <Date 2017-04-13.03:03:28.941>
user = 'https://github.com/osamu0329nakamura'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.03:03:28.941>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-04-13.03:03:28.943>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-11.23:22:47.047>
creator = 'OSAMU.NAKAMURA'
dependencies = []
files = []
hgrepos = []
issue_num = 30047
keywords = []
message_count = 5.0
messages = ['291520', '291543', '291569', '291584', '291585']
nosy_count = 4.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'OSAMU.NAKAMURA', 'Mariatta']
pr_nums = ['1086', '1098']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30047'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 5b68c441-639c-4083-a0a1-85f8c4fa2978** [comment]
In 18.3.2. Edge and Level Trigger Polling (epoll) Objects,
there is duplicated 'on' in description of `EPOLLEXCLUSIVE`.

   Wake only ... objects polling on on a fd.
                                 ^^^^^

**Comment by serhiy-storchaka** [comment]
New changeset 3e0f1fc4e0ffcfcc706015fa3d67c262948ef171 by Serhiy Storchaka (NAKAMURA Osamu) in branch 'master':
bpo-30047: Fix a typo in [Doc/library/select.rst](https://github.com/python/cpython/blob/main/Doc/library/select.rst) (bpo-1086)
https://github.com/python/cpython/commit/3e0f1fc4e0ffcfcc706015fa3d67c262948ef171

**Comment by Mariatta** [comment]
This needs backport, which I will do later today. Thanks.

**Comment by Mariatta** [comment]
New changeset f0c416799b33742af36d7c6608b9a422615fb3d2 by Mariatta in branch '3.6':
[3.6] bpo-30047: Fix a typo in [Doc/library/select.rst](https://github.com/python/cpython/blob/main/Doc/library/select.rst) (GH-1086) (GH-1098)
https://github.com/python/cpython/commit/f0c416799b33742af36d7c6608b9a422615fb3d2

**Comment by Mariatta** [comment]
Backported to 3.6.
Closing this now.
Thanks all :)
