### ISSUE TITLE
Bad parameter name in re.escape()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74231]
BPO | [30045](https://bugs.python.org/issue30045)
--- | :---
Nosy | @rhettinger, @ezio-melotti, @bitdancer, @serhiy-storchaka, @mandeep

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-13.07:44:50.858>
created_at = <Date 2017-04-11.20:28:24.514>
labels = ['expert-regex', 'type-feature', '3.7']
title = 'Bad parameter name in re.escape()'
updated_at = <Date 2017-04-13.07:44:50.857>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.07:44:50.857>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-13.07:44:50.858>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-11.20:28:24.514>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30045
keywords = []
message_count = 4.0
messages = ['291514', '291524', '291589', '291591']
nosy_count = 6.0
nosy_names = ['rhettinger', 'ezio.melotti', 'mrabarnett', 'r.david.murray', 'serhiy.storchaka', 'mandeepb']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30045'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Currently re.escape() parameter has a name "pattern", but in the documentation the name of the parameter is "string".

The name "pattern" is not correct, and maybe even misleading. The argument of escape() is not a pattern, it is an arbitrary string, and escape() makes a pattern from it by escaping special characters.

It is unlikely that the argument is passed to re.escape() by keyword. Therefore renaming it to "string" shouldn't break existing code.

**Comment by rhettinger** [comment]
"Pattern" seems right to me.

**Comment by aa752287-3877-4488-b28e-6a0aef4e10d3** [comment]
I agree that pattern seems right. However I think that the parameter in the docs should be changed from string to pattern for consistency purposes.

**Comment by serhiy-storchaka** [comment]
This looked not correct to me but if you say "pattern" seems right I'm closing this issue.

I'll update the parameter name in [PR 1048](https://github.com/python/cpython/pull/1048).
