### ISSUE TITLE
No documentation for C type Py_Ellipsis

### ISSUE THREAD

**Issue by 84dd73fe-9313-425f-aae0-390228a90839** [python/cpython#74245]
BPO | [30059](https://bugs.python.org/issue30059)
--- | :---
Nosy | @serhiy-storchaka, @Mariatta, @MSeifert04
PRs | <li>python/cpython#1018</li><li>python/cpython#1147</li><li>python/cpython#1148</li><li>python/cpython#1149</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-15.02:05:54.878>
created_at = <Date 2017-04-12.17:25:17.804>
labels = ['type-feature', '3.7', 'docs']
title = 'No documentation for C type Py_Ellipsis'
updated_at = <Date 2017-04-15.02:05:54.878>
user = 'https://github.com/MSeifert04'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-15.02:05:54.878>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-15.02:05:54.878>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-12.17:25:17.804>
creator = 'MSeifert'
dependencies = []
files = []
hgrepos = []
issue_num = 30059
keywords = []
message_count = 8.0
messages = ['291567', '291570', '291571', '291607', '291679', '291693', '291694', '291695']
nosy_count = 4.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'Mariatta', 'MSeifert']
pr_nums = ['1018', '1147', '1148', '1149']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30059'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
The "Py_Ellipsis" object is part of the public C-API but it isn't documented anywhere.

It is defined in "sliceobject.o/.h" so I created a PR and added it to the "slice" documentation.

**Comment by serhiy-storchaka** [comment]
I'm wondering if it is worth to add a separate section for Ellipsis at the same level as "Slice Objects", but in the same file. See for example "Instance Method Objects" and "Method Objects" in method.rst.

**Comment by 84dd73fe-9313-425f-aae0-390228a90839** [comment]
> I'm wondering if it is worth to add a separate section for Ellipsis at the same level as "Slice Objects", but in the same file.

I'm not sure either. 

There seems to be no precedent in the documentation, for example "Py_NotImplemented" is also just another (but mentioned first) point in the Object protocol [https://docs.python.org/3/c-api/object.html#object-protocol] and "Py_None" even has a complete page [https://docs.python.org/3/c-api/none.html].

**Comment by serhiy-storchaka** [comment]
There are precedences in tuple.rst and method.rst.

**Comment by serhiy-storchaka** [comment]
New changeset 0dc5c3169dcd4853612d11ed8c92b12fa210c07f by Serhiy Storchaka (Michael Seifert) in branch 'master':
bpo-30059: Include Py_Ellipsis in C API documentation (bpo-1018)
https://github.com/python/cpython/commit/0dc5c3169dcd4853612d11ed8c92b12fa210c07f

**Comment by Mariatta** [comment]
New changeset 05bfbcd233b2f5ba0d0634a380092d6ead6b35e1 by Mariatta (Michael Seifert) in branch '3.6':
[3.6] bpo-30059: Include Py_Ellipsis in C API documentation (GH-1018) (GH-1149)
https://github.com/python/cpython/commit/05bfbcd233b2f5ba0d0634a380092d6ead6b35e1

**Comment by Mariatta** [comment]
New changeset 0b46fcf45afe32402b34240770e01be9b5da3031 by Mariatta (Michael Seifert) in branch '2.7':
[2.7] bpo-30059: Include Py_Ellipsis in C API documentation (GH-1018) (GH-1147)
https://github.com/python/cpython/commit/0b46fcf45afe32402b34240770e01be9b5da3031

**Comment by Mariatta** [comment]
New changeset f40e72dbe60038eae69bc72e207ac47851d96752 by Mariatta (Michael Seifert) in branch '3.5':
[3.5] bpo-30059: Include Py_Ellipsis in C API documentation (GH-1018) (GH-1148)
https://github.com/python/cpython/commit/f40e72dbe60038eae69bc72e207ac47851d96752
