### ISSUE TITLE
signal.signal should check tripped signals

### ISSUE THREAD

**Issue by jdemeyer** [python/cpython#74243]
BPO | [30057](https://bugs.python.org/issue30057)
--- | :---
Nosy | @pitrou, @jdemeyer
PRs | <li>python/cpython#4258</li><li>python/cpython#4261</li><li>python/cpython#4263</li>
Files | <li>[fix30057-py2.patch](https://bugs.python.org/file46801/fix30057-py2.patch "Uploaded as text/plain at 2017-04-12.16:54:05 by @jdemeyer"): Patch for Python 2</li><li>[fix30057-py3.patch](https://bugs.python.org/file46802/fix30057-py3.patch "Uploaded as text/plain at 2017-04-12.16:54:17 by @jdemeyer"): Patch for Python 3</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-03.19:36:58.774>
created_at = <Date 2017-04-12.15:52:29.807>
labels = ['interpreter-core', '3.7']
title = 'signal.signal should check tripped signals'
updated_at = <Date 2017-11-03.19:36:58.773>
user = 'https://github.com/jdemeyer'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-03.19:36:58.773>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-03.19:36:58.774>
closer = 'pitrou'
components = ['Interpreter Core']
creation = <Date 2017-04-12.15:52:29.807>
creator = 'jdemeyer'
dependencies = []
files = ['46801', '46802']
hgrepos = []
issue_num = 30057
keywords = ['patch']
message_count = 5.0
messages = ['291561', '305494', '305497', '305499', '305501']
nosy_count = 2.0
nosy_names = ['pitrou', 'jdemeyer']
pr_nums = ['4258', '4261', '4263']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30057'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by jdemeyer** [comment]
There is a race condition in calling signal.signal() if the signal arrives while (or right before) signal.signal() is being executed: the function signal.signal(sig, action) marks the signal "sig" as not tripped. Because of this, signals can get lost. Instead, it would be better to call PyErr_CheckSignals() to check for pending signals.

**Comment by pitrou** [comment]
Thanks for the report! I will push your patch soon.

**Comment by pitrou** [comment]
New changeset f6f90ff079a22b79a58d47b6117cc8a8c7d366f3 by Antoine Pitrou in branch 'master':
bpo-30057: Fix potential missed signal in signal.signal(). (bpo-4258)
https://github.com/python/cpython/commit/f6f90ff079a22b79a58d47b6117cc8a8c7d366f3

**Comment by pitrou** [comment]
New changeset ea80ae04e2ec68c7e289048d3224a24b3c3fb107 by Antoine Pitrou (Miss Islington (bot)) in branch '3.6':
bpo-30057: Fix potential missed signal in signal.signal(). (GH-4258) (bpo-4261)
https://github.com/python/cpython/commit/ea80ae04e2ec68c7e289048d3224a24b3c3fb107

**Comment by pitrou** [comment]
New changeset c713837e91f39dc18740c74729cb7cebcf54fe6e by Antoine Pitrou in branch '2.7':
[2.7] bpo-30057: Fix potential missed signal in signal.signal(). (GH-4258) (bpo-4263)
https://github.com/python/cpython/commit/c713837e91f39dc18740c74729cb7cebcf54fe6e
