### ISSUE TITLE
RuntimeWarning: invalid value encountered in maximum/minimum

### ISSUE THREAD

**Issue by 2113fda4-5a2f-48b8-b4a4-b7b38abf379b** [python/cpython#74242]
BPO | [30056](https://bugs.python.org/issue30056)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-12.16:34:03.192>
created_at = <Date 2017-04-12.15:21:34.975>
labels = ['type-bug']
title = 'RuntimeWarning: invalid value encountered in maximum/minimum'
updated_at = <Date 2017-04-12.16:34:03.191>
user = 'https://bugs.python.org/aching'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-12.16:34:03.191>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-12.16:34:03.192>
closer = 'r.david.murray'
components = []
creation = <Date 2017-04-12.15:21:34.975>
creator = 'aching'
dependencies = []
files = []
hgrepos = []
issue_num = 30056
keywords = []
message_count = 2.0
messages = ['291560', '291562']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'aching']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30056'
versions = ['Python 3.5']
```

</p></details>

**Comment by 2113fda4-5a2f-48b8-b4a4-b7b38abf379b** [comment]
I just updated to numpy 1.12.1 and am getting this Runtime Warning when using numpy.minimum or numpy.maximum:

RuntimeWarning: invalid value encountered in maximum

Prior to updating, I was using numpy 1.10.x and had no issues running numpy.minimum or numpy.maximum

**Comment by bitdancer** [comment]
Numpy is not part of the python standard library.  You should report this issue to the numpy bug tracker, which appears to be here: https://github.com/numpy/numpy/issues.  Or perhaps first ask the numpy community if this is really a bug: the new version might have fixed a bug in minimum/maximum that is now detecting a problem with your code that wasn't detected previously.
