### ISSUE TITLE
Fix errors handling in the parser module

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74256]
BPO | [30070](https://bugs.python.org/issue30070)
--- | :---
Nosy | @rhettinger, @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#1131</li><li>python/cpython#1184</li><li>python/cpython#1185</li><li>python/cpython#1189</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-19.21:50:22.323>
created_at = <Date 2017-04-14.11:07:11.622>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'Fix errors handling in the parser module'
updated_at = <Date 2017-04-19.21:50:22.323>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-19.21:50:22.323>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-19.21:50:22.323>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-04-14.11:07:11.622>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30070
keywords = []
message_count = 6.0
messages = ['291645', '291855', '291890', '291899', '291903', '291910']
nosy_count = 3.0
nosy_names = ['rhettinger', 'benjamin.peterson', 'serhiy.storchaka']
pr_nums = ['1131', '1184', '1185', '1189']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30070'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch fixes miscellaneous errors in errors handling in the parser module. This errors can cause leaking references, raising wrong exceptions, and even crashing.

**Comment by rhettinger** [comment]
LGTM

**Comment by serhiy-storchaka** [comment]
New changeset a79f4c219531c05fc8f670c1e4bbf12c081935d3 by Serhiy Storchaka in branch 'master':
bpo-30070: Fixed leaks and crashes in errors handling in the parser module. (bpo-1131)
https://github.com/python/cpython/commit/a79f4c219531c05fc8f670c1e4bbf12c081935d3

**Comment by serhiy-storchaka** [comment]
New changeset 39dedb6e1a18069ce8f5c8e6076e9d9ef9d6d515 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30070: Fixed leaks and crashes in errors handling in the parser module. (GH-1131). (bpo-1184)
https://github.com/python/cpython/commit/39dedb6e1a18069ce8f5c8e6076e9d9ef9d6d515

**Comment by serhiy-storchaka** [comment]
New changeset 952a05e4e2cf082b74a1676a2804f1f43a9b7702 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30070: Fixed leaks and crashes in errors handling in the parser module. (GH-1131). (bpo-1185)
https://github.com/python/cpython/commit/952a05e4e2cf082b74a1676a2804f1f43a9b7702

**Comment by serhiy-storchaka** [comment]
New changeset 2a1bf0633cd0c55662df7875ee2b1654251adf6b by Serhiy Storchaka in branch '2.7':
[2.7] [3.5] bpo-30070: Fixed leaks and crashes in errors handling in the parser module. (GH-1131). (GH-1185) (bpo-1189)
https://github.com/python/cpython/commit/2a1bf0633cd0c55662df7875ee2b1654251adf6b
