### ISSUE TITLE
anaconda3::traitsu::NotImplementedError

### ISSUE THREAD

**Issue by fed8bf41-597f-4901-ba37-33be298fca6b** [python/cpython#74252]
BPO | [30066](https://bugs.python.org/issue30066)
--- | :---
Nosy | @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-13.13:38:25.682>
created_at = <Date 2017-04-13.13:09:16.819>
labels = ['type-bug', 'invalid']
title = 'anaconda3::traitsu::NotImplementedError'
updated_at = <Date 2017-04-13.13:38:25.680>
user = 'https://bugs.python.org/leopoldotosi'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-13.13:38:25.680>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-13.13:38:25.682>
closer = 'berker.peksag'
components = []
creation = <Date 2017-04-13.13:09:16.819>
creator = 'leopoldotosi'
dependencies = []
files = []
hgrepos = []
issue_num = 30066
keywords = []
message_count = 2.0
messages = ['291611', '291615']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'leopoldotosi']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30066'
versions = ['Python 3.6']
```

</p></details>

**Comment by fed8bf41-597f-4901-ba37-33be298fca6b** [comment]
the code below crash when run on anaconda3



```py
import traits.api as trapi
import traitsui.api as trui

from traits.api import HasTraits, Str, Range, Enum

class Person(HasTraits):
    name = Str('Jane Doe')
    age = Range(low=0)
    gender = Enum('female', 'male')

person = Person(age=30)

from traitsui.api import Item, RangeEditor, View

person_view = View(
    Item('name'),
    Item('gender'),
    Item('age', editor=RangeEditor(mode='spinner')),
    buttons=['OK', 'Cancel'],
    resizable=True,
)


person.configure_traits(view=person_view)
```

---------------------------------------------------------------------------
```pytb
NotImplementedError                       Traceback (most recent call last)
<ipython-input-18-3929f77bb9e4> in <module>()
----> 1 person.configure_traits(view=person_view)
```


/home/leopoldo/anaconda3/lib/python3.6/site-packages/traits/has_traits.py in configure_traits(self, filename, view, kind, edit, context, handler, id, scrollable, \*\*args)
   2169                 context = self
   2170             rc = toolkit().view_application( context, self.trait_view( view ),
-\> 2171                                            kind, handler, id, scrollable, args )
   2172             if rc and (filename is not None):
   2173                 fd = None

/home/leopoldo/anaconda3/lib/python3.6/site-packages/traitsui/toolkit.py in view_application(self, context, view, kind, handler, id, scrollable, args)
    289 
    290         """
--\> 291         raise NotImplementedError
    292 
    293     #\---------------------------------------------------------------------------

NotImplementedError:

**Comment by berkerpeksag** [comment]
Please report this to either traits or traitsui developers. This issue tracker is for issues with CPython and its standard library, not for third-party modules on PyPI.
