### ISSUE TITLE
Insufficient validation in _posixsubprocess.fork_exec()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74251]
BPO | [30065](https://bugs.python.org/issue30065)
--- | :---
Nosy | @gpshead, @serhiy-storchaka
PRs | <li>python/cpython#1110</li><li>python/cpython#1186</li><li>python/cpython#1190</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-19.21:52:48.822>
created_at = <Date 2017-04-13.10:14:01.054>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'Insufficient validation in _posixsubprocess.fork_exec()'
updated_at = <Date 2017-04-19.21:52:48.821>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-19.21:52:48.821>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-19.21:52:48.822>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-04-13.10:14:01.054>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30065
keywords = []
message_count = 6.0
messages = ['291595', '291626', '291627', '291891', '291904', '291911']
nosy_count = 2.0
nosy_names = ['gregory.p.smith', 'serhiy.storchaka']
pr_nums = ['1110', '1186', '1190']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30065'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
\_posixsubprocess.fork_exec() takes a sequence of file descriptors. It first validates it, and since the validation is passed uses it without checking for errors. But since \_\_len__, \_\_getitem__ and \_\_int__ can execute user code and release GIL, errors can occur after the validation. This can cause a crash.

Proposed patch fixes this by the simplest way -- it restricts the type of a sequence to tuple and types of elements to int. Since \_posixsubprocess is private module this shouldn't break third-party code.

Other issue with \_posixsubprocess.fork_exec() was that it converts args to a tuple or a list and iterate it without checking if the size is changed.

**Comment by gpshead** [comment]
nice find.  did anyone's code actually run into this issue?

**Comment by serhiy-storchaka** [comment]
It is hard to reproduce (especially the second issue) since in all cases in the stdlib a list passed to fork_exec() is just created by sorted() and doesn't have other references. But if someone is so insane that passes int-like objects with non-idempotent \_\_int__ as file descriptors his can get a crash in debug build (or mystical bugs in release build). Added tests utilizes this, but this unlikely happens in real code.

I have found this issue during analyzing usages of PyObject_Size(), PySequence_Size() and PyMapping_Size() in bpo-30061.

**Comment by serhiy-storchaka** [comment]
New changeset 66bffd1663489d080349debbf1b472d432351038 by Serhiy Storchaka in branch 'master':
bpo-30065: Fixed arguments validation in \_posixsubprocess.fork_exec(). (bpo-1110)
https://github.com/python/cpython/commit/66bffd1663489d080349debbf1b472d432351038

**Comment by serhiy-storchaka** [comment]
New changeset e2546172622dd52692cf0e26c2b931f942f345b6 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30065: Fixed arguments validation in \_posixsubprocess.fork_exec(). (GH-1110) (bpo-1186)
https://github.com/python/cpython/commit/e2546172622dd52692cf0e26c2b931f942f345b6

**Comment by serhiy-storchaka** [comment]
New changeset c97c1914f401359f2a7e6c8e0364e71ad9fb5bc8 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30065: Fixed arguments validation in \_posixsubprocess.fork_exec(). (GH-1110) (bpo-1190)
https://github.com/python/cpython/commit/c97c1914f401359f2a7e6c8e0364e71ad9fb5bc8
