### ISSUE TITLE
_osx_support.py: misplaced flags in re.sub()

### ISSUE THREAD

**Issue by ec31e85c-a35c-494f-805f-21a63c135c1b** [python/cpython#74253]
BPO | [30067](https://bugs.python.org/issue30067)
--- | :---
Nosy | @vstinner, @jwilk, @serhiy-storchaka, @JackMc, @zhangyangyu
PRs | <li>python/cpython#1134</li><li>python/cpython#1135</li><li>python/cpython#1136</li><li>python/cpython#1137</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-04-14.14:48:14.293>
created_at = <Date 2017-04-13.20:04:13.195>
labels = ['3.7', 'easy', 'type-bug', 'library']
title = '_osx_support.py: misplaced flags in re.sub()'
updated_at = <Date 2017-04-14.14:48:14.292>
user = 'https://github.com/jwilk'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-14.14:48:14.292>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-04-14.14:48:14.293>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-13.20:04:13.195>
creator = 'jwilk'
dependencies = []
files = []
hgrepos = []
issue_num = 30067
keywords = ['easy']
message_count = 5.0
messages = ['291631', '291651', '291652', '291654', '291656']
nosy_count = 5.0
nosy_names = ['vstinner', 'jwilk', 'serhiy.storchaka', 'Jack.McCracken', 'xiang.zhang']
pr_nums = ['1134', '1135', '1136', '1137']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30067'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ec31e85c-a35c-494f-805f-21a63c135c1b** [comment]
[Lib/_osx_support.py](https://github.com/python/cpython/blob/main/Lib/_osx_support.py) contains the following line:

```py
    flags = re.sub(r'-arch\s+\w+\s', ' ', flags, re.ASCII)
```


But the 4th re.sub() argument is the maximum number of substitutions, so this is equivalent to:

```py
    flags = re.sub(r'-arch\s+\w+\s', ' ', flags, count=256)
```


It was probably meant to be:

```py
    flags = re.sub(r'-arch\s+\w+\s', ' ', flags, flags=re.ASCII)
```



This bug was found using pydiatra:
http://jwilk.net/software/pydiatra

**Comment by vstinner** [comment]
I created the issue bpo-30072: "re functions: convert count and flags parameters to keyword-only?".

**Comment by 3edf0a29-a2aa-4bae-8291-3d814e2b76c1** [comment]
Resolved in GitHub https://github.com/python/cpython/pull/1134.

In 2.7, the flag re.ASCII is not passed due to 2.7's default ASCII strings.

Backporting to 3.5 and 3.6.

**Comment by 3edf0a29-a2aa-4bae-8291-3d814e2b76c1** [comment]
https://github.com/python/cpython/pull/1135 and https://github.com/python/cpython/pull/1137 backport it to 3.5 and 3.6, respectively.

**Comment by zhangyangyu** [comment]
My fault.
