### ISSUE TITLE
compile warnings of _PySlice_Unpack in 2.7

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74260]
BPO | [30074](https://bugs.python.org/issue30074)
--- | :---
Nosy | @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1154</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-15.17:12:20.516>
created_at = <Date 2017-04-15.07:46:43.635>
labels = []
title = 'compile warnings of _PySlice_Unpack in 2.7'
updated_at = <Date 2017-04-15.17:12:20.515>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-15.17:12:20.515>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-15.17:12:20.516>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-04-15.07:46:43.635>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30074
keywords = []
message_count = 3.0
messages = ['291708', '291722', '291723']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1154']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30074'
versions = ['Python 2.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
Compile 2.7 now get many warning about \_PySlice_Unpack, not in 3.x. See an example: http://buildbot.python.org/all/builders/x86%20Ubuntu%20Shared%202.7/builds/109/steps/compile/logs/warnings%20%2822%29.

**Comment by serhiy-storchaka** [comment]
New changeset 5e79321742cb3af2184d22e2148c6756cade1864 by Serhiy Storchaka in branch '2.7':
bpo-30074: Fix compile warnings of \_PySlice_Unpack and convert missed (bpo-1154)
https://github.com/python/cpython/commit/5e79321742cb3af2184d22e2148c6756cade1864

**Comment by serhiy-storchaka** [comment]
Thank you for pointing on this and for your review Xiang!
