### ISSUE TITLE
Support Apple AIFF-C pseudo compression in aifc.py

### ISSUE THREAD

**Issue by 7072b078-f107-44c7-92bb-fa3ce0c2a07c** [python/cpython#74263]
BPO | [30077](https://bugs.python.org/issue30077)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @ambv, @serhiy-storchaka, @zhangyangyu, @thruston, @dnknth
PRs | <li>python/cpython#1156</li><li>python/cpython#24449</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2021-08-13.11:33:51.235>
created_at = <Date 2017-04-15.18:44:39.148>
labels = ['OS-mac', 'type-feature', 'library', '3.11']
title = 'Support Apple AIFF-C pseudo compression in aifc.py'
updated_at = <Date 2021-08-13.20:44:39.965>
user = 'https://github.com/thruston'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-13.20:44:39.965>
actor = 'thruston'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2021-08-13.11:33:51.235>
closer = 'lukasz.langa'
components = ['Library (Lib)', 'macOS']
creation = <Date 2017-04-15.18:44:39.148>
creator = 'thruston'
dependencies = []
files = []
hgrepos = []
issue_num = 30077
keywords = ['patch']
message_count = 8.0
messages = ['291727', '291761', '291762', '291766', '386497', '399529', '399530', '399558']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'lukasz.langa', 'serhiy.storchaka', 'xiang.zhang', 'thruston', 'yussuf.ozkan']
pr_nums = ['1156', '24449']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30077'
versions = ['Python 3.11']
```

</p></details>

**Comment by 7072b078-f107-44c7-92bb-fa3ce0c2a07c** [comment]
aifc.py fails to open AIFF files containing the compression type "sowt" in the COMM chunk with an "unsupported compression type" error.

This compression type is an Apple specific extension that signals that the data is not actually compressed but is stored uncompressed in little Endian order.  

Supporting it would require a trivial change to allow the compression type as a byte-string and to add a do-nothing \_convert routine. 

This would allow aifc.py to be used with AIFF files on Apple macOS.

**Comment by zhangyangyu** [comment]
Anyway, such a function addition could only get into 3.7.

**Comment by serhiy-storchaka** [comment]
Seems the "sowt" compression is not just a no-op operation. Perhaps it should change a byte order.

Needed tests and test files for the new compression.

**Comment by 7072b078-f107-44c7-92bb-fa3ce0c2a07c** [comment]
I think it's probably better as a no-op.  Currently in my patch I just put 

```py
    return data
```


You could do

    return data[::-1]

to reverse the sample, so that it came out as big endian, but if you leave it as a no-op then the data is returned in the native format for Intel Mac OS, which is the whole point of the "sowt" encoding.  Either way, the user can easily reverse the data in a `unpack` format if they want to, but in my own testing it seemed easier and simpler just to leave it in the native format. Then basically "it just works".

The patch as I've proposed it works fine on my MacOS boxes, but I have only tested it with AIFF-C files from one source.
