### ISSUE TITLE
Inconsistent handling of failure of PyModule_AddObject

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74267]
BPO | [30081](https://bugs.python.org/issue30081)
--- | :---
Nosy | @serhiy-storchaka, @zhangyangyu
Superseder | <li>bpo-26871: Change weird behavior of PyModule_AddObject()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-16.16:44:28.085>
created_at = <Date 2017-04-16.16:22:37.863>
labels = ['type-bug']
title = 'Inconsistent handling of failure of PyModule_AddObject'
updated_at = <Date 2017-04-16.16:44:28.084>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-16.16:44:28.084>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-16.16:44:28.085>
closer = 'xiang.zhang'
components = []
creation = <Date 2017-04-16.16:22:37.863>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30081
keywords = []
message_count = 3.0
messages = ['291750', '291751', '291753']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'xiang.zhang']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '26871'
type = 'behavior'
url = 'https://bugs.python.org/issue30081'
versions = []
```

</p></details>

**Comment by zhangyangyu** [comment]
The doc of PyModule_AddObject()[1] states it steals a reference to \*value*. But this is only the case when it succeed. On failure the reference is not stolen.

The usages of it across the code base are inconsistent. Some realizes this situation and depends on it: [2]. Some doesn't realize: [3]. Most just assume it always succeeds: [4].

BTW, it seems many modules doesn't release memories well in failure situations in their PyMOD_INIT. Maybe I miss some post-handling procedures?

[1] https://docs.python.org/3/c-api/module.html#c.PyModule_AddObject
[2] https://github.com/python/cpython/blob/master/Python/modsupport.c#L644
[3] https://github.com/python/cpython/blob/master/Modules/gcmodule.c#L1590
[4] https://github.com/python/cpython/blob/master/Modules/_datetimemodule.c#L5799

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-26868 and bpo-26871. There is also a thread on Python-Dev.

**Comment by zhangyangyu** [comment]
Ohh, I am not alone. :-)
