### ISSUE TITLE
Asyncio: GeneratorExit + strange exception

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#74269]
BPO | [30083](https://bugs.python.org/issue30083)
--- | :---
Nosy | @gsalgado, @socketpair, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-16.18:18:42.735>
labels = ['expert-asyncio']
title = 'Asyncio: GeneratorExit + strange exception'
updated_at = <Date 2020-09-18.10:56:44.670>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-18.10:56:44.670>
actor = 'salgado'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-04-16.18:18:42.735>
creator = 'socketpair'
dependencies = []
files = []
hgrepos = []
issue_num = 30083
keywords = []
message_count = 2.0
messages = ['291763', '377104']
nosy_count = 3.0
nosy_names = ['salgado', 'socketpair', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue30083'
versions = ['Python 3.5']
```

</p></details>

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
How to reproduce: Run the following program:
\=========================
```py
import asyncio
async def handle_connection(reader, writer):
    try:
        await reader.readexactly(42)
    except BaseException as err:
        print('Interesting: %r.' % err)
        raise
    finally:
        writer.close()

loop = asyncio.get_event_loop()
coro = asyncio.start_server(handle_connection, '127.0.0.1', 8888)
server = loop.run_until_complete(coro)
try:
    loop.run_forever()
except KeyboardInterrupt:
    print('KeyboardInterrupt catched.')
server.close()
loop.run_until_complete(server.wait_closed())
loop.close()
```

=========================

0. Python 3.5.2
1. Connect using telnet to localhost and port 888, type one short line and press Enter.
2. Type Ctrl+C in terminal where programw is running.
3. You will see the following output:

\=========================
```pytb
^CKeyboardInterrupt catched.
Interesting: GeneratorExit().
Exception ignored in: <coroutine object handle_connection at 0x7fa6a1d91b48>
Traceback (most recent call last):
  File "bug.py", line 12, in handle_connection
    writer.close()
  File "/usr/lib/python3.5/asyncio/streams.py", line 306, in close
    return self._transport.close()
  File "/usr/lib/python3.5/asyncio/selector_events.py", line 591, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 567, in call_soon
    handle = self._call_soon(callback, args)
  File "/usr/lib/python3.5/asyncio/base_events.py", line 576, in _call_soon
    self._check_closed()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 356, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Task was destroyed but it is pending!
task: <Task pending coro=<handle_connection() done, defined at bug.py:4> wait_for=<Future pending cb=[Task._wakeup()]>>
```

=========================

This is almost canonical example of asyncio usage. So I have two questions:

1. Why coroutine is interrupted with GeneratorExit instead of CancelledError ?
2. Why something happend AFTER io loop is closed ?
3. How to code all that right ? I want to close connection on any error. Example provided is simplified code. In real code it looks like:

\=====
        try:
            await asyncio.wait_for(self._handle_connection(reader, writer), 60)
        except asyncio.TimeoutError:
            writer.transport.abort()
        except asyncio.CancelledError:
            writer.transport.abort()
        except Exception:
            writer.transport.abort()
        finally:
            writer.close()
\=====

**Comment by Dreamsorcerer** [comment]
The original example doesn't cause any errors for me, even on Python 3.8. But, we see a lot of these errors in aiohttp's test suite and have struggled to track them down:
https://github.com/aio-libs/aiohttp/issues/7196

**Comment by gvanrossum** [comment]
@Dreamsorcerer If you have a new issue, please file a new bug.
