### ISSUE TITLE
Failed to build these modules: _ctypes

### ISSUE THREAD

**Issue by 1220ddd9-1292-49f3-b2d8-3f0384085267** [python/cpython#74276]
BPO | [30090](https://bugs.python.org/issue30090)
--- | :---
Nosy | @mlouielu, @eamanu, @shihai1991

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-17.17:55:43.727>
created_at = <Date 2017-04-17.16:27:57.666>
labels = ['invalid', 'build', '3.7']
title = 'Failed to build these modules: _ctypes'
updated_at = <Date 2019-07-05.18:14:07.856>
user = 'https://github.com/eamanu'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-05.18:14:07.856>
actor = 'shihai1991'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-17.17:55:43.727>
closer = 'eric.smith'
components = ['Build']
creation = <Date 2017-04-17.16:27:57.666>
creator = 'eamanu'
dependencies = []
files = []
hgrepos = []
issue_num = 30090
keywords = []
message_count = 4.0
messages = ['291800', '291803', '291807', '347365']
nosy_count = 3.0
nosy_names = ['louielu', 'eamanu', 'shihai1991']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30090'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1220ddd9-1292-49f3-b2d8-3f0384085267** [comment]
Hello everybody, 

I am working with the code.

I clone the repo, and make a pull upstream of github's cpython repository (master branch), and when I make:

    ./configure --with-pydebug && make -j

build correctly but finished with this message:

    Failed to build these modules:
    _ctypes   

But the Test Result is: SUCCESS

Regards

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Are you using Ubuntu or other Linux distribution? This problem is because you didn't install the dependency package.

You may first try to use the instruction at [devguide](https://devguide.python.org):
http://cpython-devguide.readthedocs.io/setup.html#build-dependencies

Or, assume you have install build-essential and python3-dev ...etc., maybe you lost to install libffi-dev, just simply `apt-get install libffi-dev` and rebuild to solve this problem.

**Comment by 1220ddd9-1292-49f3-b2d8-3f0384085267** [comment]
The problem was solution making:

    apt-get install libffi-dev

Thanks
