### ISSUE TITLE
starred tuple expression vs list display and function call

### ISSUE THREAD

**Issue by d5c4a6d8-d068-44fe-b971-ca1eeb68736d** [python/cpython#74270]
BPO | [30084](https://bugs.python.org/issue30084)
--- | :---
Nosy | @ezio-melotti, @stevendaprano, @vadmium
Files | <li>[x.py](https://bugs.python.org/file46807/x.py "Uploaded as text/plain at 2017-04-16.22:39:03 by umedoblock"): simple four lines.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-17.01:12:49.391>
created_at = <Date 2017-04-16.22:39:03.635>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'starred tuple expression vs list display and function call'
updated_at = <Date 2017-04-17.04:39:31.423>
user = 'https://bugs.python.org/umedoblock'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-17.04:39:31.423>
actor = 'umedoblock'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-17.01:12:49.391>
closer = 'steven.daprano'
components = ['Interpreter Core']
creation = <Date 2017-04-16.22:39:03.635>
creator = 'umedoblock'
dependencies = []
files = ['46807']
hgrepos = []
issue_num = 30084
keywords = []
message_count = 4.0
messages = ['291769', '291770', '291772', '291779']
nosy_count = 5.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'steven.daprano', 'umedoblock', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30084'
versions = ['Python 3.5']
```

</p></details>

**Comment by d5c4a6d8-d068-44fe-b971-ca1eeb68736d** [comment]
Hi, all.

First of all, my python environment is below.

Python 3.5.2+ (default, Sep 22 2016, 12:18:14) 
[GCC 6.2.0 20160927] on linux

= differ evaluation order about starred expression
I get below result then I run x.py
\======================================================
  File "/home/umedoblock/x.py", line 4
    (*(1, 2))
    ^
SyntaxError: can't use starred expression here
\======================================================

Next, I comment out line 4 and run Python3.
I got below result.
And I feel strange behavior above result.
Because I think that Python should return same result above and below. 
\======================================================
```pytb
Traceback (most recent call last):
  File "/home/umedoblock/x.py", line 1, in <module>
    list(*(1, 2))
TypeError: list() takes at most 1 argument (2 given)
```

======================================================

```pycon
= pass or not about starred expression.
list expression pass starred expression, the other hand
tuple expression cannot pass starred expression.
I hope to pass starred expression about list and tuple.
>>> [*(1, 2)]
[1, 2]
>>> (*(1, 2))
  File "<stdin>", line 1
SyntaxError: can't use starred expression here
```

**Comment by vadmium** [comment]
This doesn’t seem like a bug to me. At least it is consistent with the rule for making a tuple when there are commas versus returning the direct expression when there are no commas:

```pycon
>>> x = (1); type(x)
<class 'int'>
>>> x = (1,); type(x)
<class 'tuple'>
```


I don’t think it is worth changing the syntax again just to pack a single starred expression into a tuple without a comma. If you really want to do that, it would be clearer to write

```py
expression = (1, 2)
tuple_1 = (*expression,)  # Brackets and comma suggest a tuple
tuple_2 = tuple(expression)  # Tuple constructor even more obvious
```


Allowing tuple packing without a comma would add a new inconsistency with function calls. It would conflict with your list(*(1, 2)) case:

```py
list(*(1, 2))  # Currently equivalent to list(1, 2)
list( (*(1, 2)) )  # Would be equivalent to list( (1, 2) )
```


The root problem IMO is that round brackets and commas have too many inconsistent special cases in Python (simple expressions vs tuples, tuples with zero, one or more items, function calls and signatures, generator expressions, unpacking assignments, etc). But it may be too hard to change any of this.

**Comment by stevendaprano** [comment]
> list expression pass starred expression, the other hand
> tuple expression cannot pass starred expression.

You are misinterpreting what you are seeing.

( ) is not a tuple expression (except for the special case of empty brackets, which makes an empty tuple). It's just grouping an expression. So (*x) is equivalent to just bare \*x.

To make a tuple, you need a comma.

Apart from the empty tuple, the brackets are just for grouping. Put a comma after the starred expression and it will work:

py\> t = 1, 2
py\> t
(1, 2)
py\> (*t,)
(1, 2)


The trailing comma is allowed in lists as well:

py\> [*t,]
[1, 2]


I agree with Martin: there's no bug here, the behaviour is consistent with the way tuples and lists are normally created, and there's no need to make (*t) yet another special case.

If you really want to argue in favour of this change, I suggest you discuss it on the Python-Ideas mailing list and see if you can get community consensus for it. \*If* you get agreement that this is a good idea, then you can re-open this.

**Comment by d5c4a6d8-d068-44fe-b971-ca1eeb68736d** [comment]
Sorry and thanks to Martin and Steven.
I agree with your post about first my post.
I understand "(*x) is equivalent to just bare \*x."
