### ISSUE TITLE
Unicode eq operation with hash.

### ISSUE THREAD

**Issue by corona10** [python/cpython#74279]
BPO | [30093](https://bugs.python.org/issue30093)
--- | :---
Nosy | @vstinner, @ezio-melotti, @corona10

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-18.13:19:44.270>
created_at = <Date 2017-04-18.13:11:45.459>
labels = ['3.7', 'expert-unicode', 'performance']
title = 'Unicode eq operation with hash.'
updated_at = <Date 2017-04-18.13:19:44.269>
user = 'https://github.com/corona10'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-18.13:19:44.269>
actor = 'corona10'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-18.13:19:44.270>
closer = 'corona10'
components = ['Unicode']
creation = <Date 2017-04-18.13:11:45.459>
creator = 'corona10'
dependencies = []
files = []
hgrepos = []
issue_num = 30093
keywords = []
message_count = 3.0
messages = ['291833', '291834', '291835']
nosy_count = 3.0
nosy_names = ['vstinner', 'ezio.melotti', 'corona10']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30093'
versions = ['Python 3.7']
```

</p></details>

**Comment by corona10** [comment]
If the Unicode compare operation is done by comparing the hashes, it is likely to be efficient because memory comparison is not necessary.

If this idea is approved I could upload my PR right now. :-)
(I already checked local unit test is passed.)

**Comment by vstinner** [comment]
My previous attempt which ended with "Raymond Hettinger: I don't think it is worth it."
http://bugs.python.org/issue16286#msg216654

Most string comparisons are comparisons of strings of less than 20 characters.

**Comment by corona10** [comment]
Thanks for the reply.

I did not know it was already discussed.
The conclusion of the thread looks reasonable.
