### ISSUE TITLE
DeprecationWarning: invalid escape sequence: Only appears on first run

### ISSUE THREAD

**Issue by d623c433-3e67-4a0a-abb9-feaa556f8894** [python/cpython#74277]
BPO | [30091](https://bugs.python.org/issue30091)
--- | :---
Nosy | @serhiy-storchaka, @jdufresne

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-17.21:47:35.771>
created_at = <Date 2017-04-17.17:19:05.700>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'DeprecationWarning: invalid escape sequence: Only appears on first run'
updated_at = <Date 2017-04-17.21:47:35.770>
user = 'https://github.com/jdufresne'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-17.21:47:35.770>
actor = 'jdufresne'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-17.21:47:35.771>
closer = 'jdufresne'
components = ['Interpreter Core']
creation = <Date 2017-04-17.17:19:05.700>
creator = 'jdufresne'
dependencies = []
files = []
hgrepos = []
issue_num = 30091
keywords = []
message_count = 5.0
messages = ['291805', '291806', '291809', '291812', '291813']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'jdufresne']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30091'
versions = ['Python 3.6']
```

</p></details>

**Comment by d623c433-3e67-4a0a-abb9-feaa556f8894** [comment]
After upgrading to Python 3.6, I'm working towards cleaning up "DeprecationWarning: invalid escape sequence". I've noticed that the Deprecation warning only appears on the first run. It looks like once the code is compiled to `__pycache__`, the deprecation warning does not show. This makes debugging more difficult as I need clean out `__pycache__` directories for the runs to be reproducible.

Example script:

foo.py
```
import bar
```

bar.py
```
s = '\.'
```

First run
```
$ python36 -Wall foo.py 
.../test/bar.py:1: DeprecationWarning: invalid escape sequence \.
  s = '\.'
```

Second run (no DeprecationWarning)
```
$ python36 -Wall foo.py
```

Third run after cleaning
```
$ rm -rf __pycache__
$ python36 -Wall foo.py 
.../test/bar.py:1: DeprecationWarning: invalid escape sequence \.
  s = '\.'
```

I expect the deprecation warning to output on every run.

**Comment by serhiy-storchaka** [comment]
This warning is emitted by the compiler when it compiles string literals with invalid escape sequences. Once the source is compiled to the bytecode and saved to the .pyc file the compiler no longer involved. You can disable writing compiled bytecode by calling python with option -B.

**Comment by d623c433-3e67-4a0a-abb9-feaa556f8894** [comment]
I see.

I think if the goal is for developers to see and fix these DeprecationWarnings, it would help if the warnings were reproducible without taking steps different from normal Python development. TBH, this is the first time I've ever used the -B CLI argument.

For an example of where developers saw different sets of warnings which lead to confusion, see https://github.com/dateutil/dateutil/pull/358.

**Comment by serhiy-storchaka** [comment]
This is how Python works. This can't be changed without changing the compiler, the format of .pyc files (for saving warnings) and importing system. And this may slow down normal compilation due to generating warnings for saving them in .pyc files. I don't think this is worth.

**Comment by d623c433-3e67-4a0a-abb9-feaa556f8894** [comment]
Understood. Thanks for the response. I'll have to keep this in mind as I debug these warnings in the future.
