### ISSUE TITLE
Discourage operator.__dunder__ functions

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#74271]
BPO | [30085](https://bugs.python.org/issue30085)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ncoghlan, @stevendaprano, @SanketDG
PRs | <li>python/cpython#1171</li><li>python/cpython#3736</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-09-24.18:30:04.724>
created_at = <Date 2017-04-17.02:27:09.573>
labels = ['type-feature', '3.7', 'docs']
title = 'Discourage operator.__dunder__ functions'
updated_at = <Date 2017-09-24.21:13:17.867>
user = 'https://github.com/stevendaprano'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-24.21:13:17.867>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-09-24.18:30:04.724>
closer = 'terry.reedy'
components = ['Documentation']
creation = <Date 2017-04-17.02:27:09.573>
creator = 'steven.daprano'
dependencies = []
files = []
hgrepos = []
issue_num = 30085
keywords = []
message_count = 7.0
messages = ['291774', '291991', '291993', '292062', '302220', '302878', '302886']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'ncoghlan', 'steven.daprano', 'docs@python', 'sanketdg']
pr_nums = ['1171', '3736']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30085'
versions = ['Python 3.7']
```

</p></details>

**Comment by stevendaprano** [comment]
As discussed on the Python-Ideas mailing list, it is time to discourage the use of operator.\_\_dunder__ functions. Not to remove them or deprecate them, just change the documentation to make it clear that the dunderless versions are preferred.

Guido +1'ed this suggestion, and there were no objections:

https://mail.python.org/pipermail/python-ideas/2017-April/045424.html

**Comment by terryjreedy** [comment]
My suggestion from the python-ideas thread:: replace the current

"The function names are those used for special class methods; variants without leading and trailing __ are also provided for convenience."

with

""Many function names are those used for special methods, minus the double underscores.  For backward compatibility, many of these have a variant with the double underscores kept.  We recommend using the dunderless form.  Note that operator.\_\_add__(x, y), for instance, being the same as x + y, is not the same as x.\_\_add__(y)."

Possibly add ", since the first two may result in calling y.\_\_radd__(x)".



Raymond assigned the

**Comment by terryjreedy** [comment]
Raymond assigned the PR to himself, so I added him here as nosy and assignee.

**Comment by 8af688e8-3695-49be-8c1b-2072d278400e** [comment]
@terry, I have updated the same, thanks!

**Comment by terryjreedy** [comment]
Raymond, may someone else merge this?  I will add a blurb.

**Comment by terryjreedy** [comment]
New changeset 5b9299d8c72aeadccadd77e4b8132094ba9a1f96 by Terry Jan Reedy (Sanket Dasgupta) in branch 'master':
bpo-30085: Improve documentation for operator (bpo-1171)
https://github.com/python/cpython/commit/5b9299d8c72aeadccadd77e4b8132094ba9a1f96

**Comment by terryjreedy** [comment]
New changeset d38caf68bb417232fb0ccecb5558d7d0ca4a9507 by Terry Jan Reedy (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-30085: Improve documentation for operator (GH-1171) (bpo-3736)
https://github.com/python/cpython/commit/d38caf68bb417232fb0ccecb5558d7d0ca4a9507
