### ISSUE TITLE
Replace sys.version to sys.version_info in sysconfig.py

### ISSUE THREAD

**Issue by corona10** [python/cpython#74278]
BPO | [30092](https://bugs.python.org/issue30092)
--- | :---
Nosy | @serhiy-storchaka, @corona10
PRs | <li>python/cpython#1165</li>
Superseder | <li>bpo-24916: In sysconfig, don&#x27;t rely on sys.version format</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-18.07:22:14.468>
created_at = <Date 2017-04-18.07:01:18.382>
labels = ['3.7', 'library']
title = 'Replace sys.version to sys.version_info in sysconfig.py'
updated_at = <Date 2017-04-18.07:22:14.466>
user = 'https://github.com/corona10'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-18.07:22:14.466>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-18.07:22:14.468>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-18.07:01:18.382>
creator = 'corona10'
dependencies = []
files = []
hgrepos = []
issue_num = 30092
keywords = []
message_count = 2.0
messages = ['291824', '291827']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'corona10']
pr_nums = ['1165']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '24916'
type = None
url = 'https://bugs.python.org/issue30092'
versions = ['Python 3.7']
```

</p></details>

**Comment by corona10** [comment]
Not to rely on sys.version here, its format is an implementation detail
of CPython, use sys.version_info or sys.hexversion

**Comment by serhiy-storchaka** [comment]
The patch contains too much unrelated changes.

As for changing the definition of sysconfig.get_config_vars('py_version') I'm not sure it is worth to do bacause this loss an information. This is a duplicate bpo-24916.
