### ISSUE TITLE
type() and len() recognize "abc", expression as "abc" string.

### ISSUE THREAD

**Issue by d5c4a6d8-d068-44fe-b971-ca1eeb68736d** [python/cpython#74272]
BPO | [30086](https://bugs.python.org/issue30086)
--- | :---
Nosy | @rhettinger, @ezio-melotti

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-17.04:55:21.634>
created_at = <Date 2017-04-17.04:43:18.244>
labels = ['expert-regex', 'type-bug', 'invalid']
title = 'type() and len() recognize "abc", expression as "abc" string.'
updated_at = <Date 2017-04-17.04:55:21.632>
user = 'https://bugs.python.org/umedoblock'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-17.04:55:21.632>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-17.04:55:21.634>
closer = 'rhettinger'
components = ['Regular Expressions']
creation = <Date 2017-04-17.04:43:18.244>
creator = 'umedoblock'
dependencies = []
files = []
hgrepos = []
issue_num = 30086
keywords = []
message_count = 2.0
messages = ['291781', '291782']
nosy_count = 4.0
nosy_names = ['rhettinger', 'ezio.melotti', 'mrabarnett', 'umedoblock']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30086'
versions = ['Python 3.5']
```

</p></details>

**Comment by d5c4a6d8-d068-44fe-b971-ca1eeb68736d** [comment]
But I found a real bug to use a tuple with a comma.

Python3 recognized "abc", expression as tuple of one element.
But type() and len() recognize "abc", expression as "abc" string.
So now, I found a real bug.

I'll show you below sentences.

```pycon
>>> "abc",
('abc',)
>>> obj = "abc",
>>> obj
('abc',)
>>> type(obj)
<class 'tuple'>
>>> len(("abc",))
1
>>> len(obj)
1

>>> type("abc",)
<class 'str'>
>>> len("abc",)
3
```

**Comment by rhettinger** [comment]
What you're seeing is a feature of the grammar.

Function allow an optional trailing comma in the argument list:

```pycon
    >>> pow(2, 5)
    32
    >>> pow(2, 5,)
    32
```


So, to create a tuple inside in an argument list, you need the extra layer of parentheses.

Sorry, this isn't a real bug.  It is just a conflict resolution between use of a comma to separate arguments in a function call and use of a comma to create a tuple.
