### ISSUE TITLE
Update examples in abc documentation to use abc.ABC

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#74282]
BPO | [30096](https://bugs.python.org/issue30096)
--- | :---
Nosy | @brettcannon, @rhettinger, @merwok, @vedgar, @Mariatta, @appeltel
PRs | <li>python/cpython#1220</li><li>python/cpython#3408</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-07.18:34:09.129>
created_at = <Date 2017-04-18.19:51:38.503>
labels = ['type-feature', '3.7', 'docs']
title = 'Update examples in abc documentation to use abc.ABC'
updated_at = <Date 2017-09-15.18:15:39.977>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.18:15:39.977>
actor = 'eric.araujo'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-07.18:34:09.129>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-18.19:51:38.503>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 30096
keywords = []
message_count = 11.0
messages = ['291842', '291843', '291999', '301038', '301039', '301568', '301605', '301606', '302197', '302233', '302284']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'rhettinger', 'eric.araujo', 'docs@python', 'veky', 'Mariatta', 'Eric Appelt']
pr_nums = ['1220', '3408']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30096'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by brettcannon** [comment]
I noticed that the documentation for the abc module (https://docs.python.org/3/library/abc.html) has all example classes use ABCMeta instead of ABC which is what most people probably want. To keep things simple the docs should probably be updated to inherit from abc.ABC.

**Comment by rhettinger** [comment]
+1 It would be nice to have the examples show the usual best practices.

That said, in the doc for abc.ABC itself, it would be nice to show an brief example both ways (much like we do for the property() docstring) to show the relationship between the two.  In other words, I want people to inherit from ABC but don't want the knowledge of ABCMeta to be lost.

**Comment by 47afc646-a8b0-4fd5-95c1-f9f9183ec3e3** [comment]
I created a PR to update the documentation to use this pattern and follow Raymond's suggestion of showing both ways to define an abc.

In order to make the examples comprehensible when read from beginning to end, I reordered the classes so that abc.ABC is described first.

**Comment by merwok** [comment]
New changeset 122e88a8354e3f75aeaf6211232dac88ac296d54 by Éric Araujo (Eric Appelt) in branch 'master':
bpo-30096: Use ABC in abc reference examples (bpo-1220)
https://github.com/python/cpython/commit/122e88a8354e3f75aeaf6211232dac88ac296d54

**Comment by merwok** [comment]
Thanks for the patch!  Raymond approved it and I merged it after a minor change.  Now let me read the doc again about backports :)

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
"Best practices" according to whom?

Inheritance is one thing, metaclass changing is another thing. They should look different. Yes, I appreciate the fact that I can write "(Blah)" instead of "(metaclass=BlahMeta)" in quick and dirty scripts, but my feeling is that that practice shouldn't be promoted in the docs.

Please read http://bugs.python.org/issue26988#msg273076 for another perspective.

**Comment by Mariatta** [comment]
New changeset b0d0217c0e4c1512a06ef306928b2fd8f82d046e by Mariatta (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-30096: Use ABC in abc reference examples (GH-1220) (GH-3408)
https://github.com/python/cpython/commit/b0d0217c0e4c1512a06ef306928b2fd8f82d046e

**Comment by Mariatta** [comment]
Backported to 3.6 by Miss Islington.
Closing this issue.
Thanks.

**Comment by merwok** [comment]
> "Best practices" according to whom?

Well at least two senior core developers :)  See the rationale in bpo-16049 when abc.ABC was first added (with Guido approving that inheritance is nicer for most people).

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
Well, actually, Raymond was proposing an alternative to Py2's special \_\_metaclass__ attribute assignment syntax, which honestly \_is_ an abomination (and the big part of reason why that was changed in Py3 to a keyword argument in a class definition).

And Guido missed the point that in frameworks such as Django, the inheritance is the main thing people want, metaclasses just being a technical implementation detail (the easiest proof is that with modern descriptors with \_\_set_name__ and ordered class namespaces, it's unnecessary to use metaclasses in Django model implementation at all). Here it is exactly the opposite.

As I said in the linked comment, I think we missed the opportunity to make Python much more powerful, practically shunning the idea of keyword arguments in a class definition totally. But as it is said, Guido's will  be done. :-) Thanks for the link.

**Comment by merwok** [comment]
Keyword arguments in a class definition are supported: https://www.python.org/dev/peps/pep-3115/#specification

Anyway, this ticket is closed, a mailing list such as python-ideas would be a better venue to discuss base classes vs metaclasses in a general way.
