### ISSUE TITLE
PDB enhancement

### ISSUE THREAD

**Issue by d9630c1a-54c2-4e7a-8932-542a13bc8320** [python/cpython#74280]
BPO | [30094](https://bugs.python.org/issue30094)
--- | :---
Nosy | @rhettinger, @skirpichev, @DimitrisJim
Files | <li>[zdebug.py](https://bugs.python.org/file46810/zdebug.py "Uploaded as text/plain at 2017-04-18.18:32:35 by erixoltan"): Patched modification of pdb.py that introduces a new ppp command</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-04-18.18:32:36.145>
labels = ['3.7', 'type-feature', 'library']
title = 'PDB enhancement'
updated_at = <Date 2021-04-23.08:41:30.117>
user = 'https://bugs.python.org/erixoltan'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-23.08:41:30.117>
actor = 'Sergey.Kirpichev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-04-18.18:32:36.145>
creator = 'erixoltan'
dependencies = []
files = ['46810']
hgrepos = []
issue_num = 30094
keywords = []
message_count = 2.0
messages = ['291839', '291840']
nosy_count = 4.0
nosy_names = ['rhettinger', 'Sergey.Kirpichev', 'Jim Fasarakis-Hilliard', 'erixoltan']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30094'
versions = ['Python 3.7']
```

</p></details>

**Comment by d9630c1a-54c2-4e7a-8932-542a13bc8320** [comment]
I have created a pdb enhancement that allows me to query an object's internals more gracefully. It is incredibly useful and it would be very easy to include this logic in the distribution version of pdb. 

I created my own modification of pdb called zdebug (attached as zdebug.py) that implements a new ppp debugging command. This command prints a formatted output of an object's internals. It could be smoother, and doesn't fully obey the programming conventions used with in pdb, and I'm not proposing to submit it as a patch. However the ppp command is pretty simple and incredibly useful.  

Here's a tiny example. I can drill into an object, see its internals, and interactively explore its property chain. (The zdebug.zbreak() call is equivalent to pdb.set_trace()). 

```pycon
$ python3
>>> from datetime import date
>>> today = date.today()
>>> import zdebug
>>> zdebug.zbreak()
--Return--
> <stdin>(1)<module>()->None
zdebug> p today
datetime.date(2017, 4, 18)
zdebug> ppp today
   ctime = <built-in method ctime of datetime.date object at 0x7fc688a1cf50>
   day = 18
   fromordinal = <built-in method fromordinal of type object at 0x562b84a60d60>
   fromtimestamp = <built-in method fromtimestamp of type object at 0x562b84a60d60>
   isocalendar = <built-in method isocalendar of datetime.date object at 0x7fc688a1cf50>
   isoformat = <built-in method isoformat of datetime.date object at 0x7fc688a1cf50>
   isoweekday = <built-in method isoweekday of datetime.date object at 0x7fc688a1cf50>
   max = 9999-12-31
   min = 0001-01-01
   month = 4
   replace = <built-in method replace of datetime.date object at 0x7fc688a1cf50>
   resolution = 1 day, 0:00:00
   strftime = <built-in method strftime of datetime.date object at 0x7fc688a1cf50>
   timetuple = <built-in method timetuple of datetime.date object at 0x7fc688a1cf50>
   today = <built-in method today of type object at 0x562b84a60d60>
   toordinal = <built-in method toordinal of datetime.date object at 0x7fc688a1cf50>
   weekday = <built-in method weekday of datetime.date object at 0x7fc688a1cf50>
   year = 2017
```


zdebug\> p today.day
18
zdebug\> p today.year
2017

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Dunno, if I wanted to see a nice formatted output of the internals I'd run `pp vars(obj)`. 

That, though, suffers a bit from the fact that `vars` is not the most known of the builtins.

**Comment by iritkatriel** [comment]
@erixoltan - you'd have a better chance of having a contribution reviewed if it was in the form of a GitHub against the current development branch.

I agree with @DimitrisJim that there are non-invasive ways to do this in pdb.
