### ISSUE TITLE
Add support for ncurses A_ITALIC

### ISSUE THREAD

**Issue by 13d9aa96-8359-4b61-871f-f561ff79bfd8** [python/cpython#74287]
BPO | [30101](https://bugs.python.org/issue30101)
--- | :---
Nosy | @vstinner, @Eijebong, @zhangyangyu
PRs | <li>python/cpython#1015</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-26.15:17:40.602>
created_at = <Date 2017-04-19.17:18:46.302>
labels = ['3.7', 'library']
title = 'Add support for ncurses A_ITALIC'
updated_at = <Date 2017-04-26.15:33:04.115>
user = 'https://github.com/Eijebong'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-26.15:33:04.115>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-26.15:17:40.602>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-04-19.17:18:46.302>
creator = 'Eijebong'
dependencies = []
files = []
hgrepos = []
issue_num = 30101
keywords = []
message_count = 2.0
messages = ['292360', '292363']
nosy_count = 3.0
nosy_names = ['vstinner', 'Eijebong', 'xiang.zhang']
pr_nums = ['1015']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30101'
versions = ['Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
New changeset ab7886b78574d9224b26dc3a5b08e5c105fbbf11 by Xiang Zhang (Eijebong) in branch 'master':
bpo-30101: Add support for curses.A_ITALIC. (bpo-1015)
https://github.com/python/cpython/commit/ab7886b78574d9224b26dc3a5b08e5c105fbbf11

**Comment by vstinner** [comment]
Thanks Bastien Orivel for your first contribution to Python!
