### ISSUE TITLE
HTMLCalendar allow custom classes

### ISSUE THREAD

**Issue by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [python/cpython#74281]
BPO | [30095](https://bugs.python.org/issue30095)
--- | :---
Nosy | @doerwalter, @rhettinger, @oz123, @Mariatta
PRs | <li>python/cpython#1439</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-06.13:04:03.892>
created_at = <Date 2017-04-18.19:37:57.549>
labels = ['3.7', 'type-feature', 'library']
title = 'HTMLCalendar allow custom classes'
updated_at = <Date 2017-06-06.13:04:03.890>
user = 'https://github.com/oz123'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.13:04:03.890>
actor = 'doerwalter'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-06.13:04:03.892>
closer = 'doerwalter'
components = ['Library (Lib)']
creation = <Date 2017-04-18.19:37:57.549>
creator = 'Oz.Tiram'
dependencies = []
files = []
hgrepos = []
issue_num = 30095
keywords = []
message_count = 18.0
messages = ['291841', '291858', '291859', '291869', '291872', '291873', '291874', '292155', '292212', '292213', '292236', '292934', '293081', '294846', '294952', '294954', '295245', '295259']
nosy_count = 4.0
nosy_names = ['doerwalter', 'rhettinger', 'Oz.Tiram', 'Mariatta']
pr_nums = ['1439']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30095'
versions = ['Python 3.7']
```

</p></details>

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
At the moment methods like HTMLCalendar.formatmonthname and HTMLCalendar.formatmonth have hard coded name 'month'.

This class is pretty helpful as a good start, but if you want to customize
the styles it's not helpful.

I think it would be helpful for others too, if this would have be customize able.

Would you accept a PR for such thing?

**Comment by Mariatta** [comment]
Can't you override the `.month` css class and customize the style that way?

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
Of course I can, but I can't add multiple css classes, and I forced to
have the same class for both the title of the month and the body of the month.

**Comment by doerwalter** [comment]
IMHO this could all be done by overwriting the relevant methods.

But this might be overkill.

I think a solution might be to move the CSS classes into class attributes of HTMLCalendar. Customizing the CSS classes would then be done by subclassing HTMLCalendar and overwriting the appropriate class attributes.

Is this what you had in mind?

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
@doerwalter, exactly. I found myself overwriting the relevant methods too many times.

I usually did something like this:

```py
    class WorkCalendar(HTMLCalendar):

        def formatmonthname(self, theyear, themonth, withyear=True,
                        style=r'class="month-head"'):
             
            """
            Return a month name as a table row.
            """
            monthname = super().formatmonthname(theyear, themonth, withyear)
            regex = r'class\="month"'
            return re.sub(regex, style, monthname, 1)
```



Using class attributes would nice, also considering that the days CSS classes are defined as class attributes.

My intention was a few more class attributes (for the month header, and month) and also change the existing code such that each day can have multiple CSS classes and not just one.

I am willing to work on a PR for that if that sounds good and there is someone who would be willing to merge it.

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
... Using class attributes would nice, also considering that the days CSS classes are defined as class attributes.

I meant to write :

Using class attributes would be nicer, also considering that the days CSS classes are defined as class attributes.

**Comment by doerwalter** [comment]
OK, go ahead. I'm looking forward to what you come up with.

**Comment by doerwalter** [comment]
The second link is a 404.

For the v1 patch:

The variable names are a bit inconsistent: The first uses "classes" all others use "styles". This should be consistent within itself and with the existing code, i.e. "classes" should be used.

Also each class attribute should be preceded with a comment, explaining what the CSS class is used for.

As these are now made public to be overwritten by subclasses, I wonder wether it would make sense to document these class attributes in [Doc/library/calendar.rst](https://github.com/python/cpython/blob/main/Doc/library/calendar.rst)

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
@Walter,

I agree with you about consistent naming. Personally, I would prefer to name all the variables "styles". But I preferred not to break past compatibility too. So I guess we are stuck for a while with "classes". I will rename the variables. As for documenting that, I would also do that.
Thanks for the feedback.

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
Apparently, I forgot to push the second branch. It is now pushed.

I renamed the class attribute names on the v1 branch. I still need to do
the following:

 - Add docs
 - Fix existing tests and add new tests demonstrating the usage of the new attributes.

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
@Walter,

I implemented your suggestions plus the obvious tasks of adding tests and documentation.

Would be happy to hear your feedback.

**Comment by doerwalter** [comment]
See comments on Github

**Comment by doerwalter** [comment]
See my comments on the pull request: https://github.com/python/cpython/pull/1439

After you address those, IMHO this is ready to be merged.

**Comment by doerwalter** [comment]
See comments on the pull request. Also it seems that currently the pull request can't be merged because of merge conflicts.

**Comment by 0debf432-aa5a-4c01-98e8-f723a18c8b09** [comment]
@Walter, I fixed the issues your raised, and also solved the merge conflict in What's New.

**Comment by doerwalter** [comment]
Closing the issue. The patch has been merged.
