### ISSUE TITLE
json module: encoder optimization

### ISSUE THREAD

**Issue by ca982ac1-0d3c-422b-b163-5c784d5874cb** [python/cpython#74297]
BPO | [30111](https://bugs.python.org/issue30111)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[encoder_opt.patch](https://bugs.python.org/file46815/encoder_opt.patch "Uploaded as text/plain at 2017-04-20.09:15:29 by Marian Horban 2")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-20.10:36:21.415>
created_at = <Date 2017-04-20.09:15:30.868>
labels = ['library', 'performance']
title = 'json module: encoder optimization'
updated_at = <Date 2017-04-20.10:36:21.413>
user = 'https://bugs.python.org/MarianHorban2'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-20.10:36:21.413>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-20.10:36:21.415>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-20.09:15:30.868>
creator = 'Marian Horban 2'
dependencies = []
files = ['46815']
hgrepos = []
issue_num = 30111
keywords = ['patch']
message_count = 2.0
messages = ['291955', '291960']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Marian Horban 2']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30111'
versions = ['Python 2.7']
```

</p></details>

**Comment by ca982ac1-0d3c-422b-b163-5c784d5874cb** [comment]
It is possible to improve performance of json module encoder.
Since access to local variables is faster than to globals/builtins I propose to use locals instead of globals.
Small test of such improvement:

```pycon
>>> import timeit
>>> def flocal(name=False):
...     for i in range(5):
...         x = name
... 
>>> timeit.timeit("flocal()", "from __main__ import flocal", number=10000000)
5.0455567836761475
>>> 
>>> def fbuilt_in():
...     for i in range(5):
...         x = False
... 
>>> 
>>> timeit.timeit("fbuilt_in()", "from __main__ import fbuilt_in", number=10000000)
5.451796054840088
```

**Comment by serhiy-storchaka** [comment]
New features can be only added to the default branch. True and False are not global variables but keywords in Python 3. And in any case the json module is accelerated by C implementation which much faster than any microoptimized Python code.
