### ISSUE TITLE
Spam

### ISSUE THREAD

**Issue by cbf387af-c88f-4503-987f-7c55ef082fd7** [python/cpython#74298]
BPO | [30112](https://bugs.python.org/issue30112)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-20.09:47:18.745>
created_at = <Date 2017-04-20.09:20:30.795>
labels = ['invalid']
title = 'Spam'
updated_at = <Date 2017-04-20.15:03:00.633>
user = 'https://bugs.python.org/drkirkby'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-20.15:03:00.633>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-20.09:47:18.745>
closer = 'christian.heimes'
components = []
creation = <Date 2017-04-20.09:20:30.795>
creator = 'drkirkby'
dependencies = []
files = []
hgrepos = []
issue_num = 30112
keywords = []
message_count = 1.0
messages = ['291958']
nosy_count = 0.0
nosy_names = []
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30112'
versions = []
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Please don't click the link, Google chrome return a security error

"""
Attackers on www.arqja.com may trick you into doing something dangerous like installing software or revealing your personal information (for example, passwords, phone numbers, or credit cards).
"""
