### ISSUE TITLE
json module: it is not possible to override 'true', 'false' values during encoding bool

### ISSUE THREAD

**Issue by ca982ac1-0d3c-422b-b163-5c784d5874cb** [python/cpython#74300]
BPO | [30114](https://bugs.python.org/issue30114)
--- | :---
Nosy | @rhettinger, @etrepum, @serhiy-storchaka
Files | <li>[json_improvement.patch](https://bugs.python.org/file46816/json_improvement.patch "Uploaded as text/plain at 2017-04-20.10:04:05 by Marian Horban 2")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/etrepum'
closed_at = <Date 2017-04-21.04:48:10.924>
created_at = <Date 2017-04-20.10:04:06.183>
labels = ['3.7', 'type-feature', 'library']
title = "json module: it is not possible to override 'true', 'false' values during encoding bool"
updated_at = <Date 2017-04-21.05:10:09.581>
user = 'https://bugs.python.org/MarianHorban2'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-21.05:10:09.581>
actor = 'serhiy.storchaka'
assignee = 'bob.ippolito'
closed = True
closed_date = <Date 2017-04-21.04:48:10.924>
closer = 'bob.ippolito'
components = ['Library (Lib)']
creation = <Date 2017-04-20.10:04:06.183>
creator = 'Marian Horban 2'
dependencies = []
files = ['46816']
hgrepos = []
issue_num = 30114
keywords = ['patch']
message_count = 4.0
messages = ['291959', '292004', '292006', '292007']
nosy_count = 4.0
nosy_names = ['rhettinger', 'bob.ippolito', 'serhiy.storchaka', 'Marian Horban 2']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30114'
versions = ['Python 3.7']
```

</p></details>

**Comment by ca982ac1-0d3c-422b-b163-5c784d5874cb** [comment]
It is not possible to override 'true', 'false' values during encoding bool.
For example if I want to dump dict like:
    {"key": True}
and result must be not 
    {"key": true}
but let's say
    {"key": "TRUE"}
It is really hard to force json.dumps function to do it.

I understand that improving of json encoder performance causes this inflexible implementation.
Perfect solution for extending/overriding json module would be move nested functions
\_iterencode_list
\_iterencode_dict
\_iterencode
into class JSONEncoder as static methods.
But it could make performance a bit worse.

So if we cannot afford it I would propose to move function \_make_iterencode to JSONEncoder as a static method.
This change will not degrade performance.
But it will be possible to override this method in SPECIFIC user's Encoder.

**Comment by rhettinger** [comment]
Sorry, I think this is unnecessary feature creep.  The goal of the JSON module is to generate valid JSON for some semantically equivalent Python.  Wanting to turn \*True* into the string "True" isn't in the spirit of the module and certainly not worth all the proposed code churn.  If this is really what you need (a somewhat exotic need at that), then I would recommend writing a recursive tree walker that replaces \*True* nodes with "True" prior to outside of the JSON module.

**Comment by serhiy-storchaka** [comment]
I concur with Raymond.

**Comment by 8bb2fe13-d245-4fef-8aa2-70d7108db3c3** [comment]
Agreed, this does seem unnecessary. The library has been in active use for over a decade, and this is the first time I've seen this request. I would recommend preprocessing the data that you're going to encode if you have a need for this.
