### ISSUE TITLE
numpy.ndarray.T doesn't change the structure

### ISSUE THREAD

**Issue by 125b527d-ed51-4e00-b32d-db4283fec5cc** [python/cpython#74302]
BPO | [30116](https://bugs.python.org/issue30116)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-20.14:27:46.863>
created_at = <Date 2017-04-20.12:08:52.656>
labels = ['type-bug']
title = "numpy.ndarray.T doesn't change the structure"
updated_at = <Date 2017-04-20.14:27:46.862>
user = 'https://bugs.python.org/mmeliani'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-20.14:27:46.862>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-20.14:27:46.863>
closer = 'r.david.murray'
components = []
creation = <Date 2017-04-20.12:08:52.656>
creator = 'm.meliani'
dependencies = []
files = []
hgrepos = []
issue_num = 30116
keywords = []
message_count = 2.0
messages = ['291967', '291975']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'm.meliani']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30116'
versions = ['Python 2.7']
```

</p></details>

**Comment by 125b527d-ed51-4e00-b32d-db4283fec5cc** [comment]
The few following lines, i believe, show how the numpy.ndarray.T or numpy.ndarray.transpose() don't change the structure of the data only the way they're displayed. Which is sometimes a problem when handling big quantities of data which you need to look at a certain way for sorting problems among others.

```pycon
>>> import numpy as np
>>> x=np.array([[0,1,2],[1,2,3]])
>>> x=x.T
>>> print x
[[0 1]
 [1 2]
 [2 3]]
>>> y=np.array([[0,1],[1,2],[2,3]])
>>> print y
[[0 1]
 [1 2]
 [2 3]]
>>> y.view('i8,i8')
array([[(0, 1)],
       [(1, 2)],
       [(2, 3)]],
      dtype=[('f0', '<i8'), ('f1', '<i8')])
>>> x.view('i8,i8')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: new type not compatible with array.
```

**Comment by bitdancer** [comment]
Numpy is not part of the Python standard library.  You'll need to engage with the numpy community on this question.  (I say engage with them on the question, not report a bug to them, because I highly doubt this is a bug...there's probably some way to do what you want, so I suggest asking a question first rather than reporting a bug).
