### ISSUE TITLE
test_logging report reference leak

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74301]
BPO | [30115](https://bugs.python.org/issue30115)
--- | :---
Nosy | @vsajip, @vstinner, @zhangyangyu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-27.03:54:59.077>
created_at = <Date 2017-04-20.11:03:04.108>
labels = []
title = 'test_logging report reference leak'
updated_at = <Date 2017-04-27.03:54:59.075>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-27.03:54:59.075>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-27.03:54:59.077>
closer = 'xiang.zhang'
components = []
creation = <Date 2017-04-20.11:03:04.108>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30115
keywords = []
message_count = 4.0
messages = ['291961', '291986', '292023', '292394']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'vstinner', 'xiang.zhang']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30115'
versions = []
```

</p></details>

**Comment by zhangyangyu** [comment]
0:00:00 [1/1] test_logging
beginning 9 repetitions
123456789
.........
test_logging leaked [24, -24, 1, 24] memory blocks, sum=25
test_logging failed in 3 min 15 sec

1 test failed:
    test_logging

Seems d61910c598876788c9b4bf0e116370bbfc5a2f85 is responsible.

**Comment by vsajip** [comment]
I just did a git pull, then:

$ make distclean
$ ./configure --with-pydebug
$ make EXTRA_CFLAGS="-DPy_REF_DEBUG -DPy_TRACE_REFS"
$ ./python
Python 3.7.0a0 (heads/master:8f5cdfa, Apr 20 2017, 16:41:52) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>\>\>
$ ./python -m test.regrtest -R : test_logging
Run tests sequentially
0:00:00 [1/1] test_logging
beginning 9 repetitions
123456789
.........
test_logging passed in 3 min 2 sec
1 test OK.

Total duration: 3 min 2 sec
Tests result: SUCCESS

I do sometimes get errors if I run again, e.g.

test_logging leaked [-164, 164, 0, 0] references, sum=0
test_logging leaked [-29, 31, 0, 0] memory blocks, sum=2

but results appear different every time, it seems. Is there any way to get them reproducibly?

**Comment by vsajip** [comment]
Also getting values I'm not sure how to interpret:

```sh
$ ./python -m test.regrtest -R : test_logging
Run tests sequentially
0:00:00 [1/1] test_logging
beginning 9 repetitions
123456789
.........
test_logging leaked [-164, 164, -164, 0] references, sum=-164
test_logging leaked [-54, 56, -54, 2] memory blocks, sum=-50
test_logging failed in 2 min 57 sec
```


How can you be sure the problem is here rather than in the reference leak checks?

**Comment by zhangyangyu** [comment]
Seems in bpo-30131 Victor has solved this. :-)
