### ISSUE TITLE
Added missing archive programs.

### ISSUE THREAD

**Issue by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [python/cpython#74308]
BPO | [30122](https://bugs.python.org/issue30122)
--- | :---
Nosy | @bitdancer, @JulienPalard, @AraHaan
PRs | <li>python/cpython#1228</li><li>python/cpython#1229</li><li>python/cpython#1230</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-09-09.16:01:28.878>
created_at = <Date 2017-04-21.04:03:19.403>
labels = ['3.7', 'docs']
title = 'Added missing archive programs.'
updated_at = <Date 2019-09-09.16:01:28.874>
user = 'https://github.com/AraHaan'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-09.16:01:28.874>
actor = 'mdk'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-09-09.16:01:28.878>
closer = 'mdk'
components = ['Documentation']
creation = <Date 2017-04-21.04:03:19.403>
creator = 'Decorater'
dependencies = []
files = []
hgrepos = []
issue_num = 30122
keywords = []
message_count = 6.0
messages = ['292005', '292041', '292042', '292043', '292071', '351510']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'docs@python', 'mdk', 'Decorater']
pr_nums = ['1228', '1229', '1230']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30122'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
I realized the Windows docs lacked some information so I added it. I will try to create an cherry pick for 3.6 and 3.6 as well. Also if desired I could also see if it can be applied to the 2.7 branch as well.

**Comment by bitdancer** [comment]
Please close the redundant PRs.  I've commented on [pr1228](https://github.com/python/cpython/pull/1228).

**Comment by bitdancer** [comment]
To be clear: backport PRs should be created only after a PR has been approved.

**Comment by bitdancer** [comment]
Also, please review the (newly rewritten) section in the [devguide](https://devguide.python.org) about PRs.  I see now that there were changes made from the original here already, but I don't see the commits that made those changes.  The history of changes should be kept during PR development (they get squashed at the end).

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
Oh
