### ISSUE TITLE
argparse action not correctly describing the right behavior

### ISSUE THREAD

**Issue by a184b55b-4f19-4ec5-969b-ee9b42c82c7e** [python/cpython#74313]
BPO | [30127](https://bugs.python.org/issue30127)
--- | :---
Nosy | @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-21.13:44:59.499>
created_at = <Date 2017-04-21.13:20:52.388>
labels = ['type-bug', 'invalid', 'docs']
title = 'argparse action not correctly describing the right behavior'
updated_at = <Date 2017-04-21.13:44:59.498>
user = 'https://bugs.python.org/DiegoCostantini'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-21.13:44:59.498>
actor = 'Diego Costantini'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-21.13:44:59.499>
closer = 'Diego Costantini'
components = ['Documentation']
creation = <Date 2017-04-21.13:20:52.388>
creator = 'Diego Costantini'
dependencies = []
files = []
hgrepos = []
issue_num = 30127
keywords = []
message_count = 3.0
messages = ['292044', '292045', '292046']
nosy_count = 3.0
nosy_names = ['eric.smith', 'docs@python', 'Diego Costantini']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30127'
versions = ['Python 2.7']
```

</p></details>

**Comment by a184b55b-4f19-4ec5-969b-ee9b42c82c7e** [comment]
Here https://docs.python.org/2/library/argparse.html#action we have the following:

```pycon
>>> parser = argparse.ArgumentParser()
>>> parser.add_argument('--foo', action='store_true')
>>> parser.add_argument('--bar', action='store_false')
>>> parser.add_argument('--baz', action='store_false')
>>> parser.parse_args('--foo --bar'.split())
Namespace(bar=False, baz=True, foo=True)
```


baz should be False because omitted.
I also tested it.

**Comment by ericvsmith** [comment]
I think the example is correct. Because baz's action is store_false, the default is True. So if baz is omitted, it should have a True value. That's what the example shows, and what I see when I run this code.

Can you show what you tested, what you saw, and what you expected?

**Comment by a184b55b-4f19-4ec5-969b-ee9b42c82c7e** [comment]
You are right, I misunderstood the part where it sets defaults opposite to the stored value, although apparently over one year ago I did understand it correctly when I first went through that documentation.

Today my second pair of eyes had my same understanding of it though :)
