### ISSUE TITLE
CheckTraceCallbackContent of test_sqlite3 fails on OS X Tiger

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74312]
BPO | [30126](https://bugs.python.org/issue30126)
--- | :---
Nosy | @db3l, @ronaldoussoren, @vstinner, @ned-deily, @berkerpeksag, @palaviv
PRs | <li>python/cpython#1238</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.14:38:20.517>
created_at = <Date 2017-04-21.12:26:34.613>
labels = ['OS-mac', '3.7', 'tests']
title = 'CheckTraceCallbackContent of test_sqlite3 fails on OS X Tiger'
updated_at = <Date 2017-05-02.14:38:20.516>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.14:38:20.516>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.14:38:20.517>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-04-21.12:26:34.613>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30126
keywords = []
message_count = 10.0
messages = ['292032', '292033', '292035', '292036', '292052', '292055', '292075', '292076', '292087', '292766']
nosy_count = 6.0
nosy_names = ['db3l', 'ronaldoussoren', 'vstinner', 'ned.deily', 'berker.peksag', 'palaviv']
pr_nums = ['1238']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30126'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
I suggest to skip the following test on OS X Tiger, since it fails but I'm not interested to fix it and it seems to be an old SQLite bug which was fixed after Tiger was released (I don't see this failure on any other buildbot).

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/569/steps/test/logs/stdio

\======================================================================
FAIL: CheckTraceCallbackContent (sqlite3.test.hooks.TraceCallbackTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/db3l/buildarea/3.x.bolen-tiger/build/Lib/sqlite3/test/hooks.py", line 270, in CheckTraceCallbackContent
    self.assertEqual(traced_statements, queries)
AssertionError: Lists differ: ['cre[19 chars]'insert into foo(x) values(1)', 'insert into foo(x) values(1)'] != ['cre[19 chars]'insert into foo(x) values(1)']
```


First list contains 1 additional elements.
First extra element 2:
'insert into foo(x) values(1)'

```diff
+ ['create table foo(x)', 'insert into foo(x) values(1)']
- ['create table foo(x)',
-  'insert into foo(x) values(1)',
-  'insert into foo(x) values(1)']
```

----------------------------------------------------------------------

**Comment by vstinner** [comment]
SQLite version:

Re-running test 'test_sqlite' in verbose mode
test_sqlite: testing with version '2.6.0', sqlite_version '3.6.11'

**Comment by vstinner** [comment]
The test is already skipped on SQLite version older than 3.3.9, no idea why the test fails on SQLite version 3.6.11 on OS X Tiger:

@unittest.skipIf(sqlite.sqlite_version_info \< (3, 3, 9),
                 "sqlite3_prepare_v2 is not available") 

I proposed the PR https://github.com/python/cpython/pull/1238

**Comment by vstinner** [comment]
It's even more strange. The test started to fail since this build, Sun Apr 9 10:10:15 2017:

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/528

test_sqlite: testing with version '2.6.0', sqlite_version '3.6.11'
...
test test_sqlite failed


Sadly, before the test passed and so the SQLite version wasn't logged:

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/527/steps/test/logs/stdio
0:26:24 [227/404/1] test_sqlite passed


@David Bolen: Did you make a change, like an upgrade, on this buildbot slave around Apr 9, 2017?

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
> It's even more strange. The test started to fail since this build, Sun Apr 9 10:10:15 2017:

This was merged on Apr 9 (commit 0e6cb2ea624570ed08c354f1ed1f595dab4192d6).

From a quick look in the internet some other people had a similar problem:
http://stackoverflow.com/questions/28973887/how-to-fix-sqlite3-libversion-mismatch

It seems there might be mismatch between sqlite3_libversion() and SQLITE_VERSION. I am not familiar with the buildbots but can you run a test that check that sqlite3_libversion() == SQLITE_VERSION?

**Comment by vstinner** [comment]
> It seems there might be mismatch between sqlite3_libversion() and SQLITE_VERSION. I am not familiar with the buildbots but can you run a test that check that sqlite3_libversion() == SQLITE_VERSION?

The Python sqlite3 exports sqlite3_libversion() as sqlite3.sqlite_version, "3.6.11" on OS X Tiger.

The doc https://sqlite.org/c3ref/libversion.html says "These interfaces [sqlite3_libversion()] provide the same information as the SQLITE_VERSION, ..."

I don't know how to check, I don't have access to the buildbot.

**Comment by db3l** [comment]
No recent changes to the buildbot (I think the last was in September to bump the local python used to run the slave/build installer to 2.7).

The default system sqlite (/usr/lib) is 3.0.8.6, so extremely old, but 3.6.11 is in /usr/local/{lib,include} from early days of setting up the slave, so only marginally less old.  As long as the python build process finds that (which it appears to) it should be consistent.

I configured and built a local 3.x branch version of python on the slave and modified it to dump the version info during module initialization:

```pycon
> ./python.exe
Python 3.7.0a0 (heads/master:d1ae24e, Apr 21 2017, 15:06:29) 
[GCC 4.0.1 (Apple Computer, Inc. build 5367)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlite3
SQLITE_VERSION: 3.6.11
SQLITE_VERSION_NUMBER: 3006011
sqlite3_libversion: 3.6.11
```


so it appears to be in line.  This local build still fails the test.

Maybe whatever feature is needed for this test is broken with 3.6.11.

One thing I did notice, though I suspect it's not an issue, but the 3.6.11 this slave is using seems to fall into the gap in the original bpo-9303 \_v2 support patch where a \_v2 prepare with a plain close (versions \>= 3.3.9 and \<3.7.14).  Both plain and \_v2 close methods have the same signature, but I wonder if there might be an issue mixing and matching?

I don't think anything else has a hard dependency on my /usr/local libraries on the slave at this point (the dmg installer builds its own local copies), so I could try updating that to a more current sqlite3 if we wanted to see if that resolved the issue.

**Comment by db3l** [comment]
The test appears to pass against a local test build of sqlite3 3.18.0, so I'll probably just plan on updating the slave to that later tonight.  Unless anyone is interested in figuring out why it fails with 3.6.11 and not 3.18.0 (e.g., does the test have a higher minimum version than it currently declares).

**Comment by db3l** [comment]
Ok, this should be resolved.  I opted to be a bit more conservative and only upgraded to sqlite3 3.8.3.1, which is the oldest version still in use for the dmg installer packages (for 2.7).  I restarted the most recent 3.x build and while it's not completely done yet, the sqlite tests have passed.

**Comment by vstinner** [comment]
David: "Ok, this should be resolved."

Oh, thank you! I confirm that test_sqlite3 pass again!
