### ISSUE TITLE
Strings that end with properly escaped backslashes cause error to be thrown in re.search/sub/etc. functions.

### ISSUE THREAD

**Issue by b5420b66-f2af-404e-9146-586ce6c96762** [python/cpython#74319]
BPO | [30133](https://bugs.python.org/issue30133)
--- | :---
Nosy | @ezio-melotti, @bitdancer, @serhiy-storchaka
Superseder | <li>bpo-31714: Improve re documentation</li>
Files | <li>[sample.py](https://bugs.python.org/file46822/sample.py "Uploaded as text/plain at 2017-04-21.21:18:05 by Patrick Foley")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-16.13:25:52.023>
created_at = <Date 2017-04-21.21:18:05.459>
labels = ['expert-regex', '3.7']
title = 'Strings that end with properly escaped backslashes cause error to be thrown in re.search/sub/etc. functions.'
updated_at = <Date 2017-11-16.13:25:52.022>
user = 'https://bugs.python.org/PatrickFoley'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-16.13:25:52.022>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-16.13:25:52.023>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-21.21:18:05.459>
creator = 'Patrick Foley'
dependencies = []
files = ['46822']
hgrepos = []
issue_num = 30133
keywords = []
message_count = 7.0
messages = ['292079', '292080', '292093', '292094', '292095', '292102', '306358']
nosy_count = 5.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'r.david.murray', 'serhiy.storchaka', 'Patrick Foley']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = '31714'
type = None
url = 'https://bugs.python.org/issue30133'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b5420b66-f2af-404e-9146-586ce6c96762** [comment]
The following code demonstrates:

```py
import re
text = 'ab\\'
exp = re.compile('a')
print(re.sub(exp, text, ''))
```


If you remove the backslash(es), the code runs fine.

This appears to be specific to the re module and only to strings that end in (even properly escaped) backslashes. You could easily receive raw data like this from freehand input sources so it would be nice not to have to remove trailing backslashes before running a regular expression.

**Comment by bitdancer** [comment]
I think you are missing a re.escape around text.  Text is otherwise not a valid replacement pattern.

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
Yes, the second argument is a replacement template, not a literal.

This issue does point out a different problem, though: re.escape will add backslashes that will then be treated as literals in the template, for example:

```pycon
>>> re.sub(r'a', re.escape('(A)'), 'a')
'\\(A\\)'
```


re.escape doesn't always help.

The solution here is to pass a replacement function instead:

```pycon
>>> re.sub(r'a', lambda m: '(A)', 'a')
'(A)'
```

**Comment by bitdancer** [comment]
Good point, re.escape is for literal text you want to insert into a matching pattern, but the replacement template isn't a matching pattern.  Do we need a different escape function?  I guess the function solution is enough?

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
The function solution does have a larger overhead than a literal.

Could the template be made more accepting of backslashes without breaking anything? (There's also bpo-29995 "re.escape() escapes too much", which might help.)

**Comment by serhiy-storchaka** [comment]
re.escape() shouldn't be used for a replacement template. You need just double backslashes when escape a literal string for a replacement template: s.replace('\\\\', '\\\\\\\\'). This should be documented if still is not documented.

**Comment by serhiy-storchaka** [comment]
The proper way of escaping the replacement string has been documented by bpo-31714.
