### ISSUE TITLE
The "callable" fixer doesn't exist

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74328]
BPO | [30142](https://bugs.python.org/issue30142)
--- | :---
Nosy | @gpshead, @benjaminp, @serhiy-storchaka, @Mariatta
PRs | <li>python/cpython#1296</li><li>python/cpython#1303</li><li>python/cpython#1304</li><li>python/cpython#1305</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-04-26.16:56:53.391>
created_at = <Date 2017-04-23.12:00:24.158>
labels = ['easy', '3.7', 'expert-2to3', 'docs']
title = 'The "callable" fixer doesn\'t exist'
updated_at = <Date 2017-04-26.17:16:45.206>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-26.17:16:45.206>
actor = 'serhiy.storchaka'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-04-26.16:56:53.391>
closer = 'Mariatta'
components = ['Documentation', '2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-04-23.12:00:24.158>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30142
keywords = ['easy']
message_count = 6.0
messages = ['292162', '292368', '292371', '292372', '292373', '292376']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'benjamin.peterson', 'docs@python', 'serhiy.storchaka', 'Mariatta']
pr_nums = ['1296', '1303', '1304', '1305']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30142'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The "callable" fixer was removed in dbdf029a5575f6e6ec0140260236963ed7d2c2be, but it still is mentioned in the documentation.

https://docs.python.org/3/library/2to3.html#2to3fixer-callable

**Comment by Mariatta** [comment]
New changeset a90b990480f45b6a0ad02d43455cf8b620bac9c5 by Mariatta (Dong-hee Na) in branch 'master':
bpo-30142: Remove "callable" from the 2to3fixer documentation. (GH-1296)
https://github.com/python/cpython/commit/a90b990480f45b6a0ad02d43455cf8b620bac9c5

**Comment by Mariatta** [comment]
New changeset 9a626ec4e58c0bca1b4f71154e9e1da7e6d7e4a7 by Mariatta (Dong-hee Na) in branch '3.5':
[3.5] bpo-30142: Remove "callable" from the 2to3fixer documentation. (GH-1304)
https://github.com/python/cpython/commit/9a626ec4e58c0bca1b4f71154e9e1da7e6d7e4a7

**Comment by Mariatta** [comment]
New changeset 19b3a4885cc685adb42db6f8f7b625768f6d1baf by Mariatta (Dong-hee Na) in branch '2.7':
[2.7] bpo-30142: Remove "callable" from the 2to3fixer documentation. (GH-1305)
https://github.com/python/cpython/commit/19b3a4885cc685adb42db6f8f7b625768f6d1baf

**Comment by Mariatta** [comment]
New changeset 2fc3c543fc93d6211de8dcfaeac3a0fd10a356e0 by Mariatta (Dong-hee Na) in branch '3.6':
[3.6] bpo-30142: Remove "callable" from the 2to3fixer documentation. (GH-1303)
https://github.com/python/cpython/commit/2fc3c543fc93d6211de8dcfaeac3a0fd10a356e0

**Comment by serhiy-storchaka** [comment]
Thanks Dong-hee Na and Mariatta.
