### ISSUE TITLE
Using collections ABC from collections.abc rather than collections in 2to3 converted code

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74329]
BPO | [30143](https://bugs.python.org/issue30143)
--- | :---
Nosy | @rhettinger, @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#1262</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-16.07:19:42.040>
created_at = <Date 2017-04-23.12:11:25.685>
labels = ['3.7', 'type-feature', 'expert-2to3']
title = 'Using collections ABC from collections.abc rather than collections in 2to3 converted code'
updated_at = <Date 2017-11-16.07:19:42.040>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-16.07:19:42.040>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-16.07:19:42.040>
closer = 'serhiy.storchaka'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-04-23.12:11:25.685>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30143
keywords = []
message_count = 4.0
messages = ['292163', '306279', '306282', '306341']
nosy_count = 3.0
nosy_names = ['rhettinger', 'benjamin.peterson', 'serhiy.storchaka']
pr_nums = ['1262']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30143'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch makes 2to3 generating a code that uses abstract collection classes Sequence and Mapping from collections.abc rather than collections. Since abstract collection classes now are defined in collections.abc and collections contains only aliases for compatibility, this is more idiomatic Python 3 code.

**Comment by serhiy-storchaka** [comment]
What are your thoughts about this Benjamin?

**Comment by rhettinger** [comment]
+1 I think this change will be essential.  IIRC, elsewhere Guido approved a 3.7 change so that the ABC will no longer be visible in collections.

**Comment by serhiy-storchaka** [comment]
New changeset 0a2abdfca2495291809855cf7dfc6721c9c962e3 by Serhiy Storchaka in branch 'master':
bpo-30143: 2to3 now generates a code that uses abstract collection classes (bpo-1262)
https://github.com/python/cpython/commit/0a2abdfca2495291809855cf7dfc6721c9c962e3
