### ISSUE TITLE
Fix for issue 8743 not available in python MacOS 3.5.1

### ISSUE THREAD

**Issue by f6ed1dce-d350-4eba-89df-6ca241900e74** [python/cpython#74325]
BPO | [30139](https://bugs.python.org/issue30139)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @bitdancer, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-22.19:31:34.337>
created_at = <Date 2017-04-22.18:54:20.271>
labels = ['OS-mac', 'library']
title = 'Fix for issue 8743 not available in python MacOS 3.5.1'
updated_at = <Date 2017-04-22.19:50:56.163>
user = 'https://bugs.python.org/HoracioHoyos'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-22.19:50:56.163>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-22.19:31:34.337>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'macOS']
creation = <Date 2017-04-22.18:54:20.271>
creator = 'Horacio Hoyos'
dependencies = []
files = []
hgrepos = []
issue_num = 30139
keywords = []
message_count = 5.0
messages = ['292134', '292135', '292136', '292137', '292138']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'r.david.murray', 'serhiy.storchaka', 'Horacio Hoyos']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30139'
versions = ['Python 3.5']
```

</p></details>

**Comment by f6ed1dce-d350-4eba-89df-6ca241900e74** [comment]
Hi all,

I was having issues while testing a custom Set implementation using the \_collections_abc base MutableSet and found that my issue was apparently resolved with bpo-8743. My test is simple:

```py
ms = MySetImpl()
ms & 'testword'
```


which should fail with TypeError, given that in the 8743 fix the \_\_and__ incorporated a test for isinstance(other, Set).

Looking at the \_collections_abc.py in my installation (/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/_collections_abc.py) I can not see the changes in the patches submitted for bpo-8743.

**Comment by bitdancer** [comment]
Then you have a broken copy of 3.5.1.  There is nothing OS-specific about that file.

**Comment by ned-deily** [comment]
>\> Then you have a broken copy of 3.5.1.

Yes. You don't say from where you installed Python 3.5.1 but I just took a quick look at \_collections_abc.py in both the versions installed by the python.org 3.5.1 macOS installer and by the current 3.5.3 version (which you should update to, or, better, 3.6.1) and the bpo-8743 changes appear to be there.  If you still believe there is a problem with Python here, please reopen and provide a complete test case.

**Comment by serhiy-storchaka** [comment]
But there is no neither an entry bpo-8743, nor neighbour entries bpo-14710 and bpo-13355 in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS). Seems [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is broken.

**Comment by ned-deily** [comment]
> But there is no neither an entry bpo-8743, nor neighbour entries bpo-14710 and bpo-13355 in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS). Seems [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is broken.

Hmm. They seem to have been properly preserved in the current 3.6 and master branch versions of [Misc/HISTORY](https://github.com/python/cpython/blob/main/Misc/HISTORY).  Perhaps the 3.5 [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) was corrupted in a merge along the way?  In any case, this is not relevant to the OP's problem.  Once the auto-generation of [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is implemented, we're going to have to go back and redo [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) and [Misc/HISTORY](https://github.com/python/cpython/blob/main/Misc/HISTORY) in active branches.  I don't think there is a need for a separate issue to track that but, if you want to open one, Serhiy, feel free to do so.
