### ISSUE TITLE
BytesWarning is missing from the documents

### ISSUE THREAD

**Issue by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [python/cpython#74320]
BPO | [30134](https://bugs.python.org/issue30134)
--- | :---
Nosy | @benjaminp, @bitdancer, @methane, @vadmium, @serhiy-storchaka, @cocoatomo
PRs | <li>python/cpython#1249</li><li>python/cpython#12738</li><li>python/cpython#12739</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-09.12:50:05.322>
created_at = <Date 2017-04-22.03:49:31.787>
labels = ['type-feature', 'docs']
title = 'BytesWarning is missing from the documents'
updated_at = <Date 2019-04-09.12:50:05.322>
user = 'https://github.com/cocoatomo'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-09.12:50:05.322>
actor = 'methane'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-04-09.12:50:05.322>
closer = 'methane'
components = ['Documentation']
creation = <Date 2017-04-22.03:49:31.787>
creator = 'cocoatomo'
dependencies = []
files = []
hgrepos = []
issue_num = 30134
keywords = ['patch']
message_count = 9.0
messages = ['292099', '292101', '292145', '339701', '339704', '339707', '339708', '339713', '339741']
nosy_count = 7.0
nosy_names = ['benjamin.peterson', 'r.david.murray', 'methane', 'docs@python', 'martin.panter', 'serhiy.storchaka', 'cocoatomo']
pr_nums = ['1249', '12738', '12739']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30134'
versions = ['Python 2.7']
```

</p></details>

**Comment by 2d91cabd-b217-43ac-afd6-4d0c354b0f59** [comment]
In Python 2.6, BytesWarning was added, but a description of that warning is missing from the document, library/exceptions.rst.

**Comment by serhiy-storchaka** [comment]
BytesWarning should be added in the table in warnings.rst (and check that all other built-in warning categories are in this table). It is worth to mention the -b option.

And I think the docstring of BytesWarning should be corrected. "Unicode" should be used rather that "str" since str and bytes is the same in 2.7.

**Comment by vadmium** [comment]
.
bpo-11681 is already open for the -b option, with a patch in progress.

If updating the doc string, also change “buffer” to “bytearray”. This is what “bytearray” was originally called in Python 3, and “buffer” is something different in Python 2.
