### ISSUE TITLE
default value of argument seems to be overwritten

### ISSUE THREAD

**Issue by 48729656-8578-44ed-bb88-c6dbff2a6f75** [python/cpython#74321]
BPO | [30135](https://bugs.python.org/issue30135)
--- | :---
Nosy | @stevendaprano, @serhiy-storchaka
Files | <li>[misc_math.7z](https://bugs.python.org/file46825/misc_math.7z "Uploaded as application/x-7z-compressed at 2017-04-22.04:19:14 by approximately"): Two Python scripts, only one character changed</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-22.06:31:18.234>
created_at = <Date 2017-04-22.04:19:14.649>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'default value of argument seems to be overwritten'
updated_at = <Date 2017-04-22.17:44:42.212>
user = 'https://bugs.python.org/approximately'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-22.17:44:42.212>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-22.06:31:18.234>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-04-22.04:19:14.649>
creator = 'approximately'
dependencies = []
files = ['46825']
hgrepos = []
issue_num = 30135
keywords = []
message_count = 5.0
messages = ['292100', '292110', '292113', '292118', '292129']
nosy_count = 3.0
nosy_names = ['steven.daprano', 'serhiy.storchaka', 'approximately']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30135'
versions = ['Python 3.5']
```

</p></details>

**Comment by 48729656-8578-44ed-bb88-c6dbff2a6f75** [comment]
Two function results differ if the parameter is given explictly instead of using the given default.

(Enclosed example: A small simple interpreter of Forth language, both scripts should give the same result, but the first one (variant1) fails because the value from the first pass remains on the stack.)

**Comment by serhiy-storchaka** [comment]
See "Why are default values shared between objects?" in Python FAQ (https://docs.python.org/3/faq/programming.html#id13).

**Comment by 48729656-8578-44ed-bb88-c6dbff2a6f75** [comment]
A documented misbheavior is still a misbehavior.

**Comment by serhiy-storchaka** [comment]
This is correct behavior. You just made a common mistake made by newcomers. Read Python FAQ and other resources, this can help you to avoid other pitfalls.

**Comment by stevendaprano** [comment]
In the future please don't post binary files containing source code, especially something as non-standard as 7z. That just makes it difficult for people to review the code. Either paste your code snippet directly into the bug report, or attach it as a .py file.

If the file is so huge it needs compression, you shouldn't be posting it at all. You should post the \*minimum* code to demonstrate the problem, not an entire application: we don't a 200 line simulation of a Forth interpreter just to see something that can be shown in ten lines. Even though this is written for Java programmers, the same applies here: http://sscce.org/


Thank you.
