### ISSUE TITLE
Pathological regex behaviour

### ISSUE THREAD

**Issue by fb8ef5d2-775c-4892-9640-4e3ffe37b9fd** [python/cpython#74334]
BPO | [30148](https://bugs.python.org/issue30148)
--- | :---
Nosy | @tim-one, @ezio-melotti, @serhiy-storchaka
Files | <li>[retest.py](https://bugs.python.org/file46828/retest.py "Uploaded as text/plain at 2017-04-23.19:26:02 by jpakkane")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-16.14:56:22.648>
created_at = <Date 2017-04-23.19:26:02.749>
labels = ['expert-regex', 'performance']
title = 'Pathological regex behaviour'
updated_at = <Date 2017-11-16.14:56:22.646>
user = 'https://bugs.python.org/jpakkane'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-16.14:56:22.646>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-16.14:56:22.648>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-04-23.19:26:02.749>
creator = 'jpakkane'
dependencies = []
files = ['46828']
hgrepos = []
issue_num = 30148
keywords = []
message_count = 4.0
messages = ['292181', '292183', '292237', '292238']
nosy_count = 5.0
nosy_names = ['tim.peters', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'jpakkane']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30148'
versions = []
```

</p></details>

**Comment by fb8ef5d2-775c-4892-9640-4e3ffe37b9fd** [comment]
Attached is a script that runs a single regex against one line of text taking over 12 seconds.

If you run the exact same regex in Perl it finishes immediately.

The slowness has something to do with spaces. If you replace consecutive spaces in the input with one, the evaluation is immediate.

This bug was originally discovered here: https://bugzilla.gnome.org/show_bug.cgi?id=781569

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
If 'ignores' is '', you get this:

    (?:\b(?:extern|G_INLINE_FUNC|%s)\s*)

which can match an empty string, and it's tried repeatedly.

That's inadvisable.

There's also:

    (?:\s+|\*)+

which can match whitespace in multiple ways.

That's inadvisable too.

If the pattern really doesn't match the string (and it doesn't!), then it won't find out until it has tried \_all_ of the possibilities.

Some implementations, such as Perl's, have extra checks to try to reduce the problem.

**Comment by fb8ef5d2-775c-4892-9640-4e3ffe37b9fd** [comment]
This is slow even when ignores is set to a non-empty value. It's not as slow but the real slowdown is in the whitespace regex. Here is a minimal sample:

input = '                              abc'
re.search(r'(\\s+)+d', input)

**Comment by tim-one** [comment]
Yes, that example takes time exponential in the number of blanks to (fail to) match - each time you add a blank to `input`, it essentially doubles the time required.

It's _possible_ for an implementation to deduce that `(\s+)+` is an insanely inefficient way to spell `\s+`, like it's _possible_ for an implementation to deduce that 10**10**10 - 10**10**10 is an insanely inefficient way to spell 0.

Python's does not.  To understand what's going on, Friedl's book "Mastering Regular Expressions" is an excellent source.
