### ISSUE TITLE
Import collections ABC from collections.abc rather than collections

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74330]
BPO | [30144](https://bugs.python.org/issue30144)
--- | :---
Nosy | @rhettinger, @terryjreedy, @skrah, @serhiy-storchaka
PRs | <li>python/cpython#1263</li><li>python/cpython#2106</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-04-24.07:41:43.362>
created_at = <Date 2017-04-23.12:30:13.851>
labels = ['3.7', 'type-feature', 'library']
title = 'Import collections ABC from collections.abc rather than collections'
updated_at = <Date 2017-06-11.10:14:03.910>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-11.10:14:03.910>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-04-24.07:41:43.362>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-23.12:30:13.851>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30144
keywords = []
message_count = 7.0
messages = ['292164', '292165', '292166', '292171', '292195', '292202', '295697']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'stutzbach', 'skrah', 'serhiy.storchaka']
pr_nums = ['1263', '2106']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30144'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Now abstract collection classes are defined in collections.abc rather than collections. collections contains just aliases for compatibility. Importing collections ABC from collections.abc is more idiomatic. And when aliases will be removed from collection this will be the only way.

But some code still imports them from collections. Proposed patch makes it importing them from collections.abc.

The most basic modules like locale, weakref and pathlib could import them just from \_collections_abc for decreasing the startup time, but this is different issue.

The patch doesn't touch the collections module itself and its tests, and the \_decimal module which imports collections.MutableMapping in C code (changing this would require more rewriting).

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
I thought splitting off abc was done for performance reasons (reduce the number of imports at Python startup), not for more idiomatic code.

**Comment by serhiy-storchaka** [comment]
If this is the main cause I can replace collections.abc in this patch with \_collections_abc. But I prefer to do this in separate commit. My next patch will include other changes for the number of imports.

**Comment by rhettinger** [comment]
+1 This patch looks like a step in the right direction.

**Comment by serhiy-storchaka** [comment]
New changeset 2e576f5aec1f8f23f07001e2eb3db9276851a4fc by Serhiy Storchaka in branch 'master':
bpo-30144: Import collections ABC from collections.abc rather than collections. (bpo-1263)
https://github.com/python/cpython/commit/2e576f5aec1f8f23f07001e2eb3db9276851a4fc

**Comment by serhiy-storchaka** [comment]
bpo-30152 replaces some collections.abc with \_collections_abc for performance reasons.

**Comment by terryjreedy** [comment]
New changeset a13225e209cfa5f7b458dbcbac19dc4df26feb95 by terryjreedy in branch '3.6':
[3.6]bpo-30144: change idlelib abc import [GH-1263] (bpo-2106)
https://github.com/python/cpython/commit/a13225e209cfa5f7b458dbcbac19dc4df26feb95
