### ISSUE TITLE
lru_cache should support invalidations

### ISSUE THREAD

**Issue by jcea** [python/cpython#74339]
BPO | [30153](https://bugs.python.org/issue30153)
--- | :---
Nosy | @rhettinger, @jcea, @stevendaprano, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-04-25.01:18:20.393>
created_at = <Date 2017-04-24.10:29:30.249>
labels = ['3.7', 'type-feature', 'library']
title = 'lru_cache should support invalidations'
updated_at = <Date 2017-04-25.02:44:34.605>
user = 'https://github.com/jcea'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-25.02:44:34.605>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-04-25.01:18:20.393>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-04-24.10:29:30.249>
creator = 'jcea'
dependencies = []
files = []
hgrepos = []
issue_num = 30153
keywords = []
message_count = 6.0
messages = ['292216', '292226', '292228', '292229', '292248', '292251']
nosy_count = 4.0
nosy_names = ['rhettinger', 'jcea', 'steven.daprano', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30153'
versions = ['Python 3.7']
```

</p></details>

**Comment by jcea** [comment]
I think that "functools.lru_cache()" should have the ability to "invalidate" a (possibly cached) value. Something like:

```py
@functools.lru_cache()
def func(param):
  ...

func.invalidate(PARAM) # discard this cached call, or ignore if not cached
```

**Comment by stevendaprano** [comment]
Perhaps the existing ``cache_clear`` method could take optional arguments?

```py
def cache_clear(self, *args, **kw):
    if not (args or kw):
        # clear the entire cache
    else:
        # clear just the cache entry for *args, **kw
```

**Comment by serhiy-storchaka** [comment]
Could cache_clear() clear the entire cache or discard just the cached call without arguments?

**Comment by serhiy-storchaka** [comment]
This is a duplicate of rejected bpo-28178.

See also related bpo-17528, bpo-18577, bpo-19859, bpo-23030, bpo-26082, and bpo-28112.

**Comment by rhettinger** [comment]
Sorry Jesús, I don't want to add feature creep to the LRU cache.

FWIW, it is very easy to make your own variants from collections.OrderedDict.

**Comment by rhettinger** [comment]
If you're interested, here is a starting point for experimenting with any variations you want (invalidate a specific entry, changeable maxsize, pickle/unpickle, expiration of entries after a specific time, inspection of the internal contents, ability to inject known values, testing whether a specific argument tuple is in the cache, logging of cache access, or just about anything you could do with a regular dictionary):

```py
    class LRU(OrderedDict):

        def __init__(self, func, maxsize=128):
            self.maxsize = 128
            self.func = func

        def __call__(self, *args):
            if args in self:
                value = self[args]
                self.move_to_end(args)
                return value
            value = self.func(*args)
            if len(self) >= self.maxsize:
                self.popitem(False)
            self[args] = value
            return value
```
