### ISSUE TITLE
Add _PyTuple_Empty and make PyTuple_New(0) never failing

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74348]
BPO | [30162](https://bugs.python.org/issue30162)
--- | :---
Nosy | @rhettinger, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1283</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-25.13:21:03.910>
created_at = <Date 2017-04-25.16:51:52.323>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Add _PyTuple_Empty and make PyTuple_New(0) never failing'
updated_at = <Date 2019-08-26.21:35:12.272>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-26.21:35:12.272>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-25.13:21:03.910>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-04-25.16:51:52.323>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30162
keywords = []
message_count = 4.0
messages = ['292274', '292297', '350453', '350570']
nosy_count = 3.0
nosy_names = ['rhettinger', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1283']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30162'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch makes the empty tuple be allocated in static memory rather than dynamic memory, expose a reference to it as \_PyTuple_Empty, and makes PyTuple_New(0) never raising exceptions. This allows to simplify the code. No longer need to call PyTuple_New(0), check it's result for errors, and clean up it after the use, you just can use a borrowed reference \_PyTuple_Empty.

\_PyTuple_Empty is for CPython internal use only.

**Comment by rhettinger** [comment]
The patch shows a nice payoff from this short-cut, so go ahead and apply it.

Still, I wish there were some aversion to posting a new patch every two days that alters twenty files all over the standard library.  The rate of churn is alarming.
