### ISSUE TITLE
Using `with` statement causes dict to start papering over attribute errors

### ISSUE THREAD

**Issue by 1bb48fc4-6db7-4888-8351-2b3068bae1d6** [python/cpython#74347]
BPO | [30161](https://bugs.python.org/issue30161)
--- | :---
Nosy | @tjguk, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-25.16:22:31.139>
created_at = <Date 2017-04-25.16:19:38.030>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'Using `with` statement causes dict to start papering over attribute errors'
updated_at = <Date 2017-04-25.16:28:28.438>
user = 'https://bugs.python.org/charlesc'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-25.16:28:28.438>
actor = 'tim.golden'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-25.16:22:31.139>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-04-25.16:19:38.030>
creator = 'charlesc'
dependencies = []
files = []
hgrepos = []
issue_num = 30161
keywords = []
message_count = 4.0
messages = ['292270', '292271', '292272', '292273']
nosy_count = 3.0
nosy_names = ['tim.golden', 'r.david.murray', 'charlesc']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30161'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1bb48fc4-6db7-4888-8351-2b3068bae1d6** [comment]
This is a weird one.  I've reproduced it with 3 versions of 2.7, including the latest 2.7.13.  I didn't find an open bug about this, but I had difficulty crafting a search string for it, so I may have missed something.

Basically, using a `with` statement (maybe any such statement, but using an open file definitely does it, even when I do nothing with it) causes the built-in dict class to stop raising AttributeErrors, which can result in odd bugs.

Example:

```pycon
Python 2.7.13 (default, Apr 25 2017, 10:12:36) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> with sys.stderr as foo:
...     pass
... 
>>> {}.nosuchattribute
>>> {}.nosuchattribute is None
>>> 
```


I haven't tried the latest 3.x, but it's definitely still there in 3.2.3:

```pycon
Python 3.2.3 (default, Nov 17 2016, 01:04:00) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> with sys.stderr as foo:
...     pass
... 
>>> {}.nosuchattribute
>>> {}.nosuchattribute is None
>>>
```

**Comment by bitdancer** [comment]
You've closed stderr.

**Comment by 1bb48fc4-6db7-4888-8351-2b3068bae1d6** [comment]
oh ffs ;)

**Comment by tjguk** [comment]
I think you're suppressing sys.stderr after the "with". Try a NameError 
or anything.

Alternatively, try a "with" which isn't using sys.stderr

Obviously, the next question is why \*that's* happening.
