### ISSUE TITLE
Deprecation warnings emitted in test_importlib

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74344]
BPO | [30158](https://bugs.python.org/issue30158)
--- | :---
Nosy | @brettcannon, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1285</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-29.04:10:47.620>
created_at = <Date 2017-04-25.09:58:19.018>
labels = ['3.7', 'type-bug', 'tests']
title = 'Deprecation warnings emitted in test_importlib'
updated_at = <Date 2017-04-29.04:10:47.619>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-29.04:10:47.619>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-29.04:10:47.620>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-04-25.09:58:19.018>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30158
keywords = []
message_count = 4.0
messages = ['292259', '292284', '292285', '292560']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1285']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30158'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -We -m test.regrtest -v test_importlib
...
```

======================================================================
ERROR: test_find_module (test.test_importlib.test_abc.Frozen_MetaPathFinderDefaultsTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_importlib/test_abc.py", line 160, in test_find_module
    self.assertIsNone(self.ins.find_module('something', None))
  File "/home/serhiy/py/cpython/Lib/test/test_importlib/test_abc.py", line 151, in find_module
    return super().find_module(fullname, path)
  File "/home/serhiy/py/cpython/Lib/importlib/abc.py", line 72, in find_module
    stacklevel=2)
DeprecationWarning: MetaPathFinder.find_module() is deprecated since Python 3.4 in favor of MetaPathFinder.find_spec()(available since 3.4)
```


...

**Comment by vstinner** [comment]
> DeprecationWarning: MetaPathFinder.find_module() is deprecated since Python 3.4 in favor of MetaPathFinder.find_spec()(available since 3.4)

Is a space missing in the error message between "MetaPathFinder.find_spec()" and "(available since 3.4)"?

**Comment by vstinner** [comment]
Deprecation introduced by issue bpo-29576 according to the PR.

**Comment by serhiy-storchaka** [comment]
New changeset 3cc8259b71ef784a9f7593f04da96043afe2228a by Serhiy Storchaka in branch 'master':
bpo-30158: Fix deprecation warnings in test_importlib introduced by bpo-29576. (bpo-1285)
https://github.com/python/cpython/commit/3cc8259b71ef784a9f7593f04da96043afe2228a
