### ISSUE TITLE
Testing FTP support in urllib shouldn't use Debian FTP server

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74350]
BPO | [30164](https://bugs.python.org/issue30164)
--- | :---
Nosy | @orsenthil, @serhiy-storchaka, @miss-islington
PRs | <li>python/cpython#25968</li><li>python/cpython#25969</li><li>python/cpython#25970</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/orsenthil'
closed_at = <Date 2021-05-07.13:50:48.703>
created_at = <Date 2017-04-26.04:50:03.025>
labels = ['3.7', 'type-bug', 'tests']
title = "Testing FTP support in urllib shouldn't use Debian FTP server"
updated_at = <Date 2021-05-07.14:12:57.185>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-07.14:12:57.185>
actor = 'miss-islington'
assignee = 'orsenthil'
closed = True
closed_date = <Date 2021-05-07.13:50:48.703>
closer = 'orsenthil'
components = ['Tests']
creation = <Date 2017-04-26.04:50:03.025>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30164
keywords = []
message_count = 3.0
messages = ['292299', '292300', '393184']
nosy_count = 3.0
nosy_names = ['orsenthil', 'serhiy.storchaka', 'miss-islington']
pr_nums = ['25968', '25969', '25970']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30164'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
test_urllib2net.py uses ftp://ftp.debian.org/ for testing FTP support in urllib. But Debian just announced shutting down its public FTP services.

https://lists.debian.org/debian-announce/2017/msg00001.html

**Comment by orsenthil** [comment]
I had started taking some action on it recently: https://github.com/python/pythondotorg/issues/1069 

I verified that only one test module is affected and rest of our ftp.debian.org references are examples/docstrings that will need to be updated eventually too.
