### ISSUE TITLE
Class Logger is unindented in the documentation.

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74354]
BPO | [30168](https://bugs.python.org/issue30168)
--- | :---
Nosy | @vsajip, @DimitrisJim
PRs | <li>python/cpython#1295</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-07.18:40:20.254>
created_at = <Date 2017-04-26.12:44:00.952>
labels = ['3.7', 'docs']
title = 'Class Logger is unindented in the documentation.'
updated_at = <Date 2017-05-07.18:40:20.253>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-07.18:40:20.253>
actor = 'vinay.sajip'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-07.18:40:20.254>
closer = 'vinay.sajip'
components = ['Documentation']
creation = <Date 2017-04-26.12:44:00.952>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 30168
keywords = []
message_count = 2.0
messages = ['292336', '293206']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'docs@python', 'Jim Fasarakis-Hilliard']
pr_nums = ['1295']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30168'
versions = ['Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Currently, `Logger` in `logging.rst` doesn't have an indent after `.. class:: Logger`. This causes the formatting for the specific section to look somewhat unexpected [1]. 

I've already created a PR that indents the methods/attributes accordingly. 

After @bitdancer's request, created this issue to get feedback from vinay if this was done on purpose.

[1]: https://docs.python.org/3/library/logging.html#logging.Logger

**Comment by vsajip** [comment]
New changeset 55ace65eba587fe3cf3759a43cccf85214651971 by Vinay Sajip (Jim Fasarakis-Hilliard) in branch 'master':
Closes bpo-30168: indent methods in Logger Class (bpo-1295)
https://github.com/python/cpython/commit/55ace65eba587fe3cf3759a43cccf85214651971
