### ISSUE TITLE
Import command-line parsing modules only when needed

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74352]
BPO | [30166](https://bugs.python.org/issue30166)
--- | :---
Nosy | @terryjreedy, @mitsuhiko, @berkerpeksag, @serhiy-storchaka, @iritkatriel
PRs | <li>python/cpython#1293</li><li>python/cpython#2098</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2020-09-19.15:36:00.414>
created_at = <Date 2017-04-26.08:34:19.633>
labels = ['type-feature', 'library']
title = 'Import command-line parsing modules only when needed'
updated_at = <Date 2020-09-19.15:36:00.414>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-19.15:36:00.414>
actor = 'serhiy.storchaka'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2020-09-19.15:36:00.414>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-26.08:34:19.633>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30166
keywords = []
message_count = 5.0
messages = ['292319', '292961', '292965', '295687', '377159']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'bethard', 'aronacher', 'berker.peksag', 'serhiy.storchaka', 'iritkatriel']
pr_nums = ['1293', '2098']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30166'
versions = ['Python 3.6']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Berker suggested to move this part from bpo-30152 to its own PR.

When the file can be imported as a module and run as a script it is worth to make command-line parsing modules (getopt, optparse, argparse) be imported only when they are used, i.e. when the file is ran as a script. Most of the stdlib modules already do this.

Proposed patch moves imports of command-line parsing modules and some other modules used only when the module is ran to the main() function or to the branch executed only if \_\_name__ == "\_\_main__". It doesn't change scripts and files that are purposed to be used only for running (__main__.py, main.py).

**Comment by serhiy-storchaka** [comment]
New changeset 7e4db2f253c555568d56177c2fd083bcf8f88d34 by Serhiy Storchaka in branch 'master':
bpo-30166: Import command-line parsing modules only when needed. (bpo-1293)
https://github.com/python/cpython/commit/7e4db2f253c555568d56177c2fd083bcf8f88d34

**Comment by terryjreedy** [comment]
I want to backport the idlelib.pyshell change.  I have been told that even a partial backport, even if done by hand, is a backport and the result a cherry-pick.

**Comment by terryjreedy** [comment]
New changeset c0ef607c52e58e94693fbedb27f2813bc3fed8fa by terryjreedy in branch '3.6':
[3.6] bpo-30166: backport pyshell changes ([GH 1293](https://github.com/python/cpython/pull/1293)) (bpo-2098)
https://github.com/python/cpython/commit/c0ef607c52e58e94693fbedb27f2813bc3fed8fa
