### ISSUE TITLE
Incorrect in referring to ISO as "International Standards Organization"

### ISSUE THREAD

**Issue by c39df839-4236-4a5f-8f32-0cce151c7f1f** [python/cpython#74368]
BPO | [30182](https://bugs.python.org/issue30182)
--- | :---
Nosy | @terryjreedy, @Mariatta, @mlouielu, @jessegonzalez
PRs | <li>python/cpython#1312</li><li>python/cpython#1313</li><li>python/cpython#1314</li><li>python/cpython#1315</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-27.05:26:28.068>
created_at = <Date 2017-04-27.02:50:12.378>
labels = ['easy', '3.7', 'docs']
title = 'Incorrect in referring to ISO as "International Standards Organization"'
updated_at = <Date 2017-04-27.05:45:36.457>
user = 'https://github.com/jessegonzalez'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-27.05:45:36.457>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-04-27.05:26:28.068>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-27.02:50:12.378>
creator = 'sifusam'
dependencies = []
files = []
hgrepos = []
issue_num = 30182
keywords = ['easy']
message_count = 8.0
messages = ['292389', '292390', '292399', '292400', '292401', '292402', '292403', '292404']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'docs@python', 'Mariatta', 'louielu', 'sifusam']
pr_nums = ['1312', '1313', '1314', '1315']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30182'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c39df839-4236-4a5f-8f32-0cce151c7f1f** [comment]
When reviewing the Unicode HOWTO, I found a reference to ISO as "International Standards Organization", which should instead read "International Organization for Standardization".

https://www.iso.org/home.html

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Add the link: 

Python 3: https://docs.python.org/3/howto/unicode.html
Python 2: https://docs.python.org/2/howto/unicode.html

Both of 2 and 3 howto unicode use "International Standards Organization"


Jesse, would you like to create a PR for this?

**Comment by c39df839-4236-4a5f-8f32-0cce151c7f1f** [comment]
PR created. CLA signed, but indicates otherwise in my account details.

**Comment by Mariatta** [comment]
New changeset 33a5568f69301562d536852d12b9e03cd8dfc3a4 by Mariatta in branch '3.6':
[3.6] bpo-30182: Use the correct name for ISO in Unicode HOWTO. (GH-1312) (GH-1313)
https://github.com/python/cpython/commit/33a5568f69301562d536852d12b9e03cd8dfc3a4

**Comment by Mariatta** [comment]
New changeset c4dfe2537fee970dc1bf3eb4fc2a3e007b36531c by Mariatta in branch '3.5':
[3.5] bpo-30182: Use the correct name for ISO in Unicode HOWTO. (GH-1312) (GH-1314)
https://github.com/python/cpython/commit/c4dfe2537fee970dc1bf3eb4fc2a3e007b36531c

**Comment by Mariatta** [comment]
New changeset 24404b4c92fc4195422c38563d0c6204fa7b16b1 by Mariatta in branch '2.7':
[2.7] bpo-30182: Use the correct name for ISO in Unicode HOWTO. (GH-1312). (bpo-1315)
https://github.com/python/cpython/commit/24404b4c92fc4195422c38563d0c6204fa7b16b1

**Comment by Mariatta** [comment]
Thanks :)

**Comment by terryjreedy** [comment]
Since I had the same wrong idea, I dug further into the site.
The explanation is at https://www.iso.org/about-us.html
'''
It's all in the name

Because 'International Organization for Standardization' would have different acronyms in different languages (IOS in English, OIN in French for Organisation internationale de normalisation), our founders decided to give it the short form ISO. ISO is derived from the Greek isos, meaning equal. Whatever the country, whatever the language, we are always ISO.
