### ISSUE TITLE
Duplicate code in pickletools.py

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#74360]
BPO | [30174](https://bugs.python.org/issue30174)
--- | :---
Nosy | @tim-one, @pitrou, @avassalotti, @serhiy-storchaka, @JelleZijlstra, @Mariatta
PRs | <li>python/cpython#1301</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-27.16:07:12.745>
created_at = <Date 2017-04-26.15:50:03.808>
labels = ['3.7', 'type-bug', 'library']
title = 'Duplicate code in pickletools.py'
updated_at = <Date 2017-04-27.16:07:12.744>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-27.16:07:12.744>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-27.16:07:12.745>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-26.15:50:03.808>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 30174
keywords = []
message_count = 6.0
messages = ['292364', '292366', '292367', '292370', '292457', '292459']
nosy_count = 6.0
nosy_names = ['tim.peters', 'pitrou', 'alexandre.vassalotti', 'serhiy.storchaka', 'JelleZijlstra', 'Mariatta']
pr_nums = ['1301']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30174'
versions = ['Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
The bytes1 ArgumentDescriptor is duplicated in pickletools.py.

**Comment by tim-one** [comment]
I already commented on github - +1 for this change.

**Comment by Mariatta** [comment]
Does this need to be backported?

**Comment by serhiy-storchaka** [comment]
The variant without " in the string" is more correct and consistent with bytes4 and bytes8.

The first bytes1 was added in bpo-16550. The duplicate was mistakenly added in bpo-17810.

This change can be backported, but it is not worth since the duplication doesn't have any effect.

**Comment by serhiy-storchaka** [comment]
New changeset 5a4e3d8f9c37e700402b23fafbfc413e5ca3113d by Serhiy Storchaka (Jelle Zijlstra) in branch 'master':
bpo-30174: Remove duplicate definition from pickletools (bpo-1301)
https://github.com/python/cpython/commit/5a4e3d8f9c37e700402b23fafbfc413e5ca3113d

**Comment by serhiy-storchaka** [comment]
Thank you for catching this Jelle!
