### ISSUE TITLE
Correct the parsing of a test case docstring.

### ISSUE THREAD

**Issue by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [python/cpython#74367]
BPO | [30181](https://bugs.python.org/issue30181)
--- | :---
Nosy | @bitdancer, @cjerdonek, @brianmay, @mlouielu
PRs | <li>python/cpython#1505</li>
Superseder | <li>bpo-39450: unittest TestCase shortDescription does not strip whitespace</li>
Files | <li>[test_foo.py](https://bugs.python.org/file46831/test_foo.py "Uploaded as text/plain at 2017-04-27.02:44:33 by benf_wspdigital"): Unit tests demonstrating the problem</li><li>[issue30181-fix.cfc063a9.tar.gz](https://bugs.python.org/file46859/issue30181-fix.cfc063a9.tar.gz "Uploaded as application/x-gzip at 2017-05-12.07:12:22 by benf_wspdigital"): Implementation fixing this issue, patches up to commit cfc063a9</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-25.21:47:01.731>
created_at = <Date 2017-04-27.02:44:34.655>
labels = ['3.7', 'type-feature', 'library']
title = 'Correct the parsing of a test case docstring.'
updated_at = <Date 2020-10-25.21:47:01.730>
user = 'https://bugs.python.org/benfwspdigital'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-25.21:47:01.730>
actor = 'chris.jerdonek'
assignee = 'none'
closed = True
closed_date = <Date 2020-10-25.21:47:01.731>
closer = 'chris.jerdonek'
components = ['Library (Lib)']
creation = <Date 2017-04-27.02:44:34.655>
creator = 'benf_wspdigital'
dependencies = []
files = ['46831', '46859']
hgrepos = []
issue_num = 30181
keywords = []
message_count = 21.0
messages = ['292387', '292396', '292406', '292427', '292649', '292650', '292651', '292652', '292654', '293268', '293271', '293522', '293523', '293525', '293527', '293528', '293561', '293681', '293804', '378297', '379612']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'chris.jerdonek', 'brian', 'louielu', 'benf_wspdigital']
pr_nums = ['1505']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '39450'
type = 'enhancement'
url = 'https://bugs.python.org/issue30181'
versions = ['Python 3.7']
```

</p></details>

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
The docstring of a test case is not correctly parsed for display.

The attached ‘test_foo.py’ module contains two test case functions. Both docstrings conform to PEP-257 \<https://www.python.org/dev/peps/pep-0257/\>: they have a single-line synopsis and some extra text in a new paragraph.

However, only one of the functions has its docstring synopsis used in the output:

\=====
\======================================================================
FAIL: test_lower_returns_expected_code (test_foo.Foo_TestCase)
Should return expected code.
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
[…]
```


======================================================================
FAIL: test_reverse_returns_expected_text (test_foo.Foo_TestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
[…]
```


----------------------------------------------------------------------
Ran 2 tests in 0.001s
\=====

This violates the docstring parsing as described in PEP-257. The synopsis should be obtained by, first, stripping leading and trailing whitespace from the docstring; then, from that stripped text, taking the first line as the synopsis.

So the expected output for ‘test_foo.Foo_TestCase. test_reverse_returns_expected_text’ should include its docstring synopsis, “Should return expected reverse text.”

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
This is because unittest.TestCase method `shortDescription()` will only return the first line of docstring, writing at here*:

"""
The default implementation of this method returns the first line of the test method’s docstring, if available, or None.
"""

Not sure if we may change this default behavior for this.



* https://docs.python.org/3/library/unittest.html#unittest.TestCase.shortDescription

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
> This is because unittest.TestCase method `shortDescription()` will only return the first line of docstring

Yes, that is the “docstring synopsis” I referred to. PEP-257 has a section specifically about how tools should parse a docstring: https://www.python.org/dev/peps/pep-0257/#handling-docstring-indentation

In particular, note that “ Blank lines should be removed from the beginning and end of the docstring.”

So, the “first line of the docstring“ for the example ‘test_reverse_returns_expected_text’ is the text “Should return expected reverse text.”.

**Comment by bitdancer** [comment]
Considering that in the cpython test suite we avoid using docstrings in unittests because of this "feature" of unittest, I doubt anyone on the core team is going to be motivated to fix this :)  That doesn't mean we won't accept a PR, but if we do we would only put it in 3.7 because it is a visible behavior change, and there are tools that parse unittest output.

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
Howdy R. David,

Okay, I have put together a series of commits to address this bug. The
changes are in my personal fork of the ‘cpython’ repository, so this is
a pull request from ‘wip/issue/issue30181_parse-docstring-using-pydoc’
in that repository.

The following changes since commit 8550803dfba4cf7018ee7415593ceb34c52923e6:

  Backed out changeset f23fa1f7b68f (2017-02-10 14:19:36 +0100)

are available in the git repository at:

  https://benf_wspdigital@bitbucket.org/benf_wspdigital/cpython.git

```py
for you to fetch changes up to c2de731582a9da1147a300a991890ff663891e75:
```


  Parse the test case docstring using `pydoc.splitdoc`. (2017-05-01 16:55:52 +1000)

\----------------------------------------------------------------
(from the branch description for wip/issue/issue30181_parse-docstring-using-pydoc local branch)

Correct the parsing of a test case docstring.

\----------------------------------------------------------------
Ben Finney (4):
      Add test cases for single-line test case docstring.
      Add test cases for stripping surrounding space for shortDescription.
      Add test cases for test case docstring with surrounding newlines.
      Parse the test case docstring using `pydoc.splitdoc`.

 [Lib/unittest/case.py](https://github.com/python/cpython/blob/main/Lib/unittest/case.py)                       | 34 ++++++++++++\------
 [Lib/unittest/test/test_case.py](https://github.com/python/cpython/blob/main/Lib/unittest/test/test_case.py)             | 42 ++++++++++++++++++++++
 [Lib/unittest/test/test_functiontestcase.py](https://github.com/python/cpython/blob/main/Lib/unittest/test/test_functiontestcase.py) | 58 +++++++++++++++++++++++++\-----
 3 files changed, 115 insertions(+), 19 deletions(-)

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Ben, the process of submitting PR was migrated to GitHub, you will need to use a GitHub account to do it.

You can refer to [devguide](https://devguide.python.org) for how to submit a PR here:

http://cpython-devguide.readthedocs.io/pullrequest.html

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
On 2017-05-01 17:45, Louie Lu wrote:
> Ben, the process of submitting PR was migrated to GitHub

Thank you. I'll re-base my branch onto the master branch found at the GitHub repository.

> you will need to use a GitHub account to do it

I don't maintain repositories at GitHub. Does that mean the contribution must be rejected?

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
> Thank you. I'll re-base my branch onto the master branch found at the GitHub repository.

You may re-clone a GitHub repository instead of rebase bitbucket repo.


> I don't maintain repositories at GitHub. Does that mean the contribution must be rejected?

No, your contribution will not be rejected by "you don't maintain the repo on GitHub", everyone can send the patch (PR) to python/cpython.

you will need to fork python/cpython from GitHub first, this will create a fork in your GitHub account, maybe benf/cpython if your GitHub account is benf, and then clone this repo (benf/cpython), the rest step please see the instruction in [devguide](https://devguide.python.org) !

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Ben, if you have any problem about how to get on with GitHub, I can help you at #python-dev @ freenode, ping louielu on the chatroom.

**Comment by 8771ced3-5f01-4f3c-9b5c-4c5072809ab7** [comment]
I made an attempt at a PR. Unfortunately some of the tests appear to fail on some environments, and the messages produced don't exactly clarify why.

**Comment by 8771ced3-5f01-4f3c-9b5c-4c5072809ab7** [comment]
Me getting confused at the newline in the comparison output.

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
Apparently there is some consternation about my bugs.python.org identity. This is Ben Finney of WSP Digital, in Melbourne, Australia.

A GitHub account is wholly irrelevant to this account. A GitHub account is wholly irrelevant to accepting the PSF CLA.

This bugs.python.org account `benf_wspdigital` does not mention a GitHub account, and that's the way I want to keep it.

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
> No, your contribution will not be rejected by "you don't maintain the repo on GitHub", everyone can send the patch (PR) to python/cpython.

I am glad to know that. I won't be maintaining a GitHub account because I disagree with the terms of service.

> Ben, if you have any problem about how to get on with GitHub, I can help you […]

Thank you for the offer. My problem with how to get on with GitHub is I don't accept their terms of service :-) How do we proceed?

Git is a \*decentralised* VCS, it should not be a barrier that I make the contribution from a different repository host.

**Comment by bitdancer** [comment]
Our tooling and workflow is indeed dependent on github.  We should repurpose the current 'remote hg repo' to allow the entry of a non-github git repo, but someone will have to write that code.  In the meantime, if you upload a patch generated from your branch here, someone else will create the github PR so we can get it processed.  If you generate the patch using 'git show -v', the authorship information should get imported into the github PR that gets generated.

**Comment by 8771ced3-5f01-4f3c-9b5c-4c5072809ab7** [comment]
I have already created such a pull requests. It is bidirectionally linked to this ticket.

However concerns have been raised that the automatic bot hasn't recognised that Ben Finney has signed the CLA. Hence it appears the pull request might be rejected.

Sure there are currently problems with the pull request, and it fails the tests, however I am not going to spend any additional efforts fixing them unless this situation with the CLA can be resolved first.

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
> if you upload a patch generated from your branch here, someone else will create the github PR so we can get it processed.

The branch has several commits. I have generated the patches, and am now uploading them as a tarball.

It may be easier to simply merge from the Git branch, https://rocketgit.com/user/benf_wspdigital/cpython/source/log/branch/wip,issue,issue30181_parse-docstring-using-pydoc

**Comment by bitdancer** [comment]
Ah, yes, that's a bug in our workflow we'll need to fix.  The CLA signed on the bug tracker is the ultimate authority, so we need some way to manually bypass the bot for cases like this.

A committer should be able to bypass the problem and get the patch pushed, once it is approved.

**Comment by b0d32f06-35f7-4ea4-9bc4-869b80a2335b** [comment]
> I have already created such a pull requests. It is bidirectionally linked to this ticket.

I hope the PSF can start accepting contributions without that laundering, but until then: thank you for taking that on.

**Comment by bitdancer** [comment]
It's not the PSF, it's the dev team, and it is "just" a matter of tooling.  Which means help improving the tooling is welcome :)
