### ISSUE TITLE
curses attribute constants list is incomplete

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74362]
BPO | [30176](https://bugs.python.org/issue30176)
--- | :---
Nosy | @Yhg1s, @vstinner, @berkerpeksag, @serhiy-storchaka, @zhangyangyu, @Mariatta
PRs | <li>python/cpython#1302</li><li>python/cpython#2241</li><li>python/cpython#2277</li><li>python/cpython#2278</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-19.14:13:28.288>
created_at = <Date 2017-04-26.16:10:21.307>
labels = ['3.7', 'docs']
title = 'curses attribute constants list is incomplete'
updated_at = <Date 2017-06-19.14:13:28.287>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-19.14:13:28.287>
actor = 'xiang.zhang'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-19.14:13:28.288>
closer = 'xiang.zhang'
components = ['Documentation']
creation = <Date 2017-04-26.16:10:21.307>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30176
keywords = []
message_count = 9.0
messages = ['292375', '292377', '292379', '292388', '296155', '296195', '296341', '296342', '296343']
nosy_count = 7.0
nosy_names = ['twouters', 'vstinner', 'docs@python', 'berker.peksag', 'serhiy.storchaka', 'xiang.zhang', 'Mariatta']
pr_nums = ['1302', '2241', '2277', '2278']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30176'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Initially constants was enumerated in alphabetical order (except A_ITALIC). Maybe continue supporting this order? On other hand, it may be worth to group highlighting attributes separately. A_ATTRIBUTES, A_CHARTEXT and A_COLOR are not specific attributes, but bit masks, they also could be grouped separately or moved into a separate table.

Perhaps it is worth to add notes for A_ITALIC and highlighting attributes. They are not always available.

**Comment by zhangyangyu** [comment]
+1 for group. I added "The exact constants available are system dependent" to note some may be absent.

**Comment by serhiy-storchaka** [comment]
I still think that the difference between the groups should be documented in more details. Not all functions that support A_BOLD support also A_ITALIC and A_HORIZONTAL (even if they are defined). Bit masks are used in totally different way than other constants.

**Comment by zhangyangyu** [comment]
I can't find any official, portable doc about the details so I don't prefer to have them. I support bit-masks are different. Previously I don't what's the better way to organize them, now I have a try. Please check the update. :-)

**Comment by Mariatta** [comment]
New changeset 116dd5eba60a940b35db6aaf4e8c998ac30ad440 by Mariatta (Xiang Zhang) in branch 'master':
bpo-30176: Add missing curses cell attributes constants (GH-1302)
https://github.com/python/cpython/commit/116dd5eba60a940b35db6aaf4e8c998ac30ad440

**Comment by Mariatta** [comment]
New changeset 304a96e5868c1b38a87692668f297aaf041e6e67 by Mariatta in branch '3.6':
bpo-30176: Add missing curses cell attributes constants (GH-1302). (GH-2241)
https://github.com/python/cpython/commit/304a96e5868c1b38a87692668f297aaf041e6e67

**Comment by zhangyangyu** [comment]
New changeset 04521c275e47e4df59046ee0297810f06c208350 by Xiang Zhang in branch '3.5':
bpo-30176: Add missing curses cell attributes constants (bpo-2277)
https://github.com/python/cpython/commit/04521c275e47e4df59046ee0297810f06c208350

**Comment by zhangyangyu** [comment]
New changeset b39a7481ee7e6166d6d2b252a7a514b1f6553dfa by Xiang Zhang in branch '2.7':
bpo-30176: Add missing curses cell attributes constants (bpo-2278)
https://github.com/python/cpython/commit/b39a7481ee7e6166d6d2b252a7a514b1f6553dfa

**Comment by zhangyangyu** [comment]
Thanks Mariatta and Serhiy!
