### ISSUE TITLE
Indent methods and attributes of MimeTypes class

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74364]
BPO | [30178](https://bugs.python.org/issue30178)
--- | :---
Nosy | @DimitrisJim, @Mariatta
PRs | <li>python/cpython#1306</li><li>python/cpython#1570</li><li>python/cpython#1571</li><li>python/cpython#1572</li><li>python/cpython#1801</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.17:14:57.191>
created_at = <Date 2017-04-26.17:13:34.720>
labels = ['3.7', 'docs']
title = 'Indent methods and attributes of MimeTypes class'
updated_at = <Date 2017-05-25.17:14:57.189>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-25.17:14:57.189>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-25.17:14:57.191>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-26.17:13:34.720>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 30178
keywords = []
message_count = 6.0
messages = ['292374', '293615', '293616', '293618', '293623', '294500']
nosy_count = 3.0
nosy_names = ['docs@python', 'Jim Fasarakis-Hilliard', 'Mariatta']
pr_nums = ['1306', '1570', '1571', '1572', '1801']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30178'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Similar to bpo-30168 opened earlier. The MimeTypes class's methods and attributes aren't indented and the resulting documentation is not indented and duplicates the class name. 

Didn't find anything that might indicate this was intentional when trying to blame this change. It seems to have happened at some point between 2.6 [1] and 2.7 [2], though, where the class directive was moved to the MimeTypes Objects section. Also didn't find an expert for this module in the index. 

Proposed change just indents these. 

[1]: https://github.com/python/cpython/blame/2.6/Doc/library/mimetypes.rst
[2]: https://github.com/python/cpython/blame/2.7/Doc/library/mimetypes.rst

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
bump

**Comment by Mariatta** [comment]
New changeset c71168090df435c1eb8c03005b11df764cd7ebd6 by Mariatta (Jim Fasarakis-Hilliard) in branch 'master':
bpo-30178: Indent methods and attributes of MimeType class (GH-1306)
https://github.com/python/cpython/commit/c71168090df435c1eb8c03005b11df764cd7ebd6

**Comment by Mariatta** [comment]
New changeset 600c5ad53c0112d48581c48f986ea04676a28c44 by Mariatta in branch 'master':
bpo-30178: Add Jim Fasarakis-Hilliard to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS) (GH-1572)
https://github.com/python/cpython/commit/600c5ad53c0112d48581c48f986ea04676a28c44

**Comment by Mariatta** [comment]
Jim, are you up for preparing the backport to 2.7?
I came across a conflict while doing so with cherry_picker.py, and don't have the bandwidth to resolve it for now.
Otherwise, I'll look into the 2.7 backport after PyCon.
Thanks :)

**Comment by Mariatta** [comment]
Thanks Jim and Stéphane.
