### ISSUE TITLE
<COMObject <unknown>>

### ISSUE THREAD

**Issue by d9f7de3e-b052-4376-a5e0-603a9dce5795** [python/cpython#74377]
BPO | [30191](https://bugs.python.org/issue30191)
--- | :---
Nosy | @eryksun

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-27.20:47:33.991>
created_at = <Date 2017-04-27.20:33:06.852>
labels = ['interpreter-core', 'performance']
title = '<COMObject <unknown>>'
updated_at = <Date 2017-04-27.20:47:33.989>
user = 'https://bugs.python.org/SogandKa'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-27.20:47:33.989>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-27.20:47:33.991>
closer = 'eryksun'
components = ['Interpreter Core']
creation = <Date 2017-04-27.20:33:06.852>
creator = 'Sogand Ka'
dependencies = []
files = []
hgrepos = []
issue_num = 30191
keywords = []
message_count = 2.0
messages = ['292479', '292480']
nosy_count = 2.0
nosy_names = ['eryksun', 'Sogand Ka']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30191'
versions = ['Python 2.7']
```

</p></details>

**Comment by d9f7de3e-b052-4376-a5e0-603a9dce5795** [comment]
I am using COM in python 2.7 (win32com) and here is my problem:

```pycon
>>> Vissim
<COMObject Vissim.Vissim.800>
>>> Vissim.Net
<COMObject <unknown>>
```


why is it unknown? 
Also, I have to type everything in shell, since it does not show me the keywords. Would be great to see any helpful suggestion.

**Comment by eryksun** [comment]
This issue tracker is only for CPython. win32com is part of PyWin32, which is an independent project that's hosted at the following SourceForge site:

https://sourceforge.net/projects/pywin32

I suggest that you ask for help on the python-win32 list:

https://mail.python.org/mailman/listinfo/python-win32
