### ISSUE TITLE
forkserver process should silence KeyboardInterrupt

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74371]
BPO | [30185](https://bugs.python.org/issue30185)
--- | :---
Nosy | @rhettinger, @pitrou, @vstinner, @applio
PRs | <li>python/cpython#1319</li><li>python/cpython#1454</li><li>python/cpython#1455</li>
Files | <li>[forkserversignal.py](https://bugs.python.org/file46832/forkserversignal.py "Uploaded as text/plain at 2017-04-27.10:53:01 by @pitrou")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-04.15:17:42.999>
created_at = <Date 2017-04-27.10:51:47.621>
labels = ['3.7', 'type-bug', 'library']
title = 'forkserver process should silence KeyboardInterrupt'
updated_at = <Date 2017-05-04.16:19:48.010>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-04.16:19:48.010>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-04.15:17:42.999>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-04-27.10:51:47.621>
creator = 'pitrou'
dependencies = []
files = ['46832']
hgrepos = []
issue_num = 30185
keywords = []
message_count = 11.0
messages = ['292420', '292421', '292422', '292425', '292426', '292983', '292986', '292989', '292996', '292997', '292998']
nosy_count = 5.0
nosy_names = ['rhettinger', 'pitrou', 'vstinner', 'sbt', 'davin']
pr_nums = ['1319', '1454', '1455']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30185'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
The forkserver intermediate process is an implementation detail.  However, if you Ctrl-C the main process, the forkserver process will exit with a KeyboardInterrupt traceback, even if the main process catches KeyboardInterrupt to exit silently.  This produces stderr such as:

```pytb
$ ./python forkserversignal.py 
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/antoine/cpython/default/Lib/multiprocessing/forkserver.py", line 164, in main
    rfds = [key.fileobj for (key, events) in selector.select()]
  File "/home/antoine/cpython/default/Lib/selectors.py", line 445, in select
    fd_event_list = self._epoll.poll(timeout, max_ev)
KeyboardInterrupt
```



For the sake of usability, forkserver should probably silence those tracebacks by default, for example by changing the default signal handler in the forkserver process (but children forked by the forkserver process should probably get the default Python signal handlers...).

Not sure this can be considered a bugfix or an enhancement.

**Comment by pitrou** [comment]
Uploading small reproducer script.

**Comment by pitrou** [comment]
A simpler solution would actually be to catch KeyboardInterrupt inside the forkserver loop and exit cleanly...

**Comment by vstinner** [comment]
> A simpler solution would actually be to catch KeyboardInterrupt inside the forkserver loop and exit cleanly...

I'm not sure that we always want to exit on CTRL-c. But I agree that the forkserver has to handle CTRL-c. Maybe ignore it, but be killed when its master gets a CTRL-c?

**Comment by pitrou** [comment]
> I'm not sure that we always want to exit on CTRL-c.

That's what the forkserver does right now, it's just that it does it with a traceback that's useless to the user.

> Maybe ignore it, but be killed when its master gets a CTRL-c?

That's a possibility (the forkserver should already exit automatically when its parent dies), the problem is what to do for the forkserver's children?  Should they restore the default signal handler?

Simply silencing the KeyboardInterrupt traceback at least is a straightforward solution with little risk of side effects.

**Comment by pitrou** [comment]
New changeset 6dd4d734ed207ba16b017e38f8909de7ef187e29 by Antoine Pitrou in branch 'master':
bpo-30185: avoid KeyboardInterrupt tracebacks in forkserver (bpo-1319)
https://github.com/python/cpython/commit/6dd4d734ed207ba16b017e38f8909de7ef187e29

**Comment by pitrou** [comment]
New changeset a7e48b544becc01dbf9059ed01f38997c6d0156c by Antoine Pitrou in branch '3.6':
[3.6] bpo-30185: avoid KeyboardInterrupt tracebacks in forkserver (GH-1319) (bpo-1454)
https://github.com/python/cpython/commit/a7e48b544becc01dbf9059ed01f38997c6d0156c

**Comment by pitrou** [comment]
New changeset 7299088ccf5f72b8494063814b58a180b4250aa7 by Antoine Pitrou in branch '3.5':
[3.5] bpo-30185: avoid KeyboardInterrupt tracebacks in forkserver (GH-1319) (bpo-1455)
https://github.com/python/cpython/commit/7299088ccf5f72b8494063814b58a180b4250aa7

**Comment by vstinner** [comment]
Python 2.7 isn't affected by this bug?

**Comment by pitrou** [comment]
There is no forkserver in 2.7.

**Comment by vstinner** [comment]
> There is no forkserver in 2.7.

Oh right, it's specific to forkserver, ok ;-) Thank you for the fix.
