### ISSUE TITLE
unittest's assertAlmostEqual improved error message

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#74376]
BPO | [30190](https://bugs.python.org/issue30190)
--- | :---
Nosy | @rhettinger, @giampaolo, @rbtcollins, @ezio-melotti, @voidspace, @serhiy-storchaka
PRs | <li>python/cpython#1331</li><li>python/cpython#1534</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-25.21:06:29.071>
created_at = <Date 2017-04-27.20:12:42.186>
labels = ['3.7', 'type-feature', 'library']
title = "unittest's assertAlmostEqual improved error message"
updated_at = <Date 2017-07-25.21:06:29.069>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-25.21:06:29.069>
actor = 'giampaolo.rodola'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-25.21:06:29.071>
closer = 'giampaolo.rodola'
components = ['Library (Lib)']
creation = <Date 2017-04-27.20:12:42.186>
creator = 'giampaolo.rodola'
dependencies = []
files = []
hgrepos = []
issue_num = 30190
keywords = []
message_count = 14.0
messages = ['292477', '292482', '292510', '292537', '292540', '292548', '292668', '293350', '293415', '293416', '293417', '293418', '299138', '299140']
nosy_count = 6.0
nosy_names = ['rhettinger', 'giampaolo.rodola', 'rbcollins', 'ezio.melotti', 'michael.foord', 'serhiy.storchaka']
pr_nums = ['1331', '1534']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30190'
versions = ['Python 3.7']
```

</p></details>

**Comment by giampaolo** [comment]
When comparing 2 numbers as "self.assertAlmostEqual(a, b, delta=1000)" the error message looks like this:

    AssertionError: 27332885 != 27391120 within 1000 delta

Especially when a and b are big numbers or differ a lot, it would be useful to see the absolute difference between the 2 numbers as in:

    AssertionError: 27332885 != 27391120 within 1000 delta (58235 difference)

**Comment by giampaolo** [comment]
PR: https://github.com/python/cpython/pull/1331/

**Comment by serhiy-storchaka** [comment]
Is it worth to output a difference when the delta argument is not passed?

Is it worth to output a signed difference rather than an absolute value?

**Comment by giampaolo** [comment]
Thanks for chiming in.

> Is it worth to output a difference when the delta argument is not passed?

Yes, probably. I will change that.

> Is it worth to output a signed difference rather than an absolute value?

Mmmm probably not IMHO. Personally I never care about the position of left and right arguments. I just want to check whether a and b are almost equal.

**Comment by giampaolo** [comment]
Done.

**Comment by rhettinger** [comment]
The patch looks good to me.

**Comment by giampaolo** [comment]
New changeset 5d7a8d0c13737fd531b722ad76c505ef47aac96a by Giampaolo Rodola in branch 'master':
bpo-30190: improved error msg for assertAlmostEqual(delta=...) (bpo-1331)
https://github.com/python/cpython/commit/5d7a8d0c13737fd531b722ad76c505ef47aac96a

**Comment by serhiy-storchaka** [comment]
New test produce deprecation warnings:

/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:228: DeprecationWarning: invalid escape sequence \\(
  ["^1 != 2 within 7 places \\(1 difference\\)$", "^oops$",
/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:229: DeprecationWarning: invalid escape sequence \\(
  "^1 != 2 within 7 places \\(1 difference\\)$",
/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:230: DeprecationWarning: invalid escape sequence \\(
  "^1 != 2 within 7 places \\(1 difference\\) : oops$"])

**Comment by giampaolo** [comment]
Mmm I can't see them. Am I supposed to enable this kind of warning somehow?

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -Wa Lib/unittest/test/test_assertions.py
Lib/unittest/test/test_assertions.py:228: DeprecationWarning: invalid escape sequence \(
  ["^1 != 2 within 7 places \(1 difference\)$", "^oops$",
Lib/unittest/test/test_assertions.py:229: DeprecationWarning: invalid escape sequence \(
  "^1 != 2 within 7 places \(1 difference\)$",
Lib/unittest/test/test_assertions.py:230: DeprecationWarning: invalid escape sequence \(
  "^1 != 2 within 7 places \(1 difference\) : oops$"])
...................................
```

----------------------------------------------------------------------
Ran 35 tests in 0.052s

OK

**Comment by serhiy-storchaka** [comment]
Warnings are not shown when the source is already compiled to .pyc file.

```sh
$ find -name '*.py[co]' -exec rm '{}' +
$ ./python -Wa -m test test_unittest
Run tests sequentially
0:00:00 load avg: 0.54 [1/1] test_unittest
/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:228: DeprecationWarning: invalid escape sequence \(
  ["^1 != 2 within 7 places \(1 difference\)$", "^oops$",
/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:229: DeprecationWarning: invalid escape sequence \(
  "^1 != 2 within 7 places \(1 difference\)$",
/home/serhiy/py/cpython/Lib/unittest/test/test_assertions.py:230: DeprecationWarning: invalid escape sequence \(
  "^1 != 2 within 7 places \(1 difference\) : oops$"])
1 test OK.
```


Total duration: 5 sec
Tests result: SUCCESS

**Comment by giampaolo** [comment]
OK thanks. Fix coming.

**Comment by giampaolo** [comment]
Reopening as it needs backports for 2.7, 3.3, 3.4, 3.5 and 3.6.

**Comment by giampaolo** [comment]
Sorry, I accidentally picked up the wrong thread.
