### ISSUE TITLE
Enhance swap_attr() and swap_item() in test.support

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74383]
BPO | [30197](https://bugs.python.org/issue30197)
--- | :---
Nosy | @vstinner, @ezio-melotti, @voidspace, @serhiy-storchaka
PRs | <li>python/cpython#1341</li><li>python/cpython#1345</li><li>python/cpython#1346</li><li>python/cpython#1347</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-28.17:07:22.174>
created_at = <Date 2017-04-28.11:06:00.937>
labels = ['3.7', 'type-feature', 'tests']
title = 'Enhance swap_attr() and swap_item() in test.support'
updated_at = <Date 2020-10-06.10:48:50.555>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-06.10:48:50.555>
actor = 'wburchill7'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-28.17:07:22.174>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-04-28.11:06:00.937>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30197
keywords = []
message_count = 6.0
messages = ['292527', '292536', '292539', '292541', '292542', '378109']
nosy_count = 5.0
nosy_names = ['vstinner', 'ezio.melotti', 'michael.foord', 'serhiy.storchaka', 'wburchill7']
pr_nums = ['1341', '1345', '1346', '1347']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30197'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch adds two features to functions swap_attr() and swap_item() in the test.support module.

1. They now work (rather than failing in \_\_exit__) when delete the attribute or item inside the with block. There were several cases when I refused to use these functions instead of manually coded try/finally due to lack of this feature.

2. The original value of the attribute or item can be assigned to the target of "as" in the with statement. This can save a line of the code in some cases.

**Comment by vstinner** [comment]
New changeset d1a1def7bf221b04dcf3fc3a67aa19aa2f622f83 by Victor Stinner (Serhiy Storchaka) in branch 'master':
bpo-30197: Enhance functions swap_attr() and swap_item() in test.support. (bpo-1341)
https://github.com/python/cpython/commit/d1a1def7bf221b04dcf3fc3a67aa19aa2f622f83

**Comment by serhiy-storchaka** [comment]
New changeset 712114b3f9f5f98f03c66a80607b6f7101c5cc90 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30197: Enhance functions swap_attr() and swap_item() in test.support. (GH-1341) (bpo-1345)
https://github.com/python/cpython/commit/712114b3f9f5f98f03c66a80607b6f7101c5cc90

**Comment by serhiy-storchaka** [comment]
New changeset 910ba937e90ffe3aa154a5b27dc7e2c3d3c88d1f by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30197: Enhance functions swap_attr() and swap_item() in test.support. (bpo-1341) (bpo-1346)
https://github.com/python/cpython/commit/910ba937e90ffe3aa154a5b27dc7e2c3d3c88d1f

**Comment by serhiy-storchaka** [comment]
New changeset 941ea53b5776aaeb9dc1026e482a4ce5c5768830 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30197: Enhance swap_attr() and backport swap_item() in test.test_support. (bpo-1341) (bpo-1347)
https://github.com/python/cpython/commit/941ea53b5776aaeb9dc1026e482a4ce5c5768830
