### ISSUE TITLE
writing non-ascii characters in xml file using python code embedded in C

### ISSUE THREAD

**Issue by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [python/cpython#74381]
BPO | [30195](https://bugs.python.org/issue30195)
--- | :---
Nosy | @malemburg, @vstinner, @benjaminp, @ezio-melotti, @serhiy-storchaka, @zhangyangyu
Files | <li>[write_to_xml1.py](https://bugs.python.org/file46841/write_to_xml1.py "Uploaded as text/plain at 2017-04-29.14:16:06 by aimad")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-16.13:14:27.836>
created_at = <Date 2017-04-28.10:14:52.815>
labels = ['expert-XML', 'type-bug', 'invalid']
title = 'writing non-ascii characters in xml file using python code embedded in C'
updated_at = <Date 2017-05-16.15:08:57.404>
user = 'https://bugs.python.org/aimad'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-16.15:08:57.404>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-16.13:14:27.836>
closer = 'aimad'
components = ['XML']
creation = <Date 2017-04-28.10:14:52.815>
creator = 'aimad'
dependencies = []
files = ['46841']
hgrepos = []
issue_num = 30195
keywords = []
message_count = 9.0
messages = ['292521', '292523', '292594', '292630', '292631', '292633', '292634', '292639', '293761']
nosy_count = 7.0
nosy_names = ['lemburg', 'vstinner', 'benjamin.peterson', 'ezio.melotti', 'serhiy.storchaka', 'xiang.zhang', 'aimad']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30195'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
my python code embedded in C program, uses etree from lxml to write a plain string as element attribute in xml file. the problem is when my string contains non english characters(non ascii), the program fails to write even with unicode conversion such as unicode(mystring, "utf-8"), but when I use python code only, it works.

**Comment by serhiy-storchaka** [comment]
lxml is not the part of the Python standard library. Use lxml bug tracker if your issue is specific for lxml.

If you can reproduce the issue with xml.etree.ElementTree from the stdlib, please provide a simple example code that does this.

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
I have just tried to do this task using xml.etree.ElementTree and still have the same problem.
In the file 'write_to_xml1.py' I'm trying to develop some function that creates an xml file and then add data containing non ascii characters.The python program works perfectly, but when I tried to call  these functions from C, the program crashes.Note that this problem dosn't happen when adding ascii characters only.Here is the C program :

```c
void create_report()
{
	PyObject *pName, *pModule, *pDict, *pFunc, *pValue, *pArgs;

    // Initialize the Python Interpreter
    Py_Initialize();
```


    // Build the name object
    pName = PyString_FromString("write_to_xml1");
    // Load the module object
    pModule = PyImport_Import(pName);

    // pDict is a borrowed reference 
    pDict = PyModule_GetDict(pModule);

    // pFunc is also a borrowed reference 
    pFunc = PyDict_GetItemString(pDict,"create_report");

```c
	if (PyCallable_Check(pFunc)) 
    {
		PyObject_CallObject(pFunc,NULL);	
    } else 
    {
        PyErr_Print();
    }

}
void modif_report()
{
	PyObject *pName, *pModule, *pDict, *pFunc, *pValue, *pArgs;

    // Initialize the Python Interpreter
    Py_Initialize();

    // Build the name object
    pName = PyString_FromString("write_to_xml1");
    // Load the module object
    pModule = PyImport_Import(pName);
    // pDict is a borrowed reference 
    pDict = PyModule_GetDict(pModule);
    // pFunc is also a borrowed reference 
    pFunc = PyDict_GetItemString(pDict,"traite");
	if (PyCallable_Check(pFunc)) 
    {
		PyObject_CallObject(pFunc,NULL);	
    } else 
    {
        PyErr_Print();
    }
```


}

```c
int main(int argc, char *argv[])
{
	create_report();
	modif_report();
        return(0);
}      // end main()
```

**Comment by zhangyangyu** [comment]
IMHO this doesn't look like an error in xml library. With a little tweak in of your problem: adding encoding declaration, removing not needed imports, replace open with codecs.open(encoding='utf8') in create_report, the C problem works fine for me:

[tmp]$ cat essai_rapport_test_30-04-2017-22-22_你好.xml
\<?xml version="1.0" ?\>
\<rapport_test date="2017-04-30" langue="你好" nb_correcte="你好" nb_incorrecte="abc" time="22:22:46"/\>

xml_file.write(doc.toprettyxml()) fails for me since ascii codecs cannot encode the result of doc.toprettyxml, a unicode. And I would suggest you adding failure checks to your C program. Almost every step could fail and then result in a segfault.

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
Thank you xiang zhang for your reply.
I think that the problem is not in xml_file.write(doc.toprettyxml()) because it works using python only, and the C problem dosen't work since you didn't get any 'alerte' balise.

**Comment by zhangyangyu** [comment]
But I didn't see any crash either. You'd better provide a simple reproduce program, not involving so much logic. Or could you debug it and provide a crash backtrace?

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
Also, using codecs.open(encoding='utf8') gives unhadled exception in C? but no problem using python code only.

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
Probably it's my fault to use the word 'crash', what I mean is that generated report by python program contains the right result(the 'alerte' balise is added) but the other report generated by the same python program embedde in C didn't give the right result (report is created but no 'alerte' balise is added)

**Comment by 1a512287-30d6-46b5-83d3-e5b0bdeaf2e7** [comment]
problem solved, It's not related to embedding python in C, Ijust had to use mystring.decode('utf-8') instead of unicode(mystring,"utf-8")
