### ISSUE TITLE
socket.setblocking(0) changes socket.type

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#74390]
BPO | [30204](https://bugs.python.org/issue30204)
--- | :---
Nosy | @giampaolo, @vadmium
Superseder | <li>bpo-21327: socket.type value changes after using settimeout()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-04-29.09:31:34.033>
created_at = <Date 2017-04-29.08:23:43.135>
labels = ['3.7', 'library']
title = 'socket.setblocking(0) changes socket.type'
updated_at = <Date 2017-04-29.09:31:34.031>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-29.09:31:34.031>
actor = 'giampaolo.rodola'
assignee = 'none'
closed = True
closed_date = <Date 2017-04-29.09:31:34.033>
closer = 'giampaolo.rodola'
components = ['Library (Lib)']
creation = <Date 2017-04-29.08:23:43.135>
creator = 'giampaolo.rodola'
dependencies = []
files = []
hgrepos = []
issue_num = 30204
keywords = []
message_count = 3.0
messages = ['292576', '292587', '292588']
nosy_count = 2.0
nosy_names = ['giampaolo.rodola', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '21327'
type = None
url = 'https://bugs.python.org/issue30204'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by giampaolo** [comment]
This caused me a lot of headaches (broken test) before figuring out what the heck was wrong: =)

```pycon
>>> import socket
>>> s = socket.socket()
>>> s.type
<SocketKind.SOCK_STREAM: 1>
>>> s.setblocking(0)
>>> s.type
2049
>>> s.setblocking(1) 
>>> s.type
<SocketKind.SOCK_STREAM: 1>
```



getsockopt() on the other hand always tells the truth:

```pycon
>>> s.getsockopt(socket.SOL_SOCKET, socket.SO_TYPE)
1
```



...so I suppose we can do that in the "type" property of the Python socket class.
It appears the type is set in socket init:
https://github.com/python/cpython/blob/1e2147b9d75a64df370a9393c2b5b9d170dc0afd/Modules/socketmodule.c#L904
...and it's changed later in setblocking:
https://github.com/python/cpython/blob/1e2147b9d75a64df370a9393c2b5b9d170dc0afd/Modules/socketmodule.c#L609

**Comment by vadmium** [comment]
Is this a duplicate of bpo-21327? There is some discussion there and a patch to add get_socket_type that excludes SOCK_NONBLOCK.

**Comment by giampaolo** [comment]
Woo! I completely forgot I already bumped into this and that I even filed a ticket for it.
