### ISSUE TITLE
socket.getsockname() type mismatch with AF_UNIX on Linux

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#74391]
BPO | [30205](https://bugs.python.org/issue30205)
--- | :---
Nosy | @ronaldoussoren, @pitrou, @vstinner, @giampaolo, @tiran, @ned-deily
PRs | <li>python/cpython#1370</li><li>python/cpython#1404</li><li>python/cpython#1403</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.22:23:04.258>
created_at = <Date 2017-04-29.08:55:10.959>
labels = ['3.7', 'type-bug', 'library']
title = 'socket.getsockname() type mismatch with AF_UNIX on Linux'
updated_at = <Date 2017-05-02.22:23:04.257>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.22:23:04.257>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.22:23:04.258>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-04-29.08:55:10.959>
creator = 'giampaolo.rodola'
dependencies = []
files = []
hgrepos = []
issue_num = 30205
keywords = []
message_count = 11.0
messages = ['292580', '292581', '292702', '292776', '292781', '292806', '292807', '292809', '292810', '292818', '292819']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'pitrou', 'vstinner', 'giampaolo.rodola', 'christian.heimes', 'ned.deily', 'neologix']
pr_nums = ['1370', '1404', '1403']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30205'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by giampaolo** [comment]
```pycon
>>> import socket
>>> s = socket.socket(socket.AF_UNIX)
>>> s.getsockname()
b''
>>> s.bind('foo')
>>> s.getsockname()
'foo'
```

**Comment by giampaolo** [comment]
The change was introduced here:
https://github.com/python/cpython/commit/b10c71daa2099c450101e5854fd693a405bec49c

**Comment by pitrou** [comment]
Amusingly, binding to the empty string produces something different:

```pycon
>>> s = socket.socket(socket.AF_UNIX)
>>> s.getsockname()
b''
>>> s.bind(b'')
>>> s.getsockname()
b'\x000005d'
```


```py
while binding to the nul byte string produces the expected result:
```


```pycon
>>> s = socket.socket(socket.AF_UNIX)
>>> s.bind(b'\x00')
>>> s.getsockname()
b'\x00'
```

**Comment by pitrou** [comment]
New changeset 495b5021e73e3c4b6404417ecf4fa83aa10297f0 by Antoine Pitrou in branch 'master':
bpo-30205: Fix getsockname() for unbound AF_UNIX sockets on Linux (bpo-1370)
https://github.com/python/cpython/commit/495b5021e73e3c4b6404417ecf4fa83aa10297f0

**Comment by giampaolo** [comment]
Thanks.

**Comment by vstinner** [comment]
Test fails on  x86 Tiger 3.x:

http://buildbot.python.org/all/builders/x86%20Tiger%203.x/builds/600/steps/test/logs/stdio

\======================================================================
FAIL: testUnbound (test.test_socket.TestUnixDomain)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/db3l/buildarea/3.x.bolen-tiger/build/Lib/test/test_socket.py", line 4687, in testUnbound
    self.assertEqual(self.sock.getsockname(), '')
AssertionError: None != ''
```

**Comment by vstinner** [comment]
Maybe restrict the unit test to Linux since the change was specific to Linux?

**Comment by pitrou** [comment]
Oh, yuck.

> Maybe restrict the unit test to Linux since the change was specific to Linux?

That sounds reasonable.  I didn't know getsockname() could return None...

**Comment by vstinner** [comment]
> I didn't know getsockname() could return None...

```c
Me neither. Maybe it's a bug? makesockaddr() returns None if addrlen equals 0:                                   
             
    if (addrlen == 0) {                                                           
        /* No address -- may be recvfrom() from known socket */                   
        Py_RETURN_NONE;                                                           
    }
```

**Comment by pitrou** [comment]
New changeset 0c2ff0898db2db9cd9c643dfadbff11761bacf5f by Antoine Pitrou in branch '3.6':
Backport bpo-30205 to 3.6 (bpo-1403)
https://github.com/python/cpython/commit/0c2ff0898db2db9cd9c643dfadbff11761bacf5f

**Comment by pitrou** [comment]
New changeset 0d9d61828bbd6cbc289489bf1d439fa91eca3743 by Antoine Pitrou in branch '3.5':
Backport bpo-30205 to 3.5 (bpo-1404)
https://github.com/python/cpython/commit/0d9d61828bbd6cbc289489bf1d439fa91eca3743
