### ISSUE TITLE
some UTF8 symbols

### ISSUE THREAD

**Issue by 0420f1ca-3259-4b0e-9a24-6d57cf2346ad** [python/cpython#74395]
BPO | [30209](https://bugs.python.org/issue30209)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @zooba
Superseder | <li>bpo-30019: IDLE freezes when opening a file with astral characters</li>
Files | <li>[goth - crasher.py](https://bugs.python.org/file46843/goth%20-%20crasher.py "Uploaded as text/plain at 2017-04-29.16:53:57 by Priit Oorn")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-04-29.23:08:39.493>
created_at = <Date 2017-04-29.16:48:42.228>
labels = ['expert-IDLE', 'OS-windows', 'type-crash']
title = 'some UTF8 symbols'
updated_at = <Date 2017-04-29.23:08:39.491>
user = 'https://bugs.python.org/PriitOorn'
```

bugs.python.org fields:
```python
activity = <Date 2017-04-29.23:08:39.491>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-04-29.23:08:39.493>
closer = 'terry.reedy'
components = ['IDLE', 'Windows']
creation = <Date 2017-04-29.16:48:42.228>
creator = 'Priit Oorn'
dependencies = []
files = ['46843']
hgrepos = []
issue_num = 30209
keywords = []
message_count = 3.0
messages = ['292595', '292600', '292606']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'mrabarnett', 'zach.ware', 'steve.dower', 'Priit Oorn']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30019'
type = 'crash'
url = 'https://bugs.python.org/issue30209'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0420f1ca-3259-4b0e-9a24-6d57cf2346ad** [comment]
It seems that idle has problems with some UTF8 / Unicode characters and loading files that have them inside them.

I tried to do code to replace text with other symbols from unicode table. First in idle and pasting the symbol "𝔄" into the idle it caused both the text editor and idle itself to close. Then made edit and paste in notepad.exe for the same file, which seemed to work fine... but when I tried to open the file in idle, it opened an empty editor which was bugged and unable to close and I had to kill it off from taskmanager.
(Yes you can edit and write stuff into the empty new file, and even save it, but you can't close it from the top window X button and Exit causes it to close idle and keep the editor window still open)

```py
replacements = {'A':'𝔄', 'B':'𝔅', 'C':'ℭ', 'D':'𝔇'}
```

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
IDLE uses tkinter, which wraps tcl/tk. Versions up to tcl/tk 8.6 can't handle 'astral' codepoints.

See also:

Issue bpo-30019: IDLE freezes when opening a file with astral characters

Issue bpo-21084: IDLE can't deal with characters above the range (U+0000-U+FFFF)

**Comment by terryjreedy** [comment]
Duplicate, or close enough, of bpo-30019, which has more on issue.
