### ISSUE TITLE
data parameter for binascii.b2a_base64 is not positional-only

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74392]
BPO | [30206](https://bugs.python.org/issue30206)
--- | :---
Nosy | @vstinner, @vadmium, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1352</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-01.05:12:47.881>
created_at = <Date 2017-04-29.09:22:01.315>
labels = ['3.7', 'type-bug', 'library']
title = 'data parameter for binascii.b2a_base64 is not positional-only'
updated_at = <Date 2017-05-01.05:12:47.880>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-01.05:12:47.880>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-01.05:12:47.881>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-04-29.09:22:01.315>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30206
keywords = []
message_count = 3.0
messages = ['292585', '292589', '292603']
nosy_count = 4.0
nosy_names = ['vstinner', 'martin.panter', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1352']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30206'
versions = ['Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
Before functions in binascii having \*data* parameter all accept it as positionaly-only. But after bpo-25357, binascii.b2a_base64 changed it to accept keyword argument also but it looks unintentional.

**Comment by serhiy-storchaka** [comment]
Because this change looks unintentional (no one of reviewers even noticed it) and was not documented, I think it is better to make the data parameter positional-only in 3.7. The chance of breaking a user code is very low, and even if this breaks some code, it is easy to fix it. But it is safer to left 3.6 untouched.

**Comment by vstinner** [comment]
Right, my API change was unintentional.
