### ISSUE TITLE
Small typos in IDLE doc

### ISSUE THREAD

**Issue by csabella** [python/cpython#74394]
BPO | [30208](https://bugs.python.org/issue30208)
--- | :---
Nosy | @terryjreedy, @Mariatta, @csabella
PRs | <li>python/cpython#1354</li><li>python/cpython#1356</li><li>python/cpython#1357</li><li>python/cpython#1358</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-04-30.00:49:42.461>
created_at = <Date 2017-04-29.13:42:38.557>
labels = ['expert-IDLE', 'type-bug', '3.7']
title = 'Small typos in IDLE doc'
updated_at = <Date 2017-05-02.21:36:31.451>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.21:36:31.451>
actor = 'cheryl.sabella'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-04-30.00:49:42.461>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-04-29.13:42:38.557>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30208
keywords = []
message_count = 13.0
messages = ['292593', '292604', '292605', '292609', '292610', '292611', '292612', '292613', '292614', '292615', '292622', '292678', '292812']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'docs@python', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1354', '1356', '1357', '1358']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30208'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Fix some small typos in IDLE doc.

**Comment by terryjreedy** [comment]
New changeset 9dc2b3809f38be2e403ee264958106badfda142d by terryjreedy (csabella) in branch 'master':
bpo-30208: DOC: fix small typos in IDLE (bpo-1354)
https://github.com/python/cpython/commit/9dc2b3809f38be2e403ee264958106badfda142d

**Comment by terryjreedy** [comment]
Thank you for the review.  These are definitely bugs.  Please check IDLE component also for IDLE doc issues.  That will auto-assign them to me.

Your first merged PR?  If so, congrats.

Changes should be applied to at least 3.6, if not 3.5 and 2.7.  3.6 doc should be essentially identical, so I expect merge without conflict.  Likely true for others.  Can you (easily) prepare the PRs?  Can you use the cherry-pick script?

**Comment by csabella** [comment]
I followed the steps for cherry-pick, but messed up a little as I made 3 PRs instead of one.  However, I couldn't do the labels asked for in this section:

When a cherry-pick was applied successfully, this script will open up a browser tab that points to the pull request creation page.

The url of the pull request page looks similar to the following:

https://github.com/python/cpython/compare/3.5...\<username\>:backport-6de2b78-3.5?expand=1

    Apply the appropriate cherry-pick for ... label
    Press the Create Pull Request button.
    Remove the needs backport to ... label from the original pull request against master.

**Comment by terryjreedy** [comment]
New changeset 5a8dcec93936de816cef5c17522e48fca9c30b43 by terryjreedy (csabella) in branch '3.6':
[3.6] bpo-30208: DOC: fix small typos in IDLE (bpo-1356)
https://github.com/python/cpython/commit/5a8dcec93936de816cef5c17522e48fca9c30b43

**Comment by terryjreedy** [comment]
New changeset 52630ae17aa5bd8bffdb430b6515d07ffbaabc9e by terryjreedy (csabella) in branch '3.5':
[3.5] bpo-30208: DOC: fix small typos in IDLE (bpo-1357)
https://github.com/python/cpython/commit/52630ae17aa5bd8bffdb430b6515d07ffbaabc9e

**Comment by terryjreedy** [comment]
New changeset 4734c2d5c0529632e4b51eb75104b50955afd692 by terryjreedy (csabella) in branch '2.7':
[2.7] bpo-30208: DOC: fix small typos in IDLE (bpo-1358)
https://github.com/python/cpython/commit/4734c2d5c0529632e4b51eb75104b50955afd692

**Comment by terryjreedy** [comment]
From what I have seen, one PR for each branch is correct.  I believe cherry-pick.py was initially written by Mariatta.  Please bring up any problems or questions using it on core-mentorship, where she and others will see it.

**Comment by csabella** [comment]
For this "Please check IDLE component also for IDLE doc issues.", I see the same text as the doc page in idlelib/help/html.  Is that the one you want me to change or is that created automatically by Sphinx?

**Comment by terryjreedy** [comment]
I mean 'IDLE' in the Components: box, to the left of the Versions: box, both in the 'classification' frame near the top of this page.

**Comment by csabella** [comment]
LOL, well I made that a lot harder than you intended.  :-)

**Comment by Mariatta** [comment]
One PR per branch is correct.

For future reference, preferably the commit hash to be cherry-picked is the one that is merged into CPython's master branch. It can be found at the original PR where it says \<coredeveloper\> merged commit \<hash\> into python:master. For [PR 1353](https://github.com/python/cpython/pull/1353), it is 9dc2b38. 

For this issue, it doesn't make much difference since the PR contains only one commit. For PRs that contain multiple commits, it makes more sense to cherry-pick the squashed commit to master :)

Thanks :)

**Comment by csabella** [comment]
Thank you for that information, Mariatta.  I had to read your description
twice to find the 9dc2b38 commit hash.  Once someone learns this, then they
will remember it, but you may want to highlight it on the cherry-pick
readme.  That was very well written and easy to follow, but I don't
remember it specifying the commit hash to use.

Cherry-pick is an awesome tool.  Can't wait to use it again!   :-)
