### ISSUE TITLE
test_ssl.py is broken in Centos7

### ISSUE THREAD

**Issue by 8ba85964-d644-4885-a072-16bf65006af2** [python/cpython#74398]
BPO | [30212](https://bugs.python.org/issue30212)
--- | :---
Nosy | @vstinner, @zhangyangyu
Files | <li>[test.log](https://bugs.python.org/file46844/test.log "Uploaded as text/x-log at 2017-04-29.23:15:34 by david-cpi")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-12.11:39:04.115>
created_at = <Date 2017-04-29.23:15:34.972>
labels = ['build', 'tests']
title = 'test_ssl.py is broken in Centos7'
updated_at = <Date 2021-09-12.11:39:04.114>
user = 'https://bugs.python.org/david-cpi'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-12.11:39:04.114>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-09-12.11:39:04.115>
closer = 'iritkatriel'
components = ['Tests']
creation = <Date 2017-04-29.23:15:34.972>
creator = 'david-cpi'
dependencies = []
files = ['46844']
hgrepos = []
issue_num = 30212
keywords = []
message_count = 10.0
messages = ['292608', '292731', '292736', '292737', '292738', '292747', '292750', '292751', '333980', '333982']
nosy_count = 4.0
nosy_names = ['vstinner', 'xiang.zhang', 'david-cpi', 'David Antonio Garcia Campos']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30212'
versions = ['Python 3.5']
```

</p></details>

**Comment by 8ba85964-d644-4885-a072-16bf65006af2** [comment]
To make the test pass, I added the following try statement:
            try: 
             sock.sendall(buf)
            except:
             pass

**Comment by zhangyangyu** [comment]
The failure can't be reproduced by me, 3.5 on CentOS 7.1.

**Comment by vstinner** [comment]
@david-cpi: Can you please elaborate?

* What is your Centos full version?
* How do you get Python 3.5? Tarball from python.org?
* What is the error message?

"except: pass" is bad practice, you must catch a specific exception type.

It seems very strange to have to ignore errors on sendall().

**Comment by vstinner** [comment]
Oh, I missed the attached test.log file. So, it's CentOS 7.3.1611 and the full error message is:

== CPython 3.5.2 (default, Apr 29 2017, 16:07:16) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
==   Linux-3.10.0-514.16.1.el7.x86_64-x86_64-with-centos-7.3.1611-Core little-endian
==   hash algorithm: siphash24 64bit
==   /home/vagrant/Downloads/Python-3.5.2/build/test_python_16502
...
[1/1/1] test_ssl
test_ssl: testing with 'OpenSSL 1.0.1e-fips 11 Feb 2013' (1, 0, 1, 5, 15)
          under Linux ('CentOS Linux', '7.3.1611', 'Core')
          HAS_SNI = True
          OP_ALL = 0x800003f7
          OP_NO_TLSv1_1 = 0x10000000
...
test_read_write_data (test.test_ssl.NetworkedBIOTests) ... Needed 3 calls to complete do_handshake().
Needed 1 calls to complete write().
ERROR
...
\======================================================================
ERROR: test_read_write_data (test.test_ssl.NetworkedBIOTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/vagrant/Downloads/Python-3.5.2/Lib/test/test_ssl.py", line 1785, in test_read_write_data
    buf = self.ssl_io_loop(sock, incoming, outgoing, sslobj.read, 1024)
  File "/home/vagrant/Downloads/Python-3.5.2/Lib/test/test_ssl.py", line 1724, in ssl_io_loop
    sock.sendall(buf)
BrokenPipeError: [Errno 32] Broken pipe
```


----------------------------------------------------------------------
Ran 117 tests in 39.538s

FAILED (errors=1, skipped=8)
/home/vagrant/Downloads/Python-3.5.2/Lib/unittest/case.py:628: ResourceWarning: unclosed \<socket.socket fd=4, family=AddressFamily.AF_INET, type=2049, proto=0, laddr=('10.0.2.15', 53304)\>
  outcome.errors.clear()
test test_ssl failed

**Comment by vstinner** [comment]
David: can you please check if you get the same error with Python 3.6, or even the development version (Git master branch)?

**Comment by 8ba85964-d644-4885-a072-16bf65006af2** [comment]
Hi Victor,
I will try during the day and get back with the logs.

**Comment by 8ba85964-d644-4885-a072-16bf65006af2** [comment]
Hello Victor,

in 3.6.1 the test passes but it's because on sub-test was removed.

The one generating the issue is NetworkedBIOTests which is not found in 3.6.1.

in 3.5.2:
    if support.is_resource_enabled('network'):
        tests.append(NetworkedTests)
        tests.append(NetworkedBIOTests)
in 3.6.1
    if support.is_resource_enabled('network'):
        tests.append(NetworkedTests)

**Comment by vstinner** [comment]
> in 3.6.1 the test passes but it's because on sub-test was removed.

The unit tests still exist and were enhanced.

On Python 3.5, the BIO read-write data test used the external server self-signed.pythontest.net. On Python 3.6, the test now uses a server running locally. See issue bpo-25940 and commit 3840b2ac6728d1940a7efc2ecab2c7d9a100c080.

Note: the failing test was renamed to test_bio_read_write_data.

--

David: You can try the following command to run the failing test in verbose mode (and only run this test). You can add --forever option to run the test in a loop until it fails.

In your output, I see "Needed 3 calls to complete do_handshake(). Needed 1 calls to complete write()." but not "Needed 2 calls to complete read(). Needed 1 calls to complete unwrap().".

For Python 3.5:

haypo@selma$ ./python -m test -u all test_ssl -v -m test_read_write_data

== CPython 3.5.3+ (default, May 2 2017, 11:20:59) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
==   Linux-4.10.11-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five little-endian
==   hash algorithm: siphash24 64bit
==   /home/haypo/prog/python/3.5/build/test_python_20359
Testing with flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0)
[1/1] test_ssl
test_ssl: testing with 'OpenSSL 1.0.2k-fips  26 Jan 2017' (1, 0, 2, 11, 15)
          under Linux ('Fedora', '25', 'Twenty Five')
          HAS_SNI = True
          OP_ALL = 0x800003ff
          OP_NO_TLSv1_1 = 0x10000000
test_read_write_data (test.test_ssl.NetworkedBIOTests) ... Needed 3 calls to complete do_handshake().
Needed 1 calls to complete write().
Needed 2 calls to complete read().
Needed 1 calls to complete unwrap().
ok

\----------------------------------------------------------------------
Ran 1 test in 0.456s

OK
1 test OK.


For Python 3.6:

haypo@selma$ ./python -m test test_ssl -v -m test_bio_read_write_data

== CPython 3.6.1+ (default, May 2 2017, 10:23:14) [GCC 6.3.1 20161221 (Red Hat 6.3.1-1)]
==   Linux-4.10.11-200.fc25.x86_64-x86_64-with-fedora-25-Twenty_Five little-endian
==   hash algorithm: siphash24 64bit
==  cwd: /home/haypo/prog/python/3.6/build/test_python_20383
==  encodings: locale=UTF-8, FS=utf-8
Testing with flags: sys.flags(debug=0, inspect=0, interactive=0, optimize=0, dont_write_bytecode=0, no_user_site=0, no_site=0, ignore_environment=0, verbose=0, bytes_warning=0, quiet=0, hash_randomization=1, isolated=0)
Run tests sequentially
0:00:00 [1/1] test_ssl
test_ssl: testing with 'OpenSSL 1.0.2k-fips  26 Jan 2017' (1, 0, 2, 11, 15)
          under Linux ('Fedora', '25', 'Twenty Five')
          HAS_SNI = True
          OP_ALL = 0x800003ff
          OP_NO_TLSv1_1 = 0x10000000
test_bio_read_write_data (test.test_ssl.SimpleBackgroundTests) ...  server:  new connection from ('127.0.0.1', 42160)
 server: connection cipher is now ('ECDHE-RSA-AES256-SHA', 'TLSv1/SSLv3', 256)
 server: selected protocol is now None
Needed 3 calls to complete do_handshake().
Needed 1 calls to complete write().
Needed 2 calls to complete read().
Needed 2 calls to complete unwrap().
ok

\----------------------------------------------------------------------
Ran 1 test in 0.058s

OK
1 test OK.

Total duration: 413 ms
Tests result: SUCCESS
