### ISSUE TITLE
Rename test.test_support to test.support in 2.7

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74393]
BPO | [30207](https://bugs.python.org/issue30207)
--- | :---
Nosy | @ncoghlan, @ezio-melotti, @voidspace, @zware, @serhiy-storchaka
PRs | <li>python/cpython#1353</li><li>python/cpython#1369</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-01.17:28:34.273>
created_at = <Date 2017-04-29.10:52:06.625>
labels = ['type-feature', 'tests']
title = 'Rename test.test_support to test.support in 2.7'
updated_at = <Date 2017-05-01.17:28:34.272>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-01.17:28:34.272>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-01.17:28:34.273>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-04-29.10:52:06.625>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30207
keywords = []
message_count = 5.0
messages = ['292590', '292620', '292664', '292670', '292675']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'ezio.melotti', 'michael.foord', 'zach.ware', 'serhiy.storchaka']
pr_nums = ['1353', '1369']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30207'
versions = ['Python 2.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch converts test.test_support into package and rename it to test.support, move test.script_helper into the test.support package.  Old names test.test_support and test.script_helper are left as aliases to test.support and test.support.script_helper for compatibility (hence most tests don't need modification).

Benefits of this change:

1. This makes the structure of the test directory more compatible with 3.x. This helps bacporting tests. There were a number of cases when the only required change in backported 2.7 patch was changing "support" to "test_support". Many times backporting simple tests broke 2.7 buildbots because this change was not made.

2. This makes easier backporting changes in test.support itself and backporting 3.x features from test.support.

**Comment by serhiy-storchaka** [comment]
New changeset a694e092f6356970ca0d3e86000a3a829fb212b4 by Serhiy Storchaka in branch '2.7':
bpo-30207: Rename test.test_support to test.support. (bpo-1353)
https://github.com/python/cpython/commit/a694e092f6356970ca0d3e86000a3a829fb212b4

**Comment by zware** [comment]
I like this change, but the install target in Makefile.pre.in needs to be adjusted accordingly: http://buildbot.python.org/all/builders/x86%20Gentoo%20Installed%20with%20X%202.7/builds/120

**Comment by serhiy-storchaka** [comment]
Thank you for noticing this Zachary.

**Comment by serhiy-storchaka** [comment]
New changeset 6bed8f95d72f622cb916bcebad651ccd3de6fe9d by Serhiy Storchaka in branch '2.7':
bpo-30207: Install the [Lib/test/support](https://github.com/python/cpython/blob/main/Lib/test/support) directory. (bpo-1369)
https://github.com/python/cpython/commit/6bed8f95d72f622cb916bcebad651ccd3de6fe9d
