### ISSUE TITLE
make_zip.py lacks command a few line options.

### ISSUE THREAD

**Issue by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [python/cpython#74400]
BPO | [30214](https://bugs.python.org/issue30214)
--- | :---
Nosy | @brettcannon, @pfmoore, @tjguk, @zware, @zooba, @AraHaan, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-12-03.13:05:22.154>
created_at = <Date 2017-04-30.04:35:48.055>
labels = ['3.7', 'type-feature', 'expert-tkinter', 'OS-windows']
title = 'make_zip.py lacks command a few line options.'
updated_at = <Date 2021-12-03.13:05:22.152>
user = 'https://github.com/AraHaan'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-03.13:05:22.152>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-12-03.13:05:22.154>
closer = 'iritkatriel'
components = ['Demos and Tools', 'Tkinter', 'Windows']
creation = <Date 2017-04-30.04:35:48.055>
creator = 'Decorater'
dependencies = []
files = []
hgrepos = []
issue_num = 30214
keywords = []
message_count = 6.0
messages = ['292617', '292684', '292692', '292696', '292700', '407583']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Decorater', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30214'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
make_zip.py does not offer the options to include tests with the tkinner stuff when making the full distributions immediately after building python using MSVC.

Basically running makezip like this:

".\\PCbuild\\amd64\\python.exe" ".\\Tools\\msi\\make_zip.py" -a x64 -o ".\\python36-x86-x64"

or like this:

".\\PCbuild\\win32\\python.exe" ".\\Tools\\msi\\make_zip.py" -o ".\\python36-x86"

does not even include the tests and tkinner stuff that is optional when installing python by the installer. I would like command sqitches to be able to if desired.

Also on the 64 bit copy it does mess up where none of the libs\\*.lib, nor any of the assemblies are copied. And is reproducible on me.

**Comment by brettcannon** [comment]
Can you separate out the bug report from the feature request as two separate issues? You can keep one here and rename the title if you want.

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
Alright renamed it.

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
Alright moved the bug part to http://bugs.python.org/issue30222.

**Comment by zooba** [comment]
I disagree with this going into the core repo - this script is meant for producing our official packages, and is not a general purpose tool.

If someone does make changes, please backport them as far as possible (so that bug fixes are easy to cherry pick) and don't break the core use case.
