### ISSUE TITLE
Deprecate assertNotAlmostEqual

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74407]
BPO | [30221](https://bugs.python.org/issue30221)
--- | :---
Nosy | @pitrou, @rbtcollins, @ezio-melotti, @bitdancer, @voidspace, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-02.05:06:44.275>
created_at = <Date 2017-05-01.16:53:21.124>
labels = ['3.7', 'type-feature', 'library']
title = 'Deprecate assertNotAlmostEqual'
updated_at = <Date 2017-05-02.05:06:44.274>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-02.05:06:44.274>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-02.05:06:44.275>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-05-01.16:53:21.124>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30221
keywords = []
message_count = 12.0
messages = ['292674', '292679', '292680', '292681', '292686', '292687', '292689', '292691', '292695', '292698', '292704', '292713']
nosy_count = 6.0
nosy_names = ['pitrou', 'rbcollins', 'ezio.melotti', 'r.david.murray', 'michael.foord', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30221'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The purpose of the assertNotAlmostEqual() method of TestCase is not clear. This method is never used in the CPython testsuite (except tests for it itself), it is never mentioned in the bug tracker (except one general issue about mass renaming methods in TestCase). I have found only one usage of assertNotAlmostEqual() which is not testing its itself on GitHub [1], and in that case it would be better to use assertAlmostEqual() with correct expected result instead.

It seems to me that assertNotAlmostEqual() was added just "for symmetry", and there are no real cases for it. Deprecating and following removing it will make the API simpler.

[1] https://github.com/BrechtDeVlieger/Altran_courses/blob/d983b30b4dc1eac6905a71209037ed082330f7fe/Python%20fundamentals/Day1/Functions/test_temperature_ori.py

**Comment by voidspace** [comment]
I agree it's not \*very* useful, but I don't see any benefit in getting rid of it either.

**Comment by pitrou** [comment]
Agreed with Michael.

**Comment by serhiy-storchaka** [comment]
This will save time and memory of unittest users for reading the documentation, remembering it and trying to understand in which cases assertNotAlmostEqual() can be used. This will prevent them from using unsuitable method.

I found only one case of using assertNotAlmostEqual() in the wild, and it doesn't look a proper use. Do you have any cases in which it is useful?

Recently I did have a discussion with Giampaolo about changes to assertAlmostEqual() and assertNotAlmostEqual() [1]. If assertNotAlmostEqual() didn't exist this discussion would even not started. So this would save my and Giampaolo's time.

[1] https://github.com/python/cpython/pull/1331

**Comment by pitrou** [comment]
Any peculiarity that applies to assertNotAlmostEqual also applies to assertAlmostEqual, so I'm not sure how removing one but keeping the other would simplify anything.

Furthermore, such symmetry between positive and negative asserts is widespread in the unittest API, so this dual API is quite expected and nothing to be surprised about.

**Comment by bitdancer** [comment]
Not only is not something to be surprised about, it would be surprising for it to be absent.  So the user cognitive overhead of removing it is quite possibly higher than that of it being there.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
There are 100 results in Google books alone. Are the books wrong (honest question, I did not check)?

They will be wrong if we remove it. ;)


I agree with Michael that assertNotAlmostEqual() doesn't hurt.

**Comment by serhiy-storchaka** [comment]
> Any peculiarity that applies to assertNotAlmostEqual also applies to assertAlmostEqual, so I'm not sure how removing one but keeping the other would simplify anything.

There are use cases for assertAlmostEqual(). You can find examples in the CPython tests and in other open sources. Do you have use cases for assertNotAlmostEqual()?

> Furthermore, such symmetry between positive and negative asserts is widespread in the unittest API, so this dual API is quite expected and nothing to be surprised about.

This symmetry is not absolute. There are no asserts opposite to assertRaises(), assertWarns(), assertLogs() and assertCountEqual(), assertMultiLineEqual(), assertSequenceEqual(), etc. Some asserts are not symmetric by its nature. assertNotRaises() would be useless.

> There are 100 results in Google books alone. Are the books wrong (honest question, I did not check)?

Do these books have any use cases for assertNotAlmostEqual() or just enumerate the list of TestCase methods?

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
> Do these books have any use cases for assertNotAlmostEqual() or just enumerate the list of TestCase methods?

I think this should be researched by the proponent of the change.

**Comment by serhiy-storchaka** [comment]
Google finds only 16 books for me. I have reviewed them, and all of them just list assertion methods, copying the official documentation or one other. Often the book contains just one mention of assertNotAlmostEqual (not including the contents and the index). No books contain an example for assertNotAlmostEqual. They even don't mention the delta parameter added in 3.2.

**Comment by rbtcollins** [comment]
We've now spent more time debating the deprecation that we would have saved if it had been deprecated.

Deprecations cost user good will. Whilst I very much want to delete all assertions in favour of matchers, which would allow composed symmetry rather than the manual symmetry we have today.

Like michael I don't see any benefit in getting rid of it either. I don't believe it will make the API substantially easier to learn: the lack of symmetry increases special cases, so it will IMO make it harder to learn.

Unless you've new arguments to make about this, I think the ticket can be closed WONTFIX.

**Comment by serhiy-storchaka** [comment]
If the absent of use cases is not good argument I close this issue. But this looks as a design mistake to me.
