### ISSUE TITLE
shutil.unpack_archive doesn't support PathLike

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#74404]
BPO | [30218](https://bugs.python.org/issue30218)
--- | :---
Nosy | @brettcannon, @tarekziade, @JelleZijlstra
PRs | <li>python/cpython#1367</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.21:27:43.011>
created_at = <Date 2017-04-30.21:50:48.042>
labels = ['3.7', 'library']
title = "shutil.unpack_archive doesn't support PathLike"
updated_at = <Date 2017-05-05.21:27:58.888>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.21:27:58.888>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.21:27:43.011>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2017-04-30.21:50:48.042>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 30218
keywords = []
message_count = 3.0
messages = ['292642', '293141', '293142']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'tarek', 'JelleZijlstra']
pr_nums = ['1367']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30218'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
According to PEP-519, it should. I'll submit a PR soon.

**Comment by brettcannon** [comment]
New changeset a12df7b7d40dbf47825917c8fa03d2c09b5a382c by Brett Cannon (Jelle Zijlstra) in branch 'master':
bpo-30218: support path-like objects in shutil.unpack_archive() (GH-1367)
https://github.com/python/cpython/commit/a12df7b7d40dbf47825917c8fa03d2c09b5a382c

**Comment by brettcannon** [comment]
Thanks for the patch (and patience), Jelle!
