### ISSUE TITLE
Add Lib/test/__main__.py in 2.7

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74409]
BPO | [30223](https://bugs.python.org/issue30223)
--- | :---
Nosy | @ncoghlan, @vstinner, @ezio-melotti, @zware, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1373</li><li>python/cpython#1395</li><li>python/cpython#1399</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.16:21:10.245>
created_at = <Date 2017-05-02.06:56:55.910>
labels = ['type-feature', 'tests']
title = 'Add Lib/test/__main__.py in 2.7'
updated_at = <Date 2017-05-05.16:21:10.244>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.16:21:10.244>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.16:21:10.245>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-05-02.06:56:55.910>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30223
keywords = []
message_count = 15.0
messages = ['292720', '292722', '292723', '292735', '292779', '292786', '292794', '292795', '292796', '292797', '292798', '292808', '292811', '292814', '293119']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'vstinner', 'ezio.melotti', 'zach.ware', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1373', '1395', '1399']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30223'
versions = ['Python 2.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Following patch adds [Lib/test/__main__.py](https://github.com/python/cpython/blob/main/Lib/test/__main__.py) in 2.7. This allows running tests with 'python -m test' as in 3.x.

**Comment by vstinner** [comment]
Oh yes, I always wanted this tiny feature! It's painful to have to adapt my command for Python 2 after testing Python 3.

**Comment by zhangyangyu** [comment]
+1. Every time when I want to run tests for 2.7, I have to type twice. Once python -m test, error and then python -m test.regrtest.

**Comment by ncoghlan** [comment]
+1 from me. We hadn't done this (or the test.support backport) previously due to the "no new features" guideline, but I think simplifying cross-branch maintenance overrides that concerns.

**Comment by serhiy-storchaka** [comment]
New changeset 43566aee12a177a7aef5d732abf768251e6b8a12 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30223: Add [Lib/test/__main__.py](https://github.com/python/cpython/blob/main/Lib/test/__main__.py). (bpo-1373)
https://github.com/python/cpython/commit/43566aee12a177a7aef5d732abf768251e6b8a12

**Comment by serhiy-storchaka** [comment]
These new features affect only core developers and other contributors fixing bugs in 2.7. I don't think the "no new features" guideline is applicable here.

**Comment by zware** [comment]
Once again, I agree with the change, but I have an unhappy buildbot :)

http://buildbot.python.org/all/builders/x86%20Gentoo%20Non-Debug%20with%20X%202.7/builds/124

This time it is due to python 2.4 not supporting the absolute_import \_\_future__ feature.  By this point, I think we could get away with just removing the python 2.4 pickle compat tests.

**Comment by serhiy-storchaka** [comment]
Oh, it is so easy to break test_xpickle. But I think this test is very important. It is pity that test_xpickle is removed in 3.x.

I hope [PR 1395](https://github.com/python/cpython/pull/1395) will fix test_xpickle.

**Comment by zware** [comment]
2.4 is rather far out of date, but [PR1395](https://github.com/python/cpython/pull/1395) is simple enough.  I would support re-adding test_xpickle in 3.x, and can ensure that every major version is available on that buildbot to exercise it.

**Comment by serhiy-storchaka** [comment]
New changeset 8e158b2316385497c7b6b818d8b45855d7f87f0b by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30223: Fix test_xpickle for Python 2.4. (bpo-1395)
https://github.com/python/cpython/commit/8e158b2316385497c7b6b818d8b45855d7f87f0b

**Comment by serhiy-storchaka** [comment]
Thanks Zachary!

**Comment by vstinner** [comment]
Hum, it seems like test_regrtest is more and more important. Yet another regression:

http://buildbot.python.org/all/builders/x86%20Gentoo%20Installed%20with%20X%202.7/builds/126/steps/test/logs/stdio

```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.installed/build/target/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.installed/build/target/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.installed/build/target/lib/python2.7/test/regrtest.py", line 1684, in <module>
    main_in_temp_cwd()
  File "/buildbot/buildarea/2.7.ware-gentoo-x86.installed/build/target/lib/python2.7/test/regrtest.py", line 1664, in main_in_temp_cwd
    TESTCWD = os.path.join(TEMPDIR, TESTCWD)
UnboundLocalError: local variable 'TEMPDIR' referenced before assignment
```

**Comment by vstinner** [comment]
> Hum, it seems like test_regrtest is more and more important.

To be fair, I don't think that this particular bug would be catched by the CI since the bug is only triggered on a buildbot which installs Python and runs tests on the installed test suite.

It should be fixed by https://github.com/python/cpython/pull/1399

**Comment by vstinner** [comment]
New changeset 8105dd7f75b6aa5f812522d452cd378372752a10 by Victor Stinner in branch '2.7':
bpo-30223: Add global in regrtest main_in_temp_cwd (bpo-1399)
https://github.com/python/cpython/commit/8105dd7f75b6aa5f812522d452cd378372752a10

**Comment by serhiy-storchaka** [comment]
Thank you Victor for fixing this bug.
