### ISSUE TITLE
Missing entry for the tilde (~) operator in the Index

### ISSUE THREAD

**Issue by dbef62b9-748b-467c-814d-4382f38a6075** [python/cpython#74403]
BPO | [30217](https://bugs.python.org/issue30217)
--- | :---
Nosy | @terryjreedy, @lebigot, @serhiy-storchaka, @marco-buttu, @Mariatta, @lebigot
PRs | <li>python/cpython#1502</li><li>python/cpython#2138</li><li>python/cpython#2137</li><li>python/cpython#2136</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-12.19:45:14.277>
created_at = <Date 2017-04-30.19:56:00.691>
labels = ['type-feature', '3.7', 'docs']
title = 'Missing entry for the tilde (~) operator in the Index'
updated_at = <Date 2017-06-12.19:45:14.277>
user = 'https://github.com/lebigot'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-12.19:45:14.277>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-12.19:45:14.277>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-04-30.19:56:00.691>
creator = 'lebigot'
dependencies = []
files = []
hgrepos = []
issue_num = 30217
keywords = []
message_count = 8.0
messages = ['292641', '293238', '293241', '293324', '295531', '295816', '295818', '295819']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'lebigot', 'docs@python', 'serhiy.storchaka', 'marco.buttu', 'Mariatta', 'Eric Lebigot']
pr_nums = ['1502', '2138', '2137', '2136']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30217'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by dbef62b9-748b-467c-814d-4382f38a6075** [comment]
The index (https://docs.python.org/3.6/genindex-Symbols.html) is missing an entry for the tilde operator ~ (there is also no entry under "tilde").

A relevant pointer could be to object.\_\_invert__ (https://docs.python.org/3.6/reference/datamodel.html#object.\_\_invert__).

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
Thanks Eric.  I think the reference should be added here, as we do for the other operators:

https://docs.python.org/3/library/stdtypes.html#bitwise-operations-on-integer-types

**Comment by dbef62b9-748b-467c-814d-4382f38a6075** [comment]
Good reference.

Another one would be https://docs.python.org/3/reference/expressions.html#unary-arithmetic-and-bitwise-operations, which explicitly indicates that it only makes sense for integer types (which is useful to keep in mind, as one may think that it could somehow apply to floating point numbers as well).

The one at https://docs.python.org/3.6/reference/datamodel.html#object.\_\_invert__ is also important for learning that it is related to \_\_invert__().

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
Looking at [Doc/reference/expressions.rst](https://github.com/python/cpython/blob/main/Doc/reference/expressions.rst) and [Doc/reference/datamodel.rst](https://github.com/python/cpython/blob/main/Doc/reference/datamodel.rst), I do not see any reference to the symbols, but only to the operator name (negation, minus, plus, inversion, etc.).  Therefore I think it is better to not change these files.

In the PR [*] I added (in [Doc/library/stdtypes.rst](https://github.com/python/cpython/blob/main/Doc/library/stdtypes.rst)) both a reference to the symbol and to the name.

Thank you very much 

[*] https://github.com/python/cpython/pull/1502/

**Comment by serhiy-storchaka** [comment]
New changeset 5eb7075915f0509c5027376bda0e6d9c1e505a2c by Serhiy Storchaka (Marco Buttu) in branch 'master':
bpo-30217: Add the operators ~ and | to the index (bpo-1502)
https://github.com/python/cpython/commit/5eb7075915f0509c5027376bda0e6d9c1e505a2c

**Comment by Mariatta** [comment]
New changeset f59cac4b6458e5c47e24a39ba46fb178c3766577 by Mariatta (Marco Buttu) in branch '3.6':
bpo-30217: add the operators ~ and | to the index (GH-1502) (GH-2136)
https://github.com/python/cpython/commit/f59cac4b6458e5c47e24a39ba46fb178c3766577

**Comment by Mariatta** [comment]
New changeset bbb335891c2967bd13fbe2da775c0348260d95cb by Mariatta (Marco Buttu) in branch '2.7':
bpo-30217: add the operators ~ and | to the index (GH-1502) (GH-2137)
https://github.com/python/cpython/commit/bbb335891c2967bd13fbe2da775c0348260d95cb

**Comment by Mariatta** [comment]
New changeset 37e04153d5e331162608b33639ecd3c9a5ae2432 by Mariatta (Marco Buttu) in branch '3.5':
bpo-30217: add the operators ~ and | to the index (GH-1502) (GH-2138)
https://github.com/python/cpython/commit/37e04153d5e331162608b33639ecd3c9a5ae2432
