### ISSUE TITLE
Why are custom messages for ValueError, TypeError suppressed in argparse?

### ISSUE THREAD

**Issue by a6982a76-b293-41eb-bd2e-00129268a441** [python/cpython#74406]
BPO | [30220](https://bugs.python.org/issue30220)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-18.16:40:22.469>
created_at = <Date 2017-05-01.16:19:51.087>
labels = ['extension-modules', 'invalid', 'type-feature', '3.7']
title = 'Why are custom messages for ValueError, TypeError suppressed in argparse?'
updated_at = <Date 2018-10-18.16:40:22.468>
user = 'https://bugs.python.org/pgacv2'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-18.16:40:22.468>
actor = 'paul.j3'
assignee = 'none'
closed = True
closed_date = <Date 2018-10-18.16:40:22.469>
closer = 'paul.j3'
components = ['Extension Modules']
creation = <Date 2017-05-01.16:19:51.087>
creator = 'pgacv2'
dependencies = []
files = []
hgrepos = []
issue_num = 30220
keywords = []
message_count = 6.0
messages = ['292669', '292673', '292709', '293150', '293165', '327985']
nosy_count = 2.0
nosy_names = ['paul.j3', 'pgacv2']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30220'
versions = ['Python 3.7']
```

</p></details>

**Comment by a6982a76-b293-41eb-bd2e-00129268a441** [comment]
ArgumentParser.\_get_value() has two exception handlers: one for ArgumentTypeError, and one for (TypeError, ValueError). But in the latter case, any custom message I include the TypeError or ValueError is ignored and replaced with a generic "invalid value" message.

I don't see why the module wouldn't first check for a custom message in a TypeError or ValueError exception, as it does for ArgumentTypeError, and only use the generic message if a custom one is not specified. The current behavior does not let you to give the user a detailed reason for the exception unless you raise ArgumentTypeError, which is considered an implementation detail as mentioned in bpo-20039, and also doesn't feel right for errors that are not related to the argument's type.


Code to reproduce:

```py
import argparse

def nonnegative_not_suppressed(arg):
  try:
    x = int(arg)
    if x >= 0:
      return x
    else:
      raise argparse.ArgumentTypeError('Enter a nonnegative integer')
  except:
    raise argparse.ArgumentTypeError('Enter a nonnegative integer')

def nonnegative_suppressed(arg):
  try:
    x = int(arg)
    if x >= 0:
      return x
    else:
      raise ValueError('Enter a nonnegative integer')
  except:
    raise ValueError('Enter a nonnegative integer')

p = argparse.ArgumentParser('parser')
p.add_argument('--no-suppress', type=nonnegative_not_suppressed)
p.add_argument('--suppress', type=nonnegative_suppressed)
p.parse_args(['--no-suppress', '-4']) # Displays "Enter a nonnegative integer"
p.parse_args(['--suppress', '-4']) # Displays "invalid nonnegative_suppressed value: '-4'"
```

**Comment by a6982a76-b293-41eb-bd2e-00129268a441** [comment]
You can get around the message suppression by raising anything that isn't a ValueError, TypeError, or subclass thereof. It will propagate up past \_get_value(). I still don't see the reason for giving special treatment to ValueError and TypeError.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
In http://bugs.python.org/issue9353 Steven Bethard includes 'ArgumentTypeError' in a list of values that "look like they should be public but aren't in \_\_all__::".  

I take that `__all__` list to be the ultimate authority on what's public or not, not omissions in the comments or documentation.

ArgumentTypeError is used in an illustration in the 'type' section of the documentation, https://docs.python.org/3/library/argparse.html#type

It also used in the FileType class, which I see as an example of a custom type callable.

In a function like \_get_value it is far easier to test for an custom Error class than to test the message of a more generic class.

The most common `type` functions are `int` and `float`.  Are these custom or generic messages?

    ValueError: invalid literal for int() with base 10: 'one'
    ValueError: could not convert string to float: 'one'

In these common cases the ValueError is converted into a parser.Error call that identifies the argument name, the type, and the bad value, as well as correct usage.

If you issue some other error (e.g. NameError) \_get_value won't catch it, and you'll get the full error stack and no 'usage'.  You'd have to wrap the 'parse_args' call in your own try/except block.

I would think than any anticipated error raised by the type callable will be related to the argument's type.  What other errors do you have in mind?  

I did not mean to say in http://bugs.python.org/issue20039 that you shouldn't use it.  The documentation could be better, but it is available.  If it works for you, use it.

**Comment by a6982a76-b293-41eb-bd2e-00129268a441** [comment]
Paul,

There are a number of scenarios in which you need to check a value and not just a type. For instance, I have a tool with several command-line arguments that need to be \*nonnegative* integers, and a call to int() would not catch that. Many other utilities that ask for an argument of "how many times do you want to do X?" only make sense if you provide a nonnegative number.

Entering dates is another one. There is no callable in the datetime module or built-in that takes only one argument that can be used to validate a date. And if you write your own, you may need to make sure the date is within a specified range: only in the future, only in the past, no more/fewer than X days away from today, etc. My tool receives a date to execute a database query in the form of "select * from table where created_date \>= argument_date." I can perform the validation further into the script, but performing as much validation up front when the arguments are parsed allows you to fail more quickly in the case of invalid input.

I can understand that ArgumentTypeError is available to be used when there is a problem with the arguments' type. But disallowing the use of custom messages in TypeError and ValueError seems like an arbitrary restriction with no pros and at least some cons. I assume that this was not an arbitrary decision and there really was a reason for it, but I can't see what that reason is.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
I didn't mean to question the use of value tests in the 'type' callable.  The ArgumentTypeError example in the documentation does that kind of test.

Argparse is using the term 'type' loosely.  It just means any kind of conversion and/or test that can be applied to a string.

I doubt if \_get_value() ever traps a TypeError.  That error complains about the type of the input argument. As in, for example 'int([])'.  But 'int(astring)' only produces a ValueError.  If the callable issues a TypeError when given a string, it shouldn't be used as a 'type' parameter.

If your prewritten test produces a ValueError, and you don't like the standardization, you can just wrap it in simple function reraises the 'custom' message as an ArgumentTypeError.  There's no other way of identifying a 'custom' message.
