### ISSUE TITLE
xdrlib.Unpacker.unpack_string returns bytes (docs say should be str)

### ISSUE THREAD

**Issue by 65c5baef-7d48-47a0-bce6-4a8fff15928a** [python/cpython#74402]
BPO | [30216](https://bugs.python.org/issue30216)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @zhangyangyu, @rupertnash, @janhn
Superseder | <li>bpo-9544: [doc] xdrlib.Packer().pack_fstring throws a TypeError when called with a str()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-29.16:18:16.830>
created_at = <Date 2017-04-30.11:12:49.436>
labels = ['3.7', 'type-bug', 'library']
title = 'xdrlib.Unpacker.unpack_string returns bytes (docs say should be str)'
updated_at = <Date 2017-05-29.16:20:32.388>
user = 'https://github.com/rupertnash'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-29.16:20:32.388>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-29.16:18:16.830>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-04-30.11:12:49.436>
creator = 'rnash'
dependencies = []
files = []
hgrepos = []
issue_num = 30216
keywords = []
message_count = 5.0
messages = ['292624', '292629', '292635', '294696', '294701']
nosy_count = 5.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'xiang.zhang', 'rnash', 'hnhn']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '9544'
type = 'behavior'
url = 'https://bugs.python.org/issue30216'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 65c5baef-7d48-47a0-bce6-4a8fff15928a** [comment]
According to the docs this method should return a str, but it returns bytes
https://docs.python.org/3.6/library/xdrlib.html#xdrlib.Unpacker.unpack_string

I can see three options:
 a default encoding should be applied
 the documentation updated to make clear this returns bytes
 the method removed and just rely on the existing unpack_bytes which does what you'd expect (and in fact the two methods are aliases)

**Comment by zhangyangyu** [comment]
xdrlib doc seems still remain in 2.x world. 'string' is used to represent 'bytes'. And some methods' names like pack_fstring, pack_string seem not suitable in 3.x world.

**Comment by serhiy-storchaka** [comment]
The term "string" in names like "pack_string" refers to the XDR standard (RFC 1014). They have to stay, but the documentation must be updated to make clear that they work with bytes.

**Comment by 06bbce58-3120-46b9-873e-214d43e32c00** [comment]
There's a patch for xdrlib documentation in bpo-9544. Would that solve this issue?

**Comment by serhiy-storchaka** [comment]
Partially. Thank you for pointing on the predecessor Jan.
