### ISSUE TITLE
Closing a BufferedRandom calls lseek() mutliple times

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74415]
BPO | [30229](https://bugs.python.org/issue30229)
--- | :---
Nosy | @pitrou, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1386</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-11.00:09:08.676>
created_at = <Date 2017-05-02.12:17:53.091>
labels = ['3.7', 'expert-IO', 'performance']
title = 'Closing a BufferedRandom calls lseek() mutliple times'
updated_at = <Date 2017-08-11.00:09:08.675>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-11.00:09:08.675>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-11.00:09:08.676>
closer = 'vstinner'
components = ['IO']
creation = <Date 2017-05-02.12:17:53.091>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30229
keywords = []
message_count = 3.0
messages = ['292749', '292930', '300145']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1386']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30229'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Given the following snippet:

```py
    with open("x", "w+", encoding="utf-8") as fp:
        pass
```


Creating the TextIOWrapper object requires many syscall: see the issue bpo-30228.

But I also noticed that \*closing* such object also requires multiple lseek() syscalls, whereas the snippet doesn't read nor write anything.

Attached PR avoids lseek() if read and write buffers are empty.

**Comment by serhiy-storchaka** [comment]
READAHEAD uses read_end, RAW_OFFSET uses raw_pos. Are you sure that if READAHEAD(self) is zero RAW_OFFSET(self) is zero too?

**Comment by vstinner** [comment]
I closed my PR, so I also close this issue.
