### ISSUE TITLE
[3.5] Warning -- locale was modified by test_idle

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74419]
BPO | [30233](https://bugs.python.org/issue30233)
--- | :---
Nosy | @terryjreedy, @pfmoore, @vstinner, @tjguk, @zware, @zooba
PRs | <li>python/cpython#1397</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = <Date 2017-05-02.21:38:14.614>
created_at = <Date 2017-05-02.16:21:24.194>
labels = ['expert-IDLE', 'type-bug', 'tests', 'OS-windows']
title = '[3.5] Warning -- locale was modified by test_idle'
updated_at = <Date 2017-05-03.09:58:58.510>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-03.09:58:58.510>
actor = 'terry.reedy'
assignee = 'vstinner'
closed = True
closed_date = <Date 2017-05-02.21:38:14.614>
closer = 'terry.reedy'
components = ['IDLE', 'Tests', 'Windows']
creation = <Date 2017-05-02.16:21:24.194>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30233
keywords = []
message_count = 9.0
messages = ['292783', '292792', '292804', '292813', '292831', '292853', '292865', '292867', '292873']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = ['1397']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30233'
versions = ['Python 3.5']
```

</p></details>

**Comment by vstinner** [comment]
Importing idlelib.IOBinding modifies the LC_CTYPE locale. For example, this module is imported by idlelib.EditorWindow which is imported by idlelib.idle_test.test_formatparagraph.

As a consequence, running test_idle changes locales and the following warning is logged:

[3.5] Warning -- locale was modified by test_idle

http://buildbot.python.org/all/builders/AMD64%20Windows10%203.5/builds/224/steps/test/logs/warnings%20%281%29

I didn't check yet why I only see this warning on 3.5 buildbots.

**Comment by terryjreedy** [comment]
The warning, which became a failure in 3.6, was averted for 3.6 by bpo-27372.  I intentionally did not patch 3.5 and merge forward because the warning was neither unique nor a failure, while adding the merge would have been a considerable bother.  Also, I anticipated that the 3.5.3 release after 3.6.0 would be the last 3.5 bugfix release as per normal policy, so that this would be a moot point by now.  (And I have no idea why normal policy was not followed.)  I think this issue should be closed as any of "duplicate", "out of date", or "won't fix".

**Comment by vstinner** [comment]
> I intentionally did not patch 3.5 and merge forward because the warning was neither unique nor a failure,

I modified buildbots to log warnings in all branches. I'm now fixing all warnings to be able to identify quickly real bugs. The warning is reproduced by all 3.5 Windows buildbots.

**Comment by terryjreedy** [comment]
I see.  That changes the situation a bit.

**Comment by terryjreedy** [comment]
Victor, I forgot to ask.  Did you properly test IDLE before committing the patch?  This means building python 3.5, starting IDLE, and exercising the modules affected.  test_idle is nowhere nearly a substitute for such hand-testing.  This is a big part of the 'bother' I referred to.

**Comment by vstinner** [comment]
> Victor, I forgot to ask.  Did you properly test IDLE before committing the patch?  This means building python 3.5, starting IDLE, and exercising the modules affected.  test_idle is nowhere nearly a substitute for such hand-testing.  This is a big part of the 'bother' I referred to.

No, I only ran test_idle. I didn't know that it's not enough.

I ran "./python -m idlelib" and played with the UI: no obvious bug
occurred. I don't know what I am supposed to test.

**Comment by terryjreedy** [comment]
If you can load any existing file into the editor, edit a bit, or maybe cut it down to a print statement, save under a new name, and run it, that should be enough.

**Comment by vstinner** [comment]
> If you can load any existing file into the editor, edit a bit, or maybe cut it down to a print statement, save under a new name, and run it, that should be enough.

I created a latin1 file with a "# coding: latin1" cookie header. I was able to open it in IDLE, run it, edit it, and then reload it. IDLE respected the Latin1 encoding, whereas my locale encoding is UTF-8.

Seems good.

**Comment by terryjreedy** [comment]
Thanks, I feel better now.  This might end up being the only IDLE patch for 3.5.

A test issue for git CI with respect to tkinter and IDLE has been that Travis on Linux does not run 'gui' tests, so it is semi-useless for tk and IDLE.  I notice on [PR 1397](https://github.com/python/cpython/pull/1397) that Appveyor a) ran this time, b)runs on Windows, and c) appears to run gui tests (test_tk and test_ttk_guionly were \*not* skipped).  This is quite helpful.  And, of course, you will notice if one of the stable Windows buildbots running gui tests is not green.
