### ISSUE TITLE
Move quick test in PyObject_IsSubClass outside of PyType_CheckExact guard

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74416]
BPO | [30230](https://bugs.python.org/issue30230)
--- | :---
Nosy | @birkenfeld, @rhettinger, @pitrou, @serhiy-storchaka, @DimitrisJim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-02.14:30:45.015>
labels = ['interpreter-core', '3.8', 'performance']
title = 'Move quick test in PyObject_IsSubClass outside of PyType_CheckExact guard'
updated_at = <Date 2018-12-11.16:13:42.423>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-11.16:13:42.423>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-05-02.14:30:45.015>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 30230
keywords = []
message_count = 8.0
messages = ['292764', '293244', '293379', '293390', '293422', '293471', '306785', '331638']
nosy_count = 5.0
nosy_names = ['georg.brandl', 'rhettinger', 'pitrou', 'serhiy.storchaka', 'Jim Fasarakis-Hilliard']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30230'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-117593

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Currently the first lines in PyObject_IsSubClass are:

```c
    /* We know what type's __subclasscheck__ does. */
    if (PyType_CheckExact(cls)) {
        /* Quick test for an exact match */
        if (derived == cls)
            return 1;
        return recursive_issubclass(derived, cls);
    }
```


The if (derived == cls) runs only if PyType_CheckExact is True which doesn't hold for any classes with a custom metaclass. As a result, a check of the form issubclass(Sequence, Sequence) will take a slow path that invokes \_\_subclasscheck__.

I'm not sure if this was placed inside there due to some wild edge-case, though. PyObject_IsInstance uses the same trick and does so outside the if (PyType_CheckExact(cls)) check.

I'll gladly submit a PR if this indeed needs fixing and not by design.

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
Additional question, are tests required to check this behavior? (Also, bumping)

**Comment by rhettinger** [comment]
Will deeply grokking this code, I would say to leave it alone.  The test seems reasonable and is very fast (likely free of cost on many machines).

**Comment by serhiy-storchaka** [comment]
Jim doesn't propose to remove fast test, it proposes to add a test for fast path for avoiding invoking \_\_subclasscheck__ (this is slow). This can change semantic, but isinstance() already contains such fast path.

This is similar to testing "elem is seq[i]" before "elem == seq[i]" when search in sequences. This optimization changes semantic for NaNs. Does a "Not-A-Class" class which is not a subclass of itself (issubclass(C, C) returns False) makes any sense?

**Comment by rhettinger** [comment]
My point was that it isn't wise to propose PRs for code you don't fully understand (he said, "I'm not sure if this was placed inside there due to some wild edge-case,").

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
> he said, "I'm not sure if this was placed inside there due to some wild edge-case,"

As a new contributor, I'll always lean on the side of me not seeing something rather than confidently stating that something is definitely wrong. I'm new, the code-base is 20 years old and worked on by a dozen of experienced devs :-)

>  Does a "Not-A-Class" class which is not a subclass of itself (issubclass(C, C) returns False) makes any sense?

I'm not sure. Apart from the performance impact, there's a behavioral discrepancy between isinstance and issubclass as you also stated. 

In isinstance, __instancecheck__ doesn't *always* get a chance to override the behavior. The `if type(inst) == Cls` [1] stops it before it gets a chance. 
In issubclass, __subclasscheck__ does override it:

```py
    class Meta(type):
        def __instancecheck__(self, other):
            print("invoked")
            return False
        def __subclasscheck__(self, other):
            print("invoked")
            return False

    class Cls(metaclass=Meta):
        pass
```


    isinstance(Cls(), Cls)
    True

```py
    issubclass(Cls, Cls)
    invoked
    False
```


So, I guess the question might be re-framed to: Is it guaranteed that \_\_instancecheck__ and \_\_subclasscheck__ are \*always* called?

If yes: PyObject_IsInstance should be tweaked.
If no:  PyObject_IsSubclass should be tweaked.

p.s Should I maybe move this to python-dev?

[1]: https://github.com/python/cpython/blob/master/Objects/abstract.c#L2338

**Comment by serhiy-storchaka** [comment]
Yes, please move this to Python-Dev.

**Comment by iritkatriel** [comment]
The documentation says "A class is considered a subclass of itself.", so I think the optimization proposed here is safe. 

https://docs.python.org/3/library/functions.html#issubclass

**Comment by grigoriev-semyon** [comment]
Results:

```bash
➜  semyon cat test.py 
class X(type):
	def __subclasscheck__(self, other):
		return super().__subclasscheck__(other)

class Y(metaclass=X):
	pass

for _ in range(2000000):
	assert issubclass(Y, Y)
➜  semyon time python3.12 test.py
python3.12 test.py  1,82s user 0,01s system 99% cpu 1,834 total
➜  semyon time python3.13 test.py
python3.13 test.py  0,74s user 0,00s system 99% cpu 0,748 total
```

**Comment by grigoriev-semyon** [comment]
Can someone make a hint pls, how to get a `type.__subclasscheck__` method using C API?

I tried
```C
PyObject *type_checker = _PyType_Lookup(&PyType_Type, &_Py_ID(__subclasscheck__));
```
but it doesnt works

**Comment by erlend-aasland** [comment]
@grigoriev-semyon: This question belongs in the *Help* category on Discourse. Regarding your question, see [the C API docs](https://docs.python.org/3/c-api/object.html). I'm marking your (and my post) as off-topic for this issue.

**Comment by AlexWaygood** [comment]
We tried this in #117593, and it was found to break several existing test cases in CPython. I think it's been like this for long enough now that other users of metaclasses will likely be relying on the behaviour staying as it is. As such, I think backwards compatibility means that we shouldn't do this, even if you agree that it makes sense for custom `__subclasscheck__` methods not to be called in some special situations (I'm not sure I _do_ agree).

If somebody else thinks they can optimise this bit of code and wants to tackle it themselves, then please feel free to reopen, but for now I'm closing
