### ISSUE TITLE
remove outdated checks in struct

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74410]
BPO | [30224](https://bugs.python.org/issue30224)
--- | :---
Nosy | @mdickinson, @meadori, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1374</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-15.03:54:57.140>
created_at = <Date 2017-05-02.07:35:05.781>
labels = ['3.7', 'type-feature', 'library']
title = 'remove outdated checks in struct'
updated_at = <Date 2017-05-15.03:54:57.139>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-15.03:54:57.139>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-15.03:54:57.140>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-05-02.07:35:05.781>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30224
keywords = []
message_count = 7.0
messages = ['292724', '292748', '292755', '292762', '292773', '292777', '293668']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'meador.inge', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1374']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30224'
versions = ['Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
Reading struct's code I find some checks seem outdated. They seemly exists because there are two kinds of integer in 2.x. I wrote a patch to remove them but maybe they exist for other reasons I don't see. Sorry if I misunderstand them. :-(

**Comment by serhiy-storchaka** [comment]
Could you please run microbenchmarks for affected code to be sure that changes don't hit performance (if for example PyLong_FromLongLong is significantly slower than PyLong_FromLong)?

**Comment by zhangyangyu** [comment]
There seems no significant regression in performance. A microbenchmark against nu_longlong:

./python3 -m perf timeit --duplicate=1000 --compare-to /home/angwer/repos/cpython/python -s 'import struct; p = struct.Struct("@L")' 'p.unpack(b"d\\x00\\x00\\x00\\x00\\x00\\x00\\x00")'
python: ..................... 156 ns +- 10 ns
python3: ..................... 157 ns +- 9 ns

Median +- std dev: [python] 156 ns +- 10 ns -\> [python3] 157 ns +- 9 ns: 1.01x slower
Not significant!

**Comment by serhiy-storchaka** [comment]
I see a tiny 3% regression.

```sh
$ ./python -m timeit -s 'import struct; u = struct.Struct("100000Q").unpack; b = b"abcd\0\0\0\0"*100000' 'u(b)'
Unpatched:  50 loops, best of 5: 9.34 msec per loop
Patched:    50 loops, best of 5: 9.66 msec per loop

$ ./python -m timeit -s 'import struct; u = struct.Struct("<100000Q").unpack; b = b"abcd\0\0\0\0"*100000' 'u(b)'
Unpatched:  50 loops, best of 5: 9.37 msec per loop
Patched:    50 loops, best of 5: 9.71 msec per loop

$ ./python -m timeit -s 'import struct; u = struct.Struct(">100000Q").unpack; b = b"\0\0\0\0dcba"*100000' 'u(b)'
Unpatched:  20 loops, best of 5: 11.6 msec per loop
Patched:    20 loops, best of 5: 12 msec per loop
```

**Comment by zhangyangyu** [comment]
The test on my box is reverse and stable, python3 is unpatched and python is patched. Anyway, it can't be called significant.

 ./python3 -m perf timeit --compare-to /home/angwer/repos/cpython/python -s 'import struct; u = struct.Struct("100000Q").unpack; b=b"abcd\\x00\\x00\\x00\\x00"\*100000' 'u(b)'
python: ..................... 2.96 ms +- 0.05 ms
python3: ..................... 3.13 ms +- 0.03 ms

Median +- std dev: [python] 2.96 ms +- 0.05 ms -\> [python3] 3.13 ms +- 0.03 ms: 1.06x slower

./python3 -m perf timeit --compare-to /home/angwer/repos/cpython/python -s 'import struct; u = struct.Struct("\<100000Q").unpack; b=b"abcd\\x00\\x00\\x00\\x00"\*100000' 'u(b)'
python: ..................... 2.96 ms +- 0.05 ms
python3: ..................... 3.13 ms +- 0.14 ms

Median +- std dev: [python] 2.96 ms +- 0.05 ms -\> [python3] 3.13 ms +- 0.14 ms: 1.06x slower

./python3 -m perf timeit --compare-to /home/angwer/repos/cpython/python -s 'import struct; u = struct.Struct("\>100000Q").unpack; b=b"\\x00\\x00\\x00\\x00dcba"\*100000' 'u(b)'
python: ..................... 3.51 ms +- 0.09 ms
python3: ..................... 3.67 ms +- 0.06 ms

Median +- std dev: [python] 3.51 ms +- 0.09 ms -\> [python3] 3.67 ms +- 0.06 ms: 1.05x slower

**Comment by serhiy-storchaka** [comment]
Your patch LGTM. Current code in \_struct.c is ugly. I just wonder if it is worth to optimize PyLong_FromLongLong and PyLong_FromUnsignedLongLong if they are slower than PyLong_FromLong and PyLong_FromUnsignedLong.

**Comment by zhangyangyu** [comment]
New changeset 96f502856796f9310fed7161dc540201a4afc1ee by Xiang Zhang in branch 'master':
bpo-30224: remove outdated checks in struct (bpo-1374)
https://github.com/python/cpython/commit/96f502856796f9310fed7161dc540201a4afc1ee
