### ISSUE TITLE
test_imaplib needs a TLS server accepting self-signed certificates

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74417]
BPO | [30231](https://bugs.python.org/issue30231)
--- | :---
Nosy | @gpshead, @pitrou, @vstinner, @larryhastings, @benjaminp, @ned-deily, @berkerpeksag, @vadmium, @dstufft
PRs | <li>python/cpython#1419</li><li>python/cpython#2192</li><li>python/cpython#2193</li><li>python/cpython#2481</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-14.21:01:55.994>
created_at = <Date 2017-05-02.14:44:44.104>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_imaplib needs a TLS server accepting self-signed certificates'
updated_at = <Date 2019-05-10.18:11:27.953>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-10.18:11:27.953>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-14.21:01:55.994>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-02.14:44:44.104>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30231
keywords = []
message_count = 12.0
messages = ['292768', '292840', '292848', '293037', '293131', '293442', '293450', '296017', '296035', '296036', '298743', '298866']
nosy_count = 9.0
nosy_names = ['gregory.p.smith', 'pitrou', 'vstinner', 'larry', 'benjamin.peterson', 'ned.deily', 'berker.peksag', 'martin.panter', 'dstufft']
pr_nums = ['1419', '2192', '2193', '2481']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30231'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The public cyrus.andrew.cmu.edu IMAP server (port 993) doesn't accept TLS connection using our self-signed x509 certificate. The following two tests of test_imaplib were skipped by the issue bpo-30175:

* test_logincapa_with_client_certfile() of RemoteIMAP_SSLTest
* test_logincapa_with_client_ssl_context() of RemoteIMAP_SSLTest

We should either remove these tests or spawn an IMAP server which accepts such certificate on pythontest.net.

@Benjamin: Is there someone available to build such IMAP server on pythontest.net? Or do you suggest to just remove the 2 unit tests?

**Comment by benjaminp** [comment]
I can't say I'm very interested in running a imap server. It would be best if these tests could be replaced by something local. Failing that, I suppose we'll have to remove them.

**Comment by vstinner** [comment]
> It would be best if these tests could be replaced by something local.

Is there someone interested to write such local IMAP server to test test_imaplib using a client x509 certificate?

> Failing that, I suppose we'll have to remove them.

That's not my favorite option, but I wrote a patch for that:
https://github.com/python/cpython/pull/1419

**Comment by vstinner** [comment]
If no one speak up to propose a fix for the two skipped tests before a deadline of two weeks, I will removed them, apply:
https://github.com/python/cpython/pull/1419

**Comment by berkerpeksag** [comment]
I'd suggest marking them with @unittest.expectedFailure as an alternative way to move forward.

**Comment by vstinner** [comment]
> I'd suggest marking them with @unittest.expectedFailure as an alternative way to move forward.

I don't understand the purpose of tests known to fail. Is it to validate that we have bugs? :)

**Comment by berkerpeksag** [comment]
> Is it to validate that we have bugs? :)

More or less, yes. Since the problem is not in the library code and the tests are not completely useless, using @unittest.expectedFailure might be a better short term solution than skipping or removing them (at least we are not going to forget them :))

Yet another alternative is to tweak test_logincapa_with_client_certfile to just check for DeprecationWarning. See https://github.com/python/cpython/pull/1419/files#r115050499 for details.

**Comment by vstinner** [comment]
New changeset b18563da8803433509e9a0e29718e0271014659f by Victor Stinner in branch 'master':
bpo-30231: Remove skipped test_imaplib tests (bpo-1419)
https://github.com/python/cpython/commit/b18563da8803433509e9a0e29718e0271014659f

**Comment by vstinner** [comment]
New changeset 8a39af945796164a16a607fecfef5297b7a87deb by Victor Stinner in branch '3.6':
bpo-30231: Remove skipped test_imaplib tests (bpo-1419) (bpo-2192)
https://github.com/python/cpython/commit/8a39af945796164a16a607fecfef5297b7a87deb

**Comment by vstinner** [comment]
New changeset 7895a0585b4b6a1c8082d17227307c6ce2c8bb8b by Victor Stinner in branch '3.5':
bpo-30231: Remove skipped test_imaplib tests (bpo-1419) (bpo-2193)
https://github.com/python/cpython/commit/7895a0585b4b6a1c8082d17227307c6ce2c8bb8b

**Comment by ned-deily** [comment]
New changeset b5f20ea91ec4d9dc7e1c31629903888c651bd02c by Ned Deily (Victor Stinner) in branch '3.3':
[3.3] Backport CI config from master and remove skipped imaplib tests (bpo-2481)
https://github.com/python/cpython/commit/b5f20ea91ec4d9dc7e1c31629903888c651bd02c

**Comment by larryhastings** [comment]
New changeset b1549175ed30f2931e2bb980a7e3c360ed19e1c9 by larryhastings (Victor Stinner) in branch '3.4':
[3.4] Backport CI config from master (bpo-2475)
https://github.com/python/cpython/commit/b1549175ed30f2931e2bb980a7e3c360ed19e1c9
