### ISSUE TITLE
resolve undefined behaviour in struct

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74428]
BPO | [30242](https://bugs.python.org/issue30242)
--- | :---
Nosy | @mdickinson, @meadori, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1418</li><li>python/cpython#1586</li><li>python/cpython#1587</li><li>python/cpython#1588</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-15.05:19:43.392>
created_at = <Date 2017-05-03.04:30:53.895>
labels = ['3.7', 'type-bug', 'library']
title = 'resolve undefined behaviour in struct'
updated_at = <Date 2017-05-15.05:19:43.391>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-15.05:19:43.391>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-15.05:19:43.392>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-05-03.04:30:53.895>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30242
keywords = []
message_count = 10.0
messages = ['292836', '292839', '292843', '292844', '292845', '292847', '293670', '293674', '293675', '293676']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'meador.inge', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1418', '1586', '1587', '1588']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30242'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
In struct there are several places using code like:

  p[--i] = (char)x;

to extract the least significant byte from a long. Although this behaviour seems to apply to common implementations but it does not conform to C standard.

**Comment by serhiy-storchaka** [comment]
I think it is better to change the type of p to unsigned char.

**Comment by zhangyangyu** [comment]
> I think it is better to change the type of p to unsigned char.

Good advice.

**Comment by serhiy-storchaka** [comment]
I meant changing the type of the first argument of np_ubyte() etc.

```py
np_ubyte(unsigned char *p, PyObject *v, const formatdef *f)
```

**Comment by zhangyangyu** [comment]
Hmm, do we need to? Currently all pack routines accept a char \*p. Converting it to unsigned char * inside could also solve the problem.

**Comment by serhiy-storchaka** [comment]
Your patch LGTM as a minimal patch for backporting to maintained releases (maybe Mark have other comments). But I think it would be better to make all pointers to raw memory of type unsigned char*. Not just packing, but unpacking too. Using even memcpy between long* and char* is undefined behavior, the source and target should either have the same type, or one of them be unsigned char*.

**Comment by zhangyangyu** [comment]
New changeset 981096f98b9c131594b0ac85ad01b63cbd11aa0a by Xiang Zhang in branch 'master':
bpo-30242: resolve some undefined behaviours in struct (bpo-1418)
https://github.com/python/cpython/commit/981096f98b9c131594b0ac85ad01b63cbd11aa0a

**Comment by zhangyangyu** [comment]
New changeset aad1caf55f7fadb00ee097a1465bece4e128d8ef by Xiang Zhang in branch '3.6':
bpo-30242: resolve some undefined behaviours in struct (bpo-1418) (bpo-1586)
https://github.com/python/cpython/commit/aad1caf55f7fadb00ee097a1465bece4e128d8ef

**Comment by zhangyangyu** [comment]
New changeset dd2a09cf98845b1460f0e049ad0ffeeb5c6c6476 by Xiang Zhang in branch '3.5':
bpo-30242: resolve some undefined behaviours in struct (bpo-1418) (bpo-1587)
https://github.com/python/cpython/commit/dd2a09cf98845b1460f0e049ad0ffeeb5c6c6476

**Comment by zhangyangyu** [comment]
New changeset 982a17e02d99dcf6e4dff93110cff5ecc59247f5 by Xiang Zhang in branch '2.7':
bpo-30242: resolve some undefined behaviours in struct (bpo-1418) (bpo-1588)
https://github.com/python/cpython/commit/982a17e02d99dcf6e4dff93110cff5ecc59247f5
