### ISSUE TITLE
Using boolean arguments in the _json module

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74434]
BPO | [30248](https://bugs.python.org/issue30248)
--- | :---
Nosy | @rhettinger, @etrepum, @ezio-melotti, @serhiy-storchaka, @MojoVampire
PRs | <li>python/cpython#1423</li>
Dependencies | <li>bpo-30243: Core dump when use uninitialized _json objects</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-05-28.12:32:50.052>
created_at = <Date 2017-05-03.08:38:15.688>
labels = ['extension-modules', '3.7', 'performance']
title = 'Using boolean arguments in the _json module'
updated_at = <Date 2017-05-28.12:32:50.051>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-28.12:32:50.051>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-05-28.12:32:50.052>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-05-03.08:38:15.688>
creator = 'serhiy.storchaka'
dependencies = ['30243']
files = []
hgrepos = []
issue_num = 30248
keywords = []
message_count = 5.0
messages = ['292861', '292932', '293132', '293202', '294644']
nosy_count = 5.0
nosy_names = ['rhettinger', 'bob.ippolito', 'ezio.melotti', 'serhiy.storchaka', 'josh.r']
pr_nums = ['1423']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30248'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Currently PyObject_IsTrue() is called every time when bool attributes (_json.Scanner.strict, \_json.Encoder.sort_keys, \_json.Encoder.skipkeys) are used in C acceleration of the json module. PyObject_IsTrue() is fast when the argument is a bool, but in any case this isn't efficient and is cumbersome. It is better to convert Python bool to C boolean value only once when create an object, as already is done for \_json.Encoder.allow_nan and for most other boolean values in extension modules.

Proposed patch simplifies and optimizes the code by making arguments strict, sort_keys and skipkeys be converted only once at argument parsing time.

The patch changes behavior in the case when the boolean value of the argument is not constant. But this is very bad practice, we may ignore this obscure case (as ignore the case when the boolean value of the container doesn't consistent with its content, see bpo-27613).

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
So, incredibly minor note:

This will prevent a ridiculous use case of passing in a mutable object as the argument (say, a list), and mutating it between truthy and falsy values (appending or clearing) to toggle behaviors in an existing Encoder.

Note: As stated, this is a ridiculous use case, and I don't think we should be handcuffed by compatibility with an insane behavior that no one has likely ever used. The docs never guarantee that those values are examined live, so it's an implementation detail, and not a useful one at that. I just want to mention it so there is a small note in MISC/News or the like to document that slight tweak in observed behavior.

Otherwise, change looks good to me.

**Comment by serhiy-storchaka** [comment]
Initially I was going to add explicit bool() calls in Python implementations, so that Python and C implementation behave the same in case of non-constant options. But then I figured out that is behavior is insane and we shouldn't guarantee anything in this case. If we don't bother to satisfy matching the behavior in Python and C implementations, this change is not worth to be mentioned in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS).

**Comment by rhettinger** [comment]
This looks like a nice improvement.

**Comment by serhiy-storchaka** [comment]
New changeset ac5bbd43bc7b769c13ae0412cb28a3521f4d4ff1 by Serhiy Storchaka in branch 'master':
bpo-30248: Convert boolean arguments only once in \_json. (bpo-1423)
https://github.com/python/cpython/commit/ac5bbd43bc7b769c13ae0412cb28a3521f4d4ff1
