### ISSUE TITLE
fix several error messages in struct

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74432]
BPO | [30246](https://bugs.python.org/issue30246)
--- | :---
Nosy | @mdickinson, @bitdancer, @meadori, @berkerpeksag, @vadmium, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1421</li><li>python/cpython#3561</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-14.03:23:45.295>
created_at = <Date 2017-05-03.07:37:18.539>
labels = ['3.7', 'type-bug', 'library']
title = 'fix several error messages in struct'
updated_at = <Date 2017-09-14.03:23:45.293>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-14.03:23:45.293>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-14.03:23:45.295>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-05-03.07:37:18.539>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30246
keywords = ['patch']
message_count = 5.0
messages = ['292854', '292859', '302116', '302137', '302139']
nosy_count = 7.0
nosy_names = ['mark.dickinson', 'r.david.murray', 'meador.inge', 'berker.peksag', 'martin.panter', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1421', '3561']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30246'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
There are several error messages only mention bytes. But they may also accept string or other bytes-like objects.

**Comment by serhiy-storchaka** [comment]
"unpack requires a bytes-like object of length %zd" is not correct too. array.array('i', [1, 2, 3]) has length 3, but Struct('3b').unpack doesn't accept it. The more correct error message is "unpack requires an object containing %zd bytes" (or "a buffer"). The similar issue was discussed some time ago, but I don't remember what module was discussed and who participated in that discussion.

**Comment by vadmium** [comment]
FWIW a similar change to the Struct constructor message was also proposed in bpo-19985.

**Comment by zhangyangyu** [comment]
New changeset c3e97d9d984130d1c2aceedc4dfcd603b3162688 by Xiang Zhang in branch 'master':
bpo-30246: fix several error messages which only mention bytes in struct (bpo-1421)
https://github.com/python/cpython/commit/c3e97d9d984130d1c2aceedc4dfcd603b3162688

**Comment by zhangyangyu** [comment]
New changeset fa82dda1012b406a7091587fc65384ce11528346 by Xiang Zhang in branch '3.6':
[3.6] bpo-30246: fix several error messages which only mention bytes in struct (bpo-3561)
https://github.com/python/cpython/commit/fa82dda1012b406a7091587fc65384ce11528346
