### ISSUE TITLE
Windows Visual Studio solution does not have an install target

### ISSUE THREAD

**Issue by 271e878f-1235-4b2e-b652-7a77057c8224** [python/cpython#74437]
BPO | [30251](https://bugs.python.org/issue30251)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-13.06:39:44.861>
created_at = <Date 2017-05-03.09:55:08.199>
labels = ['invalid', 'build', '3.7', 'OS-windows']
title = 'Windows Visual Studio solution does not have an install target'
updated_at = <Date 2017-07-13.18:13:00.172>
user = 'https://bugs.python.org/steveire'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-13.18:13:00.172>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-13.06:39:44.861>
closer = 'steve.dower'
components = ['Build', 'Windows']
creation = <Date 2017-05-03.09:55:08.199>
creator = 'steveire'
dependencies = []
files = []
hgrepos = []
issue_num = 30251
keywords = []
message_count = 4.0
messages = ['292872', '293236', '298270', '298304']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'steveire', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30251'
versions = ['Python 3.7']
```

</p></details>

**Comment by 271e878f-1235-4b2e-b652-7a77057c8224** [comment]
The Windows Visual Studio solution does not have an install target. As far as I understand, the configure system used on Unix does have an install target.

That means that on Windows, binaries resulting from the build to not end up in the same layout as result from using the official installer. 

Third party modules expect the same layout. For example, Sip/PyQt requires it https://www.riverbankcomputing.com/pipermail/pyqt/2017-April/039109.html . There are probably other modules similarly affected.

I don't know what else an install target should do, but I note its absence.

**Comment by zooba** [comment]
Visual Studio has some deployment concepts, but for multi-project solutions like ours you would generally have a separate project. It's a build tool, not an install tool, and mixing the concepts is generally a bad idea.

For building an installer, these projects are in tools/msi.

For doing a quick layout, we could write a script to simply copy files around. There are scripts in [Tools/msi](https://github.com/python/cpython/blob/main/Tools/msi) that do some of this already that could be adapted.

**Comment by 271e878f-1235-4b2e-b652-7a77057c8224** [comment]
This is resolved as not a bug.

Is there a way to convert it to a feature request?

**Comment by zooba** [comment]
Sure, but then I'll resolve it as rejected :)

The solution does not need an install target. That's not the point - we have separate projects and scripts for that.
