### ISSUE TITLE
[2.7] regrtest: handle child process crash

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74444]
BPO | [30258](https://bugs.python.org/issue30258)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1431</li><li>python/cpython#1477</li><li>python/cpython#1479</li><li>python/cpython#2244</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-17.00:27:05.542>
created_at = <Date 2017-05-03.14:25:28.802>
labels = ['tests']
title = '[2.7] regrtest: handle child process crash'
updated_at = <Date 2017-06-16.12:39:12.093>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.12:39:12.093>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-17.00:27:05.542>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-03.14:25:28.802>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30258
keywords = []
message_count = 12.0
messages = ['292904', '292906', '292907', '292911', '293078', '293079', '293085', '293086', '293089', '293296', '293829', '296190']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['1431', '1477', '1479', '2244']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30258'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
In the master branch, regrtest in multiprocess mode handles well crash of child processes. In 2.7, regrtest handles them badly: see issue bpo-30254.

Attached PR backports the CHILD_ERROR status from regrtest master and adds code to handle crash (or any non-zero exit code) of the child process (a worker running an unit test).

**Comment by serhiy-storchaka** [comment]
Victor, you are just incredible!

**Comment by vstinner** [comment]
New changeset c991eb280e60ed25c68a5332bd8633959e9f7113 by Victor Stinner in branch '2.7':
bpo-30258: regrtest handles child process crash (bpo-1431)
https://github.com/python/cpython/commit/c991eb280e60ed25c68a5332bd8633959e9f7113

**Comment by vstinner** [comment]
Ooops, there is a bug in my pushed changed, spotted by Serhiy:

>                      # Strip last refcount output line if it exists, since it
                     \# comes from the shutdown of the interpreter in the subcommand.
                     stderr = debug_output_pat.sub("", stderr)
\+
\+                    if retcode != 0:
\+                        result = (CHILD_ERROR, "Exit code %s" % retcode)
\+                        output.put((test, stdout.rstrip(), stderr.rstrip(),
\+                                    result))
+

Missed return?

**Comment by vstinner** [comment]
New changeset 228da42961ac9bf2990e6c191ecc9b762ead617c by Victor Stinner in branch '2.7':
bpo-30258: Fix handling of child error in regrtest (bpo-1477)
https://github.com/python/cpython/commit/228da42961ac9bf2990e6c191ecc9b762ead617c

**Comment by vstinner** [comment]
@Serhiy: I fixed the bug you found. Don't hesitate to propose directly a PR if I missed something (or open an issue, it's up to you).

At least, regrtest of Python 2.7 should now handle correctly crashes when using -jN.

**Comment by serhiy-storchaka** [comment]
You just pressed the merge button 2 minutes before I finished a review.

**Comment by serhiy-storchaka** [comment]
Do you mind to port changes to 3.x?

**Comment by vstinner** [comment]
> You just pressed the merge button 2 minutes before I finished a review.

Oh sorry, I didn't expect a review on this small change.

> Do you mind to port changes to 3.x?

I created https://github.com/python/cpython/pull/1479 for the run_tests_multiprocess() bugfix.

**Comment by vstinner** [comment]
New changeset 74683fc6247c522ae955a6e7308b8ff51def35d8 by Victor Stinner in branch 'master':
bpo-30258: regrtest: Fix run_tests_multiprocess() (bpo-1479)
https://github.com/python/cpython/commit/74683fc6247c522ae955a6e7308b8ff51def35d8

**Comment by vstinner** [comment]
Python 2.7 now has test_regrtest and test_regrtest pass on all 2.7 buildbots, so I close the issue.

**Comment by vstinner** [comment]
New changeset a0ccc54e6dffacf9e7c06f2a3e9056d2d35d21eb by Victor Stinner in branch '3.6':
Synchronize libregrtest from master to 3.6 (bpo-2244)
https://github.com/python/cpython/commit/a0ccc54e6dffacf9e7c06f2a3e9056d2d35d21eb
