### ISSUE TITLE
test_xml_etree: python: Objects/sliceobject.c:176: _PySlice_AdjustIndices: Assertion `step >= -PY_SSIZE_T_MAX' failed.

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74441]
BPO | [30255](https://bugs.python.org/issue30255)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1429</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.08:26:40.362>
created_at = <Date 2017-05-03.11:06:38.690>
labels = ['interpreter-core', 'type-crash']
title = "test_xml_etree: python: Objects/sliceobject.c:176: _PySlice_AdjustIndices: Assertion `step >= -PY_SSIZE_T_MAX' failed."
updated_at = <Date 2017-05-05.08:26:40.361>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.08:26:40.361>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.08:26:40.362>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-05-03.11:06:38.690>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30255
keywords = []
message_count = 8.0
messages = ['292888', '292894', '292898', '292901', '292902', '292903', '293036', '293075']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1429']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30255'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
```pytb
./python -m test -v test_xml_etree
...
test_getslice_negative_steps (test.test_xml_etree.ElementSlicingTest) ...
python: Objects/sliceobject.c:176: _PySlice_AdjustIndices: Assertion `step >= -PY_SSIZE_T_MAX' failed.
...
Traceback (most recent call first):
  File "/home/haypo/prog/python/2.7/Lib/xml/etree/ElementTree.py", line 266, in __getitem__
    return self._children[index]
  File "/home/haypo/prog/python/2.7/Lib/test/test_xml_etree.py", line 2305, in test_getslice_negative_steps
    self.assertEqual(self._elem_tags(e[3::-sys.maxsize-1]), ['a3'])
```


See issues: bpo-30074, bpo-27867.

**Comment by vstinner** [comment]
Attached PR fixes test_xml_etree.

**Comment by serhiy-storchaka** [comment]
Thank you Victor for noticing and fixing this crash!

**Comment by vstinner** [comment]
New changeset f6a3133972378205baaa6a854d46170d04a2db67 by Victor Stinner in branch '2.7':
bpo-30255: Clip step in \_PySlice_Unpack() (bpo-1429)
https://github.com/python/cpython/commit/f6a3133972378205baaa6a854d46170d04a2db67

**Comment by vstinner** [comment]
I pushed the change to try to fix buildbots, but I'm not sure that it's complete.

The change announces "... clip the step to [-PY_SSIZE_T_MAX,
PY_SSIZE_T_MAX] ...", but there is no explicit to clip the maximum to PY_SSIZE_T_MAX. Maybe there is a bug on this side too! The code should be reviewed one more time.

**Comment by vstinner** [comment]
> Thank you Victor for noticing and fixing this crash!

Something is \*very* strange: we have +20 buildbots, but I didn't see this assertion failure on any buildbot. Instead, I noticed that regrtest runs less tests than announced: see issue bpo-30254.

It's very strange because I expect either a crash: regrtest stops with no more output, or a report of the crash. But no, regrtest displays the summary as everything was fine...

**Comment by vstinner** [comment]
> It's very strange because I expect either a crash: regrtest stops with no more output, or a report of the crash. But no, regrtest displays the summary as everything was fine...

It was a bug in regrtest: now fixed by bpo-30258.

**Comment by vstinner** [comment]
> The change announces "... clip the step to [-PY_SSIZE_T_MAX, PY_SSIZE_T_MAX] ...", but there is no explicit to clip the maximum to PY_SSIZE_T_MAX. Maybe there is a bug on this side too! The code should be reviewed one more time.

Ok, I checked: \_PySlice_Unpack() uses \_PyEval_SliceIndex() to convert the step Python object into a C Py_ssize_t, so the code is already correct: it does "clip the step to [-PY_SSIZE_T_MAX, PY_SSIZE_T_MAX]" as announced ;-) I close the issue.

Thanks Serhiy for your work on fixing corner cases related to slices ;-)
