### ISSUE TITLE
_bsddb: else misleadingly indented

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74443]
BPO | [30257](https://bugs.python.org/issue30257)
--- | :---
Nosy | @jcea, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1428</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.08:30:16.284>
created_at = <Date 2017-05-03.12:04:41.408>
labels = ['extension-modules']
title = '_bsddb: else misleadingly indented'
updated_at = <Date 2017-05-05.08:30:16.283>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.08:30:16.283>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.08:30:16.284>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-05-03.12:04:41.408>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30257
keywords = []
message_count = 5.0
messages = ['292890', '292892', '292908', '292909', '292918']
nosy_count = 3.0
nosy_names = ['jcea', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1428']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30257'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
building '\_bsddb' extension
gcc -pthread -fPIC -fno-strict-aliasing -O0 -g -O0 -Wall -Wstrict-prototypes -I/usr/include -I. -IInclude -I./Include -I/usr/local/include -I/home/haypo/prog/python/2.7/Include -I/home/haypo/prog/python/2.7 -c /home/haypo/prog/python/2.7/Modules/_bsddb.c -o build/temp.linux-x86_64-2.7-pydebug/home/haypo/prog/python/2.7/Modules/_bsddb.o
/home/haypo/prog/python/2.7/Modules/_bsddb.c: Dans la fonction « newDBObject »:
/home/haypo/prog/python/2.7/Modules/_bsddb.c:936:5: attention : this « else » clause does not guard... [-Wmisleading-indentation]
     else
     ^~~~
/home/haypo/prog/python/2.7/Modules/_bsddb.c:938:9: note : ...this statement, but the latter is misleadingly indented as if it is guarded by the « else »
         self-\>moduleFlags.cursorSetReturnsNone = DEFAULT_CURSOR_SET_RETURNS_NONE;
         ^~~~
gcc -pthread -shared build/temp.linux-x86_64-2.7-pydebug/home/haypo/prog/python/2.7/Modules/_bsddb.o -L/usr/lib64 -L/usr/local/lib -Wl,-R/usr/lib64 -ldb-5.3 -o build/lib.linux-x86_64-2.7-pydebug/_bsddb.so


I agree that the indentation is surprising and looks like a bug.

    if (self->myenvobj)
        self->moduleFlags = self->myenvobj->moduleFlags;
    else
        self->moduleFlags.getReturnsNone = DEFAULT_GET_RETURNS_NONE;
        self->moduleFlags.cursorSetReturnsNone = DEFAULT_CURSOR_SET_RETURNS_NONE;


Attached PR only don't set cursorSetReturnsNone to DEFAULT_CURSOR_SET_RETURNS_NONE anymore if self-\>myenvobj is set.

**Comment by vstinner** [comment]
The second line in the else block was added... 14 years ago (!) by this commit:

commit 455d46f0d921337405ebd3a098c210f3614ae77c
Author: Gregory P. Smith \<greg@mad-scientist.com\>
Date:   Wed Jul 9 04:45:59 2003 +0000

    bsddb 4.1.6:
    
     * Extended DB & DBEnv set_get_returns_none functionality to take a
       "level" instead of a boolean flag.  The boolean 0 and 1 values still
       have the same effect.  A value of 2 extends the "return None instead
       of raising an exception" behaviour to the DBCursor set methods.
       This will become the default behaviour in pybsddb 4.2.
     * Fixed a typo in DBCursor.join_item method that made it crash instead
       of returning a value.  Obviously nobody uses it.  Wrote a test case
       for join and join_item.

**Comment by serhiy-storchaka** [comment]
It looks to me that the valid combinations of getReturnsNone and cursorSetReturnsNone flags are 00, 10 and 11. But this suspicious code allows to get 01. It looks as a bug to me.

**Comment by vstinner** [comment]
New changeset 2c27731901003cbcc64056fe9db725abe8484616 by Victor Stinner in branch '2.7':
bpo-30257: \_bsddb: Fix newDBObject() (bpo-1428)
https://github.com/python/cpython/commit/2c27731901003cbcc64056fe9db725abe8484616

**Comment by vstinner** [comment]
I don't understand well the consequence of the change, so I didn't document it in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) :-)
