### ISSUE TITLE
Make mimetypes.guess_type accept path-like objects

### ISSUE THREAD

**Issue by 8a616333-8514-433f-9780-5538a80023ef** [python/cpython#74454]
BPO | [30268](https://bugs.python.org/issue30268)
--- | :---
Nosy | @bitdancer, @progval, @serhiy-storchaka
Superseder | <li>bpo-34926: Allow querying a Path&#x27;s mime-type</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-18.09:28:49.113>
created_at = <Date 2017-05-04.16:08:06.793>
labels = ['library']
title = 'Make mimetypes.guess_type accept path-like objects'
updated_at = <Date 2022-01-18.09:28:49.113>
user = 'https://github.com/ProgVal'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-18.09:28:49.113>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-18.09:28:49.113>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2017-05-04.16:08:06.793>
creator = 'Valentin.Lorentz'
dependencies = []
files = []
hgrepos = []
issue_num = 30268
keywords = []
message_count = 5.0
messages = ['292995', '293106', '293107', '293108', '293115']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'Valentin.Lorentz', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '34926'
type = None
url = 'https://bugs.python.org/issue30268'
versions = []
```

</p></details>

**Comment by 8a616333-8514-433f-9780-5538a80023ef** [comment]
The documentation for mimetypes.guess_type says that it “guesses the type of a file based on its filename or URL”.

However, this function only accepts a string object, and not a bytes object:

```pycon
>>> import os
>>> import mimetypes
>>> mimetypes.guess_type(os.listdir(os.fsencode('./'))[0])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.7/mimetypes.py", line 291, in guess_type
    return _db.guess_type(url, strict)
  File "/usr/lib/python3.7/mimetypes.py", line 116, in guess_type
    scheme, url = urllib.parse.splittype(url)
  File "/usr/lib/python3.7/urllib/parse.py", line 924, in splittype
    match = _typeprog.match(url)
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by bitdancer** [comment]
Why do you think this is a bug?

**Comment by bitdancer** [comment]
To clarify my question, I don't think it is a bug, but the fact that you do might mean there needs to be a doc clarification.  Or it might not.  Or, there might be a desirable enhancement here, maybe relating to the pathlike protocol.

**Comment by serhiy-storchaka** [comment]
There were issues with mimetypes.guess_type() on Windows in Python 2 (bpo-9291 and a number of duplicate issues). I afraid that adding support of bytes paths will return the hell from which we ran in Python 3.

**Comment by 8a616333-8514-433f-9780-5538a80023ef** [comment]
@r.david.murray I don't think it's a bug either, but a possible enhancement.

@serhiy.storchaka We could simply do this: if isinstance(url, bytes):  url = os.fsdecode(url)
