### ISSUE TITLE
[2.7] test.support.unlink() should fail or emit a warning on WindowsError: [Error 32] The process cannot access the file ...

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74451]
BPO | [30265](https://bugs.python.org/issue30265)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware, @zooba
PRs | <li>python/cpython#1456</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.08:28:25.677>
created_at = <Date 2017-05-04.00:03:15.298>
labels = ['tests', 'OS-windows', 'performance']
title = '[2.7] test.support.unlink() should fail or emit a warning on WindowsError: [Error 32] The process cannot access the file ...'
updated_at = <Date 2017-05-05.08:28:25.676>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.08:28:25.676>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.08:28:25.677>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-05-04.00:03:15.298>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30265
keywords = []
message_count = 5.0
messages = ['292949', '292980', '292982', '293076', '293077']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'zach.ware', 'steve.dower']
pr_nums = ['1456']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30265'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
While working on issue bpo-30264, I noticed that test.support.unlink() ignores \*all* OSError exceptions. I suggest to add handle WindowsError: [Error 32] differently.

Example of such error, issue bpo-15388:

WindowsError: [Error 32] The process cannot access the file because it is being used by another process:

I suggest to either raise an exception (passthrough the original OSError), or emit/log a warning.

**Comment by jkloth** [comment]
Looking at test.support, the only errors that I can see being ignored by unlink() is FileNotFoundError and NotADirectoryError (line 399). The only bare OSError except clause is on line 359, but for an lstat() call.

**Comment by vstinner** [comment]
> Looking at test.support, the only errors that I can see being ignored by unlink() is FileNotFoundError and NotADirectoryError (line 399)

Oh wait, I was looking at Python 2.7 code:

```py
def unlink(filename):
    try:
        _unlink(filename)
    except OSError:
        pass
```


So this issuse seems to be specific to Python 2.7.

**Comment by vstinner** [comment]
New changeset 03b278895fa0db355af4e450eac71dd0532db394 by Victor Stinner in branch '2.7':
bpo-30265: support.unlink() don't catch any OSError (bpo-1456)
https://github.com/python/cpython/commit/03b278895fa0db355af4e450eac71dd0532db394

**Comment by vstinner** [comment]
Ok, fixed.
