### ISSUE TITLE
Remove sqlite3.Cache display method

### ISSUE THREAD

**Issue by 1b8b9392-df29-400a-8625-f44843db437b** [python/cpython#74456]
BPO | [30270](https://bugs.python.org/issue30270)
--- | :---
Nosy | @brettcannon, @bitdancer, @berkerpeksag, @palaviv
PRs | <li>python/cpython#1462</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-23.05:55:18.905>
created_at = <Date 2017-05-04.18:49:54.747>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'Remove sqlite3.Cache display method'
updated_at = <Date 2018-07-23.05:55:18.904>
user = 'https://github.com/palaviv'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-23.05:55:18.904>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-23.05:55:18.905>
closer = 'berker.peksag'
components = ['Extension Modules']
creation = <Date 2017-05-04.18:49:54.747>
creator = 'palaviv'
dependencies = []
files = []
hgrepos = []
issue_num = 30270
keywords = []
message_count = 7.0
messages = ['293005', '293023', '293053', '293124', '293130', '293137', '322177']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ghaering', 'r.david.murray', 'berker.peksag', 'palaviv']
pr_nums = ['1462']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30270'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
The display method is there for debugging and should not be in the released code.

**Comment by brettcannon** [comment]
How long has the method been there? And does it hurt anything for it to be exposed? Removing it at this point may break code if it predates Python 3.7.

**Comment by 1b8b9392-df29-400a-8625-f44843db437b** [comment]
From looking at the git blame this is there since 2006. Maybe this should be dependent on issue bpo-30262. Maybe at first there should be a deprecation warning and then removing this later.
I understand that this might break someone's code but this is an undocumented method of an undocumented class in the sqlite3 module. I don't think that there will be a lot of people that use the sqlite3.Cache object.

**Comment by brettcannon** [comment]
With over 10 years of existence for that method, I can guarantee you someone relies on it, and so we should do a reasonable job to avoid breaking them without at least some warning first.

**Comment by bitdancer** [comment]
If it is there for debugging, why would we want to remove it?

**Comment by berkerpeksag** [comment]
FWIW, I agree with Brett and David. Did you try to use it? I prefer to fix it even if it's broken at the moment.
