### ISSUE TITLE
AbstractContextManager should support __method__ = None

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#74452]
BPO | [30266](https://bugs.python.org/issue30266)
--- | :---
Nosy | @gvanrossum, @ncoghlan, @1st1, @ilevkivskyi, @JelleZijlstra, @Mariatta
PRs | <li>python/cpython#1448</li><li>python/cpython#2054</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-06-10.03:38:08.981>
created_at = <Date 2017-05-04.03:37:32.485>
labels = ['3.7', 'library']
title = 'AbstractContextManager should support __method__ = None'
updated_at = <Date 2017-06-10.04:37:55.104>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.04:37:55.104>
actor = 'JelleZijlstra'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-06-10.03:38:08.981>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-05-04.03:37:32.485>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 30266
keywords = []
message_count = 7.0
messages = ['292955', '295541', '295547', '295603', '295604', '295607', '295608']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'ncoghlan', 'yselivanov', 'levkivskyi', 'JelleZijlstra', 'Mariatta']
pr_nums = ['1448', '2054']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30266'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
Like other ABCs, contextlib.AbstractContextManager should support the pattern where setting a method to None disables structural subtyping, which was introduced across the standard library in bpo-25958. Ivan Levkivskyi suggested making AbstractContextManager support this pattern in CR comments in https://github.com/python/cpython/pull/1412/files#r114482765.

Should this change be applied to 3.6 as well as master? I'm leaning towards yes, because the resolution to bpo-25958 (https://hg.python.org/cpython/rev/72b9f195569c) added a general statement in the documentation that "Setting a special method to ``None`` indicates that the corresponding operation is not available". Thus, the fact that contextlib.AbstractContextManager doesn't obey this rule is a bug.

I'll send a PR shortly.

**Comment by gvanrossum** [comment]
New changeset 57161aac5eb9bcb0b43e551a1937ff0a84c1ec52 by Guido van Rossum (Jelle Zijlstra) in branch 'master':
bpo-30266: support "= None" pattern in AbstractContextManager (bpo-1448)
https://github.com/python/cpython/commit/57161aac5eb9bcb0b43e551a1937ff0a84c1ec52

**Comment by gvanrossum** [comment]
This should be backported to 3.6.

**Comment by Mariatta** [comment]
New changeset 753422f6e32e13d96319b090788f0474f1e21fc4 by Mariatta in branch '3.6':
bpo-30266: support "= None" pattern in AbstractContextManager (GH-1448) (GH-2054)
https://github.com/python/cpython/commit/753422f6e32e13d96319b090788f0474f1e21fc4

**Comment by Mariatta** [comment]
PR has been backported to 3.6.

Thanks :)

**Comment by gvanrossum** [comment]
Thanks Mariatta!

**Comment by JelleZijlstra** [comment]
Thanks for doing the merge and backport!
