### ISSUE TITLE
set stop default to -PY_SSIZE_T_MAX-1 in PySlice_Unpack

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74467]
BPO | [30281](https://bugs.python.org/issue30281)
--- | :---
Nosy | @mdickinson, @vstinner, @serhiy-storchaka, @zhangyangyu
PRs | <li>python/cpython#1480</li><li>python/cpython#1529</li><li>python/cpython#1530</li><li>python/cpython#1531</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-10.11:21:37.377>
created_at = <Date 2017-05-05.10:47:45.512>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'set stop default to -PY_SSIZE_T_MAX-1 in PySlice_Unpack'
updated_at = <Date 2017-05-10.11:21:37.376>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.11:21:37.376>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-10.11:21:37.377>
closer = 'xiang.zhang'
components = ['Interpreter Core']
creation = <Date 2017-05-05.10:47:45.512>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30281
keywords = []
message_count = 8.0
messages = ['293097', '293098', '293101', '293116', '293396', '293399', '293400', '293402']
nosy_count = 4.0
nosy_names = ['mark.dickinson', 'vstinner', 'serhiy.storchaka', 'xiang.zhang']
pr_nums = ['1480', '1529', '1530', '1531']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30281'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
The default value for stop in PySlice_Unpack should be -PY_SSIZE_T_MAX-1. Otherwise a sequence of length PY_SSIZE_T_MAX could get a wrong slicelength when doing L[::-1].

**Comment by serhiy-storchaka** [comment]
I'm not sure that -PY_SSIZE_T_MAX-1 always is representable. I would use PY_SSIZE_T_MIN and add a static assert (Py_BUILD_ASSERT) that PY_SSIZE_T_MIN + 1 \<= -PY_SSIZE_T_MAX. Actually currently PY_SSIZE_T_MIN is -PY_SSIZE_T_MAX-1 by definition, but this can be changed in future.

**Comment by vstinner** [comment]
Hum, integer overflows are complex issues. It deserves an unit test, maybe even in C written in \_testcapi?

**Comment by zhangyangyu** [comment]
I am okay to use PY_SSIZE_T_MIN. But if we are worried about future change of PY_SSIZE_T_MIN, seems we also need to change the API doc of PySlice_Unpack(). Although \_PyEval_SliceIndex's comment says it clips value to -PY_SSIZE_T_MAX-1, actually it uses PyNumber_AsSize_t and clips value to PY_SSIZE_T_MIN.

**Comment by zhangyangyu** [comment]
New changeset 2ddf5a19c3a06978edff2c8ba0aaf5df3528204a by Xiang Zhang in branch 'master':
bpo-30281: Fix the default value for stop in PySlice_Unpack() (bpo-1480)
https://github.com/python/cpython/commit/2ddf5a19c3a06978edff2c8ba0aaf5df3528204a

**Comment by zhangyangyu** [comment]
New changeset 98b49a00d413972965044fd355be3b8482caa07c by Xiang Zhang in branch '3.6':
bpo-30281: Fix the default value for stop in PySlice_Unpack() (bpo-1480) (bpo-1529)
https://github.com/python/cpython/commit/98b49a00d413972965044fd355be3b8482caa07c

**Comment by zhangyangyu** [comment]
New changeset 639e295650a51894412c9d976958792010d3bcf8 by Xiang Zhang in branch '3.5':
bpo-30281: Fix the default value for stop in PySlice_Unpack() (bpo-1530) (bpo-1480）
https://github.com/python/cpython/commit/639e295650a51894412c9d976958792010d3bcf8

**Comment by zhangyangyu** [comment]
New changeset 05469fa1c05acf55bdca05db21822ecdd7f6487a by Xiang Zhang in branch '2.7':
bpo-30281: Fix the default value for stop in PySlice_Unpack() (bpo-1531) (bpo-1480)
https://github.com/python/cpython/commit/05469fa1c05acf55bdca05db21822ecdd7f6487a
