### ISSUE TITLE
Rename 'name' to 'fullname' argument to ExtensionFileLoader

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#74460]
BPO | [30274](https://bugs.python.org/issue30274)
--- | :---
Nosy | @brettcannon, @sayanchowdhury, @iritkatriel, @zkneupper, @DonnaDia
PRs | <li>python/cpython#1735</li><li>python/cpython#26195</li><li>python/cpython#27981</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-04.22:24:49.383>
labels = ['easy', 'type-feature', 'library', '3.11']
title = "Rename 'name' to 'fullname' argument to ExtensionFileLoader"
updated_at = <Date 2021-08-26.19:45:24.698>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-26.19:45:24.698>
actor = 'python-dev'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-05-04.22:24:49.383>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 30274
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['293022', '293122', '294193', '339886', '393702', '400363']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'docs@python', 'python-dev', 'sayanchowdhury', 'iritkatriel', 'zkneupper', 'DonnaDia']
pr_nums = ['1735', '26195', '27981']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30274'
versions = ['Python 3.11']
```

</p></details>

**Comment by brettcannon** [comment]
https://docs.python.org/3/library/importlib.html#importlib.machinery.ExtensionFileLoader says "fullname, path" for \_\_init__(), but https://github.com/python/cpython/blob/647c3d381e67490e82cdbbe6c96e46d5e1628ce2/Lib/importlib/_bootstrap_external.py#L909 says "name, path". While I would much rather change the parameter name to match the rest of the module, I don't think I'm comfortable with the backwards-compatibility breakage over just a single parameter name (although chances are no one will notice in either direction as everyone probably passes by position).

**Comment by brettcannon** [comment]
Another option is to rename 'name' to 'fullname', make 'name' keyword-only, and then raise a DeprecationWarning if 'name' is used, eventually removing the keyword-only argument.

**Comment by f6330953-d34a-4806-aa4c-7b29197e4ed6** [comment]
I am starting to work on this issue.

**Comment by brettcannon** [comment]
This has been like this for so long I don't think it's worth the potential breakage to fix.
