### ISSUE TITLE
import hashlib makes many programs slow

### ISSUE THREAD

**Issue by 05ed1d68-9f72-4552-af38-41e9d578a41d** [python/cpython#74462]
BPO | [30276](https://bugs.python.org/issue30276)
--- | :---
Nosy | @vstinner, @tiran, @bmwiedemann

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-05-05.17:18:32.662>
created_at = <Date 2017-05-05.03:23:43.142>
labels = ['expert-SSL', '3.7', 'library']
title = 'import hashlib makes many programs slow'
updated_at = <Date 2017-05-12.16:17:46.396>
user = 'https://github.com/bmwiedemann'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-12.16:17:46.396>
actor = 'bmwiedemann'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-05-05.17:18:32.662>
closer = 'bmwiedemann'
components = ['Library (Lib)', 'SSL']
creation = <Date 2017-05-05.03:23:43.142>
creator = 'bmwiedemann'
dependencies = []
files = []
hgrepos = []
issue_num = 30276
keywords = []
message_count = 13.0
messages = ['293039', '293073', '293087', '293090', '293091', '293092', '293102', '293103', '293114', '293117', '293123', '293129', '293555']
nosy_count = 3.0
nosy_names = ['vstinner', 'christian.heimes', 'bmwiedemann']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30276'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
Steps to Reproduce:
echo import hashlib \> test.py
time python -m cProfile -s tottime test.py 2\>&1 | head

Actual Results:
shows 27ms spent in hashlib.py


The problem goes away when dropping everything after line 133
in hashlib.py

see also bpo-21288

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
traced it down a bit further.
nearly all that time is spent in
import \_hashlib
which probably means, it is spent in functions like PyInit__hashlib in [Modules/_hashopenssl.c](https://github.com/python/cpython/blob/main/Modules/_hashopenssl.c)

I can see in strace that after loading libssl, libcrypto and libz,
it calls getpid and opens /dev/urandom 8 times
and most of the time is spent in the middle of these:

grep open...dev.uran strace.out
1493970277.542629 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.542847 open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC) = 4
1493970277.543370 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.543967 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.592232 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.592518 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.597778 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4
1493970277.598629 open("/dev/urandom", O_RDONLY|O_CLOEXEC) = 4

**Comment by tiran** [comment]
I cannot reproduce the open /dev/urandom calls locally. You seem to be running an old Python version and/or old Kernel. Python prefers getrandom() over /dev/urandom. The urandom code caches the fd for /dev/urandom.

```sh
$ strace ./python -c 'import hashlib' 2>&1 | grep random
getrandom("\xe0\xa5\x00\xda\xe1\xce\x1a\x9c\xe7\x61\x71\xf2\x1d\x15\x63\x19\xdc\x60\x70\x3c\xef\xf6\xcb\xdb", 24, GRND_NONBLOCK) = 24
open("/dev/urandom", O_RDONLY|O_NOCTTY|O_NONBLOCK) = 3
```


The O_RDONLY|O_NOCTTY|O_NONBLOCK|O_CLOEXEC comes from OpenSSL.

What's your Python version, OpenSSL version, Kernel version and which platform/distribution are you on?

**Comment by vstinner** [comment]
What is your Python version? It looks like an old version.

**Comment by vstinner** [comment]
What is your OS? Which kind of computer is it? I'm surprised that you noticed open calls on /dev/urandom, it should be very quick, no?

**Comment by tiran** [comment]
I rather suspect it's OpenSSL. It takes a bit to load and initialize libcrypto.so. On my system it takes about 17ms to import \_hashlib. There is nothing we can do about it in CPython.

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
I'm running openSUSE Tumbleweed with python-2.7.13 and python3-3.6.1
on an Intel Pentium N3530 with linux-4.10.12
There the total time of the "import \_hashlib" oneliner varies between 100 and 250 ms (python3 is a bit slower and the machine is slower when running on battery)

the urandom calls themselves are not slow, but probably the processing in between. Can't that be done on demand on first use?

This is (one minor part of) slowing down python CLI tools like OpenStack's
cinder help

**Comment by vstinner** [comment]
> the urandom calls themselves are not slow, but probably the processing in between. Can't that be done on demand on first use?

If the time is spent on loading OpenSSL, maybe you should try to
import hashlib on demand?

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
This might work in some places, but if you look at real-world users like
urllib3/util/ssl_.py
> from hashlib import md5, sha1, sha256

or
twisted/words/protocols/jabber/xmlstream.py
> from hashlib import sha1

It would probably not need any openssl at all, but still gets the full penalty time from the import.
So you get all or nothing.
It would be nice to just get access to those few hashes you need for your protocal (because you certainly do not want to reimplement it).

**Comment by tiran** [comment]
If import of hashlib is slowed down by OpenSSL, then import of ssl module will be even slower.

Am 5. Mai 2017 17:57:41 MESZ schrieb "Bernhard M. Wiedemann" \<report@bugs.python.org\>:
>
>Bernhard M. Wiedemann added the comment:
>
>This might work in some places, but if you look at real-world users
>like
>urllib3/util/ssl_.py
>\> from hashlib import md5, sha1, sha256
>
>or
>twisted/words/protocols/jabber/xmlstream.py
>\> from hashlib import sha1
>
>It would probably not need any openssl at all, but still gets the full
>penalty time from the import.
>So you get all or nothing.
>It would be nice to just get access to those few hashes you need for
>your protocal (because you certainly do not want to reimplement it).
>
>\----------
>
>_______________________________________
>Python tracker \<report@bugs.python.org\>
>\<http://bugs.python.org/issue30276\>
>_______________________________________

**Comment by vstinner** [comment]
I ran a quick benchmark on my laptop, Fedora 25:

haypo@selma$ python3 -m perf command -o ref.json -- python3 -c 'pass' && python3 -m perf command -o hashlib.json -- python3 -c 'import hashlib' && python3 -m perf compare_to ref.json hashlib.json  --table

+-----------+---------+------------------------------+
| Benchmark | ref     | hashlib                      |
+===========+=========+==============================+
| command   | 26.7 ms | 30.2 ms: 1.13x slower (+13%) |
+-----------+---------+------------------------------+

Importing hashlib only takes 3.5 ms on my laptop.

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
getting to a similar size on Debian, so I'll move this into the openSUSE bugtracker to find out why it is so slow there.

**Comment by 05ed1d68-9f72-4552-af38-41e9d578a41d** [comment]
Tracking this in https://bugzilla.opensuse.org/show_bug.cgi?id=1038906
now.
It turned out to be a problem with (our?) openssl-1.0.2
which Debian stable does not have yet
and Debian/9 (stretch) has openssl-1.1.0 without this problem

The nicest python-based reproducer so far is
time python -S -c '' ; time python -S -c 'import \_hashlib'
