### ISSUE TITLE
Remove unused Python/thread_foobar.h

### ISSUE THREAD

**Issue by 703b20e5-de45-4041-8834-18834780ba2b** [python/cpython#74465]
BPO | [30279](https://bugs.python.org/issue30279)
--- | :---
Nosy | @vstinner, @ma8ma
PRs | <li>python/cpython#1473</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-05.08:09:04.270>
created_at = <Date 2017-05-05.07:39:25.283>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Remove unused Python/thread_foobar.h'
updated_at = <Date 2017-05-05.08:09:04.268>
user = 'https://github.com/ma8ma'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-05.08:09:04.268>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-05.08:09:04.270>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-05-05.07:39:25.283>
creator = 'masamoto'
dependencies = []
files = []
hgrepos = []
issue_num = 30279
keywords = []
message_count = 4.0
messages = ['293057', '293065', '293067', '293070']
nosy_count = 2.0
nosy_names = ['vstinner', 'masamoto']
pr_nums = ['1473']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30279'
versions = ['Python 3.7']
```

</p></details>

**Comment by 703b20e5-de45-4041-8834-18834780ba2b** [comment]
[Python/thread_foobar.h](https://github.com/python/cpython/blob/main/Python/thread_foobar.h) is the template code that is threading adaptation for new platforms, and it hasn't been used on actual platforms.  As a matter of fact, [Python/thread_pthread.h](https://github.com/python/cpython/blob/main/Python/thread_pthread.h) and [Python/thread_nt.h](https://github.com/python/cpython/blob/main/Python/thread_nt.h) give concrete examples of adaptation, therefore, I think thread_foobar.h hasn't needed no more.  In addition, there was an issue that only changed thread_foobar.h to fix overlooking (bpo-21312).

python-dev: https://mail.python.org/pipermail/python-dev/2017-May/147840.html

**Comment by vstinner** [comment]
Copy of my answer on the python-dev thread:

You can remove thread_foobar.h. I don't think that anyone still wants
to use this template. The other thread_*.h files can be used as
template as well.

Victor

**Comment by vstinner** [comment]
New changeset fdaeea620f8c78da89cddba4ab010c64535800e0 by Victor Stinner (Masayuki Yamamoto) in branch 'master':
bpo-30279: Remove unused [Python/thread_foobar.h](https://github.com/python/cpython/blob/main/Python/thread_foobar.h) (bpo-1473)
https://github.com/python/cpython/commit/fdaeea620f8c78da89cddba4ab010c64535800e0

**Comment by vstinner** [comment]
I hope that your merged change will now make your work simpler ;-) I don't want to backport this change, so I close the issue.
