### ISSUE TITLE
make distclean and Misc/python-config.sh

### ISSUE THREAD

**Issue by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [python/cpython#74475]
BPO | [30289](https://bugs.python.org/issue30289)
--- | :---
Nosy | @zhangyangyu
PRs | <li>python/cpython#1498</li><li>python/cpython#1506</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-09.02:57:31.614>
created_at = <Date 2017-05-06.03:41:10.270>
labels = ['build', '3.7']
title = 'make distclean and Misc/python-config.sh'
updated_at = <Date 2017-05-10.02:40:47.250>
user = 'https://bugs.python.org/dilyanpalauzov'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.02:40:47.250>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-09.02:57:31.614>
closer = 'xiang.zhang'
components = ['Build']
creation = <Date 2017-05-06.03:41:10.270>
creator = 'dilyan.palauzov'
dependencies = []
files = []
hgrepos = []
issue_num = 30289
keywords = []
message_count = 6.0
messages = ['293151', '293270', '293272', '293273', '293349', '293371']
nosy_count = 2.0
nosy_names = ['dilyan.palauzov', 'xiang.zhang']
pr_nums = ['1498', '1506']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30289'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
'make distclean' forgets to delete [Misc/python-config.sh](https://github.com/python/cpython/blob/main/Misc/python-config.sh) .

**Comment by zhangyangyu** [comment]
New changeset fa5abac1e6cd74979557d5a6f960a55f40a10b0e by Xiang Zhang in branch 'master':
bpo-30289: remove [Misc/python-config.sh](https://github.com/python/cpython/blob/main/Misc/python-config.sh) when make distclean (bpo-1498)
https://github.com/python/cpython/commit/fa5abac1e6cd74979557d5a6f960a55f40a10b0e

**Comment by zhangyangyu** [comment]
New changeset 410d75ab71e2db0fdc8b2016600a3d3d4830f38e by Xiang Zhang in branch '3.6':
bpo-30289: remove [Misc/python-config.sh](https://github.com/python/cpython/blob/main/Misc/python-config.sh) when make distclean (bpo-1498) (bpo-1506)
https://github.com/python/cpython/commit/410d75ab71e2db0fdc8b2016600a3d3d4830f38e

**Comment by zhangyangyu** [comment]
Thanks for your report!

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
3.5 is also affected.

**Comment by zhangyangyu** [comment]
I know, but this is not a bug. So I only want to backport it to 3.6.
