### ISSUE TITLE
Allow windows launcher to specify bit lengths with & without minor version

### ISSUE THREAD

**Issue by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [python/cpython#74477]
BPO | [30291](https://bugs.python.org/issue30291)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @GadgetSteve, @miss-islington
PRs | <li>python/cpython#1488</li><li>python/cpython#7849</li><li>python/cpython#12812</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-05-13.10:12:25.324>
created_at = <Date 2017-05-06.09:57:32.454>
labels = ['type-feature', '3.7', 'OS-windows']
title = 'Allow windows launcher to specify bit lengths with & without minor version'
updated_at = <Date 2019-04-12.22:32:37.328>
user = 'https://github.com/GadgetSteve'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-12.22:32:37.328>
actor = 'miss-islington'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-05-13.10:12:25.324>
closer = 'Steve Barnes'
components = ['Windows']
creation = <Date 2017-05-06.09:57:32.454>
creator = 'Steve Barnes'
dependencies = []
files = []
hgrepos = []
issue_num = 30291
keywords = []
message_count = 12.0
messages = ['293153', '293178', '293181', '293187', '293235', '293239', '293285', '293591', '293610', '297212', '340119', '340122']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Steve Barnes', 'miss-islington']
pr_nums = ['1488', '7849', '12812']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30291'
versions = ['Python 3.7']
```

</p></details>

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
Currently you can use, assuming all are installed:

py -2 # gets the latest python 2 with 64 bit as the default
py -2.7 # gets python 2.7 with 64 bit as the default
py -2.7-32 # gets -32 bit python 2.7
py -3 # gets the latest python 3 with 64 bit as the default
py -3.5 # gets python 3.5 with 64 bit as the default
py -3.5-32 # gets -32 bit python 3.5

But you cannot use:

py -2-32 # Usage Error but would be handy for the latest 32 bit python 2
py -3-32 # Usage Error but would be handy for the latest 32 bit python 3

Note that you also cannot use:
py -3.5-64  # Unknown option: -3 would be handy for testing with I need 64 bit python 3.5 with an error if it doesn't exist currently -3.5 defaults to 3.5 64 bit if available 32 bit otherwise.

For testing packages and programs it would be very useful to be able to specify any of:

 - Latest available 32 bit python 2 or 3
 - 64 bit python 3 fail if unavailable.

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
Also noted when looking at the code that the validate function, (validate_version), has a couple of issues:

 - It will allow python major versions 0-9 (at the moment only 2 or 3 are valid).
 - It will not allow minor versions with more than one digit so if/when python 3.10 comes out it will stop working, (if there is a 3.10 rather than or as well as 4.0).

I am not sure if these potential issues warrant a separate ticket.

**Comment by eryksun** [comment]
I don't see a pressing need to support a -64 architecture suffix. If you run 3.6 and get a 32-bit version, you can assume there's no 64-bit version installed and error out if you need 64-bit. That said, supporting this suffix would make the interface and error handling more consistent.

I also noticed the problem with double-digit minor versions, but that's years away. It would be an obvious problem resolved early in 3.10 development, assuming 3.10 even uses the py launcher as it exists today. I'd just kick the can on that one. Maybe add a comment noting the potential problem.

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
I believe that I have a fix in pull request bpo-1488 for the following points, and have manually tested for them:

 - py Still defaults to highest py3 with 64 bits as the default
 - py -2/3.n-32 Still works or reports not present as appropriate
 - py -2/3.n-64 Works or reports not present as appropriate
 - py -2/3 Still defaults to highest then 64 bit if present
 - py -2/3-32/64 Gives highest python 2/3 or reports not present
 - py -2/3.nn Should now work if/when there is such a version present, (any number of digits as far as the validation goes), or reports no such python.
 - py -4, etc., Ditto
 - py n.m-anything other than 32 or 64 - no change of behaviour.

CLA - Signed and submitted but not a working day yet. All automatic checks passed. Will add another push to update to the help message.

**Comment by zooba** [comment]
The actual change I want here is to support Company/Tag pairs as defined in PEP-514. There is no suffix on 64-bit CPython tags, so interpreting "-64" is going outside the PEP.

I'd also be okay with a strict mode that requires -32 for 32-bit interpreters, rather than assuming the language version is close enough. Perhaps a "-only" flag or suffix?

**Comment by zooba** [comment]
With a few more minutes thought, being able to nicely support PEP-514 here might be too much for this poor launcher to handle, so it may just be best to do that as a separate tool. (In particular, the matching rules would have to change from "enter a Python version" to "enter some convenient search pattern as a command line option", and that's a non-trivial change.)

Given that, I'm in favour of this change. When Eryk says the code is good (and the CLA notice comes through), I'll merge it.

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
CLA Now showing on profile.
Minor change to help message, (Defaults to matching 64 bit installation), pushed to hopefully auto-update the CLA flag.

**Comment by zooba** [comment]
New changeset 870f6a11dd3b2d5455f7057ce0d9c2cd31acc2f2 by Steve Dower (Steve (Gadget) Barnes) in branch 'master':
bpo-30291 Changes to launcher so as to allow py -3-32, -2.7-64, 3.10, etc.
https://github.com/python/cpython/commit/870f6a11dd3b2d5455f7057ce0d9c2cd31acc2f2

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
Closing as committed in https://github.com/python/cpython/commit/870f6a11dd3b2d5455f7057ce0d9c2cd31acc2f2

**Comment by zooba** [comment]
New changeset 5b8f972e093157cc55185841db9ad33fa332a641 by Steve Dower (Steve (Gadget) Barnes) in branch 'master':
bpo-30362 : Add list options to launcher. (bpo-1578)
https://github.com/python/cpython/commit/5b8f972e093157cc55185841db9ad33fa332a641
