### ISSUE TITLE
multiprocessing: AttributeError: 'SimpleQueue' object has no attribute '_poll'

### ISSUE THREAD

**Issue by 6a1d6514-2ce3-4648-92cf-12bbf1b4b949** [python/cpython#74487]
BPO | [30301](https://bugs.python.org/issue30301)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba, @applio, @zhangyangyu
PRs | <li>python/cpython#1601</li><li>python/cpython#1627</li><li>python/cpython#1628</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-17.14:06:16.744>
created_at = <Date 2017-05-07.19:01:50.828>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = "multiprocessing: AttributeError: 'SimpleQueue' object has no attribute '_poll'"
updated_at = <Date 2017-05-17.14:06:16.743>
user = 'https://bugs.python.org/DanielMoore'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-17.14:06:16.743>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-17.14:06:16.744>
closer = 'xiang.zhang'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-05-07.19:01:50.828>
creator = 'Daniel Moore'
dependencies = []
files = []
hgrepos = []
issue_num = 30301
keywords = []
message_count = 7.0
messages = ['293209', '293753', '293774', '293838', '293850', '293853', '293854']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'davin', 'xiang.zhang', 'Daniel Moore']
pr_nums = ['1601', '1627', '1628']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30301'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6a1d6514-2ce3-4648-92cf-12bbf1b4b949** [comment]
I originally posted this as a question on StackOverflow thinking I was doing something wrong:

http://stackoverflow.com/questions/43834494/python-3-6-attributeerror-simplequeue-object-has-no-attribute-poll/43835368#43835368

But I think I found the solution and answered my own question. I'm pretty sure you need to set:

```py
self._poll = self._reader.poll
```


in the \_\_setstate__ method in the SimpleQueue class of queues.py from the multiprocessing library. Otherwise, I'd love to know an alternative solution.

Thanks!

**Comment by zhangyangyu** [comment]
Related commit is bdb1cf1ca56db25b33fb15dd91eef2cc32cd8973. A simple reproduce snippet:

```py
import multiprocessing as mp

def foo(q):
    q.put('hello')
    assert not q.empty()

if __name__ == '__main__':
    mp.set_start_method('spawn')
    q = mp.SimpleQueue()
    p = mp.Process(target=foo, args=(q,))
    p.start()
    print(q.get())
    p.join()
```

**Comment by serhiy-storchaka** [comment]
LGTM. But can you convert the reproducer to a test?

**Comment by zhangyangyu** [comment]
Thanks for your reply Serhiy. Test added. :-)

**Comment by zhangyangyu** [comment]
New changeset 6f75bc003ab4d5294b0291289ae03f7a8d305f46 by Xiang Zhang in branch 'master':
bpo-30301: Fix AttributeError when using SimpleQueue.empty() (bpo-1601)
https://github.com/python/cpython/commit/6f75bc003ab4d5294b0291289ae03f7a8d305f46

**Comment by zhangyangyu** [comment]
New changeset 9081b36f330964faa4dee3af03228d2ca7c71835 by Xiang Zhang in branch '3.5':
bpo-30301: Fix AttributeError when using SimpleQueue.empty() (bpo-1601) (bpo-1627)
https://github.com/python/cpython/commit/9081b36f330964faa4dee3af03228d2ca7c71835

**Comment by zhangyangyu** [comment]
New changeset 43d4c0329e2348540a3a16ac61b3032f04eefd34 by Xiang Zhang in branch '3.6':
bpo-30301: Fix AttributeError when using SimpleQueue.empty() (bpo-1601) (bpo-1628)
https://github.com/python/cpython/commit/43d4c0329e2348540a3a16ac61b3032f04eefd34
