### ISSUE TITLE
IDLE: Add _utest to textview and add textview tests

### ISSUE THREAD

**Issue by 9da18a29-a07d-4828-a801-24cc911246de** [python/cpython#74489]
BPO | [30303](https://bugs.python.org/issue30303)
--- | :---
Nosy | @terryjreedy, @Mariatta, @mlouielu
PRs | <li>python/cpython#1499</li><li>python/cpython#1641</li><li>python/cpython#1866</li><li>python/cpython#1916</li><li>python/cpython#2018</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-06-23.02:14:44.969>
created_at = <Date 2017-05-08.07:58:09.865>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Add _utest to textview and add textview tests'
updated_at = <Date 2017-06-23.02:14:44.968>
user = 'https://github.com/mlouielu'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-23.02:14:44.968>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-06-23.02:14:44.969>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-05-08.07:58:09.865>
creator = 'louielu'
dependencies = []
files = []
hgrepos = []
issue_num = 30303
keywords = []
message_count = 7.0
messages = ['293228', '293895', '293897', '295233', '295234', '295241', '295271']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'Mariatta', 'louielu']
pr_nums = ['1499', '1641', '1866', '1916', '2018']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30303'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Relate to bpo-30290, add \_utest to textview to support direct unittest.

**Comment by terryjreedy** [comment]
New changeset ba365da9cee8901fad08ab0b61c7489c110e5c97 by terryjreedy (Louie Lu) in branch 'master':
bpo-30303: IDLE: Add \_utest argument to textview (bpo-1499)
https://github.com/python/cpython/commit/ba365da9cee8901fad08ab0b61c7489c110e5c97

**Comment by terryjreedy** [comment]
I am adding a couple of exception tests to complete coverage.

**Comment by Mariatta** [comment]
Louie Lu, are you louisom on GitHub?
Here in the b.p.o it shows that you have signed CLA, indicated with an asterisk next to your username.
Somehow on GitHub the bot could not verify that you've signed it.

Please clarify. Thanks.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Mariatta: yes, louisom is my GitHub account. but I migrate to mlouielu this new account. Should I add louisom to b.p.o GitHub account list?

**Comment by terryjreedy** [comment]
If the bpo profile allows more than one git account, then please add the second one.

**Comment by terryjreedy** [comment]
New changeset e1a60d903276da10d1ac098e59103f4a72bef08e by terryjreedy (Mariatta) in branch '3.6':
[3.6] bpo-30303: IDLE: Add \_utest argument to textview (GH-1499) (bpo-1916)
https://github.com/python/cpython/commit/e1a60d903276da10d1ac098e59103f4a72bef08e
