### ISSUE TITLE
Display the bytecode when compiled a regular expression in debug mode

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74485]
BPO | [30299](https://bugs.python.org/issue30299)
--- | :---
Nosy | @terryjreedy, @ezio-melotti, @serhiy-storchaka, @jcgoble3
PRs | <li>python/cpython#1491</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-14.06:54:04.286>
created_at = <Date 2017-05-07.15:27:38.755>
labels = ['expert-regex', 'type-feature', 'library', '3.7']
title = 'Display the bytecode when compiled a regular expression in debug mode'
updated_at = <Date 2017-05-14.06:54:04.285>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-14.06:54:04.285>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-14.06:54:04.286>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'Regular Expressions']
creation = <Date 2017-05-07.15:27:38.755>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30299
keywords = []
message_count = 5.0
messages = ['293198', '293211', '293214', '293224', '293636']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'jcgoble3']
pr_nums = ['1491']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30299'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch makes compiling a regular expression in debug mode (with the re.DEBUG flag) displaying the bytecode in human readable form (in addition to the syntax tree). For example:

```pycon
>>> re.compile('test_[a-z_]+', re.DEBUG)
LITERAL 116
LITERAL 101
LITERAL 115
LITERAL 116
LITERAL 95
MAX_REPEAT 1 MAXREPEAT
  IN
    RANGE (97, 122)
    LITERAL 95
```


 0. INFO 16 0b1 6 MAXREPEAT (to 17)
      prefix_skip 5
      prefix [0x74, 0x65, 0x73, 0x74, 0x5f] ('test_')
      overlap [0, 0, 0, 1, 0]
17: LITERAL 0x74 ('t')
19. LITERAL 0x65 ('e')
21. LITERAL 0x73 ('s')
23. LITERAL 0x74 ('t')
25. LITERAL 0x5f ('\_')
27. REPEAT_ONE 12 1 MAXREPEAT (to 40)
31.   IN 7 (to 39)
33.     RANGE 0x61 0x7a ('a'-'z')
36.     LITERAL 0x5f ('\_')
38.     FAILURE
39:   SUCCESS
40: SUCCESS
re.compile('test_[a-z_]+', re.DEBUG)

This feature is needed mainly for our own needs. It can help optimizing regular expression compilation.

**Comment by terryjreedy** [comment]
The new output is the blank line and numbered lines, produced by the new dis function.

The addition is specific to CPython's re module.  Thus the doc for re.DEBUG remains "Display debug information about compiled expression."  I think that the NEWS entry should also mention that this is a cpython-specific enhancement and not a language change.  See review note.

**Comment by serhiy-storchaka** [comment]
What the review note you mean Terry?

**Comment by terryjreedy** [comment]
Whoops, the one I thought I added previously.  I must not have clicked the [comment] button after writing it and before closing the tab.

**Comment by serhiy-storchaka** [comment]
New changeset 4ab6abfca4d6e444cca04821b24701cde6993f4e by Serhiy Storchaka in branch 'master':
bpo-30299: Display a bytecode when compile a regex in debug mode. (bpo-1491)
https://github.com/python/cpython/commit/4ab6abfca4d6e444cca04821b24701cde6993f4e
