### ISSUE TITLE
Small correction in set code sample

### ISSUE THREAD

**Issue by 95002720-4e56-46b3-889b-376a3f8667eb** [python/cpython#74497]
BPO | [30312](https://bugs.python.org/issue30312)
--- | :---
Nosy | @rhettinger, @terryjreedy, @Mariatta, @mcocdawc
PRs | <li>python/cpython#2081</li><li>python/cpython#2085</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-06-10.20:35:18.890>
created_at = <Date 2017-05-09.08:47:27.007>
labels = ['3.7', 'docs']
title = 'Small correction in set code sample'
updated_at = <Date 2017-06-10.20:35:18.889>
user = 'https://github.com/mcocdawc'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.20:35:18.889>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-06-10.20:35:18.890>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-05-09.08:47:27.007>
creator = 'mcocdawc'
dependencies = []
files = []
hgrepos = []
issue_num = 30312
keywords = []
message_count = 6.0
messages = ['293291', '293293', '293575', '295658', '295664', '295665']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'docs@python', 'Mariatta', 'mcocdawc']
pr_nums = ['2081', '2085']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30312'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 95002720-4e56-46b3-889b-376a3f8667eb** [comment]
There is a code example about the set type found under:
https://docs.python.org/3/tutorial/datastructures.html

It reads as:
```
>>> basket = {'apple', 'orange', 'apple', 'pear', 'orange', 'banana'}
>>> print(basket)                      # show that duplicates have been removed
{'orange', 'banana', 'pear', 'apple'}
>>> 'orange' in basket                 # fast membership testing
True
>>> 'crabgrass' in basket
False

>>> # Demonstrate set operations on unique letters from two words
...
>>> a = set('abracadabra')
>>> b = set('alacazam')
>>> a                                  # unique letters in a
{'a', 'r', 'b', 'c', 'd'}
>>> a - b                              # letters in a but not in b
{'r', 'd', 'b'}
>>> a | b                              # letters in either a or b
```

I read "either a or b" as "a .EXOR. b". Shouldn't it be:
```
>>> a | b                              # letters in a or b
```
I don't speak English as a native language, so perhaps I am wrong.

**Comment by rhettinger** [comment]
ISTM the result of the expression makes the meaning clear:

```pycon
    >>> a | b
    {'r', 'l', 'b', 'c', 'z', 'd', 'a', 'm'}
```


That said, the text might be a little clearer like this:

   \# letters in a or b or both

**Comment by terryjreedy** [comment]
English 'or' remains ambiguous, and often exclusive, even without 'either'.  Hence jokes like
  Parent: "Cake or pie?"
  Smart kid: "Both!"
I agree with replacing 'either' with 'or both'.

**Comment by Mariatta** [comment]
New changeset ca816153445cba3baec15f7e890c71abfe495340 by Mariatta (KatherineMichel) in branch 'master':
bpo-30312: Small correction in datastructures set code sample (GH-2081)
https://github.com/python/cpython/commit/ca816153445cba3baec15f7e890c71abfe495340

**Comment by Mariatta** [comment]
New changeset 865ed9ea67cf0d8a8dead91f3eac527553d92284 by Mariatta (KatherineMichel) in branch '3.6':
bpo-30312: Small correction in datastructures set code sample (GH-2081) (GH-2085)
https://github.com/python/cpython/commit/865ed9ea67cf0d8a8dead91f3eac527553d92284

**Comment by Mariatta** [comment]
Documentation has been updated, and backported to 3.6.
Thanks :)
