### ISSUE TITLE
Buildbots: 15 min is too low for test_tools on x86 Tiger 3.6 buildbot

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74499]
BPO | [30314](https://bugs.python.org/issue30314)
--- | :---
Nosy | @vstinner, @zware, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.00:51:27.698>
created_at = <Date 2017-05-09.14:56:48.286>
labels = ['3.7', 'tests']
title = 'Buildbots: 15 min is too low for test_tools on x86 Tiger 3.6 buildbot'
updated_at = <Date 2017-06-28.00:51:27.696>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-28.00:51:27.696>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.00:51:27.698>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-09.14:56:48.286>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30314
keywords = []
message_count = 5.0
messages = ['293316', '294047', '294048', '294053', '297088']
nosy_count = 3.0
nosy_names = ['vstinner', 'zach.ware', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30314'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
We should give more than 15 min to the "x86 Tiger 3.6" buildbot, since test_tools was killed by the timeout. On the previous build, test_tools took min 25 sec.

The global 15 min timeout was designed to detect deadlocks issues, but here it's just that the buildbot is sometimes too slow.

Maybe we should increase the timeout to 30 min on all buildbots, but also increase the timeout of the "tests" step to long than 1 hour? Otherwise, the test can be killed by buildbot without logging the Python traceback.

Maybe we can configured buildbot to first send a signal (SIGUSR1? SIGINT?) before killing the process to dump a traceback, but that's something different.

\---
0:15:54 [ 52/405] test_tools crashed -- running: test_zipfile (178 sec)
Timeout (0:15:00)!
Thread 0xa000d000 (most recent call first):
  File "/Users/db3l/buildarea/3.6.bolen-tiger/build/Lib/ast.py", line 101 in \<genexpr\>
  ...
  File "/Users/db3l/buildarea/3.6.bolen-tiger/build/Lib/test/test_tools/test_unparse.py", line 124 in assertASTEqual
  ...
\---
http://buildbot.python.org/all/builders/x86%20Tiger%203.6/builds/349/steps/test/logs/stdio

See also bpo-30172: "test_tools takes longer than 5 minutes on some buildbots".

**Comment by vstinner** [comment]
PR: https://github.com/python/buildmaster-config/pull/8

**Comment by serhiy-storchaka** [comment]
test_tools is so slow because it proceeds \*all* Python files. This controlled by the "cpu" resource (only 10 random files are chosen if it is disabled).

Maybe disable the "cpu" resource on slow buildbots?

**Comment by vstinner** [comment]
I merged my PR and applied the new buildbot configuration. I will try to check if the config was applied correctly.

Serhiy: "test_tools is so slow because it proceeds \*all* Python files. This controlled by the "cpu" resource (only 10 random files are chosen if it is disabled)."

I created the bpo-30417 to track this idea.

**Comment by vstinner** [comment]
The timeout of buildbot has been adjusted (my PR https://github.com/python/buildmaster-config/pull/8 has been merged).

The cpu resource has been disabled on Travis CI to make it faster.

This issue can now been fixed.
