### ISSUE TITLE
Add code coverage for argument in random.shuffle

### ISSUE THREAD

**Issue by csabella** [python/cpython#74494]
BPO | [30308](https://bugs.python.org/issue30308)
--- | :---
Nosy | @rhettinger, @mdickinson, @vstinner, @csabella
PRs | <li>python/cpython#1504</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-05-11.15:20:37.884>
created_at = <Date 2017-05-08.21:20:00.280>
labels = ['3.7', 'type-feature', 'tests']
title = 'Add code coverage for argument in random.shuffle'
updated_at = <Date 2017-05-11.15:20:37.883>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-11.15:20:37.883>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-05-11.15:20:37.884>
closer = 'rhettinger'
components = ['Tests']
creation = <Date 2017-05-08.21:20:00.280>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30308
keywords = []
message_count = 9.0
messages = ['293253', '293254', '293259', '293286', '293288', '293359', '293360', '293498', '293499']
nosy_count = 4.0
nosy_names = ['rhettinger', 'mark.dickinson', 'vstinner', 'cheryl.sabella']
pr_nums = ['1504']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30308'
versions = ['Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Added test cases for `random` argument in random.shuffle for code coverage.

Two interesting results (documented within test cases):
1.  In the docs, `random` is defined as a function returning a float in the range [0, 1), but negative floats could be returned and shuffle worked using slice notation.
2.  A dictionary with sequential numeric keys could be shuffled.

**Comment by csabella** [comment]
Add Mark Dickinson and Raymond Hettinger to nosy list per Brett's suggestion on core-mentorship.

**Comment by rhettinger** [comment]
* Why not use unittest.mock to test the \*random* argument for shuffle?

* Try to avoid direct calls to \_randbelow().  That method is a non-public implementation detail subject to change.

* Also please don't make test_random.py depend on secrets which itself depends on random.py.

**Comment by mdickinson** [comment]
I see you've added a test for the behaviour of:

```py
    shuffle(seq, random=lambda: -1.0)
```


I'd suggest leaving that test out: that this works right now is really just an accident of the (CPython) implementation, and it may well not work on other Python implementations. Adding a test in effect says that there was a deliberate decision to support this (which as far as I know there isn't, and shouldn't be).

**Comment by mdickinson** [comment]
I'm also a bit uncomfortable with adding tests for other specific exceptions when a misbehaving `random` is passed: again, the details of whether an exception is raised or not for "self.assertRaises(IndexError, shuffle, seq, random=lambda: -1.1)", and which precise class of exception is raised, seem like something that could be left as implementation-defined. I'm not sure I see much value in pinning down the precise behaviour in this case (which is effectively what a testcase does).

**Comment by csabella** [comment]
OK, I've removed the test for the negative values returned by random.  In core-mentorship, David Murray had suggested adding a comment to document it as unexpected behavior.  I had asked there because I wasn't quite sure what to do about it.

Should I also leave out the test for being able to shuffle a dict with numeric keys?

Thanks.

**Comment by csabella** [comment]
I've also changed the test to use Mock for the random function.  I'm new to mock, so I'm not sure if I did it right.  Using a return_value seemed to be the best way to go.  I didn't know if it was necessary to test if an incorrect function was sent in.

**Comment by rhettinger** [comment]
New changeset f111fd2e65ef7aefd4ebeadbb48e84d609bf3733 by Raymond Hettinger (csabella) in branch 'master':
bpo-30308: Code coverage for argument in random.shuffle (bpo-1504)
https://github.com/python/cpython/commit/f111fd2e65ef7aefd4ebeadbb48e84d609bf3733

**Comment by rhettinger** [comment]
Thank you for the patch.
