### ISSUE TITLE
random.shuffle pointlessly shuffles dicts

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#74496]
BPO | [30311](https://bugs.python.org/issue30311)
--- | :---
Nosy | @tim-one, @rhettinger, @stevendaprano, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-09.06:36:46.496>
created_at = <Date 2017-05-09.01:34:22.402>
labels = ['invalid', 'type-bug', '3.7']
title = 'random.shuffle pointlessly shuffles dicts'
updated_at = <Date 2017-05-09.06:36:46.494>
user = 'https://github.com/stevendaprano'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-09.06:36:46.494>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-09.06:36:46.496>
closer = 'rhettinger'
components = []
creation = <Date 2017-05-09.01:34:22.402>
creator = 'steven.daprano'
dependencies = []
files = []
hgrepos = []
issue_num = 30311
keywords = []
message_count = 4.0
messages = ['293265', '293266', '293269', '293283']
nosy_count = 4.0
nosy_names = ['tim.peters', 'rhettinger', 'steven.daprano', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30311'
versions = ['Python 3.7']
```

</p></details>

**Comment by stevendaprano** [comment]
According to the documentation, random.shuffle() should accept a sequence. But it also accepts dicts, in which case it does nothing, expensively:

py\> x = dict.fromkeys(range(10\*\*6))
py\> random.shuffle(x)
py\> str(x)[:55] + "...}"
'{0: None, 1: None, 2: None, 3: None, 4: None, 5: None, ...}'


I'm not sure if it is better to explicitly test for and reject dicts and mappings, or just document that sorting dicts will apparently succeed while doing nothing.

Do we want to support sorting OrderedDicts? That at least makes sense, since they have an order, but again shuffle() seemingly works but actually does nothing.

I lean towards explicitly testing for dicts and raising.

**Comment by vadmium** [comment]
It is also pointless to shuffle a list object repeating the same item, but that is no reason to add a special case. Is there a real problem with allowing dictionaries and OrderedDict? It seems to behave sensibly if you give each item a unique value:

```pycon
>>> D = {i: i * 100 for i in range(5)}
>>> D
{0: 0, 1: 100, 2: 200, 3: 300, 4: 400}
>>> shuffle(D)
>>> D
{0: 300, 1: 100, 2: 200, 3: 0, 4: 400}
```

**Comment by tim-one** [comment]
Generally speaking, trying to shuffle a dict D already blows up, unless D's keys are the integers range(len(D)).  In that case, D is indistinguishable from a list in the sense that both map range(N) to values via __getitem__.  `shuffle()` does no type checks whatsoever now, and will shuffle any object that maps range(N) to values.

Fine by me the way it is.

**Comment by rhettinger** [comment]
I concur with Tim.  These are just duck-typing facts of life.
