### ISSUE TITLE
TestCase.assertMultiLineEqual only registered for Unicode strings in 2.7

### ISSUE THREAD

**Issue by vadmium** [python/cpython#74490]
BPO | [30304](https://bugs.python.org/issue30304)
--- | :---
Nosy | @ezio-melotti, @vadmium, @serhiy-storchaka, @Mariatta, @adityahase
PRs | <li>python/cpython#2846</li><li>python/cpython#2847</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-25.21:33:05.285>
created_at = <Date 2017-05-08.08:50:09.734>
labels = ['easy', 'type-bug', 'tests', 'docs']
title = 'TestCase.assertMultiLineEqual only registered for Unicode strings in 2.7'
updated_at = <Date 2017-07-25.21:33:05.283>
user = 'https://github.com/vadmium'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-25.21:33:05.283>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-25.21:33:05.285>
closer = 'Mariatta'
components = ['Documentation', 'Tests']
creation = <Date 2017-05-08.08:50:09.734>
creator = 'martin.panter'
dependencies = []
files = []
hgrepos = []
issue_num = 30304
keywords = ['easy']
message_count = 9.0
messages = ['293229', '294387', '294576', '298991', '298993', '298995', '298998', '299137', '299146']
nosy_count = 7.0
nosy_names = ['ezio.melotti', 'docs@python', 'martin.panter', 'serhiy.storchaka', 'Mariatta', 'Sourav Singh', 'adityahase']
pr_nums = ['2846', '2847']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30304'
versions = ['Python 2.7']
```

</p></details>

**Comment by vadmium** [comment]
In Mercurial revision 6e5b5d1b6714, the documentation for “assertMultiLineEqual” was changed from

This method is used by default when comparing Unicode strings with “assertEqual”.

to

This method is used by default when comparing strings with “assertEqual”. 

The new text is misleading because “str” objects are also strings, but the default does not apply to “str” objects.

**Comment by 5761bba3-ba61-4f41-90eb-2f7a7e49dac3** [comment]
@Martin I would like to take a stab at the issue. How do I start?

**Comment by vadmium** [comment]
I think the simplest way forward would be to add the word “Unicode” back in. You could look at making a Git Hub pull request for this if you want. Hopefully somebody else can merge it though, because I probably won’t be in a position to do so for a while.

**Comment by a42c1b8f-da40-49e1-abe9-42ea9ef001ba** [comment]
Hi, I'm new to python development community.
I've created a GitHub PR that fixes this issue.

**Comment by serhiy-storchaka** [comment]
This is related only to 2.7. All correct in 3.x.

**Comment by Mariatta** [comment]
Thanks Serhiy.

Aditya, your PR was made against the master branch. Can you make the change against the 2.7 branch?

Thanks.

**Comment by a42c1b8f-da40-49e1-abe9-42ea9ef001ba** [comment]
I've fixed that.

**Comment by Mariatta** [comment]
New changeset 0666d0e50432e3b0109db96b8e48fb6c496bd49c by Mariatta (Aditya Hase) in branch '2.7':
bpo-30304: Improve TestCase.assertMultiLineEqual docs (GH-2847)
https://github.com/python/cpython/commit/0666d0e50432e3b0109db96b8e48fb6c496bd49c

**Comment by Mariatta** [comment]
Thanks!
