### ISSUE TITLE
Error using newline='' when writing to CSV file

### ISSUE THREAD

**Issue by 57edb024-6dac-4ae7-89d7-8fbb185c5ed5** [python/cpython#74509]
BPO | [30324](https://bugs.python.org/issue30324)
--- | :---
Nosy | @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-09.22:41:48.079>
created_at = <Date 2017-05-09.22:31:41.199>
labels = ['invalid']
title = "Error using newline='' when writing to CSV file"
updated_at = <Date 2017-05-10.02:16:15.538>
user = 'https://bugs.python.org/BeamPower'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.02:16:15.538>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-09.22:41:48.079>
closer = 'martin.panter'
components = []
creation = <Date 2017-05-09.22:31:41.199>
creator = 'BeamPower'
dependencies = []
files = []
hgrepos = []
issue_num = 30324
keywords = []
message_count = 5.0
messages = ['293356', '293357', '293358', '293368', '293370']
nosy_count = 2.0
nosy_names = ['martin.panter', 'BeamPower']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30324'
versions = ['Python 2.7']
```

</p></details>

**Comment by 57edb024-6dac-4ae7-89d7-8fbb185c5ed5** [comment]
I am using the newline='' feature in my program to avoid the extra lines being placed between each line being written to a CSV file.
This error is odd though... I used it before on a previous rev, and it worked fine.
I think the CSV file writing feature has been available since Python 2.3?

Here's the error I am getting:

```pytb
Traceback (most recent call last):
  File "C:\Python\parser\parser.py", line 91, in <module>
    write_header_to_csv()
  File "C:\Python\parser\parser.py", line 44, in write_header_to_csv
    csvfile = open('decodedfile.csv', 'w', newline='')
TypeError: 'newline' is an invalid keyword argument for this function
```


At the top of my program, I have the following imports:
import sys
import binascii
import csv

**Comment by 57edb024-6dac-4ae7-89d7-8fbb185c5ed5** [comment]
Sorry, I left out a detail... I am running Python 2.7.13

**Comment by vadmium** [comment]
In Python 2, the "open" function doesn't have a "newline" parameter. Perhaps you were looking at the wrong documentation version.

**Comment by 57edb024-6dac-4ae7-89d7-8fbb185c5ed5** [comment]
Sorry, my mistake. I thought I was running Python 2.7, but I was running Python 3.1.

By the way, is there a solution to the extra lines being written to a CSV file using Python 2.7?

Thank you.

**Comment by vadmium** [comment]
On Python 2, I'm guessing you are getting extra CRs on Windows? It looks like you have to open in binary mode there to avoid newline translation. This is documented for the "reader" and "writer" functions.
