### ISSUE TITLE
concurrent.futures.Executor.map() consumes all memory when big generators are used

### ISSUE THREAD

**Issue by 4f9978cc-721c-408e-9016-a0d789568628** [python/cpython#74508]
BPO | [30323](https://bugs.python.org/issue30323)
--- | :---
Nosy | @MojoVampire, @zhangyangyu
Superseder | <li>bpo-29842: Make Executor.map work with infinite/large inputs correctly</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-16.09:32:15.125>
created_at = <Date 2017-05-09.21:37:02.176>
labels = ['3.7', 'library', 'performance']
title = 'concurrent.futures.Executor.map() consumes all memory when big generators are used'
updated_at = <Date 2017-05-16.09:38:40.987>
user = 'https://bugs.python.org/Klamann'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-16.09:38:40.987>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-16.09:32:15.125>
closer = 'Klamann'
components = ['Library (Lib)']
creation = <Date 2017-05-09.21:37:02.176>
creator = 'Klamann'
dependencies = []
files = []
hgrepos = []
issue_num = 30323
keywords = []
message_count = 5.0
messages = ['293353', '293420', '293539', '293627', '293755']
nosy_count = 3.0
nosy_names = ['josh.r', 'xiang.zhang', 'Klamann']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29842'
type = 'resource usage'
url = 'https://bugs.python.org/issue30323'
versions = ['Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4f9978cc-721c-408e-9016-a0d789568628** [comment]
The Executor's map() function accepts a function and an iterable that holds the function arguments for each call to the function that should be made. This iterable could be a generator, and as such it could reference data that won't fit into memory.

The behaviour I would expect is that the Executor requests the next element from the iterable whenever a thread, process or whatever is ready to make the next function call.

But what actually happens is that the entire iterable gets converted into a list right after the map function is called and therefore any underlying generator will load all referenced data into memory. Here's where the list gets built from the iterable:
https://github.com/python/cpython/blob/3.6/Lib/concurrent/futures/_base.py#L548

The way I see it, there's no reason to convert the iterable to a list in the map function (or any other place in the Executor). Just replacing the list comprehension with a generator expression would probably fix that.


Here's an example that illustrates the issue:

```py
    from concurrent.futures import ThreadPoolExecutor
    import time
    
    def generate():
        for i in range(10):
            print("generating input", i)
            yield i
    
    def work(i):
        print("working on input", i)
        time.sleep(1)
    
    with ThreadPoolExecutor(max_workers=2) as executor:
        generator = generate()
        executor.map(work, generator)
```


The output is:

    generating input 0
    working on input 0
    generating input 1
    working on input 1
    generating input 2
    generating input 3
    generating input 4
    generating input 5
    generating input 6
    generating input 7
    generating input 8
    generating input 9
    working on input 2
    working on input 3
    working on input 4
    working on input 5
    working on input 6
    working on input 7
    working on input 8
    working on input 9

Ideally, the lines should alternate, but currently all input is generated immediately.

**Comment by zhangyangyu** [comment]
IIUC, the meaning of executor.map() is to run the tasks concurrently. So you have to loop the iterable ahead to submit all the tasks. If you make it a generator comprehension, you are actually submitting a task and then getting the result. So you are executing the tasks sequentially. Doesn't it violate the intention and meaning of executor.map()?

**Comment by 4f9978cc-721c-408e-9016-a0d789568628** [comment]
Yes, I was wrong in my assumption that simply replacing the list comprehension with a generator expression would fix the issue.

Nevertheless, there is no need to load the \*entire* generator into memory by converting it to a list. All we have to read are the first n elements, where n is the number of workers that are currently available.

I've implemented an alternative solution that works for me, using wait() and notify() from threading.Condition, but I'm not quite sure if this would be the best solution for everyone. But I could post it here, if you're intrested.

We should also consider that not strictly evaluating every iterable that is passed to the map() function might break existing code that implicitly relies on that fact that this is happening (although this is not a documented feature of the map function and was probably not the intended behaviour in the first place).

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
This is a strict duplicate of bpo-29842, for which I've had a PR outstanding for a couple months now.

**Comment by 4f9978cc-721c-408e-9016-a0d789568628** [comment]
Thanks for pointing this out.
\*closed\*
