### ISSUE TITLE
test_distutils is too verbose on Windows

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74503]
BPO | [30318](https://bugs.python.org/issue30318)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @merwok, @zware, @zooba, @dstufft

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:10:44.502>
created_at = <Date 2017-05-09.15:54:26.200>
labels = ['tests', '3.7', 'library', 'OS-windows']
title = 'test_distutils is too verbose on Windows'
updated_at = <Date 2018-09-19.23:10:44.501>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:10:44.501>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:10:44.502>
closer = 'vstinner'
components = ['Distutils', 'Tests', 'Windows']
creation = <Date 2017-05-09.15:54:26.200>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30318
keywords = []
message_count = 3.0
messages = ['293330', '293885', '293886']
nosy_count = 8.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'eric.araujo', 'zach.ware', 'steve.dower', 'dstufft']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30318'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
test_distutils should only dump stdout/stderr on compilation failure, but hide them on success (by default).

Example of output:

http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/588/steps/test/logs/stdio

0:58:52 [277/405/1] test_distutils passed (124 sec) -- running: test_tokenize (322 sec)
xxmodule.c
   Creating library d:\\temp\\tmp1byjf67b\\Debug\\temp\\tmp1byjf67b\\xx_d.cp37-win32.lib and object d:\\temp\\tmp1byjf67b\\Debug\\temp\\tmp1byjf67b\\xx_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
foo.c
   Creating library d:\\temp\\tmp78_8qa47\\tempt\\temp\\tmpduqip5h3\\foo_d.cp37-win32.lib and object d:\\temp\\tmp78_8qa47\\tempt\\temp\\tmpduqip5h3\\foo_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
foo.c
   Creating library d:\\temp\\tmp78_8qa47\\tempt\\temp\\tmpduqip5h3\\foo_d.cp37-win32.lib and object d:\\temp\\tmp78_8qa47\\tempt\\temp\\tmpduqip5h3\\foo_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
xxmodule.c
   Creating library d:\\temp\\tmpruuda1qt\\Debug\\temp\\tmpruuda1qt\\xx_d.cp37-win32.lib and object d:\\temp\\tmpruuda1qt\\Debug\\temp\\tmpruuda1qt\\xx_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
foo.c
   Creating library d:\\temp\\tmpxzrh56h5\\tempt\\temp\\tmpht642isv\\foo_d.cp37-win32.lib and object d:\\temp\\tmpxzrh56h5\\tempt\\temp\\tmpht642isv\\foo_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
foo.c
   Creating library d:\\temp\\tmpxzrh56h5\\tempt\\temp\\tmpht642isv\\foo_d.cp37-win32.lib and object d:\\temp\\tmpxzrh56h5\\tempt\\temp\\tmpht642isv\\foo_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance
xxmodule.c
   Creating library build\\temp.win32-3.7-pydebug\\Debug\\xx_d.cp37-win32.lib and object build\\temp.win32-3.7-pydebug\\Debug\\xx_d.cp37-win32.exp
LINK : /LTCG specified but no code generation required; remove /LTCG from the link command line to improve linker performance

D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\build\\test_python_204\>exit 1 

D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\build\\test_python_204\>exit 0

**Comment by zooba** [comment]
The problem here I think is that distutils itself should only dump stdout/stderr on failure, but because of how it spawns processes it never actually captures the output from external tools.

We really need to update distutils's spawn() function to use subprocess. That would also resolve a handful of other issues.

**Comment by vstinner** [comment]
> The problem here I think is that distutils itself should only dump stdout/stderr on failure, ...

Hum, I would like to see warnings even if the compilation succeed. So I would prefer to only modify test_distutils.
