### ISSUE TITLE
PyObject_GetIter does not behave as documented on dict objects

### ISSUE THREAD

**Issue by d9fbe775-5897-4ca4-b73e-b5b147c3f567** [python/cpython#74507]
BPO | [30322](https://bugs.python.org/issue30322)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-10.21:56:50.697>
created_at = <Date 2017-05-09.20:19:39.454>
labels = ['docs']
title = 'PyObject_GetIter does not behave as documented on dict objects'
updated_at = <Date 2017-05-10.21:56:50.695>
user = 'https://bugs.python.org/SamDeMeyer'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-10.21:56:50.695>
actor = 'Sam De Meyer'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-10.21:56:50.697>
closer = 'Sam De Meyer'
components = ['Documentation']
creation = <Date 2017-05-09.20:19:39.454>
creator = 'Sam De Meyer'
dependencies = []
files = []
hgrepos = []
issue_num = 30322
keywords = []
message_count = 4.0
messages = ['293346', '293347', '293352', '293456']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'serhiy.storchaka', 'Sam De Meyer']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30322'
versions = ['Python 3.6']
```

</p></details>

**Comment by d9fbe775-5897-4ca4-b73e-b5b147c3f567** [comment]
According to the docs (https://docs.python.org/3/c-api/object.html) the `PyObject_GetIter` method should be equivalent to the python call `iter(<some_dict>)`, but, when given a dict, the `PyObject_GetIter` returns an iterator over key-value pairs whereas the `iter()` method returns an iterator over keys only.

I tripped over this when giving the `<some_dict>.update()` a dict-like object that does not inherit from the builtin dict and implements its own `__iter__()`.

The `update()` method eventually reaches the following piece of code:
https://hg.python.org/cpython/file/4243df51fe43/Objects/dictobject.c#l2383

>    it = PyObject_GetIter(seq2);
> ...
>        item = PyIter_Next(it);
> ...
>        fast = PySequence_Fast(item, "");
> ...
>        key = PySequence_Fast_GET_ITEM(fast, 0);
>        value = PySequence_Fast_GET_ITEM(fast, 1);

displaying the difference in behaviour between `PyObject_GetIter` and `iter(o)`.

**Comment by serhiy-storchaka** [comment]
I can't believe in this since one-argument iter() just calls PyObject_GetIter().

dict.update() accepts either a dict-like object (which should have the keys() method) or an iterable producing key-value pairs. If your dict-like object doesn't work as expected, check that it has the keys() method.

**Comment by rhettinger** [comment]
This from the help on dict.update():

 |  update(...)
 |      D.update([E, ]**F) -\> None.  Update D from dict/iterable E and F.
 |      If E present and has a .keys() method, does:     for k in E: D[k] = E[k]
 |      If E present and lacks .keys() method, does:     for (k, v) in E: D[k] = v
 |      In either case, this is followed by: for k in F: D[k] = F[k]

Likewise in the source for collections.abc.MutableMapping:

```py
    def update(*args, **kwds):
        ''' D.update([E, ]**F) -> None.  Update D from mapping/iterable E and F.
            If E present and has a .keys() method, does:     for k in E: D[k] = E[k]
            If E present and lacks .keys() method, does:     for (k, v) in E: D[k] = v
            In either case, this is followed by: for k, v in F.items(): D[k] = v
        '''
        if not args:
            raise TypeError("descriptor 'update' of 'MutableMapping' object "
                            "needs an argument")
        self, *args = args
        if len(args) > 1:
            raise TypeError('update expected at most 1 arguments, got %d' %
                            len(args))
        if args:
            other = args[0]
            if isinstance(other, Mapping):
                for key in other:
                    self[key] = other[key]
            elif hasattr(other, "keys"):
                for key in other.keys():
                    self[key] = other[key]
            else:
                for key, value in other:
                    self[key] = value
        for key, value in kwds.items():
            self[key] = value
```

**Comment by d9fbe775-5897-4ca4-b73e-b5b147c3f567** [comment]
You seem to be right, my object was lacking the keys method.

Please excuse me for the false alarm, and thanks for pointing it out.
