### ISSUE TITLE
Version may be out of date in travis.yml

### ISSUE THREAD

**Issue by 3e343a24-9ff1-42e1-854f-3942dc156566** [python/cpython#74512]
BPO | [30327](https://bugs.python.org/issue30327)
--- | :---
Nosy | @brettcannon, @vstinner, @monkeyboy2805
PRs | <li>python/cpython#1526</li><li>python/cpython#1550</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-11.17:32:54.846>
created_at = <Date 2017-05-10.06:14:35.342>
labels = ['3.7', 'invalid', 'type-bug', 'tests', 'build']
title = 'Version may be out of date in travis.yml'
updated_at = <Date 2017-05-11.17:32:54.845>
user = 'https://github.com/Monkeyboy2805'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-11.17:32:54.845>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-11.17:32:54.846>
closer = 'brett.cannon'
components = ['Build', 'Tests']
creation = <Date 2017-05-10.06:14:35.342>
creator = 'Jensen Taylor'
dependencies = []
files = []
hgrepos = []
issue_num = 30327
keywords = []
message_count = 4.0
messages = ['293381', '293384', '293462', '293510']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'vstinner', 'Jensen Taylor']
pr_nums = ['1526', '1550']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30327'
versions = ['Python 3.7']
```

</p></details>

**Comment by 3e343a24-9ff1-42e1-854f-3942dc156566** [comment]
It's only 3.6. I may be talking nonsense but it didn't quite look right

**Comment by vstinner** [comment]
Python 3.6 is the latest stable release of Python. It's perfectly fine to \*build the documentation* using that version.

I don't think that the Travis "docs job" must test that Sphinx works on the nightly version: this work should be done by Sphinx, not by the Python documentation team.

**Comment by vstinner** [comment]
@brett: What do you think?

**Comment by brettcannon** [comment]
I agree with Victor since that's why I set up the Travis file that way. :)

Thanks to this issue, though, I have added a comment to .travis.yml to explain why the version is what it is.
