### ISSUE TITLE
Document deprecated alias of assertNotRegex

### ISSUE THREAD

**Issue by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [python/cpython#74520]
BPO | [30335](https://bugs.python.org/issue30335)
--- | :---
Nosy | @marco-buttu, @DimitrisJim, @Mariatta
PRs | <li>python/cpython#1536</li><li>python/cpython#2055</li><li>python/cpython#2056</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-06-10.01:35:07.355>
created_at = <Date 2017-05-10.15:53:20.883>
labels = ['3.7', 'docs']
title = 'Document deprecated alias of assertNotRegex'
updated_at = <Date 2017-06-10.01:35:07.353>
user = 'https://github.com/DimitrisJim'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.01:35:07.353>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-06-10.01:35:07.355>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-05-10.15:53:20.883>
creator = 'Jim Fasarakis-Hilliard'
dependencies = []
files = []
hgrepos = []
issue_num = 30335
keywords = []
message_count = 6.0
messages = ['293430', '293446', '295565', '295595', '295596', '295597']
nosy_count = 4.0
nosy_names = ['docs@python', 'marco.buttu', 'Jim Fasarakis-Hilliard', 'Mariatta']
pr_nums = ['1536', '2055', '2056']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30335'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b78688f9-6435-4192-9fe9-2f86f7e61fcf** [comment]
The assertNotRegexpMatches name was deprecated in 3.2 in favor of assertNotRegex [1]. This is currently not documented in unittest.rst.

[1]: https://github.com/python/cpython/commit/ed3a7d2d601ce1e65b0bacf24676440631158ec8

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
Hi Jim, I think assertNotRegexpMatches has never been introduced:

https://docs.python.org/3/whatsnew/3.1.html
https://docs.python.org/3/whatsnew/3.2.html

That is why there is no reference in the documentation about that.  I also executed a test with Python 3.1 and 3.2. and I found that there is no assertNotRegexpMatches assertion available.

**Comment by Mariatta** [comment]
New changeset 74921ed8941fce14c2a53dc7280f43eb01fe4ed8 by Mariatta (Jim Fasarakis-Hilliard) in branch 'master':
bpo-30335: Add deprecation alias entry for assertNotRegexpMatches (GH-1536)
https://github.com/python/cpython/commit/74921ed8941fce14c2a53dc7280f43eb01fe4ed8

**Comment by Mariatta** [comment]
New changeset 10c9a09ef4810f0235f5f585dcce70eca049604a by Mariatta in branch '3.6':
[3.6] bpo-30335: Add deprecation alias entry for assertNotRegexpMatches (GH-1536) (GH-2055)
https://github.com/python/cpython/commit/10c9a09ef4810f0235f5f585dcce70eca049604a

**Comment by Mariatta** [comment]
New changeset cabdba24b5cee036bd4963d2dcf5bf667e6d63c9 by Mariatta in branch '3.5':
[3.5] bpo-30335: Add deprecation alias entry for assertNotRegexpMatches (GH-1536) (GH-2056)
https://github.com/python/cpython/commit/cabdba24b5cee036bd4963d2dcf5bf667e6d63c9

**Comment by Mariatta** [comment]
Thanks!
