### ISSUE TITLE
Optimize out non-capturing groups

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74525]
BPO | [30340](https://bugs.python.org/issue30340)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @MojoVampire
PRs | <li>python/cpython#1542</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-05-14.06:54:30.184>
created_at = <Date 2017-05-11.09:20:53.903>
labels = ['expert-regex', '3.7', 'library', 'performance']
title = 'Optimize out non-capturing groups'
updated_at = <Date 2017-05-14.06:54:30.183>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-14.06:54:30.183>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-05-14.06:54:30.184>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'Regular Expressions']
creation = <Date 2017-05-11.09:20:53.903>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30340
keywords = []
message_count = 5.0
messages = ['293477', '293481', '293501', '293504', '293635']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'josh.r']
pr_nums = ['1542']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30340'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch makes the regular expression parser produce more optimal tree, mainly due to getting rid of non-capturing groups. This allows to apply an optimization that was forbidden before and makes the regular expression compiler producing more efficient code.

For example following expressions are transformed in more optimal form:

'(?:x|y)+' -\> '[xy]+'
'(?:ab)|(?:ac)' -\> 'a[bc]'
r'[a-z]|\\d' -\> r'[a-z\\d]'

This can speed up matching by 10-25 times.

```sh
$ ./python -m timeit -s "import re; p = re.compile(r'(?:x|y)+'); s = 'x'*10000"  "p.match(s)"
Unpatched:  500 loops, best of 5: 865 usec per loop
Patched:    5000 loops, best of 5: 84.5 usec per loop

$ ./python -m timeit -s "import re; p = re.compile(r'(?:[a-z]|\d)+'); s = 'x'*10000"  "p.match(s)"
Unpatched:  100 loops, best of 5: 2.19 msec per loop
Patched:    5000 loops, best of 5: 84.5 usec per loop
```

**Comment by serhiy-storchaka** [comment]
```sh
$ ./python -m timeit -s "import re; p = re.compile(r'[a-z]|[0-9]'); s = ' '*10000+'x'"  "p.search(s)"
Unpatched:  500 loops, best of 5: 732 usec per loop
Patched:    1000 loops, best of 5: 279 usec per loop
```

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
The PR includes defining and using a \_uniq function that is actually a no-op function (it doesn't uniquify, the first line returns the argument, so the rest is skipped). Was that supposed to be removed, or should it actually uniqify?

**Comment by serhiy-storchaka** [comment]
Good catch Josh! This return was temporary added for debugging, the function should actually uniqify.

**Comment by serhiy-storchaka** [comment]
New changeset 821a9d146bc04a1bc1a9807962990a1f59d692b8 by Serhiy Storchaka in branch 'master':
bpo-30340: Enhanced regular expressions optimization. (bpo-1542)
https://github.com/python/cpython/commit/821a9d146bc04a1bc1a9807962990a1f59d692b8
