### ISSUE TITLE
LC_ALL=en_US + io.open() => LookupError: (osx)

### ISSUE THREAD

**Issue by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [python/cpython#74523]
BPO | [30338](https://bugs.python.org/issue30338)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @asottile

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-12.10:12:16.597>
created_at = <Date 2017-05-10.22:22:18.657>
labels = ['OS-mac', 'library', 'type-crash']
title = 'LC_ALL=en_US + io.open() => LookupError: (osx)'
updated_at = <Date 2017-05-12.10:13:47.736>
user = 'https://github.com/asottile'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-12.10:13:47.736>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-12.10:12:16.597>
closer = 'vstinner'
components = ['Library (Lib)', 'macOS']
creation = <Date 2017-05-10.22:22:18.657>
creator = 'Anthony Sottile'
dependencies = []
files = []
hgrepos = []
issue_num = 30338
keywords = []
message_count = 7.0
messages = ['293457', '293460', '293509', '293534', '293538', '293540', '293541']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'Anthony Sottile']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30338'
versions = ['Python 2.7']
```

</p></details>

**Comment by 341ce0e2-bdbb-4bd4-99e6-746f11201a3f** [comment]
Originally seen here: https://github.com/Microsoft/vscode/issues/26227

```
$ LC_ALL=en_US python -c 'import io; io.open("/dev/null")'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
LookupError: unknown encoding: 
```

Admittedly, that `LC_ALL` looks malformed (should be en_US.UTF-8), but given this works on linux:

```
$ env -i LC_ALL=en_US python -c 'import io; io.open("/dev/null")'
$
```

It may be an OSX specific bug?

I've only tagged py27 + py36 because I did not have a build toolchain available to try on master, though I imagine it is reproducible there as well.

**Comment by vstinner** [comment]
> It may be an OSX specific bug?

Yes, on Linux, it "just works":

haypo@selma$ LC_ALL=en_US python2 -c 'import io; io.open("/dev/null")'
haypo@selma$ LC_ALL=en_USxxx python2 -c 'import io; io.open("/dev/null")'

In fact, you get ASCII encoding for these two locales:

haypo@selma$ LC_ALL=en_US python2 -c 'import locale; print(locale.getpreferredencoding(False))'
ANSI_X3.4-1968

haypo@selma$ LC_ALL=en_USxxx python2 -c 'import locale; print(locale.getpreferredencoding(False))'
ANSI_X3.4-1968

Internally, io.open() uses locale.getpreferredencoding(False) if you don't specify an encoding.

**Comment by ronaldoussoren** [comment]
On macOS 10.12:

ronald$ LC_ALL=en_US python2.7 -c 'import locale; print(repr(locale.getpreferredencoding()))'
''
ronald$ LC_ALL=en_US python3.6 -c 'import locale; print(repr(locale.getpreferredencoding()))'
'UTF-8'

getpreferredencoding uses the CODESET path on macOS, with means the result above is explained by this session (python 2.7):

```pycon
>>> import locale
>>> locale.setlocale(locale.LC_ALL, '')
'en_US'
>>> locale.nl_langinfo(locale.CODESET)
''
```


Note that \_pyio uses locale.getpreferedencoding(), not locale.getpreferredencoding(False). The latter would use US-ASCII as the encoding:

```pycon
>>> import locale
>>> locale.nl_langinfo(locale.CODESET)
'US-ASCII'
```



I guess the empty string for the encoding is explained by the following shell session that looks at the locale information:

```sh
$ LC_ALL=en_US.UTF-8 locale -ck LC_ALL | charmap
charmap="UTF-8"

$ LC_ALL=en_US locale -ck LC_ALL | grep charmap
charmap=
```


In python3 locale.getpreferredencoding (or rather, the same function in \_bootlocale) was tweaked to deal with this problem:

```py
if not result and sys.platform == 'darwin':
     # nl_langinfo can return an empty string
     # when the setting has an invalid value.
     # Default to UTF-8 in that case because
     # UTF-8 is the default charset on OSX and
     # returning nothing will crash the
     # interpreter.
     result = 'UTF-8'
```


Backporting this to 2.7 would IMHO be the best way to fix this issue.

**Comment by vstinner** [comment]
I created a PR to backport bpo-6393 to Python 2.7: https://github.com/python/cpython/pull/1555

**Comment by vstinner** [comment]
> Note that \_pyio uses locale.getpreferedencoding(), not locale.getpreferredencoding(False).

Oh, it's a difference between Python 2.7 and Python 3.

Python 3 calls setlocale(LC_CTYPE, "") at startup, so locale.getpreferredencoding(False) can be used in Python 3.

Python 2.7 requires to call locale.getpreferredencoding() to get the encoding of the \*user* locale.

**Comment by vstinner** [comment]
Thanks for your bug report Anthony Sottile! It's now fixed!


My backport was merged.

New changeset 94a3694c3dda97e3bcb51264bf47d948c5424d84 by Victor Stinner in branch '2.7':
bpo-6393: Fix locale.getprerredencoding() on macOS (bpo-1555)
https://github.com/python/cpython/commit/94a3694c3dda97e3bcb51264bf47d948c5424d84

Before, without the fix:

```pytb
macbook:2.7 haypo$ LANG=en_US ./python.exe -c 'import io; print(io.open("setup.py").encoding)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
LookupError: unknown encoding: 
```



After, with the fix:

macbook:2.7 haypo$ LANG=en_US ./python.exe -c 'import io; print(io.open("setup.py").encoding)'
UTF-8


--

Python 3.7 is not affected:

macbook:master haypo$ LANG=en_US ./python.exe -c 'import locale; print(locale.getpreferredencoding())'
UTF-8

macbook:master haypo$ LANG=en_US ./python.exe -c 'import io; print(io.open("setup.py").encoding)'
UTF-8

**Comment by vstinner** [comment]
The best "workaround" on Python 2.7 is to specify the encoding: replace io.open(filename) with io.open(filename, encoding="utf8").

It's always better to specify the encoding ;-)
