### ISSUE TITLE
The 'in' syntax should work with any object that implements __iter__

### ISSUE THREAD

**Issue by 52c55900-b81d-4976-b1e6-a3a1710a70ee** [python/cpython#74537]
BPO | [30352](https://bugs.python.org/issue30352)
--- | :---
Nosy | @rhettinger, @stevendaprano, @zhangyangyu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-05-12.21:41:31.972>
created_at = <Date 2017-05-12.12:18:04.014>
labels = ['interpreter-core', 'type-bug']
title = "The 'in' syntax should work with any object that implements __iter__"
updated_at = <Date 2017-05-12.21:41:31.970>
user = 'https://bugs.python.org/EdouardKLEIN'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-12.21:41:31.970>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-05-12.21:41:31.972>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-05-12.12:18:04.014>
creator = 'Edouard KLEIN'
dependencies = []
files = []
hgrepos = []
issue_num = 30352
keywords = []
message_count = 4.0
messages = ['293547', '293548', '293551', '293576']
nosy_count = 4.0
nosy_names = ['rhettinger', 'steven.daprano', 'xiang.zhang', 'Edouard KLEIN']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30352'
versions = ['Python 3.6']
```

</p></details>

**Comment by 52c55900-b81d-4976-b1e6-a3a1710a70ee** [comment]
In this StackOverflow question:

http://stackoverflow.com/questions/43935187/how-come-an-object-that-implements-iter-is-not-recognized-as-iterable/43935360#43935360

the question of why an object that implements \_\_iter__ through \_\_getattr__ does not work with the "in" syntax is raised. The accepted answer is that the interpreter checks for \_\_iter__ instead of just calling it.

If that's the case, I think that:
- Either the behaviour of the interpreter should be changed to accept any object that implements \_\_iter__, regardless of how,
- Or, if there is a technical reason why the interpreter can't change its behavior, the documentation https://docs.python.org/3/library/stdtypes.html#iterator-types should make it clear that \_\_iter__ must be hard coded into the object.

Here is the code of the object that arguably should be iterable but is not:

```py
class IterOrNotIter:
    def __init__(self):
        self.f = open('/tmp/toto.txt')
    def __getattr__(self, item):
        try:
            return self.__getattribute__(item)
        except AttributeError:
            return self.f.__getattribute__(item)
```


IterOrNotIter().\_\_iter__().\_\_next__()  # Works
'a' in IterOrNotIter()  # Raises a TypeError

**Comment by stevendaprano** [comment]
This is not a small change, and will need careful thought.

The problem is that in Python 3 (and in Python 2 for new-style classes), dunder methods are only called by the interpreter if they are defined on the class itself, not on the instance. That's an optimization, and it does mean that (for example) automatic delegation doesn't work with dunder methods.

But if we change this, we should change it for \*all* dunder methods, not just \_\_iter__. It would be a problem if we start "fixing" dunders piecemeal, one at a time. Either they should all work (like with classic classes) or none of them should.

So this is potentially a big change.

**Comment by stevendaprano** [comment]
A further thought... looking at your example code, I believe that part of the \_\_getattr__ is redundant.

```py
    def __getattr__(self, item):
        try:
            return self.__getattribute__(item)
        except AttributeError:
            return self.f.__getattribute__(item)
```



\_\_getattr__ is only called if normal attribute lookup has already failed, so the call to self.\_\_getattribute__ is unnecessary. If it would have succeeded, it would have already succeeded and \_\_getattr__ won't have been called at all.

For more discussion on how to do automatic delegation, you should look at Alex Martelli's recipe from the Python Cookbook:

https://code.activestate.com/recipes/52295-automatic-delegation-as-an-alternative-to-inherita/

Also, its a bit... funny... to call dunder methods directly. (I'm deliberately not using the word "wrong".) They are implementation, not interface. I think your \_\_getattr__ should be:

```py
    def __getattr__(self, name):
        return getattr(self.f, name)
```


It also looks nicer :-)

**Comment by rhettinger** [comment]
-1 on this proposal.  We haven't really seen a need for this in practice.  And such as change would be likely create unforeseen consequences to existing code.  

The proposal is at odds with the existing design.  Python internals work by checking for whether a given slot is filled-out.  Trying to make these lookups transparent to \_\_getattr__ calls would be tricky at best (we can't know what \_\_getattr__ does without calling it) and definitely not fast.

Even if it could be done easily, I would still prefer the current design which requires explicit delegation of magic methods by proxy objects.

FWIW, me made the same decision for super() objects ( https://docs.python.org/3/library/functions.html#super ):

"""
Note that super() is implemented as part of the binding process for explicit dotted attribute lookups such as super().\_\_getitem__(name). It does so by implementing its own \_\_getattribute__() method for searching classes in a predictable order that supports cooperative multiple inheritance. Accordingly, super() is undefined for implicit lookups using statements or operators such as super()[name].
"""

For the reasons listed above and those listed by Steven, I'm marking this as closed/rejected.  Thank you for the suggestion, but we need to decline.
