### ISSUE TITLE
ctypes: pass by value for structs broken on Cygwin/MinGW 64-bit

### ISSUE THREAD

**Issue by embray** [python/cpython#74538]
BPO | [30353](https://bugs.python.org/issue30353)
--- | :---
Nosy | @vsajip, @ned-deily, @embray, @eryksun, @zhangyangyu, @stratakis, @irushchyshyn
PRs | <li>python/cpython#1559</li><li>python/cpython#5954</li>
Files | <li>[arm64_build_log.txt](https://bugs.python.org/file46892/arm64_build_log.txt "Uploaded as text/plain at 2017-05-24.08:53:23 by @irushchyshyn")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-03-08.15:34:17.694>
created_at = <Date 2017-05-12.16:19:48.894>
labels = ['ctypes', 'type-bug', '3.7']
title = 'ctypes: pass by value for structs broken on Cygwin/MinGW 64-bit'
updated_at = <Date 2018-03-08.15:34:17.692>
user = 'https://github.com/embray'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-08.15:34:17.692>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-03-08.15:34:17.694>
closer = 'ned.deily'
components = ['ctypes']
creation = <Date 2017-05-12.16:19:48.894>
creator = 'erik.bray'
dependencies = []
files = ['46892']
hgrepos = []
issue_num = 30353
keywords = ['patch']
message_count = 14.0
messages = ['293556', '293600', '293685', '293742', '293771', '293921', '294249', '294336', '294337', '294692', '295362', '295530', '313439', '313444']
nosy_count = 7.0
nosy_names = ['vinay.sajip', 'ned.deily', 'erik.bray', 'eryksun', 'xiang.zhang', 'cstratak', 'ishcherb']
pr_nums = ['1559', '5954']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30353'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by embray** [comment]
The test ctypes.test.test_structures.StructureTestCase.test_pass_by_value fails on 64-bit Cygwin and MinGW using the system libffi with:

\======================================================================
FAIL: test_pass_by_value (ctypes.test.test_structures.StructureTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/embray/src/python/cpython/Lib/ctypes/test/test_structures.py", line 416, in test_pass_by_value
    self.assertEqual(s.first, 0xdeadbeef)
AssertionError: 195948557 != 3735928559
```



It seems that libffi does not handle passing structs by value properly on those platforms as I explained here: https://github.com/libffi/libffi/issues/305

The upstream bug hasn't been confirmed yet by the libffi developers so I could be wrong, but I think this is fairly clearly broken there.

I have a PR forthcoming to work around the issue.

**Comment by zhangyangyu** [comment]
Looks same as bpo-29804.

**Comment by embray** [comment]
Thanks for pointing that out.  Indeed it's the same symptom, but slightly different cause.  libffi has different implementations of its calling routines for different architectures/platforms depending on the machine architecture and calling conventions used.  So this case is probably buggy for the arm64 implementation as well, as in bpo-29804.

Off the top of my head I don't know a reliable way to check for this case, but this fix would work around the arm64 issue as well if I could check for that architecture easily at compile time.

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
A 'defined(__aarch64__)' can be used for the arm64 arch. I will add it to your patch and test it on an arm64 machine to see if the test passes.

**Comment by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [comment]
I have added `defined(__aarch64__)` check to the if statement and tested the patch on arm64. The test passed.

So could you please also add the check for `defined(__aarch64__)` to the pull request so that it fixes bpo-29804 as well?

**Comment by embray** [comment]
Sure, thanks for pointing that out.

**Comment by embray** [comment]
Iryna, I updated the pull request with a slightly updated fix.  Could you confirm again, when you get a chance, that it works for arm64?  Thanks.

**Comment by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [comment]
Thank you, Erik. I have applied your new patch, and ran another build on arm64. The tests passed. Attaching the build log for more information.

**Comment by embray** [comment]
Thanks for checking!

**Comment by vsajip** [comment]
Patch LGTM now, perhaps others will concur?

**Comment by vsajip** [comment]
New changeset 9ba3aa4d02a110d1a1ea464a8aff3be7dd9c63c3 by Vinay Sajip (Erik Bray) in branch 'master':
bpo-30353: Fix pass by value for structs on 64-bit Cygwin/MinGW (GH-1559)
https://github.com/python/cpython/commit/9ba3aa4d02a110d1a1ea464a8aff3be7dd9c63c3

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
This bug affects also the 3.6 branch. Can the fix be backported?
