### ISSUE TITLE
Change data model documentation to zero-argument super()

### ISSUE THREAD

**Issue by csabella** [python/cpython#74539]
BPO | [30354](https://bugs.python.org/issue30354)
--- | :---
Nosy | @ncoghlan, @Mariatta, @csabella
PRs | <li>python/cpython#1561</li><li>python/cpython#1868</li><li>python/cpython#1869</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-30.20:49:20.732>
created_at = <Date 2017-05-12.19:40:13.790>
labels = ['type-feature', '3.7', 'docs']
title = 'Change data model documentation to zero-argument super()'
updated_at = <Date 2017-05-30.20:49:20.730>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-30.20:49:20.730>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-30.20:49:20.732>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-05-12.19:40:13.790>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30354
keywords = []
message_count = 5.0
messages = ['293566', '293665', '294782', '294783', '294784']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'docs@python', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1561', '1868', '1869']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30354'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Update data model documentaion to reflect the zero-argument form of super().

**Comment by ncoghlan** [comment]
New changeset 12b1c180986fc744331b8f30d3d2f49a0fdb43dd by Nick Coghlan (csabella) in branch 'master':
bpo-30354: Update data model documentation for super() (GH-1561)
https://github.com/python/cpython/commit/12b1c180986fc744331b8f30d3d2f49a0fdb43dd

**Comment by Mariatta** [comment]
New changeset 75ea91bb736f2a061a3ebc689ff17629bdc15568 by Mariatta (csabella) in branch '3.5':
bpo-30354: Update data model documentation for super() (GH-1561) (GH-1869)
https://github.com/python/cpython/commit/75ea91bb736f2a061a3ebc689ff17629bdc15568

**Comment by Mariatta** [comment]
New changeset ad13d54646d189cea8e6f7a9bc4a87e20df33ac4 by Mariatta (csabella) in branch '3.6':
bpo-30354: Update data model documentation for super() (GH-1561) (GH-1868)
https://github.com/python/cpython/commit/ad13d54646d189cea8e6f7a9bc4a87e20df33ac4

**Comment by Mariatta** [comment]
Thanks for the PR and the backports, Cheryl :)
