### ISSUE TITLE
devguide suggests to use VS 2008 to build Python 2.7, but VS 2008 is no more supported?

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74535]
BPO | [30350](https://bugs.python.org/issue30350)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-21.23:07:27.504>
created_at = <Date 2017-05-12.09:32:47.790>
labels = ['build', 'OS-windows', 'docs']
title = 'devguide suggests to use VS 2008 to build Python 2.7, but VS 2008 is no more supported?'
updated_at = <Date 2018-09-21.23:07:27.503>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-21.23:07:27.503>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-09-21.23:07:27.504>
closer = 'vstinner'
components = ['Build', 'Documentation', 'Windows']
creation = <Date 2017-05-12.09:32:47.790>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30350
keywords = []
message_count = 12.0
messages = ['293536', '293550', '293560', '293581', '293663', '293667', '293686', '293689', '293707', '293709', '293710', '293734']
nosy_count = 8.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'docs@python', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30350'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
Steve Dower wrote this comment on my PR https://github.com/python/cpython/pull/1544 :

"Ah, I see. This is fine then - I have very little interest in doing much work to support the old build files (as they are explicitly unsupported)."

Copy of my reply:

"I have very little interest in doing much work to support the old build files (as they are explicitly unsupported)."

Wait wait wait... I fail to follow progress on the Windows build system, so I rely on the [devguide](https://devguide.python.org) which I expect to be up to date, and the guide says:

https://docs.python.org/devguide/setup.html#windows-compiling

"Python 2.7 uses Microsoft Visual Studio 2008, which is most easily obtained through an MSDN subscription."

I have a MSDN account, but after 30 min, I failed to get my MSDN number and I don't know my subscription is still valid or not (well, I guess that, it's expired). It took me 1 hour to find an old ISO of Visual Studio 2008, and not from microsoft.com :-(

I didn't want to install VS 2008, but I just followed the [devguide](https://devguide.python.org).

... Do you mean that VS 2010 must now be used and the [devguide](https://devguide.python.org) is just outdated?


Moreover: we do have a buildbot using VS 2008. I'm now trying to fix all buildbots, so I had to fix issues on this VS 2008 buildbot too: http://bugs.python.org/issue30313

But I guess that it's ok to have a buildbot on a system not officially fully supported.

**Comment by jkloth** [comment]
A few things...

First to Victor's comments on the [devguide](https://devguide.python.org).  The following sentence after the one quoted states:

"To use the build files in the PCbuild directory you will also need Visual Studio 2010"

In short, you need \*both* VS2008 and VS2010 to compile the "default" way.

Secondly, to Steve's comment on the PC\\VS9.0 build files.

Normally Steve would be correct in stating that the PC\\VS* directories are not maintained, however, in this case they are supported.  It is explicitly stated as such in the [devguide](https://devguide.python.org) and PCbuild\\readme.txt (https://github.com/python/cpython/blob/2.7/PCbuild/readme.txt).

**Comment by zware** [comment]
Jeremy is correct.

To further clarify, \*all* 2.7 Windows builders \*are* using VS 2008's compiler toolchain, but they're using VS 2015's MSBuild with VS 2010's description of 2008's compiler toolchain to build the projects described in PCbuild/.  It's a mess, but it works and makes things much easier to customize.  The two specific VS9.0 builders are using VS 2008 directly via the [PC/VS9.0](https://github.com/python/cpython/blob/main/PC/VS9.0) build files, but ideally the output from both methods should be exactly the same.  As Jeremy pointed out, the [PC/VS9.0](https://github.com/python/cpython/blob/main/PC/VS9.0) files are still explicitly supported, and those two builders were set up to make sure they're not broken.

Anything older than [PC/VS9.0](https://github.com/python/cpython/blob/main/PC/VS9.0) is explicitly \*un\*supported, and I would have no problem with just removing them (and any support for them in sysconfig).

**Comment by vstinner** [comment]
Anyway, I fixed some issues specific to VS9.0 recently, so things
should be a little bit better now :-)

For me, the last annoying issue is bpo-30313: re-run failed tests in
verbose mode. I will try to implement proposed solution.

**Comment by jkloth** [comment]
Now that my buildbot is back online, there is one unresolved issue pertaining to using VS9.0 only for building.  That is building without Perl.  It was a supported feature prior to backporting the MSBuild toolchain.  With recent OpenSSL releases, without Perl is no longer functional.

I have a changeset that restores this ability, but would like to know if that change was intentional, or just missed due to not having any buildbots covering VS9.0-only builds.

**Comment by zware** [comment]
> I have a changeset that restores this ability, but would like to know if 
> that change was intentional, or just missed due to not having any buildbots 
> covering VS9.0-only builds.

It was intentional; it was more effort than I wanted to put in to get newer OpenSSL to work with both the new build scripts and the old method, so I figured installing Perl wasn't the worst thing in the world for those who wanted to use the VS9.0 files.  If your patch isn't too big or invasive, I'd be fine with applying it, though.

**Comment by vstinner** [comment]
"To further clarify, \*all* 2.7 Windows builders \*are* using VS 2008's compiler toolchain, but they're using VS 2015's MSBuild with VS 2010's description of 2008's compiler toolchain to build the projects described in PCbuild/."

Wait? Why not suggesting to use this recent VS 2015 if it's supported? It's a pain to try to install VS 2008 in 2017: it disappeared from microsoft.com, at least the Express edition. Moreover, it becomes more and more clear that VS 2008 has a worse support than the PCbuild directory.

So why not updating the [devguide](https://devguide.python.org) to suggest first to use the PCbuild directory using VS 2010 or newer? Are the latest VS version able to use PCbuild of Python 2.7?

**Comment by vstinner** [comment]
> Now that my buildbot is back online, there is one unresolved issue pertaining to using VS9.0 only for building.  That is building without Perl.  It was a supported feature prior to backporting the MSBuild toolchain.  With recent OpenSSL releases, without Perl is no longer functional.

I opened bpo-30368 to track this issue.

**Comment by jkloth** [comment]
> Wait? Why not suggesting to use this recent VS 2015 if it's
> supported?

In theory it is supported, yes.  However, it is not compatible with previous C runtimes.  Meaning things like memory allocation (malloc) and file pointers (FILE \*) wouldn't play nice in extensions compiled against the 2008 toolchain (everything on PyPI).

> It's a pain to try to install VS 2008 in 2017: it disappeared from
> microsoft.com, at least the Express edition.

I believe that is why Microsoft released the Visual C++ Compiler for Python 2.7 (https://www.microsoft.com/en-us/download/details.aspx?id=44266) although, if memory serves, there is some issue with the 64-bit toolchain.

> Moreover, it becomes more and more clear that VS 2008 has a worse
> support than the PCbuild directory.

I guess that is why this bug report exists ;)  Seriously, though, that is why we recently added the VS9.0 builders.

> So why not updating the [devguide](https://devguide.python.org) to suggest first to use the
> PCbuild directory using VS 2010 or newer? Are the latest VS
> version able to use PCbuild of Python 2.7?

See above.  You can, but then your built Python is incompatible with the world.

**Comment by vstinner** [comment]
> I believe that is why Microsoft released the Visual C++ Compiler for Python 2.7 (https://www.microsoft.com/en-us/download/details.aspx?id=44266) although, if memory serves, there is some issue with the 64-bit toolchain.

Oh, I recall an announcement about that, but I don't see the link on
the [devguide](https://devguide.python.org). It should be added.

**Comment by eryksun** [comment]
>\> It's a pain to try to install VS 2008 in 2017: it disappeared from
>\> microsoft.com, at least the Express edition.

> I believe that is why Microsoft released the Visual C++ Compiler for 
> Python 2.7 
> (https://www.microsoft.com/en-us/download/details.aspx?id=44266) 
> although, if memory serves, there is some issue with the 64-bit
> toolchain.

That release is intended for building extension modules. Is it possible to configure it for building CPython?

**Comment by zooba** [comment]
> That release is intended for building extension modules. Is it possible to configure it for building CPython

It's intended for extension modules, but should be usable for building CPython itself if someone wants to take the time to update the Python 2.7 build system to use it. (Also, there's nothing wrong with the 64-bit toolset in this installer - that was the Windows SDK version of the compilers.)

The main reason you can't use it is because our build system is MSBuild based and the compiler package does not register with MSBuild (it doesn't provide a Platform Toolset). It would be possible to write one that would work, though I don't know exactly how to do it - I believe ICC and clang both provide the required files though, so it may be relatively easy to add the toolset files into our source repo and make it work.

There are likely some other reasons that the build will fail, but those can likely be worked around within the source repository.
