### ISSUE TITLE
itertools.groupby() can fail a C assert()

### ISSUE THREAD

**Issue by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [python/cpython#74532]
BPO | [30347](https://bugs.python.org/issue30347)
--- | :---
Nosy | @arigo, @rhettinger, @serhiy-storchaka
PRs | <li>python/cpython#1557</li><li>python/cpython#3770</li><li>python/cpython#3772</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-09-26.20:16:27.494>
created_at = <Date 2017-05-11.21:10:21.469>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'itertools.groupby() can fail a C assert()'
updated_at = <Date 2017-09-26.20:16:27.493>
user = 'https://github.com/arigo'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-26.20:16:27.493>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-09-26.20:16:27.494>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-05-11.21:10:21.469>
creator = 'arigo'
dependencies = []
files = []
hgrepos = []
issue_num = 30347
keywords = ['patch']
message_count = 8.0
messages = ['293517', '293519', '293549', '293579', '302948', '303062', '303065', '303071']
nosy_count = 3.0
nosy_names = ['arigo', 'rhettinger', 'serhiy.storchaka']
pr_nums = ['1557', '3770', '3772']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30347'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 7aa6e20b-8983-474f-b2ae-de7eff1caa04** [comment]
This triggers an assert() failure on debug-mode Python (or a leak in release Python):

```py
from itertools import groupby

def f(n):
    print("enter:", n)
    if n == 5:
        list(b)
    print("leave:", n)
    return n != 6

for (k, b) in groupby(range(10), f):
    print(list(b))
```


With current trunk we get: python: ./Modules/itertoolsmodule.c:303: \_grouper_next: Assertion \`gbo-\>currkey == NULL' failed.

**Comment by rhettinger** [comment]
Do you have a suggested fix?

**Comment by serhiy-storchaka** [comment]
[PR 1557](https://github.com/python/cpython/pull/1557) implements the simplest fix -- remove the assert and use Py_XSETREF() instead of simple assignment. Since the resulting code in \_grouper_next() is identical to the code in groupby_next(), it was shared between these two functions.

**Comment by rhettinger** [comment]
At first glance, the suggested PR looks fine.  Unless there is a rush, I would like to hold-off spend more time thinking about bpo-30346 before moving forward with this one.

**Comment by serhiy-storchaka** [comment]
Hmm, the sole bpo-30346 is not enough for fixing this crash. I don't know if there is a simpler fix based on bpo-30346, but since [PR 1557](https://github.com/python/cpython/pull/1557) removes the code duplication I'm going to merge it in any case.

**Comment by serhiy-storchaka** [comment]
New changeset c740e4fe8a9bc5815dc18c38d7f7600b128c3c51 by Serhiy Storchaka in branch 'master':
bpo-30347: Stop crashes when concurrently iterate over itertools.groupby() iterators. (bpo-1557)
https://github.com/python/cpython/commit/c740e4fe8a9bc5815dc18c38d7f7600b128c3c51

**Comment by serhiy-storchaka** [comment]
New changeset 69b2dc8637ba924d78f9869be592c5a545510f10 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-30347: Stop crashes when concurrently iterate over itertools.groupby() iterators. (GH-1557) (bpo-3770)
https://github.com/python/cpython/commit/69b2dc8637ba924d78f9869be592c5a545510f10

**Comment by serhiy-storchaka** [comment]
New changeset d0b9dc33676bdad217d5074954c1b37d4ca54a10 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30347: Stop crashes when concurrently iterate over itertools.groupby() iterators. (GH-1557). (bpo-3772)
https://github.com/python/cpython/commit/d0b9dc33676bdad217d5074954c1b37d4ca54a10
