### ISSUE TITLE
Annotating a function as returning an (async) context manager?

### ISSUE THREAD

**Issue by njsmith** [python/cpython#74544]
BPO | [30359](https://bugs.python.org/issue30359)
--- | :---
Nosy | @warsaw, @ncoghlan, @njsmith, @1st1, @ilevkivskyi, @JelleZijlstra

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-13.02:48:47.515>
labels = ['3.7', 'library']
title = 'Annotating a function as returning an (async) context manager?'
updated_at = <Date 2017-06-07.12:03:24.691>
user = 'https://github.com/njsmith'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-07.12:03:24.691>
actor = 'ncoghlan'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-05-13.02:48:47.515>
creator = 'njs'
dependencies = []
files = []
hgrepos = []
issue_num = 30359
keywords = []
message_count = 6.0
messages = ['293592', '293596', '293964', '295328', '295333', '295334']
nosy_count = 6.0
nosy_names = ['barry', 'ncoghlan', 'njs', 'yselivanov', 'levkivskyi', 'JelleZijlstra']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue30359'
versions = ['Python 3.7']
```

</p></details>

**Comment by njsmith** [comment]
sphinxcontrib-trio [1] does a few things; one of them is to enhance sphinx's autodoc support by trying to sniff out the types of functions so that it can automatically determine that something is, say, a generator, or an async classmethod.

This runs into problems when it comes to context managers, for two reasons. One reason is pretty obvious: the sniffing logic would like to be able to tell by looking at a function that it should be used as a context manager, so that it can document it as such, but there's no reliable way to do this. The other reason is more subtle: the sniffing code has to walk the .\_\_wrapped__ chain in order to detect things like async classmethods, but when it walks the chain for a @contextmanager function, it finds the underlying generator, and ends up thinking that this function should be documented as returning an iterator, which is just wrong. If we can detect context managers, we can know to ignore any 

Obviously this is always going to be a heuristic process; there's no 100% reliable way to tell what arbitrary wrappers are doing. But the heuristic works pretty well... it's just that right now the method of detecting context manager functions is pretty disgusting:

https://github.com/python-trio/sphinxcontrib-trio/blob/2d9e65187dc7a08863b68a78bdee4fb051f0b99e/sphinxcontrib_trio/__init__.py#L80-L90
https://github.com/python-trio/sphinxcontrib-trio/blob/2d9e65187dc7a08863b68a78bdee4fb051f0b99e/sphinxcontrib_trio/__init__.py#L241-L246

So it would be really nice if contextlib.contextmanager somehow marked its functions because:

- then I could (eventually) use that marker instead of making assumptions about contextmanager's internals and messing with code objects

- then we could (immediately) point to how the standard library does it as a standard for other projects to follow, instead of using this weird sphinxcontrib-trio-specific \_\_returns_contextmanager__ thing that I just made up.

I don't really care what the marker is, though I suppose \_\_returns_contextmanager__ = True is as good as anything and has the advantage of a massive installed base (2 projects).

[1] http://sphinxcontrib-trio.readthedocs.io/

**Comment by ncoghlan** [comment]
Given that we have contextlib.AbstractContextManager now, perhaps it should just set "f.\_\_annotations__['return'] = AbstractContextManager"? (assuming no other return annotation is already set)

**Comment by ilevkivskyi** [comment]
Or you can use typing.ContextManager[ret_type] if you like generics
(typing.AsyncContextManager will be also added soon).

Also this recent discussion seems relevant https://github.com/python/peps/pull/242 and the corresponding thread on python-dev: https://www.mail-archive.com/python-dev@python.org/msg95595.html

**Comment by njsmith** [comment]
I can think of two downsides to using \_\_annotations__ for this:

1) Obviously contextlib itself isn't going to add any kind of annotation in any versions before 3.7, but third-party projects might (like contextlib2, say). And these projects have been known to be used on Python versions that don't have \_\_annotations__ support. At the moment I personally don't have to care about this because sphinxcontrib-trio doesn't support anything before 3.5, but I suspect this will eventually change. (E.g. sphinx has expressed some interest in having these changes upstreamed.) So this would mean that we'd still need some other ad hoc mechanism to use when running on old Pythons, and have to check for both that and the \_\_annotations__. But that's probably doable, so eh. It'd be helpful if contextlib2 could join in on whatever protocol, though.

2) sphinxcontrib-trio actually interacts very poorly with \_\_annotations__ right now [1]. But I mean, I need to figure out how to fix this anyway, so... not really your problem :-).

Neither of these downsides seems very compelling :-). So I guess contextlib should add some appropriate \_\_annotations__, and \*maybe* also add something like \_\_returns_contextmanager__ = True if that's useful to maintain consistency with contextlib2 or similar?

(Wasn't there some discussion about keeping type hints out of the stdlib for now? is this likely to ruffle any figures on those grounds?)

[1] https://github.com/python-trio/sphinxcontrib-trio/issues/4

**Comment by ncoghlan** [comment]
As far as whether or not this usage fits within the guidelines at https://www.python.org/dev/peps/pep-0008/#function-annotations, it would definitely be worth bringing up in a python-dev thread before going ahead with it.

I think it's a good dynamic use of annotations that fits within the spirit of PEP-484 without requiring sphinxcontrib-trio to rely on a static typechecker like mypy, but others may have a different perspective.

**Comment by JelleZijlstra** [comment]
@njsmith are you still interested in pursuing this? The issue has been open for a long time with little interest, so we may be better off keeping things as is for simplicity.
