### ISSUE TITLE
Docs example: converting mixed types to floating point

### ISSUE THREAD

**Issue by ghost** [python/cpython#74546]
BPO | [30361](https://bugs.python.org/issue30361)
--- | :---
Nosy | @terryjreedy, @Mariatta
PRs | <li>python/cpython#1701</li><li>python/cpython#1856</li><li>python/cpython#1857</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-05-29.22:23:28.670>
created_at = <Date 2017-05-14.09:08:39.114>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Docs example: converting mixed types to floating point'
updated_at = <Date 2017-05-29.22:25:44.079>
user = None
```

bugs.python.org fields:
```python
activity = <Date 2017-05-29.22:25:44.079>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-05-29.22:23:28.670>
closer = 'terry.reedy'
components = ['Documentation']
creation = <Date 2017-05-14.09:08:39.114>
creator = '-'
dependencies = []
files = []
hgrepos = []
issue_num = 30361
keywords = ['easy']
message_count = 9.0
messages = ['293641', '293967', '294715', '294716', '294717', '294718', '294719', '294720', '294721']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'docs@python', 'Mariatta', '-']
pr_nums = ['1701', '1856', '1857']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30361'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ghost** [comment]
Section 3.1.1 in the Docs states:
"operators with mixed type operands convert the integer operand to floating point"
https://docs.python.org/3/tutorial/introduction.html

```pycon
But gives an example using the division operator:
>>> 3 * 3.75 / 1.5
7.5
>>> 7.0 / 2
3.5

In Python 3, division always returns a float, e.g. when all operands are integers:
>>> 3 * 3 / 1
9.0
>>> 7 / 2
3.5

To illustrate that "operators with mixed type operands convert the integer operand to floating point" the example should not use division. For example:
>>> 3 * 3.75 - 1
10.25
>>> 7.0 + 2
9.0
```

**Comment by terryjreedy** [comment]
Agreed.  Also, I think one example is enough.  A good sprint fix.

**Comment by terryjreedy** [comment]
New changeset e405d4b8dfb8b497e1c3d1f0f8e28030040c165e by terryjreedy (gfyoung) in branch 'master':
bpo-30361: Use better example for mixed-type operands (bpo-1701)
https://github.com/python/cpython/commit/e405d4b8dfb8b497e1c3d1f0f8e28030040c165e

**Comment by Mariatta** [comment]
Thanks for merging the PR, Terry.

Now it needs backport :)

**Comment by terryjreedy** [comment]
Go ahead.  I don't care much either way.

**Comment by terryjreedy** [comment]
New changeset d52f47a8f7794ee09151973a00d29c8612672e7a by terryjreedy (Mariatta) in branch '3.6':
[3.6] bpo-30361: Use better example for mixed-type operands (GH-1701) (bpo-1856)
https://github.com/python/cpython/commit/d52f47a8f7794ee09151973a00d29c8612672e7a

**Comment by terryjreedy** [comment]
New changeset 03c7cfcd52be702957cc174f5cb2ce4c8be8bfca by terryjreedy (Mariatta) in branch '3.5':
[3.5] bpo-30361: Use better example for mixed-type operands (GH-1701) (bpo-1857)
https://github.com/python/cpython/commit/03c7cfcd52be702957cc174f5cb2ce4c8be8bfca

**Comment by terryjreedy** [comment]
Just curious, what sprint?

**Comment by Mariatta** [comment]
Sorry, I don't know whether this was a sprint project or not.]
Saw that the original PR has sprint label on it, I merely copied them over to the backport PRs.

Thanks.
