### ISSUE TITLE
Unicode symbols crash lib2to3.parse

### ISSUE THREAD

**Issue by f30089f1-dc91-488a-9b0b-66525a04ea60** [python/cpython#74540]
BPO | [30355](https://bugs.python.org/issue30355)
--- | :---
Nosy | @terryjreedy, @benjaminp, @zhangyangyu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-19.19:06:27.589>
created_at = <Date 2017-05-12.21:26:00.316>
labels = ['invalid', 'type-bug', 'expert-2to3']
title = 'Unicode symbols crash lib2to3.parse'
updated_at = <Date 2017-05-19.19:06:27.547>
user = 'https://bugs.python.org/YannGrisel'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-19.19:06:27.547>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-19.19:06:27.589>
closer = 'terry.reedy'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-05-12.21:26:00.316>
creator = 'Yann Grisel'
dependencies = []
files = []
hgrepos = []
issue_num = 30355
keywords = []
message_count = 3.0
messages = ['293573', '293601', '293965']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'benjamin.peterson', 'xiang.zhang', 'Yann Grisel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30355'
versions = ['Python 3.6']
```

</p></details>

**Comment by f30089f1-dc91-488a-9b0b-66525a04ea60** [comment]
The code formatter YAPF relies on lib2to3 to parse the code before formatting it. The function "classify" from "lib2to3/pgen2/parse.py" returns a ParseError when encountering unicode variable names (like Δ), which it should not.

**Comment by zhangyangyu** [comment]
Why? Unicode identifiers are not allowed in 2.x. I don't think lib2to3 is able or responsible to parse invalid syntax source codes.

**Comment by terryjreedy** [comment]
I agree.  Δ is not a 2.x identifier (variable name) or anything else (like 'binary operator') and it would be wrong for lib2to3.pgen2.parse.classify to classify it is such, or as anything else.  So I am closing this.  Benjamin can reopen if we are mistaken.
