### ISSUE TITLE
Profile documentation - include sort argument for runctx

### ISSUE THREAD

**Issue by csabella** [python/cpython#74543]
BPO | [30358](https://bugs.python.org/issue30358)
--- | :---
Nosy | @berkerpeksag, @csabella
PRs | <li>python/cpython#1566</li><li>python/cpython#1579</li><li>python/cpython#1580</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-14.15:31:58.650>
created_at = <Date 2017-05-13.00:58:34.695>
labels = ['type-feature', '3.7', 'docs']
title = 'Profile documentation - include sort argument for runctx'
updated_at = <Date 2017-05-14.15:31:58.649>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-14.15:31:58.649>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-14.15:31:58.650>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-05-13.00:58:34.695>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30358
keywords = []
message_count = 4.0
messages = ['293638', '293639', '293650', '293651']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'cheryl.sabella']
pr_nums = ['1566', '1579', '1580']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30358'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by berkerpeksag** [comment]
For future reference, this was also reported by Chris Cummins on docs@p.o at https://mail.python.org/pipermail/docs/2017-May/031420.html

**Comment by berkerpeksag** [comment]
New changeset 99776296230ddd8429ebad2d07854b8c27ea10ab by Berker Peksag (csabella) in branch 'master':
bpo-30358: Document sort argument of profile.runctx() (GH-1566)
https://github.com/python/cpython/commit/99776296230ddd8429ebad2d07854b8c27ea10ab

**Comment by berkerpeksag** [comment]
New changeset 61b6e5cf929a80bb44500fb1a212facf66d7f45c by Berker Peksag in branch '3.6':
bpo-30358: Document sort argument of profile.runctx() (GH-1566)
https://github.com/python/cpython/commit/61b6e5cf929a80bb44500fb1a212facf66d7f45c

**Comment by berkerpeksag** [comment]
New changeset f3291eeb90da2ddb37efea30dfc9406983b0f681 by Berker Peksag in branch '3.5':
bpo-30358: Document sort argument of profile.runctx() (GH-1566)
https://github.com/python/cpython/commit/f3291eeb90da2ddb37efea30dfc9406983b0f681
