### ISSUE TITLE
Backport warnings in ElementTree/cElementTree modules and fix bugs

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74550]
BPO | [30365](https://bugs.python.org/issue30365)
--- | :---
Nosy | @scoder, @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#1581</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-17.07:09:16.698>
created_at = <Date 2017-05-14.15:38:53.969>
labels = ['extension-modules', 'expert-XML', 'type-bug', 'library']
title = 'Backport warnings in ElementTree/cElementTree modules and fix bugs'
updated_at = <Date 2017-05-17.07:09:16.698>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-17.07:09:16.698>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-17.07:09:16.698>
closer = 'serhiy.storchaka'
components = ['Extension Modules', 'Library (Lib)', 'XML']
creation = <Date 2017-05-14.15:38:53.969>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30365
keywords = []
message_count = 4.0
messages = ['293652', '293653', '293654', '293846']
nosy_count = 4.0
nosy_names = ['scoder', 'benjamin.peterson', 'eli.bendersky', 'serhiy.storchaka']
pr_nums = ['1581']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30365'
versions = ['Python 2.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch add warnings in ElementTree and cElementTree modules (backports bpo-29204) when run Python with the -3 option and fixes several bugs in the etree package and its tests:

The deprecation warning about the doctype() method was emitted when use xml.etree.ElementTree.XMLParser. Now it emitted only when use a subclass of XMLParser with defined doctype() method, as intended.

In the test_bug_200708_close test an EchoTarget instance was incorrectly passed to XMLParser() as the html argument and silently ignored. Now it is passed as the target argument.

Tests no longer failed when use the -m option for running only selected test methods. Checking warnings now is more specific, warnings are expected only when use deprecated features.

**Comment by scoder** [comment]
Looks good to me (didn't test it).

Note that getchildren() is not deprecated in lxml because it's actually the fastest way to build a list of the children. It's faster than list(element) because it avoids the Python (C-level) iteration overhead. However, that probably wouldn't be substantial enough to merit adding it if it wasn't there already. I'm ok with deprecating the method in ET. It's redundant there.

**Comment by serhiy-storchaka** [comment]
getchildren() and getiterator() were deprecated in Python implementation for years (since updating to ElementTree 1.3 in Python 2.7 and 3.2). And they are documented as deprecated. Just C implementation didn't emit warnings. It may be too late to add unconditional deprecation warnings, but we can add them as Py3k warnings.

I'm going to remove these deprecated methods in 3.8.

**Comment by serhiy-storchaka** [comment]
New changeset 09b52471f39ba280d836b945d47719c697af0b45 by Serhiy Storchaka in branch '2.7':
bpo-30365: Backport warnings and fix bugs in ElementTree. (bpo-1581)
https://github.com/python/cpython/commit/09b52471f39ba280d836b945d47719c697af0b45
