### ISSUE TITLE
[2.7] OpenSSL compilation fails on AMD64 Windows7 SP1 VS9.0 2.7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74553]
BPO | [30368](https://bugs.python.org/issue30368)
--- | :---
Nosy | @pfmoore, @vstinner, @tiran, @tjguk, @jkloth, @zware, @zooba
PRs | <li>python/cpython#1805</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.00:49:25.038>
created_at = <Date 2017-05-15.08:46:08.774>
labels = ['expert-SSL', 'build', 'OS-windows']
title = '[2.7] OpenSSL compilation fails on AMD64 Windows7 SP1 VS9.0 2.7'
updated_at = <Date 2017-06-28.00:49:25.037>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-28.00:49:25.037>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.00:49:25.038>
closer = 'vstinner'
components = ['Build', 'Windows', 'SSL']
creation = <Date 2017-05-15.08:46:08.774>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30368
keywords = []
message_count = 22.0
messages = ['293687', '293735', '293737', '293781', '293784', '294419', '294422', '294425', '294437', '294479', '294508', '295311', '295866', '296314', '296488', '296492', '296493', '296495', '296539', '296551', '296561', '297087']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'christian.heimes', 'tim.golden', 'jkloth', 'zach.ware', 'steve.dower']
pr_nums = ['1805']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30368'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
See http://bugs.python.org/issue30350#msg293663

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7/builds/83/steps/compile/logs/stdio

Build started: Project: \_ssl, Configuration: Debug|x64
...
No Perl installation was found. Existing Makefiles are used.
...
IOError: [Errno 2] No such file or directory: 'crypto\\\\buildinf_amd64.h'

**Comment by zooba** [comment]
Perl should not be required - we should be checking these files in to our clone on svn.p.o for use when building. (Perl is only required by whoever creates the source tree, normally Zach.)

Perhaps it got missed in the latest update?

**Comment by zware** [comment]
Perl is not required when using the PCbuild/ build files on any branch.  It is currently required to use the [PC/VS9.0](https://github.com/python/cpython/blob/main/PC/VS9.0) build files, at least for 64-bit builds, because I was not able to make it work (and not break the new system) in the time I had to get it done.

**Comment by vstinner** [comment]
I don't really care if Jeremy installs Perl on the buildbot or if someone succeed to fix the dependency on the svn repository. I only care of seeing a green buildbot ;-)

**Comment by zware** [comment]
The simple fix from my point of view is for Jeremy to install Perl :).  But since he also mentioned having a patch ready in bpo-30350, I'd like to see it before declaring that installing Perl is what should be done.

**Comment by jkloth** [comment]
Submitted [PR-1805](https://github.com/python/cpython/pull/1805) that should restore perl-less building.

Also some open issues as noted in the PR.

**Comment by zware** [comment]
I tried out [PR1805](https://github.com/python/cpython/pull/1805) with Perl unavailable, and it seemed to build fine with `PC\VS9.0\build.bat -e -d -p x64`.  However, trying `PC\VS9.0\amd64\python_d.exe -m test.ssltests` segfaults.  Can you reproduce?

**Comment by jkloth** [comment]
On my VM, ssltests pass, but both the Perl and non-Perl segfault in
test_ssl (and many others).  My VM has just VS2008 installed, does
VS2010 come with an updated SDK?

**Comment by jkloth** [comment]
OK, testing with the 7.1 SDK installed changes the crashes around, but something is really amiss.  I'd like to do more testing, but it will need to wait until morning here.

**Comment by zware** [comment]
Ok, sounds good.  The two points you raised on the PR also sound fine, as far as I can tell.

**Comment by jkloth** [comment]
Updated PR.  It seems that in my testing back and forth, some build artifacts were affecting my outcomes.  That's what I get for cutting corners...

Per Zach's comment, I've changed to VS project files to use the prepare_ssl.py include directories (include{suffix} vs inc{suffix}).  This simplifies build_ssl.py further.

I have, however, left the "fix_buildinf()" code in place since it requires an update to the checked-in external OpenSSL before it can be removed.

**Comment by jkloth** [comment]
Just a status check, as I would like to see my buildbot go green again.  (This along with the PR on bpo-30339).

**Comment by vstinner** [comment]
Any progress on this issue? The following buildbot still fails to build Python 2.7:
http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7

**Comment by jkloth** [comment]
This is ready to be merged, pending any comments from Zach.

**Comment by vstinner** [comment]
New changeset ebbccea997e03f60fec8308f2fb9e89a11521a74 by Victor Stinner (Jeremy Kloth) in branch '2.7':
bpo-30368: Update build_ssl.py to restore Perl-less building (bpo-1805)
https://github.com/python/cpython/commit/ebbccea997e03f60fec8308f2fb9e89a11521a74

**Comment by vstinner** [comment]
I checked AMD64 Windows7 SP1 VS9.0 2.7. Before the commit, the build 129 failed badly when building ssl:

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7/builds/129/steps/compile/logs/stdio

IOError: [Errno 2] No such file or directory: 'crypto\\\\buildinf_amd64.h'

In the first build with the commit, the compilation of ssl succeeded!

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7/builds/130

"\_ssl - 0 error(s), 375 warning(s)"

... but the compilation step still failed, for other reasons. I see that 2 projects failed:

..\\..\\Modules\\expat\\xmlparse.c(13) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
\_elementtree - 1 error(s), 9 warning(s)

and

..\\..\\Modules\\expat\\xmlparse.c(13) : fatal error C1083: Cannot open include file: 'sys/time.h': No such file or directory
pyexpat - 1 error(s), 1 warning(s)

It may be related to the recent update of libexpat from 2.1.1 to 2.2.0?

**Comment by vstinner** [comment]
In a previous build, build 111 (June 6), the compilation of \_elementtree succeeded:

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7/builds/111/steps/compile/logs/stdio
\_elementtree - 0 error(s), 10 warning(s)

I also see that the commit 0e4571a68a7f48e8469ef05b04ba3463d3fd82c0 which upgraded libexpat introduced "#ifdef WIN32". I see that libexpat 2.2.1, the new version, replace "#ifdef WIN32" with "#ifdef \_WIN32". I tested manually and it seems to fix the compilation of xmlparse.c at least! So bpo-30694 which update expat from 2.2.0 to 2.2.1 should fix this buildbot.

**Comment by vstinner** [comment]
So, I made final tests with the merged commit. I manually uninstalled (Active)Perl. Without the commit, the compilation of ssl failed on my Windows VM since I'm using VS 2008.

(1) using build.bat

git clean -fdx
In the VS2008 shell, type: PC\\VS9.0\\build.bat -e -d -p x64
=\> you get a python_d.exe with a working \_ssl module!

(2) using VS GUI

git clean -fdx
PCbuild\\get_externals.bat
Open VS 2008, build the project
=\> compilation of \_ssl fails with a permission error about a temporay object file... I don't understand it
Rebuild the project
=\> compilation of \_ssl works, python_d.exe has a working \_ssl module!

Except of the "temporary" (but reproductible) compilation error in the VS GUI, I confirm that the change fixes this issue!

I prefer to keep the issue open until the buildbot is repaired (expat issue).

**Comment by jkloth** [comment]
Added PR to bpo-29591 to address issue building Expat.  In short, the project files were not updated along with the copy of Expat.

I cannot reproduce the GUI build problem.  I would need to see the build logs to attempt to resolve.

**Comment by vstinner** [comment]
> Added PR to bpo-29591 to address issue building Expat.  In short, the project files were not updated along with the copy of Expat.

I would prefer to first fix the new vulnerabilities, but upgrading expat to 2.2.1, and then review your change.

=\> https://github.com/python/cpython/pull/2312

**Comment by vstinner** [comment]
Oh cool, with my commit 2ada64d2a073f85f135461833952dbe8d656810d "[2.7] bpo-30694: Upgrade [Modules/expat/](https://github.com/python/cpython/blob/main/Modules/expat) to libexpat 2.2.1 (bpo-2300)", and obvious Jeremy's previous fix!, the compile step of "AMD64 Windows7 SP1 VS9.0 2.7" succeeded for the first time since a long time!

**Comment by vstinner** [comment]
The initial issue ("[2.7] OpenSSL compilation fails on AMD64 Windows7 SP1 VS9.0 2.7") is now fixed, so I close the issue. Thanks for the help everyone who helped me on this one!
