### ISSUE TITLE
test_long_lines() fails randomly on AMD64 Windows7 SP1 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74556]
BPO | [30371](https://bugs.python.org/issue30371)
--- | :---
Nosy | @warsaw, @vstinner, @jkloth, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-03.13:25:22.000>
created_at = <Date 2017-05-15.16:17:12.716>
labels = ['3.7', 'tests']
title = 'test_long_lines() fails randomly on AMD64 Windows7 SP1 3.x'
updated_at = <Date 2017-07-03.13:25:21.998>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.13:25:21.998>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-03.13:25:22.000>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-15.16:17:12.716>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30371
keywords = []
message_count = 9.0
messages = ['293721', '293805', '293810', '293811', '293815', '293817', '293821', '293823', '297580']
nosy_count = 4.0
nosy_names = ['barry', 'vstinner', 'jkloth', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30371'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.x/builds/436/steps/test/logs/stdio

\======================================================================
FAIL: test_long_lines (test.test_email.test_email.TestFeedParsers)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.x.kloth-win64\build\lib\test\test_email\test_email.py", line 3526, in test_long_lines
    self.assertEqual(m.get_payload(), 'x'*M*N)
AssertionError: 'xxxx[17103482 chars]xxxxxzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[2896464 chars]xxxx' != 'xxxx[17103482 chars]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[2896464 chars]xxxx'
```



Notice the "z" in "...xxxxxz...".

**Comment by vstinner** [comment]
New fail, same buildbot:

\======================================================================
FAIL: test_long_lines (test.test_email.test_email.TestFeedParsers)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\buildbot.python.org\3.x.kloth-win64\build\lib\test\test_email\test_email.py", line 3534, in test_long_lines
    self.assertEqual(m.items(), [('a', ''), ('b', 'x'*M*N)])
AssertionError: Lists differ: [('a'[1845894 chars]xxxxxzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[18154072 chars]xx')] != [('a'[1845894 chars]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[18154072 chars]xx')]
```


First differing element 1:
('b',[1845882 chars]xxxxxzxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[18154071 chars]xxx')
('b',[1845882 chars]xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx[18154071 chars]xxx')

  [('a', ''),
   ('b',


Don't click on http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.x/builds/439/steps/test/logs/stdio : the log contains lines of 2 MB which make my Firefox super slow :-)

**Comment by jkloth** [comment]
Watch this space, but I'm pretty sure that it is (was) bad memory.  It passes memtest86+ but I had issues with these kits in other machines.  I swapped out the stick I believe that had the stuck bit.  

Unfortunately, it is a wait and see solution, as they do pass memtest86+, just not the Python test suite ;)

**Comment by vstinner** [comment]
> Watch this space, but I'm pretty sure that it is (was) bad memory.

It's really strange that only one very specific Python test fails if it's a bad memory issue?

**Comment by jkloth** [comment]
My thinking is that in normal running, the in-use memory is below the bad bit.  It is due to that test using such a large chunk of memory that it pushes the data into the bad area.  I would wager that if largemem tests were run, the would error as well.

**Comment by vstinner** [comment]
If you are sure that your memory has issues, don't test it, just change it. I had memory issues once but memtest86 was quick to prove memory errors in my case. I changed the memory for free since it was still under the warranty.

**Comment by jkloth** [comment]
That's the real problem, I'm not \*sure* it's the memory, but it does have the symptoms.  And that is why my buildbot was down earlier, I was attempting to determine the bad stick and replace it.  I'm just hoping I changed the right one.  That is why I brought up the testing (they both pass memtest).

So far so good, no test_email issues after the change, but only 2 runs in.

**Comment by vstinner** [comment]
See also bpo-20118: test_linetoolong() of test_imaplib is skipped "temporarily" on Python 2.7 since 2014 :-)

**Comment by vstinner** [comment]
Jeremy Kloth changed a memory stick on his physical server. I didn't see this bug recently, so I consider that the bug is fixed.

Thank you Jeremy!
