### ISSUE TITLE
Incomplete description of re.LOCALE

### ISSUE THREAD

**Issue by ec31e85c-a35c-494f-805f-21a63c135c1b** [python/cpython#74558]
BPO | [30373](https://bugs.python.org/issue30373)
--- | :---
Nosy | @jwilk, @serhiy-storchaka
Superseder | <li>bpo-24896: It is undocumented that re.UNICODE and re.LOCALE affect re.IGNORECASE</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-15.18:43:03.451>
created_at = <Date 2017-05-15.17:33:23.635>
labels = ['docs']
title = 'Incomplete description of re.LOCALE'
updated_at = <Date 2017-05-15.18:43:03.422>
user = 'https://github.com/jwilk'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-15.18:43:03.422>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-15.18:43:03.451>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-05-15.17:33:23.635>
creator = 'jwilk'
dependencies = []
files = []
hgrepos = []
issue_num = 30373
keywords = []
message_count = 2.0
messages = ['293726', '293729']
nosy_count = 3.0
nosy_names = ['jwilk', 'docs@python', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '24896'
type = None
url = 'https://bugs.python.org/issue30373'
versions = []
```

</p></details>

**Comment by ec31e85c-a35c-494f-805f-21a63c135c1b** [comment]
\<https://docs.python.org/3/library/re.html#re.LOCALE\> reads:
"Make \\w, \\W, \\b, \\B, \\s and \\S dependent on the current locale."

But this is not the only thing this flag does. When combined with re.IGNORECASE,  it also makes case-insesitive matching locale-dependent.

**Comment by serhiy-storchaka** [comment]
This looks similar to bpo-24896. Closing this issue as a duplicate since it is makes large sense to merge these two documentation changes.
