### ISSUE TITLE
test_smtpnet.test_connect_using_sslcontext_verified() randomly failed with "smtplib.SMTPServerDisconnected: Connection unexpectedly closed" on AMD64 FreeBSD CURRENT Debug 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74566]
BPO | [30381](https://bugs.python.org/issue30381)
--- | :---
Nosy | @vstinner, @tiran, @koobs

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.16:29:42.623>
created_at = <Date 2017-05-16.22:18:35.078>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_smtpnet.test_connect_using_sslcontext_verified() randomly failed with "smtplib.SMTPServerDisconnected: Connection unexpectedly closed" on AMD64 FreeBSD CURRENT Debug 3.x'
updated_at = <Date 2017-09-15.16:29:42.621>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.16:29:42.621>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.16:29:42.623>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-16.22:18:35.078>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30381
keywords = ['buildbot']
message_count = 3.0
messages = ['293808', '301511', '302265']
nosy_count = 3.0
nosy_names = ['vstinner', 'christian.heimes', 'koobs']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30381'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
See also bpo-30331 (test_poplib) and bpo-30328 (test_ssl): other connection reset on the FreeBSD buildbots.

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/272/steps/test/logs/stdio

0:15:55 load avg: 1.77 [387/405/1] test_smtpnet failed -- running: test_subprocess (62 sec)
test_connect (test.test_smtpnet.SmtpSSLTest) ... ok
test_connect_default_port (test.test_smtpnet.SmtpSSLTest) ... ok
test_connect_using_sslcontext (test.test_smtpnet.SmtpSSLTest) ... ok
test_connect_using_sslcontext_verified (test.test_smtpnet.SmtpSSLTest) ... ERROR
test_connect_starttls (test.test_smtpnet.SmtpTest) ... ok

\======================================================================
ERROR: test_connect_using_sslcontext_verified (test.test_smtpnet.SmtpSSLTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_smtpnet.py", line 77, in test_connect_using_sslcontext_verified
    server = smtplib.SMTP_SSL(self.testServer, self.remotePort, context=context)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/smtplib.py", line 1029, in __init__
    source_address)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/smtplib.py", line 337, in connect
    (code, msg) = self.getreply()
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/smtplib.py", line 393, in getreply
    raise SMTPServerDisconnected("Connection unexpectedly closed")
smtplib.SMTPServerDisconnected: Connection unexpectedly closed
```


----------------------------------------------------------------------
Ran 5 tests in 7.470s

FAILED (errors=1)
test test_smtpnet failed

**Comment by tiran** [comment]
Probably not a bug in the SSL module

**Comment by vstinner** [comment]
Sadly, I didn't see the bug again since I report it. So I close the bug :-(
