### ISSUE TITLE
Curses documentation refers to incorrect type

### ISSUE THREAD

**Issue by 912184f5-0882-4e83-8706-852c046ba7db** [python/cpython#74561]
BPO | [30376](https://bugs.python.org/issue30376)
--- | :---
Nosy | @kushaldas
PRs | <li>python/cpython#1630</li><li>python/cpython#1746</li><li>python/cpython#1747</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-23.17:56:35.956>
created_at = <Date 2017-05-15.21:16:05.280>
labels = ['type-bug', '3.7', 'docs']
title = 'Curses documentation refers to incorrect type'
updated_at = <Date 2017-05-23.17:56:35.955>
user = 'https://bugs.python.org/RyanJarvis'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-23.17:56:35.955>
actor = 'kushal.das'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-23.17:56:35.956>
closer = 'kushal.das'
components = ['Documentation']
creation = <Date 2017-05-15.21:16:05.280>
creator = 'Ryan Jarvis'
dependencies = []
files = []
hgrepos = []
issue_num = 30376
keywords = []
message_count = 5.0
messages = ['293740', '294207', '294264', '294265', '294268']
nosy_count = 3.0
nosy_names = ['docs@python', 'kushal.das', 'Ryan Jarvis']
pr_nums = ['1630', '1746', '1747']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30376'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 912184f5-0882-4e83-8706-852c046ba7db** [comment]
Currently the Python curses documentation refers to `WindowObject` multiple times in the documentation.  The actual type signature is `_curses.curses window`.  WindowObject does not exist.  

Seen at 16.11.1. Textbox objects and curses.initscr() for both Python2 and Python3 documentation.   

https://docs.python.org/3/library/curses.html
https://docs.python.org/2/library/curses.html

There is no type information available the curses window object in the documentation.

**Comment by kushaldas** [comment]
New changeset 93fc20b73eea3da0b6305aaee951e5dd22d5c408 by Kushal Das (Berker Peksag) in branch 'master':
bpo-30376: Update outdated WindowObject references (bpo-1630)
https://github.com/python/cpython/commit/93fc20b73eea3da0b6305aaee951e5dd22d5c408

**Comment by kushaldas** [comment]
New changeset 8af0a214be7c0c921ba5ce5c11043dd5b5da9211 by Kushal Das in branch '3.5':
[3.5] bpo-30376: Update outdated WindowObject references (GH-1630) (bpo-1747)
https://github.com/python/cpython/commit/8af0a214be7c0c921ba5ce5c11043dd5b5da9211

**Comment by kushaldas** [comment]
New changeset 9bcf81da1436468c3c5e500ae36678a2ad675e32 by Kushal Das in branch '3.6':
[3.6] bpo-30376: Update outdated WindowObject references (GH-1630) (bpo-1746)
https://github.com/python/cpython/commit/9bcf81da1436468c3c5e500ae36678a2ad675e32

**Comment by kushaldas** [comment]
Thanks for filing the bug, fixed now. Thank you Berker for the quick patch.
