### ISSUE TITLE
SysLogHandler does not support IPv6 destinations

### ISSUE THREAD

**Issue by 230cf65d-b011-43af-982a-22a6898f900d** [python/cpython#74563]
BPO | [30378](https://bugs.python.org/issue30378)
--- | :---
Nosy | @vsajip, @zhangyangyu
PRs | <li>python/cpython#1676</li><li>python/cpython#1902</li><li>python/cpython#1903</li><li>python/cpython#1904</li>
Files | <li>[test_syslog.py](https://bugs.python.org/file46865/test_syslog.py "Uploaded as text/plain at 2017-05-16.14:23:19 by calcheng"): Test script for syslog</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-01.14:24:10.743>
created_at = <Date 2017-05-16.14:23:19.881>
labels = ['3.7', 'type-bug', 'library']
title = 'SysLogHandler does not support IPv6 destinations'
updated_at = <Date 2017-06-01.14:24:10.740>
user = 'https://bugs.python.org/calcheng'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-01.14:24:10.740>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-01.14:24:10.743>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-05-16.14:23:19.881>
creator = 'calcheng'
dependencies = []
files = ['46865']
hgrepos = []
issue_num = 30378
keywords = []
message_count = 6.0
messages = ['293764', '294936', '294945', '294946', '294947', '294948']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'xiang.zhang', 'calcheng']
pr_nums = ['1676', '1902', '1903', '1904']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30378'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 230cf65d-b011-43af-982a-22a6898f900d** [comment]
The attached test script works fine with IPv4 syslog:
$ python test_syslog.py 192.168.1.4
(no errors reported)

When running the attached script with python 3.5.2 on Ubuntu 16.04, received the following error:

```sh
$ python3 test_syslog.py ::1
--- Logging error 
```
---
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.5/logging/handlers.py", line 908, in emit
    self.socket.sendto(msg, self.address)
socket.gaierror: [Errno -9] Address family for hostname not supported
Call stack:
  File "test_syslog.py", line 16, in <module>
    logging.info("Test Syslog with IPv6")
Message: 'Test Syslog with IPv6'
Arguments: ()
```


Similar error in python 2.7.10:

```pytb
$ python test_syslog.py ::1
Traceback (most recent call last):
  File "/usr/lib/python2.7/logging/handlers.py", line 864, in emit
    self.socket.sendto(msg, self.address)
gaierror: [Errno -9] Address family for hostname not supported
Logged from file test_syslog.py, line 16
```

**Comment by zhangyangyu** [comment]
New changeset 0b4b57df964f1ba427684556b8e5f05852454e0d by Xiang Zhang in branch 'master':
bpo-30378: Fix the problem that SysLogHandler can't handle IPv6 addresses (bpo-1676)
https://github.com/python/cpython/commit/0b4b57df964f1ba427684556b8e5f05852454e0d

**Comment by zhangyangyu** [comment]
New changeset e20d22671996712eac416dd7bda79b5344d81164 by Xiang Zhang in branch '3.5':
bpo-30378: Fix the problem that SysLogHandler can't handle IPv6 addresses (bpo-1676) (bpo-1902)
https://github.com/python/cpython/commit/e20d22671996712eac416dd7bda79b5344d81164

**Comment by zhangyangyu** [comment]
New changeset 95b4da2be4aeb74ee46ddece71f2075b32915c60 by Xiang Zhang in branch '3.6':
bpo-30378: Fix the problem that SysLogHandler can't handle IPv6 addresses (bpo-1676) (bpo-1903)
https://github.com/python/cpython/commit/95b4da2be4aeb74ee46ddece71f2075b32915c60

**Comment by zhangyangyu** [comment]
New changeset 3ef3bcbe38e1913119c3022ca470d06908eeda3c by Xiang Zhang in branch '2.7':
bpo-30378: Fix the problem that SysLogHandler can't handle IPv6 addresses (bpo-1904) (bpo-1676)
https://github.com/python/cpython/commit/3ef3bcbe38e1913119c3022ca470d06908eeda3c

**Comment by zhangyangyu** [comment]
Thanks calcheng for your report and Vinay for the review.
