### ISSUE TITLE
Unnecessary complexity in tokenize.py: comments and newlines

### ISSUE THREAD

**Issue by 6ff72e7e-4aad-4e79-be1d-06a37c934121** [python/cpython#74562]
BPO | [30377](https://bugs.python.org/issue30377)
--- | :---
Nosy | @terryjreedy, @meadori, @serhiy-storchaka, @albertjan
PRs | <li>python/cpython#1607</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-05-24.11:54:15.962>
created_at = <Date 2017-05-16.13:08:09.170>
labels = ['3.7', 'type-feature', 'library']
title = 'Unnecessary complexity in tokenize.py: comments and newlines'
updated_at = <Date 2017-05-24.11:54:15.961>
user = 'https://github.com/albertjan'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-24.11:54:15.961>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-05-24.11:54:15.962>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-05-16.13:08:09.170>
creator = 'Albert-Jan Nijburg'
dependencies = []
files = []
hgrepos = []
issue_num = 30377
keywords = []
message_count = 9.0
messages = ['293760', '293770', '293772', '293841', '293844', '293845', '293952', '293973', '294346']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'meador.inge', 'serhiy.storchaka', 'Albert-Jan Nijburg']
pr_nums = ['1607']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30377'
versions = ['Python 3.7']
```

</p></details>

**Comment by 6ff72e7e-4aad-4e79-be1d-06a37c934121** [comment]
While porting tokenize.py to javascript I stumbled upon this. The bit of code that checks if it's a newline or a comment, checks for comment twice. These can be split up, this way the code is a bit more readable. 

https://github.com/python/cpython/blob/master/Lib/tokenize.py#L560

It's not broken, it's just a bit more complex then it has to be.

**Comment by serhiy-storchaka** [comment]
The code is correct, it just can be made cleaner. No need to backport the change to other versions.

The line "if line[pos] in '#\\r\\n':" looks a kind of optimization. In common case (not a newline and not a comment) there is only one check. The expression "(NL, COMMENT)[line[pos] == '#']" is redundant of course, it can be replaced by just "NL". Note that now the line that yields yield TokenInfo(NL, ...) is almost the same for comments and newlines. If rename nl_pos to pos the same line can be used in both cases.

**Comment by 6ff72e7e-4aad-4e79-be1d-06a37c934121** [comment]
Oh yes you're right! I've updated the code on github. Even cleaner this way :).

**Comment by serhiy-storchaka** [comment]
This is simple change, and I would write the same code, but just for the case could you please sign CLA?

**Comment by 6ff72e7e-4aad-4e79-be1d-06a37c934121** [comment]
I did yesterday, should be coming through today right?

**Comment by serhiy-storchaka** [comment]
Don't worry, CLA is accepted manually, and this takes some time.

**Comment by 6ff72e7e-4aad-4e79-be1d-06a37c934121** [comment]
Still no CLA, I checked my username on the pdf, and it's correct, hope someone looks at it soon :)

**Comment by terryjreedy** [comment]
This is pycon week, so staff person is busy with that.

**Comment by serhiy-storchaka** [comment]
New changeset c471ca448cf336d7eb4a7cbe14d0012baf122d1f by Serhiy Storchaka (Albert-Jan Nijburg) in branch 'master':
bpo-30377: Simplify handling of COMMENT and NL in tokenize.py (bpo-1607)
https://github.com/python/cpython/commit/c471ca448cf336d7eb4a7cbe14d0012baf122d1f
