### ISSUE TITLE
distutils._msvccompiler cannot find VS 2017

### ISSUE THREAD

**Issue by zooba** [python/cpython#74574]
BPO | [30389](https://bugs.python.org/issue30389)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @merwok, @zware, @zooba, @dstufft
PRs | <li>python/cpython#1632</li><li>python/cpython#3425</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-09-11.15:53:48.951>
created_at = <Date 2017-05-17.17:54:52.483>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = 'distutils._msvccompiler cannot find VS 2017'
updated_at = <Date 2017-09-11.17:23:05.940>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-11.17:23:05.940>
actor = 'vstinner'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-09-11.15:53:48.951>
closer = 'steve.dower'
components = ['Distutils', 'Windows']
creation = <Date 2017-05-17.17:54:52.483>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 30389
keywords = []
message_count = 7.0
messages = ['293862', '301612', '301632', '301676', '301704', '301881', '301892']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'eric.araujo', 'zach.ware', 'steve.dower', 'dstufft']
pr_nums = ['1632', '3425']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30389'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zooba** [comment]
Visual Studio 2017 (including VC 14.1) cannot be discovered by the old registry key method. There is a new method that requires instantiating a COM class and querying for all installs, then selecting one.

My pyfindvs library (https://github.com/zooba/pyfindvs) can find a VS 2017 installation, and I propose porting the core C function into Python so that distutils.\_msvccompiler can use it.

This would be internal and not for public use (except via the normal build_ext API).

**Comment by zooba** [comment]
New changeset 05f01d85257d0f3409c7335aaf0bf6a6da7eecb7 by Steve Dower in branch 'master':
bpo-30389 Adds detection of VS 2017 to distutils.\_msvccompiler (bpo-1632)
https://github.com/python/cpython/commit/05f01d85257d0f3409c7335aaf0bf6a6da7eecb7

**Comment by zooba** [comment]
New changeset 76006f285a7e146484d9296597d1d0ace778f992 by Steve Dower in branch '3.6':
[3.6] bpo-30389 Adds detection of VS 2017 to distutils.\_msvccompiler python/cpython#45973 (bpo-3425)
https://github.com/python/cpython/commit/76006f285a7e146484d9296597d1d0ace778f992

**Comment by vstinner** [comment]
I'm pretty sure that the commit 05f01d85257d0f3409c7335aaf0bf6a6da7eecb7 introduced this memory leak:

test_distutils leaked [8736, 8740, 8740] references, sum=26216
test_distutils leaked [8640, 8642, 8642] memory blocks, sum=25924

http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%203.x/builds/99/steps/test/logs/stdio

**Comment by vstinner** [comment]
Python 3.6 is also impacted:
http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%203.6/builds/104

**Comment by zooba** [comment]
I fixed the ref leak during the sprints but forgot to tag this issue in the PR.

**Comment by vstinner** [comment]
The fix:

commit af8d6b90723daa943c5cd0a38ee7564790d8687a
Author: Steve Dower \<steve.dower@microsoft.com\>
Date:   Fri Sep 8 11:35:38 2017 -0700

    Fixes reference leak (bpo-3457)
