### ISSUE TITLE
warning of threading_cleanup in test_threading

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#74572]
BPO | [30387](https://bugs.python.org/issue30387)
--- | :---
Nosy | @vstinner, @zhangyangyu
PRs | <li>python/cpython#1634</li><li>python/cpython#1636</li><li>python/cpython#1637</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-17.22:39:17.383>
created_at = <Date 2017-05-17.15:01:59.068>
labels = ['3.7', 'tests']
title = 'warning of threading_cleanup in test_threading'
updated_at = <Date 2017-05-17.22:39:17.381>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-17.22:39:17.381>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-17.22:39:17.383>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-17.15:01:59.068>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 30387
keywords = []
message_count = 10.0
messages = ['293857', '293867', '293868', '293869', '293871', '293875', '293878', '293890', '293892', '293900']
nosy_count = 2.0
nosy_names = ['vstinner', 'xiang.zhang']
pr_nums = ['1634', '1636', '1637']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30387'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
Running test_threading throws a warning now.

./python -m test test_threading
Run tests sequentially
0:00:00 load avg: 0.22 [1/1] test_threading
Warning -- threading_cleanup() failed to cleanup 0 threads after 2 sec (count: 0, dangling: 21)
1 test OK.

Total duration: 13 sec
Tests result: SUCCESS

Seems related to 79ef7f8e88a4972c4aecf95cfc5cd934f1861e08.

**Comment by vstinner** [comment]
What is your OS? On which Python version?

**Comment by vstinner** [comment]
> Seems related to 79ef7f8e88a4972c4aecf95cfc5cd934f1861e08.

That's bpo-30357.

It's just that before test_threaindg "leaked" tests but there was no warning. Getting a warning is a good thing, it means that we have a bug that it must be fixed ;-)

**Comment by vstinner** [comment]
Oh wait, I succeeded to reproduce the bug on master. In verbose mode, we even get the test name!

test_is_alive_after_fork (test.test_threading.ThreadTests) ... Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 21)
ok

**Comment by vstinner** [comment]
https://github.com/python/cpython/pull/1634 fixes the 
test_is_alive_after_fork() warning on Linux.

**Comment by vstinner** [comment]
New changeset f8d05b3a24e745ab4a974b891ac1389e2f11ce4d by Victor Stinner in branch 'master':
bpo-30387: Fix warning in test_threading (bpo-1634)
https://github.com/python/cpython/commit/f8d05b3a24e745ab4a974b891ac1389e2f11ce4d

**Comment by vstinner** [comment]
Oh, strange, the test in Python 2.7 doesn't have the bug: see commit 30a5445b30bb627a64b2d30788f6db58f6db3ae1. Compare it to the code in Python 3: commit 9939cc89a4ee54ab50719a597a8b8a0795a691f6.

The warning is already fixed in master. I created backports for 3.5 and 3.6.

**Comment by vstinner** [comment]
New changeset 44944b602af23712d7119801183cdc6e202e4f76 by Victor Stinner in branch '3.6':
bpo-30387: Fix warning in test_threading (bpo-1634) (bpo-1636)
https://github.com/python/cpython/commit/44944b602af23712d7119801183cdc6e202e4f76

**Comment by vstinner** [comment]
New changeset f5633e02433a81a6d0f14fc1c3294e752f4ac1a3 by Victor Stinner in branch '3.5':
bpo-30387: Fix warning in test_threading (bpo-1634) (bpo-1637)
https://github.com/python/cpython/commit/f5633e02433a81a6d0f14fc1c3294e752f4ac1a3

**Comment by vstinner** [comment]
Ok, the warning should now be fixed. Thanks for the report Xiang. I don't know how I missed it ;-)
