### ISSUE TITLE
Unexpected and/or inconsistent del behavior

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#74587]
BPO | [30402](https://bugs.python.org/issue30402)
--- | :---
Nosy | @rhettinger, @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-19.04:46:10.332>
created_at = <Date 2017-05-18.20:57:29.599>
labels = ['interpreter-core', 'invalid']
title = 'Unexpected and/or inconsistent del behavior'
updated_at = <Date 2017-05-19.04:46:10.278>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-19.04:46:10.278>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-19.04:46:10.332>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-05-18.20:57:29.599>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 30402
keywords = []
message_count = 2.0
messages = ['293942', '293948']
nosy_count = 2.0
nosy_names = ['rhettinger', 'bup']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30402'
versions = ['Python 3.6']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
```py
k = 'k'
del [k]
```


That deletes the variable k from the local scope (even though it \*looks* like it's trying to delete a list containing 1 element which is equivalent to the variable k).

But if using list literals to delete groups of objects is valid, then why not set literals?

del {k}
raises SyntaxError: can't delete literal

The better option imo would be to only allow tuples when del-ing groups of objects, but if list literals are allowed then set literals should be as well.

**Comment by rhettinger** [comment]
Sorry, this is just how expression lists work.  See [Grammar/Grammar](https://github.com/python/cpython/blob/main/Grammar/Grammar) at https://hg.python.org/cpython/file/tip/Grammar/Grammar

This is really no different than: 
    for [k] is s: ...
or:
    [k, j] = s

> Why not set literals

Because sets are unordered and because it isn't needed.
