### ISSUE TITLE
Get rid of trailing comma in the repr() of BaseException

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74584]
BPO | [30399](https://bugs.python.org/issue30399)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka
PRs | <li>python/cpython#1650</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.15:54:13.976>
created_at = <Date 2017-05-18.15:32:17.794>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Get rid of trailing comma in the repr() of BaseException'
updated_at = <Date 2017-11-15.15:54:13.975>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.15:54:13.975>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.15:54:13.976>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-05-18.15:32:17.794>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30399
keywords = []
message_count = 3.0
messages = ['293928', '293977', '306278']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'serhiy.storchaka']
pr_nums = ['1650']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30399'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The repr() of BaseException (and all exceptions that don't override \_\_repr__) with a single argument contains a redundant trailing comma:

```pycon
>>> BaseException('spam')
BaseException('spam',)
```


This is just an artefact of the implementation.

Proposed patch removes this comma.

**Comment by terryjreedy** [comment]
I think the trailing comma is slightly worse than redundant, as someone who has forgotten the trailing comma rule for calls can mistakenly read it as making the arg a tuple.  So +1 on removing it.

**Comment by serhiy-storchaka** [comment]
New changeset f8a4c03ede6048022f60a58d5a21b278b78a8a16 by Serhiy Storchaka in branch 'master':
bpo-30399: Get rid of trailing comma in the repr of BaseException. (bpo-1650)
https://github.com/python/cpython/commit/f8a4c03ede6048022f60a58d5a21b278b78a8a16
