### ISSUE TITLE
multiprocesing.Queue silently ignore messages after exc in _feeder

### ISSUE THREAD

**Issue by 6dc2ace7-63c1-4dd4-a1e8-050515409c65** [python/cpython#74599]
BPO | [30414](https://bugs.python.org/issue30414)
--- | :---
Nosy | @pitrou, @vstinner, @applio, @zhangyangyu, @tomMoral, @grzgrzgrz3
PRs | <li>python/cpython#1683</li><li>python/cpython#1815</li><li>python/cpython#1816</li><li>python/cpython#1817</li><li>python/cpython#1013</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.15:54:28.329>
created_at = <Date 2017-05-20.18:26:50.921>
labels = ['3.7', 'type-bug', 'library']
title = 'multiprocesing.Queue silently ignore messages after exc in _feeder'
updated_at = <Date 2017-06-09.12:29:15.767>
user = 'https://github.com/grzgrzgrz3'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.12:29:15.767>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-25.15:54:28.329>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-05-20.18:26:50.921>
creator = 'grzgrzgrz3'
dependencies = []
files = []
hgrepos = []
issue_num = 30414
keywords = []
message_count = 12.0
messages = ['294044', '294399', '294401', '294481', '294485', '294486', '294492', '294493', '295022', '295040', '295116', '295521']
nosy_count = 6.0
nosy_names = ['pitrou', 'vstinner', 'davin', 'xiang.zhang', 'tomMoral', 'grzgrzgrz3']
pr_nums = ['1683', '1815', '1816', '1817', '1013']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30414'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6dc2ace7-63c1-4dd4-a1e8-050515409c65** [comment]
multiprocessing.Queue is running background thread feeder. Feeder serialize and sends buffered data to pipe. 

The issue is with exception handling, feeder is catching all exceptions but out of main loop, so after exception is handled feeder is not going back to loop - thread finish. If feeder thread is not running any Queue.put will execute without exceptions but message not gonna be delivered.

Solution is to move exception handling inside main loop. I will provide PR.

I have run performance tests (found: bpo-17025) and submitted patch do not affect performance.

**Comment by pitrou** [comment]
Can you expand on which exceptions you are getting in the feeder thread?

**Comment by pitrou** [comment]
Nevermind, I saw the PR and the test case.

**Comment by pitrou** [comment]
New changeset bc50f03db4f58c869b78e98468e374d7e61f1227 by Antoine Pitrou (grzgrzgrz3) in branch 'master':
bpo-30414: multiprocessing.Queue.\_feed do not break from main loop on exc (bpo-1683)
https://github.com/python/cpython/commit/bc50f03db4f58c869b78e98468e374d7e61f1227

**Comment by pitrou** [comment]
New changeset 2783cc42629b9445ea848ce36bbf213ef7789271 by Antoine Pitrou in branch '3.6':
[3.6] bpo-30414: multiprocessing.Queue.\_feed do not break from main loop on exc (GH-1683) (bpo-1815)
https://github.com/python/cpython/commit/2783cc42629b9445ea848ce36bbf213ef7789271

**Comment by pitrou** [comment]
New changeset 89004d761361332314beb08b443bff5b092ec36e by Antoine Pitrou in branch '3.5':
[3.5] bpo-30414: multiprocessing.Queue.\_feed do not break from main loop on exc (GH-1683) (bpo-1816)
https://github.com/python/cpython/commit/89004d761361332314beb08b443bff5b092ec36e

**Comment by pitrou** [comment]
New changeset bdd964710deffe8593063dcb63157e5b55a82c61 by Antoine Pitrou in branch '2.7':
[2.7] bpo-30414: multiprocessing.Queue.\_feed do not break from main loop on exc (GH-1683) (bpo-1817)
https://github.com/python/cpython/commit/bdd964710deffe8593063dcb63157e5b55a82c61

**Comment by pitrou** [comment]
This is committed and pushed, thank you!

**Comment by f50fb426-9df6-4590-87cf-f8a5d8c3396e** [comment]
This fix, while preventing the Queue to crash, does not give any way to  programatically detect that the message was dropped. This is a problem as we can no longer assume that the Queue will not drop messages. For instance, we can no longer detect deadlocks in concurrent.futures.ProcessPoolExecutor as done in https://github.com/python/cpython/pull/1013 where the crashed QueueFeederThread was used to monitor the working state of the executor.

We could either:
- Put a flag highlighting the fact that some messages where dropped.
- Add an argument to the Queue to close on pickling errors.

I'd be happy to work on a PR to implement any solution that you think is reasonable.

**Comment by pitrou** [comment]
Thomas, thanks for the heads up.  I would suggest something like the following patch to multiprocessing.Pool:

```diff
$ git diff
diff --git a/Lib/multiprocessing/queues.py b/Lib/multiprocessing/queues.py
index 7f77837..ebbb360 100644
--- a/Lib/multiprocessing/queues.py
+++ b/Lib/multiprocessing/queues.py
@@ -260,8 +260,16 @@ class Queue(object):
                     info('error in queue thread: %s', e)
                     return
                 else:
-                    import traceback
-                    traceback.print_exc()
+                    self._on_queue_thread_error(e)
+
+    def _on_queue_thread_error(self, e):
+        """
+        Private API called when feeding data in the background thread
+        raises an exception.  For overriding by concurrent.futures.
+        """
+        import traceback
+        traceback.print_exc()
+
 
 _sentinel = object()
 
```



Then you can write your own Queue subclass in concurrent.futures to handle that error and clean up/restart whatever needs to be cleaned up or restarted.  What do you think?

**Comment by f50fb426-9df6-4590-87cf-f8a5d8c3396e** [comment]
I think this is a good solution as it let the user define easily the behavior it needs in other situation too. I would recommend adding the object responsible for the failure to the \_on_queue_thread_error callback. This would simplify the error handling.


```diff
@@ -260,8 +260,16 @@ class Queue(object):
                     info('error in queue thread: %s', e)
                     return
                 else:
-                    import traceback
-                    traceback.print_exc()
+                    self._on_queue_thread_error(e, obj)
+
+    def _on_queue_thread_error(self, e, obj):
+        """
+        Private API called when feeding data in the background thread
+        raises an exception.  For overriding by concurrent.futures.
+        """
+        import traceback
+        traceback.print_exc()
+
```

**Comment by vstinner** [comment]
We started to get \*random* failures of test_queue_feeder_donot_stop_onexc() of test_multiprocessing_spawn since a few days. I may be related to this change. Can you please take a look at bpo-30595?
