### ISSUE TITLE
locale.getpreferredencoding doesn't return result

### ISSUE THREAD

**Issue by 5257473f-ffb4-431e-9b81-e87482d1f705** [python/cpython#74594]
BPO | [30409](https://bugs.python.org/issue30409)
--- | :---
Nosy | @vstinner, @ezio-melotti, @dstufft, @seanmccully
PRs | <li>python/cpython#1672</li>
Files | <li>[patchset.diff](https://bugs.python.org/file46877/patchset.diff "Uploaded as text/plain at 2017-05-20.03:41:43 by @seanmccully")</li><li>[suggested_change.diff](https://bugs.python.org/file46878/suggested_change.diff "Uploaded as text/plain at 2017-05-20.06:20:03 by @AraHaan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-21.02:13:39.892>
created_at = <Date 2017-05-20.03:41:44.335>
labels = ['expert-unicode']
title = "locale.getpreferredencoding doesn't return result"
updated_at = <Date 2017-05-21.10:12:19.686>
user = 'https://github.com/seanmccully'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-21.10:12:19.686>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-21.02:13:39.892>
closer = 'vstinner'
components = ['Unicode']
creation = <Date 2017-05-20.03:41:44.335>
creator = 'seanmccully'
dependencies = []
files = ['46877', '46878']
hgrepos = []
issue_num = 30409
keywords = ['patch']
message_count = 9.0
messages = ['293995', '293999', '294000', '294001', '294002', '294008', '294009', '294065', '294068']
nosy_count = 4.0
nosy_names = ['vstinner', 'ezio.melotti', 'dstufft', 'seanmccully']
pr_nums = ['1672']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30409'
versions = ['Python 2.7']
```

</p></details>

**Comment by 5257473f-ffb4-431e-9b81-e87482d1f705** [comment]
```pytb
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 312, in run
    wheel_cache
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 295, in populate_requirement_set
    wheel_cache=wheel_cache):
  File "/usr/lib/python2.7/site-packages/pip/req/req_file.py", line 84, in parse_requirements
    filename, comes_from=comes_from, session=session
  File "/usr/lib/python2.7/site-packages/pip/download.py", line 422, in get_file_content
    content = auto_decode(f.read())
  File "/usr/lib/python2.7/site-packages/pip/utils/encoding.py", line 31, in auto_decode
    return data.decode(locale.getpreferredencoding(False))
TypeError: decode() argument 1 must be string, not None
```

**Comment by vstinner** [comment]
File "/usr/lib/python2.7/site-packages/pip/utils/encoding.py", line 31, in auto_decode
    return data.decode(locale.getpreferredencoding(False))
TypeError: decode() argument 1 must be string, not None

I'm sorry, but this issue looks like a bug in pip, not in Python. Please report the issue at https://github.com/pypa/pip/issues

**Comment by vstinner** [comment]
Oh, I'm sorry, I read too fast. I didn't notice the pull request. It seems like a real bug in Python 2.7.

**Comment by vstinner** [comment]
In fact, it seems like I introduced a regression in bpo-6393, commit 94a3694c3dda97e3bcb51264bf47d948c5424d84.

**Comment by vstinner** [comment]
> In fact, it seems like I introduced a regression in bpo-6393, commit 94a3694c3dda97e3bcb51264bf47d948c5424d84.

I backported this commit, but I didn't notice the bug in the code... In fact, this commit was followed by the commit 6a448d4c2eac16af4c451b43c6dc46cf287b1671.

**Comment by 5257473f-ffb4-431e-9b81-e87482d1f705** [comment]
ok,  is this a valid fix then?

    On Saturday, May 20, 2017 1:34 AM, STINNER Victor <report@bugs.python.org> wrote:

STINNER Victor added the comment:

> In fact, it seems like I introduced a regression in bpo-6393, commit 94a3694c3dda97e3bcb51264bf47d948c5424d84.

I backported this commit, but I didn't notice the bug in the code... In fact, this commit was followed by the commit 6a448d4c2eac16af4c451b43c6dc46cf287b1671.

\----------

_______________________________________
Python tracker \<report@bugs.python.org\>
\<http://bugs.python.org/issue30409\>
_______________________________________

**Comment by vstinner** [comment]
> ok,  is this a valid fix then?

Yes, totally. Sorry, ignore my first comment.

**Comment by vstinner** [comment]
New changeset cef8b1741c03a09ea7371947dc65f632c61ef8ad by Victor Stinner (Sean McCully) in branch '2.7':
bpo-30409: locale.getpreferredencoding doesn't return result (bpo-1672)
https://github.com/python/cpython/commit/cef8b1741c03a09ea7371947dc65f632c61ef8ad

**Comment by vstinner** [comment]
Sean McCully: Thank you very much for both your bug report and for your pull request! You got your name into Python ;-)
