### ISSUE TITLE
[defaultdict] default_factory should accept a "key" default parameter (which can be passed my __missing__)

### ISSUE THREAD

**Issue by e2182fe2-eab5-4f7e-aa68-9536283d83ab** [python/cpython#74593]
BPO | [30408](https://bugs.python.org/issue30408)
--- | :---
Nosy | @rhettinger, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-05-20.06:12:42.236>
created_at = <Date 2017-05-20.02:38:07.273>
labels = ['extension-modules', '3.7']
title = '[defaultdict] default_factory should accept a "key" default parameter (which can be passed my __missing__)'
updated_at = <Date 2017-05-20.06:12:42.235>
user = 'https://bugs.python.org/namtt'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-20.06:12:42.235>
actor = 'namtt'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-05-20.06:12:42.236>
closer = 'namtt'
components = ['Extension Modules']
creation = <Date 2017-05-20.02:38:07.273>
creator = 'namtt'
dependencies = []
files = []
hgrepos = []
issue_num = 30408
keywords = []
message_count = 4.0
messages = ['293992', '293993', '294007', '294010']
nosy_count = 3.0
nosy_names = ['rhettinger', 'steven.daprano', 'namtt']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30408'
versions = ['Python 3.7']
```

</p></details>

**Comment by e2182fe2-eab5-4f7e-aa68-9536283d83ab** [comment]
currently default_factory does not accept any parameter. This made the default value generated by it constant among keys. If default_factory takes in key as the parameter, it should be able to generate default values based on key, which provide more flexibility to the class defaultdict.

**Comment by rhettinger** [comment]
Take a look at the __missing__(key) method for the regular dict API to see if it meets your needs.  It is in the ``d[key]`` section at https://docs.python.org/3/library/stdtypes.html#dict 

```pycon
>>> class UpperDict(dict):
        def __missing__(self, key):
            return key.upper()

>>> d = UpperDict()
>>> print(d['tom'])
TOM
```

**Comment by stevendaprano** [comment]
I think this should be closed. For backwards compatibility, the defaultdict default_factory function must remain as it is. There is lots of code that uses something like `int` or `list` as the factory, and if the missing key was to be passed, the code would break.

As Raymond says, if you need the key passed to your factory, you can subclass dict and give it a \_\_missing__ method.

**Comment by e2182fe2-eab5-4f7e-aa68-9536283d83ab** [comment]
Sure, thanks Raymond and Steven for your thoughts.
