### ISSUE TITLE
async and await should be keywords in 3.7

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#74591]
BPO | [30406](https://bugs.python.org/issue30406)
--- | :---
Nosy | @gvanrossum, @rhettinger, @vstinner, @giampaolo, @ambv, @PierreQuentel, @1st1, @JelleZijlstra, @miss-islington
PRs | <li>python/cpython#1669</li><li>python/cpython#6143</li><li>python/cpython#6145</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gvanrossum'
closed_at = <Date 2017-10-06.03:28:00.513>
created_at = <Date 2017-05-19.21:27:41.864>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'async and await should be keywords in 3.7'
updated_at = <Date 2019-02-27.23:41:58.653>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-27.23:41:58.653>
actor = 'gvanrossum'
assignee = 'gvanrossum'
closed = True
closed_date = <Date 2017-10-06.03:28:00.513>
closer = 'yselivanov'
components = ['Interpreter Core']
creation = <Date 2017-05-19.21:27:41.864>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 30406
keywords = []
message_count = 11.0
messages = ['293976', '293994', '293997', '294003', '303793', '303794', '305549', '305634', '314046', '314051', '336783']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'rhettinger', 'vstinner', 'giampaolo.rodola', 'lukasz.langa', 'quentel', 'yselivanov', 'JelleZijlstra', 'miss-islington']
pr_nums = ['1669', '6143', '6145']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30406'
versions = ['Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
According to PEP-492, async and await should be full keywords in Python 3.7, but this hasn't been implemented yet. I have a patch ready that I'll submit as a PR soon.

**Comment by rhettinger** [comment]
+1 These words are here to stay.   

That said, Guido needs to explicitly sign-off on any new language keywords.

**Comment by gvanrossum** [comment]
Yes, I signed off on this when I approved that PEP.

**Comment by vstinner** [comment]
It's time to remove Yury's hacks from the parser and get a sane syntax ;-) I agree to make async and await real keywords!

**Comment by 1st1** [comment]
New changeset ac317700ce7439e38a8b420218d9a5035bba92ed by Yury Selivanov (Jelle Zijlstra) in branch 'master':
bpo-30406: Make async and await proper keywords (bpo-1669)
https://github.com/python/cpython/commit/ac317700ce7439e38a8b420218d9a5035bba92ed

**Comment by 1st1** [comment]
Thanks a lot, Jelle!

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
According to PEP-492, async and await should have been deprecated in 3.5 and 3.6, but I don't think they have been :

```py
await = 1
def f(async=True):
    ...
```


don't raise any deprecation warning in 3.6.

Since version 3.7 will break existing code with a SyntaxError, could it be possible to have something explicit in the SyntaxError message for these new keywords, for instance

SyntaxError : 'async' is a keyword

I don't speack C so I can't provide a patch, sorry.

**Comment by vstinner** [comment]
> (...) don't raise any deprecation warning in 3.6.

python3 requires -Wd to display DeprecationWarning:

https://mail.python.org/pipermail/python-dev/2017-November/150149.html

Yury Selivanov: "We had PendingDeprecationWarning for async/await names in 3.5, and DeprecationWarning in 3.6."
