### ISSUE TITLE
Devguide lacks instructions for building docs

### ISSUE THREAD

**Issue by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [python/cpython#74618]
BPO | [30433](https://bugs.python.org/issue30433)
--- | :---
Nosy | @cjrh, @matrixise, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-26.16:50:50.954>
created_at = <Date 2017-05-22.18:51:43.603>
labels = ['docs']
title = 'Devguide lacks instructions for building docs'
updated_at = <Date 2017-05-26.16:50:50.902>
user = 'https://github.com/cjrh'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-26.16:50:50.902>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-05-26.16:50:50.954>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-05-22.18:51:43.603>
creator = 'cjrh'
dependencies = []
files = []
hgrepos = []
issue_num = 30433
keywords = []
message_count = 5.0
messages = ['294170', '294171', '294173', '294555', '294557']
nosy_count = 4.0
nosy_names = ['cjrh', 'docs@python', 'matrixise', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30433'
versions = []
```

</p></details>

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
The official [devguide](https://devguide.python.org) at https://github.com/python/devguide does not include instructions on exactly how to build the docs!  If, after cloning, you simply type `make`, you get some helpful output:

```sh
$ make
Please use `make <target>' where <target> is one of
  html       to make standalone HTML files
  dirhtml    to make HTML files named index.html in directories
  singlehtml to make a single large HTML file
  pickle     to make pickle files
  json       to make JSON files
  htmlhelp   to make HTML files and a HTML help project
  qthelp     to make HTML files and a qthelp project
  devhelp    to make HTML files and a Devhelp project
  epub       to make an epub
  latex      to make LaTeX files, you can set PAPER=a4 or PAPER=letter
  latexpdf   to make LaTeX files and run them through pdflatex
  text       to make text files
  man        to make manual pages
  changes    to make an overview of all changed/added/deprecated items
  linkcheck  to check all external links for integrity
  doctest    to run all doctests embedded in the documentation (if enabled)
  check      to run a check for frequent markup errors
```


However, in order to build, say, HTML, you need to have sphinx installed in your environment.  I would like to add a `requirements.txt` file that will specify which dependencies must be installed (into a virtualenv, probably), in order to successfully build the documentation.  In the GitHub PR, I have also added a BUILDING.rst that explains how to install the dependencies for building the documentation.

**Comment by matrixise** [comment]
Hello,

Are you sure about the PR ?

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
Oops, sorry!  The PR was wrong because it auto-assumes the main cpython repo, but my PR is in the [devguide](https://devguide.python.org) repo. This is the URL for the PR:

https://github.com/python/devguide/pull/206

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
The PR has been merged by Mariatta so I think this can be closed.

**Comment by Mariatta** [comment]
Thanks Caleb.

This has been addressed in the Dev Guide PR https://github.com/python/devguide/pull/206 and it has been merged.
