### ISSUE TITLE
multiprocessing AuthenticationError "digest sent was rejected"

### ISSUE THREAD

**Issue by c1b45b5b-c2dc-453d-8e39-1947ee730255** [python/cpython#74619]
BPO | [30434](https://bugs.python.org/issue30434)
--- | :---
Nosy | @zhangyangyu, @arp11, @ZackerySpytz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-08-26.01:17:28.482>
created_at = <Date 2017-05-22.20:24:15.023>
labels = ['type-bug', 'library']
title = 'multiprocessing AuthenticationError "digest sent was rejected"'
updated_at = <Date 2020-08-26.01:17:28.481>
user = 'https://bugs.python.org/SoonJeffrey'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-26.01:17:28.481>
actor = 'xiang.zhang'
assignee = 'none'
closed = True
closed_date = <Date 2020-08-26.01:17:28.482>
closer = 'xiang.zhang'
components = ['Library (Lib)']
creation = <Date 2017-05-22.20:24:15.023>
creator = 'Soon Jeffrey'
dependencies = []
files = []
hgrepos = []
issue_num = 30434
keywords = []
message_count = 4.0
messages = ['294178', '294190', '305621', '375780']
nosy_count = 4.0
nosy_names = ['xiang.zhang', 'arp11', 'Soon Jeffrey', 'ZackerySpytz']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30434'
versions = ['Python 2.7']
```

</p></details>

**Comment by c1b45b5b-c2dc-453d-8e39-1947ee730255** [comment]
This is codes I run:

```py
class TopicManager(SyncManager):
    pass
```


Server side:
m = TopicManager(address=('', 50000), authkey='12345')
s = m.get_server()
s.serve_forever()

client side:
m = TopicManager(address=('eng-g9-018', 50000), authkey='12345')
m.connect()

When I use Python2.7.5, m.connect() can connect to server.
But when I use Python2.7.13, m.connect() throws out AuthenticationError "digest sent was rejected"

Searched and multiprocessing.current_process().authkey = "12345" doesn't   help.

**Comment by 15acd0e6-bb0d-4f10-a276-cfa4c0fd79f0** [comment]
The docstring for the class points out that the `multiprocessing.Manager()` function creates started instances of the SyncManager class. You should probably follow that advice, it calls start() for you.

**Comment by zhangyangyu** [comment]
I can't reproduce the failure with 2.7.13 but I do encounter the same failure just now, much same as yours, 2.7.5 and 2.7.13.  I'd like to describe my situation.

I have one client process started by 2.7.13(I build it from source) and one server process started by the system Python 2.7.5.  I then get the same error as yours, failing at connect() and the authkey doesn't matter.

The reason I find is that the system Python is patched by the OS vendor, changing the default MD5 algorithm to SHA256.  So they can't communicate.  Patching the source or syncing the version works for me.
