### ISSUE TITLE
why not use the same style func name. eg: int.to_bytes (with underline) and array.tobytes(without underline).

### ISSUE THREAD

**Issue by 2ecf86d6-06f5-4022-9dff-01c8aac49d8e** [python/cpython#74611]
BPO | [30426](https://bugs.python.org/issue30426)
--- | :---
Nosy | @ericvsmith, @zaazbb

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-22.12:38:19.112>
created_at = <Date 2017-05-22.07:58:58.744>
labels = ['3.7', 'library']
title = 'why not use the same style func name. eg: int.to_bytes (with underline) and array.tobytes(without underline).'
updated_at = <Date 2017-05-23.03:07:47.751>
user = 'https://github.com/zaazbb'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-23.03:07:47.751>
actor = 'eric.smith'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-22.12:38:19.112>
closer = 'eric.smith'
components = ['Library (Lib)']
creation = <Date 2017-05-22.07:58:58.744>
creator = 'zaazbb'
dependencies = []
files = []
hgrepos = []
issue_num = 30426
keywords = []
message_count = 4.0
messages = ['294127', '294144', '294213', '294214']
nosy_count = 2.0
nosy_names = ['eric.smith', 'zaazbb']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30426'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2ecf86d6-06f5-4022-9dff-01c8aac49d8e** [comment]
I note that, some functions have different style names, some have underline, and some not. why do so??

eg:
int.to_bytes()  and array.tobytes()
int.from_byte() and array.frombytes()
ZipInfo.from_file() and array.fromfile()
...

**Comment by ericvsmith** [comment]
There's no particular reason, we just weren't careful about enforcing a consistent style, especially on older code.

But whatever the reason, it's now too late to change this.

**Comment by 2ecf86d6-06f5-4022-9dff-01c8aac49d8e** [comment]
how about add a unitive style function name, for a compatibility reason, keep the old function exists also.

for example, add int.tobytes(), and keep int.to_bytes() exists.

**Comment by ericvsmith** [comment]
We won't do that, because then we'd have two functions that do the same thing. There's no sense having to learn two functions, just to achieve consistency. Sorry.
