### ISSUE TITLE
isinstance checks in os.path.normcase redundant with os.fspath

### ISSUE THREAD

**Issue by db36b1c5-c904-4d78-ae55-de8a610fb115** [python/cpython#74612]
BPO | [30427](https://bugs.python.org/issue30427)
--- | :---
Nosy | @brettcannon, @serhiy-storchaka, @wm75, @miss-islington, @isidentical
PRs | <li>python/cpython#1712</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-01-02.22:13:44.727>
created_at = <Date 2017-05-22.08:17:57.051>
labels = ['3.7', 'library', 'performance']
title = 'isinstance checks in os.path.normcase redundant with os.fspath'
updated_at = <Date 2020-01-02.22:13:44.726>
user = 'https://github.com/wm75'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-02.22:13:44.726>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2020-01-02.22:13:44.727>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2017-05-22.08:17:57.051>
creator = 'wolma'
dependencies = []
files = []
hgrepos = []
issue_num = 30427
keywords = []
message_count = 7.0
messages = ['294130', '294131', '294137', '294206', '339077', '358868', '359223']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'serhiy.storchaka', 'wolma', 'miss-islington', 'BTaskaya']
pr_nums = ['1712']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30427'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by db36b1c5-c904-4d78-ae55-de8a610fb115** [comment]
os.path.normcase as defined in both posixpath and ntpath is now calling os.fspath on its argument first. With that I think the following isinstance(str, bytes) checks have become redundant since AFAIU os.fspath is guaranteed to return either str or bytes instances.

**Comment by db36b1c5-c904-4d78-ae55-de8a610fb115** [comment]
Just created a PR for this, which eliminates the redundancy. This also changes the error message (making it less specific), but not the type of a raised exception.
If you think that the error message deserves to be preserved that could, of course, be done too.

**Comment by serhiy-storchaka** [comment]
Does calling os.fspath() needed in normcase() at all? Is normcase() even called with arguments which are not just str/bytes?

**Comment by brettcannon** [comment]
The problem with leaving os.fspath() out of os.path.normcase() is that suddenly a single function that deals with paths won't work with path-like objects. So that means support for path-like objects won't implicitly work in code that assumes a path but doesn't explicitly go out of its way to support path-like objects.
