### ISSUE TITLE
Add ability to change "-- more --" text in pager module

### ISSUE THREAD

**Issue by 7a0e8e26-1b5e-419c-8ffc-f845eb202d0f** [python/cpython#74629]
BPO | [30444](https://bugs.python.org/issue30444)
--- | :---
Nosy | @rhettinger, @stevendaprano, @serhiy-storchaka, @gautamkrishnar
PRs | <li>python/cpython#1774</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-08.14:35:41.694>
created_at = <Date 2017-05-23.22:28:32.078>
labels = ['3.7', 'type-feature', 'library']
title = 'Add ability to change "-- more --" text in pager module'
updated_at = <Date 2017-07-08.14:35:41.692>
user = 'https://github.com/gautamkrishnar'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-08.14:35:41.692>
actor = 'Gautam krishna.R'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-08.14:35:41.694>
closer = 'Gautam krishna.R'
components = ['Library (Lib)']
creation = <Date 2017-05-23.22:28:32.078>
creator = 'Gautam krishna.R'
dependencies = []
files = []
hgrepos = []
issue_num = 30444
keywords = []
message_count = 7.0
messages = ['294290', '294294', '294327', '294580', '294599', '294601', '297956']
nosy_count = 4.0
nosy_names = ['rhettinger', 'steven.daprano', 'serhiy.storchaka', 'Gautam krishna.R']
pr_nums = ['1774']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30444'
versions = ['Python 3.7']
```

</p></details>

**Comment by 7a0e8e26-1b5e-419c-8ffc-f845eb202d0f** [comment]
Need ability to change the text

**Comment by stevendaprano** [comment]
Can you please explain why you need to change the --more-- text in the pager?

I haven't been able to find any way to change the "--more--" prompt in the shell commands `less` and `more`, and remember that the pager will under some circumstances use one of those.

**Comment by 7a0e8e26-1b5e-419c-8ffc-f845eb202d0f** [comment]
While i was working on one of my personal project i thought of using pager module for piping the output in the terminal, please see the issue:
https://github.com/gautamkrishnar/socli/issues/46

Adding ability to modify "-- more --" (statically specified text will allow us to change its value to something like "- Press enter to see more..." or any other value...

**Comment by serhiy-storchaka** [comment]
pydoc.pager() is not a public API. This is an internal function of the pydoc module. The stdlib does not have a benefit from adding this feature.

**Comment by 7a0e8e26-1b5e-419c-8ffc-f845eb202d0f** [comment]
Yes even if it was built for PyDoc why cant we can extend its functionality to make it work with others too, Without breaking its current functionality...

**Comment by rhettinger** [comment]
My preference is to keep pydoc focused on its primary task.  

This proposal seems like "feature creep" and the benefit is of questionable importance.

**Comment by 7a0e8e26-1b5e-419c-8ffc-f845eb202d0f** [comment]
Thank you! closing this due to inncativity..
