### ISSUE TITLE
datetime.datetime.__add__ does not respect fold.

### ISSUE THREAD

**Issue by f97acf69-d70e-4f34-a74d-4b0f1d7ed70f** [python/cpython#74628]
BPO | [30443](https://bugs.python.org/issue30443)
--- | :---
Nosy | @abalkin, @mrshannon

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-23.21:34:31.300>
created_at = <Date 2017-05-23.21:21:46.333>
labels = ['3.7', 'invalid', 'type-bug', 'library']
title = 'datetime.datetime.__add__ does not respect fold.'
updated_at = <Date 2017-05-23.21:34:31.298>
user = 'https://github.com/mrshannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-23.21:34:31.298>
actor = 'belopolsky'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-23.21:34:31.300>
closer = 'belopolsky'
components = ['Library (Lib)']
creation = <Date 2017-05-23.21:21:46.333>
creator = 'mrshannon'
dependencies = []
files = []
hgrepos = []
issue_num = 30443
keywords = []
message_count = 2.0
messages = ['294285', '294286']
nosy_count = 2.0
nosy_names = ['belopolsky', 'mrshannon']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30443'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f97acf69-d70e-4f34-a74d-4b0f1d7ed70f** [comment]
datetime.datetime.\_\_add__ is currently implemented by converting the date into a datetime.timedelta object (using toordinal) before adding it to the other (timedelta) object and reconstructing with datetime.combine.  With this method, fold will always be set to 0.

There are two cases that will produce an incorrect result (assuming positive timedelta for examples).

1. fold=0 and the timedelta is large enough to push the time into or past a fold.  Either fold will be 0 and not 1 as it should or the time will be too far ahead by the size of the fold.

2. fold=1 and the timedelta is small enough to leave the time in the fold but fold will be set to 0.  This results in the time being too far behind by the size of the fold.

A possible fix is to convert to UTC before adding the timedelta and call self.\_tzinfo.fromutc() on the result.

**Comment by abalkin** [comment]
The current behavior is intentional.  Please see PEP-495 for details.
