### ISSUE TITLE
[subinterpreters] Expose the subinterpreters C-API in the stdlib

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#74624]
BPO | [30439](https://bugs.python.org/issue30439)
--- | :---
Nosy | @ncoghlan, @vstinner, @pmp-p, @ericsnowcurrently, @zooba
PRs | <li>python/cpython#1748</li><li>python/cpython#1802</li><li>python/cpython#1803</li>
Superseder | <li>bpo-32604: [subinterpreters] PEP 554 implementation: add interpreters module</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericsnowcurrently'
closed_at = <Date 2020-05-15.01:18:14.078>
created_at = <Date 2017-05-23.05:24:25.443>
labels = ['expert-subinterpreters', 'type-feature', '3.8']
title = '[subinterpreters] Expose the subinterpreters C-API in the stdlib'
updated_at = <Date 2020-05-15.01:18:14.076>
user = 'https://github.com/ericsnowcurrently'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-15.01:18:14.076>
actor = 'vstinner'
assignee = 'eric.snow'
closed = True
closed_date = <Date 2020-05-15.01:18:14.078>
closer = 'vstinner'
components = ['Subinterpreters']
creation = <Date 2017-05-23.05:24:25.443>
creator = 'eric.snow'
dependencies = []
files = []
hgrepos = []
issue_num = 30439
keywords = []
message_count = 5.0
messages = ['294225', '294501', '294529', '310315', '368897']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'vstinner', 'pmpp', 'eric.snow', 'steve.dower']
pr_nums = ['1748', '1802', '1803']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '32604'
type = 'enhancement'
url = 'https://bugs.python.org/issue30439'
versions = ['Python 3.8']
```

</p></details>

**Comment by ericsnowcurrently** [comment]
For a variety of reasons, I'd like to be able to manage subinterpreters from Python code.  An initial effort would add a \_interpreters module to the stdlib that exposes the basic functionality of the corresponding C-API.

**Comment by ericsnowcurrently** [comment]
proposed: https://mail.python.org/pipermail/python-ideas/2017-May/045765.html

**Comment by ncoghlan** [comment]
A naming suggestion: let's leave the `interpreters` & `_interpreters` names free for a possible future PEP to make this a public API with a fallback multiprocessing backed implementation for implementations that don't have native subinterpreter support.

Then for this "testing and experimentation only" API, we'd go with "\_subinterpreters" to match the name typically used to refer to the CPython feature.
