### ISSUE TITLE
xml.etree sourcecode bug

### ISSUE THREAD

**Issue by 23004c14-65ff-496c-bf6b-b710dc617c7e** [python/cpython#74637]
BPO | [30452](https://bugs.python.org/issue30452)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[xmlMerge.py](https://bugs.python.org/file46891/xmlMerge.py "Uploaded as text/plain at 2017-05-24.08:36:17 by baksaz"): xml merger</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.11:41:21.292>
created_at = <Date 2017-05-24.08:36:18.402>
labels = ['expert-XML', 'invalid']
title = 'xml.etree sourcecode bug'
updated_at = <Date 2017-05-25.11:41:21.289>
user = 'https://bugs.python.org/baksaz'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-25.11:41:21.289>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-25.11:41:21.292>
closer = 'serhiy.storchaka'
components = ['XML']
creation = <Date 2017-05-24.08:36:18.402>
creator = 'baksaz'
dependencies = []
files = ['46891']
hgrepos = []
issue_num = 30452
keywords = []
message_count = 3.0
messages = ['294335', '294349', '294471']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'baksaz']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30452'
versions = ['Python 3.6']
```

</p></details>

**Comment by 23004c14-65ff-496c-bf6b-b710dc617c7e** [comment]
Hi,
I used before an XML merger script with 2.7 version, which was running fine. After my Anaconda was updated by SCCM to version 3.6 the same script fails and reports the following traceback:

File "C:\\Program Files\\Anaconda3\\lib\\xml\\etree\\ElementTree.py", line 1190, in
parse
 tree.parse(source, parser)
  File "C:\\Program Files\\Anaconda3\\lib\\xml\\etree\\ElementTree.py", line 591, in p
arse
    self.\_root = parser.\_parse_whole(source)
xml.etree.ElementTree.ParseError: unclosed token: line 128, column 4

What can I do?

**Comment by 23004c14-65ff-496c-bf6b-b710dc617c7e** [comment]
The error was caused, because the xml files did not had the correct close element for the root tag.
The issue is not closed, because the error message was not adequate to be able to highlight the root cause.

**Comment by serhiy-storchaka** [comment]
This error message is not created by xml.etree, it is just propagated from the expat library. Open a ticket on the expat library tracker if you want to improve the error message.
