### ISSUE TITLE
parse windows path error in webbrowser.get() and lead to webbrowser.Error: could not locate runnable browser

### ISSUE THREAD

**Issue by 36bf06ae-b4a3-44a6-ba55-bdbfbbbb5c9f** [python/cpython#74636]
BPO | [30451](https://bugs.python.org/issue30451)
--- | :---
Nosy | @birkenfeld, @serhiy-storchaka, @chainly
PRs | <li>python/cpython#1784</li><li>python/cpython#1807</li>
Superseder | <li>bpo-22025: webbrowser.get(command_line) does not support Windows-style path separators</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.01:00:19.924>
created_at = <Date 2017-05-24.05:51:58.206>
labels = ['type-bug', 'library']
title = 'parse windows path error in webbrowser.get() and lead to webbrowser.Error: could not locate runnable browser'
updated_at = <Date 2017-07-24.01:00:19.923>
user = 'https://github.com/chainly'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-24.01:00:19.923>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-24.01:00:19.924>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-05-24.05:51:58.206>
creator = 'chainly'
dependencies = []
files = []
hgrepos = []
issue_num = 30451
keywords = []
message_count = 2.0
messages = ['294325', '294455']
nosy_count = 3.0
nosy_names = ['georg.brandl', 'serhiy.storchaka', 'chainly']
pr_nums = ['1784', '1807']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '22025'
type = 'behavior'
url = 'https://bugs.python.org/issue30451'
versions = []
```

</p></details>

**Comment by 36bf06ae-b4a3-44a6-ba55-bdbfbbbb5c9f** [comment]
a bug when platform is not posix, lead to
webbrowser.Error: could not locate runnable browser
see below:
import shlex
shlex.split(r'C:\\a\\chrome.exe', comments=False, posix=True)
['C:achrome.exe']
shlex.split(r'C:\\a\\chrome.exe', comments=False, posix=False)
['C:\\a\\chrome.exe']

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-22025.
