### ISSUE TITLE
Python module cx_Oracle ld installation issue on Solaris11U3 SPARC: fatal: file /oracle/database/lib/libclntsh.so: wrong ELF class: ELFCLASS64 error

### ISSUE THREAD

**Issue by 2b3878b5-053c-472c-8a28-71adbe60c1b6** [python/cpython#74639]
BPO | [30454](https://bugs.python.org/issue30454)
--- | :---
Nosy | @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.00:34:18.540>
created_at = <Date 2017-05-24.10:56:57.370>
labels = ['build', 'expert-installation']
title = 'Python module cx_Oracle ld installation issue on Solaris11U3 SPARC: fatal: file /oracle/database/lib/libclntsh.so: wrong ELF class: ELFCLASS64 error'
updated_at = <Date 2017-07-24.00:34:18.499>
user = 'https://bugs.python.org/sameernatekar'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-24.00:34:18.499>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-24.00:34:18.540>
closer = 'berker.peksag'
components = ['Installation']
creation = <Date 2017-05-24.10:56:57.370>
creator = 'sameernatekar'
dependencies = []
files = []
hgrepos = []
issue_num = 30454
keywords = []
message_count = 2.0
messages = ['294344', '298922']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'sameernatekar']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30454'
versions = ['Python 2.7']
```

</p></details>

**Comment by 2b3878b5-053c-472c-8a28-71adbe60c1b6** [comment]
Trying to install cx_Oracle on Solaris11U3 but getting ld: fatal: file /oracle/database/lib/libclntsh.so: wrong ELF class: ELFCLASS64 error
 
\# python setup.py build
running build
running build_ext
building 'cx_Oracle' extension
cc -DNDEBUG -KPIC -DPIC -I/oracle/database/rdbms/demo -I/oracle/database/rdbms/public -I/usr/include/python2.7 -c cx_Oracle.c -o build/temp.solaris-2.11-sun4v.32bit-2.7-11g/cx_Oracle.o -DBUILD_VERSION=5.2.1
"SessionPool.c", line 202: warning: integer overflow detected: op "\<\<"
cc -G build/temp.solaris-2.11-sun4v.32bit-2.7-11g/cx_Oracle.o -L/oracle/database/lib -L/usr/lib -lclntsh -lpython2.7 -o build/lib.solaris-2.11-sun4v.32bit-2.7-11g/cx_Oracle.so
ld: fatal: file /oracle/database/lib/libclntsh.so: wrong ELF class: ELFCLASS64
error: command 'cc' failed with exit status 2
 
Tried all available information on the internet:
Installed gcc
Installed solarisstudio12.4
Installed instantclient-basic-solaris.sparc64-12.2.0.1.0, instantclient-odbc-solaris.sparc64-12.2.0.1.0
Set LD_LIBRARY_PATH to oracle home directory:instantclient_12_2/
 
Same issue seen while installing DBD:Oracle perl module.

**Comment by berkerpeksag** [comment]
cx_Oracle is not part of the Python standard library and according to https://community.oracle.com/thread/4048639 the solution is to install it from Solaris' package repository.
