### ISSUE TITLE
test_traceback fails in coverage run

### ISSUE THREAD

**Issue by 17104f8a-dfd5-4c28-a7aa-b43ed3d777b2** [python/cpython#74630]
BPO | [30445](https://bugs.python.org/issue30445)
--- | :---
Nosy | @vstinner, @zware, @codedragon
PRs | <li>python/cpython#1775</li><li>python/cpython#3356</li><li>python/cpython#3357</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-24.21:25:03.374>
created_at = <Date 2017-05-23.22:49:33.044>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_traceback fails in coverage run'
updated_at = <Date 2017-09-05.23:07:46.329>
user = 'https://github.com/codedragon'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-05.23:07:46.329>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-24.21:25:03.374>
closer = 'zach.ware'
components = ['Tests']
creation = <Date 2017-05-23.22:49:33.044>
creator = 'maria'
dependencies = []
files = []
hgrepos = []
issue_num = 30445
keywords = []
message_count = 3.0
messages = ['294396', '294397', '301396']
nosy_count = 3.0
nosy_names = ['vstinner', 'zach.ware', 'maria']
pr_nums = ['1775', '3356', '3357']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30445'
versions = ['Python 3.7']
```

</p></details>

**Comment by zware** [comment]
New changeset 3480ef9dd3177be8c0d71a74853dca6e5b11fbe1 by Zachary Ware (codedragon) in branch 'master':
 bpo-30445: Allow appended output in RecursionError message
https://github.com/python/cpython/commit/3480ef9dd3177be8c0d71a74853dca6e5b11fbe1

**Comment by zware** [comment]
Merged, thanks for the patch!

**Comment by vstinner** [comment]
New changeset 6fce7ea893dc3f69b607dd6ef48c2d3d0f6ca414 by Victor Stinner in branch '3.6':
bpo-30445: Allow appended output in RecursionError message (bpo-3356)
https://github.com/python/cpython/commit/6fce7ea893dc3f69b607dd6ef48c2d3d0f6ca414
