### ISSUE TITLE
Improve __slots__ datamodel documentation

### ISSUE THREAD

**Issue by affb16c2-6fdb-403f-b328-86b7e719c99e** [python/cpython#74634]
BPO | [30449](https://bugs.python.org/issue30449)
--- | :---
Nosy | @rhettinger, @aaronchall, @Mariatta, @csabella
PRs | <li>python/cpython#1806</li><li>python/cpython#1819</li><li>python/cpython#5815</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-15.23:36:05.333>
created_at = <Date 2017-05-24.01:01:47.039>
labels = ['3.7', 'docs']
title = 'Improve __slots__ datamodel documentation'
updated_at = <Date 2019-02-15.23:36:05.333>
user = 'https://github.com/aaronchall'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-15.23:36:05.333>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2019-02-15.23:36:05.333>
closer = 'cheryl.sabella'
components = ['Documentation']
creation = <Date 2017-05-24.01:01:47.039>
creator = 'Aaron Hall'
dependencies = []
files = []
hgrepos = []
issue_num = 30449
keywords = ['patch']
message_count = 14.0
messages = ['294305', '294310', '294429', '294515', '294521', '294532', '309213', '309274', '309293', '311470', '312569', '312571', '312572', '312574']
nosy_count = 6.0
nosy_names = ['rhettinger', 'docs@python', 'mpb', 'Aaron Hall', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1806', '1819', '5815']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30449'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
The \_\_slots__ documentation in the datamodel needs improvement.

For example:

> When inheriting from a class without \_\_slots__, the \_\_dict__ attribute of that class will always be accessible, so a \_\_slots__ definition in the subclass is meaningless.

The \_\_slots__ definition for such a subclass is not meaningless: other slots declared will still be used, and the \_\_dict__ will not be instantiated unless it is looked for (although this may be an implementation detail).

> The action of a \_\_slots__ declaration is limited to the class where it is defined. As a result, subclasses will have a \_\_dict__ unless they also define \_\_slots__ (which must only contain names of any additional slots).

That's not quite right either. The action of a \_\_slots__ declaration is not entirely limited to the class where it is defined. They can have implications for multiple inheritance, and child classes will have access to those slots.

I have some changes I'd like to make to the entire section on \_\_slots__, and I'll be providing a pull request soon.

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
I've been working on this section quite a lot, trying to improve the flow of content (which in the prior revision is a bit of a mish-mash of information in the "Notes on using \_\_slots__ section") - I intend to move some of that information into the exposition/introduction.

I have also been reviewing my changes and actively working on it with a volunteer at the PyCon sprints, Joshua Goldin. Will submit a pull request soon, tonight or tomorrow morning.

**Comment by rhettinger** [comment]
As much as possible, please stick with the existing terse style of the data model docs.  They tend to be concise, direct, and very light on examples.  They don't serve as a tutorial, faq, or cover programming patterns or advice.

Looking at the PR, I don't think most of these changes should be made.

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
I created a new PR based on rhettinger's feedback (which on consideration was quite correct) with a fresh branch from master. 

Terseness is retained, and I think this revision makes the documentation more correct and complete. The rewording makes the behavior more clear (IMHO).

No example code is needed for this revision, so I didn't give any, but one or two class definitions might be desirable.

Feedback is quite welcome!

**Comment by rhettinger** [comment]
Overall this looks good.  Please do fix the one review comment.

**Comment by rhettinger** [comment]
New changeset 2b44e302ec3079363c4d5c875677945953705c58 by Raymond Hettinger (Aaron Hall, MBA) in branch 'master':
bpo-30449 Terse slots (bpo-1819)
https://github.com/python/cpython/commit/2b44e302ec3079363c4d5c875677945953705c58
