### ISSUE TITLE
test_capi.test_subinterps() fails on ARMv7 Ubuntu 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74632]
BPO | [30447](https://bugs.python.org/issue30447)
--- | :---
Nosy | @vstinner, @ericsnowcurrently
PRs | <li>python/cpython#1791</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.00:20:42.753>
created_at = <Date 2017-05-24.00:20:39.108>
labels = ['3.7', 'tests']
title = 'test_capi.test_subinterps() fails on ARMv7 Ubuntu 3.x'
updated_at = <Date 2017-05-25.10:52:56.762>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-25.10:52:56.762>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-25.00:20:42.753>
closer = 'eric.snow'
components = ['Tests']
creation = <Date 2017-05-24.00:20:39.108>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30447
keywords = []
message_count = 5.0
messages = ['294302', '294313', '294317', '294416', '294464']
nosy_count = 2.0
nosy_names = ['vstinner', 'eric.snow']
pr_nums = ['1791']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30447'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/ARMv7%20Ubuntu%203.x/builds/786/steps/test/logs/stdio

\======================================================================
FAIL: test_subinterps (test.test_capi.EmbeddingTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/ssd/buildbot/buildarea/3.x.gps-ubuntu-exynos5-armv7l/build/Lib/test/test_capi.py", line 471, in test_subinterps
    self.assertNotEqual(interp.interp, main.interp)
AssertionError: '0x0' == '0x0'
```

**Comment by ericsnowcurrently** [comment]
Yeah, I some extra checks (involving pointers) to that test and some platforms don't work as expected.  I'll take a look in the morning.

**Comment by vstinner** [comment]
Ok thanks of taking care of my little buildbot babies.

**Comment by ericsnowcurrently** [comment]
New changeset d1c3c13fedaf62b71445ccd048e395aa4a7d510f by Eric Snow in branch 'master':
bpo-30447: Fix/skip the subinterpreters test on some platforms. (bpo-1791)
https://github.com/python/cpython/commit/d1c3c13fedaf62b71445ccd048e395aa4a7d510f

**Comment by vstinner** [comment]
Thanks for fixing that one Eric.
