### ISSUE TITLE
test_subprocess creates a core dump on FreeBSD

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74633]
BPO | [30448](https://bugs.python.org/issue30448)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @ericsnowcurrently
PRs | <li>python/cpython#2515</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-30.23:41:31.481>
created_at = <Date 2017-05-24.00:24:03.414>
labels = ['3.7', 'tests']
title = 'test_subprocess creates a core dump on FreeBSD'
updated_at = <Date 2017-06-30.23:41:31.477>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-30.23:41:31.477>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-30.23:41:31.481>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-05-24.00:24:03.414>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30448
keywords = []
message_count = 9.0
messages = ['294303', '294318', '294320', '294512', '294824', '296971', '297055', '297453', '297454']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'eric.snow']
pr_nums = ['2515']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30448'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Eric Snow: do you think that it could be related to your recent subinterpreter changes please?

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/311/steps/test/logs/stdio

0:08:26 load avg: 3.35 [253/405] test_subprocess failed (env changed) (98 sec) -- running: test_io (30 sec)

Warning -- files was modified by test_subprocess
  Before: []
  After:  ['python.core']

**Comment by ericsnowcurrently** [comment]
That looks similar to other failures due to an issue fixed in a later PR.  It shouldn't be an issue any longer.  I'll double check in the morning.

**Comment by vstinner** [comment]
I'm surprised that we only detect hard crashes only indirectly through the
creation of core dump files... Some tests might be enhanced to raise an
exception at least if the process was killed by a signal, maybe also if the
exit code is non-zero (depending on the test).

We had a similar but different issue in test_io which created a core dump
on a deliberate crash.

**Comment by ericsnowcurrently** [comment]
At this point I'm not convinced the failure is due to my recent changes.  Regardless, I do agree with you about detecting hard crashes.

**Comment by vstinner** [comment]
Sadly, I'm unable to reproduce the issue on my FreeBSD 11 VM :-(

**Comment by vstinner** [comment]
Oops, I mentioned the wrong bpo in my PRs: the fix was pushed using bpo-30764 identifier :-/

**Comment by vstinner** [comment]
It seems like test_child_terminated_in_stopped_state() of test_subprocess on Python 2.7 fails on some macOS versions, see:
http://bugs.python.org/issue30764#msg296966

Can someone please try to reproduce the bug? I'm unable to reproduce the bug on Darwin 16.5.0 (macOS Sierra?).

**Comment by vstinner** [comment]
New changeset fd93f37f0dc537eb7edca7b75e2f92ef54dd2833 by Victor Stinner in branch '2.7':
bpo-30448: Fix support.SuppressCrashReport on macOS (bpo-2515)
https://github.com/python/cpython/commit/fd93f37f0dc537eb7edca7b75e2f92ef54dd2833

**Comment by vstinner** [comment]
macOS 2.7 buildbots are back. All known bugs are fixed, I close the issue.
