### ISSUE TITLE
Add __slots__ to ABC convenience class

### ISSUE THREAD

**Issue by affb16c2-6fdb-403f-b328-86b7e719c99e** [python/cpython#74648]
BPO | [30463](https://bugs.python.org/issue30463)
--- | :---
Nosy | @rhettinger, @cjw296, @serhiy-storchaka, @ilevkivskyi, @aaronchall
PRs | <li>python/cpython#1822</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-06.19:38:51.124>
created_at = <Date 2017-05-24.20:41:17.931>
labels = ['3.7', 'type-feature', 'library']
title = 'Add __slots__ to ABC convenience class'
updated_at = <Date 2019-11-16.01:14:18.818>
user = 'https://github.com/aaronchall'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-16.01:14:18.818>
actor = 'cjw296'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-06.19:38:51.124>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-05-24.20:41:17.931>
creator = 'Aaron Hall'
dependencies = []
files = []
hgrepos = []
issue_num = 30463
keywords = []
message_count = 4.0
messages = ['294389', '294420', '295297', '356740']
nosy_count = 5.0
nosy_names = ['rhettinger', 'cjw296', 'serhiy.storchaka', 'levkivskyi', 'Aaron Hall']
pr_nums = ['1822']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30463'
versions = ['Python 3.7']
```

</p></details>

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
We have \_\_slots__ with other ABC's, see http://bugs.python.org/issue11333 and http://bugs.python.org/issue21421.

There are no downsides to having empty slots on a non-instantiable class, but it does give the option of denying \_\_dict__ creation for subclassers. 

The possibility of breaking is for someone using \_\_slots__ but relying on \_\_dict__ creation in a subclass - they will have to explicitly add "\_\_dict__" to \_\_slots__. Since we have added \_\_slots__ to other ABC's, 

I will provide a PR soon on this. Diff should look like this (in [Lib/abc.py](https://github.com/python/cpython/blob/main/Lib/abc.py)):

```diff
class ABC(metaclass=ABCMeta):
    """Helper class that provides a standard way to create an ABC using
    inheritance.
    """
- pass
+ __slots__ = ()
```


(I also want to add a test for this, and ensure other ABC's also have this if they don't.)

**Comment by rhettinger** [comment]
This seems reasonable.

**Comment by serhiy-storchaka** [comment]
New changeset ff48739ed0a3f366c4d56d3c86a37cbdeec600de by Serhiy Storchaka (Aaron Hall, MBA) in branch 'master':
bpo-30463: Add an empty \_\_slots__ to abc.ABC.
https://github.com/python/cpython/commit/ff48739ed0a3f366c4d56d3c86a37cbdeec600de
