### ISSUE TITLE
gammavariate has a wrong comment

### ISSUE THREAD

**Issue by 34524473-76d2-40a1-b37f-8dd7d594cc36** [python/cpython#74649]
BPO | [30464](https://bugs.python.org/issue30464)
--- | :---
Nosy | @rhettinger, @mdickinson, @leodema
PRs | <li>python/cpython#1798</li><li>python/cpython#1934</li>
Files | <li>[unnamed.png](https://bugs.python.org/file46895/unnamed.png "Uploaded as image/png at 2017-05-24.21:47:13 by @leodema"): Graph of expovariate(1) and gammavariate(alpha=1, beta=beta)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/mdickinson'
closed_at = <Date 2019-05-12.09:10:06.440>
created_at = <Date 2017-05-24.21:47:13.578>
labels = []
title = 'gammavariate has a wrong comment'
updated_at = <Date 2019-05-12.10:22:36.133>
user = 'https://github.com/leodema'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-12.10:22:36.133>
actor = 'mark.dickinson'
assignee = 'mark.dickinson'
closed = True
closed_date = <Date 2019-05-12.09:10:06.440>
closer = 'mark.dickinson'
components = []
creation = <Date 2017-05-24.21:47:13.578>
creator = 'leodema'
dependencies = []
files = ['46895']
hgrepos = []
issue_num = 30464
keywords = []
message_count = 5.0
messages = ['294403', '294438', '342247', '342249', '342251']
nosy_count = 4.0
nosy_names = ['rhettinger', 'mark.dickinson', 'SilentGhost', 'leodema']
pr_nums = ['1798', '1934']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30464'
versions = []
```

</p></details>

**Comment by 34524473-76d2-40a1-b37f-8dd7d594cc36** [comment]
The gammavariate function in random.py has a wrong comment.

It says that when alpha is one it's equivalent to call expovariate(1).

We can see that is not true (see graphs) and it should be expovariate(1/beta). It's not a big deal but it can cause confusion.

**Comment by rhettinger** [comment]
I agree that the comment should be changed. While we at it, perhaps sync-up with expovariate() code and eliminate the ``u <= 1e-7`` test:

Instead of:

        elif alpha == 1.0:
            # expovariate(1)
            u = random()
            while u <= 1e-7:
                u = random()
            return -_log(u) * beta

Use this instead:

        elif alpha == 1.0:
            # expovariate(1.0 / beta)
            return -_log(1.0 - random()) * beta
