### ISSUE TITLE
Allow retrieve the number of waiters pending for most of the asyncio lock primitives

### ISSUE THREAD

**Issue by 494843ea-eb4d-4035-9f53-0d2535742f7e** [python/cpython#74642]
BPO | [30457](https://bugs.python.org/issue30457)
--- | :---
Nosy | @1st1, @pfreixes
PRs | <li>python/cpython#1786</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-19.17:39:56.665>
created_at = <Date 2017-05-24.14:48:25.108>
labels = ['type-feature', '3.7', 'expert-asyncio']
title = 'Allow retrieve the number of waiters pending for most of the asyncio lock primitives'
updated_at = <Date 2017-10-19.17:39:56.664>
user = 'https://github.com/pfreixes'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-19.17:39:56.664>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-19.17:39:56.665>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-05-24.14:48:25.108>
creator = 'pfreixes'
dependencies = []
files = []
hgrepos = []
issue_num = 30457
keywords = []
message_count = 6.0
messages = ['294357', '304093', '304109', '304110', '304111', '304624']
nosy_count = 2.0
nosy_names = ['yselivanov', 'pfreixes']
pr_nums = ['1786']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30457'
versions = ['Python 3.7']
```

</p></details>

**Comment by 494843ea-eb4d-4035-9f53-0d2535742f7e** [comment]
Currently, there is no way to access to the number of waiters pending to be woken up. This information can be useful for those environments which create and delete asyncio primitives instances depending if there are waiters still to be processed.

The following example shows an example of the DogPile solution that uses the Event lock mechanism. Each time that there is a miss in the cache, a new Event is created and it will be removed by the last waiter.


```py
import asyncio

cache = {}
events = {}

async def get(process, key):
    try:
        return cache[key]
    except KeyError:
        try:
            await events[key].wait()
            if len(events[key]._waiters) == 0:
                events.pop(key)
            return cache[key]
        except KeyError:
            events[key] = asyncio.Event()
            # simulates some IO to get the Key
            await asyncio.sleep(0.1)
            cache[key] = "some random value"
            events[key].set()


async def main():
    tasks = [get(i, "foo") for i in range(1, 10)]
    await asyncio.gather(*tasks)
```


asyncio.get_event_loop().run_until_complete(main())

**Comment by 1st1** [comment]
Isn't this code equivalent to yours:

```py
async def get(process, key):
    try:
        return cache[key]
    except KeyError:
        if key in events:
            await events[key].wait()
        else:
            events[key] = asyncio.Event()
```


            # simulates some IO to get the Key
            await asyncio.sleep(0.1)
            cache[key] = "some random value"
            event.set()

        return cache[key]


?

**Comment by 494843ea-eb4d-4035-9f53-0d2535742f7e** [comment]
Not really, your code never removes the key from the events. If the cache is cleaned all further executions will keep forever in the `wait` statement. It is needed to create the Event again to perform at least one query to retrieve the cache value.

**Comment by 1st1** [comment]
> Not really, your code never removes the key from the events. If the cache is cleaned all further executions will keep forever in the `wait` statement. It is needed to create the Event again to perform at least one query to retrieve the cache value.

Right.  Well, that should be solved by adding "events.pop(key)" right after "events[key].set()"?

**Comment by 494843ea-eb4d-4035-9f53-0d2535742f7e** [comment]
You are right, having the `pop` after the `set` it would remove the key from the events. Despite the workaround that you proposes is quite clean, it is kinda implicit.

The nature of the `pending` method is to give to the developer a way to check how many waiters are still pending. This not only helps to make this code more explicit also other pieces of code that might need access to the length of the waiters.

**Comment by 1st1** [comment]
> The nature of the `pending` method is to give to the developer a way to check how many waiters are still pending. This not only helps to make this code more explicit also other pieces of code that might need access to the length of the waiters.

This also is a perfect way to introduce races in your code.  I'm going to reject this, sorry.  I've demonstrated that it's possible to do what you wanted to do without adding new functionality.
