### ISSUE TITLE
Propagate zipfile.py pypy issue #905 patch to CPython 3.7

### ISSUE THREAD

**Issue by 1510523b-2bdb-44fa-9092-cac883321cf4** [python/cpython#74653]
BPO | [30468](https://bugs.python.org/issue30468)
--- | :---
Nosy | @Yhg1s, @serhiy-storchaka, @shubharamani
Files | <li>[issue905.diff](https://bugs.python.org/file46899/issue905.diff "Uploaded as text/plain at 2017-05-24.23:08:12 by @shubharamani")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-05-27.05:04:18.917>
created_at = <Date 2017-05-24.23:08:12.625>
labels = ['invalid', '3.7', 'library', 'performance']
title = 'Propagate zipfile.py pypy issue #905 patch to CPython 3.7'
updated_at = <Date 2017-05-27.05:11:26.085>
user = 'https://github.com/shubharamani'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-27.05:11:26.085>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-05-27.05:04:18.917>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-05-24.23:08:12.625>
creator = 'shubhar'
dependencies = []
files = ['46899']
hgrepos = []
issue_num = 30468
keywords = ['patch']
message_count = 10.0
messages = ['294413', '294466', '294487', '294488', '294495', '294496', '294503', '294505', '294571', '294579']
nosy_count = 5.0
nosy_names = ['twouters', 'alanmcintyre', 'serhiy.storchaka', 'alecsandru.patrascu', 'shubhar']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30468'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
PyPy had a longstanding issue :
ZipFile.extractall is very slow compared to CPython 2.6

https://bitbucket.org/pypy/pypy/issues/905/zipfileextractall-is-very-slow-compared-to

which has been fixed in the PyPy code base. The changes were entirely in zipfile.py (see the attached patch for PyPy)

The patch fixed a significant performance bottleneck in PyPy.

**Comment by serhiy-storchaka** [comment]
Could you provide a benchmarkin script that demonstrates a performance bottleneck?

The patch is against 2.7. Please provide a patch against the master branch.

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
Please assign this bug to me. I will submit a patch

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
serhiy sure I will attach proof of the performance bottle-neck on 2.7 and 3.7 before I submit a patch. Please assign this bug to me.

**Comment by serhiy-storchaka** [comment]
I assigned this issue to me as the maintainer of the zipfile module. This means that I undertake to examine the results of benchmarking, make the review of the proposed patch, and merge it if it improves the performance and doesn't have negative side effects. This shouldn't stop you from writing your patch.

Actually there was a reason why the code is written in that way. But maybe that reason no longer actual or there are stronger arguments for other ways. It is hard to say until I reproduce benchmarking results.

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
Serhiy yes what you said makes sense. Thanks for clarifying. Updates (benchmarking results) shortly...stay tuned.

**Comment by ae6878ec-d873-4297-8b64-d05d471e780d** [comment]
Serhiy, I am curious why did you have chosen to compute the CRC32 table everytime? It is standard (the generator polynomial does not change) and always will output the same values. And it is also less computational intensive to loading a precomputed array vs calculating it each time a zip archive is extracted.

**Comment by serhiy-storchaka** [comment]
I'm not the initial author of zipfile. That initial code for decrypting  was added in bpo-698833.

I like your idea about replacing the generating code with the precomputed table. Please open a separate issue for this.

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
Upon comparing the PyPy changes from attached diff to the latest cpython3 github, I don't find a need for improvement. Looks like cpython3 zipfile.py has the same changes and the read() method in class 
ZipExtFile(io.BufferedIOBase) is vastly improved compared to what pypy had. In fact it has been completely re-written.

The CPython 2.7 version of this bug was promptly closed as a duplicate:
http://bugs.python.org/issue30467

Perhaps the changes from CPython3 are not being backported to CPython2 ?

This bug can be closed because CPython3 has no issues.

**Comment by serhiy-storchaka** [comment]
The reason of using bytes concatenating rather than accumulating in the list, is that in most cases one of arguments is an empty bytes object (appending to the empty buffer or uncompressing a file with large compression block), and this case is optimized in CPython. In mos cases there is at most one nontrivial bytes concatenation per read operation, and using b''.join() is slower in that case.
