### ISSUE TITLE
Crash on OS X   EXC_BAD_ACCESS (SIGSEGV)

### ISSUE THREAD

**Issue by 926f5a78-c649-40ff-bc69-82d4f44ddc70** [python/cpython#74659]
BPO | [30474](https://bugs.python.org/issue30474)
--- | :---
Nosy | @ronaldoussoren, @ned-deily
Files | <li>[python-crash.txt](https://bugs.python.org/file46900/python-crash.txt "Uploaded as text/plain at 2017-05-25.13:12:43 by buchs"): OS X crash listing.</li><li>[Kafka-Poll.py](https://bugs.python.org/file46901/Kafka-Poll.py "Uploaded as text/plain at 2017-05-25.13:13:45 by buchs"): Code I was running</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.14:09:14.745>
created_at = <Date 2017-05-25.13:12:47.390>
labels = ['OS-mac', 'interpreter-core', 'type-crash']
title = 'Crash on OS X   EXC_BAD_ACCESS (SIGSEGV)'
updated_at = <Date 2017-05-25.14:09:14.743>
user = 'https://bugs.python.org/buchs'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-25.14:09:14.743>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-25.14:09:14.745>
closer = 'ned.deily'
components = ['Interpreter Core', 'macOS']
creation = <Date 2017-05-25.13:12:47.390>
creator = 'buchs'
dependencies = []
files = ['46900', '46901']
hgrepos = []
issue_num = 30474
keywords = []
message_count = 2.0
messages = ['294476', '294478']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'buchs']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30474'
versions = ['Python 2.7']
```

</p></details>

**Comment by 926f5a78-c649-40ff-bc69-82d4f44ddc70** [comment]
I have been getting periodic crashes from a long running python job on Mac OS X. There is nothing indicative of a crash from standard output or error. I'm not sure if the OS X crash records actually find your way back to you, but I am explicitly including mine here. I will try to attach my code after submission of this entry. I run this in the background on OS X, with stdout and stderr redirected to the same file.

**Comment by ned-deily** [comment]
According to the crash trace you supplied, the crash happened as a result of a call in librdkafka called from the cimpl extension module. As neither of these are part of the Python standard library, suggest you contact the project that supplies them or possibly Homebrew if you installed them through brew. Good luck!
