### ISSUE TITLE
"as" keyword in comprehensions

### ISSUE THREAD

**Issue by e7156765-cbc4-40de-a178-4c6a47cd8ca6** [python/cpython#74656]
BPO | [30471](https://bugs.python.org/issue30471)
--- | :---
Nosy | @brettcannon, @rhettinger

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-26.02:29:58.302>
created_at = <Date 2017-05-25.08:13:59.858>
labels = ['type-feature', '3.7']
title = '"as" keyword in comprehensions'
updated_at = <Date 2017-05-26.18:07:40.880>
user = 'https://bugs.python.org/nemeskeyd'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-26.18:07:40.880>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-26.02:29:58.302>
closer = 'rhettinger'
components = []
creation = <Date 2017-05-25.08:13:59.858>
creator = 'nemeskeyd'
dependencies = []
files = []
hgrepos = []
issue_num = 30471
keywords = []
message_count = 5.0
messages = ['294446', '294514', '294524', '294543', '294561']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'rhettinger', 'nemeskeyd']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30471'
versions = ['Python 3.7']
```

</p></details>

**Comment by e7156765-cbc4-40de-a178-4c6a47cd8ca6** [comment]
Currently, the "as" keyword in supported in import and with statements to bind an object to a name. I think it would be nice to have the same functionality in list/dict/etc. comprehensions as well.

Rationale: as I understand, comprehensions are preferred over map/filter + lambdas for creating modified versions of sequences (etc.) in Python. They are indeed useful for replacing map, filter, or map(filter); however, filter(map) is currently not supported. This is not an unusual use-case, as the two examples below show. It is also evident that they are very wordy with lambdas, and could be much clearer with comprehensions:

```py
    with open(file) as inf:
        lines = list(filter(lambda l: l, map(lambda line: line.strip(), inf)))
    items = dict(filter(lambda kv: kv[1] > 5,
                        map(lambda kv: kv[0], len(kv[1]), d.items())))
```


Currently the only way to do this with comprehensions are:

```py
    with open(file) as inf:
        lines = [l for l in (line.strip() for line in inf) if l]
    items = {k: v for k, v in ((k, len(v)) for k, v in d.items()) if v > 5)}
```


, or

```py
    items = {k: len(v) for k, v in d.items() if len(v) > 5}
```


The first option is as unwieldy and unreadable as the code with lambdas, while the second is ineffective as it calls len() twice (and of course here len() is just a placeholder for a potentially heavy operation).

I propose to allow the "as" keyword in comprehensions as well to bind the result of an operation in the output expression to a name that could be used in the optional predicate. In other words, provide a let-like functionality. Like so:

```py
    with open(file) as inf:
        lines = [line.strip() as l for line in inf if l]
    items = {(k, len(v) as lenv) for k, v in d.items() if lenv > 5}
```

**Comment by brettcannon** [comment]
The best place to propose this is on the python-ideas mailing list. My suspicion, though, is people will say it's not worth the new syntax as you can also undo your comprehensions as normal code and simply assign to a variable name directly.

**Comment by rhettinger** [comment]
As Brett says, the place to propose this is on python-ideas.  

I'm going to mark it here as closed/rejected because it will likely have to go through a lengthy process (possibly including a PEP) before having a chance of being accepted.  Please don't take this as discouragement.  It is just that the tracker is the wrong forum for the conversation to start.

On the plus side, the idea does seem like a nice convenience.  On the minus side, we really like that inconveniences serve as a nudge to not put too much inside a list comprehension and use a regular for-loop instead.  Also, Guido in the past has resisted similar suggestions for making assignments inside a while-loop conditional expression ("while (f.read(10) as block) != '': ...).

**Comment by e7156765-cbc4-40de-a178-4c6a47cd8ca6** [comment]
The truth is, I was thinking about going to the list, but according to PEP-42 (https://www.python.org/dev/peps/pep-0042/), this space was one of the places new features could be requested:

"""
Note

This PEP has been rejected as obsolete. All new feature requests should either go to the Python bug tracker [1] or the python-ideas [2] mailing list. The rest of this document is retained for historical purposes only.
"""

Going to the list, then.

**Comment by brettcannon** [comment]
I've created https://github.com/python/peps/pull/267 to clarify things a bit better in PEP-42, Dávid .
