### ISSUE TITLE
Propagate zipfile.py pypy issue #905 patch to CPython 2.7

### ISSUE THREAD

**Issue by 1510523b-2bdb-44fa-9092-cac883321cf4** [python/cpython#74652]
BPO | [30467](https://bugs.python.org/issue30467)
--- | :---
Nosy | @serhiy-storchaka, @shubharamani
Superseder | <li>bpo-30468: Propagate zipfile.py pypy issue #905 patch to CPython 3.7</li>
Files | <li>[issue905.diff](https://bugs.python.org/file46898/issue905.diff "Uploaded as text/plain at 2017-05-24.23:06:33 by @shubharamani"): patch which was applied to PyPy code base</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-25.10:48:42.908>
created_at = <Date 2017-05-24.23:06:33.470>
labels = ['performance']
title = 'Propagate zipfile.py pypy issue #905 patch to CPython 2.7'
updated_at = <Date 2017-05-25.15:21:44.401>
user = 'https://github.com/shubharamani'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-25.15:21:44.401>
actor = 'shubhar'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-25.10:48:42.908>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-05-24.23:06:33.470>
creator = 'shubhar'
dependencies = []
files = ['46898']
hgrepos = []
issue_num = 30467
keywords = ['patch']
message_count = 3.0
messages = ['294411', '294462', '294489']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'shubhar']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30468'
type = 'performance'
url = 'https://bugs.python.org/issue30467'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
PyPy had a longstanding issue :
ZipFile.extractall is very slow compared to CPython 2.6

https://bitbucket.org/pypy/pypy/issues/905/zipfileextractall-is-very-slow-compared-to

which has been fixed in the PyPy code base. The changes were entirely in zipfile.py (see the attached patch for PyPy)

The patch fixed a significant performance bottleneck in PyPy.

**Comment by serhiy-storchaka** [comment]
This is the same as bpo-30468. It isn't worth to open separate issues for different versions.

**Comment by 1510523b-2bdb-44fa-9092-cac883321cf4** [comment]
Please assign this bug to me.
