### ISSUE TITLE
Tutorial doesn't explain the use of classes

### ISSUE THREAD

**Issue by treyhunner** [python/cpython#74651]
BPO | [30466](https://bugs.python.org/issue30466)
--- | :---
Nosy | @rhettinger, @Mariatta, @treyhunner
PRs | <li>python/cpython#1804</li><li>python/cpython#2700</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-21.03:11:50.306>
created_at = <Date 2017-05-24.22:58:40.354>
labels = ['type-feature', '3.7', 'docs']
title = "Tutorial doesn't explain the use of classes"
updated_at = <Date 2017-07-21.03:11:50.305>
user = 'https://github.com/treyhunner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-21.03:11:50.305>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-21.03:11:50.306>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-05-24.22:58:40.354>
creator = 'trey'
dependencies = []
files = []
hgrepos = []
issue_num = 30466
keywords = []
message_count = 5.0
messages = ['294409', '294418', '298255', '298422', '298764']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'Mariatta', 'trey']
pr_nums = ['1804', '2700']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30466'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by treyhunner** [comment]
The tutorial page for classes starts with "Compared with other programming languages".

While object-oriented programming and classes are popular in many programming languages, not everyone learning about Python's classes is familiar with the concept.  I teach both new programmers and programmers who have heard of object-oriented programming but never created a class before.

I think the first paragraph on this page should be a brief explanation of the use of classes.  It may also be a good idea to have a "Why classes?" section explaining the uses of classes in more detail.

**Comment by rhettinger** [comment]
This particular PR seems fine.  I'll review it in more detail later.

In general, the tutorial is intended to be a structured overview of the language rather than a how-to-program lesson.  Concepts are usually linked to the glossary or external sources and some information is communicated indirectly by the examples.

**Comment by Mariatta** [comment]
New changeset 3fbd70018f835edd33250de2f79b7a7ef45f8359 by Mariatta (Trey Hunner) in branch 'master':
bpo-30466: Add brief explanation of classes to tutorial (GH-1804)
https://github.com/python/cpython/commit/3fbd70018f835edd33250de2f79b7a7ef45f8359

**Comment by rhettinger** [comment]
Apparently this was committed without my review.

**Comment by Mariatta** [comment]
New changeset ef4231adb7aa6b323c94e854ac3dc3bebc841115 by Mariatta (Trey Hunner) in branch '3.6':
bpo-30466: Add brief explanation of classes to tutorial (GH-1804) (GH-2700)
https://github.com/python/cpython/commit/ef4231adb7aa6b323c94e854ac3dc3bebc841115
