### ISSUE TITLE
defaultdict raises SystemError, __missing__ returned NULL in thread

### ISSUE THREAD

**Issue by 8aca85a3-0943-4f9a-81b2-3a5b465014cb** [python/cpython#74658]
BPO | [30473](https://bugs.python.org/issue30473)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @zhangyangyu, @mlouielu
Superseder | <li>bpo-30524: iter(classmethod, sentinel) broken for Argument Clinic class methods?</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = <Date 2017-06-20.20:34:13.205>
created_at = <Date 2017-05-25.12:21:49.767>
labels = ['interpreter-core', 'type-crash']
title = 'defaultdict raises SystemError, __missing__ returned NULL in thread'
updated_at = <Date 2017-07-01.22:25:16.704>
user = 'https://bugs.python.org/PeterParente'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-01.22:25:16.704>
actor = 'vstinner'
assignee = 'vstinner'
closed = True
closed_date = <Date 2017-06-20.20:34:13.205>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-05-25.12:21:49.767>
creator = 'Peter Parente'
dependencies = []
files = []
hgrepos = []
issue_num = 30473
keywords = []
message_count = 10.0
messages = ['294473', '294477', '294482', '294484', '294497', '294504', '296485', '296487', '297466', '297498']
nosy_count = 5.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'xiang.zhang', 'louielu', 'Peter Parente']
pr_nums = []
priority = 'critical'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30524'
type = 'crash'
url = 'https://bugs.python.org/issue30473'
versions = ['Python 3.6']
```

</p></details>

**Comment by 8aca85a3-0943-4f9a-81b2-3a5b465014cb** [comment]
Working on this PR (https://github.com/maxpoint/spylon/pull/49), I encountered an unexpected SystemError in Python 3.6 on my Mac and on Travis Linux. 

```pytb
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/Users/parente/miniconda3/envs/spylon-dev/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/parente/miniconda3/envs/spylon-dev/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/parente/projects/spylon/spylon/spark/progress.py", line 99, in _spark_progress_thread_worker
    td = datetime.datetime.now() - start_times[stage_id]
SystemError: <built-in method __missing__ of collections.defaultdict object at 0x106013098> returned NULL without setting an error
```


The exception only occurs in Python 3.6, not in Python 3.5 or 3.4: https://travis-ci.org/maxpoint/spylon/builds/235992988

The defaultdict is both created and used as a local variable in a threading.Thread run() function. It's never accessed outside that context (https://github.com/maxpoint/spylon/pull/49/commits/2bd47dc32f6129f5f6a4824be1eaed568351df11#diff-1ba10d1cd92a35a380442cb586e310e2R179)

I didn't see a related issue on the tracker here nor did I see anything in the 3.6 changelog about a behavior change.

**Comment by 8aca85a3-0943-4f9a-81b2-3a5b465014cb** [comment]
Much simpler example: https://gist.github.com/parente/a4772297459f05e43e12a5820051431b

Wrapping the datetime.datetime.now in a lambda avoids the issue.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Another way to reproduce this problem:

```pycon
>>> import datetime
>>> from collections import defaultdict as dd
>>> d = dd(datetime.datetime.now)
>>> d['foo']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in method __missing__ of collections.defaultdict object at 0x7f072e55b3b8> returned NULL without setting an error
```


This problem doesn't appear on Python 2.7, too.

**Comment by zhangyangyu** [comment]
Interestingly I could only reproduce the failure on 3.6 but not master.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
This bug is introduce at commit: 37e4ef7b17ce6e98ca725c0a53ae14c313c0e48c, then fixed at commit: 998c20962ca3e2e693c1635efe76c0144dde76fc

**Comment by serhiy-storchaka** [comment]
In 3.6 \_PyStack_UnpackDict() returns just args if there are no keyword arguments. But if args is NULL, the result of \_PyStack_UnpackDict() is treated as error.

Thank you for the reproducer Louie!

**Comment by vstinner** [comment]
This bug is a duplicate of bpo-30524.

Louie Lu: "This bug is introduce at commit: 37e4ef7b17ce6e98ca725c0a53ae14c313c0e48c, then fixed at commit: 998c20962ca3e2e693c1635efe76c0144dde76fc"

This is the fix for master. For Python 3.6, the fix is the commit f0ff849adc6b4a01f9d1f08d9ad0f1511ff84541. I added wrote unit tests for this bug, but also for many ways to calls functions: commit b7577456c430283f8b7ec4e914b701cb943cc69b.

> Much simpler example: https://gist.github.com/parente/a4772297459f05e43e12a5820051431b

I'm able to reproduce the bug in Python 3.6 before f0ff849adc6b4a01f9d1f08d9ad0f1511ff84541, and also confirm that this commit fixes the bug.

The good news is that Python 3.6.2rc1 is already available and contains my fix, and 3.6.2 final should be released soon.

**Comment by vstinner** [comment]
Oh, and thank you Peter Parente for the bug report, and for the script to reproduce the bug. It was usual to validate that the bug is now fixed.

**Comment by 8aca85a3-0943-4f9a-81b2-3a5b465014cb** [comment]
Glad to hear it. Cheers, Victor!

**Comment by vstinner** [comment]
> It was usual to validate that the bug is now fixed.

Crap, I wanted to write: useful, not usual!?
