### ISSUE TITLE
FormattedValue expressions have wrong lineno and col_offset information

### ISSUE THREAD

**Issue by ambv** [python/cpython#74650]
BPO | [30465](https://bugs.python.org/issue30465)
--- | :---
Nosy | @rhettinger, @vstinner, @ericvsmith, @ned-deily, @ambv, @serhiy-storchaka, @asottile
PRs | <li>python/cpython#1800</li><li>python/cpython#3409</li><li>python/cpython#6593</li><li>python/cpython#12920</li><li>python/cpython#10021</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ambv'
closed_at = <Date 2017-10-04.12:08:59.860>
created_at = <Date 2017-05-24.22:53:37.508>
labels = ['type-bug', '3.7']
title = 'FormattedValue expressions have wrong lineno and col_offset information'
updated_at = <Date 2020-04-01.23:22:36.159>
user = 'https://github.com/ambv'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-01.23:22:36.159>
actor = 'Anthony Sottile'
assignee = 'lukasz.langa'
closed = True
closed_date = <Date 2017-10-04.12:08:59.860>
closer = 'eric.smith'
components = []
creation = <Date 2017-05-24.22:53:37.508>
creator = 'lukasz.langa'
dependencies = []
files = []
hgrepos = []
issue_num = 30465
keywords = ['3.6regression']
message_count = 10.0
messages = ['294408', '294423', '294866', '301368', '301551', '301563', '303571', '303680', '315971', '340699']
nosy_count = 7.0
nosy_names = ['rhettinger', 'vstinner', 'eric.smith', 'ned.deily', 'lukasz.langa', 'serhiy.storchaka', 'Anthony Sottile']
pr_nums = ['1800', '3409', '6593', '12920', '10021']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30465'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ambv** [comment]
f-strings are computed in a separate compiler step. This makes their lineno and col_offset information wrong. This is problematic for flake8 which reports problems inside f-strings on the wrong line (typically the first one).

Attached patch fixes the issue.

**Comment by rhettinger** [comment]
Thanks for adding so many tests.

**Comment by serhiy-storchaka** [comment]
I have concerns about following cases.

* f-string containing multiple equivalent subexpressions:

f'{x} {x}'

or

f'''
{x}
{x}
'''

* f-string containing escaped newlines:

f'''\\
\\
{x}\\
\\
'''

The tests look slightly verbose and fragile to me. If once the parser will produce more efficient tree (see bpo-26415), the tests may fail. Needed more tests (for cases mentioned above), and adding them will add more verbose code. Maybe just find the child (or several children) of specific type and check lineno and col_offset only for it and few its children? If this will make the tests simpler. But if tests can't be made simpler, we should live with this.

**Comment by ericvsmith** [comment]
See also bpo-31140: I'm not sure if that case is covered by this issue.

**Comment by ericvsmith** [comment]
New changeset e7c566caf177afe43b57f0b2723e723d880368e8 by ericvsmith (Łukasz Langa) in branch 'master':
bpo-30465: Fix lineno and col_offset in fstring AST nodes (bpo-1800)
https://github.com/python/cpython/commit/e7c566caf177afe43b57f0b2723e723d880368e8

**Comment by ericvsmith** [comment]
New changeset aa1afc72c1ee1f090e6302198d9a0295f1ce1c05 by ericvsmith (Miss Islington (bot)) in branch '3.6':
bpo-30465: Fix lineno and col_offset in fstring AST nodes (GH-1800) (gh-3409)
https://github.com/python/cpython/commit/aa1afc72c1ee1f090e6302198d9a0295f1ce1c05

**Comment by ned-deily** [comment]
Is there more to do on this issue or can it be closed now?

**Comment by ericvsmith** [comment]
I think it's fixed. Closing.
