### ISSUE TITLE
urllib.parse.parse_qsl does not handle unicode data properly

### ISSUE THREAD

**Issue by maxking** [python/cpython#74668]
BPO | [30483](https://bugs.python.org/issue30483)
--- | :---
Nosy | @maxking, @csabella, @cyrkov

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-05-26.09:49:46.950>
labels = ['3.8', 'type-bug', '3.7']
title = 'urllib.parse.parse_qsl does not handle unicode data properly'
updated_at = <Date 2020-04-16.10:52:01.356>
user = 'https://github.com/maxking'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-16.10:52:01.356>
actor = 'cyrkov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-05-26.09:49:46.950>
creator = 'maxking'
dependencies = []
files = []
hgrepos = []
issue_num = 30483
keywords = []
message_count = 3.0
messages = ['294541', '318050', '366592']
nosy_count = 3.0
nosy_names = ['maxking', 'cheryl.sabella', 'cyrkov']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30483'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-93757
* gh-115771
* gh-116366
* gh-116367

**Comment by maxking** [comment]
After decoding percentage encoded `name` and `values` in the query string, it tries to `_coerce_result` or encode the result to ascii (which is the value of _implicit_encoding).

```
  File "/usr/lib/python3.6/urllib/parse.py", line 691, in parse_qsl
    value = _coerce_result(value)
  File "/usr/lib/python3.6/urllib/parse.py", line 95, in _encode_result
    return obj.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character '\xe9' in position 1: ordinal not in range(128)
```

As seen in the partial traceback above, it breaks things when trying to parse unicode encode query string values.

**Comment by frostburn** [comment]
Can confirm that this issue exists in Python 3.8.10 and that cyrkov's solution works. (I manually re-implemented `parse_qsl` as a quick fix.)

**Comment by michaelkedar** [comment]
I've also run into this issue on Python 3.11.5 in code that calls `parse_qsl` on a `flask.request.query_string` that contains %-encoded Unicode characters

**Comment by serhiy-storchaka** [comment]
Both decoding and encoding can fail or lose information. To avoid this we should either use the lossless encoding or error handler ('latin1' or 'surrogateescape') for both directions, or omit decoding and encoding at all. The latter is usually more efficient, and can even be simpler, like in this case. #115771 supports arbitrary raw and percent-encoded bytes.
