### ISSUE TITLE
Element.findall(path, dict) doesn't insert null namespace

### ISSUE THREAD

**Issue by 25dbb005-29e0-41c7-b4a1-36fd8b32beae** [python/cpython#74670]
BPO | [30485](https://bugs.python.org/issue30485)
--- | :---
Nosy | @rhettinger, @scoder, @zooba, @tirkarthi
PRs | <li>python/cpython#1823</li><li>python/cpython#12830</li><li>python/cpython#12860</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-03.06:44:21.911>
created_at = <Date 2017-05-26.12:57:08.696>
labels = ['expert-XML', '3.8', 'type-feature', 'library']
title = "Element.findall(path, dict) doesn't insert null namespace"
updated_at = <Date 2019-05-03.06:44:21.910>
user = 'https://bugs.python.org/benwainwright'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-03.06:44:21.910>
actor = 'scoder'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-03.06:44:21.911>
closer = 'scoder'
components = ['Library (Lib)', 'XML']
creation = <Date 2017-05-26.12:57:08.696>
creator = 'ben.wainwright'
dependencies = []
files = []
hgrepos = []
issue_num = 30485
keywords = ['patch']
message_count = 14.0
messages = ['294549', '294553', '294558', '294566', '340191', '340192', '340222', '340223', '340224', '340226', '340227', '340238', '340365', '340509']
nosy_count = 6.0
nosy_names = ['rhettinger', 'scoder', 'eli.bendersky', 'steve.dower', 'ben.wainwright', 'xtreak']
pr_nums = ['1823', '12830', '12860']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30485'
versions = ['Python 3.8']
```

</p></details>

**Comment by 25dbb005-29e0-41c7-b4a1-36fd8b32beae** [comment]
The findall method for ElementTree.Element handles namespace prefixes by tokenising the path and inserting the full namespace in braces based on entries in a dictionary.

Unfortunately, this does not work for a namespace without a prefix, so if you have files containing namespaces with and without prefixes, you still need to manually add the namespace url for the unprefixed path.

The function xpath_tokenizer checks to see if tokens contain a colon and only adds in the namespace url in that instance.

This could be changed to add the url if their is a colon, or if there is not, and the empty string key is present in the namespaces dictionary.

**Comment by rhettinger** [comment]
I agree that this is a recurring irritant.

**Comment by scoder** [comment]
Agreed that this should be added. I think the key should be None, though, not the empty string. I attached a quick patch for lxml's corresponding file. It's mostly the same for ET.

**Comment by scoder** [comment]
Patch replaced by pull request.
https://github.com/python/cpython/pull/1823
