### ISSUE TITLE
DOC: automatically create a venv and install Sphinx when running make

### ISSUE THREAD

**Issue by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [python/cpython#74672]
BPO | [30487](https://bugs.python.org/issue30487)
--- | :---
Nosy | @ned-deily, @cjrh, @zware, @willingc, @csabella
PRs | <li>python/cpython#1743</li><li>python/cpython#4346</li><li>python/cpython#4592</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-01-06.16:56:25.509>
created_at = <Date 2017-05-26.16:49:48.410>
labels = ['3.7', 'docs']
title = 'DOC: automatically create a venv and install Sphinx when running make'
updated_at = <Date 2019-01-06.16:56:25.508>
user = 'https://github.com/cjrh'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-06.16:56:25.508>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-01-06.16:56:25.509>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-05-26.16:49:48.410>
creator = 'cjrh'
dependencies = []
files = []
hgrepos = []
issue_num = 30487
keywords = ['patch']
message_count = 15.0
messages = ['294556', '305932', '305936', '305955', '307019', '307082', '307085', '307086', '307087', '307090', '307092', '307094', '307097', '333080', '333087']
nosy_count = 6.0
nosy_names = ['ned.deily', 'cjrh', 'docs@python', 'zach.ware', 'willingc', 'cheryl.sabella']
pr_nums = ['1743', '4346', '4592']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30487'
versions = ['Python 3.7']
```

</p></details>

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
Under guidance from zware during Pycon sprints, I've changed the Doc/ Makefile to automatically create a virtual environment and install Sphinx, all as part of the `make html` command.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
I messed up the PR through a failed rebase (trying to rebase my PR on top of upstream). I closed the PR as a result.  I have now fixed up my feature branch, but I have not resubmitted the PR.  Since the PR was left alone for many months, I'm ok with leaving things as is, and close this issue?

**Comment by zware** [comment]
You should be able to force-push your branch (`git push -f origin auto-venv-docbuilder`, or replace `origin` with the correct remote name) to fix the existing PR.

Sorry I haven't gotten back to this previously; time to do a review and remembering that the PR exists have not coincided.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
No worries. I've made a new [PR 4346](https://github.com/python/cpython/pull/4346). The old one was unsalvagable I'm afraid. Too many other people got added to the notifications list as a result of my incorrect rebase.  The new one is fine.

**Comment by zware** [comment]
New changeset d8d6b9122134f040cd5a4f15f40f6c9e3386db4d by Zachary Ware (Caleb Hattingh) in branch 'master':
bpo-30487: automatically create a venv and install Sphinx when running make (GH-4346)
https://github.com/python/cpython/commit/d8d6b9122134f040cd5a4f15f40f6c9e3386db4d

**Comment by ned-deily** [comment]
I don't think this is a good idea. It has already caused problems with one buildbot (bpo-32149) and will likely break other build scripts.  As the Doc Makefile stood previous to this commit, the Doc builds could take advantage of either a system-installed or user-supplied Sphinx and blurb without having to use the venv step.  Unless there are major objections, I am going to at least temporarily revert it.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
Hi Ned

It's still supposed to allow both. It sounds like it's not working properly. I'll have a look. FYI, I worked on this for Zach Ware who is the primary stakeholder for this feature. 

Rgds
Caleb

**Comment by ned-deily** [comment]
One problem is that the venv can't always be automatically built in all environments, as a recent Python 3 needs to be available in the right location.

**Comment by zware** [comment]
Go ahead with the revert, Ned.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
It looks like the check for an existing sphinx-build passes, and so no new venv is made, but this also means that blurb doesn't get installed.  I was concerned about this, but figured that at least the buildbots would create new envs each time, and this would only be an issue that a user with an odd configuration might have.

Sorry for the trouble.

The feature was simpler when it was only sphinx.  Now that blurb is there too, the logic for checking what is and isn't already present becomes a bit complex to reason through.

**Comment by ned-deily** [comment]
"Now that blurb is there too, the logic for checking what is and isn't already present becomes a bit complex to reason through."

Yeah, it is a bit complicated.  There's also the issue of trying to use a make recipe to ensure a "venv" exists and is up-to-date.  I don't necessarily want to abandon the idea (and sorry I wasn't around to review the proposed change initially) but let's at least hold off until 370a3 is out the door.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
Yep, sounds good.

**Comment by ned-deily** [comment]
New changeset 122fc136b34e11906466851e77bb6959946467ee by Ned Deily in branch 'master':
Revert "bpo-30487: automatically create a venv and install Sphinx when running make (GH-4346)" (bpo-4592)
https://github.com/python/cpython/commit/122fc136b34e11906466851e77bb6959946467ee
