### ISSUE TITLE
Allow setting cell value

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74671]
BPO | [30486](https://bugs.python.org/issue30486)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ncoghlan, @pitrou, @vstinner, @benjaminp, @serhiy-storchaka, @lisroach, @DimitrisJim
PRs | <li>python/cpython#1840</li><li>python/cpython#3668</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/lisroach'
closed_at = <Date 2017-06-08.11:45:01.119>
created_at = <Date 2017-05-26.16:17:01.425>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Allow setting cell value'
updated_at = <Date 2017-09-20.13:54:17.955>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-20.13:54:17.955>
actor = 'vstinner'
assignee = 'lisroach'
closed = True
closed_date = <Date 2017-06-08.11:45:01.119>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-05-26.16:17:01.425>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 30486
keywords = []
message_count = 10.0
messages = ['294554', '294573', '294577', '294583', '295057', '295058', '295416', '295417', '295476', '302617']
nosy_count = 9.0
nosy_names = ['rhettinger', 'terry.reedy', 'ncoghlan', 'pitrou', 'vstinner', 'benjamin.peterson', 'serhiy.storchaka', 'lisroach', 'Jim Fasarakis-Hilliard']
pr_nums = ['1840', '3668']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30486'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
There are use cases for setting a cell value.  One such use case is for (un)pickling recursive closures (see heroic workaround here: https://github.com/cloudpipe/cloudpickle/pull/90/files#diff-d2a3618afedd4e124c532151eedbae09R74 ).  Other use cases may include tinkering around and general education value.

There also doesn't seem to be, AFAICS, any counter-indication to being able to do so.  It's already possible in C using PyCell_Set(), which is a public API.  It just lacks an API in Python land.  For example `cell_contents` could become a read/write property...

**Comment by lisroach** [comment]
This idea makes sense to me. I'll see if I can put together the code for it.

**Comment by rhettinger** [comment]
+1  I don't see any reason this can't be writeable.

**Comment by ncoghlan** [comment]
+1 from me, as this also has potential value in testing use cases and in dealing with some of the consequences of the zero-arg super() design (i.e. it will make the injected \_\_class__ cell writable)

**Comment by terryjreedy** [comment]
A possible counter-indication would be if setting a cell could cause a crash, as opposed to a mysterious exception.  Since 3.x already allows writing any object to a cell from python code,
 
def outer():
    cell = None
    def inner(ob):
        nonlocal cell
        cell = ob  # rebinds \<hidden-cell\>.cell_contents
    return inner

```py
set_cell = outer()
print(set_cell.__closure__[0].cell_contents)  # None
set_cell('something')
print(set_cell.__closure__[0].cell_contents)  # 'something'
```


making "cell.cell_contents = 'something'" legal should not enable more crashes.

I think that "function.\_\_closure__[i].cell_contents = object" is perhaps not a good idea for production code, but I think it falls within the realm of 'consenting adults code' for the other uses suggested above.  How should it be documented?

**Comment by pitrou** [comment]
There's already a documentation change to the PR, you can leave your comments there.

**Comment by serhiy-storchaka** [comment]
New changeset 64505a1f6c0af4574e17e823b27ffe24eca44df5 by Serhiy Storchaka (Lisa Roach) in branch 'master':
bpo-30486: Allow setting cell value (bpo-1840)
https://github.com/python/cpython/commit/64505a1f6c0af4574e17e823b27ffe24eca44df5

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Lisa!

**Comment by lisroach** [comment]
Thank you for you guidance, Serhiy!

**Comment by vstinner** [comment]
New changeset 0ad05c32cc41d4c21bfd78b9ffead519ead475a2 by Victor Stinner in branch 'master':
bpo-30486: Make cell_set_contents() symbol private (bpo-3668)
https://github.com/python/cpython/commit/0ad05c32cc41d4c21bfd78b9ffead519ead475a2
