### ISSUE TITLE
python.exe crashed when open long path in windows 7

### ISSUE THREAD

**Issue by 9a6d145d-2b91-4a92-a94f-ab5d84c572e0** [python/cpython#74679]
BPO | [30494](https://bugs.python.org/issue30494)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @aokaywe
Files | <li>[python.png](https://bugs.python.org/file46907/python.png "Uploaded as image/png at 2017-05-28.00:54:57 by @aokaywe")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-28.01:41:13.826>
created_at = <Date 2017-05-28.00:54:59.076>
labels = ['OS-windows', 'type-crash']
title = 'python.exe crashed when open long path in windows 7'
updated_at = <Date 2017-05-28.01:41:13.812>
user = 'https://github.com/aokaywe'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-28.01:41:13.812>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-28.01:41:13.826>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2017-05-28.00:54:59.076>
creator = 'aokaywe'
dependencies = []
files = ['46907']
hgrepos = []
issue_num = 30494
keywords = []
message_count = 2.0
messages = ['294618', '294621']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'aokaywe']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30494'
versions = ['Python 2.7']
```

</p></details>

**Comment by 9a6d145d-2b91-4a92-a94f-ab5d84c572e0** [comment]
1. os.makedirs(ur'\\\\?\\c:\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹')
2. open(ur'\\\\?\\c:\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\测试文件夹\\t.txt','w')

you can see python was crashed.

**Comment by eryksun** [comment]
Your example works fine for me in Windows 10, and I see no reason why it would fail in Windows 7. The crash dialog in your screenshot shows that the problem occurred in a DLL named "winhadnt.dll". I suspect that this is malware injected into the python.exe process. Even if it's part of a legitimately installed program on your machine, this DLL has nothing to do with Python, so I'm closing this issue as 3rd party. 

By the way, Python 2 doesn't completely support raw unicode strings. '\\u' and '\\U' are still parsed as Unicode escape sequences. You can use forward slash for the path literal instead. Then normalize the path to use backslash at runtime.
