### ISSUE TITLE
'make clinic' does not work for out of tree builds / clinic.py is not in the devguide

### ISSUE THREAD

**Issue by gpshead** [python/cpython#74677]
BPO | [30492](https://bugs.python.org/issue30492)
--- | :---
Nosy | @nascheme, @gpshead, @vstinner, @larryhastings, @zware, @iritkatriel
PRs | <li>python/cpython#1836</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-17.23:03:31.981>
created_at = <Date 2017-05-27.18:28:09.959>
labels = ['build', '3.7', 'expert-argument-clinic', 'docs']
title = "'make clinic' does not work for out of tree builds / clinic.py is not in the devguide"
updated_at = <Date 2022-01-17.23:03:31.980>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-17.23:03:31.980>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-01-17.23:03:31.981>
closer = 'iritkatriel'
components = ['Documentation', 'Argument Clinic']
creation = <Date 2017-05-27.18:28:09.959>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 30492
keywords = []
message_count = 8.0
messages = ['294604', '294605', '294606', '294607', '294617', '308795', '308799', '410830']
nosy_count = 7.0
nosy_names = ['nascheme', 'gregory.p.smith', 'vstinner', 'larry', 'docs@python', 'zach.ware', 'iritkatriel']
pr_nums = ['1836']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30492'
versions = ['Python 3.7']
```

</p></details>

**Comment by gpshead** [comment]
I never do in-tree builds anymore because they make me feel dirty and leave build artifacts cluttering up my source tree.

make clinic does not work for out of tree builds.

To reproduce:

\~$ git clone ...cpython repo...
\~$ mkdir build && cd build
\~/build$ ../cpython/configure --with-pydebug
\~/build$ make clinic
./python -E ./Tools/clinic/clinic.py --make
./python: can't open file './Tools/clinic/clinic.py': [Errno 2] No such file or directory
Makefile:545: recipe for target 'clinic' failed
make: *** [clinic] Error 2

Per https://docs.python.org/3/howto/clinic.html it looks like I can just manually run clinic.py on the files I have modified.  Ideally the build system would take care of that for me.  But all I really want is a single command that keeps me up to date.

python3 [Tools/clinic/clinic.py](https://github.com/python/cpython/blob/main/Tools/clinic/clinic.py)  appears to be that command.  Even if it isn't fixed for out of tree builds, use of clinic needs to be in the [devguide](https://devguide.python.org).

**Comment by larryhastings** [comment]
I don't know how to fix it.  "make clinic" needs to be run in-tree anyway as it's modifying the C source code in place.

Can you suggest a patch?

**Comment by gpshead** [comment]
The Makefile knows where the source tree is, I think we can make it tell clinic.py.  Let me whip something up.

**Comment by gpshead** [comment]
My PR doesn't address the potential issue of needing to have done a make all before doing a make clinic.  I'll leave that for something else, there could be bootstrapping issues in that situation depending on what the developer is doing.

In that less common case, running clinic.py oneself under a stable python3 interpreter is probably advisable.

The [devguide](https://devguide.python.org) docs still need to mention 'make clinic' and point to the argument clinic docs in some section talking about the Modules/ tree.

**Comment by gpshead** [comment]
New changeset 178418ad6791b6ef5ba610ed93fab75fc1567ad2 by Gregory P. Smith in branch 'master':
bpo-30492: Allow make clinic to work out of tree. (bpo-1836)
https://github.com/python/cpython/commit/178418ad6791b6ef5ba610ed93fab75fc1567ad2
