### ISSUE TITLE
Incomplete traceback with `exec` on SyntaxError

### ISSUE THREAD

**Issue by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [python/cpython#74681]
BPO | [30496](https://bugs.python.org/issue30496)
--- | :---
Nosy | @brettcannon, @stefanseefeld, @ncoghlan, @benjaminp, @serhiy-storchaka, @1st1
Files | <li>[pyerror.tgz](https://bugs.python.org/file46908/pyerror.tgz "Uploaded as application/x-compressed-tar at 2017-05-28.13:28:54 by @stefanseefeld")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-29.18:46:42.063>
created_at = <Date 2017-05-28.13:28:54.786>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'Incomplete traceback with `exec` on SyntaxError'
updated_at = <Date 2017-05-29.18:46:42.062>
user = 'https://github.com/stefanseefeld'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-29.18:46:42.062>
actor = 'stefan'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-29.18:46:42.063>
closer = 'stefan'
components = ['Interpreter Core']
creation = <Date 2017-05-28.13:28:54.786>
creator = 'stefan'
dependencies = []
files = ['46908']
hgrepos = []
issue_num = 30496
keywords = []
message_count = 5.0
messages = ['294645', '294691', '294699', '294707', '294709']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'stefan', 'ncoghlan', 'benjamin.peterson', 'serhiy.storchaka', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30496'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
The following code is supposed to catch and report errors encountered during the execution of a (python) script:

```
import traceback
import sys

try:
    env = {}
    with open('script') as f:
        exec(f.read(), env)
except:
    type_, value_, tb = sys.exc_info()
    print (traceback.print_tb(tb))
```
However, depending on the nature of the error, the traceback may contain the location of the error *within* the executed `script` file, or it may only report the above `exec(f.read(), env)` line.

The attached tarball contains both the above as well as a 'script' that exhibit the problem.

Is this a bug or am I missing something ? Are there ways to work around this, i.e. determine the correct (inner) location of the error ?

(I'm observing this with both Python 2.7 and Python 3.5)

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
Some further experiements:

Replacing the `exec(f.read(), env)` line by
```
code = compile(f.read(), 'script', 'exec')
exec(code, env)
```
exhibits the same behaviour. If I remove the `try...except`, the correct
(full) traceback is printed out. So it looks like the issue is with the traceback propagation through exception handlers when the error happens during parsing.

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
Answering my own question:

It appears I can get the location of a syntax error by inspecting the
raised `SyntaxError`, which solves my specific use-case. 
The bug remains, though: The traceback is incomplete if it stems from a syntax error.

**Comment by serhiy-storchaka** [comment]
The traceback contain the location of the code that raised an exception when executed. In case of NameError this is a line in your script "x=u". In case of SyntaxError the code that failed is not in your script (it still is not executed), but in a compiler implicitly called by exec(). The line with exec() is correctly reported.

The behavior looks correct to me.

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
OK, fair enough, that makes sense. As I said, in my last message, I was mainly simply trying to figure out the exact location of the error in the executed script, which I got from inspecting the SyntaxError.
So if all of this is expected behaviour, I think we can close this issue.

Many thanks for following up.
