### ISSUE TITLE
CAN Socket support for NetBSD

### ISSUE THREAD

**Issue by 990e9fa1-52f3-43b0-a5ea-6804358c2ff1** [python/cpython#74697]
BPO | [30512](https://bugs.python.org/issue30512)
--- | :---
Nosy | @0-wiz-0, @serhiy-storchaka
PRs | <li>python/cpython#30066</li>
Dependencies | <li>bpo-31927: Fix compiling the socket module on NetBSD 8 and other issues</li>
Files | <li>[can.diff](https://bugs.python.org/file46915/can.diff "Uploaded as text/plain at 2017-05-30.14:50:41 by @0-wiz-0"): Patch adding NetBSD CAN sockets support.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2022-01-21.07:44:59.409>
created_at = <Date 2017-05-30.14:50:42.966>
labels = ['extension-modules', 'type-feature', '3.11']
title = 'CAN Socket support for NetBSD'
updated_at = <Date 2022-01-21.07:44:59.408>
user = 'https://github.com/0-wiz-0'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-21.07:44:59.408>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2022-01-21.07:44:59.409>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-05-30.14:50:42.966>
creator = 'wiz'
dependencies = ['31927']
files = ['46915']
hgrepos = []
issue_num = 30512
keywords = ['patch']
message_count = 3.0
messages = ['294764', '305441', '411090']
nosy_count = 2.0
nosy_names = ['wiz', 'serhiy.storchaka']
pr_nums = ['30066']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30512'
versions = ['Python 3.11']
```

</p></details>

**Comment by 990e9fa1-52f3-43b0-a5ea-6804358c2ff1** [comment]
NetBSD recently got support for CAN. The existing Linux support for CAN partially detects this, but then fails to build. The attached patch against 3.6.1 (from Manuel Bouyer \<bouyer@NetBSD.org\>) fixes this problem and adds proper NetBSD support for CAN sockets.

**Comment by serhiy-storchaka** [comment]
The compilation will be fixed in bpo-31927.

I have wrote similar patch for adding CAN Socket support on NetBSD. I'll combine the patches later.

This is a new feature and can be added only in 3.7.
