### ISSUE TITLE
Allow replacing a logging.StreamHandler's stream

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74707]
BPO | [30522](https://bugs.python.org/issue30522)
--- | :---
Nosy | @vsajip, @pitrou, @vstinner
PRs | <li>python/cpython#2921</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-30.09:44:33.389>
created_at = <Date 2017-05-31.08:09:10.627>
labels = ['type-feature', '3.7']
title = "Allow replacing a logging.StreamHandler's stream"
updated_at = <Date 2017-07-30.09:44:33.388>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-30.09:44:33.388>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-30.09:44:33.389>
closer = 'vinay.sajip'
components = []
creation = <Date 2017-05-31.08:09:10.627>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 30522
keywords = []
message_count = 6.0
messages = ['294820', '294821', '294822', '297957', '297958', '299495']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'pitrou', 'vstinner']
pr_nums = ['2921']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30522'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
Right now it is probably possible using something like:

```py
    handler.acquire()
    try:
        handler.flush()
        handler.stream = new_stream
    finally:
        handler.release()
```


but it would be nice to have an officially-supported method to do that.

Context: if I reconfigure sys.stderr, I'd like to update all handlers that have a reference to the old sys.stderr.

**Comment by vstinner** [comment]
Which StreamHandler class? Is this issue related to logging? If yes, please mention it in the title ;-)

**Comment by pitrou** [comment]
Oh, yes, sorry.  This is about logging.

**Comment by vsajip** [comment]
How about this as an API?

```py
    def setStream(self, stream):
        """
        Sets the StreamHandler's stream to the specified value,
        if it is different.
```


        Returns the old stream, if the stream was changed, or None
        if it wasn't.
        """

**Comment by pitrou** [comment]
Vinay, yes, that sounds fine to me.

**Comment by vsajip** [comment]
New changeset 2543f50033208c1a8df04999082b11aa09e82a04 by Vinay Sajip in branch 'master':
bpo-30522: Implemented a method to allow setting a logging.StreamHander's stream. (GH-2921)
https://github.com/python/cpython/commit/2543f50033208c1a8df04999082b11aa09e82a04
