### ISSUE TITLE
Enum does not recognize enum.auto as unique values

### ISSUE THREAD

**Issue by bef3b989-2e47-4e9c-91d3-504408b50b75** [python/cpython#74702]
BPO | [30517](https://bugs.python.org/issue30517)
--- | :---
Nosy | @ethanfurman, @pkch, @MojoVampire

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2017-05-31.10:02:53.059>
created_at = <Date 2017-05-31.02:08:08.797>
labels = ['invalid', 'type-bug', 'library']
title = 'Enum does not recognize enum.auto as unique values'
updated_at = <Date 2017-05-31.10:02:53.058>
user = 'https://github.com/pkch'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-31.10:02:53.058>
actor = 'max'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2017-05-31.10:02:53.059>
closer = 'max'
components = ['Library (Lib)']
creation = <Date 2017-05-31.02:08:08.797>
creator = 'max'
dependencies = []
files = []
hgrepos = []
issue_num = 30517
keywords = []
message_count = 3.0
messages = ['294804', '294813', '294831']
nosy_count = 3.0
nosy_names = ['ethan.furman', 'max', 'josh.r']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30517'
versions = ['Python 3.6']
```

</p></details>

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
This probably shouldn't happen:

```py
    import enum

    class E(enum.Enum):
      A = enum.auto
      B = enum.auto

    x = E.B.value
    print(x) # <class 'enum.auto'>
    print(E(x))  # E.A
```


The first print() is kinda ok, I don't really care about which value was used by the implementation. But the second print() seems surprising.

By the same token, this probably shouldn't raise an exception (it does now):

```py
    import enum

    @enum.unique
    class E(enum.Enum):
      A = enum.auto
      B = enum.auto
      C = object()
```


and `dir(E)` shouldn't skip `B` in its output (it does now).

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
You didn't instantiate auto; read the docs ( https://docs.python.org/3/library/enum.html#using-automatic-values ): auto is a class, you instantiate it to make instances for use. If you omit the parens, it's just a plain class, not a special value for automatic value assignment.

You want:

```py
    class E(enum.Enum):
        A = enum.auto()
        B = enum.auto()
```

**Comment by bef3b989-2e47-4e9c-91d3-504408b50b75** [comment]
Ah sorry about that ... Yes, everything works fine when used properly.
