### ISSUE TITLE
unittest: assertAlmostEqual rounding error

### ISSUE THREAD

**Issue by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [python/cpython#74700]
BPO | [30515](https://bugs.python.org/issue30515)
--- | :---
Nosy | @mdickinson, @sam-s

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-30.19:53:25.865>
created_at = <Date 2017-05-30.17:26:28.253>
labels = ['invalid', 'library']
title = 'unittest: assertAlmostEqual rounding error'
updated_at = <Date 2017-05-30.19:53:25.864>
user = 'https://github.com/sam-s'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-30.19:53:25.864>
actor = 'sam-s'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-30.19:53:25.865>
closer = 'sam-s'
components = ['Library (Lib)']
creation = <Date 2017-05-30.17:26:28.253>
creator = 'sam-s'
dependencies = []
files = []
hgrepos = []
issue_num = 30515
keywords = []
message_count = 3.0
messages = ['294772', '294778', '294779']
nosy_count = 2.0
nosy_names = ['mark.dickinson', 'sam-s']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30515'
versions = ['Python 2.7']
```

</p></details>

**Comment by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [comment]
I get this `unittest` failure:

```
Traceback (most recent call last):
  File "zzz.py", line 348, in test_opposite
    self.assertAlmostEqual(a, b, places=2)
AssertionError: 1.1036640046288428 != 1.0986122886681098 within 2 places
```

This seems incorrect: 1.1036640046288428 rounded off to 2 places is 1.10 and so is 1.0986122886681098.

E.g., in Lisp:

```
> (round 1.1036640046288428d0 0.01)
110 ;
0.0036640292157588336d0
> (round 1.0986122886681098d0 0.01)
110 ;
-0.001387686744974238d0
```

**Comment by mdickinson** [comment]
The `assertAlmostEqual` comparison looks at the difference between the two values, and rounds that to 2 decimal places. In this case, the difference is approximately 0.00505, which rounded to 2 decimal places is 0.01.

If instead each of the two values were rounded and the rounded values compared, you'd end up in a situation where (for example) `self.assertEqual(1.144999999, 1.145000001, places=2)` failed, despite the values being only 2 billionths apart.

**Comment by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [comment]
you are right, sorry.
