### ISSUE TITLE
Import type aliases from another module

### ISSUE THREAD

**Issue by d51975e9-b1f0-47f0-be62-f9ef72b04806** [python/cpython#74703]
BPO | [30518](https://bugs.python.org/issue30518)
--- | :---
Nosy | @ilevkivskyi, @JelleZijlstra, @Paragape

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-03.16:14:09.541>
created_at = <Date 2017-05-31.02:54:11.425>
labels = ['type-feature', 'invalid', 'build']
title = 'Import type aliases from another module'
updated_at = <Date 2017-06-03.16:14:09.539>
user = 'https://github.com/Paragape'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-03.16:14:09.539>
actor = 'Paragape'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-03.16:14:09.541>
closer = 'Paragape'
components = ['Build']
creation = <Date 2017-05-31.02:54:11.425>
creator = 'Paragape'
dependencies = []
files = []
hgrepos = []
issue_num = 30518
keywords = []
message_count = 5.0
messages = ['294807', '294809', '294811', '295046', '295085']
nosy_count = 3.0
nosy_names = ['levkivskyi', 'JelleZijlstra', 'Paragape']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30518'
versions = ['Python 3.5']
```

</p></details>

**Comment by d51975e9-b1f0-47f0-be62-f9ef72b04806** [comment]
I have a 'base' module where I define some type aliases, such as:

```py
    from typing import List, Tuple
    Block = [int, Tuple[int]]
    Blocks = List[Block]
    Tags = List[str]
```


I would like to import these aliases into other modules so that the 'base' module provides the definitive alias.

Currently, if I attempt to import the type aliases using:

```py
    from base_module import Tags, Blocks
```


Pycharm shows no error, but when I attempt to execute the code I get the error:

    ImportError: cannot import name 'Tags'

I see that there has been some discussion related to this in 2015, but I can't find any documentation saying that something like this has been implemented.

**Comment by d51975e9-b1f0-47f0-be62-f9ef72b04806** [comment]
I just found out that the problem is even worse.  While PyCharm accepts the syntax below, I still can't compile 'Blocks'.

**Comment by JelleZijlstra** [comment]
This is likely an issue with the setup of your project, not with type aliases. You haven't given enough information to tell me what the real problem is.

I'm not sure what you mean by "I still can't compile 'Blocks'".

**Comment by ilevkivskyi** [comment]
>     Block = [int, Tuple[int]]
>     Blocks = List[Block]

These are both invalid type aliases (I have no idea why PyCharm does not flag them, you could report this at PyCharm issue tracker). I am not sure what exactly you want. If you want a list of either integers or tuples of integers, then you should write for example:

```py
Block = Union[int, Tuple[int, ...]]
Blocks = List[Block]
```


Concerning import, this is definitely not a problem with aliases. What I have noticed is that you write "I have a 'base' module ..." and then "from base_module import ...", if you have a module named base.py, then you should write:

```py
from base import Blocks, Tags
```


Or maybe you just have an import cycle...

**Comment by d51975e9-b1f0-47f0-be62-f9ef72b04806** [comment]
Thanks for your response!  Yes, the problem was a circular definition.  I still have much to learn about Python...
