### ISSUE TITLE
Incorrect error messages for invalid whitespaces in f-string subexpressions

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74714]
BPO | [30529](https://bugs.python.org/issue30529)
--- | :---
Nosy | @ericvsmith, @serhiy-storchaka
PRs | <li>python/cpython#1888</li><li>python/cpython#2013</li><li>python/cpython#2232</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-08.21:39:16.397>
created_at = <Date 2017-05-31.20:24:52.747>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Incorrect error messages for invalid whitespaces in f-string subexpressions'
updated_at = <Date 2017-06-16.01:41:02.691>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.01:41:02.691>
actor = 'eric.smith'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-08.21:39:16.397>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-05-31.20:24:52.747>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30529
keywords = []
message_count = 7.0
messages = ['294869', '294870', '295244', '295420', '295463', '295468', '295469']
nosy_count = 2.0
nosy_names = ['eric.smith', 'serhiy.storchaka']
pr_nums = ['1888', '2013', '2232']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30529'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Python parser supports only ' ', '\\t', '\\x0c' and '\\r' as whitespaces. The parser of f-strings raises incorrect error messages for subexpressions consistent only from whitespaces, if they contain whitespaces out this set.

```pycon
>>> eval("\xa0")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
     
    ^
SyntaxError: invalid character in identifier
>>> eval("f'''{\xa0}'''")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
SyntaxError: f-string: empty expression not allowed
```

**Comment by serhiy-storchaka** [comment]
[PR 1888](https://github.com/python/cpython/pull/1888) makes error messages for f-string subexpressions consistent with error messages for expressions out of f-strings, simplifies and speeds up the parsing code.

**Comment by serhiy-storchaka** [comment]
Could you please look at the patch Eric?

**Comment by ericvsmith** [comment]
Sorry, I've been busy. I'll get to this soon, though.

**Comment by serhiy-storchaka** [comment]
New changeset 2e9cd5825c5ccdbb6f65a57c0c7941078e003c14 by Serhiy Storchaka in branch 'master':
bpo-30529: Fix errors for invalid whitespaces in f-string subexpressions. (bpo-1888)
https://github.com/python/cpython/commit/2e9cd5825c5ccdbb6f65a57c0c7941078e003c14

**Comment by serhiy-storchaka** [comment]
New changeset 570b1c971c31cd08dbf060f4e21636c40aa47786 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30529: Fix errors for invalid whitespaces in f-string subexpressions. (GH-1888) (bpo-2013)
https://github.com/python/cpython/commit/570b1c971c31cd08dbf060f4e21636c40aa47786

**Comment by serhiy-storchaka** [comment]
Thank you for your review Eric.
