### ISSUE TITLE
email.policy.SMTP.fold() mangles long headers

### ISSUE THREAD

**Issue by 86921ab5-3d12-4876-8e4c-eedda72c7e38** [python/cpython#74717]
BPO | [30532](https://bugs.python.org/issue30532)
--- | :---
Nosy | @warsaw, @bitdancer, @jhillacre
PRs | <li>python/cpython#1892</li><li>python/cpython#2591</li><li>python/cpython#2592</li>
Files | <li>[test_long_mime_headers.py](https://bugs.python.org/file46917/test_long_mime_headers.py "Uploaded as text/plain at 2017-05-31.22:08:52 by chris@arrai.com"): Test case for folding long email headers.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-06.21:30:10.140>
created_at = <Date 2017-05-31.22:08:53.091>
labels = ['type-bug']
title = 'email.policy.SMTP.fold() mangles long headers'
updated_at = <Date 2017-07-06.21:30:10.139>
user = 'https://bugs.python.org/chrisarraicom'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-06.21:30:10.139>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-06.21:30:10.140>
closer = 'r.david.murray'
components = []
creation = <Date 2017-05-31.22:08:53.091>
creator = 'chris@arrai.com'
dependencies = []
files = ['46917']
hgrepos = []
issue_num = 30532
keywords = []
message_count = 10.0
messages = ['294875', '294878', '295209', '295210', '296584', '296732', '296948', '297843', '297844', '297845']
nosy_count = 4.0
nosy_names = ['barry', 'r.david.murray', 'jhillacre', 'chris@arrai.com']
pr_nums = ['1892', '2591', '2592']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30532'
versions = ['Python 3.5']
```

</p></details>

**Comment by 86921ab5-3d12-4876-8e4c-eedda72c7e38** [comment]
When email.policy.SMTP.fold() attempts to wrap a line in which a chunk that does not contain a space is longer than the maximum line length, two things go wrong:
 - The second line does not begin with a space, creating an invalid header.
 - The space before the long chunk is stripped, causing the line break to occur in an invalid place.

In the attached test case, email.policy.SMTP.fold() is called on a line of the style:
Content-Disposition: attachment; filename="\<filename\>"

\<filename\> does not contain any spaces and increases in length with each pass. Everything works correctly when 'filename="\<filename\>"' fits onto one line. However, once it is longer than the maximum line length, the following happens:
 - the space after the semicolon is dropped
 - the line break often splits up the 'filename' keyword
 - the second line loses the initial whitespace

**Comment by 22884b00-60c4-4a65-aa27-c8175ab1d641** [comment]
I added a pull request that causes Chris's test to pass. I can confirm that the Chris's was not pass for me on master branch.

**Comment by 22884b00-60c4-4a65-aa27-c8175ab1d641** [comment]
Rebased the github PR on latest master to get the windows build passing CI.

Is there anything I need to do to keep the PR moving?

**Comment by bitdancer** [comment]
Ping the issue again next week if I don't get to it this weekend.

**Comment by 22884b00-60c4-4a65-aa27-c8175ab1d641** [comment]
> Ping the issue again next week if I don't get to it this weekend.

I am a week late, but here is a ping.

**Comment by bitdancer** [comment]
Just as well.  I had no time last weekend.  I should have time this Sunday, though.

**Comment by bitdancer** [comment]
New changeset b350c22ebcbb891412e0b334afc9f0db19534e06 by R. David Murray (Joel Hillacre) in branch 'master':
bpo-30532: Fix whitespace folding in certain cases
https://github.com/python/cpython/commit/b350c22ebcbb891412e0b334afc9f0db19534e06

**Comment by bitdancer** [comment]
New changeset c60d2f5e8609b040ab58c498fde23928fe9dbef5 by R. David Murray (Joel Hillacre) in branch '3.6':
bpo-30532: Fix whitespace folding in certain cases (bpo-2591)
https://github.com/python/cpython/commit/c60d2f5e8609b040ab58c498fde23928fe9dbef5

**Comment by bitdancer** [comment]
New changeset 3bbdf990a2c1b0b303b950058e3177a1bd5f697a by R. David Murray (Joel Hillacre) in branch '3.5':
bpo-30532: Fix whitespace folding in certain cases (bpo-2592)
https://github.com/python/cpython/commit/3bbdf990a2c1b0b303b950058e3177a1bd5f697a

**Comment by bitdancer** [comment]
Thanks, Joel!
