### ISSUE TITLE
missing feature in inspect module: getmembers_static

### ISSUE THREAD

**Issue by carljm** [python/cpython#74718]
BPO | [30533](https://bugs.python.org/issue30533)
--- | :---
Nosy | @carljm, @DinoV, @kernc, @lisroach, @corona10, @hongweipeng, @tirkarthi, @isidentical, @itamaro
PRs | <li>python/cpython#20911</li><li>python/cpython#29874</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-12-01.19:24:09.933>
created_at = <Date 2017-05-31.22:52:48.216>
labels = ['type-feature', 'library', '3.11']
title = 'missing feature in inspect module: getmembers_static'
updated_at = <Date 2021-12-01.19:24:09.932>
user = 'https://github.com/carljm'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-01.19:24:09.932>
actor = 'dino.viehland'
assignee = 'none'
closed = True
closed_date = <Date 2021-12-01.19:24:09.933>
closer = 'dino.viehland'
components = ['Library (Lib)']
creation = <Date 2017-05-31.22:52:48.216>
creator = 'carljm'
dependencies = []
files = []
hgrepos = []
issue_num = 30533
keywords = ['patch']
message_count = 7.0
messages = ['294876', '295029', '329255', '406072', '407393', '407423', '407483']
nosy_count = 9.0
nosy_names = ['carljm', 'dino.viehland', 'kernc', 'lisroach', 'corona10', 'hongweipeng', 'xtreak', 'BTaskaya', 'itamaro']
pr_nums = ['20911', '29874']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30533'
versions = ['Python 3.11']
```

</p></details>

**Comment by carljm** [comment]
The inspect module contains a getattr_static() function, for accessing an arbitrary attribute on a Python object without risking descriptor or \_\_getattr__ code execution. This is useful for introspection tools that don't want to trigger any side effects.

The inspect module also contains a getmembers() function, which returns a mapping of names to values for all the object's members. This function could also be very useful to introspection tools, except that internally it uses normal getattr, thus reintroduces the risk of arbitrary code execution.

It would be useful to have an equivalent to getmembers() that is descriptor-safe. This could be done either by introducing a new getmembers_static(), or possibly by adding a `getattr` optional keyword argument to getmembers, that would take a getattr-equivalent callable to use in fetching attributes from the object. (The latter option might render some internal assumptions of getmembers() incorrect, needs experimentation.)

**Comment by lisroach** [comment]
+1 to a new getmembers_static(), I don't see why this couldn't be implemented.
