### ISSUE TITLE
error message for incorrect call degraded in 3.7

### ISSUE THREAD

**Issue by scoder** [python/cpython#74719]
BPO | [30534](https://bugs.python.org/issue30534)
--- | :---
Nosy | @brettcannon, @rhettinger, @scoder, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#1901</li><li>python/cpython#1996</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-06-06.15:56:44.818>
created_at = <Date 2017-06-01.06:32:30.571>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'error message for incorrect call degraded in 3.7'
updated_at = <Date 2017-06-08.11:41:21.286>
user = 'https://github.com/scoder'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-08.11:41:21.286>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-06-06.15:56:44.818>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-06-01.06:32:30.571>
creator = 'scoder'
dependencies = []
files = []
hgrepos = []
issue_num = 30534
keywords = []
message_count = 14.0
messages = ['294906', '294912', '294913', '294914', '294915', '294916', '294917', '294920', '295050', '295079', '295096', '295097', '295269', '295414']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'rhettinger', 'scoder', 'vstinner', 'serhiy.storchaka']
pr_nums = ['1901', '1996']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30534'
versions = ['Python 3.7']
```

</p></details>

**Comment by scoder** [comment]
I'm seeing doctest failures in Cython's test suite with Py3.7 due to the change of an error message:

```pytb
Failed example:
    func1(arg=None)
Expected:
    Traceback (most recent call last):
    ...
    TypeError: func1() takes no keyword arguments
Got:
    Traceback (most recent call last):
      File "/opt/python/3.7-dev/lib/python3.7/doctest.py", line 1329, in __run
        compileflags, 1), test.globs)
      File "<doctest always_allow_keywords_T295.func1[2]>", line 1, in <module>
        func1(arg=None)
    TypeError: func1() takes exactly one argument (0 given)
```


I'd normally just adapt the doctest and move on, but this seems like the error message is worse than before, so I thought I'd bring it up here. func1() is implemented as a METH_O C function. Suggesting that it does not accept keyword arguments seems better than saying that it expects "exactly one argument" instead of the exactly one argument that was passed.

**Comment by vstinner** [comment]
Example with a builtin function, abs(), which uses METH_O.

Before:

```pycon
haypo@selma$ python3
Python 3.5.3 (default, Apr 24 2017, 13:32:13) 
>>> abs(x=5)
TypeError: abs() takes no keyword arguments
```


After:

```pycon
haypo@selma$ ./python
Python 3.7.0a0 (heads/master:85aba23, May 31 2017, 10:29:03) 
>>> abs(x=5)
TypeError: abs() takes exactly one argument (0 given)
```


In Python 3.5, PyCFunction_Call() starts by checking keyword arguments:

```c
    if (flags == (METH_VARARGS | METH_KEYWORDS)) {
        ...
    }
    else {
        if (kwds != NULL && PyDict_Size(kwds) != 0) {
            PyErr_Format(PyExc_TypeError, "%.200s() takes no keyword arguments",
                         f->m_ml->ml_name);
            return NULL;
        }

        switch (flags) {
        case METH_NOARGS:
            size = PyTuple_GET_SIZE(args);
            if (size != 0) {
                PyErr_Format(PyExc_TypeError,
                    "%.200s() takes no arguments (%zd given)",
                    f->m_ml->ml_name, size);
                return NULL;
            }
            ...
```



In Python 3.7, \_PyMethodDef_RawFastCallKeywords() first check positional arguments:

```c
    switch (flags)
    {
    case METH_NOARGS:
        if (nargs != 0) {
            PyErr_Format(PyExc_TypeError,
                "%.200s() takes no arguments (%zd given)",
                method->ml_name, nargs);
            goto exit;
        }

        if (nkwargs) {
            goto no_keyword_error;
        }
```


        ...

We can easily exchange the two checks, but IMHO we need an unit test (at least decorated by @cpython_only) to avoid regressions in the future.

**Comment by vstinner** [comment]
Ah, Python 3.6 is not affected:

```pycon
haypo@selma$ ./python
Python 3.6.1+ (heads/unpack_dict:ba4fb35, May 31 2017, 16:31:51) 
>>> abs(x=5)
TypeError: abs() takes no keyword arguments
```

**Comment by vstinner** [comment]
I introduced the regression with the commit 7fc252adfbedece75f2330bcfdadbf84dee7836f: 

"Optimize \_PyCFunction_FastCallKeywords(): Issue bpo-29259: Write fast path in \_PyCFunction_FastCallKeywords() for METH_FASTCALL, (...) Cleanup also \_PyCFunction_FastCallDict(): (...) Move code to raise the "no keyword argument" exception into a new no_keyword_error label."

**Comment by vstinner** [comment]
See also "[Python-ideas] Positional-only parameters" discussion of last March:
https://mail.python.org/pipermail/python-ideas/2017-March/044956.html

Brett Cannon: "It seems all the core devs who have commented on this are in the positive (Victor, Yury, Ethan, Yury, Guido, Terry, and Steven; MAL didn't explicitly vote). So to me that suggests there's enough support to warrant writing a PEP. (...)"

(No, I didn't write such PEP yet :-p)

Maybe we can also enhance the error message to explain that the function accepts exactly one positional-only argument?

**Comment by serhiy-storchaka** [comment]
Note that some error messages are "takes no keyword arguments", but others are "does not take keyword arguments" or "doesn't take keyword arguments". They should be unified. What wording is better?

**Comment by vstinner** [comment]
> Note that some error messages are "takes no keyword arguments", but others are "does not take keyword arguments" or "doesn't take keyword arguments".

We already have a \_PyArg_NoKeywords() function. Maybe we could add a new \_PyErr_NoKeywords() function which would just raise the error?

**Comment by serhiy-storchaka** [comment]
The details can be different. For example:

```pycon
>>> 1 .__add__(x=2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: wrapper __add__ doesn't take keyword arguments
```


The message contains the word "wrapper" and doesn't contains parenthesis. I think it can be extended for containing the type name ("int.\_\_add__()" or "wrapper \_\_add__ of in objects"), and this hard to do with general \_PyErr_NoKeywords(). Let first unify messages, then try to add more useful information in messages and create a general API if this is possible.

**Comment by brettcannon** [comment]
> Note that some error messages are "takes no keyword arguments", but others are "does not take keyword arguments" or "doesn't take keyword arguments". They should be unified. What wording is better?

I vote for "takes no keyword arguments".

**Comment by serhiy-storchaka** [comment]
Updated error messages. Later I'm going to unify error messages for Python and C functions. But this is a different issue.

I can wrote a test, but I don't know good place for it. test_builtin doesn't look a good place to me.

**Comment by brettcannon** [comment]
The tests could either go into the respective type's tests or a new test module like test_exception_messages could be added that's only to help keep messages in sync with each other.

**Comment by serhiy-storchaka** [comment]
There is no respective type. abs() is just an arbitrary example. There are perhaps tens functions affected by this bug. test_exception_messages looks an overkill. There are similar tests in test_capi and test_getargs2 that test public PyArg_* functions. But this bug is related to other code.

Hmm, may be test_call is an appropriate test.

**Comment by serhiy-storchaka** [comment]
New changeset 5eb788bf7f54a8e04429e18fc332db858edd64b6 by Serhiy Storchaka in branch 'master':
bpo-30534: Fixed error messages when pass keyword arguments (bpo-1901)
https://github.com/python/cpython/commit/5eb788bf7f54a8e04429e18fc332db858edd64b6

**Comment by serhiy-storchaka** [comment]
New changeset 6cca5c8459cc439cb050010ffa762a03859d3051 by Serhiy Storchaka in branch 'master':
bpo-30592: Fixed error messages for some builtins. (bpo-1996)
https://github.com/python/cpython/commit/6cca5c8459cc439cb050010ffa762a03859d3051
