### ISSUE TITLE
PyMemoryView_FromBuffer memory leak

### ISSUE THREAD

**Issue by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [python/cpython#74712]
BPO | [30527](https://bugs.python.org/issue30527)
--- | :---
Nosy | @skrah, @lazka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-05-31.17:32:00.126>
created_at = <Date 2017-05-31.16:35:05.477>
labels = ['invalid']
title = 'PyMemoryView_FromBuffer memory leak'
updated_at = <Date 2017-05-31.19:49:55.134>
user = 'https://github.com/lazka'
```

bugs.python.org fields:
```python
activity = <Date 2017-05-31.19:49:55.134>
actor = 'lazka'
assignee = 'none'
closed = True
closed_date = <Date 2017-05-31.17:32:00.126>
closer = 'lazka'
components = []
creation = <Date 2017-05-31.16:35:05.477>
creator = 'lazka'
dependencies = []
files = []
hgrepos = []
issue_num = 30527
keywords = []
message_count = 7.0
messages = ['294851', '294852', '294853', '294856', '294858', '294860', '294867']
nosy_count = 2.0
nosy_names = ['skrah', 'lazka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30527'
versions = []
```

</p></details>

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
I'm using the following code

```c
PyObject *
get_memoryview (PyObject *self) {
    Py_buffer view;
```


    ...

    // this takes a ref on self
    if (PyBuffer_FillInfo (&view, self, buffer, length, 0, 0) < 0)
        return NULL;

    // this returns a \<memory\> object
    return PyMemoryView_FromBuffer (&view);
}

The problem is that when I call release() on the returned memory object
the buffer does not get release and as a result the exporter leaks.

Am I missing something or is this a bug?

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
"Py_buffer view" is stack allocated. One can use memoryviews based on such buffers \*inside* a function, but not return them.

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
hm, ok.

Any idea how I can create a memoryview that is usable from Python then?

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
"Py_buffer view" needs to go into the exporting object.  That object needs  a getbufferproc().  That getbufferproc() can use  PyBuffer_FillInfo() to fill in the view that is now kept alive because it's in the object.

The object then supports the buffer protocol and memoryviews can be created automatically from the Python level without any further C code.

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
Ah, so if I understand correctly, exposing always requires something implementing the buffer interface in some way. I might require multiple different memoryviews for this object, so maybe some proxy object implementing it might work.

Thanks Stefan for your quick help.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Sorry, actually I wasn't totally clear:  The exporting object just needs a getbufferproc() that can respond to buffer requests and keeps track of how many views are exported.

"View in the object" is misleading and not necessary; it can be used for some advanced stuff.

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
In case someone ends up here with a similar problem, here is my solution using a proxy object: https://github.com/pygobject/pycairo/blob/4ab80df68dd99a8e4bfb0c6a88dc5b2a9b0f3f10/cairo/bufferproxy.c
