### ISSUE TITLE
[EASY] SubinterpThreadingTests.test_threads_join_2() of test_threading leaks references

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74721]
BPO | [30536](https://bugs.python.org/issue30536)
--- | :---
Nosy | @vstinner, @ericsnowcurrently, @zware, @serhiy-storchaka, @sayanchowdhury
Superseder | <li>bpo-30547: [Windows] SubinterpreterTest.test_callbacks_leak() of test_atexit leaks references</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-08.10:20:50.294>
created_at = <Date 2017-06-01.10:42:19.613>
labels = ['easy', '3.7', 'performance']
title = '[EASY] SubinterpThreadingTests.test_threads_join_2() of test_threading leaks references'
updated_at = <Date 2017-06-08.10:47:04.664>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-08.10:47:04.664>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-08.10:20:50.294>
closer = 'vstinner'
components = []
creation = <Date 2017-06-01.10:42:19.613>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30536
keywords = ['easy (C)']
message_count = 4.0
messages = ['294932', '294997', '295024', '295393']
nosy_count = 5.0
nosy_names = ['vstinner', 'eric.snow', 'zach.ware', 'serhiy.storchaka', 'sayanchowdhury']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30547'
type = 'resource usage'
url = 'https://bugs.python.org/issue30536'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Ah! I succeeded to hack a tool to bisect -m test -R 3:3 failure (issue bpo-29512, I will publish it later, right now it's too hackish), so I found a first guilty of failure on the Gentoo Refleak failure.

Maybe it's related to recent Eric Snow's work. Maybe not. I didn't dig the bug yet.

haypo@selma$ ./python -m test -R 3:3 -m test_threads_join_2 test_threading
Run tests sequentially
0:00:00 load avg: 0.16 [1/1] test_threading
beginning 6 repetitions
123456
......
test_threading leaked [3, 3, 3] references, sum=9
test_threading failed

1 test failed:
    test_threading

Total duration: 2 sec
Tests result: FAILURE

**Comment by vstinner** [comment]
I tagged this issue as easy. I consider that it's a good exercice for new contributors. Core developers: please let new contributors try to fix it since this issue is not critical, try to explain how to fix it rather than writing the fix ;-)

**Comment by f6330953-d34a-4806-aa4c-7b29197e4ed6** [comment]
I replicated the issue. Starting to work on the issue.

**Comment by vstinner** [comment]
This issue is a duplicate of bpo-30547.

I tested that bpo-30547 fixes this issue.
