### ISSUE TITLE
_io._WindowsConsoleIO.write raises the wrong error when WriteConsoleW fails

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#74729]
BPO | [30544](https://bugs.python.org/issue30544)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @segevfiner
PRs | <li>python/cpython#1912</li><li>python/cpython#1925</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-02.21:40:51.935>
created_at = <Date 2017-06-01.22:57:43.644>
labels = ['type-bug', '3.7', 'expert-IO', 'OS-windows']
title = '_io._WindowsConsoleIO.write raises the wrong error when WriteConsoleW fails'
updated_at = <Date 2017-06-02.21:40:51.934>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-02.21:40:51.934>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-02.21:40:51.935>
closer = 'steve.dower'
components = ['Windows', 'IO']
creation = <Date 2017-06-01.22:57:43.644>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30544
keywords = ['3.2regression']
message_count = 6.0
messages = ['294975', '294988', '294998', '295033', '295034', '295056']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Segev Finer']
pr_nums = ['1912', '1925']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30544'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Found due to this: https://github.com/pytest-dev/py/issues/103

I'm going to submit a PR.

**Comment by eryksun** [comment]
The following is an example of the problem, right?

```pycon
    >>> fd = os.open('stdout.txt', os.O_CREAT | os.O_WRONLY)
    >>> os.dup2(fd, 1)
    >>> print('spam')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    OSError: [WinError 87] The parameter is incorrect
```


Code like this used to work, so possibly this needs to be addressed more generally. I have a couple ideas, but they're major changes. It's simpler to require code that pulls the rug out from under \_WindowsConsoleIO to rebind sys.std*. 

For a counterexample, PyOS_StdioReadline always checks for a console and falls back on the old my_fgets function for a non-console. For example:

```pycon
    >>> open('stdin.txt', 'w').write('x=42; os.dup2(oldfd, 0)\n')
    24
    >>> fd = os.open('stdin.txt', os.O_RDONLY)
    >>> oldfd = os.dup(0); os.dup2(fd, 0)
    >>> Breakpoint 0 hit
    python36!my_fgets:
    00000000`66e98318 488bc4          mov     rax,rsp
    0:000> g
    >>> x
    42
```

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
We might want to open a separate issue for the FD redirection issue since this one was really about the \_io.\_WindowsConsoleIO.write GetLastError() issue.

Also see https://github.com/pytest-dev/pytest/pull/2462 where I discuss this more.

Still not sure why it's random in Pytest. I can only guess it's due to another console handle getting opened with the same number or something.

**Comment by zooba** [comment]
New changeset 523776c3419f6795e78173d53c10e35ec4eed48d by Steve Dower (Segev Finer) in branch 'master':
bpo-30544: \_io.\_WindowsConsoleIO.write raises the wrong error when WriteConsoleW fails (bpo-1912)
https://github.com/python/cpython/commit/523776c3419f6795e78173d53c10e35ec4eed48d

**Comment by zooba** [comment]
Yeah, make it a separate issue.

This PR fixes an obvious error that we should just fix, so I've merged it. (I might get to the backport today, but if someone else submits it then I'll merge.)

**Comment by zooba** [comment]
New changeset c63ae1122f84d4188ffadfd1454902093eb10be1 by Steve Dower in branch '3.6':
bpo-30544: \_io.\_WindowsConsoleIO.write raises the wrong error when WriteConsoleW fails (bpo-1912) (bpo-1925)
https://github.com/python/cpython/commit/c63ae1122f84d4188ffadfd1454902093eb10be1
