### ISSUE TITLE
Functional Programming HOWTO describes one argument itertools.count()

### ISSUE THREAD

**Issue by csabella** [python/cpython#74723]
BPO | [30538](https://bugs.python.org/issue30538)
--- | :---
Nosy | @rhettinger, @Mariatta, @csabella
PRs | <li>python/cpython#1919</li><li>python/cpython#1943</li><li>python/cpython#1944</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-06-04.17:39:53.998>
created_at = <Date 2017-06-01.11:32:35.975>
labels = ['type-feature', '3.7', 'docs']
title = 'Functional Programming HOWTO describes one argument itertools.count()'
updated_at = <Date 2017-06-05.03:12:25.736>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-05.03:12:25.736>
actor = 'Mariatta'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-06-04.17:39:53.998>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-06-01.11:32:35.975>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30538
keywords = []
message_count = 11.0
messages = ['294935', '294986', '295011', '295021', '295081', '295111', '295134', '295135', '295139', '295160', '295161']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1919', '1943', '1944']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30538'
versions = ['Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
The Functional Programming HOWTO describes single variable itertools.count instead of the two variable version that is linked to.

**Comment by rhettinger** [comment]
If you would like, go ahead an submit a PR.

**Comment by csabella** [comment]
Submitted a PR, thank you.

I changed added the argument for count().  Also I noticed that the link to accumulate() was broken, so I fixed that and I added a link to functools in the references at the end of the page.

One other thing I noticed was that enumerate was described with one argument, but it takes two.  Should I update that as well?

Thanks!

**Comment by rhettinger** [comment]
> enumerate was described with one argument, but it takes two.
> Should I update that as well?

Yes please.

**Comment by csabella** [comment]
Thank you.  I've added that.  

This may seem like an odd question, but should I assume that the docs should always match the code?  For example, in the Functional HOWTO, I wasn't sure if the arguments were left off purposely or if it was just something that hadn't been updated.  If the docs should always match, then I wouldn't have to ask so many questions if I see another place where this happens.

Also, the example for enumerate is this:

```py
f = open('data.txt', 'r')
for i, line in enumerate(f):
    if line.strip() == '':
        print('Blank line at line #%i' % i)
```


Is it code churn to replace the old style string formatting or is that something else that should be done as clean-up?

**Comment by rhettinger** [comment]
> Is it code churn to replace the old style string formatting
> or is that something else that should be done as clean-up?

Let's leave it as is.  Old-style formatting is still valid and is not going away.   We consciously decided not to sweep through the docs change the string formatting style.  Also, since both occur quite a bit in the wild, it is is useful for the docs to show some of both.

**Comment by rhettinger** [comment]
New changeset 9be4ff359daa67cde6246494f643ed7cd2825d46 by Raymond Hettinger (csabella) in branch 'master':
bpo-30538: Update count() in Functional Programming HOWTO (bpo-1919)
https://github.com/python/cpython/commit/9be4ff359daa67cde6246494f643ed7cd2825d46

**Comment by rhettinger** [comment]
Thank you for the PR.

**Comment by csabella** [comment]
Thank you.  And thank you for explaining about the strings.  That's what I suspected, so I appreciate you confirming it.

**Comment by Mariatta** [comment]
New changeset b32fb6c1fb6cdf019817176f573e60c0923a6e22 by Mariatta (csabella) in branch '3.5':
bpo-30538: Update count() in Functional Programming HOWTO (GH-1919) (GH-1944)
https://github.com/python/cpython/commit/b32fb6c1fb6cdf019817176f573e60c0923a6e22

**Comment by Mariatta** [comment]
New changeset ce40550acd3a8928bb6fef4d4e73642a8a69745d by Mariatta (csabella) in branch '3.6':
bpo-30538: Update count() in Functional Programming HOWTO (GH-1919) (GH-1943)
https://github.com/python/cpython/commit/ce40550acd3a8928bb6fef4d4e73642a8a69745d
