### ISSUE TITLE
regrtest: add --matchfile option

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74725]
BPO | [30540](https://bugs.python.org/issue30540)
--- | :---
Nosy | @vstinner, @vadmium, @serhiy-storchaka
PRs | <li>python/cpython#1909</li><li>python/cpython#2244</li><li>python/cpython#2249</li><li>python/cpython#2250</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-09.08:21:09.627>
created_at = <Date 2017-06-01.19:39:14.483>
labels = ['3.7', 'type-feature', 'tests']
title = 'regrtest: add --matchfile option'
updated_at = <Date 2017-07-18.17:52:29.518>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-18.17:52:29.518>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-09.08:21:09.627>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-01.19:39:14.483>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30540
keywords = []
message_count = 8.0
messages = ['294959', '294960', '295082', '295496', '295497', '296188', '296202', '296209']
nosy_count = 3.0
nosy_names = ['vstinner', 'martin.panter', 'serhiy.storchaka']
pr_nums = ['1909', '2244', '2249', '2250']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30540'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Attached pull request adds the --matchfile option to regrtest.
    
* Add a new option taking a filename to get a list of test names to filter tests.
* support.match_tests becomes a list.
* Modify run_unittest() to accept to match the whole test identifier, not just a part of a test identifier.
   
For example, the following command only runs test_default_timeout() of the BarrierTests class of test_threading:
    
$ ./python -m test -v test_threading -m test.test_threading.BarrierTests.test_default_timeout

**Comment by vstinner** [comment]
This issue is the last part to implement the issue bpo-29512: "regrtest refleak: implement bisection feature".

See also the second part, bpo-30523: unittest: add --list-tests option to only display the list of test names, don't run tests.

**Comment by serhiy-storchaka** [comment]
I less need reading test names from a file than other changes in this file. :)

But what about doctests? They are run unconditionally.

**Comment by vstinner** [comment]
New changeset ef8320cf6f09b659c63bfb188bf45dbcae556762 by Victor Stinner in branch 'master':
bpo-30540: regrtest: add --matchfile option (bpo-1909)
https://github.com/python/cpython/commit/ef8320cf6f09b659c63bfb188bf45dbcae556762

**Comment by vstinner** [comment]
> But what about doctests? They are run unconditionally.

Sorry, I don't know how to handle them. I only tried to make a small enhancement for my "bisect" usecase. If you see a way to handle them, don't hesitate to propose a patch!

I would prefer to have time to play with the new feature before backporting it to stable branches. If someone needs this feature right now in stable branches, speak up and maybe also reopen the issue ;-)

My change was merged (with unit tests!), so I close the issue.

**Comment by vstinner** [comment]
New changeset a0ccc54e6dffacf9e7c06f2a3e9056d2d35d21eb by Victor Stinner in branch '3.6':
Synchronize libregrtest from master to 3.6 (bpo-2244)
https://github.com/python/cpython/commit/a0ccc54e6dffacf9e7c06f2a3e9056d2d35d21eb

**Comment by vstinner** [comment]
New changeset 24c2c20873dc800c99d1dabf26419b40cadfe627 by Victor Stinner in branch '2.7':
bpo-30540, bpo-30523: Add --matchfile and --list-cases options to regrtest (bpo-2249)
https://github.com/python/cpython/commit/24c2c20873dc800c99d1dabf26419b40cadfe627

**Comment by vstinner** [comment]
New changeset 46e299c1536da541b9dbf76c0cb909bf8c79f589 by Victor Stinner in branch '3.5':
[3.5] bpo-30540, bpo-30523: Add --matchfile and --list-cases options to regrtest (bpo-2250)
https://github.com/python/cpython/commit/46e299c1536da541b9dbf76c0cb909bf8c79f589
