### ISSUE TITLE
Add HTTP Response code 421

### ISSUE THREAD

**Issue by dd87c8e8-c0b2-4ca8-b7c3-ba55d72ffbb9** [python/cpython#74738]
BPO | [30553](https://bugs.python.org/issue30553)
--- | :---
Nosy | @rhettinger, @berkerpeksag, @julienc91, @vmsp
PRs | <li>python/cpython#2589</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-26.18:50:50.797>
created_at = <Date 2017-06-02.12:50:32.258>
labels = ['3.7', 'type-feature', 'library']
title = 'Add HTTP Response code 421'
updated_at = <Date 2017-10-26.18:50:50.794>
user = 'https://github.com/julienc91'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-26.18:50:50.794>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-26.18:50:50.797>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-06-02.12:50:32.258>
creator = 'julienc'
dependencies = []
files = []
hgrepos = []
issue_num = 30553
keywords = []
message_count = 5.0
messages = ['295013', '297755', '297901', '305080', '305081']
nosy_count = 4.0
nosy_names = ['rhettinger', 'berker.peksag', 'julienc', 'vmsp']
pr_nums = ['2589']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30553'
versions = ['Python 3.7']
```

</p></details>

**Comment by dd87c8e8-c0b2-4ca8-b7c3-ba55d72ffbb9** [comment]
The `http.HTTPStatus` class provides constants for most of the HTTP status codes.
Status code 421 was added by the RFC 7540 (HTTP/2), and is not part of this class. It is described as follows:

> The 421 (Misdirected Request) status code indicates that the request
> was directed at a server that is not able to produce a response.
> This can be sent by a server that is not configured to produce
> responses for the combination of scheme and authority that are
> included in the request URI.

Would it be possible to create the corresponding constant in `http.HTTPStatus`?

For reference:
* Status code 421 in the RFC 7540:
    https://tools.ietf.org/html/rfc7540#section-9.1.2
* Documentation on the HTTPStatus class in python 3.6:
    https://docs.python.org/3/library/http.html#http-status-codes
* Another opened issue relative to the status code 451 currently pending review:
    https://bugs.python.org/issue26589

**Comment by a112f6b9-61d0-4bf0-8679-04d3662796fc** [comment]
I just submitted a PR, feel free to take a look.

**Comment by rhettinger** [comment]
+1

**Comment by berkerpeksag** [comment]
New changeset 52ad72dd0a5a56414cc29b7c9b03259169825f35 by Berker Peksag (Vitor Pereira) in branch 'master':
bpo-30553: Add status code 421 to http.HTTPStatus (GH-2589)
https://github.com/python/cpython/commit/52ad72dd0a5a56414cc29b7c9b03259169825f35

**Comment by berkerpeksag** [comment]
Thank you Julien (for the report) and Vitor (for the patch)
