### ISSUE TITLE
ProcessPoolExecutor hangs forever if the object raises on __getstate__

### ISSUE THREAD

**Issue by 335b6a05-b084-4d4e-bac2-46d0b794bffa** [python/cpython#74734]
BPO | [30549](https://bugs.python.org/issue30549)
--- | :---
Nosy | @grzgrzgrz3
Superseder | <li>bpo-30006: Deadlocks in `concurrent.futures.ProcessPoolExecutor`</li>
Files | <li>[test_noshutdown.py](https://bugs.python.org/file46919/test_noshutdown.py "Uploaded as text/plain at 2017-06-02.09:15:57 by Roberto Martínez")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-23.17:03:01.394>
created_at = <Date 2017-06-02.09:15:57.510>
labels = ['type-bug']
title = 'ProcessPoolExecutor hangs forever if the object raises on __getstate__'
updated_at = <Date 2017-10-23.17:03:01.393>
user = 'https://bugs.python.org/RobertoMartnez'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-23.17:03:01.393>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-23.17:03:01.394>
closer = 'berker.peksag'
components = []
creation = <Date 2017-06-02.09:15:57.510>
creator = 'Roberto Mart\xc3\xadnez'
dependencies = []
files = ['46919']
hgrepos = []
issue_num = 30549
keywords = []
message_count = 2.0
messages = ['294999', '296577']
nosy_count = 2.0
nosy_names = ['Roberto Mart\xc3\xadnez', 'grzgrzgrz3']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30006'
type = 'behavior'
url = 'https://bugs.python.org/issue30549'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 335b6a05-b084-4d4e-bac2-46d0b794bffa** [comment]
Hi, I detected that a ProcessPoolExecutor hangs if the object fails to picklelize.

I attached the simplest code to reproduce the behavior. Note that the interpreter should exit after the exception but it doesn't and hangs forever.

I tested with python 3.4, 3.5 and 3.6 with the same results.

**Comment by 6dc2ace7-63c1-4dd4-a1e8-050515409c65** [comment]
This is already reported and patch was proposed. Here: bpo-30006
