### ISSUE TITLE
_io._WindowsConsoleIO breaks in the face of fd redirection

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#74740]
BPO | [30555](https://bugs.python.org/issue30555)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @segevfiner
PRs | <li>python/cpython#1927</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-02.16:56:53.131>
labels = ['type-bug', '3.8', '3.9', 'expert-IO', '3.10', 'OS-windows']
title = '_io._WindowsConsoleIO breaks in the face of fd redirection'
updated_at = <Date 2021-04-23.22:04:03.017>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-23.22:04:03.017>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows', 'IO']
creation = <Date 2017-06-02.16:56:53.131>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30555
keywords = []
message_count = 5.0
messages = ['295041', '295047', '388796', '391745', '391746']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Segev Finer']
pr_nums = ['1927']
priority = 'normal'
resolution = None
stage = 'backport needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30555'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
\_WindowsConsoleIO works by taking the handle out of the file descriptors of the stdio handles (get_osfhandle) and reading/writing to it directly using ReadConsoleW/WriteConsoleW.

The problem is that some Python code wants to do file descriptor level redirection by overwriting the standard file descriptors using dup2. The problem is that this is also going to close the handle that Python itself is going to use to read/write to the console. Leading to the following:

```pycon
    >>> fd = os.open('stdout.txt', os.O_CREAT | os.O_WRONLY)
    >>> os.dup2(fd, 1)
    >>> print('spam')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    OSError: [WinError 87] The parameter is incorrect  # "OSError: [WinError 6] The handle is invalid" after https://bugs.python.org/issue30544
```


This manifests itself for example in Pytest which does fd redirection to capture test output. See https://github.com/pytest-dev/py/issues/103 for the issue. And see https://github.com/pytest-dev/pytest/pull/2462 for an WIP attempt to workaround this.

This issue also impacts other code that uses console handles itself like colorama: https://github.com/pytest-dev/pytest/issues/2465. Though that code is likely going to have to deal with this by itself.

Those file descriptors are an emulation implemented by the Universal CRT and you can see their implementation in your copy of the Windows SDK. It's quite possible that this doesn't happen in older CRT versions either since colorama doesn't seem to break on Python 2.7 for example.

One way I can think working around this is that Python will DuplicateHandle the console handles so that even if dup2 closes the original ones it will keep on working. We can also switch to calling \_get_osfhandle always instead of caching the handle, it will break when the fd is redirected to a non-console. But so does \_WindowsConsoleIO in general since it will try to continue writing to the console despite the redirection, meaning that Python code doing redirection has to handle sys.std* anyhow. Though I'm not sure about the performance of constantly calling \_get_osfhandle. And their yet might be other ways to solve this.

Also see comment by eryksun https://bugs.python.org/msg294988

Solving this in CPython will remove the need for hacks like the PR I referenced.

**Comment by zooba** [comment]
> We can also switch to calling \_get_osfhandle always instead of caching the handle, it will break when the fd is redirected to a non-console. But so does \_WindowsConsoleIO in general since it will try to continue writing to the console despite the redirection, meaning that Python code doing redirection has to handle sys.std* anyhow.

This might be the best approach, ultimately. I bet there's an optimization here, though it's not obvious.

Probably the main issue here is readline not properly handling sys.std*. If that was fixed, I think many of these problems (at least at the interactive prompt) would simply go away.

**Comment by erlend-aasland** [comment]
ISTM this was fixed. I'm marking this as pending close. cc. @zooba

**Comment by erlend-aasland** [comment]
AFAICS, gh-77046 is a duplicate of this issue and can be closed.

**Comment by zooba** [comment]
It was fixed but not backported, which is why I left it open. The backports are irrelevant now, so yeah, can close.
