### ISSUE TITLE
[Suggestion] Improve documentation for set() API

### ISSUE THREAD

**Issue by 2b37b863-2556-4a96-8f51-572d9adfee04** [python/cpython#74743]
BPO | [30558](https://bugs.python.org/issue30558)
--- | :---
Nosy | @rhettinger, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-06-04.17:37:29.719>
created_at = <Date 2017-06-03.04:05:36.498>
labels = ['type-feature', 'invalid', 'docs']
title = '[Suggestion] Improve documentation for set() API'
updated_at = <Date 2017-06-04.17:37:29.719>
user = 'https://bugs.python.org/JacobPratt'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-04.17:37:29.719>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-06-04.17:37:29.719>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-06-03.04:05:36.498>
creator = 'Jacob Pratt'
dependencies = []
files = []
hgrepos = []
issue_num = 30558
keywords = []
message_count = 3.0
messages = ['295064', '295069', '295112']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'martin.panter', 'Jacob Pratt']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30558'
versions = ['Python 3.6']
```

</p></details>

**Comment by 2b37b863-2556-4a96-8f51-572d9adfee04** [comment]
While going through the documentation, I found that set() has surprisingly little documentation, not even a list of built-in methods.

I'm not sure exactly what is missing, but I know that issubset and issuperset isn't in there (that's what I was looking for, specifically).

Thanks!

**Comment by vadmium** [comment]
Did you see \<https://docs.python.org/3.6/library/stdtypes.html#set-types-set-frozenset\>?

**Comment by rhettinger** [comment]
This looks like an invalid request.
