### ISSUE TITLE
SSL socket does not respect SO_RCVTIME0 timeouts

### ISSUE THREAD

**Issue by 0f5bd8a7-17f6-4f86-b49b-d48cfc7262a4** [python/cpython#74747]
BPO | [30562](https://bugs.python.org/issue30562)
--- | :---
Nosy | @tiran, @the-allanc
Files | <li>[httpdelay.py](https://bugs.python.org/file46922/httpdelay.py "Uploaded as text/plain at 2017-06-03.21:15:41 by @the-allanc")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-06-06.17:27:31.318>
created_at = <Date 2017-06-03.21:15:42.052>
labels = ['expert-SSL', 'type-bug']
title = 'SSL socket does not respect SO_RCVTIME0 timeouts'
updated_at = <Date 2017-06-06.17:27:31.317>
user = 'https://github.com/the-allanc'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.17:27:31.317>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-06-06.17:27:31.318>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2017-06-03.21:15:42.052>
creator = 'allanc'
dependencies = []
files = ['46922']
hgrepos = []
issue_num = 30562
keywords = []
message_count = 2.0
messages = ['295106', '295280']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'allanc']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30562'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 0f5bd8a7-17f6-4f86-b49b-d48cfc7262a4** [comment]
I initially filed this ticket against the ldap3 library, as this is where I first encountered the issue: https://github.com/cannatag/ldap3/issues/356

I've attached a file which reproduces the issue using the standard library - it makes both a HTTP and HTTPS request to a link that should return a HTTP response after 10 seconds, but we set the socket option SO_RCVTIMEO to 2 seconds. This should result in a read timeout while waiting for a response.

On my 64 bit Ubuntu 16.04 machine, the HTTP connection times out as expected, but the HTTPS connection doesn't time out at all (and so ends up reading the HTTP response).

It doesn't seem to be an issue specific to HTTPS - I ran into the original issue while using TLS for an LDAP connection using the ldap3 library. If you follow the comments in the ticket, a connection with SO_RCVTIMEO set to 3 seconds ended up taking 1076 seconds to timeout, while on an OSX machine, it took 148 seconds to timeout. On a Windows machine, it seems to work just fine (it timed out after the desired 3 seconds).

Is this option fully supported for SSL sockets?

**Comment by tiran** [comment]
SO_RCVTIME0 works only with operating system level sockets. A SSLSocket is not an OS level. It's a high level abstraction layer that wraps either a file descriptor or a memory BIO. A read operation on a SSLSocket can perform write, a write operation can perform read. For the initial handshake, it will do both.

This means that SO_RCVTIME0 is not supported. Either you have to use the SSLSocket's timeout feature or do your own socket io and use a memory BIO. The internal timeout feature is build around select()/poll() syscall and low level OpenSSL calls.
