### ISSUE TITLE
faulthandler does not correctly filter fatal exceptions on Windows

### ISSUE THREAD

**Issue by zooba** [python/cpython#74742]
BPO | [30557](https://bugs.python.org/issue30557)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @ned-deily, @zware, @eryksun, @zooba
PRs | <li>python/cpython#1924</li><li>python/cpython#1960</li><li>python/cpython#1969</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-06-06.20:47:54.209>
created_at = <Date 2017-06-02.21:09:30.875>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'faulthandler does not correctly filter fatal exceptions on Windows'
updated_at = <Date 2017-06-06.20:47:54.208>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.20:47:54.208>
actor = 'steve.dower'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-06-06.20:47:54.209>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-06-02.21:09:30.875>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 30557
keywords = []
message_count = 9.0
messages = ['295054', '295055', '295216', '295217', '295232', '295272', '295281', '295284', '295301']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'ned.deily', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = ['1924', '1960', '1969']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30557'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zooba** [comment]
faulthandler adds a structured exception handler on Windows so we can dump a Python traceback before crashing. This should only be done for fatal exceptions, but is currently done for some non-fatal exceptions.

The current test is `flags & EXCEPTION_NONCONTINUABLE`, which is incorrect (as evidenced by the fact that the check is wrong in its current context and should be `!(flags & EXCEPTION_NONCONTINUABLE)`).

Instead, `code & 0x80000000` determines whether the exception is an error. If not, we should skip logging any info.

**Comment by zooba** [comment]
Also, it displays exception codes as decimal, but should be hex. I'll fix that too

**Comment by zooba** [comment]
New changeset e6a23c8f9a3ce05b759599696cc131c2d9d147ac by Steve Dower in branch 'master':
bpo-30557: faulthandler now correctly filters and displays exception codes on Windows (bpo-1924)
https://github.com/python/cpython/commit/e6a23c8f9a3ce05b759599696cc131c2d9d147ac

**Comment by ned-deily** [comment]
Buildbot failure?
http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.x/builds/521

**Comment by zooba** [comment]
Thanks. Apparently that "filter out bit 4" thing didn't exist in Win7. Guess I need to track down the actual docs and confirm exactly where that happens.

Doesn't break the important functionality though, just the test. I don't know that the exit code is stable when the process crashes, so perhaps I should just test for non-zero.

**Comment by vstinner** [comment]
It seems like all 3.x Windows buildbots are red... except of x86 Windows7 3.x.

Only on Windows older than 7 SP 1, so on Windows 7 for buildbots, the bit is cleared.

I created https://github.com/python/cpython/pull/1969 to try to fix buildbots.

**Comment by zooba** [comment]
New changeset 6a1d84e2b37291b7e3bc5ddad14a60aed430e404 by Steve Dower (Victor Stinner) in branch 'master':
bpo-30557: Fix test_faulthandler (bpo-1969)
https://github.com/python/cpython/commit/6a1d84e2b37291b7e3bc5ddad14a60aed430e404

**Comment by zooba** [comment]
My backport wasn't merged, so I cherrypicked Victor's fix into that PR. Once the buildbots are green again, I'll merge it.

**Comment by zooba** [comment]
New changeset 2bafc0dccac2390a52670ba289878318b6ea0293 by Steve Dower in branch '3.6':
[3.6] bpo-30557: faulthandler now correctly filters and displays exception … (bpo-1960)
https://github.com/python/cpython/commit/2bafc0dccac2390a52670ba289878318b6ea0293
