### ISSUE TITLE
Bugs in Web app

### ISSUE THREAD

**Issue by b6ff01e2-4ed0-4f3e-831a-cfe8e45a6a2e** [python/cpython#74744]
BPO | [30559](https://bugs.python.org/issue30559)
--- | :---
Nosy | @terryjreedy, @mdickinson

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-03.09:17:48.620>
created_at = <Date 2017-06-03.08:36:44.422>
labels = ['expert-IDLE', 'type-bug', 'invalid']
title = 'Bugs in Web app'
updated_at = <Date 2017-06-03.15:42:44.893>
user = 'https://bugs.python.org/Mahira'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-03.15:42:44.893>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-03.09:17:48.620>
closer = 'mark.dickinson'
components = ['IDLE']
creation = <Date 2017-06-03.08:36:44.422>
creator = 'Mahira'
dependencies = []
files = []
hgrepos = []
issue_num = 30559
keywords = []
message_count = 3.0
messages = ['295071', '295072', '295083']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'mark.dickinson', 'Mahira']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30559'
versions = ['Python 3.6']
```

</p></details>

**Comment by b6ff01e2-4ed0-4f3e-831a-cfe8e45a6a2e** [comment]
Hai 

```pytb
I followed your Tutorial
In the Following Program, i am getting 
Traceback (most recent call last):
  File "C:\Users\Mahira\AppData\Local\Programs\Python\Python36\Scripts\localhost.py", line 1, in <module>
    import web
  File "C:\Users\Mahira\AppData\Local\Programs\Python\Python36\Scripts\web.py", line 6, in <module>
    app = web.application(("urls"),globals())
AttributeError: module 'web' has no attribute 'application'
```


And my program is:

```py
import web

urls = (
    '/', 'index'
)

class index:
    def GET(self):
        return "Hello, world!"

if __name__ == "__main__":
    app = web.application(urls, globals())
    app.run()
```

**Comment by mdickinson** [comment]
Hi Mahira,

This site is for reporting bugs in the Python core language itself, not bugs in code written by users.

You appear to be using the "Learn Python the Hard Way" tutorial, which is a third-party resource that's not maintained by the Python language developers. You might want to try asking your questions on one of the Python mailing lists (see https://www.python.org/community/lists/), or the "Learn Code the Hard Way" chat room: https://gitter.im/lcthw/Lobby

**Comment by terryjreedy** [comment]
It is good that you included both a short program and the full traceback. Too many beginners don't do that when asking questions.  Three comments: your program does not have syntax errors and compiled just fine; exceptions almost never involved the editor/IDE you happen to use; if 'web' comes from a book, its discussion group should be your best bet.
