### ISSUE TITLE
README Formatting

### ISSUE THREAD

**Issue by f0e87730-c80d-42de-809a-9c6ac970d3d9** [python/cpython#74753]
BPO | [30568](https://bugs.python.org/issue30568)
--- | :---
Nosy | @CrazyPython, @Mariatta, @csabella
PRs | <li>python/cpython#1942</li>
Superseder | <li>bpo-29555: Update Python Software Foundation Copyright Year</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-05.03:04:53.578>
created_at = <Date 2017-06-04.20:02:18.565>
labels = ['type-feature', '3.7', 'docs']
title = 'README Formatting'
updated_at = <Date 2017-06-05.03:04:53.576>
user = 'https://github.com/CrazyPython'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-05.03:04:53.576>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-05.03:04:53.578>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-04.20:02:18.565>
creator = 'James.Lu'
dependencies = []
files = []
hgrepos = []
issue_num = 30568
keywords = []
message_count = 3.0
messages = ['295140', '295143', '295156']
nosy_count = 4.0
nosy_names = ['docs@python', 'James.Lu', 'Mariatta', 'cheryl.sabella']
pr_nums = ['1942']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29555'
type = 'enhancement'
url = 'https://bugs.python.org/issue30568'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f0e87730-c80d-42de-809a-9c6ac970d3d9** [comment]
- Shorten the Copyright statement from a list of years (`2001, 2002, 2003, ... 2017`) into `2001-2017`
  - Extend copyright date at end of README from 2016 to 2017
 - Ensure that there are two newlines before every header throughout the file (this was the original format)

**Comment by csabella** [comment]
I had made the same suggestion a few months ago and found that it had already been discussed.  :-)

Duplicate of http://bugs.python.org/issue29555.

**Comment by Mariatta** [comment]
Thanks :) Yes the issue with copyright in the docs is still pending.
I'm closing this as a duplicate.
