### ISSUE TITLE
Leak in sys.getwindowsversion

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#74752]
BPO | [30567](https://bugs.python.org/issue30567)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @eryksun, @zooba, @segevfiner
PRs | <li>python/cpython#1940</li><li>python/cpython#1970</li><li>python/cpython#1971</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-06-06.16:24:40.023>
created_at = <Date 2017-06-04.17:20:58.894>
labels = ['3.7', 'OS-windows', 'performance']
title = 'Leak in sys.getwindowsversion'
updated_at = <Date 2017-06-07.15:45:14.902>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-07.15:45:14.902>
actor = 'vstinner'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-06-06.16:24:40.023>
closer = 'serhiy.storchaka'
components = ['Windows']
creation = <Date 2017-06-04.17:20:58.894>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30567
keywords = []
message_count = 6.0
messages = ['295132', '295137', '295275', '295276', '295277', '295351']
nosy_count = 8.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'eryksun', 'steve.dower', 'Segev Finer']
pr_nums = ['1940', '1970', '1971']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30567'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
There is a ref leak in sys.getwindowsversion due to using PyTuple_Pack and forgetting that it increments the ref count of passed in objects. Found here: https://github.com/python/cpython/pull/1927#issuecomment-306019512.

Clearly shows up in python -m test -R 3:2 test_sys

**Comment by serhiy-storchaka** [comment]
New changeset 48fb766f70d9ca9d5934cbddbe8d8e7972cb6343 by Serhiy Storchaka (Segev Finer) in branch 'master':
bpo-30567: Fix refleak in sys.getwindowsversion (bpo-1940)
https://github.com/python/cpython/commit/48fb766f70d9ca9d5934cbddbe8d8e7972cb6343

**Comment by serhiy-storchaka** [comment]
New changeset 68e5af89d46db6250a0fa7fe4249c66f866faff8 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30567: Fix refleak in sys.getwindowsversion (GH-1940) (bpo-1970)
https://github.com/python/cpython/commit/68e5af89d46db6250a0fa7fe4249c66f866faff8

**Comment by serhiy-storchaka** [comment]
New changeset 86f8f1f05cd5822b4a4031b90cfdbe5fa1b1159e by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30567: Fix refleak in sys.getwindowsversion (GH-1940) (bpo-1971)
https://github.com/python/cpython/commit/86f8f1f05cd5822b4a4031b90cfdbe5fa1b1159e

**Comment by serhiy-storchaka** [comment]
Thank you for your patch Segev!

**Comment by vstinner** [comment]
The bpo-30546 has been marked as a duplicate of this issue.
