### ISSUE TITLE
issubclass segfaults on objects with weird __getattr__

### ISSUE THREAD

**Issue by c76257d7-ce70-46d8-9cc4-60e5210fac74** [python/cpython#74755]
BPO | [30570](https://bugs.python.org/issue30570)
--- | :---
Nosy | @gpshead, @db3l, @cfbolz, @bitdancer, @ambv, @serhiy-storchaka, @nicoddemus, @DimitrisJim, @mlouielu, @pablogsal, @miss-islington, @sweeneyde, @iritkatriel
PRs | <li>python/cpython#29017</li><li>python/cpython#29048</li><li>python/cpython#29175</li><li>python/cpython#29178</li><li>python/cpython#29258</li><li>python/cpython#29414</li><li>python/cpython#29415</li>
Files | <li>[segfault.crash](https://bugs.python.org/file46924/segfault.crash "Uploaded as text/plain at 2017-06-05.00:25:16 by Daniel Lepage"): Crash Log</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2021-11-04.20:53:21.931>
created_at = <Date 2017-06-05.00:25:34.296>
labels = ['interpreter-core', '3.10', '3.9', 'type-crash', '3.11']
title = 'issubclass segfaults on objects with weird __getattr__'
updated_at = <Date 2021-11-15.05:42:14.836>
user = 'https://bugs.python.org/DanielLepage'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-15.05:42:14.836>
actor = 'Dennis Sweeney'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2021-11-04.20:53:21.931>
closer = 'lukasz.langa'
components = ['Interpreter Core']
creation = <Date 2017-06-05.00:25:34.296>
creator = 'Daniel Lepage'
dependencies = []
files = ['46924']
hgrepos = []
issue_num = 30570
keywords = ['patch']
message_count = 22.0
messages = ['295150', '295151', '295152', '295153', '295179', '295181', '401381', '404151', '404152', '404157', '404158', '404829', '404831', '405144', '405173', '405750', '405753', '405754', '405755', '406328', '406330', '406340']
nosy_count = 14.0
nosy_names = ['gregory.p.smith', 'db3l', 'Carl.Friedrich.Bolz', 'r.david.murray', 'lukasz.langa', 'serhiy.storchaka', 'Bruno Oliveira', 'Daniel Lepage', 'Jim Fasarakis-Hilliard', 'louielu', 'pablogsal', 'miss-islington', 'Dennis Sweeney', 'iritkatriel']
pr_nums = ['29017', '29048', '29175', '29178', '29258', '29414', '29415']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30570'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by c76257d7-ce70-46d8-9cc4-60e5210fac74** [comment]
The following code causes a segmentation fault:
class Failure(object):
    def \_\_getattr__(self, attr):
        return (self, None)
issubclass(Failure(), int)

I am running a macbook pro, OS X 10.12.4, and have observed the problem in python 3.5.2, 3.6.0, and 3.6.1.

It appears that returning (self,) causes it to go into an infinite loop attempting to get `x.__bases__`, and returning `(self, y)` for any value `y` causes it to attempt to get `x.__bases__` 262,030 times and then segfault.

A crash log is attached.

**Comment by c76257d7-ce70-46d8-9cc4-60e5210fac74** [comment]
I tried it on python 2.7.12 and python 2.6.9 since I had them lying around and got the same behavior.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
I can reproduce this bugs on 3.7, Linux.

```pycon
Python 3.7.0a0 (heads/master:d3bedf356a, Jun  5 2017, 10:21:52) 
[GCC 6.3.1 20170306] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> class Foo(object):
...  def __getattr__(self, attr):
...   return (self, None)
... 
>>> issubclass(Foo(), int)
```


[1]    21897 segmentation fault (core dumped)  ./python

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Without this segfault, I think you do a wrong operation. In other cases, for example:

```pycon
>>> issubclass(10, int)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: issubclass() arg 1 must be a class
```



`issubclass` will return TypeError on instance, if you test as `issubclass(Failure, int)` or `issubclass(Failure().__class__, int`, it should get the correct answer.

**Comment by bitdancer** [comment]
Yes, but we try to make it not possible to segfault the interpreter with pure python code that isn't intentionally mucking with C-level stuff, so this is a bug we would like to fix.

**Comment by serhiy-storchaka** [comment]
This looks as yet one example of issues similar of bpo-14010.
