### ISSUE TITLE
How to install cmake?

### ISSUE THREAD

**Issue by a4b1e036-3670-4583-a7e7-430733cd6fc2** [python/cpython#74758]
BPO | [30573](https://bugs.python.org/issue30573)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-05.12:34:09.827>
created_at = <Date 2017-06-05.12:30:59.605>
labels = ['type-bug']
title = 'How to install cmake?'
updated_at = <Date 2017-06-05.12:40:43.165>
user = 'https://bugs.python.org/Dingo64'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-05.12:40:43.165>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-05.12:34:09.827>
closer = 'Dingo64'
components = []
creation = <Date 2017-06-05.12:30:59.605>
creator = 'Dingo64'
dependencies = []
files = []
hgrepos = []
issue_num = 30573
keywords = []
message_count = 3.0
messages = ['295182', '295183', '295186']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Dingo64']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30573'
versions = ['Python 3.5']
```

</p></details>

**Comment by a4b1e036-3670-4583-a7e7-430733cd6fc2** [comment]
When I try to use pip to install something it says it cannot because it doesn't make cmake. When I try to install cmake:

```pytb
C:\Python35>pip3 install cmake
Collecting cmake
  Downloading cmake-0.7.0.tar.gz (29.2MB)
    100% |################################| 29.2MB 14kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\7\AppData\Local\Temp\pip-build-kudn0eog\cmake\setup.py", li
ne 7, in <module>
        from skbuild import setup
    ImportError: No module named 'skbuild'
```


    \----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\\Users\\7\\AppDat
a\\Local\\Temp\\pip-build-kudn0eog\\cmake
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and.

C:\\Python35\>pip3 install skbuild
Collecting skbuild
  Could not find a version that satisfies the requirement skbuild (from versions
: )
No matching distribution found for skbuild

**Comment by a4b1e036-3670-4583-a7e7-430733cd6fc2** [comment]
I did:
python -m pip install --upgrade pip

and then
pip3 install cmake
went OK.

So I would suggest to change notices like "You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' comm
and." into errors or warning so they seem more like something user has to do rather than something he might consider doing.

**Comment by bitdancer** [comment]
The pip issue tracker is at https://github.com/pypa/pip/issues if you want to suggest this, but I doubt it will be accepted.  The action \*is* something optional.
