### ISSUE TITLE
Python interpreter crashes on macOS

### ISSUE THREAD

**Issue by 461cf981-bfb7-41f7-acb2-8ecf89b62905** [python/cpython#74760]
BPO | [30575](https://bugs.python.org/issue30575)
--- | :---
Nosy | @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-09.15:34:21.829>
created_at = <Date 2017-06-05.16:28:08.053>
labels = ['OS-mac', 'invalid', 'type-crash']
title = 'Python interpreter crashes on macOS'
updated_at = <Date 2017-06-09.15:34:21.827>
user = 'https://bugs.python.org/YiboWang'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.15:34:21.827>
actor = 'Yibo Wang'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-09.15:34:21.829>
closer = 'Yibo Wang'
components = ['macOS']
creation = <Date 2017-06-05.16:28:08.053>
creator = 'Yibo Wang'
dependencies = []
files = []
hgrepos = []
issue_num = 30575
keywords = []
message_count = 3.0
messages = ['295203', '295205', '295544']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'Yibo Wang']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30575'
versions = ['Python 3.6']
```

</p></details>

**Comment by 461cf981-bfb7-41f7-acb2-8ecf89b62905** [comment]
I am writing python wrapper for rust library, everything goes fine until execution finishes.

"Python quit unexpectedly"
[1]    25805 segmentation fault  python3

To reproduce, download code from GitHub repo provided by this blog(https://kushaldas.in/posts/writing-python-extensions-in-rust.html), then follow the section "Building the Python extension".

macOS Sierra 10.12.5 (16F73)
Python 3.6.1 via Homebrew
rustc 1.17.0 (56124baa9 2017-04-24)
(This issue won't appear on Windows 10 and Ubuntu 16.04)

**Comment by ned-deily** [comment]
Sorry but, without more information, no one is likely to want to try to pursue this issue.  There are too many components, Python and non-Python, here that could cause a crash and trying to interface to other libraries using extensions like cffi (and ctypes) is always risky.  Including the macOS stack dump trace that may be produced by the segfault would at least give some clues as to where the problem is occurring; check in \~/Library/Log and /Library/Log.

**Comment by 461cf981-bfb7-41f7-acb2-8ecf89b62905** [comment]
It's a bug from cffi because the interpreter won't crash when using ctypes only without cffi.
