### ISSUE TITLE
docs mention datetuil presumably it should be dateutil

### ISSUE THREAD

**Issue by 310dd13a-adf5-42f8-b3ef-a4a4f2d763e3** [python/cpython#74768]
BPO | [30583](https://bugs.python.org/issue30583)
--- | :---
Nosy | @wimglenn, @Mariatta
PRs | <li>python/cpython#1972</li><li>python/cpython#1974</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-06.19:32:47.873>
created_at = <Date 2017-06-06.17:27:29.011>
labels = ['type-feature', '3.7', 'docs']
title = 'docs mention datetuil presumably it should be dateutil'
updated_at = <Date 2017-06-06.19:32:47.872>
user = 'https://github.com/wimglenn'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-06.19:32:47.872>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-06.19:32:47.873>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-06.17:27:29.011>
creator = 'wim.glenn'
dependencies = []
files = []
hgrepos = []
issue_num = 30583
keywords = []
message_count = 4.0
messages = ['295279', '295286', '295295', '295296']
nosy_count = 3.0
nosy_names = ['docs@python', 'wim.glenn', 'Mariatta']
pr_nums = ['1972', '1974']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30583'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 310dd13a-adf5-42f8-b3ef-a4a4f2d763e3** [comment]
Typo from https://github.com/python/cpython/commit/94c8a3f91fbba72845706853d28bd5af8fc11875#diff-5a85d656ffad06e86bee33767ae24f33R1852 went unnoticed and is present in official docs 

https://docs.python.org/3.6/library/datetime.html#tzinfo-objects 

https://docs.python.org/3.7/library/datetime.html#tzinfo-objects

**Comment by Mariatta** [comment]
New changeset 53f2af16551eb3a080da313257603c31ef8b93b4 by Mariatta (wim glenn) in branch 'master':
bpo-30583: Fix typo in datetime dateutil documentation (GH-1972)
https://github.com/python/cpython/commit/53f2af16551eb3a080da313257603c31ef8b93b4

**Comment by Mariatta** [comment]
New changeset b25b7254d909697bb7f3aa893b740cb650547cb6 by Mariatta (wim glenn) in branch '3.6':
bpo-30583: Fix typo in datetime dateutil documentation (GH-1972) (GH-1974)
https://github.com/python/cpython/commit/b25b7254d909697bb7f3aa893b740cb650547cb6

**Comment by Mariatta** [comment]
Thanks wim glenn :)
