### ISSUE TITLE
test_os fails on non-English (Russian) Windows

### ISSUE THREAD

**Issue by 1cb85035-97d8-42c3-a287-2706aee5fe65** [python/cpython#74769]
BPO | [30584](https://bugs.python.org/issue30584)
--- | :---
Nosy | @vstinner, @denis-osipov
PRs | <li>python/cpython#1980</li><li>python/cpython#1999</li><li>python/cpython#2000</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-08.12:33:42.197>
created_at = <Date 2017-06-07.07:39:23.759>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_os fails on non-English (Russian) Windows'
updated_at = <Date 2017-06-08.12:38:43.389>
user = 'https://github.com/denis-osipov'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-08.12:38:43.389>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-08.12:33:42.197>
closer = 'denis-osipov'
components = ['Tests']
creation = <Date 2017-06-07.07:39:23.759>
creator = 'denis-osipov'
dependencies = []
files = []
hgrepos = []
issue_num = 30584
keywords = []
message_count = 9.0
messages = ['295315', '295316', '295322', '295358', '295359', '295411', '295422', '295425', '295433']
nosy_count = 2.0
nosy_names = ['vstinner', 'denis-osipov']
pr_nums = ['1980', '1999', '2000']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30584'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
test_os fails on non-English (Russian) Windows 7 Home Extended 6.1.7601 x64

\======================================================================
ERROR: test_access_denied (test.test_os.StatAttributeTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\repos\cpython\lib\test\test_os.py", line 476, in test_access_denied
    creationflags=DETACHED_PROCESS
  File "C:\repos\cpython\lib\subprocess.py", line 293, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['icacls.exe', 'C:\\Users\\User\
```


\\AppData\\\\Local\\\\Temp\\\\@test_6804_tmp', '/deny', 'Users:(S)']' returned non-zero 

exit status 1332.

\----------------------------------------------------------------------
Ran 250 tests in 5.120s

FAILED (errors=1, skipped=92)
test_os failed

1 test failed:
    test_os

Total duration: 5 sec
Tests result: FAILURE

There is no group BUILTIN\\Users on my Windows. There is BUILTIN\\Пользователи instead.

**Comment by vstinner** [comment]
> exit status 1332.

On the Internet, I found:

1332 	No mapping between account names and security IDs was done.

The unit test:

    @unittest.skipUnless(sys.platform == "win32", "Win32 specific tests")
    def test_access_denied(self):
        # Default to FindFirstFile WIN32_FIND_DATA when access is
        # denied. See bpo-28075.
        # os.environ['TEMP'] should be located on a volume that
        # supports file ACLs.
        fname = os.path.join(os.environ['TEMP'], self.fname)
        self.addCleanup(support.unlink, fname)
        create_file(fname, b'ABC')
        # Deny the right to [S]YNCHRONIZE on the file to
        # force CreateFile to fail with ERROR_ACCESS_DENIED.
        DETACHED_PROCESS = 8
        subprocess.check_call(
            ['icacls.exe', fname, '/deny', 'Users:(S)'],
            creationflags=DETACHED_PROCESS
        )
        result = os.stat(fname)
        self.assertNotEqual(result.st_size, 0)

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Using the numeric SID instead of localized name in test_access_denied works for me (I've made PR).

**Comment by vstinner** [comment]
New changeset 897bba75632dfce87c355e3cd4700468357715a7 by Victor Stinner (Denis Osipov) in branch 'master':
bpo-30584: Fix test_os fails on non-English Windows (bpo-1980)
https://github.com/python/cpython/commit/897bba75632dfce87c355e3cd4700468357715a7

**Comment by vstinner** [comment]
I merged your fix. Thanks!

Let's wait for Windows buildbots. If tests pass on buildbots, the change should be backported to other branches impacted by the bug.

http://buildbot.python.org/all/waterfall?category=3.x.stable&category=3.x.unstable

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Tests on Windows buildbots passed. I've made PR for 3.5 and 3.6 backporting.

**Comment by vstinner** [comment]
New changeset ca1b66fd059758bbd6e2cc62c8f2adecefe8f942 by Victor Stinner (Denis Osipov) in branch '3.6':
[3.6] bpo-30584: Fix test_os fails on non-English Windows (GH-1980) (bpo-1999)
https://github.com/python/cpython/commit/ca1b66fd059758bbd6e2cc62c8f2adecefe8f942

**Comment by vstinner** [comment]
New changeset a0b9088881b8fcfda864070335b249071508ee0c by Victor Stinner (Denis Osipov) in branch '3.5':
[3.5] bpo-30584: Fix test_os fails on non-English Windows (GH-1980) (bpo-2000)
https://github.com/python/cpython/commit/a0b9088881b8fcfda864070335b249071508ee0c

**Comment by vstinner** [comment]
Thanks Denis Osipov for the fix and backports!
