### ISSUE TITLE
Refcounting mistake in _ssl.c

### ISSUE THREAD

**Issue by njsmith** [python/cpython#74779]
BPO | [30594](https://bugs.python.org/issue30594)
--- | :---
Nosy | @tiran, @alex, @njsmith, @jimjjewett, @serhiy-storchaka, @dstufft
PRs | <li>python/cpython#1992</li><li>python/cpython#1993</li><li>python/cpython#1994</li><li>python/cpython#1997</li>
Files | <li>[demo.py](https://bugs.python.org/file46932/demo.py "Uploaded as text/plain at 2017-06-08.06:13:34 by @njsmith")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-06-09.20:53:34.667>
created_at = <Date 2017-06-08.06:13:35.133>
labels = ['expert-SSL', '3.7', 'type-crash']
title = 'Refcounting mistake in _ssl.c'
updated_at = <Date 2017-06-09.20:53:34.666>
user = 'https://github.com/njsmith'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.20:53:34.666>
actor = 'serhiy.storchaka'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-06-09.20:53:34.667>
closer = 'serhiy.storchaka'
components = ['SSL']
creation = <Date 2017-06-08.06:13:35.133>
creator = 'njs'
dependencies = []
files = ['46932']
hgrepos = []
issue_num = 30594
keywords = []
message_count = 8.0
messages = ['295380', '295381', '295382', '295388', '295408', '295409', '295573', '295574']
nosy_count = 7.0
nosy_names = ['janssen', 'christian.heimes', 'alex', 'njs', 'Jim.Jewett', 'serhiy.storchaka', 'dstufft']
pr_nums = ['1992', '1993', '1994', '1997']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30594'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by njsmith** [comment]
If you pass a server_hostname= that fails IDNA decoding to SSLContext.wrap_socket or SSLContext.wrap_bio, then the SSLContext object has a spurious Py_DECREF called on it, eventually leading to segfaults.

Demo attached.

**Comment by serhiy-storchaka** [comment]
New changeset 65ece7ca2366308fa91a39a8dfa255e6bdce3cca by Serhiy Storchaka (Nathaniel J. Smith) in branch 'master':
bpo-30594: Fixed refcounting in newPySSLSocket (bpo-1992)
https://github.com/python/cpython/commit/65ece7ca2366308fa91a39a8dfa255e6bdce3cca

**Comment by serhiy-storchaka** [comment]
Thank you for your report and patch Nathaniel.

Do you mind to create backporting PRs?

**Comment by njsmith** [comment]
posted backports for 3.5 and 3.6. It looks like 2.7 is actually unaffected, because it doesn't have IDNA support, so there's no failure path in between when the reference is stored and when its INCREFed.

**Comment by serhiy-storchaka** [comment]
New changeset 854f7ba1d5cbb6a42511beae66c8dbe34f2cbcd3 by Serhiy Storchaka (Nathaniel J. Smith) in branch '3.6':
[3.6] bpo-30594: Fixed refcounting in newPySSLSocket (GH-1992) (bpo-1994)
https://github.com/python/cpython/commit/854f7ba1d5cbb6a42511beae66c8dbe34f2cbcd3

**Comment by serhiy-storchaka** [comment]
New changeset 54ba41ecc5711f89841342c5f9dd555ee13404b5 by Serhiy Storchaka (Nathaniel J. Smith) in branch '3.5':
[3.5] bpo-30594: Fixed refcounting in newPySSLSocket (GH-1992) (bpo-1993)
https://github.com/python/cpython/commit/54ba41ecc5711f89841342c5f9dd555ee13404b5

**Comment by 74c4563b-ab1c-43d8-9219-30c4eca796bc** [comment]
Serhiy -- do your last two messages mean that this is now resolved?

**Comment by serhiy-storchaka** [comment]
Yes, this is now resolved, thanks to Nathaniel.
