### ISSUE TITLE
textwrap: placeholder backtracking special case lacks test coverage

### ISSUE THREAD

**Issue by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [python/cpython#74776]
BPO | [30591](https://bugs.python.org/issue30591)
--- | :---
Nosy | @serhiy-storchaka, @jonathaneunice
PRs | <li>python/cpython#1988</li><li>python/cpython#2064</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-07.20:51:14.622>
created_at = <Date 2017-06-07.16:40:44.785>
labels = ['3.7', 'type-feature', 'tests']
title = 'textwrap: placeholder backtracking special case lacks test coverage'
updated_at = <Date 2017-06-10.04:17:35.490>
user = 'https://github.com/jonathaneunice'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.04:17:35.490>
actor = 'jonathaneunice'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-07.20:51:14.622>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-06-07.16:40:44.785>
creator = 'jonathaneunice'
dependencies = []
files = []
hgrepos = []
issue_num = 30591
keywords = []
message_count = 2.0
messages = ['295354', '295368']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'jonathaneunice']
pr_nums = ['1988', '2064']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30591'
versions = ['Python 3.7']
```

</p></details>

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
A rare case in textwrap when max_lines insufficient and textwrap needs to backtrack to a previous line to add the placeholder seems to lack test coverage.

This issue added as prereq for suggesting an additional test. PR imminent.

Code: [Lib/textwrap.py](https://github.com/python/cpython/blob/main/Lib/textwrap.py) (as is)
Test: [Lib/test/test_textwrap.py](https://github.com/python/cpython/blob/main/Lib/test/test_textwrap.py) (extended)

**Comment by serhiy-storchaka** [comment]
New changeset 5edf827c8052958b9d293f75ce8d93b66c1d58da by Serhiy Storchaka (Jonathan Eunice) in branch 'master':
bpo-30591: Added test for textwrap backtracking. (bpo-1988)
https://github.com/python/cpython/commit/5edf827c8052958b9d293f75ce8d93b66c1d58da
