### ISSUE TITLE
Document that sqlite3.Cursor.executescript disregards isolation_level

### ISSUE THREAD

**Issue by e2ebc582-b75f-4d91-b8f9-5cefc7206258** [python/cpython#74778]
BPO | [30593](https://bugs.python.org/issue30593)
--- | :---
Nosy | @berkerpeksag, @jimjjewett, @palaviv, @miss-islington, @erlend-aasland
PRs | <li>python/cpython#26220</li><li>python/cpython#26230</li><li>python/cpython#26231</li>
Files | <li>[issue30593-fix.diff](https://bugs.python.org/file46942/issue30593-fix.diff "Uploaded as text/plain at 2017-06-12.19:33:03 by Noah Levitt")</li><li>[issue30593-test.diff](https://bugs.python.org/file46943/issue30593-test.diff "Uploaded as text/plain at 2017-06-12.19:35:32 by Noah Levitt")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-19.07:40:30.081>
created_at = <Date 2017-06-07.22:26:12.665>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = 'Document that sqlite3.Cursor.executescript disregards isolation_level'
updated_at = <Date 2021-05-19.07:40:30.080>
user = 'https://bugs.python.org/NoahLevitt'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-19.07:40:30.080>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-05-19.07:40:30.081>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-06-07.22:26:12.665>
creator = 'Noah Levitt'
dependencies = []
files = ['46942', '46943']
hgrepos = []
issue_num = 30593
keywords = ['patch']
message_count = 7.0
messages = ['295376', '295567', '295813', '295815', '393908', '393928', '393929']
nosy_count = 7.0
nosy_names = ['docs@python', 'berker.peksag', 'Jim.Jewett', 'palaviv', 'Noah Levitt', 'miss-islington', 'erlendaasland']
pr_nums = ['26220', '26230', '26231']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30593'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by e2ebc582-b75f-4d91-b8f9-5cefc7206258** [comment]
As far as I can tell, sqlite3 executescript() does not respect isolation_level. Is that true? If so, I think it's worth mentioning in the doc. Or maybe it should respect isolation_level, not sure there's any particular reason not to.

**Comment by 74c4563b-ab1c-43d8-9219-30c4eca796bc** [comment]
Do you have a test case that could be used to verify a patch?
(Or even a full patch?)

**Comment by e2ebc582-b75f-4d91-b8f9-5cefc7206258** [comment]
Here's a test case

**Comment by e2ebc582-b75f-4d91-b8f9-5cefc7206258** [comment]
And here's a fix.

Unfortunately I think the change could break people's scripts. If they have isolation_level set (not None) and use executescript(), they will have to issue an explicit call to connection.commit().

executescript() could do the commit itself explicitly after running the sql, I suppose. Then the behavior is much like the old behavior, but at least you get the performance boost of running inside a transaction. (Substantial if you pass 10k insert statements to executescript(), or something like that.)

Or, we could not change the code, and instead change the documentation. The docs could suggest wrapping the sql script with "begin;" and "commit;".
