### ISSUE TITLE
test_queue_feeder_donot_stop_onexc() of test_multiprocessing_spawn fails randomly on x86 Windows7 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74780]
BPO | [30595](https://bugs.python.org/issue30595)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba, @applio, @grzgrzgrz3
PRs | <li>python/cpython#2026</li><li>python/cpython#2027</li><li>python/cpython#2148</li><li>python/cpython#2881</li><li>python/cpython#2883</li><li>python/cpython#5429</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-26.15:54:28.860>
created_at = <Date 2017-06-08.07:40:26.663>
labels = ['3.7', 'tests', 'OS-windows']
title = 'test_queue_feeder_donot_stop_onexc() of test_multiprocessing_spawn fails randomly on x86 Windows7 3.x'
updated_at = <Date 2018-01-29.16:16:17.462>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-29.16:16:17.462>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-26.15:54:28.860>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-06-08.07:40:26.663>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30595
keywords = []
message_count = 15.0
messages = ['295385', '295520', '295525', '295527', '295528', '295631', '295632', '295633', '295855', '295961', '299201', '299243', '299244', '311145', '311146']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower', 'davin', 'grzgrzgrz3']
pr_nums = ['2026', '2027', '2148', '2881', '2883', '5429']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30595'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/712/steps/test/logs/stdio

\======================================================================
ERROR: test_queue_feeder_donot_stop_onexc (test.test_multiprocessing_spawn.WithProcessesTestQueue)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\test\_test_multiprocessing.py", line 767, in test_queue_feeder_donot_stop_onexc
    self.assertTrue(q.get(timeout=0.1))
  File "D:\cygwin\home\db3l\buildarea\3.x.bolen-windows7\build\lib\multiprocessing\queues.py", line 105, in get
    raise Empty
queue.Empty
```

**Comment by vstinner** [comment]
Hum, it may be a regression a recent change like the commit bc50f03db4f58c869b78e98468e374d7e61f1227:
    bpo-30414: multiprocessing.Queue.\_feed do not break from main loop on exc (bpo-1683)

**Comment by 6dc2ace7-63c1-4dd4-a1e8-050515409c65** [comment]
Looks like build bot is too slow for timeout=0.1. 

I am guessing `0.1` is too low because we have wrong condition in Queue.get.

It should be.

```diff
diff --git a/Lib/multiprocessing/queues.py b/Lib/multiprocessing/queues.py
index dda03dd..42e9884 100644
--- a/Lib/multiprocessing/queues.py
+++ b/Lib/multiprocessing/queues.py
@@ -101,7 +101,7 @@ class Queue(object):
             try:
                 if block:
                     timeout = deadline - time.time()
-                    if timeout < 0 or not self._poll(timeout):
+                    if self._poll(timeout):
                         raise Empty
                 elif not self._poll():
                     raise Empty
```


If we successfully acquired self.\_rlock, we should poll no matter how long acquire took.

**Comment by 6dc2ace7-63c1-4dd4-a1e8-050515409c65** [comment]
of course it should be `if not`:

```diff
diff --git a/Lib/multiprocessing/queues.py b/Lib/multiprocessing/queues.py
index dda03dd..514f991 100644
--- a/Lib/multiprocessing/queues.py
+++ b/Lib/multiprocessing/queues.py
@@ -101,7 +101,7 @@ class Queue(object):
             try:
                 if block:
                     timeout = deadline - time.time()
-                    if timeout < 0 or not self._poll(timeout):
+                    if not self._poll(timeout):
                         raise Empty
                 elif not self._poll():
                     raise Empty
```

**Comment by vstinner** [comment]
> I am guessing `0.1` is too low because we have wrong condition in Queue.get. It should be.

I'm not sure that the buildbot took this code path, but I like your suggestion. Checking the reader in non-blocking mode is cheap.

poll() with timeout \< 0 works as poll(0), I checked the UNIX and Windows implementations.

So I proposed your change as a PR, and credited you ;-)
https://github.com/python/cpython/pull/2027

**Comment by vstinner** [comment]
New changeset 1b7863c3b6519c6e134c28cab8b8af0dea43e375 by Victor Stinner in branch 'master':
bpo-30595: Fix multiprocessing.Queue.get(timeout) (bpo-2027)
https://github.com/python/cpython/commit/1b7863c3b6519c6e134c28cab8b8af0dea43e375

**Comment by vstinner** [comment]
Thanks Grzegorz Grzywacz! I commited your idea of fix. Let's if it fixes the issue. It will be hard to check since it seems like the bug was random.

Later, I will backport the fix to other branches.

**Comment by vstinner** [comment]
Let's \*see* if it fixes the issue. It will be hard to check since it seems
like the bug was random.

**Comment by vstinner** [comment]
> New changeset 1b7863c3b6519c6e134c28cab8b8af0dea43e375 by Victor Stinner in branch 'master':
> bpo-30595: Fix multiprocessing.Queue.get(timeout) (bpo-2027)
> https://github.com/python/cpython/commit/1b7863c3b6519c6e134c28cab8b8af0dea43e375

While this change is a nice fix, it isn't enough to make the test stable on slow buildbot: it failed again on the same buildbot,
http://buildbot.python.org/all/builders/x86%20Windows7%203.x/builds/744

If I modify the timeout from 100 ms to 1 ms, the test also fail on Linux on my laptop. So I proposed https://github.com/python/cpython/pull/2148 to increase the timeout from 100 ms to 1 sec.

**Comment by vstinner** [comment]
New changeset 8f6eeaf21cdf4aea25fdefeec814a1ce07453fe9 by Victor Stinner in branch 'master':
bpo-30595: Increase test_queue_feeder_donot_stop_onexc() timeout (bpo-2148)
https://github.com/python/cpython/commit/8f6eeaf21cdf4aea25fdefeec814a1ce07453fe9

**Comment by vstinner** [comment]
New changeset e42339d3a08a8fde3349722def85d7a8e49899be by Victor Stinner in branch '3.6':
[3.6] bpo-30595: Fix multiprocessing.Queue.get(timeout) (bpo-2027) (bpo-2881)
https://github.com/python/cpython/commit/e42339d3a08a8fde3349722def85d7a8e49899be

**Comment by vstinner** [comment]
New changeset ec9a7127b8196dc5ef27c5ee2772ecea7cbb32df by Victor Stinner in branch '2.7':
[3.6] bpo-30595: Fix multiprocessing.Queue.get(timeout) (bpo-2027) (bpo-2881) (bpo-2883)
https://github.com/python/cpython/commit/ec9a7127b8196dc5ef27c5ee2772ecea7cbb32df

**Comment by vstinner** [comment]
I fixed multiprocessing.Queue.get(timeout) in 2.7, 3.6 and master. I close the issue.
