### ISSUE TITLE
Error message incorrect when index is called with keyword argument ("[].index(x=2)")

### ISSUE THREAD

**Issue by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [python/cpython#74785]
BPO | [30600](https://bugs.python.org/issue30600)
--- | :---
Nosy | @larryhastings, @serhiy-storchaka, @SylvainDe, @DimitrisJim
PRs | <li>python/cpython#2051</li>
Files | <li>[git_bisect_bpo30600.txt](https://bugs.python.org/file46939/git_bisect_bpo30600.txt "Uploaded as text/plain at 2017-06-09.12:27:07 by @SylvainDe")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-10.04:57:41.194>
created_at = <Date 2017-06-08.12:25:37.283>
labels = ['interpreter-core', 'easy', 'type-bug', '3.7', 'expert-argument-clinic']
title = 'Error message incorrect when index is called with keyword argument ("[].index(x=2)")'
updated_at = <Date 2017-06-10.04:57:41.192>
user = 'https://github.com/SylvainDe'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-10.04:57:41.192>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-10.04:57:41.194>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Argument Clinic']
creation = <Date 2017-06-08.12:25:37.283>
creator = 'SylvainDe'
dependencies = []
files = ['46939']
hgrepos = []
issue_num = 30600
keywords = ['easy']
message_count = 8.0
messages = ['295427', '295432', '295434', '295437', '295519', '295523', '295610', '295611']
nosy_count = 4.0
nosy_names = ['larry', 'serhiy.storchaka', 'SylvainDe', 'Jim Fasarakis-Hilliard']
pr_nums = ['2051']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30600'
versions = ['Python 3.7']
```

</p></details>

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Issue found while trying to write tests for  https://bugs.python.org/issue30592 .

Issue related to http://bugs.python.org/issue30534 .

The following code:

    [].index(x=2)

should raise the following error:

    TypeError: index() takes no keyword arguments

but currently raises:

    TypeError: index() takes at least 1 argument (0 given)


This is easily reproduced with the following unit test:

```py
    # AssertionError: "^index\(\) takes no keyword arguments$" does not match "index() takes at least 1 argument (0 given)"
    def test_varargs4_kw(self):
        msg = r"^index\(\) takes no keyword arguments$"
        self.assertRaisesRegex(TypeError, msg, [].index, x=2)
```

**Comment by serhiy-storchaka** [comment]
Good catch! This issue is similar to bpo-30534, but caused by generated code.

The solution is easy: make Argument Clinic ([Tools/clinic/clinic.py](https://github.com/python/cpython/blob/main/Tools/clinic/clinic.py)) generating \_PyArg_NoStackKeywords() before \_PyArg_ParseStack() and regenerate all generated by Argument Clinic code (make clinic).

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Can I give this a try or is anyone working on this already ?

**Comment by serhiy-storchaka** [comment]
Yes, pleas do this.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Thanks Serhiy Storchaka for the tip! I am currently investigating how the argument clinic works. I have used git bisect to find when the issue got introduced.

commit fdd42c481edba4261f861fc1dfe24bbd79b5a17a
bpo-20185: Convert list object implementation to Argument Clinic. (#542)

**Comment by serhiy-storchaka** [comment]
This commit only exposed existing bug in Argument Clinic. The same bug should be exposed for other methods that takes no keyword arguments converted to Argument Clinic.

**Comment by serhiy-storchaka** [comment]
New changeset 7445381c606faf20e253da42656db478a4349f8e by Serhiy Storchaka (Sylvain) in branch 'master':
bpo-30600: Fix error messages (condition order in Argument Clinic) (bpo-2051)
https://github.com/python/cpython/commit/7445381c606faf20e253da42656db478a4349f8e

**Comment by serhiy-storchaka** [comment]
The PR LGTM. Thank you for your contribution SylvainDe!
