### ISSUE TITLE
[Windows] os.spawn*() tests of test_os leak references on Windows

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74787]
BPO | [30602](https://bugs.python.org/issue30602)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @eryksun, @zooba
PRs | <li>python/cpython#2184</li><li>python/cpython#2212</li><li>python/cpython#2287</li><li>python/cpython#2357</li><li>python/cpython#2486</li>
Files | <li>[test_os.py](https://bugs.python.org/file46935/test_os.py "Uploaded as text/plain at 2017-06-08.16:18:47 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-23.13:23:03.889>
created_at = <Date 2017-06-08.16:18:47.751>
labels = ['3.7', 'tests', 'OS-windows', 'performance']
title = '[Windows] os.spawn*() tests of test_os leak references on Windows'
updated_at = <Date 2017-06-29.08:53:25.029>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-29.08:53:25.029>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-23.13:23:03.889>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-06-08.16:18:47.751>
creator = 'vstinner'
dependencies = []
files = ['46935']
hgrepos = []
issue_num = 30602
keywords = []
message_count = 12.0
messages = ['295451', '295462', '295508', '295999', '296082', '296086', '296103', '296408', '296707', '296714', '296717', '297264']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = ['2184', '2212', '2287', '2357', '2486']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30602'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The leak can be reproduced with the minimum attached test_os.py:

C:\\haypo\\python\>PCbuild\\amd64\\python_d.exe -m test -R 3:3 test_os
Run tests sequentially
0:00:00 [1/1] test_os
beginning 6 repetitions
123456
......
test_os leaked [2, 2, 2] memory blocks, sum=6
test_os failed

1 test failed:
    test_os

Total duration: 172 ms
Tests result: FAILURE

**Comment by eryksun** [comment]
The memory leak is in os_spawnv_impl and os_spawnve_impl in [Modules/posixmodule.c](https://github.com/python/cpython/blob/main/Modules/posixmodule.c). The call fails with a ValueError when the first argument in the argv list is an empty string, in which case these functions both mistakenly pass i (0) to free_string_array() as the count of strings to free. But the conversion was successful, so it needs to include the current string in the count, i.e. `i + 1`.

The fix for this could also address the following two issues, which are mostly cosmetic in nature. os_spawnve_impl needs its TypeError message to be special cased the same as in os_spawnv_impl, i.e. "spawnve() arg 2 must contain only strings". Currently it uses the default message from the failed conversion: "expected str, bytes or os.PathLike object, not %.200s". Also, its ValueError message needs to reference "spawnve()" instead of "spawnv()".

**Comment by vstinner** [comment]
Eryk: do you want to work on a PR to fix it? It seems like you understand well the bug!

**Comment by vstinner** [comment]
New changeset 526b22657cb18fe79118c2ea68511aca09430c2c by Victor Stinner in branch 'master':
bpo-30602: Fix refleak in os.spawnve() (bpo-2184)
https://github.com/python/cpython/commit/526b22657cb18fe79118c2ea68511aca09430c2c

**Comment by vstinner** [comment]
Oh, I fixed a leak in test_spawnve_noargs() of test_os, but test_spawnv_noargs() still leaks :-) os.spawnv() is very similar to os.spawnve(). https://github.com/python/cpython/pull/2212 fixes os.spawnv() as well.

I tested that "python -m test -R 3:3 test_os" doesn't leak anymore with this second fix.

**Comment by vstinner** [comment]
New changeset 8acb4cf2b3436652568d7a70228b166316181466 by Victor Stinner in branch 'master':
bpo-30602: Fix refleak in os.spawnv() (bpo-2212)
https://github.com/python/cpython/commit/8acb4cf2b3436652568d7a70228b166316181466

**Comment by vstinner** [comment]
It seems like I introduced a bug:
https://github.com/python/cpython/pull/2184#pullrequestreview-44308536

**Comment by vstinner** [comment]
The fixes must be backported to Python 3.6, test_os still leaks references on this branch:

test_os leaked [6, 6, 6] memory blocks, sum=18

**Comment by vstinner** [comment]
New changeset c8d6ab2e25ff212702d387e516e258b1d8c52910 by Victor Stinner in branch 'master':
bpo-30602: Fix lastarg in os.spawnve() (bpo-2287)
https://github.com/python/cpython/commit/c8d6ab2e25ff212702d387e516e258b1d8c52910

**Comment by vstinner** [comment]
New changeset c472fb6b2744b36c7a0823c20e0d5ac9be3ea623 by Victor Stinner in branch '3.6':
bpo-30602: Fix lastarg in os.spawnve() (bpo-2287) (bpo-2357)
https://github.com/python/cpython/commit/c472fb6b2744b36c7a0823c20e0d5ac9be3ea623

**Comment by vstinner** [comment]
Thank you Eryk Sun for the careful reviews! All known issues on os.spawn*() on Windows are now be fixed, so I closed this issue.

**Comment by vstinner** [comment]
New changeset b78fbaaeab9df8cfbbdae3d5faf2d1537d73e43b by Victor Stinner in branch '3.6':
bpo-30602: Fix refleak in os.spawnv() (bpo-2212) (bpo-2486)
https://github.com/python/cpython/commit/b78fbaaeab9df8cfbbdae3d5faf2d1537d73e43b
