### ISSUE TITLE
test_threaded_import leaks references

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74784]
BPO | [30599](https://bugs.python.org/issue30599)
--- | :---
Nosy | @rhettinger, @pitrou, @vstinner, @serhiy-storchaka, @matrixise
PRs | <li>python/cpython#2001</li><li>python/cpython#2029</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.00:44:27.997>
created_at = <Date 2017-06-08.10:57:39.584>
labels = ['3.7', 'tests', 'performance']
title = 'test_threaded_import leaks references'
updated_at = <Date 2017-06-28.00:44:27.996>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-28.00:44:27.996>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.00:44:27.997>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-08.10:57:39.584>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30599
keywords = []
message_count = 9.0
messages = ['295403', '295413', '295421', '295431', '295435', '295440', '295441', '295645', '297086']
nosy_count = 5.0
nosy_names = ['rhettinger', 'pitrou', 'vstinner', 'serhiy.storchaka', 'matrixise']
pr_nums = ['2001', '2029']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30599'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Gentoo%20Refleaks%203.x/builds/28/steps/test/logs/stdio

1:50:39 load avg: 3.66 [302/405/8] test_threaded_import failed -- running: test_tarfile (80 sec)
beginning 6 repetitions
123456
......
test_threaded_import leaked [355866, 185490, 120912] references, sum=662268
test_threaded_import leaked [119138, 62100, 40480] memory blocks, sum=221718


Might be related to bpo-30598 and bpo-30547.

**Comment by vstinner** [comment]
Even when the two latest refleak fixes (ab1cb80b435a34e4f908c97cd2f3a7fe8add6505 and 865de27dd79571a4a5c7a7d22a07fb909c4a9f8e), test_threaded_import still leaks.

haypo@selma$ ./python -m test -R 3:3 -m test_side_effect_import test_threaded_import  
Run tests sequentially
0:00:00 load avg: 0.39 [1/1] test_threaded_import
beginning 6 repetitions
123456
......
test_threaded_import leaked [1374, 1374, 1374] references, sum=4122
test_threaded_import leaked [459, 460, 460] memory blocks, sum=1379
test_threaded_import failed

1 test failed:
    test_threaded_import

Total duration: 392 ms
Tests result: FAILURE

**Comment by vstinner** [comment]
The leak was introduced by the commit 346cbd351ee0dd3ab9cb9f0e4cb625556707877e.

**Comment by vstinner** [comment]
> The leak was introduced by the commit 346cbd351ee0dd3ab9cb9f0e4cb625556707877e.

This commit "bpo-16500: Allow registering at-fork handlers" adds the following code to [Lib/random.py](https://github.com/python/cpython/blob/main/Lib/random.py):

+if hasattr(_os, "fork"):
\+    \_os.register_at_fork(_inst.seed, when='child')

test_threaded_import creates fresh instance of the random module and so os.register_at_fork() is called multiple time with multiple different callbacks.

The problem is that it's not currently possible to remove callbacks. It would be nice to be able to unregister callbacks, at least a private for unit tests.

The minimum would be a os.unregister_at_fork() function.

I would prefer to have get/set functions to be able to restore callbacks once tests complete, but also to detect when an unexpected callback was registered. For example, write a new test in [Lib/test/libregrtest/save_env.py](https://github.com/python/cpython/blob/main/Lib/test/libregrtest/save_env.py) for regrtest.

See also bpo-16500 which added the new API.

**Comment by serhiy-storchaka** [comment]
This make the API and implementation more complex. I prefer making tests not creating several instances of the random module. Or do this in a short-living subprocess.

**Comment by pitrou** [comment]
Agreed with Serhiy.  test_threaded_import should just re-import a module which has less side effects.

**Comment by vstinner** [comment]
With https://github.com/python/cpython/pull/2001 test_threaded_import doesn't leak anymore.

**Comment by vstinner** [comment]
New changeset c5179f6e2dfcc01cf0b977b184f5b8f8ac98fab1 by Victor Stinner in branch 'master':
bpo-30599: Fix test_threaded_import reference leak (bpo-2029)
https://github.com/python/cpython/commit/c5179f6e2dfcc01cf0b977b184f5b8f8ac98fab1

**Comment by vstinner** [comment]
test_threaded_import has been fixed, so I close the issue. Thanks Antoine and Serhiy for the reviews and feedback ;-)

I'm ok to not provide a "unregister" function. At least, until an user complains with a good rationale ;-)
