### ISSUE TITLE
textwrap: declining indent level has no test case

### ISSUE THREAD

**Issue by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [python/cpython#74788]
BPO | [30603](https://bugs.python.org/issue30603)
--- | :---
Nosy | @jonathaneunice, @emilyemorehouse, @Mariatta
PRs | <li>python/cpython#2014</li><li>python/cpython#2064</li><li>python/cpython#2206</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/emilyemorehouse'
closed_at = <Date 2017-06-16.02:20:49.024>
created_at = <Date 2017-06-08.21:12:09.339>
labels = ['3.7', 'type-feature', 'library']
title = 'textwrap: declining indent level has no test case'
updated_at = <Date 2017-06-16.02:20:49.024>
user = 'https://github.com/jonathaneunice'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.02:20:49.024>
actor = 'Mariatta'
assignee = 'emilyemorehouse'
closed = True
closed_date = <Date 2017-06-16.02:20:49.024>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-06-08.21:12:09.339>
creator = 'jonathaneunice'
dependencies = []
files = []
hgrepos = []
issue_num = 30603
keywords = []
message_count = 6.0
messages = ['295464', '295746', '295951', '296063', '296111', '296144']
nosy_count = 3.0
nosy_names = ['jonathaneunice', 'emilyemorehouse', 'Mariatta']
pr_nums = ['2014', '2064', '2206']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30603'
versions = ['Python 3.7']
```

</p></details>

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
The case where textwrap.dedent() handles a declining indent level, requiring it to revise its margin estimate downward, remains untested.

This issue is opened in support of an imminent PR that adds an appropriate test.

**Comment by emilyemorehouse** [comment]
Good catch. We should also add additional tests for a declining indentation level with a blank line and a declining indentation with a whitespace only line, as it is a pattern followed throughout the dedent tests. 

It should be noted that [PR 2014](https://github.com/python/cpython/pull/2014) is the appropriate pull request for this issue. [PR 2064](https://github.com/python/cpython/pull/2064) is for a different, though related, issue (https://bugs.python.org/issue30620).

**Comment by Mariatta** [comment]
New changeset 601483d3b8a0433ca25f7fd6beea2cef674be039 by Mariatta (Jonathan Eunice) in branch 'master':
bpo-30603: Add test case to textwrap.dedent (GH-2014)
https://github.com/python/cpython/commit/601483d3b8a0433ca25f7fd6beea2cef674be039

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
@emilyemorehouse Added new tests per your request:

https://github.com/python/cpython/pull/2206

**Comment by emilyemorehouse** [comment]
Looks great, thanks for the updates.

Mariatta, can you get this merged in?

**Comment by Mariatta** [comment]
New changeset 214f7eed7640f873223427c02a95a70775d2b396 by Mariatta (Jonathan Eunice) in branch 'master':
bpo-30603: add tests to textwrap.dedent (GH-2206)
https://github.com/python/cpython/commit/214f7eed7640f873223427c02a95a70775d2b396
