### ISSUE TITLE
Windows HTML Help always opens maximized

### ISSUE THREAD

**Issue by f7a29477-11b6-4add-a132-918438c57010** [python/cpython#74796]
BPO | [30611](https://bugs.python.org/issue30611)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @chrullrich

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-09.17:31:27.361>
created_at = <Date 2017-06-09.09:20:31.289>
labels = ['invalid', 'type-feature', '3.7', 'OS-windows']
title = 'Windows HTML Help always opens maximized'
updated_at = <Date 2017-06-09.17:31:27.360>
user = 'https://github.com/chrullrich'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-09.17:31:27.360>
actor = 'chrullrich'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-09.17:31:27.361>
closer = 'chrullrich'
components = ['Windows']
creation = <Date 2017-06-09.09:20:31.289>
creator = 'chrullrich'
dependencies = []
files = []
hgrepos = []
issue_num = 30611
keywords = []
message_count = 4.0
messages = ['295503', '295538', '295556', '295560']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'steve.dower', 'chrullrich']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30611'
versions = ['Python 3.7']
```

</p></details>

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
The CHM help files on Windows always open maximized. I would prefer they opened in a regular window instead, because the current behavior is annoying.

Fix: In [Tools/msi/doc/doc.wxs](https://github.com/python/cpython/blob/main/Tools/msi/doc/doc.wxs) line 34, change 'Show="maximized"' to 'Show="normal"'.

**Comment by zware** [comment]
Does 'Show="normal"' cause the usual behavior of "do whatever it was doing when last closed"?  Does 'Show=' need to be specified?

Would you like to submit a PR?

**Comment by zooba** [comment]
Opening in normal size (i.e. randomly positioned somewhere on the screen) is equally annoying.

PR is welcome, but I won't be approving it. Someone else might.

Certainly doesn't need to be backported - this is not a bug.

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
I'll have to start with the ceterae again, won't I? OK, since you asked:

Ceterum censeo: This behavior could have been easily adapted to differing local requirements if MSI had been used as the distribution package format by appropriately transforming  the Shortcut table at install time, but burn bundles do not expose an interface to apply transforms to individual component MSIs, needlessly disabling this unique advantage of the Windows Installer technology.

(Apologies to people who know Latin. Unless I'm really lucky here.)

Not sure if the tracker will let me close the bug myself; if it doesn't, know that I have tried.
