### ISSUE TITLE
Unusual Windows registry path syntax

### ISSUE THREAD

**Issue by f7a29477-11b6-4add-a132-918438c57010** [python/cpython#74797]
BPO | [30612](https://bugs.python.org/issue30612)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @chrullrich, @csabella, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#20281</li><li>python/cpython#22815</li><li>python/cpython#22816</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-20.12:01:28.901>
created_at = <Date 2017-06-09.09:33:23.987>
labels = ['3.8', 'type-feature', '3.7', 'OS-windows', 'docs']
title = 'Unusual Windows registry path syntax'
updated_at = <Date 2020-10-20.12:23:43.163>
user = 'https://github.com/chrullrich'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-20.12:23:43.163>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-10-20.12:01:28.901>
closer = 'steve.dower'
components = ['Documentation', 'Windows']
creation = <Date 2017-06-09.09:33:23.987>
creator = 'chrullrich'
dependencies = []
files = []
hgrepos = []
issue_num = 30612
keywords = ['patch']
message_count = 8.0
messages = ['295505', '295555', '295557', '295558', '339865', '379117', '379119', '379121']
nosy_count = 9.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'steve.dower', 'chrullrich', 'cheryl.sabella', 'ZackerySpytz', 'miss-islington']
pr_nums = ['20281', '22815', '22816']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30612'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
In 3.6.1, the manual, section 3.1.3, has this to say:

"Your administrator will need to activate the “Enable Win32 long paths” group policy, or set the registry value HKEY_LOCAL_MACHINE\\SYSTEM\\CurrentControlSet\\Control\\FileSystem@LongPathsEnabled to 1."

Separating a value name from the key path with an @-sign, which is what the above is doing, is something I have never before seen anywhere. I suggest changing it by either:

- replacing the instructions for the manual change with a link to \<https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx#maxpath\> or a more suitable reference (I could not find a KB article when I looked)

- rewording it as, e.g.,

  ... in the registry key HKEY_...FileSystem, set the REG_DWORD value LongPathsEnabled to 1

  The value type could be left out; the value is predefined on all platforms where it will be effective.

**Comment by zooba** [comment]
Pull requests welcome, but as someone who lives in the Windows API day in and day out, I can vouch for it being the normal abbreviated way of specifying a fully qualified registry value.

**Comment by f7a29477-11b6-4add-a132-918438c57010** [comment]
Out of curiosity, can you point me to an example or two?

I have been living with, though not in, Win32 for quite a few years myself, and I can say with certainty that I have never seen this notation before in my life.

Other than that, PR on the way soonish.

**Comment by zooba** [comment]
There's a handful of references in https://docs.microsoft.com/en-us/visualstudio/ide/walkthrough-creating-a-multiple-computer-build-environment, though TBH most of the docs written by actual doc writers use more complicated sentences to avoid it.

It's also the syntax used by MSBuild, which is probably mostly why I think it's normal.
