### ISSUE TITLE
selectors should use bare except clauses

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#74809]
BPO | [30624](https://bugs.python.org/issue30624)
--- | :---
Nosy | @gvanrossum, @vstinner, @giampaolo, @berkerpeksag, @serhiy-storchaka, @1st1, @Mariatta
PRs | <li>python/cpython#2082</li><li>python/cpython#2108</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-12.12:52:28.737>
created_at = <Date 2017-06-10.18:11:44.214>
labels = ['3.7', 'expert-asyncio']
title = 'selectors should use bare except clauses'
updated_at = <Date 2017-06-12.12:52:28.734>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-12.12:52:28.734>
actor = 'giampaolo.rodola'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-12.12:52:28.737>
closer = 'giampaolo.rodola'
components = ['asyncio']
creation = <Date 2017-06-10.18:11:44.214>
creator = 'giampaolo.rodola'
dependencies = []
files = []
hgrepos = []
issue_num = 30624
keywords = []
message_count = 8.0
messages = ['295648', '295682', '295685', '295699', '295701', '295706', '295772', '295773']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'vstinner', 'giampaolo.rodola', 'neologix', 'berker.peksag', 'serhiy.storchaka', 'yselivanov', 'Mariatta']
pr_nums = ['2082', '2108']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30624'
versions = ['Python 3.7']
```

</p></details>

**Comment by giampaolo** [comment]
Right now it uses "except Exception: ...; raise" which does not take KeyboardInterrupt and SystemExit into account, leaving the fd in a bad state (it's not unregister()ed).

**Comment by Mariatta** [comment]
I removed 3.4 from versions, since this is not a security fix.

Does this need backport to 3.5 too? 
Or only 3.6?

**Comment by serhiy-storchaka** [comment]
Look also at KqueueSelector.modify(). And the mentioning of SystemError in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is wrong, it is a subclass of Exception.

**Comment by vstinner** [comment]
Serhiy Storchaka added the comment:

Look also at KqueueSelector.modify(). And the mentioning of SystemError in
[Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) is wrong, it is a subclass of Exception.

I guess that he means SystemExit ;-)

**Comment by serhiy-storchaka** [comment]
My apologies. The [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) entry is correct. But only 2 of 3 "except Exception" are fixed.

**Comment by giampaolo** [comment]
> But only 2 of 3 "except Exception" are fixed.

My bad. New PR:
https://github.com/python/cpython/pull/2108

**Comment by giampaolo** [comment]
New changeset ced36a993fcfd1c76637119d31c03156a8772e11 by Giampaolo Rodola in branch 'master':
bpo-30624 remaining bare except (bpo-2108)
https://github.com/python/cpython/commit/ced36a993fcfd1c76637119d31c03156a8772e11

**Comment by giampaolo** [comment]
I see that on 3.6 except BaseException: is used, so the backport should not be necessary.
