### ISSUE TITLE
Cannot use functional API to create enum with zero values

### ISSUE THREAD

**Issue by 6c53f22f-246d-4255-aab6-e377bdeb50f4** [python/cpython#74801]
BPO | [30616](https://bugs.python.org/issue30616)
--- | :---
Nosy | @vstinner, @ethanfurman, @gerritholl
PRs | <li>python/cpython#2304</li><li>python/cpython#2324</li><li>python/cpython#2888</li><li>python/cpython#2889</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2017-08-17.08:57:32.952>
created_at = <Date 2017-06-09.17:30:17.874>
labels = ['3.7', 'library']
title = 'Cannot use functional API to create enum with zero values'
updated_at = <Date 2017-08-17.08:57:32.934>
user = 'https://github.com/gerritholl'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-17.08:57:32.934>
actor = 'vstinner'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2017-08-17.08:57:32.952>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-06-09.17:30:17.874>
creator = 'Gerrit.Holl'
dependencies = []
files = []
hgrepos = []
issue_num = 30616
keywords = []
message_count = 5.0
messages = ['295559', '296567', '296569', '296776', '300404']
nosy_count = 3.0
nosy_names = ['vstinner', 'ethan.furman', 'Gerrit.Holl']
pr_nums = ['2304', '2324', '2888', '2889']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30616'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6c53f22f-246d-4255-aab6-e377bdeb50f4** [comment]
The OO API allows to create empty enums, i.e. without any values.  However, the functional API does not, as this will result in an IndexError as shown below:

In [1]: import enum

In [2]: class X(enum.IntFlag): pass

In [3]: Y = enum.IntFlag("Y", [])
\---------------------------------------------------------------------------
```pytb
IndexError                                Traceback (most recent call last)
<ipython-input-3-1fda5945e0b2> in <module>()
----> 1 Y = enum.IntFlag("Y", [])
```


\~/lib/python3.6/enum.py in \_\_call__(cls, value, names, module, qualname, type, start)
    291             return cls.\_\_new__(cls, value)
    292         # otherwise, functional API: we're creating a new Enum type
--\> 293         return cls.\_create_(value, names, module=module, qualname=qualname, type=type, start=start)
    294 
    295     def \_\_contains__(cls, member):

\~/lib/python3.6/enum.py in \_create_(cls, class_name, names, module, qualname, type, start)
    382         if isinstance(names, str):
    383             names = names.replace(',', ' ').split()
--\> 384         if isinstance(names, (tuple, list)) and isinstance(names[0], str):
    385             original_names, names = names, []
    386             last_values = []

IndexError: list index out of range

**Comment by ethanfurman** [comment]
New changeset dcc8ce44c74492670e6bfbde588a2acbf8f365e0 by ethanfurman (Dong-hee Na) in branch 'master':
bpo-30616: Functional API of enum allows to create empty enums. (bpo-2304)
https://github.com/python/cpython/commit/dcc8ce44c74492670e6bfbde588a2acbf8f365e0

**Comment by ethanfurman** [comment]
3.7 fixed, now need 3.6.

**Comment by ethanfurman** [comment]
New changeset 504b95047a8ada06ab630abce55ac2f85566ca37 by ethanfurman (Dong-hee Na) in branch '3.6':
[3.6] bpo-30616: Functional API of enum allows to create empty enums. (bpo-2304) (bpo-2324)
https://github.com/python/cpython/commit/504b95047a8ada06ab630abce55ac2f85566ca37

**Comment by vstinner** [comment]
Thanks for the bugreport Gerrit Holl and thanks for fixes Dong-hee Na!
