### ISSUE TITLE
import json before using json module in tutorial Input and Output

### ISSUE THREAD

**Issue by a5039892-fb56-49e1-9a60-06ac1b83f800** [python/cpython#74806]
BPO | [30621](https://bugs.python.org/issue30621)
--- | :---
Nosy | @Mariatta, @suketa
PRs | <li>python/cpython#2074</li><li>python/cpython#2118</li><li>python/cpython#2119</li><li>python/cpython#2120</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-12.02:01:01.941>
created_at = <Date 2017-06-10.09:17:03.605>
labels = ['3.7', 'docs']
title = 'import json before using json module in tutorial Input and Output'
updated_at = <Date 2017-06-12.02:01:01.939>
user = 'https://github.com/suketa'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-12.02:01:01.939>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-12.02:01:01.941>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-10.09:17:03.605>
creator = 'suketa'
dependencies = []
files = []
hgrepos = []
issue_num = 30621
keywords = []
message_count = 6.0
messages = ['295626', '295736', '295737', '295738', '295739', '295740']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'suketa']
pr_nums = ['2074', '2118', '2119', '2120']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30621'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a5039892-fb56-49e1-9a60-06ac1b83f800** [comment]
In Input and Output tutorial, use json module without `import json`.

**Comment by Mariatta** [comment]
New changeset 1dbce04d0e3e93b715eb0d8024da396361759d16 by Mariatta (suketa) in branch 'master':
bpo-30621: Update Input Output Tutorial Example(GH-2074)
https://github.com/python/cpython/commit/1dbce04d0e3e93b715eb0d8024da396361759d16

**Comment by Mariatta** [comment]
New changeset 47c9decb5feabb51416deffd2098ee31d73f1f5f by Mariatta in branch '3.6':
bpo-30621: Update Input Output Tutorial Example(GH-2074) (GH-2118)
https://github.com/python/cpython/commit/47c9decb5feabb51416deffd2098ee31d73f1f5f

**Comment by Mariatta** [comment]
New changeset 7563b0508172cedb5e6a95d05e9122f1a0bfcd86 by Mariatta in branch '3.5':
bpo-30621: Update Input Output Tutorial Example(GH-2074) (GH-2119)
https://github.com/python/cpython/commit/7563b0508172cedb5e6a95d05e9122f1a0bfcd86

**Comment by Mariatta** [comment]
New changeset 107949cb87d0f064bd9bcd39dc2a5e7266bfee30 by Mariatta in branch '2.7':
bpo-30621: Update Input Output Tutorial Example(GH-2074) (GH-2120)
https://github.com/python/cpython/commit/107949cb87d0f064bd9bcd39dc2a5e7266bfee30

**Comment by Mariatta** [comment]
Thanks! :)
