### ISSUE TITLE
textwrap: dedent contains logic that can never execute

### ISSUE THREAD

**Issue by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [python/cpython#74805]
BPO | [30620](https://bugs.python.org/issue30620)
--- | :---
Nosy | @serhiy-storchaka, @jonathaneunice, @emilyemorehouse, @Mariatta
PRs | <li>python/cpython#2064</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/emilyemorehouse'
closed_at = <Date 2017-06-16.02:22:31.187>
created_at = <Date 2017-06-10.04:09:38.061>
labels = ['3.7', 'type-feature', 'library']
title = 'textwrap: dedent contains logic that can never execute'
updated_at = <Date 2017-06-16.02:22:31.186>
user = 'https://github.com/jonathaneunice'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.02:22:31.186>
actor = 'Mariatta'
assignee = 'emilyemorehouse'
closed = True
closed_date = <Date 2017-06-16.02:22:31.187>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-06-10.04:09:38.061>
creator = 'jonathaneunice'
dependencies = []
files = []
hgrepos = []
issue_num = 30620
keywords = []
message_count = 4.0
messages = ['295606', '295731', '295733', '296145']
nosy_count = 4.0
nosy_names = ['serhiy.storchaka', 'jonathaneunice', 'emilyemorehouse', 'Mariatta']
pr_nums = ['2064']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30620'
versions = ['Python 3.7']
```

</p></details>

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
textwrap.dedent contains a bit of code that appears logical at first blush, but in fact can never execute under any input conditions.

Not only are the lines "dead code," they are the only thing (i.e. only non-debugging lines) now standing in the way of textwrap having 100% test coverage.

Here is the proof: https://gist.github.com/jonathaneunice/86f6a721e48c89e272a778530e8f758c

A PR removing the bogus lines is imminent.

**Comment by emilyemorehouse** [comment]
The logic in your proof is certainly sound. The only time that the else statement within Clause 4 (to use terminology from the proof) would execute is either 
  1) if margin is equal to indent, which is handled in Clause 2, or 
  2) if the margin is None, which is handled in Clause 1.

I support this PR. On a related note, I feel that the existing comments could clearer illustrate this. Specifically, it is unclear that Clause 2 will also catch cases where margin and indent are equal.

**Comment by emilyemorehouse** [comment]
Jonathan, could you improve the comments for the dedent function? You have a great understanding of the logic flow from your proof and it would be beneficial to document this to avoid future confusion.

Specifically, it should be clear that Clause 2 inherently handles equivalence for margin and indent and that Clause 4 will always complete with the break statement.

**Comment by Mariatta** [comment]
New changeset 7a801839e9a88bdcac5aaab494b532230fcf7caa by Mariatta (Jonathan Eunice) in branch 'master':
bpo-30620: Remove dead lines from textwrap.dedent (GH-2064)
https://github.com/python/cpython/commit/7a801839e9a88bdcac5aaab494b532230fcf7caa
