### ISSUE TITLE
"SystemError: <class '_io.TextIOWrapper'> returned NULL without setting an error"  from open function

### ISSUE THREAD

**Issue by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [python/cpython#74811]
BPO | [30626](https://bugs.python.org/issue30626)
--- | :---
Nosy | @brettcannon, @ncoghlan, @benjaminp, @ericsnowcurrently, @serhiy-storchaka, @pppery
PRs | <li>python/cpython#2103</li><li>python/cpython#2221</li><li>python/cpython#2222</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-06-15.18:21:52.337>
created_at = <Date 2017-06-10.18:53:58.796>
labels = ['interpreter-core', '3.7', 'library', 'expert-IO', 'type-crash']
title = '"SystemError: <class \'_io.TextIOWrapper\'> returned NULL without setting an error"  from open function'
updated_at = <Date 2017-06-15.18:21:52.336>
user = 'https://github.com/pppery'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.18:21:52.336>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-06-15.18:21:52.337>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Library (Lib)', 'IO']
creation = <Date 2017-06-10.18:53:58.796>
creator = 'ppperry'
dependencies = []
files = []
hgrepos = []
issue_num = 30626
keywords = []
message_count = 7.0
messages = ['295654', '295680', '295681', '295693', '296118', '296119', '296120']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'ncoghlan', 'benjamin.peterson', 'stutzbach', 'eric.snow', 'serhiy.storchaka', 'ppperry']
pr_nums = ['2103', '2221', '2222']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30626'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [comment]
This code (reduced from an example I had of trying to debug code including the module-level code of already imported modules), raises a SystemError:
import builtins
from importlib.machinery import PathFinder
from importlib.util import find_spec
import importlib
import sys
import \_imp
dct={}
def copy_module(module):
    new = type(sys)(module.\_\_name__)
    new.\_\_dict__.update(module.\_\_dict__)
    return new

dct["\_\_builtins__"] = b = copy_module(builtins)

```py
spec = PathFinder.find_spec("_bootstrap",importlib.__path__)
source_bootstrap = type(sys)("_bootstrap");
spec.loader.exec_module(source_bootstrap);
source_bootstrap.__name__ = "importlib._bootstrap";    
new_sys = copy_module(sys)

new_sys.path_hooks = []
new_sys.meta_path = []
new_sys.modules = {
    "importlib._bootstrap":source_bootstrap,
    "importlib._bootstrap_external":importlib._bootstrap_external,
}
b.__import__ = source_bootstrap.__import__
source_bootstrap._install(new_sys,_imp)
dct["__file__"]=__file__
exec("open(__file__)",dct)
```


The actual file passed to the open function doesn't matter, as long as it would work

**Comment by ncoghlan** [comment]
I couldn't reproduce this on 3.7, but I can confirm that 3.6 gives a SystemError with the above code:

```pytb
$ ./python _issue30626.py
Traceback (most recent call last):
  File "_issue30626.py", line 30, in <module>
    exec("open(__file__)",dct)
  File "<string>", line 1, in <module>
SystemError: <class '_io.TextIOWrapper'> returned NULL without setting an error
```


It's plausible this was fixed as part of the interpreter startup refactoring, so I doubt we're going to able to easily isolate the specific change that fixed it :(

**Comment by ncoghlan** [comment]
That said: given that we know it \*is* fixed somewhere in 3.7, it would likely be useful to check the assumption that the startup refactoring fixed it by going to the last commit before that landed and seeing if the error still occurs.

**Comment by serhiy-storchaka** [comment]
In rare circumstances PyImport_Import() could return NULL without raising an error.

It \*isn't* fixed in 3.7.

**Comment by serhiy-storchaka** [comment]
New changeset 145541cfa05394c38cfd64c0be2c5fb382860995 by Serhiy Storchaka in branch 'master':
bpo-30626: Fix error handling in PyImport_Import(). (bpo-2103)
https://github.com/python/cpython/commit/145541cfa05394c38cfd64c0be2c5fb382860995

**Comment by serhiy-storchaka** [comment]
New changeset fab05de21480fc54a5101cf813195cb32724b5ad by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30626: Fix error handling in PyImport_Import(). (GH-2103) (bpo-2221)
https://github.com/python/cpython/commit/fab05de21480fc54a5101cf813195cb32724b5ad

**Comment by serhiy-storchaka** [comment]
New changeset 263dcc39daa74066c2b2fcb007a4bd4f7ec65073 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30626: Fix error handling in PyImport_Import(). (GH-2103) (bpo-2222)
https://github.com/python/cpython/commit/263dcc39daa74066c2b2fcb007a4bd4f7ec65073
