### ISSUE TITLE
IDLE: add unittests to test_autocomplete

### ISSUE THREAD

**Issue by 9da18a29-a07d-4828-a801-24cc911246de** [python/cpython#74817]
BPO | [30632](https://bugs.python.org/issue30632)
--- | :---
Nosy | @terryjreedy, @mlouielu
PRs | <li>python/cpython#2124</li>
Superseder | <li>bpo-30348: IDLE: Add test_autocomplete unittests</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-06-15.03:07:20.856>
created_at = <Date 2017-06-12.08:30:22.830>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: add unittests to test_autocomplete'
updated_at = <Date 2017-10-13.04:42:07.541>
user = 'https://github.com/mlouielu'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-13.04:42:07.541>
actor = 'berker.peksag'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-06-15.03:07:20.856>
closer = 'louielu'
components = ['IDLE']
creation = <Date 2017-06-12.08:30:22.830>
creator = 'louielu'
dependencies = []
files = []
hgrepos = []
issue_num = 30632
keywords = []
message_count = 4.0
messages = ['295755', '295806', '296028', '296061']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'louielu']
pr_nums = ['2124']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30348'
type = 'enhancement'
url = 'https://bugs.python.org/issue30632'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Add unittest to test_open_completions, test_fetch_copmletions, and test_get_entity in test_autocomplete

**Comment by terryjreedy** [comment]
This issue, and in part the patch, appears to be a duplicate of bpo-30348.  What am I missing?  An issue can have multiple PRs, and one can either replace another one that is closed or augment one that must be applied first.

**Comment by terryjreedy** [comment]
Ping.  Please answer question about two PRs.

For bpo-30666, I wrote
1. Test_autocomplete.AutoCompleteTest has a test_method for each method of autocomplete.AutoComplete.  The last 5 test methods are empty ('pass'). Finish them.  A couple of the methods might be usefully split into smaller methods.  Get_entity is actually a function, as 'self' is ignored. After the first else, fetch_completions is also independent of 'self'.  [PR 2011](https://github.com/python/cpython/pull/2011) combines the two blocks into a function that can be moved to run.py.

These method tests should be supplemented by user action tests with live widgets and simulated key events.  Such tests would be black box tests in that they should be independent of the implementation.

I decided to broaden this issue to all autocomplete tests and narrow that one to autocomplete_w tests.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
This is a duplicate of bpo-30348, I forgot there has a exists PR. I'll combine them and finish left 5 unittest in bpo-30348.
