### ISSUE TITLE
Warnings in VS2015 Update 3 32-Bit

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#74816]
BPO | [30631](https://bugs.python.org/issue30631)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @segevfiner
PRs | <li>python/cpython#1963</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-16.03:16:08.515>
created_at = <Date 2017-06-11.22:14:26.541>
labels = ['type-bug', '3.7', 'OS-windows', 'build']
title = 'Warnings in VS2015 Update 3 32-Bit'
updated_at = <Date 2017-06-16.03:16:08.508>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.03:16:08.508>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-16.03:16:08.515>
closer = 'zach.ware'
components = ['Build', 'Windows']
creation = <Date 2017-06-11.22:14:26.541>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30631
keywords = []
message_count = 3.0
messages = ['295732', '296151', '296152']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Segev Finer']
pr_nums = ['1963']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30631'
versions = ['Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
I'm hitting the following warnings when building in VS2015 Update 3 in 32-bit:

liblzma:
    warning C4028: formal parameter {} different from declaration
    warning C4113: 'FARPROC' differs in parameter lists from '{}'
    warning C4244: 'initializing': conversion from '{}' to '{}', possible loss of data
    warning C4267: '=': conversion from '{}' to '{}', possible loss of data
    warning C4996: 'GetVersion': was declared deprecated

libeay:
    warning C4996: 'gethostbyname': Use getaddrinfo() or GetAddrInfoW() instead or define \_WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings

socketmodule:
     warning C4996: '{}': Use {}() or {}() instead or define \_WINSOCK_DEPRECATED_NO_WARNINGS to disable deprecated API warnings (multiple)

tix:
    warning C4090: 'function': different 'const' qualifiers
    warning C4028: formal parameter {} different from declaration

And ValidateUcrtbase in python.vcxproj is failing on first build because it depends on ctypes but runs before it's built when building using the pcbuild.sln

**Comment by zware** [comment]
New changeset c9318853bbe8d62cb72ed853b0ffb75311ea474c by Zachary Ware (Segev Finer) in branch 'master':
bpo-30631: Silence MSVC warnings in third-party code (GH-1963)
https://github.com/python/cpython/commit/c9318853bbe8d62cb72ed853b0ffb75311ea474c

**Comment by zware** [comment]
Thanks for the patch!
