### ISSUE TITLE
lower() is called twice

### ISSUE THREAD

**Issue by bffe776b-84f6-4d46-b460-ef9186a48ffc** [python/cpython#74814]
BPO | [30629](https://bugs.python.org/issue30629)
--- | :---
Nosy | @terryjreedy, @narusemotoki
PRs | <li>python/cpython#2099</li><li>python/cpython#2284</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-06-20.08:29:31.671>
created_at = <Date 2017-06-11.06:36:19.321>
labels = ['3.7', 'type-feature', 'library']
title = 'lower() is called twice'
updated_at = <Date 2017-06-20.08:29:31.670>
user = 'https://github.com/narusemotoki'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-20.08:29:31.670>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-06-20.08:29:31.671>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-06-11.06:36:19.321>
creator = 'motoki'
dependencies = []
files = []
hgrepos = []
issue_num = 30629
keywords = []
message_count = 6.0
messages = ['295689', '296222', '296223', '296398', '296406', '296407']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'motoki']
pr_nums = ['2099', '2284']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30629'
versions = ['Python 3.7']
```

</p></details>

**Comment by bffe776b-84f6-4d46-b460-ef9186a48ffc** [comment]
https://github.com/python/cpython/blob/master/Lib/html/parser.py#L415

elem is already lowercase string but call lower() for handle_endtag().

```py
elem = match.group(1).lower() # script or style
if self.cdata_elem is not None:
    if elem != self.cdata_elem:
        self.handle_data(rawdata[i:gtpos])
        return gtpos

self.handle_endtag(elem.lower())
```

**Comment by terryjreedy** [comment]
New changeset 3358d589fb51372a56ddcfffa277855e5661c4c0 by terryjreedy (Motoki Naruse) in branch 'master':
bpo-30629: Remove second call of str.lower() in html.parser.parse_endtag. (bpo-2099)
https://github.com/python/cpython/commit/3358d589fb51372a56ddcfffa277855e5661c4c0

**Comment by terryjreedy** [comment]
This appears to be your first CPython contribution.  Welcome.  We hope it is not the last.  If you prepare a PR to add yourself to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS), in appropriate alphabetical position, I will merge it.  Just suggest me as a reviewer.

**Comment by bffe776b-84f6-4d46-b460-ef9186a48ffc** [comment]
It will be highlight of my programmer life. Thank you. That pull request is just the beginning, not the last.

**Comment by terryjreedy** [comment]
New changeset 5cc7ac24da10568d2a910a91a24183b904118cf8 by terryjreedy (Motoki Naruse) in branch 'master':
bpo-30629: Add Motoki Naruse to [Misc/ACKS](https://github.com/python/cpython/blob/main/Misc/ACKS) (bpo-2284)
https://github.com/python/cpython/commit/5cc7ac24da10568d2a910a91a24183b904118cf8

**Comment by terryjreedy** [comment]
What persuaded me to make the offer was your extra effort to include the link to the specific line and the minimal quote needed to explain.  The link made it trivial to look at the context of the change.
