### ISSUE TITLE
Missing MSI files

### ISSUE THREAD

**Issue by 1e5e6bc3-c7ff-497e-a997-7dc3602830c9** [python/cpython#74815]
BPO | [30630](https://bugs.python.org/issue30630)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @bitdancer, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-17.01:31:10.628>
created_at = <Date 2017-06-11.15:04:41.451>
labels = ['invalid', 'OS-windows']
title = 'Missing MSI files'
updated_at = <Date 2017-06-17.01:31:10.626>
user = 'https://bugs.python.org/MarkAirey'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-17.01:31:10.626>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-17.01:31:10.628>
closer = 'terry.reedy'
components = ['Windows']
creation = <Date 2017-06-11.15:04:41.451>
creator = 'Mark Airey'
dependencies = []
files = []
hgrepos = []
issue_num = 30630
keywords = []
message_count = 4.0
messages = ['295718', '295726', '295812', '296224']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'r.david.murray', 'zach.ware', 'steve.dower', 'Mark Airey']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30630'
versions = ['Python 3.6']
```

</p></details>

**Comment by 1e5e6bc3-c7ff-497e-a997-7dc3602830c9** [comment]
I downloaded and installed python 3.0, 3.6.0 and 3.6.1 and they all said that I was missing: "api-ms-win-crt-runtime-|1-1-0.dll" or the msi files as i have read online. I don't know how to get said files and I need this program soon. Can anyone help?

**Comment by bitdancer** [comment]
Steve can correct me if I'm wrong, but I think this means your Windows OS isn't up to date.  Googling seems to indicate that this isn't a problem unique to Python.

**Comment by zooba** [comment]
Try installing https://go.microsoft.com/fwlink/?LinkId=746572 separately. This should add the required files, and because it's the "official" installer will provide more details about the underlying error (if any).

You may also need to reboot your machine. This is a system update, not a trivial file installation.

**Comment by terryjreedy** [comment]
Unless you are experimenting, you only need 3.6.1.  3.0 is deprecated in the sense that it was not meant for production use.

This tracker is for developing the next releases of CPython.  If you have any more questions, try python-list.
