### ISSUE TITLE
Syntax error reported on compile(...), but not on compile(..., ast.PyCF_ONLY_AST)

### ISSUE THREAD

**Issue by 61a746e0-56f6-4f74-bbde-a98c5612db23** [python/cpython#74822]
BPO | [30637](https://bugs.python.org/issue30637)
--- | :---
Nosy | @terryjreedy, @ncoghlan, @hniksic, @enedil, @pablogsal, @miss-islington, @iritkatriel
PRs | <li>python/cpython#28459</li><li>python/cpython#28460</li><li>python/cpython#28461</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-19.23:32:16.181>
created_at = <Date 2017-06-12.12:37:36.042>
labels = ['3.11', 'type-feature', 'docs']
title = 'Syntax error reported on compile(...), but not on compile(..., ast.PyCF_ONLY_AST)'
updated_at = <Date 2021-10-04.19:18:41.937>
user = 'https://github.com/hniksic'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-04.19:18:41.937>
actor = 'pablogsal'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-09-19.23:32:16.181>
closer = 'pablogsal'
components = ['Documentation']
creation = <Date 2017-06-12.12:37:36.042>
creator = 'hniksic'
dependencies = []
files = []
hgrepos = []
issue_num = 30637
keywords = ['patch']
message_count = 13.0
messages = ['295771', '295908', '295909', '295910', '296225', '301001', '401136', '401172', '401174', '402177', '402182', '402184', '403152']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'ncoghlan', 'hniksic', 'docs@python', 'enedil', 'pablogsal', 'miss-islington', 'iritkatriel']
pr_nums = ['28459', '28460', '28461']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30637'
versions = ['Python 3.11']
```

</p></details>

**Comment by 61a746e0-56f6-4f74-bbde-a98c5612db23** [comment]
Our application compiles snippets of user-specified code using the compile built-in with ast.PyCF_ONLY_AST flag. At this stage we catch syntax errors and perform some sanity checks on the AST. The AST is then compiled into actual code using compile() and run using further guards.

We found that using a bare "return" in the code works with ast.PyCF_ONLY_AST, but raises SyntaxError when compiled without the flag:

```pycon
>>> import ast
>>> compile('return', '', 'exec', ast.PyCF_ONLY_AST, True)
<_ast.Module object at 0x7f35df872310>

>>> compile('return', '', 'exec', 0, True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "", line 1
SyntaxError: 'return' outside function
```


Is this intended behavior? It doesn't seem to be documented anywhere.

**Comment by c52bddf0-d054-40a8-9f85-1ccf099957bc** [comment]
Docs mention:


```py
ast.parse(source, filename='<unknown>', mode='exec')
    Parse the source into an AST node. Equivalent to compile(source, filename, mode, ast.PyCF_ONLY_AST).
```


If you just parse code into AST, you first check whether it is possible to turn such source into a Python syntax tree. In that case, it obviously is, as you may imagine a function, that returns nothing:

```py
def func():
    return
```


If however you try to make executable code of the source, it is checked whether the constructs make sense in provided context. And, as you may imagine, top-level code with return statement is not valid, hence the error.

**Comment by ncoghlan** [comment]
It's intended behaviour, but you're right that we don't explicitly document anywhere that SyntaxError can be reported from three different places:

- the initial parsing based on the language Grammar
- the conversion of the parse tree into the AST
- the conversion of the AST into a runtime code object

It isn't possible to separate the first two from pure Python code, but ast.parse() (aka the ast.PyCF_ONLY_AST compile flag) skips the last one.

As Michał noted, it's usually that last stage which checks for "higher level" constructs related to lexical structure, where certain statements can only be meaningfully executed when used inside a suitable compound statement, but can still be parsed outside it:

```
>>> ast.dump(ast.parse("break"))
'Module(body=[Break()])'
>>> ast.dump(ast.parse("continue"))
'Module(body=[Continue()])'
>>> ast.dump(ast.parse("return"))
'Module(body=[Return(value=None)])'
>>> ast.dump(ast.parse("yield"))
'Module(body=[Expr(value=Yield(value=None))])'
```

(`await` currently isn't in that category, but that's specifically due to the parser hacks used to enable it without needing a __future__ import)

The appropriate fix would probably be to add a sentence to the `ast.PyCF_ONLY_AST` documentation to say that some syntax errors are only detected when compiling the AST to a code object.

**Comment by 61a746e0-56f6-4f74-bbde-a98c5612db23** [comment]
> The appropriate fix would probably be to add a sentence to the
> `ast.PyCF_ONLY_AST` documentation to say that some syntax errors
> are only detected when compiling the AST to a code object.

Yes, please. I'm not saying the current behavior is wrong (it makes sense that some constructs are legal as AST, but can't be converted into code), I just found it surprising. In other words, we would have found it very useful for the documentation to mention that code generation performs additional checks on the AST that are not performed during the ast.PyCF_ONLY_AST compilation.

**Comment by terryjreedy** [comment]
Python grammar is constrained to be, I believe, LL(1).  Whatever the constraint is, there are a few syntax rules that either cannot be written or would be difficult to write within the constraint.  So they are checked during compilation.  Can you suggest a couple of sentences you would have like to have seen, and where?

I might also note that not all exceptions raised by compile are literally 'SyntaxError's.

**Comment by 61a746e0-56f6-4f74-bbde-a98c5612db23** [comment]
> Can you suggest a couple of sentences you would have like to have
> seen, and where?

Thanks, I would suggest to add something like this to the documentation of ast.parse:

"""
``parse`` raises ``SyntaxError`` if the compiled source is invalid, and ``ValueError`` if the source contains null bytes. Note that a successful parse does not guarantee correct syntax of ``source``. Further syntax errors can be detected, and ``SyntaxError`` raised, when the source is compiled to a code object using ``compile`` without the ``ast.PyCF_ONLY_AST`` flag, or executed with ``exec``. For example, a lone ``break`` statement can be parsed, but not converted into a code object or executed.
"""

I don't think the ``compile`` docs need to be changed, partly because they're already sizable, and partly because they don't document individual flags at all. (A reference to the ``ast`` module regarding the flags, like the one for AST objects in the first paragraph, might be a useful addition.)
