### ISSUE TITLE
Leak in test_c_locale_coercion

### ISSUE THREAD

**Issue by matrixise** [python/cpython#74820]
BPO | [30635](https://bugs.python.org/issue30635)
--- | :---
Nosy | @ncoghlan, @vstinner, @matrixise
PRs | <li>python/cpython#2126</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-13.12:31:33.601>
created_at = <Date 2017-06-12.08:59:15.408>
labels = ['type-bug', '3.7']
title = 'Leak in test_c_locale_coercion'
updated_at = <Date 2017-06-13.12:31:33.600>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-13.12:31:33.600>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-13.12:31:33.601>
closer = 'ncoghlan'
components = []
creation = <Date 2017-06-12.08:59:15.408>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 30635
keywords = []
message_count = 4.0
messages = ['295759', '295760', '295907', '295912']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'vstinner', 'matrixise']
pr_nums = ['2126']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30635'
versions = ['Python 3.7']
```

</p></details>

**Comment by matrixise** [comment]
./python -m test -R 3:3  test_c_locale_coercion -m test_external_target_locale_configuration                                                                                                                            Mon 12 Jun 2017 10:57:14 AM CEST
Run tests sequentially
0:00:00 load avg: 1.31 [1/1] test_c_locale_coercion
beginning 6 repetitions
123456
......
test_c_locale_coercion leaked [2, 2, 2] references, sum=6
test_c_locale_coercion failed

1 test failed:
    test_c_locale_coercion

Total duration: 4 sec
Tests result: FAILURE

**Comment by vstinner** [comment]
Likely a leak in the implementation of the PEP-538, commit 6ea4186de32d65b1f1dc1533b6312b798d300466, bpo-28180.

**Comment by ncoghlan** [comment]
New changeset 023564bf7d95f8e6a4b790491811e75ce497a071 by Nick Coghlan (Victor Stinner) in branch 'master':
bpo-30635: Fix refleak in test_c_locale_coercion (bpo-2126)
https://github.com/python/cpython/commit/023564bf7d95f8e6a4b790491811e75ce497a071

**Comment by ncoghlan** [comment]
Technically a false alarm due to an unintended caching side effect in the test case.

Victor fixed it by moving the list creation to the module setup fixture, so it only runs once, even when hunting refleaks.
