### ISSUE TITLE
Add PYTHONCOERCECLOCALE to the help of the command line

### ISSUE THREAD

**Issue by matrixise** [python/cpython#74821]
BPO | [30636](https://bugs.python.org/issue30636)
--- | :---
Nosy | @ncoghlan, @matrixise
PRs | <li>python/cpython#2125</li><li>python/cpython#2131</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-13.01:31:43.428>
created_at = <Date 2017-06-12.09:55:38.049>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Add PYTHONCOERCECLOCALE to the help of the command line'
updated_at = <Date 2017-06-13.01:31:43.427>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-13.01:31:43.427>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-13.01:31:43.428>
closer = 'ncoghlan'
components = ['Interpreter Core']
creation = <Date 2017-06-12.09:55:38.049>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 30636
keywords = []
message_count = 6.0
messages = ['295763', '295768', '295776', '295777', '295833', '295834']
nosy_count = 2.0
nosy_names = ['ncoghlan', 'matrixise']
pr_nums = ['2125', '2131']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30636'
versions = ['Python 3.7']
```

</p></details>

**Comment by matrixise** [comment]
Add the description of PYTHONCOERCECLOCALE in the command line.

**Comment by ncoghlan** [comment]
I just noticed that there's a line-wrapping problem in the patch as-merged. The output ends up being:

PYTHONCOERCECLOCALE: if this variable is set to 0, it disables the locale
coercion behavior

It should either match the immediately preceding settings, which use a three space indent:

PYTHONMALLOC: set the Python memory allocators and/or install debug hooks
   on Python memory allocators. Use PYTHONMALLOC=debug to install debug
   hooks.

While some of the earlier ones align the continuation line with the opening text on the first line, those are all for much shorter variable names.

**Comment by matrixise** [comment]
yep, I see that, I fix it asap

**Comment by ncoghlan** [comment]
Thanks once again! :)
