### ISSUE TITLE
inspect.getfile(obj) calls object repr on failure

### ISSUE THREAD

**Issue by cd34197f-d4a4-4e30-9fbe-454f267f097e** [python/cpython#74824]
BPO | [30639](https://bugs.python.org/issue30639)
--- | :---
Nosy | @bitdancer, @takluyver, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#2132</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-24.12:43:35.838>
created_at = <Date 2017-06-12.13:54:06.692>
labels = ['3.7', 'easy', 'type-feature', 'library']
title = 'inspect.getfile(obj) calls object repr on failure'
updated_at = <Date 2017-10-24.12:43:35.836>
user = 'https://github.com/takluyver'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-24.12:43:35.836>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-24.12:43:35.838>
closer = 'yselivanov'
components = ['Library (Lib)']
creation = <Date 2017-06-12.13:54:06.692>
creator = 'takluyver'
dependencies = []
files = []
hgrepos = []
issue_num = 30639
keywords = ['easy']
message_count = 9.0
messages = ['295782', '295792', '295796', '295807', '295808', '295809', '295811', '304903', '304905']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'takluyver', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['2132']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30639'
versions = ['Python 3.7']
```

</p></details>

**Comment by cd34197f-d4a4-4e30-9fbe-454f267f097e** [comment]
This came up in IPython & Jedi: several functions in inspect end up calling getfile(). If the object is something for which it can't find the source file, it throws an error, the message for which contains the object's repr.

This is problematic for us because for some objects the repr may be expensive to calculate (e.g. data tables where the repr forms primary output, not just debugging information). In some cases, it could also throw another error.

I plan to make a PR for this, but I'm opening an issue so I've got a bpo number.

https://github.com/ipython/ipython/issues/10493
https://github.com/davidhalter/jedi/issues/919

**Comment by bitdancer** [comment]
What is your proposed solution?  This doesn't at the moment sound like a bug in Python to me.

**Comment by cd34197f-d4a4-4e30-9fbe-454f267f097e** [comment]
Not exactly a bug, but I think that an improvement is possible. My plan is to delay computing the repr until the error is formatted, so that code which catches the TypeError can carry on safely.

I think this is more relevant for inspect than for many other modules, because by design, we're often calling inspect functions on arbitrary objects which we can make few guarantees about.

**Comment by serhiy-storchaka** [comment]
I think in that case it is enough to report just type name.

**Comment by cd34197f-d4a4-4e30-9fbe-454f267f097e** [comment]
Sure, I can do that if you want. The other thing I thought of was using object.\_\_repr__, so the repr always shows like \<foo object at 0x123abc...\> .

**Comment by serhiy-storchaka** [comment]
The address of the object is not informative. The possibility of getting a source file is determined by the type of the object.

**Comment by cd34197f-d4a4-4e30-9fbe-454f267f097e** [comment]
OK, I've updated the PR to do that.

**Comment by 1st1** [comment]
New changeset e968bc735794a7123f28f26d68fdf5dc8c845280 by Yury Selivanov (Thomas Kluyver) in branch 'master':
bpo-30639: Lazily compute repr for error (bpo-2132)
https://github.com/python/cpython/commit/e968bc735794a7123f28f26d68fdf5dc8c845280

**Comment by 1st1** [comment]
Thank you, Thomas.
