### ISSUE TITLE
[EASY][doc] Document that signal.set_wakeup_fd(-1), unregister the previsouly set wakeup FD

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74829]
BPO | [30644](https://bugs.python.org/issue30644)
--- | :---
Nosy | @pitrou, @vstinner
PRs | <li>python/cpython#2149</li><li>python/cpython#2140</li><li>python/cpython#2150</li><li>python/cpython#2151</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-13.08:38:21.616>
created_at = <Date 2017-06-13.07:45:59.946>
labels = ['easy', '3.7', 'docs']
title = '[EASY][doc] Document that signal.set_wakeup_fd(-1), unregister the previsouly set wakeup FD'
updated_at = <Date 2017-06-13.08:38:21.614>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-13.08:38:21.614>
actor = 'pitrou'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-13.08:38:21.616>
closer = 'pitrou'
components = ['Documentation']
creation = <Date 2017-06-13.07:45:59.946>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30644
keywords = ['easy']
message_count = 3.0
messages = ['295859', '295863', '295864']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'docs@python']
pr_nums = ['2149', '2140', '2150', '2151']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30644'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The signal.set_wakeup_fd() function is used to write signal numbers as bytes into a pipe, to be able to handle signals using a "regular" file descriptors instead of special signal handlers.

https://docs.python.org/dev/library/signal.html

Problem: it's not documented how to unregister the FD. I just saw "signal.set_wakeup_fd(-1)" in a Pull Request and realized that we forgot to document it:
https://github.com/python/cpython/pull/2139/

This issue is an EASY issue: please leave it to real newcomers who didn't write any PR to CPython previously. Core developers: explain how to fix the issue, don't fix it ;-)

[Doc/library/signal.rst](https://github.com/python/cpython/blob/main/Doc/library/signal.rst) should be modified. I read that it's even possible to create a PR using an online editor? I never tried:
https://github.com/python/cpython/blob/master/Doc/library/signal.rst

**Comment by pitrou** [comment]
> This issue is an EASY issue: please leave it to real newcomers who didn't write any PR to CPython previously. Core developers: explain how to fix the issue, don't fix it ;-)

Too late, sorry!

**Comment by vstinner** [comment]
> This issue is an EASY issue: please leave it to real newcomers who didn't write any PR to CPython previously. Core developers: explain how to fix the issue, don't fix it ;-)

Oh wait, it seems like the core developer Antoine Pitrou fixed the issue before I created it! =\> commit d79c1d4a9406384f10a37f26a7515ce79f9fdd78

He already created 3 PR to backport the doc enhancement to 2.7, 3.5 and 3.6 branches.

Sorry!
