### ISSUE TITLE
SQLite: sqlite3_enable_shared_cache() is deprecated

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74831]
BPO | [30646](https://bugs.python.org/issue30646)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @erlend-aasland
Superseder | <li>bpo-24464: &quot;sqlite3_enable_shared_cache&quot; deprecation warning when compiling with macOS system SQLite3</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-13.11:22:18.408>
created_at = <Date 2017-06-13.08:34:13.720>
labels = ['OS-mac', '3.7', 'library']
title = 'SQLite: sqlite3_enable_shared_cache() is deprecated'
updated_at = <Date 2020-09-06.10:15:30.728>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-06.10:15:30.728>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-13.11:22:18.408>
closer = 'ned.deily'
components = ['Library (Lib)', 'macOS']
creation = <Date 2017-06-13.08:34:13.720>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30646
keywords = []
message_count = 5.0
messages = ['295867', '295902', '295954', '376441', '376443']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'erlendaasland']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '24464'
type = None
url = 'https://bugs.python.org/issue30646'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Warning seen on the macOS Travis CI job:
"warning: 'sqlite3_enable_shared_cache' is deprecated: first deprecated in OS X 10.7"


https://travis-ci.org/python/cpython/jobs/242325662

clang -Wno-unused-result -Wsign-compare -g -O0 -Wall -Wstrict-prototypes -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -I./Include -I. -I/usr/local/opt/openssl/include -I/usr/local/include -I/Users/travis/build/python/cpython/Include -I/Users/travis/build/python/cpython -c /Users/travis/build/python/cpython/Modules/_gdbmmodule.c -o build/temp./Users/travis/build/python/cpython/Modules/_sqlite/module.c:136:10: warning: 'sqlite3_enable_shared_cache' is deprecated: first deprecated in OS X 10.7 [-Wdeprecated-declarations]

```py
    rc = sqlite3_enable_shared_cache(do_enable);
```


         ^

/usr/include/sqlite3.h:5170:31: note: 'sqlite3_enable_shared_cache' has been explicitly marked deprecated here

SQLITE_API int SQLITE_STDCALLmacosx-10.11-x86_64-3.6-pydebug/Users/travis/build/python/cpython/Modules/_gdbmmodule.o

 sqlite3_enable_shared_cache(int) \_\_OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, \_\_MAC_10_7, \_\_IPHONE_2_0, \_\_IPHONE_5_0);

                              ^

1 warning generated.

**Comment by ned-deily** [comment]
That's another reason why the python.org macOS installer build and, to the best of my knowledge, most third-party distributors of Python on macOS use their own builds of sqlite3 rather than the Apple-supplied system one.  I don't think there's anything new to be done here.

**Comment by ronaldoussoren** [comment]
See also \<https://sqlite.org/c3ref/enable_shared_cache.html\>. Apple basically disabled this function starting at macOS 10.7, that's why there's a warning.

It is possible to suppress the warning, but I don't think its worth the trouble.

BTW. The python documentation for this function claims this changes a thread-local setting, but the SQLite documentation says this is a process global setting in SQLite 3.5.0 and later (released in 2007).  It is possible to make behaviour match the python documentation by making \_sqlite3.enable_shared_cache store a flag that's used in the call to sqlite3_open_v2. That would be a backward compatibility concern (there's bound to be users that rely on the current behavior), but would also avoid this warning.
