### ISSUE TITLE
lack of right parentheses

### ISSUE THREAD

**Issue by f497f5d7-6dc1-4fdb-8046-3a4b1629ee11** [python/cpython#74835]
BPO | [30650](https://bugs.python.org/issue30650)
--- | :---
Nosy | @serhiy-storchaka, @moreati, @messi Liao
PRs | <li>python/cpython#2154</li><li>python/cpython#2215</li><li>python/cpython#2216</li>
Files | <li>[posixmodule_compiler_error.png](https://bugs.python.org/file46945/posixmodule_compiler_error.png "Uploaded as image/png at 2017-06-13.09:42:38 by @messi Liao"): compiler error</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-15.14:18:00.029>
created_at = <Date 2017-06-13.09:42:38.882>
labels = ['build', '3.7']
title = 'lack of right parentheses'
updated_at = <Date 2017-06-15.14:18:00.029>
user = 'https://github.com/messiLiao'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.14:18:00.029>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-15.14:18:00.029>
closer = 'serhiy.storchaka'
components = ['Cross-Build']
creation = <Date 2017-06-13.09:42:38.882>
creator = 'bh_binghu'
dependencies = []
files = ['46945']
hgrepos = []
issue_num = 30650
keywords = []
message_count = 5.0
messages = ['295883', '295920', '295921', '296091', '296092']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'Alex.Willmer', 'bh_binghu']
pr_nums = ['2154', '2215', '2216']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30650'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f497f5d7-6dc1-4fdb-8046-3a4b1629ee11** [comment]
lack of right parentheses

**Comment by serhiy-storchaka** [comment]
New changeset 0d322181d9018b25a5c28e62a0c193b4309aaa95 by Serhiy Storchaka (messi Liao) in branch 'master':
bpo-30650: Fixed a syntax error: missed right parentheses (bpo-2154)
https://github.com/python/cpython/commit/0d322181d9018b25a5c28e62a0c193b4309aaa95

**Comment by serhiy-storchaka** [comment]
Thank you for your patch Messi Liao! Do you mind to backport it to branches 3.6 and 3.5?

**Comment by serhiy-storchaka** [comment]
New changeset f75f6edb1fdbaeb12f9de368ebdeb1b7d1836433 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30650: Fixed a syntax error: missed right parentheses (GH-2154) (bpo-2215)
https://github.com/python/cpython/commit/f75f6edb1fdbaeb12f9de368ebdeb1b7d1836433

**Comment by serhiy-storchaka** [comment]
New changeset b39c78a73c203dcaf8f2061da81827c667440402 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30650: Fixed a syntax error: missed right parentheses (GH-2154) (bpo-2216)
https://github.com/python/cpython/commit/b39c78a73c203dcaf8f2061da81827c667440402
