### ISSUE TITLE
typo in PyModule_New documentation

### ISSUE THREAD

**Issue by 06bbce58-3120-46b9-873e-214d43e32c00** [python/cpython#74841]
BPO | [30656](https://bugs.python.org/issue30656)
--- | :---
Nosy | @emilyemorehouse, @Mariatta, @janhn
PRs | <li>python/cpython#2170</li><li>python/cpython#2169</li><li>python/cpython#2230</li><li>python/cpython#2231</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-16.01:50:11.469>
created_at = <Date 2017-06-13.14:40:09.288>
labels = ['3.7', 'docs']
title = 'typo in PyModule_New documentation'
updated_at = <Date 2017-06-16.01:50:11.468>
user = 'https://github.com/janhn'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.01:50:11.468>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-16.01:50:11.469>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-13.14:40:09.288>
creator = 'hnhn'
dependencies = []
files = []
hgrepos = []
issue_num = 30656
keywords = []
message_count = 5.0
messages = ['295922', '295939', '295945', '296142', '296143']
nosy_count = 4.0
nosy_names = ['docs@python', 'emilyemorehouse', 'Mariatta', 'hnhn']
pr_nums = ['2170', '2169', '2230', '2231']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30656'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 06bbce58-3120-46b9-873e-214d43e32c00** [comment]
The doc for PyModule_New() refers to "PyImport_NewObject()", while it should refer to "PyModule_NewObject()":

https://docs.python.org/3.6/c-api/module.html#c.PyModule_New

**Comment by emilyemorehouse** [comment]
Good catch, fixed in PR.

**Comment by Mariatta** [comment]
New changeset 2d0afef82a07afdb666f2ca0c533aac5d39155cd by Mariatta (Emily Morehouse) in branch 'master':
bpo-30656: Fix Python C API Module Objects documentation (GH-2170)
https://github.com/python/cpython/commit/2d0afef82a07afdb666f2ca0c533aac5d39155cd

**Comment by Mariatta** [comment]
New changeset 6a90a124706b73824aebf5c2bd7b27daf82b2342 by Mariatta in branch '3.6':
bpo-30656: Fix Python C API Module Objects documentation (GH-2170) (GH-2230)
https://github.com/python/cpython/commit/6a90a124706b73824aebf5c2bd7b27daf82b2342

**Comment by Mariatta** [comment]
New changeset 0b13f58497d3a36d062c3b3b827abb05db5afbc1 by Mariatta in branch '3.5':
bpo-30656: Fix Python C API Module Objects documentation (GH-2170) (GH-2231)
https://github.com/python/cpython/commit/0b13f58497d3a36d062c3b3b827abb05db5afbc1
