### ISSUE TITLE
Buildbot: don't sent email notification for custom builders

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74843]
BPO | [30658](https://bugs.python.org/issue30658)
--- | :---
Nosy | @vstinner, @zware, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.16:35:21.183>
created_at = <Date 2017-06-13.16:16:03.420>
labels = ['3.7', 'tests']
title = "Buildbot: don't sent email notification for custom builders"
updated_at = <Date 2017-09-15.16:35:21.181>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.16:35:21.181>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.16:35:21.183>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-13.16:16:03.420>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30658
keywords = []
message_count = 6.0
messages = ['295936', '295971', '295994', '296018', '297138', '302268']
nosy_count = 3.0
nosy_names = ['vstinner', 'zach.ware', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30658'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Sadly, our version of buildbot doesn't support branches. Other options:
http://docs.buildbot.net/latest/manual/cfg-reporters.html#mailnotifier-arguments

**Comment by Mariatta** [comment]
This is not a cpython issue, is it?

**Comment by vstinner** [comment]
> This is not a cpython issue, is it?

I'm talking about CPython buildbots:
http://buildbot.python.org/all/waterfall?category=3.x.stable&category=3.x.unstable

I prefer to use bugs.python.org to discuss CPython issues, but if you consider that it's not the right place, we might use https://github.com/python/buildmaster-config/

But it seems like only Zach and me are watching https://github.com/python/buildmaster-config/ a little known project.

**Comment by Mariatta** [comment]
I didn't know about buildmaster-config repo.

It's not listed as one of the projects for the Python Core team :)

https://github.com/orgs/python/teams/python-core/repositories 

Should it be?

**Comment by vstinner** [comment]
It seems like buildbot.python.org will be upgrade to buildbot 0.9, and so we will be able to filter emails by branches ;-)

**Comment by vstinner** [comment]
Custom builders are rarely used. The work on upgrading our buildbots to 0.9 is in progress but moves slowly (sadly, Zach failed to finish this task at the CPython sprint last week). I close the issue, even if it's not done, just because I didn't get any such email last month.

If email notifications related to custom builders start to annoy me again, I will open an issue in the CPython buildbot configuration project or the CPython workflow project.
