### ISSUE TITLE
Lossless Optimization of PNG files

### ISSUE THREAD

**Issue by b60c8e9c-b9b2-4d59-8127-633b971795fc** [python/cpython#74845]
BPO | [30660](https://bugs.python.org/issue30660)
--- | :---
Nosy | @vstinner, @methane, @serhiy-storchaka, @tiagofilipesilva
PRs | <li>python/cpython#2141</li><li>python/cpython#8032</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-01.07:03:26.091>
created_at = <Date 2017-06-13.23:11:28.720>
labels = ['docs', '3.8', 'performance']
title = 'Lossless Optimization of PNG files'
updated_at = <Date 2018-07-01.07:03:26.088>
user = 'https://github.com/tiagofilipesilva'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-01.07:03:26.088>
actor = 'methane'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-07-01.07:03:26.091>
closer = 'methane'
components = ['Documentation']
creation = <Date 2017-06-13.23:11:28.720>
creator = 'tfs'
dependencies = []
files = []
hgrepos = []
issue_num = 30660
keywords = ['patch']
message_count = 7.0
messages = ['295969', '295989', '295990', '298375', '320795', '320801', '320826']
nosy_count = 5.0
nosy_names = ['vstinner', 'methane', 'docs@python', 'serhiy.storchaka', 'tfs']
pr_nums = ['2141', '8032']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30660'
versions = ['Python 3.8']
```

</p></details>

**Comment by b60c8e9c-b9b2-4d59-8127-633b971795fc** [comment]
I took the liberty to apply tools that optimize the binary weight (without loss of quality) of the 14 PNG files present in the Python 3.7 source tree and then applied a pull request (bpo-2141).

Is there anything to be discussed? Thanks.

**Comment by serhiy-storchaka** [comment]
What tools did you use, optipng, advpng, pngcrush, pngnq, pngquant, or other? How much space is saved?

Note that some tools remove an information about palette that makes files displaying differently on different platforms and output devises.

**Comment by vstinner** [comment]
I suggest to work on Sphinx to propose to implement this optimization on the HTML rendering, maybe with optional external tools. What do you think?

Another attempt: bpo-27461 :-)

**Comment by b60c8e9c-b9b2-4d59-8127-633b971795fc** [comment]
Sorry for the late reply. I had to deal with stuff.

serhiy.storchaka:

> What tools did you use, optipng, advpng, pngcrush, pngnq, pngquant, or other? How much space is saved?

I had half a crate of whiskey that day so I'm going to say optipng and pngcrush were used and if my recollection is good the saved space was ≈ 5 to 50 % depending on the file.

> Note that some tools remove an information about palette that makes files displaying differently on different platforms and output devises.

I am aware of that. But if I understood correctly these files are rendered in documentation, and I don't think they're going to do this in a PlayStation 2. There may be complaints with Windows XP users because I remember for sure that optimized PNG files could not render very well back in those days.

haypo:

> I suggest to work on Sphinx to propose to implement this optimization on the HTML rendering, maybe with optional external tools. What do you think?

Like you I'm very fond of a long-term proper solution and that is, by the way, the solution you deserve.

Unfortunately, I do not have the skills for provide that. I can only give the solution you need (which is smaller files).
