### ISSUE TITLE
speech module

### ISSUE THREAD

**Issue by ecaa61c9-7267-47a1-8606-58ed5388e0e1** [python/cpython#74840]
BPO | [30655](https://bugs.python.org/issue30655)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[speech.py](https://bugs.python.org/file46947/speech.py "Uploaded as text/plain at 2017-06-13.14:02:55 by agamstark7"): The above file contains corrected module.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-13.14:25:10.596>
created_at = <Date 2017-06-13.14:02:56.604>
labels = ['build']
title = 'speech module'
updated_at = <Date 2017-06-14.00:41:27.098>
user = 'https://bugs.python.org/agamstark7'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-14.00:41:27.098>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-13.14:25:10.596>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-06-13.14:02:56.604>
creator = 'agamstark7'
dependencies = []
files = ['46947']
hgrepos = []
issue_num = 30655
keywords = []
message_count = 2.0
messages = ['295917', '295919']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'agamstark7']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30655'
versions = ['Python 3.6']
```

</p></details>

**Comment by ecaa61c9-7267-47a1-8606-58ed5388e0e1** [comment]
when you will use this module for developing a chatbox you will get error that prompt is missing parenthesis.

I HAVE SOLVED THIS ERROR AND UPLOADING NEW MODULE.

**Comment by serhiy-storchaka** [comment]
The speech module is not a part of the Python standard library. Use corresponding bug tracker.
