### ISSUE TITLE
Use ** correctly for "kwargs" in signature of namedtuple._replace()

### ISSUE THREAD

**Issue by 8029d403-64fb-4202-9817-4695852d288d** [python/cpython#74844]
BPO | [30659](https://bugs.python.org/issue30659)
--- | :---
Nosy | @rhettinger, @benhoyt, @serhiy-storchaka, @Mariatta
PRs | <li>python/cpython#2173</li><li>python/cpython#2195</li><li>python/cpython#2196</li><li>python/cpython#2197</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-06-14.19:08:45.257>
created_at = <Date 2017-06-13.18:49:23.204>
labels = ['3.7', 'docs']
title = 'Use ** correctly for "kwargs" in signature of namedtuple._replace()'
updated_at = <Date 2017-06-14.19:08:45.256>
user = 'https://github.com/benhoyt'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-14.19:08:45.256>
actor = 'Mariatta'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-06-14.19:08:45.257>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-13.18:49:23.204>
creator = 'benhoyt'
dependencies = []
files = []
hgrepos = []
issue_num = 30659
keywords = []
message_count = 8.0
messages = ['295949', '295952', '295985', '295988', '296022', '296023', '296024', '296025']
nosy_count = 5.0
nosy_names = ['rhettinger', 'benhoyt', 'docs@python', 'serhiy.storchaka', 'Mariatta']
pr_nums = ['2173', '2195', '2196', '2197']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30659'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8029d403-64fb-4202-9817-4695852d288d** [comment]
The documentation for namedtuple.\_replace() needs a tweak: currently its signature shows "kwargs" without the ** notation, indicating it's a single, positional argument. It should have the ** to indicate it's actually any number of keyword arguments.

See https://docs.python.org/3/library/collections.html#collections.somenamedtuple.\_replace and compare with the docs for the signature of Logger.debug() for example: https://docs.python.org/3/library/logging.html#logging.Logger.debug

**Comment by Mariatta** [comment]
New changeset 184bd82ba8106785ba22f0d2477dbd08bef821fb by Mariatta (Ben Hoyt) in branch 'master':
bpo-30659 : Use ** for kwargs in namedtuple.\_replace() signature (GH-2173)
https://github.com/python/cpython/commit/184bd82ba8106785ba22f0d2477dbd08bef821fb

**Comment by rhettinger** [comment]
This looks fine.

**Comment by serhiy-storchaka** [comment]
Sorry, wrong issue.

**Comment by Mariatta** [comment]
New changeset 789f47ebb56283bd0156957121ac2854817b2bf9 by Mariatta in branch '3.6':
bpo-30659 : Use ** for kwargs in namedtuple.\_replace() signature (GH-2173) (GH-2195)
https://github.com/python/cpython/commit/789f47ebb56283bd0156957121ac2854817b2bf9

**Comment by Mariatta** [comment]
New changeset 4b30107bfdc9ba5afbe7f4a9d96273d6078bc310 by Mariatta in branch '2.7':
bpo-30659 : Use ** for kwargs in namedtuple.\_replace() signature (GH-2173) (GH-2196)
https://github.com/python/cpython/commit/4b30107bfdc9ba5afbe7f4a9d96273d6078bc310

**Comment by Mariatta** [comment]
New changeset a3afdca2190201bf6572435226dd3f8668139002 by Mariatta in branch '3.5':
bpo-30659 : Use ** for kwargs in namedtuple.\_replace() signature (GH-2173) (GH-2197)
https://github.com/python/cpython/commit/a3afdca2190201bf6572435226dd3f8668139002

**Comment by Mariatta** [comment]
Fixed and backported.
Thanks.
