### ISSUE TITLE
fix OrderedDict.__init__ docstring to reflect PEP 468

### ISSUE THREAD

**Issue by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [python/cpython#74847]
BPO | [30662](https://bugs.python.org/issue30662)
--- | :---
Nosy | @brettcannon, @rhettinger, @ericsnowcurrently, @serhiy-storchaka, @jonathaneunice, @Mariatta
PRs | <li>python/cpython#2179</li><li>python/cpython#3370</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-09-06.01:13:34.075>
created_at = <Date 2017-06-14.04:46:10.997>
labels = ['3.7', 'library']
title = 'fix OrderedDict.__init__ docstring to reflect PEP 468'
updated_at = <Date 2017-09-06.01:13:34.074>
user = 'https://github.com/jonathaneunice'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.01:13:34.074>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-09-06.01:13:34.075>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-06-14.04:46:10.997>
creator = 'jonathaneunice'
dependencies = []
files = []
hgrepos = []
issue_num = 30662
keywords = []
message_count = 8.0
messages = ['295982', '295987', '296039', '296053', '301397', '301410', '301426', '301427']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'rhettinger', 'eric.snow', 'serhiy.storchaka', 'jonathaneunice', 'Mariatta']
pr_nums = ['2179', '3370']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30662'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
In Python 3.6 and current repo (pre-3.7), the docstring for collections.OrderedDict.\_\_init__() stats that keyword argument order is arbitrary. That is untrue if I properly understand PEP-468, which as of Python 3.6 makes the order of kwargs stable / identical to the order seen in the source code.

Associated PR imminent.

**Comment by serhiy-storchaka** [comment]
Currently there are two implementations of OrderedDict, and Python implementation is not used. Is C implementation need an update? What about the module documentation, is it need an update?

I don't think that we should include such details about past Python versions in docstrings. I can't remember precedences.

**Comment by brettcannon** [comment]
Past Python details should not be included in docstrings; it should simply represent the current code.

**Comment by abbe2d7d-a720-4d8f-b841-4af0b21b2140** [comment]
PR updated to incorporate Serhiy Storchaka and Brett Cannon feedback.

**Comment by rhettinger** [comment]
New changeset faa57cbe7074b26807cd7ed89a7b173b5cbf3086 by Raymond Hettinger (Jonathan Eunice) in branch 'master':
bpo-30662: fixed OrderedDict.\_\_init__ docstring re PEP-468 (bpo-2179)
https://github.com/python/cpython/commit/faa57cbe7074b26807cd7ed89a7b173b5cbf3086

**Comment by rhettinger** [comment]
Mariatta is working on the backport.

**Comment by Mariatta** [comment]
New changeset 3b9d4444fe631117430dee8ef8a2f205b4b450d5 by Mariatta in branch '3.6':
[3.6] bpo-30662: fixed OrderedDict.\_\_init__ docstring re PEP-468 (GH-2179) (GH-3370)
https://github.com/python/cpython/commit/3b9d4444fe631117430dee8ef8a2f205b4b450d5

**Comment by Mariatta** [comment]
Backport done.
Thanks all :)
