### ISSUE TITLE
json.tool does not accept an --indent flag

### ISSUE THREAD

**Issue by 2529eca5-d492-46f9-981e-895c64228e98** [python/cpython#74854]
BPO | [30669](https://bugs.python.org/issue30669)
--- | :---
Nosy | @vadmium, @serhiy-storchaka, @LukeSwart
PRs | <li>python/cpython#2207</li>
Superseder | <li>bpo-29636: Specifying indent in the json.tool command</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-15.05:25:49.668>
created_at = <Date 2017-06-15.01:38:17.014>
labels = ['3.7', 'type-feature', 'library']
title = 'json.tool does not accept an --indent flag'
updated_at = <Date 2017-06-15.05:25:49.667>
user = 'https://github.com/LukeSwart'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.05:25:49.667>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-15.05:25:49.668>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-06-15.01:38:17.014>
creator = 'eartheaterrr'
dependencies = []
files = []
hgrepos = []
issue_num = 30669
keywords = []
message_count = 2.0
messages = ['296055', '296060']
nosy_count = 3.0
nosy_names = ['martin.panter', 'serhiy.storchaka', 'eartheaterrr']
pr_nums = ['2207']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29636'
type = 'enhancement'
url = 'https://bugs.python.org/issue30669'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2529eca5-d492-46f9-981e-895c64228e98** [comment]
I have been using the json.tool quite often by running `cat my-file.json | python -m json.tool` or (`:%! python -m json.tool` in vim) to pretty print the json file, but I would like to customize the indentation level to 2 indentation spaces instead of default of 4. Unfortunately, `json.tool` is hard-coded to use 4 spaces for indentation, so I am filing this issue to propose this change.

**Comment by vadmium** [comment]
bpo-29636 looks related
