### ISSUE TITLE
pprint for dict in sorted order or insert order?

### ISSUE THREAD

**Issue by 426c83a0-b8db-41c3-828a-67c3d739d054** [python/cpython#74855]
BPO | [30670](https://bugs.python.org/issue30670)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @josephsmeng, @pombredanne, @aaronchall, @eamanu, @remilapeyre, @tirkarthi, @ewjoachim
PRs | <li>python/cpython#11769</li><li>python/cpython#11769</li><li>python/cpython#11769</li><li>python/cpython#12500</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-22.17:24:37.317>
created_at = <Date 2017-06-15.02:15:55.228>
labels = ['3.8', 'type-bug', 'library']
title = 'pprint for dict in sorted order or insert order?'
updated_at = <Date 2019-03-23.01:17:06.773>
user = 'https://github.com/josephsmeng'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-23.01:17:06.773>
actor = 'xavierguihot'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-22.17:24:37.317>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-06-15.02:15:55.228>
creator = 'josephsmeng'
dependencies = []
files = []
hgrepos = []
issue_num = 30670
keywords = ['patch', 'patch', 'patch']
message_count = 19.0
messages = ['296056', '296065', '296068', '305440', '305442', '310898', '327904', '334588', '334605', '334689', '334693', '334846', '334854', '334932', '334933', '334936', '334937', '338614', '338615']
nosy_count = 11.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'josephsmeng', 'pombredanne', 'Aaron Hall', 'eamanu', 'remi.lapeyre', 'xtreak', 'Jan-Hein B\xc3\xbchrman', 'Valentin Beyer', 'ewjoachim']
pr_nums = ['11769', '11769', '11769', '12500']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30670'
versions = ['Python 3.8']
```

</p></details>

**Comment by 426c83a0-b8db-41c3-828a-67c3d739d054** [comment]
start from 3.6+, dict keys are ordered heir creation order.
the builtin print function works as we expected, but for 
pprint, the keys is sorted. should we using the sorted version
or just obey the creation order as builtin print?

**Comment by rhettinger** [comment]
Until dict insertion order is guaranteed, it doesn't make sense to change pprint().

**Comment by serhiy-storchaka** [comment]
Concur with Raymond.

**Comment by affb16c2-6fdb-403f-b328-86b7e719c99e** [comment]
If/when order is guaranteed (3.7?) we should have a pprint that respects current order, 

-or-

we should get an improved pprint (maybe named pp or print?) that understands mappings and other abstract data types.

I had a conversation about pprint at the Python meetup last night. It kinda went like this: https://www.youtube.com/watch?v=NpYEJx7PkWE 

Maybe now's the time for improved behavior?

**Comment by serhiy-storchaka** [comment]
A year ago I proposed to add a method for detecting whether a dict preserves an order and in what sense. [1] But this idea was rejected.

[1] https://mail.python.org/pipermail/python-dev/2016-October/146597.html
