### ISSUE TITLE
test_zipfile leaks references on Python 3.5 on the wo Refleaks buildbots (Gentoo, Windows)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74860]
BPO | [30675](https://bugs.python.org/issue30675)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @mlouielu
PRs | <li>python/cpython#2220</li><li>python/cpython#2227</li>
Files | <li>[test_x.py](https://bugs.python.org/file46955/test_x.py "Uploaded as text/plain at 2017-06-15.22:08:16 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-26.23:47:56.331>
created_at = <Date 2017-06-15.13:17:06.946>
labels = ['tests', 'performance']
title = 'test_zipfile leaks references on Python 3.5 on the wo Refleaks buildbots (Gentoo, Windows)'
updated_at = <Date 2017-06-26.23:47:56.329>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-26.23:47:56.329>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-26.23:47:56.331>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-15.13:17:06.946>
creator = 'vstinner'
dependencies = []
files = ['46955']
hgrepos = []
issue_num = 30675
keywords = ['buildbot']
message_count = 9.0
messages = ['296084', '296085', '296087', '296108', '296109', '296128', '296129', '296173', '296976']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'louielu']
pr_nums = ['2220', '2227']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30675'
versions = ['Python 3.5']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%203.5/builds/27/steps/test/logs/stdio

[336/398/5] test_zipfile
beginning 6 repetitions
123456
......
test_zipfile leaked [3, 9, 8] references, sum=20
test_zipfile leaked [3, 9, 8] memory blocks, sum=20
(...)
Re-running test 'test_zipfile' in verbose mode
(...)
OK (skipped=1)



http://buildbot.python.org/all/builders/x86%20Gentoo%20Refleaks%203.5/builds/30/steps/test/logs/stdio

[135/398/3] test_zipfile
beginning 6 repetitions
123456
......
test_zipfile leaked [6, 6, 9] references, sum=21
test_zipfile leaked [6, 8, 11] memory blocks, sum=25
(...)
Re-running test 'test_zipfile' in verbose mode
(...)
OK (skipped=1)

**Comment by vstinner** [comment]
I tried "./python -m test -R 3:3 test_zipfile" on Linux and my Windows VM, but I'm unable to reproduce the issue. Maybe I passed the wrong options to regrtest (-m test)?

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
```sh
$ git checkout upstream/3.5
$ make -j8
$ ./python.exe -m test -R 3:3 test_zipfile
[1/1] test_zipfile
beginning 6 repetitions
123456
......
1 test OK.
```



That is a pass on my macOS with upstream/3.5

**Comment by vstinner** [comment]
I succeeded to reproduce the bug, but only when running the -jN option, like:

./python -m test -j2 -R 3:3 test_zipfile

I reduced the test to:

./python -m test -j2 -R 3:3 test_zipfile -m test_random_open

This test heavily use random.randint().

In fact, the bug doesn't come from test_zipfile, but it's an issue Python singleton objects. There is a bug in regrtest which doesn't call warmup_caches() in worker processes when using the -jN option (multiprocessing mode).

My PR https://github.com/python/cpython/pull/2220 should fix the bug.

Sadly, I didn't backport test_regrtest functional tests from master to 3.5 yet: see bpo-30383.

**Comment by vstinner** [comment]
It seems like Python 3.6 and master (3.7) are not impacted by this bug, thanks to my rework on regrtest (now libregrtest) in Python 3.6.

It's unclear to me if Python 2.7 has the bug: I don't see the warm_caches() function.

**Comment by vstinner** [comment]
Ok, using attached test_x.py, I'm able to reproduce this bug on Python 2.7.

**Comment by vstinner** [comment]
New changeset 33cf0c4cd6e8abe138c3469ca9ec1502410945f0 by Victor Stinner in branch '3.5':
bpo-30675: Fix multiprocessing code in regrtest (bpo-2220)
https://github.com/python/cpython/commit/33cf0c4cd6e8abe138c3469ca9ec1502410945f0

**Comment by vstinner** [comment]
New changeset 8bb0863e0282c71d21bc2c1b5184d05d8f3a0988 by Victor Stinner in branch '2.7':
bpo-30675: Fix refleak hunting in regrtest (bpo-2227)
https://github.com/python/cpython/commit/8bb0863e0282c71d21bc2c1b5184d05d8f3a0988

**Comment by vstinner** [comment]
I tested: "./python -m test -j2 -R 3:3 -m test_random_open test_zipfile" now pass on 2.7, 3.5, 3.6 and master branches. So this issue is now fixed.

By the way, bpo-30776 should reduce even further false positive when hunting reference leaks.
