### ISSUE TITLE
datetime.fromtimestamp raises OSError on first day after epoch on Windows

### ISSUE THREAD

**Issue by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [python/cpython#74869]
BPO | [30684](https://bugs.python.org/issue30684)
--- | :---
Nosy | @tim-one, @pfmoore, @abalkin, @tjguk, @bitdancer, @zware, @eryksun, @zooba, @lazka
Superseder | <li>bpo-29097: [Windows] datetime.fromtimestamp(t) when 0 &lt;= t &lt;= 86399 fails on Python 3.6</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-16.17:06:14.501>
created_at = <Date 2017-06-16.12:55:21.589>
labels = ['3.7', 'type-bug', 'library', 'OS-windows']
title = 'datetime.fromtimestamp raises OSError on first day after epoch on Windows'
updated_at = <Date 2017-06-16.17:06:14.499>
user = 'https://github.com/lazka'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-16.17:06:14.499>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-16.17:06:14.501>
closer = 'r.david.murray'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-06-16.12:55:21.589>
creator = 'lazka'
dependencies = []
files = []
hgrepos = []
issue_num = 30684
keywords = []
message_count = 3.0
messages = ['296191', '296196', '296213']
nosy_count = 9.0
nosy_names = ['tim.peters', 'paul.moore', 'belopolsky', 'tim.golden', 'r.david.murray', 'zach.ware', 'eryksun', 'steve.dower', 'lazka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29097'
type = 'behavior'
url = 'https://bugs.python.org/issue30684'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
I'm not sure this is a bug since the docs says raising OSError is allowed, but it looks weird to me.

On Windows.

Using Python 3.4:

```pycon
>>> datetime.datetime.fromtimestamp(0)
datetime.datetime(1970, 1, 1, 1, 0)
```


Using Python 3.6.1:

```pycon
>>> datetime.datetime.fromtimestamp(0)
OSError: [Errno 22] Invalid argument
```


The first time stamp which works with 3.6 is 86400, so exactly the next day.

**Comment by eryksun** [comment]
This is due to computing the PEP-495 fold in the function datetime_from_timet_and_us in [Modules/_datetimemodule.c](https://github.com/python/cpython/blob/main/Modules/_datetimemodule.c). It computes the local time for (timet - max_fold_seconds), which is negative for timestamps less than max_fold_seconds (86400). It's documented that localtime_s [1] fails for negative time values. For example:

    0:000> kc 6
    Call Site
    python36_d!localtime_s
    python36_d!_PyTime_localtime
    python36_d!local
    python36_d!datetime_from_timet_and_us
    python36_d!datetime_from_timestamp
    python36_d!datetime_fromtimestamp

Dereference the time_t* arg (-86400):

    0:000> ?? *(int64_t *)@rdx
    int64 0n-86400

Print the errno_t return value (0x16 is EINVAL):

    0:000> pt; r rax
    rax=0000000000000016

[1]: https://msdn.microsoft.com/en-us/library/a442x3ye.aspx

**Comment by bitdancer** [comment]
This appears to be a duplicate of bpo-29097.
