### ISSUE TITLE
[Windows] Potential for GIL deadlock on Windows in threadmodule acquire_lock

### ISSUE THREAD

**Issue by c25a033a-9a3c-4182-9c8b-fd1a48f41ba3** [python/cpython#74861]
BPO | [30676](https://bugs.python.org/issue30676)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-15.17:30:43.681>
created_at = <Date 2017-06-15.13:34:17.697>
labels = ['invalid', 'type-bug', 'library', 'OS-windows']
title = '[Windows] Potential for GIL deadlock on Windows in threadmodule acquire_lock'
updated_at = <Date 2017-06-15.17:30:43.679>
user = 'https://bugs.python.org/sdeibel'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-15.17:30:43.679>
actor = 'sdeibel'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-15.17:30:43.681>
closer = 'sdeibel'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-06-15.13:34:17.697>
creator = 'sdeibel'
dependencies = []
files = []
hgrepos = []
issue_num = 30676
keywords = []
message_count = 3.0
messages = ['296088', '296113', '296117']
nosy_count = 6.0
nosy_names = ['paul.moore', 'sdeibel', 'pitrou', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30676'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by c25a033a-9a3c-4182-9c8b-fd1a48f41ba3** [comment]
In acquire_timed in \_threadmodule.c (used to implement threading lock acquire()) there is an optimization from https://github.com/python/cpython/commit/e75ff35af2b6c85d48c68b95f295aeac7396b162 that says it first tries non-blocking lock w/o releasing the GIL.  However, it seems that this call can block on Windows.

The call to PyThread_acquire_lock_timed(lock, 0, 0) (w/o releasing GIL) on Windows calls EnterNonRecursiveMutex which in turn, in the \_PY_USE_CV_LOCKS impl, immediately calls PyMUTEX_LOCK as if it's not going to block.  However, various implementations of this seem like they can block.  Specifically, the impls of PyMUTEX_LOCK that end up using AcquireSRWLockExclusive and EnterCriticalSection both block.  The only case that is correct (does not block) is when !_PY_USE_CV_LOCKS where EnterNonRecursiveMutex() instead calls WaitForSingleObjectEx() with the zero timeout.

This seems like an incorrect potential for GIL deadlock, because the thread blocks without releasing GIL.  Shouldn't it ultimately be using TryAcquireSRWLockExclusive and TryEnterCriticalSection in these two cases?

This seems like an issue on Windows only.  The pthreads implementations look like they correctly handle timeout of 0 sent to PyThread_acquire_lock_timed().

**Comment by zooba** [comment]
We recently tried switching the GIL implementation on Windows by changing the setting you refer to. It didn't work, so we didn't keep the change, but I don't recall the details - likely the same issue you bring up here.

I don't have the other issue number handy right now, but it may be worth trying to find it. We should be able to switch to the OS implementation of condition variables, and I'd expect performance improvement, but we need to resolve these issues first.

**Comment by c25a033a-9a3c-4182-9c8b-fd1a48f41ba3** [comment]
I think I misunderstood the implementation of EnterNonRecursiveMutex -- the mutex that could block there is the internal 'cs' mutex, which would only be held only briefly while Enter/LeaveNonRecursiveMutex are running, and it looks like the 'cs' mutex is released before doing anything that blocks (in the two impls of PyCOND_WAIT and PyCOND_TIMEDWAIT).

So my report is invalid and I'm closing it.  Sorry about that!
