### ISSUE TITLE
Multiprocessing Send to Manager Fails for Large Payload

### ISSUE THREAD

**Issue by 4c9d81ed-35a0-43e6-8606-bd3bd7b504c7** [python/cpython#74870]
BPO | [30685](https://bugs.python.org/issue30685)
--- | :---
Nosy | @pitrou, @applio, @ZackerySpytz
Superseder | <li>bpo-17560: problem using multiprocessing with really big objects?</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-07-25.15:37:14.225>
created_at = <Date 2017-06-16.16:12:46.539>
labels = ['3.7', 'type-feature', 'library']
title = 'Multiprocessing Send to Manager Fails for Large Payload'
updated_at = <Date 2019-07-25.15:37:14.197>
user = 'https://bugs.python.org/maxehr'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-25.15:37:14.197>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2019-07-25.15:37:14.225>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-06-16.16:12:46.539>
creator = 'maxehr'
dependencies = []
files = []
hgrepos = []
issue_num = 30685
keywords = []
message_count = 4.0
messages = ['296210', '297210', '348415', '348439']
nosy_count = 4.0
nosy_names = ['pitrou', 'davin', 'maxehr', 'ZackerySpytz']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '17560'
type = 'enhancement'
url = 'https://bugs.python.org/issue30685'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4c9d81ed-35a0-43e6-8606-bd3bd7b504c7** [comment]
On line 393 of multiprocessing/connection.py, the size of the payload to be sent is serialized as an integer. This fails for sending large payloads. It should probably be serialized as a long or better yet a long long.

**Comment by pitrou** [comment]
As the comment just above that line says, this is for wire compatibility with older Python versions.

But we could have an escape hatch: a special value of the length (which happens to be encoded as a signed integer), such as -64, which would signal a following 64-bit length field.  Would you like to submit a PR?
