### ISSUE TITLE
ChainMap doesn't preserve the order of ordered mappings

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#74875]
BPO | [30690](https://bugs.python.org/issue30690)
--- | :---
Nosy | @rhettinger, @ericvsmith, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-18.04:20:10.463>
created_at = <Date 2017-06-17.12:37:08.590>
labels = ['3.7', 'invalid', 'type-feature', 'library']
title = "ChainMap doesn't preserve the order of ordered mappings"
updated_at = <Date 2017-06-18.04:20:10.461>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-18.04:20:10.461>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-18.04:20:10.463>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-06-17.12:37:08.590>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 30690
keywords = []
message_count = 2.0
messages = ['296237', '296258']
nosy_count = 3.0
nosy_names = ['rhettinger', 'eric.smith', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30690'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Iterating ChainMap emits keys in mixed order even if all underlying mappings are ordered dicts (OrderedDict). Would be nice to keep the order more predictable.

This would solve bpo-30664. See also bpo-30689.

**Comment by rhettinger** [comment]
Until regular dicts guarantee order, I don't want to go down this path for ChainMap which currently makes no guarantees about preserving and passing through properties of the underlying mappings.   The current implementation is short, fast, and reliable.  I don't want to trade any of those for a feature that we don't even guarantee for regular dicts.

For http://bugs.python.org/issue30664, I recommend going with Eric's suggestion in http://bugs.python.org/issue30664#msg296005.
