### ISSUE TITLE
infinite loop in PyRun_InteractiveLoopFlags()

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#74881]
BPO | [30696](https://bugs.python.org/issue30696)
--- | :---
Nosy | @vstinner, @xdegaye
PRs | <li>python/cpython#4160</li><li>python/cpython#4379</li>
Files | <li>[infinite_loop.patch](https://bugs.python.org/file46959/infinite_loop.patch "Uploaded as text/plain at 2017-06-18.10:33:04 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-12.16:33:59.948>
created_at = <Date 2017-06-18.10:33:04.834>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'infinite loop in PyRun_InteractiveLoopFlags()'
updated_at = <Date 2017-11-13.12:40:12.021>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-13.12:40:12.021>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-12.16:33:59.948>
closer = 'xdegaye'
components = ['Interpreter Core']
creation = <Date 2017-06-18.10:33:04.834>
creator = 'xdegaye'
dependencies = []
files = ['46959']
hgrepos = []
issue_num = 30696
keywords = ['patch']
message_count = 9.0
messages = ['296267', '296322', '296324', '306118', '306120', '306151', '306152', '306153', '306155']
nosy_count = 2.0
nosy_names = ['vstinner', 'xdegaye']
pr_nums = ['4160', '4379']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30696'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
```pycon
To reproduce the problem, apply the nomemory_allocator.patch from issue 30695 and run the following two statements that must be interrupted with ^C:
$  ./python -q
>>> import _testcapi
>>> _testcapi.set_nomemory_allocator()
sys.excepthook is missing
^Cpython: Objects/call.c:785: PyEval_CallObjectWithKeywords: Assertion `!PyErr_Occurred()' failed.
Aborted (core dumped)
```


The attached patch fixes this problem.
No PR for the moment: this patch and nomemory_allocator.patch are needed to demonstrate other issues.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
The patch is far too simplistic. With this patch an exception kills the interactive loop, for example:

```pycon
$ ./python -q
>>> x
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'x' is not defined
$
```

**Comment by vstinner** [comment]
See also my old issue bpo-8070 opened 7 years ago :-)

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset e0582a37c8d1776a2fd4968e9216f3a05f780276 by xdegaye in branch 'master':
bpo-30696: Fix the REPL looping endlessly when no memory (GH-4160)
https://github.com/python/cpython/commit/e0582a37c8d1776a2fd4968e9216f3a05f780276

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset ea5b545e38b3fec7ff29276b5cd59dec583ebf34 by xdegaye in branch '3.6':
[3.6] bpo-30696: Fix the REPL looping endlessly when no memory (GH-4160). (bpo-4379)
https://github.com/python/cpython/commit/ea5b545e38b3fec7ff29276b5cd59dec583ebf34

**Comment by vstinner** [comment]
Thanks for fixing this very old bug!

What about Python 2.7?

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
> What about Python 2.7?

\_testcapi.set_nomemory() does not exist on Pyhton 2.7 so the changes cannot be tested. Applying the changes to PyRun_InteractiveLoopFlags() in 2.7 looks rather straightforward but there are too many differences in PyRun_InteractiveOneFlags() between 2.7 and 3.7.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Also the existing test coverage of these functions in all the Python versions is very weak.

**Comment by vstinner** [comment]
Ok, I understand, thanks for the explanation.
