### ISSUE TITLE
test_free_different_thread() of test_code leaks references on Python 3.6

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74889]
BPO | [30704](https://bugs.python.org/issue30704)
--- | :---
Nosy | @vstinner, @ned-deily, @DinoV, @1st1
PRs | <li>python/cpython#2455</li><li>python/cpython#2456</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.00:32:06.547>
created_at = <Date 2017-06-19.15:28:11.008>
labels = ['3.7', 'performance']
title = 'test_free_different_thread() of test_code leaks references on Python 3.6'
updated_at = <Date 2017-07-08.04:51:40.210>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-08.04:51:40.210>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.00:32:06.547>
closer = 'vstinner'
components = []
creation = <Date 2017-06-19.15:28:11.008>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30704
keywords = []
message_count = 5.0
messages = ['296350', '296919', '297080', '297083', '297934']
nosy_count = 4.0
nosy_names = ['vstinner', 'ned.deily', 'dino.viehland', 'yselivanov']
pr_nums = ['2455', '2456']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30704'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
haypo@selma$ ./python -m test -m test.test_code.CoExtra.test_free_different_thread -R 3:3 test_code 
Run tests sequentially
test_code leaked [2, 1, 1] memory blocks, sum=4

The regression was introduced by the bpo-30604: commit 2997fec01ee7300c6d5940e6c55e4ccf9f56f1b5.

**Comment by vstinner** [comment]
Ping Dino & Yury! test_code still leaks in 3.6 and master branches.

**Comment by vstinner** [comment]
New changeset 23e7944eba1968bb8432fdc4cc96d4fdd2c1a230 by Victor Stinner in branch 'master':
bpo-30704, bpo-30604: Fix memleak in code_dealloc() (bpo-2455)
https://github.com/python/cpython/commit/23e7944eba1968bb8432fdc4cc96d4fdd2c1a230

**Comment by vstinner** [comment]
New changeset 26daad4ee14693381d84a5235709d22aed1c22ed by Victor Stinner in branch '3.6':
bpo-30704, bpo-30604: Fix memleak in code_dealloc() (bpo-2455) (bpo-2456)
https://github.com/python/cpython/commit/26daad4ee14693381d84a5235709d22aed1c22ed

**Comment by ned-deily** [comment]
New changeset c794b643c9172d69afa46f85982befd82511d9df by Ned Deily (Victor Stinner) in branch '3.6':
bpo-30704, bpo-30604: Fix memleak in code_dealloc() (bpo-2455) (bpo-2456)
https://github.com/python/cpython/commit/c794b643c9172d69afa46f85982befd82511d9df
