### ISSUE TITLE
Incorrect description of "async with" in PEP492 and documentation

### ISSUE THREAD

**Issue by b8110ac9-b6ea-45a9-942d-c09a0a676ef5** [python/cpython#74892]
BPO | [30707](https://bugs.python.org/issue30707)
--- | :---
Nosy | @ncoghlan, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-20.04:34:20.751>
labels = ['type-bug', '3.7', 'docs']
title = 'Incorrect description of "async with" in PEP492 and documentation'
updated_at = <Date 2017-06-20.05:38:31.725>
user = 'https://bugs.python.org/DamienGeorge'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-20.05:38:31.725>
actor = 'ncoghlan'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-06-20.04:34:20.751>
creator = 'Damien George'
dependencies = []
files = []
hgrepos = []
issue_num = 30707
keywords = []
message_count = 2.0
messages = ['296400', '296402']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'docs@python', 'yselivanov', 'Damien George']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30707'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b8110ac9-b6ea-45a9-942d-c09a0a676ef5** [comment]
The behaviour of the "async with" statement in CPython does not match the description of it in PEP-492, nor the language documentation.  The implementation uses a try/except/finally block, while the PEP and documentation describe the behaviour using a try/except/else block.  The PEP and documentation should be updated to reflect the true intention of "async with".

**Comment by ncoghlan** [comment]
The specific issue is that early exits from an "async with" statement are actually defined the same way they for synchronous with statements: exiting early via return, break, or continue, is the same as reaching the end of the try block.

However, that's not what the documentation currently says: it describes "async with" in terms of try/except/else, which isn't correct.

**Comment by slateny** [comment]
This looks resolved to me - [language reference](https://docs.python.org/3/reference/compound_stmts.html#async-with)'s been updated with `finally`, and regarding the pep I opened an issue [here](https://github.com/python/peps/issues/2602) on the pep repo for discussion there.
