### ISSUE TITLE
Bad getter from Descriptor#Properties example

### ISSUE THREAD

**Issue by 4bfa8fbf-e507-41f8-89c2-8dd781a03287** [python/cpython#74894]
BPO | [30709](https://bugs.python.org/issue30709)
--- | :---
Nosy | @Mariatta, @anqurvanillapy
PRs | <li>python/cpython#2288</li><li>python/cpython#2339</li><li>python/cpython#2340</li><li>python/cpython#2341</li><li>python/cpython#2342</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-23.04:25:38.181>
created_at = <Date 2017-06-20.11:13:18.810>
labels = ['type-feature', '3.7', 'docs']
title = 'Bad getter from Descriptor#Properties example'
updated_at = <Date 2017-06-23.04:25:38.180>
user = 'https://github.com/anqurvanillapy'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-23.04:25:38.180>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-23.04:25:38.181>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-06-20.11:13:18.810>
creator = 'anqurvanillapy'
dependencies = []
files = []
hgrepos = []
issue_num = 30709
keywords = []
message_count = 6.0
messages = ['296412', '296665', '296666', '296670', '296671', '296673']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'anqurvanillapy']
pr_nums = ['2288', '2339', '2340', '2341', '2342']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30709'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4bfa8fbf-e507-41f8-89c2-8dd781a03287** [comment]
- The purpose of `obj` in the example is implicit
- As an argument the `obj` will cause errors when using Cell('b10').value because it expects more arguments, but 1 given

**Comment by 4bfa8fbf-e507-41f8-89c2-8dd781a03287** [comment]
Previous conversation here: https://github.com/python/cpython/pull/2288

**Comment by Mariatta** [comment]
New changeset b066edfb1b268e90ea11f45dd1827f46d7ceec88 by Mariatta (_ = NaN) in branch 'master':
bpo-30709: Improve code example in Descriptor HowTo doc (GH-2339)
https://github.com/python/cpython/commit/b066edfb1b268e90ea11f45dd1827f46d7ceec88

**Comment by Mariatta** [comment]
New changeset 508267437cc66fdadc12fb19fb2958c452b8a26f by Mariatta in branch '2.7':
[2.7] bpo-30709: Improve code example in Descriptor HowTo doc (GH-2339) (GH-2340)
https://github.com/python/cpython/commit/508267437cc66fdadc12fb19fb2958c452b8a26f

**Comment by Mariatta** [comment]
New changeset 8aa15ba884b14c1cf65d4c1a4c5abc4253f5c9ed by Mariatta in branch '3.5':
[3.5] bpo-30709: Improve code example in Descriptor HowTo doc (GH-2339) (GH-2341)
https://github.com/python/cpython/commit/8aa15ba884b14c1cf65d4c1a4c5abc4253f5c9ed

**Comment by Mariatta** [comment]
New changeset d79ac2c2468f072653ed9096cd33f89acb6ff5bb by Mariatta in branch '3.6':
[3.6] bpo-30709: Improve code example in Descriptor HowTo doc (GH-2339) (GH-2342)
https://github.com/python/cpython/commit/d79ac2c2468f072653ed9096cd33f89acb6ff5bb
