### ISSUE TITLE
struct.unpack generates wrong error in certain conditions

### ISSUE THREAD

**Issue by 24aaf459-983b-484e-b693-1267079b57de** [python/cpython#74897]
BPO | [30712](https://bugs.python.org/issue30712)
--- | :---
Nosy | @serhiy-storchaka, @SylvainDe

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-20.15:05:48.211>
created_at = <Date 2017-06-20.13:32:47.593>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'struct.unpack generates wrong error in certain conditions'
updated_at = <Date 2017-06-23.07:25:30.273>
user = 'https://bugs.python.org/knzsys'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-23.07:25:30.273>
actor = 'knzsys'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-20.15:05:48.211>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-06-20.13:32:47.593>
creator = 'knzsys'
dependencies = []
files = []
hgrepos = []
issue_num = 30712
keywords = []
message_count = 10.0
messages = ['296428', '296438', '296444', '296449', '296521', '296522', '296528', '296542', '296544', '296686']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'SylvainDe', 'knzsys']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30712'
versions = ['Python 2.7']
```

</p></details>

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
```py
#Working code:
from struct import *
rawdata = 'A'*196
laserdata = list(unpack('2s2s29H',rawdata[14:76]))
laserdata += list(unpack('26f3L4s',rawdata[76:196]))					

#This code generates error:
from struct import *
rawdata = 'A'*196
laserdata = list(unpack('2s2s29H26f3L4s',rawdata[14:196]))
# Does not work due to python bug: unpack calculates wrong size 184 (should be 182) from format string and generates error: 
```


#struct.error: unpack requires a string argument of length 184

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
the pack function has the same error: it adds additional 2 bytes

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Could it be caused by alignment ?

Also, it could be interesting to explain a bit more what you expect and what you actually get.

**Comment by serhiy-storchaka** [comment]
Don't forget about an alignment. If the first character is not one of '@', '=', '\<', '\>' or '!', '@' is assumed, which means native byte order, type sizes and alignments. If the 'f' format character require 4-byte alignment, 2 padding bytes are inserted before the first 'f' item.

Add the '=' character at the start of the format string if you need native byte order, "standard" type sizes and no alignments. Add the '\<' or '\>' characters if you need some specific byte order.

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
Thanks a lot.
changing format string from '2s2s29H26f3L4s' to '=2s2s29H26f3L4s' worked for me.

But I still do not understand, why it's working if I splitt format string in 2 parts + use the (un)pack command 2 times ('2s2s29H' + '26f3L4s' are working separately, but '=2s2s29H26f3L4s' needs the alignment specified.

Do someone have a link, where the alignment options are deeply explained?

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
just an example, how the pack function behaves with the same format string:

before: 13830108be00cafe....3e05ecbc5138000000043c9be14125359541bf338044000000007452e041.....
after:  13830108be00cafe....3e05ecbc51380000000400003c9be14125359541bf338044000000007452e041....

the pack function inserts 2 0x00 bytes at byte pos 62.

which means the first f item converts to 0x0000AABBCCDD instead to 0xAABBCCDD (float value AABBCCDD is an example).
if the formatstring starts with f it converts to 0xAABBCCDD.

Why this strange behavior?

**Comment by serhiy-storchaka** [comment]
https://docs.python.org/3/library/struct.html#byte-order-size-and-alignment

"""
Notes:
1. Padding is only automatically added between successive structure members. No padding is added at the beginning or the end of the encoded struct.
"""

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
many many thanks for your help!
and fast responses :-)
this explain my oberservations

why only the first 2 bytes are padded?
0xAABBCCDD (4 bytes = real32) to 0x0000AABBCCDD (6 bytes)
and not to 0x0000AABB0000CCDD (8 bytes)

it has something to do with the behavior of the  C compiler’s sizeof expression? and why?

since I need pack / unpack often in my projects, i want to have it completely clarified.

**Comment by serhiy-storchaka** [comment]
Because the size of '2s2s29H' is 62 bytes. If the following C float needs to be aligned on 4 bytes boundary, it should start at offset 64, after 2 padding bytes.

**Comment by 24aaf459-983b-484e-b693-1267079b57de** [comment]
Ah OKAY!
That's the key which makes all clear to me!

I didn't thought at that!

Thanks a lot Serhiy Storchaka for your help!
