### ISSUE TITLE
Show expected input for right shift operator usage in custom "print" error message

### ISSUE THREAD

**Issue by CuriousLearner** [python/cpython#74906]
BPO | [30721](https://bugs.python.org/issue30721)
--- | :---
Nosy | @terryjreedy, @pfmoore, @ncoghlan, @tjguk, @zware, @serhiy-storchaka, @zooba, @CuriousLearner
PRs | <li>python/cpython#2345</li><li>python/cpython#3131</li><li>python/cpython#3155</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-18.12:19:05.924>
created_at = <Date 2017-06-21.05:13:56.910>
labels = ['type-feature', '3.7']
title = 'Show expected input for right shift operator usage in custom "print" error message'
updated_at = <Date 2017-08-19.06:59:41.955>
user = 'https://github.com/CuriousLearner'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-19.06:59:41.955>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-18.12:19:05.924>
closer = 'ncoghlan'
components = []
creation = <Date 2017-06-21.05:13:56.910>
creator = 'CuriousLearner'
dependencies = []
files = []
hgrepos = []
issue_num = 30721
keywords = []
message_count = 12.0
messages = ['296518', '296525', '299128', '299139', '299238', '300484', '300485', '300487', '300488', '300492', '300493', '300569']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'paul.moore', 'ncoghlan', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'CuriousLearner']
pr_nums = ['2345', '3131', '3155']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30721'
versions = ['Python 3.7']
```

</p></details>

**Comment by CuriousLearner** [comment]
While working on issue: http://bugs.python.org/issue30597 to enhance the custom error message by showing expected output in Python3 syntax when someone uses Python2 syntax, a PR was raised: https://github.com/python/cpython/pull/2009, where we just handled the case for print with soft-space and excessive white-space.

In the implementation discussion, an issue was raised to handle the case with right shift operator by Nick as in here:
http://bugs.python.org/issue30597#msg295484

Nick suggested here about the possible patch: https://github.com/python/cpython/pull/2009#issuecomment-307539241

**Comment by ncoghlan** [comment]
The specific error in question here is the one where Python 3 reads the old Python 2 stream redirection syntax as a combination of the right shift operator and tuple creation:

```
>>> print >> sys.stderr, "message"
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'
```

Searching for that error message indicates that people are hitting it reasonably frequently, so we may be able to save them a trip to Google by adding a custom 'Did you mean "print(\<output\>, file={:100!r})'.format(rhs)"? message when the right-shift operand dispatch is about to report the default "no implementation" type error, and the LHS is the print builtin.

**Comment by terryjreedy** [comment]
The test added in the PR passes on linux (Travis) and Mac (op's machine), fails on Windows (Appveyor).  The patch itself modifies abstract.c.  Could some Windows expert take a look?

test_string_with_stream_redirection (test.test_print.TestPy2MigrationHint) ... FAIL
FAIL: test_string_with_stream_redirection (test.test_print.TestPy2MigrationHint)

```pytb
Traceback (most recent call last):
File "C:\projects\cpython\lib\test\test_print.py", line 165, in test_string_with_stream_redirection
'file=<output_stream>)', str(context.exception))
AssertionError: 'Did you mean "print(, file=<output_stream>)' not found in "unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.StringIO'"
```

**Comment by zooba** [comment]
The "op_slot == 96" looks suspicious - how is this value actually supposed to be calculated?

**Comment by ncoghlan** [comment]
Checking how we do it elsewhere, `NB_SLOT(nb_rshift)` looks like the right replacement.

That's a compiler-dependent struct field offset calculation, so a discrepancy there could easily be the cause of a Windows-only failure.

**Comment by serhiy-storchaka** [comment]
New changeset 5e2eb35bbed3e84079165e576cdb50ef36e13493 by Serhiy Storchaka (Sanyam Khurana) in branch 'master':
bpo-30721: Show correct syntax hint in Py3 when using Py2 redirection syntax (bpo-2345)
https://github.com/python/cpython/commit/5e2eb35bbed3e84079165e576cdb50ef36e13493

**Comment by ncoghlan** [comment]
Checking the merged implementation locally, I belatedly noticed that we forgot the trailing question mark on the question:

```
>>> import sys
>>> print >> sys.stderr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"
```

So putting this back to "needs patch" (no NEWS entry needed, just the missing question marks in the patch and the tests).

**Comment by CuriousLearner** [comment]
Ah, sorry for that. I'll just fix that right away in a few mins :)

**Comment by ncoghlan** [comment]
Note that I filed a separate issue to ask Ned about potentially backporting this to 3.6: https://bugs.python.org/issue31232

**Comment by ncoghlan** [comment]
New changeset a7c449b8c08933deabcf329fb74ed1336f6db34f by Nick Coghlan (Sanyam Khurana) in branch 'master':
bpo-30721: Add missing '?' to new error message (GH-3131)
https://github.com/python/cpython/commit/a7c449b8c08933deabcf329fb74ed1336f6db34f

**Comment by ncoghlan** [comment]
And done - thanks folks!

**Comment by ncoghlan** [comment]
New changeset 1a05e87ec75436d818f05a5dabcecaea67334cbd by Nick Coghlan in branch '3.6':
[3.6] bpo-31232: Backport custom print rshift message (GH-3155)
https://github.com/python/cpython/commit/1a05e87ec75436d818f05a5dabcecaea67334cbd
