### ISSUE TITLE
re.sub substitution match group contains wrong value after unmatched pattern was processed

### ISSUE THREAD

**Issue by 50dab7f3-5cb8-4c6f-a78e-0219522e5938** [python/cpython#74905]
BPO | [30720](https://bugs.python.org/issue30720)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-21.03:26:30.353>
created_at = <Date 2017-06-21.02:38:32.644>
labels = ['expert-regex', 'invalid']
title = 're.sub substitution match group contains wrong value after unmatched pattern was processed'
updated_at = <Date 2017-06-21.06:54:30.430>
user = 'https://bugs.python.org/WilliamBudd'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-21.06:54:30.430>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-21.03:26:30.353>
closer = 'serhiy.storchaka'
components = ['Regular Expressions']
creation = <Date 2017-06-21.02:38:32.644>
creator = 'William Budd'
dependencies = []
files = []
hgrepos = []
issue_num = 30720
keywords = []
message_count = 7.0
messages = ['296506', '296508', '296509', '296510', '296511', '296515', '296527']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'William Budd']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30720'
versions = ['Python 3.6']
```

</p></details>

**Comment by 50dab7f3-5cb8-4c6f-a78e-0219522e5938** [comment]
```py
pattern = re.compile('<div>(<p>.*?</p>)</div>', flags=re.DOTALL)
```


----------------------------------------------------------------

\# This works as expected in the following case:

```py
print(re.sub(pattern, '\\1',
             '<div><p>foo</p></div>\n'
             '<div><p>bar</p>123456789</div>\n'))
```


\# which outputs:

\<p\>foo\</p\>
\<div\>\<p\>bar\</p\>123456789\</div\>

\----------------------------------------------------------------

\# However, it does NOT work as I expect in this case:

```py
print(re.sub(pattern, '\\1',
             '<div><p>foo</p>123456789</div>\n'
             '<div><p>bar</p></div>\n'))
```


\# actual output:

\<p\>foo\</p\>123456789\</div\>
\<div\>\<p\>bar\</p\>

\# expected output:

\<div\>\<p\>foo\</p\>123456789\</div\>
\<p\>bar\</p\>

\----------------------------------------------------------------

It seems that pattern matching/substitution iterations only go haywire once the matching iteration immediately prior to it turned out not to be a match. Maybe some internal variable is not cleaned up properly in an edge(?) case triggered by the example above?

**Comment by serhiy-storchaka** [comment]
It works correctly. It finds a substring that starts with '\<div\>\<p\>' and ends with '\</p\>\</div\>' from left to right. The leftmost found substring starts from index 0 and ends before the final '\\n'. Overlapped substrings are not found.

**Comment by 50dab7f3-5cb8-4c6f-a78e-0219522e5938** [comment]
I don't understand... Isn't the "?" in ".\*?" supposed to make the ".\*" matching non-greedy, hence matching the first "\</p\>" rather than the last "\</p\>"?

**Comment by serhiy-storchaka** [comment]
Yes, it is non-greedy. But it needs matching not just '\</p\>', but '\</p\>\</div\>'. After finding the first '\</p\>' it doesn't see the '\</div\>' after it and continue searching until found '\</p\>\</div\>'.

**Comment by 50dab7f3-5cb8-4c6f-a78e-0219522e5938** [comment]
I now see you're right of course. Not a bug after all. Thank you.

I mistakenly assumed that the group boundary ")" would delimit the end of the non-greedy match group. I.e., ".\*?\</p\>" versus ".\*?\</p\>\</div\>".

I don't see a way to accomplish the "even less greedy" variant I'm looking for though...

**Comment by 50dab7f3-5cb8-4c6f-a78e-0219522e5938** [comment]
Doh! This has a really easy solution, doesn't it; just replace "." with "[^\<]": re.compile('\<div\>(\<p\>[^\<]*?\</p\>)\</div\>', flags=re.DOTALL).

Sorry about the noise.

**Comment by serhiy-storchaka** [comment]
Atomic groups can help you: '\<div\>((?\>\<p\>.\*?\</p\>))\</div\>'.

But this feature is not supported in the re module yet (see bpo-433030). You can use the third-party regex module which is compatible with the re module and supports atomic grouping.

```pycon
>>> import regex as re
>>> pattern = re.compile('<div>((?><p>.*?</p>))</div>', flags=re.DOTALL)
>>> print(re.sub(pattern, '\\1',
...              '<div><p>foo</p>123456789</div>\n'
...              '<div><p>bar</p></div>\n'))
<div><p>foo</p>123456789</div>
<p>bar</p>
```
