### ISSUE TITLE
Tools/demo/redemo.py broken

### ISSUE THREAD

**Issue by f2ac4c00-3564-4cdf-8737-2f8da4515403** [python/cpython#74907]
BPO | [30722](https://bugs.python.org/issue30722)
--- | :---
Nosy | @ezio-melotti, @berkerpeksag, @serhiy-storchaka, @mlouielu, @csarn
PRs | <li>python/cpython#2311</li><li>python/cpython#4090</li><li>python/cpython#8501</li><li>python/cpython#8503</li><li>python/cpython#8504</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-27.16:18:23.283>
created_at = <Date 2017-06-21.08:57:43.914>
labels = ['type-bug', '3.7']
title = 'Tools/demo/redemo.py broken'
updated_at = <Date 2018-07-27.16:18:23.282>
user = 'https://github.com/csarn'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-27.16:18:23.282>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-27.16:18:23.283>
closer = 'berker.peksag'
components = ['Demos and Tools']
creation = <Date 2017-06-21.08:57:43.914>
creator = 'Christoph Sarnowski2'
dependencies = []
files = []
hgrepos = []
issue_num = 30722
keywords = ['patch']
message_count = 13.0
messages = ['296530', '296532', '296533', '296535', '296543', '296547', '304825', '304827', '304828', '309024', '322503', '322504', '322506']
nosy_count = 6.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'berker.peksag', 'serhiy.storchaka', 'louielu', 'Christoph Sarnowski2']
pr_nums = ['2311', '4090', '8501', '8503', '8504']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30722'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f2ac4c00-3564-4cdf-8737-2f8da4515403** [comment]
In Python 3.6, the flags in the "re" module became members of an enum.IntFlag, whereas before they were just ints.

This breaks the regex demo in [Tools/demo/redemo.py](https://github.com/python/cpython/blob/main/Tools/demo/redemo.py).

To fix this, in line 86 of redemo.py, 

```py
    getattr(re, name)
```


has to be replaced by 

    getattr(re, name).value

Also, the checkbox for "LOCALE" can be removed (or fixed), as re.LOCALE is invalid for str patterns.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Hi Christoph, chould you provide a small example that breaks the regex demo? thanks!

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Also, would you like to contribute with PR on GitHub?

**Comment by f2ac4c00-3564-4cdf-8737-2f8da4515403** [comment]
Hi, sorry for forgetting steps to reproduce the bug.

Easiest way to see it is to start redemo.py from a console (important on windows), so you can see stdout/stderr.
Then just a click on any of those flag checkboxes leads to an exception backtrace printed on the console.

And to demonstrate that the flag checkbox does not work, enter ".\*" (without quotes) as the pattern, and any multiline string as the string to search, and activate the checkbox "MULTILINE".
Correct behaviour: no exception, all lines of the string get highlighted as the first match
Erroneous (actual) behaviour: An exception traceback gets printed: '\_tkinter.TclError: expected integer but got "RegexFlag.MULTILINE"'
and only the first line is highlighted as first match, demonstrating that the MULTILINE flag is in fact not active.


When it comes to a pull request, I could do that for the change that I proposed. But regarding the "LOCALE" flag, the better solution (in my opinion) would be to make it work instead of just removing it, but that is a more elaborate change that I am not able to spend time on.

What would you suggest?
a) I provide a pull request, leaving "LOCALE" flag behaviour broken
b) I provide a pull request, removing "LOCALE" flag (to be introduced again when someone is willing to fix it)

**Comment by serhiy-storchaka** [comment]
I think ideally it would be nice to provide a switch between Unicode and bytes and disable the LOCALE flag in the Unicode mode. But this is too complex task. I think it is better to remove LOCALE.

**Comment by f2ac4c00-3564-4cdf-8737-2f8da4515403** [comment]
By the way, I confused the flags, in my error-reproduction steps, instead of the re.MULTILINE flag, it is the re.DOTALL flag that should lead to all lines being matched by ".\*".

**Comment by berkerpeksag** [comment]
New changeset 62adc55aff0b78447568f73bd1abc610d2784bf8 by Berker Peksag (Christoph Sarnowski) in branch 'master':
bpo-30722: Make redemo work with Python 3.6+ (GH-2311)
https://github.com/python/cpython/commit/62adc55aff0b78447568f73bd1abc610d2784bf8

**Comment by berkerpeksag** [comment]
New changeset a5f9d24c171c7e3a3715161fd16b747c7dcaf76f by Berker Peksag (Miss Islington (bot)) in branch '3.6':
bpo-30722: Make redemo work with Python 3.6+ (GH-2311)
https://github.com/python/cpython/commit/a5f9d24c171c7e3a3715161fd16b747c7dcaf76f

**Comment by berkerpeksag** [comment]
Thank you, Christoph. I wasn't aware of [Tools/demo/redemo.py](https://github.com/python/cpython/blob/main/Tools/demo/redemo.py) and I must say it was fun to play with while reviewing [PR 2311](https://github.com/python/cpython/pull/2311).

**Comment by ezio-melotti** [comment]
A comment on a closed (and somewhat unrelated) issue is unlikely to receive much feedback.
If you want to improve `redemo.py`, I would suggest creating a new issue and then address the problems with one (or more) PR(s) instead.

Also note that "refactoring" issues -- especially on a demo like `redemo.py` -- might be rejected, so you might also want to post on https://discuss.python.org/ for feedback before creating issues/PRs.
