### ISSUE TITLE
Swap doesn't work in some circumstances

### ISSUE THREAD

**Issue by f1827f43-3dd6-4db0-a6f7-1785054e3f5a** [python/cpython#74914]
BPO | [30729](https://bugs.python.org/issue30729)
--- | :---
Nosy | @rhettinger, @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-22.06:17:39.543>
created_at = <Date 2017-06-22.05:38:50.902>
labels = ['OS-mac', 'type-bug', 'invalid']
title = "Swap doesn't work in some circumstances"
updated_at = <Date 2017-06-22.06:17:39.470>
user = 'https://bugs.python.org/Ikaros'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-22.06:17:39.470>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-22.06:17:39.543>
closer = 'rhettinger'
components = ['macOS']
creation = <Date 2017-06-22.05:38:50.902>
creator = 'Ikaros'
dependencies = []
files = []
hgrepos = []
issue_num = 30729
keywords = []
message_count = 2.0
messages = ['296614', '296615']
nosy_count = 4.0
nosy_names = ['rhettinger', 'ronaldoussoren', 'ned.deily', 'Ikaros']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30729'
versions = ['Python 3.5']
```

</p></details>

**Comment by f1827f43-3dd6-4db0-a6f7-1785054e3f5a** [comment]
Suppose I have two lists 
L1 = [1,3,2,4], L2 = [1,3,2,4]
L1[1], L1[2] = L1[2], L1[1]
This gives me L1 = [1,2,3,4]
However, if I write
L2[1], L2[L2[1] - 1] = L2[L2[1] - 1], L2[1]
This gives me back the same L2 = [1,3,2,4]
I am not sure if this is a mistake ... If it is what it intended to do please tell me.

**Comment by rhettinger** [comment]
This is the expected behavior.
The assignments are made left-to-right.
The first use of L2[1] is updated BEFORE the second use as index.

The assignments are equivalent to:
\==================================
```pycon
>>> L1 = [1,3,2,4]
>>> L2 = [1,3,2,4]
>>> tup = L2[L2[1] - 1], L2[1]
>>> tup
(2, 3)
>>> L2[1] = tup[0]
>>> L2[L2[1] - 1] = tup[1]
>>> L2
[1, 3, 2, 4]
```


Which is the same as you observed
\=================================
```pycon
>>> L1 = [1,3,2,4]
>>> L2 = [1,3,2,4]
>>> L2[1], L2[L2[1] - 1] = L2[L2[1] - 1], L2[1]
>>> L2
[1, 3, 2, 4]
```


The core issue is that L2[1] is being used twice during the series of assignments.  First it gets updated with L2[1] = 3.  Then L2[1] is used again AFTER it has been updated.
