### ISSUE TITLE
Typo in Document What's New: Calendar

### ISSUE THREAD

**Issue by 25086f34-4d81-4875-a647-be124308f5b5** [python/cpython#74918]
BPO | [30733](https://bugs.python.org/issue30733)
--- | :---
Nosy | @doerwalter, @Mariatta
PRs | <li>python/cpython#2414</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-06-26.16:35:47.141>
created_at = <Date 2017-06-22.12:34:09.489>
labels = ['type-feature', '3.7', 'docs']
title = "Typo in Document What's New: Calendar"
updated_at = <Date 2017-06-26.16:35:47.140>
user = 'https://bugs.python.org/JonathonVandezande'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-26.16:35:47.140>
actor = 'doerwalter'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-06-26.16:35:47.141>
closer = 'doerwalter'
components = ['Documentation']
creation = <Date 2017-06-22.12:34:09.489>
creator = 'Jonathon Vandezande'
dependencies = []
files = []
hgrepos = []
issue_num = 30733
keywords = []
message_count = 3.0
messages = ['296625', '296912', '296914']
nosy_count = 4.0
nosy_names = ['doerwalter', 'docs@python', 'Mariatta', 'Jonathon Vandezande']
pr_nums = ['2414']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30733'
versions = ['Python 3.7']
```

</p></details>

**Comment by 25086f34-4d81-4875-a647-be124308f5b5** [comment]
Says:
The HTMLCalendar has added new class attribute which ease the customisation the CSS classes in the produced HTML calendar. (Contributed by Oz Tiram in bpo-30095.)

Should say:
The HTMLCalendar has added new class attributes which ease the customisation of the CSS classes in the produced HTML calendar. (Contributed by Oz Tiram in bpo-30095.)


Summary of changes:
'attribute' should be plural
Missing an 'of' in front of 'the CSS classes', could also substitute 'of' for 'the'

**Comment by doerwalter** [comment]
Should be fixed now. Thanks for noticing it.
