### ISSUE TITLE
Use correct executable manifest for windows

### ISSUE THREAD

**Issue by 7c2bc60f-8be0-4c1a-9402-5cdaffcbe363** [python/cpython#74916]
BPO | [30731](https://bugs.python.org/issue30731)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
PRs | <li>python/cpython#2328</li><li>python/cpython#2699</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-07-13.19:52:27.150>
created_at = <Date 2017-06-22.09:33:42.489>
labels = ['type-feature', '3.7', 'OS-windows']
title = 'Use correct executable manifest for windows'
updated_at = <Date 2017-07-13.19:52:27.149>
user = 'https://bugs.python.org/tumagonx'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-13.19:52:27.149>
actor = 'steve.dower'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-07-13.19:52:27.150>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-06-22.09:33:42.489>
creator = 'tumagonx'
dependencies = []
files = []
hgrepos = []
issue_num = 30731
keywords = []
message_count = 6.0
messages = ['296619', '296628', '296637', '296657', '298309', '298310']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'tumagonx']
pr_nums = ['2328', '2699']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30731'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 7c2bc60f-8be0-4c1a-9402-5cdaffcbe363** [comment]
I think there is typo in python default manifest (applies to exe dll and pyd) in official installation.

currently written as:
\<trustinfo\>
...
\</trustInfo\>

should be:
\<trustInfo xmlns="urn:schemas-microsoft-com:asm.v3"\>
...
\</trustInfo\>

notice the lowercase "i" in incorrect manifest

**Comment by zooba** [comment]
What is the impact of this error? I know of people who are relying on the manifest who have not raised any issue, so perhaps it isn't actually that important?

**Comment by 7c2bc60f-8be0-4c1a-9402-5cdaffcbe363** [comment]
Not really, just want to be correct... AFAIK wrong manifest like that will prevent execution on older Windows such XP saying application not configured properly. Apparently earlier Windows has been stricter. But it's not like official python 3.6 support XP.

**Comment by 7c2bc60f-8be0-4c1a-9402-5cdaffcbe363** [comment]
@Segev
oops, must be my own typo "i" when I try repair the manifest. sorry about that.

**Comment by zooba** [comment]
New changeset c40ad03bf2693b4af539978f1274e57b85367547 by Steve Dower (Segev Finer) in branch 'master':
bpo-30731: python.manifest fix (bpo-2328)
https://github.com/python/cpython/commit/c40ad03bf2693b4af539978f1274e57b85367547

**Comment by zooba** [comment]
New changeset d8e522f7cf8d59993acae9409b6af0ee9a35038f by Steve Dower in branch '3.6':
bpo-30731: python.manifest fix (bpo-2328) (bpo-2699)
https://github.com/python/cpython/commit/d8e522f7cf8d59993acae9409b6af0ee9a35038f
