### ISSUE TITLE
Support Unicode 10.0

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#74921]
BPO | [30736](https://bugs.python.org/issue30736)
--- | :---
Nosy | @malemburg, @rhettinger, @vstinner, @benjaminp, @ezio-melotti, @stevendaprano
PRs | <li>python/cpython#2344</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-23.05:31:56.498>
created_at = <Date 2017-06-22.13:46:00.812>
labels = ['type-feature', '3.7', 'expert-unicode']
title = 'Support Unicode 10.0'
updated_at = <Date 2017-06-23.05:31:56.497>
user = 'https://github.com/stevendaprano'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-23.05:31:56.497>
actor = 'benjamin.peterson'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-23.05:31:56.498>
closer = 'benjamin.peterson'
components = ['Unicode']
creation = <Date 2017-06-22.13:46:00.812>
creator = 'steven.daprano'
dependencies = []
files = []
hgrepos = []
issue_num = 30736
keywords = []
message_count = 4.0
messages = ['296630', '296633', '296654', '296679']
nosy_count = 7.0
nosy_names = ['lemburg', 'rhettinger', 'vstinner', 'benjamin.peterson', 'ezio.melotti', 'mrabarnett', 'steven.daprano']
pr_nums = ['2344']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30736'
versions = ['Python 3.7']
```

</p></details>

**Comment by stevendaprano** [comment]
Unicode 10.0 is now finalized:

http://blog.unicode.org/2017/06/announcing-unicode-standard-version-100.html

It would be good if Python 3.7 would support it. (I think that Python currently supports Unicode 8?)

**Comment by rhettinger** [comment]
+1

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
@Steven: Python 3.6 supports Unicode 9.


```pycon
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import unicodedata
>>> unicodedata.unidata_version
'9.0.0'
```

**Comment by benjaminp** [comment]
New changeset 279a96206f3118a482d10826a1e32b272db4505d by Benjamin Peterson in branch 'master':
bpo-30736: upgrade to Unicode 10.0 (bpo-2344)
https://github.com/python/cpython/commit/279a96206f3118a482d10826a1e32b272db4505d
