### ISSUE TITLE
https://www.pypi-mirrors.org/ error 503

### ISSUE THREAD

**Issue by c727457d-2967-48a7-abd3-394d46bb14f3** [python/cpython#74926]
BPO | [30741](https://bugs.python.org/issue30741)
--- | :---
Nosy | @brettcannon, @vstinner, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-01.00:37:45.024>
created_at = <Date 2017-06-23.14:24:00.083>
labels = []
title = 'https://www.pypi-mirrors.org/ error 503'
updated_at = <Date 2017-07-01.00:37:45.005>
user = 'https://bugs.python.org/LucZimmermann'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-01.00:37:45.005>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-01.00:37:45.024>
closer = 'ned.deily'
components = []
creation = <Date 2017-06-23.14:24:00.083>
creator = 'Luc Zimmermann'
dependencies = []
files = []
hgrepos = []
issue_num = 30741
keywords = []
message_count = 5.0
messages = ['296721', '296722', '296723', '296727', '297460']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'vstinner', 'ned.deily', 'Luc Zimmermann']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30741'
versions = []
```

</p></details>

**Comment by c727457d-2967-48a7-abd3-394d46bb14f3** [comment]
is that linked with the certificate error on pypi ? 

you redirect http request to https, but you still listen 80 and not 443 ?

**Comment by vstinner** [comment]
http://www.pypi-mirrors.org/ (clear text) works and redirects to https://www.pypi-mirrors.org/ (TLS) which fails with HTTP error 503:

503 Service Unavailable
No server is available to handle this request.

**Comment by vstinner** [comment]
See also issue bpo-30739:
  Could not fetch URL https://pypi.python.org/simple/PyJWT/: connection error: [SSL: CERTIFICATE_VERIFY_FAILED] unknown error (_ssl.c)

**Comment by brettcannon** [comment]
So is this a bug in Python or a problem with the website? If it's the former then the title is misleading and we should clarify it, and if it's the latter this should be closed as "third party".

**Comment by ned-deily** [comment]
This doesn't appear to be a Python issue.  If necessary, suggest follow up with either pip or the PyPA packaging-problems issue tracker:

https://github.com/pypa/packaging-problems/issues
