### ISSUE TITLE
VS2015 support for 2.7 branch

### ISSUE THREAD

**Issue by 2ec5c540-4650-469c-b2b8-2582913a47f2** [python/cpython#74927]
BPO | [30742](https://bugs.python.org/issue30742)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
PRs | <li>python/cpython#2446</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-27.16:10:13.662>
created_at = <Date 2017-06-23.21:27:58.066>
labels = ['build', 'OS-windows']
title = 'VS2015 support for 2.7 branch'
updated_at = <Date 2017-06-27.16:10:13.658>
user = 'https://bugs.python.org/DenanZuki'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-27.16:10:13.658>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-27.16:10:13.662>
closer = 'steve.dower'
components = ['Build', 'Windows']
creation = <Date 2017-06-23.21:27:58.066>
creator = 'D\xc5\xbeenan Zuki\xc4\x87'
dependencies = []
files = []
hgrepos = []
issue_num = 30742
keywords = []
message_count = 2.0
messages = ['296738', '297053']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'D\xc5\xbeenan Zuki\xc4\x87']
pr_nums = ['2446']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30742'
versions = ['Python 2.7']
```

</p></details>

**Comment by 2ec5c540-4650-469c-b2b8-2582913a47f2** [comment]
In VS2015 timezone and friends have been replace by \_timezone (related bpo-24643). The second problem is missing \_PyVerify_fd during linking phase.

**Comment by zooba** [comment]
There are \*many* more fixes required than just these. We're not prepared to take the changes into 2.7 at this stage, and we don't want to encourage people to think that MSVC 14.0 or later are supported when we know that it's incomplete.

I'd suggest creating a fork and making your updates in that. You are welcome to promote it as MSVC 14.0-compatible sources for anyone else who wants to build 2.7 from them, and you may find more contributors to help you that way.
