### ISSUE TITLE
unittest discover does not mention module file must be named with "test_" prefix

### ISSUE THREAD

**Issue by 4b6ca53c-85a5-4872-a94a-9b0e5f3ca189** [python/cpython#74928]
BPO | [30743](https://bugs.python.org/issue30743)
--- | :---
Nosy | @zware

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-27.20:35:24.525>
created_at = <Date 2017-06-23.21:57:36.855>
labels = ['type-bug', 'invalid', 'docs']
title = 'unittest discover does not mention module file must be named with "test_" prefix'
updated_at = <Date 2017-06-27.20:35:24.524>
user = 'https://bugs.python.org/alex75'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-27.20:35:24.524>
actor = 'alex.75'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-06-27.20:35:24.525>
closer = 'alex.75'
components = ['Documentation']
creation = <Date 2017-06-23.21:57:36.855>
creator = 'alex.75'
dependencies = []
files = []
hgrepos = []
issue_num = 30743
keywords = []
message_count = 5.0
messages = ['296740', '296741', '296742', '297073', '297074']
nosy_count = 3.0
nosy_names = ['docs@python', 'zach.ware', 'alex.75']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30743'
versions = ['Python 3.6']
```

</p></details>

**Comment by 4b6ca53c-85a5-4872-a94a-9b0e5f3ca189** [comment]
1. execute "python -m unittest"
2. Result: 0 test found
3. Change file name from "aaaTest.py" to "test_aaa.py" 
4. execute "python -m unittest"
3. Result: Ran 1 tests in 000.0s

Module file MUST be named using the prefiux "test_".

The page "https://docs.python.org/3/library/unittest.html"
does not mention this MANDATORY rule.

I went to this conclusion because I readed the documentation without find any point about the naming convention of modules and than looking for this specific rule searching "test_" and "test_ " without any result.

Regards,

Alessandro

**Comment by zware** [comment]
Does this cover what you're looking for?

https://docs.python.org/3/library/unittest.html#cmdoption-unittest-discover-p

**Comment by 4b6ca53c-85a5-4872-a94a-9b0e5f3ca189** [comment]
If you refer to the -p ("pattern" parameter) I think not.
I have my module named aaaTest.py.
I is is not mentioned that discover look for modules named "test_" for which reason I have to use a pattern?

If you refer to -s ("start-directory" parameter) same thing: for which reason I have to assume my aaaTest.py module is not recognized as a test?

**Comment by zware** [comment]
This all seems to be covered in https://docs.python.org/3/library/unittest.html#test-discovery

```sh
$ cat aaaTest.py 
import unittest
```



```py
class TestAAA(unittest.TestCase):

    def test_something(self):
        self.assertTrue(True)


if __name__ == '__main__':
    unittest.main()
$ python3 -m unittest discover -v -p "*Test.py"
test_something (aaaTest.TestAAA) ... ok
```


----------------------------------------------------------------------
Ran 1 test in 0.000s

OK



As the `--pattern` documentation says, the default pattern is "test*.py" which does not match "aaaTest.py".

**Comment by 4b6ca53c-85a5-4872-a94a-9b0e5f3ca189** [comment]
You are right.

As the `--pattern` documentation says, the default pattern is "test*.py" which does not match "aaaTest.py".

I had looking for the wrong pattern.

Thanks,

Alex
