### ISSUE TITLE
Non-atomic and unusual (wrong) rename behavior under OS X

### ISSUE THREAD

**Issue by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [python/cpython#74934]
BPO | [30749](https://bugs.python.org/issue30749)
--- | :---
Nosy | @ronaldoussoren, @ned-deily
Files | <li>[renameatomic.py](https://bugs.python.org/file46973/renameatomic.py "Uploaded as text/plain at 2017-06-24.22:59:56 by Alex Groce")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-26.08:11:10.558>
created_at = <Date 2017-06-24.22:59:56.646>
labels = ['OS-mac', 'type-bug', 'invalid']
title = 'Non-atomic and unusual (wrong) rename behavior under OS X'
updated_at = <Date 2017-06-26.08:11:10.556>
user = 'https://bugs.python.org/AlexGroce'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-26.08:11:10.556>
actor = 'Alex Groce'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-26.08:11:10.558>
closer = 'Alex Groce'
components = ['macOS']
creation = <Date 2017-06-24.22:59:56.646>
creator = 'Alex Groce'
dependencies = []
files = ['46973']
hgrepos = []
issue_num = 30749
keywords = []
message_count = 6.0
messages = ['296794', '296837', '296852', '296853', '296854', '296855']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'Alex Groce']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30749'
versions = []
```

</p></details>

**Comment by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [comment]
Attached file causes a failed rename, which is fine.  However, after the failed rename, the directory structure has changed (and the error reported is not very helpful).  Behavior does not match Linux or Windows behavior.

Discovered using random testing to check pyfakefs for conformance with os module, using TSTL tool.

**Comment by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [comment]
Checked, and this is a problem on Python 3 as well as 2.7.

**Comment by ronaldoussoren** [comment]
What version of macOS did you test on?

**Comment by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [comment]
Tested on latest Mac OS; mv at command line does the right thing, have not checked a C rename yet.

**Comment by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [comment]
```c
#include <stdio.h>
#include <stdlib.h>
#include <errno.h>
#include <sys/stat.h>

int main () {
  system("rm -rf testingdir");
  mkdir("testingdir",S_IRWXU);  
  mkdir("testingdir/a",S_IRWXU);
  mkdir("testingdir/a/a",S_IRWXU);
  mkdir("testingdir/a/a/a",S_IRWXU);
  printf("BEFORE:\n");
  system("ls -lR testingdir");
  int res = rename("testingdir","testingdir/a/a/a");
  printf("res = %d, ERRNO = %d\n",res,errno);
  printf("AFTER:\n");
  system("ls -lR testingdir");  
}
```



shows that it appears to be an OS X rename issue, not a Python problem.

Lowering # directories in the chain by 1 reverts to errno 22 and correct behavior, but it's at the OS level, not Python.

**Comment by d8c60c1f-0a86-4bbf-81bb-67ddde9d6437** [comment]
Looks to be OS X rename, not Python
