### ISSUE TITLE
Warnings in Modules/_winapi.c

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#74930]
BPO | [30745](https://bugs.python.org/issue30745)
--- | :---
Nosy | @pfmoore, @tjguk, @ned-deily, @zware, @serhiy-storchaka, @zooba, @segevfiner
PRs | <li>python/cpython#2376</li><li>python/cpython#2378</li><li>python/cpython#2379</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-06-24.13:26:58.471>
created_at = <Date 2017-06-24.10:13:59.533>
labels = ['build', '3.7', 'OS-windows']
title = 'Warnings in Modules/_winapi.c'
updated_at = <Date 2017-07-08.04:51:39.063>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-08.04:51:39.063>
actor = 'ned.deily'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-06-24.13:26:58.471>
closer = 'serhiy.storchaka'
components = ['Windows']
creation = <Date 2017-06-24.10:13:59.533>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30745
keywords = []
message_count = 7.0
messages = ['296761', '296763', '296764', '296766', '296768', '296771', '297930']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'ned.deily', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'Segev Finer']
pr_nums = ['2376', '2378', '2379']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30745'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
..\\Modules\\_winapi.c(886): warning C4090: 'function': different 'const' qualifiers
..\\Modules\\_winapi.c(848): warning C4101: 'wenvironment_size': unreferenced local variable

Added in d174d24a5d37d1516b885dc7c82f71ecd5930700

**Comment by serhiy-storchaka** [comment]
Thank you for noticing this Segev. I hope the following PR fixes warnings.

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
I tried the PR locally and I didn't get the warnings. :)

**Comment by serhiy-storchaka** [comment]
New changeset 0ee32c148119031e19c79359f5c4789ee69fa355 by Serhiy Storchaka in branch 'master':
bpo-30745: Fix compiler warnings introduced in bpo-30730. (bpo-2376)
https://github.com/python/cpython/commit/0ee32c148119031e19c79359f5c4789ee69fa355

**Comment by serhiy-storchaka** [comment]
New changeset 0e1f9e8d3ea82262cbb9a403b70a884da5e6a6ac by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30745: Fix compiler warnings introduced in bpo-30730. (GH-2376) (bpo-2378)
https://github.com/python/cpython/commit/0e1f9e8d3ea82262cbb9a403b70a884da5e6a6ac

**Comment by serhiy-storchaka** [comment]
New changeset e0d446e9caa38923e43818f78c94f95fe0aa995e by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30745: Fix compiler warnings introduced in bpo-30730. (GH-2376) (bpo-2379)
https://github.com/python/cpython/commit/e0d446e9caa38923e43818f78c94f95fe0aa995e

**Comment by ned-deily** [comment]
New changeset d1d65015fca44b8d1f0b1df78694310270f03a6d by Ned Deily (Serhiy Storchaka) in branch '3.6':
[3.6] bpo-30745: Fix compiler warnings introduced in bpo-30730. (GH-2376) (bpo-2378)
https://github.com/python/cpython/commit/d1d65015fca44b8d1f0b1df78694310270f03a6d
