### ISSUE TITLE
textwrap.dedent mishandles empty lines

### ISSUE THREAD

**Issue by 8a0c69e7-f5ea-4ea3-8880-4903ed9740d7** [python/cpython#74939]
BPO | [30754](https://bugs.python.org/issue30754)
--- | :---
Nosy | @gvanrossum, @birkenfeld, @terryjreedy, @gpshead, @ncoghlan, @pitrou, @Julian, @vadmium, @serhiy-storchaka, @emilyemorehouse, @miss-islington, @tmblweed
PRs | <li>python/cpython#14469</li><li>python/cpython#14475</li><li>python/cpython#14476</li><li>python/cpython#14477</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-06-30.04:27:50.173>
created_at = <Date 2017-06-25.15:25:24.508>
labels = ['easy', '3.8', 'type-bug', '3.7', 'docs']
title = 'textwrap.dedent mishandles empty lines'
updated_at = <Date 2019-06-30.04:41:58.325>
user = 'https://github.com/Julian'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-30.04:41:58.325>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-06-30.04:27:50.173>
closer = 'gregory.p.smith'
components = ['Documentation']
creation = <Date 2017-06-25.15:25:24.508>
creator = 'Julian'
dependencies = []
files = []
hgrepos = []
issue_num = 30754
keywords = ['patch', 'easy']
message_count = 13.0
messages = ['296825', '296961', '296983', '296997', '297002', '297007', '343988', '345411', '345420', '346909', '346911', '346912', '346913']
nosy_count = 13.0
nosy_names = ['gvanrossum', 'georg.brandl', 'terry.reedy', 'gregory.p.smith', 'ncoghlan', 'pitrou', 'docs@python', 'Julian', 'martin.panter', 'serhiy.storchaka', 'emilyemorehouse', 'miss-islington', 'syadlapalli']
pr_nums = ['14469', '14475', '14476', '14477']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30754'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 8a0c69e7-f5ea-4ea3-8880-4903ed9740d7** [comment]
⊙  python2 -c 'from textwrap import dedent; print repr(dedent(" " * 2 + "\\n" + " " * 4 + "\\n"))'
'\\n\\n'

instead of the presumed '\\n  \\n'

The same appears to be the case for py3.6.


(At first glance, this seems unrelated to http://bugs.python.org/issue19479 although that issue seems to have an unreviewed patch that changes the implementation, so it might also "accidentally" fix the issue).

**Comment by vadmium** [comment]
Some people like to avoid indented blank lines, treating them the same as trailing whitespace. I suspect this behaviour may be intentional.

**Comment by emilyemorehouse** [comment]
I concur with Martin, whitespace is not expected to be preserved on whitespace-only lines nor even considered when finding common leading whitepace. To illustrate this, see the examples below:

The following yields the same (expected) results:

    > python2 -c 'from textwrap import dedent; print repr(dedent(" " * 2 + "\n" + " " * 4 + "\t\n"))'
    > '\n\n'

And a simplified version of a test case from test_textwrap.py:

    > python2 -c 'from textwrap import dedent; print repr(dedent("  Foo\n \n"))'
    > 'Foo\n\n'

**Comment by terryjreedy** [comment]
This is related to bpo-19479 at least in the sense of addressing the same module, and being about   It has a patch, so it would be good to accept or reject. Martin, could you take a look?  There is currently no expert listed for textwrap.  Georg is current dormant as far as cpython is concerned.

To call the current behavior a bug, it should conflict with somethings in the docs.  Otherwise, it may be an enhancement proposal, in which case python-ideas would be a good place to discuss.  Julian, look in the docs to see if you find a conflict.

**Comment by serhiy-storchaka** [comment]
I think the current behavior is useful, but undocumented. Otherwise a blank line starting with unmatched whitespaces (e.g. "  foo\\n\\t\\n  bar") would block deindenting.

This also matches the behavior of Python parser which ignores all whitespaces in blank lines.

```pycon
>>> exec('if 1:\n\tpass\n  pass\n')                                                                                                                                                         
Traceback (most recent call last):                                                                                                                                                              
  File "<stdin>", line 1, in <module>                                                                                                                                                           
  File "<string>", line 3                                                                                                                                                                       
    pass                                                                                                                                                                                        
       ^                                                                                                                                                                                        
IndentationError: unindent does not match any outer indentation level                                                                                                                           
>>> exec('if 1:\n\t\n  pass\n')                                                                                                                                                             
>>> 
```


Added Antoine and Nick as yet two experts of the textwrap module.

**Comment by 8a0c69e7-f5ea-4ea3-8880-4903ed9740d7** [comment]
@Terry IMHO it conflicts with the fundamental description of the function.

> Remove any common leading whitespace from every line in text.

If this behavior is intentional, textwrap.dedent does not do that, it does that, but also some other stuff.

As for whether it \*should* do that, I can't really see how it'd be a good idea to do this -- whether indented blank lines are like trailing whitespace or not is a good reason not to \*add* them, but if you've got some already, textwrap.dedent isn't responsible for them, they were there already.

It is also extremely hard to get the other behavior given a function that does this one, but trivial to do the reverse.

Also, the #1 reason to use textwrap.dedent (and also the very next line of the docstring after the one I quoted) is to line up sections of source code. With this behavior, that usecase goes away any time you need trailing whitespace, which is exactly how I found this behavior, by unittesting a function that was returning:

textwrap.dedent(
    """
    foo '
        bar
        baz
    

        quux
     '
    """,
)
