### ISSUE TITLE
not able to execute print command on page 16 of documentation

### ISSUE THREAD

**Issue by baee580a-8bbe-4608-bb86-9d9a65204f58** [python/cpython#74938]
BPO | [30753](https://bugs.python.org/issue30753)
--- | :---
Nosy | @stevendaprano
Files | <li>[1.png](https://bugs.python.org/file46974/1.png "Uploaded as image/png at 2017-06-25.11:11:26 by Vishal Devgn"): png image from python 3.6</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-25.11:26:20.624>
created_at = <Date 2017-06-25.11:11:27.078>
labels = ['build', 'invalid']
title = 'not able to execute print command on page 16 of documentation'
updated_at = <Date 2017-06-25.11:26:20.614>
user = 'https://bugs.python.org/VishalDevgn'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-25.11:26:20.614>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-25.11:26:20.624>
closer = 'steven.daprano'
components = []
creation = <Date 2017-06-25.11:11:27.078>
creator = 'Vishal Devgn'
dependencies = []
files = ['46974']
hgrepos = []
issue_num = 30753
keywords = []
message_count = 2.0
messages = ['296821', '296822']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'Vishal Devgn']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30753'
versions = ['Python 3.6']
```

</p></details>

**Comment by baee580a-8bbe-4608-bb86-9d9a65204f58** [comment]
```pycon
>>> a, b = 0, 1
>>> while b < 1000:
... print(b, end=',')
... a, b = b, a+b
```


in 3.6 as soon as i write print command, it displays an indentation error.

**Comment by stevendaprano** [comment]
This is a bug in your code, not Python, and the error tells you how to fix it. You have to indent the block.

```pycon
>>> while b < 1000:
...     print(b, end=',')
...     a, b = b, a+b
```


Remember to press TAB or spacebar inside indented blocks.

You should work through the tutorial.

https://docs.python.org/3/tutorial/index.html

By the way, you say page 16 of which documentation? Are you reading from a book? Which book?
