### ISSUE TITLE
There is functionality bug in linecache library.

### ISSUE THREAD

**Issue by 3074b4ff-58e6-4884-933f-26e3fef7b366** [python/cpython#74948]
BPO | [30763](https://bugs.python.org/issue30763)
--- | :---
Nosy | @gvanrossum, @rhettinger, @serhiy-storchaka, @emilyemorehouse

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-27.16:38:14.629>
created_at = <Date 2017-06-26.11:30:08.017>
labels = ['invalid', 'type-bug', 'library']
title = 'There is functionality bug in linecache library.'
updated_at = <Date 2017-06-27.16:38:14.628>
user = 'https://bugs.python.org/YangXiao'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-27.16:38:14.628>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-27.16:38:14.629>
closer = 'gvanrossum'
components = ['Library (Lib)']
creation = <Date 2017-06-26.11:30:08.017>
creator = 'Yang Xiao'
dependencies = []
files = []
hgrepos = []
issue_num = 30763
keywords = []
message_count = 5.0
messages = ['296874', '296875', '296988', '296998', '297006']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'rhettinger', 'serhiy.storchaka', 'emilyemorehouse', 'Yang Xiao']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30763'
versions = ['Python 2.7']
```

</p></details>

**Comment by 3074b4ff-58e6-4884-933f-26e3fef7b366** [comment]
There is a functionality bug in linecache library.

>\>test.py\<\<
import linecache

```py
def test_getline(f):
    print linecache.getlines(f)


if __name__ == "__main__":
    tf1 = 'aaa'
    with open(tf1,'w') as f:
        f.write('good morning\n')
    test_getline(tf1)

    tf2 = 'bbb'
    with open(tf2,'w') as f:
        f.write('good evening\n')
    test_getline(tf2)

    tf1 = 'aaa'
    with open(tf1,'w') as f:
        f.write('good morning 123\n')
    test_getline(tf1)

    tf2 = 'bbb'
    with open(tf2,'w') as f:
        f.write('good evening 123\n')
    test_getline(tf2)
```


The expectant output shoule be:
['good morning\\n']
['good evening\\n']
['good morning\\n']
['good evening\\n']

However, the script above outputs below:
['good morning\\n']
['good evening\\n']
['good morning\\n']
['good evening\\n']

I think there is a bug about implementation of linecache library.

**Comment by 3074b4ff-58e6-4884-933f-26e3fef7b366** [comment]
Sorry, there is a mistake in [msg296874](https://bugs.python.org/msg296874).

The expectant output shoule be:
['good morning\\n']
['good evening\\n']
['good morning 123\\n']
['good evening 123\\n']

**Comment by emilyemorehouse** [comment]
This is the expected functionality of linecache. As each file is read, it is stored in a cache, subsequent calls using linecache do not check to see if the file has changed.

If you know that the file has changed, you should call linecache.checkcache() to check all files or linecache.checkcache(filename) to check a specific file. (https://docs.python.org/2/library/linecache.html#linecache.checkcache)


[Since no one is listed in the Experts Index, I've included some other contributors to linecache who can assist in closing out this issue]

**Comment by gvanrossum** [comment]
You nailed it, Emily! This is not a bug (though the docs could be a bit more upfront about this -- just having "cache" in the name doesn't cut it these days :-).

If either Serhiy or Raymond agrees they can close the issue (we won't wait for the third vote). If we don't hear from them within a reasonable time we can also close the issue.

**Comment by serhiy-storchaka** [comment]
I concur with Emily and Guido. This is not a bug. Maybe this should be documented more explicitly if "cache" in the name is not enough, I don't know. I have no any special relation to the linecache module, maybe just once fixed a bug or two.
