### ISSUE TITLE
locale.normalize() and getdefaultlocale() convert C.UTF-8 to en_US.UTF-8

### ISSUE THREAD

**Issue by af4925dc-98b6-440f-9623-c180bdc314be** [python/cpython#74940]
BPO | [30755](https://bugs.python.org/issue30755)
--- | :---
Nosy | @malemburg, @ncoghlan, @mattheww, @benjaminp, @serhiy-storchaka, @hroncok, @gordonmessmer, @websurfer5
PRs | <li>python/cpython#14925</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-25.16:58:59.153>
labels = ['3.7', '3.8']
title = 'locale.normalize() and getdefaultlocale() convert C.UTF-8 to en_US.UTF-8'
updated_at = <Date 2019-07-29.15:54:44.990>
user = 'https://github.com/mattheww'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-29.15:54:44.990>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-06-25.16:58:59.153>
creator = 'mattheww'
dependencies = []
files = []
hgrepos = []
issue_num = 30755
keywords = ['patch']
message_count = 8.0
messages = ['296828', '297342', '302981', '302982', '347520', '347521', '347528', '348367']
nosy_count = 8.0
nosy_names = ['lemburg', 'ncoghlan', 'mattheww', 'benjamin.peterson', 'serhiy.storchaka', 'hroncok', 'gordonmessmer', 'Jeffrey.Kintscher']
pr_nums = ['14925']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue30755'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by af4925dc-98b6-440f-9623-c180bdc314be** [comment]
I have a system where the default locale is C.UTF-8, and en_US.UTF-8 is
not installed.

But locale.normalize() unhelpfully converts "C.UTF-8" to "en_US.UTF-8".

So the following crashes for me:

  python3.6 -c "import locale;locale.setlocale(locale.LC_ALL, ('C', 'UTF-8'))"


Similarly getdefaultlocale() returns ('en_US', 'UTF-8'), so this crashes too:

  export LANG=C.UTF-8
  unset LC_CTYPE
  unset LC_ALL
  unset LANGUAGE
  python3.6 -c "import locale;locale.setlocale(locale.LC_ALL, locale.getdefaultlocale())"


This behaviour is caused by a locale_alias entry in [Lib/locale.py](https://github.com/python/cpython/blob/main/Lib/locale.py) .

https://bugs.python.org/issue20076 documents its addition but doesn't
provide a rationale.

I can see that it might be helpful to provide such a conversion if
C.UTF-8 doesn't exist and en_US.UTF-8 does, but the current code is
breaking modern correctly-configured systems for the benefit of old
misconfigured ones (C.UTF-8 shouldn't really be in the environment if it
isn't available on the system, after all).

**Comment by ncoghlan** [comment]
I'm honestly not sure how our Python level locale handling really works (I've mainly worked on the lower level C locale manipulation), so adding folks to the nosy list based on bpo-20076 and bpo-29571.

I agree we shouldn't be aliasing C.UTF-8 to en_US.UTF-8 though - we took en_US.UTF-8 out of the locale coercion fallback list in PEP-538 because it wasn't really right.

**Comment by af4925dc-98b6-440f-9623-c180bdc314be** [comment]
I've investigated a bit more.

First, I've tried with Python 3.7.0a1 . As you'd expect, PEP-537 means
this behaviour now also occurs when no locale environment variables at
all are set.


Second, I've looked through locale.py a bit. I believe what it calls the
"aliasing engine" is applied for:

 - getlocale()
 - getdefaultlocale()
 - setlocale() when passed a tuple, but not when passed a string


This leads to some rather odd results.

With 3.7.0a1 and no locale environment variables:

```pycon
  >>> import locale
  >>> locale.getlocale()
  ('en_US', 'UTF-8')

  # getlocale() is lying: the effective locale is really C.UTF-8
  >>> sorted("abcABC", key=locale.strxfrm)
  ['A', 'B', 'C', 'a', 'b', 'c']
```



Third, I've checked on a system which does have en_US.UTF-8 installed,
and (as you'd expect) instead of crashing it gives wrong results:

```pycon
  >>> import locale
  >>> locale.setlocale(locale.LC_ALL, ('C', 'UTF-8'))
  'en_US.UTF-8'
  >>> locale.getlocale()
  ('en_US', 'UTF-8')

  # now getlocale() is telling the truth, and the user isn't getting the
  # collation they requested
  >>> sorted("abcABC", key=locale.strxfrm)
  ['a', 'A', 'b', 'B', 'c', 'C']
```

**Comment by af4925dc-98b6-440f-9623-c180bdc314be** [comment]
(For PEP-537 please read PEP-538, sorry)
