### ISSUE TITLE
Misleading message “can't concat bytes to str”

### ISSUE THREAD

**Issue by 410541c4-67eb-407f-b4b5-1e85802982d6** [python/cpython#74947]
BPO | [30762](https://bugs.python.org/issue30762)
--- | :---
Nosy | @serhiy-storchaka, @seirl
PRs | <li>python/cpython#2400</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-25.03:21:17.291>
created_at = <Date 2017-06-26.10:13:37.055>
labels = ['interpreter-core']
title = "Misleading message \xe2\x80\x9ccan't concat bytes to str\xe2\x80\x9d"
updated_at = <Date 2017-10-25.03:21:17.290>
user = 'https://github.com/seirl'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-25.03:21:17.290>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-25.03:21:17.291>
closer = 'berker.peksag'
components = ['Interpreter Core']
creation = <Date 2017-06-26.10:13:37.055>
creator = 'antoine.pietri'
dependencies = []
files = []
hgrepos = []
issue_num = 30762
keywords = []
message_count = 2.0
messages = ['296870', '296888']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'antoine.pietri']
pr_nums = ['2400']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30762'
versions = []
```

</p></details>

**Comment by 410541c4-67eb-407f-b4b5-1e85802982d6** [comment]
```pycon
>>> b'a' + 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't concat bytes to str
```



This error message is misleading because it is reversed: what is really happening is that we're concatenating str to bytes! When you say "attach A to B" it means B is there first and A is added to it afterwards.

That said, we can't just reverse the message (“can't concat str to bytes”), because having the message reversed compared to the code would be also misleading.

I therefore propose to use “and” (→ “can't concat bytes and str”), which makes more sense and preserve the order.

**Comment by serhiy-storchaka** [comment]
This already is fixed in bpo-29116.

```pycon
>>> b'a' + 'a'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: can't concat str to bytes
```
