### ISSUE TITLE
configparse module in python3 can not write '%' to config file

### ISSUE THREAD

**Issue by 0508a1ae-5852-4f8a-82fb-0a7a2fb2644d** [python/cpython#74945]
BPO | [30760](https://bugs.python.org/issue30760)
--- | :---
Nosy | @mcepl, @ambv, @3xp10it

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-04-02.17:52:06.083>
created_at = <Date 2017-06-26.09:48:10.568>
labels = ['type-bug', 'invalid']
title = "configparse module in python3 can not write '%' to config file"
updated_at = <Date 2018-04-02.17:52:06.083>
user = 'https://github.com/3xp10it'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-02.17:52:06.083>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2018-04-02.17:52:06.083>
closer = 'lukasz.langa'
components = []
creation = <Date 2017-06-26.09:48:10.568>
creator = 'quanyechavshuo'
dependencies = []
files = []
hgrepos = []
issue_num = 30760
keywords = []
message_count = 3.0
messages = ['296865', '298204', '313245']
nosy_count = 3.0
nosy_names = ['mcepl', 'lukasz.langa', 'quanyechavshuo']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30760'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0508a1ae-5852-4f8a-82fb-0a7a2fb2644d** [comment]
Hello,I was using configparser module in python3.6,but find it works not good when I try to write '%' to my config file,below is my func:

```py
def update_config_file_key_value(file, section, key_name, key_value):
    # 通过configparser模块的调用更新配置文件
    # section是[]里面的值
    if os.path.exists(file) == False:
        os.system("touch %s" % file)
    import configparser
    config = configparser.ConfigParser()
    config.read(file)
    sectionList = config.sections()
    if section not in sectionList:
        config.add_section(section)
    config.set(section, key_name, str(key_value))
    with open(file, 'w') as f:
        config.write(f)
```


When I use it as:
update_config_file_key_value('config.ini','default','cookie',"123")
it works well,but below not ok:
update_config_file_key_value('config.ini','default','cookie',"%123")
and below not ok:
update_config_file_key_value('config.ini','default','cookie',"123%")
and below not ok:
update_config_file_key_value('config.ini','default','cookie',"12%3")

That's to say,configparser can not write '%' to config file.

**Comment by ambv** [comment]
With the default ConfigParser, we're using basic interpolation, as covered by:

https://docs.python.org/3/library/configparser.html#configparser.BasicInterpolation

To not have it, set interpolation to None in the ConfigParser constructor:

```py
    config = configparser.ConfigParser(interpolation=None)
```


Then percent signs will be treated like any other character. Let me know if you have further questions.
