### ISSUE TITLE
[EASY (C)] test_execve_invalid_env() of test_os leaks references

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74954]
BPO | [30769](https://bugs.python.org/issue30769)
--- | :---
Nosy | @vstinner, @ericvw, @serhiy-storchaka, @emilyemorehouse
PRs | <li>python/cpython#2416</li><li>python/cpython#2425</li><li>python/cpython#2447</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-27.16:10:00.412>
created_at = <Date 2017-06-26.16:41:42.439>
labels = ['easy', '3.7', 'tests', 'performance']
title = '[EASY (C)] test_execve_invalid_env() of test_os leaks references'
updated_at = <Date 2017-06-27.16:36:11.616>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-27.16:36:11.616>
actor = 'emilyemorehouse'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-27.16:10:00.412>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-06-26.16:41:42.439>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30769
keywords = ['easy (C)']
message_count = 17.0
messages = ['296915', '296916', '296917', '296918', '296920', '296921', '296922', '296985', '296999', '297000', '297040', '297047', '297051', '297052', '297054', '297056', '297057']
nosy_count = 4.0
nosy_names = ['vstinner', 'ericvw', 'serhiy.storchaka', 'emilyemorehouse']
pr_nums = ['2416', '2425', '2447']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30769'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
haypo@selma$ ./python -m test -R 3:3 -m test_execve_invalid_env test_os
test_os leaked [2, 2, 2] references, sum=6
test_os leaked [2, 2, 2] memory blocks, sum=6

I don't understand if it's related to bpo-30602 or not?

**Comment by vstinner** [comment]
The leak can reproduce only using this test:

```py
    def test_execve_invalid_env(self):
        args = [sys.executable, '-c', 'pass']

        # equal character in the enviroment variable name
        newenv = os.environ.copy()
        newenv["FRUIT=ORANGE"] = "lemon"
        with self.assertRaises(ValueError):
            os.execve(args[0], args, newenv)
```


It seems like the bug is in parse_envlist() function of [Modules/posixmodule.c](https://github.com/python/cpython/blob/main/Modules/posixmodule.c), when a key contains the '=' character.

**Comment by vstinner** [comment]
FYI I found this leak using my bisect_test.py script:
https://mail.python.org/pipermail/python-dev/2017-June/148368.html

Another hint: it seems like the leak was introduced recently ;-) Try "git log [Modules/posixmodule.c](https://github.com/python/cpython/blob/main/Modules/posixmodule.c)".

Reminder: core developers, please don't fix the issue, but \*explain how to fix it* ;-)

**Comment by vstinner** [comment]
Oops, wrong link to my email:
https://mail.python.org/pipermail/python-dev/2017-June/148489.html

I used this command:

 ./python bisect_test.py -R 3:3 test_os

Where the script comes from:
https://github.com/haypo/misc/blob/master/python/bisect_test.py

**Comment by serhiy-storchaka** [comment]
Oh, my bad. Thank you for finding this leak Victor.

**Comment by d399e807-80a0-406d-8006-e79791f279ae** [comment]
I think I may have found it.

```sh
$ git show 77703942c5997dff00c48f10df1b29b11645624c
```


Appears to indicate key2 and val2 are \*not* decremented in the error conditions.  Should I PR a fix for this or let Serhiy resolve?

**Comment by emilyemorehouse** [comment]
I also found what Eric did, specifically lines 4913-4918 in the commit he mentioned introduced the bug:

```c
    if (PyBytes_GET_SIZE(key2) == 0 ||
        strchr(PyBytes_AS_STRING(key2) + 1, '=') != NULL)
    {
        PyErr_SetString(PyExc_ValueError, "illegal environment variable name");
        goto error;
    }
```


One of the tricks is that the test that fails was added after the commit that introduced the bug.

**Comment by vstinner** [comment]
New changeset a7874c73c0c729bbec2fd4b077bd0eec276cfff4 by Victor Stinner (Eric N. Vander Weele) in branch 'master':
bpo-30769: Fix reference leak introduced in 77703942c59 (bpo-2416)
https://github.com/python/cpython/commit/a7874c73c0c729bbec2fd4b077bd0eec276cfff4

**Comment by serhiy-storchaka** [comment]
The code in 3.5 differs from the code in master and 3.6, but it contains the same bug.

**Comment by serhiy-storchaka** [comment]
New changeset 2d348f7a723db839aa18ce8213b8663ccb0a3d35 by Serhiy Storchaka (Emily Morehouse) in branch '3.6':
[3.6] bpo-30769: Fix reference leak introduced in 77703942c59 (GH-2416) (bpo-2425)
https://github.com/python/cpython/commit/2d348f7a723db839aa18ce8213b8663ccb0a3d35

**Comment by emilyemorehouse** [comment]
I think I need a bit more direction for the 3.5 backport. The original test below passes:
    ./python -m test -R 3:3 -m test_execve_invalid_env test_os

**Comment by serhiy-storchaka** [comment]
Just read the code. Find the function parse_envlist() in posixmodule.c and find similar code checking for '='.

Even if the leak is not detected by the test (but it is detected on Linux, maybe you use Windows?) it exists.

os.spawnve() also should be affected by this bug and fixed by the same patch, because it uses the same code.

**Comment by vstinner** [comment]
New changeset eb3c52a0d273491e745e0cbff2b73900bb96aa45 by Victor Stinner (Emily Morehouse) in branch '3.5':
[3.5] bpo-30769: Fix reference leak introduced in 7770394 (GH-2416) (bpo-2447)
https://github.com/python/cpython/commit/eb3c52a0d273491e745e0cbff2b73900bb96aa45

**Comment by vstinner** [comment]
Ooookay, the bug is now fix on all branches. Thanks Eric & Emily for your PR and thanks Serhiy for the help ;-)

**Comment by serhiy-storchaka** [comment]
Many thanks for you Victor for your wonderful tool.

**Comment by emilyemorehouse** [comment]
Resolving this since the fix and backports have been merged in.

**Comment by emilyemorehouse** [comment]
And thank you to Serhiy and Victor for the assistance and attention to this issue!
