### ISSUE TITLE
test_multiprocessing_forkserver leaks references on Python 3

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74958]
BPO | [30775](https://bugs.python.org/issue30775)
--- | :---
Nosy | @pitrou, @vstinner, @applio
PRs | <li>python/cpython#2467</li><li>python/cpython#2468</li><li>python/cpython#2469</li><li>python/cpython#2470</li><li>python/cpython#2471</li><li>python/cpython#2472</li><li>python/cpython#2473</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.09:51:49.847>
created_at = <Date 2017-06-26.20:16:57.190>
labels = ['3.7', 'tests', 'performance']
title = 'test_multiprocessing_forkserver leaks references on Python 3'
updated_at = <Date 2017-09-15.16:04:53.679>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.16:04:53.679>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.09:51:49.847>
closer = 'pitrou'
components = ['Tests']
creation = <Date 2017-06-26.20:16:57.190>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30775
keywords = []
message_count = 14.0
messages = ['296942', '296943', '296944', '296945', '296946', '297164', '297166', '297168', '297169', '297170', '297171', '297172', '297174', '302261']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'davin']
pr_nums = ['2467', '2468', '2469', '2470', '2471', '2472', '2473']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30775'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
```sh
$ ./python -m test --match=test.test_multiprocessing_forkserver.WithProcessesTestBarrier.test_barrier --match=test.test_multiprocessing_forkserver.WithProcessesTestFinalize.test_finalize -R 3:3 test_multiprocessing_forkserver 
```


test_multiprocessing_forkserver leaked [222, 222, 225] memory blocks, sum=669
test_multiprocessing_forkserver failed

Total duration: 5 sec
Tests result: FAILURE

**Comment by vstinner** [comment]
test_multiprocessing_spawn doesn't leak:

haypo@selma$ ./python -m test --match=test.test_multiprocessing_spawn.WithProcessesTestBarrier.test_barrier --match=test.test_multiprocessing_spawn.WithProcessesTestFinalize.test_finalize -R 3:3 test_multiprocessing_spawn
Run tests sequentially
0:00:00 load avg: 0.11 [1/1] test_multiprocessing_spawn
beginning 6 repetitions
123456
......
1 test OK.

Total duration: 10 sec
Tests result: SUCCESS

**Comment by vstinner** [comment]
The first message was on Python 3.6. On master, regrtest sees even more kinds of leaks: references, memory blocks and file descriptors.

haypo@selma$ ./python -m test --match=test.test_multiprocessing_forkserver.WithProcessesTestBarrier.test_barrier --match=test.test_multiprocessing_forkserver.WithProcessesTestFinalize.test_finalize -R 3:3 test_multiprocessing_forkserver 
Run tests sequentially
0:00:00 load avg: 0.25 [1/1] test_multiprocessing_forkserver
beginning 6 repetitions
123456
......
test_multiprocessing_forkserver leaked [492, 492, 492] references, sum=1476
test_multiprocessing_forkserver leaked [221, 222, 225] memory blocks, sum=668
test_multiprocessing_forkserver leaked [4, 4, 4] file descriptors, sum=12
test_multiprocessing_forkserver failed

1 test failed:
    test_multiprocessing_forkserver

Total duration: 5 sec
Tests result: FAILURE

**Comment by pitrou** [comment]
Is it test_finalize or test_barrier?

**Comment by vstinner** [comment]
> Is it test_finalize or test_barrier?

Try yourself: it only leaks when you run both :-)

**Comment by vstinner** [comment]
New changeset a79f8faccf5e26f55e8b9496ad49d2071b5e299c by Victor Stinner (Antoine Pitrou) in branch 'master':
bpo-30775: Fix refleaks in test_multiprocessing (bpo-2467)
https://github.com/python/cpython/commit/a79f8faccf5e26f55e8b9496ad49d2071b5e299c

**Comment by vstinner** [comment]
Hey, thank you Antoine for fixing the last known reference leak!

**Comment by pitrou** [comment]
New changeset e022aad73a4151b5628e2476a8465ce6c0d18b8c by Antoine Pitrou in branch '3.6':
[3.6] bpo-30775: Fix refleaks in test_multiprocessing (GH-2467) (bpo-2468)
https://github.com/python/cpython/commit/e022aad73a4151b5628e2476a8465ce6c0d18b8c

**Comment by vstinner** [comment]
New changeset f15bf1f3f3104f6ab2229e4b359984489a74685b by Victor Stinner (Antoine Pitrou) in branch '3.5':
[3.5] bpo-30775: Fix refleaks in test_multiprocessing (GH-2467) (bpo-2469)
https://github.com/python/cpython/commit/f15bf1f3f3104f6ab2229e4b359984489a74685b

**Comment by vstinner** [comment]
New changeset 79d37ae979a65ada0b2ac820279ccc3b1cd41ba6 by Victor Stinner (Antoine Pitrou) in branch 'master':
Clear potential ref cycle between Process and Process target (bpo-2470)
https://github.com/python/cpython/commit/79d37ae979a65ada0b2ac820279ccc3b1cd41ba6

**Comment by pitrou** [comment]
New changeset 38d6a40898940d2c62c637fcc8acce05e75de5c2 by Antoine Pitrou in branch '3.6':
[3.6] Clear potential ref cycle between Process and Process target (GH-2470) (bpo-2471)
https://github.com/python/cpython/commit/38d6a40898940d2c62c637fcc8acce05e75de5c2

**Comment by pitrou** [comment]
New changeset a9705b777859f555d50eb5dcd5fc4260c42a0188 by Antoine Pitrou in branch '3.5':
[3.5] Clear potential ref cycle between Process and Process target (GH-2470) (bpo-2472)
https://github.com/python/cpython/commit/a9705b777859f555d50eb5dcd5fc4260c42a0188

**Comment by vstinner** [comment]
New changeset 12536bd261ba95cd2748f3d7d47768742a6ffa7a by Victor Stinner (Antoine Pitrou) in branch '2.7':
[2.7] Clear potential ref cycle between Process and Process target (GH-2470) (bpo-2473)
https://github.com/python/cpython/commit/12536bd261ba95cd2748f3d7d47768742a6ffa7a

**Comment by vstinner** [comment]
The Python 2.7 change caused a regression in Sphinx: bpo-31016.
