### ISSUE TITLE
IDLE: configdialog -- add docstrings and improve comments

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#74960]
BPO | [30777](https://bugs.python.org/issue30777)
--- | :---
Nosy | @terryjreedy, @vstinner, @mlouielu, @csabella
PRs | <li>python/cpython#2440</li><li>python/cpython#2576</li><li>python/cpython#2577</li><li>python/cpython#2579</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-05.04:56:34.363>
created_at = <Date 2017-06-26.21:57:01.952>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: configdialog -- add docstrings and improve comments'
updated_at = <Date 2017-07-05.20:21:52.677>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-05.20:21:52.677>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-05.04:56:34.363>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-06-26.21:57:01.952>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 30777
keywords = []
message_count = 6.0
messages = ['296955', '297030', '297059', '297693', '297699', '297778']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'vstinner', 'louielu', 'cheryl.sabella']
pr_nums = ['2440', '2576', '2577', '2579']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30777'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
Spinoff from bpo-30728.  Docstrings are a form of comment.  Both leave behavior alone and do not require testing, just human review.  Add the docstrings from the original version of [PR 2307](https://github.com/python/cpython/pull/2307), and any others.  Review and fix comments in light of the comments on that PR.

**Comment by csabella** [comment]
I've made a PR for the docstrings and comments.  I didn't change any of the comments separating the sections in the create* functions as I wasn't sure how you wanted those changed.  When reading the code, I found the comments helpful in that they separated each section, but whitespace might be just as helpful, visually.

Thanks!

**Comment by terryjreedy** [comment]
Louie, perhaps you would like to review the PR, especially the comment revisions responding to your comments.

**Comment by terryjreedy** [comment]
New changeset 7eb5883ac59833bf63f0e1f7fb95671a1ac1ee08 by terryjreedy (csabella) in branch 'master':
bpo-30777: IDLE: configdialog - add docstrings and improve comments (bpo-2440)
https://github.com/python/cpython/commit/7eb5883ac59833bf63f0e1f7fb95671a1ac1ee08

**Comment by terryjreedy** [comment]
New changeset e5bb112ba2048cb3ea19481a7b38fe1433c5a7ef by terryjreedy in branch '3.6':
[3.6] bpo-30777: IDLE: configdialog - add docstrings and improve comments (GH-2440) (bpo-2577)
https://github.com/python/cpython/commit/e5bb112ba2048cb3ea19481a7b38fe1433c5a7ef

**Comment by terryjreedy** [comment]
Unlinked bogus revert message.  configdialog still has new docstrings.
