### ISSUE TITLE
ast.c duplicates STR(CHILD)

### ISSUE THREAD

**Issue by e9b54dbb-a02d-420d-8236-6dcde5afc0aa** [python/cpython#74968]
BPO | [30785](https://bugs.python.org/issue30785)
--- | :---
Nosy | @emilyemorehouse

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-28.17:34:28.109>
created_at = <Date 2017-06-27.08:01:37.027>
labels = ['interpreter-core', 'invalid', 'type-feature', '3.7']
title = 'ast.c duplicates STR(CHILD)'
updated_at = <Date 2017-06-28.17:34:28.107>
user = 'https://bugs.python.org/ChristopherAycock'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-28.17:34:28.107>
actor = 'emilyemorehouse'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-28.17:34:28.109>
closer = 'emilyemorehouse'
components = ['Interpreter Core']
creation = <Date 2017-06-27.08:01:37.027>
creator = 'Christopher Aycock'
dependencies = []
files = []
hgrepos = []
issue_num = 30785
keywords = []
message_count = 2.0
messages = ['297018', '297202']
nosy_count = 2.0
nosy_names = ['emilyemorehouse', 'Christopher Aycock']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30785'
versions = ['Python 3.7']
```

</p></details>

**Comment by e9b54dbb-a02d-420d-8236-6dcde5afc0aa** [comment]
The function alias_for_import_name() duplicates logic starting at [Python/ast.c:3237](https://github.com/python/cpython/blob/main/Python/ast.c#L3237)

```c
    char *sch = STR(CHILD(n, i));
    strcpy(s, STR(CHILD(n, i)));
    s += strlen(sch);
    *s++ = '.';
```


I assume the strcpy() is supposed to use the sch value from the line above. There shouldn't be any consequence to the code as it currently is; I just noticed it while reading through the source.

**Comment by emilyemorehouse** [comment]
Thanks Christopher, you are absolutely correct. There are a few ways in which this code could be optimized (and many other small optimizations probably exist elsewhere in the code).

If you are interested in submitting a PR for this, you are more than welcome to and I can re-open the issue. Otherwise, I'm going to close it out as this is not a critical optimization.
