### ISSUE TITLE
Can't use proxy to connect internet on windows

### ISSUE THREAD

**Issue by 6fb35c75-4711-42dd-a140-91ec7dcf81b7** [python/cpython#74973]
BPO | [30790](https://bugs.python.org/issue30790)
--- | :---
Nosy | @csabella, @Cordius
PRs | <li>python/cpython#2445</li><li>python/cpython#2474</li><li>python/cpython#2535</li><li>python/cpython#2554</li><li>python/cpython#2611</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-06-28.09:21:41.536>
labels = ['3.8', 'type-bug', 'library']
title = "Can't use proxy to connect internet on windows"
updated_at = <Date 2019-05-22.01:04:48.433>
user = 'https://github.com/Cordius'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-22.01:04:48.433>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-06-28.09:21:41.536>
creator = 'Cordius'
dependencies = []
files = []
hgrepos = []
issue_num = 30790
keywords = []
message_count = 1.0
messages = ['343137']
nosy_count = 2.0
nosy_names = ['cheryl.sabella', 'Cordius']
pr_nums = ['2445', '2474', '2535', '2554', '2611']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30790'
versions = ['Python 3.8']
```

</p></details>

**Comment by encukou** [comment]
There was no response after several years of pings on the pull request. I'll close the issue.

@Cordius, if you still want this change to go in, please open a new issue with the requested information.
