### ISSUE TITLE
Add multiprocessing.Process.kill()

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74977]
BPO | [30794](https://bugs.python.org/issue30794)
--- | :---
Nosy | @pitrou, @applio, @vmsp
PRs | <li>python/cpython#2528</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-18.15:34:58.644>
created_at = <Date 2017-06-28.20:03:41.527>
labels = ['3.7', 'type-feature', 'library']
title = 'Add multiprocessing.Process.kill()'
updated_at = <Date 2017-07-18.15:35:11.987>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-18.15:35:11.987>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-18.15:34:58.644>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-06-28.20:03:41.527>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 30794
keywords = []
message_count = 4.0
messages = ['297216', '297681', '297685', '298600']
nosy_count = 3.0
nosy_names = ['pitrou', 'davin', 'vmsp']
pr_nums = ['2528']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30794'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
subprocess.Popen() has both terminate() and kill() methods.  Under Unix, the first sends SIGTERM and the second SIGKILL.

multiprocessing.Process() only has terminate(), which sends SIGTERM.  It may be useful to add a kill() method to send SIGKILL (on Windows, kill() would be the same as terminate()).

One possible use case is when the child process has redefined the SIGTERM handler to something that doesn't trigger an exit (or takes a long time to exit).  Or if something non-interruptible is running...

**Comment by a112f6b9-61d0-4bf0-8679-04d3662796fc** [comment]
Hey, I submitted a PR and just signed the CLA. If you could please take a look. Thanks!

**Comment by pitrou** [comment]
Thank you Vitor! I posted some review comments on your PR.

**Comment by pitrou** [comment]
New changeset ba75af713078966cc594fc7f0809ed53c532c58f by Antoine Pitrou (Vitor Pereira) in branch 'master':
bpo-30794: added kill() method to multiprocessing.Process (bpo-2528)
https://github.com/python/cpython/commit/ba75af713078966cc594fc7f0809ed53c532c58f
