### ISSUE TITLE
tkinter.Tk() adds suffix to window class name when launching multiple instances

### ISSUE THREAD

**Issue by 0b49082b-e6a8-432f-b942-f90d37c76a25** [python/cpython#74974]
BPO | [30791](https://bugs.python.org/issue30791)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka, @hakonhagland

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-01.05:29:36.712>
created_at = <Date 2017-06-28.15:18:17.986>
labels = ['type-bug', 'expert-tkinter']
title = 'tkinter.Tk() adds suffix to window class name when launching multiple instances'
updated_at = <Date 2017-07-01.05:29:36.710>
user = 'https://github.com/hakonhagland'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-01.05:29:36.710>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-01.05:29:36.712>
closer = 'serhiy.storchaka'
components = ['Tkinter']
creation = <Date 2017-06-28.15:18:17.986>
creator = 'hakonhagland'
dependencies = []
files = []
hgrepos = []
issue_num = 30791
keywords = []
message_count = 3.0
messages = ['297191', '297445', '297473']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'serhiy.storchaka', 'hakonhagland']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30791'
versions = []
```

</p></details>

**Comment by 0b49082b-e6a8-432f-b942-f90d37c76a25** [comment]
Hello. In order to group several instances of a given application under one icon in the desktop launcher (I am using Ubuntu 17.04) they must have the same appName property of the WM_CLASS string. For example, if I run emacs twice:

￼$ emacs &
$ emacs &

Both instances will show up under the Emacs icon in the desktop launchbar. The reason is that both instances have the same WM_CLASS string. We can check this string using

￼$ xprop WM_CLASS

and then click on the Emacs window. It then shows:

￼WM_CLASS(STRING) = "emacs", "Emacs"
Here "emacs" is the resource (appName), and "Emacs" is the className.

Now, consider this program (my-tkapp.py):

```py
#! /usr/bin/env python
import tkinter as tk
root = tk.Tk(className='myTkApp')
label = tk.Label(root, text="Hello World")
label.pack()
root.mainloop()
```



If I run this program twice:

￼$ my-tkapp.py &
$ my-tkapp.py &

and then run xprop to check the WM_CLASS property of both windows, the first window gives:

￼WM_CLASS(STRING) = "myTkApp", "Mytkapp"

whereas the second gives:

￼WM_CLASS(STRING) = "myTkApp #2", "Mytkapp"

Note that tkinter has added a #2 suffix to the app name property. This is not desired. It makes the window manager group the two windows under separate icons in the desktop launch bar.

How can I keep the same appName property of the WM_CLASS string for different instances of my application?

Note: This question was first asked at stackoverflow.com:

https://stackoverflow.com/q/44795622/2173773

I tried to follow the source from the call:

```py
root = tkinter.Tk(className='myTkApp')
```


but at 5 levels down on the stack I ended up inside TCL code, and I was not able to determine who was responsible for adding the "#2" suffix.

However, a similar perl script gives the same behavior, so I suspect the problem is within the TCL TK code. Is there a way to change the
WM_CLASS property of the window after the call to tkinter.Tk, but before entering mainloop() in order to work around the issue?
After entering the mainloop(), I guess it is too late to do anything, since then the icon is already displayed in the window manager's launch bar.

I am using Ubuntu 17.04 and Python version 3.6.1.

Best regards,
Håkon Hægland

**Comment by terryjreedy** [comment]
> tkinter has added a #2
I think you yourself proved otherwise. Additional evidence is that ' #2' is not added on Windows.  I have 3 windows titled 'myApp' stacked behind my installed python/IDLE icon. root.winfo_class() returns the class name capitalized, but the window title is not.  root.winfo_class('newname') does not work.  Note: I added more chars to the label to make it big enough to force the window to be big enough to display the title.

There might be a reason why tcl deduplicates class names on \*nix.  So even if you found a way to set a classname after the Tk call, tcl might still deduplicate it.  Or we might decide not to force change the current behavior.

I suspect that this will be closed as a 3rd-party issue.

**Comment by serhiy-storchaka** [comment]
I concur with Terry. This is not a Tkinter issue, this is a Tk issue.

Ask help on Tcl/Tk resources. If this is considered a bug open a ticket on the Tk tracker: https://core.tcl.tk/tk/tktnew .
