### ISSUE TITLE
OS X failures in test_site

### ISSUE THREAD

**Issue by pitrou** [python/cpython#74978]
BPO | [30795](https://bugs.python.org/issue30795)
--- | :---
Nosy | @ronaldoussoren, @pitrou, @vstinner, @ned-deily
Superseder | <li>bpo-29585: site.py imports relatively large `sysconfig` module.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-30.22:03:23.037>
created_at = <Date 2017-06-28.20:05:38.720>
labels = ['OS-mac', 'type-bug', '3.7']
title = 'OS X failures in test_site'
updated_at = <Date 2017-06-30.22:03:23.036>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-30.22:03:23.036>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-30.22:03:23.037>
closer = 'ned.deily'
components = ['macOS']
creation = <Date 2017-06-28.20:05:38.720>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 30795
keywords = []
message_count = 2.0
messages = ['297217', '297223']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'pitrou', 'vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29585'
type = 'behavior'
url = 'https://bugs.python.org/issue30795'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
It seems there is a sporadic failure on OS X (oops, sorry, I mean "macOS"):

https://travis-ci.org/python/cpython/jobs/248079407#L3403

\======================================================================

FAIL: test_getsitepackages (test.test_site.HelperFunctionsTests)

\----------------------------------------------------------------------

```pytb
Traceback (most recent call last):
```


  File "/Users/travis/build/python/cpython/Lib/test/test_site.py", line 266, in test_getsitepackages

    self.assertEqual(len(dirs), 2)

AssertionError: 1 != 2

\----------------------------------------------------------------------

**Comment by vstinner** [comment]
Yeah, it's a known issue, see:
http://bugs.python.org/issue29585#msg297194
