### ISSUE TITLE
Redesign PyCodeObject.co_extras to use a single memory block, instead of two

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74972]
BPO | [30789](https://bugs.python.org/issue30789)
--- | :---
Nosy | @vstinner, @DinoV, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#2555</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-04.12:18:48.237>
created_at = <Date 2017-06-28.00:10:41.038>
labels = ['interpreter-core', '3.7', 'performance']
title = 'Redesign PyCodeObject.co_extras to use a single memory block, instead of two'
updated_at = <Date 2017-07-05.15:59:12.046>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-05.15:59:12.046>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-04.12:18:48.237>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-06-28.00:10:41.038>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30789
keywords = []
message_count = 7.0
messages = ['297077', '297624', '297648', '297745', '297764', '297769', '297770']
nosy_count = 4.0
nosy_names = ['vstinner', 'dino.viehland', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['2555']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30789'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Currently, \_PyCode_SetExtra() uses two memory block for code extras. Using a different structure, it would be possible to use a single memory block: less memory fragmentation, better CPU cache usage, less indirections, etc.

It matters since the long term plan for co_extras is to implement of kind-of JIT compiler insider CPython: see bpo-28158.

**Comment by serhiy-storchaka** [comment]
Since nobody has provided a patch I have made it myself.

**Comment by vstinner** [comment]
New changeset 378ebb6578b9d709f38b888d23874c0b18125249 by Victor Stinner (Serhiy Storchaka) in branch 'master':
bpo-30789: Use a single memory block for co_extra. (bpo-2555)
https://github.com/python/cpython/commit/378ebb6578b9d709f38b888d23874c0b18125249

**Comment by vstinner** [comment]
New changeset 8207c17486baece8ed0ac42d9f8d69ecec4ba7e4 by Victor Stinner in branch 'master':
Revert "bpo-30822: Fix testing of datetime module." (bpo-2588)
https://github.com/python/cpython/commit/8207c17486baece8ed0ac42d9f8d69ecec4ba7e4

**Comment by serhiy-storchaka** [comment]
How is this related to datetime module? I hope you didn't reverted too much?

**Comment by vstinner** [comment]
> How is this related to datetime module? I hope you didn't reverted too much?

I'm sorry for the spam. It was the first time that I really used the
[Revert] button: even if the revert change is correct, the \*commit
message* is completely wrong :-/
https://mail.python.org/pipermail/python-committers/2017-July/004674.html

**Comment by vstinner** [comment]
I'm sorry for the spam. It was the first time that I really used the
[Revert] button: even if the revert change is correct, the \*commit
message* is completely wrong :-/
https://mail.python.org/pipermail/python-committers/2017-July/004674.html
