### ISSUE TITLE
netrc.__repr__() is broken for writing to file

### ISSUE THREAD

**Issue by c51ddbe9-c399-41be-8e96-0f4656621af2** [python/cpython#74989]
BPO | [30806](https://bugs.python.org/issue30806)
--- | :---
Nosy | @methane, @Bezier89
PRs | <li>python/cpython#2491</li><li>python/cpython#4244</li><li>python/cpython#4276</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-03.05:37:32.768>
created_at = <Date 2017-06-29.19:12:21.752>
labels = ['3.7', 'type-bug', 'library']
title = 'netrc.__repr__() is broken for writing to file'
updated_at = <Date 2017-12-10.06:10:05.430>
user = 'https://github.com/Bezier89'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-10.06:10:05.430>
actor = 'methane'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-03.05:37:32.768>
closer = 'methane'
components = ['Library (Lib)']
creation = <Date 2017-06-29.19:12:21.752>
creator = 'Bezier89'
dependencies = []
files = []
hgrepos = []
issue_num = 30806
keywords = ['patch']
message_count = 4.0
messages = ['297296', '303398', '305461', '307943']
nosy_count = 2.0
nosy_names = ['methane', 'Bezier89']
pr_nums = ['2491', '4244', '4276']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30806'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c51ddbe9-c399-41be-8e96-0f4656621af2** [comment]
Have any valid .netrc file. For testing purposes you can use this:

machine abc.xyz login myusername password mypassword

The documentation for netrc.\_\_repr__() states that it "dumps the class data as a string in the format of a netrc file". However, when you try to actually do this, you'll encounter a nasty bug. This can be seen by running the follow commands:

```py
auth = netrc.netrc(os.path.expanduser(r"~\.netrc"))
print(auth.__repr__())
```


The expected output is:

machine abc.xyz
        login myusername
        password mypassword

The actual output is:

machine abc.xyz
        login 'myusername'
        password 'mypassword'

If you write this back out to the .netrc file, authentication will fail since incorrect username/password (with ' character at beginning at end) will be passed.

**Comment by methane** [comment]
New changeset b24cd055ecb3eea9a15405a6ca72dafc739e6531 by INADA Naoki (James Sexton) in branch 'master':
bpo-30806 netrc.\_\_repr__() is broken for writing to file (GH-2491)
https://github.com/python/cpython/commit/b24cd055ecb3eea9a15405a6ca72dafc739e6531

**Comment by methane** [comment]
New changeset 5fbe5e161c969bc8a0d44a301152f8bf5afe0fc7 by INADA Naoki (Miss Islington (bot)) in branch '3.6':
bpo-30806: Fix netrc.\_\_repr__() format (GH-2491)
https://github.com/python/cpython/commit/5fbe5e161c969bc8a0d44a301152f8bf5afe0fc7
