### ISSUE TITLE
bolen-dmg-3.x build-installer.py failed

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74987]
BPO | [30804](https://bugs.python.org/issue30804)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @methane
PRs | <li>python/cpython#2516</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-03.13:20:40.883>
created_at = <Date 2017-06-29.15:30:53.904>
labels = ['OS-mac', '3.7']
title = 'bolen-dmg-3.x build-installer.py failed'
updated_at = <Date 2017-07-03.13:20:40.846>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.13:20:40.846>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-03.13:20:40.883>
closer = 'vstinner'
components = ['macOS']
creation = <Date 2017-06-29.15:30:53.904>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30804
keywords = []
message_count = 4.0
messages = ['297277', '297428', '297436', '297437']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'methane']
pr_nums = ['2516']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30804'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
It may be related to bpo-29585, see commits:

- a8f8d5b4bd30dbe0828550469d98f12d2ebb2ef4
- b01c574ad6d796025152b5d605eceb7816e6f7a7
- 6b42eb17649bed9615b6e6cecaefdb2f46990b2c

http://buildbot.python.org/all/builders/bolen-dmg-3.x/builds/209/steps/compile/logs/stdio

...
gcc-4.0 -arch ppc -arch i386 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -g -L/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/dmg/libraries/usr/local/lib  -Wl,-stack_size,1000000  -framework CoreFoundation Python.framework/Versions/3.7/Python -o python.exe [Programs/python.o](https://github.com/python/cpython/blob/main/Programs/python.o)  -ldl  -framework CoreFoundation     
DYLD_FRAMEWORK_PATH=/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/dmg/_bld/python ./python.exe -E -S -m sysconfig --generate-posix-vars ;\\
if test $? -ne 0 ; then \\
	echo "generate-posix-vars failed" ; \\
	rm -f ./pybuilddir.txt ; \\
	exit 1 ; \\
fi
gcc-4.0 -c  -fno-strict-aliasing -Wsign-compare -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -arch ppc -arch i386 -isysroot /Developer/SDKs/MacOSX10.4u.sdk -g -I/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/dmg/libraries/usr/local/include   -std=c99 -Wextra -Wno-unused-parameter -Wno-missing-field-initializers  -IObjects -IInclude -IPython -I. -I/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Include -isysroot /Developer/SDKs/MacOSX10.4u.sdk    -DPy_BUILD_CORE -o [Modules/_math.o](https://github.com/python/cpython/blob/main/Modules/_math.o) /Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Modules/_math.c
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1643, in \<module\>
    main()
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1596, in main
    buildPython()
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 1146, in buildPython
    runCommand("make")
  File "/Users/db3l/buildarea.dmg/bolen-dmg-3.x/build/Mac/BuildScript/build-installer.py", line 531, in runCommand
    raise RuntimeError("command failed: %s"%(commandline,))
RuntimeError: command failed: make
program finished with exit code 1
elapsedTime=1419.113943

**Comment by methane** [comment]
Sorry, It seems I failed to merge local patch.

**Comment by vstinner** [comment]
New changeset 5e742fa922ea70131b4c63451c87cf0347532806 by Victor Stinner (INADA Naoki) in branch 'master':
bpo-30804: fix macOS build with framework enabled. (bpo-2516)
https://github.com/python/cpython/commit/5e742fa922ea70131b4c63451c87cf0347532806

**Comment by vstinner** [comment]
Naoki: "How about adding --enable-framework on mac environment of Traivs?"

I like the idea. Can you please propose a PR?
