### ISSUE TITLE
test_unittest fails when hunting reference leaks

### ISSUE THREAD

**Issue by vstinner** [python/cpython#74996]
BPO | [30813](https://bugs.python.org/issue30813)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#2502</li><li>python/cpython#2505</li><li>python/cpython#2506</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-30.11:23:29.315>
created_at = <Date 2017-06-30.09:50:28.320>
labels = ['3.7']
title = 'test_unittest fails when hunting reference leaks'
updated_at = <Date 2017-07-11.07:03:41.837>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.07:03:41.837>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-30.11:23:29.315>
closer = 'vstinner'
components = []
creation = <Date 2017-06-30.09:50:28.320>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30813
keywords = []
message_count = 6.0
messages = ['297370', '297371', '297376', '297386', '297390', '298134']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['2502', '2505', '2506']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30813'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Example of Python 3.5 (same error on master):

haypo@selma$ ./python -m test -R 3:3 -v test_unittest 
(...)
\======================================================================
ERROR: test_discover_with_init_module_that_raises_SkipTest_on_import (unittest.test.test_discovery.TestDiscovery)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/3.5/Lib/unittest/test/test_discovery.py", line 572, in test_discover_with_init_module_that_raises_SkipTest_on_import
    pickle.loads(pickle.dumps(suite, proto))
_pickle.PicklingError: Can't pickle <class 'unittest.loader.ModuleSkipped'>: attribute lookup ModuleSkipped on unittest.loader failed
```


======================================================================
ERROR: test_discover_with_module_that_raises_SkipTest_on_import (unittest.test.test_discovery.TestDiscovery)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/haypo/prog/python/3.5/Lib/unittest/test/test_discovery.py", line 548, in test_discover_with_module_that_raises_SkipTest_on_import
    pickle.loads(pickle.dumps(suite, proto))
_pickle.PicklingError: Can't pickle <class 'unittest.loader.ModuleSkipped'>: attribute lookup ModuleSkipped on unittest.loader failed
```

**Comment by vstinner** [comment]
Using --huntrleaks in regrtest runs this statement in regrtest:

```py
   unittest.BaseTestSuite._cleanup = False
```


This line comes from bpo-11798.

https://github.com/python/cpython/pull/2502 fixes this issue.

**Comment by vstinner** [comment]
New changeset e4f9a2d2be42d5a2cdd624f8ed7cdf5028c5fbc3 by Victor Stinner in branch 'master':
bpo-30813: Fix unittest when hunting refleaks (bpo-2502)
https://github.com/python/cpython/commit/e4f9a2d2be42d5a2cdd624f8ed7cdf5028c5fbc3

**Comment by vstinner** [comment]
New changeset 714afccf6e7644d21ce1a39e90bf83cb0c9a74f1 by Victor Stinner in branch '3.5':
bpo-30813: Fix unittest when hunting refleaks (bpo-2502) (bpo-2506)
https://github.com/python/cpython/commit/714afccf6e7644d21ce1a39e90bf83cb0c9a74f1

**Comment by vstinner** [comment]
New changeset 22d4e8fb99b16657eabfe7f9fee2d40a5ef882f6 by Victor Stinner in branch '3.6':
bpo-30813: Fix unittest when hunting refleaks (bpo-2502) (bpo-2505)
https://github.com/python/cpython/commit/22d4e8fb99b16657eabfe7f9fee2d40a5ef882f6

**Comment by serhiy-storchaka** [comment]
Ah, this fixed bpo-25746!
