### ISSUE TITLE
IDLE parenmatch - highlighting options

### ISSUE THREAD

**Issue by b70526e6-c864-42a1-aa80-a1de956f683b** [python/cpython#74992]
BPO | [30809](https://bugs.python.org/issue30809)
--- | :---
Nosy | @terryjreedy, @taleinat, @wohlganger
PRs | <li>python/cpython#3574</li>
Dependencies | <li>bpo-27099: IDLE: turn built-in extensions into regular modules</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2019-06-06.19:33:38.414>
created_at = <Date 2017-06-29.20:36:07.899>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE parenmatch - highlighting options'
updated_at = <Date 2019-06-06.19:33:38.413>
user = 'https://github.com/wohlganger'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-06.19:33:38.413>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2019-06-06.19:33:38.414>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-06-29.20:36:07.899>
creator = 'wohlganger'
dependencies = ['27099']
files = []
hgrepos = []
issue_num = 30809
keywords = ['patch']
message_count = 11.0
messages = ['297317', '297340', '297404', '297442', '297443', '297446', '297452', '297905', '300827', '344848', '344859']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'taleinat', 'wohlganger']
pr_nums = ['3574']
priority = 'low'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30809'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b70526e6-c864-42a1-aa80-a1de956f683b** [comment]
Current IDLE parenmatch highlighting uses the 'hilite' style when highlighting the parens/expression.

Desired behavior is to use a user-setting based style that is independent from the hilite style (which is used for highlighting selected text). Desired selectable options are for foreground color, background color, underlining and font (which covers font type, size, bold, and italics)

Apart from running IDLE and checking that the selections match, I don't know how to test. Testing would need a human to check for correct colors, etc. if it was made, so it couldn't be automated...

**Comment by terryjreedy** [comment]
I am not willing to add a new theme element to the 13 that already exist, let alone define it in config-extensions.def rather than in config-hightlight.def.  It is too much additional complication for too little impact.  Also, any theme specified in config-extensions would likely not work if the user switches between dark and light text.  Theme sets work together.

I will consider letting users select which of the existing 13 to use.  This requires that users be able to know what the 13 choices are.  Hence  the dependence on bpo-22705.

I might also look at the visual effect of underlining.

**Comment by b70526e6-c864-42a1-aa80-a1de956f683b** [comment]
The pull request has been changed to only have the theme element able to be selected. bpo-22705 hasn't had activity in a few years. Is there something I can do to move it along?

**Comment by terryjreedy** [comment]
As far as you want to go with
1. Review the uploaded patch here or on Rietveld (see review link).
   Or skip this if you make PR and review on github.
2. Download code, makes minimal changes needed to succeed with 'git apply download' in new branch.
3. git commit -m "Patch by Saimadhav Heblikar updated to 3.7"
4. (Optional) test, make changes needed to pass, commit.
5. Make PR and comment or review on github.

**Comment by terryjreedy** [comment]
There is another option.  I want to incorporate 'builtin extensions' as regular features (bpo-27099), and move their configuration options to other tabs, which will need some reworking.  bpo-22705 will then be less urgent. Selection from a finite set will then be from a dropdown box, like similar non-extension options. Thus bpo-27099, which waiting on current work in process on ConfigDialog, is an alternate dependency.

**Comment by b70526e6-c864-42a1-aa80-a1de956f683b** [comment]
Implimenting bpo-27099 seems the more reasonable solution to me, so I'll work on that when I have free time.

**Comment by terryjreedy** [comment]
Since configdialog code is being re-written, I would not want to write code right now.  But we could start planning.

**Comment by b70526e6-c864-42a1-aa80-a1de956f683b** [comment]
I've rolled pretty much all this was going to do, other than underlining and font work into bpo-27099. Trying to bring parenmatch into main otherwise would have been just as much of a hassle.

**Comment by terryjreedy** [comment]
As I said on bpo-27099, please do not include new options with the transfer patch.
