### ISSUE TITLE
Germany made the upper case ß official. 'ß'.upper() should now return ẞ.

### ISSUE THREAD

**Issue by b9812c09-ac37-4608-9c1f-858156940076** [python/cpython#74993]
BPO | [30810](https://bugs.python.org/issue30810)
--- | :---
Nosy | @malemburg, @vstinner, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-30.11:37:36.677>
created_at = <Date 2017-06-30.07:58:55.638>
labels = ['type-feature', '3.7']
title = "Germany made the upper case \xc3\x9f official. '\xc3\x9f'.upper() should now return \xe1\xba\x9e."
updated_at = <Date 2017-06-30.11:37:36.675>
user = 'https://bugs.python.org/TarekSaier'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-30.11:37:36.675>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-30.11:37:36.677>
closer = 'vstinner'
components = []
creation = <Date 2017-06-30.07:58:55.638>
creator = 'Tarek Saier'
dependencies = []
files = []
hgrepos = []
issue_num = 30810
keywords = []
message_count = 4.0
messages = ['297351', '297358', '297392', '297393']
nosy_count = 4.0
nosy_names = ['lemburg', 'vstinner', 'steven.daprano', 'Tarek Saier']
pr_nums = []
priority = 'low'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30810'
versions = ['Python 3.7']
```

</p></details>

**Comment by b9812c09-ac37-4608-9c1f-858156940076** [comment]
I'm not sure if Python just relies on some other resource for this (i.e. a C function), but as of yesterday the correct upper case of ß is ẞ:

Official announcement in German:
http://www.rechtschreibrat.com/DOX/rfdr_PM_2017-06-29_Aktualisierung_Regelwerk.pdf

**Comment by b9812c09-ac37-4608-9c1f-858156940076** [comment]
Small addition after I posted in excitement and now actually read the announcement: German now allows ẞ \*as well as* SS when turning ß into upper case.

**Comment by stevendaprano** [comment]
Although I'm not German, I'm rather pleased by this. Nevertheless I don't think we actually need to do anything yet.

I think it is more important that Python follows the standard Unicode behaviour. If and when Unicode recommend that 'ß'.upper() returns '\\N{LATIN CAPITAL LETTER SHARP S}' then we should follow, until then we should treat it as no different from any other locale-specific difference. For example, 'i'.upper() returns 'I' instead of 'İ' as you would expect if you are Turkish.

**Comment by vstinner** [comment]
Python doesn't make politic :-) Python implements Unicode standard. Python 3.7 currently uses Unicode 10.0:

```pycon
haypo@selma$ ./python
Python 3.7.0a0 (heads/master:b903067, Jun 30 2017, 11:49:25) 
>>> unicodedata.unidata_version
'10.0.0'
```


It seems like Unicode 10 still uses "SS":

```pycon
>>> 'ß'.upper()
'SS'
```


The German government has to change the Unicode standard :-) Please report this "bug" to the Unicode standard :-) So I closes this issue as "third party.
