### ISSUE TITLE
StringIO uses inefficient PyUnicode_AsUCS4

### ISSUE THREAD

**Issue by methane** [python/cpython#74998]
BPO | [30815](https://bugs.python.org/issue30815)
--- | :---
Nosy | @pitrou, @vstinner, @methane, @bhavishyagopesh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-06-30.12:55:32.642>
created_at = <Date 2017-06-30.12:26:04.006>
labels = ['3.7', 'invalid', 'expert-IO', 'performance']
title = 'StringIO uses inefficient PyUnicode_AsUCS4'
updated_at = <Date 2017-06-30.13:39:18.899>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2017-06-30.13:39:18.899>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-06-30.12:55:32.642>
closer = 'methane'
components = ['IO']
creation = <Date 2017-06-30.12:26:04.006>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 30815
keywords = []
message_count = 9.0
messages = ['297394', '297395', '297396', '297397', '297398', '297399', '297400', '297401', '297402']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'methane', 'bhavishya']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30815'
versions = ['Python 3.7']
```

</p></details>

**Comment by methane** [comment]
From PEP-393, PyUnicode_AsUCS4 is inefficient.
And C implementation of io.StringIO() uses it.

That's why Python 3 is slower than Python 2 on logging_format and logging_simple benchmarks.
https://mail.python.org/pipermail/speed/2017-February/000503.html

Maybe, it can use \_PyUnicodeWriter APIs instead.

**Comment by vstinner** [comment]
There was a discussion to use an adaptative implementation depending \*how* the API is used. Write only is different than write, seek back, write, read, seek, etc.

The idea was used unicode writer when it's the most efficient, write only, and switch to something else (ex: current code) when other methods are used.

See bpo-15612.

**Comment by vstinner** [comment]
I rewrote my old benchmarks using the new perf module API: bench_stringio3.py. This benchmark suite now takes forever with perf, since perf computes much more values and the suite contains a total of 108 benchmarks! Most lines should be commented to take a reasonable time :-)

**Comment by vstinner** [comment]
According to my result computed 5 times ago, the most signicant different was on \*reading* from StringIO which contains USC1 text:

reader long lines ascii               |  103 us (*) | 33.4 us (-68%)
reader long lines latin1              |  105 us (*) | 34.2 us (-67%)

**Comment by methane** [comment]
I'm sorry, it's my mistake.

I used vmprof on mac and I thought as_ucs4 is bottleneck.
But vmprof on Linux (and perf) shows totally different result.

Maybe, current vmprof doesn't work well for native code on macOS.

**Comment by vstinner** [comment]
> I rewrote my old benchmarks using the new perf module API: bench_stringio3.py.

WTF? The file is not attached to this issue, but I removed it locally :-(

It seems like Roundup cleared the file field of this form when I got a conflict when I wanted to post my message...

**Comment by methane** [comment]
FYI, https://github.com/python/performance/pull/27 will fix performance regression.
Python 3 performance is similar to Python 2 after s/warn/warning/

**Comment by 0b0359bc-ff2a-49c4-9dcf-7be0c23e8afc** [comment]
I'm running archlinux(on mac...not very confident of my system though I
tried cpu isolation with "isolcpus") so if please anyone else also can run
it....and confirm if it actually helps. Thanks.

**Comment by vstinner** [comment]
"FYI, https://github.com/python/performance/pull/27 will fix performance regression. Python 3 performance is similar to Python 2 after s/warn/warning/"

I was surprised to see that Logger.warn() is slower than Logger.warning()! It is because warn() emits a deprecation warning, thing which isn't cheap...
