### ISSUE TITLE
Add mimetype for extension .json

### ISSUE THREAD

**Issue by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [python/cpython#75007]
BPO | [30824](https://bugs.python.org/issue30824)
--- | :---
Nosy | @bitdancer, @PierreQuentel, @berkerpeksag, @sijis
PRs | <li>python/cpython#3048</li><li>python/cpython#3394</li><li>python/cpython#3401</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-01.05:18:09.973>
created_at = <Date 2017-07-01.19:31:36.476>
labels = ['3.7', 'type-feature', 'library']
title = 'Add mimetype for extension .json'
updated_at = <Date 2017-11-01.05:18:09.971>
user = 'https://github.com/PierreQuentel'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-01.05:18:09.971>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-01.05:18:09.973>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-07-01.19:31:36.476>
creator = 'quentel'
dependencies = []
files = []
hgrepos = []
issue_num = 30824
keywords = []
message_count = 6.0
messages = ['297494', '297527', '300260', '301531', '301546', '305358']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'quentel', 'berker.peksag', 'sijis']
pr_nums = ['3048', '3394', '3401']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30824'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 006d7b03-f9f3-44da-bb8d-8d7a3e15fee9** [comment]
I propose to add a mapping of file extension .json to mime type "application/json".
This is registered in https://www.iana.org/assignments/media-types

**Comment by bitdancer** [comment]
Per our current policy with respect to mime types, this should be added to all currently maintained versions.

**Comment by bitdancer** [comment]
New changeset 8204b903683f9e0f037ccfaa87622716019914d7 by R. David Murray (Nate Tangsurat) in branch 'master':
bpo-30824: Add mimetype for .json (bpo-3048)
https://github.com/python/cpython/commit/8204b903683f9e0f037ccfaa87622716019914d7

**Comment by bitdancer** [comment]
New changeset 47e5f791223773dd46273153e9fa5b48f848f0c9 by R. David Murray (Miss Islington (bot)) in branch '2.7':
[2.7] bpo-30824: Add mimetype for .json (GH-3048) (bpo-3394)
https://github.com/python/cpython/commit/47e5f791223773dd46273153e9fa5b48f848f0c9

**Comment by bitdancer** [comment]
New changeset e29ab7e75138e198b51c8bd04afa16d9d2c976a5 by R. David Murray (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-30824: Add mimetype for .json (GH-3048) (bpo-3401)
https://github.com/python/cpython/commit/e29ab7e75138e198b51c8bd04afa16d9d2c976a5

**Comment by berkerpeksag** [comment]
3.5 is now in security-fix-only mode so I'm closing this one as 'fixed'. Thank you, all.
