### ISSUE TITLE
UnloadUserprofile displays the error "The handle is invalid"

### ISSUE THREAD

**Issue by 2f05a21b-aac3-4078-a2b7-960aebd35f27** [python/cpython#75016]
BPO | [30833](https://bugs.python.org/issue30833)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
Files | <li>[issue.py](https://bugs.python.org/file46988/issue.py "Uploaded as text/plain at 2017-07-03.10:08:56 by d doe")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-03.10:08:57.085>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'UnloadUserprofile displays the error "The handle is invalid"'
updated_at = <Date 2017-07-03.10:09:47.619>
user = 'https://bugs.python.org/ddoe'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-03.10:09:47.619>
actor = 'd doe'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2017-07-03.10:08:57.085>
creator = 'd doe'
dependencies = []
files = ['46988']
hgrepos = []
issue_num = 30833
keywords = []
message_count = 1.0
messages = ['297550']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'd doe']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30833'
versions = ['Python 2.7', 'Python 3.7']
```

</p></details>

**Comment by 2f05a21b-aac3-4078-a2b7-960aebd35f27** [comment]
UnloadUserprofile displays the error "The handle is invalid" the second time it is called.
The script in attachment gives reproduction steps.

The issue have been found on Windows 2008r2, windows 2012r2.
It exists with python 2.7 and python 3.7. (script done for 2.7)

**Comment by iritkatriel** [comment]
win32profile is not a Python module. Closing as third party issue.
