### ISSUE TITLE
Remove own implementation for thread-local storage

### ISSUE THREAD

**Issue by 703b20e5-de45-4041-8834-18834780ba2b** [python/cpython#75015]
BPO | [30832](https://bugs.python.org/issue30832)
--- | :---
Nosy | @vstinner, @ma8ma
PRs | <li>python/cpython#2537</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-03.14:00:29.256>
created_at = <Date 2017-07-03.08:23:53.413>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Remove own implementation for thread-local storage'
updated_at = <Date 2017-07-05.13:44:56.600>
user = 'https://github.com/ma8ma'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-05.13:44:56.600>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-03.14:00:29.256>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-07-03.08:23:53.413>
creator = 'masamoto'
dependencies = []
files = []
hgrepos = []
issue_num = 30832
keywords = []
message_count = 5.0
messages = ['297543', '297547', '297572', '297588', '297749']
nosy_count = 2.0
nosy_names = ['vstinner', 'masamoto']
pr_nums = ['2537']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30832'
versions = ['Python 3.7']
```

</p></details>

**Comment by 703b20e5-de45-4041-8834-18834780ba2b** [comment]
CPython has provided the own implementation for thread-local storage (TLS) on [Python/thread.c](https://github.com/python/cpython/blob/main/Python/thread.c), it's used in the case which a platform has not supplied native TLS.  However, currently all supported platforms (NT and pthreads) have provided native TLS and defined the Py_HAVE_NATIVE_TLS macro with unconditional in any case.
Therefore, I'd propose removing outdated code.

python-dev: https://mail.python.org/pipermail/python-dev/2017-July/148534.html

**Comment by vstinner** [comment]
This change is related to the PEP-539: the new Thread-Local Storage (TLS) API.

**Comment by vstinner** [comment]
New changeset aa0aa0492c5fffe750a26d2ab13737a1a6d7d63c by Victor Stinner (Masayuki Yamamoto) in branch 'master':
bpo-30832: Remove own implementation for thread-local storage (bpo-2537)
https://github.com/python/cpython/commit/aa0aa0492c5fffe750a26d2ab13737a1a6d7d63c

**Comment by vstinner** [comment]
Well done, I didn't see any major outdage (compilation error) on 3.x buildbots ;-)

**Comment by vstinner** [comment]
New changeset 8207c17486baece8ed0ac42d9f8d69ecec4ba7e4 by Victor Stinner in branch 'master':
Revert "bpo-30822: Fix testing of datetime module." (bpo-2588)
https://github.com/python/cpython/commit/8207c17486baece8ed0ac42d9f8d69ecec4ba7e4
