### ISSUE TITLE
Tweak order of links in https://www.python.org/downloads/source/

### ISSUE THREAD

**Issue by d7de5f0b-c30e-493b-b61c-b08f34219386** [python/cpython#75010]
BPO | [30827](https://bugs.python.org/issue30827)
--- | :---
Nosy | @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-02.09:54:34.972>
created_at = <Date 2017-07-02.09:50:54.677>
labels = ['type-feature', 'expert-installation', 'docs']
title = 'Tweak order of links in https://www.python.org/downloads/source/'
updated_at = <Date 2017-07-02.09:54:34.963>
user = 'https://bugs.python.org/SargeBorsch'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-02.09:54:34.963>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-02.09:54:34.972>
closer = 'berker.peksag'
components = ['Documentation', 'Installation']
creation = <Date 2017-07-02.09:50:54.677>
creator = 'Sarge Borsch'
dependencies = []
files = []
hgrepos = []
issue_num = 30827
keywords = []
message_count = 2.0
messages = ['297510', '297511']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'Sarge Borsch']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30827'
versions = ['Python 2.7']
```

</p></details>

**Comment by d7de5f0b-c30e-493b-b61c-b08f34219386** [comment]
Right now, there are these links in https://www.python.org/downloads/source/:
    Latest Python 2 Release - Python 2.7.13
    Latest Python 3 Release - Python 3.6.1

Python 3 should be the first, because it's the real Python now, and Python 2 is deprecated and legacy.

**Comment by berkerpeksag** [comment]
Thank you for the report, Sarge. This is already reported to python.org issue tracker at https://github.com/python/pythondotorg/issues/1079

Closing this as 'third party'.
