### ISSUE TITLE
Fix a variable shadowing warning in Python-ast.c

### ISSUE THREAD

**Issue by 01739b76-d2eb-4f5a-9981-7fcc911f8676** [python/cpython#75024]
BPO | [30841](https://bugs.python.org/issue30841)
--- | :---
Nosy | @brettcannon, @ncoghlan, @benjaminp, @ambv, @1st1, @OswinC
PRs | <li>python/cpython#2180</li><li>python/cpython#2181</li><li>python/cpython#2182</li><li>python/cpython#3001</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-04.18:00:35.117>
created_at = <Date 2017-07-03.19:21:00.693>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Fix a variable shadowing warning in Python-ast.c'
updated_at = <Date 2017-08-04.18:00:35.116>
user = 'https://github.com/OswinC'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-04.18:00:35.116>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-04.18:00:35.117>
closer = 'lukasz.langa'
components = ['Interpreter Core']
creation = <Date 2017-07-03.19:21:00.693>
creator = 'OswinC'
dependencies = []
files = []
hgrepos = []
issue_num = 30841
keywords = []
message_count = 5.0
messages = ['297609', '299208', '299210', '299754', '299755']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ncoghlan', 'benjamin.peterson', 'lukasz.langa', 'yselivanov', 'OswinC']
pr_nums = ['2180', '2181', '2182', '3001']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30841'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 01739b76-d2eb-4f5a-9981-7fcc911f8676** [comment]
When [Parser/asdl_c.py](https://github.com/python/cpython/blob/main/Parser/asdl_c.py) is composing the content of [Python/Python-ast.c](https://github.com/python/cpython/blob/main/Python/Python-ast.c), it uses "value" to name the variables in inner blocks, which can shadow the variables named the same in outer blocks. It would be a good practice to avoid the shadowing naming to prevent the variables from being misused.

**Comment by benjaminp** [comment]
What actually omits warnings about this?

**Comment by 01739b76-d2eb-4f5a-9981-7fcc911f8676** [comment]
This can be repro by setting -Wshadow-compatible-local when using gcc to compile Python-ast.c.
An example on my machine:
➜  cpython git:(69c0db5050) ✗ gcc-7 -Wshadow-compatible-local -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I./Include -I. -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -I/Users/python/.pyenv/versions/3.6.1/include -I/usr/local/include -I/Users/python/.pyenv/versions/3.6.1/include/python3.6m -c [Python/Python-ast.c](https://github.com/python/cpython/blob/main/Python/Python-ast.c) -o build/temp.macosx-10.12-x86_64-3.6/Python-ast.o
[Python/Python-ast.c](https://github.com/python/cpython/blob/main/Python/Python-ast.c): In function 'obj2ast_stmt':
[Python/Python-ast.c:4586](https://github.com/python/cpython/blob/main/Python/Python-ast.c#L4586):25: warning: declaration of 'value' shadows a previous local [-Wshadow=compatible-local]
                 expr_ty value;
                         ^~~~~
[Python/Python-ast.c:4570](https://github.com/python/cpython/blob/main/Python/Python-ast.c#L4570):17: note: shadowed declaration is here
         expr_ty value;
                 ^~~~~

**Comment by ambv** [comment]
The actual change is just three lines in asdl_c.py. Python-ast.c is generated.

**Comment by ambv** [comment]
Thanks!
