### ISSUE TITLE
IDLE: configdialog -- fix tkinter Variables

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#75034]
BPO | [30851](https://bugs.python.org/issue30851)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#2626</li><li>python/cpython#2648</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-10.19:15:04.531>
created_at = <Date 2017-07-05.01:25:38.842>
labels = ['expert-IDLE', 'type-bug', '3.7']
title = 'IDLE: configdialog -- fix tkinter Variables'
updated_at = <Date 2017-07-10.19:15:04.529>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-10.19:15:04.529>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-10.19:15:04.531>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-05.01:25:38.842>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 30851
keywords = []
message_count = 5.0
messages = ['297692', '297916', '298022', '298074', '298078']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'cheryl.sabella']
pr_nums = ['2626', '2648']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30851'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
As part of bpo-30777, Cheryl Sabella listed Variables defined for a tab page, and the use thereof, in the docstring for the tab page.  This revealed some anomalies.

Duplicate: font_name is defined on font and highlight pages.  The first StringVariable should be attached to a widget before the name is rebound.  We should investigate after there are tests for the two pages.

Unused: for anything deleted, make sure that there is no corresponding trace function left.

binding_target (keys) sounds like something that was never an external option but just an internal implementation detail; delete.

encoding (general) \*is* an external option, but I believe used only by 2.x.  Recheck (in config.py also) and probably delete.

user_help_browser and help_browser (general) may have once been options.  We now use the system browser, which, at least on some systems, users can set.  Delete.

**Comment by csabella** [comment]
Created the pull request so it's ready once the tests are available.

**Comment by terryjreedy** [comment]
After wresting with a test for bpo-30870, I am not sure we will ever have the full tests I would like.  Anyway, I concluded that the replacement of font_name is a bug.  It did not matter because all pages are created before configuration is read.  If any of font_name, font_bold, or font_size are changed, set_font_sample is called to define a new font and reset the fonts for the samples on both font and hightlight pages.  I checked that this still works.

I convinced myself that the 3.6+ dialog cannot change 'encoding' in userCfg.

**Comment by terryjreedy** [comment]
New changeset aa8d0a24694bea05061f1920ec3f944a9e6799d5 by terryjreedy (csabella) in branch 'master':
bpo-30851: IDLE: Remove unused tk variables in configdialog. (bpo-2626)
https://github.com/python/cpython/commit/aa8d0a24694bea05061f1920ec3f944a9e6799d5

**Comment by terryjreedy** [comment]
New changeset 8e3f73e5499a5bc575a5e7ad4ee0f16b1aaae829 by terryjreedy in branch '3.6':
[3.6] bpo-30851: IDLE: Remove unused tk variables in configdialog. (GH-2626) (bpo-2648)
https://github.com/python/cpython/commit/8e3f73e5499a5bc575a5e7ad4ee0f16b1aaae829
