### ISSUE TITLE
[2.7] bsddb3: test01_basic_replication() of test_bsddb3 fails randomly on AMD64 Windows8.1 Refleaks 2.7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75033]
BPO | [30850](https://bugs.python.org/issue30850)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba
PRs | <li>python/cpython#2584</li><li>python/cpython#2840</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.13:43:57.959>
created_at = <Date 2017-07-04.15:20:07.697>
labels = ['tests', 'library', 'OS-windows']
title = '[2.7] bsddb3: test01_basic_replication() of test_bsddb3 fails randomly on AMD64 Windows8.1 Refleaks 2.7'
updated_at = <Date 2018-05-11.15:30:57.281>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-11.15:30:57.281>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-24.13:43:57.959>
closer = 'vstinner'
components = ['Library (Lib)', 'Tests', 'Windows']
creation = <Date 2017-07-04.15:20:07.697>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30850
keywords = []
message_count = 11.0
messages = ['297676', '297697', '297712', '297719', '297726', '298466', '298945', '298946', '298956', '298968', '316400']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = ['2584', '2840']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30850'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
See also bpo-30778: "test_bsddb3 crash on x86 Windows XP 2.7".

http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%202.7/builds/40/steps/test/logs/stdio

```pytb
1:07:30 [145/403/1] test_bsddb3 failed -- running: test_weakref (4038 sec), test_io (2487 sec), test_mmap (1406 sec)
test_bsddb3 still working, be patient...
  test_bsddb3 still working, be patient...
  test_bsddb3 still working, be patient...
Berkeley DB 4.7.25: (May 15, 2008)
Test path prefix:  d:\temp\z-test_bsddb3-5156
XXX: timeout happened beforestartup was confirmed - see issue 3892
test test_bsddb3 failed -- Traceback (most recent call last):
  File "D:\buildarea\2.7.ware-win81-release.refleak\build\lib\bsddb\test\test_replication.py", line 384, in test01_basic_replication
    self.assertTrue(time.time()<timeout)
AssertionError: False is not true
```

**Comment by serhiy-storchaka** [comment]
First at all replace self.assertTrue(time.time()\<timeout) with self.assertLess(time.time(), timeout).

There was a large set of patches that did this globally for all tests (bpo-16510 and subissues), but it was mostly rejected (only some parts were merged, and often only into master).

**Comment by vstinner** [comment]
"First at all replace self.assertTrue(time.time()\<timeout) with
self.assertLess(time.time(), timeout). There was a large set of
patches that did this globally for all tests (bpo-16510 and
subissues), but it was mostly rejected (only some parts were merged,
and often only into master)."

Can you please propose a PR for that Serhiy, please?

**Comment by serhiy-storchaka** [comment]
> Can you please propose a PR for that Serhiy, please?

Will do.

**Comment by vstinner** [comment]
New changeset 2b92cd3b16ba83aaaf11a91a19845ca6804663d9 by Victor Stinner (Serhiy Storchaka) in branch '2.7':
bpo-30850: Use specialized assert methods in bsddb tests. (bpo-2584)
https://github.com/python/cpython/commit/2b92cd3b16ba83aaaf11a91a19845ca6804663d9

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%202.7/builds/50

```pytb
...
test03_ThreadedTransactions (bsddb.test.test_thread.HashThreadedTransactions) ... ok
test03_ThreadedTransactions (bsddb.test.test_thread.BTreeThreadedNoWaitTransactions) ... ok
test03_ThreadedTransactions (bsddb.test.test_thread.HashThreadedNoWaitTransactions) ... ok
testCheckElapsedTime (test.test_bsddb3.TimingCheck) ... beginning 6 repetitions
123456
......
Berkeley DB 4.7.25: (May 15, 2008)
Test path prefix:  d:\temp\z-test_bsddb3-4292
XXX: timeout happened beforestartup was confirmed - see issue 3892
test test_bsddb3 failed -- Traceback (most recent call last):
  File "D:\buildarea\2.7.ware-win81-release.refleak\build\lib\bsddb\test\test_lock.py", line 132, in test04_lock_timeout2
    self.assertGreaterEqual(end_time-start_time, 0.0999)
AssertionError: 0.09599995613098145 not greater than or equal to 0.0999
```


ok

\======================================================================
FAIL: test04_lock_timeout2 (bsddb.test.test_lock.LockingTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "D:\buildarea\2.7.ware-win81-release.refleak\build\lib\bsddb\test\test_lock.py", line 132, in test04_lock_timeout2
    self.assertGreaterEqual(end_time-start_time, 0.0999)
AssertionError: 0.09599995613098145 not greater than or equal to 0.0999
```

**Comment by vstinner** [comment]
x86 Windows XP 2.7:

http://buildbot.python.org/all/builders/x86%20Windows%20XP%202.7/builds/240/steps/test/logs/stdio

\======================================================================
FAIL: test04_lock_timeout2 (bsddb.test.test_lock.LockingTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "d:\cygwin\home\db3l\buildarea\2.7.bolen-windows\build\lib\bsddb\test\test_lock.py", line 132, in test04_lock_timeout2
    self.assertGreaterEqual(end_time-start_time, 0.0999)
AssertionError: 0.05800008773803711 not greater than or equal to 0.0999
```

**Comment by vstinner** [comment]
I wrote https://github.com/python/cpython/pull/2840 to tolerate only 50 ms on Windows, whereas 100 ms are expected (the test expects 99 ms or greater).

**Comment by vstinner** [comment]
New changeset 0fc940a09ae6636e78f94ecf6436b8de14bd1c45 by Victor Stinner in branch '2.7':
test_bsddb3 tolerates smaller timeout on Windows (bpo-2840)
https://github.com/python/cpython/commit/0fc940a09ae6636e78f94ecf6436b8de14bd1c45

**Comment by vstinner** [comment]
The test fails randomly. Since I'm unable to reproduce the bug, I close the bug. (If the bug is not fixed, I will reopen the issue.)
