### ISSUE TITLE
Compile error on Python/ceval.c without threads

### ISSUE THREAD

**Issue by 703b20e5-de45-4041-8834-18834780ba2b** [python/cpython#75037]
BPO | [30854](https://bugs.python.org/issue30854)
--- | :---
Nosy | @pitrou, @vstinner, @ma8ma
PRs | <li>python/cpython#2581</li><li>python/cpython#2583</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-05.09:25:12.100>
created_at = <Date 2017-07-05.07:53:20.494>
labels = ['build', '3.7']
title = 'Compile error on Python/ceval.c without threads'
updated_at = <Date 2017-07-05.13:44:55.781>
user = 'https://github.com/ma8ma'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-05.13:44:55.781>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-05.09:25:12.100>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-07-05.07:53:20.494>
creator = 'masamoto'
dependencies = []
files = []
hgrepos = []
issue_num = 30854
keywords = []
message_count = 5.0
messages = ['297711', '297716', '297723', '297724', '297742']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'masamoto']
pr_nums = ['2581', '2583']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30854'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 703b20e5-de45-4041-8834-18834780ba2b** [comment]
I found a syntax error when compiling without threads.
In that place, the colon has been used instead of semicolon at end of statement.

build commands and error log:
$ uname -a
Linux masayuki-P35-DS3 4.4.0-83-generic #106-Ubuntu SMP Mon Jun 26 17:54:25 UTC 2017 i686 i686 i686 GNU/Linux
$ git checkout master
$ ./configure --without-threads && LC_ALL=C make -j2
(snip)
gcc -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes    -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration   -I. -I./Include    -DPy_BUILD_CORE -o [Python/ceval.o](https://github.com/python/cpython/blob/main/Python/ceval.o) [Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c)
[Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c): In function 'Py_MakePendingCalls':
[Python/ceval.c:551](https://github.com/python/cpython/blob/main/Python/ceval.c#L551):23: error: expected ';' before ':' token
             goto error:
                       ^
Makefile:1551: recipe for target '[Python/ceval.o](https://github.com/python/cpython/blob/main/Python/ceval.o)' failed
make: *** [[Python/ceval.o](https://github.com/python/cpython/blob/main/Python/ceval.o)] Error 1

related changeset:
3024c0529077f5cff0b32dc84b5923c8fba99a87 [3.6] bpo-30703: Improve signal delivery (GH-2415) (bpo-2527)
c08177a1ccad2ed0d50898c2731b518c631aed14 bpo-30703: Improve signal delivery (bpo-2415)

I open one line change PR that replaces colon with semicolon for master branch right away.

**Comment by vstinner** [comment]
New changeset 0c3116309307ad2c7f8e2d2096612f4ab33cbb62 by Victor Stinner (Masayuki Yamamoto) in branch 'master':
bpo-30854: Fix compile error when --without-threads (bpo-2581)
https://github.com/python/cpython/commit/0c3116309307ad2c7f8e2d2096612f4ab33cbb62

**Comment by vstinner** [comment]
New changeset e3a0ff0d76b9e7a994afa7f2c54b19a63f1bb57d by Victor Stinner (Masayuki Yamamoto) in branch '3.6':
[3.6] bpo-30854: Fix compile error when --without-threads (GH-2581) (bpo-2583)
https://github.com/python/cpython/commit/e3a0ff0d76b9e7a994afa7f2c54b19a63f1bb57d

**Comment by vstinner** [comment]
Thanks Masayuki Yamamoto for your fixes!

**Comment by vstinner** [comment]
New changeset 8207c17486baece8ed0ac42d9f8d69ecec4ba7e4 by Victor Stinner in branch 'master':
Revert "bpo-30822: Fix testing of datetime module." (bpo-2588)
https://github.com/python/cpython/commit/8207c17486baece8ed0ac42d9f8d69ecec4ba7e4
