### ISSUE TITLE
Consolidate stateful C globals under a single struct.

### ISSUE THREAD

**Issue by ericsnowcurrently** [python/cpython#75043]
BPO | [30860](https://bugs.python.org/issue30860)
--- | :---
Nosy | @ncoghlan, @pitrou, @vstinner, @benjaminp, @jkloth, @ericsnowcurrently, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#2594</li><li>python/cpython#3379</li><li>python/cpython#3397</li><li>python/cpython#3458</li><li>python/cpython#3498</li><li>python/cpython#3499</li><li>python/cpython#3506</li><li>python/cpython#3507</li><li>python/cpython#3567</li><li>python/cpython#4532</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericsnowcurrently'
closed_at = <Date 2017-09-14.23:57:39.144>
created_at = <Date 2017-07-05.20:30:30.280>
labels = ['type-feature', '3.7']
title = 'Consolidate stateful C globals under a single struct.'
updated_at = <Date 2017-11-24.11:09:30.985>
user = 'https://github.com/ericsnowcurrently'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.11:09:30.985>
actor = 'vstinner'
assignee = 'eric.snow'
closed = True
closed_date = <Date 2017-09-14.23:57:39.144>
closer = 'eric.snow'
components = []
creation = <Date 2017-07-05.20:30:30.280>
creator = 'eric.snow'
dependencies = []
files = []
hgrepos = []
issue_num = 30860
keywords = ['patch']
message_count = 20.0
messages = ['297780', '297782', '297794', '297848', '297851', '301428', '301435', '301436', '301438', '301599', '301679', '301735', '301884', '301885', '301927', '301931', '301935', '302153', '302216', '306888']
nosy_count = 8.0
nosy_names = ['ncoghlan', 'pitrou', 'vstinner', 'benjamin.peterson', 'jkloth', 'eric.snow', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['2594', '3379', '3397', '3458', '3498', '3499', '3506', '3507', '3567', '4532']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30860'
versions = ['Python 3.7']
```

</p></details>

**Comment by ericsnowcurrently** [comment]
CPython's C code makes extensive use of global variables.  The globals fall into one of several categories:

* (effectively) constants (incl. static types)
* freelists, caches, and counters
* used exclusively in main or in REPL
* process-global state
* module state
* Python runtime state

Those in the last category are not explicitly organized nor easily discoverable.  Among other things, this has an impact on efforts that change the runtime (e.g. my multi-core Python project).  To improve the situation I'd like to do the following:

1. group the (stateful) runtime globals into various topical structs
2. consolidate the topical structs under a single top-level \_PyRuntimeState struct
3. add a check-c-globals.py script that helps identify runtime globals

One side effect of consolidating these globals is a significant performance improvement of CPython.  Presumably this is due to the caching behavior of a single struct vs. that of dozens of separate globals.

I have a patch and will put up a PR momentarily.

**Comment by ericsnowcurrently** [comment]
One thing I'd like to also try is to use a freelist embedded in \_PyRuntimeState for the PyInterpreterState and PyThreadState linked lists.

**Comment by serhiy-storchaka** [comment]
See also bpo-29881.

**Comment by pitrou** [comment]
After looking at the PR, I'm a bit skeptical about this.  Suddenly a lot of things which are implementation details get moved to the public include files, which makes things more confusing from my POV.  I also don't know why all globals should be consolidated in a single place (it is not a widespread policy in other projects AFAIK, but I may be mistaken).

Perhaps it would be more reasonable to consolidate the globals in each .c file independently, without trying to join all of them together in one place nor expose them in the public include files.

**Comment by ncoghlan** [comment]
The core motivation driving the original refactoring was to better understand and consolidate our runtime state in order to clarify what the GIL is actually protecting (aside from the reference counts). That then turned out to have surprising performance benefits (presumably by way of loading all of this state permanently into the CPU cache and then keeping it there).

The changes to the public include files arise more from the fact we don't currently have a common place to put internal CPython headers for declarations we want to share across compilation modules.

I agree the latter is confusing, and it could be worth having a separate "[Include/internal/CPython.h](https://github.com/python/cpython/blob/main/Include/internal/CPython.h)" header that outright failed the build if you attempted to include it without Py_BUILD_CORE set.

(This also ties into my comments on the PR, where I believe the current approach of mixing public and private state in the same structs will cause problems with compilers generating incorrect field offsets in extension modules and embedding applications)

**Comment by ericsnowcurrently** [comment]
New changeset 76d5abc8684bac4f2fc7cccfe2cd940923357351 by Eric Snow in branch 'master':
bpo-30860: Consolidate stateful runtime globals. (bpo-2594)
https://github.com/python/cpython/commit/76d5abc8684bac4f2fc7cccfe2cd940923357351

**Comment by vstinner** [comment]
Sadly, Windows doesn't like much your big change.

Just one example:

     2>C:\buildbot.python.org\3.x.kloth-win64\build\Include\Python-ast.h(563): warning C4005: 'Yield': macro redefinition [C:\buildbot.python.org\3.x.kloth-win64\build\PCbuild\pythoncore.vcxproj]
         C:\Program Files (x86)\Windows Kits\8.1\Include\um\winbase.h(97): note: see previous definition of 'Yield'
         bltinmodule.c

http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%203.x/builds/954/steps/compile/logs/stdio

**Comment by benjaminp** [comment]
I'm also a bit skeptical about the header design in this PR. We should not to have a monolithic \_Python.h header, and it should not be sometimes included in Python.h. Rather, code that needs the internal headers should include them directly. In fact, this PR regresses that by moving all the internal headers into Include/...

**Comment by ericsnowcurrently** [comment]
New changeset 05351c1bd8b70d1878527762174cdaaba3572395 by Eric Snow in branch 'master':
Revert "bpo-30860: Consolidate stateful runtime globals." (bpo-3379)
https://github.com/python/cpython/commit/05351c1bd8b70d1878527762174cdaaba3572395

**Comment by ncoghlan** [comment]
Regarding the accidental exposure of \_Py_CheckRecursionLimit, the main active usage of the stable ABI that we're aware of is Riverbank's C/C++ binding generator for PyQt: http://pyqt.sourceforge.net/Docs/sip4/directives.html#directive-%Module (see the use_limited_api option for the linked directive)

I checked with Phil Thomson (sip's maintainer), and the bindings sip generates don't use either of the public macros that access this nominally private value.

**Comment by ericsnowcurrently** [comment]
New changeset 2ebc5ce42a8a9e047e790aefbf9a94811569b2b6 by Eric Snow in branch 'master':
bpo-30860: Consolidate stateful runtime globals. (bpo-3397)
https://github.com/python/cpython/commit/2ebc5ce42a8a9e047e790aefbf9a94811569b2b6

**Comment by ericsnowcurrently** [comment]
FYI, the merged code introduced a bunch of new warnings on Windows.  I'm looking into it.

**Comment by vstinner** [comment]
The commit 2ebc5ce42a8a9e047e790aefbf9a94811569b2b6 introduced reference leaks: see bpo-31420 which tracks them.

**Comment by vstinner** [comment]
New changeset 4866957e86594935ec2e6434b6e470ebeb0c79b4 by Victor Stinner in branch 'master':
bpo-30860: Add [Include/internal/](https://github.com/python/cpython/blob/main/Include/internal) in "make tags" (bpo-3498)
https://github.com/python/cpython/commit/4866957e86594935ec2e6434b6e470ebeb0c79b4

**Comment by ericsnowcurrently** [comment]
New changeset ba6d5d1defd7a281c8c8804e4b4cfd7370886236 by Eric Snow in branch 'master':
bpo-30860: Always provide serialno. (bpo-3507)
https://github.com/python/cpython/commit/ba6d5d1defd7a281c8c8804e4b4cfd7370886236

**Comment by vstinner** [comment]
New changeset 8728018624f257c7cfe44014742ae46134047f49 by Victor Stinner (Eric Snow) in branch 'master':
bpo-30860: Fix a refleak. (bpo-3506)
https://github.com/python/cpython/commit/8728018624f257c7cfe44014742ae46134047f49

**Comment by ericsnowcurrently** [comment]
New changeset fc1bf872e9d31f3e837f686210f94e57ad3d6582 by Eric Snow in branch 'master':
bpo-30860: Move windows.h include out of internal/*.h. (bpo-3458)
https://github.com/python/cpython/commit/fc1bf872e9d31f3e837f686210f94e57ad3d6582

**Comment by ericsnowcurrently** [comment]
New changeset dae0276bb6bc7281d59fb0b8f1aab31634ee80dc by Eric Snow in branch 'master':
bpo-30860: Fix a refleak. (bpo-3567)
https://github.com/python/cpython/commit/dae0276bb6bc7281d59fb0b8f1aab31634ee80dc

**Comment by vstinner** [comment]
New changeset ccb3c7654cc3d031fb93bf443a6ef9cfb11f6b43 by Victor Stinner in branch 'master':
bpo-30860: Fix deadcode in obmalloc.c (bpo-3499)
https://github.com/python/cpython/commit/ccb3c7654cc3d031fb93bf443a6ef9cfb11f6b43

**Comment by vstinner** [comment]
New changeset 9e87e7776f7ace66baaf7247233afdabd00c2b44 by Victor Stinner in branch 'master':
bpo-32096: Remove obj and mem from \_PyRuntime (bpo-4532)
https://github.com/python/cpython/commit/9e87e7776f7ace66baaf7247233afdabd00c2b44
