### ISSUE TITLE
Can't install Python for Windows 3.6.1 on multiple profiles

### ISSUE THREAD

**Issue by a6586212-627a-4750-b866-857a68e4bcf4** [python/cpython#75042]
BPO | [30859](https://bugs.python.org/issue30859)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-08.03:11:12.198>
created_at = <Date 2017-07-05.19:23:15.749>
labels = ['type-bug', 'invalid', 'OS-windows']
title = "Can't install Python for Windows 3.6.1 on multiple profiles"
updated_at = <Date 2017-07-08.03:11:12.197>
user = 'https://bugs.python.org/JoeJacobs'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-08.03:11:12.197>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-08.03:11:12.198>
closer = 'terry.reedy'
components = ['Windows']
creation = <Date 2017-07-05.19:23:15.749>
creator = 'Joe Jacobs'
dependencies = []
files = []
hgrepos = []
issue_num = 30859
keywords = []
message_count = 4.0
messages = ['297776', '297786', '297788', '297802']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Joe Jacobs']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30859'
versions = ['Python 3.6']
```

</p></details>

**Comment by a6586212-627a-4750-b866-857a68e4bcf4** [comment]
Windows 7 Ultimate: SP1.  Fully pathed as of July 4th, 2017

My Windows 7 install has multiple user accounts.  The main install account is set up with "Administrator" privledges.

Some point in the past I had installed Python 3.6.1 on the main account.  Did not install for all users.  That put the python files inside the %appdata% folder.

I was then trying to go through the Python Minecraft book with my daughter.  We had logged in as my daughters login and tried to install Python 3.6.1 for her.  Got an error stating Python was already installed, even though she couldn't access it for her Windows login.

Ultimately, had to uninstall Python 3.6, and reinstall for "All users".  

Would think that multiple users could install Python in their own folder regardless of versions that other people have installed.

**Comment by eryksun** [comment]
In Windows 10, I have 32-bit 3.6.1 installed for both an administrator and a standard user, both per-user installations. Maybe the logs from the failed attempt will help clarify what went wrong. If they still exist in the account's %temp% folder, please zip them up to a single file and upload it to this issue.

**Comment by a6586212-627a-4750-b866-857a68e4bcf4** [comment]
I checked, there are no install logs.

Just realized, maybe an issue with the web installer rather than the base installer.

python-3.6.1-amd64-webinstall

Had downloaded this file and tried to run it.  I wouldn't even get to the screen that asks you to do a standard or custom install.  The only screen that popped up said python was already installed.

I run it now after i uninstalled and re-installed for "All Users" and i don't have that issue.

Are the logs for the web installer stored somewhere else?  If not, maybe i'll try again and see if i can replicate again.

**Comment by a6586212-627a-4750-b866-857a68e4bcf4** [comment]
So, with the feedback, i uninstalled everything and tried installing again, but in the %appdata% folder for both users and everything worked fine.  Both users have python installed.  If i run the web launcher, the first time it installs on the second account and subsequent running of the launcher ask me to uninstall or repair as expected.

I'm unable to find logs for the failed installs in the %temp% folder.  If i'm able to duplicate the issue, i'll open a new bug report.

Please go ahead and close this report.
