### ISSUE TITLE
test_bsddb3 hangs longer than 37 minutes on x86 Tiger 2.7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75040]
BPO | [30857](https://bugs.python.org/issue30857)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-10.23:55:58.292>
created_at = <Date 2017-07-05.14:05:25.093>
labels = ['OS-mac', 'tests']
title = 'test_bsddb3 hangs longer than 37 minutes on x86 Tiger 2.7'
updated_at = <Date 2017-08-10.23:55:58.291>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-10.23:55:58.291>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-10.23:55:58.292>
closer = 'vstinner'
components = ['macOS', 'Tests']
creation = <Date 2017-07-05.14:05:25.093>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30857
keywords = []
message_count = 4.0
messages = ['297758', '297759', '297767', '300134']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30857'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/x86%20Tiger%202.7/builds/227/steps/test/logs/stdio

...
running: test_bsddb3 (2204 sec), test_itertools (30 sec)
0:50:54 [394/403] test_itertools passed (42 sec) -- running: test_bsddb3 (2217 sec)
0:51:00 [395/403] test_telnetlib passed -- running: test_bsddb3 (2223 sec)
0:51:06 [396/403] test_urllibnet passed -- running: test_bsddb3 (2228 sec)
0:51:07 [397/403] test_xrange passed -- running: test_bsddb3 (2230 sec)
0:51:07 [398/403] test_buffer passed -- running: test_bsddb3 (2230 sec)
0:51:08 [399/403] test_sys_setprofile passed -- running: test_bsddb3 (2231 sec)
0:51:09 [400/403] test_sysconfig passed -- running: test_bsddb3 (2232 sec)
[21696 refs]
[21696 refs]
0:51:10 [401/403] test_pkg passed -- running: test_bsddb3 (2233 sec)
0:51:13 [402/403] test_capi passed -- running: test_bsddb3 (2236 sec)

command timed out: 1800 seconds without output running ['make', 'buildbottest', 'TESTOPTS=-j2', 'TESTPYTHONOPTS=', 'TESTTIMEOUT=1500'], attempting to kill
process killed by signal 9
program finished with exit code -1
elapsedTime=4880.023461

**Comment by vstinner** [comment]
See also bpo-30850 " [2.7] bsddb3: test01_basic_replication() of test_bsddb3 fails randomly on AMD64 Windows8.1 Refleaks 2.7 " and bpo-30778 " test_bsddb3 crash on x86 Windows XP 2.7 ".

**Comment by serhiy-storchaka** [comment]
On http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%202.7/builds/41/steps/test/logs/stdio
 test_bsddb3  is passed but takes more than 2 hours. It is the slowest test.

**Comment by vstinner** [comment]
Sadly I didn't see this bug recently, so I just close the issue.
