### ISSUE TITLE
round(number[, digits])  does not return value with >12 decimal places

### ISSUE THREAD

**Issue by 3a3d6a45-29ca-4368-931f-7d69ea3c1dfb** [python/cpython#75058]
BPO | [30875](https://bugs.python.org/issue30875)
--- | :---
Nosy | @mdickinson, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-08.16:26:57.314>
created_at = <Date 2017-07-08.03:07:40.867>
labels = ['library']
title = 'round(number[, digits])  does not return value with >12 decimal places'
updated_at = <Date 2017-07-08.16:26:57.313>
user = 'https://bugs.python.org/johnForgue'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-08.16:26:57.313>
actor = 'john Forgue'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-08.16:26:57.314>
closer = 'john Forgue'
components = ['Library (Lib)']
creation = <Date 2017-07-08.03:07:40.867>
creator = 'john Forgue'
dependencies = []
files = []
hgrepos = []
issue_num = 30875
keywords = []
message_count = 3.0
messages = ['297928', '297929', '297959']
nosy_count = 3.0
nosy_names = ['mark.dickinson', 'steven.daprano', 'john Forgue']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30875'
versions = ['Python 3.4']
```

</p></details>

**Comment by 3a3d6a45-29ca-4368-931f-7d69ea3c1dfb** [comment]
I have a sensor that returns float with 15 decimal places.

Using  "round(number[, digits])" in a program I get no rounding

Using the same command in the terminal interpreter it returns
...   (3 periods) then hangs requiring ^C to continue.

I'm using Python 3.4.2 on RasPi Jessie.

**Comment by stevendaprano** [comment]
> Using  "round(number[, digits])" in a program I get no rounding

It works for me. Can you show an example of it not working?

py\> round(1.23456789012345, 3)
1.235


> Using the same command in the terminal interpreter it returns
> ...   (3 periods) then hangs requiring ^C to continue.


That sounds like the interactive interpreter is waiting for a closing parenthesis (round bracket). It will sit and wait forever for you to finish typing the command. If you hit ENTER, you'll just get another prompt.

py\> round(1.23456789012345, 3
...
...
... )
1.235


If this does not explain what you are seeing, you will have to give us more information, including examples of the failures and instructions for how to replicate the failure.

**Comment by 3a3d6a45-29ca-4368-931f-7d69ea3c1dfb** [comment]
I found a programming issue that circumvented the round function.  As for the terminal "verification" I reported.... I'm not sure what I did and cannot repeat.

Sorry for the false alarm.

John
