### ISSUE TITLE
unittest execute tests twice in some conditions

### ISSUE THREAD

**Issue by cf4f7014-9aeb-4803-aa63-f58cbfac5fd5** [python/cpython#75057]
BPO | [30874](https://bugs.python.org/issue30874)
--- | :---
Nosy | @terryjreedy, @rbtcollins, @ezio-melotti, @voidspace, @mlouielu, @ale5000-git

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-08.03:03:49.065>
labels = ['type-bug']
title = 'unittest execute tests twice in some conditions'
updated_at = <Date 2017-08-25.10:52:13.654>
user = 'https://github.com/ale5000-git'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-25.10:52:13.654>
actor = 'ale5000'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-07-08.03:03:49.065>
creator = 'ale5000'
dependencies = []
files = []
hgrepos = []
issue_num = 30874
keywords = []
message_count = 6.0
messages = ['297927', '298366', '298376', '298383', '298452', '300832']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'rbcollins', 'ezio.melotti', 'michael.foord', 'louielu', 'ale5000']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30874'
versions = ['Python 3.6']
```

</p></details>

**Comment by cf4f7014-9aeb-4803-aa63-f58cbfac5fd5** [comment]
Unittest execute the tests twice in some conditions.

You can see the log here: https://travis-ci.org/ale5000-git/test/builds/251382617

based on this code: https://github.com/ale5000-git/test/tree/7a64f24a8bfea0579e30346ba993744272aa9c36

The code to load tests is this:
def custom_test_suite():
    import unittest
    return unittest.TestLoader().discover("tests", pattern="\*_test.py")

**Comment by terryjreedy** [comment]
What invocation conditions?  If this only happens with Travis, then this may be a Travis issue.  If it only happens with Travis coverage runs, then it might be intentional, or a coverage issue.

**Comment by cf4f7014-9aeb-4803-aa63-f58cbfac5fd5** [comment]
I have setup a simpler one here: https://github.com/ale5000-git/test/tree/master/unittest-1

Just run manually "setup.py test" and you will se the bug.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
On my MacOS with python 3.5.2 get this result:


➜  unittest-1 git:(master) ✗ python3 setup.py test
running test
running egg_info
writing dependency_links to Test_1.egg-info/dependency_links.txt
writing top-level names to Test_1.egg-info/top_level.txt
writing Test_1.egg-info/PKG-INFO
reading manifest file 'Test_1.egg-info/SOURCES.txt'
writing manifest file 'Test_1.egg-info/SOURCES.txt'
running build_ext
running test
running egg_info
writing dependency_links to Test_1.egg-info/dependency_links.txt
writing top-level names to Test_1.egg-info/top_level.txt
writing Test_1.egg-info/PKG-INFO
reading manifest file 'Test_1.egg-info/SOURCES.txt'
writing manifest file 'Test_1.egg-info/SOURCES.txt'
running build_ext
test_fix_all (test_main.MainTestCase) ... ok

\----------------------------------------------------------------------
Ran 1 test in 0.000s


```py
with Python 3.7.a0 got this result:
```


➜  unittest-1 git:(master) ✗ /Users/louielu/Python/cpython/python.exe -m unittest
.
\----------------------------------------------------------------------
Ran 1 test in 0.000s

OK



I think it will be more like a setting issue, not unittest problem.

**Comment by cf4f7014-9aeb-4803-aa63-f58cbfac5fd5** [comment]
@louielu: I have the problem under Windows, and on Travis CI under Linux.

**Comment by cf4f7014-9aeb-4803-aa63-f58cbfac5fd5** [comment]
hi,
is there any news?
