### ISSUE TITLE
IDLE: add docstrings to browser.py

### ISSUE THREAD

**Issue by csabella** [python/cpython#75064]
BPO | [30881](https://bugs.python.org/issue30881)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#2638</li><li>python/cpython#2663</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-11.06:40:25.212>
created_at = <Date 2017-07-08.23:58:08.992>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: add docstrings to browser.py'
updated_at = <Date 2017-07-11.06:53:34.397>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.06:53:34.397>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-11.06:40:25.212>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-08.23:58:08.992>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 30881
keywords = []
message_count = 3.0
messages = ['297973', '298131', '298133']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'cheryl.sabella']
pr_nums = ['2638', '2663']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30881'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Add docstrings to browser.py to aid to unit test creation.

**Comment by terryjreedy** [comment]
New changeset ba352270b724d67fc938c335c605acdee7474308 by terryjreedy (csabella) in branch 'master':
bpo-30881: IDLE: add docstrings to browser.py (bpo-2638)
https://github.com/python/cpython/commit/ba352270b724d67fc938c335c605acdee7474308

**Comment by terryjreedy** [comment]
New changeset 675c1adfe5c87573e81fb295ccad7b6cfa03a3ee by terryjreedy in branch '3.6':
[3.6] bpo-30881: IDLE: add docstrings to browser.py (GH-2638) (bpo-2663)
https://github.com/python/cpython/commit/675c1adfe5c87573e81fb295ccad7b6cfa03a3ee
