### ISSUE TITLE
The staticmethod doesn't properly reject keyword arguments

### ISSUE THREAD

**Issue by 62fee66e-961c-4235-99bd-93f081bdab5b** [python/cpython#75061]
BPO | [30878](https://bugs.python.org/issue30878)
--- | :---
Nosy | @serhiy-storchaka, @SylvainDe
PRs | <li>python/cpython#2635</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-09.03:47:08.992>
created_at = <Date 2017-07-08.07:00:06.230>
labels = ['interpreter-core', 'easy', 'type-feature', '3.7']
title = "The staticmethod doesn't properly reject keyword arguments"
updated_at = <Date 2017-07-09.07:27:41.595>
user = 'https://bugs.python.org/kayhayen'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-09.07:27:41.595>
actor = 'SylvainDe'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-09.03:47:08.992>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-07-08.07:00:06.230>
creator = 'kayhayen'
dependencies = []
files = []
hgrepos = []
issue_num = 30878
keywords = ['easy (C)']
message_count = 6.0
messages = ['297946', '297948', '297969', '297981', '297982', '297988']
nosy_count = 3.0
nosy_names = ['kayhayen', 'serhiy.storchaka', 'SylvainDe']
pr_nums = ['2635']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30878'
versions = ['Python 3.7']
```

</p></details>

**Comment by 62fee66e-961c-4235-99bd-93f081bdab5b** [comment]
Check out this:

```pytb
python3.6 -c "staticmethod(function=1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: staticmethod expected 1 arguments, got 0

python3.6 -c "staticmethod()"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: staticmethod expected 1 arguments, got 0

python3.6 -c "staticmethod(f=1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: staticmethod expected 1 arguments, got 0
```


I believe Python 2.7 behaves the same.

What should happen is more like this:

```pytb
python3.6 -c "range(f=1)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
TypeError: range() does not take keyword arguments
```


While statically optimizing, I came across this as a first. At least "classmethod" behaves the same. I suppose it is because these are not intended for manual use anymore.

I would recommend to fix up the argument parsing to either indicate its rejection of keyword arguments, or to accept "function = " for input (preferred).

Thanks,
Kay Hayen

**Comment by serhiy-storchaka** [comment]
This is similar to recently fixed bpo-30534 and bpo-30627. The solution is simple as for bpo-30627.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
I have a fix ready but I'll look if other functions using \_PyArg_NoKeywords may have the same defect before submitting it.

**Comment by serhiy-storchaka** [comment]
New changeset 9648088e6ccd6d0cc04f450f55628fd8eda3784c by Serhiy Storchaka (Sylvain) in branch 'master':
bpo-30878: Fix error message when keyword arguments are passed (bpo-2635)
https://github.com/python/cpython/commit/9648088e6ccd6d0cc04f450f55628fd8eda3784c

**Comment by serhiy-storchaka** [comment]
Thank you for your report Kay and thank you for your patch SylvainDe.

**Comment by c21f90fa-a1a8-4e31-b5b5-053d40995d53** [comment]
Thanks Serhiy Storchaka !

This issue seems to affect (all) other Python versions. Should we proceed to a cherry-pick ?
