### ISSUE TITLE
Built-in list disappeared from Python 2.7 intersphinx inventory

### ISSUE THREAD

**Issue by e1afdd59-e3e8-4817-96a8-290a8b7436c4** [python/cpython#75065]
BPO | [30882](https://bugs.python.org/issue30882)
--- | :---
Nosy | @zware, @serhiy-storchaka, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2020-04-27.03:47:04.071>
created_at = <Date 2017-07-09.17:53:27.989>
labels = ['type-bug', 'docs']
title = 'Built-in list disappeared from Python 2.7 intersphinx inventory'
updated_at = <Date 2020-04-27.03:47:04.070>
user = 'https://bugs.python.org/ChristophDeil'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-27.03:47:04.070>
actor = 'zach.ware'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2020-04-27.03:47:04.071>
closer = 'zach.ware'
components = ['Documentation']
creation = <Date 2017-07-09.17:53:27.989>
creator = 'Christoph.Deil'
dependencies = []
files = []
hgrepos = []
issue_num = 30882
keywords = []
message_count = 3.0
messages = ['297993', '298027', '367375']
nosy_count = 6.0
nosy_names = ['docs@python', 'zach.ware', 'serhiy.storchaka', 'Christoph.Deil', 'Mariatta', 'Benjamin Swan']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30882'
versions = ['Python 2.7']
```

</p></details>

**Comment by e1afdd59-e3e8-4817-96a8-290a8b7436c4** [comment]
We have a project where we sub-class `list`. Since recently our docs build is failing because the intersphinx inventory entry for `list` on Python 2.7 doesn't exist any more.

I think this is a regression, because Python 2.7 is supposed to be stable and other functions and classes here are still there, just "list" is missing:
https://docs.python.org/2.7/library/functions.html#func-list

Just in case someone else sees this issue, the Sphinx warning looks like this:
```
docs/api/pyregion.ShapeList.rst:7: WARNING: py:class reference target not found: list
```
if you have something like
```
class ShapeList(list):
    """My list sub-class"""
```

**Comment by serhiy-storchaka** [comment]
This is caused by backporting some changes from 3.x. In 3.x the list class is described in two places, in functions.rst and in stdtypes.rst, and these changes fixed the ambiguity by excluding the reference in functions.rst from the index. But in 2.7 this is the only description of the list class.

We need either revert changes that exclude the reference to the list class description in functions.rst from the index, or add a description in stdtypes.rst.
