### ISSUE TITLE
test_urllib2net failed on s390x Debian 3.6: ftp.debian.org error, too many connections from your internet address

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75066]
BPO | [30883](https://bugs.python.org/issue30883)
--- | :---
Nosy | @vstinner, @berkerpeksag, @serhiy-storchaka
PRs | <li>python/cpython#2755</li><li>python/cpython#2756</li><li>python/cpython#2757</li><li>python/cpython#2758</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-20.00:22:40.047>
created_at = <Date 2017-07-09.20:48:59.883>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_urllib2net failed on s390x Debian 3.6: ftp.debian.org error, too many connections from your internet address'
updated_at = <Date 2017-07-20.09:06:00.282>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-20.09:06:00.282>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-20.00:22:40.047>
closer = 'berker.peksag'
components = ['Tests']
creation = <Date 2017-07-09.20:48:59.883>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30883
keywords = []
message_count = 8.0
messages = ['297995', '298021', '298627', '298629', '298698', '298699', '298700', '298710']
nosy_count = 3.0
nosy_names = ['vstinner', 'berker.peksag', 'serhiy.storchaka']
pr_nums = ['2755', '2756', '2757', '2758']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30883'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/s390x%20Debian%203.6/builds/530/steps/test/logs/stdio

ERROR: test_ftp (test.test_urllib2net.OtherNetworkTests) (url='ftp://ftp.debian.org/debian/README')

ERROR: test_ftp_basic (test.test_urllib2net.TimeoutTest)

ERROR: test_ftp_default_timeout (test.test_urllib2net.TimeoutTest)
...
ftplib.error_temp: 421 There are too many connections from your internet address.
...
urllib.error.URLError: \<urlopen error ftp error: error_temp('421 There are too many connections from your internet address.',)\>

ERROR: test_ftp_no_timeout (test.test_urllib2net.TimeoutTest)

ERROR: test_ftp_timeout (test.test_urllib2net.TimeoutTest)

**Comment by serhiy-storchaka** [comment]
All public-facing debian.org FTP services will be shut down on November 1, 2017.

See https://www.debian.org/News/2017/20170425.

**Comment by berkerpeksag** [comment]
I merged Ammar's PR in d81bea6520892e0428aec61c73e0631a69db11bb, but it looks like I missed that the PR title and commit message was different and the latter didn't contain bpo-30883.

**Comment by berkerpeksag** [comment]
New changeset a739000db55ef55e69a53ca6966ea8657cac4354 by Berker Peksag (Ammar Askar) in branch '2.7':
[2.7] bpo-30883: Use pythontest.net instead of debian.org in test_urllib2net (GH-2755)
https://github.com/python/cpython/commit/a739000db55ef55e69a53ca6966ea8657cac4354

**Comment by berkerpeksag** [comment]
New changeset aca493b7a337338fa20395fbc2d1895cb8093826 by Berker Peksag (Ammar Askar) in branch '3.5':
[3.5] bpo-30883: Use pythontest.net instead of debian.org in test_urllib2net (GH-2755)
https://github.com/python/cpython/commit/aca493b7a337338fa20395fbc2d1895cb8093826

**Comment by berkerpeksag** [comment]
New changeset ae4dca7701ca77a37aa8c956450ff8e21fe6883e by Berker Peksag (Ammar Askar) in branch '3.6':
[3.6] bpo-30883: Use pythontest.net instead of debian.org in test_urllib2net (GH-2755)
https://github.com/python/cpython/commit/ae4dca7701ca77a37aa8c956450ff8e21fe6883e

**Comment by berkerpeksag** [comment]
Thanks, Ammar!

**Comment by vstinner** [comment]
Oh, I didn't know that pythontest.net had a FTP server. Cool! Thank you for the fix ;-)
