### ISSUE TITLE
BytesWarning in re module when compiling certain bytes patterns

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#75079]
BPO | [30896](https://bugs.python.org/issue30896)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @JelleZijlstra

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-11.02:11:08.731>
created_at = <Date 2017-07-10.23:27:55.351>
labels = ['library']
title = 'BytesWarning in re module when compiling certain bytes patterns'
updated_at = <Date 2017-07-11.02:11:08.729>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.02:11:08.729>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-11.02:11:08.731>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-07-10.23:27:55.351>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 30896
keywords = []
message_count = 2.0
messages = ['298095', '298100']
nosy_count = 3.0
nosy_names = ['ezio.melotti', 'serhiy.storchaka', 'JelleZijlstra']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30896'
versions = ['Python 3.6']
```

</p></details>

**Comment by JelleZijlstra** [comment]
This code in sre_parse (line 738 and down):

                            warnings.warn(
                                'Flags not at the start of the expression %s%s' % (
                                    source.string[:20],  # truncate long regexes
                                    ' (truncated)' if len(source.string) > 20 else '',
                                ),
                                DeprecationWarning, stacklevel=7
                            )


triggers a BytesWarning if you do `_line_re = re.compile(br'^(.*?)$(?m)')`.

The fix should be simple; I can try to get a PR in over the next few days.

**Comment by serhiy-storchaka** [comment]
Thank you for your report Jelle, but this was fixed in bpo-30605.
