### ISSUE TITLE
importlib: _find_and_load() race condition on sys.modules[name] check

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75074]
BPO | [30891](https://bugs.python.org/issue30891)
--- | :---
Nosy | @gvanrossum, @Yhg1s, @warsaw, @brettcannon, @pfmoore, @ncoghlan, @vstinner, @tjguk, @ambv, @ericsnowcurrently, @zware, @serhiy-storchaka, @zooba
PRs | <li>python/cpython#2645</li><li>python/cpython#2646</li><li>python/cpython#2651</li><li>python/cpython#2665</li><li>python/cpython#2801</li>
Files | <li>[importlib_sleep.patch](https://bugs.python.org/file47000/importlib_sleep.patch "Uploaded as text/plain at 2017-07-10.13:59:45 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-27.10:25:47.039>
created_at = <Date 2017-07-10.09:44:24.364>
labels = ['3.7', 'type-bug', 'tests', 'OS-windows']
title = 'importlib: _find_and_load() race condition on sys.modules[name] check'
updated_at = <Date 2018-04-04.19:19:31.431>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-04.19:19:31.431>
actor = 'gvanrossum'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-27.10:25:47.039>
closer = 'vstinner'
components = ['Tests', 'Windows']
creation = <Date 2017-07-10.09:44:24.364>
creator = 'vstinner'
dependencies = []
files = ['47000']
hgrepos = []
issue_num = 30891
keywords = ['patch']
message_count = 35.0
messages = ['298044', '298046', '298047', '298048', '298049', '298053', '298058', '298063', '298064', '298066', '298067', '298068', '298069', '298070', '298071', '298072', '298081', '298087', '298088', '298798', '298801', '299184', '299305', '302106', '302124', '314594', '314615', '314818', '314819', '314879', '314887', '314889', '314894', '314948', '314949']
nosy_count = 13.0
nosy_names = ['gvanrossum', 'twouters', 'barry', 'brett.cannon', 'paul.moore', 'ncoghlan', 'vstinner', 'tim.golden', 'lukasz.langa', 'eric.snow', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = ['2645', '2646', '2651', '2665', '2801']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30891'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
```pytb
1:36:32 [224/405/1] test_import failed -- running: test_mmap (2236 sec), test_io (2529 sec), test_venv (1437 sec)
beginning 6 repetitions
123456
.....test test_import failed -- Traceback (most recent call last):
  File "D:\buildarea\3.6.ware-win81-release.refleak\build\lib\test\test_import\__init__.py", line 377, in test_concurrency
    raise exc
  File "D:\buildarea\3.6.ware-win81-release.refleak\build\lib\test\test_import\__init__.py", line 362, in run
    import package
  File "D:\buildarea\3.6.ware-win81-release.refleak\build\lib\test\test_import\data\package\__init__.py", line 2, in <module>
    package.submodule
AttributeError: module 'package' has no attribute 'submodule'
```

**Comment by vstinner** [comment]
I was able to \*easily* (100% failure rate) reproduce the failure with Python 3.6 and 3.7 (master) on Windows using this command:

./python -m test -R 3:100 -m test_concurrency test_import

**Comment by vstinner** [comment]
I don't understand if a test_concurrency() failure is a bug in importlib, or a bug in the test :-)

**Comment by vstinner** [comment]
Note: "./python -m test -R 3:100 -m test_concurrency test_import" is just a convenient way to run test_concurrency() "in a loop", in the same process, 100 times.

I'm unable to reproduce the bug on Linux, even when I write 3 into /proc/sys/vm/drop_caches while the test is running to drop filesystem caches.

I also tried to use a temporary directory in my home (TMPDIR=$HOME/tmp) to use temporary files in ext4 rather than tmpfs. But I don't know if importlib uses temporary files or not :-)

**Comment by vstinner** [comment]
Oh, the unit test was added 4 days ago:

commit b4baacee1adc06edbe30ac7574d17a8cd168e2e0
Author: Serhiy Storchaka \<storchaka@gmail.com\>
Date:   Thu Jul 6 08:09:03 2017 +0300

    bpo-30814: Fixed a race condition when import a submodule from a package. (bpo-2580)

**Comment by ncoghlan** [comment]
Indeed, Serhiy's been stress-testing some bits of the import system, and finding a few holes made possible by the shift away from a single global import lock to per-module locks. (bpo-30876 is another example of that)

Nothing immediately comes to mind as a platform-dependent code path that could explain why that error is showing up on Windows and not on Linux, though.

**Comment by serhiy-storchaka** [comment]
Some parts of import machinery are platform depended (see bpo-30873).

I don't have idea what is wrong on Windows.

I'm puzzled. test_concurrency itself runs a test in a loop. The only difference between one and several consequent runs of test_concurrency is running setUp() and tearDown() between tests. Victor, try to add importlib.invalidate_caches() inside a loop. Does it cause a failure in a single test_concurrency?

**Comment by vstinner** [comment]
> Victor, try to add importlib.invalidate_caches() inside a loop. Does it cause a failure in a single test_concurrency?

I added a "importlib.invalidate_caches()" call in the "for i in range(10):" loop. With this change, a single run doesn't fail. It doesn't fix the test neither: with -R 3:100, the command still fails.

> Some parts of import machinery are platform depended (see bpo-30873).

I don't think that this bpo-30873 or bpo-30626 is platform dependent.


> I don't have idea what is wrong on Windows.

IMHO it's just that my Windows VM is slow. It's a race condition. If I run "./python -m test -m test_concurrency test_import test_import": the command pass, but when again, it fails. It's pure random :-)

**Comment by vstinner** [comment]
I added print(id(package)) in [Lib/test/test_import/data/package/__init__.py](https://github.com/python/cpython/blob/main/Lib/test/test_import/data/package/__init__.py): when the bug occurs on my Windows VM, I see two print with two different identifiers. Moreover, when the bug occurs, first id(sys.modules['package']) is the first identifier, and then package is replaced with the new 'package' package in sys.modules (new identifier).

I don't understand something: sys.modules isn't supposed to be protected by a lock? I checked if \_installed_safely.\_\_enter__() if the \_imp is held: it isn't held when \_bootstrap.\_setup() is called, nor when \_imp.\_install_external_importers() is called. But even if I patch these two functions to acquire the lock, Python startup fails on importing a codec module, because the \_imp lock is not held in \_installed_safely.\_\_enter__(). So maybe sys.modules dict is supposed to be protected by a different lock, maybe indirectly?

I hack \_bootstrap.\_find_and_load_unlocked() to sleep 10 ms if name == 'package'. With this change, test_concurrency() fails immediatly on my Linux box.

* Apply attached importlib_sleep.patch (written for the current master branch)
* Recompile: make regen-importlib && make
* Run test_concurrency() just once: ./python -m test -m test_concurrency -v test_import
* You get the bug

By the way, importlib_sleep.patch changes test_concurrency() to run the test exactly once (it changes to loop to a single iteration, instead of 10).

Is it normal that a sleep makes import failing? Imports are not supposed to be atomic?

--

I tried to similar hack before the commit b4baacee1adc06edbe30ac7574d17a8cd168e2e0:

* add a sleep in importlib
* copy test_concurrency() from master
* Run test_concurrency()
* The test pass

While I'm not sure of my hack, it \*seems* like sys.modules was somehow atomic before this commit?

**Comment by vstinner** [comment]
FYI test_concurrency() added by commit b4baacee1adc06edbe30ac7574d17a8cd168e2e0 doesn't really test bpo-30814. I backported the unit test on 1ccbad9c95cf5782a1329eeaecba6e3eb0c37cb8 (commit before b4baacee1adc06edbe30ac7574d17a8cd168e2e0), and the test pass, whereas I expected it to fail before the fix.

**Comment by ncoghlan** [comment]
No, there's no global lock on the import system these days.

Instead, imports are supposed to be atomic on a per-module basis, but bpo-30814 showed that some of the accesses to the shared state management (which \*is* still supposed to be protected by the import lock) could get into trouble given concurrent imports from different threads.

However, the new test exercises an interesting sequence of per-module lock acquisition, since each thread effectively runs through this sequence:

- import package # Test case
- import package.submodule # Package init
- import package # Parent package import

That moves back-and-forth between C & Python in a few different places, and hence may have been relying on the GIL to keep the parts executed in C atomic.

So now I'm wondering whether or not this new problem might be due to moving the \_imp.acquire_lock() calls into Python code as part of bpo-30814, as that creates a window near the start of \_find_and_load() where the thread may end up holding neither the GIL \*nor* the import lock. By contrast, when the import lock was acquired in C, then by the time the Python code starts running (potentially releasing the GIL), the import lock has already been acquired.

**Comment by vstinner** [comment]
> FYI test_concurrency() added by commit b4baacee1adc06edbe30ac7574d17a8cd168e2e0 doesn't really test bpo-30814. I backported the unit test on 1ccbad9c95cf5782a1329eeaecba6e3eb0c37cb8 (commit before b4baacee1adc06edbe30ac7574d17a8cd168e2e0), and the test pass, whereas I expected it to fail before the fix.

Oops, please ignore this comment, it was a mistake. After clearing my repository (removing \_\_pycache__ directories), the test failed. I forgot to copy the [Lib/test/test_import/data/package/](https://github.com/python/cpython/blob/main/Lib/test/test_import/data/package) directory.

**Comment by serhiy-storchaka** [comment]
test_concurrency is failed before b4baacee1adc06edbe30ac7574d17a8cd168e2e0 on my computer. I think it tests the bpo-30814 bug even if it doesn't fail on all computers. At the end, this is a race condition, and the failure is probabilistic.

**Comment by vstinner** [comment]
Using attached importlib_sleep.patch, you can \*see* the race condition with:

```diff
diff --git a/Lib/test/test_import/data/package/__init__.py b/Lib/test/test_import/data/package/__init__.py
index a4f2bc3..f07eb11 100644
--- a/Lib/test/test_import/data/package/__init__.py
+++ b/Lib/test/test_import/data/package/__init__.py
@@ -1,2 +1,3 @@
 import package.submodule
+print("package: id=%#x" % id(package))
 package.submodule
```



Example of output:
\---
haypo@selma$ ./python -m test -m test_concurrency -v test_import
package: id=0x7fb497400d58
package: id=0x7fb49744d458
test test_import failed -- (...)
\---

[Lib/test/test_import/data/package/__init__.py](https://github.com/python/cpython/blob/main/Lib/test/test_import/data/package/__init__.py) is run twice instead of being run once. A lock is missing somewhere on the package module.

**Comment by serhiy-storchaka** [comment]
Victor tested test_concurrency on 3.5, and it is failed on slow Windows VM. Therefore the bug exists on 3.5 and is not related to recent changes.

**Comment by ncoghlan** [comment]
I'm about to head to bed so I'll get back to this discussion tomorrow, but in the meantime: Victor, maybe it would make sense to reformulate your reproducer as a monkeypatch for \_find_and_load_unlocked() that injects the 10 ms sleep from the test case if it finds \_frozen_importlib in sys.modules?

That is, temporarily replacing it with something like:

```py
    orig_find_and_load_unlocked = _frozen_importlib._find_and_load_unlocked
    def _slow_find_and_load_unlocked(name, import_):
        time.sleep(0.010)
        return orig_find_and_load_unlocked(name, import_)
```


That way, we'd hopefully be able to reproduce the failure independently of the slower buildbot.

**Comment by vstinner** [comment]
New changeset 4f9a446f3fb42f800e73cd9414dd1eccb3ca4fa7 by Victor Stinner in branch 'master':
bpo-30891: Fix importlib \_find_and_load() race condition (bpo-2646)
https://github.com/python/cpython/commit/4f9a446f3fb42f800e73cd9414dd1eccb3ca4fa7

**Comment by vstinner** [comment]
New changeset fe6e686c27ce3a3ecdf03803cff7e230dee5530d by Victor Stinner in branch '3.6':
bpo-30891: Fix importlib \_find_and_load() race condition (bpo-2646) (bpo-2651)
https://github.com/python/cpython/commit/fe6e686c27ce3a3ecdf03803cff7e230dee5530d

**Comment by vstinner** [comment]
Backporting the fix ot Python 3.5 doesn't seem trivial, 3.5 lacks many changes.

**Comment by vstinner** [comment]
New changeset e72b1359f81d1dd42bd8a5c5cc2b3928b74f8023 by Victor Stinner in branch 'master':
bpo-30891: Fix again importlib \_find_and_load() (bpo-2665)
https://github.com/python/cpython/commit/e72b1359f81d1dd42bd8a5c5cc2b3928b74f8023

**Comment by vstinner** [comment]
New changeset bb323b261d0f41ad6998d3a16c41b29b3bb8e982 by Victor Stinner in branch '3.6':
bpo-30891: Fix again importlib \_find_and_load() (bpo-2665) (bpo-2801)
https://github.com/python/cpython/commit/bb323b261d0f41ad6998d3a16c41b29b3bb8e982

**Comment by vstinner** [comment]
With Python 3.5.4rc1 released (3.5.4 will be the last 3.5 release accepting bug fixes), I'm not sure that it's still worth it to try to backport such changes to Python 3.5. The importlib is very important, any regression can be very important.

I'm not sure that backporting the unit test is interesting. If the test fails, we will be unable to fix it.

**Comment by vstinner** [comment]
Victor:
> I'm not sure that backporting the unit test is interesting. If the test fails, we will be unable to fix it.

Serhiy closed his PR:
https://github.com/python/cpython/pull/2645#event-1181495893

So now I close this issue.

**Comment by ambv** [comment]
If you're looking at this issue because it still happens to you, you are probably using zipimport. Stop using zipimport.

**Comment by vstinner** [comment]
Łukasz Langa: "If you're looking at this issue because it still happens to you, you are probably using zipimport. Stop using zipimport."

Hum, do you mean that zipimport also has an issue? Maybe open a new issue?
