### ISSUE TITLE
Python 3.6.1 String Literal Error Not Going to sys.stderr

### ISSUE THREAD

**Issue by 8e835e9e-8ca7-4ddf-9051-dfad77269a69** [python/cpython#75077]
BPO | [30894](https://bugs.python.org/issue30894)
--- | :---
Nosy | @stevendaprano
Files | <li>[Python361_bug.txt](https://bugs.python.org/file47001/Python361_bug.txt "Uploaded as text/plain at 2017-07-10.21:07:26 by George Gillan"): Text file with same contents as "Comment" above.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-11.01:16:40.616>
created_at = <Date 2017-07-10.21:07:26.622>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'Python 3.6.1 String Literal Error Not Going to sys.stderr'
updated_at = <Date 2017-07-11.01:16:40.591>
user = 'https://bugs.python.org/GeorgeGillan'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.01:16:40.591>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-11.01:16:40.616>
closer = 'steven.daprano'
components = ['Interpreter Core']
creation = <Date 2017-07-10.21:07:26.622>
creator = 'George Gillan'
dependencies = []
files = ['47001']
hgrepos = []
issue_num = 30894
keywords = []
message_count = 2.0
messages = ['298083', '298096']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'George Gillan']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30894'
versions = ['Python 3.6']
```

</p></details>

**Comment by 8e835e9e-8ca7-4ddf-9051-dfad77269a69** [comment]
Python 3.6.1 String Literal Error Not Going to sys.stderr

Using Windows 7 and Python 3.6.1. Attempting to redirect sys.stderr to a file. The application will be deployed via .pyw file instead of .py so the GUI application runs without a console window.

Is this fixable or 'as-is' due to the nature of the way the interpreter scans the code?

The following code worked as intended.

```py
#!/usr/bin/env python3.6 
errfile = 'test_err.txt'

import sys
errorlog = open(errfile, 'w')
sys.stderr = errorlog
```


1/0

The code above produced a file called test_err.txt with the following contents:

```pytb
Traceback (most recent call last):
  File "C:\Users\George\Coding\Python\test\mintest.py", line 8, in <module>
    1/0
ZeroDivisionError: division by zero
```



The following code did not work as intended.

```py
#!/usr/bin/env python3.6 
errfile = 'test_err.txt'

import sys
errorlog = open(errfile, 'w')
sys.stderr = errorlog

print("test)
```


The code above did not create the file test_err.txt with the error going to the console window instead.


Copy-paste from the Windows console.

The successful test (first) showed nothing in the console window; the error was logged to the file as noted above. The unsuccessful test (second) did not create the file, instead the error was sent to the console.

C:\\Users\\George\\Coding\\Python\\test\>mintest

C:\\Users\\George\\Coding\\Python\\test\>mintest
  File "C:\\Users\\George\\Coding\\Python\\test\\mintest.py", line 8
    print("test)
               ^
SyntaxError: EOL while scanning string literal

C:\\Users\\George\\Coding\\Python\\test\>

PS: This is my first bug/issue submission here. Please coach me as needed if I messed it up.

**Comment by stevendaprano** [comment]
Before Python runs your code, it compiles it to byte-code. A SyntaxError means that the code cannot be compiled, and so it does not run.

So the SyntaxError is raised \*before* any of the code runs, and standard error is not re-directed. This is expected behaviour, not a bug. You cannot catch compile-time errors at run-time.
