### ISSUE TITLE
IDLE: Add idle config parser unittest

### ISSUE THREAD

**Issue by 9da18a29-a07d-4828-a801-24cc911246de** [python/cpython#75082]
BPO | [30899](https://bugs.python.org/issue30899)
--- | :---
Nosy | @terryjreedy, @mlouielu, @csabella
PRs | <li>python/cpython#2662</li><li>python/cpython#2685</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-12.18:17:41.540>
created_at = <Date 2017-07-11.06:12:54.138>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Add idle config parser unittest'
updated_at = <Date 2017-07-12.18:42:42.282>
user = 'https://github.com/mlouielu'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-12.18:42:42.282>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-12.18:17:41.540>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-11.06:12:54.138>
creator = 'louielu'
dependencies = []
files = []
hgrepos = []
issue_num = 30899
keywords = []
message_count = 4.0
messages = ['298126', '298129', '298240', '298242']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'louielu', 'cheryl.sabella']
pr_nums = ['2662', '2685']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30899'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Add IdleConfParser and IdleUserConfParser unittest.

**Comment by terryjreedy** [comment]
I plan to review tomorrow afternoon.

**Comment by terryjreedy** [comment]
New changeset 50c9435c9b73b39fcf79cc3e58edc58bb943d0ed by terryjreedy (Louie Lu) in branch 'master':
bpo-30899: Add unittests, 100% coverage, for IDLE's two ConfigParser subclasses. (bpo-2662)
https://github.com/python/cpython/commit/50c9435c9b73b39fcf79cc3e58edc58bb943d0ed

**Comment by terryjreedy** [comment]
New changeset a9bf62cadf6ccd55b84a8d4f353529b02a537830 by terryjreedy in branch '3.6':
[3.6] bpo-30899: Add unittests, 100% coverage, for IDLE's two ConfigParser subclasses. (GH-2662) (bpo-2685)
https://github.com/python/cpython/commit/a9bf62cadf6ccd55b84a8d4f353529b02a537830
