### ISSUE TITLE
Add a is_mount() to pathlib

### ISSUE THREAD

**Issue by 2f3b0058-d572-4436-82d8-062775910f62** [python/cpython#75080]
BPO | [30897](https://bugs.python.org/issue30897)
--- | :---
Nosy | @ambv, @cooperlees
PRs | <li>python/cpython#2669</li><li>python/cpython#2980</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-01.22:52:11.483>
created_at = <Date 2017-07-11.02:35:10.747>
labels = ['3.7', 'type-feature', 'library']
title = 'Add a is_mount() to pathlib'
updated_at = <Date 2017-08-01.23:40:25.154>
user = 'https://github.com/cooperlees'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-01.23:40:25.154>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-01.22:52:11.483>
closer = 'cooperlees'
components = ['Library (Lib)']
creation = <Date 2017-07-11.02:35:10.747>
creator = 'cooperlees'
dependencies = []
files = []
hgrepos = []
issue_num = 30897
keywords = []
message_count = 3.0
messages = ['298104', '298110', '299639']
nosy_count = 2.0
nosy_names = ['lukasz.langa', 'cooperlees']
pr_nums = ['2669', '2980']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30897'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2f3b0058-d572-4436-82d8-062775910f62** [comment]
It would be nice to have pathlib.Path objects to have a ismount() function to return a bool if it is a POSIX mount point, similar to `os.path.ismount(path)`

**Comment by 2f3b0058-d572-4436-82d8-062775910f62** [comment]
Mocked up a concept PR. Will try teach myself how to test + see if I need to add Windows support etc.
https://github.com/cooperlees/cpython/commit/master

**Comment by ambv** [comment]
New changeset 173ff4a58a6b337fe8a0eb44f211f33f278d3d5f by Łukasz Langa (Cooper Lees) in branch 'master':
bpo-30897: Add is_mount() to pathlib.Path (bpo-2669)
https://github.com/python/cpython/commit/173ff4a58a6b337fe8a0eb44f211f33f278d3d5f
