### ISSUE TITLE
"503 HTTP ERROR" on attempt to access some points of python library documentation

### ISSUE THREAD

**Issue by 00dacf01-16a4-4440-953f-a6ef85d8e7e8** [python/cpython#75084]
BPO | [30901](https://bugs.python.org/issue30901)
--- | :---
Nosy | @brettcannon, @Mariatta, @mlouielu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-11.16:03:16.984>
created_at = <Date 2017-07-11.07:23:15.230>
labels = ['docs']
title = '"503 HTTP ERROR" on attempt to access some points of python library documentation'
updated_at = <Date 2017-07-11.16:17:25.269>
user = 'https://bugs.python.org/AlexanderKamyanskiy'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.16:17:25.269>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-11.16:03:16.984>
closer = 'brett.cannon'
components = ['Documentation']
creation = <Date 2017-07-11.07:23:15.230>
creator = 'Alexander Kamyanskiy'
dependencies = []
files = []
hgrepos = []
issue_num = 30901
keywords = []
message_count = 4.0
messages = ['298139', '298140', '298163', '298164']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'docs@python', 'Mariatta', 'louielu', 'Alexander Kamyanskiy']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30901'
versions = []
```

</p></details>

**Comment by 00dacf01-16a4-4440-953f-a6ef85d8e7e8** [comment]
I found that some points in Python Library reference documentation are not accessible, I got 503 http error.

The problem starts from this link and some points below the 29.14 point of doc list:

https://docs.python.org/3/library/fpectl.html

Also now I got 503:
https://docs.python.org/3/library/custominterp.html
https://docs.python.org/3/library/zipimport.html
https://docs.python.org/3/library/pkgutil.html
https://docs.python.org/3/library/symbol.html
https://docs.python.org/3/library/token.html
...


In fact I can't say for example that "31. Importing Modules" all inaccessible - I can't access 
31.3. modulefinder — Find modules used by a script
31.4. runpy — Locating and executing Python modules
31.5. importlib — The implementation of import

but cannot (I got 503 http response):
31.1. zipimport — Import modules from Zip archives
31.2. pkgutil — Package extension utility

P.S. I've tried to access documentation from absolutely another place and I'm sure it's not my local settings in browser or local firewall or smth like this.

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Can reproduce this problem in Chromium 59.0.3071, it seems affect every selectable version in docs.python.org. Also, [devguide](https://devguide.python.org) has some page down, too.

* [devguide](https://devguide.python.org): https://docs.python.org/devguide/triaging.html

**Comment by brettcannon** [comment]
Those pages all work for me. May have been transient.

**Comment by Mariatta** [comment]
There was partial outage. See post mortem report:
https://status.python.org/incidents/cc622spyl26l
