### ISSUE TITLE
IDLE: Fix configdialog should use wm_withdraw

### ISSUE THREAD

**Issue by 9da18a29-a07d-4828-a801-24cc911246de** [python/cpython#75083]
BPO | [30900](https://bugs.python.org/issue30900)
--- | :---
Nosy | @terryjreedy, @mlouielu, @csabella
PRs | <li>python/cpython#2664</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-11.07:50:23.446>
created_at = <Date 2017-07-11.07:05:27.549>
labels = ['expert-IDLE', '3.7', 'invalid']
title = 'IDLE: Fix configdialog should use wm_withdraw'
updated_at = <Date 2017-07-11.07:56:46.298>
user = 'https://github.com/mlouielu'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-11.07:56:46.298>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-11.07:50:23.446>
closer = 'louielu'
components = ['IDLE']
creation = <Date 2017-07-11.07:05:27.549>
creator = 'louielu'
dependencies = []
files = []
hgrepos = []
issue_num = 30900
keywords = []
message_count = 4.0
messages = ['298136', '298141', '298142', '298143']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'louielu', 'cheryl.sabella']
pr_nums = ['2664']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30900'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Introduce in bpo-30728, commit bac7d3363b099d, `self.wm_withdraw` has been changed into `self.withdraw`. This make bpo-30870 un-testable since it using `self.withdraw` will block out `event_generate`.

This issue revert `self.widthdraw` to `self.wm_withdraw`.

**Comment by terryjreedy** [comment]
Color me dubious ;-). The change was made because tkinter.\_\_init__, line 1990 has this line
    withdraw = wm_withdraw
There is a similar line for all of the around 30 wm_xyz functions. Prefixing the names of methods of class Wm is an unusual redundancy.  I cannot think of any sane way for tk to know which python synonym was used to call the Python wrapper.

What code using event_generate led you to this conclusion?

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Hmmm, I think it is a mistake of my test, it is something inside configdialog __init__ make unittest can't do event_generate, but not this one `self.withdraw`.

**Comment by terryjreedy** [comment]
I first beat my head against event_generate two or three years ago.  So I appreciate you taking a whack at it.  It is nice that Variable.set and invoke can be used for tests, but it would really be nice to have e_v work too.
