### ISSUE TITLE
Warning in _json.c on platforms where char is unsigned

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#75094]
BPO | [30911](https://bugs.python.org/issue30911)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @segevfiner
PRs | <li>python/cpython#2684</li><li>python/cpython#2690</li><li>python/cpython#2692</li><li>python/cpython#2693</li><li>python/cpython#2694</li><li>python/cpython#2729</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-07-13.08:26:39.203>
created_at = <Date 2017-07-12.17:28:06.269>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'Warning in _json.c on platforms where char is unsigned'
updated_at = <Date 2017-07-16.04:51:05.634>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-16.04:51:05.634>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-07-13.08:26:39.203>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-07-12.17:28:06.269>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30911
keywords = []
message_count = 15.0
messages = ['298239', '298262', '298263', '298271', '298272', '298273', '298274', '298275', '298276', '298277', '298278', '298389', '298390', '298392', '298420']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'Segev Finer']
pr_nums = ['2684', '2690', '2692', '2693', '2694', '2729']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30911'
versions = ['Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Shows in buildbots:

/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Modules/_json.c: In function ‘scanner_new’:
/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Modules/_json.c:1212:5: warning: comparison is always false due to limited range of data type [-Wtype-limits]
     if (s-\>strict \< 0)
     ^

This means that the error check doesn't work right.

**Comment by serhiy-storchaka** [comment]
New changeset 541bd28941af407f2329e6a540d6367e5625b115 by Serhiy Storchaka (Segev Finer) in branch 'master':
bpo-30911: Fix a crash in json on platforms with unsigned char (bpo-2684)
https://github.com/python/cpython/commit/541bd28941af407f2329e6a540d6367e5625b115

**Comment by serhiy-storchaka** [comment]
Thank you for noticing this warning Segev.

Actually the issue was more serious. This caused a crash when pass the strict argument that raises an exception when converted to bool. [PR 2690](https://github.com/python/cpython/pull/2690) adds test for this (actually it just ports recently added tests from simplejson).

**Comment by serhiy-storchaka** [comment]
New changeset d3aaa2f1496aae0809c9ec9623fa528d3a2c16c2 by Serhiy Storchaka in branch 'master':
bpo-30911: Add tests for bad boolean arguments for accelerated json (bpo-2690)
https://github.com/python/cpython/commit/d3aaa2f1496aae0809c9ec9623fa528d3a2c16c2

**Comment by vstinner** [comment]
> Actually the issue was more serious.

If the bug is serious, it deserves a NEWS entry, no? Moreover, the fix+test should be backported to 2.7, 3.5 and 3.6, no?

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Introduced in https://github.com/python/cpython/commit/ac5bbd43bc7b769c13ae0412cb28a3521f4d4ff1 which is only in 3.7 that means this wasn't ever released. I can send a PR with a NEWS entry if it still needs one?

**Comment by vstinner** [comment]
Oh ok. If it's a regression in the master branch, the code was never released with the bug. In this case, there is no need to document such fix. Thank you :-) I close the issue.

Thanks for the fix Sergev, thanks for the test Serhiy ;-)

**Comment by serhiy-storchaka** [comment]
New changeset 7d0a99582050ccac2e7126484d23072be342f317 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30911: Add tests for bad boolean arguments for accelerated json (GH-2690) (bpo-2692)
https://github.com/python/cpython/commit/7d0a99582050ccac2e7126484d23072be342f317

**Comment by serhiy-storchaka** [comment]
The tests are backported to other branches. This is a one of reasons why I created a separate PR for tests.

**Comment by serhiy-storchaka** [comment]
New changeset 2ec2c5f0b05efdcb7919c477591f1cb48bfb0aa9 by Serhiy Storchaka in branch '3.5':
[3.5] bpo-30911: Add tests for bad boolean arguments for accelerated json (GH-2690) (bpo-2693)
https://github.com/python/cpython/commit/2ec2c5f0b05efdcb7919c477591f1cb48bfb0aa9

**Comment by serhiy-storchaka** [comment]
New changeset b6dae2e40d14436d77d3f0bfe6a5b4ae73c83c6e by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30911: Add tests for bad boolean arguments for accelerated json (GH-2690) (bpo-2694)
https://github.com/python/cpython/commit/b6dae2e40d14436d77d3f0bfe6a5b4ae73c83c6e

**Comment by vstinner** [comment]
It is possible that the change introduced a reference leak. See for example:
http://buildbot.python.org/all/builders/AMD64%20Windows8.1%20Refleaks%203.5/builds/49

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Serhiy's change added tests to test_json, so you can say this unearthed ref leaks rather than introduced them. Probably needs a separate bpo issue and fix.

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Created http://bugs.python.org/issue30936

**Comment by serhiy-storchaka** [comment]
New changeset 3dbe11a1219d148e4a133449a86ac5d157e35d35 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-30911: Add tests for bad boolean arguments for accelerated json (GH-2690) (bpo-2729)
https://github.com/python/cpython/commit/3dbe11a1219d148e4a133449a86ac5d157e35d35
