### ISSUE TITLE
test_os.TestSendfile.test_keywords() leaks dangling threads

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75091]
BPO | [30908](https://bugs.python.org/issue30908)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#2680</li><li>python/cpython#2844</li><li>python/cpython#2845</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-26.00:12:46.988>
created_at = <Date 2017-07-12.13:26:16.654>
labels = ['3.7', 'tests', 'performance']
title = 'test_os.TestSendfile.test_keywords() leaks dangling threads'
updated_at = <Date 2017-07-26.00:12:46.943>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-26.00:12:46.943>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-26.00:12:46.988>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-12.13:26:16.654>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 30908
keywords = []
message_count = 8.0
messages = ['298217', '298219', '298220', '298221', '298224', '298971', '298983', '298984']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['2680', '2844', '2845']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30908'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The test_keywords() test of test_os.TestSendfile emits a warning about dangling threads:

haypo@selma$ ./python -m test --fail-env-changed -R 3:3 test_os -m test.test_os.TestSendfile.test_keywords
Run tests sequentially
0:00:00 load avg: 0.53 [1/1] test_os
Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
beginning 6 repetitions
123456
Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
.
test_os failed (env changed)

1 test altered the execution environment:
    test_os

Total duration: 21 sec
Tests result: ENV CHANGED

**Comment by serhiy-storchaka** [comment]
This isn't specific to test_keywords. Dangling threads occurred even if replace the test body with just "return". This is caused by setUp/tearDown or setUpClass/tearDownClass.

**Comment by vstinner** [comment]
> This isn't specific to test_keywords. Dangling threads occurred even if replace the test body with just "return". This is caused by setUp/tearDown or setUpClass/tearDownClass.

Right, see my PR bpo-2680. The general problem is that tearDownClass() seems to be called while the test case instance is still alive and so didn't clear its attributes. But I wrote a single line fix instead of trying to fix unittest or regrtest :-)

**Comment by vstinner** [comment]
New changeset d1cc037d1442cc35d1b194ec8e50901514360949 by Victor Stinner in branch 'master':
bpo-30908: Fix dangling thread in test_os.TestSendfile (bpo-2680)
https://github.com/python/cpython/commit/d1cc037d1442cc35d1b194ec8e50901514360949

**Comment by serhiy-storchaka** [comment]
The alternate solution is to remove all references to test instances before calling tearDownClass().

Interesting, that this warning is occurred only in the leak hunting mode. In normal cases test instances are removed from a testsuite, but regrtest hacks unittest and disables this in the leak hunting mode (see the line "unittest.BaseTestSuite.\_cleanup = False" in [Lib/test/libregrtest/setup.py](https://github.com/python/cpython/blob/main/Lib/test/libregrtest/setup.py)). See bpo-11798.

**Comment by vstinner** [comment]
Serhiy Storchaka: If you would like to enhance the unittest module, please open a new issue. I prefer to keep this one for the very specific test_os bug.

**Comment by vstinner** [comment]
New changeset 157b6ad677b7b330d30b2bb5ffbb2edac77b78cb by Victor Stinner in branch '3.5':
bpo-30908: Fix dangling thread in test_os.TestSendfile (bpo-2680) (bpo-2845)
https://github.com/python/cpython/commit/157b6ad677b7b330d30b2bb5ffbb2edac77b78cb

**Comment by vstinner** [comment]
New changeset bb33ccfc5a216eff753b10a8dc59ec0277f1e1fb by Victor Stinner in branch '3.6':
bpo-30908: Fix dangling thread in test_os.TestSendfile (bpo-2680) (bpo-2844)
https://github.com/python/cpython/commit/bb33ccfc5a216eff753b10a8dc59ec0277f1e1fb
