### ISSUE TITLE
python 3 git master fails to find libffi and build _ctypes on Mageia v6 x86-64

### ISSUE THREAD

**Issue by 59062004-5199-4539-afa5-e89c3bd56d93** [python/cpython#75095]
BPO | [30912](https://bugs.python.org/issue30912)
--- | :---
Nosy | @doko42, @zware, @shlomif
PRs | <li>python/cpython#2687</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-06.20:20:10.816>
created_at = <Date 2017-07-12.19:51:39.369>
labels = ['build', '3.7']
title = 'python 3 git master fails to find libffi and build _ctypes on Mageia v6 x86-64'
updated_at = <Date 2017-09-06.20:20:10.815>
user = 'https://github.com/shlomif'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.20:20:10.815>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-06.20:20:10.816>
closer = 'zach.ware'
components = ['Build']
creation = <Date 2017-07-12.19:51:39.369>
creator = 'shlomif'
dependencies = []
files = []
hgrepos = []
issue_num = 30912
keywords = []
message_count = 4.0
messages = ['298243', '301492', '301512', '301513']
nosy_count = 3.0
nosy_names = ['doko', 'zach.ware', 'shlomif']
pr_nums = ['2687']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue30912'
versions = ['Python 3.7']
```

</p></details>

**Comment by 59062004-5199-4539-afa5-e89c3bd56d93** [comment]
Running "make" in cpython git master on mageia linux v6 x86-64 gives me this problem with ffi:

\<\<\<\<\<\<\<\<
running build
running build_ext
Header file /usr/include/ffi.h does not define LIBFFI_H or ffi_wrapper_h
INFO: Could not locate ffi libs and/or headers

The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
atexit                pwd                   time


Failed to build these modules:
\_ctypes

running build_scripts
copying and adjusting /home/shlomif/Download/unpack/prog/python/cpython/Tools/scripts/pydoc3 -\> build/scripts-3.7
copying and adjusting /home/shlomif/Download/unpack/prog/python/cpython/Tools/scripts/idle3 -\> build/scripts-3.7
copying and adjusting /home/shlomif/Download/unpack/prog/python/cpython/Tools/scripts/2to3 -\> build/scripts-3.7
copying and adjusting /home/shlomif/Download/unpack/prog/python/cpython/Tools/scripts/pyvenv -\> build/scripts-3.7
changing mode of build/scripts-3.7/pydoc3 from 644 to 755
changing mode of build/scripts-3.7/idle3 from 644 to 755
changing mode of build/scripts-3.7/2to3 from 644 to 755
changing mode of build/scripts-3.7/pyvenv from 644 to 755
renaming build/scripts-3.7/pydoc3 to build/scripts-3.7/pydoc3.7
renaming build/scripts-3.7/idle3 to build/scripts-3.7/idle3.7
renaming build/scripts-3.7/2to3 to build/scripts-3.7/2to3-3.7
renaming build/scripts-3.7/pyvenv to build/scripts-3.7/pyvenv-3.7
>\>\>\>\>\>\>

\<\<\<\<\<\<
commit d1cc037d1442cc35d1b194ec8e50901514360949
Author: Victor Stinner \<victor.stinner@gmail.com\>
Date:   Wed Jul 12 16:05:43 2017 +0200

    bpo-30908: Fix dangling thread in test_os.TestSendfile (bpo-2680)

    tearDown() now clears explicitly the self.server variable to make
    sure that the thread is completely cleared when tearDownClass()
    checks if all threads have been cleaned up.

    Fix the following warning:

    $ ./python -m test --fail-env-changed -m test.test_os.TestSendfile.test_keywords -R 3:1 test_os
    (...)
    Warning -- threading_cleanup() failed to cleanup 0 threads after 3 sec (count: 0, dangling: 2)
    (...)
    Tests result: ENV CHANGED
>\>\>\>\>

The problem is that my /usr/include/ffi.h looks like this:

```c
<<<<
#define _MULTIARCH_HEADER ffi.h
#include <multiarch-dispatch.h>
>>>>
```

**Comment by zware** [comment]
doko, have you seen/have an opinion on python/cpython#46939?

**Comment by zware** [comment]
New changeset 6d51b876121e472d4372496d609a26d7e3081c51 by Zachary Ware (Shlomi Fish) in branch 'master':
bpo-30912: Don't check the content of ffi.h (GH-2687)
https://github.com/python/cpython/commit/6d51b876121e472d4372496d609a26d7e3081c51

**Comment by zware** [comment]
Thanks for the patch!
