### ISSUE TITLE
Sequence Matcher from diff lib is not implementing longest common substring problem correctly

### ISSUE THREAD

**Issue by 480e084d-53e2-4ed8-901e-a971d90e093c** [python/cpython#75103]
BPO | [30920](https://bugs.python.org/issue30920)
--- | :---
Nosy | @tim-one
Files | <li>[script.py](https://bugs.python.org/file47010/script.py "Uploaded as text/plain at 2017-07-13.15:05:54 by Syam Mohan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-14.20:12:32.181>
created_at = <Date 2017-07-13.15:05:55.311>
labels = ['invalid', 'type-bug', 'library']
title = 'Sequence Matcher from diff lib is not implementing longest common substring problem correctly'
updated_at = <Date 2017-07-14.20:12:32.179>
user = 'https://bugs.python.org/SyamMohan'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-14.20:12:32.179>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-14.20:12:32.181>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-07-13.15:05:55.311>
creator = 'Syam Mohan'
dependencies = []
files = ['47010']
hgrepos = []
issue_num = 30920
keywords = []
message_count = 2.0
messages = ['298287', '298295']
nosy_count = 2.0
nosy_names = ['tim.peters', 'Syam Mohan']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30920'
versions = ['Python 2.7']
```

</p></details>

**Comment by 480e084d-53e2-4ed8-901e-a971d90e093c** [comment]
Was seeing this lib from difflib import SequenceMatcher not returning the biggest common substring always..

try the example from attachment..

it is returning wrong value, not the biggest substring

**Comment by tim-one** [comment]
This is an unfortunate consequence of the default "autojunk" feature.  You can turn that off by passing `autojunk=False`, like so:

```py
match = SequenceMatcher(None, string1, string2, autojunk=False)...
                                              ^^^^^^^^^^^^^^^^
```


Then it returns a match of size 534.
