### ISSUE TITLE
Unable to launch IDLE in windows 7

### ISSUE THREAD

**Issue by e89b2bce-1090-458e-8df2-4cdeea42f164** [python/cpython#75101]
BPO | [30918](https://bugs.python.org/issue30918)
--- | :---
Nosy | @terryjreedy, @trencyclopedia
Superseder | <li>bpo-8231: Unable to run IDLE without write-access to home directory</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-09-10.21:38:34.394>
created_at = <Date 2017-07-13.13:49:20.345>
labels = ['expert-IDLE', 'type-bug']
title = 'Unable to launch IDLE in windows 7'
updated_at = <Date 2017-09-10.21:38:34.393>
user = 'https://github.com/trencyclopedia'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-10.21:38:34.393>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-09-10.21:38:34.394>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-13.13:49:20.345>
creator = 'trencyclo'
dependencies = []
files = []
hgrepos = []
issue_num = 30918
keywords = []
message_count = 4.0
messages = ['298284', '298373', '301832', '301834']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'trencyclo']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '8231'
type = 'behavior'
url = 'https://bugs.python.org/issue30918'
versions = ['Python 3.5']
```

</p></details>

**Comment by e89b2bce-1090-458e-8df2-4cdeea42f164** [comment]
"unable to create user config directory   Z:\\.idlerc   check path and permisssion"

It through out this error, when I try to launch the IDLE not as an adminnistrator acount. There is an networed disk memory Z: on my computer

this error is caused by configHandler.py script in the [Lib/idlelib](https://github.com/python/cpython/blob/main/Lib/idlelib) directory. Here is a solution: https://www.experts-exchange.com/questions/24006687/Invalid-Python-config-directory.html

**Comment by terryjreedy** [comment]
This is a duplicate of bpo-8231.  But before I close this, when you do 
> set
in the console (command prompt), what HOME* variables are set and is USERPROFILE?

In python, what does 

```pycon
>>> from os.path import expanduser
>>> expanduser('~')
show?
```

**Comment by e89b2bce-1090-458e-8df2-4cdeea42f164** [comment]
Hi Terry,
Sorry,  I missed your resply because it was buried in my trash email.
Here are the configuration in my PC:
HOMEDRIVE=Z:
HOMEPATH=\\
HOMESHARE=\\\\nt3.imec.be\\zhai65
LOCALAPPDATA=C:\\Users\\zhai65\\AppData\\Local

```py
USERPROFILE=C:\Users\zhai65
```


```pycon
In python
>>> expanduser('~')
'C:\\Users\\zhai65'
```


I partly bypassed the bug by following the instructions shown in my
previous link.

\*Best Regards！*
\*--*

\*Eric Donghui \*\*Zhai \*
* PhD Candidate\*
\*IMEC & KU Leuven\*

\*Mobile: +32-0489 676629 Email: trencyclopedia@gmail.com \<zhai.dh@163.com\>
 \*
\*Address: \*\*IMEC, Kapeldreef 75, Leuven, Belgiium\*

**Comment by terryjreedy** [comment]
Thanks for the information.  I hope to get to this before 3.6.3.
