### ISSUE TITLE
Identity comparison ("is") fails for floats in Python3 but works in Python2

### ISSUE THREAD

**Issue by 3b8d22d7-a74a-4e4d-9598-f78aa6008f26** [python/cpython#75115]
BPO | [30932](https://bugs.python.org/issue30932)
--- | :---
Nosy | @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-14.17:40:38.500>
created_at = <Date 2017-07-14.17:33:35.526>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'Identity comparison ("is") fails for floats in Python3 but works in Python2'
updated_at = <Date 2017-07-14.17:40:38.481>
user = 'https://bugs.python.org/LloydVonHans'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-14.17:40:38.481>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-14.17:40:38.500>
closer = 'steven.daprano'
components = ['Interpreter Core']
creation = <Date 2017-07-14.17:33:35.526>
creator = 'LloydVonHans'
dependencies = []
files = []
hgrepos = []
issue_num = 30932
keywords = []
message_count = 2.0
messages = ['298363', '298364']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'LloydVonHans']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30932'
versions = ['Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3b8d22d7-a74a-4e4d-9598-f78aa6008f26** [comment]
The identity comparison fails in floats in Python3.

```pycon
>>> -7.3 is -7.3
False
```


While in Python2

```pycon
>>> -7.3 is -7.3
True
```

**Comment by stevendaprano** [comment]
This is not a bug. Whether Python allocates one, or two, float objects for a particular floating point value is dependent on the implementation and not a language guarantee. The language does not promise that two floats with the value 7.3 will be the same object, only that they are equal.

In Python 3.5 on Linux, I can see:

py\> 7.3 is 7.3
True
py\> x = 7.3
py\> y = 7.3
py\> x is y
False


*but your results may be different*. There is no language promise here, except that `x is x` must be true.
