### ISSUE TITLE
AttributeErrors after import in multithreaded environment

### ISSUE THREAD

**Issue by f854bb0c-5b64-46cd-95a9-fd152a47d024** [python/cpython#75112]
BPO | [30929](https://bugs.python.org/issue30929)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @larryhastings, @ericsnowcurrently, @serhiy-storchaka
Files | <li>[mod.zip](https://bugs.python.org/file47014/mod.zip "Uploaded as application/zip at 2017-07-14.12:05:08 by boytsovea"): example which demonstrates the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-15.11:28:57.964>
created_at = <Date 2017-07-14.12:05:09.990>
labels = ['interpreter-core', 'type-bug']
title = 'AttributeErrors after import in multithreaded environment'
updated_at = <Date 2017-07-15.11:28:57.962>
user = 'https://bugs.python.org/boytsovea'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-15.11:28:57.962>
actor = 'larry'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-15.11:28:57.964>
closer = 'larry'
components = ['Interpreter Core']
creation = <Date 2017-07-14.12:05:09.990>
creator = 'boytsovea'
dependencies = []
files = ['47014']
hgrepos = []
issue_num = 30929
keywords = []
message_count = 4.0
messages = ['298349', '298387', '298393', '298394']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'larry', 'eric.snow', 'serhiy.storchaka', 'boytsovea']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30929'
versions = ['Python 3.4']
```

</p></details>

**Comment by f854bb0c-5b64-46cd-95a9-fd152a47d024** [comment]
Hello everybody!

We are using Python 3.4 running at CentOS 7 x64 and experiencing some problems with simulatenous import of modules from different threads of execution.
The attached archive contains simple example, which demonstrates the issue. 

There is python package called "mod". It contains two sub-packages called "foo" and "bar". They, in turn, contain modules "foo" and "bar" respectively. 

Another package called "threader" contains function "run_threads()", which runs two threads of execution (using threading) and joins them.
First thread of execution imports "mod.foo.foo" from "mod" and calls its function. The second thread does the same, but for module "mod.bar.bar".

Finally, there is module "test.py" which calls "threader.run_threads()" and when it returns, tries to import "mod.foo.foo" and call its function.

To reproduce the bug you need to run "test.py" for several times.

Most of the launches complete successfully. But sometimes we encounter AttributeError during import like that:

'module' object has no attribute 'foo'


We've done some investigation in order to clarify this behaviour and added import hook (you can see it in test.py), which logs all import that take place. 
When the launch completes successfully, the order of imports looks like that:

```sh
$ python3 test.py 
[py][import] threader
[py][import] threading
[py][import] time
[py][import] traceback
[py][import] linecache
[py][import] tokenize
[py][import] collections
[py][import] _collections
[py][import] operator
[py][import] _operator
[py][import] keyword
[py][import] heapq
[py][import] itertools
[py][import] _heapq
[py][import] reprlib
[py][import] re
[py][import] sre_compile
[py][import] _sre
[py][import] sre_parse
[py][import] sre_constants
[py][import] _locale
[py][import] copyreg
[py][import] token
[py][import] mod
[py][import] mod.foo
[py][import] mod.bar
[py][import] mod.foo.foo
[py][import] mod.bar.bar
print from foo
print from bar
```


When the issue arises we see the following:

```sh
$ python3 test.py 
[py][import] threader
[py][import] threading
[py][import] time
[py][import] traceback
[py][import] linecache
[py][import] tokenize
[py][import] collections
[py][import] _collections
[py][import] operator
[py][import] _operator
[py][import] keyword
[py][import] heapq
[py][import] itertools
[py][import] _heapq
[py][import] reprlib
[py][import] re
[py][import] sre_compile
[py][import] _sre
[py][import] sre_parse
[py][import] sre_constants
[py][import] _locale
[py][import] copyreg
[py][import] token
[py][import] mod
[py][import] mod.foo
[py][import] mod
[py][import] mod.bar
[py][import] mod.foo.foo
[py][import] mod.bar.bar
thread of foo: import error 'module' object has no attribute 'foo'
print from bar
```



That is when the issue arises there are two imports of package "mod".

And the most confusing thing about this scenario is that even after completion of "run_threads()" interpreter can not import "mod.foo.foo" and gives the same AttributeErrors in for-loop inside test.py.

**Comment by serhiy-storchaka** [comment]
This may be a duplicate of bpo-30891.

But 3.4 is in security fixes only mode. And this issue doesn't look like a security issue.

**Comment by f854bb0c-5b64-46cd-95a9-fd152a47d024** [comment]
The same behaviour is reprodusible at ubuntu 16.04 with python 3.5.2. And a colleague of mine said that he was able to reproduce the issue with python 3.6.

**Comment by larryhastings** [comment]
I'm closing this.  It isn't a security issue, so it's not applicable for 3.4.  3.5 is about to close for bugfixes too, so you'd have to work very... quickly.

If this applies to 3.6, figure out whether or not it's a duplicate of Issue bpo-30891.  If it isn't, please create a new issue, and only flag 3.6+.
