### ISSUE TITLE
loop.create_server does not detect if the interface is IPv6 enabled

### ISSUE THREAD

**Issue by 8d544c45-9066-4aaf-99c6-0e7697f2caba** [python/cpython#75128]
BPO | [30945](https://bugs.python.org/issue30945)
--- | :---
Nosy | @pitrou, @1st1, @asottile, @jnwatson, @cecton
PRs | <li>python/cpython#7207</li>
Files | <li>[test_ipv6.py](https://bugs.python.org/file47019/test_ipv6.py "Uploaded as text/plain at 2017-07-17.10:04:34 by @cecton"): Example file to reproduce the issue</li><li>[eaddrnotavail_asyncio.patch](https://bugs.python.org/file47026/eaddrnotavail_asyncio.patch "Uploaded as text/plain at 2017-07-20.11:34:42 by @pitrou")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-17.10:04:34.577>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'loop.create_server does not detect if the interface is IPv6 enabled'
updated_at = <Date 2018-10-19.21:14:34.454>
user = 'https://github.com/cecton'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-19.21:14:34.454>
actor = 'jnwatson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-07-17.10:04:34.577>
creator = 'cecton'
dependencies = []
files = ['47019', '47026']
hgrepos = []
issue_num = 30945
keywords = ['patch']
message_count = 12.0
messages = ['298474', '298683', '298684', '298714', '298716', '298718', '311915', '311916', '311917', '311942', '317895', '318045']
nosy_count = 5.0
nosy_names = ['pitrou', 'yselivanov', 'Anthony Sottile', 'jnwatson', 'cecton']
pr_nums = ['7207']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30945'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-114420
* gh-114441
* gh-114442

**Comment by 8d544c45-9066-4aaf-99c6-0e7697f2caba** [comment]
The IPv6 detection in asyncio.base_events.create_server only detect if IPv6 is available instead of checking if the interface can actually support it.

I noticed that by using Python in a Docker container (example code to reproduce in attachment):


docker run -it --rm -v /tmp/test_ipv6.py:/src/test_ipv6.py python:3.6 python /src/test_ipv6.py


Will result in:


```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1043, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/src/test_ipv6.py", line 11, in <module>
    server = loop.run_until_complete(server_creation)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1047, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('::1', 27015, 0, 0): cannot assign requested address
```



By default Docker containers have only IPv4 enabled:


1: lo: \<LOOPBACK,UP,LOWER_UP\> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
38: eth0@if39: \<BROADCAST,MULTICAST,UP,LOWER_UP\> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.2/16 scope global eth0
       valid_lft forever preferred_lft forever


I believe this detection mechanism should rely on the interface requested. I found this on the web for Python 2 that manage to get the info per interface: https://pastebin.com/VEnhF1Ht but it's using an external library.

However if you change the hostname to 127.0.0.1 it works normally.

**Comment by pitrou** [comment]
Better than trying to detect IPv6 compatibility beforehand would probably to recognize the error and simply ignore it.

Note: errno 99 is EADDRNOTAVAIL.

Something like this could work (untested):

```diff
diff --git a/Lib/asyncio/base_events.py b/Lib/asyncio/base_events.py
index 33b8f48..413161a 100644
--- a/Lib/asyncio/base_events.py
+++ b/Lib/asyncio/base_events.py
@@ -1038,6 +1038,11 @@ class BaseEventLoop(events.AbstractEventLoop):
                     try:
                         sock.bind(sa)
                     except OSError as err:
+                        if err.errno == errno.EADDRNOTAVAIL:
+                            # See bpo-30945
+                            sockets.pop()
+                            sock.close()
+                            continue
                         raise OSError(err.errno, 'error while attempting '
                                       'to bind on address %r: %s'
                                       % (sa, err.strerror.lower())) from None
```

**Comment by 1st1** [comment]
> Better than trying to detect IPv6 compatibility beforehand would probably to recognize the error and simply ignore it.


+1

**Comment by pitrou** [comment]
Cécile, could you try the following patch?  I have no easy way to test here.

**Comment by 8d544c45-9066-4aaf-99c6-0e7697f2caba** [comment]
Sure! It seems to work, the process returns an exit code of 0 and I see no traceback but the message is still displayed in the terminal.

(Also I did something weird because your patch applies on branch master and I ran it with Python 3.6... I suppose it shouldn't be a problem)


```pytb
[0] [11:54:13] /tmp > d run -it --rm -v /tmp:/tmp:ro -v ~/repos/cpython/Lib/asyncio:/usr/local/lib/python3.6/asyncio:ro python:3.6 python /tmp/test_ipv6.py
error while attempting to bind on address ('::1', 27015, 0, 0): cannot assign requested address
[0] [11:54:19] /tmp > d run -it --rm -v /tmp:/tmp:ro python:3.6 python /tmp/test_ipv6.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1043, in create_server
    sock.bind(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/test_ipv6.py", line 11, in <module>
    server = loop.run_until_complete(server_creation)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 1047, in create_server
    % (sa, err.strerror.lower()))
OSError: [Errno 99] error while attempting to bind on address ('::1', 27015, 0, 0): cannot assign requested address
[1] [11:54:52] /tmp >
```

**Comment by pitrou** [comment]
Cécile, thank you.  The reason the message is still displayed is that I turned the error into a warning (in other words, it is expected).

**Comment by serhiy-storchaka** [comment]
Thank you for your patch Antoine. I am surprised that it was not merged at its time. It fixes a constant failure on some buildbots. Buildbot failure could perhaps be fixed by changing the configuration (I think that I encountered such errors on different buildbots in the past), but it is better to fix it in the core.
