### ISSUE TITLE
Sphinx 1.6.3 deprecation warning for sphinx.util.compat.Directive in docs builds

### ISSUE THREAD

**Issue by ned-deily** [python/cpython#75122]
BPO | [30939](https://bugs.python.org/issue30939)
--- | :---
Nosy | @brettcannon, @larryhastings, @ned-deily
PRs | <li>python/cpython#2721</li><li>python/cpython#2719</li><li>python/cpython#2722</li><li>python/cpython#2723</li><li>python/cpython#2724</li><li>python/cpython#2725</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.09:02:21.134>
created_at = <Date 2017-07-15.19:19:13.621>
labels = ['3.7', 'docs']
title = 'Sphinx 1.6.3 deprecation warning for sphinx.util.compat.Directive in docs builds'
updated_at = <Date 2019-05-10.18:16:15.459>
user = 'https://github.com/ned-deily'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-10.18:16:15.459>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-24.09:02:21.134>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-07-15.19:19:13.621>
creator = 'ned.deily'
dependencies = []
files = []
hgrepos = []
issue_num = 30939
keywords = []
message_count = 8.0
messages = ['298401', '298402', '298404', '298405', '298409', '298451', '298461', '298864']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'larry', 'ned.deily', 'docs@python']
pr_nums = ['2721', '2719', '2722', '2723', '2724', '2725']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30939'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ned-deily** [comment]
[..]/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)

The solution is to import Directive directly from docutils.  PR to follow for master, needs to be cherrypicked to all maintenance branches and, ideally, all current security-only branches.

**Comment by ned-deily** [comment]
New changeset 50f58163a69abe2f35e91044d1df165ee7bdbb42 by Ned Deily in branch 'master':
bpo-30939: Avoid Sphinx deprecation warning in docs build. (bpo-2721)
https://github.com/python/cpython/commit/50f58163a69abe2f35e91044d1df165ee7bdbb42

**Comment by ned-deily** [comment]
New changeset bbd0f423d2a19c6a4a9cda6914fc60b87e17250b by Ned Deily in branch '3.6':
bpo-30939: Avoid Sphinx deprecation warning in docs build. (bpo-2721) (bpo-2722)
https://github.com/python/cpython/commit/bbd0f423d2a19c6a4a9cda6914fc60b87e17250b

**Comment by ned-deily** [comment]
New changeset ada3f31365d0634d0cd8eeacfacd98291e34a8cc by Ned Deily in branch '3.5':
bpo-30939: Avoid Sphinx deprecation warning in docs build. (bpo-2721) (bpo-2723)
https://github.com/python/cpython/commit/ada3f31365d0634d0cd8eeacfacd98291e34a8cc

**Comment by ned-deily** [comment]
New changeset 64a9f3d961084819335ea011063eb8cb41733882 by Ned Deily in branch '2.7':
bpo-30939: Avoid Sphinx deprecation warning in docs build. (bpo-2721) (bpo-2725)
https://github.com/python/cpython/commit/64a9f3d961084819335ea011063eb8cb41733882

**Comment by brettcannon** [comment]
I wonder if we should pin sphinx directly instead of the approximate pin we
have now to prevent this sort of thing in the future? I had figured they
wouldn't introduce a new warning in a bugfix release but I was wrong in
that assumption.

**Comment by ned-deily** [comment]
> I wonder if we should pin sphinx directly instead of the approximate pin we
> have now to prevent this sort of thing in the future?

Perhaps. OTOH, we will find out about Sphinx incompatibilities pretty quickly that way, rather than having doc builds potentially silently fail or only finding out about the problem at release time.

**Comment by larryhastings** [comment]
New changeset 3b3a5a5b70dc468dcfacb17a3d6b342820b480ff by larryhastings (Ned Deily) in branch '3.4':
bpo-30939: Avoid Sphinx deprecation warning in docs build. (bpo-2721) (bpo-2724)
https://github.com/python/cpython/commit/3b3a5a5b70dc468dcfacb17a3d6b342820b480ff
