### ISSUE TITLE
Missing line in example program

### ISSUE THREAD

**Issue by bae6c309-76ef-4076-aef9-0fafeae136ec** [python/cpython#75124]
BPO | [30941](https://bugs.python.org/issue30941)
--- | :---
Nosy | @bitdancer, @lucbouge

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-16.19:33:16.579>
created_at = <Date 2017-07-16.18:24:33.397>
labels = ['type-bug', 'invalid', 'docs']
title = 'Missing line in example program'
updated_at = <Date 2017-07-16.19:33:16.577>
user = 'https://github.com/lucbouge'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-16.19:33:16.577>
actor = 'r.david.murray'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-16.19:33:16.579>
closer = 'r.david.murray'
components = ['Documentation']
creation = <Date 2017-07-16.18:24:33.397>
creator = 'lucbouge'
dependencies = []
files = []
hgrepos = []
issue_num = 30941
keywords = []
message_count = 2.0
messages = ['298445', '298447']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'docs@python', 'lucbouge']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30941'
versions = ['Python 3.6']
```

</p></details>

**Comment by bae6c309-76ef-4076-aef9-0fafeae136ec** [comment]
On page \<https://docs.python.org/3.6/_sources/library/stdtypes.txt\>, the following program is listed.

It raises a syntactic error.

An empty line is missing after "...     n += val" to close the loop body. 

```pycon
   >>> # iteration
   >>> n = 0
   >>> for val in values:
   ...     n += val
   >>> print(n)
   504
```

**Comment by bitdancer** [comment]
This is the standard way that we write examples.  Sprinkling in extra blank lines everywhere would make the examples less readable.  One you've learned how the command interpreter works, the examples are clear, so you each beginner only has to learn this once (and I believe it is explained in the tutorial, though I haven't checked).
