### ISSUE TITLE
Implement lwalk(levelwalk) function on os.py

### ISSUE THREAD

**Issue by 9841b8ca-54c2-496c-9e81-48deab1900d9** [python/cpython#75125]
BPO | [30942](https://bugs.python.org/issue30942)
--- | :---
Nosy | @bitdancer, @andrekorol
Superseder | <li>bpo-26781: os.walk max_depth</li>
Files | <li>[os.py](https://bugs.python.org/file47017/os.py "Uploaded as text/plain at 2017-07-17.05:26:38 by @andrekorol"): os.py with lwalk function implemented</li><li>[os.py](https://bugs.python.org/file47018/os.py "Uploaded as text/plain at 2017-07-17.05:40:33 by @andrekorol"): os.py with lwalk function implemented</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-17.12:40:03.414>
created_at = <Date 2017-07-17.05:26:44.573>
labels = ['3.7', 'type-feature', 'library']
title = 'Implement lwalk(levelwalk) function on os.py'
updated_at = <Date 2017-07-17.12:40:03.413>
user = 'https://github.com/andrekorol'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-17.12:40:03.413>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-17.12:40:03.414>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-07-17.05:26:44.573>
creator = 'andrekorol'
dependencies = []
files = ['47017', '47018']
hgrepos = ['370']
issue_num = 30942
keywords = []
message_count = 4.0
messages = ['298458', '298459', '298460', '298492']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'andrekorol']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '26781'
type = 'enhancement'
url = 'https://bugs.python.org/issue30942'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9841b8ca-54c2-496c-9e81-48deab1900d9** [comment]
I forked cpython and implemented an lwalk function on os.py. The lwalk funtion behaves exactly like walk(), except that it recurses only to a certain level of depth that can be selected by the user. More information on the lwalk function can be found on "os.py" in my cpython fork. It worked fine when I tested the funtion in a local virtual environment, but when I installed Python 3.7 with my lwalk function implemented in os.py I get an error when I try to test it in my recent Python installation: "TypeError: 'NoneType' object is not iterable".
I'd like to know where else I need to add info about my lwalk function so it can be correctly used in a fresh Python installation and so than I can send a Pull Request.

**Comment by 9841b8ca-54c2-496c-9e81-48deab1900d9** [comment]
I forked cpython and implemented an lwalk function on os.py. The lwalk funtion behaves exactly like walk(), except that it recurses only to a certain level of depth that can be selected by the user. More information on the lwalk function can be found on "os.py" in my cpython fork.
I'd like to know what else I need to do in order to send a Pull Request.

**Comment by 9841b8ca-54c2-496c-9e81-48deab1900d9** [comment]
UPDATE: I already fixed the cause of the TypeError I mentioned earlier.

**Comment by bitdancer** [comment]
Thanks for being interested in improving Python.  Please join the discussion in the existing bpo-26781, which proposes a max_depth parameter for walk.
