### ISSUE TITLE
Docs for __subclasses__(): Add hint that Python imports are lazy

### ISSUE THREAD

**Issue by dff66fbe-9795-4708-85c5-19bd22fd0f69** [python/cpython#75131]
BPO | [30948](https://bugs.python.org/issue30948)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-17.15:17:57.978>
created_at = <Date 2017-07-17.14:19:59.603>
labels = []
title = 'Docs for __subclasses__(): Add hint that Python imports are lazy'
updated_at = <Date 2017-07-17.15:17:57.976>
user = 'https://bugs.python.org/guettli'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-17.15:17:57.976>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-17.15:17:57.978>
closer = 'r.david.murray'
components = []
creation = <Date 2017-07-17.14:19:59.603>
creator = 'guettli'
dependencies = []
files = []
hgrepos = []
issue_num = 30948
keywords = []
message_count = 2.0
messages = ['298527', '298536']
nosy_count = 2.0
nosy_names = ['guettli', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30948'
versions = []
```

</p></details>

**Comment by dff66fbe-9795-4708-85c5-19bd22fd0f69** [comment]
AFAIK cls.\_\_subclasses__() only returns the classes which the interpreter has already loaded.

This means there can be more subclasses in modules where not imported by the current interpreter up to now.

https://docs.python.org/3.7/library/stdtypes.html?highlight=subclasses#class.\_\_subclasses__

I think it would be nice to add a hint to the docs that python imports are lazy.

What do you think?

**Comment by bitdancer** [comment]
Thanks for the suggestion, but I don't think so.

Python imports are not lazy.  They are ordered.  Python is an \*interpreted* language, so \_\_subclasses__ is only going to hold those subclasses whose class definitions have been executed. This is fundamental to how the language works, and does not warrant a special note here.  Note that the entry already includes something that should give a strong hint about this even if you hadn't previously thought about it: the statement that it only includes subclasses that are "still alive".  This implies they aren't in the list until they become alive.
