### ISSUE TITLE
Fatal python error when jumping into except clause

### ISSUE THREAD

**Issue by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [python/cpython#75136]
BPO | [30953](https://bugs.python.org/issue30953)
--- | :---
Nosy | @xdegaye, @serhiy-storchaka, @pppery, @mlouielu, @iritkatriel
PRs | <li>python/cpython#6196</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-27.21:42:08.539>
created_at = <Date 2017-07-17.21:24:58.022>
labels = ['interpreter-core', '3.8', 'library', 'type-crash']
title = 'Fatal python error when jumping into except clause'
updated_at = <Date 2020-09-27.21:42:08.539>
user = 'https://github.com/pppery'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-27.21:42:08.539>
actor = 'ppperry'
assignee = 'none'
closed = True
closed_date = <Date 2020-09-27.21:42:08.539>
closer = 'ppperry'
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2017-07-17.21:24:58.022>
creator = 'ppperry'
dependencies = []
files = []
hgrepos = []
issue_num = 30953
keywords = ['patch']
message_count = 7.0
messages = ['298556', '298572', '298817', '314272', '314291', '314307', '377510']
nosy_count = 5.0
nosy_names = ['xdegaye', 'serhiy.storchaka', 'ppperry', 'louielu', 'iritkatriel']
pr_nums = ['6196']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30953'
versions = ['Python 3.8']
```

</p></details>

**Comment by d5fdb119-613c-451d-b1c0-d3c0c3358f9c** [comment]
trying to execute the following code:
import sys
def trace(frame, event, arg):
    if event == "line" and frame.f_lineno \> 12:
        frame.f_lineno = 12
        return None
    return trace
sys.settrace(trace)
def error():
    try:
        pass
    except:
        pass
    pass
    pass
error()
Produces a fatal error:
Fatal Python error: XXX block stack underflow

Current thread 0x00000af4 (most recent call first):
  File "jumpintoexception.py", line 12 in error
  File "jumpintoexception.py", line 15 in \<module\>

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
You will need to use `dis` to see what actually done by bytecode.


```sh
$ ./python -m dis tests.py
```


Disassembly of \<code object error at 0x7fbb69da5340, file "tests.py", line 8\>:
  9           0 SETUP_EXCEPT             4 (to 6)

 10           2 POP_BLOCK
              4 JUMP_FORWARD            12 (to 18)

 11     \>\>    6 POP_TOP
              8 POP_TOP
             10 POP_TOP

 12          12 POP_EXCEPT
             14 JUMP_FORWARD             2 (to 18)
             16 END_FINALLY

 14     \>\>   18 LOAD_CONST               0 (None)
             20 RETURN_VALUE


this is the actual bytecode in `error()`.

When the eval loop hit the line 9, it will perform bytecode `SETUP_EXCEPT`, thus push a block into the blockstack. 
Your code in trace wrote that `and frame.f_lineno > 12`, thus it will run line 12 and perform POP_EXCEPT to pop out the blockstack.

then goto line 13, catch by trace if statement, f_lineno changed to 12, and perform `POP_EXCEPT` again, there isn't any block inside the blockstack, thus it will get a "XXX block stack underflow".

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
bpo-17288 is related.
