### ISSUE TITLE
Documentation error in inspect module

### ISSUE THREAD

**Issue by b628143a-fe57-4479-8040-36a515adb0d3** [python/cpython#75134]
BPO | [30951](https://bugs.python.org/issue30951)
--- | :---
Nosy | @masklinn, @ambv, @serhiy-storchaka, @marco-buttu, @laike9m, @jalexvig, @pablogsal, @miss-islington, @utkarsh2102
PRs | <li>python/cpython#2742</li><li>python/cpython#2743</li><li>python/cpython#10668</li><li>python/cpython#28543</li><li>python/cpython#28544</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-24.10:39:41.795>
created_at = <Date 2017-07-17.17:29:35.640>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = 'Documentation error in inspect module'
updated_at = <Date 2021-10-04.19:18:42.585>
user = 'https://github.com/jalexvig'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-04.19:18:42.585>
actor = 'pablogsal'
assignee = 'docs@python'
closed = True
closed_date = <Date 2021-09-24.10:39:41.795>
closer = 'lukasz.langa'
components = ['Documentation']
creation = <Date 2017-07-17.17:29:35.640>
creator = 'jalexvig'
dependencies = []
files = []
hgrepos = []
issue_num = 30951
keywords = ['patch']
message_count = 10.0
messages = ['298545', '298644', '330300', '334563', '372358', '402547', '402548', '402549', '402550', '403159']
nosy_count = 10.0
nosy_names = ['xmorel', 'docs@python', 'lukasz.langa', 'serhiy.storchaka', 'marco.buttu', 'laike9m', 'jalexvig', 'pablogsal', 'miss-islington', 'utkarsh2102']
pr_nums = ['2742', '2743', '10668', '28543', '28544']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30951'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by b628143a-fe57-4479-8040-36a515adb0d3** [comment]
The documentation for co_names in the inspect module is:

"tuple of names of local variables"

Local variable names are however in co_varnames while co_names contains global variable names. This description should read:

"tuple of names of global variables"

Relevant StackOverflow post here:

https://stackoverflow.com/q/45147260/1953800

**Comment by c6a24554-5737-4174-b47e-54fc0403b8dc** [comment]
Or maybe: "tuple of names of global variables used in the bytecode"
