### ISSUE TITLE
Scripts folder is empty

### ISSUE THREAD

**Issue by f878a6f8-e1f8-4656-9417-b3544513994d** [python/cpython#75141]
BPO | [30958](https://bugs.python.org/issue30958)
--- | :---
Nosy | @ned-deily, @Onixiya

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-19.01:00:46.662>
created_at = <Date 2017-07-18.08:00:43.638>
labels = ['invalid', 'type-bug', 'expert-installation']
title = 'Scripts folder is empty'
updated_at = <Date 2017-07-19.01:00:46.661>
user = 'https://github.com/Onixiya'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-19.01:00:46.661>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-19.01:00:46.662>
closer = 'ned.deily'
components = ['Installation']
creation = <Date 2017-07-18.08:00:43.638>
creator = 'Onixiya'
dependencies = []
files = []
hgrepos = []
issue_num = 30958
keywords = []
message_count = 3.0
messages = ['298578', '298619', '298623']
nosy_count = 2.0
nosy_names = ['ned.deily', 'Onixiya']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30958'
versions = ['Python 3.6']
```

</p></details>

**Comment by f878a6f8-e1f8-4656-9417-b3544513994d** [comment]
The Scripts folder is empty when i installed python.

**Comment by ned-deily** [comment]
Sorry, but you are going to have supply more information for anyone to attempt to give an answer.  Please indicated exactly how you are trying to install Python (building from source, with one of the binary installers, etc), which operating system and version, which version of Python, and the path to the empty Scripts folder.

**Comment by f878a6f8-e1f8-4656-9417-b3544513994d** [comment]
Nvm turns out the modules in the folder were hidden for some reason. Thanks anyway.

Sent from Mail for Windows 10

From: Ned Deily
Sent: Wednesday, 19 July 2017 10:08 AM
To: leo.kerr300@gmail.com
Subject: [bpo-30958] Scripts folder is empty

Ned Deily added the comment:

Sorry, but you are going to have supply more information for anyone to attempt to give an answer.  Please indicated exactly how you are trying to install Python (building from source, with one of the binary installers, etc), which operating system and version, which version of Python, and the path to the empty Scripts folder.

\----------
nosy: +ned.deily

_______________________________________
Python tracker \<report@bugs.python.org\>
\<http://bugs.python.org/issue30958\>
_______________________________________
