### ISSUE TITLE
Add caching to logging.Logger.isEnabledFor()

### ISSUE THREAD

**Issue by 19bd76dc-4503-420c-bcab-5827b5823b32** [python/cpython#75145]
BPO | [30962](https://bugs.python.org/issue30962)
--- | :---
Nosy | @vsajip, @pitrou, @vstinner, @avylove
PRs | <li>python/cpython#2752</li><li>python/cpython#15286</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-30.09:44:55.689>
created_at = <Date 2017-07-18.20:24:53.442>
labels = ['3.7', 'library', 'performance']
title = 'Add caching to logging.Logger.isEnabledFor()'
updated_at = <Date 2019-08-14.19:55:48.148>
user = 'https://github.com/avylove'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-14.19:55:48.148>
actor = 'zaneb'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-30.09:44:55.689>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-07-18.20:24:53.442>
creator = 'aviso'
dependencies = []
files = []
hgrepos = []
issue_num = 30962
keywords = []
message_count = 5.0
messages = ['298612', '298613', '298614', '298615', '299494']
nosy_count = 4.0
nosy_names = ['vinay.sajip', 'pitrou', 'vstinner', 'aviso']
pr_nums = ['2752', '15286']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue30962'
versions = ['Python 3.7']
```

</p></details>

**Comment by 19bd76dc-4503-420c-bcab-5827b5823b32** [comment]
Checking to see if a log level is enabled can add non-insignificant time to programs with a large number of logging statements. This issue is to track a pull request which introduces caching to the logging module so checking to see if a log level is enabled takes half the current time.

Benchmark code is in the referenced pull request

**Comment by pitrou** [comment]
Does this speed up actual logging calls such logger.info, etc?

**Comment by 19bd76dc-4503-420c-bcab-5827b5823b32** [comment]
Yes, though the bottleneck for normal logging is more likely in other areas so the speedup will be less noticeable. Where I notice it is with debug statements when debugging is disabled. In that scenario the bulk of the time is spent checking if the level is enabled anywhere in the ancestry.

**Comment by vstinner** [comment]
>\> Benchmark code is in the referenced pull request
> Does this speed up actual logging calls such logger.info, etc?

According to the benchmark in the PR, it's 50% faster when the log is ignored, like a debug call in production.

**Comment by vsajip** [comment]
New changeset 78c18a9b9a1445f7c755929917a790ba02b4a5e0 by Vinay Sajip (Avram Lubkin) in branch 'master':
bpo-30962: Added caching to Logger.isEnabledFor() (GH-2752)
https://github.com/python/cpython/commit/78c18a9b9a1445f7c755929917a790ba02b4a5e0
