### ISSUE TITLE
Python script is failing to run

### ISSUE THREAD

**Issue by ed12a635-3156-4521-8a04-29436141759c** [python/cpython#75143]
BPO | [30960](https://bugs.python.org/issue30960)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @mlouielu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-18.15:29:55.421>
created_at = <Date 2017-07-18.14:35:07.883>
labels = ['extension-modules', 'type-crash']
title = 'Python script is failing to run'
updated_at = <Date 2017-07-18.17:09:46.796>
user = 'https://bugs.python.org/Megha'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-18.17:09:46.796>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-18.15:29:55.421>
closer = 'r.david.murray'
components = ['Extension Modules']
creation = <Date 2017-07-18.14:35:07.883>
creator = 'Megha'
dependencies = []
files = []
hgrepos = []
issue_num = 30960
keywords = []
message_count = 8.0
messages = ['298589', '298590', '298591', '298593', '298598', '298599', '298606', '298607']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'louielu', 'Megha']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue30960'
versions = []
```

</p></details>

**Comment by ed12a635-3156-4521-8a04-29436141759c** [comment]
Hi,

We are facing below error message whenever we use python.

Could you please let me know root cause and steps to overcome this problem.

./python32.sh
Fatal Python error: Py_Initialize: Unable to get the locale encoding
EOFError: EOF read where not expected
Abort (core dumped)

Python version:

\# ./python3.2 -V
Python 3.2.2
root@atclvm820\>

**Comment by serhiy-storchaka** [comment]
Python 3.2 is not supported version. Try to upgrade to newer version.

**Comment by ed12a635-3156-4521-8a04-29436141759c** [comment]
Hi Serhiy,

Thanks a lot for your comment.

Yes we do aware that 3.2V is outdated.
Our plan is to upgrade to latest version.

Otherside, It'll be great if you can let us know any root cause for below mentioned error message and how to overcome the same.

./python32.sh
Fatal Python error: Py_Initialize: Unable to get the locale encoding
EOFError: EOF read where not expected
Abort (core dumped)

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Your information isn't that clear, this is what I found on the Internet:

https://techglimpse.com/error-executing-python3-5-command-solution/
https://unix.stackexchange.com/questions/17863/py3compile-error-unable-to-get-the-locale-encoding

Maybe your environment variable PYTHONHOME or PYTHONPATH had some problem.

**Comment by ed12a635-3156-4521-8a04-29436141759c** [comment]
Thanks louielu for your response.

Yes I did check related to env & its python path, this looks ok.


#!/usr/sunos/bin/sh -x

\# This script is a wrapper for the official OSS python

PYTHON=/opt/python/python/python3.2
PYTHON_ENV=/etc/opt/ericsson/3ppenv/python.env

if [ -r $PYTHON_ENV ]; then
  . $PYTHON_ENV && export PYTHONHOME && export PYTHONPATH
  $PYTHON $*
else
  echo "reading $PYTHON_ENV failed"
  exit 1
fi

Do you still suggest to export it again ?

May I know 
in which scenarios
1)We can see the mentioned error message
2) core dump will happen for python?

Appreciate your comment.


Also we can see lots and lots of core files of python;



-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.14513
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.14551
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.14651
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.14739
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:05 python3.2.15279
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:05 python3.2.15291
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.15290
-rw-------   1 nmsadm   nms      7430940 Jul 14 07:05 python3.2.15288
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.15368
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:05 python3.2.15374
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.15575
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.15641
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:05 python3.2.15792
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:06 python3.2.16645
-rw-------   1 nmsadm   nms      7430940 Jul 14 07:06 python3.2.16652
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:06 python3.2.16728
-rw-------   1 nmsadm   nms      7410460 Jul 14 07:06 python3.2.16895
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:06 python3.2.17082
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:06 python3.2.17273
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:06 python3.2.17305
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:06 python3.2.17365
-rw-------   1 nmsadm   nms      7426844 Jul 14 07:06 python3.2.17462
#date
Tue Jul 18 16:24:44 IST 2017

**Comment by bitdancer** [comment]
This is a bug tracker for Python.  3.2 is out of maintenance, so such a question is not appropriate for this forum. In any case it is an issue with your install, not with Python itself, so again not appropriate for this forum. You should ask for help on the python-list mailing list, or the #python irc channel on freenode.  

I wish we could help you here, but we need to keep this forum focused on bugs in Python itself.  Please do not reopen the issue.

louielu, if you want to continue to help Megha, which would be great, please take it to private email.

**Comment by ed12a635-3156-4521-8a04-29436141759c** [comment]
Hi,

python-list mailing list, or the #python irc channel on freenode.  

May I know python mailing list please?

**Comment by serhiy-storchaka** [comment]
https://www.python.org/community/lists/
https://www.python.org/community/irc/
