### ISSUE TITLE
Unexpected behavior of operator "in"

### ISSUE THREAD

**Issue by e76c44e5-8994-4e2a-9c6c-fa5cd27949ac** [python/cpython#75148]
BPO | [30965](https://bugs.python.org/issue30965)
--- | :---
Nosy | @tim-one, @ammaraskar, @mcara

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-19.05:34:31.668>
created_at = <Date 2017-07-19.05:28:37.975>
labels = ['type-bug', 'invalid']
title = 'Unexpected behavior of operator "in"'
updated_at = <Date 2017-07-19.14:23:42.380>
user = 'https://github.com/mcara'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-19.14:23:42.380>
actor = 'mcara'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-19.05:34:31.668>
closer = 'ammar2'
components = []
creation = <Date 2017-07-19.05:28:37.975>
creator = 'mcara'
dependencies = []
files = []
hgrepos = []
issue_num = 30965
keywords = []
message_count = 6.0
messages = ['298633', '298634', '298635', '298636', '298678', '298680']
nosy_count = 3.0
nosy_names = ['tim.peters', 'ammar2', 'mcara']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30965'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by e76c44e5-8994-4e2a-9c6c-fa5cd27949ac** [comment]
```pycon
Unexpected behavior of operator "in" when checking if a list/tuple/etc. contains a value:
>>> 1 in [1] is True
False
>>> (1 in [1]) is True
True
```


Is this a bug? If not, please explain why first variant return False.

**Comment by ammaraskar** [comment]
Check out this section of the documentation, notably this part:

"Note that comparisons, membership tests, and identity tests, all have the same precedence and have a left-to-right chaining feature"

Chaining lets you write stuff like this:

```pycon
>>> x = 1
>>> 0 < x < 2
True
```


And since membership tests and identity tests are chained, the code you posted above essentially turns into:

(1 in [1]) and ([1] is True)

The former part of that expression is True but the latter is false.

**Comment by ammaraskar** [comment]
Sorry, forgot the actual link. https://docs.python.org/3/reference/expressions.html#operator-precedence

**Comment by tim-one** [comment]
Not a bug.  For an explanation, I just answered a very similar question on StackOverflow:

https://stackoverflow.com/questions/45180899/unexpected-result-from-in-operator/45180967#45180899

**Comment by e76c44e5-8994-4e2a-9c6c-fa5cd27949ac** [comment]
Thank you! It was my fault: I was not expecting `in` to be a comparison operator.

**Comment by e76c44e5-8994-4e2a-9c6c-fa5cd27949ac** [comment]
I am sure that some time ago I read that `in` is a comparison operator but I forgot it and I was thinking that (x in y) would be equivalent to (replaced with) the return value of y.__contains__(x).
