### ISSUE TITLE
return-value of filecmp.dircmp.report_*

### ISSUE THREAD

**Issue by 05bee110-f329-44f6-a361-04ae3c46b8ba** [python/cpython#75153]
BPO | [30970](https://bugs.python.org/issue30970)
--- | :---
Nosy | @bitdancer, @picibucor
PRs | <li>python/cpython#2762</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-19.14:16:04.816>
created_at = <Date 2017-07-19.12:58:48.870>
labels = ['type-feature', '3.7']
title = 'return-value of filecmp.dircmp.report_*'
updated_at = <Date 2017-07-19.14:16:04.814>
user = 'https://github.com/picibucor'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-19.14:16:04.814>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-19.14:16:04.816>
closer = 'r.david.murray'
components = []
creation = <Date 2017-07-19.12:58:48.870>
creator = 'Mih\xc3\xa1ly Mirk'
dependencies = []
files = []
hgrepos = []
issue_num = 30970
keywords = []
message_count = 2.0
messages = ['298673', '298677']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Mih\xc3\xa1ly Mirk']
pr_nums = ['2762']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30970'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 05bee110-f329-44f6-a361-04ae3c46b8ba** [comment]
The functions: 
filecmp.dircmp.report()
filecmp.dircmp.report_partial_closure()
filecmp.dircmp.report_full_closure()

do not have return values

**Comment by bitdancer** [comment]
Thanks for wanting to improve Python.  However, the purpose of those function is to \*print* the result.  They intentionally do not have return values.

All of the values that you would have these functions return are accessible via attributes already.
