### ISSUE TITLE
Regular expression "hangs" interpreter

### ISSUE THREAD

**Issue by ad5d1ca7-3a28-48c6-a982-6f73be5dfae0** [python/cpython#75156]
BPO | [30973](https://bugs.python.org/issue30973)
--- | :---
Nosy | @ezio-melotti, @bitdancer, @gareth-rees

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-20.15:24:43.944>
created_at = <Date 2017-07-20.04:41:58.549>
labels = ['expert-regex', 'type-bug']
title = 'Regular expression "hangs" interpreter'
updated_at = <Date 2017-07-20.19:22:22.710>
user = 'https://bugs.python.org/TTrindad'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-20.19:22:22.710>
actor = 'mrabarnett'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-20.15:24:43.944>
closer = 'r.david.murray'
components = ['Regular Expressions']
creation = <Date 2017-07-20.04:41:58.549>
creator = 'T Trindad'
dependencies = []
files = []
hgrepos = []
issue_num = 30973
keywords = []
message_count = 4.0
messages = ['298705', '298715', '298727', '298746']
nosy_count = 5.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'r.david.murray', 'gdr@garethrees.org', 'T Trindad']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30973'
versions = ['Python 2.7']
```

</p></details>

**Comment by ad5d1ca7-3a28-48c6-a982-6f73be5dfae0** [comment]
The following code "hangs" the interpreter:

```py
    import re
    re.search(r"/\*\*((?:[^*]+|\*[^/])*)\*/", """	/** Copy Constructor **/
	private EvaluationContext (EvaluationContext base) {""")
```




Changing the regex to r"/\\*\\*((?:[^*]|\\*[^/])*)\\*/" makes it work normally.

**Comment by faa20c90-fcf0-43f4-810b-00286077d549** [comment]
This is the usual exponential backtracking behaviour of Python's regex engine. The problem is that the regex

    (?:[^*]+|\*[^/])*

can match against a string in exponentially many ways, and Python's regex engine tries all of them before giving up.

**Comment by bitdancer** [comment]
Right.  We don't try to fix handling these kinds of exponential expressions.  This is a case of "don't do that" :)

(I don't know if the regex module is better at "handling" this kind of regex bug.)

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
The regex module is much better in this respect, but it's not foolproof. With this particular example it completes quickly.
