### ISSUE TITLE
multiprocessing.Process.is_alive can show True for dead processes

### ISSUE THREAD

**Issue by 4e2d7717-31fe-466f-a906-2a6535f9ced0** [python/cpython#75159]
BPO | [30976](https://bugs.python.org/issue30976)
--- | :---
Nosy | @pfmoore, @tjguk, @gareth-rees, @zware, @zooba, @applio, @mickp
Files | <li>[alive.py](https://bugs.python.org/file47028/alive.py "Uploaded as text/plain at 2017-07-20.14:58:52 by @mickp")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-20.19:13:32.563>
created_at = <Date 2017-07-20.14:58:52.426>
labels = ['invalid', 'OS-windows']
title = 'multiprocessing.Process.is_alive can show True for dead processes'
updated_at = <Date 2017-07-20.19:13:32.561>
user = 'https://github.com/mickp'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-20.19:13:32.561>
actor = 'mickp'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-20.19:13:32.563>
closer = 'mickp'
components = ['Windows']
creation = <Date 2017-07-20.14:58:52.426>
creator = 'mickp'
dependencies = []
files = ['47028']
hgrepos = []
issue_num = 30976
keywords = []
message_count = 3.0
messages = ['298724', '298736', '298745']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'gdr@garethrees.org', 'zach.ware', 'steve.dower', 'davin', 'mickp']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30976'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 4e2d7717-31fe-466f-a906-2a6535f9ced0** [comment]
multiprocessing.Process.is_alive() returns True for processes that have been killed. See attached for example.

Workaround: also test against psutils.pid_exists.

**Comment by faa20c90-fcf0-43f4-810b-00286077d549** [comment]
This is a race condition — when os.kill returns, that means that the signal has been delivered, but it does not mean that the subprocess has exited yet. You can see this by inserting a sleep after the kill and before the liveness check:

```py
    print(proc.is_alive())
    os.kill(proc.pid, signal.SIGTERM)
    time.sleep(1)
    print(proc.is_alive())
```


This (probably) gives the process time to exit. (Presumably the psutil.pid_exists() call has a similar effect.) Of course, waiting for 1 second (or any amount of time) might not be enough. The right thing to do is to join the process. Then when the join exits you know it died.

**Comment by 4e2d7717-31fe-466f-a906-2a6535f9ced0** [comment]
Yep - apologies, my mistake.
