### ISSUE TITLE
Update os.samefile docstring to match documentation

### ISSUE THREAD

**Issue by 96ad250a-ae79-413f-a32d-3b613bde8287** [python/cpython#75157]
BPO | [30974](https://bugs.python.org/issue30974)
--- | :---
Nosy | @bitdancer, @zooba, @eMPee584, @miss-islington, @iritkatriel
PRs | <li>python/cpython#7337</li><li>python/cpython#15086</li><li>python/cpython#15087</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-21.16:30:18.661>
created_at = <Date 2017-07-20.08:07:10.749>
labels = ['3.8', 'type-bug', '3.7', 'docs']
title = 'Update os.samefile docstring to match documentation'
updated_at = <Date 2020-09-21.16:30:18.660>
user = 'https://github.com/eMPee584'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-21.16:30:18.660>
actor = 'steve.dower'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-09-21.16:30:18.661>
closer = 'steve.dower'
components = ['Documentation']
creation = <Date 2017-07-20.08:07:10.749>
creator = 'eMPee584'
dependencies = []
files = []
hgrepos = []
issue_num = 30974
keywords = ['patch']
message_count = 10.0
messages = ['298708', '298731', '322555', '322556', '348928', '348929', '348930', '348932', '348933', '377161']
nosy_count = 6.0
nosy_names = ['r.david.murray', 'docs@python', 'steve.dower', 'eMPee584', 'miss-islington', 'iritkatriel']
pr_nums = ['7337', '15086', '15087']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30974'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 96ad250a-ae79-413f-a32d-3b613bde8287** [comment]
Don't know whether it should be considered a documentation or behavioral issue, but os.samefile calls os.stat() on given files, following symlinks. Does this really "test whether two pathnames reference the same actual file"? I'd consider os.lstat() more suited for that.

This bites me every time I want to overwrite a symlink with its referenced file using ranger.

**Comment by bitdancer** [comment]
I would take "actual file" as meaning the file the symlink points to, so I'd say the documentation matches the implementation according to your description of the two.  The current docs actually say "refer to the same file or directory", and mention os.stat explicitly, so again I'd say the docs and implementation match.

It sounds like what you want is to open a feature request for a samefile equivalent that does not follow symlinks.  lsamefile?

We could use this issue for making the docstring match the docs, though.  I think the sentence in the docs is short enough to just get copied into the docstring.
