### ISSUE TITLE
Calling asyncore.file_wrapper.close twice may close unrelated file descriptor

### ISSUE THREAD

**Issue by a3806f99-9e4c-4c1e-88f5-8972537b5177** [python/cpython#75163]
BPO | [30980](https://bugs.python.org/issue30980)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#2789</li><li>python/cpython#2898</li><li>python/cpython#2899</li><li>python/cpython#2900</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-26.23:27:36.110>
created_at = <Date 2017-07-20.23:23:23.492>
labels = ['3.7', 'type-bug', 'library']
title = 'Calling asyncore.file_wrapper.close twice may close unrelated file descriptor'
updated_at = <Date 2017-07-26.23:27:36.108>
user = 'https://bugs.python.org/NirSoffer'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-26.23:27:36.108>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-26.23:27:36.110>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-07-20.23:23:23.492>
creator = 'Nir Soffer'
dependencies = []
files = []
hgrepos = []
issue_num = 30980
keywords = []
message_count = 5.0
messages = ['298753', '299020', '299021', '299272', '299273']
nosy_count = 2.0
nosy_names = ['vstinner', 'Nir Soffer']
pr_nums = ['2789', '2898', '2899', '2900']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30980'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
Commit 4d4c69dc35154a9c21fed1b6b4088e741fbc6ae6 added protection for double close in file_wrapper.close, but the test did not consider that fact that file_wrapper is dupping the file descriptor, making the test ineffective.

```pycon
>>> fd1, fd2 = os.pipe()
>>> f = asyncore.file_wrapper(fd1)
>>> os.close(f.fd)
>>> f.close()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.5/asyncore.py", line 621, in close
    os.close(self.fd)
OSError: [Errno 9] Bad file descriptor
>>> f.fd
4
>>> fd3, fd4 = os.pipe()
>>> fd3
4
>>> f.close()
>>> os.close(fd3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 9] Bad file descriptor
```


f.close() closed an unrelated file descriptor.

**Comment by vstinner** [comment]
New changeset c648a93ae342ac28d2abbb100161eae4f907d001 by Victor Stinner (Nir Soffer) in branch 'master':
bpo-30980: Fix double close in asyncore.file_wrapper (bpo-2789)
https://github.com/python/cpython/commit/c648a93ae342ac28d2abbb100161eae4f907d001

**Comment by vstinner** [comment]
Thanks for your fix Nir Soffer!

**Comment by vstinner** [comment]
New changeset 29094cec7cddd561cac16ce93443ca72d740de4d by Victor Stinner (Nir Soffer) in branch '2.7':
bpo-30980: Fix double close in asyncore.file_wrapper (bpo-2789) (bpo-2900)
https://github.com/python/cpython/commit/29094cec7cddd561cac16ce93443ca72d740de4d

**Comment by vstinner** [comment]
New changeset 25de5baf3eaebddbf879aacf49c0f614f922dc42 by Victor Stinner (Nir Soffer) in branch '3.6':
bpo-30980: Fix double close in asyncore.file_wrapper (bpo-2789) (bpo-2898)
https://github.com/python/cpython/commit/25de5baf3eaebddbf879aacf49c0f614f922dc42
