### ISSUE TITLE
reduce uuid.UUID() memory footprint

### ISSUE THREAD

**Issue by 64d6bacc-d229-4315-b217-f79274508316** [python/cpython#75160]
BPO | [30977](https://bugs.python.org/issue30977)
--- | :---
Nosy | @vstinner, @taleinat, @serhiy-storchaka, @wbolster
PRs | <li>python/cpython#2785</li><li>python/cpython#9078</li><li>python/cpython#9106</li><li>python/cpython#9133</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-06.11:35:57.364>
created_at = <Date 2017-07-20.17:15:28.449>
labels = ['3.8', 'library', 'performance']
title = 'reduce uuid.UUID() memory footprint'
updated_at = <Date 2018-09-10.13:11:09.040>
user = 'https://github.com/wbolster'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-10.13:11:09.040>
actor = 'taleinat'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-06.11:35:57.364>
closer = 'taleinat'
components = ['Library (Lib)']
creation = <Date 2017-07-20.17:15:28.449>
creator = 'wbolster'
dependencies = []
files = []
hgrepos = []
issue_num = 30977
keywords = ['patch']
message_count = 11.0
messages = ['298738', '298739', '298757', '298785', '303194', '324665', '324671', '324672', '324682', '324683', '324923']
nosy_count = 5.0
nosy_names = ['vstinner', 'taleinat', 'serhiy.storchaka', 'wbolster', 'Nir Soffer']
pr_nums = ['2785', '9078', '9106', '9133']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30977'
versions = ['Python 3.8']
```

</p></details>

**Comment by 64d6bacc-d229-4315-b217-f79274508316** [comment]
memory usage for uuid.UUID seems larger than it has to be. it seems that using \_\_slots__ will save around \~100 bytes per instance, which is very significant, e.g. when dealing with large sets of uuids (which are often used as "primary keys" into external data stores).

uuid.UUID has a \_\_setattr__ that prevents any extra attributes to be
set:

```py
    def __setattr__(self, name, value):
        raise TypeError('UUID objects are immutable')
```


...so it seems to me not having \_\_dict__ should not cause any problems?


before (RES column):

>\>\> import uuid
>\>\> y = {uuid.uuid4() for _ in range(1000000)}

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
23020 wbolster   20   0  315M  253M  7256 S  0.0  1.6  0:04.98 python

```py
with slots:
```


>\>\> import uuid
>\>\> y = {uuid.uuid4() for _ in range(1000000)}

  PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
21722 wbolster   20   0  206M  145M  7348 S  0.0  0.9  0:05.03 python

i will open a pr on github shortly.

**Comment by 64d6bacc-d229-4315-b217-f79274508316** [comment]
as a follow-up note, i also experimented with keeping the actual value as a bytes object instead of an integer, but that does not lead to less memory being used: a 128-bit integer uses less memory than a 16 byte bytes object (presumably because PyBytesObject has a cached hash() field and a trailing null byte).

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
This saves memory, but using str(uuid.uuid4()) requires even less memory.
If you really want to save memory, you can keep the uuid.uuid4().int.

Can you explain someone would like to have 1000000 uuid objects, instead of 1000000 strings? What is the advantage of keeping UUID objects around?

**Comment by 64d6bacc-d229-4315-b217-f79274508316** [comment]
i consider uuids as low level data types, not as fancy containers, similar to how i view datetime objects. given the native support in e.g. postgresql and many other systems, it's common to deal with uuids.

of course you can convert to/from strings or numbers, but that is cumbersome in many cases. for comparison, one would typically not convert unicode text from/into utf-8 encoded byte strings either, even though the latter will save memory in many cases.

from experience: converting can lead to nasty bugs, e.g. because you forgot about a conversion, and then a uuid string does not compare equal to a uuid.UUID instance, leaving you puzzled.

**Comment by serhiy-storchaka** [comment]
This change breaks pickle.

You should preserve forward and backward pickle compatibility.

1. Pickle data produced by old Python versions should be unpickleable with a new implementation. Implement \_\_setstate__ for satisfying this.

2. Pickle data produced by a new implementation should be unpickleable in old Python versions. There are many ways to satisfy this, you should choose the most efficient.
