### ISSUE TITLE
the winapi fails to run shortcuts (because considers a shortcut not a valid Win32App)

### ISSUE THREAD

**Issue by b6f15325-d2b9-4574-aa34-be8d03c91fe0** [python/cpython#75162]
BPO | [30979](https://bugs.python.org/issue30979)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-25.17:38:42.548>
created_at = <Date 2017-07-20.22:32:04.846>
labels = ['type-feature', '3.7', 'OS-windows']
title = 'the winapi fails to run shortcuts (because considers a shortcut not a valid Win32App)'
updated_at = <Date 2021-02-25.17:38:42.548>
user = 'https://bugs.python.org/BerntGbor'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-25.17:38:42.548>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-25.17:38:42.548>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2017-07-20.22:32:04.846>
creator = 'Bern\xc3\xa1t G\xc3\xa1bor'
dependencies = []
files = []
hgrepos = []
issue_num = 30979
keywords = []
message_count = 4.0
messages = ['298752', '298754', '298775', '298782']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Bern\xc3\xa1t G\xc3\xa1bor']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30979'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by b6f15325-d2b9-4574-aa34-be8d03c91fe0** [comment]
Although python27.exe.lnk is callable from any command line tool, with any of its arguments the subprocess module thinks it's not a valid Win32 application.

Proof, let there be python27.exe.lnk be a shortcut to python.exe:

C:\\Python27
λ ls python*
python.exe*  python27.exe.lnk*  pythonw.exe\*

λ python.exe -c "import sys; print(sys.version)"
2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]

C:\\Python27
λ python.exe -c "import subprocess; print(subprocess.call(['./python.exe', '-c', '\\"import sys; print(sys.version)\\"']))"
0

```pytb
C:\Python27
λ python27.exe -c "import subprocess; print(subprocess.call(['./python27.exe.lnk', '-c', '\"import sys; print(sys.version)\"']))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "C:\Python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 193] %1 is not a valid Win32 application
```

**Comment by eryksun** [comment]
subprocess.Popen calls WinAPI CreateProcess, which can execute PE/COFF executables and .BAT/.CMD batch scripts. It doesn't know anything about .LNK shell shortcuts. If CreateProcess fails, a Windows shell (e.g. CMD or PowerShell) tries ShellExecuteEx, which knows how to open a .LNK file. You can use shell=True for this in Python.

Directly supporting ShellExecuteEx would be a major enhancement. It would probably require a new keyword-only parameter, or at least a sentinel value for the existing `shell` parameter.

**Comment by tjguk** [comment]
For shell objects such as shortcuts you could use os.startfile which invokes ShellExecute under the covers

**Comment by eryksun** [comment]
That depends on the shortcut. I have some shortcuts that are designed to be run from the command line (e.g. python.lnk), which take arguments and inherit the working directory of the parent process. I add .LNK to PATHEXT so I can run them as commands without a filename extension. os.startfile doesn't allow passing command-line arguments to these shortcuts.
