### ISSUE TITLE
IDLE: Test config dialog font bold button and sample change

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#75164]
BPO | [30981](https://bugs.python.org/issue30981)
--- | :---
Nosy | @terryjreedy
PRs | <li>python/cpython#2794</li><li>python/cpython#2796</li><li>python/cpython#2798</li><li>python/cpython#2805</li><li>python/cpython#2810</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-22.04:58:45.585>
created_at = <Date 2017-07-21.02:19:00.484>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Test config dialog font bold button and sample change'
updated_at = <Date 2017-07-22.19:33:43.898>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-22.19:33:43.898>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-22.04:58:45.585>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-21.02:19:00.484>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 30981
keywords = []
message_count = 10.0
messages = ['298761', '298770', '298771', '298776', '298779', '298780', '298781', '298834', '298837', '298867']
nosy_count = 1.0
nosy_names = ['terry.reedy']
pr_nums = ['2794', '2796', '2798', '2805', '2810']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30981'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
I am working on this.
* Change 'test_highlight_sample' to 'highlight_sample.
* Change 'set_font_sample()' to 'set_samples()', since it also changes highlight_sample, and test.
* Add gui event test for 'bold' checkbutton.
* Perhaps add gui event test for size pulldown, or wait until replace.
* Test tab setting or wait until replace.

Do this before bpo-24776 to redo page and bpo-13802 to redo sample

**Comment by terryjreedy** [comment]
New changeset d0969d69245d9c4eea3498ba4bde4b4cd676ad7f by Terry Jan Reedy in branch 'master':
bpo-30981: IDLE -- Add more configdialog font page tests.  (bpo-2794)
https://github.com/python/cpython/commit/d0969d69245d9c4eea3498ba4bde4b4cd676ad7f

**Comment by terryjreedy** [comment]
I left out gui event tests since they depends on the widgets, which will likely change.  I though about tests for the uncovered load_font_config and load_tab_config, but am not sure what to do that would not amount to copying their code.

**Comment by terryjreedy** [comment]
Viktor, I am aware that there are errors in the patch I pushed that will result in error on the Windows machines that run gui tests.  Am working on a fix now.

**Comment by terryjreedy** [comment]
I am too tired to fix this correctly right now, so I added @skip to class with failing tests.

**Comment by terryjreedy** [comment]
New changeset 7c5798ebfa9b822d6cedf1fc8c034f6ea90644dc by Terry Jan Reedy in branch 'master':
bpo-30981: temporarity skip failing IDLE test class (bpo-2798)
https://github.com/python/cpython/commit/7c5798ebfa9b822d6cedf1fc8c034f6ea90644dc

**Comment by vstinner** [comment]
Thanks for the fix :-) (Don't forget to fix it later ;-))

**Comment by terryjreedy** [comment]
New changeset 616ecf18f3aacbd8d172e01673877b22fe946e54 by Terry Jan Reedy in branch 'master':
bpo-30981: IDLE: Augment one configdialog font page test (bpo-2810)
https://github.com/python/cpython/commit/616ecf18f3aacbd8d172e01673877b22fe946e54

**Comment by terryjreedy** [comment]
New changeset 04864b491e3ce0f022e918ad344fb53a99ce2a1b by Terry Jan Reedy in branch '3.6':
[3.6] bpo-30981: IDLE -- Add more configdialog font page tests.  (GH-… (bpo-2796)
https://github.com/python/cpython/commit/04864b491e3ce0f022e918ad344fb53a99ce2a1b

**Comment by terryjreedy** [comment]
Followup issue is bpo-30993.
