### ISSUE TITLE
str.format_map() silences exceptions in __getitem__

### ISSUE THREAD

**Issue by 98e2c05b-e10f-4e0f-bfa1-526da4fe30f0** [python/cpython#75161]
BPO | [30978](https://bugs.python.org/issue30978)
--- | :---
Nosy | @brettcannon, @rhettinger, @vstinner, @ericvsmith, @ezio-melotti, @serhiy-storchaka, @Akuli
PRs | <li>python/cpython#2790</li><li>python/cpython#2992</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-03.09:17:00.328>
created_at = <Date 2017-07-20.19:53:55.353>
labels = ['interpreter-core', 'type-bug', '3.7', 'expert-unicode']
title = 'str.format_map() silences exceptions in __getitem__'
updated_at = <Date 2017-08-03.09:17:00.328>
user = 'https://github.com/Akuli'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-03.09:17:00.328>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-03.09:17:00.328>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Unicode']
creation = <Date 2017-07-20.19:53:55.353>
creator = 'Akuli'
dependencies = []
files = []
hgrepos = []
issue_num = 30978
keywords = []
message_count = 12.0
messages = ['298747', '298767', '298794', '298799', '298809', '298812', '298816', '298818', '298819', '298821', '299692', '299693']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'rhettinger', 'vstinner', 'eric.smith', 'ezio.melotti', 'serhiy.storchaka', 'Akuli']
pr_nums = ['2790', '2992']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue30978'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 98e2c05b-e10f-4e0f-bfa1-526da4fe30f0** [comment]
Example:

```py
    class BrokenMapping:
        def __getitem__(self, key):
            1/0
    
    # this silences the ZeroDivisionError and raises KeyError('world')
    'hello {world}'.format_map(BrokenMapping())
```


I have tried this on several different CPython versions on Ubuntu 14.04
(including the latest Python 3.7.0a0 from github) and they all do this.
PyPy passes the ZeroDivisionError through correctly.

**Comment by serhiy-storchaka** [comment]
Yet one consequence: this swallows KeyboardInterrupt and converts it to KeyError.

**Comment by vstinner** [comment]
While KeyboardInterrupt and ZeroDivisionError are easy to understand, IndexError converted to KeyError doesn't look like a major bug. So I'm not sure about fixing Python 3.5 and 3.6. Maybe it's ok because this function is rarely used and exceptions are not "expected": I hardly imagine a code explicitly catching KeyError to do something on format_map() error.

In short, my vote for backport is +0 :-)

**Comment by ericvsmith** [comment]
I'm -0 on a backport. The new behavior is more correct, but I don't like changing the exception type in a micro release.

**Comment by serhiy-storchaka** [comment]
What are your thoughts about backporting this Raymond?

**Comment by vstinner** [comment]
For Python 3.5 and 3.6, would it make sense to modify the code to pass though BaseException, but replace all other exceptions with KeyError? It would be a compromise between doing nothing and fixing the bug :-)

**Comment by rhettinger** [comment]
> What are your thoughts about backporting this Raymond?

+0 On the one hand, this can be considered a bug fix.  On the other hand, I would suspect that no code that is currently working would benefit.

**Comment by 98e2c05b-e10f-4e0f-bfa1-526da4fe30f0** [comment]
I think all exceptions should be passed through. Things like
dict.\_\_contains__ don't selectively turn some errors to KeyError
either; if something is not hashable it's a TypeError, not a KeyError.

```pycon
    >>> [] in {}
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: unhashable type: 'list'
```

**Comment by 98e2c05b-e10f-4e0f-bfa1-526da4fe30f0** [comment]
Oops, I forgot to mention that I have no thoughts about backporting
this. It would be nice to see this fixed in 3.7 though :)

**Comment by brettcannon** [comment]
I'm -0 on the backport since as Raymond and Eric pointed out it won't benefit currently working code and I personally don't like changing what exception is raised in a bugfix release.

**Comment by serhiy-storchaka** [comment]
New changeset 5075416b8fedc5526b643dabc915f7945fa0d969 by Serhiy Storchaka in branch 'master':
bpo-30978: str.format_map() now passes key lookup exceptions through. (bpo-2790)
https://github.com/python/cpython/commit/5075416b8fedc5526b643dabc915f7945fa0d969

**Comment by serhiy-storchaka** [comment]
New changeset f08b2be4416163e3d18b8d09891e7cda0d8a21d4 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-30978: str.format_map() now passes key lookup exceptions through. (GH-2790) (bpo-2992)
https://github.com/python/cpython/commit/f08b2be4416163e3d18b8d09891e7cda0d8a21d4
