### ISSUE TITLE
Add --include-py argument to Tools/msi/make_zip.py

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#75169]
BPO | [30986](https://bugs.python.org/issue30986)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @segevfiner
PRs | <li>python/cpython#2806</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-05-29.09:54:41.303>
created_at = <Date 2017-07-21.22:06:13.878>
labels = ['type-feature', '3.7', 'OS-windows']
title = 'Add --include-py argument to Tools/msi/make_zip.py'
updated_at = <Date 2020-05-29.09:54:41.302>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-29.09:54:41.302>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2020-05-29.09:54:41.303>
closer = 'cheryl.sabella'
components = ['Windows']
creation = <Date 2017-07-21.22:06:13.878>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 30986
keywords = []
message_count = 3.0
messages = ['298826', '298852', '298853']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Segev Finer']
pr_nums = ['2806']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30986'
versions = ['Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
Add an argument --include-py to [Tools/msi/make_zip.py](https://github.com/python/cpython/blob/main/Tools/msi/make_zip.py) that allows including the Python modules sources and not only bytecode.

I found it useful while running Twisted's test suite in [PR 2318](https://github.com/python/cpython/pull/2318), since I got an error otherwise. I don't remember what that error was and wasn't able to reproduce it while trying to run Twisted's test suite again.

**Comment by zooba** [comment]
The nuget package doesn't suffer from this - why not? Should you have been using the full layout rather than the embedding layout?

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
I used the full one. I doubt virtualenv (used by tox) will work with the embedding layout :P.

I remember getting an exception from something because it was missing the .py source files but I don't remember what it was and wasn't able to reproduce it now.
