### ISSUE TITLE
Sort only when needed in TimedRotatingFileHandler's getFilesToDelete

### ISSUE THREAD

**Issue by a7b5c67e-117a-4abb-a6aa-4a7a06cef472** [python/cpython#75172]
BPO | [30989](https://bugs.python.org/issue30989)
--- | :---
Nosy | @vsajip, @lovesh
PRs | <li>python/cpython#2812</li><li>python/cpython#4466</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-19.22:28:03.729>
created_at = <Date 2017-07-22.07:17:22.771>
labels = ['3.7', 'type-feature', 'library']
title = "Sort only when needed in TimedRotatingFileHandler's getFilesToDelete"
updated_at = <Date 2017-11-19.22:28:03.728>
user = 'https://github.com/lovesh'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-19.22:28:03.728>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-19.22:28:03.729>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-07-22.07:17:22.771>
creator = 'Lovesh Harchandani'
dependencies = []
files = []
hgrepos = []
issue_num = 30989
keywords = ['patch']
message_count = 3.0
messages = ['298839', '305104', '306508']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'Lovesh Harchandani']
pr_nums = ['2812', '4466']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30989'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a7b5c67e-117a-4abb-a6aa-4a7a06cef472** [comment]
At `/Lib/logging/handlers.py` in `TimedRotatingFileHandler`'s `getFilesToDelete` method, filenames are sorted using `result.sort()` regardless of `len(result)`, if `len(result)` < backupCount, sorting is not required.

**Comment by vsajip** [comment]
New changeset afad147b59fe84b12317f7340ddd2deeecb22321 by Vinay Sajip (Lovesh Harchandani) in branch 'master':
bpo-30989: Sort in TimedRotatingFileHandler only when needed. (GH-2812)
https://github.com/python/cpython/commit/afad147b59fe84b12317f7340ddd2deeecb22321

**Comment by vsajip** [comment]
New changeset 65dffe58dd062385024eacbe75a0fa59ec12a993 by Vinay Sajip (Miss Islington (bot)) in branch '3.6':
bpo-30989: Sort in TimedRotatingFileHandler only when needed. (GH-2812) (GH-4466)
https://github.com/python/cpython/commit/65dffe58dd062385024eacbe75a0fa59ec12a993
