### ISSUE TITLE
Support for ISO-TP protocol in SocketCAN

### ISSUE THREAD

**Issue by 28c9ae67-5f7c-48e5-b39a-08b39a89784e** [python/cpython#75170]
BPO | [30987](https://bugs.python.org/issue30987)
--- | :---
Nosy | @terryjreedy, @tiran, @berkerpeksag, @pylessard
PRs | <li>python/cpython#2956</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.10:03:27.357>
created_at = <Date 2017-07-22.04:13:11.705>
labels = ['3.7', 'type-feature', 'library']
title = 'Support for ISO-TP protocol in SocketCAN'
updated_at = <Date 2017-11-24.10:03:27.356>
user = 'https://github.com/pylessard'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.10:03:27.356>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.10:03:27.357>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-07-22.04:13:11.705>
creator = 'Pier-Yves Lessard'
dependencies = []
files = []
hgrepos = []
issue_num = 30987
keywords = []
message_count = 4.0
messages = ['298832', '300861', '300943', '305174']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'christian.heimes', 'berker.peksag', 'Pier-Yves Lessard']
pr_nums = ['2956']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue30987'
versions = ['Python 3.7']
```

</p></details>

**Comment by 28c9ae67-5f7c-48e5-b39a-08b39a89784e** [comment]
PF_CAN socket using ISO-TP protocol cannot be used as getsockaddrarg only supports CAN_RAW and CAN_BCM for AF_CAN addresses.

**Comment by terryjreedy** [comment]
There is no specific maintainer for socket modules, so this may or may not get attention anytime soon -- https://docs.python.org/devguide/experts.html.

New features are not backported.

**Comment by tiran** [comment]
New changeset a30f6d45ac3e72761b96a8df0527182029eaee24 by Christian Heimes (Pier-Yves Lessard) in branch 'master':
bpo-30987 - Support for ISO-TP protocol in SocketCAN (bpo-2956)
https://github.com/python/cpython/commit/a30f6d45ac3e72761b96a8df0527182029eaee24

**Comment by berkerpeksag** [comment]
[PR 2956](https://github.com/python/cpython/pull/2956) has been merged. Christian, can this issue be closed now?
