### ISSUE TITLE
Invalid PGP Key Prevents Archive Validation

### ISSUE THREAD

**Issue by c4c50ee6-8483-4bc8-b87c-d4fa2253feb6** [python/cpython#75175]
BPO | [30992](https://bugs.python.org/issue30992)
--- | :---
Nosy | @ned-deily, @cwgem

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-28.17:43:16.516>
created_at = <Date 2017-07-22.15:53:23.799>
labels = ['expert-installation']
title = 'Invalid PGP Key Prevents Archive Validation'
updated_at = <Date 2017-07-28.19:51:27.781>
user = 'https://github.com/cwgem'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-28.19:51:27.781>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-28.17:43:16.516>
closer = 'ned.deily'
components = ['Installation']
creation = <Date 2017-07-22.15:53:23.799>
creator = 'cwprogram'
dependencies = []
files = []
hgrepos = []
issue_num = 30992
keywords = []
message_count = 3.0
messages = ['298858', '299415', '299431']
nosy_count = 2.0
nosy_names = ['ned.deily', 'cwprogram']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30992'
versions = ['Python 3.6']
```

</p></details>

**Comment by c4c50ee6-8483-4bc8-b87c-d4fa2253feb6** [comment]
When trying to validate the Python 3.6.1 tgz using the ASC file, I can't import all the keys due to the following error:

```
gpg: Note: signatures using the MD5 algorithm are rejected
gpg: key ED9D77D5: no valid user IDs
gpg: this may be caused by a missing self-signature
```

This is using Ubuntu 16.04 and gpg (GnuPG) 1.4.20, running the command

```
wget https://www.python.org/static/files/pubkeys.txt
gpg --import pubkeys.txt
```

If I take out the key ID manually out of the entire list and import the keys by their IDs instead it works.

**Comment by ned-deily** [comment]
Thanks for the report.  I have opened https://github.com/python/pythondotorg/pull/1109 to remove the obsolete MD5 key from the pubkeys file.  Until the updated file is deployed and the website page updated, another workaround may be to use the --allow-weak-digest-algos option of gpg:

gpg --import --allow-weak-digest-algos pubkeys.txt

In general, problems with the python.org website should be reported on its issue tracker:

https://www.python.org/about/help/
https://github.com/python/pythondotorg/issues

**Comment by ned-deily** [comment]
P.S., the pubkeys.txt file on python.org and the "OpenPGP Public Keys" section of https://www.python.org/downloads/ have now been updated.
