### ISSUE TITLE
add coroutine AbstractEventLoop.sock_close

### ISSUE THREAD

**Issue by 68d0670c-2e75-4424-bf2b-65112da5b875** [python/cpython#75179]
BPO | [30996](https://bugs.python.org/issue30996)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[asyncio_wait_forever.py](https://bugs.python.org/file47034/asyncio_wait_forever.py "Uploaded as text/plain at 2017-07-23.09:30:07 by cfy")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-23.09:30:07.956>
labels = ['expert-asyncio', '3.7', 'performance']
title = 'add coroutine AbstractEventLoop.sock_close'
updated_at = <Date 2017-12-21.09:37:37.246>
user = 'https://bugs.python.org/cfy'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-21.09:37:37.246>
actor = 'asvetlov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-07-23.09:30:07.956>
creator = 'cfy'
dependencies = []
files = ['47034']
hgrepos = []
issue_num = 30996
keywords = []
message_count = 2.0
messages = ['298894', '308863']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'cfy']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue30996'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 68d0670c-2e75-4424-bf2b-65112da5b875** [comment]
I suppose asyncio lack async version of sock_close that can call loop.remove_reader and others before close socket and perhaps lack something like coroutine AbstractEventLoop.sock_make_blocking that can do some deregister job.

switch constant in the script:
* change CALL_REMOVE_READING_BEFORE_CLOSE to True will make script running smoothly
* change USE_UVLOOP to True will make script use uvloop

**Comment by kumaraditya303** [comment]
No comments in last 5 years, I'll close this for now. The use-case isn't clear and not many users have requested this, we can reconsider if anyone has a use-case for this.

P.S I recommend to use high level APIs instead of lower level APIs like handling fd directly unless necessary.
