### ISSUE TITLE
Asyncore does not need to copy map.items() before polling

### ISSUE THREAD

**Issue by a3806f99-9e4c-4c1e-88f5-8972537b5177** [python/cpython#75177]
BPO | [30994](https://bugs.python.org/issue30994)
--- | :---
Nosy | @vstinner
PRs | <li>python/cpython#2819</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-25.18:29:54.865>
created_at = <Date 2017-07-23.00:15:18.836>
labels = ['3.7', 'library']
title = 'Asyncore does not need to copy map.items() before polling'
updated_at = <Date 2017-07-25.18:29:54.864>
user = 'https://bugs.python.org/NirSoffer'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-25.18:29:54.864>
actor = 'Nir Soffer'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-25.18:29:54.865>
closer = 'Nir Soffer'
components = ['Library (Lib)']
creation = <Date 2017-07-23.00:15:18.836>
creator = 'Nir Soffer'
dependencies = []
files = []
hgrepos = []
issue_num = 30994
keywords = []
message_count = 5.0
messages = ['298880', '298905', '299029', '299031', '299129']
nosy_count = 2.0
nosy_names = ['vstinner', 'Nir Soffer']
pr_nums = ['2819']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue30994'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
Asyncore is not thread safe, and cannot be called from multiple threads. Hence it does not need to copy the socket_map when preparing for poll or
select.

The copy was introduced in:

commit d74900ebb5a22b387b49684990da1925e1d6bdc9
Author: Josiah Carlson \<josiah.carlson@gmail.com\>
Date:   Mon Jul 7 04:15:08 2008 +0000

    Committing Py3k version of changelist 64080 and 64257, along with updated tests
    for smtpd, which required updating with the new semantics.

This is a huge patch, looks like port of asyncore to python 3, trying to 
keep the behavior of the python 2 code.

Converting map.items() to list(map.items()) is correct, but on python 3 we
can take advantage of the fact that items() does not copy anything.

**Comment by vstinner** [comment]
Why it may be ok to avoid the copy, what is the advantage of applying the
change? The current code is correct.

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
The advantage is avoiding wasteful copy on each iteration.

**Comment by vstinner** [comment]
asyncore is now deprecated and I prefer to restrict changes to minimum to avoid regressions. While the change makes sense, it only looks like a very cheap micro-optimization. I don't think that it's worth it.

**Comment by a3806f99-9e4c-4c1e-88f5-8972537b5177** [comment]
Using a quick test with 1000 clients sending 1000000 pings, I could not see
significant difference between master and this patch. Seems that the extra
copy is hidden by the noise.

Having this documented is good enough if someone want to use this.
