### ISSUE TITLE
IDLE: Add tests for configdialog highlight tab

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#75184]
BPO | [31001](https://bugs.python.org/issue31001)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#2908</li><li>python/cpython#3123</li><li>python/cpython#3124</li>
Dependencies | <li>bpo-31205: IDLE, configdialog: Factor out KeysPage class from ConfigDialog</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-08-18.01:03:13.313>
created_at = <Date 2017-07-24.07:22:14.860>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE: Add tests for configdialog highlight tab'
updated_at = <Date 2017-08-18.01:03:29.306>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-18.01:03:29.306>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-08-18.01:03:13.313>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-07-24.07:22:14.860>
creator = 'terry.reedy'
dependencies = ['31205']
files = []
hgrepos = []
issue_num = 31001
keywords = []
message_count = 7.0
messages = ['299596', '300276', '300351', '300463', '300464', '300466', '300467']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'cheryl.sabella']
pr_nums = ['2908', '3123', '3124']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31001'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
[Pr2908](https://github.com/python/cpython/pull/2908) originally just sorted highlight methods together, but was extended to sort all methods together and relabeled for bpo-31060.  (This actually simplified the diff.)  [Pr2925](https://github.com/python/cpython/pull/2925), the 3.6 backport, appears on the replacement issue.

**Comment by terryjreedy** [comment]
If we do the same renamings for the theme selection vars and functions as done for keys selection on the keys tab, then the corresponding tests can be copied and slightly altered.  However, duplicate names require that KeyPage be separated first.  Hence the dependency.

When the current mess is replaced on both pages, we \*might* be able to make a simple Frame subclass tested once and used on both pages.

**Comment by csabella** [comment]
Working on this now.

**Comment by terryjreedy** [comment]
Coverage now 95%.  We are getting close.  Still not covered in highlight group: 
 
create_page_highlight:  # Highlight only.
    text.bind('\<Double-Button-1\>', lambda e: 'break')
    text.bind('\<B1-Motion\>', lambda e: 'break')
Callbacks are never called. I presume that these mask something.  I am not sure that they are needed.

save_new:  # Same as for keys.
        if not idleConf.userCfg['highlight'].has_section(theme_name): 
Never false.

delete_custom:  # Same as for keys.
        if not item_list: 
            self.custom_theme_on['state'] = DISABLED 
            self.customlist.SetMenu(item_list, '- no custom themes -') 
        else: 
            self.customlist.SetMenu(item_list, item_list[0]) 
Condition never false, else never executed.

**Comment by terryjreedy** [comment]
New changeset 82aff62462e65077a6614b466c986f93a601c33d by Terry Jan Reedy (Cheryl Sabella) in branch 'master':
bpo-31001: IDLE: Add tests for configdialog highlight tab (bpo-3123)
https://github.com/python/cpython/commit/82aff62462e65077a6614b466c986f93a601c33d

**Comment by terryjreedy** [comment]
New changeset 6db2edbe050cc9ac9026f350a24f2d525bcadecd by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31001: IDLE: Add tests for configdialog highlight tab (GH-3123) (bpo-3124)
https://github.com/python/cpython/commit/6db2edbe050cc9ac9026f350a24f2d525bcadecd

**Comment by terryjreedy** [comment]
Another big thank you.
