### ISSUE TITLE
[Regression] sphinx shows an EOF error when using python2.7 from the trunk

### ISSUE THREAD

**Issue by doko42** [python/cpython#75199]
BPO | [31016](https://bugs.python.org/issue31016)
--- | :---
Nosy | @doko42, @pitrou, @vstinner, @benjaminp

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-16.17:35:58.196>
created_at = <Date 2017-07-24.15:05:43.075>
labels = ['invalid', 'library', 'release-blocker']
title = '[Regression] sphinx shows an EOF error when using python2.7 from the trunk'
updated_at = <Date 2017-09-18.06:56:47.362>
user = 'https://github.com/doko42'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-18.06:56:47.362>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-16.17:35:58.196>
closer = 'benjamin.peterson'
components = ['Library (Lib)']
creation = <Date 2017-07-24.15:05:43.075>
creator = 'doko'
dependencies = []
files = []
hgrepos = []
issue_num = 31016
keywords = []
message_count = 5.0
messages = ['298980', '302260', '302322', '302346', '302410']
nosy_count = 4.0
nosy_names = ['doko', 'pitrou', 'vstinner', 'benjamin.peterson']
pr_nums = []
priority = 'release blocker'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31016'
versions = ['Python 2.7']
```

</p></details>

**Comment by doko42** [comment]
[forwarded from https://bugs.debian.org/869098 and]

sphinx shows an EOF error when using python2.7 from the trunk. Last successful build was with the 2.7.13 release.

It looks like this is triggered only when using the parallel mode in sphinx.  I haven't yet worked on this issue, Sphinx is v1.4.9.

sphinx-build -b html -d \_build/doctrees  -n -j 4 . \_build/html
Running Sphinx v1.4.9
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/2/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 91 source files that are out of date
updating environment: 91 added, 0 changed, 0 removed
reading sources... [100%] test-repositories .. writing-tests                                                                                  
waiting for workers...

Exception occurred:
  File "/usr/lib/python2.7/dist-packages/sphinx/util/parallel.py", line 97, in \_join_one
    exc, result = pipe.recv()
EOFError

**Comment by vstinner** [comment]
Using git bisect, I identified that Sphinx started to fail since the commit 12536bd261ba95cd2748f3d7d47768742a6ffa7a which comes from bpo-30775.

I reported the bug to Sphinx:
https://github.com/sphinx-doc/sphinx/issues/4061

**Comment by benjaminp** [comment]
This seems like a bug, or least poor design, in Sphinx. It tries to read from pipes from processes that it knows are already dead (because it joined them!).

**Comment by benjaminp** [comment]
wontfixing since Sphinx has fixed their code.

**Comment by vstinner** [comment]
FYI The bug has been fixed in the Sphinx development branch (HEAD of master): https://github.com/sphinx-doc/sphinx/issues/4061#issuecomment-330140975 I validated that Sphinx master now works as expected on Python 2.7.14.
