### ISSUE TITLE
webbrowser._synthesize uses outdated calling signature for webbrowser.register

### ISSUE THREAD

**Issue by d6d00a9f-f997-40c9-a91c-a71a998535b8** [python/cpython#75197]
BPO | [31014](https://bugs.python.org/issue31014)
--- | :---
Nosy | @ncoghlan, @vstinner, @serhiy-storchaka, @davesteele, @jmsdvl, @miss-islington
PRs | <li>python/cpython#2689</li><li>python/cpython#7267</li><li>python/cpython#8183</li><li>python/cpython#10729</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-07-08.08:19:09.179>
created_at = <Date 2017-07-24.14:32:24.484>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'webbrowser._synthesize uses outdated calling signature for webbrowser.register'
updated_at = <Date 2018-11-26.21:49:33.945>
user = 'https://github.com/jmsdvl'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-26.21:49:33.945>
actor = 'miss-islington'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-07-08.08:19:09.179>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-07-24.14:32:24.484>
creator = 'jmsdvl'
dependencies = []
files = []
hgrepos = []
issue_num = 31014
keywords = ['patch']
message_count = 13.0
messages = ['298976', '298986', '298987', '298989', '299000', '299007', '318173', '318174', '318243', '321266', '321268', '330466', '330469']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'vstinner', 'serhiy.storchaka', 'daves', 'jmsdvl', 'miss-islington']
pr_nums = ['2689', '7267', '8183', '10729']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31014'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by d6d00a9f-f997-40c9-a91c-a71a998535b8** [comment]
The function `register` of the `webbrowser` module was updated a little while back to use the newish keyword-only argument syntax; however, the function `_synthesize` (also in `webbrowser`) is still using the outdated positional arguments only calling convention; leading a pair of tests in `[Lib/tests/test_webbrowser.py](https://github.com/python/cpython/blob/main/Lib/tests/test_webbrowser.py)` to fail.  I've issued a PR that fixes the function call to use the more modern calling convention.

**Comment by serhiy-storchaka** [comment]
Is it possible to write a test?

**Comment by d6d00a9f-f997-40c9-a91c-a71a998535b8** [comment]
What would a new test be testing? I only found this behaviour because two existing tests were failing (with the PR they pass, of course). I'm happy to write a test, I'm just not sure what the test should be testing that the existing tests don't already test.

**Comment by serhiy-storchaka** [comment]
These tests are not failing on our buildbots and developer's computers. Seems they are failing only in special environment. This path of execution is not tested in more common environments, therefore possible regression couldn't be caught until somebody run tests in similar special environment. New test should test this path of execution in common environments.

**Comment by d6d00a9f-f997-40c9-a91c-a71a998535b8** [comment]
Ok I understand what you mean.

I think the only conditions for test failure are (A) $BROWSER is set and (B) $BROWSER is set to an actual executable that should be caught by \`\`register_standard_browsers\`\` prior to execution reaching the last if clause of \`\`register_standard_browsers\`\` (\`\`if 'BROWSER' in os.environ:\`\`) - those two conditions should be sufficient for execution to reach the offending line of code.

I'll see if I can cook up a test for that.  I think the right way to do this is to monkeypatch ``os.environ`` and ``shutil.which``, am I right?

**Comment by serhiy-storchaka** [comment]
This would be not easy. Since the BROWSER environment variable should be patched before the first use the webbrowser module, the test should import webbrowser in a separate process (you can use the test.support.script_helper.assert_python_ok() helper).

\_synthesize() is used in two places with different arguments: in register_standard_browsers() and in get().
