### ISSUE TITLE
gcc7 throws warning when pymem.h development header is used

### ISSUE THREAD

**Issue by 54ff019f-b4f3-4d27-9ab6-4b362de8cb97** [python/cpython#75196]
BPO | [31013](https://bugs.python.org/issue31013)
--- | :---
Nosy | @vstinner, @encukou, @stratakis
Superseder | <li>bpo-31474: [2.7] Fix  -Wnonnull and -Wint-in-bool-context warnings</li>
Files | <li>[Python-2.7.13-pymem-gcc7.patch](https://bugs.python.org/file47035/Python-2.7.13-pymem-gcc7.patch "Uploaded as text/plain at 2017-07-24.14:15:36 by Gabriel Somlo"): patch to fix gcc7 warnings when calling PyMem_MALLOC  macros</li><li>[netnsmodule.c](https://bugs.python.org/file47036/netnsmodule.c "Uploaded as text/x-csrc at 2017-07-24.14:19:05 by Gabriel Somlo"): file showing warning emitted with -Wall (error -Werror)</li><li>[foo.c](https://bugs.python.org/file47037/foo.c "Uploaded as text/x-csrc at 2017-07-24.14:36:47 by Gabriel Somlo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-28.17:55:45.169>
created_at = <Date 2017-07-24.14:15:36.430>
labels = []
title = 'gcc7 throws warning when pymem.h development header is used'
updated_at = <Date 2018-02-28.17:55:45.168>
user = 'https://bugs.python.org/GabrielSomlo'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-28.17:55:45.168>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-28.17:55:45.169>
closer = 'ned.deily'
components = []
creation = <Date 2017-07-24.14:15:36.430>
creator = 'Gabriel Somlo'
dependencies = []
files = ['47035', '47036', '47037']
hgrepos = []
issue_num = 31013
keywords = ['patch']
message_count = 6.0
messages = ['298973', '298974', '298975', '298977', '298978', '313057']
nosy_count = 4.0
nosy_names = ['vstinner', 'petr.viktorin', 'cstratak', 'Gabriel Somlo']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31474'
type = None
url = 'https://bugs.python.org/issue31013'
versions = ['Python 2.7']
```

</p></details>

**Comment by 54ff019f-b4f3-4d27-9ab6-4b362de8cb97** [comment]
C programs using PyMem_MALLOC in pymem.h generate a warning when -Wint-in-bool-context is enabled (typically through -Wall). In places where -Werror is enabled (such as RPM build), this causes the build to fail with an error that looks like:

...
In file included from /usr/include/python2.7/Python.h:78:0,
                 from netnsmodule.c:16:
netnsmodule.c: In function 'netns_nsexecvp':
/usr/include/python2.7/pymem.h:97:30: error: '\*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]
  ( (type \*) PyMem_MALLOC((n) * sizeof(type)) ) )
                              ^
/usr/include/python2.7/pymem.h:75:15: note: in definition of macro 'PyMem_MALLOC'
     : malloc((n) ? (n) : 1))
               ^
netnsmodule.c:61:10: note: in expansion of macro 'PyMem_NEW'
   argv = PyMem_NEW(char \*, argc + 1);
          ^~~~~~~~~
cc1: all warnings being treated as errors
error: command 'gcc' failed with exit status 1
...

I'm attaching a patch that fixes the issue, please consider applying!

Thanks,
--Gabriel

**Comment by 54ff019f-b4f3-4d27-9ab6-4b362de8cb97** [comment]
This attachment illustrates how the problem is triggered. The file is part of the CORE network emulator (github.com/coreemu/core). Compile with "gcc -Wall -I/usr/include/python2.7 -c netnsmodule.c".

**Comment by vstinner** [comment]
> /usr/include/python2.7/pymem.h:97:30: error: '\*' in boolean context, suggest '&&' instead [-Werror=int-in-bool-context]

I don't understand this error. I would be curious to see the output of the preprocessor. Try maybe to use gcc -E?

**Comment by 54ff019f-b4f3-4d27-9ab6-4b362de8cb97** [comment]
output of "gcc -E -Wall -I/usr/include/python2.7 -c netnsmodule.c \> foo.c"

I think gcc7 is a bit more paranoid about whether some expression evaluating to an int can/should in itself be used as a Boolean (i.e., without being compared to 0).

**Comment by vstinner** [comment]
> malloc(((argc + 1) * sizeof(char \*)) ? ((argc + 1) * sizeof(char \*)) : 1)) ) );

Ah ok, the "(n)?" expression is "((argc + 1) * sizeof(char \*)) ? " and yes it contains "\*".
