### ISSUE TITLE
gcc 7 fallthrough warnings

### ISSUE THREAD

**Issue by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [python/cpython#75200]
BPO | [31017](https://bugs.python.org/issue31017)
--- | :---
Nosy | @zware, @stratakis
Superseder | <li>bpo-30923: Add -Wimplicit-fallthrough=0 to Makefile ?</li>
Files | <li>[fallthrough36](https://bugs.python.org/file47039/fallthrough36 "Uploaded as text/plain at 2017-07-24.17:07:48 by @stratakis")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-24.17:10:14.852>
created_at = <Date 2017-07-24.17:07:49.484>
labels = ['3.7']
title = 'gcc 7 fallthrough warnings'
updated_at = <Date 2017-07-24.17:10:14.850>
user = 'https://github.com/stratakis'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-24.17:10:14.850>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-24.17:10:14.852>
closer = 'zach.ware'
components = []
creation = <Date 2017-07-24.17:07:49.484>
creator = 'cstratak'
dependencies = []
files = ['47039']
hgrepos = []
issue_num = 31017
keywords = []
message_count = 2.0
messages = ['298996', '298997']
nosy_count = 2.0
nosy_names = ['zach.ware', 'cstratak']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30923'
type = None
url = 'https://bugs.python.org/issue31017'
versions = ['Python 3.7']
```

</p></details>

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
On gcc 7 the new -Wimplicit-fallthrough option was introduced which produces warnings about switch cases that can fall through.

The easiest way to silence these warnings is to add the comment /* Falls through. \*/ for those cases. More information here [0]

Attaching the stderr output from compilation from the master branch.

[0] https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/

**Comment by zware** [comment]
This is a duplicate of bpo-30923.
