### ISSUE TITLE
_tracemalloc frame_t packing optimization not working in Windows x64

### ISSUE THREAD

**Issue by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [python/cpython#75201]
BPO | [31018](https://bugs.python.org/issue31018)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba, @segevfiner
PRs | <li>python/cpython#2848</li><li>python/cpython#2492</li><li>python/cpython#2868</li><li>python/cpython#2869</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-25.17:21:25.140>
created_at = <Date 2017-07-24.17:20:41.563>
labels = ['extension-modules', 'type-feature', '3.7', 'OS-windows']
title = '_tracemalloc frame_t packing optimization not working in Windows x64'
updated_at = <Date 2017-07-25.17:21:25.139>
user = 'https://github.com/segevfiner'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-25.17:21:25.139>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-25.17:21:25.140>
closer = 'vstinner'
components = ['Extension Modules', 'Windows']
creation = <Date 2017-07-24.17:20:41.563>
creator = 'Segev Finer'
dependencies = []
files = []
hgrepos = []
issue_num = 31018
keywords = []
message_count = 5.0
messages = ['298999', '299046', '299121', '299122', '299123']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower', 'Segev Finer']
pr_nums = ['2848', '2492', '2868', '2869']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31018'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6ccb8c66-b6ca-4c37-b449-e35b11a6b9e4** [comment]
..\\Modules\\_tracemalloc.c(88): warning C4359: '\<unnamed-tag\>': Alignment specifier is less than actual alignment (8), and will be ignored.

For this to actually work we simply need to use #pragma pack instead.

**Comment by vstinner** [comment]
New changeset 39243779f4c97ec6f700fa73c007ca66dfa9408e by Victor Stinner (Segev Finer) in branch 'master':
bpo-31018: Switch to #pragma pack from \_\_declspec(align) (bpo-2848)
https://github.com/python/cpython/commit/39243779f4c97ec6f700fa73c007ca66dfa9408e

**Comment by vstinner** [comment]
New changeset d8b5216f998bbb0f921815165f46918b86620ab7 by Victor Stinner (Segev Finer) in branch '3.6':
[3.6] bpo-31018: Switch to GH-pragma pack from \_\_declspec(align) (GH-2848) (bpo-2868)
https://github.com/python/cpython/commit/d8b5216f998bbb0f921815165f46918b86620ab7

**Comment by vstinner** [comment]
New changeset 49175b3b670a4514b5dc5dcf7b58203d2be852c1 by Victor Stinner (Segev Finer) in branch '3.5':
[3.5] bpo-31018: Switch to GH-pragma pack from \_\_declspec(align) (GH-2848) (bpo-2869)
https://github.com/python/cpython/commit/49175b3b670a4514b5dc5dcf7b58203d2be852c1

**Comment by vstinner** [comment]
Thanks for the fix ;-)
