### ISSUE TITLE
sys.executable can be not normalized

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75213]
BPO | [31030](https://bugs.python.org/issue31030)
--- | :---
Nosy | @terryjreedy, @vstinner, @serhiy-storchaka, @eryksun

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-07-25.12:41:50.673>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10', 'tests']
title = 'sys.executable can be not normalized'
updated_at = <Date 2021-02-27.20:06:55.248>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-27.20:06:55.248>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'Tests']
creation = <Date 2017-07-25.12:41:50.673>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31030
keywords = []
message_count = 8.0
messages = ['299065', '299067', '299068', '299444', '299456', '387775', '387782', '387787']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'vstinner', 'serhiy.storchaka', 'eryksun']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31030'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
test_executable in [Lib/test/test_sys.py](https://github.com/python/cpython/blob/main/Lib/test/test_sys.py) tests that sys.executable is absolute. But this test is too strong, it fails if sys.executable is not normalized.

```pytb
$ Lib/../python -m test test_sys
Run tests sequentially
0:00:00 load avg: 0.39 [1/1] test_sys
test test_sys failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_sys.py", line 649, in test_executable
    self.assertEqual(os.path.abspath(sys.executable), sys.executable)
AssertionError: '/home/serhiy/py/cpython/python' != '/home/serhiy/py/cpython/Lib/../python'
- /home/serhiy/py/cpython/python
+ /home/serhiy/py/cpython/Lib/../python
?                         +++++++
```



test_sys failed

1 test failed:
    test_sys

Total duration: 2 sec
Tests result: FAILURE

I don't know what is wrong: the value of sys.executable or the test.

**Comment by serhiy-storchaka** [comment]
test_venv fails for the same cause.

```pytb
$ Lib/../python -m test -m test_defaults test_venv
Run tests sequentially
0:00:00 load avg: 0.31 [1/1] test_venv
test test_venv failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_venv.py", line 103, in test_defaults
    self.assertIn('home = %s' % path, data)
AssertionError: 'home = /home/serhiy/py/cpython/Lib/..' not found in 'home = /home/serhiy/py/cpython\ninclude-system-site-packages = false\nversion = 3.7.0\n'
```


test_venv failed

1 test failed:
    test_venv

Total duration: 166 ms
Tests result: FAILURE

**Comment by vstinner** [comment]
Technically, /home/serhiy/py/cpython/Lib/../python is absolute and is a valid path. I'm not sure that it's possible to normalize sys.executable early in the Python initialization.

If we modify the site module to normalize sys.executable, it would mean that sys.executable wouldn't be normalized when using the python3 -S command line option. I dislike having subtle differences between site and no site.

I suggest to normalize sys.executable in the unit test.

**Comment by terryjreedy** [comment]
On Windows, sys.executable is normalized before or during startup. C:\\Programs\\Python36\>Lib\\..\\python -m test test_sys prints
 test_executable (__main__.SysModuleTest) ... ok

C:\\Programs\\Python36\>Lib\\..\\python -c "import sys; print(sys.executable)"
C:\\Programs\\Python36\\python.exe

**Comment by eryksun** [comment]
Terry, the Windows implementation calls GetModuleFileNameW to get the executable's fully-qualified path from the loader. However, depending on how Python is started, this could be a \\\\?\\ path, which leads to a bug in the startup code that determines the prefix path based on the landmark "lib\\os.py". Probably the easiest solution would be to normalize the executable path to remove the \\\\?\\ or \\\\.\\ prefix. This prefix isn't useful here anyway since Windows doesn't properly support running programs from long paths, not even in Windows 10. I'll open a new issue for this.

**Comment by iritkatriel** [comment]
I think that was fixed by now. On main I see

```
% Lib/../python.exe -c "import sys; print(sys.executable)"
/Users/iritkatriel/src/cpython/python.exe


% Lib/../python.exe -m test test_sys test_venv            
Using random seed: 233981894
Raised RLIMIT_NOFILE: 256 -> 1024
0:00:00 load avg: 3.10 Run 2 tests sequentially
0:00:00 load avg: 3.10 [1/2] test_sys
0:00:02 load avg: 3.09 [2/2] test_venv
Could not find platform dependent libraries <exec_prefix>

== Tests result: SUCCESS ==

All 2 tests OK.

Total duration: 10.8 sec
Total tests: run=109 skipped=10
Total test files: run=2/2
Result: SUCCESS

```
