### ISSUE TITLE
test_listcomps fails when run directly

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75210]
BPO | [31027](https://bugs.python.org/issue31027)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka
PRs | <li>python/cpython#2939</li><li>python/cpython#2945</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-07-29.18:39:40.501>
created_at = <Date 2017-07-25.12:17:21.604>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_listcomps fails when run directly'
updated_at = <Date 2017-07-29.18:39:40.500>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-29.18:39:40.500>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-07-29.18:39:40.501>
closer = 'terry.reedy'
components = ['Tests']
creation = <Date 2017-07-25.12:17:21.604>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31027
keywords = []
message_count = 4.0
messages = ['299057', '299443', '299474', '299482']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'serhiy.storchaka']
pr_nums = ['2939', '2945']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31027'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```pytb
$ ./python Lib/test/test_listcomps.py 
doctest (test.test_listcomps) ... 33 tests with zero failures
Traceback (most recent call last):
  File "Lib/test/test_listcomps.py", line 148, in <module>
    test_main(verbose=True)
  File "Lib/test/test_listcomps.py", line 142, in test_main
    support.run_doctest(test_genexps, verbose)
NameError: name 'test_genexps' is not defined
```

**Comment by terryjreedy** [comment]
On Windows, fresh 3.7, python -m test.test_listcomps fails same way.
python -m test test_listcomps is okay.

**Comment by terryjreedy** [comment]
New changeset ceb93f4540981e3f9af66bd936920186aba813fc by Terry Jan Reedy (Zackery Spytz) in branch 'master':
bpo-31027: Fix test_listcomps failure when run directly (bpo-2939)
https://github.com/python/cpython/commit/ceb93f4540981e3f9af66bd936920186aba813fc

**Comment by terryjreedy** [comment]
New changeset b26cc82b2252dd54e73661a026b32e7808fef945 by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31027: Fix test_listcomps failure when run directly (GH-2939) (bpo-2945)
https://github.com/python/cpython/commit/b26cc82b2252dd54e73661a026b32e7808fef945
