### ISSUE TITLE
test_tokenize fails when run directly

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75212]
BPO | [31029](https://bugs.python.org/issue31029)
--- | :---
Nosy | @serhiy-storchaka, @matrixise
PRs | <li>python/cpython#2865</li><li>python/cpython#2998</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-05.18:28:49.104>
created_at = <Date 2017-07-25.12:25:22.550>
labels = ['3.7', 'easy', 'type-bug', 'tests']
title = 'test_tokenize fails when run directly'
updated_at = <Date 2017-08-05.18:28:49.103>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-05.18:28:49.103>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-05.18:28:49.104>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-07-25.12:25:22.550>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31029
keywords = ['easy']
message_count = 6.0
messages = ['299062', '299064', '299066', '299080', '299081', '299791']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'matrixise']
pr_nums = ['2865', '2998']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31029'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
```pytb
$ ./python Lib/test/test_tokenize.py
Traceback (most recent call last):
  File "Lib/test/test_tokenize.py", line 1607, in <module>
    unittest.main()
NameError: name 'unittest' is not defined
```

**Comment by matrixise** [comment]
fixed, I am going to push my branch

**Comment by matrixise** [comment]
Serhiy you are free to merge my PR, and I will do the backport for 3.6

**Comment by serhiy-storchaka** [comment]
New changeset 90addd6d1c1fde4ec12a6b554d1deacfac6a879c by Serhiy Storchaka (Stéphane Wirtel) in branch 'master':
bpo-31029: test_tokenize Add missing import unittest (bpo-2865)
https://github.com/python/cpython/commit/90addd6d1c1fde4ec12a6b554d1deacfac6a879c

**Comment by serhiy-storchaka** [comment]
Thanks Stéphane.

**Comment by serhiy-storchaka** [comment]
New changeset 9cd0ef8f3b93818f0ee5318cb1fc9a1ea32e95b6 by Serhiy Storchaka (Rajath Agasthya) in branch '3.6':
bpo-31029: test_tokenize Add missing import unittest (bpo-2998)
https://github.com/python/cpython/commit/9cd0ef8f3b93818f0ee5318cb1fc9a1ea32e95b6
