### ISSUE TITLE
Tests running twice.

### ISSUE THREAD

**Issue by a24690b2-760c-4b16-8d68-d9a44e29742c** [python/cpython#75226]
BPO | [31043](https://bugs.python.org/issue31043)
--- | :---
Nosy | @methane, @musically-ut
PRs | <li>python/cpython#2891</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-26.10:59:58.802>
created_at = <Date 2017-07-26.10:20:49.309>
labels = ['3.7', 'type-bug', 'tests']
title = 'Tests running twice.'
updated_at = <Date 2017-07-26.10:59:58.801>
user = 'https://github.com/musically-ut'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-26.10:59:58.801>
actor = 'methane'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-26.10:59:58.802>
closer = 'methane'
components = ['Tests']
creation = <Date 2017-07-26.10:20:49.309>
creator = 'musically_ut'
dependencies = []
files = []
hgrepos = []
issue_num = 31043
keywords = []
message_count = 2.0
messages = ['299218', '299219']
nosy_count = 2.0
nosy_names = ['methane', 'musically_ut']
pr_nums = ['2891']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31043'
versions = ['Python 3.7']
```

</p></details>

**Comment by a24690b2-760c-4b16-8d68-d9a44e29742c** [comment]
Due to a rebase artifact (sorry!), the tests for the datetime module are being run twice:

test_datetime.py:

[...]
        cls.tearDownClass = tearDownClass
    all_test_classes.extend(test_classes)

```py
    all_test_classes.extend(test_classes)

def test_main():
    run_unittest(*all_test_classes)
[...]
```



Fix coming shortly.

**Comment by methane** [comment]
New changeset ede9084476f88f5a86c7eaaac33cdd938e4cce93 by INADA Naoki (Utkarsh Upadhyay) in branch 'master':
bpo-31043: fixed test_datetime run twice. (GH-2891)
https://github.com/python/cpython/commit/ede9084476f88f5a86c7eaaac33cdd938e4cce93
