### ISSUE TITLE
Results in section 4.4 break and continue

### ISSUE THREAD

**Issue by 46f04332-bc88-4cdc-8307-668503b45f56** [python/cpython#75220]
BPO | [31037](https://bugs.python.org/issue31037)
--- | :---
Nosy | @zware, @matrixise
Files | <li>[testresults.PNG](https://bugs.python.org/file47040/testresults.PNG "Uploaded as image/png at 2017-07-25.15:15:09 by Lisabel Leon"): My results</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-26.06:26:47.252>
created_at = <Date 2017-07-25.15:15:09.703>
labels = ['invalid', 'docs']
title = 'Results in section 4.4 break and continue'
updated_at = <Date 2017-07-27.02:53:36.551>
user = 'https://bugs.python.org/LisabelLeon'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-27.02:53:36.551>
actor = 'zach.ware'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-07-26.06:26:47.252>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-07-25.15:15:09.703>
creator = 'Lisabel Leon'
dependencies = []
files = ['47040']
hgrepos = []
issue_num = 31037
keywords = []
message_count = 5.0
messages = ['299097', '299099', '299116', '299117', '299288']
nosy_count = 4.0
nosy_names = ['docs@python', 'zach.ware', 'matrixise', 'Lisabel Leon']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31037'
versions = ['Python 3.6']
```

</p></details>

**Comment by 46f04332-bc88-4cdc-8307-668503b45f56** [comment]
The first example of this section shows different results if typed into the Python interpreter.  This is the documentation (documentation.png) and these are the results as I type it into my environment (testresults.jpg).

**Comment by matrixise** [comment]
could you be more explicit? which section ?

Thank you

**Comment by zware** [comment]
Take a look at the statement immediately following the example:

"(Yes, this is the correct code. Look closely: the else clause belongs to the for loop, not the if statement.)"

The example is correct, and is introducing the concept of an 'else' clause on a for loop.  This is very much not the first report of this that we've had, though; perhaps the 'look closely' admonition should be moved before the example?

For future reference, please copy and paste the text of your tests rather than a screenshot; not all participants can see the screenshot.

**Comment by 46f04332-bc88-4cdc-8307-668503b45f56** [comment]
Thank you Zachary for such a speedy response.
I'll paste text next time.

Rgds!
Lisabel

**Comment by zware** [comment]
We just received another report about this on docs@:

https://mail.python.org/pipermail/docs/2017-July/032314.html
