### ISSUE TITLE
Add a language switch to the Python documentation

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#75228]
BPO | [31045](https://bugs.python.org/issue31045)
--- | :---
Nosy | @terryjreedy, @vstinner, @larryhastings, @ned-deily, @methane, @JulienPalard
PRs | <li>python/cpython#2652</li><li>python/cpython#3023</li><li>python/cpython#3024</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-09.11:55:18.442>
created_at = <Date 2017-07-26.14:10:13.986>
labels = ['type-feature', '3.7', 'docs']
title = 'Add a language switch to the Python documentation'
updated_at = <Date 2018-07-02.19:56:30.983>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-02.19:56:30.983>
actor = 'larry'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-09.11:55:18.442>
closer = 'mdk'
components = ['Documentation']
creation = <Date 2017-07-26.14:10:13.986>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 31045
keywords = []
message_count = 9.0
messages = ['299234', '299447', '299458', '299831', '299910', '299911', '299912', '299931', '320910']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'vstinner', 'larry', 'ned.deily', 'methane', 'docs@python', 'mdk']
pr_nums = ['2652', '3023', '3024']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31045'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JulienPalard** [comment]
A language switch, like the actual version switch, should allow to change from a translation to another.

I mean jumping from docs.python.org/3/ to docs.python.org/fr/3/ and so on.

It's already discussed in PEP-545.

**Comment by terryjreedy** [comment]
I left out 2.7 because I don't know if the 2.7 docs have been or will be included.  

I am looking forward to this because I know someone who programs in Python and is also looking to learn 'professional' Japanese, including CS.  I myself might try the Spanish translations, if there are any.

**Comment by JulienPalard** [comment]
@terry About Japanese translation, Inada Naoki is the coordinator, their repository is created (https://github.com/python/python-docs-ja) they just have to push now.

Once this language switch fully tested / implemented / released, it will be easy to add a language. Rules to add a language to the picker are described in PEP-545 (translation have to meet criterias like having a fully translated tutorial).

Spannish translation exist too, here https://github.com/PyAr/tutorial/commits/master but I don't remember if they contacted us about porting it to docs.python.org.

FYI I try to document which language is at which step of landing to d.p.o here: https://mdk.fr/blog/python-documentation-translation.html, coordinators are documented here: https://docs.python.org/devguide/experts.html#documentation-translations

FTR I'm currently testing the new switchers locally, I should be able to remove the "WIP" soon.

**Comment by vstinner** [comment]
New changeset dff9b5f9d62aa0b23f8a255867d09d11890efd1b by Victor Stinner (Julien) in branch 'master':
bpo-31045: Language switch (bpo-2652)
https://github.com/python/cpython/commit/dff9b5f9d62aa0b23f8a255867d09d11890efd1b

**Comment by vstinner** [comment]
New changeset e93135dbb265e801c0000a19cd9c5428d57d1cf4 by Victor Stinner (Julien Palard) in branch '3.6':
bpo-31045: Language switch (bpo-2652) (bpo-3023)
https://github.com/python/cpython/commit/e93135dbb265e801c0000a19cd9c5428d57d1cf4

**Comment by vstinner** [comment]
New changeset 245dafca85097dd8b84f02b01f39f5d32091754b by Victor Stinner (Julien Palard) in branch '2.7':
bpo-31045: Language switch (bpo-2652) (bpo-3024)
https://github.com/python/cpython/commit/245dafca85097dd8b84f02b01f39f5d32091754b

**Comment by vstinner** [comment]
Even if changes are merged, I prefer to wait until the doc at docs.python.org is to date before closing the issue.

**Comment by ned-deily** [comment]
For future reference, please make sure to include current release managers on proposed changes like this since doc building and distribution is part of the release process.
