### ISSUE TITLE
Windows: os.path.isabs(os.path.abspath(" ")) == False

### ISSUE THREAD

**Issue by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [python/cpython#75230]
BPO | [31047](https://bugs.python.org/issue31047)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @timgraham, @lazka, @miss-islington
PRs | <li>python/cpython#8544</li><li>python/cpython#8549</li><li>python/cpython#8550</li><li>python/cpython#10082</li><li>python/cpython#10096</li><li>python/cpython#10097</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-25.17:47:07.708>
created_at = <Date 2017-07-26.16:47:29.883>
labels = ['OS-windows']
title = 'Windows: os.path.isabs(os.path.abspath(" ")) == False'
updated_at = <Date 2018-10-25.17:47:07.707>
user = 'https://github.com/lazka'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-25.17:47:07.707>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2018-10-25.17:47:07.708>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-07-26.16:47:29.883>
creator = 'lazka'
dependencies = []
files = []
hgrepos = []
issue_num = 31047
keywords = ['patch']
message_count = 11.0
messages = ['299253', '299266', '322633', '322636', '323229', '328322', '328328', '328448', '328463', '328464', '328465']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'Tim.Graham', 'lazka', 'miss-islington']
pr_nums = ['8544', '8549', '8550', '10082', '10096', '10097']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31047'
versions = ['Python 3.6']
```

</p></details>

**Comment by fc233844-b7d8-4db9-bc24-cd51bb8e9bda** [comment]
On Windows os.path.abspath(" ") == " "

While that's not a valid Windows path, similar invalid paths like "" or "?" etc all produce an absolute path.

Tested on 2.7 and 3.6

**Comment by eryksun** [comment]
The generic abspath implementation could be moved into the genericpath module, where it will be common to both posixpath and ntpath:

```py
    def abspath(path):
        """Return an absolute path."""
        path = os.fspath(path)
        if not isabs(path):
            if isinstance(path, bytes):
                cwd = os.getcwdb()
            else:
                cwd = os.getcwd()
            path = join(cwd, path)
        return normpath(path)
```


Then replace it in ntpath if nt.\_getfullpathname is defined, but with a fallback to the generic implementation if OSError is raised (e.g. for " "):

    try:
        from nt import _getfullpathname
    except ImportError:
        pass
    else:
        def abspath(path):
            """Return an absolute path."""
            try:
                return _getfullpathname(path)
            except OSError:
                return genericpath.abspath(path)

This \_getfullpathname version also skips the redundant fspath and normpath calls.
