### ISSUE TITLE
Python 2.7.8 Release does not update the system Path variable

### ISSUE THREAD

**Issue by 35a3b59a-1d29-4678-96d4-2a28da4e9c8c** [python/cpython#75237]
BPO | [31054](https://bugs.python.org/issue31054)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-29.02:57:41.618>
created_at = <Date 2017-07-27.07:32:14.133>
labels = ['type-feature', 'OS-windows']
title = 'Python 2.7.8 Release does not update the system Path variable'
updated_at = <Date 2017-07-29.02:57:41.617>
user = 'https://bugs.python.org/EkremSaban'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-29.02:57:41.617>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-29.02:57:41.618>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-07-27.07:32:14.133>
creator = 'Ekrem Saban'
dependencies = []
files = []
hgrepos = []
issue_num = 31054
keywords = []
message_count = 3.0
messages = ['299294', '299448', '299449']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Ekrem Saban']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31054'
versions = ['Python 2.7']
```

</p></details>

**Comment by 35a3b59a-1d29-4678-96d4-2a28da4e9c8c** [comment]
The Python 2.7.8 installer should also modify the system path variable so that typing "python" in any command window would not result in an error:
"The command "python" is either written wrong or could not be found."

**Comment by terryjreedy** [comment]
We are guessing that you are using Windows.  The 2.7.8 installer is years old and will not be changed.  The same is true for any released installer.

I believe that the 2.7 installers already give one the \*option* to change the path.  If so, this issue should be closed.  Please try out the 2.7.13 installer.

Changing the path should not be done automatically.

**Comment by zooba** [comment]
Correct. This is already in newer installers.
