### ISSUE TITLE
Documentation for Popen.poll is unclear

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#75248]
BPO | [31065](https://bugs.python.org/issue31065)
--- | :---
Nosy | @gpshead, @mdickinson, @bitdancer, @berkerpeksag, @elenaoat, @vanadium23
PRs | <li>python/cpython#3169</li><li>python/cpython#4161</li>
Files | <li>[issue31065.diff](https://bugs.python.org/file47102/issue31065.diff "Uploaded as text/plain at 2017-08-26.08:56:20 by @elenaoat")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-29.04:07:46.172>
created_at = <Date 2017-07-28.10:30:57.024>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Documentation for Popen.poll is unclear'
updated_at = <Date 2017-10-29.04:07:46.170>
user = 'https://github.com/mdickinson'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-29.04:07:46.170>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-29.04:07:46.172>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-07-28.10:30:57.024>
creator = 'mark.dickinson'
dependencies = []
files = ['47102']
hgrepos = []
issue_num = 31065
keywords = ['patch', 'easy']
message_count = 10.0
messages = ['299378', '299387', '299397', '299398', '299408', '300642', '300864', '300991', '305175', '305176']
nosy_count = 7.0
nosy_names = ['gregory.p.smith', 'mark.dickinson', 'r.david.murray', 'docs@python', 'berker.peksag', 'Elena.Oat', 'vanadium23']
pr_nums = ['3169', '4161']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31065'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by mdickinson** [comment]
The documentation for Popen.poll says:

> Check if child process has terminated. Set and return returncode attribute.

This requires the reader to guess that if the child process has not terminated, the call returns immediately, with a return value of ``None``. It would be good to be explicit about this.

**Comment by bitdancer** [comment]
Yes we can add "otherwise return None".  However it is pretty clear as is, since "poll" implies an immediate return, and if there's no return code to return, the logical value in Python to get back is None :)

**Comment by mdickinson** [comment]
Right, after following the source, I realise that `poll` is indeed returning `self.returncode` in all cases, and if the process hasn't terminated yet then `self.returncode` is still at its initial value of `None`.

I can think of other ways that the result could potentially be indicated, though: when I poll, I'm asking whether the child process is still running or not, so a boolean result wouldn't be unreasonable. Or perhaps an exception (like doing `get(block=False)` on a queue does). I don't there's a good reason not to be explicit here.

**Comment by mdickinson** [comment]
> I don't there's

I don't \*think* there's ...

Stupid fingers.

**Comment by bitdancer** [comment]
Agreed.  Explicit is good.

**Comment by 84349b2c-e6ed-40d9-b641-fab27c89e8c4** [comment]
Try to solve this issue, because it's pretty simple (:

**Comment by a1c683f7-b296-4095-93bb-30a5158fd67e** [comment]
I've added a sentence saying about the explicit return value.

**Comment by gpshead** [comment]
New changeset 006617ff7d6df3fdedcfe53e94ee2c52cc796437 by Gregory P. Smith (Ivan Chernoff) in branch 'master':
bpo-31065: Add doc about Popen.poll returning None. (bpo-3169)
https://github.com/python/cpython/commit/006617ff7d6df3fdedcfe53e94ee2c52cc796437

**Comment by berkerpeksag** [comment]
New changeset 0f1973d06e2116deafb19bbb9443b138187803c7 by Berker Peksag in branch '3.6':
bpo-31065: Add doc about Popen.poll returning None. (GH-3169)
https://github.com/python/cpython/commit/0f1973d06e2116deafb19bbb9443b138187803c7

**Comment by berkerpeksag** [comment]
I've backported 006617ff7d6df3fdedcfe53e94ee2c52cc796437  to 3.6. I think this can be closed now, thank you!
