### ISSUE TITLE
FileFinder fails to find modules for import if modules are created at runtime and don't result in a directory mtime update

### ISSUE THREAD

**Issue by f0316d50-4b01-4b1e-94db-ec2d2b122541** [python/cpython#75241]
BPO | [31058](https://bugs.python.org/issue31058)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericsnowcurrently
Files | <li>[import_tester.py](https://bugs.python.org/file47042/import_tester.py "Uploaded as text/plain at 2017-07-27.17:59:34 by pdgoins-work")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-28.07:57:42.951>
created_at = <Date 2017-07-27.17:59:34.510>
labels = ['invalid', 'type-bug', 'library']
title = "FileFinder fails to find modules for import if modules are created at runtime and don't result in a directory mtime update"
updated_at = <Date 2017-07-28.16:38:17.563>
user = 'https://bugs.python.org/pdgoins-work'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-28.16:38:17.563>
actor = 'pdgoins-work'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-28.07:57:42.951>
closer = 'ncoghlan'
components = ['Library (Lib)']
creation = <Date 2017-07-27.17:59:34.510>
creator = 'pdgoins-work'
dependencies = []
files = ['47042']
hgrepos = []
issue_num = 31058
keywords = []
message_count = 3.0
messages = ['299331', '299374', '299407']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'ncoghlan', 'eric.snow', 'pdgoins-work']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31058'
versions = ['Python 3.6']
```

</p></details>

**Comment by f0316d50-4b01-4b1e-94db-ec2d2b122541** [comment]
If modules are added to a package namespace at runtime, there is a chance that they will not be properly detected if adding the module does not also result in an update to the parent directory's st_mtime attribute.

This manifests in not being able to import the module in question, despite it clearly existing on disk and despite being to import it via a new Python interpreter if a second one is opened in parallel.

Attached is a SSCCE which reproduces this issue.  On my Windows dev machine, it works flawlessly on Python 2.7 and 3.6.  However, on a Linux VM, it works on Python 2.7 yet fails fairly consistently on Python 3.6.

I'm working around the issue by walking sys.path_importer_cache and resetting FileFinder.\_path_mtime to 0, forcing the cache to be recreated on the next call to FileFinder.find_spec().

This bug is admittedly a bit of a corner case, but I did end up spend many hours trying to figure out what was going on, so whether or not this gets fixed, I hope this may be useful info to someone.  Thanks for your attention.

**Comment by ncoghlan** [comment]
This is a known limitation of the import caching mechanism, and is the key reason https://docs.python.org/3/library/importlib.html#importlib.invalidate_caches is offered as a supported public API.

Ideally, the code that is dynamically creating packages at runtime will be calling that itself, but if it isn't, then the integrating application needs to take care of calling it at appropriate points in the program execution.

**Comment by f0316d50-4b01-4b1e-94db-ec2d2b122541** [comment]
Ack; missed that.  Thanks, and sorry for the noise.
