### ISSUE TITLE
List Comprehension Bug

### ISSUE THREAD

**Issue by 35050d63-d8fd-4701-bde2-d6b633e48187** [python/cpython#75246]
BPO | [31063](https://bugs.python.org/issue31063)
--- | :---
Nosy | @tim-one, @ronaldoussoren, @ned-deily, @stevendaprano, @hyunjaemoon
Files | <li>[Screen Shot 2017-07-27 at 9.59.40 PM.png](https://bugs.python.org/file47044/Screen%20Shot%202017-07-27%20at%209.59.40%20PM.png "Uploaded as image/png at 2017-07-28.05:10:01 by @hyunjaemoon"): Photo</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-28.05:27:18.344>
created_at = <Date 2017-07-28.05:10:01.602>
labels = ['OS-mac', 'type-bug', 'invalid']
title = 'List Comprehension Bug'
updated_at = <Date 2017-07-28.05:39:01.750>
user = 'https://github.com/hyunjaemoon'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-28.05:39:01.750>
actor = 'steven.daprano'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-28.05:27:18.344>
closer = 'tim.peters'
components = ['macOS']
creation = <Date 2017-07-28.05:10:01.602>
creator = 'hyunjaemoon'
dependencies = []
files = ['47044']
hgrepos = []
issue_num = 31063
keywords = []
message_count = 3.0
messages = ['299363', '299364', '299365']
nosy_count = 5.0
nosy_names = ['tim.peters', 'ronaldoussoren', 'ned.deily', 'steven.daprano', 'hyunjaemoon']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31063'
versions = ['Python 3.6']
```

</p></details>

**Comment by 35050d63-d8fd-4701-bde2-d6b633e48187** [comment]
Please check the photo attached.
This was tested on Python 3.6.0. It seems that there is a bug in list comprehension. The list b should include 84 as well according to the code I wrote. I believe this is a quite severe bug.
Thank you very much.

**Comment by tim-one** [comment]
This isn't a bug.  84 appears twice in the list, the first time at index 9.  The .index() method finds the first (leftmost; smallest index) occurrence.  Since 9 isn't even, the `if` test isn't satisfied, so 84 does not appear in the result.

**Comment by stevendaprano** [comment]
In the future, please do not post screenshots, please copy and paste the text. Screenshots are hard or impossible for the blind or visually impaired to see, but they can use a screen reader to work with text.
