### ISSUE TITLE
pydoc for tempfile.TemporaryDirectory should say it returns the name

### ISSUE THREAD

**Issue by d406a435-4a30-4d38-ae96-14942a320756** [python/cpython#75240]
BPO | [31057](https://bugs.python.org/issue31057)
--- | :---
Nosy | @bitdancer, @iritkatriel
PRs | <li>python/cpython#2916</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-06.19:16:21.735>
created_at = <Date 2017-07-27.15:05:53.019>
labels = ['type-feature', 'docs']
title = 'pydoc for tempfile.TemporaryDirectory should say it returns the name'
updated_at = <Date 2022-02-06.19:16:21.735>
user = 'https://bugs.python.org/ThomasThurman'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-06.19:16:21.735>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-02-06.19:16:21.735>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-07-27.15:05:53.019>
creator = 'Thomas Thurman'
dependencies = []
files = []
hgrepos = []
issue_num = 31057
keywords = []
message_count = 4.0
messages = ['299317', '299328', '299386', '411601']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'docs@python', 'Thomas Thurman', 'iritkatriel']
pr_nums = ['2916']
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31057'
versions = ['Python 3.5']
```

</p></details>

**Comment by d406a435-4a30-4d38-ae96-14942a320756** [comment]
Currently the pydoc for tempfile.TemporaryDirectory begins

"Create and return a temporary directory."

It doesn't explain anywhere \*what* it returns (in fact, it returns the name of the directory as a string). The return type is further obscured by TemporaryDirectory being a context manager.

**Comment by bitdancer** [comment]
It actually returns the path, since "name" often means the last component of the path.  Just saying "path" might be confused with pathlib, though.  So I guess we'd have to say "returning its path as a string", which sounds awkward.  The original wording is in fact accurate, since most people will understand "the directory" as the directory path as a string.  I'm not sure this change would be an improvement.  I'm not saying no, though.  I guess you'd say I'm -0 on changing it.

**Comment by bitdancer** [comment]
Boy, I wasn't thinking very clearly when I wrote that.

As pointed out on the PR, tempfile.TemporaryDirectory of course returns a TemporaryDirectory object.  That's in the nature of Python.  I was reading so poorly that I didn't even notice it was the docstring you were modifying :(

The main docs phrase this more clearly, especially the sentence that says the name can be retrieved from the name property (and I see I was wrong, it does use 'name', not 'path').  We don't want to copy all of the text from there, but it could be used as a model to improve the phrasing.
