### ISSUE TITLE
Startup failure if executable is a \\?\ path on Windows

### ISSUE THREAD

**Issue by eryksun** [python/cpython#75257]
BPO | [31074](https://bugs.python.org/issue31074)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @eryksun, @zooba
Superseder | <li>bpo-38322: Azure Pipelines: appx tests fail: init_fs_encoding: failed to get the Python codec of the filesystem encoding</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-10-22.23:18:35.124>
created_at = <Date 2017-07-29.06:36:00.359>
labels = ['interpreter-core', '3.7', 'OS-windows', 'type-crash']
title = 'Startup failure if executable is a \\\\?\\ path on Windows'
updated_at = <Date 2019-10-22.23:18:35.123>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-22.23:18:35.123>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-10-22.23:18:35.124>
closer = 'vstinner'
components = ['Interpreter Core', 'Windows']
creation = <Date 2017-07-29.06:36:00.359>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 31074
keywords = []
message_count = 4.0
messages = ['299459', '299467', '299487', '355177']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'shubha_bloodhound']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '38322'
type = 'crash'
url = 'https://bugs.python.org/issue31074'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by eryksun** [comment]
search_for_prefix in [PC/getpathp.c](https://github.com/python/cpython/blob/main/PC/getpathp.c) sets the wrong path when Python is started with a \\\\?\\ path on Windows, which results in the following crash:

```pycon
    >>> subprocess.call(r'"\\?\C:\Program Files\Python36\python.exe"')
    Fatal Python error: Py_Initialize: unable to load the file system codec
    ModuleNotFoundError: No module named 'encodings'
```


    Current thread 0x00000b40 (most recent call first):
    3221226505

The problem is due to the implementation of join(), which calls PathCchCombineEx, which strips the \\?\ prefix from the joined path. Consequently in gotlandmark(), setting `prefix[n] = '\0'` nulls the wrong index because the value of n includes the original \\?\ prefix. 

    Breakpoint 0 hit
    python36_d!gotlandmark:
    00000000`6cc1a920 48894c2408      mov     qword ptr [rsp+8],rcx
            ss:000000c2`9a9ee920={python36_d!prefix (00000000`6cf697d0)}
    1:005> du python36_d!prefix
    00000000`6cf697d0  "\\?\C:\Program Files\Python36"

    1:005> pc
    python36_d!gotlandmark+0x15:
    00000000`6cc1a935 e8e60a0000      call    python36_d!wcsnlen_s (00000000`6cc1b420)
    1:005> pc
    python36_d!gotlandmark+0x2b:
    00000000`6cc1a94b e890010000      call    python36_d!join (00000000`6cc1aae0)
    1:005> p
    python36_d!gotlandmark+0x30:
    00000000`6cc1a950 33d2            xor     edx,edx
    1:005> du python36_d!prefix
    00000000`6cf697d0  "C:\Program Files\Python36\lib\os"
    00000000`6cf69810  ".py"

    1:005> pt
    python36_d!gotlandmark+0x7b:
    00000000`6cc1a99b c3              ret
    1:005> du python36_d!prefix
    00000000`6cf697d0  "C:\Program Files\Python36\lib"

I think the simplest solution is to remove the \\\\?\\ prefix from the executable path that's returned by GetModuleFileNameW in get_progpath(). AFAIK, no version of Windows can reliably run programs from long paths, and the current MAXPATHLEN (256) doesn't allow it anyway. The only reason to use \\\\?\\ for the executable path would be to avoid the normal DOS/Windows path normalization rules -- e.g. removing trailing dots and spaces or using DOS device names such as "con.exe". That's not really a practical concern.

**Comment by zooba** [comment]
Sounds like the right fix. We should increase the maximum path length though, since 3.6 and later can work with much longer paths on Win10 through normal APIs and without prefix.

**Comment by e7a5fbd1-93de-490e-9ce0-43299ddcffad** [comment]
May I take resolve this issue and submit a patch ?
