### ISSUE TITLE
*args unpacking can mask TypeErrors

### ISSUE THREAD

**Issue by 89042997-fe19-49d2-aba2-a4861a6d999e** [python/cpython#75254]
BPO | [31071](https://bugs.python.org/issue31071)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @pochmann
PRs | <li>python/cpython#2957</li><li>python/cpython#2991</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-08-03.09:18:25.635>
created_at = <Date 2017-07-28.16:03:22.305>
labels = ['interpreter-core', 'type-bug', '3.7']
title = '*args unpacking can mask TypeErrors'
updated_at = <Date 2017-08-03.09:18:25.634>
user = 'https://github.com/pochmann'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-03.09:18:25.634>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-08-03.09:18:25.635>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-07-28.16:03:22.305>
creator = 'Stefan Pochmann'
dependencies = []
files = []
hgrepos = []
issue_num = 31071
keywords = []
message_count = 4.0
messages = ['299402', '299411', '299690', '299694']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'Stefan Pochmann']
pr_nums = ['2957', '2991']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31071'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 89042997-fe19-49d2-aba2-a4861a6d999e** [comment]
Python 3.6 makes it sound like maps aren't iterable:

```pycon
>>> map(str, *map(int, [[]]))
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    map(str, *map(int, [[]]))
TypeError: type object argument after * must be an iterable, not map
```


More, including a likely explanation, in my question and its answer here:
https://stackoverflow.com/q/45363330/1672429

Apparently the TypeError from int([]) gets mistaken for a TypeError indicating non-iterability of the map object.

**Comment by bitdancer** [comment]
Thanks for the report.  Retitling because this has nothing to do with map:

```pycon
>>> def foo(*args):
...     raise TypeError('fake')
...     yield 1
... 
>>> foo(1, *foo())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() argument after * must be an iterable, not generator
>>> foo(*foo())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in foo
TypeError: fake
```

**Comment by serhiy-storchaka** [comment]
New changeset 25e4f779d7ae9f37a1933cb5cbfad06e673c01f9 by Serhiy Storchaka in branch 'master':
bpo-31071: Avoid masking original TypeError in call with * unpacking (bpo-2957)
https://github.com/python/cpython/commit/25e4f779d7ae9f37a1933cb5cbfad06e673c01f9

**Comment by serhiy-storchaka** [comment]
New changeset 946a0b69e217ff22a6c056047eab42053e9a2d5f by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31071: Avoid masking original TypeError in call with * unpacking (GH-2957) (bpo-2991)
https://github.com/python/cpython/commit/946a0b69e217ff22a6c056047eab42053e9a2d5f
