### ISSUE TITLE
reduce takes iterable, not just sequence

### ISSUE THREAD

**Issue by 89042997-fe19-49d2-aba2-a4861a6d999e** [python/cpython#75265]
BPO | [31082](https://bugs.python.org/issue31082)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ncoghlan, @serhiy-storchaka, @pochmann, @corona10, @ZackerySpytz
PRs | <li>python/cpython#20796</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-06-28.06:41:38.949>
created_at = <Date 2017-07-30.21:06:27.401>
labels = ['type-feature', '3.7', 'docs']
title = 'reduce takes iterable, not just sequence'
updated_at = <Date 2020-06-28.06:41:38.949>
user = 'https://github.com/pochmann'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-28.06:41:38.949>
actor = 'corona10'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-06-28.06:41:38.949>
closer = 'corona10'
components = ['Documentation']
creation = <Date 2017-07-30.21:06:27.401>
creator = 'Stefan Pochmann'
dependencies = []
files = []
hgrepos = []
issue_num = 31082
keywords = ['patch']
message_count = 6.0
messages = ['299520', '299768', '299771', '299825', '299974', '372496']
nosy_count = 8.0
nosy_names = ['rhettinger', 'terry.reedy', 'ncoghlan', 'docs@python', 'serhiy.storchaka', 'Stefan Pochmann', 'corona10', 'ZackerySpytz']
pr_nums = ['20796']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31082'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 89042997-fe19-49d2-aba2-a4861a6d999e** [comment]
functools.reduce has a parameter called "iterable" and it only needs to be an iterable, not a sequence.

The paragraph documenting it says "sequence" instead of "iterable" six times:
https://docs.python.org/3/library/functools.html#functools.reduce

The help shown by executing "help(functools.reduce)" in Python additionally actually names the parameter "sequence" in the signature.

**Comment by terryjreedy** [comment]
Serhiy, given that the parameters of reduce are currently positional only (by experiment, it has not gotten the C.A. treatment yet), can 'sequence' in the signature in the docstring be changes to 'iterable'?

**Comment by serhiy-storchaka** [comment]
Yes, I think it can. But be aware that "sequence" is used not only in the signature, but in following description.

The term "sequence" in the documentation and the docstring looks to me like a synonym of "iterable", not a reference to collections.abc.Sequence. I don't know how the wording can be improved. Maybe looking at the documentation of builtins filter, map, zip, and itertools functions can help.

**Comment by ncoghlan** [comment]
Checking older versions of the docs, it looks like we simply haven't reworded those docs since Python 2.0 (when the "list" of the 1.5 docs became "sequence" for 2.0).

So I think the most appropriate resolution here would be to replace the current use of "sequence" with "iterable" in both the code and the documentation.

**Comment by serhiy-storchaka** [comment]
The term "sequence" also is used in the docstring of itertools.starmap() (actually an iterable is accepted).
