### ISSUE TITLE
Release Build Failure on Ubuntu 14.04

### ISSUE THREAD

**Issue by 8487f21f-228a-4041-9f76-116ed9c43da7** [python/cpython#75264]
BPO | [31081](https://bugs.python.org/issue31081)
--- | :---
Nosy | @pitrou, @scolby33
Files | <li>[ccMFxPIP.out](https://bugs.python.org/file47048/ccMFxPIP.out "Uploaded as text/plain at 2017-07-30.18:59:17 by @scolby33"): Preprocessed source as output by gcc</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-30.19:19:07.515>
created_at = <Date 2017-07-30.18:59:51.601>
labels = ['build']
title = 'Release Build Failure on Ubuntu 14.04'
updated_at = <Date 2017-07-30.19:19:07.514>
user = 'https://github.com/scolby33'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-30.19:19:07.514>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-30.19:19:07.515>
closer = 'pitrou'
components = ['Build']
creation = <Date 2017-07-30.18:59:51.601>
creator = 'scolby33'
dependencies = []
files = ['47048']
hgrepos = []
issue_num = 31081
keywords = []
message_count = 4.0
messages = ['299507', '299509', '299510', '299511']
nosy_count = 2.0
nosy_names = ['pitrou', 'scolby33']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31081'
versions = ['Python 3.6']
```

</p></details>

**Comment by 8487f21f-228a-4041-9f76-116ed9c43da7** [comment]
After downloading and decompressing the latest 3.6.2 source release, I attempted to build as follows:

```sh
    $ ./configure --enable-optimizations --enable-ipv6  # seems fine
    $ make -s -j$(nproc)
```


At the end of the build I have this error reported:

    Failed to build these modules:
    _socket
    
    
    Following modules built successfully but were removed because they could not be imported:
    _asyncio              _ssl

Scrolling up, I see that the \_asyncio and \_ssl failures are due to \_socket being missing. Scrolling up further, I see several warnings and errors, to wit:

    \*a series of tests that seem to go okay*
    0:05:14 load avg: 0.62 [161/405] test_hash
    0:05:15 load avg: 0.65 [162/405] test_hashlib
    Fatal Python error: Segmentation fault
    
    Current thread 0x00002afbece8e380 (most recent call first):
      File "/usr/local/src/python/Python-3.6.2/Lib/test/support/__init__.py", line 1508 in gc_collect
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/save_env.py", line 271 in \_\_exit__
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/runtest.py", line 172 in runtest_inner
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/runtest.py", line 137 in runtest
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/main.py", line 374 in run_tests_sequential
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/main.py", line 454 in run_tests
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/main.py", line 530 in \_main
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/main.py", line 504 in main
      File "/usr/local/src/python/Python-3.6.2/Lib/test/libregrtest/main.py", line 573 in main
      File "/usr/local/src/python/Python-3.6.2/Lib/test/regrtest.py", line 46 in \_main
      File "/usr/local/src/python/Python-3.6.2/Lib/test/regrtest.py", line 50 in \<module\>
      File "/usr/local/src/python/Python-3.6.2/Lib/runpy.py", line 85 in \_run_code
      File "/usr/local/src/python/Python-3.6.2/Lib/runpy.py", line 193 in \_run_module_as_main
    Segmentation fault (core dumped)
    
After this, the build seems to think all the tests are done and continues with "Rebuilding with profile guided optimizations:". There are a lot of warnings here, mostly about missing execution counts, which I assume comes from 3/4 of the tests not being run. Later on, however, we have this gem:

    /usr/local/src/python/Python-3.6.2/Modules/socketmodule.c:7693:1: internal compiler error: in edge_badness, at ipa-inline.c:895
     }
     ^
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-4.8/README.Bugs> for instructions.
    Preprocessed source stored into /tmp/ccMFxPIP.out file, please attach this to your bugreport.
    ERROR: Cannot create report: [Errno 17] File exists: '/var/crash/_usr_lib_gcc_x86_64-linux-gnu_4.8_cc1.1000.crash'

I have gcc (Ubuntu 4.8.4-2ubuntu\~14.04.3) 4.8.4

I'm new to building Python and even newer to reporting bugs here, so please let me know what additional information I should provide or steps I should take.

**Comment by pitrou** [comment]
Well, as the log you posted shows, this seems to be a gcc bug.  Of course, I don't know if the gcc project still accepts bug reports for gcc 4.8, but we're unlikely to be able to help you here.

**Comment by 8487f21f-228a-4041-9f76-116ed9c43da7** [comment]
You make a fair point. I didn't realize that my version of gcc was so far behind. Perhaps I ought to seek out a binary distribution of Python 3.6, since upgrading the whole of gcc doesn't seem quite worth my time.

If you don't think there is anything else to be done on Python's end, feel free to mark this resolved in some way.

(And indeed, the entire 4.8 series is no longer maintained.)

**Comment by pitrou** [comment]
Well, if it's really a compiler bug, there's nothing we can do against it.  You should still be able to build without the --with-optimizations flag, which will give you a build perhaps 20% slower but still fully functional.
