### ISSUE TITLE
mathematically wrong results from int and long bit_length methods

### ISSUE THREAD

**Issue by 8a836185-2bfa-415f-85ca-5ab0210e3727** [python/cpython#75262]
BPO | [31079](https://bugs.python.org/issue31079)
--- | :---
Nosy | @skrah

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-30.18:02:45.015>
created_at = <Date 2017-07-30.16:27:18.107>
labels = ['3.7', 'invalid', 'type-bug', 'library']
title = 'mathematically wrong results from int and long bit_length methods'
updated_at = <Date 2017-07-30.18:02:45.013>
user = 'https://bugs.python.org/vinsci'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-30.18:02:45.013>
actor = 'skrah'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-30.18:02:45.015>
closer = 'skrah'
components = ['Library (Lib)']
creation = <Date 2017-07-30.16:27:18.107>
creator = 'vinsci'
dependencies = []
files = []
hgrepos = []
issue_num = 31079
keywords = []
message_count = 4.0
messages = ['299500', '299501', '299505', '299506']
nosy_count = 2.0
nosy_names = ['skrah', 'vinsci']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31079'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8a836185-2bfa-415f-85ca-5ab0210e3727** [comment]
It takes as many bits to store the number 0 as the number 1, but the implementation claims it takes no bits at all to store a 0.

```pycon
>>> (1).bit_length() == (0).bit_length() and True or False
False
```


It takes one extra bit to store the sign for negative numbers, but this isn't reflected in the implementations.

```pycon
>>> (-1).bit_length() == 1 + (1).bit_length() and True or False
False
```

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Look at [Include/longobject.h](https://github.com/python/cpython/blob/main/Include/longobject.h) and https://docs.python.org/3/library/stdtypes.html?highlight=bit_length#int.bit_length .

**Comment by 8a836185-2bfa-415f-85ca-5ab0210e3727** [comment]
```pycon
>>> (0).bit_length.__doc__
"int.bit_length() -> int\n\nNumber of bits necessary to represent self in binary.\n>>> bin(37)\n'0b100101'\n>>> (37).bit_length()\n6"
```


The library documentation has clearly been written in disregard of the advertised functionality in the docstrings of the methods.

The documentation is just echoing the flaws of the unit tests.

For the Python 3 variant of this issue, it can be added that the library documentation wrongly states that the method is "New in version 3.1.".

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Thank you for your expertise.
