### ISSUE TITLE
Allow `logging.config.fileConfig` to accept kwargs

### ISSUE THREAD

**Issue by bfb2a162-b350-4256-9379-5a389cce9c84** [python/cpython#75263]
BPO | [31080](https://bugs.python.org/issue31080)
--- | :---
Nosy | @vsajip, @Preston-Landers
PRs | <li>python/cpython#2979</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-02.21:22:00.379>
created_at = <Date 2017-07-30.17:10:10.388>
labels = ['type-feature', 'library']
title = 'Allow `logging.config.fileConfig` to accept kwargs'
updated_at = <Date 2017-08-03.08:43:28.349>
user = 'https://github.com/Preston-Landers'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-03.08:43:28.349>
actor = 'vinay.sajip'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-02.21:22:00.379>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-07-30.17:10:10.388>
creator = 'planders'
dependencies = []
files = []
hgrepos = []
issue_num = 31080
keywords = []
message_count = 6.0
messages = ['299502', '299586', '299632', '299671', '299677', '299691']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'planders']
pr_nums = ['2979']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31080'
versions = []
```

</p></details>

**Comment by bfb2a162-b350-4256-9379-5a389cce9c84** [comment]
The function `logging.config.fileConfig` accepts `args` but it would be nice if it also accepted `kwargs`.

A simple patch seems to do it:

	diff --git a/Lib/logging/config.py b/Lib/logging/config.py
	index d692514..4672b48 100644
	--- a/Lib/logging/config.py
	+++ b/Lib/logging/config.py
	@@ -145,7 +145,9 @@ def \_install_handlers(cp, formatters):
				 klass = \_resolve(klass)
			 args = section["args"]
			 args = eval(args, vars(logging))
	-        h = klass(*args)
	\+        kwargs = section.get("kwargs", '{}')
	\+        kwargs = eval(kwargs, vars(logging))
	\+        h = klass(*args, \*\*kwargs)
			 if "level" in section:
				 level = section["level"]
				 h.setLevel(level)


Unless there are any objections I plan to submit a pull request. In my use case I have a Pyramid service which
uses `concurrent-log-handler` and it seems better to be able to name keyword args for file configuration.

**Comment by bfb2a162-b350-4256-9379-5a389cce9c84** [comment]
This is the current state of my patch:

https://github.com/python/cpython/compare/master...Preston-Landers:bpo-31080-fileconfig

It makes both `args` and `kwargs` optional in the config file. (Obviously, the actual handler may require args.)

**Comment by vsajip** [comment]
Yes, seems reasonable, but don't change [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) directly in your patch - this is now done using the "blurb" tool. Installed into a Python 3 environment using "pip install blurb".

**Comment by vsajip** [comment]
New changeset 6ea56d2ebcae69257f8dd7af28c357b25bf394c3 by Vinay Sajip (Preston Landers) in branch 'master':
bpo-31080: Allowed logging.config.fileConfig() to accept both args and kwargs. (GH-2979)
https://github.com/python/cpython/commit/6ea56d2ebcae69257f8dd7af28c357b25bf394c3

**Comment by bfb2a162-b350-4256-9379-5a389cce9c84** [comment]
A colleague pointed out that I used single quotes in the defaults where the line uses double quotes for another argument. I'm not sure if this is considered a problem but I could submit an update if it is.

**Comment by vsajip** [comment]
No, that's OK - leave it as is, I'll consider it when next visiting the area.
