### ISSUE TITLE
Windows Installer Version

### ISSUE THREAD

**Issue by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [python/cpython#75260]
BPO | [31077](https://bugs.python.org/issue31077)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @damon-atkins

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-29.21:06:02.201>
created_at = <Date 2017-07-29.16:43:13.913>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'Windows Installer Version'
updated_at = <Date 2017-07-29.21:06:02.200>
user = 'https://github.com/damon-atkins'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-29.21:06:02.200>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-29.21:06:02.201>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-07-29.16:43:13.913>
creator = 'damon-atkins'
dependencies = []
files = []
hgrepos = []
issue_num = 31077
keywords = []
message_count = 2.0
messages = ['299475', '299486']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'damon-atkins']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31077'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [comment]
The Windows installer for example titles the software as
Display Name:Python 3.5.3 (64-bit)
Display Version: 3.5.3150.0
The default install folder is
C:\\Program Files\\Python35

There is no consistency

It looks like the 3150 been shorten to 3
If you look at Python 2.7.2 it has a display version of 2.7.13150

Suggest
Display Name:Python 3.5 (64-bit)
Display Version: 3.5.3150.0
C:\\Program Files\\Python3.5 or C:\\Program Files\\Python3.5.3150
OR
Display Name:Python 3.5.3150 (64-bit)
Display Version: 3.5.3150.0
C:\\Program Files\\Python3.5.3150
OR
Display Name:Python 3.5.3 (64-bit)
Display Version: 3.5.3.3150
C:\\Program Files\\Python3.5.3

Alse seems that Python 3 installer is placing one entery in the 'Users' registry for uninstall and the rest of the entries in 'System' registry for uninstall

I suggest if the files are installed in C:\\Program Files then their should be no  'User' registry entries.

**Comment by zooba** [comment]
Please file separate bugs for each of your concerns, and ensure Python 3.6/3.7 and 2.7 are separate as these are fundamentally different installers and will have different bugs.

Other versions will not be changed at this point.
