### ISSUE TITLE
QueueHandler not formatting messages

### ISSUE THREAD

**Issue by 93826b83-4f3a-4b66-93fb-36cbcc3bbf6f** [python/cpython#75267]
BPO | [31084](https://bugs.python.org/issue31084)
--- | :---
Nosy | @vsajip, @favll, @emontnemery
PRs | <li>python/cpython#2954</li><li>python/cpython#9537</li><li>python/cpython#31355</li>
Files | <li>[queue_handler_bug.py](https://bugs.python.org/file47052/queue_handler_bug.py "Uploaded as text/plain at 2017-07-30.21:52:10 by @favll")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-01.18:18:30.585>
created_at = <Date 2017-07-30.21:52:10.801>
labels = ['3.7', 'type-bug', 'library']
title = 'QueueHandler not formatting messages'
updated_at = <Date 2022-02-15.10:20:46.632>
user = 'https://github.com/favll'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-15.10:20:46.632>
actor = 'emontnemery'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-01.18:18:30.585>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2017-07-30.21:52:10.801>
creator = 'favll'
dependencies = []
files = ['47052']
hgrepos = []
issue_num = 31084
keywords = []
message_count = 2.0
messages = ['299525', '299626']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'favll', 'emontnemery']
pr_nums = ['2954', '9537', '31355']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31084'
versions = ['Python 3.7']
```

</p></details>

**Comment by 93826b83-4f3a-4b66-93fb-36cbcc3bbf6f** [comment]
QueueHandler does not seem to format messages when setting a Formatter and attaching the QueueHandler to a logger. See attachement for a concise example.

According to the internal documentation of the QueueHandler's prepare method it is expected that self.format(record) will format the message and put the message into record.message. However, this is not the case and self.format(record) only returns the message. So this should be ab easy fix.

**Comment by vsajip** [comment]
New changeset adfe3440f65dfd6cf4463db6cd02cdc78e77ce17 by Vinay Sajip (favll) in branch 'master':
bpo-31084: QueueHandler now formats messages correctly. (GH-2954)
https://github.com/python/cpython/commit/adfe3440f65dfd6cf4463db6cd02cdc78e77ce17
