### ISSUE TITLE
regrtest.py: "${test_file_name} skipped" message printed twice for each ${test_file_name}

### ISSUE THREAD

**Issue by 80036ac5-bb84-4d39-8416-02cd8e51707d** [python/cpython#75271]
BPO | [31088](https://bugs.python.org/issue31088)
--- | :---
Nosy | @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = <Date 2019-06-24.13:23:55.875>
created_at = <Date 2017-07-31.12:59:50.734>
labels = ['invalid', '3.7', 'tests']
title = 'regrtest.py: "${test_file_name} skipped" message printed twice for each ${test_file_name}'
updated_at = <Date 2019-06-24.13:23:55.870>
user = 'https://bugs.python.org/Arfrever'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-24.13:23:55.870>
actor = 'vstinner'
assignee = 'vstinner'
closed = True
closed_date = <Date 2019-06-24.13:23:55.875>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-07-31.12:59:50.734>
creator = 'Arfrever'
dependencies = []
files = []
hgrepos = []
issue_num = 31088
keywords = []
message_count = 4.0
messages = ['299555', '299587', '299630', '346398']
nosy_count = 2.0
nosy_names = ['vstinner', 'Arfrever']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31088'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
Since some change during last 3 months, regrtest.py on 2.7 branch prints "${test_file_name} skipped" message twice for each ${test_file_name}, firstly directly after given ${test_file_name}, and secondly after the following test.

Example:

0:00:06 [ 17/401] test_abc
0:00:06 [ 18/401] test_abstract_numbers
0:00:06 [ 19/401] test_aepack
test_aepack skipped -- No module named aetypes
0:00:06 [ 20/401] test_aifc -- test_aepack skipped
0:00:06 [ 21/401] test_al
test_al skipped -- No module named al
0:00:06 [ 22/401] test_anydbm -- test_al skipped
0:00:08 [ 23/401] test_applesingle
test_applesingle skipped -- No module named MacOS
0:00:08 [ 24/401] test_argparse -- test_applesingle skipped
0:00:14 [ 25/401] test_array
0:00:15 [ 26/401] test_ascii_formatd
0:00:15 [ 27/401] test_ast

**Comment by vstinner** [comment]
The output is correct. First, regrtest says that the test is running. Then
the test is skipped and a message is logged. Finally, the test result is
logged: the test was skipped.

Using -j0, the output is less surprising ;-)

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
This bug in output actually occurs in sequential mode.

Apparently problem can be reproduced in 3.\*, but only if [Tools/scripts/run_tests.py](https://github.com/python/cpython/blob/main/Tools/scripts/run_tests.py) is changed to run tests sequentially. (That problem reported as bpo-31098.)

Example from 3.7:

0:00:42 load avg: 1.89 [ 11/405] test_cprofile
0:00:42 load avg: 1.89 [ 12/405] test_winsound
test_winsound skipped -- Use of the 'audio' resource not enabled
0:00:43 load avg: 1.89 [ 13/405] test_pickletools -- test_winsound skipped (resource denied)
0:00:46 load avg: 1.82 [ 14/405] test_select
0:00:58 load avg: 1.54 [ 15/405] test_bisect
