### ISSUE TITLE
remove dead code in PyErr_GivenExceptionMatches()

### ISSUE THREAD

**Issue by scoder** [python/cpython#75274]
BPO | [31091](https://bugs.python.org/issue31091)
--- | :---
Nosy | @pitrou, @scoder, @serhiy-storchaka
PRs | <li>python/cpython#2963</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-07-31.20:30:21.339>
created_at = <Date 2017-07-31.19:24:27.609>
labels = ['interpreter-core', '3.7', 'performance']
title = 'remove dead code in PyErr_GivenExceptionMatches()'
updated_at = <Date 2017-07-31.20:30:21.338>
user = 'https://github.com/scoder'
```

bugs.python.org fields:
```python
activity = <Date 2017-07-31.20:30:21.338>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-07-31.20:30:21.339>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-07-31.19:24:27.609>
creator = 'scoder'
dependencies = []
files = []
hgrepos = []
issue_num = 31091
keywords = []
message_count = 4.0
messages = ['299579', '299580', '299584', '299585']
nosy_count = 3.0
nosy_names = ['pitrou', 'scoder', 'serhiy.storchaka']
pr_nums = ['2963']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31091'
versions = ['Python 3.7']
```

</p></details>

**Comment by scoder** [comment]
```c
PyObject *exception, *value, *tb;
        PyErr_Fetch(&exception, &value, &tb);
        /* PyObject_IsSubclass() can recurse and therefore is
           not safe (see test_bad_getattr in test.pickletester). */
        res = PyType_IsSubtype((PyTypeObject *)err, (PyTypeObject *)exc);
        /* This function must not fail, so print the error here */
        if (res == -1) {
            PyErr_WriteUnraisable(err);
            res = 0;
        }
        PyErr_Restore(exception, value, tb);
```


According to the comment, there was previously a call to PyObject_IsSubclass() involved which could fail, but since it was replaced with a call to PyType_IsSubtype(), it can no longer fail.
See pull request.

**Comment by scoder** [comment]
Looks like the switch from PyObject_IsSubclass() to PyType_IsSubtype() was made during the original Py3 development cycle. It should thus be safe to assume that the semantics are "as designed". :)

What about applying the patch also to 3.6 and older?

**Comment by serhiy-storchaka** [comment]
New changeset e4c06bcca358c6dcb6393a75a1589ff6a2d45cde by Serhiy Storchaka (scoder) in branch 'master':
bpo-31091: Remove dead code in PyErr_GivenExceptionMatches(). (bpo-2963)
https://github.com/python/cpython/commit/e4c06bcca358c6dcb6393a75a1589ff6a2d45cde

**Comment by serhiy-storchaka** [comment]
This is just a cleaning up. There is no bug in the old code. Usually such kind of changes are not backported.
