### ISSUE TITLE
itertools.islice not accepting np.int64

### ISSUE THREAD

**Issue by 3af4cbad-e47b-486c-87be-c9adc5ba2c2a** [python/cpython#75280]
BPO | [31097](https://bugs.python.org/issue31097)
--- | :---
Nosy | @rhettinger, @terryjreedy, @mdickinson, @braaannigan
Superseder | <li>bpo-30537: Using PyNumber_AsSsize_t in itertools.islice</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-05.03:02:31.085>
created_at = <Date 2017-08-01.13:23:06.701>
labels = ['type-bug', 'library']
title = 'itertools.islice not accepting np.int64'
updated_at = <Date 2017-08-05.03:07:56.748>
user = 'https://github.com/braaannigan'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-05.03:07:56.748>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-05.03:02:31.085>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-08-01.13:23:06.701>
creator = 'braaannigan'
dependencies = []
files = []
hgrepos = []
issue_num = 31097
keywords = []
message_count = 6.0
messages = ['299617', '299618', '299620', '299625', '299628', '299769']
nosy_count = 4.0
nosy_names = ['rhettinger', 'terry.reedy', 'mark.dickinson', 'braaannigan']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30537'
type = 'behavior'
url = 'https://bugs.python.org/issue31097'
versions = ['Python 3.6']
```

</p></details>

**Comment by 3af4cbad-e47b-486c-87be-c9adc5ba2c2a** [comment]
The error arises when this code is used:
itertools.islice( [3, 4, 5], np.int64(2) )

but not with this
itertools.islice([3,4,5], 2)

**Comment by rhettinger** [comment]
See http://bugs.python.org/issue30537

**Comment by 3af4cbad-e47b-486c-87be-c9adc5ba2c2a** [comment]
Thanks Ray. The use case is here:
https://stackoverflow.com/questions/45356718/saving-matplotlib-animation-leads-to-error/45438057#45438057

I'm going to suggest a workaround in matplotlib for the moment.  Changing type in this use case shouldn't be a big issue, it only happens once for each animation created.

**Comment by mdickinson** [comment]
That actually looks as though it may be worth a bug report to the matplotlib folks.

**Comment by 3af4cbad-e47b-486c-87be-c9adc5ba2c2a** [comment]
Hi Mark - I've done that here:
https://github.com/matplotlib/matplotlib/issues/8973

Liam

**Comment by terryjreedy** [comment]
LB, an exception is a graceful shutdown, not a crash.  A crash is a seg fault, core dump, or an OS message 'Your app has stopped unexpectedly'.

In bpo-30537, the exception was regarded as expected, not a bug, and changing islice to accept np ints was regarded as an enhancement, and therefore limited to 3.7
