### ISSUE TITLE
deheader: double #incude of the same file

### ISSUE THREAD

**Issue by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [python/cpython#75285]
BPO | [31102](https://bugs.python.org/issue31102)
--- | :---
Nosy | @serhiy-storchaka, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-12.21:45:26.747>
created_at = <Date 2017-08-02.09:51:51.421>
labels = ['type-feature', 'invalid', 'build']
title = 'deheader: double #incude of the same file'
updated_at = <Date 2018-06-12.21:45:26.737>
user = 'https://bugs.python.org/dilyanpalauzov'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-12.21:45:26.737>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-12.21:45:26.747>
closer = 'Mariatta'
components = ['Build']
creation = <Date 2017-08-02.09:51:51.421>
creator = 'dilyan.palauzov'
dependencies = []
files = []
hgrepos = []
issue_num = 31102
keywords = []
message_count = 3.0
messages = ['299650', '299655', '319404']
nosy_count = 3.0
nosy_names = ['dilyan.palauzov', 'serhiy.storchaka', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31102'
versions = ['Python 3.6']
```

</p></details>

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
For cpython 3.6 deheader (http://www.catb.org/esr/deheader/) reports:

[Mac/Tools/pythonw.c](https://github.com/python/cpython/blob/main/Mac/Tools/pythonw.c) has more than one inclusion of \<Python.h\>
[Modules/_sre.c](https://github.com/python/cpython/blob/main/Modules/_sre.c) has more than one inclusion of "sre_lib.h"
[Modules/_testcapimodule.c](https://github.com/python/cpython/blob/main/Modules/_testcapimodule.c) has more than one inclusion of "testcapi_long.h"
[Modules/_threadmodule.c](https://github.com/python/cpython/blob/main/Modules/_threadmodule.c) has more than one inclusion of "structmember.h"
[Modules/expat/xmltok.c](https://github.com/python/cpython/blob/main/Modules/expat/xmltok.c) has more than one inclusion of "asciitab.h"
[Modules/expat/xmltok.c](https://github.com/python/cpython/blob/main/Modules/expat/xmltok.c) has more than one inclusion of "latin1tab.h"
[Modules/expat/xmltok.c](https://github.com/python/cpython/blob/main/Modules/expat/xmltok.c) has more than one inclusion of "utf8tab.h"
[Modules/faulthandler.c](https://github.com/python/cpython/blob/main/Modules/faulthandler.c) has more than one inclusion of \<signal.h\>
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/codecs.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/undef.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/fastsearch.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/split.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/ucs2lib.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/ucs1lib.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/partition.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/find_max_char.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/ucs4lib.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/asciilib.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/find.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/replace.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/localeutil.h"
[Objects/unicodeobject.c](https://github.com/python/cpython/blob/main/Objects/unicodeobject.c) has more than one inclusion of "stringlib/count.h"

**Comment by serhiy-storchaka** [comment]
"sre_lib.h" and "stringlib/*.h" are included multiple times for purpose. They are template files and different inclusions instantiate implementations for specific kind of Unicode strings.

"testcapi_long.h" also is a template file.

[Modules/expat/xmltok.c](https://github.com/python/cpython/blob/main/Modules/expat/xmltok.c) is imported file. And it include some header files multiple times for purpose.
