### ISSUE TITLE
unable to open python on Windows

### ISSUE THREAD

**Issue by 583de14a-d648-4f9e-a6c8-d90cea26e93f** [python/cpython#75283]
BPO | [31100](https://bugs.python.org/issue31100)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-09.23:37:29.616>
created_at = <Date 2017-08-02.01:07:08.958>
labels = ['expert-installation', 'OS-windows', 'type-crash']
title = 'unable to open python on Windows'
updated_at = <Date 2021-09-09.23:37:29.615>
user = 'https://bugs.python.org/KennethGriffin'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-09.23:37:29.615>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-09-09.23:37:29.616>
closer = 'steve.dower'
components = ['Installation', 'Windows']
creation = <Date 2017-08-02.01:07:08.958>
creator = 'Kenneth Griffin'
dependencies = []
files = []
hgrepos = []
issue_num = 31100
keywords = []
message_count = 5.0
messages = ['299640', '299641', '299783', '401534', '401537']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Kenneth Griffin', 'brobby crobby', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31100'
versions = ['Python 3.6']
```

</p></details>

**Comment by 583de14a-d648-4f9e-a6c8-d90cea26e93f** [comment]
tried installing multiple versions of 3.6 on windows. the installation works. However, when trying to put python --version in the command line of powershell, i get a pop up that says python has stopped working.

**Comment by 290f9f80-17ba-434b-b276-565baeb344cc** [comment]
i get this message while using git bash
$ python
C:/Users/simrash2000/AppData/Local/Programs/Python/Python36/python.exe: error while loading shared libraries: api-ms-win-crt-heap-l1-1-0.dll: cannot open shared object file: No such file or directory

**Comment by zooba** [comment]
This probably means that your system failed to install the C Runtime, but not badly enough that it actually reported an error.

First try rebooting, and if that doesn't work then search for the VisualC++ 2015 Redistributable installer and run that.
