### ISSUE TITLE
os.remove() auto add \ in Windows2012R2

### ISSUE THREAD

**Issue by f2100d5e-2b50-450e-82b8-d42ade3b131e** [python/cpython#75284]
BPO | [31101](https://bugs.python.org/issue31101)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-02.07:42:15.290>
created_at = <Date 2017-08-02.07:25:45.738>
labels = ['invalid', 'OS-windows', 'performance']
title = 'os.remove() auto add \\ in Windows2012R2'
updated_at = <Date 2017-08-02.07:42:15.289>
user = 'https://bugs.python.org/007hengxyx'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-02.07:42:15.289>
actor = 'paul.moore'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-02.07:42:15.290>
closer = 'paul.moore'
components = ['Windows']
creation = <Date 2017-08-02.07:25:45.738>
creator = '007hengxyx'
dependencies = []
files = []
hgrepos = []
issue_num = 31101
keywords = []
message_count = 2.0
messages = ['299645', '299646']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', '007hengxyx']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31101'
versions = ['Python 2.7']
```

</p></details>

**Comment by f2100d5e-2b50-450e-82b8-d42ade3b131e** [comment]
I need to remove a file in python at Windows2012R2, but, os.remove()auto add \\ in each seq.

code:
#coding=utf-8
import os
dir_path='d:\\c\\d\\e\\t\\c\\t.xf'
os.remove(dir_path)


```pycon
result:
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> ================================ RESTART 
```
================================
>\>\> 

```pytb
Traceback (most recent call last):
  File "D:\test\script\test.py", line 4, in <module>
    os.remove(dir_path)
WindowsError: [Error 3] The system cannot find the path specified: 'd:\\c\\d\\e\t\\c\t.xf'
>>>
```

**Comment by pfmoore** [comment]
There are two problems with your code and bug report:

1. By using a single quoted string, some of the backslashes in the path are being interpreted as starting a special character (specifically \\t is interpreted as a tab character). You should either double the backslashes to prevent this interpretation (dir_path='d:\\\\c\\\\d\\\\e\\\\t\\\\c\\\\t.xf'), use forward slashes (dir_path='d:/c/d/e/t/c/t.xf') or use a raw string (dir_path=r'd:\\c\\d\\e\\t\\c\\t.xf').

2. You're reporting that Python "auto adds \\". It doesn't, it's just that the repr of the string shows a single quoted string with backslashes doubled - that's the standard repr for strings.

So, Python is behaving as expected, and there's no bug here.
