### ISSUE TITLE
os.posix_fallocate() generate exception with errno 0

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#75289]
BPO | [31106](https://bugs.python.org/issue31106)
--- | :---
Nosy | @vstinner, @larryhastings, @ned-deily, @asvetlov, @socketpair, @serhiy-storchaka, @koobs, @Mariatta, @izbyshev
PRs | <li>python/cpython#3000</li><li>python/cpython#3088</li><li>python/cpython#4101</li>
Files | <li>[koobs-freebsd-current.non-debug.3.x.build.16.stdio.txt](https://bugs.python.org/file47454/koobs-freebsd-current.non-debug.3.x.build.16.stdio.txt "Uploaded as text/plain at 2018-02-21.03:05:04 by @koobs")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-24.06:39:10.970>
created_at = <Date 2017-08-02.15:03:06.789>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'os.posix_fallocate() generate exception with errno 0'
updated_at = <Date 2018-05-26.22:03:05.681>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-26.22:03:05.681>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-24.06:39:10.970>
closer = 'ned.deily'
components = ['Library (Lib)']
creation = <Date 2017-08-02.15:03:06.789>
creator = 'socketpair'
dependencies = []
files = ['47454']
hgrepos = []
issue_num = 31106
keywords = ['patch']
message_count = 19.0
messages = ['299660', '299740', '299741', '299742', '299746', '299747', '299830', '300244', '300259', '300264', '300266', '304876', '308955', '311429', '312453', '312475', '313013', '317538', '317772']
nosy_count = 9.0
nosy_names = ['vstinner', 'larry', 'ned.deily', 'asvetlov', 'socketpair', 'serhiy.storchaka', 'koobs', 'Mariatta', 'izbyshev']
pr_nums = ['3000', '3088', '4101']
priority = None
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31106'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
\===
os.posix_fallocate(os.open('qwe.qwe', os.O_RDONLY|os.O_CREAT), 0, 1024\*1024)
\===

generates OSError with errno 0. Suppose this happen due to O_RDONLY flag.

strace :

\====
open("qwe.qwe", O_RDONLY|O_CREAT|O_CLOEXEC, 0777) = 3
fallocate(3, 0, 0, 1048576)             = -1 EBADF (Bad file descriptor)
\====


Python 3.5.3, Ubuntu 64-bit.

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
man posix_fallocate:

RETURN VALUE

posix_fallocate() returns zero on success, or an error number on failure.  Note that errno is not set.

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
Also, EINTR will not be caught too (!)

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
https://github.com/python/cpython/pull/3000

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
All checks passed.

Please merge.

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
posix_fadvise() is also affected :(

Fixed in this patch.

**Comment by Mariatta** [comment]
Adding Larry who is listed as posix expert.

**Comment by larryhastings** [comment]
New changeset d4b93e21c2664d6a78e0656e7a7be0807be1c352 by larryhastings (Коренберг Марк) in branch 'master':
bpo-31106: Fix handling of erros in posix_fallocate() and posix_fadvise() (bpo-3000) (bpo-3000)
https://github.com/python/cpython/commit/d4b93e21c2664d6a78e0656e7a7be0807be1c352

**Comment by serhiy-storchaka** [comment]
Needed a NEWS entry.

**Comment by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [comment]
If I understand right, Python 3.5 will not be fixed with this pathc. Right ?

If yes, I will tell Debian maintainers to backport this patch to Python 3.5, which is shipped with latest stable Debian 9.

**Comment by larryhastings** [comment]
You understand correctly.  It won't be backported to Python 3.5.

**Comment by serhiy-storchaka** [comment]
Марк, do you mind to add a NEWS entry?
