### ISSUE TITLE
posixpath.normpath truncating forward slashes from URL

### ISSUE THREAD

**Issue by 6ad80a69-1e14-4740-923c-aa9bfa34da4a** [python/cpython#75287]
BPO | [31104](https://bugs.python.org/issue31104)
--- | :---
Nosy | @serhiy-storchaka, @govindsmenokee
PRs | <li>python/cpython#2985</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-02.11:38:18.177>
created_at = <Date 2017-08-02.11:14:07.774>
labels = ['invalid', 'type-bug', 'library']
title = 'posixpath.normpath truncating forward slashes from URL'
updated_at = <Date 2017-08-02.11:38:18.143>
user = 'https://github.com/govindsmenokee'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-02.11:38:18.143>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-02.11:38:18.177>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-08-02.11:14:07.774>
creator = 'govindsmenokee'
dependencies = []
files = []
hgrepos = []
issue_num = 31104
keywords = []
message_count = 2.0
messages = ['299653', '299654']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'govindsmenokee']
pr_nums = ['2985']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31104'
versions = ['Python 2.7']
```

</p></details>

**Comment by 6ad80a69-1e14-4740-923c-aa9bfa34da4a** [comment]
Handle unwanted truncation of forward slash in case of URL input for normpath function.
For Example - path = 'https://google.com'
The current output of normpath function would be - 'https:/google.com'
After changes the output would be - 'https://google.com'

**Comment by serhiy-storchaka** [comment]
Is the string 'https://google.com' an URL or a path? If it is a path, posixpath.normpath() correctly collapses duplicated slashes. If it is an URL, using posixpath.normpath() is not correct.
