### ISSUE TITLE
Windows Installer Product does not include micro version in display name

### ISSUE THREAD

**Issue by 44577252-695b-49f0-801a-822a5229b79a** [python/cpython#75286]
BPO | [31103](https://bugs.python.org/issue31103)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @damon-atkins
Files | <li>[3.6.2.png](https://bugs.python.org/file47056/3.6.2.png "Uploaded as image/png at 2017-08-02.10:11:17 by Markus Kramer"): Product Version 3.6.2150.0</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-03-18.22:59:52.783>
created_at = <Date 2017-08-02.10:04:48.381>
labels = ['expert-installation', '3.9', '3.10', '3.8', 'type-feature', 'invalid', 'OS-windows']
title = 'Windows Installer Product does not include micro version in display name'
updated_at = <Date 2021-03-18.22:59:52.782>
user = 'https://bugs.python.org/MarkusKramer'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-18.22:59:52.782>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-03-18.22:59:52.783>
closer = 'steve.dower'
components = ['Installation', 'Windows']
creation = <Date 2017-08-02.10:04:48.381>
creator = 'Markus Kramer'
dependencies = []
files = ['47056']
hgrepos = []
issue_num = 31103
keywords = []
message_count = 13.0
messages = ['299651', '299652', '299658', '299676', '299715', '299716', '299717', '299721', '299757', '299758', '299784', '388978', '389047']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'damon-atkins', 'Markus Kramer']
pr_nums = []
priority = 'low'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31103'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by 44577252-695b-49f0-801a-822a5229b79a** [comment]
Each Windows installation has a “product version”.

The Windows installer python-3.6.2.exe has product version "3.6.2150.0"  (accessible with context menu / Properties / Details).

This causes at least 2 problems:
 - Automated software inventory relies on product version and therefore does not detect version 3.6.2
 - Microsoft installation guidelines require the first three fields to be smaller than 256.

Proposed alternatives for the value of product version:
- "3.6.2.0" to indicate the final release build.
- "3.6.2.150" to indicate the build number. The build number may be higher than 256, but this is unusual for a final release.



Side note: 
This is a sub-problem of http://bugs.python.org/issue31077

**Comment by 44577252-695b-49f0-801a-822a5229b79a** [comment]
Screenshot of Product Version 3.6.2150.0

**Comment by zooba** [comment]
Can you link to those guidelines please? Microsoft release plenty of software with version numbers over 256.

Also, since people already rely on the current scheme, we'd need a very compelling reason to break them. I don't believe you've made that case yet.

**Comment by eryksun** [comment]
The docs [1] are clear that this property must be of the form major.minor.build. It can include at least one additional field, which the installer ignores. The major and minor version numbers can be up to 255, and the build number can be up to 65535. Python's ProductVersion property complies with this:

```py
    db = msilib.OpenDatabase('core.msi', msilib.MSIDBOPEN_READONLY)
    v = db.OpenView("select * from Property where Property='ProductVersion'")
    v.Execute(None)
    r = v.Fetch()
```


```pycon
    >>> r.GetString(2)
    '3.6.2150.0'
```


It would be unorthodox to use the build version field for Python's micro release version number. I don't see why it's really important since micro releases are ABI compatible for in-place upgrades.

[1]: https://msdn.microsoft.com/en-us/library/windows/desktop/aa370859

**Comment by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [comment]
Hi Guys,

The reason I raise the original is for all those configuration management tools which need the version number.

In the uninstall registry is very much an inconsistent.
\*Anything with a Display Name in the registry (name in the GUI) will be listed.
* Their are two places for version information.
** 1 "large int (DWORD) version number" called "version" store across several integers in the registry, which supports \<0-255\>.\<0-255\>.\<0-65535\> this is not visible in the GUI.
** display version, which is a string, and can be set to anything, this is visible in the GUI.

"display version" is set most of the time.
"large int version number" not always

"large int (DWORD) version number" I have actual see software which as created this as a text string, which is just wrong. e.g. Google Chrome, however Google Update Helper does the right thing.

People see the "display version" so this needs to match the version of python.  I would expect most configuration management tools to use "display version" before "large int (DWORD) version number"

The following is based on installing python 3.6.2 (3.6.2150 not sure what this means)

display name should be "Python 3.6 (64-bit)" if you wish to encourage  only single version of 3.6 to be installed. or "Python 3.6.2 (64-bit)" if you wish to allow many versions of 3.6 to be installed. "3.6" matches closer to what happens in the unix/linux world (/usr/lib/python2.6).
 
display version string should 3.6.2 or 3.6.2.2150 never 3.6.2150 
"large int (DWORD) version number" should not be set, but you could force it to 3.6.2 given your unlikely to go higher than 255.255.65535 the automatic builds might not like doing this, might be easier not to set it.

**Comment by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [comment]
The python 3.5.3 (64-bit) installer currently adds most of the components installed in the "MACHINE" Registry all but 1 item (2 entries)

"python 3.5.3 (64-bit)" software entry which it places in both the 32 bit and also the 64 bit registry.  It should be in the "MACHINE" Registry and only in the 64 bit registry, which is the default for 64 bit installer. 

For example a 32 bit installer would place "python 3.5.3 (32-bit)" only in the 32 bit part of the registry.

**Comment by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [comment]
Because this entry "python 3.5.3 (64-bit)" is the USER part of the registry, only the user who installs python can see that it is installed.

**Comment by zooba** [comment]
There's an existing bug for the registration going to the wrong place. It requires changes to the Wix toolset to resolve. No need to conflate it with this issue.

As far as I can tell, the problem here is just the version string displayed in Programs and Features? Correct?

**Comment by 44577252-695b-49f0-801a-822a5229b79a** [comment]
Steve, yes: from my point of view, the version in "Programs and Features" should be  3.6.2 or 3.6.2.0 or 3.6.2.150. 


Eryk, thank you for your explanation - I had a wrong memory about the third field in ProductVersion to be the micro version and learned something. 


If that would be helpful, I could change the title of this issue.

**Comment by a128b6da-4a85-4b01-8d85-dd95b1e7e19c** [comment]
To Summaries
A)
Name/DisplayName "Python 3.X (64-bit)" or "Python 3.X.Y" (64-bit) "Python 3.X (64-bit)" would match the install directory which is \\Python3X (this should be \\Python3.X)

Display Version should start with 3.X.Y or 3.X.Y.\<build number\>

version DWORD in the registry does not need to be set but if set would need to be 3.X.Y
B) Registry being placed in in the wrong location
HKU\\\<User-SID\>\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall\\{GUID}
should be going into
HKLM\\Software\\Microsoft\\Windows\\CurrentVersion\\Uninstall

C) Suggest the default install dir is
"c:\\Program Files\\Python3.6" instead of "c:\\Program Files\\Python36"

**Comment by zooba** [comment]
This issue is about A.

B has a separate issue. C will not be changed. Please don't bother bringing them up again here, it's just a distraction.
