### ISSUE TITLE
Timer error pop from empty deque/list

### ISSUE THREAD

**Issue by f0046e67-8192-4c61-bf35-88a7236331ae** [python/cpython#75282]
BPO | [31099](https://bugs.python.org/issue31099)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-01.22:25:49.065>
created_at = <Date 2017-08-01.20:50:29.486>
labels = ['invalid', 'library']
title = 'Timer error pop from empty deque/list'
updated_at = <Date 2017-08-01.22:25:49.065>
user = 'https://bugs.python.org/RandyHenderson'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-01.22:25:49.065>
actor = 'Randy Henderson'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-01.22:25:49.065>
closer = 'Randy Henderson'
components = ['Library (Lib)']
creation = <Date 2017-08-01.20:50:29.486>
creator = 'Randy Henderson'
dependencies = []
files = []
hgrepos = []
issue_num = 31099
keywords = []
message_count = 3.0
messages = ['299634', '299636', '299638']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Randy Henderson']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31099'
versions = ['Python 3.6']
```

</p></details>

**Comment by f0046e67-8192-4c61-bf35-88a7236331ae** [comment]
Even when a deque is populated in the Timer setup parameter, the interpreter gives "IndexError: pop from an empty deque".  IndexError is generated for lists as well.

```pycon
>>> Timer(stmt='d.popleft()',setup='d=deque([1,2,3])',globals=globals()).timeit()
Traceback (most recent call last):
  File "<pyshell#75>", line 1, in <module>
 Timer(stmt='d.popleft()',setup='d=deque([1,2,3])',globals=globals()).timeit()
  File "C:\Program Files\Python\Python36\lib\timeit.py", line 178, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
IndexError: pop from an empty deque
```

**Comment by bitdancer** [comment]
Perhaps I'm missing something, but isn't this to be expected?  Timer will run d.popleft() repeatedly until you get the error you see because the list is empty.  Are you thinking that setup is run each time?  That would defeat its purpose.

**Comment by f0046e67-8192-4c61-bf35-88a7236331ae** [comment]
You're right.  I was expecting the code in stmt to be run only once, but I
just discovered in the documentation that the default is for it to be run
one million times.  I provided the argument 'number=1' to the timeit()
method and am now getting the behavior I expected.  I'll remove/close the
bug entry.  Sorry -- newbie!
