### ISSUE TITLE
cannot run module with double quotes

### ISSUE THREAD

**Issue by ced91e00-1f49-46ee-87a3-56d0c9c3aba8** [python/cpython#75295]
BPO | [31112](https://bugs.python.org/issue31112)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-03.04:58:23.276>
created_at = <Date 2017-08-03.03:11:54.651>
labels = ['invalid', 'OS-windows', 'performance']
title = 'cannot run module with double quotes'
updated_at = <Date 2017-08-03.04:58:23.274>
user = 'https://bugs.python.org/ericshenjs'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-03.04:58:23.274>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-03.04:58:23.276>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2017-08-03.03:11:54.651>
creator = 'ericshenjs'
dependencies = []
files = []
hgrepos = []
issue_num = 31112
keywords = []
message_count = 2.0
messages = ['299681', '299682']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'ericshenjs']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31112'
versions = ['Python 3.6']
```

</p></details>

**Comment by ced91e00-1f49-46ee-87a3-56d0c9c3aba8** [comment]
(vPy3X64) test01@NJNU f:\\Src\\localCode\\python\\py3_eric
> python "-m locust.main -V"
f:\\SDKs\\Python\\vPy3X64\\Scripts\\python.exe: Error while finding module specification for ' locust.main -V' (ModuleNotFoundError: No module named ' locust')

(vPy3X64) test01@NJNU f:\\Src\\localCode\\python\\py3_eric
> python -m locust.main -V
[2017-08-03 10:53:19,111] NJNU/INFO/stdout: Locust 0.8a2
[2017-08-03 10:53:19,111] NJNU/INFO/stdout:

(vPy3X64) test01@NJNU f:\\Src\\localCode\\python\\py3_eric
> python -V
Python 3.6.1 :: Anaconda 4.4.0 (64-bit)

**Comment by eryksun** [comment]
Python uses the C runtime wmain entry point, which parses the commandline string into an argument array using documented rules [1]. The quoted string "-m locust.main -V" is passed as a single argument instead of the expected three arguments: ["-m", "locust.main", "-V"].

[1]: https://msdn.microsoft.com/en-us/library/17w5ykft
