### ISSUE TITLE
Small typo in plistlib docs

### ISSUE THREAD

**Issue by 98c96024-603a-4828-88d2-575bd6f282e2** [python/cpython#75293]
BPO | [31110](https://bugs.python.org/issue31110)
--- | :---
Nosy | @serhiy-storchaka, @googlebleh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-03.14:43:54.875>
created_at = <Date 2017-08-02.19:06:01.148>
labels = ['type-feature', '3.7', 'docs']
title = 'Small typo in plistlib docs'
updated_at = <Date 2017-08-03.14:43:54.873>
user = 'https://github.com/googlebleh'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-03.14:43:54.873>
actor = 'cwee'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-03.14:43:54.875>
closer = 'cwee'
components = ['Documentation']
creation = <Date 2017-08-02.19:06:01.148>
creator = 'cwee'
dependencies = []
files = []
hgrepos = []
issue_num = 31110
keywords = []
message_count = 4.0
messages = ['299668', '299684', '299685', '299710']
nosy_count = 3.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'cwee']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31110'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 98c96024-603a-4828-88d2-575bd6f282e2** [comment]
Starting with 3.4, the docs for plistlib have had a typo:
https://docs.python.org/3.4/library/plistlib.html#plistlib.readPlist
https://docs.python.org/3.5/library/plistlib.html#plistlib.readPlist
https://docs.python.org/3.6/library/plistlib.html#plistlib.readPlist
https://docs.python.org/3.7/library/plistlib.html#plistlib.readPlist

Functions `readPlist` and `readPlistFromBytes` reference the `__getitem_` method, which should be `__getitem__`.

I'd be happy to submit a PR if there's a repo for the site's documentation.

**Comment by serhiy-storchaka** [comment]
https://github.com/python/cpython

**Comment by serhiy-storchaka** [comment]
3.4 and 3.5 can take only security fixes. Create a PR for the master branch. After merging it the changes can be cherry-picked into the 3.6 branch. See details in Python Developer’s Guide (https://docs.python.org/devguide/).

**Comment by 98c96024-603a-4828-88d2-575bd6f282e2** [comment]
Just noticed the note was removed in commit edef358ed6d in the latest 3.7 docs. Closing issue.

Thanks for the intro on how to contribute though!
