### ISSUE TITLE
copyreg does not properly mangle __slots__ names

### ISSUE THREAD

**Issue by 089d1745-ea22-4f29-b30c-4e658c1dc24d** [python/cpython#75290]
BPO | [31107](https://bugs.python.org/issue31107)
--- | :---
Nosy | @serhiy-storchaka, @ShaneHarvey
PRs | <li>python/cpython#2989</li><li>python/cpython#3003</li><li>python/cpython#3004</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-08-05.15:24:03.870>
created_at = <Date 2017-08-02.18:53:14.769>
labels = ['3.7', 'type-bug', 'library']
title = 'copyreg does not properly mangle __slots__ names'
updated_at = <Date 2017-08-05.15:24:03.861>
user = 'https://github.com/ShaneHarvey'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-05.15:24:03.861>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-08-05.15:24:03.870>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-08-02.18:53:14.769>
creator = 'ShaneHarvey'
dependencies = []
files = []
hgrepos = []
issue_num = 31107
keywords = []
message_count = 4.0
messages = ['299665', '299737', '299787', '299788']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'ShaneHarvey']
pr_nums = ['2989', '3003', '3004']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31107'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 089d1745-ea22-4f29-b30c-4e658c1dc24d** [comment]
This line in copyreg.\_slotnames does not properly calculate mangled attribute names:
https://github.com/python/cpython/blob/v3.6.2/Lib/copyreg.py#L131

The problem is that it does not strip leading underscores from the class name:

```pycon
>>> class _LeadingUnderscoreClassName(object):
...     __slots__ = ("__bar",)
...
>>> import copy_reg
>>> copy_reg._slotnames(_LeadingUnderscoreClassName)
['__LeadingUnderscoreClassName__bar']
```


The result is that copy, pickle, and anything else that relies on \_slotnames() do not work on classes with leading underscores and private \_\_slots__. This bug is present in all versions of Python.

**Comment by serhiy-storchaka** [comment]
New changeset c4c9866064f03646c686d7e08b00aeb203c35c19 by Serhiy Storchaka (Shane Harvey) in branch 'master':
bpo-31107: Fix copyreg mangled slot names calculation. (bpo-2989)
https://github.com/python/cpython/commit/c4c9866064f03646c686d7e08b00aeb203c35c19

**Comment by serhiy-storchaka** [comment]
New changeset 4795ba857ef2a89e6b477285df961672106a1792 by Serhiy Storchaka (Shane Harvey) in branch '3.6':
[3.6] bpo-31107: Fix copyreg mangled slot names calculation. (GH-2989) (bpo-3003)
https://github.com/python/cpython/commit/4795ba857ef2a89e6b477285df961672106a1792

**Comment by serhiy-storchaka** [comment]
New changeset 88ffff5ddbb8692ecb2c661aa29000dbde9eff8c by Serhiy Storchaka (Shane Harvey) in branch '2.7':
[2.7] bpo-31107: Fix copyreg mangled slot names calculation. (GH-2989). (bpo-3004)
https://github.com/python/cpython/commit/88ffff5ddbb8692ecb2c661aa29000dbde9eff8c
