### ISSUE TITLE
zipimport argument clinic conversion

### ISSUE THREAD

**Issue by 9ebd57ca-3afd-4f57-a549-6a1ad70de606** [python/cpython#75292]
BPO | [31109](https://bugs.python.org/issue31109)
--- | :---
Nosy | @Yhg1s, @brettcannon, @larryhastings, @serhiy-storchaka, @jarondl
PRs | <li>python/cpython#2990</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-19.17:09:39.922>
created_at = <Date 2017-08-02.19:05:24.076>
labels = ['3.7', 'type-feature', 'library', 'expert-argument-clinic']
title = 'zipimport argument clinic conversion'
updated_at = <Date 2017-08-19.17:09:39.921>
user = 'https://github.com/jarondl'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-19.17:09:39.921>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-19.17:09:39.922>
closer = 'brett.cannon'
components = ['Library (Lib)', 'Argument Clinic']
creation = <Date 2017-08-02.19:05:24.076>
creator = 'jarondl'
dependencies = []
files = []
hgrepos = []
issue_num = 31109
keywords = []
message_count = 4.0
messages = ['299667', '299687', '299704', '300524']
nosy_count = 5.0
nosy_names = ['twouters', 'brett.cannon', 'larry', 'serhiy.storchaka', 'jarondl']
pr_nums = ['2990']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31109'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9ebd57ca-3afd-4f57-a549-6a1ad70de606** [comment]
Convert zipimport to use the argument clinic.
I will submit the PR shortly.

**Comment by serhiy-storchaka** [comment]
If zipimport will be reimplemented in Python (bpo-25711) this change will be not needed.

**Comment by 9ebd57ca-3afd-4f57-a549-6a1ad70de606** [comment]
Oh that's a cool idea which I was not aware of.

**Comment by brettcannon** [comment]
New changeset 02f3b7d5ab2206d256879e5a8a34f560218ed397 by Brett Cannon (Yaron de Leeuw) in branch 'master':
bpo-31109: Convert zipimport to use Argument Clinic (GH-2990)
https://github.com/python/cpython/commit/02f3b7d5ab2206d256879e5a8a34f560218ed397
