### ISSUE TITLE
add __contains__ for list_iterator (and others) for better performance

### ISSUE THREAD

**Issue by 9008ea77-dbea-496f-ba6b-b73570cfd4db** [python/cpython#75291]
BPO | [31108](https://bugs.python.org/issue31108)
--- | :---
Nosy | @rhettinger, @terryjreedy, @pitrou, @serhiy-storchaka, @sir-sigurd
PRs | <li>python/cpython#2988</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-31.07:07:26.714>
created_at = <Date 2017-08-02.18:53:46.470>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'add __contains__ for list_iterator (and others) for better performance'
updated_at = <Date 2017-08-31.07:07:26.713>
user = 'https://github.com/sir-sigurd'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-31.07:07:26.713>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-31.07:07:26.714>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-08-02.18:53:46.470>
creator = 'sir-sigurd'
dependencies = []
files = []
hgrepos = []
issue_num = 31108
keywords = []
message_count = 6.0
messages = ['299666', '299686', '299773', '299774', '301022', '301040']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'pitrou', 'serhiy.storchaka', 'sir-sigurd']
pr_nums = ['2988']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31108'
versions = ['Python 3.7']
```

</p></details>

**Comment by 9008ea77-dbea-496f-ba6b-b73570cfd4db** [comment]
> python -mtimeit -s "l = list(range(100000))" "l[-1] in l"
1000 loops, best of 3: 1.34 msec per loop
> python -mtimeit -s "l = list(range(100000))" "l[-1] in iter(l)"                                
1000 loops, best of 3: 1.59 msec per loop

**Comment by serhiy-storchaka** [comment]
The patch adds almost 40 line of the code and increases the performance of not well famous feature at best by 10-20%. Adding an optimization for every new iterator type will add a comparable quantity of the code. I think this is too high cost.

Using a common template implementation for iterators (bpo-27438) would decrease the relative cost of this feature.

**Comment by serhiy-storchaka** [comment]
Terry, this proposition doesn't change the behavior. It moves the iterator forward during searching. The only effect is inlining \_\_next__ in a loop and getting rid of the overhead of few indirections and calls.

**Comment by terryjreedy** [comment]
Sorry, I mistakenly assumed, without carefully checking the C code, that the speedup was from checking the underlying collection, without advancing the iterator.  I presume that " ++it-\>it_index;" is the statement to the contrary. I should have either asked or found this sooner.  I unlinked the noisy comment.

**Comment by pitrou** [comment]
I don't think I've ever used `in` on an iterator.  I didn't even expect it to work, and would not consider its use a good practice.

**Comment by rhettinger** [comment]
I recommend rejecting this proposal
