### ISSUE TITLE
SSLContext.wrap_socket() throws OSError with errno == 0

### ISSUE THREAD

**Issue by 7cb04df6-5f46-4078-bf67-48262ccd0118** [python/cpython#75305]
BPO | [31122](https://bugs.python.org/issue31122)
--- | :---
Nosy | @gpshead, @tiran, @jab, @bdarnell, @vadmium, @dimaqq, @Safihre, @xgid, @miss-islington, @remilapeyre, @shevisjohnson
PRs | <li>python/cpython#18772</li><li>python/cpython#21888</li><li>python/cpython#21889</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2020-08-15.17:06:01.924>
created_at = <Date 2017-08-04.19:16:41.456>
labels = ['expert-SSL', '3.8', 'type-bug', '3.7', '3.9']
title = 'SSLContext.wrap_socket() throws OSError with errno == 0'
updated_at = <Date 2020-08-15.17:45:01.059>
user = 'https://bugs.python.org/nikratio'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-15.17:45:01.059>
actor = 'miss-islington'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2020-08-15.17:06:01.924>
closer = 'gregory.p.smith'
components = ['SSL']
creation = <Date 2017-08-04.19:16:41.456>
creator = 'nikratio'
dependencies = []
files = []
hgrepos = []
issue_num = 31122
keywords = ['patch']
message_count = 18.0
messages = ['299759', '299766', '299793', '328093', '332779', '336732', '363318', '363322', '363329', '363333', '364067', '367335', '375471', '375478', '375479', '375481', '375482', '375484']
nosy_count = 12.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'jab', 'nikratio', 'Ben.Darnell', 'martin.panter', 'Dima.Tisnek', 'Safihre', 'xgdomingo', 'miss-islington', 'remi.lapeyre', 'shevis']
pr_nums = ['18772', '21888', '21889']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31122'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 7cb04df6-5f46-4078-bf67-48262ccd0118** [comment]
With a particularly atrocious network connection, I often get the following exception:

  File "/usr/lib/python3/dist-packages/dugong/__init__.py", line 503, in connect
    self.\_sock = self.ssl_context.wrap_socket(self.\_sock, server_hostname=server_hostname)
  File "/usr/lib/python3.5/ssl.py", line 385, in wrap_socket
    \_context=self)
  File "/usr/lib/python3.5/ssl.py", line 760, in \_\_init__
    self.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 996, in do_handshake
    self.\_sslobj.do_handshake()
  File "/usr/lib/python3.5/ssl.py", line 641, in do_handshake
    self.\_sslobj.do_handshake()
OSError: [Errno 0] Error

I don't think an error with errno == 0 should ever be raised by Python.

**Comment by vadmium** [comment]
It might help if you explained what “atrocities” are happening on your network. Is there a proxy or man-in-the-middle (or the remote peer) that shuts down TCP connections?

If so, perhaps this is similar to bpo-10808. From my memory, in that case an OS “recv” or “read” call returns zero to indicate a connection was shut down. Python and/or Open SSL correctly treats this as an error, but then assumes “errno” is valid. Perhaps Python should be raising SSLEOFError in this situation.

Maybe also check the “suppress_ragged_eofs” setting, but I think that only affects later stages, after the handshake succeeds.

**Comment by 7cb04df6-5f46-4078-bf67-48262ccd0118** [comment]
Regarding "atrocious connection": I wish I knew, but I have no control of the connection. All I can tell is that there are frequent disconnects, occasional latency spikes, my remote ip address seems to change frequently (while the apparent local one stays as-is, so presumably some NAT in between), temporary bandwidth drops, etc.
