### ISSUE TITLE
shelve.open of temporary file fails with error "anydbm.error: db type could not be determined"

### ISSUE THREAD

**Issue by c0f2ff81-094d-4e92-b1c6-279077c13a1c** [python/cpython#75308]
BPO | [31125](https://bugs.python.org/issue31125)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-06.13:01:52.062>
created_at = <Date 2017-08-05.16:26:59.156>
labels = ['3.7', 'type-bug', 'library']
title = 'shelve.open of temporary file fails with error "anydbm.error: db type could not be determined"'
updated_at = <Date 2017-08-06.13:02:58.588>
user = 'https://bugs.python.org/StephenLarroque'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-06.13:02:58.588>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-06.13:01:52.062>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-08-05.16:26:59.156>
creator = 'Stephen Larroque'
dependencies = []
files = []
hgrepos = []
issue_num = 31125
keywords = []
message_count = 3.0
messages = ['299790', '299797', '299798']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Stephen Larroque']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31125'
versions = ['Python 2.7', 'Python 3.3', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by c0f2ff81-094d-4e92-b1c6-279077c13a1c** [comment]
This is a followup of bpo-23174.

When using `shelve.open(tempfile.mkstemp()[1])`, the shelve (or anydbm or dumbdbm) fail with "anydbm.error: db type could not be determined".

Instead, the module could detect the file is empty and use it as if it were not existing before ('c' or 'n' flag). For the moment, there is no way around except creating the temporary file and then delete it.

**Comment by bitdancer** [comment]
No, it should not.  A DBM is not necessarily a single file.  What you should be doing is creating a temporary \*directory*, and opening your DB inside that.

**Comment by bitdancer** [comment]
By the way, if you want to open a doc issue with a suggestion of how to clarify this in the docs, that would be welcome.
