### ISSUE TITLE
[2.7] Python 64 bit _ssl compile fails due missing buildinf_amd64.h

### ISSUE THREAD

**Issue by e6330703-be9f-426c-807a-4e38421ac008** [python/cpython#75303]
BPO | [31120](https://bugs.python.org/issue31120)
--- | :---
Nosy | @vstinner, @tiran, @zware, @hirenvadalia
Files | <li>[openssl-1.0.2j.diff](https://bugs.python.org/file47057/openssl-1.0.2j.diff "Uploaded as text/plain at 2017-08-04.13:21:42 by @hirenvadalia"): Patch for openssl-1.0.2j on http://svn.python.org/projects/external/openssl-1.0.2j/</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zware'
closed_at = <Date 2018-06-09.19:08:09.363>
created_at = <Date 2017-08-04.13:02:50.157>
labels = ['build']
title = '[2.7] Python 64 bit _ssl compile fails due missing buildinf_amd64.h'
updated_at = <Date 2018-06-09.19:08:09.363>
user = 'https://github.com/hirenvadalia'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-09.19:08:09.363>
actor = 'zach.ware'
assignee = 'zach.ware'
closed = True
closed_date = <Date 2018-06-09.19:08:09.363>
closer = 'zach.ware'
components = ['Build']
creation = <Date 2017-08-04.13:02:50.157>
creator = 'hirenvadalia'
dependencies = []
files = ['47057']
hgrepos = []
issue_num = 31120
keywords = ['patch']
message_count = 5.0
messages = ['299743', '299744', '299745', '300578', '303424']
nosy_count = 4.0
nosy_names = ['vstinner', 'christian.heimes', 'zach.ware', 'hirenvadalia']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31120'
versions = ['Python 2.7']
```

</p></details>

**Comment by e6330703-be9f-426c-807a-4e38421ac008** [comment]
```pytb
I am trying to compile Python 2.7.13 (https://github.com/python/cpython/tree/9c1426de7521299f70eb5483e7e25d1c2a73dbbd) in 64 bit but I am getting following error:
Build started: Project: _ssl, Configuration: Release|x64
Performing Pre-Build Event...
Found a working perl at 'c:\perl\bin\perl.exe'
Traceback (most recent call last):
  File "build_ssl.py", line 248, in <module>
    main()
  File "build_ssl.py", line 231, in main
    shutil.copy(r"crypto\buildinf_%s.h" % arch, r"crypto\buildinf.h")
  File "C:\projects\windows-work\cpython-2.7.13\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\projects\windows-work\cpython-2.7.13\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'crypto\\buildinf_amd64.h'
Project : error PRJ0019: A tool returned an error code from "Performing Pre-Build Event..."
Build log was saved at "file://C:\projects\windows-work\cpython-2.7.13\PC\VS9.0\x64-temp-Release\_ssl\BuildLog.htm"
_ssl - 1 error(s), 0 warning(s)
Build started: Project: _hashlib, Configuration: Release|x64
Performing Pre-Build Event...
Found a working perl at 'c:\perl\bin\perl.exe'
Traceback (most recent call last):
  File "build_ssl.py", line 248, in <module>
    main()
  File "build_ssl.py", line 231, in main
    shutil.copy(r"crypto\buildinf_%s.h" % arch, r"crypto\buildinf.h")
  File "C:\projects\windows-work\cpython-2.7.13\lib\shutil.py", line 119, in copy
    copyfile(src, dst)
  File "C:\projects\windows-work\cpython-2.7.13\lib\shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'crypto\\buildinf_amd64.h'
Project : error PRJ0019: A tool returned an error code from "Performing Pre-Build Event..."
Build log was saved at "file://C:\projects\windows-work\cpython-2.7.13\PC\VS9.0\x64-temp-Release\_hashlib\BuildLog.htm"
_hashlib - 1 error(s), 0 warning(s)
Build complete: 23 Projects succeeded, 2 Projects failed, 1 Projects skipped
```



Then I did some search here + buildbots and I found there is already bug for it: https://bugs.python.org/issue30368 which seems to be fixed for upcoming Python 2.7.14 release.
Also I found that for commit 9c1426de7521299f70eb5483e7e25d1c2a73dbbd AMD64 buildbot has failed build (http://buildbot.python.org/all/builders/AMD64%20Windows7%20SP1%20VS9.0%202.7/builds/23/)

**Comment by e6330703-be9f-426c-807a-4e38421ac008** [comment]
I did some more digging into this and I found something strange:
So while compiling Python, it downloads externals from http://svn.python.org/projects/external/
Above site has many version of openssl so I looked into all openssl directory and found that from openssl version 0.9.8g we have ‘buildinf_amd64.h’ file under http://svn.python.org/projects/external/openssl-0.9.8g/crypto/ till openssl version 1.0.2f and after that we don’t have ‘*_amd64.h’ file under openssl-*/crypro directory and that is the reason 64 bit build is failing when user tries to compile Python 2.7.13 using PC\\VS9.0 build scripts + Visual Studio 2008.

Since all openssl source on http://svn.python.org/projects/external/ is pre-configured, don’t you guys think we should have \*_amd64.h file under openssl-*/crypto directory?

**Comment by e6330703-be9f-426c-807a-4e38421ac008** [comment]
Just another update I had chat with Zach for this on core-mentorship@python.org and he suggested to supply a patch which I will submit soon.

**Comment by e6330703-be9f-426c-807a-4e38421ac008** [comment]
Hey Zach,

Any update on this?

**Comment by zware** [comment]
Sorry it's taken me so long to get back to this, Hiren.  Do you still need it since 2.7.14 is out?
