### ISSUE TITLE
raw strings cannot end with a backslash character r'\'

### ISSUE THREAD

**Issue by gpshead** [python/cpython#75319]
BPO | [31136](https://bugs.python.org/issue31136)
--- | :---
Nosy | @tim-one, @gpshead, @vstinner, @ericvsmith, @bitdancer, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-08.02:28:28.256>
created_at = <Date 2017-08-08.00:50:49.474>
labels = ['interpreter-core', '3.7', 'invalid']
title = "raw strings cannot end with a backslash character r'\\'"
updated_at = <Date 2019-02-21.02:29:54.398>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-21.02:29:54.398>
actor = 'gwideman'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-08.02:28:28.256>
closer = 'tim.peters'
components = ['Interpreter Core']
creation = <Date 2017-08-08.00:50:49.474>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 31136
keywords = []
message_count = 9.0
messages = ['299883', '299885', '299889', '299890', '299893', '299918', '299934', '336174', '336175']
nosy_count = 7.0
nosy_names = ['tim.peters', 'gregory.p.smith', 'vstinner', 'eric.smith', 'r.david.murray', 'gwideman', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31136'
versions = ['Python 3.7']
```

</p></details>

**Comment by gpshead** [comment]
A raw string literal cannot end in a backslash.  There is no friendly way to write a string that ends in a backslash character.

In particular I want to put the following into a Python string: \\\\?\\

'\\\\\\\\?\\\\' works but is escaping hell so I wanted to suggest to the author to use r'\\\\?\\' but that leads to:
SyntaxError: EOL while scanning string literal

Tested in a random 3.7.0a0 build as well as older 2.7 and 3.x stable versions.

r'\\' is the easiest way to reproduce this.  (which could be written using the same number of bytes as '\\\\'... the use case above where a string containing a lot of \\s that also ends in a \\ is where it matters more from a code beauty point of view)

Can we update the parser to allow this?

**Comment by vstinner** [comment]
Workaround working on all Python versions, string concatenation made by the compiler: r"...." "...".

```pycon
>>> print(r"a\n" "\\")
a\n\
```

**Comment by vadmium** [comment]
What would your proposal do where an embedded backslash is currently valid?

```pycon
>>> print(r'Backslash apostrophe: \'.')
Backslash apostrophe: \'.
>>> r'\'  # Comment or string?'
"\\'  # Comment or string?"
```

**Comment by gpshead** [comment]
This may well be a "not a bug" resolution to preserve existing semantics that weren't what I expected.

**Comment by tim-one** [comment]
Yes, I'm closing as not-a-bug.  It's been this way (and documented) forever.  More specifically, as the docs say, a raw string can't end with an \_odd_ number of backslashes:

"""
String quotes can be escaped with a backslash, but the backslash remains in the string; for example, r"\\"" is a valid string literal consisting of two characters: a backslash and a double quote; r"\\" is not a valid string literal (even a raw string cannot end in an odd number of backslashes). Specifically, a raw string cannot end in a single backslash (since the backslash would escape the following quote character).
"""

**Comment by bitdancer** [comment]
In fact, this ia a FAQ: 

https://docs.python.org/3/faq/design.html#why-can-t-raw-strings-r-strings-end-with-a-backslash

**Comment by gpshead** [comment]
If i could stop thinking of r as meaning "raw" as we document it and instead "regular expression literal" I wouldn't make this mistake. :)

Thanks everyone!
