### ISSUE TITLE
test_prlimit from test_resource fails when building python3 inside systemd-nspawn environment

### ISSUE THREAD

**Issue by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [python/cpython#75315]
BPO | [31132](https://bugs.python.org/issue31132)
--- | :---
Nosy | @vstinner, @encukou, @stratakis, @torsava, @miss-islington
PRs | <li>python/cpython#9280</li><li>python/cpython#9283</li><li>python/cpython#9284</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-13.23:39:23.702>
created_at = <Date 2017-08-07.16:43:21.994>
labels = ['3.7']
title = 'test_prlimit from test_resource fails when building python3 inside systemd-nspawn environment'
updated_at = <Date 2018-09-13.23:39:23.701>
user = 'https://github.com/stratakis'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-13.23:39:23.701>
actor = 'benjamin.peterson'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-13.23:39:23.702>
closer = 'benjamin.peterson'
components = []
creation = <Date 2017-08-07.16:43:21.994>
creator = 'cstratak'
dependencies = []
files = []
hgrepos = []
issue_num = 31132
keywords = ['patch']
message_count = 7.0
messages = ['299852', '299853', '299866', '300979', '325297', '325299', '325301']
nosy_count = 5.0
nosy_names = ['vstinner', 'petr.viktorin', 'cstratak', 'torsava', 'miss-islington']
pr_nums = ['9280', '9283', '9284']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31132'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
FAIL: test_prlimit (test.test_resource.ResourceTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/builddir/build/BUILD/Python-3.6.2/Lib/test/support/__init__.py", line 556, in wrapper
    return func(*args, **kw)
  File "/builddir/build/BUILD/Python-3.6.2/Lib/test/test_resource.py", line 153, in test_prlimit
    1, resource.RLIMIT_AS)
AssertionError: PermissionError not raised by prlimit
```



I observed this issue when mock [0] the underlying build system we use in Fedora started using the systemd-nspawn container technology instead of chroot [1][2] in order to create a minimal build environment.

[0] https://github.com/rpm-software-management/mock
[1] https://github.com/rpm-software-management/mock/wiki/Release-Notes-1.4.1
[2] https://www.freedesktop.org/software/systemd/man/systemd-nspawn.html

**Comment by 186985f5-a56c-43bc-be75-552d7c9e60f4** [comment]
So the issue seems to be that Python believes it's run without root privileges, but it's mistaken because it indeed has root.

**Comment by vstinner** [comment]
Maybe we should simply skip the test if the user is root? If os.getuid()==0.

**Comment by encukou** [comment]
The test is already skipped if the user is root. It verifies that process 1 can't be touched by non-root users.

The problem is an assumption that process with PID 1 belongs to root. That assumption isn't true in containers: PID 1 is whatever the container was started with -- in this case, likely a test runner or build system.

On Linux, we could check if `/proc/1` actually belongs to root. I don't know about other systems, though.
Would that change be acceptable?
