### ISSUE TITLE
python not added to path

### ISSUE THREAD

**Issue by 2a3d46c3-4bee-48ae-acd6-c7453c44e655** [python/cpython#75317]
BPO | [31134](https://bugs.python.org/issue31134)
--- | :---
Nosy | @eryksun
Files | <li>[PythonError.docx](https://bugs.python.org/file47060/PythonError.docx "Uploaded as application/vnd.openxmlformats-officedocument.wordprocessingml.document at 2017-08-07.20:46:32 by AW")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-07.22:27:42.529>
created_at = <Date 2017-08-07.20:46:32.856>
labels = ['type-bug', 'invalid']
title = 'python not added to path'
updated_at = <Date 2017-08-07.22:27:42.528>
user = 'https://bugs.python.org/AW'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-07.22:27:42.528>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-07.22:27:42.529>
closer = 'eryksun'
components = []
creation = <Date 2017-08-07.20:46:32.856>
creator = 'AW'
dependencies = []
files = ['47060']
hgrepos = []
issue_num = 31134
keywords = []
message_count = 3.0
messages = ['299868', '299872', '299873']
nosy_count = 2.0
nosy_names = ['eryksun', 'AW']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31134'
versions = []
```

</p></details>

**Comment by 2a3d46c3-4bee-48ae-acd6-c7453c44e655** [comment]
I selected "Add Python 3.6 to PATH" when I installed the program. 

I am able to launch Python from the start button. 

It isn't recognized on the command line.

See screen shots in the attached Word file.

**Comment by eryksun** [comment]
A WM_SETTINGCHANGE message gets broadcasted to top-level windows, so Explorer should reload its environment from the registry. Did you start a new command prompt from Explorer?

**Comment by 2a3d46c3-4bee-48ae-acd6-c7453c44e655** [comment]
Sorry, no I didn't.  When I went off to find out how to add Python to the path manually, I found out that opening a new command window would be needed to see any update.  I was coming back to say "never mind" when I saw your message.  

Sorry to bother you!
