### ISSUE TITLE
Allow pydoc to run with an arbitrary hostname

### ISSUE THREAD

**Issue by 905da7cf-0b4d-428a-93cb-55d7844d5288** [python/cpython#75311]
BPO | [31128](https://bugs.python.org/issue31128)
--- | :---
Nosy | @merwok, @feanil
PRs | <li>python/cpython#3011</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/merwok'
closed_at = <Date 2017-09-14.21:55:24.142>
created_at = <Date 2017-08-06.22:55:50.381>
labels = ['type-feature', '3.7', 'docs']
title = 'Allow pydoc to run with an arbitrary hostname'
updated_at = <Date 2017-09-14.21:55:24.141>
user = 'https://github.com/feanil'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-14.21:55:24.141>
actor = 'eric.araujo'
assignee = 'eric.araujo'
closed = True
closed_date = <Date 2017-09-14.21:55:24.142>
closer = 'eric.araujo'
components = ['Documentation']
creation = <Date 2017-08-06.22:55:50.381>
creator = 'feanil'
dependencies = []
files = []
hgrepos = []
issue_num = 31128
keywords = []
message_count = 3.0
messages = ['299817', '302217', '302218']
nosy_count = 3.0
nosy_names = ['eric.araujo', 'docs@python', 'feanil']
pr_nums = ['3011']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31128'
versions = ['Python 3.7']
```

</p></details>

**Comment by 905da7cf-0b4d-428a-93cb-55d7844d5288** [comment]
I want to run the pydoc server while doing development inside a container.  However, the pydoc http server only binds to localhost with no option to override this.  This means that if I'm trying to read the docs from a remote machine,  I have to do some network Jiu Jitsu.

Acceptance Criteria:
- Pydoc takes a new argument that overrides the hostname the server binds to.
- Pydoc continues to default to localhost

**Comment by merwok** [comment]
New changeset 6a396c9807b1674a24e240731f18e20de97117a5 by Éric Araujo (Feanil Patel) in branch 'master':
bpo-31128: Allow pydoc to bind to arbitrary hostnames (bpo-3011)
https://github.com/python/cpython/commit/6a396c9807b1674a24e240731f18e20de97117a5

**Comment by merwok** [comment]
Merged, thanks!
