### ISSUE TITLE
Insufficient error message with incorrect formated string literal

### ISSUE THREAD

**Issue by b740f1b7-c0eb-4f2c-8cca-e819cf72b99c** [python/cpython#75323]
BPO | [31140](https://bugs.python.org/issue31140)
--- | :---
Nosy | @Cito, @ericvsmith
PRs | <li>python/cpython#1800</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-29.00:11:29.166>
created_at = <Date 2017-08-08.08:55:58.045>
labels = ['interpreter-core', 'type-bug', '3.7', '3.9']
title = 'Insufficient error message with incorrect formated string literal'
updated_at = <Date 2022-03-29.00:56:04.675>
user = 'https://bugs.python.org/chris259263'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-29.00:56:04.675>
actor = 'PeterL777'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-29.00:11:29.166>
closer = 'eric.smith'
components = ['Interpreter Core']
creation = <Date 2017-08-08.08:55:58.045>
creator = 'chris.259263'
dependencies = []
files = []
hgrepos = []
issue_num = 31140
keywords = []
message_count = 9.0
messages = ['299901', '299903', '299906', '299907', '309773', '358410', '416234', '416236', '416237']
nosy_count = 5.0
nosy_names = ['cito', 'eric.smith', 'chris.259263', 'philiprowlands', 'PeterL777']
pr_nums = ['1800']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31140'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.9']
```

</p></details>

**Comment by b740f1b7-c0eb-4f2c-8cca-e819cf72b99c** [comment]
Trying to run a script with a bug in a formated string literal (in the example the ":" is missing) throws an "invalid syntax" error at the first expression of the script.

Example:

```py
import math
a = "a"
b = f"{a>2s}"   # forgotten ":", should be f"{a:>2s}"
```


Running this script throws an "invalid syntax" error in the first line "import math".

In a large program this behavior makes it nearly impossible to find the real bug in the program as the error message does not give any hint about the line or the type of the error in the program.

Using Python 3.6.2, IDLE 3.6.2 on Mac macOS Sierra (10.12.1)

**Comment by ericvsmith** [comment]
On 3.6.1 on Windows, I get:

% python3 bpo-31140.py
  File "\<fstring\>", line 1
    (a\>2s)
        ^
SyntaxError: invalid syntax

Which is far from ideal, but at least points to (a portion of) the correct text.

I won't have access to a copy of 3.6.2 or 3.7 until later today. Can you show the exact output from 3.6.2?

**Comment by b740f1b7-c0eb-4f2c-8cca-e819cf72b99c** [comment]
Hi Eric,

running the script from the terminal on my system (macOS, Python 3.6.2) gives the same ErrorMessage as you stated.

The problem is the output "line 1".

Running the script from IDLE (3.6.2), the error points to the first line. And in IDLE you do not get the useful hint "(a\>2s)" but just "SyntaxError: invalid syntax".

**Comment by ericvsmith** [comment]
Thanks. There was some work on this recently: I'll try and check 3.7 later today.
