### ISSUE TITLE
python shell crashed while input quotes in print()

### ISSUE THREAD

**Issue by e045dd82-2f94-4471-ab6f-26b33b66f4d4** [python/cpython#75325]
BPO | [31142](https://bugs.python.org/issue31142)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily, @stevendaprano, @serhiy-storchaka
Files | <li>[crashlog.txt](https://bugs.python.org/file47068/crashlog.txt "Uploaded as text/plain at 2017-08-09.14:05:16 by py78py90py"): IDLE crash log</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-12.03:23:59.131>
created_at = <Date 2017-08-08.12:09:52.939>
labels = ['OS-mac', 'expert-IDLE', 'expert-tkinter', 'type-crash']
title = 'python shell crashed while input quotes in print()'
updated_at = <Date 2017-08-12.03:23:59.130>
user = 'https://bugs.python.org/py78py90py'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-12.03:23:59.130>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-12.03:23:59.131>
closer = 'ned.deily'
components = ['IDLE', 'macOS', 'Tkinter']
creation = <Date 2017-08-08.12:09:52.939>
creator = 'py78py90py'
dependencies = []
files = ['47068']
hgrepos = []
issue_num = 31142
keywords = []
message_count = 6.0
messages = ['299909', '299956', '300010', '300030', '300069', '300186']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'steven.daprano', 'serhiy.storchaka', 'py78py90py']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31142'
versions = ['Python 3.6']
```

</p></details>

**Comment by e045dd82-2f94-4471-ab6f-26b33b66f4d4** [comment]
I have downloaded python 3.6 into MacOSX system.
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin

Then I opened the IDLE and try to input some sentences.
I inputed "print()", then input single quote in print.
But the IDLE crashed.

**Comment by stevendaprano** [comment]
I'm afraid your error report isn't completely clear. What do you mean "input single quote in print"? Do you mean this?

```py
    print(')
```



You say IDLE "crashed". What do you mean? Do you mean the IDLE application put up an error message and then disappeared? If so, what was the error message?

If IDLE said something like:

    SyntaxError: EOL while scanning string literal

that's perfectly normal. That's because you haven't written a valid string, you need to quote the single quote: print("'").

**Comment by e045dd82-2f94-4471-ab6f-26b33b66f4d4** [comment]
Sorry for the incomplete information.

I have inputed following line:
print(")
IDLE crashed.
I also input following line:
print(')
IDLE also crashed.
I have uploaded the crash log.

**Comment by terryjreedy** [comment]
There is still something you left out.  Entering either print(")\<return\> or print(')\<return\> at either a shell prompt or in a file and running the file should result in "SyntaxError: EOL while scanning string literal", as Steven said.  Ditto for eval("print(')") or eval('print(")').  The error comes from Python's compile() function.  The result \*should* be the same on all systems. This is feature, neither a crash nor a bug.  So my first inclination was to close this as 'Not a bug'.

But getting a system crash log is usually a bug when running Python code. From my reading of Mac's crash log, what crashed is not IDLE but Python running \_tkinter calling tcl running tk calling OSX's CoreFoundation which raised NSRangeException.  How did you bypass compile()?

Where did you get the Python that you installed?  If from python.org, did you pay attention to https://www.python.org/download/mac/tcltk/ and install a tcl/tk that works?  If not, not our bug.

Ned and Serhiy: can we patch  \_tkinter on Mac to refuse to run with the buggy Apple tcl/tk?  Or at least pop up a Warning box that says to not bug us when it crashes?

**Comment by e045dd82-2f94-4471-ab6f-26b33b66f4d4** [comment]
I downloaded python from www.python.org. And I think I have tcl/tk installed.

```pycon
Python 3.6.2 (v3.6.2:5fd33b5926, Jul 16 2017, 20:11:06) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>>> WARNING: The version of Tcl/Tk (8.5.9) in use may be unstable.
Visit http://www.python.org/download/mac/tcltk/ for current information.
```


I am trying to use the recommended tcltk version.

**Comment by ned-deily** [comment]
Note that the web page states you need to use Tcl/Tk 8.5.18, and not 8.6.x.  Both are available from ActiveState here:

https://www.activestate.com/activetcl/downloads

Try installing 8.5.18 (you don't need to uninstall 8.6.x) and your crashes should go away.
