### ISSUE TITLE
Add a path attribute to NamedTemporaryFile

### ISSUE THREAD

**Issue by 423378f0-f418-4710-a5ff-8cbf6c802f17** [python/cpython#75320]
BPO | [31137](https://bugs.python.org/issue31137)
--- | :---
Nosy | @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-04.23:12:01.319>
created_at = <Date 2017-08-08.00:59:25.740>
labels = ['type-feature', 'library']
title = 'Add a path attribute to NamedTemporaryFile'
updated_at = <Date 2022-01-04.23:12:01.318>
user = 'https://bugs.python.org/wsanchez'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-04.23:12:01.318>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-04.23:12:01.319>
closer = 'iritkatriel'
components = ['Library (Lib)']
creation = <Date 2017-08-08.00:59:25.740>
creator = 'wsanchez'
dependencies = []
files = []
hgrepos = []
issue_num = 31137
keywords = []
message_count = 2.0
messages = ['299884', '299898']
nosy_count = 2.0
nosy_names = ['wsanchez', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31137'
versions = ['Python 3.6']
```

</p></details>

**Comment by 423378f0-f418-4710-a5ff-8cbf6c802f17** [comment]
Add a path attribute to NamedTemporaryFile which provides a pathlib.Path object pointing to the file on disk.

**Comment by serhiy-storchaka** [comment]
You can just pass the name attribute to the pathlib.Path constructor. Adding a name attribute will not allow you to do what you can't do now, but will increase the coupling between the tempfile and pathlib modules. The purpose of introducing the path protocol was avoiding creating such couplings.
