### ISSUE TITLE
add initializer to concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by 34b428e6-c49c-4be2-ba46-fe34dcb38478** [python/cpython#75327]
BPO | [31144](https://bugs.python.org/issue31144)
--- | :---
Nosy | @pitrou, @nvdv
Superseder | <li>bpo-21423: concurrent.futures.ThreadPoolExecutor/ProcessPoolExecutor should accept an initializer argument</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-02.18:09:21.914>
created_at = <Date 2017-08-08.14:02:29.953>
labels = ['3.7', 'type-feature', 'library']
title = 'add initializer to concurrent.futures.ProcessPoolExecutor'
updated_at = <Date 2017-09-02.18:09:21.913>
user = 'https://github.com/nvdv'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-02.18:09:21.913>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-02.18:09:21.914>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-08-08.14:02:29.953>
creator = 'nvdv'
dependencies = []
files = []
hgrepos = []
issue_num = 31144
keywords = []
message_count = 4.0
messages = ['299921', '300615', '301166', '301167']
nosy_count = 2.0
nosy_names = ['pitrou', 'nvdv']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '21423'
type = 'enhancement'
url = 'https://bugs.python.org/issue31144'
versions = ['Python 3.7']
```

</p></details>

**Comment by 34b428e6-c49c-4be2-ba46-fe34dcb38478** [comment]
Unfortunately concurrent.futures.ProcessPoolExecutor does not provide any means to interact with worker processes (like initializer function in multiprocessing.Pool constructor).

This problem has been mentioned at least once: 
https://mail.python.org/pipermail/python-dev/2014-March/133697.html.

It's not hard to work around this issue by subclassing ProcessPoolExecutor and adding all necessary methods, but IMO solution can be more generic.

**Comment by 34b428e6-c49c-4be2-ba46-fe34dcb38478** [comment]
I can make a PR if it makes any sense for stdlib maintainer.

**Comment by pitrou** [comment]
That would sound like a reasonable addition, yes.

**Comment by pitrou** [comment]
Actually, looks like this was already proposed in bpo-21423. Closing as duplicate.
