### ISSUE TITLE
Start should be a keyword argument of the built-in sum

### ISSUE THREAD

**Issue by a7d035cf-7a65-424d-a94c-5be23113c333** [python/cpython#75324]
BPO | [31141](https://bugs.python.org/issue31141)
--- | :---
Nosy | @rhettinger, @vstinner, @stevendaprano, @serhiy-storchaka, @MarkCBell, @lisroach, @csabella
PRs | <li>python/cpython#3022</li>
Superseder | <li>bpo-34637: Make *start* usable as a keyword argument for sum().</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/lisroach'
closed_at = <Date 2018-09-12.17:59:37.496>
created_at = <Date 2017-08-08.11:52:48.120>
labels = ['ctypes', 'type-feature', '3.7']
title = 'Start should be a keyword argument of the built-in sum'
updated_at = <Date 2018-09-13.06:20:51.911>
user = 'https://github.com/MarkCBell'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-13.06:20:51.911>
actor = 'vstinner'
assignee = 'lisroach'
closed = True
closed_date = <Date 2018-09-12.17:59:37.496>
closer = 'rhettinger'
components = ['ctypes']
creation = <Date 2017-08-08.11:52:48.120>
creator = 'Mark.Bell'
dependencies = []
files = []
hgrepos = []
issue_num = 31141
keywords = []
message_count = 10.0
messages = ['299908', '299957', '299968', '299973', '300356', '300420', '315790', '315791', '315793', '315794']
nosy_count = 7.0
nosy_names = ['rhettinger', 'vstinner', 'steven.daprano', 'serhiy.storchaka', 'Mark.Bell', 'lisroach', 'cheryl.sabella']
pr_nums = ['3022']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '34637'
type = 'enhancement'
url = 'https://bugs.python.org/issue31141'
versions = ['Python 3.7']
```

</p></details>

**Comment by a7d035cf-7a65-424d-a94c-5be23113c333** [comment]
The built-in function sum takes an optional argument "start" to specify what value to start adding from (defaults to 0). This argument should be a keyword argument in order to match the other built-in functions such as:

    enumerate(range(10), start=5)

This patch allows users to write:

    sum(range(10), start=5)

which previously raised "TypeError: sum() takes no keyword arguments". Since the only change is making an optional positional argument into a keyword argument, this has no effect on any existing code using the current convention of:

    sum(range(10), 5)

**Comment by stevendaprano** [comment]
This seems like a reasonable enhancement to `sum` to me.

Since 2.7 is in feature freeze, this can only apply to 3.7.

**Comment by rhettinger** [comment]
Lisa, would you like to take this one?

**Comment by serhiy-storchaka** [comment]
Adding this feature is so easy as moving '/' in Argument Clinic declaration one line up. I don't think it is worth to allow passing the first argument as a keyword argument.

Check what performance effect of this change on simple calls sum(()), sum((), 0).

**Comment by a7d035cf-7a65-424d-a94c-5be23113c333** [comment]
I ran some timing tests of the patch I submitted to compare it to the current build of Python. Using timit on the current master branch I got:

    python.exe -m timeit "sum(())"    .... 1.12 usec per loop
    python.exe -m timeit "sum((), 0)" .... 1.22 usec per loop

And for the patched version:

    python.exe -m timeit "sum(())"    .... 1.46 usec per loop
    python.exe -m timeit "sum((), 0)" .... 1.57 usec per loop

However my patch wasn't just the simple argument clinic change suggested by serhiy.storchaka, so maybe that would be more efficient and easier to understand.

**Comment by serhiy-storchaka** [comment]
Your tests show that there is a performance regression of getting rid of Argument Clinic (in addition to increasing the maintenance cost of the code that was generated previously). Try to use the simple Argument Clinic change (it can has non-zero cost too, but I expect that its penalty is much smaller).
