### ISSUE TITLE
Update docstrings of itertools functions

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75336]
BPO | [31153](https://bugs.python.org/issue31153)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @vexoxev
PRs | <li>python/cpython#3047</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-09-24.23:03:04.543>
created_at = <Date 2017-08-09.07:42:39.840>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Update docstrings of itertools functions'
updated_at = <Date 2017-09-24.23:03:04.542>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-24.23:03:04.542>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-09-24.23:03:04.543>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-08-09.07:42:39.840>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31153
keywords = ['easy']
message_count = 3.0
messages = ['299975', '302719', '302893']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'serhiy.storchaka', 'vexoxev']
pr_nums = ['3047']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31153'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Docstrings of some itertools functions look outdated.

1. The docstring of groupby() contains the signature "groupby(iterable[, keyfunc])". But groupby() supports keyword arguments, the name of the second parameter is "key", and its default value is None.

2. accumulate() accepts None as the second argument.

3. The equivalent code of count() has the first parameter "firstval" instead of "start". It uses the "while 1" loop instead of more idiomatic in Python 3 "while True".

4. The term "sequence" is used in the docstring of starmap(), while actually an iterable is accepted. Compare with the docstring of map(). See also bpo-31082.

**Comment by serhiy-storchaka** [comment]
For groupby() see also bpo-27385.

**Comment by rhettinger** [comment]
Marking this as closed.  1) is being fixed elsewhere, 2) don't want to make func=None an official part of the API (it was a convenience for letting func default to the equivalent of operator.add), 3) already fixed, and 4) already fixed.
