### ISSUE TITLE
Stopiteration terminates while-loop

### ISSUE THREAD

**Issue by b4b72bd2-1e1c-41c4-9ac0-0f669dd310f8** [python/cpython#75339]
BPO | [31156](https://bugs.python.org/issue31156)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-09.14:22:02.623>
created_at = <Date 2017-08-09.09:49:19.542>
labels = ['type-feature', 'docs']
title = 'Stopiteration terminates while-loop'
updated_at = <Date 2017-08-09.14:22:02.617>
user = 'https://bugs.python.org/GnterRote'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-09.14:22:02.617>
actor = 'G\xc3\xbcnter Rote'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-09.14:22:02.623>
closer = 'G\xc3\xbcnter Rote'
components = ['Documentation']
creation = <Date 2017-08-09.09:49:19.542>
creator = 'G\xc3\xbcnter Rote'
dependencies = []
files = []
hgrepos = []
issue_num = 31156
keywords = []
message_count = 3.0
messages = ['299982', '300005', '300011']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'docs@python', 'G\xc3\xbcnter Rote']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31156'
versions = ['Python 3.4']
```

</p></details>

**Comment by b4b72bd2-1e1c-41c4-9ac0-0f669dd310f8** [comment]
It should be mentioned in the documentation that 

A StopIteration exception raised in the body of a while loop will terminate (and is caught by) the while-loop, thus leading to graceful termination.

A good place would be here:
1) https://docs.python.org/3/reference/compound_stmts.html#the-while-statement

I don't know how such a StopIteration termination of a while loop
affects the else-clause. This should be clarified.

Here:
2) https://docs.python.org/3/library/exceptions.html#StopIteration
it would be good to explicitly state:

An enclosing while-loop or for-loop acts like an implicit catch for StopIteration. The StopIteration exception will terminate the loop.

(I guess, a for-loop is also just terminated when the StopIteration originates in the BODY of the loop, although this is not the typical case.)

**Comment by bitdancer** [comment]
```pycon
>>> while True:
...     raise StopIteration
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
StopIteration
```

**Comment by b4b72bd2-1e1c-41c4-9ac0-0f669dd310f8** [comment]
Sorry, that was my misinterpretation of what happened.
I had been stumbling over an old program I had written, but
apparently it works because the while-loop is inside
a generator function, and the StopIteration is simply
passed on.

```pycon
Here is a small demonstration example:
>>> def f():
...   for x in range(5):
...     yield x
... 
>>> def g():
...   h=f()
...   while True:
...      yield next(h)+100
...      yield next(h)
... 
>>> list(g())
[100, 1, 102, 3, 104]
```


(I am beginning to wonder whether this program will be adversely affected by PEP-479 -- Change StopIteration handling inside generators.)
