### ISSUE TITLE
Return destination path in Path.rename and Path.replace

### ISSUE THREAD

**Issue by 03208004-7947-421b-adbb-00a0994f8621** [python/cpython#75346]
BPO | [31163](https://bugs.python.org/issue31163)
--- | :---
Nosy | @jaraco, @pitrou, @bitdancer, @berkerpeksag, @csabella
PRs | <li>python/cpython#4055</li><li>python/cpython#13582</li><li>python/cpython#15944</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-09-11.14:23:08.013>
created_at = <Date 2017-08-09.15:32:24.454>
labels = ['easy', '3.8', '3.9', 'type-feature', 'library', 'docs']
title = 'Return destination path in Path.rename and Path.replace'
updated_at = <Date 2019-09-11.14:23:08.008>
user = 'https://bugs.python.org/albertogomcas'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-11.14:23:08.008>
actor = 'jaraco'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-09-11.14:23:08.013>
closer = 'jaraco'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2017-08-09.15:32:24.454>
creator = 'albertogomcas'
dependencies = []
files = []
hgrepos = []
issue_num = 31163
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['300019', '300027', '342970', '351865', '351892']
nosy_count = 7.0
nosy_names = ['jaraco', 'pitrou', 'r.david.murray', 'docs@python', 'berker.peksag', 'cheryl.sabella', 'albertogomcas']
pr_nums = ['4055', '13582', '15944']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31163'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 03208004-7947-421b-adbb-00a0994f8621** [comment]
Extracted from bpo-31154

Both calls lack any kind of return, which leads me to expect after a rename/replace the Path instance would be changed to the new path. This is not the case (reading the PEP I have seen Path instances are kind of immutable), after the call the Path instance keeps "pointing" to the previous (and quite likely now useless) path. 

Returning the new path would be a reasonable option. In any case, I think the documentation should mention this behavior explicitly.

**Comment by bitdancer** [comment]
I agree.  The normal python convention is that an immutable object returns the new value when an operation "changes" it, while a mutable object returns None.  It seems like replace and rename should follow this convention (and that it would also be convenient).
