### ISSUE TITLE
Only check for print and exec parentheses cases for SyntaxError, not subclasses

### ISSUE THREAD

**Issue by 652782da-b5f3-46b2-ae1b-1f73662bb759** [python/cpython#75344]
BPO | [31161](https://bugs.python.org/issue31161)
--- | :---
Nosy | @mjpieters, @stevendaprano, @ambv, @serhiy-storchaka
PRs | <li>python/cpython#3082</li><li>python/cpython#3083</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-22.20:17:57.125>
created_at = <Date 2017-08-09.13:31:18.767>
labels = ['interpreter-core', 'easy', 'type-bug', '3.7']
title = 'Only check for print and exec parentheses cases for SyntaxError, not subclasses'
updated_at = <Date 2017-08-22.20:17:57.124>
user = 'https://github.com/mjpieters'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-22.20:17:57.124>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-22.20:17:57.125>
closer = 'lukasz.langa'
components = ['Interpreter Core']
creation = <Date 2017-08-09.13:31:18.767>
creator = 'mjpieters'
dependencies = []
files = []
hgrepos = []
issue_num = 31161
keywords = ['easy (C)']
message_count = 11.0
messages = ['300002', '300003', '300076', '300109', '300158', '300208', '300214', '300220', '300221', '300718', '300719']
nosy_count = 4.0
nosy_names = ['mjpieters', 'steven.daprano', 'lukasz.langa', 'serhiy.storchaka']
pr_nums = ['3082', '3083']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31161'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 652782da-b5f3-46b2-ae1b-1f73662bb759** [comment]
SyntaxError.__init__() checks for the `print` and `exec` error cases where the user forgot to use parentheses:

```pycon
>>> exec 1
  File "<stdin>", line 1
    exec 1
         ^
SyntaxError: Missing parentheses in call to 'exec'

>>> print 1
  File "<stdin>", line 1
    print 1
          ^
SyntaxError: Missing parentheses in call to 'print'
```


However, this check is also applied to \*subclasses* of SyntaxError:

```pycon
>>> if True:
... print "Look ma, no parens!"
  File "<stdin>", line 2
    print "Look ma, no parens!"
        ^
IndentationError: Missing parentheses in call to 'print'
```


and

```pycon
>>> compile('if 1:\n    1\n\tprint "Look ma, tabs!"', '', 'single')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "", line 3
    print "Look ma, tabs!"
                         ^
TabError: Missing parentheses in call to 'print'
```


Perhaps the check needs to be limited to just the exact type.

**Comment by 652782da-b5f3-46b2-ae1b-1f73662bb759** [comment]
Credit for uncovering this gem: https://stackoverflow.com/questions/45591883/why-is-an-indentionerror-being-raised-here-rather-than-a-syntaxerror

**Comment by stevendaprano** [comment]
I'm not sure whether this is a bug or a feature.

In the examples you show, we have \*both* an IndentationError/TabError and missing parentheses around print. So I'm almost inclined to say that this is right:

- you get an IndentationError (or TabError);

- and the error message \*also* tells you that print is missing parens.

Two errors for the price of one!

I'm not sure that I would have designed it this way from scratch, but given that it already exists I'm not sure that it should be "fixed".

In any case, since the error message itself is not part of the public API, I don't think there's any problem in changing it in a bug-fix release. So \*if* we change this, we can change it in 3.6.

**Comment by 652782da-b5f3-46b2-ae1b-1f73662bb759** [comment]
It's confusing; a syntax error reports on the first error found, not two errors at once. The TabError or IndentationError exception detail message itself is lost (it should be "IndentationError: Improper mixture of spaces and tabs." or "TabError: Improper indentation.", respectively). So you end up with an end-user scratching their head, the two parts of the message make no sense together.

**Comment by serhiy-storchaka** [comment]
> Perhaps the check needs to be limited to just the exact type.

Looks reasonable to me. Do you want to provide a PR Martijn?

**Comment by stevendaprano** [comment]
> \> Perhaps the check needs to be limited to just the exact type.
> Looks reasonable to me. Do you want to provide a PR Martijn?

You realise that is making the current traceback \*less* informative 
instead of more informative? I think that's going backwards -- useful 
information about the syntax errors are being discarded. "Practicality 
beats purity" -- the current behaviour is helpful, even if it mixes 
information about two errors into one traceback.

**Comment by serhiy-storchaka** [comment]
The current traceback is incorrect. It mixes exception type and message from different errors.

**Comment by 652782da-b5f3-46b2-ae1b-1f73662bb759** [comment]
This does not increase clarity. It creates confusion.

There are two distinct syntax errors, and they should be reported separately, just like `print "abc" 42` is two syntax errors; you'll hear about the second one once the first one is fixed.

**Comment by 652782da-b5f3-46b2-ae1b-1f73662bb759** [comment]
Disregard my last message, I misread Serhiy's sentence (read 'correct' for 'incorrect').

**Comment by ambv** [comment]
New changeset 680f04a926bce04e4320ba883068c345eba502a6 by Łukasz Langa (Martijn Pieters) in branch '3.6':
bpo-31161: only check for parens error for SyntaxError (bpo-3083)
https://github.com/python/cpython/commit/680f04a926bce04e4320ba883068c345eba502a6

**Comment by ambv** [comment]
New changeset 772d809a63f40fd35679da3fb115cdf7fa81bd20 by Łukasz Langa (Martijn Pieters) in branch 'master':
bpo-31161: only check for parens error for SyntaxError (bpo-3082)
https://github.com/python/cpython/commit/772d809a63f40fd35679da3fb115cdf7fa81bd20
