### ISSUE TITLE
urllib.request.urlopen CERTIFICATE_VERIFY_FAILED error

### ISSUE THREAD

**Issue by a23805a2-4b89-4a88-8848-e69c04e4e913** [python/cpython#75345]
BPO | [31162](https://bugs.python.org/issue31162)
--- | :---
Nosy | @bitdancer, @eamanu, @jacobtylerwalls
Files | <li>[scriptError.txt](https://bugs.python.org/file47069/scriptError.txt "Uploaded as text/plain at 2017-08-09.14:50:08 by chua.chewbock@gmail.com")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-08-09.14:49:18.765>
labels = ['invalid', 'type-bug', 'library']
title = 'urllib.request.urlopen CERTIFICATE_VERIFY_FAILED error'
updated_at = <Date 2021-07-19.20:27:00.207>
user = 'https://bugs.python.org/chuachewbockgmailcom'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-19.20:27:00.207>
actor = 'jacobtylerwalls'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-08-09.14:49:18.765>
creator = 'chua.chewbock@gmail.com'
dependencies = []
files = ['47069']
hgrepos = []
issue_num = 31162
keywords = []
message_count = 4.0
messages = ['300012', '300026', '336303', '397836']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'eamanu', 'chua.chewbock@gmail.com', 'jacobtylerwalls']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31162'
versions = ['Python 3.6']
```

</p></details>

**Comment by a23805a2-4b89-4a88-8848-e69c04e4e913** [comment]
Error encountered when executing urllib.request.urlopen on IDLE3 interactive as well as run from script.

**Comment by bitdancer** [comment]
What makes you think this is a python bug rather than exactly what it says: a cert verification error?
