### ISSUE TITLE
math.sqrt function wrong

### ISSUE THREAD

**Issue by 1cf9f427-249e-4a58-a94f-1fdb127e3176** [python/cpython#75340]
BPO | [31157](https://bugs.python.org/issue31157)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba
Files | <li>[PyCuda - [C__Users_mick_PyScripts_PyCuda] - C__Users_mick_.PyCharmCE2017.2_config_scratches_scratch_5.py - PyCharm Community Edition 2017.2 09_08_2017 10_44_31.png](https://bugs.python.org/file47067/PyCuda%20-%20%5BC__Users_mick_PyScripts_PyCuda%5D%20-%20C__Users_mick_.PyCharmCE2017.2_config_scratches_scratch_5.py%20-%20PyCharm%20Community%20Edition%202017.2%2009_08_2017%2010_44_31.png "Uploaded as image/png at 2017-08-09.09:54:19 by Mick Press"): Screen shot</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-09.09:58:42.890>
created_at = <Date 2017-08-09.09:54:19.597>
labels = ['invalid', 'OS-windows', 'performance']
title = 'math.sqrt function wrong'
updated_at = <Date 2017-08-09.09:58:42.868>
user = 'https://bugs.python.org/MickPress'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-09.09:58:42.868>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-09.09:58:42.890>
closer = 'vstinner'
components = ['Windows']
creation = <Date 2017-08-09.09:54:19.597>
creator = 'Mick Press'
dependencies = []
files = ['47067']
hgrepos = []
issue_num = 31157
keywords = []
message_count = 2.0
messages = ['299983', '299984']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower', 'Mick Press']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31157'
versions = ['Python 3.5']
```

</p></details>

**Comment by 1cf9f427-249e-4a58-a94f-1fdb127e3176** [comment]
math.sqrt for very large numbers returns wrong value. Attached is screen shot showing my sqrt function result and math.sqrt function result.

**Comment by vstinner** [comment]
The math module uses the float type which has a limited precision: it's 64-bit IEEE.

For better precision, you can use the decimal module which has configurable precision.

Example:
\---
```py
import decimal
```


decimal.getcontext().prec = 5
root = decimal.Decimal('123').sqrt()
print(root)

decimal.getcontext().prec = 50
root = decimal.Decimal('123').sqrt()
print(root)
\---

Output:
\---
11.091
11.090536506409417162051600102609932918463376742454
\---

Said differently: the behaviour that you noticed is not a bug, but a known limitation of Python, of the Python float type to be exact.

https://docs.python.org/3/tutorial/floatingpoint.html
