### ISSUE TITLE
Doc: Language switch can't switch on specific cases

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#75342]
BPO | [31159](https://bugs.python.org/issue31159)
--- | :---
Nosy | @vstinner, @JulienPalard
PRs | <li>python/cpython#3039</li><li>python/cpython#3051</li><li>python/cpython#3081</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-23.16:36:28.986>
created_at = <Date 2017-08-09.11:38:46.455>
labels = []
title = "Doc: Language switch can't switch on specific cases"
updated_at = <Date 2017-09-23.16:36:28.985>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-23.16:36:28.985>
actor = 'mdk'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-23.16:36:28.986>
closer = 'mdk'
components = []
creation = <Date 2017-08-09.11:38:46.455>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 31159
keywords = []
message_count = 6.0
messages = ['299990', '300016', '300056', '300095', '300232', '300233']
nosy_count = 2.0
nosy_names = ['vstinner', 'mdk']
pr_nums = ['3039', '3051', '3081']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31159'
versions = []
```

</p></details>

**Comment by JulienPalard** [comment]
Since ja has been added to the language switch, a bug appeared and in some case the switch won't ... switch.

Due to a regex bug in switchers.js, a needed trailing slash is sometimes not matched. It has not been detected previously as it can happen only when there more than two languages in the picker which is now the case.

Bug is in:  var language_regexp = '\\.org/(' + Object.keys(all_languages).join('|') + '/)';

It only matches the trailing slash for the last language, currently the / is for ja, so fr does no longer match the needed slash.

Fix may consists in adding a non-matching group around the join.

But there's another issue when a user goes to a version in which there's a language picker but the current langage is not known by the picker, typically if a user is on /ja/2.7/ but the language picker with Japanese has only been merged on 3.6 and 3.7: the regex on /ja/2.7 will not contain "ja", so it will not be able to match it.


So we should write this regex otherwise, I grepped on the server logs and checked on the filesystem, this one should work better and still be safe:


    var language_regexp = '\.org/([a-z]{2}(?:-[a-z]{2})?/)';

**Comment by vstinner** [comment]
New changeset 122081deef86174beee965be1207fa46ea23533d by Victor Stinner (Julien Palard) in branch 'master':
bpo-31159: fix language switch regex on unknown yet built languages. (bpo-3039)
https://github.com/python/cpython/commit/122081deef86174beee965be1207fa46ea23533d

**Comment by JulienPalard** [comment]
Now works in 3.7, needs backports to 3.6 and 2.7.

**Comment by vstinner** [comment]
New changeset e8e7fba0b24582959feca9c31f2a72fc0251f83d by Victor Stinner (Julien Palard) in branch '3.6':
bpo-31159: fix language switch regex on unknown yet built languages. … (bpo-3051)
https://github.com/python/cpython/commit/e8e7fba0b24582959feca9c31f2a72fc0251f83d

**Comment by vstinner** [comment]
New changeset fe8d9dc479a96ef490034107e7d4a6228b4be140 by Victor Stinner (Julien Palard) in branch '2.7':
bpo-31159: fix language switch regex on unknown yet built languages. … (bpo-3051) (bpo-3081)
https://github.com/python/cpython/commit/fe8d9dc479a96ef490034107e7d4a6228b4be140

**Comment by vstinner** [comment]
To choose the langague, see what Wikipedia does: Wikipedia EN displays
"Français", no?
