### ISSUE TITLE
Update to expat 2.2.4 (expat: utf8_toUtf8 cannot properly handle exhausting buffer)

### ISSUE THREAD

**Issue by ab131abd-b788-46d4-a098-f8a32e26f5c7** [python/cpython#75353]
BPO | [31170](https://bugs.python.org/issue31170)
--- | :---
Nosy | @birkenfeld, @vstinner, @larryhastings, @benjaminp, @ned-deily, @serhiy-storchaka, @hartwork, @tianlynn
PRs | <li>python/cpython#3315</li><li>python/cpython#3350</li><li>python/cpython#3351</li><li>python/cpython#3352</li><li>python/cpython#3353</li><li>python/cpython#3354</li><li>python/cpython#3570</li><li>python/cpython#3745</li><li>python/cpython#3746</li><li>python/cpython#3751</li><li>python/cpython#3785</li>
Files | <li>[cpython_rebuild_expat_dir.sh](https://bugs.python.org/file47118/cpython_rebuild_expat_dir.sh "Uploaded as application/x-shellscript at 2017-09-04.21:41:01 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-01-04.15:52:09.415>
created_at = <Date 2017-08-10.04:48:25.430>
labels = ['type-bug', 'library', 'release-blocker']
title = 'Update to expat 2.2.4 (expat: utf8_toUtf8 cannot properly handle exhausting buffer)'
updated_at = <Date 2019-05-10.18:04:35.827>
user = 'https://github.com/tianlynn'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-10.18:04:35.827>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-01-04.15:52:09.415>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-08-10.04:48:25.430>
creator = 'tianlynn'
dependencies = []
files = ['47118']
hgrepos = []
issue_num = 31170
keywords = ['patch']
message_count = 26.0
messages = ['300043', '300044', '300268', '300309', '300605', '301011', '301012', '301084', '301270', '301287', '301399', '301422', '301424', '302159', '302483', '302833', '302898', '302925', '302927', '302930', '302931', '302975', '303037', '307254', '309469', '309471']
nosy_count = 8.0
nosy_names = ['georg.brandl', 'vstinner', 'larry', 'benjamin.peterson', 'ned.deily', 'serhiy.storchaka', 'sping', 'tianlynn']
pr_nums = ['3315', '3350', '3351', '3352', '3353', '3354', '3570', '3745', '3746', '3751', '3785']
priority = 'release blocker'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31170'
versions = ['Python 3.4', 'Python 3.5']
```

</p></details>

**Comment by ab131abd-b788-46d4-a098-f8a32e26f5c7** [comment]
```c
utf8_toUtf8(const ENCODING *UNUSED_P(enc),
            const char **fromP, const char *fromLim,
            char **toP, const char *toLim)
{
  char *to;
  const char *from;
  const char *fromLimInitial = fromLim;
```


  /* Avoid copying partial characters. \*/
  align_limit_to_full_utf8_characters(*fromP, &fromLim);

  for (to = \*toP, from = \*fromP; (from \< fromLim) && (to \< toLim); from++, to++)
    \*to = \*from;
  \*fromP = from;
  \*toP = to;

```c
  if (fromLim < fromLimInitial)
    return XML_CONVERT_INPUT_INCOMPLETE;
  else if ((to == toLim) && (from < fromLim))
    // <===== Bug is here. In case (to == toLim), it's possible that
    //        from is still pointing to partial character. For example,
    //        a character with 3 bytes (A, B, C) and form is pointing to C.
    //        It means only A and B is copied to output buffer. Next
    //        scanning will start with C which could be considered as invalid
    //        byte and got dropped. After this, only "AB" is kept in memory
    //        and thus it will lead to invalid continuation byte.
    return XML_CONVERT_OUTPUT_EXHAUSTED;
  else
    return XML_CONVERT_COMPLETED;
}
```

**Comment by serhiy-storchaka** [comment]
This is not our code. Please use corresponding bug tracker [1] if you have found a bug in Expat.

But I think there is not a bug here.

[1] https://github.com/libexpat/libexpat/issues

**Comment by ab131abd-b788-46d4-a098-f8a32e26f5c7** [comment]
Reactive this issue as to let you know that libexpat has confirmed and fixed the bug and they are interested in porting the fix to python. Reactive this in case you want to know what's going on and make a decision accordingly. (Sorry, I'm not very familiar with process here)

**Comment by e17d0dad-ccf7-4c8c-9c31-cdd9810492bf** [comment]
For the record, the upstream fix is commit https://github.com/libexpat/libexpat/commit/74a7090a6eb92c27b7010287a4082de6b357fa42 and it will be part of Expat 2.2.4.

**Comment by e17d0dad-ccf7-4c8c-9c31-cdd9810492bf** [comment]
Expat 2.2.4 with a fix has been released now: https://github.com/libexpat/libexpat/releases

**Comment by serhiy-storchaka** [comment]
I confirm the regression (see bpo-31303 for reproducer). Victor, do you mind to update expat to 2.2.4?

This issue can be classified as a security issue, since a regression was added in security update.

**Comment by serhiy-storchaka** [comment]
Corresponding Expat issue: https://github.com/libexpat/libexpat/issues/115.

**Comment by benjaminp** [comment]
We can put expat 2.2.4 in 2.7.14 final.

**Comment by vstinner** [comment]
I produced attached [PR 3315](https://github.com/python/cpython/pull/3315) using attached cpython_rebuild_expat_dir.sh + revert [Modules/expat/expat_external.h](https://github.com/python/cpython/blob/main/Modules/expat/expat_external.h) change to keep #include "pyexpatns.h".

**Comment by vstinner** [comment]
New changeset 759e30ec47048cb9835c62aaeac48748c8151390 by Victor Stinner in branch 'master':
bpo-31170: Update libexpat from 2.2.3 to 2.2.4 (bpo-3315)
https://github.com/python/cpython/commit/759e30ec47048cb9835c62aaeac48748c8151390

**Comment by vstinner** [comment]
New changeset e5f2f8038540f9f06478f842f8f7313df4d2e59b by Victor Stinner in branch '3.6':
bpo-31170: Update libexpat from 2.2.3 to 2.2.4 (bpo-3315) (bpo-3350)
https://github.com/python/cpython/commit/e5f2f8038540f9f06478f842f8f7313df4d2e59b

**Comment by ned-deily** [comment]
New changeset 297516ea509c72d8ebed3a9b3ce200f023aca0b7 by Ned Deily (Victor Stinner) in branch '3.3':
[3.3] bpo-30947, bpo-31170: Update expat from 2.2.1 to 2.2.4 (bpo-3352)
https://github.com/python/cpython/commit/297516ea509c72d8ebed3a9b3ce200f023aca0b7

**Comment by benjaminp** [comment]
New changeset c00d5087cd308cc8be41e0afd8df27726185347f by Benjamin Peterson (Victor Stinner) in branch '2.7':
bpo-31170: Update libexpat from 2.2.3 to 2.2.4 (bpo-3315)
https://github.com/python/cpython/commit/c00d5087cd308cc8be41e0afd8df27726185347f

**Comment by vstinner** [comment]
I wrote an non-regression test for the Python master branch using the test case attached to https://github.com/libexpat/libexpat/issues/115: [PR 3570](https://github.com/python/cpython/pull/3570).

**Comment by ned-deily** [comment]
I believe all the branches except 3.5 and 3.4 have been updated so adjusting the Versions field accordingly.  All yours, Larry!

**Comment by larryhastings** [comment]
New changeset 86a713cb0c110b6798ca7f9e630fc511ee0a4028 by larryhastings (Victor Stinner) in branch '3.4':
[3.4][Security] bpo-30947, bpo-31170: Update expat from 2.2.1 to 2.2.4 (bpo-3353)
https://github.com/python/cpython/commit/86a713cb0c110b6798ca7f9e630fc511ee0a4028

**Comment by larryhastings** [comment]
New changeset f2492bb6aae061aea47e21fc7e56b7ab9bfdf543 by larryhastings (Victor Stinner) in branch '3.5':
[3.5][Security] bpo-30947, bpo-31170: Update expat from 2.2.1 to 2.2.4 (bpo-3354)
https://github.com/python/cpython/commit/f2492bb6aae061aea47e21fc7e56b7ab9bfdf543

**Comment by vstinner** [comment]
New changeset e6d9fcbb8d0c325e57df08ae8781aafedb71eca2 by Victor Stinner in branch 'master':
bpo-31170: Write unit test for Expat 2.2.4 UTF-8 bug (bpo-3570)
https://github.com/python/cpython/commit/e6d9fcbb8d0c325e57df08ae8781aafedb71eca2

**Comment by vstinner** [comment]
New changeset 5f5da728aec9c4f74cc771fbf30037b64a447514 by Victor Stinner in branch '2.7':
bpo-31170: Write unit test for Expat 2.2.4 UTF-8 bug (bpo-3570) (bpo-3745)
https://github.com/python/cpython/commit/5f5da728aec9c4f74cc771fbf30037b64a447514

**Comment by vstinner** [comment]
New changeset ad051cbce1360ad3055a048506c09bc2a5442474 by Victor Stinner in branch '3.6':
bpo-31170: Write unit test for Expat 2.2.4 UTF-8 bug (bpo-3570) (bpo-3746)
https://github.com/python/cpython/commit/ad051cbce1360ad3055a048506c09bc2a5442474

**Comment by vstinner** [comment]
libexpat has been upgraded to version 2.2.4 in Python 2.7, 3.3, 3.4, 3.5, 3.6 and master.

I added an unit test to Python 2.7, 3.6 and master. I'm not sure about backporting the new unit test to Python 3.3, 3.4 and 3.5.

I close the issue.

**Comment by vstinner** [comment]
Oh, it seems like Steve Dower found an issue on Windows: [PR 3751](https://github.com/python/cpython/pull/3751).

I reopen the issue.

**Comment by larryhastings** [comment]
New changeset 44c1b62939a6192776dc9d093546154044cb2ecb by larryhastings (Steve Dower) in branch '3.5':
[3.5] bpo-31170: Fix inclusion of expat in Windows build projects. (bpo-3751)
https://github.com/python/cpython/commit/44c1b62939a6192776dc9d093546154044cb2ecb

**Comment by larryhastings** [comment]
New changeset 8b11e8de7aedacfbbcc8c780f3c4097396f1d1a3 by larryhastings (Victor Stinner) in branch '3.4':
[3.4] bpo-31170: Fix inclusion of expat in Windows build projects (bpo-3785)
https://github.com/python/cpython/commit/8b11e8de7aedacfbbcc8c780f3c4097396f1d1a3
