### ISSUE TITLE
IDLE hangs with absurdly long __repr__s

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#75351]
BPO | [31168](https://bugs.python.org/issue31168)
--- | :---
Nosy | @terryjreedy, @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-08-10.17:36:06.713>
created_at = <Date 2017-08-10.02:04:45.587>
labels = ['expert-IDLE', 'type-bug', '3.7']
title = 'IDLE hangs with absurdly long __repr__s'
updated_at = <Date 2017-08-10.17:36:06.713>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-10.17:36:06.713>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-08-10.17:36:06.713>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-08-10.02:04:45.587>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 31168
keywords = []
message_count = 2.0
messages = ['300036', '300110']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'bup']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31168'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
Objects with a 500,000+ character \_\_repr__ will cause the IDLE shell to hang and thus lose any progress on open windows. 200,000 (on a decent system) seems to be the tipping point where it can never recover.

**Comment by terryjreedy** [comment]
I am quite aware that tk text widgets (and probably other widgets) have line-length limitations.  Which issue this duplicates depends on what action you propose.  bpo-28840 proposes addressing limits in the docs. bpo-1442493 is about code changes.
