### ISSUE TITLE
Miscellaneous errors in asyncio speedup module

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75368]
BPO | [31185](https://bugs.python.org/issue31185)
--- | :---
Nosy | @vstinner, @giampaolo, @methane, @cjerdonek, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#3076</li><li>python/cpython#3269</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-03.06:31:28.354>
created_at = <Date 2017-08-11.16:28:18.591>
labels = ['extension-modules', 'type-bug', '3.7', 'expert-asyncio']
title = 'Miscellaneous errors in asyncio speedup module'
updated_at = <Date 2020-05-08.08:17:05.358>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-08.08:17:05.358>
actor = 'chris.jerdonek'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-03.06:31:28.354>
closer = 'serhiy.storchaka'
components = ['Extension Modules', 'asyncio']
creation = <Date 2017-08-11.16:28:18.591>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31185
keywords = []
message_count = 9.0
messages = ['300171', '300172', '300174', '300175', '300176', '300177', '301183', '301184', '368427']
nosy_count = 6.0
nosy_names = ['vstinner', 'giampaolo.rodola', 'methane', 'chris.jerdonek', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['3076', '3269']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31185'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed patch fixes miscellaneous errors in asyncio speedup module. It is hard to enumerate they all, but they are mostly NULL dereferencing, reference leaks, and handling exceptions in corner cases.

**Comment by 1st1** [comment]
Adding INADA, he is a co-author/reviewer of that code.

**Comment by 1st1** [comment]
Huge thanks, Serhiy, btw.

**Comment by vstinner** [comment]
"reference leaks" oh? our Refleaks buildbots didn't catch them. Do your new tests reproduce the bugs, to make sure that we don't leak anymore?

**Comment by 1st1** [comment]
> "reference leaks" oh? our Refleaks buildbots didn't catch them.

The test suite for Tasks and Futures is pretty extensive, but it obviously doesn't cover some obscure use cases.

+1 to make sure that any refleak that was discovered should have a new regression test for it.

**Comment by serhiy-storchaka** [comment]
They are occurred in very obscure cases like calling \_\_init__ multiple times. The patch doesn't contain tests for them.

**Comment by serhiy-storchaka** [comment]
New changeset bca4939d806170c3ca5d05f23710d11a8f1669cf by Serhiy Storchaka in branch 'master':
bpo-31185: Fixed miscellaneous errors in asyncio speedup module. (bpo-3076)
https://github.com/python/cpython/commit/bca4939d806170c3ca5d05f23710d11a8f1669cf

**Comment by serhiy-storchaka** [comment]
New changeset 98bbeb78e06d5756491705920e72f9721850c727 by Serhiy Storchaka in branch '3.6':
bpo-31185: Fixed miscellaneous errors in asyncio speedup module. (bpo-3076) (bpo-3269)
https://github.com/python/cpython/commit/98bbeb78e06d5756491705920e72f9721850c727
