### ISSUE TITLE
Suggested Enhancements to zipfile & tarfile command line interfaces

### ISSUE THREAD

**Issue by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [python/cpython#75365]
BPO | [31182](https://bugs.python.org/issue31182)
--- | :---
Nosy | @brettcannon, @serhiy-storchaka, @GadgetSteve
PRs | <li>python/cpython#3084</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-29.20:54:42.344>
created_at = <Date 2017-08-11.08:25:56.339>
labels = ['3.7', 'type-feature', 'library']
title = 'Suggested Enhancements to zipfile & tarfile command line interfaces'
updated_at = <Date 2019-03-29.20:54:42.344>
user = 'https://github.com/GadgetSteve'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-29.20:54:42.344>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-29.20:54:42.344>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2017-08-11.08:25:56.339>
creator = 'Steve Barnes'
dependencies = []
files = []
hgrepos = []
issue_num = 31182
keywords = []
message_count = 3.0
messages = ['300156', '302328', '339148']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'serhiy.storchaka', 'Steve Barnes']
pr_nums = ['3084']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31182'
versions = ['Python 3.7']
```

</p></details>

**Comment by 80c73838-aa1d-43ef-8f08-69c1afb3791f** [comment]
I would like to add to the command line of both tarfile and zipfile interface some additional options that I believe to be useful.

1. Wildcard filename matching for archiving
2. Recursive archiving (with excludes)
3. Append to archive option
4. Compression Selection
 4.1 For zipfile: zip64, bizp2 & lzma (if available)
 4.2 For tarfile: document that gz, xz & bz2 are there and determined by ext.

**Comment by serhiy-storchaka** [comment]
The command-line interface of zipfile and tarfile modules was deliberately kept simple. If you need more complex functionality, just write a script. Python is a programming language!

> 1. Wildcard filename matching for archiving

This is a work for a shell. Interpreting wildcards by a program breaks compatibility and makes impossible to handle files containing special characters. For example it breaks:

    python3 -m zipfile -c myzip.zip "The Book [vol. 5].txt".

No way.

> 2. Recursive archiving (with excludes)

Archiving already is recursive. It may be worth to add an option for adding directories not recursively.

> 3. Append to archive option

May be. I don't know what to do with compressed tar archives.

> 4.1 For zipfile: zip64, bizp2 & lzma (if available)

Would be nice. And this option could force compression for tarfile.

As new features they can be added only in 3.7.
