### ISSUE TITLE
Fix data descriptor detection in inspect.getattr_static

### ISSUE THREAD

**Issue by 87d62d9f-3d27-4eca-a9e2-eba39ffb9e6b** [python/cpython#75367]
BPO | [31184](https://bugs.python.org/issue31184)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka
Superseder | <li>bpo-26103: Contradiction in definition of &quot;data descriptor&quot; between (dotted lookup behavior/datamodel documentation) and (inspect lib/descriptor how-to)</li>
Files | <li>[0001-Fix-data-descriptor-detection-in-inspect.getattr_sta.patch](https://bugs.python.org/file47078/0001-Fix-data-descriptor-detection-in-inspect.getattr_sta.patch "Uploaded as text/plain at 2017-08-11.16:22:09 by davidhalter"): Potential patch that fixes the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-08-11.16:22:11.131>
labels = ['type-bug', 'library', '3.11']
title = 'Fix data descriptor detection in inspect.getattr_static'
updated_at = <Date 2021-12-08.04:22:58.232>
user = 'https://bugs.python.org/davidhalter'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-08.04:22:58.232>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-08-11.16:22:11.131>
creator = 'davidhalter'
dependencies = []
files = ['47078']
hgrepos = []
issue_num = 31184
keywords = ['patch']
message_count = 4.0
messages = ['300170', '300173', '407976', '407985']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'davidhalter']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = '26103'
type = 'behavior'
url = 'https://bugs.python.org/issue31184'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-104517
* gh-104557

**Comment by 87d62d9f-3d27-4eca-a9e2-eba39ffb9e6b** [comment]
inspect.getattr_static is currently not identifying data descriptors the right way.

Data descriptors are defined by having a \_\_get__ attribute and at least one of the \_\_set__ and \_\_delete__ attributes.

Implementation detail: Both \_\_delete__ and \_\_get__ set the same slot called tp_descr_set in CPython.

I have attached a patch that fixes the issue IMO.

**Comment by serhiy-storchaka** [comment]
See also bpo-26103.

**Comment by iritkatriel** [comment]
> 
> Since issue [bpo-26103](https://bugs.python.org/issue?@action=redirect&bpo=26103) has been fixed, it's now clear that my patch is slightly wrong, but I'm happy to fix that if someone is actually going to review it.

@davidhalter   Please do update the patch. And please add a unit test that is currently failing so we can see what bug you are fixing.

**Comment by davidhalter** [comment]
Thanks for bringing it up again. I unfortunately somehow missed @rhettinger's comment on this issue. Will try to give an example as soon as possible.

**Comment by arhadthedev** [comment]
@davidhalter ping

**Comment by davidhalter** [comment]
As soon as possible doesn't mean I have time immediately. It will happen and it's still on my radar.

**Comment by davidhalter** [comment]
Here's my example:

```
import inspect

class DescriptorGet:
    def __get__(self, instance, klass):
        return "Foo"

class DescriptorGetDelete:
    def __get__(self, instance, klass):
        return "Foo"
    def __delete__(self, instance, klass):
        pass

class DescriptorGetSet:
    def __get__(self, instance, klass):
        return "Foo"
    def __set__(self, instance, klass, value):
        pass

class Foo:
    get = DescriptorGet()
    get_delete = DescriptorGetDelete()
    get_set = DescriptorGetSet()

    def __init__(self):
        self.__dict__['get'] = 42
        self.__dict__['get_delete'] = 42
        self.__dict__['get_set'] = 42

for attr in ['get', 'get_delete', 'get_set']:
    print(f'getattr        {attr}', getattr(Foo(), attr))
    print(f'getattr_static {attr}', inspect.getattr_static(Foo(), attr))
```
Output:

```
getattr        get 42
getattr_static get 42
getattr        get_delete Foo
getattr_static get_delete 42
getattr        get_set Foo
getattr_static get_set <__main__.DescriptorGetSet object at 0x7f88b10ab7f0>
```

The `get_delete` case is clearly wrong, because if a normal getattr returns the executed descriptor, we should never get the value of the instance's `__dict__` as a result in the `getattr_static` case. 

@iritkatriel @rhettinger Does this make sense? In case you think it's a bug as well, I'm happy to create a pull request with my patch & a unit test of the `__delete__` case.

**Comment by AlexWaygood** [comment]
Thanks @davidhalter. I agree that this looks like a bug. Just to give a slightly shorter reproducer:

```pycon
>>> class DescriptorGetDelete:
...     def __get__(self, instance, klass):
...         return 'foo'
...     def __delete__(self, instance, klass): pass
...
>>> class Foo:
...     get_delete = DescriptorGetDelete()
...     def __init__(self):
...         self.__dict__['get_delete'] = 42
...
>>> foo = Foo()
>>> foo.get_delete
'foo'
>>> import inspect
>>> inspect.getattr_static(foo, 'get_delete')
42
```

The result of the last call should probably be `<__main__.DescriptorGetDelete object at 0x000001D9BF998DA0>` rather than `42`.

If you file a PR for this issue, feel free to ping me on it -- I'd be happy to review it.

**Comment by carljm** [comment]
The fix here is to also check for `__delete__` method, not just `__set__` method. To be clear, despite the resolution of #70291 (which I think was [resolved incorrectly](https://github.com/python/cpython/issues/70291#issuecomment-1499279902)), the check for `__get__` method here is correct and should remain.

**Comment by furkanonder** [comment]
@carljm The issue seems to have been resolved. We can close the issue.
