### ISSUE TITLE
suboptimal code in Py_ReprEnter()

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75370]
BPO | [31187](https://bugs.python.org/issue31187)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @orenmn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-17.13:16:37.754>
created_at = <Date 2017-08-12.10:37:01.983>
labels = ['interpreter-core', '3.7', 'performance']
title = 'suboptimal code in Py_ReprEnter()'
updated_at = <Date 2017-08-17.13:16:37.753>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-17.13:16:37.753>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-17.13:16:37.754>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-08-12.10:37:01.983>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31187
keywords = []
message_count = 2.0
messages = ['300193', '300217']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'Oren Milman']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31187'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
in [Objects/object.c](https://github.com/python/cpython/blob/main/Objects/object.c), Py_ReprEnter() does the following:
    - try to retrieve the Py_Repr list from the thread-state dict.
    - in case the list is not in the dict, add it to the dict as an empty list.
    - check whether the received object is in the Py_Repr list, even in case the
      list was just created, and guaranteed to be empty.


```c
I propose to put this check inside an else clause, so that it wouldn't take
place in case the list is guaranteed to be empty, i.e.:
    list = _PyDict_GetItemId(dict, &PyId_Py_Repr);
    if (list == NULL) {
        list = PyList_New(0);
        ...
    }
    else {
        i = PyList_GET_SIZE(list);
        while (--i >= 0) {
            if (PyList_GET_ITEM(list, i) == obj)
                return 1;
        }
    }
```


I ran the test suite, and it seems that this change doesn't break anything, so
I would be happy to open a PR for it.

**Comment by serhiy-storchaka** [comment]
PyList_GET_SIZE(list) is cheap (especially in comparison of \_PyDict_GetItemId(), \_PyDict_SetItemId() and PyList_New()), and its tiny overhead can be avoided at most once per thread's lifetime. I'm sure you can't measure the effect of this change.

If surrounding code be modified for other reasons, may be your change could be applied. But it alone just makes a code churn.
