### ISSUE TITLE
Fix grammar in threading.Barrier docs

### ISSUE THREAD

**Issue by 76c7b998-47d6-4120-bc2c-1439767e764a** [python/cpython#75374]
BPO | [31191](https://bugs.python.org/issue31191)
--- | :---
Nosy | @Mariatta, @schedutron
PRs | <li>python/cpython#3080</li><li>python/cpython#3224</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-27.22:19:32.174>
created_at = <Date 2017-08-12.21:00:27.584>
labels = ['3.7', 'docs']
title = 'Fix grammar in threading.Barrier docs'
updated_at = <Date 2017-08-27.22:19:32.173>
user = 'https://github.com/schedutron'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-27.22:19:32.173>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-27.22:19:32.174>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-08-12.21:00:27.584>
creator = 'schedutron'
dependencies = []
files = []
hgrepos = []
issue_num = 31191
keywords = []
message_count = 2.0
messages = ['300261', '300930']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'schedutron']
pr_nums = ['3080', '3224']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31191'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by Mariatta** [comment]
New changeset 143be366295038b36fc32c44b8e1b48a375eab56 by Mariatta (Saurabh Chaturvedi) in branch 'master':
bpo-31191: Improve grammar in threading.Barrier docs (GH-3080)
https://github.com/python/cpython/commit/143be366295038b36fc32c44b8e1b48a375eab56

**Comment by Mariatta** [comment]
New changeset 2dfafa3c565c0b51920269a891fa270848b378d5 by Mariatta in branch '3.6':
bpo-31191: Improve grammar in threading.Barrier docs (GH-3080) (GH-3224)
https://github.com/python/cpython/commit/2dfafa3c565c0b51920269a891fa270848b378d5
