### ISSUE TITLE
Inconsistent __repr__s for _collections objects

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#75377]
BPO | [31194](https://bugs.python.org/issue31194)
--- | :---
Nosy | @rhettinger, @bitdancer, @serhiy-storchaka, @vedgar, @mr-nfamous
Superseder | <li>bpo-27541: Repr of collection&#x27;s subclasses</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-08-15.14:54:52.945>
created_at = <Date 2017-08-13.16:12:55.189>
labels = ['3.7', 'type-feature', 'library']
title = 'Inconsistent __repr__s for _collections objects'
updated_at = <Date 2017-08-15.14:54:52.943>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-15.14:54:52.943>
actor = 'r.david.murray'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-08-15.14:54:52.945>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-08-13.16:12:55.189>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 31194
keywords = []
message_count = 4.0
messages = ['300222', '300272', '300297', '300298']
nosy_count = 5.0
nosy_names = ['rhettinger', 'r.david.murray', 'serhiy.storchaka', 'veky', 'bup']
pr_nums = []
priority = 'low'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '27541'
type = 'enhancement'
url = 'https://bugs.python.org/issue31194'
versions = ['Python 3.7']
```

</p></details>

**Comment by df79943f-4aee-4531-a00d-c6b12816eb70** [comment]
With the new C implementation of collections.OrderedDict, its repr correctly uses the subclass's name, unlike deque and defaultdict.

```py
class Thing(_collections.OrderedDict):
    pass
>>> Thing()
Thing([])

class Thing(_collections.deque):
    pass
>>> Thing()
deque([])
```

**Comment by rhettinger** [comment]
IIRC, deque() did this to better match the behavior of list().  Not everything in Python is consistent and sometimes we have to pick and choose between what we want to be consistent with.  For the most part, the decisions have worked out well in practice (deque.\_\_repr__ hasn't seemed to bother anyone in its dozen year history).

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
More and more, Python looks to me like a certain language that I thought I had left behind a long time ago.

       [...] Each  operator  decides  which sort of scalar it
       would be  most  appropriate  to  return.   
       [...] In  general, they do what you want,
       unless you want consistency.

Maybe it's just a sign of growing up. :-)

**Comment by bitdancer** [comment]
This is a duplicate of bpo-27541.
