### ISSUE TITLE
Make any() and all() work with async generators

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#75378]
BPO | [31195](https://bugs.python.org/issue31195)
--- | :---
Nosy | @brettcannon, @vstinner, @giampaolo, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-14.17:45:53.423>
created_at = <Date 2017-08-13.18:41:23.954>
labels = ['3.7', 'library']
title = 'Make any() and all() work with async generators'
updated_at = <Date 2017-08-14.17:45:53.422>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-14.17:45:53.422>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-14.17:45:53.423>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2017-08-13.18:41:23.954>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 31195
keywords = []
message_count = 3.0
messages = ['300224', '300225', '300256']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'vstinner', 'giampaolo.rodola', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31195'
versions = ['Python 3.7']
```

</p></details>

**Comment by brettcannon** [comment]
It would be great if I could do something like:

```py
  if any(x for async x in aiter()): ...
```


But as of right now, any() complains that "TypeError: 'async_generator' object is not iterable". I would assume that any() and all() could be updated to look for \_\_aiter__() instead of just \_\_iter__() and do the right thing in either case? Or am I missing something subtle here?

**Comment by 1st1** [comment]
> Or am I missing something subtle here?

We'll need to make any() and all() coroutines.  Not simple coroutines though, but weird "hybrid" functions that preserve the old semantics + implement async stuff.

I don't think this is a very good idea.  Maybe we should think about "asyncitertools" package with functions like "anext", "aiter", "async_all", "async_chain", etc.

**Comment by brettcannon** [comment]
I figured there was something. :( Closing this as "rejected".
