### ISSUE TITLE
socket.IP_PKTINFO is missing from python

### ISSUE THREAD

**Issue by d049e23d-b40f-4458-aaee-d3c564037da9** [python/cpython#75386]
BPO | [31203](https://bugs.python.org/issue31203)
--- | :---
Nosy | @aixtools, @ZackerySpytz, @guerby, @ovv
PRs | <li>python/cpython#3161</li><li>python/cpython#20029</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-08-14.14:59:44.401>
labels = ['type-feature', 'library', '3.9']
title = 'socket.IP_PKTINFO is missing from python'
updated_at = <Date 2020-05-10.23:09:05.545>
user = 'https://github.com/guerby'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-10.23:09:05.545>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-08-14.14:59:44.401>
creator = 'guerby'
dependencies = []
files = []
hgrepos = []
issue_num = 31203
keywords = ['patch']
message_count = 3.0
messages = ['300248', '300249', '327001']
nosy_count = 5.0
nosy_names = ['`', 'Michael.Felt', 'ZackerySpytz', 'guerby', 'qdawans']
pr_nums = ['3161', '20029']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31203'
versions = ['Python 3.9']
```

</p></details>

**Comment by d049e23d-b40f-4458-aaee-d3c564037da9** [comment]
The constant socket.IP_PKTINFO is missing.

Definition on Linux:

http://elixir.free-electrons.com/linux/v4.12.7/source/include/uapi/linux/in.h#L96

Exemple code that would benefit from the definition:

https://chiliproject.tetaneutral.net/projects/tetaneutral/wiki/Netconsole#nagios-selectors

Note: socket.IPV6_PKTINFO is defined :).

**Comment by d049e23d-b40f-4458-aaee-d3c564037da9** [comment]
Probable fix in [Modules/socketmodule.c](https://github.com/python/cpython/blob/main/Modules/socketmodule.c) after /* IPv4 [gs]etsockopt options \*/ add:

```c
#ifdef  IP_PKTINFO
    PyModule_AddIntMacro(m, IP_PKTINFO);
#endif
```

**Comment by kumaraditya303** [comment]
Superseded by https://github.com/python/cpython/issues/100813
