### ISSUE TITLE
IDLE, configdialog: Factor out KeysPage class from ConfigDialog

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#75388]
BPO | [31205](https://bugs.python.org/issue31205)
--- | :---
Nosy | @terryjreedy, @ambv, @csabella
PRs | <li>python/cpython#3096</li><li>python/cpython#3097</li><li>python/cpython#3154</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-08-15.23:14:03.299>
created_at = <Date 2017-08-15.01:13:03.385>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'IDLE, configdialog: Factor out KeysPage class from ConfigDialog'
updated_at = <Date 2017-08-25.16:31:42.367>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-25.16:31:42.367>
actor = 'lukasz.langa'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-08-15.23:14:03.299>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-08-15.01:13:03.385>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 31205
keywords = []
message_count = 12.0
messages = ['300273', '300275', '300292', '300301', '300312', '300315', '300316', '300544', '300583', '300722', '300734', '300845']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'lukasz.langa', 'cheryl.sabella']
pr_nums = ['3096', '3097', '3154']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31205'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
Do as did with bpo-31050 and GenPage class.  This should be done \*before* bpo-31001, highlights test.

**Comment by terryjreedy** [comment]
Let me know if you start on this.

**Comment by csabella** [comment]
I'll work on this today.

**Comment by csabella** [comment]
I ran into an issue with the three calls to functions in ConfigDialog (deactivate_current_config, activate_config_changes, and save_all_changed_extensions) from within the KeysPage class.  I tried to minimize the changes by just creating self.cd for the ConfigDialog instance.  Besides that, the changes were the same as the FontPage and GenPage.

**Comment by terryjreedy** [comment]
New changeset e36d9f5568093b3885da62a0bf0fdfbe3771672b by Terry Jan Reedy (Cheryl Sabella) in branch 'master':
bpo-31205: IDLE: Factor KeysPage class from ConfigDialog (bpo-3096)
https://github.com/python/cpython/commit/e36d9f5568093b3885da62a0bf0fdfbe3771672b

**Comment by terryjreedy** [comment]
The change to configdialog is basically a block move with a few edits.  The resulting diff is so complicated that git could not apply it cleanly to the identical code in 3.6.  We should do multiple PRs for the highlight group.

**Comment by terryjreedy** [comment]
New changeset ff4b222b029f9977a4509d8697ba2b82c09b477a by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31205: IDLE: Factor KeysPage class from ConfigDialog (GH-3096) (bpo-3097)
https://github.com/python/cpython/commit/ff4b222b029f9977a4509d8697ba2b82c09b477a

**Comment by terryjreedy** [comment]
New changeset a32e40561a24de373d1c5a437a8aa329758ba8e4 by Terry Jan Reedy (Cheryl Sabella) in branch 'master':
bpo-31206: IDLE: Factor HighPage class from ConfigDialog (bpo-3141)
https://github.com/python/cpython/commit/a32e40561a24de373d1c5a437a8aa329758ba8e4

**Comment by terryjreedy** [comment]
New changeset 764e282158df0d7d6d7e0c72f38756c979a36539 by Terry Jan Reedy (Cheryl Sabella) in branch '3.6':
[3.6] bpo-31206: IDLE: Factor HighPage class from ConfigDialog (GH-3141) (bpo-3154)
https://github.com/python/cpython/commit/764e282158df0d7d6d7e0c72f38756c979a36539

**Comment by ambv** [comment]
I don't understand why python/cpython#47347 was introduced to 3.6.2. This doesn't look like a bugfix?

**Comment by terryjreedy** [comment]
Reading PEP-434, special rules for IDLE, should mostly answer your question.

**Comment by ambv** [comment]
Oh, forgot about this exception, sorry! Thanks for the clarification.
