### ISSUE TITLE
os.walk has a bug on Windows

### ISSUE THREAD

**Issue by dea96370-4ef0-4c32-ab9a-2996c52bbf53** [python/cpython#75397]
BPO | [31214](https://bugs.python.org/issue31214)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @lovettchris

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-15.23:10:59.580>
created_at = <Date 2017-08-15.22:41:38.982>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'os.walk has a bug on Windows'
updated_at = <Date 2017-08-15.23:27:33.975>
user = 'https://github.com/lovettchris'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-15.23:27:33.975>
actor = 'clovett'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-15.23:10:59.580>
closer = 'r.david.murray'
components = ['Windows']
creation = <Date 2017-08-15.22:41:38.982>
creator = 'clovett'
dependencies = []
files = []
hgrepos = []
issue_num = 31214
keywords = []
message_count = 3.0
messages = ['300313', '300314', '300320']
nosy_count = 6.0
nosy_names = ['paul.moore', 'peter.otten', 'tim.golden', 'zach.ware', 'steve.dower', 'clovett']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31214'
versions = ['Python 3.6']
```

</p></details>

**Comment by dea96370-4ef0-4c32-ab9a-2996c52bbf53** [comment]
When I walk a directory recursively, it is tacking on an additional non-existant file from one of the subdirectories.  Here's the code:

```py
    def copy_dir(self, src, dest):
        result = sftp.mkdir(dest)
        for dirname, dirnames, filenames in os.walk(src):
            for subdirname in dirnames:
                print("entering dir:" + subdirname)
                self.copy_dir(os.path.join(src, subdirname), os.path.join(dest, subdirname))
            for filename in filenames:
                print("copying:" + filename)
```


Here's the output:

entering dir:include
copying:CallbackInterface.h
copying:ClockInterface.h
entering dir:tcc
copying:CallbackInterface.tcc
copying:CMakeLists.txt
copying:darknet.i
copying:darknet.i.h
copying:darknet.obj
copying:darknet.py
copying:darknetImageNetLabels.txt
copying:darknetPYTHON_wrap.cxx
copying:darknetPYTHON_wrap.h
copying:darknet_config.json
copying:demo.py
copying:demoHelper.py
copying:OpenBLASSetup.cmake
copying:runtest.sh
copying:schoolbus.png
copying:CallbackInterface.h
copying:ClockInterface.h
copying:CallbackInterface.tcc

The last 3 files listed here doesn't exist, they are a repeat of the files found in the subdirectories.

**Comment by f7385517-0a24-49a2-83fd-f4eca87773fa** [comment]
Read the documentation of os.walk() again. It already walks the complete directory tree starting with src. 

When you invoke it again by calling your copy_dir() method recursively you will of course see once more the files and directories in the respective subdirectory.

**Comment by dea96370-4ef0-4c32-ab9a-2996c52bbf53** [comment]
Oh, my bad then. Apologies for the noise in your system.
