### ISSUE TITLE
distutils/util.py get_platform() does not identify linux-i686 platforms

### ISSUE THREAD

**Issue by 3d09c3c3-422b-4c99-b544-01ffadb7a9a5** [python/cpython#75394]
BPO | [31211](https://bugs.python.org/issue31211)
--- | :---
Nosy | @jaraco, @merwok, @zooba, @dstufft, @siming85

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-02-03.18:19:05.697>
created_at = <Date 2017-08-15.16:20:29.892>
labels = ['3.7', 'library']
title = 'distutils/util.py get_platform() does not identify linux-i686 platforms'
updated_at = <Date 2021-02-03.18:19:05.697>
user = 'https://github.com/siming85'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-03.18:19:05.697>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2021-02-03.18:19:05.697>
closer = 'steve.dower'
components = ['Distutils']
creation = <Date 2017-08-15.16:20:29.892>
creator = 'siming85'
dependencies = []
files = []
hgrepos = []
issue_num = 31211
keywords = []
message_count = 5.0
messages = ['300300', '300318', '300387', '300515', '386322']
nosy_count = 5.0
nosy_names = ['jaraco', 'eric.araujo', 'steve.dower', 'dstufft', 'siming85']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31211'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3d09c3c3-422b-4c99-b544-01ffadb7a9a5** [comment]
in CentOS installations where both 32 and 64 bit libraries can co exist, and when python is compiled to run with 32-bit libraries (i686)

```pycon
>>> from distutils.util import get_platform
>>> get_platform()
'linux-x86_64'
```


because the api only looks at OS flavor and not the actual binary architecture.

this string is used as part of PEP-425 tags in the built wheel/egg file:
my_package-3.3.0-cp34-cp34m-linux-x86_64.whl

but this creates a mismatch with PIP - pip.pep425tags returns "linux-i686" instead on the same python instance, addressed by:

```py
# snippet pip code
def _is_running_32bit():
    return sys.maxsize == 2147483647
    
if result == "linux_x86_64" and _is_running_32bit():
    # 32 bit Python program (running on a 64 bit Linux): pip should only
    # install and run 32 bit compiled extensions in that case.
    result = "linux_i686"
```


so the end result is any packages built with sdist_wheel (using setuptools/distutils) is not installable on the same instance.

Of course the workaround is to overwrite that and provide --plat-name linux_i686. 

but the question is - shouldn't the tags line up?

**Comment by merwok** [comment]
Hello!  Your analysis sounds right, but this is the wrong place.  distutils doesn’t know about wheels, it’s setuptools and/or the wheel module that generate them, and pip and others who consumes them.  Please report the issue to the setuptools and/or wheel bug trackers (see https://packaging.python.org/key_projects/ ) and I’ll close this one.

**Comment by 3d09c3c3-422b-4c99-b544-01ffadb7a9a5** [comment]
Hi Eric

I understand where you are coming from, but I disagree with having to raise this to 3rd party tools.

both wheel/pip makes calls to distutils.util.get_platform(). Fixing it in one location would fix it across the board.

In addition, taking setuptools & pip out of picture (uninstalling), using just distutils.core.setup() and doing a bdist (built-in command available in distutils) is still generating a wrong tag in linux 32-bit arch.

pkg-1.0.0.linux-x86_64.tar.gz

within distutils.util.get_platform() the code under sunos makes attempts to identify the correct bitness:
            bitness = {2147483647:"32bit", 9223372036854775807:"64bit"}
            machine += ".%s" % bitness[sys.maxsize]

why would the linux logic not handle the same problem?

**Comment by merwok** [comment]
> both wheel/pip makes calls to distutils.util.get_platform(). Fixing it in one location
> would fix it across the board.

True, but it may have unintended effects in other places that disrupt or break parts of the CPython build process, or downstream packaging toolchains.

> using just distutils.core.setup() and doing a bdist (built-in command available in
> distutils) is still generating a wrong tag in linux 32-bit arch.

I would say that this is irrelevant, since these kinds of bdist are not well defined and not really used.

> within distutils.util.get_platform() the code under sunos makes attempts to identify the \> correct bitness: [...]
> why would the linux logic not handle the same problem?

That’s always the question with distutils, and the reason for us being over-cautious with these requests for changes.  One needs to do VCS archaeology to understand if a specific line was a conscious decision, an assumption, an oversight or a mistake.  My suggestion of bringing this to setuptools is because they have a much faster release cycle, and broad testing.  They can change only the wheel compatibility tags and get feedback immediately, whereas changing distutils.util.get_plaform may break many things and we’ll only know in a couple years when the next release is packaged by distributions and third-party vendors.

[removing Raymond from nosy and adding Jason the setuptools maintainer]
