### ISSUE TITLE
Add version changed notes for OpenSSL 1.1.0 compatibility

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#75398]
BPO | [31215](https://bugs.python.org/issue31215)
--- | :---
Nosy | @ncoghlan, @tiran, @storymode7, @miss-islington
PRs | <li>python/cpython#7346</li><li>python/cpython#7525</li><li>python/cpython#7526</li><li>python/cpython#7541</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-09.01:29:20.432>
created_at = <Date 2017-08-16.05:17:39.527>
labels = ['easy', '3.8', 'type-feature', '3.7', 'docs']
title = 'Add version changed notes for OpenSSL 1.1.0 compatibility'
updated_at = <Date 2018-06-09.01:29:20.431>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-09.01:29:20.431>
actor = 'ncoghlan'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-06-09.01:29:20.432>
closer = 'ncoghlan'
components = ['Documentation']
creation = <Date 2017-08-16.05:17:39.527>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 31215
keywords = ['patch', 'easy']
message_count = 7.0
messages = ['300326', '300331', '318456', '318759', '319044', '319045', '319129']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'christian.heimes', 'docs@python', 'storymode7', 'miss-islington']
pr_nums = ['7346', '7525', '7526', '7541']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31215'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ncoghlan** [comment]
https://bugs.python.org/issue26470 updated the ssl and hashlib modules in 2.7 and 3.5+ to be compatible with OpenSSL 1.1.0.

However, it's currently unclear what the \*minimum* versions actually are for platforms that want to drop support for OpenSSL 1.0.x, and it's particularly unclear in 2.7, as that lacks the deprecation warning for OpenSSL 0.9.8, 1.0.0 and 1.0.1 that was introduced in Python 3.6.

This doesn't rise to the level of something to be documented as a new feature in the 2.7 What's New, but I think a version changed note in the opening section of the `ssl` module documentation would be appropriate:

2.7 branch:

    .. versionchanged: 2.7.13
       Updated to support linking with OpenSSL 1.1.0

3.6 and master branches (immediately before the 3.6 deprecation notice):

    .. versionchanged: 3.5.3
       Updated to support linking with OpenSSL 1.1.0

**Comment by tiran** [comment]
+1

For reference, Python 3.5 received OpenSSL 1.1.0 support in 3.5.3.
