### ISSUE TITLE
del expects __delitem__ if __setitem__ is defined

### ISSUE THREAD

**Issue by 9c572669-04c8-4fe6-89ec-9bdb2bcad992** [python/cpython#75401]
BPO | [31218](https://bugs.python.org/issue31218)
--- | :---
Nosy | @rhettinger, @bitdancer, @hongweipeng, @tirkarthi, @iritkatriel
Files | <li>[delitem_example.py](https://bugs.python.org/file47085/delitem_example.py "Uploaded as text/plain at 2017-08-16.10:48:17 by raumzeitkeks"): Minimal example demonstrating the differing behaviour</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-08.19:38:45.031>
created_at = <Date 2017-08-16.10:48:18.005>
labels = ['interpreter-core', 'type-bug', '3.11']
title = 'del expects __delitem__ if __setitem__ is defined'
updated_at = <Date 2021-07-08.19:38:45.030>
user = 'https://bugs.python.org/raumzeitkeks'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-08.19:38:45.030>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-08.19:38:45.031>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-08-16.10:48:18.005>
creator = 'raumzeitkeks'
dependencies = []
files = ['47085']
hgrepos = []
issue_num = 31218
keywords = []
message_count = 5.0
messages = ['300346', '300354', '327857', '397037', '397167']
nosy_count = 6.0
nosy_names = ['rhettinger', 'r.david.murray', 'raumzeitkeks', 'hongweipeng', 'xtreak', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31218'
versions = ['Python 3.11']
```

</p></details>

**Comment by 9c572669-04c8-4fe6-89ec-9bdb2bcad992** [comment]
I noticed some odd behaviour on classes defining \_\_setitem__.
Using del on a class defining \_\_setitem__ but not \_\_delitem__ results in "AttributeError: \_\_delitem__".
On classes definig neiter \_\_setitem__ nor \_\_delitem__ on the other hand this results in "TypeError: 'WithoutSetItem' object doesn't support item deletion".

See the appended example script.

**Comment by bitdancer** [comment]
I'm not sure we would consider this a bug (the message is accurate), but I wouldn't object to fixing it, since that would indeed seem more consistent with how \_\_delitem__ and del are defined in the language reference.
