### ISSUE TITLE
allow hashlib `update' to accept str

### ISSUE THREAD

**Issue by 64afb080-17d2-4ec9-8ce8-06d407d3325a** [python/cpython#75408]
BPO | [31225](https://bugs.python.org/issue31225)
--- | :---
Nosy | @gpshead, @pitrou, @tiran, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-17.12:24:43.646>
created_at = <Date 2017-08-17.10:59:35.000>
labels = ['3.7', 'type-feature', 'library']
title = "allow hashlib `update' to accept str"
updated_at = <Date 2017-08-17.21:56:57.084>
user = 'https://bugs.python.org/ksqsf'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-17.21:56:57.084>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-17.12:24:43.646>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-08-17.10:59:35.000>
creator = 'ksqsf'
dependencies = []
files = []
hgrepos = []
issue_num = 31225
keywords = []
message_count = 4.0
messages = ['300406', '300409', '300411', '300459']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'pitrou', 'christian.heimes', 'serhiy.storchaka', 'ksqsf']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31225'
versions = ['Python 3.7']
```

</p></details>

**Comment by 64afb080-17d2-4ec9-8ce8-06d407d3325a** [comment]
It'll be nice if \`update' can accept str directly, rather than str.encode first.

One of the most common use cases is "m.update(s.encode())", so it shouldn't make a big difference to just use "m.update(s)"; after all, users who want to specify encoding explicitly can still do so.

**Comment by pitrou** [comment]
This will never happen as this is precisely the kind of confusion Python 3 was designed to avoid.

**Comment by serhiy-storchaka** [comment]
Explicit is better than implicit.

It is easy to add ".encode()" in the user code if it needs this.  Adding this feature has non-zero (and actually not a small) cost. Since update() is not just a method, but a part of a protocol, you need to update all implementations. On other hand, raising an error on string argument can help to catch an error if a string unexpectedly occurred instead of a bytes object.

**Comment by tiran** [comment]
Yes, what Antoine and Serhiy said.
