### ISSUE TITLE
Backport the new custom "print >> sys.stderr" error message?

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#75415]
BPO | [31232](https://bugs.python.org/issue31232)
--- | :---
Nosy | @warsaw, @rhettinger, @ncoghlan, @ericvsmith, @ned-deily, @encukou, @serhiy-storchaka
PRs | <li>python/cpython#3155</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-19.07:00:45.977>
created_at = <Date 2017-08-18.11:07:17.473>
labels = ['type-feature']
title = 'Backport the new custom "print >> sys.stderr" error message?'
updated_at = <Date 2017-08-19.07:00:45.976>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-19.07:00:45.976>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-19.07:00:45.977>
closer = 'ncoghlan'
components = []
creation = <Date 2017-08-18.11:07:17.473>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 31232
keywords = []
message_count = 9.0
messages = ['300486', '300494', '300498', '300521', '300523', '300525', '300566', '300568', '300570']
nosy_count = 7.0
nosy_names = ['barry', 'rhettinger', 'ncoghlan', 'eric.smith', 'ned.deily', 'petr.viktorin', 'serhiy.storchaka']
pr_nums = ['3155']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31232'
versions = ['Python 3.6']
```

</p></details>

**Comment by ncoghlan** [comment]
https://bugs.python.org/issue30721 introduces a new custom error message, such that in 3.7+ "print \>\> sys.stderr" will report:

```
>>> import sys
>>> print >> sys.stderr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
```

This is quite clearly an enhancement to the error reporting rather than a bug fix, but similar to the syntax errors for print statements without parentheses, it's an enhancement that only touches an error handling code path (specifically, the one where \>\> is already in the process of raising TypeError after operand coercion failed), and relates to an issue that a lot of ad hoc Python scripts are likely to encounter.

As such, before I propose it as a downstream patch for Fedora's Python 3.6 stack, I figured I'd propose it as an upstream maintenance backport first.

**Comment by ericvsmith** [comment]
I'm in favor of backporting to 3.6. It's not an intrusive change and is helpful in porting 2.x scripts.

**Comment by ned-deily** [comment]
I am OK with adding it to 3.6.x.

**Comment by warsaw** [comment]
It's probably fine, since it should be a rare occurrence, but it of course has the potential to break things like tests (doc and otherwise).  Unlikely, but it should be pointed out.  Still, I'm also fine with backporting it.

**Comment by rhettinger** [comment]
But this backport would break my code:

```pycon
    >>> print = 10
    >>> print >> 1
    5
```


Just kidding ;-)

+1 for the backport.  It will likely save some headaches.

**Comment by serhiy-storchaka** [comment]
It will not break this code. The only visible effect is changing error messages of some TypeError exceptions.

**Comment by ncoghlan** [comment]
The condition we (mostly Serhiy) came up with for the check is actually kinda neat, since it's based on the value of the LHS and is hard to trigger accidentally:

```
>>> printf = print
>>> print = 10
>>> print >> 1
5
>>> printf >> 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and 'int'. Did you mean "print(<message>, file=<output_stream>)"
```

Anyway, I'll put together a PR that combines both the original patch and the follow up fix to add the missing question mark.

**Comment by ncoghlan** [comment]
New changeset 1a05e87ec75436d818f05a5dabcecaea67334cbd by Nick Coghlan in branch '3.6':
[3.6] bpo-31232: Backport custom print rshift message (GH-3155)
https://github.com/python/cpython/commit/1a05e87ec75436d818f05a5dabcecaea67334cbd

**Comment by ncoghlan** [comment]
Thanks all!
