### ISSUE TITLE
Travis CI mac test broken: ./python: is a directory

### ISSUE THREAD

**Issue by 12e2b808-f665-48aa-b07a-049efb374e4b** [python/cpython#75414]
BPO | [31231](https://bugs.python.org/issue31231)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @bitdancer, @sn0wle0pard
PRs | <li>python/cpython#3134</li><li>python/cpython#3174</li><li>python/cpython#3175</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-18.15:32:40.954>
created_at = <Date 2017-08-18.06:38:47.416>
labels = ['OS-mac', '3.7']
title = 'Travis CI mac test broken: ./python: is a directory'
updated_at = <Date 2017-08-22.01:40:30.653>
user = 'https://github.com/sn0wle0pard'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-22.01:40:30.653>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-18.15:32:40.954>
closer = 'vstinner'
components = ['macOS']
creation = <Date 2017-08-18.06:38:47.416>
creator = 'han.lee'
dependencies = []
files = []
hgrepos = []
issue_num = 31231
keywords = []
message_count = 9.0
messages = ['300474', '300500', '300501', '300502', '300503', '300506', '300508', '300656', '300663']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'r.david.murray', 'han.lee']
pr_nums = ['3134', '3174', '3175']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31231'
versions = ['Python 3.7']
```

</p></details>

**Comment by 12e2b808-f665-48aa-b07a-049efb374e4b** [comment]
CPython: master branch

In mac and window create python.exe not python https://github.com/python/cpython/blob/master/Makefile.pre.in#L154

But Travis CI and docs use ./python command for test
https://docs.python.org/devguide/

https://travis-ci.org/python/cpython/jobs/265843638
/Users/travis/.travis/job_stages: line 73: ./python: is a directory

**Comment by bitdancer** [comment]
The docs you point to are correct (they mention python.exe).  The Travis log also shows it using python.exe.  So the error message about the directory must be about some other operation than just running the python command.

**Comment by vstinner** [comment]
The error comes from "./python -m test.pythoninfo": see bpo-30871.

Attached PR should fix this bug.

**Comment by bitdancer** [comment]
Ah, this is probably the issue: https://github.com/python/cpython/pull/3134

**Comment by bitdancer** [comment]
Heh.  I saw the PR but didn't realize it was attached to this issue :)

**Comment by vstinner** [comment]
New changeset 92b1f90143286385c0ff5be98d3721b90580a912 by Victor Stinner in branch 'master':
bpo-31231: Fix pythoninfo in Travis config (bpo-3134)
https://github.com/python/cpython/commit/92b1f90143286385c0ff5be98d3721b90580a912

**Comment by vstinner** [comment]
Thanks Han Lee for the bug report, the issue should now be fixed.

**Comment by vstinner** [comment]
New changeset 29d007bb670b486788f73c2d742b0ad0b679ff13 by Victor Stinner in branch '3.6':
[3.6] bpo-30871: Add test.pythoninfo (bpo-3174)
https://github.com/python/cpython/commit/29d007bb670b486788f73c2d742b0ad0b679ff13

**Comment by vstinner** [comment]
New changeset cce1cb9180dd9143c5b2ce094a52c555b42c7aa8 by Victor Stinner in branch '2.7':
bpo-30871: Add test.pythoninfo (bpo-3174) (bpo-3175)
https://github.com/python/cpython/commit/cce1cb9180dd9143c5b2ce094a52c555b42c7aa8
