### ISSUE TITLE
Add lazy evaluation support for dict.setdefault()

### ISSUE THREAD

**Issue by 1514313d-ad2c-4fcb-a9eb-8968bdf48884** [python/cpython#75423]
BPO | [31240](https://bugs.python.org/issue31240)
--- | :---
Nosy | @rhettinger, @JimDennis, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-20.15:37:46.876>
created_at = <Date 2017-08-20.05:14:06.200>
labels = ['type-feature']
title = 'Add lazy evaluation support for dict.setdefault()'
updated_at = <Date 2017-08-20.15:37:46.875>
user = 'https://github.com/JimDennis'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-20.15:37:46.875>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-20.15:37:46.876>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-08-20.05:14:06.200>
creator = 'jimd'
dependencies = []
files = []
hgrepos = []
issue_num = 31240
keywords = []
message_count = 3.0
messages = ['300596', '300598', '300603']
nosy_count = 3.0
nosy_names = ['rhettinger', 'jimd', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31240'
versions = []
```

</p></details>

**Comment by 1514313d-ad2c-4fcb-a9eb-8968bdf48884** [comment]
Code such as mydict.setdefault('eggs', []) will needlessly incur the cost of instantiating a list even when 'eggs' is already a valid key in mydict.  collections.defaultdict will not do this.  detecting and automatically calling "callable" and "type" objects (implicit laziness) would break cases where callables and types are used as first class values.

Add keyword argument: lazy?  Thus mydict.setdefault('eggs',list, lazy=True) would generate a new list only when necessary while the default would still be to append a reference to list (first class) objects).

**Comment by serhiy-storchaka** [comment]
The advantage of dict.setdefault() is its atomicity. With lazy evaluation of the value it can't be atomic anymore, and can be replaced with the following code:

```py
    if key not in mydict:
        mydict[key] = value
```


I'm -1 for this change. It increases complexity (both semantical and implementational) of dict.setdefault() and doesn't have significant benefit.

**Comment by rhettinger** [comment]
-1 from me as well.

The need has already been fulfilled in other ways (defaultdict and \_\_missing__).  I don't think we need yet another way to do it.

Also, I suspect that the benefit of a lazy instantiation would be more than offset by cost of passing in the arguments (global variable lookup for the list builtin, a load constant for True, and the keyword argument processing).

Lastly, I don't like making the signature more complex or further breaking the already loose symmetry with dict.get() and dict.pop().  Likewise, this isn't parallel with other tools that take a default argument such as min(), max(), getattr(), etc.
