### ISSUE TITLE
checks whether PyArg_ParseTuple returned a negative int

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75426]
BPO | [31243](https://bugs.python.org/issue31243)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3171</li><li>python/cpython#3233</li><li>python/cpython#3235</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-08-29.16:18:10.107>
created_at = <Date 2017-08-21.08:33:08.944>
labels = ['extension-modules', 'easy', '3.7', 'expert-IO', 'type-crash']
title = 'checks whether PyArg_ParseTuple returned a negative int'
updated_at = <Date 2017-08-29.16:18:10.106>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-29.16:18:10.106>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-08-29.16:18:10.107>
closer = 'serhiy.storchaka'
components = ['Extension Modules', 'IO']
creation = <Date 2017-08-21.08:33:08.944>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31243
keywords = ['easy (C)']
message_count = 7.0
messages = ['300613', '300616', '300618', '300977', '300982', '300993', '300994']
nosy_count = 4.0
nosy_names = ['benjamin.peterson', 'stutzbach', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3171', '3233', '3235']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31243'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
according to the docs (https://docs.python.org/3.7/c-api/arg.html?highlight=pyarg_parsetuple#c.PyArg_ParseTuple), PyArg_ParseTuple
returns true for success or false for failure. I also looked at the
implementation in [Python/getargs.c](https://github.com/python/cpython/blob/main/Python/getargs.c), and it seems that indeed PyArg_ParseTuple
can return only 0 or 1.

however, in some places in the codebase, there are checks whether
PyArg_ParseTuple returned a negative int.
I found a bunch in [Modules/_testcapimodule.c](https://github.com/python/cpython/blob/main/Modules/_testcapimodule.c), and one in [Modules/_io/textio.c](https://github.com/python/cpython/blob/main/Modules/_io/textio.c)
in textiowrapper_read_chunk. (hopefully i haven't missed other places.)

this code crashes because of the check in textiowrapper_read_chunk:
import codecs
import \_io
class MyDec():
    def getstate(self):
        return 420
class MyDecWrapper():
    def \_\_call__(self, blabla):
        return MyDec()
quopri = codecs.lookup("quopri")
quopri.\_is_text_encoding = True
quopri.incrementaldecoder = MyDecWrapper()
t = \_io.TextIOWrapper(_io.BytesIO(b'aaaaaa'),
                      newline='\\n', encoding="quopri")
t.read(42)


I guess all of these checks should be changed to check whether PyArg_ParseTuple
returned 0.

also, before this specific call to PyArg_ParseTuple in textiowrapper_read_chunk,
we should check whether 'state' is a tuple.
Moreover, this call shouldn't produce a wrong error message, as explained in
bpo-28261.

**Comment by serhiy-storchaka** [comment]
Do you want to provide a PR Oren?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
yes, soon.
(just wanted to hear your opinion before doing that.)

**Comment by serhiy-storchaka** [comment]
New changeset ba7d7365215d791025d1efd25393c91404f2cfc8 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31243: Fixed PyArg_ParseTuple failure checks. (bpo-3171)
https://github.com/python/cpython/commit/ba7d7365215d791025d1efd25393c91404f2cfc8

**Comment by serhiy-storchaka** [comment]
New changeset c7750c2a3af014a5b742d0159d8957ea95b6c221 by Serhiy Storchaka (Oren Milman) in branch '3.6':
[3.6] bpo-31243: Fixed PyArg_ParseTuple failure checks. (GH-3171) (bpo-3233)
https://github.com/python/cpython/commit/c7750c2a3af014a5b742d0159d8957ea95b6c221

**Comment by serhiy-storchaka** [comment]
New changeset 20958e6d91d11a80d6c664ce6346791259b1d193 by Serhiy Storchaka (Oren Milman) in branch '2.7':
[2.7] bpo-31243: Fixed PyArg_ParseTuple failure checks. (GH-3171) (bpo-3235)
https://github.com/python/cpython/commit/20958e6d91d11a80d6c664ce6346791259b1d193

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Oren!
