### ISSUE TITLE
Asyncio UNIX socket and SOCK_DGRAM

### ISSUE THREAD

**Issue by 79085f79-779f-4b68-b127-e4eff87a65e8** [python/cpython#75428]
BPO | [31245](https://bugs.python.org/issue31245)
--- | :---
Nosy | @vstinner, @1st1, @ovv
PRs | <li>python/cpython#3164</li><li>python/cpython#4594</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-30.13:43:36.111>
created_at = <Date 2017-08-21.14:06:59.680>
labels = ['type-feature', '3.7', 'expert-asyncio']
title = 'Asyncio UNIX socket and SOCK_DGRAM'
updated_at = <Date 2017-11-27.23:34:10.354>
user = 'https://github.com/Ovv'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-27.23:34:10.354>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-30.13:43:36.111>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-08-21.14:06:59.680>
creator = 'qdawans'
dependencies = []
files = []
hgrepos = []
issue_num = 31245
keywords = []
message_count = 3.0
messages = ['300625', '305228', '307102']
nosy_count = 3.0
nosy_names = ['vstinner', 'yselivanov', 'qdawans']
pr_nums = ['3164', '4594']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31245'
versions = ['Python 3.7']
```

</p></details>

**Comment by 79085f79-779f-4b68-b127-e4eff87a65e8** [comment]
Following this discussion: https://groups.google.com/forum/#!searchin/python-tulip/datagram%7Csort:relevance/python-tulip/rpScueoGf1I/WBvEWf8vCgAJ

I added the support for AF_UNIX SOCK_DGRAM is asyncio. Lots of code is coming from the other family/type of socket already implemented.

**Comment by 1st1** [comment]
New changeset fe4ea9cf1ee04f5a60e4ed928d8624b95b031e18 by Yury Selivanov (Quentin Dawans) in branch 'master':
bpo-31245: Asyncio unix socket datagram (bpo-3164)
https://github.com/python/cpython/commit/fe4ea9cf1ee04f5a60e4ed928d8624b95b031e18

**Comment by vstinner** [comment]
New changeset 28e61650b23119b68cd7943ccc01b8b9af1b4103 by Victor Stinner in branch 'master':
bpo-31245: asyncio: Fix typo, isistance =\> isinstance (bpo-4594)
https://github.com/python/cpython/commit/28e61650b23119b68cd7943ccc01b8b9af1b4103
