### ISSUE TITLE
Diameter protocol in Python

### ISSUE THREAD

**Issue by d65d32d1-685b-4a9e-87ab-b6da00dd58ae** [python/cpython#75434]
BPO | [31251](https://bugs.python.org/issue31251)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-21.18:08:56.567>
created_at = <Date 2017-08-21.17:09:22.325>
labels = ['invalid', '3.7', 'library']
title = 'Diameter protocol in Python'
updated_at = <Date 2017-08-21.18:08:56.530>
user = 'https://bugs.python.org/GeorgeLane'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-21.18:08:56.530>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-21.18:08:56.567>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-08-21.17:09:22.325>
creator = 'George Lane'
dependencies = []
files = []
hgrepos = []
issue_num = 31251
keywords = []
message_count = 4.0
messages = ['300643', '300645', '300646', '300647']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'George Lane']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31251'
versions = ['Python 3.7']
```

</p></details>

**Comment by d65d32d1-685b-4a9e-87ab-b6da00dd58ae** [comment]
Diameter protocol in Python

**Comment by serhiy-storchaka** [comment]
Could you provide more information George?

**Comment by d65d32d1-685b-4a9e-87ab-b6da00dd58ae** [comment]
Hi, ¿can you tell me about Diameter protocol implemented by Python?, ¿where
can I found documentation and package for downloading?

Best regards

2017-08-21 14:36 GMT-03:00 Serhiy Storchaka \<report@bugs.python.org\>:

>
> Serhiy Storchaka added the comment:
>
> Could you provide more information George?
>
> \----------
> nosy: +serhiy.storchaka
> status: open -\> pending
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<http://bugs.python.org/issue31251\>
> _______________________________________
>

**Comment by bitdancer** [comment]
This isn't a help forum, it is a place for reporting bugs in Python.  The kind of question you are asking is best asked on the python-list mailing list (see mail.python.org).
