### ISSUE TITLE
unittest fails to properly destruct objects created during setUp if a test fails

### ISSUE THREAD

**Issue by e6a6c686-63dc-4f7c-a397-c0623f3aba64** [python/cpython#75444]
BPO | [31261](https://bugs.python.org/issue31261)
--- | :---
Nosy | @pfmoore, @tjguk, @bitdancer, @zware, @zooba, @MCBama
Files | <li>[test_bug.py](https://bugs.python.org/file47094/test_bug.py "Uploaded as text/plain at 2017-08-22.22:26:00 by @MCBama"): unittest showcasing the unexpected behavior</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-22.23:20:06.279>
created_at = <Date 2017-08-22.22:26:00.693>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'unittest fails to properly destruct objects created during setUp if a test fails'
updated_at = <Date 2017-08-22.23:20:06.277>
user = 'https://github.com/MCBama'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-22.23:20:06.277>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-22.23:20:06.279>
closer = 'r.david.murray'
components = ['Windows']
creation = <Date 2017-08-22.22:26:00.693>
creator = 'MCBama'
dependencies = []
files = ['47094']
hgrepos = []
issue_num = 31261
keywords = []
message_count = 2.0
messages = ['300725', '300730']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'r.david.murray', 'zach.ware', 'steve.dower', 'MCBama']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31261'
versions = ['Python 3.6']
```

</p></details>

**Comment by e6a6c686-63dc-4f7c-a397-c0623f3aba64** [comment]
When running the attached example test dummy objects are created during setUp and destructed at the end of a passing test but when a test fails the dummy object that was created in setUp fails to deconstruct. This leads to cascading errors when writing integration tests where having a "ghost" object sitting in the background and listening to messages is detrimental.

This behavior became apparent when I was writing integration tests making use of a signalling package so I pulled everything that wasn't base python to see if the bug was reproduced and it was. The object that failed to deconstruct when the test failed(0x000001CA971F6208) deconstructs at the end of the entire testcase while the object declared within the test function itself(0x000001CA971F62B0) deconstructs as soon as the test fails out.

The output of the test that I ran was this:

> python -m unittest test_bug.py


test_fail (test_bug.TestBug)
Created \<test_bug.DummyClass object at 0x000001CA971F6208\>
Created local \<test_bug.DummyClass object at 0x000001CA971F62B0\>
F
deleting \<test_bug.DummyClass object at 0x000001CA971F62B0\>


test_pass (test_bug.TestBug)
Created \<test_bug.DummyClass object at 0x000001CA971F62B0\>
.
deleting \<test_bug.DummyClass object at 0x000001CA971F62B0\>


test_passes (test_bug.TestBug)
Created \<test_bug.DummyClass object at 0x000001CA971A5400\>
.
deleting \<test_bug.DummyClass object at 0x000001CA971A5400\>

\======================================================================
FAIL: test_fail (test_bug.TestBug)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Code\test_bug.py", line 27, in test_fail
    self.assertTrue(False)
AssertionError: False is not true
```


----------------------------------------------------------------------
Ran 3 tests in 0.004s

FAILED (failures=1)

deleting \<test_bug.DummyClass object at 0x000001CA971F6208\>

**Comment by bitdancer** [comment]
GC cleanup is not guaranteed to be synchronous.  You are observing normal Python behavior here.  Cleanup does not happen until the TestCase instance is finalized (thus eliminating the self.dummy reference to your DummyClass).  In the case of passing tests, that is after the '.' is printed.  In the case of failing tests, that is after the failure is printed, which isn't until the failure summary is printed at after running all tests.

If it is important to you that DummyClass be finalized, you need to add an addCleanup call to your setUp method that will do whatever finalization you need done.  Including doing 'del self.dummy' (or self.dummy = None) if you need the reference to it gone...but depending on garbage collection is a bad idea, so if you are doing that there is probably something sub-optimal about your design.
