### ISSUE TITLE
Import Package/Module through HTTP/S repository

### ISSUE THREAD

**Issue by 6a9e2fb5-ae19-488d-a74d-a8fdb1dd87a2** [python/cpython#75447]
BPO | [31264](https://bugs.python.org/issue31264)
--- | :---
Nosy | @brettcannon, @ncoghlan, @bitdancer, @ericsnowcurrently, @operatorequals

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-23.14:58:14.329>
created_at = <Date 2017-08-23.10:18:02.276>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'Import Package/Module through HTTP/S repository'
updated_at = <Date 2017-08-24.03:30:18.287>
user = 'https://github.com/operatorequals'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-24.03:30:18.287>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-23.14:58:14.329>
closer = 'r.david.murray'
components = ['Extension Modules']
creation = <Date 2017-08-23.10:18:02.276>
creator = 'operatorequals'
dependencies = []
files = []
hgrepos = ['372']
issue_num = 31264
keywords = []
message_count = 4.0
messages = ['300747', '300755', '300773', '300775']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ncoghlan', 'r.david.murray', 'eric.snow', 'operatorequals']
pr_nums = []
priority = 'normal'
resolution = 'later'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31264'
versions = ['Python 3.7']
```

</p></details>

**Comment by 6a9e2fb5-ae19-488d-a74d-a8fdb1dd87a2** [comment]
A module presented in "https://github.com/operatorequals/httpimport" which provides functionality for package/module loading through HTTP/S, like the golang's "import github.com/someusr/somepkg/subpkg", but for any directory served with HTTP/S.

I believe that this module has to become a core feature, after, of course, the necessary scrutiny!

**Comment by bitdancer** [comment]
This kind of proposal should start with a discussion on the python-ideas mailing list.  You can reopen the issue if there is a consensus for moving forward...but I wouldn't be surprised if this was considered to be a PEP level proposal.

**Comment by ncoghlan** [comment]
Note that we're highly unlikely to ever accept a PEP to provide this natively, as it couples the process of runtime module loading too tightly to what should be private organisational details of the software publication process (domain names, repository names, etc).

We already know from experience with Java component naming that these kinds of approaches simply don't age well for widely adopted software in a distributed development context, as they turn things that shouldn't have any software compatibility implications (renaming a development repository, moving to a different repository hosting provider, selling a company) into major API compatibility management headaches.

While there are some reasonable applications for the feature when it comes to private software modules that are used only within a single (relatively small) organisation, the existence of httpimport also shows that there aren't any further changes needed to the core import system to enable it.

**Comment by bitdancer** [comment]
Indeed, I personally can't imagine a circumstance in which I'd want to use this feature.  Even inside an org.  It also has security implications, which would also make it a harder sell.
