### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by c259cd39-9096-4439-a787-5b8280484f2b** [python/cpython#75445]
BPO | [31262](https://bugs.python.org/issue31262)
--- | :---
Nosy | @bitdancer, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-22.23:25:22.633>
created_at = <Date 2017-08-22.22:52:37.898>
labels = ['3.7', 'invalid', 'docs']
title = 'Documentation Error'
updated_at = <Date 2017-08-22.23:31:39.204>
user = 'https://bugs.python.org/DiptiSherlekar'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-22.23:31:39.204>
actor = 'Dipti Sherlekar'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-22.23:25:22.633>
closer = 'r.david.murray'
components = ['Documentation']
creation = <Date 2017-08-22.22:52:37.898>
creator = 'Dipti Sherlekar'
dependencies = []
files = []
hgrepos = []
issue_num = 31262
keywords = []
message_count = 4.0
messages = ['300727', '300731', '300732', '300733']
nosy_count = 4.0
nosy_names = ['r.david.murray', 'docs@python', 'martin.panter', 'Dipti Sherlekar']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31262'
versions = ['Python 3.7']
```

</p></details>

**Comment by c259cd39-9096-4439-a787-5b8280484f2b** [comment]
Documentation says : In C++ terminology, normally class members (including the data members) are public  

Solution: In C++ the class memebers are private not public by default.

**Comment by bitdancer** [comment]
No, that sentence is telling you what the \*Python*'s behavior is, using C++ terminology.  Unlike C++, where class members are private by default, the Python equivalent of class members are public by default.

If you can figure out a clearer way to phrase that you may reopen the issue with your suggestion.

**Comment by vadmium** [comment]
Assuming this is about the Classes section in the tutorial, you seem to be going down the same track as \<https://github.com/python/cpython/pull/2696\>

**Comment by c259cd39-9096-4439-a787-5b8280484f2b** [comment]
Thanks all.

Dipti
