### ISSUE TITLE
attribute error

### ISSUE THREAD

**Issue by 2f5e086f-362f-4f53-83e2-700494ff43af** [python/cpython#75449]
BPO | [31266](https://bugs.python.org/issue31266)
--- | :---
Nosy | @nixster
Files | <li>[temp1.py](https://bugs.python.org/file47095/temp1.py "Uploaded as text/plain at 2017-08-23.19:38:33 by @nixster"): template from string module</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-24.01:25:16.300>
created_at = <Date 2017-08-23.19:38:33.729>
labels = ['extension-modules', 'type-crash']
title = 'attribute error'
updated_at = <Date 2017-08-24.01:25:16.298>
user = 'https://github.com/nixster'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-24.01:25:16.298>
actor = 'nixster'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-24.01:25:16.300>
closer = 'nixster'
components = ['Extension Modules']
creation = <Date 2017-08-23.19:38:33.729>
creator = 'nixster'
dependencies = []
files = ['47095']
hgrepos = []
issue_num = 31266
keywords = []
message_count = 3.0
messages = ['300763', '300764', '300771']
nosy_count = 2.0
nosy_names = ['peter.otten', 'nixster']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31266'
versions = ['Python 3.6']
```

</p></details>

**Comment by 2f5e086f-362f-4f53-83e2-700494ff43af** [comment]
Hello!
I am just write some program with "string module", after starting my program python give me error about "re module".

My program is a tutorial from DrapsTV from Youtube.

```pytb
Error -->>
Traceback (most recent call last):
  File "temp1.py", line 1, in <module>
    from string import Template
  File "/usr/lib64/python3.6/string.py", line 77, in <module>
    class Template(metaclass=_TemplateMetaclass):
  File "/usr/lib64/python3.6/string.py", line 82, in Template
    flags = _re.IGNORECASE
AttributeError: module 're' has no attribute 'IGNORECASE'
```

**Comment by f7385517-0a24-49a2-83fd-f4eca87773fa** [comment]
You have probably written your own re.py file which shadows the one in the standard library. Once you remove or rename your re.py the error should go away.

**Comment by 2f5e086f-362f-4f53-83e2-700494ff43af** [comment]
Thank you Peter, problem has fixed.

I think, python interpreter must understand if a "temp1.py" will start in same directory with file "re.py", this is not a native module for python and interpreter can ignore re.py from user directory and etc.
