### ISSUE TITLE
[2.7] Enhance PC/VS9.0/ project to produce python.bat, as PCbuild/

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75443]
BPO | [31260](https://bugs.python.org/issue31260)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-08.22:42:17.260>
created_at = <Date 2017-08-22.15:18:17.339>
labels = ['build', 'OS-windows']
title = '[2.7] Enhance PC/VS9.0/ project to produce python.bat, as PCbuild/'
updated_at = <Date 2017-09-08.22:42:17.259>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-08.22:42:17.259>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-08.22:42:17.260>
closer = 'zach.ware'
components = ['Build', 'Windows']
creation = <Date 2017-08-22.15:18:17.339>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31260
keywords = []
message_count = 3.0
messages = ['300704', '301747', '301748']
nosy_count = 5.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'zach.ware']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31260'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
It would be nice to have a python.bat script produced by the [PC/VS9.0/](https://github.com/python/cpython/blob/main/PC/VS9.0) project, as done by the PCbuild/ project.

It would fix the newly added buildbot step "pythoninfo":
https://bugs.python.org/issue30871#msg300703

Without python.bat, it's not easy to get the path to the Python executable from the buildbot configuration.

**Comment by vstinner** [comment]
Zachary Ware added pythoninfo to buildbot VS9.0 builds:
https://github.com/python/buildmaster-config/commit/c1d51a791d63c5e7d05c160ba25babd302fefe83

**Comment by zware** [comment]
I'd rather not go through the gymnastics to actually add python.bat creation to the VS9.0 config, so I'm closing this as rejected.  If someone else finds it useful and wants to provide a patch, I'll review and merge it.
