### ISSUE TITLE
typing module conflicts with  __slots__-classes

### ISSUE THREAD

**Issue by 3033a1eb-eb43-436c-a503-349eaed7802a** [python/cpython#75455]
BPO | [31272](https://bugs.python.org/issue31272)
--- | :---
Nosy | @ilevkivskyi, @grayfall

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-28.10:41:52.741>
created_at = <Date 2017-08-24.18:34:24.915>
labels = ['type-bug', 'library']
title = 'typing module conflicts with  __slots__-classes'
updated_at = <Date 2017-08-28.10:41:52.740>
user = 'https://github.com/grayfall'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-28.10:41:52.740>
actor = 'levkivskyi'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-28.10:41:52.741>
closer = 'levkivskyi'
components = ['Library (Lib)']
creation = <Date 2017-08-24.18:34:24.915>
creator = 'grayfall'
dependencies = []
files = []
hgrepos = []
issue_num = 31272
keywords = []
message_count = 4.0
messages = ['300797', '300854', '300946', '300949']
nosy_count = 2.0
nosy_names = ['levkivskyi', 'grayfall']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31272'
versions = ['Python 3.5']
```

</p></details>

**Comment by 3033a1eb-eb43-436c-a503-349eaed7802a** [comment]
I've got conflicts between Python's typing system and `__slots__`. Here is a small reproducible example.

```py
    from typing import TypeVar, Generic, Sequence
    
    T = TypeVar("T")

    class TestGeneric(Sequence, Generic[T]):
        __slots__ = ("test",)

        def __init__(self, test: T):
            self.test = [test]
        
        def __iter__(self):
            return iter(self.test)
        def __len__(self):
            return len(self.test)
        
        def __contains__(self, item):
            return item in self.test
        
        def __getitem__(self, _):
            return self.test[0]
```


Now whenever I try to specify a content type, e.g.
    
    V = TestGeneric[int]

I get 

    ValueError: 'test' in __slots__ conflicts with class variable

I use `Generics`  in classes without slots a lot, hence I think this error has to be linked to `__slots__`. Moreover, the same class works fine, if you remove the `__slots__`

**Comment by ilevkivskyi** [comment]
I think this is fixed in latest version. I thought it was also backported to Python 3.5.3. What is the version you are using? Could you please try updating to the latest bugfix release? (currently these are 3.5.4 and 3.6.2).

**Comment by 3033a1eb-eb43-436c-a503-349eaed7802a** [comment]
Indeed, this issue has been fixed. Anyway, it is not mentioned in any release notes. Perhaps, this should be mentioned somewhere.

**Comment by ilevkivskyi** [comment]
It is listed in [Misc/NEWS](https://github.com/python/cpython/blob/main/Misc/NEWS) as "minor bug fixes" in typing module, I don't think this is something that deserves a separate line in release notes.
