### ISSUE TITLE
[2.7] unittest: Unicode support in TestCase.skip

### ISSUE THREAD

**Issue by a467d304-eecb-40a7-aa4b-0011a662f427** [python/cpython#75456]
BPO | [31273](https://bugs.python.org/issue31273)
--- | :---
Nosy | @vstinner, @rbtcollins, @ezio-melotti, @voidspace, @serhiy-storchaka
Files | <li>[issue.txt](https://bugs.python.org/file47099/issue.txt "Uploaded as text/plain at 2017-08-24.20:37:12 by Nathan Buckner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-30.15:55:20.087>
created_at = <Date 2017-08-24.20:37:13.004>
labels = ['type-bug', 'library']
title = '[2.7] unittest: Unicode support in TestCase.skip'
updated_at = <Date 2017-10-30.15:55:20.085>
user = 'https://bugs.python.org/NathanBuckner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-30.15:55:20.085>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-30.15:55:20.087>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-08-24.20:37:13.004>
creator = 'Nathan Buckner'
dependencies = []
files = ['47099']
hgrepos = []
issue_num = 31273
keywords = []
message_count = 3.0
messages = ['300802', '305232', '305234']
nosy_count = 6.0
nosy_names = ['vstinner', 'rbcollins', 'ezio.melotti', 'michael.foord', 'serhiy.storchaka', 'Nathan Buckner']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31273'
versions = ['Python 2.7']
```

</p></details>

**Comment by a467d304-eecb-40a7-aa4b-0011a662f427** [comment]
Unicode support for TestCase.skip is broken because the caught SkipTest exception is passed through a str call.
except SkipTest as e:
    self.\_addSkip(result, str(e))
Could be fixed with by changing to unicode(e)

**Comment by vstinner** [comment]
> Could be fixed with by changing to unicode(e)

Replacing str(e) with unicode(e) can introduce Unicode errors regressions. I'm not confident in doing such change late in the old 2.7 branch.

I suggest you to only use native strings (byte strings, "str" type) in Python 2, and slowly upgrade your application to Python 3.

I propose to close this issue as WONT FIX.

**Comment by serhiy-storchaka** [comment]
I concur with Victor. Unlikely this affects many people since skipping messages usually are ASCII strings.

As a workaround you can implement your own skip() method that encodes unicode to 8-bit string.

```py
    def skip(self, reason):
        if isinstance(reason, unicode):
            reason = unicode.encode(reason, 'utf-8')
        TestCase.skip(self, reason)
```
