### ISSUE TITLE
bug in islink() and is_symlink()

### ISSUE THREAD

**Issue by 5cdd8f08-8b62-49e4-b09a-f733264c71a9** [python/cpython#75452]
BPO | [31269](https://bugs.python.org/issue31269)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-24.13:37:57.978>
created_at = <Date 2017-08-24.13:23:52.058>
labels = ['type-feature', 'invalid']
title = 'bug in islink() and is_symlink()'
updated_at = <Date 2017-08-25.06:39:09.391>
user = 'https://bugs.python.org/karaV'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-25.06:39:09.391>
actor = 'karaV'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-24.13:37:57.978>
closer = 'r.david.murray'
components = []
creation = <Date 2017-08-24.13:23:52.058>
creator = 'karaV'
dependencies = []
files = []
hgrepos = []
issue_num = 31269
keywords = []
message_count = 5.0
messages = ['300782', '300784', '300785', '300786', '300828']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'karaV']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31269'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5cdd8f08-8b62-49e4-b09a-f733264c71a9** [comment]
Hi,

I found a problem which can be a bug and want to inform you.

it seems os.islink() and PATH(mypath).is_symlink()  functions doen't work correct when there is linked folder inside the path:

For example I have the following path:
a/b/c/test.txt

if my c folder is link these 2 functions will not show that this path is link

Only if i remove test.txt and use a/b/c path is shows that path is link.


Seems these functions checks only last part of given path not full path and doesn't find if there is link in somewere inside path and shows not correct result.

Interesting to know your opinion regarding it.

**Comment by bitdancer** [comment]
The docs say, eg: "Return True if the path points to a symbolic link".  The path points to a file system object, and it is the object that is being checked, not each component of the path used to get to that object.

**Comment by 5cdd8f08-8b62-49e4-b09a-f733264c71a9** [comment]
Hi David

Thanks for support. one question. I couldn't find a function which will check full path is link or not. Is there any known function\>

>Четверг, 24 августа 2017, 17:38 +04:00 от "R. David Murray" \<report@bugs.python.org\>:
>
>
>R. David Murray added the comment:
>
>The docs say, eg: "Return True if the path points to a symbolic link".  The path points to a file system object, and it is the object that is being checked, not each component of the path used to get to that object.
>
>\----------
>nosy: +r.david.murray
>resolution:  -\> not a bug
>stage:  -\> resolved
>status: open -\> closed
>
>_______________________________________
>Python tracker \< report@bugs.python.org \>
>\< http://bugs.python.org/issue31269 \>
>_______________________________________

**Comment by bitdancer** [comment]
I would phrase that as "check if any of the components of the path are links", at which point one "obvious"[*] answer is "any(x.is_symlink() for x in [*mypath.parents, mypath])".  If the path is absolute, you could use "not (mypath.resolve() == mypath)".

[*] I put that in quotes because it is only obvious once you have a non-trivial amount of experience with programming in Python.

**Comment by 5cdd8f08-8b62-49e4-b09a-f733264c71a9** [comment]
Thanks a lot David

>Четверг, 24 августа 2017, 18:42 +04:00 от "R. David Murray" \<report@bugs.python.org\>:
>
>
>R. David Murray added the comment:
>
>I would phrase that as "check if any of the components of the path are links", at which point one "obvious"[*] answer is "any(x.is_symlink() for x in [*mypath.parents, mypath])".  If the path is absolute, you could use "not (mypath.resolve() == mypath)".
>
>[*] I put that in quotes because it is only obvious once you have a non-trivial amount of experience with programming in Python.
>
>\----------
>
>_______________________________________
>Python tracker \< report@bugs.python.org \>
>\< http://bugs.python.org/issue31269 \>
>_______________________________________
