### ISSUE TITLE
Support building against homebrew on macOS

### ISSUE THREAD

**Issue by warsaw** [python/cpython#75457]
BPO | [31274](https://bugs.python.org/issue31274)
--- | :---
Nosy | @warsaw, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-08-25.03:21:16.901>
labels = ['build', '3.7', 'docs']
title = 'Support building against homebrew on macOS'
updated_at = <Date 2017-08-25.03:35:10.189>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-25.03:35:10.189>
actor = 'Mariatta'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Build', 'Documentation']
creation = <Date 2017-08-25.03:21:16.901>
creator = 'barry'
dependencies = []
files = []
hgrepos = []
issue_num = 31274
keywords = []
message_count = 2.0
messages = ['300819', '300820']
nosy_count = 3.0
nosy_names = ['barry', 'docs@python', 'Mariatta']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31274'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by warsaw** [comment]
The [devguide](https://devguide.python.org) does touch on how to build Python from source using homebrew installed libraries on macOS, although I found it to be 1) a bit incomplete; 2) not so easy to discover.

It might make sense to modify configure to autodetect homebrew, or to have a switch to enable linking against homebrew libraries.

Barring that, I'd like to at least update the [devguide](https://devguide.python.org) to include details on how to also build sqlite3 and zlib modules.

**Comment by Mariatta** [comment]
If you're proposing changes to the [devguide](https://devguide.python.org), then please file the issue at https://github.com/python/devguide :)

**Comment by erlend-aasland** [comment]
Superseded by python/devguide#894
