### ISSUE TITLE
import in finally results in SystemError

### ISSUE THREAD

**Issue by 81c94ca1-33c5-43a1-9206-327e323bc407** [python/cpython#75467]
BPO | [31286](https://bugs.python.org/issue31286)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericsnowcurrently, @serhiy-storchaka, @tacaswell
PRs | <li>python/cpython#3217</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-29.12:50:01.846>
created_at = <Date 2017-08-27.02:38:08.893>
labels = ['interpreter-core', '3.7', 'type-crash']
title = 'import in finally results in SystemError'
updated_at = <Date 2017-08-29.13:18:53.258>
user = 'https://github.com/tacaswell'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-29.13:18:53.258>
actor = 'tcaswell'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-29.12:50:01.846>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-08-27.02:38:08.893>
creator = 'tcaswell'
dependencies = []
files = []
hgrepos = []
issue_num = 31286
keywords = []
message_count = 7.0
messages = ['300911', '300913', '300914', '300915', '300984', '300985', '300988']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ncoghlan', 'eric.snow', 'serhiy.storchaka', 'tcaswell']
pr_nums = ['3217']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31286'
versions = ['Python 3.7']
```

</p></details>

**Comment by 81c94ca1-33c5-43a1-9206-327e323bc407** [comment]
Code to reproduce:

```py
def import_in_finally_fail():
    try:
        print('yo')
    finally:
        import asyncio.queues as aq
```



Results in:

In [68]: import_in_finally_fail()
yo
\---------------------------------------------------------------------------
```pytb
SystemError                               Traceback (most recent call last)
<ipython-input-68-4a6d2efcb22b> in <module>()
----> 1 import_in_finally_fail()
```


/tmp/py2661VBj in import_in_finally_fail()

SystemError: 'finally' pops bad exception


The exact import does matter, but it needs to be at least 2 modules deep and be aliased.  

By patching cpython to put what finally pops off the stack in the error message it looks like it is the parent module of the import.

This was found via the Matplotlib test suite (ex https://travis-ci.org/matplotlib/matplotlib/jobs/262907186 ) and reported to pytest (https://github.com/pytest-dev/pytest/issues/2674)

**Comment by serhiy-storchaka** [comment]
Confirmed. The bug is 3.7 only.

**Comment by serhiy-storchaka** [comment]
The regression was introduced in bpo-30024. It was missed a difference between LOAD_ATTR and IMPORT_FROM. LOAD_ATTR replaces the object with the value of the attribute (do not changing the stack pointer). IMPORT_FROM keeps the original module on the stack and pushes the value of the attribute increasing the stack pointer.

There are two ways of fixing this issue.

1. Add two instructions ROT_TWO and POP_TOP after every IMPORT_FROM in the bytecode generated from "import a.b.c as d".

2. Make IMPORT_FROM popping the original module from the stack. The explicit DUP_TOP instruction should be inserted before every IMPORT_FROM in the bytecode generated from "from a import b, c".

**Comment by serhiy-storchaka** [comment]
[PR 3217](https://github.com/python/cpython/pull/3217) implements the first way. It also includes some refactoring. Remove all pyc-files before testing.

**Comment by serhiy-storchaka** [comment]
New changeset 265fcc5fc25d65afb33fda480c603f1e974e374e by Serhiy Storchaka in branch 'master':
bpo-31286, bpo-30024: Fixed stack usage in absolute imports with (bpo-3217)
https://github.com/python/cpython/commit/265fcc5fc25d65afb33fda480c603f1e974e374e

**Comment by serhiy-storchaka** [comment]
Thank you for your report Thomas!

Don't forget to remove pyc-files before re-running the Matplotlib test suite.

**Comment by 81c94ca1-33c5-43a1-9206-327e323bc407** [comment]
Your welcome!

Matplotlib ended up just moving the import out of the finally block once we
understood the issue.

Tom
