### ISSUE TITLE
Squash new gcc warning (-Wstringop-overflow)

### ISSUE THREAD

**Issue by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [python/cpython#75460]
BPO | [31279](https://bugs.python.org/issue31279)
--- | :---
Nosy | @vstinner, @skrah
PRs | <li>python/cpython#3207</li><li>python/cpython#4620</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-25.18:56:52.476>
created_at = <Date 2017-08-25.17:38:57.459>
labels = ['build', '3.7']
title = 'Squash new gcc warning (-Wstringop-overflow)'
updated_at = <Date 2017-11-29.23:00:38.008>
user = 'https://github.com/skrah'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.23:00:38.008>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-25.18:56:52.476>
closer = 'skrah'
components = ['Build']
creation = <Date 2017-08-25.17:38:57.459>
creator = 'skrah'
dependencies = []
files = []
hgrepos = []
issue_num = 31279
keywords = []
message_count = 3.0
messages = ['300851', '300852', '307270']
nosy_count = 2.0
nosy_names = ['vstinner', 'skrah']
pr_nums = ['3207', '4620']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31279'
versions = ['Python 3.7']
```

</p></details>

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
gcc-7.2 emits the following not-so-useful warning:


[Objects/bytearrayobject.c:226](https://github.com/python/cpython/blob/main/Objects/bytearrayobject.c#L226):9: warning: ‘memcpy’: specified size between 9223372036854775808 and 18446744073709551615 exceeds maximum object size 9223372036854775807

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
New changeset dce6502059f46a04f90938b9d832394c8215397b by Stefan Krah in branch 'master':
bpo-31279: Silence -Wstringop-overflow warning. (bpo-3207)
https://github.com/python/cpython/commit/dce6502059f46a04f90938b9d832394c8215397b

**Comment by vstinner** [comment]
New changeset dedcbee04cd52790027ecfb46cb3aa33efebdc84 by Victor Stinner in branch '3.6':
[3.6] bpo-30923, bpo-31279: Fix GCC warnings (bpo-4620)
https://github.com/python/cpython/commit/dedcbee04cd52790027ecfb46cb3aa33efebdc84
