### ISSUE TITLE
Namespace packages in directories added to path aren't importable if packages from the same namespace are in site-packages

### ISSUE THREAD

**Issue by 0a775683-2046-429c-a1c9-267a53469b7d** [python/cpython#75461]
BPO | [31280](https://bugs.python.org/issue31280)
--- | :---
Nosy | @warsaw, @ericvsmith, @jimfulton
Files | <li>[z.py](https://bugs.python.org/file47101/z.py "Uploaded as text/plain at 2017-08-25.22:41:31 by @jimfulton")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-26.13:18:55.954>
created_at = <Date 2017-08-25.21:53:30.872>
labels = ['type-bug', 'invalid']
title = "Namespace packages in directories added to path aren't importable if packages from the same namespace are in site-packages"
updated_at = <Date 2017-08-26.18:04:55.162>
user = 'https://github.com/jimfulton'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-26.18:04:55.162>
actor = 'j1m'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-26.13:18:55.954>
closer = 'j1m'
components = []
creation = <Date 2017-08-25.21:53:30.872>
creator = 'j1m'
dependencies = []
files = ['47101']
hgrepos = []
issue_num = 31280
keywords = []
message_count = 7.0
messages = ['300856', '300857', '300858', '300859', '300876', '300877', '300889']
nosy_count = 3.0
nosy_names = ['barry', 'eric.smith', 'j1m']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31280'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 0a775683-2046-429c-a1c9-267a53469b7d** [comment]
I'm having an issue importing from namespaces packages whose directories are added to sys.path and have other packages from the same namespace in site-packages.

To reproduce:

- Create a virtualenv and install zc.buildout in it (``envdir/bin/pip install zc.buildout``).

- Run the attached script with the virtual environment (``envdir/bin/python z.py``).

Note that scenarios like https://www.python.org/dev/peps/pep-0420/#id3 work fine.  This seems to related to having namespace packages in site-packages, or, presumably anywhere on the default path.

I've verified this with Python 3.4, 3.5, and 3.6.

If y'all agree that this is a bug, then I'll attempt debug it and come up with a PR.

**Comment by ericvsmith** [comment]
Jim: did you forget to attach the z.py script?

**Comment by 0a775683-2046-429c-a1c9-267a53469b7d** [comment]
No, but I managed to unattach it, because "Choose File" always feels like a submit button to me.

Sorry.

Attached.

**Comment by ericvsmith** [comment]
I think this is a function of the .pth file causing 'zc' to be in sys.modules. If I delete the .pth file, the first import of zc.m succeeds.

Note that if the .pth file is in place, then:

```pycon
% bin/python3
Python 3.6.1 (default, Mar 24 2017, 12:50:34)
[GCC 5.4.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> 'zc' in sys.modules
True
>>>
```

**Comment by 0a775683-2046-429c-a1c9-267a53469b7d** [comment]
Wow, OK. It didn't occur to me to look for .pth files. (Buildout doesn't use them.)  I guess this is a pip bug or misfeature.  I'll head over to pypa.

Thanks!

**Comment by ericvsmith** [comment]
No problem. If you open a pypa issue, can you post a link here? Thanks.

**Comment by 0a775683-2046-429c-a1c9-267a53469b7d** [comment]
See: https://github.com/pypa/pip/issues/4695
