### ISSUE TITLE
segfault on missing library symbol

### ISSUE THREAD

**Issue by 76e86f4d-81e4-4dc5-b6cf-27a2dec1193f** [python/cpython#75471]
BPO | [31290](https://bugs.python.org/issue31290)
--- | :---
Nosy | @r-barnes, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-08-28.07:28:43.695>
labels = []
title = 'segfault on missing library symbol'
updated_at = <Date 2018-09-14.09:49:38.587>
user = 'https://github.com/r-barnes'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-14.09:49:38.587>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-08-28.07:28:43.695>
creator = 'immortalplants'
dependencies = []
files = []
hgrepos = []
issue_num = 31290
keywords = []
message_count = 1.0
messages = ['300942']
nosy_count = 2.0
nosy_names = ['immortalplants', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31290'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 76e86f4d-81e4-4dc5-b6cf-27a2dec1193f** [comment]
I'm building a Python library with a C++ component composed of a number of source .cpp files.

After some changes today, compiling and loading in Python3 resulted in a segfault:


```pycon
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170118] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mymodule
Segmentation fault (core dumped)
```



As you might imagine, this is not the funnest thing ever to debug.

Thankfully, when I compiled the module for Python2 and tried to load, a much more helpful and informative error message was displayed.


```pycon
Python 2.7.13 (default, Jan 19 2017, 14:48:08) 
[GCC 6.3.0 20170118] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mymodule
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mymodule/__init__.py", line 1, in <module>
    import _mymodule
ImportError: ./_mymodule.so: undefined symbol: DBFGetRecordCount
>>> 
```



And indeed, it seems that in my setup.py file where I had

setuptools.Extension(
  "\_mymodule",
  glob.glob('src/*.cpp') + glob.glob('lib/mylib/*.cpp') + glob.glob('lib/mylib/sublib/*.c'),

I should have had 'lib/mylib/sublib/*.cpp'.



I think the current behaviour can be improved:

1. Python3 should provide a helpful error message, like Python2 does.

2. setup.py should fail or at least provide a warning if there are missing symbols. (Perhaps this suggestion should be aimed at one of the setup utilities, but I'm not sure where to send it.)

**Comment by kumaraditya303** [comment]
This is not a Python issue as it is bug in your program that it is segfaulting, you can debug it in gdb so closing.
