### ISSUE TITLE
typo in __hash__ docs

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#75476]
BPO | [31295](https://bugs.python.org/issue31295)
--- | :---
Nosy | @bitdancer, @anntzer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-28.20:00:57.206>
created_at = <Date 2017-08-28.19:42:50.053>
labels = ['3.7', 'invalid', 'docs']
title = 'typo in __hash__ docs'
updated_at = <Date 2017-08-28.20:00:57.204>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-28.20:00:57.204>
actor = 'r.david.murray'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-08-28.20:00:57.206>
closer = 'r.david.murray'
components = ['Documentation']
creation = <Date 2017-08-28.19:42:50.053>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 31295
keywords = []
message_count = 2.0
messages = ['300961', '300964']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'docs@python', 'Antony.Lee']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31295'
versions = ['Python 3.7']
```

</p></details>

**Comment by 379dc349-3a10-424f-b9d2-a0104f092359** [comment]
In https://docs.python.org/3.7/reference/datamodel.html#object.\_\_hash__ I think

x.\_\_hash__() returns an appropriate value such that x == y implies both that x is y and hash(x) == hash(y).

should be

x.\_\_hash__() returns an appropriate value such that x == y and x is y both imply that hash(x) == hash(y).

right?

**Comment by bitdancer** [comment]
No, it is correct as worded.  It is talking about the default methods.  With the default methods, x == y implies that x is y.
