### ISSUE TITLE
crashes in multiply_float_timedelta() and in truedivide_timedelta_float()

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75474]
BPO | [31293](https://bugs.python.org/issue31293)
--- | :---
Nosy | @abalkin, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3227</li><li>python/cpython#3654</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-19.14:01:15.912>
created_at = <Date 2017-08-28.14:36:40.195>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'crashes in multiply_float_timedelta() and in truedivide_timedelta_float()'
updated_at = <Date 2017-09-19.14:01:15.910>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-19.14:01:15.910>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-19.14:01:15.912>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-08-28.14:36:40.195>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31293
keywords = ['patch']
message_count = 7.0
messages = ['300954', '300955', '300956', '300957', '300958', '302520', '302528']
nosy_count = 3.0
nosy_names = ['belopolsky', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3227', '3654']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31293'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
both of the following true division and multiplication operations crash the
interpreter:

```py
import datetime

class BadFloat(float):
    def as_integer_ratio(self):
        return (1 << 1000) - 1
```


datetime.timedelta() / BadFloat()
datetime.timedelta() * BadFloat()


this is because both multiply_float_timedelta() and truedivide_timedelta_float()
(in [Modules/_datetimemodule.c](https://github.com/python/cpython/blob/main/Modules/_datetimemodule.c)) assume as_integer_ratio() returns tuple.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
i am working on a patch.

BTW, is there anywhere a list of what counts as an extension
module, and what counts as the interpreter core?

**Comment by serhiy-storchaka** [comment]
I don't know if there is a list, but definitely the parser, the compiler, the evaluation loop, builtin types and few builtin modules (like builtins and sys) are interpreter core. The \_datetime module is an accelerator of the datetime module. It is optional and definitely is not in the core.

**Comment by serhiy-storchaka** [comment]
Please check if there is similar issue with Decimal.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
I guess you meant for me to check whether the following has any problem:
import decimal

```py
class BadFloat(float):
    def as_integer_ratio(self):
        return 1 << 1000

decimal.Decimal.from_float(BadFloat())
```


so it doesn't crash.
if IIUC, this is because the C implementation of Decimal.from_float()
is PyDecType_FromFloat(), while the relevant part of it is a call to
PyDecType_FromFloatExact().
But PyDecType_FromFloatExact() uses float.as_integer_ratio(), and thus
ISTM that the issue doesn't exist there.

(also, the following doesn't raise an exception, as expected:
import decimal

```py
class BadFloat(float):
    def as_integer_ratio(self):
        raise RuntimeError

decimal.Decimal.from_float(BadFloat())
)
```

**Comment by serhiy-storchaka** [comment]
New changeset 865e4b4f630e2ae91e61239258abb58b488f1d65 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31293: Fix crashes in truediv and mul of a timedelta by a float with a bad as_integer_ratio() method. (bpo-3227)
https://github.com/python/cpython/commit/865e4b4f630e2ae91e61239258abb58b488f1d65

**Comment by serhiy-storchaka** [comment]
New changeset f37dd11f0d4832c15d49c2ddc83d533ddaa36e74 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31293: Fix crashes in truediv and mul of a timedelta by a float with a bad as_integer_ratio() method. (GH-3227) (bpo-3654)
https://github.com/python/cpython/commit/f37dd11f0d4832c15d49c2ddc83d533ddaa36e74
