### ISSUE TITLE
zipimport.zipimporter.get_data() crashes when path.replace() returns a non-str

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75472]
BPO | [31291](https://bugs.python.org/issue31291)
--- | :---
Nosy | @Yhg1s, @brettcannon, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3226</li><li>python/cpython#3243</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-30.11:09:04.820>
created_at = <Date 2017-08-28.08:44:26.426>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'zipimport.zipimporter.get_data() crashes when path.replace() returns a non-str'
updated_at = <Date 2017-08-30.11:09:04.819>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-30.11:09:04.819>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-30.11:09:04.820>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-08-28.08:44:26.426>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31291
keywords = []
message_count = 9.0
messages = ['300944', '300962', '300963', '300965', '300966', '300967', '300972', '300995', '301021']
nosy_count = 4.0
nosy_names = ['twouters', 'brett.cannon', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3226', '3243']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31291'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
on Windows, assuming the file 'foo.zip' exists, the following would cause an
assertion failure in [Modules/zipimport.c](https://github.com/python/cpython/blob/main/Modules/zipimport.c) in zipimport_zipimporter_get_data_impl():

```py
import zipimport

class BadStr(str):
    def replace(self, old, new):
        return 42
```


zipimport.zipimporter('foo.zip').get_data(BadStr('bar'))


this is because zipimport_zipimporter_get_data_impl() assumes that
BadStr('bar').replace('/', '\\\\') is a string.

**Comment by brettcannon** [comment]
I don't think this is a bad thing. This is duck-typing at work to be flexible where the type doesn't really matter, just the provided interface. If someone happens to provide an object that doesn't do the right thing then that's their fault for using the wrong object and the resulting exception that will occur from a bad path is acceptable.

I appreciate the work to do a PR, Oren, but I'm closing this issue as "rejected". (And if it makes you feel any better, you helped find a bug in the Bedevere bot. :) .

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
I understand that our goal is to make Python better, not to make me happier :)

anyway, I haven't checked, but I am quite sure that similar code might
crash the interpreter on a release build of Python.
(just wanted to clarify that, as you used the term 'exception'.)

**Comment by brettcannon** [comment]
If it will crash the interpreter then that's different. If that turns out to be the case then please come back here and we can rework the issue and PR to prevent that by being better about checking return values or resulting exception cases.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
just checked, and indeed on my Windows 10 the original code I posted here
crashes the interpreter.

The patch in the PR undermines duck-typing, and that's why I added a comment
there, stating I wasn't sure about the patch.
an alternate solution would be to simply check whether the return value of
pathname.replace('/', '\\') is a str.

do you think I would update the PR to do that?

**Comment by brettcannon** [comment]
Could you paste in what the crash looks like? E.g. is it a segfault, SystemError, etc.?

And you can tweak the PR or just open a new one if you would rather that fixes the crash itself without taking away duck typing.

**Comment by serhiy-storchaka** [comment]
Oren already fixed several similar problems and he is aware of difference between a crash and an exception.

The problem is Windows specific. The current code uses Unicode C API with the result of calling the replace method. This can cause a segfault (or may be an assertion failure in debug build).

The proposed solution LGTM. It undermines duck-typing, but I think this doesn't break any existing code. The duck-typing was not intentional and is Windows-only.

**Comment by serhiy-storchaka** [comment]
New changeset 631fdee6e61b4ba8ce800f827fecdd536bfb04f3 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31291: Fixed an assertion failure in zipimport.zipimporter.get_data() (bpo-3226)
https://github.com/python/cpython/commit/631fdee6e61b4ba8ce800f827fecdd536bfb04f3

**Comment by serhiy-storchaka** [comment]
New changeset 095a421b1606ee27e00a5d9d253b05a9f0cfadb8 by Serhiy Storchaka (Oren Milman) in branch '3.6':
[3.6] bpo-31291: Fixed an assertion failure in zipimport.zipimporter.get_data() (GH-3226) (bpo-3243)
https://github.com/python/cpython/commit/095a421b1606ee27e00a5d9d253b05a9f0cfadb8
