### ISSUE TITLE
Update doc for starmap_async error_back kwarg

### ISSUE THREAD

**Issue by 75f7e854-3273-45e3-8668-38159bcff5b0** [python/cpython#75485]
BPO | [31304](https://bugs.python.org/issue31304)
--- | :---
Nosy | @Mariatta
PRs | <li>python/cpython#4168</li><li>python/cpython#4177</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-30.18:48:42.792>
created_at = <Date 2017-08-29.20:13:31.257>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = 'Update doc for starmap_async error_back kwarg'
updated_at = <Date 2017-10-30.18:48:42.790>
user = 'https://bugs.python.org/tamas'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-30.18:48:42.790>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-30.18:48:42.792>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-08-29.20:13:31.257>
creator = 'tamas'
dependencies = []
files = []
hgrepos = []
issue_num = 31304
keywords = ['patch', 'easy']
message_count = 4.0
messages = ['300999', '305244', '305245', '305246']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'tamas']
pr_nums = ['4168', '4177']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31304'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 75f7e854-3273-45e3-8668-38159bcff5b0** [comment]
The documentation suggests that multiprocessing.pool.Pool. starmap_async has a kwarg called 'error_back', but it actually has a kwarg called 'error_callback' to handle errors, just like map_async.

Link:
https://docs.python.org/3.7/library/multiprocessing.html#multiprocessing.pool.Pool.starmap_async

**Comment by Mariatta** [comment]
New changeset 11225753a89c2907bb717e6c050fe907e5e11829 by Mariatta (Pablo Galindo) in branch 'master':
bpo-31304: Update starmap_async documentation. (GH-4168)
https://github.com/python/cpython/commit/11225753a89c2907bb717e6c050fe907e5e11829

**Comment by Mariatta** [comment]
New changeset 2702380870b63ebe0161dfa29a2d0a3de02401b4 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31304: Update starmap_async documentation. (GH-4168) (GH-4177)
https://github.com/python/cpython/commit/2702380870b63ebe0161dfa29a2d0a3de02401b4

**Comment by Mariatta** [comment]
This has been fixed. Thanks!
