### ISSUE TITLE
ConfigParser.read silently fails if filenames argument is a byte string

### ISSUE THREAD

**Issue by cc078fa6-9844-4016-bade-976a9d810ae6** [python/cpython#75488]
BPO | [31307](https://bugs.python.org/issue31307)
--- | :---
Nosy | @ambv, @berkerpeksag, @vxgmichel, @DavidCEllis, @Cryvate
PRs | <li>python/cpython#3420</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-02.12:49:05.393>
created_at = <Date 2017-08-30.14:15:47.010>
labels = ['3.7', 'type-feature', 'library']
title = 'ConfigParser.read silently fails if filenames argument is a byte string'
updated_at = <Date 2017-11-02.12:49:05.391>
user = 'https://github.com/vxgmichel'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-02.12:49:05.391>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-02.12:49:05.393>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-08-30.14:15:47.010>
creator = 'vxgmichel'
dependencies = []
files = []
hgrepos = []
issue_num = 31307
keywords = []
message_count = 5.0
messages = ['301026', '301149', '301192', '305421', '305422']
nosy_count = 5.0
nosy_names = ['lukasz.langa', 'berker.peksag', 'vxgmichel', 'David Ellis', 'cryvate']
pr_nums = ['3420']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31307'
versions = ['Python 3.7']
```

</p></details>

**Comment by cc078fa6-9844-4016-bade-976a9d810ae6** [comment]
Calling `config_parser.read` with `'test'` is equivalent to:

```py
    config_parser.read(['test'])

while calling `config_parser.read` with `b'test'` is treated as:

    config_parser.read([116, 101, 115, 116])
```


which means python will try to open the file descriptors 101, 115 and 116.

I don't know if byte path should be supported, but this is probably not the expected behavior.

The method code: https://github.com/python/cpython/blob/master/Lib/configparser.py#L678-L702

**Comment by ambv** [comment]
Good catch. Supporting bytes passed as a path is a reasonable request since the builtin `open()` supports this, too. Go ahead and create a pull request! We only need to modify line 690 to also list `bytes`.

**Comment by 3873e664-9d3f-406b-bb16-a4d912ca397a** [comment]
This is related to the issue I'd brought up previously here so closing this would also close that issue: http://bugs.python.org/issue29627

I did originally attempt to add support for bytes in PR where I added support for Path-like objects: 
https://github.com/python/cpython/pull/242 but I was asked to take it back out.

**Comment by berkerpeksag** [comment]
New changeset e314853d57450b2b9523157eebd405289a795a0e by Berker Peksag (Vincent Michel) in branch 'master':
bpo-31307: Make ConfigParser.read() accept bytes objects (GH-3420)
https://github.com/python/cpython/commit/e314853d57450b2b9523157eebd405289a795a0e

**Comment by berkerpeksag** [comment]
Thanks! I went ahead and merged [PR 3420](https://github.com/python/cpython/pull/3420) since Łukasz (the configparser maintainer) has accepted the idea.
