### ISSUE TITLE
Traceback prints different code than the running module

### ISSUE THREAD

**Issue by d330a3fb-6893-4285-8ce2-52329a23bafc** [python/cpython#75481]
BPO | [31300](https://bugs.python.org/issue31300)
--- | :---
Nosy | @bitdancer
Superseder | <li>bpo-8087: Unupdated source file in traceback</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-29.13:42:20.684>
created_at = <Date 2017-08-29.11:03:31.539>
labels = ['type-bug', 'library']
title = 'Traceback prints different code than the running module'
updated_at = <Date 2017-08-29.13:42:20.682>
user = 'https://bugs.python.org/AigarsMahinovs'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-29.13:42:20.682>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-29.13:42:20.684>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-08-29.11:03:31.539>
creator = 'Aigars Mahinovs'
dependencies = []
files = []
hgrepos = []
issue_num = 31300
keywords = []
message_count = 2.0
messages = ['300980', '300989']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Aigars Mahinovs']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '8087'
type = 'behavior'
url = 'https://bugs.python.org/issue31300'
versions = ['Python 3.6']
```

</p></details>

**Comment by d330a3fb-6893-4285-8ce2-52329a23bafc** [comment]
If you run a longer running Python program, then change the Python module that it loaded on disk and then cause a traceback to happen in the code in that module, then the traceback may be nonsensical as it will reference line numbers from the module in memory, but print code from the same line numbers from the file on disk, even if they are different.

In any case there should be a prominent warning on traceback if the module in memory does not match the module on disk, but ideally the traceback print should show the code in memory - the actual code that caused the problem.

**Comment by bitdancer** [comment]
This is a duplicate of bpo-8087, which contains quite a bit of discussion of the subtleties of the issue.
