### ISSUE TITLE
xml.etree.ElementTree fails to parse a document (regression)

### ISSUE THREAD

**Issue by 16eed237-58f0-4125-b811-e8d4c1c6b320** [python/cpython#75484]
BPO | [31303](https://bugs.python.org/issue31303)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
Superseder | <li>bpo-31170: Update to expat 2.2.4 (expat: utf8_toUtf8 cannot properly handle exhausting buffer)</li>
Files | <li>[bad_file.xml](https://bugs.python.org/file47108/bad_file.xml "Uploaded as text/xml at 2017-08-29.17:45:53 by Vyacheslav.Rafalskiy")</li><li>[bad_file.xml](https://bugs.python.org/file47109/bad_file.xml "Uploaded as text/xml at 2017-08-29.17:50:24 by Vyacheslav.Rafalskiy")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-08-30.05:15:12.619>
created_at = <Date 2017-08-29.17:45:53.331>
labels = ['expert-XML', 'type-bug', '3.7']
title = 'xml.etree.ElementTree fails to parse a document (regression)'
updated_at = <Date 2017-08-30.05:15:12.566>
user = 'https://bugs.python.org/VyacheslavRafalskiy'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-30.05:15:12.566>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-08-30.05:15:12.619>
closer = 'serhiy.storchaka'
components = ['XML']
creation = <Date 2017-08-29.17:45:53.331>
creator = 'Vyacheslav.Rafalskiy'
dependencies = []
files = ['47108', '47109']
hgrepos = []
issue_num = 31303
keywords = []
message_count = 3.0
messages = ['300996', '300997', '301010']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'Vyacheslav.Rafalskiy']
pr_nums = []
priority = 'critical'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31170'
type = 'behavior'
url = 'https://bugs.python.org/issue31303'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 16eed237-58f0-4125-b811-e8d4c1c6b320** [comment]
In Python 3.5.4 and 3.6.2, both on Windows and Linux, parsing a manifestly correct xml file like:

```py
xml.etree.ElementTree.parse('bad_file.xml')
```


raises:
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1023: invalid continuation byte

Any other Python version I tried works fine, including 2.7.13, 3.5.2 ...

**Comment by serhiy-storchaka** [comment]
Simpler reproducer:

```pycon
>>> import xml.etree.ElementTree
>>> xml.etree.ElementTree.XML(b'<key attr="' + b'x'*1023 + b'\xc3\xa0&quot;"/>')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/xml/etree/ElementTree.py", line 1315, in XML
    parser.feed(text)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 1023: invalid continuation byte
```


Seems this is a regression in the Expat library.

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-31170. Updating expat to 2.2.4 fixes this issue.
