### ISSUE TITLE
assertion failure in imp.create_dynamic(), when spec.name is not a string

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75496]
BPO | [31315](https://bugs.python.org/issue31315)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericsnowcurrently, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3257</li><li>python/cpython#3653</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-19.12:54:26.111>
created_at = <Date 2017-08-31.16:25:55.661>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in imp.create_dynamic(), when spec.name is not a string'
updated_at = <Date 2017-09-19.12:54:46.470>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-19.12:54:46.470>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-19.12:54:26.111>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-08-31.16:25:55.661>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31315
keywords = ['patch']
message_count = 8.0
messages = ['301050', '301056', '301057', '301061', '301109', '302516', '302518', '302519']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'ncoghlan', 'eric.snow', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3257', '3653']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31315'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure in get_encoded_name(), which is
called by \_PyImport_LoadDynamicModuleWithSpec() (in [Python/importdl.c](https://github.com/python/cpython/blob/main/Python/importdl.c)):

```py
import imp

class BadSpec:
    name = 42
    origin = 'foo'

imp.create_dynamic(BadSpec())
```



this is because \_PyImport_LoadDynamicModuleWithSpec() assumes that spec.name is
a string.


should we fix this (even though imp is deprecated)?

**Comment by brettcannon** [comment]
I'm about to go on vacation so I might not be right of mind to comment, but I think throwing a TypeError is valid if it's triggering an assertion error that is already there.

P.S. Thanks for all the fuzz testing you're doing, Oren!

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
do you mean that we should fix it to raise a TypeError?

the assertion is there, but not explicitly. 
get_encoded_name() calls PyUnicode_FindChar(), which calls
PyUnicode_READY(), which does assert(_PyUnicode_CHECK).

```pycon
so i get:
>>> import imp
>>>
>>> class BadSpec:
...     name = 42
...     origin = 'foo'
...
>>> imp.create_dynamic(BadSpec())
Assertion failed: PyUnicode_Check(op), file ..\Objects\unicodeobject.c, line 380
```

**Comment by brettcannon** [comment]
Yes, I'm saying that instead of hitting the C-level assertion error an explicit TypeError should be raised (or some other change like calling str() on the object). Either way, a C-level assertion from valid Python code is bad. :)

**Comment by ericsnowcurrently** [comment]
On Thu, Aug 31, 2017 at 1:32 PM, Brett Cannon \<report@bugs.python.org\> wrote:
> I think throwing a TypeError is valid if it's triggering an assertion error that is already there.

+1

> P.S. Thanks for all the fuzz testing you're doing, Oren!

Also a big +1. :)

**Comment by serhiy-storchaka** [comment]
New changeset 9974e1bcf3d0cec9b38b39b39b7ec8a1ebd9ef54 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31315: Fix an assertion failure in imp.create_dynamic(), when spec.name is not a string. (bpo-3257)
https://github.com/python/cpython/commit/9974e1bcf3d0cec9b38b39b39b7ec8a1ebd9ef54

**Comment by serhiy-storchaka** [comment]
New changeset 99a51d4e5b154a7b8d971090fecc1e34769a3ca1 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31315: Fix an assertion failure in imp.create_dynamic(), when spec.name is not a string. (GH-3257) (bpo-3653)
https://github.com/python/cpython/commit/99a51d4e5b154a7b8d971090fecc1e34769a3ca1

**Comment by serhiy-storchaka** [comment]
Thank you Oren!
