### ISSUE TITLE
email throws exception with oversized header input

### ISSUE THREAD

**Issue by doko42** [python/cpython#75495]
BPO | [31314](https://bugs.python.org/issue31314)
--- | :---
Nosy | @warsaw, @doko42, @bitdancer, @serhiy-storchaka, @corona10, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-27.17:11:03.881>
created_at = <Date 2017-08-31.10:29:52.379>
labels = ['expert-email']
title = 'email throws exception with oversized header input'
updated_at = <Date 2021-06-27.17:11:03.880>
user = 'https://github.com/doko42'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-27.17:11:03.880>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-27.17:11:03.881>
closer = 'iritkatriel'
components = ['email']
creation = <Date 2017-08-31.10:29:52.379>
creator = 'doko'
dependencies = []
files = []
hgrepos = []
issue_num = 31314
keywords = ['patch']
message_count = 6.0
messages = ['301044', '304005', '304054', '304105', '304107', '396173']
nosy_count = 6.0
nosy_names = ['barry', 'doko', 'r.david.murray', 'serhiy.storchaka', 'corona10', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31314'
versions = ['Python 2.7']
```

</p></details>

**Comment by doko42** [comment]
[forwarded from https://bugs.debian.org/854001]

```sh
$ cat tst.py
#!/usr/bin/env python
import sys
import email
```


```py
mail = email.message_from_string(
"""From: <postmaster@example.com>
To: <bounce@example.com>
Subject: demo
X-Overlong-Header-Name-causes-python-mail-to-crash-in-re-serialization-example:
```


Hello
""")
message = mail.as_string()
sys.stdout.write(message)

```pytb
$ python tst.py 
Traceback (most recent call last):
  File "tst.py", line 13, in <module>
    message = mail.as_string()
  File "/usr/lib/python2.7/email/message.py", line 137, in as_string
    g.flatten(self, unixfrom=unixfrom)
  File "/usr/lib/python2.7/email/generator.py", line 83, in flatten
    self._write(msg)
  File "/usr/lib/python2.7/email/generator.py", line 115, in _write
    self._write_headers(msg)
  File "/usr/lib/python2.7/email/generator.py", line 164, in _write_headers
    v, maxlinelen=self._maxheaderlen, header_name=h).encode()
  File "/usr/lib/python2.7/email/header.py", line 408, in encode
    lastchunk, lastcharset = newchunks[-1]
IndexError: list index out of range
```

**Comment by corona10** [comment]
I sent a patch if anyone have a time, please take a look :)

**Comment by serhiy-storchaka** [comment]
[PR 3938](https://github.com/python/cpython/pull/3938) fixes this issue, but I'm wondering why self.\_split() returns an empty list only for long header names.

**Comment by corona10** [comment]
I found that when email header's self.\_firstlinelen value is negative
then self.\_split() returns an empty list.
Because when the self.\_firstlinelen value is negative value then
'targetlen' becomes a negative value.

I will update a patch into calculating self.firstlinelen as same as Python3.

2017-10-11 0:46 GMT+09:00 Serhiy Storchaka \<report@bugs.python.org\>:
>
> Serhiy Storchaka \<storchaka+cpython@gmail.com\> added the comment:
>
> [PR 3938](https://github.com/python/cpython/pull/3938) fixes this issue, but I'm wondering why self.\_split() returns an empty list only for long header names.
>
> \----------
> nosy: +serhiy.storchaka
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue31314\>
> _______________________________________

-- 
Chungnam National University | Computer Science & Engineering

Tel: +82 010-3353-9127
Email: donghee.na92@gmail.com
Linkedin: https://www.linkedin.com/in/dong-hee-na-2b713b49/

**Comment by corona10** [comment]
And my patch was wrong, I will re-upload it soon.

2017-10-11 13:51 GMT+09:00 Dong-hee Na \<report@bugs.python.org\>:
>
> Dong-hee Na \<donghee.na92@gmail.com\> added the comment:
>
> I found that when email header's self.\_firstlinelen value is negative
> then self.\_split() returns an empty list.
> Because when the self.\_firstlinelen value is negative value then
> 'targetlen' becomes a negative value.
>
> I will update a patch into calculating self.firstlinelen as same as Python3.
>
> 2017-10-11 0:46 GMT+09:00 Serhiy Storchaka \<report@bugs.python.org\>:
>\>
>\> Serhiy Storchaka \<storchaka+cpython@gmail.com\> added the comment:
>\>
>\> [PR 3938](https://github.com/python/cpython/pull/3938) fixes this issue, but I'm wondering why self.\_split() returns an empty list only for long header names.
>\>
>\> \----------
>\> nosy: +serhiy.storchaka
>\>
>\> _______________________________________
>\> Python tracker \<report@bugs.python.org\>
>\> \<https://bugs.python.org/issue31314\>
>\> _______________________________________
>
> --
> Chungnam National University | Computer Science & Engineering
>
> Tel: +82 010-3353-9127
> Email: donghee.na92@gmail.com
> Linkedin: https://www.linkedin.com/in/dong-hee-na-2b713b49/
>
> \----------
>
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue31314\>
> _______________________________________

-- 
Chungnam National University | Computer Science & Engineering

Tel: +82 010-3353-9127
Email: donghee.na92@gmail.com
Linkedin: https://www.linkedin.com/in/dong-hee-na-2b713b49/
