### ISSUE TITLE
Tkinter root window does not close if used with matplotlib.pyplot

### ISSUE THREAD

**Issue by 049bfe99-57ec-4753-8344-c0d29dd2f3cf** [python/cpython#75490]
BPO | [31309](https://bugs.python.org/issue31309)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-30.16:52:57.731>
created_at = <Date 2017-08-30.15:34:35.229>
labels = ['3.7', 'invalid', 'type-bug', 'expert-tkinter']
title = 'Tkinter root window does not close if used with matplotlib.pyplot'
updated_at = <Date 2017-08-30.16:52:57.708>
user = 'https://bugs.python.org/psiehr'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-30.16:52:57.708>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-30.16:52:57.731>
closer = 'terry.reedy'
components = ['Tkinter']
creation = <Date 2017-08-30.15:34:35.229>
creator = 'psiehr'
dependencies = []
files = []
hgrepos = []
issue_num = 31309
keywords = []
message_count = 2.0
messages = ['301028', '301032']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'psiehr']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31309'
versions = ['Python 3.7']
```

</p></details>

**Comment by 049bfe99-57ec-4753-8344-c0d29dd2f3cf** [comment]
Today I ran into a problem when using both tkinter and matplotlib.pyplot at the same time. I thought it would be best to let you know, in case it is an issue. 

The problem is/was that the root window did not close itself, when just using `askopenfilename()`. 

A complete description of the problem, including a minimal working example, screenshots and a "solution" can be found on StackOverflow: 
https://stackoverflow.com/q/45960815/7414040 

I think that the function `askopenfilename()` does not ensure that the tkinter root window, that has been opened, is destroyed after the function call ended.

**Comment by terryjreedy** [comment]
This is purely a tkinter issue.  Windows people can ignore this.

Your problem was a result of your program error, of not keeping a reference to Tk(), combined with tkinter's \_default_root 'feature'.

The solution you report in your answer, 'root = tkinter.Tk()', later followed by an explicit 'root.destroy()' is \*the* correct way to do what you want.  I explained further in my answer.

There is no way for askopenfilename to know that you are done with root or tkinter.\_default_root.
