### ISSUE TITLE
On Windows importlib.util.find_spec("re") results in AttributeError: module 'importlib' has no attribute 'util'

### ISSUE THREAD

**Issue by 18d3d571-8e35-49b9-a61c-8d5bf130f0d9** [python/cpython#75499]
BPO | [31318](https://bugs.python.org/issue31318)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @elmbeech

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-01.06:10:20.954>
created_at = <Date 2017-09-01.04:01:34.889>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'On Windows importlib.util.find_spec("re") results in AttributeError: module \'importlib\' has no attribute \'util\''
updated_at = <Date 2017-09-01.15:44:39.549>
user = 'https://github.com/elmbeech'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-01.15:44:39.549>
actor = 'bue'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-01.06:10:20.954>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-09-01.04:01:34.889>
creator = 'bue'
dependencies = []
files = []
hgrepos = []
issue_num = 31318
keywords = []
message_count = 3.0
messages = ['301083', '301085', '301130']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'bue']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31318'
versions = ['Python 3.6']
```

</p></details>

**Comment by 18d3d571-8e35-49b9-a61c-8d5bf130f0d9** [comment]
Hi There, 

I found the following bug, but have now idea where to search to fix this:

On Windows calling a python script from the command line with the line importlib.util.find_spec("re") in it or using the standard python shell 
and executing importlib.util.find_spec("re") causes an AttributeError: module 'importlib' has no attribute 'util'.
Surprisingly using ipython and calling the same script with %run or executing importlib.util.find_spec("re") in the ipython shell works fine.

```pycon
C:\Users\buchere>python
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
 on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import importlib
>>> importlib.util.find_spec("re")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'importlib' has no attribute 'util'
>>> exit()
 
ipython:
C:\Users\buchere>ipython
Python 3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:14:34) [MSC v.1900 32 bit (Intel)]
```


Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import importlib

In [2]: importlib.util.find_spec("re")
Out[2]: ModuleSpec(name='re', loader=\<_frozen_importlib_external.SourceFileLoade
r object at 0x01EB6750\>, origin='c:\\\\users\\\\buchere\\\\appdata\\\\local\\\\programs\\\\p
ython\\\\python36-32\\\\lib\\\\re.py')

In [3]:

The same code works fine in the Darwin and Linux standard python shell. 
This error is really specific to the Windows standard python shell.

**Comment by zooba** [comment]
util is a submodule of importlib, and so it should always be imported before using it.

Other platforms may import it for various other reasons, but that is not part of the API. You should fix it by typing (note that the first line is different from yours):

>\>\> import importlib.util
>\>\> importlib.util.find_spec("re")

**Comment by 18d3d571-8e35-49b9-a61c-8d5bf130f0d9** [comment]
thank you Steve for the explanation!

I was not aware that I should import sub modules explicitly like this.
especial because it worked on my development machine without doing so.
now I know.

Elmar
