### ISSUE TITLE
a SystemError and a crash in PyCData_setstate() when __dict__ is bad

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75492]
BPO | [31311](https://bugs.python.org/issue31311)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3254</li><li>python/cpython#3255</li><li>python/cpython#3743</li><li>python/cpython#3781</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.06:40:21.439>
created_at = <Date 2017-08-30.19:29:41.381>
labels = ['ctypes', '3.7', 'type-crash']
title = 'a SystemError and a crash in PyCData_setstate() when __dict__ is bad'
updated_at = <Date 2017-09-27.06:40:21.407>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.06:40:21.407>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.06:40:21.439>
closer = 'serhiy.storchaka'
components = ['ctypes']
creation = <Date 2017-08-30.19:29:41.381>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31311
keywords = ['patch']
message_count = 10.0
messages = ['301034', '301035', '301036', '301807', '302840', '302841', '302914', '302919', '302928', '303099']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3254', '3255', '3743', '3781']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31311'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes PyCData_setstate() (in [Modules/_ctypes/_ctypes.c](https://github.com/python/cpython/blob/main/Modules/_ctypes/_ctypes.c)) to
raise a SystemError:

```py
import ctypes
class BadStruct(ctypes.Structure):
    def __dict__(self):
        pass
```


BadStruct().\_\_setstate__({}, b'foo')

this is because PyCData_setstate() assumes that the \_\_dict__ attribute is a dict.


while we are here, I wonder whether we should change the format given to 
PyArg_ParseTuple() to "!Os#", so that the following would raise a TypeError:

```py
import ctypes
class MyStruct(ctypes.Structure):
    pass
```


MyStruct().\_\_setstate__(42, b'foo')

AttributeError: 'int' object has no attribute 'keys'


what do you think?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
typo - change the format to "O!s#"

**Comment by serhiy-storchaka** [comment]
And the following example results in segmentation fault.

```py
import ctypes
class BadStruct(ctypes.Structure):
    @property
    def __dict__(self):
        raise AttributeError
```


BadStruct().\_\_setstate__({}, b'')

As for change the format given to PyArg_ParseTuple(), I think it can be done only in master. It is better to make a separate PR for this.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
just in case it was missed - I have opened two PRs for this issue.

**Comment by serhiy-storchaka** [comment]
New changeset 4facdf523aa6967487a9425f124da9661b59fd43 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31311: Impove error reporting in case the first argument to PyCData_setstate() isn't a dictionary. (bpo-3255)
https://github.com/python/cpython/commit/4facdf523aa6967487a9425f124da9661b59fd43

**Comment by serhiy-storchaka** [comment]
I thought about this issue so long because I can't find good cause for \_\_dict__ to be not a dict. Defining the \_\_dict__ method or property doesn't affect instance dictionary and attributes lookup. It just breaks the \_\_setstate__ method. Without having good example of overriding \_\_dict__ I have no good test cases and don't know what a way of handling this error is better.

There is yet one disadvantage of the current implementation. The instance's dict can be lazy. It can be created only on demand, when instance's attribute is set or the \_\_dict__ attribute is read. PyObject_GetAttrString(myself, "\_\_dict__") creates it if it was not created. It would be more efficient to use \_PyObject_GetDictPtr(). But this is a separate issue, 3.7 only.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
> But this is a separate issue, 3.7 only.
I don't think i understand what this issue would include.

Anyway, i updated the PR according to your comments.

**Comment by serhiy-storchaka** [comment]
New changeset 57c2561c8c5663aef55b00e3f29cba575ff36ccd by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31311: Fix a SystemError and a crash in ctypes.\_CData.\_\_setstate__(), in case of a bad \_\_dict__. (bpo-3254)
https://github.com/python/cpython/commit/57c2561c8c5663aef55b00e3f29cba575ff36ccd

**Comment by serhiy-storchaka** [comment]
New changeset a6bddb8e4397df30926eb1ade6420a2277174227 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31311: Fix a SystemError and a crash in ctypes.\_CData.\_\_setstate__(), in case of a bad \_\_dict__. (GH-3254) (bpo-3743)
https://github.com/python/cpython/commit/a6bddb8e4397df30926eb1ade6420a2277174227

**Comment by serhiy-storchaka** [comment]
New changeset 81691b05484a68df9cebb1310dd7dcabb3c6eb0a by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31311: Fix a SystemError and a crash in ctypes.\_CData.\_\_setstate__(), in case of a bad \_\_dict__. (GH-3254). (bpo-3781)
https://github.com/python/cpython/commit/81691b05484a68df9cebb1310dd7dcabb3c6eb0a
