### ISSUE TITLE
Build differences caused by the time stamps

### ISSUE THREAD

**Issue by 294c30b8-46e2-4754-b5e1-3769c01a3906** [python/cpython#75493]
BPO | [31312](https://bugs.python.org/issue31312)
--- | :---
Nosy | @bitdancer, @waylandzhong
Superseder | <li>bpo-29708: support reproducible Python builds</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-08-31.12:40:30.855>
created_at = <Date 2017-08-31.08:15:49.458>
labels = ['type-bug', 'library']
title = 'Build differences caused by the time stamps'
updated_at = <Date 2017-08-31.12:40:30.853>
user = 'https://github.com/waylandzhong'
```

bugs.python.org fields:
```python
activity = <Date 2017-08-31.12:40:30.853>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-08-31.12:40:30.855>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-08-31.08:15:49.458>
creator = 'WaylandZ'
dependencies = []
files = []
hgrepos = []
issue_num = 31312
keywords = []
message_count = 2.0
messages = ['301042', '301047']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'WaylandZ']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29708'
type = 'behavior'
url = 'https://bugs.python.org/issue31312'
versions = ['Python 2.7']
```

</p></details>

**Comment by 294c30b8-46e2-4754-b5e1-3769c01a3906** [comment]
When I build python (version 2.7.13), I find the build results are different every time. It seems to be caused by some times tamps, and they may be generated by the code below:
    [Lib/py_compile.py:106](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L106): with open(file, 'U') as f:
    [Lib/py_compile.py:107](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L107):     try:
    [Lib/py_compile.py:108](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L108):        timestamp = long(os.fstat(f.fileno()).st_mtime)
    [Lib/py_compile.py:109](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L109):    except AttributeError:
    [Lib/py_compile.py:110](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L110):        timestamp = long(os.stat(file).st_mtime)
    [Lib/py_compile.py:111](https://github.com/python/cpython/blob/main/Lib/py_compile.py#L111):   codestring = f.read()

As we know, reproducible build is a good way to counter malicious attacks that generate malicious executables, by making it easy to recreate the executable to determine if the result is correct. How can I eliminate the differences caused by the time stamps? Just remove some code? Or is there any configuration?
If we can't eliminate the difference now, can lsof support it in future versions?
Thank you.

**Comment by bitdancer** [comment]
Duplicate of bpo-29708.
