### ISSUE TITLE
test_ssl logs a traceback

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75501]
BPO | [31320](https://bugs.python.org/issue31320)
--- | :---
Nosy | @pitrou, @vstinner, @tiran, @alex, @vadmium, @dstufft, @Mariatta
PRs | <li>python/cpython#3360</li><li>python/cpython#3369</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-13.00:54:27.421>
created_at = <Date 2017-09-01.14:39:37.775>
labels = ['3.7', 'tests']
title = 'test_ssl logs a traceback'
updated_at = <Date 2017-09-13.00:54:27.420>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-13.00:54:27.420>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-13.00:54:27.421>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-09-01.14:39:37.775>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31320
keywords = []
message_count = 9.0
messages = ['301107', '301108', '301110', '301119', '301209', '301375', '301403', '301425', '302020']
nosy_count = 8.0
nosy_names = ['janssen', 'pitrou', 'vstinner', 'christian.heimes', 'alex', 'martin.panter', 'dstufft', 'Mariatta']
pr_nums = ['3360', '3369']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31320'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
It would be nice to not log such traceback:

```pytb
haypo@selma$ ./python -m test test_ssl -m test.test_ssl.ThreadedTests.test_echo
Run tests sequentially
0:00:00 load avg: 0.69 [1/1] test_ssl
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/home/haypo/prog/python/master/Lib/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/haypo/prog/python/master/Lib/test/test_ssl.py", line 1936, in run
    if not self.wrap_conn():
  File "/home/haypo/prog/python/master/Lib/test/test_ssl.py", line 1881, in wrap_conn
    self.sock, server_side=True)
  File "/home/haypo/prog/python/master/Lib/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/home/haypo/prog/python/master/Lib/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/home/haypo/prog/python/master/Lib/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/home/haypo/prog/python/master/Lib/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error
```


1 test OK.

Total duration: 205 ms
Tests result: SUCCESS

**Comment by vstinner** [comment]
Python 2.7 doesn't seem to be affected.

**Comment by pitrou** [comment]
I don't get such traceback here (Ubuntu 16.04, OpenSSL 1.0.2g).

**Comment by vstinner** [comment]
I'm running Fedora 26:

haypo@selma$ ./python -m test.pythoninfo|grep -E 'ssl|platform'
platform.architecture: 32bit ELF
platform.platform: Linux-4.12.5-300.fc26.x86_64-x86_64-with-fedora-26-Twenty_Six
platform.python_implementation: CPython
ssl.HAS_SNI: True
ssl.OPENSSL_VERSION: OpenSSL 1.1.0f-fips  25 May 2017
ssl.OPENSSL_VERSION_INFO: (1, 1, 0, 6, 15)
ssl.OP_ALL: -0x7fffffac
ssl.OP_NO_TLSv1_1: 0x10000000
sys.platform: linux

**Comment by vadmium** [comment]
Not sure if you just want to hide the presence of the exception and traceback. But regarding the exception itself (OSError with errno 0), this is not ideal. From memory, you tend to get this when the connection is shut down insecurely at the TCP level. A better exception would be SSLEOFError. Similar report in bpo-31122 (same wrap_socket → do_handshake chain). Probably also relevant: bpo-10808.

**Comment by tiran** [comment]
The error occurs in the test case that uses a PROTOCOL_TLS_SERVER context for both client and server context. In that case, OpenSSL wrap_socket() fails internally and OpenSSL raises an OSError with errno 0.

Simple fix: catch OSError in the client thread and fail the test appropriately.

**Comment by tiran** [comment]
New changeset 305e56c27afce605e5d2f71903a966cf0bb95038 by Christian Heimes in branch 'master':
bpo-31320: No traceback to sys.stderr in test_ssl (bpo-3360)
https://github.com/python/cpython/commit/305e56c27afce605e5d2f71903a966cf0bb95038

**Comment by Mariatta** [comment]
New changeset c506403faf8dbfc8baf4212e8e2aedb7268acb5e by Mariatta (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31320: No traceback to sys.stderr in test_ssl (GH-3360) (GH-3369)
https://github.com/python/cpython/commit/c506403faf8dbfc8baf4212e8e2aedb7268acb5e

**Comment by vstinner** [comment]
Thanks for the fix Christian.
