### ISSUE TITLE
[doc] Add example of platform-specific support for negative timestamps to the time doc

### ISSUE THREAD

**Issue by 1c433fce-d942-4e18-a18b-b162d7ee74fc** [python/cpython#75508]
BPO | [31327](https://bugs.python.org/issue31327)
--- | :---
Nosy | @tim-one, @abalkin, @ambv, @zooba, @matrixise, @pganssle, @mlouielu, @miss-islington, @slateny, @Vidhyavinu
PRs | <li>python/cpython#31460</li><li>python/cpython#31825</li><li>python/cpython#31826</li><li>python/cpython#31827</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-16.10:23:07.119>
created_at = <Date 2017-09-01.17:24:09.798>
labels = ['easy', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = '[doc] Add example of platform-specific support for negative timestamps to the time doc'
updated_at = <Date 2022-03-16.10:23:07.118>
user = 'https://bugs.python.org/jerrykramskoy'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-16.10:23:07.118>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-03-16.10:23:07.119>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-09-01.17:24:09.798>
creator = 'jerrykramskoy'
dependencies = []
files = []
hgrepos = []
issue_num = 31327
keywords = ['patch', 'easy']
message_count = 18.0
messages = ['301143', '301219', '304152', '304154', '304155', '304159', '304160', '304161', '304162', '339018', '339019', '339020', '339042', '413754', '414931', '414933', '414934', '415332']
nosy_count = 12.0
nosy_names = ['tim.peters', 'belopolsky', 'docs@python', 'lukasz.langa', 'steve.dower', 'matrixise', 'p-ganssle', 'louielu', 'jerrykramskoy', 'miss-islington', 'slateny', 'vidhya']
pr_nums = ['31460', '31825', '31826', '31827']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31327'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by 1c433fce-d942-4e18-a18b-b162d7ee74fc** [comment]
Running python 3.6.2 on Windows 10.

The following method causes presents a timetstamp value of -3600 (i.e. DST adjustment of one hour) which causes time.localtime() to raise an OS Errno 22.


```py
    def _naive_is_dst(self, dt):
        timestamp = _datetime_to_timestamp(dt)
        return time.localtime(timestamp + time.timezone).tm_isdst
```




Reproduce with python shell...

```py
import time
z=time.localtime(-3600)
Traceback (most recent call last):
  Python Shell, prompt 7, line 1
builtins.OSError: [Errno 22] Invalid argument
```




The documentation doesn't specify a legal value range for input to localtime.


Unfortunately,this causes AWS boto3 support for dynamodb to crash.

Cheers, Jerry

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
Using macOS and Linux can't reproduce this problem, both platform
return this output:

```pycon
>>> import time
>>> time.localtime(-3600)
time.struct_time(tm_year=1970, tm_mon=1, tm_mday=1, tm_hour=7, tm_min=0, tm_sec=0, tm_wday=3, tm_yday=1, tm_isdst=0)
```

**Comment by matrixise** [comment]
Hi Steve, I have added you on this issue because it's related to Windows.

Maybe you could check it.

**Comment by tim-one** [comment]
The docs for the `time` module say:

"""
Although this module is always available, not all functions are available on all platforms. Most of the functions defined in this module call platform C library functions with the same name. It may sometimes be helpful to consult the platform documentation, because the semantics of these functions varies among platforms.
"""

The Windows `localtime()` simply doesn't support dates before the epoch:

https://msdn.microsoft.com/en-us/library/aa246456(v=vs.60).aspx

**Comment by matrixise** [comment]
Thank you Tim,

In this case, the documentation seems to be correct, maybe we could close this issue because it's independent of Python.

What's your opinion on this point?

Close it or Improve the documentation?

**Comment by tim-one** [comment]
Since this is a pretty common gotcha, I'd prefer to add it as an example to the text I already quoted; e.g., add:

"""
For example, the native Windows C libraries do not support times before the epoch, and `localtime(n)` for negative `n` raises `OSError` on Windows.
"""

**Comment by matrixise** [comment]
Thank you, I will provide a PR for this issue and close it once it's over.

**Comment by tim-one** [comment]
I'll just add that it may be a different issue to argue about how `_naive_is_dst()` is implemented.

**Comment by abalkin** [comment]
Is this similar to bpo-29097?
