### ISSUE TITLE
Make 'python  -m idle' work to start IDLE

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#75500]
BPO | [31319](https://bugs.python.org/issue31319)
--- | :---
Nosy | @rhettinger, @terryjreedy, @merwok, @serhiy-storchaka, @aaronchall

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-09-04.06:33:57.650>
created_at = <Date 2017-09-01.06:56:13.600>
labels = ['expert-IDLE', 'type-feature', '3.7']
title = 'Rename idlelib to just idle'
updated_at = <Date 2017-09-04.06:33:57.608>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-04.06:33:57.608>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-09-04.06:33:57.650>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-09-01.06:56:13.600>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 31319
keywords = []
message_count = 6.0
messages = ['301086', '301087', '301088', '301106', '301137', '301210']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'eric.araujo', 'serhiy.storchaka', 'Aaron Hall']
pr_nums = []
priority = 'low'
resolution = 'later'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31319'
versions = ['Python 3.7']
```

</p></details>

**Comment by rhettinger** [comment]
Currently, I start IDLE with:

```sh
  $ python -m idlelib.idle
```


It would be nice add \_\_main__.py to simplify this to:

```sh
  $ python -m idlelib
```


And perhaps, more boldly rename the directory so that we get:

```sh
  $ python -m idle
```

**Comment by rhettinger** [comment]
I would also like Terry to consider renaming or aliasing idlelib to idle.  That would further simplify the startup and it is a more appropriate name given that IDLE is used as an application rather than as a library.

**Comment by merwok** [comment]
What about adding a simple [Lib/idle.py](https://github.com/python/cpython/blob/main/Lib/idle.py) that imports and runs the main function from idlelib?

**Comment by terryjreedy** [comment]
Summary of options to make 'python -m idle' start IDLE, with 3 more added.

0. Rename `idlelib` to `idle`.  Easy but rejected for breaking too much.
1. Symlink `idle` to `idlelib`.
2. Add /Lib/idle.py.
3. (0+1) Rename `idlelib` to `idle` and symlink `idlelib` to `idle`.
4. (0+2) Rename `idlelib' to `idle` and  `idlelib`.
5. Teach the  -m function to recognize 'idle' as an alias for 'idlelib'.

5. leave /Lib alone; the mechanism could be used for other modules if desired (though I have no candidates at the moment).
