### ISSUE TITLE
SimpleNamespace deep copy

### ISSUE THREAD

**Issue by 380e8875-9c67-42d0-9bb3-80fb1856daba** [python/cpython#75503]
BPO | [31322](https://bugs.python.org/issue31322)
--- | :---
Nosy | @stevendaprano, @ericsnowcurrently, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-01.15:13:27.668>
created_at = <Date 2017-09-01.14:51:16.388>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'SimpleNamespace deep copy'
updated_at = <Date 2017-09-01.15:13:27.667>
user = 'https://bugs.python.org/PritishPatil'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-01.15:13:27.667>
actor = 'Pritish Patil'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-01.15:13:27.668>
closer = 'Pritish Patil'
components = ['Extension Modules']
creation = <Date 2017-09-01.14:51:16.388>
creator = 'Pritish Patil'
dependencies = []
files = []
hgrepos = []
issue_num = 31322
keywords = []
message_count = 4.0
messages = ['301112', '301120', '301121', '301125']
nosy_count = 4.0
nosy_names = ['steven.daprano', 'eric.snow', 'yselivanov', 'Pritish Patil']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31322'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 380e8875-9c67-42d0-9bb3-80fb1856daba** [comment]
I am new here and not sure how I can suggest this properly.


When using nested SimpleNamespaces, a making a copy by using 

```py
new_NS=SimpleNamespace(**namespace.__dict__.copy())
```


only copies the highest level namespace. This is expected in python as shallow copies are preferred. But, a nested deep copy function would be nice, and will allow easier use.

I suggest a simple

```py
def my_namespace_copy(namespace):
    '''Recursively deep copies nested namespaces'''
    new_NS=SimpleNamespace(**namespace.__dict__.copy())
    for i in new_NS.__dict__.keys():
        if(type(new_NS.__dict__[i]) == types.SimpleNamespace):
            new_NS.__setattr__(i, my_namespace_copy(new_NS.__getattribute__(i)))
    return new_NS
```


I am not sure of the exact implementation of the class and guess this would need some appropriate modifications.

I suggest this be added at SimpleNameSpace.\_\_copy__ or at SimpleNameSpace.\_\_deepcopy__

**Comment by stevendaprano** [comment]
> When using nested SimpleNamespaces, a making a copy by using 
> 
> new_NS=SimpleNamespace(**namespace.\_\_dict__.copy())

In general, you shouldn't call or directly access dunder attributes. 
There are exceptions, but generally they're for Python's use only. For 
example, the public interface for getting \_\_dict__ is to call 
vars(namespace).

But there's no need to do this by hand. Use the copy module instead.

```py
copy.copy(namespace)  # copy one level only

copy.deepcopy(namespace)  # copy all the way down
```


seem to work for me.

Does this solve your problem? If so, we'll close this issue.

**Comment by ericsnowcurrently** [comment]
Hmm.  What problems are you seeing with deep copies?  copy.deepcopy() should work since SimpleNamespace is picklable. [1][2]  I don't have any problems:

```pycon
>>> import types, copy
>>> ns = types.SimpleNamespace(x=1, y=2)
>>> copied = copy.deepcopy(ns)
>>> copied
namespace(x=1, y=2)
>>> ns = types.SimpleNamespace(x=types.SimpleNamespace(a=1),
                               y=types.SimpleNamespace(b=2))
>>> copied = copy.deepcopy(ns)
>>> copied
namespace(x=namespace(a=1), y=namespace(b=2))
>>> ns.x is copied.x
False
```


[1] issue bpo-15022
[2] https://docs.python.org/3/library/copy.html

**Comment by 380e8875-9c67-42d0-9bb3-80fb1856daba** [comment]
Yes. copy.deepcopy() works. 

Didn't think of it!
