### ISSUE TITLE
req_rate is a namedtuple type rather than instance

### ISSUE THREAD

**Issue by 96306edd-cf83-4aab-be7e-fdcccd64c37f** [python/cpython#75506]
BPO | [31325](https://bugs.python.org/issue31325)
--- | :---
Nosy | @rhettinger, @berkerpeksag, @serhiy-storchaka, @gvx
PRs | <li>python/cpython#3259</li><li>python/cpython#4529</li><li>python/cpython#4533</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/berkerpeksag'
closed_at = <Date 2017-11-23.23:58:51.954>
created_at = <Date 2017-09-01.15:15:22.782>
labels = ['3.7', 'type-bug', 'library']
title = 'req_rate is a namedtuple type rather than instance'
updated_at = <Date 2017-11-23.23:58:51.954>
user = 'https://github.com/gvx'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-23.23:58:51.954>
actor = 'rhettinger'
assignee = 'berker.peksag'
closed = True
closed_date = <Date 2017-11-23.23:58:51.954>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-09-01.15:15:22.782>
creator = 'gvx'
dependencies = []
files = []
hgrepos = []
issue_num = 31325
keywords = ['patch']
message_count = 10.0
messages = ['301127', '301134', '301148', '301152', '303528', '303550', '303553', '303561', '306861', '306862']
nosy_count = 4.0
nosy_names = ['rhettinger', 'berker.peksag', 'serhiy.storchaka', 'gvx']
pr_nums = ['3259', '4529', '4533']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31325'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 96306edd-cf83-4aab-be7e-fdcccd64c37f** [comment]
> Finally, urllib/robotparser.py appears to contain a bug in the
> following:
>
>   req_rate = collections.namedtuple('req_rate',
>                                    'requests seconds')
>   entry.req_rate = req_rate
>   entry.req_rate.requests = int(numbers[0])
>   entry.req_rate.seconds = int(numbers[1])
> 
> As I read it, this should fail as the req_rate is immutable.

Ref: https://news.ycombinator.com/item?id=15136961

They are mistaken in the nature of the bug, which is that req_rate is
a namedtuple type, rather than an instance. As such, it is actually
mutable, causing the assignments to not fail. Every entry creates a
separate req_rate type, so it all works, but not in the way it should.

**Comment by rhettinger** [comment]
* The named tuple class should begin with a capital letter and be fully self-documenting: "RequestRate".

* The creation of the named tuple class should be done only once, not on every call.  Instead only a new instance should be creating on every call:

```py
     entry.req_rate = req_rate(RequestRate)
```


* There needs to be a test.

* The docstring should be updated to include the name of the class refer to the term named tuple instead of the namedtuple() factory function:

     - Returns the contents of the ``Request-rate`` parameter from
     - ``robots.txt`` in the form of a :func:`~collections.namedtuple`
     - ``(requests, seconds)``.  If there is no such parameter or it doesn't

     + Returns the contents of the ``Request-rate`` parameter from
     + ``robots.txt`` as a :term:`named tuple` ``RequestRate(requests, seconds)``.
     + If there is no such parameter or it doesn't

**Comment by berkerpeksag** [comment]
Good catch and thank you for turning the bug report in the HN thread to a pull request! I agree with all of Raymond's comments.

I have two more comments:

* Please follow our commit style at https://devguide.python.org/committing/#commit-messages
* We need a NEWS entry. You can find details at https://devguide.python.org/committing/#what-s-new-and-news-entries (we don't need to add an entry in [Doc/whatsnew/](https://github.com/python/cpython/blob/main/Doc/whatsnew) so you can safely ignore it)

**Comment by rhettinger** [comment]
There was a typo in my previous message.  The instantiation code should be:

```py
   entry.req_rate = RequestRate(int(numbers[0]), int(numbers[1]))
```

**Comment by serhiy-storchaka** [comment]
What is a reason of making req_rate a named tuple?

**Comment by rhettinger** [comment]
> What is a reason of making req_rate a named tuple?

I don't know the original reason but it seems like a normal use of named tuples to make the data more self-describing to help with debugging and also to support field access by name, rr.requests or rr.seconds is clearer than rr[0] or rr[1].

**Comment by serhiy-storchaka** [comment]
This is a normal use of named tuples for adding access by name to tuple results. But req_rate never was a tuple. Nobody used rr[0].

**Comment by rhettinger** [comment]
There is no rule that something had to be a tuple at some point in its history before becoming a named tuple.  This use seems perfectly reasonable to me.

**Comment by rhettinger** [comment]
New changeset 3df02dbc8e197053105f9dffeae40b04ec66766e by Raymond Hettinger (Berker Peksag) in branch 'master':
bpo-31325: Fix usage of namedtuple in RobotFileParser.parse() (bpo-4529)
https://github.com/python/cpython/commit/3df02dbc8e197053105f9dffeae40b04ec66766e

**Comment by rhettinger** [comment]
New changeset ff847d1ac7e6a8ee1fb6f8883cfb4aec4b4a9b03 by Raymond Hettinger (Miss Islington (bot)) in branch '3.6':
bpo-31325: Fix usage of namedtuple in RobotFileParser.parse() (GH-4529) (bpo-4533)
https://github.com/python/cpython/commit/ff847d1ac7e6a8ee1fb6f8883cfb4aec4b4a9b03
