### ISSUE TITLE
Small opportunity for NULL dereference in compile.c

### ISSUE THREAD

**Issue by warsaw** [python/cpython#75518]
BPO | [31337](https://bugs.python.org/issue31337)
--- | :---
Nosy | @warsaw, @skrah, @serhiy-storchaka
PRs | <li>python/cpython#3282</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/warsaw'
closed_at = <Date 2017-09-06.00:42:50.268>
created_at = <Date 2017-09-04.16:43:32.129>
labels = ['interpreter-core', '3.7']
title = 'Small opportunity for NULL dereference in compile.c'
updated_at = <Date 2017-09-06.00:42:50.266>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.00:42:50.266>
actor = 'barry'
assignee = 'barry'
closed = True
closed_date = <Date 2017-09-06.00:42:50.268>
closer = 'barry'
components = ['Interpreter Core']
creation = <Date 2017-09-04.16:43:32.129>
creator = 'barry'
dependencies = []
files = []
hgrepos = []
issue_num = 31337
keywords = []
message_count = 9.0
messages = ['301222', '301223', '301224', '301225', '301228', '301229', '301234', '301245', '301417']
nosy_count = 3.0
nosy_names = ['barry', 'skrah', 'serhiy.storchaka']
pr_nums = ['3282']
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31337'
versions = ['Python 3.7']
```

</p></details>

**Comment by warsaw** [comment]
There is a very minor opportunity for NULL dereference in compile.c.  compiler_subdict() does not check the return value of get_const_value(), which could be NULL.  This was found by Kirit Sankar Gupta.

This is not a security issue in practice, since compiler_subdict() calls are_all_items_const() before it gets to the call, so the condition which triggers get_const_value() to return NULL will never happen (i.e. the default: clause of get_const_value()).  Still, it can't hurt to be more correct in case the conditions which are implicitly assumed could change.  Plus the fix is super easy, so why not do it?

**Comment by warsaw** [comment]
As it's barely worth fixing, it's not worth backporting.

**Comment by serhiy-storchaka** [comment]
The default case is added just for silencing compiler warning. It is never executed. There are a number of places in the core that look like

    assert(0);
    return NULL; /* or whatever */

This is a dead code, but compilers complain without it.

How do you suggest to improve this code?

**Comment by warsaw** [comment]
I'll preface that it's not a major issue that I feel \*has* to be fixed, but given that assert \*can* be compiled away, does it make sense to use abort() instead?  E.g.

1 file changed, 2 insertions(+), 2 deletions(-)
[Python/compile.c](https://github.com/python/cpython/blob/main/Python/compile.c) | 4 ++--

```diff
modified   Python/compile.c
@@ -1350,8 +1350,8 @@ get_const_value(expr_ty e)
     case NameConstant_kind:
         return e->v.NameConstant.value;
     default:
-        assert(!is_const(e));
-        return NULL;
+        /* We should never get here. */
+        abort();
     }
 }
 
```


This at least makes gcc happy and makes the intent clearer.

**Comment by serhiy-storchaka** [comment]
Could you please also look at other asserts? I have counted 48 occurrences of assert(0), 11 assert(0 && "message") and 2 assert(!"message"). If fix one occurrence, why not fix all others?

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
I'm very much in favor of using abort() /* NOT REACHED \*/ in such cases.

The only drawback is that in the case of libraries, sometimes
distribution package lint tools complain.

**Comment by warsaw** [comment]
On Sep 4, 2017, at 10:18, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> Serhiy Storchaka added the comment:
> 
> Could you please also look at other asserts? I have counted 48 occurrences of assert(0), 11 assert(0 && "message") and 2 assert(!"message"). If fix one occurrence, why not fix all others?

I think it makes sense to change them all, probably using the pattern that Stefan gave, but let’s do that in a separate issue.

**Comment by warsaw** [comment]
See bpo-31338 for adopting the abort() idiom.

**Comment by warsaw** [comment]
Alright, I'm going to close this bug in favor of bpo-31338
