### ISSUE TITLE
test.bisect module causes tests to fail

### ISSUE THREAD

**Issue by nascheme** [python/cpython#75523]
BPO | [31342](https://bugs.python.org/issue31342)
--- | :---
Nosy | @nascheme, @vstinner
Files | <li>[test_datetime_out.txt](https://bugs.python.org/file47119/test_datetime_out.txt "Uploaded as text/plain at 2017-09-05.04:28:07 by @nascheme")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = <Date 2018-07-17.01:50:03.197>
created_at = <Date 2017-09-04.21:48:37.228>
labels = ['type-bug']
title = 'test.bisect module causes tests to fail'
updated_at = <Date 2018-07-17.11:27:14.592>
user = 'https://github.com/nascheme'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-17.11:27:14.592>
actor = 'vstinner'
assignee = 'vstinner'
closed = True
closed_date = <Date 2018-07-17.01:50:03.197>
closer = 'nascheme'
components = []
creation = <Date 2017-09-04.21:48:37.228>
creator = 'nascheme'
dependencies = []
files = ['47119']
hgrepos = []
issue_num = 31342
keywords = []
message_count = 7.0
messages = ['301271', '301288', '301296', '321761', '321774', '321785', '321814']
nosy_count = 2.0
nosy_names = ['nascheme', 'vstinner']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31342'
versions = []
```

</p></details>

**Comment by nascheme** [comment]
After a lot of head scratching, I have discovered why tests are failing for me.  E.g. "./python [Lib/test/test_datetime.py](https://github.com/python/cpython/blob/main/Lib/test/test_datetime.py)" results in

AttributeError: module 'bisect' has no attribute 'bisect_right'

Running tests this way causes test/bisect to be imported rather than the std library bisect module.  I'm not sure of the correct fix, perhaps rename test.bisect?

Patch that added it: bpo-29512: Add test.bisect, bisect failing tests

**Comment by vstinner** [comment]
Can you put the whole traceback? I'm unable to reproduce the issue. Which datetime test uses biesct?

**Comment by nascheme** [comment]
The key is how the test is run.  If you run:

```sh
$ ./python Lib/test/<some script>.py
```


Then the [Lib/test](https://github.com/python/cpython/blob/main/Lib/test) gets added to the first part of sys.path.  Then "import bisect" imports the [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) module rather than [Lib/bisect.py](https://github.com/python/cpython/blob/main/Lib/bisect.py).  Obvious options seem to be:

1. rename [Lib/test/bisect.py](https://github.com/python/cpython/blob/main/Lib/test/bisect.py) to something else
 
2. don't allow running files in [Lib/test](https://github.com/python/cpython/blob/main/Lib/test) as scripts

To me, #2 is not a good option.  I'm attaching the output of:

./python.exe [Lib/test/regrtest.py](https://github.com/python/cpython/blob/main/Lib/test/regrtest.py) -v test_datetime 2\>&1

In case it is helpful.  I pruned some lines to keep the file smaller.
