### ISSUE TITLE
Include major(), minor(), makedev() from sysmacros

### ISSUE THREAD

**Issue by tiran** [python/cpython#75524]
BPO | [31343](https://bugs.python.org/issue31343)
--- | :---
Nosy | @tiran, @serhiy-storchaka
PRs | <li>python/cpython#3318</li><li>python/cpython#3344</li><li>python/cpython#3345</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-05.15:09:27.675>
created_at = <Date 2017-09-04.21:50:37.081>
labels = ['extension-modules', 'build', '3.7']
title = 'Include major(), minor(), makedev() from sysmacros'
updated_at = <Date 2017-10-17.22:02:24.383>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-17.22:02:24.383>
actor = 'fweimer'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-05.15:09:27.675>
closer = 'christian.heimes'
components = ['Extension Modules']
creation = <Date 2017-09-04.21:50:37.081>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 31343
keywords = []
message_count = 5.0
messages = ['301272', '301311', '301315', '301316', '304501']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'serhiy.storchaka', 'fweimer']
pr_nums = ['3318', '3344', '3345']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31343'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by tiran** [comment]
On Fedora 26, GCC is emitting warnings because we are using minor(), major() and makedev() 
from sys/types.h. The macros should be included from sys/sysmacros.h instead:

./Modules/posixmodule.c: In function ‘os_major_impl’:
./Modules/posixmodule.c:8758:13: warning: In the GNU C Library, "major" is defined
 by \<sys/sysmacros.h\>. For historical compatibility, it is
 currently defined by \<sys/types.h\> as well, but we plan to
 remove this soon. To use "major", include \<sys/sysmacros.h\>
 directly. If you did not intend to use a system-defined macro
 "major", you should undefine it after including \<sys/types.h\>.
     return major(device);
             \^~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                           
./Modules/posixmodule.c: In function ‘os_minor_impl’:
./Modules/posixmodule.c:8775:13: warning: In the GNU C Library, "minor" is defined
 by \<sys/sysmacros.h\>. For historical compatibility, it is
 currently defined by \<sys/types.h\> as well, but we plan to
 remove this soon. To use "minor", include \<sys/sysmacros.h\>
 directly. If you did not intend to use a system-defined macro
 "minor", you should undefine it after including \<sys/types.h\>.
     return minor(device);
             \^~~~~~~~~~~~~                                                                                                                                                                                                                                                                                                                                                           
./Modules/posixmodule.c: In function ‘os_makedev_impl’:
./Modules/posixmodule.c:8793:13: warning: In the GNU C Library, "makedev" is defined
 by \<sys/sysmacros.h\>. For historical compatibility, it is
 currently defined by \<sys/types.h\> as well, but we plan to
 remove this soon. To use "makedev", include \<sys/sysmacros.h\>
 directly. If you did not intend to use a system-defined macro
 "makedev", you should undefine it after including \<sys/types.h\>.
     return makedev(major, minor);
             \^~~~~~~~~~~~~~~~~~~~~

**Comment by tiran** [comment]
New changeset 75b961869a1184895c9d5bf41a57f3c985622662 by Christian Heimes in branch 'master':
bpo-31343: Include sys/sysmacros.h (bpo-3318)
https://github.com/python/cpython/commit/75b961869a1184895c9d5bf41a57f3c985622662

**Comment by tiran** [comment]
New changeset ffa7011cb904ee6ad9d4931b073c13d9e1514e6b by Christian Heimes in branch '2.7':
[2.7] bpo-31343: Include sys/sysmacros.h (GH-3318) (bpo-3345)
https://github.com/python/cpython/commit/ffa7011cb904ee6ad9d4931b073c13d9e1514e6b

**Comment by tiran** [comment]
New changeset 02854dab6231d726fa2c63d44ab25598988c44f4 by Christian Heimes in branch '3.6':
[3.6] bpo-31343: Include sys/sysmacros.h (GH-3318) (bpo-3344)
https://github.com/python/cpython/commit/02854dab6231d726fa2c63d44ab25598988c44f4

**Comment by serhiy-storchaka** [comment]
Louie Lu proposed the fix for this issue in bpo-30013.
