### ISSUE TITLE
Pull zlib out to cpython-source-deps

### ISSUE THREAD

**Issue by zware** [python/cpython#75539]
BPO | [31358](https://bugs.python.org/issue31358)
--- | :---
Nosy | @doko42, @pfmoore, @tjguk, @zware, @zooba
PRs | <li>python/cpython#3375</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-07.00:34:51.421>
created_at = <Date 2017-09-06.00:43:52.330>
labels = ['type-feature', '3.7', 'OS-windows', 'build']
title = 'Pull zlib out to cpython-source-deps'
updated_at = <Date 2017-09-07.00:34:51.421>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-07.00:34:51.421>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-07.00:34:51.421>
closer = 'zach.ware'
components = ['Build', 'Windows']
creation = <Date 2017-09-06.00:43:52.330>
creator = 'zach.ware'
dependencies = []
files = []
hgrepos = []
issue_num = 31358
keywords = []
message_count = 3.0
messages = ['301418', '301442', '301552']
nosy_count = 5.0
nosy_names = ['doko', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = ['3375']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31358'
versions = ['Python 3.7']
```

</p></details>

**Comment by zware** [comment]
We currently bundle zlib in our source at [Modules/zlib](https://github.com/python/cpython/blob/main/Modules/zlib), but it is only used on Windows.  The soon-to-be-attached PR instead pulls it from https://github.com/python/cpython-source-deps

There is one failure in test_venv only when zlib is not built at all, which I have not yet investigated.

/cc doko as the most recent updater of the bundled copy of zlib.

**Comment by doko42** [comment]
+1, if that's ok with the Windows maintainers.

**Comment by zware** [comment]
New changeset d01db1c2a2a71455163a1d3b214cc8dc27201303 by Zachary Ware in branch 'master':
bpo-31358: Pull zlib out of the repository (GH-3375)
https://github.com/python/cpython/commit/d01db1c2a2a71455163a1d3b214cc8dc27201303
