### ISSUE TITLE
Fixing a bug related to LTO only build

### ISSUE THREAD

**Issue by c3813e2c-4ffd-40ca-a270-4322e30c3407** [python/cpython#75535]
BPO | [31354](https://bugs.python.org/issue31354)
--- | :---
Nosy | @gpshead, @vstinner, @ned-deily, @stratakis, @octaviansoldea
PRs | <li>python/cpython#3110</li><li>python/cpython#10261</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2018-12-09.09:08:30.867>
created_at = <Date 2017-09-05.21:54:13.298>
labels = ['3.8', 'type-feature', '3.7', 'build']
title = 'Fixing a bug related to LTO only build'
updated_at = <Date 2018-12-09.09:08:30.865>
user = 'https://github.com/octaviansoldea'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-09.09:08:30.865>
actor = 'ned.deily'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2018-12-09.09:08:30.867>
closer = 'ned.deily'
components = ['Build']
creation = <Date 2017-09-05.21:54:13.298>
creator = 'octavian.soldea'
dependencies = []
files = []
hgrepos = []
issue_num = 31354
keywords = []
message_count = 11.0
messages = ['301381', '301385', '301722', '329444', '329844', '329876', '329897', '329925', '331346', '331351', '331418']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'vstinner', 'ned.deily', 'cstratak', 'octavian.soldea']
pr_nums = ['3110', '10261']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31354'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by c3813e2c-4ffd-40ca-a270-4322e30c3407** [comment]
Hi All,

This is Octavian Soldea from the Scripting Languages Optimization team at Intel Corporation. I would like to submit a patch to fix an LTO build issue. With "./configure --with-lto" followed by "make", CPython should be built with LTO or Link-Time-Optimization. However, currently, no impact is made to the build process, meaning the flag is not effective. This patch has been created out of a python-dev discussion thread: http://www.mail-archive.com/python-dev@python.org/msg96469.html. The LTO flag was originally introduced by my team member Alecsandru Patrascu back in 2015: https://bugs.python.org/issue25702.

Before the change:

./configure --with-lto
make
gcc command line output example:
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -I. -I./Include -DPy_BUILD_CORE -o [Python/ceval.o](https://github.com/python/cpython/blob/main/Python/ceval.o) [Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c)
Note no "lto" flag was present. This is the same result as the default build without the LTO flag.

After changes:

./configure --with-lto
make
expected gcc command line output example =\>
gcc -pthread -c -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -flto -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Werror=implicit-function-declaration -I. -I./Include -DPy_BUILD_CORE -o [Python/ceval.o](https://github.com/python/cpython/blob/main/Python/ceval.o) [Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c)

Thanks,
Octavian

**Comment by vstinner** [comment]
Would you mind to create a pull request?

**Comment by gpshead** [comment]
New changeset 4c81401b3a9ffa48fc9e1ffff9963cbad5111e33 by Gregory P. Smith (octaviansoldea) in branch 'master':
bpo-31354: Let configure --with-lto work on all builds
https://github.com/python/cpython/commit/4c81401b3a9ffa48fc9e1ffff9963cbad5111e33
