### ISSUE TITLE
Remove Travis CI macOS job: rely on buildbots

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75536]
BPO | [31355](https://bugs.python.org/issue31355)
--- | :---
Nosy | @brettcannon, @pitrou, @vstinner, @ned-deily, @zware
PRs | <li>python/cpython#3367</li><li>python/cpython#5858</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-27.20:40:55.606>
created_at = <Date 2017-09-05.23:24:41.735>
labels = ['build', '3.7']
title = 'Remove Travis CI macOS job: rely on buildbots'
updated_at = <Date 2018-02-27.20:40:55.605>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-27.20:40:55.605>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-27.20:40:55.606>
closer = 'pitrou'
components = ['Build']
creation = <Date 2017-09-05.23:24:41.735>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31355
keywords = ['patch']
message_count = 15.0
messages = ['301398', '301408', '301411', '301413', '301421', '301430', '301431', '301466', '302550', '302815', '312631', '312647', '312761', '312831', '313023']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'pitrou', 'vstinner', 'ned.deily', 'zach.ware']
pr_nums = ['3367', '5858']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31355'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Currently, Travis CI has a job running tests on macOS. Sadly, there is a bug on Travis: \*sometimes*, the macOS job blocks a Pull Request to be merged even if macOS is marked as "Allowed Failure". If you cancel the job, it's even worse: Travis CI is marked a failed and the PR cannot be merged.

I tried to cancel the build and restart it, but 2 hours later, the macOS job was still queued and I was still unable to merge my PR.

We cannot work around the Travis CI issue. We are getting more and more pull requests, especially this week with the CPython sprint, so the macOS queue is getting even longer.

I discussed the issue with Zachary Ware and we agreed to "disable" ("remove" in practice) the macOS job for this week, and rely on the macOS buildbots instead.

We have 3 macOS buildbots (x86 Tiger 3.x, x86-64 El Capitan 3.x, x86-64 Sierra 3.x) and I worked hard last months to get buildbots green. So we should be quickly notified of failures. There is now the buildbot-status mailing list for this purpose!

https://mail.python.org/mm3/mailman3/lists/buildbot-status.python.org/

I already reported the issue twice on python-committers mailing list in June and September (this year):

* https://mail.python.org/pipermail/python-committers/2017-September/004824.html
* https://mail.python.org/pipermail/python-committers/2017-June/004661.html

**Comment by vstinner** [comment]
Failures of the two Allowed Failure jobs, coverage and macOS, are not reported to GitHub PR. For example, the coverage job is failing on Python 3.6 since May 2016 at least, and nobody noticed.

I don't think that it's worth it to waste Travis CI resources if nobody notices failures.

See https://github.com/python/core-workflow/issues/101 for the discussion on Allowed Failures on Travis CI.

**Comment by ned-deily** [comment]
Since Travis CI time is a bottleneck for the ongoing sprint, I agree that it makes sense to disable the macOS build checks for now.  Longer term, it would be nice to resolve the problem but we certainly could rely on our own macOS buildbots; I'm not aware of many (any?) instances yet where the Travis macOS instance has caught a problem.  I think Brett should make the call on whether to permanently disable this after he gets back.

**Comment by zware** [comment]
I will note that my on-going research on rewriting the buildbot config makes it look like we should be able to securely enable building PRs by checking for the 'awaiting merge' label.

**Comment by vstinner** [comment]
New changeset 501b324d3a940d26e0021a38aae8d896a30fbcff by Victor Stinner in branch 'master':
bpo-31355: Travis CI: remove the macOS job (bpo-3367)
https://github.com/python/cpython/commit/501b324d3a940d26e0021a38aae8d896a30fbcff

**Comment by ned-deily** [comment]
New changeset 11453524ed26ee449275c32bedfd86ef19dd91ee by Ned Deily (Victor Stinner) in branch '3.6':
bpo-31355: Travis CI: remove the macOS job (bpo-3367)
https://github.com/python/cpython/commit/11453524ed26ee449275c32bedfd86ef19dd91ee

**Comment by ned-deily** [comment]
New changeset 2bc83afb30850f682487ffa560c9e3663788baaa by Ned Deily (Victor Stinner) in branch '2.7':
bpo-31355: Travis CI: remove the macOS job (bpo-3367)
https://github.com/python/cpython/commit/2bc83afb30850f682487ffa560c9e3663788baaa

**Comment by pitrou** [comment]
> I'm not aware of many (any?) instances yet where the Travis macOS instance has caught a problem.

It did help me on some delicate signals/threading issues.

**Comment by brettcannon** [comment]
Should this be closed?

**Comment by vstinner** [comment]
Yeah, I consider that the issue can now be closed. If someone really wants runnings checks on macOS, we should wait until Travis CI solves their issues, or find a different CI provider.

https://blog.travis-ci.com/2017-09-22-macos-update
