### ISSUE TITLE
Implement PEP 553 - built-in breakpoint()

### ISSUE THREAD

**Issue by warsaw** [python/cpython#75534]
BPO | [31353](https://bugs.python.org/issue31353)
--- | :---
Nosy | @warsaw, @bitdancer, @serhiy-storchaka, @ethanhs, @alkuzad
PRs | <li>python/cpython#3355</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/warsaw'
closed_at = <Date 2017-10-05.16:11:54.413>
created_at = <Date 2017-09-05.20:44:20.033>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Implement PEP 553 - built-in breakpoint()'
updated_at = <Date 2018-07-09.17:47:30.913>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-09.17:47:30.913>
actor = 'barry'
assignee = 'barry'
closed = True
closed_date = <Date 2017-10-05.16:11:54.413>
closer = 'barry'
components = ['Interpreter Core']
creation = <Date 2017-09-05.20:44:20.033>
creator = 'barry'
dependencies = []
files = []
hgrepos = []
issue_num = 31353
keywords = []
message_count = 6.0
messages = ['301372', '302109', '302110', '303573', '321306', '321337']
nosy_count = 5.0
nosy_names = ['barry', 'r.david.murray', 'serhiy.storchaka', 'ethan smith', 'alkuzad']
pr_nums = ['3355']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31353'
versions = ['Python 3.7']
```

</p></details>

**Comment by warsaw** [comment]
Placeholder issue for discussion of the design of the implementation of PEP-553.

**Comment by f8abd1df-fedc-4d62-89c9-35304b41bbba** [comment]
Will that be backported also to Python2.7 ? I personally do not see a reason to teach old dog new tricks but it seems appropriate in such core things. New users could transition easier, otherwise this would be next py2\<-\>py3 difference to explain every time someone uses new code.

**Comment by bitdancer** [comment]
It is a new feature, so no it would not be backported.

**Comment by warsaw** [comment]
PEP is accepted.  PR needs review.
