### ISSUE TITLE
"async" and "await" are not keyword

### ISSUE THREAD

**Issue by 9ee5d0b6-b50d-4df0-b5f3-86d06d7afd4a** [python/cpython#75543]
BPO | [31362](https://bugs.python.org/issue31362)
--- | :---
Nosy | @1st1, @ammaraskar

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-06.07:52:33.101>
created_at = <Date 2017-09-06.06:20:02.374>
labels = ['type-bug', 'expert-asyncio']
title = '"async" and "await" are not keyword'
updated_at = <Date 2017-09-06.07:52:33.100>
user = 'https://bugs.python.org/ConorCal'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.07:52:33.100>
actor = 'Conor Cal'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-06.07:52:33.101>
closer = 'Conor Cal'
components = ['asyncio']
creation = <Date 2017-09-06.06:20:02.374>
creator = 'Conor Cal'
dependencies = []
files = []
hgrepos = []
issue_num = 31362
keywords = []
message_count = 4.0
messages = ['301443', '301444', '301445', '301453']
nosy_count = 3.0
nosy_names = ['yselivanov', 'ammar2', 'Conor Cal']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31362'
versions = ['Python 3.6']
```

</p></details>

**Comment by 9ee5d0b6-b50d-4df0-b5f3-86d06d7afd4a** [comment]
"async" and "await" became kaywords in CPython 3.6. but in the keyword library, they are not in kwlist, and will return False by iskeyword method.

**Comment by 9ee5d0b6-b50d-4df0-b5f3-86d06d7afd4a** [comment]
"async" and "await" became kaywords in CPython 3.6. But they are not in kwlist of the keyword library, and will return False by iskeyword method.

**Comment by ammaraskar** [comment]
For what its worth, "async" and "await" are special keywords. They only act as keywords under certain situations by the tokenizer. You can read more about this here: https://www.python.org/dev/peps/pep-0492/#transition-plan

As far as I am aware, this special casing exists even in the latest version: https://github.com/python/cpython/blob/master/Parser/tokenizer.c#L1553-L1588

**Comment by 9ee5d0b6-b50d-4df0-b5f3-86d06d7afd4a** [comment]
thanks Ammar Askar, I also find this Issue is duplidcate, bpo-26264 has the same question. So I'll just close this oen.
