### ISSUE TITLE
argparse mutually_exclusive_group under add_argument_group fails if part of parent_processor

### ISSUE THREAD

**Issue by a1f79920-b6fc-44ea-ad2b-a1825616e6d0** [python/cpython#75541]
BPO | [31360](https://bugs.python.org/issue31360)
--- | :---
Nosy | @vadmium
Superseder | <li>bpo-25882: argparse help error: arguments created by add_mutually_exclusive_group() are shown outside their parent group created by add_argument_group()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-06.11:26:42.780>
created_at = <Date 2017-09-06.03:42:16.859>
labels = ['type-bug', 'library']
title = 'argparse mutually_exclusive_group under add_argument_group fails if part of parent_processor'
updated_at = <Date 2017-09-06.11:26:42.770>
user = 'https://bugs.python.org/PaulTrainadiscontent'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.11:26:42.770>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-06.11:26:42.780>
closer = 'martin.panter'
components = ['Library (Lib)']
creation = <Date 2017-09-06.03:42:16.859>
creator = 'Paul Traina (discontent)'
dependencies = []
files = []
hgrepos = []
issue_num = 31360
keywords = []
message_count = 2.0
messages = ['301437', '301460']
nosy_count = 2.0
nosy_names = ['martin.panter', 'Paul Traina (discontent)']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '25882'
type = 'behavior'
url = 'https://bugs.python.org/issue31360'
versions = ['Python 3.6']
```

</p></details>

**Comment by a1f79920-b6fc-44ea-ad2b-a1825616e6d0** [comment]
Hopefully I'm not being obtuse, but I seem to be getting incorrect/unexpected help output when using mutually_exclusive_group under an add_argument_group if this layering is happening in a parent parser.

Here's an example of the triggering usage:

```py
import argparse

global_options = argparse.ArgumentParser(add_help=False)
global_options.add_argument('--summary', action='store_true', help='summarize information')
global_options.add_argument('--verbose', action='store_true', help='tell us more')

output_format = global_options.add_argument_group("Output format", "ways to foo")
styles = output_format.add_mutually_exclusive_group()
styles.add_argument('--plain', dest='style')
styles.add_argument('--green', dest='style')
styles.add_argument('--blue', dest='style')

parser = argparse.ArgumentParser()
commands = parser.add_subparsers()
hit = commands.add_parser('hit', parents=[global_options])
miss = commands.add_parser('miss', parents=[global_options])

print(parser.parse_args(['hit', '-h']))
```


which produces:

usage: bar.py hit [-h] [--summary] [--verbose]
                  [--plain STYLE | --green STYLE | --blue STYLE]

optional arguments:
  -h, --help     show this help message and exit
  --summary      summarize information
  --verbose      tell us more
  --plain STYLE
  --green STYLE
  --blue STYLE

Output format:
  ways to foo


"--plain" "--green" and "--blue" \*should* be under "Output format"

**Comment by vadmium** [comment]
Seems the same as two other open bugs: bpo-25882 and bpo-16807.
