### ISSUE TITLE
Possible problem with PR #3377

### ISSUE THREAD

**Issue by 1cb85035-97d8-42c3-a287-2706aee5fe65** [python/cpython#75545]
BPO | [31364](https://bugs.python.org/issue31364)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @benjaminp, @zware, @zooba, @denis-osipov
PRs | <li>python/cpython#3377</li>
Files | <li>[output.txt](https://bugs.python.org/file47123/output.txt "Uploaded as text/plain at 2017-09-06.08:07:46 by @denis-osipov"): Output with warnings and errors</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-06.14:20:14.718>
created_at = <Date 2017-09-06.08:07:47.968>
labels = ['build', '3.7', 'OS-windows']
title = 'Possible problem with PR python/cpython#47627'
updated_at = <Date 2017-09-06.14:20:14.717>
user = 'https://github.com/denis-osipov'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-06.14:20:14.717>
actor = 'denis-osipov'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-06.14:20:14.718>
closer = 'denis-osipov'
components = ['Windows']
creation = <Date 2017-09-06.08:07:47.968>
creator = 'denis-osipov'
dependencies = []
files = ['47123']
hgrepos = []
issue_num = 31364
keywords = []
message_count = 2.0
messages = ['301455', '301459']
nosy_count = 7.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'benjamin.peterson', 'zach.ware', 'steve.dower', 'denis-osipov']
pr_nums = ['3377']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31364'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
It looks like last PR bpo-3377 changing pytime.c (adding #include \<winsock2.h\>) causing problem with compilation. Now on my Win10 i have multiple warnings and errors about ws2def.h, winsock.h and winsock2.h (see attached file).

**Comment by pitrou** [comment]
AppVeyor breaks as well:
https://ci.appveyor.com/project/python/cpython/build/3.7.0a0.5986#L200
