### ISSUE TITLE
Remove support for threads-less builds

### ISSUE THREAD

**Issue by pitrou** [python/cpython#75551]
BPO | [31370](https://bugs.python.org/issue31370)
--- | :---
Nosy | @brettcannon, @gpshead, @pitrou, @tiran, @bitdancer, @briancurtin, @pmp-p, @serhiy-storchaka, @kb-1000
PRs | <li>python/cpython#3385</li><li>python/cpython#3482</li><li>python/cpython#3648</li><li>python/cpython#3649</li><li>python/cpython#8805</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-03.06:42:40.326>
created_at = <Date 2017-09-06.21:10:49.815>
labels = ['interpreter-core', 'type-feature', '3.7', 'build']
title = 'Remove support for threads-less builds'
updated_at = <Date 2022-03-09.09:35:58.994>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-09.09:35:58.994>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-03.06:42:40.326>
closer = 'berker.peksag'
components = ['Build', 'Interpreter Core']
creation = <Date 2017-09-06.21:10:49.815>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 31370
keywords = ['patch']
message_count = 29.0
messages = ['301518', '301520', '301521', '301539', '301543', '301559', '301595', '301596', '301805', '301964', '301968', '301971', '301973', '301980', '301987', '301988', '302474', '302476', '302484', '302492', '326681', '348490', '408243', '408257', '408501', '408508', '408518', '408575', '408594']
nosy_count = 11.0
nosy_names = ['brett.cannon', 'gregory.p.smith', 'pitrou', 'christian.heimes', 'Arfrever', 'r.david.murray', 'brian.curtin', 'pmpp', 'serhiy.storchaka', 'kb1000', 'Steve Gomez']
pr_nums = ['3385', '3482', '3648', '3649', '8805']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31370'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
The --without-threads option has a lot of repercussions on the code base, forcing us to maintain specific paths for builds with threads disabled, for no useful purpose.

**Comment by pitrou** [comment]
See discussion in https://mail.python.org/pipermail/python-dev/2017-September/149156.html

**Comment by pitrou** [comment]
Question: should we keep [Modules/Setup.config.in](https://github.com/python/cpython/blob/main/Modules/Setup.config.in)?  It's going to become empty:
https://github.com/python/cpython/blob/master/Modules/Setup.config.in

**Comment by vstinner** [comment]
The PEP-11 should be updated just to mention that platforms without threading support are not supported in Python 3.7.

**Comment by vstinner** [comment]
We had a buildbot testing --without-threads, but it's gone. I just removed its unused class from the buildbot configuration:

https://github.com/python/buildmaster-config/commit/091f52aa05a8977966796ba3ef4b8257bef1c0e9

**Comment by gpshead** [comment]
I guess Setup.config.in can go.  It's only purpose was for autoconf driven Setup changes.

**Comment by vstinner** [comment]
New changeset a6a4dc816d68df04a7d592e0b6af8c7ecc4d4344 by Victor Stinner (Antoine Pitrou) in branch 'master':
bpo-31370: Remove support for threads-less builds (bpo-3385)
https://github.com/python/cpython/commit/a6a4dc816d68df04a7d592e0b6af8c7ecc4d4344

**Comment by vstinner** [comment]
PEP-11 was updated, the change was merged, this issue can now be closed. Thanks Antoine!

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
Also 'import threading' code in [Tools/scripts/run_tests.py](https://github.com/python/cpython/blob/main/Tools/scripts/run_tests.py) should be cleaned.

**Comment by 80036ac5-bb84-4d39-8416-02cd8e51707d** [comment]
[Lib/_dummy_thread.py](https://github.com/python/cpython/blob/main/Lib/_dummy_thread.py) and [Lib/dummy_threading.py](https://github.com/python/cpython/blob/main/Lib/dummy_threading.py) were deleted, but [Doc/library/_dummy_thread.rst](https://github.com/python/cpython/blob/main/Doc/library/_dummy_thread.rst) and [Doc/library/dummy_threading.rst](https://github.com/python/cpython/blob/main/Doc/library/dummy_threading.rst) still exist.

Probably [Doc/whatsnew/3.7.rst](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.7.rst) should mention that these modules were deleted.

Or maybe they should be restored and firstly deprecated, before deletion in a later version of Python.

**Comment by vstinner** [comment]
Arfrever: "[Lib/_dummy_thread.py](https://github.com/python/cpython/blob/main/Lib/_dummy_thread.py) and [Lib/dummy_threading.py](https://github.com/python/cpython/blob/main/Lib/dummy_threading.py) were deleted, but [Doc/library/_dummy_thread.rst](https://github.com/python/cpython/blob/main/Doc/library/_dummy_thread.rst) and [Doc/library/dummy_threading.rst](https://github.com/python/cpython/blob/main/Doc/library/dummy_threading.rst) still exist."

Ah, it should be deleted as well.

Arfrever: "Probably [Doc/whatsnew/3.7.rst](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.7.rst) should mention that these modules were deleted."

Right.

Arfrever: "Or maybe they should be restored and firstly deprecated, before deletion in a later version of Python."

I don't think that it's worth it, but I suggest to add a warning to Python 3.6 documentation. Something like the following warning in Python 2.7 documentation of the commands module:
"Deprecated since version 2.6: The commands module has been removed in Python 3. Use the subprocess module instead."
https://docs.python.org/2/library/commands.html

**Comment by vstinner** [comment]
Oh, Arfrever wrote me on IRC that the removal of dummy_threading broke portage on Gentoo: https://bugs.gentoo.org/630730

eventlet also uses dummy_threading:

eventlet/support/dns/entropy.py:23:    import dummy_threading as \_threading
eventlet/support/dns/resolver.py:29:    import dummy_threading as \_threading

Hum, maybe we need one release with the deprecated module, and only remove it in Python 3.8?

**Comment by tiran** [comment]
+1 to restore dummy_threading and go through a proper deprecation phase in 3.7+.

-0 to restore \_dummy_thread. It's an internal, private module.

**Comment by serhiy-storchaka** [comment]
Following lines needs updating:

[Lib/importlib/_bootstrap.py:1135](https://github.com/python/cpython/blob/main/Lib/importlib/_bootstrap.py#L1135)
[Lib/_pydecimal.py:436](https://github.com/python/cpython/blob/main/Lib/_pydecimal.py#L436)
[Lib/test/ssl_servers.py:11](https://github.com/python/cpython/blob/main/Lib/test/ssl_servers.py#L11)
[Lib/test/support/__init__.py:2053](https://github.com/python/cpython/blob/main/Lib/test/support/__init__.py#L2053)
[Lib/test/test_httplib.py:1080](https://github.com/python/cpython/blob/main/Lib/test/test_httplib.py#L1080)
[Lib/test/test_idle.py:4](https://github.com/python/cpython/blob/main/Lib/test/test_idle.py#L4)
[Lib/test/test_multiprocessing_main_handling.py:3](https://github.com/python/cpython/blob/main/Lib/test/test_multiprocessing_main_handling.py#L3)
[Lib/test/test_thread.py:5](https://github.com/python/cpython/blob/main/Lib/test/test_thread.py#L5)
[Lib/test/test_threadsignals.py:8](https://github.com/python/cpython/blob/main/Lib/test/test_threadsignals.py#L8)
[Lib/test/test_tools/test_sundry.py:43](https://github.com/python/cpython/blob/main/Lib/test/test_tools/test_sundry.py#L43)
[Lib/test/test_winreg.py:7](https://github.com/python/cpython/blob/main/Lib/test/test_winreg.py#L7)
[Lib/test/test_wsgiref.py:256](https://github.com/python/cpython/blob/main/Lib/test/test_wsgiref.py#L256)
[Lib/test/test_xmlrpc.py:1179](https://github.com/python/cpython/blob/main/Lib/test/test_xmlrpc.py#L1179)

**Comment by bitdancer** [comment]
dummy_threading should definitely not have been removed, and like all the other APIs should not be removed until 2.7 is dead.  Deprecating it is of course fine :)

**Comment by bitdancer** [comment]
And actually, I wouldn't be surprised if eventlet depended on the \*functionality* in \_dummy_threading, so you probably need to restore that, too.

**Comment by pitrou** [comment]
> eventlet also uses dummy_threading

Not sure what you mean by that.  eventlet uses the regular try/except import dance around "import threading":

https://github.com/eventlet/eventlet/blob/master/eventlet/support/dns/entropy.py#L20-L23
https://github.com/eventlet/eventlet/blob/master/eventlet/support/dns/resolver.py#L23-L26

As for portage, Arfrever fixed it :-)

https://gitweb.gentoo.org/proj/portage.git/commit/?id=504f66b0e25281e4465ebeceb799c3e54ff2b884

That said, I am not against bringing dummy_threading back, though it would sound rather weird to use it unconditionally...

**Comment by pitrou** [comment]
https://github.com/python/cpython/pull/3648 restores dummy_threading and \_dummy_thread, but deprecates them.

**Comment by pitrou** [comment]
New changeset b43c4caf81b10e5c7ebaeb3a712c6db584f60bbd by Antoine Pitrou in branch 'master':
Restore dummy_threading and \_dummy_thread, but deprecate them (bpo-31370) (bpo-3648)
https://github.com/python/cpython/commit/b43c4caf81b10e5c7ebaeb3a712c6db584f60bbd

**Comment by pitrou** [comment]
New changeset 88c60c9668f0aa732693517a60b851cc1dfce0cb by Antoine Pitrou in branch 'master':
Trivial cleanups following bpo-31370 (bpo-3649)
https://github.com/python/cpython/commit/88c60c9668f0aa732693517a60b851cc1dfce0cb
