### ISSUE TITLE
Add SSLSocket.get_verify_result()

### ISSUE THREAD

**Issue by tiran** [python/cpython#75553]
BPO | [31372](https://bugs.python.org/issue31372)
--- | :---
Nosy | @tiran, @tonybaloney
PRs | <li>python/cpython#3395</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2017-09-06.21:49:03.982>
labels = ['expert-SSL', 'type-feature', '3.8']
title = 'Add SSLSocket.get_verify_result()'
updated_at = <Date 2019-05-06.15:19:16.987>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-06.15:19:16.987>
actor = 'anthony shaw'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2017-09-06.21:49:03.982>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 31372
keywords = []
message_count = 2.0
messages = ['301526', '341525']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'anthony shaw']
pr_nums = ['3395']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31372'
versions = ['Python 3.8']
```

</p></details>

**Comment by tiran** [comment]
It might be useful to expose SSL_get_verify_result, https://wiki.openssl.org/index.php/Manual:SSL_get_verify_result(3) . The function returns the last verification error of 0 for no error. Application could still verify the chain with verify_mode = CERT_NONE.

```pycon
>>> import socket, ssl
>>> ctx = ssl.SSLContext()
>>> s = ctx.wrap_socket(socket.socket())
>>> s.connect(('www.python.org', 443))
>>> s._sslobj._sslobj.get_verify_result()
(20, 'unable to get local issuer certificate')
```

**Comment by erlend-aasland** [comment]
Closing as not-planned; see Christian's comment on the (closed) PR https://github.com/python/cpython/pull/3395#issuecomment-530456009:

> Let's not add this now.
