### ISSUE TITLE
Missing documentation for sqlite3.OperationalError

### ISSUE THREAD

**Issue by 52495ff2-50ef-47ef-817a-6fde230ca8cd** [python/cpython#75559]
BPO | [31378](https://bugs.python.org/issue31378)
--- | :---
Nosy | @berkerpeksag, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#7677</li><li>python/cpython#7678</li><li>python/cpython#7679</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-13.09:30:47.048>
created_at = <Date 2017-09-07.08:14:59.537>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Missing documentation for sqlite3.OperationalError'
updated_at = <Date 2018-06-13.09:30:47.047>
user = 'https://bugs.python.org/LeonardoTaglialegne'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-13.09:30:47.047>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-06-13.09:30:47.048>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-09-07.08:14:59.537>
creator = 'Leonardo Taglialegne'
dependencies = []
files = []
hgrepos = []
issue_num = 31378
keywords = ['patch']
message_count = 5.0
messages = ['301575', '301577', '319439', '319440', '319441']
nosy_count = 5.0
nosy_names = ['docs@python', 'berker.peksag', 'ZackerySpytz', 'Leonardo Taglialegne', 'miss-islington']
pr_nums = ['7677', '7678', '7679']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31378'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 52495ff2-50ef-47ef-817a-6fde230ca8cd** [comment]
sqlite3.OperationalError has no documentation whatsoever in docs.python.org

**Comment by berkerpeksag** [comment]
Thank you for the report. I think we can add a simplified version of the OperationalError documentation in PEP-249:

    Exception raised for errors that are related to the database's
    operation and not necessarily under the control of the programmer,
    e.g. an unexpected disconnect occurs, the data source name is not
    found, a transaction could not be processed, a memory allocation
    error occurred during processing, etc. It must be a subclass of
    DatabaseError.

Reference: https://www.python.org/dev/peps/pep-0249/#operationalerror
