### ISSUE TITLE
Unable to read the project file "pythoncore.vcxproj".

### ISSUE THREAD

**Issue by 1cb85035-97d8-42c3-a287-2706aee5fe65** [python/cpython#75562]
BPO | [31381](https://bugs.python.org/issue31381)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @denis-osipov

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-09-17.16:25:21.587>
created_at = <Date 2017-09-07.10:38:26.040>
labels = ['build', '3.7', 'OS-windows']
title = 'Unable to read the project file "pythoncore.vcxproj".'
updated_at = <Date 2017-09-17.16:25:21.586>
user = 'https://github.com/denis-osipov'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-17.16:25:21.586>
actor = 'denis-osipov'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-09-17.16:25:21.587>
closer = 'denis-osipov'
components = ['Windows']
creation = <Date 2017-09-07.10:38:26.040>
creator = 'denis-osipov'
dependencies = []
files = []
hgrepos = []
issue_num = 31381
keywords = []
message_count = 4.0
messages = ['301581', '301584', '301590', '302372']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'denis-osipov']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31381'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Can't load pythoncore.vcxproj in VS2017 after [PR 3375](https://github.com/python/cpython/pull/3375) bpo-31358: Pull zlib out of the repository bpo-3375.

During pcbuild.sln loading there is error message:

D:\\repos\\cpython\\PCbuild\\pythoncore.vcxproj : error  : Unable to read the project file "pythoncore.vcxproj".
D:\\repos\\cpython\\PCbuild\\pythoncore.vcxproj(70,37): Specified condition "$(IncludeExternals)" evaluates to "" instead of a boolean.

**Comment by zooba** [comment]
I already have a fix in a pending PR for this. Don't have the number handy, but will link it later today.

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Thank you. Looking forward to it.

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Fixed in [PR 3397](https://github.com/python/cpython/pull/3397) (I guess).
