### ISSUE TITLE
asyncio should make it easy to enable cooperative SIGINT handling

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#75568]
BPO | [31387](https://bugs.python.org/issue31387)
--- | :---
Nosy | @gpshead, @ncoghlan, @vstinner, @giampaolo, @njsmith, @1st1, @ryanhiebert, @aeros
Dependencies | <li>bpo-29988: with statements are not ensuring that __exit__ is called if __enter__ succeeds</li><li>bpo-31388: Provide a way to defer SIGINT handling in the current thread</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-07.19:37:30.590>
labels = ['3.7', 'type-bug', 'library']
title = 'asyncio should make it easy to enable cooperative SIGINT handling'
updated_at = <Date 2019-10-14.23:11:16.713>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-14.23:11:16.713>
actor = 'aeros'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-09-07.19:37:30.590>
creator = 'ncoghlan'
dependencies = ['29988', '31388']
files = []
hgrepos = []
issue_num = 31387
keywords = []
message_count = 4.0
messages = ['301619', '301631', '301661', '301669']
nosy_count = 8.0
nosy_names = ['gregory.p.smith', 'ncoghlan', 'vstinner', 'giampaolo.rodola', 'njs', 'yselivanov', 'ryanhiebert', 'aeros']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31387'
versions = ['Python 3.7']
```

</p></details>

**Comment by ncoghlan** [comment]
bpo-29988 covers the fact that with the default SIGINT handler installed, a poorly timed Ctrl-C can lead to context managers failing to even start running their \_\_(a)exit__ methods, let alone complete them.

For the asynchronous case, the problem is even worse, as the \*event loop* may be interrupted at arbitrary points if the default SIGINT handler is left in place.

To handle this robustly, it's desirable to make it easy to switch event-driven programs over to cooperative Ctrl-C handling by installing an asyncio SIGINT handler while the event loop is running, rather than leaving the default SIGINT handler in place.

(Note: while installing a cooperative SIGINT handler will enable more robust event-loop managed resource cleanup, it will have the downside that Ctrl-C won't be able to interrupt a coroutine that has incorrectly blocked the main thread)

**Comment by njsmith** [comment]
Some prior discussion on the old asyncio tracker:
    https://github.com/python/asyncio/pull/305#issuecomment-168714572
    https://github.com/python/asyncio/issues/341

**Comment by ncoghlan** [comment]
bpo-31388 is also potentially relevant here, as registering a signal handler for SIGINT isn't sufficient to cover all potential cases were Py_AddPendingCall gets called. In particular, the tests for bpo-29988 use Py_AddPendingCall to emulate Ctrl-C, rather than relying on SIGINT actually being raised.

**Comment by ncoghlan** [comment]
As per Nathaniel's comments on bpo-29988 and 31388, doing this robustly relies on:

1. the event loop being able to reliably guard itself and \_\_aexit__ method implementations against interrupts (bpo-31388)
2. "async with" statements ensuring that if the frame resumes after calling \_\_aenter__, then it will also call \_\_aexit__ (as was done for synchronous with statements in bpo-29988)
