### ISSUE TITLE
`import as` does not work when module has same same as parent module

### ISSUE THREAD

**Issue by 3fa19196-1e8a-4473-b524-6181d40d40a9** [python/cpython#75566]
BPO | [31385](https://bugs.python.org/issue31385)
--- | :---
Nosy | @brettcannon, @ncoghlan, @bitdancer, @ericsnowcurrently, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-07.22:29:22.721>
created_at = <Date 2017-09-07.19:11:59.632>
labels = ['type-bug', 'invalid']
title = '`import as` does not work when module has same same as parent module'
updated_at = <Date 2017-09-07.22:29:22.719>
user = 'https://bugs.python.org/DavidHagen'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-07.22:29:22.719>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-07.22:29:22.721>
closer = 'ncoghlan'
components = []
creation = <Date 2017-09-07.19:11:59.632>
creator = 'David Hagen'
dependencies = []
files = []
hgrepos = []
issue_num = 31385
keywords = []
message_count = 4.0
messages = ['301614', '301621', '301634', '301642']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'ncoghlan', 'r.david.murray', 'eric.snow', 'serhiy.storchaka', 'David Hagen']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31385'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 3fa19196-1e8a-4473-b524-6181d40d40a9** [comment]
Consider the following Python project:

bugtest/
  \_\_init__.py (Contents: from .foo import \*)
  foo/
    \_\_init__.py (Contents: from .foo import \*)
    foo.py (Contents: \<empty file\>)

Then in a Python session, the following line executes without error (as expected):

>\>\> import bugtest.foo.foo

However, the following line gives an error (not as expected):

```pycon
>>> import bugtest.foo.foo as bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'bugtest.foo.foo' has no attribute 'foo'
```


Note that this behavior is dependent on the folder foo and the file foo.py having the same base name. But is not dependent on actually trying to import bugtest.foo.foo. Trying to import bugtest.foo.baz will also fail as long as bugtest.foo.foo exists.

It is also dependent on the \_\_init__.py files importing something from their respective submodules.

**Comment by bitdancer** [comment]
It seems likely that this is related to the problems discussed (and hopefully solved) in bpo-30024.

**Comment by serhiy-storchaka** [comment]
In 3.7 the error is different:

```pycon
>>> import bugtest.foo.foo as bar
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'foo' from 'bugtest.foo.foo' (/home/serhiy/py/cpython/bugtest/foo/foo.py)
```


The statement "from .foo import \*" in bugtest/__init__.py imports name foo from the module bugtest.foo and rewrites the attribute foo.

```pycon
>>> import bugtest
>>> bugtest.foo
<module 'bugtest.foo.foo' from '/home/serhiy/py/cpython/bugtest/foo/foo.py'>
```


This behavior is the same in all supported Python versions.

**Comment by ncoghlan** [comment]
As Serhiy notes, this isn't a bug in the import name resolution, it's a consequence of the wildcard import in bugtest's \_\_init__.py replacing its own "bug.foo" submodule attribute with a reference to "bug.foo.foo".

If the star imports can't be avoided, then a potential workaround is to restore "bugtest.foo" from sys.modules:

```py
    foo = sys.modules[__name__ + ".foo"]
```
