### ISSUE TITLE
Issue with _posixsubprocess when importing subprocess32

### ISSUE THREAD

**Issue by 5546be57-d70f-49fb-ba81-612a1c5fbdaa** [python/cpython#75564]
BPO | [31383](https://bugs.python.org/issue31383)
--- | :---
Nosy | @gpshead, @moreati

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2017-09-07.18:05:19.020>
created_at = <Date 2017-09-07.15:07:15.355>
labels = ['build']
title = 'Issue with _posixsubprocess when importing subprocess32'
updated_at = <Date 2017-09-07.18:05:19.019>
user = 'https://bugs.python.org/paulpaulson'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-07.18:05:19.019>
actor = 'gregory.p.smith'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2017-09-07.18:05:19.020>
closer = 'gregory.p.smith'
components = ['Cross-Build']
creation = <Date 2017-09-07.15:07:15.355>
creator = 'paulpaulson'
dependencies = []
files = []
hgrepos = []
issue_num = 31383
keywords = []
message_count = 2.0
messages = ['301589', '301600']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'Alex.Willmer', 'paulpaulson']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31383'
versions = ['Python 2.7']
```

</p></details>

**Comment by 5546be57-d70f-49fb-ba81-612a1c5fbdaa** [comment]
I am trying to install subprocess32 with my python 2.7 installation via buildroot. It appeared to install correctly but when I import it on the embedded system I get an error:

```pycon
>>> import subprocess32
/usr/lib/python2.7/site-packages/subprocess32.py:472: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your pro
gram uses threads.
  "program uses threads.", RuntimeWarning)
Following this path I tried to import _posixsubprocess
```


```py
import _posixsubprocess
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dynamic module does not define init function (init_posixsubprocess)
subprocess32 seems to have it's own version and it's not working in this case?
```


I can use subprocess32 otherwise, tested out basic functionality like subprocess32.Popen(["ls"]).communicate()

**Comment by gpshead** [comment]
The standard library in Python 2.7 does not have an associated extension module.  \_posixsubprocess comes from subprocess32.

There isn't much point in using subprocess32 on POSIX systems without the \_posixsubprocess extension module.

If that import is failing, something in your build for whatever your embedded system is, is not doing the right thing.

as this is subprocess32 only related and not python stdlib subprocess related in Python 3 I suggest using the https://github.com/google/python-subprocess32/issues tracker.  But I don't have enough information to offer much help.

"ImportError: dynamic module does not define init function (init_posixsubprocess)" is very suspicious given that it does: https://github.com/google/python-subprocess32/blob/master/_posixsubprocess.c#L879
