### ISSUE TITLE
Upgrade installers to OpenSSL 1.1.0g and 1.0.2n

### ISSUE THREAD

**Issue by zooba** [python/cpython#75573]
BPO | [31392](https://bugs.python.org/issue31392)
--- | :---
Nosy | @pfmoore, @ronaldoussoren, @vstinner, @tiran, @tjguk, @ned-deily, @zware, @zooba
PRs | <li>python/cpython#3448</li><li>python/cpython#3466</li><li>python/cpython#4715</li><li>python/cpython#4716</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-14.18:45:58.413>
created_at = <Date 2017-09-08.02:52:49.065>
labels = ['OS-mac', 'expert-SSL', 'type-feature', '3.7', 'OS-windows']
title = 'Upgrade installers to OpenSSL 1.1.0g and 1.0.2n'
updated_at = <Date 2018-09-14.18:45:58.412>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-14.18:45:58.412>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-14.18:45:58.413>
closer = 'ned.deily'
components = ['macOS', 'Windows', 'SSL']
creation = <Date 2017-09-08.02:52:49.065>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 31392
keywords = ['patch']
message_count = 12.0
messages = ['301673', '301744', '301770', '301776', '302160', '302161', '307519', '307627', '307633', '307635', '307917', '325383']
nosy_count = 8.0
nosy_names = ['paul.moore', 'ronaldoussoren', 'vstinner', 'christian.heimes', 'tim.golden', 'ned.deily', 'zach.ware', 'steve.dower']
pr_nums = ['3448', '3466', '4715', '4716']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31392'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zooba** [comment]
As per usual

**Comment by tiran** [comment]
New changeset e6eb48c10dc389d1d70657593de6a6cb3087d3d1 by Christian Heimes (Steve Dower) in branch 'master':
bpo-31400: Improve SSL error handling on Windows (bpo-3463)
https://github.com/python/cpython/commit/e6eb48c10dc389d1d70657593de6a6cb3087d3d1

**Comment by zooba** [comment]
New changeset b84bcc48ae31c385fe480c08c05d95212ef7fcdc by Steve Dower in branch 'master':
bpo-31392: Update SSL build for 1.1.0 (bpo-3448)
https://github.com/python/cpython/commit/b84bcc48ae31c385fe480c08c05d95212ef7fcdc

**Comment by tiran** [comment]
New changeset 16f16dbd0ed02cd1a7b270eb6dd80d9bd179902e by Christian Heimes in branch '3.6':
[3.6] bpo-31400: Improve SSL error handling on Windows (GH-3463) (bpo-3466)
https://github.com/python/cpython/commit/16f16dbd0ed02cd1a7b270eb6dd80d9bd179902e

**Comment by tiran** [comment]
Ned, can you take care of macOS? Victor noted that master still builds with 1.0.2k.

**Comment by vstinner** [comment]
FYI I wrote a script to get the version of all library copies embedded in CPython:
https://github.com/haypo/misc/blob/master/cpython/external_versions.py

This is how I noticed the OpenSSL version inconsistency.
