### ISSUE TITLE
TypeError: gdbm key must be string, not unicode

### ISSUE THREAD

**Issue by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [python/cpython#75579]
BPO | [31398](https://bugs.python.org/issue31398)
--- | :---
Nosy | @vstinner, @ezio-melotti, @bitdancer, @serhiy-storchaka, @sam-s, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-06-18.16:23:29.812>
created_at = <Date 2017-09-08.20:54:57.304>
labels = ['type-bug', 'expert-unicode']
title = 'TypeError: gdbm key must be string, not unicode'
updated_at = <Date 2021-06-18.16:23:29.811>
user = 'https://github.com/sam-s'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-18.16:23:29.811>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-06-18.16:23:29.812>
closer = 'iritkatriel'
components = ['Unicode']
creation = <Date 2017-09-08.20:54:57.304>
creator = 'sam-s'
dependencies = []
files = []
hgrepos = []
issue_num = 31398
keywords = []
message_count = 7.0
messages = ['301728', '301729', '301730', '301781', '301788', '396072', '396074']
nosy_count = 6.0
nosy_names = ['vstinner', 'ezio.melotti', 'r.david.murray', 'serhiy.storchaka', 'sam-s', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31398'
versions = ['Python 2.7']
```

</p></details>

**Comment by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [comment]
`in` and `has_key` have different behavior for Unicode keys for `gdbm` in 2.7:
```
>>> import gdbm
>>> db = gdbm.open("foo.gdbm","c")
>>> db.has_key("a")
0
>>> db.has_key(u"a")
0
>>> "a" in db
False
>>> u"a" in db
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: gdbm key must be string, not unicode
```

**Comment by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [comment]
platform:
Python 2.7.13 (default, Jul 18 2017, 09:17:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin

**Comment by 8d330395-585a-4724-9ff6-e8027e2dd7d5** [comment]
the problem is not present in 
Python 3.6.2 (default, Jul 17 2017, 16:44:45):
```
>>> import dbm
>>> import dbm.gnu
>>> db = dbm.gnu.open("foo","c")
>>> "a" in db
False
>>> u"a" in db
False
```

**Comment by bitdancer** [comment]
In python3, u"a" and "a" are the same thing.  The equivalent in python3 would bee b"a" vs "a", but I have no idea if we even support bytes keys in python3 gdbm.

In 2.7 does has_key(u"x") work if x is a valid key?

**Comment by serhiy-storchaka** [comment]
has_key(u"x") works if x is a valid key.

has_key() parses the argument with PyArg_ParseTuple("s#") which implicitly converts unicode to str. \_\_contains__() explicitly checks for str type.
