### ISSUE TITLE
pydoc.Helper.keywords missing async and await

### ISSUE THREAD

**Issue by 520aaf02-3cd5-4f31-aafa-feeeba6679cf** [python/cpython#75571]
BPO | [31390](https://bugs.python.org/issue31390)
--- | :---
Nosy | @berkerpeksag, @rswgnu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-01.07:51:22.018>
created_at = <Date 2017-09-08.00:34:00.084>
labels = ['type-bug', 'docs']
title = 'pydoc.Helper.keywords missing async and await'
updated_at = <Date 2017-11-01.07:51:22.016>
user = 'https://github.com/rswgnu'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-01.07:51:22.016>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-01.07:51:22.018>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-09-08.00:34:00.084>
creator = 'rsw'
dependencies = []
files = []
hgrepos = []
issue_num = 31390
keywords = []
message_count = 2.0
messages = ['301657', '305360']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'rsw']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31390'
versions = ['Python 3.6']
```

</p></details>

**Comment by 520aaf02-3cd5-4f31-aafa-feeeba6679cf** [comment]
Shouldn't async and await be added to the pydoc keywords list?

**Comment by berkerpeksag** [comment]
Thank you for your report. Prior to Python 3.7, async and await keywords have had special meanings and they weren't treated as normal keywords. They are now in Python 3.7:

```pycon
>>> async = 42
  File "<stdin>", line 1
    async = 42
          ^
SyntaxError: invalid syntax
```


And they are listed as keywords:

```sh
$ ./python -m pydoc keywords
```


Here is a list of the Python keywords.  Enter any keyword to get more help.

False               class               from                or
None                continue            global              pass
True                def                 if                  raise
and                 del                 import              return
as                  elif                in                  try
assert              else                is                  while
async               except              lambda              with
await               finally             nonlocal            yield
break               for                 not                 

So I don't think we should modify pydoc to list them as keywords in Python 3.6.
