### ISSUE TITLE
Docs Downloads are 404s

### ISSUE THREAD

**Issue by 31ec7cc3-49c0-419a-97ef-c96df8ce8930** [python/cpython#75576]
BPO | [31395](https://bugs.python.org/issue31395)
--- | :---
Nosy | @ned-deily, @n8henrie

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.17:10:01.398>
created_at = <Date 2017-09-08.14:33:40.444>
labels = ['docs']
title = 'Docs Downloads are 404s'
updated_at = <Date 2017-09-12.17:10:01.397>
user = 'https://github.com/n8henrie'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.17:10:01.397>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-12.17:10:01.398>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-09-08.14:33:40.444>
creator = 'n8henrie'
dependencies = []
files = []
hgrepos = []
issue_num = 31395
keywords = []
message_count = 2.0
messages = ['301699', '301978']
nosy_count = 3.0
nosy_names = ['ned.deily', 'docs@python', 'n8henrie']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31395'
versions = []
```

</p></details>

**Comment by 31ec7cc3-49c0-419a-97ef-c96df8ce8930** [comment]
Please see my (closed) issue, I was told to resubmit here. https://github.com/python/pythondotorg/issues/1140

Basically, I usually download a local copy of the epub and HTML docs so I can reference offline (and faster using the "custom search engine" feature of several modern browsers). Tried to download 3.6.2 and noticed I was getting a 404: https://docs.python.org/3/archives/python-3.6.2-docs-html.zip

Testing the other links on the page, looks like most are down:

```shell_session
$ curl -s https://docs.python.org/3/download.html | grep -o '"archives/.*"' | xargs -I{} bash -c 'echo; url="https://docs.python.org/3/{}"; echo "${url}"; c
url -s -I "${url}" | head -n 1'

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-letter.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-letter.tar.bz2
HTTP/1.1 200 OK

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-a4.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-pdf-a4.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-html.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-html.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-text.zip
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs-text.tar.bz2
HTTP/1.1 404 Not Found

https://docs.python.org/3/archives/python-3.6.2-docs.epub
HTTP/1.1 404 Not Found
```

I looked to see if this was an existing issue, sorry if it's a duplicate.

**Comment by ned-deily** [comment]
Thanks for the report.  After looking into this a bit, the URLs you are using are those from the daily docs build, the latest doc changes checked into each branch.  As best I can tell, the part of the daily build that makes the downloadable files has been broken, probably for some time and most likely due to trying to use an older version of TeX Live.  Until we can get the server upgraded, you can download the docs that reflect the source as of the 3.6.2 release.  You can find these linked to on the docs download page:

https://www.python.org/doc/versions/

I've reopened the original pythondotorg issue since it turns out to be a server issue.
