### ISSUE TITLE
Ellipsis_token.type != token.ELLIPSIS

### ISSUE THREAD

**Issue by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [python/cpython#75575]
BPO | [31394](https://bugs.python.org/issue31394)
--- | :---
Nosy | @terryjreedy, @berkerpeksag, @aivarannamaa, @Mariatta
PRs | <li>python/cpython#3469</li><li>python/cpython#3525</li><li>python/cpython#3526</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-13.04:04:26.579>
created_at = <Date 2017-09-08.09:24:31.636>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Ellipsis_token.type != token.ELLIPSIS'
updated_at = <Date 2017-09-13.04:04:26.578>
user = 'https://github.com/aivarannamaa'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-13.04:04:26.578>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-13.04:04:26.579>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-09-08.09:24:31.636>
creator = 'Aivar.Annamaa'
dependencies = []
files = []
hgrepos = []
issue_num = 31394
keywords = ['patch', 'easy']
message_count = 14.0
messages = ['301687', '301688', '301689', '301691', '301694', '301697', '301707', '301713', '301725', '301765', '301777', '302028', '302029', '302030']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'docs@python', 'berker.peksag', 'Aivar.Annamaa', 'Mariatta']
pr_nums = ['3469', '3525', '3526']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31394'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [comment]
Type code for ellipsis token doesn't match with the constant token.ELLIPSIS:
\---------------------------------------
```py
import io
import token
import tokenize
```


source = "..."

```py
tokens = list(tokenize.tokenize(io.BytesIO(source.encode('utf-8')).readline))
ellipsis = tokens[1]

print(ellipsis)
print(token.ELLIPSIS) 
```

-----------------------------------------

This code outputs following in Python 3.5 and 3.6:

> TokenInfo(type=53 (OP), string='...', start=(1, 0), end=(1, 3), line='...')
> 52

and following in Python 3.4

> TokenInfo(type=52 (OP), string='...', start=(1, 0), end=(1, 3), line='...')
> 51

**Comment by berkerpeksag** [comment]
Thank you for the report, but this behavior is already documented at https://docs.python.org/3/library/tokenize.html

    To simplify token stream handling, all Operators and Delimiters
    tokens are returned using the generic token.OP token type. The
    exact type can be determined by checking the exact_type property
    on the named tuple returned from tokenize.tokenize().

If you replace the following line

```py
    print(ellipsis)
```


with

```py
    print(ellipsis.exact_type)
```


you will see that it prints '52'.

**Comment by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [comment]
But it looks like Ellipsis is neither operator nor delimiter: https://docs.python.org/3/reference/lexical_analysis.html#operators

**Comment by berkerpeksag** [comment]
If you look at https://docs.python.org/3/reference/lexical_analysis.html#delimiters '.' (period) is listed as delimiter and there is the following sentence to answer your question:

    A sequence of three periods has a special meaning as an ellipsis literal.

**Comment by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [comment]
But ellipsis is a distinct token, not a sequence of three period tokens.

Also, I can't see how we could conceptually treat ellipsis as a delimiter or operator -- it's a literal.

I still think either documentation or implementation needs to be fixed here.

**Comment by berkerpeksag** [comment]
Please don't reopen an issue if it was closed by a core developer.

It's not clear to me what exactly do you want to change in the implementation or documentation.

     A sequence of three periods has a special meaning as an ellipsis literal.

is literally describes how the ELLIPSIS token is identified in [Parser/tokenizer.c](https://github.com/python/cpython/blob/main/Parser/tokenizer.c) (see PyToken_ThreeChars in that file) So a sequence of three periods is identified as an ellipsis literal which is an expression in Python.

Do you want to change tokenize.tokenize() (it's in [Lib/tokenize.py](https://github.com/python/cpython/blob/main/Lib/tokenize.py)) so it will return

    TokenInfo(type=52 (ELLIPSIS), ...)

instead of

    TokenInfo(type=53 (OP), ...)

? Note that ELLIPSIS has been added to tokenize.EXACT_TOKEN_TYPES in bpo-24622. To me, since it has been added to tokenize.EXACT_TOKEN_TYPES there is no need to special case ELLIPSIS in [Lib/tokenize.py](https://github.com/python/cpython/blob/main/Lib/tokenize.py).

Or do you want to clarify

    To simplify token stream handling, all Operators and Delimiters tokens are returned using the generic token.OP token type.

at https://docs.python.org/3/library/tokenize.html?

**Comment by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [comment]
(Sorry, I didn't mean to challenge the authority of a core developer. I simply didn't notice that adding a comment reopens the issue. I hope this time I selected correct parameters and this doesn't happen again)

I'm trying to rephrase my concern. 

Initially I thought there was a mistake in the tokenizer or in the token module.

After you pointed out the documentation about token.OP and exact_type, I'm worried about a smaller detail. The documentation only talks about \*operators* and \*delimiters* having type attribute set to token.OP. According to my understanding (and also the listings at https://docs.python.org/3/reference/lexical_analysis.html#operators), ellipsis is neither operator nor delimiter. 

Am I right about this? 

(I understand that the source representation of both ELLIPSIS and DOT tokens contains period \*character(s)*, but I don't see why is this relevant when we discuss the properties of \*tokens*)

Anyway, if ellipsis is neither operator nor delimiter, (and if there is a reason why it is treated similarly with operators and delimiters) then I recommend to update the documentation by replacing 

> all Operators and Delimiters tokens 
> are returned using the generic token.OP token type

with 

> all Operators, Delimiters and Ellipsis tokens
> are returned using the generic token.OP token type


(I understand, that this is not a serious issue. If you prefer not to discuss it further then I'm happy to leave it as it is.)

**Comment by terryjreedy** [comment]
I think we should add 'and Ellipsis' in the tokenize doc to get
'all Operators and Delimiters tokens and Ellipsis are returned ...'.  I would actually prefer 'Operator and Delimiter tokens' but I don't know if the 's' is needed to trigger the current linkage.

**Comment by berkerpeksag** [comment]
Thank you for your detailed response, Aivar. I agree that adding 'and Ellipsis' would make the tokenize documentation clearer. Would you like to send a pull request?

**Comment by 00cb8ee4-8477-4cf2-a23b-96ae6c49efd3** [comment]
Here is the PR: https://github.com/python/cpython/pull/3469

(It's my first, so I don't know if I should to also update NEWS file or add "skip news" label. I signed the CLA, so I hope this warning goes away.)

**Comment by terryjreedy** [comment]
Once the CLA * shows up after your name, one of us should remove CLA needed tag and bot will verify.  I believe tagging as trivial would also work.

**Comment by Mariatta** [comment]
New changeset 5f8fbf917ebf2398aa75a1f271617e2e50ab7c88 by Mariatta (Aivar Annamaa) in branch 'master':
bpo-31394: Clarify documentation about token type attribute (GH-3469)
https://github.com/python/cpython/commit/5f8fbf917ebf2398aa75a1f271617e2e50ab7c88

**Comment by Mariatta** [comment]
New changeset 5513e888e9a742156c35ce7ab628407d8cf9e1f0 by Mariatta in branch '3.6':
[3.6] bpo-31394: Clarify documentation about token type attribute (GH-3469) (GH-3525)
https://github.com/python/cpython/commit/5513e888e9a742156c35ce7ab628407d8cf9e1f0

**Comment by Mariatta** [comment]
New changeset ea0f7c26cef4550bf4db1a9bae17d41b79ab7c0d by Mariatta in branch 'master':
bpo-31394: Make tokenize.rst PEP-8-compliant (GH-3526)
https://github.com/python/cpython/commit/ea0f7c26cef4550bf4db1a9bae17d41b79ab7c0d
