### ISSUE TITLE
--without-pymalloc broken

### ISSUE THREAD

**Issue by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [python/cpython#75588]
BPO | [31407](https://bugs.python.org/issue31407)
--- | :---
Nosy | @skrah, @ericsnowcurrently
PRs | <li>python/cpython#3507</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericsnowcurrently'
closed_at = <Date 2017-09-12.00:02:52.705>
created_at = <Date 2017-09-10.15:36:36.750>
labels = ['build']
title = '--without-pymalloc broken'
updated_at = <Date 2017-09-12.00:02:52.704>
user = 'https://github.com/skrah'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.00:02:52.704>
actor = 'eric.snow'
assignee = 'eric.snow'
closed = True
closed_date = <Date 2017-09-12.00:02:52.705>
closer = 'eric.snow'
components = ['Build']
creation = <Date 2017-09-10.15:36:36.750>
creator = 'skrah'
dependencies = []
files = []
hgrepos = []
issue_num = 31407
keywords = ['patch']
message_count = 4.0
messages = ['301810', '301924', '301925', '301928']
nosy_count = 2.0
nosy_names = ['skrah', 'eric.snow']
pr_nums = ['3507']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31407'
versions = []
```

</p></details>

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
./configure --without-pymalloc produces:

[Objects/obmalloc.c](https://github.com/python/cpython/blob/main/Objects/obmalloc.c): In function ‘bumpserialno’:
[Objects/obmalloc.c:1326](https://github.com/python/cpython/blob/main/Objects/obmalloc.c#L1326):21: error: ‘struct \_pymem_runtime_state’ has no member named ‘serialno’
     ++_PyRuntime.mem.serialno;
                     ^
[Objects/obmalloc.c](https://github.com/python/cpython/blob/main/Objects/obmalloc.c): In function ‘_PyMem_DebugRawAlloc’:
[Objects/obmalloc.c:1417](https://github.com/python/cpython/blob/main/Objects/obmalloc.c#L1417):44: error: ‘struct \_pymem_runtime_state’ has no member named ‘serialno’
     write_size_t(tail + SST, \_PyRuntime.mem.serialno);
                                            ^
[Objects/obmalloc.c](https://github.com/python/cpython/blob/main/Objects/obmalloc.c): In function ‘_PyMem_DebugRawRealloc’:
[Objects/obmalloc.c:1502](https://github.com/python/cpython/blob/main/Objects/obmalloc.c#L1502):44: error: ‘struct \_pymem_runtime_state’ has no member named ‘serialno’
     write_size_t(tail + SST, \_PyRuntime.mem.serialno);
                                            ^

**Comment by ericsnowcurrently** [comment]
I'm looking into this.

**Comment by ericsnowcurrently** [comment]
I've verified that the PR fixes the problem.

**Comment by ericsnowcurrently** [comment]
New changeset ba6d5d1defd7a281c8c8804e4b4cfd7370886236 by Eric Snow in branch 'master':
bpo-30860: Always provide serialno. (bpo-3507)
https://github.com/python/cpython/commit/ba6d5d1defd7a281c8c8804e4b4cfd7370886236
