### ISSUE TITLE
Dynamic compilation that uses function in comprehension fails when compiled inside function

### ISSUE THREAD

**Issue by 8dcc9775-b0db-4de9-b052-1f058aea0103** [python/cpython#75582]
BPO | [31401](https://bugs.python.org/issue31401)
--- | :---
Nosy | @bitdancer, @vedgar, @josepablocam
Files | <li>[reproduce.zip](https://bugs.python.org/file47127/reproduce.zip "Uploaded as application/zip at 2017-09-08.21:19:38 by @josepablocam"): Zip file contaIning three python programs to reproduce error</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.13:51:35.357>
created_at = <Date 2017-09-08.21:19:38.914>
labels = ['type-bug', 'invalid']
title = 'Dynamic compilation that uses function in comprehension fails when compiled inside function'
updated_at = <Date 2017-09-12.13:51:35.355>
user = 'https://github.com/josepablocam'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.13:51:35.355>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.13:51:35.357>
closer = 'r.david.murray'
components = []
creation = <Date 2017-09-08.21:19:38.914>
creator = 'jpc'
dependencies = []
files = ['47127']
hgrepos = []
issue_num = 31401
keywords = []
message_count = 7.0
messages = ['301734', '301784', '301790', '301794', '301795', '301938', '301961']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'veky', 'jpc']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31401'
versions = ['Python 3.6']
```

</p></details>

**Comment by 8dcc9775-b0db-4de9-b052-1f058aea0103** [comment]
Execution fails with NameError when trying to dynamically compile a Python program that uses a function in a comprehension, and the code is compiled inside a function call, rather than as a global statement.

Using the attached files to reproduce (in reproduce.zip):

python3 compile_in_function.py comprehension.py #fails
python3 compile_global.py comprehension.py # works
python2 compile_in_function.py comprehension.py #works with Python 2.7.12

**Comment by bitdancer** [comment]
Could you please post the examples instead of a zip file?  Zip files are hard to read on a mobile browser :)

**Comment by 8dcc9775-b0db-4de9-b052-1f058aea0103** [comment]
Woops, sorry about that, makes sense. Below an example (same idea as the files):

```
Python 3.6.2 (default, Sep  9 2017, 13:27:06) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> src = """
... def f(x): return x
... [f(v) for v in [1,2,3]]
... """
>>> def comp():
...     exec(compile(src, filename='<str>', mode='exec'))
... 
>>> comp()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 2, in comp
  File "<str>", line 3, in <module>
  File "<str>", line 3, in <listcomp>
NameError: name 'f' is not defined
>>> exec(compile(src, filename='<str>', mode='exec'))
>>> 
```

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
List comprehension is irrelevant here, any nested function has the same problem. And the inner name doesn't have to refer to a function. Also, compilation as a separate step is not necessary.

So the minimal example is

```py
    src = '''\
    a = 5
    def g(x): return a + x
    print(g(3))
    '''
    def comp(): exec(src)
    comp()
```


But I'm not sure if it is a bug at all. If you write explicitly

```py
    exec(src, {})
```


you get a result 8 without problem. The docs say

    ...if the optional parts are omitted, the code is executed in the current scope.

And the current scope inside comp is "fast locals", where you can't really make new names. Maybe exec should raise an exception then, but it surely cannot just "work" inside fast locals scope.

**Comment by bitdancer** [comment]
This is indeed not a bug, it it a consequence of the scoping rules.

What surprises me is that it works without passing in an explicit scope in in 3.7.  I'm not sure what we changed that makes that true.

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
Hm... then it \_is_ a bug (in 3.7). Or we have "fast locals and slow locals" nightmare again... :-/

I don't have 3.7 to test... what do you mean is working? jpc's example or mine?

**Comment by bitdancer** [comment]
Hmm.  I must have made a mistake when I ran (jpc's) test on 3.7.  It is failing with the NameError for me when I try it again.
