### ISSUE TITLE
crashes when comparing between a Decimal object and a bad Rational object

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75587]
BPO | [31406](https://bugs.python.org/issue31406)
--- | :---
Nosy | @skrah, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3476</li><li>python/cpython#3477</li><li>python/cpython#3479</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-10.17:07:20.713>
created_at = <Date 2017-09-10.13:25:42.551>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'crashes when comparing between a Decimal object and a bad Rational object'
updated_at = <Date 2017-09-10.17:07:20.712>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-10.17:07:20.712>
actor = 'skrah'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-10.17:07:20.713>
closer = 'skrah'
components = ['Extension Modules']
creation = <Date 2017-09-10.13:25:42.551>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31406
keywords = ['patch']
message_count = 4.0
messages = ['301809', '301813', '301815', '301817']
nosy_count = 3.0
nosy_names = ['skrah', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3476', '3477', '3479']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31406'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code crashes the interpreter:

```py
import decimal
import fractions

class BadRational(fractions.Fraction):
    numerator = None
    denominator = 42
```


decimal.Decimal() \< BadRational()


this is because numerator_as_decimal() (in [Modules/_decimal/_decimal.c](https://github.com/python/cpython/blob/main/Modules/_decimal/_decimal.c)) assumes
that 'numerator' is an integer.

multiply_by_denominator() (in [Modules/_decimal/_decimal.c](https://github.com/python/cpython/blob/main/Modules/_decimal/_decimal.c)) also assumes that
'denominator' is an integer, and so the following code crashes the interpreter:

```py
import decimal
import fractions

class BadRational(fractions.Fraction):
    numerator = 42
    denominator = None
```


decimal.Decimal() \< BadRational()

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
New changeset 3cedf46cdbeefc019f4a672c1104f3d5e94712bd by Stefan Krah in branch 'master':
bpo-31406: Fix crash due to lack of type checking in subclassing. (bpo-3477)
https://github.com/python/cpython/commit/3cedf46cdbeefc019f4a672c1104f3d5e94712bd

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
New changeset f8909d0e4b652256e4da153fa6be664490f60a07 by Stefan Krah (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31406: Fix crash due to lack of type checking in subclassing. (GH-3477) (bpo-3479)
https://github.com/python/cpython/commit/f8909d0e4b652256e4da153fa6be664490f60a07

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Thanks for the report and the patch!
