### ISSUE TITLE
Python won't load on Acer Aspire

### ISSUE THREAD

**Issue by a0a5b48d-77d6-4d07-a4da-1d5cc5bea095** [python/cpython#75583]
BPO | [31402](https://bugs.python.org/issue31402)
--- | :---
Nosy | @terryjreedy, @Chikimonki

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-09.16:17:34.736>
created_at = <Date 2017-09-09.11:04:11.512>
labels = ['invalid', 'expert-installation', 'type-crash']
title = "Python won't load on Acer Aspire"
updated_at = <Date 2017-09-09.16:17:34.733>
user = 'https://github.com/Chikimonki'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-09.16:17:34.733>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-09.16:17:34.736>
closer = 'terry.reedy'
components = ['Installation']
creation = <Date 2017-09-09.11:04:11.512>
creator = 'Chikimonki'
dependencies = []
files = []
hgrepos = []
issue_num = 31402
keywords = []
message_count = 2.0
messages = ['301766', '301778']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'Chikimonki']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31402'
versions = ['Python 3.6']
```

</p></details>

**Comment by a0a5b48d-77d6-4d07-a4da-1d5cc5bea095** [comment]
Well I'm reading Al Sweigarts Automate the boring stuff, downloaded the exe for Python 3.6, and got the right 32-bit one, then nothing happens when I run it. It just does nothing. I do have it set up perfectly well on another computer, but it won't budge on this one. It's an Acer Aspire 32-bit 2.00Gb Ram notebook.
 Next I got a message from google telling me I have a problem signing in for my email, gmail, and need to clear all my cookies.

**Comment by terryjreedy** [comment]
Please ask for installation help on python-list.  It can also be accessed via news.gmane.org. Give following details: OS, including version; source of installer; how you tried to install; what error message you got.

If you have Windows XP, 3.6 will not install.  If Vista+, and you need to install .dll, do so.  Search or ask.
