### ISSUE TITLE
assertion failures in warn_explicit() in case of a bad warnings.filters or warnings.defaultaction

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75597]
BPO | [31416](https://bugs.python.org/issue31416)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3496</li><li>python/cpython#3509</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.06:48:53.490>
created_at = <Date 2017-09-11.07:52:58.758>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failures in warn_explicit() in case of a bad warnings.filters or warnings.defaultaction'
updated_at = <Date 2017-09-12.06:48:53.489>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.06:48:53.489>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.06:48:53.490>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-11.07:52:58.758>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31416
keywords = ['patch']
message_count = 3.0
messages = ['301867', '301903', '301940']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3496', '3509']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31416'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure in warn_explicit() (in
[Python/_warnings.c](https://github.com/python/cpython/blob/main/Python/_warnings.c)):

```py
import warnings
warnings.filters = [(None, None, Warning, None, 0)]
warnings.warn_explicit(message='foo', category=Warning, filename='bar',
                       lineno=1)
```


this is because warn_explicit() assumes that get_filter() returned a string,
and passes the return value (of get_filter()) to \_PyUnicode_EqualToASCIIString(),
which asserts it received a string.


In addition, get_filter() might return warnings.defaultaction, and so the
following code also causes an assertion failure in warn_explicit():

```py
import warnings
warnings.defaultaction = None
warnings.filters = []
warnings.warn_explicit(message='foo', category=Warning, filename='bar',
                       lineno=1)
```

**Comment by serhiy-storchaka** [comment]
New changeset 9d984fd2b097c8c29479d1c3eb740995fe1ccb0d by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31416: Fix assertion failures in case of a bad warnings.filters or warnings.defaultaction. (bpo-3496)
https://github.com/python/cpython/commit/9d984fd2b097c8c29479d1c3eb740995fe1ccb0d

**Comment by serhiy-storchaka** [comment]
New changeset 9adc87b0f82e5169c5f44739f89212a86013d1c4 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31416: Fix assertion failures in case of a bad warnings.filters or warnings.defaultaction. (GH-3496) (bpo-3509)
https://github.com/python/cpython/commit/9adc87b0f82e5169c5f44739f89212a86013d1c4
