### ISSUE TITLE
SystemError raised by warn_explicit() in case warnings.onceregistry is not a dict

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75592]
BPO | [31411](https://bugs.python.org/issue31411)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3485</li><li>python/cpython#3493</li><li>python/cpython#3494</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-11.07:07:50.728>
created_at = <Date 2017-09-10.17:37:43.544>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'SystemError raised by warn_explicit() in case warnings.onceregistry is not a dict'
updated_at = <Date 2017-09-11.07:07:50.727>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-11.07:07:50.727>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-11.07:07:50.728>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-10.17:37:43.544>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31411
keywords = ['patch']
message_count = 4.0
messages = ['301822', '301862', '301865', '301866']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3485', '3493', '3494']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31411'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes warn_explicit() (in [Python/_warnings.c](https://github.com/python/cpython/blob/main/Python/_warnings.c)) to raise a
SystemError:

```py
import warnings
warnings.filterwarnings('once')
warnings.onceregistry = None
warnings.warn_explicit(message='foo', category=Warning, filename='bar',
                       lineno=1, registry=None)
```



this is because warn_explicit() assumes that warnings.onceregistry is a dict,
and passes it to update_registry(), which passes it to already_warned(), which
eventually passes it to \_PyDict_SetItemId(), which raises the SystemError.

**Comment by serhiy-storchaka** [comment]
New changeset 252033d50effa08046ac34fcc406bc99796ab88b by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31411: Prevent raising a SystemError in case warnings.onceregistry is not a dictionary. (bpo-3485)
https://github.com/python/cpython/commit/252033d50effa08046ac34fcc406bc99796ab88b

**Comment by serhiy-storchaka** [comment]
New changeset 004547f97067be2e23ae770f300c0c0d1db1ba27 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31411: Prevent raising a SystemError in case warnings.onceregistry is not a dictionary. (GH-3485). (bpo-3493)
https://github.com/python/cpython/commit/004547f97067be2e23ae770f300c0c0d1db1ba27

**Comment by serhiy-storchaka** [comment]
New changeset 7972ed2111ea2f01e8712eef91bcf2260e05ad8b by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31411: Prevent raising a SystemError in case warnings.onceregistry is not a dictionary. (GH-3485). (bpo-3494)
https://github.com/python/cpython/commit/7972ed2111ea2f01e8712eef91bcf2260e05ad8b
