### ISSUE TITLE
int.__repr__() is slower than repr()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75591]
BPO | [31410](https://bugs.python.org/issue31410)
--- | :---
Nosy | @vstinner, @methane, @serhiy-storchaka
PRs | <li>python/cpython#3481</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-21.12:05:31.980>
created_at = <Date 2017-09-10.17:34:20.389>
labels = ['interpreter-core', '3.7', 'performance']
title = 'int.__repr__() is slower than repr()'
updated_at = <Date 2017-09-21.12:14:11.657>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-21.12:14:11.657>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-21.12:05:31.980>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-09-10.17:34:20.389>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31410
keywords = ['patch']
message_count = 3.0
messages = ['301821', '302685', '302688']
nosy_count = 3.0
nosy_names = ['vstinner', 'methane', 'serhiy.storchaka']
pr_nums = ['3481']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31410'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Following the StackOverflow question [1].

Calling repr() is faster than calling unbound method \_\_repr__(). This looks strange at first glance because it is \*obvious* that repr() is implemented via calling \_\_repr__().

```sh
$ ./python -m timeit "''.join(map(repr, range(10000)))"
500 loops, best of 5: 809 usec per loop

$ ./python -m timeit "''.join(map(int.__repr__, range(10000)))"
200 loops, best of 5: 1.27 msec per loop
```


Actually repr() just called the tp_repr slot, while calling int.\_\_repr__ passes through many intermediate layers.

Proposed PR gets rid of a half of the overhead. It avoids creating and calling an itermediate function object. The result still is slower then calling repr().

```sh
$ ./python -m timeit "''.join(map(int.__repr__, range(10000)))"
200 loops, best of 5: 1.01 msec per loop
```



The PR also speeds up calling classmethod descriptors.

```sh
$ ./python -m timeit -s "cm = bytes.fromhex; args = [('',)]*10000; from itertools import starmap" -- "b''.join(starmap(cm, args))"
500 loops, best of 5: 515 usec per loop


$ ./python -m timeit -s "cm = bytes.__dict__['fromhex']; args = [(bytes, '')]*10000; from itertools import starmap" -- "b''.join(starmap(cm, args))"
500 loops, best of 5: 704 usec per loop
```


Patched:

```sh
$ ./python -m timeit -s "cm = bytes.__dict__['fromhex']; args = [(bytes, '')]*10000; from itertools import starmap" -- "b''.join(starmap(cm, args))"
500 loops, best of 5: 598 usec per loop
```



[1] https://stackoverflow.com/questions/45376719/why-is-reprint-faster-than-strint

**Comment by serhiy-storchaka** [comment]
New changeset 5e02c7826f9797fb3add79b608ef51f7a62b3e5a by Serhiy Storchaka in branch 'master':
bpo-31410: Optimized calling wrapper and classmethod descriptors. (bpo-3481)
https://github.com/python/cpython/commit/5e02c7826f9797fb3add79b608ef51f7a62b3e5a

**Comment by vstinner** [comment]
Oh, nice optimization!

I see that you reused the \_PyMethodDef_RawFastCallDict() function that I added exactly for the same reason: prevent the creation of a temporary C function only created for a single call and then destroyed.
