### ISSUE TITLE
assertion failure in PyErr_WriteUnraisable() in case of an exception with a bad __module__

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75599]
BPO | [31418](https://bugs.python.org/issue31418)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3539</li><li>python/cpython#3556</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-14.06:42:14.343>
created_at = <Date 2017-09-11.12:49:19.794>
labels = ['interpreter-core', '3.7', 'type-crash']
title = 'assertion failure in PyErr_WriteUnraisable() in case of an exception with a bad __module__'
updated_at = <Date 2017-09-14.06:42:14.342>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-14.06:42:14.342>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-14.06:42:14.343>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-09-11.12:49:19.794>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31418
keywords = ['patch']
message_count = 7.0
messages = ['301872', '301873', '301874', '302042', '302047', '302126', '302145']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3539', '3556']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31418'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure in PyErr_WriteUnraisable() (in
[Python/errors.c](https://github.com/python/cpython/blob/main/Python/errors.c)):

```py
class BadException(Exception):
    __module__ = None

class BadClass:
    def __del__(self):
        raise BadException

foo = BadClass()
del foo
```



this is because PyErr_WriteUnraisable() assumes that \_\_module__ is a string,
and passes it to \_PyUnicode_EqualToASCIIId(), which asserts it received a string.


what is the wanted behavior in such a case?
should we ignore the bad \_\_module__ and print '\<unknown\>' as the module name
in the traceback?

**Comment by serhiy-storchaka** [comment]
Printing '\<unknown\>' LGTM.

Implicit converting to str can raise a warning or exception if \_\_module__ is a bytes object.

**Comment by serhiy-storchaka** [comment]
I think this patch doesn't need a test (which would require using a subprocess).

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
what do you mean by 'Implicit converting to str can raise a warning or exception if \_\_module__ is a bytes object.'?

should we treat \_\_module__ differently in case it is a bytes object?

**Comment by serhiy-storchaka** [comment]
PyFile_WriteObject(moduleName, f, Py_PRINT_RAW) implicitly converts its argument to string. I mean that treating non-string moduleName the same way as string moduleName not equal to string "builtins" and calling PyFile_WriteObject() would cause other problem. Treating non-string moduleName the same way as moduleName==NULL LGTM.

**Comment by serhiy-storchaka** [comment]
New changeset f6e61df01536493f1280cd07639c7ff9bffb2cdc by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31418: Fix an assertion failure in PyErr_WriteUnraisable() in case of an exception with a bad \_\_module__ attribute. (bpo-3539)
https://github.com/python/cpython/commit/f6e61df01536493f1280cd07639c7ff9bffb2cdc

**Comment by serhiy-storchaka** [comment]
New changeset 5dbb28ececdd0382d85b164aaf37bec1ae08036c by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31418: Fix an assertion failure in PyErr_WriteUnraisable() in case of an exception with a bad \_\_module__ attribute. (GH-3539) (bpo-3556)
https://github.com/python/cpython/commit/5dbb28ececdd0382d85b164aaf37bec1ae08036c
