### ISSUE TITLE
Support importing anything in ._pth files.

### ISSUE THREAD

**Issue by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [python/cpython#75594]
BPO | [31413](https://bugs.python.org/issue31413)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @AraHaan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-11.20:52:05.388>
created_at = <Date 2017-09-11.01:19:39.079>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7', 'OS-windows']
title = 'Support importing anything in ._pth files.'
updated_at = <Date 2017-09-11.20:52:05.387>
user = 'https://github.com/AraHaan'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-11.20:52:05.387>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-11.20:52:05.388>
closer = 'steve.dower'
components = ['Interpreter Core', 'Windows']
creation = <Date 2017-09-11.01:19:39.079>
creator = 'Decorater'
dependencies = []
files = []
hgrepos = []
issue_num = 31413
keywords = []
message_count = 2.0
messages = ['301846', '301900']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Decorater']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31413'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
E:\\TinyURL\\app\\Release\>tinyurl
Fatal Python error: only 'import site' is supported in .\_pth file

Current thread 0x0000161c (most recent call first):

The above Happens when I try to use the .\_pth file to automatically call \<something\>.main()

However it prints that and then Crashes on Windows. I am not sure about how it does on linux or not.

I would like this extended to work how I thought it would. (To support more than just site.py in the standard library as this would reduce rebuilds of embedded interpreters.

**Comment by zooba** [comment]
This is by design. You should not be using the .\_pth file for anything other than initializing sys.path.

If you want to run code at startup, consider using sitecustomize.py or a regular .pth file, all of which will be imported when you include "import site" in the .\_pth file.
