### ISSUE TITLE
Error while building PDF documentation

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#75604]
BPO | [31423](https://bugs.python.org/issue31423)
--- | :---
Nosy | @ned-deily, @zware, @JulienPalard, @Mariatta, @Linkid
PRs | <li>python/cpython#3693</li><li>python/cpython#3699</li><li>python/cpython#3700</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-23.05:51:11.007>
created_at = <Date 2017-09-11.19:54:48.450>
labels = ['3.7', 'docs']
title = 'Error while building PDF documentation'
updated_at = <Date 2017-10-03.08:48:30.541>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.08:48:30.541>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-23.05:51:11.007>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-09-11.19:54:48.450>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 31423
keywords = ['patch']
message_count = 11.0
messages = ['301895', '302757', '302762', '302763', '302765', '302766', '302784', '302861', '302869', '302965', '303582']
nosy_count = 6.0
nosy_names = ['ned.deily', 'docs@python', 'zach.ware', 'mdk', 'Mariatta', 'linkid']
pr_nums = ['3693', '3699', '3700']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31423'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JulienPalard** [comment]
Since the docsbuild-scripts [1] upgraded its sphinx-build [2], we're having this error when building the docs:

    ! Undefined control sequence.
    \py@authoraddress -> \strong

    {Python Software Foundation}\\ Email: \email {d...
    l.58 \sphinxtableofcontents
                           
    !  ==> Fatal error occurred, no output PDF file produced!


it looks like to be from conf.py line 97 [3]:

conf.py-95-# Additional stuff for the LaTeX preamble.
conf.py-96-latex_elements['preamble'] = r'''
conf.py:97:\\authoraddress{
conf.py-98-  \\strong{Python Software Foundation}\\\\
conf.py-99-  Email: \\email{docs@python.org}
conf.py-100-}


 [1]: https://github.com/python/docsbuild-scripts 
 [2]: we merged https://github.com/python/docsbuild-scripts/pull/12
 [3]: https://github.com/python/cpython/blob/909a6f626ff343937cd3f06fda996870e7890724/Doc/conf.py#L97

**Comment by zware** [comment]
New changeset 6de35849cb7a18bfaad828eb57a2e6caa7978690 by Zachary Ware in branch '3.6':
[3.6] bpo-31423: Fix building the PDF documentation (GH-3693) (GH-3699)
https://github.com/python/cpython/commit/6de35849cb7a18bfaad828eb57a2e6caa7978690

**Comment by zware** [comment]
New changeset da86874a3d8f882d6aedd882b2e27f59b59d6798 by Zachary Ware in branch '2.7':
[2.7] bpo-31423: Fix building the PDF documentation (GH-3693) (GH-3700)
https://github.com/python/cpython/commit/da86874a3d8f882d6aedd882b2e27f59b59d6798

**Comment by zware** [comment]
Pending results of actual builds on docs.p.o, this should be fixed.

**Comment by ned-deily** [comment]
Thanks for looking into this.  See also https://github.com/python/psf-salt/issues/118 where the question arose whether the version of Tex Live on docs is new enough.  I'm no expert at anything Tex but the odd thing is that I had been able to build dist docs on my current Debian (testing) system without this change.  Let's see what happens on docs after the daily full doc build.

**Comment by ned-deily** [comment]
Good news! It appears that the changes supplied by @Linkid have indeed fixed the daily downloadable doc build failures, 3.7, 3.6, and 2.7 docs were built successfully and the 404s are gone.  Thanks everyone for helping with this!

**Comment by Mariatta** [comment]
Seems like people are seeing 404s when downloading docs today. By any chance this issue is related?

**Comment by ned-deily** [comment]
> Seems like people are seeing 404s when downloading docs today.

Do you have specific URLs or web pages?  Or a link to where this was discussed?  I just did a quick look at some of the download pages and everything worked for me.

**Comment by Mariatta** [comment]
Sorry!! Yesterday morning I received 50+ emails all about document download page is 404. Reading those again, turns out these are older emails from a week before, somehow just showing up in my mailbox.
I think everything is good here. :)

Thanks!

**Comment by ned-deily** [comment]
New changeset a74ce09c738c3e3aa89994bf31049cb914dca389 by Ned Deily (Zachary Ware) in branch '3.6':
[3.6] bpo-31423: Fix building the PDF documentation (GH-3693) (GH-3699)
https://github.com/python/cpython/commit/a74ce09c738c3e3aa89994bf31049cb914dca389
