### ISSUE TITLE
Add an answer to the Windows FAQ about installing the Universal C Runtime

### ISSUE THREAD

**Issue by 1fc80209-cfe6-41fd-9885-cef8c09f27e2** [python/cpython#75608]
BPO | [31427](https://bugs.python.org/issue31427)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @Mariatta

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-12.12:00:28.355>
labels = ['3.8', '3.9', '3.10', 'type-feature', 'OS-windows', 'docs']
title = 'Add an answer to the Windows FAQ about installing the Universal C Runtime'
updated_at = <Date 2021-03-12.17:34:56.076>
user = 'https://bugs.python.org/StephanHouben'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-12.17:34:56.076>
actor = 'eryksun'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Windows']
creation = <Date 2017-09-12.12:00:28.355>
creator = 'Stephan Houben'
dependencies = []
files = []
hgrepos = []
issue_num = 31427
keywords = []
message_count = 4.0
messages = ['301952', '301959', '301974', '301994']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'eryksun', 'steve.dower', 'Mariatta', 'Stephan Houben']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31427'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by 1fc80209-cfe6-41fd-9885-cef8c09f27e2** [comment]
Several people have asked on python-list why they are running into these errors.

Python 3.6.0 can't start because api-ms-win-crt-runtime-l1-1-0.dll is missing. 

The solution is to install KB 2999226 "Update for Universal C Runtime in Windows". 
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

Propose to add this as a Windows FAQ.

**Comment by Mariatta** [comment]
Is this only a problem with 3.6.0 or \>= 3.6.0?

**Comment by zooba** [comment]
This is a problem with 3.5 and later running on Windows 8.1 or earlier without all Windows Updates being installed.

It can happen for two reasons:
* not using the official installer (most common)
* random failure in the official installer (rare)

Installing KB2999226 is a good start, though it will likely trigger another Windows Update to get the latest version. Windows 10 is not affected.

I'm in favor of adding this to the FAQ.

**Comment by eryksun** [comment]
The FAQ could instead link to the more recent update, KB3118401.

https://support.microsoft.com/en-us/help/3118401/update-for-universal-c-runtime-in-windows
