### ISSUE TITLE
[3.5] crash in gen_traverse(): gi_frame.ob_type=NULL, called by subtract_refs() during a GC collection

### ISSUE THREAD

**Issue by 39a8e412-f8e3-4d55-bb23-77cdef1f43ea** [python/cpython#75607]
BPO | [31426](https://bugs.python.org/issue31426)
--- | :---
Nosy | @pitrou, @vstinner, @mcepl, @ianw, @serhiy-storchaka, @1st1, @vzhestkov
Files | <li>[crash-bt.txt](https://bugs.python.org/file47134/crash-bt.txt "Uploaded as text/plain at 2017-09-12.08:34:51 by @ianw"): gdb backtrace of segfault</li><li>[crash-py-bt.txt](https://bugs.python.org/file47135/crash-py-bt.txt "Uploaded as text/plain at 2017-09-12.08:35:51 by @ianw"): GDB Python backtrace</li><li>[gdb-bt-full.txt](https://bugs.python.org/file50163/gdb-bt-full.txt "Uploaded as text/plain at 2021-07-20.07:34:56 by @vzhestkov"): gdb bt full</li><li>[py-bt.txt](https://bugs.python.org/file50164/py-bt.txt "Uploaded as text/plain at 2021-07-20.07:35:18 by @vzhestkov")</li><li>[gbd-bt-brief.txt](https://bugs.python.org/file50165/gbd-bt-brief.txt "Uploaded as text/plain at 2021-07-20.07:35:35 by @vzhestkov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-08-04.15:32:05.027>
created_at = <Date 2017-09-12.08:35:09.148>
labels = ['interpreter-core', 'type-crash']
title = '[3.5] crash in gen_traverse(): gi_frame.ob_type=NULL, called by subtract_refs() during a GC collection'
updated_at = <Date 2021-08-04.15:32:05.027>
user = 'https://github.com/ianw'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-04.15:32:05.027>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2021-08-04.15:32:05.027>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-09-12.08:35:09.148>
creator = 'iwienand'
dependencies = []
files = ['47134', '47135', '50163', '50164', '50165']
hgrepos = []
issue_num = 31426
keywords = []
message_count = 6.0
messages = ['301943', '301944', '301945', '301946', '397858', '398905']
nosy_count = 7.0
nosy_names = ['pitrou', 'vstinner', 'mcepl', 'iwienand', 'serhiy.storchaka', 'yselivanov', 'vzhestkov']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31426'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 39a8e412-f8e3-4d55-bb23-77cdef1f43ea** [comment]
Using 3.5.2-2ubuntu0\~16.04.3 (Xenial) we see an occasional segfault during garbage collection of a generator object

A full backtrace is attached, but the crash appears to be triggered inside gen_traverse during gc

\---
(gdb) info args
gen = 0x7f22385f0150
visit = 0x50eaa0 \<visit_decref\>
arg = 0x0

(gdb) print \*gen
$109 = {ob_base = {ob_refcnt = 1, ob_type = 0xa35760 \<PyGen_Type\>}, gi_frame = 0x386aed8, gi_running = 1 '\\001', gi_code = \<code at remote 0x7f223bb42f60\>, gi_weakreflist = 0x0, gi_name = 'linesplit', gi_qualname = 'linesplit'}
\---

I believe gen_traverse is doing the following

\---
```c
static int
gen_traverse(PyGenObject *gen, visitproc visit, void *arg)
{
    Py_VISIT((PyObject *)gen->gi_frame);
    Py_VISIT(gen->gi_code);
    Py_VISIT(gen->gi_name);
    Py_VISIT(gen->gi_qualname);
    return 0;
}
```

---

The problem here being that this generator's gen-\>gi_frame has managed to acquire a NULL object type but still has references

\---
(gdb) print \*gen-\>gi_frame
$112 = {ob_base = {ob_base = {ob_refcnt = 2, ob_type = 0x0}, ob_size = 0}, f_back = 0x0, f_code = 0xca3e4fd8950fef91, ...
\---

Thus it gets visited and it doesn't go well.

I have attached the py-bt as well, it's very deep with ansible, multiprocessing forking, imp.load_source() importing ... basically a nightmare.  I have not managed to get it down to any sort of minimal test case unfortunately.  This happens fairly infrequently, so suggests a race.  The generator in question has a socket involved:

\---
```py
def linesplit(socket):
    buff = socket.recv(4096).decode("utf-8")
    buffering = True
    while buffering:
        if "\n" in buff:
            (line, buff) = buff.split("\n", 1)
            yield line + "\n"
        else:
            more = socket.recv(4096).decode("utf-8")
            if not more:
                buffering = False
            else:
                buff += more
    if buff:
        yield buff
```

---

Wild speculation but maybe something to do with finalizing generators with file-descriptors across fork()?

At this point we are trying a work-around of not having the above socket reading routine in a generator but just a "regular" loop.  As it triggers as part of a production roll-out I'm not sure we can do too much more debugging.  Unless this rings any immediate bells for people, we can probably just have this for tracking at this point.  [1] is the original upstream issue
 
[1] https://storyboard.openstack.org/#!/story/2001186#comment-17441

**Comment by vstinner** [comment]
Python 3.5 moved to security only fixes recently, it doesn't accept bug fixes anymore:
https://devguide.python.org/#status-of-python-branches

It would be nice to Python 3.5.4 at least, or better: Python 3.6.x.


> (gdb) print \*gen-\>gi_frame
> $112 = {ob_base = {ob_base = {ob_refcnt = 2, ob_type = 0x0}, ob_size = 0}, f_back = 0x0, f_code = 0xca3e4fd8950fef91, ...

ob_type should never be NULL for an object still reachable and with a reference count different than zero. It seems like a bug in a C extension. It would help to test your application on a Python compiled in debug mode.

**Comment by vstinner** [comment]
I pointed bpo-26617 to Ian since Python 3.5.2 contains this GC crash, but it seems like it's not the same bug.

**Comment by vstinner** [comment]
> I pointed bpo-26617 to Ian since Python 3.5.2 contains this GC crash, but it seems like it's not the same bug.

Ah, I found an issue which had bpo-26617 in subtract_refs():
https://stackoverflow.com/questions/39990934/debugging-python-segmentation-faults-in-garbage-collection

So it's not only update_refs() called during GC collection.
