### ISSUE TITLE
ElementTree.Element.__deepcopy__() raises a SystemError in case of a bad memo

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75609]
BPO | [31428](https://bugs.python.org/issue31428)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3512</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.14:40:01.664>
created_at = <Date 2017-09-12.12:04:08.403>
labels = ['expert-XML', 'type-bug', '3.7']
title = 'ElementTree.Element.__deepcopy__() raises a SystemError in case of a bad memo'
updated_at = <Date 2017-09-12.14:40:01.663>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.14:40:01.663>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.14:40:01.664>
closer = 'serhiy.storchaka'
components = ['XML']
creation = <Date 2017-09-12.12:04:08.403>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31428
keywords = ['patch']
message_count = 3.0
messages = ['301953', '301955', '301963']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3512']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31428'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes ElementTree.Element.\_\_deepcopy__() to raise a
SystemError:

```py
class BadMemo:
    def get(*args):
        return None

import xml.etree.ElementTree
xml.etree.ElementTree.Element('foo').__deepcopy__(BadMemo())
```



this is because \_elementtree_Element___deepcopy__() (in [Modules/_elementtree.c](https://github.com/python/cpython/blob/main/Modules/_elementtree.c))
assumes that memo is a dictionary, and passes it to PyDict_SetItem(), which
raises the SystemError.

**Comment by serhiy-storchaka** [comment]
I suppose the Python implementation supports arbitrary mapping, not just dict. We could use general mapping API in the C implementation, but I think it isn't worth. \_\_deepcopy__ is used internally by copy.deepcopy(), which always passes a dict. I think it isn't worth to backport a fix, and it doesn't need tests. The behavior of calling \_\_deepcopy__ with non-dict is implementation detail. But it shouldn't crash or raise SystemError.

**Comment by serhiy-storchaka** [comment]
New changeset d056818ed2ade6d28190a375d7183f4aef9caa55 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31428: Prevent raising a SystemError in case the memo arg of ElementTree.Element.\_\_deepcopy__() isn't a dictionary. (bpo-3512)
https://github.com/python/cpython/commit/d056818ed2ade6d28190a375d7183f4aef9caa55
