### ISSUE TITLE
Impossible download python 3.6.2 and 2.7 documentation (html)

### ISSUE THREAD

**Issue by 3dfec8ea-750a-4831-8fb3-00a840342620** [python/cpython#75614]
BPO | [31433](https://bugs.python.org/issue31433)
--- | :---
Nosy | @berkerpeksag
Superseder | <li>bpo-31395: Docs Downloads are 404s</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.18:14:28.317>
created_at = <Date 2017-09-12.17:17:08.608>
labels = ['3.7']
title = 'Impossible download python 3.6.2 and 2.7 documentation (html)'
updated_at = <Date 2017-09-12.18:14:28.309>
user = 'https://bugs.python.org/DiegoSatoba'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.18:14:28.309>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.18:14:28.317>
closer = 'berker.peksag'
components = []
creation = <Date 2017-09-12.17:17:08.608>
creator = 'Diego Satoba'
dependencies = []
files = []
hgrepos = []
issue_num = 31433
keywords = []
message_count = 2.0
messages = ['301979', '301986']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'Diego Satoba']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '31395'
type = None
url = 'https://bugs.python.org/issue31433'
versions = ['Python 2.7', 'Python 3.7']
```

</p></details>

**Comment by 3dfec8ea-750a-4831-8fb3-00a840342620** [comment]
Hi, 

Links to python 3.6.2 and 2.7 documentation in HTML are broken, web server returns 404 Not Found.

The links are:
https://docs.python.org/2/archives/python-2.7.14rc1-docs-html.zip
https://docs.python.org/3/archives/python-3.6.2-docs-html.zip

**Comment by berkerpeksag** [comment]
Thank you for the report. This is a duplicate of bpo-31395. See https://bugs.python.org/issue31395#msg301978 and https://github.com/python/psf-salt/issues/118 for details.
