### ISSUE TITLE
Addition giving incorrect result in certain circumstances

### ISSUE THREAD

**Issue by aef01229-7f34-43d8-aa00-102c9aa0d07c** [python/cpython#75616]
BPO | [31435](https://bugs.python.org/issue31435)
--- | :---
Nosy | @bitdancer, @skrah
Files | <li>[pythonbug.txt](https://bugs.python.org/file47136/pythonbug.txt "Uploaded as text/plain at 2017-09-12.19:56:01 by Aodhán Collins"): Calculation Tests</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-12.20:17:03.237>
created_at = <Date 2017-09-12.19:56:01.464>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'Addition giving incorrect result in certain circumstances'
updated_at = <Date 2017-09-12.20:18:08.875>
user = 'https://bugs.python.org/AodhnCollins'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-12.20:18:08.875>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-12.20:17:03.237>
closer = 'skrah'
components = ['Interpreter Core']
creation = <Date 2017-09-12.19:56:01.464>
creator = 'Aodh\xc3\xa1n Collins'
dependencies = []
files = ['47136']
hgrepos = []
issue_num = 31435
keywords = []
message_count = 3.0
messages = ['301991', '301992', '301993']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'skrah', 'Aodh\xc3\xa1n Collins']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31435'
versions = ['Python 3.5']
```

</p></details>

**Comment by aef01229-7f34-43d8-aa00-102c9aa0d07c** [comment]
Basic addition is dropping a tiny fraction when adding together certain numbers. We have discovered that when adding together the numbers 8.95 and 0.95 we get an incorrect answer, that is off by a tiny fraction. This doesn't occur when adding 7.95 and 0.95 but occurs for 8.95 and above. We have attached a file showing our calculations failing on Python 2.7 (on both a Mac and Linux system) and 3.5 (on a Linux system).

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Pythons has binary floating point, which does not give the same
results as a pocket calculator.

You can see the differences by using the decimal module:


```pycon
# These are the binary floats in exact decimal representation.
>>> Decimal(7.95)
Decimal('7.95000000000000017763568394002504646778106689453125')
>>> Decimal(8.95)
Decimal('8.949999999999999289457264239899814128875732421875')


# This is exact decimal arithmetic.
>>> Decimal("8.95") + Decimal("0.95")
Decimal('9.90')
```

**Comment by bitdancer** [comment]
https://docs.python.org/3/tutorial/floatingpoint.html
