### ISSUE TITLE
ResourceWarning in Python/traceback.c in case of a bad io.TextIOWrapper

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75625]
BPO | [31444](https://bugs.python.org/issue31444)
--- | :---
Nosy | @pitrou, @vstinner, @serhiy-storchaka, @orenmn

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-13.10:11:25.970>
created_at = <Date 2017-09-13.09:12:50.596>
labels = ['3.7', 'invalid', 'expert-IO', 'performance']
title = 'ResourceWarning in Python/traceback.c in case of a bad io.TextIOWrapper'
updated_at = <Date 2017-09-13.10:11:25.968>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-13.10:11:25.968>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-13.10:11:25.970>
closer = 'vstinner'
components = ['IO']
creation = <Date 2017-09-13.09:12:50.596>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31444
keywords = []
message_count = 4.0
messages = ['302039', '302040', '302049', '302050']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'serhiy.storchaka', 'Oren Milman']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31444'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
the following code causes a ResourceWarning:

```py
import io
def _bad_TextIOWrapper(*args):
    return None
io.TextIOWrapper = _bad_TextIOWrapper
1/0
```



this is because \_Py_DisplaySourceLine() (in [Python/traceback.c](https://github.com/python/cpython/blob/main/Python/traceback.c)) assumes that
io.TextIOWrapper() returned a stream object, and tries to call its close() 
method. in case calling close() fails, \_Py_DisplaySourceLine() just calls
PyErr_Clear().


maybe \_Py_DisplaySourceLine() should try to call binary.close() in such cases?

```c
I also thought about adding a check such as:
PyObject_IsInstance(fob, (PyObject*)&PyTextIOWrapper_Type);
but I am not sure whether we should use PyTextIOWrapper_Type outside of the io
module.
```

**Comment by vstinner** [comment]
> this is because \_Py_DisplaySourceLine() (in [Python/traceback.c](https://github.com/python/cpython/blob/main/Python/traceback.c)) assumes that io.TextIOWrapper() returned a stream object, and tries to call its close()  method. in case calling close() fails, \_Py_DisplaySourceLine() just calls PyErr_Clear().

I consider that \_Py_DisplaySourceLine() is right to expect that io.TextIOWrapper() creates a stream object. If the TextIOWrapper creation fails, it calls binary.close() to prevent a resource warning. Here your function doesn't fail but returns None which is really not expected.


> def \_bad_TextIOWrapper(*args): return None
> io.TextIOWrapper = \_bad_TextIOWrapper

I don't see why Python should support such strange TextIOWrapper type. I simply suggest to close the issue as WONTFIX.

**Comment by serhiy-storchaka** [comment]
I think it should be closed as "not a bug".

If io.TextIOWrapper() is successful, it is responsible for property closing a binary file. The bug is in user code, not in the interpreter code.

\_Py_DisplaySourceLine() correctly calls binary.close() if io.TextIOWrapper() failed.

**Comment by vstinner** [comment]
Ok, thanks for the confirmation Serhiy. I close the bug.
