### ISSUE TITLE
wrong default module search path in help message

### ISSUE THREAD

**Issue by zhangyangyu** [python/cpython#75621]
BPO | [31440](https://bugs.python.org/issue31440)
--- | :---
Nosy | @vstinner, @tiran, @ericsnowcurrently, @zware, @eryksun, @zooba, @zhangyangyu, @gaurav6696
PRs | <li>python/cpython#3624</li><li>python/cpython#4613</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2018-12-27.23:36:34.291>
created_at = <Date 2017-09-13.08:01:11.397>
labels = ['easy', 'type-bug', '3.7']
title = 'wrong default module search path in help message'
updated_at = <Date 2018-12-27.23:36:34.289>
user = 'https://github.com/zhangyangyu'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-27.23:36:34.289>
actor = 'cheryl.sabella'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2018-12-27.23:36:34.291>
closer = 'cheryl.sabella'
components = []
creation = <Date 2017-09-13.08:01:11.397>
creator = 'xiang.zhang'
dependencies = []
files = []
hgrepos = []
issue_num = 31440
keywords = ['patch', 'easy']
message_count = 9.0
messages = ['302032', '302338', '302339', '302361', '302480', '307127', '307132', '307147', '307148']
nosy_count = 8.0
nosy_names = ['vstinner', 'christian.heimes', 'eric.snow', 'zach.ware', 'eryksun', 'steve.dower', 'xiang.zhang', 'gauravbackback']
pr_nums = ['3624', '4613']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31440'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by zhangyangyu** [comment]
In python --help:

PYTHONHOME   : alternate \<prefix\> directory (or \<prefix\>:\<exec_prefix\>).
               The default module search path uses \<prefix\>/pythonX.X.

I think the default module search path should be \<prefix\>/lib/pythonX.X.

**Comment by tiran** [comment]
You are right, the path is wrong on Unix-like platforms. It's os.path.join(sys.prefix, 'lib', 'python{major}.{minor}'). But the actual path may depend on the platform, too. I don't recall how Windows sets up the path.

**Comment by tiran** [comment]
See site module, especially site.\_get_path()

```py
# Same to sysconfig.get_path('purelib', os.name+'_user')
def _get_path(userbase):
    version = sys.version_info

    if os.name == 'nt':
        return f'{userbase}\\Python{version[0]}{version[1]}\\site-packages'

    if sys.platform == 'darwin' and sys._framework:
        return f'{userbase}/lib/python/site-packages'
```


    return f'{userbase}/lib/python{version[0]}.{version[1]}/site-packages'

**Comment by zhangyangyu** [comment]
Not sure about Windows. \_get_path() looks to me is used for user site-packages. getsitepackages() doesn't do the same and seems matching the current message, also the OS2 branch in py2. Let's consult Windows guys.

**Comment by zooba** [comment]
I don't have time right this second to write it all up, but I did so in the past at https://docs.python.org/3/using/windows.html#finding-modules

Hopefully the answer you need is somewhere in that. Module search paths are complicated (but eric.snow is going to make it possible to use Python code to derive the search path at startup... right Eric? Right? :) )

**Comment by tiran** [comment]
New changeset 08d2b86a1058b733bb7f1ae2b55818dd9687d21c by Christian Heimes (gauravbackback) in branch 'master':
bpo-31440: Changed default module search path for windows
https://github.com/python/cpython/commit/08d2b86a1058b733bb7f1ae2b55818dd9687d21c

**Comment by vstinner** [comment]
I confirm that Python 2.7 is affected and should also be fixed.

**Comment by tiran** [comment]
I'll do a backport tomorrow.

**Comment by tiran** [comment]
New changeset cb79c2203953bd465f2c53b7a09a51071717575f by Christian Heimes (Miss Islington (bot)) in branch '3.6':
bpo-31440: Changed default module search path for windows (bpo-4613)
https://github.com/python/cpython/commit/cb79c2203953bd465f2c53b7a09a51071717575f
