### ISSUE TITLE
_winapi.CreateProcess (used by subprocess) is not thread-safe

### ISSUE THREAD

**Issue by 9060d193-4e82-4f3b-bf67-e5bd7fa733af** [python/cpython#75627]
BPO | [31446](https://bugs.python.org/issue31446)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba, @evanunderscore
PRs | <li>python/cpython#11141</li><li>python/cpython#11149</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-12-14.09:25:42.298>
created_at = <Date 2017-09-13.09:59:03.191>
labels = ['3.8', '3.7', 'library', 'OS-windows']
title = '_winapi.CreateProcess (used by subprocess) is not thread-safe'
updated_at = <Date 2018-12-14.09:25:42.297>
user = 'https://github.com/evanunderscore'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-14.09:25:42.297>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-12-14.09:25:42.298>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-09-13.09:59:03.191>
creator = 'evan_'
dependencies = []
files = []
hgrepos = []
issue_num = 31446
keywords = ['patch']
message_count = 4.0
messages = ['302045', '302046', '331786', '331788']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'evan_']
pr_nums = ['11141', '11149']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31446'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 9060d193-4e82-4f3b-bf67-e5bd7fa733af** [comment]
The method used for spawning subprocesses on Windows is not thread-safe under certain circumstances. The following example demonstrates how this manifests:

```pycon
    >>> import threading
    >>> import subprocess
    >>> for i in range(100):
    ...     threading.Thread(
    ...         target=subprocess.Popen,
    ...         args=('ping localhost',),
    ...         kwargs={'stdout': subprocess.DEVNULL},
    ...     ).start()
    ...
    Exception in thread Thread-1202:
    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "C:\Program Files\Python36\lib\threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Program Files\Python36\lib\subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "C:\Program Files\Python36\lib\subprocess.py", line 990, in _execute_child
        startupinfo)
    ValueError: embedded null character

    Exception in thread Thread-1206:
    Traceback (most recent call last):
      File "C:\Program Files\Python36\lib\threading.py", line 916, in _bootstrap_inner
        self.run()
      File "C:\Program Files\Python36\lib\threading.py", line 864, in run
        self._target(*self._args, **self._kwargs)
      File "C:\Program Files\Python36\lib\subprocess.py", line 707, in __init__
        restore_signals, start_new_session)
      File "C:\Program Files\Python36\lib\subprocess.py", line 990, in _execute_child
        startupinfo)
    ValueError: embedded null character
```


    >>>

subprocess.Popen calls down to \_winapi.CreateProcess, which calls CreateProcessW. When args is passed as a fixed string, the result of the argument conversion is attached to the object and shared by future calls into C code. However, the documentation for CreateProcess states:

"The Unicode version of this function, CreateProcessW, can modify the contents of this string. Therefore, this parameter cannot be a pointer to read-only memory (such as a const variable or a literal string). If this parameter is a constant string, the function may cause an access violation." (Source: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682425(v=vs.85).aspx)

It appears CreateProcessW is briefly inserting null characters into the buffer, causing errors if that buffer is used elsewhere before it is changed back.

The call to CreateProcessW using the shared buffer can be seen here: https://github.com/python/cpython/blob/b8f4163da30e16c7cd58fe04f4b17e38d53cd57e/Modules/_winapi.c#L879

Note that this error does not occur when passing args as a list, as subprocess.list2cmdline creates a new (though identical) string for each invocation.

One potential solution is to allocate a copy of command_line (the shared buffer) instead of using the original.

**Comment by vstinner** [comment]
I remove Python 3.3-3.5 from Python versions since these versions don't accept bugfixes anymore, only security fixes:
https://devguide.python.org/#status-of-python-branches
