### ISSUE TITLE
Subprocess exceptions re-raised in parent process do not have child_traceback attribute

### ISSUE THREAD

**Issue by 6f7b1187-fbd0-4e68-b40d-3d52c6303837** [python/cpython#75631]
BPO | [31450](https://bugs.python.org/issue31450)
--- | :---
Nosy | @gpshead, @tiran, @stratakis, @msekletar, @miss-islington
PRs | <li>python/cpython#11422</li><li>python/cpython#11422</li><li>python/cpython#11422</li><li>python/cpython#11422</li><li>python/cpython#11426</li><li>python/cpython#11426</li><li>python/cpython#11426</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-01-07.15:43:57.994>
created_at = <Date 2017-09-13.12:25:50.310>
labels = ['3.7', 'type-bug', 'library']
title = 'Subprocess exceptions re-raised in parent process do not have child_traceback attribute'
updated_at = <Date 2019-01-07.15:43:57.994>
user = 'https://github.com/msekletar'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-07.15:43:57.994>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-01-07.15:43:57.994>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-09-13.12:25:50.310>
creator = 'msekletar'
dependencies = []
files = []
hgrepos = []
issue_num = 31450
keywords = ['patch', 'patch', 'patch', 'patch']
message_count = 4.0
messages = ['302064', '302066', '332945', '332946']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'cstratak', 'msekletar', 'miss-islington']
pr_nums = ['11422', '11422', '11422', '11422', '11426', '11426', '11426']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31450'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6f7b1187-fbd0-4e68-b40d-3d52c6303837** [comment]
Issue
\-----
Documentation of subprocess module claims that exceptions raised in child process will be re-raised in the parent process and will have child_traceback attribute set [1]. At least on Fedora Rawhide with python-3.6.2 this is not the case.


Reproducer
\----------
```sh
$ cat preexec-exception.py
#!/usr/bin/env python3
```


```py
import subprocess

class PreExecCallback:
    def __call__(self):
        raise Exception()

if __name__ == "__main__":
    p = PreExecCallback()
```


    try:
        subprocess.Popen(['/bin/echo', 'foobar'], preexec_fn=p)
    except subprocess.SubprocessError as e:
        if not hasattr(e, 'child_traceback'):
            print('BUG: Exception happened in child, but exception object does not have child_traceback attribute')

Actual result
\-------------
```sh
$ ./preexec-exception.py 
BUG: Exception happened in child, but exception object does not have child_traceback attribute
```


Expected result
\---------------
No output, because child_traceback attribute is present

Additional info
\---------------
I happened to notice this while working with pre-exec callbacks. However, according to https://stackoverflow.com/questions/38433837/subprocess-child-traceback this seems to be the generic problem.

[1] https://docs.python.org/3/library/subprocess.html#exceptions

**Comment by tiran** [comment]
Documentation and implementation are out of sync. Python 3's subprocess module no longer sets child_traceback. I checked 3.3 to master. The assignment has been removed.
