### ISSUE TITLE
asyncio.gather does not cancel tasks if one fails

### ISSUE THREAD

**Issue by 1ba98678-fa11-4898-9594-bcb37e4aa73f** [python/cpython#75633]
BPO | [31452](https://bugs.python.org/issue31452)
--- | :---
Nosy | @gvanrossum, @asvetlov, @1st1, @kwarunek
PRs | <li>python/cpython#3597</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-19.17:48:16.085>
created_at = <Date 2017-09-13.14:53:36.998>
labels = ['3.7', 'type-bug', 'library', 'expert-asyncio']
title = 'asyncio.gather does not cancel tasks if one fails'
updated_at = <Date 2017-10-19.17:48:16.084>
user = 'https://bugs.python.org/AndrewLytvyn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-19.17:48:16.084>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-19.17:48:16.085>
closer = 'yselivanov'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-09-13.14:53:36.998>
creator = 'Andrew Lytvyn'
dependencies = []
files = []
hgrepos = []
issue_num = 31452
keywords = ['patch']
message_count = 10.0
messages = ['302079', '302186', '302195', '302243', '302720', '302735', '302737', '302743', '302751', '304625']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'asvetlov', 'yselivanov', 'kwarunek', 'Andrew Lytvyn']
pr_nums = ['3597']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31452'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1ba98678-fa11-4898-9594-bcb37e4aa73f** [comment]
If you do not await gather, then if one of gather inner coroutines fails, others keep working, but they should not.


```python
import asyncio
import logging

logging.basicConfig(level=logging.DEBUG)

loop = asyncio.get_event_loop()

async def success_coro(seconds):
    await asyncio.sleep(seconds)
    print(seconds)


async def failed_coro(seconds):
    await asyncio.sleep(seconds)
    print(seconds)
    raise ZeroDivisionError

coros = [
    success_coro(2),
    failed_coro(3),
    success_coro(5),
]

async def waiter():
    await asyncio.gather(*coros)

asyncio.ensure_future(waiter())

loop.run_forever()
```
\-------------------------------------------------------------
```pytb
Console:
2
3
ERROR:asyncio:Task exception was never retrieved
future: <Task finished coro=<waiter() done, defined at tst.py:72> exception=ZeroDivisionError()>
Traceback (most recent call last):
  File "tst.py", line 73, in waiter
    await asyncio.gather(*coros)
  File "tst.py", line 64, in failed_coro
    raise ZeroDivisionError
ZeroDivisionError
5
```

-------------------------------------------------------------

Expected behavior that 5 should not be printed.

**Comment by asvetlov** [comment]
Yuri, it looks like a serious bug.

I expected `success_coro(5)` cancelling but see print out.

**Comment by 1st1** [comment]
Andrew, looks like it.  You can take a look if you want (I don't have time to work on this right now).

**Comment by 43a930ce-92ff-472e-b021-f9644eabb63f** [comment]
I hit the same thing. Also there is a PR patch

**Comment by 1st1** [comment]
I looked at the PR, and I'm not so sure about this change.  In short, it can be viewed as a backwards incompatible change to asyncio.gather.

Guido, what do you think?

**Comment by gvanrossum** [comment]
I'm afraid I no longer have all the details of this design in my head, and I have no idea what the fix does (and no time to read up on everything).

The OP says "If you do not await gather" -- what happens if you \*do* await it? Do the tasks then get killed?

It seems strange to both cancel the task \*and* set its exception.

The docstring for gather() seems to be pretty clear that cancellation and failure of one task should not affect other tasks. So this argues against the PR.

**Comment by 1st1** [comment]
> I'm afraid I no longer have all the details of this design in my head, and I have no idea what the fix does (and no time to read up on everything).

Let's say we have three tasks: t1, t2, t3.  Then we use gather on them:

   await gather(t1, t2, t3)

Let's say that t2 finishes first with an exception.

Currently, both t1 and t3 would continue their execution even though gather throws the t2 exception.

The PR for this issue makes 'gather' to cancel both t1 and t3 as soon as t2 throws an exception.

The question is: I see the point of the PR, but I'm afraid that it's too late to change the semantics of asyncio.gather.  Instead we should consider adding new TaskGroup API (we discussed it briefly on the sprint).

**Comment by 1ba98678-fa11-4898-9594-bcb37e4aa73f** [comment]
Guido, look. The point is that if you change run_forever with run_until_complete, then behavior changes: success_coro(5) will not be executed.

I think that it's strange that behavior differs depending on entrypoint: run_forever or run_untill_complete

**Comment by gvanrossum** [comment]
> if you change run_forever with run_until_complete, then behavior changes: success_coro(5) will not be executed

Oh, that's a red herring. The reason is that the event loop stops when you use run_complete(), but the execution of success_coro(5) is still pending, and when you resume the loop (e.g. call run_until_complete() on the same loop with a different task) it will run.

So the issue is really the semantics of gather(), and I agree with Yury that we designed it intentionally that way, and if you want different behavior we'll have to provide a different API.

**Comment by 1st1** [comment]
I'm going to reject this issue as it's not backwards compatible.  I'll work on adding a new TaskGroup primitive in the next couple of days that would address this problem.
