### ISSUE TITLE
ElementTree.XMLParser() mishandles exceptions

### ISSUE THREAD

**Issue by scoder** [python/cpython#75636]
BPO | [31455](https://bugs.python.org/issue31455)
--- | :---
Nosy | @scoder, @vstinner, @zware, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3545</li><li>python/cpython#3585</li><li>python/cpython#3992</li><li>python/cpython#6318</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-04-26.06:37:08.327>
created_at = <Date 2017-09-13.17:28:39.624>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'ElementTree.XMLParser() mishandles exceptions'
updated_at = <Date 2018-04-26.06:37:08.326>
user = 'https://github.com/scoder'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-26.06:37:08.326>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2018-04-26.06:37:08.327>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-13.17:28:39.624>
creator = 'scoder'
dependencies = []
files = []
hgrepos = []
issue_num = 31455
keywords = ['patch']
message_count = 14.0
messages = ['302101', '302103', '302107', '302169', '302205', '302224', '304324', '304338', '304383', '314358', '314722', '314733', '314735', '314741']
nosy_count = 6.0
nosy_names = ['scoder', 'vstinner', 'eli.bendersky', 'zach.ware', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3545', '3585', '3992', '6318']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31455'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by scoder** [comment]
The "XMLParser.\_\_init__()" method in "\_elementtree.c" contains this code:

```c
    self->handle_start = PyObject_GetAttrString(target, "start");
    self->handle_data = PyObject_GetAttrString(target, "data");
    self->handle_end = PyObject_GetAttrString(target, "end");
    self->handle_comment = PyObject_GetAttrString(target, "comment");
    self->handle_pi = PyObject_GetAttrString(target, "pi");
    self->handle_close = PyObject_GetAttrString(target, "close");
    self->handle_doctype = PyObject_GetAttrString(target, "doctype");
    PyErr_Clear();
```


This ignores all exceptions, not only AttributeError.
It also passes live exceptions into the later lookup calls, which may execute arbitrary user code.

**Comment by serhiy-storchaka** [comment]
Oh, I see many other issues with C implementation of ElementTree.

1. If XMLParser.\_\_init__ is called twice, it leaks references and the Expat parser.

Possible solution: use the Py_XSETREF() macro instead of simple assignment. The Expat parser needs special handling.

Other possible solution: drop \_\_init__() and make all initialization in \_\_new__(). But this is a solution only for 3.7 because can break compatibility.

2. If XMLParser.\_\_init__ is not called or if it fails to initialize the Expat parser, self-\>entity and self-\>target are NULL. Later in xmlparser_getattro() they are increfed unconditionally.

**Comment by scoder** [comment]
Feel free to provide a separate pull request. These issues seem independent of the exception handling problem that I wrote a fix for.

**Comment by serhiy-storchaka** [comment]
I agree. While these issues are not totally independent (they changes the same code), my issue needs uncommon use of \_\_new__ and \_\_init__, while your issue can be exposed in normal cases.

**Comment by serhiy-storchaka** [comment]
New changeset c8d8e15bfc24abeeaaf3d8be9073276b0c011cdf by Serhiy Storchaka (scoder) in branch 'master':
bpo-31455: Fix an assertion failure in ElementTree.XMLParser(). (bpo-3545)
https://github.com/python/cpython/commit/c8d8e15bfc24abeeaaf3d8be9073276b0c011cdf

**Comment by serhiy-storchaka** [comment]
New changeset 49caab46f687eb201898fb6c2c40d47bdcb0e58b by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31455: Fix an assertion failure in ElementTree.XMLParser(). (GH-3545) (bpo-3585)
https://github.com/python/cpython/commit/49caab46f687eb201898fb6c2c40d47bdcb0e58b

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Serhiy, in addition to the problems you mentioned with not calling \_\_init__(), it seems
that calling every method of an uninitialized XMLParser object would crash.

If you don't mind, i would be happy to open an issue to fix these crashes.

**Comment by serhiy-storchaka** [comment]
It would be nice. But I see you already have opened bpo-31758 for reference leaks. I think that other problems can be solved in the same issue.

Do you mind to backport your patch to 2.7 Stefan? If this makes sense. Otherwise I'll just close this issue. Live exceptions don't cause crash in 2.7.

**Comment by scoder** [comment]
Backport PR for 2.7 added: 3992
