### ISSUE TITLE
LoggerAdapter objects cannot be nested

### ISSUE THREAD

**Issue by ambv** [python/cpython#75638]
BPO | [31457](https://bugs.python.org/issue31457)
--- | :---
Nosy | @vsajip, @ambv, @Mariatta
PRs | <li>python/cpython#3551</li><li>python/cpython#3576</li><li>python/cpython#4042</li><li>python/cpython#4043</li><li>python/cpython#4044</li><li>python/cpython#4050</li><li>python/cpython#6568</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ambv'
closed_at = <Date 2017-09-14.17:51:52.625>
created_at = <Date 2017-09-13.20:15:11.999>
labels = ['type-bug', '3.7']
title = 'LoggerAdapter objects cannot be nested'
updated_at = <Date 2018-04-22.22:00:33.135>
user = 'https://github.com/ambv'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-22.22:00:33.135>
actor = 'lukasz.langa'
assignee = 'lukasz.langa'
closed = True
closed_date = <Date 2017-09-14.17:51:52.625>
closer = 'lukasz.langa'
components = []
creation = <Date 2017-09-13.20:15:11.999>
creator = 'lukasz.langa'
dependencies = []
files = []
hgrepos = []
issue_num = 31457
keywords = ['patch']
message_count = 8.0
messages = ['302111', '302175', '302182', '304598', '304599', '304622', '304630', '315631']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'lukasz.langa', 'Mariatta']
pr_nums = ['3551', '3576', '4042', '4043', '4044', '4050', '6568']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31457'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ambv** [comment]
LoggerAdapter objects cannot be nested in Python 3 due to their `log()` and `isEnabledFor()` methods addressing attributes that are not present on the proxy.

Adding the missing attributes fixes the issue.

**Comment by Mariatta** [comment]
New changeset 4d9a8f22999de489ede9216ff983d4359d837760 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31457: Don't omit inner ``process()`` calls with nested LogAdapters (GH-4044) (GH-4050)
https://github.com/python/cpython/commit/4d9a8f22999de489ede9216ff983d4359d837760
