### ISSUE TITLE
Remove trailing spaces from Python-ast.h

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75645]
BPO | [31464](https://bugs.python.org/issue31464)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#3568</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.05:51:25.444>
created_at = <Date 2017-09-14.07:17:34.276>
labels = ['3.7']
title = 'Remove trailing spaces from Python-ast.h'
updated_at = <Date 2017-09-15.05:51:25.443>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.05:51:25.443>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.05:51:25.444>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-09-14.07:17:34.276>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31464
keywords = ['patch']
message_count = 2.0
messages = ['302149', '302230']
nosy_count = 2.0
nosy_names = ['benjamin.peterson', 'serhiy.storchaka']
pr_nums = ['3568']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31464'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed PR makes [Parser/asdl_c.py](https://github.com/python/cpython/blob/main/Parser/asdl_c.py) not emitting trailing spaces for blank lines in [Include/Python-ast.h](https://github.com/python/cpython/blob/main/Include/Python-ast.h).

**Comment by benjaminp** [comment]
New changeset 5d84cb368c0c3e475c25171c302068c4dfc3e396 by Benjamin Peterson (Serhiy Storchaka) in branch 'master':
bpo-31464: asdl_c.py no longer emits trailing spaces in Python-ast.h. (bpo-3568)
https://github.com/python/cpython/commit/5d84cb368c0c3e475c25171c302068c4dfc3e396
