### ISSUE TITLE
No easy way to change float formatting when subclassing encoder.JSONEncoder

### ISSUE THREAD

**Issue by 524b48e8-68da-4cd2-91d6-5a77cc237cbf** [python/cpython#75647]
BPO | [31466](https://bugs.python.org/issue31466)
--- | :---
Nosy | @merwok, @methane, @serhiy-storchaka, @impact27, @sfreilich
PRs | <li>python/cpython#3515</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-03-08.04:04:28.780>
created_at = <Date 2017-09-14.09:48:13.111>
labels = ['3.8', 'type-feature', '3.7']
title = 'No easy way to change float formatting when subclassing encoder.JSONEncoder'
updated_at = <Date 2021-04-01.15:16:16.135>
user = 'https://github.com/impact27'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-01.15:16:16.135>
actor = 'sfreilich'
assignee = 'none'
closed = True
closed_date = <Date 2021-03-08.04:04:28.780>
closer = 'methane'
components = []
creation = <Date 2017-09-14.09:48:13.111>
creator = 'qpeter'
dependencies = []
files = []
hgrepos = []
issue_num = 31466
keywords = ['patch']
message_count = 4.0
messages = ['302162', '302306', '387891', '389993']
nosy_count = 5.0
nosy_names = ['eric.araujo', 'methane', 'serhiy.storchaka', 'qpeter', 'sfreilich']
pr_nums = ['3515']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31466'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 524b48e8-68da-4cd2-91d6-5a77cc237cbf** [comment]
I want to output floats in ENG format. Working with distance in micrometers, it is a bit annoying to see:
2.5e-5
.0003
instead of 
25e-6
300e-6
The solution I found was to redefine `iterencode` but that doesn't feel right.

I would like to see something similar to the "default" function that is easely modified.

**Comment by merwok** [comment]
Hello and thanks for the patch!  If you don’t get feedback, you could try the python-ideas mailing list to see if other people have the same need and if there’s already a solution for this.

Serhiy, would you mind refreshing my memory about json development?  I’m not sure whether it’s still supposed to follow the development of simplejson, or if it’s effectively a fork now.
