### ISSUE TITLE
Remove trailing whitespaces

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75643]
BPO | [31462](https://bugs.python.org/issue31462)
--- | :---
Nosy | @terryjreedy, @benjaminp, @serhiy-storchaka
PRs | <li>python/cpython#3564</li><li>python/cpython#3594</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-14.06:39:03.099>
created_at = <Date 2017-09-14.05:50:09.035>
labels = ['3.7']
title = 'Remove trailing whitespaces'
updated_at = <Date 2017-09-15.02:52:20.865>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.02:52:20.865>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-14.06:39:03.099>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-09-14.05:50:09.035>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31462
keywords = ['patch']
message_count = 5.0
messages = ['302140', '302144', '302173', '302180', '302229']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'benjamin.peterson', 'serhiy.storchaka']
pr_nums = ['3564', '3594']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31462'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed PR removes trailing whitespaces from CPython source files. Some of them were added since the last trailing whitespaces removing. Some text files were omitted in previous trailing whitespaces removings. Now I consider them safe to cleanup.

**Comment by serhiy-storchaka** [comment]
New changeset 13ad3b7a82bf56d803fbe48ee5df6c4b08986c78 by Serhiy Storchaka in branch 'master':
bpo-31462: Remove trailing whitespaces. (bpo-3564)
https://github.com/python/cpython/commit/13ad3b7a82bf56d803fbe48ee5df6c4b08986c78

**Comment by terryjreedy** [comment]
I plan to backport the idlelib changes.  Do you prefer than I try to include other files (by using cherry-pick) or only do idlelib (probably much easier)?

**Comment by serhiy-storchaka** [comment]
Usually we don't backport such kind of changes. And I afraid that cherry-picking would be with many conflicts, because many changes are in new code. The idlelib changes are more harmless, since they are in text files.

**Comment by terryjreedy** [comment]
New changeset 93d5f91fff5740b463980797a04f3d5f1d5f1a51 by Terry Jan Reedy in branch '3.6':
[3.6] bpo-31462: IDLE - remove trailing whitespaces (GH-3564) (bpo-3594)
https://github.com/python/cpython/commit/93d5f91fff5740b463980797a04f3d5f1d5f1a51
