### ISSUE TITLE
Stdlib source files not installed

### ISSUE THREAD

**Issue by ba64272d-9789-48f7-9918-6a14aeebdb4d** [python/cpython#75657]
BPO | [31476](https://bugs.python.org/issue31476)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-02.23:15:33.983>
created_at = <Date 2017-09-14.19:50:17.521>
labels = ['type-bug', 'expert-installation', 'OS-windows']
title = 'Stdlib source files not installed'
updated_at = <Date 2019-10-31.14:22:00.643>
user = 'https://bugs.python.org/Zero'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-31.14:22:00.643>
actor = 'Zero'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-02.23:15:33.983>
closer = 'steve.dower'
components = ['Installation', 'Windows']
creation = <Date 2017-09-14.19:50:17.521>
creator = 'Zero'
dependencies = []
files = []
hgrepos = []
issue_num = 31476
keywords = []
message_count = 4.0
messages = ['302201', '302283', '302291', '348934']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31476'
versions = ['Python 3.6']
```

</p></details>

**Comment by ba64272d-9789-48f7-9918-6a14aeebdb4d** [comment]
Ever since Python 3.6.1, trying to open a Python-source library module in IDLE on Windows (10) has not worked properly since the installer has only been providing \*.pyc files. Learning how to use Python has always been easy since it (1) has a great help document, (2) makes it easy to get help() on objects, and (3) allows the source to easily be explored and/or patched. Is there something special that needs to be done to get both the standard library's \*.py files and precompile them to \*.pyc during installation?

I would be glad to run further tests if the Windows installer can be run headless with specific command-line arguments.

**Comment by terryjreedy** [comment]
IDLE's class browser is based on stdlib's pyclbr, which processes source.py files.  I have no idea how you install python to not get source files, as source is the default option with the PSF installer.  In any case, this is an install issue, not an IDLE issue.

Since you are asking for the standard behavior, I suspect you must be using an alternate .pyc-only installer. I am therefore inclined to close as 'not a bug'.

If you want further response, please tell us the exact name of the installer and the url where you got it.

**Comment by ba64272d-9789-48f7-9918-6a14aeebdb4d** [comment]
The URL for the installer that was used last is:

https://www.python.org/ftp/python/3.6.2/python-3.6.2-amd64-webinstall.exe
