### ISSUE TITLE
Running inside docker container from non-root user

### ISSUE THREAD

**Issue by b079ef3f-9e4f-48a4-9172-5135696a4902** [python/cpython#75650]
BPO | [31469](https://bugs.python.org/issue31469)
--- | :---
Nosy | @bitdancer, @Cinerar
PRs | <li>python/cpython#3403</li>
Superseder | <li>bpo-10496: Python startup should not require passwd entry</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-14.15:33:48.783>
created_at = <Date 2017-09-14.15:12:08.951>
labels = ['3.7', 'type-bug', 'library']
title = 'Running inside docker container from non-root user'
updated_at = <Date 2017-09-14.15:34:28.949>
user = 'https://github.com/Cinerar'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-14.15:34:28.949>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-14.15:33:48.783>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-09-14.15:12:08.951>
creator = 'cinerar'
dependencies = []
files = []
hgrepos = []
issue_num = 31469
keywords = []
message_count = 2.0
messages = ['302172', '302174']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'cinerar']
pr_nums = ['3403']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '10496'
type = 'behavior'
url = 'https://bugs.python.org/issue31469'
versions = ['Python 3.7']
```

</p></details>

**Comment by b079ef3f-9e4f-48a4-9172-5135696a4902** [comment]
When i try to run youtube-dl inside docker container from non root user i recieve this error:

failed to import the site module traceback (most recent call last): file "/usr/lib/python3.6/site.py", line 544, in main() file "/usr/lib/python3.6/site.py", line 530, in main known_paths = addusersitepackages(known_paths) file "/usr/lib/python3.6/site.py", line 282, in addusersitepackages user_site = getusersitepackages() file "/usr/lib/python3.6/site.py", line 258, in getusersitepackages user_base = getuserbase() # this will also set user_base file "/usr/lib/python3.6/site.py", line 248, in getuserbase user_base = get_config_var('userbase') file "/usr/lib/python3.6/sysconfig.py", line 601, in get_config_var return get_config_vars().get(name) file "/usr/lib/python3.6/sysconfig.py", line 558, in get_config_vars \_config_vars['userbase'] = \_getuserbase() file "/usr/lib/python3.6/sysconfig.py", line 205, in \_getuserbase return joinuser("\~", ".local") file "/usr/lib/python3.6/sysconfig.py", line 184, in joinuser return os.path.expanduser(os.path.join(*args)) file "/usr/lib/python3.6/posixpath.py", line 247, in expanduser userhome = pwd.getpwuid(os.getuid()).pw_dir keyerror: 'getpwuid(): uid not found: 1000'

I believe this problem is described here:
http://blog.dscpl.com.au/2015/12/unknown-user-when-running-docker.html

this simple fix make it work again

**Comment by bitdancer** [comment]
It sounds like docker is just broken (I would expect unix tools to work in a docker container).  That however is beside the point.

I believe this is a duplicate of bpo-10496, but I don't know why it hasn't been fixed.
