### ISSUE TITLE
assertion failure in random.seed() in case the seed argument has a bad __abs__() method

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75659]
BPO | [31478](https://bugs.python.org/issue31478)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @vedgar, @orenmn
PRs | <li>python/cpython#3596</li><li>python/cpython#3794</li><li>python/cpython#3845</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-02.21:35:15.517>
created_at = <Date 2017-09-14.20:33:46.293>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in random.seed() in case the seed argument has a bad __abs__() method'
updated_at = <Date 2017-10-02.21:35:15.516>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-02.21:35:15.516>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-02.21:35:15.517>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-14.20:33:46.293>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31478
keywords = ['patch']
message_count = 13.0
messages = ['302208', '302228', '302232', '302234', '302241', '302317', '302740', '302782', '303196', '303201', '303207', '303451', '303566']
nosy_count = 4.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'veky', 'Oren Milman']
pr_nums = ['3596', '3794', '3845']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31478'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure:
class BadInt(int):
    def \_\_abs__(self):
        return None

```py
import random

random.seed(BadInt())
```



this is because random_seed() (in [Modules/_randommodule.c](https://github.com/python/cpython/blob/main/Modules/_randommodule.c)) assumes that
PyNumber_Absolute() returned an int, and so it passes it to \_PyLong_NumBits(),
which asserts it received an int.


what should we do in such a case?
should we raise an exception? (the docs don't mention abs() in case the seed is
an int - https://docs.python.org/3.7/library/random.html#random.seed)

**Comment by rhettinger** [comment]
It would make sense to verify that an actual int was returned and to raise a TypeError if it wasn't.  

Do you want to submit a PR (with a test case)?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
sure.
but what about the TypeError message? should it complain about
the return value of abs(seed)? (the docs of random.seed don't mention abs().)

**Comment by serhiy-storchaka** [comment]
There are several ways of solving this issue:

1. Verify that an actual int was returned and raise a TypeError if it wasn't.

2. Verify that an actual int was returned and fall back to the hash if it wasn't.

3. Use int.\_\_abs__() instead of abs(), the result will be guaranteed int. The drawback is that this makes a copy of positive integers for int subclasses.

4. Check the sign of the seed and call int.\_\_neg__() for negative values.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
i opened a PR that implements the first option, but of course I wouldn't
mind if you decide another option is better.

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
So floats (and complexes) cannot be seeds anymore? :-o Or this pertains only to ints? In this case, I think the easiest doc fix is to change

If a is an int, it is used directly.

to

If a is an int, its absolute value is used.

**Comment by serhiy-storchaka** [comment]
The more I think about this the more I like the idea of using int.\_\_abs__() directly (PyLong_Type.tp_as_number-\>nb_absolute() in C). The C code doesn't call potentially overridable methods bit_length() and to_bytes(), it uses concrete implementations directly. I don't see reasons why it should obey overriding the \_\_abs__() method.

This will save us from the problem with the wording of the error message.

I mentioned a drawback, but the current implementation has the same drawback. We can avoid copying positive integer subtypes by using more complex code, but I think it isn't worth.

**Comment by rhettinger** [comment]
>  I don't see reasons why it should obey overriding the \_\_abs__() method.

I concur.

**Comment by serhiy-storchaka** [comment]
New changeset d780b2d588e68bd7047ef5d1f04e36da38b7a350 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31478: Fix an assertion failure in random.seed() in case a seed has a bad \_\_abs__() method. (bpo-3596)
https://github.com/python/cpython/commit/d780b2d588e68bd7047ef5d1f04e36da38b7a350

**Comment by serhiy-storchaka** [comment]
New changeset befc956acf8ddeb94f000ed081ddec51315429e5 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31478: Fix an assertion failure in random.seed() in case a seed has a bad \_\_abs__() method. (GH-3596) (bpo-3794)
https://github.com/python/cpython/commit/befc956acf8ddeb94f000ed081ddec51315429e5

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
With regard to backporting to 2.7:

In 2.7 also, PyNumber_Absolute() is called, and its return value is stored in
the variable n.
However, there is no \_PyLong_NumBits(n), so there is no assertion failure.
If n isn't an integer:
- if !PyObject_IsTrue(n), then the seed is zero (e.g. if n is None, [], () or {})
- otherwise, PyNumber_And() and PyNumber_Rshift() are used in a loop on n, so
  probably a TypeError would be raised.


So I think a backport is still desirable, but i am not sure about the test.

Maybe we should use @cpython_only, and make sure that no error is raised?
We can also make sure that random() returns a different value than when the
seed is zero.

What do you think?

**Comment by serhiy-storchaka** [comment]
I agree that a backport is still desirable.

Your plan LGTM. Implement \_\_abs__ raising an exception (test both int ant long subclasses). Make sure that no error is raised. Make sure that random() returns the same value as when seeding with an exact int and long.

**Comment by serhiy-storchaka** [comment]
New changeset 13da1a60f13e173f65bb0da5ab325641d5bb99ec by Serhiy Storchaka (Oren Milman) in branch '2.7':
[2.7] bpo-31478: Prevent unwanted behavior in \_random.Random.seed() in case the arg has a bad \_\_abs__() method (GH-3596) (bpo-3845)
https://github.com/python/cpython/commit/13da1a60f13e173f65bb0da5ab325641d5bb99ec
