### ISSUE TITLE
assertion failure in subprocess.Popen() in case the env arg has a bad keys() method

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75652]
BPO | [31471](https://bugs.python.org/issue31471)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3580</li><li>python/cpython#3584</li><li>python/cpython#3595</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-15.07:20:59.988>
created_at = <Date 2017-09-14.16:42:10.886>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in subprocess.Popen() in case the env arg has a bad keys() method'
updated_at = <Date 2017-09-15.07:20:59.986>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-15.07:20:59.986>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-15.07:20:59.988>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-14.16:42:10.886>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31471
keywords = ['patch']
message_count = 10.0
messages = ['302181', '302199', '302200', '302203', '302231', '302235', '302236', '302237', '302238', '302239']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3580', '3584', '3595']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31471'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure on Windows:
class BadEnv(dict):
    keys = None

```py
import subprocess

import sys

subprocess.Popen([sys.executable, "-c", "pass"], env=BadEnv())
```



this is because getenvironment() (in [Modules/_winapi.c](https://github.com/python/cpython/blob/main/Modules/_winapi.c)) calls PyMapping_Values()
immediately after calling PyMapping_Keys().
calling PyMapping_Values() ultimately leads to calling \_PyObject_FastCallDict(),
which does 'assert(!PyErr_Occurred());'.
thus, in case of an error in PyMapping_Keys(), the assertion fails.

**Comment by serhiy-storchaka** [comment]
New changeset 0b3a87ef54a0112b74e8a1d8c6f87d10db4239ab by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31471: Fix assertion failure in subprocess.Popen() on Windows, in case env has a bad keys() method. (bpo-3580)
https://github.com/python/cpython/commit/0b3a87ef54a0112b74e8a1d8c6f87d10db4239ab

**Comment by serhiy-storchaka** [comment]
Is this bug reproducible in 2.7?

**Comment by serhiy-storchaka** [comment]
New changeset f135f62cfd1529cbb9326e53728a22afd05b6bc3 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31471: Fix assertion failure in subprocess.Popen() on Windows, in case env has a bad keys() method. (GH-3580) (bpo-3584)
https://github.com/python/cpython/commit/f135f62cfd1529cbb9326e53728a22afd05b6bc3

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
in 2.7 getenvironment() is in [PC/_subprocess.c](https://github.com/python/cpython/blob/main/PC/_subprocess.c), and it also calls PyMapping_Values()
immediately after calling PyMapping_Keys().
however, \_PyObject_FastCallDict() doesn't exist here.
in case of an error in both PyMapping_Keys() and PyMapping_Values(), the
error in PyMapping_Values() just overwrites the error in PyMapping_Keys().

but I haven't gone over all of the code that could be run as part of
PyMapping_Values(), so I am not sure whether something could go wrong in case PyMapping_Keys() failed.

**Comment by serhiy-storchaka** [comment]
Then I think it is worth to backport the fix to 2.7.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
OK.
but there isn't an assertion failure to test in 2.7, so is adding a test
still relevant?

**Comment by serhiy-storchaka** [comment]
It's on you.

**Comment by serhiy-storchaka** [comment]
New changeset c7f165fe652651c32833245fc902c790a4f173fa by Serhiy Storchaka (Oren Milman) in branch '2.7':
[2.7] bpo-31471: Fix assertion failure in subprocess.Popen() on Windows, in case env has a bad keys() method. (GH-3580) (bpo-3595)
https://github.com/python/cpython/commit/c7f165fe652651c32833245fc902c790a4f173fa

**Comment by serhiy-storchaka** [comment]
Thanks Oren!
