### ISSUE TITLE
Always reset the signal alarm in tests

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75660]
BPO | [31479](https://bugs.python.org/issue31479)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#3588</li><li>python/cpython#7312</li><li>python/cpython#7314</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-19.16:40:46.616>
created_at = <Date 2017-09-14.21:33:50.360>
labels = ['3.7', 'tests']
title = 'Always reset the signal alarm in tests'
updated_at = <Date 2018-06-01.13:23:12.637>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-01.13:23:12.637>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-19.16:40:46.616>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-09-14.21:33:50.360>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = ['373']
issue_num = 31479
keywords = ['patch']
message_count = 7.0
messages = ['302213', '302223', '302543', '302545', '302546', '318412', '318413']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['3588', '7312', '7314']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31479'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
While fixing bpo-17085 on Python 2.7 (test_socket: cancel scheduled alarm on test failure), I noticed that not all unit tests currently always reset the signal alarm.

I propose to always use the pattern "try/finally: signal.alarm(0)" to make sure that a test doesn't "leak" a pending fatal signal alarm.

Attached PR fixes the issue.

I don't think that it's worth it to backport the fix, since it only impacts tests which fail, interrupted manually by CTRL+c or other corner cases.

**Comment by serhiy-storchaka** [comment]
Maybe add a context manager? Some pattern is repeated multiple times.

**Comment by vstinner** [comment]
New changeset 9abee722d448c1c00c7d4e11ce242ec7b13e5c49 by Victor Stinner in branch 'master':
bpo-31479: Always reset the signal alarm in tests (bpo-3588)
https://github.com/python/cpython/commit/9abee722d448c1c00c7d4e11ce242ec7b13e5c49

**Comment by vstinner** [comment]
While the fix is nice to have to handle corner cases, I'm not sure that it's really useful to backport the change to Python 2.7 and 3.6. So I close the issue.

**Comment by vstinner** [comment]
Serhiy: "Maybe add a context manager? Some pattern is repeated multiple times."

As I wrote on the PR, I'm not sure because not all the code look the same. Please propose a PR if you want, I can review it!
