### ISSUE TITLE
random.seed() doesn't work with bytes and version=1

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75663]
BPO | [31482](https://bugs.python.org/issue31482)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @Mariatta
PRs | <li>python/cpython#3614</li><li>python/cpython#3629</li><li>python/cpython#3659</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/Mariatta'
closed_at = <Date 2017-09-20.18:04:36.435>
created_at = <Date 2017-09-15.12:10:39.762>
labels = ['3.7', 'type-bug', 'library']
title = "random.seed() doesn't work with bytes and version=1"
updated_at = <Date 2017-09-20.18:04:36.434>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-20.18:04:36.434>
actor = 'Mariatta'
assignee = 'Mariatta'
closed = True
closed_date = <Date 2017-09-20.18:04:36.435>
closer = 'Mariatta'
components = ['Library (Lib)']
creation = <Date 2017-09-15.12:10:39.762>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31482
keywords = ['patch']
message_count = 12.0
messages = ['302246', '302370', '302512', '302535', '302538', '302540', '302542', '302544', '302547', '302549', '302552', '302647']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'Mariatta']
pr_nums = ['3614', '3629', '3659']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31482'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The behavior of random.seed() with bytes and version=1 is specially documented. But actually it doesn't work.

```pycon
>>> import random
>>> random.seed(b'abc', version=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/serhiy/py/cpython/Lib/random.py", line 113, in seed
    x = ord(a[0]) << 7 if a else 0
TypeError: ord() expected string of length 1, but int found
```

**Comment by rhettinger** [comment]
New changeset 132a7d7cdbc7cb89fa1c1f4e8192241c3d68f549 by Raymond Hettinger in branch 'master':
bpo-31482:  Missing bytes support for random.seed() version 1 (bpo-3614)
https://github.com/python/cpython/commit/132a7d7cdbc7cb89fa1c1f4e8192241c3d68f549

**Comment by serhiy-storchaka** [comment]
Raymond, why the fix is not backported to 3.6?

**Comment by rhettinger** [comment]
Mariatta, what is the procedure for completing the backport?  I can see the miss-islington bot made a commit but it didn't take in the 3.6 branch.

**Comment by serhiy-storchaka** [comment]
What is wrong with [PR 3629](https://github.com/python/cpython/pull/3629)?

**Comment by Mariatta** [comment]
Hi Raymond, 

Somehow the backport PR https://github.com/python/cpython/pull/3629 was closed before instead of merged.

To retrigger the backport, we can re-apply the "needs backport to 3.6" label on the original PR (3614). I will do this now :)

**Comment by Mariatta** [comment]
Backport PR has been created. Once the CI checks are done, we can squash and merge it.

**Comment by serhiy-storchaka** [comment]
If [PR 3629](https://github.com/python/cpython/pull/3629) was closed by mistake it could be just reopened, isn't?

**Comment by Mariatta** [comment]
Serhiy, it can't be re-opened since miss-islington deleted the branch already.

**Comment by serhiy-storchaka** [comment]
Ah, now I understand what happened. Thanks Mariatta.

**Comment by Mariatta** [comment]
New changeset c6ce8fba07ea6798eac46ab2808167afecd4d90b by Mariatta (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31482:  Missing bytes support for random.seed() version 1 (GH-3614) (GH-3659)
https://github.com/python/cpython/commit/c6ce8fba07ea6798eac46ab2808167afecd4d90b

**Comment by Mariatta** [comment]
Backport was done. Thanks.
