### ISSUE TITLE
calling a _json.Encoder object raises a SystemError in case obj.items() returned a tuple

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75667]
BPO | [31486](https://bugs.python.org/issue31486)
--- | :---
Nosy | @rhettinger, @berkerpeksag, @serhiy-storchaka, @orenmn, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-11-21.14:34:54.710>
created_at = <Date 2017-09-15.17:21:39.054>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'calling a _json.Encoder object raises a SystemError in case obj.items() returned a tuple'
updated_at = <Date 2021-11-21.14:36:00.086>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-21.14:36:00.086>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-11-21.14:34:54.710>
closer = 'iritkatriel'
components = ['Extension Modules']
creation = <Date 2017-09-15.17:21:39.054>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31486
keywords = []
message_count = 6.0
messages = ['302278', '302290', '304712', '305794', '305796', '406717']
nosy_count = 5.0
nosy_names = ['rhettinger', 'berker.peksag', 'serhiy.storchaka', 'Oren Milman', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31486'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
the following code causes a SystemError:

```py
import json.encoder
class BadDict(dict):
    def items(self):
        return ()

encoder = json.encoder.c_make_encoder(None, None, None, None, 'foo', 'bar',
                                      True, None, None)
encoder(obj=BadDict({'spam': 42}), _current_indent_level=4)
```



this is because encoder_call() (in [Modules/_json.c](https://github.com/python/cpython/blob/main/Modules/_json.c)) passes the 'obj' argument
so that eventually encoder_listencode_dict() calls PyMapping_Items() on it.
encoder_listencode_dict() assumes that PyMapping_Items() returned a list, and
passes it to PyList_Sort().


ISTM that subclassing dict and implementing items() so that it returns a tuple
is not unrealistic.

maybe we should silently convert the tuple that PyMapping_Items() returned to a
list?

**Comment by serhiy-storchaka** [comment]
Oh, I was aware of this issue for long time, but didn't have good opportunity for fixing it. And yes, making PyMapping_Items() (and friends) always returning a list looks like a reasonable option to me. This could fix similar bugs in third-party extensions. In Python 2 PyMapping_Items() is documented as returning a list, but actually it can return an arbitrary type. Authors of extensions could be fooled by the documentation and use concrete list API.

The drawback of this solution is some performance degradation in rare case of items() returning a tuple.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
ISTM that [PR 3840](https://github.com/python/cpython/pull/3840) resolved this issue (as part of bpo-28280).

**Comment by berkerpeksag** [comment]
[PR 3840](https://github.com/python/cpython/pull/3840) has been merged and it looks like Oren was correct. I'm getting the following output with current master:

```pycon
>>> encoder(obj=BadDict({'spam': 42}), _current_indent_level=4)
['{}']
```

**Comment by serhiy-storchaka** [comment]
bpo-28280 fixed this issue only in the master branch. I had left this issue open for fixing 3.6.
