### ISSUE TITLE
Improve f-strings documentation wrt format specifiers

### ISSUE THREAD

**Issue by Mariatta** [python/cpython#75668]
BPO | [31487](https://bugs.python.org/issue31487)
--- | :---
Nosy | @ericvsmith, @vadmium, @Mariatta
PRs | <li>python/cpython#3604</li><li>python/cpython#3619</li><li>python/cpython#3627</li><li>python/cpython#3628</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-16.19:01:58.324>
created_at = <Date 2017-09-15.17:34:45.675>
labels = ['3.7', 'docs']
title = 'Improve f-strings documentation wrt format specifiers'
updated_at = <Date 2017-09-18.00:14:24.732>
user = 'https://github.com/Mariatta'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-18.00:14:24.732>
actor = 'martin.panter'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-16.19:01:58.324>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-09-15.17:34:45.675>
creator = 'Mariatta'
dependencies = []
files = []
hgrepos = []
issue_num = 31487
keywords = ['patch']
message_count = 5.0
messages = ['302279', '302350', '302367', '302368', '302397']
nosy_count = 4.0
nosy_names = ['eric.smith', 'docs@python', 'martin.panter', 'Mariatta']
pr_nums = ['3604', '3619', '3627', '3628']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31487'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by Mariatta** [comment]
Provide a couple more examples of using format specifiers in f-string.

**Comment by Mariatta** [comment]
New changeset 46c1052404c1a6e4d35af8e96613db8a4be75b52 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31487: Improve f-strings documentation (GH-3604) (GH-3619)
https://github.com/python/cpython/commit/46c1052404c1a6e4d35af8e96613db8a4be75b52

**Comment by Mariatta** [comment]
New changeset 63c591c0b0b57870a606e8edc59afe6264e7504d by Mariatta in branch 'master':
bpo-31487: Update F-strings doc example (GH-3627)
https://github.com/python/cpython/commit/63c591c0b0b57870a606e8edc59afe6264e7504d

**Comment by Mariatta** [comment]
New changeset 4f6bae9677c0e5398e64c503fd3c19cae94567da by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31487: Update F-strings doc example (GH-3627) (GH-3628)
https://github.com/python/cpython/commit/4f6bae9677c0e5398e64c503fd3c19cae94567da

**Comment by vadmium** [comment]
>\>\> f"{number:#0x}"  # using integer format specifier

It’s not clear what your purpose was adding the above line, but the zero flag (0) does nothing because there is no “width” field. I think it could be misleading, because it is actually the “#x” codes that generate the “0x” prefix.

If you want to illustrate a minimum width, I suggest something like

```pycon
>>> f"{number:#06x}"
'0x0400'
```


or (if the number is never negative)

```pycon
>>> f"0x{number:04X}"
'0x0400'
```


Or if you don’t care about the width:

```pycon
>>> f"{number:#x}"
'0x400'
```
