### ISSUE TITLE
Valgrind suppression file

### ISSUE THREAD

**Issue by 46242032-1dd7-4e2d-b95b-bb2ff63014fe** [python/cpython#75675]
BPO | [31494](https://bugs.python.org/issue31494)
--- | :---
Nosy | @terryjreedy, @skrah
Files | <li>[valgrind.log](https://bugs.python.org/file47140/valgrind.log "Uploaded as text/x-log at 2017-09-16.20:50:29 by Aaron Michaux")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-22.18:12:48.691>
created_at = <Date 2017-09-16.20:50:30.108>
labels = ['interpreter-core', 'invalid']
title = 'Valgrind suppression file'
updated_at = <Date 2017-09-22.18:12:48.689>
user = 'https://bugs.python.org/AaronMichaux'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-22.18:12:48.689>
actor = 'skrah'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-22.18:12:48.691>
closer = 'skrah'
components = ['Interpreter Core']
creation = <Date 2017-09-16.20:50:30.108>
creator = 'Aaron Michaux'
dependencies = []
files = ['47140']
hgrepos = []
issue_num = 31494
keywords = []
message_count = 4.0
messages = ['302353', '302759', '302760', '302761']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'skrah', 'Aaron Michaux']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31494'
versions = ['Python 3.5']
```

</p></details>

**Comment by 46242032-1dd7-4e2d-b95b-bb2ff63014fe** [comment]
The file "[Misc/valgrind-python.supp](https://github.com/python/cpython/blob/main/Misc/valgrind-python.supp)" doesn't work on Linux x64, running Python3.5.2, when configured as such:

  --with-pydebug --with-valgrind --without-pymalloc

Running the interpreter

   echo "x = 1; print(x)" | valgrind --tool=memcheck --leak-check=full --track-origins=yes --verbose --log-file=valgrind.log --suppressions=Misc/valgrind-python.supp /path/to/built/python3

Gives the attached valgrind.log file. The tail of this file says:

==22828== 
==22828== LEAK SUMMARY:
==22828==    definitely lost: 0 bytes in 0 blocks
==22828==    indirectly lost: 0 bytes in 0 blocks
==22828==      possibly lost: 298,529 bytes in 690 blocks
==22828==    still reachable: 605,872 bytes in 4,874 blocks
==22828==         suppressed: 0 bytes in 0 blocks
==22828== Reachable blocks (those to which a pointer was found) are not shown.
==22828== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==22828== 
==22828== ERROR SUMMARY: 256 errors from 256 contexts (suppressed: 0 from 0)
==22828== ERROR SUMMARY: 256 errors from 256 contexts (suppressed: 0 from 0)

**Comment by terryjreedy** [comment]
3.5 only gets security fixes, and this does not seem to be a security issue.  Please retest with 3.6 or 3.7.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
The suppressions are mainly for "invalid access" due to a gc trick.

The primary goal is to be definitely-lost-clean.


I would say it works as expected.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Also, I don't think --with-pydebug works well with valgrind.

It's either:
   1) --with-pydebug
   2) CFLAGS="-O0 -g" --with-valgrind
   3) CFLAGS="-O0 -g" --without-pymalloc

Combining 2) and 3) probably does not hurt, but is not necessary.
