### ISSUE TITLE
assertion failures in case a module has a bad __name__ attribute

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75673]
BPO | [31492](https://bugs.python.org/issue31492)
--- | :---
Nosy | @ethanfurman, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3620</li><li>python/cpython#3773</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.06:46:43.849>
created_at = <Date 2017-09-16.18:00:45.072>
labels = ['interpreter-core', '3.7', 'type-crash']
title = 'assertion failures in case a module has a bad __name__ attribute'
updated_at = <Date 2017-09-27.06:46:43.849>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.06:46:43.849>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.06:46:43.849>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-09-16.18:00:45.072>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31492
keywords = ['patch']
message_count = 3.0
messages = ['302348', '302514', '303090']
nosy_count = 3.0
nosy_names = ['ethan.furman', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3620', '3773']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31492'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure:
import os
os.\_\_name__ = None
os.does_not_exist

this is because module_getattro() (in [Objects/moduleobject.c](https://github.com/python/cpython/blob/main/Objects/moduleobject.c)) assumes that
\_\_name__ is a string, and passes it to PyErr_Format(), which asserts it is a
string.


if we fixed that one (so that the code above would raise an AttributeError),
the following code would still cause an assertion failure:

```py
import os
os.__name__ = None
from os import does_not_exist
```



this is because import_from() (in [Python/ceval.c](https://github.com/python/cpython/blob/main/Python/ceval.c)) also assumes that \_\_name__
is a string, and passes it to PyUnicode_FromFormat(), which asserts it is a
string.


BTW, while we are in module_getattro(): isn't the second call to PyErr_Clear()
redundant? (Ethan, IIUC, you worked on this as part of bpo-8297 some years ago..)

**Comment by serhiy-storchaka** [comment]
New changeset 6db7033192cd537ca987a65971acb01206c3ba82 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31492: Fix assertion failures in case of a module with a bad \_\_name__ attribute. (bpo-3620)
https://github.com/python/cpython/commit/6db7033192cd537ca987a65971acb01206c3ba82

**Comment by serhiy-storchaka** [comment]
New changeset f0db2dfda777ad3380e7816cabe4c4240f31687f by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31492: Fix assertion failures in case of a module with a bad \_\_name__ attribute. (GH-3620). (bpo-3773)
https://github.com/python/cpython/commit/f0db2dfda777ad3380e7816cabe4c4240f31687f
