### ISSUE TITLE
Signal delivered to a subprocess triggers parent's handler

### ISSUE THREAD

**Issue by 8261aa84-e702-455d-ad8f-b513a205490a** [python/cpython#75670]
BPO | [31489](https://bugs.python.org/issue31489)
--- | :---
Nosy | @pitrou, @njsmith, @1st1, @Kentzo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-16.05:25:54.129>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = "Signal delivered to a subprocess triggers parent's handler"
updated_at = <Date 2017-12-20.00:25:03.190>
user = 'https://github.com/Kentzo'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-20.00:25:03.190>
actor = 'njs'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-09-16.05:25:54.129>
creator = 'Ilya.Kulakov'
dependencies = []
files = []
hgrepos = []
issue_num = 31489
keywords = []
message_count = 7.0
messages = ['302321', '302323', '308652', '308670', '308677', '308678', '308696']
nosy_count = 4.0
nosy_names = ['pitrou', 'njs', 'yselivanov', 'Ilya.Kulakov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31489'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
It looks like a signal delivered to multiprocessing's process implicitly created by ProcessPoolExecutor triggers signal handler in the parent:

```
from concurrent.futures import ProcessPoolExecutor
import asyncio
import os
import signal
import sys
import time


def background_task():
    print(f"Running background task {os.getpid()}", file=sys.stderr)
    time.sleep(15)
    print("Exiting background task", file=sys.stderr)


async def task():
    print("Running task")

    executor = ProcessPoolExecutor()
    with executor:
        loop = asyncio.get_event_loop()

        try:
            await loop.run_in_executor(executor, background_task)
        except asyncio.CancelledError:
            print("Cancelling task 1", file=sys.stderr)

            try:
                await asyncio.sleep(15)
            except asyncio.CancelledError:
                print("Cancelling task 2", file=sys.stderr)
                raise

            raise

def main():
    def terminate(coro):
        print(f"Terminating {os.getpid()}")
        coro.cancel()

    loop = asyncio.get_event_loop()
    t = asyncio.ensure_future(task())
    loop.add_signal_handler(signal.SIGTERM, terminate, t)

    try:
        print(f"Running {os.getpid()}", file=sys.stderr)
        loop.run_until_complete(t)
    finally:
        loop.run_until_complete(loop.shutdown_asyncgens())
        loop.close()


if __name__ == '__main__':
    main()
```

1. Normal execution:

> Running 1000
> Running task
> Running background task 9999
> Exiting background task

2. Sending SIGTERM to parent once:

> Running 1000
> Running task
> Running background task 9999

\< kill -s SIGTERM 9999

> Terminating 1000
> Cancelling task 1
> Exiting background task


3. Sending SIGTERM to parent twice:

> Running 1000
> Running task
> Running background task 9999

\< kill -s SIGTERM 1000

> Terminating 1000
> Cancelling task 1

\< kill -s SIGTERM 1000

> Terminating 1000
> Cancelling task 2
> Exiting background task


4. Sending SIGTERM to once to parent and once to child:

> Running 1000
> Running task
> Running background task 9999

\< kill -s SIGTERM 1000

> Terminating 1000
> Cancelling task 1

\< kill -s SIGTERM 9999

> Terminating 1000
> Cancelling task 2
> Exiting background task


As you can see, sending SIGTERM into a subprocess somehow triggered a signal handler inside a parent. This is unexpected.

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
I think either loop's signal handler should not be called from a subprocess or at the very least, os.getpid / os.getpgrp should report correctly.

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/94454
