### ISSUE TITLE
Add _PyType_Name()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75678]
BPO | [31497](https://bugs.python.org/issue31497)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka
PRs | <li>python/cpython#3630</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-17.19:19:07.876>
created_at = <Date 2017-09-17.16:33:09.095>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Add _PyType_Name()'
updated_at = <Date 2017-09-17.19:19:07.876>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-17.19:19:07.876>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-17.19:19:07.876>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-09-17.16:33:09.095>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31497
keywords = ['patch']
message_count = 3.0
messages = ['302373', '302376', '302380']
nosy_count = 2.0
nosy_names = ['rhettinger', 'serhiy.storchaka']
pr_nums = ['3630']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31497'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Proposed PR adds a helper function \_PyType_Name() which returns the last component of tp_name after dot. This allows to avoid duplication of the code.

I'm going to use this helper in more places in future for getting rid of hardcoded type names (bpo-27541, bpo-21861).

**Comment by rhettinger** [comment]
+1 This would clean-up the code a bit.

**Comment by serhiy-storchaka** [comment]
New changeset 4ab46d794961491ed185c195d53da7ee6a16e646 by Serhiy Storchaka in branch 'master':
bpo-31497: Add private helper \_PyType_Name(). (bpo-3630)
https://github.com/python/cpython/commit/4ab46d794961491ed185c195d53da7ee6a16e646
