### ISSUE TITLE
Wrong offset with IndentationError ("expected an indented block")

### ISSUE THREAD

**Issue by 1f7c169c-a6ad-45ae-b614-0d40d962c776** [python/cpython#75676]
BPO | [31495](https://bugs.python.org/issue31495)
--- | :---
Nosy | @blueyed, @vadmium, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-22.00:00:42.162>
created_at = <Date 2017-09-16.20:58:29.614>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'Wrong offset with IndentationError ("expected an indented block")'
updated_at = <Date 2019-03-22.00:00:42.160>
user = 'https://github.com/blueyed'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-22.00:00:42.160>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-22.00:00:42.162>
closer = 'cheryl.sabella'
components = ['Interpreter Core']
creation = <Date 2017-09-16.20:58:29.614>
creator = 'blueyed'
dependencies = []
files = []
hgrepos = []
issue_num = 31495
keywords = []
message_count = 3.0
messages = ['302354', '302356', '338574']
nosy_count = 3.0
nosy_names = ['blueyed', 'martin.panter', 'cheryl.sabella']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31495'
versions = ['Python 3.8']
```

</p></details>

**Comment by 1f7c169c-a6ad-45ae-b614-0d40d962c776** [comment]
Given the following file `t-expected-indent.py`:
```
if 1:
foo
```

python t-expected-indent.py reports:

```
  File "t-expected-indent.py", line 2
    foo
      ^
IndentationError: expected an indented block
```

However, it should get reported for column 1 instead of 3.

**Comment by vadmium** [comment]
Some relevant info I wrote in bpo-25677:

‘The caret points to the character \_before_ offset. . . . In some cases (e.g. the line “1 +”), the offset is the string index \_after_ the error. But in the case of “1;1 + 1 = 2”, offset is the index where the error (statement) begins.’

In this case it looks like the offset is of the end of the first word on the line that has the wrong indentation. The caret is positioned one position back, to point at the last character of that word.
