### ISSUE TITLE
assertion failure in ctypes in case an _anonymous_ attr appears outside _fields_

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75671]
BPO | [31490](https://bugs.python.org/issue31490)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3615</li><li>python/cpython#3774</li><li>python/cpython#3780</li><li>python/cpython#3952</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-12.15:02:42.915>
created_at = <Date 2017-09-16.09:57:38.930>
labels = ['ctypes', '3.7', 'type-crash']
title = 'assertion failure in ctypes in case an _anonymous_ attr appears outside _fields_'
updated_at = <Date 2017-10-12.15:02:42.914>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-12.15:02:42.914>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-12.15:02:42.915>
closer = 'serhiy.storchaka'
components = ['ctypes']
creation = <Date 2017-09-16.09:57:38.930>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31490
keywords = ['patch']
message_count = 6.0
messages = ['302331', '302363', '303091', '303108', '303908', '304243']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3615', '3774', '3780', '3952']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31490'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure:
import ctypes
class BadStruct(ctypes.Structure):
    \_fields_ = []
    \_anonymous_ = ['foo']
    foo = None


this is because MakeAnonFields() (in [Modules/_ctypes/stgdict.c](https://github.com/python/cpython/blob/main/Modules/_ctypes/stgdict.c)) goes over the
names specified in \_anonymous_, and looks each name up in the class by calling
PyObject_GetAttr().
in case an attribute of such a name is found (i.e. PyObject_GetAttr() succeeded),
MakeAnonFields() assumes that the attribute was created by MakeFields(), so it
asserts the type of the attribute is PyCField_Type.

however, PyObject_GetAttr() would succeed also in case it is a normal attribute
specified by the user, but isn't specified in \_fields_, as in the code above.
in such a case, the type of the attribute is not PyCField_Type, and so the
assertion fails.

**Comment by serhiy-storchaka** [comment]
New changeset 30b61b51e05d2d43e8e2e783b0a9df738535423b by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31490: Fix an assertion failure in ctypes in case an \_anonymous_ attr is defined only outside \_fields_. (bpo-3615)
https://github.com/python/cpython/commit/30b61b51e05d2d43e8e2e783b0a9df738535423b

**Comment by serhiy-storchaka** [comment]
New changeset bdb215b18a42360b6a9c82876fa71f19ca1a416d by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31490: Fix an assertion failure in ctypes in case an \_anonymous_ attr is defined only outside \_fields_. (GH-3615) (bpo-3774)
https://github.com/python/cpython/commit/bdb215b18a42360b6a9c82876fa71f19ca1a416d

**Comment by serhiy-storchaka** [comment]
New changeset 9bfa55bfea60553831e99dbbca6a7c7d1065fd4b by Serhiy Storchaka (Miss Islington (bot)) in branch '2.7':
[2.7] bpo-31490: Fix an assertion failure in ctypes in case an \_anonymous_ attr is defined only outside \_fields_. (GH-3615) (bpo-3780)
https://github.com/python/cpython/commit/9bfa55bfea60553831e99dbbca6a7c7d1065fd4b

**Comment by serhiy-storchaka** [comment]
In 2.7 "%U" is not recognized in the format string.

```pycon
>>> class Name(Structure):
...     _fields_ = []
...     _anonymous_ = ["x"]
...     x = 42
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: '%U' is specified in _anonymous_ but not in _fields_
```

**Comment by serhiy-storchaka** [comment]
New changeset fb3bb8d5d5d70acaaa0fdec15c137544fdd4463f by Serhiy Storchaka (Oren Milman) in branch '2.7':
[2.7] bpo-31490: Fix an assertion failure in ctypes in case an \_anonymous_ attr is defined only outside \_fields_. (GH-3615) (bpo-3952)
https://github.com/python/cpython/commit/fb3bb8d5d5d70acaaa0fdec15c137544fdd4463f
