### ISSUE TITLE
Default values for zero in time.strftime()

### ISSUE THREAD

**Issue by 1cb85035-97d8-42c3-a287-2706aee5fe65** [python/cpython#75679]
BPO | [31498](https://bugs.python.org/issue31498)
--- | :---
Nosy | @brettcannon, @abalkin, @bitdancer, @denis-osipov

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brettcannon'
closed_at = <Date 2017-09-20.08:58:29.396>
created_at = <Date 2017-09-17.17:06:56.947>
labels = ['interpreter-core', 'invalid', 'type-bug', '3.7']
title = 'Default values for zero in time.strftime()'
updated_at = <Date 2017-09-20.08:58:29.395>
user = 'https://github.com/denis-osipov'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-20.08:58:29.395>
actor = 'denis-osipov'
assignee = 'brett.cannon'
closed = True
closed_date = <Date 2017-09-20.08:58:29.396>
closer = 'denis-osipov'
components = ['Interpreter Core']
creation = <Date 2017-09-17.17:06:56.947>
creator = 'denis-osipov'
dependencies = []
files = []
hgrepos = []
issue_num = 31498
keywords = []
message_count = 9.0
messages = ['302374', '302452', '302472', '302500', '302525', '302548', '302551', '302554', '302584']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'belopolsky', 'r.david.murray', 'denis-osipov']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31498'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Now default values for zero in time.strftime returns string with day of week value 1:

```pycon
>>> time.strftime("%Y %m %d %H %M %S %w %j", (2000,)+(0,)*8)
'2000 01 01 00 00 00 1 001'
```


while 2000-01-01 is Saturday (=6th day of week).

Now each illegal value (day of month \< 1 etc.) are forced to a correct one (by the way why now day of week isn't 0=Sunday and forced to 1). Maybe strftime also should force day of week to according to the date (%Y %m %d) if it's given.

```pycon
>>> time.strftime("%Y %m %d %H %M %S %w %j", (2000,)+(0,)*8)
'2000 01 01 00 00 00 6 001'
```

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
If it's really a bug I could make PR with changes in timemodule.c (in gettmarg() and checktm() functions). But I'm not sure that it's not intended behavior.

**Comment by bitdancer** [comment]
Generally we're just reporting whatever the platform strftime does.  Is that what happens in this case?

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
It seems strange to me that time.strftime() returns formatted date with wrong day of week and day of year values. So, I think it's probably a bug.
But I'm just learning Python and programming and I think that it can be intentional behavior.
If it's a bug I'd like to try to fix it. Otherwise could someone tell me why this behavior is OK?

**Comment by bitdancer** [comment]
Well, the first question that needs to be answered is: if you call the C strftime with the same arguments, what result do you get?  Because if it is the C strftime doing this, then it is not a bug in Python, whether it is correct behavior or not.

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Yes, C strftime returns the same. Inside of Python time.strftime() in Windows we give struct tm with inconsistent attributes (year, mon, mday and wday,yday) as argument for C strftime().

Before it timemodule does a lot of work to parse arguments of time.strftime() and check if all values in obtained struct tm are correct. Also it force values of some attributes to correct ones. Why don't make one more step (e.g. call C mktime before C strftime) to give C function a struct time argument with all consistent attributes?

Or Python time.strftime() should return exactly the same as C strftime?

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Actually now Python time.strftime not always returns the same value as C strftime with the same arguments, because timemodule make some refining of raw argument values to avoid errors.

**Comment by bitdancer** [comment]
Yes, I think we can "fix" some things.  I don't know if this falls into the class of things we should fix.  I'll leave that decision to people with more experience with time stuff.

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
Thank you for your answers. It's what I want to know. It looks like I shouldn't try to fix (to break) something that works well enough.

If nobody minds I'll close the issue with not a bug resolution.
