### ISSUE TITLE
assertion failure in json, in case _json.make_encoder() received a bad encoder() argument

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75686]
BPO | [31505](https://bugs.python.org/issue31505)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3643</li><li>python/cpython#3777</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.05:41:43.824>
created_at = <Date 2017-09-18.08:57:43.748>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in json, in case _json.make_encoder() received a bad encoder() argument'
updated_at = <Date 2017-09-27.05:41:43.823>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.05:41:43.823>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.05:41:43.824>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-18.08:57:43.748>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31505
keywords = ['patch']
message_count = 3.0
messages = ['302428', '302836', '303094']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3643', '3777']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31505'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure:

```py
import _json
def _bad_encoder(*args):
    return None

enc = _json.make_encoder(None, None, _bad_encoder, None,
                         'foo', 'bar', None, None, None)

enc(obj='spam', _current_indent_level=4)
```



This is because encoder_new() (in [Modules/_json.c](https://github.com/python/cpython/blob/main/Modules/_json.c)) assumes that the received
encoder() argument is a function that returns a string, and stores it in the
new PyEncoderObject.
When encoder_encode_string() is called (by encoder_listencode_obj()), it
returns whatever the stored encoder() returned, assuming it returned a string.
Then, encoder_listencode_obj() passes this value to \_steal_accumulate(), which
passes it to \_PyAccu_Accumulate(), which asserts it is a string.


Similarly, the following code also causes an assertion failure (only the obj
argument is different):

```py
import _json
def _bad_encoder(*args):
    return None

enc = _json.make_encoder(None, None, _bad_encoder, None,
                         'foo', 'bar', None, None, None)

enc(obj={'spam': 42}, _current_indent_level=4)
```



In this case, encoder_listencode_dict() passes whatever encoder_encode_string()
returned, to \_PyAccu_Accumulate(), which asserts it is a string.

**Comment by serhiy-storchaka** [comment]
New changeset 2b382dd6121bb1e4b75470fb3ef8555665df3eb6 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31505: Fix an assertion failure in json, in case \_json.make_encoder() received a bad encoder() argument. (bpo-3643)
https://github.com/python/cpython/commit/2b382dd6121bb1e4b75470fb3ef8555665df3eb6

**Comment by serhiy-storchaka** [comment]
New changeset 7c24e99c99c961e6633ac45390a211f65806c687 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31505: Fix an assertion failure in json, in case \_json.make_encoder() received a bad encoder() argument. (GH-3643) (bpo-3777)
https://github.com/python/cpython/commit/7c24e99c99c961e6633ac45390a211f65806c687
