### ISSUE TITLE
Enhance dir(module) to be informed by __all__ by updating module.__dir__

### ISSUE THREAD

**Issue by 7bf4b5f1-5975-4db8-95de-03ab3ac26821** [python/cpython#75684]
BPO | [31503](https://bugs.python.org/issue31503)
--- | :---
Nosy | @brettcannon, @rhettinger, @terryjreedy, @ncoghlan, @bitdancer, @serhiy-storchaka, @csabella, @codypiersall
PRs | <li>python/cpython#3610</li>
Superseder | <li>bpo-32225: Implement PEP 562: module __getattr__ and __dir__</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-12-21.23:21:07.122>
created_at = <Date 2017-09-18.02:20:36.031>
labels = ['type-feature', '3.7']
title = 'Enhance dir(module) to be informed by __all__ by updating module.__dir__'
updated_at = <Date 2018-12-21.23:21:07.121>
user = 'https://github.com/codypiersall'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-21.23:21:07.121>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2018-12-21.23:21:07.122>
closer = 'cheryl.sabella'
components = []
creation = <Date 2017-09-18.02:20:36.031>
creator = 'codypiersall'
dependencies = []
files = []
hgrepos = []
issue_num = 31503
keywords = []
message_count = 8.0
messages = ['302404', '302405', '302406', '302407', '302408', '302409', '302425', '332309']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'rhettinger', 'terry.reedy', 'ncoghlan', 'r.david.murray', 'serhiy.storchaka', 'cheryl.sabella', 'codypiersall']
pr_nums = ['3610']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '32225'
type = 'enhancement'
url = 'https://bugs.python.org/issue31503'
versions = ['Python 3.7']
```

</p></details>

**Comment by 7bf4b5f1-5975-4db8-95de-03ab3ac26821** [comment]
If a some_module defines \_\_all__, dir(some_module) should only return what is in \_\_all__.  This is already a mechanism that Python provides to specify module-level APIs.  Currently, dir(some_module) returns some_module.\_\_dict__.keys().

The concern with this enhancement is backwards compatibility.  It is conceivable that some library's code would be broken with the different return value of dir(some_module).  However, it seems unlikely that any code, other than tests, depends on the current behavior of dir(some_module).

If \_\_all__ is not defined in some_module, the old behavior is preserved.

**Comment by rhettinger** [comment]
I think  change this would be risky and could break code that uses dir() to actually know what is in a module.

IIRC, this was discussed when \_\_all__ was introduced. I believe it was decided that \_\_all__ would affect from-imports and help() but not dir().  This decision has been in place for a long time now and I would expect that people (and tools) have come to rely on the current behavior.

**Comment by terryjreedy** [comment]
Guido on python-ideas: I ave to agree with the other committers who already spoke up.

Me: I use dir to see the complete list now presently presented.  The presence or absence of  \_\_file__ indicates coded on Python or not.

IDLE module completion start with public items (I believe \_\_all__ or not start with \_).  Type '\_' and the complete list appears.  I think we should reject this.

**Comment by ncoghlan** [comment]
While I agree changing the default would be risky from a compatibility perspective, I do think it would be helpful to offer a straightforward way to filter out transitive imports and other non-public implementation details from the result of `dir(module)`, and require folks to use `list(vars(module).keys())` if they want a reliably complete listing of all global variables defined in a module.

The simplest spelling that comes to mind would be to allow people to write:

```py
    __dir__ = __all__
```


to get ``__all__`` to also affect the result of ``dir()``, permitting module authors to make their own determination as to whether they consider "The result of dir() includes non-public implementation details" to be covered by any backwards compatibility guarantees they might offer.

A less simple, but potentially more flexible, mechanism would be to require that to be spelled as:

```py
    def __dir__():
        return __all__
```


but I'm not sure the extra flexibility would be useful in any meaningful way (especially if one of the options for easier definition of dynamic module level properties were eventually adopted).

**Comment by ncoghlan** [comment]
As far the implementation goes, since the `__dir__` overload support in the `dir()` builtin ignores instance dictionaries, this could be implemented in module.__dir__ (or object.__dir__) rather than directly in the builtin.

Alternatively, it could use a different attribute name rather than having `__dir__` be a list of strings on instances, and a protocol method on classes.

If we went with a different name, then I think `__public__` would be a reasonable option, since the purpose of the attribute is to make it easy to programmatically distinguish public attributes from non-public ones (independently of the established leading underscore convention, which doesn't work well for transitive module references).

**Comment by serhiy-storchaka** [comment]
This would break tab completion of names not included in \_\_all__.

**Comment by ncoghlan** [comment]
Yes, that's one of the goals of the feature: to allow module authors to decide if they want tab completion for all attributes, or just the public API.
