### ISSUE TITLE
Operator precedence  description  for arithmetic operators

### ISSUE THREAD

**Issue by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [python/cpython#75682]
BPO | [31501](https://bugs.python.org/issue31501)
--- | :---
Nosy | @rhettinger, @Mariatta, @svelankar
PRs | <li>python/cpython#3633</li><li>python/cpython#3638</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-18.00:56:53.806>
created_at = <Date 2017-09-17.23:11:19.121>
labels = ['3.7', 'docs']
title = 'Operator precedence  description  for arithmetic operators'
updated_at = <Date 2017-09-19.22:48:33.514>
user = 'https://github.com/svelankar'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-19.22:48:33.514>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-18.00:56:53.806>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-09-17.23:11:19.121>
creator = 'svelankar'
dependencies = []
files = []
hgrepos = []
issue_num = 31501
keywords = ['patch']
message_count = 4.0
messages = ['302391', '302401', '302402', '302565']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'Mariatta', 'svelankar']
pr_nums = ['3633', '3638']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31501'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 6394ae25-ec38-4bb4-ae9f-c7fd49375561** [comment]
Description for the operator precedence should read 
"Multiplication, matrix multiplication division, remainder" instead of 

"Multiplication, matrix multiplication, division, floor division, remainder.

Section 6.16. Operator precedence

I feel this would help a new comer to python to instantly figure out what does "//" stand for.

**Comment by rhettinger** [comment]
This is a reasonable proposal.

**Comment by rhettinger** [comment]
New changeset 9b47af65375fab9318e88ccb061394a36c8c6c33 by Raymond Hettinger (svelankar) in branch 'master':
bpo-31501: Operator precedence  description  for arithmetic operators (bpo-3633)
https://github.com/python/cpython/commit/9b47af65375fab9318e88ccb061394a36c8c6c33

**Comment by Mariatta** [comment]
New changeset e2593aa673c0347a74c4896a519e3b8cb7b55eb4 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31501: Operator precedence description for arithmetic operators (GH-3633) (GH-3638)
https://github.com/python/cpython/commit/e2593aa673c0347a74c4896a519e3b8cb7b55eb4
