### ISSUE TITLE
Documentation for return value for string.rindex is missing when search string is empty

### ISSUE THREAD

**Issue by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [python/cpython#75685]
BPO | [31504](https://bugs.python.org/issue31504)
--- | :---
Nosy | @rhettinger, @bitdancer, @vadmium, @serhiy-storchaka, @vedgar, @kgashok
PRs | <li>python/cpython#3642</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-31.18:34:20.146>
created_at = <Date 2017-09-18.08:04:47.139>
labels = ['type-bug', 'docs']
title = 'Documentation for return value for string.rindex is missing when search string is empty'
updated_at = <Date 2020-10-31.19:44:47.402>
user = 'https://github.com/kgashok'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-31.19:44:47.402>
actor = 'veky'
assignee = 'docs@python'
closed = True
closed_date = <Date 2020-10-31.18:34:20.146>
closer = 'iritkatriel'
components = ['Documentation']
creation = <Date 2017-09-18.08:04:47.139>
creator = 'kgashok'
dependencies = []
files = []
hgrepos = []
issue_num = 31504
keywords = ['patch']
message_count = 15.0
messages = ['302418', '302421', '302422', '302424', '302427', '302431', '302435', '302436', '302437', '302438', '302443', '302444', '302455', '302465', '380092']
nosy_count = 7.0
nosy_names = ['rhettinger', 'r.david.murray', 'docs@python', 'martin.panter', 'serhiy.storchaka', 'veky', 'kgashok']
pr_nums = ['3642']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31504'
versions = ['Python 3.6']
```

</p></details>

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
"abcde".rindex("") returns 5
"a".rindex("") returns 1 

This is not documented anywhere in the Python documentation.

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
Also, "".rindex("") returns 0

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
string.find() also exhibits the same behaviour.

"abcde".find("") -\> 5 which also is not documented anywhere.

**Comment by serhiy-storchaka** [comment]
This is documented.

"Return the highest index in the string where substring sub is found,"

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
The documentation (https://docs.python.org/3/library/stdtypes.html#str.find) does not describe what will be the behaviour if the substring is "". 

And by the way, as per https://docs.python.org/3/reference/expressions.html#membership-test-operations, 

    Empty strings are always considered to be a substring of any other 
    string, so "" in "abc" will return True.

Returning an invalid index value, although confusing, should at least be documented in some form.

**Comment by vadmium** [comment]
The behaviour for searching for empty strings in Python is inconsistent; see bpo-24243. IMO the behaviour for the (r)find/index methods is sensible, but it is worth making the documentation explicit.

The returned indexes you have given (5, 1, and 0) are valid for slicing.

**Comment by serhiy-storchaka** [comment]
The documentation doesn't mention empty string specially because there is nothing special with empty string.

Returned index value is valid. "abcde"[5:5] == "".

bpo-24243 is about the case of end \< start. Not this case.

I don't see a bug here.

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
I am not saying that there is a bug. As Martin points out, "it is worth making the documentation explicit."

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
How about 

```pytb
"abcde"[5]
Traceback (most recent call last):
  File "python", line 1, in <module>
IndexError: string index out of range
```

**Comment by serhiy-storchaka** [comment]
5 is not valid index of character, but it is valid index of substring.

IMHO documenting explicitly miscellaneous particular cases which are not exceptions of general rules just adds a noise. This makes the documentation larger and decrease the chance that it will be read.

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
Look at my suggested changes. It doesn't add noise, IMHO.

All I am saying is that the explicit behaviour needs to be documented. 
I unnecessarily wasted at least 3-4 hours on this "undocumented" behavior.

**Comment by 7d1b28b3-ccc0-4dc5-910a-1f50404e0852** [comment]
@Storchaka, 

You say `5` is related to the substring. Pray, explain how 5 is related to a null substring? Also, from https://bugs.python.org/msg243710, as per the great Hettinger:

   Though this is closed as not a bug, feel free to add an example or a 
   mention in the documentation.  Keep it short though.  

That's all I am asking to be included.

**Comment by fe5a23f9-4d47-49f8-9fb5-d6fbad5d9e38** [comment]
This is nonsense. 'abcde'[7:7] is also ''. So the maximal index in fact doesn't exist. What do you think exactly is the property that differentiates 5 from 7 here?

**Comment by bitdancer** [comment]
You have to remember that the most useful way to think about python slice indexes is that they point between characters. Consider, for example, that you have a starting index of something, and you are looking backward in the string for a trailing delimiter:

```pycon
  >>> x = 'this is <weird example> of something'
  >>> x.rfind('>', 9)
  22
  >>> x[9:22]
  'weird example'
```


So the above is why 5 is different from 7: 5 is the index that you would use in a slice if you wanted the string that ended before the match...and the match in the null string case is the end of the string.  That is, Python is being consistent in this degenerate case.
