### ISSUE TITLE
Improve the error message logic for object_new & object_init

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#75687]
BPO | [31506](https://bugs.python.org/issue31506)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka, @CuriousLearner, @miss-islington, @tirkarthi, @ppt000
PRs | <li>python/cpython#3650</li><li>python/cpython#4740</li><li>python/cpython#11641</li><li>python/cpython#11641</li><li>python/cpython#11641</li><li>python/cpython#11939</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-19.13:48:34.176>
created_at = <Date 2017-09-18.09:44:09.052>
labels = ['interpreter-core', 'easy', 'type-feature', '3.7']
title = 'Improve the error message logic for object_new & object_init'
updated_at = <Date 2019-02-19.13:48:34.173>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-19.13:48:34.173>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2019-02-19.13:48:34.176>
closer = 'ncoghlan'
components = ['Interpreter Core']
creation = <Date 2017-09-18.09:44:09.052>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 31506
keywords = ['patch', 'easy (C)']
message_count = 28.0
messages = ['302439', '302445', '302446', '302448', '302453', '302462', '302503', '302586', '302587', '302593', '302596', '302599', '307676', '307678', '307679', '307699', '307932', '307933', '308018', '308063', '309464', '326091', '326225', '330500', '335943', '335945', '335946', '335947']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'serhiy.storchaka', 'CuriousLearner', 'miss-islington', 'xtreak', 'ppt000']
pr_nums = ['3650', '4740', '11641', '11641', '11641', '11939']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31506'
versions = ['Python 3.7']
```

</p></details>

**Comment by ncoghlan** [comment]
As described in https://blog.lerner.co.il/favorite-terrible-python-error-message/, object_new and object_init currently have "object" hardcoded in the error messages they raise for excess parameters:


```pycon
>>> class C: pass
... 
>>> C(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object() takes no parameters
>>> c = C()
>>> c.__init__(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object.__init__() takes no parameters
```


This hardcoding makes sense for the case where that particular method has been overridden, and the interpreter is reporting an error in the subclass's call up to the base class, rather than in the call to create an instance of the subclass:

```pycon
>>> class D:
...     def __init__(self, *args):
...         return super().__init__(*args)
... 
>>> D(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in __init__
TypeError: object.__init__() takes no parameters
```



However, it's misleading in the case where object_new is reporting an error because it knows object_init hasn't been overridden (or vice-versa), and hence won't correctly accept any additional arguments: in those cases, it would be far more useful to report "type-\>tp_name" in the error message, rather than hardcoding "object".

If we split the error message logic that way, then the first two examples above would become:

```pycon
>>> class C: pass
... 
>>> C(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: C() takes no parameters
>>> c = C()
>>> c.__init__(10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: C.__init__() takes no parameters
```


while the subclassing cases would be left unchanged.

**Comment by serhiy-storchaka** [comment]
Not sure this is easy issue. It requires taking to account many different cases and analyzing many arguments checking code scattered around many files.

**Comment by ncoghlan** [comment]
Fortunately, the logic is already well encapsulated: there's a "if (excess_args && (case A || case B)) {... report error ...}" check at the start of each of object_new and object_init, where "case A" = "the other function in the object_new/object_init pair has \*not* been overriden" and "case B" is "this function \*has* been overridden".

That means the only change needed is to include the type name in an updated error message in case A, while retaining the current error messages for case B.

**Comment by serhiy-storchaka** [comment]
It is not so easy to make an error message conforming with error messages for similar types. This may require changing error messages in other code.

First, "takes no arguments" instead of "takes no parameters".

For normal \_\_new__ and \_\_init__ you never got "takes no arguments". They  take at least one argument -- a class or an instance.

```pycon
>>> tuple.__new__(tuple, 1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: tuple expected at most 1 arguments, got 4
>>> list.__init__([], 1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: list expected at most 1 arguments, got 4
>>> class C:
...     def __new__(cls): return object.__new__(cls)
...     def __init__(self): pass
... 
>>> C.__new__(C, 1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __new__() takes 1 positional argument but 5 were given
>>> C.__init__(C(), 1, 2, 3, 4)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 5 were given
```

**Comment by ncoghlan** [comment]
For this issue, I'm not proposing to make any change other than to solve the specific problem reported in the blog post: when the method itself isn't overridden, then the error message should report the name of the most derived class, not "object", to help users more readily find the likely source of their problem (a missing "\_\_init__" method definition).

Making these custom errors consistent with Python 3's otherwise improved argument unpacking errors would be a separate issue (and I agree \*that* change wouldn't qualify as being easy).

**Comment by serhiy-storchaka** [comment]
What do you expect for:

```py
class C: pass

object.__new__(C, 1)
C.__new__(C, 1)
```

**Comment by ncoghlan** [comment]
Those would both report "C() takes no parameters" without further enhancements (which would be out of scope for this issue).

The proposed improvement here isn't "Let's make the error message exactly correct in all cases" (that's probably impossible, since we've lost relevant information by the time the argument processing happens).

Instead, it's "let's make the error message more helpful in the most common case for beginners, and let the folks performing the more advanced operation of calling \_\_new__ directly do the translation if they need to"

**Comment by ncoghlan** [comment]
New changeset a6c0c0695614177c8b6e1840465375eefcfee586 by Nick Coghlan (Serhiy Storchaka) in branch 'master':
bpo-31506: Improve the error message logic for object.\_\_new__ and object.\_\_init__. (GH-3650)
https://github.com/python/cpython/commit/a6c0c0695614177c8b6e1840465375eefcfee586

**Comment by ncoghlan** [comment]
Reopening, as I was a little hasty with the merge button: the merged PR *also* changed the `__init__` error message to drop the method name, but I don't think that's what we want.

I'm also wondering if we should change the up-call case to \*always* report the method name.

That is, we'd implement the following revised behaviour:

```py
    # Without any method overrides
    class C:
        pass
```


    C(42) -> "TypeError: C() takes no arguments"
    C.__new__(42) -> "TypeError: C() takes no arguments"
    C().__init__(42) -> "TypeError: C.__init__() takes no arguments"
    # These next two quirks are the price we pay for the nicer errors above
    object.__new__(C, 42) -> "TypeError: C() takes no arguments"
    object.__init__(C(), 42) -> "TypeError: C.__init__() takes no arguments"

```py
    # With method overrides
    class D:
        def __new__(cls, *args, **kwds):
            super().__new__(cls, *args, **kwds)
        def __init__(self, *args, **kwds):
            super().__init__(*args, **kwds)
```


    D(42) -> "TypeError: object.__new__() takes no arguments"
    D.__new__(42) -> "TypeError: object.__new__() takes no arguments"
    D().__init__(42) -> "TypeError: object.__init__() takes no arguments"
    object.__new__(C, 42) -> "TypeError: object.__new__() takes no arguments"
    object.__init__(C(), 42) -> "TypeError: object.__init__() takes no arguments"

**Comment by ncoghlan** [comment]
I filed bpo-31527 as a follow-up issue to see whether or not it might be possible to amend the way these custom errors are generated to benefit from the work that has gone into improving the error responses from PyArg_ParseTupleAndKeywords.

**Comment by serhiy-storchaka** [comment]
C.\_\_new__(42) emits different error, "TypeError: object.\_\_new__(X): X is not a type object (int)". Perhaps you meant C.\_\_new__(C, 42) which now emits "TypeError: C() takes no arguments".

Messages "object.\_\_new__() takes no arguments" and "object.\_\_init__() takes no arguments" are not correct since both object.\_\_new__() and object.\_\_init__() take one argument -- a class and an instance correspondingly.

**Comment by ncoghlan** [comment]
Aye, the "C.\_\_new__" example omitting the first arg was just an error in that example.

And that's a good point about the current "object.\_\_init__()" error message actually being incorrect, since the \*methods* each take exactly one argument - it's only the "object(*args, \*\*kwds)" form that genuinely expects zero arguments.

If we were to correct that error as well, we'd end up with the following:

```py
    # Without any method overrides
    class C:
        pass
```


    C(42) -> "TypeError: C() takes no arguments"
    C.__new__(C, 42) -> "TypeError: C() takes no arguments"
    C().__init__(42) -> "TypeError: C.__init__() takes exactly one argument"
    # These next two quirks are the price we pay for the nicer errors above
    object.__new__(C, 42) -> "TypeError: C() takes no arguments"
    object.__init__(C(), 42) -> "TypeError: C.__init__() takes exactly one argument"

```py
    # With method overrides
    class D:
        def __new__(cls, *args, **kwds):
            super().__new__(cls, *args, **kwds)
        def __init__(self, *args, **kwds):
            super().__init__(*args, **kwds)
```


    D(42) -> "TypeError: object.__new__() takes exactly one argument"
    D.__new__(D, 42) -> "TypeError: object.__new__() takes exactly one argument"
    D().__init__(42) -> "TypeError: object.__init__() takes exactly one argument"
    object.__new__(C, 42) -> "TypeError: object.__new__() takes exactly one argument"
    object.__init__(C(), 42) -> "TypeError: object.__init__() takes exactly one argument"
