### ISSUE TITLE
email.utils.parseaddr has no docstring

### ISSUE THREAD

**Issue by mdickinson** [python/cpython#75688]
BPO | [31507](https://bugs.python.org/issue31507)
--- | :---
Nosy | @warsaw, @mdickinson, @bitdancer, @Mariatta, @kwarunek, @AstroCat84
PRs | <li>python/cpython#3647</li><li>python/cpython#3733</li><li>python/cpython#3735</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-07.05:31:55.497>
created_at = <Date 2017-09-18.09:52:35.349>
labels = ['3.7', 'easy', 'type-bug', 'library', 'expert-email']
title = 'email.utils.parseaddr has no docstring'
updated_at = <Date 2017-10-07.05:31:55.496>
user = 'https://github.com/mdickinson'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-07.05:31:55.496>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-07.05:31:55.497>
closer = 'Mariatta'
components = ['Library (Lib)', 'email']
creation = <Date 2017-09-18.09:52:35.349>
creator = 'mark.dickinson'
dependencies = []
files = []
hgrepos = []
issue_num = 31507
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['302442', '302459', '302461', '302468', '302560', '303869']
nosy_count = 6.0
nosy_names = ['barry', 'mark.dickinson', 'r.david.murray', 'Mariatta', 'kwarunek', 'rohitb']
pr_nums = ['3647', '3733', '3735']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31507'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by mdickinson** [comment]
While demonstrating email.utils.parseaddr in a recent training course, I discovered it had no docstring (see below). This looks as though it should be an easy fix for a first-time contributor.

taniyama:Desktop mdickinson$ ipython
Python 3.6.2 (default, Jul 24 2017, 13:17:39) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from email.utils import parseaddr

In [2]: parseaddr?
Signature: parseaddr(addr)
Docstring: \<no docstring\>
File:      /opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/email/utils.py
Type:      function

**Comment by 43a930ce-92ff-472e-b021-f9644eabb63f** [comment]
As well as `parsedate_to_datetime`... I'll work on that

**Comment by 49058fd9-7512-4dec-8444-d2846b20c39c** [comment]
I have submitted a pull request for the changes to email.utils.parseaddr.

**Comment by bitdancer** [comment]
Mark: re your training course...if you aren't trying to stay compatible with python2, note that python3 has a much more sophisticated address parser now, that gets called automatically if you use the new policies.

**Comment by bitdancer** [comment]
New changeset 9e7b9b21fe45f7d93eaf9382fedfa18247d0d2b2 by R. David Murray (Rohit Balasubramanian) in branch 'master':
bpo-31507 Add docstring to parseaddr function in email.utils.parseaddr (gh-3647)
https://github.com/python/cpython/commit/9e7b9b21fe45f7d93eaf9382fedfa18247d0d2b2

**Comment by Mariatta** [comment]
New changeset 93c0885dc84381cbbb970402b1a21bf690ee312c by Mariatta (Rohit Balasubramanian) in branch '3.6':
bpo-31507 Add docstring to parseaddr function in email.utils.parseaddr (GH-3647) (GH-3733)
https://github.com/python/cpython/commit/93c0885dc84381cbbb970402b1a21bf690ee312c
