### ISSUE TITLE
test_many_processes() of test_multiprocessing_spawn failed on x86-64 Sierra 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75691]
BPO | [31510](https://bugs.python.org/issue31510)
--- | :---
Nosy | @pitrou, @vstinner
PRs | <li>python/cpython#3857</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-02.15:38:08.493>
created_at = <Date 2017-09-18.16:19:32.110>
labels = ['3.7', 'tests']
title = 'test_many_processes() of test_multiprocessing_spawn failed on x86-64 Sierra 3.x'
updated_at = <Date 2017-10-02.15:38:08.492>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-02.15:38:08.492>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-02.15:38:08.493>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-09-18.16:19:32.110>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31510
keywords = ['patch']
message_count = 8.0
messages = ['302469', '302537', '302680', '302681', '303535', '303536', '303538', '303544']
nosy_count = 2.0
nosy_names = ['pitrou', 'vstinner']
pr_nums = ['3857']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31510'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
The process was killed (SIGKILL).

See also bpo-30356.

http://buildbot.python.org/all/builders/x86-64%20Sierra%203.x/builds/765/steps/test/logs/stdio

\======================================================================
FAIL: test_many_processes (test.test_multiprocessing_spawn.WithProcessesTestProcess)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/buildbot/buildarea/3.x.billenstein-sierra/build/Lib/test/_test_multiprocessing.py", line 505, in test_many_processes
    self.assertEqual(p.exitcode, -signal.SIGTERM)
AssertionError: -9 != -15
```

**Comment by vstinner** [comment]
I failed to reproduce the bug on Linux.

**Comment by vstinner** [comment]
test_many_processes() test was added by Antoine Pitrou in bpo-30589. This test was mentionned in bpo-30703.

**Comment by vstinner** [comment]
test_many_processes() is made in two steps. The bug occurs at the second step which calls proc.terminate() on processes. Code of the test:

```py
    @classmethod
    def _sleep_some(cls):
        time.sleep(100)

    @classmethod
    def _test_sleep(cls, delay):
        time.sleep(delay)

    def test_many_processes(self):
        if self.TYPE == 'threads':
            self.skipTest('test not appropriate for {}'.format(self.TYPE))

        sm = multiprocessing.get_start_method()
        N = 5 if sm == 'spawn' else 100

        # Try to overwhelm the forkserver loop with events
        procs = [self.Process(target=self._test_sleep, args=(0.01,))
                 for i in range(N)]
        for p in procs:
            p.start()
        for p in procs:
            join_process(p)
        for p in procs:
            self.assertEqual(p.exitcode, 0)

        procs = [self.Process(target=self._sleep_some)
                 for i in range(N)]
        for p in procs:
            p.start()
        time.sleep(0.001)  # let the children start...
        for p in procs:
            p.terminate()
        for p in procs:
            join_process(p)
        if os.name != 'nt':
            for p in procs:
                self.assertEqual(p.exitcode, -signal.SIGTERM) # <--- HERE
```


I'm not sure about the "time.sleep(0.001)  # let the children start...". It looks like a weak synchronization. Maybe if the system is heavily loaded, the signal is sent before Python registered signal handlers? 1 ms seems short to start Python. On my Linux laptop, it's closer to 15 ms.

**Comment by pitrou** [comment]
> It looks like a weak synchronization.

It is.  I don't remember exactly why I had to add this, I can't reproduce any issue without it anymore...

> the signal is sent before Python registered signal handlers?

Python signal handlers are not relevant here, we're sending SIGTERM which kills the process.

**Comment by pitrou** [comment]
It seems other people have similar issues:
https://github.com/libuv/libuv/issues/1226

Perhaps we need to relax the test on OSX :-/

**Comment by vstinner** [comment]
Antoine: "It seems other people have similar issues: https://github.com/libuv/libuv/issues/1226 Perhaps we need to relax the test on OSX :-/"

Oh thanks for the confirmation. I proposed a patch to accept -SIGKILL on macOS: [PR 3857](https://github.com/python/cpython/pull/3857).

**Comment by vstinner** [comment]
New changeset e6cfdefa0c2f5bda177e49b228c2c7528f7c239c by Victor Stinner in branch 'master':
bpo-31510: Fix multiprocessing test_many_processes() on macOS (bpo-3857)
https://github.com/python/cpython/commit/e6cfdefa0c2f5bda177e49b228c2c7528f7c239c
