### ISSUE TITLE
Document structure of memo dictionary to enable more advanced __deepcopy__ uses

### ISSUE THREAD

**Issue by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [python/cpython#75694]
BPO | [31513](https://bugs.python.org/issue31513)
--- | :---
Nosy | @bitdancer, @MojoVampire

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-18.20:24:48.695>
created_at = <Date 2017-09-18.20:05:46.694>
labels = ['invalid', 'docs']
title = 'Document structure of memo dictionary to enable more advanced __deepcopy__ uses'
updated_at = <Date 2017-09-18.20:24:48.693>
user = 'https://github.com/MojoVampire'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-18.20:24:48.693>
actor = 'r.david.murray'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-18.20:24:48.695>
closer = 'r.david.murray'
components = ['Documentation']
creation = <Date 2017-09-18.20:05:46.694>
creator = 'josh.r'
dependencies = []
files = []
hgrepos = []
issue_num = 31513
keywords = []
message_count = 2.0
messages = ['302485', '302486']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'docs@python', 'josh.r']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31513'
versions = []
```

</p></details>

**Comment by 99ffcaa5-b43b-4e8e-a35e-9c890007b9cd** [comment]
At present, the documentation for the copy module doesn't document anything about the memo dictionary for deepcopy except to say that it must be received by custom \_\_deepcopy__ methods and passed along when calling copy.deepcopy, and that it is a "dictionary of objects already copied during the current copying pass", without specifying what the keys or values are.

Without providing a documented meaning for the keys and values in the memo dict, it's impossible to use it in a supported way for more complex cases (e.g. a case where the object must be created partially and memoized prior to deepcopying attributes that can self-reference). For an example, see this StackOverflow answer's approach to using \_\_deepcopy__: https://stackoverflow.com/a/46284091/364696

Officially, the line where it does:

memo[id(self)] = newself = self.\_\_class__(copy.deepcopy(self.id, memo))

is not using documented behavior AFAICT; the fact that the memo dict maps id()'s of the original objects to the new instance is undocumented. This wouldn't be so bad if there were a documented way to achieve the desired result, but in recursive cases like these it's the only way to add deepcopy support without also adding pickle support.

I'd suggest documenting the current behavior, assuming the current behavior is consistent on all alternate Python implementations; I know id() is a little funky elsewhere, but I'm not sure there is any other sane implementation.

**Comment by bitdancer** [comment]
Unless I'm mistaken (and someone will correct me and reopen the issue if I am :) it is intentionally undocumented.  A proposal for a documented protocol of some sort is certainly a possibility, but is something that should start with a discussion on the python-ideas mailing list.
