### ISSUE TITLE
test_subprocess hangs randomly on AMD64 Windows10 3.x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75690]
BPO | [31509](https://bugs.python.org/issue31509)
--- | :---
Nosy | @vstinner, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-13.13:55:14.819>
created_at = <Date 2017-09-18.16:16:13.377>
labels = ['3.7']
title = 'test_subprocess hangs randomly on AMD64 Windows10 3.x'
updated_at = <Date 2017-10-13.13:55:14.818>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-13.13:55:14.818>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-13.13:55:14.819>
closer = 'vstinner'
components = []
creation = <Date 2017-09-18.16:16:13.377>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31509
keywords = []
message_count = 4.0
messages = ['302467', '302608', '304306', '304339']
nosy_count = 2.0
nosy_names = ['vstinner', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31509'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/builders/AMD64%20Windows10%203.x/builds/1242/steps/test/logs/stdio

0:49:36 [401/405] test_osx_env passed
0:49:38 [402/405] test_fractions passed -- running: test_subprocess (31 sec)
0:49:51 [403/405] test_importlib passed -- running: test_subprocess (44 sec)
0:49:53 [404/405] test_pwd skipped -- running: test_subprocess (46 sec)
test_pwd skipped -- No module named 'pwd'

command timed out: 1200 seconds without output running ['Tools\\\\buildbot\\\\test.bat', '-x64', '-j2', '--timeout', '900'], attempting to kill
program finished with exit code 1
elapsedTime=4198.024000

See also bpo-30885.

**Comment by vstinner** [comment]
As expected, I'm unable to reproduce the bug on my Windows VM, even using --forever during 1 hour:
python -m test test_subprocess -v --timeout=120 --forever.

**Comment by ned-deily** [comment]
I also have seen test_subprocess hangs on both macOS and on Debian Linux on both 3.6 and master, as recently as 3.6.3 and 3.7.0a1 but not with current heads.  After some experimenting and bisecting, I tracked the fix down to the mock os.waitpid fixes for bpo-31178 (git11045c9d8a and gitfae0512e58). So perhaps this issue can be closed.

**Comment by vstinner** [comment]
Ned: "I also have seen test_subprocess hangs on both macOS and on Debian Linux on both 3.6 and master, as recently as 3.6.3 and 3.7.0a1 but not with current heads.  After some experimenting and bisecting, I tracked the fix down to the mock os.waitpid fixes for bpo-31178 (git11045c9d8a and gitfae0512e58). So perhaps this issue can be closed."

Oh, that's a very good news. Thanks!
