### ISSUE TITLE
require sqlite3_prepare_v2

### ISSUE THREAD

**Issue by benjaminp** [python/cpython#75706]
BPO | [31525](https://bugs.python.org/issue31525)
--- | :---
Nosy | @benjaminp, @berkerpeksag, @miss-islington
PRs | <li>python/cpython#3666</li><li>python/cpython#12923</li><li>python/cpython#12972</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-20.14:36:20.661>
created_at = <Date 2017-09-20.01:47:44.689>
labels = ['extension-modules', '3.7']
title = 'require sqlite3_prepare_v2'
updated_at = <Date 2019-04-26.16:15:34.486>
user = 'https://github.com/benjaminp'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-26.16:15:34.486>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-20.14:36:20.661>
closer = 'benjamin.peterson'
components = ['Extension Modules']
creation = <Date 2017-09-20.01:47:44.689>
creator = 'benjamin.peterson'
dependencies = []
files = []
hgrepos = []
issue_num = 31525
keywords = ['patch']
message_count = 6.0
messages = ['302581', '302585', '302588', '302622', '340925', '340929']
nosy_count = 3.0
nosy_names = ['benjamin.peterson', 'berker.peksag', 'miss-islington']
pr_nums = ['3666', '12923', '12972']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31525'
versions = ['Python 3.7']
```

</p></details>

**Comment by benjaminp** [comment]
sqlite has had the sqlite3_prepare_v2 API for more than 10 years now. The sqlite module should switch to using it, which will let us delete some code for automatically recompiling statements.

**Comment by berkerpeksag** [comment]
We already use sqlite3_prepare_v2 if it's available: https://github.com/python/cpython/blob/master/Modules/_sqlite/util.h#L43

Do you want to use sqlite3_prepare_v2() unconditionally and drop support for older SQLite versions?

**Comment by benjaminp** [comment]
ermm, yes, I guess I was looking at an old version of the code.

**Comment by benjaminp** [comment]
New changeset 525269430a3f9fbb7287e4bb6b365ac216004980 by Benjamin Peterson in branch 'master':
closes bpo-31525: require sqlite3_prepare_v2 (bpo-3666)
https://github.com/python/cpython/commit/525269430a3f9fbb7287e4bb6b365ac216004980
