### ISSUE TITLE
ResourceWarning: unclosed <socket.socket [closed] fd=3, ...> warning

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75701]
BPO | [31520](https://bugs.python.org/issue31520)
--- | :---
Nosy | @vstinner, @vadmium

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.01:28:20.801>
created_at = <Date 2017-09-19.16:30:09.884>
labels = ['3.7', 'library']
title = 'ResourceWarning: unclosed <socket.socket [closed] fd=3, ...> warning'
updated_at = <Date 2017-11-24.01:28:20.800>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.01:28:20.800>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.01:28:20.801>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-09-19.16:30:09.884>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31520
keywords = []
message_count = 5.0
messages = ['302541', '302934', '302949', '302952', '306871']
nosy_count = 2.0
nosy_names = ['vstinner', 'martin.panter']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31520'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
\_socket.socket object destructor emits a ResourceWarning if the socket is not closed. 

The problem is this warning:

build/Lib/contextlib.py:60: ResourceWarning: unclosed \<socket.socket [closed] fd=3, family=AddressFamily.AF_INET, type=2049, proto=6\>
  self.gen = func(*args, \*\*kwds)

The message says "unclosed" and "closed" in the same sentence. It's confusing.

In fact, the Python module "socket" has a socket.socket class based on the \_socket.socket of the C module "\_socket".

The Python module has a private \_closed attribute set to True as soon as close() was closed. \*But* the underlying \_socket.socket.close() is only called once the "io refs" counter reachs zero.

The Python module allows to open to "fork" the socket using the makefile() method: the "io refs" counter is increased in that case. makefile() creates a raw socket.SocketIO() object which will call the close() method of the original socket.

Ok, let's come back at the C level. The \_socket.socket destructor checks if \_socket.socket.close() was called to decide if the ResourceWarning should be emitted or not.

Maybe SocketIO should raise the ResourceWarning?

IMHO the minimum patch is to modify socket.socket.\_\_repr__() to include the "io refs" counter. So a developer knowing the implementation can understand the surprising warning.

**Comment by vstinner** [comment]
socket.SocketIO inherits from io.RawIOBase which inherits from io.IOBase.

io.IOBase has a finalizer which calls the close() method. I tried to add a \_\_del__ method to socket.SocketIO, but the object was already closed by the finalizer.

io.FileIO uses a trick at the C level: it sets an internal "finalizing" attribute to check if close() was called by IOBase finalizer. If it's the case, a ResourceWarning is emitted.

I don't see a simpler way to emit a ResourceWarning in SocketIO. Maybe it's not the right approach.

**Comment by vadmium** [comment]
I’m curious how you manage to trigger the warning in the “closed” state. The Python I have handy is half a year out of date, but all my attempts to trigger the warning either produce the less confusing version,

ResourceWarning: unclosed \<socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('0.0.0.0', 0)\>

or there is no warning at all due IOBase.\_\_del__ (see bpo-19829).

If your SocketIO was wrapped in a BufferedReader/Writer/RWPair, then that could easily close the SocketIO object before SocketIO.\_\_del__ is called. You would also have to override the wrapper’s \_\_del__ method, rather than (or as well as) SocketIO.\_\_del__.

**Comment by vstinner** [comment]
> I’m curious how you manage to trigger the warning in the “closed” state.

It comes from Refleak buildbots. Example:

0:13:47 load avg: 3.24 [ 52/407] test_urllib2net passed (239 sec)
beginning 6 repetitions
123456
Resource 'http://www.imdb.com' is not available
/buildbot/buildarea/3.x.ware-gentoo-x86.refleak/build/Lib/test/libregrtest/refleak.py:253: ResourceWarning: unclosed \<socket.socket [closed] fd=3, family=AddressFamily.AF_INET, type=2049, proto=6\>
  gc.collect()
......

I failed to reproduce this exact warning. I don't know if it's related to the "Resource 'http://www.imdb.com' is not available" message.

**Comment by vstinner** [comment]
I'm not confortable to expose the value of the private \_io_refs attribute in repr(socket.socket). I'm not sure that anything should really be done here. I close the issue.
