### ISSUE TITLE
Negative number raised to even power is negative (-1 ** even = negative)

### ISSUE THREAD

**Issue by b8e5d9b9-c9df-471e-8ad1-06d1fe37549c** [python/cpython#75700]
BPO | [31519](https://bugs.python.org/issue31519)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-19.14:57:50.783>
created_at = <Date 2017-09-19.14:51:10.264>
labels = ['type-bug', 'invalid']
title = 'Negative number raised to even power is negative (-1 ** even = negative)'
updated_at = <Date 2017-09-19.15:13:21.417>
user = 'https://bugs.python.org/rdhunkins'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-19.15:13:21.417>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-19.14:57:50.783>
closer = 'r.david.murray'
components = []
creation = <Date 2017-09-19.14:51:10.264>
creator = 'rdhunkins'
dependencies = []
files = []
hgrepos = []
issue_num = 31519
keywords = []
message_count = 4.0
messages = ['302529', '302530', '302532', '302533']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'rdhunkins']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31519'
versions = ['Python 3.6']
```

</p></details>

**Comment by b8e5d9b9-c9df-471e-8ad1-06d1fe37549c** [comment]
Hello,
I'm only a novice with Python, so please take it easy on me if I have transgressed.

I am using Python 3.6.2 on a win10 64 bit machine, and entered this:

```pycon
>>> a= [-1 ** x for x in range(1,10)]
>>> print(a)
[-1, -1, -1, -1, -1, -1, -1, -1, -1]
which is not correct.
```


however, entering this:

```pycon
>>> b = [pow(-1, x) for x in range(1,10)]
>>> print(b)
[-1, 1, -1, 1, -1, 1, -1, 1, -1]
```


which is correct.
Any negative number entered and raised to an even power seems to not return a positive value, but the pow(x,y) function works.

I never have reported a bug on any programming language ever, and surprisingly I can't find a report of this (I did search, so if it's out there, I must not understand how to use the search. Forgive me. As I said, I'm very new to Python and I'm not a professional programmer.)

**Comment by bitdancer** [comment]
You are being tripped up by operator precedence:

```pycon
>>> -1**2
-1
>>> (-1)**2
1
```

**Comment by b8e5d9b9-c9df-471e-8ad1-06d1fe37549c** [comment]
Thanks. Stupid of me. Appreciate the correction.

**Comment by bitdancer** [comment]
It's a FAQ, but it was faster for me to just cut and paste than it was to look up the FAQ link :)
