### ISSUE TITLE
Dead link in SSLContext.set_ciphers documentation

### ISSUE THREAD

**Issue by 74276bb4-928d-42d2-ac2e-17266a3681b7** [python/cpython#75714]
BPO | [31533](https://bugs.python.org/issue31533)
--- | :---
Nosy | @pitrou, @tiran, @felipeochoa, @Mariatta
PRs | <li>python/cpython#3674</li><li>python/cpython#3675</li><li>python/cpython#3676</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-20.20:24:08.627>
created_at = <Date 2017-09-20.15:43:21.178>
labels = ['3.7', 'docs']
title = 'Dead link in SSLContext.set_ciphers documentation'
updated_at = <Date 2017-09-20.20:24:08.626>
user = 'https://github.com/felipeochoa'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-20.20:24:08.626>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-20.20:24:08.627>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-09-20.15:43:21.178>
creator = 'fov'
dependencies = []
files = []
hgrepos = []
issue_num = 31533
keywords = ['patch']
message_count = 12.0
messages = ['302629', '302632', '302634', '302635', '302636', '302638', '302639', '302644', '302648', '302656', '302657', '302658']
nosy_count = 5.0
nosy_names = ['pitrou', 'christian.heimes', 'docs@python', 'fov', 'Mariatta']
pr_nums = ['3674', '3675', '3676']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31533'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 74276bb4-928d-42d2-ac2e-17266a3681b7** [comment]
The link to the `OpenSSL cipher list format` 404s. I don't know if it's where the original meant to point, but the same information is available at https://wiki.openssl.org/index.php/Manual:Ciphers(1)#CIPHER_LIST_FORMAT

**Comment by Mariatta** [comment]
Where in the docs is this `OpenSSL cipher list format` link located?

**Comment by pitrou** [comment]
Mariatta, that would be in the documentation for the `SSLContext.set_ciphers` method (in `[Doc/library/ssl.rst](https://github.com/python/cpython/blob/main/Doc/library/ssl.rst)`).

**Comment by Mariatta** [comment]
Thanks Antoine. So is this a matter of replacing the url to https://wiki.openssl.org/index.php/Manual:Ciphers(1)#CIPHER_LIST_FORMAT?
Or is there a better url that will not go out of date in the future...

**Comment by pitrou** [comment]
I don't think OpenSSL are promising anything about their URLs (the old one having gone 404 is proof of that :-)). So Felipe's suggestion is as good as any, IMHO.

**Comment by 74276bb4-928d-42d2-ac2e-17266a3681b7** [comment]
Woops. Apologies -- I somehow deleted that part from the report. Thanks Antoine for jumping in. If you are using the wiki url, make sure not to include the question mark at the end :-)

**Comment by Mariatta** [comment]
Cool! I'm tagging this as an easy issue, suitable for first timers or new contributors. 

Felipe, are you up for preparing the PR?

**Comment by 74276bb4-928d-42d2-ac2e-17266a3681b7** [comment]
Sure, will do!

**Comment by tiran** [comment]
New changeset 19e4d9346db7fb65845b98a9cb9caacaaac8a81a by Christian Heimes (Felipe) in branch 'master':
bpo-31533: fix broken link to OpenSSL docs (bpo-3674)
https://github.com/python/cpython/commit/19e4d9346db7fb65845b98a9cb9caacaaac8a81a

**Comment by Mariatta** [comment]
New changeset 6b44ad1abdb9b3aaf27e2ba1fc4b69b9a0f50c25 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31533: fix broken link to OpenSSL docs (GH-3674) (GH-3675)
https://github.com/python/cpython/commit/6b44ad1abdb9b3aaf27e2ba1fc4b69b9a0f50c25

**Comment by Mariatta** [comment]
New changeset 5b6452d412b5be45f265093e75563fcf6d05dc3e by Mariatta (Christian Heimes) in branch '2.7':
bpo-31533: fix broken link to OpenSSL docs (GH-3674) (GH-3676)
https://github.com/python/cpython/commit/5b6452d412b5be45f265093e75563fcf6d05dc3e

**Comment by Mariatta** [comment]
Fixed and backported.
Thanks everyone!
