### ISSUE TITLE
python 3.6.2 installation failed 0x80070002 error

### ISSUE THREAD

**Issue by e048a7a3-4b90-41ff-91e5-93379d32ab42** [python/cpython#75715]
BPO | [31534](https://bugs.python.org/issue31534)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
Files | <li>[Python 3.6.2 (64-bit)_20170920180757.log](https://bugs.python.org/file47158/Python%203.6.2%20%2864-bit%29_20170920180757.log "Uploaded as hello,  i have windows 7 with 64 bit os. i download the files: Python 3.6.2 - 2017-07-17:  Windows x86-64 web-based installer  Windows x86-64 executable installer. i clicked run as admin when i tried each one of them.   in the setup window,i clicked on "install now". it started loading and then showed "setup failed":"0x80070002- the system cannot find the file specified". i add the log file for more information. can you please help me figure it out? at 2017-09-20.15:59:48 by roie")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-02.22:47:01.180>
created_at = <Date 2017-09-20.15:59:49.190>
labels = ['OS-windows']
title = 'python 3.6.2 installation failed 0x80070002 error'
updated_at = <Date 2019-08-02.22:47:01.180>
user = 'https://bugs.python.org/roie'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-02.22:47:01.180>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-02.22:47:01.180>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-09-20.15:59:49.190>
creator = 'roie'
dependencies = []
files = ['47158']
hgrepos = []
issue_num = 31534
keywords = []
message_count = 3.0
messages = ['302630', '302769', '321941']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'roie', 'malopet']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31534'
versions = ['Python 3.6']
```

</p></details>

**Comment by e048a7a3-4b90-41ff-91e5-93379d32ab42** [comment]
hello,

i have windows 7 with 64 bit os.
i download the files:
Python 3.6.2 - 2017-07-17:
 Windows x86-64 web-based installer
 Windows x86-64 executable installer.
i clicked run as admin when i tried each one of them.


in the setup window,i clicked on "install now".
it started loading and then showed "setup failed":"0x80070002- the system cannot find the file specified".
i add the log file for more information.
when i searched on the internet, i didn't manage to draw information needed for solution on this matter. 
can you please help me figure it out?

**Comment by zooba** [comment]
If you look in your %TEMP% directory, there should be more log files near the one you attached (most of the filename will be the same).

Could you zip them up and attach all of them here? I think there's some information in one of the others that I'll need to see.

Also, you shouldn't have to run this installer as admin. If you are not planning to install for all users on your machine (and according to the log, you did not select that option), then it may work better if you just run it as yourself.
