### ISSUE TITLE
PyOS_InputHook is not called when waiting for input() in Windows

### ISSUE THREAD

**Issue by dbe84a28-293c-4318-987c-766bbc70f1e2** [python/cpython#75727]
BPO | [31546](https://bugs.python.org/issue31546)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @ZackerySpytz, @yhlam, @miss-islington
PRs | <li>python/cpython#7978</li><li>python/cpython#7990</li><li>python/cpython#7991</li>
Files | <li>[test_tk.py](https://bugs.python.org/file47160/test_tk.py "Uploaded as text/plain at 2017-09-21.16:13:02 by @yhlam"): TK test script</li><li>[py35_call_stack.png](https://bugs.python.org/file47161/py35_call_stack.png "Uploaded as image/png at 2017-09-21.16:15:37 by @yhlam"): Python 3.5 call stack</li><li>[py36_call_stack.png](https://bugs.python.org/file47162/py36_call_stack.png "Uploaded as image/png at 2017-09-21.16:16:11 by @yhlam"): Python 3.6 call stack</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-07-23.15:44:37.548>
created_at = <Date 2017-09-21.16:13:02.342>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'PyOS_InputHook is not called when waiting for input() in Windows'
updated_at = <Date 2019-07-23.15:44:37.548>
user = 'https://github.com/yhlam'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-23.15:44:37.548>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2019-07-23.15:44:37.548>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2017-09-21.16:13:02.342>
creator = 'yhlam'
dependencies = []
files = ['47160', '47161', '47162']
hgrepos = []
issue_num = 31546
keywords = ['patch']
message_count = 12.0
messages = ['302701', '302702', '302703', '302705', '302707', '304785', '305567', '305568', '320674', '320680', '320681', '348067']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'ZackerySpytz', 'yhlam', 'miss-islington']
pr_nums = ['7978', '7990', '7991']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31546'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by dbe84a28-293c-4318-987c-766bbc70f1e2** [comment]
Since python 3.6, PyOS_InputHook is not called when waiting for IO in Windows.

This causes issues with GUI framework like tkinter that relys on PyOS_InputHook to handle user interaction.

I attached a test script. When running the script with python 3.5, the tkinter window will show up properly. But if you run the script with python 3.6, the tkinter window will be frozen. 

I believe the issue is introduced in commit 3929499. In commit 3929499, \_PyOS_WindowsConsoleReadline is added as the new Windows implementation of PyOS_StdioReadline. Originally, PyOS_StdioReadline calls my_fgets to read input, and my_fgets will call PyOS_InputHook before the calling the real fgets. However, \_PyOS_WindowsConsoleReadline calls ReadConsoleW instead of my_fgets to read input, and PyOS_InputHook is never called.

The bug is first reported in matplotlib.
https://github.com/matplotlib/matplotlib/issues/9206#issuecomment-331192016

**Comment by dbe84a28-293c-4318-987c-766bbc70f1e2** [comment]
Attach python 3.5 call stack of the test script

**Comment by dbe84a28-293c-4318-987c-766bbc70f1e2** [comment]
Attach python 3.6 call stack of the test script

**Comment by zooba** [comment]
You're right, we're missing this section of code:

        if (PyOS_InputHook != NULL)
            (void)(PyOS_InputHook)();

Since we just call it and ignore anything it does, it should be safe enough to add it immediately before the ReadConsoleW call (inside the loop).

**Comment by zooba** [comment]
(Belongs inside [Parser/myreadline.c](https://github.com/python/cpython/blob/main/Parser/myreadline.c) in the \_PyOS_WindowsConsoleReadline function)

**Comment by dbe84a28-293c-4318-987c-766bbc70f1e2** [comment]
As the fix seems simple, any chance this bug can be fixed in next python 3.6 maintenance release? It is the major roadblock for my application to upgrade to python 3.6. Thanks

**Comment by zooba** [comment]
The fix is simple, just need someone to do a PR. (I might get to it eventually, but I'm working on other things right now.)

**Comment by zooba** [comment]
And yes, I think this is fine for 3.6.
