### ISSUE TITLE
gettext.Catalog title is not flagged as a class

### ISSUE THREAD

**Issue by 517ec50a-c0bc-4503-b041-270261e61905** [python/cpython#75725]
BPO | [31544](https://bugs.python.org/issue31544)
--- | :---
Nosy | @merwok, @serhiy-storchaka, @Linkid

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-27.05:38:00.282>
created_at = <Date 2017-09-21.15:27:06.127>
labels = ['invalid', 'type-feature', '3.7', 'docs']
title = 'gettext.Catalog title is not flagged as a class'
updated_at = <Date 2018-10-27.05:38:00.281>
user = 'https://github.com/Linkid'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-27.05:38:00.281>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-10-27.05:38:00.282>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-09-21.15:27:06.127>
creator = 'linkid'
dependencies = []
files = []
hgrepos = []
issue_num = 31544
keywords = []
message_count = 3.0
messages = ['302696', '302734', '314740']
nosy_count = 4.0
nosy_names = ['eric.araujo', 'docs@python', 'serhiy.storchaka', 'linkid']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31544'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 517ec50a-c0bc-4503-b041-270261e61905** [comment]
In the ``gettext`` documentatino, in the title about the ``Catalog`` constructor, ``Catalog`` is not flagged as a class.

**Comment by merwok** [comment]
Are you talking about https://docs.python.org/3/library/gettext.html#the-catalog-constructor ?  I think the lack of markup is on purpose, since the text explains that this is a compatibility measure (mostly obsolete nowadays).

For future bug reports, please include links or screenshots!  They make it easier to communicate.
