### ISSUE TITLE
Fixing documentation for timedelta.

### ISSUE THREAD

**Issue by a24690b2-760c-4b16-8d68-d9a44e29742c** [python/cpython#75726]
BPO | [31545](https://bugs.python.org/issue31545)
--- | :---
Nosy | @vstinner, @berkerpeksag, @musically-ut
PRs | <li>python/cpython#3687</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-27.11:25:47.997>
created_at = <Date 2017-09-21.16:09:25.692>
labels = ['type-feature', '3.7', 'docs']
title = 'Fixing documentation for timedelta.'
updated_at = <Date 2017-10-27.14:13:51.870>
user = 'https://github.com/musically-ut'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-27.14:13:51.870>
actor = 'musically_ut'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-27.11:25:47.997>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-09-21.16:09:25.692>
creator = 'musically_ut'
dependencies = []
files = []
hgrepos = []
issue_num = 31545
keywords = ['patch']
message_count = 5.0
messages = ['302700', '305110', '305112', '305116', '305121']
nosy_count = 4.0
nosy_names = ['vstinner', 'docs@python', 'berker.peksag', 'musically_ut']
pr_nums = ['3687']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31545'
versions = ['Python 3.7']
```

</p></details>

**Comment by a24690b2-760c-4b16-8d68-d9a44e29742c** [comment]
There are some instances in the documentation of datetime where the repr of timedelta is mentioned, which was changed in bpo-30302.


Am making a PR shortly to address them.

**Comment by berkerpeksag** [comment]
New changeset 843ea47a034307c7b1ca642dd70f0269255b289a by Berker Peksag (Utkarsh Upadhyay) in branch 'master':
bpo-31545: Update documentation containing timedelta repr. (GH-3687)
https://github.com/python/cpython/commit/843ea47a034307c7b1ca642dd70f0269255b289a

**Comment by berkerpeksag** [comment]
Thanks!

**Comment by vstinner** [comment]
Thank you Utkarsh Upadhyay for finishing the change up to the documentation ;-)

**Comment by a24690b2-760c-4b16-8d68-d9a44e29742c** [comment]
:)

There's still a lot of room for improvement on documentation front, esp. the inline \_\_doc__s. I'll be working on that next.

~
ut
