### ISSUE TITLE
Adding context in concurrent.futures.ProcessPoolExecutor

### ISSUE THREAD

**Issue by f50fb426-9df6-4590-87cf-f8a5d8c3396e** [python/cpython#75721]
BPO | [31540](https://bugs.python.org/issue31540)
--- | :---
Nosy | @pitrou, @tomMoral
PRs | <li>python/cpython#3682</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-03.09:58:35.209>
created_at = <Date 2017-09-21.09:01:38.314>
labels = ['3.7', 'type-feature', 'library']
title = 'Adding context in concurrent.futures.ProcessPoolExecutor'
updated_at = <Date 2017-10-03.09:58:35.208>
user = 'https://github.com/tomMoral'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.09:58:35.208>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-03.09:58:35.209>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-09-21.09:01:38.314>
creator = 'tomMoral'
dependencies = []
files = []
hgrepos = []
issue_num = 31540
keywords = []
message_count = 2.0
messages = ['302674', '303591']
nosy_count = 2.0
nosy_names = ['pitrou', 'tomMoral']
pr_nums = ['3682']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31540'
versions = ['Python 3.7']
```

</p></details>

**Comment by f50fb426-9df6-4590-87cf-f8a5d8c3396e** [comment]
The `ProcessPoolExecutor` processes start method can only be change by changing the global default context with `set_start_method` at the beginning of a script. We propose to allow passing a context argument in the constructor to allow more flexible control of the executor.

Adding this would allow testing `ProcessPoolExecutor` with all the available context

**Comment by pitrou** [comment]
New changeset e8c368df22c344183627e7ef882bea1683fe6dbe by Antoine Pitrou (Thomas Moreau) in branch 'master':
bpo-31540: Allow passing multiprocessing context to ProcessPoolExecutor (bpo-3682)
https://github.com/python/cpython/commit/e8c368df22c344183627e7ef882bea1683fe6dbe
