### ISSUE TITLE
asyncio.wait_for can cancel futures faster with timeout==0

### ISSUE THREAD

**Issue by 86ff8d94-ee5b-445a-bc3a-d16703ca2300** [python/cpython#75737]
BPO | [31556](https://bugs.python.org/issue31556)
--- | :---
Nosy | @asvetlov, @1st1, @hellysmile
PRs | <li>python/cpython#3703</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-05.16:05:32.055>
created_at = <Date 2017-09-22.20:47:57.541>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'asyncio.wait_for can cancel futures faster with timeout==0'
updated_at = <Date 2017-10-05.16:59:54.129>
user = 'https://github.com/hellysmile'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-05.16:59:54.129>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-05.16:05:32.055>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-09-22.20:47:57.541>
creator = 'hellysmile'
dependencies = []
files = []
hgrepos = []
issue_num = 31556
keywords = ['patch']
message_count = 8.0
messages = ['302770', '302771', '302772', '302773', '302774', '302775', '302779', '303777']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'hellysmile']
pr_nums = ['3703']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31556'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 86ff8d94-ee5b-445a-bc3a-d16703ca2300** [comment]
There is no need to create extra future and use loop.call_later to cancel base future from asyncio.wait_for when timeout==0. If loop is heavy loaded it can be cancelled simnifically later then 0 seconds later.

**Comment by 1st1** [comment]
Do you have a use case where this optimization is important?

**Comment by 86ff8d94-ee5b-445a-bc3a-d16703ca2300** [comment]
If coroutine function has some blocking calls before first await/yield from statement maybe makes sense do no let them be executed, if timeout equals 0

**Comment by 1st1** [comment]
I think this is a backwards incompatible change and thus will be rejected.  Currently there's a guarantee that "wait_for" can throw a TimeoutError \*only* when when you await it.

```py
   fut = wait_for(something, 0)
```


   \# some important code

   try:
       await fut
   except TimeoutError:
       \# do something

With your PR merged, the above asyncio code would be broken, because asyncio users can guard with try..except only the await expression.

**Comment by 86ff8d94-ee5b-445a-bc3a-d16703ca2300** [comment]
asyncio.wait_for is coroutine itself, to start executing code, no matter with this PR or not it needs to be awaited/yield from

```py
import asyncio

@asyncio.coroutine
def foo():
    print(1)

loop = asyncio.get_event_loop()

fut = asyncio.wait_for(foo(), 0)

print('it is not raised yet')
```


try:
    loop.run_until_complete(fut)
except asyncio.TimeoutError:
    print('raised here')


will print 
it is not raised yet
raised here

**Comment by 1st1** [comment]
You're right!  Let's work on the PR then, I've left a review comment.

**Comment by 86ff8d94-ee5b-445a-bc3a-d16703ca2300** [comment]
Actually provided example without patch will print 1, which is not expected

**Comment by 1st1** [comment]
Note, that this will not be backported to 3.6, as it behaves in a slightly incompatible way.  I consider this patch as an enhancement that makes 'asyncio.wait_for' semantics easier to reason about and more practical.
