### ISSUE TITLE
Extend json.tool to handle jsonlines (with a flag)

### ISSUE THREAD

**Issue by ff34e289-2fcf-42dc-aee3-c2d138a4b82a** [python/cpython#75734]
BPO | [31553](https://bugs.python.org/issue31553)
--- | :---
Nosy | @rhettinger, @vstinner, @ezio-melotti, @serhiy-storchaka, @lisroach
PRs | <li>python/cpython#3846</li><li>python/cpython#10051</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/lisroach'
closed_at = <Date 2018-11-07.10:25:30.301>
created_at = <Date 2017-09-22.16:41:06.565>
labels = ['3.8', 'type-feature', 'library']
title = 'Extend json.tool to handle jsonlines (with a flag)'
updated_at = <Date 2018-11-07.10:25:30.300>
user = 'https://bugs.python.org/EricMoyer'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-07.10:25:30.300>
actor = 'serhiy.storchaka'
assignee = 'lisroach'
closed = True
closed_date = <Date 2018-11-07.10:25:30.301>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-09-22.16:41:06.565>
creator = 'Eric Moyer'
dependencies = []
files = []
hgrepos = []
issue_num = 31553
keywords = ['patch']
message_count = 9.0
messages = ['302755', '302781', '302783', '302785', '302904', '302953', '328290', '328396', '329411']
nosy_count = 6.0
nosy_names = ['rhettinger', 'vstinner', 'ezio.melotti', 'serhiy.storchaka', 'lisroach', 'Eric Moyer']
pr_nums = ['3846', '10051']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31553'
versions = ['Python 3.8']
```

</p></details>

**Comment by ff34e289-2fcf-42dc-aee3-c2d138a4b82a** [comment]
json.tool should have the ability to format jsonlines data. It is a very commonly used format in many industries. Right now when given jsonlines (for example):

    echo -e '{"ingredients":["frog", "water", "chocolate", "glucose"]} | python -m json.tool

Works. But:

    echo -e '{"ingredients":["frog", "water", "chocolate", "glucose"]}\n{"ingredients":["chocolate","steel bolts"]}' | python -m json.tool

Reports an error: "Extra data: line 2 column 1 - line 3 column 1 (char 58 - 100)"

I propose that the above behavior be retained but:

    echo -e '{"ingredients":["frog", "water", "chocolate", "glucose"]}\n{"ingredients":"chocolate","steel bolts"}' | python3.7 -m json.tool --jsonlines

Should print:
{
    "ingredients": [
        "frog",
        "water",
        "chocolate",
        "glucose"
    ]
}
{
    "ingredients": [
        "chocolate",
        "steel bolts"
    ]
}

If someone else agrees this is an appropriate enhancement, I can start work on a PR in a couple of weeks.

**Comment by rhettinger** [comment]
This seems like a reasonable enhancement.

**Comment by serhiy-storchaka** [comment]
Jsonlines is an external to JSON format. You should split the data on lines and pass every line to the JSON parser separately. The same you should do with json.tool.

```sh
$ echo -e '{"ingredients":["frog", "water", "chocolate", "glucose"]}\n{"ingredients":["chocolate","steel bolts"]}' | while read -r line; do echo -n "$line" | python -m json.tool; done
{
    "ingredients": [
        "frog",
        "water",
        "chocolate",
        "glucose"
    ]
}
{
    "ingredients": [
        "chocolate",
        "steel bolts"
    ]
}
```

**Comment by ezio-melotti** [comment]
I agree with Raymond that this is a reasonable request.
Even if jsonlines is not part of the JSON specification, the format is quite common, and practicality beats purity (espcially considering that we are just talking about json.tool).

**Comment by rhettinger** [comment]
Eric, did you want to write the PR yourself or would you like for Lisa to bring it to fruition?   If you're going to do it yourself, Lisa will serve as the primary reviewer (with either Ezio or me doing the final sign-off).

**Comment by ff34e289-2fcf-42dc-aee3-c2d138a4b82a** [comment]
I planned to write the PR myself, on the principle of "it's my itch, I
should scratch it." But if you think it is better for someone else to write
it, you know the codebase better than I, and you know how long a PR takes
to review/fix. My intention is to help. I'll do whatever is easier for you.
