### ISSUE TITLE
open() doesn't use locale.getpreferredencoding()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75746]
BPO | [31565](https://bugs.python.org/issue31565)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @benjaminp, @ericsnowcurrently, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-23.21:49:37.051>
labels = ['type-bug', '3.7', 'expert-IO']
title = "open() doesn't use locale.getpreferredencoding()"
updated_at = <Date 2017-09-23.22:54:56.922>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-23.22:54:56.922>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-09-23.21:49:37.051>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31565
keywords = []
message_count = 1.0
messages = ['302812']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'benjamin.peterson', 'stutzbach', 'eric.snow', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31565'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It is documented that the default encoding for open() and io.TextIOWrapper() is locale.getpreferredencoding(). But actually the C implementation in Python 3 uses \_bootlocale.getpreferredencoding(). Monkey-patching locale.getpreferredencoding doesn't affect open().

**Comment by vstinner** [comment]
Since Python 3.10, ``Modules/_io/textio.c`` uses ``_Py_GetLocaleEncodingObject()``. It can no longer be monkey-patched.

Since Python 3.12, the _pyio module now uses ``locale.getencoding()``.

I suggest to either remove the mention of the called function from the documentation, or closing this issue as won't fix.

**Comment by vstinner** [comment]
https://docs.python.org/dev/library/functions.html#open now says:

>  locale.getencoding() is called to get the current locale encoding

The issue has been fixed in the meanwhile.
