### ISSUE TITLE
NewType can subclass NewType

### ISSUE THREAD

**Issue by aab27600-7ba3-44f4-80f4-cd0104144671** [python/cpython#75745]
BPO | [31564](https://bugs.python.org/issue31564)
--- | :---
Nosy | @Mariatta, @Topper-123
PRs | <li>python/cpython#3696</li><li>python/cpython#3715</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-24.02:47:13.562>
created_at = <Date 2017-09-23.21:35:05.494>
labels = ['type-feature', '3.7', 'docs']
title = 'NewType can subclass NewType'
updated_at = <Date 2017-09-24.02:47:13.561>
user = 'https://github.com/Topper-123'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-24.02:47:13.561>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-24.02:47:13.562>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-09-23.21:35:05.494>
creator = 'Petersen'
dependencies = []
files = []
hgrepos = []
issue_num = 31564
keywords = ['patch']
message_count = 4.0
messages = ['302809', '302825', '302826', '302827']
nosy_count = 3.0
nosy_names = ['docs@python', 'Mariatta', 'Petersen']
pr_nums = ['3696', '3715']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31564'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by aab27600-7ba3-44f4-80f4-cd0104144671** [comment]
It has become possible to create a ``NewType`` from an existing  ``NewType``, see https://github.com/python/mypy/pull/3465 and https://github.com/python/peps/pull/271.

This is a small update to the documentation as a concequence of the above change.

**Comment by Mariatta** [comment]
New changeset 039b25d8fd21f8d5d9e3cb536402d952cf068dc1 by Mariatta (topper-123) in branch 'master':
bpo-31564: Update typing documentation (GH-3696)
https://github.com/python/cpython/commit/039b25d8fd21f8d5d9e3cb536402d952cf068dc1

**Comment by Mariatta** [comment]
New changeset 018e6b9f696311a65f47f33ea04b7baef3f3664f by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31564: Update typing documentation (GH-3696) (GH-3715)
https://github.com/python/cpython/commit/018e6b9f696311a65f47f33ea04b7baef3f3664f

**Comment by Mariatta** [comment]
Thanks Terji!
