### ISSUE TITLE
Configure thinks it finds python3.5 but doesn't

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#75749]
BPO | [31568](https://bugs.python.org/issue31568)
--- | :---
Nosy | @vstinner, @larryhastings
PRs | <li>python/cpython#3737</li><li>python/cpython#5274</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = <Date 2017-09-25.08:25:15.282>
created_at = <Date 2017-09-24.09:15:21.290>
labels = ['build', 'release-blocker']
title = "Configure thinks it finds python3.5 but doesn't"
updated_at = <Date 2018-01-23.02:14:51.483>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-23.02:14:51.483>
actor = 'ncoghlan'
assignee = 'vstinner'
closed = True
closed_date = <Date 2017-09-25.08:25:15.282>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-09-24.09:15:21.290>
creator = 'larry'
dependencies = []
files = []
hgrepos = []
issue_num = 31568
keywords = ['patch', '3.5regression']
message_count = 5.0
messages = ['302837', '302838', '302887', '302891', '302923']
nosy_count = 2.0
nosy_names = ['vstinner', 'larry']
pr_nums = ['3737', '5274']
priority = 'release blocker'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31568'
versions = ['Python 3.5']
```

</p></details>

**Comment by larryhastings** [comment]
On Python 3.5, the makefile pseudotarget "regen-opcode" now fails if "python3.5" can't be found on the path.  What's strange is that the configure script scans to see if it can find "python3.5", and it thinks it can, but then actually attempting to run it fails.

I can't merge PRs in 3.5 right now because this is broken.  Note that everything is fine on my Ubuntu laptop because I \*do* have "python3.5" on my path.  But the Travis CI buildbot doesn't.

Here is an example failure on Travis CI:

https://travis-ci.org/python/cpython/jobs/279140454

I don't know how this got merged, because the PR that made this change should itself have failed.  Maybe the configuration of the buildbot has changed since we merged that PR?

**Comment by larryhastings** [comment]
Oh, and, Victor, I tagged you with this because git blame says you're the most person to touch PYTHON_FOR_REGEN in the makefile, checkin ab6b962ef24 .

**Comment by vstinner** [comment]
The Travis CI error is:
\---
python3.5 ./Objects/typeslots.py \\

		\< ./Include/typeslots.h \\

		./Objects/typeslots.inc

pyenv: python3.5: command not found

pyenv: python3.5: command not found

The \`python3.5' command exists in these Python versions:

pyenv: python3.5: command not found

  3.5

  3.5.3

make: *** [regen-opcode] Error 127

make: *** Waiting for unfinished jobs....
\---

It looks like this Travis CI bug:
https://github.com/travis-ci/travis-ci/issues/8363

I wrote https://github.com/python/cpython/pull/3737 which should works around the Travis CI. Change inspired by:
https://github.com/pre-commit/pre-commit/commit/e3ab8902692e896da9ded42bd4d76ea4e1de359d

**Comment by larryhastings** [comment]
New changeset 70c630a7316f9f6063557786442e3c56502fe8ea by larryhastings (Victor Stinner) in branch '3.5':
bpo-31568, Travis CI: Fix python3.5 (bpo-3737)
https://github.com/python/cpython/commit/70c630a7316f9f6063557786442e3c56502fe8ea

**Comment by vstinner** [comment]
It seems like the bug was fixed. Nice.
