### ISSUE TITLE
snakebite.net is not available

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75743]
BPO | [31562](https://bugs.python.org/issue31562)
--- | :---
Nosy | @vstinner, @benjaminp, @tpn, @bitdancer, @zware, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-23.17:46:49.604>
labels = ['type-bug', 'tests']
title = 'snakebite.net is not available'
updated_at = <Date 2018-12-17.11:44:25.744>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-17.11:44:25.744>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-09-23.17:46:49.604>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31562
keywords = []
message_count = 7.0
messages = ['302793', '302799', '312029', '312129', '312131', '312136', '331995']
nosy_count = 6.0
nosy_names = ['vstinner', 'benjamin.peterson', 'trent', 'r.david.murray', 'zach.ware', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31562'
versions = []
```

</p></details>

### Linked PRs
* gh-109060
* gh-109087
* gh-109102
* gh-109103

**Comment by serhiy-storchaka** [comment]
The testConnectTimeout in test_timeout is skipped since network resources it uses are not available.

```sh
$ ./python -m test -vuall test_timeout
...
testConnectTimeout (test.test_timeout.TCPTimeoutTestCase) ... skipped "Resource 'blackhole.snakebite.net' is not available"

$ host blackhole.snakebite.net
;; connection timed out; no servers could be reached
$ host whitehole.snakebite.net
;; connection timed out; no servers could be reached
$ host snakebite.net
;; connection timed out; no servers could be reached
```


Is it temporary or permanent issue?

**Comment by tpn** [comment]
Hmmmm, I'll investigate when I get home tomorrow.

**Comment by ewdurbin** [comment]
https://github.com/python/psf-salt/commit/ed19ff8b633ab311093859c179ad5329f37fb024 Adds firewall rules so that

`pythontest:56666` works a standing for `blackhole.snakebite.net:56666`
and
`pythontest:56667` works a standing for `blackhole.snakebite.net:56667`
