### ISSUE TITLE
hashlib.blake2: error in example for signed cookies

### ISSUE THREAD

**Issue by ec36f777-fa79-4c20-ac5e-15501f77bca7** [python/cpython#75741]
BPO | [31560](https://bugs.python.org/issue31560)
--- | :---
Nosy | @benjaminp, @dchest
PRs | <li>python/cpython#3694</li><li>python/cpython#3707</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-23.17:27:43.037>
created_at = <Date 2017-09-23.16:22:48.191>
labels = ['3.7', 'docs']
title = 'hashlib.blake2: error in example for signed cookies'
updated_at = <Date 2017-09-23.17:27:43.036>
user = 'https://github.com/dchest'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-23.17:27:43.036>
actor = 'benjamin.peterson'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-23.17:27:43.037>
closer = 'benjamin.peterson'
components = ['Documentation']
creation = <Date 2017-09-23.16:22:48.191>
creator = 'dchest'
dependencies = []
files = []
hgrepos = []
issue_num = 31560
keywords = ['patch']
message_count = 3.0
messages = ['302787', '302791', '302792']
nosy_count = 3.0
nosy_names = ['benjamin.peterson', 'docs@python', 'dchest']
pr_nums = ['3694', '3707']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31560'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ec36f777-fa79-4c20-ac5e-15501f77bca7** [comment]
The example for creating and verifying signed cookies with hashlib.blake2 doesn't work. Corrected in GitHub PR bpo-3694.

**Comment by benjaminp** [comment]
New changeset aecc08ac3a14a73aa353655bb65ff8d965e935a0 by Benjamin Peterson (Dmitry Chestnykh) in branch 'master':
Docs: correct hashlib.blake2 keyed hashing example (bpo-31560)
https://github.com/python/cpython/commit/aecc08ac3a14a73aa353655bb65ff8d965e935a0

**Comment by benjaminp** [comment]
New changeset 5614487378863d14cdbe730b00d6803523abb7ac by Benjamin Peterson (Miss Islington (bot)) in branch '3.6':
[3.6] Docs: correct hashlib.blake2 keyed hashing example (bpo-31560)
https://github.com/python/cpython/commit/5614487378863d14cdbe730b00d6803523abb7ac
