### ISSUE TITLE
assertion failure in _warnings.warn() in case of a bad __name__ global

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75747]
BPO | [31566](https://bugs.python.org/issue31566)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3717</li><li>python/cpython#3730</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.05:01:23.965>
created_at = <Date 2017-09-24.06:53:40.936>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in _warnings.warn() in case of a bad __name__ global'
updated_at = <Date 2017-09-27.05:01:23.963>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.05:01:23.963>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.05:01:23.965>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-09-24.06:53:40.936>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31566
keywords = ['patch']
message_count = 3.0
messages = ['302829', '302877', '302885']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = ['3717', '3730']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31566'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure:
\_\_name__ = b'foo'
\_\_file__ = None
import \_warnings
\_warnings.warn('bar')

This is because setup_context() (in [Python/_warnings.c](https://github.com/python/cpython/blob/main/Python/_warnings.c)) assumes that \_\_name__
is a string, and so it passes it to \_PyUnicode_EqualToASCIIString(), which
asserts it is a string.

**Comment by serhiy-storchaka** [comment]
New changeset 5d3e80021ab33360191eb0fbff34e0246c913884 by Serhiy Storchaka (Oren Milman) in branch 'master':
bpo-31566: Fix an assertion failure in \_warnings.warn() in case of a bad \_\_name__ global. (bpo-3717)
https://github.com/python/cpython/commit/5d3e80021ab33360191eb0fbff34e0246c913884

**Comment by serhiy-storchaka** [comment]
New changeset 415cc1fa57710614ed3384d0cafc58ccf7adee8c by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31566: Fix an assertion failure in \_warnings.warn() in case of a bad \_\_name__ global. (GH-3717) (bpo-3730)
https://github.com/python/cpython/commit/415cc1fa57710614ed3384d0cafc58ccf7adee8c
