### ISSUE TITLE
crash in os.utime() in case of a bad ns argument

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75758]
BPO | [31577](https://bugs.python.org/issue31577)
--- | :---
Nosy | @mdickinson, @ned-deily, @zware, @serhiy-storchaka, @orenmn, @miss-islington, @tirkarthi
PRs | <li>python/cpython#3752</li><li>python/cpython#9222</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-14.20:50:26.547>
created_at = <Date 2017-09-25.16:47:57.601>
labels = ['extension-modules', '3.7', '3.8', 'type-crash']
title = 'crash in os.utime() in case of a bad ns argument'
updated_at = <Date 2018-09-14.20:50:26.545>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-14.20:50:26.545>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-14.20:50:26.547>
closer = 'zach.ware'
components = ['Extension Modules']
creation = <Date 2017-09-25.16:47:57.601>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31577
keywords = ['patch']
message_count = 12.0
messages = ['302962', '302976', '303020', '324940', '324941', '325154', '325166', '325171', '325174', '325257', '325259', '325397']
nosy_count = 7.0
nosy_names = ['mark.dickinson', 'ned.deily', 'zach.ware', 'serhiy.storchaka', 'Oren Milman', 'miss-islington', 'xtreak']
pr_nums = ['3752', '9222']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31577'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes the interpreter to crash:
class BadInt:
    def \_\_divmod__(*args):
        return 42

```py
import os
os.utime('foo.txt', ns=(BadInt(), 1))
```



This is because split_py_long_to_s_and_ns() (in [Modules/posixmodule.c](https://github.com/python/cpython/blob/main/Modules/posixmodule.c)) assumes
that PyNumber_Divmod() returns a 2-tuple, and passes it to PyTuple_GET_ITEM(),
which assumes it is a tuple. Thus, PyTuple_GET_ITEM() might return a non-NULL
value which is not an address of a Python object.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
I opened a PR.
I think another fix might be to use
PyLong_Type.tp_as_number-\>long_divmod() instead of PyNumber_Divmod().

**Comment by serhiy-storchaka** [comment]
There is also similar issue in timedelta.\_\_divmod__.

PyLong_Type.tp_as_number-\>nb_divmod() works only with integers.

The different way of solving this issue is used in microseconds_to_delta_ex() in \_datetimemodule.c.

Perhaps the best solution is to add a check that the result of nb_divmod() is a 2-tuple in PyNumber_Divmod(). This could fix similar errors in third-party code. What is your thoughts Mark?
