### ISSUE TITLE
Avoid suppressing all exceptions in PyObject_HasAttr()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75753]
BPO | [31572](https://bugs.python.org/issue31572)
--- | :---
Nosy | @pitrou, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#3723</li><li>python/cpython#3724</li><li>python/cpython#3725</li><li>python/cpython#3726</li><li>python/cpython#3727</li><li>python/cpython#3728</li><li>python/cpython#3729</li><li>python/cpython#3731</li><li>python/cpython#4081</li>
Dependencies | <li>bpo-32787: Better error handling in ctypes</li><li>bpo-32788: Better error handling in sqlite3</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-24.17:46:45.898>
labels = ['extension-modules', 'interpreter-core', 'type-bug']
title = 'Avoid suppressing all exceptions in PyObject_HasAttr()'
updated_at = <Date 2018-12-05.14:44:23.566>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-05.14:44:23.566>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Interpreter Core']
creation = <Date 2017-09-24.17:46:45.898>
creator = 'serhiy.storchaka'
dependencies = ['32787', '32788']
files = []
hgrepos = []
issue_num = 31572
keywords = ['patch']
message_count = 12.0
messages = ['302873', '304759', '304764', '304787', '304795', '306084', '306085', '306086', '306087', '310091', '316580', '331121']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'serhiy.storchaka']
pr_nums = ['3723', '3724', '3725', '3726', '3727', '3728', '3729', '3731', '4081']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31572'
versions = []
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Initially hasattr() suppressed all raised exceptions. In bpo-2196 hasattr() was changed to suppress only Exception exceptions and propagate exceptions like SystemExit and KeyboardInterrupt. In bpo-9666 hasattr() was changed to suppress only AttributeError.

But C API functions, PyObject_HasAttr() and like, were not changed. PyObject_HasAttr() is documented as an equivalent of hasattr(), but there is undocumented difference. The C code that uses PyObject_HasAttr() starves from the same problem as the Python code that used old hasattr().

The only solution of this problem is getting rid of PyObject_HasAttr() if favor of PyObject_GetAttr(). In this issue I'm going to propose a set of PRs that replace PyObject_HasAttr() invocations in different components with more correct code.

**Comment by serhiy-storchaka** [comment]
New changeset 04e36af9b88cd5e80fc818e51d46f07252a2ff3f by Serhiy Storchaka in branch 'master':
bpo-31572: Get rid of using \_PyObject_HasAttrId() in pickle. (bpo-3729)
https://github.com/python/cpython/commit/04e36af9b88cd5e80fc818e51d46f07252a2ff3f

**Comment by pitrou** [comment]
> The only solution of this problem is getting rid of PyObject_HasAttr() if favor of PyObject_GetAttr().

I don't understand why.  Why not fix PyObject_HasAttr() like hasattr() was?

**Comment by serhiy-storchaka** [comment]
hasattr() can return True, False, or raise an exception. But PyObject_HasAttr() just returns an integer: 0 for False, not 0 for True. There is no way to return an error, and existing code doesn't expect that PyObject_HasAttr() returns an error. Leaking an exception from PyObject_HasAttr() will break existing code.

**Comment by serhiy-storchaka** [comment]
New changeset 77af0a3bcab666a356eea2927a8031a7578d60d2 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31572: Get rid of using \_PyObject_HasAttrId() in pickle. (GH-3729). (bpo-4081)
https://github.com/python/cpython/commit/77af0a3bcab666a356eea2927a8031a7578d60d2

**Comment by serhiy-storchaka** [comment]
New changeset d4f8480dfe89447587550a85b61d4e9faf827e98 by Serhiy Storchaka in branch 'master':
bpo-31572: Don't silence unexpected errors in the \_warnings module. (bpo-3731)
https://github.com/python/cpython/commit/d4f8480dfe89447587550a85b61d4e9faf827e98

**Comment by serhiy-storchaka** [comment]
New changeset 1707e4020fa8dca8e6a3ac4f9da105b54d597b66 by Serhiy Storchaka in branch 'master':
bpo-31572: Silence only AttributeError when get the \_\_copy__ attribute in itertools.tee(). (bpo-3724)
https://github.com/python/cpython/commit/1707e4020fa8dca8e6a3ac4f9da105b54d597b66

**Comment by serhiy-storchaka** [comment]
New changeset 60c3d3551a96febac7b6016fb44605643842c686 by Serhiy Storchaka in branch 'master':
bpo-31572: Get rid of \_PyObject_HasAttrId() in dict and OrderedDict. (bpo-3728)
https://github.com/python/cpython/commit/60c3d3551a96febac7b6016fb44605643842c686

**Comment by serhiy-storchaka** [comment]
New changeset bba2239c17a404fc99524bfbf8126c9b3b7fb343 by Serhiy Storchaka in branch 'master':
bpo-31572: Get rid of \_PyObject_HasAttrId() in the ASDL parser. (bpo-3725)
https://github.com/python/cpython/commit/bba2239c17a404fc99524bfbf8126c9b3b7fb343

**Comment by vstinner** [comment]
I suppose that the next step is to design a migration path to avoid legacy API which suppress exceptions :-) It was discussed at: https://github.com/capi-workgroup/problems/issues/54

Maybe we can start by **soft** deprecating old APIs.
