### ISSUE TITLE
problem in math

### ISSUE THREAD

**Issue by 7ec8c67d-7b57-43bd-82d1-9c45ece16672** [python/cpython#75757]
BPO | [31576](https://bugs.python.org/issue31576)
--- | :---
Nosy | @vstinner, @aneeshjose

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-25.13:10:52.334>
created_at = <Date 2017-09-25.13:09:14.565>
labels = ['3.7', 'invalid', 'performance']
title = 'problem in math'
updated_at = <Date 2017-09-25.13:20:01.311>
user = 'https://github.com/aneeshjose'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-25.13:20:01.311>
actor = 'aneesh317'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-25.13:10:52.334>
closer = 'vstinner'
components = []
creation = <Date 2017-09-25.13:09:14.565>
creator = 'aneesh317'
dependencies = []
files = []
hgrepos = []
issue_num = 31576
keywords = []
message_count = 3.0
messages = ['302955', '302956', '302957']
nosy_count = 2.0
nosy_names = ['vstinner', 'aneesh317']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31576'
versions = ['Python 3.7']
```

</p></details>

**Comment by 7ec8c67d-7b57-43bd-82d1-9c45ece16672** [comment]
We know that the answer of sin 90 is 1.
But In Python's library math,the value of it is around 0.83...
My program is as follows:
import math
a=math.sin(90)
print(a)
#Output obtained is 0.83.....
Hope you guys solve this on the next update or nearby
I hope it is a small issue.But the credibility of program depends upon every minute particles

**Comment by vstinner** [comment]
It seems like you are confused between radians and degrees. math.sin() expects radians.
https://docs.python.org/dev/library/math.html#math.sin

Sorry but the Python bug tracker is not the right to ask questions. I close your bug report.

**Comment by 7ec8c67d-7b57-43bd-82d1-9c45ece16672** [comment]
Thankyou for the information .
