### ISSUE TITLE
Functional Programming HOWTO sub-optimal example for reduce

### ISSUE THREAD

**Issue by ca7bc867-e879-499e-8499-d50fbd2afd19** [python/cpython#75756]
BPO | [31575](https://bugs.python.org/issue31575)
--- | :---
Nosy | @rhettinger

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-26.06:41:01.314>
created_at = <Date 2017-09-25.12:11:35.918>
labels = ['3.7', 'docs']
title = 'Functional Programming HOWTO sub-optimal example for reduce'
updated_at = <Date 2017-09-26.06:41:01.312>
user = 'https://bugs.python.org/AnranYang'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-26.06:41:01.312>
actor = 'rhettinger'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-26.06:41:01.314>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-09-25.12:11:35.918>
creator = 'Anran Yang'
dependencies = []
files = []
hgrepos = []
issue_num = 31575
keywords = []
message_count = 2.0
messages = ['302950', '303015']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'Anran Yang']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31575'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ca7bc867-e879-499e-8499-d50fbd2afd19** [comment]
At the end of the Functional Programming HOWTO document (https://docs.python.org/3.7/howto/functional.html) the usage of reduce/lambda/for loops are compared and discussed. However, the example for reduce seems sub-optimal and thus the discussion is not that efficient. The example:

```py
total = functools.reduce(lambda a, b: (0, a[1] + b[1]), items)[1]
```


could be changed to:

```py
total = functools.reduce(lambda total, item: total + item[1], items, 0)
```


which is much more readable and is actually not much inferior to the loop one (though the sum approach is still more concise).

**Comment by rhettinger** [comment]
I think the existing code conveys the author's message better than the proposed revision.  The example isn't about efficiency; rather, it is about comparing several alternative formulations with this one being the weakest of the lost.  For emphasizing that point and not getting lost in a made-up example, the a[1] and b[1] style is more effective.

That's for the suggestion but I don't think it is a win.
