### ISSUE TITLE
Add _pth breadcrumb to sys.path documentation

### ISSUE THREAD

**Issue by fd3a86f9-3ea4-4f83-9af0-70d4a24b6031** [python/cpython#75763]
BPO | [31582](https://bugs.python.org/issue31582)
--- | :---
Nosy | @pfmoore, @tjguk, @ericsnowcurrently, @zware, @zooba, @RusselWebber
PRs | <li>python/cpython#31082</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-26.04:47:19.983>
labels = ['3.11', 'type-feature', 'OS-windows', 'docs']
title = 'Add _pth breadcrumb to sys.path documentation'
updated_at = <Date 2022-03-23.17:29:54.697>
user = 'https://bugs.python.org/TravelerHauptman'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.17:29:54.697>
actor = 'steve.dower'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Windows']
creation = <Date 2017-09-26.04:47:19.983>
creator = 'Traveler Hauptman'
dependencies = []
files = []
hgrepos = []
issue_num = 31582
keywords = ['patch']
message_count = 7.0
messages = ['303000', '303358', '410996', '411883', '411942', '411980', '415887']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'eric.snow', 'zach.ware', 'steve.dower', 'Traveler Hauptman', 'RusselWebber']
pr_nums = ['31082']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31582'
versions = ['Python 3.11']
```

</p></details>

**Comment by fd3a86f9-3ea4-4f83-9af0-70d4a24b6031** [comment]
Python on windows (winpython) was not adding PYTHONPATH to sys.path as documented and I could not understand why.

It took a lot of time, web searches, and finally a tour through the code to find out about \_pth; which is well documented but difficult to find out about if you don't know about it beforehand.

Please improve the sys.path documentation to say that it depends on either PYTHONPATH or the \*.\_pth file. Better yet, link to the actual sys.path heuristics.

**Comment by zooba** [comment]
Sounds like a good idea.

I hope that sys.path initialization is documented as well for POSIX as it is for Windows, as that will make this a simple "for X, click here; for Y, click here" patch. Otherwise, someone will need to figure out exactly what rules are followed so they can be documented.

(Hey Eric - when we get that Python initialization script, we can have one set of rules for inferring sys.path on all platforms in easy-to-read Python code :) )
