### ISSUE TITLE
2to3 call for file in current directory yields error

### ISSUE THREAD

**Issue by 1cb85035-97d8-42c3-a287-2706aee5fe65** [python/cpython#75764]
BPO | [31583](https://bugs.python.org/issue31583)
--- | :---
Nosy | @benjaminp, @bitdancer, @ambv, @denis-osipov
PRs | <li>python/cpython#3758</li><li>python/cpython#6528</li><li>python/cpython#6529</li>
Files | <li>[2to3bugpython.png](https://bugs.python.org/file47187/2to3bugpython.png "Uploaded as image/png at 2017-10-03.18:20:43 by jabdo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-11-04.18:06:16.006>
created_at = <Date 2017-09-26.04:58:01.484>
labels = ['3.7', 'type-bug', 'expert-2to3']
title = '2to3 call for file in current directory yields error'
updated_at = <Date 2018-11-04.18:06:16.006>
user = 'https://github.com/denis-osipov'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-04.18:06:16.006>
actor = 'denis-osipov'
assignee = 'none'
closed = True
closed_date = <Date 2018-11-04.18:06:16.006>
closer = 'denis-osipov'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-09-26.04:58:01.484>
creator = 'denis-osipov'
dependencies = []
files = ['47187']
hgrepos = []
issue_num = 31583
keywords = ['patch']
message_count = 9.0
messages = ['303001', '303635', '303636', '303637', '303639', '303647', '315469', '315470', '315474']
nosy_count = 5.0
nosy_names = ['benjamin.peterson', 'r.david.murray', 'lukasz.langa', 'denis-osipov', 'jabdo']
pr_nums = ['3758', '6528', '6529']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31583'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1cb85035-97d8-42c3-a287-2706aee5fe65** [comment]
2to3 doesn't work if called for file in current directory with --add-suffix option.
	
$ /d/repos/cpython/python.bat /d/repos/cpython/Tools/scripts/2to3 -n -W --add-suffix=3 test2to3.py
Running Debug|x64 interpreter...
WARNING: --write-unchanged-files/-W implies -w.
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: Refactored test2to3.py
--- test2to3.py (original)
+++ test2to3.py (refactored)

--some changes--

```pytb
Traceback (most recent call last):
  File "D:/repos/cpython/Tools/scripts/2to3", line 5, in <module>
    sys.exit(main("lib2to3.fixes"))
  File "D:\repos\cpython\lib\lib2to3\main.py", line 259, in main
    options.processes)
  File "D:\repos\cpython\lib\lib2to3\refactor.py", line 687, in refactor
    items, write, doctests_only)
  File "D:\repos\cpython\lib\lib2to3\refactor.py", line 282, in refactor
    self.refactor_file(dir_or_file, write, doctests_only)
  File "D:\repos\cpython\lib\lib2to3\refactor.py", line 728, in refactor_file
    *args, **kwargs)
  File "D:\repos\cpython\lib\lib2to3\refactor.py", line 339, in refactor_file
    write=write, encoding=encoding)
  File "D:\repos\cpython\lib\lib2to3\refactor.py", line 505, in processed_file
    self.write_file(new_text, filename, old_text, encoding)
  File "D:\repos\cpython\lib\lib2to3\main.py", line 84, in write_file
    os.makedirs(output_dir)
  File "D:\repos\cpython\\lib\os.py", line 221, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] The system cannot find the path specified: ''
```



It works well if I use absolute path for target file or set -o:

```sh
$ /d/repos/cpython/python.bat /d/repos/cpython/Tools/scripts/2to3 -n -W --add-suffix=3 /d/MyPythonScripts/test2to3.py

$ /d/repos/cpython/python.bat /d/repos/cpython/Tools/scripts/2to3 -n -W --add-suffix=3 -o . test2to3.py
```

**Comment by cc11ee67-45e4-40f4-8506-6e56835e67cb** [comment]
Issue also effects 3.5

**Comment by bitdancer** [comment]
3.5 is in security-fix-only mode, and we use versions to indicate which versions we plan to fix the bug in.

**Comment by cc11ee67-45e4-40f4-8506-6e56835e67cb** [comment]
Gotcha, sorry about that. Active uses 3.5, so I guess I would take it up
with them?

**Comment by bitdancer** [comment]
Yes, redistributors sometimes backport non-security fixes if they consider them important enough.

Note that I haven't evaluated the merits of this issue, and there is a related issue about how 2to3 finds its fixers that this may overlap with.

**Comment by cc11ee67-45e4-40f4-8506-6e56835e67cb** [comment]
Inserting (with 12 spaces)

```py
            if not output_dir:
                output_dir = "./"
```


at lines 83 and 84 works as a temporary workaround.  `StdoutRefactoringTool` is not receiving an `output_dir` from `option`, which seems to only be an issue when `--add-sufix` is used.
