### ISSUE TITLE
Refactor the enumerate.__next__ implementation

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75766]
BPO | [31585](https://bugs.python.org/issue31585)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka
PRs | <li>python/cpython#3759</li>
Files | <li>[enum_next.diff](https://bugs.python.org/file47235/enum_next.diff "Uploaded as text/plain at 2017-10-24.12:51:13 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-26.05:34:27.541>
created_at = <Date 2017-09-26.05:27:26.063>
labels = ['interpreter-core', 'type-feature', '3.7']
title = 'Refactor the enumerate.__next__ implementation'
updated_at = <Date 2017-10-24.12:51:13.655>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-24.12:51:13.655>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-26.05:34:27.541>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2017-09-26.05:27:26.063>
creator = 'serhiy.storchaka'
dependencies = []
files = ['47235']
hgrepos = []
issue_num = 31585
keywords = ['patch']
message_count = 3.0
messages = ['303006', '303007', '304908']
nosy_count = 2.0
nosy_names = ['rhettinger', 'serhiy.storchaka']
pr_nums = ['3759']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31585'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Currently the large and complex part of enum_next() and enum_next_long() in [Objects/enumobject.c](https://github.com/python/cpython/blob/main/Objects/enumobject.c) is duplicated. This increases the code size and makes harder maintaining the code. The proposed patch refactors the implementation and removes the code duplication.

**Comment by rhettinger** [comment]
Having separate code paths was an intentional decision.  I prefer to keep it that way.

**Comment by serhiy-storchaka** [comment]
Added a patch for history.
