### ISSUE TITLE
SystemError in _collections._count_element() in case of a bad mapping argument

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75767]
BPO | [31586](https://bugs.python.org/issue31586)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3763</li><li>python/cpython#3776</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-09-27.03:46:36.120>
created_at = <Date 2017-09-26.06:32:28.949>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'SystemError in _collections._count_element() in case of a bad mapping argument'
updated_at = <Date 2017-09-27.03:46:36.119>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.03:46:36.119>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-09-27.03:46:36.120>
closer = 'rhettinger'
components = ['Extension Modules']
creation = <Date 2017-09-26.06:32:28.949>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31586
keywords = ['patch']
message_count = 5.0
messages = ['303014', '303016', '303077', '303088', '303089']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3763', '3776']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31586'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes a SystemError:
class BadMapping:
    get = dict.get
    \_\_setitem__ = dict.\_\_setitem__

```py
import _collections
_collections._count_elements(BadMapping(), [42])
```



This is because \_count_elements() (in [Modules/_collectionsmodule.c](https://github.com/python/cpython/blob/main/Modules/_collectionsmodule.c)) assumes
that the mapping argument is a dictionary in case it has the same get() and
\_\_setitem__() methods as dict. And so, \_count_elements() passes the mapping
argument to \_PyDict_GetItem_KnownHash(), which raises the SystemError.


ISTM it is a very unlikely corner case, so that adding a test (as well as
a NEWS.d item) for it is unnecessary.
What do you think?

**Comment by serhiy-storchaka** [comment]
I agree. \_collections.\_count_elements() is an internal function. It should be called only with Counter (which is a dict subclass) or its subclass.

But I think it is worth to make the code more reliable.

**Comment by rhettinger** [comment]
Oren, thank you for the work you've been doing.

**Comment by rhettinger** [comment]
New changeset 31aca4bf79217e6ec4c1d056d3ad7ed4dd469c78 by Raymond Hettinger (Oren Milman) in branch 'master':
bpo-31586: Use \_count_element fast path for real dicts.
https://github.com/python/cpython/commit/31aca4bf79217e6ec4c1d056d3ad7ed4dd469c78

**Comment by rhettinger** [comment]
New changeset a1c49f6f09150f70f063417c8d67a38e59dde7ed by Raymond Hettinger (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31586: Use \_count_element fast path for real dicts. (bpo-3776)
https://github.com/python/cpython/commit/a1c49f6f09150f70f063417c8d67a38e59dde7ed
