### ISSUE TITLE
Documentation Language mixed up

### ISSUE THREAD

**Issue by 95bb1f9d-8709-4062-b7a1-061455e391c9** [python/cpython#75765]
BPO | [31584](https://bugs.python.org/issue31584)
--- | :---
Nosy | @methane, @zware, @JulienPalard, @Mariatta, @asl97
Files | <li>[shot-20170926-28526-p58mc1.jpeg](https://bugs.python.org/file47172/shot-20170926-28526-p58mc1.jpeg "Uploaded as image/jpeg at 2017-09-27.17:23:31 by @asl97")</li><li>[デザインと歴史 FAQ — Python 2.7.14 ドキュメント.html](https://bugs.python.org/file47173/%E3%83%87%E3%82%B6%E3%82%A4%E3%83%B3%E3%81%A8%E6%AD%B4%E5%8F%B2%20FAQ%20%E2%80%94%20Python%202.7.14%20%E3%83%89%E3%82%AD%E3%83%A5%E3%83%A1%E3%83%B3%E3%83%88.html "Uploaded as text/plain at 2017-09-27.17:23:46 by @asl97")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-04-10.13:36:11.544>
created_at = <Date 2017-09-26.05:14:07.896>
labels = ['docs']
title = 'Documentation Language mixed up'
updated_at = <Date 2018-04-10.13:36:11.543>
user = 'https://github.com/asl97'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-10.13:36:11.543>
actor = 'mdk'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-04-10.13:36:11.544>
closer = 'mdk'
components = ['Documentation']
creation = <Date 2017-09-26.05:14:07.896>
creator = 'asl'
dependencies = []
files = ['47172', '47173']
hgrepos = []
issue_num = 31584
keywords = []
message_count = 21.0
messages = ['303004', '303008', '303021', '303023', '303154', '303164', '303165', '303171', '303174', '303175', '303176', '303186', '303991', '304014', '304015', '308846', '308847', '308854', '309044', '315168', '315169']
nosy_count = 6.0
nosy_names = ['methane', 'docs@python', 'zach.ware', 'mdk', 'Mariatta', 'asl']
pr_nums = []
priority = 'high'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31584'
versions = ['Python 2.7']
```

</p></details>

**Comment by 95bb1f9d-8709-4062-b7a1-061455e391c9** [comment]
Some of the documentation language are mixed up.

eg:
Japanese on the English page https://docs.python.org/2.7/faq/design.html
French on the Japanese https://docs.python.org/ja/2.7/faq/design.html

It seem to affect multiple pages:
https://docs.python.org/2.7/bugs.html
https://docs.python.org/2.7/distributing/index.html
https://docs.python.org/2.7/extending/index.html
https://docs.python.org/2.7/extending/extending.html
The c-api pages https://docs.python.org/2.7/c-api/index.html
The faq pages https://docs.python.org/2.7/faq/index.html

And possibly others.

**Comment by Mariatta** [comment]
Indeed a problem! Seems to affect Python 2.7 docs. If not mistaken, Julien worked on the language switcher. Maybe he has some clue ...

**Comment by JulienPalard** [comment]
Hi asl, thanks for reporting I'm looking at it.
Thanks Mariatta for the notification.

**Comment by JulienPalard** [comment]
I'm currently unable to find any misplaced string...

I suspect the "fast builds" may cause the bug and the "full build" may fix it, and I probably checked right after a full build.

I'll test this locally soon (full build in one lang followed by a fast build in another lang) to see if I can reproduice it.

The build cycle is "build english then build french then build japanese", so having english on french is unnoticable, and you noticed french on japanese and japanese on english, so it looks to match with the build pattern.

We may temporarily deactivate fast builds it needed (if it's long to fix) I'll know more after my local tests.

**Comment by JulienPalard** [comment]
Local builds were not able to reproduce the bug for the moment and I did not spotted the bug on production neither. If anyone see it please write down the URL, the misplaced translation, and the date, time, timezone on which the string was found, so I can inspect the server logs.

Did the strings were all over the page, or only a few strings on a normally rendered page?

**Comment by 95bb1f9d-8709-4062-b7a1-061455e391c9** [comment]
Attached is a screenshot of https://docs.python.org/2.7/faq/design.html generated by web-capture.net shortly before this report was created.

It shows the whole content was in Japanese.

On the screenshot, it says it was last updated on Sep 26, 2017.

It was one of the numerous sources I used to verify that it wasn't just my end which was seeing the language mix up.

Unfortunately, that is the only actual screenshot that I have available that was created when it happened.

The browser cache for the English page is also gone but I do have the cache of the Japanese page which was in French.

https://docs.python.org/ja/2.7/faq/design.html
```
HTTP/1.1 200
status: 304
date: Wed, 27 Sep 2017 16:54:12 GMT
via: 1.1 varnish
age: 130544
x-served-by: cache-sin18020-SIN
x-cache: HIT
x-cache-hits: 2
x-timer: S1506531252.204533,VS0,VE0
server: nginx
content-type: text/html
last-modified: Tue, 26 Sep 2017 03:00:31 GMT
etag: "59c9c2cf-146c2"
x-clacks-overhead: GNU Terry Pratchett
accept-ranges: bytes
content-length: 83650
```

**Comment by 95bb1f9d-8709-4062-b7a1-061455e391c9** [comment]
html dump

**Comment by JulienPalard** [comment]
Thanks for those details.

Until we find japanese on a french page, or french on an english page, which would clearly disproove the hypothesis of a build picking up translated files from a previous build, I still consider this hypothesis the good one.

I'm also seeing pages like genindex-位.html on the english directory tree, which is less surprising : the english build may just not remove them.

**Comment by JulienPalard** [comment]
Found another hypothesis: As the builds take a long time, builds may overlap (starting a build while another is still unfinished, typically rsync-ing its files), but this would result in:

- japanese being build while french being rsynced
- french being build while english being rsynced
- english being build while japanese being rsynced

This mean japanese on french pages, french on english pages, and english on japanese pages, which is the other way around, nobody spotted any of this overlaps, so I discard this hypothesis.

**Comment by zware** [comment]
Sounds like we really ought to be building each translation in its own directory so they can't possibly stomp on each other.

**Comment by JulienPalard** [comment]
I'd prefer to understand exacly what is going wrong and fix it, but I agree it would fix the issue and even fix the other hypothesis, so I don't exclude doing it, even if I find the root cause.

I'm currently doing a full build locally (I previously tried building using the [Doc/Makefile](https://github.com/python/cpython/blob/main/Doc/Makefile), was unable to reproduce the bug, I'm now building using the build_docs.py script) it will take like an hour on my laptop, I'll see.

**Comment by JulienPalard** [comment]
I'm still unable to reproduce the bug.

I'm now monitoring the docs.python.org hierarchy whith a:

grep -rl 'définition' /srv/docs.python.org/ja/; grep -rl か /srv/docs.python.org/{2.7,3.6,3.7}

So if it happen again we'll maybe learn more, according to this simple grep the bug is not on production at this time on any page.

**Comment by JulienPalard** [comment]
FTR I'm still daily monitoring the presence of mixed-up pages server side and did not spotted a single one.

I'm still using my very basic:

```sh
  $ grep -rl 'définition' /srv/docs.python.org/ja/; grep -rl か /srv/docs.python.org/{2.7,3.6,3.7}
```

**Comment by methane** [comment]
Japanese HTML has this line:

    <link rel="canonical" href="https://docs.python.org/2/faq/design.html" />

I suspect this line affects CDN's cache.
But I can't find document about canonical link in fastly's document.

**Comment by methane** [comment]
https://twitter.com/miyagawa/status/917629042278359040

Miyagawa-san, the member of Fastly told me they doesn't use HTML
content for cache key, unless we customize VCL.

But I can't find VCL for docs.python.org in github.com/python.
