### ISSUE TITLE
SystemError in class creation in case of a metaclass with a bad __prepare__() method

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75769]
BPO | [31588](https://bugs.python.org/issue31588)
--- | :---
Nosy | @ncoghlan, @ericsnowcurrently, @serhiy-storchaka, @orenmn
PRs | <li>python/cpython#3764</li><li>python/cpython#3790</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.16:28:47.445>
created_at = <Date 2017-09-26.07:38:12.271>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'SystemError in class creation in case of a metaclass with a bad __prepare__() method'
updated_at = <Date 2017-09-27.16:28:47.445>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.16:28:47.445>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.16:28:47.445>
closer = 'ncoghlan'
components = ['Interpreter Core']
creation = <Date 2017-09-26.07:38:12.271>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31588
keywords = ['patch']
message_count = 8.0
messages = ['303019', '303118', '303121', '303122', '303143', '303144', '303146', '303159']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'eric.snow', 'serhiy.storchaka', 'Oren Milman']
pr_nums = ['3764', '3790']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31588'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes a SystemError:
class BadMetaclass(type):
    def \_\_prepare__(*args):
        pass

```py
class Foo(metaclass=BadMetaclass):
    pass
```



This is because builtin___build_class__() assumes that \_\_prepare__() returned a
mapping, and passes it to PyEval_EvalCodeEx(), which passes it to
\_PyEval_EvalCodeWithName(), which passes it to \_PyFrame_New_NoTrack(), which
raises the SystemError.


This issue seems related to bpo-17421.

**Comment by serhiy-storchaka** [comment]
I'm not a metaclass expert. Eric, Nick, could you please take a look at the patch?

**Comment by ncoghlan** [comment]
There's no \_\_prepare__ method in 2.7, so that version can't be affected by this.

For 3.6 and 3.7, I can't reproduce the reported SystemError. Instead, I get:

```
>>> class BadMetaclass(type):
...     def __prepare__(*args):
...         pass
... 
>>> class Foo(metaclass=BadMetaclass):
...     pass
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in Foo
TypeError: 'NoneType' object is not subscriptable

```

The error remains the same if I add `@classmethod` to the __prepare__ definition.


That's still thoroughly cryptic and worth changing, but indicates the test should be checking the error message details, not just the error type.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
```c
Nick, maybe you tried to reproduce in release?
In debug (where I got the SystemError), you have in the beginning of _PyFrame_New_NoTrack():
#ifdef Py_DEBUG
    if (code == NULL || globals == NULL || !PyDict_Check(globals) ||
        (locals != NULL && !PyMapping_Check(locals))) {
        PyErr_BadInternalCall();
        return NULL;
    }
```

**Comment by ncoghlan** [comment]
Aye, that's exactly what I did.

**Comment by ncoghlan** [comment]
New changeset 5837d0418f47933b2e3c139bdee8a79c248a943c by Nick Coghlan (Oren Milman) in branch 'master':
bpo-31588: Validate return value of \_\_prepare__() methods (GH-3764)
https://github.com/python/cpython/commit/5837d0418f47933b2e3c139bdee8a79c248a943c

**Comment by ncoghlan** [comment]
CI is still running for the backport, so I'll merge that tomorrow.

Thanks for the patch!

**Comment by ncoghlan** [comment]
New changeset 084f80b82c564c8a3cef26fc6e56da188a379be2 by Nick Coghlan (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31588: Validate return value of \_\_prepare__() methods (GH-3790)
https://github.com/python/cpython/commit/084f80b82c564c8a3cef26fc6e56da188a379be2
