### ISSUE TITLE
CSV module incorrectly treats escaped newlines as new records if unquoted

### ISSUE THREAD

**Issue by 816d07ce-f06e-45ee-a4a5-a3894602990f** [python/cpython#75771]
BPO | [31590](https://bugs.python.org/issue31590)
--- | :---
Nosy | @terryjreedy, @bitdancer, @mallyvai, @xflr6, @ZackerySpytz
Files | <li>[csv_test.tar](https://bugs.python.org/file47181/csv_test.tar "Uploaded as application/x-tar at 2017-09-30.08:40:51 by @mallyvai")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-06-28.01:58:30.815>
created_at = <Date 2017-09-26.09:28:19.879>
labels = ['type-bug', 'library']
title = 'CSV module incorrectly treats escaped newlines as new records if unquoted'
updated_at = <Date 2020-06-28.01:58:30.814>
user = 'https://github.com/mallyvai'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-28.01:58:30.814>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2020-06-28.01:58:30.815>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-09-26.09:28:19.879>
creator = 'mallyvai'
dependencies = []
files = ['47181']
hgrepos = []
issue_num = 31590
keywords = []
message_count = 9.0
messages = ['303025', '303376', '303381', '303382', '303388', '303401', '309814', '372479', '372492']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'r.david.murray', 'mallyvai', 'xflr6', 'ZackerySpytz', 'Vaibhav Mallya (mallyvai)']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31590'
versions = ['Python 2.7']
```

</p></details>

**Comment by 816d07ce-f06e-45ee-a4a5-a3894602990f** [comment]
I'm writing python `csv` based-parsers as part of a data processing pipeline that includes Redshift and other data stores upstream and down. It's easy and expected in all of these data stores  (http://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html) that CSV-style data can be generated with ESCAPE'd newlines, and with or without quotes on the columns.

Challenge: However, 2.x CSV module has a bug where ESCAPE'd newlines in unquoted CSVs are not actually treated as escaped newlines, but as entirely new record entries. This is at odds with expected behavior in most common data warehouses (See - Redshift docs I linked above for example) and is a subtle source of bugs for data processing pipelines. We changed our Redshift Parameters to ADDQUOTES so we could get around this bug, after some debugging. 

Note - This seems to be a continuation of https://bugs.python.org/issue15927 which was closed as WONTFIX for 2.x. I think this is a legitimate bug, and should be fixed in 2.x. If someone is relying on old / bad behavior might mean something else is wrong. In my view, the current behavior effectively adds an implicit, undocumented dialect to the CSV module.

**Comment by terryjreedy** [comment]
In closing bpo-15927, R. David Murray said "Although this is clearly a bug fix, it also represents a behavior change that could cause a working program to fail.  I have therefore only applied it to 3.4, but I'm open to arguments that it should be backported." 

David, I'll leave you to evaluate the argument presented.

Vaibhav: in the meanwhile, consider moving your pipeline to 3.x or patching your copy of the csv module.  You can put it in sitepackes as csv27.  Or if you are distributing code anyway, include your patched copy with it.

**Comment by bitdancer** [comment]
I'm pretty hesitant to make this kind of change in python2.  I'm going to punt, and let someone else make the decision.  Which means if no one does, the status quo will win.  Sorry about that.

**Comment by 855695c5-8967-4baf-a912-99f43a87f14b** [comment]
If there's any way this can be documented that would be a big help, at
least. There have been other folks who run into this, and the current
behavior is implicit.

On Sep 29, 2017 5:44 PM, "R. David Murray" \<report@bugs.python.org\> wrote:

R. David Murray \<rdmurray@bitdance.com\> added the comment:

I'm pretty hesitant to make this kind of change in python2.  I'm going to
punt, and let someone else make the decision.  Which means if no one does,
the status quo will win.  Sorry about that.

\----------

_______________________________________
Python tracker \<report@bugs.python.org\>
\<https://bugs.python.org/issue31590\>
_______________________________________

**Comment by terryjreedy** [comment]
I explained on bpo-15927 why I currently see it as an enhancement issue, and therefore not appropriate to be backported.  In fact, based on the doc, I am puzzled why the line terminator was being escaped.

**Comment by 816d07ce-f06e-45ee-a4a5-a3894602990f** [comment]
Hello R. David & Terry!

Appreciate your prompt responses. While experimenting with different test cases I realized that escaped slashes and newlines are intrinsically annoying to reason about as stringy-one-liners, so I threw together a small tarball test case - attached - to make sure we're on the same page. 

To be clear, I was referring \*solely* to reading with csv.DictReader (we're not using the writing part).

The assertion for the multi_line_csv_unquoted fails, and I believe it should succeed.

I hadn't considered the design-bug vs code-bug angle. I also think that documenting this somehow - explicitly - would help others, since there's no mention of the interaction here, with what should be a fairly common use-case. It might even make sense to make a "strong recommendation" that everything is quoted + escaped (much as redshift makes a strong recommendation to escape).

Our data pipeline is doing fine after the right parameters on both sides, this is more about improving Python for the rest of the community. Thanks for your help, I will of course respect any decision you make.
