### ISSUE TITLE
expose pthread_getcpuclockid in time module

### ISSUE THREAD

**Issue by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [python/cpython#75777]
BPO | [31596](https://bugs.python.org/issue31596)
--- | :---
Nosy | @vstinner, @benjaminp, @pdox
PRs | <li>python/cpython#3756</li><li>python/cpython#3904</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-05.07:01:58.393>
created_at = <Date 2017-09-26.18:33:14.144>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'expose pthread_getcpuclockid in time module'
updated_at = <Date 2017-10-06.09:03:39.636>
user = 'https://github.com/pdox'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-06.09:03:39.636>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-05.07:01:58.393>
closer = 'benjamin.peterson'
components = ['Extension Modules']
creation = <Date 2017-09-26.18:33:14.144>
creator = 'pdox'
dependencies = []
files = []
hgrepos = []
issue_num = 31596
keywords = []
message_count = 6.0
messages = ['303059', '303743', '303769', '303781', '303800', '303809']
nosy_count = 3.0
nosy_names = ['vstinner', 'benjamin.peterson', 'pdox']
pr_nums = ['3756', '3904']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31596'
versions = ['Python 3.7']
```

</p></details>

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
time.clock_gettime() makes it possible to retrieve the thread-specific cpu-time clock for the current thread using time.CLOCK_THREAD_CPUTIME_ID. However, it is currently not possible in Python to retrieve the thread-specific clock for other threads. Exposing pthread_getcpuclockid() makes this possible.

**Comment by benjaminp** [comment]
New changeset e14679c78464d1e0e16786c2a0e9bcebe49e842b by Benjamin Peterson (pdox) in branch 'master':
closes bpo-31596: Add an interface for pthread_getcpuclockid(3) (bpo-3756)
https://github.com/python/cpython/commit/e14679c78464d1e0e16786c2a0e9bcebe49e842b

**Comment by vstinner** [comment]
The test is too strict, it fails on many buildbots.

Four examples:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%2010.x%20Shared%203.x/builds/1008/steps/test/logs/stdio

\======================================================================
FAIL: test_pthread_getcpuclockid (test.test_time.TimeTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd10/build/Lib/test/test_time.py", line 100, in test_pthread_getcpuclockid
    self.assertLessEqual(t2, t3)
AssertionError: 16.309616 not less than or equal to 16.309358
```


http://buildbot.python.org/all/builders/s390x%20Debian%203.x/builds/1466/steps/test/logs/stdio

\======================================================================
FAIL: test_pthread_getcpuclockid (test.test_time.TimeTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-debian-z/build/Lib/test/test_time.py", line 99, in test_pthread_getcpuclockid
    self.assertLessEqual(t1, t2)
AssertionError: 0.938456056 not less than or equal to 0.8324859600000001
```


http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.x/builds/999/steps/test/logs/stdio

\======================================================================
FAIL: test_pthread_getcpuclockid (test.test_time.TimeTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current.nondebug/build/Lib/test/test_time.py", line 100, in test_pthread_getcpuclockid
    self.assertLessEqual(t2, t3)
AssertionError: 0.813547 not less than or equal to 0.81335
```


http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/996/steps/test/logs/stdio

\======================================================================
FAIL: test_pthread_getcpuclockid (test.test_time.TimeTestCase)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/buildbot/python/3.x.koobs-freebsd-current/build/Lib/test/test_time.py", line 100, in test_pthread_getcpuclockid
    self.assertLessEqual(t2, t3)
AssertionError: 1.121773 not less than or equal to 1.121547
```

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
This looks specific to FreeBSD and s390x. Those platforms might not provide the same cpu-time clock consistency guarantees as Linux+glibc+x86. Would it be ok to just disable the ordering check for those systems?

**Comment by benjaminp** [comment]
New changeset 86566702f311f8e90600e85350f6b6769a384ea5 by Benjamin Peterson in branch 'master':
weaken pthread_getcpuclockid test (more bpo-31596) (bpo-3904)
https://github.com/python/cpython/commit/86566702f311f8e90600e85350f6b6769a384ea5

**Comment by vstinner** [comment]
Thank you Benjamin, buildots are back to green :-)

I prefer the new unit test which only tests pthread_getcpuclockid() clock and not make any assumption on the link between this clock and CLOCK_THREAD_CPUTIME_ID.
