### ISSUE TITLE
ipaddress.hosts() doesn't return anything on a /32 "network"

### ISSUE THREAD

**Issue by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [python/cpython#75778]
BPO | [31597](https://bugs.python.org/issue31597)
--- | :---
Nosy | @ericvsmith, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-26.20:08:18.628>
created_at = <Date 2017-09-26.19:00:01.579>
labels = ['3.7', '3.8', 'type-bug', 'library', 'invalid']
title = 'ipaddress.hosts() doesn\'t return anything on a /32 "network"'
updated_at = <Date 2017-09-26.21:05:49.201>
user = 'https://bugs.python.org/LordAntonHvornum'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-26.21:05:49.201>
actor = 'Lord Anton Hvornum'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-26.20:08:18.628>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-09-26.19:00:01.579>
creator = 'Lord Anton Hvornum'
dependencies = []
files = []
hgrepos = []
issue_num = 31597
keywords = []
message_count = 9.0
messages = ['303063', '303070', '303072', '303073', '303074', '303075', '303076', '303078', '303079']
nosy_count = 3.0
nosy_names = ['eric.smith', 'serhiy.storchaka', 'Lord Anton Hvornum']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31597'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Network.hosts

I couldn't find anywhere in the documentation mentioning the fact that doing the following would return nothing:

```pycon
>>> import ipaddress
>>> net = ipaddress.ip_network('127.0.0.1/32')
>>> list(net.hosts())
[]
```


For all intense and purposes, that network still contains hosts.
That being one single lonely host of '127.0.0.1'.

It's illogical to not return any hosts if there actually are one or more in there.
Now the programmer has to do a one-off-check to see if this particular defined network (of a huge list usually)
happens to end with /32, then it needs to treat the item not as a defined network (even tho it is with a netmask),
but rather strip the netmask and treat it as a single host entity.. It makes no sense if you're iterating over a huge list of network infrastructure.

**Comment by serhiy-storchaka** [comment]
This is documented.

```py
 hosts()
```


    Returns an iterator over the usable hosts in the network. The usable hosts are all the IP addresses that belong to the network, except the network address itself and the network broadcast address.

```pycon
>>> import ipaddress
>>> ipaddress.ip_network('127.0.0.1/32').network_address
IPv4Address('127.0.0.1')
>>> ipaddress.ip_network('127.0.0.1/32').broadcast_address
IPv4Address('127.0.0.1')
```

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
This is still a very strange behavior and I can't see why this still
shouldn't return a IP address.
if the broadcast, network and host address are all the same, that should
call for a exceptional behavior from the library.
Because 127.0.0.1/32 is still a usable host address, and it's a way of
isolating a host on a network device for instance, but it's still a host
address in there.. Or am i loosing my marbles?

**Comment by serhiy-storchaka** [comment]
Because this is a definition of this method.

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
And this definition is some how immutable?

**Comment by ericvsmith** [comment]
Yes, due to backward compatibility constraints, the behavior is immutable.

You might be able to argue for another method, say all_hosts(), or something. Or maybe even a optional parameter to hosts() that defaults to the existing behavior, but if provided, lets you select a new behavior.

What I would not support is a change to hosts() (or a new method) that treats a /32 network specially.

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
I was actually just thinking about the same thing, why not just add a
optional flag to the already existing function.
I get that people are way into backward compatibility, and I won't get into
a religious fight over that particular topic as long as there's a fix for
this honestly strange behavior. (It's some Windows mentality saying a /32
network doesn't contain any hosts when you come from a network background).

Seeing as this is apparently a touchy subject, I won't even try to submit a
patch for this because I will screw this up.
So I politely ask someone with more intricate knowledge of this library,
it's history and use to add a totally optional flag that returns the single
host on this very narrow network called /32.

**Comment by ericvsmith** [comment]
You lost me at "some Windows mentality". I come from a networking background.

Sorry, I don't care enough about this issue to pursue it.

**Comment by 18d1b506-fcb1-4c1d-8275-7cdc1dd5653c** [comment]
Historically Windows have struggled with /32 assigned networks.
Trying to push such a network address to a Windows machine has usually (not
all cases) rendered it connection-less, where as switches, routers, \*nix
etc have never had any major issues with the logic of a /32 network host
isolation.

Anyway, it was a slight joke/peck on the history of networking.
