### ISSUE TITLE
Preferring MSVC 2017 in Python 3.6.x new minor releases

### ISSUE THREAD

**Issue by 699aa770-10df-492d-aaa0-dc43011258cc** [python/cpython#75776]
BPO | [31595](https://bugs.python.org/issue31595)
--- | :---
Nosy | @pfmoore, @tjguk, @ned-deily, @merwok, @zware, @zooba, @dstufft, @xoviat

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-09-26.19:33:15.712>
created_at = <Date 2017-09-26.18:07:03.541>
labels = ['type-feature', 'library', 'OS-windows']
title = 'Preferring MSVC 2017 in Python 3.6.x new minor releases'
updated_at = <Date 2017-09-26.23:10:16.532>
user = 'https://github.com/xoviat'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-26.23:10:16.532>
actor = 'xoviat'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-09-26.19:33:15.712>
closer = 'steve.dower'
components = ['Distutils', 'Windows']
creation = <Date 2017-09-26.18:07:03.541>
creator = 'xoviat'
dependencies = []
files = []
hgrepos = []
issue_num = 31595
keywords = []
message_count = 4.0
messages = ['303057', '303060', '303068', '303082']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'ned.deily', 'eric.araujo', 'zach.ware', 'steve.dower', 'dstufft', 'xoviat']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31595'
versions = ['Python 3.6']
```

</p></details>

**Comment by 699aa770-10df-492d-aaa0-dc43011258cc** [comment]
MSVC 2017 retains ABI compatibility with MSVC 2015, yet supports (as always with a newer compiler version) more features and compiles faster. Because it retains ABI compatibility with existing Python versions, I think it makes sense for distutils to prefer it (this could be fixed in setuptools, but distutils generally takes care of compiler detection).

Thoughts?

**Comment by zware** [comment]
3.5 is in security-fix-only mode, so it will not receive such an update.  3.6 is up to Ned and Steve.

**Comment by zooba** [comment]
Let me hop in my time machine and fix that for you: https://github.com/python/cpython/pull/3425

(FWIW, I think it makes \*much* more sense for setuptools to fix this by simply forking all of distutils and never looking back. But since we don't live in that world yet, it went into distutils.)

**Comment by 699aa770-10df-492d-aaa0-dc43011258cc** [comment]
@zooba

Since you mention it, I agree with that proposal. But currently we have core developers contributing to distutils and @jaraco contributing to setuptools. @jaraco is quite competent, but I doubt that he would be able to maintain an independent fork of distutils by himself.

In short, I think your proposal is a good one, but how can we allocate manpower?
