### ISSUE TITLE
Make bytes and bytearray maketrans accept dictionaries as first argument as it's done in str

### ISSUE THREAD

**Issue by fa9207e6-7e78-46b2-bb5b-e2a58d55a9d7** [python/cpython#75775]
BPO | [31594](https://bugs.python.org/issue31594)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-25.21:33:59.916>
created_at = <Date 2017-09-26.16:04:49.513>
labels = ['interpreter-core', 'type-feature', '3.7']
title = "Make bytes and bytearray maketrans accept dictionaries as first argument as it's done in str"
updated_at = <Date 2021-10-25.21:33:59.916>
user = 'https://bugs.python.org/oleksandrsuvorov'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-25.21:33:59.916>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-25.21:33:59.916>
closer = 'iritkatriel'
components = ['Interpreter Core']
creation = <Date 2017-09-26.16:04:49.513>
creator = 'oleksandr.suvorov'
dependencies = []
files = []
hgrepos = []
issue_num = 31594
keywords = []
message_count = 6.0
messages = ['303048', '303049', '303051', '303053', '303056', '303377']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'serhiy.storchaka', 'oleksandr.suvorov']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31594'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Could you please provide more information? What the problem you want to solve?

**Comment by fa9207e6-7e78-46b2-bb5b-e2a58d55a9d7** [comment]
str.maketrans in python3 is able to accept just one argument which is a
mapping of translations.
While bytearray and bytes are still using only old way where you should
pass two iterables from and to.

static str.maketrans(x [,y [,z]])
static bytes.maketrans(from, to)
static bytearray.maketrans(from, to)

**Comment by serhiy-storchaka** [comment]
Why do you need this functionality?

**Comment by fa9207e6-7e78-46b2-bb5b-e2a58d55a9d7** [comment]
This change requested just because I find it inconsistent and passing
translation as key-value is much easier to read rather than two lists.
When translation table gets bigger than 10 pairs it gets annoying to match
in the head between from and to while reading it.
Could be marked as minor.
\----------_________________________

> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue31594\>
> _______________________________________
>

**Comment by serhiy-storchaka** [comment]
Inconsistency is a weak argument. It itself is not enough to add a new feature. str.translate() accepts a mapping instead of a string (as it would be for consistency with bytes.translate()) because it would be inconvenient to provide a 1114112-character string. str.maketrans() just compile a mapping in the optimized representation, because using a general mapping is not very efficient.

A bytes object of length 256 already is the most efficient representation of the translation table for bytes. And you can create it from a mapping in Python:

```py
def mymaketrans(mapping):
    table = bytearray(range(256))
    for x, y in mapping.items():
        table[x] = y
    return table
```

**Comment by terryjreedy** [comment]
Consistency between bytes and strings is not much of a concern here, or the change would have been make for bytes when it was made for strings.  I would not approve the request without knowing who chose not to and why.

I think an example like
t = bytes.maketrans(
    b'ABCDEVGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz',
    b'vcccvcccvcccccvcccccvcscscvcccvcccvcccccvcccccvcscsc')
is \*much* better as it is than as a dict.
