### ISSUE TITLE
assertion failure in zipimporter.get_source() in case of a bad zlib.decompress()

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75783]
BPO | [31602](https://bugs.python.org/issue31602)
--- | :---
Nosy | @brettcannon, @orenmn
PRs | <li>python/cpython#3784</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brettcannon'
closed_at = <Date 2017-09-29.18:35:09.294>
created_at = <Date 2017-09-27.06:24:51.408>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'assertion failure in zipimporter.get_source() in case of a bad zlib.decompress()'
updated_at = <Date 2017-09-29.18:35:09.293>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-29.18:35:09.293>
actor = 'brett.cannon'
assignee = 'brett.cannon'
closed = True
closed_date = <Date 2017-09-29.18:35:09.294>
closer = 'brett.cannon'
components = ['Extension Modules']
creation = <Date 2017-09-27.06:24:51.408>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31602
keywords = ['patch']
message_count = 2.0
messages = ['303100', '303351']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'Oren Milman']
pr_nums = ['3784']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31602'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes an assertion failure (in case there exists a
compressed zip file named 'foo.zip' with a file called 'bar.py' in it):

```py
import zlib
import zipimport
def bad_decompress(*args):
    return None

zlib.decompress = bad_decompress
zipimport.zipimporter('foo.zip').get_source('bar')
```



This is because get_data() (in [Modules/zipimport.c](https://github.com/python/cpython/blob/main/Modules/zipimport.c)) assumes that
zlib.decompress() returned a bytes object, and returns it.
zipimport_zipimporter_get_source_impl() assumes that get_data() returned a
bytes object, and passes it to PyBytes_AS_STRING(), which asserts it is a bytes
object.

**Comment by brettcannon** [comment]
New changeset 01c6a8859ef2ff5545a87cf537573bd342c848bf by Brett Cannon (Oren Milman) in branch 'master':
bpo-31602: Fix an assertion failure in zipimporter.get_source() in case of a bad zlib.decompress() (GH-3784)
https://github.com/python/cpython/commit/01c6a8859ef2ff5545a87cf537573bd342c848bf
