### ISSUE TITLE
Add listsize in pdb.py

### ISSUE THREAD

**Issue by matrixise** [python/cpython#75788]
BPO | [31607](https://bugs.python.org/issue31607)
--- | :---
Nosy | @rhettinger, @bitdancer, @matrixise
PRs | <li>python/cpython#3787</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-14.14:58:26.949>
created_at = <Date 2017-09-27.10:22:08.788>
labels = ['3.8', 'type-feature', '3.7']
title = 'Add listsize in pdb.py'
updated_at = <Date 2018-05-14.14:58:26.947>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-14.14:58:26.947>
actor = 'matrixise'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-14.14:58:26.949>
closer = 'matrixise'
components = []
creation = <Date 2017-09-27.10:22:08.788>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 31607
keywords = ['patch']
message_count = 6.0
messages = ['303123', '303136', '303138', '303157', '303206', '316515']
nosy_count = 3.0
nosy_names = ['rhettinger', 'r.david.murray', 'matrixise']
pr_nums = ['3787']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31607'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by matrixise** [comment]
I just added a new command for the prompt of Pdb.

(Pdb) listsize
List size: 10
(Pdb) listsize 5
List size: 5
(Pdb) listsize
List size: 5

I will publish a PR

**Comment by bitdancer** [comment]
It isn't obvious from your description here what 'listsize' does.  I think you should have provided some more motivating details :)

Looking at your PR, this is essentially a configuration setting.  I wonder if we should think about the general problem rather than continuing to clutter the top level command namespace.  (The only current example of this I spotted in the pdb docs is display/undisplay.)

**Comment by matrixise** [comment]
Hi David,

It's my fault and you are right, I didn't give the right description.

By default when you want to list the source code with pdb, you will use the list command but this one is just limited to the 10 next lines and there is no possibility to change this limit of 10 lines.

We can play with the second parameter of pdb, examples:

* list 10, 11
will show the code from the line 10 to 11

* list 10, 50
will show the code from the line 10 to 50

* list 10, 5
will show the code from the line 10 and the next 5 lines.

* list
will show from the current position and the next 10 lines.

and my first question was, why this limit exists? Could we change that?

after, I have read the doc of gdb and I have seen there was a "set linesize count" option where you can configure the number of lines to show.

Here is the reason of my proposal.

For the configuration of pdb, I am interested, I know we can use the .pdbrc file but it is really interesting if we desire to add new aliases or add new commands for the breakpoints.


Here is an other example for this issue:

./python -m pdb demo.py
 
> demo.py(1)\<module\>()
-\> import os
(Pdb) listsize 5
List size: 5
(Pdb) l
  1  -\>	import os
  2  	import sys
  3  	
  4  	def main():
  5  	    print(f"CWD: {sys.getcwd()}")
  6  	    print(f"PID: {sys.getpid()}")
(Pdb) l
  7  	
  8  	if \_\_name__ == '\_\_main__':
  9  	    main()
[EOF]
(Pdb)

**Comment by rhettinger** [comment]
I don't think this is worth adding a separate command.

If some controls were needed (changing the list size has not been requested before), it may be better to follow gdb with set/get commands that could be used for other parameters as well.

**Comment by matrixise** [comment]
Raymond,

+1 for the set/get commands for the parameters.

I could update my PR with your suggestions.

Stephane
