### ISSUE TITLE
crash in methods of a subclass of _collections.deque with a bad __new__()

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75789]
BPO | [31608](https://bugs.python.org/issue31608)
--- | :---
Nosy | @rhettinger, @benjaminp, @serhiy-storchaka, @orenmn, @miss-islington
PRs | <li>python/cpython#3788</li><li>python/cpython#9177</li><li>python/cpython#9179</li><li>python/cpython#9178</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2018-09-11.18:46:58.886>
created_at = <Date 2017-09-27.10:43:58.369>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'crash in methods of a subclass of _collections.deque with a bad __new__()'
updated_at = <Date 2020-12-08.13:23:48.376>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-08.13:23:48.376>
actor = 'benjamin.peterson'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2018-09-11.18:46:58.886>
closer = 'benjamin.peterson'
components = ['Extension Modules']
creation = <Date 2017-09-27.10:43:58.369>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31608
keywords = ['patch']
message_count = 7.0
messages = ['303125', '303133', '304000', '325049', '325054', '325055', '325057']
nosy_count = 5.0
nosy_names = ['rhettinger', 'benjamin.peterson', 'serhiy.storchaka', 'Oren Milman', 'miss-islington']
pr_nums = ['3788', '9177', '9179', '9178']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31608'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes the interpreter to crash:

```py
import _collections
class BadDeque(_collections.deque):
    def __new__(cls, *args):
        if len(args):
            return 42
        return _collections.deque.__new__(cls)
```


BadDeque() * 42

(The interpreter would crash also if we replaced 'BadDeque() * 42' with
'BadDeque() + \_collections.deque([42])'.)

This is because deque_copy() (in [Modules/_collectionsmodule.c](https://github.com/python/cpython/blob/main/Modules/_collectionsmodule.c)) returns whatever
BadDeque() returned, without verifying it is a deque.
deque_repeat() assumes that deque_copy() returned a deque, and passes it to
deque_inplace_repeat(), which assumes it is a deque, and crashes.

(Similarly, deque_concat() assumes that deque_copy() returned a deque, which
is the reason for the other crash.)


ISTM it is a very unlikely corner case, so that adding a test (as well as
a NEWS.d item) for it is unnecessary.
What do you think?

**Comment by serhiy-storchaka** [comment]
All other sequence objects return an instance of the base class rather than a subclass. list, tuple, str, bytes, bytearray, array. Only deque tries to create an instance of a subclass.

**Comment by serhiy-storchaka** [comment]
I meant that if make deque.copy(), deque.\_\_add__() and deque.\_\_mul__() returning an exact deque for subclasses, this would make the deque class more consistent with other collections and solve this issue. This could even make them (almost) atomic.
