### ISSUE TITLE
please allow association of google login with current account on bug tracker

### ISSUE THREAD

**Issue by d56b526f-0816-4fc8-89c7-97360296de39** [python/cpython#75781]
BPO | [31600](https://bugs.python.org/issue31600)
--- | :---
Nosy | @wt, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.06:50:43.443>
created_at = <Date 2017-09-27.06:20:32.159>
labels = []
title = 'please allow association of google login with current account on bug tracker'
updated_at = <Date 2017-09-27.06:50:43.440>
user = 'https://github.com/wt'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.06:50:43.440>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.06:50:43.443>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-09-27.06:20:32.159>
creator = 'wt'
dependencies = []
files = []
hgrepos = []
issue_num = 31600
keywords = []
message_count = 2.0
messages = ['303097', '303107']
nosy_count = 2.0
nosy_names = ['wt', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31600'
versions = []
```

</p></details>

**Comment by d56b526f-0816-4fc8-89c7-97360296de39** [comment]
I have a Google account. Unfortunately, I had a bugs.python.org account before using the Google auth. Now I cannot seem to attach my Google auth to this account. When I try to login with Google now, it just tells me that an account with my email address already exists.

I hope this is a reasonable place to report bugs for the bug tracker.

**Comment by serhiy-storchaka** [comment]
http://psf.upfronthosting.co.za/roundup/meta is a place to report bugs for the bug tracker.
