### ISSUE TITLE
Availability of utimensat, futimens not checked correctly on macOS

### ISSUE THREAD

**Issue by bba6fca5-7452-47f9-b329-3366a9a3e529** [python/cpython#75782]
BPO | [31601](https://bugs.python.org/issue31601)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @jmroot, @moreati, @indygreg

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-12-08.10:25:06.093>
created_at = <Date 2017-09-27.06:23:40.145>
labels = ['build', '3.7', 'type-crash']
title = 'Availability of utimensat, futimens not checked correctly on macOS'
updated_at = <Date 2020-12-08.10:25:06.092>
user = 'https://github.com/jmroot'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-08.10:25:06.092>
actor = 'jmr'
assignee = 'none'
closed = True
closed_date = <Date 2020-12-08.10:25:06.093>
closer = 'jmr'
components = ['Cross-Build']
creation = <Date 2017-09-27.06:23:40.145>
creator = 'jmr'
dependencies = []
files = []
hgrepos = []
issue_num = 31601
keywords = []
message_count = 7.0
messages = ['303098', '303386', '330010', '330122', '349515', '349537', '382722']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'jmr', 'Alex.Willmer', 'indygreg', 'Peter Petrik', 'Peter Petrik2']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31601'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by bba6fca5-7452-47f9-b329-3366a9a3e529** [comment]
The futimens and utimensat functions are available in High Sierra but not previous versions of macOS. Building against the 10.13 SDK and deploying to an earlier version will result in a crash when the dynamic linker can't find the symbols at runtime. Availability of the symbols needs to be checked at runtime before use.

This was originally reported in \<https://trac.macports.org/ticket/54893\>.

**Comment by ronaldoussoren** [comment]
This is true for other symbols as well, when deploying to older releases of macOS. 

I have added runtime checking for a number of symbols in the past, that could be extended to newer APIs.  

--
On the road, hence brief. 

Op 30 sep. 2017 om 09:17 heeft Terry J. Reedy \<report@bugs.python.org\> het volgende geschreven:

> 
> Change by Terry J. Reedy \<tjreedy@udel.edu\>:
> 
> 
> \----------
> components: +macOS
> nosy: +ned.deily, ronaldoussoren
> title: Availability of utimensat and futimens not checked correctly on macOS -\> Availability of utimensat,futimens not checked correctly on macOS
> 
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue31601\>
> _______________________________________
