### ISSUE TITLE
unittest.TestLoader().loadTestsFromTestCase(...) fails when adding test cases with the expectedFailure decorator

### ISSUE THREAD

**Issue by 9d30888a-2d68-4fd0-a072-c8711cca9f17** [python/cpython#75785]
BPO | [31604](https://bugs.python.org/issue31604)
--- | :---
Nosy | @rbtcollins, @ezio-melotti, @voidspace, @kwarunek, @iritkatriel
Files | <li>[mwe.py](https://bugs.python.org/file47170/mwe.py "Uploaded as text/plain at 2017-09-27.08:16:44 by Erasmus Cedernaes"): Minimum working example</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-10.16:21:47.683>
created_at = <Date 2017-09-27.08:16:44.803>
labels = ['type-bug', 'tests']
title = 'unittest.TestLoader().loadTestsFromTestCase(...) fails when adding test cases with the expectedFailure decorator'
updated_at = <Date 2021-05-10.16:21:47.680>
user = 'https://bugs.python.org/ErasmusCedernaes'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-10.16:21:47.680>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-05-10.16:21:47.683>
closer = 'iritkatriel'
components = ['Tests']
creation = <Date 2017-09-27.08:16:44.803>
creator = 'Erasmus Cedernaes'
dependencies = []
files = ['47170']
hgrepos = []
issue_num = 31604
keywords = []
message_count = 3.0
messages = ['303112', '303282', '393417']
nosy_count = 6.0
nosy_names = ['rbcollins', 'ezio.melotti', 'michael.foord', 'kwarunek', 'Erasmus Cedernaes', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31604'
versions = ['Python 2.7']
```

</p></details>

**Comment by 9d30888a-2d68-4fd0-a072-c8711cca9f17** [comment]
How to reproduce:
* Run the attached file with Python 2.7 without any modifications. This will produce an error, as described below.
* Uncomment line 2 (the decorator @unittest.expectedFailure) and run the file with Python 2.7. This will not produce an error.

Description:
Adding the decorator @unittest.expectedFailure to a unittest.TestCase causes the TestLoader().loadTestsFromTestCase(...) to fail with the following output:

\===============================================================
```pytb
$ python2.7 mwe.py
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "[...]/mwe.py", line 12, in <module>
    tests = unittest.TestLoader().loadTestsFromTestCase(TestClassThatFails)
  File "/usr/lib/python2.7/unittest/loader.py", line 50, in loadTestsFromTestCase
    if issubclass(testCaseClass, suite.TestSuite):
TypeError: issubclass() arg 1 must be a class
```

==============================================================

The error does only occur when adding the test manually to a test suite. Running unittest.main(), does not produce the error.

**Comment by 43a930ce-92ff-472e-b021-f9644eabb63f** [comment]
AFAIK this helper is meant to be used with test function not the TestCases.
