### ISSUE TITLE
bug in doctest when comparing - 0.0 == 0.0

### ISSUE THREAD

**Issue by 92298fb5-0d22-4c55-a936-3f384ee2a2d4** [python/cpython#75780]
BPO | [31599](https://bugs.python.org/issue31599)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-27.00:43:48.426>
created_at = <Date 2017-09-26.22:02:58.572>
labels = ['invalid']
title = 'bug in doctest when comparing - 0.0 == 0.0'
updated_at = <Date 2017-09-27.00:43:48.425>
user = 'https://bugs.python.org/ZVincius'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-27.00:43:48.425>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-27.00:43:48.426>
closer = 'r.david.murray'
components = []
creation = <Date 2017-09-26.22:02:58.572>
creator = 'Z\xc3\xa9 Vin\xc3\xadcius'
dependencies = []
files = []
hgrepos = []
issue_num = 31599
keywords = []
message_count = 4.0
messages = ['303081', '303083', '303084', '303085']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'Z\xc3\xa9 Vin\xc3\xadcius']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31599'
versions = []
```

</p></details>

**Comment by 92298fb5-0d22-4c55-a936-3f384ee2a2d4** [comment]
See https://github.com/pytest-dev/pytest/issues/2796#event-1266625358

**Comment by bitdancer** [comment]
Can you explain why you think that is a bug in doctest?  It looks like you are getting different output than you expect, but that by itself wouldn't be a bug in doctest.

**Comment by bitdancer** [comment]
To be clear: doctest compares strings, so "-0.0" is not the same as "0.0" to doctest.

**Comment by 92298fb5-0d22-4c55-a936-3f384ee2a2d4** [comment]
Hi R. David Murray,

doctest compares strings, so "-0.0" is not the same as "0.0" to doctest

Thank you. That explains why "-0.0 == 0.0" is True to Python, but False to
doctest.

Cheers,
Zé
