### ISSUE TITLE
Building 3.6 fails on Windows

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75793]
BPO | [31612](https://bugs.python.org/issue31612)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @jkloth, @zware, @serhiy-storchaka, @zooba
Files | <li>[build.log](https://bugs.python.org/file47171/build.log "Uploaded as text/x-log at 2017-09-27.13:55:22 by @serhiy-storchaka")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-02.23:14:19.503>
created_at = <Date 2017-09-27.13:55:22.836>
labels = ['build', 'OS-windows']
title = 'Building 3.6 fails on Windows'
updated_at = <Date 2019-08-02.23:14:19.502>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-02.23:14:19.502>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-02.23:14:19.503>
closer = 'steve.dower'
components = ['Build', 'Windows']
creation = <Date 2017-09-27.13:55:22.836>
creator = 'serhiy.storchaka'
dependencies = []
files = ['47171']
hgrepos = []
issue_num = 31612
keywords = []
message_count = 9.0
messages = ['303141', '303142', '303145', '303147', '303148', '303149', '303152', '303153', '303163']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'jkloth', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31612'
versions = ['Python 3.6']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
makefile.vc(1076): fatal error U1087: cannot have : and :: dependents for same target [C:\\Users\\Serhiy Storchaka\\py\\cpython3.6\\PCbuild\\tcl.vcxproj]

The full log is attached.

**Comment by vstinner** [comment]
How did you build Python 3.6 on Windows? Did you use Visual Studio 2015? Do you use Visual Studio GUI or in the command line?

**Comment by serhiy-storchaka** [comment]
I have installed Visual Studio 2017 and have ran PCbuild\\build.bat.

From the master branch all have built successfully.

**Comment by vstinner** [comment]
> I have installed Visual Studio 2017 and have ran PCbuild\\build.bat.

Oh, I think that VS 2017 is a new feature of Python 3.7 (master), no?

Steve Dower, or Zachary Ware: can you confirm?

See bpo-31340 and bpo-30389.

**Comment by vstinner** [comment]
Here are my notes on how to compile CPython on Windows:
https://haypo-notes.readthedocs.io/cpython_windows.html#python-and-visual-studio-version-matrix

**Comment by pfmoore** [comment]
I believe that's the case, although I'm somewhat surprised by the nature of the error. I'm just checking diffs at the moment.

But VS 2015 is the officially supported compiler for 3.6.

**Comment by serhiy-storchaka** [comment]
> https://haypo-notes.readthedocs.io/cpython_windows.html#python-and-visual-studio-version-matrix

Thank you Victor.

Therefore I do need to install 4 versions of Visual Studio for building three major maintained branches: 2008, 2010, 2015 and 2017? Oh, now I understand why Victor doesn't have sufficient disk space for running tests.

**Comment by vstinner** [comment]
To compile Python 2.7, you need VS 2008 \*and* 2010.

To compile Python 3.5, 3.6 or master, you need VS 2015.

To compile Python 3.4, you need VS 2010.

I had to work on Python 2.7, 3.4, 3.5, 3.6 and master, so I installed VS 2008, 2010 and 2015 :-)

I didn't give a try to VS 2017 yet. I'm fine with 3 VS versions installed in parallel ;-)

**Comment by zooba** [comment]
If you install VS 2017 and select the "Python native development" option as described in the dev guide, you get the correct compilers (plural) for Python 3.5 onwards. The build.bat file (specifically, the find_msbuild.bat helper) will choose the correct version.

You do not need to install VS 2015 anymore. VS 2015 and VS 2017 both include VC toolset v140, which is the officially supported compiler (the VS version is separate).

The error is coming from the Tcl makefile at these lines:

.SUFFIXES:
.SUFFIXES:.c .rc

I personally have no idea what these mean or why it is failing, and I don't even know what these are meant to do. But perhaps you have some file called ".SUFFIXES" or similar that is causing the Tcl build to fail?
