### ISSUE TITLE
can't list groupby generator without breaking the sub groups generators

### ISSUE THREAD

**Issue by 9b1a7a3f-6736-4ab6-819b-cdb360447917** [python/cpython#75795]
BPO | [31614](https://bugs.python.org/issue31614)
--- | :---
Nosy | @rhettinger, @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-09-27.21:29:33.528>
created_at = <Date 2017-09-27.20:55:49.086>
labels = ['type-bug', 'invalid']
title = "can't list groupby generator without breaking the sub groups generators"
updated_at = <Date 2017-09-28.19:26:42.662>
user = 'https://bugs.python.org/LocLeLoarer'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-28.19:26:42.662>
actor = 'Lo\xc3\xafc Le Loarer'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-09-27.21:29:33.528>
closer = 'rhettinger'
components = []
creation = <Date 2017-09-27.20:55:49.086>
creator = 'Lo\xc3\xafc Le Loarer'
dependencies = []
files = []
hgrepos = []
issue_num = 31614
keywords = []
message_count = 4.0
messages = ['303180', '303183', '303221', '303270']
nosy_count = 3.0
nosy_names = ['rhettinger', 'eric.smith', 'Lo\xc3\xafc Le Loarer']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31614'
versions = ['Python 2.7', 'Python 3.5']
```

</p></details>

**Comment by 9b1a7a3f-6736-4ab6-819b-cdb360447917** [comment]
If I "list" the itertools groupby generator, then the sub generators of each groups are all empty except the last one.

```py
import itertools as i
L = ['azerty','abcd','ac','aaa','z','baba','bitte','rhum','z','y']
g = list(i.groupby(L, lambda x: x[0]))
number_of_groups = len(g)
ans = 0
for k, v in g: # This doesn't work
#for k, v in i.groupby(L, lambda x: x[0]): # This works
    v = list(v)
    print(k,v,len(v))
    ans += 100*len(v)//number_of_groups
print(ans)
assert(ans == 163)
I don't understand why. Is my code broken ?
```


The need for saving the group generator first exists when I need the number of groups before walking thru the groups, like in the above example.

I have not been able to test to latest python versions, is the problem already fixed ?

**Comment by rhettinger** [comment]
Except for display the last few elements, this is the documented and intended behavior: ( https://docs.python.org/3/library/itertools.html#itertools.groupby ):

'''
The returned group is itself an iterator that shares the underlying iterable with groupby(). Because the source is shared, when the groupby() object is advanced, the previous group is no longer visible. So, if that data is needed later, it should be stored as a list:

```py
groups = []
uniquekeys = []
data = sorted(data, key=keyfunc)
for k, g in groupby(data, keyfunc):
    groups.append(list(g))      # Store group iterator as a list
    uniquekeys.append(k)
'''
```


The display of the last few elements isn't supposed to happen.  That is being fixed so that all of the subiterator results are empty when the parent iterator is exhausted.

**Comment by ericvsmith** [comment]
Loïc Le Loarer: Note that your use case isn't possible, anyway. There's no way to know the number of groups until the input is exhausted, at which point you've already iterated through all of the data.

**Comment by 9b1a7a3f-6736-4ab6-819b-cdb360447917** [comment]
Thanks a lot for the clear answer, sorry for not having read the online documentation, I only read the help(itertools.groupby) which has much less details.

And for my use case, I can use an explicit command just to compute the number of groups.
