### ISSUE TITLE
PCbuild\clean.bat fails if the path contains whitespaces

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75790]
BPO | [31609](https://bugs.python.org/issue31609)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba
PRs | <li>python/cpython#4280</li><li>python/cpython#4285</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-11-05.00:25:42.275>
created_at = <Date 2017-09-27.10:49:26.537>
labels = ['type-bug', '3.7', 'OS-windows', 'build']
title = 'PCbuild\\clean.bat fails if the path contains whitespaces'
updated_at = <Date 2017-11-05.00:25:42.274>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-05.00:25:42.274>
actor = 'steve.dower'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-11-05.00:25:42.275>
closer = 'steve.dower'
components = ['Build', 'Windows']
creation = <Date 2017-09-27.10:49:26.537>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31609
keywords = ['patch']
message_count = 3.0
messages = ['303126', '305579', '305581']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = ['4280', '4285']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31609'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
C:\\Users\\Serhiy Storchaka\\py\\cpython3.6-debug\>PCbuild\\clean.bat
'C:\\Users\\Serhiy' is not recognized as an internal or external command,
operable program or batch file.

**Comment by zooba** [comment]
New changeset aed08562220974b5c67371b908f23caa1be07e38 by Steve Dower in branch 'master':
bpo-31609: Fixes quotes in [PCbuild/clean.bat](https://github.com/python/cpython/blob/main/PCbuild/clean.bat) (bpo-4280)
https://github.com/python/cpython/commit/aed08562220974b5c67371b908f23caa1be07e38

**Comment by zooba** [comment]
New changeset f4443562345130c991fded3dc3b02b94aee0f362 by Steve Dower (Miss Islington (bot)) in branch '3.6':
bpo-31609: Fixes quotes in [PCbuild/clean.bat](https://github.com/python/cpython/blob/main/PCbuild/clean.bat) (GH-4280) (bpo-4285)
https://github.com/python/cpython/commit/f4443562345130c991fded3dc3b02b94aee0f362
