### ISSUE TITLE
os.path.join() return wrong value in windows

### ISSUE THREAD

**Issue by 1f374817-ea4c-4fd4-8797-34a4b9803b71** [python/cpython#75798]
BPO | [31617](https://bugs.python.org/issue31617)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @quangnt

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-28.11:33:46.854>
created_at = <Date 2017-09-28.11:09:21.340>
labels = ['type-bug', 'invalid', 'OS-windows']
title = 'os.path.join() return wrong value in windows'
updated_at = <Date 2017-09-28.11:33:46.852>
user = 'https://github.com/quangnt'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-28.11:33:46.852>
actor = 'eryksun'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-28.11:33:46.854>
closer = 'eryksun'
components = ['Windows']
creation = <Date 2017-09-28.11:09:21.340>
creator = 'triquang'
dependencies = []
files = []
hgrepos = []
issue_num = 31617
keywords = []
message_count = 2.0
messages = ['303216', '303223']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'triquang']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31617'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1f374817-ea4c-4fd4-8797-34a4b9803b71** [comment]
In windows if we use os.path.join('C:\\\\Test\\\\UnitTest', '/Page') ==\> It returns 'C:/Page' ==\> It should be 'C:\\\\Test\\\\UnitTest/Page'.

**Comment by eryksun** [comment]
This is explained in the docs:

    Join one or more path components intelligently.... If a 
    component is an absolute path, all previous components are 
    thrown away and joining continues from the absolute path 
    component. On Windows, the drive letter is not reset when 
    an absolute path component (e.g., r'\foo') is encountered.
