### ISSUE TITLE
Change sys.settrace opcode tracing to occur after frame line number update

### ISSUE THREAD

**Issue by 5d088e7f-313b-42e6-aa21-f85bbf47e2f0** [python/cpython#75799]
BPO | [31618](https://bugs.python.org/issue31618)
--- | :---
Nosy | @ncoghlan, @nedbat, @njsmith, @serhiy-storchaka, @gwk
PRs | <li>python/cpython#3798</li><li>python/cpython#4045</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-19.07:44:47.153>
created_at = <Date 2017-09-28.12:40:03.218>
labels = ['type-bug', '3.7']
title = 'Change sys.settrace opcode tracing to occur after frame line number update'
updated_at = <Date 2017-10-19.07:44:47.151>
user = 'https://github.com/gwk'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-19.07:44:47.151>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-19.07:44:47.153>
closer = 'ncoghlan'
components = []
creation = <Date 2017-09-28.12:40:03.218>
creator = 'gwk'
dependencies = []
files = []
hgrepos = []
issue_num = 31618
keywords = ['patch']
message_count = 3.0
messages = ['303225', '303226', '304605']
nosy_count = 5.0
nosy_names = ['ncoghlan', 'nedbat', 'njs', 'serhiy.storchaka', 'gwk']
pr_nums = ['3798', '4045']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31618'
versions = ['Python 3.7']
```

</p></details>

**Comment by 5d088e7f-313b-42e6-aa21-f85bbf47e2f0** [comment]
This patch moves the new opcode tracing added in commit 5a85167 to happen after frame-\>f_lineno is updated. With this patch, when both f_trace_lines and f_trace_opcodes are enabled the trace function will see the same line number for both the 'line' and 'opcode' events.

A side effect of this patch is that the order of event emission has been switched; 'line' now happens before 'opcode'. Maintaining the current order would require more elaborate logic.

**Comment by 5d088e7f-313b-42e6-aa21-f85bbf47e2f0** [comment]
The feature was was implemented in bpo-31344. See bpo-29400 for my parallel effort, which has been abandoned.

**Comment by ncoghlan** [comment]
Thanks for the fix!
