### ISSUE TITLE
Tests failures using -u largefile when the disk is full

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75792]
BPO | [31611](https://bugs.python.org/issue31611)
--- | :---
Nosy | @vstinner, @jkloth, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-29.21:59:05.857>
created_at = <Date 2017-09-27.12:29:24.371>
labels = ['invalid', '3.7', 'tests']
title = 'Tests failures using -u largefile when the disk is full'
updated_at = <Date 2018-05-29.21:59:05.856>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.21:59:05.856>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-29.21:59:05.857>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-09-27.12:29:24.371>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31611
keywords = []
message_count = 7.0
messages = ['303130', '303137', '303140', '303150', '303158', '303160', '318112']
nosy_count = 3.0
nosy_names = ['vstinner', 'jkloth', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31611'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
I ran the Python test suite on Windows on a freshly installed Python 3.7a1 and I got errors: bpo-31606.

I created a separated issue for tests failing because my disk has low free space.


On my Windows VM, I have a single 40 GB disk with 1.36 GB free.

C:\\Users\\haypo\\AppData\\Local\\Programs\\Python\\Python37\>python -m test -v -u all test_largefile

\======================================================================
ERROR: test_truncate (test.test_largefile.PyLargeFileTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\test\test_largefile.py", line 37, in setUp
    f.flush()
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\_pyio.py", line 1226, in flush
    self._flush_unlocked()
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\_pyio.py", line 1233, in _flush_unlocked
    n = self.raw.write(self._write_buf)
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\_pyio.py", line 1630, in write
    return os.write(self._fd, b)
OSError: [Errno 28] No space left on device
```


(other tests fail with similar message)



test_io:

\======================================================================
ERROR: test_large_file_ops (test.test_io.CIOTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\test\test_io.p
y", line 574, in test_large_file_ops
    self.large_file_ops(f)
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\test\test_io.p
y", line 355, in large_file_ops
    self.assertEqual(f.write(b"xxx"), 3)
OSError: [Errno 28] No space left on device
```


======================================================================
ERROR: test_large_file_ops (test.test_io.PyIOTest)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\test\test_io.py", line 574, in test_large_file_ops
    self.large_file_ops(f)
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\test\test_io.py", line 355, in large_file_ops
    self.assertEqual(f.write(b"xxx"), 3)
  File "C:\Users\haypo\AppData\Local\Programs\Python\Python37\lib\_pyio.py", line 1630, in write
    return os.write(self._fd, b)
OSError: [Errno 28] No space left on device
```

**Comment by serhiy-storchaka** [comment]
This is expected behavior, isn't?

**Comment by vstinner** [comment]
> This is expected behavior, isn't?

I would prefer that the test skips itself when the disk is full: on "OSError: [Errno 28] No space left on device".

Or maybe largefile resource should be excluded from "all"... at least on Windows, since NTFS doesn't see to support files full of zeros without accounting zero bytes (seek + write 1 byte: NTFS counts the seek in the disk space).

**Comment by serhiy-storchaka** [comment]
Definitely the test shouldn't be quietly skipped! If you enable the "largefile" resource, but the test can't write large file, this is either a bug in the tested code, or an error in the test, or misconfiguration.

We already have the "extralargefile" resource which is excluded from "all". "largefile" is for moderately large files, around 2 GiB.

**Comment by vstinner** [comment]
> "largefile" is for moderately large files, around 2 GiB.

largefile creates files larger than 2 GB. Extract of test_largefile:

```py
# size of file to create (>2GB; 2GB == 2147483648 bytes)
size = 2500000000
```


My VM has less than 2 GB free: only 1.36 GB free.

**Comment by serhiy-storchaka** [comment]
largefile - It is okay to run some test that may create huge
                files.  These tests can take a long time and may
                consume \>2GB of disk space temporarily.

I understand this as 2GB is a minimum free disk space for tests without "largefile". Tests with "largefile" need more free disk space.


Accordingly the bigmemtest decorator is used for tests that consume \>1GB of RAM.
