### ISSUE TITLE
Pluralization typo in Language Reference section 7.12

### ISSUE THREAD

**Issue by 1716bd18-148d-4f6b-88f4-48facb62d6f2** [python/cpython#75802]
BPO | [31621](https://bugs.python.org/issue31621)
--- | :---
Nosy | @kms70847, @Mariatta
PRs | <li>python/cpython#3809</li><li>python/cpython#3810</li>
Files | <li>[simple_stmts_pluralized.rst](https://bugs.python.org/file47175/simple_stmts_pluralized.rst "Uploaded as text/plain at 2017-09-28.18:26:13 by @kms70847"): a copy of `simple_stmts.rst` with the proposed one-letter change</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-28.20:00:50.915>
created_at = <Date 2017-09-28.18:26:13.874>
labels = ['3.7', 'docs']
title = 'Pluralization typo in Language Reference section 7.12'
updated_at = <Date 2017-09-28.20:00:50.914>
user = 'https://github.com/kms70847'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-28.20:00:50.914>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-09-28.20:00:50.915>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-09-28.18:26:13.874>
creator = 'kms70847'
dependencies = []
files = ['47175']
hgrepos = []
issue_num = 31621
keywords = ['patch']
message_count = 6.0
messages = ['303266', '303268', '303269', '303272', '303273', '303274']
nosy_count = 3.0
nosy_names = ['docs@python', 'kms70847', 'Mariatta']
pr_nums = ['3809', '3810']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31621'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1716bd18-148d-4f6b-88f4-48facb62d6f2** [comment]
The documentation for the `global` statement contains the line:

 \> CPython implementation detail: The current implementation does not enforce some of these restriction [...]

"restriction" should be "restrictions" since there is more than one of them.

Attached is a copy of `simple_stmts.rst` with the proposed one-letter change.

**Comment by Mariatta** [comment]
Thanks Kevin. Can you open a pull request with this change?

**Comment by 1716bd18-148d-4f6b-88f4-48facb62d6f2** [comment]
Yes, I intend to make a PR shortly.

**Comment by 1716bd18-148d-4f6b-88f4-48facb62d6f2** [comment]
Ok, I've created a pull request, available at https://github.com/python/cpython/pull/3809.

**Comment by Mariatta** [comment]
New changeset 641494ec3168bd556f0af226196e13ae29bddd53 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31621: Fix typo in Simple Statements documentation (GH-3809) (GH-3810)
https://github.com/python/cpython/commit/641494ec3168bd556f0af226196e13ae29bddd53

**Comment by Mariatta** [comment]
Thanks!
