### ISSUE TITLE
stop using ranlib

### ISSUE THREAD

**Issue by benjaminp** [python/cpython#75806]
BPO | [31625](https://bugs.python.org/issue31625)
--- | :---
Nosy | @vstinner, @benjaminp, @stratakis, @kadler
PRs | <li>python/cpython#3815</li><li>python/cpython#3824</li><li>python/cpython#10417</li><li>python/cpython#15387</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-11-29.14:46:30.011>
created_at = <Date 2017-09-29.06:15:32.648>
labels = ['3.8', 'build', '3.7']
title = 'stop using ranlib'
updated_at = <Date 2019-12-09.09:40:56.912>
user = 'https://github.com/benjaminp'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-09.09:40:56.912>
actor = 'Jakub Piotr C\xc5\x82apa'
assignee = 'none'
closed = True
closed_date = <Date 2018-11-29.14:46:30.011>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-09-29.06:15:32.648>
creator = 'benjamin.peterson'
dependencies = []
files = []
hgrepos = []
issue_num = 31625
keywords = ['patch']
message_count = 11.0
messages = ['303301', '303332', '303333', '303336', '303338', '329001', '329483', '329534', '330691', '330692', '330693']
nosy_count = 4.0
nosy_names = ['vstinner', 'benjamin.peterson', 'cstratak', 'kadler']
pr_nums = ['3815', '3824', '10417', '15387']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31625'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by benjaminp** [comment]
As far as I'm aware, every modern \*nix's ar supports an "s" flag that removes the need to run ranlib separately on a a static library. We should just do that and stop running ranlib. That saves us some lines in configure.ac and the Makefile.

**Comment by benjaminp** [comment]
New changeset d15108a4789aa1e3c12b2890b770550c90a30913 by Benjamin Peterson in branch 'master':
stop using ranlib (closes bpo-31625) (bpo-3815)
https://github.com/python/cpython/commit/d15108a4789aa1e3c12b2890b770550c90a30913

**Comment by vstinner** [comment]
Buildbots are unhappy :-( Compilation failed on:

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Debug%203.x/builds/962/steps/compile/logs/stdio

http://buildbot.python.org/all/builders/AMD64%20FreeBSD%20CURRENT%20Non-Debug%203.x/builds/964/steps/compile/logs/stdio

**Comment by benjaminp** [comment]
New changeset 6fb0e4a6d085ffa4e4a6daaea042a1cc517fa8bc by Benjamin Peterson in branch 'master':
explicitly list objects for the ar command (bpo-3824)
https://github.com/python/cpython/commit/6fb0e4a6d085ffa4e4a6daaea042a1cc517fa8bc

**Comment by vstinner** [comment]
Thanks ;-)
