### ISSUE TITLE
asyncio.Queue leaks memory if the queue is empty and consumers poll it frequently

### ISSUE THREAD

**Issue by 0555863e-1a62-4179-a1a0-ab6e9f1b3a0b** [python/cpython#75801]
BPO | [31620](https://bugs.python.org/issue31620)
--- | :---
Nosy | @asvetlov, @cjrh, @1st1, @SurenNihalani
PRs | <li>python/cpython#3813</li><li>python/cpython#4326</li>
Files | <li>[test.py](https://bugs.python.org/file47174/test.py "Uploaded as text/plain at 2017-09-28.17:27:48 by zackelan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-13.19:16:34.008>
created_at = <Date 2017-09-28.17:27:49.202>
labels = ['expert-asyncio', '3.7', 'performance']
title = 'asyncio.Queue leaks memory if the queue is empty and consumers poll it frequently'
updated_at = <Date 2017-12-13.19:16:34.007>
user = 'https://bugs.python.org/zackelan'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-13.19:16:34.007>
actor = 'asvetlov'
assignee = 'none'
closed = True
closed_date = <Date 2017-12-13.19:16:34.008>
closer = 'asvetlov'
components = ['asyncio']
creation = <Date 2017-09-28.17:27:49.202>
creator = 'zackelan'
dependencies = []
files = ['47174']
hgrepos = []
issue_num = 31620
keywords = ['patch']
message_count = 6.0
messages = ['303264', '303290', '303371', '305787', '305789', '308234']
nosy_count = 5.0
nosy_names = ['asvetlov', 'cjrh', 'yselivanov', 'snihalani', 'zackelan']
pr_nums = ['3813', '4326']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31620'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 0555863e-1a62-4179-a1a0-ab6e9f1b3a0b** [comment]
Repro: Call asyncio.wait_for(some_queue.get(), some_timeout) repeatedly, with no items in the queue, so that the call times out each time.

Expected: No increase in memory while polling an empty queue

Actual: The queue holds on to pending "getter" futures until a item passes through the queue, which clears the pending tasks out.

Use case:

I have producer and consumer asyncio.Tasks, linked by an asyncio.Queue. The producer is idle most of the time and pushes messages very infrequently. The consumer task polls the queue with wait_for and a timeout so that it's able to record "yep, I'm still idle" when the wait_for times out.

Attached script has a minimal repro. The producer emits an item every 60 seconds and the consumer polls every second. At the 59th second the \_getters member of the queue is holding on to 59 pending futures. By varying the intervals this can leak an arbitrary amount of memory, for example producer emitting an item once a day vs. consumer polling once a second will leak 86,400 futures.

From the attached script:

2017-09-28 10:09:12,699 Queue \<Queue maxsize=100 \_getters[1]\> is idle
...
2017-09-28 10:10:09,784 Queue \<Queue maxsize=100 \_getters[58]\> is idle
2017-09-28 10:10:10,785 Queue \<Queue maxsize=100 \_getters[59]\> is idle
2017-09-28 10:10:11,699 Received 0 from \<Queue maxsize=100 tasks=1\>
2017-09-28 10:10:12,700 Queue \<Queue maxsize=100 \_getters[1]\> is idle
2017-09-28 10:10:13,702 Queue \<Queue maxsize=100 \_getters[2]\> is idle

Noticed this in 3.6.1, though based on no changes to https://github.com/python/cpython/blob/master/Lib/asyncio/queues.py between the 3.6 branch and master I suspect it also affects 3.6.x and 3.7.

**Comment by d8545981-328e-4424-931f-6c70260c1ccf** [comment]
I am working on fixing this.

**Comment by 60717714-ac02-4c78-a5e0-6f0d36b9c456** [comment]
This looks like a dupe, or at least quite closely related to https://bugs.python.org/issue26259. If the PR resolves both issues that one should be closed too.

**Comment by asvetlov** [comment]
New changeset c62f0cb3b1f6f9ca4ce463b1c99b0543bdfa38d6 by Andrew Svetlov (Suren Nihalani) in branch 'master':
bpo-31620: have asyncio/queues not leak memory when you've exceptions during waiting (bpo-3813)
https://github.com/python/cpython/commit/c62f0cb3b1f6f9ca4ce463b1c99b0543bdfa38d6

**Comment by asvetlov** [comment]
New changeset ac4f6d4448fb6f9affb817bafb8357450fe43349 by Andrew Svetlov (Miss Islington (bot)) in branch '3.6':
bpo-31620: have asyncio/queues not leak memory when you've exceptions during waiting (GH-3813) (bpo-4326)
https://github.com/python/cpython/commit/ac4f6d4448fb6f9affb817bafb8357450fe43349
