### ISSUE TITLE
test_mailbox fails if the hostname is empty

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75808]
BPO | [31627](https://bugs.python.org/issue31627)
--- | :---
Nosy | @warsaw, @bitdancer, @skrah, @serhiy-storchaka, @koobs
PRs | <li>python/cpython#3821</li><li>python/cpython#3837</li><li>python/cpython#3838</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-30.19:54:03.956>
created_at = <Date 2017-09-29.07:17:31.265>
labels = ['3.7', 'type-bug', 'tests', 'expert-email']
title = 'test_mailbox fails if the hostname is empty'
updated_at = <Date 2017-09-30.19:54:03.956>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-30.19:54:03.956>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-30.19:54:03.956>
closer = 'serhiy.storchaka'
components = ['Tests', 'email', 'FreeBSD']
creation = <Date 2017-09-29.07:17:31.265>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31627
keywords = ['patch']
message_count = 5.0
messages = ['303304', '303329', '303411', '303421', '303422']
nosy_count = 5.0
nosy_names = ['barry', 'r.david.murray', 'skrah', 'serhiy.storchaka', 'koobs']
pr_nums = ['3821', '3837', '3838']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31627'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
On just installed FreeBSD the hostname is empty. This causes a failure of test_mailbox.

\======================================================================
FAIL: test_create_tmp (test.test_mailbox.TestMaildir)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/usr/home/serhiy/py/cpython3.7-debug/Lib/test/test_mailbox.py", line 758, in test_create_tmp
    self.assertIsNotNone(match, "Invalid file name: '%s'" % tail)
AssertionError: unexpectedly None : Invalid file name: '1506668827.M125806P21276Q34.'
```


----------------------------------------------------------------------

Changing the "+" qualifier to the "\*" qualifier in the regex pattern fixes the issue.

```py
         pattern = re.compile(r"(?P<time>\d+)\.M(?P<M>\d{1,6})P(?P<P>\d+)"
-                             r"Q(?P<Q>\d+)\.(?P<host>[^:/]+)")
+                             r"Q(?P<Q>\d+)\.(?P<host>[^:/]*)")
```

**Comment by bitdancer** [comment]
A system with no hostname can be considered to be improperly configured, but it doesn't look like this would weaken the test, so I think it is OK.

**Comment by serhiy-storchaka** [comment]
New changeset f4ea642cb60556231e714089a79d3c59c202661e by Serhiy Storchaka in branch 'master':
bpo-31627: Make test_mailbox be lenient to empty hostname. (bpo-3821)
https://github.com/python/cpython/commit/f4ea642cb60556231e714089a79d3c59c202661e

**Comment by serhiy-storchaka** [comment]
New changeset d9c21a45fdc83904753d91ad45e3eafa195f4713 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31627: Make test_mailbox be lenient to empty hostname. (GH-3821) (bpo-3837)
https://github.com/python/cpython/commit/d9c21a45fdc83904753d91ad45e3eafa195f4713

**Comment by serhiy-storchaka** [comment]
New changeset 1163fb9be08c6072455b59d6f954e60662d18e75 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31627: Make test_mailbox be lenient to empty hostname. (GH-3821) (bpo-3838)
https://github.com/python/cpython/commit/1163fb9be08c6072455b59d6f954e60662d18e75
