### ISSUE TITLE
integer overflow in the size of a ctypes.Array

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75818]
BPO | [31637](https://bugs.python.org/issue31637)
--- | :---
Nosy | @serhiy-storchaka, @orenmn
Superseder | <li>bpo-1621: Do not assume signed integer overflow behavior</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-29.11:50:34.083>
created_at = <Date 2017-09-29.10:39:58.190>
labels = ['ctypes', 'type-bug', '3.7']
title = 'integer overflow in the size of a ctypes.Array'
updated_at = <Date 2017-09-29.13:33:05.228>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-29.13:33:05.228>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-29.11:50:34.083>
closer = 'Oren Milman'
components = ['ctypes']
creation = <Date 2017-09-29.10:39:58.190>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31637
keywords = []
message_count = 3.0
messages = ['303322', '303324', '303326']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Oren Milman']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1621'
type = 'behavior'
url = 'https://bugs.python.org/issue31637'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code:
from ctypes import *
from \_testcapi import PY_SSIZE_T_MAX, LONG_MAX

```py
if LONG_MAX == PY_SSIZE_T_MAX == (1 << 31) - 1:
    class MyArray(Array):
        _type_ = c_longlong
        _length_ = 1 << 29

    arr = MyArray()
    for i in range(3):
        arr[i] = i
    for i in range(3):
        print(arr[i])
```


Produces this output (on a 32bit Python on my Windows 10):
2
2
2

This is because PyCArrayType_new() (in [Modules/_ctypes/_ctypes.c](https://github.com/python/cpython/blob/main/Modules/_ctypes/_ctypes.c)) raises a
"array too large" error in case (length * itemsize \< 0). However, this
multiplication might also overflow to a non-negative number, e.g. to zero in
the code above.
PyCArrayType_new() then does:
    stgdict-\>size = itemsize * length;

Array_ass_item() and Array_item() both do:
    size = stgdict-\>size / stgdict-\>length;
    offset = index * size;

So in the above code, the integer overflow caused the array to collapse to a
single element (the first element).


```c
ISTM that we can fix this by changing the overflow detection logic to this:
    assert(itemsize >= 0 && length >= 0);
    array_size = itemsize * length;
    if (itemsize && array_size / itemsize != length) {
        PyErr_SetString(PyExc_OverflowError,
                        "array too large");
        goto error;
    }
```


The assertion is guaranteed to be true after bpo-29843 is resolved. (I would open
a PR for bpo-29843 soon.)

**Comment by serhiy-storchaka** [comment]
Isn't this a duplicate of bpo-1621?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
oh, i missed that. sorry.
