### ISSUE TITLE
Asyncio: SSL transport does not support set_protocol()

### ISSUE THREAD

**Issue by a3e07c71-8cf4-4014-bc51-98d47623ef08** [python/cpython#75813]
BPO | [31632](https://bugs.python.org/issue31632)
--- | :---
Nosy | @1st1, @jlacoline
PRs | <li>python/cpython#3817</li><li>python/cpython#4052</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-19.17:50:44.809>
created_at = <Date 2017-09-29.08:59:33.967>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'Asyncio: SSL transport does not support set_protocol()'
updated_at = <Date 2017-10-19.18:12:46.546>
user = 'https://github.com/jlacoline'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-19.18:12:46.546>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-19.17:50:44.809>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-09-29.08:59:33.967>
creator = 'jlacoline'
dependencies = []
files = []
hgrepos = []
issue_num = 31632
keywords = ['patch']
message_count = 4.0
messages = ['303313', '304626', '304627', '304631']
nosy_count = 2.0
nosy_names = ['yselivanov', 'jlacoline']
pr_nums = ['3817', '4052']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31632'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by a3e07c71-8cf4-4014-bc51-98d47623ef08** [comment]
The bug was encountered when using the HTTPS client of the aiohttp package. 

Calling the method set_protocol() on a SSL transport (_SSLProtocolTransport) does not have the expected result: the new protocol will never be used (i.e. its data_received() method won't be called). The previous one keeps receiving data.

The problem comes from asyncio/ssl_proto.py:308. In my understanding, \_SSLProtocolTransport is modifying its local reference to the protocol but does not modify the reference in SSLProtocol, which is the one that is actually called.
So imo this line should look like "self.ssl_protocol.\_app_protocol = protocol"

I'll submit a github PR soon to fix this issue.

**Comment by 1st1** [comment]
New changeset ea2ef5d0ca869d4550820ed53bdf56013dbb9546 by Yury Selivanov (jlacoline) in branch 'master':
bpo-31632: fix set_protocol() in \_SSLProtocolTransport (bpo-3817) (bpo-3817)
https://github.com/python/cpython/commit/ea2ef5d0ca869d4550820ed53bdf56013dbb9546

**Comment by 1st1** [comment]
Loïc, thank you for the contribution!

**Comment by 1st1** [comment]
New changeset 9c23b173b823b5e6da01d85c570c7ae2ab07b38b by Yury Selivanov (Miss Islington (bot)) in branch '3.6':
bpo-31632: fix set_protocol() in \_SSLProtocolTransport (GH-3817) (GH-3817) (bpo-4052)
https://github.com/python/cpython/commit/9c23b173b823b5e6da01d85c570c7ae2ab07b38b
