### ISSUE TITLE
zipapp module should support compression

### ISSUE THREAD

**Issue by 460ababa-b553-4a7d-9326-8fa4392d56d3** [python/cpython#75819]
BPO | [31638](https://bugs.python.org/issue31638)
--- | :---
Nosy | @pfmoore, @merwok, @zmwangx
PRs | <li>python/cpython#3819</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/pfmoore'
closed_at = <Date 2017-09-29.17:37:11.919>
created_at = <Date 2017-09-29.11:12:16.606>
labels = ['3.7', 'type-feature', 'library']
title = 'zipapp module should support compression'
updated_at = <Date 2017-09-29.17:37:11.919>
user = 'https://github.com/zmwangx'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-29.17:37:11.919>
actor = 'paul.moore'
assignee = 'paul.moore'
closed = True
closed_date = <Date 2017-09-29.17:37:11.919>
closer = 'paul.moore'
components = ['Library (Lib)']
creation = <Date 2017-09-29.11:12:16.606>
creator = 'zmwangx'
dependencies = []
files = []
hgrepos = []
issue_num = 31638
keywords = ['patch', 'needs review']
message_count = 3.0
messages = ['303323', '303343', '303345']
nosy_count = 3.0
nosy_names = ['paul.moore', 'eric.araujo', 'zmwangx']
pr_nums = ['3819']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31638'
versions = ['Python 3.7']
```

</p></details>

**Comment by 460ababa-b553-4a7d-9326-8fa4392d56d3** [comment]
Currently (up to 3.7.0a1) archives generated by the zipapp module are uncompressed, which are unnecessarily large for large projects. It's easy to add deflate compression support, and Python loads compressed archives just fine.

I already have a patch available. I'll submit a PR soon.

**Comment by pfmoore** [comment]
Definitely. The reason it uses uncompressed files is simply an oversight on my part - I hadn't realised the default for zipfile was uncompressed.

**Comment by pfmoore** [comment]
New changeset d87b105ca794addf92addb28293c92a7ef4141e1 by Paul Moore (Zhiming Wang) in branch 'master':
bpo-31638: Add compression support to zipapp (GH-3819)
https://github.com/python/cpython/commit/d87b105ca794addf92addb28293c92a7ef4141e1
