### ISSUE TITLE
bug in datetime.datetime.timestamp

### ISSUE THREAD

**Issue by 87822c28-4b94-4f65-8522-b3f583247aed** [python/cpython#75825]
BPO | [31644](https://bugs.python.org/issue31644)
--- | :---
Nosy | @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-30.00:40:40.520>
created_at = <Date 2017-09-29.22:21:28.480>
labels = ['invalid', 'type-bug', 'library']
title = 'bug in datetime.datetime.timestamp'
updated_at = <Date 2017-09-30.01:32:44.083>
user = 'https://bugs.python.org/kliano'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-30.01:32:44.083>
actor = 'kliano'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-30.00:40:40.520>
closer = 'eric.smith'
components = ['Library (Lib)']
creation = <Date 2017-09-29.22:21:28.480>
creator = 'kliano'
dependencies = []
files = []
hgrepos = []
issue_num = 31644
keywords = []
message_count = 3.0
messages = ['303362', '303380', '303385']
nosy_count = 2.0
nosy_names = ['eric.smith', 'kliano']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31644'
versions = ['Python 3.6']
```

</p></details>

**Comment by 87822c28-4b94-4f65-8522-b3f583247aed** [comment]
datetime.datetime(2014,3,9,2).timestamp() returns 1394352000.0
datetime.datetime(2014,3,9,3).timestamp() returns 1394352000.0

**Comment by ericvsmith** [comment]
This is a daylight savings time folding problem. Without a timezone, those are in fact the same point in time, at least in my timezone (US Eastern).

If you specify a timezone, you'll see the difference:

datetime.datetime(2014,3,9,2,tzinfo=datetime.timezone(datetime.timedelta(0))).timestamp() -\> 1394330400.0

datetime.datetime(2014,3,9,3,tzinfo=datetime.timezone(datetime.timedelta(0))).timestamp() -\> 1394334000.0

These are 3600 seconds, or one hour, apart.

**Comment by 87822c28-4b94-4f65-8522-b3f583247aed** [comment]
The datetime object returned by strptime() does not have tzinfo.  Whatever default timezone that was chosen should produce consistent timestamp.  Reading a sequential datetime string and converting it to a sequence of timestamp results in expected time folding.

datetime.datetime.strptime(dtstr,fmt).timestamp()
