### ISSUE TITLE
Document exit() from parse_args

### ISSUE THREAD

**Issue by bbbf6d87-5650-459a-b509-ac8248be47b0** [python/cpython#75821]
BPO | [31640](https://bugs.python.org/issue31640)
--- | :---
Nosy | @merriam, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-29.16:54:02.874>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Document exit() from parse_args'
updated_at = <Date 2017-10-12.19:19:21.604>
user = 'https://github.com/merriam'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-12.19:19:21.604>
actor = 'paul.j3'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-09-29.16:54:02.874>
creator = 'CharlesMerriam'
dependencies = []
files = []
hgrepos = []
issue_num = 31640
keywords = []
message_count = 3.0
messages = ['303341', '303344', '304283']
nosy_count = 4.0
nosy_names = ['CharlesMerriam', 'r.david.murray', 'docs@python', 'paul.j3']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31640'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by bbbf6d87-5650-459a-b509-ac8248be47b0** [comment]
It is unexpected to testers and users to ArgParse that it terminates the process; one usually expects an error code.  Fix by modifying documentation to section 16.4.4 The parse_args() Method. 

Change the words "Return the populated namespace." to "Return the populated namespace, or exit with a status 0 if the help message is printed, or exit with status 2 if an invalid argument was parsed."

**Comment by bitdancer** [comment]
I think this is reasonable, but do note that this is covered in 16.4.4.2, and the fact that help exits is actually a property of help, not parse_args.  That is, the docs are correct and complete as they stand, but I agree that it would be helpful to have the summary include this information as well.

**Comment by 7a064fe6-c535-4d80-a11f-a04ed39056c5** [comment]
And the actual exit is via `parse.error` and `parse.exit`, which are documented in 16.4.5.9.

When run interactively in Ipython, exits (including the help) are captured and displayed with:

In [896]: parser.parse_args()
usage: ipython3 [-h] [--one | --two | --six]
ipython3: error: unrecognized arguments: --pylab --nosep --term-title --InteractiveShellApp.pylab_import_all=False
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

The exit makes unittesting a challenge.  'test_argparse.py' resolves this by using a subclassed parser, one that changes the error/exit, and also redirects output.

**Comment by serhiy-storchaka** [comment]
Closing, as this behavior is documented.
