### ISSUE TITLE
test_uuid: test_getnode and test_windll_getnode fail if connected to the Internet via an Android phone

### ISSUE THREAD

**Issue by eb193824-a002-4e53-a73b-be75738ef3f2** [python/cpython#75824]
BPO | [31643](https://bugs.python.org/issue31643)
--- | :---
Nosy | @warsaw, @xdegaye, @serhiy-storchaka, @native-api
PRs | <li>python/cpython#4448</li><li>python/cpython#4804</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-09-29.21:37:18.944>
labels = ['type-bug', 'tests', '3.9', '3.10', '3.11']
title = 'test_uuid: test_getnode and test_windll_getnode fail if connected to the Internet via an Android phone'
updated_at = <Date 2021-06-14.21:55:20.385>
user = 'https://github.com/native-api'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-14.21:55:20.385>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-09-29.21:37:18.944>
creator = 'Ivan.Pozdeev'
dependencies = []
files = []
hgrepos = []
issue_num = 31643
keywords = []
message_count = 7.0
messages = ['303360', '303373', '308097', '308100', '308104', '308152', '308194']
nosy_count = 5.0
nosy_names = ['barry', '__Vano', 'xdegaye', 'serhiy.storchaka', 'Ivan.Pozdeev']
pr_nums = ['4448', '4804']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31643'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
Ethernet emulation for some devices like Android phones' tethering use all-zero MAC addresses (which is okay since they don't actually pass Ethernet frames to other NICs). This results in a node ID of 0 if I'm currently connected to the Net via such a device. Which fails range checks in the corresponding tests.

RFC 4122 doesn't actually have any prohibitions of using a node ID of 0. Neither does IEEE 802.3 (or rather, whatever info I gathered on it since the standard's text is not freely available) assign any special meaning to an all-zero MAC address.

The patch also corrects the check call in test_windll_getnode since the tested function always generates UUID from a MAC address.

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
Example failure:

\======================================================================
FAIL: test_windll_getnode (test.test_uuid.TestInternals)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Ivan\cpython\lib\test\test_uuid.py", line 501, in test_windll_getnode
```


```py
    self.check_node(node)
  File "C:\Ivan\cpython\lib\test\test_uuid.py", line 449, in check_node
    "%s is not an RFC 4122 node ID" % hex)
AssertionError: False is not true : 000000000000 is not an RFC 4122 node ID
```


======================================================================
FAIL: test_getnode (test.test_uuid.TestUUID)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\Ivan\cpython\lib\test\test_uuid.py", line 296, in test_getnode
    self.assertTrue(0 < node1 < (1 << 48), '%012x' % node1)
AssertionError: False is not true : 000000000000
```

**Comment by mhsmith** [comment]
According to my tests, on Android API level 21, `getnode` uses the `ip` command to return the actual MAC address of the device. On API level 34, the `ip` command [no longer returns anything for an unprivileged user](https://developer.android.com/training/articles/user-data-ids#mac-11-plus), so `getnode` falls back on a random address, as documented. Either way, the resulting address is non-zero.

@encukou: So I think this issue can be closed.
