### ISSUE TITLE
Improve ElementPath

### ISSUE THREAD

**Issue by scoder** [python/cpython#75829]
BPO | [31648](https://bugs.python.org/issue31648)
--- | :---
Nosy | @scoder, @serhiy-storchaka
PRs | <li>python/cpython#3835</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-09-30.13:36:57.025>
created_at = <Date 2017-09-30.08:16:42.055>
labels = ['expert-XML', 'type-feature', 'library', '3.7']
title = 'Improve ElementPath'
updated_at = <Date 2017-09-30.13:36:57.024>
user = 'https://github.com/scoder'
```

bugs.python.org fields:
```python
activity = <Date 2017-09-30.13:36:57.024>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-09-30.13:36:57.025>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'XML']
creation = <Date 2017-09-30.08:16:42.055>
creator = 'scoder'
dependencies = []
files = []
hgrepos = []
issue_num = 31648
keywords = ['patch']
message_count = 7.0
messages = ['303400', '303402', '303403', '303404', '303405', '303408', '303409']
nosy_count = 3.0
nosy_names = ['scoder', 'eli.bendersky', 'serhiy.storchaka']
pr_nums = ['3835']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31648'
versions = ['Python 3.7']
```

</p></details>

**Comment by scoder** [comment]
* Allow whitespace around predicate parts, i.e. "[a = 'text']" instead of requiring the less readable "[a='text']".

* Add support for text comparison of the current node, like "[.='text']".

Both currently raise "invalid path" exceptions. PR coming.

**Comment by serhiy-storchaka** [comment]
Is this feature already implemented in lxml? Is it a part of some wider standard?

**Comment by scoder** [comment]
Well, there's XPath for a standard:
https://www.w3.org/TR/xpath/

ElementPath deviates from it in its namespace syntax (it allows "{ns}tag" where XPath requires "p:tag" prefixes), but that's about it. All other differences are basically needless limitations of ElementPath.

In fact, I had noticed these two limitations in lxml, so I implemented them for the next release. And since ElementPath in ElementTree is still mostly the same as ElementPath in lxml, here's the same thing for ET.

**Comment by serhiy-storchaka** [comment]
I think the break in the loop for [.='text'] is not correct.

```pycon
>>> from xml.etree import ElementTree as ET
>>> e = ET.XML('<root><a><b>text</b></a><a><b></b></a><a><b>text</b></a></root>')
>>> list(e.findall('.//a[b="text"]'))
[<Element 'a' at 0x7ffadb305d58>, <Element 'a' at 0x7ffadb305f58>]
>>> list(e.findall('.//a[.="text"]'))
[<Element 'a' at 0x7ffadb305d58>]
```


I expect that findall() finds all matched elements, not just the first one. Both above requests should return the same result.

**Comment by scoder** [comment]
Thanks for noticing. I added a test and fixed it.

**Comment by serhiy-storchaka** [comment]
New changeset 101a5e84acbab9d880e150195f23185dfb5449a9 by Serhiy Storchaka (scoder) in branch 'master':
bpo-31648: Improve ElementPath (bpo-3835)
https://github.com/python/cpython/commit/101a5e84acbab9d880e150195f23185dfb5449a9

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Stefan! Good improvement.
