### ISSUE TITLE
None value in sys.modules no longer blocks import

### ISSUE THREAD

**Issue by tiran** [python/cpython#75823]
BPO | [31642](https://bugs.python.org/issue31642)
--- | :---
Nosy | @warsaw, @brettcannon, @ncoghlan, @tiran, @ericsnowcurrently, @serhiy-storchaka
PRs | <li>python/cpython#3834</li><li>python/cpython#3923</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-08.09:55:13.546>
created_at = <Date 2017-09-29.20:21:12.164>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'None value in sys.modules no longer blocks import'
updated_at = <Date 2017-10-08.09:55:13.493>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-08.09:55:13.493>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-08.09:55:13.546>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-09-29.20:21:12.164>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 31642
keywords = ['patch', '3.6regression']
message_count = 5.0
messages = ['303356', '303374', '303396', '303900', '303904']
nosy_count = 6.0
nosy_names = ['barry', 'brett.cannon', 'ncoghlan', 'christian.heimes', 'eric.snow', 'serhiy.storchaka']
pr_nums = ['3834', '3923']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31642'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by tiran** [comment]
Since Python 3.6, the blocking of imports is broken for 'from package import module' imports.

```sh
$ mkdir a
$ touch a/__init__.py a/b.py
```


```pycon
>>> import sys
>>> sys.modules['a.b'] = None
>>> from a import b
>>> b is None
True
>>> import a.b
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: import of 'a.b' halted; None in sys.modules
```


Tests with Python 2.7 to master:

```pytb
$ python2.7 -c "from a import b; print(b)"
<module 'a.b' from 'a/b.py'>
$ python2.7 -c "import sys; sys.modules['a.b'] = None; from a import b"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name b
$ python2.7 -c "import sys; sys.modules['a.b'] = None; from a import b"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name b
$ python3.4 -c "import sys; sys.modules['a.b'] = None; from a import b"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: import of 'a.b' halted; None in sys.modules
$ python3.5 -c "import sys; sys.modules['a.b'] = None; from a import b"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: import of 'a.b' halted; None in sys.modules
$ python3.6 -c "import sys; sys.modules['a.b'] = None; from a import b"
$ ./python -c "import sys; sys.modules['a.b'] = None; from a import b"
```

**Comment by serhiy-storchaka** [comment]
This is a side effect of bpo-15767. The exception is raised in \_find_and_load, but it is always silenced in \_handle_fromlist.

**Comment by serhiy-storchaka** [comment]
[PR 3834](https://github.com/python/cpython/pull/3834) provide possible solution of this issue.

Initially import errors were silenced for solving bpo-15715. An import error raised when import was blocked by setting None in sys.modules was not silenced because it has different error message. I don't know whether this was intentional. In bpo-15767 (5fdb8c897023) the error message test was replaced by the type test, and that exception become silenced (I suppose it was not intentional).

**Comment by serhiy-storchaka** [comment]
New changeset f07e2b64df6304a36fb5e29397d3c77a7ba17704 by Serhiy Storchaka in branch 'master':
bpo-31642: Restore blocking "from" import by setting None in sys.modules. (bpo-3834)
https://github.com/python/cpython/commit/f07e2b64df6304a36fb5e29397d3c77a7ba17704

**Comment by serhiy-storchaka** [comment]
New changeset 6f059ab80a351a7dd85cc57c5ca240f817a79c5d by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31642: Restore blocking "from" import by setting None in sys.modules. (GH-3834). (bpo-3923)
https://github.com/python/cpython/commit/6f059ab80a351a7dd85cc57c5ca240f817a79c5d
