### ISSUE TITLE
concurrent.futures.as_completed() no longer accepts arbitrary iterables

### ISSUE THREAD

**Issue by ambv** [python/cpython#75822]
BPO | [31641](https://bugs.python.org/issue31641)
--- | :---
Nosy | @pitrou, @vstinner, @ned-deily, @ambv, @grzgrzgrz3
PRs | <li>python/cpython#3830</li><li>python/cpython#3831</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ambv'
closed_at = <Date 2017-10-03.08:51:35.285>
created_at = <Date 2017-09-29.19:49:30.607>
labels = ['type-bug', '3.7']
title = 'concurrent.futures.as_completed() no longer accepts arbitrary iterables'
updated_at = <Date 2017-10-03.08:51:45.011>
user = 'https://github.com/ambv'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.08:51:45.011>
actor = 'ned.deily'
assignee = 'lukasz.langa'
closed = True
closed_date = <Date 2017-10-03.08:51:35.285>
closer = 'ned.deily'
components = []
creation = <Date 2017-09-29.19:49:30.607>
creator = 'lukasz.langa'
dependencies = []
files = []
hgrepos = []
issue_num = 31641
keywords = ['patch', '3.6regression']
message_count = 7.0
messages = ['303355', '303357', '303359', '303361', '303364', '303583', '303584']
nosy_count = 5.0
nosy_names = ['pitrou', 'vstinner', 'ned.deily', 'lukasz.langa', 'grzgrzgrz3']
pr_nums = ['3830', '3831']
priority = None
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31641'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ambv** [comment]
bpo-27144 introduced a regression for `as_completed()`: it used to accept arbitrary iterables but now requires sequences, otherwise raising an exception like:


```pytb
Traceback (most recent call last):
  File "sandcastle/worker/sandcastle_worker.py", line 1266, in get_work_item
  File "jupiter/jupiter_client.py", line 166, in acquireWork
  File "jupiter/jupiter_client.py", line 241, in _acquire_multiple_async
  File "jupiter/jupiter_client.py", line 336, in _wait_for_responses
  File "/usr/local/fbcode/gcc-5-glibc-2.23/lib/python3.6/concurrent/futures/_base.py", line 217, in as_completed
    total_futures = len(fs)
TypeError: object of type 'map' has no len()
```



Since `as_completed()` is a very popular function, we need to revert the behavior here.

**Comment by ned-deily** [comment]
Sounds like we need to get this fixed for 3.6.3 final which is scheduled for Monday (3 days).  Or revert the previous fix.

**Comment by ambv** [comment]
Fix is already landed in 3.6 and master.

**Comment by ned-deily** [comment]
New changeset 2e3fd03796528a9f88f79d38e1d890af153c8e61 by Ned Deily (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31641: Allow arbitrary iterables in `concurrent.futures.as_completed()` (GH-3830) (bpo-3831)
https://github.com/python/cpython/commit/2e3fd03796528a9f88f79d38e1d890af153c8e61

**Comment by ned-deily** [comment]
Cherry picked into 3.6.3 final -\> closing
