### ISSUE TITLE
unit test for optimization levels does not cover __debug__ case

### ISSUE THREAD

**Issue by dianaclarke** [python/cpython#75838]
BPO | [31657](https://bugs.python.org/issue31657)
--- | :---
Nosy | @dianaclarke, @Mariatta
PRs | <li>python/cpython#3450</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-04.18:25:01.668>
created_at = <Date 2017-10-01.15:08:33.133>
labels = ['type-feature', '3.7']
title = 'unit test for optimization levels does not cover __debug__ case'
updated_at = <Date 2017-10-04.18:25:01.666>
user = 'https://github.com/dianaclarke'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-04.18:25:01.666>
actor = 'Mariatta'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-04.18:25:01.668>
closer = 'Mariatta'
components = []
creation = <Date 2017-10-01.15:08:33.133>
creator = 'diana'
dependencies = []
files = []
hgrepos = []
issue_num = 31657
keywords = ['patch']
message_count = 3.0
messages = ['303465', '303630', '303724']
nosy_count = 2.0
nosy_names = ['diana', 'Mariatta']
pr_nums = ['3450']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31657'
versions = ['Python 3.7']
```

</p></details>

**Comment by dianaclarke** [comment]
There are currently three supported optimization levels (0, 1, and 2). Briefly summarized, they do the following.

    0: no optimizations
    1: remove assert statements and __debug__ blocks
    2: remove docstrings, assert statements, and __debug__ blocks

The current compile() tests for optimization levels in [Lib/test/test_builtin.py](https://github.com/python/cpython/blob/main/Lib/test/test_builtin.py) covers the assert and docstring cases, but it doesn't test that \_\_debug__ code blocks are included or excluded based on the optimization level.

For example, if you change [Python/compile.c](https://github.com/python/cpython/blob/main/Python/compile.c) to always include \_\_debug__ blocks regardless of the optimization level, the existing compile() tests will continue to pass.

```diff
$ git diff Python/compile.c
diff --git a/Python/compile.c b/Python/compile.c
index 280ddc39e3..d65df098bb 100644
--- a/Python/compile.c
+++ b/Python/compile.c
@@ -4143,7 +4143,7 @@ expr_constant(struct compiler *c, expr_ty e)
         /* optimize away names that can't be reassigned */
         id = PyUnicode_AsUTF8(e->v.Name.id);
         if (id && strcmp(id, "__debug__") == 0)
-            return !c->c_optimize;
+            return 1;
         return -1;
     case NameConstant_kind: {
         PyObject *o = e->v.NameConstant.value;
```

**Comment by Mariatta** [comment]
New changeset 543386b7f077d210ea0722079d68beb6c066730a by Mariatta (diana) in branch 'master':
bpo-31657: Add test coverage for the \_\_debug__ case (GH-3450)
https://github.com/python/cpython/commit/543386b7f077d210ea0722079d68beb6c066730a

**Comment by Mariatta** [comment]
Thanks for this enhancement, Diana.

Since PR has been merged, and backport is not needed, I think this can be closed now. :)
