### ISSUE TITLE
Bitwise operations for bytes-type

### ISSUE THREAD

**Issue by d51cb458-b85e-4ade-aa04-a03cf5b7b1c5** [python/cpython#75837]
BPO | [31656](https://bugs.python.org/issue31656)
--- | :---
Nosy | @ncoghlan, @bitdancer, @vadmium, @DaGuich
Superseder | <li>bpo-19251: bitwise ops for bytes of equal length</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-01.15:30:51.999>
created_at = <Date 2017-10-01.15:01:16.775>
labels = ['interpreter-core', 'type-feature']
title = 'Bitwise operations for bytes-type'
updated_at = <Date 2018-05-17.14:04:38.047>
user = 'https://github.com/DaGuich'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-17.14:04:38.047>
actor = 'ncoghlan'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-01.15:30:51.999>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-10-01.15:01:16.775>
creator = 'MGilch'
dependencies = []
files = []
hgrepos = []
issue_num = 31656
keywords = []
message_count = 4.0
messages = ['303464', '303466', '303492', '316932']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'r.david.murray', 'martin.panter', 'MGilch']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '19251'
type = 'enhancement'
url = 'https://bugs.python.org/issue31656'
versions = []
```

</p></details>

**Comment by d51cb458-b85e-4ade-aa04-a03cf5b7b1c5** [comment]
I've seen that the bytes type does not support bitwise operations, but I think users would expect that those operations will work.

**Comment by bitdancer** [comment]
What happens when you apply a bitwise operation to two bytes objects of unequal length?

Since the answer to that question is not obvious, we simply don't support the operation.

If you want to make a proposal for this the python-ideas mailing list would be the appropriate forum.

**Comment by vadmium** [comment]
There’s already a bug open for this: bpo-19251. Only equal-length strings should be supported.
