### ISSUE TITLE
Don't release the GIL if we can acquire a multiprocessing semaphore immediately

### ISSUE THREAD

**Issue by 09844748-0623-4c37-9350-082719a270a2** [python/cpython#75834]
BPO | [31653](https://bugs.python.org/issue31653)
--- | :---
Nosy | @pitrou, @vstinner, @serhiy-storchaka, @applio
PRs | <li>python/cpython#4078</li><li>python/cpython#4091</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-22.11:11:08.000>
created_at = <Date 2017-10-01.01:43:01.894>
labels = ['extension-modules', 'easy', '3.7', 'performance']
title = "Don't release the GIL if we can acquire a multiprocessing semaphore immediately"
updated_at = <Date 2017-10-23.20:57:57.879>
user = 'https://bugs.python.org/DanielColascione'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-23.20:57:57.879>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-22.11:11:08.000>
closer = 'pitrou'
components = ['Extension Modules']
creation = <Date 2017-10-01.01:43:01.894>
creator = 'Daniel Colascione'
dependencies = []
files = []
hgrepos = []
issue_num = 31653
keywords = ['patch', 'easy (C)']
message_count = 4.0
messages = ['303441', '303449', '304742', '304840']
nosy_count = 5.0
nosy_names = ['pitrou', 'vstinner', 'serhiy.storchaka', 'davin', 'Daniel Colascione']
pr_nums = ['4078', '4091']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31653'
versions = ['Python 3.7']
```

</p></details>

**Comment by 09844748-0623-4c37-9350-082719a270a2** [comment]
Right now, the main loop in semlock_acquire looks like this:

    do {
        Py_BEGIN_ALLOW_THREADS
        if (blocking && timeout_obj == Py_None)
            res = sem_wait(self->handle);
        else if (!blocking)
            res = sem_trywait(self->handle);
        else
            res = sem_timedwait(self->handle, &deadline);
        Py_END_ALLOW_THREADS
        err = errno;
        if (res == MP_EXCEPTION_HAS_BEEN_SET)
            break;
    } while (res < 0 && errno == EINTR && !PyErr_CheckSignals());

Here, we unconditionally release the GIL even we could acquire the mutex without blocking! As a result, we could end up switching to another thread in the process and greatly increasing the latency of operations that lock and release multiple shared data structures.

Instead, we should unconditionally try sem_trywait, and only then, if we want to block, release the GIL and try sem_wait or sem_timedwait. This way, we'll churn only when we need to.

Note that threading.Lock works the way I propose.

**Comment by serhiy-storchaka** [comment]
Looks reasonable to me. Do you want to provide a patch Daniel?

**Comment by pitrou** [comment]
New changeset c872d39d324cd6f1a71b73e10406bbaed192d35f by Antoine Pitrou in branch 'master':
bpo-31653: Don't release the GIL if we can acquire a multiprocessing semaphore immediately (bpo-4078)
https://github.com/python/cpython/commit/c872d39d324cd6f1a71b73e10406bbaed192d35f

**Comment by vstinner** [comment]
New changeset 828ca59208af0b1b52a328676c5cc0c5e2e999b0 by Victor Stinner in branch 'master':
bpo-31653: Remove deadcode in semlock_acquire() (bpo-4091)
https://github.com/python/cpython/commit/828ca59208af0b1b52a328676c5cc0c5e2e999b0
