### ISSUE TITLE
SimpleNamespace accepts non-string keyword names

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75836]
BPO | [31655](https://bugs.python.org/issue31655)
--- | :---
Nosy | @rhettinger, @terryjreedy, @vstinner, @bitdancer, @ericsnowcurrently, @serhiy-storchaka
PRs | <li>python/cpython#3909</li><li>python/cpython#3920</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-07.20:54:37.221>
created_at = <Date 2017-10-01.06:36:41.956>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'SimpleNamespace accepts non-string keyword names'
updated_at = <Date 2017-10-07.20:54:37.220>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-07.20:54:37.220>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-07.20:54:37.221>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-10-01.06:36:41.956>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31655
keywords = ['patch']
message_count = 8.0
messages = ['303450', '303461', '303463', '303467', '303521', '303843', '303891', '303892']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'vstinner', 'r.david.murray', 'eric.snow', 'serhiy.storchaka']
pr_nums = ['3909', '3920']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31655'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Usually non-string keyword names are rejected.

```pycon
>>> def f(**kwargs): pass                                                                                                                                                                                                                    
...                                                                                                                                                                                                                                          
>>> f(**{0:0})
Traceback (most recent call last):                                                                                                                                                                                                           
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                        
TypeError: f() keywords must be strings                                                                                                                                                                                                      
>>> dict(**{0:0})
Traceback (most recent call last):                                                                                                                                                                                                           
  File "<stdin>", line 1, in <module>                                                                                                                                                                                                        
TypeError: keywords must be strings                                                                                                                                                                                                          
```


There are checks in multiple places that satisfy this: in \_PyEval_EvalCodeWithName(), PyArg_ValidateKeywordArguments(), PyArg_ParseTupleAndKeywords(), etc.

But SimpleNamespace is an exception.

```pycon
>>> from types import SimpleNamespace
>>> SimpleNamespace(**{0:0})
namespace()
```


Non-string keys are omitted in the repr. Wouldn't be better to add also the check that keyword names for SimpleNamespace constructor are strings?

I don't know how classify this issue, as a bug or an enhancement.

Based on the StackOverflow question: https://stackoverflow.com/questions/46164770/accepting-integers-as-keys-of-kwargs.

**Comment by bitdancer** [comment]
Well, it would be an "unenhancement" (reducing functionality :).  

What I think it would be classed as is an API bug fix, and those generally can be made only in feature releases.  I can imagine code depending on this ability, since we have had code in the wild that depends on the ability to put non-string keys in an object's \_\_dict__ even before SimpleNamespace existed.

(By the way, dir is broken if an object's \_\_dict__ contains non-string keys.)

**Comment by bitdancer** [comment]
Sorry, not broken, it just raises a type error, which is appropriate :)

**Comment by rhettinger** [comment]
> Wouldn't be better to add also the check that keyword names
> for SimpleNamespace constructor are strings?

Yes.

> I don't know how classify this issue, as a bug or an enhancement.

It is arguably a bug fix.  +0 for putting this in Python 3.6.

**Comment by vstinner** [comment]
Please reject non-string keys. I don't see any good reason to use non-string, and it's painful to support such CPython implementation details in other Python implementations.

**Comment by terryjreedy** [comment]
After reading the doc entry for SimpleNamespace, I see running 'SimpleNamespace(**{0:0})' as a bug because doing so results in an object than contradicts the doc.

1. "A simple object subclass that provides attribute access to its namespace, as well as a meaningful repr. Unlike ... you can ... delete attributes."

But, after 'sn = SimpleNamespace(**{0:0})', sn.0 is a SyntaxError and getattr(sn, 0) raises 'TypeError: getattr(): attribute name must be string'.  As already noted, the 'attribute' does not appear in repr(sn).  'del sn.0' and 'delattr(sn, 0)' also fail.  If this is a feature, it is extremely buggy.

2. "The type is roughly equivalent to the following code:"

```py
class SimpleNamespace:
    def __init__(self, **kwargs):
        self.__dict__.update(kwargs)

    def __repr__(self):
        keys = sorted(self.__dict__)
        items = ("{}={!r}".format(k, self.__dict__[k]) for k in keys)
        return "{}({})".format(type(self).__name__, ", ".join(items))

    def __eq__(self, other):
        return self.__dict__ == other.__dict__
```


With this definition, SimpleNamespace(**{0:0}) raises TypeError.  To me, running versus raising is outside the bounds of 'roughly equivalent'.

**Comment by serhiy-storchaka** [comment]
New changeset 79ba471488b936abda5ba5234b1ea90cbc94cae6 by Serhiy Storchaka in branch 'master':
bpo-31655: Validate keyword names in SimpleNamespace constructor. (bpo-3909)
https://github.com/python/cpython/commit/79ba471488b936abda5ba5234b1ea90cbc94cae6

**Comment by serhiy-storchaka** [comment]
New changeset cae6e4775b37c412609d3a0d303c0831ff0012ff by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31655: Validate keyword names in SimpleNamespace constructor. (GH-3909) (bpo-3920)
https://github.com/python/cpython/commit/cae6e4775b37c412609d3a0d303c0831ff0012ff
