### ISSUE TITLE
pyautogui.typewrite() method doesn't work as expected.

### ISSUE THREAD

**Issue by 9a3932b3-89f0-4b26-92a1-e53d25187ff1** [python/cpython#75844]
BPO | [31663](https://bugs.python.org/issue31663)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-10-02.17:24:43.602>
created_at = <Date 2017-10-02.09:24:09.482>
labels = ['type-bug']
title = "pyautogui.typewrite() method doesn't work as expected."
updated_at = <Date 2017-10-02.17:24:43.600>
user = 'https://bugs.python.org/basanna007'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-02.17:24:43.600>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-10-02.17:24:43.602>
closer = 'terry.reedy'
components = []
creation = <Date 2017-10-02.09:24:09.482>
creator = 'basanna007'
dependencies = []
files = []
hgrepos = []
issue_num = 31663
keywords = []
message_count = 2.0
messages = ['303515', '303554']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'zach.ware', 'basanna007']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31663'
versions = ['Python 3.6']
```

</p></details>

**Comment by 9a3932b3-89f0-4b26-92a1-e53d25187ff1** [comment]
Tried to run pyautogui.typewrite('Hello World') On IDLE terminal to type 'Hello World' string to an open notepad(say). As, i've interchanged my mouse click options(on windows OS), instead of 'Hello World' string being print to to the open notepad, i could see a right click on it.

The method pyautogui.typewrite() doesn't function as per mouse options settings on my machine.

**Comment by terryjreedy** [comment]
This tracker is for issues about improving future cpython releases on python.org.  Questions about using current python go to other forums, such as python-list.  You can also use python-list via the news.gmane.org newsgroup mirror gmane.comp.python.general.

If you ask your question elsewhere, you must give much more information.  What is pyautogui.typewrite?  It is not part of the Python stdlib.  What does 'interchanged my mouse click options (on windows OS)' mean?  What did you do in IDLE, in some detail.  What did you see and where?
