### ISSUE TITLE
Pandas_datareader Error Message - ModuleNotFoundError: No module named 'pandas_datareader' with module in folder

### ISSUE THREAD

**Issue by e39eacf1-e64f-4365-8616-9d757f539e6a** [python/cpython#75847]
BPO | [31666](https://bugs.python.org/issue31666)
--- | :---
Nosy | @pfmoore, @tjguk, @merwok, @zware, @zooba, @matrixise

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-09.09:40:53.570>
created_at = <Date 2017-10-02.19:42:56.391>
labels = ['invalid', 'library', 'OS-windows']
title = "Pandas_datareader Error Message - ModuleNotFoundError: No module named 'pandas_datareader' with module in folder"
updated_at = <Date 2017-10-09.09:40:53.495>
user = 'https://bugs.python.org/ScottTucholka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-09.09:40:53.495>
actor = 'matrixise'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-09.09:40:53.570>
closer = 'matrixise'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-10-02.19:42:56.391>
creator = 'Scott Tucholka'
dependencies = []
files = []
hgrepos = []
issue_num = 31666
keywords = []
message_count = 3.0
messages = ['303837', '303935', '303938']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'eric.araujo', 'zach.ware', 'steve.dower', 'matrixise', 'Scott Tucholka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31666'
versions = ['Python 3.6']
```

</p></details>

**Comment by merwok** [comment]
Hello!  Your bug report gives very little information for us to help you.  Can you give details such as: your environement / setup, your code, expected result and full error message?

https://devguide.python.org/tracker/#reporting-an-issue

**Comment by e39eacf1-e64f-4365-8616-9d757f539e6a** [comment]
I am running Windows 10 Enterprise x64 and use Spyder (Python 3.6).

This is my code:
import pandas as pd
import pandas_datareader as dr
dr.get_data_yahoo('AAPL')

I am expecting that the module will import and the get_data_yahoo will
return results for 'AAPL'.

```pytb
This is my log:
Python 3.6.2 |Anaconda, Inc.| (default, Sep 19 2017, 08:03:39) [MSC v.1900
64 bit (AMD64)]
Type "copyright", "credits" or "license" for more information.
IPython 6.1.0 -- An enhanced Interactive Python.
import pandas as pd
import pandas_datareader as dr
dr.get_data_yahoo('AAPL')
Traceback (most recent call last):
  File "<ipython-input-1-43a2f11394e3>", line 2, in <module>
    import pandas_datareader as dr
ModuleNotFoundError: No module named 'pandas_datareader'
```


Thanks

**Comment by matrixise** [comment]
Hi,

Your bug is related to Pandas and not to Python 3.6.

Maybe you need to post your issue to the bug tracker of Pandas.

You need to install pandas-datareader

pip install pandas-datareader

But it is not an issue with Python.

Have a nice day,
