### ISSUE TITLE
Wrong links in the gettext.NullTranslations class

### ISSUE THREAD

**Issue by 517ec50a-c0bc-4503-b041-270261e61905** [python/cpython#75848]
BPO | [31667](https://bugs.python.org/issue31667)
--- | :---
Nosy | @serhiy-storchaka, @Linkid
PRs | <li>python/cpython#3860</li><li>python/cpython#3886</li><li>python/cpython#4100</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-24.08:01:17.224>
created_at = <Date 2017-10-02.20:04:55.633>
labels = ['type-feature', '3.7', 'docs']
title = 'Wrong links in the gettext.NullTranslations class'
updated_at = <Date 2017-10-24.08:01:17.224>
user = 'https://github.com/Linkid'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-24.08:01:17.224>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-24.08:01:17.224>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-10-02.20:04:55.633>
creator = 'linkid'
dependencies = []
files = []
hgrepos = []
issue_num = 31667
keywords = ['patch']
message_count = 5.0
messages = ['303563', '303565', '303718', '303722', '304869']
nosy_count = 3.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'linkid']
pr_nums = ['3860', '3886', '4100']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31667'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 517ec50a-c0bc-4503-b041-270261e61905** [comment]
In gettext.NullTranslations class doc [0], links to gettext and ngettext methods are not consistent.

[0] https://docs.python.org/3/library/gettext.html#the-nulltranslations-class

**Comment by serhiy-storchaka** [comment]
Good catch linkid! [PR 3860](https://github.com/python/cpython/pull/3860) fixes these and several other gettext related links.

**Comment by serhiy-storchaka** [comment]
New changeset c02a1f4ad8fcdbffad2911c5a31c71a17a89d713 by Serhiy Storchaka in branch 'master':
bpo-31667: Fix gettext related links. (bpo-3860)
https://github.com/python/cpython/commit/c02a1f4ad8fcdbffad2911c5a31c71a17a89d713

**Comment by serhiy-storchaka** [comment]
New changeset ed77fbffa5bf81c8d16700370fe8bb63bbae1428 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31667: Fix gettext related links. (GH-3860) (bpo-3886)
https://github.com/python/cpython/commit/ed77fbffa5bf81c8d16700370fe8bb63bbae1428

**Comment by serhiy-storchaka** [comment]
New changeset ef346a2473376c888ff160db9623eaa9871db2ac by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31667: Fix gettext related links. (GH-3860) (bpo-4100)
https://github.com/python/cpython/commit/ef346a2473376c888ff160db9623eaa9871db2ac
