### ISSUE TITLE
trivial typos in Tools/msi/uploadrelease.bat

### ISSUE THREAD

**Issue by 6c8a72cc-9872-4016-ae96-23477ed791a8** [python/cpython#75843]
BPO | [31662](https://bugs.python.org/issue31662)
--- | :---
Nosy | @ned-deily, @zooba, @akruis
PRs | <li>python/cpython#3851</li><li>python/cpython#3858</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-10-02.16:20:42.385>
created_at = <Date 2017-10-02.08:12:16.826>
labels = ['3.8', 'type-bug', '3.7', 'build']
title = 'trivial typos in Tools/msi/uploadrelease.bat'
updated_at = <Date 2017-10-03.08:48:30.331>
user = 'https://github.com/akruis'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.08:48:30.331>
actor = 'ned.deily'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-10-02.16:20:42.385>
closer = 'steve.dower'
components = ['Build']
creation = <Date 2017-10-02.08:12:16.826>
creator = 'anselm.kruis'
dependencies = []
files = []
hgrepos = []
issue_num = 31662
keywords = ['patch']
message_count = 5.0
messages = ['303513', '303546', '303547', '303549', '303581']
nosy_count = 3.0
nosy_names = ['ned.deily', 'steve.dower', 'anselm.kruis']
pr_nums = ['3851', '3858']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31662'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 6c8a72cc-9872-4016-ae96-23477ed791a8** [comment]
There are 3 trivial typos in [Tools/msi/uploadrelease.bat](https://github.com/python/cpython/blob/main/Tools/msi/uploadrelease.bat): "godo" instead of "goto" in lines 25 to 28.

**Comment by zooba** [comment]
New changeset efb560eee28b6b2418e1231573ca62574d6dc07b by Steve Dower (Anselm Kruis) in branch 'master':
bpo-31662: Fix typos in uploadrelease.bat script
https://github.com/python/cpython/commit/efb560eee28b6b2418e1231573ca62574d6dc07b

**Comment by zooba** [comment]
Thanks. It is indeed trivial, so I'll merge and backport it.

**Comment by zooba** [comment]
New changeset d6201cb0e865dad116ffe46e5ea3d02e8eeb42c1 by Steve Dower (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31662: Fix typos in uploadrelease.bat script (bpo-3858)
https://github.com/python/cpython/commit/d6201cb0e865dad116ffe46e5ea3d02e8eeb42c1

**Comment by ned-deily** [comment]
New changeset a51c760ddd7ad2513202e419cde90670283a6bc9 by Ned Deily (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31662: Fix typos in uploadrelease.bat script (bpo-3858)
https://github.com/python/cpython/commit/a51c760ddd7ad2513202e419cde90670283a6bc9
