### ISSUE TITLE
sys.executable different in os.execv'd python3.6 virtualenv session in python2 vs python3

### ISSUE THREAD

**Issue by 834e2c04-ecd2-4a99-9b10-7be18891e5d3** [python/cpython#75841]
BPO | [31660](https://bugs.python.org/issue31660)
--- | :---
Nosy | @warsaw, @vsajip, @ronaldoussoren, @ned-deily, @bitdancer, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-03.23:57:30.193>
created_at = <Date 2017-10-02.03:12:27.813>
labels = ['OS-mac', 'invalid']
title = "sys.executable different in os.execv'd python3.6 virtualenv session in python2 vs python3"
updated_at = <Date 2018-10-03.23:57:30.190>
user = 'https://bugs.python.org/StephenMoore'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-03.23:57:30.190>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2018-10-03.23:57:30.193>
closer = 'cheryl.sabella'
components = ['macOS']
creation = <Date 2017-10-02.03:12:27.813>
creator = 'Stephen Moore'
dependencies = []
files = []
hgrepos = []
issue_num = 31660
keywords = []
message_count = 6.0
messages = ['303507', '303530', '303551', '303569', '303570', '327018']
nosy_count = 7.0
nosy_names = ['barry', 'vinay.sajip', 'ronaldoussoren', 'ned.deily', 'r.david.murray', 'cheryl.sabella', 'Stephen Moore']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31660'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by 834e2c04-ecd2-4a99-9b10-7be18891e5d3** [comment]
Hi,

I've come across a problem whereby if you do an os.execv to a python3.6 virtualenv python inside python2.7 vs python3.6 then the resulting python session has a different sys.executable.

Where if you os.execv from python2.7 the sys.executable is equal to the virtualenv python

Whereas from python3.6 the resulting python session has a sys.executable of the system python.

An example of this in play can be found at https://gist.github.com/delfick/d750dc83e3b28e90cef8e2bfbd5b175a

Note that I don't see the problem if the virtualenv is based on python2.7 (https://gist.github.com/delfick/f1ad6872e2614189a7d98f2583ffc564)

**Comment by bitdancer** [comment]
virtualenv is not part of the standard library.  What happens if you use venv instead?

**Comment by ned-deily** [comment]
I suspect what is being seen here is essentially a duplicate of bpo-31363. On macOS framework builds, a python launcher executable is used ([Mac/Tools/pythonw.c](https://github.com/python/cpython/blob/main/Mac/Tools/pythonw.c)) to exec the real Python interpreter binary and the launcher uses the \_\_PYVENV_LAUNCHER__ environment variable to be able to handle symlinks (work initially implemented in bpo-15307).

**Comment by 834e2c04-ecd2-4a99-9b10-7be18891e5d3** [comment]
It appears the problem doesn't appear when using python3 -m venv.

Also it seems \_\_PYVENV_LAUNCHER__ is set to the virtualenv's python except when it's a python3.6 virtualenv and we os.execv from python3.6, where it's set the system python.

Should I be making an issue with the virtualenv project?

**Comment by 834e2c04-ecd2-4a99-9b10-7be18891e5d3** [comment]
I just realised python3 sets it's own \_\_PYVENV_LAUNCHER__ and if you unset it before calling to os.execv, then the virtualenv has the correct sys.executable.
