### ISSUE TITLE
test.test_imp.ImportTests.test_load_source has side effects

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75857]
BPO | [31676](https://bugs.python.org/issue31676)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @ezio-melotti, @voidspace, @ericsnowcurrently, @serhiy-storchaka, @Mariatta
PRs | <li>python/cpython#3871</li><li>python/cpython#3988</li>
Files | <li>[tests-bigmem.txt](https://bugs.python.org/file47185/tests-bigmem.txt "Uploaded as text/plain at 2017-10-03.12:47:35 by @serhiy-storchaka"): Full log</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-18.08:13:52.813>
created_at = <Date 2017-10-03.12:46:07.105>
labels = ['type-bug', '3.7']
title = 'test.test_imp.ImportTests.test_load_source has side effects'
updated_at = <Date 2017-10-18.08:13:52.811>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-18.08:13:52.811>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-18.08:13:52.813>
closer = 'vstinner'
components = []
creation = <Date 2017-10-03.12:46:07.105>
creator = 'serhiy.storchaka'
dependencies = []
files = ['47185']
hgrepos = []
issue_num = 31676
keywords = ['patch']
message_count = 9.0
messages = ['303608', '303619', '303620', '303621', '303622', '303713', '304358', '304551', '304560']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'ezio.melotti', 'michael.foord', 'eric.snow', 'serhiy.storchaka', 'Mariatta']
pr_nums = ['3871', '3988']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31676'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I have found a strange failure when run the bigmem tests.

```pytb
0:20:19 load avg: 1.04 [116/407/1] test_cgitb
test test_cgitb failed -- Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_cgitb.py", line 23, in test_html
    raise ValueError("Hello World")
ValueError: Hello World

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/serhiy/py/cpython/Lib/test/test_cgitb.py", line 27, in test_html
    html = cgitb.html(sys.exc_info())
  File "/home/serhiy/py/cpython/Lib/cgitb.py", line 117, in html
    records = inspect.getinnerframes(etb, context)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 1483, in getinnerframes
    frameinfo = (tb.tb_frame,) + getframeinfo(tb, context)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 1445, in getframeinfo
    lines, lnum = findsource(frame)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 780, in findsource
    module = getmodule(object, file)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 739, in getmodule
    f = getabsfile(module)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 708, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/home/serhiy/py/cpython/Lib/inspect.py", line 693, in getsourcefile
    if os.path.exists(filename):
  File "/home/serhiy/py/cpython/Lib/genericpath.py", line 19, in exists
    os.stat(path)
ValueError: embedded null byte
```


0:20:19 load avg: 1.04 [117/407/2] test_csv -- test_cgitb failed


It is not reproduced when run test_cgitb separately.

**Comment by vstinner** [comment]
I bisect the bug manually and using test.bisect. I identified that the bug is triggered when you run the following 3 tests:
\---
test.test_imp.ImportTests.test_load_source
test.test_cgitb.TestCgitb.test_html
test.test_cgitb.TestCgitb.test_fonts
\---

Write these tests into "tests" file and run:

./python -m test.bisect -uall -M4G test_imp test_cgitb --matchfile=tests

**Comment by vstinner** [comment]
Sorry, run:

./python -m test -M4G test_imp test_cgitb --matchfile=tests

**Comment by vstinner** [comment]
The problem is that imp.load_source() modifies \_\_file__ of the \_\_main__ module.

Example of a file x.py:
\---
```py
import imp
import sys
print(sys.modules[__name__])
try:
    imp.load_source(__name__, __file__ + "\0")
except:
    pass
print(sys.modules[__name__])
```

---

Output:
\---
\<module '\_\_main__' from 'x.py'\>
\<module '\_\_main__' from 'x.py\\x00'\>
\---

**Comment by vstinner** [comment]
Attached [PR 3871](https://github.com/python/cpython/pull/3871) fixes the side effect in test_imp, but I'm not sure that it's the best fix. Maybe load_source() should use a "transaction" to restore attributes on failure?

load_source() seems to be used imp.reload() for example. Do you expect this function to restore the imported module to its original state on failure?

**Comment by brettcannon** [comment]
The whole imp module is deprecated so I'm personally not bothered by imp.load_source() not being strengthened to be more sane.

**Comment by vstinner** [comment]
New changeset a505ecdc5013cd8f930aacc1ec4fb2afa62d3853 by Victor Stinner in branch 'master':
bpo-31676: Fix test_imp.test_load_source() side effect (bpo-3871)
https://github.com/python/cpython/commit/a505ecdc5013cd8f930aacc1ec4fb2afa62d3853

**Comment by Mariatta** [comment]
New changeset 178148025494c4058571831fb11fc8eeff8b7365 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31676: Fix test_imp.test_load_source() side effect (GH-3871) (GH-3988)
https://github.com/python/cpython/commit/178148025494c4058571831fb11fc8eeff8b7365

**Comment by vstinner** [comment]
I tested "./python -m test -uall -M4G test_imp test_cgitb" on 3.6 and the master branch. Both tests now pass correctly. I close the issue.
