### ISSUE TITLE
Associate .wasm with application/wasm

### ISSUE THREAD

**Issue by 4486b781-9e87-4500-b952-20149ab73698** [python/cpython#75851]
BPO | [31670](https://bugs.python.org/issue31670)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka, @flagxor, @tirkarthi
PRs | <li>python/cpython#3861</li>
Superseder | <li>bpo-34758: http.server module sets incorrect mimetype for WebAssembly files</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-10-24.08:49:33.687>
created_at = <Date 2017-10-03.06:22:26.661>
labels = ['type-feature', '3.8', 'expert-IO']
title = 'Associate .wasm with application/wasm'
updated_at = <Date 2019-10-24.08:49:33.684>
user = 'https://github.com/flagxor'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-24.08:49:33.684>
actor = 'xtreak'
assignee = 'none'
closed = True
closed_date = <Date 2019-10-24.08:49:33.687>
closer = 'xtreak'
components = ['IO']
creation = <Date 2017-10-03.06:22:26.661>
creator = 'flagxor'
dependencies = []
files = []
hgrepos = []
issue_num = 31670
keywords = ['patch']
message_count = 8.0
messages = ['303578', '303634', '303658', '303660', '303661', '316379', '329449', '338738']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'flagxor', 'xtreak', 'runpiw']
pr_nums = ['3861']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '34758'
type = 'enhancement'
url = 'https://bugs.python.org/issue31670'
versions = ['Python 3.8']
```

</p></details>

**Comment by 4486b781-9e87-4500-b952-20149ab73698** [comment]
WebAssembly is tentatively spec'ed to require the application/wasm mime type for download sources:
https://github.com/WebAssembly/design/blob/master/Web.md

The mimetype module should associate .wasm with this mimetype to allow users of SimpleHTTPServer etc. to be able to easily use WebAssembly.

**Comment by bitdancer** [comment]
We generally wait for something a bit stronger than "tentatively" before adding a mime type (ie: an actual submission to the relevant standards channel).

**Comment by 4486b781-9e87-4500-b952-20149ab73698** [comment]
Tentative might be an understatement.
There was 4 browser sign-off on using that mime type within the WebAssembly CG, which has drafted the spec so far.
We're in the process of handing v1 of the spec off to the WebAssembly Working Group on our way to a good and proper W3C REC.
However, use of the mime type is already shipping in Chrome and I believe on the way with other browsers (and just got added to our shared toolchain).

That said we should get a proper allocation with IANA.
I've added an agenda item to our next Working Group meeting to have the group explicitly empower me to approach IANA:
https://github.com/WebAssembly/meetings/blob/master/2017/WG-10-23.md

Be back in month with a IANA request email to reference.

Assuming we've sorted out a proper allocation, do you have a sense of if getting the file type into python2.7 is likely?

Thanks!

**Comment by serhiy-storchaka** [comment]
Yes, updates of the mimetype database usually are backported to 2.7.

**Comment by bitdancer** [comment]
Yes, if/when it goes in it will go in to all currently maintained versions.  I've adjusted 'versions' accordingly.
