### ISSUE TITLE
Tkinter: memory leak in splitlines() and split()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75856]
BPO | [31675](https://bugs.python.org/issue31675)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#3866</li><li>python/cpython#3874</li><li>python/cpython#3876</li>
Dependencies | <li>bpo-31673: Fix the name of Tkinter&#x27;s adderrorinfo method</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-10-04.19:02:26.560>
created_at = <Date 2017-10-03.12:04:23.288>
labels = ['3.7', 'expert-tkinter', 'performance']
title = 'Tkinter: memory leak in splitlines() and split()'
updated_at = <Date 2017-10-04.19:02:26.559>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-04.19:02:26.559>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-10-04.19:02:26.560>
closer = 'serhiy.storchaka'
components = ['Tkinter']
creation = <Date 2017-10-03.12:04:23.288>
creator = 'serhiy.storchaka'
dependencies = ['31673']
files = []
hgrepos = []
issue_num = 31675
keywords = ['patch']
message_count = 7.0
messages = ['303599', '303602', '303604', '303611', '303643', '303648', '303726']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = ['3866', '3874', '3876']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31675'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
There is a memory leak in Tkinter's methods splitlines() and split() when pass a string larger than 2 GiB (when encoded to UTF-8).

**Comment by vstinner** [comment]
Which function? Do you mean split() and splitlist() methods of tkapp? C functions \_tkinter_tkapp_split() and \_tkinter_tkapp_splitlist().

Do you know how to reproduce the memory leak?

**Comment by serhiy-storchaka** [comment]
Just run the bigmem tests with ulimit (after fixing bpo-31673).

    (ulimit -v 4350000; ./python -m test -vuall -M4G test_tcl)

**Comment by vstinner** [comment]
Oh, Python splitlist() doesn't seem to be documented.

Tcl SplitList documentation: https://www.tcl.tk/man/tcl/TclLib/SplitList.htm

**Comment by serhiy-storchaka** [comment]
New changeset 27c623c845dd6e4b8e1782666ca3a956636da266 by Serhiy Storchaka in branch 'master':
bpo-31675: Fix memory leaks in Tkinter's methods splitlist() and split() (bpo-3866)
https://github.com/python/cpython/commit/27c623c845dd6e4b8e1782666ca3a956636da266

**Comment by serhiy-storchaka** [comment]
New changeset a65b2420f681c45db43e94bfe3dc50ad1dfcd03d by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31675: Fix memory leaks in Tkinter's methods splitlist() and split() (GH-3866) (bpo-3874)
https://github.com/python/cpython/commit/a65b2420f681c45db43e94bfe3dc50ad1dfcd03d

**Comment by serhiy-storchaka** [comment]
New changeset 328b5d0e64798cf17360c6b2a07c2b18f2798b88 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31675: Fix memory leaks in Tkinter's methods splitlist() and split() (GH-3866) (bpo-3876)
https://github.com/python/cpython/commit/328b5d0e64798cf17360c6b2a07c2b18f2798b88
