### ISSUE TITLE
Incorrect C Function name for timedelta

### ISSUE THREAD

**Issue by 4fd21500-1b95-4e70-8034-507c03558639** [python/cpython#75859]
BPO | [31678](https://bugs.python.org/issue31678)
--- | :---
Nosy | @berkerpeksag, @Phobosmir
PRs | <li>python/cpython#3869</li><li>python/cpython#4274</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-04.10:46:51.512>
created_at = <Date 2017-10-03.13:47:42.265>
labels = ['type-bug', '3.7', 'docs']
title = 'Incorrect C Function name for timedelta'
updated_at = <Date 2017-11-04.10:46:51.510>
user = 'https://github.com/Phobosmir'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-04.10:46:51.510>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-04.10:46:51.512>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-10-03.13:47:42.265>
creator = 'phobosmir'
dependencies = []
files = []
hgrepos = []
issue_num = 31678
keywords = ['patch']
message_count = 4.0
messages = ['303616', '305552', '305553', '305554']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'phobosmir']
pr_nums = ['3869', '4274']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31678'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 4fd21500-1b95-4e70-8034-507c03558639** [comment]
Documentation:

PyDateTime_DELTA_GET_MICROSECOND
https://docs.python.org/3/c-api/datetime.html#c.PyDateTime_DELTA_GET_MICROSECOND

Should be:
PyDateTime_DELTA_GET_MICROSECONDS

**Comment by berkerpeksag** [comment]
New changeset 82cd3cede804ca694fb0657fd985d5eff84a414f by Berker Peksag (Phobosmir) in branch 'master':
bpo-31678: Fix typo in PyDateTime_DELTA_GET_MICROSECONDS (GH-3869)
https://github.com/python/cpython/commit/82cd3cede804ca694fb0657fd985d5eff84a414f

**Comment by berkerpeksag** [comment]
New changeset f9387469e82eccb6e0471037033f921be7f59909 by Berker Peksag (Miss Islington (bot)) in branch '3.6':
bpo-31678: Fix typo in PyDateTime_DELTA_GET_MICROSECONDS (GH-3869)
https://github.com/python/cpython/commit/f9387469e82eccb6e0471037033f921be7f59909

**Comment by berkerpeksag** [comment]
Good catch, thank you!
