### ISSUE TITLE
string.Template: code, docs and PEP all disagree on definition of identifier

### ISSUE THREAD

**Issue by 444a5333-691d-47d1-9316-49e7a80f62df** [python/cpython#75850]
BPO | [31669](https://bugs.python.org/issue31669)
--- | :---
Nosy | @warsaw, @tjol, @serhiy-storchaka
Superseder | <li>bpo-31672: string.Template should use re.ASCII flag</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-03.13:17:15.566>
created_at = <Date 2017-10-03.06:02:28.152>
labels = ['3.7', 'invalid', 'type-bug', 'library']
title = 'string.Template: code, docs and PEP all disagree on definition of identifier'
updated_at = <Date 2017-10-03.15:07:13.699>
user = 'https://github.com/tjol'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.15:07:13.699>
actor = 'barry'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-03.13:17:15.566>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-10-03.06:02:28.152>
creator = 'tjollans'
dependencies = []
files = []
hgrepos = []
issue_num = 31669
keywords = []
message_count = 4.0
messages = ['303577', '303614', '303623', '303625']
nosy_count = 3.0
nosy_names = ['barry', 'tjollans', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = '31672'
type = 'behavior'
url = 'https://bugs.python.org/issue31669'
versions = ['Python 3.7']
```

</p></details>

**Comment by 444a5333-691d-47d1-9316-49e7a80f62df** [comment]
string.Template matches a $identifier with the regex [_a-z][_a-z0-9]* and re.IGNORECASE. This matches S, ſ and s, but not ß. https://github.com/python/cpython/blob/master/Lib/string.py#L78 (this code came up on python-dev)

The docs specify "any case-insensitive ASCII alphanumeric string (including underscores) that starts with an underscore or ASCII letter.". This includes S and s, but neither ſ nor ß. https://docs.python.org/3/library/string.html#template-strings

The docs refer to PEP-292, which specifies "By default, 'identifier' must spell a Python identifier [...]" This includes S, ſ, s and ß. https://www.python.org/dev/peps/pep-0292/

It's not entirely clear what the correct behaviour is (probably accepting any Python identifier). In any case, the current behaviour of string.Template is a bit silly, but changing it might break stuff.

**Comment by serhiy-storchaka** [comment]
There is no contradiction. PEP-292 means Python 2 identifiers. Python 3 documentation was changed according to changing the definition of Python identifiers (see bpo-24351).

**Comment by 444a5333-691d-47d1-9316-49e7a80f62df** [comment]
Should the PEP be clarified?

**Comment by warsaw** [comment]
PEPs aren't really intended to be ongoing specs, keeping up with implementation changes.  The documentation is pretty clear in defining identifiers as "any case-insensitive ASCII alphanumeric string (including underscores) that starts with an underscore or ASCII letter".
