### ISSUE TITLE
Scientific formatting of decimal 0 different from float 0

### ISSUE THREAD

**Issue by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [python/cpython#75865]
BPO | [31684](https://bugs.python.org/issue31684)
--- | :---
Nosy | @rhettinger, @facundobatista, @mdickinson, @ericvsmith, @skrah, @asmeurer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-03.21:46:21.562>
labels = []
title = 'Scientific formatting of decimal 0 different from float 0'
updated_at = <Date 2017-10-04.19:02:15.707>
user = 'https://github.com/asmeurer'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-04.19:02:15.707>
actor = 'skrah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-10-03.21:46:21.562>
creator = 'Aaron.Meurer'
dependencies = []
files = []
hgrepos = []
issue_num = 31684
keywords = []
message_count = 7.0
messages = ['303653', '303672', '303719', '303720', '303723', '303725', '303728']
nosy_count = 6.0
nosy_names = ['rhettinger', 'facundobatista', 'mark.dickinson', 'eric.smith', 'skrah', 'Aaron.Meurer']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31684'
versions = []
```

</p></details>

**Comment by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [comment]
```pycon
>>> '{:+.19e}'.format(0.)
'+0.0000000000000000000e+00'
>>> import decimal
>>> '{:+.19e}'.format(decimal.Decimal(0))
'+0.0000000000000000000e+19'
```


Note the decimal uses e+19 instead of e+00. Obviously it's still mathematically correct, but it's annoying to have anything other than e+00 for a 0 value.

**Comment by mdickinson** [comment]
The aim here is to capture the original Decimal value where possible, including the exponent information. (Unlike floats, trailing zeros in a `Decimal` instance are significant.)

```pycon
>>> from decimal import Decimal
>>> Decimal('+0.0000000000000000000e+19')
Decimal('0')
>>> Decimal('+0.0000000000000000000e+00')
Decimal('0E-19')
```

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Yes, from the point of view of decimal it's the right thing:

```pycon
>>> x = Decimal("1e25").quantize(Decimal("1e30"))
>>> x
Decimal('0E+30')
>>> '{:+.19e}'.format(x)
'+0.0000000000000000000e+49'
>>> 
```


The original magnitude should be traceable (the example is not
perfect but the first thing that quickly came to mind).

**Comment by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [comment]
I guess I would expect that to be captured by the number of zeros printed (and obviously doing a string format operation with a set number of digits destroys that information).

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
I don't think format() destroys the information:

```pycon
>>> '{:+.19e}'.format(Decimal("0.00000e20"))
'+0.0000000000000000000e+34'
```



The original magnitude was e+15, after formatting it's still e+15.

**Comment by 6fd3d553-ff50-40bd-a9a1-836658cb1a33** [comment]
I meant that format() destroys information in a decimal in general. Obviously if you have n digits of precision and format with m \< n, then you lose information. 

I also can't help but feel that we're mixing up "trailing zeros" (i.e., precision), and "exponent" (magnitude), which should be orthogonal. I'm assuming that a decimal is represented internally as base\*10\*\*exponent. I'm also assuming that Decimal(0) sets both base and exponent to 0. It doesn't make sense to me that a string formatting operation that requests a certain number of digits of precision should change the exponent. 

I get that 0.0 is different from 0.00000, but in that case, they should print differently: as '0.0' and '0.00000'. It seems sly to try to maintain that through a format operation via the exponent, especially when format \*in general* loses precision information for a decimal anyway (by "format" I mean format with a set number of digits requested). Especially since that "trick" only works for exactly one number, zero. If you do '{:+.30e}'.format(Decimal('1.0000000000000000000')) or '{:+.10e}'.format(Decimal('1.0000000000000000000')), no such trick is used, because no such trick can be used. You just lose information. 

I'm sure my mental model is off here. I'm used to sympy.Float/mpmath.mpf where values like 0\*2\*\*i are normalized to i = 0 (e.g. mpmath.mpf((0, 0, 20, 0)).\_mpf_ gives (0, 0, 0, 0)), so this problem never comes up in the code that I'm used to.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
> I'm also assuming that Decimal(0) sets both base and exponent to 0.

No, 0 is really special in the IBM specification. The magnitude is
kept, the precision is not.

```pycon
>>> Decimal("0e10") * Decimal("0e20") 
Decimal('0E+30')


>>> Decimal("0.000e10")
Decimal('0E+7')
```


So we're basically doing the reverse of the above in formatting when a
precision is given.
