### ISSUE TITLE
pydot missing write, write_png, etc

### ISSUE THREAD

**Issue by 7b8d8117-981c-446b-aa57-bd20aa05d04d** [python/cpython#75860]
BPO | [31679](https://bugs.python.org/issue31679)
--- | :---
Nosy | @zware
Files | <li>[ML_ex2.py](https://bugs.python.org/file47186/ML_ex2.py "Uploaded as text/plain at 2017-10-03.17:04:17 by jbrearley")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-03.17:13:31.921>
created_at = <Date 2017-10-03.17:04:18.229>
labels = ['extension-modules', 'type-bug']
title = 'pydot missing write, write_png, etc'
updated_at = <Date 2017-10-03.17:13:31.919>
user = 'https://bugs.python.org/jbrearley'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.17:13:31.919>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-03.17:13:31.921>
closer = 'zach.ware'
components = ['Extension Modules']
creation = <Date 2017-10-03.17:04:18.229>
creator = 'jbrearley'
dependencies = []
files = ['47186']
hgrepos = []
issue_num = 31679
keywords = []
message_count = 2.0
messages = ['303632', '303633']
nosy_count = 2.0
nosy_names = ['zach.ware', 'jbrearley']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31679'
versions = ['Python 3.6']
```

</p></details>

**Comment by 7b8d8117-981c-446b-aa57-bd20aa05d04d** [comment]
I have successfully installed Graphviz tool from http://graphviz.org, updated my PATH variable appropriately and can generate .PNG files using Python module Graphviz with WinPython 3.6.1. However, I cannot get anywhere using the pydot V1.2.3 module in the same environment. 

The online help suggests that there there are write & write_png members but I can find no trace of them. My sample script is attached. The error I get is:

```pytb
Traceback (most recent call last):
  File "ML_ex2.py", line 109, in <module>
    graph.write(path=out_fn, format="png")
AttributeError: 'list' object has no attribute 'write'
```

**Comment by zware** [comment]
pydot is not part of the standard library; you'll need to find their issue tracker (looks like maybe https://github.com/erocarrera/pydot/issues?) and open a ticket there.
