### ISSUE TITLE
Cannot connect to CE path `127.0.0.1:8010`

### ISSUE THREAD

**Issue by c5226a7f-63fe-40fd-a30d-0c2bc56bcba9** [python/cpython#75866]
BPO | [31685](https://bugs.python.org/issue31685)
--- | :---
Nosy | @zware, @strawberrysandcream

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-03.23:11:13.609>
created_at = <Date 2017-10-03.22:11:19.078>
labels = ['invalid']
title = 'Cannot connect to CE path `127.0.0.1:8010`'
updated_at = <Date 2017-10-03.23:11:26.670>
user = 'https://github.com/strawberrysandcream'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.23:11:26.670>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-03.23:11:13.609>
closer = 'zach.ware'
components = []
creation = <Date 2017-10-03.22:11:19.078>
creator = 'maolvera'
dependencies = []
files = []
hgrepos = []
issue_num = 31685
keywords = []
message_count = 2.0
messages = ['303656', '303659']
nosy_count = 2.0
nosy_names = ['zach.ware', 'maolvera']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31685'
versions = ['Python 2.7']
```

</p></details>

**Comment by c5226a7f-63fe-40fd-a30d-0c2bc56bcba9** [comment]
Is there any reason it cannot connect to CE path?

C:\\Users\\Documents\\Twister-git_hub_branch\\client\\executionprocess\>ExecutionProcess.py -u user -e EP-name -s 127.0.0.1:8010

TWISTER_PATH is set to `C:\Users\Documents\Twister-git_hub_branch\client\executionprocess`.

Catching `Ctrl + C` signal OK.

Portable mode: Appending `C:\Users\Documents\Twister-git_hub_branch` to python path.

EP Info: Connecting to the Central Engine...
*ERROR* Cannot connect to CE path `127.0.0.1:8010`! Exiting!
Cannot connect to server! Farewell!

**Comment by zware** [comment]
This issue does not appear to have anything to do with the CPython interpreter or standard library, and this issue tracker is not a help forum.  Please try python-list@python.org for assistance, but you'll need to provide the other users of the list significantly more detail about what you're trying to do and how to get any kind of meaningful help.
