### ISSUE TITLE
pkgutil.get_data() leaks open files in Python 2.7

### ISSUE THREAD

**Issue by 308d1678-b02d-445e-978b-e5e183845395** [python/cpython#75862]
BPO | [31681](https://bugs.python.org/issue31681)
--- | :---
Nosy | @merwok, @elprans
PRs | <li>python/cpython#3875</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/merwok'
closed_at = <Date 2017-10-09.15:22:09.938>
created_at = <Date 2017-10-03.19:39:44.162>
labels = ['library', 'performance']
title = 'pkgutil.get_data() leaks open files in Python 2.7'
updated_at = <Date 2017-11-06.18:44:09.169>
user = 'https://github.com/elprans'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-06.18:44:09.169>
actor = 'berker.peksag'
assignee = 'eric.araujo'
closed = True
closed_date = <Date 2017-10-09.15:22:09.938>
closer = 'eric.araujo'
components = ['Library (Lib)']
creation = <Date 2017-10-03.19:39:44.162>
creator = 'Elvis.Pranskevichus'
dependencies = []
files = []
hgrepos = []
issue_num = 31681
keywords = ['patch']
message_count = 2.0
messages = ['303642', '303965']
nosy_count = 2.0
nosy_names = ['eric.araujo', 'Elvis.Pranskevichus']
pr_nums = ['3875']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31681'
versions = ['Python 2.7']
```

</p></details>

**Comment by 308d1678-b02d-445e-978b-e5e183845395** [comment]
pkgutil.get_data() does this:

```py
     def get_data(self, pathname):
        return open(pathname, "rb").read()
```


which very obviously leaks open file descriptors.  This has been fixed in 3.x by https://github.com/python/cpython/commit/1ab58dfb12dedb7, but never backported to 2.7.

**Comment by merwok** [comment]
New changeset cfe1aefcbd2534ddc1059a7332842644e6c8d1e4 by Éric Araujo (Elvis Pranskevichus) in branch '2.7':
bpo-31681: Make sure pkgutil.get_data closes files properly (bpo-3875)
https://github.com/python/cpython/commit/cfe1aefcbd2534ddc1059a7332842644e6c8d1e4
