### ISSUE TITLE
Expose curses library name and version on Python level

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75861]
BPO | [31680](https://bugs.python.org/issue31680)
--- | :---
Nosy | @Yhg1s, @terryjreedy, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#4217</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-10-30.11:23:08.706>
created_at = <Date 2017-10-03.19:39:02.613>
labels = ['extension-modules', 'type-feature', '3.8']
title = 'Expose curses library name and version on Python level'
updated_at = <Date 2018-10-30.11:23:21.692>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-10-30.11:23:21.692>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-10-30.11:23:08.706>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-10-03.19:39:02.613>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31680
keywords = ['patch']
message_count = 10.0
messages = ['303640', '303644', '303645', '303646', '303654', '303657', '303845', '303846', '305381', '328896']
nosy_count = 4.0
nosy_names = ['twouters', 'terry.reedy', 'vstinner', 'serhiy.storchaka']
pr_nums = ['4217']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31680'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The name and the version of the curses library are needed for work around bugs in old versions or skip tests on platforms that provide broken curses library (like OpenBSD providing ncurses 5.7).

The curses and \_curses modules provide the attribute "version" (= b'2.2'), but this is just a version of the module.

**Comment by vstinner** [comment]
How can we get the ncurses version?

**Comment by vstinner** [comment]
On Fedora 26, /usr/include/ncurses/curses.h contains:
\---
```c
/* These are defined only in curses.h, and are used for conditional compiles */
#define NCURSES_VERSION_MAJOR 6
#define NCURSES_VERSION_MINOR 0
#define NCURSES_VERSION_PATCH 20170212

/* This is defined in more than one ncurses header, for identification */
#undef  NCURSES_VERSION
#define NCURSES_VERSION "6.0"

/*
 * Identify the mouse encoding version.
 */
#define NCURSES_MOUSE_VERSION 2
```

---

You want to expose such versions? Do you know if there are "curses" implementations different than GNU ncurses?
https://www.gnu.org/software/ncurses/

I'm asking to know how other implementations expose their versions.

**Comment by vstinner** [comment]
> The name and the version of the curses library are needed for work around bugs in old versions or skip tests on platforms that provide broken curses library (like OpenBSD providing ncurses 5.7).

If there are known issues depending on the ncurses version, it may help to export this version in the test.pythoninfo utility. Do you have an example of known bug? Do we already skip tests depending on the ncurses version?

**Comment by serhiy-storchaka** [comment]
Yes, this is what I meant. The version should be exposed as a tuple (major, minor, patch) or as a special named tuple. I don't know what to do with other implementations. NCURSES_VERSION_MAJOR is not a part of standard. One solution -- set the version to (0, 0, 0) for unknown implementations. Or expose ncurses version as optional ncurses_version, and expose versions for other known implementations with different names.

A known bug is bpo-15037. We still don't skip tests depending on the ncurses version because there is no easy way to determine the ncurses version in Python.

**Comment by vstinner** [comment]
I suggest:

```py
curses._NCURSES_VERSION_INFO = (6, 0, 20170212)
curses._NCURSES_VERSION = "6.0"
curses._NCURSES_MOUSE_VERSION = 2
```


Similar example, the readline module uses:

```c
    PyModule_AddIntConstant(m, "_READLINE_VERSION", RL_READLINE_VERSION);
    PyModule_AddIntConstant(m, "_READLINE_RUNTIME_VERSION", rl_readline_version);
    PyModule_AddStringConstant(m, "_READLINE_LIBRARY_VERSION", rl_library_version);
```


readline has two famous implementations: GNU readline and editline. editline reuses GNU readline constants, but the string mentions "editline". Example on macOS El Capitain (test.pythoninfo output):

readline.\_READLINE_LIBRARY_VERSION: EditLine wrapper
readline.\_READLINE_RUNTIME_VERSION: 0x402
readline.\_READLINE_VERSION: 0x402

http://buildbot.python.org/all/builders/x86-64%20El%20Capitan%203.x/builds/871/steps/pythoninfo/logs/stdio

I'm not sure that it's useful to make versions public. I suggest to start with private versions, since we only plan to use them in tests right now.

**Comment by terryjreedy** [comment]
pythoninfo seems like the right place.  It is publicly readable.  We just reserved the right to change it in any release as needed.  (This actually is useful to other users also as long as they know.) bpo-15037 was originally filed for 3.4 and is currently marked for 3.6.  Backporting this to 3.6 will allow a 3.6 fix for bpo-15037.

**Comment by serhiy-storchaka** [comment]
No need to backport this to 3.6. The test in 3.6 can be skipped on OpenBSD, independently from the ncurses version.

**Comment by serhiy-storchaka** [comment]
[PR 4217](https://github.com/python/cpython/pull/4217) adds a named tuple curses.ncurses_version containing the three components of the ncurses library version: major, minor, and patch.

```pycon
>>> curses.ncurses_version
curses.ncurses_version(major=6, minor=0, patch=20160625)
```


Other curses implementation don't provide a version programmically.
