### ISSUE TITLE
test_semaphore_tracker() of test_multiprocessing_spawn fails randomly (race condition?)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75868]
BPO | [31687](https://bugs.python.org/issue31687)
--- | :---
Nosy | @ncoghlan, @vstinner, @subler

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.23:27:14.912>
created_at = <Date 2017-10-04.09:36:35.852>
labels = ['3.7', 'tests']
title = 'test_semaphore_tracker() of test_multiprocessing_spawn fails randomly (race condition?)'
updated_at = <Date 2018-09-19.23:27:14.911>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.23:27:14.911>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.23:27:14.912>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-04.09:36:35.852>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31687
keywords = []
message_count = 9.0
messages = ['303678', '306557', '307355', '307356', '310360', '310949', '320613', '321016', '325825']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'vstinner', 'stevezh']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31687'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Recent example of the slow and busy (load of 8.05 with 2 CPUs) x86 Gentoo Refleaks 3.6 buildbot:

http://buildbot.python.org/all/builders/x86%20Gentoo%20Refleaks%203.6/builds/111/steps/test/logs/stdio

```pytb
== CPU count: 2
...
1:41:09 load avg: 8.05 [170/405/1] test_multiprocessing_spawn failed -- running: test_asyncio (1118 sec)
beginning 6 repetitions
123456
/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/unittest/case.py:633: ResourceWarning: unclosed file <_io.BufferedReader name=22>
  outcome.errors.clear()
test test_multiprocessing_spawn failed -- Traceback (most recent call last):
  File "/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/test/_test_multiprocessing.py", line 4091, in test_semaphore_tracker
    _multiprocessing.sem_unlink(name2)
AssertionError: OSError not raised
1:41:12 load avg: 7.97 [171/405/1] test_posixpath passed -- running: test_asyncio (1122 sec)
beginning 6 repetitions
123456
......
```

**Comment by vstinner** [comment]
Failure on x86 Gentoo Refleaks 3.6, two days ago:

http://buildbot.python.org/all/#/builders/72/builds/41

\======================================================================
FAIL: test_semaphore_tracker (test.test_multiprocessing_spawn.TestSemaphoreTracker)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/test/_test_multiprocessing.py", line 4161, in test_semaphore_tracker
    _multiprocessing.sem_unlink(name2)
AssertionError: OSError not raised
```

======================================================================
FAIL: test_sys_exit (test.test_multiprocessing_spawn.WithProcessesTestSubclassingProcess)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/buildbot/buildarea/3.6.ware-gentoo-x86.refleak/build/Lib/test/_test_multiprocessing.py", line 584, in test_sys_exit
    self.assertEqual(p.exitcode, 1)
AssertionError: None != 1
```

**Comment by vstinner** [comment]
x86 Tiger 3.x:

http://buildbot.python.org/all/#/builders/30/builds/260

\======================================================================
FAIL: test_semaphore_tracker (test.test_multiprocessing_forkserver.TestSemaphoreTracker)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/db3l/buildarea/3.x.bolen-tiger/build/Lib/test/_test_multiprocessing.py", line 4380, in test_semaphore_tracker
    _multiprocessing.sem_unlink(name2)
AssertionError: OSError not raised
```


======================================================================
FAIL: test_forkserver_sigkill (test.test_multiprocessing_forkserver.WithProcessesTestProcess)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/Users/db3l/buildarea/3.x.bolen-tiger/build/Lib/test/_test_multiprocessing.py", line 653, in test_forkserver_sigkill
    self.check_forkserver_death(signal.SIGKILL)
  File "/Users/db3l/buildarea/3.x.bolen-tiger/build/Lib/test/_test_multiprocessing.py", line 643, in check_forkserver_death
    self.assertTrue(evt.is_set())
AssertionError: False is not true
```

**Comment by 375b7e59-4103-45bc-878f-886f5b1ba4c6** [comment]
It maybe the semaphore tracker process doesn't unlink the semaphore as soon as possible when child process exit when the system is slow. Increase test case's time in the child and before assertRaises will help.
