### ISSUE TITLE
Exception: Cannot import `win32api`!

### ISSUE THREAD

**Issue by c5226a7f-63fe-40fd-a30d-0c2bc56bcba9** [python/cpython#75863]
BPO | [31682](https://bugs.python.org/issue31682)
--- | :---
Nosy | @zware, @strawberrysandcream

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-03.21:44:00.546>
created_at = <Date 2017-10-03.21:36:59.580>
labels = ['invalid', 'expert-installation']
title = 'Exception: Cannot import `win32api`!'
updated_at = <Date 2017-10-03.21:44:00.544>
user = 'https://github.com/strawberrysandcream'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-03.21:44:00.544>
actor = 'zach.ware'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-03.21:44:00.546>
closer = 'zach.ware'
components = ['Installation']
creation = <Date 2017-10-03.21:36:59.580>
creator = 'maolvera'
dependencies = []
files = []
hgrepos = []
issue_num = 31682
keywords = []
message_count = 2.0
messages = ['303650', '303652']
nosy_count = 2.0
nosy_names = ['zach.ware', 'maolvera']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31682'
versions = ['Python 2.7']
```

</p></details>

**Comment by c5226a7f-63fe-40fd-a30d-0c2bc56bcba9** [comment]
Hello, I'm a newbie at Python. I am trying to download Twister to be able to run hardware tests, and it gives me Exception: Cannot import `win32api`!.
I downloaded 'win32_221' and added it to C:\Python27\Scripts

It is still giving me the same error.

This is what I got

TWISTER_PATH is set to `C:\Users\user\Documents\Twister-git_hub_branch\client\executionprocess`.

```pytb
Traceback (most recent call last):
  File "C:\Users\user\Documents\Twister-git_hub_branch\client\executionprocess\ExecutionProcess.py", line 1563, in <module>
    raise Exception('Cannot import `win32api`!\n')
Exception: Cannot import `win32api`!
```

**Comment by zware** [comment]
win32api is part of the third-party pywin32 package, which is most easily installed by running `C:\Python27\python.exe -m pip install pypiwin32`.  For further assistance, please try either the comp.lang.python list at python-list@python.org, the pywin32 list at python-win32@python.org, or the #python channel on freenode.
