### ISSUE TITLE
scope error

### ISSUE THREAD

**Issue by a70a9bed-263a-4329-a21d-5e9667768f1a** [python/cpython#75869]
BPO | [31688](https://bugs.python.org/issue31688)
--- | :---
Nosy | @terryjreedy, @mdickinson, @bitdancer
Files | <li>[pythonerror.jpg](https://bugs.python.org/file47190/pythonerror.jpg "Uploaded as image/png at 2017-10-04.12:33:34 by abdullah patel"): jpg</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-04.16:48:23.725>
created_at = <Date 2017-10-04.12:33:34.721>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = 'scope error'
updated_at = <Date 2017-10-04.17:48:23.491>
user = 'https://bugs.python.org/abdullahpatel'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-04.17:48:23.491>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-04.16:48:23.725>
closer = 'r.david.murray'
components = ['Interpreter Core']
creation = <Date 2017-10-04.12:33:34.721>
creator = 'abdullah patel'
dependencies = []
files = ['47190']
hgrepos = []
issue_num = 31688
keywords = []
message_count = 4.0
messages = ['303682', '303689', '303710', '303721']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'mark.dickinson', 'r.david.murray', 'abdullah patel']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31688'
versions = ['Python 3.6']
```

</p></details>

**Comment by a70a9bed-263a-4329-a21d-5e9667768f1a** [comment]
there should be an error when this code is run. as  I have not defined the arguments (I was told by my computer science teacher that it should not work in theory) and parameters but it clearly works.

**Comment by mdickinson** [comment]
The code looks fine to me; I don't see any reason to expect an error.

What error were you expecting, and why?

**Comment by bitdancer** [comment]
Yes, this conforms to Python's namespace/scoping rules: nested scopes are allowed to reference (but not assign to) variables from the global scope even without a 'global' declaration.

**Comment by terryjreedy** [comment]
Abdullah, in the future, please upload or post runnable Python code, not an image.  Output can be copied into a message.  If you think IDLE is doing something wrong, test by running the code directly with Python.  If your file is test.py, enter the following on a Command Prompt command line.
path-to-your-python-code-dir\> python -m test.py

There would only be an IDLE issue (and then only maybe) if the code ran differently or produced different output in IDLE than with python directly.  That is not the case here.
