### ISSUE TITLE
Include missing info on required build steps and how to build installer

### ISSUE THREAD

**Issue by eb193824-a002-4e53-a73b-be75738ef3f2** [python/cpython#75872]
BPO | [31691](https://bugs.python.org/issue31691)
--- | :---
Nosy | @zooba, @native-api
PRs | <li>python/cpython#4426</li><li>python/cpython#4427</li><li>python/cpython#4428</li><li>python/cpython#4429</li><li>python/cpython#4430</li><li>python/cpython#4431</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-17.00:49:59.296>
created_at = <Date 2017-10-04.15:09:59.384>
labels = ['3.8', 'build', '3.7', 'type-crash']
title = 'Include missing info on required build steps and how to build installer'
updated_at = <Date 2017-11-17.22:10:20.294>
user = 'https://github.com/native-api'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-17.22:10:20.294>
actor = 'Ivan.Pozdeev'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-17.00:49:59.296>
closer = 'steve.dower'
components = ['Build']
creation = <Date 2017-10-04.15:09:59.384>
creator = 'Ivan.Pozdeev'
dependencies = []
files = []
hgrepos = []
issue_num = 31691
keywords = ['patch']
message_count = 7.0
messages = ['303700', '306113', '306403', '306404', '306405', '306406', '306407']
nosy_count = 2.0
nosy_names = ['steve.dower', 'Ivan.Pozdeev']
pr_nums = ['4426', '4427', '4428', '4429', '4430', '4431']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31691'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
Current build instructions no not mention required preliminary steps before building the solution and don't say how to build the installer package - which is the ultimate goal of a build.

Being on XP at the moment, I cannot check the validity of build instructions for other branches. Maybe they can use this info as well.

**Comment by eb193824-a002-4e53-a73b-be75738ef3f2** [comment]
Indeed, other branches can use this info as well.

**Comment by zooba** [comment]
New changeset fd0fa67464f75cebca67cd14d050476a0c73bd53 by Steve Dower (native-api) in branch 'master':
bpo-31691: Specify where to find build instructions for the Windows installer (bpo-4426)
https://github.com/python/cpython/commit/fd0fa67464f75cebca67cd14d050476a0c73bd53

**Comment by zooba** [comment]
New changeset c02307e9634583d3f2660e46b5200bf0b282695a by Steve Dower (native-api) in branch '2.7':
bpo-31691: Specify how to build installer in Windows (bpo-4430)
https://github.com/python/cpython/commit/c02307e9634583d3f2660e46b5200bf0b282695a

**Comment by zooba** [comment]
New changeset 0a6158ca392adfdfbeb7eb43d8d8109c02b00d23 by Steve Dower (Miss Islington (bot)) in branch '3.6':
bpo-31691: Specify where to find build instructions for the Windows installer (GH-4426) (bpo-4431)
https://github.com/python/cpython/commit/0a6158ca392adfdfbeb7eb43d8d8109c02b00d23

**Comment by zooba** [comment]
Thanks for the PR!

**Comment by zooba** [comment]
New changeset c69611990365ae2f2efffd191de0aba9ee98d95c by Steve Dower (native-api) in branch '3.6':
bpo-31691: Specify where to find installer build instructions for Windows (bpo-4427)
https://github.com/python/cpython/commit/c69611990365ae2f2efffd191de0aba9ee98d95c
