### ISSUE TITLE
random.choices does not work with negative weights

### ISSUE THREAD

**Issue by 33d57e24-160a-4e02-8f5d-24c11f3c93cf** [python/cpython#75870]
BPO | [31689](https://bugs.python.org/issue31689)
--- | :---
Nosy | @rhettinger, @mdickinson, @davecom, @tewhalen, @aldwinaldwin

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-10-05.04:11:29.427>
created_at = <Date 2017-10-04.12:53:19.075>
labels = ['invalid', '3.7', 'library']
title = 'random.choices does not work with negative weights'
updated_at = <Date 2019-07-19.06:59:20.132>
user = 'https://bugs.python.org/ariddell'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-19.06:59:20.132>
actor = 'aldwinaldwin'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-10-05.04:11:29.427>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-10-04.12:53:19.075>
creator = 'ariddell'
dependencies = []
files = []
hgrepos = []
issue_num = 31689
keywords = []
message_count = 7.0
messages = ['303683', '303685', '303697', '303738', '323235', '336933', '348145']
nosy_count = 6.0
nosy_names = ['rhettinger', 'mark.dickinson', 'ariddell', 'davecom', 'Ted Whalen', 'aldwinaldwin']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31689'
versions = ['Python 3.7']
```

</p></details>

**Comment by 33d57e24-160a-4e02-8f5d-24c11f3c93cf** [comment]
Code to reproduce problem:

```py
population = list(range(10))
weights = list(-1 * w for w in range(10))
[random.choices(population, weights) for _ in range(1000)]
```


will raise IndexError:

    358         bisect = \_bisect.bisect
    359         total = cum_weights[-1]
--\> 360         return [population[bisect(cum_weights, random() * total)] for i in range(k)]
    361 
    362 ## -------------------- real-valued distributions  \-------------------

IndexError: list index out of range

**Comment by mdickinson** [comment]
@ariddell: What behaviour did you want to see here?

It wouldn't have occurred to me to even try using `random.choices` with negative weights; forcing the weights to be nonnegative (with strictly positive sum) sounds like a natural restriction.

**Comment by 33d57e24-160a-4e02-8f5d-24c11f3c93cf** [comment]
Upon some reflection, I think raising a ValueError is the right thing to do. Negative weights don't have an obvious interpretation.

**Comment by rhettinger** [comment]
I'm content with the current exception.
