### ISSUE TITLE
[EASY] Running test_builtin twice fails on input tty tests

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75884]
BPO | [31703](https://bugs.python.org/issue31703)
--- | :---
Nosy | @vstinner, @serhiy-storchaka
Superseder | <li>bpo-13886: test_builtin.PtyTests fail on non-ASCII characters if the readline module is loaded</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-05.13:50:59.570>
created_at = <Date 2017-10-05.13:41:53.800>
labels = ['easy', '3.7', 'tests']
title = '[EASY] Running test_builtin twice fails on input tty tests'
updated_at = <Date 2017-10-05.13:51:22.249>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-05.13:51:22.249>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-05.13:50:59.570>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-10-05.13:41:53.800>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31703
keywords = ['easy']
message_count = 3.0
messages = ['303765', '303766', '303767']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '13886'
type = None
url = 'https://bugs.python.org/issue31703'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
haypo@selma$ ./python -m test test_builtin test_builtin -v

\======================================================================
FAIL: test_input_tty_non_ascii (test.test_builtin.PtyTests)
\----------------------------------------------------------------------
```diff
Traceback (most recent call last):
  File "/home/haypo/prog/python/master/Lib/test/test_builtin.py", line 1717, in test_input_tty_non_ascii
    self.check_input_tty("prompté", b"quux\xe9", "utf-8")
  File "/home/haypo/prog/python/master/Lib/test/test_builtin.py", line 1708, in check_input_tty
    self.assertEqual(input_result, expected)
AssertionError: 'quux' != 'quux\udce9'
- quux
+ quux\udce9
?     +
```



======================================================================
FAIL: test_input_tty_non_ascii_unicode_errors (test.test_builtin.PtyTests)
\----------------------------------------------------------------------
```diff
Traceback (most recent call last):
  File "/home/haypo/prog/python/master/Lib/test/test_builtin.py", line 1721, in test_input_tty_non_ascii_unicode_errors
    self.check_input_tty("prompté", b"quux\xe9", "ascii")
  File "/home/haypo/prog/python/master/Lib/test/test_builtin.py", line 1708, in check_input_tty
    self.assertEqual(input_result, expected)
AssertionError: 'quux' != 'quux\udce9'
- quux
+ quux\udce9
?     +
```

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-13886 (and several other issues).

Why do you think that this issue is easy?

**Comment by vstinner** [comment]
> Why do you think that this issue is easy?

I'm not sure that it's easy :-)
