### ISSUE TITLE
one-argument version for Generator.typing

### ISSUE THREAD

**Issue by b485b51b-d27f-423a-8035-c9ad55e98281** [python/cpython#75881]
BPO | [31700](https://bugs.python.org/issue31700)
--- | :---
Nosy | @srittau, @ilevkivskyi, @zeth

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-02.22:56:04.702>
created_at = <Date 2017-10-05.08:35:17.837>
labels = ['3.7', 'invalid']
title = 'one-argument version for Generator.typing'
updated_at = <Date 2021-12-01.01:34:39.694>
user = 'https://github.com/srittau'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-01.01:34:39.694>
actor = 'zeth'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-02.22:56:04.702>
closer = 'levkivskyi'
components = []
creation = <Date 2017-10-05.08:35:17.837>
creator = 'srittau'
dependencies = []
files = []
hgrepos = []
issue_num = 31700
keywords = []
message_count = 5.0
messages = ['303748', '303839', '305456', '305459', '407421']
nosy_count = 3.0
nosy_names = ['srittau', 'levkivskyi', 'zeth']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31700'
versions = ['Python 3.7']
```

</p></details>

**Comment by b485b51b-d27f-423a-8035-c9ad55e98281** [comment]
Currently typing.Generator requires three arguments: Generator[YieldType, SendType, ReturnType].

At least for me, passing values to a generator is a very rare case. I suggest to allow only one argument to be passed to Generator: Generator[YieldType], where the other arguments default to None. This makes the common case more readable and is less error-prone. (I always forget the second and third argument, since that use case is so uncommon for me.)

**Comment by ilevkivskyi** [comment]
You can use Iterator type, for example this works in mypy (didn't test in other type checkers):

```py
  def f() -> Iterator[int]:
      yield 42
```


In case you want annotate something specifically as Generator[int, None, None] (for example to use its .close() method), then you can create a generic alias:

```py
  T = TypeVar('T')
  Gen = Generator[T, None, None]

  def f() -> Gen[int]:
      ...
```


this is supported by mypy as well.

**Comment by ilevkivskyi** [comment]
Since there is no response for few weeks I assume this works for you.

**Comment by b485b51b-d27f-423a-8035-c9ad55e98281** [comment]
Sorry for not responding, but I didn't know what I could have added that I didn't already say in the opening post. Of course, you can use workaround like using the three-argument version or creating aliases. Using Iterator is of course not a real solution for the general case.

I still believe that Generator should be usable with just one argument or typing should provide such an alias.
