### ISSUE TITLE
Improve re documentation

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75895]
BPO | [31714](https://bugs.python.org/issue31714)
--- | :---
Nosy | @warsaw, @akuchling, @gpshead, @ezio-melotti, @serhiy-storchaka, @bricsuc, @Cryvate
PRs | <li>python/cpython#3907</li><li>python/cpython#3994</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-14.09:26:57.790>
created_at = <Date 2017-10-06.14:22:12.410>
labels = ['expert-regex', 'type-feature', '3.7', 'docs']
title = 'Improve re documentation'
updated_at = <Date 2017-10-14.09:26:57.789>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-14.09:26:57.789>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-14.09:26:57.790>
closer = 'serhiy.storchaka'
components = ['Documentation', 'Regular Expressions']
creation = <Date 2017-10-06.14:22:12.410>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31714
keywords = ['patch']
message_count = 7.0
messages = ['303822', '303825', '303826', '303829', '303833', '304387', '304390']
nosy_count = 9.0
nosy_names = ['barry', 'akuchling', 'gregory.p.smith', 'ezio.melotti', 'mrabarnett', 'docs@python', 'serhiy.storchaka', 'Brian Ward', 'cryvate']
pr_nums = ['3907', '3994']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31714'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The proposed PR improves the documentation of re module and Regular Expression HOWTO.

* Clarify the effect of the LOCALE flag.

* Remove outdated statements.

* Add an example of escaping a replacement string.

* Add or correct some references.

* Improve and fix a formatting.

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
I was looking at your changes and got myself in a muddle. What is you rational for when you use ``[character or string]`` versus ``'[character or string]``? You seem to be creating consistency there, but I cannot quite see the rules you are aiming for!

**Comment by ezio-melotti** [comment]
ISTM that ``x`` is used when x is a regex or regex metachar, whereas ``'x'`` is used when 'x' is a string.  I find this distinction reasonable.

**Comment by serhiy-storchaka** [comment]
It is explained in the documentation:

"""
(In the rest of this
section, we'll write RE's in ``this special style``, usually without quotes, and
strings to be matched ``'in single quotes'``.)
"""

**Comment by 9562d477-4c17-4346-9b04-e98ab6200789** [comment]
In re.rst, the instances of "Correcsponds the" should be "Corresponds to the" and "Doesn't have correcsponding inline flag" should be "No corresponding inline flag."

**Comment by serhiy-storchaka** [comment]
New changeset cd195e2a7ac5c9b2574d5462752b7939641de4a9 by Serhiy Storchaka in branch 'master':
bpo-31714: Improved regular expression documentation. (bpo-3907)
https://github.com/python/cpython/commit/cd195e2a7ac5c9b2574d5462752b7939641de4a9

**Comment by serhiy-storchaka** [comment]
New changeset 69ed5b61e7d2bdaf2dc6684061f737adc24a96ae by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31714: Improved regular expression documentation. (GH-3907). (bpo-3994)
https://github.com/python/cpython/commit/69ed5b61e7d2bdaf2dc6684061f737adc24a96ae
