### ISSUE TITLE
setup.py: _ctypes won't get built when system ffi is only in $PREFIX

### ISSUE THREAD

**Issue by 1f4f0d85-e63f-4322-8b54-768e60e1d01b** [python/cpython#75891]
BPO | [31710](https://bugs.python.org/issue31710)
--- | :---
Nosy | @doko42, @ned-deily, @pmp-p, @zware, @moreati, @r-bit-rry, @pbhege
Superseder | <li>bpo-14527: How to link with a non-system libffi?</li>
Files | <li>[build.log](https://bugs.python.org/file47728/build.log "Uploaded as text/x-log at 2018-08-02.13:51:46 by @r-bit-rry")</li><li>[config.log](https://bugs.python.org/file47729/config.log "Uploaded as text/x-log at 2018-08-02.14:49:24 by @r-bit-rry")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-05-08.03:21:22.178>
created_at = <Date 2017-10-06.05:14:44.023>
labels = ['build', '3.7']
title = "setup.py: _ctypes won't get built when system ffi is only in $PREFIX"
updated_at = <Date 2020-05-08.03:21:22.176>
user = 'https://github.com/pmp-p'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-08.03:21:22.176>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2020-05-08.03:21:22.178>
closer = 'ned.deily'
components = ['Build', 'Cross-Build']
creation = <Date 2017-10-06.05:14:44.023>
creator = 'pmpp'
dependencies = []
files = ['47728', '47729']
hgrepos = []
issue_num = 31710
keywords = []
message_count = 12.0
messages = ['303799', '303801', '322948', '322952', '322955', '322961', '322965', '322967', '323425', '333383', '348109', '368414']
nosy_count = 9.0
nosy_names = ['doko', 'ned.deily', 'pmpp', 'zach.ware', 'Alex.Willmer', 'rbelio', 'mhpruitt', 'Ivan Levchenko', 'Paul Hege']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '14527'
type = 'compile error'
url = 'https://bugs.python.org/issue31710'
versions = ['Python 3.7']
```

</p></details>

**Comment by 1f4f0d85-e63f-4322-8b54-768e60e1d01b** [comment]
--with-system-ffi is mandatory for linux build but no way is provided ( eg --with-ffi-includes= --with-ffi-libs= ) so setup.py can detect libffi already built in $PREFIX and $EPREFIX/lib.

even if cflags/ldflags are ok , \_ctypes build will be skipped with reason:
INFO: Could not locate ffi libs and/or headers

test condition: crystax-ndk toward android-19 on ubuntu xenial 32 bits

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
> even if cflags/ldflags are ok 

Might be this. setup.py doesn't use -I flags in $CFLAGS. It looks into $CPPFLAGS only.

**Comment by MhmRhm** [comment]
After compiling libffi from source with the following commands:
```
rm /usr/lib64/libffi.*
./configure --prefix=/usr --disable-static --libdir=/usr/lib --disable-multi-os-directory --with-gcc-arch=native
```

I was able to build _ctypes.

The mentioned command installs the binaries at /usr/lib/ instead of /usr/lib64/
