### ISSUE TITLE
some methods of uninitialized io.IncrementalNewlineDecoder objects raise SystemError

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75899]
BPO | [31718](https://bugs.python.org/issue31718)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka, @orenmn, @csabella, @ZackerySpytz
PRs | <li>python/cpython#3913</li><li>python/cpython#18640</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-06.18:09:48.760>
labels = ['type-bug', '3.8', '3.9', 'expert-IO']
title = 'some methods of uninitialized io.IncrementalNewlineDecoder objects raise SystemError'
updated_at = <Date 2020-02-24.06:50:50.454>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-24.06:50:50.454>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-10-06.18:09:48.760>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31718
keywords = ['patch']
message_count = 6.0
messages = ['303842', '303847', '303853', '303860', '303874', '361625']
nosy_count = 6.0
nosy_names = ['benjamin.peterson', 'stutzbach', 'serhiy.storchaka', 'Oren Milman', 'cheryl.sabella', 'ZackerySpytz']
pr_nums = ['3913', '18640']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31718'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Given an uninitialized IncrementalNewlineDecoder:
uninitialized = io.IncrementalNewlineDecoder.\_\_new__(io.IncrementalNewlineDecoder)

each of the following calls would raise a SystemError ('null argument to
internal routine'):
uninitialized.getstate()
uninitialized.setstate((b'foo', 0))
uninitialized.reset()

In contrast, the following call would raise a ValueError
('IncrementalNewlineDecoder.\_\_init__ not called'):
uninitialized.decode(b'bar')

ISTM that getstate(), setstate(), and reset() should have the same behavior as
decode(). (Though i think that including the actual type name in the error
message would be better, as it could be a subclass of IncrementalNewlineDecoder).

**Comment by serhiy-storchaka** [comment]
Is IncrementalNewlineDecoder subclassable?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Yes, although i don't know if there are usecases for that.

**Comment by serhiy-storchaka** [comment]
There is other issues with IncrementalNewlineDecoder.\_\_init__ -- it leaks references when called repeatedly.

The simplest solution of both issues will be moving the initialization to the new method. But this class looks designed for subclassing, and this can break subclasses that change arguments before passing them to the superclass' constructor.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
With regard to refleaks in \_\_init__() methods, i started looking for similar refleaks
in the codebase, and hope to open an issue to fix them soon.
