### ISSUE TITLE
msilib.MSIError is spelled MsiError in documentation

### ISSUE THREAD

**Issue by ddf74a51-5f28-44b3-89e3-5080a0864212** [python/cpython#75901]
BPO | [31720](https://bugs.python.org/issue31720)
--- | :---
Nosy | @uranusjr, @Mariatta
PRs | <li>python/cpython#3914</li><li>python/cpython#3916</li><li>python/cpython#3917</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-07.16:01:25.605>
created_at = <Date 2017-10-07.13:39:30.328>
labels = ['3.7', 'docs']
title = 'msilib.MSIError is spelled MsiError in documentation'
updated_at = <Date 2017-10-07.16:01:25.603>
user = 'https://github.com/uranusjr'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-07.16:01:25.603>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-07.16:01:25.605>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-10-07.13:39:30.328>
creator = 'uranusjr'
dependencies = []
files = []
hgrepos = []
issue_num = 31720
keywords = ['patch']
message_count = 3.0
messages = ['303877', '303886', '303887']
nosy_count = 3.0
nosy_names = ['docs@python', 'uranusjr', 'Mariatta']
pr_nums = ['3914', '3916', '3917']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31720'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ddf74a51-5f28-44b3-89e3-5080a0864212** [comment]
The title describes it all.

**Comment by Mariatta** [comment]
New changeset 5f396dba1d11356ab18e3bec130596197e741a64 by Mariatta (Miss Islington (bot)) in branch '3.6':
bpo-31720: msilib documentation, change MsiError into MSIError (GH-3914) (GH-3917)
https://github.com/python/cpython/commit/5f396dba1d11356ab18e3bec130596197e741a64

**Comment by Mariatta** [comment]
Thanks!
