### ISSUE TITLE
[2.7] test_regrtest.test_crashed() fails on s390x

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75900]
BPO | [31719](https://bugs.python.org/issue31719)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @stratakis, @irushchyshyn
PRs | <li>python/cpython#3912</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-09.07:56:03.866>
created_at = <Date 2017-10-06.20:35:01.179>
labels = ['tests']
title = '[2.7] test_regrtest.test_crashed() fails on s390x'
updated_at = <Date 2017-10-10.13:14:48.633>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-10.13:14:48.633>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-09.07:56:03.866>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-06.20:35:01.179>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31719
keywords = ['patch']
message_count = 7.0
messages = ['303854', '303926', '303930', '303931', '303932', '303994', '304038']
nosy_count = 4.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'cstratak', 'ishcherb']
pr_nums = ['3912']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31719'
versions = ['Python 2.7']
```

</p></details>

**Comment by vstinner** [comment]
On the s390x architecture, the test_regrtest.test_crashed() fails because Python doesn't crash.

test.support.\_crash_python() calls ctypes.string_at(0) to crash Python. In debug mode, ctypes.string_at(0) fails with an assertion error and the process is killed with the SIGABRT signal. In release mode, ctypes.string_at(0) returns an empty string but doesn't crash.

Attached PR adds a new \_testcapi.\_read_null() function which does crash in a reliable way on s390x and x86 :-) The function uses the C "volatile" keyword to prevent compiler optimizations. I copied the code from my faulthandler.\_read_null() function in the master branch which was battle tested. It does crash on all platforms... except of AIX.

**Comment by e19bb02b-4d86-4b52-b95f-8ba3ba41da14** [comment]
I have run a build with the patch applied, and can confirm that the tests  pass on s390x.
Full build log can be viewed here: https://kojipkgs.fedoraproject.org//work/tasks/9473/22339473/build.log

**Comment by vstinner** [comment]
New changeset cc4b6f1c6210460c0645b1df508e114e16805784 by Victor Stinner in branch '2.7':
bpo-31719: Fix test_regrtest.test_crashed() on s390x (bpo-3912)
https://github.com/python/cpython/commit/cc4b6f1c6210460c0645b1df508e114e16805784

**Comment by vstinner** [comment]
For the records, test_regrtest.test_crashed() uses faulthandler.\_sigsegv() in the master branch. This function calls raise(SIGSEGV) directly, rather than trying to read from NULL (address 0).

**Comment by vstinner** [comment]
The main issue with reading from NULL is that it may not crash on AIX.  But I checked: test_regrtest passed on our AIX buildbot.

**Comment by serhiy-storchaka** [comment]
Why not use just abort() or Py_FatalError()?

```sh
$ ./python -c 'import ctypes; ctypes.CDLL("libc.so.6").abort()'
Aborted (core dumped)

$ ./python -c 'import ctypes; ctypes.pythonapi.Py_FatalError(b"boom!")'
Fatal Python error: boom!
```


Current thread 0x00007f26805c7580 (most recent call first):
  File "\<string\>", line 1 in \<module\>
Aborted (core dumped)

**Comment by vstinner** [comment]
> Why not use just abort() or Py_FatalError()?

I try to test how a real program crash, like a real invalid memory read. Maybe it doesn't matter much here.
