### ISSUE TITLE
refleaks in zipimport when calling zipimporter.__init__() more than once

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75904]
BPO | [31723](https://bugs.python.org/issue31723)
--- | :---
Nosy | @vstinner, @orenmn
PRs | <li>python/cpython#3919</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-09.15:08:00.557>
created_at = <Date 2017-10-07.15:27:27.337>
labels = ['extension-modules', '3.7', 'performance']
title = 'refleaks in zipimport when calling zipimporter.__init__() more than once'
updated_at = <Date 2017-10-09.15:14:07.350>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-09.15:14:07.350>
actor = 'Oren Milman'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-09.15:08:00.557>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-10-07.15:27:27.337>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31723
keywords = ['patch']
message_count = 6.0
messages = ['303883', '303969', '303970', '303971', '303972', '303973']
nosy_count = 2.0
nosy_names = ['vstinner', 'Oren Milman']
pr_nums = ['3919']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31723'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes refleaks:
import zipimport
zi = zipimport.zipimporter.\_\_new__(zipimport.zipimporter)
zi.\_\_init__('bar.zip')
zi.\_\_init__('bar.zip')
zi.\_\_init__('bar.zip\\\\foo')

This is because zipimport_zipimporter___init___impl() (in [Modules/zipimport.c](https://github.com/python/cpython/blob/main/Modules/zipimport.c))
doesn't decref (if needed) before assigning to `self->files`, `self->archive`
and `self->prefix`.

I would open a PR to fix this soon.

Should i add a test to test_zipimport?
If yes, could you point out some similar refcount test to help me write this
test?

**Comment by vstinner** [comment]
New changeset c0cabc23bbe474d542ff8a4f1243f4ec3cce5549 by Victor Stinner (Oren Milman) in branch 'master':
bpo-31723: Fix refleaks when zipimporter.\_\_init__() is called more than once (GH-3919)
https://github.com/python/cpython/commit/c0cabc23bbe474d542ff8a4f1243f4ec3cce5549

**Comment by vstinner** [comment]
> The following code causes refleaks:

I'm curious, how did you find this code? Are you using a code generator coupled with a tool to track for reference leaks?

**Comment by vstinner** [comment]
I merged your PR, thanks! As I wrote on the PR:

I don't think that a NEWS entry is needed, since you are not supposed to call \_\_init__() multiple times.

I don't think that it's worth it to backport the fix to Python 2.7 and 3.6. So I close the issue.

**Comment by vstinner** [comment]
> I'm curious, how did you find this code? Are you using a code generator coupled with a tool to track for reference leaks?

Oh, I think that the issue is related to bpo-31718.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Yes, i am going manually over the code to find similar stuff to bpo-31718,
and i afraid i found quite a few, and still working on it..
