### ISSUE TITLE
Turtle/tkinter: NameError crashes ipython with "Tcl_AsyncDelete: async handler deleted by the wrong thread"

### ISSUE THREAD

**Issue by ba7e70d0-a2ff-4119-bcff-66158db9ce3c** [python/cpython#75906]
BPO | [31725](https://bugs.python.org/issue31725)
--- | :---
Nosy | @serhiy-storchaka, @willingc

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-16.15:53:08.817>
created_at = <Date 2017-10-08.07:16:44.873>
labels = ['invalid', 'expert-tkinter']
title = 'Turtle/tkinter: NameError crashes ipython with "Tcl_AsyncDelete: async handler deleted by the wrong thread"'
updated_at = <Date 2018-06-16.18:24:39.855>
user = 'https://bugs.python.org/RickJPelleg'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-16.18:24:39.855>
actor = 'Rick J. Pelleg'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-16.15:53:08.817>
closer = 'willingc'
components = ['Tkinter']
creation = <Date 2017-10-08.07:16:44.873>
creator = 'Rick J. Pelleg'
dependencies = []
files = []
hgrepos = []
issue_num = 31725
keywords = []
message_count = 7.0
messages = ['303898', '303906', '303910', '304395', '304397', '319756', '319772']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'willingc', 'Rick J. Pelleg']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31725'
versions = ['Python 3.6']
```

</p></details>

**Comment by ba7e70d0-a2ff-4119-bcff-66158db9ce3c** [comment]
On Windows 10 Education, ran:
ipython
Python 3.6.3 (v3.6.3:2c5fed8, Oct  3 2017, 17:26:49) [MSC v.1900 32 bit (Intel)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.2.1 -- An enhanced Interactive Python. Type '?' for help.
\----
After "from turtle import \*" and several simple turtle commands:

In [36]: fill()
\---------------------------------------------------------------------------
```pytb
NameError                                 Traceback (most recent call last)
<ipython-input-36-4268fc8160e4> in <module>()
----> 1 fill()
```


NameError: name 'fill' is not defined

```pytb
Tcl_AsyncDelete: async handler deleted by the wrong thread
Exception ignored in: <bound method Image.__del__ of <tkinter.PhotoImage object at 0x0465AEB0>>
Traceback (most recent call last):
  File "d:\users\yuval\appdata\local\programs\python\python36-32\lib\tkinter\__init__.py", line 3501, in __del__
    self.tk.call('image', 'delete', self.name)
```

**Comment by serhiy-storchaka** [comment]
Can you reproduce the issue without IPython?

**Comment by ba7e70d0-a2ff-4119-bcff-66158db9ce3c** [comment]
Mmm... right now I cannot reproduce at all, both in iPython and in python.
Will continue to try.

**Comment by ba7e70d0-a2ff-4119-bcff-66158db9ce3c** [comment]
Sorry, all reproduction attempts failed, both in plain Python and in
iPython.
I guess you can close this for now.

**Comment by ba7e70d0-a2ff-4119-bcff-66158db9ce3c** [comment]
Just one more issue: since it happened before I found out that the "turtle"
package already has the pre-defined short version of commands, such as
"fd()", "lt()", etc., the crashed session included four function
definitions, for "fd()", "bk()", "lt()" and "rt()", in the form of:

```py
def fd(val):

    forward(val)
```
