### ISSUE TITLE
test_xmlrpc_net should use something other than buildbot.python.org

### ISSUE THREAD

**Issue by zware** [python/cpython#75905]
BPO | [31724](https://bugs.python.org/issue31724)
--- | :---
Nosy | @loewis, @zware, @iritkatriel
PRs | <li>python/cpython#3921</li><li>python/cpython#3922</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-08.05:44:01.243>
labels = ['tests', '3.9', '3.10', '3.11']
title = 'test_xmlrpc_net should use something other than buildbot.python.org'
updated_at = <Date 2021-08-01.21:47:55.945>
user = 'https://github.com/zware'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-01.21:47:55.945>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2017-10-08.05:44:01.243>
creator = 'zach.ware'
dependencies = []
files = []
hgrepos = []
issue_num = 31724
keywords = []
message_count = 5.0
messages = ['303894', '303895', '303896', '303897', '398721']
nosy_count = 3.0
nosy_names = ['loewis', 'zach.ware', 'iritkatriel']
pr_nums = ['3921', '3922']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31724'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-105796

**Comment by zware** [comment]
With the upgrade to buildbot 0.9, the xmlrpc interface to buildbot.python.org is removed, causing test_xmlrpc to fail.  The test should hit a different host, possibly on pythontest.net?

**Comment by zware** [comment]
New changeset 73ffd3f2036179ed54591ef0455e5ba5694ae5bd by Zachary Ware in branch 'master':
bpo-31724: Skip test_xmlrpc_net (GH-3921)
https://github.com/python/cpython/commit/73ffd3f2036179ed54591ef0455e5ba5694ae5bd

**Comment by zware** [comment]
This is currently mitigated by some nasty hacks on the buildbot.python.org server to avoid breaking tests on every released version of Python 3, but this still needs to change.  The test is skipped in master and (soon) 3.6 to minimize the damage when the hacks on buildbot.p.o break.

**Comment by zware** [comment]
New changeset d13a4e50679c0861971cfae2bb226f35b8bf5142 by Zachary Ware (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31724: Skip test_xmlrpc_net (GH-3922)
https://github.com/python/cpython/commit/d13a4e50679c0861971cfae2bb226f35b8bf5142

**Comment by vstinner** [comment]
I proposed PR #105796 to remove the test, so no volunteer proposed a change in 6 years to use a different public XML-RPC server. The local test_xmlrpc test is enough.

**Comment by vstinner** [comment]
The test was removed by https://github.com/python/cpython/commit/820febc535cd9548b11c01c3c6d572b442f20c35
