### ISSUE TITLE
PEP 485 tiny typo

### ISSUE THREAD

**Issue by 97905533-7f62-4694-afbd-d1e9aaccfa26** [python/cpython#75917]
BPO | [31736](https://bugs.python.org/issue31736)
--- | :---
Nosy | @berkerpeksag, @bbolker

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-10.05:28:52.377>
created_at = <Date 2017-10-09.17:11:10.754>
labels = ['type-bug']
title = 'PEP 485 tiny typo'
updated_at = <Date 2017-10-10.05:28:52.350>
user = 'https://github.com/bbolker'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-10.05:28:52.350>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-10.05:28:52.377>
closer = 'berker.peksag'
components = []
creation = <Date 2017-10-09.17:11:10.754>
creator = 'bbolker'
dependencies = []
files = []
hgrepos = []
issue_num = 31736
keywords = []
message_count = 2.0
messages = ['303987', '304012']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'bbolker']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31736'
versions = []
```

</p></details>

**Comment by 97905533-7f62-4694-afbd-d1e9aaccfa26** [comment]
In two places in https://www.python.org/dev/peps/pep-0485/ floating point numbers are incorrectly formatted: 1-e8 and 1-e9 rather than 1e-8 and 1e-9 ("absolute tolerance default", para. 3 and "relative tolerance default", para. 1)

**Comment by berkerpeksag** [comment]
Thank you for the report. Fixed in https://github.com/python/peps/commit/070dc7e037e5f66e4e17b661641503815a8bbe05

(By the way, you can report issues like this at https://github.com/python/peps/issues or send a PR directly.)
