### ISSUE TITLE
list unhashable, can not be use as key to dict

### ISSUE THREAD

**Issue by 3f34ef4e-c5a1-463e-9629-42c801fbb439** [python/cpython#75911]
BPO | [31730](https://bugs.python.org/issue31730)
--- | :---
Nosy | @ned-deily, @gene@nlc.co.nz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-08.21:02:03.083>
created_at = <Date 2017-10-08.20:54:49.535>
labels = ['interpreter-core', 'type-feature', 'invalid']
title = 'list unhashable, can not be use as key to dict'
updated_at = <Date 2017-10-08.21:02:03.081>
user = 'https://github.com/genenlcconz'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-08.21:02:03.081>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-08.21:02:03.083>
closer = 'ned.deily'
components = ['Interpreter Core']
creation = <Date 2017-10-08.20:54:49.535>
creator = 'gene@nlc.co.nz'
dependencies = []
files = []
hgrepos = []
issue_num = 31730
keywords = []
message_count = 2.0
messages = ['303919', '303920']
nosy_count = 2.0
nosy_names = ['ned.deily', 'gene@nlc.co.nz']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31730'
versions = ['Python 2.7']
```

</p></details>

**Comment by 3f34ef4e-c5a1-463e-9629-42c801fbb439** [comment]
A list can no be used as the key to a dict, apparently because it is "unhashable": TypeError: unhashable type: 'list'.

The code must exist to hash object like this a tuple is hashable and can be constructed from a list.

**Comment by ned-deily** [comment]
As documented, a dict key must be hashable and, because lists are not immutable, they are not hashable and thus can't be used as keys.  See the Python Glossary for more info.  https://docs.python.org/2/glossary.html
