### ISSUE TITLE
Lib/site.py: method `abs_paths` is not documented

### ISSUE THREAD

**Issue by 4e12238e-f4c0-4728-8475-4718fcb426dd** [python/cpython#75919]
BPO | [31738](https://bugs.python.org/issue31738)
--- | :---
Nosy | @merwok, @JulienPalard, @lielfr

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.17:53:58.545>
created_at = <Date 2017-10-09.18:06:22.227>
labels = ['invalid', '3.7', 'tests']
title = 'Lib/site.py: method `abs_paths` is not documented'
updated_at = <Date 2017-10-16.17:53:58.508>
user = 'https://github.com/lielfr'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.17:53:58.508>
actor = 'eric.araujo'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-16.17:53:58.545>
closer = 'eric.araujo'
components = ['Tests']
creation = <Date 2017-10-09.18:06:22.227>
creator = 'lielfr'
dependencies = []
files = []
hgrepos = []
issue_num = 31738
keywords = []
message_count = 3.0
messages = ['303998', '304066', '304478']
nosy_count = 3.0
nosy_names = ['eric.araujo', 'mdk', 'lielfr']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31738'
versions = ['Python 3.7']
```

</p></details>

**Comment by JulienPalard** [comment]
Hi, thanks for reporting.

This method has been renamed in https://github.com/python/cpython/commit/28a691b7fdde1b8abafa4c4a5025e6bfa44f48b9 and is only used in [Lib/site.py](https://github.com/python/cpython/blob/main/Lib/site.py) (currently in main()).

The function has a docstring, so:

  Help on function abs_paths in module site:

```py
  abs_paths()
      Set all module __file__ and __cached__ attributes to an absolute path
```



Is this function usefull for you outside of site.py?

**Comment by 4e12238e-f4c0-4728-8475-4718fcb426dd** [comment]
No, I've just tried to find something to work on as a first contribution.

**Comment by merwok** [comment]
Thanks for wanting to help!  This function is not meant to be public, which explains why it’s not documented.  Please see the [devguide](https://devguide.python.org) and the core-mentorship mailing list to find ways to contribute!
