### ISSUE TITLE
Proportional Width Font on Generated Python Docs PDFs and in mobile browser

### ISSUE THREAD

**Issue by e8cb2942-cd71-46f0-832e-e3357885e15a** [python/cpython#75924]
BPO | [31743](https://bugs.python.org/issue31743)
--- | :---
Nosy | @ezio-melotti, @merwok, @willingc, @JulienPalard, @synthmeat
Files | <li>[Screenshot 2017-10-10 12.41.34.png](https://bugs.python.org/file47203/Screenshot%202017-10-10%2012.41.34.png "Uploaded as image/png at 2017-10-10.11:00:17 by @synthmeat")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-10.11:00:17.426>
labels = ['3.7', '3.8', '3.9', '3.10', 'type-feature', 'docs']
title = 'Proportional Width Font on Generated Python Docs PDFs and in mobile browser'
updated_at = <Date 2021-06-18.17:38:08.865>
user = 'https://github.com/synthmeat'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-18.17:38:08.865>
actor = 'paul.dubois'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2017-10-10.11:00:17.426>
creator = 'synthmeat'
dependencies = []
files = ['47203']
hgrepos = []
issue_num = 31743
keywords = []
message_count = 2.0
messages = ['304024', '396076']
nosy_count = 7.0
nosy_names = ['ezio.melotti', 'eric.araujo', 'docs@python', 'willingc', 'mdk', 'synthmeat', 'paul.dubois']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31743'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by e8cb2942-cd71-46f0-832e-e3357885e15a** [comment]
Fonts in the generated documentation PDFs, for all Python versions, are proportional width in code blocks, unlike in HTML version, where they are fixed-width.

Example https://docs.python.org/2.7/archives/python-2.7.14-docs-pdf-a4.zip

**Comment by iritkatriel** [comment]
CC @CAM-Gerlach

**Comment by arhadthedev** [comment]
Seems to be fixed:

![image](https://user-images.githubusercontent.com/4881073/234222804-80b071de-cd67-43ab-9deb-1bd45b92b5d5.png)

**Comment by CAM-Gerlach** [comment]
I cannot reproduce the issue either viewing the downloaded PDFs from a variety of old and new Python versions (back to 3.6, 2.7 and the indicated 3.7), as well as those same and even older versions on an Android device (Pixel 6a), including on the pages mentioned (heapq, etc). If it still exists, it seems likely to be an issue with the fonts/viewers on the specific devices in question, so unclear what we can do about it even if so. Closing this; if others can repro on a recent version with specific information as to the device, browser/PDF viewer, OS, document in question, etc. feel free to mention that. Thanks!
