### ISSUE TITLE
refleaks when calling sqlite3.Connection.__init__() more than once

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75921]
BPO | [31740](https://bugs.python.org/issue31740)
--- | :---
Nosy | @vstinner, @orenmn
PRs | <li>python/cpython#3944</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-10.19:35:17.393>
created_at = <Date 2017-10-09.20:32:17.747>
labels = ['extension-modules', '3.7', 'performance']
title = 'refleaks when calling sqlite3.Connection.__init__() more than once'
updated_at = <Date 2017-10-10.19:35:17.391>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-10.19:35:17.391>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-10.19:35:17.393>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-10-09.20:32:17.747>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31740
keywords = ['patch']
message_count = 5.0
messages = ['303997', '303999', '304048', '304071', '304072']
nosy_count = 2.0
nosy_names = ['vstinner', 'Oren Milman']
pr_nums = ['3944']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31740'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code causes refleaks:
import sqlite3
connection = sqlite3.Connection.\_\_new__(sqlite3.Connection)
connection.\_\_init__('foo')
connection.\_\_init__('foo')

This is because pysqlite_connection_init() (in [Modules/_sqlite/connection.c](https://github.com/python/cpython/blob/main/Modules/_sqlite/connection.c))
doesn't decref (if needed) before assigning to various fields of `self`.

I would open a PR to fix this soon.

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
Ah, here also there are crashes when calling methods of uninitialized connection objects.

Should i fix this as part of this issue, or open another one?

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
(opened bpo-31746 for the crashes i mentioned)

**Comment by vstinner** [comment]
New changeset 93c5a5df8ea118f6e4a153a7c8cccd65a5ff8bff by Victor Stinner (Oren Milman) in branch 'master':
bpo-31740: Prevent refleaks when sqlite3.Connection.\_\_init__() is called more than once (GH-3944)
https://github.com/python/cpython/commit/93c5a5df8ea118f6e4a153a7c8cccd65a5ff8bff

**Comment by vstinner** [comment]
Oren Milman: thanks for your contribution! I merged your PR.

I don't consider that such corner case requires to backport the change to Python 2.7 and 3.6.
