### ISSUE TITLE
subprocess.run should alias universal_newlines to text

### ISSUE THREAD

**Issue by 2856216f-7512-4f2e-9675-c165ab4fdb85** [python/cpython#75937]
BPO | [31756](https://bugs.python.org/issue31756)
--- | :---
Nosy | @warsaw, @gpshead, @ncoghlan, @andyclegg, @zooba
PRs | <li>python/cpython#4049</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2017-10-23.02:03:49.650>
created_at = <Date 2017-10-11.10:16:51.865>
labels = ['3.7', 'type-feature', 'library']
title = 'subprocess.run should alias universal_newlines to text'
updated_at = <Date 2017-10-23.02:03:49.649>
user = 'https://github.com/andyclegg'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-23.02:03:49.649>
actor = 'gregory.p.smith'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2017-10-23.02:03:49.650>
closer = 'gregory.p.smith'
components = ['Library (Lib)']
creation = <Date 2017-10-11.10:16:51.865>
creator = 'andrewclegg'
dependencies = []
files = []
hgrepos = []
issue_num = 31756
keywords = ['patch']
message_count = 6.0
messages = ['304125', '304149', '304150', '304158', '304198', '304774']
nosy_count = 5.0
nosy_names = ['barry', 'gregory.p.smith', 'ncoghlan', 'andrewclegg', 'steve.dower']
pr_nums = ['4049']
priority = 'normal'
resolution = 'fixed'
stage = 'commit review'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31756'
versions = ['Python 3.7']
```

</p></details>

**Comment by 2856216f-7512-4f2e-9675-c165ab4fdb85** [comment]
Following on from https://bugs.python.org/issue6135

The subprocess module by default returns bytes from subprocess calls. It has a text mode, but this can only be accessed by slightly tangential arguments (setting encoding, errors or universal_newlines).

ncoghlan notes in [msg304118](https://bugs.python.org/msg304118) that this is a similar situation to the binary/text mode settings for open(). From the docs " In text mode, if encoding is not specified the encoding used is platform dependent: locale.getpreferredencoding(False) is called to get the current locale encoding"

The universal_newlines argument now effectively just turns on the text mode, however this is not an intuitively and obviously discoverable. So to improve usability, and to mirror the file opening behaviour, subprocess calls should be \*explicitly* dual mode (binary/text), and have an explicitly named argument to control this.

My enhancement suggestion is as follows:
* Add a text=True/False argument that is an alias of universal_newlines, to improve the API.
* Clearly document that this implies that the encoding will be guessed, and that an explicit encoding can be given if the guess is wrong

For completeness, the following changes could also be made, although these may be controversial
* Remove/deprecate the universal_newlines argument
* Revert the default mode to text (as in Python 2.7), and have a binary=True argument instead

**Comment by zooba** [comment]
Really, this is just an alias for universal_newlines in Popen.\_\_init__. So we add the parameter and:

\+    if text:
\+        universal_newlines = True
     self.universal_newlines = universal_newlines

And 99% of the change is making it clear in the docs why we have two arguments with the same meaning.

**Comment by zooba** [comment]
> just an alias

Which I recognise is in the bug title. My point is that the enhancement itself is less relevant than the rationale and the documentation. 

Without a doc patch, there's really nothing to discuss here other than duplicating APIs (which is probably justified, even though it looks like a wart).

**Comment by 2856216f-7512-4f2e-9675-c165ab4fdb85** [comment]
OK great, I'll get working on a patch.

**Comment by ncoghlan** [comment]
As far as docs phrasing goes, it probably makes sense to frame it as "text" being the preferred argument name in 3.7+, with "universal_newlines" retained indefinitely as a compatibility preserving alias. After all, if that wasn't our intention, we wouldn't be adding the more straightforward alias in the first place.

As a new Py3-only argument, "text" can also be made keyword-only. (The Popen arg list is so long that most folks treat everything other than the first item as keyword-only anyway, but it doesn't hurt to ask the interpreter to enforce that)

**Comment by gpshead** [comment]
New changeset 7fed7bd8bb628f0f09c6011871a4ce68afb41b18 by Gregory P. Smith (andyclegg) in branch 'master':
bpo-31756: subprocess.run should alias universal_newlines to text (bpo-4049)
https://github.com/python/cpython/commit/7fed7bd8bb628f0f09c6011871a4ce68afb41b18
