### ISSUE TITLE
Assertion failure in timedelta() in case of bad __divmod__

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75933]
BPO | [31752](https://bugs.python.org/issue31752)
--- | :---
Nosy | @Yhg1s, @terryjreedy, @abalkin, @serhiy-storchaka, @orenmn, @mlouielu, @miss-islington
PRs | <li>python/cpython#3947</li><li>python/cpython#4086</li><li>python/cpython#4088</li><li>python/cpython#9958</li><li>python/cpython#10039</li><li>python/cpython#10040</li><li>python/cpython#10614</li><li>python/cpython#10615</li><li>python/cpython#10617</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-23.16:57:20.973>
created_at = <Date 2017-10-10.21:29:28.746>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'Assertion failure in timedelta() in case of bad __divmod__'
updated_at = <Date 2018-11-20.19:56:41.169>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-20.19:56:41.169>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-23.16:57:20.973>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-10-10.21:29:28.746>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31752
keywords = ['patch']
message_count = 12.0
messages = ['304083', '304131', '304351', '304751', '304808', '304810', '304822', '327990', '330143', '330146', '330148', '330151']
nosy_count = 7.0
nosy_names = ['twouters', 'terry.reedy', 'belopolsky', 'serhiy.storchaka', 'Oren Milman', 'louielu', 'miss-islington']
pr_nums = ['3947', '4086', '4088', '9958', '10039', '10040', '10614', '10615', '10617']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31752'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
The following code causes an assertion error in timedelta constructor.

```py
from datetime import timedelta

class BadInt(int):
    def __mul__(self, other):
        return Prod()

class Prod:
    def __radd__(self, other):
        return Sum()

class Sum:
    def __divmod__(self, other):
        return (0, -1)

timedelta(hours=BadInt(1))
```



Result:

python: /home/serhiy/py/cpython/Modules/_datetimemodule.c:1573: microseconds_to_delta_ex: Assertion \`0 \<= temp && temp \< 1000000' failed.
Aborted (core dumped)

**Comment by 9da18a29-a07d-4828-a801-24cc911246de** [comment]
I got a different result in latest commit: eeb5ffd54e5

```pytb
➜  cpython git:(master) ✗ ./python test.py
Traceback (most recent call last):
  File "test.py", line 15, in <module>
    timedelta(hours=BadInt(1))
SystemError: <class 'datetime.timedelta'> returned NULL without setting an error
```


Do I miss some configure, I'm using ./configure --with-debug

**Comment by terryjreedy** [comment]
On Win10, installed 3.5.4, 3.6.3, 3.7.1a1 all raise SystemError.
3.6 and 3.7 repository debug builds raise AssertionError and Windows crash box.  After the patch, a silent crash.

**Comment by serhiy-storchaka** [comment]
Unpatched Python should crash in debug build and can raise SystemError in release build.

I can't reproduce a crash on Windows after the patch.

**Comment by serhiy-storchaka** [comment]
New changeset 4ffd4653a7ec9c97775472276cf5e159e2366bb2 by Serhiy Storchaka in branch 'master':
bpo-31752: Fix possible crash in timedelta constructor called with custom integers. (bpo-3947)
https://github.com/python/cpython/commit/4ffd4653a7ec9c97775472276cf5e159e2366bb2

**Comment by serhiy-storchaka** [comment]
New changeset 6e45d7b90accbbdfef353c41ab0a78a3e4742803 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
bpo-31752: Fix possible crash in timedelta constructor called with custom integers. (GH-3947) (bpo-4086)
https://github.com/python/cpython/commit/6e45d7b90accbbdfef353c41ab0a78a3e4742803

**Comment by serhiy-storchaka** [comment]
New changeset 5ef883b096895a84123760859f0f34ad37bf2277 by Serhiy Storchaka in branch '2.7':
[2.7] bpo-31752: Fix possible crash in timedelta constructor called with custom integers. (GH-3947) (bpo-4088)
https://github.com/python/cpython/commit/5ef883b096895a84123760859f0f34ad37bf2277
