### ISSUE TITLE
SetType is missing in the 'types' module

### ISSUE THREAD

**Issue by 1e085b4d-03ce-4e86-a41d-031d3ef82712** [python/cpython#75936]
BPO | [31755](https://bugs.python.org/issue31755)
--- | :---
Nosy | @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-11.08:02:35.923>
created_at = <Date 2017-10-11.07:45:29.559>
labels = ['invalid', 'type-bug', 'library']
title = "SetType is missing in the 'types' module"
updated_at = <Date 2017-10-11.08:23:22.059>
user = 'https://bugs.python.org/KenjiAsukaAsukaKenji'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-11.08:23:22.059>
actor = 'Kenji Asuka (Asuka Kenji)'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-11.08:02:35.923>
closer = 'christian.heimes'
components = ['Library (Lib)']
creation = <Date 2017-10-11.07:45:29.559>
creator = 'Kenji Asuka (Asuka Kenji)'
dependencies = []
files = []
hgrepos = []
issue_num = 31755
keywords = []
message_count = 4.0
messages = ['304112', '304113', '304114', '304116']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'Kenji Asuka (Asuka Kenji)']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31755'
versions = ['Python 2.7']
```

</p></details>

**Comment by 1e085b4d-03ce-4e86-a41d-031d3ef82712** [comment]
```py
# Create a dict and a set
d = {1: '1'}
s = {1}

# They have different types
print(type(d))             # <type 'dict'>
print(type(s))             # <type 'set'>
print(type(d) is type(s))  # False
print(type(s) is type(d))  # False
print(type(d) == type(s))  # False
```


\# Dictionary type is found in 'types' module
print(type(d) is types.DictType)               # True
print(type(d) is types.DictionaryType)         # True
print(types.DictType == types.DictionaryType)  # True

\# Set type is not found in 'types' module
print(type(s) is types.DictType)            # False
print(type(s) is types.DictionaryType)      # False
print(type(s) is types.DictProxyType)       # False
print(type(s) is types.ListType)            # False
print(type(s) is types.SliceType)           # False
print(type(s) is types.TupleType)           # False
print(type(s) is types.NotImplementedType)  # False
print(type(s) is types.SetType)             # AttributeError: 'module' object has no attribute 'SetType'

**Comment by 1e085b4d-03ce-4e86-a41d-031d3ef82712** [comment]
'set' is a built-in type, and should belong to one of the types in the 'types' module. However, in the latest 2.7 implementations, none of the names matches the 'set' type.

Like 'list' and 'dict', I suppose there should be a name 'SetType' in the 'types' module. However, I guess it was forgotten to be created when the '{x: y}' syntax was introduced.

**Comment by tiran** [comment]
The types modules is not suppose to hold all known types. It only contains types that are not available as builtin. The DictType member is a relict from the past. Before Python 2.2, the dict builtin and dict type were different things.

In Python 3, the types module no longer has DictType, IntType etc.

**Comment by 1e085b4d-03ce-4e86-a41d-031d3ef82712** [comment]
You wrote:

> It only contains types that are not available as builtin.

I think the opposite is true.


As shown in the "Versions" field in the issue, this bug is Python 2 specific, so there is nothing to do with Python 3.

My point is not on 'dict', but on 'set'. So the history of 'dict' doesn't care.

As we can see there are names for:
- 'None' (types.NoneType)
- 'bool' (types.BooleanType)
- 'int' (types.IntType)
- 'long' (types.LongType)
- 'float' (types.FloatType)
- 'complex' (types.ComplexType)
- etc.

and more importantly:
- 'tuple' (types.TupleType)
- 'list' (types.ListType)
- 'dict' (types.DictType)

and since 'set' is also considered a built-in type (see https://docs.python.org/2/library/stdtypes.html), I can't see the reason WHY it is not considered a bug without having 'set' (types.SetType) in the module.
