### ISSUE TITLE
Documented type of parameter 'itemsize' to PyBuffer_FillContiguousStrides is incorrect.

### ISSUE THREAD

**Issue by 131c72c7-92c8-4263-8cd0-7be37dfb421a** [python/cpython#75935]
BPO | [31754](https://bugs.python.org/issue31754)
--- | :---
Nosy | @berkerpeksag, @ruibo, @Mariatta, @vyas45
PRs | <li>python/cpython#3993</li><li>python/cpython#4005</li><li>python/cpython#4011</li><li>python/cpython#4012</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.18:26:06.121>
created_at = <Date 2017-10-11.00:18:47.270>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = "Documented type of parameter 'itemsize' to PyBuffer_FillContiguousStrides is incorrect."
updated_at = <Date 2017-10-16.18:26:06.120>
user = 'https://github.com/ruibo'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.18:26:06.120>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-16.18:26:06.121>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-10-11.00:18:47.270>
creator = 'snoeberger'
dependencies = []
files = []
hgrepos = []
issue_num = 31754
keywords = ['patch', 'easy']
message_count = 8.0
messages = ['304096', '304355', '304360', '304385', '304424', '304425', '304479', '304480']
nosy_count = 5.0
nosy_names = ['docs@python', 'berker.peksag', 'snoeberger', 'Mariatta', 'vyas45']
pr_nums = ['3993', '4005', '4011', '4012']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31754'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 131c72c7-92c8-4263-8cd0-7be37dfb421a** [comment]
The signature for PyBuffer_FillContiguousStrides in the documentation shows that the type of parameter 'itemsize' is Py_ssize_t [1]. This is different from the signature in [Include/abstract.h](https://github.com/python/cpython/blob/main/Include/abstract.h) which shows that the type as int [2].


[1] https://docs.python.org/3/c-api/buffer.html#c.PyBuffer_FillContiguousStrides
[2] https://github.com/python/cpython/blob/49b2734bf12dc1cda80fd73d3ec8896ae3e362f2/Include/abstract.h#L559-L563

**Comment by 438f87e1-dfd7-42f4-9c9c-81be97e197c2** [comment]
Hello !  I am new to the community and would love to start my contribution here. Can I take up this bug ? 

In order to do so I am going through the following links: 

https://docs.python.org/devguide/docquality.html
https://docs.python.org/devguide/pullrequest.html

Is the list exhaustive for this particular issue ? 

Thanks !

**Comment by Mariatta** [comment]
Welcome Aniket. Yes those two links are good starting points.
Please propose a PR with the fix.

**Comment by 438f87e1-dfd7-42f4-9c9c-81be97e197c2** [comment]
Thanks Mariatta. I have initiated a PR for the issue. 

https://github.com/python/cpython/pull/3993

**Comment by berkerpeksag** [comment]
New changeset 1b9e76ed3a055a53ca67397e928e1b408461900b by Berker Peksag (vyas45) in branch 'master':
bpo-31754: Fix type of 'itemsize' in PyBuffer_FillContiguousStrides (GH-3993)
https://github.com/python/cpython/commit/1b9e76ed3a055a53ca67397e928e1b408461900b

**Comment by berkerpeksag** [comment]
New changeset e881302b70ab36bafcf37e3917be118bbec97763 by Berker Peksag (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31754: Fix type of 'itemsize' in PyBuffer_FillContiguousStrides (GH-3993)
https://github.com/python/cpython/commit/e881302b70ab36bafcf37e3917be118bbec97763

**Comment by berkerpeksag** [comment]
New changeset 50cef52372381a9e2f3d760497d8db76254cffef by Berker Peksag (vyas45) in branch '2.7':
[2.7] bpo-31754: Fix type of 'itemsize' in PyBuffer_FillContiguousStrides (GH-3993)
https://github.com/python/cpython/commit/50cef52372381a9e2f3d760497d8db76254cffef

**Comment by berkerpeksag** [comment]
Thank you for the report, Robert and thank you for the patches, Aniket.
