### ISSUE TITLE
Tutorial: Fibonacci numbers start with 1, 1

### ISSUE THREAD

**Issue by 7c400b98-afda-4475-b8f2-8b29d46c2b9d** [python/cpython#75938]
BPO | [31757](https://bugs.python.org/issue31757)
--- | :---
Nosy | @rhettinger, @terryjreedy, @mdickinson, @stevendaprano
PRs | <li>python/cpython#3991</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2017-10-14.14:36:58.087>
created_at = <Date 2017-10-11.14:40:19.957>
labels = ['type-bug', '3.7', 'docs']
title = 'Tutorial: Fibonacci numbers start with 1, 1'
updated_at = <Date 2017-10-14.14:36:58.087>
user = 'https://bugs.python.org/skyhein'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-14.14:36:58.087>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2017-10-14.14:36:58.087>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-10-11.14:40:19.957>
creator = 'skyhein'
dependencies = []
files = []
hgrepos = []
issue_num = 31757
keywords = ['patch']
message_count = 8.0
messages = ['304144', '304156', '304157', '304167', '304174', '304363', '304375', '304394']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'mark.dickinson', 'steven.daprano', 'docs@python', 'skyhein']
pr_nums = ['3991']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31757'
versions = ['Python 3.7']
```

</p></details>

**Comment by 7c400b98-afda-4475-b8f2-8b29d46c2b9d** [comment]
In https://docs.python.org/3/tutorial/controlflow.html#defining-functions both examples produce fibonacci numbers starting with 0. They should start with 1, as in the example in https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming

The first example should change the lines
    while a \< n:
        print(a, end=' ')
to
    while b \< n:
        print(b, end=' ')

and the second example should change the lines
    while a \< n:
        result.append(a)    # see below
to
    while b \< n:
        result.append(b)    # see below

**Comment by mdickinson** [comment]
Is there any particular reason you want to start with 1? While not universal, it's standard to define `Fib(0) = 0`, and to start the sequence at `0`. (And note that Python usually starts indexing things from 0, so it makes sense to start with `Fib(0)` rather than `Fib(1)`.)

In principle, one could define `Fib(0)=1`, `Fib(1)=1`, `Fib(1)=2`, and so on, but there's a strong reason not to do so: it breaks (or at least uglifies) many nice number-theoretic properties, like `gcd(Fib(m), Fib(n)) == Fib(gcd(m, n))`.

**Comment by mdickinson** [comment]
A nice response to the question of whether to start with 0 or 1 here: https://stackoverflow.com/a/5901955

> The definition with Fib(0) = 1 is known as the combinatorial
> definition, and Fib(0) = 0 is the classical definition. Both
> are used in the Fibonacci Quarterly, though authors that use
> the combinatorial definition need to add a sentence of
> explanation.

I confess that I hadn't heard of the Fibonacci Quarterly before.

**Comment by 7c400b98-afda-4475-b8f2-8b29d46c2b9d** [comment]
I would not insist of starting with 1 instead of 0 (I follow your arguments here), but perhaps it would be nice if it would behave the same way in both chapters. The first fibonacci number examples in https://docs.python.org/3/tutorial/introduction.html#first-steps-towards-programming start with 1.

There are three examples here, in the first,

```py
while b < 10:
    print(b)
```


should change to

```py
while a < 10:
    print(a)
```


The output of this first example would have an additional 0:
0
1
1
...

And in the third example

```py
while b < 1000:
    print(b, end=',')
```


should change to

```py
while a < 1000:
    print(a, end=',')
```


where the output of this third example would change from

1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

to

0,1,1,2,3,5,8,13,21,34,55,89,144,233,377,610,987,

**Comment by mdickinson** [comment]
I agree it would be good to be consistent.

**Comment by terryjreedy** [comment]
I agree that we should be consistent -- with the current standard definition -- with the changes suggested above.  Heinrich, can you, and do you want to, submit a patch?  If so, please also sign the contributor agreement.  See https://www.python.org/psf/contrib/

The Fibonacci numbers start with 1 if there is no F(0), as in Fibonacci's rabbit model.  Before 0 was accepted as a number, the series had to start with F(1) = F(2) = 1.  See https://en.wikipedia.org/wiki/Fibonacci_number

**Comment by rhettinger** [comment]
I update the example in "First Steps Towards Programming" to match the one in "Defining Functions" (which is also shown on the home page at www.python.org.

**Comment by rhettinger** [comment]
New changeset 8c26a34f93db7ae96b42bcce6b557437436c7721 by Raymond Hettinger in branch 'master':
bpo-31757: Make Fibonacci examples consistent (bpo-3991)
https://github.com/python/cpython/commit/8c26a34f93db7ae96b42bcce6b557437436c7721
