### ISSUE TITLE
Python 3.5 missing from documentation

### ISSUE THREAD

**Issue by 1badd512-0525-4080-8712-5291bd4c7493** [python/cpython#75947]
BPO | [31766](https://bugs.python.org/issue31766)
--- | :---
Nosy | @freddrake, @larryhastings, @ned-deily, @TonyFlury
PRs | <li>python/cpython#3969</li><li>python/cpython#3970</li><li>python/cpython#3971</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-12.18:31:21.085>
created_at = <Date 2017-10-11.21:18:37.930>
labels = ['type-bug', '3.7', 'docs']
title = 'Python 3.5 missing from documentation'
updated_at = <Date 2017-10-12.18:31:21.083>
user = 'https://github.com/TonyFlury'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-12.18:31:21.083>
actor = 'ned.deily'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-12.18:31:21.085>
closer = 'ned.deily'
components = ['Documentation']
creation = <Date 2017-10-11.21:18:37.930>
creator = 'anthony-flury'
dependencies = []
files = []
hgrepos = []
issue_num = 31766
keywords = ['patch']
message_count = 8.0
messages = ['304181', '304185', '304271', '304272', '304275', '304276', '304277', '304278']
nosy_count = 5.0
nosy_names = ['fdrake', 'larry', 'ned.deily', 'docs@python', 'anthony-flury']
pr_nums = ['3969', '3970', '3971']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31766'
versions = ['Python 2.7', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 1badd512-0525-4080-8712-5291bd4c7493** [comment]
In the Python version pull down list on docs.python.org, Python3.5 used to be listed, but has now been removed; the list only contains 2.7, 3.6 & 3.7.

Python 3.5 is still the official Python 3.5 release in the Ubuntu repository, and still a supported release in other parts of python.org, so to see it disappearing from the drop-down was surprising.

To note - if you pick a particular page - say : 

https://docs.python.org/3/tutorial/index.html

and change the url to : 

https://docs.python.org/3.5/tutorial/index.html

The pull down now does contain 3.5 (along side 2.7, 3.63 & 3.7)

**Comment by ned-deily** [comment]
The documentation for 3.5 was deliberated removed from the pull down lists of current docsets as 3.5 is now in security-fix-only mode; the 3.5 documentation is only updated when a new security release is made and general doc changes to it are no longer made.  You can find a link to the docsets for 3.5.x and all Python releases on the Python Documentation By Version page (https://www.python.org/doc/versions/) which is linked to from a number of places, including the index page of the current and past Python versions docsets (e.g. https://docs.python.org/3/) and from the main python.org doc page (https://www.python.org/doc/).

**Comment by 1badd512-0525-4080-8712-5291bd4c7493** [comment]
Isn't Python 2.7 in Security Fix only as well ?

It seems strange; Python 3.5 probably the most heavily installed Python 3 release (every Ubuntu installation has Python 3.5 installed by default - and neither Python 3.6 or 3.7 are available from the standard ubuntu repository); the docs.python.org site is the normal place people are directed to for help - and the implication of the removal will be for many people is that Python 3.5 is obsolete which isn't the case at all.

**Comment by freddrake** [comment]
The 3.5 docs should really remain in the main docs UI via the pulldown as long as it's so widely used.  The fact that it won't be changing much just means it can be served efficiently.

**Comment by ned-deily** [comment]
New changeset b7cbfe49e39a7bbd7da20b937735a8a60bbf1872 by Ned Deily in branch 'master':
bpo-31766: restore 3.5 to docs version switchers (bpo-3969)
https://github.com/python/cpython/commit/b7cbfe49e39a7bbd7da20b937735a8a60bbf1872

**Comment by ned-deily** [comment]
New changeset f8d42ea0e4341b270f1de71b4ff40cfa18420eed by Ned Deily in branch '3.6':
bpo-31766: restore 3.5 to docs version switchers (bpo-3970)
https://github.com/python/cpython/commit/f8d42ea0e4341b270f1de71b4ff40cfa18420eed

**Comment by ned-deily** [comment]
New changeset 356b68023d6fee5e30d25a4a680ac5b9e4f8dd65 by Ned Deily in branch '2.7':
bpo-31766: restore 3.5 to docs version switchers (bpo-3971)
https://github.com/python/cpython/commit/356b68023d6fee5e30d25a4a680ac5b9e4f8dd65

**Comment by ned-deily** [comment]
> Isn't Python 2.7 in Security Fix only as well ?

No, 2.7 is still being actively maintained (until 2020).
(https://devguide.python.org/#status-of-python-branches)

But, bowing to popular demand, I've restored 3.5 to the switchers for 3.7, 3.6, and 2.7.  It should appear again in the on-line docs shortly.  Thanks for all of your comments!
