### ISSUE TITLE
BUG: System deadlocks performing big loop operations in python 3.5.4, windows 10

### ISSUE THREAD

**Issue by 3b2d58e8-6f21-47f9-8fbc-847e0358c4a5** [python/cpython#75946]
BPO | [31765](https://bugs.python.org/issue31765)
--- | :---
Nosy | @terryjreedy, @bitdancer, @GREEKYnikhilsharma

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-13.21:34:33.032>
created_at = <Date 2017-10-11.19:10:07.908>
labels = []
title = 'BUG: System deadlocks performing big loop operations in python 3.5.4, windows 10'
updated_at = <Date 2017-10-13.21:34:33.030>
user = 'https://github.com/GREEKYnikhilsharma'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-13.21:34:33.030>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-13.21:34:33.032>
closer = 'terry.reedy'
components = []
creation = <Date 2017-10-11.19:10:07.908>
creator = 'Nik101'
dependencies = []
files = []
hgrepos = []
issue_num = 31765
keywords = []
message_count = 3.0
messages = ['304173', '304175', '304366']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'r.david.murray', 'Nik101']
pr_nums = []
priority = 'normal'
resolution = 'later'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31765'
versions = []
```

</p></details>

**Comment by 3b2d58e8-6f21-47f9-8fbc-847e0358c4a5** [comment]
What I did
1) root file declared where operation will start and import hashlib for
getting hash signatures
2) os.walk for recursively diving into directory tree
3) open file and find sha256 digest and print it
4) close the file
5) recursively repeat all above 2 steps till we traversed directory tree

Above logic python program caused sudden exponential increase in RAM usage
(task manager by chance)  and certainly DEADLOCK and......  Force shutdown

I want to know what went wrong.....

**Comment by bitdancer** [comment]
Most likely an error in your program logic, I'm afraid.  This isn't a forum for getting help, you should try the python-list mailing list.  (If you do find a bug, you can then open an issue with details.)

**Comment by terryjreedy** [comment]
Nikhil, I am closing this for now because I am at least 85% sure David is right.  To get any help, you need to reduce your code to the minimum needed to produce the symptoms and then include that with any question.  You would be told the same on Stackoverflow, which is another place to seek answers.
