### ISSUE TITLE
Missing "raise from None" in /Lib/xml/etree/ElementPath.py

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#75957]
BPO | [31776](https://bugs.python.org/issue31776)
--- | :---
Nosy | @serhiy-storchaka, @pablogsal
PRs | <li>python/cpython#3978</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.08:25:46.316>
created_at = <Date 2017-10-12.20:59:28.080>
labels = ['3.7', 'type-feature', 'library']
title = 'Missing "raise from None" in /Lib/xml/etree/ElementPath.py'
updated_at = <Date 2017-10-16.08:25:46.315>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.08:25:46.315>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-16.08:25:46.316>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-10-12.20:59:28.080>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 31776
keywords = ['patch']
message_count = 2.0
messages = ['304288', '304462']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'pablogsal']
pr_nums = ['3978']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31776'
versions = ['Python 3.7']
```

</p></details>

**Comment by pablogsal** [comment]
Based on bpo-29762 (https://github.com/python/cpython/commit/5affd23e6f42125998724787025080a24839266e), there is an inconsistency on one exception chain in /Lib/xml/etree/ElementPath.py:

             try:
                 selector.append(ops[token[0]](next, token))
             except StopIteration:
                raise SyntaxError("invalid path")

should be

              raise SyntaxError("invalid path") from None

**Comment by serhiy-storchaka** [comment]
New changeset 0df19055c92a0b0728659807978e4ca4d6c8e1bc by Serhiy Storchaka (Pablo Galindo) in branch 'master':
bpo-31776: Missing "raise from None" in [Lib/xml/etree/ElementPath.py](https://github.com/python/cpython/blob/main/Lib/xml/etree/ElementPath.py) (bpo-3978)
https://github.com/python/cpython/commit/0df19055c92a0b0728659807978e4ca4d6c8e1bc
