### ISSUE TITLE
Support unbuffered TextIOWrapper

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75956]
BPO | [31775](https://bugs.python.org/issue31775)
--- | :---
Nosy | @vstinner, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-12.15:09:32.634>
labels = ['3.7', 'expert-IO']
title = 'Support unbuffered TextIOWrapper'
updated_at = <Date 2017-10-28.12:09:57.068>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-28.12:09:57.068>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-10-12.15:09:32.634>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31775
keywords = []
message_count = 7.0
messages = ['304250', '304252', '304253', '304258', '304260', '304262', '304266']
nosy_count = 2.0
nosy_names = ['vstinner', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'pending'
superseder = None
type = None
url = 'https://bugs.python.org/issue31775'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
It seems like that some methods of the io.TextIOWrapper class requires that its buffer object has the read1() method, whereas the constructor checks if the buffer has a read1() method and the TextIOWrapper \_read_chunk() method is able to call buffer.read() if buffer doesn't have read1().

This issue may help to get fully unbuffered sys.stdin, at least when replaced manually:

```py
stdin = sys.stdin
sys.stdin = open(0, "r", buffering=0, encoding=stdin.encoding, errors=stdin.errors, newline=stdin.newline)
```

**Comment by vstinner** [comment]
I created this issue because of this comment in create_stdio() of [Python/pylifecycle.c](https://github.com/python/cpython/blob/main/Python/pylifecycle.c):
\---
    /* stdin is always opened in buffered mode, first because it shouldn't
       make a difference in common use cases, second because TextIOWrapper
       depends on the presence of a read1() method which only exists on
       buffered streams.
    */
    if (Py_UnbufferedStdioFlag && write_mode)
        buffering = 0;
    else
        buffering = -1;
\---

**Comment by vstinner** [comment]
Oh, currently it's not possible to create an unbuffered read-only TextIOWrapper object:

```pycon
haypo@selma$ python3
Python 3.6.2 (default, Oct  2 2017, 16:51:32) 
>>> open("/etc/issue", "r", 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: can't have unbuffered text I/O
```

**Comment by serhiy-storchaka** [comment]
The falling back to read() was implemented in bpo-12591. What methods still require read1()?

**Comment by vstinner** [comment]
> The falling back to read() was implemented in bpo-12591. What methods still require read1()?

I read the Python implementation of TextIOWrapper in \_pyio:

* seek() calls buffer.read() "if chars_to_skip:"... not sure that it can happen if buffer is a FileIO?
* read(None)  and read(-1) to read "everything" (until EOF): buffer.read()

It seems like read(None) also calls buffer.read() in the C implementation, \_io_TextIOWrapper_read_impl():

```c
        /* Read everything */
        PyObject *bytes = _PyObject_CallMethodId(self->buffer, &PyId_read, NULL);
        PyObject *decoded;
        if (bytes == NULL)
            goto fail;
```


and in \_io_TextIOWrapper_seek_impl():

```c
        /* Just like _read_chunk, feed the decoder and save a snapshot. */
        PyObject *input_chunk = _PyObject_CallMethodId(
            self->buffer, &PyId_read, "i", cookie.bytes_to_feed);
```

**Comment by vstinner** [comment]
Context: I created this issue as a follow-up of the discussion on the -u command line option, bpo-28647, which still leaves sys.stdin \*buffered* in the current master branch.

**Comment by serhiy-storchaka** [comment]
What methods still require read1()?

**Comment by vstinner** [comment]
Sadly I don't have the bandwidth to work on this issue, it's inactive for 5 years, I just close the issue.
