### ISSUE TITLE
Typo in comments Modules/_ssl.c

### ISSUE THREAD

**Issue by ff5828d1-cbc3-40a8-9e39-ce4f17ece55e** [python/cpython#75969]
BPO | [31788](https://bugs.python.org/issue31788)
--- | :---
Nosy | @benjaminp, @vyas45
PRs | <li>python/cpython#3999</li><li>python/cpython#4008</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-15.19:28:33.893>
created_at = <Date 2017-10-14.23:55:59.127>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = 'Typo in comments Modules/_ssl.c'
updated_at = <Date 2017-10-15.19:48:54.581>
user = 'https://bugs.python.org/SemenZhydenko'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-15.19:48:54.581>
actor = 'benjamin.peterson'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-15.19:28:33.893>
closer = 'benjamin.peterson'
components = ['Documentation']
creation = <Date 2017-10-14.23:55:59.127>
creator = 'Semen Zhydenko'
dependencies = []
files = []
hgrepos = []
issue_num = 31788
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['304405', '304443', '304444', '304446', '304447']
nosy_count = 4.0
nosy_names = ['benjamin.peterson', 'docs@python', 'vyas45', 'Semen Zhydenko']
pr_nums = ['3999', '4008']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31788'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ff5828d1-cbc3-40a8-9e39-ce4f17ece55e** [comment]
completly must be changed to completely

**Comment by 438f87e1-dfd7-42f4-9c9c-81be97e197c2** [comment]
I can pick this up if it's okay.

**Comment by 438f87e1-dfd7-42f4-9c9c-81be97e197c2** [comment]
My bad, didn't notice the PR already existing.

**Comment by benjaminp** [comment]
New changeset 1295e11d397c6138427296d5f9653a9e7dd69062 by Benjamin Peterson (Semen Zhydenko) in branch 'master':
completly -\> completely (bpo-3999) (closes bpo-31788)
https://github.com/python/cpython/commit/1295e11d397c6138427296d5f9653a9e7dd69062

**Comment by benjaminp** [comment]
New changeset cfc604722ff5ad64de96ddeb944661f1e94d8cd0 by Benjamin Peterson (Miss Islington (bot)) in branch '3.6':
[3.6] completly -\> completely (GH-3999) (closes bpo-31788) (bpo-4008)
https://github.com/python/cpython/commit/cfc604722ff5ad64de96ddeb944661f1e94d8cd0
