### ISSUE TITLE
crashes when calling methods of an uninitialized zipimport.zipimporter object

### ISSUE THREAD

**Issue by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [python/cpython#75962]
BPO | [31781](https://bugs.python.org/issue31781)
--- | :---
Nosy | @brettcannon, @orenmn
PRs | <li>python/cpython#3986</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-20.20:43:37.214>
created_at = <Date 2017-10-13.16:56:47.582>
labels = ['extension-modules', '3.7', 'type-crash']
title = 'crashes when calling methods of an uninitialized zipimport.zipimporter object'
updated_at = <Date 2017-10-20.20:43:37.213>
user = 'https://github.com/orenmn'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-20.20:43:37.213>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-20.20:43:37.214>
closer = 'brett.cannon'
components = ['Extension Modules']
creation = <Date 2017-10-13.16:56:47.582>
creator = 'Oren Milman'
dependencies = []
files = []
hgrepos = []
issue_num = 31781
keywords = ['patch']
message_count = 3.0
messages = ['304346', '304680', '304681']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'Oren Milman']
pr_nums = ['3986']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31781'
versions = ['Python 3.7']
```

</p></details>

**Comment by 4e331a12-c2bb-4cd1-b83c-dcc766e8fbf8** [comment]
The following code crashes:
import zipimport
zi = zipimport.zipimporter.\_\_new__(zipimport.zipimporter)
zi.find_module('foo')

This is because get_module_info() (in [Modules/zipimport.c](https://github.com/python/cpython/blob/main/Modules/zipimport.c)) assumes that the
zipimporter object is initialized, so it assumes that `self->prefix` is not
NULL, and passes it to make_filename(), which crashes.

get_module_code() makes the same assumption, and zipimport_zipimporter_get_data_impl()
assumes that `self->archive` is not NULL, and passes it to PyUnicode_GET_LENGTH(),
which crashes.
Thus, every method of an uninitialized zipimporter object might crash.


I would open a PR to fix this soon.

**Comment by brettcannon** [comment]
New changeset db60a5bfa5d5f7a6f1538cc1fe76f0fda57b524e by Brett Cannon (Oren Milman) in branch 'master':
bpo-31781: Prevent crashes when calling methods of an uninitialized zipimport.zipimporter object (GH-3986)
https://github.com/python/cpython/commit/db60a5bfa5d5f7a6f1538cc1fe76f0fda57b524e

**Comment by brettcannon** [comment]
As always, thanks for the fix, Oren!
