### ISSUE TITLE
The mccabe complexity output in module flake8.

### ISSUE THREAD

**Issue by 5f74d499-1719-41ed-b972-004d96aa5e3b** [python/cpython#75977]
BPO | [31796](https://bugs.python.org/issue31796)
--- | :---
Nosy | @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.01:10:01.558>
created_at = <Date 2017-10-16.01:07:22.303>
labels = []
title = 'The mccabe complexity output in module flake8.'
updated_at = <Date 2017-10-16.01:10:01.488>
user = 'https://bugs.python.org/fqbrighter'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.01:10:01.488>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-16.01:10:01.558>
closer = 'ned.deily'
components = []
creation = <Date 2017-10-16.01:07:22.303>
creator = 'fqbrighter'
dependencies = []
files = []
hgrepos = []
issue_num = 31796
keywords = []
message_count = 2.0
messages = ['304450', '304451']
nosy_count = 2.0
nosy_names = ['ned.deily', 'fqbrighter']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31796'
versions = []
```

</p></details>

**Comment by 5f74d499-1719-41ed-b972-004d96aa5e3b** [comment]
Dear,
      I have found that if a function name appears more than one time in a
file, the output of McCabe complexity for this function name only appear
once. I think it should output all of them. So, I send this email for
inquiring about this confusing problems.

Thanks,

Sincerely,

fuqianz

**Comment by ned-deily** [comment]
flake8 is not part of the Python Standard Library.  You might start with its project page here: https://gitlab.com/pycqa/flake8
