### ISSUE TITLE
test_buffer altered the execution environment

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#75973]
BPO | [31792](https://bugs.python.org/issue31792)
--- | :---
Nosy | @vstinner, @ezio-melotti, @voidspace, @skrah, @serhiy-storchaka
PRs | <li>python/cpython#4007</li><li>python/cpython#4009</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.08:22:33.422>
created_at = <Date 2017-10-15.09:35:57.853>
labels = ['3.7', 'tests', 'performance']
title = 'test_buffer altered the execution environment'
updated_at = <Date 2017-10-16.08:22:33.369>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.08:22:33.369>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-16.08:22:33.422>
closer = 'serhiy.storchaka'
components = ['Tests']
creation = <Date 2017-10-15.09:35:57.853>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31792
keywords = ['patch']
message_count = 14.0
messages = ['304426', '304428', '304430', '304432', '304434', '304435', '304436', '304437', '304438', '304441', '304442', '304455', '304460', '304461']
nosy_count = 5.0
nosy_names = ['vstinner', 'ezio.melotti', 'michael.foord', 'skrah', 'serhiy.storchaka']
pr_nums = ['4007', '4009']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31792'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
test_buffer adds two environment variables: 'OPENBLAS_MAIN_FREE': '1', 'GOTOBLAS_MAIN_FREE': '1'.

```sh
$ ./python -m test -v test_buffer
...
Warning -- os.environ was modified by test_buffer
  Before: (140174267697792, environ({...})
  After:  (140174267697792, environ({..., 'OPENBLAS_MAIN_FREE': '1', 'GOTOBLAS_MAIN_FREE': '1'}) 
test_buffer failed (env changed)
```


1 test altered the execution environment:
    test_buffer

Total duration: 8 sec
Tests result: SUCCESS

**Comment by vstinner** [comment]
Why the env changed wasn't noticed before? Is it a recent change?

**Comment by serhiy-storchaka** [comment]
I just have installed NumPy. It temporary sets these two environment variables for importing the multiarray numpy extension module, but forgot to remove them if the import is failed.

test_buffer imports numpy.

try:
    with warnings.catch_warnings():
        from numpy import ndarray as numpy_array
except ImportError:
    numpy_array = None

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
So it is a numpy issue? Which numpy version is it?

**Comment by serhiy-storchaka** [comment]
It is particularly a NumPy issue (I have opened a bug https://github.com/numpy/numpy/issues/9861). It is exposed because I have installed NumPy with non-debug build of CPython and run the test with debug build of CPython. The test is passes with non-debug build of CPython. I am wondering if we can make a workaround and if we should do this.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Thanks. If it only occurs when mixing debug/non-debug I don't think we have to do anything about it.

**Comment by vstinner** [comment]
I suggest to always save/restore env vars on numpy import, since we don't
control 3rd party code.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
That's fine.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
I can't figure out how to make the damn button green on GitHub,
so LGTM. :)

**Comment by serhiy-storchaka** [comment]
The issue is fixed on NumPy side (will be included in the next release). Is the workaround on our side still needed?

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
I'd push it so we don't have to worry about similar things in the
future.  The "warnings.catch_warnings()" thing is also a workaround
for some past numpy release.

**Comment by serhiy-storchaka** [comment]
New changeset 676db4bbf2e7c18dc7c35add17dd3bbdc2d3eeb3 by Serhiy Storchaka in branch 'master':
bpo-31792: Restore os.environ in test_buffer when import numpy. (bpo-4007)
https://github.com/python/cpython/commit/676db4bbf2e7c18dc7c35add17dd3bbdc2d3eeb3

**Comment by serhiy-storchaka** [comment]
New changeset 06949585d292d1a9dbf2d0d0fa8fc8fe1dee3ccf by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31792: Restore os.environ in test_buffer when import numpy. (GH-4007) (bpo-4009)
https://github.com/python/cpython/commit/06949585d292d1a9dbf2d0d0fa8fc8fe1dee3ccf

**Comment by serhiy-storchaka** [comment]
Thank you Victor and Stefan for your review.
