### ISSUE TITLE
Allow to specialize smart quotes in documentation translations

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#75974]
BPO | [31793](https://bugs.python.org/issue31793)
--- | :---
Nosy | @terryjreedy, @ezio-melotti, @merwok, @methane, @willingc, @JulienPalard
PRs | <li>python/cpython#4006</li><li>python/cpython#4324</li><li>python/cpython#4325</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-11-05.21:20:59.395>
created_at = <Date 2017-10-15.09:49:48.934>
labels = ['3.7', 'docs']
title = 'Allow to specialize smart quotes in documentation translations'
updated_at = <Date 2018-11-05.21:20:59.394>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-05.21:20:59.394>
actor = 'mdk'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-11-05.21:20:59.395>
closer = 'mdk'
components = ['Documentation']
creation = <Date 2017-10-15.09:49:48.934>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 31793
keywords = ['patch']
message_count = 7.0
messages = ['304429', '304666', '305779', '305782', '305783', '305785', '314329']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'ezio.melotti', 'eric.araujo', 'methane', 'docs@python', 'willingc', 'mdk']
pr_nums = ['4006', '4324', '4325']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31793'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JulienPalard** [comment]
It would be great to allow each translation to specify their smart-quotes configuration, typically Japanese prefer no smart-quotes:

- https://github.com/python/docsbuild-scripts/issues/32

It's easily done by adding a [Doc/docutils.conf](https://github.com/python/cpython/blob/main/Doc/docutils.conf) file, I'm opening a PR.

**Comment by terryjreedy** [comment]
Patch is trivial two lines but needs review and merge from someone familiar with Sphinx stuff.

[Éric, https://docs.python.org/devguide/experts.html contains the invalid Eric.Araujo]

**Comment by methane** [comment]
New changeset 5a66c8a64d180b5f3c80307924adaec53cc8faa3 by INADA Naoki (Julien Palard) in branch 'master':
bpo-31793: Doc: Specialize smart-quotes for Japanese (GH-4006)
https://github.com/python/cpython/commit/5a66c8a64d180b5f3c80307924adaec53cc8faa3

**Comment by methane** [comment]
New changeset 47eaaa55247b6ad8ae507c0048509c2e3db79bf0 by INADA Naoki (Miss Islington (bot)) in branch '2.7':
bpo-31793: Doc: Specialize smart-quotes for Japanese (GH-4006)
https://github.com/python/cpython/commit/47eaaa55247b6ad8ae507c0048509c2e3db79bf0

**Comment by methane** [comment]
New changeset 64f10492dcda4117ac06399ae46ab645cb09b19e by INADA Naoki (Miss Islington (bot)) in branch '3.6':
bpo-31793: Doc: Specialize smart-quotes for Japanese (GH-4006)
https://github.com/python/cpython/commit/64f10492dcda4117ac06399ae46ab645cb09b19e

**Comment by methane** [comment]
Thanks, Julien.
