### ISSUE TITLE
Ensure that all PyTypeObject fields are set to non-NULL defaults

### ISSUE THREAD

**Issue by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [python/cpython#75972]
BPO | [31791](https://bugs.python.org/issue31791)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @pdox

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-07-15.12:46:38.969>
created_at = <Date 2017-10-15.06:22:29.308>
labels = ['interpreter-core', '3.7', 'performance']
title = 'Ensure that all PyTypeObject fields are set to non-NULL defaults'
updated_at = <Date 2021-07-15.12:46:38.969>
user = 'https://github.com/pdox'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-15.12:46:38.969>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-07-15.12:46:38.969>
closer = 'iritkatriel'
components = ['Interpreter Core']
creation = <Date 2017-10-15.06:22:29.308>
creator = 'pdox'
dependencies = []
files = []
hgrepos = []
issue_num = 31791
keywords = []
message_count = 5.0
messages = ['304420', '304421', '304422', '304423', '304448']
nosy_count = 3.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'pdox']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31791'
versions = ['Python 3.7']
```

</p></details>

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
Ensure that every function pointer in every PyTypeObject is set to a non-NULL default, to spare the cost of checking for NULL with every use. As a basic example, consider PyNumber_Negative:

```c
PyObject *
PyNumber_Negative(PyObject *o)
{
    PyNumberMethods *m;

    if (o == NULL) {
        return null_error();
    }
```


```py
    m = o->ob_type->tp_as_number;
    if (m && m->nb_negative)
        return (*m->nb_negative)(o);
```


    return type_error("bad operand type for unary -: '%.200s'", o);
}

If "tp_as_number" and "nb_negative" were always guaranteed non-NULL, then the function could omit the second if statement, and invoke the function pointer directly. To maintain the existing behavior, the default nb_negative function would be set to the following:

```c
PyObject* nb_negative_default(PyObject *o) {
    return type_error("bad operand type for unary -: '%.200s'", o);
}
```


This removes two NULL-checks from the PyNumber_Negative. Many other operators and builtins would be able to benefit in the same way.

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
I believe it would also make sense to inline the 'as' structures (tp_as_async, tp_as_number, tp_as_sequence, tp_as_mapping, and tp_as_buffer), instead of having them be pointers. This would save one pointer dereference with each use. But this would have API compatibility consequences, so for this change it is off the table.

**Comment by serhiy-storchaka** [comment]
1. This will increase the size of type object. Most types are not numbers, not collections and don't support the buffer protocol, thus save memory for tp_as_number, tp_as_sequence, tp_as_mapping and tp_as_buffer. This also can increase the time of type creation.

2. This will make harder testing that the particular protocol is supported (e.g. see PyIndex_Check or PyObject_CheckBuffer). And this will break any third-party code that does this directly, without using C API.

3. Calling function instead of executing inlined code after checking can increase stack consumption and slow down execution (see the usage of tp_descr_get).

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
serhiy.storchaka:

1) Where tp_as_number would normally be NULL, instead it would point to a fixed PyNumberMethods structure containing the default functions. This would make the memory increase negligible, as all non-number types would use the same structure.

2) If this is behavior we want to formally support, then we should provide macros for it. (all they must do is compare against the default pointer value, rather than NULL). Are there particular extension(s) you suspect may be doing this?

3) This has to be handled on a case-by-case basis. I would not remove inlined optimizations. If there are some fields that truly benefit from remaining NULL, those can be left alone. I would like to focus on the functions for which the common case (in code without type errors) is to make the indirect call.

**Comment by rhettinger** [comment]
For all the reasons Serhiy mentioned, I recommend rejecting this request.  This was an intentional and long-standing design decision. A substantial part of the Python ecosystem depends on it.
