### ISSUE TITLE
double free or corruption (while using smem)

### ISSUE THREAD

**Issue by bf207f4d-e2bc-43b3-808d-f2d817de8fa5** [python/cpython#75971]
BPO | [31790](https://bugs.python.org/issue31790)
--- | :---
Nosy | @terryjreedy, @iritkatriel
Files | <li>[logs.txt](https://bugs.python.org/file47279/logs.txt "Uploaded as text/plain at 2017-11-20.15:06:05 by zulthan"): log files</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-05-27.21:53:07.851>
created_at = <Date 2017-10-15.06:00:32.490>
labels = ['library', 'type-crash']
title = 'double free or corruption (while using smem)'
updated_at = <Date 2021-05-27.21:53:07.851>
user = 'https://bugs.python.org/zulthan'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-27.21:53:07.851>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2021-05-27.21:53:07.851>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2017-10-15.06:00:32.490>
creator = 'zulthan'
dependencies = []
files = ['47279']
hgrepos = []
issue_num = 31790
keywords = []
message_count = 5.0
messages = ['304418', '304665', '306550', '394604', '394610']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'zulthan', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue31790'
versions = ['Python 2.7']
```

</p></details>

**Comment by bf207f4d-e2bc-43b3-808d-f2d817de8fa5** [comment]
Command executed when the crash happened:

/usr/bin/python /usr/bin/smem -t -c command pss -P /usr/lib/chromium/chromium

The attached error.log contains the backtrace and memory map printed.

This is a sporadic error, the command is called every second 0-24, and I got one such error after half a day of running. I probably had another after a few days, but I failed to save that one, so I am not sure, if they are really the same.

It would seem that using a more overloaded / older machine triggers the error more often, the machine I got it on was a

Hewlett-Packard HP Compaq dc7900 Small Form Factor/3031h, BIOS 786G1 v01.27 10/22/2015

The problem seems to have emerged after updating to Debian Stretch.

python version:
Python 2.7.13

smem version:
pool/main/s/smem/smem_1.4-2_all.deb
(could not get an internal smem version, only the debian package)

**Comment by terryjreedy** [comment]
The error log is not present.  Try uploading again.

**Comment by bf207f4d-e2bc-43b3-808d-f2d817de8fa5** [comment]
In a span of about 1 month, I had multiple errors:

*** Error in `/usr/bin/python': free(): invalid next size (normal): 0x000055f9c9e7c970 ***
*** Error in `/usr/bin/python': free(): invalid next size (normal): 0x000055e33fda3970 ***
*** Error in `/usr/bin/python': free(): invalid next size (normal): 0x0000564d42335970 ***
*** Error in `/usr/bin/python': double free or corruption (out): 0x0000561d8b9d4f80 ***
*** Error in `/usr/bin/python': double free or corruption (out): 0x0000557700e74f80 ***
*** Error in `/usr/bin/python': free(): invalid next size (normal): 0x0000564b6142e970 ***

In the same time-period, I have been running the same code on another system, with a different python version, which did not produce any error:

python version that causes issues:
python --version
Python 2.7.13

python version that is error-free:
Python 2.7.9
