### ISSUE TITLE
Slicings documentation doesn't mention Ellipsis

### ISSUE THREAD

**Issue by 2c100645-d0d7-4890-9a79-ab2d098d4979** [python/cpython#75976]
BPO | [31795](https://bugs.python.org/issue31795)
--- | :---
Nosy | @rhettinger, @nitishch

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-16.12:06:43.842>
created_at = <Date 2017-10-15.22:45:56.215>
labels = ['type-feature', 'invalid', 'docs']
title = "Slicings documentation doesn't mention Ellipsis"
updated_at = <Date 2017-10-16.12:06:43.840>
user = 'https://github.com/nitishch'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-16.12:06:43.840>
actor = 'rhettinger'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-10-16.12:06:43.842>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-10-15.22:45:56.215>
creator = 'nitishch'
dependencies = []
files = []
hgrepos = []
issue_num = 31795
keywords = []
message_count = 4.0
messages = ['304449', '304452', '304453', '304467']
nosy_count = 3.0
nosy_names = ['rhettinger', 'docs@python', 'nitishch']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31795'
versions = []
```

</p></details>

**Comment by 2c100645-d0d7-4890-9a79-ab2d098d4979** [comment]
Ellipsis object documentation[1] specifies that Ellipsis is mainly used by Slicings. But Slicing's documentation[2] doesn't mention anything about Ellipsis. Consequently - it is not immediately clear from Ellipsis documentation what it's used for.

[1] https://docs.python.org/3/library/stdtypes.html?highlight=ellipsis#the-ellipsis-object

[2] https://docs.python.org/3/reference/expressions.html#slicings

**Comment by rhettinger** [comment]
In regular Python, the ellipsis isn't used for slicing.  It does have special meaning for numpy.   So, I think the docs may be correct as is.

**Comment by 2c100645-d0d7-4890-9a79-ab2d098d4979** [comment]
The problem is that while documentation for other objects like Null object, NotImplemented object make it clear what they are used for, documentation for Ellipsis object only says that it's used in slicings and the slicings documentation doesn't cover Ellipsis.

Can we add an example of its usage in Numpy to the docs?

**Comment by rhettinger** [comment]
> Can we add an example of its usage in Numpy to the docs?

I don't think we should.   In CPython, the ellipsis has no interesting semantics.  It is something that third-party modules can use however they wish.  It doesn't make sense for CPython docs to cover their usage.
