### ISSUE TITLE
multiprocessing calls flush on sys.stdout at exit even if it is None (pythonw)

### ISSUE THREAD

**Issue by 7a34cbe6-092a-448a-8014-9a94def168ca** [python/cpython#75985]
BPO | [31804](https://bugs.python.org/issue31804)
--- | :---
Nosy | @terryjreedy, @pitrou, @applio, @poxthegreat
PRs | <li>python/cpython#5492</li><li>python/cpython#6079</li><li>python/cpython#6080</li><li>python/cpython#6081</li>
Files | <li>[process.py.patch](https://bugs.python.org/file47224/process.py.patch "Uploaded as text/plain at 2017-10-17.14:59:34 by @poxthegreat"): patch file with trivial bugfix</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-03-11.19:10:52.978>
created_at = <Date 2017-10-17.14:59:34.932>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'multiprocessing calls flush on sys.stdout at exit even if it is None (pythonw)'
updated_at = <Date 2018-03-11.19:10:52.977>
user = 'https://github.com/poxthegreat'
```

bugs.python.org fields:
```python
activity = <Date 2018-03-11.19:10:52.977>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2018-03-11.19:10:52.978>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2017-10-17.14:59:34.932>
creator = 'Pox TheGreat'
dependencies = []
files = ['47224']
hgrepos = []
issue_num = 31804
keywords = ['patch']
message_count = 12.0
messages = ['304512', '304678', '309708', '309716', '309721', '309759', '309762', '309853', '313608', '313613', '313616', '313617']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'pitrou', 'davin', 'Pox TheGreat']
pr_nums = ['5492', '6079', '6080', '6081']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31804'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 7a34cbe6-092a-448a-8014-9a94def168ca** [comment]
If you start Python by pythonw then sys.stdout and sys.stderr are set to None. If you also use multiprocessing then when the child process finishes BaseProcess.\_bootstrap calls sys.stdout.flush() and sys.stderr.flush() finally. This causes the process return code to be not zero (it is 1).

**Comment by pitrou** [comment]
This looks to be a duplicate of https://bugs.python.org/issue28326
