### ISSUE TITLE
vars() manipulation encounters problems with Enum

### ISSUE THREAD

**Issue by ethanfurman** [python/cpython#75982]
BPO | [31801](https://bugs.python.org/issue31801)
--- | :---
Nosy | @warsaw, @ethanfurman, @eric-wieser
PRs | <li>python/cpython#5237</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = <Date 2018-09-10.18:30:27.608>
created_at = <Date 2017-10-17.00:21:55.188>
labels = ['type-bug', '3.7']
title = 'vars() manipulation encounters problems with Enum'
updated_at = <Date 2018-09-10.18:30:27.607>
user = 'https://github.com/ethanfurman'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-10.18:30:27.607>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = True
closed_date = <Date 2018-09-10.18:30:27.608>
closer = 'ethan.furman'
components = []
creation = <Date 2017-10-17.00:21:55.188>
creator = 'ethan.furman'
dependencies = []
files = []
hgrepos = []
issue_num = 31801
keywords = ['patch']
message_count = 3.0
messages = ['304487', '306257', '310425']
nosy_count = 4.0
nosy_names = ['barry', 'eli.bendersky', 'ethan.furman', 'Eric.Wieser']
pr_nums = ['5237']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31801'
versions = ['Python 3.7']
```

</p></details>

**Comment by ethanfurman** [comment]
The following code should work (from https://stackoverflow.com/a/46780742/208880):


```py
    class BaudRate(Enum):

        cls = vars()
        regexp = r"(?:^|,)B(?P<rate>\d+)"
        rates = sorted(map(int, re.findall(regexp, ",".join(dir(termios)))))
        for value in rates:
            cls['B%d' % value] = value

        @classmethod
        def valid_rate(cls, value):
            return (any(value == item.value for item in cls))
```



This doesn't work because EnumMeta does not allow names to be reassigned nor deleted.  aenum gets around this by allowing an \_ignore_ attribute which contains the names that should not be tracked (and, in fact, those names are removed from the final class).

Unless a better idea is put forward, I will add \_ignore_ support to Enum.

**Comment by f72d0bc0-f319-4dd9-9db4-d64615e4a426** [comment]
Not necessarily an argument against this feature, but two workarounds exist for this already:


1. Use `nonlocal` to prevent `value` going into the class namespace:

```py
    value = None
    
    class BaudRate(enum.Enum):    
        nonlocal value
        for value in rates:
            locals()['B%d' % value] = value
    
        @classmethod
        def valid_rate(cls, value):
            return (any(value == item.value for item in cls))
```


2. Use `types.new_class`, which is more suited to dynamic class creation anyway:

```py
    def make_cls(ns):
        for value in rates:
            ns['B%d' % value] = value

        @classmethod
        def valid_rate(cls, value):
            return (any(value == item.value for item in cls))
```


        ns['valid_rate'] = valid_rate

    types.new_class('BaudRate', (enum.Enum,), exec_body=make_cls)
