### ISSUE TITLE
async and await missing from keyword list in lexical analysis doc

### ISSUE THREAD

**Issue by fce6aa28-f7e2-4802-a520-563f240dbc1b** [python/cpython#75992]
BPO | [31811](https://bugs.python.org/issue31811)
--- | :---
Nosy | @vstinner, @1st1, @tomfloyer
PRs | <li>python/cpython#4140</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.17:31:51.712>
created_at = <Date 2017-10-18.15:32:02.998>
labels = ['type-feature', '3.7', 'docs']
title = 'async and await missing from keyword list in lexical analysis doc'
updated_at = <Date 2017-11-08.17:43:42.637>
user = 'https://bugs.python.org/ColinDunklau'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.17:43:42.637>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-08.17:31:51.712>
closer = 'yselivanov'
components = ['Documentation']
creation = <Date 2017-10-18.15:32:02.998>
creator = 'Colin Dunklau'
dependencies = []
files = []
hgrepos = []
issue_num = 31811
keywords = ['patch']
message_count = 7.0
messages = ['304583', '304618', '304672', '304686', '304687', '305077', '305885']
nosy_count = 6.0
nosy_names = ['vstinner', 'docs@python', 'yselivanov', 'Colin Dunklau', 'F. Lamar', 'tomfloyer']
pr_nums = ['4140']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31811'
versions = ['Python 3.7']
```

</p></details>

**Comment by fce6aa28-f7e2-4802-a520-563f240dbc1b** [comment]
I see that code making async/await real keywords has been merged, but it looks like [Doc/reference/lexical_analysis.rst](https://github.com/python/cpython/blob/main/Doc/reference/lexical_analysis.rst) doesn't have those added
https://github.com/python/cpython/blob/4a2d00c/Doc/reference/lexical_analysis.rst#keywords            

Is that list autogenerated somehow or was it just overlooked?

**Comment by 484a35a6-5f9e-4d9c-9594-198f4e291210** [comment]
I a new contributor. This seems like a simple fix. I'd be happy to work on it. I will submit ar PR on or before 10-22-17

**Comment by 1st1** [comment]
They are covered here: https://github.com/python/cpython/blob/4a2d00cb4525fcb3209f04531472ba6a359ed418/Doc/reference/compound_stmts.rst#coroutines

**Comment by fce6aa28-f7e2-4802-a520-563f240dbc1b** [comment]
Hi Yury, perhaps I've misinterpreted PEP-492, and I can't claim to understand how the parser works and thus how the changes in https://github.com/python/cpython/pull/1669 affect things, but it seems to me that async and await are truly reserved words now, not just only reserved in certain contexts. If that's true, shouldn't they also appear in the list in the lexical analysis doc?

I'd appreciate any clarification you (or anyone else) can offer.

**Comment by 1st1** [comment]
Ah, you mean this list: https://docs.python.org/3/reference/lexical_analysis.html#keywords ?

Your original link was a bit hard to read as it shows rest markup and not the actual list of keywords.  So I missed it, sorry.

I'll reopen the issue, please feel free to submit a PR!

**Comment by 46a704e8-fbfe-42f9-a056-1c751da65c84** [comment]
I've added those keywords to documentation master branch.

**Comment by vstinner** [comment]
The final commit uses the wrong bpo number:

New changeset bf9d317626eebcf79bd0756b4dd43df82d5cc186 by Yury Selivanov (Tom Floyer) in branch 'master':
bpo-31810: added missing keywords to docs. (bpo-4140)
https://github.com/python/cpython/commit/bf9d317626eebcf79bd0756b4dd43df82d5cc186
