### ISSUE TITLE
Travis CI, buildbots: run "make smelly" to check if CPython leaks symbols

### ISSUE THREAD

**Issue by vstinner** [python/cpython#75991]
BPO | [31810](https://bugs.python.org/issue31810)
--- | :---
Nosy | @vstinner, @taleinat, @ned-deily, @zware, @1st1, @CuriousLearner
PRs | <li>python/cpython#4054</li><li>python/cpython#4057</li><li>python/cpython#4140</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-24.09:15:51.323>
created_at = <Date 2017-10-18.15:22:59.036>
labels = ['3.7', 'tests']
title = 'Travis CI, buildbots: run "make smelly" to check if CPython leaks symbols'
updated_at = <Date 2017-11-08.17:31:33.755>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.17:31:33.755>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-24.09:15:51.323>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-18.15:22:59.036>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31810
keywords = ['patch', 'buildbot']
message_count = 6.0
messages = ['304582', '304632', '304634', '304871', '304880', '305883']
nosy_count = 6.0
nosy_names = ['vstinner', 'taleinat', 'ned.deily', 'zach.ware', 'yselivanov', 'CuriousLearner']
pr_nums = ['4054', '4057', '4140']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31810'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Recently, a new "cell_set_contents()" public symbol was added by mistake: see bpo-30486. It was quickly noticed by doko, and fixed by me (commit 0ad05c32cc41d4c21bfd78b9ffead519ead475a2).

The problem is that we already have a "make smelly" command to check if Python "leaks" symbols, but this check is not run on our CIs (Travis CI or buildbots).

It would be nice to run automatically this test.

**Comment by CuriousLearner** [comment]
Hi Haypo,

I'd like to work on a patch for this issue.

Can you please guide me how the tests are configured for buildbots?

**Comment by vstinner** [comment]
Sanyam: please first try to write a change for Travis CI: modify
.travis.yml, create a PR and check if it works.

**Comment by vstinner** [comment]
New changeset 87d332dcdbffe8ff60d99f74b1ad241c0967b055 by Victor Stinner in branch 'master':
bpo-31810: Add smelly.py to check exported symbols (bpo-4057)
https://github.com/python/cpython/commit/87d332dcdbffe8ff60d99f74b1ad241c0967b055

**Comment by vstinner** [comment]
"make smelly" is now run on Travis CI.

**Comment by 1st1** [comment]
New changeset bf9d317626eebcf79bd0756b4dd43df82d5cc186 by Yury Selivanov (Tom Floyer) in branch 'master':
bpo-31810: added missing keywords to docs. (bpo-4140)
https://github.com/python/cpython/commit/bf9d317626eebcf79bd0756b4dd43df82d5cc186
