### ISSUE TITLE
python -m ensurepip hangs

### ISSUE THREAD

**Issue by 4ee349e0-3075-45f2-a267-516aef8641be** [python/cpython#75994]
BPO | [31813](https://bugs.python.org/issue31813)
--- | :---
Nosy | @yan12125, @tonybaloney
Files | <li>[S71018-182104.jpg](https://bugs.python.org/file47226/S71018-182104.jpg "Uploaded as image/jpeg at 2017-10-18.15:42:58 by Serhy Pyton"): screenshot</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-06.17:40:24.352>
created_at = <Date 2017-10-18.15:42:58.250>
labels = ['invalid', 'type-bug', 'expert-installation']
title = 'python -m ensurepip hangs'
updated_at = <Date 2019-05-06.17:40:24.351>
user = 'https://bugs.python.org/SerhyPyton'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-06.17:40:24.351>
actor = 'anthonypjshaw'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-06.17:40:24.352>
closer = 'anthonypjshaw'
components = ['Installation']
creation = <Date 2017-10-18.15:42:58.250>
creator = 'Serhy Pyton'
dependencies = []
files = ['47226']
hgrepos = []
issue_num = 31813
keywords = []
message_count = 3.0
messages = ['304585', '304603', '341575']
nosy_count = 3.0
nosy_names = ['yan12125', 'anthonypjshaw', 'Serhy Pyton']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31813'
versions = ['Python 3.6']
```

</p></details>

**Comment by 4ee349e0-3075-45f2-a267-516aef8641be** [comment]
pip stucks, during installing python 3.6.3 in termux and not complete it. Posibly it's could be a problem only on meizu m2. Also it produse load in such state.

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
Might be caused by this bug: https://github.com/pypa/pip/issues/3532

pip uses lockfile, and lockfile uses hard links, which are prohibited on newer Android versions unless you're root. A workaround is configuring python with |./configure --without-ensurepip|.
