### ISSUE TITLE
Compilation Error with Python 3.6.1/3.6.3 with Tkinter

### ISSUE THREAD

**Issue by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [python/cpython#75998]
BPO | [31817](https://bugs.python.org/issue31817)
--- | :---
Nosy | @ned-deily, @jpc2350, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-30.16:51:17.463>
created_at = <Date 2017-10-19.10:07:54.917>
labels = ['build', 'expert-tkinter']
title = 'Compilation Error with Python 3.6.1/3.6.3 with Tkinter'
updated_at = <Date 2022-01-30.16:51:17.463>
user = 'https://github.com/jpc2350'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-30.16:51:17.463>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-30.16:51:17.463>
closer = 'iritkatriel'
components = ['Tkinter']
creation = <Date 2017-10-19.10:07:54.917>
creator = 'jpc2350'
dependencies = []
files = []
hgrepos = []
issue_num = 31817
keywords = []
message_count = 14.0
messages = ['304612', '304675', '304676', '304788', '305431', '305472', '306272', '307118', '314638', '316385', '319861', '370284', '370289', '411150']
nosy_count = 5.0
nosy_names = ['ned.deily', 'jpc2350', 'dplusplus', 'iritkatriel', 'zhang']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31817'
versions = ['Python 3.6']
```

</p></details>

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
Hi Guys,

I'm trying to build Python 3.6.1 and 3.6.3, with both, .configure / make / make install work correctly as they should, however, trying to import \_tkinter doesn't work.

Going back to the compilation, I get the following error in the make log:

*** WARNING: renaming "\_tkinter" since importing it failed: build/lib.linux-x86_64-3.6/_tkinter.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Tcl_GetCharLength

Following modules built successfully but were removed because they could not be imported:
\_tkinter


Any Idea's on how to fix the undefined symbol error? This happens with both Tcl/Tk 8.6.6 and 8.6.7.

The following is the configure options:
--prefix=/tools/apps/python/3.6.1 --with-tcltk-includes='-I/tools/apps/Tcl/8.6.7/include -I/tools/apps/Tk/8.6.7/include' --with-tcltk-libs='-L/tools/apps/Tcl/8.6.7/lib -L/tools/apps/Tk/8.6.7/lib' --enable-optimizations --enable-shared

**Comment by ned-deily** [comment]
You may need to set LD_LIBRARY_PATH env variable to point to your Tcl and Tk libraries or, better, add an rpath entry to LDFLAGS.

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
Hi Ned,

LD_LIBRARY_PATH has been set with the lib paths for both, like I said the
module itself builds, I’ll add the module build logs later but the module
try’s to get loaded before the tests which unfortunately gives the error
undefined symbol: Tcl_GetCharLength

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
Hi Ned,

Please see the make logs for \_tkinter below:

building '\_tkinter' extension
gcc -pthread -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -fprofile-generate -DWITH_APPINIT=1 -I./Include -I. -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/tools/src/Python-3.6.3/Include -I/tools/src/Python-3.6.3 -c /tools/src/Python-3.6.3/Modules/_tkinter.c -o build/temp.linux-x86_64-3.6/tools/src/Python-3.6.3/Modules/_tkinter.o -I/tools/apps/tcl/8.6.7/include -I/tools/apps/tk/8.6.7/include
gcc -pthread -fPIC -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -fprofile-generate -DWITH_APPINIT=1 -I./Include -I. -I/usr/include/x86_64-linux-gnu -I/usr/local/include -I/tools/src/Python-3.6.3/Include -I/tools/src/Python-3.6.3 -c /tools/src/Python-3.6.3/Modules/tkappinit.c -o build/temp.linux-x86_64-3.6/tools/src/Python-3.6.3/Modules/tkappinit.o -I/tools/apps/tcl/8.6.7/include -I/tools/apps/tk/8.6.7/include
gcc -pthread -shared -fprofile-generate -fprofile-generate build/temp.linux-x86_64-3.6/tools/src/Python-3.6.3/Modules/_tkinter.o build/temp.linux-x86_64-3.6/tools/src/Python-3.6.3/Modules/tkappinit.o -L. -L/usr/lib/x86_64-linux-gnu -L/usr/local/lib -lpython3.6m -o build/lib.linux-x86_64-3.6/_tkinter.cpython-36m-x86_64-linux-gnu.so -L/tools/apps/tcl/8.6.7/lib -L/tools/apps/tk/8.6.7/lib

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
LD_LIBRARY_PATH includes /tools/apps/tk/8.6.7/lib/:/tools/apps/tcl/8.6.7/lib/
and several other library paths that are required. 

Why would I be getting an undefined symbol error on this module?
\_tkinter.cpython-36m-x86_64-linux-gnu.so: undefined symbol: Tcl_GetCharLength

I've even tried added g++ as an option, but Python fails to be against this: bpo-23644

I'm stuck now, and this is causing real problems for some pipelines that I'm trying to get running.

**Comment by ned-deily** [comment]
Josh, sorry I don't have any further ideas off the top of my head and I likely won't have time for several weeks to try to reproduce this myself.  Have you tried renaming the \_tkinter extension back, doing a "make install", and seeing whether it imports properly from the installed python?

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
Hi Ned,

Tried that but unfortunately it didn't work. It still produces an error within the make install function which then re-removes the module - it does however create a folder called tkinter.

**Comment by 263b5680-bd15-4524-9bd5-dfb6bab4ee9b** [comment]
Hi Ned,

I've built a new machine, tried the build again using Tk and Tcl shared libraries, built Python-3.6.3 and it's still not worked.

The [Python/3.6.3-foss-2017b/lib/python3.6/tkinter](https://github.com/python/cpython/blob/main/Python/3.6.3-foss-2017b/lib/python3.6/tkinter) folder gets created and populated with several files, but when you try and import tkinter in python, it fails to import with:

```pycon
>>> import tkinter
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tools/apps/Python/3.6.3-foss-2017b/lib/python3.6/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```


Running \_\_init__.py from the tkinter folder produces this output:

```pytb
Traceback (most recent call last):
  File "__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'
```


I'm guessing something is failing to build correctly but it's not being logged.

Both Tk and Tcl versions 8.6.6 and 8.6.7 are available and working on the system.
