### ISSUE TITLE
subprocess_fork_exec more stable with vfork

### ISSUE THREAD

**Issue by bf28a09e-6d72-4c82-a4b1-8cc669e32358** [python/cpython#75995]
BPO | [31814](https://bugs.python.org/issue31814)
--- | :---
Nosy | @gpshead, @ambv, @albertz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2018-04-04.07:13:55.224>
created_at = <Date 2017-10-18.16:24:24.027>
labels = ['extension-modules', 'type-feature', '3.8']
title = 'subprocess_fork_exec more stable with vfork'
updated_at = <Date 2018-04-04.07:13:55.223>
user = 'https://github.com/albertz'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-04.07:13:55.223>
actor = 'gregory.p.smith'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2018-04-04.07:13:55.224>
closer = 'gregory.p.smith'
components = ['Extension Modules']
creation = <Date 2017-10-18.16:24:24.027>
creator = 'Albert.Zeyer'
dependencies = []
files = []
hgrepos = []
issue_num = 31814
keywords = []
message_count = 6.0
messages = ['304587', '304613', '304653', '304677', '314844', '314928']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'lukasz.langa', 'Albert.Zeyer']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31814'
versions = ['Python 3.8']
```

</p></details>

**Comment by bf28a09e-6d72-4c82-a4b1-8cc669e32358** [comment]
subprocess_fork_exec currently calls fork().

I propose to use vfork() or posix_spawn() or syscall(SYS_clone, SIGCHLD, 0) instead if possible and if there is no preexec_fn. The difference would be that fork() will call any atfork handlers (registered via pthread_atfork()), while the suggested calls would not.

There are cases where atfork handlers are registered which are not save to be called e.g. in multi-threaded environments. In the case of subprocess_fork_exec without preexec_fn, there is no need to call those atfork handlers, so avoiding this could avoid potential problems. It's maybe acceptable if a pure fork() without exec() doesn't work in this case anymore, but there is no reason that a fork()+exec() should not work in any such cases. This is fixed by my proposed solution.

An example case is OpenBlas and OpenMP, which registers an atfork handler which is safe to be called if there are other threads running.
See here:
https://github.com/tensorflow/tensorflow/issues/13802
https://github.com/xianyi/OpenBLAS/issues/240
https://trac.sagemath.org/ticket/22021

About fork+exec without the atfork handlers, see here for alternatives (like vfork):
https://stackoverflow.com/questions/46810597/forkexec-without-atfork-handlers/

**Comment by bf28a09e-6d72-4c82-a4b1-8cc669e32358** [comment]
This is a related issue, although with different argumentation:
https://bugs.python.org/issue20104

**Comment by bf28a09e-6d72-4c82-a4b1-8cc669e32358** [comment]
Here is some more background for a case where this occurs:
https://stackoverflow.com/questions/46849566/multi-threaded-openblas-and-spawning-subprocesses

My proposal here would fix this.

**Comment by gpshead** [comment]
Using new syscalls for \_posixsubprocess.c would be a feature so it would be limited to 3.7+ if done at all.

My gut feeling is that the real bug is in \*any* library code that uses pthread_atfork() in a non thread safe manner.  That code is fundamentally broken as it is placing a burden upon the entire application that it lives within that the application and no other libraries may use threads or if it does that it may not launch subprocesses.

That is unrealistic.  So I'd blame OpenBlas and OpenMP.

Supporting alternate system calls seems like it would just paper over the issue of improper use of pthread_atfork rather than address the fundamental problem.
