### ISSUE TITLE
Document that urllib.parse.{Defrag,Split,Parse}Result are namedtuples

### ISSUE THREAD

**Issue by ffb7c71b-4f64-4d94-95a7-91bbba845748** [python/cpython#76003]
BPO | [31822](https://bugs.python.org/issue31822)
--- | :---
Nosy | @freddrake, @vapier, @merwok, @serhiy-storchaka, @lisroach, @csabella
PRs | <li>python/cpython#4434</li><li>python/cpython#12528</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/lisroach'
closed_at = <Date 2019-03-24.22:07:59.798>
created_at = <Date 2017-10-19.18:54:33.035>
labels = ['easy', '3.8', 'type-feature', '3.7', 'docs']
title = 'Document that urllib.parse.{Defrag,Split,Parse}Result are namedtuples'
updated_at = <Date 2019-03-24.22:07:59.793>
user = 'https://bugs.python.org/AllenLi'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-24.22:07:59.793>
actor = 'cheryl.sabella'
assignee = 'lisroach'
closed = True
closed_date = <Date 2019-03-24.22:07:59.798>
closer = 'cheryl.sabella'
components = ['Documentation']
creation = <Date 2017-10-19.18:54:33.035>
creator = 'Allen Li'
dependencies = []
files = []
hgrepos = []
issue_num = 31822
keywords = ['patch', 'easy']
message_count = 9.0
messages = ['304637', '304638', '304832', '304833', '338645', '338646', '338756', '338761', '338763']
nosy_count = 8.0
nosy_names = ['fdrake', 'vapier', 'eric.araujo', 'docs@python', 'serhiy.storchaka', 'lisroach', 'cheryl.sabella', 'Allen Li']
pr_nums = ['4434', '12528']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31822'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ffb7c71b-4f64-4d94-95a7-91bbba845748** [comment]
It would be useful to document that urllib.parse.{Defrag,Split,Parse}Result are namedtuples, and make that API officially public if it was not otherwise.

These classes are implemented as namedtuples in Python 2 and 3, and I am not aware of a reason that that would need to change in the future.

In particular, the namedtuple \_replace() method is very useful for modifying parts of a URL, a common use case.

```py
 u = urllib.parse.urlsplit(some_url)
 u = u._replace(netloc=other_netloc)
 urllib.parse.urlunsplit(u)

 # Alternatives not depending on namedtuple API
 parts = list(u)
 parts[1] = other_netloc  # Using a magic index
 urllib.parse.urlunsplit(u)

 u = urllib.parse.SplitResult(  # Very ugly
     scheme=u.scheme,
     netloc=other_netloc,
     path=u.path,
     query=u.query,
     fragment=u.fragment)
```

**Comment by 78906f6c-39e2-41fc-95f0-75f9ad94bffc** [comment]
specifically, the docs for these classes:
https://docs.python.org/2/library/urlparse.html#results-of-urlparse-and-urlsplit
https://docs.python.org/3/library/urllib.parse.html#urlparse-result-object

> The result objects from the urlparse() and urlsplit() functions are subclasses
> of the tuple type. These subclasses add the attributes described in those
> functions, as well as provide an additional method:
> ...
> class urlparse.SplitResult(scheme, netloc, path, query, fragment)
>   Concrete class for urlsplit() results.

changing "subclasses of the tuple type" to "subclasses of collections.namedtuples" would be great.  also adding hints to use \_replace to update values would be great :).

**Comment by serhiy-storchaka** [comment]
collections.namedtuples is not a class.

**Comment by merwok** [comment]
I suggest using :term:\`named tuple\` for the link (+ an example of using \_replace as Mike said)
