### ISSUE TITLE
bytes decode raises OverflowError desipte errors='ignore'

### ISSUE THREAD

**Issue by 2d3cbf98-27bf-469e-b52d-bd6439866795** [python/cpython#76006]
BPO | [31825](https://bugs.python.org/issue31825)
--- | :---
Nosy | @vstinner, @ericvsmith, @ezio-melotti, @serhiy-storchaka, @Naitbit
PRs | <li>python/cpython#4058</li><li>python/cpython#4059</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-10-20.14:42:35.636>
created_at = <Date 2017-10-20.09:58:20.153>
labels = ['interpreter-core', 'type-bug', '3.7', 'expert-unicode']
title = "bytes decode raises OverflowError desipte errors='ignore'"
updated_at = <Date 2017-10-20.14:42:35.635>
user = 'https://github.com/Naitbit'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-20.14:42:35.635>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-10-20.14:42:35.636>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Unicode']
creation = <Date 2017-10-20.09:58:20.153>
creator = 'Naitbit'
dependencies = []
files = []
hgrepos = []
issue_num = 31825
keywords = ['patch']
message_count = 4.0
messages = ['304651', '304656', '304658', '304659']
nosy_count = 5.0
nosy_names = ['vstinner', 'eric.smith', 'ezio.melotti', 'serhiy.storchaka', 'Naitbit']
pr_nums = ['4058', '4059']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31825'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 2d3cbf98-27bf-469e-b52d-bd6439866795** [comment]
In Python 3.5 and earlier (tested 3.5.3 and 2.7.13)
b'\\\\\\xfa'.decode('unicode-escape', errors='ignore')
did return '\\\\ú'

but in Python 3.6 it raises 
OverflowError: decoding with 'unicode-escape' codec failed (OverflowError: character argument not in range(0x110000))


Python 3.6.1 (default, Sep  7 2017, 16:36:03) 
[GCC 6.3.0 20170406] on linux

**Comment by serhiy-storchaka** [comment]
New changeset 56cb465cc93dcb35aaf7266ca3dbe2dcff1fac5f by Serhiy Storchaka in branch 'master':
bpo-31825: Fixed OverflowError in the 'unicode-escape' codec (bpo-4058)
https://github.com/python/cpython/commit/56cb465cc93dcb35aaf7266ca3dbe2dcff1fac5f

**Comment by serhiy-storchaka** [comment]
New changeset 1e78ed6825701029aa45a68f9e62dd3bb8d4e928 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
bpo-31825: Fixed OverflowError in the 'unicode-escape' codec (GH-4058) (bpo-4059)
https://github.com/python/cpython/commit/1e78ed6825701029aa45a68f9e62dd3bb8d4e928

**Comment by serhiy-storchaka** [comment]
Thank you for your report Sebastian.
