### ISSUE TITLE
Add sock_recv_into to AbstractEventLoop

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76000]
BPO | [31819](https://bugs.python.org/issue31819)
--- | :---
Nosy | @gvanrossum, @pitrou, @vstinner, @giampaolo, @1st1
PRs | <li>python/cpython#4051</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-19.19:47:17.426>
created_at = <Date 2017-10-19.17:37:49.742>
labels = ['3.7', 'type-feature', 'library', 'expert-asyncio']
title = 'Add sock_recv_into to AbstractEventLoop'
updated_at = <Date 2020-08-05.00:10:19.610>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-05.00:10:19.610>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-19.19:47:17.426>
closer = 'yselivanov'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-10-19.17:37:49.742>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 31819
keywords = ['patch']
message_count = 6.0
messages = ['304623', '304629', '304639', '304640', '304641', '374761']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'pitrou', 'vstinner', 'giampaolo.rodola', 'yselivanov']
pr_nums = ['4051']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31819'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
As sock_recv() is already exposed, it is a no-brainer to add sock_recv_into(), allowing finer buffer management when people are willing to handle a socket object.

**Comment by 1st1** [comment]
I'm going to approve this unless there are any objections.

**Comment by gvanrossum** [comment]
SGTM.

**Comment by 1st1** [comment]
New changeset 525f40d231aba2c004619fc7a5207171ed65b0cb by Yury Selivanov (Antoine Pitrou) in branch 'master':
bpo-31819: Add AbstractEventLoop.sock_recv_into() (bpo-4051)
https://github.com/python/cpython/commit/525f40d231aba2c004619fc7a5207171ed65b0cb

**Comment by 1st1** [comment]
Merged. Thank you, Antoine!
