### ISSUE TITLE
Missing default argument detail in documentation of StreamReaderWriter

### ISSUE THREAD

**Issue by 11e00218-75e8-4220-b358-d5ac5eb84bdb** [python/cpython#76005]
BPO | [31824](https://bugs.python.org/issue31824)
--- | :---
Nosy | @berkerpeksag, @pablogsal
PRs | <li>python/cpython#4328</li><li>python/cpython#4367</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-10.23:14:37.429>
created_at = <Date 2017-10-19.23:17:42.386>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = 'Missing default argument detail in documentation of StreamReaderWriter'
updated_at = <Date 2017-11-10.23:14:37.428>
user = 'https://bugs.python.org/PeterLovett'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-10.23:14:37.428>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-10.23:14:37.429>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-10-19.23:17:42.386>
creator = 'PeterLovett'
dependencies = []
files = []
hgrepos = []
issue_num = 31824
keywords = ['patch', 'easy']
message_count = 7.0
messages = ['304646', '305793', '305856', '306051', '306055', '306057', '306058']
nosy_count = 4.0
nosy_names = ['PeterLovett', 'docs@python', 'berker.peksag', 'pablogsal']
pr_nums = ['4328', '4367']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31824'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 11e00218-75e8-4220-b358-d5ac5eb84bdb** [comment]
Documentation of StreamReaderWriter at
https://docs.python.org/3/library/codecs.html#codecs.StreamReaderWriter
section 7.2.1.4.3 is missing the default value on the errors argument.

Should change from:
class codecs.StreamReaderWriter(stream, Reader, Writer, errors)
to be:
class codecs.StreamReaderWriter(stream, Reader, Writer, errors='strict')

**Comment by berkerpeksag** [comment]
For those who want to work on this issue: codecs.StreamReaderWriter documentation is located at [Doc/library/codecs.rst](https://github.com/python/cpython/blob/main/Doc/library/codecs.rst).

**Comment by berkerpeksag** [comment]
Thanks for the PR, Pablo. I think we can make the same change to StreamRecoder documentation too: https://docs.python.org/3/library/codecs.html#codecs.StreamRecoder

**Comment by pablogsal** [comment]
I have updated the PR with the requested changes.

**Comment by berkerpeksag** [comment]
New changeset e184cfd7bf8bcfd160e3b611d4351ca3ce52d9e2 by Berker Peksag (Pablo Galindo) in branch 'master':
bpo-31824: Document default value of 'errors' parameters (GH-4328)
https://github.com/python/cpython/commit/e184cfd7bf8bcfd160e3b611d4351ca3ce52d9e2

**Comment by berkerpeksag** [comment]
New changeset 7abbddd88d4debe75b201145b6212afb7d93c457 by Berker Peksag (Miss Islington (bot)) in branch '3.6':
bpo-31824: Document default value of 'errors' parameters (GH-4328)
https://github.com/python/cpython/commit/7abbddd88d4debe75b201145b6212afb7d93c457

**Comment by berkerpeksag** [comment]
Thank you, Peter and Pablo.
