### ISSUE TITLE
asyncio.create_subprocess_exec doesn't capture all stdout output

### ISSUE THREAD

**Issue by 6ea92ce1-f803-4b34-ad43-602698be00d6** [python/cpython#76011]
BPO | [31830](https://bugs.python.org/issue31830)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[show.py](https://bugs.python.org/file47228/show.py "Uploaded as text/plain at 2017-10-20.20:59:08 by cannedrag")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-20.20:59:08.492>
labels = ['3.8', 'type-bug', '3.7', 'expert-asyncio']
title = "asyncio.create_subprocess_exec doesn't capture all stdout output"
updated_at = <Date 2018-07-26.13:40:08.686>
user = 'https://bugs.python.org/cannedrag'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-26.13:40:08.686>
actor = 'apatrushev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2017-10-20.20:59:08.492>
creator = 'cannedrag'
dependencies = []
files = ['47228']
hgrepos = []
issue_num = 31830
keywords = []
message_count = 1.0
messages = ['322422']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'apatrushev', 'cannedrag']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31830'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
I'll close as per the comment https://github.com/python/cpython/issues/76011#issuecomment-1093762548 and since the script is not runnable as is. If this still exists, provide a minimal reproducer and this can be reopened.
