### ISSUE TITLE
EmailMessage.add_attachment(filename="long or spécial") crashes or produces invalid output

### ISSUE THREAD

**Issue by da1215aa-4d96-4aa0-8b34-a35aaa37c8f7** [python/cpython#76012]
BPO | [31831](https://bugs.python.org/issue31831)
--- | :---
Nosy | @warsaw, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-04.00:51:27.798>
created_at = <Date 2017-10-20.22:22:56.917>
labels = ['type-bug', '3.7', 'expert-email']
title = 'EmailMessage.add_attachment(filename="long or sp\xc3\xa9cial") crashes or produces invalid output'
updated_at = <Date 2017-12-04.00:51:27.795>
user = 'https://bugs.python.org/calimeroteknik'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-04.00:51:27.795>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-12-04.00:51:27.798>
closer = 'r.david.murray'
components = ['email']
creation = <Date 2017-10-20.22:22:56.917>
creator = 'calimeroteknik'
dependencies = []
files = []
hgrepos = []
issue_num = 31831
keywords = []
message_count = 8.0
messages = ['304684', '304685', '304691', '304705', '304706', '304726', '304756', '307532']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'calimeroteknik']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31831'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by da1215aa-4d96-4aa0-8b34-a35aaa37c8f7** [comment]
Erratum: the output generated by python 3.5 and 3.4 causes line wraps in the SMTP delivery chain, which cause exactly the same breakage as ulterior versions: the crucially needed indendation of one space ends up being absent.

**Comment by bitdancer** [comment]
You are correct, that is a bug.  Presumably I forgot to check for non-ascii when the parameter value doesn't need to be folded.  I'm not sure when I'll have time to look at this, unfortunately :(.  If you can see how to fix it, you could submit a PR against my PR branch, I think.

**Comment by bitdancer** [comment]
Great, thank you for that research.  And yes, that's exactly why \_\_str__ uses utf8=True, the "picture" of the message is much more readable.  I will commit that PR soon.
