### ISSUE TITLE
Compile fail on gentoo for MIPS CPU of loongson 2f

### ISSUE THREAD

**Issue by abe8e52d-383c-4356-851d-634b641b2728** [python/cpython#76014]
BPO | [31833](https://bugs.python.org/issue31833)
--- | :---
Nosy | @pitrou, @emtone
Files | <li>[python_strace.txt](https://bugs.python.org/file47231/python_strace.txt "Uploaded as text/plain at 2017-10-23.15:58:27 by @emtone")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-23.15:59:37.516>
created_at = <Date 2017-10-21.04:32:22.627>
labels = ['extension-modules', 'build']
title = 'Compile fail on gentoo for MIPS CPU of loongson 2f'
updated_at = <Date 2017-10-23.16:11:36.825>
user = 'https://github.com/emtone'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-23.16:11:36.825>
actor = 'emtone'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-23.15:59:37.516>
closer = 'pitrou'
components = ['Extension Modules']
creation = <Date 2017-10-21.04:32:22.627>
creator = 'emtone'
dependencies = []
files = ['47231']
hgrepos = []
issue_num = 31833
keywords = []
message_count = 5.0
messages = ['304695', '304772', '304814', '304815', '304819']
nosy_count = 2.0
nosy_names = ['pitrou', 'emtone']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31833'
versions = ['Python 2.7']
```

</p></details>

**Comment by abe8e52d-383c-4356-851d-634b641b2728** [comment]
Here is the error message:
building '\_multiprocessing' extension
creating
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing
mips64el-unknown-linux-gnu-gcc -pthread -fPIC -fno-strict-aliasing -O2
-march=loongson2f -Wa,-mfix-loongson2f-nop -pipe -fwrapv -DNDEBUG
-IModules/_multiprocessing -I. -IInclude -I/usr/local/include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/mips64el-unknown-linux-gnu
-c /var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/multiprocessing.c
-o
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/multiprocessing.o
mips64el-unknown-linux-gnu-gcc -pthread -fPIC -fno-strict-aliasing -O2
-march=loongson2f -Wa,-mfix-loongson2f-nop -pipe -fwrapv -DNDEBUG
-IModules/_multiprocessing -I. -IInclude -I/usr/local/include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/mips64el-unknown-linux-gnu
-c /var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/socket_connection.c
-o
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/socket_connection.o
mips64el-unknown-linux-gnu-gcc -pthread -fPIC -fno-strict-aliasing -O2
-march=loongson2f -Wa,-mfix-loongson2f-nop -pipe -fwrapv -DNDEBUG
-IModules/_multiprocessing -I. -IInclude -I/usr/local/include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Include
-I/var/tmp/portage/dev-lang/python-2.7.12/work/mips64el-unknown-linux-gnu
-c /var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/semaphore.c
-o
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/semaphore.o
mips64el-unknown-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,--as-needed
-L. -Wl,-O1 -Wl,--as-needed -L. -fno-strict-aliasing -O2
-march=loongson2f -Wa,-mfix-loongson2f-nop -pipe -fwrapv -DNDEBUG -I.
-IInclude
-I/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Include
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/multiprocessing.o
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/socket_connection.o
build/temp.linux-mips64-2.7/var/tmp/portage/dev-lang/python-2.7.12/work/Python-2.7.12/Modules/_multiprocessing/semaphore.o
-L. -lpython2.7 -o build/lib.linux-mips64-2.7/_multiprocessing.so ***
WARNING: importing extension "\_multiprocessing" failed with \<type
'exceptions.OSError'\>: [Errno 89] Function not implemented

**Comment by pitrou** [comment]
You should try running with strace to see which system call failed:

```sh
$ strace ./python -c "import _multiprocessing"
```

**Comment by abe8e52d-383c-4356-851d-634b641b2728** [comment]
I update the Python to 2.7.14 and It's Compile success.

Here is running the command with strace:
yeeloong /home/gentoo # python --version
Python 2.7.14
yeeloong /home/gentoo # strace -o ./python_strace.txt python -c "import
\_multiprocessing"

**Comment by pitrou** [comment]
If it works with 2.7.14 then we can just close this issue.

**Comment by abe8e52d-383c-4356-851d-634b641b2728** [comment]
OK, Thank you pitrou!
