### ISSUE TITLE
Error in 3.6.3 epub docs

### ISSUE THREAD

**Issue by 31ec7cc3-49c0-419a-97ef-c96df8ce8930** [python/cpython#76027]
BPO | [31846](https://bugs.python.org/issue31846)
--- | :---
Nosy | @n8henrie

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-23.12:46:04.663>
labels = []
title = 'Error in 3.6.3 epub docs'
updated_at = <Date 2017-10-23.12:46:04.663>
user = 'https://github.com/n8henrie'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-23.12:46:04.663>
actor = 'n8henrie'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-10-23.12:46:04.663>
creator = 'n8henrie'
dependencies = []
files = []
hgrepos = []
issue_num = 31846
keywords = []
message_count = 1.0
messages = ['304799']
nosy_count = 1.0
nosy_names = ['n8henrie']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue31846'
versions = ['Python 3.6']
```

</p></details>

**Comment by 31ec7cc3-49c0-419a-97ef-c96df8ce8930** [comment]
I routinely download the epub version of the docs to my computer and mobile devices as an offline copy. The 3.6.3 version reports a big error on the first (and many other pages):

> This page contains the following errors:
error on line 5176 at column 11: Entity 'copy' not defined
Below is a rendering of the page up to the first error.

Numerous similar errors reporting `Entity 'copy' not defined` scattered throughout the epub.

Wonder if this was introduced by the change to `conf.py` that fixed the recent problem of the 404s with the HTML docs.

**Comment by kumaraditya303** [comment]
Python 3.6 is not supported anymore so closing. If this error exists in other supported versions, you can create a new issue.
