### ISSUE TITLE
HTMLParser: undocumented not implemented method

### ISSUE THREAD

**Issue by b485b51b-d27f-423a-8035-c9ad55e98281** [python/cpython#76025]
BPO | [31844](https://bugs.python.org/issue31844)
--- | :---
Nosy | @srittau, @ezio-melotti, @berkerpeksag, @csabella
PRs | <li>python/cpython#8562</li><li>python/cpython#21504</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ezio-melotti'
closed_at = <Date 2020-07-16.06:39:25.857>
created_at = <Date 2017-10-23.08:27:23.318>
labels = ['type-bug', 'library', '3.10']
title = 'HTMLParser: undocumented not implemented method'
updated_at = <Date 2020-07-16.06:39:25.857>
user = 'https://github.com/srittau'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-16.06:39:25.857>
actor = 'berker.peksag'
assignee = 'ezio.melotti'
closed = True
closed_date = <Date 2020-07-16.06:39:25.857>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-10-23.08:27:23.318>
creator = 'srittau'
dependencies = []
files = []
hgrepos = []
issue_num = 31844
keywords = ['patch']
message_count = 10.0
messages = ['304782', '304783', '305303', '305306', '322662', '322672', '323968', '371500', '373745', '373746']
nosy_count = 5.0
nosy_names = ['srittau', 'ezio.melotti', 'berker.peksag', 'cheryl.sabella', 'William Ayd']
pr_nums = ['8562', '21504']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31844'
versions = ['Python 3.10']
```

</p></details>

**Comment by b485b51b-d27f-423a-8035-c9ad55e98281** [comment]
HTMLParser derives from \_markupbase.ParserBase, which has the following method:

```py
class HTMLParser:
```


    ...

```py
    def error(self, message):
        raise NotImplementedError(
            "subclasses of ParserBase must override error()")
```


HTMLParser does not implement this method and the documentation for HTMLParser (https://docs.python.org/3.6/library/html.parser.html) does not mention that its sub-classes need to override it.

I am not sure whether this is a documentation omission, whether HTMLParser should provide an (empty?) implementation, or whether ParserBase should not raise a NotImplementedError (to make linters happy).

**Comment by b485b51b-d27f-423a-8035-c9ad55e98281** [comment]
The quoted code above should have used ParserBase:

```py
class ParserBase:
```


    ...

```py
    def error(self, message):
        raise NotImplementedError(
            "subclasses of ParserBase must override error()")
```

**Comment by c8351d6c-1112-44bf-9f85-f91f82be8bbe** [comment]
Would we be open to setting the meta class of the ParserBase to ABCMeta and setting error as an abstract method? That at the very least would make the expectation clearer for subclasses. 

I haven’t contributed to Python before but am open to this as a first attempt if the direction makes sense.

**Comment by c8351d6c-1112-44bf-9f85-f91f82be8bbe** [comment]
And assuming that subclass requirement is intentional we could add an optional keyword argument to the HTMLParser that indicates what to do with errors, much like how encoding issues are handled within codecs. For backwards compatibility it can default to ignore, but fail and warn could be two alternate approaches that the error method could account for
