### ISSUE TITLE
sqlite3.connect() should accept PathLike objects

### ISSUE THREAD

**Issue by ffb7c71b-4f64-4d94-95a7-91bbba845748** [python/cpython#76024]
BPO | [31843](https://bugs.python.org/issue31843)
--- | :---
Nosy | @vstinner, @phaqui
PRs | <li>python/cpython#4299</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-07.00:49:11.470>
created_at = <Date 2017-10-23.00:13:44.976>
labels = ['type-feature']
title = 'sqlite3.connect() should accept PathLike objects'
updated_at = <Date 2017-11-07.00:49:11.469>
user = 'https://bugs.python.org/AllenLi'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-07.00:49:11.469>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-07.00:49:11.470>
closer = 'vstinner'
components = []
creation = <Date 2017-10-23.00:13:44.976>
creator = 'Allen Li'
dependencies = []
files = []
hgrepos = []
issue_num = 31843
keywords = ['patch']
message_count = 4.0
messages = ['304773', '305674', '305702', '305703']
nosy_count = 3.0
nosy_names = ['vstinner', 'Phaqui', 'Allen Li']
pr_nums = ['4299']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31843'
versions = ['Python 3.6']
```

</p></details>

**Comment by ffb7c71b-4f64-4d94-95a7-91bbba845748** [comment]
sqlite3.connect() should accept PathLike objects (objects that implement \_\_fspath__)

**Comment by 7d6f023c-9371-47e5-8ab4-997e01d0cab0** [comment]
Had my first go at a python patch. Added a test case for it, and all tests
passing when I test with

`./python -bb -E -Wd -m test -v test.test_sqlite -r -w -uall -R 3:2`

**Comment by vstinner** [comment]
New changeset a22a127458d75b9b7e65e058f5db5ff705df5696 by Victor Stinner (Anders Lorentsen) in branch 'master':
bpo-31843: sqlite3.connect() now accepts PathLike objects as database name (bpo-4299)
https://github.com/python/cpython/commit/a22a127458d75b9b7e65e058f5db5ff705df5696

**Comment by vstinner** [comment]
Thank you Allen Li for your feature request.

Thank you very much Anders Lorentsen for addressing all my annoying comments on the pull request, and congratulations for your first contribution to CPython! It's a nice once ;-)
