### ISSUE TITLE
Port the standard library to PEP 489 multiphase initialization

### ISSUE THREAD

**Issue by fab47422-3362-4ed2-963d-5f8400bde39f** [python/cpython#76043]
BPO | [31862](https://bugs.python.org/issue31862)
--- | :---
Nosy | @ncoghlan, @vstinner, @encukou, @Dormouse759
PRs | <li>python/cpython#4108</li>
Superseder | <li>bpo-1635741: Py_Finalize() doesn&#x27;t clear all Python objects at exit</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-07.13:55:38.744>
created_at = <Date 2017-10-24.15:08:56.007>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'Port the standard library to PEP 489 multiphase initialization'
updated_at = <Date 2020-09-07.13:55:38.743>
user = 'https://github.com/Dormouse759'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-07.13:55:38.743>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2020-09-07.13:55:38.744>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-10-24.15:08:56.007>
creator = 'Dormouse759'
dependencies = []
files = []
hgrepos = []
issue_num = 31862
keywords = ['patch']
message_count = 6.0
messages = ['304914', '304916', '343182', '376487', '376488', '376489']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'vstinner', 'petr.viktorin', 'Dormouse759']
pr_nums = ['4108']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1635741'
type = 'enhancement'
url = 'https://bugs.python.org/issue31862'
versions = ['Python 3.7']
```

</p></details>

**Comment by fab47422-3362-4ed2-963d-5f8400bde39f** [comment]
PEP-489 introduced multiphase initialization of extension and built-in modules.
Now, almost no module in the standard library supports this feature. This should be improved to prepare Python for better testing of subinterpreters.

Many benefits of PEP-489 don't apply to stdlib modules. However, the PEP effectively says that by using multi-phase init, the module author "promises" that the module is "subinterpreter-friendly" [0]. So, when porting, each module should be checked that it e.g. doesn't use mutable process-global state.

I'd like to port stdlib to multi-phase init, starting with the easier modules, to:
    - get familiar with contributing to CPython,
    - check and track which modules are already "subinterpreter-friendly", and
    - figure out how and where PEP-489 is lacking (beyond what is discussed in the PEP itself).


[0]: https://www.python.org/dev/peps/pep-0489/#subinterpreters-and-interpreter-reloading

**Comment by encukou** [comment]
FWIW, Marcel is an intern in my team, tasked to learn CPython internals by trying to improve subinterpreter support. If I don't comment on his issues it's because we discussed privately beforehand.
