### ISSUE TITLE
datetime violates Postel's law

### ISSUE THREAD

**Issue by 42c26b8c-c27b-44c5-98bb-c1d848128f65** [python/cpython#76045]
BPO | [31864](https://bugs.python.org/issue31864)
--- | :---
Nosy | @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-24.23:23:34.123>
created_at = <Date 2017-10-24.22:56:14.833>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = "datetime violates Postel's law"
updated_at = <Date 2017-10-24.23:23:34.122>
user = 'https://bugs.python.org/gkuenning'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-24.23:23:34.122>
actor = 'ned.deily'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-24.23:23:34.123>
closer = 'ned.deily'
components = ['Library (Lib)']
creation = <Date 2017-10-24.22:56:14.833>
creator = 'gkuenning'
dependencies = []
files = []
hgrepos = []
issue_num = 31864
keywords = []
message_count = 4.0
messages = ['304944', '304945', '304946', '304947']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'gkuenning']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31864'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 42c26b8c-c27b-44c5-98bb-c1d848128f65** [comment]
The datetime package is too eager to reject nonconforming VCALENDAR-format files.  The particular issue I encountered is related to time zones.  RFC 5545 clearly states that the DTSTART field is required.  However, there are situations where DTSTART isn't strictly necessary because the zone in question doesn't observe daylight-savings time and never has.

For example, I have a VCALENDAR file that was generated by a program that omits DTSTART for such zones.  Here's an example:

BEGIN:VTIMEZONE
TZID:America/Phoenix
X-LIC-LOCATION:America/Phoenix
BEGIN:DAYLIGHT
TZOFFSETFROM:-0700
TZOFFSETTO:-0700
TZNAME:Ariz
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:-0700
TZOFFSETTO:-0700
TZNAME:Ariz
END:STANDARD
END:VTIMEZONE

Clearly, this file violates RFC 5445, and I have reported that fact to the program's maintainer (who will fix the problem soon).  Nevertheless, feeding an ICS file to datetime.\_parse_rfc with this error causes a ValueError exception, which makes the VCALENDAR file unreadable.

In keeping with Postel's law ("Be conservative in what you do, be liberal in what you accept from others"), \_parse_rfc should attempt to accept VCALENDAR files whenever it is possible to make sense of them.  Thus, for example:

```py
    if not founddtstart:
        rrulelines.append('DTSTART:19000101T020000')
```


The above could be improved a bit, for example by still rejecting entries in which the standard and daylight sections had different offsets (although even then it seems valid to assume a DTSTART in the distant past).

Although the dtstart issue is the one that prompted this report, I also noticed the following in \_parse_rfc:

```py
    if name == "BEGIN":
        if value in ("STANDARD", "DAYLIGHT"):
            # Process component
            pass
        else:
            raise ValueError("unknown component: "+value)
```


Again, there's an opportunity to be more robust here.  One could issue a warning message, but then ignore the unknown component.

In both cases (and I suspect numerous others), halting parsing is an extreme response to various errors, since it leaves the user of the package with no way to process a nonconforming file.  That's especially problematic since VCALENDAR files are generated by so many different programs, many of which are written by programmers who haven't bothered to read RFC 5445--or who have read it but then made some minor mistake that produces broken files.

**Comment by bitdancer** [comment]
The python standard library does not parse files, nor does it have a \_parse_rfc message. You say you reported the problem you are having to "the program's maintainer", and that is appropriate.  There does not appear to be anything in this report related to the python standard library, which is what would be appropriate for this bug tracker.

**Comment by bitdancer** [comment]
I meant the python standard library datetime package doesn't parse files, of course :)  Other parts of the stdlib certainly do parse files.

**Comment by 42c26b8c-c27b-44c5-98bb-c1d848128f65** [comment]
Duh, my mistake.  The problem is in dateutil, which AFAICT is indeed not part of the Python standard library.  I'll hang my head in shame and go report the problem in the right place.
