### ISSUE TITLE
add aiter() and anext() functions

### ISSUE THREAD

**Issue by 6ed87849-5f14-445b-9bcb-28e40d0c505c** [python/cpython#76042]
BPO | [31861](https://bugs.python.org/issue31861)
--- | :---
Nosy | @gvanrossum, @vstinner, @basak, @jab, @sorcio, @dimaqq, @1st1, @JelleZijlstra, @pablogsal, @isidentical, @belm0, @jack1142, @sweeneyde
PRs | <li>python/cpython#8895</li><li>python/cpython#23847</li><li>python/cpython#25004</li><li>python/cpython#25005</li><li>python/cpython#25008</li>
Files | <li>[aiter_comp.py](https://bugs.python.org/file47242/aiter_comp.py "Uploaded as text/plain at 2017-10-27.09:52:53 by @sorcio"): tentative Python implementation</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-03-24.01:43:07.674>
created_at = <Date 2017-10-24.13:26:15.573>
labels = ['library', '3.10']
title = 'add aiter() and anext() functions'
updated_at = <Date 2021-04-07.22:59:05.539>
user = 'https://github.com/sorcio'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-07.22:59:05.539>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2021-03-24.01:43:07.674>
closer = 'pablogsal'
components = ['Library (Lib)']
creation = <Date 2017-10-24.13:26:15.573>
creator = 'davide.rizzo'
dependencies = []
files = ['47242']
hgrepos = []
issue_num = 31861
keywords = ['patch']
message_count = 25.0
messages = ['304910', '304923', '304924', '304926', '305107', '319519', '319520', '323989', '323997', '324009', '337061', '337135', '375633', '380408', '381832', '383327', '383441', '389414', '389417', '389420', '389422', '389426', '389427', '390402', '390495']
nosy_count = 15.0
nosy_names = ['gvanrossum', 'vstinner', 'rb', 'jab', 'davide.rizzo', 'jmehnle', 'Dima.Tisnek', 'yselivanov', 'JelleZijlstra', 'pablogsal', 'BTaskaya', 'Eric Wieser', 'John Belmonte', 'jack1142', 'Dennis Sweeney']
pr_nums = ['8895', '23847', '25004', '25005', '25008']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31861'
versions = ['Python 3.10']
```

</p></details>

**Comment by 6ed87849-5f14-445b-9bcb-28e40d0c505c** [comment]
PEP-525 suggested that adding aiter() and anext() would need to wait until async \_\_aiter__ is dropped in 3.7. bpo-31709 solved that, so now it would be possible to add them.

**Comment by 1st1** [comment]
Guido, do we need a PEP to add aiter() and anext() builtins?

**Comment by gvanrossum** [comment]
> do we need a PEP to add aiter() and anext() builtins?

No, just this tracker issue, a PR and a reviewer. (Sorry, I can't review
CPython code myself any more.)

**Comment by 1st1** [comment]
> No, just this tracker issue, a PR and a reviewer. (Sorry, I can't review
CPython code myself any more.)

Alright, I'll work on a PR after PEP 55x.

**Comment by 6ed87849-5f14-445b-9bcb-28e40d0c505c** [comment]
I attempted to make a Python implementation (attached) to use in my code. There are a few questions in the comments.

One of the complications is the async equivalent of next with two arguments like next(iterator, default). It cannot return the result of \_\_anext__() because it needs to catch StopAsyncIteration. So it should return an awaitable wrapper instead (in my Python code this is rendered as a coroutine). A secondary question is whether the default value should be returned as it is passed, or awaited on.
