### ISSUE TITLE
Null pointer dereference in ndb.ndbm get when used with a default value.

### ISSUE THREAD

**Issue by 6223a2a0-241c-4263-bd27-18fc5223cc39** [python/cpython#76049]
BPO | [31868](https://bugs.python.org/issue31868)
--- | :---
Nosy | @serhiy-storchaka, @tmiasko
Superseder | <li>bpo-33383: Crash in the get() method a single argument in dbm.ndbm</li>
Files | <li>[0001-Fix-null-pointer-dereference-in-dbm.ndbm-get.patch](https://bugs.python.org/file47236/0001-Fix-null-pointer-dereference-in-dbm.ndbm-get.patch "Uploaded as text/plain at 2017-10-25.10:25:18 by @tmiasko"): [PATCH] Fix null pointer dereference in dbm.ndbm get.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-20.23:20:54.525>
created_at = <Date 2017-10-25.10:25:18.892>
labels = ['3.7', '3.8', 'type-crash']
title = 'Null pointer dereference in ndb.ndbm get when used with a default value.'
updated_at = <Date 2018-05-20.23:20:54.524>
user = 'https://github.com/tmiasko'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-20.23:20:54.524>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-20.23:20:54.525>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-10-25.10:25:18.892>
creator = 'tmiasko'
dependencies = []
files = ['47236']
hgrepos = []
issue_num = 31868
keywords = ['patch']
message_count = 3.0
messages = ['304977', '304980', '317209']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'tmiasko']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '33383'
type = 'crash'
url = 'https://bugs.python.org/issue31868'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 6223a2a0-241c-4263-bd27-18fc5223cc39** [comment]
Using ndb.ndbm get when key is missing and default value has to be returned
results in invocation of Py_INCREF on null pointer. Test case to reproduce the issue:

```
import dbm.ndbm

with dbm.ndbm.open('db', 'n') as db:
    print(db.get('missing-key'))
```

**Comment by serhiy-storchaka** [comment]
Could you please create a pull request on GitHub Tomasz?
