### ISSUE TITLE
Inconsistent capitalization of proper noun - Unicode.

### ISSUE THREAD

**Issue by 3f449fc3-bd22-4cc1-87c5-8711a4fbbfbd** [python/cpython#76054]
BPO | [31873](https://bugs.python.org/issue31873)
--- | :---
Nosy | @malemburg, @vstinner, @benjaminp, @ezio-melotti, @bitdancer, @vadmium, @serhiy-storchaka, @JulienPalard, @toonarmycaptain, @miss-islington
PRs | <li>python/cpython#4125</li><li>python/cpython#13194</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-08.16:07:03.957>
created_at = <Date 2017-10-26.13:15:32.902>
labels = ['type-feature', '3.7', 'expert-unicode', 'docs']
title = 'Inconsistent capitalization of proper noun - Unicode.'
updated_at = <Date 2019-05-08.16:34:15.666>
user = 'https://github.com/toonarmycaptain'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-08.16:34:15.666>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-05-08.16:07:03.957>
closer = 'mdk'
components = ['Documentation', 'Unicode']
creation = <Date 2017-10-26.13:15:32.902>
creator = 'toonarmycaptain'
dependencies = []
files = []
hgrepos = []
issue_num = 31873
keywords = ['patch']
message_count = 10.0
messages = ['305050', '305051', '305053', '305062', '305068', '329264', '329267', '341896', '341899', '341907']
nosy_count = 11.0
nosy_names = ['lemburg', 'vstinner', 'benjamin.peterson', 'ezio.melotti', 'r.david.murray', 'docs@python', 'martin.panter', 'serhiy.storchaka', 'mdk', 'toonarmycaptain', 'miss-islington']
pr_nums = ['4125', '13194']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31873'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 3f449fc3-bd22-4cc1-87c5-8711a4fbbfbd** [comment]
Make 'unicode'/'Unicode' capitalization consistent.
'Unicode' is a proper noun, and as such should be capitalized. 

I submitted a pull request correcting the inconsistent capitalization in the Unicode page of the Documentation - [Doc/c-api/unicode.rst](https://github.com/python/cpython/blob/main/Doc/c-api/unicode.rst) - capitalizing 12 errant instances to reflect the correct capitalization in most of the document. I was then requested to open an issue here for discussion.

**Comment by serhiy-storchaka** [comment]
I agree that the inconsistency should be fixed. But I'm not sure that we should use the words "an Unicode object" in Python 3.

In many similar cases ("a bytes object", "a type object", "a module object") the name of Python type is used. "unicode" was a name of Python type in Python 2. In Python 3 it is "str". The term "Unicode string" also is widely used. Should not we use "a str object", "a string object", "a Unicode string" or "a Unicode string object" in the C API documentation?

**Comment by bitdancer** [comment]
It may be a proper noun, but it is conventionally spelled with a lowercase letter when referring to the type/object.  It would be spelled with an upper case letter when referring to the \*standard*.

**Comment by 3f449fc3-bd22-4cc1-87c5-8711a4fbbfbd** [comment]
Does the Unicode documentation currently conform to that convention, or does it require editing? 

It appears to me that a lot of cases where reference to "Unicode object" is currently capitalised (most of them, in fact) may need to be modified. 
However, it would seem that there is a grey area in making a distinction between reference to the unicode type as implemented in Python and reference to the standard as a descriptor of the format of an object? The way I read there a lot of the cases are in essence a reference to both.

**Comment by bitdancer** [comment]
In this case I think the cost of editing for consistency may be higher than the value, especially since as you say there are ambiguous cases.
