### ISSUE TITLE
Build fails on Cygwin since issue28180

### ISSUE THREAD

**Issue by embray** [python/cpython#76058]
BPO | [31877](https://bugs.python.org/issue31877)
--- | :---
Nosy | @pfmoore, @ncoghlan, @vstinner, @tjguk, @embray, @zware, @zooba
PRs | <li>python/cpython#4134</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ncoghlan'
closed_at = <Date 2017-10-27.09:46:42.087>
created_at = <Date 2017-10-26.14:54:59.260>
labels = ['interpreter-core', 'build', '3.7', 'OS-windows']
title = 'Build fails on Cygwin since issue28180'
updated_at = <Date 2017-10-27.09:46:42.085>
user = 'https://github.com/embray'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-27.09:46:42.085>
actor = 'ncoghlan'
assignee = 'ncoghlan'
closed = True
closed_date = <Date 2017-10-27.09:46:42.087>
closer = 'ncoghlan'
components = ['Interpreter Core', 'Windows']
creation = <Date 2017-10-26.14:54:59.260>
creator = 'erik.bray'
dependencies = []
files = []
hgrepos = []
issue_num = 31877
keywords = ['patch']
message_count = 3.0
messages = ['305061', '305105', '305106']
nosy_count = 7.0
nosy_names = ['paul.moore', 'ncoghlan', 'vstinner', 'tim.golden', 'erik.bray', 'zach.ware', 'steve.dower']
pr_nums = ['4134']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31877'
versions = ['Python 3.7']
```

</p></details>

**Comment by embray** [comment]
I'm trying once again to get the test suite up to snuff on Cygwin so I can start running a buildbot (particularly now that PEP-539 is done).  However, as of bpo-28180 the build fails with:

gcc    -o python.exe [Programs/python.o](https://github.com/python/cpython/blob/main/Programs/python.o) libpython3.7m.dll.a -lintl -ldl    -lm
[Programs/python.o](https://github.com/python/cpython/blob/main/Programs/python.o): In function `main':
./Programs/python.c:81: undefined reference to `_Py_LegacyLocaleDetected'
./Programs/python.c:81:(.text.startup+0x86): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_Py_LegacyLocaleDetected'
./Programs/python.c:82: undefined reference to `_Py_CoerceLegacyLocale'
./Programs/python.c:82:(.text.startup+0x19f): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `_Py_CoerceLegacyLocale'
collect2: error: ld returned 1 exit status

It seems \_Py_LegacyLocaleDetected and \_PyCoerceLegacyLocale are missing the necessary PyAPI_FUNC declarations in pylifecycle.h.

**Comment by ncoghlan** [comment]
New changeset 031c4bfadb69feeda82ce886d6b0cadc638d2e1e by Nick Coghlan (Erik Bray) in branch 'master':
bpo-31877: Add \_Py_LegacyLocaleDetected and \_PyCoerceLegacyLocale to pylifecycle.h (GH-4134)
https://github.com/python/cpython/commit/031c4bfadb69feeda82ce886d6b0cadc638d2e1e

**Comment by ncoghlan** [comment]
Thanks for the patch!
