### ISSUE TITLE
[Windows] subprocess set priority on windows

### ISSUE THREAD

**Issue by f0209f00-5b9e-4509-97ee-b341cb65ff51** [python/cpython#76065]
BPO | [31884](https://bugs.python.org/issue31884)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba, @JamesGKent
PRs | <li>python/cpython#4150</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.15:39:17.773>
created_at = <Date 2017-10-27.14:02:33.416>
labels = ['3.7', 'type-feature', 'library', 'OS-windows']
title = '[Windows] subprocess set priority on windows'
updated_at = <Date 2017-11-08.15:39:17.772>
user = 'https://github.com/JamesGKent'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.15:39:17.772>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.15:39:17.773>
closer = 'vstinner'
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-10-27.14:02:33.416>
creator = 'JamesGKent'
dependencies = []
files = []
hgrepos = []
issue_num = 31884
keywords = ['patch']
message_count = 2.0
messages = ['305691', '305849']
nosy_count = 6.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower', 'JamesGKent']
pr_nums = ['4150']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31884'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Please describe the issue.

**Comment by vstinner** [comment]
New changeset b5d9e0811463f3b28ba355a9e0bee7f1682854e3 by Victor Stinner (James) in branch 'master':
bpo-31884 subprocess: add Windows constants for process priority (bpo-4150)
https://github.com/python/cpython/commit/b5d9e0811463f3b28ba355a9e0bee7f1682854e3
