### ISSUE TITLE
subprocess.returncode not set depending on arguments to subprocess.run

### ISSUE THREAD

**Issue by 02d1cae4-c2b4-4e77-8a53-718b1f5ca9fa** [python/cpython#76062]
BPO | [31881](https://bugs.python.org/issue31881)
--- | :---
Nosy | @bitdancer, @NAThompson

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-27.21:24:41.715>
created_at = <Date 2017-10-27.00:20:32.766>
labels = ['invalid']
title = 'subprocess.returncode not set depending on arguments to subprocess.run'
updated_at = <Date 2017-10-27.21:24:41.714>
user = 'https://github.com/NAThompson'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-27.21:24:41.714>
actor = 'nthompson'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-27.21:24:41.715>
closer = 'nthompson'
components = []
creation = <Date 2017-10-27.00:20:32.766>
creator = 'nthompson'
dependencies = []
files = []
hgrepos = []
issue_num = 31881
keywords = []
message_count = 3.0
messages = ['305094', '305096', '305097']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'nthompson']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31881'
versions = ['Python 3.6']
```

</p></details>

**Comment by 02d1cae4-c2b4-4e77-8a53-718b1f5ca9fa** [comment]
If subprocess.run is called with a single string, say:

```py
completed_ps = subprocess.run('mpirun -np 4 myexe.x moreargs', shell=True)
```


and 'myexe.x moreargs' fails with a returncode of 1, then 'completed_ps.returncode' is None. However, if we split the args with shlex, we obtain the desired result, which is a returncode of 1:

```py
import shlex
args = shlex.split('mpirun -np 4 myexe.x moreargs')
completed_ps = subprocess.run(args)
# now completed_ps.returncode = 1 if myexe.x moreargs fails.
```


Reproduced on Mac, Ubuntu 17.04, Python 3.6.1 and Python 3.6.3.

**Comment by bitdancer** [comment]
If you run

  mpirun -np 4 myexe.x moreargs; echo $?

in /bin/sh, what do you see?  You also might try to make sure it is the same mpirun and the same myexe.x that is being called in both cases (it is the mpirun return code you are seeing).

**Comment by 02d1cae4-c2b4-4e77-8a53-718b1f5ca9fa** [comment]
I have verified that

```sh
$ mpirun -np 4 myexe.x moreargs; echo $?
1
```
