### ISSUE TITLE
Cygwin: heap corruption bug in wcsxfrm

### ISSUE THREAD

**Issue by embray** [python/cpython#76064]
BPO | [31883](https://bugs.python.org/issue31883)
--- | :---
Nosy | @embray, @serhiy-storchaka
PRs | <li>python/cpython#4151</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-30.10:14:51.811>
created_at = <Date 2017-10-27.13:42:11.965>
labels = []
title = 'Cygwin: heap corruption bug in wcsxfrm'
updated_at = <Date 2017-10-30.11:38:25.882>
user = 'https://github.com/embray'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-30.11:38:25.882>
actor = 'erik.bray'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-30.10:14:51.811>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-10-27.13:42:11.965>
creator = 'erik.bray'
dependencies = []
files = []
hgrepos = []
issue_num = 31883
keywords = ['patch']
message_count = 7.0
messages = ['305120', '305126', '305131', '305133', '305215', '305217', '305224']
nosy_count = 2.0
nosy_names = ['erik.bray', 'serhiy.storchaka']
pr_nums = ['4151']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31883'
versions = []
```

</p></details>

**Comment by embray** [comment]
There is an acknowledged bug in Cygwin's implementation of wcsxfrm() [1] that can cause heap corruption in certain cases.  This bug has since been fixed in Cygwin 2.8.1-1 [2] and all current and future releases.  However, that was relatively recent (July 2017) so it may still crop up.

I also have a workaround for this from the Python side, but rather than clutter the code with workarounds for platform-specific bugs I think it suffices just to skip the test in this case.

[1] https://cygwin.com/ml/cygwin/2017-05/msg00149.html
[2] https://cygwin.com/ml/cygwin-announce/2017-07/msg00002.html

**Comment by serhiy-storchaka** [comment]
Since this bug has been fixed in Cygwin, I don't think we should add a workaround for it. The expected date of Python 3.7 release is 2018-06-15, this is far from the date of releasing the fixed Cygwin.

**Comment by embray** [comment]
To be clear, are you saying there shouldn't be a workaround to the underlying issue (I agree), or are you saying the test skip shouldn't even be added? I'm in favor of just skipping the test since it's still a problem on (currently) recent Cygwin versions. And it's not a very critical test so I'm happy to just skip it in this case.

**Comment by serhiy-storchaka** [comment]
According to your reference a problem is fixed in recent Cygwin versions, isn't?

Skipping the test on Cygwin means that wcsxfrm() will be untested on this platform. Future regressions will be unnoticed.

**Comment by embray** [comment]
Well, I agree there's an unfortunate trade-off here: One can skip the test, allowing the test suite to work on slightly older versions of Cygwin, from before this issue was fixed.  However, I then lose regression testing on newer versions.  My personal feeling in this case is that it's not a very important test and can be skipped in the future (although the bug that this test caught was fairly serious and one would want regression testing for it...)

As an alternative I could be more fine-grained and only skip the test on older versions of Cygwin that are affected.  I was hoping to avoid putting in too much Cygwin-specific test utilities, though adding a version check for Cygwin is not terribly hard (I do the same for my Cygwin port of psutil).

For reference, the current version of Cygwin that comes installed on AppVeyor (for which I'm trying to get a Cygwin build set up) is 2.8.0, which \*is* (just barely) affected by this bug.

**Comment by serhiy-storchaka** [comment]
This is a problem of AppVeyor. It should update Cygwin to a bugfix release. 2.8.0 contains other bugs.

**Comment by embray** [comment]
Well, we'll see how long it takes me to get them to respond on that.  If it's not too much trouble then I'll be happy to drop this issue.
