### ISSUE TITLE
Please define the flag METH_STACKLESS for Stackless Python

### ISSUE THREAD

**Issue by 6c8a72cc-9872-4016-ae96-23477ed791a8** [python/cpython#76071]
BPO | [31890](https://bugs.python.org/issue31890)
--- | :---
Nosy | @vstinner, @akruis
PRs | <li>python/cpython#4159</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-03.10:07:27.355>
created_at = <Date 2017-10-28.17:06:54.411>
labels = ['interpreter-core', '3.8', 'type-feature', '3.7']
title = 'Please define the flag METH_STACKLESS for Stackless Python'
updated_at = <Date 2017-11-03.10:07:27.354>
user = 'https://github.com/akruis'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-03.10:07:27.354>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-03.10:07:27.355>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-10-28.17:06:54.411>
creator = 'anselm.kruis'
dependencies = []
files = []
hgrepos = []
issue_num = 31890
keywords = ['patch']
message_count = 5.0
messages = ['305164', '305348', '305433', '305454', '305467']
nosy_count = 2.0
nosy_names = ['vstinner', 'anselm.kruis']
pr_nums = ['4159']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31890'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 6c8a72cc-9872-4016-ae96-23477ed791a8** [comment]
The header [Include/methodobject.h](https://github.com/python/cpython/blob/main/Include/methodobject.h) defines ml_flags METH_xxx.

Stackless Python adds the flag METH_STACKLESS. Traditionally Stackless used bit 0x0080 for METH_STACKLESS, but starting with C-Python 3.6 bit 0x0080 is used for METH_FASTCALL. 

In order to prevent future conflicts, I propose to add METH_STACKLESS to methodobject.h. 

```c
#ifdef STACKLESS
#define METH_STACKLESS 0x0100
#else
#define METH_STACKLESS 0x0000
#endif
```


[Include/object.h](https://github.com/python/cpython/blob/main/Include/object.h) already contains a similar definition.

**Comment by vstinner** [comment]
Hi Anselm,

What is the status of Stackless Python? I didn't hear about Stackless for 5 years. Is the project still alive?

I see some activity on https://bitbucket.org/stackless-dev/stackless/wiki/Home and http://www.stackless.com/pipermail/stackless/

**Comment by 6c8a72cc-9872-4016-ae96-23477ed791a8** [comment]
Hi Victor,

The project is still somewhat alive, because the software, that is used to control a large percentage of the CAE simulation jobs of large German automakers, requires Stackless Python, especially the option to serialize tasklets and move them around between different computers.

The Stackless project recently released Stackless Python 3.5.4 and 2.7.14 and C-Python is merged up to 3.6.1. See https://github.com/stackless-dev/stackless/tree/3.6-slp and https://bitbucket.org/stackless-dev/stackless/wiki/Download.

Under the hood we fixed the reference counting (2016) and migrated from bitbucket/hg to github/git.

Regards
  Anselm

**Comment by vstinner** [comment]
New changeset 9e3397333278f973a11d933c27a69af250e4acf0 by Victor Stinner (Anselm Kruis) in branch 'master':
bpo-31890: define METH_STACKLESS (bpo-4159)
https://github.com/python/cpython/commit/9e3397333278f973a11d933c27a69af250e4acf0

**Comment by vstinner** [comment]
Anselm Kruis: Python 3.7 now has your METH_STACKLESS flag. Enjoy ;-)
