### ISSUE TITLE
In function define class inherit ctypes.structure, and using ctypes.pointer leak memory

### ISSUE THREAD

**Issue by 4c684eb5-9de9-4072-b680-b11c48ea4a05** [python/cpython#76077]
BPO | [31896](https://bugs.python.org/issue31896)
--- | :---
Nosy | @terryjreedy, @amauryfa, @abalkin, @meadori, @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.15:08:59.639>
created_at = <Date 2017-10-30.03:53:39.513>
labels = ['ctypes', 'invalid', 'performance']
title = 'In function define class inherit ctypes.structure, and using ctypes.pointer leak memory'
updated_at = <Date 2017-11-08.15:15:20.543>
user = 'https://bugs.python.org/YangBig'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.15:15:20.543>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.15:08:59.639>
closer = 'berker.peksag'
components = ['ctypes']
creation = <Date 2017-10-30.03:53:39.513>
creator = 'Yang Big'
dependencies = []
files = []
hgrepos = []
issue_num = 31896
keywords = []
message_count = 4.0
messages = ['305204', '305508', '305854', '305855']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'amaury.forgeotdarc', 'belopolsky', 'meador.inge', 'berker.peksag', 'Yang Big']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue31896'
versions = ['Python 2.7']
```

</p></details>

**Comment by 4c684eb5-9de9-4072-b680-b11c48ea4a05** [comment]
Here my code:
  2 import sys
  3 import ctypes
  4      
  5      
  6 def hi():
  7     class timespec(ctypes.Structure):
  8     ┆   """Time specification, as described in clock_gettime(3)."""
  9     ┆   \_fields_ = (('tv_sec', ctypes.c_long),
 10     ┆   ┆   ┆   ┆   ('tv_nsec', ctypes.c_long))
 11      
 12      
 13     ts = timespec()
 14     po = ctypes.pointer(ts)
 15      
 16      
 17 def main():
 18     while True:
 19     ┆   test = hi()
 20      
 21 if \_\_name__ == "\_\_main__":
 22     sys  2 import sys
  3 import ctypes
  4      
  5      
  6 def hi():
  7     class timespec(ctypes.Structure):
  8     ┆   """Time specification, as described in clock_gettime(3)."""
  9     ┆   \_fields_ = (('tv_sec', ctypes.c_long),
 10     ┆   ┆   ┆   ┆   ('tv_nsec', ctypes.c_long))
 11      
 12      
 13     ts = timespec()
 14     po = ctypes.pointer(ts)
 15      
 16      
 17 def main():
 18     while True:
 19     ┆   test = hi()
 20      
 21 if \_\_name__ == "\_\_main__":
 22     sys.exit(main())

run this code, i find that the program occupy more and more VmRss
my python is 2.7.11, in python3 i also find this problem. 
   Is this normal？I am a newbie with python, not very familiar with some 
python's internal principle. 
   Tanks.

**Comment by terryjreedy** [comment]
The tracker is for patching CPython.  Please consider closing this and asking your question on python-list.  When you post code, do so only once, and without line numbers, so it can be copied and run as is.  Do include data on the ref leaks.

**Comment by berkerpeksag** [comment]
I agree with Terry. Your code calls hi() in an infinite loop (why timespec is defined in hi()?), we don't know how clock_gettime(3) is implemented etc. (it should cleanup its own memory if it calls malloc()) etc. Please use python-list or StackOverflow for usage questions.

**Comment by berkerpeksag** [comment]
See also bpo-12998.
