### ISSUE TITLE
IPv4Networkcontains raises exception on None

### ISSUE THREAD

**Issue by 5c19f2fa-a1ce-40cf-b87e-339089673199** [python/cpython#76086]
BPO | [31905](https://bugs.python.org/issue31905)
--- | :---
Nosy | @ericvsmith, @bitdancer, @serhiy-storchaka
PRs | <li>python/cpython#4180</li>
Files | <li>[ne.py](https://bugs.python.org/file47247/ne.py "Uploaded as text/plain at 2017-10-30.20:56:08 by Gerard Weatherby"): SCCE</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-31.07:07:05.140>
created_at = <Date 2017-10-30.20:56:08.738>
labels = ['invalid', 'type-bug', 'library']
title = 'IPv4Networkcontains raises exception on None'
updated_at = <Date 2017-10-31.07:07:23.837>
user = 'https://bugs.python.org/GerardWeatherby'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-31.07:07:23.837>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-31.07:07:05.140>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-10-30.20:56:08.738>
creator = 'Gerard Weatherby'
dependencies = []
files = ['47247']
hgrepos = []
issue_num = 31905
keywords = ['patch']
message_count = 4.0
messages = ['305250', '305251', '305262', '305275']
nosy_count = 4.0
nosy_names = ['eric.smith', 'r.david.murray', 'serhiy.storchaka', 'Gerard Weatherby']
pr_nums = ['4180']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31905'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5c19f2fa-a1ce-40cf-b87e-339089673199** [comment]
Given a IPvNetwork network
if x in network:
   ...

raises an AttributeError instead of returning False.

**Comment by bitdancer** [comment]
It is not obvious that this is a bug.  Why should None be a valid value for 'in network'?

**Comment by ericvsmith** [comment]
I agree with David. And since the PR says "not other", then it makes even less sense, since it's checking for any False-y object.

I recommend closing this as "not a bug".

**Comment by serhiy-storchaka** [comment]
I concur. IPvNetwork is not a general purposed collection. And even genera purposed collections can have restrictions on the arguments of "in". E.g.:

```pycon
>>> [] in {}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
```


Similar issue already was raised (maybe not for IPvNetwork, but for other class supporting the "in" operator) and was closed with the same arguments.
