### ISSUE TITLE
doc: Clarify error message when attempting to call function via str.format()

### ISSUE THREAD

**Issue by 25db41cf-51b5-41a8-9f68-03a0fcf7cb17** [python/cpython#76088]
BPO | [31907](https://bugs.python.org/issue31907)
--- | :---
Nosy | @ericvsmith, @serhiy-storchaka, @miss-islington, @iritkatriel
PRs | <li>python/cpython#25053</li><li>python/cpython#25055</li><li>python/cpython#25056</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = <Date 2021-03-28.20:58:54.085>
created_at = <Date 2017-10-31.00:35:20.151>
labels = ['interpreter-core', 'type-feature', '3.10', 'docs']
title = 'doc: Clarify error message when attempting to call function via str.format()'
updated_at = <Date 2021-03-28.21:05:16.373>
user = 'https://bugs.python.org/mickey695'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-28.21:05:16.373>
actor = 'eric.smith'
assignee = 'eric.smith'
closed = True
closed_date = <Date 2021-03-28.20:58:54.085>
closer = 'eric.smith'
components = ['Documentation', 'Interpreter Core']
creation = <Date 2017-10-31.00:35:20.151>
creator = 'mickey695'
dependencies = []
files = []
hgrepos = []
issue_num = 31907
keywords = ['patch']
message_count = 12.0
messages = ['305263', '305276', '305287', '305413', '305496', '309183', '389405', '389642', '389644', '389648', '389649', '389650']
nosy_count = 5.0
nosy_names = ['eric.smith', 'serhiy.storchaka', 'mickey695', 'miss-islington', 'iritkatriel']
pr_nums = ['25053', '25055', '25056']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31907'
versions = ['Python 3.10']
```

</p></details>

**Comment by 25db41cf-51b5-41a8-9f68-03a0fcf7cb17** [comment]
PEP-3101 states that format strings may only use the "."(getattr) or the "[]" (getitem) operators to address either attributes or items of parameters.
Should a programmer attempt to, for example, call a function of a parameter as follows: 

>\>\> d = datetime.datetime(2017, 10, 31)
>\>\> "{0.ctime()}".format(d)

they will receive an error message such as:

AttributeError: 'datetime.datetime' object has no attribute 'ctime()'

Proposal:
Raise an error stating that cannot embed arbitrary expressions in str.format() format strings

**Comment by ericvsmith** [comment]
How would you distinguish this from the case where an actually missing attribute was given?

```pycon
>>> "{0.ctimex}".format(d)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'datetime.datetime' object has no attribute 'ctimex'
```


I guess it would be possible to change the parser to only look for valid chars in an identifier and give an error if there were "extra" chars found, but I'm not sure it's worth the hassle. The error message seems clear enough to me. Also, I wouldn't want to change this to not be an AttributeError (for backward compatibility), and I'm not sure an AttributeError with a different message would be good.

Of course, this works with f-strings:

```pycon
>>> f"{d.ctime()}"
'Tue Oct 31 00:00:00 2017'
```


And I just realized that your code actually is valid, with a custom \_\_getattr__. And while I wouldn't recommend doing this, I also wouldn't want to break it. For all I know, people have written custom evaluators in \_\_getattr__:

```pycon
>>> class C:
...     def __getattr__(self, name):
...         if name == 'ctime()':
...             return 'okay'
...         raise AttributeError('not found')
...

>>> '{0.x}'.format(C())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 5, in __getattr__
AttributeError: not found

>>> '{0.ctime()}'.format(C())
'okay'
```


I'm changing versions because this would be a new feature, since it breaks valid code.

**Comment by serhiy-storchaka** [comment]
I have wrote a patch that change the parser to only accept valid identifiers. But now I have the same doubts and want first to discuss this [1]. This change can break the existing code as Eric's example shows.

[1] https://mail.python.org/pipermail/python-dev/2017-October/150052.html

**Comment by ericvsmith** [comment]
Guido's suggestion in https://mail.python.org/pipermail/python-dev/2017-October/150055.html is to not change anything.

Assuming we do that, it's still an open issue as to if/how we should document and test the current behavior. I'd be surprised if it's tested, but I haven't looked.

**Comment by 25db41cf-51b5-41a8-9f68-03a0fcf7cb17** [comment]
I think it should be documented properly.

In roughly two weeks I will have some time to look into it. 
So I could probably document the current behaviour by the start of December(unless someone beats me to it)
