### ISSUE TITLE
trace module cli does not write cover files

### ISSUE THREAD

**Issue by 918fd5bb-b946-4ec7-91c7-095b988657d6** [python/cpython#76089]
BPO | [31908](https://bugs.python.org/issue31908)
--- | :---
Nosy | @rhettinger, @abalkin, @berkerpeksag, @serhiy-storchaka, @selik, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#4205</li><li>python/cpython#6666</li><li>python/cpython#6667</li><li>python/cpython#6668</li><li>python/cpython#8664</li><li>python/cpython#8732</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-31.02:55:06.847>
labels = ['3.7', 'type-bug', 'library']
title = 'trace module cli does not write cover files'
updated_at = <Date 2018-08-11.06:28:37.697>
user = 'https://bugs.python.org/MichaelSelik'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-11.06:28:37.697>
actor = 'berker.peksag'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-10-31.02:55:06.847>
creator = 'Michael Selik'
dependencies = []
files = []
hgrepos = []
issue_num = 31908
keywords = ['patch']
message_count = 13.0
messages = ['305268', '305269', '305341', '305343', '305347', '305367', '306173', '315980', '315981', '315984', '323058', '323401', '323403']
nosy_count = 8.0
nosy_names = ['rhettinger', 'belopolsky', 'berker.peksag', 'serhiy.storchaka', 'selik', 'Michael Selik', 'ZackerySpytz', 'miss-islington']
pr_nums = ['4205', '6666', '6667', '6668', '8664', '8732']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31908'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 918fd5bb-b946-4ec7-91c7-095b988657d6** [comment]
The trace module command-line utility doesn't write cover files. I've noticed this issue for some years now. It works fine in Python 2. When using Python 3, no ".cover" files are written, regardless of how "--coverdir" is specified.

    mike on macbook in ~/
    $ echo 'print("hello")' > foo.py

    mike on macbook in ~/
    $ python -m trace --count foo.py
    hello

    mike on macbook in ~/
    $ ls *.cover
    ls: *.cover: No such file or directory


My apologies if this is a duplicate bug. I searched the tracker and Google for a while, but couldn't find a relevant issue.

**Comment by rhettinger** [comment]
It worked in Python 3.4, but not afterwards.

**Comment by 918fd5bb-b946-4ec7-91c7-095b988657d6** [comment]
The problem appears to be a mistake in commit f026dae130bf6f9015c4b212f16852ba4a3f3dec

https://github.com/python/cpython/commit/f026dae130bf6f9015c4b212f16852ba4a3f3dec

This made the writing of cover files conditional on ``show_missing`` which is the option to mark lines which weren't executed with several angle brackets ">>>>>".

https://github.com/python/cpython/blob/3.5/Lib/trace.py#L326

    mike on mac in ~/
    $ python -m trace --count foo.py
    hello

    mike on mac in ~/
    $ ls *.cover
    ls: *.cover: No such file or directory

    mike on mac in ~/
    $ python -m trace --count -m foo.py
    hello

    mike on mac in ~/
    $ ls *.cover
    -rw-r--r--  1 mike  staff    22B Oct 31 15:40 foo.cover

**Comment by 918fd5bb-b946-4ec7-91c7-095b988657d6** [comment]
While writing a patch for this, I noticed the ``lnotab`` parameter seems nearly unused. It's a dict, but is only used for its keys.

https://github.com/python/cpython/blob/master/Lib/trace.py#L333

Further, the choice to count unreached lines only when ``show_missing`` was set seems inconsistent.

https://github.com/python/cpython/blob/master/Lib/trace.py#L335

https://github.com/python/cpython/blob/master/Lib/trace.py#L280

**Comment by 918fd5bb-b946-4ec7-91c7-095b988657d6** [comment]
Ok, pull request submitted:
https://github.com/python/cpython/pull/4205

**Comment by berkerpeksag** [comment]
I think the first part of your patch also fixes bpo-26818. Could you adapt the test there and add a test case for the problem in this issue?

**Comment by 93fb711d-fdf4-46a8-9dad-0481f9581972** [comment]
You're referring to something like this:

\+    def test_count_and_summary(self):
\+        name = TESTFN + '.py'
\+        with open(name, 'w') as fd:
\+            self.addCleanup(unlink, name)
\+            fd.write("""\\
+x = 1
+y = 2
\+
+def f():
\+    return x + y
\+
+for i in range(10):
\+    f()
\+            """)
\+        status, stdout, stderr = assert_python_ok('-m', 'trace', '-cs', name)
\+        self.assertEqual(status, 0)
\+        self.assertIn(b'lines   cov%   module   (path)', stdout)
\+        self.assertIn(('6   100%%   %s   (%s)' % (TESTFN, name)).encode(), stdout)
+

?
