### ISSUE TITLE
Python should support VxWorks RTOS

### ISSUE THREAD

**Issue by 6858a80c-8457-46a1-887f-9e6758175163** [python/cpython#76085]
BPO | [31904](https://bugs.python.org/issue31904)
--- | :---
Nosy | @gpshead, @vstinner, @tiran, @bitdancer, @asvetlov, @ambv, @jimjjewett, @izbyshev, @kuhlenough, @miss-islington, @pxinwr
PRs | <li>python/cpython#4179</li><li>python/cpython#4184</li><li>python/cpython#11951</li><li>python/cpython#11968</li><li>python/cpython#12051</li><li>python/cpython#12118</li><li>python/cpython#12157</li><li>python/cpython#12304</li><li>python/cpython#12305</li><li>python/cpython#12319</li><li>python/cpython#12321</li><li>python/cpython#12428</li><li>python/cpython#12646</li><li>python/cpython#12648</li><li>python/cpython#12670</li><li>python/cpython#12719</li><li>python/cpython#12833</li><li>python/cpython#13486</li><li>python/cpython#13535</li><li>python/cpython#19447</li><li>python/cpython#19448</li><li>python/cpython#20254</li><li>python/cpython#20256</li><li>python/cpython#21675</li><li>python/cpython#21821</li><li>python/cpython#23391</li><li>python/cpython#23394</li><li>python/cpython#23419</li><li>python/cpython#23473</li><li>python/cpython#21687</li><li>python/cpython#23489</li><li>python/cpython#23507</li><li>python/cpython#23518</li><li>python/cpython#23530</li><li>python/cpython#23716</li><li>python/cpython#23718</li><li>python/cpython#23741</li><li>python/cpython#23776</li><li>python/cpython#23815</li><li>python/cpython#23886</li><li>python/cpython#23920</li><li>python/cpython#24191</li><li>python/cpython#25965</li><li>python/cpython#25983</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-30.19:56:33.760>
labels = ['type-feature', '3.10', 'build']
title = 'Python should support VxWorks RTOS'
updated_at = <Date 2021-05-08.11:20:17.167>
user = 'https://github.com/kuhlenough'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-08.11:20:17.167>
actor = 'Alex.Willmer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2017-10-30.19:56:33.760>
creator = 'Brian Kuhl'
dependencies = []
files = []
hgrepos = []
issue_num = 31904
keywords = ['patch']
message_count = 46.0
messages = ['305249', '305511', '305657', '305690', '305869', '305877', '315365', '336680', '336742', '337083', '337867', '337909', '338964', '339059', '339898', '340244', '340245', '340310', '340385', '340406', '340409', '343004', '343008', '366073', '374361', '374460', '374469', '382014', '382020', '382021', '382023', '382198', '382218', '382276', '382525', '382793', '382807', '383009', '383096', '383097', '383098', '383226', '383259', '383467', '385461', '393247']
nosy_count = 11.0
nosy_names = ['gregory.p.smith', 'vstinner', 'christian.heimes', 'r.david.murray', 'asvetlov', 'lukasz.langa', 'Jim.Jewett', 'izbyshev', 'Brian Kuhl', 'miss-islington', 'pxinwr']
pr_nums = ['4179', '4184', '11951', '11968', '12051', '12118', '12157', '12304', '12305', '12319', '12321', '12428', '12646', '12648', '12670', '12719', '12833', '13486', '13535', '19447', '19448', '20254', '20256', '21675', '21821', '23391', '23394', '23419', '23473', '21687', '23489', '23507', '23518', '23530', '23716', '23718', '23741', '23776', '23815', '23886', '23920', '24191', '25965', '25983']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31904'
versions = ['Python 3.10']
```

</p></details>

**Comment by 6858a80c-8457-46a1-887f-9e6758175163** [comment]
With the trend to use REST APIs between the cloud and the IoT there is increasing interest in Python on embedded devices.  Cloud developer’s typical release a reference REST implementation of JSON and/or Python on Linux and leave it to the device developer to adapt it to their platform.   While many devices use eLinux, others with IP and/or hard real-time constraints need a commercial RTOS platform. 

Currently the automake configure explicitly prevents configuration of VxWorks as a build target.

I'll provide a pull request referencing this issue with the required changes.

**Comment by terryjreedy** [comment]
The following might be relevant to this issue:
https://www.python.org/dev/peps/pep-0011/#supporting-platforms

**Comment by vstinner** [comment]
To support a new platform, you need a developer who can support this platform next years, a working buildbot, etc. You can start a discussion on python-dev to get a first feedback.

Without a strong support, this issue should be fixed a REJECTED and a patch should be maintainted out of the tree. Since the PR seems small, it should be "easy" to keep a fork of CPython up to date.

**Comment by vstinner** [comment]
FYI I already started a thread on python-dev:
[Python-Dev] Partial support of a platform
https://mail.python.org/pipermail/python-dev/2017-November/150238.html

**Comment by 6858a80c-8457-46a1-887f-9e6758175163** [comment]
I'm quite happy to take on maintainer role for Python on VxWorks, so I think we can get that one solved. 

Enabling a build bot for cross compile of propitiatory OS presents a number of legal licensing issues that outside my control. And I'll discuss it internally at Wind River. However I think it is in line with where our customers want us to go, so well worth pursuing. 

I'll keep this pull request active and up to date, till the broader issues you have raised can be resolved.      

I'll post a proposal on the mailing list after I consulted within Wind River.

Many thanks for your interest and support.

**Comment by bitdancer** [comment]
I'm not sure what licensing issues you are talking about, but setting up a buildbot shouldn't normally run into any.  As long as you have a license to the run the OS, the fact that you are using it to receive jobs from our build master and run them shouldn't be a problem.  You can keep the whole thing behind a firewall in a DMZ: the slave makes outbound connections to pick up its jobs.

On the other hand, the logistics of setting up a cross compile buildbot might be a bit complex, I've never done that.  You might need specific support from our build master.  In any case, the python-buldbots mailing list is the place to talk if you want to/can pursue this.

**Comment by encukou** [comment]
All linked PRs are now closed. I plan to close the issue in a week if there are no objections.

I would advise anyone interested in supporting VxWorks to add themselves to [the experts list](https://devguide.python.org/core-developers/experts/#platforms).

**Comment by vstinner** [comment]
Let's close the issue. I helped to get some VxWorks changes merged, but the issue is now idle since 2021.
