### ISSUE TITLE
localeconv() should decode numeric fields from LC_NUMERIC encoding, not from LC_CTYPE encoding

### ISSUE THREAD

**Issue by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [python/cpython#76081]
BPO | [31900](https://bugs.python.org/issue31900)
--- | :---
Nosy | @malemburg, @vstinner, @skrah, @serhiy-storchaka, @andreas-schwab, @stratakis
PRs | <li>python/cpython#4174</li><li>python/cpython#5191</li><li>python/cpython#5192</li>
Files | <li>[inconsistent_locale_encodings.py](https://bugs.python.org/file47246/inconsistent_locale_encodings.py "Uploaded as text/plain at 2017-10-30.16:14:00 by @vstinner")</li><li>[lc_numeric.py](https://bugs.python.org/file47377/lc_numeric.py "Uploaded as text/plain at 2018-01-10.16:59:11 by @vstinner")</li><li>[lc_numeric2.py](https://bugs.python.org/file47386/lc_numeric2.py "Uploaded as text/plain at 2018-01-15.15:41:31 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-11-28.16:53:58.445>
created_at = <Date 2017-10-30.13:41:05.693>
labels = ['3.8', '3.7', 'tests']
title = 'localeconv() should decode numeric fields from LC_NUMERIC encoding, not from LC_CTYPE encoding'
updated_at = <Date 2018-11-28.16:53:58.444>
user = 'https://github.com/stratakis'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-28.16:53:58.444>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-11-28.16:53:58.445>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-30.13:41:05.693>
creator = 'cstratak'
dependencies = []
files = ['47246', '47377', '47386']
hgrepos = []
issue_num = 31900
keywords = ['patch']
message_count = 33.0
messages = ['305227', '305229', '305230', '305231', '305235', '305236', '305237', '307230', '308561', '309774', '309960', '309962', '309966', '309969', '309970', '309971', '309973', '309974', '309975', '309977', '309978', '309980', '309981', '309986', '309987', '309988', '309989', '309993', '310020', '310940', '327905', '330610', '330611']
nosy_count = 6.0
nosy_names = ['lemburg', 'vstinner', 'skrah', 'serhiy.storchaka', 'schwab', 'cstratak']
pr_nums = ['4174', '5191', '5192']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31900'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
Original bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1484497

It seems that on the development branch of Fedora, when we updated glibc from 2.26 to 2.26.90, test_float_with_comma started failing.

Details from the original bug report:

Under certain circumstances, when LC_NUMERIC is fr_FR.ISO8859-1 but LC_ALL is C.UTF-8, locale.localeconv() fails with
    UnicodeDecodeError: 'locale' codec can't decode byte 0xa0 in position 0: Invalid or incomplete multibyte or wide character

Apparently, the thousands separator (or something else) in the lconv is "\\xa0" (unbreakable space in fr_FR.ISO8859-1), and it's being decoded with UTF-8.

This is tripped by Python's test suite, namely test_float.GeneralFloatCases.test_float_with_comma

**Comment by vstinner** [comment]
I can reproduce the bug with Python 3.6 on Fedora 26 and these locales:

* LC_ALL = LC_CTYPE = fr_FR (encoding = ISO8859-1)
* LC_NUMERIC= es_MX.utf8 (encoding = UTF-8)


Good: LC_NUMERIC = LC_CTYPE = LC_ALL = "es_MX.utf8"

haypo@selma$ env -i python3 -c 'import locale; locale.setlocale(locale.LC_ALL, "es_MX.utf8"); print(ascii(locale.localeconv()["thousands_sep"]))'

=\> '\\u2009'


Bug: LC_NUMERIC = "es_MX.utf8" but LC_CTYPE = LC_ALL = "fr_FR"

haypo@selma$ env -i python3 -c 'import locale; locale.setlocale(locale.LC_ALL, "fr_FR"); locale.setlocale(locale.LC_NUMERIC, "es_MX.utf8"); print(ascii(locale.localeconv()["thousands_sep"]))'

=\> '\\xe2\\x80\\x89'

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
Tested the PR on a system with glibc 2.26.90 where the test was failing, and it successfully passed.

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-28604. See also bpo-25812.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Same as bpo-7442, I think.

**Comment by vstinner** [comment]
Oh wow, this bug is older than what I expected :-) I added support for non-ASCII thousands separator in 2012:

https://bugs.python.org/issue13706#msg151733

**Comment by vstinner** [comment]
inconsistent_locale_encodings.py of closed issue bpo-7442 is interesting: I copy it here.

**Comment by 12c7b821-ad6f-4235-91d8-57b2aacb2dfc** [comment]
Pinging here. Is there some way I can help to move the issue forward?
