### ISSUE TITLE
Use malloc_usable_size() in pymalloc for realloc

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76092]
BPO | [31911](https://bugs.python.org/issue31911)
--- | :---
Nosy | @pitrou, @vstinner, @skrah, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.01:26:37.104>
created_at = <Date 2017-10-31.17:57:44.441>
labels = ['interpreter-core', '3.7', 'performance']
title = 'Use malloc_usable_size() in pymalloc for realloc'
updated_at = <Date 2017-11-24.01:26:37.102>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.01:26:37.102>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.01:26:37.104>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-10-31.17:57:44.441>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31911
keywords = []
message_count = 3.0
messages = ['305319', '306402', '306870']
nosy_count = 4.0
nosy_names = ['pitrou', 'vstinner', 'skrah', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31911'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
[Objects/obmalloc.c](https://github.com/python/cpython/blob/main/Objects/obmalloc.c) contains an interesting comment:

```c
    if (!address_in_range(p, pool)) {
        /* pymalloc is not managing this block.
```


           If nbytes <= SMALL_REQUEST_THRESHOLD, it's tempting to try to take
           over this block.  However, if we do, we need to copy the valid data
           from the C-managed block to one of our blocks, and there's no
           portable way to know how much of the memory space starting at p is
           valid.

```c
           As bug 1185883 pointed out the hard way, it's possible that the
           C-managed block is "at the end" of allocated VM space, so that a
           memory fault can occur if we try to copy nbytes bytes starting at p.
           Instead we punt: let C continue to manage this block. */
        return 0;
    }
```


See also bpo-1185883.

We don't have to guess, it's possible to get the size of a memory block allocated by malloc() with:

* malloc_usable_size(ptr): available at least on Linux
* \_msize(ptr): Windows

Maybe we could add a "msize" field to PyMemAllocatorEx? See also bpo-18835 whic adds PyMem_AlignedAlloc() and so already modify (and rename PyMemAllocatorEx).

See also bpo-31626, but I'm not sure that it would help for \_PyMem_DebugRawRealloc().

**Comment by pitrou** [comment]
What would be the point of this?  This would complicate the code with platform-specific code and it's not obvious that it would change runtime performance in any significant way.

**Comment by vstinner** [comment]
I agree. I don't think that it's worth it to overcompilates the API.

I proposed this change since we may change the API to add PyMem_AlignedAlloc(). Since I just rejected bpo-18835, it's no more the case.

I close this issue as rejected.
