### ISSUE TITLE
test_socket.test_create_connection() failed with EADDRNOTAVAIL (err 99)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76091]
BPO | [31910](https://bugs.python.org/issue31910)
--- | :---
Nosy | @vstinner, @berkerpeksag, @vadmium, @serhiy-storchaka
PRs | <li>python/cpython#4206</li><li>python/cpython#4208</li><li>python/cpython#4209</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.13:53:09.547>
created_at = <Date 2017-10-31.17:05:22.577>
labels = ['3.7', 'type-bug', 'tests']
title = 'test_socket.test_create_connection() failed with EADDRNOTAVAIL (err 99)'
updated_at = <Date 2017-11-08.13:53:09.545>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.13:53:09.545>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.13:53:09.547>
closer = 'vstinner'
components = ['Tests']
creation = <Date 2017-10-31.17:05:22.577>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31910
keywords = ['patch']
message_count = 8.0
messages = ['305316', '305336', '305346', '305353', '305376', '305377', '305821', '305842']
nosy_count = 4.0
nosy_names = ['vstinner', 'berker.peksag', 'martin.panter', 'serhiy.storchaka']
pr_nums = ['4206', '4208', '4209']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31910'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
On my [PR 4200](https://github.com/python/cpython/pull/4200) which is unrelated to networking, the following test failed once.

FAIL: test_create_connection (test.test_socket.NetworkConnectionNoServer)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/travis/build/python/cpython/Lib/test/test_socket.py", line 4537, in test_create_connection
    self.assertIn(cm.exception.errno, expected_errnos)
AssertionError: 99 not found in [111, 101]
```



With error codes:

* 99: EADDRNOTAVAIL: Cannot assign requested address
* 111: ECONNREFUSED: Connection refused
* 101: ENETUNREACH: Network is unreachable

Maybe we shold include EADDRNOTAVAIL in the expected error codes?

**Comment by serhiy-storchaka** [comment]
I'm not a networking but it seems reasonable. If I understand correctly, EADDRNOTAVAIL can be raised on the Travis CI when a large number of network connections are created simultaneously by other CI tests.

Or maybe just repeat the test if EADDRNOTAVAIL is raised?

**Comment by vstinner** [comment]
> Or maybe just repeat the test if EADDRNOTAVAIL is raised?

I don't think that it's worth it.

**Comment by vstinner** [comment]
New changeset 280c22a82a6756e9caffef031c564fd98f1b50e7 by Victor Stinner in branch 'master':
Fix test_socket.test_create_connection() (bpo-4206)
https://github.com/python/cpython/commit/280c22a82a6756e9caffef031c564fd98f1b50e7

**Comment by vstinner** [comment]
New changeset 89b84b026b389f3c61cbbc5ee89afd8248721b0d by Victor Stinner (Miss Islington (bot)) in branch '3.6':
Fix test_socket.test_create_connection() (GH-4206) (bpo-4208)
https://github.com/python/cpython/commit/89b84b026b389f3c61cbbc5ee89afd8248721b0d

**Comment by vstinner** [comment]
New changeset 4b73a79e796c3832be0cfd45bc27f15aea32b621 by Victor Stinner (Miss Islington (bot)) in branch '2.7':
Fix test_socket.test_create_connection() (GH-4206) (bpo-4209)
https://github.com/python/cpython/commit/4b73a79e796c3832be0cfd45bc27f15aea32b621

**Comment by berkerpeksag** [comment]
I don't see this failure on Travis for a while now. Can this issue be closed?

**Comment by vstinner** [comment]
> I don't see this failure on Travis for a while now. Can this issue be closed?

Since the failure occurred randomly, we cannot make sure that the bug is really fixed. Usually in this case, I close the issue, but reopen it if the bug comes back.

So yes, I close the issue right now.
