### ISSUE TITLE
ensurepip not honoring value of $(DESTDIR) - pip not installed

### ISSUE THREAD

**Issue by 5f090b23-0807-4e4a-984f-dca51a956842** [python/cpython#76097]
BPO | [31916](https://bugs.python.org/issue31916)
--- | :---
Nosy | @yan12125, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-26.13:21:49.782>
created_at = <Date 2017-11-01.02:08:45.271>
labels = ['type-bug', 'expert-installation']
title = 'ensurepip not honoring value of $(DESTDIR) - pip not installed'
updated_at = <Date 2019-02-26.13:21:49.780>
user = 'https://bugs.python.org/multimiler'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-26.13:21:49.780>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2019-02-26.13:21:49.782>
closer = 'cheryl.sabella'
components = ['Installation']
creation = <Date 2017-11-01.02:08:45.271>
creator = 'multimiler'
dependencies = []
files = []
hgrepos = []
issue_num = 31916
keywords = []
message_count = 3.0
messages = ['305351', '305357', '336663']
nosy_count = 3.0
nosy_names = ['yan12125', 'cheryl.sabella', 'multimiler']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31916'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5f090b23-0807-4e4a-984f-dca51a956842** [comment]
I am building python from source for installation at /opt/python-3.6.3.  The result of the build will be installed in /somewhere/deb-pkg-build-dir.  I configure, build, and install, the package as follows:

./configure --prefix=/opt/python-$VER --enable-optimizations --with-ensurepip=install
make
make install DESTDIR=/somewhere/deb-pkg-build-dir

At the very end of the build log I find:

Requirement already satisfied: setuptools in /opt/python-3.6.3/lib/python3.6/site-packages

As a result PIP is not installed.  This is an error.  The pip installation process should be looking in $(DESTDIR)/opt/python-3.6.3.  Instead it is looking at /opt/python-3.6.3/... which is the python installation on the current build host -- NOT INSTALLED BY THIS BUILD.

In the top-level Makefile.pre I find the following that runs ensurepip to install pip:

install:  commoninstall bininstall maninstall
        if test "x$(ENSUREPIP)" != "xno"  ; then \\
                case $(ENSUREPIP) in \\
                        upgrade) ensurepip="--upgrade" ;; \\
                        install|*) ensurepip="" ;; \\
                esac; \\
                $(RUNSHARED) $(PYTHON_FOR_BUILD) -m ensurepip \\
                        $$ensurepip --root=$(DESTDIR)/ ; \\
        fi

As you can see $(DESTDIR) is passed into ensurepip, but it is never used when checking for pip existence.

**Comment by d732c26f-ecfa-4c92-9f00-a1eacb6965bc** [comment]
This is a pip bug https://github.com/pypa/pip/issues/3063
