### ISSUE TITLE
PyMem_Malloc() should guarantee alignof(max_align_t)

### ISSUE THREAD

**Issue by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [python/cpython#76093]
BPO | [31912](https://bugs.python.org/issue31912)
--- | :---
Nosy | @Yhg1s, @gpshead, @vstinner, @skrah

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-10-31.18:01:35.929>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'PyMem_Malloc() should guarantee alignof(max_align_t)'
updated_at = <Date 2018-01-31.10:55:10.425>
user = 'https://github.com/skrah'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-31.10:55:10.425>
actor = 'fweimer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-10-31.18:01:35.929>
creator = 'skrah'
dependencies = []
files = []
hgrepos = []
issue_num = 31912
keywords = []
message_count = 4.0
messages = ['305320', '305322', '305324', '311322']
nosy_count = 5.0
nosy_names = ['twouters', 'gregory.p.smith', 'vstinner', 'skrah', 'fweimer']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31912'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
This is related to bpo-27987 and bpo-20064 and perhaps the pymalloc patch
from bpo-18835.

I think PyMem_Malloc() should guarantee alignof(max_align_t).

It actually did before the "#define PYMEM_FUNCS PYOBJ_FUNCS" optimization,
so we have a sort of regression here.

**Comment by vstinner** [comment]
> I think PyMem_Malloc() should guarantee alignof(max_align_t).

Do you mean the C++ std::max_align_t? Does C99 have something like that?

The Linux malloc() manual page says:

"The malloc() and calloc() functions return a pointer to  the  allocated memory,  which  is  suitably  aligned for any built-in type."

But I don't know the list of C built-in types.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
> Do you mean the C++ std::max_align_t? Does C99 have something like that?
> 
> The Linux malloc() manual page says:
> 
> "The malloc() and calloc() functions return a pointer to  the  allocated memory,  which  is  suitably  aligned for any built-in type."

C11 has max_align_t, but also for C99 "any builtin type" means 16 byte alignment
for long double on x64, so malloc() and calloc() are required to align 16 bytes
with -std=c99 (and earlier).

max_align_t is just a shorthand to express the concept.
