### ISSUE TITLE
Missing definition of HAVE_SYSCALL_GETRANDOM

### ISSUE THREAD

**Issue by 8261aa84-e702-455d-ad8f-b513a205490a** [python/cpython#76090]
BPO | [31909](https://bugs.python.org/issue31909)
--- | :---
Nosy | @benjaminp, @Kentzo
PRs | <li>python/cpython#4185</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-10-31.18:04:44.297>
created_at = <Date 2017-10-31.06:29:04.872>
labels = ['build', '3.7']
title = 'Missing definition of HAVE_SYSCALL_GETRANDOM'
updated_at = <Date 2017-10-31.18:04:44.296>
user = 'https://github.com/Kentzo'
```

bugs.python.org fields:
```python
activity = <Date 2017-10-31.18:04:44.296>
actor = 'Ilya.Kulakov'
assignee = 'none'
closed = True
closed_date = <Date 2017-10-31.18:04:44.297>
closer = 'Ilya.Kulakov'
components = ['Build']
creation = <Date 2017-10-31.06:29:04.872>
creator = 'Ilya.Kulakov'
dependencies = []
files = []
hgrepos = []
issue_num = 31909
keywords = ['patch']
message_count = 5.0
messages = ['305270', '305271', '305272', '305273', '305321']
nosy_count = 2.0
nosy_names = ['benjamin.peterson', 'Ilya.Kulakov']
pr_nums = ['4185']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31909'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
Python 3.5 and 3.6 in their corresponding configure.ac try to detect presence of sys_getrandom. The result is written into the `HAVE_GETRANDOM_SYSCALL` definition.

libexpact checks for `HAVE_SYSCALL_GETRANDOM` and since it's not defined, does not use it. This fails compilation with up to date libexpact due to a new condition [1].

[1] https://github.com/python/cpython/blob/master/Modules/expat/xmlparse.c#L87-L91

**Comment by benjaminp** [comment]
This is supposed to be handled by setup.py defining XML_POOR_ENTROTPY. Are you doing something non-standard?

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
Just compiling Python 3.6.3 from sources on Ubuntu 16.04

Is there any reason to fall back to XML_POOR_ENTROTPY when proper source is actually available?

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
nvm my last question.

My process is as per README: ./configure && make

I'll take a further look at what's wrong.

**Comment by 8261aa84-e702-455d-ad8f-b513a205490a** [comment]
Not a bug in Python.
