### ISSUE TITLE
Bring together logic for entering/leaving a frame in frameobject.c

### ISSUE THREAD

**Issue by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [python/cpython#76102]
BPO | [31921](https://bugs.python.org/issue31921)
--- | :---
Nosy | @rhettinger, @pdox
PRs | <li>python/cpython#4226</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-05.10:51:18.703>
created_at = <Date 2017-11-02.09:56:19.288>
labels = ['interpreter-core', '3.7', 'performance']
title = 'Bring together logic for entering/leaving a frame in frameobject.c'
updated_at = <Date 2017-11-05.10:51:52.084>
user = 'https://github.com/pdox'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-05.10:51:52.084>
actor = 'pdox'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-05.10:51:18.703>
closer = 'pdox'
components = ['Interpreter Core']
creation = <Date 2017-11-02.09:56:19.288>
creator = 'pdox'
dependencies = []
files = []
hgrepos = []
issue_num = 31921
keywords = ['patch']
message_count = 3.0
messages = ['305408', '305460', '305590']
nosy_count = 2.0
nosy_names = ['rhettinger', 'pdox']
pr_nums = ['4226']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue31921'
versions = ['Python 3.7']
```

</p></details>

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
This is a refactor to move all the code involved in entering a frame (making it the active frame for the current tstate) and leaving a frame (removing it as an active frame, possibly destructing it or making it GC tracked) into private functions in frameobject.c.

The underlying goal of this change is to make it possible to add (as a performance feature) stack-allocated frames, in addition to the usual heap-allocated ones.

**Comment by rhettinger** [comment]
I don't think we should be re-arranging the core of the language to facilitate your language experiments.  We need to know that is this is valuable for other people, not just you.

**Comment by 460e3b73-ef06-4a68-85e3-d1897b1b6722** [comment]
Raymond, this is not an experiment, but the beginning of a sustained effort to improve locality during execution, to make more effective use of CPU cache lines. Rather than discuss the details of this change one PR at a time, I will close this issue for now, and open a discussion on python-dev.
