### ISSUE TITLE
Misspelled "loading" in Doc/includes/sqlite3/load_extension.py

### ISSUE THREAD

**Issue by f3655659-9765-4954-9e8d-4b571f6e2a6c** [python/cpython#76104]
BPO | [31923](https://bugs.python.org/issue31923)
--- | :---
Nosy | @berkerpeksag, @wybiral
PRs | <li>python/cpython#4227</li><li>python/cpython#4281</li><li>python/cpython#4282</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-04.23:12:02.813>
created_at = <Date 2017-11-02.13:52:25.278>
labels = ['type-bug', '3.7', 'docs']
title = 'Misspelled "loading" in Doc/includes/sqlite3/load_extension.py'
updated_at = <Date 2017-11-04.23:12:02.812>
user = 'https://github.com/wybiral'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-04.23:12:02.812>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-04.23:12:02.813>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-11-02.13:52:25.278>
creator = 'davywtf'
dependencies = []
files = []
hgrepos = []
issue_num = 31923
keywords = ['patch']
message_count = 5.0
messages = ['305423', '305573', '305574', '305575', '305576']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'davywtf']
pr_nums = ['4227', '4281', '4282']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31923'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by f3655659-9765-4954-9e8d-4b571f6e2a6c** [comment]
Line #14 of [Doc/includes/sqlite3/load_extension.py](https://github.com/python/cpython/blob/main/Doc/includes/sqlite3/load_extension.py) reads:

\# disable extension laoding again

**Comment by berkerpeksag** [comment]
New changeset aafece7a9e010075fff4420cfbb16f1ec0342698 by Berker Peksag (davy wybiral) in branch 'master':
bpo-31923: Fix spelling in sqlite3 docs (GH-4227)
https://github.com/python/cpython/commit/aafece7a9e010075fff4420cfbb16f1ec0342698

**Comment by berkerpeksag** [comment]
New changeset 5c0100aec014b9e0a66884468cbfa3ac01e4bfbb by Berker Peksag (Miss Islington (bot)) in branch '3.6':
bpo-31923: Fix spelling in sqlite3 docs (GH-4227)
https://github.com/python/cpython/commit/5c0100aec014b9e0a66884468cbfa3ac01e4bfbb

**Comment by berkerpeksag** [comment]
New changeset 4376a2275967971a2f9586028347d6ed4ed6ef13 by Berker Peksag (Miss Islington (bot)) in branch '2.7':
bpo-31923: Fix spelling in sqlite3 docs (GH-4227)
https://github.com/python/cpython/commit/4376a2275967971a2f9586028347d6ed4ed6ef13

**Comment by berkerpeksag** [comment]
Thanks, Davy!
