### ISSUE TITLE
Convert selectmodule.c to Argument Clinic

### ISSUE THREAD

**Issue by taleinat** [python/cpython#76119]
BPO | [31938](https://bugs.python.org/issue31938)
--- | :---
Nosy | @vstinner, @taleinat, @larryhastings, @serhiy-storchaka, @asottile, @miss-islington
PRs | <li>python/cpython#4265</li><li>python/cpython#8796</li><li>python/cpython#21066</li><li>python/cpython#21067</li><li>python/cpython#21097</li><li>python/cpython#21098</li><li>python/cpython#21098</li><li>python/cpython#21098</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-06-30.20:04:41.754>
created_at = <Date 2017-11-03.21:20:30.369>
labels = ['type-feature', '3.8', 'expert-argument-clinic']
title = 'Convert selectmodule.c to Argument Clinic'
updated_at = <Date 2020-06-23.22:28:18.280>
user = 'https://github.com/taleinat'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-23.22:28:18.280>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-06-30.20:04:41.754>
closer = 'taleinat'
components = ['Argument Clinic']
creation = <Date 2017-11-03.21:20:30.369>
creator = 'taleinat'
dependencies = []
files = []
hgrepos = []
issue_num = 31938
keywords = ['patch']
message_count = 14.0
messages = ['305514', '305520', '305526', '320439', '320805', '323651', '372138', '372206', '372208', '372210', '372211', '372212', '372214', '372215']
nosy_count = 6.0
nosy_names = ['vstinner', 'taleinat', 'larry', 'serhiy.storchaka', 'Anthony Sottile', 'miss-islington']
pr_nums = ['4265', '8796', '21066', '21067', '21097', '21098', '21098', '21098']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31938'
versions = ['Python 3.8']
```

</p></details>

**Comment by taleinat** [comment]
Continuing the work begun as part of issue bpo-20182, this is regarding the Argument Clinic conversion of [Modules/selectmodule.c.h](https://github.com/python/cpython/blob/main/Modules/selectmodule.c.h).

I have a complete conversion ready and will create a PR momentarily.

**Comment by taleinat** [comment]
See [PR 4265](https://github.com/python/cpython/pull/4265).

**Comment by vstinner** [comment]
While reviewing [PR 4265](https://github.com/python/cpython/pull/4265), I noticed that the return type like "-\> None" or "-\> int" is removed from the function definition, so the PR removes this information. But it seems to be a limitation of Argument Clinic: I opened the issue bpo-31939.

IHMO it's not a blocker issue. We can add it back later, once the issue bpo-31939 is implemented.
