### ISSUE TITLE
"5. The import system" grammatical error

### ISSUE THREAD

**Issue by 286ff9e1-f748-4503-824f-b5380c57d3a6** [python/cpython#76117]
BPO | [31936](https://bugs.python.org/issue31936)
--- | :---
Nosy | @warsaw, @Urhixidur
PRs | <li>python/cpython#4257</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-03.20:46:04.953>
created_at = <Date 2017-11-03.17:19:46.042>
labels = ['type-feature', '3.7', 'docs']
title = '"5. The import system" grammatical error'
updated_at = <Date 2017-11-03.20:46:04.952>
user = 'https://github.com/Urhixidur'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-03.20:46:04.952>
actor = 'barry'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-03.20:46:04.953>
closer = 'barry'
components = ['Documentation']
creation = <Date 2017-11-03.17:19:46.042>
creator = 'Daniel.U..Thibault'
dependencies = []
files = []
hgrepos = []
issue_num = 31936
keywords = ['patch']
message_count = 3.0
messages = ['305489', '305491', '305506']
nosy_count = 3.0
nosy_names = ['barry', 'docs@python', 'Daniel.U..Thibault']
pr_nums = ['4257']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31936'
versions = ['Python 3.7']
```

</p></details>

**Comment by 286ff9e1-f748-4503-824f-b5380c57d3a6** [comment]
https://docs.python.org/3/reference/import.html#importsystem
"Other mechanisms for invoking the import system (such as importlib.import_module()) may choose to subvert \_\_import__() and use its own solution to implement import semantics."
should be
"Other mechanisms for invoking the import system (such as importlib.import_module()) may choose to subvert \_\_import__() and use their own solution to implement import semantics."

**Comment by warsaw** [comment]
Re-reading the paragraph now, it also parsed weirdly for me.  See the linked PR for a suggested improvement, along with your change.

Thanks!

**Comment by warsaw** [comment]
New changeset 93952f881500053057c2e08c4b253ac61233d7db by Barry Warsaw in branch 'master':
Fix a grammatical problem and reword for clarity. (bpo-4257)
https://github.com/python/cpython/commit/93952f881500053057c2e08c4b253ac61233d7db
