### ISSUE TITLE
Add the term "dunder" to the glossary

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#76118]
BPO | [31937](https://bugs.python.org/issue31937)
--- | :---
Nosy | @freddrake, @warsaw, @brettcannon, @rhettinger, @pitrou, @bitdancer, @serhiy-storchaka, @matrixise, @Mariatta
PRs | <li>python/cpython#5582</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/freddrake'
closed_at = <Date 2018-02-19.18:47:12.529>
created_at = <Date 2017-11-03.20:57:49.642>
labels = ['easy', 'type-feature', '3.7', 'docs']
title = 'Add the term "dunder" to the glossary'
updated_at = <Date 2018-02-19.18:47:12.528>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-19.18:47:12.528>
actor = 'brett.cannon'
assignee = 'fdrake'
closed = True
closed_date = <Date 2018-02-19.18:47:12.529>
closer = 'brett.cannon'
components = ['Documentation']
creation = <Date 2017-11-03.20:57:49.642>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 31937
keywords = ['patch', 'easy']
message_count = 14.0
messages = ['305509', '305510', '305512', '305513', '305542', '305569', '305786', '305791', '305792', '305946', '307002', '311797', '311798', '311800']
nosy_count = 10.0
nosy_names = ['fdrake', 'barry', 'brett.cannon', 'rhettinger', 'pitrou', 'r.david.murray', 'docs@python', 'serhiy.storchaka', 'matrixise', 'Mariatta']
pr_nums = ['5582']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31937'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by brettcannon** [comment]
The term "dunder" is used out in the community regularly, but if you have never been exposed to it before it can seem a little odd without context.

**Comment by warsaw** [comment]
-1 until we have something we can call a "mifflin".

(Kidding of course!)

**Comment by Mariatta** [comment]
> until we have something we can call a "mifflin".

Name of next GitHub bot? :P

**Comment by Mariatta** [comment]
Anyway, +1 to adding dunder to glossary.

**Comment by serhiy-storchaka** [comment]
I think it shouldn't be added as a separate entry, but just mentioned in [1] and [2], and added to the index.

[1] https://docs.python.org/3/glossary.html#term-special-method
[2] https://docs.python.org/3/reference/datamodel.html#specialnames

**Comment by rhettinger** [comment]
I would rather not clutter the glossary with this sort of entry.  Already, it has clutter that should probably be removed so that once again it becomes a worthwhile read rather than turning into a dictionary of random terms (such as meta-path-finder, module spec, and regular-package).

Instead, there should probably be a FAQ entry or wiki entry on the ever evolving spoken cultural terminology:

   dunder --\> double underscore
   stir   --\> \_\_str__
   repper --\> \_\_repr__
   rest --\> .rst files or representational-state-transfer
   sequel -\> sql
   gwid -\> globally unique indentifier
   inker and decker -\> incref and decef    (larry hastings pronunciation)

**Comment by Mariatta** [comment]
Thanks Raymond. +1 for adding the above list. 

I don't think FAQ is the right place either, I prefer we don't have to add the entries in the form of questions & answers.

**Comment by pitrou** [comment]
Agreed with Raymond that Python folk terminology should not go into the glossary.  I don't think I ever say "dunder" myself.

**Comment by serhiy-storchaka** [comment]
I never seen terms like "stir" or "inker", but the term "dunder" is used pretty widely. The glossary already contains abbreviations and Python folk terminology like EAFP and BDFL.

**Comment by rhettinger** [comment]
Recommend closing this and leaving it for StackOverflow.  I really don't want to further garbage-up the glossary.

**Comment by serhiy-storchaka** [comment]
The term "dunder" is used in PEPs: PEP-8, PEP-408, PEP-435, PEP-505, PEP-520, PEP-526, and in the enum module documentation.
