### ISSUE TITLE
Failure to build out of source from a not clean source

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76115]
BPO | [31934](https://bugs.python.org/issue31934)
--- | :---
Nosy | @brettcannon, @vstinner, @xdegaye
PRs | <li>python/cpython#4255</li><li>python/cpython#4340</li><li>python/cpython#4342</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.16:25:49.006>
created_at = <Date 2017-11-03.14:10:57.948>
labels = ['type-bug', '3.7', 'build']
title = 'Failure to build out of source from a not clean source'
updated_at = <Date 2017-11-08.16:25:49.005>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.16:25:49.005>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.16:25:49.006>
closer = 'vstinner'
components = ['Build']
creation = <Date 2017-11-03.14:10:57.948>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 31934
keywords = ['patch']
message_count = 12.0
messages = ['305486', '305492', '305521', '305524', '305655', '305853', '305862', '305864', '305870', '305871', '305874', '305875']
nosy_count = 3.0
nosy_names = ['brett.cannon', 'vstinner', 'xdegaye']
pr_nums = ['4255', '4340', '4342']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31934'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
The error message when building out of a not clean source tree:

renaming build/scripts-3.7/2to3 to build/scripts-3.7/2to3-3.7
renaming build/scripts-3.7/pyvenv to build/scripts-3.7/pyvenv-3.7
gcc -pthread   -Xlinker -export-dynamic -o [Programs/_testembed](https://github.com/python/cpython/blob/main/Programs/_testembed) [Programs/_testembed.o](https://github.com/python/cpython/blob/main/Programs/_testembed.o) libpython3.7m.a -lpthread -ldl  -lutil   -lm
gcc: error: [Programs/_testembed.o](https://github.com/python/cpython/blob/main/Programs/_testembed.o): No such file or directory
make[1]: *** [Makefile:707: [Programs/_testembed](https://github.com/python/cpython/blob/main/Programs/_testembed)] Error 1

**Comment by brettcannon** [comment]
What's "unclean" in this case? I mean you can always re-run Make after making changes and the build succeeds, so I'm not quite sure what leads to this state.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
When you build out of the source tree and this source tree has been built previously (by running 'make' in the source tree), then you get the error msg printed in [msg305486](https://bugs.python.org/msg305486) when you try to build \*out* of this not clean source tree. The solution is to run 'make clean' in the source tree first.

The reason that one must use a clean source tree is that otherwise 'make' finds an existing [Programs/_testembed.o](https://github.com/python/cpython/blob/main/Programs/_testembed.o) file in the source tree as the prerequisite to the [Programs/_testembed](https://github.com/python/cpython/blob/main/Programs/_testembed) target, but cannot build this target since [Programs/_testembed.o](https://github.com/python/cpython/blob/main/Programs/_testembed.o) does not exist locally.

It is not obvious from the error message to understand the reason for the build failure and one can waste quite some time finding the solution.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
To build out of the 'src' source tree (a subdirectory of the current directory) in a 'build' subdirectory:

```sh
$ ls -ld src
drwxr-xr-x 21 xavier xavier 4.0K Nov  3 23:50 src/
$ mkdir build
$ cd build
$ $(cd ../src && pwd)/configure && make
```


This is useful when you build for multiple platform configurations. For example on Android one can build for multiple API versions and multiple architectures (x86_64, armv7, aarch64, ...).

**Comment by vstinner** [comment]
Note for myself: Xavier proposed [PR 4255](https://github.com/python/cpython/pull/4255) fix :-)

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset 0de92859caf25e65fc968d4bb68626e9ba21b851 by xdegaye in branch 'master':
bpo-31934: Abort when building out of a not clean source tree (GH-4255)
https://github.com/python/cpython/commit/0de92859caf25e65fc968d4bb68626e9ba21b851

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset 0c4785bf39b4e86dea3a70b651e5d5db2f2cf017 by xdegaye in branch '3.6':
[3.6] bpo-31934: Abort when building out of a not clean source tree (GH-4255). (bpo-4340)
https://github.com/python/cpython/commit/0c4785bf39b4e86dea3a70b651e5d5db2f2cf017

**Comment by vstinner** [comment]
I tested manually the commit 0c4785bf39b4e86dea3a70b651e5d5db2f2cf017 merged into Python 3.6: it works as expected ;-)

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
I also tested the 2.7 and 3.6 PRs before submitting them.
Thanks for testing and for your reviews Victor :-)

**Comment by vstinner** [comment]
> I also tested the 2.7 and 3.6 PRs before submitting them.

Oh, I don't trust anyone, including myself :-) Since there is no automated, I chose to ("double") test manually your PRs.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Oh I understand, there is no practical way to test that feature except manually.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset fbdd3eeba3e526e162f2eb54d224cf36ed8cfea1 by xdegaye in branch '2.7':
[2.7] bpo-31934: Abort when building out of a not clean source tree (GH-4255). (bpo-4342)
https://github.com/python/cpython/commit/fbdd3eeba3e526e162f2eb54d224cf36ed8cfea1
