### ISSUE TITLE
subprocess.run() timeout not working with grandchildren and stdout=PIPE

### ISSUE THREAD

**Issue by 8088a9e8-db23-4ab6-b27e-dda4990049f6** [python/cpython#76116]
BPO | [31935](https://bugs.python.org/issue31935)
--- | :---
Nosy | @vstinner, @vadmium
Superseder | <li>bpo-30154: subprocess.run with stderr connected to a pipe won&#x27;t timeout when killing a never-ending shell commanad</li>
Files | <li>[test_killsub.py](https://bugs.python.org/file47251/test_killsub.py "Uploaded as text/plain at 2017-11-03.15:01:31 by Martin Ritter"): Minimal example to reproduce timeout problem</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-22.08:38:36.212>
created_at = <Date 2017-11-03.15:01:31.986>
labels = ['type-bug', 'library']
title = 'subprocess.run() timeout not working with grandchildren and stdout=PIPE'
updated_at = <Date 2018-07-22.08:38:36.210>
user = 'https://bugs.python.org/MartinRitter'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-22.08:38:36.210>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-22.08:38:36.212>
closer = 'martin.panter'
components = ['Library (Lib)']
creation = <Date 2017-11-03.15:01:31.986>
creator = 'Martin Ritter'
dependencies = []
files = ['47251']
hgrepos = []
issue_num = 31935
keywords = []
message_count = 3.0
messages = ['305487', '305529', '322137']
nosy_count = 3.0
nosy_names = ['vstinner', 'martin.panter', 'Martin Ritter']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '30154'
type = 'behavior'
url = 'https://bugs.python.org/issue31935'
versions = ['Python 3.6']
```

</p></details>

**Comment by 8088a9e8-db23-4ab6-b27e-dda4990049f6** [comment]
Hi,

I tried to use 

```py
    subprocess.run(..., stdout=subprocess.PIPE, timeout=N)
```


to run some test scripts with a given timeout. 

This works as expected with simple scripts. However if the script itself creates other children which write to stdout then `subprocess.run()` seems to wait for all of the children to finish. I've attached a minimal example.

I looked into subprocess.py and `subprocess.run()` calls `process.communicate()` again without timeout when handling the TimeoutExpired exception which then in turn waits for the pipes to be closed by all children.

If communicate() would check if the process is still alive while waiting for output and close the pipes once the process has finished the timeout feature should work as expected and descendants would get a SIGPIPE when writing to stdout/stderr.

**Comment by vadmium** [comment]
This proposal sounds like a race condition. Closing the output pipe as a child exits means you risk missing recent output. On the other hand, if you don’t care about the output any more, close the pipe first and then wait for the child.

Related discussions:

bpo-30154: Similar problem, but the grandchild does not write any output
bpo-26534: kill_group=True option for timeout
bpo-31447: Windows-specific (?)
