### ISSUE TITLE
some Blake2 parameters are encoded backwards on big-endian platforms

### ISSUE THREAD

**Issue by d63305f4-da1a-452d-91fe-9f0ae860d820** [python/cpython#76114]
BPO | [31933](https://bugs.python.org/issue31933)
--- | :---
Nosy | @tiran, @oconnor663
PRs | <li>python/cpython#4250</li><li>python/cpython#4262</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2017-11-03.20:34:17.256>
created_at = <Date 2017-11-03.12:27:26.224>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'some Blake2 parameters are encoded backwards on big-endian platforms'
updated_at = <Date 2017-11-03.20:34:17.255>
user = 'https://github.com/oconnor663'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-03.20:34:17.255>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2017-11-03.20:34:17.256>
closer = 'christian.heimes'
components = ['Extension Modules']
creation = <Date 2017-11-03.12:27:26.224>
creator = 'oconnor663'
dependencies = []
files = []
hgrepos = []
issue_num = 31933
keywords = ['patch']
message_count = 4.0
messages = ['305473', '305476', '305498', '305502']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'oconnor663']
pr_nums = ['4250', '4262']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31933'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by d63305f4-da1a-452d-91fe-9f0ae860d820** [comment]
See https://github.com/BLAKE2/libb2/issues/12.

All Blake2 params have to be encoded in little-endian byte order. For the two multi-byte integer params, leaf_length and node_offset, that means that assigning a native-endian integer to them appears to work on little-endian platforms, but gives the wrong result on big-endian. The current libb2 API doesn't make that very clear, and @sneves is working on new API functions in the GH issue above. In the meantime, we can work around the problem by explicitly assigning little-endian values to the parameter block.

**Comment by tiran** [comment]
Good work, thanks for your PR!

**Comment by tiran** [comment]
New changeset dcfb0e3c04f1b29a0d09bb0a81dcd5ee5a5fef1a by Christian Heimes (Jack O'Connor) in branch 'master':
bpo-31933: fix blake2 multi-byte params on big endian platforms (bpo-4250)
https://github.com/python/cpython/commit/dcfb0e3c04f1b29a0d09bb0a81dcd5ee5a5fef1a

**Comment by tiran** [comment]
New changeset a512493371a073e252a2e52b445aa2d66ddca7cb by Christian Heimes (Miss Islington (bot)) in branch '3.6':
bpo-31933: fix blake2 multi-byte params on big endian platforms (GH-4250) (bpo-4262)
https://github.com/python/cpython/commit/a512493371a073e252a2e52b445aa2d66ddca7cb
