### ISSUE TITLE
IDLE: Pressing "Home" on Windows places cursor before ">>>"

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#76111]
BPO | [31930](https://bugs.python.org/issue31930)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka, @mlouielu, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2021-06-11.04:10:05.568>
created_at = <Date 2017-11-02.22:09:41.313>
labels = ['expert-IDLE', 'type-bug', 'invalid', '3.9']
title = 'IDLE: Pressing "Home" on Windows places cursor before ">>>"'
updated_at = <Date 2021-06-11.04:10:05.567>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-11.04:10:05.567>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2021-06-11.04:10:05.568>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-11-02.22:09:41.313>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 31930
keywords = []
message_count = 5.0
messages = ['305452', '305465', '310506', '311647', '395602']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'serhiy.storchaka', 'louielu', 'cheryl.sabella']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31930'
versions = ['Python 3.9']
```

</p></details>

**Comment by terryjreedy** [comment]
```pycon
If one enters text in Shell after a '>>> ' prompt, Home should initially send the cursor between the prompt and entered text and then to the beginning of the line, and so on as a toggle.  On all current releases (and the final 3.5.4), on my Win10 machine, the cursor goes to the beginning of the line and stays there.
```


This is nearly the same as bpo-3851, which patched EditorWindow.home_callback on 2011-3-21 and -25.  The problem then only affected Windows, because it involved event.state for keypresses, which is set differently on Windows and \*nix.

This issue is slightly different in that the Numlock key no longer matters. (See KBK's  2009-04-04 02:51 message.)  Cherl or Louie, is this one also Windows-only or does it occur on Linux?
  
According to hg annotate, the only subsequent patch to .home_callback before the git switch was 2012-12-24 for bpo-16511.  It changed the part of the function that adjusted selection, after moving the cursor, if Shift-Home was pressed.  When the cursor moves to the beginning of the line, the selection includes the prompt.  3.5 has not been patched since the switch to git, so the problem must predate the switch.

2.7 on Windows runs with tk 8.5.15, so a later tk change cannot be the problem.  So I suspect that the 'culprit' is either an earlier 'fix' to tk or a patch to tkinter since 2011, combined with the absence of a test in IDLE for correct behavior.  Serhiy, do you have any ideas?

**Comment by csabella** [comment]
```pycon
On Ubuntu, HOME initially goes to between the text and >>>.  Pressing it again moves it before the >>> and then it toggles between the two.  So, it appears to be working as expected.
```
