### ISSUE TITLE
Document that support of start and stop parameters in the Sequence's index() is optional

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76123]
BPO | [31942](https://bugs.python.org/issue31942)
--- | :---
Nosy | @rhettinger, @vstinner, @ssbr, @serhiy-storchaka, @nitishch
PRs | <li>python/cpython#4277</li><li>python/cpython#4811</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-12.10:58:55.565>
created_at = <Date 2017-11-04.09:10:01.484>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = "Document that support of start and stop parameters in the Sequence's index() is optional"
updated_at = <Date 2017-12-12.10:58:55.564>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-12.10:58:55.564>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-12-12.10:58:55.565>
closer = 'vstinner'
components = ['Documentation']
creation = <Date 2017-11-04.09:10:01.484>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31942
keywords = ['patch', 'easy']
message_count = 6.0
messages = ['305547', '305651', '307834', '308105', '308110', '308111']
nosy_count = 6.0
nosy_names = ['rhettinger', 'vstinner', 'Devin Jeanpierre', 'docs@python', 'serhiy.storchaka', 'nitishch']
pr_nums = ['4277', '4811']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31942'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Parameters start and stop were added to the Sequence.index() mixin method in 3.5 (see bpo-23086). But not all concrete implementations of the Sequence ABC support them (for example range.index() doesn't, see bpo-28197). This should be explicitly documented (including the docstring of Sequence.index).

**Comment by vstinner** [comment]
See also bpo-31956: "Add start and stop parameters to the array.index()".
