### ISSUE TITLE
[EASY] Broken MSDN links in msilib docs

### ISSUE THREAD

**Issue by berkerpeksag** [python/cpython#76129]
BPO | [31948](https://bugs.python.org/issue31948)
--- | :---
Nosy | @berkerpeksag, @Mariatta, @akashbw
PRs | <li>python/cpython#4397</li><li>python/cpython#4398</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.00:27:17.643>
created_at = <Date 2017-11-05.11:49:27.525>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = '[EASY] Broken MSDN links in msilib docs'
updated_at = <Date 2017-11-15.00:27:17.642>
user = 'https://github.com/berkerpeksag'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.00:27:17.642>
actor = 'Mariatta'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-15.00:27:17.643>
closer = 'Mariatta'
components = ['Documentation']
creation = <Date 2017-11-05.11:49:27.525>
creator = 'berker.peksag'
dependencies = []
files = []
hgrepos = []
issue_num = 31948
keywords = ['patch', 'easy']
message_count = 5.0
messages = ['305593', '306144', '306241', '306242', '306243']
nosy_count = 4.0
nosy_names = ['docs@python', 'berker.peksag', 'Mariatta', 'Akash Jain']
pr_nums = ['4397', '4398']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31948'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by berkerpeksag** [comment]
Most of the MSDN links in [Doc/library/msilib.rst](https://github.com/python/cpython/blob/main/Doc/library/msilib.rst) are broken:

   https://docs.python.org/3/library/msilib.html

For example, the UuidToString link goes to

   https://msdn.microsoft.com/library?url=/library/en-us/rpc/rpc/uuidtostring.asp

But I believe the correct link should be

    https://msdn.microsoft.com/en-us/library/windows/desktop/aa379352(v=vs.85).aspx

**Comment by ea9e18a8-a0c7-45b4-8eae-2d285fcf9fb5** [comment]
Hi,

I am new to contributing in Python, Can I work on this issue?

**Comment by Mariatta** [comment]
New changeset 3bda02222aa3783bf85fc3ff8bc042aefd9c4fd3 by Mariatta (Jesse-Bakker) in branch 'master':
bpo-31948: Fix broken links in msilib docs (GH-4397)
https://github.com/python/cpython/commit/3bda02222aa3783bf85fc3ff8bc042aefd9c4fd3

**Comment by Mariatta** [comment]
This couldn't be backported by miss-islington, so someone needs to do it manually.

**Comment by Mariatta** [comment]
New changeset 42336def77f53861284336b3335098a1b9b8cab2 by Mariatta (Jesse-Bakker) in branch '3.6':
bpo-31948: Fix broken links in msilib docs (GH-4397). (GH-4398)
https://github.com/python/cpython/commit/42336def77f53861284336b3335098a1b9b8cab2
