### ISSUE TITLE
ImportError: DLL Load Failure: The specified module cannot be found

### ISSUE THREAD

**Issue by 699aa770-10df-492d-aaa0-dc43011258cc** [python/cpython#76122]
BPO | [31941](https://bugs.python.org/issue31941)
--- | :---
Nosy | @bitdancer, @xoviat
Superseder | <li>bpo-25655: Python errors related to failures loading DLL&#x27;s lack information</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-04.02:32:58.947>
created_at = <Date 2017-11-04.02:26:04.846>
labels = ['type-feature']
title = 'ImportError: DLL Load Failure: The specified module cannot be found'
updated_at = <Date 2017-11-04.02:32:58.889>
user = 'https://github.com/xoviat'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-04.02:32:58.889>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-04.02:32:58.947>
closer = 'r.david.murray'
components = []
creation = <Date 2017-11-04.02:26:04.846>
creator = 'xoviat'
dependencies = []
files = []
hgrepos = []
issue_num = 31941
keywords = []
message_count = 2.0
messages = ['305531', '305532']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'xoviat']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '25655'
type = 'enhancement'
url = 'https://bugs.python.org/issue31941'
versions = []
```

</p></details>

**Comment by 699aa770-10df-492d-aaa0-dc43011258cc** [comment]
Yes, I know that this isn't Python's fault. I know how to resolve the problem. But what's frustrating is that this error message is totally unhelpful, because it doesn't contain the DLL that Python is looking for.

Yes, I know that the error message is just directly from windows. But there has to be some way to make this error message more helpful. There has to be some way to tell the user what the name of the DLL is. Because the current state of this error message is sad.

**Comment by bitdancer** [comment]
Duplicate of bpo-25655.  Any concrete proposals for how to make this better are welcome.
