### ISSUE TITLE
UUID versions are not validated to lie in the documented range

### ISSUE THREAD

**Issue by ee75c303-5726-438c-b743-dcc156ee5aa5** [python/cpython#76139]
BPO | [31958](https://bugs.python.org/issue31958)
--- | :---
Nosy | @berkerpeksag, @coNQP, @tirkarthi
Superseder | <li>bpo-34732: uuid returns version more than 5</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.22:33:43.448>
created_at = <Date 2017-11-06.11:31:27.764>
labels = ['type-bug', 'library']
title = 'UUID versions are not validated to lie in the documented range'
updated_at = <Date 2018-09-19.22:33:43.446>
user = 'https://bugs.python.org/DavidMacIver'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.22:33:43.446>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.22:33:43.448>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-11-06.11:31:27.764>
creator = 'David MacIver'
dependencies = []
files = []
hgrepos = []
issue_num = 31958
keywords = []
message_count = 5.0
messages = ['305636', '305646', '325753', '325758', '325809']
nosy_count = 4.0
nosy_names = ['berker.peksag', 'David MacIver', 'conqp', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '34732'
type = 'behavior'
url = 'https://bugs.python.org/issue31958'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by ee75c303-5726-438c-b743-dcc156ee5aa5** [comment]
The documentation for the UUID module says the UUID.version field is "The UUID version number (1 through 5, meaningful only when the variant is RFC_4122)".

However, the UUID constructor doesn't actually validate that the version lies in that range if you don't pass a version to the constructor and, as a result, this isn't actually true - the version number can be anything between 0 and 15.

For an example consider the following:

```pycon
>>> from uuid import UUID
>>> u = UUID(int=1133377179260751706062848)
>>> u.variant
'specified in RFC 4122'
>>> u.version
15
```


I have only actually run this example on Python 3.6, but inspection of the code suggests that it's been like this since its introduction.

**Comment by vstinner** [comment]
What do you propose? Raise an exception in the constructor if the version is not in the range 1..5? Or just modify the variant value?
