### ISSUE TITLE
[Windows] PCbuild error: A numeric comparison was attempted

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76138]
BPO | [31957](https://bugs.python.org/issue31957)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba
PRs | <li>python/cpython#4298</li><li>python/cpython#4300</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2017-11-07.22:55:44.561>
created_at = <Date 2017-11-06.11:17:26.009>
labels = ['build', '3.7', 'OS-windows']
title = '[Windows] PCbuild error: A numeric comparison was attempted'
updated_at = <Date 2017-11-07.22:55:44.560>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-07.22:55:44.560>
actor = 'vstinner'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2017-11-07.22:55:44.561>
closer = 'vstinner'
components = ['Build', 'Windows']
creation = <Date 2017-11-06.11:17:26.009>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 31957
keywords = ['patch']
message_count = 6.0
messages = ['305631', '305632', '305633', '305675', '305685', '305797']
nosy_count = 5.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = ['4298', '4300']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue31957'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
http://buildbot.python.org/all/#/builders/58/builds/110

Build started 11/4/2017 7:30:21 PM.
Project "D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\pythoncore.vcxproj" on node 1 (KillPython target(s)).
D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\python.props(77,31): error MSB4086: A numeric comparison was attempted on "$(Registry:HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v10.0@ProductVersion)" that evaluates to "" instead of a number, in condition "$(Registry:HKEY_LOCAL_MACHINE\\SOFTWARE\\WOW6432Node\\Microsoft\\Microsoft SDKs\\Windows\\v10.0@ProductVersion) \>= '10.0.15063'". [D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\pythoncore.vcxproj]
Done Building Project "D:\\cygwin\\home\\db3l\\buildarea\\3.x.bolen-windows7\\build\\PCbuild\\pythoncore.vcxproj" (KillPython target(s)) -- FAILED.
Build FAILED.

It's likely a regression caused by one of these commits:

* 0d2a9088d16826343344b04461c8be44b4008710
* aed08562220974b5c67371b908f23caa1be07e38

**Comment by vstinner** [comment]
Compilation also failed on AMD64 Windows8 3.x:

http://buildbot.python.org/all/#/builders/32/builds/118

**Comment by vstinner** [comment]
Windows8 error:

D:\\buildarea\\3.x.bolen-windows8\\build\\PCbuild\\python.props(76,31): error MSB4086: A numeric comparison was attempted on "$(Registry:HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows\\v10.0@ProductVersion)" that evaluates to "" instead of a number, in condition "$(Registry:HKEY_LOCAL_MACHINE\\SOFTWARE\\Microsoft\\Microsoft SDKs\\Windows\\v10.0@ProductVersion) \>= '10.0.15063'". [D:\\buildarea\\3.x.bolen-windows8\\build\\PCbuild\\pythoncore.vcxproj]

**Comment by zooba** [comment]
New changeset 30f4fa456ef626ad7a92759f492ec7a268f7af4e by Steve Dower in branch 'master':
bpo-31957: Fixes version detection. (bpo-4298)
https://github.com/python/cpython/commit/30f4fa456ef626ad7a92759f492ec7a268f7af4e

**Comment by zooba** [comment]
New changeset a6ffec2e88437ed4fecb10cb359cf2fb64781e9a by Steve Dower (Miss Islington (bot)) in branch '3.6':
[3.6] bpo-31957: Fixes version detection. (GH-4298) (bpo-4300)
https://github.com/python/cpython/commit/a6ffec2e88437ed4fecb10cb359cf2fb64781e9a

**Comment by vstinner** [comment]
Thank you Steve for the quick fix!
