### ISSUE TITLE
Bugs in PyTraceBack_Print()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76130]
BPO | [31949](https://bugs.python.org/issue31949)
--- | :---
Nosy | @tiran, @berkerpeksag, @serhiy-storchaka
PRs | <li>python/cpython#4289</li><li>python/cpython#4406</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2017-11-15.16:05:18.089>
created_at = <Date 2017-11-05.14:06:35.003>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Bugs in PyTraceBack_Print()'
updated_at = <Date 2018-09-22.19:12:11.434>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-22.19:12:11.434>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2017-11-15.16:05:18.089>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-11-05.14:06:35.003>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31949
keywords = ['patch']
message_count = 4.0
messages = ['305595', '305596', '306274', '306280']
nosy_count = 3.0
nosy_names = ['christian.heimes', 'berker.peksag', 'serhiy.storchaka']
pr_nums = ['4289', '4406']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31949'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
0fbab7ff8d2efd92e222fcc13c0aff0998c3c158 changed the semantic of PyTraceBack_Print and sys.tracebacklimit. It no longer match the documentation and the behavior of the traceback module. Setting sys.tracebacklimit to 0 or less no longer suppress printing tracebacks in PyTraceBack_Print(). Setting sys.tracebacklimit to None (as at shutdown stage) no longer makes PyTraceBack_Print() using default limit, but suppress printing tracebacks and sets a TypeError without returning failure from PyTraceBack_Print().

The proposed PR restores the initial purposed semantic and fixes several other bugs in PyTraceBack_Print().

* Setting sys.tracebacklimit to 0 or less now suppress printing tracebacks.
* Setting sys.tracebacklimit to None now causes using the default limit.
* Setting sys.tracebacklimit to an integer larger than LONG_MAX now means using the limit LONG_MAX rather than the default limit.
* Fixed integer overflows in the case of more than 2\*\*31 items on Windows.
* Fixed output errors handling.

**Comment by berkerpeksag** [comment]
> Setting sys.tracebacklimit to 0 or less no longer suppress printing
> tracebacks in PyTraceBack_Print().

This was also reported in bpo-12276.

**Comment by serhiy-storchaka** [comment]
New changeset edad8eebeee3c99e324a7f1ac5073167c2b0b54d by Serhiy Storchaka in branch 'master':
bpo-31949: Fixed several issues in printing tracebacks (PyTraceBack_Print()). (bpo-4289)
https://github.com/python/cpython/commit/edad8eebeee3c99e324a7f1ac5073167c2b0b54d

**Comment by serhiy-storchaka** [comment]
New changeset 3864248866d6224336c7be49670447cb4d125cd6 by Serhiy Storchaka in branch '3.6':
[3.6] bpo-31949: Fixed several issues in printing tracebacks (PyTraceBack_Print()). (GH-4289) (bpo-4406)
https://github.com/python/cpython/commit/3864248866d6224336c7be49670447cb4d125cd6
