### ISSUE TITLE
import curses is broken on windows

### ISSUE THREAD

**Issue by f14b9dff-af28-4539-a849-308c02a30016** [python/cpython#76132]
BPO | [31951](https://bugs.python.org/issue31951)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba
Superseder | <li>bpo-1005895: curses for win32</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-01-06.09:45:38.857>
created_at = <Date 2017-11-05.22:55:53.630>
labels = ['OS-windows']
title = 'import curses is broken on windows'
updated_at = <Date 2021-01-06.09:45:38.856>
user = 'https://bugs.python.org/joem2'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-06.09:45:38.856>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2021-01-06.09:45:38.857>
closer = 'serhiy.storchaka'
components = ['Windows']
creation = <Date 2017-11-05.22:55:53.630>
creator = 'joe m2'
dependencies = []
files = []
hgrepos = []
issue_num = 31951
keywords = []
message_count = 6.0
messages = ['305610', '305647', '305648', '305654', '305656', '305790']
nosy_count = 7.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'joe m2']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1005895'
type = None
url = 'https://bugs.python.org/issue31951'
versions = ['Python 3.6']
```

</p></details>

**Comment by f14b9dff-af28-4539-a849-308c02a30016** [comment]
Importing curses on Windows install calls the following:

```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user name\AppData\Local\Programs\Python\Python36-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ModuleNotFoundError: No module named '_curses'
```


Importing curses as "\_curses" does the same thing. I have tried the "repair" function and it has not worked.

**Comment by vstinner** [comment]
The curses module is not supported on Windows.

**Comment by pfmoore** [comment]
The docs for the curses module say "While curses is most widely used in the Unix environment, versions are available for Windows, DOS, and possibly other systems as well." This is the only mention of platform support I can see.

It might be worth making the platform support explicit in the docs.

**Comment by zware** [comment]
Curses is available for Windows from Christopher Gohlke's site: https://www.lfd.uci.edu/~gohlke/pythonlibs/#curses

We should clean up this situation, though, either by making the state of Windows curses support explicit in the docs or by actually adding support for it in the default distribution.

**Comment by serhiy-storchaka** [comment]
There are two open issues for adding support of the curses module on Windows: bpo-1005895 and bpo-2889.

**Comment by f14b9dff-af28-4539-a849-308c02a30016** [comment]
I would much prefer the curses module to be supported in newer versions  since I believe that curses is installed as a built in module (not sure about that).

Anyhow, thank you for your help but I have found a replacement module called "asciimatics" which for fills all the functions that I really need.
