### ISSUE TITLE
distutils C compiler: set_executables() incorrectly parse values with spaces

### ISSUE THREAD

**Issue by b0230a51-17d2-4ab8-94be-25f4a5dcadcb** [python/cpython#76136]
BPO | [31955](https://bugs.python.org/issue31955)
--- | :---
Nosy | @vstinner, @merwok, @dstufft, @Mazay0
PRs | <li>python/cpython#4296</li><li>python/cpython#4316</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.15:50:23.119>
created_at = <Date 2017-11-06.10:34:35.676>
labels = ['type-bug', 'library']
title = 'distutils C compiler: set_executables() incorrectly parse values with spaces'
updated_at = <Date 2017-11-08.15:50:23.117>
user = 'https://github.com/Mazay0'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.15:50:23.117>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.15:50:23.119>
closer = 'vstinner'
components = ['Distutils']
creation = <Date 2017-11-06.10:34:35.676>
creator = 'Dee Mee'
dependencies = []
files = []
hgrepos = []
issue_num = 31955
keywords = ['patch']
message_count = 5.0
messages = ['305627', '305645', '305760', '305858', '305860']
nosy_count = 4.0
nosy_names = ['vstinner', 'eric.araujo', 'dstufft', 'Dee Mee']
pr_nums = ['4296', '4316']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31955'
versions = ['Python 2.7']
```

</p></details>

**Comment by b0230a51-17d2-4ab8-94be-25f4a5dcadcb** [comment]
Function set_executable() in ccompiler.py does the following check:

```py
    def set_executable(self, key, value):
        if isinstance(value, str):
            setattr(self, key, split_quoted(value))
        else:
            setattr(self, key, value)
```



The check "if isinstance(value, str)" is incorrect, because type of value can be unicode, while it should be splitted as well.

**Comment by vstinner** [comment]
> The check "if isinstance(value, str)" is incorrect, because type of value can be unicode, while it should be splitted as well.

Your pull request is for Python 3, but the type of paths is expected to be str on Python 3, no?

For Python 2, you can use isinstance(value, basestring).

**Comment by b0230a51-17d2-4ab8-94be-25f4a5dcadcb** [comment]
I agree, that this fix is necessary only for Python 2. Submitted new [PR 4316](https://github.com/python/cpython/pull/4316)

**Comment by vstinner** [comment]
New changeset 849482955f70eb1adc47a20dcbce3b4add47d864 by Victor Stinner (Mazay0) in branch '2.7':
bpo-31955: Fix distutils CCompiler.set_executable() for Unicode (GH-4316)
https://github.com/python/cpython/commit/849482955f70eb1adc47a20dcbce3b4add47d864

**Comment by vstinner** [comment]
Thank you Dee Mee for your bug report and your bug fix!
