### ISSUE TITLE
Add start and stop parameters to the array.index()

### ISSUE THREAD

**Issue by 0c3d0f49-c5d6-46dd-ba32-be6f722e146e** [python/cpython#76137]
BPO | [31956](https://bugs.python.org/issue31956)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @phaqui, @csabella, @corona10, @ZackerySpytz, @nanjekyejoannah, @kamilturek
PRs | <li>python/cpython#4435</li><li>python/cpython#25059</li>
Files | <li>[WIP-issue-31956](https://bugs.python.org/file47261/WIP-issue-31956 "Uploaded as text/plain at 2017-11-12.23:05:19 by @phaqui")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-09.01:26:32.579>
created_at = <Date 2017-11-06.11:13:47.630>
labels = ['extension-modules', 'type-feature', '3.10']
title = 'Add start and stop parameters to the array.index()'
updated_at = <Date 2021-04-09.01:26:32.577>
user = 'https://bugs.python.org/nikispahiev'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-09.01:26:32.577>
actor = 'corona10'
assignee = 'none'
closed = True
closed_date = <Date 2021-04-09.01:26:32.579>
closer = 'corona10'
components = ['Extension Modules']
creation = <Date 2017-11-06.11:13:47.630>
creator = 'niki.spahiev'
dependencies = []
files = ['47261']
hgrepos = []
issue_num = 31956
keywords = ['patch']
message_count = 14.0
messages = ['305629', '305643', '305650', '305758', '306133', '306143', '306150', '306178', '330746', '350405', '350619', '352499', '369732', '390070']
nosy_count = 10.0
nosy_names = ['rhettinger', 'serhiy.storchaka', 'Phaqui', 'cheryl.sabella', 'corona10', 'ZackerySpytz', 'niki.spahiev', 'nanjekyejoannah', 'Ryan G.', 'kamilturek']
pr_nums = ['4435', '25059']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31956'
versions = ['Python 3.10']
```

</p></details>

**Comment by 0c3d0f49-c5d6-46dd-ba32-be6f722e146e** [comment]
Sequence protocol specifies 2 optional argument for index method:
seq.index(value, [start, [stop]])

array.index(value) needs start and stop arguments too.

**Comment by rhettinger** [comment]
+1

**Comment by vstinner** [comment]
Николай Спахиев: Are you only asking for the feature, or are you interested to work on a concrete patch?

**Comment by 0c3d0f49-c5d6-46dd-ba32-be6f722e146e** [comment]
I plan to work on a patch.

**Comment by 7d6f023c-9371-47e5-8ab4-997e01d0cab0** [comment]
I decided to work on this, and I would like some review, as this would be my second contribution to cpython. Also, a general question:

As I defined the start and end arguments Py_ssize_t, bigger indexes (more negative or more positive) than what can fit in Py_ssize_t will trigger an overflow error. This should be OK, though, as other functions with index arguments has them as Py_ssize_t - and getarrayitem() itself accepts a Py_ssize_t. Or?

**Comment by serhiy-storchaka** [comment]
Just take list.index as an example.

**Comment by vstinner** [comment]
Anders Lorentsen: Py_ssize_t is the correct type for an index in the C language. It's not technically possible to create an array object larger than PY_SSIZE_T_MAX items :-)

Serhiy\> Just take list.index as an example.

I concur with Serhiy :-)

**Comment by 7d6f023c-9371-47e5-8ab4-997e01d0cab0** [comment]
Writing my tests, I originally looked at [Lib/test/seq_tests.py](https://github.com/python/cpython/blob/main/Lib/test/seq_tests.py). One test case uses indexes that are (+-)4\*sys.maxsize. This does not fit in Py_ssize_t, and so these tests cause my array implementation to raise an overflow exception.

A solution is of course to have the function take general objects instead, and then truncate them down to a number that can fit in Py_ssize_t if it's too negative or positive).

But I concur. It seems more reasonable to stay consistent with the rest of the module, too.

I'll look over the test code to make sure I test for every given scenario (or as many as I can think of), and prepare a PR for this, then :)
