### ISSUE TITLE
Default event loop policy doc lacks precision

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76131]
BPO | [31950](https://bugs.python.org/issue31950)
--- | :---
Nosy | @gvanrossum, @pitrou, @vstinner, @giampaolo, @1st1
PRs | <li>python/cpython#4306</li><li>python/cpython#4307</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-07.09:35:23.197>
created_at = <Date 2017-11-05.18:16:09.678>
labels = ['type-bug', '3.7', 'docs', 'expert-asyncio']
title = 'Default event loop policy doc lacks precision'
updated_at = <Date 2017-11-07.09:35:23.195>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-07.09:35:23.195>
actor = 'pitrou'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-07.09:35:23.197>
closer = 'pitrou'
components = ['Documentation', 'asyncio']
creation = <Date 2017-11-05.18:16:09.678>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 31950
keywords = ['patch']
message_count = 5.0
messages = ['305607', '305711', '305723', '305724', '305725']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'pitrou', 'vstinner', 'giampaolo.rodola', 'docs@python', 'yselivanov']
pr_nums = ['4306', '4307']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31950'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
The doc for the default event loop policy states that """the default policy defines context as the current thread, and manages an event loop per thread that interacts with asyncio""".  What it doesn't mention, though, is that you get a RuntimeError if you call get_event_loop() in a non-main thread -- you first have to call set_event_loop(new_event_loop()) in that thread.  This wasn't expected by me.

As a side note, customizing the event loop policy isn't trivial either: it seems it's best to subclass DefaultEventLoopPolicy and make adjustments by overriding the API methods.  Writing your own wouldn't work, as e.g. the Unix default policy has custom initialization code for child watchers.

**Comment by gvanrossum** [comment]
Agreed that this needs more clarification. Is something stopping you from submitting a PR? Note that the thing about non-main-threads is mentioned in the docstring for BaseDefaultEventLoopPolicy. I agree that the best way to create a new policy is to study the existing code and subclass DefaultEventLoopPolicy.

**Comment by pitrou** [comment]
New changeset 4135c89395726024abddb7340a0c7a42c801f616 by Antoine Pitrou in branch 'master':
bpo-31950: Improve event loop policy doc (bpo-4306)
https://github.com/python/cpython/commit/4135c89395726024abddb7340a0c7a42c801f616

**Comment by pitrou** [comment]
New changeset e65617f65e203a2a6d3e3100d0d6fed0ffa0613d by Antoine Pitrou (Miss Islington (bot)) in branch '3.6':
bpo-31950: Improve event loop policy doc (GH-4306) (bpo-4307)
https://github.com/python/cpython/commit/e65617f65e203a2a6d3e3100d0d6fed0ffa0613d

**Comment by pitrou** [comment]
Thank you Guido.  This is fixed now.
