### ISSUE TITLE
Directory at `TemporaryDirectory().name` does not exist

### ISSUE THREAD

**Issue by d9c6ba30-8e1a-4da2-9966-2db00057ffd0** [python/cpython#76140]
BPO | [31959](https://bugs.python.org/issue31959)
--- | :---
Nosy | @vadmium, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-06.12:38:04.491>
created_at = <Date 2017-11-06.12:05:51.619>
labels = ['invalid', 'type-bug', 'library']
title = 'Directory at `TemporaryDirectory().name` does not exist'
updated_at = <Date 2017-11-06.15:36:01.786>
user = 'https://bugs.python.org/AdamDangoor'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-06.15:36:01.786>
actor = 'Adam Dangoor'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-06.12:38:04.491>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-11-06.12:05:51.619>
creator = 'Adam Dangoor'
dependencies = []
files = []
hgrepos = []
issue_num = 31959
keywords = []
message_count = 5.0
messages = ['305637', '305638', '305639', '305640', '305644']
nosy_count = 3.0
nosy_names = ['martin.panter', 'serhiy.storchaka', 'Adam Dangoor']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31959'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by d9c6ba30-8e1a-4da2-9966-2db00057ffd0** [comment]
Sample code:

```
import os
from tempfile import TemporaryDirectory

name = TemporaryDirectory().name
print(os.path.exists(name))  # prints False

td = TemporaryDirectory()
name_2 = td.name
print(os.path.exists(name_2))  # prints True
```

Expected behavior: `True` is printed for both print statements.

I have run this example on:

* CPython 3.6.3
* CPython 3.5.3
* pypy 3.5.3

The unexpected behavior occurs on CPython 3.5.3 and CPython 3.6.X but not on pypy.

(bug found with Tim Weidner https://github.com/timaa2k).

**Comment by d9c6ba30-8e1a-4da2-9966-2db00057ffd0** [comment]
> The unexpected behavior occurs on CPython 3.5.3 and CPython 3.6.X but not on pypy.

This suggests that it is something to do with garbage collection. Upon further thought, maybe this is by design, but I still was surprised.

**Comment by serhiy-storchaka** [comment]
This is by design. The first TemporaryDirectory object is destroyed before the first print statement. For not be surprised use TemporaryDirectory with the "with" statement.

```py
with TemporaryDirectory() as td:
    name = td.name
    print(os.path.exists(name))  # prints True

print(os.path.exists(name))  # prints False
```

**Comment by vadmium** [comment]
The documentation says “On . . . destruction of the temporary directory object the newly created temporary directory and all its contents are removed”. If you had enabled warnings, you may have seen a hint:

```sh
$ python -Wdefault -c 'import tempfile; print(tempfile.TemporaryDirectory().name)'
/usr/lib/python3.5/tempfile.py:788: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmpj6100h57'>
  _warnings.warn(warn_message, ResourceWarning)
/tmp/tmpj6100h57
```


This is similar in spirit to earlier bug reports where workarounds were added, but to avoid this instance of the problem the string object returned by the “name” attribute would have to hold a reference back to the directory object.

* bpo-23700: iter(NamedTemporaryFile())
* bpo-18879: NamedTemporaryFile().write(...)

**Comment by d9c6ba30-8e1a-4da2-9966-2db00057ffd0** [comment]
Thank you for clearing this up for me.
