### ISSUE TITLE
exec(): method's default arguments from dict-inherited globals

### ISSUE THREAD

**Issue by 2446c507-63e2-4513-8cf0-25aac773a477** [python/cpython#76149]
BPO | [31968](https://bugs.python.org/issue31968)
--- | :---
Nosy | @rhettinger, @bitdancer, @tonybaloney, @ipolyakovskiy
PRs | <li>python/cpython#4313</li><li>python/cpython#4315</li><li>python/cpython#13140</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-06-01.15:53:07.749>
created_at = <Date 2017-11-07.12:49:16.911>
labels = ['interpreter-core', 'type-bug', '3.7', 'docs']
title = "exec(): method's default arguments from dict-inherited globals"
updated_at = <Date 2019-06-01.15:53:07.748>
user = 'https://github.com/ipolyakovskiy'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-01.15:53:07.748>
actor = 'rhettinger'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-06-01.15:53:07.749>
closer = 'rhettinger'
components = ['Documentation', 'Interpreter Core']
creation = <Date 2017-11-07.12:49:16.911>
creator = 'Ilya Polyakovskiy'
dependencies = []
files = []
hgrepos = []
issue_num = 31968
keywords = ['patch']
message_count = 4.0
messages = ['305746', '305747', '341651', '344179']
nosy_count = 5.0
nosy_names = ['rhettinger', 'r.david.murray', 'docs@python', 'anthonypjshaw', 'Ilya Polyakovskiy']
pr_nums = ['4313', '4315', '13140']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31968'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 2446c507-63e2-4513-8cf0-25aac773a477** [comment]
I'm using exec() to run code with globals object inherited from dict. The problem is overloaded \_\_getitem__ doesn't called to load default argument for class methods.
Here the example. Let's assume we create some variable storage for code execution

```py
class Env(dict):
    def __init__(self, external_storage):
        super().__init__()
        self._external_storage = external_storage

    def __setitem__(self, key, value):
        print('__setitem__: {}'.format(key))
        self._external_storage[key] = value

    def __getitem__(self, key):
        print('__getitem__: {}'.format(key))
        return self._external_storage[key]


storage = {}
env = Env(storage)
env['var'] = 2
```


exec("""
class A:
    def foo(self, x=var):
        print('foo(): {}'.format(x))

```py
a = A()
a.foo()
""", env)
```


```pytb
This code will fail with output:
__setitem__: var
Traceback (most recent call last):
  File "inheri-test.py", line 29, in <module>
    """, env)
  File "<string>", line 2, in <module>
  File "<string>", line 3, in A
NameError: name 'var' is not defined
```



As far as I understand the problem is [Python/ceval.c:2120](https://github.com/python/cpython/blob/main/Python/ceval.c#L2120). There is only PyDict_GetItem used to load variable from f_globals, instead of PyObject_GetItem in case of f_globals is not exact dict.

**Comment by bitdancer** [comment]
Yes, that's the way it works (and is intended to work, for performance reasons).  The documentation on this could be improved...while it does say globals must be a dict and that locals can be any mapping object, it does it in a sentence that is a bit confusing in this context, and it doesn't make it clear that it has to be a "real" dict, not a subclass.  (I wouldn't be surprised if that sentence was written back when you couldn't subclass dict.)
