### ISSUE TITLE
Incorrect documentation for multiprocessing.connection.{Client,Listener}

### ISSUE THREAD

**Issue by JelleZijlstra** [python/cpython#76146]
BPO | [31965](https://bugs.python.org/issue31965)
--- | :---
Nosy | @pitrou, @applio, @JelleZijlstra
PRs | <li>python/cpython#4304</li><li>python/cpython#4321</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/JelleZijlstra'
closed_at = <Date 2017-11-07.16:20:44.814>
created_at = <Date 2017-11-07.07:00:44.069>
labels = ['3.7', 'docs']
title = 'Incorrect documentation for multiprocessing.connection.{Client,Listener}'
updated_at = <Date 2017-11-07.16:20:44.813>
user = 'https://github.com/JelleZijlstra'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-07.16:20:44.813>
actor = 'pitrou'
assignee = 'JelleZijlstra'
closed = True
closed_date = <Date 2017-11-07.16:20:44.814>
closer = 'pitrou'
components = ['Documentation']
creation = <Date 2017-11-07.07:00:44.069>
creator = 'JelleZijlstra'
dependencies = []
files = []
hgrepos = []
issue_num = 31965
keywords = ['patch']
message_count = 3.0
messages = ['305713', '305773', '305774']
nosy_count = 3.0
nosy_names = ['pitrou', 'davin', 'JelleZijlstra']
pr_nums = ['4304', '4321']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31965'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
https://docs.python.org/3/library/multiprocessing.html#multiprocessing.connection.Client claims that there is an "authenticate" argument, but it does not exist in the implementation (https://github.com/python/cpython/blob/master/Lib/multiprocessing/connection.py#L487).

**Comment by pitrou** [comment]
New changeset 1e5d54cfa031f1de9ee2d2e968e0551b6e2397b7 by Antoine Pitrou (Jelle Zijlstra) in branch 'master':
bpo-31965: fix doc for multiprocessing.connection.Client and Listener (bpo-4304)
https://github.com/python/cpython/commit/1e5d54cfa031f1de9ee2d2e968e0551b6e2397b7

**Comment by pitrou** [comment]
New changeset d9c61c2a2662761dc89e0be14ceb7ea57531c836 by Antoine Pitrou (Miss Islington (bot)) in branch '3.6':
bpo-31965: fix doc for multiprocessing.connection.Client and Listener (GH-4304) (bpo-4321)
https://github.com/python/cpython/commit/d9c61c2a2662761dc89e0be14ceb7ea57531c836
