### ISSUE TITLE
[EASY C][Windows] print('hello\n', end='', flush=True) raises OSError when ran with py -u

### ISSUE THREAD

**Issue by 14fed527-981a-4e6c-b2be-7a38e07f7c52** [python/cpython#76147]
BPO | [31966](https://bugs.python.org/issue31966)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @eryksun, @zooba, @miss-islington
PRs | <li>python/cpython#5754</li><li>python/cpython#5852</li><li>python/cpython#5853</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-06-16.08:47:53.851>
created_at = <Date 2017-11-07.09:40:05.730>
labels = ['easy', 'type-bug', '3.7', 'expert-IO', 'OS-windows']
title = "[EASY C][Windows] print('hello\\n', end='', flush=True) raises OSError when ran with py -u"
updated_at = <Date 2018-06-16.08:47:53.850>
user = 'https://bugs.python.org/GuillaumeAldebert'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-16.08:47:53.850>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-06-16.08:47:53.851>
closer = 'serhiy.storchaka'
components = ['Windows', 'IO']
creation = <Date 2017-11-07.09:40:05.730>
creator = 'Guillaume Aldebert'
dependencies = []
files = []
hgrepos = []
issue_num = 31966
keywords = ['patch', 'easy (C)']
message_count = 10.0
messages = ['305726', '305733', '305734', '305744', '305750', '305756', '305762', '312730', '312735', '312736']
nosy_count = 9.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'eryksun', 'steve.dower', 'Guillaume Aldebert', 'miss-islington']
pr_nums = ['5754', '5852', '5853']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31966'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 14fed527-981a-4e6c-b2be-7a38e07f7c52** [comment]
noticed on windows10, 3.6.3-64 and 3.7.0a2-64:

using this test.py file:

```py
#!/usr/bin/env python3
print('hello\n', end='', flush=True)
```


and running it in unbuffered mode:

```pytb
C:\Dev>py -u test.py
hello
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    print('hello\n', end='', flush=True)
OSError: [WinError 87] The parameter is incorrect
```


Note that (still using py -u):

```py
print('hello', end='', flush=True) # works fine
print('', end='', flush=True) # raises OSError as well
```

**Comment by serhiy-storchaka** [comment]
The problem is with \_WindowsConsoleIO.

```pytb
C:\py\cpython>python.bat -u -c "import sys; sys.stdout.buffer.write(b'')"
Running Release|Win32 interpreter...
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [WinError 87] The parameter is incorrect
```

**Comment by vstinner** [comment]
Once the bug will be fixed, it would be nice to test this simple case :-)

**Comment by vstinner** [comment]
serhiy.storchaka: "keywords: + easy (C)"

For easy issue, you should explain how do you want the issue to be fixed.

**Comment by serhiy-storchaka** [comment]
I don't know which part of \_WindowsConsoleIO.write() fails to handle empty bytes string, but the simplest and the most efficient way to fix this bug it to add an explicit check for zero length at the begin of this method and return Python integer 0 in this case.

The test should check that sys.stdout.buffer.write(b''), sys.stdout.buffer.write(b'') and sys.stdout.buffer.raw.write(b'') return 0 (the latter to checks should be performed only if the corresponding buffer and raw attributes exist). There are special tests for WindowsConsoleIO, it would be nice to add an explicit test here too.

**Comment by eryksun** [comment]
The error is in \_io__WindowsConsoleIO_write_impl. If it's passed a length 0 buffer, it still tries to decode it via MultiByteToWideChar, which fails as documented. As Serhiy says, it can simply return Python int(0) in the zero-length case.

**Comment by vstinner** [comment]
The \_io__WindowsConsoleIO_write_impl() function should be fixed to not call MultiByteToWideChar() but use 0 if the input string is zero. Ok, it makes sense.

In that case, I agree to call it a simple issue ;-)
