### ISSUE TITLE
re.groups() is not checking the arguments

### ISSUE THREAD

**Issue by 59f70d2f-0279-4c4d-878b-42ec4f353165** [python/cpython#76150]
BPO | [31969](https://bugs.python.org/issue31969)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.17:39:30.203>
created_at = <Date 2017-11-07.13:14:30.418>
labels = ['expert-regex', 'type-bug', 'invalid']
title = 're.groups() is not checking the arguments'
updated_at = <Date 2017-11-08.17:54:02.588>
user = 'https://bugs.python.org/narendrac'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.17:54:02.588>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.17:39:30.203>
closer = 'mrabarnett'
components = ['Regular Expressions']
creation = <Date 2017-11-07.13:14:30.418>
creator = 'narendrac'
dependencies = []
files = []
hgrepos = []
issue_num = 31969
keywords = []
message_count = 7.0
messages = ['305751', '305753', '305754', '305755', '305809', '305810', '305884']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'narendrac']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31969'
versions = ['Python 2.7']
```

</p></details>

**Comment by 59f70d2f-0279-4c4d-878b-42ec4f353165** [comment]
Hi Team,

I have observed a bug in re.groups() function behavior in Python as below:

Issue:
re.groups() is not validating the arguments

```pycon
Example:
>>> m = re.match(r'(\w+)@(\w+)\.(\w+)','username@hackerrank.com')
>>> m.groups()
('username', 'hackerrank', 'com')
>>> m.groups(1)
('username', 'hackerrank', 'com')
>>> m.groups(100000000000)
('username', 'hackerrank', 'com')
>>>
```


From the above, its clear that re.groups() and re.groups(\<somevalue\>) both are same. I think re.groups() is not validating the arguments.

Please review the same and provide your comments whether my views are correct or wrong

**Comment by serhiy-storchaka** [comment]
All work as designed. In your example you don't see a difference because all groups are defined. Look at other example:

```pycon
>>> import re
>>> m = re.match(r'(?:(\w+)@)?(\w+)\.(\w+)', 'hackerrank.com')
>>> m.groups()
(None, 'hackerrank', 'com')
>>> m.groups(1)
(1, 'hackerrank', 'com')
>>> m.groups(100000000000)
(100000000000, 'hackerrank', 'com')
```

**Comment by 59f70d2f-0279-4c4d-878b-42ec4f353165** [comment]
Please look in to the following example:

```pycon
>>> m.groups()
('narendra', 'happiestmidns', 'com')
>>> m.groups(1)
('narendra', 'happiestmidns', 'com')
>>> m.groups(34)
('narendra', 'happiestmidns', 'com')
>>> m.groups(10000000000000000000000000000000000000000000000000000000)
('narendra', 'happiestmidns', 'com')
>>>
```

**Comment by serhiy-storchaka** [comment]
There is nothing wrong with this output if you use the first example.

**Comment by 59f70d2f-0279-4c4d-878b-42ec4f353165** [comment]
Hi Storchaka,

As per re.groups(), its should work as below:

```py
groups([default])
Return a tuple containing all the subgroups of the match, from 1 up to however many groups are in the pattern. The default argument is used for groups that did not participate in the match; it defaults to None. (Incompatibility note: in the original Python 1.5 release, if the tuple was one element long, a string would be returned instead. In later versions (from 1.5.1 on), a singleton tuple is returned in such cases.)
```


For example:

```pycon
>>> m = re.match(r"(\d+)\.(\d+)", "24.1632")
>>> m.groups()
('24', '1632')
If we make the decimal place and everything after it optional, not all groups might participate in the match. These groups will default to None unless the default argument is given:

>>> m = re.match(r"(\d+)\.?(\d+)?", "24")
>>> m.groups()      # Second group defaults to None.
('24', None)
>>> m.groups('0')   # Now, the second group defaults to '0'.
('24', '0')
```


I tested some scenario as below:
Scenario: Suppose i have a match like 
m = re.match(r"(\\d+)\\.(\\d+)", "24.1632")
Here if i pass m.groups(10000), then it should check if there is optional match (optional match, pattern which is specified using ?), it should print 10000 in that match and if not, it should throw error that there is no any optional match (didn't have any pattern with ?).

```pycon
Expected Output:
>>> m.groups(10000)
There is no any optional argument to use 10000

Received Output:
>>> m.groups(10000)
'24', '1632')
```


Please review the above and provide your comments?

**Comment by serhiy-storchaka** [comment]
No, it should not throw error that there is no any optional match.

It is not easy to check if there is optional match. For example, the pattern '(a)|(b)' contains optional matches, while the group in the pattern '()?' always matches.

**Comment by 39d85a87-36ea-41b2-b2bb-2be43abb500e** [comment]
@Narendra: The argument, if provided, is merely a default. Checking whether it \_could_ be used would not be straightforward, and raising an exception if it would never be used would have little, if any, benefit.

It's not a bug, and it's not worth changing.
