### ISSUE TITLE
threading.Condition can not work with threading.Semaphore

### ISSUE THREAD

**Issue by ghost** [python/cpython#76158]
BPO | [31977](https://bugs.python.org/issue31977)
--- | :---
Nosy | @tim-one, @rhettinger, @pitrou

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-09.16:42:29.934>
created_at = <Date 2017-11-08.05:12:05.708>
labels = ['type-bug']
title = 'threading.Condition can not work with threading.Semaphore'
updated_at = <Date 2017-11-09.16:42:29.933>
user = None
```

bugs.python.org fields:
```python
activity = <Date 2017-11-09.16:42:29.933>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-09.16:42:29.934>
closer = 'pitrou'
components = []
creation = <Date 2017-11-08.05:12:05.708>
creator = '\xe5\xbc\xa0\xe6\x99\x93\xe6\x9e\x97'
dependencies = []
files = []
hgrepos = []
issue_num = 31977
keywords = []
message_count = 3.0
messages = ['305807', '305910', '305938']
nosy_count = 4.0
nosy_names = ['tim.peters', 'rhettinger', 'pitrou', '\xe5\xbc\xa0\xe6\x99\x93\xe6\x9e\x97']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue31977'
versions = ['Python 3.6']
```

</p></details>

**Comment by ghost** [comment]
the python document say Condition work will Locks, like RLock...

but i find it not work with Semaphore, because Condition.\_is_owned is like this

```py
    def _is_owned(self):
        # Return True if lock is owned by current_thread.
        # This method is called only if _lock doesn't have _is_owned().
        if self._lock.acquire(0):
            self._lock.release()
            return False
        else:
            return True
```


this work for RLock, but not work for Semaphore, and Semaphore do not have it's own \_is_owned implement.

i spend a lot of time on this issue. maybe fix it, or document it out?

**Comment by pitrou** [comment]
Why do you want Condition to work with a Semaphore?  What would be achieved?

A Semaphore is not a lock, it's an other kind of concurrency primitive.  I don't think there's any point in detailing it any futrher.

**Comment by rhettinger** [comment]
I concur with Antoine and don't think there is a real issue here to be solved.
