### ISSUE TITLE
Officially add Py_SETREF and Py_XSETREF

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76164]
BPO | [31983](https://bugs.python.org/issue31983)
--- | :---
Nosy | @rhettinger, @vstinner, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-25.09:30:41.146>
created_at = <Date 2017-11-08.16:24:41.385>
labels = ['interpreter-core', 'type-feature', '3.7', 'docs']
title = 'Officially add Py_SETREF and Py_XSETREF'
updated_at = <Date 2017-12-25.09:30:41.144>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-25.09:30:41.144>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-12-25.09:30:41.146>
closer = 'serhiy.storchaka'
components = ['Documentation', 'Interpreter Core']
creation = <Date 2017-11-08.16:24:41.385>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31983
keywords = []
message_count = 5.0
messages = ['305878', '305888', '305889', '306284', '309033']
nosy_count = 4.0
nosy_names = ['rhettinger', 'vstinner', 'docs@python', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31983'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Private macros Py_SETREF and Py_XSETREF were introduced in 3.6 and backported to all maintained versions for fixing bugs (see bpo-20440 and bpo-26200). They are helpful and used not only for the primary purpose, but also for simplifying the code. Their names don't start from underscore because I planned to make them public and didn't want massive renaming and backporting conflicts. Now I think it is a time to add them officially to the stable C API.

**Comment by 5531d0d8-2a9c-46ba-8b8b-ef76132a492c** [comment]
Just adding +1.

**Comment by serhiy-storchaka** [comment]
Does anyone want to propose a patch? This is mainly a documentation issue. Needed documenting Py_SETREF and Py_XSETREF in [Doc/c-api/refcounting.rst](https://github.com/python/cpython/blob/main/Doc/c-api/refcounting.rst), adding entries in [Doc/whatsnew/3.7.rst](https://github.com/python/cpython/blob/main/Doc/whatsnew/3.7.rst), and "[Misc/NEWS.d/next/C](https://github.com/python/cpython/blob/main/Misc/NEWS.d/next/C) API/", and updating a guard in [Include/object.h](https://github.com/python/cpython/blob/main/Include/object.h).

**Comment by rhettinger** [comment]
Adding my -1.   My experience was that these macros impaired my ability to maintain the code and interfered with useful patterns like delaying all decrefs until an object was in a consistent state.

While I know that name was bikeshedded quite a bit, the outcome is rather unintuitive:  https://twitter.com/raymondh/status/930535938459025408
