### ISSUE TITLE
Ctypes Packing Bitfields Incorrectly - GCC both Linux and Cygwin

### ISSUE THREAD

**Issue by 98e4335a-1a35-4751-a1e2-aae84cb11efd** [python/cpython#76168]
BPO | [31987](https://bugs.python.org/issue31987)
--- | :---
Nosy | @berkerpeksag, @mleroy003
Superseder | <li>bpo-29753: [Linux] ctypes packs bitfields Incorrectly</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-09.11:39:58.887>
created_at = <Date 2017-11-08.22:31:58.303>
labels = ['ctypes', 'type-bug']
title = 'Ctypes Packing Bitfields Incorrectly - GCC both Linux and Cygwin'
updated_at = <Date 2017-11-09.11:39:58.884>
user = 'https://github.com/mleroy003'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-09.11:39:58.884>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-09.11:39:58.887>
closer = 'berker.peksag'
components = ['ctypes']
creation = <Date 2017-11-08.22:31:58.303>
creator = 'mleroy003'
dependencies = []
files = []
hgrepos = []
issue_num = 31987
keywords = []
message_count = 2.0
messages = ['305914', '305957']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'mleroy003']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '29753'
type = 'behavior'
url = 'https://bugs.python.org/issue31987'
versions = ['Python 3.6']
```

</p></details>

**Comment by 98e4335a-1a35-4751-a1e2-aae84cb11efd** [comment]
```c
The structure :
typedef struct __attribute__ ((packed)) {
   unsigned int   F0:24;
   unsigned int   F3:24;
   unsigned int   F6:24;
   unsigned int   F9:24;
} StructF_T;
is mapped as expected by GCC under both Linux and Cygwin.
As expected, the memory layout seen by the C program is :
0x111111222222333333444444
```


Using this definition :
class StructF(ctypes.BigEndianStructure):
    \_pack_ = 1
    \_fields_ = [
        ('F0',      ctypes.c_uint, 24),
        ('F3',      ctypes.c_uint, 24),
        ('F6',      ctypes.c_uint, 24),
        ('F9',      ctypes.c_uint, 24),
    ]
The memory layout seen from Python is not consistent :
0x11111100222222003333330044444400

It seems that the pack option is ignored by ctypes in such a case.
I found the same problem using both ctypes.BigEndianStructure and ctypes.LittleEndianStructure

**Comment by berkerpeksag** [comment]
Thank you for your report. I believe this is a duplicate of bpo-29753.
