### ISSUE TITLE
8.3. collections — Container datatypes

### ISSUE THREAD

**Issue by 624e12bd-ed46-4839-96a9-6c8c25c500f8** [python/cpython#76163]
BPO | [31982](https://bugs.python.org/issue31982)
--- | :---
Nosy | @rhettinger, @csabella, @catchmonster, @miss-islington
PRs | <li>python/cpython#11960</li><li>python/cpython#11961</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2019-02-20.22:25:43.592>
created_at = <Date 2017-11-08.16:10:51.930>
labels = ['docs']
title = '8.3. collections \xe2\x80\x94 Container datatypes'
updated_at = <Date 2019-02-20.22:25:43.592>
user = 'https://github.com/catchmonster'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-20.22:25:43.592>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2019-02-20.22:25:43.592>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-11-08.16:10:51.930>
creator = 'Sasha Kacanski'
dependencies = []
files = []
hgrepos = []
issue_num = 31982
keywords = ['patch']
message_count = 6.0
messages = ['305876', '305903', '305905', '334307', '336152', '336153']
nosy_count = 5.0
nosy_names = ['rhettinger', 'docs@python', 'cheryl.sabella', 'Sasha Kacanski', 'miss-islington']
pr_nums = ['11960', '11961']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue31982'
versions = ['Python 3.6']
```

</p></details>

**Comment by 624e12bd-ed46-4839-96a9-6c8c25c500f8** [comment]
Hi,
In ChainMap example
c = ChainMap()        # Create root context
d = c.new_child()     # Create nested child context
e = c.new_child()     # Child of c, independent from d
e.maps[0]             # Current context dictionary -- like Python's locals()
e.maps[-1]            # Root context -- like Python's globals()
e.parents             # Enclosing context chain -- like Python's nonlocals

d['x']                # Get first key in the chain of contexts
d['x'] = 1            # Set value in current context

d['x'] - will raise key does not exist error 

so simple fix is to flip last two lines...

I know, possibly anal but look love Python and would like to help new folks to not get confused if they play with example in cPython shell...

--best

**Comment by rhettinger** [comment]
I will flip the two because there is not downside.  However, the table of wasn't intended to be a sequential example (that's why there is no data or display of result).  Instead, it was just meant to be table of typing-this-does-that.

**Comment by 624e12bd-ed46-4839-96a9-6c8c25c500f8** [comment]
Agree, and I know.
