### ISSUE TITLE
Deprecate openfp() in aifc, sunau and wave

### ISSUE THREAD

**Issue by briancurtin** [python/cpython#76166]
BPO | [31985](https://bugs.python.org/issue31985)
--- | :---
Nosy | @vstinner, @briancurtin, @serhiy-storchaka
PRs | <li>python/cpython#4344</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/briancurtin'
closed_at = <Date 2019-06-17.20:12:59.749>
created_at = <Date 2017-11-08.21:56:36.323>
labels = ['3.7', 'type-feature', 'library']
title = 'Deprecate openfp() in aifc, sunau and wave'
updated_at = <Date 2019-06-17.20:12:59.747>
user = 'https://github.com/briancurtin'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-17.20:12:59.747>
actor = 'vstinner'
assignee = 'brian.curtin'
closed = True
closed_date = <Date 2019-06-17.20:12:59.749>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-11-08.21:56:36.323>
creator = 'brian.curtin'
dependencies = []
files = []
hgrepos = []
issue_num = 31985
keywords = ['patch']
message_count = 8.0
messages = ['305912', '305917', '305924', '305989', '305995', '305999', '306038', '345896']
nosy_count = 3.0
nosy_names = ['vstinner', 'brian.curtin', 'serhiy.storchaka']
pr_nums = ['4344']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31985'
versions = ['Python 3.7']
```

</p></details>

**Comment by briancurtin** [comment]
Since 1993, aifc.openfp has simply pointed to aifc.open as a matter of backwards compatibility. See https://github.com/python/cpython/commit/7bc817d5ba917528e8bd07ec461c635291e7b06a for the exact change.

aifc.openfp is both undocumented and untested, and in looking at doc coverage I decided it's better to deprecate it since it's silently been there for 25 years.

**Comment by serhiy-storchaka** [comment]
Don't forget about wave and sunau.

You can use a common test for all three modules.

**Comment by briancurtin** [comment]
i was going to do them as separate bugs and PRs per module, but if one is fine then i can do that.

Updating the title as well since nothing is beings removed (was originally going to suggest skipping to removal but won’t  do that).

**Comment by briancurtin** [comment]
Serhiy, where should a common test that covers all three of these go? I'm not seeing an obvious place for it.

**Comment by serhiy-storchaka** [comment]
audiotests.py. Create class AudioMiscTests and inherit classes AifcMiscTest, SunauMiscTest, WaveMiscTest from it instead of AudioTests. There is more work because there was no base for misc tests, but this will make adding other common misc test easier.

**Comment by briancurtin** [comment]
I think https://github.com/python/cpython/pull/4344 covers what you're looking for.

**Comment by briancurtin** [comment]
New changeset 9f914a01affc55abe799afc521ce71612bb495a5 by Brian Curtin in branch 'master':
bpo-31985: Deprecate openfp in aifc, sunau, and wave (bpo-4344)
https://github.com/python/cpython/commit/9f914a01affc55abe799afc521ce71612bb495a5
