### ISSUE TITLE
Special case log(x, 2), log(x, 10) and pow(2, x)

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76161]
BPO | [31980](https://bugs.python.org/issue31980)
--- | :---
Nosy | @rhettinger, @mdickinson, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-08.20:17:57.181>
created_at = <Date 2017-11-08.12:59:05.318>
labels = ['extension-modules', 'type-feature', '3.7']
title = 'Special case log(x, 2), log(x, 10) and pow(2, x)'
updated_at = <Date 2017-11-08.21:21:26.614>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-08.21:21:26.614>
actor = 'mark.dickinson'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-08.20:17:57.181>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-11-08.12:59:05.318>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 31980
keywords = []
message_count = 10.0
messages = ['305825', '305852', '305890', '305894', '305895', '305898', '305899', '305902', '305907', '305908']
nosy_count = 4.0
nosy_names = ['rhettinger', 'mark.dickinson', 'stutzbach', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31980'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
C99 provides functions log2(), log10() and exp2(). Is it worth to special case math.log(), math.pow() and built-in pow() for using these functions? log2(x) can be more accurate than log(x)/log(2).

There are math.log2() and math.log10(), but not math.exp2().

**Comment by serhiy-storchaka** [comment]
There is also a GNU extension pow10().

**Comment by mdickinson** [comment]
I'd say not. If people want `log` base 2 or 10, they should use the appropriate functions.

One potential numeric issue here is maintaining monotonicity. If we swap out libm `log` calls for `log2` calls for some inputs, we not only make the code more complicated, but also risk breaking monotonicity.

So -1 from me on the special casing.

I'd be very happy with exposing exp2 in the math library, but that's a separate issue.

**Comment by serhiy-storchaka** [comment]
There is no two-argument libm `log`. Two-argument log(x, base) is implemented as log(x) / log(base). log(base) adds an error.

```pycon
>>> import math
>>> math.log(2**31, 2)
31.000000000000004
```


Since two-argument log() doesn't correspond a C function, I think we are free to use more precise implementation.

We could correct also two-argument logarithms with other bases. For example:

```py
def prec_log(x, y):
    a = math.log(x, y)
    return a + math.log(x / math.pow(y, a), y)
```


```pycon
>>> math.log(3**20, 3)
19.999999999999996
>>> prec_log(3**20, 3)
20.0
```

**Comment by mdickinson** [comment]
> There is no two-argument libm `log`. Two-argument log(x, base) is implemented as log(x) / log(base).

Yep. But log(x) / log(base) is monotonic in x for a fixed base, assuming that the libm log is. My objections still hold. :-) Please let's keep the math.log implementation simple (or at least, no more complicated than it already is).

**Comment by mdickinson** [comment]
Also, prec_log would need significant work to make it handle all the corner cases sensibly. For example:

```pycon
Python 3.6.3 (default, Oct  5 2017, 23:34:28) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import math
>>> def prec_log(x, y):
...     a = math.log(x, y)
...     return a + math.log(x / math.pow(y, a), y)
... 
>>> math.log(3**1000, 3)
999.9999999999999
>>> prec_log(3**1000, 3)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in prec_log
OverflowError: math range error
```

**Comment by serhiy-storchaka** [comment]
Okay. I think that log(x, base) still will be monotonic, because log(x, nextafter(2, +INF)) \<= log2(x) \<= log(x, nextafter(2, -INF)).

I know about this limitation of prec_log(). It was just an example. Maybe  Tim know more robust and efficient algorithms.

Exposing exp2 in the math library would be less interesting, because we don't add errors in pow() and just call libm pow(). The latter can call exp2() internally if it provides more accuracy than exp(log(x)*y).

**Comment by rhettinger** [comment]
-1 from me as well.  Various root finding and minimization algorithms rely (perhaps) incorrect on the functions transitioning smoothly across the inputs.

Inside the code for math.log10() and math.log2(), it would be reasonable to use the C99 functions rather than having us compute them indirectly.  But the math.log(x, b) function should be left alone IMO.

**Comment by mdickinson** [comment]
> Exposing exp2 in the math library would be less interesting

I disagree: a libm exp2 is likely to be significantly accurate than pow(2.0, x). The latter is unlikely to be special-cased by the libm pow.

> The latter can call exp2() internally if it provides more accuracy than exp(log(x)*y).

It would be a very poor pow implementation that used exp(log(x)*y).

**Comment by mdickinson** [comment]
> significantly accurate

significantly \*more* accurate
