### ISSUE TITLE
`setuptools.setup` parameter `py_modules` is undocumented

### ISSUE THREAD

**Issue by 69e621da-2c22-4a94-b8b0-560f135da99a** [python/cpython#76177]
BPO | [31996](https://bugs.python.org/issue31996)
--- | :---
Nosy | @berkerpeksag

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-09.23:37:48.589>
created_at = <Date 2017-11-09.23:34:14.863>
labels = ['type-feature', 'docs']
title = '`setuptools.setup` parameter `py_modules` is undocumented'
updated_at = <Date 2017-11-11.06:25:32.519>
user = 'https://bugs.python.org/LutherThompson'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-11.06:25:32.519>
actor = 'Luther Thompson'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-09.23:37:48.589>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-11-09.23:34:14.863>
creator = 'Luther Thompson'
dependencies = []
files = []
hgrepos = []
issue_num = 31996
keywords = []
message_count = 3.0
messages = ['305997', '305998', '306077']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', 'Luther Thompson']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31996'
versions = ['Python 3.6']
```

</p></details>

**Comment by 69e621da-2c22-4a94-b8b0-560f135da99a** [comment]
I wrote my own distribution package with only one module, but the module file was not being installed along with the dist info file. I found by looking up the code for the `six` module that `setup` has a `py_modules` parameter which apparently must be used to make the installation work. This module is not mentioned anywhere in https://packaging.python.org/tutorials/distributing-packages/.

**Comment by berkerpeksag** [comment]
Thank you for your report, but the correct place to report issues with packaging.p.o is https://github.com/pypa/python-packaging-user-guide

**Comment by 69e621da-2c22-4a94-b8b0-560f135da99a** [comment]
Thanks, done: https://github.com/pypa/python-packaging-user-guide/issues/397
