### ISSUE TITLE
json encoder exception could be better

### ISSUE THREAD

**Issue by 494a83a2-67cc-4e1d-a52d-c1ba68fcd566** [python/cpython#76175]
BPO | [31994](https://bugs.python.org/issue31994)
--- | :---
Nosy | @serhiy-storchaka
Superseder | <li>bpo-26623: JSON encode: more informative error</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-10.19:28:24.162>
created_at = <Date 2017-11-09.19:05:23.854>
labels = ['extension-modules', 'type-feature']
title = 'json encoder exception could be better'
updated_at = <Date 2017-11-10.19:33:35.910>
user = 'https://bugs.python.org/JasonHihn'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-10.19:33:35.910>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-10.19:28:24.162>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-11-09.19:05:23.854>
creator = 'Jason Hihn'
dependencies = []
files = []
hgrepos = []
issue_num = 31994
keywords = []
message_count = 3.0
messages = ['305980', '306043', '306044']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Jason Hihn']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '26623'
type = 'enhancement'
url = 'https://bugs.python.org/issue31994'
versions = ['Python 2.7']
```

</p></details>

**Comment by 494a83a2-67cc-4e1d-a52d-c1ba68fcd566** [comment]
Given this traceback:
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: 7.0374198 is not JSON serializable

It would actually be better to have the error reported as type(o)+ " is not JSON serializable."  because at first glance, 7.0374198 \*is* serializable. In this specific case, the issue can be fixed by attempting to serialize float(o), because it is a ndarray. Maybe there's a better way to do numpy types or some kind of automatic conversion but for now, this is only a request to alter the message, I'd hope to something like:

repr(o) + " of type " + type(o) + " is not JSON serializable"

It's it's really more about the type rather than the value being serialized.

**Comment by serhiy-storchaka** [comment]
This is a duplicate of bpo-24641.

**Comment by serhiy-storchaka** [comment]
Actually it was fixed in bpo-26623.
