### ISSUE TITLE
Make iteration over dict_items yield namedtuples

### ISSUE THREAD

**Issue by fad2c4c2-24ea-4998-b3d2-19364cfd7635** [python/cpython#76173]
BPO | [31992](https://bugs.python.org/issue31992)
--- | :---
Nosy | @rhettinger, @ericvsmith, @bitdancer, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-10.13:28:26.510>
created_at = <Date 2017-11-09.16:24:13.265>
labels = ['3.8', 'type-feature', 'library']
title = 'Make iteration over dict_items yield namedtuples'
updated_at = <Date 2017-11-10.13:28:26.500>
user = 'https://bugs.python.org/RichardNeumann'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-10.13:28:26.500>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-10.13:28:26.510>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-11-09.16:24:13.265>
creator = 'Richard Neumann'
dependencies = []
files = []
hgrepos = []
issue_num = 31992
keywords = []
message_count = 5.0
messages = ['305970', '305972', '305986', '306028', '306030']
nosy_count = 5.0
nosy_names = ['rhettinger', 'eric.smith', 'r.david.murray', 'serhiy.storchaka', 'Richard Neumann']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue31992'
versions = ['Python 3.8']
```

</p></details>

**Comment by fad2c4c2-24ea-4998-b3d2-19364cfd7635** [comment]
Currently, iterating over dict_items will yield plain tuples, where the first item will be the key and the second item will be the respective value.

This has some disadvantages when e.g. sorting dict items by value and key:

```py
    def sort_by_value_len(dictionary):
        return sorted(dictionary.items(), key=lambda item: (len(item[1]), item[0]))
```


I find this index accessing extremely unelegant and unnecessarily hard to read.

If dict_items would instead yield namedtuples like

```py
    DictItem = namedtuple('DictItem', ('key', 'value'))
```


this would make constructs like

```py
    def sort_by_value_len(dictionary):
        return sorted(dictionary.items(), key=lambda item: (len(item.value), item.key))
```


possible and increase code clarity a lot.
Also, namedtuples mimic the behaviour of plain tuples regarding unpacking and index accessing, so that backward-compatipility should exist.

**Comment by serhiy-storchaka** [comment]
Oh, no! Tuples is one of the most charming features of Python. Use tuples, folk!

**Comment by ericvsmith** [comment]
I cannot imagine this ever happening, for performance reasons.

You should write your own wrapper around items, if you want this behavior.

**Comment by fad2c4c2-24ea-4998-b3d2-19364cfd7635** [comment]
Maybe there is no need to sacrifice performance, if a new, optional keyword argument would be introduced to dict.items():

```py
    def items(self, named=False):
        if named:
            <yield namedtuples>
        else:
            <current behaviour>
```


Currently I need to define a namedtuple everywhere I do this and starmap the dicts' items.

It'd be nice to have this option built-in or a new collections class like:

```py
    from collections import namedtuple
    from itertools import starmap


    DictItem = namedtuple('DictItem', ('key', 'value'))


    class NamedDict(dict):
        """Dictionary that yields named tuples on item iterations."""

        def items(self):
            """Yields DictItem named tuples."""
            return starmap(DictItem, super().items())
```

**Comment by bitdancer** [comment]
This is not something it is worth complicating the dict API or collections for.  If you want the feature in your code, implement your subclass in your own utility library.

If you disagree with this decision, please bring it up on the python-ideas mailing list for further analysis, but I'm guessing you won't get much traction.
