### ISSUE TITLE
setattr on a property gives a very unhelpful exception

### ISSUE THREAD

**Issue by 26f60f10-1ca0-4f2c-9ef2-41f19249dc8a** [python/cpython#76170]
BPO | [31989](https://bugs.python.org/issue31989)
--- | :---
Nosy | @rhettinger, @diekhans, @bitdancer
Superseder | <li>bpo-27794: setattr a read-only property; the AttributeError should show the attribute that failed</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-09.14:20:41.506>
created_at = <Date 2017-11-09.04:11:26.034>
labels = ['3.8', 'type-bug', '3.7']
title = 'setattr on a property gives a very unhelpful exception'
updated_at = <Date 2017-11-09.14:20:41.491>
user = 'https://github.com/diekhans'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-09.14:20:41.491>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-09.14:20:41.506>
closer = 'r.david.murray'
components = []
creation = <Date 2017-11-09.04:11:26.034>
creator = 'diekhans'
dependencies = []
files = []
hgrepos = []
issue_num = 31989
keywords = []
message_count = 4.0
messages = ['305933', '305934', '305935', '305961']
nosy_count = 3.0
nosy_names = ['rhettinger', 'diekhans', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '27794'
type = 'behavior'
url = 'https://bugs.python.org/issue31989'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 26f60f10-1ca0-4f2c-9ef2-41f19249dc8a** [comment]
done a setattr on a property gives a very unhelpful error message

   AttributeError: can't set attribute

it neither indicates the name of the attribute that failed or the cause.

an error such as "can't set property attribute: the_attr_name"

would be far more helpful.

**Comment by rhettinger** [comment]
Usually, all the necessary information is present in the previous line of the traceback:

```pycon
    >>> a.volume = 10
    Traceback (most recent call last):
      File "<pyshell#6>", line 1, in <module>
        a.volume = 10
    AttributeError: can't set attribute
```


I don't seem to recall anyone else having problems with this error message.

**Comment by 26f60f10-1ca0-4f2c-9ef2-41f19249dc8a** [comment]
The trackback is not helpful if the attribute name is in a
variable.  It also doesn't explain why the error occurred.

While I would not rate this as a high priority, I don't see an
argument for having uninformative error messages.

```pycon
Raymond Hettinger <report@bugs.python.org> writes:
> 
> Raymond Hettinger <raymond.hettinger@gmail.com> added the comment:
> 
> Usually, all the necessary information is present in the previous line of the traceback:
> 
>     >>> a.volume = 10
>     Traceback (most recent call last):
>       File "<pyshell#6>", line 1, in <module>
>         a.volume = 10
>     AttributeError: can't set attribute
> 
> I don't seem to recall anyone else having problems with this error message.
> 
> 
```
----------
> nosy: +rhettinger
> 
> _______________________________________
> Python tracker \<report@bugs.python.org\>
> \<https://bugs.python.org/issue31989\>
> _______________________________________

**Comment by bitdancer** [comment]
This is a duplicate of bpo-27794.
