### ISSUE TITLE
Allow specifying code packing order in audioop adpcm functions

### ISSUE THREAD

**Issue by 0370faa0-2ea3-45ef-9cfe-8179f57a0688** [python/cpython#76185]
BPO | [32004](https://bugs.python.org/issue32004)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka
Files | <li>[adpcm_test.zip](https://bugs.python.org/file47258/adpcm_test.zip "Uploaded as application/x-zip-compressed at 2017-11-10.23:40:07 by MosesofEgypt"): Zip containing an audio file and script to reproduce the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-10.23:40:07.435>
labels = ['3.8', 'type-bug', '3.7']
title = 'Allow specifying code packing order in audioop adpcm functions'
updated_at = <Date 2018-01-11.00:02:56.035>
user = 'https://bugs.python.org/MosesofEgypt'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-11.00:02:56.035>
actor = 'ncoghlan'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2017-11-10.23:40:07.435>
creator = 'MosesofEgypt'
dependencies = []
files = ['47258']
hgrepos = []
issue_num = 32004
keywords = []
message_count = 4.0
messages = ['306063', '306488', '308225', '309786']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'serhiy.storchaka', 'MosesofEgypt']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32004'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 0370faa0-2ea3-45ef-9cfe-8179f57a0688** [comment]
--- Issue \---
audioop.adpcm2lin and audioop.lin2adpcm currently treat the high 4 bits of each byte as the first code and the low 4 as the second code. In practice this is often the opposite.
http://www.drdobbs.com/database/algorithm-alley/184410326
https://wiki.multimedia.cx/index.php/Microsoft_IMA_ADPCM

--- Steps to reproduce \---
Run the attached script to decompress the attached wav to two different 16bit signed pcm wav files. The "GOOD" one had the nibbles of each code swapped before being decoded, while the "BAD" one didnt.

--- Suggested fix \---
I propose an additional optional boolean parameter to these functions to specify which nibble is the first code and which is the second.

NOTE: I haven't compiled my changes to test as I do not know how to set up a cpython build environment. This commit is more intended to show how to implement the fix.
https://github.com/MosesofEgypt/cpython/commit/4a5ca65833ec79857f065546ae0d90661ce26f5f

**Comment by 0370faa0-2ea3-45ef-9cfe-8179f57a0688** [comment]
Changed type to behavior as this is more of a bug fix than an enhancement.

**Comment by hugovk** [comment]
Closing, as the audioop module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/).
