### ISSUE TITLE
Python 3.6.3 venv FAILURE

### ISSUE THREAD

**Issue by 5f1fe87b-4938-4f71-8208-f8c41b2a764b** [python/cpython#76197]
BPO | [32016](https://bugs.python.org/issue32016)
--- | :---
Nosy | @ned-deily, @merwok, @csabella

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-22.12:43:10.087>
created_at = <Date 2017-11-13.19:18:46.299>
labels = []
title = 'Python 3.6.3 venv FAILURE'
updated_at = <Date 2018-02-22.12:43:10.087>
user = 'https://bugs.python.org/nihon2000'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-22.12:43:10.087>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-22.12:43:10.087>
closer = 'cheryl.sabella'
components = []
creation = <Date 2017-11-13.19:18:46.299>
creator = 'nihon2000'
dependencies = []
files = []
hgrepos = []
issue_num = 32016
keywords = []
message_count = 4.0
messages = ['306165', '306452', '312518', '312519']
nosy_count = 4.0
nosy_names = ['ned.deily', 'eric.araujo', 'cheryl.sabella', 'nihon2000']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32016'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5f1fe87b-4938-4f71-8208-f8c41b2a764b** [comment]
Upgraded from 3.6.1 to 3.6.3; but got an error when trying to create my virtual environment.

[larrchen@rslab239 Larry]$  /opt/python3.6.3/bin/python3.6 -m venv /u/larrchen/work2/SAN/Users/Larry/rslab239_myENV_363
Error: Command '['/u/larrchen/work2/SAN/Users/Larry/rslab239_myENV_363/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1.

I can create a virtual env for 3.6.1 and 3.6.2 but not for 3.6.3.

This is a regression issue. 

Try this command. It fails every time.

python3.6 -m venv myEnv

Larry

**Comment by merwok** [comment]
Can you find out the full error message from pip?
