### ISSUE TITLE
inspect.signature does not respect PEP 8

### ISSUE THREAD

**Issue by ilevkivskyi** [python/cpython#76199]
BPO | [32018](https://bugs.python.org/issue32018)
--- | :---
Nosy | @gvanrossum, @ericvsmith, @bitdancer, @1st1, @ilevkivskyi, @corona10
PRs | <li>python/cpython#4408</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.18:31:22.405>
created_at = <Date 2017-11-13.22:06:50.739>
labels = ['type-bug', '3.7']
title = 'inspect.signature does not respect PEP 8'
updated_at = <Date 2017-11-15.18:31:22.404>
user = 'https://github.com/ilevkivskyi'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.18:31:22.404>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.18:31:22.405>
closer = 'yselivanov'
components = []
creation = <Date 2017-11-13.22:06:50.739>
creator = 'levkivskyi'
dependencies = []
files = []
hgrepos = []
issue_num = 32018
keywords = ['patch']
message_count = 6.0
messages = ['306171', '306172', '306174', '306175', '306295', '306296']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'eric.smith', 'r.david.murray', 'yselivanov', 'levkivskyi', 'corona10']
pr_nums = ['4408']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32018'
versions = ['Python 3.7']
```

</p></details>

**Comment by ilevkivskyi** [comment]
The string representation of a function signature with annotations is currently like this:

```pycon
>>> def __init__(self, x: int = 1, y: int = 2) -> None: pass
... 
>>> import inspect
>>> str(inspect.signature(__init__))
'(self, x:str=1, y:int=2) -> None'
```


At the same time PEP-8 says:

When combining an argument annotation with a default value, use spaces around the = sign (but only for those arguments that have both an annotation and a default).

Yes:

```py
def munge(sep: AnyStr = None): ...
def munge(input: AnyStr, sep: AnyStr = None, limit=1000): ...
```


No:

```py
def munge(input: AnyStr=None): ...
def munge(input: AnyStr, limit = 1000): ...
```


I think there should be spaces in the signature repr.

**Comment by bitdancer** [comment]
FWIW, I find the version without the spaces to be more readable (but I don't find annotations to be readable in general, so my opinion may not be worth much :)

**Comment by gvanrossum** [comment]
Those people who read and write annotations regularly are all using the convention that was added to PEP-8, so let's make inspect follow that lead rather than argue about it here. :-)

**Comment by bitdancer** [comment]
Agreed.

**Comment by corona10** [comment]
I've submitted a patch. :)

**Comment by 1st1** [comment]
New changeset 762b9571c9c8c6b036f1bf90140a1d030b3f9a01 by Yury Selivanov (Dong-hee Na) in branch 'master':
bpo-32018: Fix inspect.signature repr to follow PEP-8 (bpo-4408)
https://github.com/python/cpython/commit/762b9571c9c8c6b036f1bf90140a1d030b3f9a01
