### ISSUE TITLE
seg fault when using Cntrl-q keymap to exit app

### ISSUE THREAD

**Issue by 18941071-c46c-4921-a6ee-f0ec2a4359a8** [python/cpython#76190]
BPO | [32009](https://bugs.python.org/issue32009)
--- | :---
Nosy | @vadmium
Superseder | <li>bpo-25259: readline macros can segfault Python</li>
Files | <li>[the.inputrc](https://bugs.python.org/file47259/the.inputrc "Uploaded as text/plain at 2017-11-11.22:18:02 by Britton Kerin"): The ~/.inputrc file that is needed to trigger the problem</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-12.04:19:56.887>
created_at = <Date 2017-11-11.22:18:02.634>
labels = ['library', 'type-crash']
title = 'seg fault when using Cntrl-q keymap to exit app'
updated_at = <Date 2017-11-12.04:19:56.876>
user = 'https://bugs.python.org/BrittonKerin'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-12.04:19:56.876>
actor = 'martin.panter'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-12.04:19:56.887>
closer = 'martin.panter'
components = ['Library (Lib)']
creation = <Date 2017-11-11.22:18:02.634>
creator = 'Britton Kerin'
dependencies = []
files = ['47259']
hgrepos = []
issue_num = 32009
keywords = []
message_count = 2.0
messages = ['306094', '306101']
nosy_count = 2.0
nosy_names = ['martin.panter', 'Britton Kerin']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '25259'
type = 'crash'
url = 'https://bugs.python.org/issue32009'
versions = ['Python 3.4']
```

</p></details>

**Comment by 18941071-c46c-4921-a6ee-f0ec2a4359a8** [comment]
This probably applies to more recent version also.

It may be a readline bug, but I haven't seen it except when using the python interface, despite using this same .inputrc file with many different command line programs.

I've attached the \~/.inputrc which are required to trigger the problem. 
This simple script will allow the problem to be reproduced:

     #!/usr/bin/python3.4-dbg

```py
     import readline

     input('the_prompt> ')
```


After launching test.py with the given \~/.inputrc in place, simply type Cntrl-q to trigger the seg fault.

Perhaps if this can be confirmed to be a readline issue someone can submit a bug report to that project.

Britton

**Comment by vadmium** [comment]
This looks the same as bpo-25259. The trigger is that multiple lines are generated at the same time, but Python only expects the first line.
