### ISSUE TITLE
_pickle: Py_DECREF seems to be missing from a failure case in fast_save_enter()

### ISSUE THREAD

**Issue by ce18c6f8-ec9c-4895-8ca5-c28785080292** [python/cpython#76194]
BPO | [32013](https://bugs.python.org/issue32013)
--- | :---
Nosy | @serhiy-storchaka, @lioncash
PRs | <li>python/cpython#4384</li><li>python/cpython#4385</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-13.08:21:13.558>
created_at = <Date 2017-11-13.05:08:34.362>
labels = ['extension-modules', '3.7', 'performance']
title = '_pickle: Py_DECREF seems to be missing from a failure case in fast_save_enter()'
updated_at = <Date 2017-11-13.08:21:13.557>
user = 'https://github.com/lioncash'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-13.08:21:13.557>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-13.08:21:13.558>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-11-13.05:08:34.362>
creator = 'Mathew M.'
dependencies = []
files = []
hgrepos = []
issue_num = 32013
keywords = ['patch']
message_count = 3.0
messages = ['306139', '306147', '306148']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Mathew M.']
pr_nums = ['4384', '4385']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue32013'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ce18c6f8-ec9c-4895-8ca5-c28785080292** [comment]
Hey there! I'm fairly new to the development process for Python, so I figured I'd start off with something tiny and then work on up from there. I'm not sure if this sort of minor fix warrants an issue being created, but I made this just to err on the safe side of things.

So, as far as I understand (by all means correct me if I'm wrong), a 'Py_DECREF(key);' should be present before the return in the conditional within fast_save_enter() (https://github.com/python/cpython/blob/d7d4fea4a39da4bfdea1de22fe040023eb4ddc17/Modules/_pickle.c#L1792)

**Comment by serhiy-storchaka** [comment]
New changeset f76231f89a7231fd486b37f728fbb4aab389e4d7 by Serhiy Storchaka (Mat M) in branch 'master':
bpo-32013: \_pickle: Add missing Py_DECREF in error case in fast_save_enter() (bpo-4384)
https://github.com/python/cpython/commit/f76231f89a7231fd486b37f728fbb4aab389e4d7

**Comment by serhiy-storchaka** [comment]
New changeset 6ed9d4ecde8c3f0eeadf188f15a5bbd32b9d1145 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
bpo-32013: \_pickle: Add missing Py_DECREF in error case in fast_save_enter() (GH-4384) (bpo-4385)
https://github.com/python/cpython/commit/6ed9d4ecde8c3f0eeadf188f15a5bbd32b9d1145
