### ISSUE TITLE
arraymodule: Missing Py_DECREF in failure case of make_array()

### ISSUE THREAD

**Issue by ce18c6f8-ec9c-4895-8ca5-c28785080292** [python/cpython#76201]
BPO | [32020](https://bugs.python.org/issue32020)
--- | :---
Nosy | @serhiy-storchaka, @lioncash
PRs | <li>python/cpython#4391</li><li>python/cpython#4392</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-14.07:02:31.733>
created_at = <Date 2017-11-14.04:46:30.311>
labels = ['extension-modules', '3.7', 'performance']
title = 'arraymodule: Missing Py_DECREF in failure case of make_array()'
updated_at = <Date 2017-11-14.07:03:09.522>
user = 'https://github.com/lioncash'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-14.07:03:09.522>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-14.07:02:31.733>
closer = 'serhiy.storchaka'
components = ['Extension Modules']
creation = <Date 2017-11-14.04:46:30.311>
creator = 'Mathew M.'
dependencies = []
files = []
hgrepos = []
issue_num = 32020
keywords = ['patch']
message_count = 4.0
messages = ['306183', '306184', '306186', '306187']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Mathew M.']
pr_nums = ['4391', '4392']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue32020'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by ce18c6f8-ec9c-4895-8ca5-c28785080292** [comment]
Similar to bpo-32013, just in a different location.

For reference: https://github.com/python/cpython/blob/28b624825eb92cb8c96fbf8da267d8d14a61a841/Modules/arraymodule.c#L1932

**Comment by serhiy-storchaka** [comment]
New changeset 56935a53b11b9a70f3e13e460777ec81a5b9195e by Serhiy Storchaka (Mat M) in branch 'master':
bpo-32020: arraymodule: Correct missing Py_DECREF in failure case of make_array() (bpo-4391)
https://github.com/python/cpython/commit/56935a53b11b9a70f3e13e460777ec81a5b9195e

**Comment by serhiy-storchaka** [comment]
New changeset 18056fb11e6fe6e5247cd03073bd74df8ac0acc7 by Serhiy Storchaka (Miss Islington (bot)) in branch '3.6':
bpo-32020: arraymodule: Correct missing Py_DECREF in failure case of make_array() (GH-4391) (bpo-4392)
https://github.com/python/cpython/commit/18056fb11e6fe6e5247cd03073bd74df8ac0acc7

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution Mathew!
