### ISSUE TITLE
argparse allow_abbrev option also controls short flag combinations

### ISSUE THREAD

**Issue by 8fa7ee1d-9770-452e-8c6f-a981d4690226** [python/cpython#76208]
BPO | [32027](https://bugs.python.org/issue32027)
--- | :---
Nosy | @berkerpeksag, @joernhees
PRs | <li>python/cpython#4396</li>
Superseder | <li>bpo-26967: argparse: allow_abbrev=False stops -vv from working</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-16.08:01:13.956>
created_at = <Date 2017-11-14.17:29:42.336>
labels = ['3.7', 'type-bug', 'library', 'docs']
title = 'argparse allow_abbrev option also controls short flag combinations'
updated_at = <Date 2018-09-11.01:47:50.345>
user = 'https://github.com/joernhees'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-11.01:47:50.345>
actor = 'paul.j3'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-16.08:01:13.956>
closer = 'berker.peksag'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2017-11-14.17:29:42.336>
creator = 'joern'
dependencies = []
files = []
hgrepos = []
issue_num = 32027
keywords = ['patch']
message_count = 3.0
messages = ['306229', '306343', '324976']
nosy_count = 4.0
nosy_names = ['docs@python', 'berker.peksag', 'joern', 'paul.j3']
pr_nums = ['4396']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '26967'
type = 'behavior'
url = 'https://bugs.python.org/issue32027'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 8fa7ee1d-9770-452e-8c6f-a981d4690226** [comment]
The allow_abbrev option (default True) currently is documented like this (https://docs.python.org/3/library/argparse.html#allow-abbrev):
> Normally, when you pass an argument list to the parse_args() method of an ArgumentParser, it recognizes abbreviations of long options.

However, it also controls combinations of short options and especially the combination of flags (store_const) like `-a -b` as `-ab`.

Example snippet for testing:

```py
import argparse
import sys

parser = argparse.ArgumentParser(
    allow_abbrev=False
)
parser.add_argument('-a', action='store_true')
parser.add_argument('-b', action='store_true')
parser.add_argument('x', nargs='*')
parser.parse_args('-a -b foo bar'.split())
parser.parse_args('-ab foo bar'.split())
```



As you can see the 2nd parse will fail if allow_abbrev=False.

This issue is either a doc issue only or an unintended combination of long option shortening and (the way more common) flag combinations. When i deactivated this in my code, i wanted to disable the (nice to have) long option shortening, but i unintentionally also deactivated (MUST have) short flag combinations.

**Comment by berkerpeksag** [comment]
Thank you for the report and for the PR. I think this is a duplicate of bpo-26967.

> This issue is either a doc issue only or an unintended combination of
> long option shortening and (the way more common) flag combinations.

This is indeed a bug so it would be better to fix it.
