### ISSUE TITLE
Always require parentheses for genexps in base class lists

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#76204]
BPO | [32023](https://bugs.python.org/issue32023)
--- | :---
Nosy | @ncoghlan, @serhiy-storchaka
PRs | <li>python/cpython#4400</li>
Dependencies | <li>bpo-32012: Disallow ambiguous syntax f(x for x in [1],)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.15:54:47.629>
created_at = <Date 2017-11-14.10:25:03.999>
labels = ['interpreter-core', 'type-bug', '3.7']
title = 'Always require parentheses for genexps in base class lists'
updated_at = <Date 2017-11-15.15:54:47.628>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.15:54:47.628>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.15:54:47.629>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-11-14.10:25:03.999>
creator = 'ncoghlan'
dependencies = ['32012']
files = []
hgrepos = []
issue_num = 32023
keywords = ['patch']
message_count = 2.0
messages = ['306197', '306275']
nosy_count = 2.0
nosy_names = ['ncoghlan', 'serhiy.storchaka']
pr_nums = ['4400']
priority = 'low'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32023'
versions = ['Python 3.7']
```

</p></details>

**Comment by ncoghlan** [comment]
The compiler currently allows parentheses to be omitted if a generator expression is the sole entry in a base class list:

```pycon
    >>> class C(x for x in []): pass
    ... 
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    TypeError: cannot create 'generator' instances
```


The language reference states that the parentheses around a generator expression are only optional for "calls with only one argument": https://docs.python.org/3/reference/expressions.html#generator-expressions

A base class list is not a call, so this should be treated as a syntax error, rather than being handled as equivalent to `class C((x for x in [])): pass`

**Comment by serhiy-storchaka** [comment]
New changeset ddbce1378644f9d5ad0651e1c9035bd8c6502edc by Serhiy Storchaka in branch 'master':
bpo-32023: Disallow genexprs without parenthesis in class definitions. (bpo-4400)
https://github.com/python/cpython/commit/ddbce1378644f9d5ad0651e1c9035bd8c6502edc
