### ISSUE TITLE
The pwd module implementation incorrectly sets some attributes to None

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76214]
BPO | [32033](https://bugs.python.org/issue32033)
--- | :---
Nosy | @vstinner, @tiran, @xdegaye, @serhiy-storchaka, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#19502</li><li>python/cpython#19518</li><li>python/cpython#19519</li><li>python/cpython#32053</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-04-14.18:16:47.711>
created_at = <Date 2017-11-15.10:34:19.480>
labels = ['extension-modules', '3.8', 'type-bug', '3.7', '3.9']
title = 'The pwd module implementation incorrectly sets some attributes to None'
updated_at = <Date 2022-03-22.17:42:26.595>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-22.17:42:26.595>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2020-04-14.18:16:47.711>
closer = 'vstinner'
components = ['Extension Modules']
creation = <Date 2017-11-15.10:34:19.480>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 32033
keywords = ['patch']
message_count = 13.0
messages = ['306261', '306262', '306263', '306286', '306290', '306707', '306715', '306729', '366418', '366420', '366425', '366426', '415800']
nosy_count = 6.0
nosy_names = ['vstinner', 'christian.heimes', 'xdegaye', 'serhiy.storchaka', 'ZackerySpytz', 'miss-islington']
pr_nums = ['19502', '19518', '19519', '32053']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32033'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
On Android API 24:

```sh
$ python -c "import pwd; print(pwd.getpwuid(0))"
pwd.struct_passwd(pw_name='root', pw_passwd='', pw_uid=0, pw_gid=0, pw_gecos=None, pw_dir='/', pw_shell='/system/bin/sh')
```


The pw_gecos member is None and the test_values test of pwd fails because it expects a string. The fix is either (1) to skip the pw_gecos check in test_values for Android or (2) to modify the sets() function in [Modules/pwdmodule.c](https://github.com/python/cpython/blob/main/Modules/pwdmodule.c) to set an empty string instead of None when the member of the passwd structure is a NULL pointer.

POSIX [1] does not specify what are the possible values of the members of the struct passwd. GNU libc states that pw_dir and pw_shell may be NULL pointers so it seems that sets() is broken in these two cases.

[1] http://pubs.opengroup.org/onlinepubs/009695399/functions/getpwnam.html
[2] https://www.gnu.org/software/libc/manual/html_node/User-Data-Structure.html#User-Data-Structure

**Comment by vstinner** [comment]
> self.assertIsInstance(e.pw_gecos, str)

This test is wrong: it's perfectly fine to get None here.

Python must not test the OS itself, but only test our own code: make sure that Python converts properly C types to nice Python types, so a string or None.

I propose to use something like:

```py
def check_type(field):
    self.assertTrue(field is None or isinstance(field, str), repr(field))
```


...
check_type(e.pw_gecos)

**Comment by vstinner** [comment]
Hum, I changed my mind a little bit :-)

> (2) to modify the sets() function in [Modules/pwdmodule.c](https://github.com/python/cpython/blob/main/Modules/pwdmodule.c) to set an empty string instead of None when the member of the passwd structure is a NULL pointer.

I checked the doc: pwd doesn't mention None at all :-(
https://docs.python.org/dev/library/pwd.html

For practical reasons, maybe (2) is nicer option. It would avoid to have all existing code just for Android.

I'm not sure that it's very useful to distinguish NULL and an empty char* string.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
> I'm not sure that it's very useful to distinguish NULL and an empty char* string.

I agree. An attribute of a ('pwd' Python module) password database entry corresponds to the field of a line in a 'passwd' text file. So it makes sense that when the field is empty in the text file, the corresponding attribute be an empty string and never None if it is not an integer (FWIW Android does not have a 'passwd' file).

Changing the title of the issue.

**Comment by serhiy-storchaka** [comment]
I disagree. This is an old API, a thin wrapper around standard POSIX API, and returning an empty string instead of None will make impossible to distinguish NULL from "".

It is easy to convert None in an empty string in Python: `value or ''`.

I would change the test to

```py
    if field is not None:
        self.assertIsInstance(field, str)
```


or

```py
    self.assertIsInstance(field, (str, type(None)))
```


(I prefer the former variant).

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Changing test_pwd does not correct the fact that the current implementation of the pwd module may break an existing Python application since this (old indeed) API states "The uid and gid items are integers, all others are strings".

> returning an empty string instead of None will make impossible to distinguish NULL from "".

AFAIK in the 50 years since the creation of the unix operating system, there has never been an implementation of pwd that states that a string field may be either an empty string or NULL. And it is doubtful that there will ever be one, since this would break all (all, not just the Python applications) existing applications using pwd.

**Comment by serhiy-storchaka** [comment]
On your second link it is documented explicitly that pw_dir and pw_shell might be NULL. And at least for pw_shell the behavior for NULL and "" are different.

**Comment by vstinner** [comment]
> And at least for pw_shell the behavior for NULL and "" are different.

What is the difference between the two?
