### ISSUE TITLE
error mixing positional and non-positional arguments with `argparse`

### ISSUE THREAD

**Issue by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [python/cpython#76217]
BPO | [32036](https://bugs.python.org/issue32036)
--- | :---
Nosy | @stefanseefeld, @bitdancer
Files | <li>[test_argparse.py](https://bugs.python.org/file47268/test_argparse.py "Uploaded as text/plain at 2017-11-15.16:36:45 by @stefanseefeld"): script demonstrating inconsistent command-line parsing behaviour</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.23:07:01.834>
created_at = <Date 2017-11-15.16:36:45.147>
labels = ['type-bug', 'library']
title = 'error mixing positional and non-positional arguments with `argparse`'
updated_at = <Date 2017-11-15.23:07:01.833>
user = 'https://github.com/stefanseefeld'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.23:07:01.833>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.23:07:01.834>
closer = 'r.david.murray'
components = ['Library (Lib)']
creation = <Date 2017-11-15.16:36:45.147>
creator = 'stefan'
dependencies = []
files = ['47268']
hgrepos = []
issue_num = 32036
keywords = []
message_count = 5.0
messages = ['306283', '306291', '306294', '306302', '306317']
nosy_count = 2.0
nosy_names = ['stefan', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32036'
versions = []
```

</p></details>

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
I'm trying to mix positional and non-positional arguments with a script using `argparse`, but I observe inconsistent behaviour.
The attached test runs fine when invoked with

test_argparse.py --info a a=b
test_argparse.py a a=b --info

but produces the error `error: unrecognized arguments: a=b` when invoked as

test_argparse.py a --info a=b

Is this intended behaviour ? If yes, is this documented ? If not, is there a way to make this work with existing `argparse` versions ?

**Comment by bitdancer** [comment]
Can you reproduce this without your PosArgsParser?

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
On 15.11.2017 12:54, R. David Murray wrote:
> Can you reproduce this without your PosArgsParser?
I can indeed (by simply commenting out the `action` argument to the
`add_argument()` calls).
That obviously results in all positional arguments being accumulated in
the `goal` member, as there is no logic to distinguish `a` from `a=b`
semantically.

**Comment by 4a065e0a-5a59-4cf5-9556-75a89203eea9** [comment]
It looks like https://bugs.python.org/issue14191 is a conversation about the same inconsistent behaviour. It is set to "fixed". Can you comment on this ? Should I follow the advice mentioned there about how to work around the issue ?

**Comment by bitdancer** [comment]
Ah, yes, I'd managed to forget about that issue, even though I was the one that finally committed the fix.

So, the alternate parser will be in 3.7.  In the meantime you can grab the code from the commit and put it in a local file, I think.  You'll doubtless have to tweak a few things to use it that way, but it should be fairly straightforward.
