### ISSUE TITLE
Error when unpickling IncompleteReadError

### ISSUE THREAD

**Issue by 3ed583e0-60be-4935-8b29-857fa8238d63** [python/cpython#76215]
BPO | [32034](https://bugs.python.org/issue32034)
--- | :---
Nosy | @serhiy-storchaka, @1st1, @vwvw
PRs | <li>python/cpython#4404</li><li>python/cpython#4409</li><li>python/cpython#4411</li>
Files | <li>[Impossible_to_unpickle_IncompleteReadError.py](https://bugs.python.org/file47266/Impossible_to_unpickle_IncompleteReadError.py "Uploaded as text/plain at 2017-11-15.12:53:22 by @vwvw"): python script highlighting the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.22:15:15.157>
created_at = <Date 2017-11-15.12:53:23.296>
labels = ['3.7', 'expert-asyncio']
title = 'Error when unpickling IncompleteReadError'
updated_at = <Date 2017-11-16.00:28:28.464>
user = 'https://github.com/vwvw'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-16.00:28:28.464>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.22:15:15.157>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-11-15.12:53:23.296>
creator = 'badouxn'
dependencies = []
files = ['47266']
hgrepos = []
issue_num = 32034
keywords = ['patch']
message_count = 8.0
messages = ['306268', '306270', '306289', '306292', '306297', '306305', '306316', '306324']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'yselivanov', 'badouxn']
pr_nums = ['4404', '4409', '4411']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32034'
versions = ['Python 3.7']
```

</p></details>

**Comment by 3ed583e0-60be-4935-8b29-857fa8238d63** [comment]
When using asyncio in combination with multiprocessing, a TypeError occur when readuntil() encounter an EOF instead of the delimiter.
readuntil return a IncompleteReadError exception which is pickled by the multiprocessing package.
The unpickling failed due to an argument being None. As noted in the following links, it fails:
https://stackoverflow.com/questions/16244923/how-to-make-a-custom-exception-class-with-multiple-init-args-pickleable

```pytb
The error trace is: 
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 463, in _handle_results
    task = get()
  File "/usr/lib64/python3.6/multiprocessing/connection.py", line 252, in recv
    return _ForkingPickler.loads(r)
TypeError: __init__() missing 1 required positional argument: 'expected'
```



Fix proposed: 
Make the "expected" parameter of the IncompleteReadError exception class optional.

**Comment by serhiy-storchaka** [comment]
This isn't so simple.

```pycon
>>> from asyncio.streams import IncompleteReadError
>>> import pickle
>>> e1 = IncompleteReadError(b'abc', 10)
>>> e2 = pickle.loads(pickle.dumps(e1))
>>> print(e1)
3 bytes read on a total of 10 expected bytes
>>> print(e2)
44 bytes read on a total of None expected bytes
```

**Comment by 3ed583e0-60be-4935-8b29-857fa8238d63** [comment]
My first fix was indeed wrong. 
Upon looking further into it, it seems to me that the problem come from the fact that the call to super is not done with the right argument. 
Upon unpickling, the argument that will be passed to the \_\_init__ is the string representation built on line 33-34.
That's why, when leaving expected as optional the number returned is 44, the length of the string. 

I went looking for similar Exception class in the code base and found the MaybeEncodingError in multiprocessing/pool.py 

By replacing the Error content with this one I don't have any error anymore. The message is kept identical. 
'''
     def \_\_init__(self, partial, expected):
         super().\_\_init__(partial, expected)
         self.partial = partial
         self.expected = expected
     def \_\_str__(self):
         return ("%d bytes read on a total of %r expected bytes" % (len(partial), expected))
'''

Does such a fix looks correct to you ?

**Comment by 3ed583e0-60be-4935-8b29-857fa8238d63** [comment]
Typo in the last comment. The code should be:

'''
     def \_\_init__(self, partial, expected):
         super().\_\_init__(partial, expected)
         self.partial = partial
         self.expected = expected
     def \_\_str__(self):
         return ("%d bytes read on a total of %r expected bytes" % (len(self.partial), self.expected))
'''

**Comment by 1st1** [comment]
> Does such a fix looks correct to you ?

No, this fix won't restore exception.args properly.  I made a PR with a fix.

**Comment by serhiy-storchaka** [comment]
There is the same issue with LimitOverrunError.

I'm not sure that we should keep args the same. It affects \_\_str__ and \_\_repr__. badouxn overrides \_\_str__. And the result of \_\_repr__ currently looks like the exception constructor, but actually is not compatible with it.

```pycon
>>> IncompleteReadError(b'abc', 10)
IncompleteReadError('3 bytes read on a total of 10 expected bytes',)
```

**Comment by 1st1** [comment]
New changeset 43605e6bfa8d49612df4a38460d063d6ba781906 by Yury Selivanov in branch 'master':
bpo-32034: Make IncompleteReadError & LimitOverrunError pickleable bpo-4409
https://github.com/python/cpython/commit/43605e6bfa8d49612df4a38460d063d6ba781906

**Comment by 1st1** [comment]
New changeset f35076a002b958f991d180d6f945344cc5ab3900 by Yury Selivanov (Miss Islington (bot)) in branch '3.6':
bpo-32034: Make IncompleteReadError & LimitOverrunError pickleable python/cpython#48659 (bpo-4411)
https://github.com/python/cpython/commit/f35076a002b958f991d180d6f945344cc5ab3900
