### ISSUE TITLE
cgi: TypeError when no argument string is found

### ISSUE THREAD

**Issue by b485b51b-d27f-423a-8035-c9ad55e98281** [python/cpython#76210]
BPO | [32029](https://bugs.python.org/issue32029)
--- | :---
Nosy | @srittau, @berkerpeksag
Superseder | <li>bpo-27777: cgi.FieldStorage can&#x27;t parse simple body with Content-Length and no Content-Disposition</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-15.01:53:55.106>
created_at = <Date 2017-11-15.00:31:53.576>
labels = ['type-bug', 'library']
title = 'cgi: TypeError when no argument string is found'
updated_at = <Date 2017-11-15.01:53:55.097>
user = 'https://github.com/srittau'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-15.01:53:55.097>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-15.01:53:55.106>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-11-15.00:31:53.576>
creator = 'srittau'
dependencies = []
files = []
hgrepos = []
issue_num = 32029
keywords = []
message_count = 2.0
messages = ['306244', '306248']
nosy_count = 2.0
nosy_names = ['srittau', 'berker.peksag']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '27777'
type = 'behavior'
url = 'https://bugs.python.org/issue32029'
versions = ['Python 3.6']
```

</p></details>

**Comment by b485b51b-d27f-423a-8035-c9ad55e98281** [comment]
Consider the following code:

```py
    import cgi
    from io import BytesIO
```


    cgi.FieldStorage(BytesIO(b"{}"), environ={
        "REQUEST_METHOD": "POST",
        "CONTENT_TYPE": "application/json",
        "CONTENT_LENGTH": "14",
    })

This will throw the following exception:

```pytb
Traceback (most recent call last):
  File "foo.py", line 7, in <module>
    "CONTENT_LENGTH": "14",
  File "/usr/lib/python3.6/cgi.py", line 561, in __init__
    self.read_single()
  File "/usr/lib/python3.6/cgi.py", line 740, in read_single
    self.read_binary()
  File "/usr/lib/python3.6/cgi.py", line 762, in read_binary
    self.file.write(data)
TypeError: write() argument must be str, not bytes
```


Of course, the input does not contain any argument string to be parsed by FieldStorage. Nevertheless, a TypeError in a totally unrelated part of the code seems like a bug. In my opinion, FieldStorage should just remain empty in this case, or - at best - throw a ValueError with a sensible error message.

**Comment by berkerpeksag** [comment]
Thank you for your report. This looks like a duplicate of bpo-27777. You might workaround this by passing ``headers={"Content-Disposition": "inline"}`` to cgi.FieldStorage() (untested)
