### ISSUE TITLE
Sorting pahtlib.Paths does give the same order as sorting the (string) filenames of that pathlib.Paths

### ISSUE THREAD

**Issue by abf799b4-99dc-42c9-9e84-a3ad80056090** [python/cpython#76221]
BPO | [32040](https://bugs.python.org/issue32040)
--- | :---
Nosy | @bitdancer, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-16.18:40:03.050>
created_at = <Date 2017-11-15.19:48:55.532>
labels = ['extension-modules', 'type-bug', 'invalid']
title = 'Sorting pahtlib.Paths does give the same order as sorting the (string) filenames of that pathlib.Paths'
updated_at = <Date 2017-11-16.18:41:02.184>
user = 'https://bugs.python.org/QbLearningPython'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-16.18:41:02.184>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-16.18:40:03.050>
closer = 'r.david.murray'
components = ['Extension Modules']
creation = <Date 2017-11-15.19:48:55.532>
creator = 'QbLearningPython'
dependencies = []
files = []
hgrepos = []
issue_num = 32040
keywords = []
message_count = 5.0
messages = ['306304', '306306', '306367', '306394', '306395']
nosy_count = 3.0
nosy_names = ['r.david.murray', 'serhiy.storchaka', 'QbLearningPython']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32040'
versions = ['Python 3.6']
```

</p></details>

**Comment by abf799b4-99dc-42c9-9e84-a3ad80056090** [comment]
While testing a module, I have found a weird behaviour of pathlib package. I have a list of pathlib.Paths and I sorted() it. I assumed that the order retrieved by sorting a list of Paths would be the same as the order retrieved by sorting the list of their corresponding (string) filenames. But it is not the case.

I run the following example:


\==========================================================================


```py
from pathlib import Path
```


\# order string filenames

```py
filenames_for_testing = (
    '/spam/spams.txt',
    '/spam/spam.txt',
    '/spam/another.txt',
    '/spam/binary.bin',
    '/spam/spams/spam.ttt',
    '/spam/spams/spam01.txt',
    '/spam/spams/spam02.txt',
    '/spam/spams/spam03.ppp',
    '/spam/spams/spam04.doc',
)

sorted_filenames = sorted(filenames_for_testing)
```


\# output ordered list of string filenames

```py
print()
print("Ordered list of string filenames:")
print()
[print(f'\t{element}') for element in sorted_filenames]
print()
```


\# order paths (build from same string filenames)

```py
paths_for_testing = [
    Path(filename)
    for filename in filenames_for_testing
]
sorted_paths = sorted(paths_for_testing)
```


\# outoput ordered list of pathlib.Paths

```py
print()
print("Ordered list of pathlib.Paths:")
print()
[print(f'\t{element}') for element in sorted_paths]
print()
```


\# compare

```py
print()

if sorted_filenames == [str(path) for path in sorted_paths]:
    print('Ordered lists of string filenames and pathlib.Paths are EQUAL.')
```


else:
    print('Ordered lists of string filenames and pathlib.Paths are DIFFERENT.')

```py
    for element in range(0, len(sorted_filenames)):

        if sorted_filenames[element] != str(sorted_paths[element]):

            print()
            print('First different element:')
            print(f'\tElement #{element}')
            print(f'\t{sorted_filenames[element]} != {sorted_paths[element]}')
            break

print()
```




==========================================================================


The output of this script was:


\==========================================================================

Ordered list of string filenames:

	/spam/another.txt
	/spam/binary.bin
	/spam/spam.txt
	/spam/spams.txt
	/spam/spams/spam.ttt
	/spam/spams/spam01.txt
	/spam/spams/spam02.txt
	/spam/spams/spam03.ppp
	/spam/spams/spam04.doc


Ordered list of pathlib.Paths:

	/spam/another.txt
	/spam/binary.bin
	/spam/spam.txt
	/spam/spams/spam.ttt
	/spam/spams/spam01.txt
	/spam/spams/spam02.txt
	/spam/spams/spam03.ppp
	/spam/spams/spam04.doc
	/spam/spams.txt


Ordered lists of string filenames and pathlib.Paths are DIFFERENT.

First different element:
	Element #3
	/spam/spams.txt != /spam/spams/spam.ttt


\==========================================================================


As you can see, 'spam/spams.txt' goes in different places if you have sorted by pathlib.Paths than if you have sorted by string filenames.

I think that it is weird that sorting pathlib.Paths yields a different result than sorting their string filenames. I think that pathlib.Paths should be ordered by alphabetical order of their corresponding filenames.

Thank you.

**Comment by serhiy-storchaka** [comment]
Paths are ordered by lexicographical order of their corresponding components. Paths are not strings, and this this order is more natural for them.

The alphabetical order of Path strings:

    SPAMS.txt
    SPAM\file.txt

    spam\file.txt
    spams.txt

    spam-file.txt
    spam/file.txt
    spam_file.txt

The lexicographical order of Path components:

    SPAM\file.txt
    SPAMS.txt

    spam\file.txt
    spams.txt

    spam/file.txt
    spam-file.txt
    spam_file.txt

**Comment by abf799b4-99dc-42c9-9e84-a3ad80056090** [comment]
Thanks, serhiy.storchaka, for your answer.

I am not fully convinced.

You have described the current behaviour of the pathlib package.

But let me ask: should be this the desired behaviour?

Since string filenames and pathlib.Paths are different ways to refer to the same object (a path in a filesystem), should not be they behaved in the same way when sorting?

You pointed out that the current behaviour is "more natural order" for pathlib.Paths. I am not truly sure about that. Can you please provide any citation or additional information about that?

Thank you.

**Comment by bitdancer** [comment]
It is "obvious by inspection".  Paths are paths instead of strings because they are formed out of discrete path components instead of strings.  If you sorted each directory in the paths from the top down, and then sorted the subdirectories, and then sorted the filenames, you get that sorting by component.  It's the same order you would get out of an ls -R.

**Comment by bitdancer** [comment]
To put it another way, think about sorting a list of tuples.  Same behavior.
