### ISSUE TITLE
2to3 fix for operator.isCallable()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76227]
BPO | [32046](https://bugs.python.org/issue32046)
--- | :---
Nosy | @benjaminp, @merwok, @berkerpeksag, @serhiy-storchaka, @ilevkivskyi, @corona10
PRs | <li>python/cpython#4417</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-08-02.23:52:19.273>
created_at = <Date 2017-11-16.09:09:32.818>
labels = ['3.7', 'type-feature', 'expert-2to3']
title = '2to3 fix for operator.isCallable()'
updated_at = <Date 2018-08-02.23:52:19.270>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-02.23:52:19.270>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2018-08-02.23:52:19.273>
closer = 'berker.peksag'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2017-11-16.09:09:32.818>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 32046
keywords = ['patch']
message_count = 6.0
messages = ['306346', '306454', '307142', '307143', '321608', '322998']
nosy_count = 6.0
nosy_names = ['benjamin.peterson', 'eric.araujo', 'berker.peksag', 'serhiy.storchaka', 'levkivskyi', 'corona10']
pr_nums = ['4417']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32046'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Currently 2to3 converts `operator.isCallable(obj)` to `hasattr(obj, '__call__')`. This looks cumbersome, and can be deceived by instance attribute __call__. The more correct way is to use `isinstance(obj, collections.abc.Callable)`. Starting from Python 3.2 it can use the callable() builtin.

**Comment by gvanrossum** [comment]
I would convert this to `callable()` -- the conversion to collections.abc.Callable is more verbose and requires an extra import (that can be slow).

**Comment by merwok** [comment]
New changeset a489599793f9b00ddc2c68e2ce3bce9cbb2c09a2 by Éric Araujo (Dong-hee Na) in branch 'master':
bpo-32046: Update 2to3 when converts operator.isCallable(obj). (bpo-4417)
https://github.com/python/cpython/commit/a489599793f9b00ddc2c68e2ce3bce9cbb2c09a2

**Comment by merwok** [comment]
Merged in master, I suppose stable branches should be left alone?
