### ISSUE TITLE
Faulty behaviour in email.utils.parseaddr if square brackets in subject

### ISSUE THREAD

**Issue by e24332b5-515c-49d5-9bc2-940e702aabb4** [python/cpython#76239]
BPO | [32058](https://bugs.python.org/issue32058)
--- | :---
Nosy | @warsaw, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-17.14:07:11.929>
created_at = <Date 2017-11-17.11:06:43.762>
labels = ['type-bug', 'invalid', 'expert-email']
title = 'Faulty behaviour in email.utils.parseaddr if square brackets in subject'
updated_at = <Date 2017-11-17.14:15:34.903>
user = 'https://bugs.python.org/tomdewulf'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-17.14:15:34.903>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-17.14:07:11.929>
closer = 'r.david.murray'
components = ['email']
creation = <Date 2017-11-17.11:06:43.762>
creator = 'tom de wulf'
dependencies = []
files = []
hgrepos = []
issue_num = 32058
keywords = []
message_count = 4.0
messages = ['306431', '306435', '306436', '306438']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'tom de wulf']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32058'
versions = ['Python 3.5']
```

</p></details>

**Comment by e24332b5-515c-49d5-9bc2-940e702aabb4** [comment]
Probably a parsing bug in email.utils.parseaddr.

How to recreate:

```pycon
>>> import email.utils
>>> test = 'Subject: I am a bug [Random]\r\nFrom: someone <some@email.address>\r\n\r\n'
>>> email.utils.parseaddr(test)
('', 'I')
>>> email.utils.parseaddr(test.replace('[', '').replace(']',''))
('someone', 'some@email.address')
```


Expected behaviour: no need to remove the []'s

**Comment by bitdancer** [comment]
parseaddr is for parsing the contents of an address header, not for parsing any additional text.  So the correct way to call it is parseaddress('someone \<some@email.address\>').

In any case, please look in to the new email policies, which provide a much more convenient API:

```pycon
    >>> from email import message_from_bytes
    >>> from email.policy import default
    >>> m = message_from_bytes(b'Subject: I am a bug [Random]\r\nFrom: someone <some@email.address>\r\n\r\n', policy=default)
    >>> m['from']
    'someone <some@email.address>'
    >>> m['from'].addresses
    (Address(display_name='someone', username='some', domain='email.address'),)
    >>> m['from'].addresses[0].display_name
    'someone'
    >>> m['from'].addresses[0].username
    'some'
    >>> m['from'].addresses[0].addr_spec
    'some@email.address'
```

**Comment by e24332b5-515c-49d5-9bc2-940e702aabb4** [comment]
I do get this data from an IMAP fetch statement, see my code below:

    rv, data = imap.fetch(num, "(BODY[HEADER.FIELDS (FROM SUBJECT)])")
    if rv != 'OK':
        logging.error("Error getting message sender and subject (" + num.decode("ascii") + ")")
        return
    logging.info("Got message " + num.decode("ascii"))

```py
    sender_subject = data[0][1].decode("utf-8")
    sender = email.utils.parseaddr(sender_subject.replace('[', '').replace(']',''))[1].replace("\r\n", "")
```


Thank you for providing this new API though, I will make sure to switch to that.

**Comment by bitdancer** [comment]
Unfortunately the imap module in the stdlib doesn't provide a whole lot in the way of tools for parsing the imap data, just for sending it back and forth to the server.
