### ISSUE TITLE
Fix -x option documentation

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76231]
BPO | [32050](https://bugs.python.org/issue32050)
--- | :---
Nosy | @terryjreedy, @pfmoore, @vstinner, @tjguk, @zware, @serhiy-storchaka, @zooba
PRs | <li>python/cpython#4423</li><li>python/cpython#4424</li><li>python/cpython#4475</li><li>python/cpython#4477</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.01:24:27.926>
created_at = <Date 2017-11-16.15:49:19.715>
labels = ['3.7', 'OS-windows']
title = 'Fix -x option documentation'
updated_at = <Date 2017-11-24.01:24:27.925>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.01:24:27.925>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.01:24:27.926>
closer = 'vstinner'
components = ['Windows']
creation = <Date 2017-11-16.15:49:19.715>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32050
keywords = ['patch']
message_count = 17.0
messages = ['306365', '306366', '306369', '306371', '306376', '306377', '306381', '306472', '306475', '306476', '306477', '306551', '306561', '306563', '306564', '306566', '306869']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'paul.moore', 'vstinner', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'steve.dower']
pr_nums = ['4423', '4424', '4475', '4477']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32050'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Python has a -x option documented as a "DOS specific hack only":
https://docs.python.org/dev/using/cmdline.html#cmdoption-x

Python doesn't support MS-DOS since Python 2.1:
https://www.python.org/dev/peps/pep-0011/#no-longer-supported-platforms

I propose to deprecate the option in Python 3.7: using it emits a DeprecationWarning, option deprecated in the documentation; and remove the option in Python 3.8.

**Comment by vstinner** [comment]
The note in the documentation is wrong: the line number is correct when using the -x option, even if the first line is skipped.

Example with Python 2.7:
\---
```sh
$ cat x.py 
print(1)
print(2)
x
```


```pytb
$ python2 x.py 
1
2
Traceback (most recent call last):
  File "x.py", line 3, in <module>
    x
NameError: name 'x' is not defined

$ python2 -x x.py 
2
Traceback (most recent call last):
  File "x.py", line 3, in <module>
    x
NameError: name 'x' is not defined
```

---

Attached [PR 4423](https://github.com/python/cpython/pull/4423) fixes Python 2.7 documentation.

**Comment by serhiy-storchaka** [comment]
Python still supports Windows.

**Comment by vstinner** [comment]
> Python still supports Windows.

What is the use case for this option on Windows?

On Unix, the first line is usually used for the shebang, a line like:

   #!/usr/bin/env python3

But this shebang is seen as a comment in Python and Python simply ignore the shebang, seen as a comment.

**Comment by serhiy-storchaka** [comment]
The same as on DOS.

Change the extension of the Python script from .py to .bat, and insert the following first line:

@path\\to\\python -x %0 %1 %2 %3 %4 %5 %6 %7 %8 %9

Now you can run it as a bat-file. The command in the first line will run Python, passing the name of this file and up to 9 arguments (you can make it passing more than 9 arguments, but I don't remember the syntax). "@" disables printing this command itself. The first line is not valid Python syntax, but due to the -x option it will be skipped.

**Comment by vstinner** [comment]
> @path\\to\\python -x %0 %1 %2 %3 %4 %5 %6 %7 %8 %9

Oh wow, I never saw that before.

There is now a "py" launcher on Windows, do we still need such "hack"?

**Comment by serhiy-storchaka** [comment]
Yes, of course. The py launcher is not an alternative to this "hack". It just allows you to specify just "py" (with possible options -2, -3, -3.6) instead of hardcoding the full name to the Python binary or add the path to directory containing the Python binary to your PATH.

**Comment by terryjreedy** [comment]
So the hack is not specific to DOS but is still needed for Windows .bat files. They run in Command Prompt, which was once called the DOS box.  (I don't know if they work unaltered in PowerShell.)  It seems that the doc should be updated.

**Comment by serhiy-storchaka** [comment]
The current short line of the description was enough to me for understanding what is the purpose of this option and how it can be used (I didn't use Windows for more than 10 years). But I was surprised not founding more detailed information about this feature in the documentation. Definitely it should be better documented. Most of users will have no ideas about this feature.

**Comment by serhiy-storchaka** [comment]
It seems to me that the best way is to add the following line at the start of the script:

    @path\to\python -x %0 %* & exit /b

Or

    @py -3 -x %0 %* & exit /b

**Comment by vstinner** [comment]
Ok, I will update the doc instead of deprecating the option.

**Comment by vstinner** [comment]
New changeset 733b5f3f2f2425fa939d71bc317f2e0f1968c2a0 by Victor Stinner in branch '2.7':
bpo-32050: Fix -x option documentation (bpo-4423)
https://github.com/python/cpython/commit/733b5f3f2f2425fa939d71bc317f2e0f1968c2a0

**Comment by vstinner** [comment]
New changeset c5a2071586f735d2a61d1756e7011cfbb6ce86c9 by Victor Stinner in branch 'master':
bpo-32050: Fix -x option documentation (bpo-4475)
https://github.com/python/cpython/commit/c5a2071586f735d2a61d1756e7011cfbb6ce86c9

**Comment by vstinner** [comment]
New changeset 60a376cf0023d1070329d0e861a5596637ff3275 by Victor Stinner (Miss Islington (bot)) in branch '3.6':
bpo-32050: Fix -x option documentation (GH-4475) (bpo-4477)
https://github.com/python/cpython/commit/60a376cf0023d1070329d0e861a5596637ff3275

**Comment by vstinner** [comment]
I removed the note from the documentation since it was outdated.

Serhiy, Terry: Do you want to work on a patch to rephrase the "DOS specific hack only" sentence?

> @py -3 -x %0 %* & exit /b

I'm not a BATCH expert, so I don't know if this command works on all Windows version, or even on MS-DOS. So I'm not confident to propose such doc change myself, sorry.

**Comment by terryjreedy** [comment]
I don't know either.  Once of the Windows experts should review and revise.

**Comment by vstinner** [comment]
The initial proposition was to \*deprecate* the option.

In the meanwhile, I removed an outdated note.

While the documentation is not perfect, I don't feel confortable to fix it, so I left it unchanged.

I close this PR. Please open a new issue (with a PR if possible ;-)) if you want to enhance -x option documentation.
