### ISSUE TITLE
Possible issue in multiprocessing doc

### ISSUE THREAD

**Issue by 03cf939b-aae0-455a-8a50-ba1148daab25** [python/cpython#76232]
BPO | [32051](https://bugs.python.org/issue32051)
--- | :---
Nosy | @berkerpeksag, @1a1a11a
PRs | <li>python/cpython#4469</li><li>python/cpython#4577</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-27.01:23:18.907>
created_at = <Date 2017-11-16.17:27:04.327>
labels = ['easy', 'type-bug', '3.7', 'docs']
title = 'Possible issue in multiprocessing doc'
updated_at = <Date 2017-11-27.01:23:18.906>
user = 'https://github.com/1a1a11a'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-27.01:23:18.906>
actor = 'berker.peksag'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-27.01:23:18.907>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-11-16.17:27:04.327>
creator = '1a1a11a'
dependencies = []
files = []
hgrepos = []
issue_num = 32051
keywords = ['patch', 'easy']
message_count = 7.0
messages = ['306389', '306408', '306409', '306509', '307030', '307031', '307032']
nosy_count = 3.0
nosy_names = ['docs@python', 'berker.peksag', '1a1a11a']
pr_nums = ['4469', '4577']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32051'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 03cf939b-aae0-455a-8a50-ba1148daab25** [comment]
in multiprocessing doc https://docs.python.org/3.6/library/multiprocessing.html

```pycon
under 17.2.2.7.2. Using a remote manager, 
>>> from multiprocessing.managers import BaseManager
>>> import queue
>>> queue = queue.Queue()
>>> class QueueManager(BaseManager): pass
>>> QueueManager.register('get_queue', callable=lambda:queue)
>>> m = QueueManager(address=('', 50000), authkey=b'abracadabra')
>>> s = m.get_server()
>>> s.serve_forever()
```



queue is used as both module name and variable name, should this be avoided?

**Comment by berkerpeksag** [comment]
The example itself works fine, but I agree that it would be better to use a better name. We could replace ``('foo.bar.org', 50000)`` in the following examples with ``('', 50000)`` too.

Would you like to send a PR? The documentation file is located at [Doc/library/multiprocessing.rst](https://github.com/python/cpython/blob/main/Doc/library/multiprocessing.rst).

**Comment by 03cf939b-aae0-455a-8a50-ba1148daab25** [comment]
Thank you for answering!
Yes, I would be very happy to do that, this is going to be my first contribution! :)

**Comment by 03cf939b-aae0-455a-8a50-ba1148daab25** [comment]
Hi Berker, 
   I didn't update "following examples with ``('', 50000)`` too." because this is different than the previous one, this is client connecting to server, so hostname cannot be empty string.

**Comment by berkerpeksag** [comment]
New changeset c172fc5031a4035986bef0b2fcef906706d7abf3 by Berker Peksag (Jason Yang) in branch 'master':
bpo-32051: Fix name shadowing in multiprocessing docs (GH-4469)
https://github.com/python/cpython/commit/c172fc5031a4035986bef0b2fcef906706d7abf3

**Comment by berkerpeksag** [comment]
New changeset 8a957534f5182022ee8ac2dbaac4b4900dc98159 by Berker Peksag (Miss Islington (bot)) in branch '3.6':
bpo-32051: Fix name shadowing in multiprocessing docs (GH-4469)
https://github.com/python/cpython/commit/8a957534f5182022ee8ac2dbaac4b4900dc98159

**Comment by berkerpeksag** [comment]
Thanks!
