### ISSUE TITLE
python msilib view.fetch is not returning none

### ISSUE THREAD

**Issue by 999596c9-fb75-45ca-99ef-7653f1d8eb03** [python/cpython#76245]
BPO | [32064](https://bugs.python.org/issue32064)
--- | :---
Nosy | @pfmoore, @tjguk, @berkerpeksag, @zware, @zooba
Superseder | <li>bpo-1102: Add support for _msi.Record.GetString() and _msi.Record.GetInteger()</li>
Files | <li>[MSIFileRead.py](https://bugs.python.org/file47271/MSIFileRead.py "Uploaded as text/plain at 2017-11-17.20:37:30 by uday kiran"): source code where the bug is pointed</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-19.06:51:49.072>
created_at = <Date 2017-11-17.20:37:30.115>
labels = ['type-bug', 'OS-windows']
title = 'python msilib view.fetch is not returning none'
updated_at = <Date 2017-11-19.06:51:48.981>
user = 'https://bugs.python.org/udaykiran'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-19.06:51:48.981>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-19.06:51:49.072>
closer = 'berker.peksag'
components = ['Windows']
creation = <Date 2017-11-17.20:37:30.115>
creator = 'uday kiran'
dependencies = []
files = ['47271']
hgrepos = []
issue_num = 32064
keywords = []
message_count = 4.0
messages = ['306456', '306457', '306468', '306497']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'berker.peksag', 'zach.ware', 'steve.dower', 'uday kiran']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '1102'
type = 'behavior'
url = 'https://bugs.python.org/issue32064'
versions = ['Python 3.6']
```

</p></details>

**Comment by 999596c9-fb75-45ca-99ef-7653f1d8eb03** [comment]
Please see my script attached.

Once the records are completed, the View.Fetch() function should give a none value but intsead giving runtime error: \_msi.MSIError: unknown error 103

It is already mentioned in the bugs.
https://bugs.python.org/issue29364
https://bugs.python.org/issue1102

The comments mentioned as it will be fixed in the coming release.
But it is a long back comment,but still not fixed.

Any update on this?

**Comment by 999596c9-fb75-45ca-99ef-7653f1d8eb03** [comment]
It seems you have added some patches as .c files, but how do we apply those on windows machines?
No documentation related to it.

https://bugs.python.org/file24795/_msi_fetch.patch.txt
https://bugs.python.org/file11840/_msi.patch.txt

Could you please help me how to apply these patches on windows environment.

**Comment by 999596c9-fb75-45ca-99ef-7653f1d8eb03** [comment]
I tried adding the bugs to the python source code and compile it by using the steps in https://docs.python.org/devguide/ and the fix in https://bugs.python.org/file24795/_msi_fetch.patch.txt, but ended up with many compilation errors

**Comment by berkerpeksag** [comment]
bpo-1102 is still open so this bug is not fixed yet. I've just opened [PR 4459](https://github.com/python/cpython/pull/4459) to fix it.
