### ISSUE TITLE
textpad from curses package isn't handling backspace key

### ISSUE THREAD

**Issue by a7bb9bd2-8ac7-4129-a459-663608102adc** [python/cpython#76249]
BPO | [32068](https://bugs.python.org/issue32068)
--- | :---
Nosy | @ZackerySpytz, @bacher09, @krishnasai2020
PRs | <li>python/cpython#23466</li>
Files | <li>[textpad.patch](https://bugs.python.org/file47272/textpad.patch "Uploaded as text/plain at 2017-11-18.14:20:35 by @bacher09")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-18.14:20:36.509>
labels = ['3.7', 'type-bug', 'library']
title = "textpad from curses package isn't handling backspace key"
updated_at = <Date 2020-11-22.18:17:55.437>
user = 'https://github.com/bacher09'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-22.18:17:55.437>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2017-11-18.14:20:36.509>
creator = 'bacher09'
dependencies = []
files = ['47272']
hgrepos = []
issue_num = 32068
keywords = ['patch']
message_count = 2.0
messages = ['306481', '371805']
nosy_count = 3.0
nosy_names = ['ZackerySpytz', 'bacher09', 'SBC King']
pr_nums = ['23466']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32068'
versions = ['Python 3.7']
```

</p></details>

**Comment by a7bb9bd2-8ac7-4129-a459-663608102adc** [comment]
textpad isn't handling backspace key on my system and seems on others too. When I press backspace key, terminal sends `ascii.DEL` (127) and it isn't handled by textpad.

I've attached patch that fixes this, should I also create PR for this or patch is enough ?

**Comment by erlend-aasland** [comment]
Superseded by:

- #60436
