### ISSUE TITLE
Drop loop._make_legacy_ssl_transport

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#76250]
BPO | [32069](https://bugs.python.org/issue32069)
--- | :---
Nosy | @asvetlov, @1st1
PRs | <li>python/cpython#4451</li><li>python/cpython#4453</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-18.17:18:36.222>
created_at = <Date 2017-11-18.14:44:11.212>
labels = ['3.7', 'library', 'expert-asyncio']
title = 'Drop loop._make_legacy_ssl_transport'
updated_at = <Date 2017-11-18.17:18:36.220>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-18.17:18:36.220>
actor = 'asvetlov'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-18.17:18:36.222>
closer = 'asvetlov'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-11-18.14:44:11.212>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 32069
keywords = ['patch']
message_count = 3.0
messages = ['306482', '306483', '306484']
nosy_count = 2.0
nosy_names = ['asvetlov', 'yselivanov']
pr_nums = ['4451', '4453']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32069'
versions = ['Python 3.7']
```

</p></details>

**Comment by asvetlov** [comment]
It uses `wrap_socket` and exists only for backward compatibility with Python without ssl.MemoryBIO, which is Python 3.4

Let's cut it out from Python 3.7 and 3.6 -- it's safe, pretty sure.

**Comment by 1st1** [comment]
+1

**Comment by asvetlov** [comment]
New changeset 51d546ae4d563fde608e23c9c337fefd7e95c93f by Andrew Svetlov in branch 'master':
bpo-32069: Drop legacy SSL transport (bpo-4451)
https://github.com/python/cpython/commit/51d546ae4d563fde608e23c9c337fefd7e95c93f
