### ISSUE TITLE
Documentation: Some Unicode object functions don't indicate whether they return a new reference

### ISSUE THREAD

**Issue by ce18c6f8-ec9c-4895-8ca5-c28785080292** [python/cpython#76258]
BPO | [32077](https://bugs.python.org/issue32077)
--- | :---
Nosy | @serhiy-storchaka, @lioncash, @miss-islington
PRs | <li>python/cpython#4472</li><li>python/cpython#11243</li><li>python/cpython#11245</li><li>python/cpython#11246</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-12-19.20:13:42.417>
created_at = <Date 2017-11-20.00:00:14.331>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = "Documentation: Some Unicode object functions don't indicate whether they return a new reference"
updated_at = <Date 2018-12-19.20:13:42.414>
user = 'https://github.com/lioncash'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-19.20:13:42.414>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-12-19.20:13:42.417>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-11-20.00:00:14.331>
creator = 'Mathew M.'
dependencies = []
files = []
hgrepos = []
issue_num = 32077
keywords = ['patch']
message_count = 6.0
messages = ['306516', '306518', '306519', '332161', '332162', '332163']
nosy_count = 4.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'Mathew M.', 'miss-islington']
pr_nums = ['4472', '11243', '11245', '11246']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32077'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ce18c6f8-ec9c-4895-8ca5-c28785080292** [comment]
This is just something I've noticed when browsing the C API documentation for Unicode objects.

For example, the documentation entry for PyUnicode_DecodeMBCSStateful lacks the "Return value: New reference", etc.

**Comment by serhiy-storchaka** [comment]
C API functions return new references by default. It needs to be explicitly documented only when the function returns a borrowed reference.

**Comment by serhiy-storchaka** [comment]
Ah, you have changed just refcounts.dat! This is good.
