### ISSUE TITLE
Clarify the behavior of the staticmethod builtin

### ISSUE THREAD

**Issue by 11d85565-1b84-4e34-a913-fdb04ec94a64** [python/cpython#76251]
BPO | [32070](https://bugs.python.org/issue32070)
--- | :---
Nosy | @rhettinger, @haikuginger, @andresdelfino
PRs | <li>python/cpython#4362</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-12-24.07:47:56.825>
created_at = <Date 2017-11-18.18:04:14.975>
labels = ['type-feature', 'docs']
title = 'Clarify the behavior of the staticmethod builtin'
updated_at = <Date 2018-12-25.18:30:53.654>
user = 'https://github.com/haikuginger'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-25.18:30:53.654>
actor = 'adelfino'
assignee = 'docs@python'
closed = True
closed_date = <Date 2018-12-24.07:47:56.825>
closer = 'rhettinger'
components = ['Documentation']
creation = <Date 2017-11-18.18:04:14.975>
creator = 'haikuginger'
dependencies = []
files = []
hgrepos = []
issue_num = 32070
keywords = []
message_count = 3.0
messages = ['306489', '306505', '332513']
nosy_count = 4.0
nosy_names = ['rhettinger', 'docs@python', 'haikuginger', 'adelfino']
pr_nums = ['4362']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32070'
versions = []
```

</p></details>

**Comment by 11d85565-1b84-4e34-a913-fdb04ec94a64** [comment]
It looks like the original staticmethod docstring might have been based on the classmethod docstring, and it seems like the current description might not be accurate.

Current string:

...It can be called either on the class (e.g. C.f()) or on an instance (e.g. C().f()); the instance is ignored except for its class...

Proposed change:

It can be called either on the class (e.g. C.f()) or on an instance (e.g. C().f()). Both the class and the instance are ignored, and neither is passed implicitly as the first argument to the method.

**Comment by rhettinger** [comment]
ISTM the current wording is correct and aims to describe how staticmethods differ from regular methods.   With a regular methods we have "c.m(*a) -\> type(c).m(c, \*a)" and "C.m(*a) -\> C.m(*s)".  With a class method, only the first of those changes to "c.m(*a) -\> type(c).m(*a)". Expressed in English, this change is "the instance is ignored except for its class...".

That said, the staticmethod() docs could use a complete rewrite.  They amble all over the place and don't directly speak to what a static method is for (attaching regular functions to classes to improve findability) or how they work (use descriptor logic to suppress the usual behavior of prepend "self" to the argument list when called from an instance) or a concise motivating example.
