### ISSUE TITLE
string result of str(bytes()) in Python3

### ISSUE THREAD

**Issue by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [python/cpython#76259]
BPO | [32078](https://bugs.python.org/issue32078)
--- | :---
Nosy | @vstinner, @ezio-melotti, @ArnoCan
Files | <li>[source_and_output.tar.gz](https://bugs.python.org/file47274/source_and_output.tar.gz "Uploaded as application/gzip at 2017-11-20.01:26:13 by @ArnoCan"): example source with output for 2.7 and 3.6</li><li>[howto_bytes_005.py](https://bugs.python.org/file47275/howto_bytes_005.py "Uploaded as text/plain at 2017-11-20.05:37:48 by @ArnoCan"): reduced example</li><li>[howto_bytes_005typo.py](https://bugs.python.org/file47276/howto_bytes_005typo.py "Uploaded as text/plain at 2017-11-20.05:46:44 by @ArnoCan"): typo'fix</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-20.17:09:57.135>
created_at = <Date 2017-11-20.01:26:16.669>
labels = ['3.8', 'invalid', 'type-bug', '3.7', 'expert-unicode']
title = 'string result of str(bytes()) in Python3'
updated_at = <Date 2017-11-21.03:05:57.016>
user = 'https://github.com/ArnoCan'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-21.03:05:57.016>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-20.17:09:57.135>
closer = 'vstinner'
components = ['Unicode']
creation = <Date 2017-11-20.01:26:16.669>
creator = 'acue'
dependencies = []
files = ['47274', '47275', '47276']
hgrepos = []
issue_num = 32078
keywords = []
message_count = 6.0
messages = ['306521', '306527', '306528', '306567', '306617', '306622']
nosy_count = 3.0
nosy_names = ['vstinner', 'ezio.melotti', 'acue']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32078'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [comment]
Hello,
I am currently writing some dual-version libraries and have
to deal with str/unicode.
The attached code example contains the str/unicode handling.

The Python3.6.2 release behaves as I did not expected for
all of the following the conversions:

```py
  unicode = str  # @ReservedAssignment # it is intentional


  mystring = "abc"
  u0 = unicode(bytes(mystring.encode()))  # == str(mystring)

  mystring = "abc"
  u0 = unicode(bytes(mystring.encode('utf-8')))  # == str(mystring)

  mystring = "abc"
  u0 = unicode(bytes(mystring.encode('ascii')))  # == str(mystring)

  mystring = b"abc"
  u0 = unicode(mystring)  # == str(mystring)
```


results for Python3 in:

  type: \<class 'str'\>
  len:  6
  b'abc'

```py
while in Python2:
```


  type: \<type 'unicode'\>
  len:  3
  abc

I am  not sure whether this is the intended behavior because the manual
could eventually be misinterpreted:


  4.8.1. Bytes Objects

  Bytes objects are immutable sequences of single bytes. 
  Since many major binary protocols are based on the ASCII text 
  encoding, bytes objects offer several methods that are only 
  valid when working with ASCII compatible data and are closely
  related to string objects in a variety of other ways.

```py
    class bytes([source[, encoding[, errors]]])
```


  Firstly, the syntax for bytes literals is largely the same as 
  that for string literals, except that a b prefix is added:

I expected the 'b'-prefix to be added to the input only, but I
expect the output without a type-prefix, because it is just an
attribute/property.

The result for Python3 should be similar to Python2:

  type: \<type 'str'\>
  len:  3
  abc

Regards
Arno

**Comment by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [comment]
Hello,
the following reduced example probably shows the issue a
little better.

I have currently not yet the 3.7+ environment, but guess
the same behavior.


Regards
Arno

**Comment by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [comment]
Sorry for the typo.

**Comment by vstinner** [comment]
Calling str(bytes) is wrong in Python 3:

```pycon
$ python3 -bb
Python 3.6.2 (default, Oct  2 2017, 16:51:32) 
>>> str(b'abc')
BytesWarning: str() on a bytes instance
```


Just don't do that :-)

Use repr(bytes) if you want the b'...' format:

```pycon
>>> repr(b'abc')
"b'abc'"
```

**Comment by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [comment]
I got your point, missed it before, sorry.
So just for completeness.

My issue was basically about the ambiguity of the str()-constructor
and the str()-built-in-function. Therefore the len/type prints.

It works with parameters:

```pycon
(3.6.2) [acue@lap001 Desktop]$ python -bb
Python 3.6.2 (default, Jul 29 2017, 14:24:56) 
[GCC 4.8.3 20140911 (Red Hat 4.8.3-7)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> str(b"abc")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
BytesWarning: str() on a bytes instance
>>> 
>>> 
>>> str(b"abc", "utf-8")
'abc'
>>> 
>>> type(str(b"abc",'utf-8'))
<class 'str'>
>>> 
```


Is there a common approach to force the use of the str()-constructor instead of
the str()-built-in function and/or the \_\_str__()-method?

This would make the shared code of Python2/Python3 much easier, 
at least for unicode()-\>str().

**Comment by vstinner** [comment]
I'm sorry but the bug tracker is not the right place to ask such question. There are plenty of resources on the Internet explaining how to write code compatible with Python 2 and Python 3.
