### ISSUE TITLE
Expose LockFile on Windows

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76257]
BPO | [32076](https://bugs.python.org/issue32076)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-11-19.20:21:43.608>
labels = ['3.7', 'type-feature', 'library', 'OS-windows']
title = 'Expose LockFile on Windows'
updated_at = <Date 2017-11-19.20:21:43.608>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-19.20:21:43.608>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2017-11-19.20:21:43.608>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 32076
keywords = []
message_count = 1.0
messages = ['306514']
nosy_count = 5.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32076'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-108988

**Comment by pitrou** [comment]
msvcrt.locking() is sometimes practically useless since its so-called "non-blocking" mode will still block for 1 second.  Instead, the Windows API LockFile() function (and its companion UnlockFile()) allows real non-blocking locking.

Right now you have to call LockFile() using ctypes (see https://github.com/mwilliamson/locket.py/pull/8/files for an example).  It would be nice to expose it somewhere, for example in msvcrt or another module.

**Comment by aisk** [comment]
Added these functions to `_winapi` module in https://github.com/python/cpython/pull/108988, I think current implementation is a one to one to the original Windows API in C, just like other functions in `_winapi`.

Is there any suggestion?

**Comment by zooba** [comment]
There's not a lot of point adding private functions that we don't use anywhere. If there's a need in the stdlib (e.g. a public API for locking parts of files, ideally one that works on all platforms) or at least the test suite, then sure. But we don't want to have to maintain private APIs that we don't use.

**Comment by pitrou** [comment]
Indeed, the idea was to expose it for third-party code to use. I don't have a need for this currently anymore, so I can't really comment on whether it would still be desirable (after all, there a lots of Windows APIs and we don't want to expose all of them :-)).

**Comment by erlend-aasland** [comment]
Based on @pitrou and @zooba last comments, it sounds to me like this should be closed as not-planned.

**Comment by erlend-aasland** [comment]
Well, I'm closing this as not planned; if there is a need for this in the future, we can reopen the issue.
