### ISSUE TITLE
Might be a wrong implementation

### ISSUE THREAD

**Issue by e03cf6b4-d5dd-4542-acdb-36eb0020d1ef** [python/cpython#76255]
BPO | [32074](https://bugs.python.org/issue32074)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[combinations.py](https://bugs.python.org/file47273/combinations.py "Uploaded as text/plain at 2017-11-19.09:08:47 by Sai Bhargava Ramu")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-19.09:27:44.117>
created_at = <Date 2017-11-19.09:08:48.992>
labels = ['type-bug', 'invalid', 'docs']
title = 'Might be a wrong implementation'
updated_at = <Date 2017-11-19.09:27:44.115>
user = 'https://bugs.python.org/SaiBhargavaRamu'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-19.09:27:44.115>
actor = 'serhiy.storchaka'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-19.09:27:44.117>
closer = 'serhiy.storchaka'
components = ['Documentation']
creation = <Date 2017-11-19.09:08:48.992>
creator = 'Sai Bhargava Ramu'
dependencies = []
files = ['47273']
hgrepos = []
issue_num = 32074
keywords = []
message_count = 2.0
messages = ['306499', '306500']
nosy_count = 3.0
nosy_names = ['docs@python', 'serhiy.storchaka', 'Sai Bhargava Ramu']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32074'
versions = ['Python 3.5']
```

</p></details>

**Comment by e03cf6b4-d5dd-4542-acdb-36eb0020d1ef** [comment]
https://docs.python.org/2/library/itertools.html#itertools.combinations

#The behaviour of combinations function in documentation is different and I think identation is missing with `else`
#I didn't get the logic right is point out anything further. This might not be a real issue

**Comment by serhiy-storchaka** [comment]
The implementation in the documentation is correct. Did you tested your implementation?

The indentation of the "else" is correct. See https://docs.python.org/3/reference/compound_stmts.html#the-for-statement
