### ISSUE TITLE
C API: Clarify which C functions are safe to be called before Py_Initialize()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76267]
BPO | [32086](https://bugs.python.org/issue32086)
--- | :---
Nosy | @ncoghlan, @vstinner, @ned-deily, @ericsnowcurrently, @serhiy-storchaka, @AraHaan
Superseder | <li>bpo-32096: Py_DecodeLocale() fails if used before the runtime is initialized.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-21.15:49:51.916>
created_at = <Date 2017-11-20.14:21:16.388>
labels = ['interpreter-core', '3.7', 'release-blocker']
title = 'C API: Clarify which C functions are safe to be called before Py_Initialize()'
updated_at = <Date 2017-11-21.15:49:51.914>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-21.15:49:51.914>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-21.15:49:51.916>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2017-11-20.14:21:16.388>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32086
keywords = []
message_count = 7.0
messages = ['306544', '306588', '306589', '306590', '306615', '306632', '306657']
nosy_count = 6.0
nosy_names = ['ncoghlan', 'vstinner', 'ned.deily', 'eric.snow', 'serhiy.storchaka', 'Decorater']
pr_nums = []
priority = 'release blocker'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '32096'
type = None
url = 'https://bugs.python.org/issue32086'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
See the python-dev thread:
https://mail.python.org/pipermail/python-dev/2017-November/150605.html

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
For me, it looks like Py_DecodeLocal() is still safe (according to python 3.6.3 unless anything changed in it).

**Comment by vstinner** [comment]
> For me, it looks like Py_DecodeLocal() is still safe (according to python 3.6.3 unless anything changed in it).

This issue is a regression in Python 3.7.

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
Ah, I see now.

**Comment by ncoghlan** [comment]
bpo-32096 covers reverting the change to PyDecode_Locale specifically for 3.7.

We can use this issue to ask the broader question "Do we want to \*deprecate* our previously implied support for calling PyDecode_Locale() before Py_Initialize()?"

If the answer is "Yes", then we need to design a transition plan to a different API for setting config parameters that accept "wchar_t \*".

If the answer is "No", then we need to document that design constraint on the affected APIs.

Either way, we should also improve the way we communicate the list of C API methods that can be safely called before Py_Initialize.

**Comment by serhiy-storchaka** [comment]
Is there a \*need* to break existing code? What is the benefit and how large it in comparison with the necessary of rewriting every code that embeds Python (and supporting both ways for long time)?

**Comment by vstinner** [comment]
I mark this issue as a duplicate of bpo-32096.
