### ISSUE TITLE
Display DeprecationWarning, PendingDeprecationWarning and ImportWarning in debug mode

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76269]
BPO | [32088](https://bugs.python.org/issue32088)
--- | :---
Nosy | @warsaw, @vstinner, @ambv
PRs | <li>python/cpython#4474</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-20.17:48:41.611>
created_at = <Date 2017-11-20.14:26:42.890>
labels = ['3.7', 'type-feature', 'library']
title = 'Display DeprecationWarning, PendingDeprecationWarning and ImportWarning in debug mode'
updated_at = <Date 2017-11-20.17:48:41.610>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-20.17:48:41.610>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-20.17:48:41.611>
closer = 'lukasz.langa'
components = ['Library (Lib)']
creation = <Date 2017-11-20.14:26:42.890>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32088
keywords = ['patch']
message_count = 4.0
messages = ['306547', '306549', '306571', '306572']
nosy_count = 3.0
nosy_names = ['barry', 'vstinner', 'lukasz.langa']
pr_nums = ['4474']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32088'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Related python-dev thread:
https://mail.python.org/pipermail/python-dev/2017-November/150608.html
"[Python-Dev] Show DeprecationWarning in debug mode?"

I propose to display Display DeprecationWarning, PendingDeprecationWarning and ImportWarning when Python is compiled in debug mode.

Attached PR implements proposed change.

**Comment by vstinner** [comment]
Warnings filters in debug mode.

Reference (current code):

```sh
$ ./python -c 'import warnings, pprint; pprint.pprint(warnings.filters)'
[('ignore', None, <class 'DeprecationWarning'>, None, 0),
 ('ignore', None, <class 'PendingDeprecationWarning'>, None, 0),
 ('ignore', None, <class 'ImportWarning'>, None, 0),
 ('ignore', None, <class 'BytesWarning'>, None, 0),
 ('always', None, <class 'ResourceWarning'>, None, 0)]
```


With my [PR 4474](https://github.com/python/cpython/pull/4474):

```sh
$ ./python -c 'import warnings, pprint; pprint.pprint(warnings.filters)'
[('ignore', None, <class 'BytesWarning'>, None, 0),
 ('always', None, <class 'ResourceWarning'>, None, 0)]
```



BytesWarning is not modified by my PR since this specific warning is controlled by the -b option. Example with my PR.

-b option, ignore =\> default:

```sh
$ ./python -b -c 'import warnings, pprint; pprint.pprint(warnings.filters)'
[('default', None, <class 'BytesWarning'>, None, 0),
 ('always', None, <class 'ResourceWarning'>, None, 0)]
```


-bb option, ignore =\> error:

```sh
$ ./python -bb -c 'import warnings, pprint; pprint.pprint(warnings.filters)'
[('error', None, <class 'BytesWarning'>, None, 0),
 ('always', None, <class 'ResourceWarning'>, None, 0)]
```



Note: While writing this comment, I also found a bug in the new developer mode (-X dev): bpo-32089.

**Comment by ambv** [comment]
New changeset 895862aa01793a26e74512befb0c66a1da2587d6 by Łukasz Langa (Victor Stinner) in branch 'master':
bpo-32088: Display Deprecation in debug mode (bpo-4474)
https://github.com/python/cpython/commit/895862aa01793a26e74512befb0c66a1da2587d6

**Comment by ambv** [comment]
Merged. This is an important improvement to make sure 3.7's quality is the best possible.

Thanks! ✨ 🍰 ✨
