### ISSUE TITLE
sqlite3 Cursor.description can't return column types

### ISSUE THREAD

**Issue by c4e2ca0a-e71b-4361-a70d-163896c5caf5** [python/cpython#76264]
BPO | [32083](https://bugs.python.org/issue32083)
--- | :---
Nosy | @malemburg, @berkerpeksag, @ZackerySpytz, @kyoshidajp
Superseder | <li>bpo-11691: sqlite3 Cursor.description doesn&#x27;t set type_code</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-07-26.14:25:51.201>
created_at = <Date 2017-11-20.13:08:43.266>
labels = ['3.7', 'type-feature', 'library']
title = "sqlite3 Cursor.description can't return column types"
updated_at = <Date 2018-07-26.14:25:51.199>
user = 'https://github.com/kyoshidajp'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-26.14:25:51.199>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2018-07-26.14:25:51.201>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2017-11-20.13:08:43.266>
creator = 'kyoshidajp'
dependencies = []
files = []
hgrepos = []
issue_num = 32083
keywords = []
message_count = 4.0
messages = ['306539', '306541', '322421', '322432']
nosy_count = 5.0
nosy_names = ['lemburg', 'ghaering', 'berker.peksag', 'ZackerySpytz', 'kyoshidajp']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '11691'
type = 'enhancement'
url = 'https://bugs.python.org/issue32083'
versions = ['Python 3.7']
```

</p></details>

**Comment by c4e2ca0a-e71b-4361-a70d-163896c5caf5** [comment]
My schema of sqlite3 table is the following.

--- schema check start \---
% sqlite3 sample.db
SQLite version 3.16.0 2016-11-04 19:09:39
Enter ".help" for usage hints.
sqlite\> PRAGMA table_info(Employees);
0|EmployeeID|int|1||1
1|LastName|varchar(20)|1||0
2|FirstName|varchar(10)|1||0

(ommiting)

sqlite\>
--- schema check end \---

Then, I tried to output column types by calling Cursor.description. Like this.

--- sample code start \---
```py
import sqlite3

con = sqlite3.connect("sample.db", detect_types=sqlite3.PARSE_DECLTYPES)
cursor = con.cursor()
cursor.execute("select LastName, FirstName from Employees limit 1;")
print cursor.description
cursor.close()
con.close()
--- sample code end 
```
---

The output is the following.

(('LastName', None, None, None, None, None, None), ('FirstName', None, None, None, None, None, None))

When changing detect_types parameter to

```py
detect_types=sqlite3.PARSE_DECLTYPES|sqlite3.PARSE_COLNAMES
```


the result is same.

I expect to output a column type in second element. Could you tell me why?

**Comment by berkerpeksag** [comment]
Thank you for your report. According to https://github.com/python/cpython/blob/04dee2720851ec39e831beaa3edc0c59f228f461/Modules/_sqlite/cursor.c#L573 we always set the 'type_code' field described in PEP-249 to None. Setting it would be a new feature so it can only go into Python 3.7.
