### ISSUE TITLE
_args_from_interpreter_flags() doesn't keep -X options

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76275]
BPO | [32094](https://bugs.python.org/issue32094)
--- | :---
Nosy | @warsaw, @pitrou, @vstinner, @applio
PRs | <li>python/cpython#4480</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-21.00:43:12.855>
created_at = <Date 2017-11-20.18:18:46.670>
labels = ['3.7', 'type-feature', 'library']
title = "_args_from_interpreter_flags() doesn't keep -X options"
updated_at = <Date 2017-11-21.00:43:12.854>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-21.00:43:12.854>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-21.00:43:12.855>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-11-20.18:18:46.670>
creator = 'pitrou'
dependencies = []
files = []
hgrepos = []
issue_num = 32094
keywords = ['patch']
message_count = 3.0
messages = ['306574', '306597', '306604']
nosy_count = 4.0
nosy_names = ['barry', 'pitrou', 'vstinner', 'davin']
pr_nums = ['4480']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32094'
versions = ['Python 3.7']
```

</p></details>

**Comment by pitrou** [comment]
`subprocess._args_from_interpreter_flags()` is used to control the flags passed to child Python processes, for example launched by multiprocessing.  Unfortunately, not all flags are actually recognized by this function:

```pycon
$ ./python -X dev
Python 3.7.0a2+ (heads/master:895862a, Nov 20 2017, 19:15:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys._xoptions
{'dev': True}
>>> import subprocess
>>> subprocess._args_from_interpreter_flags()
['-Wdefault']
```

**Comment by vstinner** [comment]
New changeset f39b674876d2bd47ec7fc106d673b60ff24092ca by Victor Stinner in branch 'master':
bpo-32094: Update subprocess for -X dev (bpo-4480)
https://github.com/python/cpython/commit/f39b674876d2bd47ec7fc106d673b60ff24092ca

**Comment by vstinner** [comment]
Thanks for the bug report Antoine, it's now fixed!
