### ISSUE TITLE
Add "capture_output=True" option to subprocess.run

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#76283]
BPO | [32102](https://bugs.python.org/issue32102)
--- | :---
Nosy | @warsaw, @gpshead, @ncoghlan, @bbayles
PRs | <li>python/cpython#5149</li><li>python/cpython#8374</li><li>python/cpython#8720</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = <Date 2018-01-30.06:43:14.741>
created_at = <Date 2017-11-21.06:13:46.996>
labels = ['type-feature']
title = 'Add "capture_output=True" option to subprocess.run'
updated_at = <Date 2018-08-09.22:02:59.493>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-09.22:02:59.493>
actor = 'miss-islington'
assignee = 'gregory.p.smith'
closed = True
closed_date = <Date 2018-01-30.06:43:14.741>
closer = 'gregory.p.smith'
components = []
creation = <Date 2017-11-21.06:13:46.996>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 32102
keywords = ['patch']
message_count = 4.0
messages = ['306627', '306643', '311243', '311244']
nosy_count = 4.0
nosy_names = ['barry', 'gregory.p.smith', 'ncoghlan', 'bbayles']
pr_nums = ['5149', '8374', '8720']
priority = 'normal'
resolution = 'fixed'
stage = 'commit review'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32102'
versions = []
```

</p></details>

**Comment by ncoghlan** [comment]
I'm hesitant to suggest adding yet-another-option to any subprocess API, but I'm thinking it may be worth it in this case.

The idea is to make it possible to replace:

```py
    result = subprocess.run(cmd, stdout=PIPE, stderr=PIPE)
```


with:

```py
    result = subprocess.run(cmd, capture_output=True)
```


That way, it would be possible for the raw stdin/stdout/stderr parameters to be treated as low level implementation details most of the time, since the most common configurations would be:

```py
    # Use parent's stdin/stdout/stderr
    result = subprocess.run(cmd) 
    # Use pipe for stdin, use parent's stdout/stderr
    result = subprocess.run(cmd, input=data)
    # Use parent's stdin, use pipe for stdout/stderr
    result = subprocess.run(cmd, capture_output=True) 
    # Use pipe for stdin/stdout/stderr
    result = subprocess.run(cmd, input=data, capture_output=True)
```

**Comment by warsaw** [comment]
Yeah, I find it pretty common to set both stdout and stderr to PIPE, but I'm with you in hesitating to add YAO to the subprocess API.  If you do move forward with this though, I think capture_output would have to be mutually exclusive to stdout and stderr.  You should not be allowed to provide either of the latter two if the former is given.
