### ISSUE TITLE
Please add asyncio.BaseEventLoop.connect_accepted_socket Version Added to documentation

### ISSUE THREAD

**Issue by 95192ef8-8ee9-40af-82a6-719e92b5cfd7** [python/cpython#76286]
BPO | [32105](https://bugs.python.org/issue32105)
--- | :---
Nosy | @1st1, @AraHaan
PRs | <li>python/cpython#4491</li><li>python/cpython#4493</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-21.16:16:54.249>
created_at = <Date 2017-11-21.15:25:13.581>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Please add asyncio.BaseEventLoop.connect_accepted_socket Version Added to documentation'
updated_at = <Date 2017-11-21.16:16:54.248>
user = 'https://bugs.python.org/ThomasEldonAllred'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-21.16:16:54.248>
actor = 'yselivanov'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-21.16:16:54.249>
closer = 'yselivanov'
components = ['Documentation']
creation = <Date 2017-11-21.15:25:13.581>
creator = 'Thomas Eldon Allred'
dependencies = []
files = []
hgrepos = []
issue_num = 32105
keywords = ['patch']
message_count = 4.0
messages = ['306650', '306653', '306663', '306665']
nosy_count = 4.0
nosy_names = ['docs@python', 'yselivanov', 'Decorater', 'Thomas Eldon Allred']
pr_nums = ['4491', '4493']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32105'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 95192ef8-8ee9-40af-82a6-719e92b5cfd7** [comment]
asyncio.BaseEventLoop.connect_accepted_socket was added in v3.5.3 Please add a note to the documentation.

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
Will see whhat I can do.

**Comment by 1st1** [comment]
New changeset 431665bf1971e66c51f59abf0693f700ff7919e8 by Yury Selivanov (AraHaan) in branch 'master':
bpo-32105: add asyncio.BaseEventLoop.connect_accepted_socket versionadded to documentation. (bpo-4491)
https://github.com/python/cpython/commit/431665bf1971e66c51f59abf0693f700ff7919e8

**Comment by 1st1** [comment]
New changeset d7ed48c2b8c11bb99da3661e8fe0bf5ae7f6b8d7 by Yury Selivanov (Miss Islington (bot)) in branch '3.6':
bpo-32105: add asyncio.BaseEventLoop.connect_accepted_socket versionadded to documentation. (GH-4491) (bpo-4493)
https://github.com/python/cpython/commit/d7ed48c2b8c11bb99da3661e8fe0bf5ae7f6b8d7
