### ISSUE TITLE
Add PYTHONDEVMODE=1 to enable the developer mode

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76282]
BPO | [32101](https://bugs.python.org/issue32101)
--- | :---
Nosy | @ncoghlan, @pitrou, @vstinner
PRs | <li>python/cpython#4478</li><li>python/cpython#4624</li><li>python/cpython#4821</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-30.10:49:45.114>
created_at = <Date 2017-11-21.02:58:57.806>
labels = ['type-feature', '3.7']
title = 'Add PYTHONDEVMODE=1 to enable the developer mode'
updated_at = <Date 2017-12-12.22:15:02.111>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-12.22:15:02.111>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-30.10:49:45.114>
closer = 'vstinner'
components = []
creation = <Date 2017-11-21.02:58:57.806>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32101
keywords = ['patch']
message_count = 6.0
messages = ['306618', '306625', '307195', '307284', '307286', '308162']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'pitrou', 'vstinner']
pr_nums = ['4478', '4624', '4821']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32101'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
In the review of the [PR 4478](https://github.com/python/cpython/pull/4478), Antoine Pitrou proposed to add an environment variable to enable the new Python "developer mode" to inherit the developer mode in child Python processes.

I proposed to add PYTHONDEVMODE=1. Nick Coghlan proposed PYTHONXOPTIONS=dev.

While -X is a new "catch all" for new CPython options, Python got new PYTHONxxx environment variables to enable new options:

* -X faulthandler: PYTHONFAULTHANDLER=1
* -X tracemalloc=N: PYTHONTRACEMALLOC=n
* -X importtime: PYTHONPROFILEIMPORTTIME=1 -- note that the names are different in this case, I don't know why

I have a preference for PYTHONDEVMODE=1.

If we start to use PYTHONXOPTIONS, users may want to use PYTHONXOPTIONS=tracemalloc, and then we have to decide which environment variable has the preference :-(

Moreover, tracemalloc takes an argument, whereas environment variables with a value containing '=' are rare and so likely to cause issues in programs not carefully written to handle such variables. (Environment variables are inherited by all processes, not only Python processes.)

**Comment by ncoghlan** [comment]
Another argument against PYTHONXOPTIONS is that each implementation is free to decide which -X options it wants to support, and we don't really define what they're supposed to do with options they don't recognise.

By contrast, there's an established behaviour for unknown environment variables: implementations that don't support them just ignore them.

So +1 for PYTHONDEVMODE=1 from me - that also gives us more flexibility if we decide to add arguments to the option later.

**Comment by vstinner** [comment]
While implementing a new PYTHONDEVMODE environment variable, I found that it would help to also add a new sys.flags.dev_mode flag. So I added it.

So for example, asyncio uses sys.flags.dev_mode rather than checking for 'dev' in sys.\_xoptions \*and* check if the environment variable is set or not.

**Comment by vstinner** [comment]
New changeset 5e3806f8cfd84722fc55d4299dc018ad9b0f8401 by Victor Stinner in branch 'master':
bpo-32101: Add PYTHONDEVMODE environment variable (bpo-4624)
https://github.com/python/cpython/commit/5e3806f8cfd84722fc55d4299dc018ad9b0f8401

**Comment by vstinner** [comment]
Thanks Antoine and Nick for reviews and the feedback!
