### ISSUE TITLE
add method throw() to asyncio.Task

### ISSUE THREAD

**Issue by 7992ac84-56d2-4255-88ec-109d9c0b8f39** [python/cpython#76285]
BPO | [32104](https://bugs.python.org/issue32104)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-29.19:15:03.640>
created_at = <Date 2017-11-21.14:44:12.633>
labels = ['type-feature', 'expert-asyncio']
title = 'add method throw() to asyncio.Task'
updated_at = <Date 2018-05-29.19:15:03.639>
user = 'https://bugs.python.org/OlegK2'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.19:15:03.639>
actor = 'yselivanov'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-29.19:15:03.640>
closer = 'yselivanov'
components = ['asyncio']
creation = <Date 2017-11-21.14:44:12.633>
creator = 'Oleg K2'
dependencies = []
files = []
hgrepos = []
issue_num = 32104
keywords = []
message_count = 5.0
messages = ['306644', '306647', '307287', '308232', '318071']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'Oleg K2']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32104'
versions = ['Python 3.6']
```

</p></details>

**Comment by 7992ac84-56d2-4255-88ec-109d9c0b8f39** [comment]
currently there is no other way to interrupt task but to call
cancel() which will: 

"This arranges for a CancelledError to be thrown into the wrapped coroutine on the next cycle through the event loop."

in order to write advanced Tasks there should be a way
to throw custom exceptions into active Task. 
so it can react accordingly.  

i am looking for the same thing as "generator.throw()" is providing,
allowing to interrupt generators different way.

**Comment by 1st1** [comment]
> in order to write advanced Tasks there should be a way
> to throw custom exceptions into active Task. 
> so it can react accordingly.  

What is an "advanced" task?  Why CancelledError is not enough?  What's the actual use case?

**Comment by 7992ac84-56d2-4255-88ec-109d9c0b8f39** [comment]
What is an "advanced" task?  
Why CancelledError is not enough?  
What's the actual use case?
\----------------------

for instance, i want to create a task which is responsible for 
controlling a "slow resource" that should accessed carefully not to DOS it,  
that could be an long running api call,
or report generation procedure, or slow sqlite query.

that task may be interrupted when program needs to respond quickly 
for example UI is requesting another action with that slow resource, 
that should happen asap. 

if i could throw custom exception, that task would  suspend or interrupt 
current action, then execute something new and urgent, and then continue
where it left of. 
\-----------------------------------------------------

also there is another case i have in mind, 

there is a task which monitors video stream with different means to see if that stream is alive an fine, it uses external calls to ffmpeg to check how the stream is doing,  -  that monitoring procedure is continuous always running task, 

sometimes there is a network problem or one of CDN servers go down,
when that event is happening i need to throw custom exception to that
 "monitoring task" no matter at which stage it is at.  

when that task will get custom exception it will not exit but will switch to different operation mode, it should not exit because the monitoring is continuous process ,
it just hast to interpret its measurements differently, and use different ways to measure video state.


\---

I hope i made clear examples, lmk if you need more details.
thanks!
