### ISSUE TITLE
IDLE: PathBrowser isn't working

### ISSUE THREAD

**Issue by csabella** [python/cpython#76281]
BPO | [32100](https://bugs.python.org/issue32100)
--- | :---
Nosy | @terryjreedy, @csabella
PRs | <li>python/cpython#4484</li><li>python/cpython#4512</li><li>python/cpython#4626</li><li>python/cpython#4629</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-11-23.01:09:23.780>
created_at = <Date 2017-11-21.01:14:15.686>
labels = ['expert-IDLE', 'type-bug', '3.7']
title = "IDLE: PathBrowser isn't working"
updated_at = <Date 2017-11-29.03:15:09.074>
user = 'https://github.com/csabella'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.03:15:09.074>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-11-23.01:09:23.780>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-11-21.01:14:15.686>
creator = 'cheryl.sabella'
dependencies = []
files = []
hgrepos = []
issue_num = 32100
keywords = ['patch']
message_count = 10.0
messages = ['306606', '306667', '306676', '306692', '306757', '306765', '306776', '306777', '307200', '307204']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'cheryl.sabella']
pr_nums = ['4484', '4512', '4626', '4629']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32100'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by csabella** [comment]
Clicking on Path Browser in the File menu gives an error instead of opening the Path Browser.

**Comment by terryjreedy** [comment]
```pycon
Error is printed in console window if IDLE started from one.
>>> import idlelib.idle
# Select pathbrowser in File menu
Exception in Tkinter callback
Traceback (most recent call last):
  File "F:\dev\3x\lib\tkinter\__init__.py", line 1699, in __call__
    return self.func(*args)
  File "F:\dev\3x\lib\idlelib\editor.py", line 671, in open_path_browser
    pathbrowser.PathBrowser(self.flist)
  File "F:\dev\3x\lib\idlelib\pathbrowser.py", line 18, in __init__
    self.init(flist)
TypeError: init() takes 1 positional argument but 2 were given
```

**Comment by terryjreedy** [comment]
The issue is this:
1. PathBrowser subclasses ModuleBrowser.
2. ModuleBrowser.init() has the common code for initializing both.
3. bpo-31460 changed the signature of ModuleBrowser.\_\_init__ \*and* .init.
4. I must not have tested pathbrowser after the .init change.  Bad.
5. test_pathbrowser needs a new gui test class that at least calls PathBrowser.\_\_init__, which will call ModuleBrowser.init

3.6.3 is OK, 3.7.0a2 has this bug.  3.7.0a3 is due 11/27.  Patch should be merged before this with or without new unittests.
\---

Module items can be expanded either by clicking [+] or double-clicking.  The latter also opens the file so that lines can be highlighted.  I have thought about disabling both, and opening a module browser instead, but I can see the usefulness of expanding several files one level deep to get an overview of parts or all of a package.  On the other hand, we might have double-click open both the module and a module browser.

**Comment by csabella** [comment]
I added a test for PathBrowser, but I didn't change the existing tests, except to move them to their own test class.

**Comment by terryjreedy** [comment]
The reason double-clicking got worse from 3.6.3 to now is this.  Previously, browser.ModuleBrowserTreeItem.OnDoubleClick ignored the file_open global (set to pyshell.flist.open in .\_\_init__) and called pyshell.flist.open.  The Class and Method OnDoubleClick called file_open.  So double-clicking a file name in pathbrowser opened the file, but expanding a file and double-clicking a class or function name raised "'NoneType' object is not callable".  I don't know if I ever tried the latter before.  We subsequently changed the Module DoubleClick to also use file_open, so double clicking a file name also raises. (I meant to submit this yesterday.)

**Comment by terryjreedy** [comment]
New changeset 20d48a44a54ed5e4a6df00e89ae27e3983128265 by Terry Jan Reedy (Cheryl Sabella) in branch 'master':
bpo-32100: IDLE: Fix pathbrowser errors; improve tests. (bpo-4484)
https://github.com/python/cpython/commit/20d48a44a54ed5e4a6df00e89ae27e3983128265

**Comment by terryjreedy** [comment]
New changeset ae3c5c7b9e5e5ba53213e12cc100e32415d5762c by Terry Jan Reedy in branch '3.6':
[3.6] bpo-32100: IDLE: Fix pathbrowser errors; improve tests. (GH-4484) (bpo-4512)
https://github.com/python/cpython/commit/ae3c5c7b9e5e5ba53213e12cc100e32415d5762c

**Comment by terryjreedy** [comment]
Thanks for catching and fixing this.

**Comment by terryjreedy** [comment]
New changeset fd6f8c56b9a757210e8ceaea9edc50e502dc2085 by Terry Jan Reedy in branch 'master':
bpo-32100: Delete unneeded import in idlelib.pathbrowser. (bpo-4626)
https://github.com/python/cpython/commit/fd6f8c56b9a757210e8ceaea9edc50e502dc2085

**Comment by terryjreedy** [comment]
New changeset 38ecf57306ef25874ef7c44a9875771e90faee97 by Terry Jan Reedy (Miss Islington (bot)) in branch '3.6':
bpo-32100: Delete unneeded import in idlelib.pathbrowser. (GH-4626) (bpo-4629)
https://github.com/python/cpython/commit/38ecf57306ef25874ef7c44a9875771e90faee97
