### ISSUE TITLE
Move sysmodule.c to Modules?

### ISSUE THREAD

**Issue by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [python/cpython#76287]
BPO | [32106](https://bugs.python.org/issue32106)
--- | :---
Nosy | @serhiy-storchaka, @AraHaan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-21.21:21:14.248>
created_at = <Date 2017-11-21.17:04:45.883>
labels = ['interpreter-core', '3.8', '3.7', 'library']
title = 'Move sysmodule.c to Modules?'
updated_at = <Date 2017-11-21.21:21:14.246>
user = 'https://github.com/AraHaan'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-21.21:21:14.246>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-21.21:21:14.248>
closer = 'serhiy.storchaka'
components = ['Interpreter Core', 'Library (Lib)']
creation = <Date 2017-11-21.17:04:45.883>
creator = 'Decorater'
dependencies = []
files = []
hgrepos = []
issue_num = 32106
keywords = []
message_count = 2.0
messages = ['306671', '306690']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Decorater']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32106'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by a28bdafa-f08b-4d5c-a058-5f14648d68ee** [comment]
After looking in the folder Python sysmodule.c is in there instead of in Modules. I am wondering if it has any reason to be in that folder instead of in Modules/* with the other builtin modules in python.

If not I think it is best to move it so that way it is easier to find for those who think sysmodule is in the Modules folder because it is an builtin module.

**Comment by serhiy-storchaka** [comment]
The builtins and sys modules are special as they are directly initialized at interpreter startup. They are parts of the interpreter core and this is why they are in the Python directory.
