### ISSUE TITLE
Improve MAC address calculation and fix test_uuid.py

### ISSUE THREAD

**Issue by warsaw** [python/cpython#76288]
BPO | [32107](https://bugs.python.org/issue32107)
--- | :---
Nosy | @warsaw, @vstinner, @ned-deily, @xdegaye, @serhiy-storchaka
PRs | <li>python/cpython#4494</li><li>python/cpython#4572</li><li>python/cpython#4576</li><li>python/cpython#4590</li><li>python/cpython#4591</li><li>python/cpython#4593</li><li>python/cpython#4600</li><li>python/cpython#4677</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/warsaw'
closed_at = <Date 2018-02-03.14:47:11.961>
created_at = <Date 2017-11-21.17:10:23.121>
labels = ['3.7', 'type-bug', 'tests']
title = 'Improve MAC address calculation and fix test_uuid.py'
updated_at = <Date 2018-02-03.14:47:11.960>
user = 'https://github.com/warsaw'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-03.14:47:11.960>
actor = 'barry'
assignee = 'barry'
closed = True
closed_date = <Date 2018-02-03.14:47:11.961>
closer = 'barry'
components = ['Tests']
creation = <Date 2017-11-21.17:10:23.121>
creator = 'barry'
dependencies = []
files = []
hgrepos = []
issue_num = 32107
keywords = ['patch']
message_count = 44.0
messages = ['306672', '306674', '306678', '306684', '306685', '306686', '306706', '306830', '306854', '306855', '307009', '307010', '307014', '307015', '307016', '307018', '307028', '307036', '307064', '307076', '307077', '307079', '307080', '307081', '307084', '307088', '307100', '307101', '307103', '307104', '307181', '307236', '307237', '307425', '307428', '307431', '307447', '307448', '307499', '307500', '307503', '307509', '307545', '311557']
nosy_count = 5.0
nosy_names = ['barry', 'vstinner', 'ned.deily', 'xdegaye', 'serhiy.storchaka']
pr_nums = ['4494', '4572', '4576', '4590', '4591', '4593', '4600', '4677']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32107'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by warsaw** [comment]
The check_node() function in test_uuid.py uses the wrong bitmask, causing the tests to fail on valid MAC addresses.  Also, the description in the comment is incorrect.  From my reading of the wikipedia page, the test is trying to ensure that the MAC address is "universally administered", which is designated by a zero value in "the second least significant digit of the first octet".

Thus the bitmask value \*and* the comment are both wrong AFAICT, given that the original value is:

% ./python.exe -c "from math import log2; print(log2(0x010000000000))"
40.0

I have a fix that passes on my machine, so I'll PR that and see if it passes on CI.

**Comment by serhiy-storchaka** [comment]
I'm just wondering why tests were passing successfully before.

**Comment by warsaw** [comment]
Pure chance I believe.  It all depends on the MAC address of the machines the test runs on (which is perhaps an unacceptable environmental variability in the test suite, and should be fixed/mocked?).

FWIW, I saw the failures on my 2017 MacBook Pro, where the MAC address did have that bit set on two of its interfaces.

**Comment by warsaw** [comment]
Yikes.  It's entirely possible that these tests are tainted by environmental leakage.  I was looking into why Travis fails on my PR:

https://travis-ci.org/python/cpython/jobs/305433725

and stepping through \_ifconfig_getnode() on my Mac.  The "ibridge" interface is getting returned, which has a MAC address of:

```pycon
>>> from uuid import _ifconfig_getnode
>>> mac = _ifconfig_getnode()
>>> hex(mac)
'0xacde48001122'
```


That's for the en5 interface, which according to this article is the bridge to the Touch Bar, and \*the same on every Mac*.

https://discussions.apple.com/thread/7763102?start=0&tstart=0

Why I think that's problematic for this particular test is that whatever gets returned is going to be highly dependent on the hardware the test is run on, and it's entirely possible that the MAC address returned is indeed locally administered and not tied to a physical external (and thus required to be universally administered) MAC address.

Mocking \_ifconfig_*() probably isn't a good idea because these tests are worthless that way.  But it's also true that the \_ifconfig_*() methods can match unexpected interfaces which cause the test to fail incorrectly.  It's a mess, and I'm not sure what to do about it.

**Comment by serhiy-storchaka** [comment]
If your fix is correct (and it looks correct to me), we should fix not only the test, but, first of all, the \_*\_getnode functions. Perhaps they should ignore locally administered MAC addresses and continue searching better variants or fall back to other method.

**Comment by warsaw** [comment]
On Nov 21, 2017, at 15:47, Serhiy Storchaka \<report@bugs.python.org\> wrote:

> If your fix is correct (and it looks correct to me), we should fix not only the test, but, first of all, the \_*\_getnode functions. Perhaps they should ignore locally administered MAC addresses and continue searching better variants or fall back to other method.

I think it does make sense to ignore locally administered MACs from \_getnode() and friends.  E.g. there’s no use in returning the interface for the Touch Bar bridge :)

I don’t have time right now to elaborate on that, but I’ll work on improving the PR with that change.

**Comment by vstinner** [comment]
> https://travis-ci.org/python/cpython/jobs/305433725

AssertionError: 2199023255552 is not false : 0242ac110051
AssertionError: 2199023255552 is not false : 0242ac110051

So the Travis CI MAC address is 02:42:ac:11:00:51.

**Comment by serhiy-storchaka** [comment]
Wait, now I understand the purpose of the current test! There is just a typo in a comment, should be 41 instead of 47. The test itself is correct. If the address is obtained from network cards, it should have the 41 bit clear. If it is generated randomly, it should have the 41 bit set, to avoid conflicts with addresses obtained from network cards. There is nothing about the 42 bit.

**Comment by warsaw** [comment]
On Nov 23, 2017, at 11:24, Serhiy Storchaka \<report@bugs.python.org\> wrote:

> Wait, now I understand the purpose of the current test! There is just a typo in a comment, should be 41 instead of 47. The test itself is correct. If the address is obtained from network cards, it should have the 41 bit clear. If it is generated randomly, it should have the 41 bit set, to avoid conflicts with addresses obtained from network cards. There is nothing about the 42 bit.

It’s not just a typo in the comment, it’s a typo in the bitmask, at least if the intent of the test is to ensure that the MAC address is universally administered.  That is defined as having a 0 in the “second least significant bit of the first octet”.  Here’s a way to make that clearer.

```pycon
# Second least significant bit of the first octet of the 48-bit MAC address
>>> 0b00000010_00000000_00000000_00000000_00000000_00000000
2199023255552
# Constant from the PR
>>> 1<<41
2199023255552
# Literal bit mask from the original code.
>>> 0x010000000000
1099511627776
```


The latter is off by 1 place.

**Comment by serhiy-storchaka** [comment]
I'm sorry, but this tests and the typo were added by me in bpo-23015. This check is a pair of the check for \_random_getnode(). They use the same mask and test the same bit. I forgot about this.

**Comment by serhiy-storchaka** [comment]
If I understand correctly, the original problem was that tests failed in some environments, right? In that case we should either change the environment or just remove this check. I had added it in assumption that it is never failed for addresses obtained from network cards. If my assumption is wrong, it should be just removed.

**Comment by warsaw** [comment]
On Nov 26, 2017, at 12:40, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> 
> Serhiy Storchaka \<storchaka+cpython@gmail.com\> added the comment:
> 
> If I understand correctly, the original problem was that tests failed in some environments, right? In that case we should either change the environment or just remove this check. I had added it in assumption that it is never failed for addresses obtained from network cards. If my assumption is wrong, it should be just removed.

I think your assumption is generally true in that \*real* network cards (i.e. ethernet ports or wireless adapters) will always have universally administered MAC addresses.  But what you probably didn’t expect is that certain environments can also have locally administered MAC addresses (e.g. MBP’s Touch Bar interfaces - that one surprised me too!) and some may \*only* have local MACs (e.g. Travis).

We can fix the first assumption by preferentially returning universal MACs, and only return local MACs if there are no other interfaces available.  My latest changes do this.  (Remember, I only started seeing the failures on my 2017 MBP with Touch Bar.)

I can’t think of any way of solving the second one, short of just skipping those tests on Travis.  I think any reasonable machine with real interfaces will have at least one universal MAC, so it’s just Travis being weird.  My latest commit adds a skip for Travis.  (That test is still running, so we’ll see.)

The original problem really was that the test for universal vs. local MAC address was using the incorrect bitmask.  The comment was also wrong, so my changes fix both the comment and the bitmask.

Another problem I found was that the UUID1 spec says that if a random MAC is used as a fallback, then the multicast bit must be set, so my changes also do this.

For now, I’d prefer to take the narrower approach of enabling the tests everywhere but Travis.  What I don’t know is whether any of the buildbots will fail in a similar way, but I’m hoping they’ll be okay.  If we see buildbot failures because they also lack universal MACs, then yes, we’ll have to reevaluate whether the tests make sense, or whether we should mock out the environment at a lower level.

**Comment by serhiy-storchaka** [comment]
Universally/locally administered MAC addresses doesn't have relation to this issue. My assumption was about the multicast bit (1\<\<40).

If my assumption was correct, the test is correct, and only the comment should be fixed. If it was wrong, the test should be removed. That's all.

**Comment by warsaw** [comment]
On Nov 26, 2017, at 14:07, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> 
> Universally/locally administered MAC addresses doesn't have relation to this issue. My assumption was about the multicast bit (1\<\<40).

AFAICT, the multicast bit is only required to be set on random MAC.

> If my assumption was correct, the test is correct, and only the comment should be fixed. If it was wrong, the test should be removed. That's all.

I don’t understand.  Are you saying that \_find_mac() should return whatever random MAC is found first, as the original code does?  That doesn’t seem right either, since as the MacBook Pro case shows, it’s entirely possible to get a MAC address that is the same on every single laptop.

**Comment by serhiy-storchaka** [comment]
This is a different issue.

**Comment by serhiy-storchaka** [comment]
[PR 4572](https://github.com/python/cpython/pull/4572) removes the wrong check.

**Comment by warsaw** [comment]
PR bpo-4576 includes all related changes.

**Comment by serhiy-storchaka** [comment]
Currently [PR 4576](https://github.com/python/cpython/pull/4576) combines a bug fix and a new feature.

1. Removes wrong check and adds a verbose clarifying comment. This part should be backported to maintained versions.

2. Adds multiple explicit "return None". This is a minor improvement the quality of the code. Too minor for separate PR.

3. Makes methods for getting the address of the real network card preferring universally administered addresses and falling back to locally  administered address only if universally administered addresses are not found. This is a new feature. But are there computers that have both universally and locally administered addresses (and with locally administered addresses enumerated first)?

**Comment by warsaw** [comment]
On Nov 27, 2017, at 01:24, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> 
> 3. Makes methods for getting the address of the real network card preferring universally administered addresses and falling back to locally  administered address only if universally administered addresses are not found. This is a new feature. But are there computers that have both universally and locally administered addresses (and with locally administered addresses enumerated first)?

There are certainly computers that have both universal and local admin MAC addresses, as proven by the MBP+TouchBar case that triggered this.  I don’t know whether we can assume anything about the order in which those are enumerated.

**Comment by warsaw** [comment]
New changeset 9522a218f7dff95c490ff359cc60e8c2af35f5c8 by Barry Warsaw in branch 'master':
bpo-32107 - Better merge of bpo-4494 (bpo-4576)
https://github.com/python/cpython/commit/9522a218f7dff95c490ff359cc60e8c2af35f5c8

**Comment by serhiy-storchaka** [comment]
My apologies for my dim comment and my obliviousness that leaded to spending your time on trying to fix a wrong issue.

Do you mind to fix the original issue (by removing the wrong check) in maintenance branches?

**Comment by warsaw** [comment]
On Nov 27, 2017, at 15:18, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> 
> My apologies for my dim comment and my obliviousness that leaded to spending your time on trying to fix a wrong issue.

No worries at all.  Thanks for working with me to make the fix as good as it can be.

> Do you mind to fix the original issue (by removing the wrong check) in maintenance branches?

I don’t mind, but interestingly enough, test_uuid does not fail for me locally in either the 2.7 or 3.6 branches!  I don’t know what’s different, since I’m running them on exactly the same machine, but that does seem to be the case.

Still, I think it makes sense to backport the change in check, without backporting the feature change or code cleanups, so I’ll work on branches for those.

**Comment by serhiy-storchaka** [comment]
We shouldn't check the 42nd bit in maintenance releases. This check will fail on some computers.

**Comment by warsaw** [comment]
On Nov 27, 2017, at 16:08, Serhiy Storchaka \<report@bugs.python.org\> wrote:
> 
> We shouldn't check the 42nd bit in maintenance releases. This check will fail on some computers.

Oh, without the preferential return of the universally administered MAC, you’re right.  So we should just remove the check for the 41st bit and not add the check for the 42nd bit.

**Comment by ned-deily** [comment]
The latest checkin seems to have broken several buildbots:

 http://buildbot.python.org/all/#builders/47/builds/243
 http://buildbot.python.org/all/#builders/88/builds/248
 http://buildbot.python.org/all/#builders/13/builds/255
 http://buildbot.python.org/all/#builders/16/builds/252

**Comment by warsaw** [comment]
On Nov 27, 2017, at 16:21, Ned Deily \<report@bugs.python.org\> wrote:
> 
> The latest checkin seems to have broken several buildbots:
> 
> http://buildbot.python.org/all/#builders/47/builds/243
> http://buildbot.python.org/all/#builders/88/builds/248
> http://buildbot.python.org/all/#builders/13/builds/255
> http://buildbot.python.org/all/#builders/16/builds/252

Those are all locally administered MAC addresses.  Does that mean some of the buildbot machines also have no universally administered MAC address, like Travis?  Or is something wrong with our logic?

If it’s the former, then it might just make better sense to remove the 42nd bit test in all cases.

**Comment by vstinner** [comment]
http://buildbot.python.org/all/#/builders/16/builds/252

\======================================================================
FAIL: test_ifconfig_getnode (test.test_uuid.TestInternalsWithoutExtModule)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/test/test_uuid.py", line 538, in test_ifconfig_getnode
    self.check_node(node, 'ifconfig')
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/test/test_uuid.py", line 531, in check_node
    self.assertFalse(node & (1 << 41), '%012x' % node)
AssertionError: 2199023255552 is not false : 020000000030
```

======================================================================
FAIL: test_ip_getnode (test.test_uuid.TestInternalsWithoutExtModule)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/test/test_uuid.py", line 543, in test_ip_getnode
    self.check_node(node, 'ip')
  File "/home/dje/cpython-buildarea/3.x.edelsohn-sles-z/build/Lib/test/test_uuid.py", line 531, in check_node
    self.assertFalse(node & (1 << 41), '%012x' % node)
AssertionError: 2199023255552 is not false : 020000000030
```

**Comment by vstinner** [comment]
New changeset c9409f7c4533f75b11a4c44e839d95a1403f8a0a by Victor Stinner in branch 'master':
Revert "bpo-32107 - Better merge of bpo-4494 (bpo-4576)" (bpo-4593)
https://github.com/python/cpython/commit/c9409f7c4533f75b11a4c44e839d95a1403f8a0a

**Comment by vstinner** [comment]
The commit 9522a218f7dff95c490ff359cc60e8c2af35f5c8 broke multiple buildbots. Since I don't how to fix it, I reverted it, to get more time to design, implement and test a proper fix.

**Comment by warsaw** [comment]
On Nov 27, 2017, at 18:38, STINNER Victor \<report@bugs.python.org\> wrote:
> 
> STINNER Victor \<victor.stinner@gmail.com\> added the comment:
> 
> The commit 9522a218f7dff95c490ff359cc60e8c2af35f5c8 broke multiple buildbots. Since I don't how to fix it, I reverted it, to get more time to design, implement and test a proper fix.

Thanks.  There was no way to predict the failures, but I thought that it could happen.  I think at this point the only proper fix is to remove the bitmask test.  I’ll work up a follow-on branch and port that back to 2.7 and 3.6.

**Comment by warsaw** [comment]
New changeset 23df2d1304ece169d7e0dfc843dfb8026b413d9f by Barry Warsaw in branch 'master':
bpo-32107 - Improve MAC address calculation and fix test_uuid.py (bpo-4600)
https://github.com/python/cpython/commit/23df2d1304ece169d7e0dfc843dfb8026b413d9f

**Comment by warsaw** [comment]
New changeset 56e444f8df34cd502d6e3b110c90aed086883a72 by Barry Warsaw in branch '2.7':
[2.7] bpo-32107 - Backport bitmask check fix (GH-4576) (bpo-4590)
https://github.com/python/cpython/commit/56e444f8df34cd502d6e3b110c90aed086883a72

**Comment by warsaw** [comment]
New changeset 23cc8c0f9ece32f1f96133b9db2cb30c64f23a0e by Barry Warsaw in branch '3.6':
[3.6] bpo-32107 - Backport bitmask check fix (GH-4576) (bpo-4591)
https://github.com/python/cpython/commit/23cc8c0f9ece32f1f96133b9db2cb30c64f23a0e
