### ISSUE TITLE
configparser bug: section is emptied if you assign a section to itself

### ISSUE THREAD

**Issue by 9f600957-a497-4910-a4e3-64c4ad08c950** [python/cpython#76289]
BPO | [32108](https://bugs.python.org/issue32108)
--- | :---
Nosy | @ambv, @serhiy-storchaka, @corona10
PRs | <li>python/cpython#4607</li><li>python/cpython#7588</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-17.01:34:39.553>
created_at = <Date 2017-11-21.17:46:10.957>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'configparser bug: section is emptied if you assign a section to itself'
updated_at = <Date 2019-02-17.01:34:39.553>
user = 'https://bugs.python.org/simonltwick'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-17.01:34:39.553>
actor = 'cheryl.sabella'
assignee = 'none'
closed = True
closed_date = <Date 2019-02-17.01:34:39.553>
closer = 'cheryl.sabella'
components = ['Library (Lib)']
creation = <Date 2017-11-21.17:46:10.957>
creator = 'simonltwick'
dependencies = []
files = []
hgrepos = []
issue_num = 32108
keywords = ['patch']
message_count = 5.0
messages = ['306675', '306682', '307131', '315425', '319400']
nosy_count = 4.0
nosy_names = ['lukasz.langa', 'serhiy.storchaka', 'simonltwick', 'corona10']
pr_nums = ['4607', '7588']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32108'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by 9f600957-a497-4910-a4e3-64c4ad08c950** [comment]
If you assign a ConfigParser section back to the parent ConfigParser object (say after updating the section), the section is emptied.

(I realise now that you don't need to assign the section back to the parent as it's a proxy for the section in the parent already - but still it does not behave as you would expect):
code: 
        from configparser import ConfigParser
        config = ConfigParser()
        config['test'] = {'key': 'value'}
        section = config['test']
        section['key'] = 'different'
        print("before: config['test'] is %s" % dict(config['test']))
        config['test'] = section
        print("after: config['test'] is %s" % dict(config['test']))
        \# the section is now printed as {}

**Comment by ambv** [comment]
Confirmed.

**Comment by serhiy-storchaka** [comment]
[PR 4607](https://github.com/python/cpython/pull/4607) doesn't look a correct solution to me. I don't know a precedence of calling deepcopy() for a value in \_\_setitem__(). deepcopy() is too heavy, calling it can slow down normal cases. Using deepcopy likely means a bad design.
