### ISSUE TITLE
Separated square brackets will generate a tuple instead of a list.

### ISSUE THREAD

**Issue by dd4ec7b6-8db5-4618-bd1f-366303296623** [python/cpython#76290]
BPO | [32109](https://bugs.python.org/issue32109)
--- | :---
Nosy | @bitdancer, @berkerpeksag, @csabella, @YCmove
PRs | <li>python/cpython#4498</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-22.07:09:18.665>
created_at = <Date 2017-11-22.06:46:32.124>
labels = ['3.8', 'type-feature', '3.7', 'invalid', 'docs']
title = 'Separated square brackets will generate a tuple instead of a list.'
updated_at = <Date 2017-11-23.02:10:39.480>
user = 'https://github.com/YCmove'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-23.02:10:39.480>
actor = 'YCmove'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-22.07:09:18.665>
closer = 'berker.peksag'
components = ['Documentation']
creation = <Date 2017-11-22.06:46:32.124>
creator = 'YCmove'
dependencies = []
files = []
hgrepos = ['374']
issue_num = 32109
keywords = ['patch']
message_count = 5.0
messages = ['306698', '306720', '306724', '306727', '306779']
nosy_count = 5.0
nosy_names = ['r.david.murray', 'docs@python', 'berker.peksag', 'cheryl.sabella', 'YCmove']
pr_nums = ['4498']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32109'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by berkerpeksag** [comment]
Thank you for your report and for the PR, but I think you misunderstood documentation:

    Using square brackets, separating items with commas: [a], [a, b, c]

The comma is used to show two different lists: a list with one item ``[a]`` *and* a list with three items ``[a, b, c]``, not a tuple with two lists ``[a], [a, b, c]`` (In Python, both ``(1,)`` and ``1,`` create a tuple)

**Comment by csabella** [comment]
Perhaps this is what the YCMove meant?

```pycon
>>> a = [1], [2, 3, 4]
>>> a
([1], [2, 3, 4])
>>>
```

**Comment by berkerpeksag** [comment]
That's why I mentioned ``[a], [a, b, c]`` in my earlier message.

**Comment by bitdancer** [comment]
Yes, the markup (and therefore how the code is displayed in the docs) clearly indicates that the , between the lists is not part of the python syntax being discussed.

**Comment by dd4ec7b6-8db5-4618-bd1f-366303296623** [comment]
Yes, what Cheryl Sabella says is what I was misled to. 

Took me a while to understand that ``[a]``, ``[a, b, c]`` is not ``[a], [a, b, c]``, how about replace comma to "or" for more clarity? just like it used in [tuple documention](https://github.com/python/cpython/blob/master/Doc/library/stdtypes.rst#tuples)

Here is my rephrased version, and I add one more example of comma separated lists in tuple according to R. David Murray.
