### ISSUE TITLE
CSV import and export simplified

### ISSUE THREAD

**Issue by 28ff66e0-8967-46ad-9ba7-9f3a0e425ecd** [python/cpython#76297]
BPO | [32116](https://bugs.python.org/issue32116)
--- | :---
Nosy | @rhettinger, @bitdancer, @paullongnet
PRs | <li>python/cpython#4450</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.22:33:00.783>
created_at = <Date 2017-11-22.18:36:31.437>
labels = ['type-feature', 'library']
title = 'CSV import and export simplified'
updated_at = <Date 2017-11-24.22:33:00.766>
user = 'https://github.com/paullongnet'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-24.22:33:00.766>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-24.22:33:00.783>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2017-11-22.18:36:31.437>
creator = 'paullongnet'
dependencies = []
files = []
hgrepos = []
issue_num = 32116
keywords = ['patch']
message_count = 6.0
messages = ['306746', '306747', '306748', '306749', '306752', '306927']
nosy_count = 3.0
nosy_names = ['rhettinger', 'r.david.murray', 'paullongnet']
pr_nums = ['4450']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32116'
versions = []
```

</p></details>

**Comment by 28ff66e0-8967-46ad-9ba7-9f3a0e425ecd** [comment]
It would be helpful if the CSV module included standard functions that simplify the import of CSV files to a list and the export of CSV files to a list.  Here's an example of what they could be:

```py
def csv2list(file_name): 
    list_name=[] 
    with open(file_name) as csvfile:
        readerfile = reader(csvfile)
        for row in readerfile:
            list_name.append(row)
    return list_name

def list2csv(list_name,file_name):
    with open(file_name, 'w', newline='') as csvfile:
        writerfile = csv.writer(csvfile)
        writerfile.writerows(list_name)
```

**Comment by bitdancer** [comment]
Thanks for the suggestion, but I'm -0.5.  I don't think these are compelling enough to be worth adding to the module API.  The number of times I've done this kind of operation is far smaller than the number of times I've had other code in both the input and output loops.  \*Far* smaller.

**Comment by 28ff66e0-8967-46ad-9ba7-9f3a0e425ecd** [comment]
I should have added that there are thousands of 15 year old students completing GCSE Computer Science who would benefit massively from this.  All the exam boards in England require students to be able to read from and write to CSV files.  The complicated way of doing it in Python is making this quite inaccessible to most students and so although many programmers in general wouldn't need this very often, there are literally thousands of students who would benefit from this enhancement.

**Comment by bitdancer** [comment]
Um.  If they aren't expected to understand how to write this code, why isn't it being provided to them as a canned function as part of the test environment?

To succeed in getting something like this added, I suspect you will need to show that it has more general utility, or there is something analogous that can be added that has more general utility.  I recommend starting a discussion on the python-ideas mailing list.

By the way, if I needed this in my code, I'd write:

```py
  with open(file_name, newline="") as csvfile:
      my_list = list(csv.reader(csvfile))

  with open(file_name, 'w', newline="") as csvfile:
      csv.writer(csvfile).writerows(my_list)
```


Only if I needed it more than once would I bother wrapping it in a function.

**Comment by 28ff66e0-8967-46ad-9ba7-9f3a0e425ecd** [comment]
Thanks for your advice.  The reason it's not provided as a canned function is because different schools can use different programming languages, although the vast majority choose to use Python.

**Comment by rhettinger** [comment]
I'm also -1 on this feature request.  The open and closing of files is orthogonal to what you do with an open file.  Likewise, iterators are orthogonal to how they are consumed (for-loops, list(), set(), etc).

FWIW, csv.Reader object is an iterator that can be fed directly to list():

```py
    result = list(csv.reader(fileobj)
```
