### ISSUE TITLE
ObjectListView crashes on python3.5

### ISSUE THREAD

**Issue by 52e38762-bf79-4b30-b693-2818f811ee1e** [python/cpython#76292]
BPO | [32111](https://bugs.python.org/issue32111)
--- | :---
Nosy | @ronaldoussoren, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-22.10:08:04.067>
created_at = <Date 2017-11-22.09:46:06.291>
labels = ['extension-modules', 'type-crash']
title = 'ObjectListView crashes on python3.5'
updated_at = <Date 2017-11-22.10:08:04.066>
user = 'https://bugs.python.org/BalakrishnanUnnithan'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-22.10:08:04.066>
actor = 'christian.heimes'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-22.10:08:04.067>
closer = 'christian.heimes'
components = ['Extension Modules']
creation = <Date 2017-11-22.09:46:06.291>
creator = 'Balakrishnan Unnithan'
dependencies = []
files = []
hgrepos = []
issue_num = 32111
keywords = []
message_count = 4.0
messages = ['306709', '306711', '306713', '306714']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'serhiy.storchaka', 'Balakrishnan Unnithan']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue32111'
versions = ['Python 3.5']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Could you provide more information Balakrishnan?

**Comment by 52e38762-bf79-4b30-b693-2818f811ee1e** [comment]
Issue:
On Python3.5, ObjectListView object crashes when double-clicked in cell to edit int type.
\-------------------------------------
```pytb
Traceback (most recent call last):
  File "C:\DevEnv\Python35\lib\site-packages\ObjectListView\ObjectListView.py", line 1726, in _HandleLeftClickOrDoubleClick
    self._PossibleStartCellEdit(rowIndex, subItemIndex)
  File "C:\DevEnv\Python35\lib\site-packages\ObjectListView\ObjectListView.py", line 2048, in _PossibleStartCellEdit
    self.StartCellEdit(rowIndex, subItemIndex)
  File "C:\DevEnv\Python35\lib\site-packages\ObjectListView\ObjectListView.py", line 2114, in StartCellEdit
    self.cellEditor.SetValue(evt.cellValue)
  File "C:\DevEnv\Python35\lib\site-packages\ObjectListView\CellEditor.py", line 268, in SetValue
    if isinstance(value, (long, int, float)):
NameError: name 'long' is not defined
```

-------------------------------------
On debugging, I found that the actual root-cause of this bug lies in below code:
File: ..lib\\site-packages\\ObjectListView\\CellEditor.py
Line: 100
\-------------------------------------
```py
    def __init__(self):
        self.typeToFunctionMap = {}
```


        # Standard types and their creator functions
        self.typeToFunctionMap[str] = self._MakeStringEditor
        self.typeToFunctionMap[six.text_type] = self._MakeStringEditor
        self.typeToFunctionMap[bool] = self._MakeBoolEditor

```py
        if six.PY2:
            self.typeToFunctionMap[int] = self._MakeIntegerEditor
            self.typeToFunctionMap[long] = self._MakeLongEditor
        else:
#Line:100   
            self.typeToFunctionMap[int] = self._MakeLongEditor
```


        self.typeToFunctionMap[float] = self._MakeFloatEditor
        self.typeToFunctionMap[datetime.datetime] = self._MakeDateTimeEditor
        self.typeToFunctionMap[datetime.date] = self._MakeDateEditor
        self.typeToFunctionMap[datetime.time] = self._MakeTimeEditor
\-------------------------------------
Modified code:
\-------------------------------------
```py
        if six.PY2:
            self.typeToFunctionMap[int] = self._MakeIntegerEditor
            self.typeToFunctionMap[long] = self._MakeLongEditor
        else:
#Line:100 
            self.typeToFunctionMap[int] = self._MakeIntegerEditor
```

-------------------------------------
In place of integer type editor, long type editor is being created.
As Python3.x does not support long type, the programme crashes here.

**Comment by ronaldoussoren** [comment]
This appears to be an issue with a 3th-party library (https://pypi.python.org/pypi/ObjectListView), not CPython itself.

The repository (and issue tracker) for that library is at \<https://bitbucket.org/wbruhin/objectlistview\>. 

@Balakrishnan: could you confirm that you are using this library? And if so, please file an issue with that project.

**Comment by 52e38762-bf79-4b30-b693-2818f811ee1e** [comment]
Yes, I am using this 3rd party library. Okay, I shall withdraw the issue from here.
I'm new to Python and hence do not know the various groups and their purpose.
Apologies!
Thanks for the support.

Version info:
ObjectListView 1.3.1
Python 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:07:06) [MSC v.1900 32 bit (Intel)] on win32
