### ISSUE TITLE
Tuple unpacking in return and yield statements

### ISSUE THREAD

**Issue by 4af79a99-be83-47d6-a266-517d2d6985cf** [python/cpython#76298]
BPO | [32117](https://bugs.python.org/issue32117)
--- | :---
Nosy | @gvanrossum, @serhiy-storchaka, @Cryvate, @dacut, @miss-islington, @jChapman
PRs | <li>python/cpython#4509</li><li>python/cpython#9487</li><li>python/cpython#9721</li><li>python/cpython#16994</li><li>python/cpython#19737</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-05.18:18:03.512>
created_at = <Date 2017-11-22.23:31:49.357>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'Tuple unpacking in return and yield statements'
updated_at = <Date 2020-05-05.14:50:03.820>
user = 'https://github.com/dacut'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-05.14:50:03.820>
actor = 'miss-islington'
assignee = 'none'
closed = True
closed_date = <Date 2018-10-05.18:18:03.512>
closer = 'serhiy.storchaka'
components = ['Interpreter Core']
creation = <Date 2017-11-22.23:31:49.357>
creator = 'dacut'
dependencies = []
files = []
hgrepos = []
issue_num = 32117
keywords = ['patch']
message_count = 17.0
messages = ['306761', '306783', '307257', '307264', '307266', '307267', '325327', '325421', '325459', '325460', '325461', '326063', '326064', '326122', '326823', '327160', '368161']
nosy_count = 7.0
nosy_names = ['gvanrossum', 'python-dev', 'serhiy.storchaka', 'cryvate', 'dacut', 'miss-islington', 'Jordan Chapman']
pr_nums = ['4509', '9487', '9721', '16994', '19737']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32117'
versions = ['Python 3.8']
```

</p></details>

**Comment by 4af79a99-be83-47d6-a266-517d2d6985cf** [comment]
This stems from a query on StackOverflow: https://stackoverflow.com/questions/47272460/python-tuple-unpacking-in-return-statement/

Specifically, the following syntax is allowed:
def f():
    rest = (4, 5, 6)
    t = 1, 2, 3, \*rest

While the following result in SyntaxError:
def g():
    rest = (4, 5, 6)
    return 1, 2, 3, \*rest

```py
def h():
    rest = (4, 5, 6)
    yield 1, 2, 3, *rest
```


Looking at the original commit that enabled tuple unpacking in assignment statements:
https://github.com/python/cpython/commit/4905e80c3d2f6abb613d212f0313d1dfe09475dc

I don't believe this difference is intentional.

My GitHub repo incorporates a fix for this; I'll file a pull request momentarily.

**Comment by serhiy-storchaka** [comment]
Since this changes the grammar, it should be first discussed on Python-Dev and approved by BDFL.

**Comment by 4af79a99-be83-47d6-a266-517d2d6985cf** [comment]
CLA processed, and BDFL has assented on python-dev. Serhiy, thoughts on next steps?

**Comment by 7c3b9f7a-e616-458a-973e-3db6fe83c3bc** [comment]
I think the language spec needs updating as well? In particular in

https://docs.python.org/3/reference/simple_stmts.html#the-return-statement

it seems expression_list should be replaced by starred_list.

**Comment by 4af79a99-be83-47d6-a266-517d2d6985cf** [comment]
Hm... that leaves the only production for expression_list as:
subscription ::= primary "[" expression_list "]"

And I'm not sure that this shouldn't also be replaced by starred_list. It's not accepted today, though:

In [6]: a[1,*(4, 5, 6)]
  File "\<ipython-input-6-ba56159162e9\>", line 1
    a[1,*(4, 5, 6)]
        ^
SyntaxError: invalid syntax

I will ask about this again on python-dev@

**Comment by 4af79a99-be83-47d6-a266-517d2d6985cf** [comment]
Oops, I wasn't looking broadly enough. This is also used in the augmented assignment statements syntax, e.g. a += 1, 2, 3
