### ISSUE TITLE
tutorial on dictionaries has error in example

### ISSUE THREAD

**Issue by 5469d27d-ca7a-4450-96c4-5c2c45dafd54** [python/cpython#76308]
BPO | [32127](https://bugs.python.org/issue32127)
--- | :---
Nosy | @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-24.19:25:53.680>
created_at = <Date 2017-11-24.19:14:29.532>
labels = ['invalid', 'docs']
title = 'tutorial on dictionaries has error in example'
updated_at = <Date 2017-11-25.01:42:56.088>
user = 'https://bugs.python.org/tberla'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-25.01:42:56.088>
actor = 'eric.smith'
assignee = 'docs@python'
closed = True
closed_date = <Date 2017-11-24.19:25:53.680>
closer = 'tberla'
components = ['Documentation']
creation = <Date 2017-11-24.19:14:29.532>
creator = 'tberla'
dependencies = []
files = []
hgrepos = []
issue_num = 32127
keywords = []
message_count = 4.0
messages = ['306913', '306914', '306915', '306932']
nosy_count = 3.0
nosy_names = ['eric.smith', 'docs@python', 'tberla']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32127'
versions = ['Python 3.6']
```

</p></details>

**Comment by 5469d27d-ca7a-4450-96c4-5c2c45dafd54** [comment]
in https://docs.python.org/3/tutorial/datastructures.html: 

\-----
5.5. Dictionaries
...
Here is a small example using a dictionary:

```pycon
>>>
>>> tel = {'jack': 4098, 'sape': 4139}
>>> tel['guido'] = 4127
>>> tel
{'sape': 4139, 'guido': 4127, 'jack': 4098}
```

-----

I think the order of dictionary elements shown after 'guido' is inserted is wrong.

The correct order is: 
{'jack': 4098, 'sape': 4139, 'guido': 4127}

**Comment by ericvsmith** [comment]
dict makes no guarantees on ordering, so I think the example is fine. There is no "correct" ordering.

**Comment by 5469d27d-ca7a-4450-96c4-5c2c45dafd54** [comment]
Thanks, Eric. (I'm new to Python.) Perhaps I should have paid closer attention to the description of the dictionary data structure -- 

"Performing list(d.keys()) on a dictionary returns a list of all the keys used in the dictionary, in arbitrary order"

-- rather than just jumping ahead to the code example. ;-)

**Comment by ericvsmith** [comment]
No problem. Welcome to Python!
