### ISSUE TITLE
android: test_faulthandler fails also on API 24

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76319]
BPO | [32138](https://bugs.python.org/issue32138)
--- | :---
Nosy | @vstinner, @xdegaye
PRs | <li>python/cpython#4604</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.10:45:17.160>
created_at = <Date 2017-11-26.09:58:59.003>
labels = ['3.7', 'type-bug', 'tests']
title = 'android: test_faulthandler fails also on API 24'
updated_at = <Date 2017-11-29.10:45:17.160>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.10:45:17.160>
actor = 'xdegaye'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.10:45:17.160>
closer = 'xdegaye'
components = ['Tests']
creation = <Date 2017-11-26.09:58:59.003>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 32138
keywords = ['patch']
message_count = 3.0
messages = ['306999', '307047', '307218']
nosy_count = 2.0
nosy_names = ['vstinner', 'xdegaye']
pr_nums = ['4604']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32138'
versions = ['Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
bpo-26934 skipped some tests of test_faulthandler on Android API \< 24 to fix the problem that python does not crash upon \_sigsegv(). But the same problem occurs on API 24 except randomly, you need to run test_faulthandler many times before reproducing it, see below few results in that case.

I propose to skip those tests whatever the value of the Android API level.
In that case the test.support.requires_android_level decorator is not used anymore and should be removed.


1 test failed:
  test_faulthandler

```pytb
    generic_x86_64:/data/local/tmp/python $ python -m test test_faulthandler
    Run tests sequentially
    0:00:00 [1/1] test_faulthandler
    test test_faulthandler failed -- Traceback (most recent call last):
      File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 265, in test_enable_file
        filename=filename)
      File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 114, in check_fatal_error
        self.check_error(code, line_number, fatal_error, **kw)
      File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 107, in check_error
        output, exitcode = self.get_output(code, filename=filename, fd=fd)
      File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 67, in get_output
        self.assertEqual(output, '')
    AssertionError: "sys:1: ResourceWarning: unclosed file <_[49 chars]c3'>" != ''
    - sys:1: ResourceWarning: unclosed file <_io.BufferedWriter name='/data/local/tmp/tmp17fv9xc3'>
    + 
```


======================================================================
FAIL: test_disable (test.test_faulthandler.FaultHandlerTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 307, in test_disable
    self.assertNotEqual(exitcode, 0)
AssertionError: 0 == 0
```


======================================================================
FAIL: test_gil_released (test.test_faulthandler.FaultHandlerTests)
\----------------------------------------------------------------------
```pytb
Traceback (most recent call last):
  File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 252, in test_gil_released
    'Segmentation fault')
  File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 114, in check_fatal_error
    self.check_error(code, line_number, fatal_error, **kw)
  File "/sdcard/org.python/lib/python3.7/test/test_faulthandler.py", line 110, in check_error
    self.assertNotEqual(exitcode, 0)
AssertionError: 0 == 0
```

**Comment by vstinner** [comment]
> I propose to skip those tests whatever the value of the Android API level.

Works for me.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset ef83806f5ec01f34f6cbf4ebb5752875b5961f7e by xdegaye in branch 'master':
bpo-32138: Skip on Android test_faulthandler tests that raise SIGSEGV (GH-4604)
https://github.com/python/cpython/commit/ef83806f5ec01f34f6cbf4ebb5752875b5961f7e
