### ISSUE TITLE
Android5

### ISSUE THREAD

**Issue by 52d588ef-4a07-48fe-ba05-096d05133265** [python/cpython#76313]
BPO | [32132](https://bugs.python.org/issue32132)
--- | :---
Nosy | @berkerpeksag, @Hola buenas tardes le envío los archivos
Files | <li>[18.7z](https://bugs.python.org/file47289/18.7z "Uploaded as application/octet-stream at 2017-11-25.13:31:46 by @Hola buenas tardes le envío los archivos")</li><li>[radio fftt.apk](https://bugs.python.org/file47290/radio%20fftt.apk "Uploaded as application/vnd.android.package-archive at 2017-11-25.13:33:21 by @Hola buenas tardes le envío los archivos")</li><li>[radio fftt.apk](https://bugs.python.org/file47291/radio%20fftt.apk "Uploaded as application/vnd.android.package-archive at 2017-11-25.13:34:46 by @Hola buenas tardes le envío los archivos")</li><li>[de.robv.android.xposed.installer_v33_36570c.apk](https://bugs.python.org/file47292/de.robv.android.xposed.installer_v33_36570c.apk "Uploaded as application/vnd.android.package-archive at 2017-11-25.13:38:28 by @Hola buenas tardes le envío los archivos")</li><li>[YouTube Max.apk](https://bugs.python.org/file47294/YouTube%20Max.apk "Uploaded as application/vnd.android.package-archive at 2017-11-25.13:39:57 by @Hola buenas tardes le envío los archivos")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-30.23:21:07.816>
created_at = <Date 2017-11-25.13:31:46.875>
labels = ['extension-modules', 'expert-installation', 'expert-IO', 'performance']
title = 'Android5'
updated_at = <Date 2017-11-30.23:21:07.815>
user = 'https://github.com/Holabuenastardesleenvolosarchivos'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-30.23:21:07.815>
actor = 'berker.peksag'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-30.23:21:07.816>
closer = 'berker.peksag'
components = ['Demos and Tools', 'Extension Modules', 'Installation', 'IO']
creation = <Date 2017-11-25.13:31:46.875>
creator = 'Tu madre'
dependencies = []
files = ['47289', '47290', '47291', '47292', '47294']
hgrepos = ['375']
issue_num = 32132
keywords = []
message_count = 1.0
messages = ['306957']
nosy_count = 2.0
nosy_names = ['berker.peksag', 'Tu madre']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue32132'
versions = ['Python 3.5']
```

</p></details>

**Comment by berkerpeksag** [comment]
Android is not yet a fully supported platform. It's not clear what are you reporting here. Could you give us more information?
