### ISSUE TITLE
Crash on OSX

### ISSUE THREAD

**Issue by 551eb2b2-1133-484a-bf6e-ec27f285b5ed** [python/cpython#76315]
BPO | [32134](https://bugs.python.org/issue32134)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily
Files | <li>[Idle363_crash_report.txt](https://bugs.python.org/file47297/Idle363_crash_report.txt "Uploaded as text/plain at 2017-11-25.18:39:34 by jonasfinke@aol.com"): crash report</li><li>[Screen Shot 2017-11-25 at 19.45.50.png](https://bugs.python.org/file47298/Screen%20Shot%202017-11-25%20at%2019.45.50.png "Uploaded as image/png at 2017-11-25.18:46:52 by jonasfinke@aol.com")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2017-11-25.21:14:20.757>
created_at = <Date 2017-11-25.18:39:44.486>
labels = ['OS-mac', 'expert-tkinter', 'type-crash']
title = 'Crash on OSX'
updated_at = <Date 2017-11-25.21:14:20.746>
user = 'https://bugs.python.org/jonasfinkeaolcom'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-25.21:14:20.746>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2017-11-25.21:14:20.757>
closer = 'terry.reedy'
components = ['macOS', 'Tkinter']
creation = <Date 2017-11-25.18:39:44.486>
creator = 'jonasfinke@aol.com'
dependencies = []
files = ['47297', '47298']
hgrepos = []
issue_num = 32134
keywords = []
message_count = 3.0
messages = ['306971', '306972', '306974']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'jonasfinke@aol.com']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue32134'
versions = ['Python 3.6']
```

</p></details>

**Comment by 551eb2b2-1133-484a-bf6e-ec27f285b5ed** [comment]
The Idle Editor or Idle Python Shell crashes if ` character is typed in. Character looks like an ` with underscore. 

How to repeat this problem:
1. In OSX open any .py file or the Idle Shell with Idle.
2. Switch to german keyboard layout
3. Type the letter by pressing shift and the  +=  button, left of the delete button. (Keyboard hardware layout is US)

I attached only the crash report of version 3.6.3. This issue happens also to all previous versions. I didn't checked with versions higher than 3.6.3.

Info from shell (not crashed yet):
Python 3.6.3 (v3.6.3:2c5fed86e0, Oct  3 2017, 00:32:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "copyright", "credits" or "license()" for more information.
>\>\>

**Comment by 551eb2b2-1133-484a-bf6e-ec27f285b5ed** [comment]
See screenshot from character:

without: ` and with underscore: `

(underscore is not shown as text in comment. See screen shot)

**Comment by terryjreedy** [comment]
This is a duplicate of previous reports.  The problem, visible in the crash report, is that you are using the buggy Apple installed tcl/tk 8.5.9 and missed the upgrade instructions on
https://www.python.org/download/mac/tcltk/

Ned, the web page implies that only 8.5.7 is 'not recommended' and lists 8.5.9 as an acceptible 'alternate'.  But empirically, by multiple reports like this, it leads to crashes.  Can we get that page updated?
