### ISSUE TITLE
IDLE app icon is blurry on macOS with Aqua Tk 8.6

### ISSUE THREAD

**Issue by e9681926-2aff-4240-a89b-e9210c2ce124** [python/cpython#76310]
BPO | [32129](https://bugs.python.org/issue32129)
--- | :---
Nosy | @terryjreedy, @taleinat, @benjaminp, @ned-deily, @serhiy-storchaka, @miss-islington
PRs | <li>python/cpython#12031</li><li>python/cpython#12034</li><li>python/cpython#12133</li>
Files | <li>[Screen Shot 2017-11-24 at 11.44.31 PM.png](https://bugs.python.org/file47288/Screen%20Shot%202017-11-24%20at%2011.44.31%20PM.png "Uploaded as image/png at 2017-11-25.04:49:35 by wordtech")</li><li>[pyshell.diff](https://bugs.python.org/file47293/pyshell.diff "Uploaded as text/plain at 2017-11-25.13:39:19 by wordtech")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = <Date 2019-03-02.01:13:19.261>
created_at = <Date 2017-11-25.04:49:36.218>
labels = ['3.8', 'expert-IDLE', 'type-bug', '3.7']
title = 'IDLE app icon is blurry on macOS with Aqua Tk 8.6'
updated_at = <Date 2019-03-02.19:12:15.104>
user = 'https://bugs.python.org/wordtech'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-02.19:12:15.104>
actor = 'benjamin.peterson'
assignee = 'terry.reedy'
closed = True
closed_date = <Date 2019-03-02.01:13:19.261>
closer = 'terry.reedy'
components = ['IDLE']
creation = <Date 2017-11-25.04:49:36.218>
creator = 'wordtech'
dependencies = []
files = ['47288', '47293']
hgrepos = []
issue_num = 32129
keywords = ['patch']
message_count = 15.0
messages = ['306941', '306948', '306955', '306956', '306968', '306969', '334408', '334412', '336517', '336547', '336964', '336966', '336967', '336978', '337018']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'taleinat', 'wordtech', 'benjamin.peterson', 'ned.deily', 'serhiy.storchaka', 'miss-islington']
pr_nums = ['12031', '12034', '12133']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32129'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by e9681926-2aff-4240-a89b-e9210c2ce124** [comment]
The trunk and 8.6.7 branch of Tk on macOS have recently implemented the wm_iconphoto command, which had not previously been supported on macOS. This means that versions of IDLE that link to this version of Tk will inherit the iconphoto behavior on Windows and X11, which results in a extremely blurry icon image in the Dock. It would probably be best to make this command conditional on macOS to just retain the standard app icon, or else add a sharper image.

**Comment by terryjreedy** [comment]
Here is the current code in idlelib.pyshell.main.

```py
    # set application icon
    icondir = os.path.join(os.path.dirname(__file__), 'Icons')
    if system() == 'Windows':
        iconfile = os.path.join(icondir, 'idle.ico')
        root.wm_iconbitmap(default=iconfile)
    else:
        ext = '.png' if TkVersion >= 8.6 else '.gif'
        iconfiles = [os.path.join(icondir, 'idle_%d%s' % (size, ext))
                     for size in (16, 32, 48)]
        icons = [PhotoImage(master=root, file=iconfile)
                 for iconfile in iconfiles]
        root.wm_iconphoto(True, *icons)
```


IDLE uses wm_iconbitmap on Windows and wm_iconphoto with PhotoImages from .gif or .png on everything else.  It appears that wm_iconphoto is already used on macOS with tk 8.5.

The uploaded PM.png looks like it might be idle16.png zoomed out at least 3x.  Anything that does that instead of using the much sharper 32 or 48 bit versions is, to me, buggy.  The bigger images stay much sharper even when zoomed.

**Comment by e9681926-2aff-4240-a89b-e9210c2ce124** [comment]
wm_iconphoto is a no-op on Tk 8.5 on MacOS; the C function returns true with no action. That's why this has not cropped up before.

As implemented, the command on macOS only takes the first image in the parameters to use; the Cocoa mechanism in use for displaying images as app icons does not pack multiple sizes in the image. This will be documented in the man page for the next release of Tk. That's why the image currently looks very bad, because, as you note, it's scaling up a 16px image. The 48px would look better, albeit a bit jagged. 

The attached patch proposes to simply bypass this call in Tk-Mac. The wm_iconphoto command is most useful for a) replacing a generic Windows or X11 icon with something more customized or b) displaying a change in application state. On Mac OS, option is already addressed by the bundled application icon that looks much more polished; most users will not be calling idle from the command line (where this call can make sense). Option b is not applicable in this context.

**Comment by e9681926-2aff-4240-a89b-e9210c2ce124** [comment]
Adding proposed patch.

**Comment by terryjreedy** [comment]
Ned, do you agree that simply changing 'else' to 'elif not macosx.isAquaTk()' is the best resolution?

Backporting such a change to 3.6 would be trivial; to 2.7, not.  Is there any need for the latter?

Kevin, thanks for the explanation.

**Comment by serhiy-storchaka** [comment]
If on OS X only first picture is taken, what if change the order of pictures?
