### ISSUE TITLE
heapq.heappop - documentation misleading or doesn't work

### ISSUE THREAD

**Issue by f2afac7d-5928-470a-913d-8456c46d5a80** [python/cpython#76323]
BPO | [32142](https://bugs.python.org/issue32142)
--- | :---
Nosy | @rhettinger, @ericvsmith, @bitdancer, @scooter4j

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2019-03-21.19:48:37.441>
created_at = <Date 2017-11-26.16:05:48.080>
labels = ['type-bug', 'docs']
title = "heapq.heappop - documentation misleading or doesn't work"
updated_at = <Date 2019-03-21.19:48:37.441>
user = 'https://github.com/scooter4j'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-21.19:48:37.441>
actor = 'cheryl.sabella'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2019-03-21.19:48:37.441>
closer = 'cheryl.sabella'
components = ['Documentation']
creation = <Date 2017-11-26.16:05:48.080>
creator = 'scooter4j'
dependencies = []
files = []
hgrepos = []
issue_num = 32142
keywords = []
message_count = 7.0
messages = ['307006', '307008', '307011', '307017', '307034', '307318', '320363']
nosy_count = 6.0
nosy_names = ['rhettinger', 'eric.smith', 'r.david.murray', 'docs@python', 'abcdef', 'scooter4j']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32142'
versions = ['Python 3.6']
```

</p></details>

**Comment by f2afac7d-5928-470a-913d-8456c46d5a80** [comment]
The documentation for heapq.heappop(heap) says:
"Pop and return the smallest item from the heap, maintaining the heap invariant. If the heap is empty, IndexError is raised. To access the smallest item without popping it, use heap[0]."

yet, in the following code, the resultant heap doesn't reflect the heap invariant:

```py
import heapq
li = [5, 7, 9, 1, 4, 3]
heapq.heapify(li)
#change a couple values in the heap
li[3] = 16
li[4] = 2
print (heapq.heappop(li))
print ("The heap after pop is : ",end="")
print (list(li))
```


This prints: The heap after pop is : [3, 4, 9, 16, 2]

The documentation implies to me that heapify would be called internally after heappop, but I may be misreading. Perhaps heappop could say that the heap invariant is maintained if the heap is properly sorted before the heappop invocation.

**Comment by ericvsmith** [comment]
The heap invariant is also required in order to even meet the documented behavior of returning the smallest item.

```pycon
>>> import heapq
>>> li = [5, 7, 9, 1, 4, 3]
>>> heapq.heapify(li)
>>> li
[1, 4, 3, 7, 5, 9]
>>> li[2] = 0
>>> heapq.heappop(li)
1
>>> li
[0, 4, 9, 7, 5]
>>>
```


I guess the argument could be made that docs say "from the heap", and by modifying the list yourself it's no longer a heap.

**Comment by 48d4de70-99f1-423a-ab17-65201f81ac54** [comment]
>  Perhaps heappop could say that the heap invariant is maintained if the heap is properly sorted before the heappop invocation.

Honestly I like this wording less. "Properly sorted" would suggest sorted in the sense of heap.sort() [as the docs refer to this earlier], but the array doesn't have to be sorted; it's enough if it's a heap. The function always maintains the invariant - this means that if the invariant is true as a precondition, it will be true as a postcondition. Maybe you have a different idea?

**Comment by ericvsmith** [comment]
By "sorted" I meant "sorted by the heap functions so as to maintain their invariants".

I don't have any suggestion for the actual specific language to use.

**Comment by f2afac7d-5928-470a-913d-8456c46d5a80** [comment]
Fair statement. "Properly sorted" was a poor choice. Seems that "if the
invariant is true as a precondition, it will be true as a postcondition" is
accurate and descriptive -  maybe with a caution that modifying the list
(heap) values by means other than the heapq functions are likely to render
the invariant false (the latter phrase being for somewhat newbies like me
who wouldn't realize this truth without having to learn it in the debugger).

**Comment by bitdancer** [comment]
I would suggested following the statement "To create a heap, use a list initialized to [], or you can transform a populated list into a heap via function heapify()." with "Any mutation of the list thereafter must maintain the heap invariant in order for the list to remain a heap."
