### ISSUE TITLE
os.statvfs lacks f_fsid

### ISSUE THREAD

**Issue by 0d0f5cc9-9f8a-40be-ae37-21a1029a9c02** [python/cpython#76324]
BPO | [32143](https://bugs.python.org/issue32143)
--- | :---
Nosy | @freddrake, @vadmium, @giuseppe
PRs | <li>python/cpython#4571</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-14.23:23:55.991>
created_at = <Date 2017-11-26.16:17:33.547>
labels = ['type-feature', 'library']
title = 'os.statvfs lacks f_fsid'
updated_at = <Date 2017-12-14.23:23:55.989>
user = 'https://github.com/giuseppe'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-14.23:23:55.989>
actor = 'fdrake'
assignee = 'none'
closed = True
closed_date = <Date 2017-12-14.23:23:55.991>
closer = 'fdrake'
components = ['Library (Lib)']
creation = <Date 2017-11-26.16:17:33.547>
creator = 'gscrivano'
dependencies = []
files = []
hgrepos = []
issue_num = 32143
keywords = ['patch']
message_count = 5.0
messages = ['307007', '307021', '308292', '308342', '308344']
nosy_count = 3.0
nosy_names = ['fdrake', 'martin.panter', 'gscrivano']
pr_nums = ['4571']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32143'
versions = []
```

</p></details>

**Comment by 0d0f5cc9-9f8a-40be-ae37-21a1029a9c02** [comment]
the os.statvfs() function doesn't return f_fsid.  The POSIX definition of statvfs() has f_fsid:

http://pubs.opengroup.org/onlinepubs/009604599/basedefs/sys/statvfs.h.html

**Comment by vadmium** [comment]
The doc string for the result object, and the main Python 2 documentation, both say that the result is a 10-tuple. So perhaps any new field should only be an attribute, and the tuple should stay the same size, to maintain compatibility. This was done in other cases, e.g. struct_time and stat_result.
