### ISSUE TITLE
android: locale is modified by test_strftime

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#76320]
BPO | [32139](https://bugs.python.org/issue32139)
--- | :---
Nosy | @vstinner, @xdegaye
PRs | <li>python/cpython#4569</li><li>python/cpython#4635</li><li>python/cpython#4636</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.15:31:36.249>
created_at = <Date 2017-11-26.10:44:43.349>
labels = ['3.7', 'type-bug', 'tests']
title = 'android: locale is modified by test_strftime'
updated_at = <Date 2017-11-29.15:31:36.248>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.15:31:36.248>
actor = 'xdegaye'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.15:31:36.249>
closer = 'xdegaye'
components = ['Tests']
creation = <Date 2017-11-26.10:44:43.349>
creator = 'xdegaye'
dependencies = []
files = []
hgrepos = []
issue_num = 32139
keywords = ['patch']
message_count = 6.0
messages = ['307000', '307217', '307229', '307232', '307234', '307235']
nosy_count = 2.0
nosy_names = ['vstinner', 'xdegaye']
pr_nums = ['4569', '4635', '4636']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32139'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Test results:
\------------
1 test altered the execution environment:
  test_strftime

    Warning -- locale was modified by test_strftime
      Before: [(6, 'C.UTF-8'), (3, 'C.UTF-8'), (0, 'C.UTF-8'), (5, 'C.UTF-8'), (4, 'C.UTF-8'), (1, 'C.UTF-8'), (2, 'C.UTF-8')]
      After:  [(6, 'C'), (3, 'C'), (0, 'C'), (5, 'C'), (4, 'C'), (1, 'C'), (2, 'C')] 
    test_strftime failed (env changed)


It seems that the tests indeed modify the environment. To understand the above results one must be aware that the implementation of setlocale() is broken on Android:

```pycon
generic_x86_64:/data/local/tmp/python $ python
Python 3.7.0a2+ (heads/bpo-30386:ebb493ac4e, Nov 25 2017, 18:58:20) 
[Clang 3.8.275480 ] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from locale import setlocale, LC_TIME, LC_ALL
>>> setlocale(LC_TIME)
'C.UTF-8'
>>> setlocale(LC_ALL)
'C.UTF-8'
>>> setlocale(LC_TIME, 'C')
'C'
>>> setlocale(LC_TIME)
'C'
>>> setlocale(LC_ALL)
'C'
>>> setlocale(LC_TIME, 'C.UTF-8')
'C.UTF-8'
>>> setlocale(LC_ALL)
'C.UTF-8'
```

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset cc55e78acab93a495c974b9a2ea71c8bb9cc2f5d by xdegaye in branch 'master':
bpo-32139: test_strftime does not anymore modify the locale (GH-4569)
https://github.com/python/cpython/commit/cc55e78acab93a495c974b9a2ea71c8bb9cc2f5d

**Comment by vstinner** [comment]
Python 3.6 and 2.7 are also affected and should be fixed. I requested automated backports.

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset b0df786258c99f98295b82ec62daea1f49912c33 by xdegaye (Miss Islington (bot)) in branch '3.6':
bpo-32139: test_strftime does not anymore modify the locale (GH-4569) (bpo-4635)
https://github.com/python/cpython/commit/b0df786258c99f98295b82ec62daea1f49912c33

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
New changeset bc19cf57a8f061bbb1961aa069ed54e8361023ae by xdegaye (Miss Islington (bot)) in branch '2.7':
bpo-32139: test_strftime does not anymore modify the locale (GH-4569) (bpo-4636)
https://github.com/python/cpython/commit/bc19cf57a8f061bbb1961aa069ed54e8361023ae

**Comment by 490c593f-f636-409f-bb35-6abeb38a4595** [comment]
Closing now.
Thanks Victor :-)
