### ISSUE TITLE
Python 2.7.14 has Tkinter with big  T letter.

### ISSUE THREAD

**Issue by 73f13fb2-f66f-44da-8848-823c43d36bf3** [python/cpython#76329]
BPO | [32148](https://bugs.python.org/issue32148)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[Tkinter.PNG](https://bugs.python.org/file47299/Tkinter.PNG "Uploaded as image/png at 2017-11-27.15:48:07 by HMahmood"): screen shoot of python command prompt</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-27.16:07:03.318>
created_at = <Date 2017-11-27.15:48:07.107>
labels = ['invalid', 'expert-tkinter']
title = 'Python 2.7.14 has Tkinter with big  T letter.'
updated_at = <Date 2017-11-27.16:07:03.298>
user = 'https://bugs.python.org/HMahmood'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-27.16:07:03.298>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-27.16:07:03.318>
closer = 'serhiy.storchaka'
components = ['Tkinter']
creation = <Date 2017-11-27.15:48:07.107>
creator = 'HMahmood'
dependencies = []
files = ['47299']
hgrepos = []
issue_num = 32148
keywords = []
message_count = 2.0
messages = ['307055', '307060']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'HMahmood']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32148'
versions = ['Python 2.7']
```

</p></details>

**Comment by 73f13fb2-f66f-44da-8848-823c43d36bf3** [comment]
Using python 2.7.14.
Importing Dialogs
Got problem in importing tkinter. In doccumentation of tkinter, it is stated the big letter  T in Tkinter is used only used in python 3 but. 
It is expected that it is possible to use tkinter with small letter T beccause I use python 2.7.14

**Comment by serhiy-storchaka** [comment]
In Python 2 you should import the Tkinter module, with the big letter T.
