### ISSUE TITLE
Fix flake8 warning F401: ... imported but unused

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76337]
BPO | [32156](https://bugs.python.org/issue32156)
--- | :---
Nosy | @terryjreedy, @vstinner, @serhiy-storchaka
PRs | <li>python/cpython#4614</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-29.21:52:08.484>
created_at = <Date 2017-11-28.15:07:16.018>
labels = ['3.7', 'library']
title = 'Fix flake8 warning F401: ... imported but unused'
updated_at = <Date 2018-05-29.21:52:08.483>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-29.21:52:08.483>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-29.21:52:08.484>
closer = 'vstinner'
components = ['Library (Lib)']
creation = <Date 2017-11-28.15:07:16.018>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32156
keywords = ['patch']
message_count = 4.0
messages = ['307126', '307141', '307205', '318106']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'vstinner', 'serhiy.storchaka']
pr_nums = ['4614']
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32156'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
Attached PR removes unused imports.

**Comment by serhiy-storchaka** [comment]
I suggest to split your patch on several PR for different domains, and let the domain experts review changes separately. IDLE changes look mostly harmless to me. But changes in distutils should be made with a large care.

**Comment by terryjreedy** [comment]
Idlelib deletions done.
pathbrowser, bpo-32100, [PR-4626](https://github.com/python/cpython/pull/4626)
configdialog, bpo-30781, [PR-4627](https://github.com/python/cpython/pull/4627)
