### ISSUE TITLE
Suppress (and other contextlib context managers) should work as decorators (where appropriate)

### ISSUE THREAD

**Issue by jaraco** [python/cpython#76339]
BPO | [32158](https://bugs.python.org/issue32158)
--- | :---
Nosy | @warsaw, @rhettinger, @jaraco, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-28.19:58:59.932>
created_at = <Date 2017-11-28.19:39:46.088>
labels = ['3.7', 'library']
title = 'Suppress (and other contextlib context managers) should work as decorators (where appropriate)'
updated_at = <Date 2018-02-09.19:33:23.299>
user = 'https://github.com/jaraco'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-09.19:33:23.299>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-28.19:58:59.932>
closer = 'jaraco'
components = ['Library (Lib)']
creation = <Date 2017-11-28.19:39:46.088>
creator = 'jaraco'
dependencies = []
files = []
hgrepos = []
issue_num = 32158
keywords = []
message_count = 5.0
messages = ['307155', '307157', '307158', '311899', '311903']
nosy_count = 4.0
nosy_names = ['barry', 'rhettinger', 'jaraco', 'r.david.murray']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32158'
versions = ['Python 3.7']
```

</p></details>

**Comment by jaraco** [comment]
The contextlib docs explain why a decorator is nice:

> It makes it clear that the cm applies to the whole function, rather than just a piece of it (and saving an indentation level is nice, too).

However, the built-in context managers that could readily supply this interface don't derive from DecoratorContext.

In jaraco.context, I [added decorator support by simply deriving from the two base classes](https://github.com/jaraco/jaraco.context/commit/5aa7b0bb222cff5009a2f0dc3ea49db9e7a6b71a#diff-efbedfbbcb7f61268cfeff04a32fa59d).

But it got me thinking - couldn't suppress (and possibly other) contextlib decorators support this usage out of the box?

If there's interest, I'll put together a patch with test.

**Comment by rhettinger** [comment]
> But it got me thinking - couldn't suppress (and possibly other)
> contextlib decorators support this usage out of the box?

They possibly could but probably shouldn't.   My experience is that giving them a dual role makes them more complicated and harder to understand.

For suppress() in particular, wrapping a whole function is likely an anti-pattern.  Usually we advise people to put as little as possible in the try-block to avoid catching unexpected exceptions.

Also, I think it would be inevitable that people would try to apply these to generators or awaitables and find that they don't mix well.

**Comment by jaraco** [comment]
Fair enough.

For an example, here's the case where I wanted to use the decorator to avoid excess indentation and keep the most meaningful part of the function at the base of the body:

```py
@suppress(KeyError)
def v12_to_13(manager, case):
    case['sample_id'] = case.pop('caseid')
```



In my opinion, it's nominally nicer and clearer than:

```py
def v12_to_13(manager, case):
    with suppress(KeyError):
        case['sample_id'] = case.pop('caseid')
```



But I see your points about encouraging overly-broad catching of exceptions... so it's better to have the indentation as something of a wart to dissuade excess wrapping.
