### ISSUE TITLE
Remove explicit quotes around %r and {!r}

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76338]
BPO | [32157](https://bugs.python.org/issue32157)
--- | :---
Nosy | @warsaw, @pitrou, @bitdancer, @ethanfurman, @serhiy-storchaka, @applio
PRs | <li>python/cpython#4582</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-28.21:23:06.094>
created_at = <Date 2017-11-28.17:17:54.294>
labels = ['3.7', 'library']
title = 'Remove explicit quotes around %r and {!r}'
updated_at = <Date 2017-11-28.21:23:06.094>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-28.21:23:06.094>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-28.21:23:06.094>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2017-11-28.17:17:54.294>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 32157
keywords = ['patch']
message_count = 5.0
messages = ['307146', '307150', '307151', '307152', '307167']
nosy_count = 6.0
nosy_names = ['barry', 'pitrou', 'r.david.murray', 'ethan.furman', 'serhiy.storchaka', 'davin']
pr_nums = ['4582']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32157'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It is common to use quotes around %s. If the formatted argument is a string this will produce a string in qoutes, that look as a string literal in Python and other programming languages or just as a quoted string in English. But if quotes surround %r this looks like error. If the argument is a string this will lead to doubling qoutes. If its repr is in the form \<...\>, the angular parenthesis serve a role of qoutes, and additional qoutes are not needed.

[PR 4582](https://github.com/python/cpython/pull/4582) removes qoutes around %r and {!r} in format strings.

**Comment by pitrou** [comment]
Ethan, I think you misunderstood Serhiy's proposal.

**Comment by ethanfurman** [comment]
Yup, I sure did.  :/

Looks like a good change to me.  Are these the only instances of quotes used with %r?

**Comment by serhiy-storchaka** [comment]
Yes, these are the only instances of quotes used with %r or {!r}.

**Comment by serhiy-storchaka** [comment]
New changeset a4a3020abc065d40f57069d6c69d02222ddc85d6 by Serhiy Storchaka in branch 'master':
bpo-32157: Removed explicit quotes around %r and {!r}. (bpo-4582)
https://github.com/python/cpython/commit/a4a3020abc065d40f57069d6c69d02222ddc85d6
