### ISSUE TITLE
asyncio: Don't export selectors and _overlapped in asyncio namespace

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76335]
BPO | [32154](https://bugs.python.org/issue32154)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#4605</li><li>python/cpython#4609</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-28.20:33:43.869>
created_at = <Date 2017-11-28.10:29:10.076>
labels = ['3.7', 'expert-asyncio']
title = "asyncio: Don't export selectors and _overlapped in asyncio namespace"
updated_at = <Date 2017-11-28.20:33:43.868>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-28.20:33:43.868>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-28.20:33:43.869>
closer = 'vstinner'
components = ['asyncio']
creation = <Date 2017-11-28.10:29:10.076>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32154
keywords = ['patch']
message_count = 6.0
messages = ['307117', '307121', '307122', '307129', '307130', '307160']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['4605', '4609']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32154'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
For backward compatibility with Python 3.3, [Lib/asyncio/__init__.py](https://github.com/python/cpython/blob/main/Lib/asyncio/__init__.py) exports asyncio.selectors and asyncio.\_overlapped symbols. Python 3.3 reached it's end of line last september, it's time to move on:
https://devguide.python.org/#status-of-python-branches

This change is backward incompatible.

Attached PR removes asyncio.selectors and asyncio.\_overlapped symbols, and use directly modules from the standard library. It documents the change in the "Porting to Python 3.7" section of the "What's New in Python 3.7" document.

**Comment by vstinner** [comment]
New changeset 4271dfd7815c05fd39b515c240050b3585bdfcd4 by Victor Stinner in branch 'master':
bpo-32154: Remove asyncio.selectors (bpo-4605)
https://github.com/python/cpython/commit/4271dfd7815c05fd39b515c240050b3585bdfcd4

**Comment by vstinner** [comment]
I also proposed the [PR 4609](https://github.com/python/cpython/pull/4609) to remove the old asyncio.windows_utils.socketpair alias.

**Comment by serhiy-storchaka** [comment]
Is this function publicly documented? If this is true, it should first be deprecated.

It is left in the \_\_all__ list.

**Comment by vstinner** [comment]
Serhiy Storchaka: "Is this function publicly documented? If this is true, it should first be deprecated."

It's not documented, but I found a reference in the documentation:
\---
try:
    from socket import socketpair
except ImportError:
    from asyncio.windows_utils import socketpair
\---

This code continues to work on Python 3.5 and newer, the "except" block will just never be taken.


> It is left in the \_\_all__ list.

Oops, fixed in my PR.

**Comment by vstinner** [comment]
New changeset ac577d7d0bd27a69921ced14c09172235ceebab5 by Victor Stinner in branch 'master':
bpo-32154: Remove asyncio.windows_utils.socketpair (bpo-4609)
https://github.com/python/cpython/commit/ac577d7d0bd27a69921ced14c09172235ceebab5
