### ISSUE TITLE
-mvenv vs minor python version updates

### ISSUE THREAD

**Issue by 999fe78c-da4d-4246-8cb4-dd41c09fe83f** [python/cpython#76332]
BPO | [32151](https://bugs.python.org/issue32151)
--- | :---
Nosy | @ronaldoussoren, @uranusjr

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-01.15:07:16.446>
created_at = <Date 2017-11-27.17:46:19.308>
labels = ['interpreter-core', 'library', 'type-bug', 'expert-installation', 'invalid']
title = '-mvenv vs minor python version updates'
updated_at = <Date 2017-12-01.15:07:16.445>
user = 'https://bugs.python.org/RicAnderson'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-01.15:07:16.445>
actor = 'ronaldoussoren'
assignee = 'none'
closed = True
closed_date = <Date 2017-12-01.15:07:16.446>
closer = 'ronaldoussoren'
components = ['Installation', 'Interpreter Core', 'Library (Lib)']
creation = <Date 2017-11-27.17:46:19.308>
creator = 'Ric Anderson'
dependencies = []
files = []
hgrepos = []
issue_num = 32151
keywords = []
message_count = 7.0
messages = ['307072', '307233', '307326', '307358', '307371', '307387', '307390']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'uranusjr', 'Ric Anderson']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32151'
versions = ['Python 3.5', 'Python 3.6']
```

</p></details>

**Comment by 999fe78c-da4d-4246-8cb4-dd41c09fe83f** [comment]
When a site updates python3 from 3.5 to 3.6 (based on https://docs.python.org/3/faq/general.html#how-does-the-python-version-numbering-scheme-work, this is would be a minor version update),pre-upgrade venv setups created with "python3 -menv ..." break because "python3" in the venv is really 3.5, and needs the system libpython3.5m.so.1.0, which is no longer in the library search list.

Should "python -mvenv ..." copy the libpython3.5m.so.1.0 to the venv directory/lib, or add the system path to libpython3.5m.so.1.0 to LD_LIBRARY_PATH, or should the minor version number (.5 ,or .6) be excluded from the library name, so that minor version updates don't break existing venv setups or ???

**Comment by ronaldoussoren** [comment]
This is the expected behavior, the upgrade from 3.5 to 3.6 is a feature update that is (in general) not expected to be binary compatible with the previous release.

**Comment by 999fe78c-da4d-4246-8cb4-dd41c09fe83f** [comment]
Okay, are virtual env's expected to not be compatible as well?  

E.g., I built a venv under 3.5; venv copied in the 3.5 python executable, but not the needed library; should not -mvenv also copy libpython3.5 into the virutal setup or at least include the LD_LIBRARY_PATH to libpython3.5 in bin/activate, so that myenv/bin/python3.5 can find its needed library?

**Comment by ddf74a51-5f28-44b3-89e3-5080a0864212** [comment]
Not sure if it’s the same thing, but I want to plug in that this can happen when you do a micro upgrade (e.g. 3.5.1 → 3.5.2) as well. This is because micro updates sometimes bump versions of dependencies (e.g. OpenSSL, Tk), and that breaks theirs links in the venv. Should this also be expected?
