### ISSUE TITLE
Remove tools for CVS and Subversion

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76340]
BPO | [32159](https://bugs.python.org/issue32159)
--- | :---
Nosy | @brettcannon, @vstinner, @ned-deily, @ezio-melotti, @bitdancer, @serhiy-storchaka
PRs | <li>python/cpython#4615</li><li>python/cpython#4639</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.18:33:15.300>
created_at = <Date 2017-11-28.20:22:20.747>
labels = ['build', '3.7']
title = 'Remove tools for CVS and Subversion'
updated_at = <Date 2017-11-29.18:33:15.299>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-29.18:33:15.299>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.18:33:15.300>
closer = 'serhiy.storchaka'
components = ['Build']
creation = <Date 2017-11-28.20:22:20.747>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32159
keywords = ['patch']
message_count = 19.0
messages = ['307159', '307169', '307170', '307171', '307172', '307173', '307174', '307175', '307178', '307183', '307228', '307242', '307244', '307247', '307248', '307249', '307250', '307251', '307252']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'vstinner', 'ned.deily', 'ezio.melotti', 'r.david.murray', 'serhiy.storchaka']
pr_nums = ['4615', '4639']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32159'
versions = ['Python 3.7']
```

</p></details>

**Comment by vstinner** [comment]
CPython migrated from CVS to Subversion, to Mercurial, and then to Git. CVS and Subversion are no more used to develop CPython.

Changes of attached PR:

* platform module: drop support for sys.subversion. The
  sys.subversion attribute has been removed in Python 3.3.
* Remove [Misc/svnmap.txt](https://github.com/python/cpython/blob/main/Misc/svnmap.txt)
* Remove [Tools/scripts/svneol.py](https://github.com/python/cpython/blob/main/Tools/scripts/svneol.py)
* Remove [Tools/scripts/treesync.py](https://github.com/python/cpython/blob/main/Tools/scripts/treesync.py)

**Comment by vstinner** [comment]
New changeset fe2d5babba5d26de2093b6518316b268488187be by Victor Stinner in branch 'master':
bpo-32159: Remove tools for CVS and Subversion (bpo-4615)
https://github.com/python/cpython/commit/fe2d5babba5d26de2093b6518316b268488187be

**Comment by serhiy-storchaka** [comment]
Are you sure that these scripts are not used outside of CPython? They were here when CPython used Subversion, they were here when CPython used Mercurial, what is wrong with Git?

The support of the svn:eol property is a thing I really lacked in Mercurial.

**Comment by serhiy-storchaka** [comment]
Oh, you are VERY fast in committing Victor. Please restore these scripts.

**Comment by vstinner** [comment]
> Are you sure that these scripts are not used outside of CPython?

How would someone use it? There are only part of the code base, they are not installed on the system (by "make install").

If someone uses these scripts on another project which is not CPython, well, they can copy an old version from Python 3.6 and maintain their fork, no?

Why would Python still maintain a tool if we don't use it or test it ourself?


> The support of the svn:eol property is a thing I really lacked in Mercurial.

We are using .gitattributes to specify the end of lines of some files. A few examples:
\---
\*.gif binary
\*.bat text eol=crlf
[PC/readme.txt](https://github.com/python/cpython/blob/main/PC/readme.txt) text eol=crlf
\---

I understand that Git does handle end of line, and it's configurable by .gitattributes. Sorry, I don't know much more about that, and I'm not sure that this issue is the right place to ask questions about Git ;-) Maybe ask on python-dev if you are aware of an issue with Git?


> They were here when CPython used Subversion, they were here when CPython used Mercurial, what is wrong with Git?

The scripts are very specific to CVS and Subversion. They are useful with Mercurial or Git.

I wrote that we already changed the SCM twice since Subversion, to justify that I don't think that anyone still works on a CVS or Subversion fork of CPython.

Well, if someone really does that, I don't expect that they work on the master branch, and so likely have a copy of these scripts :-)


> Oh, you are VERY fast in committing Victor.

The PR was approved by Brett Cannon and Ned Deily.

**Comment by vstinner** [comment]
> The PR was approved by Brett Cannon and Ned Deily.

Oh, and Mariatta after I added a NEWS entry.

**Comment by serhiy-storchaka** [comment]
Is svnmap.txt used for mapping Subversion references to Mercurial references on the tracker? r88752

**Comment by vstinner** [comment]
Serhiy: "Is svnmap.txt used for mapping Subversion references to Mercurial references on the tracker? r88752"

Brett, David, Ezio: any idea for Serhiy's question?

**Comment by serhiy-storchaka** [comment]
svnmap.txt was added in a single revision and was not changed anymore.

commit 533c79dc67824d95b0aff5a252f9415d3bc80716
Author: Antoine Pitrou \<solipsis@pitrou.net\>
Date:   Sat Mar 5 17:46:03 2011 +0100

    Add the map of SVN revision numbers to changeset ids.
    This is mostly to help history-digging, especially when
    focussing on feature branches.
    Note that not all changesets are in the main repository,
    but they are all in the full history repository.

It is needed for history. Old commit messages and discussion on mailing lists refer to Subversion revisions. Without svnmap.txt you will lost these references unless you have a clone of Subversion repository. I hope you are not going to get rid of [Misc/HISTORY](https://github.com/python/cpython/blob/main/Misc/HISTORY)?

It would be better to create a mapping from Subversion revisions to Git hashes.

**Comment by ned-deily** [comment]
Sorry, I didn't see that the change included the deletion of svnmap.txt.  However, I don't know where or by what that file might still be used, particularly by the lookup function used by the bug tracker.  Presumably someone (Ezio, RDM, or Brett) knows.

**Comment by bitdancer** [comment]
I think Serhiy's point is that it doesn't matter whether or not it is used by a tool, it is useful for humans.  I don't know if it is used by the tracker; Ezio worked on that code, I think.

**Comment by vstinner** [comment]
When I wrote [PR 4615](https://github.com/python/cpython/pull/4615), I misunderstood the usage of [Misc/svnmap.txt](https://github.com/python/cpython/blob/main/Misc/svnmap.txt). I understood that it was used by removed files.

I wrote [PR 4639](https://github.com/python/cpython/pull/4639) to revert the file and clarify its usage in [Misc/README](https://github.com/python/cpython/blob/main/Misc/README).

**Comment by serhiy-storchaka** [comment]
Wouldn't this add two 4 MiB patched in the git repository? Wouldn't this break the history of this file?

**Comment by vstinner** [comment]
Serhiy: "Wouldn't this add two 4 MiB patched in the git repository? Wouldn't this break the history of this file?"

No idea.

**Comment by serhiy-storchaka** [comment]
How have you created [PR 4639](https://github.com/python/cpython/pull/4639)? What git commands were used?

**Comment by vstinner** [comment]
> How have you created [PR 4639](https://github.com/python/cpython/pull/4639)? What git commands were used?

"git revert fe2d5babba5d26de2093b6518316b268488187be", then I modified the commit to only revert svnmap (git commit --amend).

Git internal storage is fully based on sha1. Identical objects should be merged naturally.

My [PR 4639](https://github.com/python/cpython/pull/4639) is made of a single commit: 58f0b38b4058bfaa45a9896aca2b07f02b2de486. You can inspect it using:

```sh
$ git ls-tree 58f0b38b4058bfaa45a9896aca2b07f02b2de486 Misc/svnmap.txt
100644 blob 142be7fc206e9d06d5cf62f6500ef987c0441087	Misc/svnmap.txt
```


Compare it with the svnmap.txt \*before* my revert:

```sh
$ git ls-tree fe2d5babba5d26de2093b6518316b268488187be^ Misc/svnmap.txt
100644 blob 142be7fc206e9d06d5cf62f6500ef987c0441087	Misc/svnmap.txt
```


=\> \*same* blob object (blob sha1: 142be7fc206e9d06d5cf62f6500ef987c0441087)

**Comment by vstinner** [comment]
New changeset 859f7ce7a49f8bd6309748c05e460c10f6a433ed by Victor Stinner in branch 'master':
bpo-32159: Revert [Misc/svnmap.txt](https://github.com/python/cpython/blob/main/Misc/svnmap.txt) (bpo-4639)
https://github.com/python/cpython/commit/859f7ce7a49f8bd6309748c05e460c10f6a433ed

**Comment by vstinner** [comment]
I reverted [Misc/svnmap.txt](https://github.com/python/cpython/blob/main/Misc/svnmap.txt).

I understood that the removal of the two tools in Tools is now ok, and so I close the issue. If I misunderstood, please speak up and/or reopen the issue ;-)

**Comment by serhiy-storchaka** [comment]
Thanks Victor!

I'll open a topic on Python-Dev about file removals.
