### ISSUE TITLE
Python 2.7.14 installation on Ubuntu 16.04/GCC 5.4 throws "internal compiler error" in "PyFloat_GetMax" function

### ISSUE THREAD

**Issue by fefac2da-b085-4ba1-91ea-6bcf76349d2b** [python/cpython#76342]
BPO | [32161](https://bugs.python.org/issue32161)
--- | :---
Nosy | @vstinner, @rahulrajaram
Files | <li>[python_2_7_14__configure_output](https://bugs.python.org/file47301/python_2_7_14__configure_output "Uploaded as text/plain at 2017-11-28.21:59:41 by @rahulrajaram"): Output of ./configure</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-28.22:48:12.959>
created_at = <Date 2017-11-28.21:59:42.041>
labels = ['expert-installation']
title = 'Python 2.7.14 installation on Ubuntu 16.04/GCC 5.4 throws "internal compiler error" in "PyFloat_GetMax" function'
updated_at = <Date 2017-11-28.23:04:25.650>
user = 'https://github.com/rahulrajaram'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-28.23:04:25.650>
actor = 'rahulrajaram'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-28.22:48:12.959>
closer = 'vstinner'
components = ['Installation']
creation = <Date 2017-11-28.21:59:42.041>
creator = 'rahulrajaram'
dependencies = []
files = ['47301']
hgrepos = []
issue_num = 32161
keywords = []
message_count = 4.0
messages = ['307176', '307184', '307186', '307188']
nosy_count = 2.0
nosy_names = ['vstinner', 'rahulrajaram']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32161'
versions = ['Python 2.7']
```

</p></details>

**Comment by fefac2da-b085-4ba1-91ea-6bcf76349d2b** [comment]
Attempt to `make` Python 2.7.14 on Ubuntu 16.04/GCC 5.4 throws the following error:


[Objects/floatobject.c](https://github.com/python/cpython/blob/main/Objects/floatobject.c): In function ‘PyFloat_GetMax’:
[Objects/floatobject.c:59](https://github.com/python/cpython/blob/main/Objects/floatobject.c#L59):5: internal compiler error: Illegal instruction
     return DBL_MAX;
     ^
Please submit a full bug report,
with preprocessed source if appropriate.
See \<file:///usr/share/doc/gcc-5/README.Bugs\> for instructions.
Makefile:1359: recipe for target '[Objects/floatobject.o](https://github.com/python/cpython/blob/main/Objects/floatobject.o)' failed
make: *** [[Objects/floatobject.o](https://github.com/python/cpython/blob/main/Objects/floatobject.o)] Error 1

**Comment by vstinner** [comment]
"internal compiler error" is a bug in GCC, not in Python. Please follow instructions in the error message:

Please submit a full bug report,
with preprocessed source if appropriate.
See \<file:///usr/share/doc/gcc-5/README.Bugs\> for instructions.

See https://gcc.gnu.org/bugs/ and https://gcc.gnu.org/

It would help if you can simplify the code to reproduce the bug without Python.

I close the issue since it's a bug in GCC, not in Python.

**Comment by vstinner** [comment]
Once you reported the bug to GCC, please add a link to your bug report here, please ;-)

**Comment by fefac2da-b085-4ba1-91ea-6bcf76349d2b** [comment]
Thanks for your response. I'll follow up with GCC.
