### ISSUE TITLE
Drop python 3.4 code from asyncio.coroutines and asyncio.unix_events

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#76347]
BPO | [32166](https://bugs.python.org/issue32166)
--- | :---
Nosy | @gvanrossum, @vstinner, @giampaolo, @asvetlov, @serhiy-storchaka, @1st1
PRs | <li>python/cpython#4612</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/asvetlov'
closed_at = <Date 2017-11-30.11:35:35.006>
created_at = <Date 2017-11-29.09:46:45.411>
labels = ['3.7', 'type-feature', 'library', 'expert-asyncio']
title = 'Drop python 3.4 code from asyncio.coroutines and asyncio.unix_events'
updated_at = <Date 2017-11-30.13:04:29.757>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2017-11-30.13:04:29.757>
actor = 'vstinner'
assignee = 'asvetlov'
closed = True
closed_date = <Date 2017-11-30.11:35:35.006>
closer = 'asvetlov'
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-11-29.09:46:45.411>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 32166
keywords = ['patch']
message_count = 11.0
messages = ['307214', '307215', '307216', '307222', '307223', '307224', '307227', '307241', '307297', '307301', '307305']
nosy_count = 6.0
nosy_names = ['gvanrossum', 'vstinner', 'giampaolo.rodola', 'asvetlov', 'serhiy.storchaka', 'yselivanov']
pr_nums = ['4612']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32166'
versions = ['Python 3.7']
```

</p></details>

**Comment by asvetlov** [comment]
Dropped lines are never executed by supported Python versions.
The code exists for sake of keeping the same code base for stdlib asyncio and third-party library with the same name.
Since Python 3.4 asyncio is a part of stdlib, asyncio on PyPI is not supported/updated for 2.5 years.
Removing is safe.

The change keeps backward compatibility with old libraries written for `yield from` syntax, both awaiting old-styled coroutines and yielding from new styles async functions are supported.

```py
async def f():
    ...
yield from f()

@asyncio.coroutine
def g():
    ...
await g()
```


Thus no regressions/deprecations, just removing non-public never executed implementation details.

**Comment by serhiy-storchaka** [comment]
I support getting rid of outdated code.

But what is relation between asyncio in the stdlib and the version outside of the stdlib? Shouldn't the code support old Python versions for easier synchronization? I remember in the past this prevented modernizing it.

The support of 3.4 is important, since this is a version shipped with Ubuntu 16.04 LTS. This will be a main version for enterprise at least yet a year.

**Comment by serhiy-storchaka** [comment]
If it is good to drop 3.4 support in the stdlib asyncio, then there is other outdated code.

There is a 3.3 specific workaround in unix_events.py.

There is a 3.4 code or comments in futures.py, sslproto.py, unix_events.py. Maybe comments are related to optional code which can now be used unconditionally.

Note that not all 3.4 code is marked with "Python 3.4". It can be marked with "Python \< 3.5".

**Comment by asvetlov** [comment]
Separate PyPI package is for Python 3.3 only.
Python 3.4 is shipped with asyncio in standard batteries.

https://github.com/python/asyncio development is stopped, no new PyPI release is expected.

Thank you for pointing on 3.4 specific code in other files.

Victor Stinner did some cleanup in last weeks, I've picked up his initiative.

Will review other files as well.
Please let me create a new issue to keep changes small and modular.

**Comment by serhiy-storchaka** [comment]
I would prefer to do all trivial changes with one commit.

There may be also non-trivial changes.

**Comment by asvetlov** [comment]
Ok, will do everything in single PR

**Comment by asvetlov** [comment]
Fixed unix_events.py but see no legacy code in futures.py and sslproto.py.

**Comment by asvetlov** [comment]
New changeset cc83920ad267c992bc421987829da04d88ae816b by Andrew Svetlov in branch 'master':
bpo-32166: Drop Python 3.4 code from asyncio (bpo-4612)
https://github.com/python/cpython/commit/cc83920ad267c992bc421987829da04d88ae816b

**Comment by serhiy-storchaka** [comment]
Thank you Andrew! This have made the code cleaner.

**Comment by asvetlov** [comment]
You are welcome!
Thanks for review

**Comment by vstinner** [comment]
> Thank you Andrew! This have made the code cleaner.

Yeah! I really love to see old these old crappy legacy stuff to go away. The asyncio code behave shorter, simpler and with less "#ifdef" ;-)

I understand that the Python language and stdlib became better the last 2-3 years ;-)
