### ISSUE TITLE
Mutable instance variables don't get new references with args.

### ISSUE THREAD

**Issue by 0c676dc3-7225-4ee6-b51e-9749ee463950** [python/cpython#76349]
BPO | [32168](https://bugs.python.org/issue32168)
--- | :---
Nosy | @ericvsmith, @bitdancer, @ekarademir
Files | <li>[bug.py](https://bugs.python.org/file47303/bug.py "Uploaded as text/plain at 2017-11-29.11:15:04 by @ekarademir"): Demonstration of the possible bug.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.11:28:00.607>
created_at = <Date 2017-11-29.11:15:04.667>
labels = ['interpreter-core', 'type-bug', 'invalid']
title = "Mutable instance variables don't get new references with args."
updated_at = <Date 2017-12-02.20:51:06.383>
user = 'https://github.com/ekarademir'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-02.20:51:06.383>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.11:28:00.607>
closer = 'eric.smith'
components = ['Interpreter Core']
creation = <Date 2017-11-29.11:15:04.667>
creator = 'ekarademir'
dependencies = []
files = ['47303']
hgrepos = []
issue_num = 32168
keywords = []
message_count = 4.0
messages = ['307219', '307220', '307221', '307456']
nosy_count = 3.0
nosy_names = ['eric.smith', 'r.david.murray', 'ekarademir']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32168'
versions = ['Python 3.6']
```

</p></details>

**Comment by 0c676dc3-7225-4ee6-b51e-9749ee463950** [comment]
Hello,

I've searched all over Google and this bug tracker with all combinations of keywords that I can associate with this issue, but I couldn't find an explanation that makes sense or fits the issue.

I know that when dealing with mutable variables, class variables share the same reference with all instances, so to assign separate attributes for instances, mutable variables should be instance level variables.

However when I create a class like the following,

```py
    class Base:
        def __init__(self, props=list(), foo='foo base'):
            self.props = props
            self.foo = foo
        
        def insert_prop(self, i):
            self.props.append(i)
```


and run this:

```py
    if __name__ == '__main__':
        base = Base()

        base.insert_prop(1)
        base.insert_prop(2)

        print('base props before base2, 3 creation:', base.props)

        base2 = Base()
        base3 = Base([41, 42])

        print('base props after base2, 3 creation:', base.props)
        print('base2 props after base2, 3 creation:', base2.props)
        print('base3 props after base2, 3 creation:', base3.props)

        base2.insert_prop(51)
        base3.insert_prop(61)

        print('base props after insertion:', base.props)
        print('base2 props after insertion:', base2.props)
        print('base3 props after insertion:', base3.props)
```


the output is this:

    base props before base2, 3 creation: [1, 2]
    base props after base2, 3 creation: [1, 2]
    base2 props after base2, 3 creation: [1, 2]
    base3 props after base2, 3 creation: [41, 42]
    base props after insertion: [1, 2, 51]
    base2 props after insertion: [1, 2, 51]
    base3 props after insertion: [41, 42, 61]

So initiating base3 with explicit args gives it a new reference to the props variable but base and base2 share the same reference. So suddenly props is hoisted to class level.

I actually encountered this behaviour when trying to do the same thing with child classes with no \_\_init__ method like:

```py
    class Sub1(Base):
        pass
```


The whole code is attached.

Is this an expected behaviour? If so I couldn't find a gotcha anywhere.

Regards,

Ertugrul

**Comment by ericvsmith** [comment]
This is defined behavior. Try searching for "mutable default parameter". For example, here's an old post on it:

http://www.effbot.org/zone/default-values.htm

This isn't related to class vs. instance attributes, but rather the default parameter 'props' being modified.

**Comment by 0c676dc3-7225-4ee6-b51e-9749ee463950** [comment]
Thank you

Ertuğrul Karademir
