### ISSUE TITLE
Add length counter for iterables

### ISSUE THREAD

**Issue by 89f4240f-251b-48e9-858b-0ad5ad4ede03** [python/cpython#76353]
BPO | [32172](https://bugs.python.org/issue32172)
--- | :---
Nosy | @stevendaprano, @bitdancer

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-11-29.23:11:36.305>
created_at = <Date 2017-11-29.23:00:53.320>
labels = ['type-feature', '3.8']
title = 'Add length counter for iterables'
updated_at = <Date 2017-12-02.21:18:24.496>
user = 'https://bugs.python.org/bugalebugale'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-02.21:18:24.496>
actor = 'r.david.murray'
assignee = 'none'
closed = True
closed_date = <Date 2017-11-29.23:11:36.305>
closer = 'steven.daprano'
components = ['Demos and Tools']
creation = <Date 2017-11-29.23:00:53.320>
creator = 'bugale bugale'
dependencies = []
files = []
hgrepos = []
issue_num = 32172
keywords = []
message_count = 3.0
messages = ['307271', '307274', '307459']
nosy_count = 3.0
nosy_names = ['steven.daprano', 'r.david.murray', 'bugale bugale']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32172'
versions = ['Python 3.8']
```

</p></details>

**Comment by 89f4240f-251b-48e9-858b-0ad5ad4ede03** [comment]
I have noticed that there is no convenient way in python to get the number of items in a generator.

For example:
  my_iterable = iter(range(1000))
  len(my_iterable) # Would not work

Of course, something like this would ruin the generator, and it will no longer be usable, but in some use cases one would like to know only the count of something.

It is possible to do it today using this line:
  sum(1 for x in my_iterable)

but it seems odd to me that there is no function like:
  itertools.count_iterable(my_iterable)
that does exactly this

**Comment by stevendaprano** [comment]
Not every trivial one-liner needs to be in the standard library. In this case, there are two easy (and obvious) ways to do it:

```py
sum(1 for x in iterator)

len(list(iterator))
```


(The first probably saves memory; the second probably is faster.)

Given how rare it is to care ONLY about the length of an iterator, I see no reason why this needs to be in the std lib. If you disagree, please take it to the Python-Ideas mailing list to get community support first before re-opening this ticket.
