### ISSUE TITLE
bool() vs len() > 0 on lists

### ISSUE THREAD

**Issue by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [python/cpython#76361]
BPO | [32180](https://bugs.python.org/issue32180)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2017-12-01.20:00:08.881>
created_at = <Date 2017-11-30.11:31:47.447>
labels = ['3.7', 'invalid', 'performance']
title = 'bool() vs len() > 0 on lists'
updated_at = <Date 2017-12-01.20:00:08.880>
user = 'https://bugs.python.org/dilyanpalauzov'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-01.20:00:08.880>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2017-12-01.20:00:08.881>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2017-11-30.11:31:47.447>
creator = 'dilyan.palauzov'
dependencies = []
files = []
hgrepos = []
issue_num = 32180
keywords = []
message_count = 8.0
messages = ['307294', '307300', '307306', '307309', '307311', '307313', '307405', '307408']
nosy_count = 3.0
nosy_names = ['rhettinger', 'dilyan.palauzov', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue32180'
versions = ['Python 3.7']
```

</p></details>

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
Please make bool() on lists at least as fast as len() \> 0 on lists is.

The trivial approach would be to define \_\_bool__ on lists, that do something like  "True if self else False".

```pycon
python3 
Python 3.6.3+ (heads/3.6-dirty:2b5cbbb13c, Nov  1 2017, 19:03:09) 
[GCC 6.4.1 20171025] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import timeit
>>> timeit.timeit('len([]) > 0')
0.0983404889702797
>>> timeit.timeit('bool([])')
0.15502946823835373
>>> timeit.timeit('True if [] else False')
0.03108721226453781
>>> timeit.timeit('len([1]) > 0')
0.11656427383422852
>>> timeit.timeit('bool([1])')
0.19317257404327393
>>> timeit.timeit('True if [1] else False')
0.057590410113334656
```

**Comment by serhiy-storchaka** [comment]
The cause of len() been faster than bool() is the same as why repr() is faster than str(). [1] len() and repr() are functions that just call corresponding slots, while bool() and str() are constructors.

In most cases you shouldn't use `bool(obj)` or `len(obj) > 0`. Instead use just `obj` in conditions.

If you can provide a patch that speeds up constructions of simple class instances, please open a pull request on GitHub. Otherwise this issue will be closed.

[1] https://stackoverflow.com/questions/45376719/why-is-reprint-faster-than-strint

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
To my understanding this optimization (bool([]) faster than len([])) cannot be made until PyObject_Bool is introduced, similar to PyObject_Repr and PyObject_Length.

Am I not going to provide a patch.

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
Under these circumstances https://wiki.python.org/moin/PythonSpeed/PerformanceTips shall be updated to state that 

"len('a list') \> 0" is slower than "True if 'a list' else False"

**Comment by serhiy-storchaka** [comment]
I don't know what should mean PyObject_Bool(), but in C code you should use PyObject_IsTrue() for getting the boolean value of the object.

**Comment by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [comment]
Is the speedup a matter of adding "\_\_bool__" to list_methods in object/listobject.c?

In any case, I am not in the internals of cpython, so that I am not going to provide a patch.

With PyObject_Bool I meant PyObject_IsTrue.
