### ISSUE TITLE
Replace empty matches adjacent to a previous non-empty match in re.sub()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#76489]
BPO | [32308](https://bugs.python.org/issue32308)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @boxed
PRs | <li>python/cpython#4846</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2018-01-04.09:06:40.130>
created_at = <Date 2017-12-13.18:28:37.987>
labels = ['expert-regex', 'type-feature', 'library', '3.7']
title = 'Replace empty matches adjacent to a previous non-empty match in re.sub()'
updated_at = <Date 2020-04-16.16:28:26.175>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-16.16:28:26.175>
actor = 'serhiy.storchaka'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2018-01-04.09:06:40.130>
closer = 'serhiy.storchaka'
components = ['Library (Lib)', 'Regular Expressions']
creation = <Date 2017-12-13.18:28:37.987>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 32308
keywords = ['patch']
message_count = 14.0
messages = ['308229', '309055', '309458', '339949', '339950', '339989', '340040', '340102', '360352', '360355', '366595', '366602', '366604', '366606']
nosy_count = 6.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'mu_mind', 'serhiy.storchaka', 'Anders.Hovm\xc3\xb6ller', 'Mark Borgerding']
pr_nums = ['4846']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32308'
versions = ['Python 3.7']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Please read all previous discussions and explanations scattered across several issues.

In your example, look how many occurrences of the pattern are found in the string:
```
>>> re.findall('.*', "One line haystack")
['One line haystack', '']
```
And where they are found:
```
>>> [m.span() for m in re.finditer('.*', "One line haystack")]
[(0, 17), (17, 17)]
```
Now, if you replace characters in the ranges 0 to 17 and 17 to 17 with the replacement string "needle", what do you get?

**Comment by znsoooo** [comment]
> For example replacing re.sub('(.*)', ...) (which now matches an empty string at the end of the string) with re.sub('(.+)', ...) is an obvious fix.

The ".*" can match empty line but the ".+" can't. This conversion is not equivalent.
