### ISSUE TITLE
EIO from write() is only fatal if print() contains a newline

### ISSUE THREAD

**Issue by 057641c5-59f0-4d1f-9529-a446f176c1bb** [python/cpython#76526]
BPO | [32345](https://bugs.python.org/issue32345)
--- | :---
Nosy | @pitrou, @vstinner

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-12-16.09:28:32.636>
labels = ['expert-IO']
title = 'EIO from write() is only fatal if print() contains a newline'
updated_at = <Date 2017-12-25.23:49:51.315>
user = 'https://bugs.python.org/Creideiki'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-25.23:49:51.315>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['IO']
creation = <Date 2017-12-16.09:28:32.636>
creator = 'Creideiki'
dependencies = []
files = []
hgrepos = []
issue_num = 32345
keywords = []
message_count = 5.0
messages = ['308468', '308690', '308718', '308719', '308732']
nosy_count = 3.0
nosy_names = ['pitrou', 'vstinner', 'Creideiki']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue32345'
versions = ['Python 2.7']
```

</p></details>

**Comment by chestnut1693** [comment]
I am experiencing the same problems. Quickly logging out from an ssh connection after I just ran a python script will cause the script to exit early, presumably by hitting a print(), without hitting the rest of the script. Using strace I saw some _"-1 EIO (Input/output error)"_ coming by. My suspicion of print() being the culprit grew when the script would continue even after dropping ssh connection when i redirected stdout and stderr with something like `&>/dev/null`. Now running without redirecting and with calling all print() without the default `end=` set to `\n`, the script continues even after dropping ssh connection.

The script starts multiple processes further down the line. I do not know how prints by these processes act.

I am using python version 3.7.3 on a raspberry pi.

**Comment by vstinner** [comment]
I hacked `_Py_write()` to make any write to file descriptor 5 fail with EIO:

```diff
diff --git a/Python/fileutils.c b/Python/fileutils.c
index 17a4ae56ef..2f36f82b1e 100644
--- a/Python/fileutils.c
+++ b/Python/fileutils.c
@@ -1957,7 +1957,13 @@ _Py_write_impl(int fd, const void *buf, size_t count, int gil_held)
                 c /= 2;
             } while (c > 0);
 #else
-            n = write(fd, buf, count);
+            if (fd == 5) {
+                n = -1;
+                errno = EIO;
+            }
+            else {
+                n = write(fd, buf, count);
+            }
 #endif
             /* save/restore errno because PyErr_CheckSignals()
              * and PyErr_SetFromErrno() can modify it */
```

I wrote a script to reproduce the issue:

```py
import os
import sys

stdout_fd = sys.stdout.fileno()
fd = 5
os.dup2(stdout_fd, fd)

# with open(fd) closes fd at the end of the with block
with open(fd, "w", encoding="utf-8") as fp:
    id(0)
    print("ANNOYING", end="\n", file=fp)
    fp.flush()
    id(0)
```

This scripts calls write() 3 times on fd 5.

* `print("ANNOYING", end="\n", file=fp)` calls write(5, "ANNOYING\n", 9): print() => TextIOWrapper.write() => BufferedWriter.flush() => `FileIO.write()` => `_Py_write()` => `write()` (call 1).
* Exiting `with` block calls `TextIOWrapper.__exit__()` => `TextIOWrapper.close()`:
  * => `TextIOWrapper.flush()` => `BufferedWriter.flush()` => `BufferedWriter.write()` => `FileIO.write()` => `_Py_write()` => `write()` (call 2).
  * and then => `BufferedWriter.close()` => `BufferedWriter.flush()` => `BufferedWriter.write()` => `FileIO.write()` => `_Py_write()` => `write()` (call 3).

**Comment by vstinner** [comment]
For me, TextIOWrapper behaves as expected: every print raises OSErrno(EIO).

Script:

```py
import contextlib
import errno
import os
import sys


@contextlib.contextmanager
def catch_eio():
    try:
        yield
    except OSError as exc:
        if exc.errno != errno.EIO:
            raise
    else:
        raise Exception("EIO not raised")


stdout_fd = sys.stdout.fileno()
fd = 5
os.dup2(stdout_fd, fd)

# with open(fd) closes fd at the end of the with block
fp = open(fd, "w", encoding="utf-8")
with catch_eio():
    print('A', file=fp)
with catch_eio():
    print('B\nC', file=fp)
with catch_eio():
    print('D', file=fp)
with catch_eio():
    fp.close()
```

Using my patch to make write() fail with EIO for fd=5, running this script just works: each print() raises OSError(EIO), as well as `fp.close()`.

**Comment by vstinner** [comment]
`print('ANNOYING', end="", file=fp)` does not raise an exception because TextIOWrapper only writes when a line is complete, unless *write_through* is false.

To initialize `sys.stdout` *write_through* being true, use `-u` command line option: https://docs.python.org/dev/using/cmdline.html#cmdoption-u

```py
import contextlib
import errno
import os
import sys


@contextlib.contextmanager
def catch_eio():
    try:
        yield
    except OSError as exc:
        if exc.errno != errno.EIO:
            raise
    else:
        raise Exception("EIO not raised")


stdout_fd = sys.stdout.fileno()
fd = 5
os.dup2(stdout_fd, fd)

# with open(fd) closes fd at the end of the with block
fp = open(fd, "w", encoding="utf-8")
print('ANNOYING', end="", file=fp)
with catch_eio():
    fp.flush()
with catch_eio():
    fp.close()
```

**Comment by vstinner** [comment]
I don't see any clear error on the Python side. I close the issue.

Maybe Python 2 print() behaved differently, but the I/O stack of Python 3 was rewritten: the `io` module (TextIOWrapper, BufferedWriter, FileIO classes).
