### ISSUE TITLE
Add AbstractFuture and AbstractTask

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#76545]
BPO | [32364](https://bugs.python.org/issue32364)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-12-18.11:13:10.296>
labels = ['3.8', 'library', 'expert-asyncio']
title = 'Add AbstractFuture and AbstractTask'
updated_at = <Date 2017-12-20.18:49:03.930>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2017-12-20.18:49:03.930>
actor = 'asvetlov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'asyncio']
creation = <Date 2017-12-18.11:13:10.296>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 32364
keywords = []
message_count = 3.0
messages = ['308543', '308578', '308771']
nosy_count = 2.0
nosy_names = ['asvetlov', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue32364'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
This seems stuck. I don't think this can and should be done now as the current norm is to subclass the default task and override the methods. ABCs wouldn't solve any problem here.

**Comment by gvanrossum** [comment]
Plus, everyone has been using type annotations where they just write `t: asyncio.Task`. So we can't even change the signature of `create_future()` to `-> AbstractTask` because it would break such annotations. Ditto for `Future`.

I'm closing this.
