### ISSUE TITLE
Disallow untagged C extension import on major platforms

### ISSUE THREAD

**Issue by pitrou** [python/cpython#76568]
BPO | [32387](https://bugs.python.org/issue32387)
--- | :---
Nosy | @warsaw, @brettcannon, @gpshead, @pfmoore, @ronaldoussoren, @ncoghlan, @pitrou, @scoder, @tiran, @tjguk, @ned-deily, @njsmith, @ericsnowcurrently, @zware, @zooba, @dstufft, @MojoVampire, @AraHaan
PRs | <li>python/cpython#4943</li>
Files | <li>[changes.diff](https://bugs.python.org/file47342/changes.diff "Uploaded as text/plain at 2017-12-20.21:43:25 by @AraHaan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2017-12-20.15:47:54.501>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Disallow untagged C extension import on major platforms'
updated_at = <Date 2019-03-02.00:45:01.466>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-02.00:45:01.466>
actor = 'gregory.p.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2017-12-20.15:47:54.501>
creator = 'pitrou'
dependencies = []
files = ['47342']
hgrepos = []
issue_num = 32387
keywords = ['patch']
message_count = 20.0
messages = ['308741', '308742', '308748', '308749', '308789', '308791', '308792', '308822', '308829', '308878', '308879', '308899', '311255', '311256', '311309', '311314', '314328', '314333', '336956', '336977']
nosy_count = 19.0
nosy_names = ['barry', 'brett.cannon', 'gregory.p.smith', 'paul.moore', 'ronaldoussoren', 'ncoghlan', 'pitrou', 'scoder', 'christian.heimes', 'tim.golden', 'ned.deily', 'njs', 'eric.snow', 'zach.ware', 'steve.dower', 'dstufft', 'Marcus.Smith', 'josh.r', 'Decorater']
pr_nums = ['4943']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32387'
versions = ['Python 3.8']
```

</p></details>

**Comment by brettcannon** [comment]
Looking at the discussion on the the PR trying to implement this, it's sounding like people in general don't think dropping the support is worth the potential breakage.

Do people still think this is worth doing?

**Comment by AraHaan** [comment]
I personally think that doing this is not really worth the effort at all as all the time it would take to do this sort of thing can be better spent doing more important things.

**Comment by brettcannon** [comment]
I'm going to assume the 👎 on my comment about closing this was voting in closing it and not in reaction to me suggesting we close this issue. 😅

I'm going to close this issue and the PR.
