### ISSUE TITLE
chr raises OverflowError

### ISSUE THREAD

**Issue by 3140d666-f844-4443-90e2-98c86a0ec737** [python/cpython#76763]
BPO | [32582](https://bugs.python.org/issue32582)
--- | :---
Nosy | @terryjreedy, @mdickinson, @vstinner, @serhiy-storchaka, @iritkatriel
PRs | <li>python/cpython#5218</li>
Files | <li>[chr-OverflowError.patch](https://bugs.python.org/file47390/chr-OverflowError.patch "Uploaded as text/plain at 2018-01-17.14:32:06 by ukl")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-01-17.14:32:06.372>
labels = ['interpreter-core', 'type-bug', '3.11']
title = 'chr raises OverflowError'
updated_at = <Date 2021-11-22.15:20:54.228>
user = 'https://bugs.python.org/ukl'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-22.15:20:54.228>
actor = 'mark.dickinson'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-01-17.14:32:06.372>
creator = 'ukl'
dependencies = []
files = ['47390']
hgrepos = []
issue_num = 32582
keywords = ['patch']
message_count = 5.0
messages = ['310178', '310180', '310288', '310330', '406721']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'mark.dickinson', 'vstinner', 'serhiy.storchaka', 'ukl', 'iritkatriel']
pr_nums = ['5218']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32582'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-104486
* gh-114882

**Comment by hauntsaninja** [comment]
Given that this is a long standing behaviour and there's little reason to be passing large values here, should we just document that chr can raise OverflowError instead?

Also note `"%c" % 1114113` raises OverflowError, should that raise ValueError instead?
