### ISSUE TITLE
Drop support of Windows Vista and Windows 7

### ISSUE THREAD

**Issue by vstinner** [python/cpython#76773]
BPO | [32592](https://bugs.python.org/issue32592)
--- | :---
Nosy | @terryjreedy, @pfmoore, @pitrou, @tjguk, @ambv, @zware, @eryksun, @zooba, @izbyshev, @ZackerySpytz, @CAM-Gerlach, @Fidget-Spinner
PRs | <li>python/cpython#5231</li><li>python/cpython#11457</li><li>python/cpython#11457</li><li>python/cpython#11457</li><li>python/cpython#15951</li><li>python/cpython#22586</li><li>python/cpython#26429</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-03-21.20:38:56.872>
created_at = <Date 2018-01-18.09:37:18.007>
labels = ['type-feature', '3.10', 'OS-windows']
title = 'Drop support of Windows Vista and Windows 7'
updated_at = <Date 2022-03-21.20:38:56.871>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-21.20:38:56.871>
actor = 'steve.dower'
assignee = 'none'
closed = True
closed_date = <Date 2022-03-21.20:38:56.872>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2018-01-18.09:37:18.007>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 32592
keywords = ['patch']
message_count = 44.0
messages = ['310227', '310233', '310234', '310296', '310297', '310303', '310308', '318103', '333160', '333161', '333186', '333187', '341393', '341534', '341535', '341612', '342041', '351882', '351965', '352476', '352502', '353307', '353308', '353312', '353328', '363348', '363352', '363356', '364793', '364798', '364899', '388700', '388703', '388705', '389225', '389377', '389378', '389385', '389398', '389413', '389445', '389449', '389460', '389476']
nosy_count = 15.0
nosy_names = ['terry.reedy', 'paul.moore', 'pitrou', 'tim.golden', 'lukasz.langa', 'python-dev', 'zach.ware', 'eryksun', 'steve.dower', 'izbyshev', 'ZackerySpytz', 'CAM-Gerlach', 'kj', 'DMI-1407', 'veso266']
pr_nums = ['5231', '11457', '11457', '11457', '15951', '22586', '26429']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32592'
versions = ['Python 3.10']
```

</p></details>

**Comment by CAM-Gerlach** [comment]
I took care of the docs changes mentioned in [my comment above](https://github.com/python/cpython/issues/76773#issuecomment-1093773607). Aside from the installer updates and the other breaking security change, have any of the code changes cleanups [mentioned in my other comment](https://github.com/python/cpython/issues/76773#issuecomment-1093773608) or discussed further above been made? If so, are they still work making for 3.12?

**Comment by CAM-Gerlach** [comment]
Just for posterity, since I couldn't find it mentioned anywhere here for some reason, it was PR #21656 that actually dropped support for Windows <8.1 in the installer.
