### ISSUE TITLE
pathlib.(Pure)WindowsPaths can compare equal but refer to different files

### ISSUE THREAD

**Issue by c6a16194-fbe2-452d-ab7b-5a02c5e92e91** [python/cpython#76793]
BPO | [32612](https://bugs.python.org/issue32612)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @bitdancer, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-01-21.21:04:41.822>
labels = ['type-security', '3.8', '3.7', 'library', 'OS-windows']
title = 'pathlib.(Pure)WindowsPaths can compare equal but refer to different files'
updated_at = <Date 2018-01-23.17:18:35.550>
user = 'https://bugs.python.org/benrg'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-23.17:18:35.550>
actor = 'r.david.murray'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2018-01-21.21:04:41.822>
creator = 'benrg'
dependencies = []
files = []
hgrepos = []
issue_num = 32612
keywords = []
message_count = 9.0
messages = ['310384', '310477', '310479', '310480', '310481', '310483', '310484', '310510', '310512']
nosy_count = 7.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'r.david.murray', 'benrg', 'zach.ware', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue32612'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by barneygale** [comment]
It should be possible to subclass `pathlib.[Pure]WindowsPath` and override `__hash__`, `__eq__`, etc, to perform a more conservative comparison. In Python 3.12+ it's also possible to subclass `pathlib.[Pure]Path`.

> I think that pathlib should either give up on case folding entirely, or should fold very conservatively, treating WCHARs as equivalent only if they're equivalent on all standard file systems on all supported Windows versions.

This would make pathlib less useful in the 99.9% of cases where this bug doesn't matter.

> Could WindowsPath (as opposed to PureWindowsPath) call samefile as part of the equality test? 

This would be too slow.

Closing this issue as there's nothing practical we can do about it in core pathlib.
