### ISSUE TITLE
add support for path-like objects in sys.path

### ISSUE THREAD

**Issue by cjerdonek** [python/cpython#76823]
BPO | [32642](https://bugs.python.org/issue32642)
--- | :---
Nosy | @malemburg, @brettcannon, @jaraco, @ncoghlan, @merwok, @cjerdonek, @ericsnowcurrently, @serhiy-storchaka, @eryksun, @jayyyin, @noamcohen97
PRs | <li>python/cpython#5691</li><li>python/cpython#22000</li><li>python/cpython#32118</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-01-24.05:27:12.840>
labels = ['type-feature', 'library', '3.11']
title = 'add support for path-like objects in sys.path'
updated_at = <Date 2022-03-26.18:25:50.267>
user = 'https://github.com/cjerdonek'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-26.18:25:50.267>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-01-24.05:27:12.840>
creator = 'chris.jerdonek'
dependencies = []
files = []
hgrepos = []
issue_num = 32642
keywords = ['patch']
message_count = 28.0
messages = ['310560', '311693', '311864', '311895', '311986', '312070', '312072', '313283', '313337', '313388', '313460', '313883', '313885', '313887', '313923', '314065', '340950', '409732', '415012', '416037', '416042', '416048', '416050', '416052', '416053', '416057', '416065', '416078']
nosy_count = 12.0
nosy_names = ['lemburg', 'brett.cannon', 'jaraco', 'ncoghlan', 'eric.araujo', 'chris.jerdonek', 'python-dev', 'eric.snow', 'serhiy.storchaka', 'eryksun', 'jayyin11043', 'ncohen']
pr_nums = ['5691', '22000', '32118']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32642'
versions = ['Python 3.11']
```

</p></details>

**Comment by zxrobinson** [comment]
Why use a subclass of PyListObject when you could use composition? Create a singleton SysPath object containing a list. Add pass through methods for all of the List behavior you want. Any methods that modify the list by adding an item can convert the item to an str. This might make sys.path much easier to understand and maintain. Letting people completely replace the whole thing would seem to make it very fragile.

**Comment by merwok** [comment]
This change requires a discussion on python-dev, maybe even a PEP.

Closing this ticket for now, please reopen if a discussion reaches positive agreement on this.
