### ISSUE TITLE
Can no longer specify OpenSSL locations with CPPFLAGS / LDFLAGS ?

### ISSUE THREAD

**Issue by 1st1** [python/cpython#76875]
BPO | [32694](https://bugs.python.org/issue32694)
--- | :---
Nosy | @warsaw, @tiran, @ned-deily, @1st1, @moreati
PRs | <li>python/cpython#5388</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2018-01-28.15:11:23.713>
labels = ['3.8', 'type-feature', '3.7', 'build']
title = 'Can no longer specify OpenSSL locations with CPPFLAGS / LDFLAGS ?'
updated_at = <Date 2018-05-24.06:04:36.625>
user = 'https://github.com/1st1'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-24.06:04:36.625>
actor = 'ned.deily'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2018-01-28.15:11:23.713>
creator = 'yselivanov'
dependencies = []
files = []
hgrepos = []
issue_num = 32694
keywords = ['patch']
message_count = 8.0
messages = ['310953', '310967', '310968', '310969', '310971', '311152', '311213', '317532']
nosy_count = 5.0
nosy_names = ['barry', 'christian.heimes', 'ned.deily', 'yselivanov', 'Alex.Willmer']
pr_nums = ['5388']
priority = 'high'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32694'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ned-deily** [comment]
As the devguide has long since been updated to include [current instructions for installing and linking with third-party libraries](https://devguide.python.org/getting-started/setup-building/#macos) from Homebrew and MacPorts, including OpenSSL, I think this issue is no longer needed.
