### ISSUE TITLE
Make create_unix_server for SOCK_DGRAM work

### ISSUE THREAD

**Issue by f5064402-3d41-4f05-9b42-2fcfe353fc8d** [python/cpython#76896]
BPO | [32715](https://bugs.python.org/issue32715)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-01-29.22:29:49.978>
labels = ['type-feature', '3.8', 'expert-asyncio']
title = 'Make create_unix_server for SOCK_DGRAM work'
updated_at = <Date 2018-01-29.23:16:47.600>
user = 'https://bugs.python.org/holgerlp'
```

bugs.python.org fields:
```python
activity = <Date 2018-01-29.23:16:47.600>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-01-29.22:29:49.978>
creator = 'holger+lp'
dependencies = []
files = []
hgrepos = []
issue_num = 32715
keywords = []
message_count = 4.0
messages = ['311188', '311192', '311196', '311198']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'holger+lp']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32715'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
Is there still interest in this issue?  What is the use case for this? 

Currently `asyncio` only supports `SOCK_STREAM` so adding support for this would require lot of changes.

**Comment by gvanrossum** [comment]
It doesn't look like even the OP has cared since the day the issue was opened (and they didn't disclose their GitHub username to bpo). Let's close this.
