### ISSUE TITLE
LoggingAdapter ignores extra kwargs of Logger#log()

### ISSUE THREAD

**Issue by cdb2d6f3-0773-44d1-93bb-8d582eccb9ae** [python/cpython#76913]
BPO | [32732](https://bugs.python.org/issue32732)
--- | :---
Nosy | @vsajip, @matrixise, @mcoolive, @samueloph
PRs | <li>python/cpython#5463</li>
Files | <li>[bpo-32732_logger_adapter.patch](https://bugs.python.org/file50136/bpo-32732_logger_adapter.patch "Uploaded as text/plain at 2021-07-01.01:06:54 by @samueloph"): patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-02-28.21:30:29.134>
created_at = <Date 2018-01-31.18:26:15.495>
labels = ['3.8', 'library', 'invalid']
title = 'LoggingAdapter ignores extra kwargs of Logger#log()'
updated_at = <Date 2021-07-01.01:06:56.860>
user = 'https://github.com/mcoolive'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-01.01:06:56.860>
actor = 'samueloph'
assignee = 'none'
closed = True
closed_date = <Date 2018-02-28.21:30:29.134>
closer = 'vinay.sajip'
components = ['Library (Lib)']
creation = <Date 2018-01-31.18:26:15.495>
creator = 'mcoolive'
dependencies = []
files = ['50136']
hgrepos = []
issue_num = 32732
keywords = ['patch']
message_count = 8.0
messages = ['311353', '311406', '313058', '313070', '313093', '313162', '320708', '396806']
nosy_count = 5.0
nosy_names = ['vinay.sajip', 'matrixise', 'srs', 'mcoolive', 'samueloph']
pr_nums = ['5463']
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue32732'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-107292

**Comment by jack-tutor** [comment]
I third that this is unexpected and poorly documented behavior.  I would like to be able to use loggerAdapter and loggers interchangeably without losing `extra` arguments.

**Comment by cc-stjm** [comment]
Likewise, just discovered this the hard way, it's the complete opposite of the expected behaviour

**Comment by vsajip** [comment]
No, not "the complete opposite". If you need to pass different `extra` values every time, don't use a `LoggerAdapter`, use a logger. The `LoggerAdapter` is for when you have a fixed set of `extra` values to be passed each time - you then pass those to the `LoggerAdapter` constructor. If you want to fine-tune, you can subclass `LoggerAdapter` to your specific needs. It's clearly documented, too:

> When you create an instance of `LoggerAdapter`, you pass it a `Logger` instance and a dict-like object which contains your contextual information. When you call one of the logging methods on an instance of `LoggerAdapter`, it delegates the call to the underlying instance of Logger passed to its constructor, and arranges to pass the contextual information in the delegated call.

If you feel the documentation is unclear, feel free to submit a PR or _specific_ wording you think is clearer (or needed in addition to what's currently there), and I'll look at it. Statements like "poorly documented" are completely useless to a maintainer if that's _all_ the feedback provided. Without specific suggestions, it's hard to assess from the complaint whether something is actually poorly documented, or whether the complainer's reading comprehension is less than optimal.

**Comment by jack-tutor** [comment]
Given that very extensive comments had been added and a lack of support was cited as a mark against this suggestion: `The existing LoggerAdapter functionality has been around since Jan 2008, and it seems that no one in that time has raised this as a must-have.`  - I figured registering support would be appreciated.

It seems a reasonable request to use a `LoggerAdapter` when you have some set of fixed extras and some other set of non-fixed extras.  This is a very reasonable use-case, that the `LoggerAdapter` can support, but is choosing not to.  I can say more, but really it would just be repeating what people have said earlier - like https://github.com/python/cpython/issues/76913#issuecomment-1093775475.

On the docs question, these are the docs I found: https://docs.python.org/3/library/logging.html#loggeradapter-objects - I'm not sure what docs you are referencing.

I would take issue with this statement, though I concede it is technically correct:
```
These methods have the same signatures as their counterparts in [Logger](https://docs.python.org/3/library/logging.html#logging.Logger), so you can use the two types of instances interchangeably.
```
as the use is not really interchangeable given that the `extra` argument in these log calls is dropped.  I would clarify that statement:
```
These methods have the same signatures as their counterparts in [Logger](https://docs.python.org/3/library/logging.html#logging.Logger), so you can use the two types of instances interchangeably, though the value passed for the kwarg `extra` will be ignored.
```

**Comment by vsajip** [comment]
> It seems a reasonable request to use a LoggerAdapter when you have some set of fixed extras and some other set of non-fixed extras

But then the `extra` information as a whole varies from call to call, and so the normal thing to do then is to use `Logger`. `LoggerAdapter` is for when you have a fixed `extra` value, and using `LoggerAdapter` saves you having to pass it every time.

> I'm not sure what docs you are referencing

I was referring to [this bit in the logging cookbook](https://docs.python.org/3/howto/logging-cookbook.html#using-loggeradapters-to-impart-contextual-information).

> I would clarify that statement

Well, that is a reasonable suggested documentation change, and I aim to add that clarification soon. Thanks!

**Comment by lukasz-mitka** [comment]
For all the unfortunate souls that end up here just like me:
```python
class MergingLoggerAdapter(logging.LoggerAdapter):
    """LoggerAdapter that merges extras"""

    def process(self, msg, kwargs):
        kwargs["extra"] = (self.extra or {}) | (kwargs["extra"] or {})
        return msg, kwargs
```

And for maintainers: even if the docs will be updated it still will be an unintuitive behavior.

**Comment by francescoalongi** [comment]
+1 for @lukasz-mitka. It might happen sometimes to need contextual information to be added just once (LoggerAdapter extra) at the beginning and other extras to be added throughout the code, it would be great to have this feature as a standard

**Comment by NiklasBeierl** [comment]
I second the idea that the use-case @francescoalongi and others describe should be supported by `logging` out of the box. It also strikes me as very unintuitive that LoggerAdapter just silently discards `extra`s passed to its log methods, as pointed out by @cc-stjm. 

Concerns for backwards compatibility could be remedied by adding a kwarg: `merge_extras: bool = False` to `LoggerAdapter`.  `LoggerAdapter` keeps his current behavior by default, but does what `MergingLoggerAdapter` from @lukasz-mitka does if `merge_extras` is set to `True`. 

Another option would be a `more_extras` kwarg for `LoggerAdapter`, that works something like this: 

- LoggerAdapter keeps the `extra`s passed to `__init__` by default. (To preserve backwards compat)
- LoggerAdapter merges the `extra`s passed to `__init__` and `.log` (or `.<loglevel>`)  IFF  `more_extras == "merge"`
- LoggerAdapter uses the `extras` passed to `__init__` if no `extras`  are passed to a `.log`-call, but extras passed to a `.log` call take precendce IFF `more_extras="replace"`

@vsajip would you accept a PR implementing such a behavior?

**Comment by vsajip** [comment]
> Concerns for backwards compatibility could be remedied by adding a kwarg: merge_extras: bool = False to LoggerAdapter. LoggerAdapter keeps his current behavior by default, but does what MergingLoggerAdapter from @lukasz-mitka does if merge_extras is set to True.

OK, I'll look at a PR along these lines.

**Comment by simonasbuj** [comment]
Hi, sorry, which python version has these changes? Im using python 3.11.5 and it says that unexpected keyword argument 'merge_extra'. Is it only in python 3.12?

**Comment by vsajip** [comment]
3.13 (not yet released). It's a behaviour change, so not backported to earlier versions.
