### ISSUE TITLE
ctypes: memoryview gives incorrect PEP3118 format strings for both packed and unpacked structs

### ISSUE THREAD

**Issue by f72d0bc0-f319-4dd9-9db4-d64615e4a426** [python/cpython#76961]
BPO | [32780](https://bugs.python.org/issue32780)
--- | :---
Nosy | @terryjreedy, @vsajip, @amauryfa, @abalkin, @aerojockey, @skrah, @meadori, @mattip, @eric-wieser
PRs | <li>python/cpython#5561</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/abalkin'
closed_at = None
created_at = <Date 2018-02-06.05:27:59.358>
labels = ['3.8', 'ctypes', 'type-bug', '3.7']
title = 'ctypes: memoryview gives incorrect PEP3118 format strings for both packed and unpacked structs'
updated_at = <Date 2019-12-23.17:24:49.037>
user = 'https://github.com/eric-wieser'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-23.17:24:49.037>
actor = 'ned.deily'
assignee = 'belopolsky'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2018-02-06.05:27:59.358>
creator = 'Eric.Wieser'
dependencies = []
files = []
hgrepos = []
issue_num = 32780
keywords = ['patch']
message_count = 8.0
messages = ['311705', '321279', '321280', '321730', '322225', '340234', '340603', '358806']
nosy_count = 10.0
nosy_names = ['terry.reedy', 'teoliphant', 'vinay.sajip', 'amaury.forgeotdarc', 'belopolsky', 'aerojockey', 'skrah', 'meador.inge', 'mattip', 'Eric.Wieser']
pr_nums = ['5561']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32780'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-101587

**Comment by eric-wieser** [comment]
@vsajip, perhaps you're qualified to review this given your work in #16589?

**Comment by vsajip** [comment]
I don't think I'm especially qualified to review this, unfortunately. I did work on some `ctypes` issues in the past, but they've required altogether too much time than I have available at the moment :disappointed: Perhaps one of the other committers who works closer to the C code level would be more appropriate (most of my work is at the Python stdlib level, though I can program in C).

**Comment by eric-wieser** [comment]
Thanks for the response.

Do you have any specific committers in mind?

I guess I could ping Travis, the other PEP author; but what #5561 needs is a review from someone with commit bit.

**Comment by vsajip** [comment]
Sadly, `ctypes`-related expertise is thin on the ground, even among committers. I've had to revert a change that I made which I thought would improve things, but didn't. One problem we all have is that any fix has to work across many architectures, and most of us don't have access to those architectures to check fixes, diagnose problems etc. You could maybe use `git blame` to throw up some possibilities.

**Comment by eric-wieser** [comment]
> Sadly, ctypes-related expertise is thin on the ground, even among committers.

Yes, I've noticed that too. PEP3118 expertise seems even more sparse, with my impression being that numpy developers are more familiar with it that CPython ones. Is there anything I could do to this issue or PR to make it more accessible to reviewers who are familiar with the C code but not with ctypes?

> One problem we all have is that any fix has to work across many architectures

My claim is that this particular fix shouldn't change any architecture-specific behavior; the logic for laying out the ctypes fields in memory hasn't changed; all that's changed is the PEP3118 reporting of the layout that was used.
The existing reporting behavior is wrong for any struct with any padding on every architecture, so no regression regarding PEP3118 should be possible.

**Comment by vsajip** [comment]
Sure. I was only giving my perceived reason as to why core developers don't have familiarity with `ctypes` internals - it seems to be outside most people's comfort zone :disappointed:

**Comment by abalkin** [comment]
@eric-wieser - it looks like I dropped the ball on this quite some time ago.  I will see it through this time.  Feel free to bug me here if I don't. :)

**Comment by eric-wieser** [comment]
@abalkin :bug:
