### ISSUE TITLE
memoryview & ctypes: incorrect itemsize for empty array

### ISSUE THREAD

**Issue by f72d0bc0-f319-4dd9-9db4-d64615e4a426** [python/cpython#76963]
BPO | [32782](https://bugs.python.org/issue32782)
--- | :---
Nosy | @terryjreedy, @amauryfa, @abalkin, @skrah, @meadori, @eric-wieser
PRs | <li>python/cpython#5576</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-06.18:53:21.025>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9', '3.10', 'ctypes']
title = 'memoryview & ctypes: incorrect itemsize for empty array'
updated_at = <Date 2020-05-23.15:47:49.464>
user = 'https://github.com/eric-wieser'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-23.15:47:49.464>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'ctypes']
creation = <Date 2018-02-06.18:53:21.025>
creator = 'Eric.Wieser'
dependencies = []
files = []
hgrepos = []
issue_num = 32782
keywords = ['patch']
message_count = 9.0
messages = ['311740', '321290', '324705', '340230', '340231', '340232', '340235', '340236', '348004']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'teoliphant', 'amaury.forgeotdarc', 'belopolsky', 'skrah', 'meador.inge', 'Eric.Wieser', 'Eric Wieser']
pr_nums = ['5576']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32782'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-100451
* gh-100452

**Comment by mattip** [comment]
Thanks for the fix that closed this. @eric-wieser do you remember where this impacted NumPy? I don't see the relevant issue or PR.

**Comment by eric-wieser** [comment]
I think the workaround in numpy needs to stay till after https://github.com/python/cpython/pull/5561

**Comment by eric-wieser** [comment]
The reference in numpy is here:

https://github.com/numpy/numpy/blob/85b26f4afc6e98694eab7a6d6abefbd3fed31fde/numpy/core/_dtype_ctypes.py#L21
