### ISSUE TITLE
<class 'contextlib._GeneratorContextManager'> returned a result with an error set

### ISSUE THREAD

**Issue by 3a02f226-0e25-4f0d-a7cb-79d66a1c129e** [python/cpython#76980]
BPO | [32799](https://bugs.python.org/issue32799)
--- | :---
Nosy | @serhiy-storchaka, @zhangyangyu
Files | <li>[Screen Shot 2018-02-08 at 8.28.00 AM.png](https://bugs.python.org/file47430/Screen%20Shot%202018-02-08%20at%208.28.00%20AM.png "Uploaded as image/png at 2018-02-08.15:28:27 by EliRibble"): Screencapture of error details in sentry</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-08.15:28:27.829>
labels = ['type-bug', 'library']
title = "<class 'contextlib._GeneratorContextManager'> returned a result with an error set"
updated_at = <Date 2018-04-21.07:55:23.880>
user = 'https://bugs.python.org/EliRibble'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-21.07:55:23.880>
actor = 'xiang.zhang'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-02-08.15:28:27.829>
creator = 'EliRibble'
dependencies = []
files = ['47430']
hgrepos = []
issue_num = 32799
keywords = []
message_count = 6.0
messages = ['311836', '311840', '311851', '313861', '313914', '315556']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'xiang.zhang', 'EliRibble']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32799'
versions = ['Python 2.7', 'Python 3.6']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 2.7.5 is not supported. Create a new issue with reproduce if this happens on supported Python versions.
