### ISSUE TITLE
Lib/_strptime.py: utilize all()

### ISSUE THREAD

**Issue by 3df6ae73-569b-4443-965f-dc5a4d7efcd7** [python/cpython#76982]
BPO | [32801](https://bugs.python.org/issue32801)
--- | :---
Nosy | @terryjreedy, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-08.16:09:49.425>
labels = ['3.8', 'library', 'performance']
title = 'Lib/_strptime.py: utilize all()'
updated_at = <Date 2018-02-11.23:49:45.830>
user = 'https://bugs.python.org/dilyanpalauzov'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-11.23:49:45.830>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-02-08.16:09:49.425>
creator = 'dilyan.palauzov'
dependencies = []
files = []
hgrepos = []
issue_num = 32801
keywords = []
message_count = 7.0
messages = ['311838', '311935', '311941', '311965', '312016', '312022', '312024']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'dilyan.palauzov', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue32801'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Does this really make a performance difference?

**Comment by iritkatriel** [comment]
Unless I'm doing something wrong, using all is actually slower:

```
import timeit
def f(arr):
    return all(value == '' for value in arr)

def g(arr):
    for value in arr:
        if value != '':
            return False
    return True

to_convert = ["" for i in range(50)]

for i in range(4):
    print('using all:\n', timeit.repeat("f(to_convert)", globals=globals()))
    print('using loop:\n', timeit.repeat("g(to_convert)", globals=globals()))
```

Output is:

```
using all:
 [2.213046186021529, 2.232533715025056, 2.2169260369846597, 2.2289347060141154, 2.2146765519864857]
using loop:
 [0.6719765960006043, 0.6848869349923916, 0.662735627964139, 0.7106767409713939, 0.7292826549964957]
```

**Comment by iritkatriel** [comment]
I'll repurpose this issue to investigate the performance of all and any.

**Comment by zware** [comment]
As @serhiy-storchaka suggested, `not any(to_convert)` would actually be the way to go here:

```
In [4]: def with_all(a):
   ...:     if all(value == '' for value in a):
   ...:         return ''
   ...:     return 'something else'
   ...:

In [5]: def as_is(a):
   ...:     for value in a:
   ...:         if value != '':
   ...:             break
   ...:     else:
   ...:         return ''
   ...:     return 'something else'
   ...:

In [6]: def with_any(a):
   ...:     if not any(a):
   ...:         return ''
   ...:     return 'something else'
   ...:

In [7]: a = [''] * 50

In [9]: %timeit with_all(a)
2.04 µs ± 24.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [10]: %timeit with_any(a)
343 ns ± 3.72 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [11]: %timeit as_is(a)
1.18 µs ± 16.1 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [12]: a = ['', '', '', 'yep', 'nope'] * 10

In [13]: %timeit with_all(a)
424 ns ± 6.47 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)

In [14]: %timeit with_any(a)
120 ns ± 2.79 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)

In [15]: %timeit as_is(a)
169 ns ± 2.35 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
```

It's not that `all` is slow, it's just not the right fit here because we're doing an additional comparison against `''` in a generator expression, which requires a lot of unnecessary setup and computation.

All that said, the original code in `_strptime` is not optimal.  I'm not convinced that matters: its performance is not terrible, it's not incorrect, and it's hardly ever actually used anyway since it's only used by the Python version of `datetime.datetime.strptime`.

I don't think there's anything worth changing here.

**Comment by iritkatriel** [comment]
Maybe we can make all faster though?

**Comment by zware** [comment]
How?  It's already in C and already short-circuits when allowed to.  The slow part of `all(v == '' for v in a)` is not `all`, it's setting up and iterating the genexp and comparing against `''`.

Here's the entire implementation of `all` (minus argument parsing, which is in Argument Clinic):

https://github.com/python/cpython/blob/cfaa79aac088284c1eeacddc19ddebe06b55dcf7/Python/bltinmodule.c#L310-L346

I don't see anything we can trim from that, nor anything specific to `all` that can be optimized.  I'm certainly not an expert in C or optimization though, and would be happy to be proven wrong :)

**Comment by iritkatriel** [comment]
When is all faster than a simple loop?

**Comment by iritkatriel** [comment]
Ok, I see I'm asking the wrong question - it's not all which is slow but the way it gets its input.
