### ISSUE TITLE
Expose ags_gen and agt_gen in asynchronous generators

### ISSUE THREAD

**Issue by 0d6a79a7-4e74-41c2-8eed-8d04ea475e57** [python/cpython#76991]
BPO | [32810](https://bugs.python.org/issue32810)
--- | :---
Nosy | @giampaolo, @yarko, @njsmith, @asvetlov, @1st1, @xgid, @ZackerySpytz, @oremanj, @GeeTransit
PRs | <li>python/cpython#11166</li>
Files | <li>[agen.py](https://bugs.python.org/file47434/agen.py "Uploaded as text/plain at 2018-02-10.13:29:06 by dabeaz")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-01-02.02:42:35.810>
created_at = <Date 2018-02-09.19:49:33.075>
labels = ['type-feature', '3.8', 'expert-asyncio']
title = 'Expose ags_gen and agt_gen in asynchronous generators'
updated_at = <Date 2021-01-02.02:42:35.810>
user = 'https://bugs.python.org/dabeaz'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-02.02:42:35.810>
actor = 'dabeaz'
assignee = 'none'
closed = True
closed_date = <Date 2021-01-02.02:42:35.810>
closer = 'dabeaz'
components = ['asyncio']
creation = <Date 2018-02-09.19:49:33.075>
creator = 'dabeaz'
dependencies = []
files = ['47434']
hgrepos = []
issue_num = 32810
keywords = ['patch']
message_count = 7.0
messages = ['311906', '311946', '311950', '331860', '331903', '335376', '349266']
nosy_count = 11.0
nosy_names = ['kdart', 'giampaolo.rodola', 'yarkot', 'njs', 'asvetlov', 'dabeaz', 'yselivanov', 'xgdomingo', 'ZackerySpytz', 'Joshua Oreman', 'GeeTransit']
pr_nums = ['11166']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32810'
versions = ['Python 3.8']
```

</p></details>

**Comment by VincentVanlaer** [comment]
This issue seems to have been closed by accident. There associated PR is still open and there is currently no clean way to access the generator. The workaround using `gc.get_referents` works though.

**Comment by erlend-aasland** [comment]
cc. @1st1

**Comment by gvanrossum** [comment]
@erlend-aasland What's going on here? @1st1 is unlikely to react. The PR suddenly gets action. (By you? By the OP?) Maybe you want to reopen this issue? (The last comment suggests it should be reopened.)

**Comment by erlend-aasland** [comment]
@gvanrossum: I did an audit of all open issues and PRs by `@ZackerySpytz` earlier today. The linked PR (#11166, authored by Zackery) was still open, and this issue seemed to have been closed by accident, hence the ping.

**Comment by gvanrossum** [comment]
Yeah, @1st1 really won't look at this, so we need someone else to do so. I'll reopen it so at least it's clear that this was closed by mistake.
