### ISSUE TITLE
Docs: Using Python on a Macintosh has bad info per Apple site

### ISSUE THREAD

**Issue by 25777705-5344-4b7a-a27d-502a58bb7384** [python/cpython#77005]
BPO | [32824](https://bugs.python.org/issue32824)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @remilapeyre, @tomy0000000

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2018-02-11.23:42:34.211>
labels = ['OS-mac', '3.9', '3.10', '3.11', 'type-feature', 'docs']
title = 'Docs: Using Python on a Macintosh has bad info per Apple site'
updated_at = <Date 2021-04-29.13:39:59.899>
user = 'https://bugs.python.org/griswolf'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-29.13:39:59.899>
actor = 'Old Sub Sailor'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'macOS']
creation = <Date 2018-02-11.23:42:34.211>
creator = 'griswolf'
dependencies = []
files = []
hgrepos = []
issue_num = 32824
keywords = []
message_count = 8.0
messages = ['312023', '312028', '368542', '368545', '368548', '368558', '392259', '392307']
nosy_count = 8.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'griswolf', 'docs@python', 'Old Sub Sailor', 'remi.lapeyre', 'TotallyLost', 'tomy0000000']
pr_nums = []
priority = 'high'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32824'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by soegaard** [comment]
A start would be to remove the sentence:

"See Apple’s Technical Document QA1067 for details."

Since as @griswold points out, you are met with the sentece:

> Note: Legacy Document
>
> This document is part of the Legacy section of the ADC Reference Library. This information should not be used for new development.

**Comment by ned-deily** [comment]
Thanks again for the report. After a very long delay, the [macOS section](https://docs.python.org/3.13/using/mac.html) of the [Python Setup and Usage](https://docs.python.org/3.13/using/index.html) document has undergone an extensive rewrite and expansion for the upcoming Python 3.13 release. Among other changes, the problematic legacy section about attempting to tailor environment variables when launching Python through the Finder has been removed.
