### ISSUE TITLE
[os] pipe() creates inheritable FDs with a bad internal state in Windows

### ISSUE THREAD

**Issue by eryksun** [python/cpython#77046]
BPO | [32865](https://bugs.python.org/issue32865)
--- | :---
Nosy | @pfmoore, @tjguk, @njsmith, @zware, @eryksun, @zooba, @izbyshev
PRs | <li>python/cpython#13739</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-17.15:51:54.875>
labels = ['type-bug', '3.8', '3.9', 'expert-IO', 'extension-modules', '3.10', 'OS-windows']
title = 'os.pipe  creates inheritable FDs with a bad internal state on Windows'
updated_at = <Date 2021-03-20.14:32:47.251>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-20.14:32:47.251>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Windows', 'IO']
creation = <Date 2018-02-17.15:51:54.875>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 32865
keywords = ['patch']
message_count = 4.0
messages = ['312283', '312294', '312297', '312300']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'njs', 'zach.ware', 'eryksun', 'steve.dower', 'izbyshev']
pr_nums = ['13739']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32865'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-113817

**Comment by vstinner** [comment]
I can reproduce the os.spawnl() issue.

Script ``x.py``:

```py
import os
import msvcrt
import sys
import time

rfd, wfd = os.pipe()
print("FDs", rfd, wfd)

rhandle = msvcrt.get_osfhandle(rfd)
whandle = msvcrt.get_osfhandle(wfd)
print("handles", rhandle, whandle)

print("FDs inheritable?",
      os.get_inheritable(rfd),
      os.get_inheritable(wfd))
print("handles inheritable?",
      os.get_handle_inheritable(rhandle),
      os.get_handle_inheritable(whandle))

cmd = [sys.executable, "y.py", str(rfd), str(wfd), str(rhandle), str(whandle)]
if 0:
    import subprocess
    proc = subprocess.run(cmd, close_fds=False)
    print("run =>", proc)
else:
    res = os.spawnl(os.P_WAIT, cmd[0], *cmd)
    time.sleep(1)
    print("spawnl =>", res)
```

Script ``y.py``:

```py
import os
import msvcrt
import sys

rfd = int(sys.argv[1])
wfd = int(sys.argv[2])
print("child: FDs", rfd, wfd)

rhandle = int(sys.argv[3])
whandle = int(sys.argv[4])
print("child: handles", rhandle, whandle)

def get_inheritable(fd):
    try:
        return os.get_inheritable(fd)
    except OSError as exc:
        return f"<error: {exc}>"

def get_handle_inheritable(handle):
    try:
        return os.get_handle_inheritable(handle)
    except OSError as exc:
        return f"<error: {exc}>"

print("child: FDs inheritable?",
      get_inheritable(rfd),
      get_inheritable(wfd))
print("child: handles inheritable?",
      get_handle_inheritable(rhandle),
      get_handle_inheritable(whandle))
```

---

Using os.spawnl(), I get:

```
FDs 3 4
handles 348 356
FDs inheritable? False False
handles inheritable? False False

child: FDs 3 4
child: handles 348 356
child: FDs inheritable? <error: [WinError 6] The handle is invalid> <error: [WinError 6] The handle is invalid>
child: handles inheritable? <error: [WinError 6] The handle is invalid> <error: [WinError 6] The handle is invalid>

spawnl => 0
```

But I get different results if I rerun the script!?

```
child: FDs inheritable? False <error: [WinError 6] The handle is invalid>
child: handles inheritable? False <error: [WinError 6] The handle is invalid>
```

The "read" FD and handle are "inherited"?

New run:

```
child: FDs inheritable? False False
child: handles inheritable? False False
```

Here the two FDs and the two handles are inherited?

---

Using subprocess.run(close_fds=False), I get:

```
FDs 3 4
handles 348 356
FDs inheritable? False False
handles inheritable? False False

child: FDs 3 4
child: handles 348 356
child: FDs inheritable? <error: [Errno 9] Bad file descriptor> <error: [Errno 9] Bad file descriptor>
child: handles inheritable? <error: [WinError 6] The handle is invalid> <error: [WinError 6] The handle is invalid>

run => CompletedProcess(args=['C:\\victor\\python\\main\\PCbuild\\amd64\\python_d.exe', 'y.py', '3', '4', '348', '356'], returncode=0)
```

The problem is that I get different results for ``child: handles inheritable?`` when using subprocess.run(close_fds=False) if I run the script multiple times!?

```
child: handles inheritable? <error: [WinError 6] The handle is invalid> <error: [WinError 6] The handle is invalid>

child: handles inheritable? False False
```

Sometimes, non-inheritable handles are inherited, sometimes not. Maybe it's just that the child process creates **new** handles which by luck get the same value?

**Comment by zooba** [comment]
Having a look at the UCRT source code (included in the Windows SDK, so it's public), it's possible this is a bug where the handles that are inherited are counted like this:

```c
        // Count the number of handles to be inherited:
        size_t handle_count = 0;
        for (handle_count = _nhandle; handle_count != 0 && _osfile(handle_count - 1) != 0; --handle_count)
        {
        }
```

`_osfile(fd)` is the flags value, so if the last few FDs are pipes (`FPIPE`) they'll be ignored, but if there's a regular file later in the array they'll be included (unless the file has `FAPPEND` or `FTEXT` or another flag).

Maybe try opening another file after creating the pipe and seeing if that makes things stable?

**Comment by erlend-aasland** [comment]
Possibly superseded by #74740?

**Comment by zooba** [comment]
> Possibly superseded...

I don't think so. This one relates to weird `spawnl` behaviour, which wasn't involved in the other issue.

**Comment by erlend-aasland** [comment]
Right; so perhaps I was a little bit too eager when I closed the linked PR.

**Comment by zooba** [comment]
Or maybe you're right... this is a very confusing issue, which is likely why it's sat open for so long.

Though when you point at a PR that was merged in 2017 as having fixed an issue that was reported in 2018 (and replicated in 2022? Maybe?), it probably means we need to understand the timelines better.

**Comment by erlend-aasland** [comment]
- 2017-06-02, issue created: #74740
- 2017-06-03, PR for `#74740` created: #1927
- 2018-02-17, issue created: #77046
- 2019-06-02, PR for `#77046` created: #13739
- 2021-04-24, PR for `#77046` (`#13739`) merged

**Comment by zooba** [comment]
> AFAICS, #1927 made #13739 moot.

It may have done for the console handles, but I think `os.pipe` still needs to pass the `_O_NOINHERIT` flag (or make the pipe handles inheritable). I'm not sure whether that _fixes_ the spawn issue, but it probably needs to be done anyway.

**Comment by vstinner** [comment]
@eryksun:
> The CRT has no public functions to query and modify the heritability of existing FDs.

I confirm that it's still the case today.

I checked the source code of UCRT version 10.0.19041.0 (``C:\Program Files (x86)\Windows Kits\10\Source\10.0.19041.0`` and ``C:\Program Files (x86)\Windows Kits\10\Include\10.0.19041.0``): I failed to find any public function which returns `_osfile(fd)`. Moreover, the `_osfile()` macro and `struct __crt_lowio_handle_data` are not exported in the public header file, but only in the internal `corecrt_internal_lowio.h` header (``C:\Program Files (x86)\Windows Kits\10\Source\10.0.19041.0\ucrt\inc``).

**Comment by vstinner** [comment]
If an application calls `os.pipe()` and then `os.spawnl()`, trying to use the pipe file descriptors in the child process can crash the process with `EXCEPTION_ACCESS_VIOLATION` :-(

Example of script `crash.py`:

```py
import os
import sys
import textwrap

fd, fd2 = os.pipe()
print(f"parent: fd={fd} fd2={fd2}")

if 1:
    # os.dup() does crash
    code = textwrap.dedent(f"""
        import os
        fd = {fd}
        print(f"child: dup {{fd}}")
        fd3 = os.dup(fd)
        print(f"child: dup {{fd}} -> {{fd3}}")
        os.close(fd3)
    """)
else:
    # _open_osfhandle() raises OSError(EBADF)
    code = textwrap.dedent(f"""
        import os
        import msvcrt
        fd = {fd}
        print(f"child: _open_osfhandle({{fd}})")
        try:
            handle = msvcrt.open_osfhandle(fd, os.O_RDONLY)
        except OSError as exc:
            handle = f"<error: {{exc!r}}>"
        print(f"child: _open_osfhandle({{fd}}) -> {{handle}}")
    """)

filename = "crash_script.py"
with open(filename, "w") as fp:
    print(code, file=fp, end="")

cmd = [sys.executable, filename]
exitcode = os.spawnl(os.P_WAIT, cmd[0], *cmd)
if exitcode == -1073741819:
    exitcode = f"{exitcode} (EXCEPTION_ACCESS_VIOLATION)"
print(f"os.spawnl() => {exitcode}")
```

Sometimes, the script goes well:

```
vstinner@WIN C:\victor\python\main>python crash.py
Running Debug|x64 interpreter...
parent: fd=3 fd2=4
child: dup 3
child: dup 3 -> 5
os.spawnl() => 0
```

Sometimes, the child process crash with EXCEPTION_ACCESS_VIOLATION:

```
Running Debug|x64 interpreter...
parent: fd=3 fd2=4
child: dup 3
os.spawnl() => -1073741819 (EXCEPTION_ACCESS_VIOLATION)
```

Calling `os.dup()` crash randomly, whereas `msvcrt.open_osfhandle()` always raises `OSError(EBADF)` (does not crash).

**Comment by zooba** [comment]
> If an application calls `os.pipe()` and then `os.spawnl()`, trying to use the pipe file descriptors in the child process can crash the process with `EXCEPTION_ACCESS_VIOLATION`

Can you see if this repros when the `NOINHERIT` flag is added, as proposed? I expect it'll go away

**Comment by zooba** [comment]
> Well, I wanted to "fix" os.get_inheritable/set_inheritable() to get/set the UCRT flag. It doesn't seem possible. The best we can do is to be more specific in os.get_inheritable/set_inheritable() documentation that only the status of the **handle** is used, not the state of the **file descriptor** which _can_ be inconsistent (but _should not_ for FDs created by the Python stdlib).

Ah yeah, I see what you mean.[^1] I guess we can recommend `msvcrt.open_osfhandle` in this case? Probably needs a `dup_as_inheritable` function, but I also haven't heard of it actually coming up before, so I'm not sure how important it is?

Do people normally do `os.pipe` and then immediately make one end inheritable? 

[^1]: I hate file descriptors 🙃

**Comment by vstinner** [comment]
> Probably needs a dup_as_inheritable function

What would be the use case to make os.pipe() file descriptors inheritable on Windows? If you use them between threads, Python interpreters or whatever inside the same process, it's not an issue that they cannot be inherited by child processes.

On Unix, to inherit file descriptors in child processes, since file descriptors are not inheritable by default, you should already use `pass_fds=[fd]` of `subprocess`. It makes sure that *fd* is made inheritable when passed to the child process.  

On Windows, the `subprocess` module doesn't support inheriting file descriptors: you should pass handles to `startupinfo.lpAttributeList['handle_list']`, and then create new file descriptors in the child process. Only `os.spawnl()` indirectly uses the dark secrets of CreateProcess() (see my previous comment about `lpReserved2`) to inherit file descriptors.

Note: `os.dup2()` has an optional `inheritable=True` parameter.

**Comment by zooba** [comment]
> Note: `os.dup2()` has an optional `inheritable=True` parameter.

So it does, but it just calls `_Py_set_inheritable` if you pass False (True is the default), and leaves you with the same inconsistent state. That can probably be a new bug to fix, I guess, if anyone ever notices (at least if we're uninheritable by default and then dup2 makes it inheritable, I don't know why you'd need to go back?)

**Comment by vstinner** [comment]
Fixed by commit https://github.com/python/cpython/commit/1d75fa43a25e5f3c33f2aaaec28fab9430834792.

@eryksun: If you consider that `os.spawnl()` must no longer inherit file descriptors on Windows, please open a separated issue. IMO it's a different topic.

**Comment by vstinner** [comment]
I no longer think that the change should be backport to stable 3.11 and 3.12 branches. The change is too subtle, and the issue sounds more hypothetical than a real practical bug.
