### ISSUE TITLE
ApplePersistenceIgnoreState warning on macOS

### ISSUE THREAD

**Issue by ca111b7b-6cb6-49d6-ae38-df0448340717** [python/cpython#77090]
BPO | [32909](https://bugs.python.org/issue32909)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @@cbrnr

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-02-22.10:55:16.157>
labels = ['OS-mac', 'type-bug']
title = 'ApplePersistenceIgnoreState warning on macOS'
updated_at = <Date 2018-02-23.08:23:45.640>
user = 'https://github.com/cbrnr'
```

bugs.python.org fields:
```python
activity = <Date 2018-02-23.08:23:45.640>
actor = 'ronaldoussoren'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2018-02-22.10:55:16.157>
creator = 'cbrnr'
dependencies = []
files = []
hgrepos = []
issue_num = 32909
keywords = []
message_count = 3.0
messages = ['312550', '312590', '312621']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'cbrnr']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue32909'
versions = ['Python 3.6']
```

</p></details>

**Comment by ronaldoussoren** [comment]
There's nothing we can do to suppress these warnings that wouldn't cause problems on other scenarios (e.g. setting ``ApplePersistenceIgnoreState`` breaks GUI libraries that do want to store state). 

I'm therefore closing this issue.

**Comment by aivarannamaa** [comment]
In macOS 10.15 this warning appears when running a tkinter program from command line with Python 3.13 (or 3.12), but does not appear when running the same program from IDLE.

What could be the reason for this difference?
