### ISSUE TITLE
Supporting extensible format(PCM) for wave.open(read-mode)

### ISSUE THREAD

**Issue by 5496b8dc-4c9c-457a-b295-4091c7500ad2** [python/cpython#77171]
BPO | [32990](https://bugs.python.org/issue32990)
--- | :---
Nosy | @ned-deily, @serhiy-storchaka, @ZackerySpytz, @acelletti
PRs | <li>python/cpython#9515</li>
Files | <li>[pluck-pcm24-ext.wav](https://bugs.python.org/file47467/pluck-pcm24-ext.wav "Uploaded as audio/wav at 2018-03-03.09:25:58 by @acelletti"): PCM 24b with FORMAT_EXTENSIBLE</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-03-03.09:25:58.701>
labels = ['3.8', 'type-feature', 'library']
title = 'Supporting extensible format(PCM) for wave.open(read-mode)'
updated_at = <Date 2018-09-23.13:35:55.962>
user = 'https://github.com/acelletti'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-23.13:35:55.962>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-03-03.09:25:58.701>
creator = 'acelletti'
dependencies = []
files = ['47467']
hgrepos = []
issue_num = 32990
keywords = ['patch']
message_count = 4.0
messages = ['313183', '313190', '313191', '325477']
nosy_count = 4.0
nosy_names = ['ned.deily', 'serhiy.storchaka', 'ZackerySpytz', 'acelletti']
pr_nums = ['9515']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue32990'
versions = ['Python 3.8']
```

</p></details>

**Comment by zooba** [comment]
Reopening this to update docs to limit our support to only PCM files.
