### ISSUE TITLE
Bdb doesn't find instruction in linecache after pdb.set_trace() following os.chdir("/tmp")

### ISSUE THREAD

**Issue by 4e0d4d83-252b-4267-9247-cc4185ed8bc1** [python/cpython#77320]
BPO | [33139](https://bugs.python.org/issue33139)
--- | :---
Nosy | @tirkarthi
Files | <li>[testpdb.py](https://bugs.python.org/file47498/testpdb.py "Uploaded as text/plain at 2018-03-25.21:10:26 by prounce"): testpdb.py is test  program to generate fault after 2nd pdb.set_trace()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-03-25.21:10:27.185>
labels = ['3.8', 'type-bug', 'library']
title = 'Bdb doesn\'t find instruction in linecache after pdb.set_trace() following os.chdir("/tmp")'
updated_at = <Date 2018-07-25.12:47:35.906>
user = 'https://bugs.python.org/prounce'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-25.12:47:35.906>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-03-25.21:10:27.185>
creator = 'prounce'
dependencies = []
files = ['47498']
hgrepos = []
issue_num = 33139
keywords = []
message_count = 2.0
messages = ['314435', '322350']
nosy_count = 2.0
nosy_names = ['prounce', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33139'
versions = ['Python 3.8']
```

</p></details>

**Comment by gaogaotiantian** [comment]
This is not an issue anymore because in `self.canonic(frame.f_code.co_filename)`, `co_filename` is an absolute path now, thus `os.chdir` won't affect the file search.
