### ISSUE TITLE
subprocess.Popen ResourceWarning should have activation-deactivation flags

### ISSUE THREAD

**Issue by 3f92f909-2ab1-4c59-a97d-5b60331bb97d** [python/cpython#77335]
BPO | [33154](https://bugs.python.org/issue33154)
--- | :---
Nosy | @pitrou, @vstinner, @vadmium, @serhiy-storchaka, @ArnoCan
Files | <li>[python3-output.txt](https://bugs.python.org/file47502/python3-output.txt "Uploaded as text/plain at 2018-03-27.10:54:43 by @ArnoCan"): output of warnings during unittest of command line tool by stderr</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-03-27.10:54:43.666>
labels = ['library', 'performance']
title = 'subprocess.Popen ResourceWarning should have activation-deactivation flags'
updated_at = <Date 2018-07-22.08:30:40.136>
user = 'https://github.com/ArnoCan'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-22.08:30:40.136>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-03-27.10:54:43.666>
creator = 'acue'
dependencies = []
files = ['47502']
hgrepos = []
issue_num = 33154
keywords = []
message_count = 3.0
messages = ['314511', '314513', '322136']
nosy_count = 6.0
nosy_names = ['pitrou', 'vstinner', 'python-dev', 'martin.panter', 'serhiy.storchaka', 'acue']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue33154'
versions = ['Python 3.6']
```

</p></details>

**Comment by iritkatriel** [comment]
I agree with @vadmium . The default should remain on, and you have a way to disable warnings if you need to.
