### ISSUE TITLE
multiprocessing: serialization must ensure that contexts are compatible (the same)

### ISSUE THREAD

**Issue by 69d2e7fa-119a-4360-858f-934e2ab9fb33** [python/cpython#77377]
BPO | [33196](https://bugs.python.org/issue33196)
--- | :---
Nosy | @pitrou, @vstinner, @taleinat, @applio, @arcivanov, @augustogoulart
Files | <li>[test_lock_sigsegv.py](https://bugs.python.org/file47510/test_lock_sigsegv.py "Uploaded as text/plain at 2018-04-01.05:58:10 by @arcivanov")</li><li>[testing_on_fedora.png](https://bugs.python.org/file47931/testing_on_fedora.png "Uploaded as image/png at 2018-11-13.14:22:01 by @augustogoulart")</li><li>[coredump](https://bugs.python.org/file47933/coredump "Uploaded as application/octet-stream at 2018-11-14.09:31:13 by @arcivanov"): coredump (Fedora 29)</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-01.05:58:11.085>
labels = ['3.8', '3.7', 'library', 'type-crash']
title = 'multiprocessing: serialization must ensure that contexts are compatible (the same)'
updated_at = <Date 2018-11-14.17:28:52.507>
user = 'https://github.com/arcivanov'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-14.17:28:52.507>
actor = 'davin'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-04-01.05:58:11.085>
creator = 'arcivanov'
dependencies = []
files = ['47510', '47931', '47933']
hgrepos = []
issue_num = 33196
keywords = []
message_count = 11.0
messages = ['314762', '314792', '329491', '329719', '329845', '329892', '329893', '329898', '329908', '329909', '329913']
nosy_count = 6.0
nosy_names = ['pitrou', 'vstinner', 'taleinat', 'davin', 'arcivanov', 'augustogoulart']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue33196'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-107275
* gh-108377
* gh-108378

**Comment by albanD** [comment]
cc @vstinner I sent a PR for this, are you the right person to review it?

**Comment by vstinner** [comment]
@albanD:
> cc @vstinner I sent a PR for this, are you the right person to review it?

I'm not available to review your PR. Maybe @pitrou can review it.

**Comment by terryjreedy** [comment]
Patch apparently caused regression for nested multiprocessing calls in 11.5. #108520
