### ISSUE TITLE
test_posix fails ERRNO 0

### ISSUE THREAD

**Issue by a7c16cf0-2fb5-4e76-9ec0-bbe2e409b5bf** [python/cpython#77404]
BPO | [33223](https://bugs.python.org/issue33223)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @nitishch, @wizofe

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-04.14:13:39.829>
labels = ['OS-mac', '3.8', 'ctypes', '3.7', 'tests']
title = 'test_posix fails ERRNO 0'
updated_at = <Date 2019-06-13.07:49:03.623>
user = 'https://github.com/wizofe'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-13.07:49:03.623>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Tests', 'ctypes']
creation = <Date 2018-04-04.14:13:39.829>
creator = 'wizofe'
dependencies = []
files = []
hgrepos = []
issue_num = 33223
keywords = []
message_count = 5.0
messages = ['314934', '314937', '322576', '322577', '345471']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'nitishch', 'wizofe']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33223'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by ronaldoussoren** [comment]
The changes mentioned by @ned-deily mean that this issue is no longer relevant.  The code now does a retry loop when the buffer is too small. I also checked that I no longer get the error mentioned in the initial report.

I intend to close the issue unless there are good reasons to keep it open.
