### ISSUE TITLE
Add stats for asyncio task usage.

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#77402]
BPO | [33221](https://bugs.python.org/issue33221)
--- | :---
Nosy | @njsmith, @asvetlov, @1st1, @thehesiod, @achimnol

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-03.22:33:22.023>
labels = ['3.8', 'expert-asyncio']
title = 'Add stats for asyncio task usage.'
updated_at = <Date 2018-04-04.02:43:26.294>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-04.02:43:26.294>
actor = 'achimnol'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-04-03.22:33:22.023>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 33221
keywords = []
message_count = 6.0
messages = ['314905', '314907', '314908', '314909', '314910', '314913']
nosy_count = 5.0
nosy_names = ['njs', 'asvetlov', 'yselivanov', 'thehesiod', 'achimnol']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33221'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
> I plan to use contextvars module to introduce a full-blown tracing API to asyncio to selectively log events like tacks creations, event loop switching, IO done by transports etc. The plan is to prototype it in uvloop first.

Seems this was never implemented and I don't think uvloop supports tracking stats either. I don't think we have resources to implement this as the user demand is very low (no comments in last 4 years). @gvanrossum What do you think?

**Comment by gvanrossum** [comment]
Let’s study what Trio does first. The link is dead but I am sure someone could find the new location of that section easily enough.

**Comment by kumaraditya303** [comment]
https://trio.readthedocs.io/en/stable/reference-lowlevel.html#debugging-and-instrumentation is the new link I think.

**Comment by gvanrossum** [comment]
Actually it's probably this link (hazmat -> lowlevel): https://trio.readthedocs.io/en/latest/reference-lowlevel.html#instrument-api

This feels like a project for someone with a lot of time on their hands. I wonder if @1st1 ever did this in uvloop?

**Comment by kumaraditya303** [comment]
I am not into increasing `asyncio` API even more now so closing. This issue has been silent indicating that not many people care about this either.
