### ISSUE TITLE
ERROR: test_sites_no_connection_close (test.test_urllib2net.OtherNetworkTests)

### ISSUE THREAD

**Issue by methane** [python/cpython#77476]
BPO | [33295](https://bugs.python.org/issue33295)
--- | :---
Nosy | @orsenthil, @ned-deily, @methane, @berkerpeksag
PRs | <li>python/cpython#6504</li><li>python/cpython#6509</li><li>python/cpython#6510</li><li>python/cpython#6511</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-17.09:15:32.370>
labels = ['3.7', '3.8', 'type-bug', 'tests']
title = 'ERROR: test_sites_no_connection_close (test.test_urllib2net.OtherNetworkTests)'
updated_at = <Date 2018-04-17.15:39:22.800>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-17.15:39:22.800>
actor = 'berker.peksag'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2018-04-17.09:15:32.370>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 33295
keywords = ['patch']
message_count = 7.0
messages = ['315384', '315399', '315400', '315401', '315402', '315403', '315404']
nosy_count = 4.0
nosy_names = ['orsenthil', 'ned.deily', 'methane', 'berker.peksag']
pr_nums = ['6504', '6509', '6510', '6511']
priority = 'critical'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33295'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-139502

**Comment by arunsl** [comment]
Can't we just mock the response header and test this with a known url like python.org and simulate the scenario?

**Comment by vstinner** [comment]
> Can't we just mock the response header and test this with a known url like python.org and simulate the scenario?

test_urllib2net.py is for tests on real websites.

Since no solution was found since the test has been skipped in 2018, I propose https://github.com/python/cpython/pull/139502 to remove the test.
