### ISSUE TITLE
Better error handling in PyImport_Cleanup()

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#77511]
BPO | [33330](https://bugs.python.org/issue33330)
--- | :---
Nosy | @brettcannon, @ncoghlan, @pitrou, @vstinner, @ericsnowcurrently, @serhiy-storchaka, @miss-islington
PRs | <li>python/cpython#6564</li><li>python/cpython#6601</li><li>python/cpython#6604</li><li>python/cpython#6605</li><li>python/cpython#6606</li><li>python/cpython#7068</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-22.08:56:30.611>
labels = ['interpreter-core', '3.8', 'type-bug', '3.7']
title = 'Better error handling in PyImport_Cleanup()'
updated_at = <Date 2018-05-23.10:36:34.627>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-23.10:36:34.627>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-04-22.08:56:30.611>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 33330
keywords = ['patch']
message_count = 9.0
messages = ['315592', '315751', '315756', '315757', '315766', '315767', '315915', '317367', '317381']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'ncoghlan', 'pitrou', 'vstinner', 'eric.snow', 'serhiy.storchaka', 'miss-islington']
pr_nums = ['6564', '6601', '6604', '6605', '6606', '7068']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33330'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by vstinner** [comment]
I gave up on my further enhancements https://github.com/python/cpython/pull/7068#issuecomment-405396647, so I just close the issue.
