### ISSUE TITLE
Provide a supported Concrete Syntax Tree implementation in the standard library

### ISSUE THREAD

**Issue by ambv** [python/cpython#77518]
BPO | [33337](https://bugs.python.org/issue33337)
--- | :---
Nosy | @gvanrossum, @gpshead, @benjaminp, @jwilk, @edreamleo, @njsmith, @ambv, @serhiy-storchaka, @kernc, @ilevkivskyi, @ethanhs, @jimmylai, @lysnikolaou, @zsol, @NiklasRosenstein, @isidentical
PRs | <li>python/cpython#6572</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-23.01:04:07.808>
labels = ['3.8', 'library']
title = 'Provide a supported Concrete Syntax Tree implementation in the standard library'
updated_at = <Date 2021-08-10.08:31:09.247>
user = 'https://github.com/ambv'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-10.08:31:09.247>
actor = 'lukasz.langa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-04-23.01:04:07.808>
creator = 'lukasz.langa'
dependencies = []
files = []
hgrepos = []
issue_num = 33337
keywords = ['patch']
message_count = 18.0
messages = ['315638', '315642', '315646', '315647', '315648', '315649', '315678', '315680', '315681', '315682', '315683', '315686', '315704', '315759', '315760', '330924', '364062', '364096']
nosy_count = 16.0
nosy_names = ['gvanrossum', 'gregory.p.smith', 'benjamin.peterson', 'jwilk', 'edreamleo', 'njs', 'lukasz.langa', 'serhiy.storchaka', 'kernc', 'levkivskyi', 'ethan smith', 'jimmylai', 'lys.nikolaou', 'zsol', 'n_rosenstein', 'BTaskaya']
pr_nums = ['6572']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33337'
versions = ['Python 3.8']
```

</p></details>

**Comment by lysnikolaou** [comment]
Should we close this? It's 3 years later and things around the parser/tokenizer/formatters have evolved a lot since this issue was opened.

**Comment by gvanrossum** [comment]
I'm fine with closing this. If someone were to ask about this on Discourse now, what advice would you give them? "Reverse engineer what Black does" seems unsatisfactory.

**Comment by gpshead** [comment]
I'd point them at https://github.com/Instagram/LibCST aka https://pypi.org/project/libcst/.
