### ISSUE TITLE
Support compiling with clang-cl on Windows

### ISSUE THREAD

**Issue by ae9affa2-721f-411e-8014-69189ad9b6f2** [python/cpython#77532]
BPO | [33351](https://bugs.python.org/issue33351)
--- | :---
Nosy | @gpshead, @pfmoore, @tjguk, @pmp-p, @zware, @zooba, @tritium21, @ethanhs, @gvanem
PRs | <li>python/cpython#6761</li><li>python/cpython#7680</li><li>python/cpython#18371</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-25.04:36:44.115>
labels = ['build', '3.9', 'OS-windows']
title = 'Support compiling with clang-cl on Windows'
updated_at = <Date 2020-02-06.07:21:40.799>
user = 'https://github.com/ethanhs'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-06.07:21:40.799>
actor = 'isuruf'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Windows']
creation = <Date 2018-04-25.04:36:44.115>
creator = 'ethan smith'
dependencies = []
files = []
hgrepos = []
issue_num = 33351
keywords = ['patch']
message_count = 12.0
messages = ['315721', '315723', '315725', '315726', '315749', '315920', '315924', '316250', '317656', '318890', '321353', '360048']
nosy_count = 9.0
nosy_names = ['gregory.p.smith', 'paul.moore', 'tim.golden', 'pmpp', 'zach.ware', 'steve.dower', 'tritium', 'ethan smith', 'gvanem']
pr_nums = ['6761', '7680', '18371']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue33351'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-101352

**Comment by bboysnick5** [comment]
With below patch, I can compile python 3.10.5 with clang 15.


diff --git a/Include/cpython/pytime.h b/Include/cpython/pytime.h
index 754c7f4..ac47e22 100644
--- a/Include/cpython/pytime.h
+++ b/Include/cpython/pytime.h
@@ -123,6 +123,7 @@ PyAPI_FUNC(int) _PyTime_FromTimeval(_PyTime_t *tp, struct timeval *tv);
    tv_usec is always positive.
    Raise an exception and return -1 if the conversion overflowed,
    return 0 on success. */
+struct timeval;
 PyAPI_FUNC(int) _PyTime_AsTimeval(_PyTime_t t,
     struct timeval *tv,
     _PyTime_round_t round);
diff --git a/Modules/_tracemalloc.c b/Modules/_tracemalloc.c
index ba0eb73..46dfd83 100644
--- a/Modules/_tracemalloc.c
+++ b/Modules/_tracemalloc.c
@@ -52,11 +52,11 @@ static PyThread_type_lock tables_lock;
 
 /* Pack the frame_t structure to reduce the memory footprint on 64-bit
    architectures: 12 bytes instead of 16. */
-typedef struct
 #ifdef __GNUC__
-__attribute__((packed))
+typedef struct __attribute__((packed))
 #elif defined(_MSC_VER)
 #pragma pack(push, 4)
+typedef struct
 #endif
 {
     /* filename cannot be NULL: "<unknown>" is used if the Python frame
diff --git a/PC/pyconfig.h b/PC/pyconfig.h
index 9fe9b30..b65e76e 100644
--- a/PC/pyconfig.h
+++ b/PC/pyconfig.h
@@ -102,7 +102,7 @@ WIN32 is still required for the locale module.
  * "1200"
  */
 #define _Py_STRINGIZE(X) _Py_STRINGIZE1((X))
-#define _Py_STRINGIZE1(X) _Py_STRINGIZE2 ## X
+#define _Py_STRINGIZE1(X) _Py_STRINGIZE2 X
 #define _Py_STRINGIZE2(X) #X
 
 /* MSVC defines _WINxx to differentiate the windows platform types

**Comment by zooba** [comment]
I wanted this, so I applied my own patch. It also suppresses a lot of uninteresting warnings, fixes a few changes since the last patch was posted here, and enables LTO on release builds.

No doubt we'll have another one of these issues in the future, but for now, I'll consider this closed.
