### ISSUE TITLE
WinError 10038 is raised when loop.sock_connect is wrapped with asyncio.wait_for

### ISSUE THREAD

**Issue by eb89c512-3e06-417b-8d64-4af79cecb784** [python/cpython#77531]
BPO | [33350](https://bugs.python.org/issue33350)
--- | :---
Nosy | @asvetlov, @1st1, @yjqiang
Files | <li>[test.py](https://bugs.python.org/file47548/test.py "Uploaded as text/plain at 2018-04-24.16:51:15 by Alisue Lambda"): A minimal script to reproduce the issue on Windows 10 Pro</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-24.16:51:15.973>
labels = ['type-bug', 'expert-asyncio']
title = 'WinError 10038 is raised when loop.sock_connect is wrapped with asyncio.wait_for'
updated_at = <Date 2019-05-08.02:50:26.588>
user = 'https://bugs.python.org/AlisueLambda'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-08.02:50:26.588>
actor = 'yjqiang'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-04-24.16:51:15.973>
creator = 'Alisue Lambda'
dependencies = []
files = ['47548']
hgrepos = []
issue_num = 33350
keywords = []
message_count = 8.0
messages = ['315707', '315708', '315709', '323238', '332649', '332650', '337905', '341847']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'Alisue Lambda', 'yjqiang']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33350'
versions = ['Python 3.6']
```

</p></details>

**Comment by kumaraditya303** [comment]
I am unable to reproduce the reported `OSError`. It only raises `TimeoutError` since it cannot connect.

**Comment by kumaraditya303** [comment]
Create a new if this happens on supported Python versions. `asyncio.wait_for` has been changed a lot since this was reported.
