### ISSUE TITLE
PyImport_Cleanup is called with builtins_copy == NULL in test_embed

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#77560]
BPO | [33379](https://bugs.python.org/issue33379)
--- | :---
Nosy | @brettcannon, @ncoghlan, @ericsnowcurrently, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-04-28.22:03:00.332>
labels = ['interpreter-core', '3.8', 'type-bug', '3.7']
title = 'PyImport_Cleanup is called with builtins_copy == NULL in test_embed'
updated_at = <Date 2018-04-29.05:56:26.461>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2018-04-29.05:56:26.461>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-04-28.22:03:00.332>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 33379
keywords = []
message_count = 2.0
messages = ['315868', '315881']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'ncoghlan', 'eric.snow', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33379'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
PyImport_Cleanup was renamed to finalize_modules in:

commit dff1ad509051f7e07e77d1e3ec83314d53fb1118 (HEAD, refs/bisect/bad)
Author: Victor Stinner <vstinner@python.org>
Date:   Fri Oct 30 18:03:28 2020 +0100

    bpo-42208: Move _PyImport_Cleanup() to pylifecycle.c (GH-23040)
    
    Move _PyImport_Cleanup() to pylifecycle.c, rename it to
    finalize_modules(), split it (200 lines) into many smaller
    sub-functions and cleanup the code.

**Comment by vstinner** [comment]
> PyImport_Cleanup is called with builtins_copy == NULL in run_embedded_interpreter() in [Lib/test/test_embed.py](https://github.com/python/cpython/blob/main/Lib/test/test_embed.py).

I don't understand this statement. I need more context.

The code changed a lot since 2018. I close the issue.
