### ISSUE TITLE
[ctypes] increase the refcount of a callback function

### ISSUE THREAD

**Issue by 6f8a2dcb-4f3a-4dba-b8d6-ce976ee46c21** [python/cpython#77587]
BPO | [33406](https://bugs.python.org/issue33406)
--- | :---
Nosy | @amauryfa, @abalkin, @meadori, @eryksun, @pablogsal, @Zuzu-Typ

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-02.06:39:05.212>
labels = ['ctypes', 'type-feature', '3.10']
title = '[ctypes] increase the refcount of a callback function'
updated_at = <Date 2021-03-28.03:07:14.762>
user = 'https://github.com/Zuzu-Typ'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-28.03:07:14.762>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2018-05-02.06:39:05.212>
creator = 'Zuzu_Typ'
dependencies = []
files = []
hgrepos = []
issue_num = 33406
keywords = []
message_count = 2.0
messages = ['316047', '316057']
nosy_count = 6.0
nosy_names = ['amaury.forgeotdarc', 'belopolsky', 'meador.inge', 'eryksun', 'pablogsal', 'Zuzu_Typ']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33406'
versions = ['Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
> when leaving the scope it gets garbage-collected. When the library now tries to execute said function, an access violation occurs.

That can happen with freed data as well; functions are not special.
If you use ctypes, you need to do lifetime management manually.

> there are ways to support this, depending on the context (e.g. global variable, class attribute, instance attribute, a dict).

IMO, this is the way to do it.
Also, nothing but good taste is stopping you from calling `Py_NewRef` through `ctypes`.

I'll close the issue.
