### ISSUE TITLE
pathlib.Path.glob does not follow symlinks

### ISSUE THREAD

**Issue by 2129c879-04cf-4594-a55d-0dd74518cf61** [python/cpython#77609]
BPO | [33428](https://bugs.python.org/issue33428)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @jreese, @zware, @zooba, @emilyemorehouse, @BrianMSheldon

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-05.06:23:00.558>
labels = ['type-bug', 'library', 'OS-windows']
title = 'pathlib.Path.glob does not follow symlinks'
updated_at = <Date 2020-04-29.11:12:49.344>
user = 'https://github.com/BrianMSheldon'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-29.11:12:49.344>
actor = 'Danya.Alexeyevsky'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2018-05-05.06:23:00.558>
creator = 'brianmsheldon'
dependencies = []
files = []
hgrepos = []
issue_num = 33428
keywords = []
message_count = 4.0
messages = ['316197', '316724', '316880', '367640']
nosy_count = 9.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'jreese', 'Danya.Alexeyevsky', 'zach.ware', 'steve.dower', 'emilyemorehouse', 'brianmsheldon']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33428'
versions = ['Python 3.6']
```

</p></details>

### Linked PRs
* gh-102616
* gh-104176
* gh-117311

**Comment by abdalazizrashid** [comment]
Any updates regarding this? I'm having the same problem on Linux.

**Comment by dlukes** [comment]
Following symlinks was [disabled on purpose](https://github.com/python/cpython/issues/70200#issuecomment-1093702406) as a fix for #70200:

https://github.com/python/cpython/blob/69f6cc77d0f1664f983a83b6ae707d99a99f5c4f/Lib/pathlib.py#L319

To re-enable it, we'd have to come up with a different mitigation for the symlink loops problem.

Or possibly, if hidden behind a `follow_symlinks` arg which would be `False` by default, it might be enough to just document it as a limitation when `follow_symlinks=True`? I don't know.

**Comment by iyadahmed** [comment]
On Ubuntu 22 I have the same problem

**Comment by barneygale** [comment]
> Or possibly, if hidden behind a follow_symlinks arg which would be False by default, it might be enough to just document it as a limitation when follow_symlinks=True? I don't know.

`glob()` still follows symlinks when matching segments like `foo/`, `*/` and so forth; it only refuses to follow symlinks when it encounters a `**` wildcard. So the current behaviour is roughly `follow_symlinks=Sometimes`.

I realised this because I've been trying to implement an iterative version of `rglob()`, building upon `walk()` and filtering paths with a compiled `re.Pattern` object. `walk()` has its own `follow_symlinks` argument that accepts `True` and `False`, but neither option aligns with the existing behaviour, so it seems like a dead end unless this "bug" is "fixed".

**Comment by barneygale** [comment]
zsh has a `***` wildcard that recurses into symlinks to directories, see *Recursive Globbing* here: https://linux.die.net/man/1/zshexpn

**Comment by barneygale** [comment]
Having thought about this some more, I'd like to propose that we add *follow_symlinks* arguments to `glob()` and `rglob()`, where:

- `follow_symlinks=False` treats symlinks as files (default)
- `follow_symlinks=True` follows symlinks to directories

Note that the default behaviour would therefore change: a pattern like `foo/bar` or `*/bar` would no longer match `foo/bar` if `foo` is a symlink. This is consistent with how `**/bar` works today.

With that in place, we could implement `glob()` iteratively atop `walk()`, which would address #89727 and substantially improve performance!

Thoughts?

**Comment by zooba** [comment]
Is it possible to follow symlinks when matching non-wildcard segments? I'm not familiar with the implementation, though if you're planning to put it atop `walk()` then the current implementation may not matter.

It might have to be a different mode, but if it preserves the current behaviour, it may be worth it. I can't decide whether it meets my expectations better or not, but it does seem we can avoid the harm of cycles in that case.

**Comment by barneygale** [comment]
With the proposed `walk()`-based implementation I have in mind, it wouldn't be possible to treat `**` differently to other patterns w.r.t following symlinks.

The current `glob()` implementation performs unnecessary work when its given a pattern that contains a non-terminal recursive wildcard, e.g. `**/a.py`. It first walks the entire directory tree when it encounters the `**` wildcard and records all the paths. It appends `/a.py` to all those paths and `stat()`s them. This second step is unnecessary! We've just walked the directory tree and established all the files/directories that exist, so we shouldn't need to do it again.

In a possible future implementation, `glob()` could walk a directory when it hits a `**` wildcard as before, and then simply filter the results through a regex. This means any tokens following `**` in the pattern won't incur any `stat()`s or `scandir()`s. It also means we don't need to maintain a set of paths we've yielded:

https://github.com/python/cpython/blob/f87f6e23964d7a4c38b655089cda65538a24ec36/Lib/pathlib.py#L193-L202

However, this only works if we treat symlinks the same no matter whether we've hit a `**` token or some other kind of token. Otherwise the filter will include or exclude the wrong things.

**Comment by barneygale** [comment]
> it does seem we can avoid the harm of cycles in that case

Symlinks really complicate everything don't they? :)

Another option: swallow ELOOP errors, like `glob.glob()` does? It seems reasonable to me. We could add an *on_error* argument to `glob()` (we already have one in `walk()`) if users want to do something different.

**Comment by zooba** [comment]
Ah I see, yeah, there's not really any alternative for handling `**`, and there's no real advantage to only collecting directories.

Refusing to traverse on `ELOOP` and also doing our own cycle detection for longer cycles is probably required anyway, and then use `follow_symlinks` to turn it off entirely.

I feel like `on_error` is too low-level for a pathlib API. I can imagine wanting to filter to _only_ symlinks (so I know what to follow up on), but we don't have any APIs for that today and I don't think this is the point to add them.

So given all that, could we default to `follow_symlinks=True` (without following errors or following the same link multiple times)?

**Comment by barneygale** [comment]
Q: how do you suggest we detect cycles? Calling `resolve()` / `os.path.realpath()` on every symlink will be quite expensive I think? Might be wrong.

**Comment by zooba** [comment]
If you have a ton of directory symlinks, sure, but who does that? And I'm pretty sure that's the only generic option (we could try to be clever and remember e.g. the inode of the first file in each directory, but I doubt that's as portable). We only have to check on the way into the symlink - not for every file inside of it (unless it's another directory symlink).

Maybe we can remember devs+inodes of the symlinks themselves and skip the check if it's a non-zero[^1] value that we haven't seen before?

And now I'm thinking about this, how do we want to handle multiple non-cyclic symlinks into the same directory? If our search root has 100 symlinks to the same directory, none of them are a cycle, but we'll return the same files 100 times. That's probably the right thing to do.

[^1]: Zero is the usual value for "inodes are not supported", but if they're all going to return zero then we'll check them all anyway, so the non-zero check probably doesn't change anything.

**Comment by barneygale** [comment]
I rather like `glob.glob()`'s behaviour, which is to follow (and emit) symlinks in a cycle until an OSError for "too many symlinks in path" is raised, silently consume that error, and continue the rest of the walk. `os.walk()` and `pathlib.Path.walk()` do the same thing, but make it somewhat customizable with an *on_error* argument. My shell and the `find` executable seem to do this too. It's a bit "stupid", I suppose, but I worry we'll be endlessly chasing edge cases if we try to be too clever.

**Comment by zooba** [comment]
Fair. I imagine enough stuff breaks down with symlink cycles that people try to avoid them anyway.

**Comment by barneygale** [comment]
PR available: #102616

**Comment by maxnoe** [comment]
> If you have a ton of directory symlinks, sure, but who does that? 

We do :)

Details don't matter really here, but we have a common directory for data, let's call it `/data/base` and there we have either directories directly for one specific kind of data preprocessing and symlinks to other directories for some other kind of preprocessing.

```
/data/base
   /2023-01-02/   # directory
   /2023-01-03 -> /preprocessed/2023-01-03  # symlink
/preprocessed/
  /2023-01-03
```

We'd very much like to do stuff like `Path("/data/base").rglob("foo.bar")`, but that doesn't work currently.

**Comment by zooba** [comment]
Great scenario, appreciate you showing us.

Will the support for `follow_symlinks=True` be a good fix for you in future? I suspect you may be dealing with a case where you'd prefer following symlinks to become the default.

**Comment by maxnoe** [comment]
> Will the support for follow_symlinks=True be a good fix for you in future? 

yes, having to specify an option is no issue.

> I suspect you may be dealing with a case where you'd prefer following symlinks to become the default.

Not really, it's all under our control, so as long as there is the option to follow symlinks, at least we would be fine.

**Comment by barneygale** [comment]
Suggestion:


|                               | Literal (e.g. `foo/`)   | Wildcard (e.g. `foo*/`) | Recursive wildcard (`**/`) |
|-------------------------------|-------------------------|-------------------------|----------------------------|
| `glob(follow_symlinks=False)` | ✓                       | ✓                       |                     |       
| `glob(follow_symlinks=True)`  | ✓                       | ✓                       | ✓                    |       

We default to `follow_symlinks=False`, which preserves existing behaviour. Users could set `follow_symlinks=True` to follow symlinks in all circumstances.

We'd be left with the problem that `glob(follow_symlinks=False)` follows symlinks in some circumstances. But perhaps that's a smaller problem than the present inability to follow symlinks when expanding `**`?

**Comment by zooba** [comment]
I still prefer `=None` to mean legacy behaviour, with `True` and `False` being complete.

Did we discuss whether we should return symlinks that would've been followed but weren't? I can't remember if we covered it or what we decided.

**Comment by barneygale** [comment]
Fair enough, just thought I'd throw it out there ;-)

> Did we discuss whether we should return symlinks that would've been followed but weren't? I can't remember if we covered it or what we decided.

Sorry - I'm not sure what you mean, can you clarify?

**Comment by zooba** [comment]
> Sorry - I'm not sure what you mean, can you clarify?

Ignore me. I was assuming that `rglob` wouldn't return a directory if it was returning its contents, but it turns out that it currently does. So a link that matches the pattern would be returned regardless of whether it is followed or not.

**Comment by barneygale** [comment]
I've added a keyword-only `follow_symlinks` argument, which will be available in Python 3.13. See [9700dd1](https://github.com/barneygale/cpython/commit/9700dd13a9e2ad47d3eb38b817ed27992788fb0f) / #102616

Thank you everyone, and especially @zooba, for the help in getting this through. Resolving!

**Comment by gpshead** [comment]
Lets change the new `follow_symlinks=None` to `follow_symlinks=NotRecursive` (or some other explicitly named sentinel value defined in the pathlib module).

People reading code that explicitly specifies `follow_symlinks=None` as would be needed if we ever decide to change the default would not be able to reason about what that does and why `=None` isn't the same behavior as `=False` or `=0`.  Seeing a named constant makes it much more clear to those not intimately familiar with the API.

This is good even if we never decide [to work towards a default change](https://discuss.python.org/t/treating-symlinks-consistently-in-pathlib-path-glob/49233).

**Comment by barneygale** [comment]
Re-resolving - the argument is now `recurse_symlinks` and accepts a boolean.
