### ISSUE TITLE
Asynchronous lambda syntax

### ISSUE THREAD

**Issue by 4ce6fc46-e605-47d4-871e-1264e9df4ca6** [python/cpython#77628]
BPO | [33447](https://bugs.python.org/issue33447)
--- | :---
Nosy | @terryjreedy, @asvetlov, @1st1, @AceAttorneyMaster111

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-05-18.19:55:06.834>
created_at = <Date 2018-05-09.03:22:40.128>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Asynchronous lambda syntax'
updated_at = <Date 2018-05-31.09:55:25.848>
user = 'https://github.com/AceAttorneyMaster111'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-31.09:55:25.848>
actor = 'thomasahle'
assignee = 'none'
closed = True
closed_date = <Date 2018-05-18.19:55:06.834>
closer = 'yselivanov'
components = ['Interpreter Core']
creation = <Date 2018-05-09.03:22:40.128>
creator = 'Noah Simon'
dependencies = []
files = []
hgrepos = []
issue_num = 33447
keywords = []
message_count = 5.0
messages = ['316304', '316305', '317056', '317061', '318279']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'asvetlov', 'thomasahle', 'yselivanov', 'Noah Simon']
pr_nums = []
priority = 'normal'
resolution = 'postponed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33447'
versions = ['Python 3.8']
```

</p></details>

**Comment by pdxjohnny** [comment]
I also really want async syntax

**Comment by p0t4t0sandwich** [comment]
Coding an self-building Python -> Web-API adapter using lambdas like you would within JS, and the only way to create an async version of my program would be to either:
A: Find some python voodoo to dynamically generate async functions.
B: Build it all by hand and update it manually with each API release.
Being completely honest, neither of these options are desirable.

**Comment by muazhari** [comment]
> The syntax for async lambdas doesn't look nice and I, personally, don't see that many use cases for them to justify adding new syntax. And this would need a new PEP.
> 
> I suggest to start a discussion on the Python-ideas mailing list if this is something you want to see in Python.

I found meaningful use cases for async lambda in reactive programming. Here is the example code that should be:
```python
async def read_one_by_id(request: ReadOneByIdRequest) -> Content[Account]:
    return rx.just(request).pipe(
        ops.map(lambda async request: await account_repository.read_one_by_id(request.id)),
        ops.map(lambda entity: Content(data=entity, message="Account read one by id succeed.")),
        ops.catch(lambda exception, source: rx.just(
            Content(entity=None, message=f"Account read one by id failed: {exception}")))
    ).run()
```
