### ISSUE TITLE
Possible lazy import opportunities in `pathlib`

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#77621]
BPO | [33440](https://bugs.python.org/issue33440)
--- | :---
Nosy | @ncoghlan, @pitrou, @njsmith, @serhiy-storchaka
PRs | <li>python/cpython#6820</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-07.12:28:40.679>
labels = ['3.8', 'library', 'performance']
title = 'Possible lazy import opportunities in `pathlib`'
updated_at = <Date 2018-05-14.20:03:34.394>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-14.20:03:34.394>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-05-07.12:28:40.679>
creator = 'ncoghlan'
dependencies = []
files = []
hgrepos = []
issue_num = 33440
keywords = ['patch']
message_count = 4.0
messages = ['316266', '316276', '316567', '316570']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'pitrou', 'njs', 'serhiy.storchaka']
pr_nums = ['6820']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue33440'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-112244

**Comment by barneygale** [comment]
I've moved the `urllib` imports into `as_uri()` / `from_uri()` as their use is uncommon. Everything else is likely to be hit in general usage, I think.

**Comment by AlexWaygood** [comment]
You could probably make this one lazy:

https://github.com/python/cpython/blob/607b5e30c67bad35b90240d9ac176131e51423a5/Lib/pathlib.py#L17

Users probably shouldn't pay the cost of importing `warnings` unless they're actually using a deprecated function. There are quite a few uses of `warnings` in `pathlib`, though, which is why I held off from changing `warnings` to be a lazy import in `pathlib` as part of #110286 -- maybe making it a lazy import in `pathlib` just adds too much ugliness for it to be worthwhile.

**Comment by barneygale** [comment]
Three of four uses of `warnings` will be removed in 3.14, so perhaps we could look again when `main` becomes 3.14?

**Comment by AlexWaygood** [comment]
> Three of four uses of `warnings` will be removed in 3.14, so perhaps we could look again when `main` becomes 3.14?

SGTM!

**Comment by barneygale** [comment]
Resolving this issue as I believe there's nothing left to do!

- The `urllib` import was made lazy in #107640
- The `fnmatch`, `glob` and `re` imports were made lazy in #112244
- The top-level `warnings` import will be removed when we branch for Python 3.14
- Everything else is cheap or needed at a module level
