### ISSUE TITLE
build system runs when it may merely link

### ISSUE THREAD

**Issue by b37622fd-a3e4-4a81-9077-68208b8b2f1f** [python/cpython#77665]
BPO | [33484](https://bugs.python.org/issue33484)
--- | :---
Nosy | @bitdancer, @grimreaper
PRs | <li>python/cpython#6781</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-13.18:38:36.064>
labels = ['build']
title = 'build system runs when it may merely link'
updated_at = <Date 2018-05-15.07:44:31.640>
user = 'https://github.com/grimreaper'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-15.07:44:31.640>
actor = 'eitan.adler'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2018-05-13.18:38:36.064>
creator = 'eitan.adler'
dependencies = []
files = []
hgrepos = []
issue_num = 33484
keywords = ['patch']
message_count = 5.0
messages = ['316471', '316473', '316474', '316475', '316476']
nosy_count = 2.0
nosy_names = ['r.david.murray', 'eitan.adler']
pr_nums = ['6781']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33484'
versions = []
```

</p></details>

**Comment by encukou** [comment]
> This is a minor performance optimization but is really a semantic correctness issue.

Avoiding 4 processes (on runs without cache) is a very minor optimization indeed. And I don't see the semantic correctness -- surely we want the functions to not return an error indicator when called.
I don't think the change is worth the possibility of breaking on the mentioned arcane platforms.
I to close this PR and issue; please comment if you disagree.
