### ISSUE TITLE
Add 1.32x faster C implementation of asyncio.isfuture().

### ISSUE THREAD

**Issue by 7c999128-17c2-4b3a-8040-fe050fb865e0** [python/cpython#77702]
BPO | [33521](https://bugs.python.org/issue33521)
--- | :---
Nosy | @pitrou, @vstinner, @asvetlov, @1st1, @jimmylai
PRs | <li>python/cpython#6876</li>
Files | <li>[isfuture_benchmark.py](https://bugs.python.org/file47593/isfuture_benchmark.py "Uploaded as text/plain at 2018-05-15.20:02:21 by @jimmylai")</li><li>[isfuture_benchmark2.py](https://bugs.python.org/file47603/isfuture_benchmark2.py "Uploaded as text/plain at 2018-05-18.23:04:29 by @vstinner")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-15.15:31:32.301>
labels = ['expert-asyncio', '3.8', 'performance']
title = 'Add 1.32x faster C implementation of asyncio.isfuture().'
updated_at = <Date 2018-05-26.00:14:20.203>
user = 'https://github.com/jimmylai'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-26.00:14:20.203>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-05-15.15:31:32.301>
creator = 'jimmylai'
dependencies = []
files = ['47593', '47603']
hgrepos = []
issue_num = 33521
keywords = ['patch']
message_count = 12.0
messages = ['316670', '316712', '317065', '317129', '317130', '317131', '317132', '317146', '317282', '317693', '317721', '317722']
nosy_count = 5.0
nosy_names = ['pitrou', 'vstinner', 'asvetlov', 'yselivanov', 'jimmylai']
pr_nums = ['6876']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue33521'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Is it still worth doing this now that ``gather()`` is "legacy"?
