### ISSUE TITLE
Provide an async iterator version of as_completed

### ISSUE THREAD

**Issue by 61a746e0-56f6-4f74-bbde-a98c5612db23** [python/cpython#77714]
BPO | [33533](https://bugs.python.org/issue33533)
--- | :---
Nosy | @hniksic, @asvetlov, @Fak3, @1st1, @mivade, @JustinTArthur, @carlodri
PRs | <li>python/cpython#10251</li><li>python/cpython#22491</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-16.06:48:52.976>
labels = ['type-feature', '3.10', 'expert-asyncio']
title = 'Provide an async iterator version of as_completed'
updated_at = <Date 2020-10-16.06:44:21.716>
user = 'https://github.com/hniksic'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-16.06:44:21.716>
actor = 'carlodri'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-05-16.06:48:52.976>
creator = 'hniksic'
dependencies = []
files = []
hgrepos = []
issue_num = 33533
keywords = ['patch']
message_count = 11.0
messages = ['316773', '316774', '316963', '317247', '326748', '328454', '328527', '377797', '377803', '377840', '377927']
nosy_count = 7.0
nosy_names = ['hniksic', 'asvetlov', 'Roman.Evstifeev', 'yselivanov', 'mivade', 'JustinTArthur', 'carlodri']
pr_nums = ['10251', '22491']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33533'
versions = ['Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
I don't like this API at all, it should have been an async generator from the very beginning.  Will look into this for 3.13

**Comment by gvanrossum** [comment]
@serhiy-storchaka Could you review the PRs from this issue? There seem two PRs by different authors.

**Comment by serhiy-storchaka** [comment]
While it is documented that `as_completed()` returns an iterator, actually it returns a generator, which has a `close()` method, so it can be explicitly closed or used with the `closing()` context manager. For asynchronous generators deterministic closing is even more important, because they always create reference loops. So I think that it is important to implement both `close()` and `aclose()` methods in new hybrid iterator. It is less likely that methods `send()` and `throw()` or attributes like `gi_running` are used in real code, so I think we can omit them.

**Comment by gvanrossum** [comment]
There seem to be *two* PRs for this one issue. #10251 and #22491. Which one should we prefer?

**Comment by serhiy-storchaka** [comment]
The latter is more compatible (it returns an iterator, not simply an iterable) and contains many tests (duplicate tests for synchronous iterator and add new tests for details which we want to preserve).

**Comment by gvanrossum** [comment]
I am planning to have a look at the PR. As always, with this type of project, I am (perhaps unnecessarily) worried that this improvement, however much of an improvement it is for new code (which can rely on the Futures' identities, for example), it may break corner cases where users have production systems that somehow, rarely, depends on some clever abuse of a detail of the old version (maybe someone *assumes* that they never get the same Future back, and they store input and output Futures in a dict expecting to have both available).

I have some other catching up to do before I get to this, but it is in my queue.

**Comment by serhiy-storchaka** [comment]
They only get the same Future back when they use an asynchronous iterator. I.e. if they change their code.

**Comment by achimnol** [comment]
Great to see this to land in asyncio!
Here's my version: https://github.com/achimnol/aiotools/blob/6d8a93ed0418d61e7c40c7f5c06b061af4581c06/src/aiotools/utils.py#L33
