### ISSUE TITLE
Better document mixed-type comparison of set items, dict keys

### ISSUE THREAD

**Issue by 54c6f951-17b0-4c2e-87f3-8b31188dc337** [python/cpython#77753]
BPO | [33572](https://bugs.python.org/issue33572)
--- | :---
Nosy | @tim-one, @terryjreedy, @mdickinson

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-18.15:19:50.946>
labels = ['type-bug', 'docs']
title = 'Better document mixed-type comparison of set items, dict keys'
updated_at = <Date 2018-05-18.19:44:10.802>
user = 'https://bugs.python.org/JanuszHarkot'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-18.19:44:10.802>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2018-05-18.15:19:50.946>
creator = 'Janusz Harkot'
dependencies = []
files = []
hgrepos = []
issue_num = 33572
keywords = []
message_count = 6.0
messages = ['317032', '317033', '317035', '317045', '317046', '317053']
nosy_count = 5.0
nosy_names = ['tim.peters', 'terry.reedy', 'mark.dickinson', 'docs@python', 'Janusz Harkot']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33572'
versions = ['Python 3.6']
```

</p></details>

**Comment by slateny** [comment]
Per [comment](https://github.com/python/cpython/pull/92549#issuecomment-1121345877), I'll close this if there aren't any objections.

**Comment by mdickinson** [comment]
@slateny I'm not seeing the applicability of that comment to this issue. I think it's still true that the docs here could use an update.

Proposed minimal edit: replace the sentence

> Numeric types used for keys obey the normal rules for numeric comparison: if two numbers compare equal (such as 1 and 1.0) then they can be used interchangeably to index the same dictionary entry.

with

> If two objects compare equal (such as 1 and 1.0) then they can be used interchangeably to index the same dictionary entry.

**Comment by slateny** [comment]
Hmm I see, so the improvement would be to generalize the statement. Do you think there's any value in adding any examples, or extending the note in the parenthesis a bit and say `... equal (such as 1, 1.0, and True) then they ...` to emphasize that point?
