### ISSUE TITLE
Detect accessing event loop from a different thread outside of _debug

### ISSUE THREAD

**Issue by 61a746e0-56f6-4f74-bbde-a98c5612db23** [python/cpython#77786]
BPO | [33605](https://bugs.python.org/issue33605)
--- | :---
Nosy | @hniksic, @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-22.19:00:04.477>
labels = ['3.8', 'type-feature', '3.7', 'expert-asyncio']
title = 'Detect accessing event loop from a different thread outside of _debug'
updated_at = <Date 2018-05-24.07:09:17.274>
user = 'https://github.com/hniksic'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-24.07:09:17.274>
actor = 'hniksic'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-05-22.19:00:04.477>
creator = 'hniksic'
dependencies = []
files = []
hgrepos = []
issue_num = 33605
keywords = []
message_count = 6.0
messages = ['317324', '317340', '317435', '317436', '317446', '317540']
nosy_count = 3.0
nosy_names = ['hniksic', 'asvetlov', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33605'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
Functions and methods are clearly[^1] documented as `not thread-safe`  and there is debug mode check.
It is only safe to call `call_soon_threadsafe` which is documented to be thread safe. Also the debug checks are not "free" so would cause a perf regression. Closing as this isn't really a problem in correct asyncio programs.


[^1]: https://docs.python.org/3/library/asyncio-eventloop.html?highlight=call_soon_threadsafe#asyncio.loop.call_soon

**Comment by gvanrossum** [comment]
Yeah, since the discussion does 4 years ago I agree that this can be closed as wontfix.
