### ISSUE TITLE
IDLE: Make multiple improvements to CodeContext

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#77791]
BPO | [33610](https://bugs.python.org/issue33610)
--- | :---
Nosy | @terryjreedy, @taleinat, @csabella, @miss-islington
PRs | <li>python/cpython#7597</li><li>python/cpython#7598</li><li>python/cpython#7599</li><li>python/cpython#14821</li><li>python/cpython#14822</li><li>python/cpython#14846</li><li>python/cpython#14847</li><li>python/cpython#14913</li><li>python/cpython#14914</li><li>python/cpython#23773</li><li>python/cpython#23774</li><li>python/cpython#23775</li>
Dependencies | <li>bpo-22703: Idle Code Context menu entrie(s)</li><li>bpo-31493: IDLE cond context: fix code update and font update timers</li><li>bpo-32831: IDLE: Add docstrings and tests for codecontext</li><li>bpo-33628: IDLE: Code cleanup on codecontext</li><li>bpo-33642: IDLE: Display up to maxlines non-blank lines for Code Context</li><li>bpo-33664: IDLE:  scroll text by lines, not pixels.</li><li>bpo-33763: IDLE: Use text widget for code context instead of label widget</li><li>bpo-35521: IDLE: Add doc section for Code Context and ref links.</li><li>bpo-35555: IDLE: Gray out Code Context on non-editor windows</li><li>bpo-37530: IDLE: simplify, optimize, and clean up code context</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2018-05-23.05:18:11.915>
labels = ['expert-IDLE', 'type-feature', '3.10']
title = 'IDLE: Make multiple improvements to CodeContext'
updated_at = <Date 2020-12-15.12:52:04.350>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-15.12:52:04.350>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2018-05-23.05:18:11.915>
creator = 'terry.reedy'
dependencies = ['22703', '31493', '32831', '33628', '33642', '33664', '33763', '35521', '35555', '37530']
files = []
hgrepos = []
issue_num = 33610
keywords = ['patch', '3.5regression']
message_count = 39.0
messages = ['317357', '317364', '317480', '317599', '317601', '317651', '317822', '318012', '318351', '318355', '318357', '318358', '318466', '318476', '318562', '318589', '318791', '319240', '319241', '319242', '319243', '332034', '332105', '332312', '347571', '348001', '348078', '348081', '348125', '348126', '348127', '348324', '348325', '348326', '383031', '383033', '383035', '383036', '383048']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'taleinat', 'cheryl.sabella', 'miss-islington']
pr_nums = ['7597', '7598', '7599', '14821', '14822', '14846', '14847', '14913', '14914', '23773', '23774', '23775']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33610'
versions = ['Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
Are there more work to be done here, or can we close this issue?

**Comment by terryjreedy** [comment]
1 1/2 years after last activity, revised https://github.com/python/cpython/issues/77791#issuecomment-1093786893 shows some undone tasks.  These are copied to new issue #95352.
