### ISSUE TITLE
Implement subclass hooks for asyncio abstract classes

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#77805]
BPO | [33624](https://bugs.python.org/issue33624)
--- | :---
Nosy | @asvetlov, @1st1, @ilevkivskyi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-23.19:18:18.620>
labels = ['type-feature', '3.8', 'expert-asyncio']
title = 'Implement subclass hooks for asyncio abstract classes'
updated_at = <Date 2018-05-26.13:02:01.777>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2018-05-26.13:02:01.777>
actor = 'levkivskyi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-05-23.19:18:18.620>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 33624
keywords = []
message_count = 1.0
messages = ['317438']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'levkivskyi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33624'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
I think that making these classes typing [runtime_checkable](https://docs.python.org/3/library/typing.html#typing.runtime_checkable]) protocols should work.

**Comment by kumaraditya303** [comment]
Even if we add this we indefinitely need to support objects which do not inherit from these so this is not worth for the minority of the cases.
