### ISSUE TITLE
asyncio: Prohibit adding a signal handler for SIGCHLD

### ISSUE THREAD

**Issue by 1st1** [python/cpython#77831]
BPO | [33650](https://bugs.python.org/issue33650)
--- | :---
Nosy | @gpshead, @pitrou, @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-05-25.20:56:35.397>
labels = ['3.8', 'expert-asyncio']
title = 'asyncio: Prohibit adding a signal handler for SIGCHLD'
updated_at = <Date 2018-06-01.19:41:05.108>
user = 'https://github.com/1st1'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-01.19:41:05.108>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-05-25.20:56:35.397>
creator = 'yselivanov'
dependencies = []
files = []
hgrepos = []
issue_num = 33650
keywords = []
message_count = 3.0
messages = ['317717', '318454', '318455']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'pitrou', 'asvetlov', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33650'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
`PidfdChildWatcher` and `ThreadedChildWatcher` don't install signal handlers for `SIGCHLD` so this can't break `asyncio` internals. The other child watchers are deprecated so closing as this is no longer an issue.

**Comment by kumaraditya303** [comment]
See also https://github.com/python/cpython/issues/88378
