### ISSUE TITLE
string formatting that produces floats with preset precision while respecting locale

### ISSUE THREAD

**Issue by c9946918-cc76-419b-8bcc-4f82a3ab6816** [python/cpython#77912]
BPO | [33731](https://bugs.python.org/issue33731)
--- | :---
Nosy | @rhettinger, @ericvsmith, @cedk, @skrah, @james-emerton
PRs | <li>python/cpython#8612</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2018-06-01.12:42:33.231>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'string formatting that produces floats with preset precision while respecting locale'
updated_at = <Date 2019-08-14.11:34:15.211>
user = 'https://bugs.python.org/JakubSzewczyk'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-14.11:34:15.211>
actor = 'ced'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-06-01.12:42:33.231>
creator = 'Jakub Szewczyk'
dependencies = []
files = []
hgrepos = []
issue_num = 33731
keywords = ['patch']
message_count = 6.0
messages = ['318407', '318410', '322911', '322913', '322914', '349684']
nosy_count = 6.0
nosy_names = ['rhettinger', 'eric.smith', 'ced', 'skrah', 'jemerton', 'Jakub Szewczyk']
pr_nums = ['8612']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue33731'
versions = ['Python 3.8']
```

</p></details>

**Comment by alexander-gabriel** [comment]
Individually localizing numbers is not a viable solution to this problem. str.format() allows us to efficiently produce strings with a lots of numbers...but only if you don't need localization. Localizing 10 or 20 numbers individually is verbose, inefficient and simply bad style.

Python should allow users to use the full power of str.format() in a localized manner.

**Comment by ericvsmith** [comment]
Thanks everyone for their input, but I'm going to close this issue. Given that there's a workaround to use the `locale` module directly, I think that's the best approach. One day I'd like to see a way of using locales that doesn't depend on the C standard library and all of its baggage, but until then let's leave locales alone.
