### ISSUE TITLE
Argument clinic and Windows line endings

### ISSUE THREAD

**Issue by giampaolo** [python/cpython#77968]
BPO | [33787](https://bugs.python.org/issue33787)
--- | :---
Nosy | @larryhastings, @giampaolo
Files | <li>[clinic.diff](https://bugs.python.org/file47634/clinic.diff "Uploaded as text/plain at 2018-06-07.18:22:00 by @giampaolo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2018-06-06.19:49:08.669>
labels = ['3.8', 'expert-argument-clinic']
title = 'Argument clinic and Windows line endings'
updated_at = <Date 2018-06-07.18:22:00.820>
user = 'https://github.com/giampaolo'
```

bugs.python.org fields:
```python
activity = <Date 2018-06-07.18:22:00.820>
actor = 'giampaolo.rodola'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2018-06-06.19:49:08.669>
creator = 'giampaolo.rodola'
dependencies = []
files = ['47634']
hgrepos = []
issue_num = 33787
keywords = ['patch']
message_count = 2.0
messages = ['318857', '318958']
nosy_count = 2.0
nosy_names = ['larry', 'giampaolo.rodola']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33787'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-104068

**Comment by zooba** [comment]
This shouldn't be necessary if your line ending settings are correct. Git on Windows should convert (most) files to CRLF on checkout and convert back on commit, so we want to work with native endings in our generators.

I have run clinic frequently for years and never had this issue. Much as I hate closing bugs based on "works on my machine", I'm still closing this, but if someone can reproduce it with `core.autocrlf=true` then feel free to post details and we can reconsider.

**Comment by erlend-aasland** [comment]
Thanks for chiming in, Steve. I'm on thin ice when it comes to Windows stuff.
