### ISSUE TITLE
[pathlib] issues with Windows device paths

### ISSUE THREAD

**Issue by eryksun** [python/cpython#78079]
BPO | [33898](https://bugs.python.org/issue33898)
--- | :---
Nosy | @pfmoore, @pitrou, @tjguk, @zware, @eryksun, @zooba
PRs | <li>python/cpython#8671</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-06-18.22:40:29.969>
labels = ['type-bug', '3.8', '3.9', '3.7', 'library', 'OS-windows']
title = 'pathlib issues with Windows device paths'
updated_at = <Date 2020-04-17.17:59:50.770>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-17.17:59:50.770>
actor = 'pitrou'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2018-06-18.22:40:29.969>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 33898
keywords = ['patch']
message_count = 2.0
messages = ['319921', '337405']
nosy_count = 6.0
nosy_names = ['paul.moore', 'pitrou', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = ['8671']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33898'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-102003

**Comment by barneygale** [comment]
@eryksun I suppose that any remaining pathlib device path issues are down to the `if` condition here:

https://github.com/python/cpython/blob/666c0840dcac9941fa41ec619fef8d45cd849a0b/Lib/pathlib.py#L284-L286

Should it exclude more paths?

**Comment by zooba** [comment]
I think this is the issue that requires `splitroot` to be correct (which it might be by now?) and then `pathlib` has to be very deliberate about the meaning of a trailing slash in the drive part vs a leading slash in the rest of the path.

The current PR doesn't seem to be easily resolvable, but is probably well out of date anyway because of other work that's been done in pathlib and ntpath.

The existing test suite and the examples Eryk posted above are probably the best way to figure out the right semantics.

**Comment by barneygale** [comment]
Based on Eryk's test cases, `ntpath.splitroot()` gets `//?/Global` and `//./Global` paths wrong:

```python
>>> ntpath.splitroot('//./Global/Z:/')
('//./Global', '/', 'Z:/')
>>> ntpath.splitroot('//?/Global/Z:/')
('//?/Global', '/', 'Z:/')
```

I believe that all the other failing test cases can be put down to pathlib erroneously adding roots to paths like `//./C:`, `//./nul`, `//./PhysicalDrive0` and `//?/UNC/`.

**Comment by zooba** [comment]
> I believe that all the other failing test cases can be put down to pathlib erroneously adding roots to paths

Yeah, this is what I expected with "deliberate about the meaning of ... leading slash in the rest of the path". I know we've encountered these consistency issues before, but I don't know whether they were all resolved.

**Comment by barneygale** [comment]
I've opened a PR that fixes all of Eryk's test cases except `//./Global` and `//?/Global`: #102003

**Comment by barneygale** [comment]
Hey @eryksun, do you think we should leave this issue open to cover the remaining "Global" and "GLOBALROOT" issues? The problem there lies mostly in `ntpath.splitroot()`, so I might remove the `expert-pathlib` label.

**Comment by zooba** [comment]
I vote for a new issue (with a more descriptive title), and would also say it's not a high priority. If you can describe it well enough, might even be able to justify tagging it "easy" and offer it up for someone at sprints.

**Comment by barneygale** [comment]
Logged here: 

- #103593

I don't understand the rules for "Global" and "GLOBALROOT" so it's not very well described :)

Resolving this issue! Thanks all.
