### ISSUE TITLE
Allow json.tool to have identical infile and outfile

### ISSUE THREAD

**Issue by b2d2c941-ee48-4a3f-8a73-2d9baec3b990** [python/cpython#78108]
BPO | [33927](https://bugs.python.org/issue33927)
--- | :---
Nosy | @rhettinger, @ezio-melotti, @matrixise, @pablogsal, @remilapeyre, @michael-kuhlmann, @CharString
PRs | <li>python/cpython#7865</li><li>python/cpython#11992</li><li>python/cpython#29478</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-06-21.10:45:40.446>
labels = ['type-bug', 'library', '3.11']
title = 'Allow json.tool to have identical infile and outfile'
updated_at = <Date 2021-11-08.22:09:34.365>
user = 'https://github.com/michael-kuhlmann'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-08.22:09:34.365>
actor = 'CharString'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-06-21.10:45:40.446>
creator = 'kuhlmann'
dependencies = []
files = []
hgrepos = []
issue_num = 33927
keywords = ['patch']
message_count = 10.0
messages = ['320151', '320152', '320173', '320302', '320326', '320328', '320329', '320368', '320729', '390853']
nosy_count = 7.0
nosy_names = ['rhettinger', 'ezio.melotti', 'matrixise', 'pablogsal', 'remi.lapeyre', 'kuhlmann', 'CharString']
pr_nums = ['7865', '11992', '29478']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue33927'
versions = ['Python 3.11']
```

</p></details>

**Comment by furkanonder** [comment]
@pablogsal The issue seems to have been solved. Can we close the issue?

```cat example.json```
```json
{"name": "John", "age": 30, "car": null}
```
After ```python -m json.tool example.json example.json```;

```cat example.json```
```json
{
    "name": "John",
    "age": 30,
    "car": null
}
```

**Comment by picnixz** [comment]
The original issue seems fixed but there was this comment: https://github.com/python/cpython/issues/89807#issuecomment-1093935603 and the subsequent reply.

Nonetheless, I think this specific issue can be closed so I'll do it. I think a new issue should be created to handle the case `--json-lines` + same in/out file.
