### ISSUE TITLE
IDLE REPL: Strange indentation

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#78141]
BPO | [33960](https://bugs.python.org/issue33960)
--- | :---
Nosy | @terryjreedy, @JulienPalard
Files | <li>[2018-06-25-223359_1920x1080_scrot.png](https://bugs.python.org/file47651/2018-06-25-223359_1920x1080_scrot.png "Uploaded as image/png at 2018-06-25.20:40:17 by @JulienPalard")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2018-06-25.20:40:17.192>
labels = ['expert-IDLE', '3.7', '3.8']
title = 'IDLE REPL: Strange indentation'
updated_at = <Date 2018-12-12.02:36:59.311>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2018-12-12.02:36:59.311>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2018-06-25.20:40:17.192>
creator = 'mdk'
dependencies = []
files = ['47651']
hgrepos = []
issue_num = 33960
keywords = []
message_count = 3.0
messages = ['320440', '320448', '320472']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'mdk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue33960'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
The first version of the fix is in 3.10.  I plan to revise in 3.11.  Note that output can be distinguished from input by giving it a noticeably different coloration in the Highlights tab of the Settings dialog.
