### ISSUE TITLE
Python 3.7.0 wont compile with SSL Support 1.1.0 > alledged missing X509_VERIFY_PARAM_set1_host()  support

### ISSUE THREAD

**Issue by 1b7855bc-133a-4788-ba63-5c39538163ad** [python/cpython#78209]
BPO | [34028](https://bugs.python.org/issue34028)
--- | :---
Nosy | @tiran, @bkline, @cjerdonek, @stratakis, @prehensilecode, @Axel, @CaymonSullivan, @joahking
Superseder | <li>bpo-43466: ssl/hashlib: Add configure option to set or auto-detect rpath to OpenSSL libs</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2021-04-19.20:02:45.151>
created_at = <Date 2018-07-03.09:13:31.460>
labels = ['expert-SSL', 'build', '3.10']
title = 'Python 3.7.0 wont compile with SSL Support 1.1.0 > alledged missing X509_VERIFY_PARAM_set1_host()  support'
updated_at = <Date 2021-04-19.20:02:45.150>
user = 'https://github.com/axel'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-19.20:02:45.150>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2021-04-19.20:02:45.151>
closer = 'christian.heimes'
components = ['SSL']
creation = <Date 2018-07-03.09:13:31.460>
creator = 'simon@simonfoley.net'
dependencies = []
files = []
hgrepos = []
issue_num = 34028
keywords = []
message_count = 20.0
messages = ['320947', '320951', '320955', '320960', '321096', '321099', '322022', '334701', '335133', '339455', '345177', '355232', '355236', '355241', '355316', '355317', '358487', '367214', '367242', '391399']
nosy_count = 13.0
nosy_names = ['christian.heimes', 'bkline', 'chris.jerdonek', 'cstratak', 'hairygristle', 'simon@simonfoley.net', 'kscheidegger', 'Phillip Middleton', 'cayman', 'malektronic', 'cjflory', 'joahking', 'Jan Wilmans']
pr_nums = []
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = '43466'
type = 'compile error'
url = 'https://bugs.python.org/issue34028'
versions = ['Python 3.10']
```

</p></details>

**Comment by NiKeYiGuN** [comment]
> I couldn't get this to work at all, python 3.7 compiled fine, but at the end it reports:
> 
> ''' *** WARNING: renaming "_ssl" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory *** WARNING: renaming "_hashlib" since importing it failed: libssl.so.1.1: cannot open shared object file: No such file or directory
> 
> Python build finished successfully!
> 
> Following modules built successfully but were removed because they could not be imported: _hashlib _ssl
> 
> Could not build the ssl module! Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host(). LibreSSL 2.6.4 and earlier do not provide the necessary APIs, [libressl-portable/portable#381](https://github.com/libressl-portable/portable/issues/381) '''
> 
> But in the end I got it to work like this:
> 
> ----- install_python3.7.sh ---- #!/bin/bash set -euo pipefail
> 
> mkdir /tmp/openssl cd /tmp/openssl wget https://www.openssl.org/source/openssl-1.1.1a.tar.gz tar -xvf openssl-1.1.1a.tar.gz cd openssl-1.1.1a ./config --prefix=/usr/local/openssl1.1.1 --openssldir=/usr/local/openssl1.1.1 make make install rm -rf /tmp/opensll
> 
> echo /usr/local/openssl1.1.1/lib > /etc/ld.so.conf.d/openssl1.1.1.conf ldconfig
> 
> mkdir /tmp/python37 wget https://www.python.org/ftp/python/3.7.3/Python-3.7.3.tgz tar xfz Python-3.7.3.tgz cd Python-3.7.3 ./configure --with-ensurepip=yes --with-openssl=/usr/local/openssl1.1.1 CFLAGS="-I/usr/local/openssl1.1.1/include" LDFLAGS="-L/usr/local/openssl1.1.1/lib" CXX=/usr/bin/g++ make make install rm -rf /tmp/python37
> 
> ldconfig --------------------
> 
> This important pieces are:
> 
> echo /usr/local/openssl1.1.1/lib > /etc/ld.so.conf.d/openssl1.1.1.conf ldconfig
> 
> to make it find the .so to load it at runtime and
> 
> ./configure --with-ensurepip=yes --with-openssl=/usr/local/openssl1.1.1 CFLAGS="-I/usr/local/openssl1.1.1/include" LDFLAGS="-L/usr/local/openssl1.1.1/lib" CXX=/usr/bin/g++
> 
> specifying the non-standard openssl-version specifically.

good!
