### ISSUE TITLE
openpty/forkpty build failure using nix package manager macOS environment

### ISSUE THREAD

**Issue by 1d3e7915-c5fd-4e7c-a38f-301ee0363845** [python/cpython#78208]
BPO | [34027](https://bugs.python.org/issue34027)
--- | :---
Nosy | @ronaldoussoren, @orivej, @ned-deily, @LnL7
PRs | <li>python/cpython#8056</li>
Files | <li>[darwin-libutil.patch](https://bugs.python.org/file47666/darwin-libutil.patch "Uploaded as text/plain at 2018-07-03.00:34:49 by @orivej")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-02.21:31:08.119>
labels = ['OS-mac', 'build', '3.9', '3.10', '3.11']
title = 'openpty/forkpty build failure using nix package manager macOS environment'
updated_at = <Date 2022-01-17.22:57:04.283>
user = 'https://github.com/LnL7'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-17.22:57:04.283>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'macOS']
creation = <Date 2018-07-02.21:31:08.119>
creator = 'LnL7'
dependencies = []
files = ['47666']
hgrepos = []
issue_num = 34027
keywords = ['patch']
message_count = 14.0
messages = ['320913', '320914', '320915', '320918', '320920', '320921', '320925', '320930', '320931', '320933', '320936', '320940', '320992', '392618']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'orivej', 'ned.deily', 'LnL7', 'lukegb']
pr_nums = ['8056']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue34027'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by reckenrode** [comment]
This can probably be closed. As of https://github.com/NixOS/nixpkgs/pull/346043, macOS support in nixpkgs looks more like a native toolchain (while still building from a bootstrap tarball). Consequently, the `libutil.h` header is not included in the default build environment anymore. Users who do need it can opt into using it with the darwin.libutil package in nixpkgs.

**Comment by emilazy** [comment]
Yes, was just coming here to say that :) As of the just‐merged https://github.com/NixOS/nixpkgs/pull/353873 we no longer patch Python for this, so unless this affects any non‐Nixpkgs environments, I think this can safely be closed.

**Comment by erlend-aasland** [comment]
Thanks for chiming in Randy and Emily; closing as outdated.
