### ISSUE TITLE
distutils is not reproducible

### ISSUE THREAD

**Issue by vstinner** [python/cpython#78214]
BPO | [34033](https://bugs.python.org/issue34033)
--- | :---
Nosy | @vstinner, @benjaminp, @encukou, @methane, @yan12125, @bmwiedemann, @jefferyto
PRs | <li>python/cpython#8057</li><li>python/cpython#8226</li>

Dependencies:
* #75558
* #78274
* #78903
* #81777

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-03.15:46:25.794>
labels = ['3.8', 'library']
title = 'distutils is not reproducible'
updated_at = <Date 2020-04-10.13:23:09.703>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-10.13:23:09.703>
actor = 'yan12125'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-07-03.15:46:25.794>
creator = 'vstinner'
dependencies = ['31377', '34093']
files = []
hgrepos = []
issue_num = 34033
keywords = ['patch']
message_count = 9.0
messages = ['320988', '320990', '320991', '321383', '321408', '321432', '321434', '337975', '359595']
nosy_count = 9.0
nosy_names = ['vstinner', 'benjamin.peterson', 'petr.viktorin', 'sascha_silbe', 'zbysz', 'methane', 'yan12125', 'bmwiedemann', 'jefferyto']
pr_nums = ['8057', '8226']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34033'
versions = ['Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
@methane: Yeah! Thank you for the https://github.com/python/cpython/commit/6dcfd6c5e3cb46543e82dc3f7234546adf4bb04a fix.

**Comment by josch** [comment]
Thank you @methane -- we are now carrying your patch in python 3.10 in Debian: https://sources.debian.org/src/python3.10/3.10.4-4/debian/patches/gh-78214.diff/

**Comment by AA-Turner** [comment]
@vstinner should this be closed now or will there be any other patches to Distutils before its removal?

A

**Comment by vstinner** [comment]
I don't know the status of this issue, you should ask @methane who is more involved in this topic.

**Comment by methane** [comment]
We have enough opening issues relating to reproducible pyc. So I agree to close this one.
