### ISSUE TITLE
[EASY] sndhdr.what() throws exceptions on unknown files

### ISSUE THREAD

**Issue by bb53ebea-2d5a-4b1f-9311-8dba1ccba5af** [python/cpython#78269]
BPO | [34088](https://bugs.python.org/issue34088)
--- | :---
Nosy | @vstinner, @ammaraskar, @lysnikolaou, @Barro, @davidawad
PRs | <li>python/cpython#8319</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-10.20:50:06.127>
labels = ['3.7', 'library']
title = '[EASY] sndhdr.what() throws exceptions on unknown files'
updated_at = <Date 2019-05-01.22:40:51.589>
user = 'https://github.com/Barro'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-01.22:40:51.589>
actor = 'davidawad'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-07-10.20:50:06.127>
creator = 'Barro'
dependencies = []
files = []
hgrepos = []
issue_num = 34088
keywords = ['patch']
message_count = 9.0
messages = ['321396', '321457', '321543', '321545', '321573', '321738', '321849', '321850', '341235']
nosy_count = 5.0
nosy_names = ['vstinner', 'ammar2', 'lys.nikolaou', 'Barro', 'davidawad']
pr_nums = ['8319']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34088'
versions = ['Python 3.7']
```

</p></details>

**Comment by hugovk** [comment]
Note the sndhdr module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AA-Turner** [comment]
Closing per Hugo's comment.

A
