### ISSUE TITLE
Asyncio StreamReader fails to close Transport

### ISSUE THREAD

**Issue by 32d36863-b68e-4e37-8cd2-94293053580a** [python/cpython#78357]
BPO | [34176](https://bugs.python.org/issue34176)
--- | :---
Nosy | @asvetlov, @1st1, @jdlh

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-21.00:30:19.386>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'Asyncio StreamReader fails to close Transport'
updated_at = <Date 2018-07-21.00:30:19.386>
user = 'https://github.com/JDLH'
```

bugs.python.org fields:
```python
activity = <Date 2018-07-21.00:30:19.386>
actor = 'JDLH'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-07-21.00:30:19.386>
creator = 'JDLH'
dependencies = []
files = []
hgrepos = []
issue_num = 34176
keywords = []
message_count = 1.0
messages = ['322047']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'JDLH']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34176'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
Python 3.7 is not supported anymore, moreover the issue does not has a reproducer to reproduce the issue and is out of date so closing. If this issue still exists, create a new issue with [reproducer](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by kumaraditya303** [comment]
Also 3.11 has rewritten ssl implementation as of https://github.com/python/cpython/pull/31275.
