### ISSUE TITLE
Reorganize C API tests

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#78453]
BPO | [34272](https://bugs.python.org/issue34272)
--- | :---
Nosy | @rhettinger, @ezio-melotti, @voidspace, @serhiy-storchaka, @miss-islington, @tirkarthi
PRs | <li>python/cpython#8551</li><li>python/cpython#8567</li><li>python/cpython#8689</li><li>python/cpython#8690</li><li>python/cpython#8691</li><li>python/cpython#10078</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-07-29.12:56:00.979>
labels = ['3.7', 'expert-C-API', '3.8', 'type-feature', 'tests']
title = 'Reorganize C API tests'
updated_at = <Date 2019-12-09.16:13:39.037>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-09.16:13:39.037>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'C API']
creation = <Date 2018-07-29.12:56:00.979>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 34272
keywords = ['patch']
message_count = 8.0
messages = ['322635', '322648', '322656', '322682', '323207', '323209', '323210', '323211']
nosy_count = 6.0
nosy_names = ['rhettinger', 'ezio.melotti', 'michael.foord', 'serhiy.storchaka', 'miss-islington', 'xtreak']
pr_nums = ['8551', '8567', '8689', '8690', '8691', '10078']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34272'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

* PR: gh-99431

* PR: gh-99614

* PR: gh-99617

**Comment by iritkatriel** [comment]
Is there anything left to do here?

**Comment by encukou** [comment]
Plenty. `test_capi/test_misc.py` still has 1800+ lines.

**Comment by vstinner** [comment]
See also issue gh-93649.

**Comment by serhiy-storchaka** [comment]
The tests were re-organized, extended, updated and re-re-organized many times.
