### ISSUE TITLE
Allow str.endswith and str.startswith to accept an iterable

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#78493]
BPO | [34312](https://bugs.python.org/issue34312)
--- | :---
Nosy | @brettcannon, @rhettinger, @taleinat, @serhiy-storchaka, @matrixise

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-08-03.17:07:54.473>
created_at = <Date 2018-08-01.20:47:42.063>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Allow str.endswith and str.startswith to accept an iterable'
updated_at = <Date 2018-08-03.17:07:54.472>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-03.17:07:54.472>
actor = 'brett.cannon'
assignee = 'none'
closed = True
closed_date = <Date 2018-08-03.17:07:54.473>
closer = 'brett.cannon'
components = ['Interpreter Core']
creation = <Date 2018-08-01.20:47:42.063>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 34312
keywords = []
message_count = 7.0
messages = ['322887', '322906', '322910', '322988', '323020', '323029', '323032']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'rhettinger', 'taleinat', 'serhiy.storchaka', 'matrixise']
pr_nums = []
priority = 'low'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34312'
versions = ['Python 3.8']
```

</p></details>

**Comment by jayaddison** [comment]
Would it be possible to consider adding `frozenset`s (also immutable) that contain strings to the acceptable prefix/suffix match types?

Rationale: I've found that in some tight loops, performing a character-in-collection check performs well when the character collection is a `frozenset`.  I'd like to re-use the same collection object for `str.startswith` and `str.endswith` calls.

For example:

```pycon
>>> characters_with_enclosures = frozenset("abdegopq")
>>>
>>> user_input = input()
'asdf'
>>> bool(any(char in characters_with_enclosures for char in user_input))
True
>>> user_input.startswith(characters_with_enclosures)  # not currently supported
```

In response to the usage-pattern concern: hopefully it's lower-likelihood that developers would write `.startswith(frozenset(...))` without learning about what a `frozenset` is than they would write `.startswith({...})` (debatable, though).
