### ISSUE TITLE
asyncio.wait should accept generator of tasks as first argument

### ISSUE THREAD

**Issue by fcdc96d4-77c1-4326-9a94-a0ac9b5246bb** [python/cpython#78530]
BPO | [34349](https://bugs.python.org/issue34349)
--- | :---
Nosy | @asvetlov, @1st1, @jnwatson, @tirkarthi, @epiphyte

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-08-06.19:41:06.692>
labels = ['3.8', 'expert-asyncio']
title = 'asyncio.wait should accept generator of tasks as first argument'
updated_at = <Date 2018-08-07.14:20:15.310>
user = 'https://github.com/jnwatson'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-07.14:20:15.310>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-08-06.19:41:06.692>
creator = 'jnwatson'
dependencies = []
files = []
hgrepos = []
issue_num = 34349
keywords = []
message_count = 2.0
messages = ['323217', '323241']
nosy_count = 5.0
nosy_names = ['asvetlov', 'yselivanov', 'jnwatson', 'xtreak', 'epiphyte']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34349'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-102761
* gh-103748

**Comment by kumaraditya303** [comment]
Since generator based coroutines are gone, now it's time to relax this check and allow generators.

**Comment by JelleZijlstra** [comment]
Allowing generators in 3.12 seems like a good idea. It's probably also useful to change the documentation in 3.10 and 3.11 to clarify that generators don't work, as #99936 asked for.

**Comment by kumaraditya303** [comment]
Let's do it.

**Comment by gvanrossum** [comment]
So there are two separate tasks here, right:
1. In 3.12, allow generators
2. In the docs for 3.10 and 3.11, explain that generators are not allowed (maybe allude to 3.12 allowing them)

**Comment by gvanrossum** [comment]
According to GH, the PR will close this issue. But it should remain open until the 3.10/3.11 docs are also updated.

**Comment by kumaraditya303** [comment]
Fixed by https://github.com/python/cpython/pull/103748
