### ISSUE TITLE
_uuid module fails to compile on FreeBSD when libuuid is installed

### ISSUE THREAD

**Issue by c139cf46-fb7c-4c62-96da-220de2afbec1** [python/cpython#78547]
BPO | [34366](https://bugs.python.org/issue34366)
--- | :---
Nosy | @mgorny
PRs | <li>python/cpython#8711</li>
Files | <li>[dev-lang:python-3.7.0:20180809-062928.log](https://bugs.python.org/file47735/dev-lang%3Apython-3.7.0%3A20180809-062928.log "Uploaded as text/x-log at 2018-08-09.06:48:30 by @mgorny"): dev-lang:python-3.7.0:20180809-062928.log</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-08-09.06:48:30.753>
labels = ['extension-modules', '3.8', 'build', '3.7']
title = '_uuid module fails to compile on FreeBSD when libuuid is installed'
updated_at = <Date 2018-08-09.07:26:17.521>
user = 'https://github.com/mgorny'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-09.07:26:17.521>
actor = 'mgorny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2018-08-09.06:48:30.753>
creator = 'mgorny'
dependencies = []
files = ['47735']
hgrepos = []
issue_num = 34366
keywords = ['patch']
message_count = 1.0
messages = ['323317']
nosy_count = 1.0
nosy_names = ['mgorny']
pr_nums = ['8711']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue34366'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Closed in favor of the duplicate issue #85077 (if it was not already solved in other issue).

In any case, thank you for your report and PR, @mgorny. Sorry that we did not have resources to solve it at time.
