### ISSUE TITLE
subprocess: execution of batch-files (.cmd/.bat) is vulnerable in python for windows / insufficient escape

### ISSUE THREAD

**Issue by 73642e62-fab4-4a87-8ab5-e3560d6d3869** [python/cpython#78670]
BPO | [34489](https://bugs.python.org/issue34489)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @sebres
PRs | <li>python/cpython#8906</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-08-24.19:44:10.049>
labels = ['type-security', '3.8', '3.7', 'library', 'OS-windows']
title = 'subprocess: execution of batch-files (.cmd/.bat) is vulnerable in python for windows / insufficient escape'
updated_at = <Date 2018-08-30.11:59:33.937>
user = 'https://github.com/sebres'
```

bugs.python.org fields:
```python
activity = <Date 2018-08-30.11:59:33.937>
actor = 'sebres'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2018-08-24.19:44:10.049>
creator = 'sebres'
dependencies = []
files = []
hgrepos = []
issue_num = 34489
keywords = []
message_count = 4.0
messages = ['324013', '324186', '324321', '324379']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'sebres']
pr_nums = ['8906']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue34489'
versions = ['Python 2.7', 'Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by gpshead** [comment]
This looks like a duplicate of https://github.com/python/cpython/issues/77696 ?  (though there's more useful info in this one?)

**Comment by zooba** [comment]
Agreed, it's the same (non-)issue. I can't see us doing anything to change how Windows handles `CreateProcess(a batch file)`.

**Comment by arhadthedev** [comment]
> Agreed, it's the same (non-)issue. I can't see us doing anything to change how Windows handles CreateProcess(a batch file).

Thus closing.
