### ISSUE TITLE
Path.relative_to() taking multiple arguments could be better documented

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#78707]
BPO | [34526](https://bugs.python.org/issue34526)
--- | :---
Nosy | @anntzer, @barneygale
PRs | <li>python/cpython#31368</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-08-28.08:42:29.205>
labels = ['easy', '3.11', '3.9', '3.10', 'docs']
title = 'Path.relative_to() taking multiple arguments could be better documented'
updated_at = <Date 2022-02-16.08:01:06.637>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-16.08:01:06.637>
actor = 'python-dev'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2018-08-28.08:42:29.205>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 34526
keywords = ['patch', 'easy']
message_count = 1.0
messages = ['324224']
nosy_count = 4.0
nosy_names = ['docs@python', 'python-dev', 'Antony.Lee', 'barneygale']
pr_nums = ['31368']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34526'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-94469
* gh-118780

**Comment by barneygale** [comment]
I think this is a mis-feature and we should look at deprecating + removing it, rather than documenting it.

Consider that pathlib has many other methods that accept a single *other* path, like `rename()`, `replace()`, `symlink_to()` and `hardlink_to()`.

The only methods that should support `*args` should be `joinpath()` and the `PurePath` initialiser IMO.

**Comment by JelleZijlstra** [comment]
Agree that this is a misfeature. We'll have to go through a deprecation cycle to remove it though, since it's at least kind of documented.
