### ISSUE TITLE
Don't use AC_RUN_IFELSE to determine float endian

### ISSUE THREAD

**Issue by 09a29c59-b75e-4923-8c78-4e1147afdd70** [python/cpython#78766]
BPO | [34585](https://bugs.python.org/issue34585)
--- | :---
Nosy | @tim-one, @mdickinson, @benjaminp, @rossburton, @yan12125
PRs | <li>python/cpython#9085</li>
Files | <li>[0001-Don-t-do-runtime-test-to-get-float-byte-order.patch](https://bugs.python.org/file47788/0001-Don-t-do-runtime-test-to-get-float-byte-order.patch "Uploaded as text/plain at 2018-09-05.10:57:21 by @rossburton")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-19.06:25:56.225>
created_at = <Date 2018-09-05.10:57:22.362>
labels = ['build', '3.8']
title = "Don't use AC_RUN_IFELSE to determine float endian"
updated_at = <Date 2018-09-19.06:49:08.815>
user = 'https://github.com/rossburton'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-19.06:49:08.815>
actor = 'benjamin.peterson'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-19.06:25:56.225>
closer = 'benjamin.peterson'
components = ['Build']
creation = <Date 2018-09-05.10:57:22.362>
creator = 'rossburton'
dependencies = []
files = ['47788']
hgrepos = []
issue_num = 34585
keywords = ['patch']
message_count = 3.0
messages = ['324627', '325705', '325708']
nosy_count = 5.0
nosy_names = ['tim.peters', 'mark.dickinson', 'benjamin.peterson', 'rossburton', 'yan12125']
pr_nums = ['9085']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue34585'
versions = ['Python 3.8']
```

</p></details>

**Comment by libTorrentUser** [comment]
Unfortunately ax_c_float_words_bigendian.m4 evil magical trickery does not work if certain compiler flags are used. Using gcc and -flto seems to be enough to break it.
