### ISSUE TITLE
Importing certain modules while debugging raises an exception

### ISSUE THREAD

**Issue by c92cce2f-9f0d-4e0b-8dd5-571a113a6991** [python/cpython#78790]
BPO | [34609](https://bugs.python.org/issue34609)
--- | :---
Nosy | @brettcannon, @terryjreedy, @ncoghlan, @pitrou, @taleinat, @ericsnowcurrently, @pppery, @csabella, @tirkarthi
Superseder | <li>bpo-33065: IDLE debugger: failure stepping through module loading</li>
Files | <li>[test_main.py](https://bugs.python.org/file47790/test_main.py "Uploaded as text/plain at 2018-09-07.18:30:27 by piscvau@yahoo.fr")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-09-23.18:14:03.033>
created_at = <Date 2018-09-07.18:30:27.399>
labels = ['type-bug', '3.8']
title = 'Importing certain modules while debugging raises an exception'
updated_at = <Date 2018-09-29.10:24:57.937>
user = 'https://bugs.python.org/piscvauyahoofr'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-29.10:24:57.937>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2018-09-23.18:14:03.033>
closer = 'terry.reedy'
components = []
creation = <Date 2018-09-07.18:30:27.399>
creator = 'piscvau@yahoo.fr'
dependencies = []
files = ['47790']
hgrepos = []
issue_num = 34609
keywords = []
message_count = 10.0
messages = ['324779', '324788', '324798', '324814', '324815', '324953', '326158', '326168', '326664', '326674']
nosy_count = 10.0
nosy_names = ['brett.cannon', 'terry.reedy', 'ncoghlan', 'pitrou', 'taleinat', 'eric.snow', 'ppperry', 'cheryl.sabella', 'xtreak', 'piscvau@yahoo.fr']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '33065'
type = 'behavior'
url = 'https://bugs.python.org/issue34609'
versions = ['Python 3.6', 'Python 3.8']
```

</p></details>

**Comment by exarkun** [comment]
> Following up, I was able to recreate under 3.8 using pdb in powershell, so it's not just in IDLE.
> 
> ```
> Traceback (most recent call last):
>   File "N:\projects\cpython\lib\pdb.py", line 1697, in main
>     pdb._runscript(mainpyfile)
>   File "N:\projects\cpython\lib\pdb.py", line 1566, in _runscript
>     self.run(statement)
>   File "N:\projects\cpython\lib\bdb.py", line 586, in run
>     exec(cmd, globals, locals)
>   File "<string>", line 1, in <module>
>   File "c:\users\onedrive\desktop\step.py", line 1, in <module>
>     import unittest
>   File "<frozen importlib._bootstrap>", line 980, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 149, in __enter__
>   File "<frozen importlib._bootstrap>", line 101, in acquire
> KeyError: 14104
> ```

This is the same as https://github.com/python/cpython/issues/91351
