### ISSUE TITLE
Store startup modules as C structures for 20%+ startup speed improvement

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#78871]
BPO | [34690](https://bugs.python.org/issue34690)
--- | :---
Nosy | @warsaw, @nascheme, @ncoghlan, @larryhastings, @ericvsmith, @phsilva, @ericsnowcurrently, @tirkarthi, @1ace
PRs | <li>python/cpython#9320</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/larryhastings'
closed_at = None
created_at = <Date 2018-09-14.21:23:50.626>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Store startup modules as C structures for 20%+ startup speed improvement'
updated_at = <Date 2020-12-18.18:11:31.629>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-18.18:11:31.629>
actor = '1ace'
assignee = 'larry'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2018-09-14.21:23:50.626>
creator = 'larry'
dependencies = []
files = []
hgrepos = []
issue_num = 34690
keywords = ['patch']
message_count = 6.0
messages = ['325401', '325403', '325407', '325410', '325745', '325872']
nosy_count = 9.0
nosy_names = ['barry', 'nascheme', 'ncoghlan', 'larry', 'eric.smith', 'phsilva', 'eric.snow', 'xtreak', '1ace']
pr_nums = ['9320']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34690'
versions = ['Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
IIUC, this has been superseded by the deepfreeze efforts of the Faster CPython team. Suggesting to close this together with the linked PR.

**Comment by kumaraditya303** [comment]
Yes, this is superseded by deepfreeze [^1] in 3.11.

[^1]: https://docs.python.org/3.11/whatsnew/3.11.html#faster-startup

**Comment by erlend-aasland** [comment]
Closing as duplicate, then.
