### ISSUE TITLE
IDLE: Don't freeze Shell when user enters sys.stdout.shell.console

### ISSUE THREAD

**Issue by 0cec372f-a045-4947-ac31-79b1ae5356f3** [python/cpython#78889]
BPO | [34708](https://bugs.python.org/issue34708)
--- | :---
Nosy | @terryjreedy, @iritkatriel
Files | <li>[fail.py](https://bugs.python.org/file47808/fail.py "Uploaded as text/plain at 2018-09-17.02:53:00 by Harrison Chudleigh"): After running this file, IDLE hangs or crashes, depending on version.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2018-09-17.02:53:01.502>
labels = ['3.10', 'expert-IDLE', '3.9', 'type-crash', '3.11']
title = 'Odd crashes/freezes when sys.stdout.shell.console is typed'
updated_at = <Date 2021-10-18.21:41:12.838>
user = 'https://bugs.python.org/HarrisonChudleigh'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-18.21:41:12.838>
actor = 'iritkatriel'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2018-09-17.02:53:01.502>
creator = 'Harrison Chudleigh'
dependencies = []
files = ['47808']
hgrepos = []
issue_num = 34708
keywords = []
message_count = 5.0
messages = ['325509', '325510', '325569', '404215', '404224']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'Harrison Chudleigh', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue34708'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-121876
* gh-121911
* gh-121912

**Comment by terryjreedy** [comment]
- [ ] Handle bad (unpickleable) Shell attribute requests.
- [ ] Rename `tags` to `_stream` (to show that private) and `shell` to `__shell` (to mangle).
- [ ] Turn `__attributes` into set rather than dict.

**Comment by terryjreedy** [comment]
3.11.0b5 on Windows:
```
>>> sys.stdout.shell.console

... 
... 
```
After 1st Enter, cursor move to blank line and nothing happens.  2nd and 3rd Enters and '...' appears.  This seems like a separate bug in secondary prompt mechanism.  Otherwise, ^C has no effect, Restart works.

**Comment by dlamblin** [comment]
If `shell` were renamed `__shell` would that mean breaking those few programs that try to find out if they're in an IDLE shell by doing something like:
```python
from sys import stdout

MODE = None
try:
    MODE = stdout.shell
except AttributeError:
    pass

def mode_write(*args, sep='  ', end='\n', color='stdout'):
    "Prints with color if OUT_MODE is the IDLE Shell"
    if OUT_MODE:
        _ = OUT_MODE.write(sep.join(args) + end, color)
    else:
        print(*args, sep=sep, end=end)

if __name__ == '__main__':
    mode_write('This tends to be blue.')
    mode_write('This tends to be red.', 'COMMENT')
    mode_write('This tends to be green.', 'STRING')
```

**Comment by terryjreedy** [comment]
Yes.  I have recommended `import sys; "idlelib.run" in sys.modules` for detecting IDLE but I have seen `import sys; hasattr(sys.stdout, 'shell'` or equivalent.  While this is a private implementation detail and would normally not care, the fact that it is accessible without importing from idlelib suggests that I should either leave the name alone or leave the name with a dummy value.

**Comment by terryjreedy** [comment]
As near as I can tell, sys.stdxyz.shell is indeed the pyshell.shell instance of pyshell.PyShell, which inherits from outwin.OutputWindow.  What is confusing is that shell has a console attribute, which is the pseudofile that prints to the input region of the Shell window, while shell becomes self.tkconsole in the pyshell.ModifiedInterpreter instance and is registered as 'console' in rpc.  See `MI.__init__`, MI.start_subprocess, `PyShell.__init__`, run.MyHandler.handle, and bits in rpc.

I don't think the interp and flist proxies are accessible in the same way that the shell/console proxy is.

**Comment by terryjreedy** [comment]
Running IDLE from Command Prompt, `sys.stdout.shell.console` results in
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "f:\dev\3x\Lib\tkinter\__init__.py", line 2068, in __call__
    return self.func(*args)
           ~~~~~~~~~^^^^^^^
  File "f:\dev\3x\Lib\tkinter\__init__.py", line 862, in callit
    func(*args)
    ~~~~^^^^^^^
  File "f:\dev\3x\Lib\idlelib\pyshell.py", line 582, in poll_subprocess
    response = clt.pollresponse(self.active_seq, wait=0.05)
  File "f:\dev\3x\Lib\idlelib\rpc.py", line 450, in pollresponse
    self.putmessage((seq, response))
    ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "f:\dev\3x\Lib\idlelib\rpc.py", line 335, in putmessage
    s = dumps(message)
  File "f:\dev\3x\Lib\idlelib\rpc.py", line 62, in dumps
    p.dump(obj)
    ~~~~~~^^^^^
TypeError: cannot pickle 'module' object
```
Should check currect doc whether TypeError instead of PicklingError is OK.  p is a subclass of Pickler that should not change error types.  The dumps call is wrapped as follows:
```
        try:
            s = dumps(message)
        except pickle.PicklingError:
            print("Cannot pickle:", repr(message), file=sys.__stderr__)
            raise
```
Will see what happens if TypeError is caught, or whether can convert to AttributeError or even string message.
