### ISSUE TITLE
typing.get_type_hints doesn't know about typeshed

### ISSUE THREAD

**Issue by 5c0d0cd9-bbdc-4a00-8830-a38a1efc5f8a** [python/cpython#78881]
BPO | [34700](https://bugs.python.org/issue34700)
--- | :---
Nosy | @gvanrossum, @bdarnell, @jstasiak, @ilevkivskyi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ilevkivskyi'
closed_at = None
created_at = <Date 2018-09-15.20:10:00.514>
labels = ['type-feature', '3.7']
title = "typing.get_type_hints doesn't know about typeshed"
updated_at = <Date 2019-05-20.15:40:49.639>
user = 'https://github.com/bdarnell'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-20.15:40:49.639>
actor = 'gvanrossum'
assignee = 'levkivskyi'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2018-09-15.20:10:00.514>
creator = 'Ben.Darnell'
dependencies = []
files = []
hgrepos = []
issue_num = 34700
keywords = []
message_count = 4.0
messages = ['325455', '326040', '326313', '342922']
nosy_count = 4.0
nosy_names = ['gvanrossum', 'Ben.Darnell', 'jstasiak', 'levkivskyi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34700'
versions = ['Python 3.7']
```

</p></details>

**Comment by JelleZijlstra** [comment]
There are several improvements to this area now:
- Many standard library types are now generic at runtime thanks to PEP 585 (point 3 in the OP)
- We now have `inspect.get_annotations` that can extract annotations without trying to evaluate them. As Guido alludes to, this is a better fit for users like Sphinx that just want to display the annotations.
