### ISSUE TITLE
Asyncio documentation for recursive coroutines is lacking

### ISSUE THREAD

**Issue by 2e21d8c0-bf12-41b2-a80b-536f2b20ec7d** [python/cpython#78882]
BPO | [34701](https://bugs.python.org/issue34701)
--- | :---
Nosy | @asvetlov, @1st1, @zorn96
PRs | <li>python/cpython#9339</li>
Files | <li>[asyncio_await_from_self_example.py](https://bugs.python.org/file47805/asyncio_await_from_self_example.py "Uploaded as text/plain at 2018-09-16.03:54:14 by @zorn96"): Example of undocumented behavior</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-16.03:54:15.711>
labels = ['type-feature', '3.7', 'docs', 'expert-asyncio']
title = 'Asyncio documentation for recursive coroutines is lacking'
updated_at = <Date 2018-09-16.04:15:11.331>
user = 'https://github.com/zorn96'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-16.04:15:11.331>
actor = 'azaria.zornberg'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'asyncio']
creation = <Date 2018-09-16.03:54:15.711>
creator = 'azaria.zornberg'
dependencies = []
files = ['47805']
hgrepos = []
issue_num = 34701
keywords = ['patch']
message_count = 3.0
messages = ['325468', '325469', '325470']
nosy_count = 4.0
nosy_names = ['asvetlov', 'docs@python', 'yselivanov', 'azaria.zornberg']
pr_nums = ['9339']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue34701'
versions = ['Python 3.4', 'Python 3.5', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
I don't see anything special about recursive coroutines. It is just a fact that event loop switches only when there are more than 1 task running otherwise it runs sequentially.  IMHO no docs update is required here.

**Comment by gvanrossum** [comment]
I agree, it looks like the confusion is about whether `await` allows the event loop to run or not, and that depends on other things -- e.g. `await asyncio.sleep(0)` always switches to the event loop, whereas `await` on something that returns a value immediately doesn't. I think this is something for tutorials to call out (and I assume they do), not something that should be explained in the docs (where the folks who are most likely going to run into this won't be looking).
