### ISSUE TITLE
aclose() doesn't stop raise StopAsyncIteration / GeneratorExit to __anext__()

### ISSUE THREAD

**Issue by 51678be9-6a33-49aa-9ca6-8112369a1e17** [python/cpython#78911]
BPO | [34730](https://bugs.python.org/issue34730)
--- | :---
Nosy | @Cito, @njsmith, @asvetlov, @dimaqq, @1st1, @dfee

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-19.00:27:25.958>
labels = ['3.10', 'expert-asyncio']
title = "aclose() doesn't stop raise StopAsyncIteration / GeneratorExit to __anext__()"
updated_at = <Date 2020-08-21.03:12:19.223>
user = 'https://github.com/dfee'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-21.03:12:19.223>
actor = 'Dima.Tisnek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-09-19.00:27:25.958>
creator = 'dfee'
dependencies = []
files = []
hgrepos = []
issue_num = 34730
keywords = []
message_count = 8.0
messages = ['325699', '325704', '325920', '325928', '325929', '375739', '375742', '375743']
nosy_count = 6.0
nosy_names = ['cito', 'njs', 'asvetlov', 'Dima.Tisnek', 'yselivanov', 'dfee']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34730'
versions = ['Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
IMO we should not change anything here but recommend the users to not close async generators concurrently with docs. Doing any change here is going to be both complex probably backwards incompatible as users might be relying on the current behavior.

**Comment by gvanrossum** [comment]
Sounds good. I agree that the behavior by now is ingrained and will be hard to change without breaking working user code, and not really worth it. So let's document it.

**Comment by kumaraditya303** [comment]
Documentation will be taken care of in https://github.com/python/cpython/issues/100108
