### ISSUE TITLE
When function in tracing returns None, tracing continues.

### ISSUE THREAD

**Issue by a5ae9dfd-b19f-4ed7-b289-70236f9e865e** [python/cpython#78980]
BPO | [34799](https://bugs.python.org/issue34799)
--- | :---
Nosy | @fabioz
Files | <li>[issue_in_tracing_func.py](https://bugs.python.org/file47822/issue_in_tracing_func.py "Uploaded as text/plain at 2018-09-25.15:06:19 by @fabioz"): Test case showing error.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-25.15:06:20.105>
labels = ['type-bug', '3.7']
title = 'When function in tracing returns None, tracing continues.'
updated_at = <Date 2018-09-25.15:06:20.105>
user = 'https://github.com/fabioz'
```

bugs.python.org fields:
```python
activity = <Date 2018-09-25.15:06:20.105>
actor = 'fabioz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2018-09-25.15:06:20.105>
creator = 'fabioz'
dependencies = []
files = ['47822']
hgrepos = []
issue_num = 34799
keywords = []
message_count = 1.0
messages = ['326360']
nosy_count = 1.0
nosy_names = ['fabioz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34799'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by brandtbucher** [comment]
Fixed the docs in [`d9246c7`](https://github.com/python/cpython/commit/d9246c7b734b8958da03494045208681d95f5b74).
