### ISSUE TITLE
Counter-intuitive behavior of Server.close() / wait_closed()

### ISSUE THREAD

**Issue by d39fc50f-b0e1-4101-b3a2-610bbbc7700a** [python/cpython#79033]
BPO | [34852](https://bugs.python.org/issue34852)
--- | :---
Nosy | @asvetlov, @cjerdonek, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-09-30.14:16:34.429>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'Counter-intuitive behavior of Server.close() / wait_closed()'
updated_at = <Date 2021-05-30.16:58:41.511>
user = 'https://bugs.python.org/aymericaugustin'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-30.16:58:41.511>
actor = 'aymeric.augustin'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-09-30.14:16:34.429>
creator = 'aymeric.augustin'
dependencies = []
files = []
hgrepos = []
issue_num = 34852
keywords = []
message_count = 3.0
messages = ['326725', '326732', '394772']
nosy_count = 4.0
nosy_names = ['asvetlov', 'chris.jerdonek', 'aymeric.augustin', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34852'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-98582
* gh-111260
* gh-111336
* gh-111424

**Comment by kumaraditya303** [comment]
IMO it should wait for all connections to be closed and the current behavior seems like an oversight.

**Comment by gvanrossum** [comment]
Yeah, there seem to be an unfinished thought here. Some of the logic I've discovered:
- The only waiter ever added to `self._waiters` is `wait_closed()` itself
- `_attach()` / `_detach()` serve as a kind of reference count, counting transports
- The only calls are in `_SelectorTransport` and `_ProactorBasePipeTransport`
- `_detach` is called when the connection is lost, and wakes up the `wait_closed()` call when the count reaches zero

It does seem likely that `wait_closed()` just shouldn't check for `self._sockets` and then all will be well?

Somebody should give this a try.

CC: @aaugustin @1st1

**Comment by gvanrossum** [comment]
I think I got it (GH-79033). I don't think we should backport this, even though it's fixing a bug -- code that got the close sequence wrong but managed to get away with it might suddenly hang.

I need to think about a test for the correct behavior

**Comment by 1st1** [comment]
The committed https://github.com/python/cpython/pull/98582 broke `wait_closed()`.

```python
class Server:
    # ...

    async def wait_closed(self):
        if self._waiters is None or self._active_count == 0:
            return
        waiter = self._loop.create_future()
        self._waiters.append(waiter)
        await waiter
```

 It now can incorrectly assume that the `Server` is closed and return prematurely, while `Server.close()` is still working.

* `self._waiters` is a list of futures that wait until the server is closed
* `_active_count` is used to track how many open client connection to the Server are there

Before https://github.com/python/cpython/pull/98582, the condition was `self._sockets is None or self._waiters is None`, which was interpreted as "if we don't have anymore server-side sockets for this Server object OR we've already closed it -- return".

Now the `self._waiters is None or self._active_count == 0` condition reads as "if we've already closed Server OR there are no active client connections then return". So in the case where we still have an open server socket `wait_closed()` now happily returns, which it shouldn't.

**Comment by 1st1** [comment]
This appears to be a 3.12 regression and IMO the commit should be just reverted. I don't understand the motivation for the change from the commit message of 5d09d11aa0b89aeba187f4f520728ccaf4fc5ac1. The added test is synthetic, calling directly the underlying private API, something that we shouldn't do in general, aiming for higher-level functional tests instead.

cc @gvanrossum @kumaraditya303

**Comment by gvanrossum** [comment]
The test that works in 3.11 but would fail in 3.12 does the following:
```
loop.call_soon(server.close)
await server.wait_closed()
```
We do have to fix that in 3.12.1.

**Comment by Dreamsorcerer** [comment]
> Before #98582, the condition was `self._sockets is None or self._waiters is None`, which was interpreted as "if we don't have anymore server-side sockets for this Server object OR we've already closed it -- return".

Based on our aiohttp code, I was originally under the impression that `wait_closed()` simply waited for the sockets to stop listening, rather than the connections to close (see #111260).

However, I think the referenced change looks correct, because the very first thing that `close()` does, even before doing anything to the sockets, is `self._sockets = None`. Therefore, I don't see how the old `if` statement can be interpreted in any way other than "if close() has already been called". It doesn't seem to have anything to do with the open sockets.

Having looked at all this, I think aiohttp shouldn't be calling `wait_closed()` at all.

**Comment by Dreamsorcerer** [comment]
> The test that works in 3.11 but would fail in 3.12 does the following:
> 
> ```
> loop.call_soon(server.close)
> await server.wait_closed()
> ```
> 
> We do have to fix that in 3.12.1.

In 3.11, wouldn't that still be an issue, depending on timing? From my reading of the code, wait_closed() would create a waiter, then as soon as the server wakes up, it will resolve that waiter. I think it's irrelevant whether the close() method is called later or not, right?

**Comment by gvanrossum** [comment]
I don't see the timing issue you refer to. The waiter is immediately (without intervening `await`, so the server can't run) added to `self._waiters`. It will only be woken up by `_wakeup()`, called by `_detach()` and `close()` once `self._active_count` reaches zero. That doesn't feel like "as soon as the server wakes up" to me.

**Comment by Dreamsorcerer** [comment]
Right, I think some of those things could be named better. But, doesn't that still happen when connections drop to 0 normally then? i.e. If we just don't call `.close()`, then `wait_closed()` would still return if the connections are dropped, but the server is still running?

**Comment by gvanrossum** [comment]
`_detach()` which is called whenever a client connection is dropped, only calls `_wakeup()` when `_sockets` is `None`, which is only the case once `close()` is called.

Maybe what you're after is the same race condition that @1st1 reported a few comments back: if `wait_closed()` is called *before* `close()` (e.g. immediately after `loop.call_soon(server.close)`) it will now return immediately (assuming there isn't already another waiter) instead waiting for the last connection to wind down.

I wonder if the fix is to change the condition at the top of `wait_closed()` to
```py
        if self._sockets is None and self._active_count == 0:
            return
```

**Comment by Dreamsorcerer** [comment]
Sounds good. Another option may have been to have an asyncio.Event to signal when the server is closed, and then it could simply await on that.

**Comment by gvanrossum** [comment]
Yeah, but internally an Event is implemented similarly, and this code was already there… Can you approve the PR?

**Comment by encukou** [comment]
The latest PR is merged. Is there more to do in this issue?

**Comment by gvanrossum** [comment]
I think it's done. Closing.
