### ISSUE TITLE
Change .js mime to "text/javascript"

### ISSUE THREAD

**Issue by bfa6ff68-66ab-4238-ba96-ce19a98186b7** [python/cpython#79056]
BPO | [34875](https://bugs.python.org/issue34875)
--- | :---
Nosy | @asvetlov, @ammaraskar, @MylesBorins, @180909, @arhadthedev
PRs | <li>python/cpython#9678</li><li>python/cpython#30740</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-10-02.22:28:39.501>
labels = ['library', '3.9', '3.10', '3.11']
title = 'Change .js mime to "text/javascript"'
updated_at = <Date 2022-01-21.11:06:31.601>
user = 'https://github.com/MylesBorins'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-21.11:06:31.601>
actor = 'arhadthedev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-10-02.22:28:39.501>
creator = 'mylesborins'
dependencies = []
files = []
hgrepos = []
issue_num = 34875
keywords = ['patch']
message_count = 7.0
messages = ['326920', '326923', '327006', '327007', '327010', '345883', '411109']
nosy_count = 5.0
nosy_names = ['asvetlov', 'ammar2', 'mylesborins', 'wangjiahua', 'arhadthedev']
pr_nums = ['9678', '30740']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue34875'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by mathiasbynens** [comment]
Following up to this old thread + [this earlier discussion](https://github.com/python/cpython/pull/3908#discussion_r222443254): [RFC 9239](https://www.rfc-editor.org/rfc/rfc9239) now unequivocally resolves this disagreement. Patch: https://github.com/python/cpython/pull/92627

**Comment by encukou** [comment]
This was reported later in #97646, and changed in #97934 (Python 3.12).
