### ISSUE TITLE
LWPCookieJar.save() creates *.lwp file in 644 mode

### ISSUE THREAD

**Issue by e2a53e08-d9ff-4ce2-9a94-6b72883af0fc** [python/cpython#79096]
BPO | [34915](https://bugs.python.org/issue34915)
--- | :---
Nosy | @vadmium, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-10-06.13:58:56.935>
labels = ['type-security', '3.8', '3.9', 'expert-IO', '3.7', 'library', '3.10']
title = 'LWPCookieJar.save() creates *.lwp file in 644 mode'
updated_at = <Date 2021-03-14.06:38:53.953>
user = 'https://bugs.python.org/aleskva'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-14.06:38:53.953>
actor = 'martin.panter'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'IO']
creation = <Date 2018-10-06.13:58:56.935>
creator = 'aleskva'
dependencies = []
files = []
hgrepos = []
issue_num = 34915
keywords = []
message_count = 4.0
messages = ['327246', '339126', '341422', '388664']
nosy_count = 3.0
nosy_names = ['martin.panter', 'aleskva', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue34915'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ambv** [comment]
FWIW Firefox also creates user profile directories with 700 so that looks like precedent to me.

**Comment by ambv** [comment]
@AA-Turner removed the security branches from this issue suggesting that this isn't a security vulnerability in need of patching. Following this train of thought, , I'm not entirely sold on the idea that this change is even a "bug fix". It looks more like an enhancement to me, which I would err on especially given its backwards incompatibility. It's @pablogsal's call, I would consider it for 3.11 but not for 3.10.

@tiran's got more experience with evaluating security issues so he can also weigh in on what we should do here.

**Comment by AA-Turner** [comment]
> @AA-Turner removed the security branches from this issue suggesting that this isn't a security vulnerability in need of patching. 

Sorry, I should have added a comment -- to confirm, my thinking was along the same lines as yours.

A

**Comment by ambv** [comment]
Oops, since I already landed gh-93463 in 3.12, I'll do the changes @tiran wants in a separate PR.

**Comment by pSub** [comment]
Thank you for your review @tiran, I learned a lot. And thank you @ambv for addressing the review findings.

**Comment by pablogsal** [comment]
I'm find landing this in 3.11 as long as it goes in before next beta

**Comment by ambv** [comment]
Alright, I'll do the backport now in one commit.
