### ISSUE TITLE
json dump silently converts int keys to string

### ISSUE THREAD

**Issue by 2ed20de7-d59d-46e7-8b2e-4af79de46af9** [python/cpython#79153]
BPO | [34972](https://bugs.python.org/issue34972)
--- | :---
Nosy | @facundobatista, @ericvsmith, @zooba, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2018-10-14.11:33:13.954>
created_at = <Date 2018-10-13.10:16:46.343>
labels = ['invalid', 'type-bug', 'library']
title = 'json dump silently converts int keys to string'
updated_at = <Date 2020-04-06.06:14:52.103>
user = 'https://bugs.python.org/My-TienNguyen'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-06.06:14:52.103>
actor = 'stub'
assignee = 'none'
closed = True
closed_date = <Date 2018-10-14.11:33:13.954>
closer = 'My-Tien Nguyen'
components = ['Library (Lib)']
creation = <Date 2018-10-13.10:16:46.343>
creator = 'My-Tien Nguyen'
dependencies = []
files = []
hgrepos = []
issue_num = 34972
keywords = []
message_count = 9.0
messages = ['327649', '327650', '327654', '327684', '327688', '327703', '361302', '365838', '365840']
nosy_count = 7.0
nosy_names = ['facundobatista', 'eric.smith', 'stub', 'steve.dower', 'xtreak', 'My-Tien Nguyen', 'Stub2']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34972'
versions = ['Python 3.6']
```

</p></details>

**Comment by GJoe2** [comment]
I had this issue recently and spend some time . While I understand json format requires keys to be strings and its specified in [RFC 7159](https://datatracker.ietf.org/doc/html/rfc7159.html)  that doesn't mean every user should know about that, I suggest writing a warning in the documentation [front page](https://docs.python.org/3/library/json.html#implementation-limitations) would save time for everyone

**Comment by facundobatista** [comment]
@GJoe2 +1, I think a paragraph there is worth it. May you suggest some wording or a draft for it? Thanks!

We should probably have a new ticket for this doc change; if you open one, please assign it to me so I can take care. Thanks again!

**Comment by ericvsmith** [comment]
I agree that a warning in the documentation would be helpful.

**Comment by GJoe2** [comment]
@facundobatista  I open a new issue at #137533, check it out
