### ISSUE TITLE
Python throws “SyntaxError: Non-UTF-8 code start with \xe8...” when parse source file

### ISSUE THREAD

**Issue by 078afb2b-1ab4-4f6d-8f2b-884f4edbd327** [python/cpython#79160]
BPO | [34979](https://bugs.python.org/issue34979)
--- | :---
Nosy | @terryjreedy, @ezio-melotti, @serhiy-storchaka, @zhangyangyu, @tirkarthi, @ausaki
PRs | <li>python/cpython#9923</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/serhiy-storchaka'
closed_at = <Date 2019-11-16.17:37:53.843>
created_at = <Date 2018-10-14.02:01:38.987>
labels = ['interpreter-core', 'type-bug']
title = 'Python throws \xe2\x80\x9cSyntaxError: Non-UTF-8 code start with \\xe8...\xe2\x80\x9d when parse source file'
updated_at = <Date 2019-11-16.17:37:53.840>
user = 'https://github.com/ausaki'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-16.17:37:53.840>
actor = 'ausaki'
assignee = 'serhiy.storchaka'
closed = True
closed_date = <Date 2019-11-16.17:37:53.843>
closer = 'ausaki'
components = ['Interpreter Core']
creation = <Date 2018-10-14.02:01:38.987>
creator = 'ausaki'
dependencies = []
files = []
hgrepos = []
issue_num = 34979
keywords = ['patch']
message_count = 11.0
messages = ['327686', '327689', '327697', '327699', '327702', '327706', '327709', '327878', '356711', '356741', '356760']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ezio.melotti', 'serhiy.storchaka', 'xiang.zhang', 'xtreak', 'ausaki']
pr_nums = ['9923']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue34979'
versions = ['Python 3.6']
```

</p></details>

**Comment by elonzh** [comment]
We are currently trying to manage Python environments and dependencies using uv. Unfortunately, our production application uses Python 3.7. 

The prerequisite for upgrading Python is that we first use uv to manage and lock dependencies to ensure that the Python upgrade does not cause breaking changes. Judging from community feedback, many users have encountered this issue when using uv, and I'm wondering if their scenarios are similar to ours. Although Python 3.7 has indeed reached its end-of-life, we very much hope that this PR can be merged, as it would be a great help for migrating to uv.
