### ISSUE TITLE
year 2038 problem in compileall.py

### ISSUE THREAD

**Issue by 05ed1d68-9f72-4552-af38-41e9d578a41d** [python/cpython#79171]
BPO | [34990](https://bugs.python.org/issue34990)
--- | :---
Nosy | @jwilk, @serhiy-storchaka, @matrixise, @bmwiedemann, @ammaraskar, @miss-islington, @tirkarthi
PRs | <li>python/cpython#9892</li><li>python/cpython#19651</li><li>python/cpython#19708</li><li>python/cpython#27928</li><li>python/cpython#27929</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-08-24.15:13:34.226>
created_at = <Date 2018-10-15.11:22:16.253>
labels = ['build', '3.9', '3.10', '3.11']
title = 'year 2038 problem in compileall.py'
updated_at = <Date 2022-02-21.11:46:17.662>
user = 'https://github.com/bmwiedemann'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-21.11:46:17.662>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2021-08-24.15:13:34.226>
closer = 'ammar2'
components = ['Build']
creation = <Date 2018-10-15.11:22:16.253>
creator = 'bmwiedemann'
dependencies = []
files = []
hgrepos = []
issue_num = 34990
keywords = ['patch']
message_count = 13.0
messages = ['327743', '327747', '327748', '327749', '327750', '327751', '327753', '327774', '360270', '367679', '400200', '400214', '400215']
nosy_count = 7.0
nosy_names = ['jwilk', 'serhiy.storchaka', 'matrixise', 'bmwiedemann', 'ammar2', 'miss-islington', 'xtreak']
pr_nums = ['9892', '19651', '19708', '27928', '27929']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue34990'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by suryansh18saxena** [comment]
Hi! I'm a first-time contributor and would love to fix this. Could you please assign me this issue? Thanks!

**Comment by vstinner** [comment]
> Hi! I'm a first-time contributor and would love to fix this. Could you please assign me this issue? Thanks!

Hi, this issue is closed, there is nothing to do.
