### ISSUE TITLE
Allow ipaddres.IPv4/v6Address in asyncio.create_server

### ISSUE THREAD

**Issue by 2a851be1-cc39-4b80-acbd-b2e3c1ee4cb2** [python/cpython#79200]
BPO | [35019](https://bugs.python.org/issue35019)
--- | :---
Nosy | @asvetlov, @methane, @1st1, @remilapeyre, @kenbassford@verizon.net, @DamlaAltun
PRs | <li>python/cpython#9956</li><li>python/cpython#17434</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-10-18.16:28:24.199>
labels = ['type-feature', '3.8', '3.9', '3.10', 'expert-asyncio']
title = 'Allow ipaddres.IPv4/v6Address in asyncio.create_server'
updated_at = <Date 2020-06-12.04:12:00.038>
user = 'https://github.com/kenbassfordverizonnet'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-12.04:12:00.038>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2018-10-18.16:28:24.199>
creator = 'bassford'
dependencies = []
files = []
hgrepos = []
issue_num = 35019
keywords = ['patch']
message_count = 6.0
messages = ['327984', '327991', '327992', '327999', '370853', '371330']
nosy_count = 6.0
nosy_names = ['asvetlov', 'methane', 'yselivanov', 'remi.lapeyre', 'bassford', 'DamlaAltun']
pr_nums = ['9956', '17434']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35019'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
Couldn't you just call `str` on ipaddress to make this work? I don't think it is worth adding support for `ipaddress` otherwise there would be lot of feature requests to support it in every `asyncio` APIs which accepts ipaddresses.

**Comment by kumaraditya303** [comment]
I am -1 on adding this, @gvanrossum what do you think?

**Comment by gvanrossum** [comment]
The intended design is that calling `str()` on an `IPv?Address` instance produces the desired string (like '1.0.0.1'). If we were going to call `str()` inside every `asyncio` API function that takes an address we'd be introducing new failure modes when an invalid object is passed. Special-casing the `IPv?Address` class would create a dependency on `ipaddress` in `asyncio` which we'd rather avoid.

I don't think the error is that messy -- you get
```
TypeError: argument of type 'IPv4Address' is not iterable
```
as soon as you call `start_server()`, which to me seems a pretty good indication of what's wrong.
