### ISSUE TITLE
Make TypeError message less ambiguous

### ISSUE THREAD

**Issue by a9d73443-5fab-46e4-8c20-7201ca9abf23** [python/cpython#79258]
BPO | [35077](https://bugs.python.org/issue35077)
--- | :---
Nosy | @rhettinger, @terryjreedy, @srinivasreddy, @tirkarthi
PRs | <li>python/cpython#10132</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-10-26.15:52:43.478>
labels = ['type-feature', '3.10']
title = 'Make TypeError message less ambiguous'
updated_at = <Date 2021-09-24.17:31:16.599>
user = 'https://bugs.python.org/coyot'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-24.17:31:16.599>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2018-10-26.15:52:43.478>
creator = 'coyot'
dependencies = []
files = []
hgrepos = []
issue_num = 35077
keywords = ['patch']
message_count = 11.0
messages = ['328565', '328567', '328580', '328587', '328596', '328597', '328598', '328604', '328834', '387630', '402579']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'thatiparthy', 'xtreak', 'coyot']
pr_nums = ['10132']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35077'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
> https://bugs.python.org/issue44110 did some improvements to error message to include type.

This makes the current wording less ambiguous - since the type of the index is explicitly mentioned, the "string" of "string index" could not be referring to that.
