### ISSUE TITLE
Add a new Include/cpython/ subdirectory for the "CPython API" with implementation details

### ISSUE THREAD

**Issue by vstinner** [python/cpython#79315]
BPO | [35134](https://bugs.python.org/issue35134)
--- | :---
Nosy | @brettcannon, @ncoghlan, @vstinner, @jkloth, @ericsnowcurrently, @serhiy-storchaka, @shihai1991, @erlend-aasland, @nw0
PRs | <li>python/cpython#10285</li><li>python/cpython#10624</li><li>python/cpython#10679</li><li>python/cpython#10680</li><li>python/cpython#10727</li><li>python/cpython#10728</li><li>python/cpython#10731</li><li>python/cpython#10732</li><li>python/cpython#10733</li><li>python/cpython#10739</li><li>python/cpython#10754</li><li>python/cpython#10764</li><li>python/cpython#12840</li><li>python/cpython#12842</li><li>python/cpython#13430</li><li>python/cpython#13431</li><li>python/cpython#14213</li><li>python/cpython#18052</li><li>python/cpython#18395</li><li>python/cpython#18490</li><li>python/cpython#18493</li><li>python/cpython#18494</li><li>python/cpython#19756</li><li>python/cpython#23701</li><li>python/cpython#23988</li><li>python/cpython#24550</li><li>python/cpython#24561</li><li>python/cpython#24770</li><li>python/cpython#24922</li><li>python/cpython#28957</li><li>python/cpython#28958</li><li>python/cpython#28964</li><li>python/cpython#28968</li><li>python/cpython#29042</li><li>python/cpython#29044</li><li>python/cpython#30923</li><li>python/cpython#32383</li><li>python/cpython#32384</li><li>python/cpython#32385</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-30.23:33:02.262>
created_at = <Date 2018-11-01.12:46:49.299>
labels = ['interpreter-core', '3.8']
title = 'Add a new Include/cpython/ subdirectory for the "CPython API" with implementation details'
updated_at = <Date 2022-04-07.00:29:55.966>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-07.00:29:55.966>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-30.23:33:02.262>
closer = 'vstinner'
components = ['Interpreter Core']
creation = <Date 2018-11-01.12:46:49.299>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 35134
keywords = ['patch']
message_count = 61.0
messages = ['329060', '329087', '329123', '329124', '329126', '329290', '329292', '330161', '330162', '330165', '330246', '330261', '330276', '330282', '330283', '330285', '330296', '330324', '330331', '330336', '330337', '330446', '330447', '330463', '330467', '330477', '330478', '330480', '330512', '330556', '330557', '330594', '340283', '340285', '342876', '342881', '346014', '360338', '361542', '361922', '361923', '367536', '382771', '383970', '387105', '387179', '387327', '389285', '394491', '403952', '403955', '403957', '403964', '403967', '403983', '404248', '404252', '411772', '416906', '416910', '416912']
nosy_count = 9.0
nosy_names = ['brett.cannon', 'ncoghlan', 'vstinner', 'jkloth', 'eric.snow', 'serhiy.storchaka', 'shihai1991', 'erlendaasland', 'nw0']
pr_nums = ['10285', '10624', '10679', '10680', '10727', '10728', '10731', '10732', '10733', '10739', '10754', '10764', '12840', '12842', '13430', '13431', '14213', '18052', '18395', '18490', '18493', '18494', '19756', '23701', '23988', '24550', '24561', '24770', '24922', '28957', '28958', '28964', '28968', '29042', '29044', '30923', '32383', '32384', '32385']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue35134'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-99723
* gh-139725
* gh-139729
* gh-139730
* gh-139731

**Comment by vstinner** [comment]
I merged 4 more changes. It seems like the separation between the limited C API and the "CPython" C API is now complete, project started in 2018 :-)

**Comment by ericsnowcurrently** [comment]
An important job well done!
