### ISSUE TITLE
sqlite3: optionally autoconvert table_info's DATETIME fields

### ISSUE THREAD

**Issue by ca731509-3229-4446-a84b-ad5ad17b5cb3** [python/cpython#79326]
BPO | [35145](https://bugs.python.org/issue35145)
--- | :---
Nosy | @berkerpeksag, @matrixise, @pganssle, @jondo
Files | <li>[SQLiteStudio-3449.sqlite](https://bugs.python.org/file47905/SQLiteStudio-3449.sqlite "Uploaded as application/octet-stream at 2018-11-05.11:49:15 by @jondo")</li><li>[2017v2-reduced.db](https://bugs.python.org/file47911/2017v2-reduced.db "Uploaded as application/octet-stream at 2018-11-06.09:43:06 by @jondo")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-02.12:16:24.101>
labels = ['3.8', 'type-bug', 'library']
title = "sqlite3: optionally autoconvert table_info's DATETIME fields"
updated_at = <Date 2019-07-25.11:30:28.046>
user = 'https://github.com/jondo'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-25.11:30:28.046>
actor = 'jondo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-11-02.12:16:24.101>
creator = 'jondo'
dependencies = []
files = ['47905', '47911']
hgrepos = []
issue_num = 35145
keywords = []
message_count = 14.0
messages = ['329128', '329129', '329157', '329214', '329225', '329226', '329227', '329291', '329309', '329319', '329350', '330393', '335544', '348435']
nosy_count = 5.0
nosy_names = ['ghaering', 'berker.peksag', 'matrixise', 'p-ganssle', 'jondo']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35145'
versions = ['Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
As per [discussion on Discourse](https://discuss.python.org/t/deprecate-default-built-in-sqlite3-converters-and-adapters/15781?u=erlendaasland), we will deprecate the built-in, default adapters and converters. Thus, this issue is now superseded by gh-90016.
