### ISSUE TITLE
locale: setlocale(..., 'eo') sets non-existing locale

### ISSUE THREAD

**Issue by ff164935-b039-4486-b258-64b1d98020a6** [python/cpython#79344]
BPO | [35163](https://bugs.python.org/issue35163)
--- | :---
Nosy | @malemburg, @carmenbianca
PRs | <li>python/cpython#17901</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-04.15:54:37.498>
labels = ['3.7', 'library']
title = "locale: setlocale(..., 'eo') sets non-existing locale"
updated_at = <Date 2020-01-08.01:52:07.078>
user = 'https://github.com/carmenbianca'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-08.01:52:07.078>
actor = 'carmenbianca'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-11-04.15:54:37.498>
creator = 'carmenbianca'
dependencies = []
files = []
hgrepos = []
issue_num = 35163
keywords = ['patch']
message_count = 1.0
messages = ['329235']
nosy_count = 2.0
nosy_names = ['lemburg', 'carmenbianca']
pr_nums = ['17901']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35163'
versions = ['Python 3.7']
```

</p></details>

**Comment by arhadthedev** [comment]
Esperanto locales were indeed fixed in gh-422 but then reverted in gh-713. According to gh-64286, this is because CPython uses X11 names from `locale.alias` instead of GLibc aliases and both alternatives lead to bugs.
