### ISSUE TITLE
Doc: Namespace Packages: Inconsistent documentation of __loader__ being None

### ISSUE THREAD

**Issue by JulienPalard** [python/cpython#79362]
BPO | [35181](https://bugs.python.org/issue35181)
--- | :---
Nosy | @warsaw, @brettcannon, @ncoghlan, @ericvsmith, @ericsnowcurrently, @JulienPalard, @csabella, @maggyero, @miss-islington
PRs | <li>python/cpython#10376</li><li>python/cpython#10016</li><li>python/cpython#15190</li><li>python/cpython#22872</li><li>python/cpython#22873</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/warsaw'
closed_at = None
created_at = <Date 2018-11-06.22:29:09.600>
labels = ['type-feature', '3.8', '3.9', '3.10', 'docs']
title = 'Doc: Namespace Packages: Inconsistent documentation of __loader__ being None'
updated_at = <Date 2020-10-24.03:04:47.832>
user = 'https://github.com/JulienPalard'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-24.03:04:47.832>
actor = 'maggyero'
assignee = 'barry'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2018-11-06.22:29:09.600>
creator = 'mdk'
dependencies = []
files = []
hgrepos = []
issue_num = 35181
keywords = ['patch']
message_count = 12.0
messages = ['329392', '329419', '339814', '341173', '346316', '346317', '379227', '379253', '379254', '379256', '379260', '379512']
nosy_count = 10.0
nosy_names = ['barry', 'brett.cannon', 'ncoghlan', 'eric.smith', 'docs@python', 'eric.snow', 'mdk', 'cheryl.sabella', 'maggyero', 'miss-islington']
pr_nums = ['10376', '10016', '15190', '22872', '22873']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35181'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by warsaw** [comment]
#15190 has been merged, so I believe all issues mentioned in this issue have been resolved.  The issue just never got closed, so closing it now.  Please follow up here or open a new issue and @ mention me if anyone thinks otherwise.  Thanks for all the contributions.
