### ISSUE TITLE
[Windows] Python 3.7 initializes LC_CTYPE locale at startup, causing performance issue on msvcrt isdigit()

### ISSUE THREAD

**Issue by d3086080-57f0-4750-b9f3-69de5a278a68** [python/cpython#79376]
BPO | [35195](https://bugs.python.org/issue35195)
--- | :---
Nosy | @pfmoore, @vstinner, @tjguk, @zware, @zooba, @tirkarthi, @Dragoljub
Files | <li>[test_isdigit.c](https://bugs.python.org/file47928/test_isdigit.c "Uploaded as text/plain at 2018-11-13.01:33:34 by cgohlke")</li><li>[setup.py](https://bugs.python.org/file47929/setup.py "Uploaded as text/plain at 2018-11-13.01:36:50 by cgohlke")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-08.22:56:21.101>
labels = ['3.7', '3.8', 'expert-IO', 'OS-windows', 'performance']
title = '[Windows] Python 3.7 initializes LC_CTYPE locale at startup, causing performance issue on msvcrt isdigit()'
updated_at = <Date 2019-05-17.09:56:11.306>
user = 'https://github.com/Dragoljub'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-17.09:56:11.306>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows', 'IO']
creation = <Date 2018-11-08.22:56:21.101>
creator = 'Dragoljub'
dependencies = []
files = ['47928', '47929']
hgrepos = []
issue_num = 35195
keywords = []
message_count = 23.0
messages = ['329490', '329545', '329573', '329575', '329587', '329589', '329592', '329641', '329743', '329745', '329786', '329787', '329789', '329790', '329791', '329792', '329793', '329828', '329854', '329855', '330007', '341901', '342702']
nosy_count = 8.0
nosy_names = ['paul.moore', 'vstinner', 'tim.golden', 'cgohlke', 'zach.ware', 'steve.dower', 'xtreak', 'Dragoljub']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue35195'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
What's the status of this issue in Python 3.10 and 3.11?

**Comment by iritkatriel** [comment]
> What's the status of this issue in Python 3.10 and 3.11?

Since we don't backport performance improvements, does it matter?

**Comment by vstinner** [comment]
Since reports are inactive for 3 years (latest message in May 2019), I close the issue.

There are other good reasons to initialize the LC_CTYPE locale on Windows at Python startup.

I didn't try, but I suppose that a workaround is to **set the LC_CTYPE locale to the ``"C"`` locale** to get back Python 3.6 performance on the C function isdigit(). I don't know Windows internals about how locales and isdigit() are implemented.

I didn't get well the use case and the reporter is inactive, I just close the issue.
