### ISSUE TITLE
Get the test suite passing with clang Memory Sanitizer enabled

### ISSUE THREAD

**Issue by gpshead** [python/cpython#79395]
BPO | [35214](https://bugs.python.org/issue35214)
--- | :---
Nosy | @Yhg1s, @gpshead, @benjaminp, @alex, @serhiy-storchaka, @izbyshev, @pablogsal, @miss-islington, @epicfaace
PRs | <li>python/cpython#10479</li><li>python/cpython#10492</li><li>python/cpython#10493</li><li>python/cpython#10499</li><li>python/cpython#10500</li><li>python/cpython#10501</li><li>python/cpython#10503</li><li>python/cpython#10504</li><li>python/cpython#10505</li><li>python/cpython#10506</li><li>python/cpython#10522</li><li>python/cpython#10523</li><li>python/cpython#10538</li><li>python/cpython#11375</li><li>python/cpython#11375</li><li>python/cpython#11375</li><li>python/cpython#11378</li><li>python/cpython#11378</li><li>python/cpython#11378</li><li>python/cpython#11385</li><li>python/cpython#11385</li><li>python/cpython#11385</li><li>python/cpython#11388</li><li>python/cpython#11388</li><li>python/cpython#11388</li><li>python/cpython#11389</li><li>python/cpython#11389</li><li>python/cpython#11389</li><li>python/cpython#11391</li><li>python/cpython#11391</li><li>python/cpython#11391</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = None
created_at = <Date 2018-11-12.07:26:34.927>
labels = ['type-security', 'interpreter-core', '3.7', '3.8', 'extension-modules', 'build', 'tests']
title = 'Get the test suite passing with clang Memory Sanitizer enabled'
updated_at = <Date 2019-08-14.20:02:32.630>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-14.20:02:32.630>
actor = 'gregory.p.smith'
assignee = 'gregory.p.smith'
closed = False
closed_date = None
closer = None
components = ['Build', 'Extension Modules', 'Interpreter Core', 'Tests']
creation = <Date 2018-11-12.07:26:34.927>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 35214
keywords = ['patch']
message_count = 28.0
messages = ['329723', '329750', '329759', '329777', '329798', '329803', '329804', '329805', '329806', '329807', '329808', '329809', '329810', '329867', '329870', '329875', '329929', '331639', '331642', '332778', '332784', '332796', '332797', '332799', '332801', '332804', '349639', '349742']
nosy_count = 9.0
nosy_names = ['twouters', 'gregory.p.smith', 'benjamin.peterson', 'alex', 'serhiy.storchaka', 'izbyshev', 'pablogsal', 'miss-islington', 'epicfaace']
pr_nums = ['10479', '10492', '10493', '10499', '10500', '10501', '10503', '10504', '10505', '10506', '10522', '10523', '10538', '11375', '11375', '11375', '11378', '11378', '11378', '11385', '11385', '11385', '11388', '11388', '11388', '11389', '11389', '11389', '11391', '11391', '11391']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'security'
url = 'https://bugs.python.org/issue35214'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by vstinner** [comment]
@gpshead:
> Nope, work remains to be done. I've got an msan buildbot system waiting but haven't had time to follow up on figuring out what remains in a while. (getting a functioning memory sanitizer build is... finnicky to say the least)

What's the status in 2023? Maybe it's time to close the issue. If needed, new a issue can be created.

**Comment by gpshead** [comment]
i mean while I think it'd be useful, i'm not working on it.

**Comment by vstinner** [comment]
Sadly, last time I tried MSAN, I got issues with stat() and OpenSSL:

* Python: https://github.com/python/cpython/issues/91043
* stat: https://github.com/llvm/llvm-project/issues/54131
* OpenSSL: https://github.com/openssl/openssl/issues/17784

**Comment by vstinner** [comment]
Sometimes tried last March: https://github.com/python/cpython/issues/91043#issuecomment-1458810011
