### ISSUE TITLE
urllib.request.urlopen throws on some valid FTP files

### ISSUE THREAD

**Issue by f7948214-dd3a-4389-b0ff-c540916f6296** [python/cpython#79417]
BPO | [35236](https://bugs.python.org/issue35236)
--- | :---
Nosy | @ianliu
PRs | <li>python/cpython#10520</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-11-13.19:20:41.097>
labels = ['3.7', 'type-bug', 'library']
title = 'urllib.request.urlopen throws on some valid FTP files'
updated_at = <Date 2018-11-13.19:24:56.483>
user = 'https://github.com/ianliu'
```

bugs.python.org fields:
```python
activity = <Date 2018-11-13.19:24:56.483>
actor = 'python-dev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-11-13.19:20:41.097>
creator = 'Ian Liu Rodrigues'
dependencies = []
files = []
hgrepos = []
issue_num = 35236
keywords = ['patch']
message_count = 1.0
messages = ['329862']
nosy_count = 1.0
nosy_names = ['Ian Liu Rodrigues']
pr_nums = ['10520']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35236'
versions = ['Python 3.7']
```

</p></details>

**Comment by arhadthedev** [comment]
Closing after https://github.com/python/cpython/pull/10520#issuecomment-1517241834:

> The library shouldn't add an extra path if the URL didn't have it. The user can deal with a incorrect server by using the intended path (if it needs to end with '/' for directory access with ftp).
>
> Closing this issue as won't fix.
