### ISSUE TITLE
SQLite incorrect row count for UPDATE

### ISSUE THREAD

**Issue by fecee5cb-643e-45e8-b8c2-4838fbe6606d** [python/cpython#79579]
BPO | [35398](https://bugs.python.org/issue35398)
--- | :---
Nosy | @berkerpeksag, @lysnikolaou, @tirkarthi, @erlend-aasland
PRs | <li>python/cpython#10913</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2018-12-04.02:27:45.503>
labels = ['3.8', '3.7', 'library']
title = 'SQLite incorrect row count for UPDATE'
updated_at = <Date 2021-08-11.21:01:29.425>
user = 'https://bugs.python.org/MontanaLow'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-11.21:01:29.425>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2018-12-04.02:27:45.503>
creator = 'Montana Low'
dependencies = []
files = []
hgrepos = []
issue_num = 35398
keywords = ['patch']
message_count = 4.0
messages = ['331006', '331069', '331090', '399417']
nosy_count = 7.0
nosy_names = ['ghaering', 'zzzeek', 'berker.peksag', 'lys.nikolaou', 'xtreak', 'Montana Low', 'erlendaasland']
pr_nums = ['10913']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35398'
versions = ['Python 2.7', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
Now that we require SQLite 3.7.15, we can safely use [sqlite3_stmt_readonly](https://www.sqlite.org/c3ref/stmt_readonly.html) to determine if we should update `.rowcount` or not. The API returns true for SELECT queries, which is also the case today. The API is pretty conservative, and returns false for cases where a query _might_ modify the database. In those cases, we may end up with `.rowcount` being zero. That is perfectly fine.

I see no reason not to use `sqlite3_stmt_readonly` to solve this.

**Comment by erlend-aasland** [comment]
> I see no reason not to use sqlite3_stmt_readonly to solve this.

@animalize made me change my mind about that, so I made a competing PR: gh-93623

Thanks for pushing, Ma Lin.

**Comment by erlend-aasland** [comment]
Fixed by:

- main: #93623
- 3.11: #93800
- 3.10: #93801
