### ISSUE TITLE
Enable manylinux1 builds on Pipelines for CI testing

### ISSUE THREAD

**Issue by zooba** [python/cpython#79864]
BPO | [35683](https://bugs.python.org/issue35683)
--- | :---
Nosy | @warsaw, @terryjreedy, @zware, @zooba, @moreati
PRs | <li>python/cpython#11493</li><li>python/cpython#11493</li><li>python/cpython#11493</li><li>python/cpython#11651</li><li>python/cpython#11651</li><li>python/cpython#11651</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-08.04:19:11.952>
labels = ['3.8', 'build', '3.7']
title = 'Enable manylinux1 builds on Pipelines for CI testing'
updated_at = <Date 2019-01-22.20:33:21.371>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-22.20:33:21.371>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2019-01-08.04:19:11.952>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 35683
keywords = ['patch', 'patch', 'patch']
message_count = 6.0
messages = ['333209', '333891', '333904', '334227', '334235', '334236']
nosy_count = 5.0
nosy_names = ['barry', 'terry.reedy', 'zach.ware', 'steve.dower', 'Alex.Willmer']
pr_nums = ['11493', '11493', '11493', '11651', '11651', '11651']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue35683'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by furkanonder** [comment]
@zooba Issue seems have been resolved. Can we close the issue?

**Comment by zooba** [comment]
Abandoned, rather than resolved, but I doubt we'll come back to it given the complexity of the space within manylinux these days.
