### ISSUE TITLE
traceback.clear_frames manages to deadlock a background task

### ISSUE THREAD

**Issue by f8d26a69-72f1-4539-8174-9eb936191981** [python/cpython#79932]
BPO | [35751](https://bugs.python.org/issue35751)
--- | :---
Nosy | @asvetlov, @1st1, @tvoinarovskyi
Files | <li>[test_async_deadlock.py](https://bugs.python.org/file48059/test_async_deadlock.py "Uploaded as text/plain at 2019-01-16.10:34:07 by @tvoinarovskyi"): Script to reproduce issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-16.10:34:07.787>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'traceback.clear_frames manages to deadlock a background task'
updated_at = <Date 2019-01-17.00:50:59.457>
user = 'https://github.com/tvoinarovskyi'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-17.00:50:59.457>
actor = 'tvoinarovskyi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-01-16.10:34:07.787>
creator = 'tvoinarovskyi'
dependencies = []
files = ['48059']
hgrepos = []
issue_num = 35751
keywords = []
message_count = 4.0
messages = ['333759', '333770', '333775', '333808']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'tvoinarovskyi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue35751'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-111792

**Comment by kumaraditya303** [comment]
`traceback.clear_frames` can close generators too so this is not special to coroutines and `asyncio`. I guess the simple solution here is "don't do that".

**Comment by gvanrossum** [comment]
@iritkatriel ^^

**Comment by iritkatriel** [comment]
I think this is the fix:

```
diff --git a/Objects/frameobject.c b/Objects/frameobject.c
index dd69207571..a512acf3f0 100644
--- a/Objects/frameobject.c
+++ b/Objects/frameobject.c
@@ -949,7 +949,8 @@ frame_clear(PyFrameObject *f, PyObject *Py_UNUSED(ignored))
 {
     if (f->f_frame->owner == FRAME_OWNED_BY_GENERATOR) {
         PyGenObject *gen = _PyFrame_GetGenerator(f->f_frame);
-        if (gen->gi_frame_state == FRAME_EXECUTING) {
+        if (gen->gi_frame_state == FRAME_EXECUTING ||
+            gen->gi_frame_state == FRAME_SUSPENDED) {
             goto running;
         }
         _PyGen_Finalize((PyObject *)gen);
```


But when I apply it we get two failures from tests that seem to imply that the current behaviour is a feature:

```
======================================================================
ERROR: test_clear_executing_generator (test.test_frame.ClearTest.test_clear_executing_generator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython/Lib/test/test_frame.py", line 112, in test_clear_executing_generator
    f.clear()
RuntimeError: cannot clear an executing frame

======================================================================
ERROR: test_clear_generator (test.test_frame.ClearTest.test_clear_generator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/iritkatriel/src/cpython/Lib/test/test_frame.py", line 78, in test_clear_generator
    gen.gi_frame.clear()
RuntimeError: cannot clear an executing frame

----------------------------------------------------------------------
```

**Comment by kumaraditya303** [comment]
> But when I apply it we get two failures from tests that seem to imply that the current behaviour is a feature:

I had already tried this and hence I wrote `simple solution here is "don't do that".` :)

**Comment by iritkatriel** [comment]
I think we should consider changing it.

**Comment by iritkatriel** [comment]
Note the confusion in the comments in test_clear_executing_generator:

# Attempting to clear an executing generator frame is forbidden.

and then (when the frame is suspended)

# Clearing the frame closes the generator

The second one was added [later](https://github.com/python/cpython/commit/dbfc129cc8f2a3ea3e6a0b7e6492887212923bc6) - the bpo issue justifies with just "the variable f wasn't used, let's use it for something". 

Was there ever a conscious decision that clearing a suspended frame should be allowed, and that it closes the generator?

We could add a close() function and deprecate clear() on a suspended frame.

**Comment by markshannon** [comment]
> Was there ever a conscious decision that clearing a suspended frame should be allowed, and that it closes the generator?

That closing a frame closes the generator, yes. Something to do with PEP 442.

That clearing a suspended frame should be allowed, I don't know.

Why not change `assertRaises()` to not close suspended generator/coroutines?

**Comment by iritkatriel** [comment]
> Why not change assertRaises() to not close suspended generator/coroutines?

I think we could either change generator.frame() to disallow it or traceback.clear_frames() to skip those frames. assertRaises is too high level to care about this.

Currently traceback.clear_frames() swallows exceptions from clear(), and the exception comes from clearing a running (but not a suspended) frame. So either we change frame.clear() to also raise on a suspended frame, or we change the code in traceback.clear_frame() to check for suspended/running instead of relying on the exception.

**Comment by iritkatriel** [comment]
I've created a PR to deprecate clearing suspended frames, add an option to raise a RuntimeError in that case, and use this option in ``traceback.clear_frames``.

https://github.com/python/cpython/pull/111792
