### ISSUE TITLE
Rewrite asyncio signal handler

### ISSUE THREAD

**Issue by asvetlov** [python/cpython#79930]
BPO | [35749](https://bugs.python.org/issue35749)
--- | :---
Nosy | @vstinner, @njsmith, @asvetlov, @1st1, @sourcejedi
PRs | <li>python/cpython#11577</li><li>python/cpython#11577</li><li>python/cpython#11577</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-16.08:17:25.991>
labels = ['3.8', 'type-feature', '3.7', 'expert-asyncio']
title = 'Rewrite asyncio signal handler'
updated_at = <Date 2020-10-21.16:43:27.154>
user = 'https://github.com/asvetlov'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-21.16:43:27.154>
actor = 'sourcejedi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-01-16.08:17:25.991>
creator = 'asvetlov'
dependencies = []
files = []
hgrepos = []
issue_num = 35749
keywords = ['patch', 'patch', 'patch']
message_count = 5.0
messages = ['333751', '333768', '333783', '333784', '379220']
nosy_count = 5.0
nosy_names = ['vstinner', 'njs', 'asvetlov', 'yselivanov', 'sourcejedi']
pr_nums = ['11577', '11577', '11577']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35749'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
`PidfdChildWatcher` and `ThreadedChildWatcher` don't install signal handlers for `SIGCHLD` so this is not a issue anymore.

**Comment by gvanrossum** [comment]
(It could still be an issue for _other_ signals, if people use them and send them at high frequency. But how likely is that, given that signals are such a crock anyways.)
