### ISSUE TITLE
inspect module does not implement introspection API for asynchronous generators

### ISSUE THREAD

**Issue by 9769cacc-ca60-4529-a16c-b53ba0a671de** [python/cpython#79940]
BPO | [35759](https://bugs.python.org/issue35759)
--- | :---
Nosy | @ncoghlan, @1st1, @tirkarthi, @tkren
PRs | <li>python/cpython#11590</li><li>python/cpython#11590</li>
Files | <li>[0001-inspect-add-introspection-API-for-asynchronous-gener.patch](https://bugs.python.org/file48066/0001-inspect-add-introspection-API-for-asynchronous-gener.patch "Uploaded as text/plain at 2019-01-17.12:34:49 by @tkren"): Initial patch for getasyncgenstate and getasyncgenlocals</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-17.12:34:49.495>
labels = ['3.8', 'type-feature', 'library']
title = 'inspect module does not implement introspection API for asynchronous generators'
updated_at = <Date 2019-01-17.14:15:35.489>
user = 'https://github.com/tkren'
```

bugs.python.org fields:
```python
activity = <Date 2019-01-17.14:15:35.489>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-01-17.12:34:49.495>
creator = 'tkren'
dependencies = []
files = ['48066']
hgrepos = []
issue_num = 35759
keywords = ['patch']
message_count = 2.0
messages = ['333861', '333870']
nosy_count = 4.0
nosy_names = ['ncoghlan', 'yselivanov', 'xtreak', 'tkren']
pr_nums = ['11590', '11590']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35759'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-102605

**Comment by kumaraditya303** [comment]
I needed this today and was surprised that it wasn't implemented. I'll review the PR.
