### ISSUE TITLE
shared memory construct to avoid need for serialization between processes

### ISSUE THREAD

**Issue by applio** [python/cpython#79994]
BPO | [35813](https://bugs.python.org/issue35813)
--- | :---
Nosy | @brettcannon, @nascheme, @rhettinger, @terryjreedy, @ronaldoussoren, @pitrou, @osvenskan, @giampaolo, @skrah, @pmp-p, @ambv, @ericsnowcurrently, @1st1, @applio
PRs | <li>python/cpython#11664</li><li>python/cpython#11664</li><li>python/cpython#11664</li><li>python/cpython#11816</li><li>python/cpython#11816</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/applio'
closed_at = None
created_at = <Date 2019-01-24.04:02:05.382>
labels = ['3.8', 'type-feature', 'library']
title = 'shared memory construct to avoid need for serialization between processes'
updated_at = <Date 2019-12-10.07:52:25.564>
user = 'https://github.com/applio'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-10.07:52:25.564>
actor = 'xdegaye'
assignee = 'davin'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-01-24.04:02:05.382>
creator = 'davin'
dependencies = []
files = []
hgrepos = []
issue_num = 35813
keywords = ['patch', 'patch', 'patch']
message_count = 57.0
messages = ['334278', '334737', '334789', '334797', '334798', '334799', '334805', '334806', '334809', '334817', '334820', '334821', '334822', '334835', '334934', '334945', '334957', '334963', '335030', '335032', '335194', '335195', '335262', '335273', '335282', '335284', '335360', '335362', '335366', '335622', '335660', '335682', '335689', '335694', '335696', '335697', '335700', '335711', '335715', '335719', '335731', '335789', '335797', '336182', '336294', '336298', '336336', '336383', '336386', '336388', '336395', '336400', '336423', '336429', '336430', '338180', '341920']
nosy_count = 15.0
nosy_names = ['brett.cannon', 'nascheme', 'rhettinger', 'terry.reedy', 'ronaldoussoren', 'pitrou', 'osvenskan', 'giampaolo.rodola', 'skrah', 'pmpp', 'lukasz.langa', 'eric.snow', 'Pam.McANulty', 'yselivanov', 'davin']
pr_nums = ['11664', '11664', '11664', '11816', '11816']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35813'
versions = ['Python 3.8']
```

</p></details>

**Comment by furkanonder** [comment]
@applio Is there anything else to do for this ticket?

**Comment by nascheme** [comment]
It looks to me like this could be closed.  The request for `ShareableList.close()` and `ShareableList.unlink()` could be extracted into a new issue.  It's a reasonable enhancement request.  Without digging deep into the code, it seems reasonable to me to consider `.shm` an internal detail.

**Comment by picnixz** [comment]
Closing as completed as per Neil's suggestion. Let's open a new issue for improvements on `ShareableList` if needed.
