### ISSUE TITLE
datetime: Expand scope of fromisoformat to include all of ISO 8601.

### ISSUE THREAD

**Issue by 037a2f6e-7b45-4e0e-807e-ea1ef102675f** [python/cpython#80010]
BPO | [35829](https://bugs.python.org/issue35829)
--- | :---
Nosy | @brettcannon, @abalkin, @jwilk, @agronholm, @dlenski, @rdb, @ammaraskar, @mehaase, @pganssle, @hongweipeng, @godlygeek

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-01-25.19:36:47.536>
labels = ['type-feature', 'library', '3.11']
title = 'datetime: parse "Z" timezone suffix in fromisoformat()'
updated_at = <Date 2022-02-02.17:32:27.477>
user = 'https://github.com/rdb'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-02.17:32:27.477>
actor = 'p-ganssle'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-01-25.19:36:47.536>
creator = 'rdb'
dependencies = []
files = []
hgrepos = []
issue_num = 35829
keywords = []
message_count = 14.0
messages = ['334365', '334368', '334370', '334372', '334378', '334430', '349163', '350643', '367533', '367695', '385309', '405759', '411713', '412385']
nosy_count = 11.0
nosy_names = ['brett.cannon', 'belopolsky', 'jwilk', 'alex.gronholm', 'dlenski', 'rdb', 'ammar2', 'mehaase', 'p-ganssle', 'hongweipeng', 'godlygeek']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35829'
versions = ['Python 3.11']
```

</p></details>

**Comment by pganssle** [comment]
For the historical record, originally this was slated to include an expansion to parse all of ISO 8601, but after a discussion with @godlygeek, I was convinced of the wisdom of deliberately excluding the formats with non-second fractional components. No one uses these obscure formats, and supporting them would be an invitation for people to introduce bugs into their code.

I don't think anyone wants this:

```python
>>> datetime.fromisoformat("2020-01-01T01:05.211")
datetime.datetime(2020, 1, 1, 1, 5, 12, 660000)
```

**Comment by hauntsaninja** [comment]
Does anything remain to be done here?

**Comment by pganssle** [comment]
I think this is done, closing.
