### ISSUE TITLE
Add pickler hook for the user to customize the serialization of user defined functions and types.

### ISSUE THREAD

**Issue by 78212f07-2619-4b41-b0fc-42fe2922b059** [python/cpython#80081]
BPO | [35900](https://bugs.python.org/issue35900)
--- | :---
Nosy | @pitrou, @avassalotti, @serhiy-storchaka, @ogrisel, @pierreglaser
PRs | <li>python/cpython#12499</li><li>python/cpython#12588</li>
Files | <li>[test_hook.py](https://bugs.python.org/file48101/test_hook.py "Uploaded as text/plain at 2019-02-05.14:40:22 by @pierreglaser")</li><li>[pickler_hook.patch](https://bugs.python.org/file48102/pickler_hook.patch "Uploaded as text/plain at 2019-02-05.14:42:20 by @pierreglaser")</li><li>[pickler_hook.patch](https://bugs.python.org/file48203/pickler_hook.patch "Uploaded as text/plain at 2019-03-11.14:51:38 by @pierreglaser")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-05-08.21:08:54.715>
created_at = <Date 2019-02-05.14:40:22.937>
labels = ['type-feature', '3.8']
title = 'Add pickler hook for the user to customize the serialization of user defined functions and types.'
updated_at = <Date 2019-05-08.21:08:54.715>
user = 'https://github.com/pierreglaser'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-08.21:08:54.715>
actor = 'pitrou'
assignee = 'none'
closed = True
closed_date = <Date 2019-05-08.21:08:54.715>
closer = 'pitrou'
components = []
creation = <Date 2019-02-05.14:40:22.937>
creator = 'pierreglaser'
dependencies = []
files = ['48101', '48102', '48203']
hgrepos = []
issue_num = 35900
keywords = ['patch']
message_count = 7.0
messages = ['334870', '334872', '335404', '337673', '341933', '341944', '341945']
nosy_count = 5.0
nosy_names = ['pitrou', 'alexandre.vassalotti', 'serhiy.storchaka', 'Olivier.Grisel', 'pierreglaser']
pr_nums = ['12499', '12588']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue35900'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Sorry, there were hard times to me, so I missed this issue. Adding the 6th item breaks the pickle protocol and the code which expects `__reduce__()` returning a tuple with 2 to 5 items. See for example #90494. I think this change required introducing a new version of the pickle protocol. It may be too late now.
