### ISSUE TITLE
argparse: positional with type=int, default=SUPPRESS raise ValueError

### ISSUE THREAD

**Issue by ed4c8109-32cc-4981-a619-50207a7c7443** [python/cpython#80259]
BPO | [36078](https://bugs.python.org/issue36078)
--- | :---
Nosy | @n8falke, @yangyangxcf

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-02-22.14:18:34.731>
labels = ['3.8', 'type-bug', 'library']
title = 'argparse: positional with type=int, default=SUPPRESS raise ValueError'
updated_at = <Date 2020-03-16.16:20:47.351>
user = 'https://github.com/n8falke'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-16.16:20:47.351>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-02-22.14:18:34.731>
creator = 'n8falke'
dependencies = []
files = []
hgrepos = []
issue_num = 36078
keywords = []
message_count = 9.0
messages = ['336314', '336320', '336340', '336347', '336524', '359955', '360224', '364328', '364335']
nosy_count = 4.0
nosy_names = ['paul.j3', 'n8falke', 'fhsxfhsx', 'jeyekomon']
pr_nums = []
priority = 'high'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36078'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-124519
* gh-124751
* gh-124752

**Comment by serhiy-storchaka** [comment]
This is something similar to #53834 (especially the case reported in https://github.com/python/cpython/issues/80259#issuecomment-1093816106). In any case #124519 fixes all cases.

I would say that this is rather a simple issue. The bug occurs only because `argparse.SUPPRESS` is a string. If it would implemented as not a string (and this is another way to fix this issue), there would be no bug.
