### ISSUE TITLE
Enable better DLL resolution

### ISSUE THREAD

**Issue by zooba** [python/cpython#80266]
BPO | [36085](https://bugs.python.org/issue36085)
--- | :---
Nosy | @pfmoore, @db3l, @ncoghlan, @tjguk, @jkloth, @ambv, @ericsnowcurrently, @zware, @mattip, @eryksun, @zooba, @pablogsal, @carandraug
PRs | <li>python/cpython#12302</li><li>python/cpython#12633</li><li>python/cpython#12636</li><li>python/cpython#19167</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/zooba'
closed_at = <Date 2019-04-01.18:18:30.116>
created_at = <Date 2019-02-23.00:28:57.358>
labels = ['type-feature', '3.8', 'OS-windows']
title = 'Enable better DLL resolution'
updated_at = <Date 2020-03-28.00:39:54.810>
user = 'https://github.com/zooba'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-28.00:39:54.810>
actor = 'vstinner'
assignee = 'steve.dower'
closed = True
closed_date = <Date 2019-04-01.18:18:30.116>
closer = 'steve.dower'
components = ['Windows']
creation = <Date 2019-02-23.00:28:57.358>
creator = 'steve.dower'
dependencies = []
files = []
hgrepos = []
issue_num = 36085
keywords = ['patch']
message_count = 61.0
messages = ['336349', '336350', '336353', '336355', '336371', '336380', '336391', '336398', '336408', '336416', '336665', '337139', '337160', '337175', '337223', '337705', '337722', '337723', '337728', '337749', '337760', '337765', '337790', '337793', '337795', '337796', '337801', '337805', '337807', '337809', '337826', '337838', '337856', '338213', '338515', '338544', '338562', '338908', '338913', '338994', '339001', '339158', '339162', '339163', '339202', '339208', '339213', '339216', '339219', '339220', '339222', '339231', '339233', '339238', '339239', '339240', '339241', '339242', '347421', '347485', '365191']
nosy_count = 14.0
nosy_names = ['paul.moore', 'db3l', 'ncoghlan', 'tim.golden', 'jkloth', 'lukasz.langa', 'eric.snow', 'zach.ware', 'mattip', 'eryksun', 'steve.dower', 'ralf.gommers', 'pablogsal', 'carandraug']
pr_nums = ['12302', '12633', '12636', '19167']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36085'
versions = ['Python 3.8']
```

</p></details>

**Comment by ax3l** [comment]
The `os.add_dll_directory` calls are great, but in many scenarios it is tricky for us to inject Python code.

For instance, in complex builds with CMake pybind11 artifacts using deeply nested, temporary directories one would like to temporarily hint some dependent DLLs for testing *prior* to an install in a fixed installation structure.

For such workflows, it would be super useful if we could define additional paths without injecting Python code or going down the rabbit hole manipulating the `site` config (which is more persistent than a temporary build directory).

Do you think you could add support for an environment variable that adds safe DLL directories?

**Comment by zooba** [comment]
I'd rather not, because that opens the door to all sorts of code injection/search path hijacking attacks.

Are you really not running any of your own code that deep? You could use your own environment variable and add them yourself.

**Comment by ax3l** [comment]
That's what I considered now, but I did not see how this is different in terms of risk to a standardized hook.

(I'll have to implement such a migration path for a series of nested projects in superbuilds, so I thought standardization might be good.)

**Comment by ax3l** [comment]
Just curious: What's the attack vector (own user rights) that you guard against with respect to search path hijacking?

On Linux, we have LD_LIBRARY_PATH and even LD_PRELOAD - as long as one is in control of one's own environment that's usually not a problem. Is that different on Windows?

**Comment by zooba** [comment]
> I do not yet see how this is different in terms of risk to a standardized environment variable.

It only applies to people actually running your code, not all arbitrary Python code in the entire world. And builds generally have a different threat model that allows for these kinds of overrides (and so your security teams will protect at a different level).

> On Linux, we have LD_LIBRARY_PATH and even LD_PRELOAD - as long as one is in control of one's own environment that's usually not a problem. Is that different on Windows (besides that PATH controls apps and dlls)?

It's basically just a threat model thing. Windows allows defenders to assume that DLLs won't be hijacked, and so anything that enables it is considered a bug to be fixed - the change to not seacrh `PATH` is one such fix, and `os.add_dll_directory` is the escape hatch for people who really need it (because they can't change the install layout of their files).

Linux has a broader threat model because of `LD_*` variables. You need to use different protections and detections to deal with the possibility of an attacker using these approaches.

Along similar lines, because Python tends to be preinstalled with Linux distros, but isn't preinstalled on Windows, there are different approaches to prevent/detect attackers using Python as part of their attack. They're just both examples of different platform assumptions that lead to different threat models, and so Python works to fit into both without unnecessarily breaking regular expectations.
