### ISSUE TITLE
remove non-ascii characters in docstring

### ISSUE THREAD

**Issue by b8e5a65c-bed4-4c5d-ba32-799f883ba638** [python/cpython#80282]
BPO | [36101](https://bugs.python.org/issue36101)
--- | :---
Nosy | @methane, @animalize
PRs | <li>python/cpython#12018</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-02-24.23:20:06.313>
created_at = <Date 2019-02-24.13:36:09.880>
labels = ['3.8', 'docs']
title = 'remove non-ascii characters in docstring'
updated_at = <Date 2019-02-24.23:20:06.312>
user = 'https://github.com/animalize'
```

bugs.python.org fields:
```python
activity = <Date 2019-02-24.23:20:06.312>
actor = 'methane'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-02-24.23:20:06.313>
closer = 'methane'
components = ['Documentation']
creation = <Date 2019-02-24.13:36:09.880>
creator = 'malin'
dependencies = []
files = []
hgrepos = []
issue_num = 36101
keywords = ['patch']
message_count = 4.0
messages = ['336468', '336469', '336488', '336489']
nosy_count = 3.0
nosy_names = ['methane', 'docs@python', 'malin']
pr_nums = ['12018']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue36101'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-107764

**Comment by methane** [comment]
Sorry, I don't remember where we discussed.
When this change was made, MSVC used ANSI Codepage for C sources.

Now we use /utf8 flag on MSVC. So that limitation has been removed.
But I am still not sure that the C source is 100% UTF-8 on all platform and compiler toolsets.

**Comment by erlend-aasland** [comment]
Thank you, Inada-san! I suspected it had to do with Windows. Perhaps someone on the @python/windows-team could chime in, regarding status quo today? Is this limitation still needed?

**Comment by methane** [comment]
There are platforms we don't support officially but some active users maintain Python running.
Solaris and AIX.
