### ISSUE TITLE
[subinterpreters] Lingering subinterpreters should be implicitly cleared on shutdown

### ISSUE THREAD

**Issue by ncoghlan** [python/cpython#80406]
BPO | [36225](https://bugs.python.org/issue36225)
--- | :---
Nosy | @ncoghlan, @vstinner, @ned-deily, @encukou, @ericsnowcurrently, @soltysh, @JulienPalard, @nanjekyejoannah, @LewisGaul, @nasageek
PRs | <li>python/cpython#17575</li>
Files | <li>[finalise-subinterps-test.diff](https://bugs.python.org/file48733/finalise-subinterps-test.diff "Uploaded as text/plain at 2019-11-21.18:31:13 by @LewisGaul")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-07.13:17:43.665>
labels = ['expert-subinterpreters', '3.10', 'type-crash']
title = '[subinterpreters] Lingering subinterpreters should be implicitly cleared on shutdown'
updated_at = <Date 2021-12-16.23:53:44.369>
user = 'https://github.com/ncoghlan'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-16.23:53:44.369>
actor = 'nasageek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Subinterpreters']
creation = <Date 2019-03-07.13:17:43.665>
creator = 'ncoghlan'
dependencies = []
files = ['48733']
hgrepos = []
issue_num = 36225
keywords = ['patch']
message_count = 17.0
messages = ['337392', '337743', '337852', '339149', '339150', '339191', '345802', '349119', '349124', '353873', '357193', '357235', '364587', '371338', '371571', '379366', '379718']
nosy_count = 10.0
nosy_names = ['ncoghlan', 'vstinner', 'ned.deily', 'petr.viktorin', 'eric.snow', 'maciej.szulik', 'mdk', 'nanjekyejoannah', 'LewisGaul', 'nasageek']
pr_nums = ['17575']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue36225'
versions = ['Python 3.10']
```

</p></details>

**Comment by ericsnowcurrently** [comment]
In gh-121060 (4be1f37b20bd51498d3adf8ad603095c0f38d6e5) I added automatic cleanup of subinterpreters.  I've also backported it to 3.13.

(I need to revisit gh-17575, which I had forgotten about.)
