### ISSUE TITLE
xml ElementTree quotation marks of xml version string

### ISSUE THREAD

**Issue by f1b150ed-9111-4e15-8a93-d66070b5e82d** [python/cpython#80414]
BPO | [36233](https://bugs.python.org/issue36233)
--- | :---
Nosy | @rhettinger, @scoder, @serhiy-storchaka, @photoniker
Files | <li>[ElementTree.py](https://bugs.python.org/file48193/ElementTree.py "Uploaded as text/plain at 2019-03-08.10:08:06 by @photoniker"): ElementTree.py</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-03-22.14:14:28.587>
created_at = <Date 2019-03-08.10:08:07.683>
labels = ['expert-XML', 'invalid', 'type-bug', '3.7']
title = 'xml ElementTree quotation marks of xml version string'
updated_at = <Date 2019-03-22.14:14:28.586>
user = 'https://github.com/photoniker'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-22.14:14:28.586>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2019-03-22.14:14:28.587>
closer = 'serhiy.storchaka'
components = ['XML']
creation = <Date 2019-03-08.10:08:07.683>
creator = 'Photoniker'
dependencies = []
files = ['48193']
hgrepos = []
issue_num = 36233
keywords = []
message_count = 8.0
messages = ['337463', '337489', '337520', '337528', '337654', '337671', '338596', '338597']
nosy_count = 5.0
nosy_names = ['rhettinger', 'scoder', 'eli.bendersky', 'serhiy.storchaka', 'Photoniker']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36233'
versions = ['Python 3.7']
```

</p></details>

**Comment by natsamjosh** [comment]
I would recommend making the change as proposed by the original poster.   Aside from consistency (double quotes are used elsewhere), we had an issue where the generated XML output was not handled correctly in a DB insert, didn't like the single quotes.  (The need to be escaped when in a DB insert.)   So why not change to double quotes?   Is there a particular reason why single quotes were used just for the declaration tag?

**Comment by aidan959** [comment]
Would it be possible for some argument (with its default set to single quotes) to override this behaviour?
