### ISSUE TITLE
Make ast.dump() not output optional default fields

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#80468]
BPO | [36287](https://bugs.python.org/issue36287)
--- | :---
Nosy | @benjaminp, @serhiy-storchaka, @1st1, @ilevkivskyi, @eamanu, @isidentical
PRs | <li>python/cpython#12328</li><li>python/cpython#18843</li>
Dependencies | <li>bpo-39981: Default values for AST Nodes</li>
Files | <li>[ast.patch](https://bugs.python.org/file48975/ast.patch "Uploaded as text/plain at 2020-03-16.10:00:55 by @isidentical")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-14.09:48:05.485>
labels = ['type-feature', 'library', '3.9']
title = 'Make ast.dump() not output optional default fields'
updated_at = <Date 2020-04-08.14:28:27.407>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-08.14:28:27.407>
actor = 'BTaskaya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-03-14.09:48:05.485>
creator = 'serhiy.storchaka'
dependencies = ['39981']
files = ['48975']
hgrepos = []
issue_num = 36287
keywords = ['patch']
message_count = 16.0
messages = ['337907', '337922', '337955', '338030', '338033', '338055', '356925', '356935', '357012', '363640', '363641', '363642', '363775', '364305', '364326', '365987']
nosy_count = 6.0
nosy_names = ['benjamin.peterson', 'serhiy.storchaka', 'yselivanov', 'levkivskyi', 'eamanu', 'BTaskaya']
pr_nums = ['12328', '18843']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36287'
versions = ['Python 3.9']
```

</p></details>

**Comment by furkanonder** [comment]
@serhiy-storchaka The issue seems to have been solved. I think we can close the problem.
