### ISSUE TITLE
eval is needlessly limited

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#80464]
BPO | [36283](https://bugs.python.org/issue36283)
--- | :---
Nosy | @stevendaprano, @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-13.23:31:43.880>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'eval is needlessly limited'
updated_at = <Date 2019-03-14.03:37:04.620>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-14.03:37:04.620>
actor = 'steven.daprano'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-03-13.23:31:43.880>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 36283
keywords = []
message_count = 2.0
messages = ['337885', '337893']
nosy_count = 2.0
nosy_names = ['steven.daprano', 'bup']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36283'
versions = ['Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
Steven, Given the lack of response and clarity, would you agree with closing this?

**Comment by stevendaprano** [comment]
I don't understand the bug report, and @mr-nfamous hasn't clarified it in nearly four years. Let's close it. If anyone wants to revisit this, we can reopen it if necessary.
