### ISSUE TITLE
Add kind field to ast.Constant, to distinguish u"..." from "..." for type checkers

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#80461]
BPO | [36280](https://bugs.python.org/issue36280)
--- | :---
Nosy | @gvanrossum, @serhiy-storchaka, @miss-islington
PRs | <li>python/cpython#12295</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gvanrossum'
closed_at = <Date 2019-03-13.20:01:54.579>
created_at = <Date 2019-03-13.04:00:08.733>
labels = ['type-bug', '3.8']
title = 'Add kind field to ast.Constant, to distinguish u"..." from "..." for type checkers'
updated_at = <Date 2019-03-13.20:01:54.578>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-13.20:01:54.578>
actor = 'gvanrossum'
assignee = 'gvanrossum'
closed = True
closed_date = <Date 2019-03-13.20:01:54.579>
closer = 'gvanrossum'
components = []
creation = <Date 2019-03-13.04:00:08.733>
creator = 'gvanrossum'
dependencies = []
files = []
hgrepos = []
issue_num = 36280
keywords = ['patch']
message_count = 5.0
messages = ['337834', '337853', '337854', '337872', '337873']
nosy_count = 3.0
nosy_names = ['gvanrossum', 'serhiy.storchaka', 'miss-islington']
pr_nums = ['12295']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36280'
versions = ['Python 3.8']
```

</p></details>

**Comment by vasily-v-ryabov** [comment]
Please correct me if I'm wrong. This `Constant.kind` field is not used in mypy any more. Previously it was used in `fastparse.py` (intro by this commit: https://github.com/python/mypy/commit/69a5a0286e0129a71624001c38c2d4897b594574), but now I don't see it in [mypy/fastparse.py](https://github.com/python/mypy/blob/master/mypy/fastparse.py) or anywhere else. Yes, this field is present in `ast` module interface, and I didn't try to search if it is used by some PyPI package. Maybe you know where it is used. Thanks!

**Comment by gvanrossum** [comment]
@vasily-v-ryabov What is your question, or what action are you requesting we take?

**Comment by vasily-v-ryabov** [comment]
@gvanrossum Initially I wanted to remove this field as it looked outdated. I've even prepared draft commit https://github.com/vasily-v-ryabov/cpython/commit/68906e03671c2459805bdb50418af9f1b3e5c154 but then I've found this thread and related commits, and also I understood it may potentially break backward compatibility. If there is no such risk, I'd suggest to create a PR or prepare some deprecation. Though this particular commit is not critical to me if this stuff is really used.

The reason to me is making AST more compact which should be generally good for performance. I'm actively learning compiler internals and AST related C API for my project (hope it will be open in the future). So I'm interested in improvements for AST and compiler related stuff in CPython.
