### ISSUE TITLE
array: Add 'w' type and deprecate 'u' type.

### ISSUE THREAD

**Issue by methane** [python/cpython#80480]
BPO | [36299](https://bugs.python.org/issue36299)
--- | :---
Nosy | @terryjreedy, @ncoghlan, @methane, @skrah, @serhiy-storchaka
PRs | <li>python/cpython#12497</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-15.05:50:02.657>
labels = ['3.8', 'library']
title = "array: Deprecate 'u' type in array module"
updated_at = <Date 2020-04-23.00:47:43.731>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-23.00:47:43.731>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-03-15.05:50:02.657>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 36299
keywords = ['patch']
message_count = 12.0
messages = ['337967', '338031', '338595', '338598', '338607', '338608', '338609', '338610', '338611', '367000', '367044', '367065']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'ncoghlan', 'methane', 'skrah', 'serhiy.storchaka']
pr_nums = ['12497']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36299'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-95760
* gh-105242

**Comment by ezio-melotti** [comment]
Even though this has been deprecated in the docs since 3.3, it doesn't seem to raise a `DeprecationWarning`.  If we want to remove it we should add the warning, and then remove it in a later version.  The documentation should also be updated according to the plan (see #93986).

**Comment by hugovk** [comment]
Please see PR https://github.com/python/cpython/pull/95760 to emit a `DeprecationWarning`.

**Comment by hugovk** [comment]
> * Add 'w' for Py_UCS4.

@methane Would you be able to look into this? It would be good to have the replacement ready when we start emitting deprecation warnings.

**Comment by hugovk** [comment]
The 3.12 beta feature freeze is in a week, so we will likely need to target changing this in 3.13 with removal in 3.15.

**Comment by encukou** [comment]
How about:
* Add `'w'` for Py_UCS4.
* Wait until all Python versions that don't have `w` reach end of life
* Deprecate `'u'`, and remove it in the future.

Is there a reason to rush this?

**Comment by methane** [comment]
`array('u')` will cause bugs and almost no valid use case for it.
So waiting deprecation 5+ years seems too slow.

* Add 'w' to Python 3.13
* Deprecate 'u' in Python 3.15
* Remove 'u' in Python 3.18

**Comment by vstinner** [comment]
I dislike the fact that ``array.array('u')`` is only deprecated in the doc. I would prefer to either emit a DeprecationWarning at runtime, or remove the deprecation. See also issue #105373. I'm fine with really deprecating it if someone wants to submit a PR (@methane ?).

**Comment by hugovk** [comment]
@vstinner PR already open at https://github.com/python/cpython/pull/95760 :)

**Comment by hugovk** [comment]
> `array('u')` will cause bugs and almost no valid use case for it. So waiting deprecation 5+ years seems too slow.
> 
> On the other hand, I don't hurry about removing it. I can wait 3+ releases instead of minimum 2 releases.
> 
> My plan is:
> 
> * Add 'w' and deprecate 'u' in Python 3.13

Done in https://github.com/python/cpython/pull/105242 and https://github.com/python/cpython/pull/95760.

> * Remove 'u' in Python 3.16+ (Postpone removal if some users still use 'u').

Let's close this issue and come back to this in four years.

**Comment by vstinner** [comment]
The `array` `u` type has been removed by the PR gh-149535.
