### ISSUE TITLE
Remove tempfile.mktemp()

### ISSUE THREAD

**Issue by 2df14aea-354c-46a6-8f5c-342c9f465901** [python/cpython#80490]
BPO | [36309](https://bugs.python.org/issue36309)
--- | :---
Nosy | @brettcannon, @serhiy-storchaka, @matrixise, @johnthagen, @pablogsal
PRs | <li>python/cpython#12437</li><li>python/cpython#15640</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-16.00:49:04.986>
labels = ['3.8', 'type-feature', 'library']
title = 'Remove tempfile.mktemp()'
updated_at = <Date 2019-09-02.10:24:19.820>
user = 'https://github.com/johnthagen'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-02.10:24:19.820>
actor = 'python-dev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-03-16.00:49:04.986>
creator = 'John Hagen'
dependencies = []
files = []
hgrepos = []
issue_num = 36309
keywords = ['patch']
message_count = 6.0
messages = ['338046', '338302', '338304', '338305', '338324', '338348']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'serhiy.storchaka', 'matrixise', 'John Hagen', 'pablogsal']
pr_nums = ['12437', '15640']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36309'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-108515

**Comment by vstinner** [comment]
I don't think that we should remove this function. It's deprecated and its documentation contains a big red warning about security. IMO it's enough: https://docs.python.org/dev/library/tempfile.html#tempfile.mktemp I close the issue as WONT FIX.
