### ISSUE TITLE
Doc: make serve uses http.server instead of Tools/scripts/server.py

### ISSUE THREAD

**Issue by matrixise** [python/cpython#80526]
BPO | [36345](https://bugs.python.org/issue36345)
--- | :---
Nosy | @brettcannon, @vstinner, @ned-deily, @berkerpeksag, @serhiy-storchaka, @matrixise, @JulienPalard
PRs | <li>python/cpython#12408</li><li>python/cpython#12511</li><li>python/cpython#12522</li><li>python/cpython#12562</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-18.13:57:39.273>
labels = ['3.8', 'docs']
title = 'Doc: make serve uses http.server instead of Tools/scripts/server.py'
updated_at = <Date 2019-05-15.08:43:26.810>
user = 'https://github.com/matrixise'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-15.08:43:26.810>
actor = 'matrixise'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-03-18.13:57:39.273>
creator = 'matrixise'
dependencies = []
files = []
hgrepos = []
issue_num = 36345
keywords = ['patch']
message_count = 22.0
messages = ['338224', '338247', '338258', '338276', '338396', '338631', '338637', '338662', '338665', '338666', '338739', '338741', '338743', '338833', '338864', '338874', '338909', '340338', '341162', '342046', '342060', '342135']
nosy_count = 8.0
nosy_names = ['brett.cannon', 'vstinner', 'ned.deily', 'docs@python', 'berker.peksag', 'serhiy.storchaka', 'matrixise', 'mdk']
pr_nums = ['12408', '12511', '12522', '12562']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36345'
versions = ['Python 3.8']
```

</p></details>

**Comment by hugovk** [comment]
`make serve` has since been replaced with `make htmllive`, which uses https://github.com/sphinx-doc/sphinx-autobuild:

* `make serve` was removed in https://github.com/python/cpython/issues/80510.
* `make htmllive` was added in https://github.com/python/cpython/pull/111900.
