### ISSUE TITLE
errors in multiprocessing.shared_memory examples

### ISSUE THREAD

**Issue by 78212f07-2619-4b41-b0fc-42fe2922b059** [python/cpython#80545]
BPO | [36364](https://bugs.python.org/issue36364)
--- | :---
Nosy | @brettcannon, @pitrou, @applio, @miss-islington, @pierreglaser
PRs | <li>python/cpython#12439</li>
Files | <li>[0001-DOC-fix-SharedMemoryManager-examples.patch](https://bugs.python.org/file48221/0001-DOC-fix-SharedMemoryManager-examples.patch "Uploaded as text/plain at 2019-03-19.14:39:57 by @pierreglaser")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/applio'
closed_at = None
created_at = <Date 2019-03-19.14:39:57.230>
labels = ['3.8', 'docs']
title = 'errors in multiprocessing.shared_memory examples'
updated_at = <Date 2019-04-02.18:05:40.065>
user = 'https://github.com/pierreglaser'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-02.18:05:40.065>
actor = 'brett.cannon'
assignee = 'davin'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-03-19.14:39:57.230>
creator = 'pierreglaser'
dependencies = []
files = ['48221']
hgrepos = []
issue_num = 36364
keywords = ['patch']
message_count = 5.0
messages = ['338360', '338914', '338915', '339314', '339356']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'pitrou', 'docs@python', 'davin', 'miss-islington', 'pierreglaser']
pr_nums = ['12439']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36364'
versions = ['Python 3.8']
```

</p></details>

**Comment by furkanonder** [comment]
> @davin is there an issue for that and thus this issue can then be closed? Or did you want to re-purpose this issue to track that? Either way I'm assigning the issue to you to let you decide which way you want to go. :)

I think issue can be closed.
