### ISSUE TITLE
AsyncIterator on 3.7: __aiter__ no longer honors finally blocks

### ISSUE THREAD

**Issue by fd732dfd-1c48-49f8-8a35-5821c15e655b** [python/cpython#80584]
BPO | [36403](https://bugs.python.org/issue36403)
--- | :---
Nosy | @ned-deily, @asvetlov, @1st1, @twisteroidambassador, @tirkarthi
Files | <li>[test_iterators_and_finally_blocks.py](https://bugs.python.org/file48229/test_iterators_and_finally_blocks.py "Uploaded as text/plain at 2019-03-23.00:15:07 by asksol")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-23.00:15:07.175>
labels = ['3.8', 'type-bug', '3.7', 'expert-asyncio']
title = 'AsyncIterator on 3.7: __aiter__ no longer honors finally blocks'
updated_at = <Date 2020-06-12.08:32:55.224>
user = 'https://bugs.python.org/asksol'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-12.08:32:55.224>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-03-23.00:15:07.175>
creator = 'asksol'
dependencies = []
files = ['48229']
hgrepos = []
issue_num = 36403
keywords = ['3.7regression']
message_count = 7.0
messages = ['338630', '338638', '338642', '338647', '345805', '345808', '371341']
nosy_count = 6.0
nosy_names = ['ned.deily', 'asvetlov', 'asksol', 'yselivanov', 'twisteroid ambassador', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36403'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
I don't see how this is a bug or regression. There is no guarantee when generators are finalized, code relying on it is already subtly broken. I'll close this unless anyone objects, marking pending.
