### ISSUE TITLE
Tkinter multi-processing performance, Linux 10-25 times faster than Windows 10

### ISSUE THREAD

**Issue by dfc7780e-cb57-4838-8853-839f3361f970** [python/cpython#80589]
BPO | [36408](https://bugs.python.org/issue36408)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba, @MojoVampire
Files | <li>[mosaic.py](https://bugs.python.org/file48232/mosaic.py "Uploaded as text/plain at 2019-03-26.10:57:58 by james.mccormack")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-23.15:57:48.837>
labels = ['3.7', 'expert-tkinter', 'OS-windows', 'performance']
title = 'Tkinter multi-processing performance, Linux 10-25 times faster than Windows 10'
updated_at = <Date 2019-03-26.10:57:58.961>
user = 'https://bugs.python.org/jamesmccormack'
```

bugs.python.org fields:
```python
activity = <Date 2019-03-26.10:57:58.961>
actor = 'james.mccormack'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tkinter', 'Windows']
creation = <Date 2019-03-23.15:57:48.837>
creator = 'james.mccormack'
dependencies = []
files = ['48232']
hgrepos = []
issue_num = 36408
keywords = []
message_count = 5.0
messages = ['338682', '338805', '338808', '338820', '338871']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'gpolo', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'josh.r', 'james.mccormack']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue36408'
versions = ['Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
Based on @zooba 's comment, there seems to be nothing left to do here. Shall we close it?

**Comment by zware** [comment]
I'd say so; as far as I can tell, this looks like a Windows issue: if 6 independent processes exhibit a slowdown with no communication between them, I don't see any way in which Python or Tcl/Tk could be at fault.
