### ISSUE TITLE
task.cancel unbound recursion if task is deadlocked

### ISSUE THREAD

**Issue by 1e3445ee-1357-417d-a204-0863cf864f91** [python/cpython#80637]
BPO | [36456](https://bugs.python.org/issue36456)
--- | :---
Nosy | @asvetlov, @cjerdonek, @dimaqq, @1st1, @crusaderky

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-28.02:52:54.531>
labels = ['3.7', '3.8', '3.9', '3.10', 'expert-asyncio']
title = 'task.cancel unbound recursion if task is deadlocked'
updated_at = <Date 2021-01-21.08:35:59.906>
user = 'https://github.com/dimaqq'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-21.08:35:59.906>
actor = 'Dima.Tisnek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-03-28.02:52:54.531>
creator = 'Dima.Tisnek'
dependencies = []
files = []
hgrepos = []
issue_num = 36456
keywords = []
message_count = 2.0
messages = ['339006', '385395']
nosy_count = 5.0
nosy_names = ['asvetlov', 'chris.jerdonek', 'Dima.Tisnek', 'yselivanov', 'crusaderky']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36456'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
What do you expect to happen in this case?

**Comment by gvanrossum** [comment]
Definitely not something you see every day. :-)

It ought to cancel f and g.

**Comment by kumaraditya303** [comment]
I don't think it is a bug. `asyncio` does not detects deadlocked tasks and it is hard to do that properly.

**Comment by gvanrossum** [comment]
But it is surprising that the cancellation cannot break through.

**Comment by arhadthedev** [comment]
The issue is "pending closing" for one and a half year so closing.

**Comment by qris** [comment]
I accidentally triggered this with `await asyncio.gather(asyncio.all_tasks())` within an async function (that was running in a Task), so it was cancelling itself. Took me hours (and a read of [this answer](https://stackoverflow.com/a/68629884/648162)) to find it.
