### ISSUE TITLE
bdb.Bdb.set_trace: should set f_trace_lines = True

### ISSUE THREAD

**Issue by 1f7c169c-a6ad-45ae-b614-0d40d962c776** [python/cpython#80675]
BPO | [36494](https://bugs.python.org/issue36494)
--- | :---
Nosy | @blueyed, @iritkatriel
PRs | <li>python/cpython#12640</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-03-31.14:28:51.712>
labels = ['type-bug', 'library', '3.9', '3.10', '3.11']
title = 'bdb.Bdb.set_trace: should set f_trace_lines = True'
updated_at = <Date 2021-05-21.21:16:24.081>
user = 'https://github.com/blueyed'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-21.21:16:24.081>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-03-31.14:28:51.712>
creator = 'blueyed'
dependencies = []
files = []
hgrepos = []
issue_num = 36494
keywords = ['patch']
message_count = 2.0
messages = ['339259', '394158']
nosy_count = 2.0
nosy_names = ['blueyed', 'iritkatriel']
pr_nums = ['12640']
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36494'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-110881

**Comment by nedbat** [comment]
Coverage.py now sets f_trace_lines=0 when it doesn't want to trace, and I've started getting bug reports that this breaks tests using pdb: https://github.com/nedbat/coveragepy/issues/1402.  Can we move this forward?

**Comment by iritkatriel** [comment]
@nedbat, I don't think @blueyed plans to finish this. Would you like to take over?

**Comment by gaogaotiantian** [comment]
Fixed.
