### ISSUE TITLE
Add Windows ARM32 buildbot

### ISSUE THREAD

**Issue by eef812a9-0c55-49e1-85e3-717a8588c91c** [python/cpython#80692]
BPO | [36511](https://bugs.python.org/issue36511)
--- | :---
Nosy | @pfmoore, @db3l, @vstinner, @tjguk, @ned-deily, @zware, @zooba, @miss-islington, @paulmon
PRs | <li>python/cpython#12917</li><li>python/cpython#13351</li><li>python/cpython#13454</li><li>python/cpython#13529</li><li>python/cpython#14244</li><li>python/cpython#14251</li><li>python/cpython#14279</li><li>python/cpython#14280</li><li>python/cpython#14290</li><li>python/cpython#14431</li><li>python/cpython#14460</li><li>python/cpython#15181</li><li>python/cpython#15186</li><li>python/cpython#15279</li><li>python/cpython#15571</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-02.19:09:21.569>
labels = ['type-feature', '3.8', 'OS-windows', 'build', '3.9']
title = 'Add Windows ARM32 buildbot'
updated_at = <Date 2019-09-10.07:33:33.875>
user = 'https://github.com/paulmon'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-10.07:33:33.875>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Windows']
creation = <Date 2019-04-02.19:09:21.569>
creator = 'Paul Monson'
dependencies = []
files = []
hgrepos = []
issue_num = 36511
keywords = ['patch']
message_count = 21.0
messages = ['339362', '342611', '342612', '342614', '342661', '343320', '343321', '343322', '343406', '346081', '346133', '346165', '346233', '346256', '349267', '349705', '350715', '350716', '350717', '351551', '351586']
nosy_count = 9.0
nosy_names = ['paul.moore', 'db3l', 'vstinner', 'tim.golden', 'ned.deily', 'zach.ware', 'steve.dower', 'miss-islington', 'Paul Monson']
pr_nums = ['12917', '13351', '13454', '13529', '14244', '14251', '14279', '14280', '14290', '14431', '14460', '15181', '15186', '15279', '15571']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36511'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
Can this be closed?

**Comment by zware** [comment]
Yes, I think so.
