### ISSUE TITLE
Recursive directory list with pathlib.Path.iterdir

### ISSUE THREAD

**Issue by c39b6e4f-97be-4b50-825a-81f3388033bf** [python/cpython#80783]
BPO | [36602](https://bugs.python.org/issue36602)
--- | :---
Nosy | @pitrou, @zooba, @pganssle, @tirkarthi, @EpicWink
PRs | <li>python/cpython#12785</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-11.10:59:34.291>
labels = ['type-feature', 'library', '3.9']
title = 'Recursive directory list with pathlib.Path.iterdir'
updated_at = <Date 2019-06-05.00:36:30.476>
user = 'https://github.com/EpicWink'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-05.00:36:30.476>
actor = 'Epic_Wink'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-04-11.10:59:34.291>
creator = 'Epic_Wink'
dependencies = []
files = []
hgrepos = []
issue_num = 36602
keywords = ['patch']
message_count = 12.0
messages = ['339959', '339969', '339997', '340003', '340012', '340042', '340072', '340135', '340144', '341059', '342007', '342687']
nosy_count = 6.0
nosy_names = ['pitrou', 'SilentGhost', 'steve.dower', 'p-ganssle', 'xtreak', 'Epic_Wink']
pr_nums = ['12785']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36602'
versions = ['Python 3.9']
```

</p></details>

**Comment by barneygale** [comment]
Hey @EpicWink, we now have a `Path.walk()` method that recursively walks directory trees, using `os.scandir()` for efficiency - see #92517. This is faster than using `rglob('*')` in most cases, and it supports following symlinks. Do you think that would cover your original use case?

**Comment by EpicWink** [comment]
`walk`'s interface is a little bit clunky, but I've realised `iterdir_recursive` doesn't need to live in the standard library, as is trivial to include in a library or copy-paste between scripts.

**Comment by AlexWaygood** [comment]
Closing, since we now have `Path.walk()`, and OP no longer has interest in the idea.

If another core developer still wants to proceed with this, feel free to reopen!
