### ISSUE TITLE
Replace bundled pip and setuptools with a downloader in the ensurepip module

### ISSUE THREAD

**Issue by webknjaz** [python/cpython#80789]
BPO | [36608](https://bugs.python.org/issue36608)
--- | :---
Nosy | @ericvsmith, @ned-deily, @serhiy-storchaka, @dstufft, @webknjaz, @pradyunsg
PRs | <li>python/cpython#12791</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-11.22:13:02.045>
labels = ['3.8', 'type-feature', 'library', '3.9']
title = 'Replace bundled pip and setuptools with a downloader in the ensurepip module'
updated_at = <Date 2021-07-05.23:28:08.628>
user = 'https://github.com/webknjaz'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-05.23:28:08.628>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-04-11.22:13:02.045>
creator = 'webknjaz'
dependencies = []
files = []
hgrepos = []
issue_num = 36608
keywords = ['patch']
message_count = 6.0
messages = ['339998', '340039', '340060', '340169', '340218', '347836']
nosy_count = 6.0
nosy_names = ['eric.smith', 'ned.deily', 'serhiy.storchaka', 'dstufft', 'webknjaz', 'pradyunsg']
pr_nums = ['12791']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36608'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-109130
* gh-109245

**Comment by webknjaz** [comment]
Folks, I revamped the PR and need some help with the build process integration here: https://github.com/python/cpython/pull/12791/files#r1306308587. Could anybody take a look?

**Comment by webknjaz** [comment]
@pradyunsg should this issue get newer labels for `3.10`, `3.11`, `3.12` and `3.13`?

**Comment by SpecLad** [comment]
Would it perhaps be viable to include pip as an (unpacked) sdist in the ensurepip source tree, and build it during the CPython build process? The repo bloat should be much smaller that way.

(You'd also need to include pip's build dependencies, but those don't need to be updated frequently.)

**Comment by webknjaz** [comment]
> Would it perhaps be viable to include pip as an (unpacked) sdist in the ensurepip source tree, and build it during the CPython build process? The repo bloat should be much smaller that way.

@AA-Turner @pradyunsg WDYT about the suggestion above? Could also be an unpacked wheel (`wheel unpack pip-*.whl` output), which feels like a more slim solution, than an sdist.
