### ISSUE TITLE
Provide list.rindex()

### ISSUE THREAD

**Issue by 693f263f-a080-47dc-8f14-c27d15b50a75** [python/cpython#80820]
BPO | [36639](https://bugs.python.org/issue36639)
--- | :---
Nosy | @rhettinger, @vstinner, @serhiy-storchaka, @johnlinp, @tirkarthi
PRs | <li>python/cpython#12851</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-04-17.08:38:40.936>
created_at = <Date 2019-04-16.06:46:24.224>
labels = ['interpreter-core', 'type-feature', '3.9']
title = 'Provide list.rindex()'
updated_at = <Date 2019-04-24.08:32:51.896>
user = 'https://github.com/johnlinp'
```

bugs.python.org fields:
```python
activity = <Date 2019-04-24.08:32:51.896>
actor = 'johnlinp'
assignee = 'none'
closed = True
closed_date = <Date 2019-04-17.08:38:40.936>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2019-04-16.06:46:24.224>
creator = 'johnlinp'
dependencies = []
files = []
hgrepos = []
issue_num = 36639
keywords = ['patch']
message_count = 9.0
messages = ['340312', '340314', '340317', '340319', '340383', '340417', '340751', '340758', '340762']
nosy_count = 6.0
nosy_names = ['rhettinger', 'vstinner', 'SilentGhost', 'serhiy.storchaka', 'johnlinp', 'xtreak']
pr_nums = ['12851']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36639'
versions = ['Python 3.9']
```

</p></details>

**Comment by atrigent** [comment]
The fact that a "use case" would be demanded for such a basic building block is frankly absurd. The existence of people asking for this functionality, such as this very discussion, and the obvious value of having some basic consistency between collection types should be more than enough reasons to include this.

**Comment by Ivanyinfan** [comment]
suprised python still doesn't support this while you can easily find this kind of function in other languages
