### ISSUE TITLE
functools.singledispatch: Shouldn't require a positional argument if there is only one keyword argument

### ISSUE THREAD

**Issue by f57a6745-bd9e-4d86-a8f7-f0c88017f699** [python/cpython#80925]
BPO | [36744](https://bugs.python.org/issue36744)
--- | :---
Nosy | @doerwalter, @rhettinger, @methane, @ambv, @tirkarthi, @tim-mitchell, @SqAtx

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-04-28.01:21:36.455>
labels = ['3.8', 'type-bug', 'library']
title = "functools.singledispatch: Shouldn't require a positional argument if there is only one keyword argument"
updated_at = <Date 2022-03-18.01:56:32.639>
user = 'https://github.com/SqAtx'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-18.01:56:32.639>
actor = 'Tim Mitchell2'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-04-28.01:21:36.455>
creator = 'KevinG'
dependencies = []
files = []
hgrepos = []
issue_num = 36744
keywords = []
message_count = 4.0
messages = ['341016', '341017', '341019', '415464']
nosy_count = 7.0
nosy_names = ['doerwalter', 'rhettinger', 'methane', 'lukasz.langa', 'xtreak', 'Tim Mitchell2', 'KevinG']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36744'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-102063

**Comment by encukou** [comment]
I'd rather not have `singledispatch` depend on `inspect.signature`, which is rather slow, and not quite guaranteed to be correct.
A better approach would be to pass the name of the argument explicitly. Still, overall it's probably not worth the added complexity.

The [Ideas section at Discourse](https://discuss.python.org/c/6) would be a better place to discuss this than an issue.

**Comment by skirpichev** [comment]
> A better approach would be to pass the name of the argument explicitly.

Not sure I get your point, it's passed:
```pycon
>>> f(x=1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<my-virtual-env>/lib/python3.7/functools.py", line 821, in wrapper
    raise TypeError(f'{funcname} requires at least '
TypeError: f requires at least 1 positional argument
```
The problem is that singledispatch can't reproduce valid python signatures.

**Comment by encukou** [comment]
I meant adding something like `@functools.singledispatch(arg_name='x')`.

**Comment by skirpichev** [comment]
I see.

Well, according to my benchmarks, the patch from closed pr costs ~3x:
```
$ ./python -m timeit -uusec -s "from functools import singledispatch" \
    "@singledispatch" \
    "def f(x):" \
    "    pass"
1 loop, best of 5: 1.59e+03 usec per loop
$ git checkout .  # now in the main:
Updated 1 path from the index
$ ./python -m timeit -uusec -s "from functools import singledispatch" \
    "@singledispatch" \
    "def f(x):" \
    "    pass"
500 loops, best of 5: 455 usec per loop
```
Could be this a bottleneck for some application?  Maybe, but on another hand - runtime cost (actual dispatch logic) will be same c.f. "arg_name"-approach.  On a pros for the inspect approach: we don't duplicate information, that already available from the function definition...

PS: "not quite guaranteed to be correct" - I don't think this is true, if we are talking about pure-python code.  ``inspect.signature()`` should be correct, unless there is a bug: either in the inspect module or in the user code.  For example, someone could create decorator, that changes function signature (but we have the ``__signature__`` attribute to workaround such cases; unfortunately this is not well documented).

**Comment by skirpichev** [comment]
> I don't think a decorator that replaces signatures with *args, **kwargs is doing anything wrong.

It's not that easy.  To really replace function signature (wrt the inspect module point of view) - you have to define the ``__signature__`` attribute on some wrapped function.

IIUC, the inspect module assumes, that decorator doesn't change function signature (and if it does so - the ``__signature__`` attribute must be added to prevent unwrapping to incorrect (original) function signature.

> But it would prevent this feature from working.

Sure, it's possible.  But it will be a bug in user code...

**Comment by encukou** [comment]
> IIUC, the inspect module assumes, that decorator doesn't change function signature

The decorator module uses the signature of the decorated function, unless it has `__wrapped__` and `follow_wrapped` is set. And `follow_wrapped` is configurable for a reason :)

> Sure, it's possible. But it will be a bug in user code...

Well, we disagree. 
But this is not the place for this discussion. Could you open a topic Discourse if you want to push this forward?
