### ISSUE TITLE
[Windows] test_asyncio fails with application verifier! _cancel_overlapped() fails with "The handle is invalid"

### ISSUE THREAD

**Issue by e963db72-c8db-4b8b-b0b5-71a12b2ef945** [python/cpython#80971]
BPO | [36790](https://bugs.python.org/issue36790)
--- | :---
Nosy | @vstinner, @asvetlov, @1st1, @ariccio
Files | <li>[python_test_invalid_handle_failure.TXT](https://bugs.python.org/file48298/python_test_invalid_handle_failure.TXT "Uploaded as text/plain at 2019-05-04.00:10:07 by @ariccio"): Windbg output for the failure</li><li>[python_invalid_handle.PNG](https://bugs.python.org/file48299/python_invalid_handle.PNG "Uploaded as image/png at 2019-05-04.00:13:49 by @ariccio"): screencap of tracebacj</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-04.00:10:11.166>
labels = ['tests', '3.9', 'expert-asyncio']
title = '[Windows] test_asyncio fails with application verifier! _cancel_overlapped() fails with "The handle is invalid"'
updated_at = <Date 2019-10-21.10:34:16.651>
user = 'https://github.com/ariccio'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-21.10:34:16.651>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'asyncio']
creation = <Date 2019-05-04.00:10:11.166>
creator = 'Alexander Riccio'
dependencies = []
files = ['48298', '48299']
hgrepos = []
issue_num = 36790
keywords = []
message_count = 6.0
messages = ['341365', '341366', '342459', '342460', '342526', '355046']
nosy_count = 5.0
nosy_names = ['vstinner', 'asvetlov', 'yselivanov', 'Alexander Riccio', 'samjonas']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36790'
versions = ['Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing because of lack of failing tests and a reproducer and instructions.
