### ISSUE TITLE
Add = to f-strings for easier debugging.

### ISSUE THREAD

**Issue by ericvsmith** [python/cpython#80998]
BPO | [36817](https://bugs.python.org/issue36817)
--- | :---
Nosy | @warsaw, @larryhastings, @ericvsmith, @serhiy-storchaka, @ilevkivskyi, @Carreau, @pablogsal
PRs | <li>python/cpython#13123</li><li>python/cpython#13059</li><li>python/cpython#13249</li><li>python/cpython#13256</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = <Date 2019-05-11.19:54:49.046>
created_at = <Date 2019-05-06.18:10:56.540>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Add = to f-strings for easier debugging.'
updated_at = <Date 2019-05-22.16:20:16.071>
user = 'https://github.com/ericvsmith'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-22.16:20:16.071>
actor = 'pablogsal'
assignee = 'eric.smith'
closed = True
closed_date = <Date 2019-05-11.19:54:49.046>
closer = 'pablogsal'
components = ['Interpreter Core']
creation = <Date 2019-05-06.18:10:56.540>
creator = 'eric.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 36817
keywords = ['patch']
message_count = 18.0
messages = ['341582', '341583', '341668', '341682', '341691', '341694', '341696', '341722', '341732', '341774', '341940', '342208', '342211', '342220', '342231', '343106', '343210', '343211']
nosy_count = 7.0
nosy_names = ['barry', 'larry', 'eric.smith', 'serhiy.storchaka', 'levkivskyi', 'mbussonn', 'pablogsal']
pr_nums = ['13123', '13059', '13249', '13256']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36817'
versions = ['Python 3.8']
```

</p></details>

**Comment by Teut2711** [comment]
Don't know how good this implemented feature is but , one of the mess is the getting item from dict in python since you have to put a [] and then "" in f strings.

`python
d = {"a":90, "b":67}
print(f"a is {d['a']} and b is {d['b']}"
`
Any intention to improve this in future?

**Comment by ericvsmith** [comment]
@Teut2711 : I'm not sure what you're proposing. If you have a concrete suggestion, please discuss it at https://discuss.python.org/c/ideas/6
