### ISSUE TITLE
Support the buffer protocol in code objects

### ISSUE THREAD

**Issue by DinoV** [python/cpython#81020]
BPO | [36839](https://bugs.python.org/issue36839)
--- | :---
Nosy | @brettcannon, @vstinner, @DinoV, @methane, @skrah, @ericsnowcurrently, @serhiy-storchaka
PRs | <li>python/cpython#13177</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/DinoV'
closed_at = None
created_at = <Date 2019-05-07.19:56:26.921>
labels = ['interpreter-core', 'type-feature', '3.8']
title = 'Support the buffer protocol in code objects'
updated_at = <Date 2020-07-01.10:38:05.486>
user = 'https://github.com/DinoV'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-01.10:38:05.486>
actor = 'skrah'
assignee = 'dino.viehland'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-05-07.19:56:26.921>
creator = 'dino.viehland'
dependencies = []
files = []
hgrepos = []
issue_num = 36839
keywords = ['patch']
message_count = 33.0
messages = ['341808', '343731', '343824', '343837', '343851', '343859', '343992', '343993', '343996', '343999', '344009', '344013', '344097', '344168', '344172', '344173', '344200', '344253', '344256', '344262', '344494', '344506', '344529', '344538', '344543', '344544', '344622', '344660', '344752', '372737', '372738', '372739', '372745']
nosy_count = 7.0
nosy_names = ['brett.cannon', 'vstinner', 'dino.viehland', 'methane', 'skrah', 'eric.snow', 'serhiy.storchaka']
pr_nums = ['13177']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36839'
versions = ['Python 3.8']
```

</p></details>

**Comment by ericsnowcurrently** [comment]
FYI, one thing I'm planning on (in the not-distant future) is to work toward properly supporting static code objects.  We may even explore making such objects const, i.e. to get them into the binary's read-only data section (`.rodata` instead of `.data`).  (FWIW, we'll probably end up splitting up code objects into immutable vs. mutable parts.)

Depending on how that plays out, something like that could cover at least some of the cases that buffer protocol support in code objects would have addressed.

**Comment by methane** [comment]
@ericsnowcurrently I like your idea.
Buffer protocol is too generic and fat for co_code and any other bytes attributes in code objects.
