### ISSUE TITLE
Python3.7.2 fails to cross-compile (yocto / openembedded) when target is mips softfloat

### ISSUE THREAD

**Issue by f752b96b-e8f9-4539-8370-c2852ac68e9b** [python/cpython#81033]
BPO | [36852](https://bugs.python.org/issue36852)
--- | :---
Nosy | @doko42, @moreati, @DasRoteSkelett, @K. PANIK
PRs | <li>python/cpython#13196</li>
Files | <li>[0001-fixing-finding-of-triplet-on-softfloat-mips.patch](https://bugs.python.org/file48318/0001-fixing-finding-of-triplet-on-softfloat-mips.patch "Uploaded as text/plain at 2019-05-08.16:01:07 by @DasRoteSkelett")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-08.16:01:08.572>
labels = ['build', '3.7']
title = 'Python3.7.2 fails to cross-compile (yocto / openembedded) when target is mips softfloat'
updated_at = <Date 2020-03-24.16:25:15.195>
user = 'https://github.com/DasRoteSkelett'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-24.16:25:15.195>
actor = 'medhi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Cross-Build']
creation = <Date 2019-05-08.16:01:08.572>
creator = 'mschoepf'
dependencies = []
files = ['48318']
hgrepos = []
issue_num = 36852
keywords = ['patch']
message_count = 9.0
messages = ['341894', '341900', '356239', '356240', '356300', '356373', '356374', '356381', '364940']
nosy_count = 5.0
nosy_names = ['doko', 'SilentGhost', 'Alex.Willmer', 'mschoepf', 'medhi']
pr_nums = ['13196']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue36852'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as Python 3.7 and yocto mips softfloat is not supported as per PEP 11.
