### ISSUE TITLE
sqlite3 dml statement detection does not account for CTEs

### ISSUE THREAD

**Issue by 9f7dd279-17db-4f62-9e03-b1e264506a25** [python/cpython#81040]
BPO | [36859](https://bugs.python.org/issue36859)
--- | :---
Nosy | @berkerpeksag, @animalize, @tirkarthi, @coleifer, @erlend-aasland
PRs | <li>python/cpython#13216</li><li>python/cpython#24492</li>
Files | <li>[36859.patch](https://bugs.python.org/file48319/36859.patch "Uploaded as text/plain at 2019-05-09.03:39:01 by @coleifer")</li><li>[36859-2.patch](https://bugs.python.org/file48320/36859-2.patch "Uploaded as text/plain at 2019-05-09.04:12:20 by @coleifer"): Working patch that retains backwards-compatibility.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-08.23:08:24.384>
labels = ['3.8', 'type-bug', 'library']
title = 'sqlite3 dml statement detection does not account for CTEs'
updated_at = <Date 2021-08-11.21:02:17.366>
user = 'https://github.com/coleifer'
```

bugs.python.org fields:
```python
activity = <Date 2021-08-11.21:02:17.366>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-05-08.23:08:24.384>
creator = 'coleifer'
dependencies = []
files = ['48319', '48320']
hgrepos = []
issue_num = 36859
keywords = ['patch']
message_count = 9.0
messages = ['341949', '341956', '341958', '341961', '341962', '386713', '386716', '386721', '399418']
nosy_count = 5.0
nosy_names = ['berker.peksag', 'malin', 'xtreak', 'coleifer', 'erlendaasland']
pr_nums = ['13216', '24492']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36859'
versions = ['Python 3.8']
```

</p></details>

**Comment by erlend-aasland** [comment]
I'm reopening this, because this issue materialises into two problems:

1. The implicit transaction handling is not as expected (`in_transaction`).
   Superseded by: gh-83638
3. `rowcount` is not updated as expected for CTE's.

**Comment by erlend-aasland** [comment]
> 2\. `rowcount` is not updated as expected for CTE's.

Suggesting to address the `rowcount` issue by improving the accuracy of the `rowcount` docs. We can then close this issue.

**Comment by erlend-aasland** [comment]
Rowcount docs are updated in the following branches:

- main: #94940 
- 3.11: #95124 
- 3.10: #95125 

Considering this as resolved.
