### ISSUE TITLE
Returning None from a callback with restype py_object decrements None's refcount too much

### ISSUE THREAD

**Issue by a197fd7e-f9de-4c4f-a391-d3b40d861fb7** [python/cpython#81061]
BPO | [36880](https://bugs.python.org/issue36880)
--- | :---
Nosy | @freakboy3742, @eryksun, @tonybaloney, @dgelessus
PRs | <li>python/cpython#13364</li>
Files | <li>[python3.8_2019-05-11-000251.crash](https://bugs.python.org/file48325/python3.8_2019-05-11-000251.crash "Uploaded as text/plain at 2019-05-10.22:38:58 by @dgelessus"): OS X crash report (Python 3.8)</li><li>[test_gc_ctypes.py](https://bugs.python.org/file48326/test_gc_ctypes.py "Uploaded as text/plain at 2019-05-11.06:10:16 by @tonybaloney")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tonybaloney'
closed_at = None
created_at = <Date 2019-05-10.22:39:01.064>
labels = ['easy', '3.8', '3.9', '3.10', 'ctypes', 'type-crash']
title = "Returning None from a callback with restype py_object decrements None's refcount too much"
updated_at = <Date 2021-03-13.06:00:14.026>
user = 'https://github.com/dgelessus'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-13.06:00:14.026>
actor = 'eryksun'
assignee = 'anthonypjshaw'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2019-05-10.22:39:01.064>
creator = 'dgelessus'
dependencies = []
files = ['48325', '48326']
hgrepos = []
issue_num = 36880
keywords = ['patch', 'easy (C)']
message_count = 10.0
messages = ['342141', '342163', '342164', '342165', '342166', '342174', '342186', '342221', '342304', '342387']
nosy_count = 4.0
nosy_names = ['freakboy3742', 'eryksun', 'anthonypjshaw', 'dgelessus']
pr_nums = ['13364']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue36880'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-100877
* gh-100878

**Comment by hauntsaninja** [comment]
Thanks, looks like this was completed
