### ISSUE TITLE
Missing documentation for decorators

### ISSUE THREAD

**Issue by 243bf073-7a9a-4861-97f6-492d27152381** [python/cpython#81094]
BPO | [36913](https://bugs.python.org/issue36913)
--- | :---
Nosy | @matrixise, @JulienPalard, @mblahay, @tomerv

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-14.07:35:28.614>
labels = ['3.8', 'type-feature', '3.7', 'docs']
title = 'Missing documentation for decorators'
updated_at = <Date 2019-05-27.03:15:43.677>
user = 'https://github.com/tomerv'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-27.03:15:43.677>
actor = 'mblahay'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-05-14.07:35:28.614>
creator = 'tomerv'
dependencies = []
files = []
hgrepos = []
issue_num = 36913
keywords = []
message_count = 5.0
messages = ['342435', '342436', '342437', '342438', '343604']
nosy_count = 5.0
nosy_names = ['docs@python', 'matrixise', 'mdk', 'mblahay', 'tomerv']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36913'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-113588
* gh-113643
* gh-113644

**Comment by slateny** [comment]
It seems that the current search https://docs.python.org/3/search.html?q=decorator does point towards the glossary as the first search result.

The [Class Definitions](https://docs.python.org/3/reference/compound_stmts.html#class-definitions) section does link PEP 3129 and also references PEP 318 so everything's technically in the doc, but as mentioned PEP 318 can also go under the box at the end of [Function definitions](https://docs.python.org/3/reference/compound_stmts.html#function-definitions).

**Comment by Rasputin2** [comment]
Hello, I am a first time contributor.  If this is something that still needs assistance, I could start by just adding a description of decorators in the docs, see if you accept that, and then start drafting entries for each decorator one by one.  This would be a good learning experience for me,.  Not sure if this is still something you guys believed needed to be worked on or not.

**Comment by hugovk** [comment]
Hello! I think all that's left is:

> PEP 318 can also go under the box at the end of [Function definitions](https://docs.python.org/3/reference/compound_stmts.html#function-definitions) for clarity.

Would you like to open a PR?

**Comment by Rasputin2** [comment]
OK.  I will do tomorrow.
John D. McDonald
PJ Consulting LLCPh.      1-312-945-3518Mobile 1-312-479-2854 

    On Thursday, December 28, 2023 at 01:25:10 AM CST, Hugo van Kemenade ***@***.***> wrote:  
 
 


Hello! I think all that's left is:


PEP 318 can also go under the box at the end of Function definitions for clarity.


Would you like to open a PR?

**Comment by Rasputin2** [comment]
Hi Hugo, 

Sorry if I am being dense here, but this is my first contribution.  First, I tried just editing the code on Codespace in Github and then I tried forking, cloning, and making the change.  Either way, I cannot seem to "find" where the docs "are" in the code.  In other words, I see this:

![image](https://github.com/python/cpython/assets/43117960/fcaafc90-ad0c-4fe1-a1bd-250e9621d52c)

I don't actually 'see' the html for the docs that folks are referencing.  I assume there is an html file somewhere for me to modify, but I cannot seem to find it.  Apologies if this is a noob question, but I can't seem to see the next step here.

**Comment by hugovk** [comment]
The HTML is generated from RST files.

If you go to https://docs.python.org/3/reference/compound_stmts.html#function-definitions and click Show Source in the left menu that takes you to https://github.com/python/cpython/blob/main/Doc/reference/compound_stmts.rst, which is the file to edit.

To generate the HTML:

```bat
cd Doc
.\make html
```
And open build/html/index.html

See also https://devguide.python.org/documentation/start-documenting/

**Comment by Rasputin2** [comment]
Ok I'll give it a shot later today.

Sent from AOL on Android 
 
  On Sat, Dec 30, 2023 at 3:36 AM, Hugo van ***@***.***> wrote:   


The HTML is generated from RST files.

If you go to https://docs.python.org/3/reference/compound_stmts.html#function-definitions and click Show Source in the left menu that takes you to https://github.com/python/cpython/blob/main/Doc/reference/compound_stmts.rst, which is the file to edit.

To generate the HTML:
cd Doc
.\make html
And open build/html/index.html

See also https://devguide.python.org/documentation/start-documenting/

**Comment by Rasputin2** [comment]
Hi Hugo:

I believe I did this correctly (hopefully).  A screenshot of the change and the github pull request are shown below:

![image](https://github.com/python/cpython/assets/43117960/4f9314fb-31a3-4f73-a40b-c48d3c24e069)


![image](https://github.com/python/cpython/assets/43117960/002b890c-29ab-44d0-95ab-e31cee1e5f96)
