### ISSUE TITLE
traceback docstrings should explicitly state return values instead of referring to other functions

### ISSUE THREAD

**Issue by affb16c2-6fdb-403f-b328-86b7e719c99e** [python/cpython#81108]
BPO | [36927](https://bugs.python.org/issue36927)
--- | :---
Nosy | @aaronchall, @mangrisano
PRs | <li>python/cpython#13359</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-15.17:04:45.954>
labels = ['3.8', 'type-bug', '3.7', 'docs']
title = 'traceback docstrings should explicitly state return values instead of referring to other functions'
updated_at = <Date 2019-05-16.13:36:45.786>
user = 'https://github.com/aaronchall'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-16.13:36:45.786>
actor = 'mangrisano'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-05-15.17:04:45.954>
creator = 'Aaron Hall'
dependencies = []
files = []
hgrepos = []
issue_num = 36927
keywords = ['patch']
message_count = 3.0
messages = ['342588', '342589', '342633']
nosy_count = 4.0
nosy_names = ['SilentGhost', 'docs@python', 'Aaron Hall', 'mangrisano']
pr_nums = ['13359']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36927'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Closing. As I explained on the PR, I don't think it's a good idea to copy-paste documentation any more than it is to copy-paste code.

**Comment by ezio-melotti** [comment]
I agree that copy-pasting is not a good solution for the issue, however I think the issue reported by @aaronchall is still valid.

Anecdotally, every time I want to print a traceback I have to go through a list of similarly named functions with unhelpful descriptions, and eventually I either end up looking at the somewhat confusing examples or start trying the functions from the interpreter to see which one gives me the result I want.

I would reopen this, unless there is already another issue/plan about updating/improving the `traceback` docs as a whole (possibly making them Diataxis-friendly).
