### ISSUE TITLE
test_recursive_repr breaks tracing in test_xml_etree

### ISSUE THREAD

**Issue by 040eebe6-04c4-48be-a928-2cd0c41360bb** [python/cpython#81135]
BPO | [36954](https://bugs.python.org/issue36954)
--- | :---
Nosy | @scoder, @blueyed, @xdegaye, @serhiy-storchaka, @GPHemsley
PRs | <li>python/cpython#13267</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-18.01:23:46.255>
labels = ['3.8', 'tests']
title = 'test_recursive_repr breaks tracing in test_xml_etree'
updated_at = <Date 2019-05-24.22:16:17.997>
user = 'https://github.com/GPHemsley'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-24.22:16:17.997>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2019-05-18.01:23:46.255>
creator = 'gphemsley'
dependencies = []
files = []
hgrepos = []
issue_num = 36954
keywords = []
message_count = 2.0
messages = ['342783', '343437']
nosy_count = 5.0
nosy_names = ['scoder', 'blueyed', 'xdegaye', 'serhiy.storchaka', 'gphemsley']
pr_nums = ['13267']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36954'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
3.8 is no longer maintain and the OP did reply to a request for the precise output. I am therefore closing this.

Please reopen or create a new issue if you are seeing this on a current version (>= 3.10) and can provide more information: which system, how you ran the test, how exactly it failed.
