### ISSUE TITLE
ISO date errors in _strptime are jumbled

### ISSUE THREAD

**Issue by 040eebe6-04c4-48be-a928-2cd0c41360bb** [python/cpython#81140]
BPO | [36959](https://bugs.python.org/issue36959)
--- | :---
Nosy | @pganssle, @GPHemsley
PRs | <li>python/cpython#13408</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-18.19:46:43.829>
labels = ['tests', '3.8', 'library']
title = 'ISO date errors in _strptime are jumbled'
updated_at = <Date 2019-05-19.01:10:45.613>
user = 'https://github.com/GPHemsley'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-19.01:10:45.613>
actor = 'gphemsley'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests']
creation = <Date 2019-05-18.19:46:43.829>
creator = 'gphemsley'
dependencies = []
files = []
hgrepos = []
issue_num = 36959
keywords = ['patch']
message_count = 5.0
messages = ['342810', '342811', '342812', '342816', '342828']
nosy_count = 2.0
nosy_names = ['p-ganssle', 'gphemsley']
pr_nums = ['13408']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue36959'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
There are two changes in test results:

`_strptime('1999 256', '%G %j')`:
was "ISO year directive '%G' must be used with the ISO week directive '%V' and a weekday directive ('%A', '%a', '%w', or '%u')."
proposed "Day of the year directive '%j' is not compatible with ISO year directive '%G'. Use '%Y' instead."

`_strptime('50 5', '%V %u')`:
was "ISO week directive '%V' is incompatible with the year directive '%Y'. Use the ISO year '%G' instead."
proposed "ISO week directive '%V' must be used with the ISO year directive '%G' and a weekday directive ('%A', '%a', '%w', or '%u')."

In both cases the former message refers to a directive that does not appear in the format string.

**Comment by serhiy-storchaka** [comment]
I consider this as a bug.

**Comment by serhiy-storchaka** [comment]
Thank you for your contribution @GPHemsley. Sorry for the delay.
