### ISSUE TITLE
zipfile: string IndexError on extract

### ISSUE THREAD

**Issue by c77585bf-32ea-4ddf-8b2e-8c016536a854** [python/cpython#81169]
BPO | [36988](https://bugs.python.org/issue36988)
--- | :---
Nosy | @18z, @krnick, @alter-bug-tracer, @iritkatriel
Files | <li>[file0.zip](https://bugs.python.org/file48345/file0.zip "Uploaded as application/zip at 2019-05-21.10:49:55 by @alter-bug-tracer")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-21.10:49:55.903>
labels = ['type-bug', '3.9', '3.10', '3.11']
title = 'zipfile: string IndexError on extract'
updated_at = <Date 2022-01-16.19:41:26.655>
user = 'https://github.com/alter-bug-tracer'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-16.19:41:26.655>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-05-21.10:49:55.903>
creator = 'alter-bug-tracer'
dependencies = []
files = ['48345']
hgrepos = []
issue_num = 36988
keywords = []
message_count = 5.0
messages = ['343006', '343047', '343052', '343140', '410717']
nosy_count = 4.0
nosy_names = ['18z', 'krnick', 'alter-bug-tracer', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue36988'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
The code has been change to use ``self.filename.endswith('/')`` instead of ``self.filename[-1] == '/'``, so this error can no longer occur.
