### ISSUE TITLE
Document that spwd is considered harmful

### ISSUE THREAD

**Issue by tiran** [python/cpython#81178]
BPO | [36997](https://bugs.python.org/issue36997)
--- | :---
Nosy | @vstinner, @giampaolo, @tiran

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2019-05-21.17:00:09.808>
labels = ['3.8', '3.9', '3.10', 'extension-modules', 'type-feature', 'docs']
title = 'Document that spwd is considered harmful'
updated_at = <Date 2021-03-31.20:00:15.345>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-31.20:00:15.345>
actor = 'christian.heimes'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Extension Modules']
creation = <Date 2019-05-21.17:00:09.808>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 36997
keywords = []
message_count = 3.0
messages = ['343072', '343122', '343145']
nosy_count = 4.0
nosy_names = ['vstinner', 'giampaolo.rodola', 'christian.heimes', 'Arfrever']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue36997'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by hugovk** [comment]
Note the spwd module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by iritkatriel** [comment]
> Note the spwd module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

Right, and the deprecation notice links to PEP 594, which contains information about why this module is considered bad.
