### ISSUE TITLE
wait_for(coro, timeout=0) memleak

### ISSUE THREAD

**Issue by dd3db5ee-f287-4f3c-8fe6-7240e020a247** [python/cpython#81223]
BPO | [37042](https://bugs.python.org/issue37042)
--- | :---
Nosy | @asvetlov, @1st1, @ixje
Files | <li>[test_leak_minimal.py](https://bugs.python.org/file48356/test_leak_minimal.py "Uploaded as text/plain at 2019-05-25.12:09:54 by @ixje"): minimal example that bleeds memory</li><li>[test_leak_minimal_mem_consumption.png](https://bugs.python.org/file48357/test_leak_minimal_mem_consumption.png "Uploaded as image/png at 2019-05-25.12:26:15 by @ixje")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-25.12:09:54.889>
labels = ['expert-asyncio', '3.7', 'performance']
title = 'wait_for(coro, timeout=0) memleak'
updated_at = <Date 2019-05-25.12:34:53.128>
user = 'https://github.com/ixje'
```

bugs.python.org fields:
```python
activity = <Date 2019-05-25.12:34:53.128>
actor = 'ixje'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-05-25.12:09:54.889>
creator = 'ixje'
dependencies = []
files = ['48356', '48357']
hgrepos = []
issue_num = 37042
keywords = []
message_count = 6.0
messages = ['343470', '343472', '343473', '343475', '343476', '343477']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'ixje']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue37042'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
I am unable to reproduce the leak on main branch. I profiled with memray and the rss usage is constant.

![newplot](https://user-images.githubusercontent.com/59607654/184598896-e50a3281-3f10-439e-8ab4-d0485e574bcf.png)

**Comment by iritkatriel** [comment]
@kumaraditya303 were you able to reproduce it with 3.7?

**Comment by iritkatriel** [comment]
I tried myself - indeed I can reproduce it on 3.7 but no on main (on a MAC).
