### ISSUE TITLE
ensurepip --upgrade doesn't change the version of pip used by venv

### ISSUE THREAD

**Issue by cjw296** [python/cpython#81288]
BPO | [37107](https://bugs.python.org/issue37107)
--- | :---
Nosy | @warsaw, @doko42, @pfmoore, @ncoghlan, @cjw296, @ned-deily, @encukou, @zooba, @dstufft

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-31.06:14:55.269>
labels = ['type-feature', 'library', '3.9']
title = "ensurepip --upgrade doesn't change the version of pip used by venv"
updated_at = <Date 2019-06-10.17:23:32.441>
user = 'https://github.com/cjw296'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-10.17:23:32.441>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-05-31.06:14:55.269>
creator = 'cjw296'
dependencies = []
files = []
hgrepos = []
issue_num = 37107
keywords = []
message_count = 6.0
messages = ['344029', '345069', '345070', '345082', '345113', '345136']
nosy_count = 9.0
nosy_names = ['barry', 'doko', 'paul.moore', 'ncoghlan', 'cjw296', 'ned.deily', 'petr.viktorin', 'steve.dower', 'dstufft']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37107'
versions = ['Python 3.9']
```

</p></details>

**Comment by XChikuX** [comment]
Hey guys,
Do we have any support for this feature?
We should either re-think if this issue can be solved.
Or close it permanently saying: **Won't fix**

**Comment by cjw296** [comment]
The issue still exists, I support @ncoghlan approach, and I have as much faith in pypi as I do in Fedora's distribution mechanisms, if not more ;-)

**Comment by zooba** [comment]
> I have as much faith in pypi as I do in Fedora's distribution mechanisms, if not more ;-)

It's not the mechanisms, but the validation. Fedora will have tested the version of pip you're getting from them in their context, whereas the PyPI release has only been tested in other contexts.

I totally understand Fedora not wanting to support users when they're not using their packages, and so not wanting them to easily get into an unsupported scenario. If there is any change made here, it should be easily patched out.

Possibly a more consistent solution is to more clearly document that it's for upgrading _old_ venvs, and possibly add output indicating that it's only upgrading to the "default" versions. If this is still confusing, then we could display "Use 'python -m pip --upgrade pip' to upgrade from public internet sources".

But this doesn't really affect me. So if those who are impacted here decide it's best to just go straight to the newest release of pip, go for it.

**Comment by XChikuX** [comment]
The important patch result I'm expecting is that, we remain consistent with the latest environments outside and inside a venv.
There have been breaking changes to how packages are handled during their installing among pip versions. I do not want to deal with broken environments in python ever.
Not using PyPI is fine as long as there is an update mechanism for the defaults both outside and inside a venv.

**Comment by cjw296** [comment]
It's quite clear this issue is going nowhere. It pretty frustrating that we have such a confusing situation, but I can't see consensus ever being reached so we'll just all have to live with this confusing and broken behaviour, but hey, it's Python Packaging, so SNAFU, right?
