### ISSUE TITLE
Automatically dedent docstring constants by default

### ISSUE THREAD

**Issue by gpshead** [python/cpython#81283]
BPO | [37102](https://bugs.python.org/issue37102)
--- | :---
Nosy | @gpshead, @methane, @Carreau, @pablogsal, @remilapeyre

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-05-30.18:00:00.547>
labels = ['interpreter-core', 'type-feature', '3.9']
title = 'Automatically dedent docstring constants by default'
updated_at = <Date 2019-06-06.14:36:45.161>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-06.14:36:45.161>
actor = 'remi.lapeyre'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-05-30.18:00:00.547>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 37102
keywords = []
message_count = 4.0
messages = ['343990', '344128', '344801', '344819']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'methane', 'mbussonn', 'pablogsal', 'remi.lapeyre']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37102'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-106411

**Comment by methane** [comment]
cleandoc is not idempotent. If we cleandoc on compile time, pydoc and inspect.getdoc() shouldn't cleandoc(__doc__).

And if user write to `obj.__doc__`, user need to cleandoc. Otherwise, pydoc will have broken layout.
This is backward incompatibile change.

```py
import inspect

s = """
  first line
    second line
      third line
"""

while True:
    print('---')
    print(s)
    t = inspect.cleandoc(s)
    if t == s:
        break
    s = t

print('---')
```

output:

```
---

  first line
    second line
      third line

---
first line
  second line
    third line
---
first line
second line
  third line
---
```

**Comment by methane** [comment]
In the PR, compile time cleandoc doesn't remove leading and trailing newlines.

code:

```py
import inspect

def foo():
    """
    first line
      second
        third
    """

print('---')
print(foo.__doc__)
print('---')
print(inspect.getdoc(foo))
print('---')
```

current behavior:

```
---

    first line
      second
        third

---
first line
  second
    third
---
```

c-cleandoc (#106066)

```
---

first line
  second
    third

---
first line
  second
    third
---
```

**Comment by hroncok** [comment]
> Change of breaking things with this change? not impossible, but extremely minor. Something using docstrings as data _and_ depending on leading indentation whitespace preservation would not like this. I am not aware of anything that would ever do that.

Tests often do that.

So far I saw:

```
_________________________________ test_excepts _________________________________

    def test_excepts():
        # These are descriptors, make sure this works correctly.
        assert excepts.__name__ == 'excepts'
>       assert (
            'A wrapper around a function to catch exceptions and\n'
            '    dispatch to a handler.\n'
        ) in excepts.__doc__
E       AssertionError: assert 'A wrapper around a function to catch exceptions and\n    dispatch to a handler.\n' in 'A wrapper around a function to catch exceptions and\ndispatch to a handler.\n\nThis is like a functional try/except block, in the same way that\nifexprs are functional if/else blocks.\n\nExamples\n--------\n>>> excepting = excepts(\n...     ValueError,\n...     lambda a: [1, 2].index(a),\n...     lambda _: -1,\n... )\n>>> excepting(1)\n0\n>>> excepting(3)\n-1\n\nMultiple exceptions and default except clause.\n>>> excepting = excepts((IndexError, KeyError), lambda a: a[0])\n>>> excepting([])\n>>> excepting([1])\n1\n>>> excepting({})\n>>> excepting({0: 1})\n1\n'
E        +  where 'A wrapper around a function to catch exceptions and\ndispatch to a handler.\n\nThis is like a functional try/except block, in the same way that\nifexprs are functional if/else blocks.\n\nExamples\n--------\n>>> excepting = excepts(\n...     ValueError,\n...     lambda a: [1, 2].index(a),\n...     lambda _: -1,\n... )\n>>> excepting(1)\n0\n>>> excepting(3)\n-1\n\nMultiple exceptions and default except clause.\n>>> excepting = excepts((IndexError, KeyError), lambda a: a[0])\n>>> excepting([])\n>>> excepting([1])\n1\n>>> excepting({})\n>>> excepting({0: 1})\n1\n' = excepts.__doc__

toolz/tests/test_functoolz.py:741: AssertionError
```

(toolz)

And:

```
________________________ UtilsTests.test_filter_params _________________________

self = <tests.oauth1.rfc5849.test_utils.UtilsTests testMethod=test_filter_params>

    def test_filter_params(self):
    
        # The following is an isolated test function used to test the filter_params decorator.
        @filter_params
        def special_test_function(params, realm=None):
            """ I am a special test function """
            return 'OAuth ' + ','.join(['='.join([k, v]) for k, v in params])
    
        # check that the docstring got through
>       self.assertEqual(special_test_function.__doc__, " I am a special test function ")
E       AssertionError: 'I am a special test function ' != ' I am a special test function '
E       - I am a special test function 
E       +  I am a special test function 
E       ? +

tests/oauth1/rfc5849/test_utils.py:60: AssertionError
```

(oauthlib)

**Comment by hroncok** [comment]
```
======================================================================
FAIL: test_asReStructuredText_empty_with_multiline_docstring (zope.interface.tests.test_document.Test_asReStructuredText.test_asReStructuredText_empty_with_multiline_docstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-zope-interface-6.0-2.fc40.x86_64/usr/lib64/python3.13/site-packages/zope/interface/tests/test_document.py", line 298, in test_asReStructuredText_empty_with_multiline_docstring
    self.assertEqual(self._callFUT(IEmpty), EXPECTED)
AssertionError: '``IE[39 chars]n \n It can be used to annotate any class or o[66 chars]\n\n' != '``IE[39 chars]n \n             It can be used to annotate an[90 chars]\n\n'
  ``IEmpty``
  
   This is an empty interface.
   
-  It can be used to annotate any class or object, because it promises
+              It can be used to annotate any class or object, because it promises
? ++++++++++++
-  nothing.
+              nothing.
  
   Attributes:
  
   Methods:
  


======================================================================
FAIL: test_asStructuredText_empty_with_multiline_docstring (zope.interface.tests.test_document.Test_asStructuredText.test_asStructuredText_empty_with_multiline_docstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILDROOT/python-zope-interface-6.0-2.fc40.x86_64/usr/lib64/python3.13/site-packages/zope/interface/tests/test_document.py", line 74, in test_asStructuredText_empty_with_multiline_docstring
    self.assertEqual(self._callFUT(IEmpty), EXPECTED)
AssertionError: 'IEmp[35 chars]n \n It can be used to annotate any class or o[66 chars]\n\n' != 'IEmp[35 chars]n \n             It can be used to annotate an[90 chars]\n\n'
  IEmpty
  
   This is an empty interface.
   
-  It can be used to annotate any class or object, because it promises
+              It can be used to annotate any class or object, because it promises
? ++++++++++++
-  nothing.
+              nothing.
  
   Attributes:
  
   Methods:
  


----------------------------------------------------------------------
Ran 1355 tests in 0.391s
```

(zope-interface)

**Comment by hroncok** [comment]
Even scipy:

```
________________________________ test_decorator ________________________________
[gw1] linux -- Python 3.13.0 /usr/bin/python3

    @pytest.mark.skipif(DOCSTRINGS_STRIPPED, reason="docstrings stripped")
    def test_decorator():
        with suppress_warnings() as sup:
            sup.filter(category=DeprecationWarning)
            # with unindentation of parameters
            decorator = doccer.filldoc(doc_dict, True)
    
            @decorator
            def func():
                """ Docstring
                %(strtest3)s
                """
>           assert_equal(func.__doc__, """ Docstring
                Another test
                   with some indent
                """)
E           AssertionError: 
E           Items are not equal:
E            ACTUAL: 'Docstring\nAnother test\n   with some indent\n'
E            DESIRED: ' Docstring\n            Another test\n               with some indent\n            '

scipy/misc/tests/test_doccer.py:86: AssertionError
```

**Comment by Carreau** [comment]
Yep, this breaks IPython as well, as we have test testing that docstrings actually have leading spaces.

**Comment by methane** [comment]
Do you think we should revert this change in 3.13?

**Comment by hroncok** [comment]
If there is a plan to include it in 3.14 anyway, then probably not. This is a breaking change but I have no idea how to properly have a deprecation period.

**Comment by Carreau** [comment]
I think this is still early enough, but the more time goes on, the more Python compile and ast lose informations that is useful for tooling. And it often would be nice to have a 2 passes tokenizer/compiler with maybe an option to not run the cleanup and normalisation passes ?

**Comment by gpshead** [comment]
It is ideal if the impacted things can improve their tests to not rely on leading spaces in the middle of docstrings.

IMNSHO, it is still too early in 3.13 to decide if we should roll this back. So far I haven't seen any *compelling* examples that are not just over specific tests asserting things to be "as previously implemented" rather than code relying specifically on code indentation style/level based leading spaces being present in docstrings.

The win for the world by reducing space consumed by docstrings by default feels rather large. So lets *try* to see if we can keep this.

---

regarding future tokenizer & compiler do less or more options... other things have a desire for some of those as well, but so far it has been hard to get people interested in providing that kind of thing within CPython and the standard library as CPython won't use such things and offering such options is by its nature both slower and painful to maintain.  It feels like third party Python code analysis tooling may be a better way to get that in a less-disruptive manner.

**Comment by pablogsal** [comment]
This is also a compiler change which means that the tokenize and AST modules won't be affected by the optimisation. Tools can still analyse source code normally before this optimisation is applied.

**Comment by gpshead** [comment]
> This is a breaking change but I have no idea how to properly have a deprecation period.

agreed.  it'd be hard to do that in a meaningful manner.

There _are_ plausible designs to retain strict indentation included compatibility while reducing memory consumption & pyc size. They'd implementation complexity and could cpu usage as a tradeoff. Example: Storing docstrings compressed and transparently decompressing them upon `.__doc__` access.

**Comment by webknjaz** [comment]
Does this affect Sphinx's API generation from docstrings? Has anyone checked? It appears to me that it could break syntaxes like doctests or example code blocks that should be indented in RST which is what often ends up in docstrings.

**Comment by methane** [comment]
> Does this affect Sphinx's API generation from docstrings? Has anyone checked? It appears to me that it could break syntaxes like doctests or example code blocks that should be indented in RST which is what often ends up in docstrings.

This PR doesn't remove all indent. This PR remoes only common indent.
Sphinx uses `inspect.getdoc()` and `inspect.getdoc()` uses `inspect.cleandoc()`.
This PR doesn't break it because `inspect.cleandoc(s) == inspect.cleandoc(compile_time_remove_indent(s))` is guaranteed.

**Comment by webknjaz** [comment]
Ah, great! Thanks for clarifying. I wasn't sure by looking at that PR.

**Comment by domdfcoding** [comment]
Was it intended that with this change tabs are now automatically converted into 8 spaces in ``__doc__``, where previously they were left alone.

For example:

```python
def f():
	"""
	hello
		world
	"""

print(repr(f.__doc__))
```

Python 3.12: `'\n\thello\n\t\tworld\n\t'`

Python 3.13: `'\nhello\n        world\n'`

Previously I could call `__doc__.expandtabs` to get the desired tab size.

**Comment by methane** [comment]
> Was it intended that with this change tabs are now automatically converted into 8 spaces in `__doc__`, where previously they were left alone.

Yes it is intended. I intended almost ident to `inspect.cleandoc()` and `inspect.getdoc()`.
Is `__doc__` incompatible to `inspect.cleandoc()` important use case?
