### ISSUE TITLE
Use PEP570 syntax in the documentation

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#81315]
BPO | [37134](https://bugs.python.org/issue37134)
--- | :---
Nosy | @gvanrossum, @tim-one, @warsaw, @brettcannon, @rhettinger, @ncoghlan, @vstinner, @serhiy-storchaka, @willingc, @JulienPalard, @bskinn, @pganssle, @pablogsal, @grantjenks, @miss-islington
PRs | <li>python/cpython#13743</li><li>python/cpython#13851</li><li>python/cpython#13854</li><li>python/cpython#13874</li><li>python/cpython#13875</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-06-06.23:03:34.884>
created_at = <Date 2019-06-02.16:18:06.936>
labels = ['type-feature', '3.8', 'docs']
title = 'Use PEP570 syntax in the documentation'
updated_at = <Date 2019-06-06.23:44:53.211>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-06.23:44:53.211>
actor = 'miss-islington'
assignee = 'docs@python'
closed = True
closed_date = <Date 2019-06-06.23:03:34.884>
closer = 'pablogsal'
components = ['Documentation']
creation = <Date 2019-06-02.16:18:06.936>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 37134
keywords = ['patch']
message_count = 48.0
messages = ['344295', '344357', '344360', '344373', '344379', '344402', '344411', '344457', '344464', '344467', '344473', '344482', '344517', '344518', '344520', '344525', '344527', '344610', '344618', '344621', '344641', '344645', '344646', '344647', '344650', '344652', '344654', '344655', '344656', '344666', '344678', '344739', '344753', '344765', '344767', '344771', '344779', '344781', '344783', '344856', '344857', '344860', '344879', '344884', '344885', '344887', '344889', '344890']
nosy_count = 16.0
nosy_names = ['gvanrossum', 'tim.peters', 'barry', 'brett.cannon', 'rhettinger', 'ncoghlan', 'vstinner', 'docs@python', 'serhiy.storchaka', 'willingc', 'mdk', 'bskinn', 'p-ganssle', 'pablogsal', 'grantjenks', 'miss-islington']
pr_nums = ['13743', '13851', '13854', '13874', '13875']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37134'
versions = ['Python 3.8']
```

</p></details>

**Comment by skirpichev** [comment]
It seems, the Python Documentation Editorial Board decided that function signatures in sphinx docs should follow the language syntax in all cases: https://discuss.python.org/t/editorial-board-decisions/58580

@pablogsal, shouldn't this be reopened?  There are several closed issues (e.g. https://github.com/python/cpython/issues/101118), but this one seems to be a canonical one.
