### ISSUE TITLE
Allow multiple separators in Stream.readuntil

### ISSUE THREAD

**Issue by a1b08a40-034a-40a3-9764-5478a287bfe4** [python/cpython#81322]
BPO | [37141](https://bugs.python.org/issue37141)
--- | :---
Nosy | @asvetlov, @1st1, @bmerry, @websurfer5
PRs | <li>python/cpython#16429</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-03.09:32:30.680>
labels = ['type-feature', '3.9', 'expert-asyncio']
title = 'Allow multiple separators in Stream.readuntil'
updated_at = <Date 2019-09-26.19:48:53.882>
user = 'https://github.com/bmerry'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-26.19:48:53.882>
actor = 'yselivanov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-06-03.09:32:30.680>
creator = 'bmerry'
dependencies = []
files = []
hgrepos = []
issue_num = 37141
keywords = ['patch']
message_count = 11.0
messages = ['344397', '344398', '344399', '344403', '344404', '344405', '344409', '352089', '352179', '353323', '353335']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'bmerry', 'Jeffrey.Kintscher']
pr_nums = ['16429']
priority = 'normal'
resolution = 'later'
stage = 'patch review'
status = 'pending'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37141'
versions = ['Python 3.9']
```

</p></details>

**Comment by vgrebenschikov** [comment]
Worth to ressurect the initiative? ... reimplementing custom reader when multiple separators required ... is tough

**Comment by bmerry** [comment]
> The PR looks reasonable. Maybe someone can champion it and make it up to date for release in 3.13? I'm willing to release. Assuming the OP (@bmerry) has moved on, it would be easiest for someone else to check out their branch into their own clone of the cpython repo and merge or rebase main on it, etc. Alternatively, @bmerry, if you're still around, please have at it!

I'm still around - I stopped trying to keep the PR up to date with main because it wasn't clear if it would ever reach the front of the priority queue for the async devs. It sounds like @gvanrossum is happy to review an updated version now, so I'm happy to dust it off and update it when I find some free time.

**Comment by gvanrossum** [comment]
Yup let’s do that! Feature freeze is late May, but don’t wait till the last minute.

**Comment by bmerry** [comment]
@gvanrossum I didn't get any merge conflicts when I merged in `main` and the tests still pass, so I think this is ready for review.

**Comment by gvanrossum** [comment]
Thanks again!

There's one detail in a different repo that you may want to get ahead of. There's a declaration for this method in typeshed; ideally we should update this conditionally with a check for `sys.version_info`.

**Comment by bmerry** [comment]
> Thanks again!
> 
> There's one detail in a different repo that you may want to get ahead of. There's a declaration for this method in typeshed; ideally we should update this conditionally with a check for `sys.version_info`.

Thanks for the reminder - I'd meant to ask about typeshed but forgot. I'll sort out a PR there when I get a chance.

**Comment by bmerry** [comment]
Looking at the typeshed entry for `readuntil` is giving me second thoughts about this PR. In typeshed, it's written like this:
```python
    # Can be any buffer that supports len(); consider changing to a Protocol if PEP 688 is accepted
    async def readuntil(self, separator: bytes | bytearray | memoryview = b"\n") -> bytes: ...
```
On the other hand, in this PR the new use case is detected like this:
```python
        if isinstance(separator, bytes):
            separator = [separator]
        else:
            # Makes sure shortest matches wins, and supports arbitrary iterables
            separator = sorted(separator, key=len)
```

So I think this PR will actually break the existing use case of passing a bytearray (or memoryview), because it would be incorrectly interpreted as an iterable of separators rather than a single separator.

@gvanrossum any thoughts on how to better decide whether we've been passed a single separator or an iterable of them? Perhaps instead of `isinstance(separator, bytes)`, one could test `hasattr(separator, "__buffer__")`? Or would it be better to introduce a new parameter (or new method) to make the user tell us the intention instead of guessing?

**Comment by bmerry** [comment]
I've opened https://github.com/python/cpython/pull/117653 to use `collections.abc.Buffer` instead of `bytes` to decide the behaviour.

**Comment by bmerry** [comment]
> Well, _my_ intuition would be to only allow tuples -- this follows the lead of e.g. `str.startswith()`:

I can see the appeal in that. It's also consistent with `isinstance` which takes tuples and not lists.

If someone does pass a list, they're probably going to get a cryptic error message; so it would be nice if we could detect incorrect usage. So maybe if it's not a tuple AND it's not a collections.abc.Buffer, raise a helpful TypeError?

**Comment by bmerry** [comment]
I've created a patch to accept only tuples in #117723.

**Comment by bmerry** [comment]
> There's one detail in a different repo that you may want to get ahead of. There's a declaration for this method in typeshed; ideally we should update this conditionally with a check for `sys.version_info`.

I've opened https://github.com/python/typeshed/pull/11755
