### ISSUE TITLE
Pre-populate user editable text in input()

### ISSUE THREAD

**Issue by stevendaprano** [python/cpython#81342]
BPO | [37161](https://bugs.python.org/issue37161)
--- | :---
Nosy | @terryjreedy, @stevendaprano

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-05.10:40:49.846>
labels = ['type-feature', '3.9']
title = 'Pre-populate user editable text in input()'
updated_at = <Date 2019-06-07.22:51:52.833>
user = 'https://github.com/stevendaprano'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-07.22:51:52.833>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-06-05.10:40:49.846>
creator = 'steven.daprano'
dependencies = []
files = []
hgrepos = []
issue_num = 37161
keywords = []
message_count = 2.0
messages = ['344701', '345012']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'steven.daprano']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37161'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
I agree that this is probably too much to ask of the builtin input(). Marking as pending, and will close soon if there won't be objections (along with a plausible way forward).

**Comment by stevendaprano** [comment]
There is the option of making the feature dependent on readline, even if that makes it posix only, or even Linux only.

Its not like we don't have other platform-dependent features, and while this would leave Windows and IDLE as slightly second-class, it might also motivate people who understand those platforms better than I do to port the feature to them.

I think that this is a useful feature. Every GUI text input field allows the field to be pre-populated, it is a shame that text UIs don't, or at least not easily.

**Comment by terryjreedy** [comment]
Steven, rereading your initial post, I think you should instead propose adding editable_input() (with restoration of startup_hook) to the readline module.  input() doc could link to it.

**Comment by arhadthedev** [comment]
@stevendaprano ping?
