### ISSUE TITLE
Odd error awaiting a Future

### ISSUE THREAD

**Issue by 1e3445ee-1357-417d-a204-0863cf864f91** [python/cpython#81353]
BPO | [37172](https://bugs.python.org/issue37172)
--- | :---
Nosy | @asvetlov, @dimaqq, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-06.10:29:59.344>
labels = ['3.7', '3.8', '3.9', 'expert-asyncio']
title = 'Odd error awaiting a Future'
updated_at = <Date 2019-06-10.10:18:40.184>
user = 'https://github.com/dimaqq'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-10.10:18:40.184>
actor = 'Dima.Tisnek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-06-06.10:29:59.344>
creator = 'Dima.Tisnek'
dependencies = []
files = []
hgrepos = []
issue_num = 37172
keywords = []
message_count = 9.0
messages = ['344798', '344800', '345017', '345100', '345102', '345111', '345114', '345115', '345118']
nosy_count = 3.0
nosy_names = ['asvetlov', 'Dima.Tisnek', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37172'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
This is definitely one of the obscure edge cases with mixing global futures and different loop. I checked and this bug is only present in the C implementation so a bug in `_asynciomodule.c`.

**Comment by kumaraditya303** [comment]
Let's not spend more time on this, the easier way to avoid this is to just avoid using global futures which isn't recommended either.
