### ISSUE TITLE
asyncio.iscoroutinefunction(<async_generator>.asend) returns False

### ISSUE THREAD

**Issue by 852e7e29-09c9-46d3-8a38-cde0becf736a** [python/cpython#81371]
BPO | [37190](https://bugs.python.org/issue37190)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-07.08:57:50.425>
labels = ['type-bug', '3.7', 'expert-asyncio']
title = 'asyncio.iscoroutinefunction(<async_generator>.asend) returns False'
updated_at = <Date 2019-06-07.08:57:50.425>
user = 'https://bugs.python.org/RaduMateiLcraru'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-07.08:57:50.425>
actor = 'Radu Matei L\xc4\x83craru'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-06-07.08:57:50.425>
creator = 'Radu Matei L\xc4\x83craru'
dependencies = []
files = []
hgrepos = []
issue_num = 37190
keywords = []
message_count = 1.0
messages = ['344910']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'Radu Matei L\xc4\x83craru']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37190'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

### Linked PRs
* gh-102129

**Comment by kumaraditya303** [comment]
These functions are not coroutine functions but rather functions which return an awaitable object. You can use `inspect.isawaitable` on the result of `asend` to check if it is awaitable.

**Comment by graingert** [comment]
@kumaraditya303 they are functions that return coroutines - this is needed so `asyncio.create_task(agen.asend())` works
```
>>> import asyncio
>>> async def async_generator(): yield
... 
>>> asyncio.iscoroutine(async_generator().asend(None))
True
>>> 
```
so I think this needs re-opening

**Comment by kumaraditya303** [comment]
It is not a `coroutine` object but rather `async_generator_asend` object which has methods and some attributes of `coroutine` so behaves like it. `iscoroutinefunction` only works correctly for `async def` functions not native methods which returns an `awaitable` object hence I suggested to use `inspect.isawaitable`.

**Comment by graingert** [comment]
The bug here is with async_generator_asend/athrow
quoting @njsmith here:

> Conceptually the asend and athrow methods on async generators are just regular async functions, and if they were implemented that way they'd automatically raise the same "forgot to await" warnings that all async functions get. But because they're implemented directly in C, they don't get that infrastructure "for free"; it has to be added manually, and it's one of those minor fiddly details that's easy to miss when you're implementing something complicated like this.

now that `inspect.is*function` support duck-type functions it's possible for a built in function to implement all the needed features to pass the test

Currently async frameworks have specific hacks that require creating a prototypical async generator function and taking a copy of the built in asend/aclose types for inspection

**Comment by kumaraditya303** [comment]
> now that inspect.is*function support duck-type functions it's possible for a built in function to implement all the needed features to pass the test Currently async frameworks have specific hacks that require creating a prototypical async generator function and taking a copy of the built in asend/aclose types for inspection


So how do you propose to fix this? Can you create a PR for this to discuss?

**Comment by carljm** [comment]
There is now a canonical way to mark a function that is not actually defined with `async def` but is known to return an awaitable, such that `inspect.iscoroutinefunction` will return `True` for it: `inspect.markcoroutinefunction` (see https://github.com/python/cpython/pull/99247)

I think the mentioned methods of async generators should probably be marked in the same way, although that might be a bit tricky for methods implemented in C; it could involve some changes to the internal implementation details of `markcoroutinefunction`.

**Comment by wrongnull** [comment]
> There is now a canonical way to mark a function that is not actually defined with `async def` but is known to return an awaitable, such that `inspect.iscoroutinefunction` will return `True` for it: `inspect.markcoroutinefunction` (see #99247)
> 
> I think the mentioned methods of async generators should probably be marked in the same way, although that might be a bit tricky for methods implemented in C; it could involve some changes to the internal implementation details of `markcoroutinefunction`.

Well, I think current approach is not suitable either. It seems impossible to add attribute to builtin function without monkey patching. What if the only way is to change C implementation?

**Comment by wrongnull** [comment]
@kumaraditya303 Hi. Can you explain why aditional bifield in inderlying structures such as ```PyCFunctionObject``` isn't the way to fix this?

**Comment by kumaraditya303** [comment]
This will never work properly because in native code we cannot distinguish between a function and a coroutine, regarding adding flags that's just going to complicate things. These aren't the only methods which return coroutine like objects, there can be more in third party code. 

The proper way to workaround this is to use `inspect.isawaitable` as I indicated above.

**Comment by kumaraditya303** [comment]
I'm -1 on this, the users should use `inspect.isawaitable` which works in all cases.
