### ISSUE TITLE
Possible optimizations for math.comb()

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#81476]
BPO | [37295](https://bugs.python.org/issue37295)
--- | :---
Nosy | @tim-one, @rhettinger, @mdickinson, @serhiy-storchaka, @PedanticHacker, @mcognetta, @pochmann
PRs | <li>python/cpython#29020</li><li>python/cpython#29030</li><li>python/cpython#29090</li><li>python/cpython#30275</li><li>python/cpython#30305</li><li>python/cpython#30313</li>
Files | <li>[comb_with_primes.py](https://bugs.python.org/file50439/comb_with_primes.py "Uploaded as text/plain at 2021-11-15.04:27:26 by @pochmann")</li><li>[comb_with_side_limits.py](https://bugs.python.org/file50526/comb_with_side_limits.py "Uploaded as text/plain at 2021-12-29.18:41:09 by @rhettinger"): Compute limits for comb_small</li><li>[timecomb.py](https://bugs.python.org/file50530/timecomb.py "Uploaded as text/plain at 2021-12-30.19:38:10 by @mdickinson")</li><li>[driver.py](https://bugs.python.org/file50531/driver.py "Uploaded as text/plain at 2021-12-30.19:38:24 by @mdickinson")</li><li>[comb_pole.py](https://bugs.python.org/file50557/comb_pole.py "Uploaded as text/plain at 2022-01-12.05:03:37 by @rhettinger"): Experiment with precomputed diagonal -- runs on 3.8 or later</li><li>[comb_pole2.py](https://bugs.python.org/file50559/comb_pole2.py "Uploaded as text/plain at 2022-01-13.03:43:19 by @rhettinger"): Precomputed k diagonal and handling for small k</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-15.19:17:40.265>
labels = ['library', 'performance']
title = 'Possible optimizations for math.comb()'
updated_at = <Date 2022-01-23.22:42:15.922>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-23.22:42:15.922>
actor = 'tim.peters'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-06-15.19:17:40.265>
creator = 'rhettinger'
dependencies = []
files = ['50439', '50526', '50530', '50531', '50557', '50559']
hgrepos = []
issue_num = 37295
keywords = ['patch']
message_count = 73.0
messages = ['345711', '345731', '345761', '345784', '345876', '345952', '345956', '404184', '404208', '404429', '404472', '406300', '406337', '406338', '406341', '407736', '408867', '408952', '408954', '408962', '408970', '408984', '408989', '408994', '409000', '409001', '409002', '409010', '409024', '409028', '409062', '409095', '409110', '409116', '409154', '409254', '409268', '409269', '409270', '409274', '409277', '409298', '409315', '409317', '409320', '409321', '409331', '409346', '409360', '409373', '409376', '409377', '409382', '409383', '409393', '409417', '409432', '410145', '410339', '410347', '410382', '410383', '410387', '410420', '410448', '410460', '410543', '410587', '410925', '410931', '411343', '411427', '411430']
nosy_count = 7.0
nosy_names = ['tim.peters', 'rhettinger', 'mark.dickinson', 'serhiy.storchaka', 'PedanticHacker', 'mcognetta', 'Stefan Pochmann']
pr_nums = ['29020', '29030', '29090', '30275', '30305', '30313']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue37295'
versions = []
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Are we going to do something more in this issue? I think all the low-hanging fruit is already picked, and further optimizations are too expensive and only have a significant effect for very large numbers that are not used in practice (probably symbolic algebra or approximate calculations would be more useful in such cases).

I'm in awe of how much we've squeezed out of this issue.

**Comment by tim-one** [comment]
Ya, it's going on 2 years since any material comment was added, so closing this. We already pursued it to overkill 😆
