### ISSUE TITLE
isinstance/issubclass doc isn't clear on whether it's an AND or an OR.

### ISSUE THREAD

**Issue by fa5ec958-6532-42d7-99e4-e0654bdcb9f7** [python/cpython#81488]
BPO | [37307](https://bugs.python.org/issue37307)
--- | :---
Nosy | @leewz, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-16.11:59:07.376>
labels = ['3.8', 'type-feature', '3.7', '3.9', 'docs']
title = "isinstance/issubclass doc isn't clear on whether it's an AND or an OR."
updated_at = <Date 2019-06-21.18:57:28.345>
user = 'https://github.com/leewz'
```

bugs.python.org fields:
```python
activity = <Date 2019-06-21.18:57:28.345>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-06-16.11:59:07.376>
creator = 'leewz'
dependencies = []
files = []
hgrepos = []
issue_num = 37307
keywords = []
message_count = 7.0
messages = ['345744', '345747', '345748', '345749', '345750', '345751', '345752']
nosy_count = 4.0
nosy_names = ['SilentGhost', 'docs@python', 'leewz', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37307'
versions = ['Python 2.7', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by slateny** [comment]
@AlexWaygood Current docs:

[isinstance](https://docs.python.org/3/library/functions.html#isinstance) says


If classinfo is a tuple of type objects (or recursively, other such tuples) or a Union Type of multiple types, return True if object is an instance of any of the types.


[isclass](https://docs.python.org/3/library/functions.html#issubclass) says


classinfo may be a tuple of class objects or a Union Type, in which case return True if class is a subclass of any entry in classinfo.

So this looks resolved to me

**Comment by AlexWaygood** [comment]
Hmm @slateny, it looks like the `issubclass` docs still make no mention of the fact that you can pass a "recursive" tuple in (using the imprecise-but-admirably-terse phrasing used in `isinstance`:

```python
>>> issubclass(bool, (int, (str, (list, dict))))
True
```

**Comment by slateny** [comment]
That's a good point, I did just notice that [Union Types](https://docs.python.org/3/library/stdtypes.html#types-union) say they flatten so maybe it technically covers the recursive case, but I think it wouldn't be a bad idea at all to borrow the same wording from `isinstance`
