### ISSUE TITLE
collections: remove deprecated aliases to ABC classes

### ISSUE THREAD

**Issue by vstinner** [python/cpython#81505]
BPO | [37324](https://bugs.python.org/issue37324)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @yan12125, @hugovk, @tirkarthi
PRs | <li>python/cpython#14171</li><li>python/cpython#23754</li>
Superseder | <li>bpo-25988: collections.abc.Indexable</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-10-07.13:20:44.080>
created_at = <Date 2019-06-17.20:38:32.149>
labels = ['library', '3.9']
title = 'collections: remove deprecated aliases to ABC classes'
updated_at = <Date 2021-01-12.23:16:45.583>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-12.23:16:45.583>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2019-10-07.13:20:44.080>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2019-06-17.20:38:32.149>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 37324
keywords = ['patch']
message_count = 8.0
messages = ['345905', '345906', '345908', '345923', '348011', '348424', '354092', '384981']
nosy_count = 5.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'yan12125', 'hugovk', 'xtreak']
pr_nums = ['14171', '23754']
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '25988'
type = None
url = 'https://bugs.python.org/issue37324'
versions = ['Python 3.9']
```

</p></details>

**Comment by vivainio** [comment]
This broke setuptools 38.5.2

**Comment by hugovk** [comment]
setuptools [38.5.2 was released in 2018](https://pypi.org/project/setuptools/38.5.2/).

Python 3.10 was released on 2021-10-04, when setuptools was at [58.2.0](https://pypi.org/project/setuptools/58.2.0/), and is now at [65.5.1](https://pypi.org/project/setuptools/65.5.1/).

I recommend upgrading.

**Comment by vivainio** [comment]
@hugovk I was pinned to old version because newer setuptools created metadata that was incompatible with old version of Artifactory

**Comment by vstinner** [comment]
Well, if you start to pin versions, you should also pin the Python version: use Python 3.9 or older, which still provide deprecated aliases to collections ABC.

**Comment by vivainio** [comment]
@vstinner that's what we are doing, but we are now evaluating updating to python 3.10 and this (soft) blocker came up

**Comment by vivainio** [comment]
For posteriority, I packaged up the compatibility shims to a python package in pypi: https://github.com/vivainio/fix-py-collections

**Comment by vstinner** [comment]
> For posteriority, I packaged up the compatibility shims to a python package in pypi: https://github.com/vivainio/fix-py-collections

I proposed https://peps.python.org/pep-0606/ but it got rejected.

**Comment by vivainio** [comment]
> I proposed https://peps.python.org/pep-0606/ but it got rejected.

If there are a lot of breaking changes like this, maybe they could be addressed with a single "compat" package like six. I don't mind if it's a third party package, really.
