### ISSUE TITLE
Add a shutdown method to threading and asyncio Queue classes

### ISSUE THREAD

**Issue by 0feeca69-f794-43f6-b3ff-ff0ea3439fc0** [python/cpython#81515]
BPO | [37334](https://bugs.python.org/issue37334)
--- | :---
Nosy | @asvetlov, @cjrh, @1st1, @tecki, @eamanu
PRs | <li>python/cpython#14227</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-19.07:41:48.477>
labels = ['3.11', 'type-feature', 'expert-asyncio']
title = 'Add a cancel method to asyncio Queues'
updated_at = <Date 2021-05-12.12:06:13.863>
user = 'https://github.com/tecki'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-12.12:06:13.863>
actor = 'Martin.Teichmann'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-06-19.07:41:48.477>
creator = 'Martin.Teichmann'
dependencies = []
files = []
hgrepos = []
issue_num = 37334
keywords = ['patch']
message_count = 16.0
messages = ['346023', '346026', '346113', '346268', '346276', '346391', '357204', '357211', '357270', '357283', '357303', '357305', '357307', '357376', '357381', '393505']
nosy_count = 5.0
nosy_names = ['asvetlov', 'cjrh', 'yselivanov', 'Martin.Teichmann', 'eamanu']
pr_nums = ['14227']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37334'
versions = ['Python 3.11']
```

</p></details>

**Comment by gvanrossum** [comment]
I brought up something similar in https://discuss.python.org/t/queue-termination/18386/22. Looking at @tecki's PR GH-14227, I'm not sure that is what I was looking for. The proposed `close()` method stops both readers and writers immediately, abandoning items still in the queue. While that's probably the best we can do if the consumer decides to stop reading, it's not what I was looking for in that Discourse issue -- I want the producer(s) to be able to indicate they're not going to produce anything more, and let the consumers drain the queue.

Does anyone mind if I just close the PR as "not what is needed"? Note that the `shutdown()` I propose will still cause all following `put` calls to fail immediately, so it can also be used by the consumer to signal to the producers that it is done.

We need a new PR though, and an additional one for the regular thread-based `queue.Queue` class.

**Comment by kumaraditya303** [comment]
Superseded by https://github.com/python/cpython/issues/96471
