### ISSUE TITLE
octal escapes applied inconsistently throughout the interpreter and lib

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#81548]
BPO | [37367](https://bugs.python.org/issue37367)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @taleinat, @ezio-melotti, @serhiy-storchaka, @mr-nfamous, @websurfer5
PRs | <li>python/cpython#14654</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-21.19:46:08.946>
labels = ['expert-regex', 'easy', '3.9']
title = 'octal escapes applied inconsistently throughout the interpreter and lib'
updated_at = <Date 2019-11-20.09:14:13.360>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-20.09:14:13.360>
actor = 'taleinat'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2019-06-21.19:46:08.946>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 37367
keywords = ['patch', 'easy', 'easy (C)']
message_count = 9.0
messages = ['346246', '346865', '347261', '347411', '347516', '356817', '357026', '357031', '357041']
nosy_count = 8.0
nosy_names = ['gvanrossum', 'terry.reedy', 'taleinat', 'ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'bup', 'Jeffrey.Kintscher']
pr_nums = ['14654']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37367'
versions = ['Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
#91668 is an alternate PR which deprecates invalid octal sequences in bytes and string literals, in the same way as invalid escape sequences are deprecated.

**Comment by terryjreedy** [comment]
Given that the current code matches the doc, which says "As in Standard C, up to three octal digits are accepted." without qualification, it seems reasonable to treat this as a design bug (to be deprecated) rather than an implementation bug (to be immediately changed).  I think it definitely preferable to deprecate now, before the upcoming beta, and close #14654, than to do nothing before 3.12.
