### ISSUE TITLE
Improve conditional check for test_gdb

### ISSUE THREAD

**Issue by jdemeyer** [python/cpython#81563]
BPO | [37382](https://bugs.python.org/issue37382)
--- | :---
Nosy | @vstinner, @benjaminp, @jdemeyer, @stratakis
PRs | <li>python/cpython#14331</li><li>python/cpython#14395</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-24.08:31:13.482>
labels = ['type-feature', 'tests', '3.9']
title = 'Improve conditional check for test_gdb'
updated_at = <Date 2019-07-02.10:01:02.710>
user = 'https://github.com/jdemeyer'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-02.10:01:02.710>
actor = 'jdemeyer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2019-06-24.08:31:13.482>
creator = 'jdemeyer'
dependencies = []
files = []
hgrepos = []
issue_num = 37382
keywords = ['patch']
message_count = 15.0
messages = ['346358', '346359', '346600', '346601', '346608', '346609', '346612', '346619', '346624', '346625', '346627', '346630', '346633', '346711', '347125']
nosy_count = 4.0
nosy_names = ['vstinner', 'benjamin.peterson', 'jdemeyer', 'cstratak']
pr_nums = ['14331', '14395']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37382'
versions = ['Python 3.9']
```

</p></details>

**Comment by vstinner** [comment]
It's really hard to make test_gdb reliable. Nowadays, it seems like test_gdb *is* reliable, so I would prefer to not attempt to enable tests on optimized builds. So far, I only saw test_gdb to run reliably on Python built with `-O0`, which is the opposite of "optimized" binary.

I close the issue as "won't fix".
