### ISSUE TITLE
getpass.getpass not working with on windows when ctrl+v  is used to enter the string

### ISSUE THREAD

**Issue by 0e82d746-686d-4581-8ce3-e778432fd3a5** [python/cpython#81607]
BPO | [37426](https://bugs.python.org/issue37426)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @bhrutledge

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-27.09:49:37.372>
labels = ['3.11', 'type-bug', 'docs']
title = 'getpass.getpass not working with on windows when ctrl+v  is used to enter the string'
updated_at = <Date 2022-02-25.20:01:48.686>
user = 'https://bugs.python.org/AtulBagga'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-25.20:01:48.686>
actor = 'terry.reedy'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-06-27.09:49:37.372>
creator = 'Atul Bagga'
dependencies = []
files = []
hgrepos = []
issue_num = 37426
keywords = []
message_count = 8.0
messages = ['346721', '346727', '346867', '347126', '375819', '413993', '414012', '414024']
nosy_count = 9.0
nosy_names = ['paul.moore', 'tim.golden', 'docs@python', 'zach.ware', 'eryksun', 'steve.dower', 'Atul Bagga', 'brianhrutledge', 'W_M']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37426'
versions = ['Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
> > I have an idea to solve it. But I don't know how to get the
> > clipboard data.
> 
> In Windows, using the window manager entails extending the process and the current thread with GUI-related structures in the kernel and then connecting the process to a window station (usually "WinSta0", which contains the clipboard) and connecting the thread to a desktop (usually "Default"). This permanently changes how the OS sees the process. I think whether or not the process should be a GUI process is something for the application to decide, not the standard library. Thus getpass should not read text from the clipboard.
> 
> The docs could note that terminals may need to be configured to support Ctrl+Shift+C (copy) and Ctrl+Shift+V (paste) shortcuts, and that some terminals provide alternate ways to paste text, such as a right-click action or context menu. I don't think the docs should provide detailed explanations and configuration details for particular terminals.

Which doc do you suggest this be included in?  This comment would not be specific for getpass, right?

**Comment by zooba** [comment]
Windows Terminal is the default in Windows 11, so this won't be an issue forever.

The biggest problem with getpass is that it doesn't display anything when typing, so if you Ctrl+V in a console host that doesn't support it, you can't tell. Doing anything about that is its own set of problems, so I'd say _at most_ we could add a note that getpass users may need to warn _their_ users that they won't be able to see whether they've typed anything.

That's probably too much though. I think we're fine to just have this issue to attract concerns and point people towards the workarounds.

**Comment by taleinat** [comment]
IMO we shouldn't consider this a bug. When someone uses Ctrl+V (or other key combination) which doesn't normally trigger pasting in their terminal, there's no reason to expect that it would do so in a Python interpreter running in that terminal.

I suggest closing this.

**Comment by zooba** [comment]
Yeah, I think this discussion went off the core issue pretty quickly, but fundamentally Ctrl+V is not "paste" in these terminal hosts, so it's not going to paste anything.
