### ISSUE TITLE
[doc] range is not a built-in function

### ISSUE THREAD

**Issue by 2074ff9d-efa1-440c-be06-167758fca1de** [python/cpython#81611]
BPO | [37430](https://bugs.python.org/issue37430)
--- | :---
Nosy | @terryjreedy, @slateny

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-06-27.15:39:32.877>
labels = ['easy', 'type-bug', '3.9', '3.10', '3.11', 'docs']
title = '[doc] range is not a built-in function'
updated_at = <Date 2022-03-28.09:10:10.773>
user = 'https://bugs.python.org/bgailer'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-28.09:10:10.773>
actor = 'slateny'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-06-27.15:39:32.877>
creator = 'bgailer'
dependencies = []
files = []
hgrepos = []
issue_num = 37430
keywords = ['easy']
message_count = 5.0
messages = ['346745', '346753', '346784', '346887', '416153']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'bgailer', 'docs@python', 'slateny']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37430'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

### Linked PRs
* gh-98353
* gh-100704
* gh-100705

**Comment by terryjreedy** [comment]
Kumar, in my opinion, issues should not be closed until the backports are merged.

**Comment by kumaraditya303** [comment]
> Kumar, in my opinion, issues should not be closed until the backports are merged.

Yeah, I usually approve backports and close the issue but because of the CLA issues PRs were delayed this time.
