### ISSUE TITLE
IDLE error on closing 3.8+ debug build

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#81705]
BPO | [37524](https://bugs.python.org/issue37524)
--- | :---
Nosy | @terryjreedy, @taleinat, @ZackerySpytz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2019-07-09.09:20:18.515>
labels = ['expert-IDLE', 'type-bug', '3.8', '3.9']
title = 'IDLE error on closing 3.8+ debug build'
updated_at = <Date 2019-07-14.08:24:30.970>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-14.08:24:30.970>
actor = 'taleinat'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2019-07-09.09:20:18.515>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 37524
keywords = []
message_count = 8.0
messages = ['347530', '347531', '347611', '347665', '347745', '347746', '347747', '347883']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'taleinat', 'ZackerySpytz']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37524'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
Is this still an issue on main? From the issue, it seems that some function is called late during finalization so some modules are finalized.

**Comment by erlend-aasland** [comment]
I'm not able to reproduce this on Windows 10 at (`main` at bceb197947bbaebb11e01195bdce4f240fdf9332),neither using PowerShell nor using cmd.exe.

**Comment by terryjreedy** [comment]
The default repository build is now 64 bit instead of 32 bit.  If this only happens on 32-bit debug builds when one quits immediately, and possibly only on my Win 10 machine 3 years ago, I don't care.
