### ISSUE TITLE
Docs: Improve phrasing of flush argument for print()

### ISSUE THREAD

**Issue by aeros** [python/cpython#81762]
BPO | [37581](https://bugs.python.org/issue37581)
--- | :---
Nosy | @ezio-melotti, @merwok, @willingc, @JulienPalard, @aeros

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-13.06:42:51.715>
labels = ['3.8', 'type-feature', '3.7', '3.9', 'docs']
title = 'Docs: Improve phrasing of flush argument for print()'
updated_at = <Date 2019-07-13.06:44:11.573>
user = 'https://github.com/aeros'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-13.06:44:11.573>
actor = 'aeros'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-07-13.06:42:51.715>
creator = 'aeros'
dependencies = []
files = []
hgrepos = []
issue_num = 37581
keywords = []
message_count = 1.0
messages = ['347778']
nosy_count = 6.0
nosy_names = ['ezio.melotti', 'eric.araujo', 'docs@python', 'willingc', 'mdk', 'aeros']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37581'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-103264
* gh-103273
* gh-103274

**Comment by iritkatriel** [comment]
CC @CAM-Gerlach.

**Comment by CAM-Gerlach** [comment]
Thanks for the ping, @iritkatriel .

IMO, I prefer the fourth option. "Output buffering" is a more conventional term, and results in a more concise and easier to read first sentence. I also agree it's inconsistent that *file* is not referred to as a keyword argument here or on any other reference (nor are any of the other args), but *flush* is, which implies that there is something different about it (when of course there's not). Furthermore, it likewise makes the sentence shorter and easier to read.

Therefore, I've submitted a PR, #103264, to implement that.
