### ISSUE TITLE
support "UNC" device paths in ntpath.splitdrive

### ISSUE THREAD

**Issue by eryksun** [python/cpython#81790]
BPO | [37609](https://bugs.python.org/issue37609)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @serhiy-storchaka, @eryksun, @zooba, @nsiregar, @barneygale
PRs | <li>python/cpython#14841</li><li>python/cpython#25261</li><li>python/cpython#31702</li>
Files | <li>[splitdrive.py](https://bugs.python.org/file49541/splitdrive.py "Uploaded as text/plain at 2020-10-27.17:15:44 by @eryksun")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-17.11:26:34.050>
labels = ['type-bug', 'library', '3.10', 'OS-windows']
title = 'support "UNC" device paths in ntpath.splitdrive'
updated_at = <Date 2022-03-06.18:47:25.283>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-06.18:47:25.283>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2019-07-17.11:26:34.050>
creator = 'eryksun'
dependencies = []
files = ['49541']
hgrepos = []
issue_num = 37609
keywords = ['patch']
message_count = 9.0
messages = ['348055', '348099', '348206', '352110', '352355', '379780', '390375', '414604', '414621']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'serhiy.storchaka', 'eryksun', 'steve.dower', 'nsiregar', 'barneygale']
pr_nums = ['14841', '25261', '31702']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37609'
versions = ['Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
I have a patch for this issue here: https://github.com/python/cpython/pull/91882

Could a core dev please review? Thank you.
