### ISSUE TITLE
Line continuation of blank line emits NEWLINE

### ISSUE THREAD

**Issue by c84483fc-f2fe-459c-87b9-209cdb095547** [python/cpython#81802]
BPO | [37621](https://bugs.python.org/issue37621)
--- | :---
Nosy | @miedzinski
PRs | <li>python/cpython#14840</li>
Files | <li>[linecont.py](https://bugs.python.org/file48488/linecont.py "Uploaded as text/plain at 2019-07-18.14:13:50 by @miedzinski")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-18.14:13:50.484>
labels = ['interpreter-core', 'type-bug', '3.9']
title = 'Line continuation of blank line emits NEWLINE'
updated_at = <Date 2019-07-18.14:27:38.598>
user = 'https://github.com/miedzinski'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-18.14:27:38.598>
actor = 'miedzinski'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-07-18.14:13:50.484>
creator = 'miedzinski'
dependencies = []
files = ['48488']
hgrepos = []
issue_num = 37621
keywords = ['patch']
message_count = 1.0
messages = ['348117']
nosy_count = 1.0
nosy_names = ['miedzinski']
pr_nums = ['14840']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37621'
versions = ['Python 3.9']
```

</p></details>

**Comment by lysnikolaou** [comment]
This is no longer relevant after the changes to the tokenizer for PEP 701, so I'm closing it.
