### ISSUE TITLE
Investigate replacing SHA3 code with OpenSSL

### ISSUE THREAD

**Issue by tiran** [python/cpython#81811]
BPO | [37630](https://bugs.python.org/issue37630)
--- | :---
Nosy | @gpshead, @tiran, @stratakis, @miss-islington
PRs | <li>python/cpython#16049</li><li>python/cpython#20154</li><li>python/cpython#20986</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2019-07-19.11:30:56.450>
labels = ['extension-modules', 'type-bug', '3.9']
title = 'Investigate replacing SHA3 code with OpenSSL'
updated_at = <Date 2021-04-17.21:27:15.432>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-17.21:27:15.432>
actor = 'miss-islington'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2019-07-19.11:30:56.450>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 37630
keywords = ['patch']
message_count = 7.0
messages = ['348165', '369066', '369067', '369138', '369715', '369741', '391313']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'cstratak', 'miss-islington']
pr_nums = ['16049', '20154', '20986']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37630'
versions = ['Python 3.9']
```

</p></details>

**Comment by gpshead** [comment]
OpenSSL doesn't have to provide sha3.  LibreSSL noted above does not.  BoringSSL does not.  You can compile without it or disable it.  etc.

We've switched our built-in implementation used when OpenSSL does not offer it to use a verified HACL\* sha3 implementation instead of the 3.11 tiny_sha3 one which replaced the <=3.10 reference implementation sha3.
