### ISSUE TITLE
telnetlib crash in Python3 while receiving un-printable characters from server

### ISSUE THREAD

**Issue by 3dd4ee52-4cb9-481f-9706-9c15210b179e** [python/cpython#81821]
BPO | [37640](https://bugs.python.org/issue37640)
--- | :---
Nosy | @Sh3idan
PRs | <li>python/cpython#14877</li><li>python/cpython#22814</li>
Files | <li>[test.py](https://bugs.python.org/file48494/test.py "Uploaded as text/plain at 2019-07-21.09:17:07 by hoang nguyen")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-21.09:17:08.000>
labels = ['library', 'type-crash']
title = 'telnetlib crash in Python3 while receiving un-printable characters from server'
updated_at = <Date 2020-10-20.11:44:22.931>
user = 'https://bugs.python.org/hoangnguyen'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-20.11:44:22.931>
actor = 'shei dan'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-07-21.09:17:08.000>
creator = 'hoang nguyen'
dependencies = []
files = ['48494']
hgrepos = []
issue_num = 37640
keywords = ['patch']
message_count = 1.0
messages = ['348233']
nosy_count = 2.0
nosy_names = ['shei dan', 'hoang nguyen']
pr_nums = ['14877', '22814']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue37640'
versions = ['Python 3.6']
```

</p></details>

**Comment by hugovk** [comment]
Note the telnetlib module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by AlexWaygood** [comment]
> Note the telnetlib module is deprecated in 3.11 and set for removal in 3.13.
> 
> See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and #91217.

Since telnetlib no longer has a maintainer in the core dev team, I'm closing this issue (cc. @hoangnguyen, @Sh3idan)
