### ISSUE TITLE
In some cases asyncio.wait_for can lead to socket leak.

### ISSUE THREAD

**Issue by b8d01a80-0170-4a62-8b4a-fb7217384759** [python/cpython#81839]
BPO | [37658](https://bugs.python.org/issue37658)
--- | :---
Nosy | @ods, @asvetlov, @cjerdonek, @elprans, @ambv, @1st1, @miss-islington, @Dreamsorcerer, @aaliddell, @kumaraditya303
PRs | <li>python/cpython#21894</li><li>python/cpython#21964</li><li>python/cpython#21965</li><li>python/cpython#21969</li><li>python/cpython#26097</li><li>python/cpython#29202</li><li>python/cpython#29832</li><li>python/cpython#29831</li>
Files | <li>[example.py](https://bugs.python.org/file48500/example.py "Uploaded as text/plain at 2019-07-23.12:16:16 by Nikita Ilyasov"): script that can reproduce the problem</li><li>[ssl_circular_refs.png](https://bugs.python.org/file50061/ssl_circular_refs.png "Uploaded as image/png at 2021-05-24.13:02:10 by @ods")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-23.12:16:17.363>
labels = ['expert-asyncio', '3.7', 'performance']
title = 'In some cases asyncio.wait_for can lead to socket leak.'
updated_at = <Date 2022-03-11.17:35:41.865>
user = 'https://bugs.python.org/NikitaIlyasov'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-11.17:35:41.865>
actor = 'dreamsorcerer'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-07-23.12:16:17.363>
creator = 'Nikita Ilyasov'
dependencies = []
files = ['48500', '50061']
hgrepos = []
issue_num = 37658
keywords = ['patch']
message_count = 18.0
messages = ['348328', '348329', '375937', '375942', '375947', '379542', '393566', '393567', '393584', '393586', '393687', '394249', '404998', '407248', '407252', '407373', '414797', '414925']
nosy_count = 12.0
nosy_names = ['ods', 'asvetlov', 'chris.jerdonek', 'Elvis.Pranskevichus', 'lukasz.langa', 'yselivanov', 'miss-islington', 'Nikita Ilyasov', 'dreamsorcerer', 'aaliddell', 'nmatravolgyi', 'kumaraditya']
pr_nums = ['21894', '21964', '21965', '21969', '26097', '29202', '29832', '29831']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue37658'
versions = ['Python 3.6', 'Python 3.7']
```

</p></details>

**Comment by alittlesir** [comment]
any question about this issue? if not, i think it is better to close it

**Comment by gvanrossum** [comment]
Yes, see above:

> There is still an issue here. I proposed a possible solution at: https://github.com/python/cpython/pull/28149#issuecomment-1007823782
