### ISSUE TITLE
The results from os.path.isdir(...) an Path(...).is_dir() are not equivalent for empty path strings.

### ISSUE THREAD

**Issue by 0d38cd09-0b52-4764-9d98-dbf883bcdfc6** [python/cpython#81869]
BPO | [37688](https://bugs.python.org/issue37688)
--- | :---
Nosy | @brettcannon, @pitrou, @serhiy-storchaka, @godaygo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-07-26.07:23:57.873>
labels = ['type-feature', 'library', 'docs']
title = 'The results from os.path.isdir(...) an Path(...).is_dir() are not equivalent for empty path strings.'
updated_at = <Date 2019-07-29.18:50:44.722>
user = 'https://github.com/godaygo'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-29.18:50:44.722>
actor = 'brett.cannon'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2019-07-26.07:23:57.873>
creator = 'godaygo'
dependencies = []
files = []
hgrepos = []
issue_num = 37688
keywords = []
message_count = 8.0
messages = ['348475', '348477', '348478', '348482', '348495', '348497', '348528', '348679']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'pitrou', 'docs@python', 'serhiy.storchaka', 'godaygo']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue37688'
versions = []
```

</p></details>

**Comment by slateny** [comment]
For the [pathlib table](https://docs.python.org/3/library/pathlib.html#correspondence-to-tools-in-the-os-module), #23276 added a note stating that `Not all pairs of functions/methods below are equivalent.` so this does seem resolved, but maybe a different choice of wording would still be good (perhaps 'counterpart' would seem less strong than 'equivalence').

**Comment by brettcannon** [comment]
I'm going to close this as solved, but if someone wants to propose a PR with different wording then that's fine.
