### ISSUE TITLE
Tkinter: File names are hidden in "Open" menu (Linux)

### ISSUE THREAD

**Issue by aeros** [python/cpython#81874]
BPO | [37693](https://bugs.python.org/issue37693)
--- | :---
Nosy | @terryjreedy, @taleinat, @serhiy-storchaka, @aeros
Files | <li>[bpo-idle-open-menu-0.png](https://bugs.python.org/file48509/bpo-idle-open-menu-0.png "Uploaded as image/png at 2019-07-27.18:07:57 by @aeros")</li><li>[bpo-idle-open-menu-1.png](https://bugs.python.org/file48510/bpo-idle-open-menu-1.png "Uploaded as image/png at 2019-07-27.18:08:33 by @aeros")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-07-27.22:07:41.114>
created_at = <Date 2019-07-27.18:07:58.323>
labels = ['type-bug', 'expert-tkinter', '3.9']
title = 'Tkinter: File names are hidden in "Open" menu (Linux)'
updated_at = <Date 2019-07-27.23:32:45.101>
user = 'https://github.com/aeros'
```

bugs.python.org fields:
```python
activity = <Date 2019-07-27.23:32:45.101>
actor = 'aeros'
assignee = 'none'
closed = True
closed_date = <Date 2019-07-27.22:07:41.114>
closer = 'terry.reedy'
components = ['Tkinter']
creation = <Date 2019-07-27.18:07:58.323>
creator = 'aeros'
dependencies = []
files = ['48509', '48510']
hgrepos = []
issue_num = 37693
keywords = ['patch']
message_count = 8.0
messages = ['348554', '348555', '348557', '348559', '348562', '348564', '348567', '348568']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'taleinat', 'serhiy.storchaka', 'aeros']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37693'
versions = ['Python 3.9']
```

</p></details>

**Comment by stephematician** [comment]
I seem to be experiencing the same issue on UbuntuMATE, 22.04. Attached are screenshots from the following MWE:

```py
import tkinter as tki
from tkinter import filedialog, ttk

def browse_file(*args):
    filename = filedialog.askopenfilename(
        parent=root,
        title="Open",
        filetypes=[('YAML files', '*.yaml,*.yml')]
    )

root = tki.Tk()
root.option_add('*tearOff', False)
root.columnconfigure(0, weight=1)
root.rowconfigure(0, weight=1)

browse_button = ttk.Button(root,
                           text="Browse", default="active",
                           command=browse_file)
browse_button.grid(row=0, column=0, sticky=('n', 's', 'e', 'w'))

root.mainloop()
```

![image](https://github.com/python/cpython/assets/12695305/4fcd29f6-9050-427b-80c2-2dca9c45c800)

**Comment by stephematician** [comment]
I see the same results in IDLE, too. Is there anything else you need to know about my system to help troubleshoot the issue?

**Comment by stephematician** [comment]
Oh I believe this is a duplicate of #100584
