### ISSUE TITLE
thread native id support for GNU/Hurd

### ISSUE THREAD

**Issue by bb4fcc58-62ae-43e5-ad87-f6da76c3db92** [python/cpython#81925]
BPO | [37744](https://bugs.python.org/issue37744)
--- | :---
Nosy | @sthibaul
Files | <li>[hurd_thread_native_id.diff](https://bugs.python.org/file48526/hurd_thread_native_id.diff "Uploaded as text/plain at 2019-08-02.00:54:24 by @sthibaul"): patch</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-02.00:54:24.752>
labels = ['interpreter-core', '3.8']
title = 'thread native id support for GNU/Hurd'
updated_at = <Date 2019-08-02.00:54:24.752>
user = 'https://github.com/sthibaul'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-02.00:54:24.752>
actor = 'samuel-thibault'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-08-02.00:54:24.752>
creator = 'samuel-thibault'
dependencies = []
files = ['48526']
hgrepos = []
issue_num = 37744
keywords = ['patch']
message_count = 1.0
messages = ['348879']
nosy_count = 1.0
nosy_names = ['samuel-thibault']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37744'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-111761

**Comment by hugovk** [comment]
Closing as the PR has been merged. 

I see there was some post-merge discussion, I'll ping there in case someone wants to re-open this or create a new issue. Thanks for the report and PR!
