### ISSUE TITLE
create_pipe_connection and start_serving_pipe not documented

### ISSUE THREAD

**Issue by c79c9332-d210-40f7-9f06-d69e40b49e50** [python/cpython#81998]
BPO | [37817](https://bugs.python.org/issue37817)
--- | :---
Nosy | @asvetlov, @1st1, @primal100

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-11.02:12:15.585>
labels = ['3.7', '3.8', '3.9', 'expert-asyncio']
title = 'create_pipe_connection and start_serving_pipe not documented'
updated_at = <Date 2019-08-11.02:12:15.585>
user = 'https://github.com/primal100'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-11.02:12:15.585>
actor = 'primal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-08-11.02:12:15.585>
creator = 'primal'
dependencies = []
files = []
hgrepos = []
issue_num = 37817
keywords = []
message_count = 1.0
messages = ['349371']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'primal']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37817'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
Do you have a use case for it? Adding docs would make this a public API so would require adding tests for desired behavior. Currently the implementation can change if needed but if added as API, changing it would be harder.

**Comment by kumaraditya303** [comment]
I am closing this for now, please create an issue with concrete use-cases if want this to be added as public APIs. (Note that these APIs are exclusive to Windows.)

Additionally, if you want fast IPC on Windows I recommend to use aiohttp with named pipe connector which is more high level than this.
