### ISSUE TITLE
Initialize Py_buffer variables more efficiently

### ISSUE THREAD

**Issue by 9008ea77-dbea-496f-ba6b-b73570cfd4db** [python/cpython#82023]
BPO | [37842](https://bugs.python.org/issue37842)
--- | :---
Nosy | @larryhastings, @sir-sigurd
PRs | <li>python/cpython#15254</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-13.16:37:28.269>
labels = ['3.9', 'expert-argument-clinic', 'performance']
title = 'Initialize Py_buffer variables more efficiently'
updated_at = <Date 2019-08-13.16:38:30.746>
user = 'https://github.com/sir-sigurd'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-13.16:38:30.746>
actor = 'sir-sigurd'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2019-08-13.16:37:28.269>
creator = 'sir-sigurd'
dependencies = []
files = []
hgrepos = []
issue_num = 37842
keywords = ['patch']
message_count = 1.0
messages = ['349582']
nosy_count = 2.0
nosy_names = ['larry', 'sir-sigurd']
pr_nums = ['15254']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue37842'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
I'm not sure this is worth it; OTOH, the change is straight-forward. @serhiy-storchaka?

**Comment by erlend-aasland** [comment]
I took a look at the generated assembly, and the resulting code is definitely more compact. +1

**Comment by JelleZijlstra** [comment]
> but as I understand only `obj` and `buf` members are really had to be initialized. 

What makes you think that? What if a third-party extension using these functions that checks some other field before it is initialized?

**Comment by erlend-aasland** [comment]
Good point. Clinic is made for this code base, but it is also used externally.

**Comment by erlend-aasland** [comment]
OTOH, we can document the new behaviour in What's New. PEP-387 should probably apply to clinic.py, but in practise we've changed and removed clinic features without deprecation warnings before, IIRC.

**Comment by AlexWaygood** [comment]
The abstract [in these docs](https://docs.python.org/3/howto/clinic.html) says:

> Currently Argument Clinic is considered internal-only for CPython. Its use is not supported for files outside CPython, and no guarantees are made regarding backwards compatibility for future versions. In other words: if you maintain an external C extension for CPython, you’re welcome to experiment with Argument Clinic in your own code. But the version of Argument Clinic that ships with the next version of CPython could be totally incompatible and break all your code.

**Comment by serhiy-storchaka** [comment]
Some code only requires setting `obj` to NULL. Some code requires setting `len` to 0 if `buf` is NULL. For optional `Py_buffer` argument you need to set both `buf` and `len`. I have not read all code, but some code may require setting other fields as well. And if there is no such code in the current codebase, it may be added in future.

Therefore, I think that all fields of `Py_buffer` should be either explicitly initialized to NULL/0, or empty-initialized. The initializer can be `{NULL}`, `{NULL, NULL}`, `{NULL, NULL, 0}` -- all these forms are equivalent. Since C23 it can be simply `{}`, but I think that we will not use it until 2030th.

**Comment by erlend-aasland** [comment]
Thanks for chiming in everyone.

AFAICS, we can conclude with this:
For this particular change, we cannot rely on the assumptions in the OP, as explained by Serhiy. OTOH, if those assumptions were correct, we _could_ have made the change, as Alex pointed out.

Closing this issue and the linked PR.
