### ISSUE TITLE
Adding additional python installations to py launcher

### ISSUE THREAD

**Issue by 528b7167-38cf-4638-8b47-7db4755c858d** [python/cpython#82037]
BPO | [37856](https://bugs.python.org/issue37856)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-14.19:39:17.495>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'Adding additional python installations to py launcher'
updated_at = <Date 2019-08-14.19:39:17.495>
user = 'https://bugs.python.org/evanTO'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-14.19:39:17.495>
actor = 'evanTO'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-08-14.19:39:17.495>
creator = 'evanTO'
dependencies = []
files = []
hgrepos = []
issue_num = 37856
keywords = []
message_count = 1.0
messages = ['349740']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'evanTO']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37856'
versions = ['Python 3.7']
```

</p></details>

**Comment by zitterbewegung** [comment]
This hasn't been looked at seriously since 2019 and on many platforms (including Windows) you can manage different python versions in their own installer.

**Comment by zooba** [comment]
Agreed. If you want to add more Python installations, see PEP 514 (which as of a release or two ago is _fully_ supported by `py.exe`).
