### ISSUE TITLE
Add deploy preview for docs

### ISSUE THREAD

**Issue by ccbe4879-e54b-43e7-9c63-280a74d52875** [python/cpython#82041]
BPO | [37860](https://bugs.python.org/issue37860)
--- | :---
Nosy | @willingc, @ewdurbin, @Mariatta, @isidentical, @epicfaace, @aeros
PRs | <li>python/cpython#15288</li><li>python/cpython#18242</li><li>python/cpython#19025</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-14.21:14:46.493>
labels = ['3.9', 'docs']
title = 'Add deploy preview for docs'
updated_at = <Date 2021-03-22.01:23:26.366>
user = 'https://github.com/epicfaace'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-22.01:23:26.366>
actor = 'epicfaace'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-08-14.21:14:46.493>
creator = 'epicfaace'
dependencies = []
files = []
hgrepos = []
issue_num = 37860
keywords = ['patch']
message_count = 7.0
messages = ['349752', '350084', '364264', '364266', '364271', '368201', '389269']
nosy_count = 7.0
nosy_names = ['docs@python', 'willingc', 'EWDurbin', 'Mariatta', 'BTaskaya', 'epicfaace', 'aeros']
pr_nums = ['15288', '18242', '19025']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37860'
versions = ['Python 3.9']
```

</p></details>

**Comment by hugovk** [comment]
@epicfaace Hi again! Building on GitHub Actions and deploying to Netlify definitely sounds promising and definitely worth a try!

Like you say, we're already building the docs in our own workflow and so it would be good to see how long the upload takes.

**Comment by epicfaace** [comment]
test

**Comment by hugovk** [comment]
I looked into the Netlify action, but there's a blocker; it requires a Netlify personal access token / `NETLIFY_AUTH_TOKEN` as a secret:

https://github.com/nwtgck/actions-netlify#required-inputs-and-env

And GitHub doesn't make secrets available to PRs from forks, which unfortunately would limit us to uploads only for core devs _and_ only when they created a branch in this repo.

I guess we could hardcode the token without using secrets, but that doesn't sound like a great idea.

---

Another option, Read the Docs can now build previews for PRs:

https://docs.readthedocs.io/en/stable/pull-requests.html

We're using for PR previews in the PEPs repo, even though the main site is hosted elsewhere (on GitHub Pages).

For example:

* PR https://github.com/python/peps/pull/2578
* created a preview at https://pep-previews--2578.org.readthedocs.build/
* allowing that new PEP to be previewed at https://pep-previews--2578.org.readthedocs.build/pep-0691/

As a demo, I've set it up for my fork:

* https://readthedocs.org/projects/hugovk-cpython/builds/
* Demo PR: https://github.com/hugovk/cpython/pull/31
* Demo docs build: https://readthedocs.org/projects/hugovk-cpython/builds/16854291/
* Demo docs: https://hugovk-cpython--31.org.readthedocs.build/
* Demo changed page: https://hugovk-cpython--31.org.readthedocs.build/whatsnew/3.11.html

I would recommend naming it something like `cpython-docs-previews` to make it clear it's not the official docs home, similar to PEPs using `pep-previews`.

(See also https://github.com/python/docs-community/issues/5 for hosting the live docs on RTD, which is another but related matter. This could be a first step towards that.)

Thoughts on using RTD for PR previews?

**Comment by pradyunsg** [comment]
Why do you want to build on GitHub Actions? Netlify provides its own building compute (similar to RTD) and has an open source plan that CPython would qualify for: https://www.netlify.com/legal/open-source-policy/. The build is configured by specifying a build command https://docs.netlify.com/configure-builds/overview/?#basic-build-settings and a publish directory.

Netlify has deploy previews functionality baked into their offering: https://docs.netlify.com/site-deploys/deploy-previews/

**Comment by hugovk** [comment]
@pradyunsg See https://github.com/python/cpython/issues/82041#issuecomment-1093831790 and https://github.com/python/cpython/pull/15288#issuecomment-579476340: 

We have a Pro level open source plan on Netlify, but the limits of 1,000 build minutes per month likely aren't enough.

But wait!

That was in [January 2000](https://web.archive.org/web/20191225003810/https://www.netlify.com/pricing/) and it now looks like there's [25k minutes per month](https://www.netlify.com/pricing/)!

If the estimates in https://github.com/python/cpython/pull/15288#issuecomment-579476340 are still accurate, that would give us something like 4,250 builds per month.

There were [660 PRs created last month](https://github.com/python/cpython/pulls?q=is%3Apr+created%3A2022-04-01..2022-04-30%09), a few would have multiple builds (and some older PRs would have builds too), but I expect 4k builds should be plenty.
