### ISSUE TITLE
os.path.normpath change some characters of a path into kinda 'hex number'

### ISSUE THREAD

**Issue by 82d34eed-6bd2-4749-84bf-9986d430f4ea** [python/cpython#82120]
BPO | [37939](https://bugs.python.org/issue37939)
--- | :---
Nosy | @terryjreedy, @eryksun, @tirkarthi
Files | <li>[Screenshot from 2019-08-24 21-41-52.png](https://bugs.python.org/file48560/Screenshot%20from%202019-08-24%2021-41-52.png "Uploaded as image/png at 2019-08-24.14:54:52 by Yugi"): screenshot for system information and terminal output</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-08-30.20:51:23.981>
created_at = <Date 2019-08-24.14:54:52.475>
labels = ['type-bug']
title = "os.path.normpath change some characters of a path into kinda 'hex number'"
updated_at = <Date 2019-08-30.20:51:23.974>
user = 'https://bugs.python.org/Yugi'
```

bugs.python.org fields:
```python
activity = <Date 2019-08-30.20:51:23.974>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2019-08-30.20:51:23.981>
closer = 'terry.reedy'
components = []
creation = <Date 2019-08-24.14:54:52.475>
creator = 'Yugi'
dependencies = []
files = ['48560']
hgrepos = []
issue_num = 37939
keywords = []
message_count = 5.0
messages = ['350371', '350373', '350382', '350386', '350887']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'eryksun', 'xtreak', 'Yugi']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37939'
versions = ['Python 3.5']
```

</p></details>

**Comment by abrlake** [comment]
On Windows, Python treats backslashes as escape characters (`\t`, `\n`, etc.), 
so copying a path directly from Explorer can cause weird results like tabs showing up.  

You can either use a raw string like `r"D:\testfolder"` or normalize the path automatically.

If you want a one-liner that also cleans `../` and expands `~` for cross-platform use, 
you can try this tiny utility I wrote called [ipathy](https://pypi.org/project/ipathy/):

```python
from ipathy import ipathy
print(ipathy("D:\\testfolder"))
# → D:/testfolder
