### ISSUE TITLE
Wrong trace with multiple decorators (linenumber wrong in frame)

### ISSUE THREAD

**Issue by 83c24f9a-307d-4db0-b453-adbd45339217** [python/cpython#82152]
BPO | [37971](https://bugs.python.org/issue37971)
--- | :---
Nosy | @cfbolz, @nedbat, @ambv, @serhiy-storchaka, @jorants
PRs | <li>python/cpython#30027</li>
Files | <li>[decolinenumbers.patch](https://bugs.python.org/file48567/decolinenumbers.patch "Uploaded as text/plain at 2019-08-29.14:36:27 by @jorants")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-28.18:32:52.219>
labels = ['interpreter-core', 'type-bug', '3.8', '3.9']
title = 'Wrong trace with multiple decorators (linenumber wrong in frame)'
updated_at = <Date 2021-12-10.23:45:06.848>
user = 'https://github.com/jorants'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-10.23:45:06.848>
actor = 'lukasz.langa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-08-28.18:32:52.219>
creator = 'control-k'
dependencies = []
files = ['48567']
hgrepos = []
issue_num = 37971
keywords = ['patch']
message_count = 8.0
messages = ['350686', '350691', '350762', '350769', '350782', '350792', '408203', '408271']
nosy_count = 5.0
nosy_names = ['Carl.Friedrich.Bolz', 'nedbat', 'lukasz.langa', 'serhiy.storchaka', 'control-k']
pr_nums = ['30027']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue37971'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
@ambv did you want to backport this to 3.10 or can we close it?

**Comment by ambv** [comment]
Ah, I got stuck here on the conflicts between versions and discussing with Pablo it seemed they weren't trivial. Let me take one last look tomorrow, maybe I can still patch 3.10.
