### ISSUE TITLE
regression when passing numpy bools to sorted(..., reverse=r)

### ISSUE THREAD

**Issue by 81c94ca1-33c5-43a1-9206-327e323bc407** [python/cpython#82161]
BPO | [37980](https://bugs.python.org/issue37980)
--- | :---
Nosy | @tim-one, @rhettinger, @terryjreedy, @mdickinson, @vstinner, @serhiy-storchaka, @seberg, @tacaswell, @ammaraskar, @dopplershift
Files | <li>[numpy_warning_bisect.log](https://bugs.python.org/file48568/numpy_warning_bisect.log "Uploaded as text/x-log at 2019-08-29.16:39:02 by @tacaswell"): bisect log</li><li>[python_bisect.sh](https://bugs.python.org/file48569/python_bisect.sh "Uploaded as application/x-shellscript at 2019-08-29.16:40:21 by @tacaswell"): bisect script</li><li>[test.py](https://bugs.python.org/file48570/test.py "Uploaded as text/plain at 2019-08-29.16:41:06 by @tacaswell"): test script for bisecting</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-08-29.16:39:02.292>
labels = ['3.8', 'library', '3.9']
title = 'regression when passing numpy bools to sorted(..., reverse=r)'
updated_at = <Date 2020-08-26.00:13:06.810>
user = 'https://github.com/tacaswell'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-26.00:13:06.810>
actor = 'lizardlizard'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-08-29.16:39:02.292>
creator = 'tcaswell'
dependencies = []
files = ['48568', '48569', '48570']
hgrepos = []
issue_num = 37980
keywords = []
message_count = 13.0
messages = ['350800', '350803', '350806', '350844', '350845', '350857', '350858', '350860', '350868', '350873', '350877', '354449', '375901']
nosy_count = 12.0
nosy_names = ['tim.peters', 'rhettinger', 'terry.reedy', 'mark.dickinson', 'vstinner', 'serhiy.storchaka', 'seberg', 'ralf.gommers', 'tcaswell', 'ammar2', 'Ryan May', 'lizardlizard']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue37980'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Starting from 3.12, all functions in the stdlib that accept the boolean argument, now accept arbitrary values, not only bool or int, and use `__bool__` instead of `__index__`. So, the original issue has been resolved.
