### ISSUE TITLE
IO-like interface for SHAKE-* and other XOFs.

### ISSUE THREAD

**Issue by 92287feb-608f-432a-8317-733495aba300** [python/cpython#82198]
BPO | [38017](https://bugs.python.org/issue38017)
--- | :---
Nosy | @dannyniu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-03.12:48:26.011>
labels = ['type-feature', 'library']
title = 'IO-like interface for SHAKE-* and other XOFs.'
updated_at = <Date 2019-09-03.12:48:26.011>
user = 'https://github.com/dannyniu'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-03.12:48:26.011>
actor = 'dannyniu'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-09-03.12:48:26.011>
creator = 'dannyniu'
dependencies = []
files = []
hgrepos = []
issue_num = 38017
keywords = []
message_count = 1.0
messages = ['351084']
nosy_count = 1.0
nosy_names = ['dannyniu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue38017'
versions = []
```

</p></details>

**Comment by gpshead** [comment]
An API of this nature would make more sense to offer in a PyPI SHAKE specific package before we consider if such an API makes sense in the standard library.  We want `hashlib` to focus on the most common very widely used standard things.

**Comment by tomato42** [comment]
@gpshead any chance of having this re-evaluated? XOFs will be used in ML-KEM, it's hard for more standard use of that...

and while yes, you shouldn't use ML-KEM (kyber) implementation written in Python for production workloads, Python is the perfect language to teach how algorithms like that work

**Comment by gpshead** [comment]
This kind of development and maintenance is still best done in third party packages on PyPI.

**Comment by tomato42** [comment]
the problem is the effect of that on other implementations, like pypy; if it's part of core hashlib, then it needs to be provided by other runtimes, if it's a pypi package, then it may work on some random platform or it may not

**Comment by gpshead** [comment]
https://pypi.org/project/cryptography/ works on PyPy and is a more natural fit for this kind of thing today.

**Comment by tomato42** [comment]
just because it runs on PyPy doesn't mean it runs on all alternative runtimes, and just because pyca/cryptography provides the API doesn't mean that 

1. I can compile/run that binary package it in the first place
2. it actually compiles on some obscure architecture

you may not like it, but XOFs are part of the hash ecosystem now
