### ISSUE TITLE
FileIO.__init__ aborts when opener returns bad fd

### ISSUE THREAD

**Issue by a23bc0d5-ffdb-42d1-b9e0-05244b380ebc** [python/cpython#82212]
BPO | [38031](https://bugs.python.org/issue38031)
--- | :---
Nosy | @ZackerySpytz, @tekknolagi, @iritkatriel
PRs | <li>python/cpython#15688</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-04.21:19:41.772>
labels = ['interpreter-core', '3.9', 'expert-IO', '3.11', '3.10', 'type-crash']
title = 'FileIO.__init__ aborts when opener returns bad fd'
updated_at = <Date 2021-10-18.23:22:00.544>
user = 'https://github.com/tekknolagi'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-18.23:22:00.544>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core', 'IO']
creation = <Date 2019-09-04.21:19:41.772>
creator = 'tekknolagi'
dependencies = []
files = []
hgrepos = []
issue_num = 38031
keywords = ['patch']
message_count = 3.0
messages = ['351150', '351159', '404246']
nosy_count = 3.0
nosy_names = ['ZackerySpytz', 'tekknolagi', 'iritkatriel']
pr_nums = ['15688']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue38031'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by iritkatriel** [comment]
https://github.com/python/cpython/pull/99775 is a backport of this pull request to the [3.11 branch](https://github.com/python/cpython/tree/3.11).

https://github.com/python/cpython/pull/99776 is a backport of this pull request to the [3.10 branch](https://github.com/python/cpython/tree/3.10).
