### ISSUE TITLE
Simplify hashlib implementation

### ISSUE THREAD

**Issue by tiran** [python/cpython#82313]
BPO | [38132](https://bugs.python.org/issue38132)
--- | :---
Nosy | @gpshead, @tiran, @matrixise, @stratakis, @miss-islington
PRs | <li>python/cpython#16023</li><li>python/cpython#16040</li><li>python/cpython#16041</li><li>python/cpython#16048</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2019-09-12.10:44:02.780>
labels = ['extension-modules', 'type-feature', '3.8', '3.9']
title = 'Simplify hashlib implementation'
updated_at = <Date 2019-09-12.13:50:49.858>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-12.13:50:49.858>
actor = 'miss-islington'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2019-09-12.10:44:02.780>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 38132
keywords = ['patch']
message_count = 6.0
messages = ['352099', '352100', '352146', '352151', '352160', '352164']
nosy_count = 5.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'matrixise', 'cstratak', 'miss-islington']
pr_nums = ['16023', '16040', '16041', '16048']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue38132'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
AFAICS, all three suggested items was implemented by gh-16023:

- [x] The `EVPobject` name is now fetched from the `EVP_MD_CTX` on demand
- [x] The pre-generated static objects were removed from the extension module
- [x] The extension module was adapted to use Argument Clinic

Closing as completed.
