### ISSUE TITLE
add Py_ASSUME() macro for __builtin_unreachable()

### ISSUE THREAD

**Issue by 9008ea77-dbea-496f-ba6b-b73570cfd4db** [python/cpython#82328]
BPO | [38147](https://bugs.python.org/issue38147)
--- | :---
Nosy | @vstinner, @sir-sigurd
Files | <li>[disasm.txt](https://bugs.python.org/file48614/disasm.txt "Uploaded as text/plain at 2019-09-19.15:27:42 by @sir-sigurd")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-12.19:34:23.478>
labels = []
title = 'add Py_ASSUME() macro for __builtin_unreachable()'
updated_at = <Date 2019-09-23.14:57:12.562>
user = 'https://github.com/sir-sigurd'
```

bugs.python.org fields:
```python
activity = <Date 2019-09-23.14:57:12.562>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-09-12.19:34:23.478>
creator = 'sir-sigurd'
dependencies = []
files = ['48614']
hgrepos = []
issue_num = 38147
keywords = []
message_count = 6.0
messages = ['352228', '352792', '352793', '352800', '352803', '353027']
nosy_count = 2.0
nosy_names = ['vstinner', 'sir-sigurd']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38147'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
Closing as there is no consensus here, so this won't happen without a wider discussion on python-dev (following which this can be reopened).

**Comment by vstinner** [comment]
The C API has the Py_UNREACHABLE() macro which does basically implement requested feature:

> GCC (along with Clang and ICC) has __builtin_unreachable() and MSVC has __assume() builtins, that can be used to optimize out unreachable conditions.

Extract of the implementation:

```c
(...)
#elif defined(__GNUC__) && (__GNUC__ > 4 || (__GNUC__ == 4 && __GNUC_MINOR__ >= 5))
#  define Py_UNREACHABLE() __builtin_unreachable()
#elif defined(__clang__) || defined(__INTEL_COMPILER)
#  define Py_UNREACHABLE() __builtin_unreachable()
#elif defined(_MSC_VER)
#  define Py_UNREACHABLE() __assume(0)
#else
#  define Py_UNREACHABLE() \
    Py_FatalError("Unreachable C code path reached")
#endif
```
