### ISSUE TITLE
Meaning of tracebacklimit differs between sys.tracebacklimit and traceback module

### ISSUE THREAD

**Issue by 9719010a-7a6d-45ea-a4c0-9c1ede24d0ea** [python/cpython#82378]
BPO | [38197](https://bugs.python.org/issue38197)
--- | :---
Nosy | @cfbolz, @iritkatriel
Files | <li>[x.py](https://bugs.python.org/file48610/x.py "Uploaded as text/plain at 2019-09-17.10:34:54 by @cfbolz")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-17.10:34:55.146>
labels = ['3.8', '3.9', '3.10']
title = 'Meaning of tracebacklimit differs between sys.tracebacklimit and traceback module'
updated_at = <Date 2020-11-04.19:48:39.522>
user = 'https://github.com/cfbolz'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-04.19:48:39.522>
actor = 'Carl.Friedrich.Bolz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2019-09-17.10:34:55.146>
creator = 'Carl.Friedrich.Bolz'
dependencies = []
files = ['48610']
hgrepos = []
issue_num = 38197
keywords = []
message_count = 3.0
messages = ['352628', '380352', '380355']
nosy_count = 2.0
nosy_names = ['Carl.Friedrich.Bolz', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38197'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-122452
* gh-123062
* gh-123252
* gh-123286
* gh-123325
* gh-123326

**Comment by cfbolz** [comment]
This issue also becomes more relevant now, with pyrepl using `code`, which uses the `traceback` module. Here's a behaviour difference between cpy3.12 and cpy3.13 (current 3.13 branch):

```
cfbolz@triacontahedron:~/projects/cpython$ cat x.py 
def x1():
    1 / 0
def x2():
    x1()
def x3():
    x2()
cfbolz@triacontahedron:~/projects/cpython$ python3.12 -i x.py
>>> x3()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/cfbolz/projects/cpython/x.py", line 6, in x3
    x2()
  File "/home/cfbolz/projects/cpython/x.py", line 4, in x2
    x1()
  File "/home/cfbolz/projects/cpython/x.py", line 2, in x1
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
>>> import sys
>>> sys.tracebacklimit = 2
>>> x3()
Traceback (most recent call last):
  File "/home/cfbolz/projects/cpython/x.py", line 4, in x2
    x1()
  File "/home/cfbolz/projects/cpython/x.py", line 2, in x1
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
>>> 
cfbolz@triacontahedron:~/projects/cpython$ ./python -i x.py 
>>> x3()
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    x3()
    ~~^^
  File "/home/cfbolz/projects/cpython/x.py", line 6, in x3
    x2()
    ~~^^
  File "/home/cfbolz/projects/cpython/x.py", line 4, in x2
    x1()
    ~~^^
  File "/home/cfbolz/projects/cpython/x.py", line 2, in x1
    1 / 0
    ~~^~~
ZeroDivisionError: division by zero
>>> import sys
>>> sys.tracebacklimit = 2
>>> x3()
Traceback (most recent call last):
  File "<python-input-3>", line 1, in <module>
    x3()
    ~~^^
  File "/home/cfbolz/projects/cpython/x.py", line 6, in x3
    x2()
    ~~^^
ZeroDivisionError: division by zero
>>> 
```

note how on 3.12 the traceback is missing the frame for `x3` when `sys.tracebacklimit` is set, and 3.13 is missing the frame for `x1`.

I would still argue that `sys.tracebacklimit` has basically been broken since essentially forever in the `traceback` module. It might still be too late to fix this, of course, because people have come to rely on this undocumented behavior.

**Comment by iritkatriel** [comment]
> I would still argue that sys.tracebacklimit has basically been broken since essentially forever in the traceback module. It might still be too late to fix this, of course, because people have come to rely on this undocumented behavior.


Yes, we'd need to add a new limit and deprecate this one.

**Comment by cfbolz** [comment]
Ok, but that means we still have a very clear behavior change in the repl from 3.12 to 3.13 if some is setting `sys.tracebacklimit`

**Comment by iritkatriel** [comment]
CC @pablogsal @ambv re repl.

**Comment by cfbolz** [comment]
ah, I see that @pablogsal already had to work around this problem in `traceback.py` in https://github.com/python/cpython/commit/e7331365b488. It should be relatively easy to use this facility to `Lib/_pyrepl/console.py` in `InteractiveColoredConsole.showtraceback`, I think.

**Comment by pablogsal** [comment]
Ok, I think we are done with this one. Thanks @cfbolz for the PRs and @serhiy-storchaka for the reviews!

**Comment by cfbolz** [comment]
@pablogsal I kind of would like to still add a paragraph to the `traceback` module docs somewhere that mentions the differences between the meaning of `limit` in that module and the meaning of `sys.tracebacklimit`. I just don't quite know where in the [page](https://docs.python.org/3/library/traceback.html) to put it. Maybe simply in the text after `print_tb` where the meaning of `limit` is explained for the first time?

I'll re-open the issue to make sure I don't forget (or should I open a new one for the doc change?).

**Comment by pablogsal** [comment]
> or should I open a new one for the doc change?

No, we can reuse this one 👍 

> Maybe simply in the text after print_tb where the meaning of limit is explained for the first time?

I think that would be a good place. Alternatively we can add it at the start after the "The module defines the following functions:
" as a note
