### ISSUE TITLE
asyncio: MultiLoopWatcher has a race condition (test_asyncio: test_close_kill_running() hangs on AMD64 RHEL7 Refleaks 3.x)

### ISSUE THREAD

**Issue by vstinner** [python/cpython#82504]
BPO | [38323](https://bugs.python.org/issue38323)
--- | :---
Nosy | @vstinner, @njsmith, @asvetlov, @cjerdonek, @1st1, @jstasiak, @pablogsal, @miss-islington, @aeros, @Fidget-Spinner, @shreyanavigyan
PRs | <li>python/cpython#18457</li><li>python/cpython#20013</li><li>python/cpython#20142</li><li>python/cpython#22756</li><li>python/cpython#23806</li><li>python/cpython#23807</li><li>python/cpython#26536</li><li>python/cpython#26541</li><li>python/cpython#26542</li><li>python/cpython#26543</li><li>python/cpython#26544</li><li>python/cpython#26574</li><li>python/cpython#26632</li><li>python/cpython#26670</li>
Files | <li>[test-kill.py](https://bugs.python.org/file49144/test-kill.py "Uploaded as text/plain at 2020-05-09.10:42:10 by @cjerdonek")</li><li>[test-kill2.py](https://bugs.python.org/file49145/test-kill2.py "Uploaded as text/plain at 2020-05-09.11:24:50 by @cjerdonek")</li><li>[test-kill3.py](https://bugs.python.org/file49150/test-kill3.py "Uploaded as text/plain at 2020-05-12.02:45:46 by @cjerdonek")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-09-30.12:57:35.040>
labels = ['type-bug', 'tests', '3.9', 'expert-asyncio']
title = 'asyncio: MultiLoopWatcher has a race condition (test_asyncio: test_close_kill_running() hangs on AMD64 RHEL7 Refleaks 3.x)'
updated_at = <Date 2021-11-05.17:45:33.738>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-05.17:45:33.738>
actor = 'byllyfish'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests', 'asyncio']
creation = <Date 2019-09-30.12:57:35.040>
creator = 'vstinner'
dependencies = []
files = ['49144', '49145', '49150']
hgrepos = []
issue_num = 38323
keywords = ['patch']
message_count = 49.0
messages = ['353568', '354079', '355150', '355157', '355159', '355362', '355363', '359909', '359910', '359928', '360975', '361576', '361691', '361801', '368061', '368183', '368280', '368467', '368468', '368501', '368511', '368514', '368516', '368532', '368544', '368549', '368561', '368563', '368564', '368699', '368725', '369086', '380420', '383194', '383197', '383199', '395090', '395113', '395119', '395126', '395138', '395139', '395142', '395143', '395376', '395693', '395718', '396684', '405813']
nosy_count = 12.0
nosy_names = ['vstinner', 'njs', 'asvetlov', 'chris.jerdonek', 'yselivanov', 'jstasiak', 'pablogsal', 'miss-islington', 'aeros', 'kj', 'shreyanavigyan', 'byllyfish']
pr_nums = ['18457', '20013', '20142', '22756', '23806', '23807', '26536', '26541', '26542', '26543', '26544', '26574', '26632', '26670']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38323'
versions = ['Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
`MultiLoopWatcher` is deprecated now so closing as "won't fix".
