### ISSUE TITLE
Memory leak in ThreadPoolExecutor + run_in_executor

### ISSUE THREAD

**Issue by be485226-b708-4c83-8543-cc27adf477c1** [python/cpython#82611]
BPO | [38430](https://bugs.python.org/issue38430)
--- | :---
Nosy | @asvetlov, @1st1, @eamanu
PRs | <li>python/cpython#17038</li>
Files | <li>[python-leak.zip](https://bugs.python.org/file48654/python-leak.zip "Uploaded as application/zip at 2019-10-10.09:41:34 by Evgeny Nizhibitsky"): Minimal python script + dockerfile/makefile for reproducibility</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-10.09:41:34.118>
labels = ['expert-asyncio', '3.7', '3.9', 'performance']
title = 'Memory leak in ThreadPoolExecutor + run_in_executor'
updated_at = <Date 2019-11-05.01:20:32.415>
user = 'https://bugs.python.org/EvgenyNizhibitsky'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-05.01:20:32.415>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-10-10.09:41:34.118>
creator = 'Evgeny Nizhibitsky'
dependencies = []
files = ['48654']
hgrepos = []
issue_num = 38430
keywords = ['patch']
message_count = 14.0
messages = ['354351', '354352', '354353', '354354', '354355', '354356', '354357', '354358', '354360', '355835', '355836', '355843', '355864', '355882']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'eamanu', 'Evgeny Nizhibitsky']
pr_nums = ['17038']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue38430'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.9']
```

</p></details>

**Comment by ndvbd** [comment]
Any solutions? I'm having this too in python 2.7.18...

**Comment by vstinner** [comment]
> Any solutions? I'm having this too in python 2.7.18...

This issue is about asyncio which was added to Python 3.4. Moreover, Python 2.7 is no longer supported: you should upgrade to Python 3.11.
