### ISSUE TITLE
Possible new issues with IDLE

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#82621]
BPO | [38440](https://bugs.python.org/issue38440)
--- | :---
Nosy | @rhettinger, @terryjreedy, @taleinat, @ned-deily
Files | <li>[Screen Shot 2019-11-06 at 5.29.32 PM.png](https://bugs.python.org/file48699/Screen%20Shot%202019-11-06%20at%205.29.32%20PM.png "Uploaded as image/png at 2019-11-07.01:36:12 by @rhettinger"): Screen-shot of the frozen file dialog</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2019-10-11.04:27:28.799>
labels = ['expert-IDLE', '3.9']
title = 'Possible new issues with IDLE'
updated_at = <Date 2019-11-12.06:42:58.086>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-12.06:42:58.086>
actor = 'taleinat'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2019-10-11.04:27:28.799>
creator = 'rhettinger'
dependencies = []
files = ['48699']
hgrepos = []
issue_num = 38440
keywords = []
message_count = 17.0
messages = ['354418', '354423', '354426', '354433', '354565', '354984', '355424', '355435', '356161', '356163', '356165', '356172', '356174', '356175', '356176', '356177', '356416']
nosy_count = 5.0
nosy_names = ['rhettinger', 'terry.reedy', 'taleinat', 'wordtech', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38440'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
Is this still an issue? There has been no response to Tal's post. Marking this as pending close.

**Comment by terryjreedy** [comment]
There have been two bugs fixed as a result of these reports.  Other items seem not easily reproducible and should be new issues if they re-occur.
