### ISSUE TITLE
Reduce the time test_subprocess takes to complete.

### ISSUE THREAD

**Issue by gpshead** [python/cpython#82637]
BPO | [38456](https://bugs.python.org/issue38456)
--- | :---
Nosy | @gpshead, @vstinner, @pablogsal
PRs | <li>python/cpython#16736</li><li>python/cpython#16737</li><li>python/cpython#16739</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/gpshead'
closed_at = None
created_at = <Date 2019-10-12.21:27:44.358>
labels = ['tests', '3.9', 'performance']
title = 'Reduce the time test_subprocess takes to complete.'
updated_at = <Date 2020-10-20.17:33:23.874>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-20.17:33:23.874>
actor = 'gregory.p.smith'
assignee = 'gregory.p.smith'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2019-10-12.21:27:44.358>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 38456
keywords = ['patch']
message_count = 8.0
messages = ['354554', '354557', '354563', '354648', '354649', '354651', '379077', '379147']
nosy_count = 3.0
nosy_names = ['gregory.p.smith', 'vstinner', 'pablogsal']
pr_nums = ['16736', '16737', '16739']
priority = 'low'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue38456'
versions = ['Python 3.9']
```

</p></details>

**Comment by gpshead** [comment]
I'm done working on this for now. The timing techniques above are valid for any test though. If we sharded some of the work in our current longest tail tests today we should be able to pull it in for lower testsuite latency on 4+ core systems.

**Comment by vstinner** [comment]
Great!
