### ISSUE TITLE
Add assert_not_called_with

### ISSUE THREAD

**Issue by 0fd391c3-486f-44e6-a698-9d6ab1a14af8** [python/cpython#82675]
BPO | [38494](https://bugs.python.org/issue38494)
--- | :---
Nosy | @cjw296, @voidspace, @serhiy-storchaka, @phmc, @lisroach, @mariocj89, @tirkarthi, @valkheim

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2019-10-28.21:27:58.514>
created_at = <Date 2019-10-16.06:22:50.247>
labels = ['type-feature', '3.9']
title = 'Add assert_not_called_with'
updated_at = <Date 2019-10-28.21:27:58.513>
user = 'https://github.com/valkheim'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-28.21:27:58.513>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2019-10-28.21:27:58.514>
closer = 'serhiy.storchaka'
components = []
creation = <Date 2019-10-16.06:22:50.247>
creator = 'valkheim'
dependencies = []
files = []
hgrepos = []
issue_num = 38494
keywords = []
message_count = 3.0
messages = ['354770', '354811', '354814']
nosy_count = 8.0
nosy_names = ['cjw296', 'michael.foord', 'serhiy.storchaka', 'pconnell', 'lisroach', 'mariocj89', 'xtreak', 'valkheim']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue38494'
versions = ['Python 3.9']
```

</p></details>

**Comment by saoili** [comment]
Maybe I'm missing something, but I feel like 'Just define a function which raises an exception when it is called with the specified arguments' misses at least one use case. I'm not trying to check that my function won't ever be called with 'foobar', I'm just trying to check that in the context of the test as I've set it up, my function didn't get called with 'foobar'. I guess I can go in and check if 'foobar' is in the calls list, but couldn't the same argument be made against including 'assert_any_call' ?
