### ISSUE TITLE
bug of the v3.7 API document demo case code

### ISSUE THREAD

**Issue by a6575801-255a-4d48-a8f7-441255092b0f** [python/cpython#82693]
BPO | [38512](https://bugs.python.org/issue38512)
--- | :---
Nosy | @ezio-melotti, @stevendaprano
Files | <li>[2.png](https://bugs.python.org/file48668/2.png "Uploaded as image/png at 2019-10-18.09:33:13 by zr22122"): The bug position</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-18.09:33:13.833>
labels = ['expert-regex', '3.8']
title = 'bug of the v3.7 API document demo case code'
updated_at = <Date 2019-10-18.09:50:54.466>
user = 'https://bugs.python.org/zr22122'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-18.09:50:54.466>
actor = 'steven.daprano'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2019-10-18.09:33:13.833>
creator = 'zr22122'
dependencies = []
files = ['48668']
hgrepos = []
issue_num = 38512
keywords = []
message_count = 2.0
messages = ['354871', '354873']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'steven.daprano', 'zr22122']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38512'
versions = ['Python 3.8']
```

</p></details>

**Comment by ezio-melotti** [comment]
FWIW the screenshot seems to be of this section of the doc: https://docs.python.org/zh-cn/3/tutorial/inputoutput.html#formatted-string-literals
Since I don't see anything wrong with that example, I agree with closing this as invalid.
