### ISSUE TITLE
Misleading AttributeError accessing fileno attribute in tarfile

### ISSUE THREAD

**Issue by tirkarthi** [python/cpython#82753]
BPO | [38572](https://bugs.python.org/issue38572)
--- | :---
Nosy | @gustaebel, @PCManticore, @serhiy-storchaka, @ZackerySpytz, @tirkarthi
PRs | <li>python/cpython#17449</li><li>python/cpython#22178</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-24.06:55:32.301>
labels = ['type-bug', 'library', '3.9']
title = 'Misleading AttributeError accessing fileno attribute in tarfile'
updated_at = <Date 2020-09-09.20:27:43.778>
user = 'https://github.com/tirkarthi'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-09.20:27:43.778>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-10-24.06:55:32.301>
creator = 'xtreak'
dependencies = []
files = []
hgrepos = []
issue_num = 38572
keywords = ['patch']
message_count = 2.0
messages = ['355283', '357749']
nosy_count = 5.0
nosy_names = ['lars.gustaebel', 'Claudiu.Popa', 'serhiy.storchaka', 'ZackerySpytz', 'xtreak']
pr_nums = ['17449', '22178']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38572'
versions = ['Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
No other method of file-like object follows this pattern. If we want to change this, we should change it in every method that calls the corresponding method of the underlying stream. And not only for buffered files, but also for text files and for any other wrapper around a file object. And it does not work until we change absolute every proxy method in every class. Testing whether the underlying file has the fileno method before calling it to prevent raising an AttributeError does not help if the underlying file has such method, but calling it raises an AttributeError.

It is simpler to call the method and catch an AttributeError at the high level.
