### ISSUE TITLE
The activate script in Windows is not correct for venvs created in git-bash

### ISSUE THREAD

**Issue by 5968cd83-4a21-4d97-b6b1-5198ae21be48** [python/cpython#82764]
BPO | [38583](https://bugs.python.org/issue38583)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @mikofski

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-24.14:32:03.287>
labels = ['type-bug', '3.9', 'OS-windows']
title = 'The activate script in Windows is not correct for venvs created in git-bash'
updated_at = <Date 2020-04-15.05:32:32.233>
user = 'https://bugs.python.org/Mo'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-15.05:32:32.233>
actor = 'bwanamarko'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-10-24.14:32:03.287>
creator = 'Mo'
dependencies = []
files = []
hgrepos = []
issue_num = 38583
keywords = []
message_count = 5.0
messages = ['355333', '355356', '355382', '356146', '366488']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'bwanamarko', 'Mo']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38583'
versions = ['Python 3.9']
```

</p></details>

**Comment by avoidik** [comment]
probably this is the only option

```bash
VIRTUAL_ENV='C:\Users\xyz\Projects\abc\.venvwin'
if ([ "$OSTYPE" = "cygwin" ] || [ "$OSTYPE" = "msys" ]) && $(command -v cygpath &> /dev/null) ; then
    VIRTUAL_ENV=$(cygpath -u "$VIRTUAL_ENV")
fi
export VIRTUAL_ENV
```

**Comment by daytonb** [comment]
I was looking into a different issue with activate script from Windows' Python in a cygwin terminal and came across this Github issue. I have 3 pieces of feedback on this issue.

1. I tested the Windows Python 3.11 venv `activate` script from a git-bash terminal. Even though the output of  `which python` is very strange (`/c/Users/daytonb/Desktop/junk/\Users\daytonb\Desktop\junk\venv/Scripts/python`), the `pip` and `python` executables you get are the ones in the virtual environment. We can, therefore, probably close this issue with no code changes.

2. If we do want to address the contents of the environment variable and strange output of `which python`, then we could use the solution proposed by @avoidik above. It is precisely what's in the `activate` script written by virtualenv. I've confirmed that on my Win10 system, that works for activating a virtual environment in a git-bash terminal. If we merge that into Python's venv `activate` code, we could close this issue.

3. Finally, I concur with @mikofski's comment above, that we don't need to worry about being able to use the Windows' Python virtual environments from within a WSL terminal. I don't think WSL has any bearing on closing this issue.

**Comment by zware** [comment]
I'm pretty sure point 2 was addressed very recently in ebc81034278 (GH-103325, gh-103088), can you confirm?

**Comment by daytonb** [comment]
Indeed! That code change addresses my point 2. I think we can close this issue.

**Comment by rdbisme** [comment]
Any chance we might get this in a new release of Python 3.10?
