### ISSUE TITLE
re: backreference number in replace string can't >= 100

### ISSUE THREAD

**Issue by 9095315e-efb9-4932-a0c9-7a6e16ee043a** [python/cpython#82763]
BPO | [38582](https://bugs.python.org/issue38582)
--- | :---
Nosy | @ezio-melotti, @serhiy-storchaka, @animalize, @vedgar, @veaba
Files | <li>[QQ图片20191024195805.png](https://bugs.python.org/file48677/QQ%E5%9B%BE%E7%89%8720191024195805.png "Uploaded as image/png at 2019-10-24.12:00:59 by @veaba")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-24.12:01:00.200>
labels = ['expert-regex', '3.7', '3.8', '3.9']
title = "re: backreference number in replace string can't >= 100"
updated_at = <Date 2019-10-26.02:37:05.513>
user = 'https://github.com/veaba'
```

bugs.python.org fields:
```python
activity = <Date 2019-10-26.02:37:05.513>
actor = 'mrabarnett'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2019-10-24.12:01:00.200>
creator = 'veaba'
dependencies = []
files = ['48677']
hgrepos = ['384', '385']
issue_num = 38582
keywords = []
message_count = 16.0
messages = ['355328', '355330', '355332', '355343', '355346', '355350', '355352', '355354', '355355', '355357', '355358', '355359', '355398', '355399', '355400', '355401']
nosy_count = 6.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'serhiy.storchaka', 'malin', 'veky', 'veaba']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38582'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
I suggest to close this issue. The original report was caused by misunderstanding the documentation. The documentation already correctly describes the current behavior. It cannot be changed due to compatibility with existing Python code and with regular expressions in other implementations. It is de-facto standard.

If you need to refer more than 99 groups, use named groups.
