### ISSUE TITLE
[typing] PEP 563: Postponed evaluation of annotations: enable it by default in Python 3.11

### ISSUE THREAD

**Issue by vstinner** [python/cpython#82786]
BPO | [38605](https://bugs.python.org/issue38605)
--- | :---
Nosy | @gvanrossum, @warsaw, @brettcannon, @terryjreedy, @ericvsmith, @jwilk, @stevendaprano, @methane, @ambv, @serhiy-storchaka, @vedgar, @ilevkivskyi, @asottile, @pablogsal, @miss-islington, @isidentical, @gousaiyang, @AlexWaygood
PRs | <li>python/cpython#20434</li><li>python/cpython#22630</li><li>python/cpython#25236</li><li>python/cpython#25490</li><li>python/cpython#25596</li><li>python/cpython#25602</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-27.16:07:10.414>
labels = ['type-bug', '3.10', 'expert-unicode']
title = '[typing] PEP 563: Postponed evaluation of annotations: enable it by default in Python 3.11'
updated_at = <Date 2022-02-07.11:12:54.549>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-07.11:12:54.549>
actor = 'jwilk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Unicode']
creation = <Date 2019-10-27.16:07:10.414>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 38605
keywords = ['patch']
message_count = 40.0
messages = ['355476', '355495', '355506', '355523', '355546', '360830', '366634', '366635', '369269', '369301', '369303', '370000', '370020', '370028', '370031', '370035', '370037', '370188', '370214', '370220', '370232', '375177', '377783', '378133', '378134', '378135', '378139', '378374', '378416', '390399', '391512', '391515', '391700', '391732', '391755', '391869', '394114', '394115', '404129', '404130']
nosy_count = 18.0
nosy_names = ['gvanrossum', 'barry', 'brett.cannon', 'terry.reedy', 'eric.smith', 'jwilk', 'steven.daprano', 'methane', 'lukasz.langa', 'serhiy.storchaka', 'veky', 'levkivskyi', 'Anthony Sottile', 'pablogsal', 'miss-islington', 'BTaskaya', 'gousaiyang', 'AlexWaygood']
pr_nums = ['20434', '22630', '25236', '25490', '25596', '25602']
priority = 'normal'
resolution = 'postponed'
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38605'
versions = ['Python 3.10']
```

</p></details>

**Comment by Morteza43** [comment]
> BPO | [38605](https://bugs.python.org/issue38605)
> --- | :---
> Nosy | @gvanrossum, @warsaw, @brettcannon, @terryjreedy, @ericvsmith, @jwilk, @stevendaprano, @methane, @ambv, @serhiy-storchaka, @vedgar, @ilevkivskyi, @asottile, @pablogsal, @miss-islington, @isidentical, @gousaiyang, @AlexWaygood
> PRs | <li>python/cpython#20434</li><li>python/cpython#22630</li><li>python/cpython#25236</li><li>python/cpython#25490</li><li>python/cpython#25596</li><li>python/cpython#25602</li>
> 
> <sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>
> 
> <details><summary>Show more details</summary><p>
> 
> GitHub fields:
> ```python
> assignee = None
> closed_at = None
> created_at = <Date 2019-10-27.16:07:10.414>
> labels = ['type-bug', '3.10', 'expert-unicode']
> title = '[typing] PEP 563: Postponed evaluation of annotations: enable it by default in Python 3.11'
> updated_at = <Date 2022-02-07.11:12:54.549>
> user = 'https://github.com/vstinner'
> ```
> 
> bugs.python.org fields:
> ```python
> activity = <Date 2022-02-07.11:12:54.549>
> actor = 'jwilk'
> assignee = 'none'
> closed = False
> closed_date = None
> closer = None
> components = ['Unicode']
> creation = <Date 2019-10-27.16:07:10.414>
> creator = 'vstinner'
> dependencies = []
> files = []
> hgrepos = []
> issue_num = 38605
> keywords = ['patch']
> message_count = 40.0
> messages = ['355476', '355495', '355506', '355523', '355546', '360830', '366634', '366635', '369269', '369301', '369303', '370000', '370020', '370028', '370031', '370035', '370037', '370188', '370214', '370220', '370232', '375177', '377783', '378133', '378134', '378135', '378139', '378374', '378416', '390399', '391512', '391515', '391700', '391732', '391755', '391869', '394114', '394115', '404129', '404130']
> nosy_count = 18.0
> nosy_names = ['gvanrossum', 'barry', 'brett.cannon', 'terry.reedy', 'eric.smith', 'jwilk', 'steven.daprano', 'methane', 'lukasz.langa', 'serhiy.storchaka', 'veky', 'levkivskyi', 'Anthony Sottile', 'pablogsal', 'miss-islington', 'BTaskaya', 'gousaiyang', 'AlexWaygood']
> pr_nums = ['20434', '22630', '25236', '25490', '25596', '25602']
> priority = 'normal'
> resolution = 'postponed'
> stage = 'patch review'
> status = 'open'
> superseder = None
> type = 'behavior'
> url = 'https://bugs.python.org/issue38605'
> versions = ['Python 3.10']
> ```
> 
> </p></details>
> 

@morteza43

**Comment by vstinner** [comment]
There are now multiple PEPs proposed to handle this problem differently. 

> PEP 563: Postponed evaluation of annotations: enable it by default in Python 3.11

The SC asked to hold this for now. So I prefer to close the issue. Please open a new issue once the SC took a decision on this topic.
