### ISSUE TITLE
Issue with ctypes in AIX

### ISSUE THREAD

**Issue by 5296c072-3169-472d-82fb-fe1917725f84** [python/cpython#82809]
BPO | [38628](https://bugs.python.org/issue38628)
--- | :---
Nosy | @vsajip, @ronaldoussoren, @amauryfa, @abalkin, @meadori, @eryksun, @aixtools, @isidentical, @sanket, @trex58

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-29.09:17:23.348>
labels = ['ctypes', 'type-bug', '3.8', '3.9', '3.10']
title = 'Issue with ctypes in AIX'
updated_at = <Date 2020-08-16.16:30:56.589>
user = 'https://bugs.python.org/Ayappan'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-16.16:30:56.589>
actor = 'vinay.sajip'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2019-10-29.09:17:23.348>
creator = 'Ayappan'
dependencies = []
files = []
hgrepos = []
issue_num = 38628
keywords = []
message_count = 33.0
messages = ['355632', '356588', '361324', '361374', '361433', '374173', '374174', '374175', '374178', '374180', '374183', '374184', '374192', '374369', '374375', '374389', '374392', '374395', '374685', '374686', '374726', '374730', '374747', '374834', '374837', '374861', '374863', '375146', '375493', '375507', '375509', '375511', '375517']
nosy_count = 12.0
nosy_names = ['vinay.sajip', 'ronaldoussoren', 'amaury.forgeotdarc', 'belopolsky', 'meador.inge', 'eryksun', 'David.Edelsohn', 'Michael.Felt', 'Ayappan', 'BTaskaya', 'sanket', 'T.Rex']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38628'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
AIX is unsupported per PEP-11.

Without access to the OS it's hard to develop a fix and test it, but we *can* merge a PR with an AIX-specific `#ifdef`, if someone wants to file one and intends to keep it up to date.

I'll close the bug and PR.
Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back.
I encourage such people to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping. 


@edelsohn (I believe [this is you in the Experts index](https://devguide.python.org/core-developers/experts/#platforms)): do you still want to get notified about AIX issues in Python?

**Comment by edelsohn** [comment]
Continue to notify me.  Thanks.
