### ISSUE TITLE
ipaddress.ip_network('0.0.0.0/0').is_private == True

### ISSUE THREAD

**Issue by d9c2408f-3874-41e9-b247-de6cb654f947** [python/cpython#82836]
BPO | [38655](https://bugs.python.org/issue38655)
--- | :---
Nosy | @ammaraskar, @corona10, @JamoBox

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-10-31.14:04:51.585>
labels = ['3.7', 'type-bug', 'library']
title = "ipaddress.ip_network('0.0.0.0/0').is_private == True"
updated_at = <Date 2020-12-23.16:40:12.315>
user = 'https://bugs.python.org/pascalhofmann'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-23.16:40:12.315>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-10-31.14:04:51.585>
creator = 'pascalhofmann'
dependencies = []
files = []
hgrepos = []
issue_num = 38655
keywords = []
message_count = 6.0
messages = ['355753', '355998', '355999', '356007', '356044', '382990']
nosy_count = 5.0
nosy_names = ['ammar2', 'corona10', 'pascalhofmann', 'Wicken', 'maw1395']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38655'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-99887

**Comment by JamoBox** [comment]
@ammaraskar I've put in a pull request #97733 for this issue - it seems to fix the immediate problem reported by OP. 

The change of approach means we are asking "is the network itself private" rather than "are the network address and broadcast address of this network both in private ranges".

Are you able to give this a quick check to see if it's suitable?

**Comment by Rosuav** [comment]
I'm trying to follow your logic here, and I *think* what you're writing now is that, if this network's base and broadcast addresses are within **the same** private block, the entire network is private. If that's your logic, it may be clearer to write it as "if this network [is a subnet of](https://docs.python.org/3/library/ipaddress.html#ipaddress.IPv4Network.subnet_of) any of the private blocks, it is private", although I believe the resulting effect will be the same.

**Comment by hauntsaninja** [comment]
Thanks for fixing!
