### ISSUE TITLE
PyGILState_Release does not release gil correctly, resulting in deadlock

### ISSUE THREAD

**Issue by e016fcc9-f65a-41b5-b1c1-35ec9ace4f77** [python/cpython#82861]
BPO | [38680](https://bugs.python.org/issue38680)
--- | :---
Nosy | @ronaldoussoren
Files | <li>[interpreterlock.zip](https://bugs.python.org/file48728/interpreterlock.zip "Uploaded as application/zip at 2019-11-21.12:50:43 by Damien LEFEVRE")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-04.04:48:28.558>
labels = ['interpreter-core', '3.7']
title = 'PyGILState_Release does not release gil correctly, resulting in deadlock'
updated_at = <Date 2019-11-21.12:50:43.704>
user = 'https://bugs.python.org/123wlpha'
```

bugs.python.org fields:
```python
activity = <Date 2019-11-21.12:50:43.704>
actor = 'Damien LEFEVRE'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2019-11-04.04:48:28.558>
creator = '123 wlpha'
dependencies = []
files = ['48728']
hgrepos = []
issue_num = 38680
keywords = []
message_count = 9.0
messages = ['355921', '355922', '355943', '356011', '356012', '356018', '356059', '356961', '357165']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', '123 wlpha', 'Damien LEFEVRE']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38680'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
This bug is marked for 3.7 which is security fixes only now and the reproducer code is very large. Marking pending unless a smaller reproducer which can used on current main is provided.

**Comment by WilliamTambellini** [comment]
2 years later and similar issue now with python 3.12. 
Note: gstate is just an enum so worth to print to debug: eg:
```
  PyGILState_STATE gstate = PyGILState_Ensure();
  std::cout << std::this_thread::get_id() <<  " : current GIL state: " << gstate << std::endl;
```
