### ISSUE TITLE
32 bit ctypes stdcall callback fails to restore stack pointer

### ISSUE THREAD

**Issue by faa344fe-5758-4a85-83ed-1651b01ec956** [python/cpython#82929]
BPO | [38748](https://bugs.python.org/issue38748)
--- | :---
Nosy | @pfmoore, @tiran, @tjguk, @zware, @zooba, @michaeldcurran
PRs | <li>python/cpython#26204</li>
Files | <li>[py3.8crash.zip](https://bugs.python.org/file49959/py3.8crash.zip "Uploaded as application/x-zip-compressed at 2021-04-14.18:42:02 by @michaeldcurran"): Testcase</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-08.16:57:34.359>
labels = ['3.8', 'type-crash', '3.10', 'ctypes', 'OS-windows', '3.9']
title = '32 bit ctypes stdcall callback fails to restore stack pointer'
updated_at = <Date 2021-11-15.23:13:25.310>
user = 'https://bugs.python.org/DavidHeffernan'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-15.23:13:25.310>
actor = 'michaeldcurran'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows', 'ctypes']
creation = <Date 2019-11-08.16:57:34.359>
creator = 'David Heffernan'
dependencies = []
files = ['49959']
hgrepos = []
issue_num = 38748
keywords = ['patch']
message_count = 10.0
messages = ['356249', '357345', '391095', '391096', '391195', '391196', '391197', '391388', '406369', '406371']
nosy_count = 8.0
nosy_names = ['paul.moore', 'christian.heimes', 'tim.golden', 'python-dev', 'zach.ware', 'steve.dower', 'David Heffernan', 'michaeldcurran']
pr_nums = ['26204']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue38748'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by junkmd** [comment]
Perhaps this is the cause of the long unresolved problem with comtypes.

Please see enthought/comtypes#212.
The problem also occurs in Python 3.11.

Does anyone have knowledge/opinion on this?
Any opinions would be appreciated.

**Comment by davidheff** [comment]
I'm not very familiar with how bug resolution works in this project. What is the process by which this bug gets fixed?

**Comment by zooba** [comment]
It's basically described at https://devguide.python.org/getting-started/pull-request-lifecycle/ along with all the other information about contributing. You'll also find it linked from the "contributing guidelines" in this repo, which GitHub links prominently all over the place (e.g., immediately below this textbox).

**Comment by pfmoore** [comment]
> I was more wondering if anybody was likely to attempt to solve this.

Basically, what you're asking is whether anyone is likely to be motivated to put their time into looking into this problem and coming up with a fix. It's honestly impossible to answer that - most (if not all) contributions to Python are by volunteers who find a problem sufficiently interesting that they are motivated to dig into it, or by people directly affected by the issue. In this case it seems that the people impacted are not able to contribute a fix, so you're relying on "interested bystanders". Unfortunately, it's likely that people interested in low-level 32-bit Windows issues like this are few and far between, so you'll just need to be patient (or, I guess, find someone you can pay to do the investigation and develop a solution, but that's unlikely to be a realistic option in most cases).

**Comment by seanbudd** [comment]
This can probably closed as this has been fixed.
More discussion in https://github.com/python/cpython/pull/26204 https://github.com/python/cpython/issues/96965

**Comment by davidheff** [comment]
OK, this is a very happy surprise. I've just checked with my code that tripped over the original defect. It fails in 3.8-3.10, but works correctly in 3.11. So the issue does indeed seem to be fixed. Thanks for all involved in doing this.
