### ISSUE TITLE
Make Python compatible with OpenSSL 3.0.0

### ISSUE THREAD

**Issue by tiran** [python/cpython#83001]
BPO | [38820](https://bugs.python.org/issue38820)
--- | :---
Nosy | @tiran, @mcepl, @ambv, @stratakis, @hroncok, @miss-islington, @iritkatriel
PRs | <li>python/cpython#17190</li><li>python/cpython#17499</li><li>python/cpython#17500</li><li>python/cpython#25316</li><li>python/cpython#25319</li><li>python/cpython#25320</li><li>python/cpython#25321</li><li>python/cpython#25537</li><li>python/cpython#25624</li><li>python/cpython#25626</li><li>python/cpython#25627</li><li>python/cpython#25817</li><li>python/cpython#25942</li><li>python/cpython#25943</li><li>python/cpython#25944</li><li>python/cpython#26266</li><li>python/cpython#26269</li><li>python/cpython#26769</li><li>python/cpython#26799</li><li>python/cpython#28205</li><li>python/cpython#28216</li><li>python/cpython#28217</li>
Dependencies | <li>bpo-43788: OpenSSL 3.0.0: Make ssl_data.h version specific</li><li>bpo-43789: OpenSSL 3.0.0: password callback called multiple times</li><li>bpo-43791: OpenSSL 3.0.0: TLS 1.0 / 1.1 connections fail with TLSV1_ALERT_INTERNAL_ERROR</li><li>bpo-43794: OpenSSL 3.0.0: Handle UNEXPECTED_EOF_WHILE_READING / wrap SSL_OP_IGNORE_UNEXPECTED_EOF</li><li>bpo-43799: OpenSSL 3.0.0: define OPENSSL_API_COMPAT 1.1.1</li><li>bpo-43811: Run GHA CI with multiple OpenSSL versions</li><li>bpo-43920: OpenSSL 3.0.0: handle empty cadata consistently</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2019-11-16.15:06:59.538>
labels = ['expert-SSL', 'type-feature', '3.9', '3.10', '3.11']
title = 'Make Python compatible with OpenSSL 3.0.0'
updated_at = <Date 2021-09-08.17:05:14.504>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-08.17:05:14.504>
actor = 'lukasz.langa'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2019-11-16.15:06:59.538>
creator = 'christian.heimes'
dependencies = ['43788', '43789', '43791', '43794', '43799', '43811', '43920']
files = []
hgrepos = []
issue_num = 38820
keywords = ['patch']
message_count = 27.0
messages = ['356750', '356759', '357979', '357980', '357981', '378790', '378807', '390485', '390650', '390662', '390664', '390666', '391688', '391887', '391892', '391940', '392701', '393098', '394031', '396120', '396123', '397326', '401311', '401355', '401407', '401408', '401409']
nosy_count = 8.0
nosy_names = ['christian.heimes', 'mcepl', 'lukasz.langa', 'cstratak', 'hroncok', 'miss-islington', 'iritkatriel', 'bweeks']
pr_nums = ['17190', '17499', '17500', '25316', '25319', '25320', '25321', '25537', '25624', '25626', '25627', '25817', '25942', '25943', '25944', '26266', '26269', '26769', '26799', '28205', '28216', '28217']
priority = 'high'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue38820'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
I am closing this as it is fixed, if required it can reopened.
