### ISSUE TITLE
Links are duplicated in documentation search result

### ISSUE THREAD

**Issue by bf99f742-a7dd-4469-a2c9-884482a322fa** [python/cpython#83017]
BPO | [38836](https://bugs.python.org/issue38836)
--- | :---
Nosy | @JulienPalard, @MaT1g3R, @iritkatriel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-18.16:55:04.644>
labels = ['3.11', 'type-bug', '3.9', '3.10', 'docs']
title = 'Links are duplicated in documentation search result'
updated_at = <Date 2021-12-06.10:57:16.467>
user = 'https://github.com/MaT1g3R'
```

bugs.python.org fields:
```python
activity = <Date 2021-12-06.10:57:16.467>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2019-11-18.16:55:04.644>
creator = 'MaT1g3R'
dependencies = []
files = []
hgrepos = []
issue_num = 38836
keywords = []
message_count = 2.0
messages = ['356883', '407758']
nosy_count = 4.0
nosy_names = ['docs@python', 'mdk', 'MaT1g3R', 'iritkatriel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38836'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by slateny** [comment]
On the current dev branch, search has changed: https://docs.python.org/dev/search.html?q=os.walk shows `os.walk` for my first search result and a bunch (100+) of other search results with all or parts of 'os.walk'. This is for Windows though, so unsure if it was changed on Mac.

**Comment by JulienPalard** [comment]
On Firefox 105 on Linux it works as @slateny mentioned in the last comment: it shows os.walk once then a bunch of semi-related results.

It looks OK to me.
