### ISSUE TITLE
UDPLITE tests fail on android

### ISSUE THREAD

**Issue by 490c593f-f636-409f-bb35-6abeb38a4595** [python/cpython#83032]
BPO | [38851](https://bugs.python.org/issue38851)
--- | :---
Nosy | @asvetlov, @gappleto97
Files | <li>[test_socket.txt](https://bugs.python.org/file48722/test_socket.txt "Uploaded as text/plain at 2019-11-19.19:40:48 by @xdegaye")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-11-19.19:40:49.552>
labels = ['type-bug', 'tests', '3.9']
title = 'UDPLITE tests fail on android'
updated_at = <Date 2019-12-10.07:54:29.574>
user = 'https://github.com/xdegaye'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-10.07:54:29.574>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2019-11-19.19:40:49.552>
creator = 'xdegaye'
dependencies = []
files = ['48722']
hgrepos = []
issue_num = 38851
keywords = []
message_count = 3.0
messages = ['356985', '358167', '358171']
nosy_count = 2.0
nosy_names = ['asvetlov', 'gappleto97']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue38851'
versions = ['Python 3.9']
```

</p></details>

**Comment by mhsmith** [comment]
> Also, isn't this just a permissions error? I wouldn't think that would indicate a failure of the feature, but instead one of the testing environment.

Yes, this was probably caused by running the tests within an app which didn't have the [INTERNET permission](https://stackoverflow.com/q/2378607). With the permission present, I've confirmed that the UDPLITE tests all pass on the current main branch.

@encukou: So I think this issue can be closed.
