### ISSUE TITLE
using tkinter.filedialog.askopenfilename() freezes python 3.8

### ISSUE THREAD

**Issue by cc444d33-f642-419b-add6-ef10f3d9dfa9** [python/cpython#83155]
BPO | [38974](https://bugs.python.org/issue38974)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @zware, @serhiy-storchaka, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-04.19:44:42.051>
labels = ['3.8', 'expert-tkinter']
title = 'using tkinter.filedialog.askopenfilename() freezes python 3.8'
updated_at = <Date 2021-04-09.02:57:37.153>
user = 'https://bugs.python.org/DanielPreston'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-09.02:57:37.153>
actor = 'colin.caprani'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tkinter']
creation = <Date 2019-12-04.19:44:42.051>
creator = 'Daniel Preston'
dependencies = []
files = []
hgrepos = []
issue_num = 38974
keywords = []
message_count = 13.0
messages = ['357819', '357820', '357822', '357823', '357829', '357830', '357832', '357841', '357868', '357870', '357872', '357949', '390586']
nosy_count = 9.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'gpolo', 'zach.ware', 'serhiy.storchaka', 'steve.dower', 'Daniel Preston', 'colin.caprani']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue38974'
versions = ['Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
DanielPreston's code as posted had a syntax error.  colincaprani's code works for me as is and with call args removed.  Neither name is a github id.  There is very likely no cpython error in current versions and if there were, we are unlikely to get more info from either person.  Closing as there is nothing to do.

**Comment by serhiy-storchaka** [comment]
You can change the status of a closed issue as "closed as not planned" without reopening it. Just press a tiny arrow at the side of the "Reopen" button.
