### ISSUE TITLE
Wrong attachement filename when mail mime header was too long

### ISSUE THREAD

**Issue by e0b6f29b-33df-4e8c-9a42-6ff2ca9283d0** [python/cpython#83221]
BPO | [39040](https://bugs.python.org/issue39040)
--- | :---
Nosy | @warsaw, @bitdancer, @maxking, @miss-islington, @manfred-kaiser
PRs | <li>python/cpython#17590</li><li>python/cpython#17620</li><li>python/cpython#20504</li><li>python/cpython#20505</li><li>python/cpython#20506</li>
Files | <li>[testscript.py](https://bugs.python.org/file48775/testscript.py "Uploaded as text/plain at 2019-12-13.18:29:20 by @manfred-kaiser"): Script to read filenames</li><li>[error.eml](https://bugs.python.org/file48776/error.eml "Uploaded as message/rfc822 at 2019-12-13.18:34:12 by @manfred-kaiser"): Mail with broken filename</li><li>[original_mail_from_gmail.eml](https://bugs.python.org/file48777/original_mail_from_gmail.eml "Uploaded as message/rfc822 at 2019-12-13.18:52:06 by @manfred-kaiser"): downloaded mail from gmail (web interface). I only edited the the mail addresses for privacy reasons. Same problem with this mail</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-13.16:59:51.619>
labels = ['3.8', 'type-bug', '3.7', 'expert-email', '3.9']
title = 'Wrong attachement filename when mail mime header was too long'
updated_at = <Date 2020-05-29.11:43:51.599>
user = 'https://github.com/manfred-kaiser'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-29.11:43:51.599>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['email']
creation = <Date 2019-12-13.16:59:51.619>
creator = 'mkaiser'
dependencies = []
files = ['48775', '48776', '48777']
hgrepos = []
issue_num = 39040
keywords = ['patch']
message_count = 23.0
messages = ['358343', '358345', '358350', '358351', '358352', '358378', '358384', '358393', '358395', '358396', '358458', '358460', '358463', '358500', '358530', '358573', '358608', '358853', '358857', '370276', '370298', '370299', '370300']
nosy_count = 5.0
nosy_names = ['barry', 'r.david.murray', 'maxking', 'miss-islington', 'mkaiser']
pr_nums = ['17590', '17620', '20504', '20505', '20506']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39040'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by jikamens** [comment]
Strange that this hasn't been fixed when a fix was submitted literally years ago.

**Comment by bitdancer** [comment]
It looks like it was and the issue just wasn't closed.

**Comment by jikamens** [comment]
@bitdancer It does not appear to have been fixed. I just ran into it with python 3.10.4:

```
$ cat /tmp/testbug.py 
#!/usr/bin/env python3

import email

message = email.message_from_string("""\
MIME-Version: 1.0
Content-Type: text/plain; name="This File Name Is
 Folded.pdf"
Content-Disposition: attachment; filename="This File Name Is
 Folded.pdf"
Content-Transfer-Encoding: 8bit

Foo
""")

print(message.get_filename())
$ python3 /tmp/testbug.py
This File Name Is
 Folded.pdf
$ python -V
3.10.4
```

**Comment by bitdancer** [comment]
That's a different bug, and it is in the legacy API.  The new API handles it correctly:

```
rdmurray@pydev:~/cpython/master[master]>cat temp.py
#!/usr/bin/env python3

import email, email.policy

message = email.message_from_string("""\
MIME-Version: 1.0
Content-Type: text/plain; name="This File Name Is
 Folded.pdf"
Content-Disposition: attachment; filename="This File Name Is
 Folded.pdf"
Content-Transfer-Encoding: 8bit

Foo
""", policy=email.policy.default)

print(message.get_filename())
rdmurray@pydev:~/cpython/master[master]>./python temp.py
This File Name Is Folded.pdf
rdmurray@pydev:~/cpython/master[master]>./python -V
Python 3.12.0a0
rdmurray@pydev:~/cpython/master[master]>
```

I don't think this is worth trying to fix in the legacy api; the reason it happens there is probably a result of some deeply embedded assumptions in that code and may not be easy to fix.  (What would be worth fixing is making the new API truly be the default policy, but I don't currently have time to shepherd that process).
