### ISSUE TITLE
import error when in python -m pdb debug mode

### ISSUE THREAD

**Issue by 46f7bf45-3456-4809-a1a4-242cd6b000c2** [python/cpython#83233]
BPO | [39052](https://bugs.python.org/issue39052)
--- | :---
Nosy | @pfmoore, @tjguk, @xdegaye, @zware, @zooba
Files | <li>[myfilesort.py](https://bugs.python.org/file48778/myfilesort.py "Uploaded as text/plain at 2019-12-15.07:19:58 by chengyang")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-15.07:19:59.412>
labels = ['type-bug', '3.7', 'OS-windows']
title = 'import error when in python -m pdb debug mode'
updated_at = <Date 2019-12-21.13:27:10.934>
user = 'https://bugs.python.org/chengyang'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-21.13:27:10.934>
actor = 'xdegaye'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2019-12-15.07:19:59.412>
creator = 'chengyang'
dependencies = []
files = ['48778']
hgrepos = []
issue_num = 39052
keywords = []
message_count = 2.0
messages = ['358412', '358770']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'xdegaye', 'zach.ware', 'steve.dower', 'chengyang']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39052'
versions = ['Python 3.7']
```

</p></details>

**Comment by gaogaotiantian** [comment]
This is not a bug, there will be code executing when you do `import`. Stepping into an `import` statement makes sense. You can do `n` to go to next line. Please reopen the issue if you have more questions.
