### ISSUE TITLE
asyncio.Task.print_stack doesn't print the full stack

### ISSUE THREAD

**Issue by 3834ffcc-6e6a-4634-8c13-5644581fcae2** [python/cpython#83241]
BPO | [39060](https://bugs.python.org/issue39060)
--- | :---
Nosy | @terryjreedy, @asvetlov, @cjerdonek, @1st1, @amit7itz
Files | <li>[example.py](https://bugs.python.org/file48779/example.py "Uploaded as text/plain at 2019-12-16.09:51:58 by @amit7itz"): An example script that re-produces the bug.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-16.09:51:58.900>
labels = ['3.8', 'type-bug', '3.7', '3.9', 'expert-asyncio']
title = "asyncio.Task.print_stack doesn't print the full stack"
updated_at = <Date 2020-05-19.01:04:50.216>
user = 'https://github.com/amit7itz'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-19.01:04:50.216>
actor = 'chris.jerdonek'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2019-12-16.09:51:58.900>
creator = 'amit7itz'
dependencies = []
files = ['48779']
hgrepos = []
issue_num = 39060
keywords = []
message_count = 5.0
messages = ['358468', '358474', '358475', '358736', '358792']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'asvetlov', 'chris.jerdonek', 'yselivanov', 'amit7itz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39060'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/91048

`print_stack` cannot cross task boundaries and it is documented that it only ever returns the stack of wrapped coroutine.

**Comment by racinette** [comment]
Hey, I've found this legendary function on SO. It prints the stack up to the point where the task is stuck.

https://stackoverflow.com/questions/41748443/recipe-for-tracking-in-python-coroutines-the-chain-of-current-awaits-in-a-neat-w
