### ISSUE TITLE
[C API] No efficient C API to get UTF-8 string from unicode object.

### ISSUE THREAD

**Issue by methane** [python/cpython#83268]
BPO | [39087](https://bugs.python.org/issue39087)
--- | :---
Nosy | @vstinner, @methane, @serhiy-storchaka
PRs | <li>python/cpython#17659</li><li>python/cpython#17683</li><li>python/cpython#18327</li><li>python/cpython#18984</li><li>python/cpython#18985</li>
Files | <li>[bench-asutf8.patch](https://bugs.python.org/file48879/bench-asutf8.patch "Uploaded as text/plain at 2020-02-03.12:14:13 by @methane")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-03-14.06:59:47.614>
created_at = <Date 2019-12-18.12:10:15.464>
labels = ['expert-C-API', 'type-feature', '3.9']
title = '[C API] No efficient C API to get UTF-8 string from unicode object.'
updated_at = <Date 2020-03-14.11:00:07.223>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-14.11:00:07.223>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2020-03-14.06:59:47.614>
closer = 'methane'
components = ['C API']
creation = <Date 2019-12-18.12:10:15.464>
creator = 'methane'
dependencies = []
files = ['48879']
hgrepos = []
issue_num = 39087
keywords = ['patch']
message_count = 17.0
messages = ['358623', '358662', '358663', '358664', '358665', '358666', '358670', '358673', '358778', '358860', '361284', '361285', '362766', '364141', '364142', '364146', '364151']
nosy_count = 3.0
nosy_names = ['vstinner', 'methane', 'serhiy.storchaka']
pr_nums = ['17659', '17683', '18327', '18984', '18985']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39087'
versions = ['Python 3.9']
```

</p></details>

**Comment by cmaloney** [comment]
For the I/O stack I'd like a version of this accessible from Python as well as C. I've begun a Ideas discussion for adding: https://discuss.python.org/t/encode-str-utf-8-uncodeobject-without-a-copy/105572
