### ISSUE TITLE
Update IDLE's credits

### ISSUE THREAD

**Issue by taleinat** [python/cpython#83270]
BPO | [39089](https://bugs.python.org/issue39089)
--- | :---
Nosy | @terryjreedy, @taleinat

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2019-12-18.17:44:49.810>
labels = ['expert-IDLE', '3.7', '3.8', '3.9']
title = "Update IDLE's credits"
updated_at = <Date 2020-04-24.20:45:04.897>
user = 'https://github.com/taleinat'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-24.20:45:04.897>
actor = 'taleinat'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2019-12-18.17:44:49.810>
creator = 'taleinat'
dependencies = []
files = []
hgrepos = []
issue_num = 39089
keywords = []
message_count = 3.0
messages = ['358636', '365296', '367222']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'taleinat']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39089'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by terryjreedy** [comment]
Erlend's PR includes info above and add a generic 'look at logs' comment.  If/when I or someone decides someone else should be added, after looking through logs, a no-issue, no-blurb PR should be fine.

**Comment by erlend-aasland** [comment]
>  If/when I or someone decides someone else should be added, after looking through logs, a no-issue, no-blurb PR should be fine.

+1

Let's close this when the backport is merged.

**Comment by erlend-aasland** [comment]
Resolved by:

- gh-95528
- gh-95559
- gh-95560

**Comment by erlend-aasland** [comment]
> I linked the backport PR; this issue should close automatically when Pablo unlocks the 3.10 branch and that PR is merged.

Well, it didn't. I don't know why.

**Comment by terryjreedy** [comment]
The bots are not perfect.  This is why the issue should not be closed when the first PR is merged to main.
