### ISSUE TITLE
Increase Enum performance

### ISSUE THREAD

**Issue by ab737601-9646-4cd2-acb2-43630fe7c37a** [python/cpython#83283]
BPO | [39102](https://bugs.python.org/issue39102)
--- | :---
Nosy | @warsaw, @methane, @ethanfurman, @ilevkivskyi, @jack1142, @MrMrRobat
PRs | <li>python/cpython#17669</li>
Files | <li>[benchmark_result.txt](https://bugs.python.org/file48793/benchmark_result.txt "Uploaded as text/plain at 2019-12-20.02:48:28 by @MrMrRobat"): Benchmark-comparison</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ethanfurman'
closed_at = None
created_at = <Date 2019-12-20.02:48:28.850>
labels = ['library', '3.10', 'performance']
title = 'Increase Enum performance'
updated_at = <Date 2021-04-11.15:41:25.877>
user = 'https://github.com/MrMrRobat'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-11.15:41:25.877>
actor = 'ethan.furman'
assignee = 'ethan.furman'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2019-12-20.02:48:28.850>
creator = 'MrMrRobat'
dependencies = []
files = ['48793']
hgrepos = []
issue_num = 39102
keywords = ['patch']
message_count = 2.0
messages = ['358694', '358742']
nosy_count = 7.0
nosy_names = ['barry', 'eli.bendersky', 'methane', 'ethan.furman', 'levkivskyi', 'jack1142', 'MrMrRobat']
pr_nums = ['17669']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue39102'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
CC @mdboom .

**Comment by ethanfurman** [comment]
I believe this issue is no longer relevant as the ideas have been incorporated in other PRs; I'll double check at some point.
