### ISSUE TITLE
signing needs two serialisation passes

### ISSUE THREAD

**Issue by f83c3787-54fe-493a-ba35-bcc702f9558d** [python/cpython#83312]
BPO | [39131](https://bugs.python.org/issue39131)
--- | :---
Nosy | @warsaw, @bitdancer, @jap
PRs | <li>python/cpython#17695</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-24.15:24:15.641>
labels = ['3.8', 'expert-email', 'performance']
title = 'signing needs two serialisation passes'
updated_at = <Date 2019-12-24.17:53:24.675>
user = 'https://github.com/jap'
```

bugs.python.org fields:
```python
activity = <Date 2019-12-24.17:53:24.675>
actor = 'r.david.murray'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['email']
creation = <Date 2019-12-24.15:24:15.641>
creator = 'jap'
dependencies = []
files = []
hgrepos = []
issue_num = 39131
keywords = ['patch']
message_count = 2.0
messages = ['358849', '358851']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'jap']
pr_nums = ['17695']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue39131'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
@bitdancer Based on the comments on the PR, I believe the OP (@jap) has abandoned this. 

Shall I close the issue or do you think it is worth leaving it to be picked up by someone else?

**Comment by jap** [comment]
Note that we (@startmail) are using this patch in production. If someone were to tell me where to look on how to implement this by extending the content manager, I'd be all ears.

**Comment by iritkatriel** [comment]
Reopening because the OP has responded and asked for advice.

**Comment by iritkatriel** [comment]
@jap - that you're using the patch in prod is not really relevant here. If you want to try creating another patch along the lines of @bitdancer 's suggestion, please go ahead. I am leaving the pending label for now because I'm not sure from your comment whether you are planning to work on this. We try not to leave issues open forever when a project is abandoned.

**Comment by iritkatriel** [comment]
@jap - you can reopen this or create a new issue if you want to work on it, or if you have specific questions about how to implement it.

**Comment by jap** [comment]
Note that whether or not the community is willing to apply the provided patch, the original bug (signing needs two serialisation passes) is still not fixed.

**Comment by iritkatriel** [comment]
> Note that whether or not the community is willing to apply the provided patch, the original bug (signing needs two serialisation passes) is still not fixed.

Noted.

Patches often require some back and forth with code reviews and design discussions. If someone who cares about this issue would be willing to fix it follow through with this process, then it will be fixed.

**Comment by iritkatriel** [comment]
Also, I don't know why you're calling it a bug. There may be potential for a performance improvement but it's not a bug unless behaviour contradicts the documentation.
