### ISSUE TITLE
DatagramProtocol + IPv6 does not work with ProactorEventLoop

### ISSUE THREAD

**Issue by 1b708fa4-eb40-42d9-9dfe-9f0c3bf31a47** [python/cpython#83329]
BPO | [39148](https://bugs.python.org/issue39148)
--- | :---
Nosy | @pfmoore, @tjguk, @njsmith, @asvetlov, @agronholm, @zware, @1st1, @zooba, @aixtools, @miss-islington, @afflux
PRs | <li>python/cpython#19121</li><li>python/cpython#20169</li><li>python/cpython#20170</li>
Files | <li>[udpreceive.py](https://bugs.python.org/file48805/udpreceive.py "Uploaded as text/plain at 2019-12-28.10:55:11 by @agronholm"): Script to reproduce the error</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2019-12-28.10:55:11.585>
labels = ['type-bug', '3.8', '3.9', 'OS-windows', 'expert-asyncio']
title = 'DatagramProtocol + IPv6 does not work with ProactorEventLoop'
updated_at = <Date 2020-05-18.10:52:49.519>
user = 'https://github.com/agronholm'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-18.10:52:49.519>
actor = 'Michael.Felt'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows', 'asyncio']
creation = <Date 2019-12-28.10:55:11.585>
creator = 'alex.gronholm'
dependencies = []
files = ['48805']
hgrepos = []
issue_num = 39148
keywords = ['patch']
message_count = 20.0
messages = ['358940', '364803', '364807', '364837', '364841', '364842', '364861', '365813', '366934', '367096', '367098', '367174', '367177', '369107', '369185', '369186', '369187', '369192', '369193', '369205']
nosy_count = 12.0
nosy_names = ['paul.moore', 'tim.golden', 'njs', 'asvetlov', 'alex.gronholm', 'zach.ware', 'yselivanov', 'steve.dower', 'Michael.Felt', 'miss-islington', 'kbr', 'Marcin Wi\xc5\x9bniewsk']
pr_nums = ['19121', '20169', '20170']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39148'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by baseplate-admin** [comment]
Hi, is this issue fixed ?

I encountered this issue in Python 3.13.1.

There are also relevant discussions raised in:

- https://github.com/agronholm/anyio/discussions/872
- https://github.com/agronholm/anyio/discussions/793
