### ISSUE TITLE
Running the test suite with --junit-xml and -R incorrectly reports refleaks

### ISSUE THREAD

**Issue by pablogsal** [python/cpython#83434]
BPO | [39253](https://bugs.python.org/issue39253)
--- | :---
Nosy | @vstinner, @zooba, @pablogsal

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-07.23:54:53.841>
labels = ['tests', '3.9']
title = 'Running the test suite with --junit-xml and -R incorrectly reports refleaks'
updated_at = <Date 2020-01-08.17:31:56.794>
user = 'https://github.com/pablogsal'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-08.17:31:56.794>
actor = 'pablogsal'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2020-01-07.23:54:53.841>
creator = 'pablogsal'
dependencies = []
files = []
hgrepos = []
issue_num = 39253
keywords = []
message_count = 9.0
messages = ['359561', '359562', '359563', '359606', '359608', '359610', '359611', '359612', '359615']
nosy_count = 3.0
nosy_names = ['vstinner', 'steve.dower', 'pablogsal']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39253'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-117232
* gh-117250
* gh-117251

**Comment by furkanonder** [comment]
In versions 3.11, 3.12 and 3.13, the issue appears to still exist.

```python
./python -m test test_list -R: --junit-xml test-results.xml   
Using random seed: 1748800823
0:00:00 load avg: 1.61 Run 1 test sequentially
0:00:00 load avg: 1.61 [1/1] test_list
beginning 9 repetitions
123456789
.........
test_list leaked [826, 826, 826, 826] references, sum=3304
test_list leaked [357, 357, 357, 357] memory blocks, sum=1428
test_list failed (reference leak)

== Tests result: FAILURE ==

1 test failed:
    test_list

Total duration: 4.1 sec
Total tests: run=58
Total test files: run=1/1 failed=1
Result: FAILURE
```

**Comment by zooba** [comment]
Pull requests welcome. I think printing a warning that collecting XML results will cause false leaks is probably fine.

**Comment by vstinner** [comment]
The problem is that writing XML is done outside the code checking for refleaks, and creating the XML stores objects in memory. Pseudo-code:

```py
xml = XML()
for i in range(6):
    run_test(xml)  # add data to xml
    check_for_refleaks()
write_xml(xml)
```

Maybe a solution would be to write partial XML in run_test() and then cumulate results in a final XML. Pseudo-code:

```py
for i in range(6):
    run_test(temp_xml_filename=f"partial{i}.xml")  # write data to disk, not to memory
    check_for_refleaks()
create_xml([f"partial{i}.xml" for i in range(6)])
```

Or partial results can be Python objects written with pickle.

**Comment by zooba** [comment]
Disabling result collection during leak tests is probably best. I don't think we collect the number of leaked objects in the results, so why would you turn it on? By mistake.

**Comment by vstinner** [comment]
@zooba:
> Disabling result collection during leak tests is probably best.

Ok, I wrote PR gh-117232 for that.

**Comment by vstinner** [comment]
Fixed by change https://github.com/python/cpython/commit/d52bdfb19fadd7614a0e5abaf68525fc7300e841.
