### ISSUE TITLE
The CO_NESTED flag is associated with a significant performance cost

### ISSUE THREAD

**Issue by df79943f-4aee-4531-a00d-c6b12816eb70** [python/cpython#83462]
BPO | [39281](https://bugs.python.org/issue39281)
--- | :---
Nosy | @mr-nfamous

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-10.01:26:34.380>
labels = ['3.8', 'performance']
title = 'The CO_NESTED flag is associated with a significant performance cost'
updated_at = <Date 2020-01-10.01:26:34.380>
user = 'https://github.com/mr-nfamous'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-10.01:26:34.380>
actor = 'bup'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-01-10.01:26:34.380>
creator = 'bup'
dependencies = []
files = []
hgrepos = []
issue_num = 39281
keywords = []
message_count = 1.0
messages = ['359700']
nosy_count = 1.0
nosy_names = ['bup']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue39281'
versions = ['Python 3.8']
```

</p></details>

**Comment by gvanrossum** [comment]
It's about a class defined inside a function (slow) vs. a class defined in the top-level scope (fast). Since there are no timings in the bug report I am closing this as non-actionable.

**Comment by gvanrossum** [comment]
(Further investigation suggests this flag became obsolete some time between 3.6 and 3.10.)
