### ISSUE TITLE
Add test for imghdr cli

### ISSUE THREAD

**Issue by tirkarthi** [python/cpython#83504]
BPO | [39323](https://bugs.python.org/issue39323)
--- | :---
Nosy | @tirkarthi
PRs | <li>python/cpython#17993</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-13.16:42:19.027>
labels = ['3.7', '3.8', 'type-feature', 'tests', '3.9']
title = 'Add test for imghdr cli'
updated_at = <Date 2020-01-13.18:33:14.368>
user = 'https://github.com/tirkarthi'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-13.18:33:14.368>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2020-01-13.16:42:19.027>
creator = 'xtreak'
dependencies = []
files = []
hgrepos = []
issue_num = 39323
keywords = ['patch']
message_count = 1.0
messages = ['359919']
nosy_count = 1.0
nosy_names = ['xtreak']
pr_nums = ['17993']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39323'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by hugovk** [comment]
Note the imghdr modules is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by hugovk** [comment]
The PR has been closed (https://github.com/python/cpython/pull/17993#issuecomment-1094952903), let's close the issue too. Thanks!
