### ISSUE TITLE
zipfile with multiprocessing: zipfile.BadZipFile

### ISSUE THREAD

**Issue by 2d6496f2-5774-4658-b08c-76a517d98dba** [python/cpython#83544]
BPO | [39363](https://bugs.python.org/issue39363)
--- | :---
Files | <li>[test_filesource.py](https://bugs.python.org/file48847/test_filesource.py "Uploaded as text/plain at 2020-01-16.18:24:06 by maxime-lemonnier"): python script</li><li>[foo_bar_small.zip](https://bugs.python.org/file48848/foo_bar_small.zip "Uploaded as application/zip at 2020-01-16.18:24:25 by maxime-lemonnier")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-16.18:24:07.296>
labels = ['library', 'type-crash']
title = 'zipfile with multiprocessing: zipfile.BadZipFile'
updated_at = <Date 2020-01-16.18:32:16.359>
user = 'https://bugs.python.org/maxime-lemonnier'
```

bugs.python.org fields:
```python
activity = <Date 2020-01-16.18:32:16.359>
actor = 'maxime-lemonnier'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-01-16.18:24:07.296>
creator = 'maxime-lemonnier'
dependencies = []
files = ['48847', '48848']
hgrepos = []
issue_num = 39363
keywords = []
message_count = 2.0
messages = ['360134', '360135']
nosy_count = 1.0
nosy_names = ['maxime-lemonnier']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue39363'
versions = ['Python 3.6']
```

</p></details>

**Comment by gpshead** [comment]
It appears you are attempting to use the same already opened zipfile instance from multiple different processes at once. This won't even work with multiprocessing start methods other than "fork" as the other processes would not inherit the open file descriptors and the zipfile instance would fail to pickle/unpickle to go to the other process.

In the "fork"ing case, an existing zipfile instance already has an open file and is thus not safe for use from those processes as they'll all be attempting to use the same underlying inherited open file descriptor at once.

`zipfile` is not going to try to prevent this.

Recommendation: Open a new zipfile instance from within each of the processes.  parallel reading will work fine then as they no longer share any state.

Other recommendation: Do not use the "fork" multiprocessing start method.  use "forkserver" or "spawn".  you'll have far fewer problems.  (the default start method on posix systems will change to one of those in the future)
