### ISSUE TITLE
from __future__ import annotations makes dataclasses.Field.type a string, not type

### ISSUE THREAD

**Issue by e2c7191a-28c5-4168-9466-de462cbb815d** [python/cpython#83623]
BPO | [39442](https://bugs.python.org/issue39442)
--- | :---
Nosy | @ericvsmith, @methane, @drhagen, @lopekpl, @barisione, @ARF1, @davetapley

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-24.11:48:40.731>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'from __future__ import annotations makes dataclasses.Field.type a string, not type'
updated_at = <Date 2022-04-08.09:16:17.541>
user = 'https://github.com/lopekpl'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.09:16:17.541>
actor = 'barisione'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-01-24.11:48:40.731>
creator = 'lopek'
dependencies = []
files = []
hgrepos = []
issue_num = 39442
keywords = []
message_count = 13.0
messages = ['360611', '360613', '360617', '360628', '360640', '360641', '360760', '381398', '381399', '401549', '401558', '416963', '416965']
nosy_count = 8.0
nosy_names = ['eric.smith', 'methane', 'drhagen', 'lopek', 'barisione', 'ARF1', 'dcecile', 'davetapley']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39442'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by peku33** [comment]
Are there any plans for fixing this? The behavior described in documentation (`type: The type of the field.`) differs from actual returned type based on side effect outside of this module.

I understand there is a workaround using `get_type_hints`, but still this is a workaround and part of core library works not as expected.

**Comment by methane** [comment]
Do not use `from __future__ import annotations` of you want actual type object.
This option won't be default. So no plan to fix it.

PEP 649 will be accepted, but you can not use it for now.
