### ISSUE TITLE
Allow to deprecate CLI arguments in argparse

### ISSUE THREAD

**Issue by 6e840fc3-124e-4d24-9ed0-dcaf57ccd24e** [python/cpython#83648]
BPO | [39467](https://bugs.python.org/issue39467)
--- | :---
Nosy | @rhettinger, @serhiy-storchaka, @4383, @shihai1991
PRs | <li>python/cpython#18208</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-01-27.18:14:11.742>
labels = ['type-feature', 'library', '3.9']
title = 'Allow to deprecate CLI arguments in argparse'
updated_at = <Date 2020-03-03.12:57:11.058>
user = 'https://github.com/4383'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-03.12:57:11.058>
actor = '4383'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-01-27.18:14:11.742>
creator = '4383'
dependencies = []
files = []
hgrepos = []
issue_num = 39467
keywords = ['patch']
message_count = 6.0
messages = ['360786', '360827', '360861', '361155', '361158', '363256']
nosy_count = 6.0
nosy_names = ['rhettinger', 'djarb', 'paul.j3', 'serhiy.storchaka', '4383', 'shihai1991']
pr_nums = ['18208']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39467'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-114086
* gh-115640
* gh-121877
* gh-121878

**Comment by jugmac00** [comment]
Hey, just came here while looking for a way to deprecate an argparse argument.

The op claims there is currently no way... Is this true? Or is there a workaround?

**Comment by corneliusroemer** [comment]
Would be great to have a built-in way to deprecate args

**Comment by serhiy-storchaka** [comment]
Since there were no reaction to my comment, I created an alternate PR #114086 where implemented my ideas.

**Comment by serhiy-storchaka** [comment]
Now you can make the obtion, the positional argument or the command deprecated by passing `deprecate=Tru`. If this is not enough, this feature can be extended.
