### ISSUE TITLE
hmac.new() default parameter change not mentioned in changelog

### ISSUE THREAD

**Issue by 9a2648f4-76e6-4e53-bf3e-46a21e063d01** [python/cpython#83728]
BPO | [39547](https://bugs.python.org/issue39547)
--- | :---
Nosy | @wbond

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-03.22:59:34.267>
labels = ['3.8', 'docs']
title = 'hmac.new() default parameter change not mentioned in changelog'
updated_at = <Date 2020-02-03.22:59:34.267>
user = 'https://github.com/wbond'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-03.22:59:34.267>
actor = 'wbond'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-02-03.22:59:34.267>
creator = 'wbond'
dependencies = []
files = []
hgrepos = []
issue_num = 39547
keywords = []
message_count = 1.0
messages = ['361329']
nosy_count = 2.0
nosy_names = ['docs@python', 'wbond']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39547'
versions = ['Python 3.8']
```

</p></details>

**Comment by slateny** [comment]
The removal does seem mentioned under the [function section](https://docs.python.org/3/library/hmac.html#hmac.new), but I wonder if it should be also noted in the changelog

**Comment by tiran** [comment]
It's documented in the 3.4 changelog, https://docs.python.org/3/whatsnew/3.4.html#hmac

**Comment by tiran** [comment]
I would not object to add a note to the "porting to 3.8" section.
