### ISSUE TITLE
Pathlib PureWindowsPath sorting incorrect (is not natural sort)

### ISSUE THREAD

**Issue by 5e7416f3-1ce7-43ff-8bfd-a56106fbc083** [python/cpython#83725]
BPO | [39544](https://bugs.python.org/issue39544)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-03.17:53:35.345>
labels = ['type-bug', 'library', '3.9', 'OS-windows']
title = 'Pathlib PureWindowsPath sorting incorrect (is not natural sort)'
updated_at = <Date 2020-02-03.18:45:29.312>
user = 'https://bugs.python.org/tegavu'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-03.18:45:29.312>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2020-02-03.17:53:35.345>
creator = 'tegavu'
dependencies = []
files = []
hgrepos = []
issue_num = 39544
keywords = []
message_count = 2.0
messages = ['361315', '361320']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'tegavu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39544'
versions = ['Python 3.9']
```

</p></details>

**Comment by barneygale** [comment]
-1 on this from me. It's a breaking change and doesn't appear to have much utility. The behaviour of explorer isn't authorative, as Eryk notes.

**Comment by AlexWaygood** [comment]
> -1 on this from me. It's a breaking change and doesn't appear to have much utility. The behaviour of explorer isn't authorative, as Eryk notes.

Agreed. If you need a natural sort, it should also be trivial to implement it as a wrapper function.
