### ISSUE TITLE
Improve Keccak support in hashlib including KangarooTwelve

### ISSUE THREAD

**Issue by 267d5092-5b30-456c-a804-baef2aaa5204** [python/cpython#83720]
BPO | [39539](https://bugs.python.org/issue39539)
--- | :---
Nosy | @gpshead, @tiran, @Mariatta, @gvanas

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-03.10:25:05.173>
labels = ['type-feature', 'library', '3.9']
title = 'Improve Keccak support in hashlib including KangarooTwelve'
updated_at = <Date 2020-02-04.01:00:29.148>
user = 'https://github.com/gvanas'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-04.01:00:29.148>
actor = 'gregory.p.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-02-03.10:25:05.173>
creator = 'gvanas'
dependencies = []
files = []
hgrepos = []
issue_num = 39539
keywords = []
message_count = 3.0
messages = ['361280', '361331', '361333']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'Mariatta', 'gvanas']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39539'
versions = ['Python 3.9']
```

</p></details>

**Comment by gpshead** [comment]
We've simplified our sha3 fallback code when OpenSSL doesn't provide it to be tiny_sha3 in https://github.com/python/cpython/issues/91254.

Supporting things outside of the very standardized hashes realm is better left to PyPI packages. See also our BLAKE3 stdlib rejection https://github.com/python/cpython/issues/83479#issuecomment-1093850686.

But your point 1 mentions the https://csrc.nist.gov/publications/detail/sp/800-185/final sha3 keccak variant hashes. Are these widely used by any system that is not a cryptocurrency? In any standard protocols? If so, they may be worth considering for hashlib.

**Comment by gpshead** [comment]
FYI - Our built-in hashlib SHA3/Keccak support now comes from the HACL\* project when OpenSSL doesn't provide SHA3.

I'm closing this as there doesn't seem to be a compelling reason to add it vs a PyPI package for all of these special purpose less-common often non-standard variants.
