### ISSUE TITLE
brace escapes are not working in formatted string literal format specifications

### ISSUE THREAD

**Issue by a0f151b7-f5e3-4789-9cc8-8192d970bc91** [python/cpython#83782]
BPO | [39601](https://bugs.python.org/issue39601)
--- | :---
Nosy | @ericvsmith, @zware, @vedgar, @crwilcox
Files | <li>[bugreport.py](https://bugs.python.org/file48887/bugreport.py "Uploaded as text/plain at 2020-02-10.16:48:04 by jitterman"): an example that demonstrates the problem</li><li>[bugreport.py](https://bugs.python.org/file48888/bugreport.py "Uploaded as text/plain at 2020-02-10.16:50:35 by jitterman"): a hopefully simple example that demonstrates the problem</li><li>[test_case.patch](https://bugs.python.org/file48891/test_case.patch "Uploaded as text/plain at 2020-02-11.17:47:08 by @crwilcox"): test case that demonstrates the defect</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ericvsmith'
closed_at = None
created_at = <Date 2020-02-10.16:48:04.528>
labels = ['type-bug', '3.8']
title = 'brace escapes are not working in formatted string literal format specifications'
updated_at = <Date 2020-02-13.06:21:00.180>
user = 'https://bugs.python.org/jitterman'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-13.06:21:00.180>
actor = 'jitterman'
assignee = 'eric.smith'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-02-10.16:48:04.528>
creator = 'jitterman'
dependencies = []
files = ['48887', '48888', '48891']
hgrepos = []
issue_num = 39601
keywords = ['patch']
message_count = 13.0
messages = ['361702', '361703', '361704', '361707', '361751', '361774', '361787', '361826', '361832', '361834', '361835', '361933', '361937']
nosy_count = 5.0
nosy_names = ['eric.smith', 'zach.ware', 'veky', 'jitterman', 'crwilcox']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39601'
versions = ['Python 3.8']
```

</p></details>

**Comment by ericvsmith** [comment]
Since PEP 701 has completely changed the implementation of f-strings (in a good way!), I'm going to close this issue as either won't fix, or maybe works as designed. In trying to reproduce this with 3.12, I'm not sure what the desired behavior actually is. If this issue is still important to you, please show code that still doesn't do what you think it should, using 3.12.
