### ISSUE TITLE
Mention in docs that asyncio.FIRST_COMPLETED does not guarantee the completion of no more than one task

### ISSUE THREAD

**Issue by 570ec1ae-eaf2-4e65-a332-caa93a042338** [python/cpython#83852]
BPO | [39671](https://bugs.python.org/issue39671)
--- | :---
Nosy | @asvetlov, @embray, @1st1, @pohlt
PRs | <li>python/cpython#21918</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-18.09:33:32.173>
labels = ['type-feature', '3.8', 'docs', 'expert-asyncio']
title = 'Mention in docs that asyncio.FIRST_COMPLETED does not guarantee the completion of no more than one task'
updated_at = <Date 2020-08-31.09:58:41.124>
user = 'https://github.com/pohlt'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-31.09:58:41.124>
actor = 'erik.bray'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'asyncio']
creation = <Date 2020-02-18.09:33:32.173>
creator = 'tom.pohl'
dependencies = []
files = []
hgrepos = []
issue_num = 39671
keywords = ['patch']
message_count = 1.0
messages = ['362181']
nosy_count = 5.0
nosy_names = ['asvetlov', 'docs@python', 'erik.bray', 'yselivanov', 'tom.pohl']
pr_nums = ['21918']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39671'
versions = ['Python 3.8']
```

</p></details>

**Comment by mhauru** [comment]
Seconding this; I'm new to asyncio and spent hours being confused by this. Here's a minimal snippet where `return_when=FIRST_EXCEPTION` does not return when the first exception is encountered, but rather finishes all tasks.

```
import asyncio
import time


async def main():
    num_reps = 10

    async def generate():
        time.sleep(1)
        raise RuntimeError()

    tasks = [asyncio.create_task(generate()) for _ in range(num_reps)]
    done_tasks, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_EXCEPTION)
    print(f"Num done: {len(done_tasks)}, num pending: {len(pending)}")


asyncio.run(main())
```
This runs for ~10s and the last line prints `Num done: 10, num pending: 0`.

**Comment by willingc** [comment]
The documentation and semantics of `asyncio.wait` has evolved since this issue was opened. I'm going to close it but add a reference to it in the [asyncio tutorial issue](https://github.com/python/cpython/issues/79012) make sure there are good examples for `wait`.
