### ISSUE TITLE
functools: singledispatchmethod doesn't work with classmethod

### ISSUE THREAD

**Issue by 9450146a-b5d1-4897-b594-6702ef7a916e** [python/cpython#83860]
BPO | [39679](https://bugs.python.org/issue39679)
--- | :---
Nosy | @ncoghlan, @glyph, @ambv, @mgrandi, @ilevkivskyi, @miss-islington, @tirkarthi, @mental32, @vr2262, @FFY00, @EugenePY, @AlexWaygood
PRs | <li>python/cpython#29034</li><li>python/cpython#29072</li><li>python/cpython#29087</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-10-28.16:03:07.339>
created_at = <Date 2020-02-18.19:16:15.217>
labels = ['type-bug', 'library', '3.9']
title = "functools: singledispatchmethod doesn't work with classmethod"
updated_at = <Date 2021-10-28.16:03:07.338>
user = 'https://github.com/vr2262'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-28.16:03:07.338>
actor = 'lukasz.langa'
assignee = 'none'
closed = True
closed_date = <Date 2021-10-28.16:03:07.339>
closer = 'lukasz.langa'
components = ['Library (Lib)']
creation = <Date 2020-02-18.19:16:15.217>
creator = 'Viktor Roytman'
dependencies = []
files = []
hgrepos = []
issue_num = 39679
keywords = ['patch']
message_count = 15.0
messages = ['362233', '362253', '362434', '362442', '371230', '372405', '378344', '380221', '395910', '404147', '404348', '404362', '404363', '405195', '405196']
nosy_count = 13.0
nosy_names = ['ncoghlan', 'glyph', 'lukasz.langa', 'markgrandi', 'levkivskyi', 'miss-islington', 'xtreak', 'mental', 'Viktor Roytman', 'FFY00', 'EugenePY', 'dmkulazhenko', 'AlexWaygood']
pr_nums = ['29034', '29072', '29087']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39679'
versions = ['Python 3.9']
```

</p></details>

**Comment by P403n1x87** [comment]
Is there a reason why this was not backported to 3.8, when the documentation still says that decorators are supported?

**Comment by AlexWaygood** [comment]
> Is there a reason why this was not backported to 3.8, when the documentation still says that decorators are supported?

This was fixed in October 2021. Python 3.8 was old enough to enter "security-only" mode in May 2021. Python versions in security-only mode only have docs updates or bugfixes applied to them if the docs update or bugfix relates to a security issue. This bug didn't relate to a security issue.
