### ISSUE TITLE
pathlib.Path objects can be used as context managers

### ISSUE THREAD

**Issue by 4b0c5ead-8181-475a-af87-9342ce46c4e3** [python/cpython#83863]
BPO | [39682](https://bugs.python.org/issue39682)
--- | :---
Nosy | @brettcannon, @pitrou, @barneygale
PRs | <li>python/cpython#18846</li><li>python/cpython#30971</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-04-01.14:11:09.381>
created_at = <Date 2020-02-19.02:10:35.842>
labels = ['type-bug', 'library', '3.9']
title = 'pathlib.Path objects can be used as context managers'
updated_at = <Date 2022-01-27.23:22:28.820>
user = 'https://github.com/barneygale'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-27.23:22:28.820>
actor = 'barneygale'
assignee = 'none'
closed = True
closed_date = <Date 2020-04-01.14:11:09.381>
closer = 'pitrou'
components = ['Library (Lib)']
creation = <Date 2020-02-19.02:10:35.842>
creator = 'barneygale'
dependencies = []
files = []
hgrepos = []
issue_num = 39682
keywords = ['patch']
message_count = 14.0
messages = ['362244', '362840', '362934', '363206', '363209', '363218', '363260', '363261', '363285', '363298', '363383', '363468', '363469', '365473']
nosy_count = 4.0
nosy_names = ['brett.cannon', 'pitrou', 'Isaac Muse', 'barneygale']
pr_nums = ['18846', '30971']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39682'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-104807

**Comment by andrewshadura** [comment]
Oh well. I was actually using this functionality.
It was super convenient to do something like:
```python
with Path('debian') / 'fill.copyright.blanks.yml' as debian_copyright_overrides:
    if debian_copyright_overrides.is_file():
        ...
    else:
        ...
```
Basically it was a very visual way to structure code that worked with different subpaths. So no matter that it didn’t "close" path, it allowed to temporarily assign a shortcut to that path, do some work, and then forget about it.

**Comment by barneygale** [comment]
Perhaps [`contextlib.nullcontext()`](https://docs.python.org/3/library/contextlib.html#contextlib.nullcontext) would help?

But context managers are all about acquiring and releasing resources. It could be considered misleading to use a context manager only for code formating purposes. I would write:

```python
debian_copyright_overrides = Path('debian') / 'fill.copyright.blanks.yml'
if debian_copyright_overrides.is_file():
    ...
else:
    ...
```
