### ISSUE TITLE
Doc for `-X dev` option should mention PYTHONDEVMODE

### ISSUE THREAD

**Issue by pitrou** [python/cpython#83893]
BPO | [39712](https://bugs.python.org/issue39712)
--- | :---
Nosy | @pitrou, @vstinner, @ezio-melotti, @merwok, @willingc, @JulienPalard, @tirkarthi, @erlend-aasland, @rahul-kumi
PRs | <li>python/cpython#18685</li>
Files | <li>[0001-bpo-39712.patch](https://bugs.python.org/file48926/0001-bpo-39712.patch "Uploaded as text/plain at 2020-02-28.10:24:34 by @erlend-aasland")</li><li>[0001-3.8-bpo-39712.patch](https://bugs.python.org/file48927/0001-3.8-bpo-39712.patch "Uploaded as text/plain at 2020-02-28.10:24:45 by @erlend-aasland")</li><li>[0001-3.7-bpo-39712.patch](https://bugs.python.org/file48928/0001-3.7-bpo-39712.patch "Uploaded as text/plain at 2020-02-28.10:24:54 by @erlend-aasland")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-21.16:57:39.490>
labels = ['easy', '3.7', '3.8', '3.9', 'type-feature', 'docs']
title = 'Doc for `-X dev` option should mention PYTHONDEVMODE'
updated_at = <Date 2020-02-29.23:00:44.564>
user = 'https://github.com/pitrou'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-29.23:00:44.564>
actor = 'erlendaasland'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-02-21.16:57:39.490>
creator = 'pitrou'
dependencies = []
files = ['48926', '48927', '48928']
hgrepos = []
issue_num = 39712
keywords = ['patch', 'easy', 'newcomer friendly']
message_count = 4.0
messages = ['362414', '362525', '363025', '363030']
nosy_count = 10.0
nosy_names = ['pitrou', 'vstinner', 'ezio.melotti', 'eric.araujo', 'docs@python', 'willingc', 'mdk', 'xtreak', 'erlendaasland', 'rahul-kumi']
pr_nums = ['18685']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39712'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-103414
* gh-103467

**Comment by furkanonder** [comment]
@erlend-aasland I think we can close that issue.

**Comment by erlend-aasland** [comment]
> @erlend-aasland I think we can close that issue.

The issue mentioned by Antoined in the OP is not resolved yet :)

**Comment by furkanonder** [comment]
What does OP mean?

**Comment by furkanonder** [comment]
> > @erlend-aasland I think we can close that issue.
> 
> The issue mentioned by Antoine in the OP is not resolved yet :)

What does OP mean?

**Comment by erlend-aasland** [comment]
Sorry; Opening Post.

**Comment by merwok** [comment]
I improved help texts and cross-references in #100627 and #93219 but did not see this issue!
Will make a patch, or review one.
