### ISSUE TITLE
cgi.parse() fatally attempts str.decode when handling multipart/form-data

### ISSUE THREAD

**Issue by ae1baa81-36a8-475e-8203-d7a6c9ee6b29** [python/cpython#83908]
BPO | [39727](https://bugs.python.org/issue39727)
--- | :---
Nosy | @ethanfurman, @kxrob
Files | <li>[curlLogs.txt](https://bugs.python.org/file48902/curlLogs.txt "Uploaded as text/plain at 2020-02-23.05:34:16 by James Edington"): terminal transcript demonstrating bug</li><li>[demo.py](https://bugs.python.org/file48903/demo.py "Uploaded as text/plain at 2020-02-23.05:36:26 by James Edington"): demonstration file of the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-23.05:34:16.503>
labels = ['3.7', 'type-bug', 'library']
title = 'cgi.parse() fatally attempts str.decode when handling multipart/form-data'
updated_at = <Date 2020-09-03.13:42:42.523>
user = 'https://bugs.python.org/JamesEdington'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-03.13:42:42.523>
actor = 'kxrob'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-02-23.05:34:16.503>
creator = 'James Edington'
dependencies = []
files = ['48902', '48903']
hgrepos = []
issue_num = 39727
keywords = []
message_count = 3.0
messages = ['362490', '362491', '376299']
nosy_count = 3.0
nosy_names = ['ethan.furman', 'James Edington', 'kxrob']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39727'
versions = ['Python 3.7']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/) and further no improvements or bug fixes will be made to the module.
