### ISSUE TITLE
Argument Clinic name conflict

### ISSUE THREAD

**Issue by isidentical** [python/cpython#83922]
BPO | [39741](https://bugs.python.org/issue39741)
--- | :---
Nosy | @larryhastings, @pablogsal, @isidentical

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-24.17:30:10.453>
labels = ['type-feature', 'expert-argument-clinic', '3.9']
title = 'Argument Clinic name conflict'
updated_at = <Date 2020-02-24.20:07:45.911>
user = 'https://github.com/isidentical'
```

bugs.python.org fields:
```python
activity = <Date 2020-02-24.20:07:45.911>
actor = 'BTaskaya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Argument Clinic']
creation = <Date 2020-02-24.17:30:10.453>
creator = 'BTaskaya'
dependencies = []
files = []
hgrepos = []
issue_num = 39741
keywords = []
message_count = 2.0
messages = ['362599', '362602']
nosy_count = 3.0
nosy_names = ['larry', 'pablogsal', 'BTaskaya']
pr_nums = []
priority = 'low'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39741'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
FTR, if you try to use params named "self" in a class method (or "module" in a module level function), AC will bail and ask you to explicitly choose a custom name for the C variable. See https://github.com/python/cpython/issues/68395#issuecomment-1536053001.

I think we can close this after gh-104065 lands.

**Comment by erlend-aasland** [comment]
(If you disagree, Batuhan, please open.)
