### ISSUE TITLE
UnicodeError becomes unpicklable if data is appended to args

### ISSUE THREAD

**Issue by 10f23934-9f9d-4e66-9af6-98972008dada** [python/cpython#83931]
BPO | [39750](https://bugs.python.org/issue39750)
--- | :---
Nosy | @serhiy-storchaka
Files | <li>[test_unicode_error_unpickle.py](https://bugs.python.org/file48914/test_unicode_error_unpickle.py "Uploaded as text/plain at 2020-02-25.16:15:35 by João Eiras"): Test case</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-25.16:15:36.125>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'UnicodeError becomes unpicklable if data is appended to args'
updated_at = <Date 2020-03-01.17:55:50.780>
user = 'https://bugs.python.org/JooEiras'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-01.17:55:50.780>
actor = 'Jo\xc3\xa3o Eiras'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-02-25.16:15:36.125>
creator = 'Jo\xc3\xa3o Eiras'
dependencies = []
files = ['48914']
hgrepos = []
issue_num = 39750
keywords = []
message_count = 4.0
messages = ['362648', '362655', '362695', '363071']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'Jo\xc3\xa3o Eiras']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39750'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
I agree with @serhiy-storchaka's comment. If you want to arbitrarily change the API of an object you need to reimplement its pickling functions accordingly.
