### ISSUE TITLE
asyncio loop.add_signal_handler() may not behave as expected

### ISSUE THREAD

**Issue by b47f2d7d-8b8b-4c4d-a799-7bb33ba3e75f** [python/cpython#83946]
BPO | [39765](https://bugs.python.org/issue39765)
--- | :---
Nosy | @asvetlov, @1st1, @rogerdahl
PRs | <li>python/cpython#18664</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-26.20:46:52.392>
labels = ['type-bug', '3.8', 'expert-asyncio']
title = 'asyncio loop.add_signal_handler() may not behave as expected'
updated_at = <Date 2020-07-05.08:32:00.516>
user = 'https://github.com/rogerdahl'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-05.08:32:00.516>
actor = 'tiposchi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-02-26.20:46:52.392>
creator = 'rogerdahl'
dependencies = []
files = []
hgrepos = []
issue_num = 39765
keywords = ['patch']
message_count = 6.0
messages = ['362734', '362747', '362748', '362750', '362830', '373018']
nosy_count = 4.0
nosy_names = ['asvetlov', 'yselivanov', 'tiposchi', 'rogerdahl']
pr_nums = ['18664']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue39765'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
When signal handlers are called is not guarantied, the only guarantee is that it will be called if the signal is received. It is an implementation detail e.g. if C code handles pending calls and checks for signal etc. I am -1 on adding anything regarding these implementation details, user code should not rely on any of this. This issue is most likely a bug in your code rather than in `asyncio`.

**Comment by gvanrossum** [comment]
@rogerdahl Have you analyzed your program more? If you can show a small demo that exhibits this behavior we'd be happy to have a look.

**Comment by rogerdahl** [comment]
@gvanrossum Please leave this open for a bit and I'll try to find some time to see what the current status is.

**Comment by arhadthedev** [comment]
> Please leave this open for a bit and I'll try to find some time to see what the current status is.

@rogerdahl ping?

**Comment by rogerdahl** [comment]
@arhadthedev Thank you for following up. I've done some tests now and I'm unable to reproduce this. Please go ahead and close the ticket. I'll reopen it with code to reproduce if I encounter the issue again.

Just speculating, I think the problem might have been an interplay between signal handlers in my program and in aiohttp, which I was using heavily.

In my test, I set up an asyncio web server with delays in it to simulate slow responses, and an aiohttp based client that registered a signal handler and then hit the server with 1000 concurrent requests. The signal handler was still invoked instantly.

aiohttp registers its own signal handlers, including for SIGINT, which I also registered for. There's a comment in the signal handler setup in aiohttp that mentions workarounds for issues with Gunicorn, so maybe they were doing something odd there.
