### ISSUE TITLE
Optimize construction of Path from other Paths by just returning the same object?

### ISSUE THREAD

**Issue by 379dc349-3a10-424f-b9d2-a0104f092359** [python/cpython#83964]
BPO | [39783](https://bugs.python.org/issue39783)
--- | :---
Nosy | @brettcannon, @rhettinger, @pitrou, @remilapeyre, @barneygale
PRs | <li>python/cpython#20288</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-02-28.11:36:37.520>
labels = ['library', '3.10']
title = 'Optimize construction of Path from other Paths by just returning the same object?'
updated_at = <Date 2020-06-21.09:44:05.958>
user = 'https://github.com/anntzer'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-21.09:44:05.958>
actor = 'Antony.Lee'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-02-28.11:36:37.520>
creator = 'Antony.Lee'
dependencies = []
files = []
hgrepos = []
issue_num = 39783
keywords = ['patch']
message_count = 6.0
messages = ['362874', '362884', '362886', '362887', '362919', '362940']
nosy_count = 5.0
nosy_names = ['brett.cannon', 'rhettinger', 'pitrou', 'remi.lapeyre', 'barneygale']
pr_nums = ['20288']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39783'
versions = ['Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
Upon reflection, I'm not sure this optimization will help. `Path(Path(...))` is a reasonably rare construction, and the check will add an (admittedly small) runtime cost for every other use case.

**Comment by barneygale** [comment]
I've never been able to establish that this provides a useful speedup - in fact it slows down the most common form of construction -- `Path('whatever')` -- by as much as 10-15%. I'll close this issue and the associated PR, but if anyone can provide evidence that this is worthwhile, I'm happy to re-open.
