### ISSUE TITLE
Bracketed paste mode for REPL: don't execute pasted command before ENTER is pressed explicitly

### ISSUE THREAD

**Issue by 6740fb1f-e34b-433e-a958-b77f9c4427e8** [python/cpython#84001]
BPO | [39820](https://bugs.python.org/issue39820)
--- | :---
Nosy | @terryjreedy, @ericvsmith, @stevendaprano, @eryksun, @asmeurer, @Marco-Sulla

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-01.23:30:35.853>
labels = ['interpreter-core', 'type-feature', '3.9']
title = "Bracketed paste mode for REPL: don't execute pasted command before ENTER is pressed explicitly"
updated_at = <Date 2021-07-27.08:45:25.542>
user = 'https://github.com/Marco-Sulla'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-27.08:45:25.542>
actor = 'mhofmann'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-03-01.23:30:35.853>
creator = 'Marco Sulla'
dependencies = []
files = []
hgrepos = []
issue_num = 39820
keywords = []
message_count = 14.0
messages = ['363109', '363139', '363201', '363258', '363295', '363301', '363315', '363316', '363328', '363336', '369299', '386991', '386992', '387189']
nosy_count = 7.0
nosy_names = ['terry.reedy', 'eric.smith', 'steven.daprano', 'eryksun', 'asmeurer', 'Marco Sulla', 'mhofmann']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39820'
versions = ['Python 3.9']
```

</p></details>

**Comment by danielhoherd** [comment]
FWIW CircuitPython has an implementation where you enter paste mode by pressing CTRL-E and then finish paste mode by pressing CTRL-D:

```
Adafruit CircuitPython 8.0.0 on 2023-02-06; Pimoroni Keybow 2040 with rp2040
>>>
paste mode; Ctrl-C to cancel, Ctrl-D to finish
=== def example(thing):
===     print(thing)
===
===     print(thing, " part 2, after an empty line")
===
>>> example('yay circuitpython')
yay circuitpython
yay circuitpython  part 2, after an empty line
```

that same function definition fails in cpython:

```
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> def example(thing):
...     print(thing)
...
>>>     print(thing, " part 2, after an empty line")
  File "<stdin>", line 1
    print(thing, " part 2, after an empty line")
IndentationError: unexpected indent
```

I really like this implementation of a whitespace friendly way to paste code, and I think it would be great if cpython had it.

**Comment by terryjreedy** [comment]
@pablogsal If you are the one working on enhancing the REPL, could you look at this and maybe other REPL issues?

**Comment by pablogsal** [comment]
> @pablogsal If you are the one working on enhancing the REPL, could you look at this and maybe other REPL issues?

Yeah, after we have the new infrastructure we can go with the existing REPL issues and start addressing them one by one.

**Comment by vstinner** [comment]
Would it be worth it to add a topic-REPL label?

**Comment by terryjreedy** [comment]
Adding `REPL` to a standard issue search (`is:issue is:open REPL`) gives 116 hits.  This should be easy enough to scan when appropriate to find those relevant, which I suspect would be maybe 10.

**Comment by lysnikolaou** [comment]
I'll close this, since the problem has been fixed in the new REPL. Please open a new issue, in case something is not working properly.
