### ISSUE TITLE
Implement PyObject_CopyToObject

### ISSUE THREAD

**Issue by nanjekyejoannah** [python/cpython#84016]
BPO | [39835](https://bugs.python.org/issue39835)
--- | :---
Nosy | @nanjekyejoannah

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-03.15:18:33.166>
labels = ['expert-C-API', 'type-feature', '3.9']
title = 'Implement PyObject_CopyToObject'
updated_at = <Date 2020-03-03.15:18:33.166>
user = 'https://github.com/nanjekyejoannah'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-03.15:18:33.166>
actor = 'nanjekyejoannah'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-03-03.15:18:33.166>
creator = 'nanjekyejoannah'
dependencies = []
files = []
hgrepos = []
issue_num = 39835
keywords = []
message_count = 1.0
messages = ['363264']
nosy_count = 1.0
nosy_names = ['nanjekyejoannah']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue39835'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-124747

**Comment by JelleZijlstra** [comment]
PEP-3118 was written 18 years ago and we've managed without this function for that long. I think we should add it only if there are clear use cases, not simply because it's in the PEP.

If you'd like this function implemented, could you provide examples of existing code (e.g., in existing C extensions) that would be made better by this function?

**Comment by vstinner** [comment]
I just close the issue. If someone wants to reopen the issue, please come with convincing examples. Not just a reference to an old PEP.
