### ISSUE TITLE
Meta: Clean up various issues in C internals

### ISSUE THREAD

**Issue by a6e54279-29a2-4197-b414-54af27f54591** [python/cpython#84124]
BPO | [39943](https://bugs.python.org/issue39943)
--- | :---
Nosy | @vstinner, @benjaminp, @methane, @serhiy-storchaka, @ammaraskar, @miss-islington, @petdance
PRs | <li>python/cpython#18950</li><li>python/cpython#18973</li><li>python/cpython#19152</li><li>python/cpython#19170</li><li>python/cpython#19185</li><li>python/cpython#19186</li><li>python/cpython#19209</li><li>python/cpython#19210</li><li>python/cpython#19236</li><li>python/cpython#19327</li><li>python/cpython#19345</li><li>python/cpython#19405</li><li>python/cpython#19445</li><li>python/cpython#19472</li><li>python/cpython#20508</li><li>python/cpython#24856</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-12.03:23:07.476>
labels = ['interpreter-core']
title = 'Meta: Clean up various issues in C internals'
updated_at = <Date 2021-03-14.12:17:39.406>
user = 'https://github.com/petdance'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-14.12:17:39.406>
actor = 'miss-islington'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-03-12.03:23:07.476>
creator = 'petdance'
dependencies = []
files = []
hgrepos = []
issue_num = 39943
keywords = ['patch']
message_count = 21.0
messages = ['363993', '364443', '365049', '365126', '365127', '365151', '365155', '365346', '365418', '366098', '366194', '366242', '366355', '366373', '366391', '366642', '366942', '370280', '370564', '370565', '388667']
nosy_count = 7.0
nosy_names = ['vstinner', 'benjamin.peterson', 'methane', 'serhiy.storchaka', 'ammar2', 'miss-islington', 'petdance']
pr_nums = ['18950', '18973', '19152', '19170', '19185', '19186', '19209', '19210', '19236', '19327', '19345', '19405', '19445', '19472', '20508', '24856']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39943'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
Both pythonrun.c:579 and frameobject:400 (of the referenced version) were edited by now and the compiler warning is not relevant to the current versions.
