### ISSUE TITLE
Python 3.8 unconditionally uses functions not available on OS X 10.4 and 10.5

### ISSUE THREAD

**Issue by a197fd7e-f9de-4c4f-a391-d3b40d861fb7** [python/cpython#84129]
BPO | [39948](https://bugs.python.org/issue39948)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily, @dgelessus
PRs | <li>python/cpython#19008</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-12.21:44:12.875>
labels = ['OS-mac', '3.8', '3.9']
title = 'Python 3.8 unconditionally uses functions not available on OS X 10.4 and 10.5'
updated_at = <Date 2020-03-15.02:00:34.521>
user = 'https://github.com/dgelessus'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-15.02:00:34.521>
actor = 'dgelessus'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2020-03-12.21:44:12.875>
creator = 'dgelessus'
dependencies = []
files = []
hgrepos = []
issue_num = 39948
keywords = ['patch']
message_count = 3.0
messages = ['364051', '364140', '364145']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'dgelessus']
pr_nums = ['19008']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue39948'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by ronaldoussoren** [comment]
@ned-deily, is this something you're still interested in fixing? There is a PR that on first glance looks not too bad, but macOS 10.5 is too old for me to still care about.

**Comment by ronaldoussoren** [comment]
The same issue is likely present in 3.11.  There's also a PR that on first glance doesn't look too bad. That said, I cannot test if this actually fixes the issue and personally don't care about supporting MacOS 10.5 (support ended in 2012 at the latest). 

@ned-deily , are you interested in testing an reviewing the PR? Otherwise I propose closing both the attached PR and this issue.

**Comment by ned-deily** [comment]
@ronaldoussoren At a quick glance, the PR seems reasonable but adding more complexity just to support 10.4 and 10.5 at this point seems a stretch. I know that the MacPorts project tries to support these older macOS versions as best as possible but they also carry a number of patches to do so. I also think it is complicated enough that we would not want to backport it so it would first be available in 3.12 or later and I suspect there are other issues with trying to run current Python on such old versions of macOS. I would be able to test it on 10.5 but it's not something I would have time to do in the immediate future. (Thanks, @zitterbewegung, for the ping!)

**Comment by dgelessus** [comment]
Original reporter here (the GitHub migration didn't match my users up). My Mac OS X 10.4 system has Python 3.10 installed successfully via MacPorts, which still carries my patch (#19008). I'll check whether Python 3.11 builds too.

I can rebase my PR for Python 3.11/3.12 if you like. That said, I won't be angry if you decide that this is out of scope for upstream CPython. I am aware that you have more important worries than 15-year-old Mac OS X 🙂

**Comment by ronaldoussoren** [comment]
@ned-deily To be honest I'd prefer to close this issue, support for ancient macOS versions just complicates the code base (even if just a little) and is likely to break later on because we don't active test this.
