### ISSUE TITLE
cgi.parse() does not work with multipart POST requests.

### ISSUE THREAD

**Issue by 8267bdc8-3822-48cc-866f-3cce8cd95320** [python/cpython#84215]
BPO | [40034](https://bugs.python.org/issue40034)
--- | :---
Nosy | @sangh
PRs | <li>python/cpython#19130</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-21.17:23:48.862>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'cgi.parse() does not work with multipart POST requests.'
updated_at = <Date 2020-03-24.01:03:00.785>
user = 'https://github.com/sangh'
```

bugs.python.org fields:
```python
activity = <Date 2020-03-24.01:03:00.785>
actor = 'sangh'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-03-21.17:23:48.862>
creator = 'sangh'
dependencies = []
files = []
hgrepos = []
issue_num = 40034
keywords = ['patch']
message_count = 1.0
messages = ['364762']
nosy_count = 1.0
nosy_names = ['sangh']
pr_nums = ['19130']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40034'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by AlexWaygood** [comment]
The cgi module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements to the module will no longer be accepted. I am therefore closing this issue.

**Comment by AlexWaygood** [comment]
> The cgi module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements to the module will no longer be accepted. I am therefore closing this issue.

Cc. @sangh

**Comment by sangh** [comment]
Okay, I understand why PEP 594 was accepted.  It is a bit disappointing to me because apart from the bug cgi.parse handled all the variations in one call where with the replacements I have to inspect the header and then call various other tools.  Anyway thanks for responding (after so long).
