### ISSUE TITLE
more user-friendly turtledemo

### ISSUE THREAD

**Issue by 356cc69d-10c2-46de-9168-85d7da97c4fd** [python/cpython#84237]
BPO | [40056](https://bugs.python.org/issue40056)
--- | :---
Nosy | @terryjreedy
PRs | <li>python/cpython#19145</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-24.20:15:15.955>
labels = ['type-feature', 'library', '3.9']
title = 'more user-friendly turtledemo'
updated_at = <Date 2020-05-24.11:37:19.410>
user = 'https://bugs.python.org/EvinLiang'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-24.11:37:19.410>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-03-24.20:15:15.955>
creator = 'Evin Liang'
dependencies = []
files = []
hgrepos = []
issue_num = 40056
keywords = []
message_count = 3.0
messages = ['364961', '365234', '369792']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'Evin Liang']
pr_nums = ['19145']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40056'
versions = ['Python 3.9']
```

</p></details>

**Comment by terryjreedy** [comment]
After further reflection, I am closing this.  Aside from 'user-friendly' being vague and opinionated:
1. The menu names are the module/file names, or if you will, the import names.  Underscored are normal in Python.  If removed, then they would no longer match the real names, and someone else might consider the omission user unfriendly.
2. The proposal is too vague to act on; today, it would need to be posted on the Python discourse ideas channel.  I gave a solution above.  An instructor could easily use it to create a directory of class examples.  Turtledemo does what it is intended to do.  A rewrite to make it a runner of user examples should better be a pypi.python.org project.
