### ISSUE TITLE
Convert static types to heap types: use PyType_FromSpec()

### ISSUE THREAD

**Issue by corona10** [python/cpython#84258]
BPO | [40077](https://bugs.python.org/issue40077)
--- | :---
Nosy | @pitrou, @vstinner, @phsilva, @encukou, @skrah, @ericsnowcurrently, @serhiy-storchaka, @corona10, @pablogsal, @miss-islington, @shihai1991, @erlend-aasland, @h-vetinari, @nw0, @kumaraditya303, @CharlieZhao95
PRs | <li>python/cpython#19177</li><li>python/cpython#19202</li><li>python/cpython#19341</li><li>python/cpython#19344</li><li>python/cpython#19438</li><li>python/cpython#20960</li><li>python/cpython#20974</li><li>python/cpython#21953</li><li>python/cpython#21954</li><li>python/cpython#23108</li><li>python/cpython#23124</li><li>python/cpython#23136</li><li>python/cpython#23428</li><li>python/cpython#23443</li><li>python/cpython#23975</li><li>python/cpython#24065</li><li>python/cpython#24066</li><li>python/cpython#24481</li><li>python/cpython#30884</li>
Files | <li>[bench_isinstance_check.py](https://bugs.python.org/file49007/bench_isinstance_check.py "Uploaded as text/plain at 2020-03-29.02:06:38 by @corona10")</li><li>[bench_subclass_check.py](https://bugs.python.org/file49008/bench_subclass_check.py "Uploaded as text/plain at 2020-03-29.02:06:47 by @corona10")</li><li>[bench_isinstance_check.py](https://bugs.python.org/file49009/bench_isinstance_check.py "Uploaded as text/plain at 2020-03-29.14:40:47 by @corona10")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-26.16:04:44.633>
labels = ['extension-modules', 'type-feature', '3.10']
title = 'Convert static types to heap types: use PyType_FromSpec()'
updated_at = <Date 2022-02-02.05:50:10.693>
user = 'https://github.com/corona10'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-02.05:50:10.693>
actor = 'kumaraditya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2020-03-26.16:04:44.633>
creator = 'corona10'
dependencies = []
files = ['49007', '49008', '49009']
hgrepos = []
issue_num = 40077
keywords = ['patch']
message_count = 47.0
messages = ['365087', '365088', '365117', '365125', '365142', '365145', '365149', '365154', '365205', '365220', '365241', '365242', '365255', '365257', '365317', '365558', '365773', '366024', '366061', '368669', '371120', '371813', '371890', '372073', '372074', '372076', '372326', '375943', '380109', '380267', '380516', '380517', '380518', '383848', '383908', '384228', '384236', '384271', '384272', '384293', '410810', '411630', '411903', '411904', '411907', '411964', '412338']
nosy_count = 16.0
nosy_names = ['pitrou', 'vstinner', 'phsilva', 'petr.viktorin', 'skrah', 'eric.snow', 'serhiy.storchaka', 'corona10', 'pablogsal', 'miss-islington', 'shihai1991', 'erlendaasland', 'h-vetinari', 'nw0', 'kumaraditya', 'CharlieZhao']
pr_nums = ['19177', '19202', '19341', '19344', '19438', '20960', '20974', '21953', '21954', '23108', '23124', '23136', '23428', '23443', '23975', '24065', '24066', '24481', '30884']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40077'
versions = ['Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
> PEP 687 was [accepted](https://discuss.python.org/t/pep-687-isolating-modules-in-the-standard-library/14824/3)

Note that this does not imply that all types shall be converted to heap types. This is also mentioned in the PEP; please read it carefully.

**Comment by kumaraditya303** [comment]
> Note that this does not imply that _all_ types shall be converted to heap types. This is also mentioned in the PEP; please read it carefully.

We are on the same page, every module needs to considered individually and I am against converting any built-in modules or types unless it's necessary.

**Comment by kumaraditya303** [comment]
Superseded by #103092
