### ISSUE TITLE
Win7/Python3.8/asyncio IPv6 UDP Server raise OSError when recved any packet

### ISSUE THREAD

**Issue by e803f1d8-e2e4-4420-8ec4-95021b0edfa4** [python/cpython#84253]
BPO | [40072](https://bugs.python.org/issue40072)
--- | :---
Nosy | @asvetlov, @agronholm, @1st1
Files | <li>[asyncio_udp_ipv6_server.py](https://bugs.python.org/file49000/asyncio_udp_ipv6_server.py "Uploaded as text/plain at 2020-03-26.01:42:37 by honglei.jiang"): server</li><li>[udp_ipv6_client.py](https://bugs.python.org/file49001/udp_ipv6_client.py "Uploaded as text/plain at 2020-03-26.01:44:08 by honglei.jiang"): client</li><li>[udptest.py](https://bugs.python.org/file49346/udptest.py "Uploaded as text/plain at 2020-07-29.12:28:24 by @agronholm")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-26.01:42:38.044>
labels = ['type-bug', '3.8', 'expert-asyncio']
title = 'Win7/Python3.8/asyncio IPv6 UDP Server raise OSError when recved any packet'
updated_at = <Date 2020-07-29.12:29:48.308>
user = 'https://bugs.python.org/hongleijiang'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-29.12:29:48.308>
actor = 'alex.gronholm'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-03-26.01:42:38.044>
creator = 'honglei.jiang'
dependencies = []
files = ['49000', '49001', '49346']
hgrepos = []
issue_num = 40072
keywords = []
message_count = 4.0
messages = ['365045', '365048', '374569', '374570']
nosy_count = 4.0
nosy_names = ['asvetlov', 'alex.gronholm', 'honglei.jiang', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40072'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
Windows 7 and Python 3.8 (security fixes only) are not supported, if this issue is still present on supported versions, feel free to create another issue with code and traceback.
