### ISSUE TITLE
multiprocessor spawn

### ISSUE THREAD

**Issue by 5089ffbc-b451-485c-8b0b-c120b6e778bf** [python/cpython#84287]
BPO | [40106](https://bugs.python.org/issue40106)
--- | :---
Nosy | @ronaldoussoren, @pitrou, @ned-deily, @applio, @mouse07410, @blalterman

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-29.21:49:38.184>
labels = ['OS-mac', '3.8', 'type-crash']
title = 'multiprocessor spawn'
updated_at = <Date 2021-07-26.13:02:18.026>
user = 'https://github.com/mouse07410'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-26.13:02:18.026>
actor = 'andrenvk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2020-03-29.21:49:38.184>
creator = 'mouse07410'
dependencies = []
files = []
hgrepos = []
issue_num = 40106
keywords = []
message_count = 2.0
messages = ['365279', '368602']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'pitrou', 'ned.deily', 'davin', 'mouse07410', 'blalterman', 'andrenvk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue40106'
versions = ['Python 3.8']
```

</p></details>

**Comment by ronaldoussoren** [comment]
I'm closing this issue, the switch from "fork" to "spawn" on macOS was done to avoid crashes in code that links to higher-level APIs on macOS, including some bits of the stdlib (in particular the _scproxy extension used by urllib).
