### ISSUE TITLE
ZipFile.extractall is not multiprocess safe with regard to directory creation.

### ISSUE THREAD

**Issue by 4ea3ccd7-c9c0-4319-b0fd-dbf8a43baf05** [python/cpython#84284]
BPO | [40103](https://bugs.python.org/issue40103)
--- | :---
Nosy | @Yhg1s, @serhiy-storchaka, @nathansilberman
PRs | <li>python/cpython#19216</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-03-29.16:33:47.483>
labels = ['3.7', '3.8', 'type-bug', 'library', '3.9']
title = 'ZipFile.extractall is not multiprocess safe with regard to directory creation.'
updated_at = <Date 2020-05-22.20:15:02.673>
user = 'https://github.com/nathansilberman'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-22.20:15:02.673>
actor = 'cheryl.sabella'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-03-29.16:33:47.483>
creator = 'nathansilberman'
dependencies = []
files = []
hgrepos = []
issue_num = 40103
keywords = ['patch']
message_count = 1.0
messages = ['365268']
nosy_count = 3.0
nosy_names = ['twouters', 'serhiy.storchaka', 'nathansilberman']
pr_nums = ['19216']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40103'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by gpshead** [comment]
This is basically asking for zipfile to have a mode where the filesystem it is extracting to can change out from underneath it mid-extraction and it should just ignore errors and continue on.

An `ignore_errors=True` style of feature is probably feasible to implement, but I don't think it'd ever be a good idea for someone to use it...

**Comment by gpshead** [comment]
agreed, https://github.com/python/cpython/pull/115082 appears to have fixed it.
