### ISSUE TITLE
recursive call within generator expression is O(depth)

### ISSUE THREAD

**Issue by c619df7d-1075-4572-ac96-92bcca308691** [python/cpython#84406]
BPO | [40225](https://bugs.python.org/issue40225)
--- | :---
Nosy | @rhettinger, @markshannon, @serhiy-storchaka, @remilapeyre, @bulaiden
PRs | <li>python/cpython#19473</li>
Files | <li>[maxbug.py](https://bugs.python.org/file49043/maxbug.py "Uploaded as text/plain at 2020-04-08.12:10:27 by @bulaiden"): code and benchmarks</li><li>[maxbug2.py](https://bugs.python.org/file49044/maxbug2.py "Uploaded as text/plain at 2020-04-08.12:50:29 by @bulaiden")</li><li>[consumerbug.py](https://bugs.python.org/file49047/consumerbug.py "Uploaded as text/plain at 2020-04-09.13:02:13 by @bulaiden")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-08.12:10:27.397>
labels = ['3.7', 'library', 'performance']
title = 'recursive call within generator expression is O(depth)'
updated_at = <Date 2020-04-11.12:09:29.711>
user = 'https://github.com/bulaiden'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-11.12:09:29.711>
actor = 'Mark.Shannon'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-08.12:10:27.397>
creator = 'brendon-zhang@hotmail.com'
dependencies = []
files = ['49043', '49044', '49047']
hgrepos = []
issue_num = 40225
keywords = ['patch']
message_count = 15.0
messages = ['365978', '365979', '365981', '365983', '365984', '366040', '366041', '366048', '366049', '366050', '366051', '366052', '366053', '366200', '366204']
nosy_count = 5.0
nosy_names = ['rhettinger', 'Mark.Shannon', 'serhiy.storchaka', 'remi.lapeyre', 'brendon-zhang@hotmail.com']
pr_nums = ['19473']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue40225'
versions = ['Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
@markshannon Is there anything left to do here?

@brandtbucher FYI.

**Comment by markshannon** [comment]
No, I think this was fixed by https://github.com/python/cpython/pull/19473
