### ISSUE TITLE
re.Scanner groups

### ISSUE THREAD

**Issue by 0a316168-aece-4837-8017-5559bdb88c2e** [python/cpython#84440]
BPO | [40259](https://bugs.python.org/issue40259)
--- | :---
Nosy | @ezio-melotti, @tirkarthi
Files | <li>[re.Scanner.txt](https://bugs.python.org/file49049/re.Scanner.txt "Uploaded as text/plain at 2020-04-12.08:07:40 by dchron")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-12.07:52:00.286>
labels = ['expert-regex', 'type-bug', '3.8']
title = 're.Scanner groups'
updated_at = <Date 2020-04-12.14:06:10.839>
user = 'https://bugs.python.org/dchron'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-12.14:06:10.839>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2020-04-12.07:52:00.286>
creator = 'dchron'
dependencies = []
files = ['49049']
hgrepos = []
issue_num = 40259
keywords = []
message_count = 2.0
messages = ['366226', '366249']
nosy_count = 4.0
nosy_names = ['ezio.melotti', 'mrabarnett', 'xtreak', 'dchron']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40259'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`re.Scanner` uses groups internally. You should not refer to groups by number unless you know exactly how `re.Scanner` works internally. Use named groups instead.

It could be a documentation issue, but `re.Scanner` is not officially documented, so nothing to do here.

**Comment by serhiy-storchaka** [comment]
My suggestion to use named groups was incorrect -- no capturing groups are supported in `re.Scanner()`. Even named group change numbering of groups and mess with capturing groups used by `re.Scanner()` itself.
