### ISSUE TITLE
Add mapping methods to types.SimpleNamespace

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#84465]
BPO | [40284](https://bugs.python.org/issue40284)
--- | :---
Nosy | @rhettinger, @vstinner, @ericsnowcurrently, @vedgar, @shihai1991
Files | <li>[Dotable.py](https://bugs.python.org/file49061/Dotable.py "Uploaded as text/plain at 2020-04-15.04:28:09 by v+python")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-12-22.02:54:50.082>
created_at = <Date 2020-04-14.21:10:49.117>
labels = ['library', '3.9']
title = 'Add mapping methods to types.SimpleNamespace'
updated_at = <Date 2020-12-22.02:54:50.081>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-22.02:54:50.081>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2020-12-22.02:54:50.082>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2020-04-14.21:10:49.117>
creator = 'rhettinger'
dependencies = []
files = ['49061']
hgrepos = []
issue_num = 40284
keywords = []
message_count = 10.0
messages = ['366447', '366448', '366449', '366451', '366453', '366463', '366485', '366486', '366499', '366822']
nosy_count = 6.0
nosy_names = ['rhettinger', 'vstinner', 'v+python', 'eric.snow', 'veky', 'shihai1991']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue40284'
versions = ['Python 3.9']
```

</p></details>

**Comment by SimonBiggs** [comment]
> Only the magic methods need to be added: __getitem__, __setitem__, and __delitem__, __contains__, __len__, and __iter__.

Out of interest @rhettinger, what was your implementation for the above? I would absolutely love to be able to use the following:

> In particular, it would be wonderful to be able to use object_hook=SimpleNamespace in json.load():

Cheers,
Simon
