### ISSUE TITLE
Consider supporting emscripten/webassembly as a build target

### ISSUE THREAD

**Issue by 415e16fa-af75-433b-a167-0c33c1aadafb** [python/cpython#84461]
BPO | [40280](https://bugs.python.org/issue40280)
--- | :---
Nosy | @warsaw, @brettcannon, @terryjreedy, @tiran, @mcepl, @pmp-p, @rdb, @ethanhs, @corona10, @miss-islington, @tirkarthi, @erlend-aasland
PRs | <li>python/cpython#29771</li><li>python/cpython#29784</li><li>python/cpython#29789</li><li>python/cpython#29794</li><li>python/cpython#29795</li><li>python/cpython#29834</li><li>python/cpython#29842</li><li>python/cpython#29872</li><li>python/cpython#29873</li><li>python/cpython#29884</li><li>python/cpython#29887</li><li>python/cpython#29892</li><li>python/cpython#29893</li><li>python/cpython#29984</li><li>python/cpython#30494</li><li>python/cpython#30495</li><li>python/cpython#30538</li><li>python/cpython#30552</li><li>python/cpython#30559</li><li>python/cpython#30597</li><li>python/cpython#30601</li><li>python/cpython#30615</li><li>python/cpython#30620</li><li>python/cpython#30622</li><li>python/cpython#30722</li><li>python/cpython#30858</li><li>python/cpython#30930</li><li>python/cpython#31050</li><li>python/cpython#31757</li><li>python/cpython#31770</li><li>python/cpython#31791</li><li>python/cpython#31829</li><li>python/cpython#31865</li><li>python/cpython#31898</li><li>python/cpython#31909</li><li>python/cpython#31947</li><li>python/cpython#31986</li><li>python/cpython#32095</li><li>python/cpython#32224</li><li>python/cpython#32233</li><li>python/cpython#32238</li><li>python/cpython#32243</li><li>python/cpython#32253</li><li>python/cpython#32266</li><li>python/cpython#32284</li><li>python/cpython#32352</li><li>python/cpython#32360</li><li>python/cpython#32412</li>
Dependencies | <li>bpo-23325: Turn SIG_DFL and SIG_IGN into functions</li><li>bpo-33393: update config.guess and config.sub</li><li>bpo-41498: Undefinied _Py_Sigset_Converter function when HAVE_SIGSET_T not set</li><li>bpo-45881: Cross compiling on Linux is untested, undocumented, and broken</li><li>bpo-45886: Fix Program/_freeze_module for cross compiling Python</li><li>bpo-45898: ctypes cfield.c defines duplicate ffi_type_* symbols</li><li>bpo-46383: _zoneinfo module_free has invalid function signature</li><li>bpo-46390: Multiple test failures on Alpine 3.15 / musl-1.2.2-r7</li><li>bpo-46408: signal module wrongly relies on small int singletons</li><li>bpo-47162: Add call trampoline to work around bad fpcasts on Emscripten</li><li>bpo-47176: Interrupt handling for wasm32-emscripten builds without pthreads</li><li>bpo-47196: Function pointer cast in test_imp</li><li>bpo-47197: ctypes mishandles `void` return type</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-14.07:11:35.905>
labels = ['type-feature', 'build', '3.11']
title = 'Consider supporting emscripten/webassembly as a build target'
updated_at = <Date 2022-04-08.10:17:32.793>
user = 'https://bugs.python.org/SimonBiggs'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-08.10:17:32.793>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2020-04-14.07:11:35.905>
creator = 'Simon Biggs'
dependencies = ['23325', '33393', '41498', '45881', '45886', '45898', '46383', '46390', '46408', '47162', '47176', '47196', '47197']
files = []
hgrepos = []
issue_num = 40280
keywords = ['patch']
message_count = 65.0
messages = ['366369', '366374', '366375', '366379', '369598', '394081', '406985', '406986', '407011', '407012', '407013', '407014', '407015', '407018', '407020', '407021', '407030', '407046', '407048', '407049', '407052', '407080', '407264', '407284', '407484', '407498', '407519', '407524', '407541', '408855', '410138', '410400', '410423', '410554', '410577', '410647', '410727', '410743', '411039', '411514', '411560', '411847', '412595', '414748', '414769', '414780', '414845', '414940', '415136', '415259', '415297', '415398', '415757', '415976', '416494', '416509', '416541', '416542', '416579', '416681', '416763', '416865', '416916', '416933', '416934']
nosy_count = 14.0
nosy_names = ['barry', 'brett.cannon', 'terry.reedy', 'christian.heimes', 'mcepl', 'pmpp', 'rdb', 'ethan smith', 'corona10', 'miss-islington', 'Roman Yurchak', 'xtreak', 'erlendaasland', 'Simon Biggs']
pr_nums = ['29771', '29784', '29789', '29794', '29795', '29834', '29842', '29872', '29873', '29884', '29887', '29892', '29893', '29984', '30494', '30495', '30538', '30552', '30559', '30597', '30601', '30615', '30620', '30622', '30722', '30858', '30930', '31050', '31757', '31770', '31791', '31829', '31865', '31898', '31909', '31947', '31986', '32095', '32224', '32233', '32238', '32243', '32253', '32266', '32284', '32352', '32360', '32412']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40280'
versions = ['Python 3.11']
```

</p></details>

**Comment by pablogsal** [comment]
Seems that commit d1de10784d9678d14759d0d03216431d1090e60e has introduced a regression when building with `--enable-optimizations`. As we made the `libinstall` target depend on `all` install of `build_all` not running `altinstall` tries to build with PGO at that point.

when building with PGO, out of tree builds fail with:

```
$make -C ../ altinstall DESTDIR=$PWD -j
...
error: [Errno 2] No such file or directory: 'build/temp.macosx-12.4-arm64-3.11/multiarch'
```

**Comment by pablogsal** [comment]
I am marking this as release-blocker

@ethanfurman Please, take a look as soon as possible

**Comment by tiran** [comment]
@ethanhs

**Comment by pablogsal** [comment]
> Does the error also occur when you serialize make with -j1? 

Yes

> Could you please upload Makefile, pybuilddir.txt and the full output?

Will do when I am back at my computer, but you can reproduce with the steps that I pasted.

**Comment by pablogsal** [comment]
The requested files:

[files.zip](https://github.com/python/cpython/files/8853460/files.zip)

**Comment by tiran** [comment]
I don't see where ``[Errno 2] No such file or directory: 'build/temp.macosx-12.4-arm64-3.11/multiarch'`` is coming from. Is it coming from ``setup.py``?

**Comment by pablogsal** [comment]
> I don't see where `[Errno 2] No such file or directory: 'build/temp.macosx-12.4-arm64-3.11/multiarch'` is coming from. Is it coming from `setup.py`?

I think so, but with the parallelism is difficult to tell. Check the attached files for reference.

**Comment by ethanhs** [comment]
Ah OK, I have a 32 core machine I can try to repro on.

**Comment by pablogsal** [comment]
> @pablogsal I am not a core dev yet, so I presume I don't have access? But if it is public then I will take a look.

You don't need to be a core Dev to access most channels, only a trigger :)

**Comment by pablogsal** [comment]
> > I also was not able to repro the failure with my first attempt, but it sounds like it may be something to do with parallelism, which is why I didn't run into at first.
> 
> It requires parallel builds and lots of CPU cores. I'm unable to reproduce the issue on my 8 core laptop.

You also may need to run it multiple times to see it fail. Seems that reproducing on macOS is easier (at least in my case).

**Comment by ethanhs** [comment]
I am not a triager either so I guess I am out of luck :/

I am trying to run it until it fails on my 32 core machine. I don't have any macOS machines unfortunately, but at least its quite fast to build on 32 cores 😅

**Comment by tiran** [comment]
gh-93584 has more context on the issue. tl;dr Make rules for PGO builds have a bug and run two ``./python setup.py build`` instances in parallel.
