### ISSUE TITLE
Fix server_close() method for ThreadingHTTPServer and TCPServer class

### ISSUE THREAD

**Issue by bce058cb-9e65-4fca-ac0c-cef060c35d81** [python/cpython#84485]
BPO | [40305](https://bugs.python.org/issue40305)
--- | :---
Nosy | @RouxAntoine
PRs | <li>python/cpython#19556</li>
Files | <li>[testHttpServer.py](https://bugs.python.org/file49068/testHttpServer.py "Uploaded as text/plain at 2020-04-16.18:13:08 by @RouxAntoine"): problematic use case of ThreadingHTTPServer()</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-16.18:13:08.923>
labels = ['type-bug', 'library', '3.9']
title = 'Fix server_close() method for ThreadingHTTPServer and TCPServer class'
updated_at = <Date 2020-04-16.18:24:18.834>
user = 'https://github.com/RouxAntoine'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-16.18:24:18.834>
actor = 'python-dev'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-16.18:13:08.923>
creator = 'ROUX antoine2'
dependencies = []
files = ['49068']
hgrepos = []
issue_num = 40305
keywords = ['patch']
message_count = 1.0
messages = ['366619']
nosy_count = 2.0
nosy_names = ['python-dev', 'ROUX antoine2']
pr_nums = ['19556']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40305'
versions = ['Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
As a result of the discussion on the PR #19556, I understood the problem, and I think that nothing needs to be changed. There are two independent interfaces here. `server_close()` should be called to close the connection implicitly created in the constructor. And `shutdown()` should be called to stop a loop started in `serve_forever()`. It should only be called if `serve_forever()` was called, and necessarily in another thread. The user can never call `serve_forever()`, and therefore do not need to call `shutdown()`. The user can call `serve_forever()` in a new thread and `shutdown()` in the main thread, or call `serve_forever()` in the main thread and `shutdown()` in a different thread. It is all not related to `server_close()`. The code that calls `serve_forever()` is responsible to call `shutdown()`, it cannot be solved at the library level.
