### ISSUE TITLE
“unmatched paren” for space before parenthesis in Py_BuildValue

### ISSUE THREAD

**Issue by 3d39250a-fd18-44dd-b1a5-0b611e22a255** [python/cpython#84489]
BPO | [40309](https://bugs.python.org/issue40309)
--- | :---
Nosy | @Wrzlprmft, @ZackerySpytz
PRs | <li>python/cpython#21158</li>
Files | <li>[foo.c](https://bugs.python.org/file49069/foo.c "Uploaded as text/x-csrc at 2020-04-17.08:54:26 by @Wrzlprmft"): Minimal Python C Extension showing the bug</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-17.08:54:27.483>
labels = ['expert-C-API', '3.7', '3.8']
title = '\xe2\x80\x9cunmatched paren\xe2\x80\x9d for space before parenthesis in Py_BuildValue'
updated_at = <Date 2020-06-25.15:53:09.748>
user = 'https://github.com/Wrzlprmft'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-25.15:53:09.748>
actor = 'ZackerySpytz'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-04-17.08:54:27.483>
creator = 'Wrzlprmft'
dependencies = []
files = ['49069']
hgrepos = []
issue_num = 40309
keywords = ['patch']
message_count = 1.0
messages = ['366647']
nosy_count = 2.0
nosy_names = ['Wrzlprmft', 'ZackerySpytz']
pr_nums = ['21158']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40309'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

### Linked PRs
* gh-110596
* gh-110680

**Comment by serhiy-storchaka** [comment]
I decided to not backport this change. It is impossible to backport tests to 3.11, because of completely different structure of C API tests. Backporting it without tests is not very good. But if we finally decide to backport C API tests from 3.12 to 3.11, the difference between 3.11 and 3.12 can cause many troubles.
