### ISSUE TITLE
pathlib's relative_to should behave like os.path.relpath

### ISSUE THREAD

**Issue by 2e43ab83-bade-46f4-acc7-c599eba17e11** [python/cpython#84538]
BPO | [40358](https://bugs.python.org/issue40358)
--- | :---
Nosy | @pitrou, @eryksun, @ammaraskar, @CuriousLearner, @CAM-Gerlach, @barneygale, @domragusa, @bowiechen
PRs | <li>python/cpython#19807</li><li>python/cpython#19813</li>
Files | <li>[relative_to.patch](https://bugs.python.org/file49095/relative_to.patch "Uploaded as text/plain at 2020-04-28.03:52:45 by @domragusa")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-22.00:03:03.148>
labels = ['type-feature', 'library', '3.11']
title = "pathlib's relative_to should behave like os.path.relpath"
updated_at = <Date 2022-02-22.23:57:02.772>
user = 'https://github.com/domragusa'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-22.23:57:02.772>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-22.00:03:03.148>
creator = 'd.ragusa'
dependencies = []
files = ['49095']
hgrepos = []
issue_num = 40358
keywords = ['patch']
message_count = 11.0
messages = ['366958', '367037', '367041', '367047', '367490', '367697', '367723', '370254', '393696', '393777', '408249']
nosy_count = 10.0
nosy_names = ['pitrou', 'python-dev', 'eryksun', 'ammar2', 'Socob', 'CuriousLearner', 'CAM-Gerlach', 'barneygale', 'd.ragusa', 'bowiechen']
pr_nums = ['19807', '19813']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40358'
versions = ['Python 3.11']
```

</p></details>

**Comment by barneygale** [comment]
`relpath()` always calls `abspath()`, which is "impure" by pathlib standards.

If _both_ arguments to `relpath()` are relative paths then the `abspath()` calls can probably be removed. It would save a system call, and allow `PurePath.relative_to()` to call into `os.path.relpath()` safely:

```python
    def relative_to(self, *other):
        if not other:
            raise TypeError("need at least one argument")
        other = type(self)(*other)
        if self.is_absolute() != other.is_absolute():
            raise ValueError("one path is relative and the other is absolute: "
                             "{!r}, {!r}".format(str(self), str(other)))
        rel = self._flavour.relpath(other, self)
        return type(self)(rel)
```

**Comment by barneygale** [comment]
An interesting comment in `PurePath.relative_to()`:

```python
        # For the purpose of this method, drive and root are considered
        # separate parts, i.e.:
        #   Path('c:/').relative_to('c:')  gives Path('/')
        #   Path('c:/').relative_to('/')   raise ValueError
```

This isn't true for `ntpath.relpath()`:

```python
>>> import ntpath
>>> ntpath.relpath('c:\\', 'c:')
'.'
```

Pathlib's behaviour is deliberate but questionable. If we're willing to drop it, then we can call through to `os.path.relpath()` when users call `relative_to(..., strict=False)`.

Also, `path.is_relative_to(other)` would simplify down to `other == path or other in path.parents`, which is so simple it barely qualifies for a (misleadingly named) method. It might make sense to deprecate it.

**Comment by pitrou** [comment]
"C:" is the current directory in drive C, so I think pathlib's answer is the correct one here (of course, I wrote it so I may be biaised :-)).

**Comment by barneygale** [comment]
Thanks Antoine! That makes sense, but it still seems a odd to me that naked Windows drive paths are the only place where absolute and relative paths can be mixed! Extending your logic:

1. Should `PureWindowsPath('c:/').relative_to('c:foo/bar')` also return `'/'`? 
2. Should `PurePosixPath('/etc/hosts').relative_to('foo')` return `/etc/hosts`?

Maybe this is a "practicality beats purity" thing?

**Comment by pitrou** [comment]
I would say it is a practically beats purity thing indeed. I don't remember the details of why I chose to allow it at the time.

**Comment by barneygale** [comment]
Correction to my earlier post: 

`C:` is a relative path, and `relpath()` transforms it to an absolute path (i.e. prepends the working directory) before working out the result. From an _actual windows box_ and `C:\Users\me`:

```python
>>> import ntpath
>>> ntpath.relpath('C:\\', start='C:')
'..\\..'
>>> ntpath.relpath('C:\\', start='C:foo')
'..\\..\\..'
```

Here's `pathlib` for comparison's sake:

```python
>>> import pathlib
>>> pathlib.PureWindowsPath('C:/').relative_to('C:')
PureWindowsPath('/')
>>> pathlib.PureWindowsPath('C:/').relative_to('C:foo')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/barney.gale/code/cpython/Lib/pathlib.py", line 673, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: 'C:\\' is not in the subpath of 'C:foo' OR one path is relative and the other is absolute.
```
