### ISSUE TITLE
SocketHandler silently drops log messages on re-connect

### ISSUE THREAD

**Issue by 29aed705-4c9b-4f6c-95b6-f70ab2701775** [python/cpython#84532]
BPO | [40352](https://bugs.python.org/issue40352)
--- | :---
Nosy | @vsajip, @serhiy-storchaka, @remilapeyre
PRs | <li>python/cpython#22061</li>
Files | <li>[Archive.zip](https://bugs.python.org/file49080/Archive.zip "Uploaded as application/zip at 2020-04-21.13:02:07 by Oleg Nykolyn"): test client and server to reproduce the issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-21.13:02:07.496>
labels = ['3.8', 'type-bug', 'library']
title = 'SocketHandler silently drops log messages on re-connect'
updated_at = <Date 2020-10-14.15:36:25.488>
user = 'https://bugs.python.org/OlegNykolyn'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-14.15:36:25.488>
actor = 'Oleg Nykolyn'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-21.13:02:07.496>
creator = 'Oleg Nykolyn'
dependencies = []
files = ['49080']
hgrepos = []
issue_num = 40352
keywords = ['patch']
message_count = 8.0
messages = ['366920', '366925', '366929', '376190', '376217', '376229', '376844', '378625']
nosy_count = 4.0
nosy_names = ['vinay.sajip', 'serhiy.storchaka', 'remi.lapeyre', 'Oleg Nykolyn']
pr_nums = ['22061']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40352'
versions = ['Python 3.8']
```

</p></details>

**Comment by 29aed705-4c9b-4f6c-95b6-f70ab2701775** [comment]
Hi,

I've faced this issue when using logging.handlers.SocketHandler AWS TCP balancer. AWS balancer uses 60 second time-out by default (max 4000s), thus resulting in lots of closed sockets during inactive periods.
SocketHandler.send() drops current message on any socket errors, so only next message gets logged.
I've tried to reproduce this using Lib unit tests, but didn't find any easy way to close() socket on test server side.
 
Sample client/server scripts attached, server output:

```
Got connection from:  ('127.0.0.1', 58044)
Got message:  b'Message #1\n'
Got message:  b'Message #2\n'
Got connection from:  ('127.0.0.1', 58045)
Got message:  b'Message #5\n'
```

Server closes incoming connection is 2 seconds, client looses messages #3 and #4.

**Comment by vsajip** [comment]
Hmmm. I set up a slightly modified version of these test files [here](https://replit.com/join/irzjibtxgq-vsajip) [and a Gist is [here](https://gist.github.com/vsajip/2c1b0c9f6b3e264e41b549d1cc805f8e)], and I am seeing something odd: If I run `python t_server.py &` followed by `python t_client.py`, I get output like this:
```text
39891.620592 Client trying to create socket
39891.628369 Client created socket
39891.628408 Client sending b'Message #1\n'
39891.628437 Client sent b'Message #1\n'
39891.628479 Server got connection from:  ('127.0.0.1', 35584)
39891.628601 Server got message:  b'Message #1\n'
39896.633251 Client sending b'Message #2\n'
39896.633459 Client sent b'Message #2\n'
39896.633532 Server got message:  b'Message #2\n'
39896.633681 Server shut down reading on socket
39896.633770 Server closed socket
39896.838884 Client sending b'Message #3\n'
39896.839071 Client sent b'Message #3\n'
39897.039539 Client sending b'Message #4\n'
39897.039638 Client failed to send b'Message #4\n' ([Errno 32] Broken pipe)
39897.240175 Client trying to create socket
39897.240500 Client created socket
39897.240542 Client sending b'Message #5\n'
39897.240579 Client sent b'Message #5\n'
39897.240770 Server got connection from:  ('127.0.0.1', 43562)
39897.240893 Server got message:  b'Message #5\n'
```
What I find odd is that the server closes its socket before the client sends Message 3, but no error is seen at the socket level until Message 4 is sent. I can't at the moment see why that is - I would have expected to see a "failed to send" for Message 3.

**Comment by vsajip** [comment]
Pinging @nykolynoleg in case you are the OP for this issue.

**Comment by vsajip** [comment]
OK, I think I see why Message 3 didn't raise an error - it was buffered locally and an actual attempt send only happened when Message 4 was sent. At that point the fact that the server had gone away was detected. If you want to avoid this problem you will probably need to use UDP, even though it is lossy. In a stream-oriented protocol, events could be buffered up locally in a network buffer (with no way of knowing which ones have actually been sent to the server).

**Comment by serhiy-storchaka** [comment]
Yes, this was the problem I encountered when trying to write the tests. This is why #22061 was not finished. Maybe there is some way to save the local buffer and resend it after reconnecting?

**Comment by vsajip** [comment]
Not without peeking into lower levels of the socket code, I don't think. It might also expose the user to low-level details of TCP (windows, flow control etc.) which is probably not desirable to do. The basic problem is that the OP wants to treat logging events discretely, implying datagrams, but to do it over the streaming interface of TCP. What would be needed would be a socket `flush()` method which flushed the current contents of the client's network buffer to the server. If that were available (of course, it isn't), we could force the buffer to be sent to the server by calling `flush()` from `emit()`, and that would detect the error straight away where the event was still available as a `LogRecord` which could be buffered to be sent later.

**Comment by vsajip** [comment]
Relevant: an answer to the question [How can I force a socket to send the data in its buffer?](http://www.unixguide.net/network/socketfaq/2.11.shtml) - tl;dr:

> You can't force it.  Period.

**Comment by serhiy-storchaka** [comment]
Then we have no choice but to close this issue?

**Comment by serhiy-storchaka** [comment]
I would like to reopen this. `SocketHandler` cannot be made lossless over TCP -- the first record after the connection is closed is lost locally before the reset arrives, and I am not proposing to fix that.

But two records are lost here, not one. In the OP's log #3 is that unavoidable one, while #4 fails with `BrokenPipeError` and `send()` simply drops it, reconnecting only on the next record. Resending #4 instead is not a new policy: `SysLogHandler` has reopened the socket and resent the current record on `OSError` since 2.5.

The other reason #22061 stalled was the lack of a faithful test. That is now solved. See #154540.
