### ISSUE TITLE
Deprecate lib2to3 (and 2to3) for future removal

### ISSUE THREAD

**Issue by gpshead** [python/cpython#84540]
BPO | [40360](https://bugs.python.org/issue40360)
--- | :---
Nosy | @gvanrossum, @gpshead, @vstinner, @carljm, @ambv, @ericsnowcurrently, @hroncok, @corona10, @miss-islington, @tirkarthi, @isidentical, @iritkatriel
PRs | <li>python/cpython#19645</li><li>python/cpython#19663</li><li>python/cpython#19898</li><li>python/cpython#21694</li><li>python/cpython#21696</li><li>python/cpython#21697</li><li>python/cpython#28116</li><li>python/cpython#28122</li><li>python/cpython#28127</li><li>python/cpython#29064</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-09-02.16:03:42.312>
created_at = <Date 2020-04-22.04:40:54.230>
labels = ['type-feature', 'expert-2to3', '3.11']
title = 'Deprecate lib2to3 (and 2to3) for future removal'
updated_at = <Date 2021-10-20.22:28:52.390>
user = 'https://github.com/gpshead'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-20.22:28:52.390>
actor = 'iritkatriel'
assignee = 'none'
closed = True
closed_date = <Date 2021-09-02.16:03:42.312>
closer = 'vstinner'
components = ['2to3 (2.x to 3.x conversion tool)']
creation = <Date 2020-04-22.04:40:54.230>
creator = 'gregory.p.smith'
dependencies = []
files = []
hgrepos = []
issue_num = 40360
keywords = ['patch']
message_count = 51.0
messages = ['366973', '367005', '367031', '367051', '367208', '367209', '367230', '367235', '367716', '367726', '367730', '367743', '367744', '367766', '367767', '367770', '367771', '367884', '368077', '368388', '373185', '373198', '373327', '373332', '373334', '373444', '373538', '374348', '374349', '374566', '374572', '374573', '374574', '374611', '374634', '374643', '379014', '400876', '400877', '400879', '400883', '400885', '400892', '400905', '400906', '400923', '400927', '400933', '400937', '404324', '404532']
nosy_count = 14.0
nosy_names = ['gvanrossum', 'gregory.p.smith', 'vstinner', 'carljm', 'lukasz.langa', 'eric.snow', 'davidhalter', 'hroncok', 'corona10', 'miss-islington', 'xtreak', 'BTaskaya', 'Peter Ludemann', 'iritkatriel']
pr_nums = ['19645', '19663', '19898', '21694', '21696', '21697', '28116', '28122', '28127', '29064']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40360'
versions = ['Python 3.11']
```

</p></details>

**Comment by johns1c** [comment]
What does this mean for someone who picks up a bit of code that happens to be obsolete and then starts getting warnings about print statements and lots of other stuff?

**Comment by gvanrossum** [comment]
@johns1c -- It means that you should ask for help somewhere else. :-) Seriously, try explaining your problem in our Discourse server at discuss.python.org.

**Comment by vstinner** [comment]
For people who still have a Python 2 code base: download/install Python 3.12 and run 2to3 included in this version. Or give a try to 2to3 alternatives.

**Comment by johns1c** [comment]
Thanks for your reply.   

This works for Python 3.11 with 2to3.exe being found in the `Scripts` directory of my Windows 11 64 bit install and 2to3.py being found in `Tools\scripts`   (it was ‘tools\scripts’ in 3.8)

Interestingly the Windows install for Python 3.12 does NOT provide either the library or the runnable utility. 

From now on it seems that a user wishing to upgrade old Python 2 code needs to install 2to3 using PIP.  The command `PIP install 2to3` will install 2to3.exe in the `Scripts` directory under the Python install directory or in the `scripts` directory of a virtual environment.   


Chris J

**Comment by hlovdal** [comment]
> 2to3 alternatives

@vstinner Such as?

**Comment by ambv** [comment]
Such as [modernize](https://pypi.org/project/modernize/).
