### ISSUE TITLE
argparse: action "extend" with 1 parameter splits strings into characters

### ISSUE THREAD

**Issue by 184aab57-ff63-4c99-bd33-8f9c6cd2f7e8** [python/cpython#84545]
BPO | [40365](https://bugs.python.org/issue40365)
--- | :---
Nosy | @rhettinger, @berkerpeksag, @asottile, @isidentical, @jonathanhaigh
Files | <li>[argparse_bug.py](https://bugs.python.org/file49086/argparse_bug.py "Uploaded as text/plain at 2020-04-22.17:42:36 by strjan"): Minimal example</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-22.17:42:36.895>
labels = ['type-bug', '3.8', '3.9']
title = 'argparse: action "extend" with 1 parameter splits strings into characters'
updated_at = <Date 2020-06-09.13:20:45.393>
user = 'https://bugs.python.org/strjan'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-09.13:20:45.393>
actor = 'Jonathan Haigh'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-04-22.17:42:36.895>
creator = 'strjan'
dependencies = []
files = ['49086']
hgrepos = []
issue_num = 40365
keywords = []
message_count = 4.0
messages = ['367033', '367045', '370898', '371103']
nosy_count = 7.0
nosy_names = ['rhettinger', 'berker.peksag', 'paul.j3', 'Anthony Sottile', 'BTaskaya', 'strjan', 'Jonathan Haigh']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40365'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

### Linked PRs
* gh-125870
* gh-125964
* gh-125965

**Comment by serhiy-storchaka** [comment]
I do not think that we should forbid `nargs=None` and `nargs='?'`. It may be surprising for some users when they experience this the first time, but it can be the needed behavior for others. And it can already be used in the user code. This is why it is even hard to change the default value of `nargs`.

But these peculiarities should be documented.
