### ISSUE TITLE
Support GenericAlias in typing

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#84576]
BPO | [40396](https://bugs.python.org/issue40396)
--- | :---
Nosy | @gvanrossum, @serhiy-storchaka, @ilevkivskyi
PRs | <li>python/cpython#19718</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-04-26.19:27:57.404>
created_at = <Date 2020-04-26.16:02:57.099>
labels = ['type-feature', 'library', '3.9']
title = 'Support GenericAlias in typing'
updated_at = <Date 2020-04-26.19:27:57.404>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-04-26.19:27:57.404>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = True
closed_date = <Date 2020-04-26.19:27:57.404>
closer = 'serhiy.storchaka'
components = ['Library (Lib)']
creation = <Date 2020-04-26.16:02:57.099>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 40396
keywords = ['patch']
message_count = 2.0
messages = ['367308', '367326']
nosy_count = 3.0
nosy_names = ['gvanrossum', 'serhiy.storchaka', 'levkivskyi']
pr_nums = ['19718']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40396'
versions = ['Python 3.9']
```

</p></details>

**Comment by danielkatzan** [comment]
@serhiy-storchaka 
why does `get_origin(list)` returns `None` while `get_origin(List)` returns `<class 'list'>`

shouldn't list behaves exactly the same as List? (the same question applies to all generics)

**Comment by gvanrossum** [comment]
@danielkatzan Looks like an omission in the code for `get_origin()`. Would you like to submit a PR to fix it? I can't promise that it will make it into 3.11 but it will be in 3.11.1.

**Comment by danielkatzan** [comment]
@gvanrossum Sure, I would be happy to, but could use a little pointer here
Not sure how this can be accomplished 

note while `type(list[str])` is `<class 'types.GenericAlias'>` and has the `__origin__` attribute, `type(list)` is actually `<class 'type'>` and doesn't have an `__origin__` attribute

I can add an explicit if, checking if the tp is actually dict\list etc, and return that instead of None

will that be a valid approach? or just masking a deeper issue that might pop up later in a different location?

**Comment by serhiy-storchaka** [comment]
This issue was closed 2 years ago, please open a new issue.

The fact that `get_origin(List)` returns `list` is not documented. It looks to me like an implementation artifact.

**Comment by AlexWaygood** [comment]
> The fact that `get_origin(List)` returns `list` is not documented. It looks to me like an implementation artifact.

Changing that would be a breaking change at this point (at least... it would break code that I, personally, have written).

**Comment by danielkatzan** [comment]
opened this https://github.com/python/cpython/issues/95539#issue-1324734978
