### ISSUE TITLE
Scripts folder is Empty in python 3.8.2 for Windows 7.

### ISSUE THREAD

**Issue by f36707b3-948c-4bd4-a47d-47ce7552e76c** [python/cpython#84575]
BPO | [40395](https://bugs.python.org/issue40395)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba
Files | <li>[Installation Log.zip](https://bugs.python.org/file49093/Installation%20Log.zip "Uploaded as application/x-zip-compressed at 2020-04-26.14:18:10 by BenTen Jan"): Log File of %temp% folder</li><li>[Python log files.zip](https://bugs.python.org/file50079/Python%20log%20files.zip "Uploaded as application/x-zip-compressed at 2021-06-01.16:23:20 by poojawarhekar2012")</li><li>[Installation log _02062021.zip](https://bugs.python.org/file50080/Installation%20log%20_02062021.zip "Uploaded as application/x-zip-compressed at 2021-06-02.02:53:14 by poojawarhekar2012")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-26.14:18:10.710>
labels = ['3.8', 'expert-installation', 'OS-windows']
title = 'Scripts folder is Empty in python 3.8.2 for Windows 7.'
updated_at = <Date 2021-06-04.10:12:16.335>
user = 'https://bugs.python.org/BenTenJan'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-04.10:12:16.335>
actor = 'kuzja'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2020-04-26.14:18:10.710>
creator = 'BenTen Jan'
dependencies = []
files = ['49093', '50079', '50080']
hgrepos = []
issue_num = 40395
keywords = []
message_count = 14.0
messages = ['367307', '367443', '367444', '367499', '367548', '367645', '374579', '374588', '394854', '394856', '394861', '394864', '394885', '395020']
nosy_count = 7.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'BenTen Jan', 'Why Me', 'poojawarhekar2012']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40395'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Windows 7 is no longer supported. Marking as pending and will close soon unless someone gives a reason not to.
