### ISSUE TITLE
allow array.array construction from memoryview w/o copy

### ISSUE THREAD

**Issue by 490cec65-8fee-46dc-aacf-bc9ad023c34b** [python/cpython#84620]
BPO | [40440](https://bugs.python.org/issue40440)
--- | :---
Nosy | @skrah, @serhiy-storchaka, @applio, @bjkeen
PRs | <li>python/cpython#19800</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-04-29.19:01:33.112>
labels = ['type-feature', 'library']
title = 'allow array.array construction from memoryview w/o copy'
updated_at = <Date 2020-05-06.14:32:22.084>
user = 'https://github.com/bjkeen'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-06.14:32:22.084>
actor = 'bjkeen'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-04-29.19:01:33.112>
creator = 'bjkeen'
dependencies = []
files = []
hgrepos = []
issue_num = 40440
keywords = ['patch']
message_count = 5.0
messages = ['367688', '367705', '367879', '367883', '368258']
nosy_count = 4.0
nosy_names = ['skrah', 'serhiy.storchaka', 'davin', 'bjkeen']
pr_nums = ['19800']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40440'
versions = []
```

</p></details>

**Comment by serhiy-storchaka** [comment]
This is a breaking change. When you create an array object, you expect creating an independent copy. Changing the source data after creating an array should not affect its content, and vice verse. If you want dependent objects, you need other type. And Python provide such type, it is memoryview.

Change of the array fundamental behavior is a large no-no.
