### ISSUE TITLE
Deprecate the optional *random* argument to random.shuffle()

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#84645]
BPO | [40465](https://bugs.python.org/issue40465)
--- | :---
Nosy | @tim-one, @rhettinger, @vstinner, @serhiy-storchaka, @hugovk
PRs | <li>python/cpython#19867</li><li>python/cpython#25874</li><li>python/cpython#31818</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-05-02.23:49:03.587>
created_at = <Date 2020-05-01.08:31:41.792>
labels = ['type-bug', 'library', '3.9']
title = 'Deprecate the optional *random* argument to random.shuffle()'
updated_at = <Date 2022-03-24.13:29:22.965>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-24.13:29:22.965>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2020-05-02.23:49:03.587>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2020-05-01.08:31:41.792>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 40465
keywords = ['patch']
message_count = 8.0
messages = ['367826', '367828', '367948', '370417', '370418', '415418', '415940', '415941']
nosy_count = 5.0
nosy_names = ['tim.peters', 'rhettinger', 'vstinner', 'serhiy.storchaka', 'hugovk']
pr_nums = ['19867', '25874', '31818']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40465'
versions = ['Python 3.9']
```

</p></details>

**Comment by shaperilio** [comment]
> AFAICT, no one ever uses the optional parameter, nor would they have a valid reason to do so. It is an ancient API oddity and is inconsistent with the other methods in the module. I've long been annoyed by it and would like to see it cleaned-up before I retire ;-)

Wow, what a bold statement 🤣. We were using it. Hope you're enjoying retirement.

Can someone help me understand the motivation for this? I keep clicking on links trying to figure it out if there was a bug associated with this, but I'm not familiar with the issue tracking here.

**Comment by serhiy-storchaka** [comment]
1. It complicated the code.
2. When that argument was specified, the result was less random.
3. The design just looked wrong.

**Comment by tim-one** [comment]
The default implementation of `shuffle()`  stopped using `random()` long ago - it switched to a method avoiding floats entirely, and also avoiding the slight statistical biases the come with using floats for this.

So if you passed `random=` after that change, it went back to using the older - different & inherently biased - algorithm.

Keeping a worse algorithm in the code base was a Bad Idea on the face of it, especially given that nobody looking at this knew of anyone actually using the optional argument.

In the very early days, Python used the feeble (by current standards) Wichmann–Hill generator. Then there was far more user interest in replacing it with something better, even if slower. For the far fewer users who still care about that, there's a documented way to subclass `Random` now to use whatever other underlying generator you like better, and in a way that affects _all_ the methods (not just `shuffle()`) building on the underlying generator.
