### ISSUE TITLE
Port _hashlib to OpenSSL 3.0.0

### ISSUE THREAD

**Issue by tiran** [python/cpython#84659]
BPO | [40479](https://bugs.python.org/issue40479)
--- | :---
Nosy | @gpshead, @tiran, @ZackerySpytz, @miss-islington
PRs | <li>python/cpython#19878</li><li>python/cpython#20107</li><li>python/cpython#20108</li><li>python/cpython#20111</li><li>python/cpython#20112</li><li>python/cpython#30455</li><li>python/cpython#30573</li><li>python/cpython#30574</li><li>python/cpython#30584</li><li>python/cpython#30585</li><li>python/cpython#30586</li><li>python/cpython#31153</li><li>python/cpython#31183</li><li>python/cpython#31184</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2020-05-03.09:23:23.143>
labels = ['expert-SSL', '3.8', 'type-feature', '3.7', '3.9']
title = 'Port _hashlib to OpenSSL 3.0.0'
updated_at = <Date 2022-02-07.08:08:13.986>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-07.08:08:13.986>
actor = 'miss-islington'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['SSL']
creation = <Date 2020-05-03.09:23:23.143>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 40479
keywords = ['patch']
message_count = 16.0
messages = ['367962', '368957', '368958', '368961', '368962', '410097', '410471', '410479', '410481', '410523', '410525', '410526', '412614', '412715', '412716', '412717']
nosy_count = 4.0
nosy_names = ['gregory.p.smith', 'christian.heimes', 'ZackerySpytz', 'miss-islington']
pr_nums = ['19878', '20107', '20108', '20111', '20112', '30455', '30573', '30574', '30584', '30585', '30586', '31153', '31183', '31184']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40479'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
@tiran Can this be closed now ?

**Comment by gpshead** [comment]
closing as the bulk of this appears done but it isn't clear what 100% is.  If there are remaining deprecated APIs in use we can open individual issues for those and clean them up as needed going forwards.
