### ISSUE TITLE
In argparse, allow REMAINDER(...) arguments in a mutually exclusive group

### ISSUE THREAD

**Issue by 0e54783b-c1ca-43c7-aeec-62ac4fe9cdda** [python/cpython#84689]
BPO | [40509](https://bugs.python.org/issue40509)
--- | :---
Nosy | @rhettinger, @taleinat, @shaniarmon
PRs | <li>python/cpython#19919</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-05.10:30:44.470>
labels = ['type-bug', 'library', '3.9']
title = 'In argparse, allow REMAINDER(...) arguments in a mutually exclusive group'
updated_at = <Date 2020-10-18.01:48:44.194>
user = 'https://github.com/shaniarmon'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-18.01:48:44.194>
actor = 'paul.j3'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-05.10:30:44.470>
creator = 'Shani Armon'
dependencies = []
files = []
hgrepos = []
issue_num = 40509
keywords = ['patch']
message_count = 9.0
messages = ['368126', '368213', '368227', '368282', '368284', '368323', '369333', '378833', '378845']
nosy_count = 4.0
nosy_names = ['rhettinger', 'taleinat', 'paul.j3', 'Shani Armon']
pr_nums = ['19919']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40509'
versions = ['Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
> Options specified with the REMAINDER nargs should be treated as optional.

Done in #124307.

> And an empty list should be treated as default.

An empty list is now treated as default for REMAINDER. Done in #124306.

Is it what you wanted, @shaniarmon? There are no examples or tests, so I am not sure.
