### ISSUE TITLE
[subinterpreters] Add --experimental-isolated-subinterpreters build option

### ISSUE THREAD

**Issue by vstinner** [python/cpython#84694]
BPO | [40514](https://bugs.python.org/issue40514)
--- | :---
Nosy | @vstinner, @ericsnowcurrently, @corona10
PRs | <li>python/cpython#19926</li><li>python/cpython#20228</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-31.22:59:17.920>
created_at = <Date 2020-05-05.13:13:51.880>
labels = ['expert-subinterpreters', 'build', '3.10']
title = '[subinterpreters] Add --experimental-isolated-subinterpreters build option'
updated_at = <Date 2020-10-31.22:59:17.920>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-31.22:59:17.920>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2020-10-31.22:59:17.920>
closer = 'vstinner'
components = ['Build', 'Subinterpreters']
creation = <Date 2020-05-05.13:13:51.880>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 40514
keywords = ['patch']
message_count = 6.0
messages = ['368141', '368156', '368159', '368172', '369401', '370745']
nosy_count = 3.0
nosy_names = ['vstinner', 'eric.snow', 'corona10']
pr_nums = ['19926', '20228']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue40514'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-93185

**Comment by erlend-aasland** [comment]
> Reopened for #93185

Why do you need to reopen it? The title says "add --experimental-isolated-subinterpreters build option". If you are to remove it, it can be done in the new issue, no?

**Comment by kumaraditya303** [comment]
I reopened it as #93185 uses this issue in title, if that PR will use a new issue, this can be closed.

**Comment by erlend-aasland** [comment]
Use #93185 for the removal; there is no need for this to be reopened.
