### ISSUE TITLE
GCC 9 compiler warnings on MacOS Catalina

### ISSUE THREAD

**Issue by 23982c60-ed6c-47d1-96c2-69d417bd81b3** [python/cpython#84696]
BPO | [40516](https://bugs.python.org/issue40516)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @remilapeyre
PRs | <li>python/cpython#19925</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-05.13:32:24.115>
labels = ['OS-mac', 'type-bug', '3.9', 'build']
title = 'GCC 9 compiler warnings on MacOS Catalina'
updated_at = <Date 2020-05-06.01:35:47.989>
user = 'https://github.com/remilapeyre'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-06.01:35:47.989>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'macOS']
creation = <Date 2020-05-05.13:32:24.115>
creator = 'remi.lapeyre'
dependencies = []
files = []
hgrepos = []
issue_num = 40516
keywords = ['patch']
message_count = 2.0
messages = ['368146', '368221']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'remi.lapeyre']
pr_nums = ['19925']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40516'
versions = ['Python 3.9']
```

</p></details>

**Comment by hugovk** [comment]
Note the nis module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by erlend-aasland** [comment]
I believe the warnings in posixmodule.c was fixed in gh-22855 (see https://github.com/python/cpython/pull/19925#discussion_r510758649)

Since the remaining warnings belong to the nis module, I suggest to close this issue.

**Comment by AA-Turner** [comment]
Closing per Erlend, it's been several days with no comments to the contrary.

A
