### ISSUE TITLE
Python 3.8.2 Mac freezing/not responding when saving new programs

### ISSUE THREAD

**Issue by 1c1f6bcc-e041-4ff6-a103-ba6da74c5729** [python/cpython#84733]
BPO | [40553](https://bugs.python.org/issue40553)
--- | :---
Nosy | @rhettinger, @terryjreedy, @ned-deily
Files | <li>[Screen Shot 2020-05-07 at 3.46.02 PM.png](https://bugs.python.org/file49139/Screen%20Shot%202020-05-07%20at%203.46.02%20PM.png "Uploaded as image/png at 2020-05-07.23:26:24 by Zain")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2020-05-07.20:55:32.906>
labels = ['expert-IDLE', '3.8', '3.9', 'type-crash']
title = 'Python 3.8.2 Mac freezing/not responding when saving new programs'
updated_at = <Date 2020-08-27.18:58:48.970>
user = 'https://bugs.python.org/Zain'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-27.18:58:48.970>
actor = 'aboeckmann'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2020-05-07.20:55:32.906>
creator = 'Zain'
dependencies = []
files = ['49139']
hgrepos = []
issue_num = 40553
keywords = []
message_count = 23.0
messages = ['368375', '368380', '368381', '368385', '368386', '368387', '368418', '368475', '368483', '368485', '368488', '368489', '368493', '368568', '368648', '368650', '368662', '368698', '375130', '375395', '375654', '375714', '376012']
nosy_count = 6.0
nosy_names = ['rhettinger', 'terry.reedy', 'ned.deily', 'Zain', 'franksj', 'aboeckmann']
pr_nums = []
priority = 'high'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue40553'
versions = ['Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
> So over the past week the issue resolved its self. I unfortunately did not get a video or a screenshot but thought you might want to know this
So maybe Apple did something or you guys fixed it. Anyways, have a good day!

Closing as it seems resolved as per comment above, feel free to reopen if required.
