### ISSUE TITLE
asyncio.StreadReader     `async for line in reader` is not documented

### ISSUE THREAD

**Issue by 01e27b45-90f2-4c74-9e5e-7e7e54c3d78e** [python/cpython#84747]
BPO | [40567](https://bugs.python.org/issue40567)
--- | :---
Nosy | @asvetlov, @socketpair, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-08.18:51:03.374>
labels = ['3.8', 'docs', '3.7', '3.9', 'expert-asyncio']
title = 'asyncio.StreadReader     `async for line in reader` is not documented'
updated_at = <Date 2020-05-08.18:51:13.351>
user = 'https://github.com/socketpair'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-08.18:51:13.351>
actor = 'socketpair'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'asyncio']
creation = <Date 2020-05-08.18:51:03.374>
creator = 'socketpair'
dependencies = []
files = []
hgrepos = []
issue_num = 40567
keywords = []
message_count = 1.0
messages = ['368453']
nosy_count = 4.0
nosy_names = ['asvetlov', 'docs@python', 'socketpair', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40567'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by slateny** [comment]
@socketpair Could you expand a bit on what works and what needs documenting? Is it that you're looking to get a link to the `async for` syntax, like say [here](https://docs.python.org/3/reference/compound_stmts.html#async-for) and [here](https://peps.python.org/pep-0492/#asynchronous-iterators-and-async-for)?

**Comment by kumaraditya303** [comment]
Just add a line in docs that it supports the async iterable protocol with a link.

**Comment by kumaraditya303** [comment]
@slateny Can you create a PR for this?
