### ISSUE TITLE
Copy property return annotations to __annotations__

### ISSUE THREAD

**Issue by b8d71def-6676-4c9e-9ea7-b05ffc11bbcb** [python/cpython#84786]
BPO | [40606](https://bugs.python.org/issue40606)
--- | :---
Nosy | @eric-wieser, @ilevkivskyi
PRs | <li>python/cpython#20052</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-12.09:11:47.151>
labels = ['3.7', '3.8', 'type-feature', 'library', '3.9']
title = 'Copy property return annotations to __annotations__'
updated_at = <Date 2020-05-15.21:04:13.252>
user = 'https://bugs.python.org/EricWieser'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-15.21:04:13.252>
actor = 'levkivskyi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-12.09:11:47.151>
creator = 'Eric Wieser'
dependencies = []
files = []
hgrepos = []
issue_num = 40606
keywords = ['patch']
message_count = 1.0
messages = ['368710']
nosy_count = 3.0
nosy_names = ['Eric.Wieser', 'levkivskyi', 'Eric Wieser']
pr_nums = ['20052']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40606'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
`property` and `cached_property` objects are not callables, they are descriptors. Does it make sense to set `__annotations__` for them?

Also, would setting an item in the `__annotations__` dict of the class help with this issue?

**Comment by JelleZijlstra** [comment]
I don't think we should do this. `__annotations__` is a low-level feature that should reflect the annotations the user actually wrote in the class. If tools want to also incorporate properties or other logic, they should rely on a higher-level tool that incorporates more logic.
