### ISSUE TITLE
slice not hashable

### ISSUE THREAD

**Issue by 5c9e5139-1698-4d50-852a-b3fcb55f7bda** [python/cpython#84783]
BPO | [40603](https://bugs.python.org/issue40603)
--- | :---
Nosy | @rhettinger, @stevendaprano, @remilapeyre, @isdanni
Files | <li>[patches.zip](https://bugs.python.org/file49149/patches.zip "Uploaded as application/x-zip-compressed at 2020-05-12.01:23:38 by Will Bradshaw"): patch to add slicing functionality to slices</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-12.01:23:39.253>
labels = ['interpreter-core', 'easy', 'type-feature', '3.9']
title = 'slice not hashable'
updated_at = <Date 2020-05-12.08:34:03.335>
user = 'https://bugs.python.org/WillBradshaw'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-12.08:34:03.335>
actor = 'remi.lapeyre'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-05-12.01:23:39.253>
creator = 'Will Bradshaw'
dependencies = []
files = ['49149']
hgrepos = []
issue_num = 40603
keywords = ['easy (C)']
message_count = 5.0
messages = ['368693', '368694', '368696', '368700', '368708']
nosy_count = 5.0
nosy_names = ['rhettinger', 'steven.daprano', 'remi.lapeyre', 'isdanni', 'Will Bradshaw']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40603'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-101264
* gh-102548
* gh-103146

**Comment by gvanrossum** [comment]
I think this is fine. The "danger" of d[a:b] seems overstated, it produces a clear KeyError.

**Comment by rhettinger** [comment]
@gvanrossum Thanks for the looking at this.

**Comment by gvanrossum** [comment]
Note that this still needs a “what’s new” entry, since it is a new feature and might even trip some folks up (see the test changes needed).

**Comment by Yhg1s** [comment]
GH-102548 adds the missing What's New entry.

**Comment by hauntsaninja** [comment]
What's New was merged, so I think this can be closed

**Comment by asmeurer** [comment]
Thank you for fixing this. 

For anyone who was wanting hashable slices, my library [ndindex](https://github.com/Quansight-Labs/ndindex) may be of interest. It has a hashable `Slice` object but it also does a lot more like slice arithmetic which may be useful for a lot of the use cases described here.
