### ISSUE TITLE
sockmodule.c: sock_connect vs negative errno values...

### ISSUE THREAD

**Issue by 1c1e7887-0de8-4060-96cf-64093562907a** [python/cpython#84808]
BPO | [40628](https://bugs.python.org/issue40628)
--- | :---
Nosy | @rcgordon

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-14.18:55:16.943>
labels = ['extension-modules', 'type-bug', '3.7']
title = 'sockmodule.c: sock_connect vs negative errno values...'
updated_at = <Date 2020-05-14.18:55:16.943>
user = 'https://github.com/rcgordon'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-14.18:55:16.943>
actor = 'icculus'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules']
creation = <Date 2020-05-14.18:55:16.943>
creator = 'icculus'
dependencies = []
files = []
hgrepos = []
issue_num = 40628
keywords = []
message_count = 1.0
messages = ['368863']
nosy_count = 1.0
nosy_names = ['icculus']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40628'
versions = ['Python 3.7']
```

</p></details>

### Linked PRs
* gh-122304

**Comment by iritkatriel** [comment]
Since Haiku is not a supported platform, I'm relabelling this from bug to feature request.  I don't know how likely it is that it will be implemented though, there would need to be a core developer who cares enough about Haiku to do something non-standard for it (an assess what the implications of that may be).

**Comment by encukou** [comment]
IMO, Python should not assume that errno codes are positive. The point of PEP-11 is to not maintain speedups/workarounds for niche platforms, not to overfit CPython to rely on quirks of the tiered platforms.
To me, this is a legitimate bug, though one that core devs won't fix alone, and might not prioritize.

Please send the PR. Considering the ramifications of the change is the reviewer's job.

**Comment by erlend-aasland** [comment]
I agree with Petr; this definitely sounds like a bug, not a feature.

**Comment by encukou** [comment]
Thank you `rcgordon` for the report, and @korli for the fix!
