### ISSUE TITLE
Ignored "BlockingIOError: [Errno 11] Resource temporarily unavailable" are still haunting us

### ISSUE THREAD

**Issue by 7745f73f-ed04-4a84-af90-687378334bb0** [python/cpython#84814]
BPO | [40634](https://bugs.python.org/issue40634)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-15.15:30:02.322>
labels = ['3.7', '3.8', 'expert-asyncio']
title = 'Ignored "BlockingIOError: [Errno 11] Resource temporarily unavailable" are still haunting us'
updated_at = <Date 2020-06-15.12:50:39.417>
user = 'https://bugs.python.org/YaroslavHalchenko'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-15.12:50:39.417>
actor = 'Yaroslav.Halchenko'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-05-15.15:30:02.322>
creator = 'Yaroslav.Halchenko'
dependencies = []
files = []
hgrepos = []
issue_num = 40634
keywords = []
message_count = 2.0
messages = ['368953', '371540']
nosy_count = 3.0
nosy_names = ['asvetlov', 'Yaroslav.Halchenko', 'yselivanov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40634'
versions = ['Python 3.5', 'Python 3.6', 'Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
I am not sure we can do anything about this as there is no reproducer. I can only suggest you to use `asyncio.PidfdChildWatcher` which can handle a lot of subprocesses on Linux.  Also Andrew commented that this does not happen on 3.8+ https://github.com/python/cpython/issues/82285#issuecomment-1093841204 so closing. 

Create a new issue with reproducer if this is still an issue on supported Python versions.

**Comment by gvanrossum** [comment]
I believe the OP is @yarikoptic.

Question for OP: does this still occur on more recent versions? Could you try Kumar's suggestion and report back?

We are aware that child process exit handling in asyncio is imperfect. See e.g. https://github.com/python/cpython/issues/94597.

**Comment by kumaraditya303** [comment]
> I believe the OP is @yarikoptic.

Oh, I tried the same GitHub username `YaroslavHalchenko` but there was no account hence I closed.

**Comment by kumaraditya303** [comment]
FTR before closing I tried the script posted in https://github.com/python/cpython/issues/82285 and I was only able to reproduce this on 3.7 which is EOL and not on 3.8+.

**Comment by gvanrossum** [comment]
> Oh, I tried the same GitHub username `YaroslavHalchenko` but there was no account hence I closed.

I found it by using GitHub search, clicking on the 4 user results, and going through all of them. Only one had significant activity, and they had "datalad" in their user description, so I figured that was the OP. :-)

In other cases I've used bpo user list search, but I don't know if you have access to that. In this case there was no GH username.

> FTR before closing I tried the script posted in #82285 and I was only able to reproduce this on 3.7 which is EOL and not on 3.8+.

The problem seems due to processes exiting faster than what the watcher can keep up, and since the OP acknowledged that *some* relieve was provided by 3.8, I imagine it's hard to repro.

**Comment by kumaraditya303** [comment]
> I found it by using GitHub search, clicking on the 4 user results, and going through all of them. Only one had significant activity, and they had "datalad" in their user description, so I figured that was the OP. :-)

Ok, hit and trial :)


> The problem seems due to processes exiting faster than what the watcher can keep up, and since the OP acknowledged that some relieve was provided by 3.8, I imagine it's hard to repro.

Yes, hence I suggested to use `asyncio.PidfdChildWatcher` which can handle a lot of subprocesses since it does not uses wakeup fd  mechanism.

**Comment by yarikoptic** [comment]
> I believe the OP is @yarikoptic.

FWIW
- confirming that YaroslavHalchenko on https://bugs.python.org/issue40634 is me.
- original issue is no longer "pressing" for us since we moved back to non-asyncio implementation of subprocesses execution.

**Comment by gvanrossum** [comment]
Thanks! Then I'll close this issue, given that we already know child watchers aren't optimal.
