### ISSUE TITLE
remove deprecated urllib.request.URLopener/FancyURLopener

### ISSUE THREAD

**Issue by 59a8ee24-f981-4c4d-a554-2e074101e387** [python/cpython#84850]
BPO | [40673](https://bugs.python.org/issue40673)
--- | :---
Nosy | @vstinner, @PetterS, @remilapeyre, @idomic

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-18.21:30:13.142>
labels = ['type-feature', 'library', '3.11']
title = 'remove deprecated urllib.request.URLopener/FancyURLopener'
updated_at = <Date 2021-11-23.13:31:04.736>
user = 'https://github.com/PetterS'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-23.13:31:04.736>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-18.21:30:13.142>
creator = 'Petter S'
dependencies = []
files = []
hgrepos = []
issue_num = 40673
keywords = []
message_count = 7.0
messages = ['369291', '369293', '369294', '369295', '369300', '369886', '406839']
nosy_count = 4.0
nosy_names = ['vstinner', 'Petter S', 'remi.lapeyre', 'Ido Michael']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40673'
versions = ['Python 3.11']
```

</p></details>

### Linked PRs
* gh-125739
* gh-127032

**Comment by hugovk** [comment]
They've been removed in https://github.com/python/cpython/pull/125739.

TODO:

> I think that we should provide some hints on how to replace code using removed APIs. Give some examples maybe?

https://github.com/python/cpython/pull/125739#discussion_r1840477094

**Comment by barneygale** [comment]
`urllib.request.URLopener` and `FancyURLopener` are [removed in Python 3.14](https://docs.python.org/3.14/whatsnew/3.14.html#removed). Thanks all.
