### ISSUE TITLE
Deprecate urllib.request.urlretrieve() and cleanup()

### ISSUE THREAD

**Issue by 23982c60-ed6c-47d1-96c2-69d417bd81b3** [python/cpython#84851]
BPO | [40674](https://bugs.python.org/issue40674)
--- | :---
Nosy | @remilapeyre, @iritkatriel
PRs | <li>python/cpython#20197</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-18.22:39:16.420>
labels = ['type-bug', 'library']
title = 'Deprecate urllib.request.urlretrieve() and cleanup()'
updated_at = <Date 2022-01-24.00:26:20.803>
user = 'https://github.com/remilapeyre'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-24.00:26:20.803>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-18.22:39:16.420>
creator = 'remi.lapeyre'
dependencies = []
files = []
hgrepos = []
issue_num = 40674
keywords = ['patch']
message_count = 1.0
messages = ['411433']
nosy_count = 2.0
nosy_names = ['remi.lapeyre', 'iritkatriel']
pr_nums = ['20197']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40674'
versions = []
```

</p></details>

**Comment by rhettinger** [comment]
FWIW, I and some of my customers use *urlretrieve* on a regular basis.  It is one of the basics of automating work flows.   Without it, we should probably use subprocess to call curl or wget.

I vote against deprecation unless the function is known to be broken in some unfixable way.
