### ISSUE TITLE
Add support for SQLITE_DIRECTONLY and SQLITE_INNOCUOUS for user-defined functions

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#84943]
BPO | [40766](https://bugs.python.org/issue40766)
--- | :---
Nosy | @erlend-aasland
PRs | <li>python/cpython#20398</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-05-25.11:13:46.593>
labels = ['3.8', 'library', '3.9', '3.10']
title = 'Add support for SQLITE_DIRECTONLY and SQLITE_INNOCUOUS for user-defined functions'
updated_at = <Date 2020-05-25.20:52:22.374>
user = 'https://github.com/erlend-aasland'
```

bugs.python.org fields:
```python
activity = <Date 2020-05-25.20:52:22.374>
actor = 'erlendaasland'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-05-25.11:13:46.593>
creator = 'erlendaasland'
dependencies = []
files = []
hgrepos = []
issue_num = 40766
keywords = ['patch']
message_count = 1.0
messages = ['369871']
nosy_count = 1.0
nosy_names = ['erlendaasland']
pr_nums = ['20398']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40766'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
I'm closing this; there has been no other requests for such features, and there has been no response to this ticket. If the need for these flags arises, we can reopen, or create a new issue.

**Comment by jbosboom** [comment]
Requesting reopen.  I'm using triggers to keep multiple [full-text search tables](https://sqlite.org/fts5.html) in sync with each other and with the content tables, and I want to use a str -> str Python function in the body of those triggers, which requires marking it innocuous or giving up [trusted_schema](https://sqlite.org/pragma.html#pragma_trusted_schema) protection.  I wouldn't normally request this given no one else has asked for it in years, but [trusted_schema is a security feature](https://sqlite.org/appfunc.html#security_implications), so I think it merits supporting in the standard library.  I updated your PR.
