### ISSUE TITLE
Misleading line in documentation

### ISSUE THREAD

**Issue by 0c1348ce-3c0b-4d38-884a-b84a22e91ad5** [python/cpython#85023]
BPO | [40846](https://bugs.python.org/issue40846)
--- | :---
Nosy | @DimitrisJim, @remilapeyre, @J-Arun-Mani
PRs | <li>python/cpython#20602</li><li>python/cpython#20603</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-02.18:23:09.969>
labels = ['docs']
title = 'Misleading line in documentation'
updated_at = <Date 2020-06-03.08:43:18.178>
user = 'https://github.com/J-Arun-Mani'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-03.08:43:18.178>
actor = 'J Arun Mani'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-06-02.18:23:09.969>
creator = 'J Arun Mani'
dependencies = []
files = []
hgrepos = []
issue_num = 40846
keywords = ['patch']
message_count = 4.0
messages = ['370616', '370622', '370624', '370647']
nosy_count = 4.0
nosy_names = ['docs@python', 'Jim Fasarakis-Hilliard', 'remi.lapeyre', 'J Arun Mani']
pr_nums = ['20602', '20603']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40846'
versions = []
```

</p></details>

**Comment by iritkatriel** [comment]
@arun-mani-j Would you like to complete this as per the review comment in https://github.com/python/cpython/pull/20602#discussion_r434399926 ?

**Comment by arun-mani-j** [comment]
@iritkatriel I have made a PR #94282 please check if it needs any modification :)
