### ISSUE TITLE
Update Windows build to use xz-5.2.5

### ISSUE THREAD

**Issue by b8e5a65c-bed4-4c5d-ba32-799f883ba638** [python/cpython#85036]
BPO | [40859](https://bugs.python.org/issue40859)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @animalize
PRs | <li>python/cpython#20622</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-04.02:41:03.855>
labels = ['3.10', '3.9', 'OS-windows']
title = 'Update Windows build to use xz-5.2.5'
updated_at = <Date 2020-06-04.02:44:37.373>
user = 'https://github.com/animalize'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-04.02:44:37.373>
actor = 'malin'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2020-06-04.02:41:03.855>
creator = 'malin'
dependencies = []
files = []
hgrepos = []
issue_num = 40859
keywords = ['patch']
message_count = 1.0
messages = ['370693']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'malin']
pr_nums = ['20622']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40859'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by gpshead** [comment]
this seem useful, but apparently something more than what is in that PR needs to be done for it to work.

**Comment by scw** [comment]
This looks like it was fixed in a few weeks after this issue was logged in the reported 3.9 and 3.10 versions on Windows.
