### ISSUE TITLE
Add PYTHONLOGGING environment variable and -L cmdline argument

### ISSUE THREAD

**Issue by 9326c04b-4d37-4a35-bdd5-d40f5f681a02** [python/cpython#85063]
BPO | [40886](https://bugs.python.org/issue40886)
--- | :---
Nosy | @vsajip, @bharel

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-06.01:11:59.053>
labels = ['type-feature', 'library', '3.10']
title = 'Add PYTHONLOGGING environment variable and -L cmdline argument'
updated_at = <Date 2020-06-06.01:24:26.960>
user = 'https://github.com/bharel'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-06.01:24:26.960>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-06-06.01:11:59.053>
creator = 'bar.harel'
dependencies = []
files = []
hgrepos = []
issue_num = 40886
keywords = []
message_count = 1.0
messages = ['370807']
nosy_count = 2.0
nosy_names = ['vinay.sajip', 'bar.harel']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40886'
versions = ['Python 3.10']
```

</p></details>

**Comment by vsajip** [comment]
I don't believe that this should be done system-wide. Those that need it can implement it for their scripts using `argparse`, as suggested in the discussion thread. This allows each script to do any necessary configuration based on the command line arguments, and a one-size-fits-all in the stdlif for this wouldn't be a good idea.
