### ISSUE TITLE
Add documentation for asyncio._set_running_loop()

### ISSUE THREAD

**Issue by 5a962246-c85a-4fde-8b2f-ce5105de0dfc** [python/cpython#85134]
BPO | [40962](https://bugs.python.org/issue40962)
--- | :---
Nosy | @asvetlov, @1st1

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-12.15:42:17.397>
labels = ['3.11', 'type-feature', 'docs']
title = 'Add documentation for asyncio._set_running_loop()'
updated_at = <Date 2022-01-16.08:05:35.818>
user = 'https://bugs.python.org/eugenhu'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-16.08:05:35.818>
actor = 'kumaraditya'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-06-12.15:42:17.397>
creator = 'eugenhu'
dependencies = []
files = []
hgrepos = []
issue_num = 40962
keywords = []
message_count = 1.0
messages = ['371387']
nosy_count = 4.0
nosy_names = ['asvetlov', 'docs@python', 'yselivanov', 'eugenhu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue40962'
versions = ['Python 3.11']
```

</p></details>

**Comment by kumaraditya303** [comment]
The URL points to the old asyncio repo https://github.com/python/asyncio/pull/452. FWIW I consider `asyncio._set_running_loop` to be private as it is used internally by `asyncio`, not something users have to use.

cc @gvanrossum

**Comment by gvanrossum** [comment]
If one were to implement one's own event loop (without calling `asyncio.BaseEventLoop.run_forever()`) one would have to use this. I don't know if we have a place where we document things for event loop authors though. And people could just read the source -- the code of `run_forever()` is pretty clear. So let's just close this.
