### ISSUE TITLE
group names of bytes regexes are strings

### ISSUE THREAD

**Issue by eb006bff-6714-463f-a4ef-e8b24105f1cb** [python/cpython#85152]
BPO | [40980](https://bugs.python.org/issue40980)
--- | :---
Nosy | @animalize, @qwenger

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-14.21:03:34.705>
labels = ['expert-regex', 'type-bug', '3.8']
title = 'group names of bytes regexes are strings'
updated_at = <Date 2020-06-17.08:20:57.392>
user = 'https://github.com/qwenger'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-17.08:20:57.392>
actor = 'matpi'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Regular Expressions']
creation = <Date 2020-06-14.21:03:34.705>
creator = 'matpi'
dependencies = []
files = []
hgrepos = []
issue_num = 40980
keywords = []
message_count = 27.0
messages = ['371516', '371607', '371614', '371629', '371631', '371633', '371634', '371637', '371638', '371639', '371643', '371644', '371646', '371652', '371657', '371660', '371672', '371676', '371681', '371692', '371696', '371697', '371705', '371709', '371718', '371719', '371720']
nosy_count = 2.0
nosy_names = ['malin', 'matpi']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue40980'
versions = ['Python 3.8']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
Latin1 Is an implementation detail of the RE parser. There is no deep meaning in this.

Group names are purposed to be human-readable. This is why they are limited to be identifiers. Non-ASCII characters in bytes pattern are not human-readable. I think we should only allow ASCII-only identifiers as group names in bytes patterns. The question is whether it needs a deprecation period?

**Comment by serhiy-storchaka** [comment]
Close this issue as "not a bug". See #91760 for more strict rules which can eliminate confusion.
