### ISSUE TITLE
singledispatchmethod significantly slower than singledispatch

### ISSUE THREAD

**Issue by 11d680f0-a6c3-43c3-85b1-a0046e9a2fd9** [python/cpython#85160]
BPO | [40988](https://bugs.python.org/issue40988)
--- | :---
Nosy | @mental32, @CaselIT
PRs | <li>python/cpython#23213</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-15.20:14:13.251>
labels = ['3.8', 'library', 'performance']
title = 'singledispatchmethod significantly slower than singledispatch'
updated_at = <Date 2020-11-10.05:12:05.587>
user = 'https://github.com/CaselIT'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-10.05:12:05.587>
actor = 'mental'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-06-15.20:14:13.251>
creator = 'CaselIT'
dependencies = []
files = []
hgrepos = []
issue_num = 40988
keywords = ['patch']
message_count = 1.0
messages = ['371594']
nosy_count = 2.0
nosy_names = ['mental', 'CaselIT']
pr_nums = ['23213']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue40988'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-106448
* gh-107148
* gh-107706
* gh-127751

**Comment by iritkatriel** [comment]
I see a similar time difference on main.

**Comment by AlexWaygood** [comment]
https://github.com/python/cpython/pull/107148 significantly optimised `@singledispatchmethod` for all non-slotted classes. If anybody can think of further optimisations that can be safely applied, I suggest a new issue should be opened for them.

Thanks @CasselT for the report, and thanks @mental32 and @eendebakpt for working on this!
