### ISSUE TITLE
Wrong warning in asyncio debug mode

### ISSUE THREAD

**Issue by b518d368-1073-48e4-9ec7-1e7e5703ef2f** [python/cpython#85164]
BPO | [40992](https://bugs.python.org/issue40992)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[asyncio-wrong-warn.py](https://bugs.python.org/file49237/asyncio-wrong-warn.py "Uploaded as text/plain at 2020-06-16.14:14:39 by Alex Alex")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-16.14:14:39.250>
labels = ['3.7', 'expert-asyncio']
title = 'Wrong warning in asyncio debug mode'
updated_at = <Date 2020-06-16.14:14:39.250>
user = 'https://bugs.python.org/AlexAlex'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-16.14:14:39.250>
actor = 'Alex Alex'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-06-16.14:14:39.250>
creator = 'Alex Alex'
dependencies = []
files = ['49237']
hgrepos = []
issue_num = 40992
keywords = []
message_count = 1.0
messages = ['371659']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'Alex Alex']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue40992'
versions = ['Python 3.7']
```

</p></details>

**Comment by willingc** [comment]
Closing this as related to an EOL version and likely improved with the timing work done since the 3.7 release.
