### ISSUE TITLE
smtplib does not handle Unicode characters

### ISSUE THREAD

**Issue by 9ef04b82-9615-4133-929b-112b12f1eee1** [python/cpython#85195]
BPO | [41023](https://bugs.python.org/issue41023)
--- | :---
Nosy | @warsaw, @bitdancer
Files | <li>[send_rawemail_demo.py](https://bugs.python.org/file49249/send_rawemail_demo.py "Uploaded as text/plain at 2020-06-18.09:45:33 by jpatel")</li><li>[providing_Unicode_characters_in_email_body.png](https://bugs.python.org/file49251/providing_Unicode_characters_in_email_body.png "Uploaded as image/png at 2020-06-18.09:50:41 by jpatel")</li><li>[providing_mail_options_in_sendmail.png](https://bugs.python.org/file49252/providing_mail_options_in_sendmail.png "Uploaded as image/png at 2020-06-18.09:50:58 by jpatel")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-06-18.12:51:03.989>
created_at = <Date 2020-06-18.09:45:34.374>
labels = ['type-feature', '3.8', 'expert-email']
title = 'smtplib does not handle Unicode characters'
updated_at = <Date 2020-06-29.10:24:36.777>
user = 'https://bugs.python.org/jpatel'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-29.10:24:36.777>
actor = 'jpatel'
assignee = 'none'
closed = True
closed_date = <Date 2020-06-18.12:51:03.989>
closer = 'r.david.murray'
components = ['email']
creation = <Date 2020-06-18.09:45:34.374>
creator = 'jpatel'
dependencies = []
files = ['49249', '49251', '49252']
hgrepos = []
issue_num = 41023
keywords = []
message_count = 3.0
messages = ['371801', '371803', '371808']
nosy_count = 3.0
nosy_names = ['barry', 'r.david.murray', 'jpatel']
pr_nums = []
priority = 'normal'
resolution = 'works for me'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41023'
versions = ['Python 3.8']
```

</p></details>

**Comment by torzsmokus** [comment]
For the record, I got this error when my hostname happened to contain non-ascii characters (and smtplib tried to include that literally in the header)
