### ISSUE TITLE
Multiprocesing Pool borken on macOS REPL

### ISSUE THREAD

**Issue by eadbd4d3-cbb4-42b8-8420-9f80dcde2bcc** [python/cpython#85213]
BPO | [41041](https://bugs.python.org/issue41041)
--- | :---
Nosy | @ericvsmith, @Carreau, @tirkarthi

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-19.21:00:05.901>
labels = ['type-bug']
title = 'Multiprocesing Pool borken on macOS REPL'
updated_at = <Date 2020-06-20.05:29:16.706>
user = 'https://github.com/Carreau'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-20.05:29:16.706>
actor = 'xtreak'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-06-19.21:00:05.901>
creator = 'mbussonn'
dependencies = []
files = []
hgrepos = []
issue_num = 41041
keywords = []
message_count = 5.0
messages = ['371900', '371906', '371916', '371917', '371918']
nosy_count = 3.0
nosy_names = ['eric.smith', 'mbussonn', 'xtreak']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41041'
versions = []
```

</p></details>

**Comment by ronaldoussoren** [comment]
#77734 is an issue that proposed to add an ``if __name__ == "__main__"`` test to some examples, but that obviously doesn't help with the REPL.  The documentation already mentions that examples won't work in the interactive interpreter (although only in [a note in the section about multiprocessing.Pool](https://docs.python.org/3/library/multiprocessing.html#using-a-pool-of-workers) and not explicitly in the [programming guidelines](https://docs.python.org/3/library/multiprocessing.html#programming-guidelines).

Is there anything actionable to do for this issue?   ``multiprocessing`` works as designed here and the documentation does mention this gotcha.

**Comment by ronaldoussoren** [comment]
I'm closing this issue because AFAIK there's nothing left to do here (see my previous message).
