### ISSUE TITLE
open() fails to read app exec links

### ISSUE THREAD

**Issue by 6475b3bd-9876-4c35-9df5-7935b61953f4** [python/cpython#85225]
BPO | [41053](https://bugs.python.org/issue41053)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @saschanaz

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-20.15:14:53.545>
labels = ['type-bug', '3.8', 'OS-windows']
title = 'open() fails to read app exec links'
updated_at = <Date 2020-06-22.02:27:27.806>
user = 'https://github.com/saschanaz'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-22.02:27:27.806>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Windows']
creation = <Date 2020-06-20.15:14:53.545>
creator = 'saschanaz'
dependencies = []
files = []
hgrepos = []
issue_num = 41053
keywords = []
message_count = 4.0
messages = ['371939', '371963', '371969', '372028']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'saschanaz']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41053'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
@eryksun Thanks for the explanations.  Is there anything here to do in Python, so shall we close the issue?

**Comment by zooba** [comment]
Up until Microsoft decides to either make them act like normal files or to publicly document how to work with them, there's nothing for us to do here.
