### ISSUE TITLE
Avoid using the locale encoding for open() in tests

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#85235]
BPO | [41063](https://bugs.python.org/issue41063)
--- | :---
Nosy | @vstinner, @methane, @serhiy-storchaka
Dependencies | <li>bpo-41048: read_mime_types() should read the rule file using UTF-8, not the locale encoding</li><li>bpo-41055: Remove outdated tests for tp_print</li><li>bpo-41058: pdb reads source files using the locale encoding</li><li>bpo-41069: Use non-ascii file names in tests by default</li><li>gh-85308: argparse uses default encoding when read arguments from file</li><li>bpo-41137: pdb uses the locale encoding for .pdbrc</li><li>bpo-41138: trace CLI reads source files using the locale encoding</li><li>bpo-41139: cgi uses the locale encoding for log files</li><li>bpo-41140: cgitb uses the locale encoding for log files</li><li>bpo-41143: distutils uses the locale encoding for the .pypirc file</li><li>gh-85322: pipes uses text files and the locale encodig</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-21.11:04:15.601>
labels = ['3.7', '3.8', '3.9', '3.10', 'type-feature', 'tests']
title = 'Avoid using the locale encoding for open() in tests'
updated_at = <Date 2020-06-28.16:23:08.646>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-28.16:23:08.646>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2020-06-21.11:04:15.601>
creator = 'serhiy.storchaka'
dependencies = ['41048', '41055', '41058', '41069', '41136', '41137', '41138', '41139', '41140', '41143', '41150']
files = []
hgrepos = []
issue_num = 41063
keywords = []
message_count = 1.0
messages = ['371994']
nosy_count = 3.0
nosy_names = ['vstinner', 'methane', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41063'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
You can use ``python -X warn_default_encoding`` to get a warning when open() is called without an explicit encoding.

@methane fixed many stdlib modules. I don't know the status of the test suite.

**Comment by vstinner** [comment]
All issues listed in this meta-issues have been fixed. I close the issue.
