### ISSUE TITLE
Exclude __pycache__ directories from backups using CACHEDIR.TAG

### ISSUE THREAD

**Issue by e1cead32-4084-4b7e-a521-93555dbdc563** [python/cpython#85253]
BPO | [41081](https://bugs.python.org/issue41081)
--- | :---
Nosy | @ericvsmith, @jstasiak
PRs | <li>python/cpython#21060</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-22.19:39:42.956>
labels = ['type-feature', 'library', '3.10']
title = 'Exclude __pycache__ directories from backups using CACHEDIR.TAG'
updated_at = <Date 2020-06-22.20:54:25.799>
user = 'https://github.com/jstasiak'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-22.20:54:25.799>
actor = 'eric.smith'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-06-22.19:39:42.956>
creator = 'jstasiak'
dependencies = []
files = []
hgrepos = []
issue_num = 41081
keywords = ['patch']
message_count = 2.0
messages = ['372109', '372113']
nosy_count = 2.0
nosy_names = ['eric.smith', 'jstasiak']
pr_nums = ['21060']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41081'
versions = ['Python 3.10']
```

</p></details>

**Comment by brettcannon** [comment]
I'm not sure what I think about this. I get the desire, but the file isn't a standard either.

**Comment by merwok** [comment]
What are the downsides of doing this?

**Comment by jstasiak** [comment]
* Extra code to run at import-time, including IO -> in principle slower imports
* Extra code to maintain for the benefit of a set of users that may be considered too small to be worth it (people running backup software that supports this marker)
* Extra noise in the filesystem

It's not a standard in an RFC kind of sense but it's somewhat recognizable in the backup software world – I know that Borg, rustic and restic support it.

**Comment by RazerM** [comment]
Some other tools which follow this already are [mypy](https://github.com/python/mypy/blob/75b68fa2c0d32bd08b98b00aece20c22d82b1b15/mypy/build.py#L1193-L1208), [pytest](https://github.com/pytest-dev/pytest/blob/a6708b92542eb886d3ba7b809213b2068a7988a6/src/_pytest/cacheprovider.py#L211-L212), [pipx](https://github.com/pypa/pipx/blob/f272651e35d4fe2b8f08226a9c451c6e5eda1590/src/pipx/main.py#L868-L878), [cargo (Rust)](https://github.com/rust-lang/cargo/blob/1cff2ee6b92e0ad3f87c44b70b28f788b2528b3c/crates/cargo-util/src/paths.rs#L720-L733).

I think it's a good idea, things like this are a real pain point when using backup software even the impact of `__pycache__` isn't particularly egregious.

**Comment by AA-Turner** [comment]
It doesn't seem to hurt, beyond the obvious "code to maintain" burden, and seems to have adoption as a _de facto_ standard, so I'd be +1. @jstasiak would you be able to benchmark if the difference of writing an additional file is noticeable for import time? If it has a measurable impact beyond the noise, we may consider an opt-out config setting for those who don't care about writing the file and want imports as fast as possible.

A

**Comment by jstasiak** [comment]
Yes, I'll try to run some tests.

**Comment by brettcannon** [comment]
So I brought this up on the core dev Discord server and either got objections or lukewarm reaction. The biggest sticking point is this is no way a standard and us doing this would make it a de-facto one.

As such, I'm afraid I need to close this until some standards body picks it up.
