### ISSUE TITLE
Support macOS 11 and Apple Silicon Macs

### ISSUE THREAD

**Issue by ronaldoussoren** [python/cpython#85272]
BPO | [41100](https://bugs.python.org/issue41100)
--- | :---
Nosy | @ronaldoussoren, @vstinner, @ned-deily, @skrah, @jmroot, @ambv, @jreese, @dirn, @mattip, @indygreg, @maxbelanger, @eamanu, @corona10, @isuruf, @miss-islington, @mistydemeo, @erlend-aasland, @nieder, @lawrence-danna-apple, @benoithudson, @harlantc
PRs | <li>python/cpython#21113</li><li>python/cpython#21153</li><li>python/cpython#21154</li><li>python/cpython#21155</li><li>python/cpython#21174</li><li>python/cpython#21175</li><li>python/cpython#21176</li><li>python/cpython#21224</li><li>python/cpython#21228</li><li>python/cpython#21239</li><li>python/cpython#21241</li><li>python/cpython#21242</li><li>python/cpython#21249</li><li>python/cpython#21266</li><li>python/cpython#21268</li><li>python/cpython#21564</li><li>python/cpython#21576</li><li>python/cpython#21577</li><li>python/cpython#21583</li><li>python/cpython#21588</li><li>python/cpython#22855</li><li>python/cpython#21114</li><li>python/cpython#21115</li><li>python/cpython#21246</li><li>python/cpython#23239</li><li>python/cpython#23280</li><li>python/cpython#23295</li><li>python/cpython#23293</li><li>python/cpython#23472</li><li>python/cpython#23480</li><li>python/cpython#23484</li><li>python/cpython#23485</li><li>python/cpython#23486</li><li>python/cpython#25014</li><li>python/cpython#25274</li><li>python/cpython#25806</li><li>python/cpython#25808</li><li>python/cpython#25809</li><li>python/cpython#26474</li>
Files | <li>[build.log](https://bugs.python.org/file49962/build.log "Uploaded as text/plain at 2021-04-15.15:38:57 by @harlantc"): build log for ARM M1 Big Sur</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ronaldoussoren'
closed_at = <Date 2021-05-02.21:13:19.655>
created_at = <Date 2020-06-24.11:51:07.053>
labels = ['OS-mac', 'build', '3.8', '3.9', '3.10']
title = 'Support macOS 11 and Apple Silicon Macs'
updated_at = <Date 2021-05-31.18:07:58.057>
user = 'https://github.com/ronaldoussoren'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-31.18:07:58.057>
actor = 'isuruf'
assignee = 'ronaldoussoren'
closed = True
closed_date = <Date 2021-05-02.21:13:19.655>
closer = 'ned.deily'
components = ['Build', 'macOS']
creation = <Date 2020-06-24.11:51:07.053>
creator = 'ronaldoussoren'
dependencies = []
files = ['49962']
hgrepos = []
issue_num = 41100
keywords = ['patch']
message_count = 43.0
messages = ['372245', '372371', '372374', '372375', '372376', '372456', '372457', '372458', '372652', '372672', '372680', '372716', '374315', '375532', '375572', '379230', '380538', '381091', '381097', '381585', '381608', '381640', '381701', '381702', '381708', '381709', '382932', '382939', '386664', '386740', '387526', '390505', '390561', '390562', '391138', '391141', '391142', '391146', '392675', '392680', '392682', '392683', '392734']
nosy_count = 24.0
nosy_names = ['ronaldoussoren', 'vstinner', 'ned.deily', 'skrah', 'jmr', 'lukasz.langa', 'jreese', 'python-dev', 'dirn', 'mattip', 'indygreg', 'Maxime Belanger', 'maxbelanger', 'eamanu', 'corona10', 'isuruf', 'miss-islington', 'mistydemeo', 'erlendaasland', 'nieder', 'lawrence-danna-apple', 'Mika_Hawkins', 'benoithudson', 'harlantc']
pr_nums = ['21113', '21153', '21154', '21155', '21174', '21175', '21176', '21224', '21228', '21239', '21241', '21242', '21249', '21266', '21268', '21564', '21576', '21577', '21583', '21588', '22855', '21114', '21115', '21246', '23239', '23280', '23295', '23293', '23472', '23480', '23484', '23485', '23486', '25014', '25274', '25806', '25808', '25809', '26474']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue41100'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by cclauss** [comment]
On Python < v3.8 see
* https://github.com/actions/setup-python/issues/856#issuecomment-2094346502
