### ISSUE TITLE
Add new formats to PyArg_ParseTuple for "str or None"

### ISSUE THREAD

**Issue by methane** [python/cpython#85339]
BPO | [41167](https://bugs.python.org/issue41167)
--- | :---
Nosy | @methane, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-30.09:03:42.484>
labels = ['expert-C-API', '3.10']
title = 'Add new formats to PyArg_ParseTuple for "str or None"'
updated_at = <Date 2020-06-30.09:18:22.615>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2020-06-30.09:18:22.615>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-06-30.09:03:42.484>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 41167
keywords = []
message_count = 2.0
messages = ['372670', '372674']
nosy_count = 2.0
nosy_names = ['methane', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41167'
versions = ['Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
It may be more useful if generalize it for integer convertors. It is common that `None` in Python code is translated to some constant (like `-1`, or `Py_SSIZE_T_MAX`, or `AT_FDCWD`) in the C code. But we need to analyze code to find whether it makes it simpler.
