### ISSUE TITLE
Use strnlen instead of strlen when the size i known.

### ISSUE THREAD

**Issue by 99202308-2311-4d52-a8a6-9e90520f11ba** [python/cpython#85342]
BPO | [41170](https://bugs.python.org/issue41170)
--- | :---
Nosy | @vstinner, @larryhastings, @ericvsmith, @edge90
PRs | <li>python/cpython#21236</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-06-30.14:44:52.513>
labels = ['expert-C-API', '3.10']
title = 'Use strnlen instead of strlen when the size i known.'
updated_at = <Date 2020-09-28.22:08:46.110>
user = 'https://github.com/edge90'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-28.22:08:46.110>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-06-30.14:44:52.513>
creator = 'Niclas Larsson'
dependencies = []
files = []
hgrepos = []
issue_num = 41170
keywords = ['patch']
message_count = 4.0
messages = ['372727', '372752', '377632', '377633']
nosy_count = 5.0
nosy_names = ['vstinner', 'larry', 'eric.smith', 'python-dev', 'Niclas Larsson']
pr_nums = ['21236']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41170'
versions = ['Python 3.10']
```

</p></details>

**Comment by furkanonder** [comment]
> [PR 21236](https://github.com/python/cpython/pull/21236) was closed by his author, can this issue be closed?

@serhiy-storchaka  also [says](https://github.com/python/cpython/pull/21236#issuecomment-699609949) that he is inclined to close the issue and since author of the PR closed the PR I think issue can be close.
