### ISSUE TITLE
Emoji Unicode failing in standard release of Python 3.8.3 / tkinter 8.6.8

### ISSUE THREAD

**Issue by 84a9c0fb-9988-47a7-97de-841a2f2f996c** [python/cpython#85384]
BPO | [41212](https://bugs.python.org/issue41212)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily, @jimjjewett, @MrBenGriffin, @E-Paine
Files | <li>[Emoji.py.txt](https://bugs.python.org/file49297/Emoji.py.txt "Uploaded as text/plain at 2020-07-05.08:41:53 by @MrBenGriffin"): File that shows issue</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = <Date 2020-07-11.01:44:57.930>
created_at = <Date 2020-07-05.08:41:53.766>
labels = ['OS-mac', '3.8', 'type-bug', 'expert-tkinter']
title = 'Emoji Unicode failing in standard release of Python 3.8.3 / tkinter 8.6.8'
updated_at = <Date 2020-07-11.18:15:59.688>
user = 'https://github.com/MrBenGriffin'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-11.18:15:59.688>
actor = 'Jim.Jewett'
assignee = 'ned.deily'
closed = True
closed_date = <Date 2020-07-11.01:44:57.930>
closer = 'terry.reedy'
components = ['macOS', 'Tkinter']
creation = <Date 2020-07-05.08:41:53.766>
creator = 'Ben Griffin'
dependencies = []
files = ['49297']
hgrepos = []
issue_num = 41212
keywords = []
message_count = 7.0
messages = ['373019', '373041', '373051', '373079', '373089', '373495', '373531']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'Jim.Jewett', 'Ben Griffin', 'epaine']
pr_nums = []
priority = 'normal'
resolution = 'third party'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41212'
versions = ['Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
@Moosems  Plans by whom to fix what?   Serhiy patched tkinter as well as he knew how so that astral chars show in tk widgets *when available in the font*.   Python core devs cannot patch tcl/tk and in particular, we cannot fix tk edit code.  However, we currently include recent tcl/tk 8.6.12 with Windows and Mac installers.

Crash (or exception)?  Please give exact details, including minimal reproducible code and macOS, tck/tk, and Python versions and installer source.  With python.org 3.10.4 on AirBook with updated Catalina, this works.
>>> '\U0001f4bb'
'💻'
>>> import tkinter as tk
>>> import tkinter as tk
>>> r=tk.Tk()
>>> c=tk.Canvas(r)
>>> c.pack()
>>> c.create_text(10,10,text='\U0001f4bb')
1
# Terminal emoji appears on canvas.
For unassigned codeponts, such as '\U00030000', a box '𰀀' is printed and shown on the canvas.  On my Mac, it contains a question mark.  For assigned codepoints with no glyph in the font, such as '\U0001000C' with Monaco, Mac prints the escape but puts a box on the canvas.

**Comment by Moosems** [comment]
@terryjreedy When the user types an emoji into the IDLE terminal it causes it to freeze and the user can no longer to type. Another issue related to this is that when the user types an emoji while editing a file it repeats everything before it and it loses syntax highlighting. 

How to reproduce:
Just type an emoji into the app and see it for yourself

**Comment by terryjreedy** [comment]
I just pasted `💻` and `'💻'` into IDLE Shell they echo just fine.  Re-read what info I requested above.

**Comment by ronaldoussoren** [comment]
@Moosems : If you do have an problem with emoji please file a new issue, with (as Terry requested):

- How to reproduce the problem (for example, "open IDLE and type ... in {new document window, shell}")
- Which version of Python did you test
- How was python installed? (Python.org installer, homebrew, ...)
- Include the Tcl/Tk versions from ``python -m test.pythoninfo`` (to get this from IDLE itself: in a shell window use ``from test.pythoninfo import main; main()``)
- Which version of macOS do you use, and are you on an M1 based platform or x86_64

FWIW: IDLE works fine for me, Python 3.11b1 installed using the python.org installer on an M1 laptop. I can type emoji both in a shell and a document window without problems and editing works OK.

**Comment by Moosems** [comment]
@ronaldoussoren I updated my question and have created a [separate issue](https://github.com/python/cpython/issues/93052) for this
