### ISSUE TITLE
add optional make_key argument to lru_cache

### ISSUE THREAD

**Issue by 8de7b16e-2a85-4b6b-afd8-c8f1d40a386a** [python/cpython#85392]
BPO | [41220](https://bugs.python.org/issue41220)
--- | :---
Nosy | @rhettinger, @jimjjewett, @bharel, @Itayazolay, @fbidu
PRs | <li>python/cpython#21353</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/rhettinger'
closed_at = <Date 2020-07-18.02:11:25.041>
created_at = <Date 2020-07-06.16:51:10.521>
labels = ['type-feature', 'library', '3.10']
title = 'add optional make_key argument to lru_cache'
updated_at = <Date 2020-07-18.02:11:25.040>
user = 'https://github.com/Itayazolay'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-18.02:11:25.040>
actor = 'rhettinger'
assignee = 'rhettinger'
closed = True
closed_date = <Date 2020-07-18.02:11:25.041>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2020-07-06.16:51:10.521>
creator = 'Itayazolay'
dependencies = []
files = []
hgrepos = []
issue_num = 41220
keywords = ['patch']
message_count = 11.0
messages = ['373141', '373153', '373197', '373209', '373212', '373285', '373505', '373506', '373522', '373535', '373869']
nosy_count = 5.0
nosy_names = ['rhettinger', 'Jim.Jewett', 'bar.harel', 'Itayazolay', 'fbidu']
pr_nums = ['21353']
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41220'
versions = ['Python 3.10']
```

</p></details>

**Comment by outofmbufs** [comment]
Not sure about the etiquette/ability to comment on closed issues, but here's an implementation of what OP asks for that is along the lines of the dataclass/equality testing direction but expressed as a keyfunc to a decorator (which in turn uses lru_cache): https://gist.github.com/outofmbufs/c0d7ca230d7db90afbaa985c714619d4
