### ISSUE TITLE
"about" button in MacOS caused an error

### ISSUE THREAD

**Issue by c7bfc925-1465-4114-ae06-e03f0f60dd6c** [python/cpython#85408]
BPO | [41236](https://bugs.python.org/issue41236)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-08.06:05:16.792>
labels = ['OS-mac', 'type-bug', '3.7']
title = '"about" button in MacOS caused an error'
updated_at = <Date 2020-07-11.13:33:41.466>
user = 'https://bugs.python.org/BaozhenChen'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-11.13:33:41.466>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2020-07-08.06:05:16.792>
creator = 'Baozhen Chen'
dependencies = []
files = []
hgrepos = []
issue_num = 41236
keywords = []
message_count = 5.0
messages = ['373278', '373291', '373507', '373517', '373523']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'Baozhen Chen']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41236'
versions = ['Python 3.7']
```

</p></details>

**Comment by iritkatriel** [comment]
The OP didn't follow up with information how to reproduce the error, and 3.8 is no longer supported. I am closing and we can reopen or create a new issue if we get information that can help understand the problem.

**Comment by terryjreedy** [comment]
Thank you Irit.  When I retry `python -m tkinter` with 3.11.0b3 in `Terminal`, the 'Terminal' menu item on the top left is replaced with a 'Python' menu item.  Clicking 'Python' and then 'About Python' pop up a read-only box with the python launcher logo.  This box is exactly the same as the terminal About box in layout and fonts, including font sized.  I strongly suspect that both boxes are created by the OS with system widgets.  Closing the demo widget reverts the menu change.

There is not now a custom 'About widget demo' box in tkinter.py.   Something must have changed.
