### ISSUE TITLE
Argparse.parse_args exits on unrecognized option with exit_on_error=False

### ISSUE THREAD

**Issue by 00dcd123-3f50-4394-96eb-3e7b1086583c** [python/cpython#85427]
BPO | [41255](https://bugs.python.org/issue41255)
--- | :---
Nosy | @rhettinger, @tirkarthi, @matthewhughes934, @jacobtylerwalls, @bigbirdcode, @joshmeranda
PRs | <li>python/cpython#27295</li><li>python/cpython#30832</li>
Files | <li>[exit_on_error_tests.patch](https://bugs.python.org/file49310/exit_on_error_tests.patch "Uploaded as text/plain at 2020-07-09.13:59:50 by @matthewhughes934")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-09.08:40:33.198>
labels = ['type-bug', 'library', '3.9']
title = 'Argparse.parse_args exits on unrecognized option with exit_on_error=False'
updated_at = <Date 2022-01-29.03:10:17.942>
user = 'https://github.com/matthewhughes934'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-29.03:10:17.942>
actor = 'jacobtylerwalls'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-07-09.08:40:33.198>
creator = 'mhughes'
dependencies = []
files = ['49310']
hgrepos = []
issue_num = 41255
keywords = ['patch']
message_count = 10.0
messages = ['373382', '373383', '373385', '373405', '373437', '373440', '373470', '396345', '397975', '401629']
nosy_count = 7.0
nosy_names = ['rhettinger', 'paul.j3', 'xtreak', 'mhughes', 'jacobtylerwalls', 'bigbird', 'joshmeranda']
pr_nums = ['27295', '30832']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41255'
versions = ['Python 3.9']
```

</p></details>

**Comment by mathews** [comment]
the following is a modification from elyra, the use of argparse is the simplest.  with an uograde python version, IT just failed to work.  the python version is 3.10.6. 
        
        import argparse

        global pipeline_name, operation_name

        logger.debug("Parsing Arguments.....")
        parser = argparse.ArgumentParser(exit_on_error=False)
        parser.add_argument(
            "-e", "--cos-endpoint", dest="cos-endpoint", help="Cloud object storage endpoint", required=True
        ) 

argparse just exits on extra arguments, with exit_on_error=False.
This is a real bug!

**Comment by ed-ij** [comment]
Just wanted to bump this after attempting to use the `exit_on_error` argument to prevent `sys.exit()` being called. Documentation could at least be improved until a better implementation is available. Adding a note in the documentation for this function which links to the "Exiting methods" section would also be helpful in the interim although I agree with bigbirdcode and joshmeranda that you shouldn't have to override methods just to have control over error handling.

**Comment by serhiy-storchaka** [comment]
I wrote #121056 before discovering this issue. It is basically an extended version of #30832.

We now have 3 duplicate issues with 4 open PRs (and one incomplete PR was already merged). It is time to finish this.
