### ISSUE TITLE
Deprecate and remove distutils

### ISSUE THREAD

**Issue by jaraco** [python/cpython#85454]
BPO | [41282](https://bugs.python.org/issue41282)
--- | :---
Nosy | @brettcannon, @doko42, @pfmoore, @jaraco, @ncoghlan, @tiran, @ned-deily, @merwok, @encukou, @methane, @ambv, @zooba, @dstufft, @pganssle, @hroncok, @frenzymadness, @pablogsal, @hugovk, @miss-islington, @tirkarthi, @FFY00
PRs | <li>python/cpython#23142</li><li>python/cpython#24355</li><li>python/cpython#24549</li><li>python/cpython#24657</li><li>python/cpython#25405</li><li>python/cpython#25406</li><li>python/cpython#25571</li><li>python/cpython#25718</li><li>python/cpython#26327</li><li>python/cpython#26329</li><li>python/cpython#26336</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-12.08:30:25.278>
labels = ['library', '3.10', '3.11']
title = 'Deprecate and remove distutils'
updated_at = <Date 2021-10-13.14:03:04.437>
user = 'https://github.com/jaraco'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-13.14:03:04.437>
actor = 'hroncok'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Distutils']
creation = <Date 2020-07-12.08:30:25.278>
creator = 'jaraco'
dependencies = []
files = []
hgrepos = []
issue_num = 41282
keywords = ['patch']
message_count = 44.0
messages = ['373548', '373549', '373586', '373612', '373613', '373614', '373615', '373622', '373629', '373630', '373631', '373633', '373649', '373651', '373652', '373653', '376390', '385812', '385946', '386453', '387897', '388224', '391082', '391087', '391175', '391683', '391768', '392322', '392327', '392329', '392331', '393017', '393018', '393020', '393021', '393023', '393026', '394241', '394242', '394248', '394275', '394277', '394302', '403835']
nosy_count = 23.0
nosy_names = ['brett.cannon', 'doko', 'paul.moore', 'jaraco', 'ncoghlan', 'christian.heimes', 'ned.deily', 'eric.araujo', 'Arfrever', 'ionelmc', 'petr.viktorin', 'methane', 'lukasz.langa', 'steve.dower', 'dstufft', 'p-ganssle', 'hroncok', 'frenzy', 'pablogsal', 'hugovk', 'miss-islington', 'xtreak', 'FFY00']
pr_nums = ['23142', '24355', '24549', '24657', '25405', '25406', '25571', '25718', '26327', '26329', '26336']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41282'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by vstinner** [comment]
I created a follow-up issue: #92584 "Rename the distutils package to _distutils".

**Comment by arhadthedev** [comment]
@vstinner Since `setup.py` was totally removed in gh-94474, can gh-92585 be repuprosed to close this issue?

**Comment by tiran** [comment]
We like to remove distutils completely. However we are not there yet. There are still some test cases and tools that have to be ported to virtual environments with setuptools or use different approaches. From the top of my head ``test_cppext``, peg generator tests, and c-analyzer have to be changed first.

**Comment by encukou** [comment]
FWIW, `test_cppext` uses venv + setuptools already, but it's not exactly a shining example of how to do this well. (Helping to improve it would be appreciated in #92906 & #94751.)
By chance, are there setuptools→venv migration success stories in the testsuite to use as examples of what to do?

**Comment by arhadthedev** [comment]
> There are also references to :mod:\`distutils\` and various functions in the distutils namespace in the whatsnew. They have to be replaced by \`\`distutils\`\`, too.

@tiran Thank you for the advice, I've created gh-95192 to address the second part.

**Comment by vstinner** [comment]
> FWIW, test_cppext uses venv + setuptools already, but it's not exactly a shining example of how to do this well. (Helping to improve it would be appreciated in https://github.com/python/cpython/issues/92906 & https://github.com/python/cpython/issues/94751.)

Using setuptools on a newly built Python is not the most common case (run Python from its source directory, not on an "installed" Python). It causes multiple issues in sysconfig and setuptools. Hopefully, it seems like these issues are being fixed one by one, but it still seems to be bumpy work-in-progress (sysconfig+setuptools issues come back time to time).

As you wrote, it doesn't work on Windows yet.

**Comment by tiran** [comment]
https://github.com/python/cpython/pull/95254 is a different approach. It unpacks setuptools wheel and injects it into sys.path.

**Comment by arhadthedev** [comment]
> We like to remove distutils completely. [...] There are still some test cases and tools that have to be ported to virtual environments with setuptools or use different approaches. From the top of my head test_cppext, peg generator tests, and c-analyzer have to be changed first.

After gh-103316 vendored setuptools into `Lib/test`, should we consider this plan outdated and close the issue as done?

**Comment by arhadthedev** [comment]
By the way, gh-92584 and gh-95254 are still open so I'm not sure.

**Comment by vstinner** [comment]
The distutils package was removed in Python 3.12 by issue #92584. Remaining issues related to this removal are tracked by issue #92584. I close this one.

**Comment by abartlet** [comment]
Debian advises at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1080851 that this breaks builds of Samba, as we use distutils.sysconfig.get_python_lib.   Can distutils.sysconfig be made an alias for sysconfig so that software like ours that just needs this detail doesn't get unnecessarily broken?

It is very helpful for Samba to be able to build historical versions on modern operating systems, and changes like this continue to make our development process more painful. 

Thanks for your understanding,

Andrew Bartlett

**Comment by zooba** [comment]
`sysconfig` has existed for 14 years already (including in Python 2) - is that not long enough to switch to it?

Installing `setuptools` should bring in the shim that you need. If we were to keep shims in the standard library, it would be impossible for them to properly migrate the old `distutils` interface.

**Comment by jaraco** [comment]
Related - CPython has given this namespace over to Setuptools, so it no longer has the ability to present that name without breaking migration plans for distutils in Setuptools. Currently, Setuptools _does_ present `distutils`, including `distutils.sysconfig`, but it's deprecated from there as well, and we're working to provide the necessary interfaces to migrate users away from that (including `distutils.sysconfig` -> `sysconfig`), so the best bet would be not to rely on Setuptools for this behavior if you can help it.

**Comment by doko42** [comment]
please can you check, if things like python3-config can solve your issues? this is also available for some time
