### ISSUE TITLE
Indicate supported sound header formats

### ISSUE THREAD

**Issue by nanjekyejoannah** [python/cpython#85525]
BPO | [41353](https://bugs.python.org/issue41353)
--- | :---
Nosy | @nanjekyejoannah
PRs | <li>python/cpython#21575</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-21.01:59:17.608>
labels = ['type-feature', 'docs']
title = 'Indicate supported sound header formats'
updated_at = <Date 2020-07-21.02:00:20.351>
user = 'https://github.com/nanjekyejoannah'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-21.02:00:20.351>
actor = 'nanjekyejoannah'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-07-21.01:59:17.608>
creator = 'nanjekyejoannah'
dependencies = []
files = []
hgrepos = []
issue_num = 41353
keywords = ['patch']
message_count = 1.0
messages = ['374047']
nosy_count = 2.0
nosy_names = ['docs@python', 'nanjekyejoannah']
pr_nums = ['21575']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41353'
versions = []
```

</p></details>

**Comment by hugovk** [comment]
Note the sndhdr module is deprecated in 3.11 and set for removal in 3.13.

See [PEP 594 – Removing dead batteries from the standard library](https://peps.python.org/pep-0594/) and https://github.com/python/cpython/issues/91217.

**Comment by merwok** [comment]
This was just merged but note that the module is deprecated: https://github.com/python/cpython/issues/91217

The copied functions in email don’t have the new docstrings.

**Comment by nanjekyejoannah** [comment]
You can open a new issue and PR for that.
