### ISSUE TITLE
pathlib.Path.resolve incorrect os.path equivalent

### ISSUE THREAD

**Issue by bef25900-0ae5-40da-a18c-c4a1f765dd71** [python/cpython#85529]
BPO | [41357](https://bugs.python.org/issue41357)
--- | :---
Nosy | @websurfer5
PRs | <li>python/cpython#21596</li>
Files | <li>[bpo-41537-test.py](https://bugs.python.org/file49333/bpo-41537-test.py "Uploaded as text/plain at 2020-07-22.22:39:38 by @websurfer5"): script that illustrates differences between how Path.resolve(), os.path.abspath(), and os.path.realpath() handle symlinks</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-21.10:31:29.452>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.7', 'docs']
title = 'pathlib.Path.resolve incorrect os.path equivalent'
updated_at = <Date 2020-07-23.01:08:11.985>
user = 'https://bugs.python.org/JendrikWeise'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-23.01:08:11.985>
actor = 'Jeffrey.Kintscher'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-07-21.10:31:29.452>
creator = 'Jendrik Weise'
dependencies = []
files = ['49333']
hgrepos = []
issue_num = 41357
keywords = ['patch']
message_count = 2.0
messages = ['374060', '374115']
nosy_count = 3.0
nosy_names = ['docs@python', 'Jeffrey.Kintscher', 'Jendrik Weise']
pr_nums = ['21596']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41357'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
This was fixed in 18cb2ef46c9.
