### ISSUE TITLE
Add snake example to turtledemo

### ISSUE THREAD

**Issue by 66cd3def-774e-4505-b243-5adadc8e670d** [python/cpython#85552]
BPO | [41380](https://bugs.python.org/issue41380)
--- | :---
Nosy | @terryjreedy, @willingc, @E-Paine, @icoder-new
PRs | <li>python/cpython#21582</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2020-07-24.07:13:31.133>
labels = ['type-feature', 'library', '3.10']
title = 'Add snake example to turtledemo'
updated_at = <Date 2020-07-28.21:58:13.287>
user = 'https://github.com/icoder-new'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-28.21:58:13.287>
actor = 'terry.reedy'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-07-24.07:13:31.133>
creator = 'Ehsonjon Gadoev'
dependencies = []
files = []
hgrepos = []
issue_num = 41380
keywords = ['patch']
message_count = 9.0
messages = ['374163', '374172', '374203', '374242', '374243', '374317', '374322', '374512', '374525']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'gregorlingl', 'willingc', 'epaine', 'Ehsonjon Gadoev']
pr_nums = ['21582']
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41380'
versions = ['Python 3.10']
```

</p></details>

**Comment by terryjreedy** [comment]
icoder-new closed PR #21582 rather than make the requested changes, and the other changes needed to make this suitable for turtledemo.  There was and is a question whether we need a signed CLA from an apparent co-author.

As far as indicated, the duplicate issue #85590 and PR #21658 only changed the target directory from turtledemo/ to tools/demo.
