### ISSUE TITLE
Tricky behavior of builtin-function map

### ISSUE THREAD

**Issue by 652ebd33-9b24-455f-b228-6b7e2866fc1a** [python/cpython#85579]
BPO | [41407](https://bugs.python.org/issue41407)
--- | :---
Nosy | @rhettinger, @stevendaprano, @jimjjewett, @DarrenDanielDay
Files | <li>[issue.py](https://bugs.python.org/file49342/issue.py "Uploaded as text/plain at 2020-07-27.10:01:38 by @DarrenDanielDay"): The file's content is just the comment.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-07-28.01:47:16.712>
created_at = <Date 2020-07-27.10:01:38.207>
labels = ['3.7', 'type-bug', 'library']
title = 'Tricky behavior of builtin-function map'
updated_at = <Date 2020-07-28.01:47:16.687>
user = 'https://github.com/DarrenDanielDay'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-28.01:47:16.687>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2020-07-28.01:47:16.712>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2020-07-27.10:01:38.207>
creator = 'DarrenDanielDay'
dependencies = []
files = ['49342']
hgrepos = []
issue_num = 41407
keywords = []
message_count = 4.0
messages = ['374371', '374372', '374444', '374449']
nosy_count = 4.0
nosy_names = ['rhettinger', 'steven.daprano', 'Jim.Jewett', 'DarrenDanielDay']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41407'
versions = ['Python 3.7']
```

</p></details>

**Comment by terryjreedy** [comment]
According to my interpretation of the current [StopIteration](https://docs.python.org/3/library/exceptions.html#StopIteration) doc, the example raise_stop_iteration function is either buggy or in consenting adults land.  Either way, one gets what one gets with no guarantees.
