### ISSUE TITLE
cgi module, parse_multipart fails

### ISSUE THREAD

**Issue by c3ddaa6a-c431-4c70-a1d8-4059cf4ec3d6** [python/cpython#85570]
BPO | [41398](https://bugs.python.org/issue41398)
--- | :---
Nosy | @gvanrossum, @ethanfurman, @websurfer5
Files | <li>[60_Request.txt](https://bugs.python.org/file49340/60_Request.txt "Uploaded as text/plain at 2020-07-26.09:58:23 by Magnus Johnsson"): The request that fails.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-26.09:58:23.957>
labels = ['3.7', '3.8', 'type-bug', 'library']
title = 'cgi module, parse_multipart fails'
updated_at = <Date 2020-08-05.23:33:14.158>
user = 'https://bugs.python.org/MagnusJohnsson'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-05.23:33:14.158>
actor = 'Jeffrey.Kintscher'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-07-26.09:58:23.957>
creator = 'Magnus Johnsson'
dependencies = []
files = ['49340']
hgrepos = []
issue_num = 41398
keywords = []
message_count = 5.0
messages = ['374307', '374374', '374705', '374753', '374757']
nosy_count = 4.0
nosy_names = ['gvanrossum', 'ethan.furman', 'Jeffrey.Kintscher', 'Magnus Johnsson']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41398'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
Closing as cgi module is deprecated as per [PEP 594](https://peps.python.org/pep-0594/) and further no improvements or bug fixes will be made to the module.
