### ISSUE TITLE
Add stacklevel support for exceptions

### ISSUE THREAD

**Issue by ff014e15-a125-4b8d-b08d-d53768e316b2** [python/cpython#85571]
BPO | [41399](https://bugs.python.org/issue41399)
--- | :---
Nosy | @serhiy-storchaka, @wyz23x2

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-26.10:17:57.372>
labels = ['interpreter-core', 'type-feature', '3.9', '3.10']
title = 'Add stacklevel support for exceptions'
updated_at = <Date 2020-07-26.10:23:51.950>
user = 'https://github.com/wyz23x2'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-26.10:23:51.950>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-07-26.10:17:57.372>
creator = 'wyz23x2'
dependencies = []
files = []
hgrepos = []
issue_num = 41399
keywords = []
message_count = 2.0
messages = ['374308', '374310']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'wyz23x2']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41399'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
@wyz23x2  - I agree with @serhiy-storchaka  and with the SO replies that advised against this.

If you want to push this idea forward, please raise it on the python-ideas list. (There is enough resistance to say this won't happen without such a discussion).
