### ISSUE TITLE
deque.pop(index) is not supported

### ISSUE THREAD

**Issue by 98e2c05b-e10f-4e0f-bfa1-526da4fe30f0** [python/cpython#85581]
BPO | [41409](https://bugs.python.org/issue41409)
--- | :---
Nosy | @rhettinger, @jimjjewett, @serhiy-storchaka, @Akuli, @pablogsal, @ShubhamKJha, @KmolYuan

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-07-28.03:30:22.736>
created_at = <Date 2020-07-27.14:18:55.663>
labels = ['type-bug', 'library', '3.10']
title = 'deque.pop(index) is not supported'
updated_at = <Date 2020-07-28.17:48:46.574>
user = 'https://github.com/Akuli'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-28.17:48:46.574>
actor = 'pablogsal'
assignee = 'none'
closed = True
closed_date = <Date 2020-07-28.03:30:22.736>
closer = 'rhettinger'
components = ['Library (Lib)']
creation = <Date 2020-07-27.14:18:55.663>
creator = 'Akuli'
dependencies = []
files = []
hgrepos = []
issue_num = 41409
keywords = []
message_count = 14.0
messages = ['374378', '374380', '374381', '374382', '374384', '374386', '374415', '374432', '374458', '374464', '374472', '374483', '374493', '374514']
nosy_count = 8.0
nosy_names = ['rhettinger', 'stutzbach', 'Jim.Jewett', 'serhiy.storchaka', 'Akuli', 'pablogsal', 'ShubhamKJha', 'Yuan']
pr_nums = []
priority = 'normal'
resolution = 'rejected'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41409'
versions = ['Python 3.10']
```

</p></details>

**Comment by AndreiPashkin** [comment]
@rhettinger, what do you think about adding more general purpose collections like `LinkedList` and `DoublyLinkedList` to `collections`? I've encountered a use case where I'd need them and there is no single popular and well-maintained library in Python's eco-system that has them implemented.

**Comment by AndreiPashkin** [comment]
@rhettinger 

> Deques designed for fast access at the end points. Also, pop() is a core deque operation that needs to be fast. Altering its signature with an optional argument would slow it down.

Also a counter-argument to that. `collections.deque` has `insert(i, x)` that supports indexing and conforms with `MutableSequence` interface even though it could be made faster without index. So if we already have `index(i, x)`, why couldn't we have `pop(i)`? And for speed it would be possible to add a special method like `fast_pop()`.
