### ISSUE TITLE
Add a `clamp` function to the `math` module

### ISSUE THREAD

**Issue by 55d8a020-4977-4335-9655-5c49a21ba477** [python/cpython#85580]
BPO | [41408](https://bugs.python.org/issue41408)
--- | :---
Nosy | @rhettinger, @mdickinson, @tirkarthi, @SFM61319
Superseder | <li>bpo-36788: Add clamp() function to builtins</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-07-27.16:23:46.367>
created_at = <Date 2020-07-27.12:28:33.417>
labels = ['type-feature', 'library', '3.10']
title = 'Add a `clamp` function to the `math` module'
updated_at = <Date 2020-07-28.07:32:49.941>
user = 'https://github.com/SFM61319'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-28.07:32:49.941>
actor = 'mark.dickinson'
assignee = 'none'
closed = True
closed_date = <Date 2020-07-27.16:23:46.367>
closer = 'SFM61319'
components = ['Library (Lib)']
creation = <Date 2020-07-27.12:28:33.417>
creator = 'SFM61319'
dependencies = []
files = []
hgrepos = []
issue_num = 41408
keywords = []
message_count = 6.0
messages = ['374373', '374376', '374388', '374391', '374393', '374396']
nosy_count = 5.0
nosy_names = ['rhettinger', 'mark.dickinson', 'stutzbach', 'xtreak', 'SFM61319']
pr_nums = []
priority = 'normal'
resolution = 'duplicate'
stage = 'resolved'
status = 'closed'
superseder = '36788'
type = 'enhancement'
url = 'https://bugs.python.org/issue41408'
versions = ['Python 3.10']
```

</p></details>

**Comment by samtygier-stfc** [comment]
In case this is ever reconsidered: Numpy has a [clip](https://numpy.org/doc/stable/reference/generated/numpy.clip.html) method, so that might be a good name for consistency.

I think clamp/clip is something I'd expect to find in math library. It exists in c++, rust, julia ...
