### ISSUE TITLE
Document C docstring behavior for signature extraction

### ISSUE THREAD

**Issue by ee92c805-465e-4ea5-af32-6a89c735c882** [python/cpython#85602]
BPO | [41430](https://bugs.python.org/issue41430)
--- | :---
Nosy | @jameshcorbett
PRs | <li>python/cpython#21673</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-07-29.00:00:19.531>
labels = ['type-feature', 'docs']
title = 'Document C docstring behavior'
updated_at = <Date 2020-07-29.01:25:49.742>
user = 'https://github.com/jameshcorbett'
```

bugs.python.org fields:
```python
activity = <Date 2020-07-29.01:25:49.742>
actor = 'jameshcorbett'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-07-29.00:00:19.531>
creator = 'jameshcorbett'
dependencies = []
files = []
hgrepos = []
issue_num = 41430
keywords = ['patch']
message_count = 1.0
messages = ['374547']
nosy_count = 2.0
nosy_names = ['docs@python', 'jameshcorbett']
pr_nums = ['21673']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41430'
versions = []
```

</p></details>

**Comment by skirpichev** [comment]
I don't think we are ready to expose this stuff as public.

Recent discussion thread (with several PEP drafts): https://discuss.python.org/t/type-signatures-for-extension-modules-pep-draft/43914

Perhaps, most close issue to track the problem is https://github.com/capi-workgroup/problems/issues/32.  Maybe we should have some "feature"-type issue in the CPython repo, but this hardly is one.

I suggest close this as "not planned".  It's not a documentation issue.

CC @picnixz

**Comment by picnixz** [comment]
> I don't think we are ready to expose this stuff as public.

Ah! I thought we were ready! I never created a manual docstring for a function actually except using AC or something with slots. If we are not ready yet on our side, then I'm ok with closing it as "not planned" for now and re-open this one when we're ready to.

**Comment by skirpichev** [comment]
> If we are not ready yet on our side

I think - no.  Currently even annotations aren't supported (https://github.com/python/cpython/issues/81677).  And no support for multiple signatures (https://github.com/python/cpython/issues/73536).

**Comment by picnixz** [comment]
When we'll be ready, then it will become a "docs" issue only. For now, we'll close it as `not planned`.
