### ISSUE TITLE
Inefficient BufferedReader.read(-1)

### ISSUE THREAD

**Issue by b8e5a65c-bed4-4c5d-ba32-799f883ba638** [python/cpython#85624]
BPO | [41452](https://bugs.python.org/issue41452)
--- | :---
Nosy | @animalize
PRs | <li>python/cpython#21698</li>
Files | <li>[demo.py](https://bugs.python.org/file49354/demo.py "Uploaded as text/plain at 2020-08-01.03:34:12 by @animalize")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-08-01.05:59:43.634>
created_at = <Date 2020-08-01.03:34:14.219>
labels = ['3.10', 'expert-IO', 'performance']
title = 'Inefficient BufferedReader.read(-1)'
updated_at = <Date 2020-08-01.05:59:43.633>
user = 'https://github.com/animalize'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-01.05:59:43.633>
actor = 'malin'
assignee = 'none'
closed = True
closed_date = <Date 2020-08-01.05:59:43.634>
closer = 'malin'
components = ['IO']
creation = <Date 2020-08-01.03:34:14.219>
creator = 'malin'
dependencies = []
files = ['49354']
hgrepos = []
issue_num = 41452
keywords = ['patch']
message_count = 2.0
messages = ['374652', '374657']
nosy_count = 1.0
nosy_names = ['malin']
pr_nums = ['21698']
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue41452'
versions = ['Python 3.10']
```

</p></details>

**Comment by mxmlnkn** [comment]
I have the same issue. It is hugely confusing that the buffer size is ignored for `read(-1)`! And regarding it being a "fast-path", it is not. It is 100 times slower on my Lustre test filesystem, which has a block size of 4 MiB.
