### ISSUE TITLE
SimpleQueues put blocks if feeded with strings greater than 2**16-13 chars

### ISSUE THREAD

**Issue by 32da1d5b-5cd8-4206-b164-816985bb136c** [python/cpython#85722]
BPO | [41550](https://bugs.python.org/issue41550)
--- | :---
Nosy | @iritkatriel, @rgrewe
Files | <li>[test_simple_queue_put.py](https://bugs.python.org/file49389/test_simple_queue_put.py "Uploaded as text/plain at 2020-08-14.09:36:36 by @rgrewe")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-08-20.08:51:26.038>
created_at = <Date 2020-08-14.09:36:36.511>
labels = ['3.7', 'invalid']
title = 'SimpleQueues put blocks if feeded with strings greater than 2**16-13 chars'
updated_at = <Date 2020-08-20.08:51:26.037>
user = 'https://github.com/rgrewe'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-20.08:51:26.037>
actor = 'rgrewe'
assignee = 'none'
closed = True
closed_date = <Date 2020-08-20.08:51:26.038>
closer = 'rgrewe'
components = []
creation = <Date 2020-08-14.09:36:36.511>
creator = 'rgrewe'
dependencies = []
files = ['49389']
hgrepos = []
issue_num = 41550
keywords = []
message_count = 7.0
messages = ['375385', '375393', '375414', '375416', '375675', '375676', '375693']
nosy_count = 2.0
nosy_names = ['iritkatriel', 'rgrewe']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue41550'
versions = ['Python 3.7']
```

</p></details>

**Comment by mberdyshev** [comment]
Is it going to be fixed in `SimpleQueue`? It seems that the provided code is still hanging as @iritkatriel described earlier.
Tested on Windows 10, Python 3.11.2.
