### ISSUE TITLE
Cannot access member "hex" for type "ByteString"

### ISSUE THREAD

**Issue by da8fd79a-d72b-43c9-b0d1-e28ad73aa32f** [python/cpython#85736]
BPO | [41564](https://bugs.python.org/issue41564)
--- | :---
Nosy | @ericvsmith, @anacrolix, @websurfer5
Files | <li>[hex.py](https://bugs.python.org/file49423/hex.py "Uploaded as text/plain at 2020-08-24.01:22:06 by @anacrolix")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-08-17.02:50:33.866>
labels = ['3.8', 'type-bug', 'library']
title = 'Cannot access member "hex" for type "ByteString"'
updated_at = <Date 2020-08-24.02:06:57.496>
user = 'https://github.com/anacrolix'
```

bugs.python.org fields:
```python
activity = <Date 2020-08-24.02:06:57.496>
actor = 'Jeffrey.Kintscher'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-08-17.02:50:33.866>
creator = 'anacrolix'
dependencies = []
files = ['49423']
hgrepos = []
issue_num = 41564
keywords = []
message_count = 8.0
messages = ['375523', '375528', '375553', '375554', '375831', '375832', '375833', '375834']
nosy_count = 3.0
nosy_names = ['eric.smith', 'anacrolix', 'Jeffrey.Kintscher']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41564'
versions = ['Python 3.8']
```

</p></details>

**Comment by martindemello** [comment]
based on this note in `Lib/_collections_abc.py` this might require creating a `ByteString` subclass:
```
# ABCs are different from other standard library modules in that they
# specify compliance tests.  In general, once an ABC has been published,
# new methods (either abstract or concrete) cannot be added.
#
# Though classes that inherit from an ABC would automatically receive a
# new mixin method, registered classes would become non-compliant and
# violate the contract promised by ``isinstance(someobj, SomeABC)``.
#
# Though irritating, the correct procedure for adding new abstract or
# mixin methods is to create a new ABC as a subclass of the previous
# ABC.  For example, union(), intersection(), and difference() cannot
# be added to Set but could go into a new ABC that extends Set.
```

**Comment by hauntsaninja** [comment]
First, note that static type checkers don't actually look at code in CPython, they look at the definition in typeshed: https://github.com/python/typeshed/blob/1d7ace353a4c96b6a279ed0df9179118467da7c7/stdlib/typing.pyi#L708
As you can see, this means that `typing.ByteString` is just a glorified `Sequence[int]`.

But it is true that typeshed is just reflecting the code that's in CPython, so decisions should be made here. The interface for `ByteString` is defined here: https://github.com/python/cpython/blob/1ae7abf6b2f410feee02286a1b2179f2c6e88abd/Lib/_collections_abc.py#L1090. You'll see there's an `XXX` comment that maybe suggests that this wasn't as thought out as it could be.

Overall, I don't think this is super well specified. As I mention here https://discuss.python.org/t/pep-688-making-the-buffer-protocol-accessible-in-python/15265/16 , if you intersect bytes, bytearray and memoryview you get a `Sequence[int]` + `.hex` and nothing else, so `hex` is really the only thing missing.

Overall, I vote to close this. It's probably problematic from a compatibility standpoint to change interfaces in `collections.abc`.

If you want to type your code loosely, just use `bytes` (type checkers will do the right thing, although PEP 688 proposes removing the shorthand: https://peps.python.org/pep-0688/#no-special-meaning-for-bytes )

If you want to type your code exactly, use a custom protocol:
```
class Hex(Sequence[int]):
    def hex(self) -> int: ...
```

**Comment by hauntsaninja** [comment]
Also see the discussion at https://github.com/python/cpython/issues/91896
