### ISSUE TITLE
pdb - Clickable path to breakpoints

### ISSUE THREAD

**Issue by a1ca7e48-20d8-42f4-b2ec-33577916c66c** [python/cpython#85773]
BPO | [41607](https://bugs.python.org/issue41607)
--- | :---
Nosy | @vedgar, @arturtamborski
PRs | <li>python/cpython#22964</li>
Files | <li>[Screenshot 2020-06-12 at 08.37.35.png](https://bugs.python.org/file49420/Screenshot%202020-06-12%20at%2008.37.35.png "Uploaded as image/png at 2020-08-21.08:49:30 by michimussato")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-08-21.08:49:30.453>
labels = ['type-feature', 'library']
title = 'pdb - Clickable path to breakpoints'
updated_at = <Date 2020-10-25.08:24:05.743>
user = 'https://bugs.python.org/michimussato'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-25.08:24:05.743>
actor = 'arturtamborski'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-08-21.08:49:30.453>
creator = 'michimussato'
dependencies = []
files = ['49420']
hgrepos = []
issue_num = 41607
keywords = ['patch']
message_count = 2.0
messages = ['375747', '375766']
nosy_count = 3.0
nosy_names = ['veky', 'michimussato', 'arturtamborski']
pr_nums = ['22964']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41607'
versions = []
```

</p></details>

**Comment by gaogaotiantian** [comment]
Changing format of stack entry is a big ask as it would break all the existing tests. "clickable link" is kind of arbitrary because it simply depends on whether your IDEs recognize the string - it's more like an IDE feature. For example, VSCode support current stack entry format with no issue. As there is no "standard" for file + line format, I'll close this as not planned.

**Comment by gaogaotiantian** [comment]
Close as no one is opposing.
