### ISSUE TITLE
[Windows] : Proactor test_sendfile_close_peer_in_the_middle_of_receiving failure

### ISSUE THREAD

**Issue by aeros** [python/cpython#85848]
BPO | [41682](https://bugs.python.org/issue41682)
--- | :---
Nosy | @gvanrossum, @terryjreedy, @ncoghlan, @vstinner, @asvetlov, @1st1, @miss-islington, @sweeneyde, @aeros, @erlend-aasland, @sobolevn, @Fidget-Spinner, @kumaraditya303, @arhadthedev
PRs | <li>python/cpython#30801</li><li>python/cpython#30811</li><li>python/cpython#30812</li><li>python/cpython#30817</li><li>python/cpython#30845</li><li>python/cpython#30860</li><li>python/cpython#30861</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-01-25.17:41:06.264>
created_at = <Date 2020-09-01.01:20:55.485>
labels = ['type-bug', '3.10', '3.11', 'tests', 'OS-windows', 'expert-asyncio']
title = '[Windows] : Proactor test_sendfile_close_peer_in_the_middle_of_receiving failure'
updated_at = <Date 2022-01-25.18:03:17.384>
user = 'https://github.com/aeros'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-25.18:03:17.384>
actor = 'vstinner'
assignee = 'none'
closed = True
closed_date = <Date 2022-01-25.17:41:06.264>
closer = 'vstinner'
components = ['Tests', 'Windows', 'asyncio']
creation = <Date 2020-09-01.01:20:55.485>
creator = 'aeros'
dependencies = []
files = []
hgrepos = []
issue_num = 41682
keywords = ['patch']
message_count = 23.0
messages = ['376175', '376176', '391134', '392061', '396238', '396503', '399770', '402294', '404820', '408612', '411293', '411299', '411313', '411322', '411386', '411508', '411638', '411639', '411640', '411641', '411643', '411646', '411651']
nosy_count = 14.0
nosy_names = ['gvanrossum', 'terry.reedy', 'ncoghlan', 'vstinner', 'asvetlov', 'yselivanov', 'miss-islington', 'Dennis Sweeney', 'aeros', 'erlendaasland', 'sobolevn', 'kj', 'kumaraditya', 'arhadthedev']
pr_nums = ['30801', '30811', '30812', '30817', '30845', '30860', '30861']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41682'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by tasty0tomato** [comment]
I built 3.11.5 on my own Windows computer, and found it passed this test on one computer, but didn't pass on another computer. I think that this issue may not be fixed completely, or I can provide needed information of the computer which this test didn't pass to find out the reason why it didn't pass.

**Comment by vstinner** [comment]
This issue is closed, please open a new issue.
