### ISSUE TITLE
Potential memory leak with asyncio and run_in_executor

### ISSUE THREAD

**Issue by dc243917-adac-4659-998e-678e07844493** [python/cpython#85865]
BPO | [41699](https://bugs.python.org/issue41699)
--- | :---
Nosy | @asvetlov, @1st1, @aeros, @dralley

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-09-03.03:24:15.642>
labels = ['3.8', '3.10', 'expert-asyncio']
title = 'Potential memory leak with asyncio and run_in_executor'
updated_at = <Date 2020-10-30.03:11:23.899>
user = 'https://bugs.python.org/sophia2'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-30.03:11:23.899>
actor = 'aeros'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-09-03.03:24:15.642>
creator = 'sophia2'
dependencies = []
files = []
hgrepos = []
issue_num = 41699
keywords = []
message_count = 7.0
messages = ['376275', '379877', '379884', '379903', '379905', '379907', '379909']
nosy_count = 5.0
nosy_names = ['asvetlov', 'yselivanov', 'aeros', 'sophia2', 'dralley']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41699'
versions = ['Python 3.8', 'Python 3.10']
```

</p></details>

**Comment by normanlmfung** [comment]
Hi there,

I am on asyncio 3.4.3 and also python 3.9 on my Windows laptop. Even with both "list(range(1000)" and "1/0" commented out I can still see the memory leak. Seems if you loop run_in_executor you'd still see leak very quickly.

def leaker():
    # x = list(range(int(1000)))
    # 1/0
    pass

**Comment by gvanrossum** [comment]
> Hi there,
> 
> I am on asyncio 3.4.3 and also python 3.9 on my Windows laptop. Even with both "list(range(1000)" and "1/0" commented out I can still see the memory leak. Seems if you loop run_in_executor you'd still see leak very quickly.
> 
> def leaker(): # x = list(range(int(1000))) # 1/0 pass

Could you post the complete code you ran, and what you did to determine that you have a memory leak? This code snippet doesn't help me at all.

Also what is "asyncio 3.4.3"? Since asyncio is distributed as part of the Python stdlib, it does not have a separate version number.

**Comment by normanlmfung** [comment]
Here's the complete code:
And from my requirements.txt, "asyncio==3.4.3" (Also found from pip freeze)
```
import asyncio
import nest_asyncio
import psutil
import os
import time

def leaker():
    # x = list(range(int(1000)))
    # 1/0
    pass

this_loop = asyncio.new_event_loop()
asyncio.set_event_loop(this_loop)
nest_asyncio.apply()
    
for i in range(10000):
    this_loop.run_in_executor(None, leaker)

    memory_bytes = psutil.Process(os.getpid()).memory_info().rss
    memory_mb = memory_bytes / 1024 **2
    memory_gb = memory_mb / 1024

    if i==0:
        starting_memory_gb = memory_gb
    print(f"memory (GB): {memory_gb}, % starting: {memory_gb/starting_memory_gb}")

    time.sleep(1)
    i = i + 1
```

**Comment by gvanrossum** [comment]
Oh, that asyncio version is ancient. See if it still leaks if you uninstall that. Talk to whoever provided your requirements.txt and tell them to take it out.

**Comment by gvanrossum** [comment]
Yes, and the first line of the description is "This version is only relevant for Python 3.3, which does not include asyncio in its stdlib."

**Comment by normanlmfung** [comment]
Well, this issue is reproducible on python 3.9 and asyncio 3.4.3. You're suggesting to open a new ticket for this?

**Comment by gvanrossum** [comment]
I am asking you to remove asyncio 3.4.3 from your project because it is out of date. If you do not understand this please ask for help somewhere else.

**Comment by normanlmfung** [comment]
Yo. https://pypi.org/project/asyncio/  --> It says 3.4.3 is latest, what you mean its outdated?

**Comment by CAM-Gerlach** [comment]
Let me explain what you're seeing here.

[`asyncio`](https://docs.python.org/3/library/asyncio.html) is a [module](https://docs.python.org/3/glossary.html#term-module) in the [Python standard library](https://docs.python.org/3/library/index.html), i.e. the set of modules that are included with any standard Python distribution (such as `math`, `re`, `datetime`, `os`, `sys` and many more). Like with the rest of the standard library modules, `asyncio` development happens on this repository alongside the rest of CPython, the reference implementation of Python and by far the most widely used.

The `asyncio` PyPI distribution package you linked above, which has a maximum version of 3.4.3 and last released over 7.5 years ago, provided a standalone version of the `asyncio` module for (ancient, long-obsolete) versions of Python (specifically, Python 3.3) before it was part of the standard library. In Python >=3.4, where it is included, the backport is not only unnecessary and outdated, but doesn't have any useful effect, as the standard library version takes precedence over the standalone package and is what you will get when you `import asyncio`, even if you have the old backport installed.

Therefore, as Guido (the original primary author of the `asyncio` module and one of the maintainers of the PyPI package) recommended, you should uninstall the standalone `asyncio` distribution package, and remove it from your requirements.txt`, as it no longer serves any useful purpose.

**Comment by normanlmfung** [comment]
Thank you very much Gerlach!

**Comment by normanlmfung** [comment]
This said, after i pip uninstall asyncio. The code snippet i provided above - I still see we're leaking memory.

**Comment by gvanrossum** [comment]
So what percentage of memory leak do you see after 10000 iterations? To get results faster you can reduce the sleep to e.g. `time.sleep(0.02)`.

Now compare this to the leakage you see with the following instead of the sleep:
```py
    this_loop.run_until_complete(asyncio.sleep(0.02))
```
That's much less, right? This is because your original program doesn't allow the event loop to run at all: `time.sleep()` blocks the current thread, where the event loop would run.

Personally, I get a leakage factor of 1.008 (that's about 0.8%, despite your output formatting) with this modification. Before (with `time.sleep(0.02)`) I get 2.565, or 156% leakage.

My theory is that the various Futures created to report the result of the function submitted to the executor (`leaker` in your case) back to the caller are stuck in the asyncio event queue, which is never emptied because you never run the event loop. I don't think we need to worry about the 0.8% leakage in the fixed case, but if you want to investigate further you are welcome to start reading and understanding the source code for asyncio (see github.com/python/cpython).

I haven't tried the OP's example program, maybe I should analyze that case next. But I'm tempted to just close this as "not a problem".

**Comment by gvanrossum** [comment]
Perhaps more useful, the program with time.sleep() leaked ~3 Kbyte per iteration, which seems reasonable for a couple of futures and associated data structures. Using asyncio as it was intended, the leak is only ~16 bytes (perhaps still worth looking into, but small enough that it probably doesn't matter, and probably very hard to track down).

The program [posted](https://github.com/python/cpython/issues/85865#issuecomment-1093882466) by @aeros does leak a bit, however this can also be vastly reduced by adding `await asyncio.sleep(0)` in the for-loop. So I suspect it's the same issue -- the [nest of Futures](https://github.com/python/cpython/blob/85dd6cb6df996b1197266d1a50ecc9187a91e481/Lib/asyncio/futures.py#L365) used to pass back the result from the executor to the asyncio client apparently is kept alive while it sits in the asyncio queue.

**Comment by normanlmfung** [comment]
Thanks gents - I am rushing some deadlines atm but will resume testing as soon as I am done with pressing objectives at hand. Allow me some time to revert.

**Comment by normanlmfung** [comment]
@gvanrossum apologies for taking so long. But I re-tested. Guido I think you're spot on that my test script was wrong to use **time.sleep**. After replacing with "**this_loop.run_until_complete(asyncio.sleep(0.02))**", the leak was no longer observable!

Thanks

**Comment by SerGeRybakov** [comment]
Hi everyone! @gvanrossum, my personal respects!
I'm facing the same problem with memory leak in loop.run_in_executor.
I have a REST-API based on Sanic, which shall run forever (obviously). This API sends and receives numpy data in different amounts and manages it with HDF5 format. 

So my snippet is the following:
```python
import asyncio
import sys
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor

import numpy as np


ex_ = "p"
# ex_ = "t"

if ex_ == "p":
    executor_ = ProcessPoolExecutor
else:
    executor_ = ThreadPoolExecutor

executor = executor_(max_workers=8)


def func():
    res = np.zeros((1024, 1024, 1024), dtype=np.int8)
    print(sys.getsizeof(res))
    return res


async def main():
    loop = asyncio.get_running_loop()
    tasks = [loop.run_in_executor(executor, func) for _ in range(4)]
    await asyncio.gather(*tasks)

    while True:
        continue


if __name__ == '__main__':
    asyncio.run(main())
```
Here the `func` emulates reading from HDF5 and returning a dataset of 1Gb size on each call. Code calls `func` 4 times and than runs until stopped. 
 
Let's assume that before start 5 Gbs of my RAM were occupied. If I call ProcessPoolExecutor, 9Gbs of my RAM are being occupied until I stop the code running. So each new call of `func` within main thread will produce a new 1Gb of data and will keep it in the global context of child process until the executor is shutdown or the child process is killed/joined/exited... And if I call ThreadPoolExecutor, 5.02 Gbs of my RAM will be occupied after start but still this number will slightly grow from call to call of `func`, what shows the same behavior but much more slow.

The heart of problem is that coroutine `main` runs forever, executor is never shutdown and garbage collector doesn't run in child processes after function return.

Is there an way to cope with it? 
Thank you in advance!

**Comment by gvanrossum** [comment]
1. It might have been better to open a new issue, but I'll respond here for now.
2. ProcessPoolExecutor really shouldn't be used with asyncio -- why are you using it?
3. I see a leak with `ThreadPoolExecutor` too, though
4. A simpler repro that doesn't use `numpy` just uses `res = b"x"*1000*1000*1000`
5. You can avoid the memory leak by inserting the following before the `while True: pass` loop:
```py
del tasks
asyncio.sleep(0)
```
This makes me think that the key is dropping the tasks, but the event loop holds on to the tasks for one iteration.

Now, if you really insist on using a `ProcessPoolExecutor`, I do think you should open a new issue, and report what you see with the above changes to your repro program.
