### ISSUE TITLE
Improve error message for string concatenation via `sum`

### ISSUE THREAD

**Issue by 4a5280e8-facc-4136-a356-842db8434d75** [python/cpython#85906]
BPO | [41740](https://bugs.python.org/issue41740)
--- | :---
Nosy | @stevendaprano, @Phillip_M_Feldman, @vedgar, @mpaolini

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-09-07.19:21:29.415>
labels = ['interpreter-core', 'type-bug', '3.8']
title = 'Improve error message for string concatenation via `sum`'
updated_at = <Date 2020-09-08.03:50:18.653>
user = 'https://github.com/PhillipMFeldman'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-08.03:50:18.653>
actor = 'veky'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-09-07.19:21:29.415>
creator = 'Phillip.M.Feldman@gmail.com'
dependencies = []
files = []
hgrepos = []
issue_num = 41740
keywords = []
message_count = 8.0
messages = ['376526', '376533', '376534', '376536', '376537', '376538', '376539', '376542']
nosy_count = 4.0
nosy_names = ['steven.daprano', 'Phillip.M.Feldman@gmail.com', 'veky', 'mpaolini']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41740'
versions = ['Python 3.8']
```

</p></details>

**Comment by yourlefthandman** [comment]
Hi :)
I've created a fix which I think makes sense based off the comments in this discussion. 
I'll note that it's my first code PR for python 😃 so I'd love feedback, even if the issue isn't critical enough to merge the fix (or the fix isn't correct)

**Comment by iritkatriel** [comment]
Closing as per https://github.com/python/cpython/pull/94710#issuecomment-1179805772.
