### ISSUE TITLE
Webbrowser Module Cannot Find xdg-settings on OSX

### ISSUE THREAD

**Issue by 131a3177-ec23-4a3c-95ab-61e1ebd85a3f** [python/cpython#85920]
BPO | [41754](https://bugs.python.org/issue41754)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @serhiy-storchaka, @miss-islington
PRs | <li>python/cpython#23075</li><li>python/cpython#23197</li><li>python/cpython#23198</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-09-10.06:15:31.730>
labels = ['OS-mac', 'easy', 'type-bug', '3.8', '3.9', '3.10', 'library']
title = 'Webbrowser Module Cannot Find xdg-settings on OSX'
updated_at = <Date 2021-02-08.17:07:14.253>
user = 'https://bugs.python.org/tonydiloreto'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-08.17:07:14.253>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2020-09-10.06:15:31.730>
creator = 'tony.diloreto'
dependencies = []
files = []
hgrepos = []
issue_num = 41754
keywords = ['patch', 'newcomer friendly']
message_count = 8.0
messages = ['376672', '378944', '379012', '380141', '380543', '380544', '380547', '386632']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'serhiy.storchaka', 'miss-islington', 'tony.diloreto']
pr_nums = ['23075', '23197', '23198']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41754'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
> Is it possible that your PATH contains a non-directory? Because it can give results a NotADirectoryError:
> 
> ```
> >>> subprocess.check_output(['xdg-settings', 'get', 'default-web-browser'], env={'PATH': '/etc/hosts'})
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/home/serhiy/py/cpython/Lib/subprocess.py", line 429, in check_output
>     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
>   File "/home/serhiy/py/cpython/Lib/subprocess.py", line 510, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/home/serhiy/py/cpython/Lib/subprocess.py", line 962, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/home/serhiy/py/cpython/Lib/subprocess.py", line 1840, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> NotADirectoryError: [Errno 20] Not a directory: 'xdg-settings'
> ```
> 
> Reopened because I afraid that there may be a severe configuration error hidden by silencing NotADirectoryError.
> 
> Could you please show os.environ['PATH'] on your computer?

Ignoring `NotADirectoryError` can ignore a configuration error, but this does match the behaviour of shells:

```sh
$ PATH=/etc/hosts ls                                                                                                             
zsh: command not found: ls
```

IMHO ignoring `NotADirectory` is the right thing to do here, there is no `xdc-settings` command found on the user's `PATH` even if that contains an invalid entry (not a directory or not existing). This avoids a strange error when the user has a directory on `PATH` that does not exist. One way this might happen is by having a shell profile that's shared between machines without having the same directory setup on all of them, I generally have the same PATH setting on all my test machines including `$HOME/.local/bin` but don't have that directory on all of them at all times.

I'm therefore reclining the issue.
