### ISSUE TITLE
Positional arguments with boolean actions behave differently

### ISSUE THREAD

**Issue by 9ae0cade-1ed1-46d4-8486-c4ffdcde33d5** [python/cpython#85935]
BPO | [41769](https://bugs.python.org/issue41769)
--- | :---
Nosy | @terryjreedy, @rjeffman

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-09-12.02:38:08.047>
labels = ['3.8', 'library']
title = 'Positional arguments with boolean actions behave differently'
updated_at = <Date 2020-09-21.14:45:29.058>
user = 'https://github.com/rjeffman'
```

bugs.python.org fields:
```python
activity = <Date 2020-09-21.14:45:29.058>
actor = 'rjeffman'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-09-12.02:38:08.047>
creator = 'rjeffman'
dependencies = []
files = []
hgrepos = []
issue_num = 41769
keywords = []
message_count = 4.0
messages = ['376764', '377141', '377241', '377258']
nosy_count = 3.0
nosy_names = ['terry.reedy', 'paul.j3', 'rjeffman']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'test needed'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41769'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-124839
* gh-124891
* gh-124898
* gh-124901
* gh-125302
* gh-125357
* gh-125358

**Comment by serhiy-storchaka** [comment]
See also #97848,

**Comment by serhiy-storchaka** [comment]
There are checks for 'store' and 'append' actions:
```py
        if nargs == 0:
            raise ValueError('nargs for store actions must be != 0; if you '
                             'have nothing to store, actions such as store '
                             'true or store const may be more appropriate')
```
```py
        if nargs == 0:
            raise ValueError('nargs for append actions must be != 0; if arg '
                             'strings are not supplying the value to append, '
                             'the append const action may be more appropriate')
```
They were here from the initial release of argparse.

There are also few general checks in `add_argument()`.

So there are precedences. We can either add checks in constructors of `BooleanOptionalAction`, `_StoreConstAction`,  `_AppendConstAction`, `_CountAction`, `_HelpAction` and `_VersionAction`, or add a general check in `add_argument()`. The latter looks easier.

I wonder if there is a case for an "anchor" action. For example, subparsers could have a positional argument with `action='store_const'` and difference `const` values, so the stored value would indicate what subparser was executed. But the same goal can be achieved by using `dest` in `add_subparsers()` or `set_defaults()` for subparser.
