### ISSUE TITLE
Consider reintroducing `types.EllipsisType` for the sake of typing

### ISSUE THREAD

**Issue by 6bb65b7e-2ff3-4135-b614-953562d22700** [python/cpython#85976]
BPO | [41810](https://bugs.python.org/issue41810)
--- | :---
Nosy | @gvanrossum, @rhettinger, @ericvsmith, @markshannon, @serhiy-storchaka, @ilevkivskyi, @SamuelMarks, @BvB93, @joshbode
PRs | <li>python/cpython#22336</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-09-22.15:55:57.057>
created_at = <Date 2020-09-18.19:29:00.494>
labels = ['type-feature', 'library', '3.10']
title = 'Consider reintroducing `types.EllipsisType` for the sake of typing'
updated_at = <Date 2020-11-05.09:51:11.541>
user = 'https://github.com/BvB93'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-05.09:51:11.541>
actor = 'eric.smith'
assignee = 'none'
closed = True
closed_date = <Date 2020-09-22.15:55:57.057>
closer = 'gvanrossum'
components = ['Library (Lib)']
creation = <Date 2020-09-18.19:29:00.494>
creator = 'BvB93'
dependencies = []
files = []
hgrepos = []
issue_num = 41810
keywords = ['patch']
message_count = 22.0
messages = ['377135', '377154', '377165', '377167', '377169', '377178', '377248', '377250', '377255', '377259', '377264', '377267', '377269', '377274', '377275', '377277', '377280', '377281', '377282', '377340', '380400', '380401']
nosy_count = 9.0
nosy_names = ['gvanrossum', 'rhettinger', 'eric.smith', 'Mark.Shannon', 'serhiy.storchaka', 'levkivskyi', 'samuelmarks', 'BvB93', 'joshbode']
pr_nums = ['22336']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41810'
versions = ['Python 3.10']
```

</p></details>

**Comment by tsibley** [comment]
How does one get access to the type of `Ellipsis` (for type annotation purposes, not at runtime) on Pythons older than 3.10, i.e. where the `types.EllipsisType` introduced here isn't available? There's `typing_extensions` for backported `typing` features, but no equivalent for `types`?

(The "right" place to raise this sort of issue/question isn't clear to me, so if this _isn't_ the right place, please let me know or point me elsewhere.)
