### ISSUE TITLE
os.waitid() documentation needs TLC

### ISSUE THREAD

**Issue by birkenfeld** [python/cpython#85991]
BPO | [41825](https://bugs.python.org/issue41825)
--- | :---
Nosy | @birkenfeld, @iritkatriel
PRs | <li>python/cpython#22356</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-09-21.16:41:50.762>
labels = ['easy', '3.9', '3.10', '3.11', 'type-feature', 'library', 'docs']
title = 'os.waitid() documentation needs TLC'
updated_at = <Date 2021-06-24.23:44:30.315>
user = 'https://github.com/birkenfeld'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-24.23:44:30.315>
actor = 'iritkatriel'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2020-09-21.16:41:50.762>
creator = 'georg.brandl'
dependencies = []
files = []
hgrepos = []
issue_num = 41825
keywords = ['patch', 'easy']
message_count = 2.0
messages = ['377263', '396516']
nosy_count = 3.0
nosy_names = ['georg.brandl', 'docs@python', 'iritkatriel']
pr_nums = ['22356']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41825'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by ddurgoji** [comment]
How do I know if a open issue has PR submitted/merged or not?
I saw few tickets which are in open state but already has a open or merged PR.

**Comment by iritkatriel** [comment]
> How do I know if a open issue has PR submitted/merged or not?
> I saw few tickets which are in open state but already has a open or merged PR.

Please use the core- mentorship list for general questions of this kind.
