### ISSUE TITLE
tempfile.py TemporaryDirectory/mkdtemp defaults to mode 0o700, propose to add mode argument

### ISSUE THREAD

**Issue by b415c998-5812-4870-b49e-ced607c918b9** [python/cpython#86050]
BPO | [41884](https://bugs.python.org/issue41884)
--- | :---
Nosy | @serhiy-storchaka, @ray-sit
PRs | <li>python/cpython#22451</li>
Files | <li>[tempfile.py](https://bugs.python.org/file49477/tempfile.py "Uploaded as text/plain at 2020-09-29.12:55:59 by @ray-sit")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-12-31.04:23:39.571>
created_at = <Date 2020-09-29.12:56:02.473>
labels = ['type-feature', 'library', '3.10']
title = 'tempfile.py TemporaryDirectory/mkdtemp defaults to mode 0o700, propose to add mode argument'
updated_at = <Date 2020-12-31.04:23:39.570>
user = 'https://github.com/ray-sit'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-31.04:23:39.570>
actor = 'ray-sit'
assignee = 'none'
closed = True
closed_date = <Date 2020-12-31.04:23:39.571>
closer = 'ray-sit'
components = ['Library (Lib)']
creation = <Date 2020-09-29.12:56:02.473>
creator = 'ray-sit'
dependencies = []
files = ['49477']
hgrepos = []
issue_num = 41884
keywords = []
message_count = 2.0
messages = ['377667', '377668']
nosy_count = 2.0
nosy_names = ['serhiy.storchaka', 'ray-sit']
pr_nums = ['22451']
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41884'
versions = ['Python 3.10']
```

</p></details>

**Comment by CharlesReinhardt** [comment]
A recent issue in the aws-cli (https://github.com/aws/aws-cli/issues/9114) would benefit from having a mode argument in `TemporaryDirectory/mkdtemp`, but it seems this change is not being considered. Commenting to link the issue to other relevant threads. We will find a different workaround for the aws-cli issue.
