### ISSUE TITLE
Long generator chain causes segmentation fault

### ISSUE THREAD

**Issue by dbe656a4-30a3-4c84-8061-94dd6a804b02** [python/cpython#86078]
BPO | [41912](https://bugs.python.org/issue41912)
--- | :---
Nosy | @tim-one, @terryjreedy
Files | <li>[gen_bug3.py](https://bugs.python.org/file49486/gen_bug3.py "Uploaded as text/plain at 2020-10-02.18:01:25 by karzes"): Causes a seg fault for large depth</li><li>[recurse_bug4.py](https://bugs.python.org/file49487/recurse_bug4.py "Uploaded as text/plain at 2020-10-02.21:09:58 by karzes"): Causes a seg fault for large depth</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-10-03.02:05:02.816>
created_at = <Date 2020-10-02.18:01:25.752>
labels = ['interpreter-core', 'invalid', 'type-crash']
title = 'Long generator chain causes segmentation fault'
updated_at = <Date 2020-10-05.02:01:18.118>
user = 'https://bugs.python.org/karzes'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-05.02:01:18.118>
actor = 'tim.peters'
assignee = 'none'
closed = True
closed_date = <Date 2020-10-03.02:05:02.816>
closer = 'terry.reedy'
components = ['Interpreter Core']
creation = <Date 2020-10-02.18:01:25.752>
creator = 'karzes'
dependencies = []
files = ['49486', '49487']
hgrepos = []
issue_num = 41912
keywords = []
message_count = 9.0
messages = ['377826', '377832', '377834', '377836', '377837', '377848', '377849', '377852', '377990']
nosy_count = 3.0
nosy_names = ['tim.peters', 'terry.reedy', 'karzes']
pr_nums = []
priority = 'normal'
resolution = 'not a bug'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue41912'
versions = ['Python 3.6']
```

</p></details>

**Comment by a-khabarov** [comment]
I think I might've accidentally reproduced this with the default recursion limit of 1000 on Python 3.11.4.
The following code prints 1000 and then segfaults.
```python
from itertools import chain
from sys import getrecursionlimit

x = ()
for i in range(1000000):
    x = chain(x, ())

print(getrecursionlimit())

next(x)
```

**Comment by carljm** [comment]
@a-khabarov I think rather that you are reporting the same issue as in #58218, which has had many, many duplicates over the years.

I think the only thing that would make your report new information is if you encountered it in real world code, rather than while attempting to stress-test the Python interpreter. Generally these cases only come up artificially.
