### ISSUE TITLE
Make IDLE Start Menu entry more descriptive

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#86074]
BPO | [41908](https://bugs.python.org/issue41908)
--- | :---
Nosy | @terryjreedy, @pfmoore, @tjguk, @ned-deily, @zware, @eryksun, @zooba, @E-Paine

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2020-10-02.09:56:26.429>
labels = ['expert-IDLE', 'type-feature', 'expert-installation', '3.10', 'OS-windows']
title = 'Make IDLE Start Menu entry more descriptive'
updated_at = <Date 2020-10-03.00:34:52.434>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-03.00:34:52.434>
actor = 'eryksun'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE', 'Installation', 'Windows']
creation = <Date 2020-10-02.09:56:26.429>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 41908
keywords = []
message_count = 3.0
messages = ['377805', '377818', '377844']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'paul.moore', 'tim.golden', 'ned.deily', 'zach.ware', 'eryksun', 'steve.dower', 'epaine']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue41908'
versions = ['Python 3.10']
```

</p></details>

**Comment by Zaid-Ahmad** [comment]
I'd like to contribute. However, being new to open source I have no clue how to proceed. I got the gist of the problem. Can anyone please give me a run through on how to go about it?

Thank you

**Comment by arhadthedev** [comment]
@Zaid-Ahmad The contributor's manual at https://devguide.python.org/ is a thorough guide enough for everything.

**Comment by zooba** [comment]
Start menu searching seems to change in every Windows release, unfortunately, so any ideas about how to make it easier to find get outdated really quickly.

We found that around Windows 7, the name of the folder stopped being helpful, which is why each item has all the info in it. And since Windows 10 it seems that executable names get searched just as strongly as the text, but since we don't have a dedicated IDLE executable (though we do in the Store package) that doesn't help.

@Zaid-Ahmad The changes for this will be somewhere under the `Tools/msi` folder - you can probably search for the existing strings and try changing them. But I think we need to see screenshots of the search behaviour to really get a feel for whether it's going to improve things or not.

**Comment by Zaid-Ahmad** [comment]
I don't find any issue. I use windows 11 and whenever I type "python" in the search bar, IDLE pops up which is what we wanted, right?
![ss](https://user-images.githubusercontent.com/39582467/181872206-ff3f0ed2-dd2a-44e3-9e26-df58e9606d80.png)

**Comment by Zaid-Ahmad** [comment]
I think the issue should be closed since it seems to be resolved @arhadthedev @eryksun @zooba @terryjreedy

**Comment by terryjreedy** [comment]
@Zaid-Ahmad I see 'IDLE (Python 3.10, 64 bit)' This issue is about changing this to 'IDLE Shell-Editor (3.10, 64 bit)' for the benefit of a newbie who does not know what IDLE is.  It seems that this would be difficult and I may close for that reason.

**Comment by Zaid-Ahmad** [comment]
Oh i see. But I don't think it is required to change the name since the course a person is taking to learn Python will mention that it is a shell editor. 

Changing the name won't make much of a difference. Right?

**Comment by erlend-aasland** [comment]
> @Zaid-Ahmad I see 'IDLE (Python 3.10, 64 bit)' This issue is about changing this to 'IDLE Shell-Editor (3.10, 64 bit)' for the benefit of a newbie who does not know what IDLE is. It seems that this would be difficult and I may close for that reason.

+1

IMO, it is not worth it to try to implement a non-trivial solution to something that is not an issue for the majority of users.

**Comment by Zaid-Ahmad** [comment]
> > @Zaid-Ahmad I see 'IDLE (Python 3.10, 64 bit)' This issue is about changing this to 'IDLE Shell-Editor (3.10, 64 bit)' for the benefit of a newbie who does not know what IDLE is. It seems that this would be difficult and I may close for that reason.
> 
> 
> 
> +1
> 
> 
> 
> IMO, it is not worth it to try to implement a non-trivial solution to something that is not an issue for the majority of users.

💯
