### ISSUE TITLE
Detect OEM code page for zip archives in ZipFile based on system locale

### ISSUE THREAD

**Issue by 0c49011a-ab29-4b67-907b-a43ebd6cc295** [python/cpython#86095]
BPO | [41929](https://bugs.python.org/issue41929)
--- | :---
Nosy | @eryksun
Files | <li>[windows_cyrillic.zip](https://bugs.python.org/file49492/windows_cyrillic.zip "Uploaded as application/zip at 2020-10-04.11:36:22 by ivan.sorokin.tech")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-04.11:36:22.751>
labels = ['library', '3.10']
title = 'Detect OEM code page for zip archives in ZipFile based on system locale'
updated_at = <Date 2020-10-04.15:42:42.504>
user = 'https://bugs.python.org/ivansorokintech'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-04.15:42:42.504>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-10-04.11:36:22.751>
creator = 'ivan.sorokin.tech'
dependencies = []
files = ['49492']
hgrepos = []
issue_num = 41929
keywords = []
message_count = 2.0
messages = ['377932', '377948']
nosy_count = 2.0
nosy_names = ['eryksun', 'ivan.sorokin.tech']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue41929'
versions = ['Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
You said by @eryksun, you can use ``ZipFile(encoding="oem)"``. I close the issue.

Python usually doesn't attempt to guess encodings, but let the developer do this dirty work: select the best encoding.
