### ISSUE TITLE
Runtime error while trying to use Python3.9 with virtualenv

### ISSUE THREAD

**Issue by c9ee1132-6bd3-41fe-8376-db3502fd14e8** [python/cpython#86114]
BPO | [41948](https://bugs.python.org/issue41948)
--- | :---
Files | <li>[Untitled picture.png](https://bugs.python.org/file49496/Untitled%20picture.png "Uploaded as image/png at 2020-10-05.20:36:17 by abhicantdraw"): Screenshot of error observed while trying to create new virtual environment</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-05.20:36:17.861>
labels = ['interpreter-core', 'type-bug', '3.9']
title = 'Runtime error while trying to use Python3.9 with virtualenv'
updated_at = <Date 2020-10-05.20:36:17.861>
user = 'https://bugs.python.org/abhicantdraw'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-05.20:36:17.861>
actor = 'abhicantdraw'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-10-05.20:36:17.861>
creator = 'abhicantdraw'
dependencies = []
files = ['49496']
hgrepos = []
issue_num = 41948
keywords = []
message_count = 1.0
messages = ['378074']
nosy_count = 1.0
nosy_names = ['abhicantdraw']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue41948'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
3.9 is no longer maintained. If you are having problems with a current version (>= 3.10) please create a new issue.

The reason this issue never received a reply is probably because there isn't enough information here to even begin to investigate the problem. In the future try giving more information - what steps you took to install it, what system you are running on, any info on the environment, etc.
