### ISSUE TITLE
Stop using PyDict_GetItem, PyDict_GetItemString and _PyDict_GetItemId

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#86172]
BPO | [42006](https://bugs.python.org/issue42006)
--- | :---
Nosy | @vstinner, @serhiy-storchaka, @hongweipeng
PRs | <li>python/cpython#22648</li><li>python/cpython#23487</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-11.14:36:40.426>
labels = ['extension-modules', 'interpreter-core', '3.10']
title = 'Stop using PyDict_GetItem, PyDict_GetItemString and _PyDict_GetItemId'
updated_at = <Date 2020-11-24.07:31:32.848>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-24.07:31:32.848>
actor = 'hongweipeng'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Interpreter Core']
creation = <Date 2020-10-11.14:36:40.426>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 42006
keywords = ['patch']
message_count = 6.0
messages = ['378437', '378460', '378462', '378463', '379643', '379645']
nosy_count = 3.0
nosy_names = ['vstinner', 'serhiy.storchaka', 'hongweipeng']
pr_nums = ['22648', '23487']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42006'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
See also https://github.com/python/cpython/issues/106033.

**Comment by erlend-aasland** [comment]
> See also #106033.

ISTM this can be closed as superseded.

**Comment by erlend-aasland** [comment]
@serhiy-storchaka, can we close this?

**Comment by vstinner** [comment]
> My plan is to deprecate PyDict_GetItem() and functions with same design flaw and finally remove them (in 4.0?).

Start maybe with a soft deprecation in Python 3.13?
