### ISSUE TITLE
ensurepip fails if cwd contains illformed setup.cf

### ISSUE THREAD

**Issue by a9f0f04e-d35d-4bb1-aab8-c9205db013c8** [python/cpython#86216]
BPO | [42050](https://bugs.python.org/issue42050)
--- | :---
Nosy | @ncoghlan, @dstufft, @pradyunsg, @con-f-use, @FFY00
Files | <li>[shell-session.txt](https://bugs.python.org/file49779/shell-session.txt "Uploaded as text/plain at 2021-01-30.11:31:04 by @con-f-use")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-16.08:27:23.104>
labels = ['3.8', '3.7', 'library', 'type-crash']
title = 'ensurepip fails if cwd contains illformed setup.cf'
updated_at = <Date 2021-01-30.11:31:05.012>
user = 'https://bugs.python.org/htgoebel'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-30.11:31:05.012>
actor = 'con-f-use'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-10-16.08:27:23.104>
creator = 'htgoebel'
dependencies = []
files = ['49779']
hgrepos = []
issue_num = 42050
keywords = []
message_count = 2.0
messages = ['378706', '385980']
nosy_count = 6.0
nosy_names = ['htgoebel', 'ncoghlan', 'dstufft', 'pradyunsg', 'con-f-use', 'FFY00']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue42050'
versions = ['Python 3.7', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
I'm unable to reproduce this on 3.12. Since (according to https://bugs.python.org/issue43038) it is related to distutils, it may no longer be relevant.

**Comment by iritkatriel** [comment]
So this issue is out date?

**Comment by pradyunsg** [comment]
Given that 3.7, 3.8 and 3.9 are in a security-fix status, I don't think we're gonna be fixing/changing the behaviour of distutils for this case. This would've been the first time I'm gonna click close on an issue on CPython with my "new" triage permissions. But, I'm gonna be cautious and avoid doing things wrong -- and defer to a core dev or another triager to close this. :)

**Comment by iritkatriel** [comment]
Closing on @pradyunsg's recommendation :)
