### ISSUE TITLE
For macOS, package the included Tcl and Tk frameworks in a rational way.

### ISSUE THREAD

**Issue by 6c6b8f17-f925-4a4a-bb51-e683b22af1e2** [python/cpython#86234]
BPO | [42068](https://bugs.python.org/issue42068)
--- | :---
Nosy | @ronaldoussoren, @ericvsmith, @ned-deily, @aivarannamaa

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/ned-deily'
closed_at = None
created_at = <Date 2020-10-18.13:20:59.214>
labels = ['OS-mac', 'type-feature', '3.9']
title = 'For macOS, package the included Tcl and Tk frameworks in a rational way.'
updated_at = <Date 2020-12-28.16:41:52.484>
user = 'https://bugs.python.org/culler'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-28.16:41:52.484>
actor = 'culler'
assignee = 'ned.deily'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2020-10-18.13:20:59.214>
creator = 'culler'
dependencies = []
files = []
hgrepos = []
issue_num = 42068
keywords = []
message_count = 8.0
messages = ['378860', '378862', '378864', '378867', '378873', '378883', '380508', '383904']
nosy_count = 5.0
nosy_names = ['ronaldoussoren', 'eric.smith', 'ned.deily', 'culler', 'Aivar.Annamaa']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42068'
versions = ['Python 3.9']
```

</p></details>

**Comment by arhadthedev** [comment]
> There were reasons why I chose to set things up the way they are now but it doesn't mean we need to continue to do it that way. I will be looking at macOS packaging issues this week during our development sprint and I will respond further to this issue then.

@ned-deily ping?

**Comment by ned-deily** [comment]
@culler, Marc, as part of some other internal changes in how we build and package python.org macOS installers as of Python 3.13.0b2, I've (finally!) adopted your suggestion to install `Tcl` and `Tk` in `/Library/Frameworks/Python.framework/Versions/X.Y/Frameworks` by using the standard Tcl and Tk `make -C macosx install-embedded SUBFRAMEWORK=1` build options. We still do not intend to support user replacement of any of the embedded third-party libraries included in the installer package this no doubt makes it easier for the advanced user who wants to experiment. Thanks!

**Comment by culler** [comment]
@ned-deily:  Great! I am very pleased to hear that.
