### ISSUE TITLE
Use specs instead of just __loader__ in C code

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#86298]
BPO | [42132](https://bugs.python.org/issue42132)
--- | :---
Nosy | @brettcannon, @corona10

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-23.22:16:01.448>
labels = ['interpreter-core', 'type-bug', '3.10']
title = 'Use specs instead of just __loader__ in C code'
updated_at = <Date 2020-10-24.16:28:23.690>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-24.16:28:23.690>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-10-23.22:16:01.448>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 42132
keywords = []
message_count = 1.0
messages = ['379483']
nosy_count = 2.0
nosy_names = ['brett.cannon', 'corona10']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42132'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-122227

**Comment by warsaw** [comment]
I'm going to take a look at these module attribute issues during the 2022 core sprint.

**Comment by warsaw** [comment]
I have `_warnings.c` implemented and tested.

**Comment by warsaw** [comment]
I think there's nothing to do for `pythonrun.c`.  These set `__loader__` but not `__spec__` directly, and [the documentation](https://docs.python.org/3.11/reference/import.html#main-spec) outlines the expected semantics.  If the documented semantics are incorrect, then there should be a separate tracking bug for that case.

Looking at `pylifecycle.c` next.

**Comment by warsaw** [comment]
I think `pylifecycle.c` is in the same boat.  So landing #97803 should close this ticket.

**Comment by warsaw** [comment]
Done!

**Comment by serhiy-storchaka** [comment]
These warnings are only emitted for the C implementation. See #122255.
