### ISSUE TITLE
Python Windows .exe Installer ignores /TargetDir if there is an existing installation

### ISSUE THREAD

**Issue by dc990c11-b690-479c-8cdd-838912d77c85** [python/cpython#86358]
BPO | [42192](https://bugs.python.org/issue42192)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @mcgfeller

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-10-29.09:16:07.299>
labels = ['3.8', 'type-feature', 'expert-installation', 'OS-windows']
title = 'Python Windows .exe Installer ignores /TargetDir if there is an existing installation'
updated_at = <Date 2020-10-31.17:15:03.333>
user = 'https://github.com/mcgfeller'
```

bugs.python.org fields:
```python
activity = <Date 2020-10-31.17:15:03.333>
actor = 'Martin.Gfeller'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2020-10-29.09:16:07.299>
creator = 'Martin.Gfeller'
dependencies = []
files = []
hgrepos = []
issue_num = 42192
keywords = []
message_count = 6.0
messages = ['379859', '379862', '379882', '379939', '380012', '380081']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'Martin.Gfeller']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42192'
versions = ['Python 3.8']
```

</p></details>

**Comment by mathstuf** [comment]
Seeing this as well. Our use case is to make relocatable prefixes that can be extracted during CI (to remove as much dependence on system state as possible). Alas, the headers and development libraries only exist in the `.exe` packages, so we're left running the `.exe` in a script. Since `TargetDir` is ignored if an existing install is present, we end up with a partial install that is packaged (basically `ensure_pip` is missing). It'd be nice to either have `TargetDir` taken into account for whether an install is eligible for replacement or `.zip` packages were provided with a development environment.

**Comment by zooba** [comment]
You can use the [packages from nuget.org](http://nuget.org/packages/python/) for CI installs. I added those for exactly that purpose (and Nuget was the most convenient tool for "find the latest version of this package for me" - you can automate downloading the client exe from https://aka.ms/nugetclidl if you need it in the build as well).

**Comment by mathstuf** [comment]
Is it possible to install nuget packages 100% locally to a specified directory and not touching the registry?

**Comment by mathstuf** [comment]
Hmm. How bad would it be just do skip `winget` and use the files directly? It looks like just extracting `tools` from the package gets me what I want (besides the tarbomb nature of it…)?

**Comment by zooba** [comment]
It's fine if you're pinning your version (and if you're paranoid, checking the file hash), and aren't relying on its caching options. Using `nuget` lets you be less specific about which version to get and it can resolve the best file, but if you don't care for that, using the file directly is fine.

After downloading and verifying the file, all it does is extract it (unless it's linking in a pre-cached copy, but that's not the default I believe).

**Comment by mathstuf** [comment]
Yes, we pin and hash verify in our CI (network hiccups happen and it's easier to see "file corrupt" than the job fail with something far down the line). I'll look at migrating to `winget` binaries instead to simplify things. Thanks!
