### ISSUE TITLE
Check if generated files are up-to-date in Github Actions

### ISSUE THREAD

**Issue by FFY00** [python/cpython#86378]
BPO | [42212](https://bugs.python.org/issue42212)
--- | :---
Nosy | @nascheme, @vstinner, @miss-islington, @FFY00
PRs | <li>python/cpython#23042</li><li>python/cpython#23423</li><li>python/cpython#23493</li><li>python/cpython#23494</li><li>python/cpython#24708</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-11-24.13:34:14.078>
created_at = <Date 2020-10-30.17:22:37.069>
labels = ['build', '3.8', '3.9', '3.10']
title = 'Check if generated files are up-to-date in Github Actions'
updated_at = <Date 2021-03-02.20:39:17.985>
user = 'https://github.com/FFY00'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-02.20:39:17.985>
actor = 'nascheme'
assignee = 'none'
closed = True
closed_date = <Date 2020-11-24.13:34:14.078>
closer = 'vstinner'
components = ['Build']
creation = <Date 2020-10-30.17:22:37.069>
creator = 'FFY00'
dependencies = []
files = []
hgrepos = []
issue_num = 42212
keywords = ['patch']
message_count = 8.0
messages = ['379989', '381482', '381483', '381484', '381720', '381731', '381732', '381738']
nosy_count = 4.0
nosy_names = ['nascheme', 'vstinner', 'miss-islington', 'FFY00']
pr_nums = ['23042', '23423', '23493', '23494', '24708']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue42212'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by itaisteinherz** [comment]
> While we are here... it might interesting to also run patchcheck.py on PRs using GitHub Actions: https://mail.python.org/archives/list/python-dev@python.org/message/DKLD2VLHZ3F54WTKZ7JHKWBMOZ4N5TK7/
> 
> .travis.yml uses:
> 
> script: # Using the built Python as patchcheck.py is built around the idea of using # a checkout-build of CPython to know things like what base branch the changes # should be compared against. # Only run on Linux as the check only needs to be run once.
> 
> * if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./python [Tools/scripts/patchcheck.py](https://github.com/python/cpython/blob/main/Tools/scripts/patchcheck.py) --travis $TRAVIS_PULL_REQUEST; fi

@vstinner Did this happen? I currently don't see a patchcheck job on my PRs, and think it should be added.

**Comment by vstinner** [comment]
> @vstinner Did this happen? I currently don't see a patchcheck job on my PRs, and think it should be added.

I don't know. If it's missing, you can propose a PR to add the check.
