### ISSUE TITLE
f_trace gets call on different lines each loop

### ISSUE THREAD

**Issue by 4024428b-f4bb-459f-ab06-0807e9217f04** [python/cpython#86452]
BPO | [42286](https://bugs.python.org/issue42286)
--- | :---
Nosy | @MegaIng
Files | <li>[f_trace_wrong_line.py](https://bugs.python.org/file49580/f_trace_wrong_line.py "Uploaded as text/plain at 2020-11-07.22:19:52 by @MegaIng")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-07.22:19:52.971>
labels = ['interpreter-core', 'type-bug', '3.9']
title = 'f_trace gets call on different lines each loop'
updated_at = <Date 2020-11-07.22:19:52.971>
user = 'https://github.com/MegaIng'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-07.22:19:52.971>
actor = 'MegaIng'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2020-11-07.22:19:52.971>
creator = 'MegaIng'
dependencies = []
files = ['49580']
hgrepos = []
issue_num = 42286
keywords = []
message_count = 1.0
messages = ['380527']
nosy_count = 1.0
nosy_names = ['MegaIng']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42286'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
I always get line 25 on main (3.14) on a Mac.

**Comment by iritkatriel** [comment]
CC @gaogaotiantian

**Comment by gaogaotiantian** [comment]
In recent versions we have made plenty of improvement (changes) related to line number calculation. The tracing mechanism has been completely different as well. I can't repro this on 3.14 either. Actually I can only repro this on 3.9 (something in 3.10 fixed it). As 3.9 does not take bug fixes anymore, there's really nothing we can do here. So I'll just close this.
