### ISSUE TITLE
C API: Add PyModule_Add() function

### ISSUE THREAD

**Issue by serhiy-storchaka** [python/cpython#86493]
BPO | [42327](https://bugs.python.org/issue42327)
--- | :---
Nosy | @vstinner, @ambv, @serhiy-storchaka, @brandtbucher
PRs | <li>python/cpython#23240</li><li>python/cpython#23443</li><li>python/cpython#28741</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-11.20:35:14.453>
labels = ['expert-C-API', 'type-feature', '3.10']
title = 'Add PyModule_Add()'
updated_at = <Date 2021-10-05.17:30:16.409>
user = 'https://github.com/serhiy-storchaka'
```

bugs.python.org fields:
```python
activity = <Date 2021-10-05.17:30:16.409>
actor = 'lukasz.langa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-11-11.20:35:14.453>
creator = 'serhiy.storchaka'
dependencies = []
files = []
hgrepos = []
issue_num = 42327
keywords = ['patch']
message_count = 9.0
messages = ['380794', '380795', '380818', '380819', '380820', '380821', '380829', '380833', '384812']
nosy_count = 4.0
nosy_names = ['vstinner', 'lukasz.langa', 'serhiy.storchaka', 'brandtbucher']
pr_nums = ['23240', '23443', '28741']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42327'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-106767
* gh-106768
* gh-106849
* gh-106851
* gh-106855
* gh-106858
* gh-106860
* gh-106863

**Comment by vstinner** [comment]
@serhiy-storchaka: So what's the status of this API?

**Comment by serhiy-storchaka** [comment]
I extracted some changes in two separate PRs: #106767 fixes some bugs by using `PyModule_AddObjectRef()`, and #106768 fixes other bugs by using new _private_ function `_PyModule_AddNew()`. Both these PRs can be backported. I hope there are no objections against this. Adding a new _public_ function `PyModule_AddNew()` has been left to other PR.
