### ISSUE TITLE
UnicodeDecodeError executing ./setup.py during build

### ISSUE THREAD

**Issue by smontanaro** [python/cpython#86491]
BPO | [42325](https://bugs.python.org/issue42325)
--- | :---
Nosy | @smontanaro, @yan12125
Files | <li>[m17n-X.h](https://bugs.python.org/file49593/m17n-X.h "Uploaded as text/x-chdr at 2020-11-11.13:57:47 by @smontanaro")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-11.13:57:47.745>
labels = ['build', '3.10']
title = 'UnicodeDecodeError executing ./setup.py during build'
updated_at = <Date 2020-11-14.05:01:23.448>
user = 'https://github.com/smontanaro'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-14.05:01:23.448>
actor = 'yan12125'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2020-11-11.13:57:47.745>
creator = 'skip.montanaro'
dependencies = []
files = ['49593']
hgrepos = []
issue_num = 42325
keywords = []
message_count = 2.0
messages = ['380761', '380956']
nosy_count = 2.0
nosy_names = ['skip.montanaro', 'yan12125']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42325'
versions = ['Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
This seems likely fixed in https://github.com/python/cpython/issues/86517 and `setup.py` is now removed.
