### ISSUE TITLE
Add helpers to populate modules in C

### ISSUE THREAD

**Issue by tiran** [python/cpython#86542]
BPO | [42376](https://bugs.python.org/issue42376)
--- | :---
Nosy | @tiran, @serhiy-storchaka, @shihai1991, @erlend-aasland
PRs | <li>python/cpython#23286</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = None
created_at = <Date 2020-11-16.19:27:21.162>
labels = ['expert-C-API', 'type-feature', '3.10']
title = 'Add helpers to populate modules in C'
updated_at = <Date 2021-11-16.17:23:51.530>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-16.17:23:51.530>
actor = 'erlendaasland'
assignee = 'christian.heimes'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2020-11-16.19:27:21.162>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 42376
keywords = ['patch']
message_count = 1.0
messages = ['381144']
nosy_count = 4.0
nosy_names = ['christian.heimes', 'serhiy.storchaka', 'shihai1991', 'erlendaasland']
pr_nums = ['23286']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42376'
versions = ['Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
With 2 years of extra experience, I see issues in this proposal -- see https://github.com/capi-workgroup/decisions/issues/6#issuecomment-1878729034

If anyone would like to move any part of this proposal forward, feel free to bounce ideas off me. I recommend tackling *adding types* separately from the module constants.

**Comment by rruuaanng** [comment]
> With 2 years of extra experience, I see issues in this proposal -- see [capi-workgroup/decisions#6 (comment)](https://github.com/capi-workgroup/decisions/issues/6#issuecomment-1878729034)
> 
> If anyone would like to move any part of this proposal forward, feel free to bounce ideas off me. I recommend tackling _adding types_ separately from the module constants.

Can you explain your viewpoint? That is, `separate types from module constants`. When I was working on https://github.com/python/cpython/issues/127435, I had to review the content of the proposal. In other words, I want to take over part of the proposal.

**Comment by encukou** [comment]
I suggest to come up with a different mechanism for *constants* (where creating the Python object is rather trivial and unchanging) and for *types* (every few releases we get a new `PyType_From*` type-creation function). I don't think they should be bundled together in one issue like here.
