### ISSUE TITLE
Empty body {} in POST requests leads to 405 Method not allowed error

### ISSUE THREAD

**Issue by 07d82778-4c22-4677-9c23-029264566ab1** [python/cpython#86583]
BPO | [42417](https://bugs.python.org/issue42417)
--- | :---
Nosy | @pfmoore, @ronaldoussoren, @tiran, @tjguk, @zware, @zooba, @akulakov
Files | <li>[sample_flask.py](https://bugs.python.org/file49609/sample_flask.py "Uploaded as text/plain at 2020-11-20.09:20:22 by bhushan.shelke")</li><li>[flask_client.py](https://bugs.python.org/file49623/flask_client.py "Uploaded as text/plain at 2020-11-25.16:25:54 by bhushan.shelke")</li><li>[flask_client_long_headers.py](https://bugs.python.org/file49676/flask_client_long_headers.py "Uploaded as text/plain at 2020-12-14.07:50:06 by bhushan.shelke")</li><li>[packet-1.PNG](https://bugs.python.org/file49677/packet-1.PNG "Uploaded as image/png at 2020-12-14.08:01:46 by bhushan.shelke")</li><li>[packet-2.PNG](https://bugs.python.org/file49678/packet-2.PNG "Uploaded as image/png at 2020-12-14.08:02:43 by bhushan.shelke")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-20.09:20:23.321>
labels = ['type-bug', 'library', '3.9', 'OS-windows']
title = 'Empty body {} in POST requests leads to 405 Method not allowed error'
updated_at = <Date 2020-12-27.03:32:41.900>
user = 'https://bugs.python.org/bhushanshelke'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-27.03:32:41.900>
actor = 'andrei.avk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2020-11-20.09:20:23.321>
creator = 'bhushan.shelke'
dependencies = []
files = ['49609', '49623', '49676', '49677', '49678']
hgrepos = []
issue_num = 42417
keywords = []
message_count = 15.0
messages = ['381470', '381471', '381472', '381473', '381474', '381835', '381836', '381840', '381846', '382798', '382808', '382959', '382960', '382961', '383835']
nosy_count = 8.0
nosy_names = ['paul.moore', 'ronaldoussoren', 'christian.heimes', 'tim.golden', 'zach.ware', 'steve.dower', 'bhushan.shelke', 'andrei.avk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42417'
versions = ['Python 3.9']
```

</p></details>

**Comment by arhadthedev** [comment]
Closing as unreproducible.
