### ISSUE TITLE
Improve colorsys.rgb_to_hls code

### ISSUE THREAD

**Issue by 0eb9db4e-4cc4-4cda-83ec-ccd093da7213** [python/cpython#86618]
BPO | [42452](https://bugs.python.org/issue42452)
--- | :---
Nosy | @terryjreedy, @jjerphan
PRs | <li>python/cpython#23306</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2020-11-28.07:12:39.305>
created_at = <Date 2020-11-24.14:09:55.925>
labels = ['type-feature', 'library', '3.10']
title = 'Improve colorsys.rgb_to_hls code'
updated_at = <Date 2020-11-28.07:12:39.304>
user = 'https://github.com/jjerphan'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-28.07:12:39.304>
actor = 'terry.reedy'
assignee = 'none'
closed = True
closed_date = <Date 2020-11-28.07:12:39.305>
closer = 'terry.reedy'
components = ['Library (Lib)']
creation = <Date 2020-11-24.14:09:55.925>
creator = 'jjerphan'
dependencies = []
files = []
hgrepos = []
issue_num = 42452
keywords = []
message_count = 3.0
messages = ['381748', '381981', '381982']
nosy_count = 2.0
nosy_names = ['terry.reedy', 'jjerphan']
pr_nums = ['23306']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42452'
versions = ['Python 3.10']
```

</p></details>

**Comment by terryjreedy** [comment]
As noted in issue #106498, the TODO comment and this patch were incorrect in that `2.0 - maxc - minc` does not equal `2.0 - (maxc + minc)` for `maxc, minc = 1.0,  0.9999999999999999` because the float sum is 2.0, leaving 0.0 and causing ZeroDivisionError, whereas the correct subtraction leaves `1.1102230246251565e-16`.
