### ISSUE TITLE
Pathlib resolve() resolves non-existent ".." components with strict=False

### ISSUE THREAD

**Issue by 44063462-a634-414b-9e1a-17e8ad86c669** [python/cpython#86630]
BPO | [42464](https://bugs.python.org/issue42464)
--- | :---
Nosy | @serhiy-storchaka, @eryksun, @eamanu, @akulakov
Files | <li>[do_not_resolve_dotdot_nonexistent.patch](https://bugs.python.org/file50141/do_not_resolve_dotdot_nonexistent.patch "Uploaded as text/plain at 2021-07-08.13:12:56 by @akulakov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-25.16:07:29.278>
labels = ['3.8', 'type-bug', 'library', '3.9', '3.10']
title = 'Pathlib resolve() resolves non-existent ".." components with strict=False'
updated_at = <Date 2021-07-08.14:30:01.681>
user = 'https://bugs.python.org/johnengelke'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-08.14:30:01.681>
actor = 'andrei.avk'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-11-25.16:07:29.278>
creator = 'john.engelke'
dependencies = []
files = ['50141']
hgrepos = []
issue_num = 42464
keywords = ['patch']
message_count = 5.0
messages = ['381844', '386095', '386118', '397138', '397143']
nosy_count = 5.0
nosy_names = ['serhiy.storchaka', 'eryksun', 'eamanu', 'john.engelke', 'andrei.avk']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42464'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
What's the use case for leaving `..` segments in the path? I understand that an an attacker could create symlinks at paths that were elided by subsequent `..` segments, and so change the resolved path, but couldn't an attacker do that with any other partially-resolved path, or even a fully-resolved path? It doesn't seem to move the needle with the TOCTOU problem

**Comment by eamanu** [comment]
Hi, I think this issue should be closed. The path is resolved as is possible, and I think that documentation is clear enough:
`“..” components are also eliminated (this is the only method to do so):`

**Comment by barneygale** [comment]
Thanks @eamanu.

A further reason: `Path.resolve()` calls straight through to `os.path.realpath()` nowadays, and I wouldn't want them to diverge.

This could be considered as a feature request, but it would need buy-in on discuss.python.org and ideally examples of other languages/runtimes implementing this behaviour.

Closing this as "not planned", but if anyone feels this is wrong, leave a comment and I'll re-open.
