### ISSUE TITLE
Add to pathlib function to check permission similar to os.access

### ISSUE THREAD

**Issue by 47db5878-9343-4477-add0-466fcc095801** [python/cpython#86647]
BPO | [42481](https://bugs.python.org/issue42481)
--- | :---
Nosy | @tiran, @eryksun, @m-aciek, @copalco

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-27.09:57:19.675>
labels = ['type-feature']
title = 'Add to pathlib function to check permission similar to os.access'
updated_at = <Date 2020-11-30.19:16:41.305>
user = 'https://github.com/copalco'
```

bugs.python.org fields:
```python
activity = <Date 2020-11-30.19:16:41.305>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2020-11-27.09:57:19.675>
creator = 'copalco'
dependencies = []
files = []
hgrepos = []
issue_num = 42481
keywords = []
message_count = 5.0
messages = ['381940', '381943', '381948', '381953', '382178']
nosy_count = 4.0
nosy_names = ['christian.heimes', 'eryksun', 'Maciej Olko', 'copalco']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42481'
versions = []
```

</p></details>

**Comment by barneygale** [comment]
> A word of warning: os.access() is not a good and sufficient permission check. It only checks DAC (discrete access control) permissions and suffers from TOCTOU issues. Operating systems have additional permission checks and security policies, for example mandatory access control (AppArmor, SELinux, Smack) and seccomp.

For these reasons, I don't think an `.access()` method is a good fit for pathlib; it's too difficult to use safely. The implementation isn't obvious (per the above discussion) and I don't think the API is either.

Closing as not planned, but if anyone feels aggrieved, please leave a comment and I'll re-open. Cheers.

**Comment by m-aciek** [comment]
For the record there's a discussion thread about exposing `mode` in pathlib: https://discuss.python.org/t/expose-file-size-mode-etc-from-pathlib-path-info/103828.
