### ISSUE TITLE
test_ttk_guionly test failures on macOS with Tcl/Tk 8.6.10

### ISSUE THREAD

**Issue by ned-deily** [python/cpython#86673]
BPO | [42507](https://bugs.python.org/issue42507)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @vstinner, @ned-deily, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-11-30.02:46:40.854>
labels = ['OS-mac', '3.8', 'expert-tkinter', '3.9', '3.10']
title = 'test_ttk_guionly test failures on macOS with Tcl/Tk 8.6.10'
updated_at = <Date 2021-01-27.11:55:43.827>
user = 'https://github.com/ned-deily'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-27.11:55:43.827>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Tkinter']
creation = <Date 2020-11-30.02:46:40.854>
creator = 'ned.deily'
dependencies = []
files = []
hgrepos = []
issue_num = 42507
keywords = []
message_count = 12.0
messages = ['382109', '382121', '382175', '382206', '382296', '382328', '382364', '382428', '382441', '382446', '382447', '385764']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'vstinner', 'ned.deily', 'serhiy.storchaka']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42507'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-123335
* gh-124654
* gh-124655
* gh-125335
* gh-125390
* gh-125391

**Comment by erlend-aasland** [comment]
FWIW, I'm unable to reproduce on Python 3.9 through 3.11 (python.org binarier). I _can_ reproduce with Homebrew supplied Python 3.8, though.

**Comment by ronaldoussoren** [comment]
What's the Tcl/Tk version for the homebrew installation? (``python -m test.pythoninfo``).

If that's an older version than 8.6.12 this could be a bug in Tcl/Tk.

**Comment by erlend-aasland** [comment]
> What's the Tcl/Tk version for the homebrew installation? (`python -m test.pythoninfo`).
> 
> If that's an older version than 8.6.12 this could be a bug in Tcl/Tk.

Same version as we supply:

```
$ python3.9 -m test.pythoninfo | grep tkinter
tkinter.TCL_VERSION: 8.6
tkinter.TK_VERSION: 8.6
tkinter.info_patchlevel: 8.6.12
$ python3.8 -m test.pythoninfo | grep tkinter
tkinter.TCL_VERSION: 8.6
tkinter.TK_VERSION: 8.6
tkinter.info_patchlevel: 8.6.12
```

FTR, ditto for 3.10 and 3.11.

**Comment by ronaldoussoren** [comment]
I ran "python3.13 -m test test_tkinter -v -u gui" for a ``--with-pydebug`` framework build with two different builds of Tkinter: deployment target 10.9 and deployment target 14.0.  The build of Tkinter is otherwise the same as in our installers, including the additional patches.

The framework itself was build using the default deployment target on 14.2.

In both runs I get no test failures.

**Comment by terryjreedy** [comment]
I get the same 2 failures running test_ttk either way (`test.test_ttk`, `test -ugui test_ttk`) with installed 3.13.0a2 on MacBook Air Catalina.  (Note: I have occasionally gotten different results running test_idle on my Windows machine the two different ways.)

**Comment by ronaldoussoren** [comment]
> I get the same 2 failures running test_ttk either way (`test.test_ttk`, `test -ugui test_ttk`) with installed 3.13.0a2 on MacBook Air Catalina. (Note: I have occasionally gotten different results running test_idle on my Windows machine the two different ways.)

It is easy enough to change the test code to avoid these failures, but because I'm not familiar with Tkinter I need some guidance on what the identify method is supposed to do. 

Two "obvious" changes:

1. Accept both values (e.g. change `self.IDENTIFY_AS` to a tuple and use `self.assertIn` instead of `self.assertEqual`)
2. Probe at a different `(x, y)` coordinate like I do in the diff I posted earlier to get the value the test expects

**Comment by terryjreedy** [comment]
It is a bit confusing in https://github.com/python/cpython/issues/86673#issuecomment-1870379283 that the failed test is in ComboboxTest, which inherits from EntryTest, whereas the probe code tests an *Entry* widget, whose EntryTest itself test passed.

I am still learning ttk stuff.  `identify` is a ttk-specific widget [method](https://docs.python.org/3/library/tkinter.ttk.html#tkinter.ttk.Widget.identify): "Returns the name of the element at position x y".  An [element](https://www.tcl.tk/man/tcl8.6/TkCmd/ttk_intro.html) "displays an individual part of a widget."  A main point of ttk widgets is to give more control over the widget elements and their appearance.  For a Combobox widget, the expected parts at 5,5
are `IDENTIFY_AS = 'Combobox.field' if sys.platform == 'darwin' else 'textarea'`.

How is CI passing if this test fails?  Or does it pass on the CI machines?

You need an answer from @serhiy-storchaka , not me, as to which fix, if either, he prefers.

**Comment by smontanaro** [comment]
I can verify both the `test_ttk` error and that both of @ronaldoussoren's patches fix the error. I agree it seems that `test_identify` seems a bit fragile.

**Comment by serhiy-storchaka** [comment]
Please test also the following patch. For some reasons I think that it may be safer to create a new layout than modify an existing layout.

```diff
diff --git a/Lib/test/test_ttk/test_style.py b/Lib/test/test_ttk/test_style.py
index 9a04a95dc40..8b1993c8950 100644
--- a/Lib/test/test_ttk/test_style.py
+++ b/Lib/test/test_ttk/test_style.py
@@ -227,13 +227,13 @@ def test_element_create_image(self):
                                    foreground='blue', background='yellow')
         img3 = tkinter.BitmapImage(master=self.root, file=imgfile,
                                    foreground='white', background='black')
-        style.element_create('Button.button', 'image',
+        style.element_create('TestButton1.button', 'image',
                              img1, ('pressed', img2), ('active', img3),
                              border=(2, 4), sticky='we')
-        self.assertIn('Button.button', style.element_names())
+        self.assertIn('TestButton1.button', style.element_names())
 
-        style.layout('Button', [('Button.button', {'sticky': 'news'})])
-        b = ttk.Button(self.root, style='Button')
+        style.layout('TestButton1', [('TestButton1.button', {'sticky': 'news'})])
+        b = ttk.Button(self.root, style='TestButton1')
         b.pack(expand=True, fill='both')
         self.assertEqual(b.winfo_reqwidth(), 16)
         self.assertEqual(b.winfo_reqheight(), 16)
```

**Comment by erlend-aasland** [comment]
@serhiy-storchaka, I agree that amending the test by creating a new layout is a better solution.

**Comment by erlend-aasland** [comment]
I merged a variant of Serhiy's suggestion; thanks all!

**Comment by erlend-aasland** [comment]
FTR, `test.test_ttk.test_widgets.ComboboxTest.test_identify` still needs to be fixed.

**Comment by erlend-aasland** [comment]
Ronald:

> One way to silence the test failure is to probe the widget at a different location:
> 
> ```diff
> diff --git a/Lib/test/test_ttk/test_widgets.py b/Lib/test/test_ttk/test_widgets.py
> index fd1a748a49..407bd1bb4b 100644
> --- a/Lib/test/test_ttk/test_widgets.py
> +++ b/Lib/test/test_ttk/test_widgets.py
> @@ -341,7 +341,7 @@ def test_identify(self):
>          self.entry.update()
>  
>          # bpo-27313: macOS Cocoa widget differs from X, allow either
> -        self.assertEqual(self.entry.identify(5, 5), self.IDENTIFY_AS)
> +        self.assertEqual(self.entry.identify(1, 1), self.IDENTIFY_AS)
>          self.assertEqual(self.entry.identify(-1, -1), "")
>  
>          self.assertRaises(tkinter.TclError, self.entry.identify, None, 5)
> ```
> 
> Again, I'm a Tkinter newby and don't understand what I'm doing here, and also don't know what this tries to test.

@serhiy-storchaka, any thoughts regarding Ronald's suggestion for `test_identify`? (cc. @chrstphrchvz) 

(FTR, I'm unable to reproduce the `test_identify` failure locally.)

**Comment by erlend-aasland** [comment]
Nah, the patch from https://github.com/python/cpython/issues/86673#issuecomment-2378588390 does not make things better :(

**Comment by erlend-aasland** [comment]
See also #71500.

**Comment by erlend-aasland** [comment]
The `test_identify` tests all pass in my dev environment. I observe that I've got Tk/Tcl 8.6.14, and the CI's got Tk/Tcl 8.6.15. (That may or may not be relevant.) Anyway, based on the CI failures and the results on my setup, it seems the macOS workarounds of #71500 are sometimes not needed for `ComboboxTest`. On my system, they're still needed. Perhaps we should just adjust these tests to allow both kinds of results; the "generic" `self.entry.identify == "textarea"`, and the macOS workarounds of #71500.

IOW, something a la this:

```diff
diff --git a/Lib/test/test_ttk/test_widgets.py b/Lib/test/test_ttk/test_widgets.py
index 88740b18864..2b22ed75f27 100644
--- a/Lib/test/test_ttk/test_widgets.py
+++ b/Lib/test/test_ttk/test_widgets.py
@@ -336,7 +336,7 @@ class EntryTest(AbstractWidgetTest, unittest.TestCase):
         'show', 'state', 'style', 'takefocus', 'textvariable',
         'validate', 'validatecommand', 'width', 'xscrollcommand',
     )
-    IDENTIFY_AS = 'Entry.field' if sys.platform == 'darwin' else 'textarea'
+    IDENTIFY_AS = {'Entry.field', 'textarea'}
 
     def setUp(self):
         super().setUp()
@@ -374,7 +374,7 @@ def test_identify(self):
         self.entry.update()
 
         # bpo-27313: macOS Cocoa widget differs from X, allow either
-        self.assertEqual(self.entry.identify(5, 5), self.IDENTIFY_AS)
+        self.assertIn(self.entry.identify(5, 5), self.IDENTIFY_AS)
         self.assertEqual(self.entry.identify(-1, -1), "")
 
         self.assertRaises(tkinter.TclError, self.entry.identify, None, 5)
@@ -461,7 +461,7 @@ class ComboboxTest(EntryTest, unittest.TestCase):
         'validate', 'validatecommand', 'values',
         'width', 'xscrollcommand',
     )
-    IDENTIFY_AS = 'Combobox.button' if sys.platform == 'darwin' else 'textarea'
+    IDENTIFY_AS = {'Combobox.button', 'textarea'}
 
     def setUp(self):
         super().setUp()
@@ -1204,7 +1204,7 @@ class SpinboxTest(EntryTest, unittest.TestCase):
         'takefocus', 'textvariable', 'to', 'validate', 'validatecommand',
         'values', 'width', 'wrap', 'xscrollcommand',
     )
-    IDENTIFY_AS = 'Spinbox.field' if sys.platform == 'darwin' else 'textarea'
+    IDENTIFY_AS = {'Spinbox.field', 'textarea'}
 
     def setUp(self):
         super().setUp()

```

**Comment by erlend-aasland** [comment]
I believe we can close this; thanks to everyone involved.
