### ISSUE TITLE
Make asyncio.__main__ reusable, also adding a preamble feature.

### ISSUE THREAD

**Issue by e11f494a-83fc-4958-93e8-f1d9d6a4afef** [python/cpython#86723]
BPO | [42557](https://bugs.python.org/issue42557)
--- | :---
Nosy | @asvetlov, @1st1, @lschoe
PRs | <li>python/cpython#24055</li>
Files | <li>[__main__.py](https://bugs.python.org/file49652/__main__.py "Uploaded as text/plain at 2020-12-03.15:34:44 by @lschoe"): mpyc.__main__.py based on asyncio.__main__.py</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-03.15:34:45.493>
labels = ['type-feature', '3.10', 'expert-asyncio']
title = 'Make asyncio.__main__ reusable, also adding a preamble feature.'
updated_at = <Date 2021-01-02.22:07:25.824>
user = 'https://github.com/lschoe'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-02.22:07:25.824>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-12-03.15:34:45.493>
creator = 'lschoe'
dependencies = []
files = ['49652']
hgrepos = []
issue_num = 42557
keywords = ['patch']
message_count = 1.0
messages = ['382419']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'lschoe']
pr_nums = ['24055']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42557'
versions = ['Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
I don't think this should added, this would become a maintenance burden. If you need this just copy the code form asyncio and modify it as you like.
