### ISSUE TITLE
PEP 594 Removing dead batteries from stdlib

### ISSUE THREAD

**Issue by aeros** [python/cpython#86777]
BPO | [42611](https://bugs.python.org/issue42611)
--- | :---
Nosy | @terryjreedy, @tiran, @jkloth, @isidentical, @aeros
PRs | <li>python/cpython#23728</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-10.04:51:12.046>
labels = ['type-feature', 'library', '3.10']
title = 'PEP 594 Removing dead batteries from stdlib'
updated_at = <Date 2020-12-12.01:54:23.481>
user = 'https://github.com/aeros'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-12.01:54:23.481>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2020-12-10.04:51:12.046>
creator = 'aeros'
dependencies = []
files = []
hgrepos = []
issue_num = 42611
keywords = []
message_count = 2.0
messages = ['382815', '382898']
nosy_count = 5.0
nosy_names = ['terry.reedy', 'christian.heimes', 'jkloth', 'BTaskaya', 'aeros']
pr_nums = ['23728']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42611'
versions = ['Python 3.10']
```

</p></details>

**Comment by arhadthedev** [comment]
Repurposing this issue for 3.13.

**Comment by hugovk** [comment]
I've made a start on removing the more straightforward ones in a branch.

Would it be better with all in one PR, as one PR per module, or somewhere in the middle with smaller batches?

**Comment by arhadthedev** [comment]
I would vote for the *one PR per module* option. It allows reviewers to not get lost with each removed module having:

- Python code
- tests
- documentation
- probably a C module
  - associated automake/Makefile and Visual Studio rules
  - also we need to check for `_Py*` functions added exclusively for the module and used nowhere else.

**Comment by arhadthedev** [comment]
Closing in favor of gh-104773.
