### ISSUE TITLE
C Extensions on Darwin that link against libpython are likely to crash

### ISSUE THREAD

**Issue by 62958ad8-c430-4a4f-81e6-ee833cc6b8c5** [python/cpython#86782]
BPO | [42616](https://bugs.python.org/issue42616)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @merwok, @zooba, @dstufft

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-10.20:21:24.861>
labels = ['3.8', '3.9', 'extension-modules', 'expert-C-API', 'build', 'type-crash', 'OS-mac', '3.10']
title = 'C Extensions on Darwin that link against libpython are likely to crash'
updated_at = <Date 2021-02-03.21:44:00.414>
user = 'https://bugs.python.org/froody'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-03.21:44:00.414>
actor = 'froody'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build', 'Extension Modules', 'macOS', 'C API']
creation = <Date 2020-12-10.20:21:24.861>
creator = 'froody'
dependencies = []
files = []
hgrepos = []
issue_num = 42616
keywords = []
message_count = 9.0
messages = ['382841', '382860', '382878', '382883', '382885', '382907', '382908', '386226', '386458']
nosy_count = 6.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'eric.araujo', 'steve.dower', 'dstufft', 'froody']
pr_nums = []
priority = 'low'
resolution = 'out of date'
stage = 'resolved'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue42616'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
I don't think we can do anything about this other than documenting that you shouldn't link extensions to libpython. AFAIK this is already best practice on unixy platforms.

The ``-bundle_loader ...`` option I mention in an earlier comment won't help here.

**Comment by ronaldoussoren** [comment]
I'm closing this issue again because linking C extensions to libpython is not a supported configuration and is not used by CPython itself or setuptools.
