### ISSUE TITLE
sqlite3 package document mistake

### ISSUE THREAD

**Issue by 6cc938b9-f8b3-4a1e-9079-51cd16a76708** [python/cpython#86790]
BPO | [42624](https://bugs.python.org/issue42624)
--- | :---
Nosy | @terryjreedy, @berkerpeksag, @erlend-aasland, @seeker-Liu

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-12.08:47:49.871>
labels = ['type-bug', '3.9', 'docs']
title = 'sqlite3 package document mistake'
updated_at = <Date 2021-02-12.12:00:09.639>
user = 'https://github.com/seeker-Liu'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-12.12:00:09.639>
actor = 'erlendaasland'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2020-12-12.08:47:49.871>
creator = 'seeker-Liu'
dependencies = []
files = []
hgrepos = []
issue_num = 42624
keywords = []
message_count = 7.0
messages = ['382904', '383329', '383367', '386859', '386860', '386861', '386862']
nosy_count = 6.0
nosy_names = ['terry.reedy', 'ghaering', 'docs@python', 'berker.peksag', 'erlendaasland', 'seeker-Liu']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42624'
versions = ['Python 3.9']
```

</p></details>

**Comment by erlend-aasland** [comment]
The sqlite3 exception docs section has been rewritten in `main` (Python 3.12), so this is fixed in `main`. I decided not to backport the docs update, because there's been a lot of work related to improving the exceptions raised by the sqlite3 extension module, and only parts of that work exists in 3.11, and even less in 3.10.

**Comment by erlend-aasland** [comment]
We _could_ backport gh-27645 to 3.11, and possibly also 3.10, but it will be hairy.

**Comment by erlend-aasland** [comment]
I backported gh-27645 to 3.11 and 3.10:

- #93836
- #93838

I consider this issue resolved. If there are further inconsistencies, please open a new issue.
