### ISSUE TITLE
urllib.request.getproxies() misparses Windows registry proxy settings

### ISSUE THREAD

**Issue by c6a16194-fbe2-452d-ab7b-5a02c5e92e91** [python/cpython#86793]
BPO | [42627](https://bugs.python.org/issue42627)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @corona10, @chrisxiao, @NateScarlet, @CrazyBoyFeng, @keuin
PRs | <li>python/cpython#26307</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-12.20:27:52.875>
labels = ['type-bug', '3.9', '3.10', '3.11', 'library', 'OS-windows']
title = 'urllib.request.getproxies() misparses Windows registry proxy settings'
updated_at = <Date 2021-11-20.14:38:47.145>
user = 'https://bugs.python.org/benrg'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-20.14:38:47.145>
actor = 'CrazyBoyFeng'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2020-12-12.20:27:52.875>
creator = 'benrg'
dependencies = []
files = []
hgrepos = []
issue_num = 42627
keywords = ['patch']
message_count = 10.0
messages = ['382921', '387468', '388149', '388152', '393927', '394668', '395276', '401215', '401995', '406658']
nosy_count = 11.0
nosy_names = ['paul.moore', 'tim.golden', 'benrg', 'zach.ware', 'steve.dower', 'corona10', 'chrisxiao', 'kotori', 'NateScarlet', 'CrazyBoyFeng', 'keuin']
pr_nums = ['26307']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42627'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by SekiBetu** [comment]
> I think the PR is basically ready, unfortunately it's stuck behind a CI issue we only just fixed, and needs to merge from main before it'll clear.
> 
> Posting here once CI is green will get attention faster than on GitHub.

any updates?

**Comment by zooba** [comment]
I retriggered the CI to see if it passes now.

**Comment by zooba** [comment]
@TTimo From a quick glance, I think it'll deal with part of the second half of that question. It should be able to pick up manually customised proxies, but I don't think it'll get automatically configured ones. And anything that's bypassing urllib here won't get any benefit, naturally.
