### ISSUE TITLE
os.path.normcase() is inconsistent with Windows file system

### ISSUE THREAD

**Issue by 756faa6e-a0b5-4103-be95-2615957fcc0e** [python/cpython#86824]
BPO | [42658](https://bugs.python.org/issue42658)
--- | :---
Nosy | @pfmoore, @tjguk, @ezio-melotti, @zware, @eryksun, @zooba, @aisk
PRs | <li>python/cpython#32010</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-16.12:44:26.513>
labels = ['type-bug', '3.8', 'OS-windows', '3.10', 'library', 'expert-unicode', '3.9']
title = 'os.path.normcase() is inconsistent with Windows file system'
updated_at = <Date 2022-03-20.15:47:09.896>
user = 'https://bugs.python.org/sogom'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-20.15:47:09.896>
actor = 'asaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Unicode', 'Windows']
creation = <Date 2020-12-16.12:44:26.513>
creator = 'sogom'
dependencies = []
files = []
hgrepos = []
issue_num = 42658
keywords = ['patch']
message_count = 2.0
messages = ['383163', '384012']
nosy_count = 8.0
nosy_names = ['paul.moore', 'tim.golden', 'ezio.melotti', 'zach.ware', 'eryksun', 'steve.dower', 'asaka', 'sogom']
pr_nums = ['32010']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42658'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by zooba** [comment]
Fix is committed for 3.12, but needs some help backporting. I can't get to it today, so if anyone wants to do it, go ahead. I'll try and get to it later this week.

**Comment by zooba** [comment]
I started backporting to 3.11, but the memory leak is back in the `test_embed` tests. I don't see where it could be, and it doesn't occur in 3.12, so we need to fix it before backporting.

**Comment by aisk** [comment]
> I started backporting to 3.11, but the memory leak is back in the `test_embed` tests. I don't see where it could be, and it doesn't occur in 3.12, so we need to fix it before backporting.

The leak is caused by calling `PyUnicode_AsUnicodeAndSize` with empty string. Since `PyUnicode_AsUnicodeAndSize` is removed in 3.12, should we fix it in former versions?

**Comment by zooba** [comment]
Who's calling AsUnicodeAndSize? Is it inside one of the parameter converters? If so, we should definitely fix it in earlier versions.

**Comment by zooba** [comment]
I updated #93591 to use `PyUnicode_AsWideCharString` instead, which avoids the leak. Presumably we're (at least potentially) leaking elsewhere, but it doesn't seem to have come up, so less urgent to track it down. I did look through, and it wasn't anything real obvious.

**Comment by serhiy-storchaka** [comment]
> The leak is caused by calling `PyUnicode_AsUnicodeAndSize` with empty string.

It is very strange. I see nothing suspicious in the code. Does it only leak for empty strings? Functions in the `os` module use this converter to convert path arguments, so it should be easy to reproduce. Also it is used in `winreg.SetValue()` and indirectly in other functions which use "u" or "Z" format units in `PyArg_Parse*()` functions.

**Comment by zooba** [comment]
I didn't see anything suspicious either, so maybe it's just a false positive in the test. Either way, the code is gone and AC just hasn't been updated yet for null-embedded strings, so it doesn't really matter.

**Comment by serhiy-storchaka** [comment]
Closing?
