### ISSUE TITLE
Asyncio loop.create_server doesn't bind to any interface if host is a sequence with just the empty string

### ISSUE THREAD

**Issue by a91f67b1-65f1-452b-975e-bf8c64c6df62** [python/cpython#86961]
BPO | [42795](https://bugs.python.org/issue42795)
--- | :---
Nosy | @asvetlov, @1st1, @plammens

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2020-12-31.11:37:17.059>
labels = ['type-bug', '3.9', 'expert-asyncio']
title = "Asyncio loop.create_server doesn't bind to any interface if host is a sequence with just the empty string"
updated_at = <Date 2020-12-31.11:38:06.637>
user = 'https://github.com/plammens'
```

bugs.python.org fields:
```python
activity = <Date 2020-12-31.11:38:06.637>
actor = 'plammens'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2020-12-31.11:37:17.059>
creator = 'plammens'
dependencies = []
files = []
hgrepos = []
issue_num = 42795
keywords = []
message_count = 1.0
messages = ['384109']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'plammens']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue42795'
versions = ['Python 3.9']
```

</p></details>

**Comment by kumaraditya303** [comment]
> I would have expected a list containing the empty string to also work as expected, i.e. "binding to all hosts in the sequence", so binding to "" and thus to every interface.

Nope, when host is an empty strings it is special cased and it is not done for list since if you are passing a list, you are supposed pass to pass list of strings of ipaddresses. Closing as not a bug and function works as intended,
