### ISSUE TITLE
@overload-ing method of parent class without actual implementation

### ISSUE THREAD

**Issue by 6a170345-91ef-4a81-8a1d-30d8718460eb** [python/cpython#86978]
BPO | [42812](https://bugs.python.org/issue42812)
--- | :---
Nosy | @gvanrossum, @uriyyo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-03.05:51:32.158>
labels = ['type-feature', '3.10']
title = '@overload-ing method of parent class without actual implementation'
updated_at = <Date 2021-01-12.00:32:35.122>
user = 'https://bugs.python.org/chaim422'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-12.00:32:35.122>
actor = 'gvanrossum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-01-03.05:51:32.158>
creator = 'chaim422'
dependencies = []
files = []
hgrepos = []
issue_num = 42812
keywords = []
message_count = 12.0
messages = ['384255', '384265', '384283', '384284', '384285', '384286', '384287', '384288', '384289', '384290', '384292', '384871']
nosy_count = 3.0
nosy_names = ['gvanrossum', 'uriyyo', 'chaim422']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42812'
versions = ['Python 3.10']
```

</p></details>

**Comment by AlexWaygood** [comment]
> I hesitate to add anything because you are exposing so much confusion. May I suggest that you ask about this on a user group first before proposing a new feature? One place that makes sense given that this is a type system feature would be this Gitter channel: https://gitter.im/python/typing

I agree with @gvanrossum. I'm closing this issue, as I don't think this issue tracker is an appropriate place for this conversation to be held. Please consider asking your question at https://github.com/python/typing/discussions or on StackOverflow.

Cc. @chaim422
