### ISSUE TITLE
OpenSSL 1.1.1: use SSL_write_ex() and SSL_read_ex()

### ISSUE THREAD

**Issue by tiran** [python/cpython#87020]
BPO | [42854](https://bugs.python.org/issue42854)
--- | :---
Nosy | @tiran, @ethanfurman, @pablogsal, @miss-islington, @FFY00, @geofft
PRs | <li>python/cpython#25468</li><li>python/cpython#27271</li><li>python/cpython#27308</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/tiran'
closed_at = <Date 2021-07-23.15:26:03.224>
created_at = <Date 2021-01-07.08:23:09.806>
labels = ['easy', 'expert-SSL', 'type-feature', '3.10']
title = 'OpenSSL 1.1.1: use SSL_write_ex() and SSL_read_ex()'
updated_at = <Date 2021-07-23.15:26:03.937>
user = 'https://github.com/tiran'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-23.15:26:03.937>
actor = 'pablogsal'
assignee = 'christian.heimes'
closed = True
closed_date = <Date 2021-07-23.15:26:03.224>
closer = 'pablogsal'
components = ['SSL']
creation = <Date 2021-01-07.08:23:09.806>
creator = 'christian.heimes'
dependencies = []
files = []
hgrepos = []
issue_num = 42854
keywords = ['patch', 'easy (C)']
message_count = 13.0
messages = ['384567', '384568', '391295', '391358', '391363', '391422', '391521', '397822', '397832', '397833', '397906', '398063', '398068']
nosy_count = 6.0
nosy_names = ['christian.heimes', 'ethan.furman', 'pablogsal', 'miss-islington', 'FFY00', 'geofft']
pr_nums = ['25468', '27271', '27308']
priority = 'high'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42854'
versions = ['Python 3.10']
```

</p></details>

### Linked PRs
* gh-95593
* gh-95594

**Comment by erlend-aasland** [comment]
Two reverts were opened after this issue was resolved:

- #95593
- #95594

I could not find any discussion regarding these reverts, so it is not immediately obvious if they are still needed. @pablogsal, your review was requested for both of these reverts; do you remember the discussion?

**Comment by pablogsal** [comment]
> I could not find any discussion regarding these reverts, so it is not immediately obvious if they are still needed. @pablogsal, your review was requested for both of these reverts; do you remember the discussion?

I remember my commit but unfortunately I don't remember the discussion for the reverts :(

**Comment by erlend-aasland** [comment]
Well, given that the reverts were not applied for 1,5 years, perhaps we could close those PRs. It would seem to me that there would exist an issue for this if these were release blockers or if they represented critical bugs.

**Comment by erlend-aasland** [comment]
I closed the revert PRs. We can open them later if needed.
