### ISSUE TITLE
Solaris 11.4 crle output not handled correctly

### ISSUE THREAD

**Issue by b3ea820a-d1fd-44cf-aaa4-0a9f1b88814a** [python/cpython#87062]
BPO | [42896](https://bugs.python.org/issue42896)
--- | :---
Nosy | @dmurphy18
PRs | <li>python/cpython#24226</li>
Files | <li>[solaris11_crle.patch](https://bugs.python.org/file49735/solaris11_crle.patch "Uploaded as text/plain at 2021-01-11.18:55:17 by @dmurphy18"): patch file to be applied to Lib/ctypes/util.py</li><li>[py387_ctypes_util.patch](https://bugs.python.org/file49780/py387_ctypes_util.patch "Uploaded as text/plain at 2021-01-30.16:50:47 by hergen"): patch for ctypes util.py</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-11.18:55:17.642>
labels = ['ctypes', '3.8']
title = 'Solaris 11.4 crle output not handled correctly'
updated_at = <Date 2021-01-30.16:50:47.619>
user = 'https://github.com/dmurphy18'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-30.16:50:47.619>
actor = 'hergen'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2021-01-11.18:55:17.642>
creator = 'dmurphy18'
dependencies = []
files = ['49735', '49780']
hgrepos = []
issue_num = 42896
keywords = ['patch']
message_count = 4.0
messages = ['384856', '384857', '385981', '385989']
nosy_count = 2.0
nosy_names = ['dmurphy18', 'hergen']
pr_nums = ['24226']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42896'
versions = ['Python 3.8']
```

</p></details>

**Comment by encukou** [comment]
cc @jcea
Is this still an issue? Does the proposed patch fix it?

For the test, perhaps we need a hard error -- not a skip -- in `test_load_version` for platforms that are known to have libc & libm.

**Comment by encukou** [comment]
Closing as the OS is unsupported.
Like other similar issues, this will continue to be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or bring support back.
