### ISSUE TITLE
Split compiler into code-gen, optimizer and assembler.

### ISSUE THREAD

**Issue by markshannon** [python/cpython#87092]
BPO | [42926](https://bugs.python.org/issue42926)
--- | :---
Nosy | @gvanrossum, @markshannon, @corona10, @brandtbucher, @iritkatriel 

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-13.15:03:23.987>
labels = []
title = 'Split compiler into code-gen, optimizer and assembler.'
updated_at = <Date 2022-02-03.22:11:26.525>
user = 'https://github.com/markshannon'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-03.22:11:26.525>
actor = 'iritkatriel'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-01-13.15:03:23.987>
creator = 'Mark.Shannon'
dependencies = []
files = []
hgrepos = []
issue_num = 42926
keywords = ['patch']
message_count = 2.0
messages = ['385033', '385043']
nosy_count = 5.0
nosy_names = ['gvanrossum', 'Mark.Shannon', 'corona10', 'brandtbucher', 'iritkatriel']
pr_nums = ['31116']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42926'
versions = []
```

</p></details>

* PR: gh-98913

* PR: gh-98914

* PR: gh-99111

* PR: gh-99869

* PR: gh-102093

* PR: gh-102320

* PR: gh-102562

* PR: gh-102926

* PR: gh-103021

* PR: gh-103277

* PR: gh-103448

* PR: gh-103456

* PR: gh-103933

* PR: gh-103941

* PR: gh-103988

* PR: gh-104460

* PR: gh-105243

* PR: gh-105247

**Comment by iritkatriel** [comment]
I've been struggling to determine where to draw the line between the optimization stage and the assembly stage.

I think the solution is to add a fourth stage, between optimization and assembly, which prepares the CFG for assembly. It does all the normalisation of pseudo-stuff (instructions, targets, etc) into actual stuff (real opcodes, offsets, etc).

I don't know if there is a name for this stage in compilers parlance. We could call it "resolve instructions" or something like that.  

It will include everything to do with: 

(1) calculating stackdepth and except targets, replacing exception related opcodes by NOP
(2) moving cold blocks to end of block-list
(3) everything related to making sure line numbers are correct
(4) replacing pseudo-op jumps by actual jumps, including figuring out the direction and translating conditional backwards jumps into real jumps
(5) Finally, calculating the jump offsets

**Comment by gvanrossum** [comment]
I don't know what that should be called either, but after this is done, are EXTENDED_ARG prefixes for jumps all set? I'm guessing, maybe make a similar list of responsibilities for the assembler? Because I'm not sure what those are.

**Comment by iritkatriel** [comment]
The responsibility of the assembler is to turn a list of instructions to a code object:

(1) write the bytecode for the instructions
(2) create the lineno table
(3) create the exception table
(4) create a code object from those + metadata about the compilation unit.

Bytecode generation in stage (1) adds EXTENDED_ARG bytecodes when an instruction has a large oparg that requires it. The part that calculates jump offsets ((5) in the "resolve" list) takes into account the EXTENDED_ARGs when calculating block sizes. 

The idea is that all the complex calculations would be in the new stage, and we can write tests for them. Then the assembler's job is to transform the instructions representation to what we need in the code object (but all the exception/jump targets, lineno, block order etc is already resolved before).  Then we can write tests just for this translation stage.

**Comment by gvanrossum** [comment]
SG. May the name can be inspired by “settle” or “tidy” or “clean”? Or maybe “resolve” is fine.

**Comment by markshannon** [comment]
From the list above:
(1) calculating stackdepth and except targets, replacing exception related opcodes by NOP
(2) moving cold blocks to end of block-list
(3) everything related to making sure line numbers are correct
(4) replacing pseudo-op jumps by actual jumps, including figuring out the direction and translating conditional backwards jumps into real jumps
(5) Finally, calculating the jump offsets

And splitting (1) into 1x (exception targets) and 1s (stack depth calculation) and adding `O` (other cfg optimizations)


In a normal compiler, there are de-sugaring and semantic analysis passes after parsing, but before optimization.
(3) and (1x) belongs in there, as does computing except targets.

(2) belongs in the optimizer

(1s), (4) and (5) belong in the assembler.

Is this a good order of passes? `3, 1x, 2, O, 4, 5, 1s`

**Comment by iritkatriel** [comment]
I like the idea or moving some of the resolution to before optimisations. I think the order you suggest is fine, by and large. I’ll need to check whether all the line number business is safe to move up front. Some of it involves duplicating blocks,etc.

**Comment by iritkatriel** [comment]
The lineno calculation needs to duplicate blocks that have no lineno but more than one predecessors. So it needs to come after mark_reachable, which is currently somewhere in the middle of the optimization stage. So that part of Mark's suggested reordering might be a problem. At least it needs to be done carefully.
