### ISSUE TITLE
Easy conversion between range and slice

### ISSUE THREAD

**Issue by e7156765-cbc4-40de-a178-4c6a47cd8ca6** [python/cpython#87122]
BPO | [42956](https://bugs.python.org/issue42956)
--- | :---
Nosy | @rhettinger, @stevendaprano, @serhiy-storchaka

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-18.10:31:17.887>
labels = ['type-feature', '3.10']
title = 'Easy conversion between range and slice'
updated_at = <Date 2021-01-18.19:21:18.745>
user = 'https://bugs.python.org/nemeskeyd'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-18.19:21:18.745>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-01-18.10:31:17.887>
creator = 'nemeskeyd'
dependencies = []
files = []
hgrepos = []
issue_num = 42956
keywords = []
message_count = 5.0
messages = ['385184', '385185', '385188', '385189', '385220']
nosy_count = 4.0
nosy_names = ['rhettinger', 'steven.daprano', 'serhiy.storchaka', 'nemeskeyd']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue42956'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
> It would be nice if there was an easy way to convert a range to a slice and vice versa. At least superficially the two are almost the same(*), yet if one wants to convert a slice to a range, he has to go through hoops to avoid potential errors, ending up with code such as:
> 
> ```python
> s = slice(1, 10, 2)
> r = range(s.start or 0, s.stop, s.step or 1)
> ```

You could do:

```
>>> r = range(s.stop)[s]
>>> r
range(1, 10, 2)
```
