### ISSUE TITLE
Add PurePath.with_suffix_appended()

### ISSUE THREAD

**Issue by 35b9d6ea-b622-45fe-841c-f827870efecc** [python/cpython#87161]
BPO | [42995](https://bugs.python.org/issue42995)
--- | :---
Nosy | @bgerrity
PRs | <li>python/cpython#24288</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-21.22:04:11.140>
labels = ['library', '3.10']
title = 'Add PurePath.with_suffix_appended()'
updated_at = <Date 2021-01-21.22:52:04.404>
user = 'https://github.com/bgerrity'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-21.22:52:04.404>
actor = 'bgerrity'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-01-21.22:04:11.140>
creator = 'bgerrity'
dependencies = []
files = []
hgrepos = []
issue_num = 42995
keywords = ['patch']
message_count = 2.0
messages = ['385451', '385452']
nosy_count = 1.0
nosy_names = ['bgerrity']
pr_nums = ['24288']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue42995'
versions = ['Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
> The operations don't come across as elegant:
> 
> e.g. `foo_path.with_suffix(foo_path.suffix + ".old")`

This comes across fine to me. Another option:

```
foo_path.with_name(foo_path.name + ".old")
```

I'm -1 on adding a `with_suffix_appended()` method or a new *append* argument to `with_suffix()`. The existing solution is readable and easy to discover.

**Comment by CAM-Gerlach** [comment]
IMO it can get a little verbose and tedious repeating `foo_path` twice if it has a longer variable name or is nested inside something else, but adding dedicated `with_suffix_*` sub-methods for common operations seems equally if not more of a kludge and clunky to use. And, the same logic would extend to `with_name` as well. 

So, yeah, I really don't see an obvious cleaner than the present `foo_path.with_suffix(foo_path.suffix + ".old")` given `pathlib.Path` is immutable.

**Comment by AlexWaygood** [comment]
I agree with @barneygale and @CAM-Gerlach -- I don't think a particularly compelling use case has been presented here, really. The issue has been open for two years now without significant activity, and the associated PR has been abandoned by the OP. Closing.
