### ISSUE TITLE
IDLE:  update code, mostly by cleanups of 2.x or 2to3 artifacts

### ISSUE THREAD

**Issue by terryjreedy** [python/cpython#87179]
BPO | [43013](https://bugs.python.org/issue43013)
--- | :---
Nosy | @terryjreedy, @taleinat, @asottile, @miss-islington
PRs | <li>python/cpython#24315</li><li>python/cpython#24316</li><li>python/cpython#24317</li><li>python/cpython#24319</li><li>python/cpython#24326</li><li>python/cpython#24327</li><li>python/cpython#24328</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/terryjreedy'
closed_at = None
created_at = <Date 2021-01-23.21:20:31.167>
labels = ['expert-IDLE', 'type-feature', '3.8', '3.9', '3.10']
title = 'IDLE:  update code, mostly by cleanups of 2.x or 2to3 artifacts'
updated_at = <Date 2021-01-25.16:29:29.864>
user = 'https://github.com/terryjreedy'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-25.16:29:29.864>
actor = 'Anthony Sottile'
assignee = 'terry.reedy'
closed = False
closed_date = None
closer = None
components = ['IDLE']
creation = <Date 2021-01-23.21:20:31.167>
creator = 'terry.reedy'
dependencies = []
files = []
hgrepos = []
issue_num = 43013
keywords = ['patch']
message_count = 14.0
messages = ['385564', '385570', '385587', '385588', '385593', '385595', '385601', '385604', '385618', '385619', '385620', '385627', '385629', '385639']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'taleinat', 'Anthony Sottile', 'miss-islington']
pr_nums = ['24315', '24316', '24317', '24319', '24326', '24327', '24328']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43013'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
(I took the liberty to collapse Anthony's multi-screenful diff with a `<details>` tag, for improved readability on this issue.)

**Comment by erlend-aasland** [comment]
ISTM that most cleanups mentioned in the OP have been done (2to3 modernisation, tkinter modernisation). Suggesting to close this and open targeted, narrow issues for each further refactor/modernisation.

**Comment by terryjreedy** [comment]
@erlend-aasland Thank you for the example of a collapsed section.  This was new to me, and I expect to use it.  I found the page for it.  Is this standard html?

I will open separate issues for further changes but made this a task issue to keep track of them.

**Comment by erlend-aasland** [comment]
> Is this standard html?

Yes, so it seems: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details

It is a very convenient HTML feature.

**Comment by arhadthedev** [comment]
@terryjreedy Could you address the remaining three TODO items so we can close this issue for good?

**Comment by terryjreedy** [comment]
I open 3 issues for the 3 items, did one, and am working on the other two.

**Comment by terryjreedy** [comment]
I did 2/3rds of item 4, replacing redefinitions of 'dict' and 'object' and deferred the same for 'type'.  Hence closing this.
