### ISSUE TITLE
_dyld_shared_cache_contains_path needs SYSTEM_VERSION_COMPAT=0

### ISSUE THREAD

**Issue by 1b7e0465-9f2c-4663-8ddc-8b935379ec44** [python/cpython#87218]
BPO | [43052](https://bugs.python.org/issue43052)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @isuruf
PRs | <li>python/cpython#24324</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-28.06:39:56.837>
labels = []
title = '_dyld_shared_cache_contains_path needs SYSTEM_VERSION_COMPAT=0'
updated_at = <Date 2021-02-01.06:09:56.349>
user = 'https://github.com/isuruf'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-01.06:09:56.349>
actor = 'isuruf'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-01-28.06:39:56.837>
creator = 'isuruf'
dependencies = []
files = []
hgrepos = []
issue_num = 43052
keywords = []
message_count = 3.0
messages = ['385845', '386055', '386057']
nosy_count = 3.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'isuruf']
pr_nums = ['24324']
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43052'
versions = []
```

</p></details>

**Comment by ronaldoussoren** [comment]
> You are right. I think I may have accidentally used the wrong SDK. Explictly setting `SYSTEM_VERSION_COMPAT=1` is unsupported then?

Yes.  The support matrix is large enough as it is.  SYSTEM_VERSION_COMPAT also doesn't us to differentiate macOS versions beyond 11.0 from each other, although that isn't a problem in practice at this point in time.
