### ISSUE TITLE
setting a logging Handler name

### ISSUE THREAD

**Issue by 0e9de2e1-bd73-4136-bf78-ad0d472879c8** [python/cpython#87224]
BPO | [43058](https://bugs.python.org/issue43058)
--- | :---
Nosy | @vsajip

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-28.20:17:02.239>
labels = ['3.8', 'type-feature', 'library', 'docs']
title = 'setting a logging Handler name'
updated_at = <Date 2021-01-28.20:17:02.239>
user = 'https://bugs.python.org/bcohen'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-28.20:17:02.239>
actor = 'bcohen'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-01-28.20:17:02.239>
creator = 'bcohen'
dependencies = []
files = []
hgrepos = []
issue_num = 43058
keywords = []
message_count = 1.0
messages = ['385880']
nosy_count = 3.0
nosy_names = ['vinay.sajip', 'docs@python', 'bcohen']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43058'
versions = ['Python 3.8']
```

</p></details>

**Comment by vsajip** [comment]
There is no need to expose `set_name` as there is an exposed property `name` already, which can be used.

**Comment by RafaelWO** [comment]
I also just stumbled across this and could not find information in the docs about how to set the `name` of a logging `Handler`.

> There is no need to expose `set_name` as there is an exposed property `name` already, which can be used.

Can you point me to where the property `name` is mentioned, @vsajip?

In my opinion, it would be helpful to have an example for that. Maybe in conjunction with `logging.getHandlerByName()` 🤔 
Happy to open a PR for that 🙂
