### ISSUE TITLE
Cannot clear signal handler set with loop.add_signal_handler in forked process with signal.signal

### ISSUE THREAD

**Issue by 4ddad88b-853c-489f-9e5c-c5d8b5d65bf9** [python/cpython#87230]
BPO | [43064](https://bugs.python.org/issue43064)
--- | :---
Nosy | @asvetlov, @1st1, @selimb
Files | <li>[python-async-signal-bug.zip](https://bugs.python.org/file49774/python-async-signal-bug.zip "Uploaded as application/x-zip-compressed at 2021-01-29.19:51:37 by @selimb"): Experiments</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-29.19:51:37.656>
labels = ['type-bug', '3.8', '3.9', '3.10', '3.7', 'expert-asyncio']
title = 'Cannot clear signal handler set with loop.add_signal_handler in forked process with signal.signal'
updated_at = <Date 2021-02-01.20:57:38.311>
user = 'https://github.com/selimb'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-01.20:57:38.311>
actor = 'selimb'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-01-29.19:51:37.656>
creator = 'selimb'
dependencies = []
files = ['49774']
hgrepos = []
issue_num = 43064
keywords = []
message_count = 2.0
messages = ['385928', '386112']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'selimb']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43064'
versions = ['Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by Mixser** [comment]
Hi, 

asyncio setups signal handler in a specific way -- it calls signal.set_wakeup_fd and passes an fd of the opened socket. After it, if any signals are sent to the process, they will be written to this socket/fd.

Any child process will inherit not only signal handlers' behavior but an opened socket. And as a result, when we are sending a signal to the child process, it will be written to the socket and the parent process will receive it too, even though this signal was sent not to him; Or if you will send it to the parent process, the child process will receive this signal too;

How you can avoid this behavior -- at the very beginning of the child process you can execute the following code

```
signal.set_wakeup_fd(-1) # don't send the signal into shared socket
```

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/94454
