### ISSUE TITLE
Memory Leak when using Thread

### ISSUE THREAD

**Issue by ea420b2e-5392-451c-97b3-07b294b6299a** [python/cpython#87238]
BPO | [43072](https://bugs.python.org/issue43072)
--- | :---
Files | <li>[simple.py](https://bugs.python.org/file49777/simple.py "Uploaded as text/plain at 2021-01-30.04:03:55 by goyalakshat14")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-01-30.04:03:55.673>
labels = ['3.8', 'library', 'performance']
title = 'Memory Leak when using Thread'
updated_at = <Date 2021-01-30.04:03:55.673>
user = 'https://bugs.python.org/goyalakshat14'
```

bugs.python.org fields:
```python
activity = <Date 2021-01-30.04:03:55.673>
actor = 'goyalakshat14'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-01-30.04:03:55.673>
creator = 'goyalakshat14'
dependencies = []
files = ['49777']
hgrepos = []
issue_num = 43072
keywords = []
message_count = 1.0
messages = ['385969']
nosy_count = 1.0
nosy_names = ['goyalakshat14']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue43072'
versions = ['Python 3.6', 'Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
@goyalakshat14 How are you measuring memory usage?

**Comment by AlexSoft73** [comment]
Hi,

I've been discussing this subject with CPython "**CORE**" developers, unfortunately they do not seem interested in fixing the memory leaks.
