### ISSUE TITLE
sqlite3 signature discrepancies between documentation and implementation

### ISSUE THREAD

**Issue by c07b3e20-0507-4d47-a83b-4eaa5733cc1f** [python/cpython#87260]
BPO | [43094](https://bugs.python.org/issue43094)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @nchammas, @erlend-aasland
PRs | <li>python/cpython#24489</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-01.20:10:10.173>
labels = ['3.9', '3.10', 'docs']
title = 'sqlite3 signature discrepancies between documentation and implementation'
updated_at = <Date 2021-03-28.21:07:22.364>
user = 'https://github.com/nchammas'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-28.21:07:22.364>
actor = 'erlendaasland'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-02-01.20:10:10.173>
creator = 'nchammas'
dependencies = []
files = []
hgrepos = []
issue_num = 43094
keywords = ['patch']
message_count = 10.0
messages = ['386100', '386120', '386708', '386741', '386806', '386813', '386826', '389544', '389552', '389651']
nosy_count = 5.0
nosy_names = ['docs@python', 'berker.peksag', 'serhiy.storchaka', 'nchammas', 'erlendaasland']
pr_nums = ['24489']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43094'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
> The problem is that sqlite3 isn't the only module where there are discrepancies between documentation and implementation. 

This does not stand in the way of fixing the docs right away.

> If we are going to change public sqlite3 APIs in to be positional-only, I'd prefer writing a PEP and fix all modules once and for all.

I think that is too large for a PEP. We could create an issue for making _some_ sqlite3 methods positional only. See also gh-93057.

**Comment by erlend-aasland** [comment]
Thanks for the report. If there are further discrepancies, please open a new issue.

For making sqlite3 methods positional only, please open a new issue.

**Comment by erlend-aasland** [comment]
FTR, I _did_ start drafting a PEP back in 2021, but I abandoned the project as I found it to be too vague for a PEP, in my opinion.
