### ISSUE TITLE
webbrowser.py triggers unwanted XQuartz startup

### ISSUE THREAD

**Issue by 546053fe-82ae-466d-805e-6e7d5257e6af** [python/cpython#87277]
BPO | [43111](https://bugs.python.org/issue43111)
--- | :---
Nosy | @terryjreedy, @ronaldoussoren, @ned-deily
PRs | <li>python/cpython#24480</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-03.09:21:34.337>
labels = ['OS-mac', '3.8', '3.9', '3.10', 'performance', 'library']
title = 'webbrowser.py triggers unwanted XQuartz startup'
updated_at = <Date 2021-02-08.09:04:26.632>
user = 'https://bugs.python.org/hans-meine'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-08.09:04:26.632>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'macOS']
creation = <Date 2021-02-03.09:21:34.337>
creator = 'hans-meine'
dependencies = []
files = []
hgrepos = []
issue_num = 43111
keywords = ['patch']
message_count = 6.0
messages = ['386182', '386553', '386555', '386557', '386623', '386625']
nosy_count = 4.0
nosy_names = ['terry.reedy', 'ronaldoussoren', 'ned.deily', 'hans-meine']
pr_nums = ['24480']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue43111'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
I've updated the version labels. The code change has not been applied to main yet (but I don't know whether it is still needed).

**Comment by ronaldoussoren** [comment]
I'm reviving the PR and will treat this as a new feature, that is I won't perform a back port of the PR. Primary reason for that is that using XQuartz in first place is a niche use case.

**Comment by ronaldoussoren** [comment]
I've merged a fix for this in the main branch.

I'm not backporting this because X11 usage on macOS should be extremely niche these days, but am willing to reconsider.
