### ISSUE TITLE
asyncio.Queue.put never yields if the queue is unbounded

### ISSUE THREAD

**Issue by 5e0c2765-278a-4b57-a542-1cc085878372** [python/cpython#87285]
BPO | [43119](https://bugs.python.org/issue43119)
--- | :---
Nosy | @asvetlov, @1st1, @MojoVampire, @Fidget-Spinner, @spenczar
PRs | <li>python/cpython#24433</li>
Files | <li>[never_yields.py](https://bugs.python.org/file49789/never_yields.py "Uploaded as text/plain at 2021-02-03.19:41:21 by @spenczar"): minimal executable reproducer of unyielding behavior</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-22.23:07:28.159>
created_at = <Date 2021-02-03.19:41:22.473>
labels = ['type-bug', '3.8', '3.9', '3.10', 'expert-asyncio']
title = 'asyncio.Queue.put never yields if the queue is unbounded'
updated_at = <Date 2022-02-22.23:07:28.159>
user = 'https://github.com/spenczar'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-22.23:07:28.159>
actor = 'asvetlov'
assignee = 'none'
closed = True
closed_date = <Date 2022-02-22.23:07:28.159>
closer = 'asvetlov'
components = ['asyncio']
creation = <Date 2021-02-03.19:41:22.473>
creator = 'spenczar'
dependencies = []
files = ['49789']
hgrepos = []
issue_num = 43119
keywords = ['patch']
message_count = 6.0
messages = ['386454', '386477', '386488', '386512', '386539', '413756']
nosy_count = 5.0
nosy_names = ['asvetlov', 'yselivanov', 'josh.r', 'kj', 'spenczar']
pr_nums = ['24433']
priority = 'normal'
resolution = 'wont fix'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43119'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by BrendanSimon** [comment]
Your put loop could be written within an `asyncio.wait_for()` statement, so that it would periodically yield with `asyncio.sleep(0)`, to reduce the performance impact.  Similarly a loop in chunks based on count or size?
