### ISSUE TITLE
uuid won't build when libuuid is installed in a non-standard place

### ISSUE THREAD

**Issue by larryhastings** [python/cpython#87324]
BPO | [43158](https://bugs.python.org/issue43158)
--- | :---
Nosy | @larryhastings, @tiran, @commodo, @miss-islington
PRs | <li>python/cpython#29353</li><li>python/cpython#29362</li><li>python/cpython#29363</li><li>python/cpython#29433</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-07.20:44:19.872>
labels = ['build', '3.9', '3.10', '3.11']
title = "uuid won't build when libuuid is installed in a non-standard place"
updated_at = <Date 2021-11-05.20:51:34.333>
user = 'https://github.com/larryhastings'
```

bugs.python.org fields:
```python
activity = <Date 2021-11-05.20:51:34.333>
actor = 'christian.heimes'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-02-07.20:44:19.872>
creator = 'larry'
dependencies = []
files = []
hgrepos = []
issue_num = 43158
keywords = ['patch']
message_count = 9.0
messages = ['386607', '405424', '405433', '405435', '405503', '405505', '405506', '405507', '405829']
nosy_count = 4.0
nosy_names = ['larry', 'christian.heimes', 'Alexandru Ardelean', 'miss-islington']
pr_nums = ['29353', '29362', '29363', '29433']
priority = 'low'
resolution = None
stage = 'commit review'
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue43158'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by mathstuf** [comment]
I'm seeing this issue again with Python 3.12. I have `util-linux` installed and can see the header, but its include directory is not added for `<uuid.h>` to work. Did this get reverted/removed in some way since the fix? (I've not tested 3.11, but 3.10 worked.)

**Comment by mathstuf** [comment]
Looking at the command line, it doesn't even try to add the include directory for `<uuid/uuid.h>` to work. I feel like something got dropped somewhere…

**Comment by mathstuf** [comment]
It looks like the configure logic is wrong in that `uuid.pc` makes `<uuid/uuid.h>` to work but Python's configure seems to think that finding the package lets it do `<uuid.h>`.

**Comment by mathstuf** [comment]
Bah…there's a patch we apply to make `fontconfig` happy that breaks Python. I'll go remove that patch and fix `fontconfig` instead…
