### ISSUE TITLE
argparse: add extend_const action

### ISSUE THREAD

**Issue by 52fcf438-5535-4986-8b54-d571dc818751** [python/cpython#87326]
BPO | [43160](https://bugs.python.org/issue43160)
--- | :---
Nosy | @rhettinger, @roganartu
PRs | <li>python/cpython#24478</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-08.04:12:31.886>
labels = ['type-feature', 'library', '3.10']
title = 'argparse: add extend_const action'
updated_at = <Date 2021-02-09.07:54:04.617>
user = 'https://github.com/roganartu'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-09.07:54:04.617>
actor = 'roganartu'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-02-08.04:12:31.886>
creator = 'roganartu'
dependencies = []
files = []
hgrepos = []
issue_num = 43160
keywords = ['patch']
message_count = 4.0
messages = ['386614', '386690', '386696', '386697']
nosy_count = 3.0
nosy_names = ['rhettinger', 'paul.j3', 'roganartu']
pr_nums = ['24478']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43160'
versions = ['Python 3.10']
```

</p></details>

**Comment by serhiy-storchaka** [comment]
This looks like a too niche feature.

You can create a custom Action. If do not make it general, it can be simpler.

You can use `append_const` with a special value, and then, after parsing arguments, replace this value with the required sequence.
