### ISSUE TITLE
macOS python install shares /usr/local with homebrew and can conflict

### ISSUE THREAD

**Issue by 0b025fe8-e4e1-4720-ae59-150cc0054cc7** [python/cpython#87334]
BPO | [43168](https://bugs.python.org/issue43168)
--- | :---
Nosy | @barry-scott, @ronaldoussoren, @ned-deily

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-08.19:57:04.928>
labels = ['OS-mac', 'expert-installation', '3.9', '3.10']
title = 'macOS python install shares /usr/local with homebrew and can conflict'
updated_at = <Date 2021-02-08.20:42:33.325>
user = 'https://github.com/barry-scott'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-08.20:42:33.325>
actor = 'ned.deily'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'macOS']
creation = <Date 2021-02-08.19:57:04.928>
creator = 'barry-scott'
dependencies = []
files = []
hgrepos = []
issue_num = 43168
keywords = []
message_count = 6.0
messages = ['386649', '386652', '386655', '386657', '386661', '386663']
nosy_count = 3.0
nosy_names = ['barry-scott', 'ronaldoussoren', 'ned.deily']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43168'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
Is there anything to do for this issue? 

BTW. Given that, as the installer mentions, installing links in /usr/local/bin is not necessary we could deselect installation of the unix tools sub package by default.

**Comment by zitterbewegung** [comment]
@ned-deily I believe this should be closed as a duplicate in light of [bpo-43167](https://bugs.python.org/issue?@action=redirect&bpo=43167) being closed.

**Comment by ned-deily** [comment]
Yeah, I think we could close this now. Possibly in the future, we will provide a somewhat different way of providing links and we can take this up again.
