### ISSUE TITLE
Argparse complains argument required when default is provided

### ISSUE THREAD

**Issue by baa0fc1d-1ea7-4ba4-8d7c-ce23bc3f5a01** [python/cpython#87358]
BPO | [43192](https://bugs.python.org/issue43192)
--- | :---
Nosy | @rhettinger, @ericvsmith

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-10.10:24:37.312>
labels = ['3.8', 'type-bug', 'library']
title = 'Argparse complains argument required when default is provided'
updated_at = <Date 2021-05-04.23:03:59.180>
user = 'https://bugs.python.org/ClintOlsen'
```

bugs.python.org fields:
```python
activity = <Date 2021-05-04.23:03:59.180>
actor = 'rhettinger'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-02-10.10:24:37.312>
creator = 'Clint Olsen'
dependencies = []
files = []
hgrepos = []
issue_num = 43192
keywords = []
message_count = 8.0
messages = ['386770', '386771', '386781', '386799', '386801', '386802', '392957', '392965']
nosy_count = 4.0
nosy_names = ['rhettinger', 'eric.smith', 'paul.j3', 'Clint Olsen']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43192'
versions = ['Python 3.8']
```

</p></details>

### Linked PRs
* gh-124094
* gh-124440
* gh-124441

**Comment by serhiy-storchaka** [comment]
We could simply say that the default value is ignored (or has no effect) for required arguments (with a reference to "required").

On other hand, the documentation for "required" is incomplete. It should explicitly say that the `required=` keyword argument cannot be used with positional arguments, and that positional arguments are treated as optional for nargs equal to '?' or '*'.
