### ISSUE TITLE
Ctypes._FuncPtr.restype doesn't handle NoneType correctly

### ISSUE THREAD

**Issue by 287ebcc3-aa6d-4338-aea4-d53d5fb7f2c3** [python/cpython#87374]
BPO | [43208](https://bugs.python.org/issue43208)
--- | :---
Nosy | @eryksun
Files | <li>[minimal_example_ctypes_nonetype_behaviour.py](https://bugs.python.org/file49803/minimal_example_ctypes_nonetype_behaviour.py "Uploaded as text/plain at 2021-02-12.14:44:57 by thijsmiedema94"): ctypes _FuncPtr.restype behaviour for None/NoneType</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-12.14:44:57.752>
labels = ['ctypes', 'type-bug', '3.10']
title = "Ctypes._FuncPtr.restype doesn't handle NoneType correctly"
updated_at = <Date 2021-02-12.23:03:12.159>
user = 'https://bugs.python.org/thijsmiedema94'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-12.23:03:12.159>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2021-02-12.14:44:57.752>
creator = 'thijsmiedema94'
dependencies = []
files = ['49803']
hgrepos = []
issue_num = 43208
keywords = []
message_count = 2.0
messages = ['386867', '386887']
nosy_count = 2.0
nosy_names = ['eryksun', 'thijsmiedema94']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43208'
versions = ['Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
This was filed during the 3.10 alpha period. The `inspect.signature` behaviour was changed since then; on my 3.10.15 it's back to None:
```py
Python 3.10.15 (main, Sep  9 2024, 00:00:00) [GCC 14.2.1 20240801 (Red Hat 14.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from inspect import signature
>>> def fn() -> None:
...     pass
... 
>>> # prints () -> NoneType starting in python 3.10, () -> None before that
>>> print(signature(fn))
() -> None
```

AFAICS, with `inspect` fixed, there's no reason for `ctypes` to special-case `NoneType`.
