### ISSUE TITLE
Add support for PEP 646

### ISSUE THREAD

**Issue by fd1152b9-82e1-43e9-8503-4a522c774a26** [python/cpython#87390]
BPO | [43224](https://bugs.python.org/issue43224)
--- | :---
Nosy | @gvanrossum, @serhiy-storchaka, @JelleZijlstra, @lysnikolaou, @pablogsal, @Fidget-Spinner, @mrahtz, @mrahtz, @AlexWaygood, @cdce8p
PRs | <li>python/cpython#24527</li><li>python/cpython#30398</li><li>python/cpython#31018</li><li>python/cpython#31019</li><li>python/cpython#31021</li><li>python/cpython#31800</li><li>python/cpython#31804</li><li>python/cpython#31828</li><li>python/cpython#31844</li><li>python/cpython#31845</li><li>python/cpython#31846</li><li>python/cpython#31954</li><li>python/cpython#32030</li><li>python/cpython#32031</li><li>python/cpython#32119</li><li>python/cpython#32159</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-14.17:21:47.204>
labels = ['interpreter-core', 'tests', 'library', '3.11']
title = 'Add support for PEP 646'
updated_at = <Date 2022-04-05.02:52:50.682>
user = 'https://github.com/mrahtz'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-05.02:52:50.682>
actor = 'JelleZijlstra'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Tests', 'Parser']
creation = <Date 2021-02-14.17:21:47.204>
creator = 'mrahtz'
dependencies = []
files = []
hgrepos = []
issue_num = 43224
keywords = ['patch']
message_count = 9.0
messages = ['414715', '414935', '414991', '415514', '416020', '416022', '416074', '416689', '416727']
nosy_count = 10.0
nosy_names = ['gvanrossum', 'serhiy.storchaka', 'JelleZijlstra', 'lys.nikolaou', 'pablogsal', 'kj', 'matthew.rahtz', 'mrahtz', 'AlexWaygood', 'cdce8p']
pr_nums = ['24527', '30398', '31018', '31019', '31021', '31800', '31804', '31828', '31844', '31845', '31846', '31954', '32030', '32031', '32119', '32159']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43224'
versions = ['Python 3.11']
```

</p></details>

**Comment by gvanrossum** [comment]
@mrahtz @JelleZijlstra @serhiy-storchaka Is it okay if I unsubscribe from these conversations and let you all come up with a compromise? I feel that while we ought to have a policy formulated and mostly implemented by beta 1 (May 6), tweaks of both the policy and the implementation during the beta period until RC 1 (Aug/Sept?) should be allowable.

**Comment by mrahtz** [comment]
@gvanrossum Fine with me. Godspeed with the rest of your work for this release :)

**Comment by mrahtz** [comment]
Keeping track of things yet to do:

- [ ] Decide on/implement type substitution behaviour (https://github.com/python/cpython/issues/91162)
- [ ] Add tests for using `*` with things in `typing.py` (e.g. `*Tuple[int]`) now that the grammar PR has been merged

**Comment by hauntsaninja** [comment]
How much of the checklist above is still relevant?

**Comment by mrahtz** [comment]
Thanks for the reminder! From a quick look, some of the items in the checklist are definitely still relevant. I'll try and find some time for this soon.

**Comment by AlexWaygood** [comment]
> Thanks for the reminder! From a quick look, some of the items in the checklist are definitely still relevant. I'll try and find some time for this soon.

Friendly ping on this -- are the unchecked items on the checklist still to do, or is this issue ~complete now? :)

**Comment by mrahtz** [comment]
Whoops, sorry - we finished https://github.com/python/cpython/pull/98267 last year but I completely forgot to update the checklist. I believe we can go ahead and close this now :)

**Comment by AlexWaygood** [comment]
> Whoops, sorry - we finished #98267 last year but I completely forgot to update the checklist. I believe we can go ahead and close this now :)

No worries -- great to hear!

> Can you do it on your end?)

I sure can. Thanks for all the work you put into this, it was a marathon!
