### ISSUE TITLE
Add Void type to typing library

### ISSUE THREAD

**Issue by 62284b30-4f9a-4516-a58d-9e106984def3** [python/cpython#87408]
BPO | [43242](https://bugs.python.org/issue43242)
--- | :---
Nosy | @ocket8888
PRs | <li>python/cpython#24557</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-17.17:14:52.078>
labels = ['type-feature', 'library', '3.10']
title = 'Add Void type to typing library'
updated_at = <Date 2021-02-17.17:16:53.722>
user = 'https://github.com/ocket8888'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-17.17:16:53.722>
actor = 'ocket8888'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-02-17.17:14:52.078>
creator = 'ocket8888'
dependencies = []
files = []
hgrepos = []
issue_num = 43242
keywords = ['patch']
message_count = 1.0
messages = ['387166']
nosy_count = 1.0
nosy_names = ['ocket8888']
pr_nums = ['24557']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43242'
versions = ['Python 3.10']
```

</p></details>

**Comment by AlexWaygood** [comment]
[As @gvanrossum stated](https://github.com/python/cpython/pull/24557#issuecomment-780728951) in the linked PR, proposals like this need substantial discussion, either on [the typing-sig mailing list](https://mail.python.org/archives/list/typing-sig@python.org/) or at https://github.com/python/typing/issues, before a CPython issue can be created. If you're able to find substantial support for your proposal in one of those forums, please feel free to open a new CPython issue and/or PR for this feature proposal.
