### ISSUE TITLE
[C API] Deprecate or remove PyFPE_START_PROTECT() and PyFPE_END_PROTECT()

### ISSUE THREAD

**Issue by vstinner** [python/cpython#87416]
BPO | [43250](https://bugs.python.org/issue43250)
--- | :---
Nosy | @vstinner, @njsmith, @corona10, @shihai1991

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-18.11:21:34.559>
labels = ['expert-C-API', '3.10']
title = '[C API] Deprecate or remove PyFPE_START_PROTECT() and PyFPE_END_PROTECT()'
updated_at = <Date 2021-02-22.12:20:04.947>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-22.12:20:04.947>
actor = 'corona10'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-02-18.11:21:34.559>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 43250
keywords = []
message_count = 8.0
messages = ['387213', '387215', '387218', '387219', '387220', '387225', '387461', '387467']
nosy_count = 4.0
nosy_names = ['vstinner', 'njs', 'corona10', 'shihai1991']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = None
url = 'https://bugs.python.org/issue43250'
versions = ['Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
I don't have the bandwidth to update Cython and mark the macro as deprecated. So I just close the issue.

**Comment by da-woods** [comment]
> I don't have the bandwidth to update Cython and mark the macro as deprecated. So I just close the issue.

I'm about to kill them off in Cython - https://github.com/cython/cython/pull/5841.
