### ISSUE TITLE
argparse: allow add_mutually_exclusive_group on add_argument_group

### ISSUE THREAD

**Issue by 811ace97-a738-4117-bd90-4469a41b9e37** [python/cpython#87425]
BPO | [43259](https://bugs.python.org/issue43259)
--- | :---
Nosy | @rhettinger, @fmigneault
Files | <li>[test.py](https://bugs.python.org/file49821/test.py "Uploaded as text/plain at 2021-02-19.12:53:32 by calestyo")</li><li>[test-no-parent.py](https://bugs.python.org/file49822/test-no-parent.py "Uploaded as text/plain at 2021-02-19.12:53:40 by calestyo")</li><li>[issue43259_utility.py](https://bugs.python.org/file49827/issue43259_utility.py "Uploaded as text/plain at 2021-02-22.05:30:12 by paul.j3")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-19.02:28:41.907>
labels = ['type-feature', 'library']
title = 'argparse: allow add_mutually_exclusive_group on add_argument_group'
updated_at = <Date 2021-06-16.20:49:44.489>
user = 'https://bugs.python.org/calestyo'
```

bugs.python.org fields:
```python
activity = <Date 2021-06-16.20:49:44.489>
actor = 'fmigneault'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-02-19.02:28:41.907>
creator = 'calestyo'
dependencies = []
files = ['49821', '49822', '49827']
hgrepos = []
issue_num = 43259
keywords = []
message_count = 7.0
messages = ['387278', '387283', '387316', '387333', '387481', '387499', '395959']
nosy_count = 4.0
nosy_names = ['rhettinger', 'paul.j3', 'calestyo', 'fmigneault']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43259'
versions = []
```

</p></details>

**Comment by serhiy-storchaka** [comment]
@fmigneault, is it your comment above? Are you interesting in creating a PR? This looks like a neat feature.

**Comment by fmigneault** [comment]
Hi @serhiy-storchaka. Yes that is my comment. I can look into it.

**Comment by serhiy-storchaka** [comment]
There is actually older issue #61011 with an already ready patch. It uses more straightforward approach -- instead of postprocessing mutually exclusive groups, it add new mutually exclusive groups to the right container (the parser or a group) at first place. The result should be more or less the same.

Closing this as a duplicate of #61011.
