### ISSUE TITLE
Sync site.py and sysconfig.py with PyPy

### ISSUE THREAD

**Issue by mattip** [python/cpython#87473]
BPO | [43307](https://bugs.python.org/issue43307)
--- | :---
Nosy | @stefanor, @mattip
PRs | <li>python/cpython#24628</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-23.17:01:37.729>
labels = ['type-feature', 'expert-installation', '3.10']
title = 'Sync site.py and sysconfig.py with PyPy'
updated_at = <Date 2021-04-06.18:33:51.948>
user = 'https://github.com/mattip'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-06.18:33:51.948>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation']
creation = <Date 2021-02-23.17:01:37.729>
creator = 'mattip'
dependencies = []
files = []
hgrepos = []
issue_num = 43307
keywords = ['patch']
message_count = 2.0
messages = ['387583', '387765']
nosy_count = 2.0
nosy_names = ['stefanor', 'mattip']
pr_nums = ['24628']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43307'
versions = ['Python 3.10']
```

</p></details>

**Comment by FFY00** [comment]
@mattip, can I close this, given the outcome of the PR?

I am working on a new sysconfig API (still researching, but you can find a rough initial draft of the proposal [here](https://gist.github.com/FFY00/a77e7235716089bcb31c2a8e54d838ba)), and would love to incorporate the changes and get feedback from PyPy there.

**Comment by FFY00** [comment]
Okay, thanks.

I'll make sure to incorporate that (not hardcoding the implementation name) into the proposal, and will ping you on the issue after I submit it. I am aware of #99560 and planning to incorporate that too :blush:
