### ISSUE TITLE
asyncio: add socket getfqdn and gethostbyaddr functions

### ISSUE THREAD

**Issue by 3bb12e22-ccb0-4663-b6b0-a547053098e8** [python/cpython#87490]
BPO | [43324](https://bugs.python.org/issue43324)
--- | :---
Nosy | @asvetlov, @1st1, @AliyevH
PRs | <li>python/cpython#24651</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-02-25.22:47:07.423>
labels = ['type-feature', '3.10']
title = 'asyncio: add socket getfqdn and gethostbyaddr functions'
updated_at = <Date 2021-02-27.03:53:44.338>
user = 'https://github.com/AliyevH'
```

bugs.python.org fields:
```python
activity = <Date 2021-02-27.03:53:44.338>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-02-25.22:47:07.423>
creator = 'AliyevH'
dependencies = []
files = []
hgrepos = []
issue_num = 43324
keywords = ['patch']
message_count = 1.0
messages = ['387690']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'AliyevH']
pr_nums = ['24651']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43324'
versions = ['Python 3.10']
```

</p></details>

**Comment by JelleZijlstra** [comment]
Can you explain the reasoning for this change? Your PR has no tests to demonstrate what this change is useful for.

**Comment by AliyevH** [comment]
@JelleZijlstra . getfqdn function sends request to dns server and  waits for it to recieve information. and this blocks thread.
i think it could be good to add asynchronous function too, to simplify it.
I can add additional change, if you think this pr will be useful too.

**Comment by AliyevH** [comment]
@kumaraditya303 
https://github.com/python/cpython/blob/main/Lib/asyncio/base_events.py#L867
for functions getnameinfo and getaddrinfo added async wrapper with help run_in_executor.
Because of it i thought it will be useful for getfqdn and gethostbyaddr too.

**Comment by gvanrossum** [comment]
Yeah, I know that we did this for those specific functions (which are called by other parts of asyncio itself), but I don't think we need to replicate the entire socket API here, especially since it's a one-line recipe to do this yourself.
