### ISSUE TITLE
os.get_terminal_size() should use file descriptors in Windows

### ISSUE THREAD

**Issue by eryksun** [python/cpython#87580]
BPO | [43414](https://bugs.python.org/issue43414)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-06.01:58:09.348>
labels = ['easy', 'type-bug', '3.8', '3.9', '3.10', 'extension-modules', 'OS-windows']
title = 'os.get_terminal_size() should use file descriptors in Windows'
updated_at = <Date 2021-03-06.01:58:09.348>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-06.01:58:09.348>
actor = 'eryksun'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Extension Modules', 'Windows']
creation = <Date 2021-03-06.01:58:09.348>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 43414
keywords = ['easy (C)']
message_count = 1.0
messages = ['388187']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'needs patch'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43414'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by zitterbewegung** [comment]
Hi I would like to work on this issue.

**Comment by raghunandanbhat** [comment]
@eryksun, I started working on this. I'm new to this, so I need some help here.

I think the change should be done in [Modules/posixmodule.c](https://github.com/python/cpython/blob/main/Modules/posixmodule.c) and I have made this change.
```
diff --git a/Modules/posixmodule.c b/Modules/posixmodule.c
--- a/Modules/posixmodule.c
+++ b/Modules/posixmodule.c
@@ -13255,7 +13255,7 @@ os_get_terminal_size_impl(PyObject *module, int fd)
         case 2: nhandle = STD_ERROR_HANDLE;
             break;
         default:
-            return PyErr_Format(PyExc_ValueError, "bad file descriptor");
+            nhandle = _get_osfhandle(fd);
         }
         handle = GetStdHandle(nhandle);
         if (handle == NULL)
```

After the change in `posixmodule.c`, there is no `bad file descriptor` error. Instead, 
```
>>> import os
>>> f = open('conout$', 'w')
>>> os.get_terminal_size(f.fileno())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [WinError 6] The handle is invalid
```
Is this expected behavior? or anymore changes are needed? 
Any help would be appreciated.

**Comment by eryksun** [comment]
I gave an example of the required changes. The implementation should not hard code standard file descriptors 0-2. Instead, the statement `handle = (HANDLE)_get_osfhandle(fd)` is used for all file descriptors. The value of `handle` is an OS handle to be used directly in the `GetConsoleScreenBufferInfo()` call.
