### ISSUE TITLE
test_peg_generator.test_c_parser emits DeprecationWarning due to distutils

### ISSUE THREAD

**Issue by tirkarthi** [python/cpython#87591]
BPO | [43425](https://bugs.python.org/issue43425)
--- | :---
Nosy | @terryjreedy, @vstinner, @ambv, @zooba, @corona10, @pablogsal, @miss-islington, @tirkarthi
PRs | <li>python/cpython#26693</li><li>python/cpython#26713</li><li>python/cpython#26968</li><li>python/cpython#26969</li><li>python/cpython#26978</li><li>python/cpython#26981</li><li>python/cpython#26986</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-07.05:07:09.546>
labels = ['type-bug', 'tests', '3.10']
title = 'test_peg_generator.test_c_parser emits DeprecationWarning due to distutils'
updated_at = <Date 2021-09-15.13:15:47.651>
user = 'https://github.com/tirkarthi'
```

bugs.python.org fields:
```python
activity = <Date 2021-09-15.13:15:47.651>
actor = 'vstinner'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Tests']
creation = <Date 2021-03-07.05:07:09.546>
creator = 'xtreak'
dependencies = []
files = []
hgrepos = []
issue_num = 43425
keywords = ['patch']
message_count = 13.0
messages = ['388222', '388242', '388243', '388572', '388780', '395716', '395768', '396805', '396808', '396837', '396838', '397716', '401831']
nosy_count = 8.0
nosy_names = ['terry.reedy', 'vstinner', 'lukasz.langa', 'steve.dower', 'corona10', 'pablogsal', 'miss-islington', 'xtreak']
pr_nums = ['26693', '26713', '26968', '26969', '26978', '26981', '26986']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43425'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
> test_peg_generator still emits DeprecationWarning warnings.

Not anymore - it's skipped since 0faa0ba240e815614e5a2900e48007acac41b214.
