### ISSUE TITLE
Add function `clear` to the `os` module

### ISSUE THREAD

**Issue by a1fc7db5-8429-43ea-9b8f-f096a55500e3** [python/cpython#87598]
BPO | [43432](https://bugs.python.org/issue43432)
--- | :---
Nosy | @serhiy-storchaka, @eryksun, @parsampsh
PRs | <li>python/cpython#24784</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-08.12:05:40.847>
labels = ['type-feature', 'library', '3.10']
title = 'Add function `clear` to the `os` module'
updated_at = <Date 2021-03-08.18:12:38.683>
user = 'https://github.com/parsampsh'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-08.18:12:38.683>
actor = 'serhiy.storchaka'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-03-08.12:05:40.847>
creator = 'parsampsh'
dependencies = []
files = []
hgrepos = []
issue_num = 43432
keywords = ['patch']
message_count = 4.0
messages = ['388262', '388266', '388274', '388275']
nosy_count = 3.0
nosy_names = ['serhiy.storchaka', 'eryksun', 'parsampsh']
pr_nums = ['24784']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43432'
versions = ['Python 3.10']
```

</p></details>

**Comment by encukou** [comment]
The `clear` command is non-standard; some minimal systems don't include it.

Clearing the screen is not something the *OS* exposes, the `os` module isn't a good place for it. There might be a better place elsewhere, though -- especially now that ANSI terminal sequences start being usable on Windows and Python itself prints colorful tracebacks, we might want to expose something like `print('\033[2J\033[H')` under a friendly name.

But, GitHub issue is not the place for such a feature request. Please open a discussion on [Discourse](https://discuss.python.org/c/ideas/6) if you want to push this further.
