### ISSUE TITLE
Race conditions when the same source file used to build mutliple extensions

### ISSUE THREAD

**Issue by c139cf46-fb7c-4c62-96da-220de2afbec1** [python/cpython#87625]
BPO | [43459](https://bugs.python.org/issue43459)
--- | :---
Nosy | @merwok, @mgorny, @dstufft
Files | <li>[0001-A-reproducer-for-distutils-build_ext-race-condition.patch](https://bugs.python.org/file49863/0001-A-reproducer-for-distutils-build_ext-race-condition.patch "Uploaded as text/plain at 2021-03-10.07:42:11 by @mgorny"): A reproducer</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-10.07:42:12.398>
labels = ['3.7', '3.8', '3.9', '3.10', 'build', 'library']
title = 'Race conditions when the same source file used to build mutliple extensions'
updated_at = <Date 2021-03-10.07:42:12.398>
user = 'https://github.com/mgorny'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-10.07:42:12.398>
actor = 'mgorny'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Distutils']
creation = <Date 2021-03-10.07:42:12.398>
creator = 'mgorny'
dependencies = []
files = ['49863']
hgrepos = []
issue_num = 43459
keywords = ['patch']
message_count = 1.0
messages = ['388410']
nosy_count = 3.0
nosy_names = ['eric.araujo', 'mgorny', 'dstufft']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'compile error'
url = 'https://bugs.python.org/issue43459'
versions = ['Python 3.6', 'Python 3.7', 'Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by orlitzky** [comment]
Look what I found. Thanks to some great debugging by one of our users, we now know that this is causing random build failures of pplpy which has several extensions compiled from the same `.cc`  source: https://github.com/sagemath/pplpy/blob/master/setup.py#L79

**Comment by merwok** [comment]
Python does not include distutils, please report this to the setuptools project.

**Comment by orlitzky** [comment]
Didn't have to :)

https://github.com/pypa/setuptools/issues/3942
