### ISSUE TITLE
pathlib mistakenly assumes os.getcwd() is a resolved path in Windows

### ISSUE THREAD

**Issue by eryksun** [python/cpython#87621]
BPO | [43455](https://bugs.python.org/issue43455)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @eryksun, @zooba, @uranusjr
PRs | <li>python/cpython#17716</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-09.23:05:56.225>
labels = ['type-bug', '3.8', '3.9', '3.10', 'library', 'OS-windows']
title = 'pathlib mistakenly assumes os.getcwd() is a resolved path in Windows'
updated_at = <Date 2022-03-03.10:05:28.651>
user = 'https://github.com/eryksun'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-03.10:05:28.651>
actor = 'uranusjr'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)', 'Windows']
creation = <Date 2021-03-09.23:05:56.225>
creator = 'eryksun'
dependencies = []
files = []
hgrepos = []
issue_num = 43455
keywords = ['patch']
message_count = 2.0
messages = ['388393', '414415']
nosy_count = 6.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'eryksun', 'steve.dower', 'uranusjr']
pr_nums = ['17716']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43455'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by barneygale** [comment]
Hey @eryksun, could you check whether this is valid after #25264 was merged? Pathlib now calls `ntpath.realpath()`, which (from scanning the code) doesn't appear to suffer from this bug.

**Comment by eryksun** [comment]
I never had a practical case for `not s`, since it's at least ".". Anyway, this is a non-issue now. It was only kept open for 3.8 and 3.9, and the last bugfix for 3.9 was released on 2022-05-17.
