### ISSUE TITLE
Python 3.9 installer not updating ARP table

### ISSUE THREAD

**Issue by dcbea8c1-6616-4edd-924e-e54a623f05f0** [python/cpython#87652]
BPO | [43486](https://bugs.python.org/issue43486)
--- | :---
Nosy | @pfmoore, @tjguk, @zware, @zooba, @codaamok
Files | <li>[1.jpg](https://bugs.python.org/file49873/1.jpg "Uploaded as image/jpeg at 2021-03-13.13:20:10 by @codaamok"): Two screenshots, see comment for context</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-13.13:20:10.315>
labels = ['type-bug', 'expert-installation', '3.9', 'OS-windows']
title = 'Python 3.9 installer not updating ARP table'
updated_at = <Date 2021-03-15.20:01:50.301>
user = 'https://github.com/codaamok'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-15.20:01:50.301>
actor = 'steve.dower'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Installation', 'Windows']
creation = <Date 2021-03-13.13:20:10.315>
creator = 'codaamok'
dependencies = []
files = ['49873']
hgrepos = []
issue_num = 43486
keywords = []
message_count = 3.0
messages = ['388615', '388620', '388774']
nosy_count = 5.0
nosy_names = ['paul.moore', 'tim.golden', 'zach.ware', 'steve.dower', 'codaamok']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43486'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
There was no response to @zooba s request for additional information, and 3.9 is no longer maintained, so I am closing this. Please reopen or create a new issue if you are seeing this problem on a supported python version (>= 3.10 at the moment) and are able to provide the information requested.
