### ISSUE TITLE
[sqlite3] Explicitly initialise and shut down sqlite3

### ISSUE THREAD

**Issue by erlend-aasland** [python/cpython#87671]
BPO | [43505](https://bugs.python.org/issue43505)
--- | :---
Nosy | @berkerpeksag, @serhiy-storchaka, @erlend-aasland
PRs | <li>python/cpython#25404</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-04-14.14:51:02.925>
created_at = <Date 2021-03-15.23:09:44.794>
labels = ['type-feature', 'library', '3.10']
title = '[sqlite3] Explicitly initialise and shut down sqlite3'
updated_at = <Date 2021-04-14.15:00:17.095>
user = 'https://github.com/erlend-aasland'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-14.15:00:17.095>
actor = 'erlendaasland'
assignee = 'none'
closed = True
closed_date = <Date 2021-04-14.14:51:02.925>
closer = 'berker.peksag'
components = ['Library (Lib)']
creation = <Date 2021-03-15.23:09:44.794>
creator = 'erlendaasland'
dependencies = []
files = []
hgrepos = []
issue_num = 43505
keywords = ['patch']
message_count = 4.0
messages = ['388788', '391083', '391084', '391085']
nosy_count = 3.0
nosy_names = ['berker.peksag', 'serhiy.storchaka', 'erlendaasland']
pr_nums = ['25404']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43505'
versions = ['Python 3.10']
```

</p></details>

**Comment by sedoy107** [comment]
While using **sqlite3** module as a part of python application, what is the right way now to call **sqlite3_config** given it must be called prior to **sqlite3_initialize**? 

Below is a simplified version of code my application uses:

`
>>> import sqlite3 # sqlite3 module in me app has already been called somewhere above by coverage module
>>> from ctypes import *
>>> from ctypes.util import *
>>> libpath = find_library('sqlite3')
>>> _sqlite3 = CDLL(libpath)
>>> _sqlite3_config = _sqlite3.sqlite3_config
>>> _sqlite3_config.argtypes = [c_int]
>>> _sqlite3_config.restype = c_int
>>> _sqlite3_config(16)
21 <----- SQLITE_MISUSE
`

My actual application uses **coverage** module (during unit tests). It creates separate python processes where each 
imports **sqlite3** executing application code. Hence SQLITE_MISUSE is issued.

Calling _sqlite3.sqlite3_shutdown() prior calling sqlite3_config seems like a viable solution in my case but I wonder if there is a better, not a hacky way. Thanks

**Comment by erlend-aasland** [comment]
> While using sqlite3 module as a part of python application, what is the right way now to call sqlite3_config given it must be called prior to sqlite3_initialize?

You need to call `sqlite3_config` before importing the sqlite3 extension module.
