### ISSUE TITLE
tkinter with Tk 8.6.11 is slow on macOS

### ISSUE THREAD

**Issue by 243a827b-4d1c-41d5-84fe-664c33bec48d** [python/cpython#87677]
BPO | [43511](https://bugs.python.org/issue43511)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @aivarannamaa, @serhiy-storchaka, @chrstphrchvz, @E-Paine
Files | <li>[tkbench.zip](https://bugs.python.org/file49905/tkbench.zip "Uploaded as application/zip at 2021-03-23.14:55:17 by @E-Paine")</li><li>[results-tkbench.txt](https://bugs.python.org/file49908/results-tkbench.txt "Uploaded as text/plain at 2021-03-24.12:06:13 by thomaswamm"): Terminal transcript of tk benchmarks on M1 Mac Mini</li><li>[results_tk-bench_Win10_i5-8250U.txt](https://bugs.python.org/file49913/results_tk-bench_Win10_i5-8250U.txt "Uploaded as text/plain at 2021-03-24.21:44:05 by thomaswamm"): Terminal transcript of bench.py on 3 Win10 pythons</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-16.06:13:14.383>
labels = ['OS-mac', 'expert-tkinter', '3.9', '3.10', 'performance']
title = 'tkinter with Tk 8.6.11 is slow on macOS'
updated_at = <Date 2021-04-22.12:16:27.487>
user = 'https://bugs.python.org/thomaswamm'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-22.12:16:27.487>
actor = 'Aivar.Annamaa'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS', 'Tkinter']
creation = <Date 2021-03-16.06:13:14.383>
creator = 'thomaswamm'
dependencies = []
files = ['49905', '49908', '49913']
hgrepos = []
issue_num = 43511
keywords = []
message_count = 17.0
messages = ['388822', '388829', '388905', '388917', '388957', '389383', '389384', '389389', '389446', '389447', '389448', '389450', '389477', '389478', '389490', '390224', '391593']
nosy_count = 7.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'Aivar.Annamaa', 'serhiy.storchaka', 'chrstphrchvz', 'epaine', 'thomaswamm']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue43511'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by ronaldoussoren** [comment]
@ned-deily : I propose closing this issue because this an issue with Tk and not something we can fix in CPython.

**Comment by serhiy-storchaka** [comment]
Looking at the difference between macOS and Linux (4 vs 200!), it seems to me, that Tk "cheated" on macOS. Now it "cheats" less.

**Comment by ned-deily** [comment]
> I propose closing this issue because this an issue with Tk and not something we can fix in CPython.

I agree.
