### ISSUE TITLE
Disallow fork in a subinterpreter affects multiprocessing plugin

### ISSUE THREAD

**Issue by 9ddeca9f-a5da-4419-a818-48482f8f6dcd** [python/cpython#87680]
BPO | [43514](https://bugs.python.org/issue43514)
--- | :---
Nosy | @tiran, @franku

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-16.14:41:07.868>
labels = ['expert-C-API', 'type-bug', '3.8']
title = 'Disallow fork in a subinterpreter affects multiprocessing plugin'
updated_at = <Date 2021-03-16.20:48:00.370>
user = 'https://github.com/franku'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-16.20:48:00.370>
actor = 'franku'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['C API']
creation = <Date 2021-03-16.14:41:07.868>
creator = 'franku'
dependencies = []
files = []
hgrepos = []
issue_num = 43514
keywords = []
message_count = 5.0
messages = ['388841', '388842', '388876', '388877', '388879']
nosy_count = 2.0
nosy_names = ['christian.heimes', 'franku']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43514'
versions = ['Python 3.8']
```

</p></details>

**Comment by terryjreedy** [comment]
Closing because the failure caused by #78832 is intentional, not a bug; the question "Is there a way to circumvent rewriting our code completely?" belongs elsewhere [Discuss-help](https://discuss.python.org/c/users/7); and because a mannequin user would not get an answer given here.
