### ISSUE TITLE
Make str.join auto-convert inputs to strings.

### ISSUE THREAD

**Issue by rhettinger** [python/cpython#87701]
BPO | [43535](https://bugs.python.org/issue43535)
--- | :---
Nosy | @rhettinger, @terryjreedy, @gpshead, @ericvsmith, @tiran, @gst, @serhiy-storchaka, @vedgar, @pablogsal, @tirkarthi, @isidentical, @EmilStenstrom, @jack1142, @kamilturek, @ajoino

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2021-03-23.21:21:24.627>
created_at = <Date 2021-03-18.02:29:06.250>
labels = ['interpreter-core', 'type-feature', '3.10']
title = 'Make str.join auto-convert inputs to strings.'
updated_at = <Date 2021-03-23.21:21:24.626>
user = 'https://github.com/rhettinger'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-23.21:21:24.626>
actor = 'rhettinger'
assignee = 'none'
closed = True
closed_date = <Date 2021-03-23.21:21:24.627>
closer = 'rhettinger'
components = ['Interpreter Core']
creation = <Date 2021-03-18.02:29:06.250>
creator = 'rhettinger'
dependencies = []
files = []
hgrepos = []
issue_num = 43535
keywords = []
message_count = 21.0
messages = ['388983', '388985', '388992', '388994', '389006', '389048', '389106', '389135', '389144', '389148', '389170', '389171', '389176', '389180', '389181', '389190', '389192', '389213', '389228', '389241', '389410']
nosy_count = 16.0
nosy_names = ['rhettinger', 'terry.reedy', 'gregory.p.smith', 'eric.smith', 'christian.heimes', 'mrabarnett', 'gstarck', 'serhiy.storchaka', 'veky', 'pablogsal', 'xtreak', 'BTaskaya', 'EmilStenstrom', 'jack1142', 'kamilturek', 'ajoino']
pr_nums = []
priority = 'normal'
resolution = None
stage = 'resolved'
status = 'closed'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43535'
versions = ['Python 3.10']
```

</p></details>

**Comment by terryjreedy** [comment]
I am now not as convinced by my own pro arguments above as I am now.  print is exceptional in that it is meant to be quick and possibly dirty output, perhaps for debugging.  str.join is a regular method that calculates a string and I see the point about strong typing better than I did before.  https://github.com/python/cpython/issues/87701#issuecomment-1093906804 answered my request for a bug example.
