### ISSUE TITLE
importlib: Document how to replace load_module() in What's New in Python 3.10

### ISSUE THREAD

**Issue by vstinner** [python/cpython#87706]
BPO | [43540](https://bugs.python.org/issue43540)
--- | :---
Nosy | @brettcannon, @vstinner, @webknjaz, @The-Compiler, @hroncok

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = <Date 2022-02-01.01:08:45.591>
created_at = <Date 2021-03-18.10:19:33.614>
labels = ['library', '3.10', 'docs']
title = "importlib: Document how to replace load_module() in What's New in Python 3.10"
updated_at = <Date 2022-02-01.01:08:45.590>
user = 'https://github.com/vstinner'
```

bugs.python.org fields:
```python
activity = <Date 2022-02-01.01:08:45.590>
actor = 'vstinner'
assignee = 'docs@python'
closed = True
closed_date = <Date 2022-02-01.01:08:45.591>
closer = 'vstinner'
components = ['Documentation', 'Library (Lib)']
creation = <Date 2021-03-18.10:19:33.614>
creator = 'vstinner'
dependencies = []
files = []
hgrepos = []
issue_num = 43540
keywords = []
message_count = 7.0
messages = ['389007', '389033', '390514', '390515', '390541', '390556', '412231']
nosy_count = 6.0
nosy_names = ['brett.cannon', 'vstinner', 'docs@python', 'webknjaz', 'The Compiler', 'hroncok']
pr_nums = []
priority = 'normal'
resolution = 'out of date'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue43540'
versions = ['Python 3.10']
```

</p></details>

**Comment by svenpanne** [comment]
Just out of curiosity: What _exactly_ is the supposed replacement for `load_module()` from an _API user_ point of view? (i.e. not from the POV of somebody trying to implement a Loader) More concretely: What should be the replacement for:

```python
importlib.machinery.SourceFileLoader(name, path).load_module()
```

I simply don't understand the sparse documentation for importlib in that regard, but we need to maintain/update the legacy code above.

**Comment by svenpanne** [comment]
Thanks for the link, it clears things up a little bit. I think it might be a good idea to directly link to the examples (or even have copies of them) in the paragraphs for the deprecated features. Something a dozen screens below is hard to discover.

Anyway, the code snippet there is not really a replacement: `spec_from_file_location()` has some magic regarding file extensions in it, so it doesn't work with e.g. Python files without a `.py` extension. The deprecated `load_module()` method handled this fine. Let's see if I can copy-n-paste some stuff from `importlib.utils` together to have a _real_ replacement.

**Comment by brettcannon** [comment]
You can construct the module spec yourself without much issue, you just need to fill in relevant details like whether it's for a package or not.
