### ISSUE TITLE
RecursionError depth exceptions break pdb's interactive tracing.

### ISSUE THREAD

**Issue by 3c4ccca5-76f8-4151-8a92-6a826ff4f0e2** [python/cpython#87714]
BPO | [43548](https://bugs.python.org/issue43548)
--- | :---
Nosy | @iritkatriel, @jdevries3133
Files | <li>[runawaystepping.py](https://bugs.python.org/file49891/runawaystepping.py "Uploaded as text/plain at 2021-03-19.02:44:55 by behindthebrain"): The simplified code to reproduce the bug.</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-19.02:44:55.809>
labels = ['interpreter-core', '3.8', 'type-crash']
title = "RecursionError depth exceptions break pdb's interactive tracing."
updated_at = <Date 2021-07-28.23:23:10.216>
user = 'https://bugs.python.org/behindthebrain'
```

bugs.python.org fields:
```python
activity = <Date 2021-07-28.23:23:10.216>
actor = 'jack__d'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Interpreter Core']
creation = <Date 2021-03-19.02:44:55.809>
creator = 'behindthebrain'
dependencies = []
files = ['49891']
hgrepos = []
issue_num = 43548
keywords = []
message_count = 3.0
messages = ['389051', '398439', '398442']
nosy_count = 3.0
nosy_names = ['iritkatriel', 'behindthebrain', 'jack__d']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue43548'
versions = ['Python 3.8']
```

</p></details>

**Comment by iritkatriel** [comment]
Closing as it's not clear what the problem is and there was not response to followup questions.
