### ISSUE TITLE
Leak in asyncio.selector_events._SelectorSocketTransport

### ISSUE THREAD

**Issue by 17ec2c0c-c412-4235-a96e-4c24d9810a75** [python/cpython#87745]
BPO | [43579](https://bugs.python.org/issue43579)
--- | :---
Nosy | @asvetlov, @1st1, @begnac

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-21.07:11:10.990>
labels = ['expert-asyncio', '3.9', '3.10', 'performance']
title = 'Leak in asyncio.selector_events._SelectorSocketTransport'
updated_at = <Date 2021-03-21.07:11:10.990>
user = 'https://github.com/begnac'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-21.07:11:10.990>
actor = 'begnac'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-03-21.07:11:10.990>
creator = 'begnac'
dependencies = []
files = []
hgrepos = []
issue_num = 43579
keywords = []
message_count = 1.0
messages = ['389219']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'begnac']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue43579'
versions = ['Python 3.9', 'Python 3.10']
```

</p></details>

**Comment by kumaraditya303** [comment]
The gc would break the cycle anyways, is this an issue in practice? @begnac

**Comment by begnac** [comment]
Sorry  ... ehm ... what ?  I don't manage to find the beginning of this
thread, can you give me some context ?



Le samedi 24 septembre 2022 à 05:49 -0700, Kumar Aditya a écrit :
> Leak in asyncio.selector_events._SelectorSocketTransport

**Comment by begnac** [comment]
In my experience, the gc doesn't always break all the cycles.
Personally I like to check for cycles in my code and clean them up, just in case.    Sometimes I stumble over cycles in code I use.    Specifically about this one, it's been such a long time I do not remember...  but if I found it, it's because something didn't get cleaned up :)

**Comment by gvanrossum** [comment]
I think it's a reasonable suggestion and the fix should be simple.

**Comment by kumaraditya303** [comment]
@begnac Want to create a PR for this?

**Comment by kumaraditya303** [comment]
Duplicate of https://github.com/python/cpython/issues/100348
