### ISSUE TITLE
With asyncio subprocess, send_signal() and the child process watcher will both call waitpid()

### ISSUE THREAD

**Issue by be5b94be-e792-4ee2-a535-0fe6678ee224** [python/cpython#87744]
BPO | [43578](https://bugs.python.org/issue43578)
--- | :---
Nosy | @asvetlov, @1st1, @lincheney

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-21.06:53:15.574>
labels = ['type-bug', '3.9', 'expert-asyncio']
title = 'With asyncio subprocess, send_signal() and the child process watcher will both call waitpid()'
updated_at = <Date 2021-03-21.06:53:15.574>
user = 'https://github.com/lincheney'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-21.06:53:15.574>
actor = 'lincheney'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-03-21.06:53:15.574>
creator = 'lincheney'
dependencies = []
files = []
hgrepos = []
issue_num = 43578
keywords = []
message_count = 1.0
messages = ['389218']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'lincheney']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43578'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-121126
* gh-121194

**Comment by FabianElsmer** [comment]
Did you find a workaround for this?

**Comment by gvanrossum** [comment]
This one is new to me. I’m not sure how to approach it yet. The only workaround I can think of without digging in the code would be to ignore the error using try/except, but that’s a last resort.

**Comment by gvanrossum** [comment]
@graingert Any idea here?

**Comment by gvanrossum** [comment]
Oops, I see the problem isn't an exception so much as a lost exit status. I'm guessing we need to improve the communication between asyncio.subprocess.Process.wait() and the child watchers.

**Comment by kumaraditya303** [comment]
On my TODO list but low priority, I can review a PR fixing this though.

**Comment by kumaraditya303** [comment]
Child watcher will be removed in 3.14 at which point this will have to be reworked again so I'll fix this after child watchers are removed, it will be much simpler then.

**Comment by willingc** [comment]
Revisit after completion of https://github.com/python/cpython/issues/120804

**Comment by astrand** [comment]
This is a major issue for us, I am surprised that this issue is not getting more attention. It can be reproduced with the test case above on Python 3.9 and 3.10; please add corresponding labels. If I understand it correctly, the problem was introduced with https://bugs.python.org/issue38630 . Is it correct that the only workaround is to use os.kill instead of proc.terminate/proc.kill?

**Comment by gvanrossum** [comment]
> This is a major issue for us, I am surprised that this issue is not getting more attention. It can be reproduced with the test case above on Python 3.9 and 3.10; please add corresponding labels. If I understand it correctly, the problem was introduced with https://bugs.python.org/issue38630 . Is it correct that the only workaround is to use os.kill instead of proc.terminate/proc.kill?

Temper your rhetoric, please. Just upgrade to Python 3.13.

**Comment by astrand** [comment]
> > This is a major issue for us, I am surprised that this issue is not getting more attention. It can be reproduced with the test case above on Python 3.9 and 3.10; please add corresponding labels. If I understand it correctly, the problem was introduced with https://bugs.python.org/issue38630 . Is it correct that the only workaround is to use os.kill instead of proc.terminate/proc.kill?
> 
> Temper your rhetoric, please. Just upgrade to Python 3.13.

Easier said than done. In our case the situation is the same as for most users, I believe: Python is provided by the platform. In our case, Yocto Kirkstone, which includes Python 3.10. In theory we could upgrade to the next Yocto LTS release which is Scarthgap, but it only includes Python 3.12; not 3.13. 

The workaround with os.kill seems to work, though, at least with SafeChildWatcher.
