### ISSUE TITLE
[Subinterpreters]: use static variable under building Python with --with-experimental-isolated-subinterpreters cause crash.

### ISSUE THREAD

**Issue by 7aa09af7-4256-46da-93fc-f6eef717c259** [python/cpython#87754]
BPO | [43588](https://bugs.python.org/issue43588)
--- | :---
Nosy | @vstinner, @corona10, @shihai1991, @JunyiXie, @kumaraditya303
PRs | <li>python/cpython#24963</li><li>python/cpython#24929</li><li>python/cpython#24965</li><li>python/cpython#24966</li><li>python/cpython#24968</li><li>python/cpython#24969</li><li>python/cpython#24970</li><li>python/cpython#24971</li><li>python/cpython#24972</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-22.08:09:32.063>
labels = ['expert-subinterpreters', '3.10', 'type-crash']
title = '[Subinterpreters]: use static variable under building Python with --with-experimental-isolated-subinterpreters cause crash.'
updated_at = <Date 2022-04-07.08:17:57.850>
user = 'https://github.com/JunyiXie'
```

bugs.python.org fields:
```python
activity = <Date 2022-04-07.08:17:57.850>
actor = 'kumaraditya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Subinterpreters']
creation = <Date 2021-03-22.08:09:32.063>
creator = 'JunyiXie'
dependencies = []
files = []
hgrepos = []
issue_num = 43588
keywords = ['patch']
message_count = 13.0
messages = ['389282', '389284', '389292', '389300', '389304', '389310', '389311', '389322', '389323', '389324', '406069', '406080', '416918']
nosy_count = 5.0
nosy_names = ['vstinner', 'corona10', 'shihai1991', 'JunyiXie', 'kumaraditya']
pr_nums = ['24963', '24929', '24965', '24966', '24968', '24969', '24970', '24971', '24972']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'crash'
url = 'https://bugs.python.org/issue43588'
versions = ['Python 3.10']
```

</p></details>

**Comment by erlend-aasland** [comment]
> Most of the static variables were removed by #75547 so I closed those PRs as they were outdated, however some static variable still exist.

Kumar, I think you linked to the incorrect issue or PR. Would you mind updating it with the correct number?

**Comment by kumaraditya303** [comment]
> Kumar, I think you linked to the incorrect issue or PR. Would you mind updating it with the correct number?

Good catch Erlend! Thanks I updated the PR number, I wonder if it was a C&P error on my end or the Github migration caused it.
