### ISSUE TITLE
convenience of using create_datagram_endpoint (and friends)

### ISSUE THREAD

**Issue by 20b7258c-7e53-44cb-9fb5-3a40f28734f7** [python/cpython#87785]
BPO | [43619](https://bugs.python.org/issue43619)
--- | :---
Nosy | @asvetlov, @1st1
Files | <li>[async.py](https://bugs.python.org/file49912/async.py "Uploaded as text/plain at 2021-03-24.20:18:16 by Roman.Valov")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-24.20:18:16.377>
labels = ['type-feature', '3.8', 'expert-asyncio']
title = 'convenience of using create_datagram_endpoint (and friends)'
updated_at = <Date 2021-03-24.20:18:16.377>
user = 'https://bugs.python.org/RomanValov'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-24.20:18:16.377>
actor = 'Roman.Valov'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-03-24.20:18:16.377>
creator = 'Roman.Valov'
dependencies = []
files = ['49912']
hgrepos = []
issue_num = 43619
keywords = []
message_count = 1.0
messages = ['389488']
nosy_count = 3.0
nosy_names = ['asvetlov', 'yselivanov', 'Roman.Valov']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43619'
versions = ['Python 3.8']
```

</p></details>

**Comment by kumaraditya303** [comment]
In a real application you would have a awaitable on which you await till the server finishes, you can use a future for indefinite sleep,  I don't think it is a hack. 

For issue 2, you need to run the coroutines as tasks and it's `asyncio` design that protocol callbacks are sync and that can't be changed, it will open another can of worms at this point. 

For these questions you can use https://discuss.python.org/c/users/7 forum.
