### ISSUE TITLE
ctypes.util.find_library can't find the lib on Alpine

### ISSUE THREAD

**Issue by 0c607e04-c633-4264-8925-28fa9ab325a6** [python/cpython#87808]
BPO | [43642](https://bugs.python.org/issue43642)
--- | :---

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-27.15:54:09.070>
labels = ['ctypes', 'type-bug', '3.9']
title = "ctypes.util.find_library can't find the lib on Alpine"
updated_at = <Date 2021-03-27.15:54:09.070>
user = 'https://bugs.python.org/An1c0de'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-27.15:54:09.070>
actor = 'An1c0de'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['ctypes']
creation = <Date 2021-03-27.15:54:09.070>
creator = 'An1c0de'
dependencies = []
files = []
hgrepos = []
issue_num = 43642
keywords = []
message_count = 1.0
messages = ['389609']
nosy_count = 1.0
nosy_names = ['An1c0de']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43642'
versions = ['Python 3.9']
```

</p></details>

**Comment by encukou** [comment]
Alpine/musl is unsupported per PEP-11. (It would be nice to support it, but, people interested in doing the work somehow don't show up around this repo.)

I'll close the bug. Like other issues for unsupported platforms, it'll be listed on [the GitHub project](https://github.com/orgs/python/projects/27) for anyone who wants to support the platform unofficially or work to make it officially supported.
I encourage such people to add themselves to the [Experts list](https://devguide.python.org/core-developers/experts/#platforms) so we know whom to ping.
