### ISSUE TITLE
MacOS os.statvfs() has rollover for >4TB disks at each 4TB (32bit counter overflow?)

### ISSUE THREAD

**Issue by 5eb57978-e77a-474c-bd1d-b250980f162b** [python/cpython#87804]
BPO | [43638](https://bugs.python.org/issue43638)
--- | :---
Nosy | @ronaldoussoren, @ned-deily, @Safihre, @sanderjo

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-27.10:36:42.644>
labels = ['OS-mac', 'type-bug', '3.9']
title = 'MacOS os.statvfs() has rollover for >4TB disks at each 4TB (32bit counter overflow?)'
updated_at = <Date 2021-03-29.08:41:43.606>
user = 'https://github.com/sanderjo'
```

bugs.python.org fields:
```python
activity = <Date 2021-03-29.08:41:43.606>
actor = 'sanderjo'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['macOS']
creation = <Date 2021-03-27.10:36:42.644>
creator = 'sanderjo'
dependencies = []
files = []
hgrepos = []
issue_num = 43638
keywords = []
message_count = 4.0
messages = ['389596', '389607', '389668', '389674']
nosy_count = 4.0
nosy_names = ['ronaldoussoren', 'ned.deily', 'Safihre', 'sanderjo']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43638'
versions = ['Python 3.9']
```

</p></details>

### Linked PRs
* gh-99570
* gh-115236
* gh-115335

**Comment by Safihre** [comment]
For reference, link to our workaround:
https://github.com/sabnzbd/sabnzbd/blob/92883f313a518158bdc3369c418a37037439eb42/sabnzbd/filesystem.py#L977-L1003

**Comment by ned-deily** [comment]
I am not an expert on this but I think the `statfs` description you are linking to above is out-of-date. The current macOS man page for `statfs` states in part:

```
     The statfs64 and fstatfs64 routines are equivalent to their corresponding non-64-suffixed routine, when
     64-bit inodes are in effect.  They were added before there was support for the symbol variants, and so
     are now deprecated.  Instead of using these, set the _DARWIN_USE_64_BIT_INODE macro before including
     header files to force 64-bit inode support.

     The statfs64 structure used by these deprecated routines is the same as the statfs structure when
     64-bit inodes are in effect (see above).

```

and the `_DARWIN_USE_64_BIT_INODE` macro is available from at least macOS 10.5 on. So I would think it should be possible to implement a workaround within `_posixmodule.c` using macOS's `statfs`.  A PR would be welcome :)

**Comment by ronaldoussoren** [comment]
Implementing os.statvfs using statfs(2) isn't as easy as I'd like: the f_namemax field of struct statvfs is not available in struct statfs. It is possibly to use pathconf(2) instead, or keep using statvfs(2) to get this field.

**Comment by ronaldoussoren** [comment]
The block counts reported by statvfs are always 32-bit, the macro's mentioned by Ned are for statfs (not the lack of a 'v' in the name). 

I've looked at the statvfs source code (yay opensource) for macOS 13 and even f_namemax is easy to replicate: libc just sets that field to a fixed value and not something that is filesystem specific. In hindsight that was expected, all filesystems users are likely to encounter support 255 characters in file names...

Longer term it might be interesting to expose statfs directly, but that's for a different issue and something that needs design work because the statfs structures used by Linux and macOS are different (and I haven't looked at other OS-es).

**Comment by ronaldoussoren** [comment]
I have (finally!) merged my PR.  I won't merge the PR into 3.11 and 3.12, because the change is a bit too large for that to my taste.

**Comment by sobolevn** [comment]
Sorry, I've missed this PR during the review phase :(
I have several comments with small changes, PR is ready.
@ronaldoussoren can you please take a look? :)

**Comment by encukou** [comment]
After the error handling fix, the refleaks buildbot started failing.
If we don't manage to fix it today, we need to revert for alpha 4 (scheduled tomorow), and fix it for the next alpha.

**Comment by encukou** [comment]
## Reposting investigation from @Eclips4

> Bisected to #115236
> I spent about an hour to try figure out what's happening.
> First of all, for some reason it's not reproducible on non-freethreading build. Changes in #115236 also isn't > related to free-threading.
> 
> We have this macros:
> ```c
>     do {                                           \
>         if (item == NULL) {                        \
>             Py_DECREF(v);                          \
>             return NULL;                           \
>         }                                          \
>         PyStructSequence_SET_ITEM(v, index, item); \
>     } while (0)                                    \
> ```
> If we rewrite this macros like this:
> ```c
> #define SET_ITEM(v, index, item)                   \
>     do {                                           \
>         PyStructSequence_SET_ITEM(v, index, item); \
>     } while (0)                                    \
> ```
> Refleaks are gone!! Why???
> I've checked it and what is amazing is that the body of this if statement isn't executed at all..

**Comment by sobolevn** [comment]
Working on the fix! Thanks for the report.

**Comment by vstinner** [comment]
> After the error handling fix, the refleaks buildbot started failing.

Apparently, the leak only occurs on macOS, on the ARM64 MacOS M1 Refleaks NoGIL 3.x worker: https://buildbot.python.org/all/#/builders/1368/builds/184

```
6 tests failed:
    test_largefile test_os test_pickle test_pickletools test_posix
    test_shutil
```

**Comment by sobolevn** [comment]
I've done manual testing.

Before:

```
» ./python.exe -m test -R 3:3 test_os test_pickle test_pickletools test_posix test_shutil
Using random seed: 690889334
0:00:00 load avg: 4.23 Run 5 tests sequentially
0:00:00 load avg: 4.23 [1/5] test_os
beginning 6 repetitions
123456
/Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=8886) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
.
test_os leaked [36, 36, 36] references, sum=108
test_os leaked [36, 36, 36] memory blocks, sum=108
0:00:08 load avg: 3.96 [2/5/1] test_pickle -- test_os failed (reference leak)
beginning 6 repetitions
123456
......
test_pickle leaked [272, 272, 272] references, sum=816
test_pickle leaked [270, 270, 270] memory blocks, sum=810
0:00:45 load avg: 3.27 [3/5/2] test_pickletools -- test_pickle failed (reference leak) in 37.4 sec
beginning 6 repetitions
123456
......
0:00:49 load avg: 3.25 [4/5/2] test_posix
beginning 6 repetitions
123456
......
test_posix leaked [27, 27, 27] references, sum=81
test_posix leaked [27, 27, 27] memory blocks, sum=81
0:00:57 load avg: 3.15 [5/5/3] test_shutil -- test_posix failed (reference leak)
beginning 6 repetitions
123456
......
test_shutil leaked [18, 18, 18] references, sum=54
test_shutil leaked [18, 18, 18] memory blocks, sum=54
test_shutil failed (reference leak)

== Tests result: FAILURE ==

4 tests failed:
    test_os test_pickle test_posix test_shutil

1 test OK.

Total duration: 1 min 1 sec
Total tests: run=1,642 skipped=203
Total test files: run=5/5 failed=4
Result: FAILURE
```

After:

```
» ./python.exe -m test -R 3:3 test_os test_pickle test_pickletools test_posix test_shutil
Using random seed: 1906848956
0:00:00 load avg: 1.70 Run 5 tests sequentially
0:00:00 load avg: 1.70 [1/5] test_os
beginning 6 repetitions
123456
/Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
./Users/sobolev/Desktop/cpython2/Lib/os.py:861: DeprecationWarning: This process (pid=667) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = fork()
.
0:00:08 load avg: 1.98 [2/5] test_pickle
beginning 6 repetitions
123456
......
0:00:46 load avg: 2.45 [3/5] test_pickletools -- test_pickle passed in 38.2 sec
beginning 6 repetitions
123456
......
0:00:50 load avg: 2.33 [4/5] test_posix
beginning 6 repetitions
123456
......
0:00:58 load avg: 2.20 [5/5] test_shutil
beginning 6 repetitions
123456
......

== Tests result: SUCCESS ==

All 5 tests OK.

Total duration: 1 min 2 sec
Total tests: run=1,642 skipped=203
Total test files: run=5/5
Result: SUCCESS
```

No refleaks anymore 🎉 

I will wait for the CI to get green and merge. Thanks everyone for their feedback!

**Comment by sobolevn** [comment]
Looks like new runs of m1 free-threaded refleaks buildbot is successful: https://buildbot.python.org/all/#/builders/1368/builds/188

We can hopefully close this issue now :)
