### ISSUE TITLE
Extensions build does not respect --jobs setting

### ISSUE THREAD

**Issue by 69ca5d4d-87eb-4a8c-9d6c-aab0bb9043ab** [python/cpython#87800]
BPO | [43634](https://bugs.python.org/issue43634)
--- | :---
Nosy | @ncoghlan, @encukou, @JustAnotherArchivist

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-26.18:58:30.950>
labels = ['build', '3.9', 'performance']
title = 'Extensions build does not respect --jobs setting'
updated_at = <Date 2021-04-03.01:20:46.248>
user = 'https://github.com/JustAnotherArchivist'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-03.01:20:46.248>
actor = 'terry.reedy'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Build']
creation = <Date 2021-03-26.18:58:30.950>
creator = 'JustAnotherArchivist'
dependencies = []
files = []
hgrepos = []
issue_num = 43634
keywords = []
message_count = 1.0
messages = ['389558']
nosy_count = 3.0
nosy_names = ['ncoghlan', 'petr.viktorin', 'JustAnotherArchivist']
pr_nums = []
priority = 'normal'
resolution = None
stage = None
status = 'open'
superseder = None
type = 'resource usage'
url = 'https://bugs.python.org/issue43634'
versions = ['Python 3.9']
```

</p></details>

**Comment by iritkatriel** [comment]
@zooba Will this still be relevant after distutils is removed?

**Comment by zooba** [comment]
No idea. @tiran may have a better idea?

**Comment by tiran** [comment]
It's no longer a problem in 3.12. All extensions are now built by Makefile.

**Comment by iritkatriel** [comment]
Since it's not a problem in 3.12 and we don't backport performance improvements, I think this can be closed.

@pablogsal do you agree?
