### ISSUE TITLE
PEP 597: Fix EncodingWarning warnings in the Python stdlib

### ISSUE THREAD

**Issue by methane** [python/cpython#87817]
BPO | [43651](https://bugs.python.org/issue43651)
--- | :---
Nosy | @vstinner, @methane
PRs | <li>python/cpython#25097</li><li>python/cpython#25109</li><li>python/cpython#25126</li><li>python/cpython#25127</li><li>python/cpython#25128</li><li>python/cpython#25142</li><li>python/cpython#25145</li><li>python/cpython#25158</li><li>python/cpython#25159</li><li>python/cpython#25171</li><li>python/cpython#25181</li><li>python/cpython#25189</li><li>python/cpython#25190</li><li>python/cpython#25192</li><li>python/cpython#25204</li><li>python/cpython#25644</li><li>python/cpython#25645</li><li>python/cpython#25648</li><li>python/cpython#25650</li><li>python/cpython#25654</li><li>python/cpython#25655</li><li>python/cpython#25715</li>
Superseder | <li>bpo-43510: PEP 597: Implemente encoding=&quot;locale&quot; option and EncodingWarning</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-29.04:30:27.870>
labels = ['3.10']
title = 'PEP 597: Fix EncodingWarning warnings in the Python stdlib'
updated_at = <Date 2021-04-29.11:37:41.800>
user = 'https://github.com/methane'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-29.11:37:41.800>
actor = 'methane'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-03-29.04:30:27.870>
creator = 'methane'
dependencies = []
files = []
hgrepos = []
issue_num = 43651
keywords = ['patch']
message_count = 22.0
messages = ['389945', '389946', '390019', '390020', '390021', '390033', '390158', '390176', '390220', '390221', '390222', '390268', '390271', '390273', '390293', '392021', '392024', '392030', '392031', '392274', '392275', '392301']
nosy_count = 3.0
nosy_names = ['vstinner', 'methane', 'ttx11529']
pr_nums = ['25097', '25109', '25126', '25127', '25128', '25142', '25145', '25158', '25159', '25171', '25181', '25189', '25190', '25192', '25204', '25644', '25645', '25648', '25650', '25654', '25655', '25715']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = '43510'
type = None
url = 'https://bugs.python.org/issue43651'
versions = ['Python 3.10']
```

</p></details>

**Comment by vstinner** [comment]
> @methane methane closed this 5 hours ago 

Well done! That's a great achievement!
