### ISSUE TITLE
Add combined opcodes

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#87850]
BPO | [43684](https://bugs.python.org/issue43684)
--- | :---
Nosy | @gvanrossum, @tim-one, @rhettinger, @terryjreedy, @gpshead, @markshannon, @ericsnowcurrently, @serhiy-storchaka, @pablogsal, @brandtbucher, @isidentical
PRs | <li>python/cpython#25090</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-03-31.22:40:32.519>
labels = ['3.10', 'performance']
title = 'Add combined opcodes'
updated_at = <Date 2021-04-06.21:41:49.532>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-06.21:41:49.532>
actor = 'gvanrossum'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = []
creation = <Date 2021-03-31.22:40:32.519>
creator = 'gvanrossum'
dependencies = []
files = []
hgrepos = []
issue_num = 43684
keywords = ['patch']
message_count = 11.0
messages = ['389939', '389967', '390101', '390104', '390105', '390109', '390263', '390292', '390350', '390373', '390378']
nosy_count = 11.0
nosy_names = ['gvanrossum', 'tim.peters', 'rhettinger', 'terry.reedy', 'gregory.p.smith', 'Mark.Shannon', 'eric.snow', 'serhiy.storchaka', 'pablogsal', 'brandtbucher', 'BTaskaya']
pr_nums = ['25090']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'performance'
url = 'https://bugs.python.org/issue43684'
versions = ['Python 3.10']
```

</p></details>

**Comment by iritkatriel** [comment]
We now have POP_JUMP_IF_NONE and LOAD_FAST__LOAD_FAST. So most of the ideas here are implemented, and a few of the others were rejected.

If nobody will object I will close this as completed.
