### ISSUE TITLE
Use syntactically correct examples on abc package page

### ISSUE THREAD

**Issue by d5df7fb9-1e9d-40e1-8473-77e8187d226c** [python/cpython#87864]
BPO | [43698](https://bugs.python.org/issue43698)
--- | :---
Nosy | @corona10, @miss-islington, @greatvovan, @sobolevn
PRs | <li>python/cpython#30502</li><li>python/cpython#30917</li><li>python/cpython#30918</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-01.18:18:39.308>
labels = ['type-bug', '3.8', '3.9', '3.10', 'docs']
title = 'Use syntactically correct examples on abc package page'
updated_at = <Date 2022-01-26.12:42:42.831>
user = 'https://github.com/greatvovan'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-26.12:42:42.831>
actor = 'miss-islington'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-04-01.18:18:39.308>
creator = 'Vladimir Ryabtsev'
dependencies = []
files = []
hgrepos = []
issue_num = 43698
keywords = ['patch']
message_count = 5.0
messages = ['390004', '410157', '411727', '411746', '411747']
nosy_count = 5.0
nosy_names = ['docs@python', 'corona10', 'miss-islington', 'Vladimir Ryabtsev', 'sobolevn']
pr_nums = ['30502', '30917', '30918']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43698'
versions = ['Python 3.8', 'Python 3.9', 'Python 3.10']
```

</p></details>

### Linked PRs
* gh-103312
* gh-103442

**Comment by slateny** [comment]
Should [this](https://github.com/python/cpython/blob/db0b455ff482df68f331411bf22b3e5829398280/Doc/library/functions.rst?plain=1#L1636) ([docs](https://docs.python.org/3/library/functions.html#staticmethod)) be changed as well?

**Comment by sobolevn** [comment]
(misclick, sorry)

@slateny yes, good catch. I will send a PR.
