### ISSUE TITLE
Document various preexisting stdlib deprecations related to import for removal in Python 3.12

### ISSUE THREAD

**Issue by brettcannon** [python/cpython#87886]
BPO | [43720](https://bugs.python.org/issue43720)
--- | :---
Nosy | @brettcannon
PRs | <li>python/cpython#25167</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/brettcannon'
closed_at = <Date 2021-04-03.22:31:33.208>
created_at = <Date 2021-04-03.20:45:08.523>
labels = ['library', '3.10']
title = 'Document various preexisting stdlib deprecations related to import for removal in Python 3.12'
updated_at = <Date 2021-04-03.22:31:33.207>
user = 'https://github.com/brettcannon'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-03.22:31:33.207>
actor = 'brett.cannon'
assignee = 'brett.cannon'
closed = True
closed_date = <Date 2021-04-03.22:31:33.208>
closer = 'brett.cannon'
components = ['Library (Lib)']
creation = <Date 2021-04-03.20:45:08.523>
creator = 'brett.cannon'
dependencies = []
files = []
hgrepos = []
issue_num = 43720
keywords = ['patch']
message_count = 2.0
messages = ['390141', '390146']
nosy_count = 1.0
nosy_names = ['brett.cannon']
pr_nums = ['25167']
priority = 'normal'
resolution = 'fixed'
stage = 'resolved'
status = 'closed'
superseder = None
type = None
url = 'https://bugs.python.org/issue43720'
versions = ['Python 3.10']
```

</p></details>

**Comment by Torxed** [comment]
On the topic of:
> these should finally go... importlib.util

If it's really getting slated in 3.12 this should be mentioned in https://docs.python.org/3.11/library/importlib.html#module-importlib.util and at the very least not be available in https://docs.python.org/3.12/library/importlib.html#module-importlib.util?

**Comment by brettcannon** [comment]
@Torxed I'm not quite sure what you're referring to, but the entire module of `importlib.util` isn't going anywhere, it just has some things _inside_ of the module that are deprecated.
