### ISSUE TITLE
[doc] add platform availabity information for os.sched_getaffinity

### ISSUE THREAD

**Issue by 1489ab23-2b7d-40a9-96e0-9f392df9685b** [python/cpython#88047]
BPO | [43881](https://bugs.python.org/issue43881)
--- | :---
Nosy | @guoci, @iritkatriel
PRs | <li>python/cpython#25459</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-17.17:12:10.500>
labels = ['3.11', 'type-feature', '3.9', '3.10', 'docs']
title = '[doc] add platform availabity information for os.sched_getaffinity'
updated_at = <Date 2022-03-29.22:25:36.593>
user = 'https://github.com/guoci'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-29.22:25:36.593>
actor = 'guoci'
assignee = 'docs@python'
closed = False
closed_date = None
closer = None
components = ['Documentation']
creation = <Date 2021-04-17.17:12:10.500>
creator = 'guoci'
dependencies = []
files = []
hgrepos = []
issue_num = 43881
keywords = ['patch']
message_count = 2.0
messages = ['416303', '416305']
nosy_count = 3.0
nosy_names = ['docs@python', 'guoci', 'iritkatriel']
pr_nums = ['25459']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'enhancement'
url = 'https://bugs.python.org/issue43881'
versions = ['Python 3.9', 'Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by encukou** [comment]
#109907 added `os.process_cpu_count`, a way to get the info on Windows as well -- and on any other platform where we know how to do this. That function is documented to return `None` if we don't know.

I'll close this issue, and the PR. Apologies for not getting to it sooner.
