### ISSUE TITLE
Cannot cleanly kill a subprocess using high-level asyncio APIs

### ISSUE THREAD

**Issue by bcb5b6b7-9c5d-409a-88e4-92c54e5aaf86** [python/cpython#88050]
BPO | [43884](https://bugs.python.org/issue43884)
--- | :---
Nosy | @asvetlov, @1st1, @sweeneyde, @kumaraditya303, @skeggse
PRs | <li>python/cpython#31611</li><li>python/cpython#32073</li>
Files | <li>[kill_subprocess.py](https://bugs.python.org/file49965/kill_subprocess.py "Uploaded as text/plain at 2021-04-19.02:47:37 by rabraham"): Kill subprocess using the high-level asyncio subprocess APIs</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-19.02:47:38.245>
labels = ['3.11', 'type-bug', 'expert-asyncio']
title = 'Cannot cleanly kill a subprocess using high-level asyncio APIs'
updated_at = <Date 2022-03-23.09:08:45.631>
user = 'https://bugs.python.org/rabraham'
```

bugs.python.org fields:
```python
activity = <Date 2022-03-23.09:08:45.631>
actor = 'kumaraditya'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['asyncio']
creation = <Date 2021-04-19.02:47:38.245>
creator = 'rabraham'
dependencies = []
files = ['49965']
hgrepos = []
issue_num = 43884
keywords = ['patch']
message_count = 6.0
messages = ['391349', '391350', '391369', '391379', '399937', '415859']
nosy_count = 6.0
nosy_names = ['asvetlov', 'yselivanov', 'rabraham', 'Dennis Sweeney', 'kumaraditya', 'skeggse']
pr_nums = ['31611', '32073']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43884'
versions = ['Python 3.11']
```

</p></details>

**Comment by gvanrossum** [comment]
I'm still trying to get my head around the issue here.

If I replace the shell command in the repro script with `"timeout 2\necho done"` I get a failure on Windows too (first `RuntimeError: Event loop is closed` from `__del__`; then a unique one, `ValueError: I/O operation on closed pipe`). The workaround/fix (`process._transport.close()`) works there too.

**Comment by gvanrossum** [comment]
Looks like the 3.10 backport has broken tests. @kumaraditya303 can you look into this? If it's too much effort we can just not backport.

**Comment by kumaraditya303** [comment]
Skipping 3.10 has it has diverged too much from main and not worth investing more time into this, 3.11 and main is fixed. Thanks @gvanrossum for reviews!

**Comment by theo-brown** [comment]
Is this meant to be fixed in 3.11+?

**Comment by gvanrossum** [comment]
Yes

**Comment by theo-brown** [comment]
Which patch? Not in 3.11.0 as far as I can tell.

**Comment by gvanrossum** [comment]
#32073 and a followup are present in 3.11.1. They may not be present in 3.11.0.

**Comment by gertvdijk** [comment]
Hmm. I came here using Google while I'm on 3.11.2 already. This happens _sometimes_ for me on a subprocess wrapped inside a task and stdin/stderr connected. It also only triggers when I am _terminating_ a process myself, instead killing it or letting the loop killing it.

Found this when hitting random test failures on 3.11.2 and created the minimal reproducer below.

```python3
import asyncio
import logging


async def myfunc_inner() -> None:
    subprocess_task = asyncio.create_task(
        asyncio.create_subprocess_exec(
            "sleep",
            "10",
            # seems to be relevant; unable to trigger without stdout/stderr connected
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
        )
    )
    proc = await subprocess_task

    try:
        await asyncio.wait_for(proc.wait(), timeout=0.02)
    except (asyncio.TimeoutError, asyncio.CancelledError):
        logging.info("Timeout on subprocess command, terminating.")
        # unable to trigger with proc.kill() or without terminating it.
        proc.terminate()
        return
    else:
        logging.info(f"process exited with {proc.returncode}]")


# unable to trigger without nested task.
async def myfunc_outer() -> None:
    await asyncio.wait_for(myfunc_inner(), timeout=1.0)


if __name__ == "__main__":
    logging.basicConfig(level=logging.DEBUG)
    loop = asyncio.get_event_loop_policy().new_event_loop()
    loop.run_until_complete(myfunc_outer())
    loop.close()
```

Running this in a shell loop 200 times, this gives ~ 1-10 failures per loop, looks random.

```console
$ for i in `seq 1 200`; do python proctimeout.py; done
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f5bff42a2a0>
Traceback (most recent call last):
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/unix_events.py", line 558, in close
    self._close(None)
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/unix_events.py", line 582, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
WARNING:asyncio:Loop <_UnixSelectorEventLoop running=False closed=True debug=False> that handles pid 419211 is closed
Exception ignored in: <function BaseSubprocessTransport.__del__ at 0x7f7dffc162a0>
Traceback (most recent call last):
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_subprocess.py", line 126, in __del__
    self.close()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_subprocess.py", line 104, in close
    proto.pipe.close()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/unix_events.py", line 558, in close
    self._close(None)
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/unix_events.py", line 582, in _close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 761, in call_soon
    self._check_closed()
  File "/home/gert/.pyenv/versions/3.11.2/lib/python3.11/asyncio/base_events.py", line 519, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
DEBUG:asyncio:Using selector: EpollSelector
Timeout on subprocess command, terminating.
[...]
```

Either removing `proc.terminate()` _or_ replacing it with `proc.kill()` makes the traceback disappear. 🤷🏼 

Am I doing something wrong here or hitting a corner case that's not tackled by this bugfix? Thanks! 🙏🏼

**Comment by gertvdijk** [comment]
> You are missing `await proc.wait()` after terminating the process, adding that fixes it.

Are you sure? It's also not included in *Here’s an example of how asyncio can run a shell command and obtain its result*, here: https://docs.python.org/3/library/asyncio-subprocess.html#

Note that I'm already awaiting the process result with `communicate()` and `wait()` says this ([here](https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.subprocess.Process.wait)):

> Use the [communicate()](https://docs.python.org/3/library/asyncio-subprocess.html#asyncio.subprocess.Process.communicate) method when using pipes to avoid this condition.

>  Anyways this is not related to this fix so create a new issue if you still face the issue.

Sorry for the noise then, but to me it sounds exactly the same still.

**Comment by kumaraditya303** [comment]
You are wrapping `proc.communicate()` in `wait_for` so it gets cancelled before it had to chance to call `self.wait()`. See the source code.  The docs are for directly awaiting the `proc.communicate()` which doesn't work  in case of `wait_for`.
