### ISSUE TITLE
array.array should remain immutable: add Py_TPFLAGS_IMMUTABLETYPE flag

### ISSUE THREAD

**Issue by gvanrossum** [python/cpython#88074]
BPO | [43908](https://bugs.python.org/issue43908)
--- | :---
Nosy | @gvanrossum, @vstinner, @tiran, @markshannon, @serhiy-storchaka, @gvanrossum, @corona10, @pablogsal, @miss-islington, @shihai1991, @erlend-aasland, @shreyanavigyan
PRs | <li>python/cpython#25520</li><li>python/cpython#25696</li><li>python/cpython#25697</li><li>python/cpython#25710</li><li>python/cpython#25714</li><li>python/cpython#25743</li><li>python/cpython#25792</li><li>python/cpython#25816</li><li>python/cpython#26115</li><li>python/cpython#26351</li><li>python/cpython#26766</li><li>python/cpython#27001</li>
Files | <li>[patch.diff](https://bugs.python.org/file49970/patch.diff "Uploaded as text/plain at 2021-04-22.08:20:29 by @erlend-aasland")</li><li>[apply-to-all.diff](https://bugs.python.org/file49980/apply-to-all.diff "Uploaded as text/plain at 2021-04-23.19:49:28 by @erlend-aasland")</li><li>[list.txt](https://bugs.python.org/file49987/list.txt "Uploaded as text/plain at 2021-04-26.10:24:34 by @erlend-aasland")</li><li>[apply-to-all.diff](https://bugs.python.org/file49990/apply-to-all.diff "Uploaded as text/plain at 2021-04-27.06:31:28 by @shreyanavigyan"): modified</li><li>[tests_log.txt](https://bugs.python.org/file49994/tests_log.txt "Uploaded as text/plain at 2021-04-27.15:52:25 by @shreyanavigyan")</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = 'https://github.com/vstinner'
closed_at = None
created_at = <Date 2021-04-21.18:52:19.855>
labels = ['type-bug', 'library', '3.10', '3.11']
title = 'array.array should remain immutable: add Py_TPFLAGS_IMMUTABLETYPE flag'
updated_at = <Date 2022-01-26.17:39:44.786>
user = 'https://github.com/gvanrossum'
```

bugs.python.org fields:
```python
activity = <Date 2022-01-26.17:39:44.786>
actor = 'vstinner'
assignee = 'vstinner'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-04-21.18:52:19.855>
creator = 'gvanrossum'
dependencies = []
files = ['49970', '49980', '49987', '49990', '49994']
hgrepos = []
issue_num = 43908
keywords = ['patch']
message_count = 120.0
messages = ['391540', '391578', '391582', '391584', '391585', '391595', '391596', '391597', '391598', '391600', '391636', '391701', '391720', '391728', '391730', '391756', '391816', '391846', '391866', '391867', '391868', '391895', '391901', '391918', '391922', '391930', '391932', '391933', '391935', '391938', '391946', '391947', '391954', '391959', '391960', '391963', '391964', '391971', '391993', '392029', '392038', '392076', '392079', '392080', '392083', '392085', '392086', '392087', '392088', '392089', '392092', '392098', '392101', '392103', '392105', '392236', '392237', '392238', '392240', '392247', '392248', '392250', '392251', '392262', '392263', '392264', '392283', '392284', '392285', '392286', '392287', '392288', '392311', '392312', '392314', '392316', '392318', '392324', '392325', '392389', '392402', '392403', '392407', '392408', '392409', '392410', '392413', '392416', '392420', '392421', '392422', '392430', '392439', '392440', '392441', '392443', '392445', '392446', '392488', '392638', '392670', '392671', '392693', '393618', '394314', '394315', '394319', '395178', '395983', '395988', '396829', '396830', '397134', '397163', '397164', '397170', '397171', '397232', '411782', '411784']
nosy_count = 12.0
nosy_names = ['gvanrossum', 'vstinner', 'christian.heimes', 'Mark.Shannon', 'serhiy.storchaka', 'Guido.van.Rossum', 'corona10', 'pablogsal', 'miss-islington', 'shihai1991', 'erlendaasland', 'shreyanavigyan']
pr_nums = ['25520', '25696', '25697', '25710', '25714', '25743', '25792', '25816', '26115', '26351', '26766', '27001']
priority = None
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43908'
versions = ['Python 3.10', 'Python 3.11']
```

</p></details>

**Comment by erlend-aasland** [comment]
> > Should the immutable flag also be applied to the heap types converted in and before Python 3.9 before closing this issue?
> 
> I don't think that Python 3.9 should be changed. It's too late. IMO this issue is not important enough to introduce a new type flag in a minor Python 3.9.x bugfix release. I suggest to close this issue.

3.9 has now entered security-only mode; suggesting to close this issue.

**Comment by vstinner** [comment]
Right, I closed the issue.

**Comment by gpshead** [comment]
FYI a question related to this new flag has arisen: https://discuss.python.org/t/immutable-types-with-mutable-bases/17764
