### ISSUE TITLE
cgi.parse_header does not handle escaping correctly

### ISSUE THREAD

**Issue by 0fec258e-630d-400a-b253-79f32338bbb9** [python/cpython#88076]
BPO | [43910](https://bugs.python.org/issue43910)
--- | :---
Nosy | @msg555
PRs | <li>python/cpython#25519</li>

<sup>*Note: these values reflect the state of the issue at the time it was migrated and might not reflect the current state.*</sup>

<details><summary>Show more details</summary><p>

GitHub fields:
```python
assignee = None
closed_at = None
created_at = <Date 2021-04-22.08:03:45.653>
labels = ['type-bug', 'library', '3.10']
title = 'cgi.parse_header does not handle escaping correctly'
updated_at = <Date 2021-04-22.08:14:58.280>
user = 'https://github.com/msg555'
```

bugs.python.org fields:
```python
activity = <Date 2021-04-22.08:14:58.280>
actor = 'msg555'
assignee = 'none'
closed = False
closed_date = None
closer = None
components = ['Library (Lib)']
creation = <Date 2021-04-22.08:03:45.653>
creator = 'msg555'
dependencies = []
files = []
hgrepos = []
issue_num = 43910
keywords = ['patch']
message_count = 1.0
messages = ['391580']
nosy_count = 1.0
nosy_names = ['msg555']
pr_nums = ['25519']
priority = 'normal'
resolution = None
stage = 'patch review'
status = 'open'
superseder = None
type = 'behavior'
url = 'https://bugs.python.org/issue43910'
versions = ['Python 3.10']
```

</p></details>

**Comment by AlexWaygood** [comment]
The cgi module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements to the module will no longer be accepted. I am therefore closing this issue.

**Comment by AlexWaygood** [comment]
> The cgi module is now deprecated following the acceptance of PEP 594, so bugfixes and improvements to the module will no longer be accepted. I am therefore closing this issue.

Cc. @msg555
